### ISSUE TITLE
Button to toggle script panel is not shown when reading reference documentation

### ISSUE THREAD

**Issue by nsrCodes** [godotengine/godot#52529]
### Godot version

v3.3.2

### System information

Pop!_OS 21.04

### Issue description

If you have the scripts panel hidden and `ctrl + click` on something to refer the docs, it is not directly clear how to get back to working on the script from where you referred the docs.

I was expecting the toggle button to also be present when reading the docs

*Workarounds*
1. Shortcut: `ctrl + backslash` to toggle the pannel. 
2. Shortcut: `ctrl + w` to close the docs.
3. Toggle the pannel from **File -> Toggle Script Panel**

https://user-images.githubusercontent.com/57226514/132807376-f2316a0a-9096-479f-9f25-a89d7734d444.mp4

I used the shortcut in the video to get back to where I was.

### Steps to reproduce

There are many ways to see how this would be frustrating for a new user.

1. Open any script in the godot editor
2. Hide the Scripts panel
3. Navigate to the reference documentation either by clicking on the dedicated button or by clicking on any attribute/method while holding `ctrl`

You will find no visual way to get back to the script you were working on. (except the option under file)

**Comment by sairam4123** [comment]
Click this to get back, 
![image](https://user-images.githubusercontent.com/61322406/132834315-9ae11381-647e-47c3-9993-3e350697cc4a.png)

**Comment by Calinou** [comment]
cc @Chaosus, who I remember added this script panel toggle button.

**Comment by Chaosus** [comment]
I'm a bit retired now since I working on my projects, maybe I should choose some time and implements it - just need to add a status bar with that button to docs and VisualScripts.

**Comment by nsrCodes** [comment]
@Chaosus I think you mentioned in [this comment](https://github.com/godotengine/godot/pull/34364#issuecomment-566677625) on #34364 that you took care of this by, **AFAIU**, passing the `toggle_scripts_panel` function a reference of the `CodeTextEditor` object and then handling the case for the script edtor explicitly. But that does not take care of the other two cases... right? 

The fixes that follow that PR (#34437) moved the toggle function from `CodeTextEditor` to `ScriptTextEditor` (*I guess to fix some inheritence design*), which, I am guessing, further limited this to the script editor.
*It is clear in the `update_toggle_scripts_button` in `CodeTextEditor` that it only updates the toggle_button in `ScriptEditor`*

> Please correct me if I am wrong, I just tried to understand the current implementation by seeing the previous commits so that maybe I could help with this.
