### ISSUE TITLE
OpenGameArt integration in asset manager

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#5253]
[OpenGameArt](http://opengameart.org) is by far the best resource around for assets released under free licenses (except for samples, but [Freesound](http://freesound.org/) sadly has a lot of NC and ND stuff, but since they have an API they're also worth taking a look at).

Right now it could easily be done via scraping (with the webmaster's consent, obviously, otherwise it's just rude and unethical) or by mirroring all the content on the Godot server (and since it's all under free licenses, it would not be an issue, and it would also spare them some bandwidth costs) but the people at [OpenGameArt](http://opengameart.org) a while ago talked about releasing their site under a FLOSS license if a funding goal was reached, which would allow an API to be implemented.

I suggest therefore that OpenGameArt is integrated into Godot.

**Comment by vnen** [comment]
Without a proper API it'll be somewhat hard to download from OGA. I don't know where you get the idea about the funding and open sourcing, I know it was suggested [in reddit](https://www.reddit.com/r/gamedev/comments/1d11ir/i_run_opengameartorg_and_im_looking_at_options_to/), but that was 3 years ago. I didn't see any news about this, though I might have missed it.

**Comment by paper-pauper** [comment]
>  I don't know where you get the idea about the funding and open sourcing

It was in their stretch goals (on Patreon, IIRC) a while ago.

**Comment by paper-pauper** [comment]
Indeed, it's in their [Patreon page](https://www.patreon.com/opengameart?ty=h) goal of $1500 ($423 raised so far):

> Open sourcing a site like OpenGameArt.org isn't as simple as you might think.  OGA runs on top of Drupal, which stores a lot of information necessary for the site to function in the site database, which means that in order for someone to download a copy of OGA that works well enough that development can be done, the database needs to be included.  Unfortunately, the database is a) way too big to allow people to download without bringing the server to its knees, and b) contains personal information such as email addresses and hashed passwords, which can't be released to the public.  What this means is that I'll have to write and maintain a program that sanitizes and shrinks the OGA database so that it will be easy to download and not compromise anyone's personal information.  As new features are added to the site (along with necessary database schema changes), this program will need to be kept up to date so that the database remains properly sanitized, which means that not only is open sourcing OGA a large initial effort, it will require that I devote some amount of time to it continuously just to make sure people can always get the latest working version.  In the event that we receive code contributions (and open sourcing your code is not in any way a guarantee of that), I'll need to spend time coordinating developing, cleaning up code, coaching potential developers (Drupal has a hefty learning curve), and providing support to people wanting to get a working copy of the site running on their own machine.  Ultimately, this may result in a lot of new features, but going open source is a time investment; you can only get back what you put in.

**Comment by vnen** [comment]
Well, I saw that but 1) it says about open-sourcing, not about API (that'd have to be developed independently) and 2) they didn't reach the goal yet.

Our Asset Library is not even released yet, it needs some polishing. So it might (or not) eventually also allow artistic assets, but for now this will remain in the open.

**Comment by Calinou** [comment]
As the [Godot Asset Library](https://godotengine.org/asset-library/) has been online for a while now, I'm closing this.

OpenGameArt integration could be added by a third-party editor plugin or GDNative.
