### ISSUE TITLE
Godot's custom theme property makes Godot crash on startup.

### ISSUE THREAD

**Issue by autofool** [godotengine/godot#52530]
### Godot version

3.3.3 stable

### System information

Linux

### Issue description

After I set custom theme in Godot interface settings, editor should save and restart the editor but it closes and doesn't start automatically. After that Starting Godot manually all projects seems to crash on start up. It only works till project manager shows up.

### Steps to reproduce

1. Open Godot with any project.
2. Create new theme resource.
3. Create theme from currant editor theme. (This step is necessary. Using theme file with default theme works fine. That means new theme files created aside from defaults are missing something or messing up editor somehow.)
4. Save the theme.
4. Go to Editor Settings > Interface > Theme. Then set the saved theme as custom theme. 
5. Click on save and restart popup at bottom.
6. Start Godot again.

**Comment by Calinou** [comment]
Related to #48477.

**Comment by pycbouh** [comment]
This is fixed in 3.x by https://github.com/godotengine/godot/pull/51648.
