### ISSUE TITLE
Rename "trackpad hint" to something more intuitive like "Enable 3D trackpad"

### ISSUE THREAD

**Issue by sunnystormy** [godotengine/godot#5254]
I recently checked the history for the spatial_editor_plugin class and saw that somebody had made the feature I added optional, however, I wasn't able to easily verify because it was named something that I don't think is intuitive for users: "trackpad hint".

Could we please rename this something much more obvious? "Trackpad hint" doesn't describe the feature in question, in fact, it sounds more like a "help" or "accessibility" thing for the editor. I've suggested an alternative in the title of this ticket, and would be open to discussion about what the new name should be.

**Comment by Zylann** [comment]
FYI, the reason why I named it this way was because users needing it had difficulty using a trackpad in the 3D editor. But indeed it should also target users that don't have a middle button. Or actually describe what it actually does: panning without using a mouse button.
