### ISSUE TITLE
fps drops

### ISSUE THREAD

**Issue by drcucaracha** [godotengine/godot#52547]
### Godot version

3.3 stable / 3.4 beta 4

### System information

windows 10 gles3 / gles2 gt 730 nvidia

### Issue description

when dof far blur / dof near blur / ssao is activated there are drops of more than 900 fps in gles3 and even more in gles2 reaching even drops of more than 2500 fps with vsync mode deactivated, I have no idea if someone already reported it or not

### Steps to reproduce

create a fps counter and just test turning effects on and off

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/7145780/test.zip)

**Comment by clayjohn** [comment]
Can you provide a little more information, like what FPS is like with each effect enabled?

For reference saying FPS dropped by 900 doesn't mean anything by itself because of the non-linear nature of FPS. For example, FPS dropping from 901 FPS to 1 FPS is much worse than a drop from 9900 to 9000.

A more valuable indicator of performance is frame time in ms (i.e. 1/FPS).
For example, an FPS of 901 corresponds to a frame time of 1.1 ms while an FPS of 1 corresponds to a 1000ms frame time.
In my earlier example an FPS of 9900 is 0.101ms while an FPS of 9000 is 0.111 ms. You can see that even with a huge FPS difference the actual performance difference is very small.

**Comment by drcucaracha** [comment]
hello thanks for answering, just call the function Engine.get_frames_per_second () and pressing the tab above changes the camera one with the dof far blur activated and another camera with the dof far blue deactivated and shows a wide fps gap when it is active and when it is not

**Comment by clayjohn** [comment]
Can you please clarify what exactly is the problem you are running into?

SSAO and DOF blur are very expensive post-processing effects, so it is expected that they would reduce your FPS when you turn them on. A reduction in performance isn't by itself a bug. But if, on your hardware, the drop is more extreme than it is on other hardware, that would be considered a bug and it may be something we can resolve. 

As a baseline, on my laptop (intel integrated graphics, business class) I get about 400 fps without effects and about 120 FPS with effects. Those numbers are exactly what I would expect given how weak my computer is.

**Comment by Calinou** [comment]
A GT 730 is a pretty slow GPU by today's standards, and is better used with SSAO and SSR disabled because of this.

**Comment by drcucaracha** [comment]
ok I did not know that the engine was oriented to high performance PCs with 3090 graphics for triple A games I thought that this path was only for a real person who coincidentally their games if they work quite fluently with this phonics and they are not low poly they can indulge in close this topic they already clarified my doubts towards where is the focus of the engine

**Comment by Calinou** [comment]
> ok I did not know that the engine was oriented to high performance PCs with 3090 graphics for triple A games I thought that this path was only for a real person who coincidentally their games if they work quite fluently with this phonics and they are not low poly they can indulge in close this topic they already clarified my doubts towards where is the focus of the engine

If you want to target old or low-end hardware, you need to tone down the graphics settings. This applies to any rendering engine, not just Godot. For the record, Unity's HDRP and UE4 will also struggle running on a GT 730, even at low settings.

Either way, I'll close this as this is not an issue that Godot can resolve.
