### ISSUE TITLE
GDScript: Spurious unassigned variable warning

### ISSUE THREAD

**Issue by ZuBsPaCe** [godotengine/godot#52551]
### Godot version

v4.0.dev (68563b576)

### System information

Windows 10

### Issue description

Following code shows 2 warnings, indicated by the comments:

```gdscript
var m1
var m2 = 22
var m3: String
var m4: String = "44"

func _ready():
	# Warning on next line: The variable 'loc5' was used but never assigned a value.
	var loc5
	var loc6 = 66
	
	# Warning on next line: The variable 'loc7' was used but never assigned a value.
	var loc7: String
	var loc8: String = "88"

	m1 = 11
	m3 = "33"

	loc5 = 55
	loc7 = "77"

	prints(m1, m2, m3, m4, loc5, loc6, loc7, loc8)
	print("OK")
```

* The test outputs "11 22 33 44 55 66 77 88" as expected.
* The warnings should not be there, because loc5 and loc7 are initialized later on.
* The warnings are only shown for local variables, which are not initialized at declaration time. Warnings are not shown for member variables.
* The gdscript unit test modules\gdscript\tests\scripts\parser\features\variable_declaration.gd asserts, that this warning must be shown. See variable_declaration.out. This is wrong.

I'm working on a pull request. Should be there soon.

### Steps to reproduce

Create a script with the code shown above in the editor and look at the warnings.

### Minimal reproduction project

[SpuriousUnassignedVariableWarningGodot4.zip](https://github.com/godotengine/godot/files/7146023/SpuriousUnassignedVariableWarningGodot4.zip)

**Comment by ZuBsPaCe** [comment]
Sorry for the multiple force pushes. Were just code style issues.

**Comment by Calinou** [comment]
> Sorry for the multiple force pushes. Were just code style issues.

No worries :slightly_smiling_face: Our GitHub Actions setup now interrupts unfinished jobs automatically when you make a job, so it doesn't hog up CI resources anymore.
