### ISSUE TITLE
Editor softlock when calling `BakedLightmap.bake()`

### ISSUE THREAD

**Issue by YellowAfterlife** [godotengine/godot#52552]
### Godot version

v3.4.beta4.official [6a058cbf3]

### System information

Windows 10, GLES3

### Issue description

While trying to automate a common point of annoyance (re-import geometry ➜ select MeshInstance ➜ click Generate UV2 ➜ select BakedLightmap ➜ click Bake Lightmaps), I stumbled upon a peculiar thing: even though I can still bake lightmaps by clicking on Bake Lightmaps button, attempting to do so myself (by calling BakedLightmap's `bake` method) subsequently softlocks the editor.

### Steps to reproduce

1. Open the attached project
2. Open TestScene.tscn
2. Click on `qodot_helper`
3. Click "Bake" on top toolbar
4. Note the editor get stuck after baking (_and_ returning a status code as normal)
![godot-bake](https://user-images.githubusercontent.com/731492/132908255-abec8035-5600-4bf1-98d4-dd8b5196d92d.gif)

Bonus: click on "Make" instead (which invokes Qodot's "full build" and _then_ baking) to hard crash the editor with an access violation

### Minimal reproduction project

[QodotTest.zip](https://github.com/godotengine/godot/files/7145959/QodotTest.zip)

**Comment by Calinou** [comment]
> re-import geometry ➜ select MeshInstance ➜ click Generate UV2

You can avoid doing this manually every time by setting the light bake option in the MeshInstance's Import dock to **Gen Lightmaps**, then clicking **Reimport**.

**Comment by YellowAfterlife** [comment]
I eventually settled on binding a script to BakedLightmap itself since I can ask Qodot to re-generate the level (and then generate UV2s) just fine - it's only baking that implodes
![image](https://user-images.githubusercontent.com/731492/132923514-408fa34a-27f9-4ad6-aad5-6f3ab04ccb2a.png)

**Comment by Calinou** [comment]
cc @JFonS

**Comment by JFonS** [comment]
I opened #52586 with a fix for the "Bake" softlock.

I also took a quick look at the "Make" crash and, by the look of things, during your call to `run_build_steps()` either the script or the node itself gets deleted and the final `yield` fails as it's trying to resume execution on a script that doesn't exist anymore.

GDscript is not my area of expertise, so I don't really know what's the best solution here, but it should probably be handled in an issue of its own :)

**Comment by akien-mga** [comment]
Fixed by #52586.
