### ISSUE TITLE
Path3D selection of curve point to set point_in/out is broken in 4.0 Same for polygon point.

### ISSUE THREAD

**Issue by stebulba** [godotengine/godot#52568]
### Godot version

4.0 dev

### System information

Ubuntu 16.04 LTS

### Issue description

When we want set up the point_in or point_out from the path_editor_plugin. You use normally  click on the handle in same time you push [SHIFT]. But with this bug you select or set_up your point_in and out of a different point of your path3D. For exemple, you  select the curve point # 10 and when you push [shift] you set_up your curve point # 3
The focus is not on the selected point.

https://user-images.githubusercontent.com/26193340/132943340-2f2114a7-2850-4455-a303-ca7b28cd0738.mp4

Other thing, the selection and drawing of the polygon is broken too.

https://user-images.githubusercontent.com/26193340/132943780-9e4e7ff2-0a4f-4cf7-9fa6-10ce6fbd3eea.mp4

### Steps to reproduce

Make a path3D in CSGPolygon3D. 
Use [shift] when you select a handle, move your mouse and the focus will be on a different handle, different point of the path3D.

**Comment by Calinou** [comment]
cc @JFonS

**Comment by Calinou** [comment]
This was confirmed by @nonunknown on the Godot contributors chat.
