### ISSUE TITLE
Inferred parameter defaulting to null turns parameter value null

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#52569]
### Godot version

3.3 stable

### System information

linux

### Issue description

As title, inferred to null turns values all into null.

I appreciated why it's doing it, but it should either not be trying to infer null to a type or more likely it should be generating an error. The justification of this bug is typing ':' is pretty much the way of doing things for most people without thought and coder is unaware the data is silently being nulled.

```
extends Node2D

var data=Node.new()

func _ready() -> void:
	test_bug()
	
func test_bug():
	call1("a","b",data)	#this is valid, data id is output
	call1("a","b","c")	#this is valid, c is output

	call2("a","b",data)	#this is invalid, data is null
	call2("a","b","c")	#this is invalid, data is null
	
func call1(a, b, c=null):
	print(a,b,c)
	
func call2(a, b, c:=null):
	print(a,b,c)
	
```

### Steps to reproduce

Run the code.

### Minimal reproduction project

just paste and go, i didn't think necessary to attach project.

**Comment by Calinou** [comment]
Should type inference be allowed in function declarations' default parameters? I think it should be a syntax error instead.

**Comment by jmb462** [comment]
``var c:=null`` raise an error : ``Could not infer the type of the variable "c" because the initial value is "null"``.

Shouldn't be the same for function parameters ?

**Comment by name-here** [comment]
@Calinou While type inference is harder to read in some cases, I don't think that justifies disabling it in setting default parameters.  It creates an inconsistency with setting values, and on top of that, sometimes inference is not harder to read and instead reduces redundancy.  For example, something like the following:

```
func test1( a, b := Vector3() ):
    print( a, b )
```

instead of

```
func test2( a, b: Vector3 = Vector3() ):
    print( a, b )
```

**Comment by Calinou** [comment]
@name-here Let's move the discussion about type inference to a proposal: https://github.com/godotengine/godot-proposals/issues/3283

**Comment by chucklepie** [comment]
OK, but currently I'd see this specific thing as a bug as one part of the
system disallows null inference and another doesn't. With a side effect of
nulling all parameter data.

That proposal also didn't cover null.

**Comment by Calinou** [comment]
> That proposal also didn't cover null.

The `null` part is a bug, and can be resolved independently of the proposal I opened.
