### ISSUE TITLE
"Border Width" properties for StyleBoxFlat are in the wrong order

### ISSUE THREAD

**Issue by ShatReal** [godotengine/godot#52577]
### Godot version

3.4.beta4

### System information

Windows 10

### Issue description

"Border Width" properties are in the order left, top, right, and bottom. "Expand Margin" and "Content Margin" properties are in the order left, right, top, and bottom.

### Steps to reproduce

1. Make a new StyleBoxFlat.
2. Expand the Border Width, Expand Margin, and Content Margin properties.
3. Observe.
![image](https://user-images.githubusercontent.com/69117768/132954997-65e62ff9-b5a1-41da-93e6-5e3001df9908.png)

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot-proposals/issues/2141. That said, properties can be reordered in the inspector without breaking compatibility with existing projects.
