### ISSUE TITLE
Mono build error MSB3248 on Manjaro/Arch (due to broken distribution-provided package)

### ISSUE THREAD

**Issue by Scrubbin** [godotengine/godot#52581]
### Godot version

Mono 3.3.3 stable

### System information

Manjaro (Arch) Linux

### Issue description

trying to compile/run/export on any godot project gives build error:
`/usr/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(2198,5): error MSB3248: Parameter "AssemblyFiles" has invalid value "/usr/lib/mono/4.5-api/mscorlib.dll". Could not load file or assembly 'System.Reflection.Metadata, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.`

### Steps to reproduce

-followed official instructions for compiling on x11 [here](https://docs.godotengine.org/en/stable/development/compiling/compiling_for_x11.html)
scons version 4.2.0
mono 6.12.0.122-1 [here](https://archlinux.org/packages/extra/x86_64/mono/)
mono-msbuild 16.10.1 [here](https://archlinux.org/packages/community/x86_64/mono-msbuild/)

### Minimal reproduction project

fresh godot 3.3.3, empty project with c# script fails to build/run/export.

### Fix
**--This issue is resolved, but requires a manual workaround fix. The msbuild package on Arch is broken which breaks godot's build process**

-follow steps 3-6 on [this](https://github.com/KSP-CKAN/CKAN/wiki/Installing-CKAN-on-Arch#arch-user-repository) page give directions to manually patch the broken 'System.Reflection.Metadata.dll' file in msbuild 
-the thread [here](https://githubmemory.com/repo/KSP-CKAN/CKAN/issues/3361?page=1) details why this issue is occuring.

This isn't specifically a Godot issue, but i'm hoping to share the issue and fix for anyone else interested until it's properly resolved.
Please feel free to close this issue if this is the wrong spot to post.

**Comment by akien-mga** [comment]
This needs to be reported to Arch Linux maintainers, we can't work it around if their packaged Mono is broken.

**Comment by geekley** [comment]
I'm having same problem on Kubuntu 21.10 after last mono update.
Godot v3.4.4.stable.mono.official [419e713a2]
```sh
$ mono --version
Mono JIT compiler version 6.12.0.179 (tarball Tue May 17 21:33:45 UTC 2022)
[...]
$ apt-cache show mono-devel 
Package: mono-devel
Source: mono
Version: 6.12.0.179-0xamarin3+ubuntu2004b1
Architecture: all
[...]
```
/usr/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(2101,5): error MSB3248: Parameter "AssemblyFiles" has invalid value "/usr/lib/mono/4.7.2-api/mscorlib.dll". Could not load file or assembly 'System.Reflection.Metadata, Version=1.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
