### ISSUE TITLE
SkeletonIK "!is_inside_tree()" Error

### ISSUE THREAD

**Issue by FazerGamer** [godotengine/godot#52589]
### Godot version

3.3 stable

### System information

Windows 10, Gles3

### Issue description

Every time I try to change a scene with the SkeletonIK node the Output would error with: 
![3](https://user-images.githubusercontent.com/48662882/132968255-eeced2b1-84aa-45a8-a55a-5d14d931481c.png)

### Steps to reproduce

In the "Minimal Project" I listed, there should be a Scene labeled as "Spatial.tscn"
Open the scene, it should throw the error upon opening it.

### Minimal reproduction project

[Godot_IKScene_Bug.zip](https://github.com/godotengine/godot/files/7148870/Godot_IKScene_Bug.zip)

**Comment by Calinou** [comment]
This was also pointed out in https://github.com/godotengine/godot/issues/48508, but I'll leave this issue open as it may be fixable independently.
