### ISSUE TITLE
4.0 Freeze when dragging and dropping layer property in tilemap node

### ISSUE THREAD

**Issue by Racinettee** [godotengine/godot#52590]
### Godot version

4.0.dev 80aba79706

### System information

Kubuntu 21.04 - Lenovo IdeaPad S145 - Intel UHD Graphics 610

### Issue description

In 4.0 dev when using the layers property of the tile map node, if I add a new layer, and then drag and drop the layer above the original, the godot editor becomes unresponsive and on low spec hardware, causes the machine to stutter.
When I encountered this issue initially, there was an assertion error in the console repeating over - the assertion was not printed to the console on subsequent reproductions but vaguely it was:
`ERROR: something.nil == something && color == RED is true`

### Steps to reproduce

Using the minimal reproduction project:

1. Open Node2D.tscn
2. Select the TileMap
3. In the property inspector drop down the layers
4. Click Add Element
5. Attempt to drag and drop the new layer properties above the original
6. Godot becomes unresponsive
   - it seemed like the assertion in the original repro was possibly going to print out indefinitely
   - possibly check the terminal for rapidly printing assertions

### Minimal reproduction project

[TileMapBug.zip](https://github.com/godotengine/godot/files/7148600/TileMapBug.zip)

**Comment by Calinou** [comment]
cc @groud

**Comment by rileylyman** [comment]
I pushed a fix up in #52622, let me know if this solves the issue for you :)

**Comment by Racinettee** [comment]
It does, thx @rileylyman
