### ISSUE TITLE
Duplicating gridmap area unselects the gridmap node, hence stops the user from further editing

### ISSUE THREAD

**Issue by nsrCodes** [godotengine/godot#52608]
### Godot version

v3.3.2

### System information

Pop!_OS 21.04

### Issue description

After you copy/cut a selected area and click elsewhere to paste the selection, the grid map gets unselected and you have to click on that node again to resume editing.

https://user-images.githubusercontent.com/57226514/132998222-0a726c69-5f78-4cf9-a6ca-2dcfc6350ccc.mp4

### Steps to reproduce

1. Create a grid map node and add a mesh library
2. Place a few tiles on the map
3. Select an area of the map by holding `shift` and dragging using LMB. (*that area may not even have any tiles*)
4. Copy the area with `ctrl` + `c` (*or even cut using `ctrl`  + `x`*). Now you have the selected area copied to and floating around with your cursor.
5. Place the copy anywhere you like

Once you place the selected area, you have to click back on the gridmap node to resume editing the level

**Comment by Bimbam360** [comment]
I know this is pinging an old issue (which you're not supposed to do), but this behaviour is still present (and annoying) as recently as v4.3.dev5.official [89f70e98d]

**Comment by Nodragem** [comment]
I think it is ok to ping to confirm that it is not solved as of v.4.3 RC3? I am surprised that this bug did not receive more 👍 as it is quite a workflow blocker.

Note that this bug also makes the "paste selects" option useless.

Anyway, the good news is that I think I solved it yesterday. I am going to make a pull request now.
