### ISSUE TITLE
get_parent() returns null even though the node certainly has a parent

### ISSUE THREAD

**Issue by JorensM** [godotengine/godot#52609]
### Godot version

3.3.3.mono

### System information

Windows 10

### Issue description

This happened on my main project that I'm working on. I tried reproducing the issue in a test project and same error occured.

### Steps to reproduce

Create a node, then create a child for that node, and in the child node, add the following code:
`var parent = get_parent()

_ready():
     print(parent)`

### Minimal reproduction project

[test project.zip](https://github.com/godotengine/godot/files/7150099/test.project.zip)

**Comment by JorensM** [comment]
It appears that putting get_parent() into _ready() solves this. Maybe this is how it's supposed to work. Sorry if I got mistaken for thinking this is a bug.

**Comment by Zireael07** [comment]
Yep, this is how it's supposed to work. Ready() is the earliest you can get other nodes in the tree.

**Comment by JorensM** [comment]
> Yep, this is how it's supposed to work. Ready() is the earliest you can get other nodes in the tree.

I see. My bad!

**Comment by KoBeWi** [comment]
btw see #36832
We should have a warning for such cases.
