### ISSUE TITLE
Improve filters in AnimationTree

### ISSUE THREAD

**Issue by m4nu3lf** [godotengine/godot#5261]
**Operating system or device - Godot version:**

Godot last build

**Issue description**:

Filters in the AnimationTree are somehow conterintuitive, I think that filters can be improved.
Take for example a Blend2Node. What does it mean to filter some tracks on that node? Are you filtering the animation coming from input A or B?
I've looked at the code because I can't get the behavior I want in the animation tree, and things seem a bit confsing to me, so... My proposal is:

A filter should be a node in the animation tree on its own. The effect of filteting out a track should be to have that track for every animation sub node to have a weight of zero. For example:

```
Anim1 <----- +
             |
Anim2 <----  Blend3Node <---------- Filter<----- Blend2Node<-----Out
             |                                       |
Anim3 <----- +                             Anim4 <---+
```

If the Filter is set to filter track x, y and z, then for Anim1, Anim2, and Anim3, these tracks should have a weight of zero in the final blending.
Multiple filters should accumulate unsing an OR logic. That is a filter can only filter out tracks. Tracks that have been already filtered get no effect.

**Comment by reduz** [comment]
moving to 3.1

**Comment by akien-mga** [comment]
The old AnimationTreePlayer is now deprecated and replaced by a new AnimationTree, so I assume that this issue might be addressed to some extent. If not, it might be better to open a new issue adapting it to the status and features in the current master branch.
