### ISSUE TITLE
Autoload settings don't tell why an autoload can't be added when name is invalid

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#52631]
### Godot version

4.0-dev (c7455d9d4284958d3ffed716ae4c7e192fb1a573)

### System information

Any

### Issue description

The Autoload tab in the Project Settings disables the "Add" button when the autoload name is invalid (e.g. when it has invalid characters), but it does not tell **why** it is disabled.

![autoload-disabled-feedback](https://user-images.githubusercontent.com/5599796/133094419-2006053b-c592-45df-8d25-90579aa51b04.png)

It should have a tooltip or maybe an error message in the dialog itself telling the reason the name is incorrect. The messages already exist in the code but they are ignored in this case. While it might be obvious in some cases, like when invalid characters are added, it might be quite confusing when the name is invalid because it conflicts with an engine class.

### Steps to reproduce

1. Create an empty scene or script to use as autoload.
1. Open Project Settings dialog.
1. Select the Autoload tab.
1. In the "Path" field, select the scene or script create earlier.
1. In the "Node Name" field, type an invalid name (e.g. "Test+", invalid since "+" isn't allowed in identifier).
1. Note the "Add" button is disabled as soon as "+" is typed but there's no information why it's invalid.

### Minimal reproduction project

N/A

**Comment by jmb462** [comment]
As there is no space left for such a message, would this solution be acceptable. (Hide/show a label under the inputs)

![error_messages](https://user-images.githubusercontent.com/3649998/133117083-d5e067c7-cefb-4f09-9958-dbb2cb59bda6.gif)
(Do not take care of icons number, I was testing anout another issue with this tree)
