### ISSUE TITLE
Useless preprocessor condition

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#5263]
There's a condition for the definition (or not) of `CHARTYPE_16BITS`, but such macro is never defined in the buildsystem. A Google search only points to this repository, so it is not defined by any system either.

There are three checks for it:

* https://github.com/godotengine/godot/blob/ebbd705b63d44d6f25949f6fda9bacf8d974c8bd/core/ustring.h#L49
* https://github.com/godotengine/godot/blob/c195c0df6b36debc870216dd42e49fbda70fa861/core/variant.h#L205
* https://github.com/godotengine/godot/blob/4bb93c976c6b67b4538c8a012ea549ec24e3ac1a/core/variant.cpp#L1448

But since it isn't defined anywhere, those checks will always evaluate to `true`. So I believe they could be removed.

**Comment by neikeq** [comment]
Another one is `USE_QUAD_VECTORS`:
- https://github.com/godotengine/godot/blob/ebbd705b63d44d6f25949f6fda9bacf8d974c8bd/core/math/vector3.h#L48
- https://github.com/godotengine/godot/blob/c195c0df6b36debc870216dd42e49fbda70fa861/core/variant.h#L154

**Comment by neikeq** [comment]
What about `REAL_T_IS_DOUBLE`? Can we remove it or is it going to be an option some day?
```
core/math/math_funcs.h:#ifdef REAL_T_IS_DOUBLE
core/math/math_defs.h:#ifdef REAL_T_IS_DOUBLE
```
