### ISSUE TITLE
[GDScript 2.0] Can't access outer scope class definitions or functions from inside a class

### ISSUE THREAD

**Issue by briansemrau** [godotengine/godot#52635]
### Godot version

4.0.dev (0c2ab55a58)

### System information

Windows 10

### Issue description

You cannot access the definition of another class from the inner scope of a class. The same is true for accessing functions defined in the outer scope. See sample code below.

---

This issue is the same as #40857, #52035, but for classes/functions.

I noticed that the code that #52100 fixes handles outer scope resolution for
`GDScriptParser::ClassNode::Member::CONSTANT`,
`GDScriptParser::ClassNode::Member::ENUM_VALUE`,
`GDScriptParser::ClassNode::Member::ENUM`,
but excludes cases for
`GDScriptParser::ClassNode::Member::CLASS`,
`GDScriptParser::ClassNode::Member::FUNCTION`.
(as well as `SIGNAL` and `VARIABLE`, but those don't make sense to access from an inner class as they're instance-specific)

### Steps to reproduce

Class example:
```gdscript
class A:
    pass

class B:
    var a = A.new()
```
```
Error at (5,13): Identifier "A" not declared in the current scope.
```

Function example:
```gdscript
static func do_thing():
	return 3

class B:
	var three = do_thing()
```
```
Error at (5,17): Function "do_thing()" not found in base self.
```

**Comment by nonunknown** [comment]
@briansemrau For the class example makes totally sense, but for the function example, it doesnt make sense (so in theory the error makes sense)

to work it should be:
```gd
extends Node
class_name Test

static func do_thing():
    return 3

class B:
   var three = Test.do_thing()

```

**Comment by briansemrau** [comment]
@nonunknown Thank you, let me update the issue.

**Comment by nonunknown** [comment]
I'm sorry but I cant see another way to call a static function than calling the class that owns the static function name! even it was:
```gdscript
class B:
   var three = self.do_thing()
```
self is referring to `B` and not to `Test`

also, if it was:
```gdscript
class B:
   var three = do_thing()
```

this implies that do_thing() is a function from B and not from Test!

**Comment by briansemrau** [comment]
I get what you're saying, but I still disagree. But it's not worth me debating it. When vnen gets a chance to look at this issue I'll trust him with that design decision.

**Comment by dalexeev** [comment]
The first is fixed.

![](https://user-images.githubusercontent.com/47700418/217899340-e5c1d425-6486-4718-bb7c-12448596e37a.png)

Constants and enums are also supported:

![](https://user-images.githubusercontent.com/47700418/217901402-1977a3b6-604d-4f34-b7b0-c2b798abe16a.png)

Static functions were not supported before, you should probably open a proposal for this. But anyway, it's too late for the 4.0 milestone as it has entered the RC phase.
