### ISSUE TITLE
ConfigFile erase_section_key and erase_section don't appear to function

### ISSUE THREAD

**Issue by georgespatton** [godotengine/godot#52645]
### Godot version

3.3.3.stable

### System information

Arch Linux

### Issue description

The methods erase_section_key and erase_section don't appear to function.

https://docs.godotengine.org/en/stable/classes/class_configfile.html

Simple reproduction steps below.  

### Steps to reproduce

Given the config file (config.ini):
```
[player]

playerName="some player name"
someOtherProperty="foo bar"

```
This code reproduces the issue:
```
extends Node
var sgf = "user://config.ini"
	
func eraseProperty():
	var section = 'player'
	var key = 'playerName'
	var f = ConfigFile.new()
	var err = f.load(sgf)
	if err == OK: 
		if f.has_section_key(section, key):
			var section_keys = f.get_section_keys(section)
			var sections = f.get_sections()
			print("sections: ", sections, " section keys: ", section_keys)
			var seckey = f.erase_section_key(section, key)
			var sec = f.erase_section(section)
			print("seckey: ", seckey, " sec: ", sec)
	

```
The output is as follows, but the config.ini file is unchanged.
```
sections: [player] 
section keys: [playerName, someOtherProperty]
seckey: Null sec: Null
```

As shown, these sections do not appear to be functional.    See https://github.com/godotengine/godot-proposals/issues/238 and https://github.com/godotengine/godot/pull/32426 for the impetus on these features.  

#32426

**Comment by georgespatton** [comment]
#32426

**Comment by Calinou** [comment]
cc @AilerNX

**Comment by AilerNX** [comment]
Like when you create values, if You don't use the function `ConfigFile.save(path)` after make changes nothing will happens with the file stored!

In your example code if You add the below line after all changes will solve this.

`f.save(sgf)`

**Comment by georgespatton** [comment]
Thanks for the explanation.  The save() code is my missing step.  I created PR https://github.com/godotengine/godot-docs/pull/5252 to make this explanation well documented.  Thanks for the rapid response.
