### ISSUE TITLE
Visual glitch in the About window

### ISSUE THREAD

**Issue by floppyhammer** [godotengine/godot#52653]
### Godot version

v4.0.dev.custom_build [7cdd8629a]

### System information

Windows 11, Vulkan Clustered

### Issue description

![about_page](https://user-images.githubusercontent.com/28705694/133199848-963d3d98-1ce8-4aef-98c3-6394fa2b3c45.gif)

Doesn't matter if `Single Window Mode` is enabled or not.

### Steps to reproduce

Open the About window, and scroll up/down in the Authors or Donors tabs.

**Comment by jmb462** [comment]
Also confirmed on Windows 10

![image](https://user-images.githubusercontent.com/3649998/133206122-c195e64e-83e0-4472-9c2e-0c81a527f5e8.png)

**Comment by timothyqiu** [comment]
Duplicate of #36164.
