### ISSUE TITLE
[3.x] Initialize all variables in constructor to prevent undefined behavior

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#52674]
### Issue description

3.x version of #43636

Due using unitialized variables, Godot may behave very strange and cause bugs like #52634.
To prevent such situations, all variables(except maybe buffers) should be initialized in constructor, because it is easy to forget to do it later.

So, initializing all variables in such class
```
class HashingContext : public Reference {
	void *ctx;
        int rar;
        bool q;
public:
	HashingContext() {
            ctx = memnew(something);
        }
	~HashingContext();
};
```
can be done in this way in 3.x branch
```
class HashingContext : public Reference {
	void *ctx;
        int rar;
        bool q;
public:
	HashingContext() {
            ctx = memnew(something);
            rar = 0;
            q = false;
        }
	~HashingContext();
};
```

Do not try to create PR which changes more than ~50-100 lines, because it will be hard to rebase after other users changes and also such small PR should be merged faster into 3.x branch. 

Maybe cppcheck html report will be helpful to find such variables - [report.zip](https://github.com/godotengine/godot/files/7163270/report.zip)

![Screenshot from 2021-09-14 17-39-42](https://user-images.githubusercontent.com/41945903/133289380-343b3c0c-ccb8-4433-b96e-1396ee8495e0.png)

Remember to put here info that you work on e.g. `core/` or `servers/` folder

**Comment by greeshmaym** [comment]
Hey @qarmin, Can you assign this issue to me.I would like to work on this

**Comment by qarmin** [comment]
You need just write in what folder you are working in and no one else should bother you.
Remember to create a PR of max 50-100 lines and if you want to change more things, it is best to create another PR.

**Comment by Kyetuur** [comment]
I'm going to look at /scene

**Comment by huancho9802** [comment]
Hello. I will take a look at /servers.

**Comment by lukan23** [comment]
Hello, I'm going to look at /platform

**Comment by splitsecmsk** [comment]
Hello, I'm going to look at /drivers

**Comment by Lucas3H** [comment]
Can I make break the work of a folder into more than one PR, since it's recommended to not change more than 50~100 lines per PR?

**Comment by akien-mga** [comment]
> Can I break the work of a folder into more than one PR, since it's recommended to not change more than 50~100 lines per PR?

Yes, definitely 👍

**Comment by VVR20** [comment]
Hi...I too  would like to work on this issue but I am having trouble knowing which folder is available to work. Can someone please help?
Cheers!

**Comment by webbuf** [comment]
Hey everyone, I'll stat taking a look at /modules

**Comment by Clawber** [comment]
Hello everyone, It seems like there's no pull request yet for /platform. I'll start working on it.

**Comment by akien-mga** [comment]
I'd like to apologize to first time contributors who tried to help with this refactoring effort, I should have flagged earlier that this wasn't that good a task for first time contributors, at least not with more guidance and making absolutely clear what a proper class member initialization should look like. Most PRs made for this effort ended up not being merged as they had issues, grew stale, and it's more work to update them for a seasoned contributor than to do the refactoring work from scratch.

Overall, Sep 2021 was already too late to start a major refactoring of the `3.x` codebase I believe, at least without clear oversight from me or other core maintainers.

So I'll close this issue, let's keep such changes to actually solving cases where member variables are clearly not identified, and not refactoring all the initialization currently done in constructors. If static analysis tools can point at uninitialized members, we can fix those, without refactoring the whole codebase.
