### ISSUE TITLE
Excessive update() usage when moving mouse on the Tabs GUI element

### ISSUE THREAD

**Issue by e8newallm** [godotengine/godot#52680]
### Godot version

4.0.dev (0232a03)

### System information

Arch Linux x86_64 5.14.2-arch1-2 

### Issue description

Moving the cursor around on seemingly any tab section causes an update that doesn't seem to do anything. This can easily be seen on the tabs at the top of the scene window, however it can also be seen on other tab sections (Though weirdly only sections of them).

https://github.com/godotengine/godot/blob/0232a031772d929c00d7c8a7947b1b9894ce26fb/scene/gui/tabs.cpp#L98-L125

The cause of this is the update() at the end of the `if (mm.is_valid())` block at line 123 which is being called regardless of if anything has been changed or updated.

I propose this update be investigated to find out what purpose it serves, and to see whether or not it can be more specifically applied to only occur if something has been changed by moving it into `Tabs::_update_hover()`.

https://github.com/godotengine/godot/blob/0232a031772d929c00d7c8a7947b1b9894ce26fb/scene/gui/tabs.cpp#L634-L669

### Steps to reproduce

1) Open any Godot project
2) Open Editor -> Editor Settings
3) On Interface -> Editor, tick Show Update Spinner
4) Close the settings
5) Wave cursor around on the tab bar at the top of the main window and watch the update spinner

**Comment by Calinou** [comment]
I can confirm this on 3.3.3 and 4.0.dev (43e96e0c6).

**Comment by timothyqiu** [comment]
It's added for the close button in #2380 I think.

**Comment by e8newallm** [comment]
If that's the only reason it's there, I'll take a look either tonight or tomorrow night and see if I can implement it better. (If someone else wants to pick it up before then, let me know so I don't end up trying to work on it too).
