### ISSUE TITLE
Viewport and window dimensions are incorrect on Windows with large desktop resolutions

### ISSUE THREAD

**Issue by Cheeseness** [godotengine/godot#52689]
### Godot version

3.3 stable

### System information

Windows 10 Pro 64 bit, Nvidia GTX1070 471.96, GLES3

### Issue description

I have had a Windows 10 user testing ultra widescreen support report to me that when they use larger monitors/desktop sizes, my games do not render above 720p. On a 3000x1080 screen, render resolution appears correct and a driver-side screenshot tool captures screenshots at 3000x1080, but on a 3840x1080 screen, a driver screenshot tool takes a 2560x720 image, while an OS screenshot captures a 3840x1080 image that appears to be scaled up from 2560x720 (with antialiasing?). The user tells me that the deviation from actual pixel size seems to increase as the window is resized, but the entire desktop resolution appears to be the factor in determining whether the problem occurs or not.

I am unable to reproduce this behaviour on Linux.

Below is an OS screenshot of a window resized to 3840x1020, which reports a viewport size of 2560x657, and an incorrect window size of 2560x657. Image dimensions show the window's size as 3840x1020.
![image](https://user-images.githubusercontent.com/1570520/133392687-da61a6e3-548e-48a9-b429-fd31ce76f537.png)

This does not appear to be related to OS.set_window_fullscreen() and occurs when manually resizing the window by clicking and dragging its borders. It also doesn't appear to be related to DPI scaling, as screenshots that I've seen of that have fonts rendered at native res.

### Steps to reproduce

In the sample project, scale the window up to larger sizes on a screen greater than 3000x1080, or use F to toggle fullscreen. Observe the labels giving output for get_viewport().get_size() and OS.get_window_size()

### Minimal reproduction project

[viewport_resolution_test.zip](https://github.com/godotengine/godot/files/7167896/viewport_resolution_test.zip)

**Comment by floppyhammer** [comment]
You have enabled `Display Scale 150%` on Windows, so this is probably not an issue.

**Comment by Cheeseness** [comment]
> You have enabled `Display Scale 150%` on Windows, so this is probably not an issue.

I haven't enabled anything like that. The project and export preferences are Godot default.

![image](https://user-images.githubusercontent.com/1570520/133402457-84ba148c-d968-40ad-82ec-b049e6532cc1.png)

As I mentioned in the initial report, this does not match behaviour that I've seen in screenshots of Godot's display scaling. That's an editor setting anyway, and this occurs in release builds.

**Comment by Cheeseness** [comment]
Taking a lead from @floppyhammer's comment, I dug around and got the user to enable the allow_hidpi setting via a config override, and that seems to have addressed the problem they were experiencing.

Looks like there's already a proposal for discussing an implementation of a check to see whether hidpi is actually warranted, so I suppose this issue is redundant https://github.com/godotengine/godot-proposals/issues/2661

**Comment by floppyhammer** [comment]
@Cheeseness Sorry, I wasn't being clear. I meant `Display Scale` in Windows Display Settings, not in Godot Editor Settings.

**Comment by Cheeseness** [comment]
> @Cheeseness Sorry, I wasn't being clear. I meant `Display Scale` in Windows Display Settings, not in Godot Editor Settings.

Oh, I see. I haven't had Windows installed since 2004, so my awareness of what it's up to these days is very low.

**Comment by Calinou** [comment]
Enable **Allow Hidpi** in the Project Settings to make the project DPI-aware. Make sure to support multiple resolutions to prevent 2D elements from becoming tiny on hiDPI displays.

**Comment by Cheeseness** [comment]
> Enable **Allow Hidpi** in the Project Settings to make the project DPI-aware on Windows and macOS.

Thanks. That's what I ended up doing onc I understood what was happening, as mentioned above https://github.com/godotengine/godot/issues/52689#issuecomment-919850521
