### ISSUE TITLE
Startup error spam `InputMap already has action`

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#52691]
### Godot version

aff0521d3f963f9e2a1bb53bb8d95bacffe42448

### System information

Windows 10

### Issue description

A lot of startup errors generating:

![image](https://user-images.githubusercontent.com/3036176/133409482-1a51ef70-5eb8-4c1b-959a-b49ca1500435.png)

### Steps to reproduce

Simply run a project manager.

### Minimal reproduction project

No need.

**Comment by akien-mga** [comment]
Probably caused by #52291.
