### ISSUE TITLE
Search in script should scroll line to the center

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#5269]
Tested on Godot 2.0.3, Windows 10 64 bits:

When I search something in a script, the editor scrolls down to that line, but I cannot see what's next. This is not convenient because I loose half of the context. 
It would be better to scroll the line to the center of the view, like any other editor does (Sublime; Npp++, VS...).

![godot_search_scroll_down](https://cloud.githubusercontent.com/assets/1311555/16170786/deb30358-355e-11e6-96f0-5b212ba85070.png)

Could be referred in https://github.com/godotengine/godot/issues/2982

**Comment by neikeq** [comment]
The find/replace dialog was replaced by a bar in the current master branch, but the above behaviour is still valid. I'll have a look.
