### ISSUE TITLE
Add a node configuration warning when using NinePatchRect's Tile or Tile Fit modes in GLES2

### ISSUE THREAD

**Issue by Lebostein** [godotengine/godot#52708]
### Godot version

3.3.3

### System information

Mac Os 10.13.6 

### Issue description

The options "Tile" and "Tile Fit" of NinePatchRect are without effect. The result is always stretched.

### Steps to reproduce

Create a NinePatchRect node, load a texture, define the margin an test the different options.
![Bildschirmfoto 2021-09-15 um 17 40 47](https://user-images.githubusercontent.com/23153870/133465144-643826aa-f549-4177-97ed-a2efc087e504.png)

**Comment by Calinou** [comment]
These options are only effective when using the GLES3 rendering backend.

**Comment by Lebostein** [comment]
I don't understand. Clipping sprites es the simplest graphic operation. Why shouldn't a renderer be able to do that? Clipping sprites with other nodes (sprite node or tileset) works with GLES2....

**Comment by Calinou** [comment]
> I don't understand. Clipping sprites es the simplest graphic operation. Why shouldn't a renderer be able to do that? Clipping sprites with other nodes (sprite node or tileset) works with GLES2....

This may come as a surprise, but GLES2 is very limited when it comes to handling texture repetition and stuff like that. Emulating this in a shader is slow and error-prone, especially on mobile GPUs that have lower shader precision.

**Comment by Lebostein** [comment]
Thanks. With GLES3 it works.

Would be very helpful to see, which options are not available for GLES2. I tried around for an hour yesterday, watched tutorials and was frustrated because it didn't work for me. Please highlight the options in red in the GUI or print a Debugging Warning.

![Zwischenablage01](https://user-images.githubusercontent.com/23153870/133554767-4beadbe2-4db4-4262-a449-e88ead91bdcd.jpg)

**Comment by jmb462** [comment]
> Would be very helpful to see, which options are not available for GLES2. I tried around for an hour yesterday, watched tutorials and was frustrated because it didn't work for me. Please highlight the options in red in the GUI or print a Debugging Warning.

The PR linked to this issue will show a warning in the tree when choosing one of the GLES2 incompatible stretch mode.

![image](https://user-images.githubusercontent.com/3649998/133660083-fac42838-a6e9-404e-911b-3bad0be9d2ac.png)

**Comment by akien-mga** [comment]
Fixed by #52728.
