### ISSUE TITLE
not working with nvidia driver 470

### ISSUE THREAD

**Issue by codekid-rgb** [godotengine/godot#52704]
### Godot version

3.3 stable

### System information

Nvidia geforce gtx 970 nvidia drivers 470 GLES3

### Issue description

![Screenshot from 2021-09-15 07-58-18](https://user-images.githubusercontent.com/75947588/133447262-bae2cb4a-67f8-4922-95f8-dab28d6ccf4a.png)
as soon as I launch Godot the issue in the screenshot come up. I think that the driver does not support openGL.

### Steps to reproduce

step 1 install gtx 970 gpu. step2 install driver 470. step3 launch Godot and get the error.

**Comment by codekid-rgb** [comment]
can someone please help?

**Comment by akien-mga** [comment]
You need to reboot after installing or updating Nvidia drivers on Linux, otherwise they don't work.

**Comment by codekid-rgb** [comment]
thank you!

**Comment by codekid-rgb** [comment]
It still does not work, what do I do?

**Comment by codekid-rgb** [comment]
Do I need a faster GPU?

**Comment by Calinou** [comment]
> Do I need a faster GPU?

The GTX 970 supports OpenGL 4.6 and Vulkan. It can run Godot just fine.

Are you using a laptop with hybrid graphics (Optimus)?

**Comment by qarmin** [comment]
No, I almost always work with Godot on Ubuntu with GTX 970 and it works fine.

I had this error when manipulating updating/installing OS or changing version of Nvidia drivers(this bug should be also visible in other activities e.g. hen playing games).

I recommend to reinstall drivers, by simply installing e.g. 460 and later installing back 470
![Screenshot from 2021-09-15 19-50-24](https://user-images.githubusercontent.com/41945903/133484012-b8506b4a-6e44-4dbf-baac-24a1b9d785d5.png)

**Comment by Zireael07** [comment]
LOL, nope, Godot worked mostly fine with a Radeon 6630M xD - here's a benchmark comparison of the two https://hwbench.com/vgas/geforce-gtx-970m-1-vs-radeon-hd-6630m

Your card should be OpenGL 4.1 capable, so the only thing I can think of is either you have a sucky integrated card that doesn't do OpenGL and the system is defaulting to that integrated, or the system isn't picking up your new card at all.

**Comment by bruvzg** [comment]
Check if your driver is correctly installed and active, what's output of the `sudo lspci` and `glxinfo` commands. And check your BIOS settings, in some cases you might need to disable secure boot for Nvidia driver to load correctly.

**Comment by codekid-rgb** [comment]
I installed the .deb from the app store on my computer and I am not using a laptop I have a full sized gtx 970 and intel core i5 6th gen with 16 gigabytes of ram

**Comment by codekid-rgb** [comment]
_00:00.0 Host bridge: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Host Bridge/DRAM Registers (rev 07)
00:01.0 PCI bridge: Intel Corporation 6th-10th Gen Core Processor PCIe Controller (x16) (rev 07)
00:14.0 USB controller: Intel Corporation 100 Series/C230 Series Chipset Family USB 3.0 xHCI Controller (rev 31)
00:16.0 Communication controller: Intel Corporation 100 Series/C230 Series Chipset Family MEI Controller #1 (rev 31)
00:17.0 SATA controller: Intel Corporation Q170/Q150/B150/H170/H110/Z170/CM236 Chipset SATA Controller [AHCI Mode] (rev 31)
00:1b.0 PCI bridge: Intel Corporation 100 Series/C230 Series Chipset Family PCI Express Root Port #17 (rev f1)
00:1c.0 PCI bridge: Intel Corporation 100 Series/C230 Series Chipset Family PCI Express Root Port #1 (rev f1)
00:1d.0 PCI bridge: Intel Corporation 100 Series/C230 Series Chipset Family PCI Express Root Port #9 (rev f1)
00:1d.1 PCI bridge: Intel Corporation 100 Series/C230 Series Chipset Family PCI Express Root Port #10 (rev f1)
00:1d.2 PCI bridge: Intel Corporation 100 Series/C230 Series Chipset Family PCI Express Root Port #11 (rev f1)
00:1f.0 ISA bridge: Intel Corporation Z170 Chipset LPC/eSPI Controller (rev 31)
00:1f.2 Memory controller: Intel Corporation 100 Series/C230 Series Chipset Family Power Management Controller (rev 31)
00:1f.3 Audio device: Intel Corporation 100 Series/C230 Series Chipset Family HD Audio Controller (rev 31)
00:1f.4 SMBus: Intel Corporation 100 Series/C230 Series Chipset Family SMBus (rev 31)
00:1f.6 Ethernet controller: Intel Corporation Ethernet Connection (2) I219-V (rev 31)
01:00.0 VGA compatible controller: NVIDIA Corporation GM204 [GeForce GTX 970] (rev a1)
01:00.1 Audio device: NVIDIA Corporation GM204 High Definition Audio Controller (rev a1)
05:00.0 Network controller: Qualcomm Atheros QCA6174 802.11ac Wireless Network Adapter (rev 32)
06:00.0 USB controller: ASMedia Technology Inc. ASM1142 USB 3.1 Host Controller_

**Comment by codekid-rgb** [comment]
that is the output of sudo lspci

**Comment by codekid-rgb** [comment]
my chip does have integrated graphics and I have had less graphics performance than usual recently, I will check what I am using.

**Comment by codekid-rgb** [comment]
hardinfo says that I am using the gtx970.

**Comment by Zireael07** [comment]
On a laptop with two cards, I've had to forcefully set DRI_PRIME to get Godot to pick the card I wanted it to.

> #!/bin/bash
> DRI_PRIME=0 ./Godot_v3.3.3-stable_x11.64

0 is integrated 1 is discrete. save to a .sh script in the folder where your Godot executable is and run Godot via running this script.

**Comment by qumaciel** [comment]
I am also having problems. I am using Linux 470.62.02 Vulkan driver on a RTX 2060M

When I open Gadot I get multiple 
```
ERROR: Condition "!importer.is_valid()" is true. Continuing.
   at: reimport_files (editor/editor_file_system.cpp:2086)
```

and 

```
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.dev.custom_build (e902347a8cefbced8898dfc9f000afdf3be0d36a)
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /usr/lib/libc.so.6(+0x3cda0) [0x7fb4ea911da0] (??:0)
[2] /usr/bin/godot(+0x6087c7) [0x55fa0f0f67c7] (??:0)
[3] /usr/bin/godot(+0x1fc9479) [0x55fa10ab7479] (??:0)
[4] /usr/bin/godot(+0x1b6fa09) [0x55fa1065da09] (??:0)
[5] /usr/bin/godot(+0x1b58617) [0x55fa10646617] (??:0)
[6] /usr/bin/godot(+0x1b9766d) [0x55fa1068566d] (??:0)
[7] /usr/bin/godot(+0x3adc018) [0x55fa125ca018] (??:0)
[8] /usr/bin/godot(+0x4440214) [0x55fa12f2e214] (??:0)
[9] /usr/lib/libpthread.so.0(+0x9259) [0x7fb4eabf7259] (??:0)
[10] /usr/lib/libc.so.6(clone+0x43) [0x7fb4ea9d35e3] (??:0)
-- END OF BACKTRACE --
================================================================
```

**Comment by Calinou** [comment]
@qumaciel This is unrelated to the issue reported here. Please open a separate issue with a minimal reproduction project attached.

**Comment by codekid-rgb** [comment]
I was using a flatpack accidentally. It works with the regular binary, thanks everyone!!!
