### ISSUE TITLE
Vulkan: Fixed Fog is no longer radial and fades according to the view plane instead

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#52707]
### Godot version

v4.0.dev.custom_build [5a612d61b]

### System information

Windows 10, Vulkan, Nvidia Quadro K2000 461.92

### Issue description

Fog is no longer radial, as opposed to Fog in 3.x

(3.x)
![Fade](https://user-images.githubusercontent.com/50302479/133455968-45d80f8b-2f55-4227-974f-364da1a91aa1.png)

In 3.x, the Fog fade is like in the picture, while in 4.0 the Fog fades in a linear fashion (like the camera far cuts off, also visible in the picture)

The Radial Fog is important because the angle of the camera doesn't affect how foggy something is, only distance matters, while without Radial Fogs rotating a camera can reveal things that are supposed to be foggy

### Steps to reproduce

Create a Scene with Fogs in 3.x and Master and observe the behaviors of the 2 Fogs when rotating the camera with objects in the Fog

In Master, the fog level of objects will change as the camera rotates, but in 3.x it will not.

**Comment by clayjohn** [comment]
I guess the difference is just that in 3.x we us the distance to a given point while in 4.0 we just use the camera-space z value

_GLES3:_
https://github.com/godotengine/godot/blob/1cbb1f279671fdcb046a4b7d9abdb1763b316612/drivers/gles3/shaders/scene.glsl#L2231

_Master:_
https://github.com/godotengine/godot/blob/f77b1f4002a5539d73bf8216f5849ceca2f1f864/servers/rendering/renderer_rd/shaders/scene_forward_clustered.glsl#L527

**Note for whoever works on this:**
Fog in master is calculated in multiple places:

- scene_forward_clustered.glsl
- scene_forward_mobile.glsl and
- sky.glsl
