### ISSUE TITLE
code not working

### ISSUE THREAD

**Issue by midnight12346** [godotengine/godot#52747]
### Godot version

v3.3.3.stable.mono.offical [b973f997f]

### System information

GLES3, MacOS High Sierra, Intel HD graphics 6000

### Issue description

func btn_pressed():
        get_tree().change_scene("res://path/to/shawty.tscn);

not working

Errors:
 /Users/academystudent/godot/main scene/scripts2/changescene.cs(18,20): error CS1002: ; expected [/Users/academystudent/godot/rpg.csproj]
  /Users/academystudent/godot/main scene/scripts2/changescene.cs(18,20): error CS1513: } expected [/Users/academystudent/godot/rpg.csproj]

### Steps to reproduce

func btn_pressed():
        get_tree().change_scene("res://path/to/shawty.tscn);

**Comment by pycbouh** [comment]
You have a typo in your code sample — you didn't close the string with a second double-quote.

Please, don't create issues if you have problems with your code. This is not a support forum, this is a bug tracker. Use our community platforms to ask for help with fixing up your projects and learning Godot:
https://godotengine.org/community
