### ISSUE TITLE
Whenever i rename a node the childrens properties become unaccessible

### ISSUE THREAD

**Issue by SpicoTheSpiritGuy** [godotengine/godot#52746]
### Godot version

3.3.stable

### System information

Windows 10, Intel HD graphics 620

### Issue description

Whenever i rename a parent node, and click on its childrens properties, it shows a blank page, heres what i get dropped down in the debug console

ERROR: (Node not found: "/root/EditorNode/@@580/@@581/@@589/@@591/@@595/@@599/@@600/@@601/@@617/@@618/@@627/@@628/@@6066/@@5905/@@5906/@@5907/@@5908/@@5909/PlaneV2/CollisionShape2D" (absolute path attempted from "/root/EditorNode/@@580/@@581/@@589/@@591/@@595/@@596/@@597/Scene/@@2784").)

if i leave and reenter the project it works, but whenever i try renaming ANYTHING saving and quitting would be a really bad way of coping with this

this only now started happening, i have been using this engine for the past 3 months and this is the first time i started fighting with it, i made new projects, i verified the integrity of game files, hell i even reinstalled the whole thing but this never really goes away no matter how hard i try

### Steps to reproduce

1. Open new project
2. create a new node
3. give it a random child
4. rename the parent child
5. click the child of the now renamed parent
6. check debug logs and the property/signal window

**Comment by SpicoTheSpiritGuy** [comment]
also i guess i should clarify, even though it says "CollisionShape2D" in there it outputs the same error message with ANY node, all i remember is deleting a node via the editors resource manager and when i switched back to the scene i used for debugging it sent me ALOT of errors similar to the one i get now and it crashed in the process (not really it was just giving me tons of errors so i just closed the debug window, soft crashing the engine), this started happening when i opened it again

and the code i previously saved before this happened wasnt saved either for some reason i have no clue why that is

**Comment by SpicoTheSpiritGuy** [comment]
oh yeah thats exactly what it is, but for me the childrens inspector window also goes fully grayed out i am certain it does that with you as well, glad my godot crashing that one time didnt result in any breakage of the main code though

**Comment by Zireael07** [comment]
I had the same issue in 3.3.3. Only root node is affected, and save and reopen scene fixes it.

**Comment by 2784** [comment]
Why am I on this group chain?

Don’t you people even care who is seeing your emails?  It’s rediculous…

Complete amatures

**Comment by ShatReal** [comment]
This also happens to me when I create new inherited scenes in 3.3.3.

**Comment by akien-mga** [comment]
Fixed by #52962.
