### ISSUE TITLE
Vulkan: Glow rendering is broken on macOS

### ISSUE THREAD

**Issue by pacmanmati** [godotengine/godot#52755]
### Godot version

4.0.dev commit 3581b893ed2dc1e444618ac40dc26dd58fe1219a

### System information

Mac OSX M1 Air

### Issue description

Mesh instances emit a strange glow in the viewport on +z and -z facing faces. Rotating the mesh makes the problem go away until you view a face from a certain angle, e.g. the top face in screenshot two.
![image](https://user-images.githubusercontent.com/37005453/133683068-3a5c52e8-0c21-48e1-a225-080bd303fff8.png)
![image](https://user-images.githubusercontent.com/37005453/133684198-0f7bce09-2884-4e11-9abe-1edb2badeba7.png)

### Steps to reproduce

Compile for arm64, the precise command I used was:`scons platform=osx arch=arm64 --jobs=$(sysctl -n hw.logicalcpu) use_static_mvk=yes` although I can reproduce the bug regardless of static linking.

Create a new scene using clustered vulkan, insert a 3d camera and mesh instance in the root 3d node.

**Comment by Calinou** [comment]
As a workaround, disable Glow in the preview environment settings (click the sun icon at the top of the 3D viewport).

**Comment by pacmanmati** [comment]
Disabling glow makes part of the issue go away. I also wanted to add on that there is a sun artifact:
![image](https://user-images.githubusercontent.com/37005453/133771133-0209c95e-536a-43c6-8fbf-852c68978977.png)
Additionally, the +z and -z faces of a mesh instance are still black after disabling glow unless the object is rotated along the y-axis.
![image](https://user-images.githubusercontent.com/37005453/133771254-933c39ca-a5f6-4b6a-b3f9-2704db1ef9d1.png)

**Comment by clayjohn** [comment]
Can you still reproduce this issue on a more recent version of the engine?

**Comment by pacmanmati** [comment]
tried it out on `4.0-rc5` with all three renderers (mobile, forward, compat) and it looks to be fixed :)
