### ISSUE TITLE
osx arm64 play mode renders nothing

### ISSUE THREAD

**Issue by pacmanmati** [godotengine/godot#52756]
### Godot version

4.0.dev commit 3581b893ed2dc1e444618ac40dc26dd58fe1219a

### System information

Mac OSX M1 Air

### Issue description

3d scene just renders a black screen.
![image](https://user-images.githubusercontent.com/37005453/133684753-ff8b9e7e-bdcf-4257-ac7b-afc940a688db.png)

For comparison, a 2d camera works as expected:
![image](https://user-images.githubusercontent.com/37005453/133685049-671ebfeb-db6f-46d0-a119-9707273d9e6f.png)

### Steps to reproduce

Compile for arm64, the precise command I used was:scons platform=osx arch=arm64 --jobs=$(sysctl -n hw.logicalcpu) use_static_mvk=yes although I can reproduce the bug regardless of static linking.

Create a new scene using clustered vulkan, insert a 3d camera and an object of your choosing (in my case, mesh instance cube) and press play.

**Comment by Calinou** [comment]
You need to add a WorldEnvironment and a light to be able to see something in the running project. Use the preview environment feature ("sun" icon at the top of the 3D viewport) to quickly copy the current environment settings to the current scene.

Also, make sure the camera is not inside the MeshInstance.

**Comment by pacmanmati** [comment]
Yep - adding a WorldEnvironment and a light does indeed solve the issue, I'll close this since it'll likely be well documented upon release.
