### ISSUE TITLE
Report a small trouble with Godot 3.3.3 export (Windows)

### ISSUE THREAD

**Issue by sante76** [godotengine/godot#52766]
### Godot version

v3.3.3.stable.official [b973f997f]

### System information

Windows 10

### Issue description

First of all, excuse my bad english. I would like to report a simple, boring bug (?) discovered with v3.3.3.stable.official version of Godot.
A bit of history: I'm searching to respect recommendations in Godot user guide, like the one who says to use lowercase to name folders... But I do mistake lot of times, so I've named a folder "GUI", simply because of habits... Later I've renamed it "gui", in lowercase. All time, my game works well  both in editor that when exported.
The new v3.3.3.stable.official was released and I install it. The game no work more... Better: the game work well in editor but no more when exported. I've found a couple of line of code like the next one:
`var gameover_panel: TimedPanel = load("res://scenes/GUI/gameover_panel.tscn").instance();`
Simply the path with "GUI" in capital letters works in all previous official versions of Godot but no more with the new v3.3.3. It's a simple, annoing, question. Exporting the project with debug, the report says simply cannot find the file specified by that path. But the game still works well in editor... To solve the problem, I simply correct that path with lowercase "gui" like this one:
`var gameover_panel: TimedPanel = load("res://scenes/gui/gameover_panel.tscn").instance();`
All work well again. 
I think can be a problem with Windows systems, who are case insensitive with file and folder names... The annoing question is the fact the game works well in editor, but not when exported and the fact this becamed a problem only with last release, when with the previous all works well. My game is tiny, so I found the problem quickly, but with larger project it can became a nightmare... I think a warning in the editor discouraging use of capital letter for file paths can help a lot.
Hoping can be usefull.

Bye.

### Steps to reproduce

Simply create a lowercase named folder like "gui" and then try to  load a file from the same folder referred with uppercase like "GUI"

**Comment by Calinou** [comment]
This is a known issue already: https://docs.godotengine.org/en/stable/getting_started/workflow/project_setup/project_organization.html#case-sensitivity

**Comment by akien-mga** [comment]
> Simply the path with "GUI" in capital letters works in all previous official versions of Godot but no more with the new v3.3.3.

I'm curious about this, what previous versions worked fine?

The behavior you described in 3.3.3 is expected, but it should be the same in earlier versions too.

**Comment by sante76** [comment]
> > Simply the path with "GUI" in capital letters works in all previous official versions of Godot but no more with the new v3.3.3.
> 
> I'm curious about this, what previous versions worked fine?
> 
> The behavior you described in 3.3.3 is expected, but it should be the same in earlier versions too.

First of all, I consider what happen a mistake of mine, because I know there was issues with uppercase/lowercase name for files in general, but I've used the same code also with the previous v3.2.3 stable version without any sort of problem. So I'm surprised when I found it, considering also I've no modified reported code from weeks...
