### ISSUE TITLE
Search Find in Files does not search all *gd files in project.

### ISSUE THREAD

**Issue by sjharb** [godotengine/godot#52789]
### Godot version

3.3.3.stable

### System information

Windows 10

### Issue description

When trying to search for keyword(s) using Find in Files does not search all *.gd files.  These are not built in scripts as other issues have been created for that topic.

The StoryPlot.gd show in the picture is not the only file that this is happening to.  I now have to use Notepad++ to get a "real" list of occurrences when it is critical for me.

Most files work to be searched and it seems like more currently created files are the ones with issue, but not exclusively.
I have a large number of script (gd) files, 274 currently, but I couldn't imagine there would be a limit.

![find_in_files_not_working_for_all_files_v3_3_3_stable](https://user-images.githubusercontent.com/57383586/133815021-5672e184-b5c2-42c2-b0e8-c75e9c81f75b.png)

Thanks,
Shaun

### Steps to reproduce

I can reproduce this in my project, but I don't expect it is be an issue for every project.

1) Open the Script Editor view.
2) Click 'Search' -> 'Find in Files'.
3) Enter a keyword and click 'Find' button.

Result: 0 matches in 0 files.

### Minimal reproduction project

I uploaded a simple reproduction project, see below comments.

**Comment by Calinou** [comment]
@sjharb Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by Luka-sama** [comment]
The problem is that it searches only in one folder (by default - in root folder). But the expected behavior would be that it searches by default in all files in project.

**Comment by sjharb** [comment]
> The problem is that you should enter the path to folder with scripts, otherwise the search will not work. If there are scripts in the root directory, you cannot search there.

For my large project all of my scripts are in the root folder, most return search results, but for some reason not all.  It is not random either, the same scripts are being skipped in the searches.  Sorry I do not have a small project that reproduces this issue.  My other small projects seem to work fine.  I wonder if this is an issue with older projects.  I would have to dig into Godot Engine code to see how the scripts are being gathered to be searched.  I assume it would just search all the *.gd files in your project?

**Comment by Luka-sama** [comment]
Sorry, I found out that the problem was in my case .gdignore in my root folder.
Though that is still strange - I did not create this file.

**Comment by shafnaz** [comment]
I also have this issue. When I open using 3.3.2, no problems, but with the later problems, that  .gdignore messes up the search

**Comment by Calinou** [comment]
@shafnaz Can you upload a minimal reproduction project that exhibits this issue?

**Comment by shafnaz** [comment]
You can place this file in your res folder. It doesn't bother version 3.3.2, but it does bother 3.3.3 onwards. you just have to delete or remove a line of code.  And I don't know how it got there, just a few of my projects have it. Maybe a library add-on.
[file.gdignore.zip](https://github.com/godotengine/godot/files/7274691/file.gdignore.zip)

**Comment by Calinou** [comment]
> You can place this file in your res folder. It doesn't bother version 3.3.2, but it does bother 3.3.3 onwards. you just have to delete or remove a line of code. And I don't know how it got there, just a few of my projects have it. Maybe a library add-on. [file.gdignore.zip](https://github.com/godotengine/godot/files/7274691/file.gdignore.zip)
`.gdignore` files are supposed to empty. Their contents are ignored by the Godot editor.

**Comment by shafnaz** [comment]
Well, I hope others that have this issue, find the solution here. Deleting the files solved it.

**Comment by sjharb** [comment]
Not that it helps, but I do not have any .gdignore file(s) in my project, just a gitignore.  I guess this issue might just be with my project since no-one else seems to have the same issue.  Again my project is large and 'old' (started with version 2 of Godot), but I do keep up to date using the latest stable build of Godot.  Sorry, I don't have a smaller project to reproduce the issue.  My other project works fine, but it is small and new.

**Comment by jakebesworth** [comment]
I'm on version 3.4.4 and I'm having a similar issue. Whenever I try to "Find in Files", it only searches a single file when the directory is root. Once I select a subdirectory, then it actually searches in all files.

This wasn't the case before 3.4.4. My .gdignore doesn't have any of the subdirectories I'm trying to search in.

**Comment by sjharb** [comment]
Found the issue.  Only projects having more than 1000 files will have issues.
It was actually pretty obvious via code inspection.
A hardcoded loop value limiting the FindInFiles to only search 1000 files.

I tested the fix locally on:
Godot Version 3.x
Windows
  
File: [find_in_files.cpp](https://github.com/godotengine/godot/blob/3.x/editor/find_in_files.cpp) line 229
Function: FindInFiles::_scan_dir

for (int i = 0; i < 1000; ++i) {

This loop if changed from 1000 -> 2000 etc allows my search to be complete since I have approximately 1500 files in my project.

Solution/Proposal:
The way to properly handle this would not be to hardcode to a higher value, say 3000.
There should be a 3 second check and if > 9 seconds goes by, pop-up to the user and ask the user if they want to continue with a 'long running search'.

**Comment by sjharb** [comment]
Here is a project that reproduces the issue in Godot 3.4.4 stable.
[godot_v3_4_4_issue_52789_1001_file_loop_test_project_6_22_2022.zip](https://github.com/godotengine/godot/files/8958651/godot_v3_4_4_issue_52789_1001_file_loop_test_project_6_22_2022.zip)

Test project Instructions:
Test project for Godot issue # 52789
find in filesSearch Find in Files does not search all *gd files in project.
The project already contains > 1000 files in the res:// directory, but they can be generated by running the project.
1) Run this project to create gdscript files into one directory (res://).
2) Try to search 'find in files' for '_998', '_997', '_996', '_995', '_994', '_993', '_992', '_991'.
Actual: cannot find files over _990 since there are 1006 files in my res:// directory.
Expected: can search through any number of files in any directory.
3) Search with 'find in files' for '_990'.
Expected: Found _990 because it was found before the 1000 loop in find_in_files.cpp is reached.

**Comment by wyattbiker** [comment]
Also,  If you unchecked the **gd** files Filter, Search Find in Files will not search any other files. I assumed if you unchecked, it would search all text based files at the minimum such txt, cfg, ini, tscn, etc

**Comment by LO-0116** [comment]
issue persists in v4.5.1.stable.official [f62fdbde1]
