### ISSUE TITLE
Vulkan: VoxelGI generates wrong lighting

### ISSUE THREAD

**Issue by jcostello** [godotengine/godot#52791]
### Godot version

v4.0.dev.calinou [7cdd8629a]

### System information

Ubuntu 21.04. RTX 2060

### Issue description

VoxelGI generates wrong lighting. There is a shadow in the VoxelGI Lighting draw view that is being generated out of nowhere.

![image](https://user-images.githubusercontent.com/1168582/133827980-4cfbeabf-49a1-4d71-a63a-40f40ba2c26e.png)

### Steps to reproduce

Check the VoxelGI Lighting draw view in the Main.tscn scene from the Minimal reproduction project

### Minimal reproduction project

[Godot VoxelGI.zip](https://github.com/godotengine/godot/files/7187327/Godot.VoxelGI.zip)

**Comment by clayjohn** [comment]
That shadow is from the preview sun. The preview sun is dynamically included in the VoxelGI lighting and since it is visible and casts a shadow, you see a shadow in the VoxelGI
