### ISSUE TITLE
AssignedAnimation and CurrentAnimation

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#52796]
### Godot version

3.3.3 stable mono

### System information

w10 64

### Issue description
This happens when executing, this problem has nothing to do with "Tool".
Hello, assign an animation to:
AssignedAnimation
It does not produce any visual change.
I expected the animation to map (not play, just map) and visually reflected but that doesn't happen.
Is this a bug? I think so.
AssignedAnimation should be the equivalent of selecting an animation in the animationPlayer, the animation is assigned and that is visually reflected in the editor, but that doesn't happen when you assign an animation to AssignedAnimation.

The problem, AssignedAnimation does not reflect anything at all visually, it does not reflect the animation change. The animation should be set and displayed in its initial state, with no playback.
So how should I assign an animation other than the predefined one that doesn't play but is visible in its initial state?
CurrentAnimation doesn't have any visual reflections either.

I have tried seek and advance and it didn't work.
![Captura3](https://user-images.githubusercontent.com/19652075/133841048-51414ec3-6e15-43b8-a8b0-0d284d717457.PNG)

### Steps to reproduce

It is about configuring several animations in a node and setting in _Ready an stoppped animation different from the predefined one.

### Minimal reproduction projec
Just try to set an animation but without playing it (that's why I stop at _Ready), the animation should be displayed but in its initial and stopped state.
[testAnimationPlayer.zip](https://github.com/godotengine/godot/files/7187941/testAnimationPlayer.zip)

**Comment by Calinou** [comment]
> Necessary?

Yes, always :slightly_smiling_face:

**Comment by Torguen** [comment]
There is a problem:
You cannot set a stopped animation (other than the predefined one) and have it displayed in its initial state.

I think it should be enough to assign an animation to "assignedanimation", then stop, then the animation should be shown in its initial and stopped state.

**Comment by Torguen** [comment]
Ok, I think this can be closed since the correct process to achieve what I described is this:

animationPlayer.CurrentAnimation = state.ToString ();
animationPlayer.Advance (0);
animationPlayer.Stop ();
