### ISSUE TITLE
Handle paths longer than 260 characters on Windows 10

### ISSUE THREAD

**Issue by noidexe** [godotengine/godot#52799]
### Godot version

v3.3.3.stable.official [b973f997f]

### System information

Windows 10, GLES 3

### Issue description

On windows, when the path to project.godot is too long (a folder with a really long name, or too deep of a hierarchy) it seems to load ok but when you try to open a scene it shows all external resources as broken dependencies. Even if the resources are there.
Deleting the import folder and regenerating it doesn't fix the problem.
Moving the project to a shorter path fixes the problem (Is 260 characters still the limit?)

The behavior I would expect is either loading the scene normally or showing the correct error (the path is too long). 
The actual error (Broken dependencies) is misleading as they are not really broken. 

I'm not sure if it is possible to properly detect the error and show the appropriate warning/message

### Steps to reproduce

- Put any project with at least a scene making use of some files(pngs, ogg, etc) in a really long path. Probably more than 260 characters long. If you try recycle the project folder windows should show a message saying the path is too long for the recycle bin.
- Open the project in the editor
- Open any scene making use of some files as resources

### Minimal reproduction project

It should be reproducible with any project. It's not the contents of the project but the path to it what triggers the error

**Comment by Calinou** [comment]
> Moving the project to a shorter path fixes the problem (Is 260 characters still the limit?)

260 characters is the path length limit on Windows. It can be lifted on Windows 10 with a registry edit. This is an opt-in mechanism for legacy compatibility reasons.

**Comment by akien-mga** [comment]
Fixed by #76739.
