### ISSUE TITLE
Linux crash handler: Missing line numbers in debug builds

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#52823]
### Godot version

bac757df214371ed8ddfa0946a1023a446f75d10

### System information

Ubuntu 21.04 - Nvidia GTX 970, Gnome shell 3.38 X11

### Issue description

On my computer and also in CI, debug builds stopped to show files and line where crash happened
```
 [1] ./bin/godot.linuxbsd.tools.64s(+0x335af924) [0x55e538f16924] (??:0)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f24d9f33210] (??:0)
[3] CSGPolygon3D::_notification(int) (??:0)
[4] CSGPolygon3D::_notificationv(int, bool) (??:0)
[5] Object::notification(int, bool) (??:0)
[6] Node::_propagate_exit_tree() (??:0)
[7] Node::_propagate_exit_tree() (??:0)
[8] Node::_set_tree(SceneTree*) (??:0)
[9] Node::remove_child(Node*) (??:0)
[10] Node::_notification(int) (??:0)
```

### Steps to reproduce

Try to crash Godot and see missing info about line

**Comment by akien-mga** [comment]
Did you build `debug_symbols=no`, or stripped the binary?

For CI it's expected and not a bug. Debug symbols are too big to upload.

**Comment by qarmin** [comment]
My build compilation command is just `scons -j6`.
It worked fine to probably mid August.

As I see debug_symbols still is enabled by default
```
debug_symbols: Add debugging symbols to release/release_debug builds (yes|no)
    default: True
    actual: True
```

**Comment by akien-mga** [comment]
Hm I can reproduce it too with my local builds. The debug symbols are present as `gdb` finds them just fine, but the crash handler is buggy.

**Comment by Calinou** [comment]
For bisection/testing purposes, you can call `CRASH_NOW()` in the project manager (e.g. by repeatedly applying a stash that you saved beforehand).

**Comment by qarmin** [comment]
I bisected that this is regression from https://github.com/godotengine/godot/pull/50737

**Comment by Calinou** [comment]
@qarmin Does it work again if you install libexecinfo and build with `execinfo=yes`?

**Comment by qarmin** [comment]
I can't find a way to install this library on Ubuntu 21.04 - https://packages.ubuntu.com/search?keywords=execinfo&searchon=names&suite=hirsute&section=all

I installed libexecs-dev and libexecline-dev from repos, but still linker fails with message
```
/usr/bin/ld: cannot find -lexecinfo
collect2: error: ld returned 1 exit status
```

**Comment by akien-mga** [comment]
I'm pretty sure this was fixed since then.
