### ISSUE TITLE
Error when mixing tabs and spaces in comment line

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#52834]
### Godot version

b1063a7

### System information

W10

### Issue description

idk I had this error in my code:
```
[TAB][SPACE]#something
```
It complains that tabs and spaces are mixed, even though it's irrelevant, because it's just a comment. Reporting this only because it was valid in 3.x

### Steps to reproduce

See snippet above.

**Comment by Calinou** [comment]
I think this should be considered invalid, as mixing indentation can cause confusion no matter the kind of line it's placed on.

We just need to document this in the changelog.

**Comment by adamscott** [comment]
Is this issue still relevant?

**Comment by KoBeWi** [comment]
It's still an error, but it's a minor issue.
