### ISSUE TITLE
Can't lerp variants anymore

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#52833]
### Godot version

b1063a7

### System information

W10

### Issue description

`lerp` built-in method used to lerp anything (Vectors, Colors etc.), not it only takes float. Might be an oversight.

### Steps to reproduce

`lerp(Vector2(), Vector2(1, 1), 0.5)`

**Comment by rxlecky** [comment]
Lerping specific data types was offloaded to methods of each supported type. This seems like an intentional change rather than oversight.
![image](https://user-images.githubusercontent.com/35656626/135720082-d60caec0-5c0c-40f5-821e-65ebdb033b12.png)

**Comment by KoBeWi** [comment]
Interestingly, `sign()` was changed from `int` to `Variant` just to support any type, like `lerp` used to. Even though every type has its own `sign()` method. There is some inconsistency here.
