### ISSUE TITLE
No equivalent of join() in PackedStringArray

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#52836]
### Godot version

b1063a7

### System information

W10

### Issue description

`join` function is rather important for String arrays, but strangely, it's missing in the new PackedStringArray. It was there in PoolStringArray

### Steps to reproduce

1. `var array = PackedStringArray(["hello", "world"])`
2. `var hellow = array.join()`
3. You expected "hello world", but it was me, Nonexistent function!
4. :(

**Comment by qarmin** [comment]
This function now is reversed in Godot 4.0
```
PackedStringArray(req_godot).join('.') -> '.'.join(PackedStringArray(req_godot))
```

**Comment by KoBeWi** [comment]
Most of the languages I used used the old way, i.e. Array.join(). Maybe we could allow both options or at least document in PackedStringArray how to join it.
