### ISSUE TITLE
Code auto-completion is unavailable for global statically typed variables defined in _ready

### ISSUE THREAD

**Issue by Novark** [godotengine/godot#52857]
### Godot version

3.3.3.stable.mono

### System information

Windows 10

### Issue description

When my statically-typed variables are declared on the global scope, but assigned data within `_ready`, the variables don't show class members in auto-complete pop-ups.

I have the following code snippet:

```python
# DB.gd

var client: MongoClient = MongoAPI.Connect("mongodb://127.0.0.1:27017")

func _ready():
    client.GetDatabase("my_db") #None of the methods/properties in MongoClient pop up in the autocomplete list
```

However, if I change the code to the following - it works just fine:

```python
# DB.gd

func _ready():
    var client: MongoClient = MongoAPI.Connect("mongodb://127.0.0.1:27017")
    client.GetDatabase("my_db") #All of the methods/properties pop up after the dot - works fine!
```

**Note:** For this example, MongoClient is an AutoLoad singleton written in C#, part of a third-party Godot Plugin

### Steps to reproduce

As described in issue report above

**Comment by akien-mga** [comment]
A minimal reproduction project would be welcome, as it's hard to confirm the bug without being able to reproduce it. Here it could also simply be that `var client: MongoClient = MongoAPI.Connect("mongodb://127.0.0.1:27017")` doesn't work in the global scope as the initialization code runs too early (you could try prefixing with `onready`).

**Comment by Novark** [comment]
> 
> 
> A minimal reproduction project would be welcome, as it's hard to confirm the bug without being able to reproduce it. Here it could also simply be that `var client: MongoClient = MongoAPI.Connect("mongodb://127.0.0.1:27017")` doesn't work in the global scope as the initialization code runs too early (you could try prefixing with `onready`).

Thanks for the heads up.  I think I'm going to act
