### ISSUE TITLE
No icon for ToolButton node

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#5286]
There's no icon for the ToolButton node. It shows empty in Create dialog and a generic one in the Scene Tree.

![godot windows opt tools 64_2016-06-18_21-15-23](https://cloud.githubusercontent.com/assets/5599796/16174487/fe3708e2-3599-11e6-8934-5e269d0545c7.png)
![godot windows opt tools 64_2016-06-18_21-16-06](https://cloud.githubusercontent.com/assets/5599796/16174490/00aa09e4-359a-11e6-83ea-40fd9df9893f.png)

(Calling @djrm for the rescue :wink:)

**Comment by djrm** [comment]
oh yes will check that.

By the way there are other missing node icons
- Interpolated camera
- Hinge joint
- Cone twist joint
- Generic 6 DOF joint

but some of them are trippy
