### ISSUE TITLE
GDScript 2.0: GDScript assumes typed array with custom classes contains raw classes

### ISSUE THREAD

**Issue by Uxeron** [godotengine/godot#52871]
### Godot version

4.0-dev.20210916

### System information

Windows 10

### Issue description

Typed arrays containing custom classes do not work as expected. When calling a function on an object contained in such an array, the editor shows an error "Cannot call non-static function on the class directly. Make an instance instead".

### Steps to reproduce

Create a custom class with class_name, and add a function.
Create a typed array with the custom class, such as `var typedArray: Array[CustomClass]`
Try to call the function from an object in the array, like `typedArray[0].some_func()`

### Minimal reproduction project

[TypedArrayTest.zip](https://github.com/godotengine/godot/files/7195770/TypedArrayTest.zip)

**Comment by kleonc** [comment]
Can't reproduce in v4.0.beta3.official [01ae26d31], must have been fixed somewhere along the way.

From the MRP:
![ysJouGW9WQ](https://user-images.githubusercontent.com/9283098/195982947-7e2c45ba-13ef-45fc-8523-9b3fef3a44bb.png)
