### ISSUE TITLE
Missing font oversampling support for custom scaling implementations.

### ISSUE THREAD

**Issue by HeartoLazor** [godotengine/godot#52882]
### Godot version

3.3 stable and 3.x

### System information

Windows 10

### Issue description

Issue:
`Missing font oversampling support for custom scaling implementations.`

What I expect:
`A way to set the font oversampling value in STRETCH_MODE_DISABLED, as this mode objective is custom scaling implementations.`

More details about the issue:
I required a pixel perfect solution for my game, where I can only scale the game in perfect multiples of the base size (1x,2x,3x,4x, etc) and celeste style HD font rendering (font oversampling).
Reading the [documentation](https://docs.godotengine.org/en/stable/tutorials/viewports/multiple_resolutions.html), there is a recommendation for the [integer resolution handler plugin](https://github.com/Yukitty/godot-addon-integer_resolution_handler):

> Godot currently doesn't have a way to enforce integer scaling when using the 2d or viewport stretch mode, which means pixel art may look bad if the final window size is not a multiple of the base window size. To fix this, use an add-on such as the Integer Resolution Handler.

That plugin replicates the godot internal scaling found in gdscript scene_tree with the exception of the "_update_font_oversampling" line because the method isn't available in GDScript. This plugin uses "STRETCH_MODE_DISABLED" + "STRETCH_ASPECT_IGNORE" flags scaling the base resolution in floored screen values (1x,2x,3x, etc). 
Because of this engine limitation, that plugin misses the font oversampling support, only available for "STRETCH_MODE_2D" using an internal scaling formula not compatible with all custom implementations.

I did a pull request fixing this issue (https://github.com/godotengine/godot/pull/52881)
With this commit the user can call in that plugin:
get_tree().update_font_oversampling(scale)
And have full font oversampling support in any stretch mode or any custom scaling implementation.
**As note I did the pull request at 3.x branch, but I need it for 3.3.3.stable as it is the branch We use in our project and I don't know what I need to do for this to be cherry picked for the future 3.3.4.stable, both branches are affected by this issue.**

### Steps to reproduce

- Create a project with some labels and a pixel art background. 
- Download and install this plugin: https://github.com/Yukitty/godot-addon-integer_resolution_handler
- Enable font oversampling.
- Set the project size to the same of the pixel art background.
- The plugin ensures no distortion in the pixel art background, but the labels ignores the oversampling flag.

**Comment by Calinou** [comment]
> As note I did the pull request at 3.x branch, but I need it for 3.3.3.stable as it is the branch We use in our project and I don't know what I need to do for this to be cherry picked for the future 3.3.4.stable, both branches are affected by this issue.

To ensure stability, new features are only added to the `3.x` branch;
