### ISSUE TITLE
Vulkan: Screen Space Reflections are disjointed and jagged

### ISSUE THREAD

**Issue by unfa** [godotengine/godot#52880]
### Godot version

v4.0.dev.calinou [b1063a7c0]

### System information

Manjaro Linux KDE, Radeon RX480 (amdgpu driver)

### Issue description

No matter how I tweak the settings, the Screen Space Reflections most of the time render as disjointed vertical or horizontal lines. It seems like there's some interpolation lacking that'd fill in the gaps?
![image](https://user-images.githubusercontent.com/491704/134087684-69f4a4b0-3af8-41cc-b4f5-aebc1ae3c3b4.png)

In rare cases the reflections are smooth and continuouos, even if not quite accurate to the 3D scene:
![image](https://user-images.githubusercontent.com/491704/134087885-ac1468bb-34db-455e-ae6f-ee570371bbdf.png)

### Steps to reproduce

Place a reflective object in your scene, enable Screen Space Reflections and move the camera around.

**Comment by jcostello** [comment]
Yeah SSR is broken since a long time. My input

![image](https://user-images.githubusercontent.com/1168582/134094343-11516346-4749-4d50-bf46-3f868c2e9e4f.png)

**Comment by clayjohn** [comment]
The main artifacts in the original post have been resolved. Further issues with SSR should have their own dedicated issues
