### ISSUE TITLE
The state of Ctrl+S

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#5289]
I find myself often editing a script, hit Ctrl+S to save it. But then, a few unexpected things happen:

1) When I want to commit my work in Git I find that the last opened .tscn scene was modified. After reading diffs, it shows random line order changes, but technically the files are identical.

2) So it means Godot saves the current scene when I use Ctrl+S, even when the scene is unmodified. If the scene is large, it might even slow down the process. I would expect not saving something that I didn't touched, or better, just save what I see (the script), not two files at a time.

I remember there is a separate shortcut for saving scripts. Now we can edit shortcuts, but these two are still separate and have to be different...
IMO it doesn't feels right. It should be possible to have a contextual save shortcut that saves only what there is on the focused panel (scene, script, shader...).

**Comment by reduz** [comment]
lines in .tscn should not change, this is most likely a bug, can you make a
small test scene using the datatypes (nodes?) where line orders may change?

**Comment by Zylann** [comment]
Well, hard to say which nodes exactly, it appears to be random:
![save_identical_changes](https://cloud.githubusercontent.com/assets/1311555/16177259/04147a8c-3627-11e6-8181-cd3de44dc3d9.png)
![save_identical_changes_2](https://cloud.githubusercontent.com/assets/1311555/16177260/0677fcb8-3627-11e6-8072-02ad2c31000d.png)
Last time I had a similar problem in other projects, it was because the data was inside a hash table, which doesn't preserves order (because order doesn't matters). It could be this because everytime, the lines I see changed are unordered.

Also, not only the file changes, but its timestamp too. It shouldn't be saved again when nothing changed. If you use Perforce this can be annoying because the scene file will be read-only and Godot will throw an error each time you Ctrl+S in the script editor (hence my proposal to simply have a contextual Ctrl+S for everything).

You can test the demo/2d/kinematic_char project: 
- Initialize a Git repo in it,
- Open the script on colworld (colworld.gd),
- Don't modify anything and hit Ctrl+S.
Now do a git status and see a few properties of a node have moved.

**Comment by Zylann** [comment]
What about being able to set a contextual Ctrl+S shortcut? By the way you cannot save a script if no scene is opened (unless you use a different shortcut, but it feels odd).

**Comment by vnen** [comment]
That's why we say to not put many bugs into one issue. While they might be related, it's unclear when to close it. There's #3674 about this too, maybe @reduz will fix it in this new pass of bug-fixing.
