### ISSUE TITLE
Can't "Download zip" from GitHub except default branch

### ISSUE THREAD

**Issue by ghmart** [godotengine/godot#52899]
### Godot version

any branch except default

### System information

Windows 7 (Chrome), Debian Bullseye (Firefox)

### Issue description

All download links points to default branch.

### Steps to reproduce

1. Select  "3.x" branch.
2. Press "Code" -> "Download ZIP"

**Comment by akien-mga** [comment]
We have no way to change that, that's an issue with GitHub itself.

As a workaround, you can modify the URL and replace `master` by the name of the branch you want to download, e.g.:

https://github.com/godotengine/godot/archive/refs/heads/3.x.zip

**Comment by ghmart** [comment]
Thank you so much!
