### ISSUE TITLE
kinematicbody2d doesn´t move over kinematic platform (left and right) when the collision shape is a raycast. it worked on godot 3.3.3

### ISSUE THREAD

**Issue by crapaam** [godotengine/godot#52896]
### Godot version

3.4 beta

### System information

windows/linux

### Issue description

I have a 2d platform game. it runs fine in godot 3.3.2 and 3.3.3.
When I run it in 3.4 beta, my player doesn´t move over the platform that moves from side to side.
After lots of testings, I found that the problem if because of the raycast that I use in the player's collision shape.
If I change it to a capsule, it works, but with the raycast it doesn´t move to the left and right.
The player movement is done with move_and_slide.

### Steps to reproduce

[TestMovingPlat.zip](https://github.com/godotengine/godot/files/7203493/TestMovingPlat.zip)

the attached file contains a tscn with a minimal project with the problem.

**Comment by akien-mga** [comment]
Fixed by #52902.
