### ISSUE TITLE
Tree expand/collapse arrows do not respect item margin

### ISSUE THREAD

**Issue by EricEzaM** [godotengine/godot#52895]
### Godot version

v4.0.dev.custom_build [dd75be92a]

### System information

Win 10

### Issue description

See the arrows below are not aligned correctly.
![image](https://user-images.githubusercontent.com/41730826/134176041-3370ed08-b6bc-4b5a-a71b-d1a03f58c5c0.png)

cc @pycbouh I think?

### Steps to reproduce

Make theme and set `Tree/Constants/Item Margin` to a high number, say 40. Create a tree with children, or use this theme as your editor theme and add some nodes.

### Minimal reproduction project

Or just set this theme as your editor theme:
[ed_theme_custom.zip](https://github.com/godotengine/godot/files/7203279/ed_theme_custom.zip)

**Comment by pycbouh** [comment]
Yeah, I can take a look
