### ISSUE TITLE
Error appears when i am editing a tilemap and i delete a block  scene/resources/tile_set.cpp:480 - Condition "!tile_map.has(p_id)" is true. Returned: SINGLE_TILE

### ISSUE THREAD

**Issue by NightMare1221** [godotengine/godot#52904]
### Godot version

Godot version 3.2.3 stable

### System information

Windows 10 ryzen 7 5000 AMD RADEON graphics

### Issue description

 scene/resources/tile_set.cpp:480 - Condition "!tile_map.has(p_id)" is true. Returned: SINGLE_TILE 
keeps appearing whenever i delete a tile it dosent affect me as in gameplay but it is annoying and i would like to know how to fix it 

https://user-images.githubusercontent.com/74435818/134216195-4da1e38d-6998-4e3a-82d3-46776e9c25f0.mp4

### Steps to reproduce

I dont know how to reproduce this

**Comment by Calinou** [comment]
> Godot version 3.2.3 stable

[Godot 3.2.x is not supported anymore.](https://docs.godotengine.org/en/stable/about/release_policy.html#release-support-timeline) Please upgrade to 3.3.3 and test this again.

**Comment by NightMare1221** [comment]
ok thanks

**Comment by NightMare1221** [comment]
Yup it works thank you i didnt see that there was an update
