### ISSUE TITLE
Where is the Import-Flags-Filter of Godot4? My pixel material is blurry

### ISSUE THREAD

**Issue by AtmosphereGameStutio** [godotengine/godot#52938]
### Godot version

v4.0.dev.20210916.official[104a6194f]

### System information

Win11

### Issue description

Where is the Import-Flags-Filter of Godot4? My pixel material is blurry
![1](https://user-images.githubusercontent.com/39994989/134363213-2c9e321a-60b3-4525-a650-fa04b58afd99.PNG)

### Steps to reproduce

Select a picture and view the Import tab

**Comment by Calinou** [comment]
Texture flags are now defined in the location where the texture is used, rather than where it's imported. Check the CanvasItemMaterial/BaseMaterial3D settings. You can also change the default filter for 2D and 3D in the Project Settings.
