### ISSUE TITLE
Ctrl+z and Ctrl+shift+z are broken in 3d mode

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot#52949]
### Godot version

3.3 stable

### System information

Windows 7 64-bit

### Issue description

Trying to ctrl+z undo or ctrl+shift+redo almost any node movement in 3D space does not actually do anything, and in most cases I have to resort to manually going to Scene > Undo or Scene > Redo to get anything to work. I've not determined if it has anything to do with changing things in the inspector, scene, import or files tabs which loses focus from the scene, but most of the time when I press ctrl+z undo or ctrl+shift+redo it just moves the camera in and out a little bit (zooming).

### Steps to reproduce

Move a 3D object, try to undo the movement with ctrl+z or redo it with ctrl+shift+z.

**Comment by Calinou** [comment]
> 3.3 stable

Please upgrade to 3.3.3, as old patch releases aren't supported anymore.

**Comment by elvisish** [comment]
> > 3.3 stable
> 
> Please upgrade to 3.3.3 and test this again, as [old patch releases aren't supported anymore](https://docs.godotengine.org/en/stable/about/release_policy.html#release-support-timeline).
> 
> Also, double-check whether you accidentally changed your keyboard layout. This happens if you press Alt + Shift on Windows.

This also happens in 3.4 beta. It doesn't help that ctrl is mapped to zoom. If I undo a translation move in the 3d editor, I certainly cannot redo it with keyboard shortcuts.

**Comment by snougo** [comment]
can't reproduce it on Mac (3.4 beta5)
you can go to check the editor setting to see if the shortcuts was changed or not
![Screen Shot 2021-09-24 at 5 22 43 PM](https://user-images.githubusercontent.com/64188282/134651626-90718c3d-52f6-4a5e-87bd-92dfaaf2c0e0.png)

**Comment by elvisish** [comment]
> can't reproduce it on Mac (3.4 beta5)
> you can go to check the editor setting to see if the shortcuts was changed or not
> ![Screen Shot 2021-09-24 at 5 22 43 PM](https://user-images.githubusercontent.com/64188282/134651626-90718c3d-52f6-4a5e-87bd-92dfaaf2c0e0.png)

Honestly, it's totally broken for me, I just cannot get undo or redo to work in 3D mode through the shortcut keys. Here's my settings:
![image](https://user-images.githubusercontent.com/16231628/134741485-a4731bd6-5ce5-4e04-8658-15f6a2068b7c.png)

I'm not sure how to reproduce this or help out in any way, if I do Scene > Undo or Scene > Redo, it works fine. Holding control and having it zoom when I move the mouse is ridiculously annoying and can't possibly be helping this, but I can't figure out how to disable that either.

**Comment by Calinou** [comment]
> Holding control and having it zoom when I move the mouse is ridiculously annoying and can't possibly be helping this

Did you change the 3D editor navigation scheme in the Editor Settings? Did you enable some kind of system-wide accessibility setting?

**Comment by elvisish** [comment]
> > Holding control and having it zoom when I move the mouse is ridiculously annoying and can't possibly be helping this
> 
> Did you change the 3D editor navigation scheme in the Editor Settings? Did you enable some kind of system-wide accessibility setting (even accidentally, like Windows sometimes tends to do)?

Nope, that's set to stock Godot (and I just reset it to be certain). I'm not sure what accessibility setting I'd need to check, is there a way of disabling holding control and moving the mouse to zoom?

**Comment by Calinou** [comment]
> is there a way of disabling holding control and moving the mouse to zoom?

This is definitely not default behavior. Something was changed on your system at some point. If you want to be 200% sure about this, try on a different PC or try running Godot on live Linux media.

**Comment by elvisish** [comment]
> > is there a way of disabling holding control and moving the mouse to zoom?
> 
> This is definitely not default behavior. Something was changed on your system at some point. If you want to be 200% sure about this, try on a different PC or try running Godot on live Linux media.

Sure, but is this an actual option in godot? Is it likely it could be a setting in keyboard shortcuts or a mouse option that got changed?

**Comment by Calinou** [comment]
> Sure, but is this an actual option in godot?

I don't remember seeing such an option with Godot. Do you have a graphics tablet connected to the PC by any chance?

**Comment by elvisish** [comment]
> > Sure, but is this an actual option in godot?
> 
> I don't remember seeing such an option in Godot. Do you have a graphics tablet connected to the PC by any chance?

No, it just always happens that if I hold control key and drag the mouse, it zooms. I'm pretty certain this might be what's causing the issue (since I had no problems in 2D or script edition besides changing tabs and breaking undo).

**Comment by Zireael07** [comment]
Control + drag to zoom is called Maya navigation IIRC, try unchecking that option in Godot.

**Comment by elvisish** [comment]
> Control + drag to zoom is called Maya navigation IIRC, try unchecking that option in Godot.

I've got it set to Godot default, not Maya, I specifically checked that yesterday to make sure it wasn't on Maya.

**Comment by elvisish** [comment]
> > Sure, but is this an actual option in godot?
> 
> I don't remember seeing such an option in Godot. Do you have a graphics tablet connected to the PC by any chance?

It's this horrible setting that's been causing the pain:
![image](https://user-images.githubusercontent.com/16231628/134783756-adfb2607-8e3e-4c3d-9d4c-5a5f8a6e325c.png)
