### ISSUE TITLE
Static Body `_ready()` is run before than parent (Spatial) `_ready()`

### ISSUE THREAD

**Issue by Amatrelan** [godotengine/godot#52942]
### Godot version

3.3.2.stable.custom_build

### System information

NIXOS, Windows (Steam version)

### Issue description

Static Body `_ready()` function seems to be running before than parent `_ready()` functions.
There is no clear indication why this happens and is different from normal (up to down).

![image](https://user-images.githubusercontent.com/10142805/134380272-0db5cc9e-3a94-43f5-8197-e5675b372c89.png)

Same behavior can be seen in also in Windows (Steam) version of engine.

### Steps to reproduce

I included minimal project that contains example.

- Create project
- Add Spatial
- Add Static Body as child for Spatial

On both add scripts to print in `_init()` and `_ready()` 

### Minimal reproduction project

[ready_fu.zip](https://github.com/godotengine/godot/files/7212265/ready_fu.zip)

**Comment by Calinou** [comment]
> Windows (Steam)

For the recored, the Steam binaries are identical to the binaries you can download from godotengine.org.

**Comment by pouleyKetchoupp** [comment]
This is how the scene tree is designed, `_ready()` is called on children first. You can use `_enter_tree()` instead to get calls in the proper tree order.

It's documented here:
https://docs.godotengine.org/en/stable/classes/class_node.html#description

**Comment by Amatrelan** [comment]
Well behavior is then different for different types, as you can see from screenshot there is Position3D ready run after parent, and only one I have seen to do that before is that Static Body, might be there is more but that still is mixed behavior.

If it should work as in documentation then that `Position3D` should have also called before parent.

**Comment by Amatrelan** [comment]
Ah sorry, my mistake on that one. Well now I know and thanks for pointing out.
