### ISSUE TITLE
Opening the default scene errors out before `EditorImportPlugin` finishes importing (regression)

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot#52968]
### Godot version

3.x branch - 23bb5883cb0de5455afe8b9d473f0d67d72487b3

### System information

Arch Linux

### Issue description

Opening the default scene errors out before `EditorImportPlugin` finishes importing. Opening the default scene should be delayed until after `EditorImportPlugin`s import function either error out or finish successfully.

### Steps to reproduce

Open the attached project below and keep an eye on the import process. Wait for the "Error loading" scene pop up to show up -- soon after you'll see the Editor running the import process for the included import plugins.
Close the Editor.
Reopen the project -- there should be no issues opening the default scene now.

### Minimal reproduction project

[open_default_scene_after_import.zip](https://github.com/godotengine/godot/files/7216685/open_default_scene_after_import.zip)

**Comment by akien-mga** [comment]
It's caused by #52344, CC @TechnoPorg.

**Comment by TechnoPorg** [comment]
I'm really sorry, I should have tested more! I'll fix both issues as soon as I can.

**Comment by akien-mga** [comment]
I reverted the change in the `3.x` and `3.3` branches for now to solve the regressions. The change is still present in `master` so that it can be debugged and fixed (or eventually reverted if a fix can't be found, but the original issue it fixes is also valid).
