### ISSUE TITLE
Wrong SphereMesh shading in 3.4 beta 5 

### ISSUE THREAD

**Issue by Schroedi** [godotengine/godot#52965]
### Godot version

3.4 beta 5 

### System information

MacOS M1

### Issue description

The default shading seems to be broken. The shading in beta 5 looks as if the light comes from the top, even though the directional light comes from the upper left in the screenshots.

The issue does not occur in Beta 4

### 3.4 Beta 5
<img width="3120" alt="3 4 beta 5 " src="https://user-images.githubusercontent.com/97124/134480533-da787033-399c-4e08-8299-e9229583917e.png">

### 3.3 Stable
<img width="3120" alt="3 3" src="https://user-images.githubusercontent.com/97124/134480547-d4d9052b-ea8f-4b53-b083-350afdbaa680.png">

### Steps to reproduce

Create a scene with a mesh and a directional light.

### Minimal reproduction project

[ExpeditionSim.zip](https://github.com/godotengine/godot/files/7216207/ExpeditionSim.zip)

**Comment by akien-mga** [comment]
Sounds like a regression from #51995, CC @drcd1 @JFonS (haven't tested building with this change reverted to confirm yet).

**Comment by Schroedi** [comment]
I can also confirm that using a capsule instead of a sphere does not result in wrong shading.

**Comment by akien-mga** [comment]
I confirmed the bug in the `master` branch too (27417c065d992cef48f28ff3c9eb9ac6c15138aa).

For now I'll revert the cherry-pick of #51995 in the `3.x` branch to solve it in the next 3.4 beta. Keeping this issue open for 4.0 as I did not revert #51995 in `master`, so it still needs a regression fix (which can then be backported to `3.x` together with the original fix).
