### ISSUE TITLE
Double-click to select full text in LineEdit does not working

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#52975]
### Godot version

8c8feb3ebdeeeee89133fc22516bab94801b5a09

### System information

Windows 10

### Issue description

It's possible to select a text by double-clicking at the end of LineEdit in 3.x:
![select_3 x](https://user-images.githubusercontent.com/3036176/134528429-bd9058dd-4fe7-44de-8b24-a2912dab5868.gif)

But it's not possible in 4.0:
![select_4 0](https://user-images.githubusercontent.com/3036176/134528602-f824ca1e-8516-458e-a6e1-89e716f23006.gif)

### Steps to reproduce

You can observe it in the LineEdit in the FileSystem ^^

### Minimal reproduction project

Too easy to reproduce

**Comment by jmb462** [comment]
The problem is that **double clic** word selection is broken after the last word.
Because of that, **triple clic** whole text selection is never detected (triple clic timer is not correctly updated)
