### ISSUE TITLE
Inconsistent `EditorImportPlugin` extensions detection in FileSystem Dock

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot#52995]
### Godot version

3.x branch at 23bb5883cb0de5455afe8b9d473f0d67d72487b3

### System information

Arch Linux

### Issue description

Registered `EditorImportPlugin` extensions are no longer showing up consistently in the FileSystem Dock on subsequent Editor restarts.

Seems to be caused by #52344, which is related to issue #52968.

### Steps to reproduce

1. Open the attached project.
2. Search for 'tmx' on the FileSystem Dock -- only the file `level1.tmx` should show up and if it does, move to step 3. If `level1.tmx` doesn't show up on the search, the issue has been reproduced.
3. Close the attached project.
4. Repeat steps 1 through 3 until the issue has been reproduced in step 2. The issue can usually be reproduced within 10 tries or so.

### Minimal reproduction project

[editor_import_extension_not_showing.zip](https://github.com/godotengine/godot/files/7221759/editor_import_extension_not_showing.zip)

**Comment by Rubonnek** [comment]
CC @TechnoPorg.

**Comment by akien-mga** [comment]
Same as https://github.com/godotengine/godot/issues/52968#issuecomment-928051500, I reverted the change in `3.3` and `3.x` so this should now only affect `master`.
