### ISSUE TITLE
Vulkan: SoftBody3D is incorrectly culled due to its visibility AABB not being updated

### ISSUE THREAD

**Issue by jcostello** [godotengine/godot#52992]
### Godot version

v4.0.dev.custom_build [88b347dc2]

### System information

Ubuntu 21.04. RTX 2060

### Issue description

This issue is very strange but like the title says. If the softbody plane mesh start above the camera, it is complete invisible even if the soft body is in direction with the camera view.

### Steps to reproduce

Use the InvisibleCloth.tscn scene from the Minimal reproduction project

### Minimal reproduction project

[Godot 4.0 SoftBody.zip](https://github.com/godotengine/godot/files/7221361/Godot.4.0.SoftBody.zip)

**Comment by Calinou** [comment]
This happens because the visibility AABB isn't automatically adjust to account for the displayed vertices. I'm not sure if it's possible to do this in a cheap way.

In the meantime, increase **Extra Cull Margin** on the mesh.

**Comment by jcostello** [comment]
Good to know that. Since this is not related to soft bodies then the issue can be closed or rename to explain the cause

**Comment by pouleyKetchoupp** [comment]
> This happens because the visibility AABB isn't automatically adjust to account for the displayed vertices. I'm not sure if it's possible to do this in a cheap way.

Soft bodies are supposed to update their AABB after calculating the new vertex positions, but there's probably a bug either in godot physics or in the vulkan renderer.
https://github.com/godotengine/godot/blob/30cf49e8d0325759b36af698f0c08d95629d1e09/scene/3d/soft_dynamic_body_3d.cpp#L90

@jcostello Do you know if it happens also in 3.x or just in 4.0?

**Comment by jcostello** [comment]
@pouleyKetchoupp 4.0

**Comment by James103** [comment]
Can confirm using the originally linked project in Godot 4.0 alpha 1.

**Comment by James103** [comment]
Still occurs in Godot 4.0 alpha 4 with the originally linked project.
Workaround: Move the SoftBody so that it is in view of the Camera or increase Extra Cull Margin.
