### ISSUE TITLE
Softbody simulation misses a lot of collisions

### ISSUE THREAD

**Issue by jcostello** [godotengine/godot#52991]
### Godot version

v4.0.dev.custom_build [88b347dc2]

### System information

Ubuntu 21.04. RTX 2060

### Issue description

Collisions with soft-bodies sometimes works, others it doesn't. Is a roulette

### Steps to reproduce

Use the MissingCollision.tscn scene from the Minimal reproduction project

### Minimal reproduction project

[Godot 4.0 SoftBody.zip](https://github.com/godotengine/godot/files/7221356/Godot.4.0.SoftBody.zip)

**Comment by peastman** [comment]
Your project is working correctly for me in the latest development code.  Possibly the problem has gotten fixed already?

**Comment by akien-mga** [comment]
Closing based on the above comment. Please let us know if you can still reproduce it.
