### ISSUE TITLE
Moving around in the 3D viewport

### ISSUE THREAD

**Issue by Ilya-Gazman** [godotengine/godot#53]
Hi,

I just lunched your editor for the first time.
Here are some UI things that will make it more easy to understand.

 - I do not understand how to move. I open the 3D Platformer project. And I wanted to see how the scene looks like. I was only been able to zoom in and zoom out, I wasn't been able to modify my camera view to move on the x or the y coordination. Even checked the right mouse button.
 - Where do I see the animation editor? I clicked on the player icon, and I found it on screen. Than I wanted to see how you made it. All I been able to find is a scrip. May be it was your animation, but I was expecting to see resources. If you have a script animation you need to tell me some how that it's a script.

Hope it helps.

Ilya

**Comment by akien-mga** [comment]
Has there been progress made on this topic since Feb 2014?

**Comment by sunnystormy** [comment]
Has anybody been working on this? I have a trackpad-based laptop, so I don't have a middle mouse button. It would be great to get some middle-mouse button emulation working for the 3D viewport. Please fix!

**Comment by sunnystormy** [comment]
@reduz @akien-mga Would it be okay if I started working on this? Also, any advice on which classes to check out?

**Comment by akien-mga** [comment]
You would be very welcome to get started on this issue! Don't hesitate to discuss here what you have in mind to get some feedback about the implementation.

As for the classes to check out, you should probably search for the plugin that corresponds to the viewport in the 3D editor. From a quick glance I'd say it's likely ``tools/editor/plugins/spatial_editor_plugin.cpp``, though you might also have to modify some of the nodes used in this plugin to get them to accept the proper input, I'm not sure.

**Comment by nunodonato** [comment]
The best way to navigate a 3d scene would be to mimic Blender's "fly-mode". Its so much faster than having to press buttons here and there to adjust the camera

**Comment by sunnystormy** [comment]
@nunodonato @akien-mga What I'm probably going to end up doing first is create an "emulate 3-button mouse" option in the settings that will behave just like it does in Blender. As for getting that into the spatial_editor, the input statement beginning at line 804 looks like a beast. It appears that this class could benefit from better encapsulation... :smirk_cat:

**Comment by sunnystormy** [comment]
@akien-mga So... I got it to work by adding two lines of code... >_> Basically, my fix allows you to press either the "shift" or "alt" buttons while the cursor is inside of the editor, and the view will pan/orbit accordingly. (Note that this is mitigated by any mouse button presses. So, you don't need to press any mouse buttons to get these effects, just the shift/alt keys.) The next question to ask is if this should be default behavior, or should it be toggled in the settings? If you want it to be optional, then I'll need some assistance with doing that. :smile_cat:

**Comment by sunnystormy** [comment]
@akien-mga @reduz Just want to check if you want this to be optional or not? Otherwise, I'm going to go ahead and push up my changes. Please let me know!

**Comment by raould** [comment]
Win 7 32bit / Godot 2.1
desktop computer with mouse
shift and ctrl don't do anything in the 3d window? it seems?
(middle mouse button for rotation works, and scroll wheel does zoom ok.)
i am used to them from using Godot on a linux laptop with a trackpad.
i wand them here as well :-)

**Comment by deberle** [comment]
I am still having trouble navigating in Godot on a MacBook. Command/Alt/Ctrl/Shift + drag, 2 finger drag seem to have no effect!

**Comment by RikKargones** [comment]
I think some UI controls from Cinema 4D will be useful too - at least for new in engine, what uses trackpades and not familiar with Blender and other 3D-modeling programs. Pressing left mouse button instead of any on keyboard (and you should know which!) working a bit more controllable and intuitive too, in my opinion.

![UI](https://user-images.githubusercontent.com/58859344/184477911-206c25a9-736a-497d-9b52-93feb848e0e9.png)

1 control: Move.
2 control: Zoom. Moving left or back is zoom-out, right or forward - zoom-in.
3 control: Rotrate.

**Comment by Calinou** [comment]
@RikKargones Please use the [godot-proposals Discussions tab](https://github.com/godotengine/godot-proposals/discussions) for feature proposals.

**Comment by RikKargones** [comment]
> Please use the [godot-proposals Discussions tab](https://github.com/godotengine/godot-proposals/discussions) for feature proposals.

Oh, I don't know about what. Thanks, I'll write about this where too.
