### ISSUE TITLE
Font preview in import dialog file browser

### ISSUE THREAD

**Issue by ip** [godotengine/godot#530]
Font preview in import dialog file browser, like in Blender. Would be handy :)

**Comment by akien-mga** [comment]
Preview has been implemented in the file browser, we just need to check if it works for font importing.

**Comment by akien-mga** [comment]
I confirm there is no font preview in the import dialog file browser as of bd736e5.

**Comment by akien-mga** [comment]
To clarify: there is proper font preview in the "Import Font" dialog after a font has been selected in the file browser. But this issue asks for (AFAIU) TTF/OTF font preview directly in the file browser, to be able to pick the right font more easily.

This brings the question to know what should be displayed, as we can't possibly display all letters of the latin alphabet on the thumbnail; maybe the letters 'Az' or something, written with the font?

**Comment by vnen** [comment]
As a reference, this is how Windows displays fonts in the explorer:

![explorer_2016-07-19_20-27-16](https://cloud.githubusercontent.com/assets/5599796/16969978/3b48401c-4def-11e6-8d2c-9e8eb5168f9d.png)

**Comment by volzhs** [comment]
What about this way as Photoshop does.

![image](https://cloud.githubusercontent.com/assets/8281454/16976033/d29b836a-4e86-11e6-8ae2-e244ef0a2b15.png)

**Comment by akien-mga** [comment]
Since the editor uses FreeType, it should be relatively easy to generate such previous. Since it's for {Editor,}FileDialog, I guess the Windows style as shown by @vnen above makes the most sense.

**Comment by flashyincceo** [comment]
What do you think about this style of displaying the font samples? 

I found the default file icon to be a little distracting, so I hid it for fonts. It's a work in progress, so I'd really appreciate any ideas or feedback!

![screen shot 2018-04-15 at 8 30 19 pm](https://user-images.githubusercontent.com/18668880/38788377-f8b5f9de-40f8-11e8-9297-4e6dcb7007fa.png)
![screen shot 2018-04-15 at 8 30 36 pm](https://user-images.githubusercontent.com/18668880/38788378-f8c3139e-40f8-11e8-8ea0-4a29f52ba5e9.png)

**Comment by zaniar** [comment]
@flashyincceo looks good enough for me

Is it possible to have more character in the preview when the icon is large?

**Comment by flashyincceo** [comment]
I appreciate the suggestion, but I'm not quite sure I understand the idea. Is it to have a longer font sample "Abcdef" vs. "Abc" for those fonts that don't completely fill the width of the icon?

**Comment by zaniar** [comment]
@flashyincceo I think having more character will provide more useful preview of font. Not just "Abc" or "Abcdef", but A to Z, or more. That way we can see differences between fonts in a glance more clearly.

**Comment by vnen** [comment]
I personally think `Abg` is enough, let's you see a capital letter, an ascent, and a descent. This is not like the font selector of a word processor, it's just so you can distinguish the few fonts you might have in your project.

**Comment by mhilbrunner** [comment]
Closed by https://github.com/godotengine/godot/pull/18234
