### ISSUE TITLE
2nd click of double clicking with (left) mouse button gets registered as FALSE for Input.is_action_pressed()

### ISSUE THREAD

**Issue by fry-** [godotengine/godot#5300]
**Operating system or device - Godot version:**
Fedora 23 KDE - Godot custom build from 5th June 2016

**Issue description** (what happened, and what was expected):
When double clicking with the left mouse, the 2nd mouse click gets registered as FALSE for Input.is_action_pressed(). Double clicking with a keyboard button works fine, both clicks get registered as TRUE. Surprisingly, this issue just applies to the left mouse button, the right button works as expected.

**Steps to reproduce:**
Download the demo below. make a double click with the arrow-up button and hold the button down after 2nd press. you will notice that the player keeps jumping, so Input.is_action_pressed = TRUE.
retry that with the left mouse button, with keeping the left mouse button pressed after the 2nd click of the double-click. you will notice that the player does not jumps while pressing down the button, so Input.is_action_pressed = FALSE.

**Link to minimal example project** (optional but very welcome):
Check this game at following commit as a demo:
https://github.com/fry-/juck/tree/383ef70a2c4c5b15d6b8c76b242cb02bbe3bb475
The input logic is in player.gd, at line 30-40.

**Comment by jtaart** [comment]
I also notice this bug. I found this message on http://godotdevelopers.org/index.php?topic=14207.0 

I think its the same bug also, I hope this helps:

> Ifrit  Guest
> 
> Godot 2.0 Beta - Double click overrides action mapping
> « on: February 11, 2016, 01:05:53 PM »

> When I have an action assigned to a mouse button, that action is only set to pressed for the first click of a double click. This seems wrong to me
> It either forces you to manage the mouse buttons yourself, bypassing the InputMap and built in action handling, or you have to live with mouse button actions being a bit sluggish when repeated.
> **Ive fixed this locally by removing rows 211-212 in input_default.cpp, and that alleviates my problem.** I have done exactly zero investigation into what other crap that change might break though, but it works for my usecase.

**Comment by akien-mga** [comment]
The lines referred to are https://github.com/godotengine/godot/blob/b6b33e8886c4e1515164925dddf55d9ee687456f/main/input_default.cpp#L211-L212, i.e. in the current master HEAD: https://github.com/godotengine/godot/blob/ccf6b31/main/input_default.cpp#L289-L290

**Comment by akien-mga** [comment]
Is this still valid in the current master branch?

**Comment by reduz** [comment]
i rewrote the action system and see nothing preventing doubleclick from working, so closing this. IF anything like this everh appens again, let's hope it's reported

**Comment by jtaart** [comment]
Was the action system rewrote for 3.0 only, because it still seems to do this in 2.1.4

**Comment by akien-mga** [comment]
Yes, the above comment refers to the development branch, not 2.1.
