### ISSUE TITLE
Thread.start uses outdated (object, method name) parameters instead of Callable

### ISSUE THREAD

**Issue by briansemrau** [godotengine/godot#53014]
### Godot version

4.0.dev

### System information

Windows 10

### Issue description

Thread::start should support using callables. It looks like a function that was left behind in the switch to callables everywhere.

This is the current function definition:
```cpp
// core_bind.h, line 556
Error start(Object *p_instance, const StringName &p_method, const Variant &p_userdata = Variant(), Priority p_priority = PRIORITY_NORMAL);
```

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
cc @KoBeWi

**Comment by KoBeWi** [comment]
Pretty sure it's not difficult to solve, check #45698 for example.
