### ISSUE TITLE
Punctual Lights from gltf / glb files import with 0 range and attenuation values

### ISSUE THREAD

**Issue by timshannon** [godotengine/godot#53019]
### Godot version

3.4-beta5

### System information

Ubuntu 20.04.3 LTS

### Issue description

Since 3.4 punctual lights from scenes imported from gltf or glb files seem to all have 0 range and attenuation.  Color seems to come across fine.   

I'm not seeing any errors in the output window.

In my workflow my gltf files come from blender, but I can replicate it (with the attached project) with the Lights gltf sample model here (https://github.com/KhronosGroup/glTF-Sample-Models/tree/adf2abe718a61a6859b29fab481bfbbdfc05df24/2.0/Lights).

### Steps to reproduce

1. Start a brand new empty project in Godot 3.4 (beta 4 or 5)
2. Download the gltf file here: https://github.com/KhronosGroup/glTF-Sample-Models/tree/adf2abe718a61a6859b29fab481bfbbdfc05df24/2.0/Lights
3. Import it into the project
4. You could turn down the ambient environment light to make it more apparent.

If you do the same in 3.3, the lights show up closer to what is expected.

### Minimal reproduction project

[test3.3.zip](https://github.com/godotengine/godot/files/7227175/test3.3.zip)
[test3.4.zip](https://github.com/godotengine/godot/files/7227176/test3.4.zip)

**Comment by Calinou** [comment]
cc @fire

**Comment by fire** [comment]
Will investigate. Worked with this with @aaronfranke too.

**Comment by aaronfranke** [comment]
I did a bisect on the master branch and found that this is a regression from #34193 (4b4efd26740d4912e66bf8503e8f146ed2be33b7).

The default values for the light fields were set to 0 (` modules/gltf/gltf_light.h` lines 45 to 50), while before they had non-zero values (`editor/import/editor_scene_importer_gltf.h` lines 214 to 219). Making them 0 was a mistake.
