### ISSUE TITLE
Nodes w/ script disappear on scene switch tab event

### ISSUE THREAD

**Issue by dirigonaut** [godotengine/godot#53031]
### Godot version

v3.3.3.stable.official [b973f997f]

### System information

Windows 10, GLES 3.0, NVIDIA GeFroce RTX 3080/PCIe/SSE2

### Issue description

Abstract:
I have two scenes that I have put together a couple of scripts to create my own way point graph system since godot does not provide one by default. This script is a [Tool](https://docs.godotengine.org/en/stable/tutorials/misc/running_code_in_the_editor.html) Script that I use to visualize the nodes and their paths between each other. When I swap tabs between scenes my way point Node2Ds are gone but when I close them and reopen them they are back. This is an issue cause if I save either of these scenes once the nodes have disappeared I do not get the nodes back on a close/open.

Scripts:
 - Graph: Crawls its children to get all their information and draw lines and dots for them
 - Graph_Node: Holds info for who it connects to. If no data exists it will try to attach itself to the node before and after.
    - Nodes need to have naming structure: ``` {String}_#``` with the # being an incrementing ID (EX: Node_1, Node_2, Node_3)

Scenes:
I have 2 Scenes that have identical parts but not identical data(node positions are different). 
 - Each is setup the exact same with a root Node2D named after the level(Scene_1, Scene_2). 
 - Childed to this is another Node2D called Graph with the attached Graph.gd script. 
 - This Node has 3 children with the Graph_Node.gd Script attached to them.

### Steps to reproduce

Step 1: Open Scene_1
![Screenshot_1](https://user-images.githubusercontent.com/35875808/134729363-e5c1436a-462c-40f1-abaf-0068fe8eff1c.png)
 
Step 2: Open Scene_2
![Screenshot_2](https://user-images.githubusercontent.com/35875808/134729438-04a64bf8-26fd-4812-8b26-302df69d1e3f.png)

Step 3: Tab back over to Scene_1:
![Screenshot_3](https://user-images.githubusercontent.com/35875808/134729479-afbcb1ef-1570-4477-be5d-a214707f3c10.png)

Step 4: Tab back to Scene_2
![Screenshot_4](https://user-images.githubusercontent.com/35875808/134729503-e35e8456-5f6a-4f38-b9cb-56f58a8ed68a.png)

Step 5: Close both Scene_1 and Scene_2
![Screenshot_6](https://user-images.githubusercontent.com/35875808/134729573-7d158b6e-6883-4319-a5ad-e6cafd2965e6.png)

Step 6: Reopen Scene_1 or Scene_2
![Screenshot_7](https://user-images.githubusercontent.com/35875808/134730286-8c0b1436-0bb9-455d-a8c4-e9c4b64b157e.png)
![Screenshot_8](https://user-images.githubusercontent.com/35875808/134730322-bf030233-1007-4f10-8e08-70257301b1ae.png)

Godot Console After all of this:
![Screenshot_5](https://user-images.githubusercontent.com/35875808/134729921-5547d2e1-536b-4782-8158-876f5bd99601.png)

### Minimal reproduction project

[Bug_Project.zip](https://github.com/godotengine/godot/files/7228029/Bug_Project.zip)

**Comment by kleonc** [comment]
@dirigonaut in your `Graph.gd` you have:
```
func _exit_tree():
	self.queue_free()
```
so when you switch the scene tab (and the previously current scene is being removed from the editor's scene tree) your `Graph` node is being freed (it's a `tool` script so your code is running in there).

I don't see a bug in here.

**Comment by dirigonaut** [comment]
Ah I was not aware that swapping tabs would call the _exit_tree() which in retrospect makes perfect sense. With this info I can make a solution that takes this functionality into account. Thank you for the prompt response, and to the rest of you all for making godot a thing.
