### ISSUE TITLE
Potential bug is camera preview, reg. aspect ratio . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot#53048]
### Godot version

3.4 latest . .

### System information

Windows 10 . .

### Issue description

Uh, not sure this is a bug, tried making an accurate 16:9 mesh, for letterboxing, idea was to scale it, to add letterbox - stuff . . .

Made a mesh, in Blender, and scaled it to match 16:9, 1280x720p has same aspect - ratio, 1.777777 . . However, the lines don't match up, see here . . .

![Skærmbillede (2280)](https://user-images.githubusercontent.com/83387915/134764198-9a565ba7-970b-445a-a0d2-7e9ccfcfd31a.png)

Well, shouldn't the yellow line, project settings is set, to 1280x720, match up with the well reference mesh, anyway, this might be a problem, later in rendering, well not sure it's important . . .

Not really sure why they don't match up, maybe it leads to distortion, later, when camera renders scene, or it isn't accurate, to the pixel ratio, well might not even be bug, not sure why it happens, thanks . . . .

### Steps to reproduce

Make a mesh, in Blender, and scale a center quad, to match 16:9, some ratio . . Then, make this . . <3

![Skærmbillede (2281)](https://user-images.githubusercontent.com/83387915/134764289-c93b7ea2-1427-45b4-88d3-8c2bd721f138.png)

I just took center square, after 3x3 sub - division, scaled the x to 1.6, and y to 0.9, and put it in Godot, in front of the camera, since aspect ratio is same for 1280x720p, 1.777777, well, not sure why the lines don't add up . . 

<img width="406" alt="Skærmbillede (2282)" src="https://user-images.githubusercontent.com/83387915/134764348-9b500f12-7a3d-4007-9b1d-3bea6fdc346f.png">

Well, it might also lead to camera not sort-of accurately rendering a scene, or lead to, something like stretching, or so . . .

Well, have several plans, for instance make something like Wind in the Willows, it'd be nice if things, were more accurate . . :OO Thx . . .

### Minimal reproduction project

Like above, takes a few minutes to make a reference mesh, it's more about accuracy, not sure . . . .

**Comment by charlesmlamb** [comment]
Well, atm. Godot doesn't have a sort-of preview, for cinematics, made a prototype, mind that, I only make cinematics, if I have a project that makes sense or, has well character . . . It's I think a calm, well as ' good as it gets ' preview, for working in cinematics, it's not finished . . . <3

![Skærmbillede (2283)](https://user-images.githubusercontent.com/83387915/134765222-3cfb155a-dbcc-4222-a2fb-02181f0a34aa.png)

Anyway, it's a nice way to frame a shot, also modest, calm, simple . . So, if I could suggest, assuming there's a worthy reason, to even make 'cinematics', well I feel best working like this, looks pretty cool . . . There could be a few variations of this, perhaps make a node, name it CinematicCamera3D, or PreviewCamera <3 Thx . . . .

**Comment by Calinou** [comment]
The default project window size is 1024×600. This resolution is *not* 16:9, it's roughly 1.71.

**Comment by charlesmlamb** [comment]
Yes, but my resolution is 1280x720, not 1024x600 :OO . . .

**Comment by charlesmlamb** [comment]
Ok, it works, well made Godot into a pro - cinematic software suite . . .

![Skærmbillede (2289)](https://user-images.githubusercontent.com/83387915/134768666-5857d410-ac18-4583-b900-98b4db8652fc.png)

Well, one can do nice things, with bit tweaking <3

**Comment by Calinou** [comment]
Closing, as this is not an issue within Godot.
