### ISSUE TITLE
rand_seed has equal random number and new seed

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#5305]
The function `rand_seed(int)` returns an array that supposedly contains the returned random number and the new seed. But both are always equal, so there's no reason to return an array.

You can see that this function makes a new seed but returns pretty much the same number (unless the new seed is negative): https://github.com/godotengine/godot/blob/eff0bd2d48b57855b8895c6798cac7df05851e74/core/math/math_funcs.cpp#L43-L60

There's some `#if 1`'d code, so I guess this function changed but kept returning array for compatibility.

**Comment by reduz** [comment]
if it ś going to break compatibility, let's do it for 3.0

**Comment by vnen** [comment]
`Math::rand_from_seed()` now has a different seed than the random number, so this is no longer valid.
