### ISSUE TITLE
Can't set tile size of atlas

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#53073]
### Godot version

c7f67da

### System information

W10

### Issue description

It's impossible to set tile size in an atlas. `tile_size` property always says 0 and tiles are stuck on 16x16 pixels.

### Steps to reproduce

1. Create a TileMap with TileSet
2. Try to change `tile_size` of an atlas
![image](https://user-images.githubusercontent.com/2223172/134787555-4cd02b6f-7d11-40eb-8564-7865eda8d83d.png)

**Comment by lmurray** [comment]
This was caused by the renaming of the property to "texture_region_size" in https://github.com/godotengine/godot/pull/52433
