### ISSUE TITLE
LineEdit custom font not showing properly

### ISSUE THREAD

**Issue by ulvido** [godotengine/godot#53082]
### Godot version

3.4-beta5

### System information

elementary OS 6, GLES2, NVIDIA® GeForce® GT® 540M,nvidia-driver-390

### Issue description

`LineEdit` custom font not showing properly latin-extended characters with `HTML` export on `Linux`
**windows os works fine, please test on ubuntu like distross**

preview works fine in theme editor. 

but in the browser extended characters converted different characters

see gif animations below with same key pres -> ğ ü ş ö ç

what can cause this problem?

### THEME PREVIEW WORKS FINE - GODOT
![preview_working](https://user-images.githubusercontent.com/27722274/134799424-8e52d5b6-77aa-4aa5-b12d-bd5e467146ae.gif)

### HTML EXPORT NOT WORKING - BROWSER
![html_not_working](https://user-images.githubusercontent.com/27722274/134799421-0a1423c5-82b6-4082-9933-9d40ee2150fc.gif)

### Steps to reproduce

create a custom theme resource and add a dynamic font and load a latin extended font for example mine is [Press Start 2P](https://fonts.google.com/specimen/Press+Start+2P)
in Default Preview tab preview test LineEdit and see it works when you type ğ ü ş ö ç 
save theme as new_theme.theme.
create a scene with User Interface (parent node type Control)
go to theme section for node and select new_theme.theme
create a new LineEdit node as child
go to Project > Export > add > HTML5
select the build templates (if you downlaoded the Minimal reproduction project custem templates are included at `build/template/v3.4-beta5`)
close the export window and press HTML preview button at top right
type same characters -> ğ ü ş ö ç and see they are converted to -> ] ] ; , .

### Minimal reproduction project

[issue_font.zip](https://github.com/godotengine/godot/files/7230966/issue_font.zip)

**Comment by ulvido** [comment]
### UPDATE

works on firefox but not chrome

![chrome_vs_ff](https://user-images.githubusercontent.com/27722274/134800897-18131b4c-e5cb-4182-8e42-42b3b472e127.gif)

**Comment by Calinou** [comment]
cc @Faless

**Comment by alexv81** [comment]
The problem was solved by itself. It is likely that the problem was in Chrome and after updating the system everything worked as it should.

**Comment by Calinou** [comment]
> The problem was solved by itself. It is likely that the problem was in Chrome and after updating the system everything worked as it should.

Alright, closing as resolved then.
