### ISSUE TITLE
Vulkan: Can't use a noise texture as uniform texture sampler in shader

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot#53089]
### Godot version

v4.0.dev.calinou [de917008f]

### System information

Linux Manjaro, Vulkan, Intel Kaby Lake

### Issue description

Just for fun, I'm trying to write a sky shader for my racer game (it should give improved performance over 2d+viewport+panorama hack used in 3.x)

I discovered that while I can assign a .png noise texture off the net, I CAN NOT assign a NoiseTexture, be it from clicking the New NoiseTexture from the dropdown, or from quick open'ing a saved .tres.

(Possibly related, some other places are also wonky: I can't assign a texture in a mesh's slot, I have to use the override - both result in spewing a load of errors about uniforms not set. This also applies to trying to put a NoiseTexture as a night_sky texture of the PhysicalSky)

### Steps to reproduce

See above

**Comment by briansemrau** [comment]
Have you tried reloading the scene? This sounds related to #51361

I have found noise textures to be more annoying, triggering that issue more often than regular textures.

**Comment by Zireael07** [comment]
I tried save and reopen, it behaves as though no texture was set upon reopening.

**Comment by briansemrau** [comment]
For me it works if I save, then do [Menu] Scene -> Reload Saved Scene
