### ISSUE TITLE
Wrong offset of root TreeItem when hide_folding is enabled for the parent Tree

### ISSUE THREAD

**Issue by floppyhammer** [godotengine/godot#53084]
### Godot version

v4.0.dev.calinou [c7f67dacc]

### System information

Windows 11, Vulkan Clustered

### Issue description

When `hide_folding` is enabled, `hsperation` is used instead of `item_margin` for offsetting the root item.

![image](https://user-images.githubusercontent.com/28705694/134802303-0e2dde49-e0f2-4316-a029-540b6a6d7a7f.png)

### Steps to reproduce

Open the reproduction project, run the only scene, click right mouse button to add tree item.

### Minimal reproduction project

[TreeTest.zip](https://github.com/godotengine/godot/files/7231098/TreeTest.zip)

**Comment by pycbouh** [comment]
Well, that’s by design.

https://github.com/godotengine/godot/blob/84faf3954417c0ee58df79c0d2cc09309825878a/scene/gui/tree.cpp#L1607

 I don’t know why it’s by design, but it’s how it’s been since forever. So I’m not sure it’s a bug, since someone decided to do it specifically.
