### ISSUE TITLE
Spatial camera unselectable in editor and icon gizmo not shown

### ISSUE THREAD

**Issue by z1dev** [godotengine/godot#53083]
### Godot version

v3.4.beta5.official

### System information

Windows 10 gles 3

### Issue description

As shown on screenshot:
![image](https://user-images.githubusercontent.com/30132426/134799930-29ee368e-8c60-47d2-bb7b-e0d1154e813a.png)
Worked in 3.3.2 and 3.3.3 where I also tested.
![image](https://user-images.githubusercontent.com/30132426/134799993-b233752c-9f1d-4806-8c34-7495715158ee.png)

### Steps to reproduce

Create a 3d scene and add camera with the + button. It doesn't matter if it's an old scene or just created.

*Bugsquad edit (keywords for easier searching): Camera3D*

**Comment by z1dev** [comment]
Just an addition: lights and other nodes that show up as similar icons seem to work.

**Comment by Calinou** [comment]
The camera icon gizmo was removed by design: https://github.com/godotengine/godot/pull/35784

**Comment by z1dev** [comment]
It was confusing, but it also prevents selecting the camera by clicking on it. It's premature to remove the icon if it causes this issue.
