### ISSUE TITLE
AnimationPlayer: Bezier Curve selection StyleBox background appears visually offset

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#53088]
### Godot version

v4.0.dev.20210924.official [5e4a71200]

### System information

manjaro Gnome 21, AMD R7 200 series, Intel i3 3.0 GHZ,8GB RAM

### Issue description

When you create a AnimationTrack with bezier, the selection is offset:
![image](https://user-images.githubusercontent.com/58845030/134807851-0683b7e6-b15b-4c41-876d-6ca3bf5fb7c6.png)

as you can see on the left, the selection is offset!

### Steps to reproduce

* Create AnimationPlayer
* Create an Animation with Bezier
* should see offset

### Minimal reproduction project

N/a

**Comment by Calinou** [comment]
@nonunknown Can you reproduce this in 3.3.4?

**Comment by nonunknown** [comment]
@Calinou this is in 3.4 beta 5:

![image](https://user-images.githubusercontent.com/58845030/135768056-90a0b6c7-e233-471f-b05e-c5f562086a58.png)

**Comment by KoBeWi** [comment]
Looks fixed on master, but maybe it's some system-specific thing.
![image](https://user-images.githubusercontent.com/2223172/171949216-ce1f8528-d887-44f4-82a4-666e3961148f.png)
@nonunknown Can you test in alpha 9?

**Comment by nonunknown** [comment]
I've tried to reproduce, but dont know how to go to bezier editor

![image](https://user-images.githubusercontent.com/58845030/171996674-c496d6d2-11a7-49e6-88c3-07dfff88e634.png)

**Comment by KoBeWi** [comment]
Create a bezier track and click this icon at the bottom:
![image](https://user-images.githubusercontent.com/2223172/171996728-40a0e507-3024-4822-9223-2b84dabe7998.png)

**Comment by nonunknown** [comment]
working flawlessly, fixed!!!

![image](https://user-images.githubusercontent.com/58845030/171996778-874c10ed-665f-45ef-bd95-024186a898e6.png)
