### ISSUE TITLE
HTTPRequest gzipped response is not automatically decompressed when saved to file

### ISSUE THREAD

**Issue by Variable-ind** [godotengine/godot#53085]
### Godot version

3.4-beta5

### System information

Linux Mint 20.1 Cinnamon

### Issue description

I made a project that can download a webpage in form of HTML text in Godot 3.3.3 but it doesn't work as expected in Godot 3.4-beta5
Here's the webpage downloaded using Godot 3.3.3
![3_3_3](https://user-images.githubusercontent.com/77773850/134803327-7bf96436-dbfd-45b8-97e0-84a9b206f502.png)

And here's the output of the same webpage using Godot 3.4-beta5
![3_4 beta5](https://user-images.githubusercontent.com/77773850/134803382-4bf091e9-dd13-465f-818e-75eafe4ab46f.png)

### Steps to reproduce

1. Open the project using both Godot 3.3.3 and then Godot 3.4 beta5 (or any other beta version)
2. Then open the OpenMe.txt
3. Output will be completely different

### Minimal reproduction project

[3_3_3 vs 3_4_beta5 download test.zip](https://github.com/godotengine/godot/files/7231170/3_3_3.vs.3_4_beta5.download.test.zip)

**Comment by akien-mga** [comment]
I can confirm the bug with the provided MRP, and seems to happen as far back as 3.4 beta 1. Further back between 3.3 and 3.4 beta 1 would require a proper git bisect.

**Comment by akien-mga** [comment]
Fixed by #53800.
