### ISSUE TITLE
Default font in editor is non-unicode

### ISSUE THREAD

**Issue by ip** [godotengine/godot#531]
If assign unicode font to Control, it appears in left side of screen (after hitting Enter) but doesn't appears in node properties inspector while writing text. Also one needs to create custom font for this, and assign it to every new Control. It is also not possible to use non-unicode text anywhere in the editor without recompiling.

**Comment by akien-mga** [comment]
Is it still valid in the current master branch?

**Comment by vnen** [comment]
@akien-mga It is valid as default font is not Unicode, though you can set a custom font for the editor.

**Comment by akien-mga** [comment]
It's more a feature request then I guess.

**Comment by akien-mga** [comment]
Fixed in 3e8eb39 \o/
