### ISSUE TITLE
Texscreen does not match screen if game window is resized at runtime.

### ISSUE THREAD

**Issue by SaracenOne** [godotengine/godot#5310]
**Operating system or device - Godot version:**
Windows 8 - Bleeding Edge Version (57c67fb0)

**Issue description** (what happened, and what was expected):
Shaders using 'texscreen' property get messed up if the game window is resized during runtime. The texscreen sample seems to get dealigned with everything. Starting a game up with any resolution does not seem to cause similar problems, only resizing at runtime.

**Steps to reproduce:**
Can be see easily in the texscreen demo by resizing the game window while the game is running. Other undiscernable visual glitches also seem to be present here.

**Link to minimal example project** (optional but very welcome):
Visible in texscreen demo (https://github.com/godotengine/godot-demo-projects)

**Comment by reduz** [comment]
there are many bugs with this, and the way Godot does texscreen copying seems to break on many platforms, will wait for 3.0 to rewrite it in a different way

**Comment by reduz** [comment]
this is fixed in 3.0 already
