### ISSUE TITLE
Exported project is not runnable when exported via commandline

### ISSUE THREAD

**Issue by nightrobin** [godotengine/godot#53110]
### Godot version

3.3.3-stable

### System information

Ubuntu 20.04 - 64 Bit

### Issue description

I tried running this in terminal:
Godot --export "Linux/X11" <MyProjectPath>/project.godot <BuildPath>/main

It generated two files. 
- main
- main.pck

However, when I tried running it using:
./main
It gave me this error: `bash: ./main: cannot execute binary file: Exec format error`

On the other hand, if I export my project through the user interface of Godot.
It generated two files:
- main.x86_64
- main.pck
But I can smoothly run this ./main with no problems.

My export_presets.cfg have:
```
[preset.0]

name="Linux/X11"
platform="Linux/X11"
runnable=true
custom_features=""
export_filter="all_resources"
include_filter=""
exclude_filter=""
export_path=""
script_export_mode=1
script_encryption_key=""

[preset.0.options]

custom_template/debug=""
custom_template/release="<PathTo3.3.3ExportTemplates.tpz>"
binary_format/64_bits=true
binary_format/embed_pck=false
texture_format/bptc=false
texture_format/s3tc=true
texture_format/etc=false
texture_format/etc2=false
texture_format/no_bptc_fallbacks=true
```
It seems that the output of these two methods are not the same.
_For the 1st method output, I tried using it with the Godot Server executable it run without problems._

How can I export using the **terminal** for Desktop Version though and not its output for the server use only?

### Steps to reproduce

Run this in terminal:
Godot --export "Linux/X11" <MyProjectPath>/project.godot <BuildPath>/main

Another method is to export the project through the user interface of Godot.

Compare the outputted files.

**Comment by Calinou** [comment]
> custom_template/release="<PathTo3.3.3ExportTemplates.tpz>"

The custom template path should be a path to a Linux binary, not a TPZ file. A TPZ file is a renamed ZIP archive that is meant to be used as a quick way to install export templates.

**Comment by nightrobin** [comment]
It works!
Thanks Calinou.
