### ISSUE TITLE
[Godot4] maybe should treat null as any variant type

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#53115]
### Godot version

4.0.dev.20210924.official

### System information

window10

### Issue description

I try implement my MyVector class,

### Steps to reproduce

If I code like this, all work well.
![1](https://user-images.githubusercontent.com/35988767/134863496-02895ad2-9b46-4606-8dfc-73544c2b677a.PNG)

But if I want set default parameter and set data=null,
I don't know how to code it because syntax error:
![2](https://user-images.githubusercontent.com/35988767/134863581-8ecd3e36-4462-421d-bb4a-75ff2efb1008.PNG)
![3](https://user-images.githubusercontent.com/35988767/134864052-66332fe7-3863-420c-9caa-0997dc9d02af.PNG)
![4](https://user-images.githubusercontent.com/35988767/134864074-a0ee913c-a37b-422a-b1e0-fc3c880fde1f.PNG)

Maybe I can not asign the function 'set_data' parameter 'value' type,
but I think it's not a good idea and also have a syntax
![5](https://user-images.githubusercontent.com/35988767/134864111-dfd905b2-3b93-46e1-b8bf-11305c3a6c6b.PNG)

### Minimal reproduction project
[NullParamTest.zip](https://github.com/godotengine/godot/files/7234250/NullParamTest.zip)

_No response_

**Comment by CsloudX** [comment]
Oh, I found can code like this:
```
func _init(size:=0,data=null):
	_init2(size,data)

func _init2(size:int, data):
	m_data.resize(size)
	match(typeof(data)):
		TYPE_INT,TYPE_FLOAT:
			for i in size:
				set_data(i,data)
		TYPE_ARRAY:
			assert(size<=data.size())
			for i in size:
				set_data(i,data[i])
```

**Comment by KoBeWi** [comment]
There is a proposal about it: https://github.com/godotengine/godot-proposals/issues/162

**Comment by CsloudX** [comment]
```
func test(val:= null) # null type
func test(val = null) #any type
```

**Comment by cdemirer** [comment]
This looks like a valid issue, similar to #56217, and can reproduce on current master. The conversion to float is supposed to be attempted at runtime, so this should compile without error.

**Comment by KoBeWi** [comment]
Yeah, after looking at it again, this is a bug.
