### ISSUE TITLE
`join` function is missing from PoolStringArray in GDNative headers

### ISSUE THREAD

**Issue by API-Beast** [godotengine/godot#53116]
In GDScript there is a "join" function to take a PoolStringArray and a delimiter and turn it into a String.

https://docs.godotengine.org/en/3.1/classes/class_poolstringarray.html#class-poolstringarray-method-join

This function is missing in the headers.

**Comment by akien-mga** [comment]
I transferred the issue to the Godot repo.

`PoolVector`'s `join` is defined here in the `3.x` branch for the core API: https://github.com/godotengine/godot/blob/3.x/core/pool_vector.h#L434-L443

But indeed it's not implemented in the GDNative headers (`modules/gdnative/include/gdnative/pool_arrays.h`).

I'm not familiar enough with the new GDExtensions yet to say if this affects `master` too.

**Comment by kdiduk** [comment]
I can make a fix for `3.x` and a back-port for `3.4`

**Comment by Calinou** [comment]
> I can make a fix for `3.x` and a back-port for `3.4`

Feel free to open a pull request for this :slightly_smiling_face:

**Comment by akien-mga** [comment]
Fixed by #55826.
