### ISSUE TITLE
Cannot preserve position and scale of ParallaxLayer

### ISSUE THREAD

**Issue by floppyhammer** [godotengine/godot#53123]
### Godot version

v3.4.beta5.official [dd0ee4872]

### System information

Windows 11, GLES3

### Issue description

![parallax](https://user-images.githubusercontent.com/28705694/134903525-99224b5b-fcd0-4372-a3f0-66cd4d035c8b.gif)

### Steps to reproduce

Use the reproduction project, and repeat the above process.

### Minimal reproduction project

[ParallaxLayerTest.zip](https://github.com/godotengine/godot/files/7235997/ParallaxLayerTest.zip)

**Comment by timothyqiu** [comment]
It's the nature of `ParallaxLayer` that its transform will be adjusted by `ParallaxBackground` and its own `motion_*` properties.

I think you can instead add another layer of `Node2D` and change the overall transform there.
