### ISSUE TITLE
[Bullet] body_test_motion causes crash when used with a Rigidbody in Kinematic mode and Bullet

### ISSUE THREAD

**Issue by BimDav** [godotengine/godot#53125]
### Godot version

3.3.stable

### System information

Windows 10

### Issue description

The issue is the same as in https://github.com/godotengine/godot/issues/51847, which was fixed in https://github.com/godotengine/godot/pull/50103, but for a RigidBody in Kinematic mode. This case is not fixed by https://github.com/godotengine/godot/pull/50103.

The same crash happens when calling kinematic methods of KinematicBody, when this body's mode has been changed to Rigid and back to Kinematic using the PhysicsServer.

### Steps to reproduce

Run the attached project

### Minimal reproduction project

[PhysicsBody_to_kinematic.zip](https://github.com/godotengine/godot/files/7236070/PhysicsBody_to_kinematic.zip)

**Comment by akien-mga** [comment]
Fixed by #53118.
