### ISSUE TITLE
"Move to..." dialog for files has white folders

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#53132]
### Godot version

3.x 29b1d39 (and probably 4.0)

### System information

W10

### Issue description

![image](https://user-images.githubusercontent.com/2223172/134939795-bfeb0a37-9a83-4e62-83c2-4ac3231e0326.png)
It's not tinted.

### Steps to reproduce

1. Right click file in the file dock
2. Select "Move to..." option

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot/blob/281d0bd59e1b8a8ee2032df97f28051d5668b5da/editor/filesystem_dock.cpp#L752

**Comment by pycbouh** [comment]
And here's the place where this should be used:

https://github.com/godotengine/godot/blob/master/editor/editor_dir_dialog.cpp#L46
