### ISSUE TITLE
Weird launching Godot from Steam error [Invalid mapping entry: dpright]

### ISSUE THREAD

**Issue by Multirous** [godotengine/godot#53139]
### Godot version

3.3.3.stable

### System information

Windows 10

### Issue description

![image](https://user-images.githubusercontent.com/77918086/134949137-3371add8-41b0-453e-b0c0-1a631d2de7ef.png)

The error shows up when I just launch Godot using Steam.
Launching Godot from the folder doesn't cause the error.
Reinstall doesn't help either.

### Steps to reproduce

I launch my Godot from the steam launcher.

### Minimal reproduction project

I have no idea what to put in, so I was going to put my whole Godot file without my projects in here, but Github doesn't allow me so. ¯\_(ツ)_/¯

**Comment by Calinou** [comment]
Do you have a controller connected to the PC when Godot is launched? If so, which controller model is it?

**Comment by Multirous** [comment]
> Do you have a controller connected to the PC when Godot is launched? If so, which controller model is it, and is it using a wired or wireless connection?
Nope, I doesn't have any controller connect to my pc.

**Comment by akien-mga** [comment]
This might happen if your Steam config includes an invalid custom gamepad mapping, which is then passed to all games (including Godot) with the `SDL_GAMECONTROLLERCONFIG` environment variable. (Godot doesn't use SDL but uses its gamepad mapping format, including this config environment variable.)

For example here on Linux it passes:
```
SDL_GAMECONTROLLERCONFIG=03000000de280000ff11000001000000,Steam Virtual Gamepad,a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,
```

(I could find out by editing the run command to `env && %command%` on Linux and running Steam in a terminal to see the console output, I'm not sure what could be the equivalent on Windows.)

Wrong mappings might be saved in your Steam config file, see https://www.reddit.com/r/SteamController/comments/8qyhs5/want_to_reset_steams_controller_settings_heres_how/ for instructions on how to find it and see if there's anything fishy (especially a mapping with `dpright:,` and no `h0.2` or similar following it) on the `SDL_GamepadBind` line.

**Comment by Multirous** [comment]
Hmm, I followed the instruction but I seem to can't find `SDL_GamepadBind` store in Steam's config folder.

**Comment by Multirous** [comment]
That's right! There's nothing in this variable 
![image](https://user-images.githubusercontent.com/77918086/135045758-38e14bfe-86c1-4caf-836b-d1863fbdb48d.png)

**Comment by Multirous** [comment]
Thanks! This does fix the problem.
