### ISSUE TITLE
Feature request - add locking functionality to an object's child nodes from the UI.

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#5313]
Linux x64 (Ubuntu 16.04) - Godot built from Git.

Change the "Makes sure the object's children are not selectable" to "Lock the selected object in place and its children" - OR add functionality to the existing lock button to also allow locking any child nodes in place (and/or add "are not selectable" to the parent node as well).

**Comment by vnen** [comment]
You can use both together: Lock the node so it can't be moved and make its children unselectable, so you can't move neither the node nor its children.

**Comment by akien-mga** [comment]
Based on @vnen's comment, I guess that no change is needed, since the feature is already implemented.
