### ISSUE TITLE
Graphical glitches on windows with Intel Iris Xe graphics (3D render to texture, GLES3, batching disabled)

### ISSUE THREAD

**Issue by jamie-pate** [godotengine/godot#53147]
### Godot version

v3.3.2.stable.official, v3.3.3.stable.official
Happens with both Release (export) and tools builds.

### System information

Windows 10, GLES3, Intel(R) Iris(R) Xe Graphics, i7-1165G7

### Issue description

The screen is cleared occasionally and a solid color is shown instead. 
https://streamable.com/fqt18v

GLES3
i7-1165G7
Intel(R) Iris(R) Xe Graphics (uhd series and other vendors are not affected)
DriverVersion: "27.20.100.9749", "30.0.100.9864"
1920 x 1080 x 4294967296 colors
os_ver: "10.0.19042 N/A Build 19042",

### Steps to reproduce

Seems like you need Viewports and gridmaps to reproduce....

### Minimal reproduction project

see https://github.com/godotengine/godot/issues/53147#issuecomment-929771161

**Comment by Calinou** [comment]
Can you reproduce this after disabling batching in the project settings?

**Comment by jamie-pate** [comment]
Random guesses as to what's going wrong in the driver:
The frustrum randomly gets set to 1.0x1.0 at the far plane?
Sampling the intermediate viewport render target incorrectly?

**Comment by lawnjelly** [comment]
What are those moving lines around 1 - 2 second mark? Are you drawing something skinned? Could be a NaN or something creeping in with some dodgy data for an animation.

**Comment by jamie-pate** [comment]
The lines are links of the lanyard 'rope' that is only visible when you scan the key card in the door. I don't think it's related because that tree gets hidden after a few seconds and the glitch persists.. it seems to be related to where the camera is pointed as it stays on the screen when the player stops moving the mouse..

Luckily I have a line on a new laptop with the same hardware today so I will hopefully be able to reproduce and report an issue with the vendor

**Comment by jamie-pate** [comment]
Seems to be related to render target double buffering? Here are some more artifacts:

https://streamable.com/baqjya
https://streamable.com/wxxevs

**Comment by Calinou** [comment]
> Seems to be related to render target double buffering? Here are some more artifacts:

Can you reproduce it if you disable V-Sync in the project *and* make sure the graphics driver doesn't force V-Sync on its end?

**Comment by jamie-pate** [comment]
interesting correlation with frame time ...this is with vsync off (unable to use gamebar to record when the editor is running?)

https://streamable.com/64gdn6

**Comment by jamie-pate** [comment]
hall of mirrors with the clear color in the editor
![image](https://user-images.githubusercontent.com/682658/135163961-5e7edec5-a3e4-42cd-95fe-6ad00499c4e8.png)

**Comment by jamie-pate** [comment]
Some of the problem seems to be linked to gpu particles,... when I turn 'emitting true' it stops flickering?

**Comment by jamie-pate** [comment]
[iris_xe_flicker_repro.zip](https://github.com/godotengine/godot/files/7248423/iris_xe_flicker_repro.zip)

Finally got a cut down repro... for some reason it needs to include a gridmap...

**Comment by jamie-pate** [comment]
https://streamable.com/0z49dg this is the reproduction in a uhd 630... Seems like it may be affected but not as badly? Only one viewport is flickering...

**Comment by akien-mga** [comment]
> [streamable.com/0z49dg](https://streamable.com/0z49dg) this is the reproduction in a uhd 630... Seems like it may be affected but not as badly? Only one viewport is flickering...

I don't seem to reproduce the issue on Linux with Intel HD 630 and Mesa 21.2.2 - but that's not surprising. I'll see if I can reproduce it on Windows 10 whenever I find time to reboot :)

**Comment by jamie-pate** [comment]
[iris_xe_flicker_repro2.zip](https://github.com/godotengine/godot/files/7255375/iris_xe_flicker_repro2.zip)
https://streamable.com/ls6ifz
Another, more focused repro. I got rid of the player and phone and focused on the 3 elements that are apparentlyrequired to cause this:

1. mesh with material that has a viewport texture
2. viewport texture must have no opaque pixels
3. Gridmap tile with transparent+refraction material
4. many viewports? The issue is reproduced most frequently when the viewport spinbox is set around 15

**Comment by jamie-pate** [comment]
seems fixed in driver 31.0.101.3959!
