### ISSUE TITLE
Mono does not release any objects of the type event.

### ISSUE THREAD

**Issue by sboron** [godotengine/godot#53156]
### Godot version

4.0.dev

### System information

Windows 10, Windows 11

### Issue description

Each input event increse the holded objects inside the engine. The events will be holded permanent and not destroyed .
When i try to free the Event with .free(), it reduce the hold objects by the engine (however, not all will be destroyed).

Same issue with _UnhandledInput and _UnhandledKeyInput

### Steps to reproduce

`
public override void _Input(InputEvent @event)
{
}`

Just moving the mouse and u will get this
![image](https://user-images.githubusercontent.com/76991284/135005976-07b93743-e611-4eee-b363-f534cc9146f4.png)

**Comment by sboron** [comment]
`  public override void _Input(InputEvent @event)
    {
        @event.Free();
    }`
    
Fun fact when i try to free manualy, the object will be just destroyed in the case that im inside the window (focused).

**Comment by akien-mga** [comment]
Duplicate of #41543, Mono is garbage collected so the memory release will happen whenever it decides it's needed.

**Comment by sboron** [comment]
Btw disposing and freeing are not working.

**Comment by sboron** [comment]
Okai. Was figured out. Two issues at the same time. First one (event disposing) can be fixed with .Disposed(). Second memory leak i will open a new ticket.
