### ISSUE TITLE
rad2deg() gives wrong outputs

### ISSUE THREAD

**Issue by ajk2196** [godotengine/godot#53158]
### Godot version

3.3.3 stable

### System information

Windows 10, 2 X RTX 2070 Super

### Issue description

I have been using **deg2rad()** and **rad2deg()** quite often nowadays in one of my projects. Upon using rad2deg() with any amount of radians, I always get a wrong output, like when I see the value of **rad2deg(25) in Godot** and the same in **Google's online calculator**, the values are both different and upon checking it, I found that **Godot is the one that is giving wrong outputs**.

I am aware that game engines work differently, (like the Z axis is inverted in 3D, Y axis is inverted in 2D), and maybe that this miscalculation of rad2deg() could be a part of some tweak, but however, for some reasons, I want to receive the exact value from rad2deg(), not the 'tweaked' ones. Help me out please, for the project's deadline is not near, but the project is too big that each and every hour counts.

Thank you for your time; thank you for the effort.

### Steps to reproduce

-Create a new godot file and add a 2D node to the scene.
-add script to it and in the _ready() function, add the following code: **print(cos(rad2deg(45)))**
-play the scene and get the value in the console and compare it online.

**Comment by Seubmarine** [comment]
Godot consider rad2deg(45) as 2578.310078
and cosine consider 2578.310078 not as an angle but as a radian witch is -0.59181274
if it was considering it as a degree it would equal to 0.52532199

I don't know if it's normal or not, but cosine function interpret any number as if it were radian

**Comment by timothyqiu** [comment]
`cos()` takes an angle in radian, so you don't need to wrap the value in `rad2deg()`.

**Comment by mrjustaguy** [comment]
Yeah to me this seems like just user misuse and not a bug, unless you can provide a specific example of I/O that gives a wrong output

**Comment by aaronfranke** [comment]
@ajk2196 `rad2deg(25)` converts 25 radians into degrees. You meant to convert 25 degrees into radians (via `deg2rad(25)`).

@Seubmarine `rad2deg(45)` converts 45 radians into degrees. You meant to convert 45 degrees into radians (via `deg2rad(45)`).

**Comment by ajk2196** [comment]
Okay, thank you @Calinou , @timothyqiu , @aaronfranke , @jmb462 and @Seubmarine . Now it is clear to me. I was using it wrong. [NOTED]: To switch trigonometric values between degrees and radians, we are just supposed to use cos() and cos(deg2rad()).
