### ISSUE TITLE
Consecutive tables in RichTextLabel do not align correctly.

### ISSUE THREAD

**Issue by EricEzaM** [godotengine/godot#53155]
### Godot version

v4.0.dev.custom_build [8abd46096]

### System information

Win 10

### Issue description

Consecutive tables do not align correctly. This affects the warnings panel in the editor.

These warnings should be vertically stacked:
![image](https://user-images.githubusercontent.com/41730826/135000444-0ed8fee5-95fc-446d-8b9b-394c2101cef0.png)

![image](https://user-images.githubusercontent.com/41730826/135000560-0b57df28-7d97-4415-8e45-a0ab382c2e51.png)

### Steps to reproduce

To reproduce in the editor:
* Create a new scene.
* Use the Node tab to add a connection to a signal.
* Delete the method from the script file. This will create a warning `"Missing connected method..."`
* Add an unused variable to the script. This will generate a GD script warning. The connection warnings and GD script warnings use separate `RichTextLabel` tables in `ScriptTextEditor` (see line ~450)

To reproduce in script:
* See Minimal repro project below. This recreates the C++ code from ScriptTextEditor

<details>
<summary>Expand to see GD Script code</summary>

```gdscript
extends Control

# Called when the node enters the scene tree for the first time.
func _ready():
	var rtl: RichTextLabel = $RichTextLabel
	
	rtl.push_table(1)
	rtl.push_cell()
	rtl.add_text("Hello from table 1!")
	rtl.pop() # Cell
	rtl.pop() # Table
	
	# Create 2nd table immediately after first
	rtl.push_table(3)
	for i in range(2):
		rtl.push_cell()
		rtl.add_text("Row %s: Col 1" % i)
		rtl.pop()
		
		rtl.push_cell()
		rtl.add_text("Row %s: Col 2" % i)
		rtl.pop()
		
		rtl.push_cell()
		rtl.add_text("Row %s: Col 3" % i)
		rtl.pop()
	rtl.pop() # Table
	
	var thing = 12
	var thing2 = 13

```

</details>

### Minimal reproduction project

[RichTextLabel_TableAlignment.zip](https://github.com/godotengine/godot/files/7239993/RichTextLabel_TableAlignment.zip)

cc @bruvzg

**Comment by bruvzg** [comment]
The ability to inline tables is an intentionally added feature. I guess the warnings panel should be modified to push a new line tag after each table.
