### ISSUE TITLE
Loading GDExtensions fails on first run when `.godot/extension_list.cfg` is not generated yet

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#53163]
### Godot version

4.0.dev (4735a0359)

### System information

Linux, Mageia 9 x86_64

### Issue description

When running a project using a GDExtension while the `.godot/extension_list.cfg` file doesn't exist yet, or hasn't been updated for a new extension, the editor will throw errors, such as:
```
SCRIPT ERROR: Parse Error: "Example" was not found in the current scope.
          at: GDScript::reload (res://main.gd:9)
ERROR: Method/function failed. Returning: ERR_PARSE_ERROR
   at: reload (modules/gdscript/gdscript.cpp:855)
ERROR: Condition "p_level <= int32_t(level_initialized)" is true.
   at: initialize_library (core/extension/native_extension.cpp:299)
SCRIPT ERROR: Parse Error: "Example" was not found in the current scope.
          at: GDScript::reload (res://main.gd:9)
ERROR: Method/function failed. Returning: ERR_PARSE_ERROR
   at: reload (modules/gdscript/gdscript.cpp:855)
ERROR: Cannot get class 'Example'.
   at: is_class_enabled (core/object/class_db.cpp:1538)
WARNING: Node Example of type Example cannot be created. A placeholder will be created instead.
     at: instantiate (scene/resources/packed_scene.cpp:164)
ERROR: In Object of type 'Node': Attempt to connect nonexistent signal 'custom_signal' to callable 'Node(main.gd)::_on_Example_custom_signal'.
   at: connect (core/object/object.cpp:1328)
```

Then the `.godot/extension_list.cfg` is properly generated and used successfully on subsequent edits, but this first use bug is annoying.

### Steps to reproduce

- Build [godot-cpp](https://github.com/godotengine/godot-cpp) example following instructions in https://godotengine.org/article/introducing-gd-extensions
- Run it (delete `.godot` or `.godot/extension_list.cfg` if it exists to reproduce the bug)

### Minimal reproduction project

https://github.com/godotengine/godot-cpp/tree/master/test/demo

**Comment by mhilbrunner** [comment]
Note: `mkdir .godot` and copying the `extension_list.cfg` in there before the first open seems to work as a workaround without any adverse effects, which is useful to get this to build on CI.

Still an annoying issue. :)

**Comment by mhilbrunner** [comment]
Edit, by BastiaanOlij on RC:
> At startup godot only loads what is added to the gdextension config file in your .import folder and the first time your library isn’t there.
> Than later on the editor will scan for new extensions and add them, it does this everytime godot gets focus i think. At this time loading of the extension fails because there is a failsafe to ensure class types are loaded in order, and the order is set to the last type when extensions were originally processed.
> Not sure what to do about it though

**Comment by BastiaanOlij** [comment]
Ah yes, the folder is now called `.godot` and the file I was thinking about is `extension_list.cfg`. I was typing that on my phone so was remembering the old names :)

I see two potential options here:
1) perform the initial scan for new extensions right after we load the `extension_list.cfg` when using the editor build, so something like:
```
load_extension_list()
#ifdef TOOLS_ENABLED
    scan_extensions()
#endif
```
2) remove the failsafe so libraries don't fail when loaded after the editor is already loaded, I really don't get its purpose to be honest and it will allow you to copy extension into your new project and have them load right away.

**Comment by YuriSizov** [comment]
Is this still an issue? @Akien @BastiaanOlij @dsnopek

**Comment by dsnopek** [comment]
I've never personally encountered this issue.

I just tried to reproduce it by deleting the `.godot/extension_list.cfg` file in a project that uses a GDExtension, and then opening it in the editor. Everything appeared to load up fine, including the default scene which used nodes from the GDExtension. Looking on the console I didn't see any unexpected errors.

So, unless I'm missing a reproduction step, I think it's not an issue anymore?

**Comment by d6e** [comment]
This is still an issue for Godot 4.2 when running with `--headless` with this [fmod extension.](https://github.com/utopia-rise/fmod-gdextension). I use `--headless` when running Godot in our CI environment and with all of the `.godot` directory ignored. There's no way to accept the restart prompt from headless. 

My repro steps are:
1. Add fmod extension and fmod libraries
2. git clean -fdx (clears away .godot, assuming you have it gitignored)
3. Launch the game (if headless, it crashes), if not headless it prompts for a restart.

Adding the `.godot/extension_list.cfg` manually works around this issue, but you have to know about the workaround which took me hours to figure out (I had to actually find out that it was the non-existent `extension_list.cfg` file at fault before I could find this issue).

I propose either some sort of `--accept-all` option for headless or just implicitly accepting yes and writing the extension list when run in `--headless` mode.
