### ISSUE TITLE
CharacterBody3D / Garbage Collector Memory Leak 

### ISSUE THREAD

**Issue by sboron** [godotengine/godot#53172]
### Godot version

4.0.dev (mono)

### System information

Windows10

### Issue description

Memory Leak for CharacterBody3D. Colliding not releasing objects.

![image](https://user-images.githubusercontent.com/76991284/135080577-abf3b181-855a-4200-a595-0c059d56284b.png)

### Steps to reproduce

- Use mono
- Create a CharacterBody3D
- Set GlobalTransform to any Position
- Wait for colliding -> Let him fall down, watch the holded objects on the engine. -> Tada Memory leak

**Comment by sboron** [comment]
Related mby with https://github.com/godotengine/godot/issues/50300

**Comment by sboron** [comment]
Important notice: Just happend on mono. GDScript works well. Looks like a Garbage Collector Issue. Related mby to my previous post.

**Comment by sboron** [comment]
Okai interestening in mono i have to Dispose the MoveAndCollide Object to free the memory (thats new).. So its a bug,but can be fixed like this

` public override void _PhysicsProcess(float delta)
    {
        var test = MoveAndSlide();
        if(test != null)
        test.Dispose();
    }`

**Comment by sboron** [comment]
So im pretty sure the garbage collector is not working in a right way.

**Comment by sboron** [comment]
`  public override void _PhysicsProcess(float delta)
    {
       MoveAndSlide();
     
    }`
    produce a memory leak. Because cant be dispose

**Comment by sboron** [comment]
Deep dive:

KinematicCollision3D will not be destroyed.
MoveAndSlide -> no KinematicCollision3D return -> memory leak
MoveAndCollide -> KinematicCollision3D return -> can be Disposed

So in the end is the same with https://github.com/godotengine/godot/issues/53156.
Objects will not be disposed automaticly. Means garbage collector working in a wrong way.

When i manualy dispose objects it works fine.

**Comment by sboron** [comment]
my idea is to rewrite move_and_slide. instead of boolean, the last element MotionResult (motion_results [motion_results.length]) should be returned here. That can of course also be zero. This means that you have the option of disposing of the element yourself. I could quickly create a PR with two lines of code and documentation changes, if desired.

**Comment by sboron** [comment]
Simple fix
` MoveAndSlide();
if (GetSlideCollisionCount() > 0)
{
                var obj = GetSlideCollision(0);
                if (obj != null)
                    obj.Dispose();
}`

Needs to be describe in the documentation.

**Comment by akien-mga** [comment]
You shouldn't have to dispose this manually. Mono is garbage collected, and this should be handled by the GC. If it's not working, that's a bug, not something that should be worked around manually by all users.

**Comment by neikeq** [comment]
> `public override void _PhysicsProcess(float delta){ MoveAndSlide(); }` produce a memory leak. Because cant be dispose

Is this all that's needed to reproduce the issue?

**Comment by neikeq** [comment]
I have not tested yet, so I can't tell if there's a leak or not. However, the garbage collector doesn't necessarily collect resources right away. There were similar issues to this in the past, and the conclusion was that the GC simply didn't collect them yet.

One way to check if this is the case is to try to force collection this way somewhere like in `_Process`:

``` C#
GC.Collect(GC.MaxGeneration);
GC.WaitForPendingFinalizers();
```

If doing that doesn't fix the issue, then there may be a leak.

Keep in mind, I only recommend that doing that for debugging purposes. In practice, if you want an object to be disposed right away instead of leaving it to the GC, then you have to call `Dispose()` as there's no RAII in C#.

**Comment by pouleyKetchoupp** [comment]
I wonder if it's a side effect of this change: https://github.com/godotengine/godot/pull/52954

I'm not re-using the cache if there's still a reference, but maybe there's an extra reference in mono that causes this logic to create a new object every time?

**Comment by sboron** [comment]
Today i will dive a bit deeper. But the issue is not a physics issue. Its 100% a mono issue. The problem occurs on many different points. See also my previous issue ticket one day ago (same problem, different context). For some reasons the garbage collector does not wach over each holded object. So seems like to be a bigger issue. i blv the easiest way to detect the issue is to build a previous commit (mby 14days ago, i see there way some several mono changes), and resimulate the problem. But im defently sure before my big baby timeout (yeah im father), 3 months ago it was working well. Also when i was writing the terrain tool the garbage collector was working.

**Comment by sboron** [comment]
> I have not tested yet, so I can't tell if there's a leak or not. However, the garbage collector doesn't necessarily collect resources right away. There were similar issues to this in the past, and the conclusion was that the GC simply didn't collect them yet.
> 
> One way to check if this is the case is to try to force collection this way somewhere like in `_Process`:
> 
> ``` C#
> GC.Collect(GC.MaxGeneration);
> GC.WaitForPendingFinalizers();
> ```
> 
> If doing that doesn't fix the issue, then there may be a leak.
> 
> Keep in mind, I only recommend that doing that for debugging purposes. In practice, if you want an object to be disposed right away instead of leaving it to the GC, then you have to call `Dispose()` as there's no RAII in C#.

Thanks for the tipp. I will reproduce it later and try to manualy trigger the GC.

**Comment by sboron** [comment]
> I have not tested yet, so I can't tell if there's a leak or not. However, the garbage collector doesn't necessarily collect resources right away. There were similar issues to this in the past, and the conclusion was that the GC simply didn't collect them yet.
> 
> One way to check if this is the case is to try to force collection this way somewhere like in `_Process`:
> 
> ```cs
> GC.Collect(GC.MaxGeneration);
> GC.WaitForPendingFinalizers();
> ```
> 
> If doing that doesn't fix the issue, then there may be a leak.
> 
> Keep in mind, I only recommend that doing that for debugging purposes. In practice, if you want an object to be disposed right away instead of leaving it to the GC, then you have to call `Dispose()` as there's no RAII in C#.

To trigger the gc manualy like u described above, solves the leak. 

So yeah we have an memory leak inside the garbage collector.

**Comment by sboron** [comment]
> ### Godot version
> 
> 4.0.dev (mono)
> 
> ### System information
> 
> Windows10
> 
> ### Issue description
> 
> Memory Leak for CharacterBody3D. Colliding not releasing objects.
> 
> ![image](https://user-images.githubusercontent.com/76991284/135080577-abf3b181-855a-4200-a595-0c059d56284b.png)
> 
> 
> ### Steps to reproduce
> 
> - Use mono
> - Create a CharacterBody3D
> - Set GlobalTransform to any Position
> - Wait for colliding -> Let him fall down, watch the holded objects on the engine. -> Tada Memory leak
> 
> ### Minimal reproduction project
> 
> _No response_

I think this issue is fixed. You can close it
