### ISSUE TITLE
Hover highlight effect is not updated correctly when hovering differents menubuttons (DisplayServer regression)

### ISSUE THREAD

**Issue by jmb462** [godotengine/godot#53188]
### Godot version

Master branch (84b11fbaa674b6e2341de534e93a981378a307ad)

### System information

Windows 10

### Issue description

When using the main editor menu, the hover effect is still shown when we change to another menu.

![menu](https://user-images.githubusercontent.com/3649998/135132614-f1cf869f-2f64-4583-a612-bd8479b2a72c.gif)

![image](https://user-images.githubusercontent.com/3649998/135133715-3bc1602d-a171-4a9f-a224-4cf77b49bb8e.png)
Here, mouse is over Debug menu and Project Menu is still highlighted.

### Steps to reproduce

Put the mouse over a menuButton of the main menu : it become highlighted (gray background)
Click to to open this menu : The font become blue
Put the mouse over the next menuButton : the new menu font become blue but the first menu get its grey highlight back. It shouldn't be highlighted anymore.

### Minimal reproduction project

Not needed

**Comment by KoBeWi** [comment]
No longer reproducible in [3fab862](https://github.com/godotengine/godot/commit/3fab862c590b706aa5c6211415d3854140dbc5d3)
