### ISSUE TITLE
DirectionalLight Shadow Contact not working on Android device

### ISSUE THREAD

**Issue by GGGomer** [godotengine/godot#53193]
### Godot version

v3.3.3.stable.official [b973f997f]

### System information

Windows 10, GLES3, Android 11, Samsung A52 5G

### Issue description

The "Contact" setting on DirectionalLight's Shadow is not functioning on Android devices.

Here's an image from the debug viewport on Windows
![image](https://user-images.githubusercontent.com/73346372/135142560-22d92bcb-6d6a-45db-8dc6-82c207f303c5.png)

And here's an image of the same scene, same build on an android device.
![image](https://user-images.githubusercontent.com/73346372/135142479-9ba33f66-f144-4886-a98d-93607254fecc.png)

### Steps to reproduce

Create a scene with a staticbody floor + collisionshape + mesh.
create a rigidbody + collisionshape + mesh.
Set a directionallight somewhere in the scene.
set camera to see shadow of rigidbody
Drop rigidbody on staticbody from an arbitrary height. 

### Minimal reproduction project

[Winkel.zip](https://github.com/godotengine/godot/files/7246487/Winkel.zip)

**Comment by Calinou** [comment]
[Contact shadows are known to be broken on many devices](https://github.com/godotengine/godot/pull/35316)
 and will be removed in 4.0 as a result. Either way, they're slow to render and are not suited for mobile devices for performance reasons.
