### ISSUE TITLE
[Vulkan] flood of errors brings Godot to its knees

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot#53206]
### Godot version

v4.0.dev.calinou [de917008f]

### System information

Linux Manjaro, Vulkan, Intel Kaby Lake

### Issue description

Flood of errors, in the thousands, something about uniforms and set...?
If you have the material preview and the scene open, the number of the errors double, which froze Godot for 5-ish minutes yesterday.
Errors stop if you click Script tab (i.e. stop rendering the scene)

NB. Selecting File->Reload Saved Scene fixes the issue (the mesh displays correctly and the errors are gone)

First, I expected identical errors to be collapsed in 4.0, and secondly, having 10 000-ish errors or 30 000 errors before the flood stops is just...

### Steps to reproduce

Open the repro project, open the building scene. 

### Minimal reproduction project

[shader problems.zip](https://github.com/godotengine/godot/files/7249823/shader.problems.zip)

**Comment by Chaosus** [comment]
Hm, I see no errors at (Windows 10 / GTX 1060 / v4.0.dev.custom_build [f410852f9])

![image](https://user-images.githubusercontent.com/3036176/135235133-a2f5ca0d-ba37-4d52-bfcd-62d06e763ca5.png)

**Comment by Zireael07** [comment]
Try creating new project with the same files? Since reload current scene fixes it, I strongly suspect this is some sort of a caching problem and might only be apparent only on first open/first load.

**Comment by Chaosus** [comment]
Yeah, it will emit flood of errors:

![image](https://user-images.githubusercontent.com/3036176/135241304-fd6ea5b0-6587-4123-a7db-f4fb6f6ad3b4.png)

**Comment by Zireael07** [comment]
Note: this is not limited to this one mesh+shader, I've had similar problems with other meshes and shaders, but this one was most egregious

**Comment by Zireael07** [comment]
also I've seen it happen with a new shader I was hand-writing in editor, but it wasn't as painful because that shader had less uniforms - so it's not limited to files copied over from somewhere else. it also applies to newly created files
