### ISSUE TITLE
Animated Billboard Particles playing in incorrect order

### ISSUE THREAD

**Issue by metinc** [godotengine/godot#53209]
### Godot version

v3.3.3.stable.official [b973f997f]

### System information

Ubuntu 21.04

### Issue description

I tried to create an animated 3d sprite with this 3x2 frames sprite sheet texture:

![3x2](https://user-images.githubusercontent.com/1820121/135261106-508eaba7-005c-430e-89fa-34d85340c88d.png)

I expected to see an animation 1-2-3-4-5-6 but I actually see 1-2-3-1-5-6

https://user-images.githubusercontent.com/1820121/135260738-beb70182-4989-4428-a69f-f2212b2c9a7f.mp4

I tested jpg files instead of png with no difference. But sometimes the animation is correct. For example a 10x10 sprite sheet is working properly, however a 3x3 is not (see attached project).

### Steps to reproduce

Create a 3d particle emitter and add a particles material. Then give it an animated billboard material.

### Minimal reproduction project

Open the scene called _bug_.

[animated_particle_bug.zip](https://github.com/godotengine/godot/files/7251541/animated_particle_bug.zip)

**Comment by Calinou** [comment]
> I tried to create an animated 3d sprite with this 3x2 frames sprite sheet texture:

YOu can use AnimatedSprite3D instead of Particles3D for this purpose.
