### ISSUE TITLE
Code completion for nested dictionaries

### ISSUE THREAD

**Issue by supaiku0** [godotengine/godot#5322]
master at 36687684632bac50f1e6b0fc4b0adab6f09bf663

Hi,

I have a singleton containing many Constants like this:
`const SkillTypes = {
    "ACTIVE": "active",
    "PASSIVE": "passive"
}`

or even nested deeper
`const Flags = {
    "Nested": {
        "DEEP": "deep"
    }
}`

Accessing them works fine:
`print(Constants.Flags.Nested.DEEP) # => "deep"`

But the code completion fails miserably and doesn't suggest anything beyond the first property. I'm aware that I'm probably abusing dictionaries for something they aren't made for, but I'm porting a JS-codebase and this is how it's done there and I like it too.

The code completion for dictionaries should support a "value"-look up.

**Comment by Anutrix** [comment]
Won't there be significant loss in performance if it has search dictionary recursively for matches?

**Comment by bojidar-bg** [comment]
Hm, I just tested on master-ish, and I get proper autocompletion `Constants.Flags.Nested.<tab>`.
Unless I'm misunderstanding the issue, it is fixed?

**Comment by Anutrix** [comment]
![Capture49](https://user-images.githubusercontent.com/11459028/60737945-2493c000-9f7a-11e9-99d4-64e074b795cb.PNG)
Is this normal? If no match is found, a lot of things are listed?

**Comment by akien-mga** [comment]
Seems fixed as of 3.1 in my tests (well 3.1.2.devel, but it's likely fixed in 3.1.stable too).

>  Is this normal? If no match is found, a lot of things are listed?

Yes, it searches first for direct substring matches, and then for strings with the highest similarity (so they include the letters typed). For example if you typed "AnmtadTextre" it would still match AnimatedTexture.
