### ISSUE TITLE
Vulkan: Texture appears distorted on MeshInstance

### ISSUE THREAD

**Issue by metinc** [godotengine/godot#53236]
### Godot version

v4.0.dev.custom_build [a238dc8bb]

### System information

Ubuntu 21.04
GPU is AMD Renoir

### Issue description

The texture appears to be distorted. I expected it to fit. I could not find an open issue so I guess this does not happen on every machine. However the Godot icon renders fine.
![Screenshot from 2021-09-29 22-29-30](https://user-images.githubusercontent.com/1820121/135344399-ea0e3feb-078a-4a44-ad42-4497c321a663.png)

### Steps to reproduce

Create a mesh instance and add a material with my provided textur

### Minimal reproduction project

[stretched_textures_bug.zip](https://github.com/godotengine/godot/files/7254914/stretched_textures_bug.zip)

**Comment by Calinou** [comment]
Can you reproduce this if you reimport the texture with **Lossless** compression instead of **Video RAM**? You can do so by selecting the texture in the FileSystem dock, going to the Import dock, changing the compression mode, then clicking **Reimport**.

**Comment by floppyhammer** [comment]
Cannot preproduce if imported with Lossless. Might be a duplicate of #49981.

**Comment by metinc** [comment]
Just had a closer look. @floppyhammer is right, this is a duplicate of #49981. In my case the distortion is simply more prominent because I use a very low resolution texture while higher resolutions only reveal this distortion when zooming out and mipmaps get visible. After changing the Godot icon resolution from 64x64 to prime number 67x67 I got the same distortion.
![Screenshot from 2021-09-30 09-21-06](https://user-images.githubusercontent.com/1820121/135406800-a2a3bb14-c118-4b90-aa3d-be5612181f39.png)
