### ISSUE TITLE
Wrong glyphs rendered in Label with custom theme derived from editor theme

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#53253]
### Godot version

v4.0.dev.custom_build [5489f4384]

confirmed in v4.0.dev.custom_build [ac7505e27]

### System information

manjaro 21, AMD Radeon r7 200 series, Vulkan, 8GB Memory

### Issue description

After opening a project with a addon, the text was all messed:
![Peek 2021-09-30 07-55](https://user-images.githubusercontent.com/58845030/135443040-be331b5d-6f0d-4adb-ba27-5991b64e90c7.gif)

### Steps to reproduce

* Open Project
* Open Addon Scene

### Minimal reproduction project

this is an addon, so in order to install:
* Create a new project
* Create an addon folder
* inside use the command bellow
`git clone git@github.com:nonunknown/gdextension-integration.git`

**Comment by akien-mga** [comment]
How do you build Godot? Do you disable the `text_server_adv` module and use the fallback one instead? In which case this could be what #53221 fixed and you're just on an older (9 days old) commit.

**Comment by nonunknown** [comment]
can confirm in the most recent commit:

![image](https://user-images.githubusercontent.com/58845030/135465307-211d3c3a-354a-41f1-8a86-32c97b83401e.png)

**Comment by akien-mga** [comment]
I can reproduce the issue, here's a MRP with the above extension properly set up:
[Test Project.zip](https://github.com/godotengine/godot/files/7260063/Test.Project.zip)

No idea what causes it but it seems to be specific to what this extension does. The scene has a tool script which might mess with stuff, but I don't see any obvious issue. CC @bruvzg @Paulb23

**Comment by bruvzg** [comment]
Editor fonts are loaded from memory instead of files and `FontData` copy saved to the custom theme seems to be missing source `ttf` file data (only have cached glyphs which were rendered at the time of theme import, and without it Font can't convert char codes to glyph indices).

**Comment by nonunknown** [comment]
Yeah makes sense, I've imported the default editor theme and modified it!
