### ISSUE TITLE
Mesh (SurfaceTool) material with normal map not working. It just makes albedo darker.

### ISSUE THREAD

**Issue by twoco** [godotengine/godot#53269]
### Godot version

3.3.3

### System information

Windows 10, GLES3, RTX 2070 Super

### Issue description

I created a simple mesh with UV and normals with the SurfaceTool and set the mesh and a material with texture to a MeshInstance. 

The material has a albedo texture and a normal map. Works great on a cube create by Godot by just adding MeshInstance and set a cube mesh by point and click in the editor. 

But  when I create a cube (or plane. does not matter) on runtime, the normal maps is not working. It just makes albedo darker. I see that when I toggle the normal map in the editor while running the game.

### Steps to reproduce

Create a mesh with the SurfaceTool and set it to a MeshInstance.

Create a SpartialMaterial with albedo and normal texture.

```py
# Create the surface with uv using the following methods. (snippet)
surface_tool.add_uv(uv1)
surface_tool.add_vertex(verts[0])

# FInally complete the mesh.
surface_tool.index()
surface_tool.generate_normals()

mesh_instance.set_mesh(surface_tool.commit())
mesh_instance.set_surface_material(0, material)
```

| Created with SurfaceTool 👎  | Created with Editor 👍 |
| --- | --- |
|![mesh-instance-created-with-surface-tool](https://user-images.githubusercontent.com/53160891/135527175-04d23a1b-2f8a-403a-b99e-95d7217fe164.jpg) | ![mash-instance-created-in-editor](https://user-images.githubusercontent.com/53160891/135527174-13175459-9410-4910-bde5-e0365eff94cb.jpg) |

Both uses the same material. The normal map not working on the surface tool one. Just makes abedo darker.

Demo project: See some posts below...

**Comment by twoco** [comment]
@Calinou Sorry 😓 here it is. I hope it helps. 
[GitHub #53269.zip](https://github.com/godotengine/godot/files/7262502/GitHub.53269.zip)

**Comment by twoco** [comment]
Ok fixed by adding `surface_tool.generate_tangents()` in my code after `surface_tool.generate_normals()`.

```py
surface_tool.generate_normals()
surface_tool.generate_tangents()
```

Can some explain that?

**Comment by clayjohn** [comment]
We should add an explanation here https://docs.godotengine.org/en/stable/classes/class_spatialmaterial.html#class-spatialmaterial-property-normal-texture

Saying that you need tangents for normal maps to work.
