### ISSUE TITLE
[Godot 4] backspace shortcut doesnt work at `Line 1` when selected

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#53274]
### Godot version

Godot Engine v4.0.dev.custom_build (2d08457f58c21c858923a546a4f29b99640ff800)

### System information

manjaro 21, AMD Radeon r7 200 series, Vulkan, 8GB Memory

### Issue description

![Peek 2021-09-30 19-06](https://user-images.githubusercontent.com/58845030/135536491-eea4ff6f-50d4-4cf4-a68f-045d5a3bd718.gif)

As you can see in the gif above, when I select a word in `line 1` it doesnt get deleted when pressing backspace
only if I delete one by one letter.

### Steps to reproduce

* Create a script
* Type anything in line 1
* Select and press backspace
* shouldnt work

### Minimal reproduction project

N/a

**Comment by Calinou** [comment]
cc @Paulb23
