### ISSUE TITLE
UV1 for Material works differently between image texture and viewport texture when using CudeMesh

### ISSUE THREAD

**Issue by meowyih** [godotengine/godot#53294]
### Godot version

3.3.3.0 stable official

### System information

Windows 7/10

### Issue description

According to docs, if user wants to apply texture on each face of CubeMesh, they can set UV1 as (3,2,1). It implies UV1 will duplicate the texture if we double or triple the UV1 value.
It works correctly when I use image texture. But when using viewport texture, UV1 does not duplicate the original viewport texture from one to six. Instead, it extends the last pixel at the edge of the viewport.
Here is the result of image texture with UV1(3,2,1)
https://github.com/meowyih/CubeViewTexture/blob/main/good.png
Here is the result of viewport texture with UV1(3,2,1)
https://github.com/meowyih/CubeViewTexture/blob/main/bad.png 

### Steps to reproduce

I wrote detail as well as a small Godot project here:
https://github.com/meowyih/CubeViewTexture

### Minimal reproduction project

https://github.com/meowyih/CubeViewTexture

**Comment by Calinou** [comment]
ViewportTextures don't have repetition enabled, and there is no way to enable it: https://github.com/godotengine/godot/issues/36820
