### ISSUE TITLE
sin cos and tan not working properly

### ISSUE THREAD

**Issue by Trafel** [godotengine/godot#5330]
The sin cos and tan functions don't seem to be working properly.
For example, if I use atan(164 / 290), it returns "0.515879" instead of returning the angle value which should be 26 or so.

**Comment by mohaalak** [comment]
first of all, atan will give you radians you should convert it to  degree using rad2deg and second it  will be 29.48 degree not 26.
I think you should close this issue.

**Comment by volzhs** [comment]
And you won't get correct value with ``164 / 290``. you need to do with ``164.0 / 290`` or ``164 / 290.0`` or ``164.0 / 290.0``
