### ISSUE TITLE
Materials not rendering properly on mobile

### ISSUE THREAD

**Issue by GGGomer** [godotengine/godot#53304]
### Godot version

v3.3.3.stable.official [b973f997f]

### System information

Windows 10, GLES3, Android 11, Samsung A52 5G

### Issue description

Textures / Material aren't showing on mobile but are in the debug window and editor.

Model and material from Blender, imported with GLTF using embedded GLTF

Windows:
![image](https://user-images.githubusercontent.com/73346372/135644048-d8f7fbd9-7ad6-47da-8c42-9808902d7189.png)

Mobile:
![image](https://user-images.githubusercontent.com/73346372/135644358-e01564db-0b13-4f8c-986b-63074c124ce1.png)

### Steps to reproduce

Create basic model in blender. Add UV Map. Export as GLTF. Import into godot. Build scene for mobile.

### Minimal reproduction project

[Winkel.zip](https://github.com/godotengine/godot/files/7268253/Winkel.zip)

**Comment by Calinou** [comment]
> GLES3

Try using the GLES2 renderer instead, which works more reliably on mobile devices overall.

**Comment by GGGomer** [comment]
As GLES2 renderer has a huge discrepancy in quality of Debug rendering on Windows and on actual mobile i'd rather not. I can't always debug on an android phone and making a complete project only for it to look awful on mobile devices is a huge waste of time. 

I tried tweaking with the .mobile settings but the difference is still immense. 

![image](https://user-images.githubusercontent.com/73346372/135646513-ea8ba1f7-bfc8-4523-96ad-01e46d5cf71d.png) 
![image](https://user-images.githubusercontent.com/73346372/135646610-f611c1d1-65de-4646-bb02-b1f90abedb18.png)

**Comment by Calinou** [comment]
> As GLES2 renderer has a huge discrepancy in quality of Debug rendering on Windows and on actual mobile i'd rather not. Shadows are incredibly inconsistent between the two. I can't always debug on an android phone and making a complete project only for it to look awful on mobile devices is a huge waste of time.

The mobile renderer uses a faster but lower-quality shadow filter mode by default, so this is expected. You can set it to `PCF13` on both platforms when using GLES2 to maximize shadow filtering quality, but this is slow on mobile.

**Comment by GGGomer** [comment]
I'll try to figure something out! Thanks for the help!
