### ISSUE TITLE
Mixed error message in the console : ERerror: deROvR:i FcileeA ccnesosWtin dofwso::uclnosde:

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#5331]
**Operating system or device - Godot version:**
Official 2.0.3stable, win64

**Issue description** (what happened, and what was expected):

IT IS NOT A JOKE (See screenshot) 

````
ERerror: deROvR:i FcileeA ccnesosWtin dofwso::uclnosde:
 errCoondrit:i ondevi 'c reen amneo_etr rforo 'u nd
is true.
    At: drivers\windows\file_windows.cpp:135
RV: -1
````

Maybe we have a Klingon or Goa'uld in the devteam ?

**Steps to reproduce:**
Could not reproduce. But thought it would worth a see ...

**Link to minimal example project** (optional but very welcome):
![bug_bizare_ererror](https://cloud.githubusercontent.com/assets/9801802/16226021/d45dba2c-37a9-11e6-8f0a-375824d90fd2.png)

**Comment by SuperUserNameMan** [comment]
It is a mix of several error messages.

When I launch the editor again, I have these two errors :
````
error: device not found
error: device not found
````
If we remove their characters from the weird error message, the remain is :

````
ERROR: FileAccessWindows::close:
 Condition ' rename_err '
is true.
    At: drivers\windows\file_windows.cpp:135
RV: -1
````

**Comment by reduz** [comment]
I don't have the slightest clue about what changes this, so any clues welcome

**Comment by SuperUserNameMan** [comment]
@reduz : i've just got an intuition about this one because of the little greenish android icon that briefly appear and disappear each time i run the editor.

I've found that the two little ``error: device not found`` message appear only when the path to ADB is set into the Editor's setting.

My understanding is that, sometimes, ADB and Godot happen to write to the console at the same time, and their messages get mixed.

**Comment by SuperUserNameMan** [comment]
I managed to reproduce similar issue by OS.execute()ing external program that wrote on the console at the same time than godot.

It is thus obvious that it is not a Godot bug.

This issue can then be closed.
