### ISSUE TITLE
SSAO graphic glitches on html5

### ISSUE THREAD

**Issue by JamesC01** [godotengine/godot#53312]
### Godot version

3.3.4.stable

### System information

Windows 10, gtx 1050 ti

### Issue description

If you enable SSAO, and test it with the 'run in browser' button, you get very strange graphic glitches.

### Steps to reproduce

Enable SSAO, and test it with the 'run in browser' button.

**Comment by clayjohn** [comment]
Duplicate of https://github.com/godotengine/godot/issues/45532
