### ISSUE TITLE
[GDScript 2.0] Editor hang caused by `GDScript::_base` self recursion

### ISSUE THREAD

**Issue by briansemrau** [godotengine/godot#53325]
### Godot version

4.0.dev (90f8eb7aa0)

### System information

W10

### Issue description

Somehow, a script is assigning itself as its base script. This is an invalid state causing unexpected behavior, (in this case endless recursion in `EditorData::script_class_get_base`).

![image](https://user-images.githubusercontent.com/6376721/135706244-d9b614e2-679f-4b67-bff1-92f92d544b3e.png)
Notice `base` points to the same address as `this`.

### Steps to reproduce

Create two GDScript classes, one extending another.
Make the class_name of the base type a substring of the class_name of the inheriting type.

```gdscript
class_name MyTypeAbstract
extends Node
...
class_name MyType
extends MyTypeAbstract
```

### Minimal reproduction project

~~This is not minimal, but it reproduces the issue.
https://github.com/BraindeadBZH/godot_card_engine/archive/refs/heads/godot4.zip
The script that ends up with its base class assigned to itself is `res://containers/card_list/card_list.gd`~~

MRP:
[GDScriptBaseTypeWrongMRP.zip](https://github.com/godotengine/godot/files/7271608/GDScriptBaseTypeWrongMRP.zip)

**Comment by briansemrau** [comment]
@BraindeadBZH for your reference

**Comment by BraindeadBZH** [comment]
To give some context, card_list.gd script is inheriting from the card_list_private.gd, which inherits from abstract_container.gd, which is a Control based scene. They all use class_name and extends using it.

**Comment by briansemrau** [comment]
Found the root cause of the issue:

https://github.com/godotengine/godot/blob/master/modules/gdscript/gdscript_compiler.cpp#L112

The expression `(!main_script->name.is_empty() && class_type->fqcn.begins_with(main_script->name))` is an incomplete comparison (`CardListPrivate` interpreted equivalently as `CardList`), leading to the script to believe the class is a local class, creating the script self-reference.
