### ISSUE TITLE
scons vsproj=yes generated files are incomplete with Mono

### ISSUE THREAD

**Issue by ganondev** [godotengine/godot#53344]
### Godot version

9c2a976a7784de79aecdbd3cb381991d047b1b7d

### System information

Windows 10

### Issue description

According to the [Visual Studio setup guide](https://docs.godotengine.org/en/stable/development/cpp/configuring_an_ide/visual_studio.html), the steps to setup VS for use with the engine is basically
```sh
scons platform=windows vsproj=yes
```
then defining a path to some sample project in the Debugging section of the C# project properties. However, with these steps I get red lines on any Mono includes, and thus many red lines anywhere that Mono types are used. I ended up having to define that manually:
![image](https://user-images.githubusercontent.com/76646757/135734443-aeb52f30-c83f-45ac-b5c1-2940f1d1a29d.png)

Considering that scons is definitely aware of my Mono installation and is able to locate the headers and libs, I feel like the generated VS solution and projects should have this information without additional intervention.

There were a few other things I had to define manually on the NMake section of the project properties:

- `module_mono_enabled=yes mono_glue=yes` on `Build Command Line` and `Rebuild All Command Line`
- change `Output` from `bin\godot.windows.tools.64.exe` to `bin\godot.windows.tools.64.mono.exe`
- define `MONO_GLUE_ENABLED` in `Preprocessor Definitions`

I feel like scons should be able to take care of all of this when generating the solution files.

### Steps to reproduce

Follow steps in [Visual Studio IDE Setup Guide](https://docs.godotengine.org/en/stable/development/cpp/configuring_an_ide/visual_studio.html).

When it comes to running scons, it doesnt matter if flags like `module_mono_enabled=yes mono_glue=yes` are given - the results are the same.

**Comment by Calinou** [comment]
cc @neikeq

**Comment by akien-mga** [comment]
Probably yes.
