### ISSUE TITLE
[Godot 4] Bones in SkeletonIK chain detaching from mesh and behaving incorrectly

### ISSUE THREAD

**Issue by J-L-42** [godotengine/godot#53358]
### Godot version

v4.0.dev.custom_build [90f8eb7aa]

### System information

Manjaro Linux

### Issue description

I tried to set up a SkeletonIK chain in Godot 4 (built from master), but had some very strange behaviour. Bones would detach themselves from the mesh and start spasming, as if they weren't quite sure how to orient themselves. I managed to reproduce the issue with [this tutorial](https://www.youtube.com/watch?v=Q4o_7_Rh510), which I updated to Godot 4 and attached below. You can see when you move the target position around that the arm separates itself from the hand and the shoulder, and sometimes starts to spin round and round. See below:

https://user-images.githubusercontent.com/11395459/135761689-20ce0b18-2a17-49fe-a821-91095530e2b4.mp4

I loaded up the same project in Godot 3.3.3 and it works as expected (as in, the arm stays attached to the hand). See below:

https://user-images.githubusercontent.com/11395459/135761704-5329ecec-e41c-4b61-aebf-dd817891be00.mp4

### Steps to reproduce

1. Load the minimal reproduction project and open `Character.tscn`
1. Play the IK on the `SkeletonIK` node
1. Drag the `TargetPosition` node around
1. The bones will start separating and spinning around

### Minimal reproduction project

[ik.zip](https://github.com/godotengine/godot/files/7273983/ik.zip)

**Comment by Calinou** [comment]
cc @TwistedTwigleg

**Comment by TwistedTwigleg** [comment]
I can confirm the issue occurs with the latest version on `master`. I'll see if I can figure out what is going on and make PR with a fix.

**Comment by TwistedTwigleg** [comment]
Initially I thought it was the automatic Maximio rig tool and it's strange bone forward directions it tends to use that was causing the issue, but I did some testing and it seems like that is not the case, as a 3D model that I know has a consistent bone direction of Y+ also has the same issue. Instead it seems like something with the rotation code in the SkeletonIK node either changed or one of the functions it relies on changed functionality (or I suppose one of the changes to the Skeleton node itself could have caused the issue).

The issue does not occur with the new Skeleton_Modification3DFABRIK, so it seems to be SkeletonIK specific. I'll see what I can do, but I'm not totally sure if I'll be able to find a fix (at least not quickly, as I don't totally understand how SkeletonIK calculates the rotation for the bones).

**Comment by fire** [comment]
@TwistedTwigleg I am contemplating removing SkeletonIK3D. Going to try it in my prs and report back. The proposal you mentioned to make SkeletonIK3D a standalone node with the stack internally was complicated. https://github.com/godotengine/godot-proposals/issues/3099
