### ISSUE TITLE
[Godot 4] AnimationTree cannot read an imported animation player's animations - must save to file and load inside a new animation player

### ISSUE THREAD

**Issue by Duroxxigar** [godotengine/godot#53357]
### Godot version

4.0 dev (a88e820)

### System information

Windows 10

### Issue description

When using the animation tree with an imported animation player that has imported animations (animations from an external program that were not saved to a file), none of the animation tree's animation resource nodes can use the imported animation.

### Steps to reproduce

Imported [open 3D mannequin](https://github.com/GDQuest/godot-3d-mannequin) and let it import the animations. Did not save to a file.

Create a new AnimationTree and point it to the imported animation player. Any animation node inside of the various AnimationTree node resources does not allow the selection of any of the animations.

If you create a new animation player (will probably work with the imported one as well) and just create new animations that way (to include being able to load the imported animations after saving them to a file), the animation tree works as expected.

### Minimal reproduction project

[anim-tree-bug.zip](https://github.com/godotengine/godot/files/7273993/anim-tree-bug.zip)

**Comment by KoBeWi** [comment]
Is this still reproducible in newest alpha?
Not sure how to test tbh.

**Comment by Sekitan** [comment]
Just tested on Alpha 11, still doesn't work.  The animation will play inside of the AnimationTree editor but calling AnimationTree State Machine Travel("state") will simply not work.  I had to save the animations to file and add them to a new animation node for them to work.

I also ran into a variety of smaller issues as I was going through this process, in no particular order:
- This is mentioned in another issue, but the glt importer is hardcoded to ignore animation tracks at the rest state, so my default T-Pose animation was empty when I saved to disk, but not when I imported it built-in.
- When saving animations to disk, you have to manually check each animation, assign a folder, and manually type the filename for every animation.  There's no option to click on the AnimationPlayer node in the import menu and have all of them saved to a selected folder.
- The AnimationTree needs a manually created AnimationPlayer to use animations.  After importing my model and manually saving all of the animations to disk I had to create an exact copy of the imported AnimationPlayer right next to it for the AnimationTree to use.
- When manually adding animations to an AnimationPlayer by creating a new animation library the "copy from clipboard" button doesn't work and animations must be manually selected one-by-one, there's no option to have it load all of the animations contained in a folder for example.
- Animations linked in the AnimationTree are unique to that specific AnimationPlayer.  Even if another AnimationPlayer has the same animations with the same name the AnimationTree State Machine nodes must be DELETED and re-created from scratch for the new animations to be recognized.
- Not specifically Animation related but the Editor's current ui focus system is buggy; focus will break so tooltip popups will not appear in menus, one time after creating a new AnimationPlayer animation library the "select animation" drop-down menu's focus was bugged so I couldn't select any animations, restarting the editor returned things to normal.

I'll add more if I find any.

**Comment by tredokiller** [comment]
I have the same problem in beta 10,  I imported fbx model with animations  and then added another one. In AnimatonPlayer it  works good but when I am adding AnimationTree all of my animations doesnt work , I have only T-Pose.

**Comment by SaracenOne** [comment]
I've been testing this, and while I'm not able to get the issue of not being able to select an animation in the AnimationTreeEditor from an imported animation player, I did notice that the AnimationTree would not update to actually process the animations when the associated AnimationTree's AnimationPlayer changed. I seem to be able to fix this by forcing the cache to update when the AnimationPlayer changes.

**Comment by SaracenOne** [comment]
Would it be possible to test this PR to confirm whether or not this addresses the problem?
https://github.com/godotengine/godot/pull/71949

**Comment by TokageItLab** [comment]
Closed by https://github.com/godotengine/godot/pull/71949.
