### ISSUE TITLE
Identifiers have wrong syntax highlighting color if placed after type hint syntax enclosed within a string

### ISSUE THREAD

**Issue by sheshire63** [godotengine/godot#53363]
### Godot version

3.3.3.stable

### System information

Linux

### Issue description

variables in a function call are getting colored green if they are after a string that ends with specific symbols
![GodotSyntaxHighlightBug](https://user-images.githubusercontent.com/58045864/135766543-d9f75fa8-a9fb-4462-be30-ddba271c656c.png)

### Steps to reproduce

```gdscript
extends Node


var example := ""

func _ready() -> void:
	print(":" + example)
	print("->" + example)
	print("" + example)
	echo(":" + example)
	echo("->" + example)
	echo("" + example)

func echo(x) -> String:
	return x
```

**Comment by Calinou** [comment]
This is fixed in the `master` branch:

![image](https://user-images.githubusercontent.com/180032/135766879-dd7e4c9c-ce93-4ae7-9432-776f9138b125.png)

**Comment by MewPurPur** [comment]
This has been fixed by https://github.com/godotengine/godot/pull/65974
