### ISSUE TITLE
Selecting an audio bus effect then selecting a node and pressing delete will delete the bus effect instead of the node

### ISSUE THREAD

**Issue by Miziziziz** [godotengine/godot#53360]
### Godot version

v3.3.4.stable.mono.official [faf3f883d]

### System information

Windows 10, GLES3

### Issue description

Selecting an audio bus effect then selecting a node and pressing delete will delete the bus effect instead of the node

### Steps to reproduce

https://user-images.githubusercontent.com/7292421/135763827-61d973b5-891f-4c90-bd83-9abf00da25e1.mov

Add an effect to an audio bus
click the effect
click a node
press 'del' on your keyboard

**Comment by Calinou** [comment]
This is likely fixed in `master` as part of @EricEzaM's input propagation fixes. I'm not sure if we can fix this in `3.x`.

**Comment by EricEzaM** [comment]
Please discuss further here https://github.com/godotengine/godot/issues/52861
