### ISSUE TITLE
Pausing only part of the tree makes area node stop working

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#53368]
### Godot version

3.4 beta 5

### System information

manjaro 21, AMD Radeon r7 200 series, Vulkan, 8GB Memory

### Issue description

look at the godot output:

https://user-images.githubusercontent.com/58845030/135770397-e1569bcc-426f-42bb-a8aa-06fa59ed8773.mp4

There are three pause modes:

`enum PauseMode {PAUSE_MATERIAL,PAUSE_SPIRITUAL,PAUSE_BOTH}`

![image](https://user-images.githubusercontent.com/58845030/135770456-bd1a4b5e-7612-410f-b5de-457091a300b1.png)

MATERIAL - will pause the material named node
SPIRITUAL - will pause the spiritual named node
BOTH - will pause the two nodes

this is done via `PauseManager.gd`

```gdscript
extends Node



enum PauseMode {PAUSE_MATERIAL,PAUSE_SPIRITUAL,PAUSE_BOTH}
var current_mode:int = 0

func _ready():
	pause_mode = PAUSE_MODE_PROCESS
	set_pause(false, PauseMode.PAUSE_BOTH)
func _input(event):
	
	if event is InputEventKey:
		if event.pressed:
			if event.scancode == KEY_F1:
				current_mode +=1
				if current_mode > 2:
					current_mode = 0
				print("Pause Mode Selected: ", PauseMode.keys()[current_mode])
				
				pass
			elif event.scancode == KEY_F2:
				
				set_pause(!get_tree().paused,current_mode)
				print("Paused ", PauseMode.keys()[current_mode], ": ", get_tree().paused)
				pass
	
	pass

func set_pause(pause:bool = true, mode:int = PauseMode.PAUSE_BOTH) -> void:
	var plane_mat:Node = get_tree().get_nodes_in_group("PLANE_MATERIAL")[0]
	var plane_spiritual:Node = get_tree().get_nodes_in_group("PLANE_SPIRITUAL")[0]
	match mode:
		PauseMode.PAUSE_MATERIAL:
			plane_mat.set_pause_mode(PAUSE_MODE_STOP)
			plane_spiritual.set_pause_mode(PAUSE_MODE_PROCESS)
			pass
		
		PauseMode.PAUSE_SPIRITUAL:
			plane_mat.set_pause_mode(PAUSE_MODE_PROCESS)
			plane_spiritual.set_pause_mode(PAUSE_MODE_STOP)
			pass
		
		PauseMode.PAUSE_BOTH:
			plane_mat.set_pause_mode(PAUSE_MODE_STOP)
			plane_spiritual.set_pause_mode(PAUSE_MODE_STOP)
			pass
	get_tree().paused = pause
	
	pass

```

### Steps to reproduce

* Create two childs of root node
* make one pause_mode STOP
* make another pause_mode PROCESS
* Add an area2D as child of the PROCESS one
* Try to collide with it
* should not work

### Minimal reproduction project

[MRP.zip](https://github.com/godotengine/godot/files/7274484/MRP.zip)

In order to reproduce the video's bug:

* Press F1 until godot prints PAUSE_SPIRITUAL
* then Press F2
* try to get the purple item (it shouldnt work)

**Comment by KoBeWi** [comment]
Here's a truly minimal scene:
[PauseTest.tscn.txt](https://github.com/godotengine/godot/files/7274639/PauseTest.tscn.txt)

This is not a bug. Physics are paused when scene tree is paused, regardless of pause mode. See #4001
Here's some workaround, not sure if it still works: https://godotforums.org/discussion/25602/area2d-not-working-with-pause-on
But I'd suggest to not use pausing in this case.
