### ISSUE TITLE
Doctool erroneously reorders constants or mixed strings

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#5337]
See this sync diff where constants got badly reordered: https://github.com/godotengine/godot/commit/16ea10c35894ba3c24730382fde71934fb549fb4

And also this PR where a string was moved to a wrong function: https://github.com/godotengine/godot/pull/5239

**Comment by djrm** [comment]
Fixed by #5350?

**Comment by akien-mga** [comment]
At least the first part yeah. I'll be on the lookout for issues like in #5239, but let's close this issue and see how things go.
