### ISSUE TITLE
Non existent 'ghost' keyframe added to animation

### ISSUE THREAD

**Issue by svprdga** [godotengine/godot#53389]
### Godot version

3.3.4

### System information

Linux Mint

### Issue description

For some reason, there is a 'ghost' key frame in a 2D animation. Please do the following in order to understand exactly:

1. Check the issue happening [(video)](https://u.pcloud.link/publink/show?code=XZ73j6XZgkvJynQVCujArxMvkWmElBBm5rq7)
2. In the video I show that a non-existent keyframe is added at the end of the animation, but there is not keyframe in this place.

### Steps to reproduce

1. Create a 2D animation

**Comment by Calinou** [comment]
This is because the animation interpolation will smoothly loop back to zero. To fix this, change the loop mode to **Clamp Loop Interp** instead of **Wrap Loop Interp** by clicking the track loop icon next to the trash can icon.

**Comment by svprdga** [comment]
Thank you @Calinou, I didn't know that.
