### ISSUE TITLE
GDScript code hint doesn't match my current typing(hint lags some distance behind) some time

### ISSUE THREAD

**Issue by kalenclark** [godotengine/godot#53384]
### Godot version

v4.0.dev.custom_build [66ab3ce95]

### System information

Pop! OS (Linux, X11 window system)

### Issue description

I just disabled some modules like mobile_vr, GDNative...
I did not modify any core code,
I tried Godot 3.x from official site and this problem disappeared
**If I type in "VideoStream", it should highlight "VideoStream" in code hint,**
but instead, **I got only "VideoStre" highlighted in the hint as img below shows**
![Screenshot from 2021-10-04 18-00-21](https://user-images.githubusercontent.com/7891503/135835697-2075cd37-caf9-4179-87ea-b8927a4b7dcf.png)

### Steps to reproduce

Just open Godot 4, create a GDScript and type in "VideoStream"

**Comment by EricEzaM** [comment]
Hmm, is the hint lagging, or is the completion popup just offset an incorrect amount?
I'm on Win 10

See how mine is in line with the V and yours isnt?
![image](https://user-images.githubusercontent.com/41730826/136023577-a677e889-e851-434b-94eb-b5ab6f5b0e89.png)

Although to be fair the popup being offset does not cause any issues for me.
![image](https://user-images.githubusercontent.com/41730826/136023956-06973388-a2f3-4968-90bd-816475aad02a.png)

**Comment by kalenclark** [comment]
> Hmm, is the hint lagging, or is the completion popup just offset an incorrect amount? I'm on Win 10
> 
> See how mine is in line with the V and yours isnt? ![image](https://user-images.githubusercontent.com/41730826/136023577-a677e889-e851-434b-94eb-b5ab6f5b0e89.png)
> 
> Although to be fair the popup being offset does not cause any issues for me. ![image](https://user-images.githubusercontent.com/41730826/136024036-e5b94065-eeda-4dd7-9ca4-d926d65a0743.png)

I'm considering the background that indicates current matching state
For example, if I type in "VideoStream", it should highlight "VideoStream" in code hint,
but instead, I got only "VideoStre" highlighted in code hint as my img shows

**Comment by akien-mga** [comment]
I can't reproduce this on Mageia 9 Linux / KDE on X11 with either 4.0-stable or 4.1-beta3.

The issue might have been that the background rectangle was not drawn with the right size. This could be due to not properly handling DPI scaling, but for me the bug is still not reproducible with 100%, 75% or 125% editor scaling.

So I'm assuming this was fixed before 4.0-stable. Please let us know if you still reproduce the issue.
