### ISSUE TITLE
Input Mapping configuration popup size doesn't fit all contents

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#53382]
### Godot version

4.0.dev (66ab3ce95)

### System information

Linux, Mageia 9 x86_64

### Issue description

In the Project Settings > Input Map, when adding a new input event to a mapping, the dialog used to capture events is not properly resized to fit its contents:
![Screenshot_20211004_100241](https://user-images.githubusercontent.com/4701338/135825173-5ebb993b-01f8-496e-ac52-b52f60b9a086.png)

CC @EricEzaM @jmb462

### Steps to reproduce

- Open Project Settings > Input Map
- Add new action, add new binding

**Comment by jmb462** [comment]
Can't reproduce the bug.

![image](https://user-images.githubusercontent.com/3649998/135825908-d54a359a-4757-498a-a7af-b0971a868102.png)

The problem is that you can't see Additional Options checkboxes ?

**Comment by akien-mga** [comment]
Yeah, here's how it looks like for me on Linux:

- Open dialog:

![Screenshot_20211004_120501](https://user-images.githubusercontent.com/4701338/135832665-13ebcdf4-6f96-41d1-96a8-3d7ed3c8d5e8.png)

- Click input box, or press <kbd>Esc</kbd> (why is this captured?):

![Screenshot_20211004_120552](https://user-images.githubusercontent.com/4701338/135832784-728478b6-5642-4e77-b1d3-8b52a6f5f688.png)

- After alt-tabbing to Firefox to paste this screenshot:

![Screenshot_20211004_120615](https://user-images.githubusercontent.com/4701338/135832855-3040df98-8a52-47f9-9bec-0331a26f04cf.png)

- After resizing the window (just a few pixels to the right):

![Screenshot_20211004_120644](https://user-images.githubusercontent.com/4701338/135832910-18fbbfdd-c764-493f-b220-63ae2122b2fd.png)

So this looks like a bug with the X11 DisplayServer.

**Comment by jmb462** [comment]
Cannot reproduce it under Linux Ubuntu 21.04

**Comment by jmdejong** [comment]
Can confirm that this stil happens in arch linux with the alpha build:
![input_key_partially_rendered](https://user-images.githubusercontent.com/7968950/152854631-115a4b72-3110-4c69-a0e3-dca0f84c3ef1.png)

Somehow the bottom part of the window is not rendered until it is resized

**Comment by akien-mga** [comment]
> It might be related to #56548 since it also fixed by having the window lose and regain focus

Tested in 77c2bfb63 and I can still reproduce the bug, #56548 didn't seem to fix it.

**Comment by akien-mga** [comment]
Fixed by https://github.com/godotengine/godot/issues/53382.
