### ISSUE TITLE
`&&` and `and` have different syntax highlighting.

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#53385]
### Godot version

3.0+

### System information

N/A

### Issue description

The syntax highlighting colours for `and`, `or` etc. are not the same as for `&&`, `||` etc. This might confuse some people.

![53385_demonstrator](https://user-images.githubusercontent.com/324679/135843441-b726ffec-780b-4af9-9aab-885200c58e81.png)

### Steps to reproduce

`if (ring_collected && ring_sprite.animation == "Sparkle" and ring_sprite.frame >= 6):`

**Comment by Calinou** [comment]
`&&` and `||` are symbols, not keywords. (Besides, they have been deprecated in 4.0, so I wouldn't spend too much effort trying to make them look like keywords.)

**Comment by KoBeWi** [comment]
We could just remove them instead of deprecating. They are very easy to replace.

**Comment by Zylann** [comment]
Keywords and symbols being colored the same isn't actually that widespread, so I'm not sure if there is consensus on that. Seems quite random or preferential. I never paid attention to this detail tbh.
Sublime Text's Monokai theme does highlight them with the same color in Lua and Python, but not in C++ and C#. Switching to another theme no longer highlights using the same colors.
In VSCode it's not the same color either for Python and C++.
Notepad++ doesnt highlight with same color either in Python, C++ or Lua.
