### ISSUE TITLE
GDScript: `$` get node (dollar) operator completion issues

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#53395]
### Godot version

4.0.dev (865b62b)

### System information

Linux, Mageia 9 x86_64

### Issue description

While working on #53303, I found two issues with the completion for GDScript's `$` get equivalent operator (which is equivalent to calling the `get_node()` function). Both are still reproducible even once #53303 will be merged.

- [ ] Completion options are not limited to only valid NodePaths. All classes in the global scope seem included:

![Screenshot_20211004_163122](https://user-images.githubusercontent.com/4701338/135870025-b3f54308-6db5-42ad-a058-a37e584b6e75.png)

- [ ] Completion a NodePath which needs quotes (e.g. with spaces or invalid characters for an identifier) will include two quotes at the end when pressing <kbd>Tab</kbd>:

![Screenshot_20211004_163143](https://user-images.githubusercontent.com/4701338/135870197-ec7b2e82-f138-4bc3-9ab2-54b007eab2b3.png)

![Screenshot_20211004_163243](https://user-images.githubusercontent.com/4701338/135870275-be7c3bf6-37c5-4a88-93dc-974b708c1454.png)

### Steps to reproduce

- Open GDScript editor for a script attached to a node with child nodes
- Use the `$` operator and try to complete node paths, including paths with spaces

**Comment by akien-mga** [comment]
I haven't tried to debug but the issue probably lies in `CodeEdit::confirm_code_completion()` or nearby.

**Comment by EricEzaM** [comment]
With the first one, the issue appears to be the parser incorrectly determining the context:
![image](https://user-images.githubusercontent.com/41730826/136057814-12061ad1-d750-4234-9235-aafa3d7523be.png)

It should be returning `GDScriptParser::COMPLETION_GET_NODE`
https://github.com/godotengine/godot/blob/198b49d8b589e88a5ae61fc8418ebf8890d2d1f7/modules/gdscript/gdscript_editor.cpp#L2648-L2653

**Comment by HolonProduction** [comment]
The problem lies with the parser which is supposed to update the completion context. The function `parse_get_node` has some checks at the beginning and only pushes a completion context if they don't fail. But without something after `$` the checks fail (correctly, this isn't valid GDScript but we want completion anyway.). The completion for get node doesn't use any properties of `CompletionContext` so pushing an empty context of type `GET_NODE` when the checks fail should work fine.
