### ISSUE TITLE
RigidBody's bouncing fails to stop.

### ISSUE THREAD

**Issue by WaterExpensive** [godotengine/godot#53391]
### Godot version

3.3.4

### System information

Solus OS, AMD CEDAR (DRM 2.50.0 / 5.13.12-193.current, LLVM 12.0.1), GLES3

### Issue description

Hey there, been trying Godot for a while and loving to test new stuff! but...
When setting the bounce setting in RigidBody, It'll continue to bounce on a StaticBody. even when setting it to a really low amount (0.2) it'll do micro-bounces which makes the rigidbody's global position not stop changing.

### Steps to reproduce

1 - make rigidbody and give it a rectangle collision shape
2 - make another scene and put a staticbody on it, and then put rigidbody on top
3 - set rigidbody's bounce setting to any amount
4 - test-play

### Minimal reproduction project

[Problematic Plastic.zip](https://github.com/godotengine/godot/files/7278458/Problematic.Plastic.zip)

**Comment by pouleyKetchoupp** [comment]
Closing as duplicate of #25186.
