### ISSUE TITLE
AtlasTexture texture returns wrong size

### ISSUE THREAD

**Issue by boruok** [godotengine/godot#53390]
### Godot version

v3.4.beta.custom_build [a5159f352]

### System information

PopOS 21.04

### Issue description

Tried to printout generated AtlasTexture with 32x48px (**actual**) size.
![house](https://user-images.githubusercontent.com/36783322/135858136-9fa23f12-5859-4743-a8ef-83481bddd02e.png)
_i filled transparent pixels with purple color for readablility._

```gdscript
extends Sprite

func _ready():
	print(texture.get_data().get_size())

# output (30, 43)
# i believe this is are trimmed size of texture.
```

meanwhile inspector displays correct size...
![image](https://user-images.githubusercontent.com/36783322/135858612-ec000646-48a5-4f2e-9188-4083e0f81207.png)

another weird behiavour is, if you try apply outline shader, resulting image is, white outline must surrounds texture.
![image](https://user-images.githubusercontent.com/36783322/135859114-09996a49-f1f8-4920-a67b-ffa185d531ac.png)

I suggest is godot trims transparent pixels from texture, need option to generate atlas **as is** with transparent pixels.

### Steps to reproduce

1. open attachment

### Minimal reproduction project

[New Game Project.zip](https://github.com/godotengine/godot/files/7278296/New.Game.Project.zip)

**Comment by kleonc** [comment]
>AtlasTexture texture returns wrong size

@boruok It's rather the opposite - it returns the correct size but its `get_data()` returns data only for its `region` property (`margin` isn't taken into account in there). And you're the one who implemented for `AtlasTexture.get_data()` like that in #53157.

> I suggest is godot trims transparent pixels from texture, need option to generate atlas as is with transparent pixels.

I'd say `get_data()` for `AtlasTexture` should either create an `Image` with all relevant data (region + all transparent pixels included) or it should be unsupported. Current implementation (returning data just for the `region`) isn't consistent with what `get_data()` is supposed to return (all data for the given `Texture`). So I'd opt for changing `AtlasTexture.get_data()` to return all the data. And if someone wants just the data for the `region` then it still could be retrieved manually the same way the current implementation of `AtlasTexture.get_data()` works:
```
# 3.x
var at: AtlasTexture = ...
var region_data: Image = at.atlas.get_data().get_rect(at.region)
```

**Comment by boruok** [comment]
@Calinou i think it's good practice to develop games with user device at mind, its can be potato machine or lowend smartphone. Especially for mobile devices, where you user session are limited with battery. As far as rendering is most expensive process it would be good if godot engine provide builtin texture packing tool.
> Without these optimizations in place, you might as well use standard textures with the Region property to crop them.

But in that way it's nearly impossible to keep track/manage all of your textures. If you have 320+ items and more on the way. Meanwhile engine can arrange atlas by itself (adding, removing, updating existing items) by now.
**Anyway i suggest allow user to decide to trim or not imported textures.**
![image](https://user-images.githubusercontent.com/36783322/135942074-72de95b3-ad9f-49f7-a8e6-ce62a391e45f.png)

**Comment by jasonwinterpixel** [comment]
Just got bit by this. We have a ton of regions specified in StyleBoxes throughout our large game. I am going through and putting stuff into spritesheets now and all the Styleboxes have the wrong coordinates now.

If the developer expects a texture of a certain size and with certain contents, then the engine should give the developer what they asked for. Even things like scaling artifacts are changed by having a border of transparent pixels.

**Comment by jasonwinterpixel** [comment]
I created a PR which has a new option for AtlasTexture imports to disable this behaviour:

https://github.com/godotengine/godot/pull/57163

**Comment by boruok** [comment]
@jasonwinterpixel thanks!
