### ISSUE TITLE
Camera2D preview doesn't show correctly when parent moves

### ISSUE THREAD

**Issue by Alex-doc** [godotengine/godot#5339]
**Operating system or device - Godot version:**
regarding [1566da2](https://github.com/godotengine/godot/pull/4373)

**Issue description** (what happened, and what was expected):
The preview shows incorrect behavior if the parent node is moved

**Steps to reproduce:**
- add node to scene
- add another node "A" (Node2D would work)
- add a Camera2D  as child in "A"
- move "A"

**Link to minimal example project** (optional but very welcome):
https://www.dropbox.com/s/9ivvyy9k06mrul5/cambug.zip?dl=0

**Comment by bojidar-bg** [comment]
Can confirm, would try to fix quickly...
