### ISSUE TITLE
Startup errors: `Error calling from signal 'changed' to callable`

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#53404]
### Godot version

adc9500e5497c7427f91d7cbf9985f74cbb3451c

### System information

Windows 10

### Issue description

Multiple errors spammed at startup:
`ERROR: Error calling from signal 'changed' to callable: Theme::_emit_theme_changed : Method expected 1 arguments, but called with 0..`

Regression from 55c9cc21e934d1217e6fdb8999c6556c8457b7d8 cc @pycbouh 

### Steps to reproduce

Run a project manager.

### Minimal reproduction project

No need.

**Comment by pycbouh** [comment]
I can't reproduce it, neither by starting the PM or the editor with a project.

**Comment by akien-mga** [comment]
The error makes sense though since `_emit_theme_changed` now takes an argument, while it's connected without any binds. I don't think the signal connections handle default C++ parameters.

**Comment by pycbouh** [comment]
Yes, but I thought it was what `DEFVAL` was for?..

```
ClassDB::bind_method(D_METHOD("_emit_theme_changed", "notify_list_changed"), &Theme::_emit_theme_changed, DEFVAL(false));
```

**Comment by akien-mga** [comment]
For the scripting API yeah but apparently this doesn't seem to be used for signal connections.

Here's an example:
```
editor/filesystem_dock.h
198:    void _navigate_to_path(const String &p_path, bool p_select_in_favorites = false);

editor/filesystem_dock.cpp
366:                    current_path->connect("text_submitted", callable_mp(this, &FileSystemDock::_navigate_to_path), make_binds(false));
```

**Comment by akien-mga** [comment]
I just compiled 8f227e9da3fd2dc10782c2ff42ed8c8e0632c82f and I can reproduce the errors when opening the project manager.

**Comment by pycbouh** [comment]
Wait, I know how I can't reproduce it. Chaosus has linked wrong commit, this is in master, the commit of my that is linked is from 3.x. So I'm testing in 3.x, and there is no such problem with the old binds (and that's where I've used DEFVAL to being with).

So it's only in master, I guess.

**Comment by Chaosus** [comment]
Ah, yeah, a little mistake, sorry.
