### ISSUE TITLE
Color class string constructor won't construct from its own ToString()

### ISSUE THREAD

**Issue by BenMcLean** [godotengine/godot#53415]
### Godot version

3.3.2.stable

### System information

Windows 10

### Issue description

The Godot.Color class outputs a string in a different format than it takes as input.

I'm doing C# in Godot 3 but I expect that the same issue probably affects all versions of Godot.

### Steps to reproduce

This code here:
```csharp
Godot.Color testColor = new Godot.Color(Godot.Color.Color8(0, 255, 255, 255).ToString());
```

results in this exception:

```
modules/mono/mono_gd/gd_mono_utils.cpp:370 - System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: Invalid color code. Length is 7 but a length of 6 or 8 is expected: 0,1,1,1
```

So, if you turn an instance of Godot.Color into a string, then try to construct a new Godot.Color from that string, it isn't allowed, because the output string format does not match the input string format.

What should happen is that Godot should either change the string constructor to accept the format provided by ToString() or it should change the ToString() to match the format of the input accepted by the string constructor. Either way, they should match so that you can easily serialize and deserialize colors in Godot.

This may be just the tip of the iceberg on a larger issue affecting many different data types in Godot.

### Minimal reproduction project

Obviously not necessary in this case.

**Comment by raulsntos** [comment]
You can serialize/deserialize Variants (like `Color`) with `GD.Var2Str` and `GD.Str2Var`.

The `Color(string)` constructor takes an HTML hexadecimal color (like `#ff0000` or `#ff0000ff`, the `#` is optional), this is explained in the documentation.

I would not recommend using `ToString` to do serialization.

**Comment by BenMcLean** [comment]
found out there's also `ToHtml`

closing this, thanks
