### ISSUE TITLE
`OS.window_fullscreen` does not exist any more

### ISSUE THREAD

**Issue by BeayemX** [godotengine/godot#53414]
### Godot version

v4.0.dev.custom_build [2e8cba0bd]

### System information

Linux Mint - Vulkan API 1.2.131 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1080

### Issue description

Changing fullscreen mode via `OS.window_fullscreen = !OS.window_fullscreen` does not work any more and will result in the following error:

```
Invalid get index 'window_fullscreen' (on base: 'OS).
```

### Steps to reproduce

Put this code in any script on any node and press `F11` while the game is running
```
extends Node2D

func _input(event):
	if event.is_echo():
		return
		
	if event is InputEventKey:
		if event.keycode == KEY_F11:
			if event.is_pressed():
				OS.window_fullscreen = !OS.window_fullscreen
```

Using this line instead also does not work

```
				OS.set_deferred("window_fullscreen", true)
```

**Comment by DeeJayLSP** [comment]
It has been moved to DisplayServer, you need to call DisplayServer.window_set_mode() instead.

**Comment by DeeJayLSP** [comment]
The following might work:
``` GDScript
func _input(event):
	if event is InputEventKey:
		if event.keycode == KEY_F11:
			if event.is_pressed():
				match DisplayServer.window_get_mode():
					0: DisplayServer.window_set_mode(3)
					3: DisplayServer.window_set_mode(0)
```

**Comment by BeayemX** [comment]
Thanks, that did the trick.

I took your code and adjusted it a bit to use the enums to make it a bit more readable:

```

func _input(event):
	if event is InputEventKey:
		if event.keycode == KEY_F11:
			if event.is_pressed():
				if DisplayServer.window_get_mode() == DisplayServer.WINDOW_MODE_FULLSCREEN:
					DisplayServer.window_set_mode(DisplayServer.WINDOW_MODE_WINDOWED)
					DisplayServer.window_set_flag(DisplayServer.WINDOW_FLAG_BORDERLESS, false)
				else:
					DisplayServer.window_set_mode(DisplayServer.WINDOW_MODE_FULLSCREEN)
```
