### ISSUE TITLE
Drag n Drop in Scene Tree issues with moving nodes and moving out of parent.

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#5341]
**Issue description** (what happened, and what was expected):
It's impossible to move nodes in the same level. They always parent to some node even when highlight line shows it will move between two nodes.
The same with moving nodes out of level/parent to higher level one instead being moved out of parent they are re parented to different subtree.

**Steps to reproduce:**
Create sub tree and duplicate it few times. Then try to move them out of parent or change positions.

**Comment by neikeq** [comment]
I can confirm this bug after 9b9580f. But sometimes it moves one position further instead of being parented.
