### ISSUE TITLE
Vulkan: Enabling subsurface scattering on BaseMaterial3D spams error in output console

### ISSUE THREAD

**Issue by ModularNucleus** [godotengine/godot#53444]
### Godot version

v4.0.dev.20211004.official [2e8cba0bd]

### System information

Windows 10, Vulkan, Nvidia Geforce GTX1060 6GB (driver: Studio 471.68) )

### Issue description

New to Github / Godot, so apologies if this is unclear or missing information.
My search of the issues did not come up with a similar report.

In Godot pre-alpha 4.0, when enabling subsurface scattering, ouput console spams
the error message:
 "_This render pipeline requires (0) bytes of push constant data, supplied: (16)
  No render pipeline was set before attempting to draw._"

In addition, the 3D gizmo "axis lines" turn black.

This does not happen in version 3.3.3 stable.
EDIT: This does not happen in the pre-alpha with the "Vulkan Mobile" back end,
only with the "Vulkan Clustered" back end.

![Godot 4 pre-alpha - subsurface scattering error](https://user-images.githubusercontent.com/91982860/136084198-c458ef64-f674-41d3-ae01-0170cdaebcda.png)

### Steps to reproduce

1. Open the "subsurface_scattering_error.tscn" scene from the "materialtest" MRP.
2. Enable the subsurface scattering property on the StandardMaterial3D.
3. Check the output console.

### Minimal reproduction project

[materialtest.zip](https://github.com/godotengine/godot/files/7288559/materialtest.zip)

**Comment by ModularNucleus** [comment]
Can reproduce partially in alpha9:
- The console no longer spams an error.
- The 3D gizmo "axis lines" still turn black.
- Moving/rotating the cube in the viewport produces visual artefacts.
- Closing Godot without first closing the scene crashes Godot.

NB: I originally failed to mention that the Mesh is a CSGMesh, which may or may not make a difference.

![Subsurface scattering issue](https://user-images.githubusercontent.com/91982860/172011762-24457fe4-37d7-42d7-a82f-6d6617559915.png)

**Comment by clayjohn** [comment]
This has been fixed. I can not reproduce in RC3
