### ISSUE TITLE
Debugger loses variable scope in the last line of a block

### ISSUE THREAD

**Issue by sszigeti** [godotengine/godot#53442]
### Godot version

3.3.3.stable + v4.0.dev.20211004.official [2e8cba0bd]

### System information

All

### Issue description

As [it was reported in 2019](https://github.com/godotengine/godot/issues/28151#issuecomment-494890396) the debugger loses scope in the last line of a block. The original reporter has promised to create a new issue but I don't think this happened, and when I saw that this is still an issue in 4.0.dev, I wanted to make sure it's not forgotten.

### Steps to reproduce

Have a script like this:

```
for x in 5:
    my_func(x) # set a breakpoint here
```

The debugger won't see  the `x` variable -- unless you edit the script and add another command after this single line

**Comment by sszigeti** [comment]
[This PR might be a fix](https://github.com/godotengine/godot/pull/38608) for this.

**Comment by akien-mga** [comment]
See #63009 for a MRP.

**Comment by akien-mga** [comment]
Fixed by #71093.
