### ISSUE TITLE
Using disable_3d=yes  increases binary size for iOS

### ISSUE THREAD

**Issue by devolonter** [godotengine/godot#53467]
### Godot version

3.3.3

### System information

macOS Big Sur 11.5.2, Xcode 13.0

### Issue description

Using the scons disable_3d=yes parameter increases the size of the iphone binary from ~60MB to ~90MB

### Steps to reproduce

Run
`scons p=iphone target=release disable_3d=yes tools=no --jobs=$(sysctl -n hw.logicalcpu)`
`scons p=iphone target=release tools=no --jobs=$(sysctl -n hw.logicalcpu)`
and compare results

**Comment by akien-mga** [comment]
That seems quite unlikely, are you sure that the two binaries you compare were built with the exact same options and build environment, aside from the `disable_3d=yes` option?

**Comment by devolonter** [comment]
Sorry, my bad! There is also use_lto option. Thanks for help!
