### ISSUE TITLE
Material set_parameter doesn't work properly

### ISSUE THREAD

**Issue by radubolovan** [godotengine/godot#5347]
**Operating system or device - Godot version:** Windows 10 - Godot 2.0.3 stable

**Issue description** (what happened, and what was expected):
The application doesn't work properly when I'm trying to access "set_parameter" function of the "FixedMaterial" class with the "FixedMaterial.PARAM_DIFUSE" parameter type in a GDScript file.

**Steps to reproduce:**
Please see this for more info: http://godotdevelopers.org/index.php?topic=15629.msg16807#msg16807

**Link to minimal example project** (optional but very welcome):

**Comment by vnen** [comment]
In the screenshot from the forum there's no crash, just the debugger saying there's no such constant. This is not really a bug. You can't use the constants from the class definition, you need an object, so you need to do `material.PARAM_DIFFUSE` instead.

**Comment by radubolovan** [comment]
The constant PARAM_DIFFUSE shuld be a constant of a class, not a member of an object.
However, I tried your advise and unfortunately the same thing happen with the cod below:

```
extends MeshInstance

func set_color(color):
	var material = FixedMaterial.new()
	material.set_parameter(material.PARAM_DIFUSE, color)
	set_material_override(material)

func _ready():
	var clr = Color(1,1,1,1)
	set_color(clr)
```

**Comment by RandomShaper** [comment]
`FixedMaterial.PARAM_DIFFUSE` is the way to go.

You missed one _F_!

**Comment by akien-mga** [comment]
Indeed :)

**Comment by radubolovan** [comment]
Yes, it's working with double F. LOL.

I wrote "solved" in the title.
