### ISSUE TITLE
edit connections (improvement)

### ISSUE THREAD

**Issue by ret80** [godotengine/godot#5348]
**Operating system or device - Godot version:**
2.0.x

**Issue description** (what happened, and what was expected):

It would be great if you will be able to add their signals and then connect to it.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by akien-mga** [comment]
Sorry, I don't get it. Connecting to signals is exactly the purpose of this tool, so I don't see what you want as an improvement.

**Comment by ret80** [comment]
user custom signal create and connect

**Comment by ret80** [comment]
add to button "create signal" in editor.

**Comment by vnen** [comment]
For what I get: in GDScript you can add custom signals. This is asking to do this via editor, so you can connect custom signals with the GUI.

**Comment by ret80** [comment]
I made a button. and to process its signals I have to connect to it from the script. but it is more convenient to do it in the editor as well as with a conventional button.

**Comment by vnen** [comment]
There's already an interface for defined signals, is this what you want:

![godot windows opt tools 64_2016-06-21_15-52-37](https://cloud.githubusercontent.com/assets/5599796/16242327/58310782-37c8-11e6-80f2-666a88f284a2.png)
![godot windows opt tools 64_2016-06-21_15-52-55](https://cloud.githubusercontent.com/assets/5599796/16242329/59e8b750-37c8-11e6-9842-6e1ac08ad1fc.png)
![godot windows opt tools 64_2016-06-21_15-56-53](https://cloud.githubusercontent.com/assets/5599796/16242442/cd4d5408-37c8-11e6-99b7-4c160f6c64ea.png)

Or is it for custom signals?

**Comment by ret80** [comment]
I do not see the version 2.1 and do not know what is happening there. but it seems that this is not exactly what I wanted. I need the ability to (create and) connect to user signals via the editor.

**Comment by Hinsbart** [comment]
Btw, custom signals will be added to the signal editor automatically if you define the signal at the top of the script like so:
```gdscript
signal my_signal
```

So that will at least save you from having to connect via code.

**Comment by ret80** [comment]
@Hinsbart  - a splendid news :)

**Comment by ret80** [comment]
and when it is scheduled to release a stable version 2.1. really want to quickly use the new features? :)

**Comment by akien-mga** [comment]
The feature is in 2.0 already, there's not much new functionality wise for this in 2.1.

![itshere](https://cloud.githubusercontent.com/assets/4701338/16243286/cc17db48-37f6-11e6-9300-3a574fabc8c3.png)

**Comment by ret80** [comment]
@akien-mga  no this feature in 2.0.

**Comment by akien-mga** [comment]
That's a screenshot from 2.0.3...

**Comment by MarianoGnu** [comment]
Add a signal from editor is useless, since you still need an script to emit them, but connect signals defined in an script is worth

**Comment by vnen** [comment]
@MarianoGnu that is already possible.

----

This seems to me a request for something that is already on Godot, so no reason to keep open. If I misunderstood then comment clearly about what you really want.

**Comment by ret80** [comment]
What I like:
1 Create a signal from the script (methods may be different, I suggest to create in the editor is not very well)
```
signal  user_signal_name(param_signal)
```
2 When you open the Connection Editor, this signal appears there
3 We can podkryuchitsya editor of this signal.

But as I understood (from the message @Hinsbart) is already implemented in version 2.1. Unless of course I understand correctly

**Comment by neikeq** [comment]
It's quite hard to understand what you are requesting for. If it's not editing signal connections from the editor, then I guess what you are asking for is signal declaration from the editor.
If that's the case, I don't think it makes sense. If you are creating a custom signal, you will have to emit it from the script no matter what, so I don't see the problem with declaring the signal also in the script.

**Comment by ret80** [comment]
later I make pictures showing what I suggest

**Comment by MarianoGnu** [comment]
As i understand he wants to declare a signal on script and connect it from editor. I tryed this on the past, but was not able to do it, probably becase i'm used to call add_user_signal instead of the keyword?
