### ISSUE TITLE
Custom node is greyed out as a target when trying to connect a signal in simple mode

### ISSUE THREAD

**Issue by derkork** [godotengine/godot#53488]
### Godot version

v3.3.3.stable.mono.official [b973f997f]

### System information

Windows 10

### Issue description

I have a custom node written in C# that I have registered using an editor plugin. Now I build a small tree like this:

![image](https://user-images.githubusercontent.com/327257/136265774-50f9d141-2934-42e1-9e0e-fc93deb6a786.png)

Now I want to connect a signal of the Tween to notify my custom node:

![image](https://user-images.githubusercontent.com/327257/136265900-aa3fa2ed-3ddb-44ca-b87e-ad79a53a8af8.png)

The connection dialog opens. As you can see the custom "Folder" node is greyed out and cannot be used as a target:

![image](https://user-images.githubusercontent.com/327257/136266087-772cda00-e421-4671-a615-3a5e0da17ddd.png)

However, once I switch to "Advanced mode", i can suddenly select my custom node as a target:

![image](https://user-images.githubusercontent.com/327257/136266347-6938c7c4-0192-4dbd-8a30-5490752366ce.png)

### Steps to reproduce

Using the attached project:

1. Go to project settings and enable the custom node plugin. This will register the custom node.
2. Open `narf.tscn` which has the sample scene.
3. Select the tween, in the inspector then connect any signal.

### Minimal reproduction project

[SignalIssue.zip](https://github.com/godotengine/godot/files/7296559/SignalIssue.zip)

**Comment by KoBeWi** [comment]
This is not a bug. The dialog only allows selecting nodes with scripts and the default behavior is to add the connected method to script. You can select existing methods only in advanced mode.

Custom node is just treated as a regular node, which is surprisingly correct behavior.
