### ISSUE TITLE
Array.slice() is broken, no way to slice to an empty array

### ISSUE THREAD

**Issue by Giwayume** [godotengine/godot#53495]
### Godot version

3.4 stable

### System information

Windows 7 64 bit

### Issue description

Unexpected behavior when using Array.slice()

Maybe this is because the docs say end is "inclusive", but if it's supposed to work this way that's an extremely poor design decision. In many cases I expect to be able to slice and return an empty array subset.

### Steps to reproduce

GDScript:

```
print_debug("[1,2,3].slice(0,0) ", [1,2,3].slice(0,0) )
print_debug("[1,2,3].slice(0,1) ", [1,2,3].slice(0,1) )
print_debug("[1,2,3].slice(0,-1) ", [1,2,3].slice(0,-1) )
```

EXPECTED output:

```
[1,2,3].slice(0,0) []
[1,2,3].slice(0,1) [1]
[1,2,3].slice(0,-1) [1, 2]
```

ACTUAL output:

```
[1,2,3].slice(0,0) [1]
[1,2,3].slice(0,1) [1, 2]
[1,2,3].slice(0,-1) [1, 2, 3]
```

Compare to Python:

```
import numpy as np

arr = np.array([1, 2, 3])

print(arr[0:0])
print(arr[0:1])
print(arr[0:-1])
```

```
[]
[1]
[1, 2]
```

Compare to Javascript:

```
[1,2,3].slice(0,0)
[1,2,3].slice(0,1)
[1,2,3].slice(0,-1)
```

```
[]
[1]
[1, 2]
```

**Comment by TechnoPorg** [comment]
Now that #35901 has been merged, is this still an issue?

**Comment by akien-mga** [comment]
The end is now non-inclusive in #35901 so this is indeed fixed.

There's still a difference with the behavior of negative indices though, which would be worth tracking in a separate issue:
```
	print_debug("[1,2,3].slice(0,0) ", [1,2,3].slice(0,0) )
	print_debug("[1,2,3].slice(0,1) ", [1,2,3].slice(0,1) )
	print_debug("[1,2,3].slice(0,-1) ", [1,2,3].slice(0,-1) )
```
