### ISSUE TITLE
Material Properties Editor - Detail Mix can't display values >1

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#535]
I can use values bigger than 1 for Detail Mix, which is very useful, but if I do property is till displayed as 1 even if it isn't.

Minor bug but annoying when you want to tweak it and you have to remember all values hehe :)

**Comment by akien-mga** [comment]
Is this issue still valid in the current master branch?

**Comment by akien-mga** [comment]
I can't reproduce that, if I set a detail mix of more than 1, it is indeed changed back to 1, but it is _not_ more than one in the XML scene properties when opened in a text editor. So I guess detail mix is indeed meant to stay between 0 and 1.
