### ISSUE TITLE
Unfocusable embedded windows aren't used for input handling

### ISSUE THREAD

**Issue by TechnoPorg** [godotengine/godot#53501]
### Godot version

4.0.dev (77721b35)

### System information

Windows 10

### Issue description

With the way that input is currently handled in embedded windows, it's forwarded to the focused subwindow. Unfortunately, this also happens when interacting with unfocusable windows. I've found 2 symptoms of this:

- After clicking on an unfocusable subwindow when previously no subwindow was focused, `Viewport::_sub_windows_forward_input` begins spamming an error and won't stop until another subwindow is brought into focus. Always occurs if all subwindows are unfocusable.
- When there is a focused subwindow but you interact with an unfocusable subwindow, the input gets incorrectly sent to the focused subwindow. For example, dragging an unfocusable subwindow is impossible because the focused one moves instead.

### Steps to reproduce

Create a project and enable the setting `Display->Window->Subwindows->Embed Subwindows`. Add a window to the scene and set its `unfocusable` property to `true`. If there are no focusable subwindows, clicking on it will immediately start an error spam. If there is a focusable subwindow, click on it to bring it into focus. Then, try dragging the titlebar of the unfocusable window. The focused one will be the one that moves, relative to the mouse.

### Minimal reproduction project

[UnfocusableWindowBugs.zip](https://github.com/godotengine/godot/files/7297637/UnfocusableWindowBugs.zip)

**Comment by YuriSizov** [comment]
cc @Sauermann

**Comment by mageowl** [comment]
I think this bug exists even when windows aren't embedded, however it is fine on the main window.
