### ISSUE TITLE
Trying to run GDScript file with 100000 lines take more than 10 minutes

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#53506]
### Godot version

3.4.beta.custom_build. df69945f1

### System information

Ubuntu 21.04 - Nvidia GTX 970, Gnome shell 3.38 X11

### Issue description

Trying to run GDScript file which contains 100000 lines with just variable creation and function execution, took more that 10 minutes(I need to close project, because profiler log took almost all my disk space)

Looks that this is caused mostly by using List [] operator which is very slow in iterating elements

![Screenshot from 2021-10-07 07-10-02](https://user-images.githubusercontent.com/41945903/136325695-41bfec29-c7a4-4933-ab42-a528a503e158.png)

### Steps to reproduce

Just try to run project

### Minimal reproduction project

[FF.zip](https://github.com/godotengine/godot/files/7298935/FF.zip)

**Comment by akien-mga** [comment]
Fixed by #53507.
