### ISSUE TITLE
force_drag() is not working

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#5351]
**Godot version:**
2.1

**Issue description** (what happened, and what was expected):
force_drag() method from Control is not working can't drop data on Control
Here is sample project.

**Link to minimal example project** :

[Force_drag_test.zip](https://github.com/godotengine/godot/files/326623/Force_drag_test.zip)

**Comment by reduz** [comment]
closed via db9335f4c1247d950b4858b56d653975bb3058ff

**Comment by n-pigeon** [comment]
Thanks xD
