### ISSUE TITLE
Vulkan: Rendering glitch: random squares in image (Linux, AMDGPU)

### ISSUE THREAD

**Issue by davidak** [godotengine/godot#53528]
### Godot version

4.0.dev.20211004.official.2e8cba0bd

### System information

NixOS 21.11.git.37cc619178fM, AMD RX 480, amdgpu, Vulkan

### Issue description

https://youtu.be/NJ2FDqf3T4E?t=61

Downstream issue: https://git.gieszer.link/unfa/liblast/issues/88

### Steps to reproduce

1. Download project
2. run `./Liblast\ Linux`

### Minimal reproduction project

File bigger than 25MB.

https://github.com/davidak/test/releases/download/0.1.0/Liblast.0.1.0.1-pre-alpha.zip

**Comment by Klowner** [comment]
Hiding all the reflection probes in the Map scene makes the decal block problem go away for me, might be a spot to keep digging.

**Comment by isaacwilliams** [comment]
I'm getting this same issue on M1 MacOS, 4.0.alpha.14. Noticed the issue on earlier builds too though.

https://user-images.githubusercontent.com/819616/187313106-acabc0e2-27b8-4f02-a926-4db2e7f9857c.mp4

Minimal demo attached:

[black-square-jitter-minimal-demo.zip](https://github.com/godotengine/godot/files/9448328/black-square-jitter-minimal-demo.zip)

**Comment by isaacwilliams** [comment]
Tried to bisect but builds are broken on MacOS before I can find a "good" commit.

**Comment by Calinou** [comment]
The rendering bug on macOS M1 is a separate issue: https://github.com/godotengine/godot/issues/61108

**Comment by isaacwilliams** [comment]
Thanks @Calinou — totally missed that one
