### ISSUE TITLE
Vulkan: soft shadows appear grainy, even on "Ultra" quality setting

### ISSUE THREAD

**Issue by unfa** [godotengine/godot#53534]
### Godot version

4.0-dev.20211004/

### System information

Manjaro Linux KDE, Radeon RX480 (amdgpu driver)

### Issue description

"Ultra":
![image](https://user-images.githubusercontent.com/491704/136412797-ba98189b-fabb-48e7-a4be-cbdf09c6bdef.png)

"Low":
![image](https://user-images.githubusercontent.com/491704/136412962-a7d45a19-b74e-4899-a81e-cb7635db0f2d.png)

Here's how the shadow settings look in this project:
![image](https://user-images.githubusercontent.com/491704/136413337-43bfc2f6-c03e-458c-ab5b-4c6797f12a6c.png)

### Steps to reproduce

1. Create a scene with soft shadows
2. Observe

*Bugsquad edit (keywords for easier searching): noisy, noise*

**Comment by Calinou** [comment]
> Would be good to have an alternative that doesn't use a dithering pattern for more simplistic looking games.

You can turn off soft shadow filtering entirely, which disables the dithering pattern.

**Comment by catboy-catfish** [comment]
> > Would be good to have an alternative that doesn't use a dithering pattern for more simplistic looking games.
> 
> You can turn off soft shadow filtering entirely in the project settings, which disables the dithering pattern. It won't look great, but it'll be fast.
> 
> An alternative is to do the opposite – if you push the shadow filtering quality all the way up, the dithering pattern should be less noticeable. When using the highest possible shadow filtering quality, you should be able to halve your light Shadow Blur values while getting the same amount of shadow blurriness.
> 
> If you really want to disable the dithering pattern but keep soft shadows, perform the following change in
> 
> https://github.com/godotengine/godot/blob/c5f4bf207742c5e584900ef13dba7e44a454280b/servers/rendering/renderer_rd/shaders/scene_forward_lights_inc.glsl#L292-L298
> 
> ```diff
> diff --git a/servers/rendering/renderer_rd/shaders/scene_forward_lights_inc.glsl b/servers/rendering/renderer_rd/shaders/scene_forward_lights_inc.glsl
> index 4d466342f8..51d26a6437 100644
> --- a/servers/rendering/renderer_rd/shaders/scene_forward_lights_inc.glsl
> +++ b/servers/rendering/renderer_rd/shaders/scene_forward_lights_inc.glsl
> @@ -292,8 +292,7 @@ void light_compute(vec3 N, vec3 L, vec3 V, float A, vec3 light_color, float atte
>  // Interleaved Gradient Noise
>  // https://www.iryoku.com/next-generation-post-processing-in-call-of-duty-advanced-warfare
>  float quick_hash(vec2 pos) {
> -	const vec3 magic = vec3(0.06711056f, 0.00583715f, 52.9829189f);
> -	return fract(magic.z * fract(dot(pos, magic.xy)));
> +	return 0.5;
>  }
>  
>  float sample_directional_pcf_shadow(texture2D shadow, vec2 shadow_pixel_size, vec4 coord) {
> ```
> 
> Then recompile Godot:
> 
> ![image](https://user-images.githubusercontent.com/180032/137731352-c8370dc4-8bb2-4567-aea3-e9d3b2ea032d.png)

Are there any benefits to using quick_hash for the shadows instead of just giving them a value of 0.5 like this?

**Comment by Calinou** [comment]
> Are there any benefits to using quick_hash for the shadows instead of just giving them a value of 0.5 like this?

Yes, dithering helps make the shadow aliasing (i.e. banding patterns in the shadowmap texture) less noticeable.

**Comment by catboy-catfish** [comment]
> Yes, dithering helps make the shadow aliasing (i.e. banding patterns in the shadowmap texture) less noticeable.
Yeah, actually, I had to learn this the hard way before you commented. I thought it would be better because of no dithering, but without it there's stair-stepping artifacts on the shadows (because they're not being blurred in any way).
