### ISSUE TITLE
2D Batching is extremely slow on Android (GLES3)

### ISSUE THREAD

**Issue by Poobslag** [godotengine/godot#53537]
### Godot version

v3.3.4.stable.official [faf3f883d]

### System information

Galaxy Note9 REV1.1, Android 10, GLES3

### Issue description

2D batching causes a severe performance degradation on Android. With 2D batching disabled, the attached demo can render 1,920 sprite nodes at 60 FPS. With 2D batching enabled, it runs at 3 FPS. This is on my Samsung Galaxy Note9 (SM-N960U) running Android 10.

2D batching enabled:

![Screenshot_20211007-112230_polygon2d_performance](https://user-images.githubusercontent.com/5902413/136416312-3d7b3ec4-2a41-43ca-90a6-4981580555c3.jpg)

2D batching disabled:
![Screenshot_20211007-112131_polygon2d_performance](https://user-images.githubusercontent.com/5902413/136416325-6c82c75a-60d2-48ef-9460-ce9172768ca8.jpg)

### Steps to reproduce

1. Deploy the attached demo on a Samsung Galaxy Note9 or similar android device. (You will need to configure an export preset and a debug keystore.) 2D batching is enabled by default.
2. Click the "x2" button to increase the number of sprite nodes from 480 to 1920. With 2D batching enabled, the FPS drops to 3.
3. Edit the Project Settings, disabling 2D Batching (`Project` -> `Project Settings`, `Rendering` -> `Batching` -> `Use Batching = Off`)
4. Deploy the demo a second time. Click the "x2" button to increase the number of sprite nodes. The FPS stays at 60.

### Minimal reproduction project

[polygon2d_performance.zip](https://github.com/godotengine/godot/files/7304963/polygon2d_performance.zip)

**Comment by Poobslag** [comment]
With 4 lights visible, the demo runs at 3 FPS.
With 1 light visible, the demo runs at 7 FPS.
With 0 lights visible, the demo runs at 60 FPS.

The lights are definitely influencing the degradation.

**Comment by lawnjelly** [comment]
Also a couple of other options:
1) If you can make your lights smaller, it may be able to run faster (even possibly with more lights but smaller).
2) You may be able to take an approach like this with lights:

https://www.youtube.com/watch?v=P6qzGofbNyo

Although it will probably be difficult to get it looking as good (and won't work if you are e.g. using normal maps), this will run shedloads faster in your situation. The main problem I seem to remember was the lack of bit depth when I tried it.

**Comment by lawnjelly** [comment]
Closing as lighting performance is unlikely to be fixed, being a limitation of the 2D rendering paradigm.
