### ISSUE TITLE
DirAccess: Folder creation fails in "Save As.." on Linux

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#5353]
**Operating system or device - Godot version:**
Mageia 6, Linux 64-bit - Current master HEAD (0266d75)

**Issue description** (what happened, and what was expected):
Creating new folders in the "Save As.." EditorFileDialog does not work. It just returns a popup saying "Alert! Could not create folder.".
I checked and I have proper write permissions in the concerned folders. Looks like a regression from recent DirAccess changes.

**Steps to reproduce:**
1. Open the "Save As.." dialog
2. Press "Create Folder", enter a name and press "OK"

**Comment by martfors** [comment]
A duplicate of https://github.com/godotengine/godot/issues/5323 i think?

**Comment by akien-mga** [comment]
Indeed.
