### ISSUE TITLE
`Window.popup_centered_ratio` can take several GB of memory and freeze OS

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#53566]
### Godot version

4.0.dev.custom_build. 87de2e7c4

### System information

Ubuntu 21.04 - Nvidia GTX 970, Gnome shell 3.38 X11

### Issue description

Executing 
```
func _process(delta) -> void:
	for i in get_children():
		i.queue_free()
######################################## Window ########################################
	var temp_variable5 = Window.new()
	add_child(temp_variable5)
	temp_variable5.popup_centered_ratio(27.2238194942474)
	OS.delay_msec(15000)
```
can take several GB of Ram(12 in my case),
Not sure if this is a bug, but maybe this function should forbid invalid arguments

### Steps to reproduce

Above

**Comment by KoBeWi** [comment]
Tested on Windows 10, the window is invalid, but doesn't take RAM.
