### ISSUE TITLE
Game freezes every 4 secounds when auto_switch_to_remote_scene_tree is on

### ISSUE THREAD

**Issue by BenHerbst** [godotengine/godot#53593]
### Godot version

3.3.4.stable

### System information

Windows 10, GLES2, Nvidia Quadro P400

### Issue description

When I turn auto_switch_to_remote_scene_tree on, my game freezes every 4 secounds after start. When I turn off, there are no freezes.

### Steps to reproduce

Activate auto_switch_to_remote_scene_tree and start a game.

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/13219.
