### ISSUE TITLE
RigidBody2D is passing through tilemap

### ISSUE THREAD

**Issue by jersten** [godotengine/godot#5359]
2.0.3 steam release (on Linux)

How to reproduce:
1. The tilemap was created like so: Sprite > StaticBody2D > with CollisionPolygon2D
2. I exported it as `basic.xml`
3. I then imported into a new scene with `TileMap`; created a `RigidBody2D` sprite, built a basic map and put the `RigidBody2D`, enabled collision bounds with debug and started the scene. The `RigidBody2D` then passed through the `TileMap`; there were no collision lines for the created TileMap. Kinematic collision was enabled on the TileMap. In the below tutorial (see XML part of it) I did not see any collision data in the XML file.

I was following [this tutorial](http://www.gamefromscratch.com/post/2015/04/28/Godot-Engine-Tutorial-Part-8-Tilemaps.aspx)

**Comment by vnen** [comment]
If you could provide a simple test project would be helpful.

**Comment by jersten** [comment]
You can close this.

I did not realize I had to set the Shape property of the tiles.

For reference and anyone else who may run into this I've included the project test.zip.
[test.zip](https://github.com/godotengine/godot/files/328465/test.zip)

**Comment by vnen** [comment]
Okay, thanks for showing how you solved it.
