### ISSUE TITLE
Links in editor help have bigger clickable area than they should

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#53599]
### Godot version

df37675

### System information

W10

### Issue description

![k2zv1k2ntO](https://user-images.githubusercontent.com/2223172/136663659-eb728582-32a4-4093-a8b9-5d597931dd9e.gif)
Notice how cursor changes to hand on blank space.

### Steps to reproduce

1. Open Vector2 in editor help
2. Inspect the tutorial links

**Comment by Krish2882005** [comment]
Sure
