### ISSUE TITLE
Mouse does not update the event MOUSE_MOTION while it's within the window's coordinates.

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#5361]
**Operating system or device - Godot version:**
Windows 10 64bit - Godot 2.1 alpha (June 21st)

**Issue description** (what happened, and what was expected):
The input event MOUSE_MOTION does not update while the mouse is within the screen coordinates, it only updates while it's outside the coordinates (which can be achieved with MOUSE_MODE_CAPTURED). For example if the window is 800x600 the MOUSE_MOTION will not start updating until its x position is greater than 800 or less than 0, or its y position is greater than 600 or less than 0.

Some more info: This problem wasn't happening from a build on June 16th. So the problem started somewhere between the 16th and 21st.

**Link to minimal example project** (optional but very welcome):
In the Window Management demo, click on the "Mouse Grab" button and try to move the mouse, it wont start moving until you've moved the mouse far enough away.

**Comment by khairul169** [comment]
Bump.. :(
