### ISSUE TITLE
Can't set ViewportTexture as MaterialOverride in imported GLTF

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot#53611]
### Godot version

3.3.3 stable

### System information

Windows 7 64-bit

### Issue description

I have a viewportTexture that I've set-up with a child camera (I've placed it above the gltf in the hierarchy to avoid the warning bug)
![image](https://user-images.githubusercontent.com/16231628/136671585-71a03727-377a-4dbd-9d26-cd98d928d855.png)

I get a reference to the meshinstance in a script on my gltf (carinterior) and I'm trying to use MaterialOverride to change the meshinstance material to a viewport texture. The problem is:

- the meshinstance has to be local to scene, which needs to be set inside the gltf
- the viewporttexture needs to be created locally on the meshinstance and not as a resource
- whatever I try it just appears black and doesn't display at all

This is all inside a separate saved scene for the car, it's then included in the level scene which further complicates things and sometimes the texture shows in the editor for the car scene but not in the level scene.

I'm honestly not even sure if ViewportTextures can be added to anything that isn't made local to scene, there's just too many parts of the chain that need to be local. The issue is that gltf objects should be able to stay at their own resource in case the model or materials need changing and updating, and making any of it local is completely destructive.

### Steps to reproduce

Setup a viewportTexture with a child camera local to the object scene, above the mesh you wish to replace. Add a script that gets the mesh in the gltf you wish to replace and use materialoverride to replace it with a reference to the viewporttexture.

### Minimal reproduction project
[viewporttests.zip](https://github.com/godotengine/godot/files/7317887/viewporttests.zip)

**Comment by Calinou** [comment]
@elvisish Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by elvisish** [comment]
> @elvisish Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.
> 
> > I'm honestly not even sure if ViewportTextures can be added to anything that isn't made local to scene, there's just too many parts of the chain that need to be local. The issue is that gltf objects should be able to stay at their own resource in case the model or materials need changing and updating, and making any of it local is completely destructive.
> 
> The local requirement is likely here for a reason – I doubt it can be removed slightly_smiling_face

I've uploaded a reproduction and after trying all day to get this working, I actually managed to rubberduck debug it by actually producing this minimal project. I believe the trick is to make every part of it local, in this case to the parent spatial that contains the gltf. It seems to work, is this the recommended approach to doing this?
