### ISSUE TITLE
Glitchy scrolling on mobile; ScrollContainer in parent and in child

### ISSUE THREAD

**Issue by shafnaz** [godotengine/godot#53619]
### Godot version

3.3.4

### System information

Android J7 Prime Android 6.0.1

### Issue description

Hi guys,

There is a glitchy movement when you have a ScrollContainer parent and a child ScrollContainer.
The parent scrolls vertical, and the child scrolls horizontally.
Running on the computer shows no problems, but on mobile, it jumps a lot. Check out the .tscn attached.

### Steps to reproduce

Load the .tscn which contains the setup.
Deploy it on your android phone.

### Minimal reproduction project

[scroll_test.zip](https://github.com/godotengine/godot/files/7316832/scroll_test.zip)

**Comment by FurDice** [comment]
I experience this same issue but with different node structure.
It only happens on real android device.
Tested on Pixel 3a, Pixel 3a XL, GalaxyNote 8
