### ISSUE TITLE
Directory.get_current_dir() hangs when run windows exported binary

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#5363]
**Operating system or device - Godot version:**
Windows 10 - 64bit

**Issue description** (what happened, and what was expected):
Game does not respond when using `Directory.get_current_dir()`
It's fine when running on editor

**Steps to reproduce:**

``` gdscript
func _ready():
    var dir = Directory.new()
    var err = dir.open("res://temp/")
    print("dir open result = ", err)
    print("current path = ", dir.get_current_dir())
```

create `temp` directory under `res://`.
export to windows binary and run.

**Link to minimal example project** (optional but very welcome):

**Comment by ArcOfDream** [comment]
Can confirm this also happens under Linux. Tested with Linux Mint 18 Cinnamon, 64-bit.

**Comment by bojidar-bg** [comment]
Can't you both at least include godot version too?

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.
