### ISSUE TITLE
Inline IME input not working on Linux and Windows

### ISSUE THREAD

**Issue by voylin** [godotengine/godot#53658]
### Godot version

3.3.4.stable.Arch_linux

### System information

Arch (Linux-lts 5.10.71-1)

### Issue description

In Chromium, Notepadqq, Kdenlive, ... and so on, everytime when I start typing in Japanese, there is inline input support so what I type directly appears. But this is not possible inside of Godot. As someone who makes Japanese games and Japanese learning games, this is kind of an annoying thing. 
This is what I mean, instead of my text directly appearing, this happens instead.
![IMG_20211011_083849](https://user-images.githubusercontent.com/56970759/136716795-9e948013-da97-4a3f-accd-3bcd87a202f6.jpg)

 
I don't have windows so I can't verify if this is a linux only problem.

### Steps to reproduce

Install any linux distro, install any Japanese input tool of your choice (I use fcitx5-mozc) and try to type inside of Godot.

**Comment by DeeJayLSP** [comment]
In Godot, text will only appear after you press Enter.
This also happens in 4.0.

**Comment by bruvzg** [comment]
Currently inline IME input is implemented only on macOS.

**Comment by segfault-god** [comment]
![Desktop Screenshot 2021 12 24 - 14 12 23 44](https://user-images.githubusercontent.com/11525934/147319406-ad542bba-0374-4fe4-b350-7e38f8fdfe8e.png)
I'm implementing this on Windows because my game needs it. I have never used imm32 and have no experience modifying the Godot, but I hope to complete it before Godot4 is released🥺

**Comment by voylin** [comment]
> ![Desktop Screenshot 2021 12 24 - 14 12 23 44](https://user-images.githubusercontent.com/11525934/147319406-ad542bba-0374-4fe4-b350-7e38f8fdfe8e.png) I'm implementing this on Windows because my game needs it. I have never used imm32 and have no experience modifying the Godot, but I hope to complete it before Godot4 is releasedpleading_face

How is your progress coming along on this? I've been thinking of giving this a try to fix, but for linux as I don't have windows. The only thing is that I have no idea where to start. Any advice of which scripts to look at which would require change?

**Comment by segfault-god** [comment]
@voylin 
I was going to start working on it soon, but I have been a bit busy and haven't made any progress.

Here is my test code: https://github.com/segfault-god/godot/commit/1aa26dd7b3b7e08ba40f3f71ff4864bddc026c07

**Comment by raulsntos** [comment]
Implemented by https://github.com/godotengine/godot/pull/70052
