### ISSUE TITLE
RubberHose: New node for animating

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#5365]
Cut out animations in Godot are really good and easy to do. 
BUT if you want to bend a knee or an arm for example then it will look like this:
![2](https://cloud.githubusercontent.com/assets/12517768/16285890/23c1dc58-38d9-11e6-90da-8d1e30887c41.png)

Here comes my feature request. Add an object/node which is bendable and whose style you can change (color, border, texture). For After Effects there is a plugin called RubberHose, and it does everything for the problem. 

**Watch this:**
https://www.youtube.com/watch?v=jn740nc0KUU

![3](https://cloud.githubusercontent.com/assets/12517768/16286127/b45ca206-38da-11e6-93a7-c38e0987a15f.png)

![5](https://cloud.githubusercontent.com/assets/12517768/16286238/7d13de62-38db-11e6-9486-005038b228d0.png)

**Comment by Hinsbart** [comment]
I think deformable sprite meshes are planned for 3.0 :)
See #2914

**Comment by reduz** [comment]
indeed, planned for 3.0

**Comment by YugoCode** [comment]
Will 3.0 immediately follow after 2.1? I mean when can we expect that you start with 2d mesh deformation? I know it is "when you add the new renderer" but when is it? Directly after you finish 2.1?

I need it sooo much for my games :((( 
And I cannot afford Creature(99$-170$). Is there any free way I can achieve this in my godot games?

Thank you guys :)

**Comment by reduz** [comment]
yes it will come after 2.1

**Comment by mohaalak** [comment]
@YugoCode  checkout this link:
https://www.youtube.com/watch?v=WfqVdVSfNQo

@ndee85 made an awesome plugin for blender for animation2d that you can bring it on godot , I think it will help you out.

**Comment by YugoCode** [comment]
@mohaalak Thank you, I know it and I love it. Also 2D mesh deformation is working, but Andreas said 2d mesh deformation will not work in godot because it simply does not support it :(

**Comment by reduz** [comment]
again kicking to 3.1, 3D had priority in 3.0 and we ran out of time

**Comment by akien-mga** [comment]
2D mesh deformation is now implemented: https://godotengine.org/article/godot-gets-2d-skeletal-deform
