### ISSUE TITLE
Inconsistent theme style across the scene tree, file tree, and project settings tree

### ISSUE THREAD

**Issue by floppyhammer** [godotengine/godot#53663]
### Godot version

v4.0.dev.custom_build [09b0293fa]

### System information

Windows 11, Vulkan Clustered

### Issue description

We have borders for tree item in the scene tree and file tree but not in the project settings tree.

![image](https://user-images.githubusercontent.com/28705694/136740968-b8114775-fcdf-4760-95e7-9d68d6433222.png)

### Steps to reproduce

Check out how tree items look in the scene tree, file tree, and project settings tree.

**Comment by YuriSizov** [comment]
> Should probably close this.

Very well!
