### ISSUE TITLE
remote debug on android does not work straight away - it glitches and requires action to make it work.

### ISSUE THREAD

**Issue by avril-gh** [godotengine/godot#5368]
**Operating system or device - Godot version:**
Windows 7, Godot 2.1 alpha, android 4.4.2 arm

**Issue description** (what happened, and what was expected):
Even tho you may deploy and run project over wifi adb on remote android device, when enabling option "deploy with remote debug" - The debug does not work. No Output from runing application is received.
This is glitch and can be easly fixed with work around trick, but the trick is not obvious, especially to someone who 100 times browsed all options to make sure everything is properly set.
(see "steps to reproduce" to find out where is glitch and what trick to do to make it work - or rather what should be fixed.)

**Steps to reproduce:**
1 - close godot editor (this step is REQUIRED)
2 - open godot editor (this step is REQUIRED)
3 - open or create any project which use _print("test")_, so you can see... that you will not see it.
4 - start your wifi adb - and then you will see in editor green android icon apear.
5 - check option "deploy with remote debug" (located in menu of last icon in run options tool tab)
6 - click green android icon and your project will run on connected android device.
7 - expect to see your _print("test")_ in editors output window - but no... you will not see it because it not works.
8 - go to settings -> editor settings -> network, and check if the IP is your WIFI where android device is connected. Even if its right IP (!) change it to seomething else and then change back to your WIFI,
9 - now it works, no matter its the same IP that didnt worked while a go - it needed to be shaked up.
10 - It will work as long as you not close godot - next time you will have again "shake" network setting.

**Comment by volzhs** [comment]
I have same problem.
it happens if PC has several IP, like vmware installed.

**Comment by avril-gh** [comment]
> it happens if PC has several IP, like vmware installed.

yes it reveals itself if computer have more than one IP's (network interfaces)

after more researchings, it seems that problem is basicaly:
**settings -> editor settings -> network -> debug_host is NOT SAVED after change**.

so if you have 3 IPs for example 192.168.1.100, 192.168.1.101, 192.168.1.102 and active is 192.168.1.102.
- you go to debug_host setting, change it to 192.168.1.100, (now debug works as long as editor is opened)
- then close editor and open it again (debug does not work)
- When you go to debug_host setting you see its again 192.168.1.102 (so the change was not saved)
