### ISSUE TITLE
Move Script editor bookmarks to a separate gutter

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#53685]
### Godot version

5edfdc53ebb97616a6a72031b2e28ec7865d6ab8

### System information

Windows 10

### Issue description

This might be subjective but why its placed over the debugger icon?:

![image](https://user-images.githubusercontent.com/3036176/136850967-85dbead7-7309-4679-a13b-70b72a49b8cb.png)

instead, (I think) it is more logically be placed like:

![image](https://user-images.githubusercontent.com/3036176/136851220-433eacb2-81e0-4473-8de2-2c75d6076a2a.png)

### Steps to reproduce

Create a bookmark.

**Comment by Paulb23** [comment]
This is not a bug, it draws over the breakpoint gutter to save on horizontal space. 

In the second image it's drawn over the `connection` gutter, so there would have to be a other gutter aside it for that.

**Comment by MewPurPur** [comment]
My recent discussion with Paulb pretty much confirmed that this isn't going to happen. We could space them out, but I'm not sure it would look better, and the icons in this main gutter are rarely on the same lines anyway.

**Comment by Chaosus** [comment]
Since the thread is created in godot-proposals I'll close this topic.
