### ISSUE TITLE
Gdscript addition error: -1+4=4616189618054758400

### ISSUE THREAD

**Issue by chmjwl** [godotengine/godot#53700]
### Godot version

v4.0.dev.calinou [2a28df82d]

### System information

Windows 10, Vulkan

### Issue description

I have encountered a very odd error when adding to numbers in gdscript, which reminds me of integer overflow errors. Basically, -1+4=4616189618054758400

This code here
```
	print("pos: ",pos)
	print("zmax: ",zmax)
	print("pos.z+zmax: ",(pos.z+zmax))
```

Produces this output here
```
pos: (-1, 0, -1)
zmax: 4
pos.z+zmax: 4616189618054758400
```

I ran typeof on all variables and got a 3.

### Steps to reproduce

I am unable to reproduce this issue in a new project.

**Comment by chmjwl** [comment]
I have managed to make a minimal reproduction project by stripping down my original project to a minimum. Is there a way to upload it here or should I send it to you via some other method?

**Comment by akien-mga** [comment]
You can upload by drag and dropping a ZIP in the comment field.
