### ISSUE TITLE
New input map editor no longer displays icons for inputs and device text

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#53708]
### Godot version

4.0.dev (94ce83bef)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 470.57.02)

### Issue description

This is how input actions currently display in `master`:

![image](https://user-images.githubusercontent.com/180032/136939976-23ff64fb-c390-4241-8ed1-c4c3ae4bb50d.png)

In contrast, this is how the same configuration looks like in `3.x`:

![image](https://user-images.githubusercontent.com/180032/136940091-2d601d15-4f74-4c6a-9423-4eaad82373f6.png)

It's more informative (as it displays the device IDs for mouse buttons and joypad buttons) and easier to visually grep thanks to the icons.

### Steps to reproduce

- Create input actions in the input map editor.
- Look at the presentation of those input actions in the editor.

### Minimal reproduction project

`master`: [4.zip](https://github.com/godotengine/godot/files/7329101/4.zip)
`3.x` **(not compatible with 3.3.4)**: [3.zip](https://github.com/godotengine/godot/files/7329100/3.zip)

**Comment by EricEzaM** [comment]
Still open - multi-part issue. FYI @Calinou I am working on the 2nd part and should have a PR shortly.

**Comment by EricEzaM** [comment]
> After further testing, it seems that the `device` isn't stored properly in `master`. No matter the value I choose in the dropdown, the `device` stored in `project.godot` is always 0.
> 
> I noticed this while working on a PR to use "All Devices" as a default option, since it works more reliably for singleplayer games [and touchscreen input](https://godotengine.org/qa/48264/touchscreen-input-doesnt-work-on-android).

Looks like I never connected up the device dropdown to actually do anything... oops! Should be all good with my PR now.
