### ISSUE TITLE
AudioStreamPlayer3D "playing" when enabled crashes the editor

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#53718]
### Godot version

v4.0.dev.custom_build [2a28df82d]

### System information

manjaro 21, AMD Radeon r7 200 series, Vulkan, 8GB Memory

### Issue description

When you enable "Playing" in the editor for it, the editor crashes

PS: Works fine in-game

### Steps to reproduce

* Create an AudioStreamPlayer3D node
* Attach an audio
* click playing
* editor should crash

### Minimal reproduction project

N/a

**Comment by CakHuri** [comment]
I can reproduce this on f9aec342dcd51d65c5970dd395e3c7a66cac446c . It crashed and then the godot editor exited.

My PR here hopefully solve this issue.

**Comment by spindlebink** [comment]
Is there any update on this? Being able to hear audio in the editor is pretty important.

**Comment by Calinou** [comment]
> Is there any update on this? Being able to hear audio in the editor is pretty important.

See https://github.com/godotengine/godot/pull/53733 which resolves this, but it needs to be reworked before it can be merged.

**Comment by spindlebink** [comment]
Could [this](https://github.com/godotengine/godot/issues/52853#issuecomment-930350594) be related? I notice both pertain to invalid accesses of camera nodes. My game is crashing when the scene is freed unless I either take the `AudioStreamPlayer3D`s out or convert them to `AudioStreamPlayer`s (no 3D).

**Comment by akien-mga** [comment]
Should have been fixed by #55544.
