### ISSUE TITLE
Opening android app twice causes a freeze (configured as Launcher/Home app)

### ISSUE THREAD

**Issue by likeich** [godotengine/godot#53716]
### Godot version

3.3.4 stable

### System information

Android 11 GLES 2

### Issue description

Opening an app twice in android is causing a freeze that did not happen in Godot 3.3.3. My app is an android launcher that allows users to click a button to go to the settings menu to set their default launcher. Clicking this button and selecting my app (World Launcher) in 3.3.3 would correctly restart the app as the default launcher instead of as a normal app. In 3.3.4 this causes a freeze and a black screen as shown below:

https://user-images.githubusercontent.com/57882701/136958920-36b28b9e-4292-46bd-8616-adba6acc4985.mp4

The app is not crashing, so I do not have a stack trace, but here are the logcat errors when this happens:

![Screenshot from 2021-10-12 08-53-47](https://user-images.githubusercontent.com/57882701/136960012-b7cc68d5-7336-448d-8031-01a977e0722a.png)

### Steps to reproduce

I don't think this is reproducible without using android custom builds. First, install the custom build template, then replace the intent filter with 
`<intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
                <category android:name="android.intent.category.HOME" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>`
to allow setting the app as the default launcher.

Export that app then leave the app running in the background and go to your settings and set it as the default launcher and the freeze will occur when android tries to start the app as the default launcher.

### Minimal reproduction project

It looks like I can't upload an MRP because the custom build template makes it too large. Following the steps above should hopefully suffice.

Edit: I created a repo with the MRP [Here](https://github.com/likeich/AndroidCrashMRP)

**Comment by Calinou** [comment]
> It looks like I can't upload an MRP because the custom build template makes it too large. Following the steps above should hopefully suffice.

You can create a GitHub repository that contains the project.

**Comment by likeich** [comment]
Akien was right. From my testing, 3.3.2 and 3.3.3 all have this issue as well.

Confirmed to still be an issue on Godot 3.4 RC 2.
Logcat:
![Screenshot from 2021-10-30 11-17-26](https://user-images.githubusercontent.com/57882701/139540980-0f329b9a-f310-47f4-8d9a-3851707f6f1a.png)

@m4gr3d where would I put logging statements to track that?

**Comment by akien-mga** [comment]
Is this still reproducible in 3.5 beta 5 or later?

**Comment by likeich** [comment]
@akien-mga yes, I just reproduced it on 3.5 beta 5.


![Screenshot from 2022-05-14 17-52-19](https://user-images.githubusercontent.com/57882701/168456440-b555abbd-0ab2-42d2-97b1-990a4b912cce.png)

**Comment by m4gr3d** [comment]
@likeich PR #61332 should address the issue you're seeing. Can you give it a try and confirm.

**Comment by likeich** [comment]
@m4gr3d It looks like it's working now. Thanks!
