### ISSUE TITLE
Blogpost gramatical error

### ISSUE THREAD

**Issue by iqualfragile** [godotengine/godot#5372]
**Issue description** (what happened, and what was expected):
http://godotengine.org/article/mir-godot-habla-dein-language-desormais
it says "dein" instead of "deine" here.
the full sentence would be

Hello world, Godot speaks "your language" 'from now on'!
Hallo Welt, Godot spricht 'von jetzt an' "deine Sprache"!

i reordered the last part, because the other way around it really sounds awkward in german.

**Comment by bojidar-bg** [comment]
@akien-mga ping ;)

**Comment by akien-mga** [comment]
Lol. Well I took it as `das Language`, but I guess I can do the agreement with `die Sprache` if it's deemed better.

**Comment by akien-mga** [comment]
Fixed.
