### ISSUE TITLE
Creating XRCamera3D or Camera3D creates memory leak

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#53725]
### Godot version

4.0.dev.custom_build. 2a28df82d

### System information

Ubuntu 21.04 - Nvidia GTX 970, Gnome shell 3.38 X11

### Issue description

```
add_child(XRCamera3D.new())
```

shows this memory leak
```
WARNING: 1 RID of type "UniformBuffer" was leaked.
     at: _free_rids (drivers/vulkan/rendering_device_vulkan.cpp:8960)
```

### Steps to reproduce

Above

**Comment by saki7** [comment]
I can confirm that `Camera3D` is also affected.

**Comment by qarmin** [comment]
Fixed in master branch
