### ISSUE TITLE
Created `ImageTexture3D` don't delete itself and leaks memory

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#53721]
### Godot version

4.0.dev.custom_build. 2a28df82d

### System information

Ubuntu 21.04 - Nvidia GTX 970, Gnome shell 3.38 X11

### Issue description

Executing
```
ImageTexture3D.new().create(27,-35,40,45,false,[])
```

creates this memory leak
```
ERROR: 1 RID allocations of type 'N17RendererStorageRD7TextureE' were leaked at exit.
```

### Steps to reproduce

Above

**Comment by qarmin** [comment]
Still happens with 4.0.alpha.custom_build.cbdc33bcf
```
ERROR: 62 RID allocations of type 'N10RendererRD7TextureE' were leaked at exit.
```

**Comment by JohanAR** [comment]
I tried to investigate this a little, and it seems like it could be prevented with better validation of arguments, however I'm not sure where the best place to add this is. The candidates I have so far are:

* ImageTexture3D::create
* TextureStorage::texture_3d_initialize
* Image::validate_3d_image

**Comment by qarmin** [comment]
No longer leaks
