### ISSUE TITLE
Cannot use different Rendering Backends(Desktop vs Mobile) from command line

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#53731]
### Godot version

4.0

### System information

Ubuntu 21.04 - Nvidia GTX 970, Gnome shell 3.38 X11

### Issue description

Currently I cannot use one time Mobile and other time Desktop Vulkan backend by just changing command line options.
I need to set this in project settings manually.

Not sure, but --rendering-driver seems to be proper option, but it is unimplemented

**Comment by Calinou** [comment]
This is fixed now:

- `--rendering-driver vulkan|d3d12|opengl3|opengl3_angle`
- `--rendering-method forward_plus|mobile|gl_compatibility`
