### ISSUE TITLE
C# Vector2(1,0).Rotated(Mathf.Deg2Rad(90))  The results are inconsistent with GDS

### ISSUE THREAD

**Issue by magian1127** [godotengine/godot#53736]
### Godot version

3.x

### System information
windows 10

### Issue description

GDS
```
	var vector = Vector2(1, 0);
	vector = vector.rotated(deg2rad(90))
	print(vector)
```
Print
(-0, 1)

C#
```
            var vector = new Vector2(1, 0);
            vector = vector.Rotated(Mathf.Deg2Rad(90));
            GD.Print(vector);
```
Print
(-4.371139E-08, 1)

**Comment by Calinou** [comment]
Remember to use `is_equal_approx()` or `is_zero_approx()` to perform floating-point comparison. Floating-point math has limited precision, so you need to allow for a tolerance. The functions I listed do this for you automatically :slightly_smiling_face:
