### ISSUE TITLE
Add CTRL+<left/right arrow> and CTRL+SHIFT+<left/right arrow> cursor operations in text inputs

### ISSUE THREAD

**Issue by paper-pauper** [godotengine/godot#5375]
In most programs:

* `CTRL+left arrow` moves to the start of the current word or else, the start of the previous word

* `CTRL+shift+left arrow` selects everything from the cursor position to the beginning of the current word, and previous words after repeated presses

The reverse applies for the right arrow. I think this is a simple but important function and should be implemented in Godot's text inputs.

(The text editor already has this functionality, BTW, but it's broken because when you use `CTRL+SHIFT+<left/right key>` and then use `CTRL+<left/right arrow>` the selection stays)

**Comment by vnen** [comment]
Wasn't this added by #5271? Ping @neikeq.

**Comment by neikeq** [comment]
@vnen I added it to LineEdit in that PR. TextEdit already had it, but I am not sure what's the bug mentioned in this issue.

**Comment by paper-pauper** [comment]
@neikeq Thank you for fixing the issue (and apologies for not having noticed). The bug I was referring to is still there - go in the GDScript editor and try to select something via CTRL+SHIFT+Left arrow, then release it and try to move elsewhere via CTRL+Left arrow. You'll see that the selection won't be cancelled, which is inconsistent with how nearly all other programs behave (and awkward).

**Comment by neikeq** [comment]
I see. It only seems to happen with TextEdit. LineEdit behaves as expected. I will fix ASAP.
