### ISSUE TITLE
More consistent entries under the "Scene" submenu

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#5376]
In my opinion "Project Settings", "Quit to Project List" and "Quit" don't belong to the "Scene" submenu. Yes, there are separators between them and the other entries but those functions have nothing to do with scenes. It's especially bad in the case of "Project Settings" - who'd look for (universal) project settings  in the menu for a (partial) scene?

I suggest those entries are moved to a "Project" submenu, for additional consistency.

**Comment by paper-pauper** [comment]
I won't open another issue for this but the Script Editor also suffers from this, as the entries related to themes are under "File" but don't have anything to do with files.

**Comment by KoBeWi** [comment]
The menu got re-arranged in 3.0 and the project-related entries got a new menu. Quit is still there, but it's hard to find a better place for it. Editor -> Quit Editor would make sense, but it would feel somewhat less intuitive.

As such, closing this one.
