### ISSUE TITLE
GDScript 2.0: RefCounted not concidered Object class in typed Array

### ISSUE THREAD

**Issue by BraindeadBZH** [godotengine/godot#53771]
### Godot version

v4.0.dev.calinou [6f1d2133b]

### System information

Windows 10

### Issue description

Declaring an Array of RefCounted derived class using its class_name gives the following error:

```
E 0:00:05:0955   @implicit_new: Class names can only be set for type OBJECT
  <C++ Error>    Condition "p_class_name != StringName() && p_type != Variant::OBJECT" is true.
  <C++ Source>   core/variant/array.cpp:619 @ set_typed()
  <Stack Trace>  main.gd:3 @ @implicit_new()
```

### Steps to reproduce

Create a RefCounted derived class and give it a class_name. In another script declare a member Array using the newly created class as type.

### Minimal reproduction project

[ClassNameIssue.zip](https://github.com/godotengine/godot/files/7338906/ClassNameIssue.zip)

**Comment by ucenna** [comment]
This is not exclusive to RefCounted, it happens for Object too. i.e.
for
```
var x : Array[Object] = []
```
will also throw the `Class names can only be set for type OBJECT` error

**Comment by novaplusplus** [comment]
I was experiencing this in my previous self-built copies of Godot 4.0 and am still getting it in 4.0 alpha 1. It appears to throw two identical error for each typed array. It also happens to Object and all Object derived classes as well for me. This includes inner classes too (which I believe are derived from RefCounted internally...?)

It does not appear to affect functionality despite the errors. I can't say what the performance impact if any might be like, though.
