### ISSUE TITLE
Window content is not rendered within the scene editor

### ISSUE THREAD

**Issue by BraindeadBZH** [godotengine/godot#53776]
### Godot version

v4.0.dev.calinou [6f1d2133b]

### System information

Windows 10, Geforce 970M

### Issue description

When adding nodes to a Window node, they are not rendered in the editor. It works when playing the scene.
![image](https://user-images.githubusercontent.com/3399852/137185758-db78b610-357a-4c9f-bd2a-f2d18460da7c.png)

### Steps to reproduce

Create a new scene, make it based on the Window node and add other nodes as child. You don't see the added node in the scene editor.

### Minimal reproduction project

[WindowIssue.zip](https://github.com/godotengine/godot/files/7340321/WindowIssue.zip)

**Comment by KoBeWi** [comment]
Still valid in d30a0d2

Sometimes the Window will glitch and render contents of other popups/dialogs from the editor:
![image](https://user-images.githubusercontent.com/2223172/176906462-3638b9c2-ddc9-4c22-b7b0-f88d4d09136f.png)
