### ISSUE TITLE
Emit a signal when VideoPlayer stops?

### ISSUE THREAD

**Issue by Keyaku** [godotengine/godot#5377]
**Operating system or device - Godot version:**
Any OS - Godot 2.X

**Issue description** (what happened, and what was expected):

I'm trying to get the best performance out of a scene of mine that plays a video and adds subtitles (thanks to a custom GDScript I wrote).  
The video is played via a VideoStreamTheora and handled by a VideoPlayer Node.

Now, my scene constantly checks if the video is still playing so that it can move on when it stops. I've been looking around in godot's code and I can't find out the source of the `is_playing()` since it points to a `playback->is_playing()` (I think it checks for a bool value?), but anyways, I believe a signal would lay off a little bit — if not more — stress out of CPU (on a side note, I see that Theora drops many frames).

So, I looked at the signals singleton but found out (remembered, actually) that "finished" is already a signal that exists for animation, so I'm not sure if the signal can conflict with the video if we were to point both towards it. If this is the case, it's best to make a signal entirely for streaming.  
If this is not feasible, what can be an alternative?

**Comment by J08nY** [comment]
If I did something like #5227 but for VideoPlayer, would that solve the issue? So that started signal is emitted each time the stream starts/restarts. Stopped signal is emitted only when the stream is interrupted while playing and finished signal is emitted when the stream stops naturally(runs out).

**Comment by Keyaku** [comment]
Ah, I somehow didn't find that PR. Yes, that'll solve the issue, and actually add more to it!
