### ISSUE TITLE
Godot overlays other applications when in fullscreen

### ISSUE THREAD

**Issue by tqphan** [godotengine/godot#53788]
### Godot version

3.3.3

### System information

Windows 10 GLES3

### Issue description

I need Godot to work with Windows accessible applications such as Onscreen Keyboard and Magnifier. Currently with Godot 3.3.3, OS.window_fullscreen = true would cover up the Onscreen Keyboard and Magnifier making them unusable. I need Godot to be fullscreen and not cover the Onscreen Keyboard and Magnifier. How can I achieve this?

### Steps to reproduce

I have tried the following:

Project Settings > Display > Window > Always On Top is disabled

OS.set_borderless_window(true)
OS.window_fullscreen = true

and 

OS.set_borderless_window(true)
OS.set_window_position(Vector2.ZERO)
OS.set_window_size(OS.get_screen_size())

**Comment by alan-ma** [comment]
This seems to be related to how Windows renders applications that take up the entire screen - some optimization causes the fullscreen application to not be active when other windows like the On-Screen Keyboard are overlayed on top.

If you're okay with some pixels being offscreen, one workaround is to position the Godot application slightly offset from (0, 0):

```
OS.set_borderless_window(true)
OS.set_window_position(Vector2(0, -1))
var size = OS.get_screen_size()
size.y += 1
OS.set_window_size(size)
```

**Comment by Calinou** [comment]
Is this something that can be worked around from the Godot side? I remember Windows detecting borderless fullscreen applications and applying specific optimizations on them as described above.

**Comment by tqphan** [comment]
@alan-ma Thank you for the workaround. This problem I only encounter with Godot and not other game engines.

**Comment by akien-mga** [comment]
I would expect that there might be a Windows API we can use for this. Being able to use accessibility features while in fullscreen seems sensible and thus something that might be configurable.

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/953.

**Comment by starryalley** [comment]
I've seen a similar issue recently in Windows 10 where I need to launch another fullscreen application (always on top=true) through a fullscreen godot app (always on top=false). In one setup I can successfully launch that other app without problem but in another setup (difference being only screen resolution is different and a slightly different revision of Windows 10) godot always takes up the full screen. That other app is showing behind godot even if that app runs always-on-top fullscreen.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/60665, as this is the same underlying cause.
