### ISSUE TITLE
Inspector lags when editing theme

### ISSUE THREAD

**Issue by floppyhammer** [godotengine/godot#53802]
### Godot version

v3.4.beta6.official [3e2bb415a]

### System information

Windows 11, GLES3

### Issue description

![theme_editing](https://user-images.githubusercontent.com/28705694/137307868-160dd408-559f-474b-833b-9dca42e47af5.gif)

Accessing styles from the theme editor seems fine though.

### Steps to reproduce

Create a new theme, import all theme elements, try to edit it in the Inspector.

**Comment by akien-mga** [comment]
CC @pycbouh

**Comment by pycbouh** [comment]
It should be snappier with https://github.com/godotengine/godot/pull/53397, but what you show in the gif is just inspector updating a big resource, and that’s pretty slow in general.

**Comment by floppyhammer** [comment]
@pycbouh In 3.3 and before, such lag doesn't occur (or too trivial to notice). I wonder what changed since then.
