### ISSUE TITLE
[ HTML5 Game ] - FPS on Exported Project Capped up to 60. Can't go more than 60

### ISSUE THREAD

**Issue by ScotFlux** [godotengine/godot#5381]
**Operating system or device - Godot version:**

HTML5 Platform - Any OS? - Godot 2.1alpha 60fa2b9

**Issue description** (what happened, and what was expected):

- What happened? FPS capped up to 60. And can't go > 60.

- What was Expected? It should harness the max power of the device (PC in my case) that shown by more FPS since the project is a simple one.

**Steps to reproduce:**

1.) Open one of examples or demos that comes with Godot.
2.) Do some setting that deal with FPS things (use_vsync, target_fps, print_fps)
3.) Export the project to HTML5 Platform
4.) Play the project using Firefox (or other)
5.) Now, FPS capped to 60.

**Link to minimal example project** (optional but very welcome):

Just use examples & demos that comes with Godot.

**Comment by Calinou** [comment]
Your browser is very likely to enforce VSync or a FPS cap of some sort. AFAIK, they all do this.

**Comment by ScotFlux** [comment]
So, this is a browser "mistake" and not Godot? If so, then let's close this.

**Comment by punto-** [comment]
Nobody's ever going to need more than 640 frames per second

**Comment by ScotFlux** [comment]
Yes, I completely agree about wasting resources on FPS > 60. The one that drive me thinking about FPS of a HTML5 game made with Godot is I want to impress Local HTML5 gamedev and want to see them saying "Wow", when I show'em that shiny FPS number (while learning and making app/game with Godot, I guess I'm also promoting Godot anywhere). Because I have no idea what to impress anyone except a shiny FPS number when it comes to performance. But, I could be wrong though. :laughing: lol

[ Copied from my comment on another issue tracker ]

**Comment by ScotFlux** [comment]
So now, it's safe to close this, right?
