### ISSUE TITLE
Scene/Filesystem panel resizes on switch

### ISSUE THREAD

**Issue by hetdegon** [godotengine/godot#5384]
**Operating system or device - Godot version:**
Issue started at an unknown point in previous commits (after Node panel was introduced) and persists in current (9e0b605) master

**Issue description** (what happened, and what was expected):
When putting the Scene and Filesystem panels to share space, switching to Filesystem resizes the panel layout for no clear reason, as seen in these screenshots. It doesn't matter if you manually enlarge the area vertically, Filesystem will always take space away from the bottom panels. (so greedy)
![ihbl1jq](https://cloud.githubusercontent.com/assets/323651/16334261/208a4a52-3a00-11e6-8e2f-dfd70ff3523d.png) ![tkqodnn](https://cloud.githubusercontent.com/assets/323651/16334264/2595ad8e-3a00-11e6-839b-06cfcffe299d.png)

This is a minimal thing, a papercut if you will, but there's no obvious reason for it to behave like this.

**Steps to reproduce:**
Put Scene and Filesystem panels in the same position, with other panel at the bottom, and switch between them.

**Comment by bojidar-bg** [comment]
Probably a min-size related issue ^^

**Comment by samuelgrigolato** [comment]
Removing this line:

`tree->set_custom_minimum_size(Size2(0,200)*EDSCALE);`

From `ScenesDock::ScenesDock(EditorNode *p_editor)` in _scenes_dock.cpp_ seems to solve the issue. Could anyone confirm this (maybe even propose some test cases) so I can prepare a PR?

**Comment by samuelgrigolato** [comment]
PR: #5416

**Comment by akien-mga** [comment]
Reopening as the fix was not correct.

**Comment by reduz** [comment]
I think the problem is that the minimum sizes of Scene and Filesystem are different, if we make them the same and this issue should go away.  Alternatively the previous fix was not bad in itself, but it breaks dock when used vertically (as both the tree and files appear together).  

A possible solution could be to check the filesystem dock and remove the minimum size when the tree appears alone, but re-add it when it shows in split view

**Comment by hetdegon** [comment]
Another little thing I noticed is that, in my setup, if you switch from the default (folder/tree view) to the file view (read: opening a folder) it'll size itself properly. So it's only the default folder view what resizes?
