### ISSUE TITLE
GDScript 2.0 errors when calling a function with a typed array with custom class as a parameter

### ISSUE THREAD

**Issue by Uxeron** [godotengine/godot#53847]
### Godot version

4.0.dev (55c71ba)

### System information

Windows 10

### Issue description

When attempting to call a function that, as one of it's parameters, has a typed array with a custom class, GDScript throws an error `Invalid type in function 'test_func' in base 'Node ()'. Cannot convert argument 1 from Array to Array`.
This only happens when running the project.

### Steps to reproduce

Create a custom class with `class_name`
Create a function that takes a typed array with the custom class as the type `func test_func(_array: Array[CustomClass]):`
Add a function call to that function, passing in an array (even an empty array works) `test_func([])`
Play the project

### Minimal reproduction project

[TypedArrayTest.zip](https://github.com/godotengine/godot/files/7354278/TypedArrayTest.zip)

**Comment by bfeber** [comment]
Confirmed in alpha14

**Comment by keeganstothert** [comment]
still in beta 6

**Comment by freelancer42** [comment]
The exact issue as described here seems to be resolved as of beta 10. The following code works for me:

(Character is a custom class)

```GDScript
func test_func(array: Array[Character]):
	print(array)

func caller():
	test_func([])
	test_func([characterInstance])
```

**However**, when the array is stored in a variable or dictionary prior to the function call it only works if the variable is properly typed:

```GDScript
func test_func(array: Array[Character]):
	print(array)

func caller():
	# This works
	test_func([])
	
	# This DOES NOT work
	test_func({ 'array': [] }['array'])
	
	# This DOES NOT work
	var test_dict_1 = { 'array': [] }
	test_func(test_dict_1['array'])
	
	# This DOES NOT work
	var actual_array_3: Array = []
	var test_dict_3 = { 'array': actual_array_3 }
	test_func(test_dict_3['array'])
	
	# This works
	var actual_array_5: Array[Character] = []
	var test_dict_5 = { 'array': actual_array_5 }
	test_func(test_dict_5['array'])
	
	# This DOES NOT work
	var actual_array_7 = []
	test_func(actual_array_7)
	
	# This DOES NOT work
	var actual_array_8: Array = []
	test_func(actual_array_8)
	
	# This works
	var actual_array_9: Array[Character] = []
	test_func(actual_array_9)
```

As far as I can tell, as long as the array is stored in a properly typed variable, that variable can be used as a function argument. If however the variable is not strongly typed (either an untyped Array or completely untyped) it does not work.

The odd case here actually seems to be when the array is defined inline in the function call (first example). In that case it seems like the engine is successfully inferring the correct type?

I suppose this does make sense on some level, but it doesn't feel very intuitive that "test_func([])" works while "var array = []; test_func(array)" does not. And the error message ("Cannot convert argument 1 from Array to Array") is... less than user friendly :)

**Comment by akien-mga** [comment]
CC @vonagam

**Comment by vonagam** [comment]
In old behavior errors shown in last comment would have been a bug:

```gdscript
var not_typed_array = []
test_func(not_typed_array)
```

Old idea in this case was to silently create a new typed array and copy contents of `not_typed_array` into it. But any modifications inside the function will be affect only that converted array and not reflected in any way on original way. Which is wrong.

Intended new behavior will function just as shown in last comment. There will be a strong difference between value of type `Array` and `Array[T]`. 

It will work for literals (as it does now too) because it means that there are no other users or references to that new array and it can be converted during analysis to typed one.

I do agree that old error message is really bad.

**Comment by freelancer42** [comment]
Good explanation, makes perfect sense!

**Comment by venilark** [comment]
var array_dictionary: Dictionary

	func test_array():
		array_dictionary = {
			"array": [""]
		}
		
		var arrayTesterClass = ArrayTesterClass.new(array_dictionary.array)
		var a = arrayTesterClass.my_array
		print(arrayTesterClass.my_array)

	class ArrayTesterClass:
		var my_array: Array[String]
		
		func _init(my_array: Array[String]):
			self.my_array = my_array

Invalid type in function 'new' in base 'GDScript'. Cannot convert argument 1 from Array to Array.

**Comment by vonagam** [comment]
`my_array` is `Array[String]`, `array_dictionary.array` is just a basic `Array` (which happen to have a string in it). Think of argument as being typed as almost `PackedStringArray`.

In current PR to make it work you would need to do this:
```
array_dictionary = {
  "array": [""] as Array[String]
}
```

And there is a plan for typed array constructor in the future with syntax like this:
```gdscript
array_dictionary = {
  "array": Array[String]([""])
}
```

Tried to make error clearer now it will say:
```
Invalid type in function 'new' in base 'GDScript'. The array of argument 1 (Array) does not have the same type as the expected typed array argument.
```

**Comment by venilark** [comment]
In my project, the array_dictionary comes from JSON.parse_string(file.get_as_text()), so even when doing 
ArrayTesterClass.new(dict.array as Array[String]) it throws the same error
is there a solution for that?

**Comment by vonagam** [comment]
In future syntax it will be `Array[String](dict.array)`, in PR it can be done like that:
```
var typed_array: Array[String] = []
typed_array.typed_assign(dict.array)
ArrayTesterClass.new(typed_array)
```

In current state on master I think you should be able to resolve it like that:
```gdscript
var typed_array: Array[String] = dict.array
ArrayTesterClass.new(typed_array)
```

**Comment by wyvernbw** [comment]
I get the error when using const but not when using var:
```gdscript
const OtherKeys: Array[String] = [...]
# cannot convert argument 1 from Array to Array ❌

var OtherKeys: Array[String] = [...]
# works fine ✅
```

**Comment by opyate** [comment]
This problem is still apparent with inheritance.

## parent class

```
extends Resource
class_name MyParent
# ...
```

## child class

```
extends MyParent
class_name MyChild
# ...
```


## in script

```
func fn(arr: Array[MyParent]): ...

# elsewhere

var objs: Array[MyChild] = get...
fn(objs)  # does not work
fn(objs as Array[MyParent])   # does not work
```
