### ISSUE TITLE
Vulkan: GPUParticles3D Color ramp is messed

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#53851]
### Godot version

v4.0.dev.custom_build [bf322bacd]

### System information

manjaro 21, AMD Radeon r7 200 series, Vulkan, 8GB Memory

### Issue description

When you change the color ramp colors, it doesnt work properly

https://user-images.githubusercontent.com/58845030/137516257-5105953c-6db3-47ca-9ee6-ab78a2d9231f.mp4

probably a regression of: #48506

### Steps to reproduce

Shown in the video above!

### Minimal reproduction project

[MRP.zip](https://github.com/godotengine/godot/files/7354658/MRP.zip)

**Comment by fljohnson** [comment]
Identical failure in v3.5 under Ubuntu jammy: Color Ramp setting has no effect on GPU Particles

**Comment by Calinou** [comment]
> Identical failure in v3.5 under Ubuntu jammy: Color Ramp setting has no effect on GPU Particles

This is not a bug. You need to enable **Vertex Color > Use As Albedo** on the SpatialMaterial used by the mesh in the particle node.

**Comment by fljohnson** [comment]
Thanks for the heads-up. It wasn't intuitive at all, nor do I think it was in the manual

**Comment by Calinou** [comment]
> Thanks for the heads-up. It wasn't intuitive at all, nor do I think it was in the manual

I improved the documentation for this in https://github.com/godotengine/godot/pull/65040 :slightly_smiling_face:

**Comment by Jamsers** [comment]
>This is not a bug. You need to enable Vertex Color > Use As Albedo on the SpatialMaterial used by the mesh in the particle node. (This isn't enabled by default for performance reasons.)

But just to clarify, for Godot 4, this is still an open issue right? Cause I can confirm on my end (4.0.beta8.official) that color ramp still has no effect on my GPUParticles3D (I'm using a RibbonTrailMesh) and Vertex Color -> Use as Albedo is ticked on in my material.

**Comment by Calinou** [comment]
> But just to clarify, for Godot 4, this is still an open issue right?

Yes.

**Comment by clayjohn** [comment]
This has been fixed. I tested as of RC3 and adding a colorramp works fine. No need to close and re-open the scene

![Screenshot from 2023-02-23 11-22-21](https://user-images.githubusercontent.com/16521339/221009285-cae684bd-4d3e-4227-81cc-2e43b50f41d6.png)
