### ISSUE TITLE
MP3 properties not in Inspector

### ISSUE THREAD

**Issue by juanitogan** [godotengine/godot#53855]
### Godot version

3.3.4

### System information

Windows 10

### Issue description

mp3 files do not show their properties (AudioStreamMP3) in the Inspector like ogg and wav files do.

mp3:
![image](https://user-images.githubusercontent.com/2923222/137537285-0a741855-cbde-418c-a203-92c8beae04c3.png)

ogg:
![image](https://user-images.githubusercontent.com/2923222/137537335-0ca99c55-6296-4b64-b18c-bb696ea2097d.png)

### Steps to reproduce

Import an mp3 and check the Inspector.

**Comment by pycbouh** [comment]
Can you provide the file?
