### ISSUE TITLE
Window node renders black square in editor

### ISSUE THREAD

**Issue by cameronsteele** [godotengine/godot#53861]
### Godot version

4.0.dev (78ddae8512)

### System information

Windows 10, NVIDIA GPU

### Issue description

Window node displays black rectangle in editor. Does not display any children. When game runs, seems to operate normally.

Editor engine outputs: `scene\main\viewport.cpp:221 - Condition "index == -1" is true` when loading a scene with a broken Window node, which is from this block of code in viewport.cpp:

```cpp
void Viewport::_sub_window_update(Window *p_window) {
    int index = -1;
    for (int i = 0; i < gui.sub_windows.size(); i++) {
        if (gui.sub_windows[i].window == p_window) {
            index = i;
            break;
        }
    }

    ERR_FAIL_COND(index == -1);

    [...]
```

![image](https://user-images.githubusercontent.com/735509/137551637-061b08cf-1ccd-4858-a95e-db109a7e493e.png)

### Steps to reproduce

1. Compile Godot
2. Create new project
3. Add Window node
4. Observe black rectangle

**Comment by seppoday** [comment]
In 4.0 alfa it even sometimes render like this:
![Godot_v4 0-alpha1_win64_window_node_problem](https://user-images.githubusercontent.com/62170071/150851769-55cb3823-97d1-4974-b9c6-a399e8138c6c.png)

**Comment by Nocxr** [comment]
Can confirm this is also happening to me in the latest build as of today (26b21dc0cb517f9baacdaceafe09285952540d6a).  The window node itself never shows any sub/child elements and will random display artifacts if you turn it on and off: 

https://user-images.githubusercontent.com/72276215/153743265-428f1c0f-b2c8-48e2-8a68-43a1610927a0.mp4

Windows 10 19043.1446
XFX 5700XT Radeon 22.2.1
Godot Version 4: 26b21dc0cb517f9baacdaceafe09285952540d6a
