### ISSUE TITLE
Problem with animation

### ISSUE THREAD

**Issue by drcucaracha** [godotengine/godot#53864]
### Godot version

Godot_v4.0-dev.20211015_win64

### System information

windows 10

### Issue description

hello the problem I have is that the animation frames are missing and it is slightly different than in version 3.4 beta 6

Godot_v3.4-beta6_win64

https://user-images.githubusercontent.com/49615968/137558300-21a48030-031d-46dc-a21c-1293cabad8bb.mp4

Godot_v4.0-dev.20211015_win64

https://user-images.githubusercontent.com/49615968/137558828-0f6364b2-a1a1-4ee7-86d1-752d7c21a5db.mp4

### Steps to reproduce

test the minimum reproduction

### Minimal reproduction project

Godot_v3.4-beta6_win64

[G3.zip](https://github.com/godotengine/godot/files/7356206/G3.zip)

Godot_v4.0-dev.20211015_win64

[G4.zip](https://github.com/godotengine/godot/files/7356207/G4.zip)

**Comment by drcucaracha** [comment]
@fire Hello thanks for answering if you look closely at the hand that holds the spear, you will see that it goes through the mesh in version 4 time (1.3 sec approx) but not in version 3 and it goes as slow as if you look at the frames of the same bones you will notice that they seem to be missing frames the animation is at 0.1 speed so that it can be appreciated well, I know they changed the animation system and I asked in the general chat yesterday if I had to report it or leave it to be stable and they told me to report it and as today there was already an alpha available I thought it was already finished

**Comment by fire** [comment]
I'm currently compiling godot 4. Can try try setting the fps to 30?

**Comment by drcucaracha** [comment]
I do not understand how to configure at 30 fps what I did was to select (AnimationPlayer- in playback options-speed 0.1) so that you could see well detailed what happens in the animation

anyway I am going to download a "newer" compiled version and try

**Comment by fire** [comment]
Looking at the animation frame by frame, it seems like the animation optimize needs to be disabled for this animation.

**Comment by fire** [comment]
![image](https://user-images.githubusercontent.com/32321/137565174-df8ffb33-f806-4645-844a-a2e5457315b4.png)

Try disabling where the arrow is.

**Comment by drcucaracha** [comment]
deactivating it solves the animation, the weird thing is that I never used the importer because it would close godot and let it import only by copying the folder

**Comment by Calinou** [comment]
@drcucaracha Can you (or anyone else) still reproduce this bug in [Godot 4.0alpha1](https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-1) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.
