### ISSUE TITLE
[4.0] AnimationPlayer Onion Skinning is disabled due to corrupted rendering bug

### ISSUE THREAD

**Issue by Gromph** [godotengine/godot#53870]
### Godot version

v4.0.dev.20211015.official [f113dc986]

### System information

Windows 10 21H1, Vulkan, Nvidia GTX 760 472.12

### Issue description

Turning on Onion Skinning and moving the current track position results in flickering red with bits of garbage from the UI mirrored and upside down
![image](https://user-images.githubusercontent.com/361560/137574181-c70acc10-4e1b-45dd-b297-61f20020d38c.png)

I verified that Onion Skinning does work correctly on this computer with Godot Version 3.3.4 and 3.4 beta 6 using GLES 3

### Steps to reproduce

1. Create new project using Vulkan Clustered or Vulkan Mobile
2. Create a 2D Scene
3. Add an AnimationPlayer
4. Create New Animation
5. Click Onion Skinning
6. Move Current track position

### Minimal reproduction project

[OnionSkinning.zip](https://github.com/godotengine/godot/files/7356985/OnionSkinning.zip)

**Comment by andersmmg** [comment]
Just a note, this issue persists in alpha 6.

**Comment by alex9099** [comment]
I can reproduce on alpha8, arch linux with nvidia 1060 (laptop)

**Comment by Ansraer** [comment]
Can reproduce this in alpha 10 on win 10 with an amd 6900xt.

**Comment by insomniacUNDERSCORElemon** [comment]
Seeing this in Beta 1. Aside from breaking the feature itself there is a fast flickering with the red, I am by no means a doctor but this may be a potential seizure risk. 

So probably something that should be fixed ASAP.

**Comment by akien-mga** [comment]
#66590 will disable onion skinning for now until this can be solved properly, possibly by @RandomShaper when he's available.
