### ISSUE TITLE
RichTextLabel's `visible_characters` no longer accounts for words that break over several lines (Complex Text Layouts regression)

### ISSUE THREAD

**Issue by DeeJayLSP** [godotengine/godot#53874]
### Godot version

Godot v4.0.dev.20211015.official [f113dc986]

### System information

Kubuntu 21.04

### Issue description

This has been found while porting a project from Godot 3 to 4.
Not sure if a bug or intended, but I haven't seen this change stated anywhere and there's no option to behave the other way.

In Godot 3, increasing the value of RichTextLabel's `visible_characters` starts typing a word that would get out of bounds already in a new line:

![v3](https://user-images.githubusercontent.com/60024671/137578068-d9cd9cd5-7667-45cd-9b24-eac492c3745a.gif)

In Godot 4, however, it starts typing the word, then moves it to a new line:

![v4](https://user-images.githubusercontent.com/60024671/137578147-9bc3a557-5ad4-41bb-8bd0-991ff3359291.gif)

This seems annoying for someone who got used the first behavior.

### Steps to reproduce

- Make a RichTextLabel, give it any text long enough to add new lines and set visible characters to 0
- Assign a timer to increase the value of visible characters.

Repeat the process on the other version

### Minimal reproduction project

[This file](https://github.com/godotengine/godot/files/7357097/visible_characters_test.zip) includes tests on v3 and v4.

**Comment by malleusinferni** [comment]
It looks like a couple of attempts have been made to fix it, but they don't address the fundamental design flaw in the new shaping/rendering pipeline. For "typewriter text" to work, the text shaping and layout stage must take the entire string as input (including invisible characters) and produce the complete list of renderable glyphs/quads. It's up to the rendering stage to look at `visible_characters` and pick out substrings of pre-shaped text. Thus, when a game updates `visible_characters`, it should prompt a redraw, not a full relayout.

The current behavior (ie. taking substrings before shaping) may break horribly on ligatures and combining characters. It ought to be possible to write additional test cases to probe for this.

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by DeeJayLSP** [comment]
I think I should mention this: when showing a word so large it gets out of bounds in Godot 3, it somehow breaks the line for everything to show up. On 4 however, it just gets out of bounds as usual.
