### ISSUE TITLE
SpatialMaterial UV 1 Scaling float precision is limited

### ISSUE THREAD

**Issue by Nukiloco** [godotengine/godot#53888]
### Godot version

v3.4.beta6.mono.official [3e2bb415a]

### System information

Windows 10, Nvidia GTX 750 Ti

### Issue description

Currently the UV 1 Scale property is limited by 3 decimal places aka ``0.0055`` turns into ``0.006`` which makes setting accurate UV scaling impossible since I need more precision though it seems like Godot is limiting this right now.

There is a possibility that other properties are limited as well when they can handle more precision than three decimal places.

### Steps to reproduce

Description above ^

**Comment by Ev1lbl0w** [comment]
Seems like any editor float property is set with a step value of `0.001`, making that rounding behavior:
https://github.com/godotengine/godot/blob/c2402754821e8fa6a6666531c9dbbcd2193d4e05/editor/editor_properties_array_dict.cpp#L895-L898

**Comment by Zireael07** [comment]
Nitpick, I have exported values in my space game that need more than three decimal points (distances in AU, star luminosity being some examples, so I'd like a way to use a greater precision for those too - currently I am seeing the same round up to three decimals behavior as OP.

**Comment by akien-mga** [comment]
> Vector2/Vector3 property editors should probably be modified to use the default_float_step editor setting, which currently defaults to 0.001. This way, you can use a greater precision for all Vector2/Vector3 properties if needed.

That's the correct solution yes.

**Comment by Calinou** [comment]
> What about changing the behavior so it won't round values when they come from keyboard input? For working with very small values, users will be typing these anyways.

The rounding is currently done with the `step` property in EditorSpinSlider/SpinBox. Allowing keyboard input to bypass this rounding could break existing projects, so it needs to be exposed as (yet another) boolean property that's `false` by default.
