### ISSUE TITLE
Making a DirectionalLight visible alters script behavior (GLES3)

### ISSUE THREAD

**Issue by SusanaHewitt** [godotengine/godot#53899]
### Godot version

3.4 Beta 6

### System information

Windows 10 GLSES 3

### Issue description

The following script is used in a cutscene. It works fine for three ships until I activate a directional light, of all things. When I do, the ships fly straight down and off camera.

```gdscript
extends Spatial

var randomGen : RandomNumberGenerator
var goingUp : bool
var totalY : float

func _ready():
	randomGen = RandomNumberGenerator.new()
	randomGen.randomize()
	if (randomGen.randf_range(-.05, .05) > 0):
		goingUp = true
	else: goingUp = false
	totalY = 0.0#THE AMOUNT OF TOTAL TRANSLATION UP OR DOWN

func _process(deltaTime):
	if (goingUp):
		totalY += deltaTime
		translate(Vector3(0, deltaTime, deltaTime*7))
		if (totalY > .6):
			goingUp = false
	else: 
		totalY -= deltaTime
		translate(Vector3(0, -deltaTime, deltaTime*7))
		if (totalY < -.6):
			goingUp = true
```

### Steps to reproduce

I have a camera whose AnimationPlayer scrolls it sideways across a Spatial, making it follow three ships that are moving with the aforementioned script. For some reason, the directional light (which even when only disabled--doesn't have to be removed--doesn't break the animation) breaks the behavior of the ship. The camera itself continues to pan as desired.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
