### ISSUE TITLE
HTTPRequest node documentation POST request example is outdated or incorrect.

### ISSUE THREAD

**Issue by jitspoe** [godotengine/godot#53910]
### Godot version

3.4 beta 4

### System information

Windows 10

### Issue description

HTTPRequest node documentation outdated.

The example shows:
```
    var body = {"name": "Godette"}
    error = http_request.request("https://httpbin.org/post", [], true, HTTPClient.METHOD_POST, body)
```

However, the signature of the function is:
`Error request(url: String, custom_headers: PoolStringArray = PoolStringArray(  ), ssl_validate_domain: bool = true, method: Method = 0, request_data: String = "")`

### Steps to reproduce

Simply copy/paste the POST example in the HTTPRequest documentation and note the error: "Invalid type in function 'request' in base 'HTTPRequest'. Cannot convert argument 5 from Dictionary to String."

### Minimal reproduction project

(just copy the example)

**Comment by kitarp29** [comment]
@Chaosus
I just have to make the changes in the Documentation right?
 Can you assign this issue to me?

**Comment by mhilbrunner** [comment]
Yes, class docs are .rst files in the main repo, tutorials and the like live in the godot-docs repo.
In general we don't assign issues in such cases, you can just work on it and submit a PR :)

**Comment by kitarp29** [comment]
Sure Thanks.

**Comment by kitarp29** [comment]
@jitspoe Could you direct me to the correct file for these changes??

**Comment by jitspoe** [comment]
> 
> 
> @jitspoe Could you direct me to the correct file for these changes??

Should be under doc/classes/HTTPRequest.xml
