### ISSUE TITLE
Drop down menus fight for control (DisplayServer regression)

### ISSUE THREAD

**Issue by Tadaboody** [godotengine/godot#53912]
### Godot version

4.0.dev.custom_build.5bf01654d

### System information

macOS 11.6 (20G165)

### Issue description

![Screen Recording 2021-10-17 at 12 18 09 mov](https://user-images.githubusercontent.com/6463334/137621369-0b0a62ba-ac1c-4fa8-843b-634bf30dd572.gif)

### Steps to reproduce

Open a project, click on any of the drop-downs and drag your mouse to any option not under "Scene"

### Minimal reproduction project

an empty project(.zip)

*Bugsquad edit (keywords for easier searching): flicker, flickering*

**Comment by Calinou** [comment]
@Tadaboody Can you reproduce this if you enable **Single Window Mode** in the Editor Settings then restart the editor?

**Comment by dploeger** [comment]
I'd like to add that in my case this happens and additionally the drop down menus are covering their parent menu items when opening. This doesn't happen in *Single Window mode* as well.

(Tell me, if that's too different and I should add another issue for it)
