### ISSUE TITLE
status != 0x8CD5 in RasterizerGLES2::canvas_light_shadow_buffer_create [Intel HD 3000, two monitors]

### ISSUE THREAD

**Issue by chalcosoma** [godotengine/godot#5392]
OS: Windows 7 Home Premium 64 bits 
Godot Engine: v2.0.3 stable
Processor: Intel Core i5 2500k 
Graphics Card: Intel HD Graphics 3000
Driver date: 26/05/2015
Driver version: 9.17.10.4229

Issue description:
I tested some Godot examples and all was working fine. I connected my other old display device - an AOC 19" max res: 1680x1050.  After I'm using two display devices the error happened.
I was following the learning step-by-step tutorial and I was in the section 1.4.3 Scripting a scene.
Then I created this script as the instructions:

```
extends Panel

func _on_button_pressed():
    get_node("Label").set_text("HELLO!")

func _ready():
    get_node("Button").connect("pressed", self, "_on_button_pressed")
```

The script works but I get the following error:

```
Type: Error
Description:
Time: 0:00:01:0087
C Error: Condition ' status != 0x8CD5 ' is true. returned: RID()
C Source: drivers\gles2\rasterizer_gles2.cpp:8804
C Function: RasterizerGLES2::canvas_light_shadow_buffer_create
```

And in debugger output:

```
**Debugger Process Started**
Remote Debugger: Connection failed with status: 2", retrying in 1 sec.
EXEC PATHP??: C:\PortableApps\Godot_v2.0.3_stable_win64.exe
EXEC PATHP??: C:\PortableApps\Godot_v2.0.3_stable_win64.exe
EXEC PATHP??: C:\PortableApps\Godot_v2.0.3_stable_win64.exe
DETECTED MONITORS: 1
```

Will I have some problem with the error above or it's ok?

Sorry for my bad English.

![error1](https://cloud.githubusercontent.com/assets/20130832/16347201/ccc1278e-3a21-11e6-9451-1a6f2b454857.jpg)
![error2](https://cloud.githubusercontent.com/assets/20130832/16347200/ccc0f688-3a21-11e6-8008-8853ec761444.jpg)

**Comment by akien-mga** [comment]
Can anyone reproduce this issue with two monitors? I fear this might be a drivers bug, as the Intel HD Graphics 3000 drivers seem to be quite bad on Windows (at least Windows 10, but maybe they were hardly better in Windows 7?).

**Comment by bojidar-bg** [comment]
Pretty bump :smile:

**Comment by avril-gh** [comment]
> Can anyone reproduce this issue with two monitors?

Godot Engine: v2.2 alpha 2016.09.28 custom build
OS: Windows 7 Ultimate 32bit
Processor  Intel(R) Core(TM)2 Quad Q8200 (4CPU) at 2.33GHz
Graphics NVidia GTX 750
Driver date: 16/09/2016
Driver version: 21.21.13.7290
Monitor1 1280x1024
Monitor2 1360x768

- **I can NOT confirm above issue.**
- **I do NOT experience mentioned error for above given example.**
- **I do NOT experience any errors for advanced 3D project using most of 3D godot features on both monitors.**


_The only thing i experience is kinda low frame rate on android devices,
but perhaps i should not use that many effects i do (i dont see it in most android games)
secondly, we looking forward for godot optimizations in this area,
and finally its a completly different topic anyway..._

**Comment by seyhbold** [comment]
I can.

Windows 7 Enterprise SP1 64bit
Core i5-3320M
Intel HD Graphics 4000
Driver date: 26/03/2012
Driver version: 8.15.10.2712

Godot_v2.1.2-stable_win64.exe

**Comment by BastiaanOlij** [comment]
I can confirm for me this seems to be an issue with intel. 

Working on my HP Probook laptop yesterday unplugged Godot is running on the slowpoke Intel GPU and I get dozens of these errors. Using yesterdays master, Windows 10.

Today plugged in (shouldn't leave my charger at work) and its running on the AMD Radion GPU without a hitch..

Only difference is the intel v.s AMD GPU so I would say its a driver thing.

**Comment by Evrey** [comment]
Can confirm this somewhat as well, though not Intel but AMD, not `canvas_light_shadow_buffer_create` but `_render_target_allocate`, not Godot 2 but Godot master branch from today *(2017-09-30)*, not GLES2 but GLES3:

```text
OpenGL ES 3.0 Renderer: AMD HAWAII (DRM 2.49.0 / 4.11.9-1-rt7-MANJARO, LLVM 5.0.0)
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
mode: spatial
SVG_GENERATION TIME: 0.608512
try to see fs update2
ERROR: _render_target_allocate: Condition ' status != 0x8CD5 ' is true.
   At: drivers/gles3/rasterizer_storage_gles3.cpp:6263.
```

Build command used for the Godot editor was:

```fish
scons use_llvm=yes bits=64 -j 8 udev=yes platform=x11 tools=yes
```

GPU driver is `xf86-video-ati`, which might be buggy. I'm not sure whether this is really-really related or just suspiciously similar.

**Comment by akien-mga** [comment]
> Can confirm this somewhat as well, though not Intel but AMD, not canvas_light_shadow_buffer_create but _render_target_allocate, not Godot 2 but Godot master branch from today (2017-09-30), not GLES2 but GLES3:

So it's not the same issue at all :)

Please open a specific issue for that one.

**Comment by Evrey** [comment]
> Please open a specific issue for that one.

Tried to replicate the bug before filing and issue and couldn't. Guess a random driver update fixed it. Or you fixed it and didn't know it, as I re-compile Godot every few days from Git's master branch. Yay, I guess?

**Comment by iRadEntertainment** [comment]
Same error here. The same project has been edited and tested on many other PCs without showing this error. When I opened the project on my old laptop, the error shows up. Video drivers haven't been updated for a while, though.
Hardware here:
-Operating System: Windows 7 Ultimate 64-bit (6.1, Build 7601) Service Pack 1 (7601.win7sp1_rtm.101119-1850)
-Processor: Intel(R) Celeron(R) CPU B815 @ 1.60GHz (2 CPUs), ~1.6GHz
-DirectX Version: DirectX 11
-Card name: Intel(R) HD Graphics
-Driver Version: 8.15.10.2712

**Comment by iRadEntertainment** [comment]
UPDATE:
I've updated the drivers on my video card with the latest ones. The error keep showing up.

Note. Compared to other hardware settings this affect the performances pretty bad on the _draw func. I've used _draw estensively on this project for testing purpouses, drawing lot of lines (around few hundreds at once in the viewport) and the more lines I draw, the more laggy the editor runs the project. Not sure if it's related, but definetly unnatural lag (to much for just lines)

**Comment by sksdutra** [comment]
Same problem here, the latest Godot stable (2.1.4), I can use with issues, but the Godot 3 beta 2 I can't.

- **Operating System**: Windows 10 Pro 64-bit
- **Processor**: Intel(R) Core(TM) i3-2350M CPU @ 2.30GHz 2.30GHz (Sandy Bridge)
- **RAM**: 4GB DDR3
- **Card name**: Intel(R) HD Graphics 3000
- **Driver Version**: 9.17.10.4459
- Direct X 12

I'm worried because I think Intel will not update this driver anymore.

Anyone has a solution? Thanks in advance.

**Comment by vnen** [comment]
@sksdutra Intel(R) HD Graphics 3000 does not have support for OpenGL 3.3, so you won't be able to run Godot 3 until a version with the GLES2 renderer is available (which will take a while).

**Comment by sksdutra** [comment]
@vnen it's sad 'cause I only have this notebook to learn, so I'll have to choose another engine without so much GPU issues.

Thank you. Goodbye Godot.

**Comment by Kinrany** [comment]
I also have this problem.

 * **Godot:** Steam v2.1.4
 * **Operating System:** Windows 7 Professional 64-bit
 * **Processor:** Intel Core i5-2520M CPU @ 2.50GHz
 * **RAM:** 4GB
 * **GPU:** Intel HD Graphics 3000
 * **Driver:** 9.17.10.4229

I have the same error right after I launch Godot:

```
ERROR: RasterizerGLES2::canvas_light_shadow_buffer_create: Condition ' status !=
 0x8CD5 ' is true. returned: RID()
   At: drivers\gles2\rasterizer_gles2.cpp:8275
```

When I open the project, I also get this:

```
WARNING: AudioDriverRtAudio::callback: RtAudio output underflow!
     At: drivers\rtaudio\audio_driver_rtaudio.cpp:57
OPENING: C:/Users/Ruslan/Documents/MAI/Программирование игр/лабораторная 2/godot
 (C:::Users::% PROJECT PATH HERE %)
running cmdline: "C:\Program Files (x86)\Steam\steamapps\common\Godot Engine\god
ot.windows.opt.tools.32.exe" "-path" "C:/Users/% PROJECT PATH HERE %" "-editor"
ERROR: RasterizerGLES2::canvas_light_shadow_buffer_create: Condition ' status !=
 0x8CD5 ' is true. returned: RID()
   At: drivers\gles2\rasterizer_gles2.cpp:8275
unicode error: invalid skip
ERROR: PopupMenu::get_item_text: Index p_idx out of size (items.size()).
   At: scene\gui\popup_menu.cpp:674
ERROR: PopupMenu::set_item_checked: Index p_idx out of size (items.size()).
   At: scene\gui\popup_menu.cpp:622
```

I don't know if these are related.

The warning seems to repeat from time to time for no reason.

&nbsp;

@sksdutra You could use 2.1.4 until 3.1 is out.

**Comment by aaronfranke** [comment]
Can you test on Linux? Older Intel GPUs are known to have really bad Windows drivers. If it's a driver bug, there's likely not much we can do to solve it.

**Comment by akien-mga** [comment]
This might work fine with GLES2 on Godot 3.2.

If the (notoriously problematic) Windows drivers for Intel HD 3000 claim OpenGL 3.3 support, you might need to force using OpenGL 2.1 by running Godot from the command line with the `--video-driver GLES2` switch, e.g.:
```
path\to\godot.exe --path path\to\project --video-driver GLES2 -e
```
and set "GLES2" as rendering backend in the project settings.
