### ISSUE TITLE
`Input.joy_connection_changed` have ambigity between a signal name and a method

### ISSUE THREAD

**Issue by BenjaminNavarro** [godotengine/godot#53931]
### Godot version

4.0 dev (468b987aa3)

### System information

Linux

### Issue description

In the `Input` class `joy_connection_changed` is both a signal and a method, which leads to ambiguities, at lest in GDScript.

For instance, trying to connect the signal: 
```gdscript
Input.joy_connection_changed.connect(_on_joy_connection_changed)
```
leads to the following error:
```
Cannot find property "connect" on base "Callable"
``` 

I think it's quite easy to fix, either the signal or the method as to be renamed. I'm ok to do it but I don't know which one is the best candidate for a rename and which name to choose for it.

### Steps to reproduce

Add the following script to any project:
```gdscript
extends Node

func _ready():
	Input.joy_connection_changed.connect(_on_joy_connection_changed)

func _on_joy_connection_changed(device_id, connected):
	print("joystick ", device_id, " is now ", connected)
```

**Comment by KoBeWi** [comment]
Already mentioned here: https://github.com/godotengine/godot/issues/38937#issuecomment-922331209
