### ISSUE TITLE
Engine closes bootsplash before loading the entire scene

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#53941]
### Godot version

v4.0.dev.custom_build [bf322bacd]

### System information

manjaro 21, AMD Radeon r7 200 series, Vulkan, 8GB Memory

### Issue description

When you have a sky set in the worldenvironment the engine shows the game before loading the sky

Without sky:

https://user-images.githubusercontent.com/58845030/137649541-98cc913d-5506-4654-ac1d-6b1d7e5cac03.mp4

With sky:

https://user-images.githubusercontent.com/58845030/137649552-35c2023e-6697-45ef-b9f2-06fb8667b858.mp4

PS: Maybe its not visible but from 06-09 the game is still "flickering/lagging" due to sky

### Steps to reproduce

* Create a 3d scene
* Add a worldenviroment node
* Set any type of sky
* run the game

### Minimal reproduction project

N/a

**Comment by clayjohn** [comment]
This was fixed a long time ago. Initializing the sky became very fast and should now only take a few milliseconds per frame for the first couple of frames.
