### ISSUE TITLE
[WIP] Vulkan: Use of hard-coded MSAA value (e.g. in mesh preview) causes GPU hangs

### ISSUE THREAD

**Issue by follower** [godotengine/godot#53940]
### Godot version

Godot Engine v4.0.dev.20211015.official.f113dc986 (and earlier)

### System information

Linux, Elementary OS 5.1, Intel(R) HD Graphics 4400 (HSW GT2), Vulkan API 1.2.182

### Issue description

_Summary:_

**Viewing a `Mesh` resource (seemingly of any subtype but most recently tested with `BoxMesh`) in the inspector results in a GPU hang.**

_Details:_

* Initially the GPU hang issue was observed to occur when opening/editing a `MeshInstance3D` that contained a mesh (or when creating one) but the specific cause was narrowed down to the rendering of the preview.
 
  (This means that if the "Node" tab is top-most--rather than the "Inspector" tab--it is possible to avoid the variant of the hang that prevents a newly created mesh from being saved when first created.)

* It also turns out the underlying issue was the reason why selecting a MSAA setting of 2X (`Viewport::MSAA_2X`) for the project settings also led to a GPU hang.

My impression is that this specific issue _may_ be GPU/driver specific however I have not isolated the lowest level of bug detail yet to be able to confirm this.

### Specific cause of hang

The hang occurs as a result of this code:

https://github.com/godotengine/godot/blob/468b987aa38b21b55c1cd8a8d4c03b8e1b2a1373/editor/plugins/mesh_editor_plugin.cpp#L113

When running under `gdb`, if the line is skipped (resulting in a default MSAA value of `Viewport::MSAA_DISABLED`) or the value is patched (to be the value of `Viewport::MSAA_DISABLED`) then the GPU hang does not occur.

(see also: https://github.com/godotengine/godot/blob/58aa020a19162becc9a00fed8a240eb12b0ab964/scene/main/viewport.h#L103-L110)

Note: The issue does not occur for the Material Editor, presumably because it uses a value of `Viewport::MSAA_4X` (which for whatever reason doesn't appear to be affected):

https://github.com/godotengine/godot/blob/468b987aa38b21b55c1cd8a8d4c03b8e1b2a1373/editor/plugins/material_editor_plugin.cpp#L119

### Vulkan Validation output

When run with Vulkan validation layers enabled the output (in part) includes the message:

```
ERROR: VALIDATION - Message Id Number: 1607255571 | Message Id Name: VUID-VkImageCreateInfo-samples-02258
        Validation Error: [ VUID-VkImageCreateInfo-samples-02258 ] Object 0: handle = 0xabcee50, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x5fccc613 |vkCreateImage(): samples VK_SAMPLE_COUNT_2_BIT is not supported by format 0x0000000D. The Vulkan spec states: samples must be a bit value that is set in imageCreateSampleCounts (as defined in Image Creation Limits) (https://vulkan.lunarg.com/doc/view/1.2.182.0/linux/1.2-extensions/vkspec.html#VUID-VkImageCreateInfo-samples-02258)
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_DEVICE, Handle 180153936
   at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:157)
```

Note particularly the portion which reads `samples VK_SAMPLE_COUNT_2_BIT is not supported by format 0x0000000D`.

That said, the `format 0x0000000D` does look a bit suspicious to me because AFAICT it doesn't actually match with a valid format value--which, based on some debugging I've performed, makes me wonder if something unexpected is happening at some point as the parameters are being processed.

### Additional code context

The initial call to `Viewport::set_msaa()` ends up here:

https://github.com/godotengine/godot/blob/56078cca90402c2ea49252216b96f53fc649d4ec/scene/main/viewport.cpp#L2777-L2784

Which then eventually seems to find its way to `RendererViewport::viewport_set_msaa()` here:

https://github.com/godotengine/godot/blob/58aa020a19162becc9a00fed8a240eb12b0ab964/servers/rendering/renderer_viewport.cpp#L939-L948

(See also: 

 * https://github.com/godotengine/godot/blob/58aa020a19162becc9a00fed8a240eb12b0ab964/servers/rendering_server.h#L825-L833
 * https://github.com/godotengine/godot/blob/53426bdc7195a3b4b9c1d0425d0ad5543ef3769a/servers/rendering_server.cpp#L2188
 * https://github.com/godotengine/godot/blob/58aa020a19162becc9a00fed8a240eb12b0ab964/servers/rendering/rendering_server_default.h#L566
 * https://github.com/godotengine/godot/blob/58aa020a19162becc9a00fed8a240eb12b0ab964/servers/rendering/renderer_viewport.h#L244
)

Which then heads to `RendererViewport::_configure_3d_render_buffers()` here:

https://github.com/godotengine/godot/blob/58aa020a19162becc9a00fed8a240eb12b0ab964/servers/rendering/renderer_viewport.cpp#L74-L94

[TODO: Add additional details.]

### Steps to reproduce

[TODO]

### Minimal reproduction project

[TODO]

**Comment by follower** [comment]
The result of running `Godot Engine v4.0.dev.custom_build.181d9337c` with test project
[`vulk-msaa-issue-repro--002.zip`](https://github.com/godotengine/godot/files/7492441/vulk-msaa-issue-repro--002.zip)*:

![msaa-pr-54606-test-screenshot](https://user-images.githubusercontent.com/189962/140649272-4693d0d6-0111-41e4-b854-47130f62ad0f.png)

\* The project actually has MSAA 4X selected in the project settings but I turned that off for this screenshot.

So, #54606 does appear to successfully work around the specific issue related to the mesh preview, as the GPU did not hang and the preview can be seen.

**Comment by Calinou** [comment]
Note that the issue about MSAA support not being checked before being applied is now tracked in https://github.com/godotengine/godot/issues/56233.
