### ISSUE TITLE
fails to compile with android_arch=x86

### ISSUE THREAD

**Issue by TheoXD** [godotengine/godot#5396]
Windows 10, latest head

Can compile fine with just "scons platform=android"  but with "scons platform=android android_arch=x86" it fails and gives the very well known (not very specific) error:

scons: *** [platform\android\os_android.os] The system cannot find the file specified

Wanted to try and use x86 emulator on desktop, I suppose that can't be done right now.

**Comment by akien-mga** [comment]
Hm, it built fine 9 days ago at least: https://github.com/GodotBuilder/godot-builds/releases/tag/master_20160616

**Comment by TheoXD** [comment]
@akien-mga, yes but you're on Linux, aren't you?

**Comment by akien-mga** [comment]
This specific build was done on Travis' OSX build nodes, but yeah it could then hint that it might be a Windows-specific bug. Are you using MSVC or MinGW?

**Comment by TheoXD** [comment]
It doesn't matter, it uses linux-android-g++ from NDK anyway , but I have MSVC installed yes.

**Comment by akien-mga** [comment]
I gather that it used to work in the past? Any idea of the last time it worked OK for you?

Recent commits that might have impacted the buildsystem:
- https://github.com/godotengine/godot/commit/a0fb5b5f95f0d4ce90766301ddce4e5f199fb125
- https://github.com/godotengine/godot/commit/408c26ce0bc3847ed956a6993faa2619cd942da2

**Comment by TheoXD** [comment]
Heh, \toolchains\x86-4.9\prebuilt\windows folder had to be renamed to "windows-x86_64", just as I had to do with the one for folder inside arm-linux-androideabi-4.9. Problem solved I guess xP
