### ISSUE TITLE
Raycasting to mouse position during _input is delayed per click

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot#53968]
### Godot version

3.3.3 stable

### System information

Windows 7 64-bit

### Issue description

If attempting to raycast to the mouse position during the event check, it will print "found" one click late, as if the raycasting happens late and it catches up the next time the player clicks. This is one-click latent:

```gdscript
func _input(event):
	if event is InputEventMouseButton and event.pressed:
		var mousePos = get_viewport().get_mouse_position()
		var from = cam.project_ray_origin(mousePos)
		var to = cam.project_ray_normal(mousePos)
		ray.cast_to = to * 10
		ray.translation = from
		if ray.is_colliding():
			print("found")
```

This, however, works:

```gdscript
func _input(event):
	var mousePos = get_viewport().get_mouse_position()
	var from = cam.project_ray_origin(mousePos)
	var to = cam.project_ray_normal(mousePos)
	ray.cast_to = to * 10
	ray.translation = from
	
	if event is InputEventMouseButton and event.pressed:
		if ray.is_colliding():
			print("found")
```

It is more expensive though, as the raycasting calculation has to be done during each input call, rather than only if the player clicks.

### Steps to reproduce

Add a raycast node, try the above code.

**Comment by elvisish** [comment]
> Try disabling input event accumulation by calling `Input.set_use_accumulated_input(false)` in the `_ready()` function.
> 
> PS: Please surround blocks of GDScript code with triple backticks like this:
> 
> ```gdscript text here ```
> 
> This prevents them from taking too much space and also makes sure issue references aren't accidentally created. I edited your comment, but remember to do this next time slightly_smiling_face

Oh sorry, I forgot to check my code formatting this time, I've been trying to remember! :/

I tried `Input.set_use_accumulated_input(false)` in the `_ready()` function and it doesn't do any different, unfortunately.

**Comment by pouleyKetchoupp** [comment]
Make sure you call `ray.force_raycast_update()` after you change the ray parameters, it's needed when you want the new result immediately.

Otherwise `Raycast` node only updates on the next physics frame for performance reasons.

I'm closing for now since it doesn't look like a bug, but feel free to ask if you have any question or trouble.
