### ISSUE TITLE
Key input issue with special characters and french keyboards (AZERTY)

### ISSUE THREAD

**Issue by Linko-3D** [godotengine/godot#53970]
### Godot version

3.3.4

### System information

MX Linux with the french keyboard layout

### Issue description

Input.is_key_pressed( ) works with both lower and upper case but with special characters like É it only works in upper case.

### Steps to reproduce

The Input.is_key_pressed(KEY_A) for example works for both lower and upper case this is normal but when using special keys like KEY_EACUTE (É key) it only works in upper case with caps lock enabled on my AZERTY keyboard (actually with capslock the é key enters the number 2...). The same applies to other special keys like for example KEY_CCEDILLA (Ç key), it only works with caps lock which enters the number 9 on my keyboard.
This only happens with letters, for example Input.is_key_pressed(KEY_AMPERSAND) (& key) works fine.

### Minimal reproduction project

func _process(delta):
	print(Input.is_key_pressed(KEY_EACUTE)) # Should display true if é in lower case is pressed

**Comment by Calinou** [comment]
Use physical key inputs if you want to avoid disrepancies across keyboard layouts. These were introduced in Godot 3.4 beta:

![image](https://user-images.githubusercontent.com/180032/137778178-c90cd1e9-bfd7-47da-9a71-6f3fbc857635.png)

**Comment by Calinou** [comment]
@Linko-3D Did you get physical key inputs to work?

**Comment by Linko-3D** [comment]
Hello,

Yes the Physical option works both on QWERTY and AZERTY keyboard layout.
