### ISSUE TITLE
Cannot connect using websocket ssl on MacOS

### ISSUE THREAD

**Issue by LoneDespair** [godotengine/godot#53989]
### Godot version

3.3.3

### System information

MacOS

### Issue description

I've setup a server that loads letsencrypt certificates and key, clients from Windows can join except MacOS

And the MacOS can only join if the ssl is disabled

Already tried to overwrite the trusted certificates, but the issue still persists

### Steps to reproduce

Setup an ssl websocket server
Connect using MacOS

**Comment by mhilbrunner** [comment]
Sounds like something with the cert was funky. If you can reproduce this and provide detailed error output, please do so! Otherwise glad you found a way to make this work.
