### ISSUE TITLE
`ProceduralSkyMaterial` uses all `DirectionalLight3D` in the scene as suns

### ISSUE THREAD

**Issue by BenjaminNavarro** [godotengine/godot#53985]
### Godot version

4.0.dev (483df71120)

### System information

Linux

### Issue description

In my scenes I use a `WorldEnvironment` node with `ProceduralSkyMaterial` to generate the sky and I have one `DirectionalLight3D` for the sun, as a child of the `WorldEnvironment`. But I also have another `DirectionalLight3D`, inside a different `Viewport`, somewhere deep in the hierarchy.

The problem is that this second light seems to also used by `ProceduralSkyMaterial` to generate a second sun, which also affect the lighting of the scene. 

With the second light enabled:
![Screenshot_20211019_092727](https://user-images.githubusercontent.com/14923636/137865396-ca162875-eaee-44bf-ab34-6e6a51720c2f.png)

With the second light disabled:
![Screenshot_20211019_092758](https://user-images.githubusercontent.com/14923636/137865402-ac5a5589-1601-4ad6-9646-5e2723b459fe.png)

To me it would make sense to only consider the `DirectionalLight3D` ligts that are below the `WorldEnvironment` node and not all the ones in the scene. If you think that's the way to go, I'm willing to try to make a PR for this.

### Steps to reproduce

Add a `WorldEnvironment` to a scene with a `ProceduralSkyMaterial` sky and two `DirectionalLight3D`.

### Minimal reproduction project

[DoubleSun.zip](https://github.com/godotengine/godot/files/7371222/DoubleSun.zip)

**Comment by Calinou** [comment]
> I propose replacing `use_in_sky_only` with a usage enum with options [Sky and lighting, Sky only, Lighting only].

I started working on this in a branch: https://github.com/Calinou/godot/tree/directional-light-add-sky-mode
