### ISSUE TITLE
Error when searching in AssetLib before first load

### ISSUE THREAD

**Issue by andersmmg** [godotengine/godot#53996]
### Godot version

3.4.rc1 (earlier too)

### System information

Manjaro Linux

### Issue description

Been an issue for a while, I thought it was fixed but I guess not. If I open the AssetLib and try to search before it loads the default list, I get this error and can't use the AssetLib until I restart the editor and let it load the recents list first.
`editor/plugins/asset_library_editor_plugin.cpp:1199 - Condition "!category_map.has(r["category_id"])" is true.`
Seems like it's because it doesn't yet have the list of categories when I try the search.

### Steps to reproduce

1. Open any Godot project
2. Switch to the AssetLib tab
3. Try searching before it has loaded the recents
4. Get the error
5. Can't search anything until editor is restarted

**Comment by KoBeWi** [comment]
This was done in this PR: #51941
We could re-open and merge it probably.

**Comment by dpensky** [comment]
Still happens in 3.4.4
![image](https://user-images.githubusercontent.com/7250660/165300968-e8d9e8aa-fbb3-42d4-9170-6e5c53fe8ea7.png)
