### ISSUE TITLE
[GDScript 2.0] Can't assign enum to a constant in GDscript

### ISSUE THREAD

**Issue by Untailygean** [godotengine/godot#54018]
### Godot version

4.0.dev (f113dc986)

### System information

Windows 10

### Issue description

In Godot 3, you could assign an enum to a constant. This is not possible in 4, you get "Parse Error: Initializer for a constant must be a constant expression.".
You can assign it to a variable instead but then you can't use it for export because you need a constant, so this is annoying.

### Steps to reproduce

Define a named enum, then try to assign that enum to a constant.

### Minimal reproduction project

Just paste this in a script.
```
enum ANIMAL_ENUM {COW, PIG, RABBIT}	#enum
var animal_var = ANIMAL_ENUM	#can assign the enum to a variable
const PIG_CONST = ANIMAL_ENUM.PIG	#can assign a member of the enum to a constant
const ANIMAL_CONST = ANIMAL_ENUM	#can't assign the enum itself to a constant
```

**Comment by Griefchief** [comment]
usage of such constants in static functions (usage of enums in static functions).
Static function can't access var's, only constants.

Example from res://addons/zylann.hterrain/hterrain_data.gd that can not be ported to Godot 4. This is a const dictionary, but it still can't be used.

```

const _map_types = {
	CHANNEL_HEIGHT: {
		name = "height",
		shader_param_name = "u_terrain_heightmap",
		texture_flags = Texture.FLAG_FILTER,
		texture_format = Image.FORMAT_RH,
		default_fill = null,
		default_count = 1,
		can_be_saved_as_png = false,
		authored = true,
		srgb = false
	},
	CHANNEL_NORMAL: {
		name = "normal",
		shader_param_name = "u_terrain_normalmap",
		texture_flags = Texture.FLAG_FILTER,
```

this will fail:
```
# TODO Can't hint it, the return is a nullable Color
static func _get_map_default_fill_color(map_type: int, map_index: int):
	var config = _map_types[map_type].default_fill
	if config == null:
		# No fill required
		return null
```
![image](https://user-images.githubusercontent.com/5757704/182355508-2696aac9-830f-4e81-8f4e-6324f8ea9e93.png)

**Comment by HPCR-SD** [comment]
I’d love to see this implemented. I know my use case for this isn’t this big thing, but it seems I’m using it similarly to others and it’s just nice to have this option. I know this is old, but would really love to show some love to this that I’m sure would be quick easy change for beta 11 or 12! :)
