### ISSUE TITLE
More consistent look for CheckButton

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#5401]
The current CheckButton doesn't look bad, but it uses red when it is switched off and that's inconsistent with other (blue) GUI elements as well as other programs, which show check buttons as filled when switched on.

For that reason, I suggest the (default) CheckButton is changed to this:

![Alternative color](https://i.imgur.com/gZnE1VU.png)

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.
