### ISSUE TITLE
ConfigFile cannot handle comments in the cfg file; returns err 43

### ISSUE THREAD

**Issue by ZaneFadul** [godotengine/godot#54025]
### Godot version

3.4-beta2 (a71169c0e0ed7644b959189522535337bdb6cb2b)

### System information

Windows 10

### Issue description

I am working on an audio manager package, and am using ConfigFile to retrieve information from a `.cfg` file. When I don't include comments, the built-in parser works correctly and returns 0; however, trying to add comments (using `#`, `;`, or `--`) will  return a 43 error, cannot parse.

I would love to be able to include comments in the `.cfg` file such that I can give examples of how to set up the configuration file.

### Steps to reproduce

1. Create a `settings.cfg` file
2. Add a generic section, comment, and key-value pair to the file
```
[Settings]
#This is a comment
test=10
```

3. Create a GDScript that uses ConfigFile to retrieve the `.cfg` file:
```
var err = config.load("user://settings.cfg")
```

4. Print the `err` on runtime, and you should receive a 43 err

**Comment by KoBeWi** [comment]
It works if you use ConfigFile class and `;` for comments.

**Comment by ZaneFadul** [comment]
I just tried again. It may have been there was a parsing error somewhere else when I was using `;`, Thanks for clearing that up!

Regarding `#` and `--`, I guess it could be good to consider using these characters to better match up with ini-style formatting.

Thanks again!
