### ISSUE TITLE
Huge performance or scene start-up hit when using `self.` in nested for loops

### ISSUE THREAD

**Issue by razvanc-r** [godotengine/godot#5404]
Ubuntu 16.04 - Godot vs. 2.0.3.stable.official

**Issue description** (what happened, and what was expected):
When using `self.` in nested for loops it decreases performance dramatically (on the order of x100 to x1000 or so - time of execution). You'll notice that with `self.`, the time to execute the scene dramatically increases. It might not even be performance issue but just some bug related to the nested for loops because it takes a while to initialize and start the scene, not really to execute the script now that I think about it.

**Steps to reproduce:**
Make for loops (maybe only for nested for loops?!) and access a variable with `self.`.

**Link to minimal example project** (optional but very welcome):
I've uploaded a project file demonstrating the issue with comment in `map.gd` script where it makes the difference.
[godot_debug.zip](https://github.com/godotengine/godot/files/332930/godot_debug.zip)

It's a pity cause I really like using `self.` because it's more explicit and I'm an adept of the philosophy of code readability (over conciseness). Hope this is particular only to these for loops...

**Comment by bojidar-bg** [comment]
Sounds like a locking issue to me, but who knows...

**Comment by RandomShaper** [comment]
With #5407 it works equally faster with `self.` and without it.

Anyway, that PR takes the opportunity created here of making some optimization. But the true reason is still unsolved: I've found that in the slow case Godot was doing a COW on every call to `put_pixel()`.

**Comment by reduz** [comment]
Yeah pixel access on Images is really slow, this needs to be optimized

**Comment by RandomShaper** [comment]
…the weird thing being that when not using `.self` the COW is not performed, which is the bottleneck.

**Comment by RandomShaper** [comment]
Somehow related to the reference count of the memory block being incremented in the `self.` case. I haven't found why.
