### ISSUE TITLE
GDScript 2.0: exporting enum requires default value or else it will be null

### ISSUE THREAD

**Issue by Duroxxigar** [godotengine/godot#54040]
### Godot version

4.0

### System information

Windows 10

### Issue description

When you export a var of type enum, it requires that you set the default value in code, or else it will only ever be null

### Steps to reproduce

Create node/script

```
enum Type { ONE, TWO }
@export var test_type: Type

func _ready():
    print(type)
```

No matter what you select in the inspector, it will print null. You have to set a default value in the script first.

**Comment by cdemirer** [comment]
Currently if you select Two in the inspector, it works. Afterwards, selecting One also works. But if you don't change it yourself, the inspector shows One but it will be null.
