### ISSUE TITLE
Saving branch as scenes loses the connected signals

### ISSUE THREAD

**Issue by Nosrick** [godotengine/godot#5405]
Windows 7: Godot 2.1 alpha (current)

When exporting a scene that has been imported, signals that have been set up are not saved.

Steps:
Import roomCard.scn
Make the children editable, and uninstanced.
Add a signal (I chose the mouse exit signal) to Click.
Export the scene.
Import the scene again: the signal is now gone.

Can't provide a totally minimal project, but I can provide an instance of it happening in one of my current projects. Here's a link:
https://bitbucket.org/nosrick/monquest

**Comment by vnen** [comment]
What do you mean by "import scene" and "export scene"? Those are not Godot standard terms, so I can't understand how to reproduce it. "Import scene" actually means to import a `.dae` 3D scene tio the project, but I don't think that's what you're doing.

**Comment by Nosrick** [comment]
Oh, my apologies.
Let me amend the steps:
Import roomCard.scn
Make the children editable, and uninstanced.
Add a signal (I chose the mouse exit signal) to Click.
Export the roomCard node.
Import roomCard.scn again: the signal is now gone.

**Comment by bojidar-bg** [comment]
If it is uninstanced, it shouldn't propagate changes to instancing scene... or am I missing something?

**Comment by volzhs** [comment]
Let me translate it...

before | after
------------ | -------------
**Import** roomCard.scn | **Instance Child Scene** with roomCard.scn
Make the children editable, and **uninstanced**. | Make the children editable, and **Discard instancing**.
Add a signal (I chose the mouse exit signal) to Click. | Add a signal (I chose the mouse exit signal) to Click.
**Export** the roomCard node. | **Save Branch as Scene** the roomCard node.
**Import** roomCard.scn again: the signal is now gone. | **Instance Child Scene** with roomCard.scn again, the signal is now gone.

**Comment by Nosrick** [comment]
Thanks, volzhs. I'm still new to all this Godot stuff.

**Comment by AlexHolly** [comment]
I have the same issue with "Save Branch as Scene" I don't use the steps before so I think this is a "Save Branch as Scene" issue.

Example:

|game
-|hud(mouse script, contains connected mouse event)
--|mouse(connect signal to hud)

Use "Save Branch as Scene" on hud, open the hud scene and see that the mouse signal is not connected.
