### ISSUE TITLE
Console output errors on Windows lost colors

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#54059]
### Godot version

dc81583fb78ae625e8ae7fe9c1cdc42ede653afa

### System information

Windows 10

### Issue description

So, any errors which are emitted use white color, instead of red and yellow as before the bug:

![image](https://user-images.githubusercontent.com/3036176/138231868-4c3e3b19-3739-4493-b22d-3b380e213698.png)

### Steps to reproduce

Force to emit any error or warning

### Minimal reproduction project

Currently, it's very easy to reproduce by simply clicking on `TextEdit`: https://github.com/godotengine/godot/issues/54037

**Comment by akien-mga** [comment]
CC @groud
