### ISSUE TITLE
String.http_escape is platform dependent and does not work correctly on windows

### ISSUE THREAD

**Issue by Tetragramat** [godotengine/godot#54069]
### Godot version

v3.3.4.stable

### System information

Windows 10

### Issue description

`String.http_escape` does not correctly escape unicode strings on windows, but it works correctly on linux.

### Steps to reproduce

This GD script
```
var e = "隊伍解散了"
print(e)
print(e.http_escape())
```
On windows 10 outputs
```
隊伍解散了
%%%%%%%%%%%%%%%
```
On linux outputs
```
隊伍解散了
%E9%98%9F%E4%BC%8D%E8%A7%A3%E6%95%A3
```

**Comment by timothyqiu** [comment]
Fixed by #61656 (master) and #61655 (3.x)
