### ISSUE TITLE
Fullscreen not working in Godot 4 when passed to DisplayServer create function

### ISSUE THREAD

**Issue by AndreaTerenz** [godotengine/godot#54065]
### Godot version

4.0.dev

### System information

Issue verified on:
- Manjaro Linux 5.13, Ryzen 5 3600, Radeon RX 580 with Vulkan 1.2
- Windows 11, Intel i5-8250U, Nvidia MX 110 also with Vulkan 1.2

### Issue description

I am trying to port my game from Godot 3 to Godot 4. Somehow, even fullscreen isn't working, even though it is turned on in the settings:
![image](https://user-images.githubusercontent.com/8989002/138263895-4e2bb15c-3223-4586-a262-dd57659c8f81.png)
![image](https://user-images.githubusercontent.com/8989002/138263925-32a11e49-dac9-4526-b4d4-4920cd87191c.png)
I know the resolution is 1024x600, the Godot default, but on Godot 3 that isn't a problem and the window simply gets scaled to completely fill my 1080p screen. From an answer I received on reddit, from a user also having this issue, it seems to happen regardless of GPU brand and regardless of how Godot 4 is "acquired" (manual build or download from the pre-alpha releases) and of whether the project is run from the editor or as an executable.

### Steps to reproduce

1. Make a new Godot 4 project
2. Setup any kind of sample scene
3. Check "Fullscreen" in the project's Window settings

**Comment by akien-mga** [comment]
`porting` means related to [platform ports](https://en.wikipedia.org/wiki/Porting).

**Comment by follower** [comment]
FWIW a project with:

 * Project settings full-screen enabled and no `--fullscreen`: doesn't work.
 * Project settings full-screen enabled and *with* `--fullscreen`: doesn't work.
 * Project settings full-screen *not* enabled and *with* `--fullscreen`: *does* work.

**Comment by follower** [comment]
This is the commit where the initial change was made: https://github.com/godotengine/godot/commit/f8a79a97c7d12da43b111a756f09ee7ad5ea28e9#diff-18b7c19417a461e4793bb2157831659d96ede991391e10ee5bc51f19453b7685L1186

And from a quick glance it seems like the lack of `init_fullscreen` is *probably* unintentional & the  duplication *might* be unintentional?

**Comment by kreaninw** [comment]
For Visual Script users, you can use this as a workaround:

![Screenshot 2022-02-15 020823](https://user-images.githubusercontent.com/1403194/153996457-3425c6f0-c0d2-412d-96c1-c76fa66df094.jpg)

1. Add a **function call node**.
2. Set call mode to **Singleton**.
3. Set singleton to **DisplayServer**.
4. Set function to **window_set_mode()**.
5. Set up node as shown above.

You can see all the available **int values** for **window_set_mode()** [here](https://docs.godotengine.org/en/latest/classes/class_displayserver.html?highlight=window_set_mode#enum-displayserver-windowmode).

**Comment by akien-mga** [comment]
Still reproducible as of 4.0 alpha 12.

**Comment by akien-mga** [comment]
Fixed for Windows with #63914, but still pending a different fix for Linux.
