### ISSUE TITLE
Nodes created in the editor from the code do not appear in the scene tree.

### ISSUE THREAD

**Issue by anunknowperson** [godotengine/godot#54064]
### Godot version

4.0.dev (007b877cb)

### System information

Windows 10, Vulkan Clustered, INTEL R CPU 0000 / RTX 3060 Ti

### Issue description

Nodes created in the editor from the code do not appear in the scene tree. Both from GDScript tool script and from the C++ module. In Godot 3, the same code works correctly and the created object appears in the scene tree. In Godot 4, the object appears in Viewport, but not on SceneTree. When saving, the object disappears, unlike the object in Godot 3.
![image](https://user-images.githubusercontent.com/54563399/138263889-fc4eaaa9-c14f-4361-95cc-91303a6588aa.png)

### Steps to reproduce

Create Node3D scene, attach a script and paste this code:

@tool
extends Node3D

func _enter_tree():
--->var node := CSGBox3D.new()
--->add_child(node)
--->node.owner = owner
--->node.position = Vector3(0, 0, 0)

### Minimal reproduction project

[bug_test.zip](https://github.com/godotengine/godot/files/7388352/bug_test.zip)

**Comment by KoBeWi** [comment]
It should be `node.owner = self`.
