### ISSUE TITLE
[4.0 nightly build] Missing mesh data in imported glTF leads to console spam and crash when viewed in inspector

### ISSUE THREAD

**Issue by ModularNucleus** [godotengine/godot#54060]
### Godot version

v4.0.dev.calinou [965ae0619]

### System information

Windows 10, Nvidia GTX 1060 6GB, Studio driver 471.68, Vulkan Clustered.

### Issue description

When instantiating the included glTF file, and selecting its "test_character2" MehInstance,
the mesh is not displayed in the "Mesh" property in the inspector. The console spams the error:
"USER ERROR: Attempted to free invalid ID: ..." (see screenshot) and Godot crashes.
![Godot 4 nightly build - vulkan - attempt to free invalid id error](https://user-images.githubusercontent.com/91982860/138230568-79a7157d-9bd5-4233-a65f-611a4c6307cd.png)

This behaviour is not reproducible in v4.0.dev.20211015.official [f113dc986]: while the same error does
appear a few times in the console, the mesh is displayed and accessible through the "Mesh" property,
and Godot does not crash.
![Godot 4 pre-alpha - vulkan - attempt to free invalid id error](https://user-images.githubusercontent.com/91982860/138231478-edd1332d-5c80-42e8-b17e-18aa772439fe.png)

### Steps to reproduce

1. Open the included MRP and instantiate the "test_character.glb" glTF file
2. Select the "test_character2" MehInstance.
3. Observe:
- The missing display of the mesh in the "Mesh" property
- The console spam an error.
- Godot crashing. 

### Minimal reproduction project

The included glTF file (my own) is valid according to [https://github.khronos.org/glTF-Validator/](url)

[glTF Import Test.zip](https://github.com/godotengine/godot/files/7386947/glTF.Import.Test.zip)

**Comment by KoBeWi** [comment]
I got the error once, but not sure how it was triggered. Can't reproduce it anymore.
@ModularNucleus Can you check if the issue still exists for you in the newest alpha?

**Comment by ModularNucleus** [comment]
No, I cannot reproduce the issue in alpha9. I guess this can be closed?
