### ISSUE TITLE
Advanced importer generated cylinder shape is incorrect with height set to 1.0

### ISSUE THREAD

**Issue by zedutch** [godotengine/godot#54079]
### Godot version

4.0 dev (75f9a180a)

### System information

Windows 10, RTX 2080, Vulkan

### Issue description

When adding collisions in the advanced importer and choosing Shape Type "Cylinder", the cylinder's height is incorrect when set to 1.0.  
To make this more clear, here is the generated cylinder with height 0.99:
![afbeelding](https://user-images.githubusercontent.com/3418190/138320400-6eff7df3-fea5-432c-bfb7-a3b30a53df28.png)
And the one with height 1.01:
![afbeelding](https://user-images.githubusercontent.com/3418190/138320473-b84a268c-db8f-473b-909d-531334e61439.png)
And finally the one with height set to 1.0:
![afbeelding](https://user-images.githubusercontent.com/3418190/138320516-40cccb85-ca87-4121-b06b-788682266983.png)
The model is exported from Blender using gltf 2 (binary format). Blender reports the height as 0.98 so it seems like the cylinder with height set to 1.0 is the wrong one while 0.99 and 1.01 seem to generate correctly. All transformations have been applied in Blender before exporting. I did not change the root scale or any other settings in the importer.

### Steps to reproduce

1. Import any external model
2. Enable "Generate physics" in the advanced importer
3. Select the Cylinder Shape Type
4. Set height to 1 (should be the default)

**Comment by Calinou** [comment]
cc @AndreaCalligaris
