### ISSUE TITLE
Camera2D force_update_scroll() doesn't work if smoothing is enabled

### ISSUE THREAD

**Issue by timoschwarzer** [godotengine/godot#5409]
**Operating system or device - Godot version:**
Ubuntu 16.04 64-bit, 2.0.3

**Issue description** (what happened, and what was expected):
When I call `force_update_scroll()` to a Camera2D with smoothing enabled, I expect it to center the followed Node immediately.
For me I have no way to jump with the camera to a specific position without smoothing and enable smoothing right afterwards.

**Comment by bojidar-bg** [comment]
Probably another method would be nice, like, `force_center`, since `force_update_scroll` has another purpose :smile:

**Comment by timoschwarzer** [comment]
I'll try to make such a function myself and will create a PR if it works...

**Comment by bojidar-bg** [comment]
Ping, is this still valid on master?

**Comment by timoschwarzer** [comment]
There is the new `align()` function from https://github.com/godotengine/godot/pull/5490 which does the wanted behavior.
