### ISSUE TITLE
Texture not repeating if mipmapping not activated

### ISSUE THREAD

**Issue by BraindeadBZH** [godotengine/godot#5410]
**Operating system or device - Godot version:**
Windows 10 - Godot v2.0.3

**Issue description** (what happened, and what was expected):
When I create a Polygon2D and set texture with Repeat Flag the texture is stretched instead of being repeated. If I activate the Mipmaps Flag then the texture is repeated properly.

PS: I don't want mipmapping because I want my texture to be pixel perfect.

**Steps to reproduce:**
1. Create a scene
2. Add a Polygon2D
3. Draw a shape with the polygon tool
4. Add a Texture
5. Toggle the Mipmaps Flag with the Repeat Flag activated

Thank you

**Comment by reduz** [comment]
Not a bug, the GLES2 backend enforces this as this is a GLES2 limitation, will change in 3.0

**Comment by BraindeadBZH** [comment]
Thanks for your reply. Keep the good work, love the engine so far.

**Comment by BraindeadBZH** [comment]
Sorry closed it by mistake

**Comment by bojidar-bg** [comment]
I think this is closable in the GLES3 implementation currently on master, correct?

**Comment by bojidar-bg** [comment]
Closing since nobody replied.

**Comment by akien-mga** [comment]
Is it fixed in the current master branch?

**Comment by reduz** [comment]
This is no longer an issue in master, as GLES3 does not have this limitation
