### ISSUE TITLE
Tree style bg_focus is applied in front of Tree (instead of as background)

### ISSUE THREAD

**Issue by dozingpip** [godotengine/godot#54107]
### Godot version

3.4.rc1.mono

### System information

Windows 10

### Issue description

If the bg_focus style is set for a Tree, it renders what looks like a Panel on top of the Tree instead of behind it. The problem shows up in the Theme Editor directly and in game.
This issue is not present in 3.3.4 stable.
Before click/ before it has focus: ![bg_focus_issue](https://user-images.githubusercontent.com/6119565/138362680-dcbab605-f225-4185-9fdb-0f494709dca4.PNG)

After click/ when it has focus: ![bg_focus_issue2](https://user-images.githubusercontent.com/6119565/138362681-d2c17ea4-f23d-4328-b955-586833071d0a.PNG)

### Steps to reproduce

This can be seen in the Theme Editor directly, so I'll just write the steps to get there.

1. Create a new Theme.
2. Add type Tree to the theme.
3. Add bg_focus as editable style for Tree.
4. In the theme, Tree > styles > make bg_focus use a StyleBoxFlat.
5. Click on the Tree object in the Theme preview. (See issue, be sad.)

### Minimal reproduction project

[New Game Project.zip](https://github.com/godotengine/godot/files/7393022/New.Game.Project.zip)
(Open new_theme.tres and click on the Tree object in the Theme Editor to see the problem)

**Comment by Calinou** [comment]
This was documented
 by https://github.com/godotengine/godot/pull/55165, closing.
