### ISSUE TITLE
No 2D equivalent of viewport.get_camera()

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#5411]
I am making a 2D game and I need to get the current camera.
There is `get_viewport().get_camera()` but it is for 3D.
Is it implemented somewhere else, or is it missing?

**Comment by reduz** [comment]
This should be implemented somehow, but some work also needs to be done in order to support multiple viewports and cameras (for 2D split screen) this works different than 3D, so it will not be exactly easy to figure out the camera controlling a viewport

**Comment by WalasPrime** [comment]
Is split screen worked out already? I just stumbled upon this issue in my own project. Would love a `get_viewport().get_camera2d()` or something similar...

**Comment by mitchcurtis** [comment]
+1. In my case I was hoping I use this to find out which camera is current, as currently I have no idea.

**Comment by Hubber116sx** [comment]
This issue has been open for three years and the problem still persists to this day.
