### ISSUE TITLE
Vulkan: Cannot retrieve HDR texture from Viewport (LDR texture is returned instead)

### ISSUE THREAD

**Issue by thunderk** [godotengine/godot#54122]
### Godot version

4.0.dev

### System information

Vulkan API 1.2.162 - NVIDIA - GeForce GT 710

### Issue description

In Godot 3.x, when a Viewport was configured with `hdr` flag enabled, the result of `get_texture().get_data()` was an _RGBAHalf_ image.

In `master` branch, the `hdr` flag disappeared (because, as I understand, it's always HDR now), but calling `get_texture().get_image()` results in an _RGB8_ image, losing the high dynamic range.

### Steps to reproduce

* Create a SubViewport $vp
* In GDScript : `print($vp.get_texture().get_image().data.format)`

**Comment by thunderk** [comment]
@Anutrix I can confirm it was working in 3.3.4, but I believe I'm using this feature since at least 3.2

**Comment by BastiaanOlij** [comment]
In Godot 4 only the 3D rendering is performed in RGBA16F HDR buffers. 

In the stage where we apply tone mapping, color correction, exposure and linear -> sRGB conversion the 3D image is resolved into the 2D end result which is a RGBA8 buffer. Then 2D rendering is performed on top of that in sRGB color space. That is the buffer returned, as is, when accessing the image data for a viewport.

Further more, in the clustered renderer the 3D buffers are retained, but in the mobile renderer this result (which is using a R10G10B10A2 buffer) isn't kept, it is only handled in tile memory and never written out (performance reasons). Neither are accessible outside of the rendering engine.

**Comment by BastiaanOlij** [comment]
Vulkan is able to handle the linear->sRGB and sRGB->linear conversion just like OpenGL but with more control over it. So when you access a buffer in a shader it will do the proper conversions and provide the data correctly. But RGBA8 buffers remain stored in sRGB color space.

**Comment by lyuma** [comment]
I think a suggestion would be to have a "RAW mode" option in Viewport which disables most environment effects ("tone mapping, color correction, exposure and linear -> sRGB conversion") as well as disable 2d rendering (or permit 2d rendering directly to HDR while in this mode).

Generally if you are looking to use HDR output, you also don't want to run exposure or color correction (otherwise, exposure/color grading will be run twice when you output this HDR texture to the screen).

**Comment by BastiaanOlij** [comment]
i was mentioning that to Fire earlier today, the problem we have with the viewport approach at the moment is that we assume what we render, is the final output we display on screen. It isn't always the case.

The issue we have in accomplishing changing this is ultimately that we're trying to combine a 3D and 2D renderer together so we can overlay UI elements ontop of 3D output, while 2D is handled on the final output.

So there is some restructuring of the renderer needed to have more control over what the output is and thus keeping a 3D viewport that contains an intermediate result as an HDR viewport and thus remove 2D rendering capability.

The same btw for creating a viewport that allows you to render non color data, needed both for 2D and 3D reasons. this should have no conversion at all.

**Comment by Jojox** [comment]
I'm trying to make a quick fix for that to be able to do some post process effect. Using 'Rendering Server' feature i was able from GDScript to change the texture format of the viewport to 'RGBAF' but this just give me a black output.
I'm having a hard time finding the code where the viewport output is served as an image in the engine. Can someone point to the relevant piece of code ?

**Comment by VantaGhost** [comment]
This feature regression is preventing me from implementing post processing effects using either Viewports or screen_texture. I'm in the process of making a screen space lens flare shader, but I'm currently limited to testing in LDR.
I cannot implement my post processing until HDR is added to Viewports and screen_texture.

**Comment by JonqsGames** [comment]
I'm still trying to have #70970 merged, you can give it a try and it should allow HDR in viewport.
