### ISSUE TITLE
Mobile HTML5 multitouch isn't working properly

### ISSUE THREAD

**Issue by JustYourAverageJosh** [godotengine/godot#54135]
### Godot version

3.4

### System information

Windows 10, GLES2, GTX 1060

### Issue description

Multitouch seems to work on HTML5, as it detects the touch indexes (touch 0, 1, etc).
However, if there are multiple touches, and they both start dragging, it can only follow one, and temporarily sets the first touch to (0,0)?

Kinda weird, try the test project I have on itch.io to see what I mean.

It does keep track of the individual touches (if they're released and they're relative drag), but only one at a time.

Load up HTML project (on itch.io) and try to drag both left and right at the same time.

https://justyouraveragejosh.itch.io/multitouch

### Steps to reproduce

Here is a simplified version of my code:

	
```
var left_touched=[-1,Vector2()]
var right_touched=[-1,Vector2()]


func _input(event):
	
	if event is InputEventScreenDrag and event.relative.length_squared()<15000:
		if left_touched[0]==event.index:
			$Left.rect_position+=event.relative
			
		elif right_touched[0]==event.index:
			$Right.rect_position+=event.index
			
			
	if event is InputEventScreenTouch:
		if event.is_pressed() and event.index<2:
			if event.position.x>get_viewport().get_visible_rect().size.x*.5 :
				right_touched=[event.index,event.position]; 
			else:left_touched=[event.index,event.position]

		if !event.is_pressed():
			if event.index==right_touched[0]:
				right_touched[0]=-1
			elif event.index==left_touched[0]:
				left_touched[0]=-1
```

### Minimal reproduction project

[HTML_DUMMY_ZIP.zip](https://github.com/godotengine/godot/files/7400680/HTML_DUMMY_ZIP.zip)

**Comment by bfxdev** [comment]
The root cause is in [library_godot_input.js](https://github.com/godotengine/godot/blob/3.4/platform/javascript/js/libs/library_godot_input.js#L427):
```
				GodotRuntime.setHeapValue(coords + (i * 2), pos[0], 'double');
				GodotRuntime.setHeapValue(coords + (i * 2 + 8), pos[1], 'double');
				GodotRuntime.setHeapValue(ids + i, touch.identifier, 'i32');
```

The WASM heap is an array of bytes, consequently the indices need to reflect the size in bytes of the data to modify. It should be like this:
```
          GodotRuntime.setHeapValue(coords + i * 16,     pos[0], 'double')
          GodotRuntime.setHeapValue(coords + i * 16 + 8, pos[1], 'double')
          GodotRuntime.setHeapValue(ids + i * 4, touch.identifier, 'i32')
```

It works as expected after a manual modification of the generated .js file using the indices above.

**Comment by akien-mga** [comment]
I guess it could be `(i * 2) * 8` and `(i * 2 + 1) * 8` to make the logic clearer. Otherwise this looks like it would be good to PR to the `master` branch (and it can be cherry-picked for `3.x` and `3.4`).
