### ISSUE TITLE
Mismatching names: RealArray vs. FloatArray

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#5414]
There is a mismatch between those names when considering scripts and exposed interface. In the class reference you can find a `RealArray` (which is the internal C++ name) but in script code you can only use `FloatArray`. `VariantParser` also uses `FloatArray`.
#3654 was closed because `RealArray` was exposed to documentation. But since everywhere else in the exposed side (including custom properties and how text formats are saved) uses `FloatArray`, that should be proper name?

I have the opinion that C++ API and Script API shouldn't have different names. It'll make easier for a Godot user to understand the C++ code if they found familiar names in the API. There's also the name difference between `RawArray` (as exposed) and `ByteArray` (as used internally).

**Comment by volzhs** [comment]
I got confused because of this.

**Comment by reduz** [comment]
All names will be unified in 3.0

**Comment by reduz** [comment]
The idea is to use the term PooledFloatArray and similar for the others

**Comment by djrm** [comment]
Maybe we should create a Tracker for API changes

**Comment by bojidar-bg** [comment]
Resolved with the Pool*Array changes?

**Comment by vnen** [comment]
Yes, this is solved (sorry for the delay, didn't see this before).
