### ISSUE TITLE
GPUParticles2D unchecking local_coords does not work as intended

### ISSUE THREAD

**Issue by SpiderIerusalem** [godotengine/godot#54159]
### Godot version

4.0.dev [aec383a]

### System information

Linux Mint 20.2 kernel 5.4.0-89-generic x86_64, and Ubuntu 20.04 kernel 5.4.0-89-generic x86_64

### Issue description

When unchecking local_coords on GPUParticles2D, emmited particles seems to be placed at 2 x position of GPUParticles2D.
![Снимок экрана от 2021-10-23 17-47-07](https://user-images.githubusercontent.com/3165105/138561189-13c7f74c-fe29-46de-a40d-ac09ce58e432.png)

### Steps to reproduce

1. Create GPUParticles2D, assign ParticlesMaterial;
2. Uncheck local_coords;
3. Place GPUParticles2D at any non-zero position.

### Minimal reproduction project

[Particle_test.zip](https://github.com/godotengine/godot/files/7403141/Particle_test.zip)

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/56892, which has more information about the problem at hand.
