### ISSUE TITLE
Node::add_child is extremely inefficient when running inside the editor

### ISSUE THREAD

**Issue by 0x0ACB** [godotengine/godot#54177]
### Godot version

3.x and 4.x maybe all

### System information

Windows 10, Ubuntu 20.4 LTS

### Issue description

I was having some issues importing scenes with a semi large amount of  (direct child) Nodes (4000). Using Visual Studio profiling I found that the function costing 96.7% of that time was `Node::add_child` which I found extremely curious since I was constructing whole meshes before that which only took up 0.5% of the time. Digging a bit deeper the issue stems from `Node::_generate_serial_child_name` which will ALWAYS iterate over ALL children at least once! In the case there is already a child with the name assigned to the Node this may happen even more often.

An easy fix for this would be to use a `Set` with all child names for the current Node; reducing the amount of lookups needed. I would submit a pull request for this but I am not sure for which branch I should do this (this affects at least 3.x and 4.x and I would like to see this fixed in the version that can be downloaded directly from the godot Website [3.3.4]).

### Steps to reproduce

Generate a lot of direct child nodes in an editor (import) script.

**Comment by KoBeWi** [comment]
So I think the problem here is `node_hrcr` variable that forces the "legible unique names" globally in the editor. It should be resolved by #54072 (didn't read the whole discussion though)
