### ISSUE TITLE
in the viewport is not working middle mouse button

### ISSUE THREAD

**Issue by OlexiyKravchuk** [godotengine/godot#5417]
After the instance in a node (viewport), the scene in which you want to process, pressing the middle mouse wheel, it stops working, but all other input events, it seems to work fine ...

**Comment by akien-mga** [comment]
Can someone reproduce this issue?

**Comment by OlexiyKravchuk** [comment]
in this topic, I attempt to solve this problem, but until now there remained unsolved problems ...
https://www.facebook.com/groups/godotengine/permalink/798483630288233/

**Comment by bojidar-bg** [comment]
Is/was this issue valid?

**Comment by karroffel** [comment]
probably related to #7453

**Comment by bojidar-bg** [comment]
@karroffel No it isn't, see the date :open_mouth:

**Comment by karroffel** [comment]
This was fixed long ago, closing :)
