### ISSUE TITLE
Vulkan: SDFGI reflect wrong with depth texture read

### ISSUE THREAD

**Issue by ywaby** [godotengine/godot#54176]
### Godot version

4.0 dev

### System information

debian stable, GTX1050TI, vulkan

### Issue description

SDFGI reflection is not right with reading depth texture in shader. 

![sdfgi](https://user-images.githubusercontent.com/12198203/138583360-fd8157c6-46d4-4f17-af46-8c5b59cc74fa.png)
![bug](https://user-images.githubusercontent.com/12198203/138583356-2ee0ec3f-f91a-41da-9448-7892f7c03c8a.png)

### Steps to reproduce

1.  enable sdfgi.
2. read depth texure in shader.

### Minimal reproduction project

[Uploading godot.zip…]()

**Comment by ODtian** [comment]
Any update? it seems still a bug in 4.0.1.stable.

**Comment by Calinou** [comment]
Reading depth texture makes the material transparent. SDFGI does not support sharp reflections on transparent materials, only rough reflections (the same as the ones you get with roughness >= 0.2).
