### ISSUE TITLE
GDScript 2.0: Accessing inherited signals and functions as members result in an "Identifier not found" error

### ISSUE THREAD

**Issue by Riteo** [godotengine/godot#54172]
### Godot version

v4.0.dev.custom_build [aec383a83]

### System information

Arch Linux 5.14.14

### Issue description

Accessing any signal/method as a member returns a parse error when running the script.
Example:

parent.gd:
```
extends Node
class_name Parent

signal parent_signal
```

child.gd:
```
extends Parent

func ready():
	# Errors on execution.
	parent_signal.connect(some_function.bind())

func some_function():
	print("Some behaviour.")
```

See the MRP for a more "realistic" and commented example.

Although not showcased, it should be noted that the old syntax works fine (`Object::connect` and `Object::emit_signal`, `Object::call` and similar basically).

I tried the best I could to fix it myself, but I'm way too inexperienced with the GDScript engine to fix this issue, nonetheless I collected some interesting information that could help whoever is capable of putting their hands in the compiler:

There is proper autocompletion (when it doesn't show its usual quirks anyway), so it means that the parser itself is working fine enough and according to my research (read: banging my head on my keyboard with GDB open for a week) all it does is just parsing a single class (but not local classes, which are interpreted as some sort of member) without accounting for inheritance, which is resolved by the compiler itself.

The real issue seems to stem from this line in `gdscript_compiler.cpp`:
https://github.com/godotengine/godot/blob/b2ab5cb504cef1ffe229523d63b997d5306afce3/modules/gdscript/gdscript_compiler.cpp#L291.

If we follow this variable a bit we can find what this codegen.class is:
https://github.com/godotengine/godot/blob/b2ab5cb504cef1ffe229523d63b997d5306afce3/modules/gdscript/gdscript_compiler.cpp#L1885
https://github.com/godotengine/godot/blob/b2ab5cb504cef1ffe229523d63b997d5306afce3/modules/gdscript/gdscript_compiler.cpp#L2410
https://github.com/godotengine/godot/blob/b2ab5cb504cef1ffe229523d63b997d5306afce3/modules/gdscript/gdscript_compiler.cpp#L2579
https://github.com/godotengine/godot/blob/b2ab5cb504cef1ffe229523d63b997d5306afce3/modules/gdscript/gdscript_compiler.cpp#L2562

It's the parser class! This is the only case in this method (aside from global classes and lambdas) which uses it, as can be seen here in other ones:
https://github.com/godotengine/godot/blob/b2ab5cb504cef1ffe229523d63b997d5306afce3/modules/gdscript/gdscript_compiler.cpp#L242-L258
https://github.com/godotengine/godot/blob/b2ab5cb504cef1ffe229523d63b997d5306afce3/modules/gdscript/gdscript_compiler.cpp#L260-L262

So why isn't the script being used? The issue apparently relies on the fact that there isn't some proper "conversion" between a parsed class and a proper script object in this regard. The function responsible for this is `GDScriptCompiler::_parse_class_level` which does properly include the parent class' members as can be seen there:
https://github.com/godotengine/godot/blob/b2ab5cb504cef1ffe229523d63b997d5306afce3/modules/gdscript/gdscript_compiler.cpp#L2209

But going even deeper in this mess reveals that, despite being accessed as such, they are never added to the actual members of the script!
https://github.com/godotengine/godot/blob/b2ab5cb504cef1ffe229523d63b997d5306afce3/modules/gdscript/gdscript_compiler.cpp#L2315-L2330

Notice how the only variable changed from this operation is `GDScript::_signals`, which is what is actually used for `Object::connect` and `Object::emit_signal`, as they both call `GDScript::has_script_signal` in their logic:
https://github.com/godotengine/godot/blob/b2ab5cb504cef1ffe229523d63b997d5306afce3/modules/gdscript/gdscript.cpp#L1066-L1079

Notice also how this logic "works around" this situation by calling its `base`'s own `has_script_signal` method.

Now this is where everything starts to get kinda fuzzy and, honestly, out of my capabilities. At this point I already debugged *a lot* this complex piece of code which, at least to me, looks like it has built up some old behaviour around some quirks that are, AFAICT, pretty much as old as Godot as we know it:
![old stuff](https://user-images.githubusercontent.com/31065808/138574345-b20adaa7-4c14-4347-adcd-aa1c19d0df20.png)

I have no idea how signals are handled internally _at all_ with this new syntax. Are they objects now? Were they one all along? I tried looking at where the compiled bytecode went, but it started getting way too out of hand for me. I tried adding them as if they were actual properties, and while it allowed them to be properly compiled (probably in the wrong way) it quickly errored out with an `UNITIALIZED` error of some sort, so there's clearly more going on.

And that's it, this is where I gave up. I hope I didn't give out useless or wrong information and that I might have helped @vnen or whoever knows better how this (at least to my eyes) very complex module works.

This certainly isn't a "brief description" lol.

### Steps to reproduce

1. Open up the MRP in the editor
2. Start the project
3. Notice it erroring in `cool_vending_machine.gd`
4. Follow its comments to continue in the reproduction (commenting the broken lines basically)
5. Notice that accessing inherited methods/signals as members gives out parser errors about identifiers not being found ([although they come from the compiler](https://github.com/godotengine/godot/blob/b2ab5cb504cef1ffe229523d63b997d5306afce3/modules/gdscript/gdscript_compiler.cpp#L372))

### Minimal reproduction project

[signal-and-function-inheritance-issue-mrp.zip](https://github.com/godotengine/godot/files/7403864/signal-and-function-inheritance-issue-mrp.zip)

**Comment by barbaros83** [comment]
i can confirm this, have the same problem

**Comment by AttackButton** [comment]
Ok. I can confirm this. The solution is to use the `self`  keyword (`self.signal_name.emit()` / `self.signal_name.connect(func_name)` )in the derived class. 

The signal created in the base class is there in the children, you just can't use it without `self`, because you cannot create another signal with the same name.

Maybe it's intentional for GDScript 2.0? The problem is that I think this situation only happens with signals, not with functions or properties.

**Comment by Riteo** [comment]
@AttackButton I didn't try replicating this issue with properties, but I can tell you that functions have the same issue as signals (at least when I made the MRP), probably they share some code AFAICT.

**Comment by strank** [comment]
Just ran into this, and at least functions now work with a build from yesterday.

Signals still result in the compiler error. Testing script (`godot --headless -s ...`):

```
extends SceneTree


class HasSignal:

    var child_can_access_this = true

    signal but_not_the_signal

    func can_access():
        pass


class ParentHasSignal:
    extends HasSignal

    func test():
        print(child_can_access_this) # works
        self.but_not_the_signal.emit() # works
        #but_not_the_signal.emit() # uncomment for compiler error
        self.can_access()
        can_access() # works


func _init():
    ParentHasSignal.new().test()
    quit()
```
