### ISSUE TITLE
Feature Request: Tile Index Visible In Editor

### ISSUE THREAD

**Issue by Norrolith** [godotengine/godot#5420]
I would like to be able to see the tile index of a tile from the tilemap editor.
By tile index I mean the integer value I would use in the third argument of set_cell.
This should be an easy feature, but one i will find very useful.

**Comment by samuelgrigolato** [comment]
Do you mean something like this?

![tile index](https://cloud.githubusercontent.com/assets/352108/16363347/cf46aaba-3b9d-11e6-9b13-ce3964f58bc9.png)

**Comment by Norrolith** [comment]
Yeah, that looks good. maybe move the number off the graphic so it doesn't blend in on gray tiles.

**Comment by samuelgrigolato** [comment]
Another option would be to add a prefix to the tile name, i.e: "1. Box", "2. Floor" etc. What do you think?

**Comment by vnen** [comment]
I'm pretty sure that tiles indices start at zero.

**Comment by Norrolith** [comment]
They do appear to do so. Thankfully my tiles also now appear to be appearing in order.

**Comment by samuelgrigolato** [comment]
@Norrolith please take a look and tell me what you think. Should I do anything differently or can I open a PR?

![demo](https://cloud.githubusercontent.com/assets/352108/16365443/bca095cc-3bd6-11e6-84d8-e47609bc9acc.png)

**Comment by Norrolith** [comment]
That looks perfect. Thank you all.

**Comment by bojidar-bg** [comment]
@samuelgrigolato I think it might look better if you replace the dot with a dash, but check for yourself which character suits it best :)

**Comment by samuelgrigolato** [comment]
@Norrolith could you please expand on that alternative tile viewing mode? I'm afraid I'm not aware of it =D. A screenshot would help a lot ^^.

@bojidar-bg I think you are right, here is the dash version of it:

![dash](https://cloud.githubusercontent.com/assets/352108/16398229/9a84ddbc-3c9f-11e6-9a23-9a4b9f04711e.png)

**Comment by Norrolith** [comment]
![godotenginescreenshot](https://cloud.githubusercontent.com/assets/9922379/16401670/101f6e0a-3cac-11e6-95cd-e9dc58639616.png)
The display as list option. It seems to be absent in your build.

**Comment by vnen** [comment]
Seems that the list view was removed by #4006.

**Comment by Norrolith** [comment]
Ah, I'm a build behind. pardon.
