### ISSUE TITLE
Saving a cube map using "ResourceSaver.save()" doesn't work

### ISSUE THREAD

**Issue by DataPlusProgram** [godotengine/godot#54202]
### Godot version

3.3.3 stable, 3.3.4 stable, 3.4.rc1

### System information

Windows, Linux(Ubuntu)

### Issue description

Trying to save a cube map resource using ResourceSave.save() doesn't work.

On Windows a 0 byte .tres file is created and the program crashes

On Linux it creates the resource and doesn't crash but the images aren't on it and will give the following error:

```
E 0:00:00.942   _write_resource: Resource was not pre cached for the resource section, bug?
  <C++ Error>   Method failed. Returning: "null"
  <C++ Source>  scene/resources/resource_format_text.cpp:1373 @ _write_resource()
  <Stack Trace> Node.gd:17 @ createSkyMat()
                Node.gd:4 @ _ready()
```
The exact same script WILL work if you set it to a EditorScript and run it using Ctrl+Shift+X.
It will create the resource and work fine.

### Steps to reproduce

The attached project uses the following simple script:
```
extends Node

func _ready():
	createSkyMat()

func createSkyMat():
	
	var top = load("res://icon.png").get_data()
	var bottom = load("res://icon.png").get_data()
	var left = load("res://icon.png").get_data()
	var right = load("res://icon.png").get_data()
	var front = load("res://icon.png").get_data()
	var back = load("res://icon.png").get_data()

	var cubeMap = createCubemap(left,right,top,bottom,front,back)
	
	print(ResourceSaver.save("res://cubemap.tres",cubeMap))
	
	return

func createCubemap(left,right,top,bottom,front,back):
	var cubemap = CubeMap.new()
	cubemap.set_side(0,left)
	cubemap.set_side(1,right)
	cubemap.set_side(2,bottom)
	cubemap.set_side(3,top)
	cubemap.set_side(4,front)
	cubemap.set_side(5,back)
	return cubemap
```

If you set it to and editor script using the following code and run it with Ctrl+Shift+X it will work correctly.

```
tool
extends EditorScript

func _run():
	createSkyMat()

func createSkyMat():
	
	var top = load("res://icon.png").get_data()
	var bottom = load("res://icon.png").get_data()
	var left = load("res://icon.png").get_data()
	var right = load("res://icon.png").get_data()
	var front = load("res://icon.png").get_data()
	var back = load("res://icon.png").get_data()

	var cubeMap = createCubemap(left,right,top,bottom,front,back)
	
	print(ResourceSaver.save("res://cubemap.tres",cubeMap))
	
	return

func createCubemap(left,right,top,bottom,front,back):
	var cubemap = CubeMap.new()
	cubemap.set_side(0,left)
	cubemap.set_side(1,right)
	cubemap.set_side(2,bottom)
	cubemap.set_side(3,top)
	cubemap.set_side(4,front)
	cubemap.set_side(5,back)
	return cubemap
```

### Minimal reproduction project

[skyboxTest.zip](https://github.com/godotengine/godot/files/7406207/skyboxTest.zip)

**Comment by Ithamar** [comment]
This commit also fixes #34312 and a slew of other TextureLayered related tickets that have been open for a long time. Great to see this fixed! 🎊

**Comment by Calinou** [comment]
> This commit also fixes #34312 and a slew of other TextureLayered related tickets that have been open for a long time. Great to see this fixed! confetti_ball

https://github.com/V-Sekai/godot/commit/2ba3561e992fd4b2920518439068ca43ec1e51d9 doesn't apply cleanly on latest `master` anymore. Do you have a rebased version of that commit? If so, please open a pull request against `master` :slightly_smiling_face:

**Comment by Ithamar** [comment]
> I just checked locally and [V-Sekai@2ba3561](https://github.com/V-Sekai/godot/commit/2ba3561e992fd4b2920518439068ca43ec1e51d9) doesn't apply cleanly on latest `master` anymore. Do you have a rebased version of that commit? If so, please open a pull request against `master` 🙂

I actually tested on `3.x`, not on `master` yet. If it can wait till tomorrow, I can have a look at that.

**Comment by Ithamar** [comment]
> I actually tested on `3.x`, not on `master` yet. If it can wait till tomorrow, I can have a look at that.

@Calinou : I tested this on master, but I think there's more broken for `TextureLayered` there, won't have time until the weekend to look into that though 😢

**Comment by Ithamar** [comment]
I've done some investigation but in `4.0beta1` it seems using `ResourceSaver.save` on any of the `TexturedLayered` classes is even more broken then in `3.x`. I think whoever is responsible for the 4.0 changes needs to sort this out before we can look at fixing the "old" issues....

**Comment by Calinou** [comment]
> I've done some investigation but in `4.0beta1` it seems using `ResourceSaver.save` on any of the `TexturedLayered` classes is even more broken then in `3.x`. I think whoever is responsible for the 4.0 changes needs to sort this out before we can look at fixing the "old" issues....

See https://github.com/godotengine/godot/issues/66192 and https://github.com/godotengine/godot/issues/65393.

**Comment by YuriSizov** [comment]
Fixed by https://github.com/godotengine/godot/pull/71394.
