### ISSUE TITLE
ConcavePolygonShape3D property `backface_collision` does not disable backface collision between bodies

### ISSUE THREAD

**Issue by briansemrau** [godotengine/godot#54208]
### Godot version

4.0.dev (80801e5f66)

### System information

W10

### Issue description

I'm creating a static object with a **ConcavePolygonShape3D** created from a mesh, using `Mesh::create_trimesh_shape`. When setting the shape property `backface_collision`, whether to true or false, collision behavior does not change.

With the property set to `false`, I expect objects to pass through the interior of the mesh (even if it produces nonphysical motion). Set to `true`, I expect collision both ways, which is what currently occurs.

![image](https://user-images.githubusercontent.com/6376721/138616426-bdad04b6-9613-4062-8c68-42011dcc59eb.png)

Dynamic ball should not be at rest inside the static cube:
![image](https://user-images.githubusercontent.com/6376721/138616386-db28c51e-859e-4ea7-995e-1aff020bfda8.png)

### Steps to reproduce

Create a ConcavePolygonShape3D.
`backface_collision` is false by default.
Watch objects collide with the backside of faces.

### Minimal reproduction project

[BackfaceColReprod.zip](https://github.com/godotengine/godot/files/7406392/BackfaceColReprod.zip)

**Comment by briansemrau** [comment]
cc @pouleyKetchoupp

**Comment by pouleyKetchoupp** [comment]
Looks like a regression from #50240, now some vertical contacts are generated when they shouldn't. I'll find a better way to keep edge contacts functional without messing with contacts against the faces.

**Comment by briansemrau** [comment]
It's not just vertical contacts. I noticed this issue when creating terrain meshes. If the player rigid body is on the interior of the mesh, I always collide.

**Comment by Robert-K** [comment]
I'm having the exact same issue again in Godot 4.4.1 when using default Godot physics.
Switching the physics engine to Jolt results in the expected behaviour.

Seems like there was another regression 👀
