### ISSUE TITLE
Font Outline gaps won't close up when Outline size is increased

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#54214]
### Godot version

v4.0.dev.20211015.official [f113dc986]

### System information

Windows 64bit, Nvidia dedicated 765M

### Issue description

https://user-images.githubusercontent.com/47016402/138618163-1c1c437c-923c-445a-85f9-b8771b088b52.mp4

### Steps to reproduce

Increase the Outline size of a Font.

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by KoBeWi** [comment]
> Outline is not intended to be used with the large radius.

We should have this documented.

**Comment by ARez2** [comment]
> > We need to make it much easier to set Font and font size. By for example allowing the user to also set it in a Toolbar.
> 
> A toolbar like this is a good idea. We should be able to extract font family names and bold/italic style tags directly from the font metadata (it's not implemented but should be easy to do), and automatically build a list of all project fonts without relying on filenames and locations.
> 
> Edit: `get_font_name` and `get_font_style` implementation PR - #54257

Is that toolbar idea closed by:
#54372 ?
