### ISSUE TITLE
CanvasGroup clips Font outline

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#54213]
### Godot version

v4.0.dev.20211015.official [f113dc986]

### System information

Windows 64 bit, Nvidia dedicated 765M

### Issue description

CanvasGroup somehow clips the outline of a font:

https://user-images.githubusercontent.com/47016402/138617797-207b637e-4602-413b-bce3-aaa05a99a829.mp4

### Steps to reproduce

Add Font with outline to CanvasGroup

**Comment by golddotasksquestions** [comment]
Tested and issue still present in Alpha7.

**Comment by clayjohn** [comment]
This is what the ``fit_margin`` property of the CanvasGroup is meant for. Increase ``fit_margin`` to be at least as many pixels as the outline is wide. 

I will have an update to the docs ready shortly so this is actually documented.
