### ISSUE TITLE
One-way collision with KinematicObject doesn't work above a certain angle.

### ISSUE THREAD

**Issue by Ovnuniarchos** [godotengine/godot#5423]
**Debian testing - Godot version: 2.1alpha commit:544b196d77428f5b3362f1b3a3b7f2be3ad4164a**
Kinematic objects don't detect static objects marked with on-way collision, when the angle between that movement vector and the one-way vector is below a certain angle.

Below, a project demonstrating this problem.
[BadKino.zip](https://github.com/godotengine/godot/files/333507/BadKino.zip)

**Comment by akien-mga** [comment]
Is it the same as #4846?

**Comment by Ovnuniarchos** [comment]
It seems so.

**Comment by reduz** [comment]
It is the same as 4846, but will fix properly in 3.0, as it requires breaking compatibility
