### ISSUE TITLE
ViewportContainer changes size when opened in editor

### ISSUE THREAD

**Issue by eazrael** [godotengine/godot#54242]
### Godot version

3.3.4, 3.4.0-rc1

### System information

Windows 10 64bit, AMD Vega 64, GLES3

### Issue description

I am quite new to godot, but I think this is not the intended behaviour. 

I have a ViewportController which changes its size when the scene is opened and anything triggering a save will write these new values to the scene file. The impact of these new values is that the viewport is shown distorted when the scene is run until a window resize happens, after which the viewport content is shown correctly. Manually resetting these values fixes the distortion, but the next time the scene is opened the wrong values, which is quite annoying.

I stripped 
- Control
  -  VBoxContainer
    - HBoxController
      - Label (for demonstration)
    - ViewportController
      - Viewport
        - Label (for demonstration)

The upper Label is set to height 20px. The ViewportController is set to Anchor (0, 0, 1, 1) with minimum size (100, 100) to take up the remaining size of the window. The Viewport is set to size (1024, 600).
It's running in the default 1024x600 window. 

When saved ViewportController and Viewport have these settings in the scene file: 

```
[node name="ViewportContainer" type="ViewportContainer" parent="VBoxContainer"]
anchor_right = 1.0
anchor_bottom = 1.0
rect_min_size = Vector2( 100, 100 )
size_flags_horizontal = 3
size_flags_vertical = 3
stretch = true
__meta__ = {
"_edit_use_anchors_": false
}

[node name="Viewport" type="Viewport" parent="VBoxContainer/ViewportContainer"]
size = Vector2( 1024, 600 )
handle_input_locally = false
usage = 0
render_target_update_mode = 3
```

When opening, this changes to 

```
[node name="ViewportContainer" type="ViewportContainer" parent="VBoxContainer"]
margin_top = 24.0
margin_right = 1024.0
margin_bottom = 600.0
rect_min_size = Vector2( 100, 100 )
size_flags_horizontal = 3
size_flags_vertical = 3
stretch = true
__meta__ = {
"_edit_use_anchors_": false
}

[node name="Viewport" type="Viewport" parent="VBoxContainer/ViewportContainer"]
size = Vector2( 1024, 576 )
handle_input_locally = false
usage = 0
render_target_update_mode = 3
```
I have no idea where this 24px top margin comes from.

Maybe related to #19252 or #38573 ?

### Steps to reproduce

1. Unzip the minimal project attached
2. Check MainWindow.tscn content
3. Open project in godot
4. Save (it's not marked with an asterisk for changed content)
5. Compare new MainWindow content

### Minimal reproduction project

[viewportissue.zip](https://github.com/godotengine/godot/files/7413224/viewportissue.zip)

**Comment by eazrael** [comment]
@pycbouh, thnaks for the explanation. These options are indeed confusing. I think I got it now right.

**Comment by pycbouh** [comment]
That's great to hear! Is the issue no longer valid then?

**Comment by eazrael** [comment]
Sorry, but yes. Waiting for Godot.. 4.0 ;-)
