### ISSUE TITLE
[4.0] libnv_vulkan_wapper.so error

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#54259]
### Godot version

v4.0.dev.20211015.official [f113dc986]

### System information

Debian 11

### Issue description

When start:
```
Godot Engine v4.0.dev.20211015.official.f113dc986 - https://godotengine.org
Can't open bumblebee display.
ERROR: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
	loader_scanned_icd_add: ICD libnv_vulkan_wrapper.so.1 doesn't support interface version compatible with loader, skip this ICD.
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 139067664
   at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:157)
MESA-INTEL: warning: Ivy Bridge Vulkan support is incomplete
Vulkan API 1.2.162 - Using Vulkan Device #0: Intel - Intel(R) HD Graphics 4000 (IVB GT2)
```
 
ps:. I use already vulkan drivers with DOTA2 (set it in video settings)

### Steps to reproduce

NA

### Minimal reproduction project

NA

**Comment by clayjohn** [comment]
This isn't a Godot error. This is an information message from your GPU driver. Typically this comes from having drivers configured from a device that is not connected (which can happen if you have hybrid graphics on a laptop, for example)
