### ISSUE TITLE
GDScript 2.0: `@export_node_path()` does not support custom classes

### ISSUE THREAD

**Issue by mrawlingst** [godotengine/godot#54284]
### Godot version

4.0.dev (f113dc986)

### System information

Windows 10

### Issue description

When trying to use the new annotation for export variables `@export_node_path()`, it does not appear to support custom classes defined by the user, only predefined classes/nodes (i.e. Label, Sprite, etc.)

### Steps to reproduce

1. Add a node as root
2. Create new script and attach to the root - `Main.gd`
3. Add a new *Label* node under root
3. Create a new script in Filesystem view - `TestClass.gd`
4. Open `TestClass.gd` script in editor
5. Give it a class name: `class_name TestClass` just under `extends <NODE>`
6. Open `Main.gd` script in editor
7. Add an export variable: `@export_node_path(Label) var labelNodePath = NodePath()`
8. Add another export variable: `@export_node_path(TestClass) var customNodePath = NodePath()`
9. Add a new TestClass node under root
10. Save scene
11. Select root node and observe both export property
        - `Label Node Path` - all but one node is greyed out, the singular node is a Label and can be selected
        - `Custom Node Path` - all nodes are greyed out and no nodes are selectable

**_The expected result is to be able to select the custom node (TestClass) inside NodePath window._**

### Minimal reproduction project

[ExportNodePathCustomClass.zip](https://github.com/godotengine/godot/files/7421236/ExportNodePathCustomClass.zip)

**Comment by poiati** [comment]
I was exploring this issue. This is related to https://github.com/godotengine/godot/issues/21789. The engine does not recognize GDScripts as named classes, it fallbacks to the first native node in the hierarchy tree. I'm wondering how we should move forward here.

**Comment by stephannv** [comment]
I think this can be closed. I downloaded the MRP and it's already possible to select the custom node.

Note: It is necessary to change `TestClass` to `"TestClass"` due this issue: https://github.com/godotengine/godot/issues/72192
