### ISSUE TITLE
GDScript 2.0: Compound primitives with setters cannot be modified without replacing the whole value

### ISSUE THREAD

**Issue by Razoric480** [godotengine/godot#54289]
### Godot version

4.0dev, 8c162f4a7ba0f542cd7e9fbbe30f004504cc0809

### System information

Windows 10

### Issue description

If you have a property with properties (Vector2, Rect2, etc) that has a setter, I.E.
```gdscript
var rect: Rect2:
	get:
		return rect
	set(value):
		rect = value
```
and you try to modify its contents by calling its properties, I.E.:
```gdscript
rect.position.x = 50
rect.size.y = 50
```
the properties aren't actually changed and the setter is not called unless you go and change the whole property, I.E.:
```gdscript
var new_rect = rect
new_rect.position.x = 50
new_rect.size.y = 50
rect = new_rect
```

### Steps to reproduce

```gdscript
extends Node

var rect: Rect2:
	get:
		return rect
	set(value):
		rect = value

func _ready():
	rect.position.x = 50
	rect.size.y = 50
	print(rect) # [P: (0, 0), S: (0, 0)]

	var new_rect = rect
	new_rect.position.x = 50
	new_rect.size.y = 50
	rect = new_rect
	print(rect) # [P: (50, 0), S: (0, 50)]
```

**Comment by cdemirer** [comment]
Currently, the MRP works if you remove the getter, even if the setter remains. The remaining issue is probably related to this: #54829
