### ISSUE TITLE
await keyword bug

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#54299]
### Godot version

4.0.dev.calinou[92a2380d9]

### System information

Window 10

### Issue description

GDScirpt no error:
![1](https://user-images.githubusercontent.com/35988767/139037801-77ad5d68-7a56-47db-826f-4d9b73aa4c02.PNG)

 but report:
Trying to call an async function without "await".
on runtime
![2](https://user-images.githubusercontent.com/35988767/139037830-e378f5ec-b31c-4943-9d28-f8b7e3cf8a20.PNG)

### Steps to reproduce

run the reproduction

### Minimal reproduction project

[AwaitTest.zip](https://github.com/godotengine/godot/files/7424852/AwaitTest.zip)

**Comment by CsloudX** [comment]
hello, any update this?

**Comment by BenjaminSchulte** [comment]
Seems to be fixed on latest master branch. (b2a5b55533b8c4c543eb33b028a4ae5da99b070c)
