### ISSUE TITLE
You can no longer enter in the editor a character that requires ALT + SHIFT (`[`, `]`, `\`, …)

### ISSUE THREAD

**Issue by fabriceci** [godotengine/godot#54303]
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

4.0 Dev (8c162f4)

### System information

macOS 11.5

### Issue description

On mac some character that we use for programming required to do `ALT` + `SHIFT` + `some key`:
- `[` and `]` =   `ALT` + `SHIFT` + `(` or `)`
- `\` =   `ALT` + `SHIFT` + `/`
- etc.

This worked fine in 3.x:

![before](https://user-images.githubusercontent.com/6397893/139061984-e8cb5e56-6698-4752-9011-af13e871c5ce.gif)

Now is broken:

![after](https://user-images.githubusercontent.com/6397893/139062138-0b9237d1-7d80-4b32-8e25-1d3c5f0c0bc2.gif)

### Steps to reproduce

Open the editor, try to enter a `[` on a mac keyboard.

### Minimal reproduction project

/

**Comment by ZX48developer** [comment]
Still present in alpha 4. This could lead on less testing on mac os. Try to program without @#[]{}\|
I'm using a old linux machine to test godot 4 because it's not usable on mac os

**Comment by slasktotten** [comment]
I just ran into this on alpha 4 as well.

**Comment by dcerjan** [comment]
Can confirm this also occurs on alpha 5 on Mac OS.
