### ISSUE TITLE
Menu dropdowns/Tabs only show up if double clicked in macOS Monterey

### ISSUE THREAD

**Issue by knadoor** [godotengine/godot#54306]
### Godot version

3.4 RC2 Standard Build

### System information

macOS Montery 12.0.1

### Issue description

**There are several issues:**

1. The menu bar dropdowns (i.e., Project, Editor, Help etc.) only show if the user double clicks on them, a single click won't work.

2. In the "About Godot" window, you need to double click on the tabs to switch between them, a single click won't work.

3. Any of the menu items, options within any boxes etc. only work if double clicked on.

These issues do not exist in version 3.3.4 under macOS or even in the Windows version of 3.4 RC2. Please refer to video down below.

### Steps to reproduce

As in the issue description above.

### Minimal reproduction project

N/A

**Comment by bruvzg** [comment]
This looks exactly like #8653 focus issue. Do you ever get this issue in the Project Manager or exported project? I suspect it might be related to the way Godot is starting a new editor process when the project is opened (it's starting the main bundle executable directly, not a bundle).

**Comment by NoFr1ends** [comment]
@bruvzg so far I only get it in the editor, never in the project manager or exported project

**Comment by bruvzg** [comment]
Here's a potential fix in the #54474 (link to the precompiled app bundle to the first comment), please check if it's working for you.

**Comment by akien-mga** [comment]
Fixed by #54474.

**Comment by knadoor** [comment]
Thank you all :)
Will be happy to test it in the next build.
