### ISSUE TITLE
Asset Library Images aren't being loaded due to https

### ISSUE THREAD

**Issue by kuhnchris** [godotengine/godot#54318]
### Godot version

3.3, 3.4-rc

### System information

Linux (arch), custom

### Issue description

When looking at screenshots in the asset library, the images are not being properly loaded.
![image](https://user-images.githubusercontent.com/761911/139126414-85d152c0-5f14-42e0-8351-148776076a87.png)
For example:  https://godotengine.org/asset-library/asset/1032
It loads fine in the browser, but if you look in the godot editor for that asset, the images ain't displayed properly.
There is also a very ominous "Invalid URL scheme: https://" in the Output, maybe this is connected?
![image](https://user-images.githubusercontent.com/761911/139126573-f0eb35b7-12e6-4d8e-8b11-9c7ba5608682.png)

### Steps to reproduce

Go to Asset Library, Search for "hex", click at "Hexgrid", check screenshots, see screenshots missing.

**Comment by kuhnchris** [comment]
So, to sum this up, the common consent would be to have the assetlib send a proper url to use instead of changing parse_url? (or at the very least improve error handling / checking in parse_url, but have assetlib / whatever is parsing assetlib send the correct URL)

**Comment by mhilbrunner** [comment]
Yes, this needs definitely to be fixed in the Assetlib.

Whether we improve error checking in parse_url() it mostly an additional concern (but wouldn't fixe this error, only provide a better error message :))

**Comment by mhilbrunner** [comment]
Closing this for now, as a bug on the Assetlib repository already exists:
https://github.com/godotengine/godot-asset-library/issues/204
