### ISSUE TITLE
Missing constructor `Basis(Vector3)`

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#54316]
### Godot version

4.0.dev.custom_build. 16edca841

### System information

Ubuntu 21.10 - Nvidia GTX 970, Gnome shell 40.4 X11

### Issue description

```
Basis(Vector3())
```
is now(since this week) not proper constructor

### Steps to reproduce

Above

**Comment by Calinou** [comment]
I can confirm this on 4.0.dev 1aef3a42b.

**Comment by akien-mga** [comment]
As I mentioned, this is not a bug, this was removed on purpose. `Basis(Vector3)` is not a natural constructor (there's no obvious conversion from a `Vector3` to a `Basis`. It used to be used to construct a basis from a set of Euler angle, which is now replaced by an explicit static `Basis.from_euler(Vector3)`.

Tests that use `Basis(Vector3)` should be changed.
