### ISSUE TITLE
GDScript 2.0: `await node.signal` does not treat member signals as signals and crashes

### ISSUE THREAD

**Issue by mrawlingst** [godotengine/godot#54322]
### Godot version

4.0.dev (f113dc9)

### System information

Windows 10

### Issue description

When trying to await a node's signal, it appears to treat the member signal as not a signal or coroutine and crashes the application.

`await node.tree_exited`

This is the warning that flags when it goes through the above code:
```
W 0:00:00:0482   "await" keyword not needed in this case, because the expression isn't a coroutine nor a signal.
  <C++ Error>    REDUNDANT_AWAIT
  <Source>       FILE.GD:#
```

Please note - I have not attempted to use custom signals in this manner yet.

### Steps to reproduce

1. Add a node as root
2. Create new script and attach to the root (name it however you want)
3. Copy and paste the code at bottom of this section
4. Run this scene
5. Press either `1` or `2` and observe the application closing itself
    - Keep an eye on the label top left, notice how it always say `NOIDEA` until application closes
6. Comment out `await node.tree_exited` line and run scene again
    - Observe how it changes labels without any issues or crashes

```gdscript
extends Node

var node: Label = null

func _ready() -> void:
    load_new_label("NOIDEA")

func _unhandled_input(event: InputEvent) -> void:
    if event is InputEventKey && event.pressed:
        if event.keycode == KEY_1:
            load_new_label("LABEL 1")
        if event.keycode == KEY_2:
            load_new_label("LABEL 2")

func load_new_label(txt: String) -> void:
    if node:
        node.queue_free()
        # THIS CRASHES THE APPLICATION
        await node.tree_exited
        node = null

    node = Label.new()
    node.text = txt
    call_deferred("add_child", node)
```

### Minimal reproduction project

[AwaitNodeSignals.zip](https://github.com/godotengine/godot/files/7428765/AwaitNodeSignals.zip)

**Comment by Desmondchaser27** [comment]
A temporary "hack" to work around this right now is to simply connect the signal you want to 'await' on to the object itself.  It will generate a function to call on the signal.  Then write in the next line await on that function (which is only called on the signal being emitted)

Script example:
`
	connect("ready", _on_ViewportContainer_ready)
	await _on_ViewportContainer_ready()
	self.queue_free()
`

**Comment by vnen** [comment]
It seems there are two issues here: one is the wrong warning, the other is the crash. They are unrelated and ideally should be reported separately since fixing one won't fix the other.

**Comment by Chaosus** [comment]
@vnen then I can reopen my issue (for warning) - https://github.com/godotengine/godot/issues/54589
