### ISSUE TITLE
Check opaque pixel for TextureButton

### ISSUE THREAD

**Issue by mateusak** [godotengine/godot#5432]
A button can take a lot of forms, that are not always a square. But in TextureButton, that doesn't matter at all. If it's a triangle or a circle, it'll activate even when it's not in the texture itself. I suggest adding a "Check for opaque pixels" option in the TextureButton.

**Comment by bojidar-bg** [comment]
There is button mask as far as I can remember, isn't it so?

**Comment by vnen** [comment]
Yep, there's a Click Mask property for TextureButtons.

**Comment by akien-mga** [comment]
Closing since there is a button mask as mentioned above.
