### ISSUE TITLE
Load Errors window is not scaling properly (hidpi)

### ISSUE THREAD

**Issue by afiestas** [godotengine/godot#5436]
**Operating system or device - Godot version:**
Archlinux, godot from git

**Issue description** (what happened, and what was expected):
I was checking out the new hidpi support (kudos for that) and I noticed that one of the windows is not scaling

**Steps to reproduce:**
Make the Load Error window appear.
![godot](https://cloud.githubusercontent.com/assets/872727/16364678/56ee1012-3bed-11e6-85bb-9a472d7dc839.png)

**Link to minimal example project** (optional but very welcome):

**Comment by reduz** [comment]
I fixed this a while ago, though I can't find the commit
