### ISSUE TITLE
TextureButton does not interact with the mouse outside its parent rect size.

### ISSUE THREAD

**Issue by Andreas-Atomphi** [godotengine/godot#54408]
### Godot version

3.3 Stable

### System information

Ubuntu Linux.

### Issue description

I'm trying to make a diagonal scroll, as I don't know how to do this by moving the VBoxController component or the ScrollingContainer, I made each button take a different horizontal position according to its y axis - scroll_vertical of the ScrollContainer, but the buttons that are outside the rectangle do not respond to input, how can i change this?

### Steps to reproduce

ScrollContainer-> VBoxContainer -> TextureButtons

Script of Texture Buttons:
func _process(delta):
	var gp = rect_position
	var gp_sc = scroll_container.rect_position
	var offset = scroll_container.rect_pivot_offset
	rect_position.x = scroll_container.scroll_vertical - gp.y
	rect_position.x += offset.x

**Comment by Chaosus** [comment]
сс @Paulb23 (not sure whether it is a bug or not)

**Comment by pycbouh** [comment]
You can’t manually change position of controls inside of a container (VBox in this case). This code demonstrates an invalid approach. I recommend joining one of our [community platforms](https://godotengine.org/community) and asking for help with your project there. GitHub is only for bug reports.
