### ISSUE TITLE
Animations not blending properly in AnimationTree. Vertical position of the skeleton is affected. 

### ISSUE THREAD

**Issue by raiseledwards810** [godotengine/godot#54407]
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

4.0.dev

### System information

Windows 10 - 64 bit

### Issue description

The vertical position of a character seems to have some kind of offset when two different animations are blended together inside an Animation Tree. This is not exclusive to the Blend3 node.

![ezgif-1-c62e8a3e6dc8](https://user-images.githubusercontent.com/42452866/139515796-149f3ad7-9c26-4592-b8f3-6be261ff5b56.gif)

This behavior is not present in previous versions. I tested the same configuration using Godot 3.4 (beta 6). 
I imported the character model using the .glb file from the TPS Demo. The problem is present in custom characters too.

### Steps to reproduce

The following reproduction project showcases this behavior.

 - Open the "TPS Demo Robot Scene"

### Minimal reproduction project

[gODOT TEST.zip](https://github.com/godotengine/godot/files/7445608/gODOT.TEST.zip)

**Comment by TokageItLab** [comment]
Please check #54205.

**Comment by macryc** [comment]
Hi can I test this fix? The windows build under #54205 says it's expired...

**Comment by TokageItLab** [comment]
@macryc Well, a while recently, I think the project manager was having some issues lately. Now rebased #54205, can you checkout and build it, and do test?

**Comment by macryc** [comment]
> @macryc Well, a while recently, I think the project manager was having some issues. So now I rebased #54205, can you checkout and build it, and do test?

Just tested and I confirm that this PR fixes the issue. Thank you.

**Comment by Rodeo-McCabe** [comment]
I can confirm this issue is still present in 4.0 alpha 3

**Comment by Noiros** [comment]
Same for alpha 4
