### ISSUE TITLE
Continuous error spam when AABB of `FogVolume` has been resized

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#54412]
### Godot version

1b2cd9f2519d54c0cf9cf58939f09d7a6834f292

### System information

Windows 10

### Issue description

Attempting to change a scale of AABB of `FogVolume` result a continious error spam:

![fog_volume_resize_error](https://user-images.githubusercontent.com/3036176/139523877-c53c5c0c-951a-455d-acbf-b12f065d106b.gif)

The error is:

```
Basis must be normalized in order to be casted to a Quaternion. Use get_rotation_quaternion() or call orthonormalized() if the Basis contains linearly independent vectors.
```

### Steps to reproduce

Create a `FogVolume` and attempt to resize it.

### Minimal reproduction project

Too easy to reproduce.

**Comment by clayjohn** [comment]
My guess is that something changed with https://github.com/godotengine/godot/pull/54084 that I didn't catch. Fog Volumes don't use Quaternions anywhere, so I will have to investigate a bit to see where the issue is coming from.

**Comment by clayjohn** [comment]
Well, for one, it looks like ``_validate_property`` needs to contain a call to ``VisualInstance3D::_validate_property(property);``

Also it looks like calls to ``basis.get_rotation()`` should turn into ``basis.get_euler_normalized()``

I'll take a peek later and see if my suspicions are correct
