### ISSUE TITLE
Suggestion: "Add Node" and "Classes Reference" dialogs improvement

### ISSUE THREAD

**Issue by joelgomes1994** [godotengine/godot#5442]
Hello!
It's not an issue, but just a suggestion. The hierarchy in both Add Node and Classes dialogs are fine, but they have some problems of readability like some items having icons, and others not. The fact that some items don't have icons makes the alignment in the hierarchy pretty messy. Example:

![image](https://cloud.githubusercontent.com/assets/19820741/16365667/86b6a44a-3bdd-11e6-994e-ffd52f20d8bf.png)

I suggest four alternatives to this:

1: Removing icons (not a good idea, but at least it's said).
2: Put the icons in the right side of the words (making the words be aligned).
3: Making the items that don't have icons inherit one from the last parent that haves a icon (making the icons be aligned).
4: Adding a reference guideline in each level of hierarchy, making easier to read, like this:

![example_grid_reference](https://cloud.githubusercontent.com/assets/19820741/16365660/581f44ca-3bdd-11e6-830b-c2d9b8f59208.png)

Also, when the same dialogs are open, the tree is expanded by default, and sometimes is convenient to search category through category. Since there's a lot of items to scroll, and collapse one by one would be inefficient, a button to toggle expand/collapse all items in hierarchy (including the inner items) would be awesome.

I hope you consider this possibilities, that will surely make the interface cleaner.

**Comment by djrm** [comment]
All this has been fixed in the master branch, and will be available in Godot 2.1 (except for the level guide)

**Comment by vnen** [comment]
Yeah, you chose the worst example about nodes without icons. Only the ones that can't be instanced don't have icons. ToolButton is not one of them and it already has an icon in master.

And the first 3 suggestions are not good ideas. Inheriting icons will likely make it confusing (more than you think it is already).

Now the level guides might be helpful. There is already such thing for the Scene Tree, so I guess it can be added every tree list.

**Comment by joelgomes1994** [comment]
Nice to know that some of these things are going to be added in the future release! In the scene tree, the guideline would be even more useful, for sure, just like the code folding in script editor. Thanks!
( @vnen Legal, dois paulistas no mesmo tópico :P )

**Comment by vnen** [comment]
For reference, #5233 adds the level guides to the scene tree. In the scene tree it is opt-in and by so it should also be opt-in for other trees. I'm not sure if there should be an option for each possible tree or one option to rule them all.

(@joelgomes1994 :wink:)

**Comment by akien-mga** [comment]
All of this is implemented / improved in 2.1 AFAIK.
