### ISSUE TITLE
[Bullet] RigidBody.body_entered not always emitted for KinematicBody with infinite_inertia=false

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot#54436]
### Godot version

3.3.4.stable.custom_build.faf3f883d

### System information

Linux 5.14.8-arch1-1, GLES3, Nvidia 1080

### Issue description

When a `KinematicBody` uses `move_and_slide` with `infinite_inertia=true`, `RigidBody` objects will emit `body_entered` inconsistenly when colliding with them. It will emit sometimes, but misses a lot of collisions (usually less direct ones, where the KinematicBody tends to slide out of the way).

### Steps to reproduce

1. Open the example project
2. Run it, see `KinematicBody` printed, indicating that the `RigidBody` detected a collision
3. Change `infinite_inertia` to `false` in `KinematicBody.gd`
4. Run again, see `KinematicBody` is _not_ printed
5. Adjust the position of the `RigidBody` so it has a more direct collision with the `KinematicBody`
6. Run again, see `KinematicBody` is printed again

### Minimal reproduction project

[example.zip](https://github.com/godotengine/godot/files/7447644/example.zip)

**Comment by Calinou** [comment]
@rcorre Does this occur with GodotPhysics too?

**Comment by rcorre** [comment]
@Calinou no, GodotPhysics emits `body_entered`, and the `KinematicBody` also "resists" the `RigidBody` more.

https://user-images.githubusercontent.com/2496231/139583683-4e8ecb64-c7d5-4400-a90e-eca31091de92.mp4

**Comment by rcorre** [comment]
Oops, I forgot I reported this and duped it in #57407. I'll close this one, I think the example in the other is better.

**Comment by rcorre** [comment]
Also, in this one I said it didn't happen with Godot Physics, but in #57407 it did, which I do remember testing. Either I was wrong in this one or something changed between 3.3 and 3.4.
