### ISSUE TITLE
CSG's not on the current scene tab fail to render on project load

### ISSUE THREAD

**Issue by Einlander** [godotengine/godot#54445]
### Godot version

v3.3.4.stable.official [faf3f883d]

### System information

Windows 10 pro, GLES3, MSI RX 570 ARMOR OC 8 GB [21.9.1]

### Issue description

When you have a project with multiple scenes open that contain CSG's, any CSG that is not the tab that opens first will not render.

### Steps to reproduce

1. Make a project with at least 2 scenes.
2. Put a csg node in each of the scenes. Save the scenes
3. Make sure both tabs are open, then close the project.
4. Open project.

The csg's in the other tabs will not be rendered.

### Minimal reproduction project

[csg_render_bug.zip](https://github.com/godotengine/godot/files/7448365/csg_render_bug.zip)

**Comment by Calinou** [comment]
Can you reproduce this in an earlier version like 3.2.3? I wonder if this is related to the new BVH. You can also try playing with the BVH options in 3.3.4, or try 3.4rc2.

**Comment by Einlander** [comment]
3.3 stable is fine.
3.4.rc3 [1a1a45061] is still broken
Adding a script that moves or rotates the node in the _ready() or _process() moves the node, but it does not make them appear.

**Comment by Einlander** [comment]
Could it be related to [46610]

**Comment by cdemirer** [comment]
This currently happens on master, but not on 3.4 because it seems 3.4 doesn't auto-open scenes on project load.

**Comment by Calinou** [comment]
> because it seems 3.4 doesn't auto-open scenes on project load.

[**Restore Scenes On Load** is enabled by default in `master`, but not in `3.x`.](https://github.com/godotengine/godot/pull/52601)

**Comment by hoontee** [comment]
Caused by #52647.
