### ISSUE TITLE
HTML5: set Request.credentials value to include sending cookies for cross-origin requests too

### ISSUE THREAD

**Issue by fenix-hub** [godotengine/godot#54447]
### Godot version

3.3.4.stable

### System information

Windows 11, (Chrome/Firefox)

### Issue description

When making HTTP requests to a server, Godot is not sending Cookies in the request on HTML5.
Since Godot is currently using `fetch` APIs on html5, and the `Cookie` header is a [forbidden one](https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name) for that, it creates inconsistency between desktop-client requests and browser ones.
The `Cookie` header just works fine on Windows and Linux, and I'm not personally aware of an eventual browser-side issue or expected behaviour, so this might be a useless issue, but I hope it's not since I've tried multiple solutions and couldn't come up with a working one.

### Steps to reproduce

Since Cookie is a forbidden header, here's some steps I tried to reproduce the issue. I hope they are correct.
1) Start up a simple http server with python (or whatever service at your choice, in order to have a server on localhost). I'll use [livehttp](https://github.com/zk4/livehttp) since allows cross origin (**important**).
```python
➜ python -m livehttp 7000
server running at http://localhost:7000
...
```
2) Set a Cookie from the web console of the godot project running  
![Immagine 2021-10-31 133545](https://user-images.githubusercontent.com/45271396/139583472-ffaaf184-07fb-4f2c-aa4e-bae1f6f625ef.png)
![Immagine 2021-10-31 130738](https://user-images.githubusercontent.com/45271396/139583483-c03a38ae-a93d-4bdb-9a94-ff4d9b3d725c.png)
3) Make sure cookie is allowed  
![Immagine 2021-10-31 130908](https://user-images.githubusercontent.com/45271396/139583494-54d62335-e925-4eb3-a30e-29e3af548b12.png)
4) Make an httprequest using the HTTPRequest to the mock server like this one, with a `Cookie` header and an additional custom one  
```gdscript
$HTTPRequest.request("http://localhost:7000", ["Cookie: session_abc=xxx", "X-SDK-Version: xxx"], true, HTTPClient.METHOD_GET)
```
5) The cookie header together with the custom one will be correctly sent to the server on desktop platforms, but not on html5 builds, which will only send *non-forbidden* headers. The session cookie will be ignored as well.  
![Immagine 2021-10-31 130811](https://user-images.githubusercontent.com/45271396/139583616-f5f9631f-0f0a-4668-88c6-9b94ca0e154a.png)

### Minimal reproduction project

[appwrite-sdk.zip](https://github.com/godotengine/godot/files/7448864/appwrite-sdk.zip)

Here's a reproduction project.
This project implements an SDK I wrote to communicate with an [Appwrite](https://appwrite.io/) instance, so this requires having one running in docker locally.
Appwrite uses cookie authentication: the server sets the cookie and it is expected to be received in the request headers.
It works for desktop platforms, but on browser the `Cookie` header is block, and the cookie itself is ignored *by Godot* (I guess?)

Under `/scn` folder there is a "TEST" scene which as a simple script attached, very similar to the one in the reproduction steps, which points to an online mock server. It can be used as well.

**Comment by Faless** [comment]
> When making HTTP requests to a server, Godot is not sending Cookies in the request on HTML5.
> Since Godot is currently using `fetch` APIs on html5, and the `Cookie` header is a [forbidden one](https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name) for that, it creates inconsistency between desktop-client requests and browser ones.

Well, as you found out, browsers will not allow setting the cookie header. There is not much we can do about it.

There is no way on the web to manually specify cookies for a request.
The `Fetch API` (like the old `XMLHTTPRequest`) will only send the `document.cookies` by default when making `same-origin` requests (as set by the server, or via JavaScript).

We could probably set the [`Request.credentials`](https://developer.mozilla.org/en-US/docs/Web/API/Request/credentials) value to `include` to have it send cookies for `cross-origin` requests too. You still won't be able to manually set them (as they will not be available in your JavaScript context), but if the server does it via the `Set-Cookie` headers, or if they are present in the browser from previous sessions, they will be sent along in future requests.

**Comment by fenix-hub** [comment]
Thank you for your answer @Faless 
> We could probably set the Request.credentials value to include to have it send cookies for cross-origin requests too. 
Seems a good solution to me, even though I don't know what will be the possible consequences. But based on my newbie research it was the only solution I could find.
> You still won't be able to manually set them (as they will not be available in your JavaScript context), but if the server does it via the Set-Cookie headers, or if they are present in the browser from previous sessions, they will be sent along in future requests.
Yes, I'm aware I won't be able to manipulate them now, but it's not a big issue.
Most of the backends I've found online (including the one I'm currently integrating) are sending the `Set-Cookie` header, indeed. 
My opinion is that, as far as services are requesting cookie authentication as a mandatory authentication method, the chances these same services are setting the token through header is pretty high, so the only possible solution would be to allow Godot to send them back, no matter if we can manipulate them or not.

A possible solution would be to add the cookie to a custom header, but in that case the backend itself should know what the custom header is, and not all backends use this approach (btw Appwrite does this using the `X-Fallback-Cookies`, which can be added without any issue both on desktop and html5 builds with Godot, but not all backends use this approach).

**Comment by carpikes** [comment]
Hi, I'm having the same problem also in non-HTML5 builds, e.g. desktop application (see issue #55837).

**Comment by daf-lernen** [comment]
there is a problem with version 3.4.3 accessing rest-apis, giving a cors-error with html export (but not on local export), exporting with version 3.4.1 doesnt show this error (same rest-api-provider - so no server issue), changing settings in the header lead to nothing, the error shows that it is always set to "include". bug or any help?

**Comment by Faless** [comment]
> there is a problem with version 3.4.3 accessing rest-apis, giving a cors-error with html export

What is the error message?

**Comment by nisovin** [comment]
> > there is a problem with version 3.4.3 accessing rest-apis, giving a cors-error with html export
> 
> What does the error message say?

If it's the same issue we're discussing on Discord, the error is this:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at [URL]. (Reason: Credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’).`

Should I open a new issue?
