### ISSUE TITLE
VoxelGI, ReflectionProbe FogVolume Extents should be replaced with Size for consistency with CSGBox3D

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#54449]
### Godot version

4.0.dev (6b0b1a4c0)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 470.74)

### Issue description

With https://github.com/godotengine/godot/pull/44183, we started moving from Extents properties to Size properties. This Size property is the same as extents, but with all values halved (which means the values you need to specify are twice as large to obtain the same size as before).

To ensure consistency within the Godot API, we should finish this compatibility breaking change before 4.0 is released.

### Steps to reproduce

- Add a VoxelGI, ReflectionProbe or FogVolume node.
- Notice how the size is still defined using an half-extents property rather than a size like CSGBox3D is.

### Minimal reproduction project

N/A

**Comment by ator-dev** [comment]
In many cases 'extents' properties are set to default values such as Vector3(1, 1, 1). Do we want to maintain this size (as in change the default to Vector3(2, 2, 2)) or should the defaults be retained and just start out smaller?

**Comment by Calinou** [comment]
> In many cases 'extents' properties are set to default values such as Vector3(1, 1, 1). Do we want to maintain this size (as in change the default to Vector3(2, 2, 2)) or should the defaults be retained and just start out smaller?

I think we can revise the values to be larger if they are typically used at larger sizes. For instance, the default extents of a ReflectionProbe were increased in `master` to make them easier to see when you add one to the scene.

**Comment by ator-dev** [comment]
That makes sense, thanks - if I have a go at doing this I'll retain default values of (0,0,0), check the usage for values of (1,1,1), and assume other values to be intentionally sized and double them as necessary.

**Comment by ator-dev** [comment]
![image](https://user-images.githubusercontent.com/66553618/140776163-3ac48465-0173-4106-951c-b43a74fe5097.png)
I'm afraid I need advice on this line in renderer_scene_render_rd.cpp, as I'm having trouble understanding it. Surely width/height/depth should be divided by 2 here, since width means the full width of an object and so a subset of its size? Should I multiply them by 2 to compensate, ignore it, or edit interactions with VolumetricFog so that it works on a different size scale?
