### ISSUE TITLE
Mouse button input events are not picked up consistently on macOS

### ISSUE THREAD

**Issue by keeganstothert** [godotengine/godot#54458]
### Godot version

3.3.4

### System information

macOS Monterey 12.0.1

### Issue description

input events are not picking up consistently for left click events on apple silicon / Monterey

### Steps to reproduce

create a brand new project and create an action that maps to any key and the left mouse button. 

```gdscript
func _input(event):
	if event.is_action_pressed("spawn"):
		print("spawn")
```

the print line will fire when pressing the key but will only fire when double clicking or rapidly clicking the left mouse button. Every few times it will actually work as expected so you may have to restart the game once or twice if it appears to be working. 

tested on x86 under manjaro and the issue does not exist.

tested under rosetta x86_64-apple-darwin and native aarch-apple-darwin on m1 MacBook issues occurs for both.

### Minimal reproduction project

any brand new project on 3.3.4 on apple silicon and Monterey 12.0.1

**Comment by Calinou** [comment]
> tested on x86 under manjaro and the issue does not exist.

This actually does happen on Linux, but hasn't been reported on macOS yet: https://github.com/godotengine/godot/issues/48369

**Comment by bruvzg** [comment]
Might be related to #54306, can you reproduce it after switching to another app and back?

**Comment by keeganstothert** [comment]
@bruvzg  switching to another app and back fixes the issue

**Comment by insomnocrat** [comment]
I'm encountering the same issue, and I can reproduce it using the steps mentioned in #8653 (moving the mouse after clicking run vs not moving the mouse).

**Comment by keeganstothert** [comment]
@Calinou 

1. Input.set_use_accumulated_input(false) does not resolve it
2. disabling V-Sync does not resolve it
3. V-Sync and force fps does not resolve it

**Comment by akien-mga** [comment]
Fixed by #54474.

**Comment by LordBrkica** [comment]
I am also encountering this issue on mac OS Monterey 12.0.1. Godot version is **3.4 stable mono.**
Device is mac mini i3 2018, with UHD 630 GPU.

Bug occurs sporadically, 1 out of 10 times when I start the game the bug will occur. 
When it occurs, its immediately obvious as the game starting UI elements (buttons) are also affected.

The Bug I would describe most simply as follows: 
- one normal left mouse click seems to be ignored/missed, one needs to double click and this is then registered as one normal click

GLES2/3 options are affected equally, and its not specific to one control type (e.g. Button) but seems to affect all equally.

Bug seems to go away after some time (window switching and window minimizing, maximizing maybe helps).

**Comment by codespren** [comment]
Can confirm, Mac OS Monterey 12.1, MacBook Pro, AMD Radeon Pro 5500M 4 GB

Steps to reproduce:
1. Create an empty project
2. Create a root scene, for example of type Node2D
3. Run the project from Godot editor
4. When the project is starting move mouse/touchpad rapidly

Project starts with window's control balls greyed out. If there are any components in the project they doesn't work with single click but requires double click instead.

One thing I noted is that when the bug occurs, during the startup phase the mouse's cursor size changes larger and stays like that very short time and then changes back to normal size. That doesn't happen if I don't move the cursor during the startup.

**Comment by codespren** [comment]
Cannot reproduce in the Godot 3.4.2 stable mono.

Device is Mac OS Monterey 12.1, Macbook Pro AMD Radeon Pro 5500M 4 GB (x86_64)
Bug happened previously with the Godot's earlier versions with the same machine but not anymore in 3.4.2

**Comment by matthew-dean** [comment]
I'm seeing mouse click events picked up, but lagging way behind keyboard input being registered with Godot.

**Comment by Calinou** [comment]
> I'm seeing mouse click events picked up, but lagging way behind keyboard input being registered with Godot.

This is already being tracked in https://github.com/godotengine/godot/issues/109264.

Also, make sure the issue isn't due to a third-party program: https://github.com/godotengine/godot/issues/104246
