### ISSUE TITLE
[GDScript 2.0] "Compiler bug: unresolved assign" in setters

### ISSUE THREAD

**Issue by MatteoPiovanelli-Laser** [godotengine/godot#54450]
### Godot version

master d6f972fad45d28222b1437a047241dd74f0d5b90

### System information

Windows 10

### Issue description

A compiler error is reported when an assignment is made in a property setter using a method from a `Resource`.
```
modules\gdscript\gdscript_byte_codegen.cpp:826 - Compiler bug: unresolved assign.
```
The same error is reported by the debugger
```
E 0:00:01:0183   GDScriptByteCodeGenerator::write_assign_with_conversion: Compiler bug: unresolved assign.
  <C++ Source>   modules\gdscript\gdscript_byte_codegen.cpp:826 @ GDScriptByteCodeGenerator::write_assign_with_conversion()
```

Identical code in a function that isn't a setter doesn't cause the error.

As long as the `Resource` is correct (i.e. is of the correct class) the code runs fine.

### Steps to reproduce

I attached a small sample with two scripts.
Playing the scene will show the error in the Debugger.
Editing and saving the `MyTestScene.gd` script will also show the error in the Output tab as well as in a notification:
![image](https://user-images.githubusercontent.com/19283945/139590665-92718974-6a3a-47fb-8f26-ff4febca0ea1.png)

### Minimal reproduction project

[godot4test.zip](https://github.com/godotengine/godot/files/7449104/godot4test.zip)

**Comment by hazer-hazer** [comment]
Hi, I would like to begin contributing to Godot, tried to find the problem of this issue and I likely found it.
[Here's a pull request](https://github.com/godotengine/godot/pull/54492) where a possible solution is described.
I'm a newbie in Open Source and Godot source code, so would like to see any recommendations from experienced devs.
