### ISSUE TITLE
Tab header for Debugger Errors doesn't reset correctly in editor.

### ISSUE THREAD

**Issue by MatteoPiovanelli-Laser** [godotengine/godot#54451]
### Godot version

master d6f972fad45d28222b1437a047241dd74f0d5b90

### System information

Windows 10

### Issue description

After running the debugger from the editor and encountering errors/warnings you are left with a tab header highlighting that fact:
![image](https://user-images.githubusercontent.com/19283945/139590777-dbf67fb4-f144-4f41-a695-efbdb776f47c.png)
Clicking on it opens the debugger tab (dock?), which again highlights the errors/warnings from the debug session:
![image](https://user-images.githubusercontent.com/19283945/139590865-fc9a5097-9baf-42d4-a90c-7ba5b2b39862.png)
Clicking the "Clear" button removes the errors from the list, but does not reset the headers:
![image](https://user-images.githubusercontent.com/19283945/139590891-3b2652c8-4922-48ce-8fc1-92e0cb39d6bc.png)

Hitting "Clear" while the debugger session is still running correctly clears those headers.

### Steps to reproduce

See description.

### Minimal reproduction project

This should happen for any project. It happens in all the projects I tried this.

**Comment by Jayman2000** [comment]
I don’t think that this issue was fully fixed. I’m running Godot 4.0 alpha 2 and the number in the bottom panel still doesn’t go away.

![The dot and the number in the tab at the top disappears, but the dot and the number next to “Debugger” in the bottom panel stays.](https://user-images.githubusercontent.com/5579359/155047261-678f4e8d-69b7-46bc-ab3e-21e3a98d8eb6.png)

**Comment by Zireael07** [comment]
Can confirm the number doesn't go away in alpha1 or alpha2

**Comment by MatteoPiovanelli-Laser** [comment]
I'm testing alpha 4 and the issue seems to still be there

**Comment by KoBeWi** [comment]
The problematic code is here:
https://github.com/godotengine/godot/blob/3dac7ff876edae8398cb0f3f27ec0bc68f1bbb8e/editor/debugger/editor_debugger_node.cpp#L278-L303
This is executed in `NOTIFICATION_PROCESS`, when debugging server is active (i.e. the project is running).
