### ISSUE TITLE
Online editor not working

### ISSUE THREAD

**Issue by TheAnvils** [godotengine/godot#54466]
### Godot version

The not recommended for web games one

### System information

DELL CHROMEBOOK

### Issue description

It’s broken.

screenshot: 
https://cdn.discordapp.com/attachments/859484450831466557/904424539423899688/image.jpg

### Steps to reproduce

1. Click on the play button

### Minimal reproduction project

No lol

**Comment by TheAnvils** [comment]
Oh and btw at first it was working and then it broke

**Comment by Calinou** [comment]
> The not recommended for web games one

Try using the GLES2 renderer instead of GLES3. The GLES3 renderer doesn't work reliably in the web editor yet, but it will in Godot 3.4 (on supported hardware).

**Comment by TheAnvils** [comment]
Ok thanks!

**Comment by akien-mga** [comment]
"It's broken" is not a bug report. You do not describe what the problem is. A screenshot is useful but it's not a description.

Everything shown in your screenshot is expected from the current state of the Web editor.
