### ISSUE TITLE
Cannot zoom in or zoom out camera using gdscript

### ISSUE THREAD

**Issue by RockZombie123** [godotengine/godot#54464]
### Godot version

v3.3.3.stable.custom_build [b973f997f]

### System information

Raspberry pi 4

### Issue description

So I'm new to godot and I'm playing around with it. However, I've stumbled upon a problem in making the camera zoom in and out using gdscript. I have a player which can move up, down, left, and right, but I want the camera to zoom out since the player is too close to the camera. Here is my code for `Camera2D`:
```
extends Camera2D

# Zoom minimum
var zoom_min = Vector2(.200001, .200001)
# Zoom max
var zoom_max = Vector2(2, 2)
# Zoom speed
var zoom_speed = Vector2(.2, .2)
# Desired zoom
var des_zoom = zoom

func _process(delta):
	zoom = lerp(zoom, des_zoom, .2)

func _input(event):
	if event is InputEventMouseButton:
		if event.is_pressed():
			if event.button_index == BUTTON_WHEEL_UP:
				if des_zoom > zoom_min:
					des_zoom -= zoom_speed
			if event.button_index == BUTTON_WHEEL_DOWN:
				if des_zoom < zoom_max:
					des_zoom += zoom_speed

```
and here is my player code (Just in case):
```
extends KinematicBody2D

var speed = 30
var velocity = Vector2.ZERO

func _physics_process(delta):
	if Input.is_action_pressed("ui_right"):
		velocity.x = speed
	elif Input.is_action_pressed("ui_left"):
		velocity.x = -speed
	else:
		velocity.x = 0
	if Input.is_action_pressed("ui_down"):
		velocity.y = speed
	elif Input.is_action_pressed("ui_up"):
		velocity.y = -speed
	else:
		velocity.y = 0
		
	move_and_slide(velocity)

```
Finally, here are 2 images for showing my output, and how the outside looks on my end:
![ran](https://user-images.githubusercontent.com/91627371/139598622-8067b749-4fb9-4425-a2c9-013c9475dd0a.png)
![Camera2D](https://user-images.githubusercontent.com/91627371/139598637-8226c705-9ca1-402b-9337-eef99d865d7a.png)

### Steps to reproduce

```
extends Camera2D

# Zoom minimum
var zoom_min = Vector2(.200001, .200001)
# Zoom max
var zoom_max = Vector2(2, 2)
# Zoom speed
var zoom_speed = Vector2(.2, .2)
# Desired zoom
var des_zoom = zoom

func _process(delta):
	zoom = lerp(zoom, des_zoom, .2)

func _input(event):
	if event is InputEventMouseButton:
		if event.is_pressed():
			if event.button_index == BUTTON_WHEEL_UP:
				if des_zoom > zoom_min:
					des_zoom -= zoom_speed
			if event.button_index == BUTTON_WHEEL_DOWN:
				if des_zoom < zoom_max:
					des_zoom += zoom_speed

```

**Comment by Calinou** [comment]
This is likely because using `+=` and `-+` on Vector2/Vector3 variables is currently broken. Try using `=` to assign the variable instead.

**Comment by akien-mga** [comment]
> This is likely because using `+=` and `-+` on Vector2/Vector3 variables is currently broken in `master` (due to the GDScript rewrite). Try using `=` to assign the variable instead.

This appears in be in 3.3.3, so that should be unrelated.

**Comment by robfram** [comment]
It works at expected in 3.2.3.stable and my 3.4.rc.custom_build.d5adb9e4b.

At first the zoom wasn't working, but later I realized the problem was the camera wasn't the current one.

@RockZombie123 could you try to add this to your demo script?
```
func _init():
        current = true
```
You can also try to check it in the inspector window.
![image](https://user-images.githubusercontent.com/35065795/139647279-b53cedcd-c689-4403-8109-be4e778a5194.png)

**Comment by RockZombie123** [comment]
@robfram Thank you! This worked like a miracle. I think `current` was probably set to `false`.
