### ISSUE TITLE
Right-click + Edit on a resource property editor no longer opens a dedicated inspector

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#54465]
### Godot version

3.4 rc1

### System information

Windows 10 64 bits GLES3 GeForce GTX 1060 6GB/PCIe/SSE2

### Issue description

In Godot 3.2.3, clicking on a resource property with a resource in it does expand that resource into a sub-inspector. But there was the alternative to right-click, and on the context menu, choose "Edit". This would open the resource in a dedicated inspector instead.

![image](https://user-images.githubusercontent.com/1311555/139598982-d0f635e0-04ea-40e2-ba0d-059bf40d141d.png)

In Godot 3.4 rc1, that option no longer works that way. Instead it does the same thing as toggling the sub-inspector, making it less useful than it was. If you ever want to open an embedded resource in a full inspector *temporarily*, it has become impossible now. The only way is to save it to a file and double-click the file, or maybe turn off the option to use sub-inspector *completely*, if it exists.

### Steps to reproduce

Using the reproduction project below.

When using Godot 3.2.3:

1) Open the `theme.tres` resource. 
2) Click on the DefaultFont property value.
3) Observe a sub-inspector opens.
4) Right-click on the "Default Font" property, choose "Edit"
5) Observe the font opens in a dedicated inspector.

When using Godot 3.4 rc1:

1) Open the `theme.tres` resource. 
2) Click on the DefaultFont property value.
3) Observe a sub-inspector opens.
4) Right-click on the "Default Font" property, choose "Edit"
5) Observe the sub-inspector collapes instead. Further "Edit" clicks keep toggling the sub-inspector and don't open a dedicated one.

### Minimal reproduction project

[EditSubInspectors.zip](https://github.com/godotengine/godot/files/7449653/EditSubInspectors.zip)

**Comment by akien-mga** [comment]
CC @pycbouh

**Comment by pycbouh** [comment]
Both clicking on the resource header and clicking on the "Edit" option does indeed trigger the same signal and the property inspector does the same thing. That logic was the same before, I see no code that would forcefully open the resource in a sub-inspector from the "Edit" button in the previous versions of Godot.

What's different now is that the `Font` resource now has an editor associated with it, the Theme Editor. This is needed for the theme editor to remain open when you start editing resources of the theme. This fact affects the logic of sub-inspectors and we can't do much about it until we properly fix the issues with resource editors and sub-inspectors. But, again, it's the same exact logic in 3.2.3, it just that `Font` didn't have any editor associated with it before.

So this is not a regression. We can make the "Edit" menu option do what you describe for usability purposes, though. I see no problem with that.

**Comment by pycbouh** [comment]
I took a second look, and I do see the difference now. Sorry for that, a bit hard to read the original code. Okay, let's restore the regression label I guess. I'll provide a solution for it tomorrow (I was going to either way).
