### ISSUE TITLE
3D editor does not recognize physical key inputs configured in freelook shortcuts (only non-physical keys work)

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#54460]
### Godot version

4.0.dev (1aef3a42b)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 470.74)

### Issue description

The editor does not recognize physical key inputs configured in shortcuts (only non-physical keys).

This is now more important to fix as [inputs are now created as physical by default](https://github.com/godotengine/godot/pull/53707). The change also affects the editor shortcut dialog. We could disable the creation of physical key inputs in the editor shortcut dialog, but this would make it impossible to support freelook keys on non-QWERTY layouts by default ([something we should be able to fix now](https://github.com/godotengine/godot/issues/11777)).

**Edit:** After testing for https://github.com/godotengine/godot/issues/54469, I noticed that this only applies to freelook shortcuts in the 3D editor. For instance, this doesn't occur with the **Always Show Grid** shortcut in the 2D editor.

This is the part of the code that handles 3D editor freelook shortcuts: https://github.com/godotengine/godot/blob/1aef3a42b234b86c5db21d5a64509453e6bf145c/editor/plugins/node_3d_editor_plugin.cpp#L2606-L2623

cc @EricEzaM 

### Steps to reproduce

- Use a non-QWERTY keyboard layout such as AZERTY:
- Add a physical key shortcut to a 3D editor freelook action as follows:

![image](https://user-images.githubusercontent.com/180032/139596232-3e8cf5fa-8e43-4e62-938b-c543f06a7424.png)

- Try to press <kbd>Z</kbd> (on AZERTY) to move forward while having freelook enabled.

### Minimal reproduction project

N/A

**Comment by EricEzaM** [comment]
The `is_shortcut_pressed` method is defined specifically for the 3D editor. See the method below, this is what would need to be changed.

https://github.com/godotengine/godot/blob/1aef3a42b234b86c5db21d5a64509453e6bf145c/editor/plugins/node_3d_editor_plugin.cpp#L2557-L2575

**Comment by EricEzaM** [comment]
Please see my comment on #54469. Hopefully that fixes both issues with one change.
