### ISSUE TITLE
 Input event doesn't emitted when mouse pos is within control node

### ISSUE THREAD

**Issue by khairul169** [godotengine/godot#5448]
**Operating system or device - Godot version:**
Ubuntu 16.04 LTS - v2.1

**Issue description** (what happened, and what was expected):
Input event (_input(event)) is not emitted when mouse position is within a control node.

**Steps to reproduce:**
Make a control node, set the size & position to whatever you want.
Give it a script,
```
func _ready():
	set_process_input(true);

func _input(ie):
	if ie.type == InputEvent.MOUSE_BUTTON:
		print("Mouse button");
	
	if ie.type == InputEvent.MOUSE_MOTION:
		print("Mouse motion");
```
Play, and see the result.

**Link to minimal example project** (optional but very welcome):
https://drive.google.com/open?id=0B4y9gkD37fATSVJFbGV0anQ4c0k

**Comment by akien-mga** [comment]
> [Since this commit](https://github.com/godotengine/godot/commit/2c59f778850dc4450481680e859efd66660c9119)

I guess you mean that you noticed the bug while using this commit, not that this commit introduced the bug? There's nothing in this commit related to input events.

**Comment by khairul169** [comment]
yeah i mean i'm compiled the editor from this commit

**Comment by vnen** [comment]
Seems similar to (if not the same as) #5361, which also states it as being a regression.

**Comment by MarianoGnu** [comment]
#5361 is fixed, take a look just in case it's fixed

**Comment by vnen** [comment]
This is the same issue. Tested the sample project and found nothing wrong, so this was fixed too.

**Comment by khairul169** [comment]
Thanks! :smile:
