### ISSUE TITLE
PopupMenu (Viewports in general) increase Physics2D work

### ISSUE THREAD

**Issue by ibrahn** [godotengine/godot#54484]
### Godot version

v4.0.dev.custom_build [344babb93]

### System information

Linux, Debian 11

### Issue description

Breaking off https://github.com/godotengine/godot/issues/54291#issuecomment-955247678 to separate issue.

`Viewport`s each have their own `World2D` and so `GodotSpace2D` these add some work to physics step even when empty.
This wouldn't be much of an issue, except that large GUIs can have many Viewports hanging around in the form of `PopupMenu`s and the cost starts to add up.
Disabling the whole Physics2D server should solve this for #54291 as it does for the editor, but games want PopupMenus and scenes with 2D physics running at the same time.

Options?:
* Reduce the work done by empty GodotSpace2D steps.
* Expose a function to disable 2D physics in a Viewport and have subclasses like PopupMenu use this by default.

### Steps to reproduce

n/a

**Comment by KoBeWi** [comment]
Creating Worlds is costly in itself and it was the reason #50530 was made.
I wonder if viewports without any world at all are possible. This could speed-up their creation too.

**Comment by rburing** [comment]
Fixed by https://github.com/godotengine/godot/pull/72425.
