### ISSUE TITLE
Volumetric Fog texture oddly fills with pitch black when Decal is present in camera frustrum

### ISSUE THREAD

**Issue by Phobos001** [godotengine/godot#54496]
### Godot version

v4.0.dev.20211027.official [157cba393]

### System information

Linux Mint 20.2, AMD Radeon VII, Mesa 21.1.8 - kisak-mesa PPA, Vulkan Clustered

### Issue description

https://user-images.githubusercontent.com/8943977/139771123-2e9e783e-6fea-42ba-8e58-c556c096f0a3.mp4

When a Decal is present on screen, and Volumetric Fog is active in the WorldEnvironment node, its very easy to generate strange black squares across the entire screen by moving the camera around. _The decal does not need to be projecting on a mesh._ It happens regardless, but only when the Decal is in the frustrum of the camera. The decal needs to have a texture assigned to it to recreate the effect.

### Steps to reproduce

1. Create a Decal
2. Assign a texture to the albedo, icon.png will do just fine.
3. Create a WorldEnvironment
4. Activate the VolumetricFog effect
5. Wiggle the editor window when the Decal is in the view. A series of black squares will consume all light. The squares will go away if the decal is out of the frustrum and new VolumetricFog data fills the spaces in.

### Minimal reproduction project

[DecalVolumetricFogError.zip](https://github.com/godotengine/godot/files/7457074/DecalVolumetricFogError.zip)

**Comment by briansemrau** [comment]
I'm unable to reproduce using the min rep on the listed commit using W10, RTX2060 (driver v472.12), vulkan clustered

**Comment by Calinou** [comment]
This may be AMDGPU driver-specific: https://github.com/godotengine/godot/issues/53528

**Comment by Ansraer** [comment]
Unable to confirm this bug on Windows + AMD 6900XT running Driver Version
21.40.11.03-211201a-374383E-RadeonSoftware.

Created the scene as described and panned around for a good minute. Never got any artifacts at all.

Will be able to test on linux with the same hardware in a few days once I can reboot my PC.

**Comment by Calinou** [comment]
For future reference, I couldn't reproduce this on 4.0.rc3 (Linux, GeForce RTX 4090 with NVIDIA 525.89.02).

![image](https://user-images.githubusercontent.com/180032/221046802-f26209ae-5118-4e80-bee8-d6ce6d077a58.png)
