### ISSUE TITLE
Texture filter not affecting TextureRegion editor

### ISSUE THREAD

**Issue by floppyhammer** [godotengine/godot#54502]
### Godot version

v4.0.dev.custom_build [455e02772]

### System information

Windows 11, Vulkan Clustered

### Issue description

Texture in the TextureRegion editor is still blurred, which makes it hard to operate on pixel art pictures.

![image](https://user-images.githubusercontent.com/28705694/139791968-9f03073a-4d01-42e4-8d11-cca56549100b.png)

### Steps to reproduce

Create a Sprite2D and drag a pixel art picture into it, enable region and edit it.

**Comment by akien-mga** [comment]
Seems fixed in 4.0 RC 1.

![image](https://user-images.githubusercontent.com/4701338/218421740-1c9f9706-05fb-4939-baa3-9d947a2aa2fe.png)
