### ISSUE TITLE
GridContainer not resizing automatically on children visibility change

### ISSUE THREAD

**Issue by marcinjakubowski** [godotengine/godot#54504]
### Godot version

3.3.4.stable.official, 4.0.dev [0ec776319]

### System information

Linux, GLES3, NVIDIA 460.91.03

### Issue description

Given a panel container with a grid container in it, and a number of children, let's say 5 columns x 3 rows of labels. If visible on the last 5 children is set to false, effectively hiding the entire row, the panel container will remain the same size. However, if I hide and show the panel again, it will resize to hold just two rows. This seems to be caused by grid container though, as it also causes the same behavior with other parent containers.

Demo:
![Peek 2021-11-02 01-48](https://user-images.githubusercontent.com/2545419/139814658-429224bd-63bb-4ca3-bbaa-0588b60ea9e6.gif)

I would expect that the container resizes itself automatically or there is a straightforward way to force it to resize. The following will work:

```
panel.visibility = false
panel.visibility = true
```

But this code obviously looks wrong. This will also work, but still seems a little bit hacky, so I'm not sure whether that's actually intended behavior. `queue_sort()` will have no effect.

```
panel.set_size(panel.get_minimum_size())
```

### Steps to reproduce

Scene code, also reproduction project is attached.

```
extends Control

onready var panel = $PanelContainer
onready var grid = $PanelContainer/GridContainer

func _on_Button_pressed():
    for idx in range(grid.get_child_count() - 5, grid.get_child_count()):
        grid.get_child(idx).visible = !grid.get_child(idx).visible


func _on_Button2_pressed():
    panel.visible = !panel.visible
```

### Minimal reproduction project

[visibility_bug_demo.zip](https://github.com/godotengine/godot/files/7459121/visibility_bug_demo.zip)

**Comment by groud** [comment]
All Containers nodes work like that if I am not mistaking, they expand but do not shrink automatically. You can call `set_size(Vector2())` on them to reset the size to the minimum size if you need.

**Comment by groud** [comment]
So yeah, closing as this is an expected behavior.

**Comment by marcinjakubowski** [comment]
It feels kind of counter-intuitive to be quite honest. Maybe a quick helper function like `force_resize()` or something like that would be helpful, with docs explaining this behavior and the need to do this?

**Comment by marcinjakubowski** [comment]
I might do that (or is a PR better? I can do C++ and know my way around Godot's source), because this issue seems to bring some confusion, see comments [here](https://godotengine.org/qa/31645/how-to-force-container-to-recalculate-own-rect_size) and [here](https://old.reddit.com/r/godot/comments/qksh50/how_to_force_container_to_recalculate/).
