### ISSUE TITLE
Make it more obvious which script is being edited

### ISSUE THREAD

**Issue by supaiku-o** [godotengine/godot#5450]
Right now it can be quite confusing when the script editor is opened and there's no obvious way to tell which script is being edited. I know that the sidepanel shows the opened scripts and colors them depending on usage(?), but it quickly becomes a headache to find the opened file when there are like 20 opened files and all are red.

That's why I suggest to show the focused script name in the window/application title, when the "script view" is active. Currently it only shows the scene name, but imo it would be better if it distinguishes between the active view ("2D/3D/Script") and adjusts the title accordingly.

**Comment by zendorf** [comment]
+1 Agreed! Several times I have found myself editing the wrong script since it can be difficult at times to tell at a glance what you are working on. I preferred pre v2 gui of Godot which had the script name on the tab label. 

Btw, supaiku-o you can turn off "script temperature enabled" in the Text Editor settings, which will make the script name only highlight your current one. Still this highlighting is subtle (white selected vs grey unselected) and I would prefer to see the tab label be the name of the script.

**Comment by neikeq** [comment]
IMO, displaying the current script name as bold in the script list would be enough. WDYT?

**Comment by Sslaxx** [comment]
Seconded with the **bold** suggestion, here.

**Comment by samuelgrigolato** [comment]
What about a third color? "Script temperature" is nice, so is having it disabled. With a "highlight current script" exclusive color, one can leverage both configurations. I've made a little demo:

![proposal](https://cloud.githubusercontent.com/assets/352108/16472994/caf7dc78-3e3f-11e6-970a-dba7ee3523ef.gif)

I think using this third color, in addition to a bold (as already suggested) and black colored font would be even better.

**Comment by bojidar-bg** [comment]
@Paulb23 @samuelgrigolato Does any of you want to try doing this? :smile:

**Comment by samuelgrigolato** [comment]
@bojidar-bg when you say "this" do you mean my last suggestion (to add a third color to configuration options)? If so, I might try =). If not, well, then I need to know exactly what to try :laughing:

**Comment by bojidar-bg** [comment]
@samuelgrigolato Well, I guess I meant it :smile:

**Comment by mefihl** [comment]
For me not works this PR.
![3333999](https://cloud.githubusercontent.com/assets/5302754/18409343/0332ae54-7745-11e6-9a5b-1dff28a4f706.png)

**Comment by mefihl** [comment]
Still not change color for me.
