### ISSUE TITLE
Showcase page: Suggestions for improvements

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#5451]
We now have a new page on the website to showcase Godot games: https://godotengine.org/showcase

This issue is meant to gather community feedback on how to improve its functionalities further.

To request the addition of new entries, please contact us directly per email [as mentioned in the blog post](http://godotengine.org/article/showcase-your-godot-game-our-website).

**Comment by HatisEm** [comment]
![This is annoying for people who are like me](https://cloud.githubusercontent.com/assets/17906040/16398471/eb59bf34-3cca-11e6-9bf8-0e378950ca6a.png)

**Comment by vnen** [comment]
@HatisEm what is the context of this? Like what browser, screen resolution...

**Comment by HatisEm** [comment]
@vnen I'm on Ubuntu 15.10 the browser is Chromium and my screen resolution is 1366 x 768

**Comment by djrm** [comment]
thats true, the new showcase option messed up the previous navigation bar collapse limits

**Comment by vnen** [comment]
Ok, then. A job for @alketii, I guess.

**Comment by djrm** [comment]
also i have a suggestion, the showcase page has to highlight the "best" games, otherwise it will become something like the libgdx gallery https://libgdx.badlogicgames.com/gallery.html

**Comment by Norrolith** [comment]
"So the best solution for this is to let you, the game developers, showcase what you can do using Godot! Games of all genres, 2D and 3D, with simple of very complex gameplays, story-rich or casual... Godot can be used for all those games, and you can help show this to the world!"
'of' in the second sentence should be 'or'. Sorry if Off Topic.

**Comment by akien-mga** [comment]
> also i have a suggestion, the showcase page has to highlight the "best" games, otherwise it will become something like the libgdx gallery https://libgdx.badlogicgames.com/gallery.html

I agree, at some time we need to implement a kind of "editor's pick" system, that would e.g. list in the first half of the page the games we selected as the best to showcase Godot features, and in the second half of the page maybe all submitted games, showing the most recent first.

**Comment by paper-pauper** [comment]
Multiple tags would be nice. Also I would not include WIP games, otherwise the barrier of entry would be lower.

Also be careful about the "libre" tag; [this game](https://github.com/CowThing/MouseBoat) is tagged as "libre" but it doesn't have any licensing info, so it is proprietary software with available source code.

**Comment by akien-mga** [comment]
> Multiple tags would be nice.

There are multiple tags already. But indeed the distinction between tags is not clear. @alketii Add a comma maybe?

> Also I would not include WIP games, otherwise the barrier of entry would be lower.

Yes and no. There are WIP games like Steam Quest and Brave Bran which are way better to showcase Godot than some "published" games on Google Play. "WIP" with 100s of hours of work is better for us than "Finished" with 5 hours of work.

> Also be careful about the "libre" tag; this game is tagged as "libre" but it doesn't have any licensing info, so it is proprietary software with available source code.

My bad, I forgot to double check; opened an issue about this upstream as I'm sure it's just the author overlooking the need for precise licensing info.

**Comment by paper-pauper** [comment]
@akien-mga 

> There are multiple tags already. But indeed the distinction between tags is not clear. @alketii Add a comma maybe?

I meant being able to filter by more than one tag, like https://godotengine.org/showcase/tags/3d+libre

> Yes and no. There are WIP games like Steam Quest and Brave Bran which are way better to showcase Godot than some "published" games on Google Play. "WIP" with 100s of hours of work is better for us than "Finished" with 5 hours of work.

But what if they become either vaporware or one of those Early Access games that will never get finished?

**Comment by akien-mga** [comment]
> But what if they become either vaporware or one of those Early Access games that will never get finished? If people can't play it it's just a video, not a game.

A video that shows that Godot is an awesome engine nonetheless. The purpose of this page is not for people to make their wishlist of games to buy, but to showcase what Godot can be used for. And almost everybody in the community knows about Steam Quest and Brave Bran, they're even used in the features page of the website.

With so little published games (especially for desktop), we can't be that picky.

**Comment by alketii** [comment]
The navbar is fixed, thanks.

**Comment by vandalk** [comment]
A search bar would be nice! I saw the games showcase on Godot's steam page and really like "Dolphin Quest 2", but to find it I had look it up page by page.

**Comment by bojidar-bg** [comment]
Press <kbd>Ctrl</kbd>-<kbd>F</kbd> to pop up a search bar (on officially supported browsers only).

**Comment by vandalk** [comment]
Yeah, but still, it only searches the current page. A search bar would be interesting for searching tags without first having to find a game with that tag and click it, and to search for keywords on all available showcased games. Like searching for a post on a blog.

**Comment by akien-mga** [comment]
Closing as we now have a proper issue tracker for the website: https://github.com/godotengine/website

Feel free to move some of the suggestions there if they aren't tracked yet or fixed by now.
