### ISSUE TITLE
Crash on M1 with multi-threaded rendering on window resize

### ISSUE THREAD

**Issue by chrrrrrrr** [godotengine/godot#54519]
### Godot version

3.3.4

### System information

macOS 11.6, GLES3, M1

### Issue description

Dragging to resize the game window makes it crash when rendering is multi-threaded. Doesn't happen on my intel mac -- only on M1. Using GLES2 seems to fix it in a simple project, but in a larger project it also crashes on GLES2.

### Steps to reproduce

Create blank project.
Project Settings > Rendering > Thread > Multi-threaded
Play project
Resize window by dragging a side or corner for a bit to crash it.

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by chrrrrrrr** [comment]
@Calinou I tried compiling the master, but I end up with a file that I can't run: `bin/godot.osx.tools.arm64`

**Comment by alexruetz** [comment]
> @Calinou I tried compiling the master, but I end up with a file that I can't run: `bin/godot.osx.tools.arm64`

As stated in the docs, to make an .app bundle you need do a bit more after compiling

> cp -r misc/dist/osx_tools.app ./Godot.app
mkdir -p Godot.app/Contents/MacOS
cp bin/godot.osx.opt.tools.universal Godot.app/Contents/MacOS/Godot
chmod +x Godot.app/Contents/MacOS/Godot

I tried to replicate that crash on the master branch but it seemed fine to me. No crash so far.

This is the crash log for the 3.3.4 Version: https://pastebin.com/HxitWbkD

**Comment by chrrrrrrr** [comment]
Thanks @alexruetz . I just got it working as well and haven't had it crash either.

**Comment by akien-mga** [comment]
Fixed by #54526.
