### ISSUE TITLE
Missing `MenuButton` and `PopupMenu` items editor button

### ISSUE THREAD

**Issue by rafallus** [godotengine/godot#54522]
### Godot version

4.0 dev fe6c65a1a82ceb66fc15c3e76a01e17cb7fede22

### System information

Arch Linux

### Issue description

When selecting a `MenuButton` or `PopupMenu` node in the Scene dock, there's no Items button in the toolbar as it used to be in 3.3. This makes impossible to properly edit these nodes
![NoItemsButton](https://user-images.githubusercontent.com/29492561/139951784-644484ef-a7fd-4c4a-af12-eae326d29537.png)

### Steps to reproduce

1. Open a new scene
2. Add a `MenuButton`or `PopupMenu` node
3. No Items button in the toolbar

### Minimal reproduction project

Not needed

**Comment by Calinou** [comment]
This is because editing the list of items is now performed directly in the inspector: https://github.com/godotengine/godot/pull/54342
