### ISSUE TITLE
isim: "game_center" and "store_kit"

### ISSUE THREAD

**Issue by ret80** [godotengine/godot#5453]
**Operating system or device - Godot version:**
isim
godot 2.0.x

**Issue description** (what happened, and what was expected):

In the file "isim/detect.py" no line includes Game Center and Inapp. Gently add them there. But is disabled by default.
```
def get_opts():
...
                ('game_center', 'Support for game center', 'no'),
		('store_kit', 'Support for in-app store', 'no'),
...

def configure(env):
...
        if env["game_center"]=="yes":
                env.Append(CPPFLAGS=['-fblocks', '-DGAME_CENTER_ENABLED'])
                env.Append(LINKFLAGS=['-framework', 'GameKit'])
    
        if env["store_kit"] == "yes":
                env.Append(CPPFLAGS=['-DSTOREKIT_ENABLED'])
                env.Append(LINKFLAGS=['-framework', 'StoreKit'])
...
```

PS.
Why include TOOLS?
```
def get_flags():

	return [
		('tools', 'yes'),
```

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by vnen** [comment]
Well, this is totally bogus now. The master branch don't have the isim platform anymore, it was merged with the iphone platform.

**Comment by akien-mga** [comment]
This has been fixed in the master branch already, as mentioned by @vnen the `isim` platform was merged in the `iphone` one, and it no longer uses tools (and now tries to enable game_center and store_kit).

I might cherry-pick the change for the 2.0 branch, but it still needs some more testing, if you could try it it would be great :)

**Comment by ret80** [comment]
Let's test, I do not mind. What should be done?
Suggestion: Rename platform "iPhone" to "iOS". All the same, when you need to do it :)

**Comment by akien-mga** [comment]
> Let's test, I do not mind. What should be done?

Once you have cloned the master branch, you should be able to build the simulator (i.e. the x86 iOS binary) with `scons p=iphone ios_sim=yes` (or `scons p=iphone arch=x86`, both should work the same).

**Comment by ret80** [comment]
evening check and let you know the result.

**Comment by ret80** [comment]
I checked. in 2.1 branch is going 2 ways: ```scons p=iphone ios_sim=yes``` and ```scons p=iphone arch=x86```.
if you take the file "iphone/detect.py" of the branches 2.1 and 2.0 branch in the copy then the project team will also be collected, ```scons p=iphone ios_sim=yes``` but the command ```scons p=iphone arch=x86``` will not meet.

**Comment by akien-mga** [comment]
Yes the `arch` parameter relies on changes made in the main `SConstruct`, while the `ios_sim` parameter is standalone. The two are maybe a bit redundant though, I might remove the `ios_sim` one to the benefit of the more generic `arch` parameter (that could be used for other platforms too instead of the more limited `bits` argument).

Thanks for testing, glad to know it works in both 2.1 and 2.0 :) I'll add relevant changes for 2.0.4 then.

**Comment by ret80** [comment]
> I might remove the ios_sim one to the benefit of the more generic arch parameter (that could be used for other platforms too instead of the more limited bits argument).

probably well worth making.

**Comment by ret80** [comment]
Just a reminder that there is a task:)

**Comment by akien-mga** [comment]
Should now be fixed with 6d6b14d1.

**Comment by ret80** [comment]
@akien-mga
Something went wrong! :(
I collected two versions of ios: ```scons p=iphone``` and ```scons p=iphone arch=arm64```. And both write that: "godot_opt.iphone does not have an architecture that iPhone 4s can execute".
Maybe I'm doing something wrong. You can confirm that you're running?

**Comment by akien-mga** [comment]
I can't check as I don't have a mac nor an iphone to test with, but there should have been no changes for `scons p=iphone`. Was it working for you in 2.0.3 and no longer in 2.0.4.1?

**Comment by ret80** [comment]
Unfortunately I also has no iPhone.
I compiled and sent a friend to check. By this I am not sure at 100%.
But earlier at another all started (2.0.3) and with the new version (2.0.4.1) says that it is not working.
Do you have friends who would check it out?

**Comment by punto-** [comment]
How do you create the final executable that you run on the iphone? You also
need to compile with arch=arm64, and make a universal binary with lipo,
using the arm and arm64 binaries

**Comment by akien-mga** [comment]
Indeed, check http://docs.godotengine.org/en/latest/reference/compiling_for_ios.html

**Comment by ret80** [comment]
Good. Thank you. I'll try, then report the results.

**Comment by ret80** [comment]
@akien-mga
Everything is working.
Could you see here is the bug #5640.
Thanks in advance.
