### ISSUE TITLE
The method `GLTFDocument::save_scene` has an unused parameter.

### ISSUE THREAD

**Issue by theraot** [godotengine/godot#54532]
### Godot version

v4.0.dev.calinou [af80bc8ab]

### System information

Windows 10

### Issue description

The required parameter `src_path` of `GLTFDocument::save_scene` it is not used in the source code.

### Steps to reproduce

Have a look at the source code: https://github.com/godotengine/godot/blob/master/modules/gltf/gltf_document.cpp#L6843-L6869

### Minimal reproduction project

NA

**Comment by fire** [comment]
See discussion here https://github.com/godotengine/godot/pull/52541

**Comment by fire** [comment]
Fixed by https://github.com/godotengine/godot/pull/52541
