### ISSUE TITLE
Performance drops on camera rotation

### ISSUE THREAD

**Issue by Reapetitive** [godotengine/godot#54531]
### Godot version

3.4 beta 4 - 3.4 rc3

### System information

Windows 10 64 bit, rtx 3070, GLES3

### Issue description

In my top down 2D game the performance drops while rotating the camera by mouse. It doesn't seem to happen, while using a controller.  The mouse camera rotation is handled in _input, while controller camera rotation is handled in _physics_process. The issue isn't necessarily noticeably, as long as you aren't already pushing everything to the limit performance wise. I suppose some changes to _input handling are causing this performance issues.

### Steps to reproduce

Read above.

### Minimal reproduction project

[CameraRotationInputTest.zip](https://github.com/godotengine/godot/files/7473775/CameraRotationInputTest.zip)

**Comment by Calinou** [comment]
@Reapetitive Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by Reapetitive** [comment]
@Calinou sure! Not a perfect representation of the problem, but you can hopefully see, if you rotate the camera by right stick of the controller, fps stay constant, while using the mouse through _input drops them by 100-200 for me, or even more if you rotate faster. Sure, this ain't much frame time wise, but it seems to scale not very well as _input commands become more complex and general resource usage becomes higher.

**Comment by Reapetitive** [comment]
@Calinou nevermind! I can't bypass it. I still have to get the event InputEventMouseMotion from any kind of _input and it seems like this alone kills the performance totally for me. Still, playing with controller doesn't hit the performance what so ever. This is really wierd, i mean im getting pretty stable frames, for example 150. Just moving the mouse drops them to like 10.

**Comment by Reapetitive** [comment]
This issue still accures in 3.4.1.

**Comment by TrickMe** [comment]
Try Input.set_use_accumulated_input(true).

I had massive performance issues when moving the mouse cursor while displaying many canvas items (Control nodes or Node2Ds) since 3.4. Accumulated input fixed it for me.

#55037 states accumulated input is off by default (should be on).
Maybe its a regression of 3.4.x, because 3.3.x was working fine for me.

**Comment by Reapetitive** [comment]
@TrickMe thank you very much! It seems to have fixed the issue for me!

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/55037 (same cause).
