### ISSUE TITLE
Current GDScript function detection for coloring is quite poor

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#5454]
It seems to only color names that have a `(` just afterwards without any spaces. So `my_func()` is highlighted, but `my_func ()` is not. It is the same with function declarations and signals (which IMO could have a different color, even if the default were equal to the function color).

Maybe the color guy @Paulb23 want to look at this.

**Comment by bojidar-bg** [comment]
Ah Github messed up again, fixed by #5487
