### ISSUE TITLE
Alarming memory leaks whenever await is used in Godot 4.0

### ISSUE THREAD

**Issue by uzkbwza** [godotengine/godot#54542]
### Godot version

4.0.dev.calinou [af80bc8ab]

### System information

Windows 10, Intel i7-6700k x86-64

### Issue description

When using `await`, in seemingly any context, a new object appears to be created which is not garbage collected nor manually accessible by the user.

https://user-images.githubusercontent.com/43023911/140013127-ca71b37f-35c3-40fb-a0f5-17263ff44a11.mp4

I've tested this with different signals in different contexts and it seems to be ubiquitous. Unfortunately I discovered this while working on a small turn-based project that makes heavy use of asynchronous code, and leaks dozens of objects into memory every turn.

Perhaps I am just using await wrong, in which case, feel free to close this.

### Steps to reproduce

Use `await` and check your monitors.

### Minimal reproduction project

[memleak.zip](https://github.com/godotengine/godot/files/7465434/memleak.zip)

**Comment by xX-Void-Xx** [comment]
Just relized this is the case in my old project (v3.2), I wonder how old this issue is ?

**Comment by Calinou** [comment]
> Just relized this is the case in my old project (v3.2), I wonder how old this issue is ?

Godot 3.x doesn't have `await`. Are you referring to the use of `yield`? Either way, this is a different issue.

**Comment by xX-Void-Xx** [comment]
> Godot 3.x doesn't have `await`. Are you referring to the use of `yield`? Either way, this is a different issue.

no Im refering to the await keyword in C#, in my case I have a GUI based game where at some point I await the "request_completed " signal of a HTTPRequest node, and it seems that a memory leak happens everytime I call await, I guess that's a different issue but I didn't relize it untill now
