### ISSUE TITLE
ItemList.get_selected_items

### ISSUE THREAD

**Issue by DimitriyPS** [godotengine/godot#5456]
Offer small improvements (improvements) ItemList

In continuation: [A&Q](http://www.godotengine.org/qa/1306/itemlist-node-how-you-the-index-the-currently-selected-item)
It would be very convenient if ItemList were method:

`ItemList.get_select_index`

which returns the index of the selected list item.

**Comment by akien-mga** [comment]
That's a good idea.
The main issue however is that the ItemList can be used in single-select or multi-select mode, so the method would have to return either an index or an array of indexes depending on the mode.. That may be why up to now it was not implemented, letting users relying on signals instead.

**Comment by DimitriyPS** [comment]
In fact, you can always return an array:
1. the length of the array = 0 - no selected items
2. the array length is >0 - there are selected items

If I chose single-select, I can do without the extra checks call:
ItemList.get_select_index[0]

I can't speak for everyone, but for me personally this decision is fully satisfied.

**Comment by akien-mga** [comment]
> ItemList.get_select_index[0]

You couldn't do that, as it would be a function, not a member variable. So it would be `get_select_index()[0]`.

For clarity, I guess the function should be named `get_selected_items()`, what do you think?

**Comment by DimitriyPS** [comment]
> You couldn't do that, as it would be a function, not a member variable. So it would be >`get_select_index()[0]`

Yes, you are right. I was not thinking of the listing rules.

>For clarity, I guess the function should be named `get_selected_items()`, what do you think?

Sorry, I not speak English... so most likely you are right.

**Comment by vnen** [comment]
Closed by #5468.
