### ISSUE TITLE
Get Better Collada Exporter into Blender upstream

### ISSUE THREAD

**Issue by paper-pauper** [godotengine/godot#5457]
[This thread](https://developer.blender.org/D1787) shows many blocking issues that prevent the Blender team from merging BCE. Can't those issues be easily fixed? 

Additionally, the last comment says that the Blender team is working on a Python-based Collada importer to replace OpenCollada for 2.8. Maybe the efforts can be joined and/or parts of BCE can be integrated into their new exporter?

I say this because if the Blender community maintained it, it would get a lot of features in a short time.

**Comment by StraToN** [comment]
AFAIK, @reduz pushed a lot to get his OpenCollada exporter merged into Blender, because the current one is simply broken. Blender devs didn't really seem to accept this, for some reason. I'm not sure I understood the full story though.

**Comment by reduz** [comment]
If anyone wants to take the work doing the changes the Blender guys
requests, feel free to do it

**Comment by akien-mga** [comment]
Would it make sense to move the better collada exporter to its own git repo, and then organize some work on it with the help from interested Blender devs?

**Comment by paper-pauper** [comment]
@akien-mga Please do; I think you can point to it from this repo, but in any case it makes more sense as a standalone repo so that we can use issues, PRs and stuff and they don't have to concern themselves about Godot

@reduz I can't promise anything but I'll try

**Comment by paper-pauper** [comment]
Just for the record - I'm working on this.

Here's the suggested changes (from the Blender review):

* Raw, un-escaped strings written to XML (Using " in object name will break export).
* Temporary mesh data created on every export and never removed.
* Unnecessary string concatenation used on potentially very large strings.
* Path separator written as "/", should be os.sep or use os.path.join(...)
* Replace string concatenation with string formatting, see: https://developer.blender.org/diffusion/BA/browse/master/io_scene_x3d/export_x3d.py
* Follow general conventions for writing XML that are used in the X3D exporter, see: https://developer.blender.org/diffusion/BA/browse/master/io_scene_x3d/export_x3d.py (how strings are formatted, indentation etc..).
* use __slots__ for all classes, saves memory and dynamically defining new attributes isn't used anywhere here (with added advantage typo's in assignment raise an error).
* ~~Pep8 style.~~ (Done in #5480)

@akien-mga Are you still going to make it a separate repo or maybe do you want to wait for all suggested changes to be implemented?

**Comment by akien-mga** [comment]
@paper-pauper Sounds great! I'll move the exporter to a separate repo asap.

**Comment by akien-mga** [comment]
@paper-pauper Done: https://github.com/godotengine/collada-exporter

Could you start opening issues on the new repo for each of the points that you listed?

**Comment by paper-pauper** [comment]
@akien-mga I will in a couple of days, and add other issues as well if I get some time to study the code.

**Comment by paper-pauper** [comment]
Closing this issue, resuming it on the `collada-exporter` tracker.

**Comment by paper-pauper** [comment]
The issue has resumed on godotengine/collada-exporter#31, if anyone is interested...
