### ISSUE TITLE
String typo found while translating

### ISSUE THREAD

**Issue by Bonfi96** [godotengine/godot#5458]
While translating I noticed what could be a typo.
The string I refer to is "Pick a Manu Scene", I would have pulled a request to correct it but i have no idea if it's supposed to be "Menu" or "Main".

**Comment by akien-mga** [comment]
It's supposed to be "Pick a Main Scene".

**Comment by bojidar-bg** [comment]
Closed by e4eb025bfe86df44fed54f93babaa9b193991336 (#5460)
