### ISSUE TITLE
TileMap Alternative Tiles Bug

### ISSUE THREAD

**Issue by Banduck** [godotengine/godot#54594]
### Godot version

v4.0.dev.20211027.official[157cba393]

### System information

Windows 10

### Issue description

If you create an alternative tile and then delete it, the area is automatically dragged even though you don't hold down the right mouse button. 
The only way to stop this is to left click, but by doing this you accidentally add another tile.

### Steps to reproduce

![Lv1B6bxpKk](https://user-images.githubusercontent.com/42905358/140322517-db360b2e-b476-47b1-861f-77f8da07ba2d.gif)

**Comment by KoBeWi** [comment]
Can't reproduce in newest alpha, but maybe I'm testing wrong.
@Banduck Does the issue still happen?

**Comment by Banduck** [comment]
@KoBeWi 
Yes it still happens in v4.0.alpha8.official [cc3ed63af]
https://user-images.githubusercontent.com/42905358/170700056-9e418fee-2178-4601-a949-09fbb74b1846.mp4

**Comment by groud** [comment]
I had this issue on Linux, with Intel integrated graphics. Could you give us your GPU information?

**Comment by Calinou** [comment]
@Banduck Remember that for GitHub video previews to work, you need to have a blank line before *and* after the video URL. I edited your post accordingly, but remember to do this in the future :slightly_smiling_face:

**Comment by groud** [comment]
I can't reproduce either on latest master.

**Comment by Banduck** [comment]
I just tested it in alpha 15, it doesn't happen anymore. I guess it's fixed.
