### ISSUE TITLE
Control with custom dynamic font has a y size of infinity after Win + D (due to DynamicFont oversampling)

### ISSUE THREAD

**Issue by VoNguyenMinhTriet** [godotengine/godot#54590]
### Godot version

3.3.4.stable

### System information

Windows 10

### Issue description

On a project with 2D stretch mode, using show desktop (Windows + D) and then go back makes controls containing text with a dynamic font stretch their y size to infinity.
**Before:**
![image](https://user-images.githubusercontent.com/42998503/140307133-9ed5a0cb-9e52-4eef-8bd8-1262b4c65eef.png)
**After Win + D and restoring:**
![image](https://user-images.githubusercontent.com/42998503/140307259-f5e7af0c-b0a5-4cdc-a778-f286fc417d33.png)
**Inside the inspector (at rect_size):**
![image](https://user-images.githubusercontent.com/42998503/140307423-ae880275-53f2-4369-bc4b-e31a288fd830.png)

I specifically said Windows + D instead of minimizing and restoring, and this only happens on 2D stretch mode.

### Steps to reproduce

Import a custom font like Arial to a project. Create a scene with Control root node and a Label inside. Use a custom DynamicFont for that Label with Arial as the font data. Change project stretch mode to 2D. Run that scene and press Windows + D 2 times.

### Minimal reproduction project

(Deleted due to containing Arial font)

**Comment by VoNguyenMinhTriet** [comment]
Shoot, there is a workaround. Can anybody explain why this happens?

**Comment by akien-mga** [comment]
Well, that's still a bug for when font oversampling is enabled, no?

**Comment by VoNguyenMinhTriet** [comment]
It still is for 3.3.4.stable.

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/47957.

Can you try reproducing this in 3.4rc3? It may have been fixed by https://github.com/godotengine/godot/pull/51973.

**Comment by VoNguyenMinhTriet** [comment]
> This is unrelated to the issue itself, but remember that Microsoft fonts' licenses don't allow you to redistribute the font files. Consider using open source metrics-compatible fonts instead, such as [Arimo](https://fonts.google.com/specimen/Arimo).

Thanks for reminding me! For one second I thought Arial was free to use.

**Comment by VoNguyenMinhTriet** [comment]
I can now confirm this issue is not reproducible in 3.4rc3.

**Comment by Calinou** [comment]
Thanks for testing :slightly_smiling_face: Closing as resolved then.
