### ISSUE TITLE
TileMap Scenes Collection Bug

### ISSUE THREAD

**Issue by Banduck** [godotengine/godot#54592]
### Godot version

v4.0.dev.20211027.official [157cba393]

### System information

Windows 10

### Issue description

By using "Scenes Collection" I have added coins that the player can collect.
When I collect a coin and restart the scene, I get this error message:
```
get_node: Node not found: "@Coin@" (relative to "/root/Node2D/TileMap").
  <C++ Error>    Condition "!node" is true. Returning: nullptr
  <C++ Source>   scene/main/node.cpp:1344 @ get_node()
```

### Steps to reproduce

![eceUNra3eF](https://user-images.githubusercontent.com/42905358/140318919-44b67634-7d7b-45b9-b41a-c589f7e2039c.gif)

### Minimal reproduction project

[SceneCollectionBug.zip](https://github.com/godotengine/godot/files/7474989/SceneCollectionBug.zip)

**Comment by groud** [comment]
The TileMap node handles the scenes it exposes internally. If you free the coin yourself, then the TileMap node cannot access it itself. I think this is likely a documentation issue, as I am not sure I would have a way to solve the problem.

**Comment by Banduck** [comment]
So you shouldn't use scenes that can be freed in the TileMap? or is there another solution?

**Comment by groud** [comment]
Right now the simplest solution would be to set the tile to the empty value using set_cell, instead of freeing it manually.

I'll have a look. I'm not sure it's possible but I may find a way to check if the scene was freed manually.
