### ISSUE TITLE
TileMap collision disappears after renaming scene

### ISSUE THREAD

**Issue by Banduck** [godotengine/godot#54598]
### Godot version

v4.0.dev.20211027.official[157cba3]

### System information

Windows 10

### Issue description

If you create a new scene, insert it into your main scene, and then rename it, the entire collision disappears from the tileset.

### Steps to reproduce

https://user-images.githubusercontent.com/42905358/140352689-547a1c56-e63a-4651-990e-91d22e6d44b8.mp4

### Minimal reproduction project

[TileMapCollisionBug.zip](https://github.com/godotengine/godot/files/7476023/TileMapCollisionBug.zip)

**Comment by Gustavobb** [comment]
I'd like to take a look at this if no one else is working on this already

**Comment by akien-mga** [comment]
May be fixed by #63496, please test when 4.0 alpha 13 is released.

**Comment by KoBeWi** [comment]
Yes, it's fixed on master.
