### ISSUE TITLE
Add Android export option for manifest chunk injection

### ISSUE THREAD

**Issue by jlopezcur** [godotengine/godot#5459]
I have to put the chunks of the manifest in folders of the modules and sometimes I have to change a code for each game (for example: GooglePlayGameServicesAPI), sometimes the chunks are duplicated and I have to delete one (for example: AdMob and GooglePlayGameServicesAPI), so:
- Is a good thing to make as a export option?
- Is in the roadmap of the GodotEngine something like this, or some system for add android modules as plugins or something similar in the near future?

In case that I'm in the good way, I already started this feature adding parameter to the export dialog, and now I am fighting with the injection into the manifest of the APK.

**Comment by akien-mga** [comment]
This is part of the proposals discussed in #18865, so closing as superseded by that issue where further discussion should happen.
