### ISSUE TITLE
Can't open scene with broken dependency on `ext_resource`

### ISSUE THREAD

**Issue by Banduck** [godotengine/godot#54603]
### Godot version

v4.0.dev.20211027.official[157cba3]

### System information

Windows 10

### Issue description

If you rename a file in the File Manager, the scene corrupts.
If you rename the file inside Godot, this does not happen.
However, the scene can be opened again if you just rename the file to its previous name.

![image](https://user-images.githubusercontent.com/42905358/140392573-fbfa847a-bafa-4476-91b3-f997c5802fca.png)
Error:
>   Resource file not found: res://icon2.png.
  scene/resources/resource_format_text.cpp:170 - res://Node2D.tscn:10 - Parse Error: [ext_resource] referenced non-loaded resource at: res://icon2.png
  scene/resources/resource_format_text.cpp:269 - res://Node2D.tscn:10 - Parse Error: [ext_resource] referenced non-loaded resource at: res://icon2.png
  Failed loading resource: res://Node2D.tscn. Make sure resources have been imported by opening the project in the editor at least once.
  editor/editor_data.cpp:554 - Index p_idx = 1 is out of bounds (edited_scene.size() = 1).

### Steps to reproduce

https://user-images.githubusercontent.com/42905358/140392667-4acdabcb-60bd-4508-a111-3b47d14fdc77.mp4

**Comment by akien-mga** [comment]
That's expected, if you rename a file from the file manager, Godot doesn't know about it and can't rename references to it in the scene files. So your scene is now referencing a file which doesn't exist anymore, so it's damaged.

When you rename a file in Godot, it fixes references in scene files to prevent this.

**Comment by Banduck** [comment]
I just tried it in Godot 3, there you can still open the scene after renaming a file, and you get a much more understandable error message:
![image](https://user-images.githubusercontent.com/42905358/140395738-a94f6908-b90a-48c6-bd41-e2fcb5de6a9f.png)

**Comment by KoBeWi** [comment]
You can fix the scene by using Edit Dependencies option and assigning missing resources.
