### ISSUE TITLE
Vulkan: Error when hit play button

### ISSUE THREAD

**Issue by danioscx** [godotengine/godot#54609]
### Godot version

v4.0.dev.custom_build.bbee19395

### System information

Fedora 34 intel i3-6000U Nvidia 920MX

### Issue description

When hit the play not display anything just black screen

![Screenshot from 2021-11-05 03-25-58](https://user-images.githubusercontent.com/32965583/140414882-f7611d09-65c6-4e21-94f4-a21b52625b85.png)

### Steps to reproduce

The Error
```
ERROR: Attempted to free invalid ID: 526975307350511
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8445)
ERROR: Attempted to free invalid ID: 526971012389596
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8445)
ERROR: Attempted to free invalid ID: 527001077154307
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8445)
ERROR: Attempted to free invalid ID: 526996782193388
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8445)
ERROR: Attempted to free invalid ID: 527026846958079
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8445)
ERROR: Attempted to free invalid ID: 527022551997155
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8445)
ERROR: Attempted to free invalid ID: 527052616761850
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8445)
ERROR: Attempted to free invalid ID: 527048321800922
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8445)
ERROR: Attempted to free invalid ID: 527078386565622
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8445)
ERROR: Attempted to free invalid ID: 527074091604717
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8445)
ERROR: Attempted to free invalid ID: 527104156369393
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8445)
ERROR: Attempted to free invalid ID: 527099861408484
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8445)
ERROR: Attempted to free invalid ID: 527129926173165
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8445)
ERROR: Attempted to free invalid ID: 527125631212251
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8445)
ERROR: Attempted to free invalid ID: 527155695976965
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8445)
ERROR: Attempted to free invalid ID: 527151401016017
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8445)
ERROR: Condition "!material" is true.
   at: material_set_shader (servers/rendering/renderer_rd/renderer_storage_rd.cpp:1549)
ERROR: Attempted to free invalid ID: 0
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8445)
ERROR: Attempted to free invalid ID: 0
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8445)
ERROR: Attempted to free invalid ID: 0
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8445)
ERROR: Attempted to free invalid ID: 0
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8445)
ERROR: Attempted to free invalid ID: 0
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8445)
ERROR: 1 shaders of type BokehDofRasterShaderRD were never freed
   at: ~ShaderRD (servers/rendering/renderer_rd/shader_rd.cpp:699)
ERROR: 2 RIDs of type "Framebuffer" were leaked.
   at: _free_rids (drivers/vulkan/rendering_device_vulkan.cpp:8973)
ERROR: 8 RIDs of type "Texture" were leaked.
   at: finalize (drivers/vulkan/rendering_device_vulkan.cpp:9277)```
```

**Comment by Calinou** [comment]
@danioscx Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

Is Godot running on your integrated or dedicated GPU? If it's running on the integrated GPU, try forcing applications to run on the dedicated GPU using `nvidia-settings`.

Also, do you see anything if you resize the window?

**Comment by danioscx** [comment]
> @danioscx Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.
> 
> Is Godot running on your integrated or dedicated GPU? If it's running on the integrated GPU, try forcing applications to run on the dedicated GPU using `nvidia-settings`.
> 
> Also, do you see anything if you resize the window?
My Output terminal
```Vulkan API 1.2.189 - Using Vulkan Device #1: NVIDIA - NVIDIA GeForce 920MX`` 
when i resize the window nothing happend still same

**Comment by danioscx** [comment]
**My Output Terminal**
i'm using NVIDIA 
```Vulkan API 1.2.189 - Using Vulkan Device #1: NVIDIA - NVIDIA GeForce 920MX``
when i resize the window nothing happend still same black screen.

The project is 
- Node3D
- Node3D
- MeshInstance3D
- Camera3D
- DirectionalLight

And No script attach to it

**Comment by warriormaster12** [comment]
I've tested on my desktop and laptop, both had the same problem.

Desktop: 
Manjaro KDE 
Nvidia Gtx 1060 6gb
i5-4570
16 gb ddr3 1600 mhz

Laptop: 
Amd Ryzen 5 2500 U
Vega 8 mobile
16 gb ddr4 2660 mhz

**Comment by warriormaster12** [comment]
Interesting, I got my scene working by having this kind of a node setup. Not having a light sources causes the black screen

![Screenshot_20220101_130826](https://user-images.githubusercontent.com/33091666/147849217-03599dc2-15cb-4e0a-88dd-c4342173d73d.png)

![Screenshot_20220101_130851](https://user-images.githubusercontent.com/33091666/147849227-9955d425-4e72-4a94-96bc-2a8cd11c5701.png)

Forgot to mention that I use build: _Godot Engine v4.0.dev.custom_build.b96428577_

**Comment by Zireael07** [comment]
@warriormaster12: Not having a light source causing it to be black is expected and documented. The OP has errors in terminal  and hasn't mentioned anything about not having light source,

**Comment by warriormaster12** [comment]
Ah I see, my bad

**Comment by Calinou** [comment]
@danioscx Can you (or anyone else) still reproduce this bug in [Godot 4.0.beta3](https://godotengine.org/article/dev-snapshot-godot-4-0-beta-3) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: Since no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
