### ISSUE TITLE
Expose `Viewport.get_listener_2d()` to the scripting API

### ISSUE THREAD

**Issue by mashumafi** [godotengine/godot#54612]
### Godot version

3.4

### System information

All

### Issue description

`get_viewport().get_listener_2d()` does not exist. It would be useful to expose this since current camera is exposed already. I am trying to do some logic that would be a lot easier to do knowing the current Listener2D position. I guess another way could be to expose the global position of a listener in case the there is no Listener2D currently and the center of the screen would be used instead.

### Steps to reproduce

`get_viewport().get_listener_2d()` is an error

### Minimal reproduction project

Above is enough to reproduce

**Comment by akien-mga** [comment]
That's a fact, but you don't describe why it's an issue. This method doesn't exist in the scripting API, that's correct.

**Comment by akien-mga** [comment]
CC @KoBeWi. The 3D `get_listener()` doesn't seem to be exposed either, but both are implemented in C++.

**Comment by KoBeWi** [comment]
Listener2D is a node you need to create yourself, so you can as well keep track of it. It might be tricky with multiple listeners, but you could use groups for this purpose.

That said, since we have methods to get current camera, methods to get current listener wouldn't hurt probably.
