### ISSUE TITLE
Texture Region editor only works after doing with Patch9Frame

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#5461]
**Operating system or device - Godot version:**
Windows 10, 2.1 alpha ba5bc57816999804e3c392e9d1f94b528baa8c18

**Issue description** (what happened, and what was expected):
Dragging LMB does not respond in Texture Region editor with ``Sprite``.
It works after doing with ``Patch9Frame``

**Steps to reproduce:**
![texture_region](https://cloud.githubusercontent.com/assets/8281454/16413324/4233e824-3d6c-11e6-9b23-4f0c880dadb6.gif)

**Link to minimal example project** (optional but very welcome):

**Comment by bojidar-bg** [comment]
@volzhs Does it work if you enable the region boolean in the Sprite's properties?

**Comment by volzhs** [comment]
@bojidar-bg Region on/off in sprite inspector does nothing either.

**Comment by MarianoGnu** [comment]
I remember having fixed this before the pull request, looks like it got messed up during rebase with AtlasTexture
