### ISSUE TITLE
AnimationTree repeats the methods and properties that trigger the last frame of the acyclic animation

### ISSUE THREAD

**Issue by magian1127** [godotengine/godot#54619]
### Godot version

3.x Latest

### System information

windows 10 

### Issue description

AnimationTree repeats the methods and properties that trigger the last frame of the acyclic animation.
I only pressed the button once.
As shown in the figure, I don't know whether it is a bug or a feature?
How can I keep the last frame of the current animation instead of switching to the next animation to solve this problem?

AnimationTree 会重复触发非循环动画的最后一帧的方法和属性.
我只按了一次Button.
如图所示,不我知道是BUG还是特性?
如何可以保持当前动画的最后一帧,而不是切换到下一个动画来解决这个问题?

![image](https://user-images.githubusercontent.com/14800320/140462922-bd83ca87-d245-4c22-a383-099d63955ebd.png)

![image](https://user-images.githubusercontent.com/14800320/140462982-7da488fa-186f-4d5d-a63a-fdd73f3833ee.png)
![image](https://user-images.githubusercontent.com/14800320/140463003-a86a7c32-ff06-4f00-ba2b-392e3206308d.png)

**Comment by timothyqiu** [comment]
See also: #51576

**Comment by magian1127** [comment]
After testing #51576, it is feasible.
经过测试#51576,可行.
