### ISSUE TITLE
Visual Instance layer and DirectionalLight3D shadows don't work together

### ISSUE THREAD

**Issue by Cop46** [godotengine/godot#54613]
### Godot version

3.3.4.stable.officiel [faf3f883d] and vulkan git

### System information

Windows 10, GLES3 and Vulkan, nvidia rtx 2080S

### Issue description

The layer of visual instance doesn't work correctly with the Shadows in the stable release and the dev vulkan version.
The first "control" is on the layer 1 and the second on the layer 2.

![scene](https://user-images.githubusercontent.com/32778861/140432302-79e3b7d7-972c-4a84-af74-53d7fa528265.png)
![CameraView](https://user-images.githubusercontent.com/32778861/140432306-dbdeab5d-1772-4614-84fb-a7912e04de81.png)

### Steps to reproduce

Just place one camera and meshs with visual instance on layer 1 and one camera and mesh on layer 2 with one directionnal light.

### Minimal reproduction project

[Testombre.zip](https://github.com/godotengine/godot/files/7479382/Testombre.zip)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/43827, which already reported the issue for `3.x`. That issue is reporting two unrelated bugs at the same time, so I'll leave this one open.

**Comment by markusneg** [comment]
OmniLight and SpotLight are affected by this as well. At least in 3.4.3.

**Comment by akien-mga** [comment]
Fixed by #61841.
