### ISSUE TITLE
AnimatedSprite animation is displayed twice.

### ISSUE THREAD

**Issue by Banduck** [godotengine/godot#54637]
### Godot version

v4.0.dev.20211027.official [157cba393]

### System information

Windows 10

### Issue description

The animation dropdown list always shows the currently selected animation twice.

### Steps to reproduce

<img width="124" alt="Godot4_nQvhca0M7j" src="https://user-images.githubusercontent.com/42905358/140554910-931967f3-4a5e-47a8-b430-13d00c035e78.png"> <- There are only these 2 animations.
<img width="229" alt="Godot4_Lq2NQ1mKMa" src="https://user-images.githubusercontent.com/42905358/140554942-c7731ae4-ba39-4f70-8e81-6d583c1b7889.png">
<img width="231" alt="Godot4_3BRLmbDm8N" src="https://user-images.githubusercontent.com/42905358/140554953-f792f7c6-ec49-4b43-80c2-93c36158f667.png">

**Comment by Calinou** [comment]
@Banduck Can you reproduce this in 3.4 as well, or does this only happen in 4.0.dev?

**Comment by Banduck** [comment]
@Calinou It only happens in 4.0.dev

**Comment by jmb462** [comment]
I've investigate on this issue and I found the bug.
I can fix it but what is the attended behiavor ?
Does the animation list need to be just sorted alphabeticaly or should the selected animation be always the first of the list.

If there is 3 animations A, B, C and C is current, should we have : 

![image](https://user-images.githubusercontent.com/3649998/140570958-6795f6e8-c96b-4ac0-86a7-0d3c8447ad8c.png)

or just alphabetic order ?

**Comment by Banduck** [comment]
@jmb462 In Godot 3 it was in alphabetical order, so I guess that's the expected order.
