### ISSUE TITLE
Godot Physics CylinderShape volume calculation wrong

### ISSUE THREAD

**Issue by briansemrau** [godotengine/godot#54636]
### Godot version

Both 3.x and 4.0

### System information

W10

### Issue description

I noticed the volume calculation for cylinders isn't correct. Should be `πr²h`, not `πr²h+(4/3)πr³`.

(Note that these functions are erroneously named `get_area`. See #54616 for a 4.0 fix.)

master:
https://github.com/godotengine/godot/blob/56cfebbe98ef18d91b891dbbde96081343d5b4cc/servers/physics_3d/godot_shape_3d.h#L259

3.x:
https://github.com/godotengine/godot/blob/14c366ddd7b016fc62c6cd3b940ffa2c1fb34726/servers/physics/shape_sw.h#L271

### Steps to reproduce

N/A

**Comment by pouleyKetchoupp** [comment]
Ah yes, thanks for catching this! I copied the one from capsule and totally forgot to update it :D
