### ISSUE TITLE
Input.is_joy_known() and joy_connection_changed signal are confused when plugging and unplugging mixed Xinput and DirectInput joysticks

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#5464]
**Operating system or device - Godot version:**

Tested on official 2.0.3stable win64, and on custom 2.1alpha compiled by @calinou few days ago. 
Running under Windows 8.1 64.

**Issue description** (what happened, and what was expected):

`I'M HAVING TROUBLE EXPLAINING THIS ISSUE CLEARLY AND SIMPLY`
_so please, in case my description appears confusing, follow the step by step guide below to reproduce the issue and read the minimal example project script to have a better understanding of what i'm talking about._

Before running the project, you have a USB Xinput controller (like XBOX360 gamepad) and a USB DirectInput controller (like Thrustmaster dual analog 3) that are connected at the same time.

When you run the project, the Xinput controller will have device number 0, and the DirectInput controller will have device number 1.

Still at runtime, if you unplug the DirectInput controller, the signal callback ``joy_connection_changed`` will receive a device number 0 instead of 1, and ``Input.is_joy_known(0)`` will return false instead of true, and ``Input.is_joy_know(1)`` will return true instead of false.

When you connect theDirectInput controler again, ``joy_connection_changed`` will receive a device number 1 (which is correct), but ``Input.is_joy_known(0)`` will still return false instead of true.

**Steps to reproduce:**
Using the minimal example project, follow this step by step guide.

1) BEFORE RUNNING THE PROJECT, plug an USB Xinput controller (like Xbox 360 controller) and a DirectInput USB controller (like a Thrustmaster dual analog 3).

2) run the example project.

3) you should read :
- "joy 0 : XInput Gamepad"
- "joy 1 : Thrustmaster Dual Analog 3.2"
- "joy 2 :" should be grayed
- "joy 3 :" should be grayed

4) press your controllers buttons to verify their device number as returned to _Input(event).
- XInput controller device number should be 0.
- DirectInput controller should be 1.

5) unplug the DirectInput controller.

6) You'll notice that "joy 0 : XInput Gamepad" will vanish instead of "joy1", and that the signal callback joy_connection_changed() will receive device_id 0 instead of 1.

7) press your Xinput controller buttons to verify its device number. 
It still should be 0.

8) plug the DirectInput controller back, and notice that this time the signal callback joy_connection_changed() will receive device_id 1.

9) unplug and replug the DirectInput controller and see that the device_id is 0 when unplugging, and 1 when replugging.

**Link to minimal example project** (optional but very welcome):

https://github.com/SuperUserNameMan/godot_issue_minimal_example/tree/master/input_is_joy_known

**Comment by akien-mga** [comment]
Ping @Hinsbart

**Comment by SuperUserNameMan** [comment]
I think the confusion could come from this line :
https://github.com/godotengine/godot/blob/57e1387199c96473007bfa2d430e8cf6cedfc5ff/platform/windows/joystick.cpp#L286

If i understood correctly, i think it should be :
````
input->joy_connection_changed( d_joysticks[id].id, false, "");
````

**Comment by SuperUserNameMan** [comment]
so after compiling godot, i confirm this is this line that was causing the issue.
