### ISSUE TITLE
GDScript 2.0: Nested Arrays do not accept an empty array as a function parameter's default value

### ISSUE THREAD

**Issue by ucenna** [godotengine/godot#54643]
### Godot version

4.0.dev.578460f7f

### System information

Windows 10

### Issue description

when setting the type and default value of a function paremeter, nested arrays will not accept an empty array.

This throws a `Type of default value for parameter "arr" (Array) is not compatible with parameter type (Array[Array])`
```
func my_func(arr : Array[Array] = []) -> void:
    pass
```

Of note, this doesn't throw anything:
``` var arr : Array[Array] = [] ```

### Steps to reproduce

define this function:
```
func my_func(arr : Array[Array] = []) -> void:
    pass
```

*Bugsquad edit (keywords for easier searching): optional, argument*

**Comment by vonagam** [comment]
I think this one should be fixed on master already because part of array PR was merged after assignables unification. Still worth linking to show where the fix came from.
