### ISSUE TITLE
"Audio Mic Record Demo" not working on Godot 3.4

### ISSUE THREAD

**Issue by tangentstorm** [godotengine/godot#54652]
**Which demo project is affected:**
godot-demo-projects/audio/mic_record/

**OS/device including version:**
windows 10, using Godot 3.4

**Issue description:**
The demo is able to play the example song. Attempting to record and play back audio from the mic causes the window to become "not responding".

The project works fine in Godot 3.3 on the same machine, so it's possible the problem is in Godot itself.

**Comment by Calinou** [comment]
[The mic record demo hasn't had any changes since 3.3, so this is an engine issue.](https://github.com/godotengine/godot-demo-projects/commits/master/audio/mic_record)

Can you reproduce this in [any of the earlier 3.4 betas and RCs](https://downloads.tuxfamily.org/godotengine/3.4/) to determine when the regression started?

**Comment by RedMser** [comment]
It's also crashing the same way with Godot 4.0 (after updating the demo file to make it run). Bisect shows 880d4703a41e1b205ff606eda184384166229c6e is the first bad commit. Not sure if this specific commit was also backported to 3.4 though.

**Comment by akien-mga** [comment]
> It's also crashing the same way with Godot 4.0 (after updating the demo file to make it run). Bisect shows 880d470 is the first bad commit. Not sure if this specific commit was also backported to 3.4 though.

CC @benjarmstrong @EIREXE

But indeed that commit hasn't been backported to the `3.x` branch yet so it shouldn't be affecting 3.4, this might be two separate issues.

**Comment by benjarmstrong** [comment]
Can you run the project with the --verbose flag and reproduce the crash? 

My thinking is the issue may be triggered by your system audio driver and how it affects the WASAPI initialization

**Comment by RedMser** [comment]
> Can you run the project with the --verbose flag and reproduce the crash?

Here you go:
```
WASAPI: Activated device using IAudioClient3 interface
WASAPI: wFormatTag = 65534
WASAPI: nChannels = 2
WASAPI: nSamplesPerSec = 48000
WASAPI: nAvgBytesPerSec = 384000
WASAPI: nBlockAlign = 8
WASAPI: wBitsPerSample = 32
WASAPI: cbSize = 22
WASAPI: mix_rate = 48000
WASAPI: fundamental_period_frames = 480
WASAPI: min_period_frames = 480
WASAPI: max_period_frames = 480
WASAPI: selected a period frame size of 480
WASAPI: detected 2 channels
WASAPI: audio buffer frames: 480 calculated latency: 10ms
```
and in a separate block at the end of the log (probably the microphone):
```
WASAPI: wFormatTag = 65534
WASAPI: nChannels = 1
WASAPI: nSamplesPerSec = 44100
WASAPI: nAvgBytesPerSec = 176400
WASAPI: nBlockAlign = 4
WASAPI: wBitsPerSample = 32
WASAPI: cbSize = 22
```

**Comment by benjarmstrong** [comment]
I'm getting the exact same behaviour in 4.0.

I'll take a look at 3.4 and see if I can reproduce the error

**Comment by benjarmstrong** [comment]
Behaviour in 3.4 is slightly different to 4.0. I think we're looking at 2 different issues.

The issue OP is describing (in Godot 3.4) is in this function, called when you attempt to play back recorded audio:

        func _on_PlayButton_pressed():
	        print("Play button pressed")
	        print(recording)
	        print(recording.format)
	        print(recording.mix_rate)
	        print(recording.stereo)
	        var data = recording.get_data()
	        print(data)
	        print(data.size())
	        $AudioStreamPlayer.stream = recording
	        $AudioStreamPlayer.play()

print(data) is the culprit, which prints a byte array of the entire recording to the console. It doesn't actually crash Godot, but it does make it unresponsive for a very, very long time. So it doesn't look like an issue with the engine itself, but rather with the demo project. We can simply remove that line.

In 4.0 I experience an immediate crash when launching the project. I'll do a bit of tinkering and see if I can find the cause.

**Comment by benjarmstrong** [comment]
I've filed a [bug report for the demo projects repo](https://github.com/godotengine/godot-demo-projects/issues/661). Since this is not an issue with Godot 3.4 I believe this thread should be closed. 

I'll open a new issue for 4.0 crashing immediately with the demo project if there isn't one already.

**Comment by akien-mga** [comment]
Moved to https://github.com/godotengine/godot-demo-projects/issues/661.

**Comment by GeorgeS2019** [comment]
@benjarmstrong   

This work
```
var data = recording.get_data().hex_encode()
print(data)
```
This does not work
```
var data = recording.get_data()
print(data)
```

**Comment by benjarmstrong** [comment]
@GeorgeS2019

The [merged fix for the demo project](https://github.com/godotengine/godot-demo-projects/pull/662) simply removes the print statement [as discussed in the corresponding issue](https://github.com/godotengine/godot-demo-projects/issues/661). Good to know we can still print huge arrays without hanging the engine though 👍
