### ISSUE TITLE
a method to know if a joystick is plugged

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#5465]
**Operating system or device - Godot version:**
Official 2.0.3stable and custom 2.1alpha

**Issue description** (what happened, and what was expected):

I've found no method to know if a joystick is already plugged.

The workarounds are : 
- scan device from 0 to 15 using ``Input.is_joy_known()`` ; but, if I understood correctly, it will only return true if the joystick has a mapping.
- ask the player to press a button and capture the device number in event.

I would like to know in advance how many joysticks are already connected without asking to the players to press buttons.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by Hinsbart** [comment]
Good catch.
Should we have a method that returns an array of connected device IDs or do you want to query the connection status of individual devices? Or maybe both ;)

**Comment by SuperUserNameMan** [comment]
I think i'd be happy with any one of these two methods, so I guess that having both would be a bliss ^^

**Comment by Hinsbart** [comment]
On a second thought, I think the first one will be enough.
With that, one can easily replicate the other one: 
```gdscript
if device_id in Input.get_connected_joysticks():
```

**Comment by kakoeimon** [comment]
I used this method to find out if a joystick is plugged.
if Input.get_joy_name(0):

Without joystick Input.get_joy_name() returns an empty string which can be used in as false.

**Comment by SuperUserNameMan** [comment]
@kakoeimon : oh thanks for the idea. I did not think of it !
