### ISSUE TITLE
parse_json() does not work in 4.0

### ISSUE THREAD

**Issue by rayanmargham** [godotengine/godot#54668]
### Godot version

4.0 Dev

### System information

Windows 11, Vega 8

### Issue description

When using parse_json() in godot 4 the function does not seem to exist, i think this might be a bug.
![image](https://user-images.githubusercontent.com/69608259/140613925-2135e842-96f6-498c-8c83-e12eeb3e7932.png)

### Steps to reproduce

Open Godot 4.0 Dev
Create a Project
Create a Scene
Attach a Script to that scene
attempt to use the parse_json() function

**Comment by Chaosus** [comment]
It's not a bug, just this function moved to JSON class. So all you have to do is declare the instance of this class (in the global space preferably):
` var json = JSON.new()` and use `json.parse`

**Comment by rayanmargham** [comment]
![image](https://user-images.githubusercontent.com/69608259/140614494-72d79d90-b5a0-42c2-a689-b02322770850.png)
Thank you so much
