### ISSUE TITLE
[3.4] Bug with transparent ParticleSystem and transparent Shader

### ISSUE THREAD

**Issue by AgentSmith0** [godotengine/godot#54661]
### Godot version

3.4-stable

### System information

Linux, GLES3

### Issue description

When turning the camera around, the particle system in front of the water shader won't always be visible. The bug is also in Godot 3.3.4 present.

### Steps to reproduce

In the attached reproduction project, open the scene test.tscn. You will see a water shader and a transparent particle system. When you turn the camera around the particles, you will see that the particles aren't visible sometimes in front of the water.

### Minimal reproduction project

[transparency-bug.zip](https://github.com/godotengine/godot/files/7490358/transparency-bug.zip)

**Comment by Calinou** [comment]
This is a known [rendering limitation](https://docs.godotengine.org/en/stable/tutorials/3d/3d_rendering_limitations.html#transparency-sorting). You may be able to work it around by changing the water material's Render Priority property, but it won't always work in all situations.

**Comment by clayjohn** [comment]
The solution here is to adjust the AABB of your particle nodes. In the MRP, the center of the AABB for the particles nodes is slightly below the water plane so the Renderer sorts them behind the water. Either the Particles need to be slightly higher, or their AABBs need to be adjusted so they do no go so far below the actual particle nodes. 

For future reference, Godot sorts based on the relative distance between the camera and the center of an objects AABB. If you have a huge AABB that doesn't accurately represent the bounds of your object, you may run into sorting issues. In general, it is best to keep your AABBs tight and your transparent objects far away from one another.
