### ISSUE TITLE
Unknown crash not being picked up in debugger

### ISSUE THREAD

**Issue by Nosrick** [godotengine/godot#5466]
**Operating system or device - Godot version:**
Windows 7, Godot 2.0.3 stable

**Issue description** (what happened, and what was expected):
When clicking a treasure card control after selecting a player, the game crashes.
It's supposed to assign the card to the player.

**Steps to reproduce:**
(This will include a brief tutorial on the game)
Select a room to place
Place a room on a treasure node (go for green for now, otherwise you'll die horribly)
Combat begins
Click a card, then click an enemy to use the card on them
Defeat all enemies
The game will now enter the treasure reward state
Click a player, then click the treasure card
The game will crash, in a way not picked up by the debugger

**Link to minimal example project** (optional but very welcome):
Cannot reproduce in minimal example project, but here's a link to my project.
https://bitbucket.org/nosrick/monquest

EDIT:
It turns out the editor actually catches some sort of error, which is attached.
![cusersjamesdesktopgodot_v2 0 3_stable_win64 e_2016-06-28_17-29-15](https://cloud.githubusercontent.com/assets/1487089/16423948/fd9100b4-3d55-11e6-8efe-5e0a241f6514.png)

**Comment by Nosrick** [comment]
Looks like it's to do with a resource calling free() instead of queue_free().
If you still want to look into the bug, please browse the repo and checkout the tag UNKNOWN_CRASH.

**Comment by reduz** [comment]
I can't find the tag

**Comment by reduz** [comment]
well, if you can reproduce let me know and will reopen
