### ISSUE TITLE
[3.4] macOS export broken for PCK file over 2GB when exporting to a ZIP archive

### ISSUE THREAD

**Issue by AgentSmith0** [godotengine/godot#54670]
### Godot version

3.4-stable

### System information

Linux, GLES3

### Issue description

When you export for MacOS with Godot 3.4 the generated PCK file will have a size of 0. This wasn't a problem with Godot 3.3.4. There are no error messages in the editor.

### Steps to reproduce

Just try to export a project for MacOS in Godot 3.4.

**Comment by Calinou** [comment]
@AgentSmith0 Can you reproduce this in any of the [3.4 betas and RCs](https://downloads.tuxfamily.org/godotengine/3.4/ to determine when the regression started?

**Comment by akien-mga** [comment]
I can't reproduce the issue, exporting from Linux to macOS gives me a 29M ZIP file (for a simple test project with a single scene). Please provide more information on your configuration and project.

**Comment by AgentSmith0** [comment]
That's correct, but when you extract the zip file or look into it, you will see that the PCK file has a size of 0, no matter how big your project is. With the other files in the ZIP, you have a archive size of around 29MB. I will try to find out when the regression has started.

**Comment by bruvzg** [comment]
Can't reproduce. Exporting from macOS for the macOS seems to work OK, tested with Mono and non-Mono builds of 3.4-stable, exporting as ZIP and as DMG.

ZIP size of exported empty project (new project with the empty Node2D scene added and set as start-up scene) is 29.8 MB, PCK size is 7 KB.

How large is your project? Is it reproducible with the empty project? If it is, upload a ZIP file to test.

**Comment by akien-mga** [comment]
Same as @bruvzg for me exporting from Linux, the PCK is 8.9 KiB for a trivial test project I have laying around.

**Comment by AgentSmith0** [comment]
I tried exporting a very small project and it worked. Probably this happens because my projects has a size of over 2GB (e. g. when exporting to Windows).

**Comment by bruvzg** [comment]
I can reproduce it with large PCK when exporting as ZIP, DMG export is fine. I guess it's an issue with `get_file_as_array` and vector size limitation.

**Comment by akien-mga** [comment]
The fix will be on 3.4.1 and 3.5.

**Comment by AgentSmith0** [comment]
Alright, thank you all very much!
