### ISSUE TITLE
'apksigner' returned with error #2

### ISSUE THREAD

**Issue by enorrmann** [godotengine/godot#54675]
### Godot version

3.4.rc2.official,3.4.rc3.official

### System information

ubuntu 21.10 openjdk8

### Issue description

the export for android process failed with 
'apksigner' returned with error #2

exporting the same project with same keys in godot version 3.2.stable works as intended

### Steps to reproduce

export for android

**Comment by Calinou** [comment]
> exporting the same project with same keys in godot version 3.2.stable works as intended

Did it work with Godot 3.3.x?

**Comment by enorrmann** [comment]
> > exporting the same project with same keys in godot version 3.2.stable works as intended
> 
> Did it work with Godot 3.3.x?

3.3.stable : same error 
3.4.stable : same error

**Comment by akien-mga** [comment]
You probably need to recreate your keystore to be compatible with 3.3+. See the command in the current docs to generate it.

**Comment by enorrmann** [comment]
> You probably need to recreate your keystore to be compatible with 3.3+. See the command in the current docs to generate it.

I followed this instructions 
https://docs.godotengine.org/en/3.4/getting_started/workflow/export/exporting_for_android.html
and still not working

**Comment by zaddok** [comment]
I get the same error as well, using Godot 3.5.1 and the instructions at:

https://docs.godotengine.org/en/latest/tutorials/export/exporting_for_android.html
