### ISSUE TITLE
ring_buffer<T> breaks builds on c++20 (and versions < c++14)

### ISSUE THREAD

**Issue by sehoffmann** [godotengine/godot#54674]
### Godot version

3.x, 4.x

### System information

n/a

### Issue description

https://github.com/godotengine/godot/blob/d18cbdf5e4a1132bfc5f581195f6bf7c3b9bed79/core/templates/ring_buffer.h#L214

Obviously this is very odd code (didn't even know that this is even valid). However, apparently this was accidentally  introduced in C++14. They remove it in C++20 now, which means that the coder works only with c++14 <= version < c++20. See https://stackoverflow.com/questions/63513984/can-class-template-constructors-have-a-redundant-template-parameter-list-in-c2

This code is both in 4.x as well as 3.x

### Steps to reproduce

n/a

**Comment by ShlomiRex** [comment]
Tried compiling godot with MSVC c++ but get tons of errors, spesifically 'Compiler Error C2666': https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c2666?view=msvc-160.
Perhaps we can withhold this untill we have C++20 support.

**Comment by sehoffmann** [comment]
` Perhaps we can withhold this untill we have C++20 support.`

Only the `<T>` need to be removed from both the ctor and dtor.

**Comment by akien-mga** [comment]
Fixed by #91208.
