### ISSUE TITLE
Empty <description> tags in --doctool class references

### ISSUE THREAD

**Issue by exigow** [godotengine/godot#54686]
### Godot version

3.3.4.stable.arch_linux

### System information

Linux 5.4.148

### Issue description

Generated class references with CLI option `--doctool` always outputs XML files with empty `<description>`, `<brief_description>` and `<tutorials>` tags. The documentation does not contain clear information on how to enable such descriptions in generated output.

### Steps to reproduce

Run `godot --doctool .`

**Comment by Calinou** [comment]
You need to fill in those tags manually after generating the XML class reference. `--doctool` does not support reading comments from the C++ source code to embed them in the class reference.

**Comment by exigow** [comment]
Thanks for the clarification.
