### ISSUE TITLE
move_and_collide gets KinematicBody2D stuck on static obstacles if test_move is used

### ISSUE THREAD

**Issue by L4Vo5** [godotengine/godot#54685]
### Godot version

3.4.stable

### System information

Windows 10

### Issue description

In a KinematicBody2D, `move_and_collide `will sometimes get the object slightly inside collision shapes. If using `test_move `to check for collisions at the direction of movement before moving, the object will get stuck unless it goes directly backwards.
This happens even with non-rotated, rectangle collision shapes, and without using delta to ensure integer positions.
Expected behaviour: after a move_and_collide, the body should not be inside another body, `test_move(transform, Vector2.ZERO)` should return false, and further `test_move`'s perpendicular to the collision should return false too.
Tested in v3.4-stable_win64.
The problem does not occur in v3.3.4-stable_win64, but using test_move for the current position is still occasionally true when it shouldn't (the checks in other directions work as expected, even when that one is wrong).

### Steps to reproduce

Code like this brings the issue, used in either of the _process functions
```
	if upP and not test_move(transform, Vector2(0, -1)):
		move_and_collide(Vector2(0, -1) * spd)
	if downP and not test_move(transform, Vector2(0, +1)):
		move_and_collide(Vector2(0, 1) * spd)
	if leftP and not test_move(transform, Vector2(-1, 0)):
		move_and_collide(Vector2(-1, 0) * spd)
	if rightP and not test_move(transform, Vector2(+1, 0)):
		move_and_collide(Vector2(1, 0) * spd)
```
where upP, downP, leftP and rightP are true only if the corresponding key is pressed, and spd is relatively big (it seems the bigger it is, the more consistently the bug happens)
The minimal reproduction project has:
- Two objects for the "player" to collide with, one a StaticBody2D and the other one a TileMap. Try running into both of them and pressing the perpendicular directions (e.g. collide coming from the right, and press up/down). It kind of feels like the TileMap has the issue more often than the rigid body, specially when lowering the spd variable, but it's hard to tell.
- a "Check" button that will skip the `test_move`'s if it's false, making the object move normally (the expected behaviour that should happen even when Check is on).
- A SpinBox to tweak the Player speed
-  Five labels that reflect the result of doing `test_move` for the current position, and 1 pixel up, down, left, and right.

### Minimal reproduction project

[collision issue test.zip](https://github.com/godotengine/godot/files/7491303/collision.issue.test.zip)

**Comment by akien-mga** [comment]
CC @godotengine/physics
