### ISSUE TITLE
RayCast2D returning incorrect hit locations in TileMap collisions

### ISSUE THREAD

**Issue by gokiburikin** [godotengine/godot#54695]
### Godot version

v4.0.dev.calinou [78931aa04]

### System information

Windows 10

### Issue description

RayCast2D's return too soon collision points when testing against TileMap physics layers. This behaviour does not exist when casting against RectangleShapes of the same size (tested at 16x16) or longer RectangleShapes.

The TileSet collision is a single encompassing rectangle. The behaviour persists even if the rectangle is extended beyond 16x16.

This does not occur in Godot 3.4 Stable.
This does occur in v4.0.dev.20211004.official [2e8cba0bd] and in v4.0.dev.calinou [78931aa04].

https://user-images.githubusercontent.com/3820082/140634283-9286e553-2d69-46e2-adcf-bbf452f53414.mp4

### Steps to reproduce

Open the attached MRP in Godot 4.0 and play the main scene. The RayCast2D will return unexpected results in the TileMap collision.

### Minimal reproduction project

[raycast-test-4.zip](https://github.com/godotengine/godot/files/7491804/raycast-test-4.zip)

**Comment by groud** [comment]
This is likely an issue with the fact I used polygon shapes internally, compared to the rectangle shapes.
The issue likely lies in the physics server side. CC @pouleyKetchoupp.
