### ISSUE TITLE
Setting global_transform.origin before adding node to scene tree causes error

### ISSUE THREAD

**Issue by AgentSmith0** [godotengine/godot#54704]
### Godot version

3.4-stable

### System information

Linux, GLES3

### Issue description

When setting `global_transform.origin` before the node is added to scene tree, the following error ocours:
```
E 0:00:57.141   get_global_transform: Condition "!is_inside_tree()" is true. Returned: Transform()
  <C++ Source>  scene/3d/spatial.cpp:272 @ get_global_transform()
  <Stack Trace> Game.gd:101 @ _ready()
```

This issue is also present in Godot 3.3.4. I don't think it's a regression.

### Steps to reproduce

I used the following code:

```
extends Spatial

func _ready():
	var test_node = Spatial.new()
	test_node.global_transform.origin = Vector3(10, 10, 10) # works, but gives error
	#test_node.translation = Vector3(10, 10, 10) # works and does the same (but gives no error)
	call_deferred("add_child", test_node)
```

### Minimal reproduction project

[global_transform-bug.zip](https://github.com/godotengine/godot/files/7492014/global_transform-bug.zip)

Just play the test.tscn file and have a look at the code in test.gd.

**Comment by akien-mga** [comment]
That's normal, **global** transform only makes sense when in the scene tree. There's no global when not in tree.
