### ISSUE TITLE
svgz files outputs an errors on godot 3.4

### ISSUE THREAD

**Issue by XDRiVE888** [godotengine/godot#54700]
### Godot version

v3.4.stable.official [206ba70f4]

### System information

Windows 10

### Issue description

Inkscape svgz files in asset folder outputs an errors than project opens, on export file or than double clicked at svgz file from godot.
The output errors look like this:  
Image width must be greater than 0.
 core/image.cpp:1481 - Condition "data.size() == 0" is true.
 modules/webp/image_loader_webp.cpp:79 - Condition "p_image.is_null() || p_image->empty()" is true. Returned: PoolVector<uint8_t>()

### Steps to reproduce

Store svgz file in asset folder on opened godot 3.4 project or close/open godot editor with svgz files, or double click on svgz file from godot 3.4 editor.

**Comment by Calinou** [comment]
@XDRiVE888 Can you reproduce this on Godot 3.3.4? Also, can you reproduce this with a uncompressed `.svg` file?

**Comment by XDRiVE888** [comment]
> @XDRiVE888 Can you reproduce this on Godot 3.3.4? Also, can you reproduce this with a uncompressed `.svg` file?

Yes, you right, with Godot 3.3.4 this error appears too. But uncopressed svg don't reproduces that error.

**Comment by akien-mga** [comment]
Indeed, gzip compressed SVG files (`.svgz`) are actually not supported by Godot currently. It's a mistake that the extension was listed as a valid one, #56862 will remove it.
