### ISSUE TITLE
Godot 4.0-dev fails importing a specific glTF 2.0 file

### ISSUE THREAD

**Issue by Alexia-AT-Digitecnology** [godotengine/godot#54708]
### Godot version

4.0-dev (20211027)

### System information

Windows 10 (NVIDIA Geforce GTX 1060 6 GB, 64 GB RAM, Core i7)

### Issue description

When you import this glTF2.0 file containing a scene [(MainScene.glb)](https://drive.google.com/file/d/1YCnH2xnrHK0g_P4kgXVoWYPTbENrshFW/view?usp=sharing) Godot 4.0-dev imports but the textures have glitches in the importing, but when I import the same glTF 2.0 scene file in Godot 3.4 the file imports well without glitches. In blender 2.93 the glTF 2.0 file imports correctly.

Godot 4.0-dev glb glitched:
![Godot 4 glb glitched](https://user-images.githubusercontent.com/18708610/140642525-ba830b81-a2b4-4c6b-9566-3ef12d15dc63.png)

Godot 3.4 glb imported correctly:
![Godot 3 glb imported correctly](https://user-images.githubusercontent.com/18708610/140642540-360c9cd1-df8b-44ae-b891-cad74494c1f8.png)

### Steps to reproduce

- Download Godot 4.0-dev 20211027 from tuxfamily repo [here](https://downloads.tuxfamily.org/godotengine/testing/4.0/4.0-dev.20211027/Godot_v4.0-dev.20211027_win64.exe.zip)
- Open Godot
- Create a new project
- Download glTF 2.0 scene file  [(here)](https://drive.google.com/file/d/1YCnH2xnrHK0g_P4kgXVoWYPTbENrshFW/view?usp=sharing)
- Copy the glb file into godot project directory
- Preview imported glb file
- Then the glitches appears

### Minimal reproduction project

There is no need of a project. You can make your own with the glTF scene file.

**Comment by Alexia-AT-Digitecnology** [comment]
This is the glTF 2.0 file imported in blender scene:
![Blender scene](https://user-images.githubusercontent.com/18708610/140643437-24f69bf2-2046-4e82-84c8-72ba243dc7c4.png)

This is in godot 3.4 and 4.0-dev imported scene:
![Godot scene](https://user-images.githubusercontent.com/18708610/140643448-c534e54f-54d4-4a01-9622-968bc12235f2.png)

It seems some inconsistencies in this part too in the two godot versions.

**Comment by fire** [comment]
First contact.

1. the floor is flickering. Changing the transparent mode to transparent changes observed results. The floor doesn't flicker.

**Comment by Calinou** [comment]
Does this occur if you disable LOD generation in the glTF import settings and click **Reimport**?

**Comment by fire** [comment]
LOD option does nothing and therefore changing mesh lod has no effect.

**Comment by fire** [comment]
My guess is that it's related to the AABB being negative.

![image](https://user-images.githubusercontent.com/32321/148156403-74f3353f-51c2-4a57-83d4-45ed1be4184a.png)

@clayjohn @reduz @JFonS @lawnjelly Any ideas?

**Comment by Whimfoome** [comment]
> My guess is that it's related to the AABB being negative.

In my game I have a lot of models and they import fine, still throwing a lot of AABB being negative errors though.

**Comment by fire** [comment]
Can confirm the scene still flickers on my fork of godot engine.

**Comment by lawnjelly** [comment]
Could well be if you are setting a negative AABB.

I'm not familiar with the parts of the engine that calculate the AABB, or reduz BVH that is currently used for culling in 4.0. I expect it just transforms the base AABB and expects it to be positive (or zero area). But am just guessing here.

So if you have a negative scaling you may have to flip the AABB on import before setting it on the MeshInstance (if you can find the code that does this, there may be existing compensation for this, at least in 3.x, or maybe it is your job in the importer).

**Comment by lawnjelly** [comment]
Had another little look at this today with @fire , he exported a smaller version (or separated) of the scene, as the original scene was crashing 3.x and blender 2.82 when I tried to import.

It seem to work fine for me in vulkan mobile, but displays the flickering in vulkan clustered.

This would seem to rule out the importer, and probably also juan's BVH which is used for the render tree (as presumably it is used the same in both vulkan backends).

I've also been getting a bunch of RID errors, which I don't know is common for guys using Godot 4 as I mainly work on 3.x.

**Comment by fire** [comment]
This bug is still valid on beta1.

**Comment by fire** [comment]
Can someone check https://github.com/godotengine/godot/pull/67176? if the bug is related?

**Comment by clayjohn** [comment]
> Can someone check #67176? if the bug is related?

Just checked, https://github.com/godotengine/godot/pull/67176 does indeed fix this bug :)

Closing as fixed by https://github.com/godotengine/godot/pull/67176
