### ISSUE TITLE
Exported project doesn't use correct app icon in Windows File Explorer

### ISSUE THREAD

**Issue by AgentSmith0** [godotengine/godot#54712]
### Godot version

3.4-stable

### System information

Linux, GLES3

### Issue description

In the Godot Editor I selected a custom app icon for Windows. When launching my app, the window header shows the correct icon, but in the Windows File Explorer there is still the default Godot icon.

EDIT: I use embedded PCK for export.

### Steps to reproduce

Export a project with custom app icons for Windows. Then go to the file explorer and you will see that the .exe file uses still the default Godot icon.

**Comment by AgentSmith0** [comment]
Maybe a duplicate of https://github.com/godotengine/godot/issues/36629 or https://github.com/godotengine/godot/issues/47240

**Comment by Chaosus** [comment]
I suppose you should read this -  https://docs.godotengine.org/en/stable/getting_started/workflow/export/changing_application_icon_for_windows.html

**Comment by Calinou** [comment]
> EDIT: I use embedded PCK for export.

That's why it broke: https://github.com/godotengine/godot/issues/33466
