### ISSUE TITLE
GDScript: Map & Reduce with lambdas always returns nil

### ISSUE THREAD

**Issue by zedutch** [godotengine/godot#54737]
### Godot version

4.0.dev (c89061e982)

### System information

Windows 10, RTX 2080, Vulkan

### Issue description

When using lambdas in array.map or array.reduce, the lambda function always returns nil. It doesn't when referencing a function with the same signature as the lambda.

### Steps to reproduce

Example script:
```
func _ready() -> void:
	var numbers := [0.0, 1.0, 2.0]
	print("Numbers: ", numbers)
	print("[Reduce] Using function: ", numbers.reduce(self.reduce_numbers, 0.0))
	print("[Reduce] Using lambda: ", numbers.reduce(func(accum: float, val: float): accum + val, 0.0))
	print("[Map] Using function: ", numbers.map(self.map_numbers))
	print("[Map] Using lambda: ", numbers.map(func(num): num + 1))


func reduce_numbers(accum: float, val: float) -> float:
	return accum + val


func map_numbers(num: float) -> float:
	return num + 1.0
```
Output is:
```
Numbers: [0, 1, 2]
[Reduce] Using function: 3
[Reduce] Using lambda: null
[Map] Using function: [1, 2, 3]
[Map] Using lambda: [null, null, null]
```

### Minimal reproduction project

[lambda_mapreduce_null.zip](https://github.com/godotengine/godot/files/7493050/lambda_mapreduce_null.zip)

**Comment by VedatGunel** [comment]
I think you need to explicitly return the value from the lambda function.
For example, this works:

`print("[Map] Using lambda: ", numbers.map(func(num): return num + 1))`

**Comment by zedutch** [comment]
> I think you need to explicitly return the value from the lambda function.

You are absolutely right! I got confused because in most programming languages you don't need a return if the lambda function is only one line, but I guess GDScript lambdas always require it...
