### ISSUE TITLE
Mono build fails, tools segfault on launch.

### ISSUE THREAD

**Issue by int-72h** [godotengine/godot#54739]
### Godot version

4.0.dev(c89061e)

### System information

Arch Linux x86_64 

### Issue description

After following the first build instruction to build the temporary binary, I tried running
```bin/godot.linuxbsd.tools.64.mono --generate-mono-glue modules/mono/glue```
as per the instructions. This immadiately gave me a segmentation fault.
GDB was of no use as it said 
```During startup program terminated with signal SIGSEGV, Segmentation fault.```

### Steps to reproduce

Follow the first 2 instructions of the Mono build guide.
The tools binary should segfault instead of generating the glue.

**Comment by raulsntos** [comment]
I can't reproduce it in the same commit with Pop OS 21.04, it could be an issue with your setup. Make sure you have installed all the [dependencies](https://docs.godotengine.org/en/stable/development/compiling/compiling_for_x11.html#requirements).

**Comment by int-72h** [comment]
I have all the dependencies listed and up to date.

**Comment by raulsntos** [comment]
> GDB was of no use as it said
> `During startup program terminated with signal SIGSEGV, Segmentation fault.`

Have you tried catching all exceptions before running? See this [stackoverflow](https://stackoverflow.com/questions/55815912/how-do-i-debug-an-executable-with-gdb-when-it-crashes-during-startup/55981669).

**Comment by int-72h** [comment]
OK I was able to get it to build successfully. I was using a prerelease version of the ntfs3 kernel driver, and I think this was causing some issues. Closing.
