### ISSUE TITLE
3.4 editor theme is missing icons for disabled checked items

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#54742]
### Godot version

3.4

### System information

W10

### Issue description

As originally mentioned in https://github.com/godotengine/godot/pull/37755#issuecomment-962563163, the editor theme in Godot 3.4 is missing icons for disabled checked and unchecked (radio) checkboxes. On master they were added in #51722

The icons might be worth backporting probably.

**Comment by Deozaan** [comment]
> the editor theme in Godot 3.4 is missing icons for disabled checked and unchecked (radio) checkboxes

This seemed ambiguous to me, so I just wanted to clarify that all of the disabled checkbox icons are missing from the theme in 3.4. Not just the radio checkbox icons.

**Comment by timothyqiu** [comment]
Closed by #59857
