### ISSUE TITLE
Ability to duplicate arrays/dictionaries directly.

### ISSUE THREAD

**Issue by hetdegon** [godotengine/godot#5475]
During an IRC conversation it was noted there is no straightforward way to easily make copies of arrays and dictionaries. It'd be a great feature to have, something like var mydictcopy = mydict.duplicate() (and likewise for arrays) or something similar to that.

Someone noted mydictcopy = Dictionary(mydict) produces a valid copy, but he described it as a bug, so it doesn't sound like a reliable method, unless we can ensure this behavior will be preserved.

**Comment by vnen** [comment]
The related issue about `mydictcopy = Dictionary(mydict)` being a bug (since it should not be exposed to script) is #5277.

**Comment by hetdegon** [comment]
Since #5277 has been fixed, does that mean there's currently no way to duplicate arrays/dicts?

**Comment by Calinou** [comment]
This issue seems to be a duplicate of https://github.com/godotengine/godot/issues/3697, so I'm closing this; please continue discussion there.
