### ISSUE TITLE
Godot Window Scales akward

### ISSUE THREAD

**Issue by SchneckeddeF** [godotengine/godot#54767]
### Godot version

3.4.stable

### System information

Ubuntu

### Issue description

Godot scales at maximized mode very ![GodotIssue](https://user-images.githubusercontent.com/87531743/140781658-7cbafbf0-3434-47b4-a913-6cbd5e96ac11.png) just look at the picture..

### Steps to reproduce

Install Godot on Ubuntu an make it Fullscreen...

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/31133. As a workaround, set the editor display scale to 75% in the Editor Settings *or* decrease the main font size to 12.
