### ISSUE TITLE
Godot freezes when unsupported Unicode character is placed in shader editor. 

### ISSUE THREAD

**Issue by jak6jak** [godotengine/godot#54769]
### Godot version

v4.0.dev.custom_build [64a27b]

### System information

Windows 10 Vulkan Clustered

### Issue description

When pasting the symbol ¶ or any other Unicode such as the ones found in Latin-1 Supplement into Godot's shader editor it freezes because the never ending error messages:
```USER` ERROR: U_ILLEGAL_ARGUMENT_ERROR
   at: ScriptIterator::ScriptIterator (modules\text_server_adv\script_iterator.cpp:71) - Method/function failed.
Unicode parsing error: Invalid unicode codepoint ffffffc2.
USER ERROR: U_ILLEGAL_ARGUMENT_ERROR```
In Godot 3.4 this does not freeze Godot but just gives an error saying invalid symbol. 

### Steps to reproduce

Type a Unicode symbol outside of normal range such as the ones in Latin-1 supplement examples being: ¡ ¢ £
(taken from: https://en.wikipedia.org/wiki/List_of_Unicode_characters) into main.gdshader
Notice how the Editor hangs because of the errors being spitted out.

### Minimal reproduction project

[Shader Imports.zip](https://github.com/godotengine/godot/files/7498898/Shader.Imports.zip)

**Comment by Calinou** [comment]
cc @bruvzg
