### ISSUE TITLE
Script Editor: "Delete line" not working properly when multiple lines are selected

### ISSUE THREAD

**Issue by mrimvo** [godotengine/godot#54766]
### Godot version

Godot Engine v4.0.dev.calinou.bd31af37b

### System information

Ubuntu 18.04

### Issue description

When working in the GDScript Editor, I often mark several lines and use a keyboard shortcut to evoke the "delete line" editing command.

Note that most of the time I don't select the first and the last line completely: The way I do it most of the time is like this:

![Auswahl_836](https://user-images.githubusercontent.com/6030346/140778645-6b1a409a-ceac-4c4a-a63a-c2902fcfffb7.png)

**Expected behavior:** delete all marked lines completely. Especially, delete line 3 and line 12 completely.

**Observed Behavor:** Almost always, the last line is not deleted. Sometimes much more lines are deleted than actually marked.

It feels very confusing and unreliable.

### Steps to reproduce

1. Open any GDScript file with the editor
2. mark multiple lines of code as shown above
3. press Ctrl+Shift+K (or in the Menu: Edit -> Delete Line)
4. the last line is still there, or much more lines get deleted than intended.

**Comment by Calinou** [comment]
@mrimvo Can you reproduce this in 3.4?

**Comment by mrimvo** [comment]
@Calinou in 3.4 I used this feature heavily and it always works as expected
