### ISSUE TITLE
Label letter missing

### ISSUE THREAD

**Issue by Dustray** [godotengine/godot#54762]
### Godot version

3.3.2 - 3.4 stable (mono)

### System information

Windows 11 Enterprise 22000.282

### Issue description

I use DynamicFont to Label, but sometimes letter missing:
![QQ截图20211108223645](https://user-images.githubusercontent.com/19183422/140763364-85c51ae4-243b-4d21-aa29-43ddd908445a.jpg)
The complete text is as follows:
![QQ截图20211108223655](https://user-images.githubusercontent.com/19183422/140763331-c6fcda27-aaf7-468c-a76f-f711314ffa7e.jpg)

### Steps to reproduce

1. Create a scene, and put a label in, with DynamicFont
2. Instantiate the scene in the C# script, and add to a VBoxContainer
3. It happened, but not every time

**Comment by Calinou** [comment]
@Dustray Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

In particular, you need to make sure the font file you're using contains all the required characters.

**Comment by akien-mga** [comment]
No answer, so closing.
