### ISSUE TITLE
Crash when opening godot 3.4

### ISSUE THREAD

**Issue by jul2040** [godotengine/godot#54770]
### Godot version

3.4 stable

### System information

Ubuntu 20.04.3 AMD Ryzen 5 2500U

### Issue description

When I open 3.4 for the first time, I get a black window for a second, and then this error:
```

Godot Engine v3.4.stable.official.206ba70f4 - https://godotengine.org
OpenGL ES 3.0 Renderer: AMD Radeon(TM) Vega 8 Graphics (RAVEN, DRM 3.36.0, 5.6.11-050611-generic, LLVM 12.0.0)
OpenGL ES Batching: ON

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v3.4.stable.official (206ba70f4b2a3eac4455bb21bd7c8af76285bd86)
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f3851448210] (??:0)
[2] godot() [0x131237f] (??:0)
[3] /usr/lib/x86_64-linux-gnu/libLLVM-12.so.1(+0x34ad1fa) [0x7f384bf301fa] (??:0)
-- END OF BACKTRACE --
================================================================
Aborted (core dumped)
```

I was able to run Godot 3.3.4

### Steps to reproduce

Download Godot 3.4 editor and run it from the command line

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
@jul2040 Can you try to get a full backtrace using a [debug build](https://github.com/Calinou/godot-debug-builds)? This will tell you where the issue comes from.

**Comment by rob-mur** [comment]
Do you happen to be using windows 11? I'm getting a crash in 3.4 on windows 11 and when I've downgraded back to 3.3.4 that version is also crashing on loading any project. If I get some time I'll try and run a debug build, but if you are on 11 that some recent update could be the culprit.

**Comment by akien-mga** [comment]
@rob-mur You're probably running into a different issue: #54076. This is not a crash, just the Windows Terminal killing the application when it shouldn't.

OP's issue is an actual crash on Linux though.

**Comment by rob-mur** [comment]
Ah, you are quite correct - apologies!

**Comment by jul2040** [comment]
@Calinou 

I tried running a debug build, and it worked fine, then I re-downloaded a build from the godot website, and it worked fine.

I think the original file got corrupted when I downloaded it.
