### ISSUE TITLE
Popup not showing in godot

### ISSUE THREAD

**Issue by RockZombie123** [godotengine/godot#54776]
### Godot version

v3.3.3.stable.custom_build [b973f997f]

### System information

Raspberry pi 4

### Issue description

So I've made a little start menu that I want to actually function.  Here's how it looks like:
![2021-11-06-234747_1920x1080_scrot](https://user-images.githubusercontent.com/91627371/140793931-8a7a4af5-6eff-4f56-8292-7e0d10097ca3.png)
I want to spawn a new window when I click `new game` but currently I am expecting the window to show up when I click`esc`. Here is the code for producing the window:
```
extends WindowDialog

func process(delta: float) -> void:
	if Input.isactionpressed("Esc"):
		var popuppause = get_node("escmenu")
		popuppause.rectposition = Vector2(-76,-63)
		popuppause.popup()


```
Should I change `WindowDialog` to `escmenu`? If not, what should I do?

### Steps to reproduce

```
extends WindowDialog

func process(delta: float) -> void:
	if Input.isactionpressed("Esc"):
		var popuppause = get_node("escmenu")
		popuppause.rectposition = Vector2(-76,-63)
		popuppause.popup()

```

**Comment by Calinou** [comment]
I don't recommend using WindowDialog for a pause menu. Instead, use a generic control node (such as a Panel) where you toggle its `visible` property.

WindowDialog is meant to be used for draggable windows, which you rarely need in a game.

**Comment by kleonc** [comment]
> Here is the code for producing the window:
> 
> ```
> extends WindowDialog
> 
> func process(delta: float) -> void:
> 	if Input.isactionpressed("Esc"):
> 		var popuppause = get_node("escmenu")
> 		popuppause.rectposition = Vector2(-76,-63)
> 		popuppause.popup()
> ```
> 
> Should I change `WindowDialog` to `escmenu`? If not, what should I do?

You have that script attached to the `WindowDialog`, no need to obtain it at all (its `self`). This should work:
```
func process(delta: float) -> void:
 	if Input.is_action_pressed("Esc"):
 		rectposition = Vector2(-76,-63)
 		popup()
```

I don't see a bug in here.

**Comment by RockZombie123** [comment]
@kleonc This doesn't work either.

**Comment by RockZombie123** [comment]
I just figured out that to make the window show, I need:
```
func _ready():
       show()
       pass
```
