### ISSUE TITLE
[3.4] Unable to scroll in Theme Editor preview while in control picker mode

### ISSUE THREAD

**Issue by fire540** [godotengine/godot#54778]
### Godot version

3.4.stable

### System information

Windows 10, GLES 3

### Issue description

When control picker mode is active in the new Theme Editor, it is not possible to scroll in the theme preview window. It should be possible to scroll whether control picker mode is active or not.

Control picker inactive, scrolling enabled:
![image](https://user-images.githubusercontent.com/67974470/140804080-9e87121f-d299-4a87-9028-8bd0a87539c2.png)

Control picker active, scrolling disabled:
![image](https://user-images.githubusercontent.com/67974470/140804164-8dc99005-d413-4fe2-953b-4755300df0bc.png)

### Steps to reproduce

1. Open the Theme Editor in Godot 3.4
2. Resize the Theme Editor to be small enough that a scroll bar appears on the right side of the preview window
3. Enable control picker by pressing the color picker icon in the top left corner
4. Attempt to scroll in the theme preview window

**Comment by Chaosus** [comment]
cc @pycbouh

**Comment by Ybaedbaenn** [comment]
I have the same issue on the same version: Windows 10, GLES3, NVIDIA GeForce GT 540M, graphics driver version 23.21.13.9135, Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz.
