### ISSUE TITLE
2D Default Gravity Vector - X component not working. (not loaded properly?)

### ISSUE THREAD

**Issue by rgrams** [godotengine/godot#5477]
**Operating system or device - Godot version:**
Windows 7, 64 bit. Tried with 2.0.3 stable official, and recent June builds. 

**Issue description** (what happened, and what was expected):
If I set the default gravity vector in Project Settings >> Physics 2d to have any non-zero x component, it does not function when I play the game. The gravity in y works, but nothing in x. Actually it worked right once, but that's never happened again it at least a dozen tries. When the editor is restarted, the x component is reset to zero. However, if I open the engine.cfg file in a text editor, it seems to have the correct values:  "[physics_2d]default_gravity_vector=Vector2(0.17, 0.26)" or whatever.

**Comment by reduz** [comment]
there is a problem with the current code for engine.cfg loadin/saving that does not support vector2, in Godot 3.0 we'll move the parsing of this configuration file to VariantParser so all settings like this should work, but in the meantime there is no fix :( you'll have to use code. Very sorry :(

**Comment by bojidar-bg** [comment]
I think this was fixed already in 2.2, is this correct? :smiley:

**Comment by reduz** [comment]
this is fixed, closing
