### ISSUE TITLE
Particle trails glitch for the first frame they are visible

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#54771]
### Godot version

v4.0.dev.custom_build [ce634e03d]

### System information

Linux Arch, Radeon RX 590

### Issue description

Trails connect to the origin (of the particle system if in local coords, of the world if not in local coords) in the first frame in which they are visible. Length secs of the trail doesn't seem to influence the length of the glitch.

https://user-images.githubusercontent.com/7917475/140791807-bf21b971-37b2-417e-81a9-ce92d7743637.mp4

See in particular:
![Screenshot_2021-11-08_18-39-45](https://user-images.githubusercontent.com/7917475/140791855-599c540e-ca1c-4972-a5d1-92a8a956416d.png)

### Steps to reproduce

Open "TrailTest.tscn" in the provided reproduction project

### Minimal reproduction project

[GodotVFX4.zip](https://github.com/godotengine/godot/files/7498984/GodotVFX4.zip)

**Comment by Calinou** [comment]
Reopening, as https://github.com/godotengine/godot/pull/58549 was reverted by https://github.com/godotengine/godot/pull/58660.
