### ISSUE TITLE
Tile atlas view changes size when switching tools

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#54787]
### Godot version

38c698c

### System information

W10

### Issue description

![isPVN6IkSH](https://user-images.githubusercontent.com/2223172/140830828-1cf5f559-0cde-4497-95a9-ac3740fd23c4.gif)
Also notice how tileset changes appearance of some tiles slightly.

### Steps to reproduce

1. Open TileMap with TileSet
2. Change between Select and Paint tools

**Comment by groud** [comment]
I can't reproduce this on master. Can you confirm it is fixed ?

**Comment by KoBeWi** [comment]
Seems fixed.
