### ISSUE TITLE
[3.4] Incorrect sub-pixel drawing behavior using `display/window/stretch/shrink` setting

### ISSUE THREAD

**Issue by sjerpsthomas** [godotengine/godot#54785]
### Godot version

3.4.stable

### System information

Windows 10, GLES3, GeForce GTX 1660 SUPER

### Issue description

When stretching the screen in the settings (using the parameter `display/window/stretch/shrink`), sub-pixel drawing behaviors are no longer drawn with stretched pixels.
Instead, they are drawn as if the pixel stretch were set to 1, and the camera were zoomed in.

**The images below illustrate a scene with a drawn line and a scaled-down sprite, using a screen stretch of 4.**

### Behavior in Godot 3.3.2.stable
![image](https://user-images.githubusercontent.com/53572785/140825911-0000bcbe-1b00-44c5-b4f8-9170330eab5d.png)

### Behavior in Godot 3.4.stable
![image](https://user-images.githubusercontent.com/53572785/140826062-16268f39-a04a-4f9f-b117-52409cf6c741.png)

### More detailed system information
Version: Godot Engine v3.4.stable.official.206ba70f4
OpenGL ES 3.0 Renderer: GeForce GTX 1660 SUPER/PCIe/SSE2
OpenGL ES Batching: ON
OS: Windows 10 Home 21H1, 19043.1288
Processor: Intel Core i7-6700 @ 3.40 GHz
Graphics card: NVIDIA GeForce GTX 1660 SUPER
Graphics card driver version: 27.21.14.5671

### Steps to reproduce

1. In a new scene, place a downscaled sprite / instance of draw_line / ...
2. Increase the screen stretch in the settings or with `get_tree().set_screen_stretch(...)`.
3. Run the scene. Note the visual change between 3.3 and 3.4.

### Minimal reproduction project

[ScreenStretchMinimalReproducableProject.zip](https://github.com/godotengine/godot/files/7500481/ScreenStretchMinimalReproducableProject.zip)

**Comment by Calinou** [comment]
Following the merge of https://github.com/godotengine/godot/pull/52137, this is now expected when not using the `viewport` stretch mode. If you want a pixel art appearance, set the stretch mode to `viewport` in the project settings.

**Comment by sjerpsthomas** [comment]
@Calinou Alright, I've set the stretch mode to `viewport` now, and the scene now has a pixel art appearance, as before.
However, changing the screen stretch through `get_tree().set_screen_stretch(...)` now causes the game to stop rendering.
The scene still processes and takes input, but the graphics do not refresh, and when resizing the window, it turns black.

The project with updated settings:
[ScreenStretchMinimalReproducableProject.zip](https://github.com/godotengine/godot/files/7500606/ScreenStretchMinimalReproducableProject.zip)

**Comment by Calinou** [comment]
> However, changing the screen stretch through get_tree().set_screen_stretch(...) now causes the game to stop rendering.

Double-check that your graphics driver isn't forcing MSAA: https://github.com/godotengine/godot/issues/18320
