### ISSUE TITLE
Reset to Rest Pose in Skeleton2D menu fails

### ISSUE THREAD

**Issue by irslutz** [godotengine/godot#54793]
### Godot version

v3.4.stable.official [206ba70f4]

### System information

Windows 10

### Issue description

I have rigged a paper doll guy, mapped bones to verts for deformation, and created animations.
![image](https://user-images.githubusercontent.com/7278221/140848504-cd504c68-fe5a-476a-926a-c16546e5e21e.png)

In Godot v3.3.4.stable.official [faf3f883d] I can select the Skeleton2D and use the Skeleton2D menu to "Set Bones to Rest Pose." The result looks good. However, in Godot v3.4.stable.official [206ba70f4] this does not work as expected.
![image](https://user-images.githubusercontent.com/7278221/140848672-cd453c39-c73e-49d9-96a2-6e794edd48af.png)

When I select "Reset to Rest Pose" in the newer version, the Polygon2D assets return to rest pose, however the bones do not. This seems to scramble the mapping of verts to bones for all animations.
![image](https://user-images.githubusercontent.com/7278221/140849351-32fcf29f-f245-42fe-b9e1-861a6562646a.png)

### Steps to reproduce

1. Load a Skeleton that has been mapped to Polygon2Ds authored in v3.3.4.stable.official [faf3f883d]
2. Select the Skeleton2D
3. Use the Skeleton2D menu to "reset to rest pose"

Observe: Polygon2Ds correctly return to rest pose, bones do not.

4. Try to play an animation

Observe: Now that bones have new offsets animations no longer look correct.

### Minimal reproduction project

[RestPoseBug.zip](https://github.com/godotengine/godot/files/7501439/RestPoseBug.zip)

**Comment by Calinou** [comment]
@irslutz  Can you reproduce this in any of the [3.4 betas and RCs](https://downloads.tuxfamily.org/godotengine/3.4/) to determine when the regression started?

**Comment by irslutz** [comment]
@Calinou I did a little bracketing for the test case. Beta2~beta4 seemed good, the first reproduction of the bug was **beta 5**.

**Comment by akien-mga** [comment]
See this change in beta 5: https://github.com/godotengine/godot/commit/de3f454c27c4598961583b2ac86b67a159478ee6

That's only a rename, maybe that's the source of confusion? The 3.4 equivalent of "Set Bones to Rest Pose" is "Overwrite Rest Pose".

**Comment by irslutz** [comment]
OK @akien-mga is correct, functionality between the two options is consistent.

- "Make Rest Pose (From Bones)" has become "Reset to Rest Pose"
- "Set Bones to Rest Pose" has become "Overwrite Rest Pose"

In each case the new label provides identical functionality. But it seems that those two labels should be switched, at least in English.

**Comment by Calinou** [comment]
The button texts were tweaked in https://github.com/godotengine/godot/pull/52317 following the advice from https://github.com/godotengine/godot/issues/28124.

@bitbutter Did I get them the wrong way around? I don't really understand right now.

**Comment by irslutz** [comment]
It looks like that suggestion was to change words and order. The words have changed but the order is the same.

**Comment by irslutz** [comment]
@Calinou I have tried to illustrate what it appears the request from #28124
![image1724](https://user-images.githubusercontent.com/7278221/141039489-6076e712-ce04-42a7-81bd-c07fd027b4a3.png)

It appears that the functionality that was tied to Make Rest Pose (From Bones) should have the text Overwrite Rest Pose and be put in the lower position. The functionality tied to Set Bones to Rest Pose should be matched to the text Reset to Rest Pose and be in the upper position.

The text is in the correct position, but the functionality is reversed.

I hope this is helpful.

**Comment by Neketek** [comment]
> OK @akien-mga is correct, functionality between the two options is consistent.
> 
> * "Make Rest Pose (From Bones)" has become "Reset to Rest Pose"
> * "Set Bones to Rest Pose" has become "Overwrite Rest Pose"
> 
> In each case the new label provides identical functionality. But it seems that those two labels should be switched, at least in English.
> 
> I notice current documentation uses old terms.

I can't agree more, this labeling is very confusing.

**Comment by akien-mga** [comment]
> I notice current documentation uses old terms.

Can you point to the documentation which still uses the old terms?
