### ISSUE TITLE
Inconsistent output of `InputEventKey.as_text()` with Czech keyboard layout on Linux

### ISSUE THREAD

**Issue by mnn** [godotengine/godot#54797]
### Godot version

3.4.stable

### System information

Linux (Manjaro)

### Issue description

It mixes "key from keyboard layout" with "physical key" (or maybe US keyboard layout?).

This is an output of me pressing top number keys from 1 to 0 (from left to right):

```
<<Plus>> 43 49
<<2>> 50 50
<<3>> 51 51
<<4>> 52 52
<<5>> 53 53
<<6>> 54 54
<<ý>> 253 55
<<á>> 225 56
<<í>> 237 57
<<é>> 233 48
```

Either everything should be a number (US keyboard layout interpretation) `1234567890` or it should be `+ěščřžýáíé` (CS keyboard layout). Now it's somehow mixed together.

### Steps to reproduce

Select a non-US keyboard layout (e.g. Czech) and call `as_text` on `InputEventKey`. Try pressing keys which are different to US layout.

### Minimal reproduction project

```gdscript
func _input(event: InputEvent) -> void:
	if event is InputEventKey && event.is_pressed():
		print("<<%s>> %s %s" % [event.as_text(), event.scancode, event.physical_scancode])
```

**Comment by akien-mga** [comment]
Works fine with French keyboard layout on Linux:
```
<<Ampersand>> 38 49
<<é>> 233 50
<<QuoteDbl>> 34 51
<<Apostrophe>> 39 52
<<ParenLeft>> 40 53
<<Minus>> 45 54
<<è>> 232 55
<<UnderScore>> 95 56
<<ç>> 231 57
<<à>> 224 48
<<ParenRight>> 41 45
<<Equal>> 61 61
```

I can reproduce the issue with Czech keyboard layout (`setxkbmap cz`), I guess it does something uncommon with the 2-6 key overrides. CC @bruvzg

**Comment by mnn** [comment]
I also noticed that for a key `´` (two keys to the right from the number `0` on top row) I am getting `<<Unknown>> 33554431 33554431` which would be ok, but it happens only every second key press which might be an issue. It looks like every first key of this key is ignored, it behaves like when writing text - for example you press a `´` key and then an `a` key to get a `á` symbol.

**Comment by akien-mga** [comment]
> I also noticed that for a key `´` (two keys to the right from the number `0` on top row) I am getting `<<Unknown>> 33554431 33554431` which would be ok, but it happens only every second key press which might be an issue. It looks like every first press of this key is ignored, it behaves like when writing text - for example you press a `´` key and then an `a` key to get a `á` symbol.

That's normal, it's a dead key, so the first keypress holds the diacritic for you to put on a letter. <kbd>´</kbd> + <kbd>E</kbd> should give you "é".

**Comment by mnn** [comment]
So it's not possible to use for key bindings at all? Or would I have to use some other input event?

**Comment by Kersoph** [comment]
As a hint as Czech and French keyboards are mentioned:
Scancodes for CH-Keyboards are not fully working as well with .as_text()

E.g.:
`ö is translates with "Apostrophe Key"
ä is translates with "BackSlash Key"
ü is translates with "Semicolon Key"
also not working are for example éà£!è$¨^'§`
Using the Unicode field and casting it to a letter works. Probably the reason why LineEdit works perfect. I'm posting here because I'm unsure if it is connected and if it's may be already solved for the Unicode case as well for the Czech layout? Then it may has the same cause.

**Comment by bruvzg** [comment]
> ö is translated with "Apostrophe Key"
> ä is translated with "BackSlash Key"
> ü is translated with "Semicolon Key"

There's no such thing as scan code for `ö`, so this is full expected, use Unicode value for this.

See [Microsoft Keyboard Scan Code Specification](http://download.microsoft.com/download/1/6/1/161ba512-40e2-4cc9-843a-923143f3456c/scancode.doc) for the list of standard PS/2 scan codes (all keyboard still use the same set).
