### ISSUE TITLE
FBX Model with Animations working in 3.x, but not correctly in 4.x

### ISSUE THREAD

**Issue by Whimfoome** [godotengine/godot#54800]
### Godot version

3.4.stable and 4.x custom

### System information

Arch Linux

### Issue description

This model is extracted from [unity package](https://assetstore.unity.com/packages/3d/characters/animals/insects/egypt-pack-spider-demo-165807), to use in my game. When I was testing Godot 4, I noticed that the model is completely wrong, but in Godot 3.x, everything is working as expected.

Godot 3.4:
![image](https://user-images.githubusercontent.com/42871796/140916248-6c4d15b9-66a5-496d-a036-a275303862d5.png)

Godot 4 with no animation playing:
![image](https://user-images.githubusercontent.com/42871796/140916406-408381dc-b8f9-401c-a0bc-d17d441e86f2.png)

Godot 4 with animation playing:
![image](https://user-images.githubusercontent.com/42871796/140916546-aa8c4ac7-6d91-441e-a2bb-5cc884a0f249.png)

I tried converting the format to gltf with Blender, but without success, Blender couldn't import it.
I found this [FBX-glTF convertor](https://github.com/cocos-creator/FBX-glTF-conv), with which I converted the model to gltf, and could successfully import it to Blender and Godot, without any issues.

### Steps to reproduce

1. Create new project
2. Import the Spider.fbx to the project files
3. Open in Godot 3 and Godot 4 to see the difference

### Minimal reproduction project

Here are the model files instead:
[Spider.zip](https://github.com/godotengine/godot/files/7504336/Spider.zip)

To convert the files manually with [the tool](https://github.com/cocos-creator/FBX-glTF-conv) on Linux, you can use wine

**Comment by fire** [comment]
The FBX importer needs to be update for https://github.com/godotengine/godot/pull/53765.

I believe the changes are `get_rest_pose * pose` and `rest_pose.affine_inverse() * pose()` on setting.

**Comment by norrath-hero** [comment]
I'm so frustrated with the FBX support for many years, I simply give it up now, I use fbx2gltf everytime.

https://github.com/facebookincubator/FBX2glTF

it make the broken FBX support even useless

**Comment by akien-mga** [comment]
This is probably fixed with the new FBX importer using [FBX2glTF](https://github.com/V-Sekai/FBX2glTF/releases).
You can test it in Godot 4.0 alpha 6: https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-6
This new importer might also be backported for the `3.x` branch eventually.

If you still find issues with these models using the new importer, we suggest opening a new issue with details about the problems in Godot 4.0 alpha 6 or later.
