### ISSUE TITLE
[Master] Cannot make editor plugin using tool keyword GDScript

### ISSUE THREAD

**Issue by xsellier** [godotengine/godot#54801]
### Godot version

4.0.dev 9444a3f01d3a8c4f49ddf24e3acc65b399ee0609

### System information

Linux binogure 5.14.0-2-amd64 #1 SMP Debian 5.14.9-2 (2021-10-03) x86_64 GNU/Linux

### Issue description

Cannot create in GDScript n editor plugin with the `tool` keyword

### Steps to reproduce

- Launch Godot
- Create a project
- Create a scene and attach a GD script
- Paste the following code:
```gdscript
tool
extends Control
[...]
```

![image](https://user-images.githubusercontent.com/6616005/140929675-c5ae7453-545e-450f-a586-c585aa5ebf7d.png)

**Comment by akien-mga** [comment]
`tool` is no longer a keyword, you should use the `@tool` annotation. See https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_basics.html#annotations

**Comment by xsellier** [comment]
Then there is an issue with the documentation since this recommand to use `tool` and not `@tool`:
https://docs.godotengine.org/en/latest/tutorials/plugins/editor/making_plugins.html

**Comment by akien-mga** [comment]
The documentation for Godot 4.0 is WIP, this page hasn't been updated yet. You can open an issue about it on godot-docs.

**Comment by xsellier** [comment]
Also, I was wondering, is it possible to just say something like that in Godot:
```
`tool` is deprecated and has been replaced by `@tool`
```
Instead of:
```
Unexpected identifier
```
