### ISSUE TITLE
Gridmap fails to join navmeshes

### ISSUE THREAD

**Issue by gokudomatic** [godotengine/godot#5481]
**Operating system or device - Godot version:**
Xubuntu 16.04 64b - Godot Engine V2.1 alpha custom_build (latest from today 06/29/16)

**Issue description** (what happened, and what was expected):
The MeshLibrary I created for my GridMap contains one tile with a navmesh but the cells in the Gridmap don't join together. When I try to calculate a path, no path was found when the end point is in another cell than the start point. Within the same cell, the path is found.

**Steps to reproduce:**

1. Download the blend file from the link
2. Export it as better collada (last git version). Lights are not needed.
3. Import it in a godot project. (animation not needed)
4. Convert the scene to a MeshLibrary
5. Create a scene with a Navigation node and a child node GridMap using the MeshLibrary. Draw some path. 
7. Add a script that calculates a path:
`

        extends Spatial

        func _update_path():
           var nav=get_node("nav") # navigation node
           var begin=Vector3(0.5,0.5,0.5) #start point
           var end=Vector3(10,0.5,0.5) # end point

           var p = nav.get_simple_path(begin,end,true)
           print(p) # should not be empty when a path is found. 

        func _ready():
           _update_path()

`

If the begin and end point are within the same cell, the path is found. But not when they go across two or more cells. Therefore the join of the navmesh didn't occure.

**Link to minimal example project** (optional but very welcome):
Link to blend file:
https://drive.google.com/file/d/0B3WfGYr6k_DGUlpXcE5PQXFzRmM/view?usp=sharing
Link to Collada file (exported from blend file):
https://drive.google.com/file/d/0B3WfGYr6k_DGWlRMdThDLXpPa1E/view?usp=sharing

**Comment by bojidar-bg** [comment]
@Anarchid Ping :P

**Comment by Anarchid** [comment]
Are vertices of the navmesh in your cells coinciding completely? NavMeshes join sub-meshes only by **exact** vertex coordinate match on shared edges. There is no logic to detect intersections etc.

**Comment by gokudomatic** [comment]
Anarchid, your last comment was crucial because it solved my problem.

Indeed I triple checked the mesh to be sure the vertices match perfectly. I was even to the point to not trust blender anymore because of the floating precision problem. But even in the dea file the coordinates were good.
However until now I thought the navigation mesh had to be in 3 dimensions, meaning then to be a cube instead of a plane. And that's because that was done like that in the navigation demo. There was no much information about how to make a navmesh anyway.
But by removing the height of my navmesh, it suddenly worked. Thanks a lot.

I rephrase the solution: the navmesh must be 2 dimensional to work in the GridMap.

**Comment by bojidar-bg** [comment]
@gokudomatic well, if it is a cube, that would probably mean that agents are able to walk on the sides of the cube --- which is rather incorrect...
