### ISSUE TITLE
Copy paste naming bug

### ISSUE THREAD

**Issue by Banduck** [godotengine/godot#54813]
### Godot version

v4.0.dev.20211108.official [596865366]

### System information

Windows 10

### Issue description

When you copy and paste a node, it gets a weird name like: CollisionShape2D -> @CollisionShape2D@23668
I'm not quite sure if this is a bug or if it's intentional, however it was different in the previous build.

### Steps to reproduce

v4.0.dev.20211108.official [596865366]:
![CLxDNlrIjW](https://user-images.githubusercontent.com/42905358/140996783-abe8239a-9a8b-48c4-9e6c-0675f6052c96.gif)
v4.0.dev.20211027.official [157cba393]:
![E2Eaq1o6MF](https://user-images.githubusercontent.com/42905358/140996848-f5cceaaf-0f0d-41d8-9d6b-ed35636db632.gif)

Edit: Okay it is definitely a bug:
<img width="311" alt="Godot4_Pg3hRGsTfH" src="https://user-images.githubusercontent.com/42905358/140997422-e09640b2-591b-4331-a752-7df4cb11bd6f.png">

**Comment by akien-mga** [comment]
That's a consequence of #54072, some calls to `add_child` in the copy-paste logic need the `true` boolean flag. CC @KoBeWi
