### ISSUE TITLE
Godot 4: impossible to restart after creating a TextureAtlas from PNGs

### ISSUE THREAD

**Issue by gustavi** [godotengine/godot#54817]
### Godot version

v4.0.dev.20211108.official.596865366

### System information

Windows 10 64bit - Vulkan API 1.2.141 - GeForce GTX 1660 SUPER

### Issue description

When you create a `TextureAtlas ` from PNGs Godot as you to restart and can not start anymore without remove PNGs `.import` files.

I didn't find any related issue in the past months on GitHub tracker. I only tried it on Windows. I thing it's the same with other images. Same behavior in Godot_v4.0-dev.20211027.

### Steps to reproduce

1. Create a blank project
2. Add PNGs (I used https://www.kenney.nl/assets/toon-characters-1)
3. Select PNG in editor (Screenshot 1)
4. Select "Import" tab on left sidebar
5. Import as `TextureAtlas`
6. Select "Atlas file" and give it a name (the name does not matter)
7. Select "Reimport" button
8. Select "Save Scenes, Re-Import, and Restart" button
9. Wait the engine restart and display a blank pop-up named "Load Errors" (Screenshot 2)

![image](https://user-images.githubusercontent.com/2736557/141005725-e668f88d-8da9-450d-a173-8382ef84c3ec.png)

![image](https://user-images.githubusercontent.com/2736557/141006501-ad30306b-80b0-403c-b04a-4e0abaa1337b.png)

### Minimal reproduction project

[texture-atlas_before.zip](https://github.com/godotengine/godot/files/7508066/texture-atlas_before.zip)

[texture-atlas_after.zip](https://github.com/godotengine/godot/files/7508067/texture-atlas_after.zip)

**Comment by Calinou** [comment]
@gustavi Can you reproduce this on 3.4 as well, or only in `master`?

**Comment by gustavi** [comment]
- 3.4 : 🟢 atlas works
- 4.0-dev.20210727 : 🔴 broken
- 4.0 : 🔴 broken

(tested on Windows only)

**Comment by KoBeWi** [comment]
Still valid in 6a9115b
