### ISSUE TITLE
Keypad navigation in text editor no longer working

### ISSUE THREAD

**Issue by GGalizzi** [godotengine/godot#54814]
### Godot version

v4.0.dev.20211108.official [596865366]

### System information

Manjaro Linux (swaywm)

### Issue description

Seems like there was a regression of https://github.com/godotengine/godot/issues/720

With num lock OFF pressing 7/1/9/3 for home/end/PgUp/PgDn no longer work in the editor. It does on 3.4

### Steps to reproduce

* Open up a script in the godot script editor.

* Turn num lock off

* Press 7, 1, 9, or 3. Nothing happens

**Comment by Calinou** [comment]
This is likely a regression from CodeEdit or input handling changes. cc @Paulb23 @EricEzaM

**Comment by EricEzaM** [comment]
Cannot reproduce on Windows 10

**Comment by Paulb23** [comment]
Seems to be x11 only, as for Windows we remap the keypad input [here](https://github.com/godotengine/godot/blob/master/platform/windows/key_mapping_windows.cpp#L382) so it works. Whereas the x11 mapping [here](https://github.com/godotengine/godot/blob/master/platform/linuxbsd/key_mapping_x11.cpp#L112) used [here](https://github.com/godotengine/godot/blob/master/platform/linuxbsd/key_mapping_x11.cpp#L324) are unchanged.

**Comment by KoBeWi** [comment]
@GGalizzi Can you still reproduce in alpha 6?

**Comment by GGalizzi** [comment]
> @GGalizzi Can you still reproduce in alpha 6?

Yes, still reproducible.
