### ISSUE TITLE
Controls added to Inspector via InspectorPlugin don't match editor theme

### ISSUE THREAD

**Issue by olestourko** [godotengine/godot#54823]
### Godot version

3.3.3 Stable

### System information

Ubuntu 20.04

### Issue description

When adding controls to the Inspector via a plugin, their theme doesn't match the editor's theme.

The `Status` property at the top is added via plugin. Notice how the native controls have a darker background and no border. Controls from the plugin also seem to have a different border when hovered. I'm using Godot's default editor theme.

![Screenshot_20211109_214208](https://user-images.githubusercontent.com/3958783/141040209-a7d7b40a-a5a9-478f-b255-0d2db4a11c29.png)

### Steps to reproduce

Create an Inspector Plugin [as described in the docs](https://docs.godotengine.org/en/stable/tutorials/plugins/editor/inspector_plugins.html) and add some controls to the inspector.

I'm not doing anything fancy; here's the `EditorProperty` I'm inserting:
```
public class BT_EditorProperty : EditorProperty
{
	OptionButton _control;

	public BT_EditorProperty() {
		_control = new OptionButton();
		foreach (string name in Enum.GetNames(typeof(TaskStatus))) {
			_control.AddItem(name);	
		}
		AddFocusable(_control);
		GD.Print(_control.Theme);
		AddChild(_control);
	}
}
```

**Comment by timothyqiu** [comment]
I think you have to set the `flat` property to `true`.

**Comment by pycbouh** [comment]
Indeed, as @timothyqiu mentioned, `OptionButton`s that are used for dropdowns in the inspector are set to `flat`, i.e. they render no background styles and the darker background is a part of the inspector dock itself. Otherwise, the theme is correctly applied in your example, it uses correct styles and colors.

**Comment by olestourko** [comment]
Ah I see. Thank you!
