### ISSUE TITLE
draw_line performance has worsened since 3.2.3

### ISSUE THREAD

**Issue by kaetjaatyy-dev** [godotengine/godot#54826]
### Godot version

3.4.stable

### System information

Windows 10, GLES3, GeForce GTX 980M

### Issue description

draw_line (and others such as draw_arc) performance has dropped significantly from 3.2.3 to 3.3 and is still at a low level in 3.4. A simple test of drawing 700 horizontal lines on screen gives about 275 FPS on my machine in 3.2.3-stable. In 3.3 (earliest version where the performance issue occurs is 3.2.4-beta1) and 3.4-stable I get 55-65 FPS on the same machine, running the same scene. This is without antialiasing. _draw is called only once (in scene _ready) and _update is not called at all. This strange behavior occurs only when drawing lines with width > 1 (tested with width=2). With width=1, 3.4. performance is extremely good.

Expected behavior: Versions after 3.2.3 would have similar performance for draw_line and other custom drawing as 3.2.3 instead of a 80% FPS loss. 

![lineperf-3 2 3-stable](https://user-images.githubusercontent.com/94034196/141055985-f2f4c8ef-6298-43ea-ba92-3b34be8cb883.png)
![lineperf-3 2 4-beta1](https://user-images.githubusercontent.com/94034196/141055986-ad7dd380-9871-4c72-8045-bd46224ff607.png)
![lineperf-3 3-rc7](https://user-images.githubusercontent.com/94034196/141055987-a9696d35-2bc1-415c-a075-e1cafe336737.png)
![lineperf-3 4-stable](https://user-images.githubusercontent.com/94034196/141055989-2e611a4f-4ed5-4314-9ce6-158b891d80f1.png)
3.

### Steps to reproduce

- Create a new scene
- Add a few hundred draw_line calls in _draw
- Run the code in Godot 3.2.3 and any 3.3 or 3.4 version
- Observe the FPS drop from the older Godot version to the newer one

### Minimal reproduction project

[gd34-perftest.zip](https://github.com/godotengine/godot/files/7510139/gd34-perftest.zip)

**Comment by clayjohn** [comment]
How does performance compare when you disable batching?

**Comment by lawnjelly** [comment]
On an integrated Intel HD Graphics 630 on Linux I get:
3.2.3 stable - 123fps
3.4 - without batching 145fps, with batching 870fps

This suggests there's something your GPU doesn't like. First I would try it with batching switched off for comparison in 3.4. Some GPUs don't deal very well with dynamic buffer usage, this is very ill defined in OpenGL, and we have attempted to use the most compatible method.

If you have a look in `rendering/2d/opengl`, there are some options for buffer usage which may help on your system, however I would encourage you to export with the defaults, as for an export you should try and have it running well on the majority of machines (yours may be an outlier).

**Comment by kaetjaatyy-dev** [comment]
> How does performance compare when you disable batching?

No meaningful change. I got about 55 FPS with a quick test with batching disabled (i.e. a few percent drop).

> This suggests there's something your GPU doesn't like. First I would try it with batching switched off for comparison in 3.4. Some GPUs don't deal very well with dynamic buffer usage, this is very ill defined in OpenGL, and we have attempted to use the most compatible method.

There is definitely something strange going on with how custom drawing is implemented between versions. When I set the line width to 1 (instead of 2 in the above benchmark) the 3.4 FPS skyrockets to about 2000, whereas 3.2.3 FPS stays constant. 

> If you have a look in rendering/2d/opengl, there are some options for buffer usage which may help on your system, however I would encourage you to export with the defaults, as for an export you should try and have it running well on the majority of machines (yours may be an outlier).

These do not seem to change the results. I flipped each of the four options separately and together, and did not see any changes in the FPS.

> You can also try updating your graphics drivers, sometimes this will be a driver issue.

Thanks, I will try that.

**Comment by lawnjelly** [comment]
Ah this changes things. If you get no increase with batching off, and it is related to line width, then it sounds like the different methods with different sized lines, rather than the dynamic buffers. I will take a look. I can't remember if we made any changes to this since 3.2.3...

**Comment by kaetjaatyy-dev** [comment]
Awesome! I should have mentioned the line width aspect in the main post but I just noticed it right now when doing further testing.

**Comment by lawnjelly** [comment]
Ah slight confusion on my part, I've realized the release I was using was with this PR #54377 (which hasn't been merged yet) which will have increased the performance a boatload.

With the regular 3.4 it draws them as default lines with or without batching. Still investigating! :grin:

**Comment by lawnjelly** [comment]
Should be fixed by #54377.
