### ISSUE TITLE
Default setter is not used if only getter function is defined.

### ISSUE THREAD

**Issue by nabfrew** [godotengine/godot#54829]
### Godot version

v4.0.dev.20211027.official [157cba393]

### System information

Windows 10

### Issue description

If only a getter function is set on a property, a default setter should apply on assignments. In this version assignments are ignored instead. See https://github.com/godotengine/godot-proposals/issues/3519

### Steps to reproduce

Run the following script. It ignores the assignment and prints `0` instead.
```
extends Node2D

var foo : int:
    get:
        return foo

func _ready():
    foo = 1
    print(foo)
```

### Minimal reproduction project

It's probably no quicker to download a zip and open than it is to copy-paste the code above into an existing project.

**Comment by Gustavobb** [comment]
I'd like to take a look at this.

**Comment by Calinou** [comment]
> I'd like to take a look at this.

Feel free to open a pull request for this :slightly_smiling_face:

**Comment by cdemirer** [comment]
It seems it assigns to the temporary int returned by the getter:
```
Disassembling _ready()
 0: line 8:     foo = 1
 2: call-ret stack(3) = self.@foo_getter()
 7: assign stack(3) = const(1)
 10: line 9:     print(foo)
...
```
