### ISSUE TITLE
Missing textures in Android (export after ~17/06)

### ISSUE THREAD

**Issue by alexolin** [godotengine/godot#5483]
I download unofficial godot engine builds  and export templates from fixnum.org/godot

I download builds from June 17, 2016 at 17:17  and June 23, 2016 at 10:44 and newest.

I export my project to Android from builds and templates  on 17 June

Screen 1

![p2](https://cloud.githubusercontent.com/assets/15943158/16445667/6748e300-3dec-11e6-93f1-a10487a18dbe.JPG)

I export my project to Android from builds and templates on 23 June

screen 2
![p1](https://cloud.githubusercontent.com/assets/15943158/16445672/7486adae-3dec-11e6-8a85-c83b8976a78c.JPG)

In my proect mesh has override shader material with 2 textures

![p3](https://cloud.githubusercontent.com/assets/15943158/16445770/e2af0524-3dec-11e6-947c-e0b6edaaa0fb.JPG)
![p4](https://cloud.githubusercontent.com/assets/15943158/16445775/e8f87898-3dec-11e6-9115-073268f07f96.JPG)

Tex 2  on Android loss with more new builds 23 and 28 June.

Please check export for android. In editor and builds for Windows Desktop (Windows 10) all textures is complete.

**Comment by RandomShaper** [comment]
Could you post all the output you get in the console window when exporting in both cases, to compare them?

**Comment by alexolin** [comment]
My be i found error.
Bug appear if use textures in TEX format, imported from old project without original png.

**Comment by reduz** [comment]
This is not actually a bug, Godot needs the original textures so it can re-import them as an android compatible compression for export in your project. The current .tex files in the filesystem probably use S3TC, which is incompatible with most Android devices

**Comment by reduz** [comment]
For Godot 3.0, I'm trying to see if it's possible to import textures to multiple formats at the same time, we'll see how it works..

**Comment by bojidar-bg** [comment]
I think this is now obsoleted by the new importer, since it doesn't even produce .tex files anymore.

**Comment by reduz** [comment]
indeed this is obsoleted by the new imported, closing
