### ISSUE TITLE
[Question] How to change Default Environment Preview in 4.0

### ISSUE THREAD

**Issue by Whimfoome** [godotengine/godot#54830]
### Godot version

3.4 and 4.0

### System information

Arch Linux

### Issue description

In Godot 3, I made the default environment to be dark, without any effects, to be easy to see what is going on with collisions, materials, etc.

In Godot 4, the Environment Preview is too bright to notice small details

Godot 3 with custom environment:
![image](https://user-images.githubusercontent.com/42871796/141091336-a65edaa0-9876-474c-a949-0e58c2bbafd7.png)

In Godot 4 you can edit the preview environment, but it's not permanent:
![image](https://user-images.githubusercontent.com/42871796/141091556-f4c108c1-3876-408a-a9c9-08afa2ce07ce.png)

I tried to change the default environment in the project settings, but that didn't do anything

### Steps to reproduce

Create default environment to your liking to edit details in scenes.
Apply it  in the Project Settings
Not working, it still uses the Environment Preview from the menu, which can be changed, but changes aren't permanent and reset every time

**Comment by Whimfoome** [comment]
Also orthographic view, seems to not render properly
![image](https://user-images.githubusercontent.com/42871796/141092401-e7027616-22ab-4c7e-85cd-926385855616.png)

**Comment by Deozaan** [comment]
Orthographic view seems to be triggering the automatic LOD if the mesh. Check those settings to adjust how it displays.

**Comment by Calinou** [comment]
Please open a separate issue for the orthographic LOD issue. In the meantime, you can disable LOD generation for your meshes in the Import dock.

**Comment by clayjohn** [comment]
> it still uses the Environment Preview from the menu, which can be changed, but changes aren't permanent and reset every time

Looks like this is the core of the problem. The environment preview settings should be saved somewhere so that they are maintained between scenes and after closing and reopening the editor.

**Comment by Whimfoome** [comment]
Okay, the environment preview setting is saved somewhere and is consistent between multiple openings of the project.

Default Environment now works again if set when preview environment is disabled.
