### ISSUE TITLE
Godot trying to load Rockstar Social Club data

### ISSUE THREAD

**Issue by Buri** [godotengine/godot#54831]
### Godot version

4.0.dev.custom_build.e317e34c1

### System information

Windows 10, Vulkan

### Issue description

Godot Engine v4.0.dev.custom_build.e317e34c1 - https://godotengine.org
USER ERROR: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        loader_get_json: Failed to open JSON file C:\Program Files\Rockstar Games\Social Club\SocialClubVulkanLayer.json
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 1678850513952
   at: VulkanContext::_debug_messenger_callback (drivers\vulkan\vulkan_context.cpp:157) - GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        loader_get_json: Failed to open JSON file C:\Program Files\Rockstar Games\Social Club\SocialClubVulkanLayer.json
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 1678850513952

### Steps to reproduce

Freshly cloned repo
Built with  scons -j 16 target=release_debug
Run built executable

Rockstar Social club is not even installed, but it was installed in the past

**Comment by Buri** [comment]
Seems like its a problem with RSC not cleaning up after itself.

**Comment by floppyhammer** [comment]
I experienced similar error messages after uninstalling Unreal.
