### ISSUE TITLE
`Vector2.angle()` and `Vector2.angle_to()` have inconsistent rotation directions

### ISSUE THREAD

**Issue by Drumstickz64** [godotengine/godot#54841]
### Godot version

3.4.stable

### System information

OS: Windows 10

### Issue description

`Vector2.angle()` measures rotation clockwise, while `Vector2.angle_to()` measures rotation counter_clockwise. 

### Steps to reproduce

```gdscript
# `angle()` uses the Vector2.RIGHT
printt(Vector2.DOWN.angle(), Vector2.DOWN.angle_to(Vector2.RIGHT)) # 1.570796	-1.570796
```

### Minimal reproduction project

[GodotAngleIssue.zip](https://github.com/godotengine/godot/files/7514671/GodotAngleIssue.zip)

**Comment by akien-mga** [comment]
Those results seem correct to me. `angle()` gives you the angle **from** the positive X axis (`Vector2.RIGHT`) **to** the vector you call it on. So `Vector2.DOWN.angle()` is equivalent to `Vector2.RIGHT.angle_to(Vector2.DOWN)`, which is the opposite of what you calculated, hence the flipped sign.

**Comment by Drumstickz64** [comment]
> Those results seem correct to me. `angle()` gives you the angle **from** the positive X axis (`Vector2.RIGHT`) **to** the vector you call it on. So `Vector2.DOWN.angle()` is equivalent to `Vector2.RIGHT.angle_to(Vector2.DOWN)`, which is the opposite of what you calculated, hence the flipped sign.
> 
> In 2D, the positive Y axis points downwards, so the positive angle on the trigonometric circle is from `Vector2.RIGHT` (`(1, 0)`) to `Vector2.DOWN` (`(0, 1)`). `angle()` gives you that oriented angle on the trigonometric circle, positive in Y+ and negative in Y-.
Ahh I see. I seem to have gotten confused, it seems so obvious now 😂
