### ISSUE TITLE
AnimationNodeStateMachinePlayback travel function works without transitions connecting the various states(nodes)

### ISSUE THREAD

**Issue by maxnim1986** [godotengine/godot#54843]
### Godot version

3.3.2.stable.official

### System information

Windows 7

### Issue description

AnimationNodeStateMachinePlayback travel function works without transitions connecting the various states(nodes). I have statemachine as a root node. Each state is a blend tree containing blendspace2d inside. The nodes are not connected with any transitions but the travel function still works.

### Steps to reproduce

Create multiple animations.
Add an animationtree node.
Add statemachine as root node.
Add various states without any transitions between them.
Use travel method in code to transition between the various states.

### Minimal reproduction project

[AnimationStateMachineTravelBugreport.zip](https://github.com/godotengine/godot/files/7514795/AnimationStateMachineTravelBugreport.zip)

**Comment by maxnim1986** [comment]
@Calinou Is this a known bug? Is it likely to be fixed?

**Comment by Calinou** [comment]
> @Calinou Is this a known bug?

I don't know – from a quick search, I can't find any similar issues reported here.

> Is it likely to be fixed? 

We need to assess whether it's actually a bug first. cc @TokageItLab

**Comment by maxnim1986** [comment]
@Calinou This surely must be a bug. According to the docs the travel function works using A* for finding suitable/shortest path between the states. How can the algorithm work if there's nothing connecting the nodes?

**Comment by TokageItLab** [comment]
I've heard of some problems with transitions between connected nodes in godotengine/godot-proposals#2200 or godotengine/godot-proposals#2523, but I've never heard of a problem with transitions to unconnected nodes. If I had to guess, I could say that #54456 is a bit related, but I think this is probably the first time this has been reported as a problem.

**Comment by maxnim1986** [comment]
@reduz Can you shed some light on this? What could possibly be happening here?

**Comment by maxnim1986** [comment]
Okay did some further testing. This happens in Godot versions 3.1/3.2/3.4 official stable.

**Comment by maxnim1986** [comment]
Okay took a look at the following file [https://github.com/godotengine/godot/blob/master/scene/animation/animation_node_state_machine.cpp](url)
I think the relevant part of the code is

**Comment by maxnim1986** [comment]
Ok so this is a feature. The travel indeed teleports to a new node in the absence of any transitions. Made some changes to the docs which has been approved. :)

**Comment by Zireael07** [comment]
Can this feature be documented better? It's highly unexpected to the user....

**Comment by Calinou** [comment]
> Can this feature be documented better? It's highly unexpected to the user....

This was documented in https://github.com/godotengine/godot-docs/pull/5391.

**Comment by TokageItLab** [comment]
It has been documented.
