### ISSUE TITLE
Vulkan: Subsurface scattering renders incorrectly

### ISSUE THREAD

**Issue by NHodgesVFX** [godotengine/godot#54858]
### Godot version

v4.0.dev.custom_build [596865366]

### System information

Windows 10 64Bit, RTX2080S, Driver: 496.49, Vulkan Clustered 

### Issue description

When adding a OmniLight3D into the scene that contains meshes using materials with SSS transmittance the object turns black. Additionally, When adding other light types it does not appear that transmittance works, you can not see any light through the mesh.

**Important Note:** restarting the editor after the mesh goes black makes the mesh appear normal but light does not shine through the object as you would expect with transmittance enabled.

![Godot4SSSError](https://user-images.githubusercontent.com/11403345/141224690-c131b820-9621-4b05-879b-7a81eef8ef37.PNG)

When enabling SSS with or without transmittance the mesh has fireflys

![Godot4SSSError_02](https://user-images.githubusercontent.com/11403345/141225569-514e403e-04d4-4c22-a6ba-007f6f53227f.PNG)

### Steps to reproduce

1. Add a mesh instance and assign a sphere mesh to it
2. Add a material to the created mesh
3. enable SSS and transmittance
4. add a OmniLight3D to the scene

Result: Object becomes black
Expected Result: Object is lit with a SSS effect

5. Save the scene and Restart the editor

Result: SSS Transmittance looks like its working but light does not actually show through the object, additionally their are fireflies on the mesh. This result also happens with other light types but the mesh does not turn black.

### Minimal reproduction project

[GodotSSSError.zip](https://github.com/godotengine/godot/files/7517137/GodotSSSError.zip)

**Comment by clayjohn** [comment]
SSS has been fixed since issue was created! I checked and it works fine in RC3
