### ISSUE TITLE
InputMap breaks when action is named "[" or ";"

### ISSUE THREAD

**Issue by Ludio235** [godotengine/godot#54853]
### Godot version

v3.3.4.stable.custom_build

### System information

Solus 4.3 Fortitude 64-bit, AMD® Ryzen 5 3600 6-core processor × 12, NVIDIA GeForce GTX 1650 SUPER/PCIe/SSE2

### Issue description

When you go to "Project settings >> Input Map" and map an action with name ";" or "[" the actions after those won't map correctly. For ";" a single next action won't map, for "[" all following actions won't map:

![InputMap](https://user-images.githubusercontent.com/94078268/141191235-405b9ec3-6886-457b-b051-cd8d7a5b479c.png)

![Errors](https://user-images.githubusercontent.com/94078268/141191268-c811486d-767a-4793-b6c7-a3f6ab331bc9.png)
 
I expect the editor to do the same as with other invalid characters:

![Expected behavior](https://user-images.githubusercontent.com/94078268/141191841-6405e7e8-7bd5-4450-b771-bb755d829ff5.png)

### Steps to reproduce

1. Go to "Project Settings... >> Input Map" and map an action with name "[" or ";".
2. Have another action in list below that.

Neither of those should work.

### Minimal reproduction project

[Bugreport.zip](https://github.com/godotengine/godot/files/7515895/Bugreport.zip)
 
The keys "Q", "W", "E", "R" and "T" as well as "[" and ";" are mapped to make a respective sprite disappear. Only "Q" and "E" should work properly as a control group.

**Comment by Calinou** [comment]
We should change the list of disallowed characters to contain `[`, `]` and `;`.

**Comment by akien-mga** [comment]
> To fix this, we should change the list of disallowed characters in InputMap to contain `[`, `]` and `;`. This restriction may be worth applying to project setting names as well.

I don't think those characters need to be restricted, the problem is simply that if they are present, the action name needs to be quoted, otherwise they're parsed as special characters in the `ConfigFile` / `project.godot` file.

This is similar to #34472.

**Comment by akien-mga** [comment]
This should actually already go through `property_name_encode()` added in #34472, but it doesn't consider that chars such as `[` and `;` need quoting. Maybe it would be safer to make `property_name_encode()` handle everything which is not `is_valid_identifier()`, WDYT @timothyqiu?
