### ISSUE TITLE
Windows network paths do not work properly with Godot's file dialog

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot#54863]
### Godot version

3.4-stable

### System information

Windows 11 for ARM VM on an M1 Mac (I think it should be reproducible with any Windows device with a network share)

### Issue description

Windows network paths do not work properly with Godot's file dialog.

What works:

* Browsing files
* Displaying the path in the path box

What doesn't work:

* Creating files or folders
* Hiding the drive letter when the path is a network path

Here is what it looks like:

![GodotWindowsNetworkShare](https://user-images.githubusercontent.com/1646875/141240943-8726200c-936d-4ec0-808c-611e5119d7e2.png)

### Steps to reproduce

Open the file dialog in the project manager on a Windows machine with a network share and observe that Godot doesn't hide the drive letter or allow creating files or folders.

### Minimal reproduction project

N/A - can be reproduced in the project manager.

**Comment by mhilbrunner** [comment]
>Windows network shares on Windows 11 for ARM VM on an M1 Mac

I just want to congratulate you on the beauty of this setup, this kept getting more fun the more I read 😛

**Comment by and-rad** [comment]
I think this needs to be reopened. The problem still occurs in 3.4 because as far as I can see the changes in #57116 were not backported to Godot 3.x.

**Comment by aaronfranke** [comment]
@and-rad Issues are closed when they are solved in the master branch. But we can ask @bruvzg if we can backport it.

**Comment by and-rad** [comment]
That would be great! I can also try to prepare a PR for that.

**Comment by bruvzg** [comment]
https://github.com/godotengine/godot/pull/61985 - backport for 3.x.
