### ISSUE TITLE
Can't switch to other views (2D, 3D, Script and AssetLib buttons not working)

### ISSUE THREAD

**Issue by jedStevens** [godotengine/godot#5486]
**Operating system or device - Godot version:**
Arch Linux
Pulled the newest git version this morning.

**Issue description** (what happened, and what was expected):
After compiling the newest updates it seems I can't switch to other views, like 2D and Script. When I start up godot it opens a project from the project manager, but then shows me the 3D view by default even though I am working in 2D. When I go to press the 2D button, it remains pressed until I click it again, as is the case with the other buttons. I have tried with all my projects and I still get this error.

**Comment by jedStevens** [comment]
I have also recorded a video to show this in action

I would also like to note that even when I add a Node2D the view doesn't change which is a default feature IIRC. 

https://www.youtube.com/watch?v=F5QPIhYK5Dc&feature=youtu.be

**Comment by bojidar-bg** [comment]
Can easily reproduce on a similar setup (using gcc 6).

**Comment by jedStevens** [comment]
A fix is found!

Going to the error he referenced this one in,  if you change line 3434 of tools/editor/editor_node.cpp

From `if (get_edited_scene()!=p_for_scene)`
To `if (get_edited_scene()!=p_for_scene && p_for_scene!=NULL)`


Thanks to @volzhs for the fix!

**Comment by bojidar-bg** [comment]
Closed by 119cd5d3ff9fbbafc59db7481c0eee29f43c0c64
