### ISSUE TITLE
Null pointer exception in physics server deleting floor bodies with new move and slide logic

### ISSUE THREAD

**Issue by omegachysis** [godotengine/godot#54878]
### Godot version

3.4.stable

### System information

Pop!_OS 21.04, NVIDIA Corporation GK104 [GeForce GTX 770], GLES3

### Issue description

Using the new `move_and_slide_with_snap` logic results in null pointer exceptions when a floor body is freed while a kinematic body is colliding with it.

<pre><font color="#CC0000"><b>ERROR:</b></font><font color="#F15D22"> Condition &quot;!body&quot; is true. Returned: nullptr</font>
<font color="#88807C">   at: body_get_direct_state (modules/bullet/bullet_physics_server.cpp:855)</font>
<font color="#CC0000"><b>ERROR:</b></font><font color="#F15D22"> Condition &quot;!id_map.has(p_rid.get_data())&quot; is true. Returned: nullptr</font>
<font color="#88807C">   at: get (./core/rid.h:140)</font></pre>

I believe this is because of the check here:
https://github.com/godotengine/godot/blob/489b49c6b89f68b9f3cc3f8a9579c6ed1e2fdf82/scene/3d/physics_body.cpp#L1070-L1072

If the object `on_floor_body` points to is freed, the RID doesn't exist (but remains 'valid' in the kinematic body).

### Steps to reproduce

1. Create static body and a kinematic body. 
2. Make kinematic body collide with static body and sit on it as a floor. 
3. Call `move_and_slide` every physics tick and free the static body.

### Minimal reproduction project

[platform-deletion.zip](https://github.com/godotengine/godot/files/7520373/platform-deletion.zip)

**Comment by arkology** [comment]
This is definitely a duplicate of already existing issue and has already been fixed.

**Comment by omegachysis** [comment]
#54666 I seee it now, I must have filtered by open issues by accident. Closing.
