### ISSUE TITLE
Calling methods on Enum types in gdscript results in debugger errors

### ISSUE THREAD

**Issue by tomkun** [godotengine/godot#54877]
### Godot version

v4.0.dev.20211108.official.596865366

### System information

Win 10 x64

### Issue description

When calling underlying dictionary methods like **.keys()** or **.size()** on enum types, the debugger reports error on scene launch:
```
get_function_signature: Native class res://NodeWithEnum.gd.MyEnum used in script doesn't exist or isn't exposed.
  <C++ Error>    Method/function failed. Returning: false
  <C++ Source>   modules/gdscript/gdscript_analyzer.cpp:3601 @ get_function_signature()
```
![image](https://user-images.githubusercontent.com/4152969/141295896-fe8cb7ba-9209-44c6-aa24-798b461da4c8.png)
![image](https://user-images.githubusercontent.com/4152969/141295930-2c8dc237-6ca5-48e4-9507-8474b91e7a9d.png)

### Steps to reproduce

1. Create an enum type
2. Call a method like .size() or .keys() on the type
3. Observe debugger reporting numerous errors

### Minimal reproduction project

[4.0_EnumMethodErrors.zip](https://github.com/godotengine/godot/files/7520312/4.0_EnumMethodErrors.zip)

**Comment by Calinou** [comment]
Enums aren't dictionaries under the hood anymore in GDScript 2.0, so this is likely expected.

**Comment by KoBeWi** [comment]
Actually they are:
![image](https://user-images.githubusercontent.com/2223172/141328709-d44e9100-2c6a-446d-9e8b-b3628eb93224.png)
IMO it's partially fine, because that makes them "immutable", but having some methods available would be useful (see https://github.com/godotengine/godot-proposals/issues/2959)

**Comment by tomkun** [comment]
@KoBeWi according to that screenshot, all the methods can be exposed just as before since it's still a dictionary behind the scenes - so it's a public API bug, not missing functionality, it seems - which also explains why it works, just throws accompanying errors.
