### ISSUE TITLE
Texture changes after apply to Spatial Material

### ISSUE THREAD

**Issue by Howtomakeusername** [godotengine/godot#54884]
### Godot version

3.3.4

### System information

Windows 10

### Issue description

I was testing some 3D and for some reason the texture after I apply it as the texture in the spatial material of the mesh instance and it changes the texture along with it
Before:
![image](https://user-images.githubusercontent.com/85679765/141311535-7f05f038-69ec-4d66-9acc-01eeb7777bbb.png)
After:
![image](https://user-images.githubusercontent.com/85679765/141311651-6f81f6de-ec7e-44e9-9d3d-902bf3beddde.png)

### Steps to reproduce

1. Create a Mesh Instance
2. Apply Spatial Material in the Material
3. Apply texture in Albeldo
4. See the texture again in 2D

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/18941. As a workaround, make a copy of the texture file on the filesystem so you can use one that's converted to sRGB in 3D, and one that's kept as-is in 2D.

**Comment by Howtomakeusername** [comment]
Ok thanks
