### ISSUE TITLE
Vulkan geometry instance assigned the wrong shader instance uniform when rendering

### ISSUE THREAD

**Issue by briansemrau** [godotengine/godot#54897]
### Godot version

4.0.dev (86460db231)

### System information

W10, Vulkan Clustered, RTX2060

### Issue description

When assigning a number of instance uniform values to a set of mesh instances, some of the meshes are using the wrong instance uniform.

This grid of boxes _should_ be forming a smooth red/green gradient:
(10x10 grid)
![image](https://user-images.githubusercontent.com/6376721/141406995-6592e088-75a0-4268-8ec6-aa1da1a3f174.png)

<details><summary>It seems to be misaligned in counts of 64</summary>
(16x16 grid)

![image](https://user-images.githubusercontent.com/6376721/141407625-0be8245b-d268-4127-b7e1-ba51c4282937.png)

</details>

### Steps to reproduce

Create more than 64 geometry instances and assign a unique instance uniform value to each.
Notice how some use the wrong values when rendering.

### Minimal reproduction project

[InstanceUniformBrokenReprod.zip](https://github.com/godotengine/godot/files/7524791/InstanceUniformBrokenReprod.zip)

**Comment by Calinou** [comment]
I can confirm this on commit c89061e98 (Linux, GeForce GTX 1080).

This also occurs after switching to the Vulkan Mobile backend in the project setting, so this is not due to clustering:

![image](https://user-images.githubusercontent.com/180032/141454998-8dcc8969-321d-4680-8b1e-d1b275bb33b1.png)

**Comment by Zylann** [comment]
Can confirm this in 28174d531b7128f0281fc2b88da2f4962fd3513e
Got there the long way... as I did not realize that this was just about the number of instances having to exceed 64 (seems like).

In my repro I also found that timing had an effect.
