### ISSUE TITLE
Collision between small Area2D's fails when using BVH

### ISSUE THREAD

**Issue by Drakmyth** [godotengine/godot#54898]
### Godot version

3.4.stable.official

### System information

Windows 10, GeForce 980Ti, Driver 496.49, GLES3

### Issue description

When a small Area2D (12x12 pixels) is positioned entirely within a slightly larger Area2D (16x16 pixels), the collision may not be detected. Making the smaller Area2D slightly bigger (1-2 pixels) on either axis allows the detection, but only in the axis that was extended.

This seems to be related to the `physics/2d/use_bvh` option. Disabling this option allows the collisions to be detected as expected.

### Steps to reproduce

See README in reproduction project repo for reproduction explanation and sample controls.

### Minimal reproduction project

https://github.com/Drakmyth/GodotCollisionTest

**Comment by lawnjelly** [comment]
Possibly related to #54855.

**Comment by timovervliet82** [comment]
Can confirm this issue in 3.4.  My project uses collision layers. I randomly spawn area2d's of 16x16 pixels.  These Area2Ds use a collision layer to detect if they spawn on the tile map collision or not. This no longer works unless I disable BVH

**Comment by pouleyKetchoupp** [comment]
@timovervliet82 Could you please test with #54925 to check that it solves your issue as well? If it doesn't I'm interested in a minimal project to investigate.

**Comment by timovervliet82** [comment]
> @timovervliet82 Could you please test with #54925 to check that it solves your issue as well? If it doesn't I'm interested in a minimal project to investigate.

I ran into some issues building your branch , was unable to test but I've created a [project](https://github.com/timovervliet82/godot_2dphysics_repro-project) for you to easily repro the issue (atleast in 3.4 stable).

**Comment by timovervliet82** [comment]
@pouleyKetchoupp 
I ran into some issues building your branch , was unable to test but I've created a [project](https://github.com/timovervliet82/godot_2dphysics_repro-project) for you to easily repro the issue (atleast in 3.4 stable).

**Comment by pouleyKetchoupp** [comment]
@timovervliet82 Thank you! I can confirm your issue is also fixed with #54925.

**Comment by timovervliet82** [comment]
@pouleyKetchoupp Great! Thank you!
