### ISSUE TITLE
Array.sort_custom raises error on Godot 4.0 with documentation example

### ISSUE THREAD

**Issue by gustavi** [godotengine/godot#54906]
### Godot version

v4.0.dev.20211108.official.596865366

### System information

Windows 10 64bit - Vulkan API 1.2.141 - GeForce GTX 1660 SUPER

### Issue description

The [documentation example](https://docs.godotengine.org/en/latest/classes/class_array.html#class-array-method-sort-custom) of `Array.sort_custom` is not working and raise the following error: `Invalid get index 'sort_ascending' (on base: 'GDScript').`

It **may** be introduced in fb83d905daed6c2a7c4f95712d47815c7ccd8f2e but also a documentation mistake.

![image](https://user-images.githubusercontent.com/2736557/141446058-77ec1414-0896-40d8-8d9e-e75fc663b710.png)

Versions tested (Windows 10 only):

- Godot 4.0-20210727 (new syntax): 🔴 error
- Godot 4.0-20211108 (new syntax): 🔴 error
- Godot 3.4 (old syntax): 🟢 works
- Godot 3.3 (old syntax): 🟢 works

### Steps to reproduce

Code to reproduce (based on official doc):

```gdscript
extends Node2D


class MyCustomSorter:
    static func sort_ascending(a, b):
        if a[0] < b[0]:
            return true
        return false


func _ready():
    var my_items = [[5, "Potato"], [9, "Rice"], [4, "Tomato"]]
    # my_items.sort_custom(MyCustomSorter, "sort_ascending")  # 3.x
    my_items.sort_custom(MyCustomSorter.sort_ascending)  # 4.x
    print(my_items)

```

### Minimal reproduction project

[sort_custom_4.0.zip](https://github.com/godotengine/godot/files/7526550/sort_custom_4.0.zip)

**Comment by akien-mga** [comment]
The inner class is probably not needed at all anymore, this might work just fine:
```
func sort_ascending(a, b):
    if a[0] < b[0]:
        return true
    return false

func _ready():
    var my_items = [[5, "Potato"], [9, "Rice"], [4, "Tomato"]]
    my_items.sort_custom(sort_ascending)
    print(my_items)
```
(didn't test)

If so the bug might be related to using static functions of inner classes specifically.

**Comment by gustavi** [comment]
Your sample works fine on last 4.0 build.

I don't know if static functions of inner classes are still something needed (I let you judge that) but the documentation should be updated with your sample.
