### ISSUE TITLE
importing .gltf not importing meshes when more than 4 weight groups are assigned to vertex

### ISSUE THREAD

**Issue by Rbetik** [godotengine/godot#54916]
### Godot version

3.4

### System information

os 

### Issue description

When importing mesh with weight paint, when more than 4 bones are assigned to vertex, imported mesh is empty with 
"a.has("JOINTS_0") && a.has("JOINTS_1") warning thrown.

In previous versions (as far as i rembember 3.0, all the way to 3.3.4, this worked by just trimming extra (above 4) bone weights.

It is probably better to force hard limit to 4 to ensure proper behavior, but some more descriptive information about what is happening would be helpful.

### Steps to reproduce

1. import .gltf with weight painted model such, that more than 4 bones are assigned to one vertex

### Minimal reproduction project

[https://github.com/Rbetik/weight_paint_import_bug](url)

**Comment by fire** [comment]
The behaviour changed because the backport of the Godot 4 code supports 8 bone weights. 

I think I have a pr for normalization, but let me check.

**Comment by fire** [comment]
If you wish, you can try using https://github.com/godotengine/godot/pull/48360 to make a new pr to handle importing meshes with more than 4 weight groups.

**Comment by tinmanjuggernaut** [comment]
This should be fixed by #61912, which is in 3.5-rc4. Rc3 and prior does import the mesh, however it strips out the material slot, leaving the mesh invisible. Rc4 imports models exported from blender w/ the >4 bone weights option enabled. We can confirm Rc4 works with our model as discussed in #62403.

**Comment by fire** [comment]
Is there anything left as a release blocker?

**Comment by akien-mga** [comment]
Fixed by #61912.
