### ISSUE TITLE
Particles2D particles are not sorted by YSort, limitation or bug?

### ISSUE THREAD

**Issue by JoanPotatoes2021** [godotengine/godot#54929]
### Godot version

v3.4.stable.official [206ba70f4]

### System information

Windows 10, GLES 3

### Issue description

Particles spawned using Particles2D do not work with YSort.
![ParticleNotYsorted](https://user-images.githubusercontent.com/88800565/141533922-5636be61-c38d-4a81-af5d-d81ee1d4defd.gif)

FOG is a mock-up using sprites, tis the expected result. Here are some settings for the particle2D node:
![nopartysort](https://user-images.githubusercontent.com/88800565/141534037-e22a4c88-db18-4559-bd76-1fbf6d117ed8.jpg)

I don't know if this is a limitation for perfomance gain, and not a bug.

### Steps to reproduce

Move a particle2D with particles spawning behind and in front of some sprites using ysort as a parent.

You should see that the particles are all grouped at the center of the particle2D, and are not calculated separated.

### Minimal reproduction project

[Particle2D_NotYsortable.zip](https://github.com/godotengine/godot/files/7530639/Particle2D_NotYsortable.zip)

**Comment by Calinou** [comment]
Does it work when using CPUParticles2D? You can try this out quickly by using the **Particles > Convert to CPUParticles** at the top of the 2D editor after selecting a Particles2D node.

**Comment by JoanPotatoes2021** [comment]
Added the mrp, I created both GPU and CPU particles from scratch,

**Comment by Calinou** [comment]
cc @groud

**Comment by lawnjelly** [comment]
This won't work for exactly the reasons you've shown in your mockup that do work. The mockup that does work has the particles as separate sprites, so they can be Y sorted. With particle systems all the particles are part of the same item, so can't be sorted.

You could in theory modify the particle system to emit and keep track of a bunch of sprites so this would work. It won't be very efficient once you get past e.g. 8 or so particles, and wouldn't have been an option before batching, because batching will in many cases reduce the drawcalls.

But anyway yes this is in effect more a feature request.

**Comment by JoanPotatoes2021** [comment]
I can easily re-create this effect with a script, a fog simulation could be simply some children sprites moving with animated alpha values and using different sprites of a spritesheet, but when you say it wouldn't be very efficient over 8 particles or so, that is in context of the sprites being in the particle system how I wanted or about all the sprites moving at the same time? I would assume that drawing some sprites moving isn't so costly, mainly because of batching.

My presumption that this was a bug, was because of the local coords tag on the particle process material tab, because on the description it says `[...]they use global coordinates.` if you add that to ysort description which is to sort any canvasitem node using the y position, I thought it should work as my mockups examples.

![LocalCoordsPart2D](https://user-images.githubusercontent.com/88800565/141646826-7dbe121c-fbcb-48ee-9b7c-abfe5ed9c6fd.jpg)

That being said simply increasing the `zindex` of the particle node also solves the issue I proposed, as such I don't think this is a reasonable request for a new feature which could potentially lower the perfomance of the particle systems, so I will be closing soon as it is not an issue.

![ParticleNotYsorted02](https://user-images.githubusercontent.com/88800565/141646981-a47cff05-7f41-4b12-8a10-76c625aa21a1.gif)

**Comment by Calinou** [comment]
Closing per the above comment.
