### ISSUE TITLE
Rename the .zip extension used for project data export in "Export ZIP" mode

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#5492]
The `.zip` extension used by the project data export can be confusing for end-users, since they may think they have to extract the file in order to play the project.

What about going back to the `.pcz` extension?

**Comment by bojidar-bg** [comment]
Well, we could have `.noextract.zip` then :P

**Comment by punto-** [comment]
I agree, we used to have this problem with the export templates where users
kept unzipping them. We should at least support both pcz and zip

**Comment by reduz** [comment]
pcz/zip is no longer supported. It is still available for exporting so you can check what it did, butthe new export system has patching support, which includes removing files, so there is not much desire to get this to work with a zip. Also zip is considerably slower to access, and in general not a good idea.
