### ISSUE TITLE
Advanced String format with named/numbered parameters

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#5493]
Someone asked for this feature on IRC is it something we could add to "String" or is too special?

```
func _ready():
    print(format("hello %0, what can %1 do for %0", {"0":"Unknown", "1":"NPC"}, "%_"))

func format(_str, dict, placeholder="[_]"):
    for key in dict:
        _str = _str.replacen( placeholder.replace("_", str(key) ), dict[key]) 
    return _str
```

**Comment by akien-mga** [comment]
It exists already:
```
print("Hello %s, how you %s" % ["world", "doing"])
```

**Comment by djrm** [comment]
@akien-mga its not the same, because you cant reuse parameters

**Comment by akien-mga** [comment]
I guess we could try to support this syntax:
```
print("Hello %0, what can %1 do for %0", [ "Unknown", "NPC" ])
```
i.e. the `%idx` would refer to the index of the array. Not sure using dictionaries would be a good solution for that, sounds a bit too far-fetched to me.

**Comment by djrm** [comment]
yeah the dictionary for the original case is useless, but is useful if you want a python like format function
`"{element} {other_element}".format(element=1, other_element=2})`
of course since gdscript does not support named parameters nor varargs (not sure about this one)
the format function would be something like:

`"{0} {1}".format([0, 1])`
and 
`"{val} {other_val}".format({'val': 1, 'other_val': 2})`

**Comment by vnen** [comment]
I remember discussing this on IRC with @Calinou and @reduz. I believe the Python format with arrays and dictionaries (as @djrm pointed) was seen as the best syntax.

**Comment by Dillybob92** [comment]
Having a similar issue here with massively dynamic tooltips

I propose this type of syntax:
 
```
var format_string = "%customname1 was reluctant to learn %customname2, but now he enjoys it."
var actual_string = format_string % { 
customname1 = "Estragon",
 customname2 = "GDScript"
}
```

Real life example:
```
	GF.GTipRTL.set_bbcode("""[b]Fireball[/b][center][color=#bbbbbb]%s[/color][/center]
[b]Cooldown[/b]: [color=#e6e7d7]%ss[/color]
[b]Damage[/b]: [color=#e10707]%s[/color]
	""" % [C_SKILL.skill_description,
		  C_SKILL.skill_cooldown,
			""+str(C_SKILL.skill_damage[0])+" - "+str(C_SKILL.skill_damage[1])+""])
```

If I were to add another placeholder randomly I would need to **re-order my array** to match the order of the placeholders (`%s's`). Would be a PITA, but, I mean it's definitely fine now but maybe in the future `GDScript` can offer a dictionary type placeholder conversion @reduz ? :)

**Comment by AlexHolly** [comment]
@Dillybob92,  please open a new issue if your feature is still not supported.

**Comment by Gfurst** [comment]
Has there been any development in this type advanced formats strings?

The user above seems to have been deleted, but that is a really neat idea, which would otherwise need a custom parser to replace names.

**Comment by vnen** [comment]
@Gfurst this function is already implemented since #7010 was merged.

**Comment by Gfurst** [comment]
thanks, care to provide some example use case, I saw a lot of discussion in between, but couldn't find any documentation over its final form. Seems kinda weird, and I'm sure about its limitations too.

**Comment by vnen** [comment]
@Gfurst I guess this was never reall documented. But for reference, it should work like this:

```Gdscript
"{value1} and {value2}".format({"value1": "something", "value2": "something else"})
# Will result in "something and something else"

# Can be done with custom placeholder markers:
"[value1] and [value2]".format({"value1": "something", "value2": "something else"}, "[_]")

# And with arrays
"{0} and {1}".format(["something", "something else"])
```

You can open an issue about on https://github.com/godotengine/godot-docs about this. If @AlexHolly can take some time to document it would be great too.

**Comment by Gfurst** [comment]
interesting, thanks @vnen 
let me ask you though, does the string need to have the same number of keys its expecting in format argument? because from the looks of the snippet could it could end up in a endless loop if the key did not match.

what I mean is having a defined dict for the keys for example, and being able to format the string regardless if that string has many, or none of the keys present.

also @akien-mga, why did you re-open, wasn't it implemented way back on version 2?

**Comment by Mochnant** [comment]
I'd love to see this format() functionality enhanced to allow non-named keys.

```"{} {} {}".format("first", "second", "third")```

This would also match what Python allows.

**Comment by vnen** [comment]
> I'd love to see this format() functionality enhanced to allow non-named keys.
>
> `"{} {} {}".format("first", "second", "third")`

In this case, why don't you use the regular formatting operator? `"%s %s %s" % ["first", "second", "third"]`

**Comment by Mochnant** [comment]
Thanks for the reply.  I could, but that (to me, at least) is the old Python 2 way to do it, and using format() is the Python 3 way.  I do a lot of Python coding, hence my interest in Godot, and it's a minor difference between Python and GDScript that doesn't seem necessary.

I could currently do:
```"{0} {1} {2}".format(["first", "second", "third"])```

While I agree named keys is nice, and useful at times, the above just seems needlessly wordy when 
```"{} {} {}".format("first", "second", "third")``` would suffice and is Pythonic to boot.

Just my opinion, of course, and it is minor.  But seems an easy enhancement that would not break any compatibility.

**Comment by Calinou** [comment]
> While I agree named keys is nice, and useful at times, the above just seems needlessly wordy when
"{} {} {}".format("first", "second", "third") would suffice and is Pythonic to boot

As far as I know, this way of formatting is not friendly to internationalization since the other of parameters cannot be changed.

**Comment by Mochnant** [comment]
This behavior is in the Python language, and I don't see how it would have any effect on internationalization at all.  The option would remain to use named or ordered arguments.

This is essentially an implicit positional argument and array.

https://docs.python.org/3.6/library/string.html#formatstrings

```
"First, thou shalt count to {0}"  # References first positional argument
"Bring me a {}"                   # Implicitly references the first positional argument
"From {} to {}"                   # Same as "From {0} to {1}"
```

**Comment by AlexHolly** [comment]
@Mochnant Is this what you want? It will work but without mixing the array. I think simply running it twice with different placeholder will work (a bit slower but better than nothing).

` "Hello {},\nI am {} your first teacher.\n{} can get the title {}.".format(["RobotGuy","Logis","RobotGuy","rookie"], "{}")`

OUTPUT:
```
Hello RobotGuy,
I am Logis your first teacher.
RobotGuy can get the title rookie.
```


```
func _ready():
	test01()

var t15 = "Hello {},\nI am {} your first teacher.\n{} can get the title {}."
var t15_rs = "Hello RobotGuy,\nI am Logis your first teacher.\nRobotGuy can get the title rookie."


func test01():
	#Test15 with array no index, mixing will not work(wrong placeholder).
	print(t15.format(["RobotGuy","Logis","RobotGuy","rookie"], "{}"))
	assert(t15.format(["RobotGuy","Logis","RobotGuy","rookie"], "{}") == t15_rs)
```

**Comment by Mochnant** [comment]
@AlexHolly I like the progress, thank you!  

I think the additional parameter might be a little confusing, though.  It would seem more straightforward to parse the format string behind the scenes and implicitly number them when a bare "{}" is found, rather than require a new parameter.  If that's impossible or impractical, and you're comfortable the extra parameter is not too much, I think it will work.  

Looking at the `String::format` function in the referenced PR, I see why the array is needed, unlike how the Python function operates, so I can live with that.

My ultimate goal is as much synchronicity with Python to assist new developers using Godot, so I appreciate the work!

**Comment by AlexHolly** [comment]
Yeah the thing is I didn't know there was such a function in python otherwise I would have used it as a reference.

I had a quick look, they support only the "{}" Syntax?
They have many features like formatting numbers in godot you have to use % for that.

http://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_format_string.html

**Comment by Mochnant** [comment]
@AlexHolly Within the String `format()` function, yes, I believe only the `{}` syntax is supported, though it is fairly broad, including bare `{}`, indexed `{0} {1}` and named `{first_name} {last_name}'.  They also support various formatting options, such as adding commas to numbers, and even column formatting.
