### ISSUE TITLE
Vulkan Mobile Renderer: Lag to crash on editing 3d scenes

### ISSUE THREAD

**Issue by WinterSnake** [godotengine/godot#54938]
### Godot version

4.0.dev

### System information

Arch Linux, Ryzen 9 3950x, 2x RTX 2070SUPER SLI, [Vulkan Version: 1.2.194](https://github.com/godotengine/godot/files/7531447/vulkaninfo.txt)

### Issue description

Unable to do anything within the 3D editor of Godot. Fills console with errors to the point of lagging/crashing the Godot editor.
Piped stdout/err to [file](https://github.com/godotengine/godot/files/7531377/vulkan-error.txt).

Happens only with the Vulkan Mobile Renderer, both for new and old projects. Vulkan Clustered works as intended as far as I can tell.
As soon as I switch to the 2D editor, the errors stop.

![image](https://user-images.githubusercontent.com/40584236/141605850-ffcaa9b9-c624-49a2-9af1-6ebe57bb41f0.png)
![image](https://user-images.githubusercontent.com/40584236/141607472-536300fd-58b8-48ae-bf81-9e0db2b345a6.png)

### Steps to reproduce

Open the 3D editor in any old or new project with Vulkan Mobile renderer

### Minimal reproduction project

[test project.zip](https://github.com/godotengine/godot/files/7531409/test.zip)

**Comment by WinterSnake** [comment]
![image](https://user-images.githubusercontent.com/40584236/141605850-ffcaa9b9-c624-49a2-9af1-6ebe57bb41f0.png)

**Comment by Whimfoome** [comment]
Can confirm
System: Arch Linux, AMDGPU driver, AMD R9 280X with Vulkan Mobile Renderer

Happens since 13769aebe9d435b9041f4ec8dc6f4b277a87b444 when #54867 was merged.
Found out by downloading the builds for the pull request's compiled binaries by github actions.
