### ISSUE TITLE
Magic Mouse not working with Godot

### ISSUE THREAD

**Issue by Glubker** [godotengine/godot#54943]
### Godot version

3.3.stable

### System information

Macbook AIR, Apple Chip

### Issue description

When I try to use Godot on my mac with my Apple Magic Mouse, I can't zoom in and it doesn't feel supported. Please add support for Apple Magic Mouse.

### Steps to reproduce

Happens when using Apple Magic Mouse on Macbook

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/49873.
