### ISSUE TITLE
Changing type in inherited scene created from external 3D scenes doesn't work

### ISSUE THREAD

**Issue by sygi** [godotengine/godot#54942]
### Godot version

v3.1.1-stable

### System information

Linux Debian 5.10.46-5rodete1

### Issue description

When changing the type in the inherited scene created after importing an external 3D scene, the type changes in the viewport/node list, but after saving and going to another scene, the changed type silently disappears.

### Steps to reproduce

Create and import a scene described in #54941.
Right-click the light node, change type to light, save and change the scene:
[Reproduction gif](https://i.ibb.co/QCrVSH9/godot.gif)

### Minimal reproduction project

Described in #54941.

**Comment by akien-mga** [comment]
Godot 3.1.1 was released 2.5 years ago and is no longer supported. Please test in Godot 3.4 or later.

**Comment by sygi** [comment]
I tested in Godot 3.4 and, while changing the type still doesn't work there, Godot shows an alert making it clear it's not supported.
