### ISSUE TITLE
LineEdit and TextEdit caret is no longer visible in a project, but still visible in editor

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#54955]
### Godot version

4.0.dev (c0fdbf16c)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 470.74)

### Issue description

LineEdit and TextEdit caret is no longer visible in a running project, but is still visible in editor controls. This may be a regression from theming/scaling-related changes (cc @pycbouh). I remember carets working a few months ago in `master`.

https://user-images.githubusercontent.com/180032/141660222-fe807097-5f02-4b5a-a758-f27d47882da9.mp4

### Steps to reproduce

- Add a LineEdit or TextEdit node in a project.
- Run the project and try to click on the text. Notice that no caret appears.

### Minimal reproduction project

[test_lineedit_textedit_caret.zip](https://github.com/godotengine/godot/files/7532828/test_lineedit_textedit_caret.zip)

**Comment by pycbouh** [comment]
> This may be a regression from theming/scaling-related changes

I guess, but I'm not sure why `Math::round(1 * get_theme_default_base_scale());` would be less than 1 under any circumstances. Base scale for the default theme should be either 1 or 2 (for hiDPI).

**Comment by MagdielM** [comment]
Can confirm this as of [97034939f], happens when using a custom theme resource with `default_base_scale` at 0 (because it defaults to 0). It does show if set to 0.5 or higher.

**Comment by pycbouh** [comment]
When it's 0 in a custom theme, it's fine. That's the "empty" value and it is ignored (or at least should be, unless there is some typo and that's the reason for all the problems here). The default theme should be used if you have it at 0 in a custom theme.

**Comment by MagdielM** [comment]
Not sure what to tell you then, this is what happens on my end:
![image](https://user-images.githubusercontent.com/56076033/145625640-8324f366-6ec2-4d7a-8621-795f57e03a74.png)

![image](https://user-images.githubusercontent.com/56076033/145625675-8ef004cb-bf3d-4e8f-be02-8914c520ae09.png)

**Comment by girng** [comment]
RX 480 (Windows 10). Base Scale has to be 0.5 or higher for the caret to show.

**Comment by pycbouh** [comment]
I found the problem and it also affected some other things, like color picker sliders. PR incoming 🙃
