### ISSUE TITLE
Godot cannot start as it fails to create a Vulkan window on a multi-GPU setup

### ISSUE THREAD

**Issue by KaruroChori** [godotengine/godot#54962]
### Godot version

v4.0.dev.calinou.ed300d7be

### System information

linux amd64, RTX 3070 and RTX 3060. Drivers updated to 460.91.03

### Issue description

The application cannot run. Vulkan is working fine with other applications as well as all the other APIs supported by these cards.
![image](https://user-images.githubusercontent.com/9377545/141665514-85f1028a-35b7-4974-830b-e4a9d8a2f49e.png)

### Steps to reproduce

Running the executable.

### Minimal reproduction project

No project required.

**Comment by Calinou** [comment]
Multi-GPU setups are not supported yet as per https://github.com/godotengine/godot/pull/49506#issuecomment-859520658.

**Comment by bruvzg** [comment]
We should add a check to reject devices without `present` capability, something like this:

https://github.com/coelckers/gzdoom/blob/01b825b18198126b1ea2f88b50a17a0c4477ac8b/src/common/rendering/vulkan/system/vk_device.cpp#L137-L147

**Comment by bruvzg** [comment]
Here's the aforementioned check implemented for Godot - #55020, but I haven't tested it on actual multi-GPU setup.
