### ISSUE TITLE
CharacterbBody2D's slide on ceiling does not stop the slide when turned off in `master` (works in 3.4)

### ISSUE THREAD

**Issue by himaghnam** [godotengine/godot#54969]
### Godot version

godot v4.0.dev.20211108.official [596865366]

### System information

windows 10

### Issue description

Characterbody2d's slide on ceiling does not stop the slide when turned off, comparing it with godot 3.4 , the kinematic body immediately stops and falls down.

### Steps to reproduce

jumping near a ceiling will reproduce the bug
press space

### Minimal reproduction project

[characterbody2d.zip](https://github.com/godotengine/godot/files/7533520/characterbody2d.zip)

**Comment by Calinou** [comment]
cc @pouleyKetchoupp

**Comment by gamergamesz** [comment]
Sorry, it was an error on my side it is working now. I added "Velocity = motion_velocity" after move_and_slide() to get the no slide motion, I thought turning off the slide on ceiling would completely stop sliding motion.

**Comment by pouleyKetchoupp** [comment]
Closing, I can confirm updating the velocity from `motion_velocity` is needed for the sliding to properly stop.
