### ISSUE TITLE
ScrollContainer internal ScrollBars exposed when saved as a separate scene

### ISSUE THREAD

**Issue by rafallus** [godotengine/godot#54960]
### Godot version

Master ed300d7be536b1ec325ba77521eceee73dd0e5fb

### System information

Arch Linux

### Issue description

When using the 'Save Branch as Scene' option with a ScrollContainer, the saved scene shows the internal children of ScrollContainer, i.e. the horizontal and vertical scroll bars
![ScrollContainer_bug](https://user-images.githubusercontent.com/29492561/141662881-35d60d13-a330-4bbf-ae99-e97ebabf6fdf.png)

### Steps to reproduce

- Add ScrollContainer node to a scene
- Select 'Save Branch as Scene' in the contextual menu from the node tree
- Open the new scene

**Comment by Calinou** [comment]
cc @KoBeWi

**Comment by KoBeWi** [comment]
It doesn't look related to my PR. #30391 only made the scrollbars hidden from accessing via script. In the case here it seems like the editor is setting their owner for whatever reason.

**Comment by KoBeWi** [comment]
This is regression from #45937

**Comment by KoBeWi** [comment]
This is regression from #45937
CC @revilo

**Comment by revilo** [comment]
@KoBeWi
I confirm, thanks for pointing out! 
When I replaced the usage of **duplicate_and_reown** by **duplicate_from_editor** for "Save branch as scene" to fix #45937, I had to setup the node owners in the same way as **duplicate_and_reown** did previously. It seems that I haven't done it in the right way obviously. Will have a deeper look into this ASAP.
