### ISSUE TITLE
Godot editor can't start because vulkan cannot find GPU. 

### ISSUE THREAD

**Issue by RedwanFox** [godotengine/godot#54968]
### Godot version

4.0.dev ed300d7be536b1ec325ba77521eceee73dd0e5fb

### System information

Windows 11, Nvidia Geforce RTX 3060 Laptop GPU, driver version 496.49

### Issue description

Can't start godot editor, because vulkan cannot find any GPU during init phase. Nvidia driver is installed

```sh
$ ./godot.windows.opt.tools.64.exe
Godot Engine v4.0.dev.custom_build.3e214a883 - https://godotengine.org
USER ERROR: vkEnumeratePhysicalDevices reported zero accessible devices.

Do you have a compatible Vulkan installable client driver (ICD) installed?
vkEnumeratePhysicalDevices Failure
   at: VulkanContext::_create_physical_device (drivers\vulkan\vulkan_context.cpp:694) - Condition "gpu_count == 0" is true. Returning: ERR_CANT_CREATE

USER ERROR: Changing the VSync mode is not supported by this display server.
   at: DisplayServer::window_get_vsync_mode (servers\display_server.cpp:332) - Changing the VSync mode is not supported by this display server.
USER ERROR: Sub-windows not supported by this display server.
   at: DisplayServer::create_sub_window (servers\display_server.cpp:196) - Method/function failed. Returning: INVALID_WINDOW_ID
USER ERROR: Condition "window_id == DisplayServer::INVALID_WINDOW_ID" is true.
   at: Window::_make_window (scene\main\window.cpp:229) - Condition "window_id == DisplayServer::INVALID_WINDOW_ID" is true.
```

Maybe related https://github.com/godotengine/godot/issues/54962

### Steps to reproduce

1. Download godot sources.
2. Build them with  `target=release_debug`
3. Run editor

**Comment by hbina** [comment]
Can you run games in Vulkan?

**Comment by mrjustaguy** [comment]
it is possible that it's trying to run off an IGPU that doesn't have vulkan drivers installed

**Comment by RedwanFox** [comment]
@hbina Yup vulkan games work ok, Doom Eternal at least.

I have added some debug printing as you suggested. Both `vkCreateInstance` and `vkEnumeratePhysicalDevices` return VK_SUCCESS error code. 

I have googled these discussions
https://stackoverflow.com/questions/68109171/vkenumeratephysicaldevices-not-finding-all-gpus/68631366#68631366
https://github.com/KhronosGroup/Vulkan-Loader/issues/552

and looks like this is exactly my problem because, I have integrated AMD GPU and discrete NVIDIA GPU.

After updating AMD chipset and GPU drivers to latest version everything seems to work for me.

**Comment by mrjustaguy** [comment]
Yea it's using your IGPU not your DGPU, there's some way to force the DGPU, but Don't know what it is exactly, as I only have a DGPU... There have been several other issues opened with the same story.

**Comment by Calinou** [comment]
> After updating AMD chipset and GPU drivers to latest version everything seems to work for me.

Closing, as this is not something that can be fixed on the Godot side.

**Comment by RedwanFox** [comment]
@mrjustaguy 
>Yea it's using your IGPU not your DGPU
Nope. It couldn't find any of adapters. And it was problem in AMD vulkan layer
