### ISSUE TITLE
suggestion for remote debug and live editing

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#5496]
I'm just new to godot.
after played it,I feel run the project is a little time-consuming. when run, the app will be reinstalled on the device, if just update the modified content will be much faster.
And I wonder whether script support live editing, it will be amazing if it does.

**Comment by reduz** [comment]
If you want to have full live editing and script reloading on device, you need to use this option:

![image](https://cloud.githubusercontent.com/assets/6265307/16474908/e04455b4-3e50-11e6-9d71-8033e4861951.png)

This will only upload the engine binary (7mb) and read your files via usb cable, and full live editing will work as it does when you run on desktop.  If you are using Godot stable (2.0.x) these options still need a little polish, the upcoming 2.1 release will have them working much better

**Comment by alexzheng** [comment]
OK, thanks for your replay.
I will wait for the upcoming 2.1 release.
Will it be available soon?

**Comment by vnen** [comment]
2.1 will be released when it's ready (we hope it'll be around sometime in July).

I'll close the issue since the requested feature is already in. Specific bugs with the feature should be reported in a new issue.
