### ISSUE TITLE
Vulkan: VoxelGI and SDFGI rendering exhibits a visible outline between surfaces and the sky

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#54978]
*Related to https://github.com/godotengine/godot/issues/56792.*

### Godot version

4.0.dev (c0fdbf16c)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 470.74)

### Issue description

VoxelGI rendering exhibits a visible line between surfaces and the sky. This has a fair chance of being related to GI rendering being deferred since https://github.com/godotengine/godot/pull/39827 (applies to both VoxelGI and SDFGI). This bug doesn't occur in `3.x` since GI rendering isn't deferred there.

**Edit:** This outline seems to take the ambient light color, as demonstrated here:

![image](https://user-images.githubusercontent.com/180032/143497796-433247d9-77a4-4c94-8ea7-07b1e6a6369d.png)

Enabling MSAA makes the issue less noticeable, but the bright line is still visible at 2× MSAA.

This bug also occurs with SDFGI, but it tends to be less noticeable overall.

### No MSAA + default VoxelGI properties + red environment (included in the MRP)

*Click to view at full size, look at the right side of the cube at the center of the image.*

![2021-11-14_18 55 05](https://user-images.githubusercontent.com/180032/141692951-57d8cda4-e82d-4fa2-bc18-f820bc161655.png)

### No MSAA + SDFGI + red environment

![image](https://user-images.githubusercontent.com/180032/141693099-4d3213a3-a3b6-41cd-86ea-317fe4d39295.png)

___

On the screenshots below, I've set the VoxelGI bias to 0 to make the line more visible, but it still happens with default VoxelGI settings.

### VoxelGI + No MSAA

![2021-11-14_18 49 25](https://user-images.githubusercontent.com/180032/141692965-6d889432-c922-4694-bc4d-9affb1f9bab3.png)

### VoxelGI + 2× MSAA

![2021-11-14_18 49 56](https://user-images.githubusercontent.com/180032/141692968-396a2d01-c526-4b0e-9a43-1edf40131efa.png)

### VoxelGI + 4× MSAA

![2021-11-14_18 50 09](https://user-images.githubusercontent.com/180032/141692970-4e4fd79b-b0c3-49e1-83cb-d1390a1e3596.png)

### VoxelGI + 8× MSAA

![2021-11-14_18 50 20](https://user-images.githubusercontent.com/180032/141692973-a7eda3db-91c6-41c1-ba1d-b61b20acf630.png)

### VoxelGI + FXAA

![2021-11-14_18 50 31](https://user-images.githubusercontent.com/180032/141692975-776d47a9-6f87-41d3-82c3-4da45a87b59d.png)

### VoxelGI + Half-resolution GI, no FXAA or MSAA

![2021-11-14_18 50 50](https://user-images.githubusercontent.com/180032/141692977-dcac00aa-b6d5-4a54-a6ee-669235a0687d.png)

### Steps to reproduce

- Add a VoxelGI node, a WorldEnvironment and a DirectionalLight3D with shadow enabled.
- Add some floating MeshInstances with their global illumination mode set to **Baked**. Place some meshes so that they sit in the shadow of other meshes.
- Select the VoxelGI node and click **Bake** at the top of the 3D editor.

### Minimal reproduction project

[test_voxelgi_sky_line.zip](https://github.com/godotengine/godot/files/7534337/test_voxelgi_sky_line.zip)

**Comment by akien-mga** [comment]
Fixed by #61070.
