### ISSUE TITLE
Cannot edit properties of remote objects in the Inspector

### ISSUE THREAD

**Issue by dalexeev** [godotengine/godot#54977]
### Godot version

v4.0.dev.custom_build [2e4e0a863]

### System information

Kubuntu 21.10

### Issue description

Unlike 3.x, in 4.0-dev I cannot edit properties of remote objects in the Inspector. When you try to change the value of a property, the messages "Set property_name" are printed in the Output Log, but nothing else happens (the value does not change either in the Inspector or in the game). This is probably a bug.

### Steps to reproduce

1. Run the project.
2. Go to the remote scene tree.
3. Select a node.
4. Try changing the value of some property in the Inspector.

### Minimal reproduction project

—

**Comment by Calinou** [comment]
I can confirm this on `master` ffc4d62e6. It works on `3.x` 3e7e70138.
