### ISSUE TITLE
Godot 4: `TileMap.set_cell(...)` do nothing after a `TileMap.clear()` call

### ISSUE THREAD

**Issue by gustavi** [godotengine/godot#54984]
### Godot version

v4.0.dev.20211108.official.596865366

### System information

Windows 10 64bit - Vulkan API 1.2.141 - GeForce GTX 1660 SUPER

### Issue description

After using `TileMap.clear()` a call to `TileMap.set_cell()` do nothing. Same behavior with `TileMap.clear_layer(...)`.

### Steps to reproduce

1. Create a`TileMap` 
2. Set a cell with `TileMap.set_cell(...)`
3. Call `TileMap.clear()`
4. Try to set the cell again
5. Nothing happened

### Minimal reproduction project

[tilemap_clear.zip](https://github.com/godotengine/godot/files/7534805/tilemap_clear.zip)

https://user-images.githubusercontent.com/2736557/141701637-f2f35ffa-9107-4411-88a3-244d7f4d1d5d.mp4

EDIT 2021-11-14 : add a video of sample project

**Comment by Calinou** [comment]
cc @groud
