### ISSUE TITLE
[Master] 3D collision is reset if the contact reported is set to anything but 0

### ISSUE THREAD

**Issue by xsellier** [godotengine/godot#54995]
### Godot version

4.0.dev b6c002f32d3ee01f227dbaaf15caf5ce378f2fb6

### System information

Linux binogure 5.14.0-2-amd64 #1 SMP Debian 5.14.9-2 (2021-10-03) x86_64 GNU/Linux

### Issue description

Using a RigidDynamicBody3D, Setting the number of Contact reported to anything but 0 will reset the node as soon as it stops moving.

![3d-collision-issue](https://user-images.githubusercontent.com/6616005/141783600-f09a2b27-35ac-4f6f-b8a3-c5efd8d24971.gif)

### Steps to reproduce

1. Checkout this repository: https://github.com/binogure-studio/real-estate-online to this commit: c4f8c72e297eec131ba75ac4ea80de206c3763f1
2. Open it with Godot engine
3. Load the scene `game/scene/classic/main.tscn`
4. See that the dice doesn't move once threw
5. Open `game/scene/dice/item.tscn`, edit the number of contacts reported to 4 (or more).
6. Load the scene `game/scene/classic/main.tscn`
7. See that the dice is reset once threw

**Comment by xsellier** [comment]
Sorry, not a bug.

**Comment by Calinou** [comment]
> Sorry, not a bug.

Do you mean this is due to something in your game code, or is this caveat already documented?

**Comment by xsellier** [comment]
There is a difference betnween `freeze` and `sleep`, when you put the rigid body on freeze it resets itself, but if you make it sleep, then it is ok.
