### ISSUE TITLE
ERROR: texture_set_data: Condition ' !texture ' is true.

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#5499]
**Operating system or device - Godot version:**
Mageia 6 x86_64, Godot HEAD (d81b635)

**Issue description** (what happened, and what was expected):
Opening a project outputs these errors:
```
ERROR: get: Condition ' !elem ' is true. returned: __null
   At: core/rid.h:146.
ERROR: texture_allocate: Condition ' !texture ' is true.
   At: drivers/gles2/rasterizer_gles2.cpp:902.
ERROR: get: Condition ' !elem ' is true. returned: __null
   At: core/rid.h:146.
ERROR: texture_set_data: Condition ' !texture ' is true.
   At: drivers/gles2/rasterizer_gles2.cpp:958.
```

This seems to be a recent regression, I don't remember seeing this before merging PRs this morning. On the other hand I don't see at a first glance in those PRs what could trigger this error.

**Comment by volzhs** [comment]
I have same issue but it happened before recent merging.
Some project didn't make error and some another did.
I couldn't find exact reason so far.

**Comment by vnen** [comment]
I saw this too for some time. And even in a project that shows it does not do it all the time. I couldn't grasp what texture it is trying to allocate.

**Comment by volzhs** [comment]
What I found is, this occurs only File system dock has a position can show file system trees and files in selected directory at start editor.

![image](https://cloud.githubusercontent.com/assets/8281454/16494025/b94d6234-3f22-11e6-829e-505196f6e72c.png)

**Comment by vnen** [comment]
Then it might have something to do with the thumbnails.

**Comment by volzhs** [comment]
weird thing is, error is occurred at editor start with first layout only.
if start editor with second layout and move file system panel to left like first layout, error is not occurred.

**Comment by reduz** [comment]
did anyone fix it? I used to be able to reproduce it but now i can't..

**Comment by akien-mga** [comment]
@reduz I don't think it was fixed, but maybe it's not reproducible because the FileSystem got broken tonight: #5590 :p
