### ISSUE TITLE
Particles2D - texture animation speed problem with random lifetime

### ISSUE THREAD

**Issue by RPicster** [godotengine/godot#54993]
### Godot version

3.4 stable

### System information

Windows 10 (GLES3)

### Issue description

When setting up a Particle2D or CPUParticle2D node with a animated texture (frames setup via a CanvasItemMaterial), the animation won't be fully played when using a random lifetime in the particle system.

The animation will always be played a speed depending on the full lifetime and will be cut off if the particle dies earlier (due to random lifetime)

It can be fixed in the Particle2D node by converting to a shader and changing `CUSTOM.y` to `tv` at the anim_speed line.

https://user-images.githubusercontent.com/9423774/141766384-797a590e-8ff0-482a-9885-dd455e5296f0.mp4

### Steps to reproduce

- Add a Particle2D or CPUParticle2D node
- Add a texture (using a spritesheet)
- Setup the CanvasItemMaterial to be a animated particle texture
- Add a random lifetime to the Particle node

### Minimal reproduction project

[3.4_particle_texture_animation_speed.zip](https://github.com/godotengine/godot/files/7537900/3.4_particle_texture_animation_speed.zip)

**Comment by akien-mga** [comment]
I guess both the current and "fixed" behavior could be considered valid?
How do other parameters behave in relationship to random lifetime, e.g. scale?

**Comment by RPicster** [comment]
> I guess both the current and "fixed" behavior could be considered valid? How do other parameters behave in relationship to random lifetime, e.g. scale?

I remember in the past no other parameters were "influenced" by the random lifetime.
But some time ago this behaviour was changed and now most parameters get influenced by the random lifetime and use the ranomized lifetime as their way to measure progressing through time.

**After a quick check, following parameters work with a modified random lifetime:**
- color ramp (gradient)
- angular velocity (curve)
- orbit velocity (curve)
- linear acceleration (curve)
- radial acceleration (curve)
- tangential acceleration (curve)
- damping (curve)
- angle (curve)
- scale (curve)
- hue variation (curve)
- animation offset (curve)

**And the following parameters don't work with it:**
- animation speed
- animation speed (curve)

So I would say that it's really the exception.

**Comment by Calinou** [comment]
Particle random lifetime was originally fixed in https://github.com/godotengine/godot/issues/43485, but I guess flipbook animation wasn't taken into account.

**Comment by RPicster** [comment]
> Particle random lifetime was originally fixed in #43485, but I guess flipbook animation wasn't taken into account.
> 
> Does this bug occur in 3D too?

Judging by the code: yes
I tried to reproduce it, but honestly 3D isn't my strength and I didn't find out how to use a flipbook animation in 3D.

**Comment by akien-mga** [comment]
For context as references were lost:
- Fixed in `4.0` by #55271.
- Fixed in `3.5` by #55717.
