### ISSUE TITLE
AnimationPlayer Loop button doesn't do anything

### ISSUE THREAD

**Issue by Whimfoome** [godotengine/godot#55002]
### Godot version

4.0.dev.mono 6715bc7754ccaed7fdd3fa383a4ba92b9bbdf551

### System information

Arch Linux, AMDGPU, Vulkan

### Issue description

This button doesn't do anything. The changes are only temporal until you open the editor again, or play the game:
![butonnomero1](https://user-images.githubusercontent.com/42871796/141832683-356e9dac-48fc-417c-9dfe-bd36727b45e2.png)

It changes color once clicked, and works in editor. That is until you close and open the editor again, or start the game, the changes are gone.
The only way that works to change if animation is looping is through the Advanced Import Dialog -> settings/loop_mode = "1" and once you change it and reimport, to change that parameter again (settings/loop_mode) you have to reload the whole editor
![image](https://user-images.githubusercontent.com/42871796/141833183-eff543cf-b759-45d8-901c-030b040b43dd.png)

### Steps to reproduce

1. Open Minimal Reproduction Project
2. Open Scene.tscn
3. From the editor click AnimationPlayer and click the loop icon
4. Reload editor
5. Changes are gone
6. Now try again but don't touch the AnimationPlayer, just double click *bouncycube.glb* and in settings/loop_mode set it to **1**
7. Now the animation is looping after reloading the scene.
8. Try to change loop_mode back to 0, without reloading the editor, and try to reimport, you won't be able to

### Minimal reproduction project

[NoLoop.zip](https://github.com/godotengine/godot/files/7540809/NoLoop.zip)

**Comment by Calinou** [comment]
This is likely because you're modifying the children of an imported scene, which means changes are lost when relaoding the scene. Instead, the editor should warn and prevent modification of the animation.

**Comment by Whimfoome** [comment]
I think the changes should be saved to the scene like before. I noticed because the animations in my game acted weird after I updated my Godot 4.0.dev version.

I think this started happening in a recent commit about implementing one more loop mode

**Comment by Whimfoome** [comment]
> This is likely because you're modifying the children of an imported scene

I am modifying instance in another scene of this scene. The changes should be saved in the new scene just like before. I am not modifying the original file.

**Comment by Calinou** [comment]
> I think this started happening in a recent commit about implementing one more loop mode

Can you try to build commit https://github.com/godotengine/godot/commit/efea3128c3b0d026a20efaf6bd46058c2b732519 (which is just before https://github.com/godotengine/godot/pull/53819 was merged) to confirm this?

**Comment by Whimfoome** [comment]
Sorry for misleading, seems like this is reproducible before this (efea3128c3b0d026a20efaf6bd46058c2b732519). Probably I do something wrong.

> Instead, the editor should warn and prevent modification of the animation.

Probably this is the best solution, to avoid mistakes like this in the future

**Comment by TokageItLab** [comment]
Not really related, but I need to change the selector of the importer to Enum instead of Int. I added this to my todo.

**Comment by KoBeWi** [comment]
In 410893a you get this warning:
![image](https://user-images.githubusercontent.com/2223172/169577063-4a1644cd-5098-422b-af1c-f9cdaea24c26.png)
which also opens a dialog when clicked:
![image](https://user-images.githubusercontent.com/2223172/169577153-6e012dce-00d4-40fb-becb-74ffc4968440.png)
so it's expected that the changes will not be saved when you edit the animation like this.
