### ISSUE TITLE
Ability to set templates path for godot_server

### ISSUE THREAD

**Issue by alketii** [godotengine/godot#5500]
Ability to set templates path for godot_server like
./godot_server.server.tools.64 --export "Linux X11" --templates "~/godot_dev/"

This could be useful for build server which supports multiple godot versions, also for packaging in linux distros, F-Droid, etc.

Thanks

**Comment by Calinou** [comment]
As export templates are now stored per-version (since Godot 3.0), this issue can now be closed. Custom export templates can still be specified in a project's export presets.
