### ISSUE TITLE
Godot 4 Gpu Pixel Snap is missing

### ISSUE THREAD

**Issue by Banduck** [godotengine/godot#55006]
### Godot version

v4.0.dev.20211108.official [596865366]

### System information

Windows 10

### Issue description

Godot 3 had a GPU Pixel Snap feature in Project Settings, and that was extremely useful for 2D games.
This option is missing in Godot 4 and that causes issues like this:
![image](https://user-images.githubusercontent.com/42905358/141825037-58001a24-721a-45bf-942f-a9d811124cfa.png)

### Steps to reproduce

Godot 3:
![image](https://user-images.githubusercontent.com/42905358/141823407-c7b5c5bf-99b5-42fb-9931-004a53b96e33.png)

**Comment by Calinou** [comment]
The option still exists as `rendering/2d/snap/snap_2d_vertices_to_pixel` (see also `rendering/2d/snap/snap_2d_transforms_to_pixel`). You probably want to enable both settings at the same time for pixel art games.

**Comment by Banduck** [comment]
@Calinou Those options are sadly not the same as `Gpu Pixel Snap`.
With `Gpu Pixel Snap`, the movement still looked smooth, while with `Snap 2d Transforms To Pixel` & `Snap 2d Vertices To Pixel` it looks choppy. It probably doesn't bother everyone, especially in a pixel game, but for those who want smooth movement (despite the pixel artstyle), it was very useful.
Also, even if I enable both, sometimes the same thing happens as in the screenshot.

**Comment by Calinou** [comment]
@Banduck Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by Banduck** [comment]
I noticed it's probably not about Godot 3/Godot 4 but it seems to have something to do with vulkan:

https://user-images.githubusercontent.com/42905358/141945790-bd7c040c-0fe2-44f1-b499-0a6524bf71c1.mp4

Here is the project, you can move the camera with the arrow key:
[Godot4.zip](https://github.com/godotengine/godot/files/7544477/Godot4.zip)
(If you enable the snap options, you will also see the choppy movement.)

And for comparison the same project in Godot 3 with Gpu Pixel Snap enabled:
[Godot3.zip](https://github.com/godotengine/godot/files/7544547/Godot3.zip)

**Comment by lawnjelly** [comment]
I suspect that's about the texture coordinates rather than snapping (the lines in the vulkan version).

**Comment by Banduck** [comment]
@lawnjelly  I did another Test and I think it's really the texture coordinates, but somehow this problem is also solved by Gpu Pixel Snap.

I set the resolution 1280 x 720 and scaled the TileMap node, this makes it more obvious that it's a texture problem.
**Godot 4 vulkan:**
![image](https://user-images.githubusercontent.com/42905358/141958885-63c4235b-7854-4c50-9843-0ca2ea2b259f.png)

But then I tried opengl3 and the problem is still there, just not as bad.
**Godot 4 opengl3:**
![image](https://user-images.githubusercontent.com/42905358/141959355-4d476f15-1863-4780-9943-2eedf673aa35.png)
(It looks exactly the same in Godot 3 **without** Gpu Pixel Snap.)

And THEN I tried it in Godot 3 **with** Gpu Pixel Snap enabled:
![image](https://user-images.githubusercontent.com/42905358/141959670-473092b2-bc88-4d03-8742-e01850269bcb.png)
perfect.

**Comment by lawnjelly** [comment]
The reason GPU affects it is because it is caused by small precision issues in where it reads texels at the borders. The very act of GPU snapping changes the alignment of the screen pixels to the texels, and thus which texel it decides to read.

However unfortunately it does not always completely solve this - we have had numerous issues in Godot 3.x with this, even with GPU snapping. This can also potentially be hardware dependent, with some GPUs having less precision.

See for example #39256, #39096.

**Comment by groud** [comment]
I think we can close this issue as solved by https://github.com/godotengine/godot/pull/54485.
Could you confirm `use_texture_padding` solves your problem ?

**Comment by Banduck** [comment]
Yes, thanks.

**Comment by RNwebdk** [comment]
![image](https://github.com/godotengine/godot/assets/16637404/c1a27110-c638-4ac9-85fb-dd8bd019b9fd)
In Godot 4, the setting previously known as "GPU Pixel Snap" in Godot 3 has been replaced with two new settings to help with pixel-perfect rendering. These settings are:
- Snap 2D Transforms to Pixel
- Snap 2D Vertices to Pixel
To find these them navigate to your project settings,Turn on advanced settings button,, look under the Rendering tab, and then click on the 2D section

**Comment by produno** [comment]
> * Snap 2D Transforms to Pixel
> * Snap 2D Vertices to Pixel
>   To find these them navigate to your project settings,Turn on advanced settings button,, look under the Rendering tab, and then click on the 2D section

This only seems to work correctly if mipmaps are turned off.

**Comment by tstefan23** [comment]
I'm facing issues with this right now, If I enable the two snap options, the lines go away; however, I get weird problems with collision shapes with uneven sprite sizes. Does this mean I should only use even sprite sizes?

**Comment by Calinou** [comment]
> however, I get weird problems with collision shapes with uneven sprite sizes. Does this mean I should only use even sprite sizes?

I suggest creating a post on the [forum](https://forum.godotengine.org/) with a minimal reproduction project (this may not be a bug, but a configuration issue).
