### ISSUE TITLE
HTML5 exported game in iframe loses keyboard input after unfocus and attempt to refocus

### ISSUE THREAD

**Issue by ShouxTech** [godotengine/godot#55017]
### Godot version

v3.4-stable_mono

### System information

Windows 10, GLES2

### Issue description

The canvas fails to regain capture input after clicking out of the iframe that it's located in. It only works the first time when you have 'Focus Canvas On Start' enabled. When the page loads, your input is captured and everything works fine but if you click off the iframe that the game is located in and try to click back in, your keyboard input doesn't work. Clicks work but keyboard input doesn't.

Attached is a video trying to show this.

https://user-images.githubusercontent.com/70824139/141878863-8ee9a511-3abf-419c-b08c-36e9fd0f7941.mp4

### Steps to reproduce

I have created a very simple project that displays a label when you press E. If you run it in Godot editor, it works fine.

To run the exported game, go into /export and if you have python 3.x installed, run ```python -m http.server``` or ```py -3 -m http.server```

Go to localhost://[the port that came from python output] in your browser and try to press E. It works. Now click out of the iframe and click back in it. It doesn't work.

The main script is located in res://Notification.cs

### Minimal reproduction project

[InputLogger.zip](https://github.com/godotengine/godot/files/7542651/InputLogger.zip)

**Comment by DoctorPoptart** [comment]
Honestly this error is probably your fault.

**Comment by xennyy** [comment]
don't care + didn't ask + cry about it + stay mad + get real + L + mald seethe cope harder + hoes mad + basic + skill issue + ratio + you fell off + the audacity + triggered + any askers + redpilled + get a life + ok and? + cringe + touch grass + donowalled + not based + your're a (insert stereotype) + not funny didn't laugh + you're* + grammar issue + go outside + get good + reported + ad hominem + GG! + ask deez + ez clap + straight cash + ratio again + final ratio + stay mad + stay pressed + pedophile + cancelled + done for + mad free + freer than air + rip bozo + :) + cringe again + mad cuz bad + lol + irrelevant + cope + jealous + go ahead whine about it + your problem + don't care even more + sex offender + sex defender + not okay + glhf + problematic

**Comment by ShouxTech** [comment]
One way to fix this is to go into game.js and remove every instance of ```evt.preventDefault()``` using ctrl + h

**Comment by Calinou** [comment]
cc @Faless

**Comment by Faless** [comment]
Is it working as expected in `3.3`?

**Comment by ShouxTech** [comment]
> Is it working as expected in `3.3`?

Yes. It works as intended. I installed 3.3 from [here](https://downloads.tuxfamily.org/godotengine/3.3/mono/) and remade the InputLogger (attached zip) and exported the project in HTML5 and keyboard input works again each time you refocus the iframe.

[InputLogger2.zip](https://github.com/godotengine/godot/files/7549562/InputLogger2.zip)

**Comment by Alexey-aka-sultan** [comment]
Sorry for the Google translator. Not only in C#. I observe the same bug in my game written in gdscript.

**Comment by Faless** [comment]
Yep, this is likely a regression from #52812

**Comment by JasonTable** [comment]
I noticed that in Firefox, if the game has a clickable button to capture the cursor, the cursor gets stuck captured and pressing escape wont free it like it normally should. However F5 refreshes the page and frees it. That's probably more of a Firefox bug though.
