### ISSUE TITLE
[3.4] Memory leak? between Dictionary(godot) and Dictionary(C#)

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#55027]
### Godot version

v3.4.stable.mono.official [206ba70f4]

### System information

Debian 11

### Issue description

This code give the issue:
   
   ```
  public System.Collections.Generic.Dictionary<int, Dictionary> SystemDict =
             new System.Collections.Generic.Dictionary<int, Dictionary>();
        public override void _PhysicsProcess(float delta)
        {
            Dictionary GodotDict = new Dictionary() { ["A"] = "1" };
            SystemDict[1] = GodotDict;
            GD.Print(SystemDict);
            GD.Print(GodotDict);
        }
```

### Steps to reproduce

Run it and check in Debugger TAB -> Monitors (Static + Static Max)

### Minimal reproduction project

[TestDictionary.zip](https://github.com/godotengine/godot/files/7547509/TestDictionary.zip)

**Comment by kleonc** [comment]
No leak in here, it's just GC not kicking in.

You can find many similar issues by [searching for "leak" and `topic:mono`](https://github.com/godotengine/godot/issues?q=is%3Aissue+leak+is%3Aclosed+label%3Atopic%3Amono), e.g. #46497, #41543.

**Comment by git2013vb** [comment]
Right... The problem is: I have no idea how to make a workaround - if exist. I use Dictionary(godot) to move data between server-clients(rpc 60 fps) and use Dictionary(c#) in order be able to use linq... So I'm stuck again  I guess :)

**Comment by git2013vb** [comment]
I investigate a bit more and seems its not Dictionary fault, But I'm not sure 100%.

From this minimum project GC work fine- I used Godot Dictionary - . It seems. 

In my original projet are involved more things lke linq, rpc..

It is possible to set something to be able to isolate the problem?

[TestDictionary.zip](https://github.com/godotengine/godot/files/7554191/TestDictionary.zip)

**Comment by kleonc** [comment]
> 
> [TestDictionary.zip](https://github.com/godotengine/godot/files/7554191/TestDictionary.zip)

In this one I don't see any leak too. So I still don't see the issue.

**Comment by git2013vb** [comment]
> > [TestDictionary.zip](https://github.com/godotengine/godot/files/7554191/TestDictionary.zip)
> 
> In this one I don't see any leak too. So I still don't see the issue.

Exactly. My point was :Dictionary not leak. If you re read my post you can see what I said :) 
My tests show me that is the rpc call who leak (as mentioned in #55086)

**Comment by kleonc** [comment]
> Exactly. My point was :Dictionary not leak.

So because:

- what you're reporting in this issue is a Dictionary related leak,
- you agreed there's no such leak,
- you've opened #55086 for investigating the same "leak" further,

I think there's nothing more to do in this issue and it can be closed.

**Comment by git2013vb** [comment]
Agree :)
