### ISSUE TITLE
Odd and annoying code folding in script editor

### ISSUE THREAD

**Issue by Notiee** [godotengine/godot#55023]
### Godot version

v4.0.dev.20211108.official [596865366]

### System information

Windows 11, Ryzen 5 2600x, GTX 1080 TI, Vulkan

### Issue description

Godot 4.0 pre-alpha has weird and unpredictable code folding, It's safe to assume its broken.

The code folding does not respect whitespace, linebreaks or comments etc. 

I find the behavior unpredictable, if i click collapse on a code block, the editor will try and collapse so there is one line break before the next code block, unless there is a comment then it will collapse till there is no newline left.

Indented blocks also don't respect the level of indentation and will collapse code beneath its level.

Here is a video showing the broken behavior aswell as how it should be from another editor:

https://user-images.githubusercontent.com/36038081/141946814-a9d613af-1c62-4994-b877-5baa5544a4d5.mp4

### Steps to reproduce

Try and fold any sort of code, i have shared the test project but any will do.

### Minimal reproduction project

[Script testing.zip](https://github.com/godotengine/godot/files/7544456/Script.testing.zip)

**Comment by jmb462** [comment]
It might be a regression since my commit : 752e2bcee06871c149f0ad465396a50c2d21264b
Don't have time right now to check, I will check this weekend if nobody has fixed it until the end of the week.

**Comment by Notiee** [comment]
Sounds good :)
