### ISSUE TITLE
Button->theme->stylebox->focus is applied on top of normal/hover stylebox

### ISSUE THREAD

**Issue by QazPolma** [godotengine/godot#55038]
### Godot version

3.4.stable

### System information

Linux Mint 20.1

### Issue description

"Button->theme->stylebox->focus" is applied on top of "Button->theme->stylebox->normal/hover" instead of replacing it.

### Steps to reproduce

Create a "button->theme->stylebox->StyleBoxTexture" for "normal" and "focus" fields. Give same transparency and different image for greatest effect.

### Minimal reproduction project

Project with 3 variations:
1."Focus" is fully transparent, so no visible effect.
2.All fields have same transparency, so "focus" amplifies the button.
3.All fields have same transparency and different image on "normal" from the rest, so "focus" image overlaps with "normal" and "hover".

[theme_focus.zip](https://github.com/godotengine/godot/files/7550318/theme_focus.zip)

**Comment by Calinou** [comment]
This is expected. The focus stylebox should be designed in a way that leaves its background visible – typically by making it display only an outline. You can achieve this by disabling **Bg > Draw Center** in StyleBoxFlat.

**Comment by jackcasey** [comment]
This is a problem IMO.

I am just trying to have a button that is dark normally. Has an outline when hovered or focused, and moves down a pixel when pressed (the whole button 'clicks' down, so the outline should follow). IE using 3 different images and clicked being priority.
![blue](https://user-images.githubusercontent.com/45890/152736813-8661cadb-8ebf-47f7-8be4-30dc35d08186.png) ![blue_focused](https://user-images.githubusercontent.com/45890/152736824-f14374a3-ae72-4a1f-bbdb-3461d465b63e.png) ![blue_pressed](https://user-images.githubusercontent.com/45890/152736835-969c5dcc-aeab-418b-8e20-4de9ae61c32f.png)


Here is what I've figured out:

1. Use the hover image as the focused image.
![Godot_v3 4 2-stable_win64_3c7USBESpe](https://user-images.githubusercontent.com/45890/152733646-7414667c-5c59-46e4-a3b1-570236fcbd9e.gif)
This is obviously no good as when the button is clicked it is also "focused" so the clicked image is always hidden behind the focus "overlay". This made the most sense to me. I assumed clicked would "overrule" focused as as higher priority style.

2. Use a transparent overlay as the focus image as god(ot) intended.
![blue_focus_overlay](https://user-images.githubusercontent.com/45890/152736634-41d27a9a-2a7b-4998-aeee-f91d1c14e904.png)
![Godot_v3 4 2-stable_win64_TJwEwhrNp0](https://user-images.githubusercontent.com/45890/152736703-d59feb60-08c3-48fe-9f2a-76ba5ee4eb99.gif)
The focus overlay can't move with the button or text when it gets pressed down :(

3. Clear the focused image in the theme, or leave it as empty:
![image](https://user-images.githubusercontent.com/45890/152734132-71e8509f-aa71-4713-8e16-f31f3db97211.png)
![image](https://user-images.githubusercontent.com/45890/152734159-a34c490c-cc2b-4f43-9273-b37afa348ffd.png)
![Godot_v3 4 2-stable_win64_jIO11dHKEX](https://user-images.githubusercontent.com/45890/152733766-93b20af1-e5ed-4038-a28f-af1105ae977a.gif)
Now Godot is automatically applying a blurry outline for the focus. Not good.

4. Use a StyleBoxEmpty as the focus style and just do without focus effects.
![image](https://user-images.githubusercontent.com/45890/152734356-8c5180b3-4f49-42d2-bc7c-6cb8992d7928.png)
![Godot_v3 4 2-stable_win64_f0Gh1eueKd](https://user-images.githubusercontent.com/45890/152734434-e11c9f23-cd4d-4d1a-aa96-71d6aba32103.gif)
This works ok for mouse driven games as focus isn't important as you always hover and click. But it means you have to make do with font color etc as a focus if you want to use a gamepad or keyboard to navigate the UI.



Basically if you want an image focus effect to change when clicked (eg move, or change color) you're out of luck? Or am I missing something?
