### ISSUE TITLE
a method to know current keyboard layout

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#5503]
**Operating system or device - Godot version:**
official 2.0.3stable

**Issue description** (what happened, and what was expected):

I would like to know what is the current keyboard layout (AZERTY, QWERTY, QWERTZ, DWOWAKR, etc) so the game automatically setup keyboard mapping without asking the player for interactions or configurations.

**Current workarounds**

A workaround is to "guess" according to what returns `OS.get_locale()`, but is not safe.

An other workaround when it is about mapping "WASD", is to use "ESDF" instead, but it might not be 100% universal, and might disturb some hardcore-gamers.

An other workaround for "WASD" that make AZERTY ("ZQSD") and QWERTx ("WASD") and QZERTY ("ZASD") all work out  of the box, is to map [WZ] [AQ] [S] [D].

~~PS : and if you also want to support DVORAK (",AOE") keyboard out of the box, you'll have to map [WZ,] [AQ] [SO] [DE].~~
edit : there are several variant of DVORAK : dvorak for left hand, for right hand and "normal" dvorak, each layout is different.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by SuperUserNameMan** [comment]
Okay, 

So I've started studying this idea, trying to implement ``OS_Window::get_latin_keyboard_variant()`` which was already implement for OSX.

Win32 API does not provide straight forward method to differentiate kb layouts based on AZERTY, QWERTY, QZERTY etc.

So far, i've done some experiments using [``GetKeyboardLayout()``](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646296(v=vs.85).aspx) and [``GetKeyboardLayoutName()``](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646298(v=vs.85).aspx) (which returns a string containing an hex number instead of a human readable string).

These functions will return a different "[Language identifier](https://msdn.microsoft.com/en-us/library/windows/desktop/dd318691(v=vs.85).aspx)" for each country and languages.

This "language identifier" does not give any obvious information about AZERTY, QWERTY etc.

If we really want this feature, and if we want to make it the most reliable possible, I think it would be required to list all "language identifiers" that are not QWERTY (since QWERTY would be default) and to store these lists into some static arrays that the ``OS_Window::get_latin_keyboard_variant()`` will have to scan.


Like i said upper, and if i understood correctly, this function is already available for OSX. 
On all other platforms, ``OS::get_latin_keyboard_variant()`` returns QWERTY by default.
On mobile platform, it does not matter.
On Linux, I have no idea how to implement it neither if it is possible.

**Comment by SuperUserNameMan** [comment]
Some more reading about an overcomplicated workaround :
http://archives.miloush.net/michkap/archive/2004/12/05/275231.html

And the legend of an undocumented ``GetLayoutDescription()`` function hidden in a comment :
http://archives.miloush.net/michkap/archive/2008/09/29/8968315.html

> ``HRESULT GetLayoutDescription (LPWSTR szId, LPCWSTR pszName, LPUINT uBufLength, DWORD dwFlags)`` that returns a human-readable IME description (like "English(US) - Dvorak"). Combining both together, it's easy to get a list of all active IMEs installed.

**Comment by SuperUserNameMan** [comment]
I've wrote some python tool scripts to collect keyboard layouts names into a CSV.

"layout names" are hexadecimal string like returned by the win32 GetKeyboardLayourName().
The human readable name is "layout text" that are available into the windows registry.
There is also a layout ID (the third column into the CSV) that is also available into the windows registry, but i don't know if it is usefull data.

The script and the csv are available here :
https://github.com/SuperUserNameMan/os_windows_get_latin_keyboard_variant

What is required now, is to test all layout to identify which ones are based on AZERTY, QWERTZ, QZERTY, DVORAK etc. (we can ignore QWERTY keyboards as it would be default)

If someone here wants to participate and has a google account, here is a shared google sheet :
https://docs.google.com/spreadsheets/d/1aKasLNLaXtWuPFENOP72f_WaWC2SreXvLhsWmb9OuJM/edit?usp=sharing

You can test several keywords layouts using the [Windows] + [Space] keys and add as much layouts as you want using the little keyboard layout icon into the task bar.

**Comment by reduz** [comment]
Godot already detects this and remaps the keys accordingly

**Comment by SuperUserNameMan** [comment]
@reduz : Unless I missed something into the Godot API, i'm not sure we are talking about the same thing.

For instance, if I setup bind "WASD" keys to action into Poject settings Input Map, this mapping will be correct only for QWERTY keyboards.
On my AZERTY keyboards, the W key is next to the X key, and the A key is at the place of the W key.
My players would have to setup the keyboard mapping manually to ZQSD or to press the [Window] + [Space] combination to ask windows to activate English kayboard layout. 
I think it is TOO complicated for some casual gamers.

So the solution i'm proposing is to add a get_latin_keyboard_variant() that would return "AZERTY" or "QWERTZ" or "QWERTY" etc, allowing to game to change the remap the keyboard mapping to actions appropriatly. 

I've found no way to do that in Godot.

**Comment by reduz** [comment]
there already is a function named exactly OS.get_latin_keyboard_variant()
:P it's just not exposed to script, I'll expose it

**Comment by SuperUserNameMan** [comment]
@reduz : yes but it returns QWERTY by default, because it is not implemented for Windows.
I tried it already.

**Comment by SuperUserNameMan** [comment]
(only OSX version seems to be implemented)

**Comment by SuperUserNameMan** [comment]
Okay,; for those still interested, i've managed to inventory as much latin keyboard layout variant as possible into [this CSV](https://github.com/SuperUserNameMan/os_windows_get_latin_keyboard_variant/blob/master/OS_Windows--get_latin_keyboard_variant()%20-%20keyboard_layouts.csv).


Actually, among the latin kb variants, there are more than just AZERTY, QWERTY, QWERTZ, QZERTY, DVORAK and NEO that were already listed [godot/core/os/os.h](https://github.com/godotengine/godot/blob/2420e46b449f4c8acdfe48c765ea52fc3e860de7/core/os/os.h#L396)

For instance :
- the turkmen keyboard layout is ÄWERTY (with a strange accent over the A), 
- the Turkish F keyboard is bizarre layout
- the Finland/Norway keyboard is some sort of "àS`ERT£" with Q and W accessed through Alt-Gr ...
etc

Also, there are several variants of DVORAK : LEFT HAND, RIGHT HAND and "normal" which each have a special layouts.


Even if it is possible to implement this feature for Windows, I still don't know if it is possible for other platforms, and if the current OSX implementation is reliable.


I don't know about the 3 persons who have reacted with a thumb-up to this thread ( @bojidar-bg , @timoschwarzer, @Zylann ), but personally i've stopped thinking this feature is really needed.

So, if no one complain, i vote for closing this feature request.

**Comment by Zylann** [comment]
A lot of the games I play assume I have a QWERTY keyboard and it's very annoying, especially when the keys are hardcoded or if the game has no remapping feature. if it's not possible to have a perfect solution, a tradeoff would be better than nothing.

**Comment by SuperUserNameMan** [comment]
@Zylann :

Maybe we could write a tiny tutorial or a note to add to the godot documentation to try to make other game-developers slightly more aware that there is something else than QWERTY, and that hard-coding key mapping is evil ?


As for us who are already aware of that and who would like to automate the key mapping according to the player kb layout, we could use some simple workarounds like this one :
- we could present the player a simple interface asking him to click on a button among "AZERTY", "QWERTY", "QWERTZ" etc and "OTHER". Each button would set a different preset, and clicking "OTHER" would ask the player to press a key for "up", an other for "down", etc.

That would be as much complicated than picked a flag to select a language.
And also, it would be reliable on all platforms.

What do you think ?

**Comment by SuperUserNameMan** [comment]
Well, i tried to git push my branch to github but something went wrong and git commands are all chinese to me.

So here is my Windows implementation of :

````
OS::LatinKeyboardVariant OS_Windows::get_latin_keyboard_variant() const {
	
	unsigned long azerty[] = { 
		0x00020401, // Arabic (102) AZERTY
		0x0001080c, // Belgian (Comma)
		0x0000080c, // Belgian French
		0x0000040c, // French
		0 // <--- STOP MARK
	};
	unsigned long qwertz[] = {
		0x0000041a, // Croation
		0x00000405, // Czech
		0x00000407, // German
		0x00010407, // German (IBM)
		0x0000040e, // Hungarian
		0x0000046e, // Luxembourgish
		0x00010415, // Polish (214)
		0x00000418, // Romanian (Legacy)
		0x0000081a, // Serbian (Latin)
		0x0000041b, // Slovak
		0x00000424, // Slovenian
		0x0001042e, // Sorbian Extended
		0x0002042e, // Sorbian Standard
		0x0000042e, // Sorbian Standard (Legacy)
		0x0000100c, // Swiss French
		0x00000807, // Swiss German
		0 // <--- STOP MARK
	};
	unsigned long dvorak[] = {
		0x00010409, // US-Dvorak
		0x00030409, // US-Dvorak for left hand
		0x00040409, // US-Dvorak for right hand
		0 // <--- STOP MARK
	};

	char name[ KL_NAMELENGTH + 1 ]; name[0] = 0;
	GetKeyboardLayoutNameA( name );

	print_line( name );

	unsigned long hex = strtoul(name, NULL, 16);

	int i=0;
	while( azerty[i] != 0 ) {
		if (azerty[i] == hex) return LATIN_KEYBOARD_AZERTY;
		i++;
	}

	i = 0;
	while( qwertz[i] != 0 ) {
		if (qwertz[i] == hex) return LATIN_KEYBOARD_QWERTZ;
		i++;
	}
	
	i = 0;
	while( dvorak[i] != 0 ) {
		if (dvorak[i] == hex) return LATIN_KEYBOARD_DVORAK;
		i++; 
	}

	return LATIN_KEYBOARD_QWERTY;
}
````

**Comment by LeonardMeagher2** [comment]
probably irrelevant, just thought I'd rewrite the code for no real reason

```
OS::LatinKeyboardVariant OS_Windows::get_latin_keyboard_variant() const {

    unsigned long azerty[] = { 
        0x00020401, // Arabic (102) AZERTY
        0x0001080c, // Belgian (Comma)
        0x0000080c, // Belgian French
        0x0000040c // French
    };
	
    unsigned long qwertz[] = {
        0x0000041a, // Croation
        0x00000405, // Czech
        0x00000407, // German
        0x00010407, // German (IBM)
        0x0000040e, // Hungarian
        0x0000046e, // Luxembourgish
        0x00010415, // Polish (214)
        0x00000418, // Romanian (Legacy)
        0x0000081a, // Serbian (Latin)
        0x0000041b, // Slovak
        0x00000424, // Slovenian
        0x0001042e, // Sorbian Extended
        0x0002042e, // Sorbian Standard
        0x0000042e, // Sorbian Standard (Legacy)
        0x0000100c, // Swiss French
        0x00000807 // Swiss German
    };
	
    unsigned long dvorak[] = {
        0x00010409, // US-Dvorak
        0x00030409, // US-Dvorak for left hand
        0x00040409 // US-Dvorak for right hand
    };

    char name[ KL_NAMELENGTH + 1 ]; name[0] = 0;
    GetKeyboardLayoutNameA( name );

    unsigned long hex = strtoul(name, NULL, 16);

    int i=0;
    while( i < 3) {
        if (azerty[i] == hex) return LATIN_KEYBOARD_AZERTY;
		if (qwertz[i] == hex) return LATIN_KEYBOARD_QWERTZ;
		if (dvorak[i] == hex) return LATIN_KEYBOARD_DVORAK;
        i++;
    }
	if (azerty[i] == hex) return LATIN_KEYBOARD_AZERTY;
    if (qwertz[i] == hex) return LATIN_KEYBOARD_QWERTZ;
	i++;

    while( i < 16 ) {
        if (qwertz[i] == hex) return LATIN_KEYBOARD_QWERTZ;
        i++; 
    }

    return LATIN_KEYBOARD_QWERTY;
}
```

**Comment by SuperUserNameMan** [comment]
I'm just bumping this one to remind other contributors that Linux / BSD / Amiga / <whatever others platform with keyboard input other than Windows> platforms still lack an implementation of this function, and that the MacOS implementation needs testing.

**Comment by icnikerazah** [comment]
https://stackoverflow.com/questions/21597804/determine-os-x-keyboard-layout-input-source-in-the-terminal-a-script
<img width="768" alt="ekran resmi 2018-01-22 16 12 26" src="https://user-images.githubusercontent.com/33985414/35222616-94bda080-ff8f-11e7-99ff-ca6ab67a9ab5.png">

**Comment by SuperUserNameMan** [comment]
apparently, you have implemented it for Linux #12480 #12517.
if no other platform needs an implementation, you could close this issue.

**Comment by icnikerazah** [comment]
My keyboard variant is not defined correctly in Editor Shortcuts. on Macos

**Comment by SuperUserNameMan** [comment]
@icnikerazah : i don't think your issue is related to the get_latin_keyboard_variant() method which only tries to tell wether the keyboard is QWERTY, AZERTY or WEIRDY.

**Comment by icnikerazah** [comment]
are qwerty, azerty, weirdy latin variant?

**Comment by rosshadden** [comment]
I came here wondering if such an automatic mapping was possible, though I figured it's not. I'm glad I found this issue, but it does sound like something that is probably best in dev-land to implement in-game mappings, and possibly pre-defined layouts. I just looked for an existing solution because I realized every time I make a game I always develop it with dvorak mappings, and switch them later, haha.

**Comment by KoBeWi** [comment]
> if no other platform needs an implementation, you could close this issue.

The remaining platforms are Android, iOS, UWP and HTML5 (probably). Do we need this method for these platforms?

**Comment by Calinou** [comment]
Now that #18020 is merged, this method is much less useful. Should we still keep this issue open or consider desktop-only support to be good enough for this method?

**Comment by SuperUserNameMan** [comment]
> One use case I see for this method is showing a keyboard image with example shortcuts, with the keyboard image matching the user's keyboard layout. Other than that, I can't see any other use cases for it.

in-game tutorial/help/hints : "When an enemy throw a grenade to you, press Q to catch it." (on azerty, this would be "A").

**Comment by WilliamTambellini** [comment]
Just a warning that 
OS.get_latin_keyboard_variant()
does nt seem to work correctly on Linux with godot 3.2.1 :
on my french azerty keyboard, it returns:  "QWERTY"
The OS (CentOS7) is correctly aware of the fr keyboard:
$ localectl 
   System Locale: LANG=en_US.UTF-8
       VC Keymap: fr
      X11 Layout: fr

**Comment by Calinou** [comment]
@WilliamTambellini The method implementation is here: https://github.com/godotengine/godot/blob/0f1da724924fc494bfd316c57757e0e1d7b90143/platform/linuxbsd/display_server_x11.cpp#L1861

**Comment by WilliamTambellini** [comment]
Tks @Calinou 
Looks like DisplayServerX11::get_latin_keyboard_variant is just not aware of the 'fr' layout:
	$ setxkbmap -print | grep xkb_symbols
        xkb_symbols   { include "pc+fr+us:2+inet(evdev)"        };

Preparing a PR.

**Comment by Calinou** [comment]
@WilliamTambellini OK :slightly_smiling_face: Make sure to open the pull request against the `master` branch, we can backport it to the `3.2` branch afterwards.

**Comment by WilliamTambellini** [comment]
sure: done:
https://github.com/godotengine/godot/pull/39330

**Comment by SuperUserNameMan** [comment]
I've received a Google notification of someone trying to access this doc :
https://docs.google.com/spreadsheets/d/1aKasLNLaXtWuPFENOP72f_WaWC2SreXvLhsWmb9OuJM/edit?usp=sharing

I don't think it is useful information anymore, but just in case, i have salvaged it from the recycle bin and restored the share.

Maybe someone more involved should make a copy just in case I clean up my drive again.

**Comment by Calinou** [comment]
This was implemented by https://github.com/godotengine/godot/pull/39457 (and made less relevant by https://github.com/godotengine/godot/pull/18020), closing.
