### ISSUE TITLE
Base class problem

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#55035]
### Godot version

3.4 stable

### System information

w10 64

### Issue description

I don't know how to describe this, just the base class code has no effect.

![Captura](https://user-images.githubusercontent.com/19652075/142066835-9cbbeb34-1a26-479d-8a24-2aa8ca03a620.PNG)

![Captura3](https://user-images.githubusercontent.com/19652075/142066846-fb4911bd-b79c-423b-8c72-51614e27f2e6.PNG)

### Steps to reproduce

Run the project

### Minimal reproduction project

[testBase.zip](https://github.com/godotengine/godot/files/7549896/testBase.zip)

**Comment by Calinou** [comment]
[The parent `_process()` function is called automatically in Godot 3.x, so you do not need to call it manually with `._process(delta)` in the child class.](https://github.com/godotengine/godot/issues/29271) This behavior was changed in Godot 4.0, but it can't be backported to 3.x to avoid breaking compatibility with existing projects.
