### ISSUE TITLE
Stationary RigidDynamicBody2D remains stationary when gravity_scale is changed from 0

### ISSUE THREAD

**Issue by nabfrew** [godotengine/godot#55047]
### Godot version

v4.0.dev.20211108.official [596865366]

### System information

Windows 10

### Issue description

If a `RigidDynamicBody2D` is completely stationary with 0 gravity, the gravity does not take effect when it is turned back on, until an impulse is applied.

You also can get the bug if the `gravity_scale` is very low, e.g 0.001, and the impulse can fail to 'activate' the gravity if it is very small, e.g. length 1.

### Steps to reproduce

Create RigidDynamicBody2d and set `gravity_scale` to 0. Add a script that changes the `gravity_scale` after instantiation. It will remain stationary. An applied impulse will activate it again, and it will then be affected by gravity. 

### Minimal reproduction project

[GravityBug.zip](https://github.com/godotengine/godot/files/7552687/GravityBug.zip)

**Comment by starcin** [comment]
Can this be about "can_sleep" property?
Does setting can_sleep to false change this behavior?

**Comment by nabfrew** [comment]
You're right, it doesn't happen if can_sleep is false.

**Comment by Calinou** [comment]
@pouleyKetchoupp Do you think changing the gravity should force all RigidBodies to wake up?

**Comment by nabfrew** [comment]
Given the `junior job` tag, maybe I'll take a crack at it myself.

**Comment by brennengreen** [comment]
Hi, doing some initial research on this task @pouleyKetchoupp 

It looks like the relevant method you're discussing in `physics_body_2d.cpp` is:

```
void RigidDynamicBody2D::set_gravity_scale(real_t p_gravity_scale) {
	gravity_scale = p_gravity_scale;
	PhysicsServer2D::get_singleton()->body_set_param(get_rid(), PhysicsServer2D::BODY_PARAM_GRAVITY_SCALE, gravity_scale);
}
```

You seem to be suggesting that this change should be done in the servers directly, e.g. actually doing the condition to check if the current gravity scale value is zero, if so then waking up the rigid body and then setting scale in `godot_body_2d.cpp`

So for some initial psuedo code the solution here would look something like:

```
void GodotBody2D::set_param(PhysicsServer2D::BodyParameter p_param, const Variant &p_value)
{
    switch(p_param) {
    ...
    case PhysicsServer2D::BODY_PARAM_GRAVITY_SCALE: {
        if (gravity_scale == 0) {
            wakeup();
        }
        gravity_scale = p_value;
    }
    ...
    }
    ...
}
```

Seems pretty straightforward though just wanted to verify as I don't use any other `::set_param` cases using wakeup() directly.

**Comment by nabfrew** [comment]
I've tried this in `physics_body_2d.cpp`

```
void RigidDynamicBody2D::set_gravity_scale(real_t p_gravity_scale) {
	bool wake = gravity_scale == 0 && p_gravity_scale != 0;
	gravity_scale = p_gravity_scale;
	PhysicsServer2D::get_singleton()->body_set_gravity_scale(get_rid(), gravity_scale, wake);
}```

and made a the new `body_set_gravity_scale` that calls `wake()`. I've not manage to get it tp compile because I'm a cpp noob and haven't had much time to debug it.

**Comment by pouleyKetchoupp** [comment]
@nabfrew @brennengreen Thanks both for giving it a try! I've recommended making the change in the physics servers directly because this way it fixes the issue not just for RigidDynamicBody2D nodes, but also when creating bodies from the physics server directly, which some users do for performance reasons.

I think we can go ahead with @brennengreen's PR now, it seems pretty close to be finalized.
