### ISSUE TITLE
Return value within match keyword in typed function will cause parse error in the release export

### ISSUE THREAD

**Issue by Xwdit** [godotengine/godot#55045]
### Godot version

4.0.dev(7d1b454)

### System information

Windows 11, RTX 2060, Vulkan

### Issue description

Return value within match keyword in typed function will cause `"Parse Error: Not all code paths return a value"` in the release export, even if I used `_:` to define the default return value.

This problem only occurs in `target=release` build, and it works fine in other build targets.

### Steps to reproduce

Copy the following code into a script file and try to run it in the release export should reproduce the error:
```gdscript
func test(_text:String)->int:
    match _text:
        "sometext":
            return 0
        _:
            return 1
```

### Minimal reproduction project

```gdscript
func test(_text:String)->int:
    match _text:
        "sometext":
            return 0
        _:
            return 1
```

**Comment by 4d49** [comment]
Reproduction project.
[test.zip](https://github.com/godotengine/godot/files/7647182/test.zip)

**Comment by globz** [comment]
Hi, I have the same parsing error with this build v4.0.beta7.official [0bb1e89fb], anyone has an idea on how to fix this?
