### ISSUE TITLE
[GDScript] Cant use Consts or enums as int annotations (e.g. RPC channel parameter)

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#55055]
### Godot version

v4.0.dev.custom_build [78931aa04]

### System information

manjaro 21, AMD Radeon r7 200 series, Vulkan, 8GB Memory

### Issue description

You cant pass a const or enum as a parameter on the `@rpc` notation:

the const inside a Singleton called `Network`:
![image](https://user-images.githubusercontent.com/58845030/142204712-2fcac10d-0fcc-40c6-bb5e-a3beb75d8376.png)

another script which tried to access the const:
![image](https://user-images.githubusercontent.com/58845030/142204676-9d4bf9f4-8ac3-4921-8260-62e8367cfbe9.png)

PS: I tested with enums and you cant do that either!

### Steps to reproduce

* Create a Singleton
* On a node attach a new script
* type as shown above

### Minimal reproduction project

N/a

**Comment by Calinou** [comment]
cc @vnen @Faless

**Comment by Faless** [comment]
As far as I understand this is a limitation of the annotation system that do not resolve const types when doing type checking.

**Comment by dalexeev** [comment]
Closed by #71634.
