### ISSUE TITLE
Group membership of instances can't be modified from the editor

### ISSUE THREAD

**Issue by lonesurvivor** [godotengine/godot#5505]
**Operating system or device - Godot version:**
Windows 7 - 2.1 alpha build

**Issue description** (what happened, and what was expected):
Overwriting group memberships of instantiated scenes can't be modified (at least not from within the editor).

**Steps to reproduce:**
Assign a group to a root node of a scene, then save the scene and instantiate it in another scene. The instance belongs to that group (as shown in the editor as well as tested in a script). However, if you remove the membership from the instance in the editor, it is still in that group (when tested by script). If you close and reopen the scene, the membership is shown in the editor again.

I'm not sure if that is intended behavior, since the group editor doesn't have reset buttons like the properties have. If it is, the group editor should be hidden when an instance of another scene is selected since changes don't have an effect anyway.

edit:
It seems that adding groups to instanciated scenes is possible, only removing the "inherited" ones isn't.

**Comment by vnen** [comment]
I don't think this is a bug. The "inherited" group is saved on the template scene, so if you save the scene where its instanced it can't remove the group, since it's not on that scene. If it removed from the template scene, them it would remove from everywhere, which might not be intended.

The bug here is that the UI let's you remove the group when it makes no difference.

**Comment by lonesurvivor** [comment]
Ok, good to know. I kind of thought that already, but wasn't sure. So it just should't be possible to remove groups on instances if they were added in the template scene.

**Comment by reduz** [comment]
It's not really a bug, but I suppose the UI should lock the signals and groups that come from the instance/inheritance
