### ISSUE TITLE
godot 4.0 skeleton3Dstack with fabrik and lookat error spam

### ISSUE THREAD

**Issue by barbaros83** [godotengine/godot#55078]
### Godot version

4.0dev from nov-9

### System information

Solus OS

### Issue description

Im getting the: (The target vector and up vector can't be parallel to each other.) error spam on godot 4.0 when i have a skeletonModificationStack3D with fabrik and lookat at the same target.
I have uploaded a minimal reproducable project below, as soon as you open the project the error spam starts.

### Steps to reproduce

As soon as you open the project the error spam starts, it has to do with the skeletonIk3D.

### Minimal reproduction project

[SkeletonLookAt3D.zip](https://github.com/godotengine/godot/files/7560405/SkeletonLookAt3D.zip)

**Comment by akien-mga** [comment]
Fixed as the SkeletonModificationStack3D were removed, pending a rewrite in a better system.
