### ISSUE TITLE
[Master] TextureButton textures doesn't match the expected texture

### ISSUE THREAD

**Issue by xsellier** [godotengine/godot#55087]
### Godot version

4.0.dev 15062513c01a835f59d9c905e5e65a7002d6c370

### System information

Linux binogure 5.14.0-2-amd64 #1 SMP Debian 5.14.9-2 (2021-10-03) x86_64 GNU/Linux

### Issue description

When hoevered the TextureButton use the Disabled texture instead of the Hover texture.

![image](https://user-images.githubusercontent.com/6616005/142420393-64718dda-14e8-48f3-88d0-40512e6ab57f.png)

### Steps to reproduce

- Launch Godot
- Create a TextureButton
- Add those textures:
Normal - ![image](https://user-images.githubusercontent.com/6616005/142420498-19913e77-3ebe-4308-916c-f4338f2a4b9c.png)
Hover - ![image](https://user-images.githubusercontent.com/6616005/142420535-361f350e-d187-4e8b-a0ba-fee18b6d639f.png)
Pressed - ![image](https://user-images.githubusercontent.com/6616005/142420542-d3f6dd55-a0b0-49bb-82dc-f5145bace561.png)
Disabled - ![image](https://user-images.githubusercontent.com/6616005/142420547-b736c0f4-7fbf-47f2-b671-74d4d0ff3b3f.png)

**Comment by Calinou** [comment]
Can you reproduce this in 3.4?

**Comment by xsellier** [comment]
> @xsellier Can you reproduce this in 3.4?

No idea, I don't use Godot 3.4 sorry.

**Comment by and-rad** [comment]
@Calinou It doesn't seem to happen in 3.4. I was able to reproduce it and somehow the two texture resources getting mixed up ended up having the same uid, which 3.x doesn't have, right? I could fix it by manually changing the uid in the *.import file of one of the affected textures. The question is how they ended up having the same uid in the first place.

@xsellier Do you remember how you got the images into the engine for the first time? I selected all of them in the file explorer and dragged them into the editor's resource explorer. There seem to be some problems with that workflow at the moment anyway (#53871), so maybe that's related.

In any case, would it be a good idea to implement a resource uid validator that runs periodically or at the request of the user and checks all resources for duplicate uids? As there seem to be some bugs with the uid system still, that might be a good idea in the near-to-mid term.

**Comment by xsellier** [comment]
Hey,

This bug has been fixed, cannot reproduce it on the master branch.
