### ISSUE TITLE
`TextServer` seems to merge Latin characters with the default project font

### ISSUE THREAD

**Issue by pycbouh** [godotengine/godot#55100]
### Godot version

4.0.dev.20211117

### System information

Windows 10

### Issue description

`TextServer` seems to consider some sequences of Latin characters as one grapheme, at least with the default font. It doesn't happen in the editor, but happens when you run a project with a `TextEdit` in the scene. Trying to select the text causes this behavior:

https://user-images.githubusercontent.com/11782833/142471901-4534a563-ab70-4536-9239-68cefda09838.mp4

I've run into this issue with `fi` and `ff`. It seems that enabling `caret_mid_grapheme` allows to select individual characters once again (but only with Shift + Arrows, mouse selection still handles it as one unit).

I noticed this behavior while working with `TextServer` in engine code, and I believe that the problem lies somewhere in `shaped_text_get_glyphs` and related methods and computations. @Paulb23 noted that this behavior may be desirable for some languages, but IMO it's a problem when this happens with English text and default project font, as that can trip users.

### Steps to reproduce

1. Create a new project with a scene containing a `TextEdit` or `LineEdit`.
2. Either pre-fill or fill it at runtime with `ff` or `fi`.
3. Try selecting individual characters.

### Minimal reproduction project

[textserver-ff-grapheme.zip](https://github.com/godotengine/godot/files/7565003/textserver-ff-grapheme.zip)

**Comment by bruvzg** [comment]
`ff`, `fl`, `fi`, `ffi` and many others are standard ligatures, if a font is designed to use them, merging it to the one grapheme is a correct behavior (it's done by HarfBuzz, not TextServer code).

But, seems like I have missed mid-grapheme cursor handling in the mouse selection (`shaped_text_hit_test_position`).

**Comment by pycbouh** [comment]
> are standard ligatures, if a font is designed to use them, merging it to the one grapheme is a correct behavior (it's done by HarfBuzz, not TextServer code).

Yes, that may be technically a correct behavior, but this isn't a great user experience. Should we change the default font then to the one that doesn't have ligatures?

**Comment by Calinou** [comment]
Web browsers can handle selecting `ffi` mid-grapheme with both mouse and keyboard. We should try to do the same.

**Comment by pycbouh** [comment]
Should `caret_mid_grapheme` be on by default then?

**Comment by bruvzg** [comment]
> Yes, that may be technically a correct behavior, but this isn't a great user experience.

Mouse selection is a bug, I'll fix it. Mid-grapheme caret probably should be enabled by default. So probably no reason to change the font.

**Comment by pycbouh** [comment]
Yes, I understand that it's a bug 🙃 Okay, setting it to on by default (and fixing the mouse bug) sounds good then!

**Comment by bruvzg** [comment]
Also, it's possible to disable this behavior, we'll need to add OpenType feature overrides to font and set it for built-in font by default. Currently, it can be done for specific control only.

<img width="389" alt="Screenshot 2021-11-18 at 21 00 47" src="https://user-images.githubusercontent.com/7645683/142479870-58498559-fc05-4c51-b11d-98a46aa450c8.png">
 
Note: there's another bug in property loading, and it will be applied only after re-entering text.
