### ISSUE TITLE
uwp export generates manifest with incomplete tag

### ISSUE THREAD

**Issue by ederspvg** [godotengine/godot#55106]
### Godot version

3.4.stable

### System information

Windows 7

### Issue description

Follow the step by step:

1: Export UWP and generate appx package file
2: Change the Example.appx package to Example.zip
3: Edit the appxmanifest file
4: When opening the appxmanifest file you can see that the last tag is incomplete: it is </Packag instead of </Package>

Como meu inglês é fraco, segue abaixo em português BR:
Segue o passo a passo:

1: Exportar UWP e gerar o arquivo de pacote appx
2: Alterar o pacote Exemplo.appx para Exemplo.zip
3: Editar o arquivo appxmanifest
4: Ao abrir o arquivo appxmanifest é possível verificar que a última tag está incompleta: está </Packag ao invés de </Package>

### Steps to reproduce

Follow the step by step:

1: Export UWP and generate appx package file
2: Change the Example.appx package to Example.zip
3: Edit the appxmanifest file
4: When opening the appxmanifest file you can see that the last tag is incomplete: it is </Packag instead of </Package>

### Minimal reproduction project

Vou tentar subir um pequeno projeto amanhã (estou abrindo está issue pelo celular em um ônibus fretado neste momento - Sorry)

**Comment by panreyes** [comment]
This issue is 1.5 years old and I can't reproduce it on my PC, in Godot 3.5.
For the sake of cleanup, I would close it with a solved tag.
