### ISSUE TITLE
SceneTreeDialog complains about transient parent with other exclusive child

### ISSUE THREAD

**Issue by Razoric480** [godotengine/godot#55133]
### Godot version

4.0dev

### System information

Windows 11 Pro

### Issue description

When picking a node when adding a new node in the animation editor, double-clicking a node in the list causes a "Transient parent has another exclusive child." error to be emitted by `Window::set_visible`.

### Steps to reproduce

1. New scene with a Node2D and an AnimationPlayer
2. Add a new track using the AnimationPlayer's Add Track button (doesn't matter what kind, so long as it's one that has you picking a node in the scene tree)
3. Double click on a node.
4. See output.

Clicking on the _Open_ button does not generate the error.

**Comment by gustavi** [comment]
Note: I also have a "Transient parent has another exclusive child." message when I export a game. I don't know if it's related or not.

**Comment by Anything-Games** [comment]
I also have gotta the "Transient parent has another exclusive child." error message when exporting my game, both on 4.0 alpha 3, and the new 4.0 alpha 4.

I have no clue how to fix this, so now I can't really do anything, it was working fine, I saved and closed my project, started it back up a few hours later and it no longer works. I updated to the new alpha 4 and was hoping it was going to fix it, but sadly it didn't.

I use windows 10 if that helps any.

**Comment by Syntaxxor** [comment]
Hopping in to say I also get that error message when I export the game, on 4.0.alpha8.

**Comment by cloa513** [comment]
I get this error with Win 10 when instancing a scene.

**Comment by amicharnoff** [comment]
> 
I have the issue @Syntaxxor . Did you figure out a solution?

**Comment by Travistyse** [comment]
Just chiming in to say that I'm also unable to export due to a transient parent has another exclusive child error. Alpha 8

**Comment by gustavi** [comment]
Are you sure you are unable to export? I have the warning but I can export without any issue.

**Comment by Calinou** [comment]
> (I'm not sure why this is formatted incorrectly in Github)

Code blocks should use triple backticks like this (with an optional language name for syntax highlighting):

\`\`\`gdscript
code here
\`\`\`

**Comment by mojoyup** [comment]
I have the 4.0 beta1 20d667284 and I am having an export issue also with similar results. I get the "Transient parent has another exclusive child" exporting in different folders. Also, in the game I am noticing that my network.gd autoload doesn't get fired from an exported exe and only works in the editor. 

I question if the _ready() is an issue of this also, but open to any issue honestly. I created #66324 before I finally found this issue. I can close mine if this is the same thing. 

How do I get my network.gd to work? I have a firebase.gd in autoload also but it works fine.

**Comment by Sergey-PrudentDev** [comment]
This continues to be a error when exporting to Android.

My logs looks like this:
```
Could not find version of build tools that matches Target SDK, using 28.0.3
Could not find version of build tools that matches Target SDK, using 28.0.3
  modules/mono/glue/runtime_interop.cpp:1303 - Failed to export project: Target platform not yet implemented.
0 param: --xr_mode_regular
1 param: --use_immersive
ADDING: classes.dex
...
Could not find version of build tools that matches Target SDK, using 28.0.3
Signing binary using: 
C:/Users/me/AppData/Local/Android/Sdk/build-tools/28.0.3/apksigner.bat sign --verbose --ks <REDACTED> --ks-pass pass:<REDACTED> --ks-key-alias <REDACTED> C:/Users/me/AppData/Local/Godot/tmpexport.1686651165.apk
Signed

  Transient parent has another exclusive child.
Installing to device (please wait...): Google Pixel 6a
```

Then the "Target platform not yet implemented" pop up:
![image](https://github.com/godotengine/godot/assets/87621722/e4b2d338-08dd-44e9-bd83-a3be9f49c656)

Sadly this all worked before I upgraded my Android to 13...

**Comment by akien-mga** [comment]
@Sergey-PrudentDev That's unrelated to this issue. Your problem is:
```
Could not find version of build tools that matches Target SDK, using 28.0.3
```
You should install Build Tools 33.0.2 (current version used by Godot 4.0).

**Comment by Sergey-PrudentDev** [comment]
Thank you for that info. I have made sure that Build Tools 33.02 is installed and now I have one error less. Still I see this:
`--- Debugging process started ---
Godot Engine v4.0.3.stable.mono.official.5222a99f5 - https://godotengine.org
Vulkan API 1.3.224 - Forward Mobile - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 2080 SUPER
 
--- Debugging process stopped ---
Installing to device (please wait...): Google Pixel 6a
  modules/mono/glue/runtime_interop.cpp:1303 - Failed to export project: Target platform not yet implemented.
0 param: --xr_mode_regular
1 param: --use_immersive
ADDING: 
...
Signing binary using: 
C:/Users/me/AppData/Local/Android/Sdk/build-tools/33.0.2/apksigner.bat sign --verbose --ks <REDACTED> --ks-pass pass:<REDACTED> --ks-key-alias <REDACTED> C:/Users/me/AppData/Local/Godot/tmpexport.1686710340.apk
Signed

  Transient parent has another exclusive child.
Installing to device (please wait...): Google Pixel 6a
`

Notice the two errors:
-    modules/mono/glue/runtime_interop.cpp:1303 - Failed to export project: Target platform not yet implemented.
-    Transient parent has another exclusive child.

This only happens when trying to do Remove Debug from within Godot (.NET).

**Comment by akien-mga** [comment]
This is still off topic, but there's no Android support for C# in 4.0, so you shouldn't be able to start the export at all normally (no export templates provided).

**Comment by Sergey-PrudentDev** [comment]
Doesn't this limit the usefulness of the .NET version of Godot significantly? Is it on the timeline to get implemented? Is there somehow I can contribute to make this a reality?

**Comment by Syntaxxor** [comment]
@Sergey-PrudentDev I highly recommend checking [this page](https://docs.godotengine.org/en/stable/contributing/ways_to_contribute.html) of the documentation, as it provides guidelines for feature proposals, code contribution, testing, and much more. You can also talk about this in the Discord, the forums, or the contributor chat. However, it's still off-topic for this issue.
