### ISSUE TITLE
Attaching Generic class script in editor makes Godot unable to find class

### ISSUE THREAD

**Issue by markdibarry** [godotengine/godot#55131]
### Godot version

3.4 stable mono

### System information

Windows 10

### Issue description

In the editor, if adding a generic typed class (Foo<T>) with a child node that uses the provided Type, Godot will say it cannot find the class. This is not an issue if you add them through the script.

### Steps to reproduce

Run the minimal reproduction project and make sure to have the following setup.
![image](https://user-images.githubusercontent.com/21325943/142638215-94a7f174-3ca5-430b-a3fd-9af79f7d65ba.png)

Make sure the classes are as follows:
![image](https://user-images.githubusercontent.com/21325943/142638296-65ad683e-a56e-4ba9-9e08-4bf61a650399.png)

Run the project, and it should create the "Baz<string>" node with no issue.

Comment out lines 7 and 8 of Foo.cs
![image](https://user-images.githubusercontent.com/21325943/142638997-c0d95b07-9d16-4680-8830-95af8dcc15b4.png)

Instead, add a Node2D and attach the Baz<T> script to it like so:
![image](https://user-images.githubusercontent.com/21325943/142638944-1af3bd8c-d5a9-4e0b-b5b1-a568f86332ee.png)

Run the project, and it should show:
![image](https://user-images.githubusercontent.com/21325943/142638859-04c96d8b-e956-4c06-8ba1-39ee35658925.png)

### Minimal reproduction project

[GenericTest.zip](https://github.com/godotengine/godot/files/7570739/GenericTest.zip)

**Comment by akien-mga** [comment]
Please comment when closing an issue so that we know what the resolution was.

**Comment by markdibarry** [comment]
Sorry. I was told this is not a bug but a limitation of Godot.
