### ISSUE TITLE
Label text  changes opacity at different zoom levels

### ISSUE THREAD

**Issue by Thebestandgreatest** [godotengine/godot#55147]
### Godot version

3.4.stable

### System information

Linux Mint 20.2 Cinnamon

### Issue description

When at 100% zoom the text on the labels in the editor was easily visible
![100percentzoom](https://user-images.githubusercontent.com/68134663/142715993-e445cf89-41ac-435b-90e2-deaf15d36a7b.png)
However when zooming out, the text opacity goes closer and closer to completely transparent

![63percentzoom](https://user-images.githubusercontent.com/68134663/142716010-35176196-0b41-43f3-8c04-c8c1cbc9953f.png)

This is an issue that I've only noticed happening recently on Linux. While using 3.4.stable on windows 10, this issue doesn't appear, but using 3.4.stable on Linux, this issue appears.

### Steps to reproduce

Open a Godot Project in version 3.4.stable on Linux
Put a label in the scene with text in it
Zoom out

**Comment by Calinou** [comment]
This is likely due to broken mipmap generation, which is a driver-specific issue. However, 2D elements do not have mipmaps enabled by default. Did you enable mipmaps on the font manually?

**Comment by Thebestandgreatest** [comment]
I did not enable mipmaps manually, and after a computer restart, the issue seems to have resolved itself.
