### ISSUE TITLE
Vulkan: ProceduralSkyMaterial and PhysicalSkyMaterial default colors are incorrect following sRGB change

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#55143]
### Godot version

4.0.dev (84f59c60b)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 470.74)

### Issue description

The ProceduralSkyMaterial default ground and sky colors are incorrect since the [Vulkan sRGB fix](https://github.com/godotengine/godot/pull/55029) was merged (I bisected this).

Also, attempting to revert the colors to their default values will result in even more saturated colors being used. This is likely due to a sRGB conversion not being performed, or being performed twice, or being performed the wrong way around.

https://user-images.githubusercontent.com/180032/142695757-f7277a48-d50a-482d-9b6c-90e0cd544c8e.mp4

This also occurs with PhysicalSkyMaterial, which has a much more blue hue compared to before:

![image](https://user-images.githubusercontent.com/180032/142695738-5b04876f-497c-4f97-a569-9c04a992fff2.png)

In 3d1c123d453e53f114d9622bdcc61e30906f828a (the commit before the sRGB change), the default appearance for the preview sky was:

![image](https://user-images.githubusercontent.com/180032/142696030-c7d536f6-7cd8-40ed-8405-80e998c3d3b0.png)

And PhysicalSkyMaterial:

![image](https://user-images.githubusercontent.com/180032/142696070-1c62f38e-d358-476e-9cea-3b0c8cac5b95.png)

### Steps to reproduce

- Create a new project.
- Notice how the preview sky has a ground that's almost fully black (it used to be brighter).
- Copy the preview environment to the scene tree by clicking the 3 vertical dots in the 3D editor's toolbar, then choose **Add Environment to Scene**.
- Edit the WorldEnvironment node's Environment resource. Open the ProceduralSkyMaterial resource and click the revert icons to reset the colors to their default values.
- Notice how colors become even more oversaturated.

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
Ah, yep I forgot that I was manually setting those colors to linear to get them to match the colors in 3.x

We just need to remove the linear conversions in sky_material.cpp.

e.g.:
https://github.com/godotengine/godot/blob/c6d2768a192eedf9a7903e8fd7b3f6ffa771db11/scene/resources/sky_material.cpp#L40
