### ISSUE TITLE
Vulkan: TileMap no longer rendering tiles for RGB8 PNG

### ISSUE THREAD

**Issue by nextrealm** [godotengine/godot#55141]
### Godot version

4.0.dev

### System information

Windows 10, Radeon RX 580 Series

### Issue description

A project created with Godot_v4.0-dev.20211027_win64.exe using PNG tiles from https://kenney.nl/assets/pixel-platformer render all of the tiles fine

When the project is opened in Godot_v4.0-dev.20211117_win64.exe PNGs showing as RGBA8 render but it seems that any showing as RGB8 dont (This is speculation, I havent investigated)

The stamp preview looks good and sprites of the bad tiles also render fine

This isnt just in editor but also the same when pressing Play

This also occurs when importing the assets into a clean project and configuring the TileSet

### Steps to reproduce

Launch Godot_v4.0-dev.20211117_win64.exe
Import tile_0021.png and tile_0022.png
Add a TileMap node
Create a new TileSet
Add the two tiles and set up the "Base Tiles"
Switch to tile drawing
Notice that the stamp preview  works as expected
Stamp the tile_0021.png tile and notice that it renders
Stamp the tile_0022.png tile and notice that it does not render

**Comment by KoBeWi** [comment]
Here's a simple tileset for testing:
![Hills](https://user-images.githubusercontent.com/2223172/149046529-a95c6848-4b98-4107-9675-8fe2462756b9.png)
It has no transparent pixels, so Godot will import it as RGB8. It displays correctly as Sprite2D, but doesn't work with TileMap. Interestingly, the editor will render the preview correctly and even display ghost tiles when drawing, but the tiles aren't actually shown in the editor, nor on the scene.
![godot4_bYjULMiB3s](https://user-images.githubusercontent.com/2223172/149046742-ccbbf6e5-6cc9-43a9-8c5d-e3d68e573e96.gif)
Adding a single transparent pixel makes the tileset render correctly.

**Comment by joaopedrosgs** [comment]
Same problem here.

**Comment by Jojox** [comment]
I think my PR fixes it. #57819
