### ISSUE TITLE
Vulkan: Default ProceduralSkyMaterial values do not match the preview sky values

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#55144]
### Godot version

4.0.dev (3d1c123d4) 

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 470.74)

### Issue description

We should aim to harmonize the default ProceduralSkyMaterial values with the preview sky's values (or the other way around).

Video recorded on 3d1c123d4 (**last commit not affected by https://github.com/godotengine/godot/issues/55143**):

https://user-images.githubusercontent.com/180032/142698132-86683a8a-859a-41a3-bb9e-f09a1c73c07f.mp4

At the beginning of the video, the preview sky's values are used, then the colors are progressively reverted to ProceduralSkyMaterial's default values.

Additionally, we should try to resolve https://github.com/godotengine/godot-proposals/issues/348 for once and all. I've found that setting the ground color to pure black generally helps create more shading in unlit areas (and less light leaking when GI is enabled), but it results in ambient lighting being too blue. To counter this, we can reduce the saturation of the sky colors.
An alternative would be to add a second **Sky Contribution** property that *only* affects areas where no GI effect is used, and default it to 0.5 (in other words, assuming that 50% of the ambient light gets to a given pixel). This could also be worthwhile for scenarios where VoxelGI is only used in specific areas of a level (because making it fit the whole level would lose too much precision).

### Steps to reproduce

- Create a new project.
- Copy the preview environment to the scene tree by clicking the 3 vertical dots in the 3D editor's toolbar, then choose **Add Environment to Scene**.
- Edit the WorldEnvironment node's Environment resource. Open the ProceduralSkyMaterial resource and click the revert icons to reset the colors to their default values.
- Notice how the sky's appearance changes noticeably as you revert each property to its default value.

### Minimal reproduction project

N/A

**Comment by tinmanjuggernaut** [comment]
The preview colors are unnatural. The ProcSky defaults is better. My recommendation has always been #36508d (https://github.com/godotengine/godot-proposals/issues/348). ProcSky default is the same hue, but different saturation and lightness. Either is better than the preview.

**Comment by Calinou** [comment]
This was fixed a while ago by https://github.com/godotengine/godot/pull/57993, closing.
