### ISSUE TITLE
Shift select ignores children on last selected node(collapsed)

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#5515]
Shift multiselect ignores the children on last selected node(collapsed)

Example:

|Root
-|Parent1
--|Child1
-|Parent2
--|Child2

1. Collapse Parent1 and Parent2
|Root
-|Parent1
-|Parent2

2. Hold shift click Parent1, click Parent2
3. Expand Parent2 and see that Child2 is not selected

**Comment by reduz** [comment]
I don't see why this is a bug...

**Comment by eska014** [comment]
All actions (duplicate, reparent, delete, move up/down) affect the children as well, so I think selecting children when selecting their parents in multiselect could make things more intuitive

**Comment by reduz** [comment]
but tree selection logic does not work this way in any UI toolkit I know

**Comment by AlexHolly** [comment]
As eska014 said it is just more intuitive.

Another example is a multiselection of folders in an OS where you move all selected folders. In this case the content of the last selected folder is not beeing moved that doesn't make sense.

(Note that "Parent1 && Parent2" are collapsed on multiselection)

**Comment by akien-mga** [comment]
Yes I also consider this a bug. See e.g.:
- My selection
![spectacle w25473](https://cloud.githubusercontent.com/assets/4701338/16708736/6f8c9fc0-45fd-11e6-8cf3-517efddc0e4e.png)
- I drag and drop between "copyright" and "welcome":
![spectacle s25499](https://cloud.githubusercontent.com/assets/4701338/16708741/968c5bc4-45fd-11e6-9c17-30976bb3a0a2.png)
- Result: all the children of "sky_foreground" got messed up and added as siblings.

**Comment by reduz** [comment]
@AlexHolly I understand, but shift-selection just does select everything in-range, and children of the last item are outside the range. I think actually that it should work the other way, that it makes more sense that it does not select items that are inside a collapsed folder at all.

@akien-mga that sounds like a separate issue

**Comment by akien-mga** [comment]
> @akien-mga that sounds like a separate issue

Right I misunderstood this issue. Opened #5613 for this bug.
