### ISSUE TITLE
Vulkan: PanoramaSkyMaterial cannot have filtering disabled on its texture anymore

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#55163]
### Godot version

4.0.dev (84f59c60b)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 470.74)

### Issue description

Now that textures no longer store filtering options, PanoramaSky no longer makes it possible to disable filtering on the texture. Disabling filtering is useful for pixel art games that need panorama skies. `filter_linear` is hardcoded here:

https://github.com/godotengine/godot/blob/4ea87f36cd23494bfbde800b436467d3d0f82b52/scene/resources/sky_material.cpp#L356

We should figure out a way to add a PanoramaSky property that can be used to toggle between `filter_nearest` and `filter_linear` (default).

Low-resolution HDRI panorama for testing (from [Poly Haven](https://polyhaven.com/a/park_parking)): [park_parking_1k.zip](https://github.com/godotengine/godot/files/7575467/park_parking_1k.zip)

### Steps to reproduce

- Add a WorldEnvironment with a PanoramaSkyMaterial.

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
I guess we just need two things:
1. a  boolean property to use nearest filtering and
2. an update function to change the shader code depending on the filtering mode that is used.

**Comment by brennengreen** [comment]
What all does adding a property include? I see how we do it for panorama
```cpp
ClassDB::bind_method(D_METHOD("set_panorama", "texture"), &PanoramaSkyMaterial::set_panorama);
ClassDB::bind_method(D_METHOD("get_panorama"), &PanoramaSkyMaterial::get_panorama);
```

Though not sure I fully understand how to translate this to a boolean property, e.g.
```cpp
ADD_PROPERTY(PropertyInfo(Variant::BOOL, "nearest filtering", PROPERTY_HINT_NONE, ""), "set_filtering", "get_filtering");
```

What's a good boolean property I can reference elsewhere in the code to base the solution off of?

**Comment by clayjohn** [comment]
@brennengreen ``environment.cpp`` has a few boolean properties you can take a look at https://github.com/godotengine/godot/blob/master/scene/resources/environment.cpp

**Comment by brennengreen** [comment]
@clayjohn Got it, based off those references looks like it'd look something along the lines of:

```cpp
class PanoramaSkyMaterial : public Material {
       ...
       private:
           bool filtering_enabled = false;
       ...
}

void PanoramaSkyMaterial::set_filtering_enabled(bool p_enabled) {
	filtering_enabled = p_enabled;
	// update shader
}

bool PanoramaSkyMaterial::is_filtering_enabled() const {
	return filtering_enabled;
}

void PanoramaSkyMaterial::_bind_methods() {
	...
	ClassDB::bind_method(D_METHOD("set_filtering_enabled", "enabled"), &PanoramaSkyMaterial::set_filtering_enabled);
	ClassDB::bind_method(D_METHOD("is_filtering_enabled"), &PanoramaSkyMaterial::is_filtering_enabled);
        ...
	ADD_PROPERTY(PropertyInfo(Variant::BOOL, "filtering_enabled"), "set_filtering_enabled", "is_filtering_enabled");
}
```

As for the second part 
> an update function to change the shader code depending on the filtering mode that is used.

Should we just determine this using `_update_shader()`? Or will we need to define a new method specifically to update the filtering

**Comment by Calinou** [comment]
> ```cpp
> ADD_PROPERTY(PropertyInfo(Variant::BOOL, "nearest filtering", PROPERTY_HINT_NONE, ""), "set_filtering", "get_filtering");
> ```

I would recommend naming the property `filter` (and be `true` by default) to be consistent with how filter properties were named in `3.x`.

**Comment by clayjohn** [comment]
> As for the second part
>
>an update function to change the shader code depending on the filtering mode that is used.
>
>Should we just determine this using _update_shader()? Or will we need to define a new method specifically to update the filtering

You can just use ``update_shader()``!

**Comment by brennengreen** [comment]
> > As for the second part
> > an update function to change the shader code depending on the filtering mode that is used.
> > Should we just determine this using _update_shader()? Or will we need to define a new method specifically to update the filtering
> 
> You can just use `update_shader()`!

I see `_update_shader()` is a static method, so would that mean we need to make `bool filtering_enabled` static as well so it can be accessed. (I think I know the answer to this just making sure to clarify) Because if that were the case, wouldn't that impact any other PanoramaSkyMaterials as well?

**Comment by brennengreen** [comment]
I have a draft of a solution in #55551 however I seem to be having trouble ensuring that `PanoramaSkyMaterial::filter` is properly changed by `PanoramaSkyMaterial::set_filtering_enabled()`

Trying to reference other examples from `BaseMaterial3D` and `PhysicalSkyMaterial` however they seem to be rather differing in each example, so not sure what to go with.

Other then that it seems to work find (e.g. the initial call to _update_shader() is properly working and setting it to the default filtering enabled property.) If you have any suggestions for how to get `set_filtering_enabled()` working properly let me know! My most up-to-date copy is on that branch.
