### ISSUE TITLE
Can't build Godot on Windows

### ISSUE THREAD

**Issue by leha-games** [godotengine/godot#55160]
### Godot version

4.0

### System information

Windows 10, Visual Studio Community 2019

### Issue description

Can't build Godot on Windows. It throws this error. 
```
[ 89%] scene\resources\animation.cpp(338): error C2440: cannot convert from "const real_t" to "Animation::HandleMode"
scene\resources\animation.cpp(338): note: Conversions between enumeration and floating point values are no longer allowed
[ 96%] Compiling ==> core\config\engine.cpp
[ 96%] engine.cpp
[ 97%] scons: *** [scene\resources\animation.windows.tools.64.obj] Error 2
scons: building terminated because of errors.
```
I've bisected this commit:
https://github.com/godotengine/godot/commit/a5d0a74b651607cbc95fc61859ab236442b73502

Building older versions is working fine for me.

### Steps to reproduce

Build the Godot on Windows 10 with Visual Studio Community 2019

**Comment by Calinou** [comment]
cc @NathanLovato 

This is a Visual Studio-only warning, so that's why it doesn't affect other compilers.

**Comment by NathanLovato** [comment]
Did you ping the wrong person by mistake? I can't help with this.

**Comment by Calinou** [comment]
> Did you ping the wrong person by mistake? I can't help with this.

Indeed, I think I meant to refer @Razoric480 instead.

**Comment by Razoric480** [comment]
Strange. Builds fine here on VS. Well, I can change them to static_cast<>.

@leha-games Can you check if the https://github.com/Razoric480/godot/tree/raz/cast-handle branch builds?

**Comment by leha-games** [comment]
> Strange. Builds fine here on VS. Well, I can change them to static_cast<>.
> @leha-games Can you check if the https://github.com/Razoric480/godot/tree/raz/cast-handle branch builds?
This branch builds successfully. 
I'm also thinking that it is strange. Nobody filled a bug yet in 4 days.

**Comment by NathanLovato** [comment]
> Sorry for the accidental ping slightly_smiling_face

No worries!

**Comment by leha-games** [comment]
@Razoric480 Yes I can confirm this branch actually builds.

**Comment by Razoric480** [comment]
> @Razoric480 Yes I can confirm this branch actually builds.

Great.
