### ISSUE TITLE
[4.0] Closing script in script list scrolls editor down

### ISSUE THREAD

**Issue by Xartorx** [godotengine/godot#55175]
### Godot version

v4.0.dev.custom_build [ed02b8af5]

### System information

Win 10 / 1080 Ti

### Issue description

Closing script in script list (with middle mouse click) scrolls script editor down.

https://user-images.githubusercontent.com/2698825/142742643-52f09356-a883-4cde-a67a-87b75c261f99.mp4

### Steps to reproduce

1. Open any script long enough
2. Open other scripts or documentation pages
3. Close them with middle mouse click

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
@Xartorx Can you reproduce this in 3.4?

**Comment by Xartorx** [comment]
@Calinou nope, only in 4.0

**Comment by Blackiris** [comment]
I was not able to reproduce this strange behaviour (using 129418962f47cc1ee6989385100dd1470960adfe). Have you tried with a different mouse? (might not be it since it works in 3.4 for you, but might be useful to know to reduce the scope)

**Comment by Paulb23** [comment]
This should be fixed by #55729
