### ISSUE TITLE
"Dim Amount/Dim Transition Time" Settings are not working

### ISSUE THREAD

**Issue by MUTEDGALAXY** [godotengine/godot#55179]
### Godot version

3.4.stable

### System information

Windows 10, RTX 2060, Core i5-9400F, GLES3

### Issue description

So apparently Dim Amount and Dim Transition Time are not working now, they were working in Godot 3.1 and looked like this:
![image](https://user-images.githubusercontent.com/53514993/142745771-1d14d68e-704a-446a-948d-864c1e24617e.png)

In Godot 3.3/3.4 this option is just broken
![image](https://user-images.githubusercontent.com/53514993/142745785-11e17a92-3ba8-4de3-8b8b-a77c219c01d6.png)

No matter what the value is, dim is still the same and appears instantly.

### Steps to reproduce

Change Dim Amount or Dim Transition Time at engine interface settings

**Comment by Calinou** [comment]
Those settings were removed as they were rarely used. (The global toggle for dimming remains available.)

The settings still appear in your own editor because your `editor_settings-3.tres` file still contains them, but they aren't used anymore. See https://github.com/godotengine/godot/issues/22099.
