### ISSUE TITLE
Can't create enum by use some keywords

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#55182]
### Godot version

v4.0.dev.calinou [ed02b8af5]

### System information

Windows 10

### Issue description

![捕获](https://user-images.githubusercontent.com/35988767/142753496-cf4710b6-e4b3-46ca-87e4-3c5454ef9e47.PNG)

### Steps to reproduce

Just code like above.
IMO, It will use this enum like this:
```
var my_dir = MyDirection.Input
```
So it will should be ok

**Comment by Chaosus** [comment]
This is "intended" and has been accepted by @vnen in https://github.com/godotengine/godot/pull/54676. However, if the majority of users would not like it - I have a fix to replace the error to warning - https://github.com/godotengine/godot/pull/54949

**Comment by CsloudX** [comment]
@Chaosus, Thanks.
Yes, I think it should just warning

**Comment by Chaosus** [comment]
Fixed by https://github.com/godotengine/godot/pull/54949
