### ISSUE TITLE
The tile selection arrows do not respect the area assigned to the selected atlas.

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#55187]
### Godot version

3.4 stable mono

### System information

w10 64

### Issue description

I am navigating between the tiles of an atlas using the selection arrows but this mode does not respect the area assigned to the atlas and it always goes one more tile to the right, that area does not belong to the area assigned to the atlas.

That is, I think the arrows should navigate the boundaries of the currently selected atlas.
In the gif you can see that this is not the case, and for some reason one tile is exceeded to the right.

![Animation](https://user-images.githubusercontent.com/19652075/142759777-45b5aa14-cfd7-4b08-8d16-6ea13b7fa45f.gif)

### Steps to reproduce

See the gif

### Minimal reproduction project

...

**Comment by timothyqiu** [comment]
I find reverting #42313 solves this issue.

It's strange that the PR above is trying to resolve an exactly opposite issue (#42290) compared to this one, and I could not reproduce that issue in 3.2.3 on Arch Linux.
