### ISSUE TITLE
In 3.4, move_and_slide will not return the value of *delta

### ISSUE THREAD

**Issue by LoserFox** [godotengine/godot#55185]
### Godot version

 v3.4.stable.official.206ba70f4

### System information

Windows10

### Issue description

In 3.4, move_and_slide will not return the value of *delta
In the past version, the return value of move_and_slide is always a value of *delta, but in 3.4, the value of *delta will not be returned, and the related documents and api have not been updated. Why?

### Steps to reproduce

old:
move_and_slide(veclocity)
new:
move_and_slide(veclocity)

**Comment by Torguen** [comment]
I think it's the same as:
https://github.com/godotengine/godot/issues/55168
