### ISSUE TITLE
body_enter Ignores New CollisionShapes

### ISSUE THREAD

**Issue by Gastronok** [godotengine/godot#5518]
**Operating system or device - Godot version:**
Windows 7, x64. Godot 2.0.3 Stable.

**Issue description** (what happened, and what was expected):
I have some Area2Ds which I wish to vary in size. I wanted to use multiple instances of the same object and either create their Shape2Ds programmatically or in the editor. CollisionShape2Ds I add to an instance in the editor are recognized in _ready(), but the body_enter signal is not called for them.

**Steps to reproduce:**
Create an Area2D with no CollisionShape2D and save it as a scene. Create a script for it with
```
func _ready():
	connect("body_enter", self, "on_body_enter")

func on_body_enter(body):
	print(str(get_name()), " saw a body enter.")
```
Add an instance of that scene to a different scene and give it a CollisionShape2D in the editor. Bodies entering this object won't be reported.

If you create a different scene which does have a CollisionShape2D directly in it and give it the same script it will report objects as expected.

**Link to minimal example project** (optional but very welcome):
[Example.zip](https://github.com/godotengine/godot/files/344438/Example.zip)

**Comment by vnen** [comment]
With the current system there's no way this can work. CollisionShapes are just editor helpers and does not exist in runtime. You need to use `add_shape()`, `set_shape()` and related methods from `CollisionObject2D` to dynamically interact with collision shapes.

This will be fixed in 3.0 when the physics system will be reviewed, which will break compatibility.

**Comment by Gastronok** [comment]
I originally tried using add_shape() via code and encountered the same issue, and additionally the shapes weren't displayed at runtime when Visible Collision Shapes was enabled.

I'll update the example to reflect that form of bad behavior as soon as I get the chance.

**Comment by TheoXD** [comment]
@vnen, wasn't there a change long time ago that finally allows manipulating CollisionShape nodes, by keeping them in the tree?

**Comment by vnen** [comment]
@TheoXD they're kept in the tree on debug to show the collision shapes, but they don't affect collision anymore (which is why shapes added via code don't show even if Visible Collision Shapes is enabled, see #4449, #4260).

**Comment by Gastronok** [comment]
Here's another example. This time the shape is added via `add_shape`, but it still doesn't register a `body_enter`. Presumably this is supposed to be possible otherwise I'm not sure how one would do dynamic shapes at all.

[Example2.zip](https://github.com/godotengine/godot/files/344744/Example2.zip)

**Comment by vnen** [comment]
Your code is wrong, even the debugger shows two errors. I told you to use `add_shape()` but you used `add_child()`. You can't use `add_child()` because a  `CircleShape2D` is not a node. Even if you add a `CollisionShape2D` as a child it won't work, since those are only editor helpers and make no difference in runtime.

Here's a corrected code from your second example:

```GDScript
func _ready():
	# Create a CollisionShape2D if one doesn't exist.
	if not has_node("CollisionShape2D"):
		var shape = CircleShape2D.new()
		shape.set_name("CollisionShape2D")
		shape.set_radius(64)
		add_shape(shape)
		print(get_name(), " has a ", shape.get_type())
	else:
		print(get_name(), " has a ", str(get_node("CollisionShape2D").get_shape().get_type()))
	connect("body_enter", self, "on_body_enter")

func on_body_enter(body):
	print(str(get_name()), " saw a body enter.")
```

**Comment by Gastronok** [comment]
Aah, apologies! In my mind I was typing `add_shape` when instead I typed `add_child` (both this time and last night).

Sounds like this is a side-effect of something that is on-track for 3.0, so I'll close this issue.

Thanks for the attention.
