### ISSUE TITLE
Prettier print for arrays

### ISSUE THREAD

**Issue by alketii** [godotengine/godot#5519]
If you have
var a = [[1,2,3],[1,2,3],[1,2,3]]
print(a)

it will print as 1, 2, 3, 1, ,2 ,3 ,1 ,2 ,3
instead of [1,2,3],[1,2,3],[1,2,3]

**Comment by neikeq** [comment]
I am not sure if you proposal is possible, since every Variant has to be converted to string. So my PR achieves `[[1, 2, 3], [1, 2, 3], [1, 2, 3]]` instead of `[1, 2, 3], [1, 2, 3], [1, 2, 3]`.

**Comment by reduz** [comment]
you can use print(var2str(value)) to get nicer gdscript friendly values

**Comment by neikeq** [comment]
@reduz still the str() result is pretty confusing. In the example above it looks more like a single array with 9 integers.

**Comment by reduz** [comment]
maybe we should fix this in Variant::operator String() directly and make
arrays more nice to look at

**Comment by alketii** [comment]
@neikeq yes, thats how it should print, I just forgot the [].
I will test PR once I know how to do it :p
