### ISSUE TITLE
Deleted Objects return True

### ISSUE THREAD

**Issue by Adrenesis** [godotengine/godot#55204]
### Godot version

3.4-stable

### System information

Windows 10 x64

### Issue description

When an object is deleted `not my_object` returns false.

Here is a sample of my minimal reproduction project with multiple versions of Godot

```
godot 3.2.3:
new_node:
[Deleted Object]
not new_node:
True
new_node is Node:
False

Godot 3.3.4:
new_node:
[Deleted Object]
not new_node:
False
new_node is Node:
False

Godot 3.4:
new_node:
[Deleted Object]
not new_node:
False
new_node is Node:
```
Game actually crashed on 3.4 and tells `left operand of "is" was already freed` (probably not a bug, but it adds a blocking crash while it could be a valid test in my opinion)

### Steps to reproduce

Create a node.
queue_free() that node
test `not my_object`

or press F5 on the minimal reproduction project

### Minimal reproduction project

[delected-object-is-true.zip](https://github.com/godotengine/godot/files/7576648/delected-object-is-true.zip)

**Comment by pycbouh** [comment]
You can't check for freed objects using just a boolean negation. You need to use [is_instance_valid()](https://docs.godotengine.org/en/stable/classes/class_%40gdscript.html#class-gdscript-method-is-instance-valid) to make sure that the object you are trying to reference is valid or not. This is explained in the documentation for [Node.queue_free()](https://docs.godotengine.org/en/stable/classes/class_node.html#class-node-method-queue-free) and [Object.free()](https://docs.godotengine.org/en/stable/classes/class_object.html#class-object-method-free).

**Comment by Adrenesis** [comment]
What is the rationale behind that behaviour change? 
What is the purpose keeping a reference to an unused pointer in a high level language? 
What is the warranty that a deleted object is not valid? (because technically it's not invalid, it's just deleted)
Why getting away from other languages that consider that deleted object evaluate to `false`?

This invalidates not only tons of code written for Godot, it also invalidates tons of assumptions for devs coming to Godot... I'm not managing pointers in GDScript, because GDScript doesn't even know the concept of pointer, it is a high-level language, a GDScript dev should not have to worry about this.

This makes the boolean casting of Godot's objects useless and move the problem to an already sketchy function name, preparing the field for another useless API break.

**Comment by pycbouh** [comment]
To be clear, this method has been around for some time (at least since 3.2, but possibly since 3.1), because this problem is not new. And while you don't work with pointers directly in GDScript, you do work with reference types as well as value types, so an invalid reference is not a far-fetched idea. But I personally cannot comment further on the matter.

**Comment by KoBeWi** [comment]
This was done, because information about freed Objects was lost in release builds for optimization reasons (your old code is probably crashing randomly when exported without debug). The freed objects used to be "null", but only in debug builds, which resulted in different behavior between debug and release. See #45639

**Comment by Adrenesis** [comment]
So, if I understand this well, instead of making Godot consistent with itself and other languages by making boolean casting being a mirror of  ìs_instance_valid()` (which should be named ìs_instance_deleted()`) like it is in most language, Godot was made consistent to not be consistent with other languages...

From my point of view, this is a really weird choice, and this should not be the definitive behaviour of Godot. It doesn't bring any feature to evaluate a deleted object to `true` while it is very confusing for new comers.

I can certainly deal with it as Godot is still my favorite engine but this is still a hard concept to grasp from a high-level point of view.

If Godot understands that it is a deleted object, why evaluating its boolean casting to `True`? what is the actual cost of doing evaluating it to `False`?
