### ISSUE TITLE
Visual Studio Code cannot run programs from within VSCode starting with version 1.62

### ISSUE THREAD

**Issue by blackears** [godotengine/godot#55205]
### Godot version

3.4 stable

### System information

Windows 10

### Issue description

Visual Studio Code recently released version 1.62.  Unfortunately, with this version it is no longer possible to run or debug your projects from within Visual Studio Code.  I had to downgrade to version 1.61 to be able to debug again.

https://godotforums.org/discussion/comment/56303#Comment_56303

### Steps to reproduce

Create a simple scene in Godot and attach a c# script to it.  Open the script in VSCode 1.62 or higher.  Try to run the game from within VSCode.  The process will hang without launching the game.

**Comment by cybereality** [comment]
The same issue also happens on Windows 11, I tried everything and it does not appear to be compatible any longer.

**Comment by Calinou** [comment]
I wonder if this is due to the same cause as https://github.com/godotengine/godot/issues/54076.

**Comment by blackears** [comment]
Where would I find the patch they're talking about, and how would I apply it?

**Comment by raulsntos** [comment]
Version 0.2.1 of the [extension](https://marketplace.visualstudio.com/items?itemName=neikeq.godot-csharp-vscode) has been released with the patch applied.

**Comment by cybereality** [comment]
It works perfectly now! Play in editor and debugging seems fully supported. Thanks for your hard work.

**Comment by Calinou** [comment]
Closing as resolved in the extension. Make sure to update it to the latest version if you still run into this issue locally.

**Comment by boruok** [comment]
looks like downgrading also works for **godot-tools** extenstion, see [how to downgrade](https://newbedev.com/how-to-downgrade-vscode)
