### ISSUE TITLE
Print an error when exporting to iOS with icons that don't match their required size

### ISSUE THREAD

**Issue by Tekuzo** [godotengine/godot#55229]
### Godot version

3.4 Stable 

### System information

M1 Macbook Air

### Issue description

When trying to export an iOS project, the export will fail if the Spotlight Icons are provided in the Optional Icons section of the export options.
An error message will state that the export failed due to a configuration error in the preset.

Exporting works normally if the spotlight icons are removed from the export.
The export still works with the 180 X 180, 152 X 152, 167 X 167 optional icons.

### Steps to reproduce

Export an iOS project and provide the spotlight icons.

### Minimal reproduction project

[Project 3.zip](https://github.com/godotengine/godot/files/7581826/Project.3.zip)

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by Calinou** [comment]
Reopening, as this is something we should detect and print a proper error message about when exporting.

**Comment by bruvzg** [comment]
> as this is something we should detect and print a proper error message about when exporting.

It is printing `Invalid icon size ....` error in the log, but we should do something with the error popup, which only displays a message based on the returned error code (and it's almost always `ERR_UNCONFIGURED`).
