### ISSUE TITLE
Material shader parameters shuffled around when saving scene

### ISSUE THREAD

**Issue by and-rad** [godotengine/godot#55240]
### Godot version

v4.0.dev.custom_build [70d530029]

### System information

Windows 10, Vulkan, RTX 2060

### Issue description

Saving a scene reorders the list of used shader parameters in any shader material file that is used on meshes in the scene. This leads to a considerable amount of diff noise if the project is tracked by version control. While not impacting functionality of the project directly (it still behaves correctly), it is inconvenient to check every affected material for false positives when committing changes.

### Steps to reproduce

- start out with a project created from the project manager
- create a shader that uses several `uniform`s
- create a shader material file that uses the shader
- create a scene, add a mesh instance, assign a plane mesh to the instance, and assign the material to the mesh
- change some of the exposed shader parameters, save the scene, and quit Godot
- open the material.tres file in a text editor, note the order of the `shader_param` entries
- open the project again, open the scene, add any node to the scene, and save the scene
- close Godot, open the material file again, note how the order is different than it was before

Here are example outputs after doing this a couple of times. Note how the order is different every time. This appears to be random.
```
[resource]
render_priority = 0
shader = ExtResource( "1_1wfqf" )
shader_param/third_var = Vector3(3, 2, 1)
shader_param/fourth_var = 4.0
shader_param/first_var = 1.0
shader_param/second_var = 2.0

[resource]
render_priority = 0
shader = ExtResource( "1_1wfqf" )
shader_param/third_var = Vector3(1, 0.4, 0)
shader_param/first_var = 1.0
shader_param/second_var = 2.0
shader_param/fourth_var = 0.0

[resource]
render_priority = 0
shader = ExtResource( "1_1wfqf" )
shader_param/fourth_var = 0.0
shader_param/third_var = Vector3(1, 0.4, 0)
shader_param/first_var = 1.0
shader_param/second_var = 2.0
```

### Minimal reproduction project

[ShaderDiffNoise.zip](https://github.com/godotengine/godot/files/7584239/ShaderDiffNoise.zip)

**Comment by akien-mga** [comment]
There could likely be a `.sort()` call somewhere to ensure that they're sorted alphabetically before serializing.

**Comment by and-rad** [comment]
I thought so too. The question is, should a pull request for this solve just this one issue or should we look for other types of resources that might be affected similarly and fix those too?

**Comment by akien-mga** [comment]
If you find other resources with similar issues then that could point at something that needs to be fixed at a lower level indeed. But I haven't seen this issue myself so it might well be specific to material shader params, in which case a local fix should be sufficient.

**Comment by and-rad** [comment]
Here is what I found so far: Serialization is done by classes that inherit from `ResourceFormatSaver`. There are a couple of them, each responsible for different resource types. Materials are `.tres` files, so they are handled by the `ResourceFormatSaverText` class, which handles basically everything that is not covered by more specialized resource savers.

It is indeed possible to sort the list of properties before they're written to disk, but I don't think it's the right thing to do here. Mostly because this would extend to any other resource that is handled by this saver and might cause all kinds of side effects down the road. On top of that, I haven't noticed the issue in any of these other resource types yet.

The root cause seems to be specific to materials and should probably be fixed there. Opening and closing the editor a bunch of times, you'll notice that in the inspector, the order of parameters in shader materials is different every time.

**Comment by akien-mga** [comment]
> The root cause seems to be specific to materials and should probably be fixed there. Opening and closing the editor a bunch of times, you'll notice that in the inspector, the order of parameters in shader materials is different every time.

Indeed, that's the bug that needs to be fixed then. The order of shader material parameters need to be consistent *in the editor*, so that it's saved in a consistent way when serializing.

**Comment by and-rad** [comment]
I tracked it down, but I don't know what the best course of action is.

Here is what's happening: When files are serialized, there's a call to `Object::get_property_list`. For a material, this gets passed along to `Shader::get_param_list` all the way to `SceneShaderForwardClustered::ShaderData::get_param_list`. This iterates over a shader's uniforms and returns the list. A shader uniform stores its position in an `order` field. This determines the order of shader parameters in the inspector as well as the serialized file. The uniform order is set when the shader is parsed for the first time everytime the editor is started. The relevant code is in `ShaderLanguage::_parse_shader`, which is a massive, 1500-LOC function.

There are two reasons why the order of shader parameters is **(1)** random and **(2)** not the same as the order defined in the shader source file:
1. The uniforms are stored in a map, so the order of iteration is not guaranteed to be the same for successive iterations.
2. Array uniforms are ordered before everything else, regardless of their position in the source file. This is deliberate, as indicated by the code comments:

```
// Need to push arrays to first place in a uniform buffer in order to correct work.
for (Map<StringName, ShaderNode::Uniform>::Element *E = shader->uniforms.front(); E; E = E->next()) {
	if (E->get().texture_order == -1 && E->get().scope != ShaderNode::Uniform::SCOPE_INSTANCE && E->get().array_size > 0) {
		E->get().order = uniforms++;
	}
}
for (Map<StringName, ShaderNode::Uniform>::Element *E = shader->uniforms.front(); E; E = E->next()) {
	if (E->get().texture_order == -1 && E->get().scope != ShaderNode::Uniform::SCOPE_INSTANCE && E->get().array_size == 0) {
		E->get().order = uniforms++;
	}
}
```
This right here is essentially what's messing up shader parameter order every time it's run.

There is a way to set the order earlier in the function in a way that preserves the order from the shader file. But I'd need guidance on possible side efects. Also, *why* is it important to put array uniforms first? What would break if we didn't? I've been working with Godot for two weeks, so I'm in no position to judge that.

Who are the right people to ping to get clarification on those points?

**Comment by and-rad** [comment]
I  found the PR that introduced the changes that are causing the current behavior: #54736

The way I see it, the best course of action would be to go back to the original issue (#54657) that was addressed by that PR, to fix the bug "properly" (sorry for the wording, couldn't think of a better word), and then to revert that PR and close this issue, which will be moot by that point.

@akien-mga @Chaosus @clayjohn any insight on this?

**Comment by Chaosus** [comment]
Ah, I think it's because uniforms are saved in Map which is a container with undefined order. The correct fix would be to save and iterate it using a List.

**Comment by Chaosus** [comment]
Or instead reverting we could place a Vector instead of Map + modify `SceneShaderForwardClustered::ShaderData::get_param_list` to force uniform arrays placed first.

**Comment by and-rad** [comment]
That has repercussions, though. The `uniforms` map is accessed by key a bunch of times throughout the codebase. It's a public member, so we'd have to track down every instance where that happens. We'd also lose the ability to access an individual uniform in O(1) time, which might not be too bad, but it's worth keeping in mind.
