### ISSUE TITLE
Input.is_key_pressed does not work with physical_scancode.

### ISSUE THREAD

**Issue by jitspoe** [godotengine/godot#55244]
### Godot version

3.4

### System information

Windows 10

### Issue description

Due to some other input issues, I've been using Input.is_key_pressed() to check for input, but this doesn't work with the physical scancodes.  I need a way to convert physical scancodes to scancodes or a separate is_physical_key_pressed() function.

This is related to this proposal here, though it's a bit more critical, as my game can't currently function with physical scancodes without it: https://github.com/godotengine/godot-proposals/issues/3571

### Steps to reproduce

Change your keyboard layout to something non-QWERTY.  Call Input.is_key_pressed(<physical scan code of key that's different from QWERTY key>) while the key is pressed and note that the result is false.

**Comment by Calinou** [comment]
cc @bruvzg
