### ISSUE TITLE
Variable & Signal nodes are not renamed in VisualScript Editor

### ISSUE THREAD

**Issue by theoway** [godotengine/godot#55265]
### Godot version

3.x & master

### System information

Any

### Issue description

In **Visualscript editor**, `function` nodes are renamed right away after their name has been changed, but this does not happen with variable and singal nodes. This can make it difficult to debug the script, also difficult to refactor if any variable/signal node has been renamed.
_(See, `function` nodes are renamed correctly)_
![(_) Node2D tscn - TestGodot - Godot Engine 2021-11-23 21-36-02_Trim](https://user-images.githubusercontent.com/41969735/143061055-5d8d1ae4-d096-4d8b-ad81-042b8237cb59.gif)

### Steps to reproduce

1. Create any project, add a node and attach a visual script to it.
2. In the visual script, add a variable and add a getter/setter node of that variable.
3. Rename it through the panel
4. The name is changed in the side panel, but the name in the node is still the old one.
5. This is same for signal nodes.

**Comment by theoway** [comment]
I've made a patch, will submit the PR soon enough.

**Comment by fire** [comment]
Fixed by: https://github.com/godotengine/godot/pull/55291
