### ISSUE TITLE
XMLParser EOFs early with valid HTML file

### ISSUE THREAD

**Issue by EIREXE** [godotengine/godot#55279]
### Godot version

3.x (4d3690eba50fdc8c7c12462a56b622a3080cee1e)

### System information

Arch Linux

### Issue description

XMLParser seems to fail to parse a certain HTML page I found online.
It seems to return EOF at position 12456 which corresponds to an iframe and misses any tags afterwards entirely, I don't think this is correct behavior, unless there's something I missed.

### Steps to reproduce

Grab the attached MRP and run Control.tscn

### Minimal reproduction project

[XMLBug.zip](https://github.com/godotengine/godot/files/7592382/XMLBug.zip)

**Comment by pycbouh** [comment]
HTML is not a subset of XML, a valid HTML document is unlikely to be a valid XML document. If it follows XHTML, then _maybe_, but it's still not a guarantee. So I don't think that there can be any expectation that our parser would work for a random HTML document.

**Comment by timothyqiu** [comment]
The said `iframe` tag is invalid in XML:

```xml
<iframe width="640" height="360" src="https://www.youtube.com/embed/Zr_q5-UsH-Y?feature=player_detailpage" frameborder="0" allowfullscreen>
```

Notice the `allowfullscreen` attribute does not have its value specified. This is allowed in HTML but forbidden in XML. Changing it to `allowfullscreen="allowfullscreen"` can make the `XMLParser` parse the whole HTML file successfully.

Anyway, the point is, HTML and XML are two different formats.

**Comment by pycbouh** [comment]
Closing per @timothyqiu comment

**Comment by EIREXE** [comment]
> The said `iframe` tag is invalid in XML:
> 
> ```
> <iframe width="640" height="360" src="https://www.youtube.com/embed/Zr_q5-UsH-Y?feature=player_detailpage" frameborder="0" allowfullscreen>
> ```
> 
> Notice the `allowfullscreen` attribute does not have its value specified. This is allowed in HTML but forbidden in XML. Changing it to `allowfullscreen="allowfullscreen"` can make the `XMLParser` parse the whole HTML file successfully.
> 
> Anyway, the point is, HTML and XML are two different formats.

I see, thanks for the info
