### ISSUE TITLE
Changes to support publishing XR games on Android/Quest

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#55274]
### Godot version

3.4.stable

### System information

Android

### Issue description

Publishing XR games to App Lab has shown a few issues with minimum requirements. A few small changes are needed to the Android export to support these.

1) the minimum SDK needs to be higher then it's currently set. We likely don't want to raise this as for other game types this would exclude older model phones as a target but making this setting configurable in the export would be a good fix. 

2) the property `android:excludeFromRecents` in the manifest file needs to be true. Again does not apply to all games so this would be nice to have as a setting in the export to control this value

3) probably to be tied to the hand tracking export setting we already have, we need to be able to set the `com.oculus.handtracking.frequency` meta data entry i.e.:
```
<!-- 60hz handtracking mode -->
<meta-data android:name="com.oculus.handtracking.frequency" android:value="HIGH"/>
```

### Steps to reproduce

Publish a game on App Lab or Oculus Store :)

**Comment by m4gr3d** [comment]
Fixed by the PRs referenced above.
