### ISSUE TITLE
Executing custom build with `--headless` flag throws error

### ISSUE THREAD

**Issue by carl-marqs** [godotengine/godot#55278]
### Godot version

v4.0.dev (5efe80f30)

### System information

Arch Linux, Vulkan

### Issue description

Executing a custom build using `--headless`flag throws this error:

```
> godot.linuxbsd.opt.tools.64 --headless -e -q
Godot Engine v4.0.dev.custom_build.5efe80f30 - https://godotengine.org
ERROR: Changing the VSync mode is not supported by this display server.
   at: window_get_vsync_mode (servers/display_server.cpp:332)
ERROR: Sub-windows not supported by this display server.
   at: create_sub_window (servers/display_server.cpp:196)
ERROR: Condition "window_id == DisplayServer::INVALID_WINDOW_ID" is true.
   at: _make_window (scene/main/window.cpp:233)
```

Some context: I was using docker (`FROM archlinux:latest`) and got stuck trying to initialize Godot so it creates editor_settings-3.tres file.

### Steps to reproduce

1. `git clone https://github.com/godotengine/godot.git && cd godot`
2. `scons use_lto=yes tools=yes target=release_debug && cd bin`
3. `godot.linuxbsd.opt.tools.64 --headless -e -q`

**Comment by akien-mga** [comment]
It doesn't throw errors for me (albeit on a `target=debug` and no LTO build) when running in a terminal under KDE Plasma on X11. It also doesn't show any window as expected, but it might well be that it still calls some window-related code that errors when the display server is _actually_ headless.
