### ISSUE TITLE
Opening the editor causes additional icons to linger in the macOS Dock

### ISSUE THREAD

**Issue by sspocketgalaxy** [godotengine/godot#55273]
### Godot version

3.4 stable

### System information

Mac OS 12.0.1, 2021 M1 iMac / 2017 i7 MBP

### Issue description

When I launch Godot from my Applications folder, a Godot App Icon shows up in the dock on the right side of the dock.  After booting up it shows the project manager.  If I drag the Godot App icon to my dock to keep it in the dock, after selecting a project from the project manager, Godot launches another application and closes the App Icon which opened the project manager UI.. If I drag the newly created App Icon that opens with my project to the dock (so now I have two Godot icons in my dock side by side) and quit Godot, and then open Godot using the 2nd icon, Godot again opens the Project manager but instead of using the App Icon I clicked on it uses the first icon and shows it as being active..Opening the project again causes Godot to launch a 3rd Dock icon and closes out the app icon that opened the project manager and this can continue forever (I tried up to 8 icons so that's sort of anecdotal).    I've tried resinstalling and trashing the ~/Library/Application/Support/Godot folder to no effect. 

Attached is a reference video of my dock

https://user-images.githubusercontent.com/51650480/143133310-d86dc506-1111-4ff6-bf8c-47bf6b583880.mov

### Steps to reproduce

1. Launch Godot
2. Select project from project manager and click Edit
3. Move the Godot App Icon to the dock to keep it available
4. Quit Godot and start over 

### Minimal reproduction project

This happens with any project including the demos from the Godot site.

**Comment by Calinou** [comment]
This should logically have been resolved in 3.4 by https://github.com/godotengine/godot/pull/48686. cc @bruvzg

**Comment by bruvzg** [comment]
It's not fixable, at least with the current design of the editor. Project manager and editor are running as different app instances, and macOS dock always show a separate icon for each instance.

**Comment by Calinou** [comment]
> It's not fixable, at least with the current design of the editor. Project manager and editor are running as different app instances, and macOS dock always show a separate icon for each instance.

Shouldn't we only have 2 dock icons in this case (one for the project manager, one for the editor)?

**Comment by bruvzg** [comment]
> Shouldn't we only have 2 dock icons in this case (one for the project manager, one for the editor)?

If you do not try to drag it, there should be two. But when you drag it, dock can create more, macOS is not designed to have multiple instances of the app running.

**Comment by Calinou** [comment]
Closing, as this isn't something we can resolve on our end.

**Comment by sspocketgalaxy** [comment]
Thank you for the intel.  I'll just only save the dock icon for the project manager and ignore the extra app icons that launch when a project is launched.

**Comment by cuppajoeman** [comment]
Until this is fixed, I found that the solution to this question made the icons go away after closing: https://apple.stackexchange.com/questions/339426/stop-app-from-showing-multiple-icons-in-dock?newreg=6ed878a8947245f2a9450250616b9c51

Note I open godot projects by clicking on the project.godot file.
