### ISSUE TITLE
win11 godot3.4 mono version start crash

### ISSUE THREAD

**Issue by aslyr** [godotengine/godot#55285]
### Godot version

3.4 Mono stable version and 3.3.4 Mono stable version

### System information

Win11

### Issue description

Config attempting to parse: 'D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/etc\mono\config'. (in domain Mono, info)
Image addref mscorlib[0000000015397340] (asmctx DEFAULT) -> D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5/mscorlib.dll[000000001556dd10]: 2 (in domain Mono, info)
Prepared to set up assembly 'mscorlib' (D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5/mscorlib.dll) (in domain Mono, info)
AOT: image 'D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5/mscorlib.dll.dll' not found: ￧ﾳﾻ￧ﾻﾟ￦ﾉﾾ￤ﾸﾍ￥ﾈﾰ￦ﾌﾇ￥ﾮﾚ￧ﾚﾄ￦ﾖﾇ￤ﾻﾶ￣ﾀﾂ
 (in domain Mono, info)
AOT: image 'D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/aot-cache/amd64/mscorlib.dll.dll' not found: ￧ﾳﾻ￧ﾻﾟ￦ﾉﾾ￤ﾸﾍ￥ﾈﾰ￦ﾌﾇ￥ﾮﾚ￧ﾚﾄ￨ﾷﾯ￥ﾾﾄ￣ﾀﾂ
 (in domain Mono, info)
Assembly mscorlib[0000000015397340] added to domain GodotEngine.RootDomain, ref_count=1 (in domain Mono, info)
Assembly mscorlib[0000000015397340] added to domain GodotEngine.Domain.Scripts, ref_count=2 (in domain Mono, info)
Image addref GodotSharp[0000000015397fa0] (asmctx DEFAULT) -> D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Api/Debug/GodotSharp.dll[00000000155ea590]: 2 (in domain Mono, info)
Prepared to set up assembly 'GodotSharp' (D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Api/Debug/GodotSharp.dll) (in domain Mono, info)
Assembly GodotSharp[0000000015397fa0] added to domain GodotEngine.Domain.Scripts, ref_count=1 (in domain Mono, info)
Requesting loading reference 0 (of 1) of D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Api/Debug/GodotSharp.dll (in domain Mono, info)
Loading reference 0 of D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Api/Debug/GodotSharp.dll asmctx DEFAULT, looking for netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 (in domain Mono, info)
Config attempting to parse: ''. (in domain Mono, info)
Image addref netstandard[0000000015398030] (asmctx DEFAULT) -> D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5/Facades/netstandard.dll[0000000015663050]: 2 (in domain Mono, info)
Prepared to set up assembly 'netstandard' (D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5/Facades/netstandard.dll) (in domain Mono, info)
Assembly netstandard[0000000015398030] added to domain GodotEngine.Domain.Scripts, ref_count=1 (in domain Mono, info)
Assembly Ref addref GodotSharp[0000000015397fa0] -> netstandard[0000000015398030]: 2 (in domain Mono, info)
Requesting loading reference 0 (of 16) of D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5/Facades/netstandard.dll (in domain Mono, info)
Loading reference 0 of D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5/Facades/netstandard.dll asmctx DEFAULT, looking for mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (in domain Mono, info)
Assembly Ref addref netstandard[0000000015398030] -> mscorlib[0000000015397340]: 3 (in domain Mono, info)
Image addref GodotSharpEditor[00000000153981e0] (asmctx DEFAULT) -> D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Api/Debug/GodotSharpEditor.dll[000000001569b2b0]: 2 (in domain Mono, info)
Prepared to set up assembly 'GodotSharpEditor' (D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Api/Debug/GodotSharpEditor.dll) (in domain Mono, info)
Assembly GodotSharpEditor[00000000153981e0] added to domain GodotEngine.Domain.Scripts, ref_count=1 (in domain Mono, info)
Requesting loading reference 0 (of 2) of D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Api/Debug/GodotSharpEditor.dll (in domain Mono, info)
Loading reference 0 of D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Api/Debug/GodotSharpEditor.dll asmctx DEFAULT, looking for netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 (in domain Mono, info)
Assembly Ref addref GodotSharpEditor[00000000153981e0] -> netstandard[0000000015398030]: 3 (in domain Mono, info)
Requesting loading reference 2 (of 16) of D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5/Facades/netstandard.dll (in domain Mono, info)
Loading reference 2 of D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5/Facades/netstandard.dll asmctx DEFAULT, looking for System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (in domain Mono, info)
Image addref System[00000000153984b0] (asmctx DEFAULT) -> D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5/System.dll[00000000156e3010]: 2 (in domain Mono, info)
Prepared to set up assembly 'System' (D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5/System.dll) (in domain Mono, info)
Assembly System[00000000153984b0] added to domain GodotEngine.Domain.Scripts, ref_count=1 (in domain Mono, info)
Assembly Ref addref netstandard[0000000015398030] -> System[00000000153984b0]: 2 (in domain Mono, info)
Requesting loading reference 0 (of 6) of D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5/System.dll (in domain Mono, info)
Loading reference 0 of D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5/System.dll asmctx DEFAULT, looking for mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (in domain Mono, info)
Assembly Ref addref System[00000000153984b0] -> mscorlib[0000000015397340]: 4 (in domain Mono, info)
Requesting loading reference 2 (of 6) of D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5/System.dll (in domain Mono, info)
Loading reference 2 of D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5/System.dll asmctx DEFAULT, looking for System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (in domain Mono, info)
Image addref System.Configuration[0000000015399500] (asmctx DEFAULT) -> D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5/System.Configuration.dll[00000000155e8570]: 2 (in domain Mono, info)
Prepared to set up assembly 'System.Configuration' (D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5/System.Configuration.dll) (in domain Mono, info)
Assembly System.Configuration[0000000015399500] added to domain GodotEngine.Domain.Scripts, ref_count=1 (in domain Mono, info)
Assembly Ref addref System[00000000153984b0] -> System.Configuration[0000000015399500]: 2 (in domain Mono, info)
Requesting loading reference 0 (of 4) of D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5/System.Configuration.dll (in domain Mono, info)
Loading reference 0 of D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5/System.Configuration.dll asmctx DEFAULT, looking for mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (in domain Mono, info)
Assembly Ref addref System.Configuration[0000000015399500] -> mscorlib[0000000015397340]: 5 (in domain Mono, info)
Requesting loading reference 2 (of 4) of D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5/System.Configuration.dll (in domain Mono, info)
Loading reference 2 of D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5/System.Configuration.dll asmctx DEFAULT, looking for System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (in domain Mono, info)
Assembly Ref addref System.Configuration[0000000015399500] -> System[00000000153984b0]: 3 (in domain Mono, info)
Requesting loading reference 1 (of 4) of D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5/System.Configuration.dll (in domain Mono, info)
Loading reference 1 of D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5/System.Configuration.dll asmctx DEFAULT, looking for System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (in domain Mono, info)
Image addref System.Xml[0000000015399230] (asmctx DEFAULT) -> D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5/System.Xml.dll[000000001564c490]: 2 (in domain Mono, info)
Prepared to set up assembly 'System.Xml' (D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5/System.Xml.dll) (in domain Mono, info)
Assembly System.Xml[0000000015399230] added to domain GodotEngine.Domain.Scripts, ref_count=1 (in domain Mono, info)
Assembly Ref addref System.Configuration[0000000015399500] -> System.Xml[0000000015399230]: 2 (in domain Mono, info)
Requesting loading reference 0 (of 3) of D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5/System.Xml.dll (in domain Mono, info)
Loading reference 0 of D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5/System.Xml.dll asmctx DEFAULT, looking for mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (in domain Mono, info)
Assembly Ref addref System.Xml[0000000015399230] -> mscorlib[0000000015397340]: 6 (in domain Mono, info)
DllImport attempting to load: 'BCrypt.dll'. (in domain Mono, info)
DllImport error loading library 'D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5\BCrypt.dll': '￧ﾳﾻ￧ﾻﾟ￦ﾉﾾ￤ﾸﾍ￥ﾈﾰ￦ﾌﾇ￥ﾮﾚ￧ﾚﾄ￦ﾖﾇ￤ﾻﾶ￣ﾀﾂ
'. (in domain Mono, info)
DllImport error loading library 'D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5\BCrypt.dll': '￧ﾳﾻ￧ﾻﾟ￦ﾉﾾ￤ﾸﾍ￥ﾈﾰ￦ﾌﾇ￥ﾮﾚ￧ﾚﾄ￦ﾖﾇ￤ﾻﾶ￣ﾀﾂ
'. (in domain Mono, info)
DllImport error loading library 'D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5\BCrypt.dll': '￧ﾳﾻ￧ﾻﾟ￦ﾉﾾ￤ﾸﾍ￥ﾈﾰ￦ﾌﾇ￥ﾮﾚ￧ﾚﾄ￦ﾖﾇ￤ﾻﾶ￣ﾀﾂ
'. (in domain Mono, info)
DllImport loaded library 'BCrypt.dll'. (in domain Mono, info)
DllImport searching in: 'BCrypt.dll' ('BCrypt.dll'). (in domain Mono, info)
Searching for 'BCryptGenRandom'. (in domain Mono, info)
Probing 'BCryptGenRandomW'. (in domain Mono, info)
Could not find 'BCryptGenRandomW' due to '￦ﾉﾾ￤ﾸﾍ￥ﾈﾰ￦ﾌﾇ￥ﾮﾚ￧ﾚﾄ￧ﾨﾋ￥ﾺﾏ￣ﾀﾂ
'. (in domain Mono, info)
Probing 'BCryptGenRandom'. (in domain Mono, info)
Found as 'BCryptGenRandom'. (in domain Mono, info)
DllImport attempting to load: '__Internal'. (in domain Mono, info)
DllImport loaded library '(null)'. (in domain Mono, info)
DllImport searching in: '__Internal' ('(null)'). (in domain Mono, info)
Searching for 'SetThreadErrorMode'. (in domain Mono, info)
DllImport searching in: '__Internal' ('(null)'). (in domain Mono, info)
Searching for 'GetFileAttributesExW'. (in domain Mono, info)
Probing 'GetFileAttributesExWW'. (in domain Mono, info)
Could not find 'GetFileAttributesExWW' due to '￦ﾉﾾ￤ﾸﾍ￥ﾈﾰ￦ﾌﾇ￥ﾮﾚ￧ﾚﾄ￧ﾨﾋ￥ﾺﾏ￣ﾀﾂ
'. (in domain Mono, info)
Probing 'GetFileAttributesExW'. (in domain Mono, info)
Found as 'GetFileAttributesExW'. (in domain Mono, info)
Requesting loading reference 2 (of 3) of D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5/System.Xml.dll (in domain Mono, info)
Loading reference 2 of D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5/System.Xml.dll asmctx DEFAULT, looking for System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (in domain Mono, info)
Assembly Ref addref System.Xml[0000000015399230] -> System[00000000153984b0]: 4 (in domain Mono, info)
Requesting loading reference 3 (of 6) of D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5/System.dll (in domain Mono, info)
Loading reference 3 of D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5/System.dll asmctx DEFAULT, looking for System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (in domain Mono, info)
Assembly Ref addref System[00000000153984b0] -> System.Xml[0000000015399230]: 3 (in domain Mono, info)
Image addref GodotTools[00000000153992c0] (asmctx DEFAULT) -> D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Tools/GodotTools.dll[00000000156f1720]: 2 (in domain Mono, info)
Prepared to set up assembly 'GodotTools' (D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Tools/GodotTools.dll) (in domain Mono, info)
Assembly GodotTools[00000000153992c0] added to domain GodotEngine.Domain.Scripts, ref_count=1 (in domain Mono, info)
Image addref GodotTools.ProjectEditor[0000000015399ce0] (asmctx DEFAULT) -> D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Tools/GodotTools.ProjectEditor.dll[0000000015687e30]: 2 (in domain Mono, info)
Prepared to set up assembly 'GodotTools.ProjectEditor' (D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Tools/GodotTools.ProjectEditor.dll) (in domain Mono, info)
Assembly GodotTools.ProjectEditor[0000000015399ce0] added to domain GodotEngine.Domain.Scripts, ref_count=1 (in domain Mono, info)
Requesting loading reference 1 (of 16) of D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5/Facades/netstandard.dll (in domain Mono, info)
Loading reference 1 of D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5/Facades/netstandard.dll asmctx DEFAULT, looking for System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (in domain Mono, info)
Image addref System.Core[00000000331c0870] (asmctx DEFAULT) -> D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5/System.Core.dll[00000000335f7b70]: 2 (in domain Mono, info)
Prepared to set up assembly 'System.Core' (D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5/System.Core.dll) (in domain Mono, info)
Assembly System.Core[00000000331c0870] added to domain GodotEngine.Domain.Scripts, ref_count=1 (in domain Mono, info)
Assembly Ref addref netstandard[0000000015398030] -> System.Core[00000000331c0870]: 2 (in domain Mono, info)
Requesting loading reference 0 (of 2) of D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5/System.Core.dll (in domain Mono, info)
Loading reference 0 of D:/Program Files/Godot_v3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5/System.Core.dll asmctx DEFAULT, looking for mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (in domain Mono, info)

### Steps to reproduce

just run Godot_v3.4-stable_mono_win64.exe on win11 , then this bug is appear，i think maybe 
AOT: image 'D:/Program Files/Godot_v3.3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5/mscorlib.dll.dll' not found: ￧ﾳﾻ￧ﾻﾟ￦ﾉﾾ￤ﾸﾍ￥ﾈﾰ￦ﾌﾇ￥ﾮﾚ￧ﾚﾄ￦ﾖﾇ￤ﾻﾶ￣ﾀﾂ
 (in domain Mono, info)
DllImport error loading library 'D:/Program Files/Godot_v3.3.4-stable_mono_win64/GodotSharp/Mono/lib/mono/4.5\BCrypt.dll': '￧ﾳﾻ￧ﾻﾟ￦ﾉﾾ￤ﾸﾍ￥ﾈﾰ￦ﾌﾇ￥ﾮﾚ￧ﾚﾄ￦ﾖﾇ￤ﾻﾶ￣ﾀﾂ
'. (in domain Mono, info)
is dll.dll and /4.5\BCrypt.dll issue?
win10 is good

**Comment by akien-mga** [comment]
Is it the same issue as #54076 ?

**Comment by aslyr** [comment]
> Is it the same issue as #54076 ?

yes，i close default window terminal ，it works well ，
