### ISSUE TITLE
[GDScript 2.0] Inconsistent cast String to integer

### ISSUE THREAD

**Issue by xsellier** [godotengine/godot#55284]
### Godot version

efd0db85f6fef4414aa6eb839a72ca75c2feb54b

### System information

Linux binogure 5.14.0-2-amd64 #1 SMP Debian 5.14.9-2 (2021-10-03) x86_64 GNU/Linux

### Issue description

I need to convert a string to an integer but nothing seems to work:

### Steps to reproduce

```gdscript
  convert(get_name(), TYPE_INT)
  # OUTPUT:
  # Parser Error: Invalid call function "convert".
```
```gdscript
  int(get_name())
  # OUTPUT:
  # Parser Error: No constructor of "int" matches the signature "int(String)"
```
```gdscript
  get_name() as int
  # OUTPUT:
  # Invalid cast: could not convert value to 'int'.
```
```gdscript
  get_name().to_int()
  # OUTPUT:
  # Invalid call. Nonexistant function "to_int" in base "StringName".
```

Correct way to convert a node name into an int:
```gdscript
str(get_name()).to_int()
```

**Comment by KoBeWi** [comment]
Related to #44407
In your case, the `name` property is a StringName, so you need to cast it to String first.

We could probably add an `int(StringName)` conversion operator.

**Comment by xsellier** [comment]
Either String or StringName none work.

**Comment by KoBeWi** [comment]
Yep, because you need to do `String.to_int()`, see the issue I linked. If we fix one of these issues, the other would be easy to fix too.

**Comment by akien-mga** [comment]
Consolidating this in #44407 which is the same root cause.
