### ISSUE TITLE
TextureRect is not passing Mouse over events, up the node tree, when mouse pass option is set, but will pass mouse events , when mouse  is set to ignore

### ISSUE THREAD

**Issue by DavidLeeEvans** [godotengine/godot#55288]
### Godot version

v3.4.rc1.official [90f8cd89a]

### System information

Arch-Linux GLES3,

### Issue description

TextureRect is capturing mouse over events, when the mouse input is set to pass.
Action inspected is for the TextureRect to propagate the mouse over event up to the TextureButton

The follow happens:
 - TextureRect mouse input set to ignore: The TextureButton respond to events.
 - TextureRect mouse input set to pass: The TextureButton does NOT respond to mouse over events.
Not sure if this is by design
![error](https://user-images.githubusercontent.com/340788/143265206-8450491d-d73c-41f3-a59d-2db66c10b8ba.png)
[TestTextureMouse.zip](https://github.com/godotengine/godot/files/7596777/TestTextureMouse.zip)

 

### Steps to reproduce

Setup a simple scene with a TextureButton & TextureRect, set the TextureRect mouse to pass
![error](https://user-images.githubusercontent.com/340788/143265466-d8415c27-8a8a-4e5e-99bc-92382c1d692f.png)

### Minimal reproduction project

[TestTextureMouse.zip](https://github.com/godotengine/godot/files/7596789/TestTextureMouse.zip)

**Comment by KoBeWi** [comment]
`mouse_filter` affects input passing to parent nodes, it doesn't work for sibling nodes.
