### ISSUE TITLE
Editor Flicker When Returning from Sleep on MacOS

### ISSUE THREAD

**Issue by ztc0611** [godotengine/godot#55295]
### Godot version

3.3.4.stable, 3.4.stable

### System information

MacOS Monetary 12.0.1, GLES3, Apple M1

### Issue description

When Godot's Editor is being displayed on an external monitor connected to my MacBook, sometimes returning from sleep mode will cause the brightness of the entire editor window to flicker rapidly. This appears to be tied to the scene's frame updates, as scenes with a complex shader that updates every frame will flicker at the full frame rate of the monitor (in my case 60), it can be as low as 5fps. It seems to bottom out at about 1 flicker per second on a totally static screen.

This does not occur on any other window on my screen, including if they were displayed on top of the Godot editor when this happened. Because of this, I do not think this is a MacOS bug, but it is very difficult to tell. Dragging the editor onto my laptop's screen and back onto the external monitor will stop the flickering, as will restarting the editor.

This does not affect the debugger window if the project was being played when sleep mode was triggered.

**Warning for flashing imagery in the following videos. I am not certain if they are strong enough to cause any adverse reactions for those who are affected by such things, but air on the side of caution please.**

Scene with a shader that updates every frame:

https://user-images.githubusercontent.com/28269330/143332123-4afebcef-2b6f-4be8-9d3b-849f855a0849.mov

Zooming in and out on the editor (the flickering slows to a crawl when nothing is changing): 

https://user-images.githubusercontent.com/28269330/143331987-be253950-c9c6-4624-8bea-a92847938d3d.mov

### Steps to reproduce

I have tried to find a reliable way to replicate this, and have as of yet been unsuccessful. It appears about 1 in 10 times that my Mac returns from sleeping. It has happened to me about 10 times so far.

Info about my system:
MacBook Pro M1 (Late 2020) attached to an external 1080p monitor via a USB-C Dock, that is also supplying power. The computer was locked by pressing the power button, but the lid was not shut. When unlocked, the laptop's screen is open and used alongside the external monitor.

### Minimal reproduction project

It appears to occur in any project that I have open at the time the computer is put to sleep, but is not guaranteed to happen or not happen no matter which project is open.

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by Krumelur** [comment]
Seeing something similar here. M1 Macbook Air. As long as I'm on the internal monitor, all is fine.
Using the external (USB-C connection) monitor, weird things happen: https://www.youtube.com/watch?v=pYv76X-Rsf8

This seems to happen with 3.4 RC1 but not with 3.4 stable.

**Comment by ztc0611** [comment]
> This seems to happen with 3.4 RC1 but not with 3.4 stable.
It still occurs for me occasionally with 3.4.2.stable, but not nearly as much as before. Also the flickering is much slower when it happens. I guess resolved?

**Comment by ztc0611** [comment]
I've not seen this issue at all with 3.4.4 or 3.5-rc6. Unsure if Godot fixed it or if MacOS 12.x fixed it.

**Comment by Calinou** [comment]
Closing per @ztc0611's comment. Please comment if you can reproduce this.

**Comment by Tobio89** [comment]
I'm on MacOS Ventura 13.3.1, Godot v3.4.4.stable.official [419e713a2] and I get this.
The screen lightens and dims based on where the mouse is. The worst thing I discovered is if I open one of the title bar menus, as I hover over the icons the screen flickers.
