### ISSUE TITLE
GDExtensions issues with doc pages not showing parameter names and object types

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#55298]
### Godot version

4.0.dev 19223f3241bb0d6afa3e9e51f8162657bebae6b6

### System information

Windows 10

### Issue description

When looking at the help pages generated for extensions we see two issues popup:
![image](https://user-images.githubusercontent.com/1945449/143365847-e2780b8c-45da-482b-8028-98b67020719a.png)

So the first issue shows itself pretty clearly, all the arguments have names like `arg0` and `arg1`, the test project (including the changes in https://github.com/godotengine/godot-cpp/pull/662) provides names for all the parameters and as far as I'm aware these are stored in the classdb so I'm guessing the issue is on the Godot side. 

The second problem we see in our `ref_obj` property and the functions such as `extended_ref_checks` and `return_extended_ref`, where the return type is set as `Object`. All these are property typed, we can see for the property that the inspector is correctly seeing the property is expecting a `ExampleRef` object type. So again this looks like an issue with the documentation not reading this information correctly from the classdb when extensions are involved.

### Steps to reproduce

Compile the test project in `godot-cpp` and view the help pages for `Example` and `ExampleRef` classes.

### Minimal reproduction project

See https://github.com/godotengine/godot-cpp/pull/662

**Comment by Daylily-Zeleen** [comment]
I think this issue should add "topic:gdextension" lable, because it only occur with GDExtension/GDNative.

And I found another problem which about this: default arguments of method can't show in doc pages, too.

And I hope this problem can be fix as fast as possible. A perfect document is very important to share and use.
