### ISSUE TITLE
MeshInstance as a child of RigidBody looks crooked in game, but fine in editor.

### ISSUE THREAD

**Issue by LennartSchlieder** [godotengine/godot#55296]
### Godot version

3.3.2.stable.official

### System information

Linux Mint (Ubuntu 20), GLES3, RTX 3090, Driver Version: 460.27.04

### Issue description

A cube as a child of a rotated rigid body looks crooked in the final game. This is only the case, when it is a child of the rigidbody. The cube looks fine in the camera preview in the editor.
![Bug?](https://user-images.githubusercontent.com/468944/143338101-1e63e0f7-97fd-4018-a4bd-9a9cff445f56.png)

![bug](https://user-images.githubusercontent.com/468944/143345839-28d8e641-7e1d-43ce-9647-4b48f58a8b17.png)

It seems to have something to do with the transforms properties of the child objects.
 

### Steps to reproduce

Create a RigidBody, with a MeshInstance as a child. Rotate the RigidBody. The Mesh will look different in the game, than it does in the camera preview in the editor. 

### Minimal reproduction project

[Pinball.zip](https://github.com/godotengine/godot/files/7599488/Pinball.zip)

**Comment by Calinou** [comment]
The RigidBody is scaled, but it should not be as its scale will be reverted to `Vector3(1, 1, 1)` when the project is run:

![image](https://user-images.githubusercontent.com/180032/143354385-0bd948ad-7e02-46bc-bbe0-ec9dd4f4b0bd.png)

Instead, scale the MeshInstance and *resize* the CollisionShape's extents (but do not scale it!).

**Comment by lschlieder** [comment]
Ah, so i was just stupid. Though that was the case, but wanted to report it nevertheless. 

>Scaling of RigidBodies is currently not supported and is a known limitation. There are plans to support uniform scaling of RigidBodies in the future (but non-uniform scaling is unlikely to ever be supported): #5734

This should really be implemented soon. I can't be the only noob, that fell for that. It is not really intuitive. One could at least give a warning or something.

**Comment by Zireael07** [comment]
> One could at least give a warning or something.

Judging from the screen, you did have a warning (the yellow triangle) in editor...

**Comment by lschlieder** [comment]
That warning was for the missing collision shape, not from scaling of the rigidbody.

**Comment by Calinou** [comment]
A warning is already supposed to be emitted, but it's not working for some reason: https://github.com/godotengine/godot/blob/902911e3afcaabcc9f09a6f2c3ec770ee6aa112d/scene/3d/physics_body.cpp#L783-L796

cc @pouleyKetchoupp

**Comment by lschlieder** [comment]
Is there a reason, why it is not emmited, when the mode is static or kinematic? 
One could just change 
`get_mode() == MODE_RIGID || get_mode() == MODE_CHARACTER `
to 
'get_mode() == MODE_RIGID || get_mode() == MODE_CHARACTER || get_mode() == MODE_KINEMATIC || get_mode() == MODE_STATIC'

**Comment by kleonc** [comment]
> A warning is already supposed to be emitted, but it's not working for some reason:

There's no warning in MRP because `mode` is set to `Kinematic`. No idea whether the problem in this case is no warning or if in `Kinematic` mode scale can be modified just fine and there's something else going on.

> The RigidBody is scaled, but it should not be as its scale will be reverted to Vector3(1, 1, 1) when the project is run:

The problem is I don't see it being reverted to (1, 1, 1) after run. Maybe in the physics server it's set to such scale but the scale of `RigidBody.transform` is unchanged.
