### ISSUE TITLE
Android CameraServer.feeds() returning empty array

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#55290]
### Godot version

3.4 stable

### System information

OSX 10.15.7

### Issue description

When exporting to Android or running through the debug on android feature `CameraServer.feeds()` returns an empty array.

The same code is working correctly for OSX

### Steps to reproduce

1. Clone https://github.com/tavurth/godot-camera
2. Setup android export
3. Enable camera permission
4. Run as debug on Android device

### Minimal reproduction project

https://github.com/tavurth/godot-camera

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/46531.

**Comment by Swaraj-cs** [comment]
Any other option to use  for android?

**Comment by Calinou** [comment]
> Any other option to use for android?

Not yet: https://github.com/godotengine/godot/issues/46531#issuecomment-1186628092
