### ISSUE TITLE
Running debug process pollutes project.godot and forces to show a confirm dialog after closing

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#55302]
### Godot version

e49b127b41a425fadc47d09d375624c5511f1f06

### System information

Windows 10

### Issue description

![bug](https://user-images.githubusercontent.com/3036176/143400166-edf14369-f4d4-4c2b-bd9f-a7dc6662aed7.gif)

### Steps to reproduce

Run to debug any project and close it.

**Comment by akien-mga** [comment]
Possibly related to #31171, cc @aaronfranke.
