### ISSUE TITLE
Running 4.0 Linux binary with `--display-server headless` still requires X11 libraries to be installed

### ISSUE THREAD

**Issue by Noiros** [godotengine/godot#55317]
### Godot version

4.0 dev

### System information

Windows 11, GLES3, Rx 5700 XT, Ryzen 7 3600x 

### Issue description

I am currently switching my godot game 3.4 to 4.0 but I encountered a problem with the server dedicate, here is my error in image
![image](https://user-images.githubusercontent.com/66034941/143489666-7cfab155-003a-409a-8887-b21df4f5a468.png)

Server config (Ubuntu 20.04, 32Gb of Ram and intel xenon (by scaleway))

### Steps to reproduce

just take binary or build project and start on dedicate server and let's go

### Minimal reproduction project

http://51.91.125.27/Object%20Wars%20server%20mini.zip

**Comment by Calinou** [comment]
Try installing the Xcursor libraries from your distribution's package manager (`sudo apt install libxcursor1`).

**Comment by Noiros** [comment]
ok thanks you, i trying

**Comment by Noiros** [comment]
not working, with the same error ...

**Comment by CrezyDud** [comment]
ubuntu sucks with downloading and it's uselessly complicated

you have to add 32 bit downloads
i don't know how but maybe 32 bit libxcursor solves it

**Comment by Noiros** [comment]
it's already isntall 
![image](https://user-images.githubusercontent.com/66034941/143494277-cef8a509-d7d1-4a48-9341-1352cd10d2e2.png)

**Comment by Calinou** [comment]
> ubuntu sucks with downloading and it's uselessly complicated
> 
> you have to add 32 bit downloads i don't know how but maybe 32 bit libxcursor solves it

Their server binary is 64-bit, so they need 64-bit libraries installed. They don't need to install 32-bit libraries.

PS: I have to remind you that we have a [Code of Conduct](https://godotengine.org/code-of-conduct). Please stay constructive.

**Comment by Noiros** [comment]
ok it's work !, i have install this lib

sudo apt install libxcursor-dev
sudo apt install libxinerama-dev
sudo apt install libxrandr-dev
sudo apt install libxi6
sudo apt install libgl1

Sorry Calinou ...

**Comment by Faless** [comment]
I'm not sure X11 libraries dynamic loading was ever implemented.
Though if the linuxbsd binary is compiled with the `x11=no` scons flag it should not depend on them.

**Comment by akien-mga** [comment]
Fixed by #69449.
