### ISSUE TITLE
Can't create config directory on Windows DFS roaming profiles

### ISSUE THREAD

**Issue by and-rad** [godotengine/godot#55314]
### Godot version

v4.0.dev.custom_build [1e99eea06]

### System information

Windows 10, AD-managed roaming user profiles

### Issue description

When Godot is used on a Windows PC, it fails to create the user's config directory **%AppData%/Godot** if the user profile is a roaming profile managed by [Active Directory](https://en.wikipedia.org/wiki/Active_Directory) and mounted on a [DFS](https://en.wikipedia.org/wiki/Distributed_File_System_(Microsoft)) path.

## Some More Details
It is common that user profiles in large companies and universities are not bound to local machines and instead live on a server and are loaded onto any machine when a user logs in. These are called **roaming profiles**. Windows uses Active Directory to manage users and groups. When a roaming profile is mounted, it's often done on a DFS path, which takes the form `\\ServerName\RootName\path\to\wherever\`. See [here](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-dfsc/3109f4be-2dbb-42c9-9b8e-0b34f7a2135e) for the full DFS specification.

Godot does not recognize that path. It fails to correctly parse it as a DFS path and subsequently errors out of creating the user config. This means no shader cache, no editor settings, no user-specific settings are ever created or saved.

The code that causes the failure is `DirAccess::make_dir_recursive` in `dir_access.cpp`, specifically this part:
```c++
full_dir = full_dir.replace("\\", "/");

String base;

if (full_dir.begins_with("res://")) {
	base = "res://";
} else if (full_dir.begins_with("user://")) {
	base = "user://";
} else if (full_dir.begins_with("/")) {
	base = "/";
} else if (full_dir.find(":/") != -1) {
	base = full_dir.substr(0, full_dir.find(":/") + 2);
} else {
	ERR_FAIL_V(ERR_INVALID_PARAMETER);
}

full_dir = full_dir.replace_first(base, "").simplify_path();

Vector<String> subdirs = full_dir.split("/");

String curpath = base;
for (int i = 0; i < subdirs.size(); i++) {
	curpath = curpath.plus_file(subdirs[i]);
	Error err = make_dir(curpath);
	if (err != OK && err != ERR_ALREADY_EXISTS) {
		ERR_FAIL_V_MSG(err, "Could not create directory: " + curpath);
	}
}
```

Running through these instructions, the DFS path 
`\\dfs\mycorp\home\myusername\AppData\Godot` turns into
`//dfs/mycorp/home/myusername/AppData/Godot` (this is expected) and from there into
`/dfs/mycorp/home/myusername/AppData/Godot`.

Because there is no Windows-type drive letter (like C:\) in the path, it effectively turns it into a unix file path. It then tries to recursively create this directory, starting at the root `/`, which fails, but not for the reasons the engine would expect. It returns with an error message and the directory is never created.

Console output:
```
USER ERROR: Could not create directory: /
   at: DirAccess::make_dir_recursive (core\io\dir_access.cpp:173) - Method/function failed. Returning: err
USER ERROR: Can't create shader cache folder, no shader caching will happen: //dfs/mycorp/home/myusername/AppData/Godot
USER ERROR: Cannot save EditorSettings config, no valid path
   at: EditorSettings::save (editor\editor_settings.cpp:1012) - Cannot save EditorSettings config, no valid path
```

### Steps to reproduce

- Sit down on a Windows machine that mounts roaming user profiles on a DFS path
- Install Godot and launch the project manager
- Create a project, change the UI language, close the manager
- Launch the manager again, observe how none of the settings have been saved and the list of projects is empty

### Minimal reproduction project

Any will do, even just starting the project manager. Observe the console output.

**Comment by and-rad** [comment]
I'm looking into this while at work, since that's the only place where I have access to a setup described above, and I noticed that path handling in Godot is kinda all over the place. I'm not super happy about that and it makes debugging harder than it has to be.

Anecdotally, grepping for ":/" and ":\\" returns a bunch of files, none of them part of the Windows-specific platform files. DirAccess checks for it (kinda understandable), the String class does (huh?), and then there's `path_utils`, which seems like a perfect place to do any path operations, queries, and transformations; and *that* is used by three other files in the entire codebase.

I have a feeling that this should be addressed.

**Comment by Calinou** [comment]
@and-rad See also https://github.com/godotengine/godot-proposals/issues/2474, which would benefit from more unified path handling.

**Comment by and-rad** [comment]
Damn, I just created a dedicated proposal for path handling. But as far as I can see, mine and the other proposal are sufficiently different, so I should be in the clear?

**Comment by Calinou** [comment]
> But as far as I can see, mine and the other proposal are sufficiently different, so I should be in the clear?

Yes, the proposals are different enough.
