### ISSUE TITLE
[Find in Files] No results found even though many occurrences 

### ISSUE THREAD

**Issue by Razzlegames** [godotengine/godot#55323]
### Godot version

- `3.3.3.stable`
- `3.4`

### System information

Windows 10

### Issue description

After updating to 3.3.3.stable I noticed "Find in Files" stopped functioning for me in this specific project.

![image](https://user-images.githubusercontent.com/8754559/143500178-d838dbc1-1a87-4967-b9ac-6be49ec949b5.png)

I haven't altered any of the default search extensions either:

![image](https://user-images.githubusercontent.com/8754559/143500215-086ea6d1-9097-4754-8d96-04ddad11b29a.png)

This appears to be a bug or a bad configuration.  I didn't look into if there were any tag caches implemented by Godot.

### Steps to reproduce

Unknown:  Appears to be a specific state that I cannot reproduce in other projects.

However, it always exists in this project.

## To look into
https://github.com/godotengine/godot/pull/54305/files

**Comment by Razzlegames** [comment]
If I get time I'll poke around the C++ debugger to see if I can figure anything out

**Comment by KoBeWi** [comment]
I think it will be difficult to debug without access to *this specific project*.

Does removing .import folder help? What if you replace project.godot with an empty one?

**Comment by Razzlegames** [comment]
> I think it will be difficult to debug without access to this specific project.

I agree.  I'll see if I can create a min project

> Does removing .import folder help? 
No changes

> What if you replace project.godot with an empty one?
No changes


- Confirmed search working when reverting back to `3.3.2-stable`.  
- Not working on
  - 3.3.3-stable
  - 3.4

**Comment by Razzlegames** [comment]
OK this wasn't too hard.  


I think this is the issue.  

- if `.gdignore` is in a directory it skips parsing this dir all together.

https://github.com/godotengine/godot/commit/f84de497187aed1fd014962394ef17dd49138322

Is this intended?  My impression of  `.gdignore` was its intent was to exclude specific files **ONLY** if they match a `pattern` expression called out in the `.gdignore` file. (similar to `.gitignore`)

- I have `.gdignore` in root of project
   - It calls out my tests sub dir  `./Tests` 
- One is blank and was auto placed in there by the editor?
   - It's in `./.import`
   
I think this could be a bug?

**Comment by Zireael07** [comment]
@Razzlegames: Nope, .gdignore files do NOT work like .gitignore (this was recently made clearer in the docs since a LOT of people made that mistake). They ignore the whole directory, as you observed.

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot/pull/53583 which was rejected.

**Comment by Razzlegames** [comment]
Ah ok.  That's a bit unexpected.  I'll stop working on my patch then :( 

Thanks guys.  I'll close this issue now.
