### ISSUE TITLE
Polish characters not displayed in Labels

### ISSUE THREAD

**Issue by municho** [godotengine/godot#55329]
### Godot version

3.4.stable.official

### System information

Kubuntu 18.04.6 LTS, GLES2 and GLES3, x86_64

### Issue description

A Label does not show all characters in the following text:
ąćęłóśżźĄĆĘŁÓŚŻŹäöüÄÖÜ

What is shown is only:
óÓäöüÄÖÜ

First I thought it was a problem with a font, but changing a font did not solve the problem (the chosen font displays Polish characters in Libre Office w/o any problems).

### Steps to reproduce

Create a UI node, create a Label, set the label text as above

### Minimal reproduction project

[LabelTest.zip](https://github.com/godotengine/godot/files/7605406/LabelTest.zip)

**Comment by akien-mga** [comment]
> First I thought it was a problem with a font, but changing a font did not solve the problem (the chosen font displays Polish characters in Libre Office w/o any problems).

That does seem to be a problem with the font. Changing the default font to DejaVuSans works fine for me:

![image](https://user-images.githubusercontent.com/4701338/143506055-cd9d4c2b-dc7a-4a41-93ed-40a1be1c08f0.png)

**Comment by Chaosus** [comment]
The same problem is with russian symbols and probably with many other languages. This is a well-known problem and is a limitation of the default font of the non-editor label which uses a limited glyph-set to decrease a binary size.

**Comment by KoBeWi** [comment]
> (the chosen font displays Polish characters in Libre Office w/o any problems).

Doesn't Libre Office use a fallback font if some characters are unsupported? I think that was the case (it would be helpful if you attached that font here for testing).

In any case, the default font is lacking in the supported characters. If you want to display Polish letters, use a font that contains them.
This was resolved in 4.0, where the default font has a wider range of chars. Closing.
