### ISSUE TITLE
Vulkan: Screen space reflections and depth of field break each other

### ISSUE THREAD

**Issue by drcd1** [godotengine/godot#55337]
### Godot version

v4.0.dev.calinou [547c27077]

### System information

Windows 10, Vulkan, Nvidia GeForce 1070 Max-Q

### Issue description

When enabling both screen space reflections and depth of field, the effect looks very glitchy.
Enabling each of them individually looks fine.

Here is the glitch in motion, as well as evidence of SSR and DOF working fine on their own.

![godot_issue](https://user-images.githubusercontent.com/22733172/143513326-02f30bcb-c4e0-44df-a936-cc933560ae84.png)

### Steps to reproduce

Create a scene with a metallic material (low roughness). Enable screen space reflections. Enable depth of field (near or far). Witness the above described problem.

### Minimal reproduction project

[bug_report.zip](https://github.com/godotengine/godot/files/7605728/bug_report.zip)

**Comment by clayjohn** [comment]
This has been fixed at some point and is no longer reproducible.
