### ISSUE TITLE
I encrypt my game and I open the game and game closed I use correct key but didnt work

### ISSUE THREAD

**Issue by hackeroyuncu09** [godotengine/godot#55340]
### Godot version

3.3.stable

### System information

Windows 10

### Issue description

I encrypt my game and I open the game and game closed I use correct key but didnt work

### Steps to reproduce

qa

**Comment by akien-mga** [comment]
You should compile Godot export templates with your key, see https://docs.godotengine.org/en/stable/development/compiling/compiling_with_script_encryption_key.html
