### ISSUE TITLE
Vulkan: GPUParticles2D interpolation not implemented yet (unlike in GPUParticles3D)

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#55357]
*Related to https://github.com/godotengine/godot/issues/51318.*

### Godot version

4.0.dev (5efe80f30)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 470.74)

### Issue description

GPUParticles2D doesn't have an **Interpolate** property available. This helps make particles feel smoother without using too much GPU time, especially when attractors and collision are enabled. The effect is more noticeable on high refresh rate monitors, but now that GPUParticles simulation occurs at 30 Hz by default, interpolation is needed on 60 Hz monitors too to ensure smooth visuals.

### Steps to reproduce

- Add a GPUParticles2D node.
- Notice how there's no **Interpolate** property in the inspector.

### Minimal reproduction project

N/A

**Comment by IgorKordiukiewicz** [comment]
Is it only missing the interpolation property or also the implementation for the property in 2D?

**Comment by Calinou** [comment]
> Is it only missing the interpolation property or also the implementation for the property in 2D?

I think both the implementation and the property are missing, but I'm not 100% sure.

**Comment by IgorKordiukiewicz** [comment]
So it looks like it only the property was missing as after just adding it, switching it off and on changes the behavior:

https://user-images.githubusercontent.com/25117425/156371120-43e309d2-e7d7-43c3-a1fc-678af7b08081.mp4
