### ISSUE TITLE
OS.execute a scene is broken on Godot 3.4 

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#55379]
### Godot version

Godot Engine v3.4.stable.official.206ba70f4

### System information

MacOS v11.3

### Issue description

To run a scene by using OS.execute is broken since Godot 3.4.x on MacOS.
On Windows works fine as before.

I used this execute to run a scene without debug info on my plugin GdUnit3.

Tested by a simple project and it can be reproduce. 

### Steps to reproduce

Use Godot 3.4 on MacOS

Try to run a scene by using OS.execute()

```
	var arguments := Array()
	arguments.append("-d")
	arguments.append("-v")
	arguments.append("res://TestScene.tscn")
	var output = []
	prints("execute ", OS.get_executable_path(), arguments)
	var current_runner_process_id = OS.execute(OS.get_executable_path(), arguments, false, output, true);
	prints("execute result", current_runner_process_id, output)
```

console print
```
execute  /Users/xxxx/Documents/develop/private/Godot_v3.4.app/Contents/MacOS/Godot [-d, -v, res://TestScene.tscn]
execute result 84106 []

```
No scene is started!

See attached project to reproduce.

### Minimal reproduction project

[execute.zip](https://github.com/godotengine/godot/files/7611565/execute.zip)

**Comment by MikeSchulze** [comment]
is still broken on v3.4.4.stable.official [419e713a2]

**Comment by bruvzg** [comment]
It's probably require `--path` argument as well, otherwise it will look in the current directory, which can be anything.

**Comment by MikeSchulze** [comment]
it works on windows without any issues, is still an issue on linux/mac

**Comment by MikeSchulze** [comment]
> It's probably require `--path` argument as well, otherwise it will look in the current directory, which can be anything.

it makes no difference, is only an issue on unix systems

**Comment by bruvzg** [comment]
> it makes no difference, is only an issue on unix systems

Seems to be working fine in the current 3.5 on macOS, when using:

```
-d -v --path /absolute/path/to/the/project/folder res://TestScene.tscn
```

Without `--path`, it might work or not depending on executable location and current working directory. If it is working, it's a pure coincidence.

**Comment by MikeSchulze** [comment]
ok i run again into this issue
with the argument --path it is working.
