### ISSUE TITLE
Code Completion, Full Crash [Error: Vector<wchar_t>::Operator [] ]

### ISSUE THREAD

**Issue by Vaiktorg** [godotengine/godot#5537]
**Operating system or device - Godot version:**
Windows 10 Pro 64-bit
Godot Engine v2.0.3 Stable

**Issue description** (what happened, and what was expected):
Typing in code editor, full crash when code completion tried to complete my code. lol

**Steps to reproduce:**
No certain way, some projects work, some just crash. Projects that due crash are because of the same thing.

**Link to minimal example project** (optional but very welcome):
https://drive.google.com/open?id=0B0tAu5jzckVeSnRZcGI0RTR2alk

**Comment by vnen** [comment]
You should've added the picture. I can find the steps to reproduce just by looking at it :laughing: 

![13606708_10208241674976935_5663538487691091470_n](https://cloud.githubusercontent.com/assets/5599796/16547521/38a74c90-4147-11e6-9253-1e65c3059350.jpg)

```GDScript
var myvar = {
i # wait the completion and then backspace, it'll crash
```
