### ISSUE TITLE
Caret/cursor and minimap colors go black after a while (and after suspend-to-RAM)

### ISSUE THREAD

**Issue by hellp** [godotengine/godot#55389]
### Godot version

3.4.stable.arch_linux

### System information

NVIDIA RTX 2070 SUPER (driver 495.44), GLES2 and 3

### Issue description

After using Godot for a while, and usually after moving away from it and coming back (no screen saver involved, though), but consistently after returning from a suspend-to-RAM situation, my text cursor (caret) as well as the colors on the minimap turn black, making it very hard to continue working. After a restart of Godot the issue goes away.

![DnXBMBA](https://user-images.githubusercontent.com/32779/143691886-879763aa-6a30-4987-b263-5d30f76ab39e.png)

- Desktop environment is X.org 1.21.1.1 and Gnome 41.1 (but issue appeared in earlier versions)
- I've used Godot only since 3.3 and under various (recent) kernels and graphics drivers and had the issue ever since.
- Happens both with GLES2 or GLES3
- Other application on my system do not have similar issues.
- A simple restart of GNOME (Alt-F2 "r", which sometimes fixes minor UI quirks) does not help.

### Steps to reproduce

- Use Godot for a while (30min+?)
- Move away/tab away from Godot
- Suspend-to-RAM (most reliable way to reproduce)
- Cursor/minimap are suddenly black

**Comment by Calinou** [comment]
Can you reproduce this after disabling batching in the Project Settings (uncheck **Use Batching** *and* **Use Batching In Edtior**)?

**Comment by hellp** [comment]
Update: Disabling Batching (both settings disabled) on 3.4 **does not** fix it. I'll try the old version next.

**Comment by hellp** [comment]
Update: issue **is** present in 3.1.2 already (after suspend). There is no minimap yet in that version, but the cursor is black as described.

**Comment by permelin** [comment]
I have the same issue on 3.4.4 stable. I'm using an Nvidia RTX 2080 on Debian Bookworm.

I've found that the cursor does **not** turn black in the code editor if I enable _block caret_ in the settings. It's not what I prefer but it's better than having to restart the editor ten times per day just to be able to see the cursor.

**Comment by DeeJayLSP** [comment]
I would like to report this happens on my work PC, which uses a GTX 1660 Super.

However it doesn't happen on my home PC, which uses a RX 460.

Both use Ubuntu 22.04. May it be a NVIDIA driver issue?
