### ISSUE TITLE
Particle2D/3D emission shape "Sphere" is behaving different than documented.

### ISSUE THREAD

**Issue by RPicster** [godotengine/godot#55398]
### Godot version

4.0.dev 52b7d5f

### System information

Windows 10

### Issue description

The documentation about Particle2D / 3D emission shape mode "Sphere" is saying:
`Particles will be emitted in the volume of a sphere.`

The actual behaviour of the implementation (of 3.x and 4.0.dev) is different and particles are emitted from the surface instead of the volume.

While this behaviour could be useful and wanted to a user, usually an implementation using the volume of a sphere is more useful.

![XeU2OutntS](https://user-images.githubusercontent.com/9423774/143722318-99987969-6089-43ef-8d16-f5602866fabf.gif)

It is especially visible and obvious in 2D because the z transformation is discarded, so there are more particles on the edges of the sphere.

### Steps to reproduce

- Create a Particle2D or 3D node
- Setup a simple particle system 
- Set it to Sphere Emission shape

**Comment by Calinou** [comment]
This was originally changed in https://github.com/godotengine/godot/pull/30357.

**Comment by RPicster** [comment]
I checked the old shader code and it was emitting from the surface and the new code is still emitting from the surface.

I opened a PR:
https://github.com/godotengine/godot/pull/55399

There my approach was to offer `Sphere Surface` and `Sphere` as emission shapes.
