### ISSUE TITLE
ParticleMaterial particle size not resetting under certain conditions

### ISSUE THREAD

**Issue by RPicster** [godotengine/godot#55396]
### Godot version

4.0.dev 52b7d5f

### System information

Windows 10

### Issue description

Particle scale is not reset when a emitter shape other than point is set and a higher than default fixed_fps is used.
Combined with a curve for particle scale this will reused particles to be invisible.

https://user-images.githubusercontent.com/9423774/143720746-027ed838-d34c-43b1-8c81-2f4cf4e92c85.mp4

### Steps to reproduce

- Create a new GPUParticle3D Node.
- Set fixed fps to 144 (or 300 or anything high)
- Set it up to show something (rectangle is enough)
- Add a scale curve to the size parameter and make it go to 0 in the end.
- Set the emission shape to anything but point (eg. sphere)

### Minimal reproduction project

[particlematerial-size-reset-bug.zip](https://github.com/godotengine/godot/files/7612392/particlematerial-size-reset-bug.zip)

**Comment by fracteed** [comment]
I have been having similar issues. After adding a curve for scaling, all particles disappear, or maybe they have actually gone down to zero. Even if I then delete the curve, I cant see any particles any more.
