### ISSUE TITLE
Right-clicking a property array sometimes will spawn two popups at once

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#55401]
### Godot version

52b7d5f

### System information

W10

### Issue description

Title. One popup is specific to this property type and the other is generic property popup.
![nJzCkwYnT9](https://user-images.githubusercontent.com/2223172/143723637-543a60cb-9c91-4457-9e8a-02ff755008e3.gif)

### Steps to reproduce

1. Inspect any node with property array, e.g. TileMap `layers`.
2. Right click property name

**Comment by guillaume-haerinck** [comment]
Originates from commit 4bd7700e, both array and properties popup are showing up

**Comment by groud** [comment]
This issue is not happening anymore as the popup menu on array element does not show up. I'll close this one for now and open an issue about this new issue.
