### ISSUE TITLE
Godot ignores folder with a project.godot file inside of it

### ISSUE THREAD

**Issue by Nukiloco** [godotengine/godot#55405]
### Godot version

v4.0.dev.calinou [52b7d5fa3]

### System information

Windows 10, Vulkan, Nvidia GTX 750 Ti

### Issue description

Currently when git cloning an ``addon repository`` into your project's ``addons`` folder, Godot will ignore the folder if the folder contains a project.godot file inside of it. I assume this is because of conflict with multiple folders or might be intended to prevent conflicts with the root project godot file.

### Steps to reproduce

1. Clone an repository into the ``addons`` folder. For example https://github.com/ywmaa/Advanced-Movement-System-Godot which is the repository that I cloned into the addons folder.
2. Godot will ignore the folder.

### Minimal reproduction project

Currently Github's upload feature is broken for me so I will need to find another way to upload the file.
I'm constantly getting a ``is not included in the list`` error on Github which I have no clue what that means.

**Comment by Nukiloco** [comment]
Just tested out more, this is not because of the .git folder but because of the ``project.godot`` file.

**Comment by akien-mga** [comment]
That's intended. A `project.godot` file defines a standalone Godot project, and those can't be nested (you can't have multiple `res://` pointing to different locations).

**Comment by Calinou** [comment]
As the repository's README says, ["This project is a template"](https://github.com/ywmaa/Advanced-Movement-System-Godot#this-project-is-a-template-for-creating-advanced-thirdfirst-person-movement-in-godot). It isn't meant to be cloned as an add-on.

I suggest contacting the project author to ask them to create a separate add-on repository. See an example of this with https://github.com/godot-extended-libraries/godot-lod and https://github.com/godot-extended-libraries/godot-lod-demo.

**Comment by Nukiloco** [comment]
Ah my bad I didn't see that part.
