### ISSUE TITLE
Vulkan: Depth of Field doesn't work when MSAA is enabled

### ISSUE THREAD

**Issue by BraqueDown** [godotengine/godot#55406]
### Godot version

v4.0.dev.custom_build [52b7d5fa3]

### System information

Windows 10, Vulkan, GTX 1060 6GB (496.76)

### Issue description

When MSAA is set to anything other than off, the camera will not render depth of field at all. This is not the case in 3.4.

![MSAA OFF](https://user-images.githubusercontent.com/43602802/143734059-f5a978e9-197f-404e-aada-7de284b60903.png)
![MSAA ON](https://user-images.githubusercontent.com/43602802/143734065-bb0ff333-3247-4b70-addb-b4f6234aa710.png)

### Steps to reproduce

1. Place meshes in scene.
2. Add Camera3D.
3. Create new CameraEffects resource on the Camera3D and enable Depth of Field.
4. Preview Camera in editor.
5. Go to Project Settings and set `rendering/anti_aliasing/quality/msaa` to anything other than off.

### Minimal reproduction project

[DoF MSAA Broken.zip](https://github.com/godotengine/godot/files/7613031/DoF.MSAA.Broken.zip)

1. Play (F5)
2. Use Space to toggle MSAA

**Comment by GanidhuAbey** [comment]
Yea I think I fixed it.

The problem was that the `depth_msaa` texture wasn't being resolved into the `depth` texture so whenever msaa was on the `depth` would have no data in it, which pretty much breaks the dof stuff.

il make a pull request for this, as soon as I figure out how... lol
