### ISSUE TITLE
Tab close button still active even when being hidden

### ISSUE THREAD

**Issue by floppyhammer** [godotengine/godot#55407]
### Godot version

v3.4.stable.official [206ba70f4]

### System information

Windows, GLES3

### Issue description

![tab](https://user-images.githubusercontent.com/28705694/143735543-f0a1eb23-7997-4a69-9830-005a28d8a05e.gif)

### Steps to reproduce

Add a Control and a Tabs, add a script to the Tabs.
```gdscript
extends Control

func _ready():
	$Tabs.add_tab("Tab1")
	$Tabs.add_tab("Tab2")
	$Tabs.tab_close_display_policy = Tabs.CLOSE_BUTTON_SHOW_ACTIVE_ONLY

func _on_Tabs_tab_close(tab):
	print("Close button pressed for tab ", tab)
```

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/7613102/Test.zip)

**Comment by floppyhammer** [comment]
Haven't tested this in 4.0 as my graphics card isn't supported. My Vulkan API version is 1.0.39. What's the minimal version for 4.0?

**Comment by ator-dev** [comment]
Confirmed to occur in 4.0 as well, and works the same way (incorrectly) when set to `CLOSE_BUTTON_SHOW_NEVER`.
> What's the minimal version for 4.0?
I'm not sure, sorry - hopefully someone else seeing this might know, or a forum like the Discord sever is likely to have an answer.
