### ISSUE TITLE
Rendering Unicode: `Invalid unicode codepoint`

### ISSUE THREAD

**Issue by ngreve** [godotengine/godot#55410]
### Godot version

v4.0.dev.custom_build [69a194f05]

### System information

Linux

### Issue description

I'm am trying to render some math equations using the `Garamond-Math.otf` font, which comes with most LaTeX setups.

When I try to render the integral symbol (unicode `0x11091d`) I get the error message `Unicode parsing error: Invalid unicode codepoint 11091d.`

I took a quick look into the source code and found the following if condition in the corresponding functions:
```c
if (p_char >= 0xd800 && p_char <= 0xdfff) || (p_char > 0x10ffff) {
   print_error("Unicode parsing error . . . ");
}  else {
 . . .
}
```

Where does these boarders come from? Can they be expanded? As my use case shows, unicode can be bigger than `0x10ffff` and the used `char32_t` data type implies that it is 4 bytes wide, which would be large enough to hold bigger values.

Btw, is there also a way to set unicode characters directly via the inspector text input? Currently, I am trying to set the string in the `ready()` function.

### Steps to reproduce

See minimal project

### Minimal reproduction project

[font_testing.zip](https://github.com/godotengine/godot/files/7613545/font_testing.zip)

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by bruvzg** [comment]
`0x11091d` is an invalid Unicode character. Check is correct.

The Unicode range is 0 to 0x10FFFF (see https://unicode.org/glossary/#codespace), and 0xD800-0xDFFF sub-range is reserves for suppurates that are usable only in the UTF-16. This range is a result of the UTF-16 encoding limitations.

**Comment by bruvzg** [comment]
`0x11091D` is a glyph index of the integral symbol in the specific font, not a Unicode character, which is `0x222B`.

**Comment by ngreve** [comment]
> `0x11091D` is a glyph index of the integral symbol in the specific font, not a Unicode character, which is `0x222B`.

I am an Idiot. I guess the font and unicodes behind it do work as expected ... First time actually taking a "deeper" look into fonts, sorry for the confusion.

**Comment by bruvzg** [comment]
This specific glyph is probably a variant of the symbol used in the style-set, the correct way to display it is to use `0x222B` and select style-set using OpenType features.

![Screenshot 2021-11-28 at 20 57 05](https://user-images.githubusercontent.com/7645683/143781967-abfbe1a0-84ae-44aa-8fa7-19de1ddf7110.png)

Here's default variant and SS-7 variant for example.

**Comment by ngreve** [comment]
@bruvzg The concept of Style Sets is actually new to me, so thank you for pointing that out.

I don't want to mix up things here, so I guess this is something for the proposal repository but @Calinou, do you know if there are any plans to implement a feature something like [this](https://altcodeunicode.com/how-to-use-alt-codes/), to enter unicode characters? Would be nice to simply enter character by holding `alt` and entering the unicode you need...

**Comment by Calinou** [comment]
> I don't want to mix things up here, so I guess this is something for the proposal repository but @Calinou, do you know if there are any plans to implement a feature similar to [this](https://altcodeunicode.com/how-to-use-alt-codes/), to enter unicode characters? Would be nice to simply enter character by holding `alt` and entering the unicode you need...

There doesn't appear to be a proposal for this. https://github.com/godotengine/godot/issues/2689 was opened a long time ago, but nobody opened a proposal for it.

**Comment by bruvzg** [comment]
> do you know if there are any plans to implement a feature similar to this, to enter unicode characters? Would be nice to simply enter character by holding alt and entering the unicode you need...

Alt + hex input PR - #55441 (not fully tested).
