### ISSUE TITLE
Sprites showing multiple times

### ISSUE THREAD

**Issue by Trafel** [godotengine/godot#5541]
I made a scene containing two sprites which represent mouse cursors.
Depending on the state, one sprite will hide and the other will continue to show.
The states change depending on which function is called

Now, when I launch the game and I click on a region that is supposed to call one of these function, the sprites actually changes but not the duplicates.

I've seen this bug before when I tried to change the position of a sprite but it's duplicate was staying in the 0, 0 coordinates. 

Where these duplicates come from ?

Here is the code of the mouse scene :

```
extends Node2D

var is_patch = true
var has_focus = false

func _ready():
	set_fixed_process(true)
	set_z(99)
	state_default()
	print(get_child_count())

func _fixed_process(delta):
	if is_patch:
		get_node("outline").set_global_pos(get_node("/root/main").get_mouse_pos())
	else:
		get_node("pointer").set_global_pos(get_node("/root/main").get_mouse_pos())
	
	if has_focus:
		get_node("pointer").show()
	else:
		get_node("pointer").hide()

########################
## Funcs
########################

func state_default():
	is_patch = true
	has_focus = false

func state_focus():
	is_patch = true
	has_focus = true

func state_active():
	is_patch = false
	has_focus = true
```

**Comment by akien-mga** [comment]
What are those "duplicates" you're talking about? Could you provide a minimal example project? Based on your description and code snippet, I don't understand what would be the bug.

**Comment by akien-mga** [comment]
Closing as I still can't understand what the issue would be, and it's likely a bug in the game's logic that would be better diagnosed on the forums or Q&A than on the bug tracker of the engine.
