### ISSUE TITLE
Callable 'get_object' return null

### ISSUE THREAD

**Issue by 4d49** [godotengine/godot#55414]
### Godot version

v4.0.dev.custom_build [cf7446c95]

### System information

Windows 10

### Issue description

Method <code>get_object</code> in Callable return null.

### Steps to reproduce

Create any Callable and call <code>get_object</code> method.

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/7613645/test.zip)

**Comment by KoBeWi** [comment]
Seems to happen when the Callable is typed.
```GDScript
func f():
	pass

func _ready() -> void:
	var callable = f
	prints(callable, callable.get_object())
```
`Node2D(test.gd)::f Node2D:[Node2D:29511123438]`
```GDScript
func f():
	pass

func _ready() -> void:
	var callable := f
	prints(callable, callable.get_object())
```
 `Node2D(test.gd)::f [Freed Object]`

**Comment by cdemirer** [comment]
Might be related: #52380

**Comment by DaGamingWolf** [comment]
> Seems to happen when the Callable is typed.
> 
> ```gdscript
> func f():
> 	pass
> 
> func _ready() -> void:
> 	var callable = f
> 	prints(callable, callable.get_object())
> ```
> 
> `Node2D(test.gd)::f Node2D:[Node2D:29511123438]`
> 
> ```gdscript
> func f():
> 	pass
> 
> func _ready() -> void:
> 	var callable := f
> 	prints(callable, callable.get_object())
> ```
> 
> `Node2D(test.gd)::f [Freed Object]`

This also happens with Signals when the same get_object() method is used. i've even seen this bug pop up when using get_name() on signals from typed perameters. perhaps it's cause is related to how the editor interacts with the new typed classes.

**Comment by fkeyzuwu** [comment]
same thing happening to me, just using a plain old method as a callable and .get_object() returns null

**Comment by vnen** [comment]
Can't reproduce in current master, might have been fixed along the way.
