### ISSUE TITLE
Editor crashes when alt-tabbing out of it or closing a running project

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#5542]
**Operating system or device - Godot version:**
- Arch Linux, Clang 3.8.0
- Godot Git https://github.com/godotengine/godot/commit/576a28470fce95cf0d35d5e2e1e408b4afe80e4f

**Issue description** (what happened, and what was expected):

The editor crashes when performing an alt-tab action outwards of it (when it's maximized) or when closing a project that is running (as a child process, ie. press <kbd>F5</kbd> then <kbd>Alt+F4</kbd>).

**Comment by bojidar-bg** [comment]
@Calinou `release_debug` or `debug` build?

**Comment by akien-mga** [comment]
I can't reproduce on Mageia 6, GCC 5.4.0.

**Comment by Sslaxx** [comment]
Can confirm and replicate this on Ubuntu 16.04 64-bit. Clang 3.8.0. Might be a compiler issue being triggered?

**Comment by bojidar-bg** [comment]
Can we have a backtrace?

**Comment by Calinou** [comment]
> @Calinou `release_debug` or `debug` build?

This is a `release_debug` build. It also happens with a `debug` build. However, I'm unable to get any backtrace with both LLDB and GDB because the "process has exited normally".

**Comment by Sslaxx** [comment]
Both times this has been reported to happen have been with Godot compiled with 3.8.0. Godot compiled with GCC 5.4.0 (apparently) has no issues. We need to determine if this is a Clang-related issue or something else.

No backtrace is given by Godot, but dmesg reports this:
traps: godot.x11.tools[22231] trap invalid opcode ip:eea674 sp:7fa53bcb3800 error:0 in godot.x11.tools.64[400000+293f000]

**Comment by supaiku-o** [comment]
I can reproduce the issue with any project, but only once I got the following error, that's why I'm not sure if it's relevant:

`
ERROR: get: Condition ' !elem ' is true. returned: __null
   At: core/rid.h:146.
ERROR: texture_allocate: Condition ' !texture ' is true.
   At: drivers/gles2/rasterizer_gles2.cpp:902.
ERROR: get: Condition ' !elem ' is true. returned: __null
   At: core/rid.h:146.
ERROR: texture_set_data: Condition ' !texture ' is true.
   At: drivers/gles2/rasterizer_gles2.cpp:958.
`

**Comment by Sslaxx** [comment]
@supaiku-o - what compiler are you using, what OS?

**Comment by Calinou** [comment]
I can't reproduce this anymore with https://github.com/godotengine/godot/commit/628b0a9375814bc811820f073df5f102bdb049fc, with the exact same setup (same compiler, same OS, same `release_debug` mode).

**Comment by Sslaxx** [comment]
@bojidar-bg - might have been some compiler issue being triggered too. Sometimes it's hard to judge these things.

**Comment by Calinou** [comment]
This is an old issue, which is very likely to be fixed by now.
