### ISSUE TITLE
AnimationPlayer `RESET` track is not created (or properties added) if used Right Click `Insert Key` in timeline. 

### ISSUE THREAD

**Issue by Amatrelan** [godotengine/godot#55438]
### Godot version

v3.4.stable.arch_linux

### System information

Linux, x11, nvidia

### Issue description

`RESET` animation track is not created if in timeline `right click` -> `Insert Key` is used. 
It doesn't also work if this way to add is used even if `RESET` track is there.
Seems to be that RESET track creation and property adding is not called if this way key frame is inserted.

Expected to be created as pressing `Key` button in properties list.

### Steps to reproduce

- Create empty project
- Add any node as root
- Add AnimationNode as child
- Create new animation
- `Add track` any property
- Right click on timeline to add Key frame

RESET track is not created. Even if RESET track is created before it won't add new properties to it.

With min project:
- Open project
- Select AnimationPlayer
- **Right click** in timeline of modulate track
- `Insert key`

And there is not RESET track

### Minimal reproduction project

[AnimationPlayerResetTrackProblem.zip](https://github.com/godotengine/godot/files/7618134/AnimationPlayerResetTrackProblem.zip)

**Comment by Calinou** [comment]
cc @RandomShaper

**Comment by KoBeWi** [comment]
I think the reason why it wasn't added is that RESET animation is optional and by default it needs to be confirmed. Now imagine you get confirmation dialog every time you try to add a key. It works from the inspector, because the confirmation appears when the track doesn't exist yet.
