### ISSUE TITLE
Applying root motion as in the official demo gives a velocity which depends on the project physic frames per second.

### ISSUE THREAD

**Issue by jcarlosrc** [godotengine/godot#55449]
### Godot version

3.4 stable

### System information

Windows 10

### Issue description

I am using root motion to apply velocity as in the official third person shooter demo (basically a copy & paste solution) as seen in the picture. However, the resulting velocity depends on the physic iterations per second of the game. It seems that _get_root_motion_transform()_ is returning an absolute value which does not need to be divided by delta. The problem is that I can see that it actually works as expected on the demo provided by the godot team.

<img width="539" alt="root_motion_screeshot" src="https://user-images.githubusercontent.com/8985409/143916294-eabf40d8-b6e7-4dc2-ac38-9833d5a4bfcd.png">

### Steps to reproduce

Load the minimal project attached. Pressing Enter changes between 15 and 60 physic frames per second. The resulting movement is clearly different. 60 fps gives an about 4x faster movement.

### Minimal reproduction project

[BugReportRootMotion.zip](https://github.com/godotengine/godot/files/7620149/BugReportRootMotion.zip)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/53752 (likely the same cause).

**Comment by jcarlosrc** [comment]
It was my fault. Seems that we have to specify which delta value the animation tree uses (physics, idle or custom) so that setting to Physics did resolve the problem. Thanks.
