### ISSUE TITLE
draw_polygon() is unaffected by Node's opacity

### ISSUE THREAD

**Issue by brachna** [godotengine/godot#5544]
**Operating system or device - Godot version:**
Windows 8.1 x64 - Godot 2.0.3 (stable)

**Issue description** (what happened, and what was expected):
Primitive drawn using draw_polygon() is unaffected by Node's opacity.
From top to bottom:
draw_line()
draw_rect()
draw_polygon()
![draw_polygon_opacity_bug](https://cloud.githubusercontent.com/assets/5756107/16559497/e6f6272c-41f5-11e6-9be2-7a6722a65f95.jpg)

**Steps to reproduce:**
1. start new project, add Node2D node as root, save scene, set it as main.
2. add new script to Node2D root node
3. paste this into script:
func _ready():
	update()

func _draw():
	var offsetX = 20.0
	var offsetY = 20.0
	var size = 100.0
	var color = Color(1.0,0.0,0.0)
	
	draw_line(Vector2(offsetX, offsetY), Vector2(offsetX + size, offsetY), color)

	draw_rect(Rect2(Vector2(offsetX, offsetY + size), Vector2(size, size)), color)
	
	var pos = [Vector2(offsetX, offsetY + size * 3), Vector2(offsetX + size, offsetY + size * 3 ),
	           Vector2(offsetX + size, offsetY + size * 4), Vector2(offsetX, offsetY + size * 4)]
	draw_polygon(pos, [color, color, color, color])
4. save script.
5. set root Node2D node's opacity to 0.5.
6. run scene.

**Link to minimal example project** (optional but very welcome):
http://www39.zippyshare.com/v/fM6dEDl2/file.html

**Comment by bojidar-bg** [comment]
Can confirm using the project given.

**Comment by timoschwarzer** [comment]
I think this is related to #5151

**Comment by rgrams** [comment]
and PR #5207 presumably

**Comment by brachna** [comment]
Yes, seems to be the same. I just didn't search for Polygon2D, but draw_polygon instead.
Will PR #5207 be included in 2.1?

**Comment by timoschwarzer** [comment]
Probably not in 2.1, only in 3.0 since the renderer will be rewritten.

**Comment by rgrams** [comment]
You can work around it with a very simple shader like:

`uniform float opacity = 1.0;
COLOR.a *= opacity;`

If you want child nodes to be affected, you can check their "Use Parent" material option (if you're not putting a separate material on them of course.)

**Comment by akien-mga** [comment]
This seems to be the same bug as #5151, closing as duplicate and I'll add a mention there about the infos in the OP.
