### ISSUE TITLE
Undo skips Spinbox increment/decrement operations

### ISSUE THREAD

**Issue by LameGod** [godotengine/godot#5545]
**Operating system or device - Godot version:**
Windows 7 x64 - 2rc1

**Issue description** (what happened, and what was expected):
After using the increment/decrement buttons on a spinbox multiple times, using undo will only negate the most recent interaction, then skipping other spinbox interactions and reverting prior actions.

**Steps to reproduce:**
In the editor place a TextureFrame.
Perform a series of undoable actions.
In the inspector, change an attribute of the TextureFrame by clicking on a Spinbox increment button several times.
Perform several undo operations, the most recent increment will be undone, then the prior series of undoable actions will be undone, skipping over the initial Spinbox increments.

**Link to minimal example project** (optional but very welcome):

**Comment by neikeq** [comment]
I think this happens because LineEdit only has one level undo. I am not sure if there is a reason for this... Ping @reduz

**Comment by akien-mga** [comment]
This seems to work fine in the current master branch (c48027af).
