### ISSUE TITLE
Can't Edit Tileset After Changing Scene

### ISSUE THREAD

**Issue by HanzCEO** [godotengine/godot#55459]
### Godot version

3.4.stable

### System information

Windows 10 64bit

## Video Preview
https://user-images.githubusercontent.com/40712686/143982503-9f09a3ad-9f35-46a1-b767-481401c27931.mp4

## Expectation
I can click tile from tileset editor like normal

## Reality
I can't click tile from tileset editor

### Steps to reproduce

1. Edit tileset A from scene A
2. Change to scene B
3. Edit tileset B from scene B
4. Change to scene A
5. Edit tileset A from scene A

**Comment by hafizosina** [comment]
i got same problem

**Comment by boruok** [comment]
fixed in **Godot_v3.4.1-rc1** by https://github.com/godotengine/godot/pull/55059

**Comment by HanzCEO** [comment]
Thank you!

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/52760.
