### ISSUE TITLE
Button focus text color

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#5546]
Currently you can set the hover text color for a button, but this only triggered by the mouse. It would be nice to have also a focus text color to when the button have the focus gained via keyboard/joystick.

**Comment by toby3d** [comment]
It is strange that this fix was not in the version 2.1 :confused:

**Comment by akien-mga** [comment]
Not strange, just the natural consequence of nobody having fixed it :)

**Comment by bvbfan** [comment]
https://github.com/godotengine/godot/pull/6739

**Comment by volzhs** [comment]
is it resolved?

![button](https://cloud.githubusercontent.com/assets/8281454/21394804/6a5e3fb0-c7dd-11e6-84cb-208e72307bcc.gif)

tested with current master head. (2c8a1729152f5bcb1cb81d24b1e642634bff7174)

**Comment by bojidar-bg** [comment]
Thanks @volzhs :smiley:
