### ISSUE TITLE
Hidden Objects constantly send their Unused Data to VRAM

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#55475]
### Godot version

v4.0.dev.20211117.official [175690957]

### System information

Windows 11, Vulkan, Nvidia Quadro K2000 461.92

### Issue description

in VRAM limited scenarios, the GPU seems to constantly be shuffling memory (VRAM<->RAM) even when the actual amount of VRAM required to render the scene is significantly lower then what is stored in Memory, Resulting in constant Heavy Stuttering and generally Poor performance.

This means that having things (such as unused textures) in memory when VRAM is limited, because instead of just sending it to RAM as Shared Memory until it is needed, thereby freeing up the VRAM needed to Render the scene, it seems to just send the unused memory back from Shared Memory down to the GPU, which would be fine, if the GPU did have VRAM it could afford to store the data while still having everything that is actually needed for rendering the scene.

### Steps to reproduce

Create several meshes, each with a Different Massive Texture, keep doing so until the Textures combined are well over your VRAM size, so that both VRAM and RAM are used to store them
Hide all but 1 of the Meshes
Run the Scene

**Comment by Calinou** [comment]
This is expected behavior
. Texture streaming is the only way to avoid this, and it's only planned to be implemented in a future 4.x due to time constraints.

**Comment by clayjohn** [comment]
To add to this. We rely on AMD's Vulkan Memory Allocator to handle memory allocation to avoid doing it all manually. 

From your post, it sounds like you are intentionally flooding the GPU's VRAM so VMA has no choice but to store texture data on system RAM and then you are experiencing poor rendering performance as a result. Is that fair to say?

Could you clarify what you would like to see happen? Are you proposing that Godot should de-allocate VRAM for hidden objects?

**Comment by mrjustaguy** [comment]
If more VRAM is allocated then what the GPU has to offer, yeah, I'm proposing that Godot should probably have a way to de-allocate VRAM for objects that are hidden. Ideally it'd just mark the Resource to be stored in RAM and if an Object becomes visible, allocate it back to VRAM.

I mean there probably should be some way to prevent the needless memory dancing when you're using for example:
1GB out of 2GBs of VRAM to render a Scene at a given period
Total Memory of all the Loaded assets is 4GBs
Currently the 3GBs that are not used to render the scene are just being aimlessly cycled around
What it Should do is fill the rest of the VRAM with the things that are needed to render the Scene now, and use the rest to store the other assets that were used in the frames before, until that memory gets replaced with more relevant data, sort of like how cache works

The logic I'd use would go as follows:
Before starting a Render pass Check if there is more VRAM allocated then there is VRAM in the system (add some margin by how much it's over till this starts probably), check what the Camera sees, and mark all the resources for Use.
When the Check is done, Move VRAM to RAM for Objects that have been cut, until all needed resources for rendering are in VRAM (Prioritizing cutting smaller resources over larger to save on bandwidth makes sense, as you're more likely to need a handful of resource changes from frame to frame and cutting half a gig of small resources and only needing to call back a little bit is better then cutting half a gig of big resources and ending up calling most of them back, despite the fact that the same number of resources have been called back in both scenarios)
