### ISSUE TITLE
AnimationPlayer RESET track does not automatically clean up tracks that were removed

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#55489]
*Related to https://github.com/godotengine/godot/issues/55438.*

### Godot version

3.4.stable, 4.0.dev (89a4ab6c1)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 470.74)

### Issue description

In the editor, the AnimationPlayer RESET track does not automatically clean up tracks that were removed. This can cause old keys to linger and cause errors when opening scenes in the editor: https://godotforums.org/discussion/28172/i-get-bombarded-with-error-messages-does-anyone-knows-what-the-mean-and-how-to-get-rid-of-them

cc @RandomShaper, as they implemented the animation reset track feature.

### Steps to reproduce

- Add an AnimationPlayer node.
- Add another node to animate (such as a Sprite).
- Create a new animation in AnimationPlayer.
- Click on a key icon in the inspector to animate a property. Ensure **Create RESET Track** is checked in the confirmation dialog.
- Remove the track in the animation.
- Notice the RESET animation still has a track for the removed track.

### Minimal reproduction project

N/A

**Comment by rcorre** [comment]
@RandomShaper are you still planning to work on this one? I can take a look if not.

**Comment by RandomShaper** [comment]
It's in my ultra long TO DO list.
