### ISSUE TITLE
GPUParticlesCollisionHeightField clips particles to particle direction most outer collision

### ISSUE THREAD

**Issue by CrezyDud** [godotengine/godot#55498]
### Godot version

v4.0.dev.custom_build [cf67f18ce]

### System information

Linux, Vulkan

### Issue description

the particle get clipped to the direction's mot outer collision

*This **ONLY** Happend with GPUParticlesCollisionHeightField*
(which is weird)

### Steps to reproduce

|
v

### Minimal reproduction project

[particle_bug.zip](https://github.com/godotengine/godot/files/7628948/particle_bug.zip)

**Comment by clayjohn** [comment]
Could you please provide a little bit more information? What do you mean by a "direction's most outer collision"?

**Comment by CrezyDud** [comment]
take a look at the reproduction project and play around

**Comment by CrezyDud** [comment]
it explains it better than i ever would

**Comment by CrezyDud** [comment]
> Could you please provide a little bit more information? What do you mean by a "direction's most outer collision"?

##+##  particles
##-##  collision
#####
##^##  particle emitter emitting upwards
##-##  collision

**Comment by CrezyDud** [comment]
*maybe* it's in the name `HeightField`

**Comment by clayjohn** [comment]
Are you trying to say that you have particles emitting underneath one occluder but above another and you want the particles to collide with the lower object?

Keep in mind the heightfield collision uses a heightfield internally so it only captures the tallest collider in the y direction. It is very useful for global effects like rain and snow. But it doesn't work if you want to do something under an occluder (e.g. smoke inside a building)

**Comment by CrezyDud** [comment]
> Are you trying to say that you have particles emitting underneath one occluder but above another and you want the particles to collide with the lower object?
> 
> Keep in mind the heightfield collision uses a heightfield internally so it only captures the tallest collider in the y direction. It is very useful for global effects like rain and snow. But it doesn't work if you want to do something under an occluder (e.g. smoke inside a building)

exactly

**Comment by CrezyDud** [comment]
any good alternative?

i want particles to have nice collisions when i punch a hole in the wall

**Comment by Calinou** [comment]
> any good alternative?
> 
> i want particles to have nice collisions when i punch a hole in the wall

Use GPUParticlesCollisionSDF, which requires baking but supports overhangs in geometry. Alternatively, use several GPUParticlesCollisionBox and GPUParticlesCollisionSphere nodes to represent your scene geometry in a basic way.

**Comment by clayjohn** [comment]
Right now you can use an SDF collider if you know where the hole will be in advance and can generate the SDF for it. Otherwise you can just arrange box occluders around the hole. 

Other engines have a mode to do occlusion based on the active camera's depth buffer. Which may be an option if someone is willing to implement it.
