### ISSUE TITLE
"toggle system console" does nothing.

### ISSUE THREAD

**Issue by nabfrew** [godotengine/godot#55499]
### Godot version

v4.0.dev.20211117.official [175690957]

### System information

Windows 10

### Issue description

in the `editor` drop down menu, there's an option to `Toggle System Console`. Selecting it does nothing.

### Steps to reproduce

Open godot. Select toggle system console. No system console will open.

**Comment by CrezyDud** [comment]
where is that option?

**Comment by nabfrew** [comment]
![ToggleSystemConsole](https://user-images.githubusercontent.com/23554500/144132989-3b7bf0c5-f44d-4cb4-bd01-34356826a6cb.PNG)

**Comment by CrezyDud** [comment]
not for me

**Comment by nabfrew** [comment]
![ToggleSystemConsole](https://user-images.githubusercontent.com/23554500/144133161-8b036633-d298-4836-ae14-66df12471529.PNG)

**Comment by CrezyDud** [comment]
how old is your version
was this removed, because it does nothing?
because i don't have that option

**Comment by pycbouh** [comment]
Duplicate of https://github.com/godotengine/godot/issues/54684, I believe. It was fixed a few days ago.
