### ISSUE TITLE
Duplicate shortcut for script editor

### ISSUE THREAD

**Issue by VardenTheOne** [godotengine/godot#55501]
### Godot version

3.4.stable

### System information

Windows 10, MacOS Monterey

### Issue description

In Windows you can duplicate line in script editor with `Crtl` + `D` when cursor is on line with no selection.
In MacOS `Crtl` + `D` does nothing.
Also there is no config for duplication in script editor in `Editor Settings` -> `Shortcuts`

### Steps to reproduce

Try to duplicate line in script editor with `Crtl` + `D` when cursor is on line with no selection in both Windows and MacOS.
Also check that duplication shortcut for script editor is absent in editor settings.

**Comment by CrezyDud** [comment]
this is a windows feature

doesn't work in linux either

**Comment by pycbouh** [comment]
On Windows and Linux it’s Control + D, but on MacOS it’s Cmd + Shift + C. This is should better match the defaults that macOS has across its apps.

**Comment by CrezyDud** [comment]
control + d just marks a word for me, or just nothing

**Comment by pycbouh** [comment]
I don’t know what you mean by this, but there are no differences between Windows and Linux default shortcuts.

**Comment by VardenTheOne** [comment]
![image](https://user-images.githubusercontent.com/57115583/144133958-b9f17a20-8077-4a4c-883a-fcdc3c397464.png)
It is in Windows. Can that shortcut be changed?

**Comment by CrezyDud** [comment]
![image](https://user-images.githubusercontent.com/84625713/144135002-9dbf2234-b57a-4006-a987-c23dfff5700e.png)
AHA
GOT IT

**Comment by pycbouh** [comment]
Ah, my bad, it seems it is called "Duplicate Selection" now, I guess it was changed and not reflected in the docs. But the rest of the point is still correct, it's <kbd>Ctrl - D</kbd> on Windows and Linux and <kbd>Cmd - Shift - C</kbd> on macOS by default.
