### ISSUE TITLE
Camera-aligned particles stop rendering past a certain amount

### ISSUE THREAD

**Issue by and-rad** [godotengine/godot#55511]
### Godot version

v4.0.dev.custom_build [56f73a7e2]

### System information

Windows 10 Pro 21H1, Vulkan, Geforce RTX 2060 (v471.68 studio)

### Issue description

3D GPU particles have a `Transform Align` property that can be used to make particles always face the camera when set to `ZBillboard`. When this is enabled, particles fail to render once the `Amount` property is set to something bigger than 7327 (this is the number that I'm getting and it might be platform- or hardware-specific. YMMV).

The same does *not* happen when the `Billboard` property on the material that renders the particle geometry is used to create camera-facing particles.

I don't know if this is expected behavior, a known limitation, or an actual bug. But I'm currently working on the 3D particle documentation and if this is in fact not a bug, I would like to include it in the docs somewhere.

### Steps to reproduce

- Open the `Main` scene in the reproduction project
- Notice how the `BillboardParams` particle node doesn't render any particles while the `BillboardMaterial` node does
- Open the `BillboardParams` node in the inspector and change the `Amount` value in the `GPUParticles3D` category:
  - anything lower than 7328 and particles are rendered
  - anything greater than 7327 and there are no particles visible from that node
- Do the same for the `BillboardMaterial` node and observe how particles are rendered fine throughout

### Minimal reproduction project

[ParticleBillboardConfusion.zip](https://github.com/godotengine/godot/files/7633515/ParticleBillboardConfusion.zip)

**Comment by clayjohn** [comment]
Closing in favour of #67717
