### ISSUE TITLE
Dock icon isn't consistant with other mac dock icons

### ISSUE THREAD

**Issue by OddHouseGames** [godotengine/godot#55513]
### Godot version

3.4 Stable

### System information

macOS Monterey 12.0.1

### Issue description

The dock icon for Godot 3.4 seems out of place/inconsistent with other dock icons:
<img width="204" alt="Screen Shot 2021-12-01 at 8 24 36 AM" src="https://user-images.githubusercontent.com/62911518/144244442-d18f7746-fa04-490a-adc4-80d485b295af.png">

Not sure if this is already updated in 4.0, but I would suggest for consistency, that the grey background behind the Godot logo be removed and the logo enlarged, to match other dock app icons.

Currently it sticks out/does not match look of other dock icons.

### Steps to reproduce

Install Godot

Navigate to app dock

**Comment by bruvzg** [comment]
<img width="403" alt="Screenshot 2021-12-01 at 16 05 50" src="https://user-images.githubusercontent.com/7645683/144248632-dd0b7468-78d0-493d-a6f9-8d9a8329074f.png">

It's consistent with other macOS apps. Originally it was larger and without background, but it was changed to match [Apple style guidelines](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/), see https://github.com/godotengine/godot-proposals/issues/1616 for previous icon change descussion.

**Comment by OddHouseGames** [comment]
@bruvzg thanks for clarification and you are absolutely correct. It looks great when in between the app icons that go by the guidelines. I guess most of the apps in my dock ignore this.
![drawing](https://user-images.githubusercontent.com/62911518/144257273-d3353dca-085e-44d8-b5de-2e354545caee.png)

I still think it makes the Godot head look really tiny, and prefer the version above artistically. But as you have correctly stated, the current one follows the guidelines and I will close this issue with this comment, thanks again.
