### ISSUE TITLE
Basis.Orthonormalized doesn't seem to be doing anything

### ISSUE THREAD

**Issue by Maveyyl** [godotengine/godot#55524]
### Godot version

3.4 mono

### System information

Windows 10

### Issue description

From what I understand, Basis.Orthonormalized should return a basis representing a rotation snapped to all 6 normal directions (or at least its composite vectors). But regardless of anything it always returns the same basis.

Here is an example basis value: ((0,5619717, 0, 0,8271565), (0, 1, 0), (-0,8271565, 0, 0,5619717))

### Steps to reproduce

```C#
Basis b = new Basis( new Vector3(0.5619717f, 0f, 0.8271565f), new Vector3(0f, 1f, 0f), new Vector3(-0.8271565f, 0f, 0.5619717f) );
Basis b2 = b.Orthonormalized();
GD.Print(b2); // same value here

```

**Comment by Calinou** [comment]
cc @aaronfranke

**Comment by kleonc** [comment]
> From what I understand, Basis.Orthonormalized should return a basis representing a rotation snapped to all 6 normal directions (or at least its composite vectors).

`Basis.Orthonormalized()` should return an [orthonormal basis](https://en.wikipedia.org/wiki/Orthonormal_basis) (if orthonormalizing is possible):

"_**orthonormal basis** for an inner product space V with finite dimension **is a basis** for V **whose vectors are orthonormal, that is, they are all unit vectors and orthogonal to each other**._"

---

> But regardless of anything it always returns the same basis.

If you'll try to orthonormalize an already orthonormal basis then yeah, it will indeed return the same basis. That's a correct behavior.

> Here is an example basis value: ((0,5619717, 0, 0,8271565), (0, 1, 0), (-0,8271565, 0, 0,5619717))

And this is indeed an orthonormal basis, these are all unit vectors which are orthogonal to each other.

---

@Calinou It's not Mono-specific, it behaves the same in GDScript. Also provided example works as it's supposed to so currently I don't see any bug in here.

**Comment by Maveyyl** [comment]
Alright so this is me not understanding what it is supposed to do, my apologies for wasting your time.
