### ISSUE TITLE
Vulkan: Clustering artifacts when using spotlights together with volumetric fog

### ISSUE THREAD

**Issue by Geometror** [godotengine/godot#55527]
### Godot version

4.0.dev (5efe80f)

### System information

Windows 10, NVIDIA RTX 3060Ti, driver 497.09, Vulkan

### Issue description

When trying to use spotlights together with volumetric fog of any kind, weird clustering artifacts appear in the area which should be illuminated by scattered light. I opened this issue because I could not reproduce #41357 anymore with Omnilights, so this issue could be used to track all bugs related to spotlights + volumetric fog.
![Screenshot 2021-12-01 202734](https://user-images.githubusercontent.com/50084500/144300568-32bedd4b-4324-443d-9e68-68785a9b7911.png)

It seems like there are two artifact types:
The stretched quads in the middle of the light cone(which are closer together the higher the value "Volume Depth" is set ) and then the "staircase" one, which seems to be caused by wrong transformations in the cluster builder (maybe). I modified the spotlight code in the volumetric_fog_process shader (basically disabled all attenuation code), which makes the light clusters clearly visible:
![grafik](https://user-images.githubusercontent.com/50084500/144302979-0d6147c5-3ba3-4881-820d-1901d00f2955.png)
![reverse_button_pressed_color](https://user-images.githubusercontent.com/50084500/144302702-f056f338-241b-432c-b3f4-bc12fa8deb0f.gif)

### Steps to reproduce

1. Create new project
2. Add spotlight and Environment node
3. Enable "Volumetric Fog"
4. Set background to a dark color and adjust the light energy until the scattered light is clearly visible.
Optional, but recommended:
5. Adjust volume depth, volume size to higher values in the project settings and set "Use Filter" to "No" to see it even clearer.

### Minimal reproduction project

[volumetric-spotlight-artifacts.zip](https://github.com/godotengine/godot/files/7636788/volumetric-spotlight-artifacts.zip)

**Comment by Geometror** [comment]
Strangely, when running the project, no clusters are drawn for the spotlight:

![grafik](https://user-images.githubusercontent.com/50084500/144333938-b5303ae1-6399-4fd1-bb22-380c6ff763f3.png)

**Comment by Calinou** [comment]
> Strangely, when running the project, no clusters are drawn for the spotlight:

Can you see clusters if you resize the window while the project running? Try making it wider/narrower.

**Comment by Geometror** [comment]
Sometimes(totally random) the clusters are drawn indeed(but same wrong transform): This also happens when resizing the editor.
![grafik](https://user-images.githubusercontent.com/50084500/144457913-d3704f0c-33e5-4319-8a53-b7b508af9f01.png)
![grafik](https://user-images.githubusercontent.com/50084500/144459194-7d8cc105-09f2-4660-a760-ac00b80ab7da.png)

**Comment by Geometror** [comment]
Could someone test this on an Apple device since it looks like in the screenshot provided with PR #55281 there are no artifacts. (which could be related to the changes in the volume_fog_process shader) 
Maybe @bruvzg can confirm/test?

**Comment by bruvzg** [comment]
I can reproduce this kind of clustering, seems like it's only happening when the camera is far from the spotlight cone, only at some angles and depends on size of the viewport/window.

![Screenshot 2021-12-03 at 12 26 29](https://user-images.githubusercontent.com/7645683/144587915-01419e3c-b40b-4e26-b1b2-543c0f8db6d7.png)

**Comment by Geometror** [comment]
Fixed with #55714.
