### ISSUE TITLE
OS.get_executable_path().get_base_dir().plus_file("program.exe") doesn't work after exporting

### ISSUE THREAD

**Issue by rageboi1011** [godotengine/godot#55558]
### Godot version

3.4.stable

### System information

Windows 10

### Issue description

So. I've been trying, and failing to make my newest project work, and I ran into this problem:
When I try to run an exe or bat file from my project, after exporting, it doesn't seem to work. I'm getting this error.

"'C:\User\[my username]\Desktop\game.exe' is not recognized as an internal or external command, operable program or batch file"

The weird thing about this is that the exe I'm trying to launch here inside the program is game.exe, but the actual exe is called "GameCartridge". Anyways, the code is in the "Steps to reproduce" section, and it's ripped straight from the godot docs. (https://docs.godotengine.org/en/latest/classes/class_projectsettings.html#class-projectsettings-method-globalize-path)
The only difference I have, is that I'm trying to launch an exe, and that's for a txt.

### Steps to reproduce

if OS.has_feature("editor"):
	gamepath = ProjectSettings.globalize_path("res://game.exe")
else:
	gamepath = OS.get_executable_path().get_base_dir().plus_file("game.exe")
OS.execute(gamepath, [], true)

**Comment by CrezyDud** [comment]
your godot version is out of date, try updating
3.4 is newest

**Comment by rageboi1011** [comment]
> your godot version is out of date, try updating 3.4 is newest

I'm going to be slightly angry if that fixes it

**Comment by rageboi1011** [comment]
> your godot version is out of date, try updating 3.4 is newest

okay just wait a bit because I have to download new export files

**Comment by CrezyDud** [comment]
if that doesn't work try setting gamepath to just
`gamepath = OS.get_executable_path()`

**Comment by rageboi1011** [comment]
> OS.get_executable_path()

I'm not trying to run the project's exe (GameCartridge.exe), but the exe that's in the project (game.exe)
also it didn't work after updating

**Comment by rageboi1011** [comment]
i tried remaking the project, and it works for some reason now.

**Comment by akien-mga** [comment]
FYI, `gamepath = OS.get_executable_path().get_base_dir().plus_file("game.exe")` points at a `game.exe` file that should be next to your Godot project exe, which is not the same location as `res://game.exe` (which would be in your PCK file).
