### ISSUE TITLE
OS.get_executable_path().get_base_dir().plus_file("hello.txt") doesn't work if outside of project folder

### ISSUE THREAD

**Issue by rageboi1011** [godotengine/godot#55562]
### Godot version

3.4.stable

### System information

Windows 10

### Issue description

I was trying to make a project where it would open an exe from the program. But it didn't work. Turns out, https://docs.godotengine.org/en/latest/classes/class_projectsettings.html#class-projectsettings-method-globalize-path only works if the exported exe is in the same folder as the txt or exe, so it can open it from there. 

### Steps to reproduce

The code is in the docs. All you need to do to reproduce the bug, is to move the exe to your desktop.

**Comment by rageboi1011** [comment]
ok i realized that it says it in the docs. there should be some way to pack the txt into the exe tho

**Comment by Calinou** [comment]
> ok i realized that it says it in the docs. there should be some way to pack the txt into the exe tho

This can be done by adding `*.txt` to the Export dialog in the non-resource export filter.
