### ISSUE TITLE
Missing visual shader material preview

### ISSUE THREAD

**Issue by dweremeichik** [godotengine/godot#55575]
### Godot version

v3.4.stable.official [206ba70f4]

### System information

Linux

### Issue description

It appears that in 3.1, you could have different inspectors open when you were editing a visual shader. This was nice because you could open up the parent ShaderMaterial and see how your changes would effect the material. I can't reproduce this in 3.4 (I'm assuming that it used to be a bug and not a feature). It would be nice however, to have the material preview available when editing visual shaders. This would also support the workflow of creating a shader as a new resource and working on it directly before applying it to an object in your scene.

Here is a GDQuest example of it "working" in 3.1: https://youtu.be/sf_Dc4ew3eM?t=485

Here are some current screenshots (showing the preview in the first one):
<img src="https://user-images.githubusercontent.com/4079608/144569466-ced344d6-04e0-456b-9235-690eb37c4e1f.png" width="250">

![image](https://user-images.githubusercontent.com/4079608/144569575-42f479a1-7a38-4732-9562-e329f6770d73.png)

### Steps to reproduce

1. Create a new shader material.
2. Create a new visual shader.
3. The shader material preview is no longer visible when the visual shader editor is open.
4. If you click the back button in the inspector to view the shader material, it closes out of the visual shader editor.

**Comment by Calinou** [comment]
cc @Chaosus

**Comment by Chaosus** [comment]
I'm working on it.

**Comment by Zireael07** [comment]
Confirming this is still an issue (also an issue for normal shader editing - I can't see the material inspector and therefore can't double check the parameters/preview while editing)

From what I can tell, also true in 4.x?

**Comment by jordanlis** [comment]
I think in 4.x you can't even see shaders preview anywhere right ?
