### ISSUE TITLE
Ability to change font size in RichTextLabel without requiring separate font resources when using DynamicFont

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#5557]
Having a `[size=(font height in pixels)]` tag for changing the font size (when using a DynamicFont) without requiring separate font resources for each size would be very helpful for things like titles.

Perhaps the font height should be settable using a percentage as well, which would then be relative to the default font size of the RichTextLabel.

**Comment by Calinou** [comment]
**Update:** This issue is still relevant as of https://github.com/godotengine/godot/commit/a1f835df771464e9db6909fd104751ccbbc1b91a.

**Comment by JustusPan** [comment]
I want to create a issue for this and then find this discussion. Strongly hoping this feature can be brought to godot  early.

I'm working on a prototype and want to create many utility components without dependency outside of godot.  And the "size of text" is a big problem for me, I can only change the size of text by tuning the rect_scale property of Control(which is not the way i expect). Supporting this tag for bbcode in godot is meaningful and helping people focus on their prototype.

**Comment by girng** [comment]
This is a good idea, I actually always thought having the extra font resources for each size was normal. But this seems like the correct way to do it

**Comment by Skullfurious** [comment]
This still isn't supported.

**Comment by Calinou** [comment]
@Skullfurious BBCode isn't a formal standard, so there is no "full" or "partial" support to speak of :slightly_smiling_face:

**Comment by asheraryam** [comment]
Not the most pleasant thing to hear but there's this PR https://github.com/godotengine/godot/pull/29762 that already does this @Skullfurious

**Comment by akien-mga** [comment]
Fixed by #42595.

**Comment by Tyrannosaurus1234** [comment]
Was this actually fixed? I'm using 3.3[.0] and the [size] tag definitely does not work, nor is it mentioned in the BBCode documentation. The [center] tag implemented in https://github.com/godotengine/godot/pull/42595 works as expected, but size does not. My apologies if I'm missing something obvious.

**Comment by akien-mga** [comment]
This is fixed in 4.0, and the fix can't be backported.

**Comment by Tyrannosaurus1234** [comment]
Aaah, I see. Thank you. 👍
