### ISSUE TITLE
Ring Axis property is always visible in ParticleMaterial

### ISSUE THREAD

**Issue by RPicster** [godotengine/godot#55589]
### Godot version

3.4 stable

### System information

Windows 10

### Issue description

In the Emission Shape settings of a ParticleMaterial, the option for Ring Axis parameter is always visible, no matter which Emission Shape was selected.

The correct behaviour should probably be to only show the property when a Ring Emitter is selected.
![ring_emitter_property](https://user-images.githubusercontent.com/9423774/144620379-2dc02b44-611b-4d8b-b07c-c833c636bf5e.png)

### Steps to reproduce

- Create a Particles2D node
- Add a ParticleMaterial resource
- Expand the EmissionShape parameter dropdown.

**Comment by akien-mga** [comment]
Fixed by #55591.
