### ISSUE TITLE
[Bullet] Sharp change in damp function when passing 1.0 mark with distro packaged Bullet (no `BT_USE_OLD_DAMPING_METHOD`)

### ISSUE THREAD

**Issue by stylemistake** [godotengine/godot#55599]
### Godot version

3.4.stable

### System information

Arch Linux, GLES3, Radeon RX550

### Issue description

I opened my project in new version of Godot (3.4), and it made all RigidBodies much stiffer to control, and experimentally I have figured out that linear_damp and angular_damp settings were to blame.

This is how I would describe the current (3.4) damp response:

![unknown-3](https://user-images.githubusercontent.com/1516236/144656349-d314cfbb-7e26-4d0e-91a4-b86dbc602f0f.png)

It should be a consistent response, a continuous curve without any sudden jumps, and it is a game breaking regression.

Jump happens at around total 1.0 mark, which is project dependent (if project settings has 0.1, then it's going to jump at 0.9 in rigidbody settings).

### Steps to reproduce

1. Create a RigidBody
2. Write a script that applies a consistent torque to it
3. Try at 0.89 angular_damp, measure terminal angular velocity
4. Try at 0.91 angular_damp, measure terminal angular velocity

It is project settings dependent, since 0.1 is the default damp and all numbers combine (in our case 0.1 + 0.9) to create the final damp number.

**Comment by Calinou** [comment]
Is this in 2D or 3D? If 3D, can you reproduce this with the GodotPhysics engine by changing the 3D physics engine in the Project Settings?

**Comment by stylemistake** [comment]
Yes, this is 3D, changing the engine does nothing.

**Comment by stylemistake** [comment]
Disregard my previous comment, this is only reproducible with the Bullet engine.

**Comment by Calinou** [comment]
cc @pouleyKetchoupp 

I remember seeing changes related to drag damping, but I thought these weren't backported to `3.x`.

**Comment by madmiraal** [comment]
The original fix was backported in #39084.

**Comment by akien-mga** [comment]
Also worth noting that Bullet was updated to 3.17 for Godot 3.4, which may have impacted this.

**Comment by madmiraal** [comment]
@stylemistake Please provide an MRP, because I'm unable to reproduce this issue. It works fine for me using both Bullet and Godot physics.
Bullet physics:
![55599-Bullet](https://user-images.githubusercontent.com/9253928/144704922-7996cada-86c2-44a8-8233-3b32bd735654.gif)
Godot physics:
![55599-Godot](https://user-images.githubusercontent.com/9253928/144704933-3144a18d-f053-422e-9eb9-275911579f7b.gif)
Sample project: [55599.zip](https://github.com/godotengine/godot/files/7653701/55599.zip)

**Comment by akien-mga** [comment]
> Arch Linux

Are you using the official Godot binary, or one packaged by Arch? This can impact the Bullet configuration.

**Comment by stylemistake** [comment]
@madmiraal Thank you for making a test project, and this is how it behaves in my environment:

https://user-images.githubusercontent.com/1516236/144746838-d4f83e53-9f13-4cdf-82d6-a094dc81a3ea.mp4

> distro packaged Bullet which doesn't define BT_USE_OLD_DAMPING_METHOD like we do for our vendored version

Can confirm, PKGBUILD for Godot unbundles Bullet and doesn't account for these defines.

**Comment by stylemistake** [comment]
Nothing to fix here, so I'm closing this.
