### ISSUE TITLE
Clicking on a blend shape crashes with Toasts

### ISSUE THREAD

**Issue by fire** [godotengine/godot#55619]
### Godot version

4.0 52b7d5fa347fb88aa016e1e30414abd01e800381

### System information

Windows 11, Nvidia 3000 series

### Issue description

Opening a glb and then clicking on a mesh blend shape menu crashes.

### Steps to reproduce

See issue description.

In 
```
void RenderingDeviceVulkan::_free_internal(RID p_id) {}
// ...
} else if (compute_pipeline_owner.owns(p_id)) {
ComputePipeline *pipeline = compute_pipeline_owner.get_or_null(p_id);
frames[frame].compute_pipelines_to_dispose_of.push_back(*pipeline);
compute_pipeline_owner.free(p_id);
} else {
ERR_PRINT("Attempted to free invalid ID: " + itos(p_id.get_id()));
}
```

Remove the else case to avoid the infinite loop that causes the crash.

### Minimal reproduction project

https://github.com/KhronosGroup/glTF-Sample-Models/blob/0bc2ad7535aba4e16fb1afba1f85fd827bbbea6d/2.0/MorphStressTest/glTF-Binary/MorphStressTest.glb

[Blend Shape Crash Game Project.zip](https://github.com/godotengine/godot/files/7653621/Blend.Shape.Crash.Game.Project.zip)

**Comment by fire** [comment]
Fixed d394cbce8.

**Comment by fire** [comment]
The crash seems to happen when I'm in debug mode and toasts are showing printing an error in vulkan of that quoted place.

**Comment by fire** [comment]
![image](https://user-images.githubusercontent.com/32321/144703562-db8eca5e-3baa-4d30-9079-0c9d44a4c3d8.png)

**Comment by lentsius-bark** [comment]
I can confirm this bug happens when I try to either see the blend shapes or click on the toast notification icon.

Turning off toast notifications fixes the issue.

Windows 11, Nvidia GeForce 1060 GTX, Godot v4.0.dev.calinou [4f298237b]

**Comment by lyuma** [comment]
Displaying toasts from a different thread might be hitting the editor thread safety issues. Let's try again after #71280 is merged.

**Comment by clayjohn** [comment]
This seems like it may have been fixed by https://github.com/godotengine/godot/pull/71553 actually which fixed a bug where we were getting deadlocks/crashes from toasts when we had shader compilation issues

**Comment by RandomShaper** [comment]
Not able to reproduce it, even without any of the aforementioned PRs (even if reverting #71553).

@fire, @lentsius-bark, are you still able to reproduce it?

**Comment by fire** [comment]
Closing due to testing.
