### ISSUE TITLE
Headless mode falsely complains about unimported resources

### ISSUE THREAD

**Issue by unfa** [godotengine/godot#55628]
### Godot version

v4.0.dev.calinou.4f298237b

### System information

Arch Linux, KDE Plasma, Radeon RX580, amdgpu driver

### Issue description

I'm trying to set up a public server fro my multiplayer game, but the `--display-driver headless` comandline option unfortunately doesn't work.

The game complains about resources not being imported, while I have just played the game from the editor, so everything is already cached.

I attach a minimal reproduction project. It works flawlessly from the editor but when I run it in headless mode I get this:

```
Test project 
❯ ../godot --display-driver headless
Godot Engine v4.0.dev.calinou.4f298237b - https://godotengine.org
 
ERROR: Failed loading resource: res://texture.jpg. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:205)
ERROR: res://Scene.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://texture.jpg
   at: load (scene/resources/resource_format_text.cpp:461)
ERROR: Failed loading resource: res://Scene.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:205)
ERROR: Failed loading scene: res://Scene.tscn
   at: start (main/main.cpp:2483)
ERROR: 1 RID allocations of type 'P11GodotBody3D' were leaked at exit.
ERROR: 1 RID allocations of type 'P11GodotArea3D' were leaked at exit.
ERROR: 1 RID allocations of type 'P12GodotSpace3D' were leaked at exit.
ERROR: 1 RID allocations of type 'P11GodotArea2D' were leaked at exit.
ERROR: 1 RID allocations of type 'P12GodotSpace2D' were leaked at exit.
ERROR: 2 RID allocations of type '6NavMap' were leaked at exit.
ERROR: 1 RID allocations of type 'N18RendererCanvasCull6CanvasE' were leaked at exit.
ERROR: 1 RID allocations of type 'N16RendererViewport8ViewportE' were leaked at exit.
ERROR: 1 RID allocations of type 'PN22RasterizerStorageDummy12DummyTextureE' were leaked at exit.
ERROR: 1 RID allocations of type 'N17RendererSceneCull8ScenarioE' were leaked at exit.
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: cleanup (core/object/object.cpp:2025)
```

### Steps to reproduce

1. Run a game in editor - works
2. Run a game in headless mode - doesn't work

### Minimal reproduction project

[Test project.zip](https://github.com/godotengine/godot/files/7654724/Test.project.zip)

First open the project in editor and play the game. You should see a rotating textured cube,
Now run the project from commandline using the `--display-driver headless` argument.

**Comment by Calinou** [comment]
cc @Faless

**Comment by kevinms** [comment]
The issue seems to be that textures saved in s3tc, etc2, .. VRAM compressed formats don't play nicely with the dummy renderer used in headless mode.

When the texture is imported, `texture.jpg.import` file is parsed and it finds the resource paths to be:
```ini
path.s3tc="res://.godot/imported/texture.jpg-82c5cf3423885067581d2eefe6b83bce.s3tc.stex"
path.etc2="res://.godot/imported/texture.jpg-82c5cf3423885067581d2eefe6b83bce.etc2.stex"
```

When the ResourceFormatImporter sees that `path.s3tc`, it checks feature flags to know if the texture format is supported by the current renderer:

```c++
	if (!path_found && assign.begins_with("path.") && r_path_and_type.path.is_empty()) {
		String feature = assign.get_slicec('.', 1);
		if (OS::get_singleton()->has_feature(feature)) {
			r_path_and_type.path = value;
			path_found = true; //first match must have priority
		}
	}...
```

In headless mode, the `RasterizerStorageDummy::has_os_feature()` gets called which always returns false.

Thought it might be something I could tackle, but I've delved too deep into the renderer and am now lost :-) Figured I'd write down what I found in case it's looks approachable by someone else!

A crappy workaround could be to reimport your texture(s) using "VRAM Uncompressed" mode, but not ideal...

**Comment by Faless** [comment]
@kevinms thanks a lot for the investigation :trophy: !
You indeed found the point of failure :+1: .

So, a simple workaround for now could be to have the dummy rasterizer return `true` for any texture format.
I'm not sure what a proper fix would look like, will probably have a better picture once we take a crack at: godotengine/godot-proposals#2756 (so we can re-export the assets in a dedicated format).
