### ISSUE TITLE
"ui_right" and "ui_up" keys do not work for focusing neighbors

### ISSUE THREAD

**Issue by lentsius-bark** [godotengine/godot#55622]
### Godot version

4.0.dev.calinou [4f298237b]

### System information

Windows 11, 1060 GT

### Issue description

As seen in the video below, both automatic and focus cannot be changed using the arrow keys (default ui controls)

https://user-images.githubusercontent.com/38346332/144704813-099bd01e-4cc0-41a8-9dba-f6fdbf1b5194.mp4

surprisingly, ui_focus_next and ui_focus_previous are fully functional. (TAB / SHIFT + TAB)

### Steps to reproduce

1. Create an empty project
3. Create buttons and put them in arbitrary locations, or in containers such as VBox/HBox/Grid
2. (optional) manually assign focus neighbors
3. run the project and click on one button
4. try to change the focused button using arrow keys (up and right do not work)

### Minimal reproduction project

[ui_focus_min.zip](https://github.com/godotengine/godot/files/7654188/ui_focus_min.zip)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/54602.

@lentsius-bark The minimal reproduction project failed to upload, as you submitted the issue before it was done uploading. Please edit your post and upload it again 🙂

**Comment by lentsius-bark** [comment]
@Calinou fixed, thanks for letting me know!

Yeah something funny must be going on behind the scenes, as with control nodes, ui_next and ui_previous are the ones that work 100% of the time.

**Comment by dalexeev** [comment]
#55169
