### ISSUE TITLE
[3.x] Input lags in Scene Tree

### ISSUE THREAD

**Issue by floppyhammer** [godotengine/godot#55632]
### Godot version

v3.5.beta.custom_build [c42e9bd58]

### System information

Windows 11, GLES3

### Issue description

v3.5.beta.custom_build [c42e9bd58]
![lag1](https://user-images.githubusercontent.com/28705694/144731147-c4153663-b115-426f-8125-279ffc71c778.gif)

v3.4.1.rc1.official [7b0801c7f]
![lag2](https://user-images.githubusercontent.com/28705694/144731149-eb7774a7-1b24-487d-a934-471f36276b2f.gif)

The yellow dot indicates my mouse click. It can be seen that in 3.4.1 a node was selected almost immediately when the dot appeared. However, there was an obvious lag in 3.5. The same occurs when using keyboard to navigate.

### Steps to reproduce

Grab the test project, select a node in the Scene Tree and feel the lag.

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/7655101/Test.zip)

**Comment by pycbouh** [comment]
> v3.5.beta.custom_build

If you mean you built it yourself, which flags did you use?

**Comment by floppyhammer** [comment]
@pycbouh Sorry, my mistake. I negligently used the debug flag. I just tested with the release flag, and no such a lag occurs.

**Comment by Calinou** [comment]
We should look into updating the GUI immediately, and updating the inspector with a 1 or 2-frame delay (whichever works) to make sure the selection stylebox can be displayed at the right place as soon as possible.
