### ISSUE TITLE
Reset track not created with animation nodes from 3.3.x

### ISSUE THREAD

**Issue by securas** [godotengine/godot#55634]
### Godot version

3.4 stable

### System information

windows 10

### Issue description

When using animation nodes created with previous godot versions (3.3.x), the RESET track is not created and there is no way to create it in the editor.

### Steps to reproduce

Open any project from a previous Godot version that has an animation player node and an animation.
The minimal reproduction project was created in 3.3.3 and should be suitable for testing.

### Minimal reproduction project

[2021_12_05_TestAnimationPlayer_3.3.3.zip](https://github.com/godotengine/godot/files/7655176/2021_12_05_TestAnimationPlayer_3.3.3.zip)

**Comment by KoBeWi** [comment]
> there is no way to create it in the editor.

There is. Just manually create an animation called RESET and keyframe any default value you want.

**Comment by securas** [comment]
Fair enough. Still a bit silly not to have this implemented in the editor.

**Comment by Calinou** [comment]
The issue is that when you open an old project, the editor can't know which value should be considered "initial" for the purposes of the RESET track.

**Comment by securas** [comment]
That is a fair point. I would suggest creating a reset animation based on
the starting conditions of the selected animation.

**Comment by KoBeWi** [comment]
Maybe a right-click option for keyframes "Create RESET Value".

**Comment by securas** [comment]
Would be great! In either case, having nothing as is now and possibly reverting this issue to documentation may generate some confusion.
