### ISSUE TITLE
"Lookup Symbol" goes to the correct line, but does not switch opened file

### ISSUE THREAD

**Issue by Frixuu** [godotengine/godot#55644]
### Godot version

4.0.dev (8c5e58ed74b9570059d23868eea97f8d8fad1727)

### System information

Windows 10

### Issue description

If the target of "Lookup Symbol" is in a .gd file, the editor should open that file and go to the symbol declaration.

Instead, when the symbol is found in some other file, the cursor moves to the line where the symbol is, but in the currently opened file.  
This is true when the target has an opened tab (the editor does not switch tabs) or when it does not (the editor does not open any new tabs).

_Seems to be applicable only to 4.0, as in 3.4.stable the Lookup Symbol does not appear to move the cursor at all._

https://user-images.githubusercontent.com/19916543/144759902-6438cc49-f92b-4be1-be55-6920539fdf82.mp4

### Steps to reproduce

Open the attached project. Open ```Bar.gd``` in the Script tab. Click on 'Lookup Symbol' in the context menu.

### Minimal reproduction project

[reproduction.zip](https://github.com/godotengine/godot/files/7656480/reproduction.zip)

**Comment by timothyqiu** [comment]
Not sure why, but if you drop `class_name Foo` and replace `Foo` with `preload("res://Foo.gd")` in `Bar.gd`, clicking `do_work` works correctly.

**Comment by cdemirer** [comment]
I located the issue.

The editor asks for the symbol here:
https://github.com/godotengine/godot/blob/e8082003f19ad8d98b6b2f74f64f4eaa7fe86353/editor/plugins/script_text_editor.cpp#L766

Eventually, the information is returned here:
https://github.com/godotengine/godot/blob/188e08307ee79920815ad4e5df2a7d2a60c649a0/modules/gdscript/gdscript_editor.cpp#L2807-L2813

But the editor doesn't know about `result.class_path`, and only looks for a `result.script`, so it takes the fallback path:
https://github.com/godotengine/godot/blob/e8082003f19ad8d98b6b2f74f64f4eaa7fe86353/editor/plugins/script_text_editor.cpp#L769-L777
