### ISSUE TITLE
Multimesh.set_instance_color() don't seems to work

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#5565]
**Operating system or device - Godot version:**
Godot 2.1 alpha, 628b0a9375814bc811820f073df5f102bdb049fc commit

**Issue description** (what happened, and what was expected):
Apparently `Multimesh.set_instance_color()`  don't seems to work. I looked at c++ code and I found place where it's used in `rasterizer_gles2.cpp`: https://github.com/godotengine/godot/blob/master/drivers/gles2/rasterizer_gles2.cpp#L2997 it seems in this line multimesh is added to `_multimesh_dirty_list` which is later resolved at: https://github.com/godotengine/godot/blob/master/drivers/gles2/rasterizer_gles2.cpp#L4278
I'm not sure but it looks like the color information is not used at the place where he is resolving `_multimesh_dirty_list`. 

**Steps to reproduce:**
1. Setup our own multimesh instance and use `set_instance_color` method
OR
1. Download sample project
2. Open `MeshParticles.tscn`
3. Run

**Link to minimal example project** (optional but very welcome):
[MultimeshTest.zip](https://github.com/godotengine/godot/files/348634/MultimeshTest.zip)

**Comment by bojidar-bg** [comment]
Is this still valid in master? (given it was tagged for 3.0)

**Comment by reduz** [comment]
i tested this recently and it seems to work fine, in fact particles now use instancing and it works there
