### ISSUE TITLE
Lightmap display in GLES3 is broken when Generate Atlas is enabled in BakedLightmap

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#55664]
### Godot version

3.5.beta (c42e9bd58)

This issue does **not** occur in 3.4.stable.

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 470.74)

### Issue description

Lightmap *display* in GLES3 is broken when Generate Atlas is enabled in BakedLightmap:

![2021-12-06_14 50 03](https://user-images.githubusercontent.com/180032/144857878-f0e5e740-7725-4b1a-97cb-fd9c4b222271.png)

No errors appear in the console. Lightmap baking works as expected, since a EXR texture with lightmap data is generated when lightmaps are baked with Generate Atlas enabled (`Spatial.exr` in the MRP). When Generate Atlas is disabled and lightmaps are baked again, lightmaps display correctly (baked as `Cube.exr` in the MRP):

![2021-12-06_14 49 56](https://user-images.githubusercontent.com/180032/144857892-8d72d282-38bc-4748-97d3-6b3303437f41.png)

This issue does not affect GLES2 which doesn't support lightmap atlases.

### Steps to reproduce

- Create a mesh in Blender and export it as glTF (required for UV mapping).
- Configure the bake mode in the glTF's import options to **Gen Lightmaps** and click **Reimport**.
- Add a BakedLightmap node.
- Add an OmniLight with bake mode set to **All (Direct + Indirect)**. This makes the issue more visible than the default **Indirect** bake mode.

### Minimal reproduction project

[test_lightmap_atlas.zip](https://github.com/godotengine/godot/files/7661134/test_lightmap_atlas.zip)

**Comment by Calinou** [comment]
I bisected the regression to commit 4c710780d49f850261cf7cb3ca361002e635e592. cc @RandomShaper

**Comment by akien-mga** [comment]
Fixed by #55676.
