### ISSUE TITLE
Object::get_property_list don't include script variables in References

### ISSUE THREAD

**Issue by TheHX** [godotengine/godot#5566]
**Issue description**:
The function `Object::get_property_list` don't include export and normal script variables, on GDScript classes that extends directly from `Reference`. The same seems to happens on classes that inherit from `Object`. But for example when the script extends from `Resource` the function works normally.

**Steps to reproduce:**
1. Run the example project.
2. Press the "Reference" button (Empty output).
3. Press the "Resource" button, the variables appears on the output, event if the only difference between the two scripts is the inheritance.

**Link to minimal example project**:
[reference_property.zip](https://github.com/godotengine/godot/files/348710/reference_property.zip)

**Comment by Zylann** [comment]
Related to https://github.com/godotengine/godot/issues/5146

**Comment by TheHX** [comment]
Checking the ```Object``` source code looks like there's a virtual function [```Object::_use_builtin_script```](https://github.com/godotengine/godot/blob/master/core/object.h#L415)(It's overriden in Node and Resource classes to return ```true```), called in [```Object::get_property_list```](https://github.com/godotengine/godot/blob/master/core/object.cpp#L453-L454) to determine if property list will have or not the script data. 

IMO the best solution for this issue is reverse the order of the property list in [Object::_get_property_list_bind](https://github.com/godotengine/godot/blob/master/core/object.cpp#L1010).

**Comment by reduz** [comment]
the _use_builtin_script function should be removed, but it will break the many property editors around the editor. This is an ancient hack that makes no more sense now. Will tag for 3.0 so we can safely remove it there

**Comment by reduz** [comment]
this was implemented in 3.0
