### ISSUE TITLE
Shader Uniform Array size limits

### ISSUE THREAD

**Issue by clayjohn** [godotengine/godot#55674]
Original Report:

I tried to use big (around 500 000 items) uniform arrays but they didn't seem to work. After narrowing down the problem it started to look like the total number of uniform items (including the items inside arrays) was limited to 4096. In addition to this, bigger types like mat4 seem to consume the available space quicker so that 1024 items already use all of it. This happens in both the editor and the running (ran from the editor) project.

Changing the sizes or contents of the arrays through "Shader Param" doesn't seem to affect anything

Tried to change setting "Rendering->Limits->Global Shader Variables->Buffer size" to see if it fixes the issue. Didn't help. Is there some other place to look for limits for these?

See attached video and sample project for more info.

If this is a (new) bug I can make an issue out of this(?)

System: Windows 10, RTX-2060(mobile), Godot v4.0.dev.custom_build [5f9e2fccc], Vulkan renderer
(btw: After changing to opengl3-renderer godot stopped showing menus, the "3d-area" was grey, menus disappeared and after selecting a node it crashed so couldn't test the opengl-renderer).

https://user-images.githubusercontent.com/50438441/144888228-691b9a84-ce1a-412c-b54b-572e0900d26e.mp4

[UniformArrayTest.zip](https://github.com/godotengine/godot/files/7662257/UniformArrayTest.zip)

_Originally posted by @GNSS-Stylist in https://github.com/godotengine/godot/issues/54657#issuecomment-986997880_

My response: 

Most discrete GPUs have a maximum uniform buffer size of 65536 bytes (including yours) Which translates to 4096 vec4s or 1024 Mat4s (which are essentially 4 vec4s). Your GPU driver will pad most data types to vec4 when used in an array (some GPUs don't add padding, but many do).

There are two things we need to do in response:

Add a warning if a user tries to add more uniforms than can fit in 65536 bytes (long term we could automatically split the uniforms up into multiple UBOs internally, or use a SSBO internally)
add documentation about data padding and size limits to the documentation page.

**Comment by Chaosus** [comment]
> Most discrete GPUs have a maximum uniform buffer size of 65536 bytes

I'm pretty sure on the mobile it's much less. Btw Godot has a function that retrieves that number from the system?

**Comment by clayjohn** [comment]
> > Most discrete GPUs have a maximum uniform buffer size of 65536 bytes
> 
> I'm pretty sure on the mobile it's much less. Btw Godot has a function that retrieves that number from the system?

Yes, most mobile support a size of only 16384. It looks like RenderingDevice has a function ``limit_get()`` which will allow you to check the limit using ``LIMIT_MAX_UNIFORM_BUFFER_SIZE`` as input
https://github.com/godotengine/godot/blob/46d384060ef20672e23b3c1ffe947ff7898ecf75/drivers/vulkan/rendering_device_vulkan.cpp#L9174 
https://github.com/godotengine/godot/blob/46d384060ef20672e23b3c1ffe947ff7898ecf75/drivers/vulkan/rendering_device_vulkan.cpp#L9218-L9219

**Comment by clayjohn** [comment]
Closed by #56153
