### ISSUE TITLE
`Node.duplicate` does not duplicate signal connections that were added by scripts

### ISSUE THREAD

**Issue by derkork** [godotengine/godot#55687]
### Godot version

v3.4.stable.mono.official [206ba70f4]

### System information

Windows 10

### Issue description

When you duplicate a node with `Node.duplicate` , it's signal connections are duplicated as well (given the default duplication flags). However this only happens for signal connections that were connected in the editor. If the signals were connected via script before duplication, these connections are not duplicated. 

I would expect all signal connections to be duplicated no matter if they were connected via script or via editor.

### Steps to reproduce

Using the attached project, open up `test_gd.tscn`. This contains this tree:

![image](https://user-images.githubusercontent.com/327257/145000689-bdd3d722-c5ca-45ba-b108-4cf083ad154d.png)

The first button has its `pressed` signal connected via the editor. The second button does not. When you start the scene the second button wil get its `pressed` signal connected via script. Then both buttons are duplicated and the script checks if the clone has the same amount of signal connections as the original. If this isn't the case, the script prints an error message.

When you run the scene you can see the error message indicating that the signals for the button which had its connections created via script are not duplicated. 

Since I first encountered this problem with C# i was thinking that this could maybe be a C# issue, so I have set up a second scene `test_cs.tscn` which does the same test in C#. However the problem occurs both in GDScript an C# so it is not C# specific.

### Minimal reproduction project

[MissingSignalIssue.zip](https://github.com/godotengine/godot/files/7667090/MissingSignalIssue.zip)

**Comment by HanzCEO** [comment]
Hello, you could set the `flag` param on `.duplicate` to `CONNECT_PERSIST` and it will work
```gdscript
scriptConnectedButton.connect("pressed", self, "_on_button_pressed", [], CONNECT_PERSIST)
```
When you listen to signal using script, it is by default uses `0` as the flag which stands for nothing.
Meanwhile, the duplication procedure code scans for `CONNECT_PERSIST` connections:
https://github.com/godotengine/godot/blob/04a9d2edb250ef266c4d0660f107301d7cfaaec7/scene/main/node.cpp#L2304-L2306

https://github.com/godotengine/godot/blob/8762d8fa5d8c4fd6ef3e44270089538dbc6d2f7c/core/object/object.h#L481-L486

Hope it helps!

**Comment by KoBeWi** [comment]
Yep, see the above comment.

**Comment by derkork** [comment]
Ah great. Thank you very much!
