### ISSUE TITLE
[HTML5] Javascript addEventListener not working ?

### ISSUE THREAD

**Issue by AlexandreHerbreteau** [godotengine/godot#55693]
### Godot version

3.4.stable

### System information

Windows10

### Issue description

Hi, 

when doing

`JavaScript.get_interface("document").addEventListener("visibilitychange", callback)`

with 

`var callback = JavaScript.create_callback(self, "_on_focus_in")`

The callback is never called.

### Steps to reproduce

Create a new project with a simple Node, an attached script with:

```
extends Node

var callback = JavaScript.create_callback(self, "_on_focus_in")
func _on_focus_in():
   print("FOCUSSSSSS IN")

func _ready():
	if OS.get_name() == "HTML5":
		JavaScript.get_interface("document").addEventListener("visibilitychange", callback)
```

Execute in HTML5 target. Open a browser and run the code: The callback is never executed, the message "FOCUSSSS IN" is never printed.

**Comment by Calinou** [comment]
For the record, this question was [crossposted](https://godotforums.org/discussion/28241/html5-signal-when-page-recover-the-focus) on the Godot forums.

**Comment by nisovin** [comment]
You need to accept the event parameter in your callback function.

**Comment by AlexandreHerbreteau** [comment]
Thanks @nisovin  !! 💯
