### ISSUE TITLE
Vector2 reports corrupted values

### ISSUE THREAD

**Issue by cgeadas** [godotengine/godot#55708]
### Godot version

v3.4.stable.official [206ba70f4]

### System information

Windows 11 and MacOS11.6

### Issue description

Vector2 reports wrong values. Example:
`print(Vector2(100.1, 99.3))`
returns:
`(100.099998, 99.300003)`
This seems related to [#50251](https://github.com/godotengine/godot/issues/50251).

### Steps to reproduce

`print(Vector2(100.1, 99.3))`

**Comment by Calinou** [comment]
This is expected behavior, as Vector2 stores 32-bit floating-point values which cannot represent `100.1` and `99.3` perfectly. To avoid this, use an Array to store the values or two separate `int` variables.
