### ISSUE TITLE
include("res://script.gd") function

### ISSUE THREAD

**Issue by alketii** [godotengine/godot#5570]
It could be really useful to part a code in several files, just like PHP include() function http://php.net/manual/en/function.include.php

**Comment by bojidar-bg** [comment]
:-1: from me, that's the worse feature some programming languages have in general, though it might be useful in some cases.

It is way better to use an autoload or "imports":
````gdscript
const ClassName = preload("res://script.gd")
var local_instance = ClassName.new()
# Or:
onready var local_instance = ClassName.new(self)

func _use():
    local_instance.do_something(1,2)
````

On a side note, wouldn't custom global functions be way more useful?

**Comment by Sslaxx** [comment]
I may be pulling this from my behind, but wasn't (isn't?) there an "extends <filename>" syntax, as well?

**Comment by bojidar-bg** [comment]
@Sslaxx doesn't count since you can't extend more than one file.

**Comment by Zylann** [comment]
I don't feel include() would be useful, I prefer to use imports. The only use case I see is when a script becomes a behemoth of 1000+ lines. But I also fight this and it can always be solved by a better code design (splitting in component nodes for example).

**Comment by vnen** [comment]
I don't see the need for custom global functions. Currently you can make a singleton with functions and use those. Much better to read `singleton.my_func()` (which I can track down) than just `my_func()` (which I can't tell where it comes from).

IMO the less access to global namespace the better.

**Comment by Zylann** [comment]
@vnen or you can preload() the script if the function is static, no need for a singleton if you don't hold any state :)

**Comment by thirite** [comment]
Custom global functions that don't require calling a singleton would be nice

**Comment by akien-mga** [comment]
Given the lack of consensus and the addition of named classes in the master branch (a3f1ee5c5), I think this is more or less settled now.

**Comment by FrederickDesimpel** [comment]
I'd still find this usefull to split a script in parts

**Comment by Calinou** [comment]
@FrederickDesimpel See https://github.com/godotengine/godot-proposals/issues/1332 and https://github.com/godotengine/godot-proposals/issues/758.
