### ISSUE TITLE
Node.replace_by leaves duplicates

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#55710]
### Godot version

3.4

### System information

Kubuntu 20.04 GLES3 Ryzan 7 5700G with Radeon Graphics

### Issue description

Node.replace_by seems to leave odd duplicates in the remote tree
```gdscript
func _process(delta):
	if  _can_shoot && InputMap.has_action(projectile_action) && Input.is_action_pressed(projectile_action):
		if  _projectile_scene != projectile_scene:
			_projectile_scene  = projectile_scene
			BULLET.replace_by(_projectile_scene.instance(), true)
			
		if  _projectile_scene != null:	
			_can_shoot = false
			emit_signal("fire")
```

![image](https://user-images.githubusercontent.com/2453707/145120775-de6ab66a-f41c-408a-9538-f148217ee392.png)

### Steps to reproduce

- download this https://github.com/Shadowblitz16/AstroWars/releases/tag/Node.replace_by-bug
- look in the remote scene tab under root/Weapon/Bullet after pressing space

### Minimal reproduction project

[See above](https://github.com/Shadowblitz16/AstroWars/releases/tag/Node.replace_by-bug)

**Comment by KoBeWi** [comment]
It's not a bug, just undocumented behavior. Seems like `replace_by` doesn't replace whole branch, but only that one node and moves all its children to the new node. In your case the two bullets will have their children lists merged.

**Comment by Shadowblitz16** [comment]
I hear that excuse `not a bug a lot` here.
Maybe instead of having weird behaviors in the engine that don't make sense you should consider fixing it.
