### ISSUE TITLE
Popup items are too easy to click accidentally

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#55712]
### Godot version

ff118d7

### System information

W10

### Issue description

![R2Zm7mXnEo](https://user-images.githubusercontent.com/2223172/145125808-66678c9c-bda1-453f-b5d8-e09e34a54a4c.gif)
See what happened here? I opened a menu, but before I managed to do anything, some option got activated, because the menu spawned under cursor.
![A86Piy3mfy](https://user-images.githubusercontent.com/2223172/145125889-79d8d53a-00a6-4a4e-915b-29a2e480478d.gif)
I get that it's possible to open menu and then release button on an item to activate it. And there is a small delay before this happens, so in theory when you simply click, the menu is not activated even if it was under cursor. But I accidentally click waay to often. The delay for release-click is too short, you hold button for 0.0001 seconds too long and you can't use the menu.

At first I thought that the problem is menus spawning under cursor (which probably shouldn't happen, but ok). However now I noticed that there is actually a delay, but it's just too short.

### Steps to reproduce

1. Try opening a menu. Best for testing are the ones in the inspector or the Edit in Animation editor
2. Notice that you fail often, because the menu spawns under your cursor and is immediately clicked as you release mouse button

**Comment by FelipeMatoba** [comment]
![hold_click_time](https://user-images.githubusercontent.com/38078218/145461020-f36711e1-4956-4ebe-8d4b-0b9486a5db64.png)
Hey, I think this can be easily fixed by increasing the delay here on scene/gui/popup_menu.cpp. I found 150 ms to be pretty confortable for a click. As a newbie, can I try making a pull request to fix this?

**Comment by KoBeWi** [comment]
@FelipeMatoba Go ahead.
