### ISSUE TITLE
Provide key combination to automatically abort execution of a Godot-built program.

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#5571]
Adventure Game Studio provides a key combination - ALT+X - that will halt the running (game) executable at any time. Perhaps Godot should provide something similar, at least for debugging purposes.

**Comment by akien-mga** [comment]
I guess <kbb>Alt</kbd>+<kbd>F4</kbd> works no?

**Comment by Sslaxx** [comment]
Apparently, not for everyone (differing window managers and the like).

**Comment by suptoasty** [comment]
It would be convenient, but you can always add an autoloaded script that does this.

**Comment by bojidar-bg** [comment]
@suptoasty unless you run a `while(true)` on the main thread.

**Comment by Hinsbart** [comment]
@boijdar_bg But in that case a built-in shortcut would likely not execute
either, would it?

Am 14.07.2016 2:17 nachm. schrieb "Bojidar Marinov" <
notifications@github.com>:

**Comment by bojidar-bg** [comment]
@Hinsbart Wel..... yeah :D

**Comment by reduz** [comment]
If you are running the game from the editor, F8 will stop it, even if the
game window is opened

**Comment by akien-mga** [comment]
> If you are running the game from the editor, F8 will stop it, even if the
game window is opened

Confirmed, so closing.
