### ISSUE TITLE
Changing default Inputs doesn't affect project at runtime

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#55721]
### Godot version

v4.0.dev.20211117.official [175690957]

### System information

Windows 11, Vulkan, Nvidia Quadro K2000 461.92

### Issue description

Project Setting Default Inputs aren't affected by changes. I haven't tested User Made Inputs, just the ones that come by default that seem to be effectively hardcoded somewhere.

### Steps to reproduce

Create an input test (Key press, using InputMap, default inputs)
F6 to run the test, trigger the input
Close it, and change input
F6 to run the test again, try to trigger the input with the new control (FAILS)
try to trigger the input with the old control (WORKS)

**Comment by akien-mga** [comment]
I think this is fixed, could you confirm?

**Comment by mrjustaguy** [comment]
tested in RC6, fixed
