### ISSUE TITLE
Directory Object broken on Windows 10

### ISSUE THREAD

**Issue by YodamanJer** [godotengine/godot#5573]
The Directory Object appears to be broken on Windows again. :(

Windows 10, Godot version 2.0.2 - 2.0.3

Attempting to check if a directory exists will always return FALSE, even if the folder/directory was just created. 

Steps to reproduce - check example program below.

http://pastebin.com/b6PEEBwi

**Comment by vnen** [comment]
This is present in 2.0.3 but was fixed in master.

**Comment by akien-mga** [comment]
Is there a safe-to-backport fix for 2.0.4, or should I leave it as is?

**Comment by vnen** [comment]
I believe these are safe to backport: 61655d6, e048d1e, ffbc2e5.

**Comment by YodamanJer** [comment]
This bug does not appear in the 2.1 alpha a user on the Godot facebook group sent me a link to, by the name of Hugo Locucio, however I see that got deleted. Was he not supposed to share that?

**Comment by akien-mga** [comment]
@YodamanJer No idea, he probably removed the link himself for some reason. You can use his builds yes, he's a trusted community member.

**Comment by akien-mga** [comment]
@vnen Those commits seem not trivial to cherry-pick (some consequent merge conflicts), so I guess I'll leave that for 2.1 which is right around the corner anyway.

**Comment by akien-mga** [comment]
I don't plan to make a newer 2.0.x version, so closing this bug. The issue is fixed in 2.1-beta.
