### ISSUE TITLE
get_loaded_locales returns duplicates for multiple translations

### ISSUE THREAD

**Issue by PoqXert** [godotengine/godot#55746]
### Godot version

3.4

### System information

Any

### Issue description

`TranslationServer.get_loaded_locales()` not checking duplicates.
For example, we have the following files in localization:
```
main.en.translation
main.ru.translation
coop.en.translation
coop.ru.translation
```
In this case `get_loaded_locales()` return `[en, ru, ru, en]`

### Steps to reproduce

Create multiple csv files.
Import it to project.
Add *.translation to Localization in Project Settings.
Use `TranslationServer.get_loaded_locales()` in code.

**Comment by RaphaelAzev** [comment]
Hi PoqXert! I tried working on this issue and followed the steps you offered to reproduce the problem.

First I added the following translation files on a brand new empty project, duplicating the i18n.ja.translation file
and renaming it as NEWTEST.ja.translation, so I would have 2 Japanese translations. 
![TranslationFiles](https://user-images.githubusercontent.com/26484801/145633730-fc8f4d88-2b2a-4917-9e62-bef0ca6a53b7.png)

I then ran ```TranslationServer.get_loaded_locales()``` and as expected from your example I received the following array:
![Test](https://user-images.githubusercontent.com/26484801/145634164-6a7071e2-96d0-48ba-87d1-278290b98ff4.png)

After messing around in the translation.cpp I got the following result with the same project and unaltered translation files:
![AfterChange](https://user-images.githubusercontent.com/26484801/145634359-2f999671-f172-4594-996e-362408159d31.png)

It now shows only one Japanese translation in the array, was this the desired result?
