### ISSUE TITLE
Inspector folding is broken in the editor following ScrollContainer changes

### ISSUE THREAD

**Issue by FelipeMatoba** [godotengine/godot#55742]
### Godot version

4.0.dev (f1e3c87244f18ab1a507b6e3637c34b2d49c1dc6)

### System information

Windows 10

### Issue description

When editing the properties of a Sprite2D's texture, the menu where they are supposed to show is too small, which makes it very difficult to select anything.

### Steps to reproduce

On a 2D scene, create a 2D node and add a 2DSprite. Through the inspector, select a texture type and then try to edit its properties. The menu that opens is not scaled properly, so you can't see its contents.

**Comment by Calinou** [comment]
Can you take a screenshot of the editor?

**Comment by FelipeMatoba** [comment]
That's the exact problem I had (didn't really know how to word it better, sorry). If that's still relevant, I'm not using a hiDPI display. Should I close this issue?

**Comment by Calinou** [comment]
> That's the exact problem I had (didn't really know how to word it better, sorry). If that's still relevant, I'm not using a hiDPI display. Should I close this issue?

This issue should be kept open, as https://github.com/godotengine/godot/issues/55726 should only be used to track the Font crash from now on.

**Comment by FelipeMatoba** [comment]
![inspector_folding](https://user-images.githubusercontent.com/38078218/145292939-fdd563e7-58c4-4fb4-a11c-4da61d3a5309.png)
Adding screenshot for reference

**Comment by Chaosus** [comment]
The material editor have similar problem:

![image](https://user-images.githubusercontent.com/3036176/145355990-bbe4aa80-68f9-4a4b-a1da-0a4e760452cd.png)
