### ISSUE TITLE
Vulkan: GPUParticles damping interacts badly with gravity, causing particles to stop

### ISSUE THREAD

**Issue by barbaros83** [godotengine/godot#55744]
### Godot version

4.0 dev nov-17 build

### System information

Solus OS

### Issue description

damping affects gravity in gpu particles in both 2D and 3D to a complete stand still, particle hangs instead of falling

### Steps to reproduce

open the project, there are 4 scenes, gpu and cpu particles for both 3D and 2D

### Minimal reproduction project

[ParticleTest.zip](https://github.com/godotengine/godot/files/7681138/ParticleTest.zip)

**Comment by QbieShay** [comment]
I believe this is intended behaviour

**Comment by QbieShay** [comment]
Bumping to 4.1 since this is a non-critical bug. @barbaros83 it would be useful for us to understand what's the intended behaviour that you had in mind that should happen instead of what happens in engine. Your issue doesn't state what's the expected behaviour so there isn't much actionable for us right now.

**Comment by Calinou** [comment]
You probably need to make damping weaker so that it doesn't counteract gravity entirely.

**Comment by barbaros83** [comment]
@QbieShay im not sure what the normal behavior is for this, but maybe if i give an example it would make more sense, so lets say you have a particle node that emits leaves, maybe the wind blowing on the edge of a roof or something, but because leaves have a large surface area, but are very light, they would lose their initial velocity very fast, so you would increase damping, but the gravitational pull would always be there, and the leaf would slowly fall down, it doesnt suspend in the air

**Comment by and-rad** [comment]
I feel like this all sounds fine. If you want to slow the fall of the leaves, why not just reduce the amount of gravity on the particle system? You can even do that at runtime.

**Comment by Calinou** [comment]
> @QbieShay im not sure what the normal behavior is for this, but maybe if i give an example it would make more sense, so lets say you have a particle node that emits leaves, maybe the wind blowing on the edge of a roof or something, but because leaves have a large surface area, but are very light, they would lose their initial velocity very fast, so you would increase damping, but the gravitational pull would always be there, and the leaf would slowly fall down, it doesnt suspend in the air

It sounds like you want per-axis damping, which can be implemented with a custom particle shader.
