### ISSUE TITLE
Document using sRGB conversion with TextureArray sampling in GLES3

### ISSUE THREAD

**Issue by jemala** [godotengine/godot#55751]
### Godot version

3.4.stable

### System information

Kubuntu 20.04, GLES3, GeForce GTX 980 (460.91.03)

### Issue description

The same texture in the same shader looks much brighter when using a TextureArray instead of the texture directly.

![image](https://user-images.githubusercontent.com/18643746/145391824-451b1db8-71a8-4603-bc2e-f6741921aaa5.png)

The cube on the left is using the texture directly and the cube on the right is using a TextureArray. The results are different, but they should look the same.

Here is how the TextureArray is being created:

```
extends CSGBox

export (Texture) var texture

func _ready():
#	material_override.set_shader_param("texture_albedo", texture)
#	print(texture.get_data().get_format())
	var textureArray = TextureArray.new()
	textureArray.create(64, 64, 1, texture.get_data().get_format())
	textureArray.set_layer_data(texture.get_data(), 0)
	material_override.set_shader_param("texture_array", textureArray)

```

And in the shader:

```
shader_type spatial;
render_mode blend_mix,depth_draw_opaque,cull_back,diffuse_burley,specular_schlick_ggx;
uniform vec4 albedo : hint_color;
uniform sampler2D texture_albedo : hint_albedo;
uniform float specular;
uniform float metallic;
uniform float roughness : hint_range(0,1);
uniform float point_size : hint_range(0,128);
uniform vec3 uv1_scale;
uniform vec3 uv1_offset;
uniform vec3 uv2_scale;
uniform vec3 uv2_offset;

uniform sampler2DArray texture_array;


void vertex() {
	UV=UV*uv1_scale.xy+uv1_offset.xy;
}




void fragment() {
	vec2 base_uv = UV;
//	vec4 albedo_tex = texture(texture_albedo,base_uv);
	vec4 albedo_tex = texture(texture_array, vec3(base_uv, float(0)));
	ALBEDO = albedo.rgb * albedo_tex.rgb;
	METALLIC = metallic;
	ROUGHNESS = roughness;
	SPECULAR = specular;
}

```

### Steps to reproduce

Please have a look at the minimal reproduction project below.

### Minimal reproduction project

[TextureArrayTest.zip](https://github.com/godotengine/godot/files/7684867/TextureArrayTest.zip)

**Comment by Calinou** [comment]
You need to add `: hint_albedo` at the end of `uniform sampler2DArray texture_array`:

![image](https://user-images.githubusercontent.com/180032/145486537-f8cd658c-3414-43b9-9481-14dc56517e2f.png)

**Comment by jemala** [comment]
Thank you Calinou, great to see you are updating the document accordingly!

**Comment by mhilbrunner** [comment]
Closed by https://github.com/godotengine/godot/pull/55772
