### ISSUE TITLE
Add usual typing shortcut keys for Mac OSX

### ISSUE THREAD

**Issue by OrenjiAkira** [godotengine/godot#5576]
Mac OSX El Capitán
Godot v2.0.3.stable.oficial

Typing in text editors in Godot needs more shortcut support when using a Mac OSX keyboard. Things like using control key in regular keyboards and jumping through words doesn't work anywhere in Godot. Mac keyboards use the alt key for that, and the command+directional jumps to the end of the line (works like both home and end keys in regular keyboards). This is not only for the code editor, but for editing node names and other attributes that require typing.

I looked for a similar issue and couldn't find one. I am sorry in advance if this is a duplicate.

**Comment by OrenjiAkira** [comment]
This is _almost_ perfect in Godot3, by the way. The only thing that still irks me is `fn+left` or `fn+right`, which jump to the beginning/end of the file instead of the beginning/end of line. Also I noticed #17981 is related

**Comment by akien-mga** [comment]
Thanks, closing this one as superseded by #17981 which is a duplicate but has more recent activity.
