### ISSUE TITLE
Godot 4: Impossible to resize panels in "SpriteFrames" menu

### ISSUE THREAD

**Issue by gustavi** [godotengine/godot#55760]
### Godot version

v4.0.dev.calinou [4f298237b]

### System information

Windows 10 64bit - Vulkan API 1.2.141 - GeForce GTX 1660 SUPER

### Issue description

Impossible to resize the SpriteFrames panels while the cursor show this possibility.

![image](https://user-images.githubusercontent.com/2736557/145445583-538b0ee2-6ca3-4bed-b07f-6a89ef0e1bef.png)

![image](https://user-images.githubusercontent.com/2736557/145446383-bb305e41-221f-4cda-9959-2f5d6101a2b7.png)

### Steps to reproduce

1. Create a new `AnimatedSprite2D`
2. Create a new `SpriteFrames`
3. Edit it
4. Try to resize panels

### Minimal reproduction project

NA (Editor related)

**Comment by Calinou** [comment]
I can reproduce this on commit 2a9dd654b but not 3.4.stable.
