### ISSUE TITLE
(solved) Weird white popping at some angles

### ISSUE THREAD

**Issue by scrscrnougat** [godotengine/godot#55780]
### Godot version

3.3.4.stable.mono

### System information

Windows 10, GLES3, Intel UHD Graphics 600 (27.20.100.8681)

### Issue description

https://user-images.githubusercontent.com/82517019/145540474-ea05b98d-bda6-45d0-b855-f8281a14dc75.mp4

### Steps to reproduce

I have two seperate house scenes, and either one has the walls white while the other one is okay and vice versa.

**Comment by Calinou** [comment]
@scrscrnougat 
Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by akien-mga** [comment]
You can also try to update your Intel drivers (from the Intel website directly, not your OEM) to the latest version: https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html

**Comment by scrscrnougat** [comment]
Actually, it was just a material issue and I fixed it.

**Comment by Calinou** [comment]
> Actually, it was just a material issue and I fixed it. (If only I can delete it...)

Could you describe the fix you applied on your project? It may be helpful to others stumbling upon this issue :slightly_smiling_face:
