### ISSUE TITLE
Cursor is sometimes stuck in resize shape

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#55786]
### Godot version

04cc06b

### System information

W10

### Issue description

![lH7rWFfJbA](https://user-images.githubusercontent.com/2223172/145581179-2b70eb6d-9d4f-4391-8856-d7942ba52540.gif)
Happens randomly with any dialog. It's especially jarring when you close a dialog and your cursor changes for whatever reason.

### Steps to reproduce

1. Open any non-maximized window/dialog
2. Move cursor to the border so it changes to "resize" shape
3. When you move cursor inside the dialog, it sometimes gets stuck in this shape

**Comment by Chaosus** [comment]
It still sometimes happens in editor dialogs. I need to investigate it futher.

**Comment by filipworksdev** [comment]
It happens all the time for me until I move my mouse over the title bar then it immediately resets. Windows 10 Godot 4  alpha 10 Iris Xe.

**Comment by KoBeWi** [comment]
Seems to be happening in 3.x too.

**Comment by akien-mga** [comment]
Is this still reproducible in 4.0 RC 3 or later?

**Comment by KoBeWi** [comment]
Haven't seen this in a long time.
