### ISSUE TITLE
The editor allows reparenting inherited nodes by dragging and dropping (which is normally not allowed)

### ISSUE THREAD

**Issue by CombustibleLemonade** [godotengine/godot#55789]
### Godot version

v3.4.stable.official

### System information

Ubuntu 21.04

### Issue description

When deleting nodes the current scene inherits from, one gets an alert: "Operating on nodes the current scene inherits from is not allowed". However, the nodes can still be re-parented by dragging them around. When the parent node changes, they are not recognized as an inherited node, and they can be deleted.

### Steps to reproduce

Open the minimal reproduction project. Load "Inherited.tscn". Attempt to delete the "B" node - an alert will appear, and the operation will be disallowed. 
In the scene tree, drag the "B" node on top of the "A" node. The "B" node will turn from grey to white. Attempt to delete the "B" node. No alert appears, and the "B" node is deleted.

### Minimal reproduction project

[InheritanceTesting.zip](https://github.com/godotengine/godot/files/7693780/InheritanceTesting.zip)

**Comment by Calinou** [comment]
Note: @CombustibleLemonade also managed to reproduce this on a recent `master` build (likely 2a9dd654b).

**Comment by CombustibleLemonade** [comment]
@Calinou It was this version:
![Clipboard - December 6, 2021 10_35 PM](https://user-images.githubusercontent.com/3164190/145612075-310a6c9f-f35c-4d32-a900-b62c856eccb8.png)

**Comment by cdemirer** [comment]
`Right click -> Reparent to New Node` is also affected.

`Right click -> Move Up / Move Down` is currently not allowed. Should they be allowed? The order can be broken by adding a new (non-inherited) child node and moving it up anyway.
