### ISSUE TITLE
64 bit Godot crashes when adding 3D Camera to scene

### ISSUE THREAD

**Issue by ericdl** [godotengine/godot#5579]
**Operating system or device - Godot version:**

Windows 7 x64
Intel HD 4000 graphics
Tested with 64 bit Godot 2.0.1, 2.0.2 and 2.0.3

**Issue description:**

On a Windows 7 x64 system using Intel HD 4000 graphics, 64 bit Godot crashes when adding a 3D camera to the scene, or selecting an existing 3D camera and zooming away from it.

A crash does not occur when using 32 bit Godot.
A crash does not occur when using 32 or 64 bit Godot on a system without Intel HD 4000 graphics.

**Steps to reproduce:**

1) Add a 3D Camera to a scene
OR
2) Select an existing 3D camera and zoom out/away from it

**Comment by akien-mga** [comment]
Can you provide a backtrace of the crash, or at least the output shown in the terminal?

Could you test the current development branch to see if you still reproduce the issue? See e.g. those [unofficial but trusted builds](https://archive.hugo.pro/godot/).

Are your Intel graphics drivers up to date?

**Comment by ericdl** [comment]
Problem persists in current development build.

When selecting an existing 3D camera in scene, terminal floods with:

> ERROR: SpatialIndexer::_update_camera: Condition ' !E ' is true.
>    At: scene\resources\world.cpp:129

Upon crash, GDB backtrace produced the following:

> Program received signal SIGSEGV, Segmentation fault.
> 0x000007fee9c72750 in ig7icd64!DrvSetCallbackProcs ()
>    from C:\Windows\system32\ig7icd64.dll

Installed latest (unverified) Intel graphics driver. Unable to reproduce problem after driver update. Safe to say this was a Intel graphics driver issue.
