### ISSUE TITLE
Astar2D get_closest_point() not returning closest point

### ISSUE THREAD

**Issue by cheekylions** [godotengine/godot#55794]
### Godot version

3.4.stable

### System information

Linux Mint 20.2 x64

### Issue description

Maybe I'm not clear on what get_closest_point() is for, so maybe this isn't the right tool for what I'm trying to do, but... 

Whenever I use it it always returns a point very far from my `to` input.

```
print("---")
print(global_position)
var closest_point = pathfinder.astar.get_closest_point(global_position)
print(closest_point)
var point_location = pathfinder.astar.get_point_position(closest_point)
print(point_location)
```
Prints to console:
```
(-1720, 269.333313)
180199
(-64, 116)
```
There are plenty of _much_ closer tiles to that position.

Also, the position at (-64,116) shouldn't even be a point in the astar map because it has a collision box there, and it's not even a legitimate point position.

What's weird is the node, which is repositioned after _ready, starts the scene at(0,0), and the above script returns (0,3) as the point position then.

I'm using a Tilemap in conjunction with Astar, so the point positions should be based on the cell positions, right?

The closest available tile, by my determination, to `(-1720,269.3)` is `(-1720,280)` based on the used_cells data I've passed to astar.

Am I using this function incorrectly? What is get_closest_point() supposed to be for, then?

### Steps to reproduce

What I believe to be my relevant Astar code:

```extends TileMap

onready var astar = AStar2D.new()
onready var traversable_tiles = get_used_cells()
onready var used_rect = get_used_rect()
onready var tileset = get_tileset()

func _ready():
	_add_traversable_tiles(traversable_tiles)
	_connect_traversable_tiles(traversable_tiles)

func _add_traversable_tiles(traversable_tiles):

	for tile in traversable_tiles:
		var id = _get_id_for_point(tile)
		var type_id = get_cellv(tile)
		var tile_shape = tileset.tile_get_shapes(type_id)
		if tile_shape.size() < 1: # Does not add tile if it has a collision shape
			astar.add_point(id, Vector2(tile.x,tile.y))
```

Here is the code I'm using to try to find the closest point position:

```
print("---")
print(global_position)
var closest_point = pathfinder.astar.get_closest_point(global_position)
print(closest_point)
var point_location = pathfinder.astar.get_point_position(closest_point)
print(point_location)
```

Here are a few example return values:

```
---
(0, 0)
124328
(0, 3)
```

```
(-1720, 269.333313)
180199
(-64, 116)
```

### Minimal reproduction project
[Astar Closest Point Issue.zip](https://github.com/godotengine/godot/files/7694289/Astar.Closest.Point.Issue.zip)

**Comment by Calinou** [comment]
@cheekylions Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by cheekylions** [comment]
Attached:

[Astar Closest Point Issue.zip](https://github.com/godotengine/godot/files/7694285/Astar.Closest.Point.Issue.zip)

**Comment by kleonc** [comment]
@Calinou Tested, no bug.

@cheekylions You're adding in-TileMap cell coordinates as the positions of the astar points, not actual global positions of these cells. So you'd need to convert coords to global positions and vice versa (or store global positions in the first place if that's what you want). No idea what you want/need, it's up to you. Here you have your `_on_Object_body_entered` method modified to show that eveything works just fine and you just didn't convert things appropriately:

```
func _on_Object_body_entered(_body):
	var position_tilemap_local = tilemap.to_local(global_position)
	var cell_coords = tilemap.world_to_map(position_tilemap_local)
	var closest_point_id = tilemap.astar.get_closest_point(cell_coords)
	var closest_cell_coords = tilemap.astar.get_point_position(closest_point_id)
	var closest_cell_tilemap_local = tilemap.map_to_world(closest_cell_coords)
	var closest_cell_global = tilemap.to_global(closest_cell_tilemap_local)

	var padding = 26
	print("-".repeat(60))
	print("%*s = %s" % [ padding, "global_position", global_position ])
	print("%*s = %s" % [ padding, "position_tilemap_local", position_tilemap_local ])
	print("%*s = %s" % [ padding, "cell_coords", cell_coords ])
	print("%*s = %s" % [ padding, "closest_point_id", closest_point_id ])
	print("%*s = %s" % [ padding, "closest_cell_coords", closest_cell_coords ])
	print("%*s = %s" % [ padding, "closest_cell_tilemap_local", closest_cell_tilemap_local ])
	print("%*s = %s" % [ padding, "closest_cell_global", closest_cell_global ])
```

**Comment by cheekylions** [comment]
@kleonc Ah, okay. Thank you for your help!
