### ISSUE TITLE
Some issues with the stretch mode canvas_items. Godot 4.0-dev

### ISSUE THREAD

**Issue by fagnerln** [godotengine/godot#55807]
### Godot version

Godot_v4.0-dev.20211108_linux

### System information

Xubuntu 20.04, Vulkan, AMD RX580, Mesa 21.0.3

### Issue description

I'm having some issues with the stretch mode canvas_items.

The project is developed using 1080p as target, because of the style, I don't think that is a good idea to upscale the sprite. But on my tests I noticed that when I resize the window to a lower value, it start to show some issues like a font misaligned to the outline and a sprite with problems on the sprite sheet.

The sheet is about blocks, for example, block yellow, green, blue, when the window is resized, some green blocks show a bit of blue, the yellow shows green, etc. Isn't a defined pattern. 

I tried 2d snap, no success

![ss](https://user-images.githubusercontent.com/18636416/145659161-92ca43ff-b793-4ed2-a9c6-615a94e4cffd.png)
.

### Steps to reproduce

1. Start the game
2. Resize the window until see some artifact 

### Minimal reproduction project

[Block_report1.zip](https://github.com/godotengine/godot/files/7696199/Block_report1.zip)

**Comment by Calinou** [comment]
The issue with font rendering should be fixable (cc @bruvzg), but I don't think the issue with texture rendering can be fixed when you're scaling down in a fractional manner.

**Comment by fagnerln** [comment]
> The issue with font rendering should be fixable (cc @bruvzg), but I don't think the issue with texture rendering can be fixed when you're scaling down in a fractional manner (i.e. not by an integer divisor, such as `1/2`, `1/3`, …).
> 
> Adding padding to your texture atlas will help reduce stray lines when rendering at a different scale factor, but AtlasTexture is in maintenance mode. While [there _is_ now support for padding in tilemap atlas sources](https://github.com/godotengine/godot/pull/54485), this is different from AtlasTexture and it can't be used everywhere.

I don't think that adding padding will help. On the picture attached is impossible to see, but on the demo project is possible to reproduce, when the issue is on the first sprite of the sheet, it will show a blank space between the blocks.

I know that pixel art scales really well using viewport stretch mode, but I don't know how to draw pixel art, so yeah, I'll try to do some workarounds. I'm worried about monitor with lower resolution or even smartphones.

Maybe you noticed that I used the size of the sprite to create the instances, this size is crucial to the game. 

Should I create sprites with different sizes to be used on different screens? Or it has another way to downscale it safely?

**Comment by Calinou** [comment]
> I'm worried about monitor with lower resolution or even smartphones.

Smartphones have very high DPI, which means scaling issues of this kind are hardly noticeable.

**Comment by fagnerln** [comment]
OK.

My idea was just to create some condition, for example, if the resolution is >=1080p then load 64px sprites, (el)if it's >= 720 then 42px.

But as you said, is becoming less common resolutions lower than 1080. I think that I'll just stop using the sprite sheet and create individual sprites to the blocks.

Feel free to close this issue if there's not much to do.
Thank you for your time

**Comment by Calinou** [comment]
Closing, as what can be resolved was resolved by https://github.com/godotengine/godot/pull/55905.
