### ISSUE TITLE
Vulkan: PointLight2D shadows only partially appear

### ISSUE THREAD

**Issue by kezzbracey** [godotengine/godot#55806]
### Godot version

v4.0.dev.20211210.official [21b81998b]

### System information

Kubuntu 21.04, NVIDIA GTX1080, X11, nvidia-driver-470, Vulkan clustered and mobile, Intel i7-7700

### Issue description

For me only a partial pointlight2d shadow is generated, and only from certain directions:

![Screenshot_20211211_113353](https://user-images.githubusercontent.com/5533167/145657389-2387a45a-ec4e-4635-86b7-c83c1c6de227.jpg)

And no shadow from other directions:

![Screenshot_20211211_113447](https://user-images.githubusercontent.com/5533167/145657394-bd307104-f39a-4807-a3fe-bac8bd74dd00.jpg)

Directional shadows work perfectly: 

![Screenshot_20211211_113610](https://user-images.githubusercontent.com/5533167/145657416-a7737fd2-287c-4509-9875-cfc45f7c1f9e.jpg)

Same result on both clustered & mobile. Changing the occluder shape has no effect.

Have tested on the last 3 builds, and on the oldest build up on the tuxfamily download list.

### Steps to reproduce

Create a new project, make a new 2d scene and add a background (sprite or polygon2d), PointLight2d and texture, LightOccluder2d and occluder polygon. 

Turn on shadows on the light and move it around the occluder.

### Minimal reproduction project

[point2dshadows.zip](https://github.com/godotengine/godot/files/7696090/point2dshadows.zip)

**Comment by sakrel** [comment]
this call to draw_list_begin in light_update_shadow seems to clear the entire shadow atlas instead of the region it's supposed to draw to: https://github.com/godotengine/godot/blob/bdf8340e5993ec3f86e4bf1d5ede48df7d023a12/servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp#L1555-L1561

**Comment by h0lley** [comment]
this broke on Jan 25, 2021, commit 71f0b4f, where reduz' PR #45376 got merged.
unfortunately it's quite a large PR, so I can't boil it down any further.
