### ISSUE TITLE
ReflectionProbe uses default environment if the current Camera has an environment override, but no WorldEnvironment is present in the scene

### ISSUE THREAD

**Issue by cybereality** [godotengine/godot#55800]
### Godot version

v3.4.stable.official

### System information

Ubuntu 21.10 AMD 6800XT Mesa Drivers GLES3

### Issue description

The reflection probe does not seem to capture the panorama sky texture, only the default procedural sky.

![reflection_sky](https://user-images.githubusercontent.com/3398643/145623073-2ed203bf-784e-42db-a22a-b82565a2df6a.jpg)

I would expect that the reflection captures the scene as you see it on screen, including the sky texture.

### Steps to reproduce

Create a scene with some objects to reflect.
Add a panorama sky to the camera environment, all formats seem to be affected.
Add a reflective object, such as a sphere with metallic at 1 and roughness at 0.
Play the scene and see only the default sky is reflected, not the sky texture.

### Minimal reproduction project

[ReflectionProbe.zip](https://github.com/godotengine/godot/files/7694794/ReflectionProbe.zip)

**Comment by Calinou** [comment]
Additionally, you can notice that the environment lighting within the ReflectionProbe is incorrect.

**Comment by cybereality** [comment]
Actually, the shadows are correct, but for the default environment. I think if the reflection used the panorama, then the lighting would be accurate.

**Comment by Calinou** [comment]
I know why this is happening. The environment is configured on the _camera_, but this does not affect ReflectionProbes. The environment doesn't appear in the editor unless you're previewing the camera:

![image](https://user-images.githubusercontent.com/180032/145625883-dfc952a2-de18-4ec5-ac6e-577295fd4239.png)

**Comment by cybereality** [comment]
Okay, yes that works now. I wish I knew that before, and I don't see this in the documentation.

https://docs.godotengine.org/en/stable/classes/class_reflectionprobe.html
https://docs.godotengine.org/en/stable/tutorials/3d/reflection_probes.html

Neither of those pages even mention the word WorldEnvironment. So I am okay with the functionality, since it does work, but I believe this should be more clear in the docs as I spent a lot of time trying to troubleshoot this.

**Comment by Calinou** [comment]
I can reproduce this on `master` 2a9dd654b as well:

![2021-12-10_23 29 52](https://user-images.githubusercontent.com/180032/145649570-94aa75c5-3dbf-4c7d-9c21-4e69e0aaff16.png)

**Testing project for `master`:** [ReflectionProbe_1.zip](https://github.com/godotengine/godot/files/7695775/ReflectionProbe_1.zip)
