### ISSUE TITLE
No godot 4 pre-alpha opens the editor, even the last one.

### ISSUE THREAD

**Issue by SoyoTamo** [godotengine/godot#55819]
**Godot 4.0-dev. 20211210 32bits**

**Ubuntu 20.04, intel CELERON 847**

**To open or create a project the editor loading screen freezes and creates a king of artifact that freezes on the screen, after killing the process, the program cannot reopen, i must delate the file "editor_settings-4.tres" to be able to start the program again.**

**![20211210_231211.jpg](https://user-images.githubusercontent.com/95949771/145679712-d50fdfb0-3090-430c-aa98-2d67ed28902b.jpg)![20211210_231256.jpg](https://user-images.githubusercontent.com/95949771/145679721-8cd3090a-023b-4ec9-bc4f-25645ddb9fc8.jpg)**

**Comment by Calinou** [comment]
The [Intel Celeron 847](https://www.intel.com/content/www/us/en/products/sku/56056/intel-celeron-processor-847-2m-cache-1-10-ghz/specifications.html) is based on Sandy Bridge, whose integrated graphics are too old to run Vulkan or OpenGL 3.3. You will have to stick go Godot 3.x which offers a GLES2 renderer.

**Comment by SoyoTamo** [comment]
> The [Intel Celeron 847](https://www.intel.com/content/www/us/en/products/sku/56056/intel-celeron-processor-847-2m-cache-1-10-ghz/specifications.html) is based on Sandy Bridge, whose integrated graphics are too old to run Vulkan or OpenGL 3.3. You will have to stick to Godot 3.x which offers a GLES2 renderer.

How weird, because I can use 3.x with OpenGL 3.3. If so sad, I hope 4.1 will re-implement OpenGL 3.3 :(

**Comment by Calinou** [comment]
> How weird, because I can use 3.x with OpenGL 3.3. If so sad, I hope 4.1 will re-implement OpenGL 3.3 :(

Godot 4.0 will feature a GLES3 renderer for 2D: https://github.com/godotengine/godot/pull/53150

3D functionality in OpenGL will likely have to wait for a future 4.x release though.
