### ISSUE TITLE
Tooltip activation region depends on Godot window position (DisplayServer regression)

### ISSUE THREAD

**Issue by cdemirer** [godotengine/godot#55817]
### Godot version

4.0.dev after 81efebb3a

### System information

5.15.2-2-MANJARO

### Issue description

Since 81efebb3a, tooltips for some stuff appear only when the mouse has the same offset relative to them as the Godot window relative to the screen. Example: 

1. Godot in fullscreen, no offset relative to the top-left corner of the screen
![fullscreen_no_offset](https://user-images.githubusercontent.com/41021322/145678868-4ca49b05-cef6-4bff-8aa4-d3e96ce1f171.png)

2. Windowed, with some offset (due to window manager) relative to the top-left corner of the screen
![windowed_some_offset](https://user-images.githubusercontent.com/41021322/145678925-b2e0e9a2-eecf-46bf-9ab8-22cfeaed91b1.png)

3. Windowed, with some more offset
![windowed_more_offset](https://user-images.githubusercontent.com/41021322/145678938-21d88578-661c-46e1-8587-ef763cf0754e.png)

The example shows the node tree, but this also happens with entries in the filesystem, list of open scripts in the script editor, etc.
Most things in the inspector aren't affected, but some are (e.g. layer mask selection).

### Steps to reproduce

Have some nodes in the tree in editor, and hover the mouse over them. Try the same after moving the Godot window.

**Comment by jmb462** [comment]
Confirmed under Windows 10 for Tree tooltips and layers selection in inspector.

You also mentionned Popups in issue title but looks fine for me for popups even for element that have the tooltip bad offset.
Do you have an example of buggy popup ?

**Comment by cdemirer** [comment]
You're right, popups are working fine. I thought they were synonymous when I opened the issue. I'll edit the title/description now.
