### ISSUE TITLE
[4.0] Some exported variables can't revert

### ISSUE THREAD

**Issue by zaevi** [godotengine/godot#55810]
### Godot version

v4.0.dev.custom_build.b46ab8967

### System information

Win10

### Issue description

Create a node with script:
```GDScript
extends Node2D

@export var my_int : int
@export var my_int2 : int = 0 # can revert
@export var my_bool : bool
@export var my_bool2 : bool = false # can revert
@export var my_array : Array
@export var my_array2 : Array = []
@export var my_packedarray : PackedStringArray
@export var my_dict : Dictionary
@export var my_dict2 : Dictionary = {}
```

Modify these exported variables, only `my_int2` and `my_bool2` can revert:

![(NGSW2Q%TO8NR 4)6DTP(F](https://user-images.githubusercontent.com/12966814/145667580-098cc4ad-ddfa-480d-a44c-5bc10ced633e.png)

### Steps to reproduce

above

**Comment by RandomShaper** [comment]
Here's the reproduction scene if anyone wants to check:
```
[gd_scene load_steps=2 format=3 uid="uid://6hvr3tuy5wyi"]

[sub_resource type="GDScript" id="GDScript_o7mr4"]
script/source = "extends Node2D

@export var my_int: int
@export var my_int2: int = 0
@export var my_bool: bool
@export var my_bool2: bool = false
@export var my_array: Array
@export var my_array2: Array = []
@export var my_packedarray: PackedStringArray
@export var my_dict: Dictionary
@export var my_dict2: Dictionary = {}
"

[node name="Node2D" type="Node2D"]
script = SubResource( "GDScript_o7mr4" )
my_int = 1
my_int2 = 1
my_bool = true
my_bool2 = true
my_array = [1]
my_array2 = [1, 2, 3]
my_packedarray = PackedStringArray("", "", "")
my_dict = {
"a": false
}
my_dict2 = {
"a": 0,
"b": Color(0.235294, 0.505882, 0.341176, 1)
}
```

**Comment by RandomShaper** [comment]
By adding some additional sanity to the code that determines default property values, this gets fixed (see the PR), and the fix makes sense by itself.

However, I'm not sure if it's correct that GDScript returns `null` as the default value of typed exported properties, at least for primitive types (in 3.x it returns a sensible default for the type of the property). @vnen, what do you think?
