### ISSUE TITLE
Strange behaviour of collision shapes

### ISSUE THREAD

**Issue by BenjaDev** [godotengine/godot#5582]
Windows 8.1, Godot 2.0.3

**Issue description** (what happened, and what was expected):
I was playing around with some collision shapes, 'cause I had a bug in my game: a destroyable box stood on a static body. Both of them had a collision shape, the box had a capsule-shape and the static body a sphere shape. So I tried other shapes to fix the bug and I noticed a strange behaviour: 
A capsule shape stays on a capsule shape.
A capsule shape stays on a sphere shape. 
But a box-shape falls from a sphere or capsule shape. It looks kinda wrong to me, if you would put a ball on a ball, the ball shouldn't stay on top of the other. Same with capsules.

Steps to reproduce:
Make a new scene, create some testcubes, giv'em some shapes and play around.

**Comment by timoschwarzer** [comment]
I think this is depending on where the center of mass is.
If you have a capsule with a center of mass at the bottom, it will stay on almost every surface.
Does it fall down when you set friction to zero?

**Comment by BenjaDev** [comment]
is it possible to set the center of mass? I think, per default it should be in the center of the model? and why doesn't the box-shape fall from the capsule? btw, my capsule is very pointy on top ;)
friction is already zero.

**Comment by reduz** [comment]
this is fixed in head

**Comment by BenjaDev** [comment]
ah great! I'm still excited about the progresses :) THX!
