### ISSUE TITLE
Unknown localization issue (editor debugging pseudolocalization)

### ISSUE THREAD

**Issue by andersmmg** [godotengine/godot#55829]
### Godot version

4.0-dev.20211210 Latest Pre-alpha

### System information

Windows 10, GTX 1650

### Issue description

Unknown issue with localization, things seem almost readable but not really
![Screenshot 2021-12-11 095907](https://user-images.githubusercontent.com/16022203/145685076-dced8052-6882-46d1-8c04-48129814b19e.png)

### Steps to reproduce

Just opened the latest pre-alpha

**Comment by Calinou** [comment]
You most enabled pseudolocalization in the editor settings. It's disabled by default, so it's very likely that you enabled it at some point.

**Comment by andersmmg** [comment]
It was turned on, and turning it off fixed this. As far as I know, I've never turned it on though! Could have been an accident I guess but I don't think it's likely I turned it on myself. Hmm.

**Comment by akien-mga** [comment]
It's properly defined as `false` so the most likely explanation would be that you turned it on by mistake.

Otherwise, it would mean that there's a much deeper bug where values get wrongly initialized (which is possible too).

**Comment by andersmmg** [comment]
Okay I've tried to do some testing and I can't find anything helpful lol. Renaming the editor settings file so it create a new one did not bring any similar issue back, and the setting doesn't appear in any of the settings files besides the one from when the issue appeared, though I assume Godot 4 doesn't ever reference the previous version settings files anyway.
