### ISSUE TITLE
Shader's TIME is not being affected by global time scale

### ISSUE THREAD

**Issue by timoschwarzer** [godotengine/godot#5583]
**Operating system or device - Godot version:**
Linux / 2.0.3

**Issue description**
A shader's `TIME` variable is not being affected by `OS.set_time_scale()`.
I don't know if this is by design, but I think when I set a global time scale, it should affect everything.

**Steps to reproduce:**
Make a shader that makes use of `TIME` and change time scale via `OS.set_time_scale()`

**Comment by reduz** [comment]
ah, it could be affected, just never thought of it

**Comment by timoschwarzer** [comment]
It would be great if that could be implemented.
It's useful when you have a shader that moves the texture on a sprite, and then do a slow motion effect by setting time scale < 1.

**Comment by timoschwarzer** [comment]
Could someone add this to 3.0 milestome? (as long as it's okay)
