### ISSUE TITLE
Vulkan: GPUParticles trail leave a trail towards world origin when dying

### ISSUE THREAD

**Issue by unfa** [godotengine/godot#55842]
### Godot version

4.0

### System information

Arch Linux, KDE Plasma, Radeon RX580, amdgpu driver

### Issue description

Here's what happens when the lifetime randomness is disabled (set to 0) - the problem doesn't occur:
https://youtu.be/O39GyzSdZfc

Here's what happens when lifetime randomness is at maximum (set to 1) - this produces unwanted erronous streaks:
https://youtu.be/WCQGEkOHSxM

### Steps to reproduce

1. Create a particle system with a ribbon mesh using particle trails and explosiveness at 1.0
2. Now enable life time randomness.

Observer as particles that die before the full cycle resets go back to the world origin, creating unwanted trails.

### Minimal reproduction project

[SSIL Test.zip](https://github.com/godotengine/godot/files/7697903/SSIL.Test.zip)
(the project was made to play with the SSIL feature preview).
Built from commit 0eff109a21fb5c0bd031a91c540983e77e75343b (clayjohn/Vulkan-ASSGI)

**Comment by Calinou** [comment]
Reopening, as https://github.com/godotengine/godot/pull/58549 was reverted by https://github.com/godotengine/godot/pull/58660.

**Comment by Ongnissim** [comment]
I know this issue still exists, but for anyone coming across this, my duct-tape solution has been to set the color gradient to transparent at the very end of the particle's life. I've only tried this on 2d particles, but this fix has worked well enough for now.
Hoping I remember to change it once this is fixed for real.

**Comment by Jamsers** [comment]
>I know this issue still exists, but for anyone coming across this, my duct-tape solution has been to set the color gradient to transparent at the very end of the particle's life. I've only tried this on 2d particles, but this fix has worked well enough for now.
Hoping I remember to change it once this is fixed for real.

Sadly this workaround also doesn't work because of [#53851](https://github.com/godotengine/godot/issues/53851), although I'm not sure if that bug only applies to 3D.

**Comment by Calinou** [comment]
> Sadly this workaround also doesn't work because of https://github.com/godotengine/godot/issues/53851, although I'm not sure if that bug only applies to 3D.

Did you try saving and reloading the scene after modifying the color ramp texture as outlined in https://github.com/godotengine/godot/issues/53851#issuecomment-1346178644?

**Comment by Jamsers** [comment]
>Did you try saving and reloading the scene after modifying the color ramp texture as outlined in https://github.com/godotengine/godot/issues/53851#issuecomment-1346178644?

Yes, unfortunately it doesn't work.
