### ISSUE TITLE
Editor Mouse Lag on Windows 11 / Alder Lake / High Refresh Rate Monitor

### ISSUE THREAD

**Issue by chcaru** [godotengine/godot#55845]
### Godot version

3.4.stable.official

### System information

Windows 11 (version 21H2, build 22000.348), 12th Gen Intel i9-12900KF, NVIDIA GeForce RTX 3080 (driver verrsion 497.09), 240hz monitor, both GLES2 + GLES3

### Issue description

Immediately when launching the Godot editor (without even selecting a project), I'm getting mouse lag. I get the issue when using Godot on my 240hz monitor. When I switch Godot to my second 60hz monitor, the lag seems to be gone.

When I turn on Editor/Editor settings/Interface/Editor/Update continuously, the mouse lag is gone on my 240hz monitor, but then my GPU gets pegged at 11%.

Videos here:
Note that the moues lag happens when moving the mouse in a circle. When I start selecting and moving the lag is gone.
https://photos.app.goo.gl/qRTfEj1MSP3Qqjx19 (one is normal speed, and the other is 1/4 speed to see the issue better)

### Steps to reproduce

1. Use a 240hz monitor and set Window's frame rate to 240hz as well
3. Open Godot
4. Observe mouse lag

### Minimal reproduction project

N/A. Any project will work.

**Comment by Calinou** [comment]
Does this occur if you disconnect your 60 Hz monitor entirely?

**Comment by chcaru** [comment]
> It's very surprising that this occurs, as the mouse cursor is drawn by the OS, not by Godot. Godot may change the mouse cursor shape in some occasions, but it will never draw a "software" cursor.

It's very strange, as soon as I switch to Godot from another window, the mouse lag starts. I turned on Editor/Editor settings/Interface/Editor/Show Update Spinner and noticed the lag is at its worst when the spinner is not moving.

> Does this occur if you disconnect your 60 Hz monitor entirely?

Yes

> Also, can you reproduce this on the master branch?

Yes

**Comment by goudekid** [comment]
I am also experiencing this, exact same symptoms.

Godot v3.4.2 stable mono
165hz display (I have 3 monitors, all at 165hz, all experience this issue)
RTX 2070 Super
i7 9700k
16 Gb ram

Issue only seems to happen when mousing over the godot window with godot in focus. If godot does not have focus, no lag. If godot has focus but I am mousing outside of it's window, no lag.

**Comment by goudekid** [comment]
Update: after some searching of other issues this actually seems to be an issue with variable refresh rate, rather than high refresh rate displays in general; #38219 also describes this issue, and the suggested fix of Editor Settings -> Interface -> Editor -> Update Continuously has fixed the issue for me.

**Comment by Calinou** [comment]
@chcaru Are you using a variable refresh rate monitor (G-Sync or FreeSync)?

**Comment by chcaru** [comment]
@Calinou, yes. It's a G-Sync

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/38219, which has more information about the issue at hand.
