### ISSUE TITLE
ProjectSettings' initial array/dict values can be modified.

### ISSUE THREAD

**Issue by zaevi** [godotengine/godot#55856]
### Godot version

master

### System information

Win10

### Issue description

I found ProjectSettings' initial values can be modified if they are arrays. You can get the initial array reference by `ProjectSettings.get()` and modify it. 

It causes that when you modify it in Project Settings dialog, the initial value also changes. So it cannot revert and won't be saved in `project.godot`. This related to #55721.

### Case 1:

Open `Project Settings` dialog, find `editor/script/search_in_file_extensions` property (it is `PackedStringArray`), change it and the revert button won't show.

![image](https://user-images.githubusercontent.com/12966814/145706655-62c849c7-98ee-4d52-8f76-7c82c18eb778.png)

Create a plugin to test its initial value:
```GDScript
@tool
extends EditorPlugin

func _enter_tree():
    print(ProjectSettings.property_get_revert("editor/script/search_in_file_extensions"))
    # will prints [gd, gdshader, 123, 456]
```

### Case 2:
Modify the property directly in plugin:
```GDScript
@tool
extends EditorPlugin

func _enter_tree():
    var array = ProjectSettings.get("editor/script/search_in_file_extensions")
    array.append("123")
    var init = ProjectSettings.property_get_revert("editor/script/search_in_file_extensions")
    print(array, init) # will prints the same array
```

### Case 3:

Reproduce #55721. Modify any default input action:
![image](https://user-images.githubusercontent.com/12966814/145707299-aa1fc715-2c0f-46fb-b1e6-dcec285687e2.png)

Print its initial value:
```GDScript
@tool
extends EditorPlugin

func _enter_tree():
    for event in ProjectSettings.property_get_revert("input/ui_accept").events:
        print(event)
#    will prints:
#    InputEventKey: keycode=16777221 (Enter), ...
#    InputEventKey: keycode=16777222 (Kp Enter), ...
#    InputEventKey: keycode=32 (Space), ...
# -> InputEventKey: keycode=71 (G), ...
```
That's why it can't affect the runtime....

**Comment by zaevi** [comment]
More details:

1.Modifying `Array` (not Packed\*Array) and `Dictionary` in Project Settings dialog will be fine, because the EditorPropertyArray/Dict duplicates it. It does that for undo/redo but hides this issue. Maybe duplicating all Packed*Array types can fix the issue simply.

https://github.com/godotengine/godot/blob/092a2861277e7df87aec10516d713d0bf4adba79/editor/editor_properties_array_dict.cpp#L160-L172

2.The issue is only for 4.0 because in 3.x `ProjectSettings.get()` always return a duplicated array. I'm not sure if it is expected.

**Comment by h0lley** [comment]
just to be sure: this issue is the reason why changing `editor/script/search_in_file_extensions` won't persist when restarting the editor, yes? no additional issue required?

**Comment by zaevi** [comment]
> just to be sure: this issue is the reason why changing `editor/script/search_in_file_extensions` in project settings won't persist when restarting the editor, yes? no additional issue required?

Yes, the issue caused this.
