### ISSUE TITLE
Input released event missed entirely if it happens while the main thread is very busy (DS4 only?)

### ISSUE THREAD

**Issue by EIREXE** [godotengine/godot#55850]
### Godot version

3.x (4cae48d81c783f2d124b09e9decf739aad17cbb7)

### System information

Arch Linux

### Issue description

When checking if a button is pressed or listening to input released events the engine won't fire them if they happen while the main thread is busy, in the case of the MRP it's simulated using `OS.delay_msec` but I've observed it happening in a real world situation in PH.

A video featuring what happens in PH can be found here: https://youtu.be/j5snGyoQshg
At the top, there is a display of the buttons in the controller, which are checked every frame using `Input.is_joy_button_pressed`.
As seen in the video, jstest-gtk reports that the button is indeed depressed, but Godot doesn't seem to notice this.

This happens with both accumulated input on and off, calling `Input.flush_buffered_events()` doesn't seem to cause any difference.

I used a DualShock 4 to replicate the bug, an Xbox One S controller seems to not cause the issue to happen.

Issue is confirmed to happen since at least 8723df767b709df71a96122a0904dc497ccc223c

### Steps to reproduce

Run the MRP and press and immediately release the bottom face button (PlayStation X button or Xbox A button).

### Minimal reproduction project

[INPUT_BUG.zip](https://github.com/godotengine/godot/files/7698249/INPUT_BUG.zip)

**Comment by Calinou** [comment]
This is likely something that https://github.com/godotengine/godot/pull/42220 will fix once it's implemented on other platforms.

**Comment by EIREXE** [comment]
> Can you reproduce this on 3.3.4?

I will check.

**Comment by EIREXE** [comment]
I can confirm it happens in 3.3.4

**Comment by madmiraal** [comment]
This is not a regression. I can confirm that it happens on earlier versions of Godot too.

The problem is that the OS' event queues for the joypads are only checked once an iteration and the OS starts dropping old events in the queue if they are not read and the queue gets full. I suspect the DS4 axes are more sensitive and it's sending move events than the Xbox One S resulting in the queue filling up faster.

**Comment by EIREXE** [comment]
> This is not a regression. I can confirm that it happens on earlier versions of Godot too.
> 
> The problem is that the OS' event queues for the joypads are only checked once an iteration and the OS starts dropping old events in the queue if they are not read and the queue gets full. I suspect the DS4 axes are more sensitive and it's sending move events than the Xbox One S resulting in the queue filling up faster.

This happens with buttons too, not just axis.

But I believe your idea is correct, the DS4's polling rate is much higher than the xbox controller's, so that could be the explanation.
