### ISSUE TITLE
MultiMesh instances updating sporadically on Android

### ISSUE THREAD

**Issue by fractilegames** [godotengine/godot#55857]
### Godot version

3.4 stable

### System information

Samsung Galaxy S21, GLES3

### Issue description

I'm updating positions of multiple instances in MultiMeshInstance in `_process()` -function. This works well on PC but on Android the visible instance positions on screen update sporadically. It looks like some instance updates are simply skipped.

The minimal reproduction project uses following code to move instances every frame:
```gdscript
func _process(delta):
	a += delta * 2.0
	var x = sin(a) * 5.0
	for i in range(0, 20):
		$MultiMeshInstance.multimesh.set_instance_transform(i, Transform(Basis(), Vector3(x, 0.0, float(i - 10))))
	$MultiMeshInstance.multimesh.visible_instance_count = 20
```

This is how it looks on Android (the boxes should be aligned horizontally):
![instancing-screenshot](https://user-images.githubusercontent.com/2310335/145707727-14fa3b0d-d450-41f4-abc5-51c680cc876a.png)

Here's a video of it in motion (for some reason the effect is less visible when recording is on):

https://user-images.githubusercontent.com/2310335/145707763-b7be07f0-b6ef-4f0c-96be-46f8dc2d9cfc.mp4

### Steps to reproduce

- Set up MultiMeshInstance
- Update multiple instances on every frame
- Upload to an Android device

### Minimal reproduction project

[InstancingTest.zip](https://github.com/godotengine/godot/files/7698467/InstancingTest.zip)

**Comment by Calinou** [comment]
I suppose a buffer size limit is being hit, which means updates have to be performed across several sizes. Limits are often much lower on mobile GPUs than they are on desktop GPUs.

**Comment by fractilegames** [comment]
I originally noticed this problem in my game project with just 8 instances. If I set the instance count to 1 here, the movement still appears jerky. Hard to say for sure when I don't have anything to compare the position against but I would say the problem is still there.

**Comment by fractilegames** [comment]
I was able to test this on two other Android devices: OnePlus Nord (Android 11) and a Huawei Tablet (Android 9). Both worked flawlessly. Exporting from Godot 3.3 made no difference on the S21.

I noticed that the same problem occurs in my other game that has (almost) certainly been working previously without the issue on my S21: https://user-images.githubusercontent.com/2310335/146045692-34f810d6-aad5-41b5-be1d-6a2e958862f7.mp4 (the cube particles).

This problem might have appeared after the Android 12 update. I would appreciate if someone else could test the minimal reproduction project on other devices, especially on Samsung phones upgraded to Android 12.

**Comment by fractilegames** [comment]
The problem has mysteriously disappeared! I assume the latest Samsung update fixed the OpenGL drivers for Exynos SOC. It would be nice to know for sure but I can't find any real change log for the update or confirmation that other people are seeing their related issues resolved.

Anyway, I can't reproduce this anymore, so I guess this can be closed now.
