### ISSUE TITLE
The editor mismatch parenthesis when a comment countains a closing parenthesis

### ISSUE THREAD

**Issue by gustavi** [godotengine/godot#55854]
### Godot version

v4.0.dev.20211210.official [21b81998b]

### System information

Windows 10 64bit - Vulkan API 1.2.141 - GeForce GTX 1660 SUPER

### Issue description

The editor mismatch parenthesis when a comment countains a closing parenthesis:

![image](https://user-images.githubusercontent.com/2736557/145706845-4f434b49-61fa-47cb-bded-530c4efadf09.png)

Affected versions:

- Godot 4.0 (21b81998b)
- Godot 3.4
- Godot 3.3

(Not tested on older versions)

### Steps to reproduce

```gdscript
func bar(x):
    pass


func foo():
    bar("a"
        # )
    )
```

### Minimal reproduction project

See previous code.

**Comment by cdemirer** [comment]
Roughly the same issue: #53332
