### ISSUE TITLE
Strange artifacts when using `floor()` in shader

### ISSUE THREAD

**Issue by jemala** [godotengine/godot#55865]
### Godot version

3.4.stable

### System information

Kubuntu 20.04, GLES3, GeForce GTX 980 (460.91.03)

### Issue description

I created a simple spatial grid (120x120) of triangles where each triangle has a unique Id. This Id is being put into UV.x, as you can see here: 

```
extends MeshInstance

func _ready():
	var st = SurfaceTool.new()

	st.begin(Mesh.PRIMITIVE_TRIANGLES)

	var count = 0;
	for z in 120:
		for x in 120:

			st.add_normal(Vector3.UP)
			st.add_uv(Vector2(count, 0))
			st.add_vertex(Vector3(x, 0, z))

			st.add_normal(Vector3.UP)
			st.add_uv(Vector2(count, 0))
			st.add_vertex(Vector3(x, 0, z - 1))

			st.add_normal(Vector3.UP)
			st.add_uv(Vector2(count, 0))
			st.add_vertex(Vector3(x + 1, 0, z))
			
			count += 1

	mesh = st.commit()
```

Now in the shader, each triangle is given a color depending on it's x position, so that triangles on the left are black, triangles on the right are red, and interpolated in between. To achieve this, the shader is using the floor function, as you can see here:

```

shader_type spatial;
render_mode blend_mix,depth_draw_opaque,cull_back,diffuse_burley,specular_schlick_ggx;

void fragment() {
	vec3 color = vec3(0, 0, 0);
	color.r = ((UV.x) / 120.0) - floor((UV.x) / 120.0);
	ALBEDO = color;
}

```

This leads to the following very strange artefacts:

![image](https://user-images.githubusercontent.com/18643746/145722574-ce8e81aa-49b0-48e6-95aa-0d9cb064e47c.png)

Besides the obvious artefacts on the left, you can also see stripes which appear for higher ID values (in the front), but not for low ID values (in the back).

![image](https://user-images.githubusercontent.com/18643746/145722831-801dc218-d925-42cd-b019-408cf6d38c23.png)

If I do the exact same calculation in the code instead of the shader, there are no such artefacts:

Code:
```

	var count = 0;
	for z in 120:
		for x in 120:
			
			var value = count / 120.0 - floor(count / 120.0);

			st.add_normal(Vector3.UP)
			st.add_uv(Vector2(value, 0))
			st.add_vertex(Vector3(x, 0, z))

```

Shader:
`
	color.r = UV.x;
`

Result:

![image](https://user-images.githubusercontent.com/18643746/145722973-8290003e-fee2-4e04-9df2-7cb937ffdcb6.png)

### Steps to reproduce

Please have a look at the MRP's below. 

"FloorTest.zip" is doing the calculation in the shader and has artifacts. 

"FloorInCodeTest.zip" is doing the calculation in the code and has no artifacts. 

### Minimal reproduction project

[FloorTest.zip](https://github.com/godotengine/godot/files/7699230/FloorTest.zip)

[FloorInCodeTest.zip](https://github.com/godotengine/godot/files/7699231/FloorInCodeTest.zip)

**Comment by clayjohn** [comment]
This looks like a floating point precision issue. I cannot reproduce on my hardware (Intel UHD graphics 620)

My guess is that this is a precision issue caused by compressing UVs. Because you don't specify a compression flag in ``commit()``, you use the default compression which compresses UVs to half floats (16 bits instead of 32). You could try disabling compression by specifying that the mesh should not be compressed e.g. ``commit(null, 0)``

Alternatively, it could be a precision issue on the GPU. Some GPUs default to half_float precision for performance reasons. In which case you may need to specify that you will be using "highp" precisions for that operation. See: https://docs.godotengine.org/en/stable/tutorials/shading/shading_reference/shading_language.html#precision

**Comment by jemala** [comment]
Hi Clayjohn, thanks for your answer. I did already test "highp" before, and it didn't help.

I just tried disabling the compression (I didn't know the mesh is being compressed) as you suggested and it looks better, especially the stripes are gone. But it still has some artifacts remaining:

![image](https://user-images.githubusercontent.com/18643746/145729497-7e77ed04-4c96-4ff6-b91d-d4057808b6de.png)

So there is still some precision issue there that I can not explain. However, in my project I am using this calculated value for a texture lookup, so I need to increase the value by 0.5 anyway to read the center of the pixel, and this solves the precision issue. My working shader (combined with `commit(null, 0)`) now looks like this:

```

void fragment() {
	vec3 color = vec3(0, 0, 0);
	color.r = ((UV.x + 0.5) / 120.0) - floor((UV.x + 0.5) / 120.0);
	ALBEDO = color;
}

```

**Comment by clayjohn** [comment]
> So there is still some precision issue there that I can not explain. However, in my project I am using this calculated value for a texture lookup, so I need to increase the value by 0.5 anyway to read the center of the pixel, and this solves the precision issue. My working shader (combined with commit(null, 0)) now looks like this:

Ah, so it is a combination of precision issues on CPU and GPU. This is not very surprising as floating point has trouble representing exact numbers. floating point numbers tent to represent values with their closest approximation, which can sometimes be slightly higher or lower than the actual value. When you call ``floor()`` and the floating point approximation is slightly below the actual value, it drops the value even more. Instead of adding ``0.5`` you could have also used ``round()``.

**Comment by jemala** [comment]
You are right, `round()` solves the issue too, I just tried it out. But I still don't get it, because all 3 vertices of a triangle have the same value. Interpolating them in the fragement shader should lead to the same value too. So, even if there is a precision issue, every pixel of a triangle should have the same color, but that's not the case:

![image](https://user-images.githubusercontent.com/18643746/145731801-aac28f3f-8f4f-45ef-9f5f-ae9791907284.png)

Anyway, I can continue my project now and learned something :-) Thanks for your help Clayjohn!

**Comment by Chaosus** [comment]
And If you use the following code:

```
shader_type spatial;
render_mode blend_mix,depth_draw_opaque,cull_back,diffuse_burley,specular_schlick_ggx;

void vertex() {
	COLOR.rgb = vec3(((UV.x) / 120.0) - floor((UV.x) / 120.0), 0, 0);
}

void fragment() {
	ALBEDO = COLOR.rgb;
}
```
the artifacts would also disappear, it's also more optimized than calculating the same part of code for each pixel in a fragment shader.

**Comment by jemala** [comment]
Ah, I really like this solution, this makes a lot of sense, thank you Chaosus. I'll implement it this way in my project.
