### ISSUE TITLE
Rotation Track 3D are uneditable via keys

### ISSUE THREAD

**Issue by stryker313** [godotengine/godot#55864]
### Godot version

4.0dev.20211210

### System information

Windows 10 gta 1060 intel 4690k

### Issue description

You cannot edit rotation 3d tracks in an animation player
In the sample project, I keyframed a rotation_3d track for the Node 3D.
You cannot edit the keyframe manually.
This also applies to Skeletons.

![Desktop Screenshot 2021 12 12 - 12 14 32 43](https://user-images.githubusercontent.com/83078010/145722410-686b2f02-6279-41de-8a4b-e661c222ab49.png)

### Steps to reproduce

1. Keyframe a rotation 3d key on any 3d node
2. Attempt to edit the keyframe
3. Error --> Condition "(p_value.get_type() != Variant::QUATERNION) && (p_value.get_type() != Variant::BASIS)" is true.
Anim Change Rotation3D

### Minimal reproduction project

[Debug.zip](https://github.com/godotengine/godot/files/7699193/Debug.zip)

**Comment by TokageItLab** [comment]
As a result of previous discussions with reduz, we are going to implement an additional EditorInspector element for quaternions. Please wait for it.
