### ISSUE TITLE
skip_test statement has no effect in DEFAULT_OP_ARRAY_CMD

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#5587]
Seen in the build log:
```
core/variant_op.cpp:983:12: warning: statement has no effect [-Wunused-value]
   skip_test;\
            ^
core/variant_op.cpp:1002:2: note: in expansion of macro 'DEFAULT_OP_ARRAY_CMD'
  DEFAULT_OP_ARRAY_CMD(m_name, const DVector<dv_type>, 0, return arr->get(index))
  ^
core/variant_op.cpp:2425:3: note: in expansion of macro 'DEFAULT_OP_DVECTOR_GET'
   DEFAULT_OP_DVECTOR_GET(VECTOR2_ARRAY, Vector2)
   ^
```

Relevant code is here: https://github.com/godotengine/godot/blob/d08092e/core/variant_op.cpp#L981-L983

**Comment by J08nY** [comment]
I believe it has, `DEFAULT_OP_ARRAY_CMD` is used 4 times in godot's source, it is `0` or similiar in three of those times and in the last one it is `if(skip_cond) return;` so if that gets inserted there by the preprocessor then it in fact has an effect.

**Comment by akien-mga** [comment]
Thanks for checking. Then I suppose there's nothing to fix, unless it can be tweaked a bit not to trigger a warning without changing the overall behaviour and performance.

**Comment by vnen** [comment]
Here the macro argument is a `;` instead of  `0`: https://github.com/godotengine/godot/blob/d08092e/core/variant_op.cpp#L1836

Can the `0` be replaced by a `;` in the `DEFAULT_OP_DVECTOR_GET` macro so the compiler stops complaining?
