### ISSUE TITLE
Vulkan Mobile backend: Fog is only rendered on the background sky, not 3D objects

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#55870]
### Godot version

4.0.dev (2a9dd654b)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 470.74)

### Issue description

Fog (the non-volumetric kind) is not applied to 3D objects when using the Vulkan Mobile backend. It works when using the Vulkan Clustered backend.

### Vulkan Clustered backend

![2021-12-12_20 30 19](https://user-images.githubusercontent.com/180032/145726852-998597dd-8e4d-47e2-a364-e5fc960b20dd.png)

### Vulkan Mobile backend

![2021-12-12_20 30 41](https://user-images.githubusercontent.com/180032/145726853-81c5dfa3-3ae2-465c-9b66-96dcec345d79.png)

### Steps to reproduce

- Add a MeshInstance3D node with any PrimitiveMesh resource inside.
- Add a WorldEnvironment node. Enable **Fog** (not Volumetric Fog) in the Environment resource. Increase the density to something easily visible such as `0.05`.
- Move the camera away from the object. Notice fog becoming stronger over distance.
- Switch to Vulkan Mobile backend in the project settings (search for `back end`).
  - **Note:** The MRP linked below already uses the Vulkan Mobile backend by default.
- Restart the editor. Notice fog only affects the background sky, not the object.

### Minimal reproduction project

[test_vulkan_clustered_vs_mobile_fog.zip](https://github.com/godotengine/godot/files/7699389/test_vulkan_clustered_vs_mobile_fog.zip)

**Comment by clayjohn** [comment]
This has been fixed at some point. Testing in RC3 and fog looks the same in Mobile and Forward+
