### ISSUE TITLE
.tres file with a Dictionary/Array with a Resource is only saved the first time (or when the Dictionary/Array is expanded again)

### ISSUE THREAD

**Issue by Maran23** [godotengine/godot#55885]
### Godot version

3.x, 4.0

### System information

Windows 10

### Issue description

First of all: This only happens when using a `Resource` inside a `Dictionary` or `Array`.
![image](https://user-images.githubusercontent.com/66004280/148618814-0512be2b-cf88-44d9-8164-f2ee1c90c66a.png)

Editing and saving a `.tres` file will work only the first time. When editing and saving again, nothing will happen (can be checked by opening the `.tres` file in a text editor).

I debugged a bit and found out that it works due to the `Dictionary`/`Array` expand, which will set the `Dictionary`/`Array` to `edited`.
That's why it works the first time.
As soon as I at least once collapse/expand the `Dictionary`/`Array` again the save will work again for the first time.

### Steps to reproduce

1. Open the attached project
2. Open the save.tres - Verify that there is 'ChangeMe' in the `Dictionary`
3. Open the save.tres in a text editor (e.g. Notepad++) - There should be 'ChangeMe' as well
4. Change the text (in Godot) to something else
5. Save
6. Everything should work and the change is saved Verify in the text editor)
7. Change the text (in Godot) again
8. Save
9. You will see your change in the editor but in the text editor you won't see the change (I used Notepad++)

### Minimal reproduction project

[GodotSaveBug.zip](https://github.com/godotengine/godot/files/7700024/GodotSaveBug.zip)

**Comment by Maran23** [comment]
Maybe PR #45879 fixed that for 4.0. That is the only thing I found that looks related to this issue.

**Comment by Maran23** [comment]
I now had a look in the code. The issue is present in 4.0 and it's actually a bit different and easier to reproduce, therefore I changed the title and description.

Basically when the `Resource` in the `Dictionary` is edited, the `Dictionary` is not set to edited, only the `Resource` inside is. This is not checked when saving (e.g. we need to check for edited children here, but I don't know yet how I can retrieve this information).

When the `Dictionary` is collapsed/expanded, the `Dictionary` is set to edited, therefore it is saved correctly.

**Comment by AnidemDex** [comment]
I had a similar issue for editor plugins when using arrays and dictionaries. Things are saved only the first time

**Comment by Maran23** [comment]
> I had a similar issue for editor plugins when using arrays and dictionaries. Things are saved only the first time.
> 
> Related issue [AnidemDex/Godot-EventSystem#23](https://github.com/AnidemDex/Godot-EventSystem/issues/23)

Yes, I can confirm it does not work for Arrays either.
I found out, that the problem is in this code:

editor_node.cpp
![image](https://user-images.githubusercontent.com/66004280/149564824-23500611-c504-4ee4-a37e-15402cf2de79.png)

In `_save_external_resources`, `_find_edited_resources` is not looking for the edited state of the children in case of `Dictionary` or `Array`. If we can somehow get the Array/Dictionary here and check, if there children are resources and if so check if they are marked as edited, we can fix it here.

Another way would be, that a Resource inside an Array/Dictionary will not just himself as edited but also their 'parent' (The Array/Dictionary himself). But don't know, if this is possible either currently.

**Comment by AnidemDex** [comment]
> Another way would be, that a Resource inside an Array/Dictionary will not just himself as edited but also their 'parent' (The Array/Dictionary himself). But don't know, if this is possible either currently.

@Maran23 
Well, what I did was to connect subresource `changed` signal to parent resource:

https://github.com/AnidemDex/Godot-EventSystem/blob/2b24de5c79cae88ff65db7ee8b08483d6f4069ae/addons/event_system_plugin/resources/timeline_class/timeline_class.gd#L22-L35

But is a bit annoying since not every change in subresource means that the main resource changed (wich is annoying when you make custom inspectors that relies on that signal).

**Comment by Maran23** [comment]
@AnidemDex I finally found a good fix for the problem and opened a PR. :)
