### ISSUE TITLE
Vulkan Mobile backend: Warn about unsupported features in the editor and class reference

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#55880]
### Godot version

4.0.dev (2a9dd654b)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 470.74)

### Issue description

The following features have been tested and have no effect when enabled in the Vulkan mobile backend:

- VoxelGI
- WorldEnvironment > SDFGI
- WorldEnvironment > Volumetric Fog

These features are unlikely to ever be supported in the Vulkan mobile backend, given its focus on low-end hardware such as mobile GPUs and integrated graphics.

We should emit node configuration warnings when an unsupported feature is enabled while using the Vulkan Mobile backend. The inspector should also be configured to hide properties that have no effect when using the Vulkan Mobile backend (especially in the Environment resource). On top of that, we should mention limitations in the class reference.

### Steps to reproduce

- Switch to the **Vulkan Mobile** backend in the project settings and restart the editor.
- Try enabling the features listed above.

### Minimal reproduction project

N/A

**Comment by mrjustaguy** [comment]
What about Depth of Field, Subsurface Scattering, SSIL and SSAO?

**Comment by BastiaanOlij** [comment]
We also need this for our new compute shader logic though here it should be a "maybe", compute shaders do work on some mobile hardware but not on all. I think in theory the mobile renderer does allow the logic even though we no longer use compute shaders ourselves for this reason.

**Comment by clayjohn** [comment]
I will work on this before release. 

Note to self to also clean up https://github.com/godotengine/godot/issues/54611 (its too late to remove, but I can hide it in the editor and emit a warning when used from a script)
