### ISSUE TITLE
Godot 4 Skeleton3D BoneAttachments don't inherit bone positions properly when SkeletonIK is on

### ISSUE THREAD

**Issue by macryc** [godotengine/godot#55883]
### Godot version

4.0 dev

### System information

Win10, GLES3, RTX 2070 mobile

### Issue description

Skeleton3D BoneAttachment node position does not match the skeleton bone that it's assigned to. There is a significant offset that doesn't seem to be following a pattern. Additionally, when SkeletonIK is on and modifies selected bone chain, the offset changes.

### Steps to reproduce

1. Import a skeleton with animations (eg. mixamo)
2. Set a skeletonIK with a target, set start and end bones
3. Create a bone attachment node as a child of the Skeleton3D, assign it to a bone (the positioning will look correct in the editor)
4. Attach a child (eg. a meshinstance3d) to the bone attachment node
5. Create a simple controller for the character, including SkeletonIK (eg, mouselook)
6. Run the game and watch the child of the bone attachment become offset from its parent

**Comment by Calinou** [comment]
cc @TokageItLab

**Comment by TokageItLab** [comment]
I can't reproduce this, the problem may occur if the PoseOverride option in BoneAttachment is turned on, but otherwise it looks working correctly. If you still have problems, please send us your Minimal reproduction project.

**Comment by macryc** [comment]
> I can't reproduce this, the problem may occur if the PoseOverride option in BoneAttachment is turned on, but otherwise it looks working correctly. If you still have problems, please send us your Minimal reproduction project.
> 

Sorry mate, my bad. The cause of the problem was that my attachment was a rigid body weapon. In 3.4 it was enough to keep those sleeping and only wake them up when you wanted to drop the weapon - I would then toplevel it, unsleep it and apply a force to it. 
It looks like in Godot 4 there is a 'freeze' property for rigid bodies and when it toggled that on, the issue got fixed.
I suspect the offset was happening because even though the rigid body weapon was sleeping, the movement of its parent BoneAttachment was still affecting it to a degree. I will just freeze/unfreeze from now on, which actually makes better sense, logically speaking...
Thanks for looking into it.
