### ISSUE TITLE
Shader appears with black background in GLES3, but transparent in editor/GLES2

### ISSUE THREAD

**Issue by nightblade9** [godotengine/godot#55888]
### Godot version

v3.4.stable.official [206ba70f4]

### System information

Windows 11, GLES3, GeForce GTX 1650 Ti

### Issue description

With the shader below applied to a TextureRect that has an image loaded, I see:

- A sprite with a black background in GLES3
- A sprite with a transparent background in GLES2
- A sprite with a transparent background in Godot editor

I believe the correct, expected background is the transparent one, since we're setting the value to `pixel.a` - which is 0 in the transparent regions of an image.

### Steps to reproduce

Create a TextureRect, add an image, and the shader below. Run it, and witness the black background.

```
shader_type canvas_item;

void fragment() {
    vec4 pixel = texture(TEXTURE, UV);
    float final = 0.15 / ((pixel.r + pixel.g + pixel.b) / 3.0);
    COLOR = vec4(final, final, final, pixel.a);
}
```

### Minimal reproduction project

[IsItAGles3Bug.zip](https://github.com/godotengine/godot/files/7700521/IsItAGles3Bug.zip)

**Comment by lawnjelly** [comment]
Your shader has a divide by zero. A divide by zero in a shader won't crash, but the results of a shader are undefined in the spec.

If you change the line to this, there is no problem.
```
float final = 0.15 / ((pixel.r + pixel.g + pixel.b + 0.01) / 3.0);
```

**Comment by Calinou** [comment]
@Chaosus Does the warning system in `master` detect divisions by zero?

**Comment by nightblade9** [comment]
Ah, I see. That resolves it nicely, thank you for the explanation and solution.
