### ISSUE TITLE
Incorrect expanding of "Import" dialog after opening a "New Project" dialog in the Project Manager

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#55894]
### Godot version

7f9a82b944724c0228301ded5fbb8efee12eac4d

### System information

Windows 10

### Issue description

Detected a minor bug:

![project_import_dialog_bug](https://user-images.githubusercontent.com/3036176/145793662-50aed152-9918-4c19-872b-e4ad51850b4b.gif)

Seems like the opening of that dialog break the structure of the Import dialog. It cannot be shrunk down to the original size after that.

### Steps to reproduce

- Open a Project Manager
- Click on the "New Project" button to show a dialog and close it
- Click on the "Import" button

**Comment by xsellier** [comment]
This issue seems to be related to this one:
https://github.com/godotengine/godot/issues/55896

**Comment by Chaosus** [comment]
@xsellier And how it is related? - there are no 3D nodes in that dialog obviously.

**Comment by xsellier** [comment]
Sounds weird, but both are happening when we are shrinking a Transform property. 2D for you, 3D for the other bug.

**Comment by Rindbee** [comment]
I tried resizing to observe the min size, it seems that the hidden controls are not ignored when calculating the min size.
