### ISSUE TITLE
Godot 4 GLES3 renderer crashing on Mac mini 2014

### ISSUE THREAD

**Issue by PaperPat** [godotengine/godot#55893]
### Godot version

v4.0.dev.calinou[6d58b968d]

### System information

Mac late 2012, Mojave 10.14.6, 8Go ram, SSD 1To, Graph Inter Iris 1536 Mo

### Issue description

- double clic on godot icon --> more than 60 sec to lauch and have active buttons in project manager
- in project manager : select a simple v4 project edition (GL3 or Vulkan select in pref rendering driver) -- > crash
- in project manager : select a simple v4 project launch (GL3 or Vulkan select in pref rendering driver) -- > crash
- in project manager : select new project -- > crash (but project created)
- project icon on Gdot V4 --> less than 10 sec to launch
- in editor, lauch a simple v4 project --> crash
- (tests realised with the New V4 project in zip archive

text debug after loading project :

```
Godot Engine v4.0.dev.calinou (c) 2007-2021 Juan Linietsky, Ariel Manzur & Godot Contributors.
  drivers/gles3/shader_gles3.cpp:90 - Condition "!version" is true. Returning: false
  drivers/gles3/shader_gles3.cpp:90 - Condition "!version" is true. Returning: false
  drivers/gles3/shader_gles3.cpp:90 - Condition "!version" is true. Returning: false
--- Debug adapter server started ---
--- GDScript language server started ---
Basculer entre onglets de scène
  drivers/gles3/shader_gles3.cpp:90 - Condition "!version" is true. Returning: false
  drivers/gles3/shader_gles3.cpp:90 - Condition "!version" is true. Returning: false
  drivers/gles3/shader_gles3.cpp:90 - Condition "!version" is true. Returning: false
  drivers/gles3/shader_gles3.cpp:90 - Condition "!version" is true. Returning: false
  drivers/gles3/shader_gles3.cpp:90 - Condition "!version" is true. Returning: false
  drivers/gles3/shader_gles3.cpp:90 - Condition "!version" is true. Returning: false
  drivers/gles3/shader_gles3.cpp:90 - Condition "!version" is true. Returning: false
  drivers/gles3/shader_gles3.cpp:90 - Condition "!version" is true. Returning: false
  drivers/gles3/shader_gles3.cpp:90 - Condition "!version" is true. Returning: false
  drivers/gles3/shader_gles3.cpp:90 - Condition "!version" is true. Returning: false
  drivers/gles3/shader_gles3.cpp:90 - Condition "!version" is true. Returning: false
  drivers/gles3/shader_gles3.cpp:90 - Condition "!version" is true. Returning: false
  drivers/gles3/shader_gles3.cpp:90 - Condition "!version" is true. Returning: false
  drivers/gles3/shader_gles3.cpp:90 - Condition "!version" is true. Returning: false
  drivers/gles3/shader_gles3.cpp:90 - Condition "!version" is true. Returning: false
  drivers/gles3/shader_gles3.cpp:90 - Condition "!version" is true. Returning: false
  drivers/gles3/shader_gles3.cpp:90 - Condition "!version" is true. Returning: false
  drivers/gles3/shader_gles3.cpp:90 - Condition "!version" is true. Returning: false
1 
2 // NOTE: Shader automatically converted from Godot Engine 4.0.dev's ProceduralSkyMaterial.
3 
4 shader_type sky;
5 
6 uniform vec4 sky_top_color : hint_color = vec4(0.35, 0.46, 0.71, 1.0);
7 uniform vec4 sky_horizon_color : hint_color = vec4(0.55, 0.69, 0.81, 1.0);
8 uniform float sky_curve : hint_range(0, 1) = 0.09;
9 uniform float sky_energy = 1.0;
10 uniform vec4 ground_bottom_color : hint_color = vec4(0.12, 0.12, 0.13, 1.0);
11 uniform vec4 ground_horizon_color : hint_color = vec4(0.37, 0.33, 0.31, 1.0);
12 uniform float ground_curve : hint_range(0, 1) = 0.02;
13 uniform float ground_energy = 1.0;
14 uniform float sun_angle_max = 1.74;
15 uniform float sun_curve : hint_range(0, 1) = 0.05;
16 
17 void sky() {
18 	float v_angle = acos(clamp(EYEDIR.y, -1.0, 1.0));
19 	float c = (1.0 - v_angle / (PI * 0.5));
20 	vec3 sky = mix(sky_horizon_color.rgb, sky_top_color.rgb, clamp(1.0 - pow(1.0 - c, 1.0 / sky_curve), 0.0, 1.0));
21 	sky *= sky_energy;
22 
23 	if (LIGHT0_ENABLED) {
24 		float sun_angle = acos(dot(LIGHT0_DIRECTION, EYEDIR));
25 		if (sun_angle < LIGHT0_SIZE) {
26 			sky = LIGHT0_COLOR * LIGHT0_ENERGY;
27 		} else if (sun_angle < sun_angle_max) {
28 			float c2 = (sun_angle - LIGHT0_SIZE) / (sun_angle_max - LIGHT0_SIZE);
29 			sky = mix(LIGHT0_COLOR * LIGHT0_ENERGY, sky, clamp(1.0 - pow(1.0 - c2, 1.0 / sun_curve), 0.0, 1.0));
30 		}
31 	}
32 
33 	if (LIGHT1_ENABLED) {
34 		float sun_angle = acos(dot(LIGHT1_DIRECTION, EYEDIR));
35 		if (sun_angle < LIGHT1_SIZE) {
36 			sky = LIGHT1_COLOR * LIGHT1_ENERGY;
37 		} else if (sun_angle < sun_angle_max) {
38 			float c2 = (sun_angle - LIGHT1_SIZE) / (sun_angle_max - LIGHT1_SIZE);
39 			sky = mix(LIGHT1_COLOR * LIGHT1_ENERGY, sky, clamp(1.0 - pow(1.0 - c2, 1.0 / sun_curve), 0.0, 1.0));
40 		}
41 	}
42 
43 	if (LIGHT2_ENABLED) {
44 		float sun_angle = acos(dot(LIGHT2_DIRECTION, EYEDIR));
45 		if (sun_angle < LIGHT2_SIZE) {
46 			sky = LIGHT2_COLOR * LIGHT2_ENERGY;
47 		} else if (sun_angle < sun_angle_max) {
48 			float c2 = (sun_angle - LIGHT2_SIZE) / (sun_angle_max - LIGHT2_SIZE);
49 			sky = mix(LIGHT2_COLOR * LIGHT2_ENERGY, sky, clamp(1.0 - pow(1.0 - c2, 1.0 / sun_curve), 0.0, 1.0));
50 		}
51 	}
52 
53 	if (LIGHT3_ENABLED) {
54 		float sun_angle = acos(dot(LIGHT3_DIRECTION, EYEDIR));
55 		if (sun_angle < LIGHT3_SIZE) {
56 			sky = LIGHT3_COLOR * LIGHT3_ENERGY;
57 		} else if (sun_angle < sun_angle_max) {
58 			float c2 = (sun_angle - LIGHT3_SIZE) / (sun_angle_max - LIGHT3_SIZE);
59 			sky = mix(LIGHT3_COLOR * LIGHT3_ENERGY, sky, clamp(1.0 - pow(1.0 - c2, 1.0 / sun_curve), 0.0, 1.0));
60 		}
61 	}
62 
63 	c = (v_angle - (PI * 0.5)) / (PI * 0.5);
64 	vec3 ground = mix(ground_horizon_color.rgb, ground_bottom_color.rgb, clamp(1.0 - pow(1.0 - c, 1.0 / ground_curve), 0.0, 1.0));
65 	ground *= ground_energy;
66 
67 	COLOR = mix(ground, sky, step(0.0, EYEDIR.y));
68 }
69 
  :18 - Unknown identifier in expression: EYEDIR
  ./core/math/rect2.h:243 - Rect2 size is negative, this is not supported. Use Rect2.abs() to get a Rect2 with a positive size.
  ./core/math/rect2.h:243 - Rect2 size is negative, this is not supported. Use Rect2.abs() to get a Rect2 with a positive size.
```

### Steps to reproduce

Steps describe in issue decription

### Minimal reproduction project

[New V4 project.zip](https://github.com/godotengine/godot/files/7702819/New.V4.project.zip)

**Comment by akien-mga** [comment]
Does your device support Metal (and thus Vulkan)?

Here the crash seem specific to the OpenGL backend which is still a WIP, so it's not unexpected. Triaging it as a simple bug in the OpenGL backend for now, until we assess if it's actually Mac specific (it doesn't seem to be, the `EYEDIR` shader error seems related to XR).

**Comment by PaperPat** [comment]
Hello,

Yes, my Mac must support Metal 2 (my osx is Mojave, later than El Capitan)



Mac computers that support Metal

Find out if your Mac computer supports Metal in OS X El Capitan or later.

This article has been archived and is no longer updated by Apple.


Metal is a graphics and compute technology built into macOS, iOS and tvOS. It allows the main processor (CPU) and graphics processor (GPU) to work together more effectively, providing more fluid graphics performance in games and accelerating high-performance media apps. These Mac computers support Metal (and Metal 2) in OS X El Capitan or later <https://support.apple.com/en-au/HT201260>:
  

MacBook <https://support.apple.com/en-au/HT201608> introduced in 2015 or later
MacBook Air <https://support.apple.com/en-au/HT201862> introduced in 2012 or later
MacBook Pro <https://support.apple.com/en-au/HT201300> introduced in 2012 or later
Mac mini <https://support.apple.com/en-au/HT201894> introduced in 2012 or later
iMac <https://support.apple.com/en-au/HT201634> introduced in 2012 or later
iMac Pro (all models)
Mac Pro <https://support.apple.com/en-au/HT202888> introduced in late 2013 or later, plus mid-2010 and mid-2012 models with a recommended Metal-capable graphics card <https://support.apple.com/en-au/HT208898>.

**Comment by akien-mga** [comment]
Then it would likely be good to open a separate bug report for the errors you get when using Vulkan, which would be different from the above GLES3 shader compilation error.

**Comment by PaperPat** [comment]
Ok, I will do that ;-)
Thank you

**Comment by Calinou** [comment]
> Here the crash seem specific to the OpenGL backend which is still a WIP, so it's not unexpected. Triaging it as a simple bug in the OpenGL backend for now, until we assess if it's actually Mac specific (it doesn't seem to be, the EYEDIR shader error seems related to XR).

This is related to sky shaders not being implemented in the OpenGL renderer. Sky shaders aren't relevant in OpenGL until 3D support is implemented anyway.

**Comment by clayjohn** [comment]
This was fixed a long time ago
