### ISSUE TITLE
Shadow map garbage shadow outside of directional light Max Distance

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#559]
I have quite big map and I need player to see quite far away.
So I made set-up with really big Camera Max distance view, and made my directional light Max Distance much smaller but enough to display RT shadows close to Camera, with reasonable sized shadow map.
Unfortunately in distance outside of Light Max Distance where should be no shadows, for some reason weird huge shadow is created.

Image:
![](http://pix.toile-libre.org/upload/original/1404070369.png)

**Comment by mookiexl** [comment]
Bug is still present in 1.1

I'm trying to find a workaround but can't find anything.
At first I thought it's reading beyond the edges of shadow texture.

So I tried things like:
'	if(length(shadow_coord.xy-vec2(0.5,0.5)>=0.5){
		shadow_attenuation=1.0;
	};

and similar.
They fix the issue in some situations, but not all. So it's probably just masking the real problem, which I can't find.

**Comment by mookiexl** [comment]
Alright, finally got it fully working. Changed rasterizer_gles2.cpp like this:

	if (l->type == VS::LIGHT_DIRECTIONAL) {
		light_data[VL_LIGHT_ATTENUATION][1] = l->directional_shadow_param[VS::LIGHT_DIRECTIONAL_SHADOW_PARAM_MAX_DISTANCE];
	}
	else{
		light_data[VL_LIGHT_ATTENUATION][1] = l->vars[VS::LIGHT_PARAM_RADIUS];
	}

So now light_attenuation.g that controls falloff of other types of light is used to fade shadows of directional light.

It's not perfect, it would be better if user could control the falloff exponent as well, but I don't understand Godot's code to implement that myself.

**Comment by n-pigeon** [comment]
Awesome! Thx for help :)

**Comment by akien-mga** [comment]
A fix for this issue was proposed in this PR: #1991
It contains a lot of noise though, so I would advise against merging it as is.

**Comment by vnen** [comment]
As @karolgotowala wrote in #2647:

> If directional shadows range is set smaller than camera view range there is full dark area behind shadows range don't know if this solves and can't try it but i believe setting ShadowBuffer texture edge to white should solve this.

> ```
glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_S, GL_CLAMP_TO_BORDER);
glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_T, GL_CLAMP_TO_BORDER);
float color[] = { 1.0f, 1.0f, 1.0f, 1.0f };
glTexParameterfv(GL_TEXTURE_2D, GL_TEXTURE_BORDER_COLOR, color);

**Comment by SuperUserNameMan** [comment]
bump.
would it be possible to fix this for 2.2 ?
