### ISSUE TITLE
Vulkan Mobile backend: Glow behaves inconsistently compared to the clustered backend

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#55901]
### Godot version

4.0.dev (2a9dd654b)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 470.74)

### Issue description

I'm aware that glow uses a different implementation, but it seems to be much harder to control on the mobile backend. The main issue is that by default, its effect is barely visible unless you decrease **Hdr Threshold**. Since the Vulkan Mobile backend uses some kind of HDR rendering, this should not be required ideally.

The second issue is that when you adjust Hdr Threshold from 0.35 to 0.34, glow will go from "not present at all" to "very strong":

![2021-12-13_13 52 09](https://user-images.githubusercontent.com/180032/145816121-b35d18db-8499-4ec9-aedc-d94b1c514da6.png)

![2021-12-13_13 52 14](https://user-images.githubusercontent.com/180032/145816131-72fffdfe-d5ad-4048-a94e-f35ed630c812.png)

### Steps to reproduce

- Add a MeshInstance3D and a WorldEnvironment node.
- Enable Glow in WorldEnvironment.
- Play around with various properties.
- Switch to the Vulkan mobile backend. Notice that the glow's appearance will change noticeably – it will often be much darker than it was with the same settings in the Vulkan clustered backend.

### Minimal reproduction project

[Mobile Lights_1.zip](https://github.com/godotengine/godot/files/7703960/Mobile.Lights_1.zip)

**Comment by BastiaanOlij** [comment]
Please try this with this PR applied: https://github.com/godotengine/godot/pull/60617

**Comment by Calinou** [comment]
> Please try this with this PR applied: #60617

Looks like that fixes it! The transition is no longer nearly as strong as it used to be:

https://user-images.githubusercontent.com/180032/166745450-013fa170-10d1-4ec0-aa06-05d3e852a3ea.mp4

Note that glow settings in this project are quite excessive – I used stronger values to make the difference more obvious.

**Comment by BastiaanOlij** [comment]
Well more testing of me today and its still struggling a bit on lower colors. The big issue is that we do not have a high dynamic range on the mobile renderers so storing emissive colors at higher intensity doesn't work well. For your situation I think both clustered and mobile will work fine, but a night time scene where you want to get some nice glow going, it's maxing out.

I think that is just a limitation of the mobile renderer and people who target both mobile renderer and clustered renderer are just going to have to know different intensities are going to be required.

**Comment by clayjohn** [comment]
Closing as this is resolved as much as it is going to be
