### ISSUE TITLE
Text wrapping is broken if the window is resized when using the `canvas_items` stretch mode

### ISSUE THREAD

**Issue by DrCanvas** [godotengine/godot#55904]
### Godot version

v4.0.dev.20211210.official [21b81998b]

### System information

Windows 10

### Issue description

For some reason text labels ignore the wrapping mode when the window is resized:

![text_bug](https://user-images.githubusercontent.com/65372494/145832978-df54fd52-8319-4179-8db3-72433f1a5bcd.gif)

![log](https://user-images.githubusercontent.com/65372494/145833028-52c74362-54cc-484a-be9b-5bdcc2f97602.jpg)

### Steps to reproduce

1. Open the reproduction project.
2. Launch the scene.
3. Resize the window.
4. Also try switching between fullscreen and window modes.

### Minimal reproduction project

[Text_bugsize.zip](https://github.com/godotengine/godot/files/7704707/Text_bugsize.zip)

**Comment by Calinou** [comment]
Does this occur if you disable font oversampling in the Project Settings?

**Comment by DrCanvas** [comment]
Disabling font oversampling kind of worked. Fonts turn blurry, though.
I also discovered that changing Text Direction property temporarily restores text wrapping:
![text_dir](https://user-images.githubusercontent.com/65372494/145857947-1cae59bf-2202-4e50-8afe-81b6eaa079b8.gif)
