### ISSUE TITLE
Crash when opening a project that's missing some dependencies

### ISSUE THREAD

**Issue by balintmaci** [godotengine/godot#55914]
### Godot version

3.4 stable

### System information

Windows 10

### Issue description

I wanted to delete the files of the oculus mobile vr plugin while the editor was closed. When I tried to open the project afterwards the editor crashed which prevented me from fixing the problem without editing the project file manually. I assume it's from the references in the project file but I could be wrong.

### Steps to reproduce

- Have a project that uses the OVR mobile plugin (possibly same affect with other plugins)
- close the editor
- delete the plugin folder from addons
- try to open the project
- see crash

**Comment by HubbleCommand** [comment]
Strange, other plugins like SmartShape2D don't cause crashes, but Godot gives missing dependency errors.

If I just download & install the godot_oculus_mobile plugin, then delete the folder, I don't have any crashes. Is there anything interesting [in the logs](https://godotengine.org/qa/98840/godot-engine-crashes-is-there-a-log-file?show=98859)?

The only weird thing I noticed was that unlike many other plugins, the Godot Oculus Mobile Plugin didn't appear in the plugins list.

**Comment by balintmaci** [comment]
Closing because I cannot reproduce the error on 3.4.1
