### ISSUE TITLE
Main font size editor setting incorrectly requires restart

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#55942]
### Godot version

f09d884

### System information

W10

### Issue description

When you change "Main Font Size" in Editor Settings, you get that yellow text saying changes won't be applied until restart. But this is a lie.
![btCwwoGoiI](https://user-images.githubusercontent.com/2223172/146098257-0cc75a4b-43ac-4cc9-ab9a-3fcefac10932.gif)
This might be not the only setting with this problem.

### Steps to reproduce

See GIF.

**Comment by akien-mga** [comment]
Well it's not a lie, the font size change is applied, but that doesn't mean that the whole UI gets recalculated to fit it properly IIRC. Some some font-related UI metrics might still need a restart I think.

**Comment by akien-mga** [comment]
For example this used to happen: #27663. You can see that many of the Controls didn't update their min sizes to fit the big text.
But indeed this seems fixed in 4.0, so maybe the restart is no longer needed.

**Comment by Norrox** [comment]
The save and restart seems to be needed by the language selector, on the same settings page (4.0)

**Comment by KoBeWi** [comment]
> The save and restart seems to be needed by the language selector, on the same settings page

Is it? It look fine to me.
![6dJitDhj7O](https://user-images.githubusercontent.com/2223172/147417548-425f6f83-0210-4451-aeae-5700c3de2e68.gif)

**Comment by Norrox** [comment]
Yeah but the language wont change unless you restart it ?

> > The save and restart seems to be needed by the language selector, on the same settings page
> 
> Is it? It look fine to me. ![6dJitDhj7O](https://user-images.githubusercontent.com/2223172/147417548-425f6f83-0210-4451-aeae-5700c3de2e68.gif)

**Comment by Calinou** [comment]
> Yeah but the language wont change unless you restart it ?

Indeed, run-time language changes *in the editor* are not supported yet. (They are supported in projects though.)

**Comment by KoBeWi** [comment]
> Yeah but the language wont change unless you restart it ?

The issue is about font size though, so it's unrelated.

**Comment by akien-mga** [comment]
Fixed by #59373.
