### ISSUE TITLE
Picking node for audio track could be improved

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#55944]
### Godot version

f09d884

### System information

W10

### Issue description

When you select the Audio Track in Add Track menu of AnimationPlayer, you are presented with full scene tree:
![image](https://user-images.githubusercontent.com/2223172/146100514-2446e6d6-12ee-4acb-ae86-ef11e169bf25.png)

But this happens when you select anything else than audio player:
![image](https://user-images.githubusercontent.com/2223172/146100577-0d25a117-595d-4e4e-8d73-6554285b64d6.png)

It would be better if invalid nodes were disabled, i.e. greyed out and unclickable. Even simply graying them out would make the nodes easier to pick. This also applies to other track types that expect a specific node type.

### Steps to reproduce

1. Go to Animation tab with AnimationPlayer and Animation added
2. Click Add Track
3. Select Audio
4. Try to pick not audio

**Comment by Calinou** [comment]
Adding an object property hint with the value `AudioStreamPlayer,AudioStremPlayer2D,AudioStreamPlayer3D` should do the trick.
