### ISSUE TITLE
Windows console gets space between characters after SSL error

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#5594]
This might be caused by some non-printable characters getting mixed up when outputting the messages.

![cmd_2016-07-08_12-07-58](https://cloud.githubusercontent.com/assets/5599796/16691834/ab71762c-4504-11e6-9dc6-615e7351e337.png)

**Comment by akien-mga** [comment]
I guess it will be harder to reproduce now that you fixed OpenSSL on Win64 :P

**Comment by vnen** [comment]
Well, one can break it again for testing :laughing:

**Comment by reduz** [comment]
It probably was related to that somehow, remember the editor it was throwing to console was not valid either, product of some sort of internal corruption. Will close for now.
