### ISSUE TITLE
Update mode not refreshed visually on undo

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#55941]
### Godot version

f09d884

### System information

W10

### Issue description

When you change update mode of an animation track and undo it, the button stays the same until the track updates.
![zlCyqMPYob](https://user-images.githubusercontent.com/2223172/146097320-adc765de-b6af-4eaa-8d53-deff644991a6.gif)
Interpolation Mode doesn't have this issue.

### Steps to reproduce

1. Add AnimationPlayer with some animation
2. Add any track
3. Change its Update Mode
4. Undo
5. Notice that the Update Mode didn't undo, but in fact it did, but it didn't refresh visually

**Comment by Calinou** [comment]
Does this also occur on `3.x`?

**Comment by KoBeWi** [comment]
Yes.
