### ISSUE TITLE
Vulkan: Lighting on billboard Sprite3D is unlit at certain angles

### ISSUE THREAD

**Issue by seankarol** [godotengine/godot#55956]
### Godot version

v4.0.dev.custom_build [de8348a9b]

### System information

Windows 10, Vulkan, NVIDIA GeForce RTX 2070 SUPER

### Issue description

When lighting a Y billboard sprite 3d, the sprite is not lit when the light is in front of the sprite but it's lit when it's behind it. This is unexpected, when a light is in front of the sprite I would have expected it to to be lit.

We can see here the light is behind the sprite and the sprite is lit.
![image](https://user-images.githubusercontent.com/5124816/146205906-cfbb6516-969b-40ad-bde7-d5f9190c7abd.png)

We can see here the light is in front of the sprite but it's black (can't see it)
![image](https://user-images.githubusercontent.com/5124816/146205945-4fe7ed01-b93f-45e2-94a0-babd42f714ca.png)

### Steps to reproduce

1. Make a Sprite3D, shaded, billboard
2. Add light
3. Rotate light around sprite
4. Notice how the sprite is lit inconsistently depending on the angle of the camera despite the sprite always being in the range of the light

### Minimal reproduction project

[lighting_test.zip](https://github.com/godotengine/godot/files/7720181/lighting_test.zip)

Example is using Y-billboard and Sdfgi because that matches my use case closer but it also seems to occur with regular billboard sprite and without Sdfgi.

**Comment by Calinou** [comment]
@seankarol Can you reproduce this on 3.4?

**Comment by seankarol** [comment]
It works as I would expect in v3.4.stable.official [206ba70f4]:

[lighting_test_34.zip](https://github.com/godotengine/godot/files/7722989/lighting_test_34.zip)

**Comment by clayjohn** [comment]
This is fixed. I'm not sure when it was fixed but I can't reproduce in RC3
