### ISSUE TITLE
WorldEnvironment Auto Exposure only works if framebuffer allocation is set to 3D, not 3D Without Effects

### ISSUE THREAD

**Issue by LoserFox** [godotengine/godot#55975]
### Godot version

 v3.4.stable.official.206ba70f4

### System information

Android, huawei mate10 ,GLES3

### Issue description

When I export a game that includes auto exposure post-processing to the android platform, the game screen will flicker. I think it is caused by auto exposure not supporting the android platform. I am using GLES3

### Steps to reproduce

Use gles3 and auto exposure in any project to reproduce the problem

**Comment by timothyqiu** [comment]
I think you have to set `rendering/quality/intended_usage/framebuffer_allocation.mobile` to `3D` in Project Settings first, it could resolve the flickering.

Although the flickering will possibly be gone, the auto exposure still won't work as expected I think. Could you try if #55983 works for you? You can try the export template in my own build in case it's not ready here: https://github.com/timothyqiu/godot/actions/runs/1586478548

**Comment by LoserFox** [comment]
The problem was discussed in private with "timothyqiu". The problem is that the default value of "framebuffer_allocation.mobile" is 3D Without Effects. This option does not support auto exposure post-processing. Replace it with 3D to solve the problem.

**Comment by LoserFox** [comment]
#15481

**Comment by LoserFox** [comment]
相关问题可查看#27439

**Comment by Calinou** [comment]
Does this mean the following line in the class reference is incorrect? https://github.com/godotengine/godot/blob/62b181a4ef22b5fe0563f5504b944afc90a34215/doc/classes/Environment.xml#L12

Could someone test all 4 of those effects with the 3D Without Effects framebuffer allocation (preferably on mobile)?

**Comment by LoserFox** [comment]
> Reopening, as we need to amend the documentation to mention this.
> 
> Does this mean the following line in the class reference is incorrect?
> 
> https://github.com/godotengine/godot/blob/62b181a4ef22b5fe0563f5504b944afc90a34215/doc/classes/Environment.xml#L12
> 
> Could someone test all 4 of those effects with the 3D Without Effects framebuffer allocation (preferably on mobile)?

i will try it

**Comment by LoserFox** [comment]
> Reopening, as we need to amend the documentation to mention this.
> 
> Does this mean the following line in the class reference is incorrect?
> 
> https://github.com/godotengine/godot/blob/62b181a4ef22b5fe0563f5504b944afc90a34215/doc/classes/Environment.xml#L12
> 
> Could someone test all 4 of those effects with the 3D Without Effects framebuffer allocation (preferably on mobile)?
After my test, only ss_reflections and ssao are invalid under 3D Without Effects on PC. I guess it’s the same on Android

**Comment by LoserFox** [comment]
After my test, only ss_reflections and ssao are invalid under 3D Without Effects on PC. I guess it’s the same on Android

**Comment by LoserFox** [comment]
I tried to create a pull request to fix the errors on the document, you can take a look at it. (The first time I created a pull request, there may be some errors) #56025
