### ISSUE TITLE
Script editor cursor offsets with indentation

### ISSUE THREAD

**Issue by El13B** [godotengine/godot#55996]
### Godot version

4.0dev (bc2ac26)

### System information

Win10, Vulkan

### Issue description

Inside the script editor the cursor seems to offset the more you add indentations. I've included an example project and here's how to reproduce the issue yourself:

### Steps to reproduce

1. Create script
2. create a beautiful if statement pyramid
3. observe as the cursor is not at the correct place

### Minimal reproduction project

[CursorBrokie.zip](https://github.com/godotengine/godot/files/7728995/CursorBrokie.zip)

**Comment by Calinou** [comment]
@El13B Can you reproduce this in 3.4? Also, are you using a custom code editor font?

**Comment by El13B** [comment]
commit (75ac048e4) didn't have that issue, so it's between then and now.

I never experienced the issue in 3.4.

I'm not using custom code editor font.

**Comment by cdemirer** [comment]
Bisection result: 01bac2c46
