### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [godotengine/godot#56]
I would like to point out that identifiers like "[`_ConstantSort`](https://github.com/okamstudio/godot/blob/0b806ee0fc9097fa7bda7ac0109191c9c5e0a1ac/tools/docdump/doc_dump.cpp#L42)" and "[`_DictionaryVariantHash`](https://github.com/okamstudio/godot/blob/0b806ee0fc9097fa7bda7ac0109191c9c5e0a1ac/core/dictionary.cpp#L34)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL32-CPP.+Do+not+declare+or+define+a+reserved+identifier) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by akien-mga** [comment]
@elfring I guess it would be best if you proposed a PR to fix those, so much work is being done on core functionalities that I'm not sure @reduz has much time to do such code cleaning.

**Comment by AlexHolly** [comment]
So the solution for "_DictionaryVariantHash" would be this?

"dictionary.cpp"
```
struct DictionaryVariantHash {

	static _FORCE_INLINE_ uint32_t hash(const Variant &p_variant)  { return p_variant.hash(); }
};


struct DictionaryPrivate {

	SafeRefCount refcount;
	HashMap<Variant,Variant,DictionaryVariantHash> variant_map;
	bool shared;

};

There are many structs that have an "_" maybe this is a godot convention?

The soloution is to remove the "_" on all struct names?

**Comment by elfring** [comment]
Would you like to [look at the consequences around the usage of underscores in some identifiers](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?") a bit more?

**Comment by akien-mga** [comment]
Should likely be done *at the latest* for 3.0, but PRs would be welcome before that too, providing they don't impact the API exposed to users (but it should only be for private stuff anyway, so it should be transparent to users).

**Comment by vnen** [comment]
Note that changing names in C++ code might impact custom modules.

**Comment by bojidar-bg** [comment]
@vnen unless they are indeed "private"

**Comment by akien-mga** [comment]
There was some improvement done with #7784 and #7795. Regarding renaming the structs and singletons in core, @reduz concluded that it probably wasn't worth it for now - to be reconsidered if/when we actually run into issues with some compilers. See today's logs for details: http://godot.eska.me/irc-logs/devel/2017-02-13.log

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by reduz** [comment]
@elfring we fix when it breaks. It didn't yet in more than a decade so there's nothing to worry about.
