### ISSUE TITLE
AnimationPlayer : copy pasted animation are not set unique resource

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#5600]
**Operating system or device - Godot version:**
2.0.3 win64

**Issue description** (what happened, and what was expected):

Into the AnimationPlayer editor, when you copy/paste an animation using the little gear icon of the main tool bar, the duplicated animation is not a set unique by default. So, if you modify the content of one of them, it will also modify the other one.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by SuperUserNameMan** [comment]
btw i'm wondering what this gear icon and its "copy/paste animation" is useful for, given that i've just noticed the "duplicate" icon on the left

**Comment by akien-mga** [comment]
I guess it's a feature? Sometimes you *do* want to add a non-unique resource to another node. This allows to do it.

**Comment by SuperUserNameMan** [comment]
Hmm ... yeah. you're right. I'm seeing some use case now.

This behavior suprised me because i did not see the duplicate icon. 

So I'm closing this issue.

**Comment by SuperUserNameMan** [comment]
btw thanks @akien-mga
