### ISSUE TITLE
`Rect2 size is negative, this is not supported` error regularly toasting

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#56007]
### Godot version

4.0 ed395c6b99915809347a87b0d65220c256d6ec3f

### System information

Windows 10 64 bits GLES3 GeForce GTX 1060 6GB/PCIe/SSE2

### Issue description

When I open about any project, the following error always gets printed and brought up by the toast system:
```
ERROR: Rect2 size is negative, this is not supported. Use Rect2.abs() to get a Rect2 with a positive size.
   at: Rect2::grow_individual (D:\PROJETS\INFO\GODOT\Engine\godot4_fork\core/math/rect2.h:243)
```
It even appears to be caused by the toast system itself when errors show up, but I'm not certain yet.

It occurs again when other errors get toasted, but I'm not sure what reproduces these. But so far I got it everytime when opening projects.

### Steps to reproduce

Open any project.
If no toasts show up, make one happen. After it resolves, the error likely shows up

**Comment by Chaosus** [comment]
Probably a regression from https://github.com/godotengine/godot/pull/37626

**Comment by Zylann** [comment]
This happens because a StyleBox is drawn starting from a very thin rectangle:
![image](https://user-images.githubusercontent.com/1311555/147502877-8669ab1f-67cd-4b8c-9660-ae8c1f752608.png)
Which is grown negatively and becomes a null-area rectangle:
![image](https://user-images.githubusercontent.com/1311555/147502922-f2096773-44ed-4497-92af-49ddce9124aa.png)
And keeps being grown negatively afterward in the same function, making negative sizes appear:
![image](https://user-images.githubusercontent.com/1311555/147502958-f5034a14-cf92-4ddb-b6f3-2a4cb9bf20e7.png)
Then the next call to `grow_individual`, which does start with a check for negative size, highlights the problem.

So ironically, the function that checks for this invalid state, allows such invalid state to occur.

**Comment by Zylann** [comment]
If I try forcing `grow_individual` to never produce a negative-size rectangle (using the second snippet), this happens

![image](https://user-images.githubusercontent.com/1311555/147522281-1c25ec1c-1aae-4f2a-95ea-2f9af68fa459.png)

**Comment by Zylann** [comment]
I just tried the first snippet, seemed to work fine.

I then tried the second snippet, and Godot turned flat:
![image](https://user-images.githubusercontent.com/1311555/147525100-cf94ff82-bb15-4c2a-af3b-37b7c00f5d64.png)
