### ISSUE TITLE
Vulkan: Alpha scissor/test material has pixel Z-order issues

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#56008]
### Godot version

4.0 ed395c6b99915809347a87b0d65220c256d6ec3f

### System information

Windows 10 64 bits GLES3 GeForce GTX 1060 6GB/PCIe/SSE2

### Issue description

When I use an alpha clip material for foliage, I expect it to behave like an opaque material, going through the opaque rendering pass, so it should not have Z-ordering issues in its pixels. However it looks like it does have that typical issue:
![image](https://user-images.githubusercontent.com/1311555/146481554-2ac6442e-eadd-42a6-89b0-302bc2e52566.png)

### Steps to reproduce

1) Create a mesh made of two intersecting quads (or make two separate quads), typical setup for classic grass
2) Create a new `StandardMaterial3D` with `transparency` set to `Alpha Clip` and an albedo texture.
3) Assign the material to the mesh instances.
4) Observe they completely disappear with Vulkan errors. I assume that's a different issue. Close the scene and reopen it. Observe the clipping issue.

### Minimal reproduction project

[AlphaClip.zip](https://github.com/godotengine/godot/files/7731788/AlphaClip.zip)

**Comment by tinmanjuggernaut** [comment]
The MRP can no longer be opened in Alpha13. However Alpha Scissors no longer has this issue with z-order. There are other z-order issues in the pipeline and I'll open another ticket, but it's no longer present here.

![image](https://user-images.githubusercontent.com/632766/181908178-ecb0ba98-08da-483c-8130-50c979118e88.png)
