### ISSUE TITLE
Editor popup menu's corners are not transparent

### ISSUE THREAD

**Issue by floppyhammer** [godotengine/godot#56009]
### Godot version

v4.0.dev.custom_build [ed395c6b9]

### System information

Windows 11, Vulkan Clustered

### Issue description

![2021-12-17 151935](https://user-images.githubusercontent.com/28705694/146505696-49690eb5-d3fc-4faf-99b3-3495c7248cde.png)

### Steps to reproduce

None.

**Comment by egiezen** [comment]
This is because PopupMenu inherits the Window class. The window must be transparent in order to get the right appearance.

**Comment by Calinou** [comment]
This is expected, as windows do not have per-pixel transparency enabled (it would slow things down and could cause things to break).

Instead, I would suggest making PopupMenu corners non-rounded to fix this.
