### ISSUE TITLE
Fonts saved by Godot cannot be loaded

### ISSUE THREAD

**Issue by markdibarry** [godotengine/godot#56018]
### Godot version

4.0.dev (58712e9)

### System information

Windows 10, Vulkan

### Issue description

Fonts Resources saved by Godot cannot be opened by Godot.

![image](https://user-images.githubusercontent.com/21325943/146551666-f4199d57-89c0-41f5-8643-531d20735f6e.png)

### Steps to reproduce

1. Create a Label node.
2. Select New Font in the Theme Overrides.
3. Add a font to the Font Data section.
4. Save Font Resource.
5. Try to load Font Resource just saved.

**Comment by pycbouh** [comment]
It seems that you saved the `FontData` part of the font resource, not the `Font` resource itself.

**Comment by markdibarry** [comment]
Here is where I saved. Is this not correct?

![image](https://user-images.githubusercontent.com/21325943/146555540-9e1ef70a-b25a-428b-b627-610b609ba4e3.png)

**Comment by Calinou** [comment]
I can't reproduce this on `master` 1cbf3947d. If I save a Font resource (not FontData) then create a new Label and load the font resource there into the font override property (not FontData, again), it works as expected.

**Comment by markdibarry** [comment]
Interesting. I was able to reproduce this bug multiple times this morning. I'm trying to replicate it again, and it's working fine now. I'm going to close this until I can figure out how to reproduce this consistently.
