### ISSUE TITLE
Font Resource clear button doesn't work

### ISSUE THREAD

**Issue by markdibarry** [godotengine/godot#56020]
### Godot version

4.0.dev (58712e9)

### System information

Windows 10, Vulkan

### Issue description

After creating or adding a Font Resource, selecting the "Clear" button doesn't work.

![image](https://user-images.githubusercontent.com/21325943/146556826-cd4bfcc3-f4ff-4a11-9c15-f65dd211bb58.png)

The following message shows in the console:

![image](https://user-images.githubusercontent.com/21325943/146556898-9d407b41-f4cd-404e-b2f5-bd39d9a7b206.png)

### Steps to reproduce

1. Create a new project.
2. Create a Label node.
3. Add a Font Resource to the label.
4. Select "clear", from the Font Resource dropdown.

**Comment by Calinou** [comment]
I can confirm this on `master` 1cbf3947d.

**Comment by bruvzg** [comment]
Seems like it's caused by #47252, same happens with the style boxes.

cc @KoBeWi
