### ISSUE TITLE
export vars are lost/reset upon saving a script with a syntax error

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#5603]
**Operating system or device - Godot version:**

Ubuntu 16.04

**Issue description** (what happened, and what was expected):

If you restart the project with an error in the script, then the reset value of the variable in the Inspector.

**Steps to reproduce:**
1. `export var test = 'a'`
2. The inspector 'a' change to 'b'
3. Add a string to simulate errors.
4. `export var test = 'a'
x`
5. Save the project and restart the project.
![2016-07-09 07-55-39](https://cloud.githubusercontent.com/assets/11325733/16705122/5bca1d54-45b3-11e6-879e-6936091d7d53.png)

**Comment by akien-mga** [comment]
I can confirm the bug. If you save a script with a syntax error (be it at the global scope as shown by @DimaKiva, or within a function such as e.g. `get_node(` in `_ready()`), the export vars are removed, and thus their values are lost from the scene.

**Comment by DualMatrix** [comment]
Still relevant in master.

**Comment by vnen** [comment]
Hm, I thought #20583 would fix this, but apparently it didn't.

**Comment by TheRadMatt** [comment]
Please fix this issue. Making any changes to a tool node is basically impossible in a more complicated game, because the values reset in every single instance.

**Comment by neikeq** [comment]
This should have been fixed by #20583. I will have a look.

**Comment by DualMatrix** [comment]
I'm still encountering this issue on the current master :(

**Comment by neikeq** [comment]
@DualMatrix Can you open a new issue with the steps to reproduce it?

**Comment by pouleyKetchoupp** [comment]
@neikeq I'm able to reproduce this issue on master, with the exact same steps, except you need to save the project 2 times in a row in step 5. Do I need to open a new issue?
