### ISSUE TITLE
Vulkan: LightmapGI does not take GridMap into account for baking

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#56030]
*See https://github.com/godotengine/godot/issues/56027 for the same issue with LightmapGI + MultiMesh, and https://github.com/godotengine/godot/issues/56031 for the same issue with GridMap + SDFGI.*

### Godot version

4.0.dev (1cbf3947d)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 470.74)

### Issue description

LightmapGI does not take GridMaps into account for baking. On the left, you can clearly notice the indirect lighting, but it's completely missing on the right:

Left: Individual MeshInstances, right: MultiMeshInstance:

![2021-12-17_18 30 58](https://user-images.githubusercontent.com/180032/146586155-d6337272-f9f9-4f8b-9910-7b5cfae2bcff.png)

This is a regression from `3.x`, as GridMap + BakedLightmap setups worked there.

In comparison, VoxelGI works:

![2021-12-17_18 32 33](https://user-images.githubusercontent.com/180032/146587924-83ea7540-f17f-4d4f-a628-d8a39c71c3ee.png)

VoxelGI lighting debug draw mode:

![2021-12-17_18 34 02](https://user-images.githubusercontent.com/180032/146587939-a0edf7e9-8450-4484-abed-305a2a46cfad.png)

### Steps to reproduce

***Note:** An imported 3D scene with UV2 generated must be used. You cannot use primitive meshes for testing this, as they do not contain a UV2 layer and it can't be generated using the MeshInstance tools. The minimal reproduction project includes a ready-to-use setup for testing this.*

- Import a 3D scene with **Static Lightmaps** bake mode. Click **Advanced** in the import dock, go to the Meshes tab and enable **Save to File**. Specify a path to a `.tres` file to save.
- Add a MeshInstance3D node with the mesh resource loaded to act as a floor. Scale it so it can fit several objects on top. Set the global illumination mode to **Baked** in the inspector.
- Add a GridMap node. Use the GridMap menu at the top of the 3D editor to create a new item. Load in the mesh resource in the inspector. Place a few GridMap tiles at varying heights (<kbd>Shift</kbd> + Mouse wheel).
- Add a LightmapGI, select it and click **Bake** at the top of the 3D editor viewport.

### Minimal reproduction project

~~[test_lightmapgi_gridmap.zip](https://github.com/godotengine/godot/files/7736932/test_lightmapgi_gridmap.zip)~~

*With `.godot/` included to workaround importing issue:* [test_lightmapgi_gridmap_1.zip](https://github.com/godotengine/godot/files/7777211/test_lightmapgi_gridmap_1.zip)

**Comment by williamd67** [comment]
Opening the attached `minimal reproduction project` gives the following error on master:
![Screenshot from 2021-12-24 10-36-06](https://user-images.githubusercontent.com/10560119/147341187-640161a6-3b58-4658-b679-e043e6b5fd9b.png)

Probably due to this, there is no UV2 for the gridmap:
![Screenshot from 2021-12-24 10-36-46](https://user-images.githubusercontent.com/10560119/147341266-a4879db9-32a1-4920-b1ef-899666c95f5f.png)

I did not try to create the project myself. It would help if the project can be corrected.

**Comment by Calinou** [comment]
@williamd67 This is strange. I can open the freshly downloaded MRP on 489f11ee0, even if `.godot/` is removed beforehand.

**Comment by williamd67** [comment]
My steps on Ubuntu 20.04:
```
mkdir ~/godot-working-directory
cp test_lightmapgi_gridmap.zip ~/godot-working-directory
cd ~/godot-working-directory
unzip test_lightmapgi_gridmap.zip
start godot (debug build: ./bin/godot.linuxbsd.tools.64) with the following options: --editor --path ~/godot-working-directory/test_lightmapgi_gridmap/
```
After that I get the following errors after opening:
```
-- Debug adapter server started ---
--- GDScript language server started ---
  Cannot open file 'res://.godot/imported/cube.glb-ec927bc01951d93b2130ba52799eca7c.scn'.
Switch Scene Tab
  scene/resources/resource_format_text.cpp:170 - res://Node3D.tscn:108 - Parse Error: [ext_resource] referenced non-loaded resource at: res://cube.tres
  scene/resources/resource_format_text.cpp:269 - res://Node3D.tscn:108 - Parse Error: [ext_resource] referenced non-loaded resource at: res://cube.tres
  servers/rendering/renderer_rd/renderer_storage_rd.cpp:1654 - Condition "!material" is true.
  Failed loading resource: res://Node3D.tscn. Make sure resources have been imported by opening the project in the editor at least once.
  editor/editor_data.cpp:554 - Index p_idx = 1 is out of bounds (edited_scene.size() = 1).
```
It seems that the ext_resource is not properly re-imported when it does not exist in the `.godot/` directory yet.

@Calinou, maybe, to unblock this issue, you can add the `.godot/`directory to the zip. 

BTW: I have the same issue for #56027.

**Comment by Calinou** [comment]
> @Calinou, maybe, to unblock this issue, you can add the .godot/directory to the zip.
>
> BTW: I have the same issue for #56027
and #55868.

Done on all 3 issues :slightly_smiling_face:
