### ISSUE TITLE
Embed PCK option doesn't support PCK over 2 GB on Windows.

### ISSUE THREAD

**Issue by AgentSmith0** [godotengine/godot#56051]
### Godot version

3.4.1

### System information

Linux, GLES3

### Issue description

I exported a big project for Windows with embedded PCK in Godot 3.4.1. When I try to execute the game, I get the following alert:
![Screenshot_20211218_154003](https://user-images.githubusercontent.com/67276662/146645079-314cef18-6659-4a87-b01b-2b6068dd5c8c.png)
 
Exporting for Linux, macOS or Windows without embedded PCK works fine (gives a file of about 5 GiB).

### Steps to reproduce

Export a big project with embedded PCK for Windows in Godot 3.4.1.

**Comment by Calinou** [comment]
@AgentSmith0 Can you reproduce this in any of the [3.4.1 RCs](https://downloads.tuxfamily.org/godotengine/3.4/) to determine when the regression started?

**Comment by AgentSmith0** [comment]
@Calinou Yes, it works when I disable PCK embedding. I will now try to determine when the regression has started.

**Comment by bruvzg** [comment]
Are use exporting 32-bit or 64-bit executable, 32-bit exports can't have more than 4 GB embedded due to EXE format limitations.

**Comment by AgentSmith0** [comment]
@bruvzg I am exporting for Windows 64-bit on a 64-bit machine.

**Comment by bruvzg** [comment]
Is any of the `rcedit` related properties (`application/*` export settings, like icon) or code signing enabled? Is it working if none of this is enabled?

Seems like the size of the embedded data is a 32-bit value even in the 64-bit executable.
https://github.com/godotengine/godot/blob/8485d0c53a55ee0295187a3144b390f35787b57d/platform/windows/export/export.cpp#L127-L130

**Comment by bruvzg** [comment]
Seems like the real limit is even lower, only 2 GB for both 32 and 64 executables:

> > PE32+ images allow for a 64-bit address space while limiting the image size to 2 gigabytes.
>
> Quote from the PE spec: https://docs.microsoft.com/en-us/windows/win32/debug/pe-format

Since it's format limitations, it can't be fixed, but we should add a check and error message if it's too big and update the documentation.

**Comment by AgentSmith0** [comment]
Thank you for the information. I think this issue can then be closed.
