### ISSUE TITLE
macOS: Editor slow and flickering, artifacts all over the place (regression in 3.4.1)

### ISSUE THREAD

**Issue by Krumelur** [godotengine/godot#56055]
### Godot version

3.4.1 stable

### System information

macOS Monterey 12.1 on MacBook Air M1 (8 cores, 16GB RAM)

### Issue description

Since version 3.4 the editor flickers and shows artifacts, typically when zooming the scene.
I'm running the Mono version of the editor.
I did not have this problem with Godot 3.3, however, there have of course been some macOS updates, so it could also be a graphic issue on Apple's side.

The issue is independent of the used screen. I can observe it on the built-in display as well as on a monitor connected via USB-C.

Here's a still image showing the problem and also a link to a video showing the problem in more detail. Look at the left hand side of the screenshot below the node tree or at the top part of the node tree.

![artifacts](https://user-images.githubusercontent.com/574373/146645491-b1c26205-e43e-4deb-96cf-45fdd18fb837.png)

Video: https://www.youtube.com/watch?v=uUi9mERvEUU

### Steps to reproduce

* Start a new project using Godot. Add a couple of sprites to the scene. The severity of the issue increases with the number of textures being rendered.
* Move mouse cursor around or start zooming in and out using the trackpad

### Minimal reproduction project

Really any project will do.

**Comment by akien-mga** [comment]
> I did not have this problem with Godot 3.3, however, there have of course been some macOS updates, so it could also be a graphic issue on Apple's side.

Could you test 3.3 again to confirm if it's a Godot regression or related to an OS update?

**Comment by Krumelur** [comment]
@akien-mga That was was actually a very good idea! And the answer is, no, it's **not happening with 3.3.4 stable**! So it was indeed introduced by Godot.

**Comment by Calinou** [comment]
@Krumelur Can you reproduce this in any of the [3.4 betas and RCs](https://downloads.tuxfamily.org/godotengine/3.4/) to determine when the regression started?

**Comment by Krumelur** [comment]
@Calinou It's **starting with 3.4.1 RC1**. 3.4 stable is still fine.

**Comment by mattchala** [comment]
the same editor flickering is happening to me on my mac m1 air in 2d mode.  does not happen in the same project in 3.4

**Comment by avanwinkle** [comment]
I see that a PR is open for a fix, thanks @bruvzg .

Just to add a data point, I'm still on Mojave 10.14.6 using Intel core i7 and I see this same behavior, so it doesn't appear to even be limited to M1 chips.

**Comment by Calinou** [comment]
Could anyone affected by this bug try to build https://github.com/bruvzg/godot/tree/macos_gl_off_ctx from source? See instructions: https://docs.godotengine.org/en/stable/development/compiling/compiling_for_osx.html

**Comment by avanwinkle** [comment]
@Calinou Just gave it a run on my M1 (first time building Godot!) and it seems... _very_ nice. Super fast moving and zooming, no glitches that I can see! I'll make a build for my Intel, just to be sure.

**Comment by avanwinkle** [comment]
Looks real good on Intel Macs too! Thanks for the quick investigation! 🚀

**Comment by akien-mga** [comment]
Fixed by #56059.
