### ISSUE TITLE
Godot v4 crashes and screen turns black

### ISSUE THREAD

**Issue by paddy-exe** [godotengine/godot#56067]
### Godot version

4.0dev (commit 8485d0c)

### System information

Windows 10, AMD Ryzen 5 2600, AMD Radeon RX 580 Series

### Issue description

When running the compiled executable the following error messages appear:
![godot-error-pic1](https://user-images.githubusercontent.com/38077837/146659482-43d324b6-380a-4fc6-812e-8b6c95186b50.png)
![godot-error-pic2](https://user-images.githubusercontent.com/38077837/146659485-a7a2bcac-d66f-4221-ab1a-43256210ae10.png)
Godot shows that it is in the Project Managment in the title bar but then turns black after a few seconds

For further information:
I have already built and run Godot 4 like 1-2 months ago and it didn't crash at that time.

### Steps to reproduce

1. Compile Godot
2. Run the compiled build

**Comment by paddy-exe** [comment]
@Calinou I think you might have misread the label of my OS. Mine is windows but you added Linux as the OS label. Or was that intentional?

**Comment by Calinou** [comment]
> @Calinou I think you might have misread the label of my OS. Mine is windows but you added Linux as the OS label. Or was that intentional?

I misread the issue, sorry.

**Comment by paddy-exe** [comment]
No idea how this issue got fixed, but both a custom build and the v4.0.dev.20220118.official [bc5ba38ff] works perfectly now on my maschine! I will close this issue then

**Comment by clayjohn** [comment]
Glad to hear that it is working now!
