### ISSUE TITLE
Godot 3.4.1 HTTP Request too long? (Android)

### ISSUE THREAD

**Issue by GogetaX** [godotengine/godot#56065]
### Godot version

3.4.1

### System information

Windows 10, Android

### Issue description

Hello,
I found a problem with godot HTTPRequest,
when I use the request using the exe or html5, everything is working correct.

but when I export it to Android, the request takes up to 30 seconds to return.
the response_code is 200, so everything is went fine.

but it takes 30 seconds to get a response?

![image](https://user-images.githubusercontent.com/51264046/146658348-c37ed993-713d-40da-b95a-994b59b9cc5a.png)
![image](https://user-images.githubusercontent.com/51264046/146658509-1f9974c0-746a-4088-bca1-ea9bbca9326f.png)

[HTTPRequestTest.zip](https://github.com/godotengine/godot/files/7740105/HTTPRequestTest.zip)
!

### Steps to reproduce

run the godot project i created on windows
run the same project on android.

**Comment by Calinou** [comment]
@GogetaX Can you reproduce this on 3.3.4 and/or 3.4?

**Comment by GogetaX** [comment]
I think i solved the problem. 
for some reason my wifi was delaying those requests as it turns out.
i factory reset the wifi and it working now.
