### ISSUE TITLE
ARVRCamera with viewport freezes interface

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#56069]
### Godot version

3.4.x e937963007ed005e2564a8b574f7437fed173193

### System information

Windows 10

### Issue description

Due to a fix done to prevent the viewport from resizing based on the window resize (the viewport size when ARVR is enabled is controlled by the ARVRServer as it needs to be much larger than what ends up being displayed), when using a secondary viewport no buffers are created until the ARVRInterface is initialised.  This never happens in the editor resulting in Godot failing when rendering a preview of the viewport.

The workaround for this is to leave the ARVR switch on the viewport off and enable it in code after the ARVRInterface is initialised.

The fix for this should be that `vp->size = arvr_interface->get_render_targetsize();` is executed earlier

### Steps to reproduce

Create a scene with a viewport as the root node with arvr enabled and a size set
Add an ARVROrigin node
Add an ARVRCamera node

Watch the UI becoming unresponsive

**Comment by akien-mga** [comment]
Fixed by #56072.
