### ISSUE TITLE
Vulkan: Subviewport Debug Draw rendering incorrectly

### ISSUE THREAD

**Issue by Leakbang** [godotengine/godot#56064]
### Godot version

v4.0.dev.calinou [b0e93711b]

### System information

Linux Kubuntu, Vulkan, NVIDIA GeForce GTX 1050 Ti, Driver Version: 495.44 

### Issue description

The `Debug Draw` options in `Rendering` doesn't appear to apply the corresponding effects. For example Wireframe displays Overdraw, Overdraw displays Lighting, and also Unshaded doesn't appear to be working correctly.

### Steps to reproduce

- Create a SubViewport and assign a Camera to it
- Enable any of the options in `Rendering -> Debug Draw`

**Comment by Calinou** [comment]
Note: This applies to the SubViewport debug draw property, **not** the debug draw mode options listed in the 3D editor's Perspective menu.

**Comment by ARez2** [comment]
Yeah i just ran into the same problem. I found a little workaround:
```gdscript
func _ready() -> void:
	$SubViewportContainer/SubViewport.debug_draw = Viewport.DEBUG_DRAW_WIREFRAME
```
Fixed the issue but of course this should be fixed in the editor.

**Comment by clayjohn** [comment]
Likely the enum names are in the wrong order in the property registration

**Comment by HalcyonGarside** [comment]
It looks like the order is generally correct, though the "Lighting" name is unincluded in the Debug Draw options which offsets the values of the last two names in the menu by one.  Do you think the solution to this issue would just be to add "Lighting" to the property registration?

**Comment by clayjohn** [comment]
Ya, that sounds fine
