### ISSUE TITLE
CPU lightmapper does not react to non-default environment Color, Energy or Sky Contribution when using the Scene environment mode

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#56078]
*Related to https://github.com/godotengine/godot/issues/56138 (which is the same issue but for `master`'s GPU lightmapper).*

### Godot version

3.4.stable, 3.5.beta (71d8ccbe9)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 470.74)

### Issue description

The CPU lightmapper does not react to non-default environment Color, Energy or Sky Contribution in WorldEnvironment when the BakedLightmap is configured to use the **Scene** environment mode. I made sure to bake lightmaps again after changing the Environment's ambient light properties.
The CPU lightmapper _does_ react to custom sky orientation/rotation though.

This may also be occuring when using the **Custom Sky** environment mode in BakedLightmap, but I didn't test that yet.

*Left: real-time ambient lighting, right: baked ambient lighting*

### Default environment settings

![2021-12-20_00 34 09](https://user-images.githubusercontent.com/180032/146695123-2dcfa071-b881-4ee0-860b-2e8e0e184ebd.png)

### Ambient Color `#000000`, Sky Contribution = 0.5, Energy = 1.0

![2021-12-20_00 35 02](https://user-images.githubusercontent.com/180032/146695124-a29b04bb-d434-4b79-8385-abe5a23231a0.png)

### Ambient Color `#000000`, Sky Contribution = 1.0, Energy = 0.5

![2021-12-20_00 36 22](https://user-images.githubusercontent.com/180032/146695125-279fbc37-a120-44c5-afb4-61f41f64e7c2.png)

### Ambient Color `#604020`, Sky Contribution = 0.0, Energy = 1.0

![2021-12-20_00 37 42](https://user-images.githubusercontent.com/180032/146695127-b8338930-7042-438e-9d1f-d8cc0f07881b.png)

### Steps to reproduce

- Add a WorldEnvironment node. Configure a ProceduralSky.
- Add a BakedLightmap node. Set the environment mode to **Scene**.
- Instance two identical 3D scenes imported with the **Gen Lightmaps** option. One of them must be placed inside the BakedLightmap's bounds, whereas the other one must be placed *fully* outside – its AABB must not touch the BakedLightmap's bounds.
- Select the BakedLightmap node and click **Bake Lightmaps** at the top of the 3D editor viewport.
- Remember to bake lightmaps every time you adjust the ambient light settings!

### Minimal reproduction project

[test_lightmap_environment_3.x.zip](https://github.com/godotengine/godot/files/7741799/test_lightmap_environment_3.x.zip)

**Comment by akien-mga** [comment]
Fixed by #62260.
