### ISSUE TITLE
Add _released() virtual method to BaseButton, the contrary to the already existing _pressed()

### ISSUE THREAD

**Issue by Nearoo** [godotengine/godot#5608]
I find the current system with the `set_click_on_press(bool enable)`-method rather awkward to use. Often, it would be usefull if a `_pressed()` method in combination with a `_released()` method would exist. Here's my proposal:
- `_pressed()` Called when button _begins_ being pressed
- `_released()` Contrary to `_pressed()`: Called when button _stops_ being pressed
- `_clicked()` Works like the current `_pressed()` method works

**Comment by vnen** [comment]
Related to #4625. Adding to my list of confusing API.

**Comment by reduz** [comment]
we will rewrite this for 3.0 and break compatibility to make it more obvious

**Comment by akien-mga** [comment]
This was fixed in 3.0 as part of the API refactoring (#5696).
