### ISSUE TITLE
Set mouse mode capture has an error

### ISSUE THREAD

**Issue by HectorVe** [godotengine/godot#56084]
### Godot version

3.4.1

### System information

Windows 10

### Issue description

In the function Capture Mouse whien is capture, this begin to, capture and uncapture the mouse randomly. This made that my game will be not playable correctly.

### Steps to reproduce

https://user-images.githubusercontent.com/63373779/146702384-69c55e14-d2ce-497b-a56e-568d5da48140.mp4

**Comment by Calinou** [comment]
@HectorVe Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
