### ISSUE TITLE
Godot 4 Gridmap navigation - agent ignores target and moves to Gridmap's origin instead.

### ISSUE THREAD

**Issue by macryc** [godotengine/godot#56099]
### Godot version

v4.0.dev.calinou.f09d88443

### System information

Win10, GLES3, RTX 2070 mobile

### Issue description

When using 3d gridmap with per-tile navmesh, the agent doesn't move towards the target. Instead it moves towards the center of the gridmap node.

### Steps to reproduce

1. Start a 3d scene, create a mesh instance - plane
2. Duplicate the mesh, turn one into a navigation mesh (Mesh > Create Navigation Mesh) and make it a child of the first one
3. Turn the other into a Trimesh Static Body).
4. Convert the scene into a mesh library.
5. start a new scene
6. create a characterbody3d with capsule mesh, attach the player script (project attached hereto)
7. create a navigationagent3d as a child of the characterbody3d and connect to the function in the script
8. create a gridmap, load the mesh library (make sure the tile has a navmesh - sometimes it doesn't save when converting scene to mesh lib)
9. draw some tiles on the grid
10. put the character on the grid
11. create a 3d node for target and place it somewhere on the grid
12. run the game - the character node will move towards the center of the grid map, ignoring its target completely

### Minimal reproduction project

[Navitest.zip](https://github.com/godotengine/godot/files/7745526/Navitest.zip)

**Comment by Calinou** [comment]
> 4.0 dev

Please edit your issue to specify the exact build commit, as 4.0.dev is a moving target.

**Comment by macryc** [comment]
> > 4.0 dev
> 
> Please edit your issue to specify the exact build commit, as 4.0.dev is a moving target. You can copy the build version by clicking the version identifier at the bottom of the editor, in the project manager or in the About dialog.

Done. This issue is actually also present in multiple other builds.

**Comment by smix8** [comment]
The GridMap does not build and register the NavigationMeshes correctly on the NavigationServer so the grid cell navregions are never merged and the only point available on the navigation is the scene origin in the center.

The first issue is that the "bake_navigation" stores NavigationMeshes that do not fit their own properties, especially when imported from another software the mesh has nothing to do with the NavigationMesh properties so when the NavigationServer wants to merge the regions based on e.g. cell_size and other properties it fails with a million error messages.

The seconds issue is that the GridMap does not add or update the navregions correctly when joining the SceneTree.
