### ISSUE TITLE
keyword "pass" does not accept ";" after it

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#5610]
**Operating system or device - Godot version:**
2.0.3stable

**Issue description** (what happened, and what was expected):

The keyword `pass` does not accepts `;` just after it.

TBH, i don't really care about this "bug". 

I open this issue just in case it is the symptom of an underlying more obscure bug into the gdscript parser or the script editor.

**Steps to reproduce:**

````
func whatever(): #{
    pass;
#}
````

-----> ``error( XXX, xx ): Error parsing expression, misplaced : ";"``

**Link to minimal example project** (optional but very welcome):

**Comment by akien-mga** [comment]
Confirmed, and it gives the same error if a `;` is alone on a line. On the other hand `print("test");` is fine.

Most likely `pass` is just ignored by the parser, so it ends up like a `;` alone by itself, and GDScript considers it a syntax error. So I'm not sure in the end if it's a bug or a feature; it might be intended that GDScript sees those a syntax errors. I don't have a strong opinion myself :)

**Comment by timoschwarzer** [comment]
I think a single ; somewhere should be valid. (Like e.g. in Java [I don't know how it's in Python])

**Comment by Sslaxx** [comment]
Perhaps the ability to use ; like that should be removed?

**Comment by SuperUserNameMan** [comment]
@Sslaxx : what do you mean bu "like that" ?

**Comment by Sslaxx** [comment]
In the way that C/C++ does. C-family languages require the semicolon at the end of a line; GDScript does not. The fact that you can (apparently) use a semicolon at the end of a line seems a little odd, and causes issues like this one.

**Comment by akien-mga** [comment]
The fact is that the semicolon *has* a purpose in GDScript, as you can do:
```
func _ready():
    print("Test"); var hello = get_node("world")
```

**Comment by Sslaxx** [comment]
If that's so then make it **mandatory**.

**Comment by akien-mga** [comment]
I don't see why.

**Comment by akien-mga** [comment]
BTW Python works the same:
```
Python 2.7.12 (default, Jul  6 2016, 12:09:17) 
[GCC 5.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> test = []; print(test)
[]
>>> ;
  File "<stdin>", line 1
    ;
    ^
SyntaxError: invalid syntax
>>> pass
>>> pass;
```

We just need to fix the parsing of `pass;` then and we'll be exactly like Python.

**Comment by vnen** [comment]
For reference, JavaScript is kind of the opposite of Python: the use of semicolons are preferred but they are also optional.

Making GDScript syntax closer to Python is better, less surprise for the users.
