### ISSUE TITLE
Editor laggy & slow on Intel Mac in 3.4.1

### ISSUE THREAD

**Issue by umutseven92** [godotengine/godot#56114]
### Godot version

3.4.1

### System information

MacOS Monterey 12.1, 2.6 GHz 6-Core Intel Core i7

### Issue description

After upgrading to 3.4.1, after a couple minutes of usage, the Godot editor becomes very laggy and slow. It is especially noticeable when scrolling- it's almost like there is an input delay. 

The slowdown appears when running game too (via the Play button). 

I've downgraded to 3.4.0 and that solved to problem, so I believe this is a regression. 

Please let me know if any more information is needed.

Godot version: 3.4.1
System: MacOS Monterey 12.1, 2.6 GHz 6-Core Intel Core i7

### Steps to reproduce

- Open a project in Godot 3.4.1
- Use for a couple of minutes

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/56055 (same cause).

**Comment by umutseven92** [comment]
Apologies @Calinou , I did go over recent issues, but must have missed it.
