### ISSUE TITLE
Can't revert font size

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#56123]
### Godot version

5ffee63

### System information

W10

### Issue description

The property revert for font size seems to be broken. The arrow appears in weird place, does nothing and there is no way to remove it no matter the value.
![image](https://user-images.githubusercontent.com/2223172/146906560-8d0f8781-54ee-43f7-82cd-572505fbff99.png)

### Steps to reproduce

1. Add e.g. Label
2. Check font sizes in theme overrides

**Comment by jmb462** [comment]
I can't reproduce this issue (with v4.0.dev.custom_build [d32185873]).

Arrow is at weird place if there is not enough width but it's still working.

![font_size](https://user-images.githubusercontent.com/3649998/146915448-6db74f8c-414d-4423-aa91-d8d24f9014ff.gif)

**Comment by KoBeWi** [comment]
Eh, doesn't seem to be happening anymore.
