### ISSUE TITLE
Drag and drop reparenting bug with multiple nodes with children

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#5613]
**Operating system or device - Godot version:**
Mageia 6 x64, current Godot HEAD.

**Issue description** (what happened, and what was expected):
Reparenting multiple groups of nodes (i.e. nodes with children) with drag and drop can lead to weird results e.g.:

- My selection
![spectacle w25473](https://cloud.githubusercontent.com/assets/4701338/16708736/6f8c9fc0-45fd-11e6-8cf3-517efddc0e4e.png)
- I drag and drop between "copyright" and "welcome":
![spectacle s25499](https://cloud.githubusercontent.com/assets/4701338/16708741/968c5bc4-45fd-11e6-9c17-30976bb3a0a2.png)
- Result: all the children of "sky_foreground" got messed up and added as siblings.
- It doesn't even preserve order as "alpaca_container" gets nudged between two were-children-now-siblings of "sky_foreground".

**Steps to reproduce:**
See above.

**Comment by reduz** [comment]
Actually now that #5515 is fixed, this is now most likely irreproducible

**Comment by akien-mga** [comment]
It seems to be fixed yes.
