### ISSUE TITLE
Vulkan: Environment custom sky rotation is not rendered correctly

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#56136]
### Godot version

4.0.dev (489f11ee0)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 470.74)

### Issue description

The environment custom sky rotation is not rendered correctly. The sky rotates wildly depending on the camera's angle in an unexpected manner.

### `3.x` (works as expected)

https://user-images.githubusercontent.com/180032/146974985-b3092e6c-13e8-404b-9c18-d86bf75fe364.mp4

### `master` (broken)

https://user-images.githubusercontent.com/180032/146975044-02bdac46-1a33-4375-8de2-9c48b9960c47.mp4

### Steps to reproduce

- Add a WorldEnvironment node with a PanoramaSkyMaterial. Adjust the sky's rotation in the resource options (try `(0, 0, 1.57)`, values are in radians in `master` but in degrees in `3.x`).
- Rotate the camera around in the 3D editor and see how the sky behaves compared to `3.x`.

### Minimal reproduction project

[test_lightmap_environment_custom_orientation_master.zip](https://github.com/godotengine/godot/files/7757010/test_lightmap_environment_custom_orientation_master.zip)

**Comment by Zylann** [comment]
I had this problem too with panorama skies
