### ISSUE TITLE
Vulkan: LightmapGI does not react to non-default environment Color, Energy or Sky Contribution when using the Scene environment mode

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#56138]
*Related to https://github.com/godotengine/godot/issues/56078 (which is the same issue but for `3.x`'s CPU lightmapper).*

### Godot version

4.0.dev (489f11ee0)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 470.74)

### Issue description

The GPU lightmapper does not react to non-default environment Color, Energy or Sky Contribution in WorldEnvironment when the BakedLightmap is configured to use the **Scene** environment mode. I made sure to bake lightmaps again after changing the Environment's ambient light properties.
The GPU lightmapper does not react to custom sky rotation either: https://github.com/godotengine/godot/issues/56135

*Left: real-time ambient lighting, right: baked ambient lighting*

### Default environment settings

![2021-12-21_19 11 36](https://user-images.githubusercontent.com/180032/146979070-e7098154-a800-4c63-819f-afe2a8e39f26.png)

### Ambient Color `#000000`, Sky Contribution = 0.5, Energy = 1.0

![2021-12-21_19 12 22](https://user-images.githubusercontent.com/180032/146979074-d675ba5f-471b-4229-a7eb-8798dad6d7bf.png)

### Ambient Color `#604020`, Sky Contribution = 0.0, Energy = 1.0

![2021-12-21_19 13 27](https://user-images.githubusercontent.com/180032/146979078-69e61666-df1f-4961-b00e-8498b8c8e282.png)

### Steps to reproduce

- Add a WorldEnvironment node. Configure a ProceduralSky.
- Add a LightmapGI node. Set the environment mode to **Scene**.
- Instance two identical 3D scenes imported with the **Static Lightmaps** option. Right-click one of them in the Scene tree dock then enable **Editable Children**. Select its child mesh and set **Global Illumination > Mode** to **Disabled**, so that it is not included in baking.
- Select the BakedLightmap node and click **Bake Lightmaps** at the top of the 3D editor viewport.
- Remember to bake lightmaps every time you adjust the ambient light settings!

### Minimal reproduction project

[test_lightmap_environment_master.zip](https://github.com/godotengine/godot/files/7757240/test_lightmap_environment_master.zip)

**Comment by tbillington** [comment]
This seems to be broken in godot 4.1 (haven't tested any other versions).

LightmapGI Disabled

<img width="1766" alt="Screenshot 2023-10-17 at 10 17 54 am" src="https://github.com/godotengine/godot/assets/2771466/f302ade7-8261-455c-90ee-44c5ef1571d8">


LightmapGI Enabled and clicked `Bake Lightmaps`

<img width="1789" alt="Screenshot 2023-10-17 at 10 18 28 am" src="https://github.com/godotengine/godot/assets/2771466/bd45f9cb-d6d4-4f44-93b5-4f5a6aeb8162">


LightmapGI Settings

<img width="377" alt="Screenshot 2023-10-17 at 10 19 00 am" src="https://github.com/godotengine/godot/assets/2771466/66c2ad7f-161b-4a07-a193-1bed051b4ac4">

**Comment by AThousandShips** [comment]
Please open a new report as this issue was fixed so not the same issue
