### ISSUE TITLE
Android question

### ISSUE THREAD

**Issue by The-Sapphire-Starship** [godotengine/godot#56141]
### Godot version

3.3-stable

### System information

Android device

### Issue description

This is not a bug, this is a question, if there is a better place to ask this please let me know.

Is there a way that I can build the Godot editor (the editor, not a godot project) into an apk and be able to run it on an Android tablet?

### Steps to reproduce

Open a GitHub issue on the Godot Engine GitHub page and ask the same question I am above

**Comment by Calinou** [comment]
The Godot editor does not support Android yet, see https://github.com/godotengine/godot-proposals/issues/1061.

PS: In the future, please use [other community platforms](https://godotengine.org/community) for support questions. This issue tracker is now meant to be used for bug reports only :slightly_smiling_face:
