### ISSUE TITLE
Accent Color in Editor Settings makes console messages icons unreadable.

### ISSUE THREAD

**Issue by seppoday** [godotengine/godot#56158]
### Godot version

4.0 dev 20211004

### System information

Windows 10

### Issue description

Changing Accent Color in editor theme setting affects icons in console. If you change it to red, then everything looks like a warning etc. It is confusing. That setting probably should not affect those icons.

Before:
![Godot4 normal color](https://user-images.githubusercontent.com/62170071/147093331-1273a1f6-d953-408a-9dd7-9ea589103a42.jpg)

After:
![Godot4 accent color](https://user-images.githubusercontent.com/62170071/147093329-4b513a04-ce78-4309-b2a3-db24c4401aa8.jpg)

I think Accent Color should not affect icons for messages in console.

### Steps to reproduce

Just change Accent Color to red and check Console.

**Comment by pycbouh** [comment]
Accent color is used throughout the editor to modulate active icons, that's kind of the point of having it user-configurable 🙂

**Comment by seppoday** [comment]
> Accent color is used throughout the editor to modulate active icons, that's kind of the point of having it user-configurable 🙂

Totally agree and 100% understand, but in this situation (those 4 icons) exception would be nice and it should provide more readability and less confusion.

**Comment by pycbouh** [comment]
Well, I don't think we need an exception, I think we just need a better solution. We can't really use the default accent color here, as it would make theming unpredictable. And also because it doesn't really work well in the light theme and with yellow icons. So we need to find another way to indicate that the buttons are pressed, that would work in every case.

**Comment by dalexeev** [comment]
![](https://user-images.githubusercontent.com/47700418/148433905-a9be529f-ad75-4e6d-94c7-456561861cf2.png)

**Comment by Calinou** [comment]
I'm not sure about removing the icon modulation entirely. While it makes sense for colored icons, the modulation should be kept for grayscale icons.

**Comment by seppoday** [comment]
Maybe we could change those 2 grayscale icons (pencil and warning icon with "!" sign). That way every icon will be colored by default and not changed with modulation:

![image](https://user-images.githubusercontent.com/62170071/148516932-768e7f27-4fe3-4e4f-9b19-85a245632982.png)

**Comment by dalexeev** [comment]
I think the icon colors match the message colors. The only thing is that the pencil icon should be gray.

![](https://user-images.githubusercontent.com/47700418/148523372-6cd60a7b-83ce-41af-87cf-b644b6fa57f2.png)

**Comment by Calinou** [comment]
> I think that editor messages icons in software should not be affected by modulation and have static/default color. For example:

The icon modulation is a helpful feature for people with low vision, so that they can see whether a button is enabled or not. If we remove it, it won't be easy to see at a glance whether a button is active due to the relatively thin text being colored (and a small border).

**Comment by dalexeev** [comment]
> Disabled and inactive are different states. Buttons there are not disabled, they are inactive. In your proposal they do look disabled, but they shouldn't. They should look like something that can be activated.

> I think the icon colors match the message colors. The only thing is that the pencil icon should be gray.

![](https://user-images.githubusercontent.com/47700418/149770061-43b7ad37-4eda-4fa9-b03f-a5312fc84e00.png)

**Comment by dalexeev** [comment]
I think this issue can be considered fixed? (Although there is still room for improvement in these buttons IMO.)

![](https://user-images.githubusercontent.com/47700418/217322548-682d5105-e25b-4d2e-b83f-201a6bddfbb3.png)
