### ISSUE TITLE
Physical Skeleton 6 DOF Joint causes a flood of errors and crashes the editor

### ISSUE THREAD

**Issue by macryc** [godotengine/godot#56166]
### Godot version

4.0 dev 489f11ee0

### System information

Win10, GLES3, RTX 2070 mobile

### Issue description

In Godot 4, I am able to open a physical skeleton resource saved in 3.4 stable - a set of physical bones with collision shapes. All physical bone nodes have 6 DOF Joint set as their Joint angular limitations carefully set for each axis. I am using this for ragdoll. It works OK for the most part, except I get the hundreds (maybe thousands) lines of this error in the Debugger:

servers\physics_3d\godot_physics_server_3d.cpp:1498 - Condition "joint->get_type() != JOINT_TYPE_6DOF" is true

After about 500 lines of this error, the debugger just says it will now stop reporting this as there are too many.

After saving the project, it would not open again. Godot just crashes while opening, presumably due to the excess of this error.

### Steps to reproduce

1. In Godot 3.4 import a skeleton and create a physical skeleton.
2. For each physical bone 3d set the joint type to 6 DOF Joint. Fiddle with parameters and save the tscn
3. Open Godot 4, create a 3d scene
4. With Godot 4 running, paste the previously saved physical skeleton tscn into your Godot 4 folder
5. Find the tscn in file viewer inside the editor and open it. It would open without issues (although expect to have to wait for a few seconds) 
6. In the debugger screen you will see a wall of the following error: 
servers\physics_3d\godot_physics_server_3d.cpp:1498 - Condition "joint->get_type() != JOINT_TYPE_6DOF" is true
6. Save the Godot 4 project and close Godot
7. Open Godot 4 again and select the project - the fans will go to the max and Godot will crash without opening the project

**Comment by macryc** [comment]
Just checked and the error spam happens for all other physical bone 3d joint types in Godot 4, regardless of whether the joint was created in Godot 4 or migrated from 3.4.

**Comment by alex-karev** [comment]
`JOINT_TYPE_6DOF` is defined in `scene/3d/physics_body_3d.h:536`

Also defined in `servers/physics_server_3d.h:626`

They have different values

`void GodotPhysicsServer3D::generic_6dof_joint_set_param(RID p_joint, Vector3::Axis p_axis, G6DOFJointAxisParam p_param, real_t p_value)` function (as well as other similar functions in `/server/physics_3d/godot_physics_server_3d.cpp`) are using the values from `servers/physics_server_3d.h:626`, while` joint->get_type()` returns values defined in `scene/3d/physics_body_3d.h`

The error is produced when these values are compared

**Comment by alex-karev** [comment]
This pull request fixes `servers/physics_3d/godot_physics_server_3d.cpp:1498 - Condition "joint->get_type() != JOINT_TYPE_6DOF" is true` error

[#67749 (pull request)](https://github.com/godotengine/godot/pull/67749/commits)

However, `servers/physics_3d/godot_physics_server_3d.cpp:1543 - Condition "joint->get_type() != JOINT_TYPE_6DOF" is true` error is still there

**Comment by alex-karev** [comment]
#67749 
This PR was merged into the master branch and fixed the issue. In my opinion, this issue can be closed

**Comment by akien-mga** [comment]
Fixed by #67749.
