### ISSUE TITLE
2D Sprite wrong bound

### ISSUE THREAD

**Issue by radubolovan** [godotengine/godot#5617]
**Operating system or device - Godot version:** Windows 10 - Godot 2.0 stable

**Issue description** (what happened, and what was expected):
I have a sprite in a 2D scene. The sprite has an atlas image attached, but the borders are wrong.
Here is a screenshot: https://s32.postimg.org/ocx2t331x/godot_sprite.png

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by radubolovan** [comment]
More info, hopefully will help:
My image has a 32x32 size and 32 bytes per pixel. It is a png, but imported and used as "tex".
Also the bug occurs only when I set the region with odd numbers (e.g. 15x15, 17x17, etc). If I use even numbers (e.g. 14x14, 16x16, etc) the bug is no longer present.

**Comment by bojidar-bg** [comment]
This sounds like a driver bug, but I can't be sure for now.

**Comment by bojidar-bg** [comment]
Can we get someone else to confirm this as well?
@radubolovan Sorry to bother you, but can you share some hardware details with us (or confirm it was fixed in 2.1.x)

**Comment by Calinou** [comment]
I'm closing this issue since it's old and lacks information (also, the link to the screenshot is no longer working).
