### ISSUE TITLE
Vulkan: FSR Sharpness appears to have no effect

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#56173]
### Godot version

4.0.dev (489f11ee0)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 470.74)

### Issue description

The FSR Sharpness project setting appears to have no effect. I get the exact same visual output regardless if it's set to `0.2` (the default) or `1.0`.

The antialiasing used in this project is FXAA. FSR itself *does* work (it has different output than bilinear scaling):

### Native resolution

![2021-12-22_20 39 01_fxaa_10native](https://user-images.githubusercontent.com/180032/147146745-4edbc1a2-9c36-4370-b9ca-5169ea17cc04.png)

### Bilinear 0.5

![2021-12-22_20 38 34_fxaa_05bilinear](https://user-images.githubusercontent.com/180032/147146742-b6201f97-8a5a-4e4f-88ff-271a8d6f2555.png)

### FSR 0.5

![2021-12-22_20 40 04_fxaa_05fsr](https://user-images.githubusercontent.com/180032/147146747-089b3b48-c03a-49d5-831c-8cf826b39d10.png)

cc @Je06jm 

### Steps to reproduce

- Set the scaling mode to FSR in the Project Settings.
- Set the 3D scale factor to 0.5 in the Project Settings.
- Run the project and take a screenshot.
- Increase FSR Sharpness to 1.0 (or even more) in the Project Settings.
- Run the project and take a screenshot again. (Note that you may have to do this twice to ensure the setting is properly saved to `project.godot`.)

### Minimal reproduction project

[test_fsr_sharpness.zip](https://github.com/godotengine/godot/files/7764859/test_fsr_sharpness.zip)

**Comment by Calinou** [comment]
I can still reproduce this as of 4366f8bcd455714a5cd29374726d83b674ff0430.

See https://github.com/godotengine/godot/issues/56174#issuecomment-1159577065 for details.

**Comment by akien-mga** [comment]
Fixed by #62475.
