### ISSUE TITLE
Vulkan: FSR only has an effect if FXAA is enabled and MSAA is disabled

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#56174]
### Godot version

4.0.dev (489f11ee0)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 470.74)

### Issue description

FSR only seems to have an effect if FXAA is enabled *and* MSAA is disabled. If only MSAA is enabled or if neither MSAA nor FXAA is enabled, FSR will not appear to have any effect even at a low resolution scale (0.5).

cc @Je06jm 

#### 0.5× scaling with FSR

![2021-12-22_20 44 51](https://user-images.githubusercontent.com/180032/147147458-9f09f80a-5a2e-4383-9e97-72d02fd6f0be.png)

#### 0.5× scaling with bilinear

![2021-12-22_20 45 06](https://user-images.githubusercontent.com/180032/147147463-30794002-21d9-4c36-a6cb-d20c6d3fcc0d.png)

#### Native resolution

![2021-12-22_20 45 39](https://user-images.githubusercontent.com/180032/147147466-44b1e74f-af9d-4651-b9b3-62f28a0b6061.png)

#### 0.5× scaling with FSR

![2021-12-22_20 46 02](https://user-images.githubusercontent.com/180032/147147467-2c5be431-8f5a-4eb8-bf6d-98c98d156fa4.png)

#### 0.5× scaling with bilinear

![2021-12-22_20 46 16](https://user-images.githubusercontent.com/180032/147147468-a36209fa-1d2e-4e90-aa10-fa2f2f722ff7.png)

#### Native resolution

![2021-12-22_20 46 25](https://user-images.githubusercontent.com/180032/147147472-10bc419f-c6c6-4b82-9359-35f507992b8b.png)

#### 0.5× scaling with FSR

![2021-12-22_20 47 04](https://user-images.githubusercontent.com/180032/147147473-305e08b2-a226-444c-bad2-4188cadfe6ad.png)

#### 0.5× scaling with bilinear

![2021-12-22_20 47 15](https://user-images.githubusercontent.com/180032/147147476-d7a5036b-3d86-47f4-ac0b-2a8829dfe19b.png)

#### Native resolution

![2021-12-22_20 47 25](https://user-images.githubusercontent.com/180032/147147477-1f93d045-4db6-4674-ade8-9c362596a9b0.png)

### Steps to reproduce

- Set the scaling mode to FSR in the Project Settings.
- Set the 3D scale factor to 0.5 in the Project Settings.
- Set **Screen Space Aa** to FXAA in the Project Settings.
- Run the project and take a screenshot.
- Set the scaling mode to Bilinear in the Project Settings.
- Run the project and take a screenshot again. (Note that you may have to do this twice to ensure the setting is properly saved to `project.godot`.)
- Repeat the above operation, but also enable MSAA at the same time (2× or higher).

### Minimal reproduction project

[test_fsr_sharpness.zip](https://github.com/godotengine/godot/files/7764859/test_fsr_sharpness.zip)

**Comment by Je06jm** [comment]
What I've found while investigating is that the FSR passes are still happening, but somewhere FSR's source images are used instead of the processed images. I believe that #56173 is yet another symptom of this problem

**Comment by MarvinFF** [comment]
[				texture = rb->texture;](https://github.com/godotengine/godot/blob/7cd6ff322042118badbaa0bdb4ca041b4ff87801/servers/rendering/renderer_rd/renderer_scene_render_rd.cpp#L1649)
https://github.com/godotengine/godot/blob/7cd6ff322042118badbaa0bdb4ca041b4ff87801/servers/rendering/renderer_rd/renderer_scene_render_rd.cpp#L2288
https://github.com/godotengine/godot/blob/7cd6ff322042118badbaa0bdb4ca041b4ff87801/servers/rendering/renderer_rd/renderer_scene_render_rd.cpp#L2315
https://github.com/godotengine/godot/blob/7cd6ff322042118badbaa0bdb4ca041b4ff87801/servers/rendering/renderer_rd/renderer_scene_render_rd.cpp#L2320
https://github.com/godotengine/godot/blob/7cd6ff322042118badbaa0bdb4ca041b4ff87801/servers/rendering/renderer_rd/renderer_scene_render_rd.cpp#L5091
a little confise about RenderBuffers.texuture, this places should use rd->internal_textrue?
And if "storage->get_effects()->tonemapper" use rb->texture ,seems it will work.
![image](https://user-images.githubusercontent.com/10183220/149646253-a800bccb-a0c8-4d01-a54a-a5329f1d5feb.png)

@Je06jm

**Comment by npetrangelo** [comment]
I'm here from this [alpha snapshot](https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-2) and the bullet point says "AMD FSR implementation may not be working as expected", but this appears to be from Nvidia. Is the bullet point mistaken?

**Comment by Calinou** [comment]
@MarvinFF I've looked at the latest `master` codebase and noticed two things:

- There is no `can_use_upscale` variable anywhere in Godot's codebase.
- To improve performance, tonemapping should happen at internal resolution, not the output resolution.

**Comment by akien-mga** [comment]
Fixed by #62475.
