### ISSUE TITLE
Panorama sky with image texture shows black sky in editor and produces endless draw errors in debugger

### ISSUE THREAD

**Issue by macryc** [godotengine/godot#56179]
### Godot version

4.0 dev 489f11ee0

### System information

Win10, GLES3, RTX 2070 mobile

### Issue description

When loading an image into the image slot on panorama sky material, the image does not show in the editor - the background just turns completely black instead although the texture does seem to be affecting the materials in the scene.
This Degubber shows thousands of this error:

ERROR: Uniforms were never supplied for set (1) at the time of drawing, which are required by the pipeline

### Steps to reproduce

1. start a 3d scene
2. add a world environment node
3. select Sky - New Sky
4. Set sky Material to new panorama sky material
5. Set Panorama to new image texture
6. load an image into the Image slot on the image texture
7. watch this error deluge the debugger: ERROR: Uniforms were never supplied for set (1) at the time of drawing, which are required by the pipeline
8. sky turns completely black

**Comment by Calinou** [comment]
Does the problem go away if you save the scene then use **Scene > Reload Saved Scene**?

**Comment by macryc** [comment]
> Does the problem go away if you save the scene then use **Scene > Reload Saved Scene**?

it would appear so, yes.

**Comment by Calinou** [comment]
I can confirm this on `master` 489f11ee0.

**Comment by clayjohn** [comment]
Closed by: https://github.com/godotengine/godot/pull/54489
