### ISSUE TITLE
[C#] Godot leaks memory when you use foreach with a Godot.Collections.Dictionary

### ISSUE THREAD

**Issue by Guimica-gml** [godotengine/godot#56180]
### Godot version

3.4.2.stable.mono (45eaa2daf)

### System information

Windows 10

### Issue description

If you have a Godot.Collections.Dictionary in your code and try to loop trough it with a foreach godot will leak memory, the code can be as simple as:
```
private Dictionary<string, int> _dict = new Dictionary<string, int>()
{
    { "0", 0 },
    { "1", 1 },
    { "2", 2 },
    { "3", 3 },
};

public override void _Process(float delta)
{
    foreach (var item in _dict)
    {
    }
}
```
It will leak memory,
it stops leaking memory if you use System.Collections.Generic.Dictionary, so it's definitelly a problem with Godot.
You can check it by going to the monitors tab on the debugger, static memory won't stop increasing

### Steps to reproduce

Create a new project and add a C# script to a node,
inside of the script create a Godot.Collections.Dictionary with any types for key and value
then try to loop though its entries with a foreach in the _Process function
You can see the memory leak by going to the monitors tab on the debugger, static memory won't stop increasing

### Minimal reproduction project

[Memory Leak.zip](https://github.com/godotengine/godot/files/7765442/Memory.Leak.zip)

**Comment by kleonc** [comment]
Happens since `3.4.beta3.mono` (no issue in `3.4.beta2.mono`).

@raulsntos Seems like a regression caused by #51044 as [`DictionaryEnumerator.UpdateEntry`](https://github.com/godotengine/godot/blob/a75afd61a77c58fc7daaa525e485398795221f6f/modules/mono/glue/GodotSharp/GodotSharp/Core/Dictionary.cs#L257-L262) seems to be the villain.

**Comment by raulsntos** [comment]
You are right, I missed this when I made that PR. I've opened #56183 to fix it.
