### ISSUE TITLE
Varyings cannot be passed for "inout" parameter

### ISSUE THREAD

**Issue by KC098** [godotengine/godot#56189]
### Godot version

3.4.2

### System information

Windows 10, AMD Radeon HD 8700, GLES3

### Issue description

In shaders, when reference the vertex variable, the error "Vartings cannot be passed for 'inout' parameter"
When using the same exact code in Godot 3,3, that error doesn't show.

### Steps to reproduce

1. Make a function that uses an inout method. 
2. Call that method using a varying. 
3. Voila

![image](https://user-images.githubusercontent.com/73260374/147220958-1598f678-dfaa-428e-bc17-0fa5485a8b85.png)

**Comment by Chaosus** [comment]
This is intended - the function can be called in the context where that varying cannot be changed (in the fragment function for example), which leads to the shader crash.

**Comment by Chaosus** [comment]
However, I think it's possible to allow passing varying to the function when it's allowed (for VERTEX_TO_FRAG varyings only when the call happened in vertex function).

**Comment by RonanZe** [comment]
Is it also planned to merged it with the 3.x branch? This shader do not work for me either since 3.4

**Comment by Chaosus** [comment]
@RonanZe Yeah - I've backported it in #56478

**Comment by gnils** [comment]
Hi, you can workaround your water by splitting up to 3 functions:

`// Wave function:
vec4 wave(vec4 parameter, vec2 position, float time, vec3 tangent, vec3 binormal)
{
	float	wave_steepness	 = parameter.z;
	float	wave_length		 = parameter.w;

	float	k				 = 2.0 * 3.14159265359 / wave_length;
	float 	c 				 = sqrt(9.8 / k);
	vec2	d				 = normalize(parameter.xy);
	float 	f 				 = k * (dot(d, position) - c * time);
	float 	a				 = wave_steepness / k;
	
			
	return vec4(d.x * (a * cos(f)), a * sin(f) * 0.25, d.y * (a * cos(f)), 0.0);
}
vec3 wave_tangent(vec4 parameter, vec2 position, float time, vec3 tangent, vec3 binormal)
{
	float	wave_steepness	 = parameter.z;
	float	wave_length		 = parameter.w;

	float	k				 = 2.0 * 3.14159265359 / wave_length;
	float 	c 				 = sqrt(9.8 / k);
	vec2	d				 = normalize(parameter.xy);
	float 	f 				 = k * (dot(d, position) - c * time);
	float 	a				 = wave_steepness / k;
	
	return tangent + normalize(vec3(1.0-d.x * d.x * (wave_steepness * sin(f)), d.x * (wave_steepness * cos(f)), -d.x * d.y * (wave_steepness * sin(f))));
}
vec3 wave_binormal(vec4 parameter, vec2 position, float time, vec3 tangent, vec3 binormal)
{
	float	wave_steepness	 = parameter.z;
	float	wave_length		 = parameter.w;

	float	k				 = 2.0 * 3.14159265359 / wave_length;
	float 	c 				 = sqrt(9.8 / k);
	vec2	d				 = normalize(parameter.xy);
	float 	f 				 = k * (dot(d, position) - c * time);
	float 	a				 = wave_steepness / k;
	
	return binormal + normalize(vec3(-d.x * d.y * (wave_steepness * sin(f)), d.y * (wave_steepness * cos(f)), 1.0-d.y * d.y * (wave_steepness * sin(f))));
}`

and then just call

`			vertex 			+= wave(wave_a, vertex_position.xz, time, vertex_tangent, vertex_binormal);
			vertex_tangent	+= wave_tangent(wave_a, vertex_position.xz, time, vertex_tangent, vertex_binormal);
			vertex_binormal	+= wave_binormal(wave_a, vertex_position.xz, time, vertex_tangent, vertex_binormal);
			vertex 			+= wave(wave_b, vertex_position.xz, time, vertex_tangent, vertex_binormal);
			vertex_tangent	+= wave_tangent(wave_b, vertex_position.xz, time, vertex_tangent, vertex_binormal);
			vertex_binormal	+= wave_binormal(wave_b, vertex_position.xz, time, vertex_tangent, vertex_binormal);
			vertex 			+= wave(wave_c, vertex_position.xz, time, vertex_tangent, vertex_binormal);
			vertex_tangent	+= wave_tangent(wave_c, vertex_position.xz, time, vertex_tangent, vertex_binormal);
			vertex_binormal	+= wave_binormal(wave_c, vertex_position.xz, time, vertex_tangent, vertex_binormal);
	`
