### ISSUE TITLE
Vulkan fails to open obs-studio-hook DLL

### ISSUE THREAD

**Issue by Vikfr0** [godotengine/godot#56198]
### Godot version

 v4.0.dev.custom_build.012b2b538

### System information

Windows 10, AMD Ryzen 3700X, AMD RX 5700 XT, Vulkan

### Issue description

On launch, without opening a project, Godot (built from master branch) prints a warning and an error. 

```
WARNING: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        ReadDataFilesInRegistry: Registry lookup failed to get layer manifest files.
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 2218030034304
     at: VulkanContext::_debug_messenger_callback (drivers\vulkan\vulkan_context.cpp:154)
ERROR: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        Failed to open dynamic library "C:\ProgramData\obs-studio-hook\.\graphics-hook32.dll" with error 193
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 2218030034304
   at: VulkanContext::_debug_messenger_callback (drivers\vulkan\vulkan_context.cpp:157)
Vulkan API 1.2.176 - Using Vulkan Device #0: AMD - AMD Radeon RX 5700 XT
ERROR: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        Failed to open dynamic library "C:\ProgramData\obs-studio-hook\.\graphics-hook32.dll" with error 193
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 2218030034304
   at: VulkanContext::_debug_messenger_callback (drivers\vulkan\vulkan_context.cpp:157)
```

I suppose it happens for people who have OBS Studio installed (or in my case Streamlabs OBS it's a fork). I believe this is tied to: https://github.com/obsproject/obs-studio/blob/master/plugins/win-capture/graphics-hook/graphics-hook.c

I do not think I have noticed misbehavior in the engine or in OBS due to that. 

### Steps to reproduce

- have OBS Studio or Streamlabs OBS installed
- launch Godot built from master branch

**Comment by Calinou** [comment]
I'm not sure if anything can be done about it, so we may just have to turn the print into a verbose print (so it only displays when `--verbose` is passed).

**Comment by akien-mga** [comment]
See https://stackoverflow.com/a/63761663, that's a bug with Streamlabs OBS which installs implicit layers for Vulkan and doesn't clean them up properly (or they're broken, if you haven't uninstalled it).
