### ISSUE TITLE
Zip exporting isn't working for reimport the project

### ISSUE THREAD

**Issue by hani09876** [godotengine/godot#56196]
### Godot version

3.4.1

### System information

Window 10, GlES3

### Issue description

I was trying to export my project as a zip and reimport in godot to make some changes. But when ever i tried to import the zip godot don't allow me to import the zip and says no project.godot file is found.

 Fix this problem. This problem is very much irritating. I  spent 2 days by trying various way but i failed.

### Steps to reproduce

Include the project.godot file while making the zip

**Comment by akien-mga** [comment]
Exporting the project is for distribution in a form which is optimized for playing, not for editing. The vast majority of users don't want players to have full access to their source code. If you want to copy your project source, you can simply zip the project folder.
