### ISSUE TITLE
Inconsistent behavior in 2d 4-directional movement

### ISSUE THREAD

**Issue by cyberrumor** [godotengine/godot#56207]
### Godot version

3.4.1 stable

### System information

Arch Linux 5.15.10, ryzen 5 5600g, mesa 21.3.2

### Issue description

When manually setting velocity of KinematicBody2d, in-game actual behavior is not consistent with expected behavior. 

Expected behavior:

While holding "move_right" bind, and with player running right, pressing "move_down" should move player down. 
While holding "move_down" bind, and with player running down, pressing "move_right" should move player right.

Actual behavior:

While holding "move_right" bind, and with player running right, pressing "move_down" moves player down.
While holding "move_down" bind, and with player running down, pressing "move_right" moves player down.

### Steps to reproduce

Player movement script is slightly modified version of what is found on the website. This is player.gd, attached to a kinematicbody2d that is the player character.

```

extends KinematicBody2D

export (int) var speed = 200

var velocity = Vector2()

func get_input():
	velocity = Vector2()
	if Input.is_action_pressed("right"):
		velocity.x += 1
		velocity.y = 0
	if Input.is_action_pressed("left"):
		velocity.x -= 1
		velocity.y = 0
	if Input.is_action_pressed("down"):
		velocity.y += 1
		velocity.x = 0
	if Input.is_action_pressed("up"):
		velocity.y -= 1
		velocity.x = 0
	velocity = velocity.normalized() * speed

func _physics_process(delta):
	get_input()
	velocity = move_and_slide(velocity)
```

### Minimal reproduction project

[minimal_project.zip](https://github.com/godotengine/godot/files/7771699/minimal_project.zip)

**Comment by KoBeWi** [comment]
```GDScript
if Input.is_action_pressed("down"):
		velocity.y += 1
		velocity.x = 0
```
^ This gets executed after moving right and resets horizontal position.

Closing, as it's not engine bug. Next time try [other community platforms](https://godotengine.org/community) first to make sure this is Godot issue.

**Comment by cyberrumor** [comment]
```
if Input.is_action_pressed("right"):
    velocity.x -= 1
    velocity.y = 0
```
should also reset vertical velocity, but it does not.

**Comment by cyberrumor** [comment]
Oh, I see what you're saying now. Order of operations here will basically move my so called bug to other directions. Thanks, sorry to bother you!
