### ISSUE TITLE
Using `null` as default parameter causes parse error when trying to access members of that parameter

### ISSUE THREAD

**Issue by BeayemX** [godotengine/godot#56217]
### Godot version

v4.0.dev.custom_build [9d02cfa6b]

### System information

Linux Mint - Vulkan API 1.2.131 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1080

### Issue description

When having a function that is using a default parameter which is `null` the parser seemingly always asumes that this variable is `null` if no further assignment in the function itself happens.
This leads to problems if this variable is a dictionary because members can't be accessed.

The provided code snippets should make it clearer.

Maybe this issue is related? #54643

#### Not working
```gdscript
func test(data=null):
	if data:
		print(data['test'])  # Accessing this member will cause the ParseError
	else:
		print("no data")
```

#### Working
```gdscript
func test(data=null):
	data = data  # This unnecessary line can be used to prevent the ParseError
	if data:
		print(data['test'])  # Now this line is working
	else:
		print("no data")
```

**Comment by KoBeWi** [comment]
Looks similar to #49183

**Comment by akien-mga** [comment]
Confirmed reproducible in 35fff9a55e61934c84bc402a5a94073496d60709.

The error is:
```
Cannot use subscript operator on a base of type "null".
```
