### ISSUE TITLE
Can not use "_get_property_list" in GDExtension 

### ISSUE THREAD

**Issue by xfxdev** [godotengine/godot#56218]
### Godot version

4.0.dev

### System information

win10

### Issue description

Hi there, I want to try the new GdExtension. But I found that I can not use ```void _get_property_list(List<PropertyInfo>* r_props) const ``` method.

when compile, I got those errors:
```
error C2061: syntax error: identifier 'List'
error C2065: 'List': undeclared identifier
...
```

Does it still not implement in [godot_cpp](https://github.com/godotengine/godot-cpp/blob/master/include/godot_cpp/core/class_db.hpp#L153) yet?

### Steps to reproduce

none

**Comment by akien-mga** [comment]
Please provide steps to reproduce or a minimal reproduction project so that this can be tested.

**Comment by akien-mga** [comment]
Closing as there are no steps to reproduce.
