### ISSUE TITLE
Editor freeze due to a deadlock in GDScript module (itself caused by a deadlock in renderer's CommandQueueMT)

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#56219]
### Godot version

4.0 54d89f2274328cbf0fd63ad01c0a203c9b0f5c62

### System information

Windows 10 64 bits

### Issue description

While opening a project that contained errors (or not, but maybe some warnings) in some GDScript files, the editor froze while (I assume) walking files of the project. So the editor was showing up but had no files in the File Explorer dock and was blocked at this point.

I can't edit my project anymore.

As usual I had a debugger attached and it has shown the following call stack:

![image](https://user-images.githubusercontent.com/1311555/147359692-9ae04be4-0378-469d-b856-7c44c477c763.png)

This hints that the singleton lock in `GDScriptCache` is being locked twice, very likely on the code path of a parsing error.  It looks like a `GDScriptParserRef` got destroyed while the cache was already locked by some ongoing operation.
Sorry I did not capture the rest of it.
The issue went away after I change a few things in the project. It still had errors after that, but by luck it no longer deadlocked. These things are often either timing-related (when threads are involved), or layout-dependent.

Note: just had a quick look at `GDScriptCache` and I notice it contains a `HashMap<String, GDScriptParserRef*>`. `GDScriptParserRef` is RefCounted, and regularly being returned with a `Ref<T>` when the cache is queried. I find this a bit error-prone because it looks like one of these could easily get destroyed outside the cache if something goes wrong due to a refcount going to zero. Either way I dont understand the point of storing pointers there instead of a smart ref pointer (or at least use a type that makes it clear they are weak references if thats the case?).

### Steps to reproduce

Unclear. It only took a moderate size project with a bunch of scripts with errors in it (class names not found mostly). Some scripts might have been open too in the script editor because it is also not the first time I was opening this project. There is no obvious way to reproduce it yet.

**Comment by KoBeWi** [comment]
Were you able to reproduce it again?

**Comment by Zylann** [comment]
Didnt repro since, but again, this was a random find. I don't know the exact stars and planets to align in order to cause it. There is a deadlock somewhere, so either it was fixed by chance, or is still in the realm of rare subterranean bugs waiting to be discovered

**Comment by KoBeWi** [comment]
Seems like extremely rare issue without clear reproduction steps, so should be safe to close. Comment if you manage to get it again.

**Comment by Zylann** [comment]
Happened again today.
![image](https://user-images.githubusercontent.com/1311555/180062416-8b63cd07-9629-441c-877c-0a615d2a9160.png)

**Comment by Zylann** [comment]
Since the second call stack is the most frequent one on the main thread, I decided to investigate manually.
After tweaking the `MutexLock` used at the place of deadlock, I can see there are indeed multiple threads involved. There are also recursive locks from the same thread, which I guess is ok with the type of mutex, though a bit harder to debug.

However in this case the deadlock seems to be indirect.  `GDScriptCache::lock` looks fine, the problem is one of them isn't giving it back, because it got stuck on something else.

```
Locking counter: 2
Thread 9194858233057207454: 
- get_parser
Thread -5649730580712930527: 
Thread -3404174980273749301: 
- get_full_script
```

After peeking through every thread one by one, I found the other one and it blocked on this:
![image](https://user-images.githubusercontent.com/1311555/180076287-b590c50f-7c52-44cf-bc89-dc3230bdb810.png)

I'm not sure I can debug this one as easily, but CommandQueueMT seems to have issues.

**Comment by Zylann** [comment]
Still happening, project locked up again with f74491fdee9bc2d68668137fbacd8f3a7e7e8df7

**Comment by adamscott** [comment]
@Zylann Did it happen again since September?

**Comment by Zylann** [comment]
Did not happen since. Hard to say since the bug has always been quite random and while it remains present as long as I dont touch anything, it can vanish just as easily when I try to do anything.
