### ISSUE TITLE
Tabs do not retain their state when switching between editors when "separate distraction mode" is activated

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#56227]
### Godot version

3.4.2 stable oficial

### System information

w10 64

### Issue description
Active the option "separate distraction mode"
The "Nodes" tab is overridden and the "file system" tab is automatically activated when switching between the script editor and the 2D editor.

https://user-images.githubusercontent.com/19652075/147370394-86763ea1-beaa-4d06-88b4-cf0eedd9939e.mp4

### Steps to reproduce
Active the option "separate distraction mode" and watch the video

### Minimal reproduction project

...

**Comment by Torguen** [comment]
v3.5.beta1.official [b9b23d222]
In my case in this version it is still present.

https://user-images.githubusercontent.com/19652075/153747700-4cff5fad-fb11-4f06-a397-990e6d0c7c14.mp4

**Comment by Torguen** [comment]
Ok, this happens when the option "separate distraction mode" is activated

**Comment by Torguen** [comment]
This keeps happening in
v3.5.1.rc1.official [https://github.com/godotengine/godot/commit/293c3844b3424b4a64d6245f99145266101a146f]

**Comment by jmb462** [comment]
It's only fixed in master branch.
This fix hasn't been backported to 3.x branch.
I will have a look.
