### ISSUE TITLE
On import animation optimization doesn't work because of node renaming

### ISSUE THREAD

**Issue by SaracenOne** [godotengine/godot#5622]
**Operating system or device - Godot version:**
Windows 8 - Bleeding Edge (454b210242ec15a9928324757f27989216bc5a59)

**Issue description** (what happened, and what was expected):
Okay, so a recent update (0db02f26b66ba4e3ac671607ba85fc794ae698fa) introduced some changes to the scene import, but one thing it broke was the running the animation optimizer on scenes as they're imported. The reason specifically for this breaking is because the update made it so that the AnimationPlayer node which is created automatically on scene import had its named changed to 'animations', whereas the method for method for preprocessing animation optimization search for a node with the default name 'AnimationPlayer'. This is obviously incredibly trivial to fix, and I would have already fixed it myself, but I wanted to know whether there was a reason for renaming the AnimationPlayer node, and whether it should be fixed by either reverting the name or have the optimizer method simply search for the node with a new name.

**Steps to reproduce:**
Import any Collada file with animation using the optimization flag.

**Link to minimal example project** (optional but very welcome):

**Comment by bojidar-bg** [comment]
Close?

**Comment by SaracenOne** [comment]
Yeah, I'll close it now.
