### ISSUE TITLE
Unfolding inspector sections doesn't work consistently

### ISSUE THREAD

**Issue by stijn-h** [godotengine/godot#56225]
### Godot version

28174d531b7128f0281fc2b88da2f4962fd3513e

### System information

W10

### Issue description

This functionality was present in #41138 (see gif further down). Not sure what has changed since then. In the case of the video, I attempt to drop a ShaderMaterial on an unfolded Material tab. Inside is a material property that accepts this resource, but unfolding doesn't work. The problem is in editor_inspector.cpp:L1264. It checks whether any property can accept the dragged resource, but for some reason it doesn't detect it. 

https://user-images.githubusercontent.com/25907608/147367910-6bdca1f8-99f4-45e0-90e6-560d7dea5c5e.mp4

Not sure if this is something specific to ShaderMaterial, couldn't find other resources in folded sections.

### Steps to reproduce

 - Select Node2D (or any CanvasItem)
 - Create new ShaderMaterial resource.
 - Drag resource over Material tab.

**Comment by KoBeWi** [comment]
For some reason the feature doesn't work for me at all.

**Comment by fire540** [comment]
The feature doesn't work for me on 3.4 either. Maybe it was broken sometime between 3.4 and https://github.com/godotengine/godot/pull/41138 and no one noticed until now.

**Comment by zaevi** [comment]
Seems #52277 broke the feature at `EditorInspectorSection::_notification`
https://github.com/godotengine/godot/blob/28174d531b7128f0281fc2b88da2f4962fd3513e/editor/editor_inspector.cpp#L1255-L1272

This code tries to check if there is any property inside the section that can be drag-dropped. However, most kinds of `EditorProperty*` are not covered yet, and sub-property are not considered (like property in `EditorPropertyResource`).
