### ISSUE TITLE
Khmer Font Render Correctly in Godot Engine 4, But not in Godot Engine 3. How can I fix this? I'm new to Godot Engine

### ISSUE THREAD

**Issue by S-Heng** [godotengine/godot#56236]
### Godot version

3.4.2

### System information

Windows 11, Nvidia 2060, GLES3

### Issue description

![Screenshot 2021-12-24 22 39 00](https://user-images.githubusercontent.com/88778856/147376430-a888e7c4-a207-42ed-a09a-85ce92810815.png)
![Screenshot 2021-12-24 22 39 15](https://user-images.githubusercontent.com/88778856/147376431-a7320cd7-fe53-4ca3-9877-c6d4ad182e75.png)

### Steps to reproduce

![Screenshot 2021-12-25 10 00 18](https://user-images.githubusercontent.com/88778856/147376521-41516fc8-ad94-48cb-83b1-22e53a5e69b4.png)
This is the correct display

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/7775409/Test.zip)

**Comment by Calinou** [comment]
Godot 4 has support for complex scripts, but Godot 3.x does not (and will not for compatibility reasons).

To use complex scripts in Godot 3.x, you can compile the editor and export templates with the https://github.com/bruvzg/godot_tl module.
