### ISSUE TITLE
Vulkan: Selecting 8× MSAA on Apple M1 GPU crashes the editor

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#56233]
*Related to https://github.com/godotengine/godot/issues/53940.*

### Godot version

4.0.dev (489f11ee0)

### System information

Apple Mac mini 2020 (M1), macOS Monterey 12.1

### Issue description

The M1 GPU only supports 4× MSAA at most, yet Godot's Vulkan renderer allows setting it to 8× even on GPUs that don't support it. Instead, the MSAA value should be clamped to the highest value supported by the hardware.
Additionally, the MSAA property hint in the project settings could be automatically modified to denote that specific values are unsupported on the user's machine.

I haven't checked whether this occurs in `3.x`'s GLES3 and GLES2 renderers yet.
**Edit:** I've tested a few games such as [Yamagi Quake 2](https://yamagi.org/quake2/) and noticed that MSAA is clamped to 4× when trying to use 8× MSAA there.

### Steps to reproduce

- Create a new project. Add a MeshInstance3D node with a BoxMesh resource.
- Open the Project Settings and enable the **Advanced** toggle.
- Set MSAA to 8×.

### Minimal reproduction project

N/A

**Comment by Hugo4IT** [comment]
> I haven't checked whether this occurs in `3.x`'s GLES3 and GLES2 renderers yet.

My M1 does not crash using MSAA 8x/16x on either GLES2 and GLES3, so this only applies to Vulkan.

- System info: M1 MacBook Air 2020, also running MacOS Monterey 12.1
- Godot version: `v3.4.stable.official`

**Comment by Calinou** [comment]
> My M1 does not crash using MSAA 8x/16x on either GLES2 and GLES3, so this only applies to Vulkan.

Can you spot a visible difference between 4× MSAA and 8× MSAA (or 16×) in either GLES2 or GLES3? You can take screenshots with each mode and use https://github.com/kornelski/dssim to generate a visual diff of the image if you can't spot the difference with your own eyes.
