### ISSUE TITLE
Video Player Not Playing Videos Seamlessly.

### ISSUE THREAD

**Issue by ajk2196** [godotengine/godot#56235]
### Godot version

3.4.2 Stable (22 Dec Release)

### System information

Windows 10, 2 X RTX 2070 Super

### Issue description

**What I want to do is play a Video on a screen seamlessly**. I have made a seamless **video which will loop perfectly if there is no delay when playing it second time (and forth from then) using the Video Player**. I achieve this by adding the play( ) function to the _on_VideoPlayer_finished( ) function which will be seen in the screenshot that I have attached. The filename is "webm0001-0600.webm" which can be seen in the screenshot. File size is <7 Mb (Have attached the screenshot for that as well).

Now, **would there be some other way / workaround to do this seamlessly if we don't reach the solution for this?** Because reaching a solution may take time; and I need to finish my project that is small and has a deadline of 30 Dec (The client wants it on the New Year's day, 1 Jan, but wants to preview it before that so that changes can be done if any). **If there isn't a workaround, can you please fast-track my request?**

![Screenshot (125)](https://user-images.githubusercontent.com/90527174/147376382-186ac2a6-0903-4520-991b-56c7142cbebf.png)

### Steps to reproduce

Screenshot attached. Let me know if you need any more information.

**Comment by Calinou** [comment]
> Now, would there be some other way / workaround to do this seamlessly if we don't reach the solution for this? Because reaching a solution may take time; and I need to finish my project that is small and has a deadline of 30 Dec (The client wants it on the New Year's day, 1 Jan, but wants to preview it before that so that changes can be done if any). If there isn't a workaround, can you please fast-track my request?

Other than looping the video file in a video editor, I don't see any other solution that will allow for seamless looping. Video playback code in Godot doesn't have any maintainers (and [format support will be moved out of core in 4.0](https://github.com/godotengine/godot-proposals/issues/3286)).

**Comment by ajk2196** [comment]
Changing the video won't work, because it is a looping video on a main screen in a game-app which the user may spend quite some time on, from a low-to-mid end device. All the requirements of my client prevent me from using a large video file. It is very easy for me to produce my large files (have a super decent PC), but it is the client; and this just one simple issue.

@Calinou,
Can you please atleast tag a few people or draw their attention towards this post, who have given some good time to the development of Godot, maybe they would look into it.

And one more request, kindly please add some more tags, like 'important' or urgent'.

**Comment by Calinou** [comment]
> Can you please atleast tag a few people or draw their attention towards this post, who have given some good time to the development of Godot, maybe they would look into it.

I insist that there is literally nobody who has time to assist with video rendering issues. The WebM decoding code was contributed by someone who left the Godot community a long time ago, [which is why it was already removed in the `master` branch](https://github.com/godotengine/godot/pull/53833).

Theora isn't as difficult to maintain, but it's still lacking knowledgeable contributors. I have no experience working on video decoders or their integration code.

> And one more request, kindly please add some more tags, like 'important' or urgent'.

We only add the `high priority` label to issues that can cause data loss or security vulnerabilities.
