### ISSUE TITLE
Tile physics properties don't have tooltips

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#56244]
### Godot version

28174d5

### System information

W10

### Issue description

This thing
![image](https://user-images.githubusercontent.com/2223172/147392454-50b9c567-4fdf-4ba9-a0e4-099cadae6115.png)
in painting mode. You can't check their full names without resizing the dock. A tooltip with full name is missing.

### Steps to reproduce

1. Add a physics layer to tileset
2. Edit it
3. Go to painting mode
4. The property names are soooo long

**Comment by brennengreen** [comment]
Looks like this can be fixed in `tile_set.cpp` inside `Tileset::_get_property_list` Looking at the section labeled physics are the options for the physics layer. Some of these we're deliberately not given property hints which are weird. I'm unaware of the typical rules when it comes to editor properties so maybe someone else can comment on why that might be.

The change seems pretty simple as adding the property hints into this snippet of code:

```cpp
// Physics layers.
		p_list->push_back(PropertyInfo(Variant::NIL, "Physics", PROPERTY_HINT_NONE, "", PROPERTY_USAGE_GROUP));
		for (int i = 0; i < physics.size(); i++) {
			p_list->push_back(PropertyInfo(Variant::VECTOR2, vformat("physics_layer_%d/linear_velocity", i), PROPERTY_HINT_NONE));
			p_list->push_back(PropertyInfo(Variant::FLOAT, vformat("physics_layer_%d/angular_velocity", i), PROPERTY_HINT_NONE));
			p_list->push_back(PropertyInfo(Variant::INT, vformat("physics_layer_%d/polygons_count", i), PROPERTY_HINT_NONE, "", PROPERTY_USAGE_EDITOR));

			for (int j = 0; j < physics[i].polygons.size(); j++) {
				// physics_layer_%d/points
				property_info = PropertyInfo(Variant::ARRAY, vformat("physics_layer_%d/polygon_%d/points", i, j), PROPERTY_HINT_ARRAY_TYPE, "Vector2", PROPERTY_USAGE_DEFAULT);
				if (physics[i].polygons[j].polygon.is_empty()) {
					property_info.usage ^= PROPERTY_USAGE_STORAGE;
				}
				p_list->push_back(property_info);

				// physics_layer_%d/polygon_%d/one_way
				property_info = PropertyInfo(Variant::BOOL, vformat("physics_layer_%d/polygon_%d/one_way", i, j));
				if (physics[i].polygons[j].one_way == false) {
					property_info.usage ^= PROPERTY_USAGE_STORAGE;
				}
				p_list->push_back(property_info);

				// physics_layer_%d/polygon_%d/one_way_margin
				property_info = PropertyInfo(Variant::FLOAT, vformat("physics_layer_%d/polygon_%d/one_way_margin", i, j));
				if (physics[i].polygons[j].one_way_margin == 1.0) {
					property_info.usage ^= PROPERTY_USAGE_STORAGE;
				}
				p_list->push_back(property_info);
			}
		}
```

If this is still open sometime tomorrow or next I'll get a PR up for it.
