### ISSUE TITLE
Expose drag and drop from filesystem to GDScript

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#5625]
from 
https://godotengine.org/qa/5972/list-files-that-been-dragged-onto-games-window-their-directory

> I want to create a batch processing application in godot - that takes for input files that have been dragged and dropped by the user to the application window. Is that something that is possible to do in godot? I need to get that data and store it in an array

Other possible applications of this would be for plugins - being able to drag external files onto a godot plugin window.

**Comment by TheHX** [comment]
After some investigation, i found there's a API for using D&D from the OS exposed to GDScript, there's a ```MainLoop::_drop_files``` virtual function, and ```files_dropped(StringArray files, int screen)``` signal on ```SceneTree```.

I've made a simple example, where you can drag images into the application window, and it'll show all images in a ```ItemList```:

[drag_n_drop_os.zip](https://github.com/godotengine/godot/files/356112/drag_n_drop_os.zip)

**Comment by blurymind** [comment]
Thank you! I am going to try this out today

**Comment by blurymind** [comment]
files_dropped(StringArray files, int screen) is missing in the documentation! 
:o

**Comment by TheHX** [comment]
@blurymind, i think this is because this feature is not available in 2.0.x versions. Only on Github HEAD.

**Comment by blurymind** [comment]
nice! I wonder how many other hidden features there are :)

**Comment by blurymind** [comment]
Seeing as to how this feature exists already in godot head master - do you guys think I should close this? Is there anything that is missing in the current implementation?

**Comment by bojidar-bg** [comment]
Well, IMO this should be closed since we already support it in `master`. If there are bugs with the implementation itself, open a new issue, but if there are issues with the way it is exposed, you might decide it is better to comment here.

**Comment by blurymind** [comment]
I think the file @TheHX provided should be included in the demos folder. It is awesome! :)

**Comment by mefihl** [comment]
Mayby @TheHX demo put in godot-demo-projects ?

**Comment by blurymind** [comment]
@TheHX Do you know how to tell this action to trigger only when the cursor is over a specific node?
Right now the files get loaded when I drag them anywhere on the app window - but I want them to load only when dragged onto a specific node!

**Comment by TheHX** [comment]
I'm not sure if there's any way to do this, without using some crazy tricks. But this id be a nice improvement for the drag and drop, but i don't know how this should be exposed.

**Comment by blurymind** [comment]
@TheHx What does the 'screen' (string) value do? I noticed that it always returns a zero.

**Comment by TheHX** [comment]
I'm not sure, but i think the screen parameter is index of the from where the files are dragged, but as it seems the feature is not implemented:
https://github.com/godotengine/godot/blob/master/platform/windows/os_windows.cpp#L767
https://github.com/godotengine/godot/blob/master/platform/x11/os_x11.cpp#L1531
https://github.com/godotengine/godot/blob/master/platform/osx/os_osx.mm#L330

**Comment by blurymind** [comment]
@TheHX  perhaps it would be useful if all gui related nodes get a _drop_files signal

**Comment by TheHX** [comment]
I don't think so, actually the D&D system in Godot is based on virtual functions, as you can see in this [script](https://github.com/godotengine/godot-demo-projects/blob/master/gui/drag_and_drop/drag_drop_script.gd).

**Comment by blurymind** [comment]
I tried doing it with focus_enter and focus_exit signals and a variable. Didnt work. Focus enter signal requires the user to click on the node - which doesnt work with drag and drop.

Can you come up with any workarounds?

We might have to reopen this bug - because drag and drop does not seem to be properly exposed to gdscript at the moment.

**Comment by blurymind** [comment]
@vnen can you reopen the bug? I shouldnt have closed it so early. Drag and drop is missing a very key element at the moment

**Comment by vnen** [comment]
@blurymind it's better if you open a new issue with a proper request.
