### ISSUE TITLE
Incorrect REDUNDANT_AWAIT warning when signal is not recognized

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#56265]
### Godot version

28174d5

### System information

W10

### Issue description

When you await a signal that can't be resolved safely, the editor will warn that it's not needed, because it doesn't know that it's a correct signal until runtime.

E.g. when you do
```GDScript
await $Timer.timeout
```
you will get `"await" keyword not needed in this case, because the expression isn't a coroutine nor a signal.`, but it's not true. If the signal can't be resolved, parser/analyzer should just assume that it's correct (dynamic typing) and don't show the warning. Also this line is shown as safe, even though it shouldn't.

### Steps to reproduce

Just use the code above and observe the warning.

**Comment by StarryWorm** [comment]
I think this one speaks for itself, issue is back on 4.4

<img width="993" height="90" alt="Image" src="https://github.com/user-attachments/assets/39703d0e-8852-43b3-b4c2-4bdc53083b1e" />
