### ISSUE TITLE
`'` in file name gets incorrectly escaped when dragged to script editor

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#56263]
### Godot version

28174d5

### System information

W10

### Issue description

![LwTQL1vpKh](https://user-images.githubusercontent.com/2223172/147420035-e7e3aff6-927f-4196-b9ab-24a9ed3d5f5e.gif)
I think it's supposed to escape in case of single quotes, but it's invalid when using doubles.

### Steps to reproduce

0. Use double quotes as default style
1. Have a file with `'` in name
2. Drag it to script editor

**Comment by rrohak** [comment]
Hi, I would like to take this on.

I dug around a little bit in the codebase and I think it would be [this method](https://github.com/godotengine/godot/blob/49403cbfa0399bb4284ea5c36cc90216a0bda6ff/editor/plugins/script_text_editor.cpp#L1435) that I have to mess with.

I see on line 1474 though that it uses an internal library function to escape all characters. I think moving `String text_to_drop `to be a method wide variable (declared at the beginning) would be nice. As well as moving the `set_caret_line`, `set_caret_column`, `insert_text_at_caret` method calls to the end of the method `drop_data_fw` would be good to avoid duplicated code. With this move, the code then becomes

```
...

String text_to_drop;

...

if(quote_style == "\"") {
    text_to_drop = text_to_drop.replace("\\'", "\'");
}

te->set_caret_line(row);
te->set_caret_column(col);
te->insert_text_at_caret(text_to_drop);
```

Drawback is that we're escaping single quotes, then unescaping at the end but this allows for least change to escape or unescape methods in ustring. I think another possibility is to change c_escape to take a flag, something like "is_single_quote", that is by default true. Then in `drop_data_fw`, we can pass in the original boolean value of the editor setting and not convert it to a string.

Let me know what you think. Either way though, I think moving the three methods for `te->set_caret_line`, etc should be moved out of each if guard, and `String text_to_drop` so we can avoid that code duplication and make it easier to read. Also moving from individual ifs to if else might help readability too. That would convert it to 

```
if(!d.has("type")) {
    return
}
String data_type =  String(d["type"]);
if(data_type == resource) {
    ...
    text_to_drop += text_to_drop.c_escape(false);
} else if (data_type == files)
...

```

**Comment by Ayush-singla27** [comment]
Has this issue been fixed? i would like to try this issue as my first open source contribution.
