### ISSUE TITLE
Invalid set index 'value' (on base: 'Nil') with value of type 'int'.

### ISSUE THREAD

**Issue by setwind** [godotengine/godot#56269]
### Godot version

3.4.2

### System information

windows7 32bit

### Issue description

when i define a variable :

onready var hbar=$MarginContainer/HBoxContainer/TextureProgress
hbar.value=100

it shows error:

Invalid set index 'value' (on base: 'Nil') with value of type 'int'.

but when i do like this:

      $MarginContainer/HBoxContainer/TextureProgress.value=100

it has  no errors

### Steps to reproduce

1, create RootNode/MarginContainer/HBoxContainer/TextureProgress
2,use the Property of TextureProgress
3,   when i define a variable :

onready var hbar=$MarginContainer/HBoxContainer/TextureProgress
hbar.value=100

it shows error:

Invalid set index 'value' (on base: 'Nil') with value of type 'int'.

but when i do like this:

      $MarginContainer/HBoxContainer/TextureBar.value=100

it has  no errors

**Comment by KoBeWi** [comment]
`hbar` variable is onready, so it's initialized when the node is added to scene tree (`_ready()`). You are trying to access a variable before it was intialized.

Also
```GDScript
onready var hbar=$MarginContainer/HBoxContainer/TextureProgress
hbar.value=100
```
is invalid syntax, so you should get a different error. Can you give the whole script?

**Comment by setwind** [comment]
extends CanvasLayer

var barRed=preload('res://imgs/redBar.png')
var barGreen=preload('res://imgs/blueBar.png')
var barYellow=preload('res://imgs/yellowBar.png')
var bar_texture
onready var hbar= $MarginContainer/HBoxContainer/TextureProgress.value
func update_healthbar(_value): 
	
	bar_texture=barGreen
	if value<60:
		bar_texture=barYellow
		pass
	if value<25:
		bar_texture=barRed
		pass
	hbar.texture_progress=bar_texture
	hbar.value=_value
	pass

func _ready():
	pass # Replace with function body.

**Comment by setwind** [comment]
Invalid set index 'texture_progress' (on base: 'Nil') with value of type 'StreamTexture'.
Invalid set index 'value' (on base: 'Nil') with value of type 'int'.

the same error

**Comment by KoBeWi** [comment]
Sooo why are you assigning float to your node variable and then use it like a node?

onready var hbar= $MarginContainer/HBoxContainer/TextureProgress.**value** <- this

If you remove `.value` it should work. Not sure why you get `(on base 'nil')` in your error, but you still didn't post the full code. There is no call to `update_healthbar()` in your example.

Anyways, GitHub is for reporting engine bugs, but this issue doesn't look like one. There are [other community platforms](https://godotengine.org/community) if you want help with your code. Closing.
