### ISSUE TITLE
Default arguments show as <unknown> in method tooltip

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#56262]
### Godot version

28174d5

### System information

W10

### Issue description

![image](https://user-images.githubusercontent.com/2223172/147419819-c975f80c-cb35-406e-8a8f-6feb6c9155b8.png)

### Steps to reproduce

```GDScript
func test(color = Vector2(1, 0)):
	pass

func _ready() -> void:
	test(
```
------------------ ^ place caret here and press Ctrl + Space

**Comment by Calinou** [comment]
I can't reproduce this in 3.5.beta a75afd61a:

![image](https://user-images.githubusercontent.com/180032/147421003-77d85f46-c562-4c1f-a624-bd6ca2dfbfa8.png)

I can reproduce it in `master` 28174d531 though:

![image](https://user-images.githubusercontent.com/180032/147421024-55d6b1df-87a7-4227-81c9-10c6a5d650ef.png)
