### ISSUE TITLE
After opening theme editor, the editor will keep redrawing

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#56264]
### Godot version

28174d5

### System information

W10

### Issue description

This is similar to #50866
When you open Theme editor, the editor will keep constantly redrawing until restart, but at a slow pace.
![YJzU3WcJsW](https://user-images.githubusercontent.com/2223172/147420250-3fa97c82-fbcc-43a6-989e-1448dc12c8f2.gif)

### Steps to reproduce

1. Create any Control node
2. Add some Theme and open Theme editor
3. Your editor will now redraw forever for no reason

**Comment by pycbouh** [comment]
I think it's only redrawing the theme preview. It was the original design which I didn't change, but it basically is polling for theme changes in the preview, to avoid immediate updates as you change the theme. This gives smoother experience in theory, which is why I kept it as is.

**Comment by KoBeWi** [comment]
Redrawing Theme editor is fine, but it will keep doing so even after it was closed. It's probably not stopping some Timer.
