### ISSUE TITLE
TextEdit's clear() from RMB menu can't be undo

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#56274]
### Godot version

28174d5

### System information

W10

### Issue description

When you use "Clear" option from right-click menu in TextEdit node, you can't undo this operation.

### Steps to reproduce

1. Add TextEdit node
2. Run project
3. Type some text
4. Right click -> Clear
5. Try undo
6. No undo

**Comment by theoniko** [comment]
Hello @KoBeWi,
Could you please give some more hints which files are relevant? Is there a wiki page for the gui in godot project which you can share?

**Comment by KoBeWi** [comment]
@theoniko Check `text_edit.cpp`, code related to `MENU_CLEAR` constant.

Right now it will just call `clear()`, which removes undo history. It should preserve the history, but only when clearing from the context menu.

**Comment by Paulb23** [comment]
Seems like it was fixed in `2.1` with #16269, but as we hid it from the editor `3.x` via #6640 was never "fixed".

**Comment by theoniko** [comment]
@Paulb23: Would cherry-picking the commit from #16269 to the latest master enought to close this issue?

**Comment by Paulb23** [comment]
Would say not as those changes are now irrelevant / can be simplified.

**Comment by volokh0x** [comment]
I got stuck on a problem that `clear()` gets called from the class constructor as well, when a lot of data are not initialized. Would it be a better decision to separate this concern from the context menu? Otherwise, is there a good way to differentiate between these two use cases inside the body of the method?
