### ISSUE TITLE
Multiplayer ENet not connection with different internet IP

### ISSUE THREAD

**Issue by tankpillow** [godotengine/godot#56277]
### Godot version

3.4.2.stable

### System information

macOS | GLES3 | 

### Issue description

I am hosting my game in a Linux VPS from a datacenter located in Canada. When I try joining the game on my own internet, it works fine. However, if I connect to a hotspot, my friend's internet or any other kind of internet it fails to connect... sort of.

This function in the `Network.gd` script works fine:
```
func joinServer():
    client = NetworkedMultiplayerENet.new()
    client.create_client(ipAddress, serverPort)
    get_tree().network_peer = client
    print(ipAddress)
    print(str(get_tree().get_network_unique_id()))
```
*Output*
```
51.222.39.211 # <-- IP to the hosted VPS
46015878
```

The function in the `WaitingRoom.gd` for the `connected_to_server` signal does not fire when the connection has been made.

```
func _ready():
    get_tree().connect("connected_to_server", self, "connectedToServer")
    get_tree().connect("connection_failed", self, "connectionFailed")
```

```
func connectedToServer():
    print("working")
    yield(get_tree().create_timer(0.1), "timeout")
    if get_tree().get_network_unique_id() != 1:
        playerCount += 1
	instancePlayer(get_tree().get_network_unique_id())
```

### Steps to reproduce

1. Add the scripts above to their respected files.
2. Run the game and try and connect to the server.

(Feel free to ping the server to verify that it is online.

### Minimal reproduction project

[Sample.zip](https://github.com/godotengine/godot/files/7778866/Sample.zip)

**Comment by Faless** [comment]
> However, if I connect to a hotspot, my friend's internet or any other kind of internet it fails to connect... sort of.

Seems pretty weird, and a bit generic (any other kind? sort of?).
Seems more like a network problem than a Godot one, I'm not sure how I can help.

The only thing that comes to mind is that your friend's mobile provider uses an IPv6 network and connecting to the IPv4 of the server doesn't work (either because they don't support IPv4 translation, or because they use NAT64 / DNS64 which doesn't always work well with all applications).

Again, this is more like a guess, I don't really know how to help otherwise.

**Comment by tankpillow** [comment]
My bad for not being clear enough, my friend tested it using their internet that has an IPv4.

**Comment by bastianccm** [comment]
Trying this and monitoring the network via Wireshark shows no response packets from your server.
Enet uses UDP, are you sure you do not have any firewall blocking (outgoing) UDP traffic on port 7777 from your machine?

**Comment by tankpillow** [comment]
> Trying this and monitoring the network via Wireshark shows no response packets from your server. Enet uses UDP, are you sure you do not have any firewall blocking (outgoing) UDP traffic on port 7777 from your machine?

The reason why the server is currently not working is because I shut down the server temporarily.
