### ISSUE TITLE
you are not Engineers

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#56272]
### Godot version

not relevant

### System information

not relevant (but they are all trash (linux/mac/windows etc))

### Issue description

@akien-mga  and godot devs : Stop calling yourselves Engineers. You are not engineers, not event close, and never will be. You all don't have a clue as to what engineering means or entails. Sitting behind a keyboard and writing code has absolutely NOTHING to do with engineering. Software developers are not engineers, they are big liars when they make such stupid claims. Engineering is about designing and building physical entities, like buildings, turbines and machinery. So stop the false lies and offensive accusations. 

@reduz you should read this as well Juan.

### Steps to reproduce

Stop lying

**Comment by mrjustaguy** [comment]
Please Google "Engineer Definition"
Here are the results

### The Noun Engineer Meaning
1) a person who designs, builds, or maintains engines, machines, or structures. - Code is very much a Structure and tells a Machine how to operate
2) a person who controls an engine, especially on an aircraft or ship. - A Programmer is a person who Controls a Computer, similar to an engine on an aircraft or a ship.

### The Verb to Engineer Meaning
1) design and build (a machine or structure). - Code is all about Structure, you're essentially building a path for electrons to flow and walls where they don't, that are ever changing based on all the conditions you've built into the Structure.
2) skillfully arrange for (something) to occur. - With Code you arrange for transistors to go on and off many billions of times per second, to get all the millions of pixels on your screen to give exactly the color you want them to many times a second (usually 60hz, however these days 144hz and above are starting to get common) If that ain't engineering, I don't know what is...

### Conclusions
1) Do your research on the definition of a category you think someone doesn't belong in before making a post about how they don't belong in the category, to avoid making such blatantly false claims and pissing off half the internet.
2) Do your research on where the appropriate place to make such a post is, this place is for communicating found issues with the software, to give feedback to the Software Engineers working on the project to improve it for all it's users. The type of complaint you have would be much better suited for places like reddit, or other Social Media that aren't made for work.
3) Read the Codes of Conduct of any community you seek to share your opinions in, they're usually very good guidelines for determining the best way to communicate with the community. For Godot's community, Please read https://godotengine.org/code-of-conduct

**Comment by Zireael07** [comment]
@mrjustaguy: This is a troll - no amount of reasoning will make him learn (and he's already banned so he won't see it either way)
