### ISSUE TITLE
"Too few vertices per face" error when running project in headless mode

### ISSUE THREAD

**Issue by Noiros** [godotengine/godot#56281]
### Godot version

v4.0.dev.20211210.official [21b81998b]

### System information

Windows 11, Vulkan, Rx 5700 XT, Ryzen 7 3600x

### Issue description

hey, I have this error that appears with each frames, I simply generated a trimesh collision and then run the game on linux server (ubuntu 20.04 in headless), the problem only appears on linux server, in the game engine on windows everything works without problem and in export windows too

### Steps to reproduce

simply add this collision in static body and execute the export project on linux 

[house_coll.zip](https://github.com/godotengine/godot/files/7780897/house_coll.zip)

**Comment by Calinou** [comment]
Can you reproduce this in `3.x`?

**Comment by Noiros** [comment]
> @Noiros Can you reproduce this in `3.x` with both Bullet and GodotPhysics? (The `master` branch only provides GodotPhysics.)

No problem with the both ...

**Comment by akien-mga** [comment]
Seems fixed as of 4.0 RC 3.
