### ISSUE TITLE
`xml_unescape()` decodes hexadecimal codes as decimal codes since Godot 3.4

### ISSUE THREAD

**Issue by goatchurchprime** [godotengine/godot#56298]
### Godot version

3.4-stable and 3.4.1.rc3

### System information

Windows 10

### Issue description

In Godot 3.3 the following:

```GDScript
	print("&lt;".xml_unescape())
	print("should be up-arrow: ", "&#21E7;".xml_unescape())
	print("should be letter A: ", "&#0041;".xml_unescape())
```

prints:
* <
* should be up-arrow: ⇧
* should be letter A: A

But since V3.4 it prints:
* <
* should be up-arrow: &#21E7;
* should be letter A: )

Interestingly, the Unicode code for ')' is U+0029, which is 41 in decimal.  This is probably not a co-incidence!

### Steps to reproduce

as above

### Minimal reproduction project

as above

**Comment by kleonc** [comment]
Probably caused by #45914/#47978.

**Comment by goatchurchprime** [comment]
It can't be used very much or someone else would have noticed.  

Luckily I've got this desperate work-around which allows me to make a release where I've got those arrow keys on my VR keyboard coming up again (note the assert to make sure that the bug is still there):
 
```GDScript
	if text[0] == "&" and text[-1] == ";":
		assert ("&#0041;".xml_unescape() == ")")  # https://github.com/godotengine/godot/issues/56298
		text = ("&#%d;" % ("0x"+text.substr(2, 4)).hex_to_int())
		text = text.xml_unescape()	
```
![image](https://user-images.githubusercontent.com/677254/147587545-bfc0db02-7acc-4b61-ae16-47fc0eaae202.png)

**Comment by bruvzg** [comment]
> If the character reference begins with "&#x", the digits and letters up to the terminating ; provide a hexadecimal representation of the character's code point in ISO/IEC 10646.
>
> If it begins just with "&#", the digits up to the terminating ; provide a decimal representation of the character's code point.
>
> see https://www.w3.org/TR/2006/REC-xml11-20060816/#sec-references

That's actually a correct behavior, `&#` should be decimal and `&#x` hexadecimal.

**Comment by goatchurchprime** [comment]
Well blow me down.  You've beaten me again.  My knowledge was corrupted by a bug.

Tested in Chrome:

```html
<html>
<body>
<h1>&lt;  &#0041;  &#x0041;</h1>
</body>
</html>
```

![image](https://user-images.githubusercontent.com/677254/147650724-3e2f028a-e528-44d8-ab6d-4d8557aebdf2.png)
