### ISSUE TITLE
VisibilityEnabler2D still toggles particles after being disabled by code

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#5630]
**Tested on Godot 2.0.3 and 2.0.4, Windows 10 64 bits**

**How it happened:**
In my game, pickups have particles on them. When the player picks them, I hide them and disable particle emission, because that way it won't "pop out" and I can make them respawn easily when the level restarts (which happens a lot).

To reduce CPU usage, I added VisibilityEnabler2D on pickups so their particles aren't simulated when out of view.
Problem: disabled pickup started to emit particles again when the player goes back the place where it was, because VisibilityEnabler2D activates them again.

Then, in addition to disable emission, I also turn off VisibilityEnabler2D with this code:

``` gdscript
get_node("VisibilityEnabler2D").set_enabler(VisibilityEnabler2D.ENABLER_PAUSE_PARTICLES, false)
```

However it doesn't works at all, the enabler continues to enable or disable particles.
It works if I disable the enabler from the inspector, but in code I see no change.

**Example project:**
Here is a test project in which  I disable the enabler from code:
[ParticlesEnabler.zip](https://github.com/godotengine/godot/files/356128/ParticlesEnabler.zip)

Press right arrow to move the camera away from the particles. Notice it stops emitting, ignoring the `ENABLER_PAUSE_PARTICLES` setting.
(I also noticed a kind of margin, the camera has to be further away from the area)
You can also notice this when intentionally disabling particles: they will start to emit once in view.

**What was expected:**
1) VisibilityEnabler2D should work the same in code and inspector
2) Should pause particle simulation instead of changing emission

**Comment by RandomShaper** [comment]
By looking at the code I can confirm that the collection of affected nodes is done when the `VisibilityEnabler2D` enters the tree, so no flags cannot be changed at runtime.

For the 2.1 branch, a new method called something like `update_affected_nodes` could be added.

For the 3.0 branch maybe the behavior of this node should be re-thought so it collects always every potentially affected node regardless which flags are set and then checks them on enter/exit to enable/disable what's relevant.

**Comment by RandomShaper** [comment]
Regarding the detection margin, it's explained at https://github.com/godotengine/godot/issues/4803#issuecomment-225460236.

**Comment by kubecz3k** [comment]
Any chance that someone will test this in 3.0?

**Comment by KoBeWi** [comment]
I tested it in 3.1 and it seems like changing enablers after scene runs (i.e. via script or remote inspector too) doesn't take any effect.
