### ISSUE TITLE
Disable unused parts of Basis Universal to improve build times and reduce binary sizes

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#56310]
### Godot version

4.0.dev (28174d531)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 470.74)

### Issue description

Right now, all the default features of Basis Universal are enabled at compile-time.

- `BASISD_SUPPORT_ASTC`
- `BASISD_SUPPORT_UASTC`
- `BASISD_SUPPORT_PVRTC1` (if https://github.com/godotengine/godot/pull/56309 is merged)
- `BASISD_SUPPORT_PVRTC2` (if https://github.com/godotengine/godot/pull/56309 is merged)

The above defines could all be set to `0` so that they are disabled at compile-time. Godot does not currently support displaying those compression formats, so they're of no use in the transcoder. (ASTC support may be considered in a future Godot release, but not for 4.0 as hardware adoption will still be too low when 4.0 is released.)

See https://github.com/BinomialLLC/basis_universal/wiki/How-to-Use-and-Configure-the-Transcoder#shrinking-the-transcoders-compiled-size.

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
I've tried my hand at it: https://github.com/Calinou/godot/tree/basis-universal-disable-unused-features

The code compiles successfully, but the linking stage fails. Any ideas?

**Comment by akien-mga** [comment]
We now support and need ASTC, but indeed PVRTC could be disabled. I'm not sure the build time and binary size gains would be significant, but why not.

**Comment by fire** [comment]
Since https://github.com/godotengine/godot/pull/56309 was merged and ASTC is required. This is closable?

**Comment by Calinou** [comment]
> Since #56309 was merged and ASTC is required. This is closable?

This PR is still relevant; see https://github.com/godotengine/godot/pull/85321.
