### ISSUE TITLE
Save dialogs' file name does not start selected anymore

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#56329]
### Godot version

4.0 28174d531b7128f0281fc2b88da2f4962fd3513e

### System information

Windows 10 64 bits GLES3 GeForce GTX 1060 6GB/PCIe/SSE2

### Issue description

In Godot 3, opening a save dialog to save anything (a scene, resource, script...) starts with the file name selected:
![image](https://user-images.githubusercontent.com/1311555/147710306-9b1e4ef4-74f6-4ef9-a5b3-57a33767bd85.png)

In Godot 4, this is no longer the case. So everytime, the user has to manually select to rewrite the intented file name, it is a usability regression:
![image](https://user-images.githubusercontent.com/1311555/147710337-c7779560-6dea-4040-abc6-09dfe25de9d4.png)

### Steps to reproduce

"Save As" anything: current scene, inspector resource, script

**Comment by nongvantinh** [comment]
I this a bug or future request?

**Comment by gerhean** [comment]
May I take this issue?

**Comment by nongvantinh** [comment]
> May I take this issue?

You're welcome!
