### ISSUE TITLE
CPUParticles2D damping is limited to 100

### ISSUE THREAD

**Issue by hunterloftis** [godotengine/godot#56324]
### Godot version

Godot_v3.4.2-stable_x11

### System information

Ubuntu desktop

### Issue description

In the editor, the value for [CPUParticles2D.damping](https://docs.godotengine.org/en/stable/classes/class_cpuparticles2d.html#class-cpuparticles2d-property-damping) is arbitrarily clamped to 100.0:

![image](https://user-images.githubusercontent.com/364501/147692389-97117b68-a57b-4613-902a-7ebaa8678b8c.png)

This can be hacked around by creating a damping curve that moves from zero immediately to the actual value you want (eg, 250):

![image](https://user-images.githubusercontent.com/364501/147692573-062c946f-7740-454a-998a-28c6501450bd.png)

It may also be hackable by setting the value in code (I haven't confirmed this).

### Steps to reproduce

- Create a CPUParticles2D node
- Give it some high velocity that you want to dampen quickly (say, 1000)
- Try to dampen it to 300
- See that you can't raise the value above 100

**Comment by akien-mga** [comment]
This can be solved by adding `,or_greater` in the property hint to keep 100 as max for the slider but still allow manual input to go above. This was done for (GPU) ParticlesMaterial but not CPUParticles and CPUParticles2D:
```
scene/3d/cpu_particles.cpp
1479:   ADD_PROPERTYI(PropertyInfo(Variant::REAL, "damping", PROPERTY_HINT_RANGE, "0,100,0.01"), "set_param", "get_param", PARAM_DAMPING);

scene/2d/cpu_particles_2d.cpp
1339:   ADD_PROPERTYI(PropertyInfo(Variant::REAL, "damping", PROPERTY_HINT_RANGE, "0,100,0.01"), "set_param", "get_param", PARAM_DAMPING);

scene/resources/particles_material.cpp
55:     shader_names->damping = "damping";
1302:   ADD_PROPERTYI(PropertyInfo(Variant::REAL, "damping", PROPERTY_HINT_RANGE, "0,100,0.01,or_greater"), "set_param", "get_param", PARAM_DAMPING);
```

It can be relevant to check if other parameters of ParticlesMaterial have `,or_greater` without it being present in the equivalent of CPUParticles*.

**Comment by albinaask** [comment]
I'll give it a try.

**Comment by clayjohn** [comment]
Closed by #56748

**Comment by albinaask** [comment]
I've fixed that variant too, but git has some hickups inducced by me, will fix and push tomorrow

**Comment by albinaask** [comment]
Hi, There seem to be one damping_min and one damping_max parameter, which one should be marked as "or_greater", I guess the damping_max?
