### ISSUE TITLE
Vulkan: StandardMaterial3D's Disable Ambient Light property has no effect

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#56332]
### Godot version

4.0.dev (28174d531)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 470.74)

### Issue description

The StandardMaterial3D property **Disable Ambient Light** has no effect.

*Left: Disable Ambient Light disabled, right: Disable Ambient Light enabled:*

![2021-12-30_01 46 25](https://user-images.githubusercontent.com/180032/147713155-262ad955-0017-44b5-95a0-d6aa0d0449cb.png)

In comparison, this is how it looks if you disable ambient lighting in the Environment resource:

![2021-12-30_01 46 37](https://user-images.githubusercontent.com/180032/147713157-2a1ea501-4eac-42bb-95bc-8645b084c750.png)

This is similar to https://github.com/godotengine/godot/issues/28171, but in the Vulkan renderer (although the fix is likely different).

### Steps to reproduce

- Add a MeshInstance3D node with a PrimitiveMesh and StandardMaterial3D.
- Enable **Disable Ambient Light** in the StandardMaterial3D's properties.

### Minimal reproduction project

[test_disable_ambient_light.zip](https://github.com/godotengine/godot/files/7791116/test_disable_ambient_light.zip)

*Bugsquad edit (keywords for easier searching): ambient light disabled, ambient_light_disabled*

**Comment by robojeb** [comment]
Sorry, I did a preliminary search but didn't run across this.

**Comment by clayjohn** [comment]
Fixed by https://github.com/godotengine/godot/pull/66107
