### ISSUE TITLE
RichTextLabel: There's no option to VAlign text

### ISSUE THREAD

**Issue by timoschwarzer** [godotengine/godot#5633]
**Operating system or device - Godot version:**
Any, 2.0.4.1

**Issue description** (what happened, and what was expected):
See title

**Comment by vnen** [comment]
Related to the discussion on #5514.

**Comment by garyo** [comment]
This is still true as of Godot 3.0

**Comment by voithos** [comment]
This would be quite useful when using `RichTextLabel` as e.g. a dialog box. Also discussed here (including ~workarounds): https://godotengine.org/qa/27229/how-to-vertically-align-text-in-a-richtextlabel

**Comment by QbieShay** [comment]
Bumping on this issue. Probably @poke1024 or @willnationsdev or @olivergs can do something about it?

**Comment by xdeadmonkx** [comment]
Also waiting for RichTextLabel to behave properly in VBoxContainer without manually setting min size

**Comment by Calinou** [comment]
@xdeadmonkx There is already an issue open about that: https://github.com/godotengine/godot/issues/18260

**Comment by aaronfranke** [comment]
This is also missing for `LineEdit`. There is only Align but no VAlign.

**Comment by Calinou** [comment]
> How is vertical alignment for RichTextLabel as of 3.4?

It wasn't implemented yet, but you may be able to work it around by following one of the workarounds described in https://github.com/godotengine/godot/issues/18260 and using a CenterContainer node.
