### ISSUE TITLE
.gdignore does not exclude C# scripts from build

### ISSUE THREAD

**Issue by jimpaly** [godotengine/godot#56339]
### Godot version

3.4.2.stable.mono

### System information

MacOS (M1)

### Issue description

After adding an empty `.gdignore` file to a folder, C# scripts are still being included when I build the project. 

More specifically, I am trying to create a project-defined C# template according to [the docs](https://docs.godotengine.org/en/stable/getting_started/scripting/creating_script_templates.html). The project encounters errors while being built because I added the `%CLASS%` placeholder to the template script. My current workaround is to add a `.` in front of the folder name because apparently, that excludes the folder from being included in the build.

### Steps to reproduce

1. Create a new project
2. Create a new folder named `script_templates`
3. Create a new C# script in `script_templates`
4. Change the class name to `%CLASS%`
5. Create a new file in `script_templates` named `.gdignore`
6. Build the project in Godot (click button on top right corner)

**Comment by Calinou** [comment]
`.gdignore` only prevents resource importing. I don't think it was ever special-cased to ignore C# scripts located within a folder.

**Comment by neikeq** [comment]
You can exclude them by adding the following to your `.csproj` project file:

```csproj
<ItemGroup>
    <Compile Exclude="script_templates/*.cs" />
</ItemGroup>
```

Otherwise, some IDEs have the option to exclude a folder when you right-click it.

This should probably be added to that doc page.

I don't think we can support this automatically out of the box because the doc page says the location can be overridden via the project setting `editor/script_templates_search_path`.

**Comment by jimpaly** [comment]
@neikeq thanks for the tip!

I tried the solution you mentioned but it gave the error, `Items that are outside Target elements must have one of the following operations: Include, Update, or Remove.` However, after changing `Exclude` to `Remove`, it seems to be working now and ignoring the template files.

**Comment by neikeq** [comment]
Oops, sorry. Yes, it's `<Compile Remove=`.
