### ISSUE TITLE
[3.4.2] Horizontal Vector 2 editing broken

### ISSUE THREAD

**Issue by Norrox** [godotengine/godot#56344]
### Godot version

3.4.2.stable

### System information

Windows 10, GTX 1080 Ti

### Issue description

The property does not work.
have been trying enabled / disabled and reopen scene, restarted the project.
This works in godot 4 master

### Steps to reproduce

![Skärmbild 2021-12-30 161909](https://user-images.githubusercontent.com/13393087/147765004-6bce7d74-d6cc-47ac-ba5f-1515cf62b26b.png)

### Minimal reproduction project

[bug00023.zip](https://github.com/godotengine/godot/files/7793586/bug00023.zip)

**Comment by Calinou** [comment]
@Norrox Can you reproduce this issue in 3.3.4 and 3.2.3?

**Comment by Norrox** [comment]
I will check, ill edit this post when i have :)

> @Norrox Can you reproduce this issue in Godot [3.3.4](https://downloads.tuxfamily.org/godotengine/3.3.4/) and [3.2.3](https://downloads.tuxfamily.org/godotengine/3.2.3/)?

**Comment by Norrox** [comment]
@Calinou It works, and it also work in 3.4.2.stable, i was just to tired to realize that i tried to see changes on vector 3's when i changed the vec 2 setting -.- sorry , i close this now ;D
