### ISSUE TITLE
Inconsistent behavior of `Font.get_char_size` for different TextServer

### ISSUE THREAD

**Issue by dalexeev** [godotengine/godot#56348]
### Godot version

v4.0.dev.custom_build [340883636]

### System information

Kubuntu 21.10

### Issue description

`Font.get_char_size` returns different results for `TextServerAdvanced` and `TextServerFallback` (`internationalization/rendering/text_driver` setting).

TextServerAdvanced:

```
(0, 7) # Wrong width
(4.15625, 23)
```

TextServerFallback:

```
(6, 7)
(4.15625, 23)
```

Note that the result is different for the attached font, but not for the standard font. My font is generated by my script, which is written similar to the Image Font importer. But a different result for different TextServer is still a bug in this case.

### Steps to reproduce

See the issue description and MRP.

### Minimal reproduction project

[get_char_size.zip](https://github.com/godotengine/godot/files/7794006/get_char_size.zip)

**Comment by dalexeev** [comment]
Related?

https://user-images.githubusercontent.com/47700418/147777155-922f5c9c-d1eb-4c75-8af9-861a2d791a0c.mp4

**Comment by bruvzg** [comment]
> `Font.get_char_size` returns different results for `TextServerAdvanced`

Missing return value for the bitmap font in the `font_get_glyph_index`.
```diff
@@ -2573,7 +2573,7 @@ int32_t TextServerAdvanced::font_get_glyph_index(RID p_font_rid, int p_size, cha
 			return FT_Get_Char_Index(fd->cache[size]->face, p_char);
 		}
 	} else {
-		return 0;
+		return (int32_t)p_char;
 	}
 #else
 	return (int32_t)p_char;
```

> Related (internationalization/rendering/text_driver = Fallback)?

Probably unrelated, seems like a rounding error in the `Fallback` text server or `TextEdit`. I'll take a look at it on Monday.
