### ISSUE TITLE
Godot 4.0 GDScript preload fails in standalone build unless files are present in directory

### ISSUE THREAD

**Issue by ricmzn** [godotengine/godot#56343]
### Godot version

4.0.dev (28174d531) built with Visual Studio 2019

### System information

OS: Windows 10 (64-bit)
Renderer: Vulkan

### Issue description

The current dev build of Godot 4.0 fails to load GDScript files which use `preload` with some assets in exported builds, citing a "file does not exist" error, unless there is another file with the same name in the executable's directory.

For instance, trying to preload an asset using the path `res://square.png` fails unless there is a file named square.png next to the exported executable, but the content of that file does not matter, as Godot will still (correctly) load it from the PCK. It just bails early if the path doesn't exist in the filesystem.

This issue only affects the built-in `preload` in GDScript, and it does not affect the latest stable build (3.4.2). It's also picky about assets it fails to load (in the reproduction project, square.png is affected but icon.png isn't, and in another project, image files fail, but custom scripted resources don't).

In addition, because it causes a script parse error, affected scripts will not be attached to nodes when running in standalone mode, so this is a blocker.

### Steps to reproduce

Using the minimal reproduction project:

- Run main scene in editor: both images are loaded from filesystem
- Export project (important: it must be outside of the project directory!) and run it: only icon.png is loaded from the PCK, and an error is shown in the console:
    - `SCRIPT ERROR: Parse Error: Preload file "res://square.png" does not exist.`
- Create a placeholder file called square.png (the content does not matter, even a 0 byte empty file will work), place it in the directory where the exported project is, and run it again: both images are loaded from the PCK
- (Workaround) Delete the placeholder square.png file, replace the `preload` call in the script of the Square node (in main.tscn) with a `load` call, re-export, and run again: both images are loaded from the PCK

### Minimal reproduction project

[PreloadIssue_4.0.zip](https://github.com/godotengine/godot/files/7793325/PreloadIssue_4.0.zip)

**Comment by gustavi** [comment]
I confirm the bug and the workaround. Thank you.

**Comment by pkowal1982** [comment]
Had (still have) the same problem.

**Comment by gustavi** [comment]
The workaround does not work any more since alpha2. Any idea how to solve this issue which is a huge blocker?

**Comment by ricmzn** [comment]
Confirmed the bug still exists in Alpha 11 (using official build & template with the reproduction project). The workaround still works, but I think this should be fixed before the first beta release, otherwise many people will be surprised when a game that works in the editor suddenly fails to load assets in standalone builds.

**Comment by JoanPotatoes2021** [comment]
The workaround of replacing all `preload()`s with `load()`s still works for alpha13: `v4.0.alpha13.official [59dcddc45]` to export projects, and the issue still stands, I feel the same as **ricmzn** 🙄 , **more people will face this issue than desired and it is bloody hard to find what caused**, imho the first beta release should cover this issue, and I don't see a lot of attention towards it though; not that I know how to fix it either, so... 🤓

**Comment by cridenour** [comment]
Since alpha 16 it now affects scene files (they are exported as `.remap`) - which effectively breaks almost every usage of `preload`.

**Comment by nonchip** [comment]
this also seems to affect my shaders. they all run in the editor but not in the export.

**Comment by pozitiffcat** [comment]
Had (still have) the same problem.

**Comment by akien-mga** [comment]
@pozitiffcat That's not the same problem, this one was a GDScript bug and was fixed months ago.

Your issue is likely https://github.com/godotengine/godot/issues/25672. It's not a bug but a confusing behavior for users between the editor and the exported project.
