### ISSUE TITLE
vsync is not limiting FPS on macOS Monterey

### ISSUE THREAD

**Issue by oronbz** [godotengine/godot#56355]
### Godot version

3.4.2.stable

### System information

macOS Monterey, GLES3, AMD Radeon Pro 5300M 4 GB

### Issue description

Hi, I'm having an issue on macOS Monterey (not sure if it's on previous versions as well) where vsync doesn't work (it's not limiting the FPS to my monitor's HZ):

You can see in the image the extremely high fps 2k+ (which also comes up with high cpu usage ~80%), and vsync is enabled.

I've used the following workarounds to silent my CPU fans:
* `Force FPS` does work if I set it, but I prefer to just enable vsync and let it do its job instead of fixing a number there (:
* `Low Processor Mode` caps the FPS at 144, which also reduce CPU usage, but not recommended for games per its documentation.
* I'm not sure what's `Vsync Via Compositor` is, but enabling it doesn't solve it.

![ ](https://user-images.githubusercontent.com/1288090/147782836-5e4fd8e6-07e5-4eba-a612-befc8245cfb6.png)

### Steps to reproduce

1. Create a new project
2. Create a Node2D scene
3. Make sure `Use Vsync` is enabled on Project Settings -> Display -> Window
4. Enabled `Print FPS` on Project Settings -> Debug -> Settings
5. Run the scene and watch the `FPS` on the output

### Minimal reproduction project

[TestVSYNC.zip](https://github.com/godotengine/godot/files/7794420/TestVSYNC.zip)

**Comment by Calinou** [comment]
Can you reproduce this on the `master` branch? You can download a nightly build [here](hugo.pro/projects/godot-builds/).

**Comment by oronbz** [comment]
> Can you reproduce this on the master branch? You can download a nightly build here.

I've yet to compile godot, but I don't mind diving into it if needed, in any case the link to the nightly build gives `404`

**Comment by oronbz** [comment]
@Calinou on: v4.0.dev.calinou [9f058674a]
things are a bit better, but still buggy:

When the window is on foreground i get 240 fps (my monitor is on 120hz)
But, when the window is on background (like when the editor is on focus) i get 3k+ FPS:

![Screen Shot 2021-12-30 at 22 50 42](https://user-images.githubusercontent.com/1288090/147787285-b1702701-7a7b-48df-8aef-2195b5c7ca89.png)

**Comment by Calinou** [comment]
> I've yet to compile godot, but I don't mind diving into it if needed, in any case the link to the nightly build gives 404

I fixed the link in my comment – it's https://hugo.pro/projects/godot-builds/ :slightly_smiling_face:

**Comment by Calinou** [comment]
Fixed in macOS 13.0 (this is a macOS bug): https://github.com/godotengine/godot/issues/64475
