### ISSUE TITLE
Vulkan: MultiMeshInstance3D not showing up and having culling issues depending on how fast they get created

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#56357]
### Godot version

4.0 28174d531b7128f0281fc2b88da2f4962fd3513e

### System information

Windows 10 64 bits GLES3 GeForce GTX 1060 6GB/PCIe/SSE2

### Issue description

This one took a long time to investigate and I still think it could be simplified better...

In my game, I generate a bunch of multimeshes in many chunks around the player. The system worked perfectly fine in Godot3. Then I ported it to Godot4, and noticed that very often, chunks would not render.
A few of them manage to render, but they also seem to be affected by bad culling (they stop rendering earlier than they should depending on camera angles).

### More details

My system is part of a module that can run in editor: it's a node added as child of a voxel terrain, and it spawns multimeshes on top of that terrain. In editor, if I add one, only half of the chunks get populated, and the others are devoid of any instances, even though debug drawing suggests the presence of a *non-empty MultiMesh* in those chunks:

![image](https://user-images.githubusercontent.com/1311555/147788255-0fe3c8e1-7ff0-4050-99b4-3d853fdc6e9d.png)
Valleys are supposed to be covered with cubes:
![image](https://user-images.githubusercontent.com/1311555/147789117-388cb042-21d7-40dc-be44-d6753e1a5626.png)

I also observe the culling issues:
![image](https://user-images.githubusercontent.com/1311555/147789227-f9941f88-b665-45e7-a8d3-f3210510e39a.png)

I found however, that if I "nudge" the system by making it re-generate the instances (changing density a bit for example), at some point the chunks get rendered as expected. Then both issues stops happening onwards. It only happens on first go, kind of.

### Steps to reproduce

I tried reproducing this in a smaller project that just creates a bunch of multimeshes, but failed to find the combination of events that would make it happen.
So once again, I resorted on dumping all function calls I do to MultiMeshes and MultiMeshInstance3D (which were nodeless, I use RenderingServer directly).

These calls are nothing fancy, just a bunch of this:
```
MultiMesh 1021781309652996 create
MultiMesh 1021781309652996 set_transform_format 1
MultiMesh 1021781309652996 set_use_colors false
MultiMesh 1021781309652996 set_use_custom_data false
MultiMesh 1021781309652996 set_instance_count 35
MultiMesh 1021781309652996 set_buffer [...floats...]
MultiMesh 1021781309652996 set_mesh non_null
MultiMeshInstance 1021850029135403 create
MultiMeshInstance 1021850029135403 set_visible true
MultiMeshInstance 1021850029135403 set_multimesh 1021781309652996
MultiMeshInstance 1021850029135403 set_world non_null
MultiMeshInstance 1021850029135403 set_transform [X: (1, 0, 0), Y: (0, 1, 0), Z: (0, 0, 1), O: (0, 0, 0)]
MultiMeshInstance 1021850029135403 set_material_override null
MultiMeshInstance 1021850029135403 set_cast_shadows_setting 1
```

Then I created a project which parses that file and replays these calls individually.
I not only found that the issue reproduces there, but also that I obtain a different result depending on how many calls I decide to play per frame. It leads to random chunks to not get rendered, despite the instances being there if I query the transforms back.

If I play them all in one frame, very often, nothing shows up:
![image](https://user-images.githubusercontent.com/1311555/147788499-3462c2a1-69c1-4fc4-ad90-2ce0db82fa7c.png)

If I play 2% of them per frame:
![image](https://user-images.githubusercontent.com/1311555/147788571-8c1bba91-e772-4696-a936-6223d756eea1.png)

If I play 0.5% of them per frame:
![image](https://user-images.githubusercontent.com/1311555/147788645-cd020d01-fa24-4a8e-b939-34d2bfc8f9ae.png)

If I play 4 calls per frame:
![image](https://user-images.githubusercontent.com/1311555/147788715-c9c2c0c8-8e3e-4cd8-af76-8c525928c6cd.png)

If I play 1 call per frame, all chunks show up properly:
![image](https://user-images.githubusercontent.com/1311555/147788921-c74cfefd-9c9b-405f-9778-82d008bda5b5.png)

### Minimal reproduction project

[MultiMesh2.zip](https://github.com/godotengine/godot/files/7794675/MultiMesh2.zip)
Play main scene, and press spacebar to start playback.
You can adjust how many calls are replayed per frame by modifying `main.gd` `EVENTS_PER_FRAME`.

**Comment by Zylann** [comment]
Still happening in 83d26737727f281afcb33f66fea5d09ed6c48d5a

**Comment by cridenour** [comment]
Interestingly, in alpha 17, I'm noticing that my multi-meshes are culling too early only when their buffer was synced over the network (at via MultiplayerSynchronizer/Spawner). But if I create the same data via `set_instance_transform`, etc. it works fine.

**Comment by bitsawer** [comment]
@Zylann is this still reproducible? I updated the test project to latest GDScript syntax, it only needed a few renames like File -> FileAccess etc. However, seems like the issue has been fixed at some point, I can't repro the issue no matter what values I use with EVENTS_PER_FRAME. Then again, maybe the issue can surface depending how fast your frame rate etc. is? But there is also a good chance that this has been fixed. Here is the updated project:

[MultiMesh2-updated.zip](https://github.com/godotengine/godot/files/12109307/MultiMesh2-updated.zip)

**Comment by bitsawer** [comment]
Thanks, I think this has been fixed too at some point. I have been going through some MultiMesh bug reports and couldn't repro this one anymore, so let's be optimists and assume that it is now working as expected. I'll close this, but everyone is free to drop a comment if they can still reproduce this in some way.

**Comment by gvvim** [comment]
Might be a regression in 4.4, after updating my project I noticed that sometimes none of my generated multimeshes would appear, even though they were created and had been assigned mesh, position, rotation etc. 

There was something like a 1 in 5 chance they would just not be getting rendered on first load, but if I reloaded the level and they got rendered once, it always worked on subsequent reloads. 

Adding a small delay (0.01 * i) between creating the MultiMesh nodes seems to fix it.

**Comment by jessdecker** [comment]
> Might be a regression in 4.4, after updating my project I noticed that sometimes none of my generated multimeshes would appear, even though they were created and had been assigned mesh, position, rotation etc.
> 
> There was something like a 1 in 5 chance they would just not be getting rendered on first load, but if I reloaded the level and they got rendered once, it always worked on subsequent reloads.
> 
> Adding a small delay (0.01 * i) between creating the MultiMesh nodes seems to fix it.

Just adding a +1 here... i see the same in 4.4.
