### ISSUE TITLE
adding a "profile="  option to the scons command line yeld a warning message, while the custom.py gets parsed

### ISSUE THREAD

**Issue by MadMcCrow** [godotengine/godot#56359]
### Godot version

master branch, commit 91b97dac03996c4b8791633ea6fa8fdc47852cb6

### System information

Manjaro Linux 

### Issue description

when building from source with a `custom.py`file set via the `profile=` Scons option, you get the warning message : 
```
WARNING: Unknown SCons variables were passed and will be ignored:
    profile=path/custom.py
```
nonetheless, the `custom.py` file gets parsed (a print line at the top gets called 3 times when doing so)

### Steps to reproduce

Create a custom.py file somewhere on your system.
clone godot from github.
call 
`scons -j 4 profile=path/to/your/custom.py`

### Minimal reproduction project

This happens with my (relatively) small project : 
you can do
```
git clone https://github.com/MadMcCrow/ARMORY.git
git checkout  WFC-custom-module
git submodule update --init
make
```

**Comment by Calinou** [comment]
This is a regression of https://github.com/godotengine/godot/pull/55203. It will be fixed by https://github.com/godotengine/godot/pull/55698 if it's merged.
