### ISSUE TITLE
Feature to close all open Docs in the list of scripts

### ISSUE THREAD

**Issue by batmanasb** [godotengine/godot#5636]
When someone looks up Docs within the editor, they open up in the script list and take a while to close using ctrl+w. So maybe a "Close All Docs" button should be added to get rid of them the easy way.

[Here's where I got the idea](https://godotengine.org/qa/5975/how-to-remove-unwanted-references)

**Comment by suptoasty** [comment]
An editor option to close open documents on exiting projects, would be a nice extension to this idea.

**Comment by r1cebank** [comment]
I will take this issue.
