### ISSUE TITLE
Dragging scene into 3D viewport with colliders pulls it towards the camera

### ISSUE THREAD

**Issue by SaracenOne** [godotengine/godot#56361]
### Godot version

9f058674acebf9a7a0704cdbc26dc9f6d853b16e

### System information

Windows 10, Vulkan, Intel® Core™ i7-8700K, Nvidia GTX 1080 (471.11)

### Issue description

Dragging a scene into the 3D viewport which has colliders will result in the object being pulled towards the camera whenever the mouse moves

### Steps to reproduce

Import a GLTF file, generate colliders for it in the import settings, drag into a 3D scene

### Minimal reproduction project

[collision_drag_demonstration.zip](https://github.com/godotengine/godot/files/7794877/collision_drag_demonstration.zip)
[collision_drag_demonstration_3_x.zip](https://github.com/godotengine/godot/files/7795014/collision_drag_demonstration_3_x.zip)

**Comment by Calinou** [comment]
Can you (or anyone else) reproduce this on 3.4?

**Comment by SaracenOne** [comment]
I'll try testing it now. If we have the same issue, I can backport the fix to that too

**Comment by SaracenOne** [comment]
While it does not seem quite as obvious in the 3.x branch (maybe something to do with the different physics or hulls generated in the example), I can confirm it did happen so I have opened a PR backporting this to the 3.x branch too
