### ISSUE TITLE
Vulkan: Lights with Size larger than 0 (especially larger than 1) produce NaNs in specular highlights

### ISSUE THREAD

**Issue by unfa** [godotengine/godot#56373]
### Godot version

4.0 dev

### System information

Arch Linux, KDE Plasma, Radeon RX580, amdgpu driver

### Issue description

Lights with large radius (omni, spot and directional) produce strange black spots in specular hilights on glossy surfaces.

Example:
![image](https://user-images.githubusercontent.com/491704/147827333-138f1c69-2a2f-4650-aba9-8b55620cda10.png)

A larger example:
https://youtu.be/5XyleMpNhjM

Minimal reproduction project screenshot:
![image](https://user-images.githubusercontent.com/491704/147827530-ca3cac14-b19e-45b7-866c-ecd1974d256e.png)

### Steps to reproduce

1. Create a mesh with a glossy surface
2. Create a light and set the size to 1 or larger
3. Look at the specular reflection - it should be black in the middle

### Minimal reproduction project

[Black Hilights.zip](https://github.com/godotengine/godot/files/7796382/Black.Hilights.zip)

**Comment by Calinou** [comment]
I can confirm this on commit 28174d531 (Fedora 34, NVIDIA 470.74).

**Comment by Calinou** [comment]
I can still reproduce this on 345b4bb86. Note that this only occurs if the material's roughness is `0.01`, *not* `0.0` or `0.02` or greater.

**Comment by unfa** [comment]
Yes.Coincidentally my reproduction project uses roughness of 0.01 and it indeed occurs only with that roughness value:
![image](https://user-images.githubusercontent.com/491704/156892717-cbd5aacc-1f9d-4a71-bb46-cc8c0bc2048e.png)

**Comment by clayjohn** [comment]
This is actually a very interesting floating point precision error!

It appears in our distribution function:
https://github.com/godotengine/godot/blob/f488a841c7225a4d80abbc04c74079fbbac01c77/servers/rendering/renderer_rd/shaders/scene_forward_lights_inc.glsl#L3-L7
``alpha`` is equal to ``roughness * roughness`` so ``alpha2`` is equal to ``roughness^4``, when ``roughness`` is ``0.01`` ``alpha2`` becomes ``1e-8`` which is no problem for 32 bit floating point numbers! ... until it is shifted by 1 unit.... ``-0.99999999`` cannot be represented by a 32 bit floating point number and so becomes ``-1`` Suddenly the above function turns into
```
 	float d = 1.0 - 1.0 * cos_theta_m * cos_theta_m; 
 	return alpha2 / (M_PI * d * d); 
```

The ``size`` property of lights is essentially added to ``cos_theta_m`` and then clamped to [0,1]. So with lights with size ``cos_theta_m`` tends towards ``1.0`` so our function becomes:
```
 	float d = 1.0 - 1.0 * 1.0 * 1.0; // 0.0 
 	return alpha2 / (M_PI * d * d); // uh-oh divide by zero produces NaNs
```
... aaaaand we end up with an NaN patch in the centre of the specular highlight where the value of ``cos_theta_m`` is equal to ``0.0``

One way to fix this is to replace our distribution function with one that is more resilient (but equivalent)
e.g. replace 
https://github.com/godotengine/godot/blob/f488a841c7225a4d80abbc04c74079fbbac01c77/servers/rendering/renderer_rd/shaders/scene_forward_lights_inc.glsl#L3-L7
with
```
float a = cos_theta_m * alpha;
float k = alpha / (1.0 - cos_theta_m * cos_theta_m + a * a);
return k * k * (1.0 / M_PI);
```

**Comment by Snowapril** [comment]
How about this? This code also could avoid divide-by-zero and will be same with original (Reference on [filament D_GGX implementation](https://github.com/google/filament/blob/036bfa9b20d730bb8e5852ed449b024570167648/shaders/src/brdf.fs#L54-L79))

```glsl
 float D_GGX(float cos_theta_m, float roughness) { 
 	float a = cos_theta_m * roughness;
 	float k = roughness / (1.0 - cos_theta_m * cos_theta_m + a * a);
 	return k * k * (1.0 / M_PI);
 } 
```

Below image generated with provided project and updated `scene_forward_lights_inc.glsl`
![image](https://user-images.githubusercontent.com/24654975/158063034-474a8a7a-a05e-4c9c-b994-c96ad25189eb.png)
If this is OK, can I submit PR with this code? 😊

**Comment by clayjohn** [comment]
> How about this? This code also could avoid divide-by-zero and will be same with original (Reference on [filament D_GGX implementation](https://github.com/google/filament/blob/036bfa9b20d730bb8e5852ed449b024570167648/shaders/src/brdf.fs#L54-L79))
> 
> ```glsl
>  float D_GGX(float cos_theta_m, float roughness) { 
>  	float a = cos_theta_m * roughness;
>  	float k = roughness / (1.0 - cos_theta_m * cos_theta_m + a * a);
>  	return k * k * (1.0 / M_PI);
>  } 
> ```
> 
> Below image generated with provided project and updated `scene_forward_lights_inc.glsl` ![image](https://user-images.githubusercontent.com/24654975/158063034-474a8a7a-a05e-4c9c-b994-c96ad25189eb.png) If this is OK, can I submit PR with this code? 😊

Yes this code is fine, it is the same as what I posted above. Go ahead and submit a PR! :)
