### ISSUE TITLE
Scroll Container doesn't follow focus of elements inside it

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#5637]
godot alpha 2.1 linux x32

Structure:
ScrollContainer
-- VboxContainer
----ItemEntry

When navigating through entries with keyboard, scroll container doesn't follow the focus and you can't see what item is selected. Also, you can't scroll through entries, unless you hover your mouse over the scroll bar or empty space in the list (which isn't how scrolling works, check any scrolling lists in your OS). 

What should happen: 
When you focus on entry that's partially or completely out of bounds of scroll container, it should set it's value to completely show the entry. If you scroll mouse with cursor in bounds of scroll container it should scroll. Pressing PageDown/PageUp should set scroll so only the last/first element is visible on top/bottom of the scroll container. 

At screenshot you can see how the topmost item in list has focus. If you press up, it switches focus to next element without moving the scroll. For controller friendly games it pretty much breaks the usability. 
![clearcolor16](https://cloud.githubusercontent.com/assets/10696955/16716169/c0afdcf4-46fd-11e6-9419-09cf3cc4e961.png)

[ScrollContainerBuggeh.tar.gz](https://github.com/godotengine/godot/files/357137/ScrollContainerBuggeh.tar.gz)
Project for testing. In scroll container, you can scroll through elements only when you hover empty area. Issue with focus is present in both ItemList and ScrollContainer

**Comment by Algorithmus** [comment]
I had a similar issue in my game, but worked around it by listening on focus changes and updating the scroll position manually. It works alright for the most part, but there are issues like RichTextLabels content getting skipped and it sometimes won't scroll all the way if you add new nodes.

**Comment by lekoder** [comment]
I just got hit by this very issue in 3.1-alpha. Is it scheduled to be fixed anytime soon?
