### ISSUE TITLE
Error while attempt to connect signal "connected_to_server"

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#56386]
### Godot version

v3.4.2.stable.mono.official [45eaa2daf]

### System information

Debian 11

### Issue description

I received this error :
```
E 0:00:01.578   connect: In Object of type 'NetworkedMultiplayerENet': Attempt to connect nonexistent signal 'connected_to_server' to method 'Node.OnServerConnected'.
  <C++ Error>   Condition "!signal_is_valid" is true. Returned: ERR_INVALID_PARAMETER
  <C++ Source>  core/object.cpp:1462 @ connect()
  <Stack Trace> :0 @ Int32 Godot.NativeCalls.godot_icall_5_637(IntPtr , IntPtr , System.String , IntPtr , System.String , IntPtr , UInt32 )()
                Object.cs:517 @ Godot.Error Godot.Object.Connect(System.String , Godot.Object , System.String , Godot.Collections.Array , UInt32 )()
                GameServer.cs:51 @ void DesertEdge.Singleton.GameServer.ConnectionToServer()()
                GameServer.cs:87 @ void DesertEdge.Singleton.GameServer.OnLoginRequestsReturned(Boolean , System.String )()
                :0 @ void Godot.NativeCalls.godot_icall_2_635(IntPtr , IntPtr , System.String , System.Object[] )()
                Object.cs:364 @ void Godot.Object.EmitSignal(System.String , System.Object[] )()
                Gateway.cs:109 @ void DesertEdge.Singleton.Gateway.ReturnLoginRequest(Boolean , System.String )()
                :0 @ void Godot.NativeCalls.godot_icall_0_3(IntPtr , IntPtr )()
                MultiplayerAPI.cs:256 @ void Godot.MultiplayerAPI.Poll()()
                Gateway.cs:52 @ void DesertEdge.Singleton.Gateway._Process(Single )()
```
Since 3.4.2 
I think its a regression
From Docs seems it didn't change 
https://docs.godotengine.org/en/stable/search.html?q=connected_to_server&check_keywords=yes&area=default

### Steps to reproduce

My code

Working:
`Global.ServerNetwork = new NetworkedMultiplayerENet();`
`GetTree().NetworkPeer = Global.ServerNetwork;`
`GetTree().Connect("connected_to_server", this, nameof(OnServerConnected));`

Not working:
`Global.ServerNetwork = new NetworkedMultiplayerENet();`
`GetTree().NetworkPeer = Global.ServerNetwork;`
`Global.ServerNetwork.Connect("connected_to_server", this, nameof(OnServerConnected));`

While `server_disconnected`, `connection_failed` signals are working in both way.

### Minimal reproduction project

NA

**Comment by Calinou** [comment]
@git2013vb Can you reproduce this in GDScript?

**Comment by zaevi** [comment]
Only `MultiplayerAPI` and `SceneTree` have signal `connected_to_server` (as SceneTree owns a MultiplayerAPI instance)

You may like to use `connection_succeeded` signal from `NetworkedMultiplayerPeer`:
```csharp
Global.ServerNetwork.Connect("connection_succeeded", this, nameof(OnServerConnected));
```

**Comment by git2013vb** [comment]
So.. Its not a regression, neither a bug; just a missing/wrong documentation? Or there is a reason why we have two different signals for my understand they do the same thing? It is possible to explain the differences and the possibilities in docs under Networking section - even better if we can have a schema/workflow - ? I have not enough info/knowledge to do it.

**Comment by mhilbrunner** [comment]
> Or there is a reason why we have two different signals for my understand they do the same thing?

They are similar but different. To quote the docs:
> **connection_succeeded ( ):** Emitted when a connection attempt succeeds.
https://docs.godotengine.org/en/stable/classes/class_networkedmultiplayerpeer.html
> **connected_to_server ( ):** Emitted when this MultiplayerAPI's network_peer successfully connected to a server. Only emitted on clients.
https://docs.godotengine.org/de/stable/classes/class_multiplayerapi.html

Note that one is emitted by the MultiplayerAPI, the other one by the specific client peer. But yeah, in general you often use them for similar purposes. This area is indeed currently unclear, and a lot of the multiplayer documentation will need to be reworked for Godot 4.0. I'm going to close this as its more an issue for the [Godot docs](https://github.com/godotengine/godot-docs/issues) repo. Feel free to open an issue there, especially if its still not clear after the Godot 4 rework!
