### ISSUE TITLE
No function available to get the vertical scrollbar of a TextEdit

### ISSUE THREAD

**Issue by andrea-calligaris** [godotengine/godot#56383]
### Godot version

3.3.4.stable

### System information

Ubuntu

### Issue description

There currently is no function to get the vertical scrollbar of a TextEdit.

### Steps to reproduce

---

### Minimal reproduction project

---

**Comment by Calinou** [comment]
Closing, as feature proposals should be discussed on the [Godot proposals](https://github.com/godotengine/godot-proposals) repository. This repository is now used for bug reports only.

Make sure to follow the proposal template when opening a new proposal – don't just copy and paste the text you wrote in this issue.
