### ISSUE TITLE
RichTextLabel doesn't get updated when text has been changed

### ISSUE THREAD

**Issue by timoschwarzer** [godotengine/godot#5639]
**Operating system or device - Godot version:**
Any, 2.0.4.1

**Issue description** (what happened, and what was expected):
RichTextLabel doesn't get updated in editor after changing its text. It does get updated after toggling BBCode.

**Comment by akien-mga** [comment]
Fixed in master with #5606, but I don't intend to do a new 2.0.x release unless there are critical bugs, so it's probably a wontfix.

**Comment by timoschwarzer** [comment]
Ah great. Then we can close this issue.
