### ISSUE TITLE
Tilemap's alternative tiles' transpose property not working (at least in editor)

### ISSUE THREAD

**Issue by axo-lotl** [godotengine/godot#56390]
### Godot version

4.0.dev (20211108 version)

### System information

Windows 10

### Issue description

When creating alternative tiles using the new TileMap/TileSet editor, the option to transpose leaves the alternative tile unchanged. The options to flip horizontally and vertically work fine.

![transpose not working](https://user-images.githubusercontent.com/55570416/147841756-8bbd5959-0598-4eaa-8b84-9e9d7a533f13.PNG)

(The transposition is also not reflected when using the alternative tile to paint in the TileMap.)

I am not familiar enough with Godot 4 to know if this is purely an issue with the TileMap/TileSet editor or with the backend.

### Steps to reproduce

1. Create a new TileMap.
2. Create a new TileSet for the TileMap.
3. Drag in any texture to create some tiles in the TileSet.
4. Select any base tile and create an alternative tile for it.
5. Select the alternative tile and check the "Transpose" property.

### Minimal reproduction project

[Bug_Transpose.zip](https://github.com/godotengine/godot/files/7797256/Bug_Transpose.zip)

(The rightmost frog is the TileMap an alternative tile with the transpose property checked.)

**Comment by KoBeWi** [comment]
Probably caused by #44365
