### ISSUE TITLE
Translation import issue with windows-1251 encoded .csv with CRLF line endings

### ISSUE THREAD

**Issue by ret80** [godotengine/godot#5640]
**Operating system or device - Godot version:**
2.0.2 - 2.0.4.1 win 10, mac os

**Issue description** (what happened, and what was expected):
Localization does not work. It seems that the translations are not imported.

PS
And do support ";" as a separator in a csv file
**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):
https://yadi.sk/d/80XgbqfJtAyAz

**Comment by ret80** [comment]
Huge request not strongly tightened with this bug and see it. And correct possible. Just burn all the terms. :( Thanks in advance.

**Comment by akien-mga** [comment]
I can confirm the bug. I converted your .csv to a Unix-like file in UTF-8 and then it works fine. I guess the importer chokes on the windows-1251 encoding.

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by ret80** [comment]
The problem still exists. If a line break is 0x0D 0x0A localization is not working.

**Comment by reduz** [comment]
I don't see any problem with 0D 0A, importer is working fine and translations are being read, though text is completely gibberish.

What will not work is windows-1251, Godot only supports UTF-8 for files and this is not going to change. Will close this issue.
