### ISSUE TITLE
Changing editor shortcuts has become very inconvenient

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#56407]
### Godot version

bc2445d

### System information

W10

### Issue description

I just needed to change a few shortcuts in the Editor Settings and it's painful to do. You need to unfold shortcut to edit it, but when you do any change, the dialog will reset and fold your shortcut again.

The shortcuts shouldn't fold themselves randomly. But more importantly, there should be a way to edit a shortcut without opening it, e.g. double clicking on the binding could automatically edit the primary shortcut.

### Steps to reproduce

1. Try to change some editor shortcuts
2. *pain*

**Comment by Kemeros** [comment]
Not sure if this is off topic or not but the naming of the shortcut sections confused me a bit. I'm guessing other noobs might feel the same.

Took me a second to understand that Canvas Item Editor is for the 2D Editor and Spatial Editor is for 3D Editor.

I mean... they are called 2D and 3D editor in the General settings, why name it differently in the shortcuts?

**Comment by EricEzaM** [comment]
> I just needed to change a few shortcuts in the Editor Settings and it's painful to do. You need to unfold shortcut to edit it, but when you do any change, the dialog will reset and fold your shortcut again.

I don't experience this behaviour... When changing a shortcut's events, the tree stays open. Even after closing and reopening the editor settings dialog.
