### ISSUE TITLE
Interacting with UIView over top the GodotView repeats previous touch events

### ISSUE THREAD

**Issue by grundee** [godotengine/godot#56417]
### Godot version

3.4.2-stable

### System information

iOS 12.4.9

### Issue description

I am integrating Appodeal (https://appodeal.com) with an iOS app (writing a new Godot iOS plugin), and I was able to show a test banner ad on top of the screen using the following plugin code:

```
void PluginExample::show_banner() {
    UIViewController *vc = [[[[UIApplication sharedApplication] delegate] window] rootViewController];
    [Appodeal showAd:AppodealShowStyleBannerTop rootViewController:vc];
}
```

Something strange occurs when actually clicking the banner: If I pressed a Button control before tapping the banner, that button will be pressed again immediately after the banner tap and before the banner opens a web browser. The effect is that a user who pressed the "Play Game" button, returned back to the main menu from the game, and then pressed the banner will have a new game started when they return from the ad!

After looking into why events would be replayed in this way, I found that if I comment out [this line](https://github.com/godotengine/godot/blob/3.4/platform/iphone/godot_view.mm#L162) in godot_view.mm then everything works fine. I am using Emulate Mouse from Touch, so it is unlikely that I am using gestures supported by that listener anyway.

My speculation is that the gesture listener is resending delayed events for some reason, but I am not familiar enough with iOS programming or Objective-C to tell why.

### Steps to reproduce

1. Enable Emulate Mouse with Touch
2. In an iOS plugin or module, display another UIView over top the GodotView (I used an Appodeal banner ad)
3. Create a menu with a button with visible effect on press (changing text, etc).
4. Export for iOS and run on device
5. Press the button and observe the effect
6. Press the overlaying banner

Expected: Banner effect only occurs.

Observed: Button press *and* banner effect occur.

**Comment by naithar** [comment]
@grundee do you have a MRP to test this issue as I can't reproduce it. 
But from the way it described, it seems like either both `GodotGestureRecognizer` and `GodotView` classes should filter out any `UITouch` that didn't come from `GodotView` or `Appodeal` uses `UIView`s instead of `UIViewController` that somehow breaks input.

**Comment by grundee** [comment]
Here is an MRP I set up: https://github.com/grundee/godot-bug-repro

The README walks through the steps to compile a simple plugin that creates an Appodeal banner, and the bug reproduces for me on Godot 3.4.2-stable.

**Comment by naithar** [comment]
Now I can reproduce the issue, thanks. 
Also to automatically ad `-ObjC` you can use `linker_flags` key in `gdip` file, like it's done here: https://github.com/godotengine/godot-ios-plugins/blob/master/plugins/apn/apn.gdip

**Comment by naithar** [comment]
https://github.com/naithar/godot/commit/7a8dd4eff53e768fdc82498cadd5404c5457f951 this changes should help fix the issue, can you test it?
I've added filtering to `GestureRecognizer` to work only with `GodotView`'s touches and renamed view methods so when `UIWindow` sends events to `GodotView` directly it wouldn't process as input.

**Comment by grundee** [comment]
Works for me! Thanks for the fix!

**Comment by naithar** [comment]
Great, I'll try to make PR soon for both `3.x` and `4.0`
