### ISSUE TITLE
TileSet editor doesn't open right after creating TileSet

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#56413]
### Godot version

bc2445d

### System information

W10

### Issue description

When you create a fresh new TileMap, right click `tile_set` property and create a new TileSet, the resource is created, but then nothing happens. You need to click the TileSet resource for the TileSet bottom editor to appear.

This could make sense if not the fact that you can deselect TileMap node and select it again for the TileSet to appear again. Whenever you do something with TileMap, both TileSet and TileMap editors are always automatically visible. The only exception is when you create a new TileMap and click it when it doesn't have any TileSet. I got used so much to having both editors always visible that it actually confused me.

When a new TileSet is created in TileMap, the TileSet editor tab should be immediately visible.

### Steps to reproduce

1. Create new TileMap node
2. Create new TileSet for that TileMap
3. Where editor
![image](https://user-images.githubusercontent.com/2223172/147861891-9c65d1f0-5d26-42ec-9d07-c905f5ba413d.png)

**Comment by SaracenOne** [comment]
Did a fix for this which also makes the tileset editor always be automatically selected when the tileset is selected in the inspector. The only question I think still remains around this is the possibility that we should automatically switch the tileset editor when a tileset with no source data configured is assigned. It's a minor thing, but it might help further reduce confusion
