### ISSUE TITLE
Mouse wheel zooming doesn't work when animation track zoom is very low

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#56415]
### Godot version

bc2445d

### System information

W10

### Issue description

Might be some precision issue, but when you zoom out very much, you can't use mouse wheel to change the zoom of animation track editor:
![RJlct6cPg7](https://user-images.githubusercontent.com/2223172/147862120-d110a9a7-6f5b-453f-afbd-8798e2afb8af.gif)
You can use the slider to make the zoom stuck or you can zoom out until you can't zoom further, even though there's still some space left.

### Steps to reproduce

1. Add AnimationPlayer with animation
2. Zoom out the animation track view using the slider to the very end
3. Try using Ctrl + wheel

**Comment by Kemeros** [comment]
Reproduced with v4.0.dev.custom_build [e09881de9] on Windows 10.

**Comment by Kemeros** [comment]
You can work around the bug by pointing the mouse on the zoom slider. Then you can reach both ends of the slider with CTRL+Wheel.

But if you drag the slider completely to the left and point your mouse anywhere else than the slider, it stop working.

So the mouse position is apparently related.
