### ISSUE TITLE
Error when keying Sprite's frame property

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#56412]
### Godot version

bc2445d

### System information

W10

### Issue description

When you create animation for Sprite node, there's this `frame` property auto-increment, i.e. you press the Key button and it will insert the frame key and automatically increment the property, so you can just click it a couple of times and you have animation.

This is very minor issue, but this never checks the sprite's bounds. If you reach the final frame, you will get an error with every Key press that the frame is out of bounds.

The relevant code is in `editor_inspector.cpp` if anyone is up for a fix. The editor should just bounds check the next frame before incrementing.

### Steps to reproduce

1. Add Sprite2D/3D
2. Add AnimationPlayer
3. Create animation
4. Insert keys for the `frame` property in sprite
5. Just keep doing it
6. Errors

**Comment by brennengreen** [comment]
I believe what the fix we're looking for is here:
```cpp
if (use_keying_next()) {
	if (property == "frame_coords" && (object->is_class("Sprite2D") || object->is_class("Sprite3D"))) {
		Vector2i new_coords = object->get(property);
		new_coords.x++;
		if (new_coords.x >= object->get("hframes").operator int64_t()) {
			new_coords.x = 0;
			new_coords.y++;
		}

		call_deferred(SNAME("emit_changed"), property, new_coords, "", false);
	} else {
		call_deferred(SNAME("emit_changed"), property, object->get(property).operator int64_t() + 1, "", false);
	}

	call_deferred(SNAME("update_property"));
}
```
Just adding bounds here for new_coords. Is it as simple as adding it to the general conditional (e.g. calling `call_deferred(SNAME("emit_changed"), property, object->get(property).operator int64_t() + 1, "", false);` when out of bounds) or do we want to handle it in a special way when we get out of bounds
