### ISSUE TITLE
(3.3) KinematicBody2D move_and_collide is handling marginal collisions inconsistently

### ISSUE THREAD

**Issue by wareya** [godotengine/godot#56421]
### Godot version

3.3

### System information

Windows

### Issue description

`move_and_collide` places bodies close enough to other objects that further calls to `move_and_collide` will cause the kinematic body to get pushed away from the object it collided with **even if** the second call's movement path points perpendicular to the first collision normal.

In other words: if I `move_and_collide` a body straight down into the ground, then sideways, the sideways call gives a small but nonzero upwards travel, instead of zero as would be expected.

The issue is: the first call should not place the body so close to the ground that the second call causes the body to get pushed outside of the ground.

In 3.3 and earlier, this is even worse, because no collision object is returned at all, so it's not clear that the motion traveled by the second call is not exactly what was requested. ~~In 3.4 and the 3.x branch, a collision object is indeed returned, which is what should happen if the travel is not exactly what was requested.~~

~~Still happens on the current `3.x` branch.~~
EDIT: I've realized after further testing that this bug is inconsistent and hard to reproduce in a minimal project on 3.4 and the current 3.x branch, so I've narrowed it down to 3.3. 

This goes all the way back to at least 3.0.6. I did not test versions earlier than 3.0.6.

### Steps to reproduce

Run the `MoveAndCollideTest` scene in the included reproduction project, look at the debug output, observe that the y component printed for the horizontal travel vector is a small negative number (indicating upwards travel). Experiment with enabling different collision shapes inside of the kinematic body and see how this changes the upwards motion.

Setup:

![image](https://user-images.githubusercontent.com/585488/147865847-0df5e89b-4f12-4ea9-9f61-efd76f26583b.png)

```gdscript
extends Node2D

func _ready():
    $Box.global_position  = Vector2(0,  8)
    var collision
    var oldpos
    oldpos = $Body.global_position
    collision = $Body.move_and_collide(Vector2(0, 8), false)
    if collision:
        print("%s %s %s" % [collision.travel, collision.normal, collision.position])
    else:
        print("no collision %s" % ($Body.global_position-oldpos))
    oldpos = $Body.global_position
    collision = $Body.move_and_collide(Vector2(8, 0), false)
    if collision:
        print("%s %s %s" % [collision.travel, collision.normal, collision.position])
    else:
        print("no collision %s" % ($Body.global_position-oldpos))
```

Output (3.3.2):

```
(0, 1.96875) (0, -1) (4, 0)
no collision (8, -0.047931)
```

### Minimal reproduction project

[MoveAndCollideTest.zip](https://github.com/godotengine/godot/files/7798548/MoveAndCollideTest.zip)

**Comment by Zireael07** [comment]
This is likely the cause of collisions feeling "bumpy" (I strongly suspect the same is true in 3D)

**Comment by wareya** [comment]
"Bumpy" collisions are/were mostly because of margin rejections from different objects being added together instead of clamped together, which I *believe* is fixed by now.

**Comment by wareya** [comment]
Closing because 3.5 is happening so 3.3.x is presumably going to be a dead branch, and the issue I was able to reproduce consistently was only in 3.3.x, not 3.4.x or later. I'll open an issue for the 3.4.x/3.5.x bug I was experiencing later, once I have the time to figure out how to reproduce it consistently.
