### ISSUE TITLE
Avoid API changes in revisions (x.y.Z).

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#5644]
Re: https://godotengine.org/article/maintenance-release-godot-2-0-4 -
"Added InputMap.get_actions()"
"Rename CanvasItem.edit_get() to edit_get_state()"

Whilst the former isn't such an issue, the latter could cause (albeit only minor) issues if the previous syntax/statement is removed altogether.

Perhaps such changes should either be reserved for minor versions (x.Y.z) or a warning added that the previous way of doing things is obsolete (and to be removed at the next minor version increase)?

**Comment by akien-mga** [comment]
Yeah but see #4653.

As long as I will be alone to maintain the stable branch, I'll continue doing it with my gut feeling and won't overly bother myself with trying to preserve 100% API compatibility. I think I'm doing an OK job already, and so far nobody complained about any API change (apart from people concerned from a theoretical standpoint).

`InputMap.get_actions()` does not impact the existing API, it just adds a simple new method, I don't see why anyone would be annoyed by having one function more. You don't have to use it.

Renaming `CanvasItem.edit_get()` is indeed an API breakage and I thought a bit about it before cherry-picking it, but I consider that the previous function name was a bug, and if a couple users were using it, they'll check the release notes and see why they're now getting an error.

**Comment by Sslaxx** [comment]
No complaints here. I hadn't been aware of #4653 (or its unpleasantness).

**Comment by akien-mga** [comment]
Closing as I think that the current subjective cherry-picking I do for patch releases is good enough. I'd be open to real life examples from users that got issues due to the limited API changes that were done over 2.0.x; so far the feedback is mostly positive, so I'm happy enough with how I worked.
