### ISSUE TITLE
Godot 4 cannot export project with C# "Target platform not supported"

### ISSUE THREAD

**Issue by harmless-tech** [godotengine/godot#56450]
### Godot version

4.0.dev.mono

### System information

Windows 10

### Issue description

When trying to export a project with a C# script you get the error "Target platform not supported." The exe and pck files are still created but the data folder is not.
From my testing it seems like in https://github.com/godotengine/godot/blob/master/modules/mono/editor/GodotTools/GodotTools/Export/ExportPlugin.cs#L387 the feature "windows" is passed in, but OS.PlatformNameMap.TryGetValue seems to expect "Windows" instead.
Changing the foreach loop in https://github.com/godotengine/godot/blob/master/modules/mono/editor/GodotTools/GodotTools/Export/ExportPlugin.cs#L387 to below allows project to be exported.
```C#
foreach (var feature in features)
{
    string f = feature.Length > 0 ? $"{feature[0].ToString().ToUpper()}{feature.Substring(1)}" : feature;

    if (OS.PlatformNameMap.TryGetValue(f, out platform))
        return true;
}
```

### Steps to reproduce

1. Clone from master.
2. Build:
    - ```scons -j12 p=windows tools=yes module_mono_enabled=yes mono_glue=no```
    - ```bin\godot.windows.tools.64.mono --generate-mono-glue modules/mono/glue```
    - ```scons -j12 p=windows target=release_debug tools=yes module_mono_enabled=yes```
    - ```scons -j12 p=windows target=release_debug tools=no module_mono_enabled=yes```
    - ```scons -j12 p=windows target=release tools=no module_mono_enabled=yes```
3. Move and rename export templates.
4. Export project.

### Minimal reproduction project

[TestProject.zip](https://github.com/godotengine/godot/files/7799848/TestProject.zip)

**Comment by GeorgeS2019** [comment]
@harmless-tech  have not try building godot4 for mono. How stable is that?

**Comment by raulsntos** [comment]
This probably broke because of #47391

C# support in the `master` is about to go through big changes as the `dotnet6` branch gets merged for 4.0, as a consequence this is an area of the module that will change a lot so fixing this now would not be very useful, instead it's better to wait until this transition is complete.

**Comment by GeorgeS2019** [comment]
@raulsntos thx for joining the .NET6 migration to speed up the process. It is still confusing for the Godot .NET community how long we need to wait, 6 months to end of 2022? We are encouraged by information like [this](https://github.com/godotengine/godot/pull/56303#issue-1090163973). On weekly basis, it is still unclear we are waiting for Godot 4.0 or 4.1 if the dotnet 6 migration will happen.

**Comment by GeorgeS2019** [comment]
@harmless-tech will you look into the [#47391](https://github.com/godotengine/godot/pull/47391) for the .NET community as suggested so we have at least a working Godot4 dev c# to work during this transition the next 6 months?
