### ISSUE TITLE
3.4.x Buttons not showing Focus texture unless 'Normal' texture is set when using keyboard control

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#56459]
### Godot version

3.4

### System information

Linux

### Issue description

On converting from 3.3 to 3.4 I noticed my menu stopped working. It is a basic texture button based system that can be controlled by mouse or keyboard.

The mouse still works, however keyboard navigation does not work if no 'normal' texture is set.

As per the video below and attached code you can move the mouse and it selects the menu items correctly showing the focus texture, however when using cursor up/down it only shows the focus texture if a normal texture is set, as can be seen in the video (or code) when you press up/down nothing is shown until you get to the bottom three buttons. Prior to 3.3 the menu worked as expected and all menu items showed the focus texture.

Note, this is probably an aside as I don't know if this is a bug/feature/the way it is, but in order to initially get focus I have to now explicity call grab_focus() in code on the first menu item. In 3.3 my menu automatically worked with the keyboard without having to first grab_focus()

https://user-images.githubusercontent.com/12863685/147927784-ec157cd3-4709-4834-99c4-cfe06cd08b78.mp4

### Steps to reproduce

1. Open code
2. Run
3. Mouse movement works ok
4. Cursors do not show the focus item on the top half of the menu

### Minimal reproduction project

[menu_bug.zip](https://github.com/godotengine/godot/files/7801754/menu_bug.zip)

**Comment by timothyqiu** [comment]
Related to #47280, it separated hover from focus.

**Comment by akien-mga** [comment]
CC @godotengine/gui-nodes

**Comment by chucklepie** [comment]
Thanks for taking the time to look, I can confirm from a short trial that setting a Normal texture seems to (temporarily) fix it, so presume this is a bug. 

But a question if I may: I created the image using an ImageTexture from the dropdown as below. But when I move out of the screen and back it changes from transparent checkboard to black and displays as black on screen. Is this a rendering/gui problem or something else (i.e. should it be black and if it should, should it immediately show black, and how do I create a transparent ImageTexture from the selection?)

![image](https://user-images.githubusercontent.com/12863685/147968015-645972b5-3525-43ed-bf79-63771a5b4c76.png)
