### ISSUE TITLE
CharacterBody2D vs KinematicBody2D (tunneling, performance)

### ISSUE THREAD

**Issue by dmaz** [godotengine/godot#56467]
### Godot version

v3.4.2.stable, v4.0.dev [9f058674a] (target=release_debug)

### System information

win10 - GLES3, Vulkan, 2080 super

### Issue description

in 3.x I've used KinematicBody2D for all high speed bullets as they are not susceptible to tunneling.  moving over to 4 I've found that not only is the replacement CharacterBody2D clearly susceptible, the performance is quite a bit worse on my machine even though it allows the tunneling.

also, 4 doesn't allow you to disable bvh and use the 2d grid hash instead.   the 2d grid hash is often faster when cell size is properly tuned in 3.x.   in this example I can get another 7.5% bump in object count with the 2d grid hash at 128 (vs bvh)

### Steps to reproduce

shoot short kinematic type objects at thin StaticBody2D objects
https://github.com/dmaz/kbull.git

### Minimal reproduction project

[kbull-master.zip](https://github.com/godotengine/godot/files/7803671/kbull-master.zip)

**Comment by Calinou** [comment]
cc @lawnjelly @pouleyKetchoupp

**Comment by dmaz** [comment]
any chance of a comment on this?   if this is the intended behavior maybe a limited BulletBody2D or something that's super fast with zero tunneling?

**Comment by dmaz** [comment]
this ticket should be closed.  this was an issue with differences between colliders.  once corrected everything seems to work fine and the performance now actually seems better in latest versions of master
