### ISSUE TITLE
Inverse_lerp problem

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#56461]
### Godot version

v3.4.2.stable.official [45eaa2daf]

### System information

w10 64

### Issue description

Inverse lerp returns values higher than 1.
Inverse lerp should return one when "var_test" is > 5
![Captura](https://user-images.githubusercontent.com/19652075/147957466-171e4865-0103-48d0-a50a-087c01f548d0.PNG)

Notice that inverse lerp keeps increasing its return value after exceeding the value of 5
![gif gif](https://user-images.githubusercontent.com/19652075/147957349-c3fce191-be98-40cd-b160-f1c349c7d0c2.gif)

### Steps to reproduce

See the code image

### Minimal reproduction project

[testInverseLerp.zip](https://github.com/godotengine/godot/files/7803044/testInverseLerp.zip)

**Comment by Zylann** [comment]
`inverse_lerp` is the inverse of `lerp`. `lerp(0, 5, 2)` returns more than `5`. So should `inverse_lerp`, isnt it?

**Comment by Torguen** [comment]
> `inverse_lerp` is the inverse of `lerp`. `lerp(0, 5, 2)` returns more than `5`. So should `inverse_lerp`, isnt it?

I'm not sure I understand you.
My knowledge about inverse lerp comes from here:
https://www.gamedev.net/articles/programming/general-and-gameplay-programming/inverse-lerp-a-super-useful-yet-often-overlooked-function-r5230/
It seems that inverse lerp should return a value between 0 and 1, in godot's doc it says a normalized value.
So, well, a normalized value is a value between 0 and 1 I think.

**Comment by Calinou** [comment]
>  It seems that inverse lerp should return a value between 0 and 1, also in godot's doc it says a normalized value.

Lerping can be used to return a value outside of the `0..1` bounds (this is known as extrapolation). Inverse lerping should be able to do that too for consistency's sake. I don't see a point in intentionally limiting its functionality :slightly_smiling_face:
