### ISSUE TITLE
Exclamation point ( ! ) from DroidSans looks strange in output

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#5647]
Ubuntu 14.04 64-bit

```
func _ready():
    print("!")
    print("!!!")
```

![image](https://cloud.githubusercontent.com/assets/4741886/16734341/763678bc-4785-11e6-855e-7bb3f67466c2.png)

**Comment by bojidar-bg** [comment]
Can confirm in the inspector as well.

**Comment by akien-mga** [comment]
Should be fixed for 2.1, it looks too weird :)

**Comment by reduz** [comment]
well, it's the font fault, anyone graphically wise up for some fontforge editing?

**Comment by akien-mga** [comment]
BTW, the Droid Sans font is under the Apache 2.0 license, so if we ever edit it (I guess we already did?), we need to make it crystal clear somewhere that this is not the original version (the Apache 2.0 license is pretty clear about that).

**Comment by reduz** [comment]
I haven't done any editing to it, currently we are using the pristine TTF files, as we implemented fallbacks

**Comment by akien-mga** [comment]
Thanks for the precision :)

**Comment by akien-mga** [comment]
I don't think that it's the font's fault; I don't imagine a font like Google's DroidSans having such a bad rendering for its exclamation mark in 14pt.

Here's a comparison in zoom 100% and 800% of:
- above: a Label using a DynamicFont with our `tools/editor_fonts/DroidSans.ttf` loaded, size 14pt
- below: a Label using the default font
- on the right: the same font (supposedly) in the Output panel (the zoomed version is actually upscaled in GIMP with no interpolation)

Zoom 100%: ![spectacle xv4312](https://cloud.githubusercontent.com/assets/4701338/17062877/04e41832-5035-11e6-89f4-cbbc45bd0057.png) ![spectacle tj4312](https://cloud.githubusercontent.com/assets/4701338/17062943/4b51dd90-5035-11e6-9326-89ab75babf3c.png)

Zoom 800%: 
![spectacle du4312](https://cloud.githubusercontent.com/assets/4701338/17062914/24e2cd54-5035-11e6-938e-4f28471438d3.png)
![spectacle tj4312](https://cloud.githubusercontent.com/assets/4701338/17062994/887ec02a-5035-11e6-8a0d-53b560bf45ed.png)

**Comment by akien-mga** [comment]
Also interesting to note: the font is not rendered the same in LineEdit / TextEdit / Label in the game's viewport (whether in-game or in the 2D viewport) as in the editor's docks:
![spectacle gx4312](https://cloud.githubusercontent.com/assets/4701338/17063235/8e44f730-5036-11e6-9b8b-949d911017b0.png)
![spectacle tj4312](https://cloud.githubusercontent.com/assets/4701338/17062943/4b51dd90-5035-11e6-9326-89ab75babf3c.png)

**Comment by vnen** [comment]
This might be related to #5663.

**Comment by akien-mga** [comment]
As shown by my above screenshots, with FreeType 2.6.5 it looks less ugly, though it's still not perfect. Moving to the 2.2 milestone as it's no longer critical for 2.1 IMO - but we should still investigate the various FreeType options at our disposal to see if this could be improved.

**Comment by bojidar-bg** [comment]
Pretty bump, what's going on with this issue (and is it somehow fixed too)?

**Comment by akien-mga** [comment]
> (and is it somehow fixed too)

Not fixed yet, though it has been worse: ![spectacle x12488](https://cloud.githubusercontent.com/assets/4701338/25775250/d9637e4c-32a0-11e7-8933-b01a9420ac6c.png)

**Comment by volzhs** [comment]
DroidSans
![font_sans](https://user-images.githubusercontent.com/8281454/28769720-97645006-7617-11e7-9f12-93749c20b88b.png)
NotoSans-Regular
![font_noto](https://user-images.githubusercontent.com/8281454/28769722-98fec4f0-7617-11e7-81a1-a6a79745fe06.png)

what about changing default ttf then?

**Comment by reduz** [comment]
noto sans is pretty, but it's huge

**Comment by volzhs** [comment]
@reduz current droidsans.ttf is 190kB and notosans-regular size is 305.9kB.
I think it's still small.

**Comment by volzhs** [comment]
@reduz I meant that I suggested replacing `DroidSans.ttf` only to `NotoSans-Regular.ttf`, not others.

**Comment by reduz** [comment]
you mean mixing them? does that even work? :D

**Comment by volzhs** [comment]
![image](https://user-images.githubusercontent.com/8281454/28777941-2012d146-7638-11e7-93fb-f64594963430.png)

@reduz it seems to work well :)

**Comment by RandomShaper** [comment]
Couldn't that be something tweakable at the FreeType level?

**Comment by Sslaxx** [comment]
Seems a bit over-complex doesn't it?

**Comment by volzhs** [comment]
I'm using 2.1.4 editor with `NotoSans-Regular.ttf` for default font.
Almost everything seems fine but title bar height should be handled in a proper way.

![image](https://user-images.githubusercontent.com/8281454/28923236-4850720a-7898-11e7-985d-46f95614bd58.png)

**Comment by Sslaxx** [comment]
Are you using Intel drivers @volzhs? If so, bear #8902 in mind.

**Comment by volzhs** [comment]
@Sslaxx it's not that case and I'm using GeForce GTX 670 with nvidia-375 driver on ubuntu 16.04.

**Comment by volzhs** [comment]
can this be closed now?

**Comment by reduz** [comment]
\o/

**Comment by bojidar-bg** [comment]
I'd take this as an "yes". Obsoleted by #10690.

**Comment by bojidar-bg** [comment]
Or wait, no. That was PRed to the 2.1 branch.

**Comment by volzhs** [comment]
it's finally closed. :open_mouth:

**Comment by akien-mga** [comment]
Well now fixed for real :)
