### ISSUE TITLE
HTML5 build ignore mouse pos

### ISSUE THREAD

**Issue by alexwbc** [godotengine/godot#565]
When I export this project (  https://mega.co.nz/#!yRgD3K6C!Iufz_NDf_sEFAUI4m0-x4T-joZhvfjWKUaBceOzik30 )) into this html5 build (( https://mega.co.nz/#!uZxxCAaB!n6CJo32dTwPfX9RrKzLlBvfXXUusVTtWWLGnQOQqLxo )) it seems that mouse  pos doesn't work (as well clicking object, even if mouse clicks are correctly processed)

Binary and export template used are the one currently available in the homepage ( June 19, 2014 (1.0devel) )

**Comment by akien-mga** [comment]
Closing as old as the HTML5 exporter has changed a lot in the current master branch, there are still issues but likely this one is fixed or has a different manifestation.
