### ISSUE TITLE
Weird node names when there are duplicates

### ISSUE THREAD

**Issue by NNesh** [godotengine/godot#56508]
### Godot version

4.0 dev (9f05867)

### System information

Linux (Manjaro KDE 21.2.1)

### Issue description

When you add the same node (duplicate) to the scene a node name is weird.
![image](https://user-images.githubusercontent.com/12952093/148184198-52e9fa46-1da1-4e3d-b8bc-d418402178cd.png)
But if I create a duplicate via Ctrl + D the name is well:
![image](https://user-images.githubusercontent.com/12952093/148184321-0b404d3d-f701-439f-8f8c-5566556bfa19.png)

### Steps to reproduce

1. Create a scene
2. Try to add a sub-scene or resource (for example .glb) to the scene twice.
3. Try to create a duplicate via Ctrl+D.

**Comment by KoBeWi** [comment]
This was fixed recently, you have outdated version.

**Comment by NNesh** [comment]
@KoBeWi I've built the last commit (8eb1d20) and I get the same issue.
![image](https://user-images.githubusercontent.com/12952093/148200442-99e3b642-6256-493b-bb6f-4701d9b04d72.png)

**Comment by KoBeWi** [comment]
Weird, this is the PR that was supposed to fix it: #54987

**Comment by NNesh** [comment]
@KoBeWi It happens when I drag and drop a sub-scene or resource to a viewport.
