### ISSUE TITLE
Scene tree is cleared when switching tabs

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#56515]
### Godot version

2c7fcdd

### System information

W10

### Issue description

When you move to another scene tab, the tab you just left is cleared:
![Aalap4bawa](https://user-images.githubusercontent.com/2223172/148215257-2f7a6a4f-f5ec-49ee-93df-a3e07823d7d5.gif)
The nodes are visible on scene, but when you save it and reload, your scene will be lost.

### Steps to reproduce

1. Add some child nodes to a scene
2. Switch to another scene tab
3. Return

**Comment by akien-mga** [comment]
Tested a local revert on a hunch, this was caused by #55512 (@RandomShaper).

**Comment by akien-mga** [comment]
This also affects the `3.x` branch as of 716580bd180002389a8076eceb09ecf5b856a2b1 due to the merge of #55514.

**Comment by RandomShaper** [comment]
I'm trying to fix it. If I don't see a chance to do it quickly, I'll let you know so you can revert.
