### ISSUE TITLE
Better 'or' statement

### ISSUE THREAD

**Issue by mateusak** [godotengine/godot#5651]
I remember seeing this in some other language, don't know where tough. Right now, if we want to test something like this:

```
var a = 1

if (a == 1 or a == 2 or a == 3):
   #do code
```

We need to write it a lot of times.
Well, what about just writing this:

```
var a = 1

if (a == 1, 2, 3):
   #do code
```

It's specially useful when testing against variables with long names or multi-dimensional arrays:

```
if (Arr[y + 1][x] == 1 or Arr[y + 1][x] == 2 or Arr[y + 1][x] == 3):
   #do code 

if (Arr[y + 1][x] == 1, 2, 3):
   #do code 
```
So, what about having this in GDScript? Would be a nice addition.

**Comment by alketii** [comment]
You can do
```
if a in range(1,5):
    pass
```

**Comment by mateusak** [comment]
GDScript is always better than I thought.

**Comment by mateusak** [comment]
But can range be used like an array?

```
if (a == 1, 4, 5):
   pass
```

**Comment by alketii** [comment]
@mateusak 

```
if a in [1,2,3,4,5]:
    pass
```

**Comment by mateusak** [comment]
Okay, thanks.

**Comment by akien-mga** [comment]
It would btw also work with more complex types:
```
var a = get_node("sword")
if a in ["hello", get_node("sword"), 42.0]:
   print("We get signal!")

**Comment by mateusak** [comment]
You guys did an awesome job with it.

**Comment by Zylann** [comment]
I see two side effects of using an array (unless GDScripts does a trick): 
- It allocates memory for each comparison
- All elements have to be evaluated before executing the 'in'. using 'or' can skip further comparisons.
So better use 'or' IMO, or put things in a variable before.
