### ISSUE TITLE
Surface tool is exponentially slower when threaded

### ISSUE THREAD

**Issue by DataPlusProgram** [godotengine/godot#56524]
### Godot version

3.4.2.stable

### System information

Windows 10, GLES3, Radeon 5700xt, R7 5800

### Issue description

Fast performance with no threading:
![noThread](https://user-images.githubusercontent.com/62811101/148236408-ffbe9422-febd-4adf-b69b-bdf39c49d5fa.gif)

Slow performance with threading:
![withThread](https://user-images.githubusercontent.com/62811101/148236421-64faf76b-ff70-44cd-91f2-46f0ac27ee46.gif)

### Steps to reproduce

I am aware of https://github.com/godotengine/godot/issues/51311 but the difference here is that `SurfaceTool.append_from()` is not being invoked.

Here is how the code is laid out

```
var surf = SurfaceTool.new()
var mesh = Mesh.new()

surf.begin(Mesh.PRIMITIVE_TRIANGLES)

	surf.set_material(mat)
		
	
	surf.add_normal(normal)
	surf.add_uv(Vector2(startUVx,startUVy))
	surf.add_vertex(TL)
	
	surf.add_normal(normal)
	surf.add_uv((Vector2(endUVx,startUVy)))
	surf.add_vertex(TR)
	
	surf.add_normal(normal)
	surf.add_uv(Vector2(endUVx,endUVy))
	surf.add_vertex(BR)
	
	
	surf.add_normal(normal)
	surf.add_uv(Vector2(startUVx,startUVy))
	surf.add_vertex(TL)
	
	surf.add_normal(normal)
	surf.add_uv(Vector2(endUVx,endUVy))
	surf.add_vertex(BR)
	
	surf.add_normal(normal)
	surf.add_uv(Vector2(startUVx,endUVy))
	surf.add_vertex(BL)
	
	
	surf.commit(mesh)
```

**Comment by Zylann** [comment]
Is the slowdown around `commit()`, by any chance?

**Comment by Zireael07** [comment]
OpenGL shaders don't play nice with threads...

**Comment by Calinou** [comment]
> OpenGL shaders don't play nice with threads...

SurfaceTool runs on the CPU, but the mesh needs to be uploaded on the CPU. There is no shader compilation involved here.

**Comment by DataPlusProgram** [comment]
I went an checked the time taken for each function individually and in a funny twist of fate it was everything but the surface tool that was causing the slowdown.

The 2 functions causing the slowdown are `create_trimesh_collision` and `lightmap_unwrap`
Here's the numbers:

**Comment by Zylann** [comment]
> The 2 functions causing the slowdown are create_trimesh_collision

> physics isnt thread-safe yet AFAIK

**Comment by Calinou** [comment]
Can you use threads for mesh generation, but go back to a single thread (that waits for multiple threads) to generate the trimesh collision?

**Comment by DataPlusProgram** [comment]
Originally I made it threaded because the editor's importing functionality isn't exposed to GDScript so I have to create a thread and wait for the editor to import each file (generation of .stex, .md5, etc..) on its own time.

Although it's not really a trivial fix I think I can rewrite the plugin-in such way that it does a threaded pre-pass importing of resources and after that it will be free to generate meshes in a non-threaded environment.

**Comment by fire** [comment]
I've noticed that sometimes the threaded mode is really threaded in my tests. I got blocked so I moved on.

**Comment by Scony** [comment]
Can someone spare a minimal reproduction project? I'd like to take a look as I suspect this one is a synchronization problem just like #57148

**Comment by clayjohn** [comment]
You can probably use the MRP here https://github.com/godotengine/godot/issues/51311#issuecomment-894250114

**Comment by Scony** [comment]
@DataPlusProgram you can see my comment regarding slowdown coming from synchronization on `VisualServer` level: https://github.com/godotengine/godot/issues/51311#issuecomment-1024966544

For your case, creating mesh `var mesh = Mesh.new()` (and adding it to the scene tree), handling that mesh, and altering mesh `surf.commit(mesh)` takes a lot of time when done on thread.

IMO, you should limit implementation running on the thread to creating `SurfaceTool` instances (with `SurfaceTool.new()`), filling them (using `surf.add_` functions), and storing `SurfaceTool` instances in the array.

Once this is done, you should do the remaining stuff in the main thread (without extra thread). So you'd just have to iterate over that stored `SurfaceTool` instances in the array and for each of those create a new Mesh instance and commit the surface tool's calculated surface to it.

**Comment by pseidemann** [comment]
hi all,

do I understand correctly that the issue is that only `commit()` is slow in a separate thread?

I ran into the same issue and also found out that MeshDataTool's surface read/write methods are also extremely slow in a separate `Thread`.

is there any good solution to this problem today in 3.5?

**Comment by Calinou** [comment]
> edit: shouldn't this issue get the bug label instead of discussion?

It may be an engine limitation that can't be lifted, and can only be documented, especially in 3.x.

**Comment by pseidemann** [comment]
thanks for the feedback @Calinou.

does this mean there might be improvements regarding this issue in godot 4?

**Comment by Calinou** [comment]
> does this mean there might be improvements regarding this issue in godot 4?

I'd suggest trying the same code in 4.0 and see if it runs any better.

**Comment by pseidemann** [comment]
amazing, so we might see improvement in 3.6 already. thanks!
