### ISSUE TITLE
Building with builtin_wslay=no fails

### ISSUE THREAD

**Issue by madmiraal** [godotengine/godot#56526]
### Godot version

3.x (22a7e6b120) and master (dcb1b8247f)

### System information

Ubuntu 21.10

### Issue description

Trying to build Godot without the builtin WebSockets library (using the shared `libwlay-dev` instead) fails with:
```
Package libwslay was not found in the pkg-config search path.
Perhaps you should add the directory containing `libwslay.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libwslay' found
OSError: 'pkg-config libwslay --cflags --libs' exited 1:
  File ".../godot/SConstruct", line 421:
    detect.configure(env)
  File ".../godot/./platform/linuxbsd/detect.py", line 321:
    env.ParseConfig("pkg-config libwslay --cflags --libs")
  File "/usr/lib/python3/dist-packages/SCons/Environment.py", line 1612:
    return function(self, self.backtick(command))
  File "/usr/lib/python3/dist-packages/SCons/Environment.py", line 599:
    raise OSError("'%s' exited %d" % (command, status))

```
Building without other builtin libraries and using shared libraries instead works fine.

It appears as if (at least on Ubuntu 21.10) that the `libwslay-dev` library is missing its `.pc` file.

### Steps to reproduce

Run `scons builtin_wslay=no`

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
> It appears as if (at least on Ubuntu 21.10) that the libwslay-dev library is missing its .pc file.

I guess we can hardcode the usual lib name and include path until all distros provide the plgconfig file.

**Comment by madmiraal** [comment]
Since `wslay` does have a [`libwslay.pc`](https://github.com/tatsuhiro-t/wslay/blob/master/lib/libwslay.pc.in) file; this option is mainly used by distribution package maintainers; and this is a distribution packaging issue, then I think we can simply use #56532 to automatically fallback to the builtin version when it's missing and leave it to the distribution to fix.

**Comment by akien-mga** [comment]
This works for me on Mageia, it's indeed a distro packaging issue, so closing. #56532 would make this more flexible though.
