### ISSUE TITLE
Sprites rendering bugs with high physics fps

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#5652]
With physics fps set to ~200 and 60 fps lock some rendering problems appear. For example, screen flashing wtih a lot of sprites on scene.
Tested on Linux, latest Godot build from github.

**Comment by SuperUserNameMan** [comment]
@zerornull  : what do you call "screen flashing" ?
Also, if your CPU is not strong enough, 200fps for the physics might be too much computations per seconds, and might lead to strange bottleneck issue that will affect the rendering frame rate.
Could you provide a minimal scene project showing this issue and tell us what is your CPU and GPU ?

**Comment by hanst99** [comment]
@zerornull You shouldn't have problems like that if your objects are moving at sane speeds compared to their size. In most commercial games, physics run at 30-60 fps. You only get issues like that if you have tiny objects moving very quickly, in which case you should use sweeping collision detection.

**Comment by abitofbyte** [comment]
The situation is slightly better with use_vsync instead of target_fps parameter, but sprites flickering still exists.

**Comment by bojidar-bg** [comment]
@abitofbyte Can you share GPU specs with us? It sounds like it might be the result of a poor GPU or driver. Also, can you make an example project exhibiting the issue so we can confirm and/or debug it?

**Comment by abitofbyte** [comment]
@bojidar-bg Here are my GPU specs: http://ark.intel.com/products/75027/Intel-Core-i5-4200H-Processor-3M-Cache-up-to-3_40-GHz . I've tested everything on two different devices, the results were same. Also issue appears only in fullscreen mode. Here's an example project: https://www.dropbox.com/s/yg43fdrpamo5njp/Flickering%20Test.zip?dl=0

**Comment by bojidar-bg** [comment]
Ok, closing this one then..
