### ISSUE TITLE
Theme resource / Window Dialog class / Content Margin properties have no effect

### ISSUE THREAD

**Issue by andrea-calligaris** [godotengine/godot#56521]
### Godot version

3.3.4.stable

### System information

Ubuntu

### Issue description

The _Content Margin_ properties in the _Window Dialog_ class of a _Theme_ resource have no effect.

### Steps to reproduce

* Assign a _Theme_ resource to a _Dialog_.
* Edit the Theme resource, adding the `Window Dialog` class to customize the Dialog appearance as you like.
* Notice immediate changes with most parameters.
* However, change `Content Margin`'s values
* See no effect

### Minimal reproduction project

[DialogContentMarginBug.zip](https://github.com/godotengine/godot/files/7815402/DialogContentMarginBug.zip)

**Comment by Calinou** [comment]
> 3.3.4.stable

Please upgrade to 3.4.2 and test this again, as the theme editor has been reworked significantly in 3.4.
