### ISSUE TITLE
DisplayServer: Godot fails to create floating Windows

### ISSUE THREAD

**Issue by Capital-EX** [godotengine/godot#56536]
### Godot version

v4.0.dev (2022/01/05)

### System information

Manjaro 12.2 Xfce4, NVIDIA GeForce GTX 1070 Ti, Vulkan API 1.2.200

### Issue description

When attempting to use the latest build of Godot 4.0, Godot will not be able to create any windows on my system. Attempting to create a floating docker result in the docker just disappearing. Attempting to create a `Window` node result in the following:
![image](https://user-images.githubusercontent.com/13488718/148303095-09c3ae4e-aa31-4500-9663-3913ee9e7385.png)

Finally, opening the editor settings results in the editor being completely impossible to close.  The only error message produce is the following:
```
drivers/vulkan/rendering_device_vulkan.cpp:8446 - Attempted to free invalid ID: <numbers>
```

However, Godot can successfully create windows while still in the project manager. This is only an issue that affects the editor. Finally, running Godot 4.0 for windows over Wine will correctly create windows:

![image](https://user-images.githubusercontent.com/13488718/148304483-5570b1a9-ec0e-4022-8029-725911b03f05.png)

I am uncertain as to what could be causing this issue.

### Steps to reproduce

1. [Download the current 4.0 testing build of Godot](https://downloads.tuxfamily.org/godotengine/testing/4.0/4.0-dev.20220105/)
1. Run it on Manjaro using Xfce4 with Xfwm4 as the window manager
1. Attempt to float a docker, open editor settings, or use a `Window` node

### Minimal reproduction project

N/A happens with an empty project.

**Comment by Calinou** [comment]
As a workaround, you can start the editor with the `--single-window` command line argument. (Note that if you start the project manager with this, the argument won't be passed over automatically to the editor. Therefore, you have to open a project directly by specifying the path to its `project.godot` file as a positional argument to the Godot binary on the command line.)

**Comment by Capital-EX** [comment]
> As a workaround, you can start the editor with the `--single-window` command line argument. (Note that if you start the project manager with this, the argument won't be passed over automatically to the editor. Therefore, you have to open a project directly by specifying the path to its `project.godot` file as a positional argument to the Godot binary on the [command line](https://docs.godotengine.org/en/stable/getting_started/editor/command_line_tutorial.html).)

The work around seems to fix my issues. Additionally, the Vulkan error message have disappear.

**Comment by akien-mga** [comment]
Can you still reproduce this issue in 4.0 RC 3 or later?

**Comment by Capital-EX** [comment]
Sadly I no longer use this set up after having growing issues with it. I can report this bug no longer happens under KDE on Arch Linux.
