### ISSUE TITLE
Vulkan: Basis Universal assertion failure causes the engine to crash when attempting to display a texture

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#56539]
### Godot version

4.0.dev (8f6cba3a4)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 495.46)

### Issue description

Basis Universal assertion failure causes the engine to crash when attempting to display a texture that uses this compression method. Standard VRAM-compressed textures are not affected.

`gdb` output:

```
godot.linuxbsd.tools.64.llvm: thirdparty/basis_universal/transcoder/basisu_transcoder.cpp:7919: bool basist::basisu_lowlevel_etc1s_transcoder::transcode_slice(void *, uint32_t, uint32_t, const uint8_t *, uint32_t, basist::block_format, uint32_t, bool, const bool, const bool, const uint32_t, const uint32_t, const uint32_t, uint32_t, basist::basisu_transcoder_state *, bool, void *, uint32_t): Assertion `g_transcoder_initialized' failed.

Thread 1 "godot.linuxbsd." received signal SIGABRT, Aborted.
```

### Steps to reproduce

- Create a new project. Drag a texture.
- Select a texture in the FileSystem dock. Go to the Import dock, change the compression mode to **Basis Universal** and click **Reimport**.
- If not done already, double-click the texture to make sure it is previewed in the inspector.
- The editor will crash as soon as it tries to display the full texture (rather than its lossless-compressed thumbnail).

### Minimal reproduction project

[test_basis_universal_crash.zip](https://github.com/godotengine/godot/files/7818672/test_basis_universal_crash.zip)

**Comment by clayjohn** [comment]
I haven't been able to reproduce this in recent builds. Are you still experiencing this crash?

**Comment by Calinou** [comment]
I can no longer reproduce this on 4.0.rc3 after removing `.godot/`, so this appears to be fixed.
