### ISSUE TITLE
Assetlib: unzip project in named folder

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#5654]
As of 31ebac2 it's possible to select a destination to unzip the download template to, so it's great.

What's still missing is that it should IMO create a subfolder in the destination directory before unzipping the contents, especially as the dialog asking for the extract path does not propose to create a new folder itself (and complains if the given path is not a pre-existing directory).

So if I install Minilens in `/home/akien/tmp`, I end up with all the files unzipped directly in `~/tmp`, which can be messy. It should automatically append `/minilens` to the path, create the folder and unzip there.

**Comment by vnen** [comment]
Since the main use is for project templates, I'm not sure about that. I would expect to create my project folder and install the template there, not in a subfolder.

It should add a bit of clarification to where it'll be extracted.

**Comment by akien-mga** [comment]
Then the dialog should allow to create a folder (it's possible already by clicking the "Browse" button, but not by typing the path). It should maybe be made clear that it's the path where the template will be *extracted*, and not *installed*. When *installing* stuff, I'm used to it ensuring that it will be self-contained in a hardcoded subfolder.

**Comment by reduz** [comment]
We could add a "directory is not empty" warning?

**Comment by akien-mga** [comment]
Sounds good to me :)

**Comment by Zylann** [comment]
Should a zipped project be a folder, or the contents of that folder? (I would always do the first so I don't understand the need to have a subfolder actually)

**Comment by vnen** [comment]
> Should a zipped project be a folder, or the contents of that folder?

IINM it's just the contents, since that's the way Godot reads ZIP projects.

**Comment by Zylann** [comment]
So that must be the way users have to zip their project, good to know. I see an `import` button in the AssetLib, but there is no export. Should be nice to be indicated somewhere.

**Comment by akien-mga** [comment]
> We could add a "directory is not empty" warning?

Should be easy to do, tagging as such.

**Comment by bojidar-bg** [comment]
Is this still an issue on master?

**Comment by KoBeWi** [comment]
Godot forces you to unzip into empty folder since 3.0.
