### ISSUE TITLE
No literal brackets in RichTextLabel

### ISSUE THREAD

**Issue by JapanYoshi** [godotengine/godot#56556]
### Godot version

3.4.stable

### System information

Windows 10

### Issue description

There’s no current way to type literal square brackets in a RichTextLabel if it forms a valid BBCode tag.

For example, say I want to display the text “[a][b][c]” in a RichTextLabel with BBCode enabled. However, the RichTextLabel will show “[a]**[c]**” as it interprets the `[b]` as an opening bold tag.

When writing HTML, literal less-thans and greater-thans can be escaped by using `&lt;` and `&gt;`, respectively.

On Multiling O Keyboard, special key types are enclosed in square brackets, and literal brackets can be made with `[LB]` and `[RB]`.

Is there an official, accepted way to type literal square brackets? If so, it should be added to the documentation for BBCode in RichTextLabel. 

Maybe `\u005B` and `\u005D`? I haven’t tried either yet, as I’m away from my PC now, and it’s not included in said documentation.

### Steps to reproduce

1. Create a RichTextLabel.
2. Enable BBCode.
3. Set `bbcode_text` to `[a][b][c]`.

**Comment by dalexeev** [comment]
Now there is only `add_text` method:

```gdscript
rtl.add_text("[a][b][c]") # Adds raw non-BBCode-parsed text to the tag stack.
```

As far as I know, there is no standard for BBCode escape sequence, it is implemented differently everywhere.
I vote for `[lb]`, `[rb]` as there are already `[lrm]`, `[rlm]` and other Unicode control characters.

**Comment by Calinou** [comment]
You can insert a [zero-width space](https://zerowidthspace.me/) after an opening bracket to make sure it is never parsed into a BBCode tag.
