### ISSUE TITLE
Incorrect Label.get_size() value

### ISSUE THREAD

**Issue by pkowal1982** [godotengine/godot#5655]
**Operating system or device - Godot version:**
Windows 7 64b - Godot_v2.0.4.1_stable_win64

**Issue description** (what happened, and what was expected):
Label returns wrong size after setting new text.
Returned size becomes correct on the next frame.
To get the correct size one can remove / add Label to the scene.

**Steps to reproduce:**
Just try to run this code, whole project is in attachment:

```
extends CanvasLayer

var label = Label.new()

func _ready():
    label.set_text("VeryLongOne")
    print(label.get_text(), " ", label.get_size())
    add_child(label)
    print(label.get_text(), " ", label.get_size())
    label.set_text("Short")
    # wrong size
    print(label.get_text(), " ", label.get_size())
    set_process(true)

func _process(delta):
    # right size
    print(label.get_text(), " ", label.get_size())
    set_process(false)
    get_tree().quit()

```

**Link to minimal example project** (optional but very welcome):
Code is in attachment
[label_get_size.zip](https://github.com/godotengine/godot/files/359219/label_get_size.zip)

**Comment by SuperUserNameMan** [comment]
I've found that many canvas items have their size/rect/etc properties updated only at the next frame.

I don't know neither if it is feature or bug.

My workaround is to use a ``yield( get_tree(), "idle_frame");`` between the modification of the canvas and the reading of its modified property.

Though, in certain situation it is not possible to use a ```yield``, so i'm forced to delay the reading to the next frame using a more complicated mechanism.

**Comment by bojidar-bg** [comment]
@SuperUserNameMan BTW, `call_deferred` should work fine in most cases.

**Comment by akien-mga** [comment]
This is still reproducible in 2.1.5 and in the current master branch, but I don't think that it's a bug. As mentioned, such properties are updated based on other nodes in the scene tree and calculated right before the next frame (same as for physics interactions, etc.). It's expected that the information returned by such methods can be delayed by one frame - when you've just set the size, it hasn't been newly computed yet.
