### ISSUE TITLE
Vulkan mobile backend: Reflection Probe Ambient settings don't work

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#56555]
### Godot version

v4.0.dev.20220105.official [8f6cba3a4]

### System information

Windows 11, Vulkan, Nvidia Quadro K2000 472.84

### Issue description

Ambient settings in Reflection Probe have no effect on the scene on the Vulkan Mobile Renderer.

### Steps to reproduce

Create a Reflection Probe
Switch between Disabled and Constant Color (with some color like red set) or Environment -> no changes in lighting
Switch to Vulkan Clustered Renderer
Switch between Disabled and Constant Color or Environment as before -> changes in lighting as expected

### Minimal reproduction project

[Bug.zip](https://github.com/godotengine/godot/files/7821344/Bug.zip)

**Comment by Calinou** [comment]
I can confirm this on `master` 8f6cba3a4.

**Comment by akien-mga** [comment]
Fixed by #58779.
