### ISSUE TITLE
Godot freezes if Tab is zero-width

### ISSUE THREAD

**Issue by dalexeev** [godotengine/godot#56564]
### Godot version

v4.0.dev.custom_build [340883636]

### System information

Kubuntu 21.10

### Issue description

https://github.com/godotengine/godot/issues/52262#issuecomment-1002742424

> Seems like it caused by tab size being zero (which is caused by zero space size), and it's stuck here trying to align the line to the tab offset:
> 
> https://github.com/godotengine/godot/blob/9f058674acebf9a7a0704cdbc26dc9f6d853b16e/modules/text_server_adv/text_server_adv.cpp#L3690-L3696

https://github.com/godotengine/godot/issues/52262#issuecomment-1002745492

> A quick fix for a tab issue. But I'm not sure why it's trying to set TextEdit font to the random one when you are opening arbitrary script, there's something else wrong as well.

### Steps to reproduce

1. Load MRP.
2. Try to open `correct.gd`.
3. Try to open `error.gd` (editor freezes).

### Minimal reproduction project

[custom_font_and_gdscript_conflict.zip](https://github.com/godotengine/godot/files/7790184/custom_font_and_gdscript_conflict.zip)

**Comment by bruvzg** [comment]
The issue with bitmap fonts having zero width tab is fixed by #56649. The freeze will be fixed by #56663.
