### ISSUE TITLE
Rigid body abruptly stops when moving along tilemap

### ISSUE THREAD

**Issue by K-e-v-o** [godotengine/godot#56565]
### Godot version

3.3 stable

### System information

Windows 11, Intel(R) Core(TM) i5-2500K CPU @ 3.30 GHz

### Issue description

I made a small 2D platformer with a RigidBody as the player and a tilemap as the floor. After walking around for a while, the RigidBody stops, even though the input is still being acknowledged because the walking animation is still playing.

Please be kind, I started this Godot thing a week ago. ;-;

### Steps to reproduce

Walk around.

### Minimal reproduction project

[platformer.zip](https://github.com/godotengine/godot/files/7823645/platformer.zip)

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/35780 (same cause).

**Comment by Calinou** [comment]
I'm fairly sure this is a duplicate of another issue, but I can't find it right now.

**Comment by Zireael07** [comment]
something something collision edges, maybe?

**Comment by K-e-v-o** [comment]
> something something collision edges, maybe?

They are both completely parallel, if this information is any use to you.

**Comment by K-e-v-o** [comment]
Found the problem. Apparently having a square collision shape is causing the issue. I just changed it to a capsule around the same size. Hooray!
