### ISSUE TITLE
Editor-connected custom signals do not work

### ISSUE THREAD

**Issue by zatherz** [godotengine/godot#5656]
**Operating system or device - Godot version:**
Arch Linux (64 bit)
Godot 2.0.4.1 binary release
Godot 2.1 beta binary release

**Issue description** (what happened, and what was expected):
When connecting a custom signal to a node, the connection is not actually present. It works when the `connect` function is used.

**Steps to reproduce:**
* Open example project.
* Using the GUI, connect the `Ship` node's `_shoot_bullet` signal to the `BulletController` node's `on_shoot_bullet` function.
* Start the project.
* Hold Shift. A lot of lines containing `SHOOT?`, but no lines containing `SHOOT` will appear in the output window, indicating that `on_shoot_bullet` from `BulletController` is not being called.
* Open `Ship`'s script and uncomment line 8.
* Start the project.
* Hold Shift. A lot of lines containing `SHOOT` *and* `SHOOT?` will appear, indicating that `on_shoot_bullet` from `BulletController` is being called.

**Link to minimal example project** (optional but very welcome):
https://ptpb.pw/YfQy.zip

**Edit**: Connecting custom signals works when connecting to the root node of the scene (but still not when connected to other nodes).

**Comment by akien-mga** [comment]
Confirmed in 2.1-beta 20160712 using the above example project and steps to reproduce. Apparently the editor-made connection just won't work.
