### ISSUE TITLE
Can't select ItemList items

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#56570]
### Godot version

393a44b

### System information

W10

### Issue description

I don't know what happened.
![godot windows tools 64_3Jz8y4GkDC](https://user-images.githubusercontent.com/2223172/148444482-26dad71a-490b-4fc4-bcf0-de0187ecc4f4.gif)
Only happens when running project, in editor it's fine. The items emit selected signal, but never actually get selected. Also if you connect the signal and print the selected id, you always get -1 when trying to select with arrows.

### Steps to reproduce

1. Add ItemList
2. Add some items
3. Run
4. Try select

**Comment by zaevi** [comment]
Seems added items are not selectable by default in 4.0.
```GDScript
func _ready():
    for i in range($ItemList.item_count):
        $ItemList.set_item_selectable(i, true)
```
![itemlist](https://user-images.githubusercontent.com/12966814/148527562-9ab876be-cad4-4e32-a73e-02b3722ba5c2.gif)

**Comment by KoBeWi** [comment]
This is caused by #54342. Item's `selectable` is false by default, but `add_item()` method has selectable as true. But the new editor seems to not use `add_item()`, hence the internal default is used.

We should make Item's `selectable` true by default and expose this property in the editor.
