### ISSUE TITLE
Memory Leak when function returning self type is defined in class

### ISSUE THREAD

**Issue by AsherGlick** [godotengine/godot#56576]
### Godot version

v4.0.dev.20220105.official [8f6cba3a4]

### System information

Ubuntu 20.04

### Issue description

When a class contains a function with the return type of itself, some memory is leaked. This occurs even if the function is not called so long as it is defined and the script is loaded. This only occurs when the return type is specified.

Example:
```
class MyTypedClass:
	func get_self() -> MyTypedClass:
		return self
```

### Steps to reproduce

* Create a class, either with `class_name` or via an internal class declaration
* Create a function within that class which has a typed return value of the class
* Run the project via the command line argument `godot --path ./path/to/project`
* Exit the godot application
* See the output message
```
ERROR: Condition "_first != nullptr" is true.
   at: ~List (./core/templates/self_list.h:106)
ERROR: Condition "_first != nullptr" is true.
   at: ~List (./core/templates/self_list.h:106)
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: cleanup (core/object/object.cpp:2025)
ERROR: Resources still in use at exit (run with --verbose for details).
   at: clear (core/io/resource.cpp:459)
```

### Minimal reproduction project

[Godot 4.0 Dev Return Self Memory Leak.zip](https://github.com/godotengine/godot/files/7824789/Godot.4.0.Dev.Return.Self.Memory.Leak.zip)

**Comment by AsherGlick** [comment]
This appears to still be an issue in v4.0.dev.20220118.official [bc5ba38ff]

When running the examples against [609964848d] it appears that memory still leaks when a class has a function that returns itself.

Perhaps there are multiple places where this fix needs to be applied?

**Comment by rcorre** [comment]
This is also an issue in 3.5.1. The self reference does not have to be a return value either. The following script will leak:

```
extends Spatial
class_name Thing

func _ready():
	var t := get_node(".") as Thing
	print(t)
```

```
CORE API HASH: 6609155589855387091
EDITOR API HASH: 17280644357449250417
Loading resource: res://default_env.tres
Loaded builtin certs
Loading resource: res://Spatial.tscn
Loading resource: res://Thing.gd
Spatial:[Spatial:1258]
ERROR: Condition "_first != nullptr" is true.
   at: ~List (./core/self_list.h:108)
ERROR: Condition "_first != nullptr" is true.
   at: ~List (./core/self_list.h:108)
PulseAudio: context terminated
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: cleanup (core/object.cpp:2070)
Leaked instance: GDScriptNativeClass:792
Leaked instance: GDScript:1255 - Resource path: res://Thing.gd
Hint: Leaked instances typically happen when nodes are removed from the scene tree (with `remove_child()`) but not freed (with `free()` or `queue_free()`).
ERROR: Resources still in use at exit (run with --verbose for details).
   at: clear (core/resource.cpp:417)
Resource still in use: res://Thing.gd (GDScript)
Orphan StringName: get_node
Orphan StringName: res://Thing.gd
Orphan StringName: GDScriptNativeClass
Orphan StringName: Spatial
Orphan StringName: _init
Orphan StringName: _ready
Orphan StringName: GDScript
StringName: 7 unclaimed string names at exit.
```

**Comment by MikeSchulze** [comment]
i guess this ticket can be closed, i try to reproduce on v4.0.2.stable.official [7a0977ce2] and no orphan resource is detected

**Comment by YuriSizov** [comment]
@MikeSchulze You say you cannot reproduce it, but you also link here from https://github.com/MikeSchulze/gdUnit4/issues/144. So what's the latest on this?

**Comment by MikeSchulze** [comment]
Hi @YuriSizov i have to verify my bug issue, is long time ago and is planed to review before release GdUnit4 v4.2.0 ;)
I will give you feedback tomorrow.

**Comment by YuriSizov** [comment]
Thanks a lot!
