### ISSUE TITLE
Clipping doesn't work off-screen

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#56579]
### Godot version

393a44b

### System information

W10

### Issue description

When you have e.g. a scroll container, it will stop clipping its children when it goes off-screen.
![godot windows tools 64_s6jEldtRYa](https://user-images.githubusercontent.com/2223172/148467824-5d9823a4-7191-4921-96e6-cbd45ee38a1e.gif)
Doesn't seem related to #36164 and doesn't happen in 3.x

### Steps to reproduce

1. Add a ScrollContainer
2. Add some control (e.g. Panel) with a very big minimum size, e.g. 1000000000
3. Pan the view so that ScrollContainer is outside the viewport

**Comment by souplamp** [comment]
Here is an MIP to test (Godot 4.0 alpha4): [Scroll.zip](https://github.com/godotengine/godot/files/8458097/Scroll.zip)

From what I've seen (and what's included in the MIP), this only happens _below_ a ScrollContainer when panning in the editor, and it only happens _above_ a ScrollContainer when panning a camera while play-testing.
