### ISSUE TITLE
All project settings and editor settings are marked as reversible, despite not being modified from their default values

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#56571]
### Godot version

4.0.dev (393a44b27). This does not occur in 4.0.dev (8f6cba3a4)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 495.46)

### Issue description

All project settings and editor settings can be reverted to their default value, despite not being modified from their default values:

![image](https://user-images.githubusercontent.com/180032/148444791-cd8c18a0-370a-4747-8d8f-1336c1b29e06.png)

Clicking the revert button once on a *modified* value will revert to the property's default value, but the revert icon will remain visible. Clicking the revert button a second time seems to pick the lowest possible value (e.g. first value of an enum), even if it is not actually the default value. For instance, reverting the Depth of Field Bokeh Shape setting will revert to **Box**, despite the default being **Hexagon**.

This does not affect the inspector.

### Steps to reproduce

- Open the Project Settings or Editor Settings in any project.

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
Probably a regression from #56176, CC @RandomShaper.
