### ISSUE TITLE
`auto_brace_complete` does not wrap selected text with the desired characters anymore (unlike `3.x`)

### ISSUE THREAD

**Issue by BeayemX** [godotengine/godot#56581]
### Godot version

v4.0.dev.custom_build [897afb69a]

### System information

Linux Mint - Vulkan API 1.2.131 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1080

### Issue description

When trying to wrap selected text in quotes or parenthesis (or any other character of that nature) it will not wrap the selected text in the desired characters but instead replace the selected text with the pressed character.

This behavior occurs regardless of the value of the editor setting `auto_brace_complete`.

![image](https://user-images.githubusercontent.com/3453076/148484312-4569317c-6d30-45bb-91de-2cdb84cc75a5.png)

### Steps to reproduce

1. Select any text in the code editor
2. Press `(`

**Comment by theoniko** [comment]
Hello @Chaosus ,
Could you please give more details i.e. which files are relevant?

**Comment by jmb462** [comment]
> When trying to wrap selected text in quotes or parenthesis (or any other character of that nature) it will not wrap the selected text in the desired characters but instead replace the selected text with the pressed character.

Isn't the expected behaviour ?

auto_brace_complete should do more than adding a closing brace when typing an opening one ?

**Comment by BeayemX** [comment]
At least in Godot 3 `auto_brace_complete` is responsible for toggling the behavior as I described it.  
Therefore I would say it is a regression.

**Comment by jmb462** [comment]
> At least in Godot 3 `auto_brace_complete` is responsible for toggling the behavior as I described it. Therefore I would say it is a regression.

Thanks, I was ignoring this feature.
