### ISSUE TITLE
LineEdit using Center and Right align gives unexpected results when the text is wider than the control

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#5658]
**Issue description**:
Using center and right align in a `LineEdit` does weird things, when the text is wider than the control. for example some text is draw outside the area of the widget and cursor don't work properly. Using left and fill align the control works normally, and all align types works properly when the text width is smaller than the total width.

![line-edit-align](https://cloud.githubusercontent.com/assets/8458222/16775455/1536f084-4837-11e6-8314-65b53545c86a.png)

**Link to minimal example project**:
[line_edit_align.zip](https://github.com/godotengine/godot/files/359854/line_edit_align.zip)

**Comment by neikeq** [comment]
Ping @SaracenOne who added alignment to LineEdit. Relevant commits: 0006f03 and e3c50ac

**Comment by SaracenOne** [comment]
Hmm...I'll try to look into it when I get a chance.

**Comment by allkhor** [comment]
Align text in a placeholder has strange behaviour, see  example below on a udp chat demo:

![line_edit_bug](https://cloud.githubusercontent.com/assets/1049442/17114132/6c7f4e3e-52cf-11e6-8537-6b014435e864.gif)

Step to reproduce: 
1) Open a udp chat demo, enter some text in placeholder and align to center or right.

**Comment by volzhs** [comment]
![lineedit](https://cloud.githubusercontent.com/assets/8281454/20597650/42487168-b288-11e6-8d09-45b67e902306.gif)

last character is hidden with align right also.

**Comment by hubbyist** [comment]
seems as if #4992 is happening again.

**Comment by Shin-NiL** [comment]
I can confirm that all of the above related issues still present on 2.1.3-stable.

**Comment by magyar123** [comment]
Same here. Centering would be important for me so I'll try to fix this today

**Comment by toger5** [comment]
It is really easy to forget they sb margins for text alignment.
Just for future errors like that it is often helpful to check if it works with a flat style box (no margins) and see if it still behaves wrong. If it is fixed this information is really helpful for the one who fixes it since he can look out for missing stylebox positioning/sizing.

**Comment by KoBeWi** [comment]
Fixed since 3.0
