### ISSUE TITLE
Unclear await related String crash using global signals in 4.0 release builds

### ISSUE THREAD

**Issue by gokiburikin** [godotengine/godot#56587]
### Godot version

v4.0.dev.20211210.official [21b81998b]

### System information

Windows 10

### Issue description

Unfortunately I don't really understand what is going wrong. When using `await` to push returned text into a `RichTextLabel` on specifically global (AutoLoad) signals and only on release builds, it produces unexpected output and/or crashes. The actual issue is probably less specific, but changing the signals to be local to the file, not printing the results somewhere, or not getting the results at all do not (seem to) crash.

Seems like some kind of pointer issue based on the results. Sometimes it simply crashes, sometimes the print produces invalid characters, and sometimes the error output displays messages like this: `Unicode parsing error: Invalid unicode codepoint 2ed168b0.`

For what it's worth, I have not tried building the exact same version with the debug / release flags on. I have only tested nightlies and pre-alphas released by akien and hugo (listed below.)

I can attempt to provide more information if necessary.

### Steps to reproduce

Open the attached MRP in different 4.0 pre-alpha builds and play the default scene. It ~~works~~ **crashes** in every "release" build I've tested (released by akien on the subreddit) and ~~crashes~~ **works** in each "nightly" i've tested (released by hugo on the unofficial nightly builds website.) I assume the difference between these builds is release vs debug based on their executable size (~100mb vs ~700mb.)

It has crashed (or has unexpected behaviour) in these versions:
v4.0.dev.20211210.official [21b81998b]
v4.0.dev.20220105.official [8f6cba3a4]

And doesn't crash in these versions:
v4.0.dev.calinou [e885de050]
v4.0.dev.calinou [092a28612]

### Minimal reproduction project

[await-crash-mrp.zip](https://github.com/godotengine/godot/files/7827834/await-crash-mrp.zip)

**Comment by akien-mga** [comment]
Thanks for the report! It seems to be the same issue as #57126, so I'm consolidating all reports in the same place.
