### ISSUE TITLE
Vulkan Clustered Renderer: Omni/Spot Lights vanishing

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#56591]
### Godot version

v4.0.dev.20220105.official [8f6cba3a4]

### System information

Windows 11, Vulkan, Nvidia Quadro K2000 472.84

### Issue description

Omni and Spot Lights start vanishing when there are too many lights on screen (specifically over Max Clustered Elements) regardless of which Cluster they're a part of on screen. 

This might be intentional behavior but it is unclear if it is per cluster or entire screen limit. If it is intended to be a limit for the entire screen this is intentional, else it's a bug.

### Steps to reproduce

Create more lights of a single type than the Max Clustered Elements setting under Limits, and spread them out over a surface, so that they aren't all in a single cluster.

### Minimal reproduction project

[Bug.zip](https://github.com/godotengine/godot/files/7828914/Bug.zip)

**Comment by clayjohn** [comment]
``rendering/limits/cluster_builder/max_clustered_elements`` is a per scene limit. Not a per cluster limit. The documentation should be updated to reflect this
