### ISSUE TITLE
Signal connecting menu should let you double click on a node to connect

### ISSUE THREAD

**Issue by zatherz** [godotengine/godot#5659]
Currently, the node connecting dialog (where you select the name of the function, whether to make it automatically etc.) requires you to select the node, then press the `Connect` button to connect. For ease of use it'd be great to be able to connect by just double clicking on the node.

**Comment by neikeq** [comment]
Do you mean displaying the dialog by double clicking?
Also keep in mind the connections dialog was transformed into a dock in the 2.1 branch.

**Comment by zatherz** [comment]
I don't mean the dock. I mean the dialog that opens after you select a signal in the dock.

**Comment by neikeq** [comment]
Oh, then it was already implemented by 1088180 :)

**Comment by zatherz** [comment]
I tried the 2.1 beta binaries and this feature didn't exist there. I guess the binary was made before that commit?

**Comment by vnen** [comment]
The beta is currently the tip of master, so this feature is there, unless we misunderstood something.

**Comment by neikeq** [comment]
Could it be that you mean double clicking an existing connection to edit it? (rather than double clicking the signal to create a new connection, which is what I understood)

**Comment by akien-mga** [comment]
I think OP wants to be able to connect a signal to a node by double clicking its name in this windows:
![spectacle qb6537](https://cloud.githubusercontent.com/assets/4701338/16785631/5fec43b0-488f-11e6-9bbd-ef88b538068e.png)

i.e. here double-clicking "Ship" should have the same behaviour as clicking "Connect".

**Comment by zatherz** [comment]
Yes, sorry for my inability to properly express that.
