### ISSUE TITLE
rpc() requires the use of StringName

### ISSUE THREAD

**Issue by Vikfr0** [godotengine/godot#56595]
### Godot version

4.0dev 91b97dac0

### System information

Windows 11

### Issue description

I find it weird I have to use StringName explicitly to call `rpc()`. I get a runtime error `Cannot convert argument 1 from String to StringName` when I try to. 

For example `connect()` does not need me to construct a StringName explicitly, though the signal parameter is a StringName. 

### Steps to reproduce

Write something like `rpc("wololo_method")`
Run the script and get `Cannot convert argument 1 from String to StringName` error

**Comment by Calinou** [comment]
cc @Faless

**Comment by mhilbrunner** [comment]
Somewhat adjacent: https://github.com/godotengine/godot/pull/53704 may solve this inadvertantly if we merge that and move away from strings for RPCs at all.

**Comment by sainthDE** [comment]
Since after the modifications to the RPCs, generally all functions annotated with @rpc must be present in the respective scripts on both the client and server side, and #53704 is also merged in the meantime, I interpret it such that the syntax added by this is now the desired way. I like the change as I no longer have to rely on strings.

server side script:
```GDScript
extends Node

func _ready():
	var peer = ENetMultiplayerPeer.new()
	peer.create_server(4343)
	get_multiplayer().multiplayer_peer = peer

@rpc(any_peer)
func say(msg):
	print("%d says %s" % [get_multiplayer().get_remote_sender_id(), msg])
```

client side script:
```GDScript
extends Node

func _ready():
	var peer = ENetMultiplayerPeer.new()
	peer.create_client("127.0.0.1", 4343)
	get_multiplayer().multiplayer_peer = peer
	network.connection_succeeded.connect(_on_connection_succeeded)

func _on_connection_succeeded() -> void:
	say.rpc_id(1, "hello")

@rpc(any_peer)
func say(_msg):
	pass # server side
```
