### ISSUE TITLE
AnimationPlayer.stop(true) doesn't reset animation [4.0]

### ISSUE THREAD

**Issue by ccuntd** [godotengine/godot#56605]
### Godot version

v4.0.dev.custom_build [c09c4e015]

### System information

Linux, Vulkan

### Issue description

The Animation doesn't reset when told to on stop()

### Steps to reproduce

AnimationPlayer.Stop()

**Comment by Calinou** [comment]
@ccuntd Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by ccuntd** [comment]
[AnimationBug.zip](https://github.com/godotengine/godot/files/7831723/AnimationBug.zip)

**Comment by KoBeWi** [comment]
Duplicate of #27499

**Comment by ccuntd** [comment]
whoa 2019, this old
