### ISSUE TITLE
TextEdit caret is drawn at an incorrect X offset with a custom font

### ISSUE THREAD

**Issue by ccuntd** [godotengine/godot#56607]
### Godot version

v4.0.dev.custom_build [c09c4e015]

### System information

Linux, Vulkan

### Issue description

![image](https://user-images.githubusercontent.com/85245131/148617944-eae3f47f-8bfa-4f81-a063-35d3da3c4e37.png)
it's inside "w"

### Steps to reproduce

yeye

### Minimal reproduction project

here's the fonr
![Perfect DOS VGA 437 ttf](https://user-images.githubusercontent.com/85245131/148618122-5bdc92a2-b65a-40b5-bcb8-e6468355f661.png)

(remove the `.png`, i had to put i there because github said "unsupported filetype")

**Comment by Calinou** [comment]
@ccuntd Can you reproduce this on 3.4.2?

Also, which font size are you using?

**Comment by ccuntd** [comment]
13 is my font size

**Comment by ccuntd** [comment]
3.4.2 is not bugged

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by cdemirer** [comment]
Might be related in some way:  #55996

**Comment by ccuntd** [comment]
probably same
