### ISSUE TITLE
move_and_slide_with_snap will let player glitch into one-way collision slope tile occasionally

### ISSUE THREAD

**Issue by yikescloud** [godotengine/godot#56616]
### Godot version

3.4.2 stable

### System information

windows 10

### Issue description

If you make a one one collision slope tile, and let your player move with snap,  and if you turn your player just at the border between tiles(keep press "A" and "D" on slope), the player will glitch into the slope.
Just like this
![image](https://user-images.githubusercontent.com/9168814/148637360-397030a1-3672-473e-bf86-5ce932e51929.png)

### Steps to reproduce

1.Make a tilemap with a one way collision tile
2.Make a kinematicbody2d player
3.let player move_and_slide_with_snap
4.Play your game, and keep press left and right when player on the slope

### Minimal reproduction project

[OneWaySlopeBug.zip](https://github.com/godotengine/godot/files/7832895/OneWaySlopeBug.zip)

**Comment by timothyqiu** [comment]
See also: #42916

**Comment by yikescloud** [comment]
![image](https://user-images.githubusercontent.com/9168814/148640104-86d60d70-35db-4ce1-ae64-9fd6b2352661.png)
increase collision margin can fix the problem
