### ISSUE TITLE
Set font size at runtime

### ISSUE THREAD

**Issue by radubolovan** [godotengine/godot#5661]
**Operating system or device - Godot version:**
All systems - all versions

**Issue description** (what happened, and what was expected):
Is it possible to resize the font size at runtime for future godot versions?
I want to optimize the maximum resources used in a project / game. Therefore I want to use a maximum of 3 fonts. But I also want to use these fonts for different sizes: 12, 14, 16, 18, etc. In my opinion is nonsense to import a single font several times to use different sizes. Let me show you a simple example: having 3 fonts and using each at least 5 sizes it means 15 resources ("fnt" files). It's too much. Too much memory "eaten" by something that could be easier managed.

Suggestion:
When importing a font (ttf, etc), make a texture out of it by a size and let the game designer to choose what should be the best "pixel perfect" look like. And also let the programmer to optimize the resources he uses.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by neikeq** [comment]
DynamicFont are already working in the current master branch. You will be able to use it when 2.1 is released :) (or by building from source)

Closing as already implemented.

**Comment by radubolovan** [comment]
This is great news! :)
Is there any documentation about this?
