### ISSUE TITLE
The code editor looks blurry in 2.1 compared to 2.0

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#5663]
When switching to Godot 2.1 I experienced a small discomfort when using the code editor, because text looks more fuzzy than in 2.0.
This is not a big deal, but when 90% of the time your work is basically looking a text you start to notice even the slightest change.

Take a look at those screenshots taken at the exact same font size, and you should notice that in 2.1 the bars of the letters tend more to span across 2 pixels and look more blurry.
![blurry_text_2](https://cloud.githubusercontent.com/assets/1311555/16787093/d6c987b8-4899-11e6-9057-dce502c7d709.png)
![blurry_text_1](https://cloud.githubusercontent.com/assets/1311555/16787092/d45f64f2-4899-11e6-8931-d339aa80983f.png)

In case it's not clear, I also made a Godot project to compare them by alternating the two superimposed screenshots:
[CompareImages.zip](https://github.com/godotengine/godot/files/360435/CompareImages.zip)

I'm not asking for cleartype subpixel rendering & the like, but is it possible to improve the quality like in 2.0?

**Comment by Calinou** [comment]
Right now, I don't think the Freetype anti-aliasing type can be changed by the user, in both the editor and projects.

**Comment by Zylann** [comment]
Actually, turning off anti-alias would be worse. Something might have changed in the way characters are smoothed / sized.

**Comment by reduz** [comment]
The original font was created with BMFont on Windows a long time ago. Right
now it's using FreeType. I can imagine there are differences, but I'm
afraid not much can be done..

**Comment by Zylann** [comment]
It looks like the characters are not grid-fitted before being smoothed: https://www.freetype.org/autohinting/background.html
I found there are options for this according to this tutorial https://www.freetype.org/freetype2/docs/tutorial/step2.html

**Comment by reduz** [comment]
the characters are grid fitted, if they were not it would look a lot
blurrier.
I have checked all the flags available when loading and rendering the
characters and, honestly, can't find anything relevant.
In fact, I forced the autohinter because it looks less blurry this way

Again, I think this is mainly due to the difference between Freetype and
ClearType

**Comment by Zylann** [comment]
I don't see a trace of ClearType in 2.0 (colors would be slightly different), it just looks like the bars fit the grid nicely. I might investigate this to see if I can get the same results.

Anyways it's a minor issue, I believe there is more important bugs to fix before :)

**Comment by akien-mga** [comment]
Is this old bug still valid? :)

**Comment by Zylann** [comment]
Probably not. Subpixel AA would be needed to have better crisp fonts anyways, but the issue was about a slight "regression" between versions.
