### ISSUE TITLE
Vulkan: 3D environment lighting from background clear color/custom color is too dark

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#56634]
### Godot version

4.0.dev (8f6cba3a4)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 495.46)

### Issue description

3D environment lighting from background clear color/custom color is too dark compared to the sky itself. In `3.x`, objects would have the exact same color as the background, regardless of whether GLES3 or GLES2 is used.

Default clear color:

![2022-01-08_23 47 21](https://user-images.githubusercontent.com/180032/148662454-82315c60-0cd7-4839-be71-fbb1725d70c4.png)

Custom ambient color set to `#ff0000`:

![2022-01-08_23 47 31](https://user-images.githubusercontent.com/180032/148662456-eccdbd22-eaf4-4b39-8b84-cd32564f0c65.png)

Setting the ambient light energy to 2.1 fixes the discrepancy between the background and objects, so I presume this is a sRGB -> linear conversion issue:

![2022-01-08_23 47 49](https://user-images.githubusercontent.com/180032/148662457-756770fb-f698-4a5e-bb12-89acc09508a9.png)

### Steps to reproduce

- Add a MeshInstance3D node with a primitive mesh.
- Add a DirectionalLight3D node then hide it, so that it has no bearing on the scene rendering.
- Add a WorldEnvironment node. Set the background mode to **Clear Color** or **Custom Color**.
- Notice how the object silhouette is distinctly visible when it shouldn't be. Of course, this does not happen if **Custom Color** is used with a black color :slightly_smiling_face: 

### Minimal reproduction project

[test_clear_ambient_color.zip](https://github.com/godotengine/godot/files/7834138/test_clear_ambient_color.zip)

**Comment by clayjohn** [comment]
The darkness comes from using the fallback material which has an ALBEDO of 0.6
https://github.com/godotengine/godot/blob/be56cab58c056c074d1e02cd0b38641204e39f41/servers/rendering/renderer_rd/forward_clustered/scene_shader_forward_clustered.cpp#L764

Setting the material of the objects to the default StandardMaterial3D makes them disappear against the background. 

The main difference with Godot 3.x is that in Godot 3.x the default shader has a pure white ALBEDO
