### ISSUE TITLE
Collisions stop working when disabling a node after a collision

### ISSUE THREAD

**Issue by mashumafi** [godotengine/godot#56641]
### Godot version

Godot_v4.0-dev.20220105_win64.exe

### System information

Windows 10

### Issue description

After a collision occurs I am showing a dialog box which should pause the game. I am using `process_mode = Node.PROCESS_MODE_DISABLED` to stop processing. If I do this after the collision occurs the object stops executing the enter/exit callback. It will always report that body in it's list of collision objects returned by `Area2D.get_overlapping_bodies()`.

### Steps to reproduce

Set process mode to disabled in the `Area2D.body_entered` signal like so:

```gdscript
func _body_entered(body: Node2D):
	process_mode = Node.PROCESS_MODE_DISABLED
	process_mode = Node.PROCESS_MODE_INHERIT
```

### Minimal reproduction project

[collision.zip](https://github.com/godotengine/godot/files/7834468/collision.zip)

In the demo use arrow keys to move the sphere into the rectangle. It will print the first collision but never emit the exit signal.

**Comment by ccuntd** [comment]
uhh, they never collide.
not even without your code

**Comment by ccuntd** [comment]
and exit signal is emitted

**Comment by AttackButton** [comment]
I was looking for an open issue about this. I think it occurs with other types of collisions too. I found this happening between two CharacterBody2D colliding, that one register the collision normally, but the other that set `process_mode = Node.PROCESS_MODE_DISABLED` will retain the collision and just making it happen when set `process_mode = Node.PROCESS_MODE_INHERIT` again, even minutes later.

Maybe it is related with: https://github.com/godotengine/godot-proposals/issues/2775 and https://github.com/godotengine/godot/pull/50625.

Maybe the only workaround for this is to use the `collision_mask` property.

```
func _body_entered(body: Object):
	print("entered ", body)
	collision_mask = 0
	collision_mask = 1

func _body_exited(body: Object):
	print("exited ", body)
```

**Comment by AttackButton** [comment]
I think the `disabled`property of CollisionShape2D is not working too, the entered and exited signals occurs even with `disabled == true`.

```
func _body_entered(body: Object):
	print($CollisionShape2D.disabled)
	if $CollisionShape2D.disabled == false:
		$CollisionShape2D.disabled = true


func _body_exited(body: Object):
	print("exited ", body)
```

**Comment by AttackButton** [comment]
Ok. I did fix the bug in my project using the `await get_tree().physics_frame`. That's strange because I tried to use set_deferred and call_deferred a lot. 

Set_deferred and call_deferred don't use process_frame (old idle_frame) internally @Calinou?

Maybe this is the behavior that you want, @mashumafi:

```
func _body_entered(body: Object):
	print("entered ", body)
	process_mode = Node.PROCESS_MODE_DISABLED
	await get_tree().process_frame
	process_mode = Node.PROCESS_MODE_INHERIT


func _body_exited(body: Object):
	print("exited ", body)
```

**Comment by mashumafi** [comment]
Tried it on my example. The sample I gave is a mvp but not my exact situation. My pausing occurs on button press. I tried setting the `pause_mode` only during the `physics_frame` but no luck. Nice try though.

**Comment by mashumafi** [comment]
Looks like this is fixed now!
