### ISSUE TITLE
Animation: Panel flickers while position is outside viewport

### ISSUE THREAD

**Issue by dionysius** [godotengine/godot#56659]
### Godot version

3.4.1

### System information

Windows 10

### Issue description

https://user-images.githubusercontent.com/1341084/148705485-a0169bc4-5a37-4d85-a1af-2845a45a85c8.mp4

CenterContainer and Animations don't like each other. The PanelContainer inside the CenterContainer is positioned outside the viewport. Once visibility of this panel is turned on, it is displayed inside the CenterContainer for a brief frame before the Animation resets the Panel outside the viewport again.

No issue with just a Control instead of CenterContainer, but I'd like to intentionally use the CenterContainer.

### Steps to reproduce

Have a CenterContainer->PanelContainer, and an AnimationPlayer

Animation with autostart:
- 0s: the panel is visible=false and positioned outside of the viewport
- 0.5s: the panel is visible=true
  - flicker here for a frame
- 1s: position of panel is still the same outside of the viewport
- 2s: the panel ends in its final position

### Minimal reproduction project

https://github.com/dionysius/godot-issue-animation-in-centercontainer/tree/master

**Comment by VikramSGIT** [comment]
@dionysius Don't use a CenterContainer. They always try to place their children at the centre. 
Everything looks good when I removed the container.✌️

**Comment by dionysius** [comment]
Unfortunately CenterContainer does it's job not well enough, hence the bug report. In my opinion it would be best if it always enforces its child(ren) to be centered and ignore any external position changes (e.g. from animation). Right now we can't animate anything inside the CenterContainer as the outcome is unpredictable.

works well with:
- rect_min_size

doesn't center with:
- rect_size
- position

undecided:
- changing of visibility
  - depends on additional animation options, e.g. turning visibility on during position orrect_size will make it flicker for a frame in its original size and position

Minimal reproduction project N°2: https://github.com/dionysius/godot-issue-animation-in-centercontainer/tree/moving_vs_resize

![screenshot 138](https://user-images.githubusercontent.com/1341084/149021625-6c1146bc-d115-4b27-bf46-35d922c56b24.jpg)

https://user-images.githubusercontent.com/1341084/149021644-2f79d7a5-1297-4e48-9524-ea7b1d01b46c.mp4

**Comment by Calinou** [comment]
> doesn't center with:
> - rect_size
> - position

`rect_size` and `position` must not be set manually when a control is child of a container. This is because the container will override those values every time they are updated.

> - changing of visibility
>   - depends on additional animation options, e.g. turning visibility on during position or rect_size will make it flicker for a frame in its original size and position

This is because of https://github.com/godotengine/godot/issues/20623.
