### ISSUE TITLE
Arabic wrong direction writing

### ISSUE THREAD

**Issue by yzn-h** [godotengine/godot#56653]
### Godot version

4.0.dev

### System information

Linux pop os 21.10, i7-8550U, Vulkan

### Issue description

Arabic direction is wrong

https://user-images.githubusercontent.com/63852512/148696319-d7eda2df-ceac-496d-ae4d-11198cc4ce11.mp4

it should be like this
![image](https://user-images.githubusercontent.com/63852512/148696364-126906fa-8209-405a-b219-69ecc28f8f95.png)

### Steps to reproduce

Write any text in Arabic that consists of more than one line

**Comment by bruvzg** [comment]
> Arabic direction is wrong

I assume you mean wrong alignment. Direction seems to be correct.

**Comment by Calinou** [comment]
Speaking of which, I think the "Left" and "Right" alignment modes should be renamed to "Begin" and "End" and be made to automatically follow the text direction.

**Comment by bruvzg** [comment]
> Speaking of which, I think the "Left" and "Right" alignment modes should be renamed to "Begin" and "End"

I agree, when layout is set to RTL, "Left" and "Right" are flipped, "Begin" and "End" would be more precise.
