### ISSUE TITLE
2.1 beta crashes at exit on Windows 10

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#5666]
Tested on Godot 2.1 beta 64 bits Windows 10:

The editor crashes when closed with the "stopped working" popup.
There is no error message in the console (only white text).

Step to reproduce:
Create empty project, open it, then close Godot.

Woops duplicate of #5664, two issues were posted while I was writing this one :p

**Comment by vnen** [comment]
I saw this first, but I'll keep #5664, which is the first issue.
