### ISSUE TITLE
Icon for scene resource doesn't load. Mac OSX 64 bit, Godot 2.1

### ISSUE THREAD

**Issue by floydnunez** [godotengine/godot#5667]
Mac OSX 64 bit, El Capitan. Godot 2.1

Loaded an old project. Made a popup visible, got a warning, dismissed it. Opened another scene, switched back and forth. Icon for the first scene didn't load.

-Open two scenes. One with a Popup that is hidden by default.
-Click on the popup. A warning will appear. Dismiss it.
-The scene is now changed. Cmd+S to save
-icon disappears.

<img width="294" alt="screen shot 2016-07-12 at 20 53 26" src="https://cloud.githubusercontent.com/assets/1719570/16788528/f94e1c70-4873-11e6-9631-6f1522dcf78a.png">

**Link to minimal example project** (optional but very welcome):

**Comment by Calinou** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.
