### ISSUE TITLE
Lighting with a spotlight does not work correctly

### ISSUE THREAD

**Issue by vadimmos** [godotengine/godot#56678]
### Godot version

v3.4.2.stable.official [45eaa2daf]

### System information

Windows 10, GLES3, NVIDIA Geforce GTX 1060? driver 497.29

### Issue description

![image](https://user-images.githubusercontent.com/14206443/148852604-5a4938ce-06aa-4556-9d2d-c65d98feaa24.png)

### Steps to reproduce

It's just that at some point all the spotlights began to shine at a certain angle incorrectly, the model on which the light falls incorrectly did not change or even move, similarly with materials and textures.

**Comment by Calinou** [comment]
@vadimmos Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

Can you reproduce this after switching to the GLES2 renderer in the Project Settings (**Rendering > Quality > Driver > Driver Name**)?

**Comment by vadimmos** [comment]
When switching to GLES2, the light from the spotlight is not visible at all.

**Comment by vadimmos** [comment]
minimal reproduction project
[test.zip](https://github.com/godotengine/godot/files/7842574/test.zip)

**Comment by vadimmos** [comment]
https://user-images.githubusercontent.com/14206443/148857328-ac8d9cad-f590-4f99-b683-e4a4b0eae052.mp4

**Comment by vadimmos** [comment]
https://user-images.githubusercontent.com/14206443/148857450-58d102aa-8a4a-4dd2-a509-d1250464d236.mp4

**Comment by Calinou** [comment]
My guess is that the level mesh has smooth normals instead of flat normals, and this breaks the appearance of lighting.

**Comment by vadimmos** [comment]
Could normals suddenly change themselves to smooth?

**Comment by clayjohn** [comment]
I opened up the MRP and it appears that there are no normals in the mesh all  normals are pointing to ``vec3(0,0,1)`` so lighting is all wonky. 

Do the normals of the mesh display correctly with your 3D DCC? This may be an export issue from wherever you created the mesh.

**Comment by vadimmos** [comment]
The problem was solved by deleting all files associated with the level model from the project, restarting the application, and re-importing.

**Comment by clayjohn** [comment]
> The problem was solved by deleting all files associated with the level model from the project, restarting the application, and re-importing.

Thanks for letting us know. It sounds like this might have been a bug with the importer.

Did the issue arise when you changed engine versions? I.e. were you using a lower engine version number and it worked correctly, and then you upgraded and it broke?

**Comment by vadimmos** [comment]
No. Since the creation of the project and before the problem occurred, the version has not changed.

**Comment by Calinou** [comment]
@vadimmos Can you (or anyone else) still reproduce this bug in [Godot 3.5.1](https://godotengine.org/article/maintenance-release-godot-3-5-1) or any later release?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.
