### ISSUE TITLE
Unable to create multiple Navigation Polygons in the same tile in TileSet editor.

### ISSUE THREAD

**Issue by cixil** [godotengine/godot#56677]
### Godot version

3.2.3.stable
EDIT: upgraded to 3.4.2.stable and issue still persists

### System information

Linux Pop!_Os

### Issue description

I expect to be able to add multiple navigation polygons to a tile in the tilemap editor, but it only allows for one at a time. 

For collision polygons, I am able to add multiple as expected. The editor also does not allow multiple occlusion polygons for me (despite someone in issue #46580 claiming this feature is implemented on master).

![issue](https://user-images.githubusercontent.com/22418985/148840105-c4558cf5-08c3-4a85-bf9d-7dee846cb219.gif)

### Steps to reproduce

1. Create a TileMap
2. Add a TileSet
2. Open tilemap editor for the tileset, add a texture and select a tile
2. Click the Navigation tab
3. Add a navigation polygon
4. Add another navigation polygon
5. The original polygon has dissappeared, but it should not

**Comment by Calinou** [comment]
> 3.2.3.stable

[Godot 3.2.x is not supported anymore](https://docs.godotengine.org/en/stable/about/release_policy.html#release-support-timeline), so please upgrade to [3.4.2](https://godotengine.org/article/maintenance-release-godot-3-4-2) and check if the issue still occurs there.

**Comment by cixil** [comment]
My bad, I assumed I was using the latest version because I installed Godot from the apt repository.

After installing v3.4.2.stable from [here](https://godotengine.org/download), the issue is still as described for navigation and occlusion polygons.

**Comment by smix8** [comment]
This is fixed in Godot 4 for the NavigationPolygon.

**Comment by akien-mga** [comment]
This is unlikely to receive special bugfixing effort for 3.x, so closing as fixed in 4.0. (But any contributor interested can try to fix it for 3.x too of course.)
