### ISSUE TITLE
In Polygon2D not changed opacity.

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#5668]
**Operating system or device - Godot version:**
Ubuntu16.04, Godot 2.1 beta

**Issue description** (what happened, and what was expected):
In Polygon2D not changed Opacity.

![2016-07-13 09-36-26](https://cloud.githubusercontent.com/assets/11325733/16790187/4d17c4ec-48e6-11e6-99b2-7d650b10c88b.png)

**Comment by vnen** [comment]
Duplicate of #5151.

**Comment by DimaKiva** [comment]
Godot 2.1 RC1 opacity still does not work.

**Comment by akien-mga** [comment]
See #5151, it has been tagged for fixing in 3.0 only.
