### ISSUE TITLE
Preload("filepath").new() causes memory leak

### ISSUE THREAD

**Issue by gerhean** [godotengine/godot#56699]
### Godot version

4.0dev

### System information

Windows10

### Issue description

```
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: ObjectDB::cleanup (core\object\object.cpp:2025)
Leaked instance: GDScriptNativeClass:-9222836574692048447
Leaked instance: Node:960973162676703 - Node name:
Leaked instance: GDScript:-9222420409540934597 - Resource path: res://bar.gd
Leaked instance: Node:1064877011502282 - Node name:
Hint: Leaked instances typically happen when nodes are removed from the scene tree (with `remove_child()`) but not freed (with `free()` or `queue_free()`).
ERROR: Resources still in use at exit (run with --verbose for details).
   at: ResourceCache::clear (core\io\resource.cpp:459)
Resource still in use: res://bar.gd (GDScript)
```

### Steps to reproduce

Create two scripts `foo.gd` and `bar.gd`.

Add `var f = preload("res://bar.gd").new()` anywhere in `foo.gd`.

Add `foo.gd` to any object in current (default) scene.

Run project using godot executable from command line.

Close project.

Look at command line.

### Minimal reproduction project

[preloadproblem.zip](https://github.com/godotengine/godot/files/7848983/preloadproblem.zip)

**Comment by timothyqiu** [comment]
IINM, this is expected behavior.

`res://bar.gd` extends `Node`. Nodes are not reference-counted and you have to call `free()` / `queue_free()` / add the node to the scene tree for it to be destroyed correctly.

**Comment by akien-mga** [comment]
Indeed, a Node won't be freed automatically unless it's added to the scene tree (which is freed when the app is closed, freeing all its child nodes).
