### ISSUE TITLE
Pixel art 3D model appears blurry.

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot#56712]
### Godot version

3.4.2

### System information

Vega 8 Ryzen 3200G

### Issue description

Model imported with pixel art textures appear blurry.
There's not easy or simple way to change the textures from the glb/gtlf file settings.

### Steps to reproduce

Create model with pixel art textures.
Import as gltf/glb.

**Comment by mrjustaguy** [comment]
Turn off filter, also maybe turn off compression.

**Comment by KoBeWi** [comment]
It would be useful if you provided some screenshot and the model.

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/45206.
