### ISSUE TITLE
Navigation2D fails to generate path

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#56729]
### Godot version

3.x (21d52c609012627f4b5089d170831a5e8c328f4e)

### System information

Windows 10, GLES3

### Issue description

Trying to use the new backported Navigation system in 2D. Encountering several issues:

Agent fails to avoid Obstacles. (But does respect NavigationPolygonInstance bounds.)

Agent start to drift up/down when moving into negative X space. Basically as if trying to avoid a gigantic triangular obstacle.

Agents get_nav_path() and get_next_location() fail to return anything but a single entry identical to get_final_location()

### Steps to reproduce

The MRP has a single scene set up with a Navigation2D node, a number of StaticBodies with Obstacle children, and one KinematicBody with an Agent. All Obstacles and Agents have .add_navigation() called with the Navigation2D Node. The only changed property in the KinematicBodys Agent is the Radius.

The Script sets the Agents target location when upon mouseclick. The physics_process interpolates to the Agent.get_next_location(). A _draw function is used to visually the path.

### Minimal reproduction project

[NavTest.zip](https://github.com/godotengine/godot/files/7855826/NavTest.zip)

**Comment by akien-mga** [comment]
CC @Duroxxigar @AndreaCatania

**Comment by Duroxxigar** [comment]
Was able to repro this in 3.5 as well as master branch. The only thing that is not reproducible in master is the negative X issue.

**Comment by TheDuriel** [comment]
> I've checked the demo on `3.x` and regarding:
> 
> * **Agent fails to avoid Obstacles** - the demo is wrong - it uses intermediate data while it should use speed vectors calculated by `NavigationAgent2D` (like in this tutorial: https://godotengine.org/article/navigation-server-godot-4-0)

I would have expected obstacles to be factored into path generation regardless of if the agent is "in motion" or not. Guess that's not the case then. Seems odd.

**Comment by Scony** [comment]
> > I've checked the demo on `3.x` and regarding:
> > 
> > * **Agent fails to avoid Obstacles** - the demo is wrong - it uses intermediate data while it should use speed vectors calculated by `NavigationAgent2D` (like in this tutorial: https://godotengine.org/article/navigation-server-godot-4-0)
> 
> I would have expected obstacles to be factored into path generation regardless of if the agent is "in motion" or not. Guess that's not the case then. Seems odd.

Well, this is because RVO2 is mostly unaware of underlying Recast-based navigation. To fix that we would need to replace RVO2 with Detour which works exactly as you'd expect.

**Comment by realgdman** [comment]
I have encountered numerous issues using Navigation2D with Tilemap after upgrading to 3.5 beta
1. Agent seems to ignore radius. In 3.4, path was laid through cell's center, in 3.5 it sticks to edge of cells, which leads to agent stuck.
2. I've noticed there are non-int coordinates along the path in 3.5. In 3.4 they are always integer, except 1st and last, which are target and object.
3. In 3.4, path was more organic and using 8-directions. In 3.5, path appears to be manhattan only.
4. In 3.5, sometimes path just bugged, sticking to some random edge upward and then cutting through cells.

![image](https://user-images.githubusercontent.com/83962805/149680126-a37de925-1efb-4872-85ec-a8bb4581bcd6.png)

[basic-pathfinding-Godot.zip](https://github.com/godotengine/godot/files/7878040/basic-pathfinding-Godot.zip)

**Comment by TheDuriel** [comment]
@realgdman 3.4 release version doesn't have the new navigation server, so I don't see the results here aren't related to the issue really. (It's better to make new issues, not pile on with 'related' issues. And there are several about tilemap navigation already.) It mainly looks like you might have your tilemaps configured differently. Either how your textures are centered or how your navmesh was set up for your tiles.

**Comment by realgdman** [comment]
@TheDuriel I haven't found tilemap navigation issue, but I don't mind creating new.

**Comment by TheDuriel** [comment]
Negative triangle issue fixed as of commit #f2a213a996970fe729190b0d33020be589e55b48

**Comment by TheDuriel** [comment]
Closing, since use case was miss understood. (I assumed the path would include obstacle avoidance. But this appears not to be intended to be a thing at all.) I might make a new issue with the other... problems that I've found.
