### ISSUE TITLE
No way to get a PhysicsRayQueryParameters2D/3D from GDScript

### ISSUE THREAD

**Issue by pooroligarch** [godotengine/godot#56728]
### Godot version

v4.0.dev [ddb9accb7]

### System information

Windows 11

### Issue description

There is no (documented) way to get a `PhysicsRayQueryParameters2D` or `3D` object from GDScript, which is required for ray casting since #54573. The class is exposed and can be used in script, but there is no constructor or other way to create it. In the reproduction project below all 3 ways to ray cast fail - using the `Vector2`s directly, creating a `PhysicsRayQueryParameters2D` with vectors as arguments or creating an empty one and setting `from` and `to` values on it. 

### Steps to reproduce

* Get the direct space state using `get_world_2d`/`3d`.`get_direct_space_state()`
* Cast a ray using `intersect_ray()` on the space state
* Try to get a parameters object as the argument for `intersect_ray()` - This fails.

### Minimal reproduction project

[raycast.zip](https://github.com/godotengine/godot/files/7855650/raycast.zip)

**Comment by Calinou** [comment]
cc @pouleyKetchoupp

**Comment by Blackiris** [comment]
The following way works for me:
```
var params = PhysicsRayQueryParameters3D.new()
params.from = pos1
params.to = pos2
params.exclude = obstacles

var res = space_state.intersect_ray(params)
```

**Comment by cdemirer** [comment]
`PhysicsRayQueryParameters*D` are classes so they are constructed with `name.new()` (e.g. `Node.new()`). Only built-ins have the `name()` constructor syntax. The list of built-ins are documented here:
https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_basics.html#built-in-types

The class constructor method (`.new()`) not being documented doesn't seem specific to this case. (It would probably be redundant.)

**Comment by pooroligarch** [comment]
> `PhysicsRayQueryParameters*D` are classes so they are constructed with `name.new()` (e.g. `Node.new()`). Only built-ins have the `name()` constructor syntax. The list of built-ins is documented here: https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_basics.html#built-in-types
> 
> The class constructor method (`.new()`) not being documented doesn't seem specific to this case. (It would probably be redundant.)

Looks like it's just a documentation issue then. Closed.
