### ISSUE TITLE
Auto-completion not working for arguments of signal connections

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#5672]
**Operating system or device - Godot version:**

**Issue description** (what happened, and what was expected):
func _on_Area2D_body_enter( body ):
    body.

no functions listed after . typed.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by J08nY** [comment]
Godot version? Since there were some changes to code completion in the current master branch since 2.0.3 even 2.0.4.

**Comment by alexzheng** [comment]
2.0.3  and 2.1

**Comment by vnen** [comment]
I don't recall completion working for arguments of signal connections. Was this working on a previous version?

**Comment by MarianoGnu** [comment]
Since GdScript is duck typed there's no way the Editor can know what type is body. To solve this you need static typing (or a way to hint the type) i usually add a line body = RigidBody.new() at the start and try not to forget to comment it later...

**Comment by reduz** [comment]
We'll add type hints for 2.2

**Comment by alexzheng** [comment]
Also onready var node = get_node("mynode") is a very handy feature,
but get_node have no hint for the node name as write var node = get_node("mynode") in _ready()

**Comment by akien-mga** [comment]
As mentioned in https://github.com/godotengine/godot/issues/15718#issuecomment-446207371, this is now solved thanks to optional typing in 3.1.

@vnen Do you think we should go one step further and automatically set the type hint when connecting signals?

**Comment by vnen** [comment]
@akien-mga that is already the case if you have the option enabled in Editor Settings.

**Comment by akien-mga** [comment]
Nice, closing then.

**Comment by MarianoGnu** [comment]
`@akien-mga that is already the case if you have the option enabled in Editor Settings.`
cool, is this feature enabled by default? it should imho
