### ISSUE TITLE
Code generated when connecting a signal in the editor is inconsistent with the official GDScript style guide

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#56732]
### Godot version

v3.4.2.stable.official [45eaa2daf]

### System information

w10 64

### Issue description

When a signal is connected, the connection code appears 1 space apart from the last line of code in the script. In the documentation, good practice suggests leaving 2 spaces between each function.
The user must bother to correct and add those spaces that the editor has not respected. Could godot do it automatically and leave 2 lines between the last line of code and the signal connection code?

Godot does this:
![Captura](https://user-images.githubusercontent.com/19652075/149184729-f0b72b4c-1e68-458f-bd2a-3c613a6665f9.PNG)

Godot should do this:
![Captura2](https://user-images.githubusercontent.com/19652075/149310615-05446bcb-ce2b-438b-9cd0-aeee4a84c24b.PNG)

### Steps to reproduce

Connect a signal

### Minimal reproduction project

...

**Comment by pycbouh** [comment]
>  good practice suggests leaving 3 spaces between each function.

Where did you see that?

**Comment by Calinou** [comment]
I think Godot will add too many lines if there was already at least two blank lines at the end of file. Godot should try to detect the number of blank lines at the end of file and adapt the spacing between newly created functions automatically. (Additionally, the script editor could remove extraneous blank lines at the end of a file when saving a file.)

**Comment by BakaVermeil** [comment]
https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_styleguide.html#blank-lines

Two blank lines are expected. Calinou hits the problem on the head.

> (Additionally, the script editor could remove extraneous blank lines at the end of a file when saving a file, keeping only 1 blank line at the end.)

This was previously shut down in favor of a git setting and lack of community interest. (Silly I know.) But I'm all in favor.

**Comment by Torguen** [comment]
My mistake, good practice suggests 2 lines. Although godot only inserts 1 empty line when connecting.

**Comment by dalexeev** [comment]
In 4.x the following project settings are implemented:

* `editor/naming/default_signal_callback_name`;
* `editor/naming/default_signal_callback_to_self_name`.

![](https://github.com/godotengine/godot/assets/47700418/b12be6f5-e3bd-472e-84c2-691d8d607f6f)

See:

* #52997
* #67018

As for 3.x, these changes cannot be backported directly and should be re-implemented if a contributor wishes to do it. In any case, this is more of a proposal material, not a bug.
