### ISSUE TITLE
Node not found: absolute path attempted from ""

### ISSUE THREAD

**Issue by NewOldMax** [godotengine/godot#56743]
### Godot version

3.4.2.stable

### System information

Windows 10/11, GLES3

### Issue description

Hi there!
Few days ago I released my [game](https://store.steampowered.com/app/1659180/TD_Worlds/) and in general everything is working fine, but some users are experiencing crashes with a strange error:
```
ERROR: Can't use get_node() with absolute paths from outside the active scene tree.
   at: Node::get_node_or_null (scene\main\node.cpp:1264) - Condition "!data.inside_tree && p_path.is_absolute()" is true. Returned: nullptr
ERROR: Cannot get path of node as it is not in a scene tree.
   at: Node::get_path (scene\main\node.cpp:1587) - Condition "!is_inside_tree()" is true. Returned: NodePath()
ERROR: (Node not found: "/root/game/level/EnemyPool" (absolute path attempted from "").)
   at: Node::get_node (scene\main\node.cpp:1323) - Condition "!node" is true. Returned: nullptr
```
EnemyPool is a node that always exists on the scene and is never removed, but disappears from the scene for some reason.
So my question is, how can this be in theory, and is there a way to get a crash dump with useful information from release build?
Also this `absolute path attempted from ""` is really weird.

### Steps to reproduce

Only some of users got this issue

**Comment by NewOldMax** [comment]
It looks like issue appears when I added Danish translation to the project, but this relation very weak

**Comment by NewOldMax** [comment]
After some debugging I found a line which causes error (get_node call) but even `get_node_or_null` crashes game there

**Comment by akien-mga** [comment]
The error says:
```
ERROR: Can't use get_node() with absolute paths from outside the active scene tree.
   at: (scene\main\node.cpp:1264)
```

That means you're likely calling `get_node` on a node which is not in the current scene tree. So it can't access `/root/game/level/EnemyPool` because that's part of a scene tree which this not doesn't belong to. You need to `add_child` the node to the tree for it to have tree access.

**Comment by NewOldMax** [comment]
@akien-mga hi
Yes, error message says about that, but node is static, I will attach image.
![image](https://user-images.githubusercontent.com/1328473/149294758-48d05b8b-cd9f-4182-95fe-7d1923f393e1.png)
So LevelManager calls `get_node('root/game/level/EnemyPool')` and usually it works fine, but in some cases (which are not determinted now) this call fails. All nodes always exists and nobody delete them normally.

**Comment by akien-mga** [comment]
Where are you calling `get_tree` exactly? If it's in `_init` then the node is _not_ in the scene tree yet.

**Comment by NewOldMax** [comment]
No, it's not in `_init`. Just a method which called to load new level data.
Something like that.
```
func loadLevel(levelData):
    ...
    get_node('/root/game/level/TowerPool').removeOldTowers(); // does not crash
    get_node('/root/game/level/EnemyPool').removeOldEnemies(); // crash or not ¯\_(ツ)_/¯
    ...
```
This worked perfectly last year but suddenly stop

**Comment by NewOldMax** [comment]
As a workaround I moved EnemyPool to `onready var` and seems to it becomes more stable, but I will test further

**Comment by NewOldMax** [comment]
Finally I find a case, it was rare combination of game params which causes "outside of tree" call.
Glad to say that this is not a Godot fault but silly me :)
