### ISSUE TITLE
Vulkan: Crash when setting Reflection Roughness Layers to a low value

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#56747]
### Godot version

v4.0.dev.20220105.official [8f6cba3a4]

### System information

Windows 11, Vulkan, Nvidia Quadro K2000 472.84

### Issue description

When Roughness Layers are set to 1,2 when trying to manipulate object materials the editor crashes (in VMR, didn't test VCR)

### Steps to reproduce

Set Roughness Layers to 1 or 2, restart the editor, Make a Mesh Instance and try to manipulate a Material for it. This will Result in a Crash.

Notes: Mobile Renderer was tested

**Comment by mrjustaguy** [comment]
Retested on Beta 14 on a GTX 1050 Ti (don't have the Quadro anymore to test with sadly) and Unable to Reproduce this.

**Comment by clayjohn** [comment]
As luck would have it I just reproduced this in the mobile renderer with a ReflectionProbe in the scene. So I will leave this open
