### ISSUE TITLE
Stretching with anchors does not take into account the scale of the nodes.

### ISSUE THREAD

**Issue by 4CoDev** [godotengine/godot#56746]
### Godot version

3.4.2.stable.mono

### System information

Windows 11, GLES3, RTX 3080 Ti

### Issue description

I made a microscopic pixel interface in my game with the ability to scale (x1, x2, x3, etc.) as in minecraft. When using wide anchors stretching does not take into account the scale of the nodes, so they are out of the edge of the window.

x1
![image](https://user-images.githubusercontent.com/95243328/149313619-8c158bca-10f4-48e5-950a-40516e46f348.png)

x2
![image](https://user-images.githubusercontent.com/95243328/149313567-6bc42473-4d3b-438b-bf4b-dc081111a438.png)

### Steps to reproduce

1. Create Panel node
2. Set Left Wide anchor
3. Set Scale for node

### Minimal reproduction project

[AnchorAndScale.zip](https://github.com/godotengine/godot/files/7862036/AnchorAndScale.zip)

**Comment by Calinou** [comment]
> I made a microscopic pixel interface in my game with the ability to scale (x1, x2, x3, etc.) as in minecraft.

With the [2D scale factor property](https://github.com/godotengine/godot/pull/52137), you do not need to do this.

**Comment by Maran23** [comment]
> Related to #52383.
> 
> > I made a microscopic pixel interface in my game with the ability to scale (x1, x2, x3, etc.) as in minecraft.
> 
> With Godot's support for [multiple resolutions](https://docs.godotengine.org/en/stable/tutorials/viewports/multiple_resolutions.html) and the [2D scale factor property](https://github.com/godotengine/godot/pull/52137), you do not need to do this. Control scaling should only be used for animation purposes or prototyping, not for anything else.

Hm, what I don't understand then: 
When I design a user interface which looks good on Desktop 1920x1080, it typically looks too tiny on a mobile with something similar like 1920x1080 since the screen is much smaller and the pixel dpi much higher. 
What is the best way to have a proper setup for all platforms/screens?

I understand that scale might not be the best bet here, but when I tried 2d stretching with a lower base resolution instead things doesn't look so crisp on desktop.

**Comment by Calinou** [comment]
> What is the best way to have a proper setup for all platforms/screens?

Use the new 2D scale factor property to increase the size of UI on mobile, regardless of the actual screen resolution.

**Comment by Maran23** [comment]
> > What is the best way to have a proper setup for all platforms/screens?
> 
> Use the new 2D scale factor property to increase the size of UI on mobile platforms, regardless of the actual screen resolution. You can do this automatically on mobile platforms by overriding the **Stretch Shrink** project setting with the `.mobile` [feature tag](https://docs.godotengine.org/en/stable/getting_started/workflow/export/feature_tags.html).

Big thanks, that worked very well! 
I was not aware I could overwrite a property for e.g. mobile, although it makes a lot of sense. Also shrink is not the best name here but I think this is fixed on 4.0 if I recall correctly.

I have read [Multiple Resolutions](https://docs.godotengine.org/en/stable/tutorials/viewports/multiple_resolutions.html) multiple times but didn't found the answer there, maybe it makes sense to document it there as well and link it to the [Feature Tag](https://docs.godotengine.org/en/stable/getting_started/workflow/export/feature_tags.html).

**Comment by azagaya** [comment]
Is there a way to change the shrink by code (besides `set_screen_stretch()`)? because not all mobile devices have the same screensize and dpi, so different scaling may be needed for different devices.

**Comment by Calinou** [comment]
> Is there a way to change the shrink by code (besides `set_screen_stretch()`)? because not all mobile devices have the same screensize and dpi, so different scaling may be needed for different devices.

Yes, see https://github.com/godotengine/godot-docs/pull/7136.

**Comment by cidwel** [comment]
I have a different usecase where I just want to scale some element in my UI.

I think this ticket is still relevant. anchor positioning should affect scale factor
![image](https://github.com/godotengine/godot/assets/535967/9879b191-bad0-452c-9b38-0dd970d557ca)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/19068.
