### ISSUE TITLE
make texture parameter of ImmediateGeometry.begin() optional ?

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#5676]
**Operating system or device - Godot version:**
2.0.4.1

**Issue description** (what happened, and what was expected):

Sometimes, it could be handy if the texture parameter of ``ImmediateGeometry.begin(primitive,texture)`` was optional.

( and also, optionally, it would be handy if all the ``PRIMITIVE_xxxx`` constants were also bound to ``ImmediateGeometry`` too, so we don't have to look for them into ``Mesh.PRIMITIVE_xxxx`` )

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by bojidar-bg** [comment]
Wouldn't a material parameter be more handy?

**Comment by SuperUserNameMan** [comment]
would this material parameter be optional ?

Though, note ImmediateGeometry already have a Material Override inherited from GeometryInstance that we can easily and optionally access .get_material_override().

**Comment by SuperUserNameMan** [comment]
BTW, it is not clear how this texture parameter must be used.

If you provide a texture to ImmediateGeometry.begin(), it won't be visible at all.

The only way to make a texture (and vertex colors) visible is to set a material override and bind texture to it.

But the texture you gave as parameter will not be used at all.

Maybe this ImmaediateGeometry also need some documentation :-/

**Comment by SuperUserNameMan** [comment]
Also, as mentioned into #5720, the code behind this texture parameter is totally unused.

The texture is stored into a cache, but this cache is used nowhere and just cleared once the immediategeo node is deleted.

**Comment by reduz** [comment]
It is not unused, it needs to be kept by the node. If not kept, it may be erased if no longer used and the texture stored in the VisualServer will become invalid.

**Comment by SuperUserNameMan** [comment]
@reduz : 
so where do we get the texture from ?
does it have to be taken from the override material ?

because if you create an ImageTexture and use it with ImmediateGeometry.begin(), this texture is not used to texture the immediategeometry.

**Comment by SuperUserNameMan** [comment]
Okay, so after talking with @reduz on IRC, the texture parameter can be used to override the texture of the material attached to the ImmediateGeometry.

If you attach a FixedMaterial to your geometry, this material will need at least a diffuse texture or detail texture, or the passed as texture parameter will be ignored.

By default, the geometry node uses the default material which has no texture. 
That's why the texture parameter seemed useless.
