### ISSUE TITLE
NavigationPolygonInstance does not use closed polygon

### ISSUE THREAD

**Issue by dardanbujupaj** [godotengine/godot#56773]
### Godot version

3.5.beta1

### System information

MacBook Air M1, Monterey 12.1 

### Issue description

When creating a NavigationPolygonInstance with > 3 Points, the NavigationServer does not close the the polygon. As a result, part of the polygon is not accessible for navigation.

Following video shows the issue (red line for the calculated navigation path) and a working polygon when the polygon is closed (last point equals first point of polygon).

https://user-images.githubusercontent.com/16074028/149425339-7247cf2b-0f54-4166-ae00-021d974d7f71.mov

 
I might be wrong and this is expected behaviour, but:
- the "Visible Navigation" Option in Debug shows the whole polygon
- with Polygon, CollisionPolygon, OccluderPolygon there is no need to close the polygon explicitly
- I didn't find an option to close the polygon using the editor, which makes it impossible to create navigation polygons without code...
- all helper methods in Geometry (merge, clip etc.) do not close polygons

### Steps to reproduce

1. Create a NavigationPolygonInstance with more than 3 Points in the editor.
2. Calculate Path using NavigationServer/NavigationAgent

### Minimal reproduction project

[nav-poly-min-repro.zip](https://github.com/godotengine/godot/files/7866636/nav-poly-min-repro.zip)

**Comment by Calinou** [comment]
I can reproduce this on `3.x` e00a6d2b7, but not on `master` d13c3c929.

`master` (4.0) version of the minimal reproduction project: [nav-poly-min-repro-4.0.zip](https://github.com/godotengine/godot/files/7866777/nav-poly-min-repro-4.0.zip)
 
Video of the project on `master` with the bug not occurring there:

https://user-images.githubusercontent.com/180032/149430360-8dab06a9-d816-4f49-ac20-31699a7f28ef.mp4

**Comment by akien-mga** [comment]
CC @AndreaCatania @Duroxxigar

**Comment by akien-mga** [comment]
Fixed by #56976.
