### ISSUE TITLE
Hot-reloading AtlasTexture causes infinite reload loop

### ISSUE THREAD

**Issue by miere43** [godotengine/godot#5678]
**Operating system or device - Godot version:**
Windows 10 x64, Godot 2.1 beta x86

**Issue description** (what happened, and what was expected):
After saving image which loaded as AtlasTexture, Gotot catches up and tries to reimport texture, but **sometimes** this causes infinite texture reloading loop, I have got a video: https://gfycat.com/EvenThinDiplodocus
I have used Paint.NET to resave the image. Also I have my image stored outside of Godot project folder, I used Import window to import image as texture. Going back to project list and opening project again helps, console shows `condition 'rename_error' is true` at `drivers\windows\file_access_window.cpp:139`

**Steps to reproduce:**
Resave image which is saved as AtlasTexture, maybe there are issue with another texture types too, but I have never encoutered it. Sometimes after saving image this issue happens, not happens when just started up Godot.

**Comment by Calinou** [comment]
I have had an infinite reload loop issue with a 3D `.dae` scene as well. It seems to happen only when you're focused on the tab containing the scene while the file is saved.

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.
