### ISSUE TITLE
Background images are not tiling when a scene is instanced.

### ISSUE THREAD

**Issue by ajk2196** [godotengine/godot#56782]
### Godot version

3.4.2 Stable

### System information

Windows 10, 2 X RTX 2070 Super, AMD 3700X

### Issue description

I have a scene file which is a part of a menu. This menu contains an image that is tiling perfectly when opened / viewed separately. However, when I instance this menu scene to my main scene, the tiling doesn't happen. Only the main base image appears at the top left corner of the texture rect.

### Steps to reproduce

My file is large and I don't want to share it.

**Comment by Chaosus** [comment]
Please provide a sample project (or at least a video/screenshot demonstration), if you don't want to share your image, create another image that reproduces this issue.

**Comment by ajk2196** [comment]
https://user-images.githubusercontent.com/90527174/149509141-79945a77-4ce7-4857-9d0d-0d0423ac2be8.mp4

Here You Go.

**Comment by KoBeWi** [comment]
When you set the anchors to Full Rect, the node fits the space it's placed into. But you put it under Node2D, which has no area, so it shrinks to minimum size. Use Top-Left anchor if you want to use it under Node2D or use a Control root instead.

Here you can see that your node shrunk to the size of the texture:
![image](https://user-images.githubusercontent.com/2223172/149545604-efc9053f-c5c7-4c11-8ccb-06e5f4760328.png)
