### ISSUE TITLE
Vulkan: Full-size GI rendering still results in slightly blurry edges

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#56792]
*Related to https://github.com/godotengine/godot/issues/54978.*

### Godot version

4.0.dev (d13c3c929)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 495.46)

### Issue description

Full-size GI rendering still results in slightly blurry edges, despite it being full resolution. This may hint at a misconfiguration of the rendering size or the sampler (should it use nearest-neighbor at full resolution?).

This occurs with both SDFGI and VoxelGI, since they both rely on deferred rendering in `master`.

Fixing this issue may also improve half-resolution GI appearance slightly, since it will be perfectly aligned on the pixel grid.

*Click to view at full size.*

![2022-01-14_17 52 04](https://user-images.githubusercontent.com/180032/149554191-7b9c627d-27d6-44a9-8461-1e1efe8bc589.png)

### SDFGI edge (blurry)

*Most lighting is contributed by SDFGI here, so the edge becomes blurry.*
*Cropped portion of the above screenshot with 400% nearest-neighbor scaling.*

![image](https://user-images.githubusercontent.com/180032/149554553-c65367ca-8e8b-4350-bcfd-5dec834973e7.png)

### Bright edge (sharp)

*Most lighting is **not** contributed by SDFGI here, so the edge remains sharp.*
*Cropped portion of the above screenshot with 400% nearest-neighbor scaling.*

![image](https://user-images.githubusercontent.com/180032/149554448-3fe15882-bf4b-4fdd-85fd-93d7ed077328.png)

### Steps to reproduce

- Add a MeshInstance3D with its global illumination mode set to **Baked**. The mesh should be a scene where significant large areas are shaded by solid surfaces.
- Add a DirectionalLight3D node with shadows enabled.
- Add a WorldEnvironment node with a new Environment resource.
- Enable SDFGI in the Environment resource.

### Minimal reproduction project

[test_sdfgi_num_cascades.zip](https://github.com/godotengine/godot/files/7865266/test_sdfgi_num_cascades.zip)

**Comment by akien-mga** [comment]
Fixed by #61070.
