### ISSUE TITLE
Profiler: the checkboxes seem difficult to tick

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#5679]
Tested on Godot 2.1 beta, Windows 10 64 bits

When testing the debugger, I found that ticking the checkboxes that toggle curves are not very responsive, I often have to click several times on them, even when the game is paused or profiling is stopped.
However, no problem when the game doesn't runs.

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by bojidar-bg** [comment]
Is this still valid?

**Comment by Zireael07** [comment]
I think it's still valid, I found it difficult to tick profiler checkboxes for curves.

I think the problem increases the lower the checkbox is (for lines high up, it's easier, for the bottom line its argh why won't it tick!)

**Comment by pycbouh** [comment]
Is the problem still present? I've been profiling my game recently and didn't notice anything. Is this an issue with the editor UI not reacting on clicks, or the active area being too small?

**Comment by Calinou** [comment]
I'll close this as nobody else has been able to reproduce this recently. Please comment (with the [issue template](https://github.com/godotengine/godot/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) filled) if you can still reproduce this.
