### ISSUE TITLE
Modifying a canceled Ctrl f search selection, selects to the cursors previous location

### ISSUE THREAD

**Issue by duianto** [godotengine/godot#56800]
### Godot version

v3.4.1.stable.official [aa1b95889]

### System information

Windows 10 21H1

### Issue description

Modifying a selection after canceling a `ctrl f` search.
Starts or ends the selection at the cursors previous location.

Where the cursor was when the last selection was made,
or where the mouse was clicked to set the cursor's location.

### Steps to reproduce

- Create a new project
- Add a new script, by right clicking in the FileSystem panel
- Choose `New script...`
- Press `Enter` to create the script
- Open it by double clicking on `new_script.gd`
- Mouse click on the word `previous` (line 14)
- Press `Ctrl f` to open and focus the find input box,
- Type: `var`
The characters `var` in the word `variables` (line 4) becomes highlighted
- Press `Esc` to close the find input box
The text `var` is selected,
and the cursor is blinking to the right of the selection.
- Press `Shift left arrow` to select one less character

### Observed
The selection starts between the `a` and `r` in the word `variables`.
And ends in the word `previous` where the mouse was clicked.

The same thing is observed if a word is selected with the keyboard.
- Move down the cursor two lines, to the word `text` (line 6)
- Press `shift left arrow` to select a character.
- `Ctrl f` search for the word `the`
- `Esc` cancel the search
- `Shift left arrow` to modify the selection

The selection starts in the word `text` (line 6),
and ends after `th` in the third word `the` on line 9.

https://user-images.githubusercontent.com/13420573/149596418-dc068fc1-bbee-4584-b298-1243ca64482b.mp4

### Expected
The selection, after canceling the search, should have been modified as requested by pressing `shift` `arrow key`.

### Notes
This isn't limited to the left arrow key, the issue occurs with any selection modification.

`Shift` mouse clicking doesn't always cause it on the first mouse click,
but continuing to `Shift` mouse click on the line(s) above or below eventually cause it to happen.

### Minimal reproduction project

Not project-specific, this happens in the script editor.

**Comment by KoBeWi** [comment]
Still valid in alpha 7

**Comment by kitbdev** [comment]
- Fixed by #86978
