### ISSUE TITLE
Skew transform doesn't work correctly for HeightMapShape

### ISSUE THREAD

**Issue by kocsis1david** [godotengine/godot#56824]
### Godot version

v3.4.2.stable.official [45eaa2daf]

### System information

Windows 10

### Issue description

When skew transform is applied to a `HeightMapShape`, ray casting works strangely. Seems like the shape remained rectangular instead of a parallelogram.

### Steps to reproduce

- Create a plane 
- Add a StaticBody child with HeightMapShape collision shape, the size should be 3*3, so it matches the plane size 
- Ray casting should work correctly now, because the collision shape is the same as the plane
- Change the transformation matrix to skew
- The plane render is rendered with the skew transform, but ray casting doesn't respect the skew transform

### Minimal reproduction project

https://github.com/kocsis1david/godot-height-map-test

The ray intersection is printed to the console, but I get an empty result when I hover the mouse over the corner of the plane.

![image](https://user-images.githubusercontent.com/722066/149639387-c8262178-c89e-4011-be38-f82fcd2cf448.png)

**Comment by Calinou** [comment]
Scaling collision shapes is not supported in Godot. It can sometimes work with uniform scaling, but it will pretty much never work reliably when using non-uniform scaling (which includes skewing).
