### ISSUE TITLE
No way for CanvasItem to ignore parent transformation and preverse draw order

### ISSUE THREAD

**Issue by Lucrecious** [godotengine/godot#56821]
### Godot version

3.5

### System information

Mac OSX

### Issue description

`set_as_toplevel(true)` sets the canvas node to the top level I guess, and so the sprite is drawn on top of everything, which I don't think is intended?

Also, putting a `CanvasItem` under a regular `Node` also pushes the children to the top level it seems because if I do that Sprites are also drawn on top of everything.

Because of this, I don't really see a way to ignore parent transformations while preserving the draw order.

Am I missing something here?

Also, `show_behind_parent` as an option doesn't do anything to fix the problem no matter where the node is in the scene tree.

### Steps to reproduce

1. Create sprite and add the Godot icon as the texture
2. Add another sprite of another image and make sure its drawn in front of the sprite in (1)
3. Add `set_as_toplevel(true)` in a built-in script for sprite in (1)

Expected: (1) sprite is drawn UNDER (2) sprite
Actual: (1) sprite is drawn OVER (2) sprite

Same thing happens if instead you put the (1) sprite under a regular `Node`.

**Comment by pycbouh** [comment]
> `set_as_toplevel(true)` sets the canvas node to the top level I guess, and so the sprite is drawn on top of everything, which I don't think is intended?

That's the point. It is drawn on top of other canvas items, and it ignores parent transformations. Note that multiple toplevel nodes are drawn in their respective tree order, but still on top of every other node.

**Comment by LunaticInAHat** [comment]
> That's the point. It is drawn on top of other canvas items, and it ignores parent transformations. Note that multiple toplevel nodes are drawn in their respective tree order, but still on top of every other node.

Is there a reason why those two separate behaviors are tied together under a single setting? I'm not sure I see that there is an inherent connection between the desire to have a node ignore its parent's transformations, and to have it draw on top of its chain of parents.

**Comment by Lucrecious** [comment]
> > `set_as_toplevel(true)` sets the canvas node to the top level I guess, and so the sprite is drawn on top of everything, which I don't think is intended?
> 
> That's the point. It is drawn on top of other canvas items, and it ignores parent transformations. Note that multiple toplevel nodes are drawn in their respective tree order, but still on top of every other node.

Okay, that's fine I guess, but then I would at least expect to be able to put an empty regular `Node` in between two canvas nodes so that the child of the `Node` would lose its transformation (this seems like a potential solution?).

I mean, if this is not how you can ignore parent transformations, then how do I?

**Comment by pycbouh** [comment]
> Is there a reason why those two separate behaviors are tied together under a single setting? I'm not sure I see that there is an inherent connection between the desire to have a node ignore its parent's transformations, and to have it draw on top of its chain of parents.

Well, the method is called `set_as_toplevel()`, I'd say that drawing on top of everything is it's anticipated behavior, and ignoring transformations comes as a part of achieving that, not as the main feature of it.

> I mean, if this is not how you can ignore parent transformations, then how do I?

You can use a `CanvasLayer`, I guess.

**Comment by cgbeutler** [comment]
Node2D has `z_as_relative` and `z_index` for manual control of draw order. Whenever using `set_as_toplevel`, I use the z indexing stuff to -1 the children accordingly.
Annoyingly, each z index level is a game-wide thing. I finally just blocked out ranges for background, characters, foreground, ui, etc. Almost like the collision flags.

**Comment by Lucrecious** [comment]
> Node2D has `z_as_relative` and `z_index` for manual control of draw order. Whenever using `set_as_toplevel`, I use the z indexing stuff to -1 the children accordingly. Annoyingly, each z index level is a game-wide thing. I finally just blocked out ranges for background, characters, foreground, ui, etc. Almost like the collision flags.

Not a bad solution, but I'd prefer not to have separate z-buffers, my game is pretty simple, don't want to complicate it more.

I think this is worth a proposal though. It's not uncommon to want to ignore parent transformation and keep the draw order.

Bullets and sword trails are pretty much a staple of many indie games, and they both need to ignore parent transformation and usually keep draw order.

**Comment by lawnjelly** [comment]
Caveat I haven't made any 2D games, but can't you just grab the position, rotation and scale of the parent Node2D and just reverse those that you don't want in the child node?

or use these which seem to do that for you:
```
	void set_global_transform(const Transform2D &p_transform);
	void set_global_position(const Point2 &p_pos);
	void set_global_rotation(float p_radians);
	void set_global_rotation_degrees(float p_degrees);
	void set_global_scale(const Size2 &p_scale);
```

**Comment by cgbeutler** [comment]
@Lucrecious Yeah, this proposal is good, just helping give folks workarounds. (Also, bullets should probably be spawned next to the player, not as a child, but I get you. My player has a cape that flows behind him, which is where I used the z-order stuffs.)

@lawnjelly You would have to call that every single update frame if the parent node is moving. Not ideal. Also, that solution is a non-starter for physics stuff. (Not saying it can't be used somewhere, just that it's got its issues.)

**Comment by lawnjelly** [comment]
Yes I just wondered if there was already a mechanism for doing this. Maybe some guys with more knowledge of the scene side 2D stuff will chime in.

Anyway, as far as the code is concerned it looks as though it might not be that involved to turn off the influence of the parent transform, in e.g.:
`CanvasItem::get_global_transform()` (where there is already an exception for not having a parent)
and `CanvasItem::_notify_transform()`.

But yeah this would require a proposal if there was no means of doing this already.

**Comment by pycbouh** [comment]
> Bullets and sword trails are pretty much a staple of many indie games, and they both need to ignore parent transformation and usually keep draw order.

Bullets I give you, though you may simple want to not parent them to their emitter. But trails mostly benefit from having relative transformations, as they are inherently attached to their source. And if you want to keep them pinned to some global position, you can do so in code with the aforementioned methods.

Although, we do have toggles for some VFX to only work in local or in global space, so maybe there is a use case for a similar toggle for nodes if you are avoiding using shaders. Not sure how strong of an argument that would be.

Either way, you can try to make your case with a proposal, so please create one.

**Comment by Calinou** [comment]
A proposal was opened here: https://github.com/godotengine/godot-proposals/issues/3808
