### ISSUE TITLE
ItemList - set_item_disabled() doesnt have any visible effect

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#5683]
*Bugsquad edit:* Seen in 2.1-beta (but actually there too in 2.0)

It doesnt seem to do what it is supposed to.

Try it

```
func _on_ItemList_item_selected( index ):
	set_item_disabled(index,true)
```

or am i messing something up here? :)

**Comment by akien-mga** [comment]
It seems to work fine for me to toggle the `disabled` parameter:
```
func _ready():
	add_item("Toto 1")
	add_item("Toto 2")
	add_item("Toto 3")

func _on_item_selected( index ):
	print("idx:", str(index), " - disabled: " + str(is_item_disabled(index)))
	set_item_disabled(index, true)
	print("idx:", str(index), " - disabled: " + str(is_item_disabled(index)))
```

Now the question is more, what should the `disabled` status do?

**Comment by akien-mga** [comment]
> Now the question is more, what should the disabled status do?

Looking at the source code, it doesn't do anything. It's just something that you can set with `set_item_disabled` and get with `is_item_disabled`. So you can use it in your game's logic by checking first if `is_item_disabled` before doing stuff with the item.

I don't know what was the intended use of this parameter though. @reduz, you added it one year ago when refactoring the file dialog: https://github.com/godotengine/godot/blame/2fd9b77/scene/gui/item_list.cpp#L1278-L1279
Do you remember what you wanted it to be used for?

**Comment by blurymind** [comment]
According to godot's online documentation it should make the item
unclickable when disabled.

That is also what i wanted it to do.
How does one do that anyways?

**Comment by akien-mga** [comment]
> According to godot's online documentation it should make the item
unclickable when disabled.

What part of the documentation? It's not said in the class reference, where it is undocumented.

**Comment by akien-mga** [comment]
> How does one do that anyways?

`void set_item_selectable ( int idx, bool selectable )`

**Comment by blurymind** [comment]
@akien-mga  I made a mistake. I was looking at the popup menu's documentation here:
http://docs.godotengine.org/en/latest/classes/class_popupmenu.html#class-popupmenu-set-item-disabled

it has the same set_item_disabled method. It does the following:

> Sets whether the item at index “idx” is disabled or not. When it is disabled it can’t be selected, or its action invoked.

Basically that is what I want - I want the item to not be invoked when right clicked and also disabled visually.

void set_item_selectable ( int idx, bool selectable )
Doesnt seem to do anything either

**Comment by blurymind** [comment]
I understand now - I just need to add an extra if case to make it work.  But how do I grey out the item?

**Comment by blurymind** [comment]
sorry if that is the intended design - I will close this issue.

**Comment by akien-mga** [comment]
That's not the intended design, see my above comment: https://github.com/godotengine/godot/issues/5683#issuecomment-232563158

**Comment by blurymind** [comment]
ah I see. Thank you for looking into this and also providing a temporary workaround. If they store a disabled state - then I can check the state with an ifcase before triggering the events that are in the  signal.

**Comment by blurymind** [comment]
@reduz thank you! :)
