### ISSUE TITLE
NavigationAgent: drastic drop in framerate when adding Node NavigationAgent

### ISSUE THREAD

**Issue by thoced** [godotengine/godot#56838]
### Godot version

3.5 beta 01

### System information

Windows 10, GLES3, NVIDIA

### Issue description

When adding the Node NavigationAgent, the framerate drops drastically for no reason. I publish a small scene for the tests. The NavigationAgent, according to the documentation, must be one of the child nodes of the Navigation node. To carry out the test, two tests must be carried out. One using the NavigationAgent and the second test by deleting it in the tree.

The VSYNC is set to FALSE to better observe the difference

### Steps to reproduce

- Test with NavigationAgent and see the FPS
- Test without NavigationAgent (delete node) and see th FPS

### Minimal reproduction project

[NavigationAgentTest.zip](https://github.com/godotengine/godot/files/7877102/NavigationAgentTest.zip)

**Comment by rpgray** [comment]
Just wanted to say I have been waiting for you to open this issue since you posted the previous one. :)
I'm experiencing similar troubles with NavigationAgent. Simply having it in my scene attached to a KinematicBody2D, even without any pathfinding code running, it drops my fps from a stable 60 to around 45 (rising and dipping constantly) and causes all movement to jitter and stutter.
This includes a different KinematicBody2D that is using the old GetSimplePath() workflow, which works just fine once the NavigationAgent node is deleted.

**Comment by thoced** [comment]
> 

Yes indeed, I have the same problem. Even without path search, without NavigationMeshInstance placed, simply with the NavigationAgent node in the scene and it's the FPS that drops directly

**Comment by tomkun** [comment]
Can confirm, `process` frame time jumps to ~70ms.
In my use case Agent is not part of the Navigation subtree, and the performance drop happens specifically on `set_navigation()` call.

**Comment by Scony** [comment]
Cannot repro on `3.x` on bef2e3d90e9a77fb9c501dd1bf8090f864a52b72 on x86_64 manjaro linux

**Comment by Huckler** [comment]
Also confirming - same issue in everything I try. My own games, demo games, repros, all of it.

**Comment by akien-mga** [comment]
I can't reproduce the issue either on Linux with the reproduction project in https://github.com/godotengine/godot/issues/56838#issue-1105063387, neither with 3.5 beta 1 nor `3.x` (e17af68da).

I have a stable 1420 FPS with or without the NavigaationAgent node in the scene.

**Comment by mhilbrunner** [comment]
I can reproduce it on Windows 10/NVIDIA. Without I have a stable 2700-2800 FPS without any large fluctuations, with the node its constantly changing between 1200-1900 FPS.

**Comment by pycbouh** [comment]
Can't reproduce on Windows 10 with AMD Radeon 5700 XT. Stays around 3k FPS with or without the `NavigationAgent` node. However, what does kill FPS for me is moving the mouse. Just waving the cursor inside of the window takes around 1k FPS. That's likely unrelated, but very curious.

**Comment by trollodel** [comment]
Something similar was already reported: #50448

**Comment by lawnjelly** [comment]
On Linux Mint 20, latest 3.x with a 120x120 window I get:
Without the node: 3600 fps
With the node: 2900 fps

Reason for the small window, with a big window you are just testing your fill rate (and mine is low with integrated GPU).

One possible is reading back info from the navigation server, this could be stalling, maybe on some OS more than others.

**Comment by tomkun** [comment]
I've tested the 2D version on Ubuntu 21.10 as well and couldn't reproduce the issue. 
On my windows machine, however, the problem has 100% repro rate.
Tested on 3.5 beta1 b9b23d22 on both systems.

![image](https://user-images.githubusercontent.com/4152969/151663648-cb028a03-4fb1-4bf0-b652-4f5ca4bb5825.png)

Minimal repro: [3.5-beta1_nav.zip](https://github.com/godotengine/godot/files/7963811/3.5-beta1_nav.zip)

**Comment by Nukiloco** [comment]
I'm actually currently having this issue with NavigationAgent nodes. Just placing one down cause the FPS to tank a lot though the amount NavigationAgent nodes does not take the FPS further which is strange?

> Can't reproduce on Windows 10 with AMD Radeon 5700 XT. Stays around 3k FPS with or without the `NavigationAgent` node. However, what does kill FPS for me is moving the mouse. Just waving the cursor inside of the window takes around 1k FPS. That's likely unrelated, but very curious.

Moving around the mouse also causes the FPS to drop even further which is seriously strange.

I'm currently using Windows as well.

**Comment by SlothDevLlama** [comment]
It also took me quite some time tracking the issue down, since the lag spikes happen on the idle frame (at least for me).
I thought it might be interesting to see the profiler just for consideration:

![image](https://user-images.githubusercontent.com/1180429/153731798-afc373bb-3162-43b6-adac-f4593a311c1d.png)

**Comment by Defaultsound** [comment]
I've also come across this issue. It also seems increasing the "Physics Tick Per Second" also will affect the rate at which the framerate will tank. Even with no logic on the NavigationAgent3D, over time the Physics process will go up and up in ms.

**Comment by macryc** [comment]
Just raised this under Godot 4.0 alpha 6. Same issue but it's not tracked under 4.0 milestone.

**Comment by lethiandev** [comment]
I did some investigation and it might be an issue with `thread_process_array` on Windows. I've replaced some code in `NavMap::step` method to update the maps in single threaded manner.
```cpp
void NavMap::step(real_t p_deltatime) {
	deltatime = p_deltatime;
	if (controlled_agents.size() > 0) {
		for (size_t i(0); i < controlled_agents.size(); i++) {
			controlled_agents[i]->get_agent()->computeNeighbors(&rvo);
			controlled_agents[i]->get_agent()->computeNewVelocity(deltatime);
		}
		// thread_process_array(
		// 		controlled_agents.size(),
		// 		this,
		// 		&NavMap::compute_single_step,
		// 		controlled_agents.data());
	}
}
```
With this simple change NavigationAgent no longer stutters my project. Also I've noticed that the problem with `thread_process_array` is less noticeable with disabled vsync on my setup.

Replaced `thread_process_array` with "single threaded mode" and **vsync off** -
![image](https://user-images.githubusercontent.com/5323129/163059181-dfc37a7e-27c8-4d03-88e3-b6514528c272.png)

Using `thread_process_array` with **vsync off** (notice the spikes on beginning only) -
![image](https://user-images.githubusercontent.com/5323129/163059749-c919cfa8-4694-4d23-9f0a-31bc5dd78814.png)

Using `thread_process_array` with **vsync on** -
![image](https://user-images.githubusercontent.com/5323129/163060090-1350f00c-87b3-41c9-b2a2-73d60b02b284.png)
