### ISSUE TITLE
3d: is_on_floor always returns false

### ISSUE THREAD

**Issue by meesha7** [godotengine/godot#56836]
### Godot version

4.0.dev.calinou [5a61822d7]

### System information

Fedora 35 Vulkan

### Issue description

`is_on_floor` never return `true` when the player collides with the floor, using the template player script.

### Steps to reproduce

- Run the scene
- Because `is_on_floor` never returns `true`, `motion_velocity.y` will grow and the motion in other directions won't work

### Minimal reproduction project

[is_on_floor_bug.zip](https://github.com/godotengine/godot/files/7876890/is_on_floor_bug.zip)

**Comment by fabriceci** [comment]
You have set the motion mode to "Free" meaning, it's a game without ground (like a top-down in 2D) all the collisions will be reported as a wall.

![Screenshot 2022-01-16 at 15 44 07](https://user-images.githubusercontent.com/6397893/149664911-dde2d8d6-f3c1-43c2-939a-a84757e2462b.png)

Just keep the default value "grounded".

**Comment by Calinou** [comment]
Should the "Free" motion mode be renamed to "Floating" perhaps?

**Comment by fabriceci** [comment]
@Calinou "floating" sounds better indeed as it describes well the effects (collision are always walls, no acceleration on the slopes. At first, I thought to something like "_no gravity_" but I wasn't sure it would be clear to users, I'm not very good at finding names :).

Is the label clear to you (I'm biased as I'm used to it)?

**Comment by Calinou** [comment]
> Is the label clear to you (I'm biased as I'm used to it)?

The current label is OK to me, but it may not be very explicit to a newcome.
