### ISSUE TITLE
Unstable framerate with version 3.5 beta 1

### ISSUE THREAD

**Issue by thoced** [godotengine/godot#56834]
### Godot version

3.5 beta 01

### System information

Windows 10, GLES3, NVIDIA

### Issue description

A simple scene played on the 3.5 beta 01 version does not keep a stable refresh level while the scene is displayed with a stable framerate on the stable 3.4.2 version

Version 3.4.2 Stable:
https://user-images.githubusercontent.com/10273261/149656993-64b1dc0f-ba91-4903-b59e-cfe2b3af42bf.mp4

Here the FrameRate is at 60 FPS

Version 3.5 beta 01:
https://user-images.githubusercontent.com/10273261/149656995-46517259-f8b8-421a-aeab-fa66ea95c52e.mp4

Here the FrameRate runs between 40 and 58 FPS (Attention a loss of the frame rate is due to the recording via obs studio)

### Steps to reproduce

Add two MeshInstance with AnimationPlayer 

### Minimal reproduction project

[navigationtest.zip](https://github.com/godotengine/godot/files/7876791/navigationtest.zip)

**Comment by akien-mga** [comment]
A minimal reproduction project would be really helpful for contributors to reproduce and fix the issue.

**Comment by thoced** [comment]
> A minimal reproduction project would be really helpful for contributors to reproduce and fix the issue.

Hello, here I have just added a small project  "navigationtest.zip". Thanks

**Comment by akien-mga** [comment]
I can't seem to reproduce the issue here on Linux. No noticeable performance difference between 3.4.2-stable and 3.5-beta1 (with vsync disabled to see how far it reaches):

```
$ vblank_mode=0 ~/Projects/godot/stable/3.5/Godot_v3.5-beta1_x11.64 --print-fps
Godot Engine v3.5.beta1.official.b9b23d222 - https://godotengine.org
Requested V-Sync mode: Disabled
ATTENTION: default value of option vblank_mode overridden by environment.
ATTENTION: default value of option vblank_mode overridden by environment.
Found discrete GPU, setting DRI_PRIME=1 to use it.
Note: Set DRI_PRIME=0 in the environment to disable Godot from using the discrete GPU.
ATTENTION: default value of option vblank_mode overridden by environment.
OpenGL ES 3.0 Renderer: AMD VEGAM (DRM 3.42.0, 5.15.14-desktop-1.mga9, LLVM 13.0.0)
Async. shader compilation: OFF
 
Project FPS: 2 (500.00 mspf)
Project FPS: 4 (250.00 mspf)
Project FPS: 284 (3.52 mspf)
Project FPS: 288 (3.47 mspf)
Project FPS: 290 (3.44 mspf)
Project FPS: 291 (3.43 mspf)
Project FPS: 287 (3.48 mspf)
Project FPS: 285 (3.50 mspf)
Project FPS: 285 (3.50 mspf)
Project FPS: 289 (3.46 mspf)
Project FPS: 291 (3.43 mspf)
Project FPS: 290 (3.44 mspf)
```

```
$ vblank_mode=0 ~/Projects/godot/stable/3.4/Godot_v3.4.2-stable_x11.64 --print-fps
Godot Engine v3.4.2.stable.official.45eaa2daf - https://godotengine.org
ATTENTION: default value of option vblank_mode overridden by environment.
ATTENTION: default value of option vblank_mode overridden by environment.
Found discrete GPU, setting DRI_PRIME=1 to use it.
Note: Set DRI_PRIME=0 in the environment to disable Godot from using the discrete GPU.
ATTENTION: default value of option vblank_mode overridden by environment.
OpenGL ES 3.0 Renderer: AMD VEGAM (DRM 3.42.0, 5.15.14-desktop-1.mga9, LLVM 13.0.0)
OpenGL ES Batching: ON
 
Project FPS: 1 (1000.0 mspf)
Project FPS: 1 (1000.0 mspf)
Project FPS: 215 (4.6 mspf)
Project FPS: 287 (3.4 mspf)
Project FPS: 290 (3.4 mspf)
Project FPS: 291 (3.4 mspf)
Project FPS: 288 (3.4 mspf)
Project FPS: 285 (3.5 mspf)
Project FPS: 285 (3.5 mspf)
Project FPS: 288 (3.4 mspf)
Project FPS: 290 (3.4 mspf)
Project FPS: 291 (3.4 mspf)
Project FPS: 287 (3.4 mspf)
```

Also tested with Intel HD 630, both versions give ~160 FPS.

**Comment by thoced** [comment]
I took the test again and found that I had no more problems. The problem came from the NavigationAgent node that I deleted before publishing my project. I think this problem can be removed. I'll post another example with the issue that the framerate drops drastically when a NavigationAgent is added to the scene.

thank you for the answer

**Comment by Calinou** [comment]
Superseded by https://github.com/godotengine/godot/issues/56838.
