### ISSUE TITLE
Can not find member properties name with dash and lower case

### ISSUE THREAD

**Issue by TyTYct** [godotengine/godot#56840]
### Godot version

3.4.2 Stable

### System information

Windows 11

### Issue description

I have property name is V_b_Paused but can not find this properties with copy that name when I run project
In Godot 3.3 is not has this issue. I think this issue is new feature in Godot 3.4 but I can find what property in setting to turn off this.
I am sorry for my bad english.
![image](https://user-images.githubusercontent.com/8284805/149665641-5063d897-4333-4727-996c-7f2ee4bbbb85.png)

### Steps to reproduce

1. add new variable
var V_b_Paused : bool = false
2. run project
3. find new variable in filter property

![image](https://user-images.githubusercontent.com/8284805/149665486-78cfbfe1-9ac6-4e24-b9f9-61fcc3dad47c.png)

**Comment by Calinou** [comment]
> In Godot 3.3 is not has this issue. I think this issue is new feature in Godot 3.4 but I can find what property in setting to turn off this.

This is likely a consequence of https://github.com/godotengine/godot/pull/33123. You need to search for "v b paused" (case-insensitive) instead.
