### ISSUE TITLE
OptionButton already has items. Per code added items are persisted in the scene on save in godot editor

### ISSUE THREAD

**Issue by dionysius** [godotengine/godot#56851]
### Godot version

3.4.1

### System information

Windows 10

### Issue description

I was wondering why my option button got more and more items. The godot editor does not offer to set the items in the editor, so I'm forced to use code. So on _tree_entered I add those wished items.

After saving the project the scene seems to have those items persisted.

### Steps to reproduce

1. Open my MRP in godot
2. Debug play it
3. Click on "show options" button
4. Open the OptionBox
  4a. You'll see more than just 3 items
5. Close the debug play
6. Save the project (Ctrl-S)
7. Close godot editor
8. show the `git diff`
  8a. You'll see the added items are persisted in the scene file for the OptionBox

```diff
λ git diff
warning: LF will be replaced by CRLF in Control.tscn.
The file will have its original line endings in your working directory
diff --git a/Control.tscn b/Control.tscn
index 73d695f..3100ca4 100644
--- a/Control.tscn
+++ b/Control.tscn
@@ -66,7 +66,7 @@ margin_top = 18.0
 margin_right = 120.0
 margin_bottom = 38.0
 text = "Third"
-items = [ "First", null, false, 0, null, "Second", null, false, 1, null, "Third", null, false, 2, null ]
+items = [ "First", null, false, 0, null, "Second", null, false, 1, null, "Third", null, false, 2, null, "First", null, false, 3, null, "Second", null, false, 4, null, "Third", null, false, 5, null ]
 selected = 2```
```

![screenshot 145](https://user-images.githubusercontent.com/1341084/149677575-3e2b97a8-78a5-460e-ae7a-784a4ba92d66.jpg)

### Minimal reproduction project

https://github.com/dionysius/issue-godot-optionbutton

**Comment by pycbouh** [comment]
1. You have a tool script. Tool script runs in the editor. Every time you open the scene in the editor, that code runs and adds the items.
```
func _on_OptionButton_tree_entered():
	print("now in tree_entered")
	var opt = get_node(OptionButtonPath) as OptionButton
	print(OptionButtonPath, opt)

	print("existing items:", opt.get_item_count())

	opt.add_item("First")
	opt.add_item("Second")
	opt.add_item("Third")
	opt.selected = 2
```

2. You can in fact edit items in the editor. There is a menu on top of the viewport when you have the node selected, called Items.

**Comment by dionysius** [comment]
I think it's the `tool` keyword's fault. According to the [docs](https://docs.godotengine.org/en/stable/tutorials/misc/running_code_in_the_editor.html)

> Modifications in editor are permanent. For example, in the following case, when we remove the script, the node will keep its rotation. Be careful to avoid making unwanted modifications.

**Comment by pycbouh** [comment]
Yes, that's the point of the tool keyword, to run in the editor. The edited scene is fully loaded and functional, so running a tool script on it modifies it. If you then save it (and running the scene automatically saves it), everything your tool script did is also saved.
