### ISSUE TITLE
Node Addon parent won't list the Addon when searched on Node list

### ISSUE THREAD

**Issue by henriquelalves** [godotengine/godot#5686]
**Operating system or device - Godot version:**
Linux Mint 17.2 Cinnamon 64-bit - Godot 2.1 Beta

**Issue description**
After activating a Node kind of Addon, the node the Addon inherits from won't show it's children (the Addon) when searching for the Addon parent.

For example (and in the case I tested): a Node Addon that inherits from ReferenceFrame will appear on the Node list, but if you search for ReferenceFrame, the Node Addon won't be listed as a child.

**Steps to reproduce:**
I tested using the Addon I created before: https://github.com/henriquelalves/GodotTIE
Just activate the Addon and search for "ReferenceFrame" on the Node list.

**Comment by bojidar-bg** [comment]
@henriquelalves Does it work for, e.g., searching for `Node2D` and seeing `Position2D`?

**Comment by henriquelalves** [comment]
Yeah, for normal nodes it works as intended (you can see its children when you search for the parent). Only for the addon nodes that this problem seems to happen.

**Comment by DualMatrix** [comment]
Still relevant in master. Tested with the new class_name instead of Addons
