### ISSUE TITLE
Collapsing / expanding node lists using the arrow keys

### ISSUE THREAD

**Issue by henriquelalves** [godotengine/godot#5687]
It's a simple thing, but since navigation on the list is possible using the Up / Down arrow keys, expanding and collapsing using the Left / Right arrow keys is the next intuitive thing people will try to do.

**Comment by blurymind** [comment]
that would be quite nice to have! :)

**Comment by AlexHolly** [comment]
With node lists you mean the SceneTree?
I can use Left/Right arrow key on master.

**Comment by henriquelalves** [comment]
Yeah, I just checked and Master has this is implemented now - I'll be closing the issue.
