### ISSUE TITLE
GDScript 2.0: Enum comparison causes `Invalid operands` error when function is using the enum as type hint

### ISSUE THREAD

**Issue by BeayemX** [godotengine/godot#56878]
### Godot version

v4.0.dev.custom_build [846c14eee]

### System information

Linux Mint - Vulkan API 1.2.131 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1080

### Issue description

Comparing a value against an enum-value only works if the function does not use that enum as a type hint.

See the example code-snippet for a better understanding of the issue.

Error message:
```
Parser Error: Invalid operands "Test (enum)" and "One (enum value)" for "==" operator.
```

This bug must have been introduced in the last one or two days, because this code was working before.

### Steps to reproduce

Copy this script into any project and see that you can't run it.
If you use the line above the non-working function instead, everything works as expected

```gdscript
extends Node

enum Test {
	One,
	Two
}

# func do(value): # Does work
func do(value : Test):  # Does NOT work
	if value == Test.One:
		print(value)
```

**Comment by cdemirer** [comment]
Bisection result: #55995

**Comment by EIREXE** [comment]
Still here in alpha 1, i recommend most people to yeet 0430e26e6d3688aa4c7505ad8aedcc8123d41978 out of their tree by using `git revert 0430e26e6d3688aa4c7505ad8aedcc8123d41978` in the meantime.
