### ISSUE TITLE
[Godot4] Can't new Custom Node in Thread

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#56890]
### Godot version

v4.0.dev.20220105.official [8f6cba3a4]

### System information

Window10

### Issue description

Coding like this, it work fine.
![捕获](https://user-images.githubusercontent.com/35988767/149877490-4569616f-a5fd-4c48-80f5-72d6ff66dd67.PNG)

Coding like this, the thread frozen.
![捕获](https://user-images.githubusercontent.com/35988767/149877671-4475bfce-9d04-4bb4-8699-85ed34a099dd.PNG)

My Custom Chunk Node coding:
![捕获](https://user-images.githubusercontent.com/35988767/149877783-9af5084b-6112-4e70-b3ad-d180685fd0e9.PNG)

### Steps to reproduce

Please run my reproduction project

### Minimal reproduction project
[ThreadNewTest.zip](https://github.com/godotengine/godot/files/7886621/ThreadNewTest.zip)

_No response_

**Comment by CsloudX** [comment]
Sorry, maybe it was relative https://github.com/godotengine/godot/pull/56593

**Comment by vnen** [comment]
Cannot reproduce with current master, it was probably fixed along the way.
