### ISSUE TITLE
remove_and_skip removes the children when their owner is null

### ISSUE THREAD

**Issue by LoneDespair** [godotengine/godot#56905]
### Godot version

3.3.3.stable

### System information

Windows 10

### Issue description

Calling remove_and_skip removes children too, if they don't have a set owner
Even if the current node have a parent

### Steps to reproduce

Add a parent node
Add a target node
add_child its children

remove_and_skip the target node, its children gets removed too

**Comment by Calinou** [comment]
@LoneDespair Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.
