### ISSUE TITLE
Inspector editing of small values does not work

### ISSUE THREAD

**Issue by Malcolmnixon** [godotengine/godot#56917]
### Godot version

3.4.2.stable.mono.official

### System information

Windows-10

### Issue description

I am attempting to set an exported script property to a small floating point value of -0.000002 (which happens to be a stepper-motor micro-step to meters conversion scale).

I have tried putting this value in a Vector3 and a float; and in either case the number gets truncated to 0, despite the fact it's most certainly in the range of a float which can handle values as small as 1.2E-38.

I can understand why truncation may be assumed valid for Vector3 as it's primarily used for transformation elements (position, rotation, scale, etc.) and a value of -0.000002 in a field would be unnoticeable; however raw float values could be used for anything, and the editor should not assume a legal range unless specified in a property hint. I was unable to find any property hints which may be helpful (set significant digits, etc.)

### Steps to reproduce

Add an exported float to a script and attempt to set it to -0.000002. Observe it gets truncated to zero.

**Comment by pycbouh** [comment]
Maybe related to https://github.com/godotengine/godot/issues/33095

**Comment by Malcolmnixon** [comment]
It looks like #33095 was primarily related to 64-bit integer fields, and the inspector had an editor that was artificially limited in its maximum dynamic range.

There is a section discussing float limitations and truncating to 6 significant digits regardless of decimal point location. In other words:
2147483647 => **214748**0000
9223372036854775807 => **922337**0000000000000

My issue is slightly different because the -0.000002 actually only has one digit of precision, and as such it should still work:
-0.000002 => -0.00000**200000**

**Comment by pycbouh** [comment]
Well, the root of #33095 is in the fact that numbers are converted into strings intermediately. That's where the precision gets lost. So it can still be the same here.

**Comment by kleonc** [comment]
There's `Editor Settings` -> `General` -> `Interface` -> `Inspector` -> `Default Float Step` setting you can change. Changing it to for example 0.000001 will let you set the value of a float to -0.000002 (from the inspector).

**Comment by Malcolmnixon** [comment]
Lol, spent a few hours tracking it down in the debugger to the same "default_float_step" used in editor_properties.cpp when constructing the EditorPropertyRangeHint. 

This gave me the hint to try the following annotation in my C# code:
```
    /// <summary>
    /// Direction scale for micro-steps to meters
    /// </summary>
    [Export(PropertyHint.Range, "-1.0,1.0,0.000000001")]
    private float scale = 1.0F;
```

This works; although it looks like that is the **absolute smallest** step-size permissible. If I try going any smaller than 1e-9 then the range system fails again and I just get zeros.

As I already had a 'master' build running in the debugger, I tried the same hint in GDScript using:
```
    @export_range(-1, 1, 0.00000001) var scale : float
````

Unfortunately this led me to issue #48773 where negative annotation arguments are not validated correctly by GDScriptParser::parse_annotation and GDScriptParser::validate_annotation_arguments.
