### ISSUE TITLE
Main window doesn't regain focus after dialogs on MacOS

### ISSUE THREAD

**Issue by coppolaemilio** [godotengine/godot#56922]
### Godot version

4.0.dev.20220118

### System information

macOS Monterey - 12.1 - M1 - Vulkan

### Issue description

When you do something like creating a node or a script where it involves filling out a dialog, the focus never returns to the editor, so you can't do anything until you click on the editor again.

After closing a dialog the editor should regain focus.

### Steps to reproduce

- Create a scene
- Open the Add Child Node (Command + A) 
- Select a node
- Try to press Command + R to test the scene
- You will hear the error sound and you will see that the main window is not on focus.

**Comment by Calinou** [comment]
I can confirm this on ce6de717f (macOS Monterey, M1 Mac mini).
