### ISSUE TITLE
Downloaded AssetLib items are hidden

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#56928]
### Godot version

f8b8d0d

### System information

W10

### Issue description

When you download an asset, but not install it, you won't be able to install it later (until editor restart). Trying to fetch it again shows error saying that download is in progress. Well, yeah, the item was downloaded and should be available to install, but the problem is this...
![image](https://user-images.githubusercontent.com/2223172/150042767-33b5cba2-c8dc-4e7d-af10-30709d2e9227.png)
(this are the downloaded assets. Absolutely unclickable)

### Steps to reproduce

1. Open AssetLib
2. Download asset
3. Don't install it, but cancel the dialog
4. Try downloading it again

**Comment by pycbouh** [comment]
Might be because of https://github.com/godotengine/godot/pull/56842. When I was testing it, I noticed the same issue, but assumed it was something else.
