### ISSUE TITLE
Mac editor constantly losing focus

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#56938]
### Godot version

v4.0.dev.20220118.official [bc5ba38ff]

### System information

Mac OSX (Intel 2019)

### Issue description

When performing normal actions in the editor, the main window seems to lose focus causing keyboard actions like saving or running scenes to have no effect.

This happens when selecting any item which shows a dropdown menu, perhaps because Godot now seems to create a new window instance when doing so.

This also may be related to https://github.com/godotengine/godot/issues/56937

https://user-images.githubusercontent.com/100964/150105150-ba276af8-5822-4c76-ac8e-04fe322b5278.mov

### Steps to reproduce

1. Open any project
2. Click on anything which opens a dropdown menu
3. Check in the titlebar to see that the main window has now lost focus

**Comment by akien-mga** [comment]
This was likely just fixed by #56825, CC @bruvzg.

**Comment by tavurth** [comment]
@akien-mga thanks for the info, I'll check in the nightly build this evening

**Comment by tavurth** [comment]
Duplicate of https://github.com/godotengine/godot/issues/56922

**Comment by bruvzg** [comment]
Return of the focus should be fixed, but popups still take focus when are opened (should not be an issue by its own, there's a flag to make window unfocusable, but it's set only for tooltips).
