### ISSUE TITLE
Mac crash when hovering on toolbar items in fullscreen

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#56937]
### Godot version

v4.0.dev.20220118.official [bc5ba38ff]

### System information

Mac OSX (Intel 2019)

### Issue description

When hovering over the file, view menu etc at the top of the screen the currently selected menu keeps changing causing a kind of flicker.

When then making the Godot editor window fullscreen, clicking on any toolbar item will crash the engine.

https://user-images.githubusercontent.com/100964/150102373-5b35fdef-22cd-4929-a796-5823b7cbecb7.mp4

### Steps to reproduce

1. open any project in Mac OS (Godot 4)
2. Click on the top menu buttons

**Comment by akien-mga** [comment]
This was possibly just fixed by #56825, CC @bruvzg.

**Comment by tavurth** [comment]
@akien-mga thanks for the info, I'll check in the nightly build this evening

**Comment by bruvzg** [comment]
Yes, this should be fixed by #56825 (both menu flicker and full-screen child window issues).
