### ISSUE TITLE
A way for script to determine the engine version it is running on

### ISSUE THREAD

**Issue by gau-veldt** [godotengine/godot#5693]
**Operating system or device - Godot version:**
Godot v2.1.beta

**Issue description** (what happened, and what was expected):
When the editor is first started it displays the Godot version in the project selection window (eg: v2.1.beta or v2.1.beta.custom_build when git-n-scons'ed).  As pointed out on FB there is no current way for a script to determine the Godot version it is running on.  It would be according to Rémi Verschelde on FB, "easy to add and a good idea" to add a method somewhere a script may access to obtain this information.

**Steps to reproduce:**
```
# sample interface for obtaining version
func getGodotVersion():
    # OS object seems to be a good choice
    return OS.get_engine_version()  # this method currently does not exist
```

**Comment by akien-mga** [comment]
I'll work on it, it should be trivial to do. The main difficulty is to decide what class should expose this method; `OS` comes to mind indeed, though the engine version is not particularly an OS-specific function.

**Comment by SuperUserNameMan** [comment]
maybe this new ``OS.get_engine_version()`` (or a sibling of it) could return all the version information (major, minor, submunor, custom/beta/alpha/stable) into an array ?

**Comment by gau-veldt** [comment]
@akien-mga (Ahh, you're Remi) Yeah I thought about "which should expose" also.  I thought of VisualServer but it seemed a bit lopsided to have it there (as in if it's there why not also be able to ask the physics, streaming, etc servers for their versions... ... ...)  OS seems to be a common root that prevents that madness.

Godot is originally run from the OS.  OS implements "environment" and that the executable running under that "environment" implements a version in the extended virtual "environment" of scripts being run by that executable.  That's my justification for it being in OS.

If the argument against OS is "things only form the OS should be there" then MainLoop might be better since not only is it a common root (except the docs for MainLoop seem to suggest overriding MainLoop is possible thus possibly losing access to the version method), but is also related to the executable (application) itself without being part of "things only from the OS".

The array suggestion feels like overkill.  We can just use String.split(".").  Really. ;)

**Comment by gau-veldt** [comment]
Junior job...
Does that translate as "worthwhile task for anyone wanting to get a feel for working with Godot sources, git, etc (perhaps to later make a plugin)"?

**Comment by vnen** [comment]
> Junior job...
Does that translate as "worthwhile task for anyone wanting to get a feel for working with Godot sources, git, etc (perhaps to later make a plugin)"?

That's what "Junior Job" means indeed. But @akien-mga already said he'll work on it and assigned to himself, so this task is already taken. There are a bunch of [other junior jobs](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+label%3A%22junior+job%22) though.

**Comment by salvob41** [comment]
Does this API endpoint work ? I am not finding it

**Comment by mrcdk** [comment]
It was moved to `Engine` https://docs.godotengine.org/en/3.0/classes/class_engine.html#class-engine-get-version-info @salvob41
