### ISSUE TITLE
set_locale() has no effect on Control nodes

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#56945]
### Godot version

7a88f5c

### System information

W10

### Issue description

Seems like Controls no longer auto-translate when locale changes:
![godot windows tools 64_N74JEyqnHJ](https://user-images.githubusercontent.com/2223172/150139239-5b467c4c-bf23-4876-8dd0-b09396c09482.gif)
(for whatever reason it also clears the title of main window)

In 3.x:
![godot windows opt tools 64_EUWBl9UB8A](https://user-images.githubusercontent.com/2223172/150139263-5fbda421-ddf4-4253-80d0-f4ef5ff09cbb.gif)

### Steps to reproduce

1. Add control with text
2. Add translation
3. Change locale

### Minimal reproduction project

[LocaleBug.zip](https://github.com/godotengine/godot/files/7897434/LocaleBug.zip)

**Comment by Zireael07** [comment]
3.x has "cig" instead of "ciąg" LOL

**Comment by Calinou** [comment]
> 3.x has "cig" instead of "ciąg" LOL

For reference, this is because the default project font in `3.x` has a more limited character set (only basic Latin-1).
