### ISSUE TITLE
`string.Capitalize` has different behavior in C#

### ISSUE THREAD

**Issue by zaevi** [godotengine/godot#56941]
### Godot version

4.0, 3.x

### System information

Win10

### Issue description

```csharp
"MyNode".Capitalize();
```
It returns `Mynode` in C#, but `My Node` (in GDScript) is expected.

### Steps to reproduce

above

**Comment by raulsntos** [comment]
The behavior of `capitalize` used to be like that but changed in #12932 to add spaces and it was never updated in C#.
