### ISSUE TITLE
CI doesn't catch unit test failure on Windows

### ISSUE THREAD

**Issue by YuriSizov** [godotengine/godot#56942]
### Godot version

master

### System information

GitHub Actions

### Issue description

I've recently ran into issues with my PR that caused some unit test runs to fail on CI. I initially thought that the problem was localized to MacOS and Linux, but upon running tests locally on Windows I found out it was affected as well. However, on CI the tests either didn't run, or didn't report anything.

Mac: https://github.com/godotengine/godot/runs/4866470574?check_suite_focus=true
Linux: https://github.com/godotengine/godot/runs/4866474222?check_suite_focus=true
Windows: https://github.com/godotengine/godot/runs/4866470448?check_suite_focus=true

In case the links are no longer available, here's what it looks like for the [mac](https://user-images.githubusercontent.com/11782833/150125185-8659347d-a6a3-4da1-a027-b1c95e1909f7.png), and here's what [windows](https://user-images.githubusercontent.com/11782833/150125327-6990dbf1-040b-4b11-87a7-8046552a7775.png) shows. Again, locally tests fail the same as they should on other platforms (running through Windows Terminal, so essentially in PowerShell).

### Steps to reproduce

See above.

### Minimal reproduction project

N/a

**Comment by YuriSizov** [comment]
@brno32 Not sure, haven't looked into it in a while. Checking latest master builds I can see that tests do appear to be running on Windows just as well as on other platforms. So probably not an issue anymore. But would be nice to confirm. You can probably try to break the tests on purpose and then check in your fork what it looks like on CI.

**Comment by akien-mga** [comment]
Probably fixed by #76887.
