### ISSUE TITLE
Tooltips blinking

### ISSUE THREAD

**Issue by jarfil** [godotengine/godot#5695]
This is a duplicate of previous issues which have been closed without fully fixing the problem (#1959 #3835 #4667 #4686 #4713).

**Operating system:**
Windows 10 Pro 64bit 1511 Build 10586.420

**Godot versions:**
* 2.0.4.1 stable 32bit
* 2.0.4.1 stable 64bit
* 2.1-beta 20160712 32bit
* 2.1-beta 20160712 64bit

**Issue description:**
Tooltips on buttons blink on and off when mouse is not moving.
Tooltip stops blinking if mouse is moved, but only as long as the mouse pointer stays over the element that initially showed the tooltip.
Tooltip state stays unchanged, whether on or off, as long as the mouse keeps moving.
When mouse stops moving, the tooltip starts flashing again.
Sometimes, when switching to another application, the tooltip stays on in the Editor.
Sometimes, tooltips just won't disappear even when the mouse pointer is over other parts of the interface.
Changing tooltip_delay to a high value (like 10 seconds) may prevent tooltips from showing at all.

![Tooltip blinking](http://i.imgur.com/RgLpW30.gif)
Video: https://www.youtube.com/watch?v=4tgtaQ0cLUo

**Steps to reproduce:**
Create a project
Open project in editor
Mouse over any button with a tooltip
Leave mouse pointer over the button
Tooltip regularly blinks on and off
Slightly move the mouse over the button
Tooltip stops flashing
Stop moving the mouse
Tooltip starts flashing again

Alt+Tab to another application
Mouse over any button with a tooltip
Just as tooltip shows, rapidly move mouse outside of Editor window
Tooltip stays visible, without flashing

**Link to minimal example project**
Behavior shows with empty project
Default tooltip_delay is 0.7 sec.

**Suspected culprits**
The software "CleanMem Mini Monitor Free" seems to enable this behavior on Windows 8.1 (but is not the only one).
The behavior seems to be related to root window handling, and/or mouse event handling.
Suspicious code lines at https://github.com/godotengine/godot/blob/master/scene/main/viewport.cpp#L2275
```
	if (gui.tooltip == p_control)
		gui.tooltip=NULL;
	if (gui.tooltip == p_control) {
		gui.tooltip=NULL;
		_gui_cancel_tooltip();
	}
```
(the second `if` seems to be a failed copy&paste, I'm not really sure what would be the correct way to fix it)

**Notes**
The blinking detected on Windows 10 is slower, and has a different pattern, than that detected under Windows 8.1.
Blinking speed seems to depend on something external to Godot.

**Comment by bojidar-bg** [comment]
@jarfil Can you setup the following script on a node:
````gdscript
extends Node
func _ready():
    set_process_input(true)
func _input(event):
    if event.type == MOUSE_MOTION:
        print(event.relative_pos)
````

Then report if it repeatedly prints `0, 0` when staying at one place :smile: 

(This is to confirm an old hypothesis of mine)

**Comment by jarfil** [comment]
@bojidar-bg Indeed, it does print `0, 0` when staying at one place.

It seems to print it once every second, like on some timer.
It prints it a seemingly random number of times, but it seems to start with once a second and then if I move the cursor out of the window and back, it starts printing several '0, 0' per tick.

I've used this script to check it:
```gdscript
extends Node
func _ready():
	set_process_input(true)
func _input(event):
	if event.type == InputEvent.MOUSE_MOTION:
		print(str(get_node("Timer01").get_wait_time()-get_node("Timer01").get_time_left(), " ", event.relative_pos))
```

Project: [godot-test01.zip](https://github.com/godotengine/godot/files/364354/godot-test01.zip)
Log: [log01.txt](https://github.com/godotengine/godot/files/364356/log01.txt)

**Comment by jarfil** [comment]
I've found that removing the `gui.tooltip_popup` check from `Viewport::_gui_remove_control` https://github.com/jarfil/godot/commit/17589a174a70fc8e4afc554916005ef1a7c40bf4 solves the blinking issue... but, is that the best way to solve this?

Why was the check in there in the first place? All it seems to do is duplicate a call to `Viewport::_gui_cancel_tooltip`, which is why the blinking seems to be happening. Is there any other case when the `gui.tooltip_popup` check would be needed?

**Comment by bojidar-bg** [comment]
@reduz Can you have a look at the above comment, since I'm unable to guess why the check would fix this.

**Comment by jarfil** [comment]
Seems like disabling the check "fixes" this because a `_gui_remove_control` is called after `_gui_show_tooltip` detects the `gui.tooltip_popup` and unceremoniously `memdelete`s it.

I've tried another way of solving this https://github.com/jarfil/godot/commit/b15b64785eb4c87b7be84e3b952efb7677a984ba by checking in `Viewport::_gui_show_tooltip` whether the new `tooltip` text is the same as the one shown in the current `gui.tooltip_label`.
However that doesn't address the timer starting in the first place.

The same check, performed in `_gui_input_event`'s `MOUSE_MOTION` section to prevent restarting the timer if the same tooltip is shown, seems like a candidate solution https://github.com/jarfil/godot/commit/955d9e122d96e4a6147e7a5b3474c5a25689c365
This leaves tooltips visible until the mouse pointer leaves the control... which is not the best solution for controls with multiple tooltip positions, like the resource panels.
