### ISSUE TITLE
Can't build vsproj with Visual Studio 2022 and Scons 4.2

### ISSUE THREAD

**Issue by rossunger** [godotengine/godot#56968]
### Godot version

main, 3.4

### System information

Windows 10, Visual Studio 2022 

### Issue description

I was having trouble building  vsproj files with 
scons p=windows vsproj=yes

SOLUTION:
Turns out it was a SCONS issue... here is a link to the comment which solved the the issue for me:
https://github.com/SCons/scons/issues/3988#issuecomment-926207871

I know it's not a godot issue, but I had a hard time with it, and figured someone else here might appreciate the solution! Is there a better place to post this kinda thing? (I'm very new to working with other people and contributing to projects)

### Steps to reproduce

Visual Studio 2022, Scons 4.2

running "scons p=windows vsproj=yes" throws errors.

**Comment by willnationsdev** [comment]
@rossunger Just wanted to comment and say thanks. I am getting back into Godot dev after a long break and ran into immediate issues getting build tools to run properly. You helped me diagnose and fix it. Cheers!

**Comment by wangafei** [comment]
scons platform=windows dev_build=yes vsproj=yes
error   -ologo
