### ISSUE TITLE
Modified built-in resources are not saved in inheritted scenes if parent is open.

### ISSUE THREAD

**Issue by FreegleBarr** [godotengine/godot#56974]
### Godot version

4.0.dev.custom_build.249c60e9d/ 3.4.2.stable.official

### System information

Ubuntu 20.04

### Issue description

possibly related: #27243, #55964,  #7984

If scene B inherits from scene A, and A has a sub-resource, when both are open, if changes to the sub-resource are updated and saved in B, then the changes to the sub-resource are applied to A in the editor, but are not actually saved until A is saved(which is not communicated by the * on the tab).

This can(and has!) lead to a lot of lost work if working on shaders or animations, for example.

### Steps to reproduce

* Create a scene A with some sort of built-in sub-resource, then create a inherited Scene B from A.
* Keep both scenes open.
* Modify the sub-resource in scene B and save only scene B.
* Scene A will now display modified sub-resource.
* Quit and reload the project without saving A.
* Scene A and B will now have the unmodified resource.

### Minimal reproduction project

[subresource_bug.zip](https://github.com/godotengine/godot/files/7900476/subresource_bug.zip)

**Comment by KoBeWi** [comment]
Editing foreign resources is no longer possible, so this is resolved.
