### ISSUE TITLE
Line2D has an black outline

### ISSUE THREAD

**Issue by devlein** [godotengine/godot#56973]
### Godot version

v4.0.dev.20220118.official [bc5ba38ff]

### System information

Windows 11, Vulkan, AMD Vega 8

### Issue description

On 4.0 any Line2D has an black outline, even the lines drawn by the editor itself. This is clearly visible when zoomed in:

![grafik](https://user-images.githubusercontent.com/72512377/150209752-6664b305-a0dd-43a1-abfc-930091fc81ce.png)
Left: v3.5.beta1 - Right v4.0.dev.20220118

It seems to be a Vulkan only problem (both clustered & mobile), GLES3 has no outline.

As a side note: 4.0 is also missing antialiasing.

### Steps to reproduce

Create an Line2D

**Comment by Calinou** [comment]
This is likely caused by sharpening being enabled in your graphics driver. AMD has such an option in its Adrenalin control panel.
