### ISSUE TITLE
NavigationServer.region_set_layers is missing

### ISSUE THREAD

**Issue by Xyotic** [godotengine/godot#56982]
### Godot version

3.5-beta1_mono

### System information

Windows 10, Vulkan, RTX2080

### Issue description

The new NavigationServer is missing the "region_set_layers" method described in the documentation:
https://docs.godotengine.org/en/latest/classes/class_navigationserver3d.html?highlight=navigationserver#class-navigationserver3d-method-region-set-layers

Also the "map_get_path" function is missing the "layers" parameter.

Maybe this is just an issue with the documentation and not the engine itself.

### Steps to reproduce

Create a script -> try to access NavigationServer.region_set_layers

**Comment by Calinou** [comment]
> Maybe this is just an issue with the documentation and not the engine itself.

Check the in-editor class reference to see if the properties/methods are present there. If this is the case, this means the online class reference is outdated.

**Comment by Xyotic** [comment]
> > Maybe this is just an issue with the documentation and not the engine itself.
> 
> Check the in-editor class reference to see if the properties/methods are present there. If this is the case, this means the online class reference is outdated.

This seems to be the case.
Just looked it up in the in-editor class reference.
The online class reference is outdated.

**Comment by Scony** [comment]
@Xyotic you're looking at the `master` documentation while using `3.x`. The layers were not backported to `3.x` on purpose so everything they relate to is not visible in `3.x`. Thus everything is as expected :)

**Comment by akien-mga** [comment]
Indeed it's as @Scony says. The `3.5` docs are not online yet, we first need to branch off `3.4` and create a new branch for it.
