### ISSUE TITLE
dear imgui (ImGui) Integration

### ISSUE THREAD

**Issue by EdwardAngeles** [godotengine/godot#5699]
Hi. So I came across this images (at the bottom) that use imgui for quick debugging in game. I'm been looking into imgui and it seems to be a really nice approach to test stuff in game. Like switching states in a FSM, scroll-bars for, I don't know, setting a scale or the health. You name it it, I think they are really useful.

I know you guys are already very busy. But I just wanted to drop this idea in here.

Here is [dear imgui](https://github.com/ocornut/imgui) which is "Bloat-free Immediate Mode Graphical User interface for C++ with minimal dependencies" and uses MIT License. So since it's in C++, would it be difficult to integrate it into godot? (I really don't know)

Anyways, what you guys think?

![](https://pbs.twimg.com/media/CnUNmiyUEAAsbLD.jpg)
(ignore the shapes...)

![](https://pbs.twimg.com/media/CnUONgaW8AAbJNk.jpg)

![](http://i.imgur.com/iQibpSk.gif)

**Comment by SuperUserNameMan** [comment]
so you want to replace godot's GUI with this imGUI ?

**Comment by punto-** [comment]
don't we already have this via live editing?

**Comment by EdwardAngeles** [comment]
No. ImGui is more meant for doing testing in game on the fly (during runtime). For the game gui I would totally go with godot's GUI, there is nothing wrong with it.

**Comment by ret80** [comment]
@EdwardAngeles  You can also quickly create using Godot GUI test window. it makes no sense to fasten another gooey system. although if you really need it, you can do it yourself as a module. possibly work.

**Comment by eska014** [comment]
Godot has great debugging tools built in, check the 'Debugger' tab at the bottom of the editor while running the game.
If you want something in game, you can easily build a debug window using Godot's `Control` nodes and add it e.g. as an AutoLoad node. Asset library should soon work nicely to share debug autoloads like that

**Comment by EdwardAngeles** [comment]
I personally think that ImGui are really useful for making in-game tools.

**Comment by reduz** [comment]
the Imgui approach sucks, I' m sorry. Even Unity is getting rid of it.
You can also create a GUI and make a level on the fly in Godot during the running game with live editing.

**Comment by EdwardAngeles** [comment]
So yeah... Been messing with godot's gui and they can totally do in-game tools and with the draw functions I can do graphs for visualizations. I suppose ImGui are more useful for game frameworks.

Anyways thank for hearing me out and the feedback. I guess I can close this issue.

**Comment by Zylann** [comment]
Unity is not completely getting rid of it, they still use this approach in editor tools. One advantage of this technique is that you can directly bind game states to a form (inspector) in a single line of code rather than callbacks and wiring and retained-style widgets, making it a weapon of choice for debugging and tweaking. There might be a way to use Godot's GUI this way thought. You basically have to see this as a "super-debug-draw" framework :p

**Comment by EdwardAngeles** [comment]
@Zylann That's right. I just check unity's roadmap and they are even adding new feature to their IMGUI. I don't think IMGUI just "sucks", it's just a different approach.

**Comment by neikeq** [comment]
dear imgui is really great, but Godot already has its own gui which works with the node system. You can always make a module for using imgui.

**Comment by Xrayez** [comment]
This proposal is still relevant at godotengine/godot-proposals#112 (not integrating a separate implementation of ImGui of course, but leveraging existing Godot's GUI system to greatly simplify visual debugging), feel free to chime in.
