### ISSUE TITLE
How can I use the shader's built-in variables to store adjacent vertices

### ISSUE THREAD

**Issue by Alunwalker** [godotengine/godot#56990]
### Godot version

3.4 stable mono

### System information

windows10, gles3

### Issue description

How can I use the shader's built-in variables to store adjacent vertices, I tried using arraymesh's normal and tangent, but they are automatically normalized in the vertex shader, so if I want to store the true values of adjacent vertices and use in shader, how to do?

### Steps to reproduce

`arr[(int)Mesh.ArrayType.Normal] = normal;`
`arr[(int)Mesh.ArrayType.Tangent] = tangent;`

The adjacent vertices are stored in normal and tangent. when I use it in the shader it's not the same as the value I'm storing, it seems to be limited between -1 and 1.

**Comment by Zireael07** [comment]
This is not a support forum, this is a bug tracker.
