### ISSUE TITLE
symbolic link to directory: ERROR: _scan_new_dir: Cannot go into subdir

### ISSUE THREAD

**Issue by supaiku-o** [godotengine/godot#5700]
**Operating system or device - Godot version:**
Arch Linux - 5545afd52b912722bbdb6e412cce9593857c5726

Adding a symlink to a directory to the project folder does not work and
throws
`ERROR: _scan_new_dir: Cannot go into subdir`

`At: tools/editor/editor_file_system.cpp:660.`

**Comment by laerus** [comment]
happens to me all the time atm in v2.1.3,

godot is descent on all files of my home directory,
on top of that it's trying to read arbitary xml files

```
ERROR: _scan_new_dir: Cannot go into subdir: ...
   At: editor/editor_file_system.cpp:614.
```
```
ERROR: open: Unrecognized XML File: res://Documents/python-docs/_static/opensearch.xml
```
this *seems* to happen mainly after i load a scene
i have the godot binary in `~/Godot/Godot` and the projects next to the binary `~/Godot/projects/`

**Comment by touilleMan** [comment]
#8144 has solve this issue for me, @akien-mga maybe you can close this ?

**Comment by vnen** [comment]
Will close as fixed, comment if it's not the case.
