### ISSUE TITLE
GDScript 2.0: `match` on multiple patterns doesn't work

### ISSUE THREAD

**Issue by RonanZe** [godotengine/godot#57004]
### Godot version

Godot_v4.0-dev.20220118_win64

### System information

Windows 8.1

### Issue description

Did'nt find other report and documentation about this bug, or is the documentation that is missing about a change in Godot 4?

I can't do multiple patterns match in Godot 4 like that exemple in doc of 3.x:
```
match x:
    1, 2, 3:
        print("It's 1 - 3")
    "Sword", "Splash potion", "Fist":
        print("Yep, you've taken damage")
```
[https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_basics.html#:~:text=match%20x%3A%0A%20%20%20%201%2C%202%2C%203%3A%0A%20%20%20%20%20%20%20%20print(%22It%27s%201%20%2D%203%22)%0A%20%20%20%20%22Sword%22%2C%20%22Splash%20potion%22%2C%20%22Fist%22%3A%0A%20%20%20%20%20%20%20%20print(%22Yep%2C%20you%27ve%20taken%20damage%22)](url)

to be more precise, here is the code that don't works:

```
match [StringA, StringB]:
   ['Beam', 'Wall'], ['Pillar', 'Wall']:
      ....
   ['Wall', 'Wall']
      ....
```

The fist match on the line is working but the one after the comma is not tested and so never matching.
The code works fine in 3.x

### Steps to reproduce

Use that code:

### Minimal reproduction project
[GDScript2.0_multi_patterns_match.zip](https://github.com/godotengine/godot/files/7906846/GDScript2.0_multi_patterns_match.zip)

_No response_

**Comment by Calinou** [comment]
@RonanZe Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by RonanZe** [comment]
> @RonanZe Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

Sorry, I've added a project
