### ISSUE TITLE
Script text editor "Indent Left" / "Indent Right" not working

### ISSUE THREAD

**Issue by dmaz** [godotengine/godot#57018]
### Godot version

v3.5.beta1.official [b9b23d222]

### System information

Windows 10

### Issue description

"Indent Left" and "Indent Right" no longer seem to work while worked just fine in v3.4.2-stable.

### Steps to reproduce

assign keys to "Indent Left" and "Indent Right" 
Editor > Editor Settings > Shortcuts > Script Text Editor

**Comment by Calinou** [comment]
cc @Paulb23

**Comment by dmaz** [comment]
Actually...  I had this set to the Brackets which used to be called BraceLeft and BraceRight

**Comment by dmaz** [comment]
this should be closed...
