### ISSUE TITLE
RawArray needs a slicing operation

### ISSUE THREAD

**Issue by gau-veldt** [godotengine/godot#5701]
**Operating system or device - Godot version:**
Godot v2.1.beta

**Issue description** (what happened, and what was expected):
RawArray supports adding chunks onto the end but missed an operation to obtain a copied slice of a larger RawArray to a new (smaller) RawArray.  Of course this could be done in a loop but things like that may be a bit inefficient doing in script, especially for larger RawArray's.  C++ optimized assembly FTW.

Proposed prototype (-1 means end of the array):

RawArray RawArray.slice(start,end=-1)

Copies a slice of the original RawArray and returns a new RawArray containing the subsection, from start to end (or -1 to slice to the end).

```
# example to use proposed RawArray.slice
func skipN(origRaw,N):
    # returns new RawArray with first N bytes of original RawArray skipped
   return origRaw.slice(N)
```

**Comment by gau-veldt** [comment]
If adding a bind isn't too tricky a process I could try to add this to a fork and go through the PR process.
It would be nice if there was way to make these slices without copying but I see peril in doing so.

**Comment by bojidar-bg** [comment]
@gau-veldt I think it was named ByteArray on the C++ side (or it is part of DVector)

**Comment by gau-veldt** [comment]
I need more information about where I should be looking in the sources to add this method to RawArray since I can't even find the implementations of the currently defined methods E.g.: RawArray.append()

**Comment by vnen** [comment]
1.  `RawArray` is called `ByteArray` in C++ ([source](https://github.com/godotengine/godot/blob/69c8b583e7b7c31e9316a24f185ca99f9452d91d/core/variant_call.cpp#L1065)).  (this is problematic and it'll be normalized in 3.0 when we break compatibility).
2. `ByteArray` is just `DVector<uint8_t>` ([source](https://github.com/godotengine/godot/blob/5e816fd8c8e8c97e22f636573667a99ac705e56c/core/variant.h#L66)). Other `*Array` types are also `DVector`s.
3. If you want to add a function you need to add it to [`DVector`](https://github.com/godotengine/godot/blob/69c8b583e7b7c31e9316a24f185ca99f9452d91d/core/dvector.h#L43). Which means it can be available (if bound) to any of the `*Array` types.
4. Those are bound in `core/variant_call.cpp` [here](https://github.com/godotengine/godot/blob/69c8b583e7b7c31e9316a24f185ca99f9452d91d/core/variant_call.cpp#L510-L519) and [here](https://github.com/godotengine/godot/blob/69c8b583e7b7c31e9316a24f185ca99f9452d91d/core/variant_call.cpp#L1526-L1534) (you need to add it in both places, as they do different things).

That should be enough to start.

**Comment by gau-veldt** [comment]
Actually I think it's already there since I've seen ByteArray.subarray in the code which is basically what a .slice() method would be doing.  The only problem is subarray() returns the same array (at different pointers) this is likely not safe to use as-is for gdscript since the following code would cause trouble:
a1=RawArray([1,2,3,5,6,7,8,9,10])
a2=RawArray.slice(2,4)   # [3,5,6]
a2.insert(1,[4])  # a2 wants to be [3,4,5,6]
# a1 has now been modified
# and probably contains (1,2,3,4,5,6,8,9,10)

**Comment by gau-veldt** [comment]
Oh... subarray only lives in the java ByteArray :( guess this is a bust... looks complicated to make a slice method in c++ due to all the locking and copy on write semantics going on the DVector class

**Comment by gau-veldt** [comment]
okay I do have to make my owqn subarray method on DVector since the subarray I spotted in the code was acutally from the java portion,

**Comment by gau-veldt** [comment]
Hopefully this won't be too ugly an implementation:

        DVector<T> subarray(int p_from, int p_to) {

                if (p_from<0 || p_from>=size()) {
                        T& aux=*((T*)0); //nullreturn
                        ERR_FAIL_COND_V(p_from<0 || p_from>=size(),aux)
                }
                if (p_to<0 || p_to>=size()) {
                        T& aux=*((T*)0); //nullreturn
                        ERR_FAIL_COND_V(p_to<0 || p_to>=size(),aux)
                }

                DVector<T> slice;
                int span=1 + p_to - p_from;
                slice.resize(span);
                Read r = read();
                Write w = slice.write();
                for (int i=0; i<span; ++i) {
                        w[i] = r[p_from+i];
                }

                return slice;
        }

**Comment by gau-veldt** [comment]
If this is OK I can then attempt to do the bind for RawArray.

**Comment by gau-veldt** [comment]
It's in my github fork guess I need to do a PR and reference this issue.  PR is #5765

**Comment by gau-veldt** [comment]
The PR includes documentation of the new method as well as handling of -1 to mean 'last element'.

**Comment by gau-veldt** [comment]
I think the merging of #5879 closes this one.
