### ISSUE TITLE
"Create Physical Skeleton" skips final bone in chain

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot#57038]
### Godot version

3.4.2.stable.arch_linux

### System information

Linux 5.16.0-arch1-1

### Issue description

When generating a physical skeleton, godot seems to skip bones at the end of a chain:

![1642771932](https://user-images.githubusercontent.com/2496231/150535996-d198b967-26cf-4305-a0f2-3a7e5d050a8b.png)

Note that Head and Lower{Leg,Arm}.{L,R} are missing in Godot.

If I add a "Foot" bone at the end of each Leg, now LowerLeg.{R,L} are generated, but the feet are not.

### Steps to reproduce

1. Create a skeleton in blender
2. Export to godot
3. Open scene
4. Select the Skeleton node
5. Click "Create Physical Skeleton"
6. Note that "leaf" bones are missing

### Minimal reproduction project

[example.zip](https://github.com/godotengine/godot/files/7913984/example.zip)

**Comment by TokageItLab** [comment]
Duplicate of #32393. It is not Godot's bug.

**Comment by Calinou** [comment]
Can't we modify Godot to display leaf bones (perhaps in a different color)? I feel this adds a lot of confusion.

**Comment by TokageItLab** [comment]
If the leaf bone information is missing in the glTF, I think it is impossible.

**Comment by rcorre** [comment]
Dupe of https://github.com/godotengine/godot/issues/32393#issuecomment-1018908835
