### ISSUE TITLE
[RichTextLabel] incorrect position in parent

### ISSUE THREAD

**Issue by radubolovan** [godotengine/godot#5703]
**Operating system or device - Godot version:** Windows 10 - Godot 2.1-beta

**Issue description** (what happened, and what was expected):
I have a simple scene with one Node2D object as "root" and I resized it to full cover the 2D area of the Camera. Then I created a RichTextLabel node as a child. The child node is not correctly positioned by default. Shouldn't it be centered having the center of it's bounding rect in the center of its parent?
Here's a screenshot: https://s31.postimg.org/dfdxfuiej/Rich_Text_Label.png

Note: the bug is also present in 2.0-stable, 2.0.3 and 2.0.4.1_stable

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by henriquelalves** [comment]
It is working as intended, because the origin / anchor point of the RichText node is its upper left corner. That way is easier for the developer to see how the text is going to be displayed.

**Comment by radubolovan** [comment]
If the origin of all nodes is top/left, why the "RichTextLabel" spawns in the center of it's parent then when first created?
As I can see it so far, all nodes has the anchor in the center.

**Comment by vnen** [comment]
@radubolovan it seems to me you are opening bugs that are not really bugs. You might be new to the engine and not fully aware of how it works. I recommend you ask you questions on [Godot's QA forum](https://godotengine.org/qa) and ask your doubts there and if some people agree with you it's a bug, then open a report.

If I'm wrong and you indeed think it's a bug, please provide a minimal project as a ZIP file that shows the bug.

**Comment by radubolovan** [comment]
Hello @vnen,
I apologize if I didn't make my post clear and I don't know how to make it more clear. I'm sorry!
In my opinion this is a bug and I don't want to open bugs just because I want to open bugs. I love this engine and I want to improve it.
If you guys consider that this is not a bug, just close it. I won't mind and it will not affect me.
And about Godot's QA forum, they directed me here.
I apologize again, I mean no harm. Just some thoughts.

**Comment by ret80** [comment]
@radubolovan - Close your issues [#5703, #5706] yourself please :)
