### ISSUE TITLE
Defining a TooltipPanel or a TooltipLabel in a theme does not affect themed controls

### ISSUE THREAD

**Issue by WalasPrime** [godotengine/godot#5704]
Windows 10 64bit Godot 2.1-beta

When applying a theme with TooltipPanel or TooltipLabel defined to a Control with tooltip text - the tooltip has default styling if some of parent Controls have no theme (or is overriden).

**Steps to reproduce:**
1. Create a control of any type (eg. a panel)
2. Create a nested control of any type (eg. a button)
3. Create a theme and attach it to the button
4. Add Class Items TooltipPanel or TooltipLabel (any or both)
5. Modify properties so that they could be easily noticed
6. Add a tooltip text to the button
7. Run the scene, hover over the element, the tooltip is using default styling

Also, in the element preview area for theme editing there is no tooltip element. My suggestion - add a dedicated tooltip element or attach tooltip texts to every element previewed.

EDIT: I've encountered this issue with a more complex hierarchy, so perhaps my issue laid somewhere else. My tooltip refused to change unless I changed the theme for VBoxContainer, while my tooltipped buttons were contained deeper in panels (which were styled).

**Comment by WalasPrime** [comment]
Managed to recreate this in a separate scene using a similar scene hierarchy. The Panel is themed with a proper TooltipLabel, which does not appear when hovering over the Button or the Panel itself.

[tooltip.zip](https://github.com/godotengine/godot/files/365740/tooltip.zip)

**Comment by akien-mga** [comment]
Is this still valid in the current master branch?

**Comment by WalasPrime** [comment]
Unfortunately the master branch currently does not compile. I'll check it as soon as possible (if I'll forget then just ping me)

**Comment by akien-mga** [comment]
The build issue was just fixed, so it should work now.

**Comment by KoBeWi** [comment]
This is fixed, probably at the same time as #18478 (which was a duplicate?)

**Comment by Calinou** [comment]
Closing, as it seems to be fixed in 3.1 according to the issue linked by @KoBeWi.
