### ISSUE TITLE
Inspector EditorSpinSlider handle no longer works?

### ISSUE THREAD

**Issue by andersmmg** [godotengine/godot#57042]
### Godot version

v4.0.dev.20220118.official [bc5ba38ff]

### System information

KDE Linux and Windows 10

### Issue description

On 3.x, you can use the slider handle in the editor to adjust values much more quickly, and drag the mouse inside the box (but not on the handle) to adjust finely. In 4.0 this no longer seems to work, you can only do the fine adjustment even though the slider handle is still visible.
![image](https://user-images.githubusercontent.com/16022203/150576117-2f5cf21d-744e-4e2c-b09b-82f260923b0e.png)

I noticed this a few versions ago, and assumed it was just a glitch, but it's always like this now. Is it a useability change maybe, or a bug? I use it all the time on 3.4, and it always throws me off and gets annoying not being able to use it 4.0

### Steps to reproduce

Open any 4.0 version and try to grab the handle. It doesn't work.
It works on all 3.x versions I can remember using.

**Comment by KoBeWi** [comment]
Which property exactly is broken?
![godot windows tools 64_KDx4rCmQYb](https://user-images.githubusercontent.com/2223172/150599382-40804bd3-cfb2-419d-a90b-05e54ca68741.gif)
I remember exponential properties having weird behavior, but some of them are fine, as seen above.

**Comment by andersmmg** [comment]
For me, I haven't found a single one that works. That looks to me like the canvasitem rect transforms, and that has the same issue. No matter where I start dragging, it's the slow precise mode.

https://user-images.githubusercontent.com/16022203/150604373-3c1f2d27-f941-41da-bf9b-c48af5d3d678.mp4

**Comment by andersmmg** [comment]
Are there any updated on this? I still have this issue on the latest alpha.

**Comment by Rindbee** [comment]
I guess these cause by `interface/inspector/default_float_step`. 


> Which property exactly is broken? 
> ![godot windows tools 64_KDx4rCmQYb](https://user-images.githubusercontent.com/2223172/150599382-40804bd3-cfb2-419d-a90b-05e54ca68741.gif) 
> I remember exponential properties having weird behavior, but some of them are fine, as seen above.


For this case, it's actually a radian value. so the displayed value is converted.

**Comment by andersmmg** [comment]
I don't think this is the problem. The step size seems fine for normally adjusting, the issue is that I'm only able to use that step size, and not the alternate I should get when directly dragging the handle (like I can in 3.x)

**Comment by Rindbee** [comment]
> I don't think this is the problem. The step size seems fine for normally adjusting, the issue is that I'm only able to use that step size, and not the alternate I should get when directly dragging the handle (like I can in 3.x)

The step used may be hard-coded to 0.001, like the properties in #54379.

**Comment by andersmmg** [comment]
Is it the same in 3.x? I can't even highlight the handle in 4, which I would assume is a big part of the issue since I can in 3.x and it works fine there.

**Comment by Rindbee** [comment]
It may indeed be a hard-coded problem. 

`PROPERTY_HINT_RANGE` exists in 4.0:
https://github.com/godotengine/godot/blob/3639c27cf16cf3ee588c5a1e7587e0deecc9db6a/scene/2d/node_2d.cpp#L415
`PROPERTY_HINT_RANGE` does not exist in 3.x:
https://github.com/godotengine/godot/blob/b6968ab0602bfe72c71d4efcafe608f9cac36252/scene/2d/node_2d.cpp#L425

This is probably why `interface/inspector/default_float_step` works in 3.x but not in 4.0.

**Comment by Calinou** [comment]
IIRC, `PROPERTY_HINT_RANGE` was never implemented for Vector2/Vector3 editors.

**Comment by andersmmg** [comment]
I still don't see how this would change what this issue is for. This stuff is could definitely be a problem, but my issue is about the extra handle that allows you to make bigger changes to the value, more like a scrollbar than a slider. Am I just missing something? xD

This is how it should work, and it does in 3.x. I can grab the handle and change the value much faster for big changes, or drag in the box to do it more precise.

https://user-images.githubusercontent.com/16022203/163604368-7f2b3850-444a-4be3-aaf1-a1c53414d7aa.mp4

In 4.x, I can't grab the handle and it changes at the same speed no matter what. The handle also doesn't highlight for me to grab it as it does in 3.x.

https://user-images.githubusercontent.com/16022203/163604478-6765d275-420c-412e-b77f-af7558eb9d43.mp4

Maybe these videos can help explain what I mean

**Comment by andersmmg** [comment]
It seems this was possibly fixed around alpha 9, I haven't been able to find by what it was fixed, but I can't reproduce it so far in alpha 9 onward
