### ISSUE TITLE
OpenSimplexNoise doesn't repeat

### ISSUE THREAD

**Issue by FreegleBarr** [godotengine/godot#57043]
### Godot version

v4.0.dev.calinou [73d00131c]

### System information

Ubuntu 20.04, Vulkan Clustered, NVIDIA GeForce MX350

### Issue description

When sampling OpenSimplexNoise, `texture` no longer repeats the coordinate between 0 and 1, resulting in stretched borders. Easy to work around by calling fract on the coordinates. This does not happen in 3.4.2, so could be simply a dropped small feature. The repeat attribute on the Texture section does not have any influence on this, though I'm not sure it should.

### Steps to reproduce

Create a shader with a NoiseTexture and set it to OpenSimplexNoise. Set the texture to Seamless and try to sample outside the [0,1] range. The texture will be stretched, which did not happen in Godot 3.

### Minimal reproduction project

[SimplexWrap.zip](https://github.com/godotengine/godot/files/7915855/SimplexWrap.zip)

**Comment by Calinou** [comment]
In `master`, filter/repeat flags are no longer stored in the texture itself and are instead defined in the location where the texture is used. This can be a material, a shader hint, etc.
