### ISSUE TITLE
Exporting any preset on linux removes MacOS codesigning settings

### ISSUE THREAD

**Issue by ehmprah** [godotengine/godot#57065]
### Godot version

3.4.stable

### System information

PopOS_! 21.10

### Issue description

After exporting a build on my linux machine, every line beginning with codesign/* or notarization/* are removed from the export_presets.cfg file. I understand that these settings are not available on a linux machine, but Godot could at least leave the presets intact so they're still working the next time I'm using my Mac.

How about just disabling the inputs on Windows / Linux machines but showing them so you see that there's something there in the export editor and the values are kept upon regerenerating the export_presets.cfg?

### Steps to reproduce

See above.

**Comment by Calinou** [comment]
This is likely resolved by https://github.com/godotengine/godot/pull/51310, which will be included in Godot 3.5.

**Comment by bruvzg** [comment]
> This is likely resolved by #51310, which will be included in Godot 3.5

Only for some option that are now supported on Linux and Windows. Notarization options will be still removed. We need to add some way to disable options, instead of removing them.
