### ISSUE TITLE
3D Grid Map draw orange grid in wrong position

### ISSUE THREAD

**Issue by CristianoSimao** [godotengine/godot#57068]
### Godot version

3.4.2

### System information

Windows 10, GLES2 - Graphic card Vega8 (AMD Ryzen 3 2200 G)

### Issue description

In this video you can see the orange grid changing the position when the floor level is clicked by the user, the grid is draw based in the last mouse position, this turn the orange grid useless.
I think the right behavior is the orange grid be drawing with the last tile placed.

After the first 48 seconds of the video you can see the grid errors.

YouTube video link:
[https://youtu.be/fqN0yDFXzOk](https://youtu.be/fqN0yDFXzOk)

### Steps to reproduce

1 - Create some simple 3d models
2 - Create a mesh library with the 3d models.
3 - Create a gridmap and add the mesh library.
4 - Start placing the 3D tiles.
5 - If you zoom out or change the camera angle and change the floor level the orange grid will be draw in the wrong position.

### Minimal reproduction project

[TesteReimport.zip](https://github.com/godotengine/godot/files/7919011/TesteReimport.zip)

**Comment by Calinou** [comment]
I thought this orange grid was supposed to follow the mouse cursor continuously. At least, I remember it doing so back when I last used GridMap…

**Comment by CristianoSimao** [comment]
If the grid follow the mouse all the time will be better.

**Comment by CheapMeow** [comment]
same problem in v3.4.4-stable_win64
