### ISSUE TITLE
"Visual Studio" option under mono settings does not work with Visual Studio 2022 Professional

### ISSUE THREAD

**Issue by GNUGradyn** [godotengine/godot#57069]
### Godot version

v3.4.2.stable.mono.official [45eaa2daf]

### System information

Windows 10 Pro 21H1, i7-8700k, RTX 2080 SUPER

### Issue description

Hello everyone. I am new to godot. I have the mono version of godot and I wish to use Visual Studio 2022 Professional as my editor, because that is what I use for work and Visual Studio is pretty big so I'd rather not have 2 entire installations of the IDE on my system. Using the built in editor as well as the latest version of Visual Studio Code works fine. Visual Studio on the other hand does not. The only step I am taking to configure the IDE is going to Editor > Editor Settings > Mono > Editor and changing the "External Editor". This works as expected when set to "Disabled" or "Visual Studio Code". However, when set to "Visual Studio", the button to open a script does absolutely nothing.

https://user-images.githubusercontent.com/20762604/150651889-56fdd85d-2018-487f-bedb-cd53a5140869.mp4

This video demonstrates the issue and also shows that my installation of visual studio does in fact work. If any more details are needed please let me know and I will be happy to provide them.

### Steps to reproduce

- Install Visual Studio 2022 Professional
- Launch the Mono version of GoDot
- Navigate to Editor > Editor Settings > Mono > Editor
- Change the External Editor to Visual Studio
- Attempt to open a script in Visual Studio from GoDot

### Minimal reproduction project

This issue occurs even on a brand new blank project

**Comment by Calinou** [comment]
I don't think support for Visual Studio 2022 was implemented yet, both for compiling Godot and using it as an external C# editor.

cc @neikeq

**Comment by raulsntos** [comment]
This is probably due to this breaking change from Visual Studio 2022: https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/breaking-api-list?view=vs-2022#dte-and-_dte-type-cast-failures

The code responsible for opening Visual Studio is in https://github.com/godotengine/godot/blob/c83563e810768d5672127a521db09da2adde808b/modules/mono/editor/GodotTools/GodotTools.OpenVisualStudio/Program.cs so I'm assuming we'd have to change `DTE` references to `DTE2`.

**Comment by akien-mga** [comment]
As a workaround, you should be able to use the "dotnet CLI" build tool instead of VS 2022 (presumably after install .NET Core 3.1? Correct me if I'm wrong Mono folks :))

**Comment by raulsntos** [comment]
@akien-mga I believe this issue is about opening the Visual Studio IDE not about building the project which should still work regardless.

**Comment by neikeq** [comment]
> Not sure which version corresponds to VS2022 but I guess changing it would break for other Visual Studio versions.

It should be 17.0.

**Comment by GNUGradyn** [comment]
Is it going to be possible to auto detect which version of DTE we should be using or should we just have separate drop-down options for "Visual Studio 2022" (DTE 17) and "Visual Studio 2019" (DTE 16). Or maybe in case they have multiple, we can have a visual studio dropdown reveal when Visual Studio is selected as the editor?

**Comment by neikeq** [comment]
I think it's better to just go with the newer version and fallback to the older one.
