### ISSUE TITLE
[RichTextLabel] incorrect representation of the text

### ISSUE THREAD

**Issue by radubolovan** [godotengine/godot#5706]
**Operating system or device - Godot version:** Windows 10 - Godot 2.1-beta

**Issue description** (what happened, and what was expected):
I made a scene, with a Node 2D as "root" and a "RichTextLabel" object as a child. I also copied an font imported in a Godot 2.0-stable version to the project. I also attached a script to set the text for the RichTextLabel object and odd hings happens. Please see the screenshot:
https://s31.postimg.org/rp4np33qj/Rich_Text_Label_bug2.png

Edit: I was able to reproduce the bug also on the 2.0.4.1-stable version and added more details in the following screenshot:
https://s31.postimg.org/nfg851c8r/Rich_Text_Label_bug2_2.png

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by vnen** [comment]
Have you expanded the Node2D dimensions with the mouse? It looks to me like you did so, which will change the scale of the node and affect all of its children. Check the scale property of the root node in the inspector and make sure it's 1, 1.

**Comment by radubolovan** [comment]
I didn't scale anything. This is the default when I created the child.
I completely understand that AFTER creating a child, rescale the parent should affect the children. But when creating a child shouldn't affect the parent's props.
Imagine that you have a "world" perfectly designed for your desires. And after a while you want to add another node as a child of that world (2D or 3D, it doesn't matter). Should that node be scaled within the parent's scale in that moment or do you want to customize the scale (or any other properties) after creating it?
No offense, just some thoughts.

**Comment by vnen** [comment]
The scale of a node affects its children, no matter when it was added. The children inherits the base transform of the parent, always (transform is position, rotation and scale). That's the way it works and it's the proper way. You must always consider the transform of the parents when editing a node.

**Comment by henriquelalves** [comment]
Just a side note, by resizing a Node2D, you are resizing all its children. In the other issue you opened you described something similar - you extended the entire Node2D to fit the entire screen. Usually you don't work with it like that; Node2D is just a reference node, and it's borders are just a visual way for you to see its scale. So if you altered it's borders like you did in the other Issue, than yes, you scaled it and all its children.

**Comment by radubolovan** [comment]
I understand what you guys are saying. I'm working in game industry since 2005 and this is the first time I see this approach. OK, I will adapt to this concern; you can close this "bug".
Cheers!

**Comment by akien-mga** [comment]
Node2D doesn't have a size, only a scale, so when you resize them, you are indeed just changing their scale, which gets multiplied to its children's scale, indeed.
