### ISSUE TITLE
"Simple" Text node

### ISSUE THREAD

**Issue by radubolovan** [godotengine/godot#5707]
**Operating system or device - Godot version:** All OS - future Godot versions

**Issue description** (what happened, and what was expected):
I suggest to implement a simple Node for texts having a single row of text and (as visual effect) auto expandable (in the right for Latin, in the left for Arabic, etc.).
Why: Most of texts in games don't have multiple lines of texts. For instance a title of a message box.
Example: as in "Button" node, there's property in the inspector called "text" and it works perfectly, but it's nonsense to make a button node just because a developer needs a simple text.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by henriquelalves** [comment]
Isn't the node "Label" enough? It is the one that most people uses for simple lines of text, and it is expandable as you describe.

**Comment by radubolovan** [comment]
Yes, Label is enough.
This can be closed.
