### ISSUE TITLE
Material preview sphere icon has wrong inactive modulation

### ISSUE THREAD

**Issue by pycbouh** [godotengine/godot#57088]
### Godot version

4.0 (#eb5aa32)

### System information

Windows 10

### Issue description

The icon used to switch to a sphere model for material preview goes completely invisible (or black) when it gets into the inactive state. Cube's icon handles that state correctly and only gets slightly dimmer.

https://user-images.githubusercontent.com/11782833/150687914-de0826b3-2854-4858-8828-505e28829cb9.mp4

### Steps to reproduce

Add a 3d node and create a material for it. Open the material resource and play around with the material preview.

### Minimal reproduction project

N/a

**Comment by AnilBK** [comment]
Related: https://github.com/godotengine/godot/pull/49466#discussion_r652268980

**Comment by pycbouh** [comment]
> Related: [#49466 (comment)](https://github.com/godotengine/godot/pull/49466#discussion_r652268980)

IMO, it's still an issue even if checkerboard is fixed. Both icons should use the same color and behave the same. If they are used elsewhere, we can duplicate them.

**Comment by snailrhymer** [comment]
I saw the same behaviour with only the top lighting toggle (#55945).

Lighting 1 off:
![Lighting toggle disappearing](https://user-images.githubusercontent.com/61291296/150891390-4102417d-eaeb-4306-ab64-97cdb4529170.png)

Lighting 2 off:
![image](https://user-images.githubusercontent.com/61291296/150891465-dad693c8-f43b-474b-8296-bbd5b0cd72b1.png)

**Comment by Josephblt** [comment]
Hello guys. I found out there are differences between the icon .svg files. I'd like to create a PR for that.
