### ISSUE TITLE
Incorrect offset at the in-editor documentation

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#57083]
### Godot version

3f9352848383af269f5c027ecc12b13615d21e35

### System information

Windows 10

### Issue description

![image](https://user-images.githubusercontent.com/3036176/150685225-ca981eed-c603-4752-85bf-dc17adecedd0.png)

It also opening incorrect link due that offset:

![editor_doc_bug](https://user-images.githubusercontent.com/3036176/150685308-8b133100-fbd2-46de-951e-4d733cb2d424.gif)

### Steps to reproduce

Open documentation of `VisualShaderNode`.

**Comment by akien-mga** [comment]
Seems to be a recent regression (no bug in 4.0.dev.20220118), probably due to #35508. It's likely not using the correct font to calculate the offset. CC @Calinou @bruvzg

**Comment by bruvzg** [comment]
Most likely it's regression from #56910

**Comment by akien-mga** [comment]
CC @pycbouh

**Comment by bruvzg** [comment]
Seems like #56910 added line separating to all draw calls, but it's missing from the offset and click calculations - here's a fix - #57090 (needs testing, I might miss adding it in some place as well).

**Comment by pycbouh** [comment]
Seems to be working better with #57090, and I don't see anything out of place from skimming various doc pages. But it seems I didn't try hard enough the last time I tested it, so take this report with a spoon of salt :P

There still seems to be a minor issue with the table of properties in some edge cases like in the clip in the OP. With the "Function" type name shifting to the left, beyond the table width. Seems to be minor, I'd say we can fix it later.
