### ISSUE TITLE
Atlas does not work at a 3D object

### ISSUE THREAD

**Issue by okay300** [godotengine/godot#57094]
### Godot version

3.4.2

### System information

Windows 7     64-bit

### Issue description

atlas (.godot)  works not correctly          
(json hash )  the importer does not work
(XML) works not correctly, each resource in the atlas occupies 32 MB

I use Free texture packer
https://free-tex-packer.com/

### Steps to reproduce

**shader**
![pic_32re35](https://user-images.githubusercontent.com/75214342/150692972-70e2840f-3eaa-451c-b5d6-0afa6f09b60d.png)

**single texture**
![423rwet](https://user-images.githubusercontent.com/75214342/150692006-d34f3046-08ff-44bf-b0d4-d6c68adb0846.png)

**atlas resource (.godot)**  
![2435w6teyuty](https://user-images.githubusercontent.com/75214342/150692009-b3ff3336-820e-4075-9b93-9b118dac3b4d.png)

 ---------------------------------------- Project description---------------------------------------

I created material which can be customized
![model_423WRE](https://user-images.githubusercontent.com/75214342/150690571-87f0ae46-5001-467b-b4f5-3875c537dd86.png)
![42qw536eyut (1)](https://user-images.githubusercontent.com/75214342/150691070-7fc0e821-1044-468f-8825-9e97cefe9e4c.png)

**Example of textures:**

standard texture
![skin_3](https://user-images.githubusercontent.com/75214342/150690513-174de659-7c2f-4e40-9b04-9e116cabe5fb.png)

texture (shield)
![skin_dop_sh_1](https://user-images.githubusercontent.com/75214342/150691279-50fd262c-bcc9-40b6-8ae1-d50068196630.png)

texture (helmet)
![skin_dop_h_1](https://user-images.githubusercontent.com/75214342/150691444-2118f28e-2195-450d-9811-640008912a7e.png)

texture (weapon)
![skin_dop_w_1](https://user-images.githubusercontent.com/75214342/150691468-682fc263-364f-4148-a2bb-828c48cd3ad9.png)

**for convenience I created the atlas**
![atlas](https://user-images.githubusercontent.com/75214342/150691731-869cddf5-f33e-4b94-9723-39ebb9f7a4e5.png)

### Minimal reproduction project

download project (25mb): 
https://anonfiles.com/L1eah7D7x0/Godo_op_7z

**Comment by Calinou** [comment]
[AtlasTexture is only designed to be used in 2D, not 3D.](https://godotengine.org/article/atlas-support-returns-godot-3-2)
