### ISSUE TITLE
Create node dialog occur error with some custom class.

### ISSUE THREAD

**Issue by dicarne** [godotengine/godot#57108]
### Godot version

4.0.dev

### System information

Windows11

### Issue description

When the custom class precedes the parent class `_add_type`, creating a parent class recursively will cause an error. When calling recursively, the `p_type_category` of the parent class (such as button) is incorrectly assigned to `OTHER_TYPE`, but it is not. It should be `CPP_TYPE`, which causes the built-in component to not find the parent class correctly, resulting in the null inherits, causing this assertion error.
[https://github.com/godotengine/godot/commit/c63f23bcaac69f7d55d8317b966d3e7885ab1f24](https://github.com/godotengine/godot/commit/c63f23bcaac69f7d55d8317b966d3e7885ab1f24) assert faild at line 264, `_add_type`function. 

### Steps to reproduce

Customize the "Buttom" class and inherit from the "Button" class will cause this error; Custom "A" class inherited from "Control" will also cause this error, which will cause confusion in the component tree. For example, some components of "button" are scattered outside, and sub components of "control" class are scattered at the "node" level. In my computer, sometimes it will crash.

### Minimal reproduction project

[node_dialog_error.zip](https://github.com/godotengine/godot/files/7923533/node_dialog_error.zip)

just press add node button in scene tree. And sub components of "control" class are scattered at the "node" level, command line will print error.

This error can be reproduce with the latest editor, like [https://github.com/godotengine/godot/actions/runs/1737159355](https://github.com/godotengine/godot/actions/runs/1737159355) or compile from the latest source code.

**Comment by KoBeWi** [comment]
No error in alpha 7.
@dicarne Can you confirm?
