### ISSUE TITLE
[4.0] VSync modes force 60 FPS

### ISSUE THREAD

**Issue by Rinocrosser** [godotengine/godot#57117]
### Godot version

4.0 Alpha 1

### System information

Windows 10 (build 19044), 3060 Ti, NV Driver 511.23, Dell S2721DGFA monitor

### Issue description

I've tried all possible VSync modes in 4.0, but all of them are 60Hz, even the Adaptive one. They supposed to be relative to the real monitor refresh rate instead.

![image](https://user-images.githubusercontent.com/19660324/150778910-4837724d-9562-4e30-be78-e2f44822a469.png)

If VSync is disabled, the real 144 or 165 Hz are only visible if the window is not in focus.
If the game window is selected, the game switch back to 60Hz.

![image](https://user-images.githubusercontent.com/19660324/150779135-7b532b78-4dfb-4943-9dcc-b1d261212a5a.png)

### Steps to reproduce

Try different VSync modes on high-speed monitor.
Try disabling VSync and switch between the game and the editor windows.

**Comment by Geometror** [comment]
Unfortunately I can't reproduce this issue. All modes seem to work as expected on my configuration, which is quite similar to yours:
Enabled -> 144 FPS == monitor's refresh rate
Adaptive -> 144 FPS == monitor's refresh rate
Mailbox -> >2800 FPS
Disabled -> >2800 FPS
Framerate does not change when the window loses focus.

Does this happen with an empty project? If not, could you provide a minimal reproduction project?

Configuration:
BS: Win 10 19044.1466, 
Graphics card: NV 3060 Ti (both 496.xx and 511.23 drivers tested)
Monitor AOC 27G2U 1440p version

**Comment by Rinocrosser** [comment]
But even if I disable G-Sync, Godot's own VSync (default, adaptive) modes are still throwing me back to 60 FPS.

**Comment by Rinocrosser** [comment]
We were testing the issue with da boyz and it may be due to dual monitor setup. My high-end monitor is 165Hz G-Sync, but there's also 60Hz panel attached. And even if I'm working on a fast one, it sets limits based on the slow one.

Godot 3.x was making it correctly.

**Comment by Lakamfo** [comment]
**Bug reproduced**, if I turn off g-sync, fps is blocked correctly at active monitor refresh rate. 

2 monitors connected to pc:
1. Active monitor - Acer Nitro XV242YPbmiiprx (144hz refresh rate)
2. Second monitor - Dell ST2200L (60hz refresh rate)

**Comment by Geometror** [comment]
@Rinocrosser 
That is strange, just tested this exact case. For me it worked correctly, meaning that when I move the window between monitors the refresh rate is adjusted dynamically (tested with two identical G-Sync compatible monitors, one set to 60Hz and one to 144 Hz, and one older 60Hz graphic design monitor).
Seems like this only happens with specific monitors/multi monitor configurations, presumably with G-Sync monitors, maybe not with G-Sync compatible ones. Although I am not sure yet, I am afraid this could be a driver bug, meaning that this can't be fixed on our side.

Some more questions to deduce the cause of the problem:
Does it still happen after switching to the OpenGL driver?
What happens when you disable VSync in Godot and force it via the nvidia control panel?

**Comment by Rinocrosser** [comment]
> tested with two identical G-Sync compatible monitors, one set to 60Hz and one to 144 Hz

@Geometror I'm afraid that you need a native 60Hz panel for this issue.

**Comment by Geometror** [comment]
Sorry, the discripition of my config in the above answer was a bit vague/unclear (edited it accordingly).
I did test it with a native 60Hz monitor (in fact, it is a screen tablet too, Kanvas Pro 20 GT1901) and could't reproduce it.

**Comment by Rinocrosser** [comment]
@Geometror @Lakamfo 

Thanks everyone, it was NVIDIA Driver after all. It happened with me before, when NVIDIA update ruined GLES / Vulkan apps performance, so I should've guessed it. The solution is clean driver install.

1. Restored NV settings to default (didn't work)
2. Played with some of these settings to find possible issues (no luck)
2. Reinstalled the driver from scratch (clean installation) – now it work flawlessly

**Comment by Rinocrosser** [comment]
Unfortunately, the issue with windows in focus / not in focus still appears, so I'll try to figure out, what is the reason, if there will be any logic behind this, I'll share my thoughts.

![image](https://user-images.githubusercontent.com/19660324/150831877-6d89395c-e794-457c-bcc7-013d9d69f8bb.png)
