### ISSUE TITLE
[4.0] 2D Pan Tool not working

### ISSUE THREAD

**Issue by Schweini07** [godotengine/godot#57127]
### Godot version

4.0-dev (6a3ff8f), 4.0-alpha1

### System information

Manjaro Linux 21.2.2

### Issue description

Trying to use the pan tool does not work on the latest commit, including the alpha1.

https://user-images.githubusercontent.com/47503977/150822292-b6f32e33-c809-4cba-93ac-20afdf4ee616.mp4

:

### Steps to reproduce

Go into the 2D editor and try to use the pan tool.

**Comment by KoBeWi** [comment]
You can use Space + LMB as a workaround.
