### ISSUE TITLE
[4.0] Certain icons are shrunken (SVG scale not taken into account)

### ISSUE THREAD

**Issue by Schweini07** [godotengine/godot#57129]
### Godot version

4.0-dev (6a3ff8f), 4.0-alpha1

### System information

Manjaro Linux 21.2.2

### Issue description

I found a few icons that are shrunken down compared to other ones.
One is the ruler tool and the others are the NavigationAgent and NavigationObstacle nodes.

![image](https://user-images.githubusercontent.com/47503977/150822829-7cb34e23-560c-4fca-b08d-541c88229e29.png)
![image](https://user-images.githubusercontent.com/47503977/150822931-488ee651-f6b0-4835-bc66-76649ecc2420.png)

### Steps to reproduce

Look for the icons on the latest commit or alpha1.

**Comment by dalexeev** [comment]
And some icons are too big:

![](https://user-images.githubusercontent.com/47700418/150851828-d6f7ab73-1d08-44ea-b7dd-11597abfccc2.png)

**Comment by pycbouh** [comment]
> And some icons are too big:
> 
> 
> 
> ![](https://user-images.githubusercontent.com/47700418/150851828-d6f7ab73-1d08-44ea-b7dd-11597abfccc2.png)
> 
> 

Pretty sure, that was an intentional change.

**Comment by Calinou** [comment]
> Pretty sure, that was an intentional change.

I think we could make the new breakpoint a bit smaller (probably a middleground between the old size and new size).

**Comment by KoBeWi** [comment]
This might be regression from #49645
SVG icons have a `viewBox` property defined. Most of them have "0 0 16 16", but e.g. the ruler icon has "0 0 4.2333 4.2333". Changing it to 16 16 doesn't help though, so not sure what is wrong here. Also seems like the property can be dropped (it repeats width and height), it would make the SVGs smaller.

**Comment by pycbouh** [comment]
AFAIK they are parsed for different purposes, so viewport values cannot be dropped. It's kind of like a clipping rectangle of the image. But even if they can, let the SVG optimizer do it, no need to edit that out manually. Probably opening it with a vector editor and correcting the size should work though.

**Comment by pycbouh** [comment]
That's something @fire may know, but I don't think there is any reason here for us to use scale anyway. I'd fix the images instead, and worry about ThorVG later, if the need arises.

**Comment by fire** [comment]
Can I have the exact link to the `.svg` so I check the online thorvg viewer?

**Comment by KoBeWi** [comment]
Correct:
https://github.com/godotengine/godot/blob/master/editor/icons/Add.svg
Incorrect:
https://github.com/godotengine/godot/blob/master/editor/icons/Ruler.svg
