### ISSUE TITLE
Save scene edition metadata: Transform, View, Position, etc.

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#5713]
**Operating system or device - Godot version:**
Ubuntu 16.04, Godot 2.1 beta

**Issue description** (what happened, and what was expected):
Not saved scene settings: Transform, View, Position of the viewport.
After opening a saved scene, all settings are reset to default.

**Comment by akien-mga** [comment]
This used to be saved in metadata in the scene file, but it was removed as it causes a lot of unnecessary noise when using version control systems. If it gets readded, it should be made in the user dir (`~/.godot` or `%APPDATA%/Godot` and not in the project files themselves.

**Comment by Calinou** [comment]
This seems to be implemented in both 2D and 3D as of https://github.com/godotengine/godot/commit/b030834b6384d5f57e5fc63db21b643adc86b3da, closing.
