### ISSUE TITLE
[4.0] Editor lightmap softlock upon re-importing an OBJ

### ISSUE THREAD

**Issue by YellowAfterlife** [godotengine/godot#57131]
### Godot version

v4.0.alpha1.official [31a7ddbf8]

### System information

Windows 10, Vulkan, 1660Ti

### Issue description

In my attempts to attach a material to an OBJ exported from Qodot using the last tab of Import dialog I have managed to get the editor to reliably softlock upon opening the scene,
```
ERROR: Condition "!lm" is true. Returning: false
   at: lightmap_is_interior (servers/rendering/renderer_rd/renderer_storage_rd.cpp:7493)
ERROR: Condition "!lm" is true. Returning: AABB()
   at: lightmap_get_aabb (servers/rendering/renderer_rd/renderer_storage_rd.cpp:7499)
ERROR: Condition "!lm" is true. Returning: false
   at: lightmap_is_interior (servers/rendering/renderer_rd/renderer_storage_rd.cpp:7493)
ERROR: Condition "!lm" is true. Returning: AABB()
   at: lightmap_get_aabb (servers/rendering/renderer_rd/renderer_storage_rd.cpp:7499)
```

### Steps to reproduce

Open the attached project, open TestScene

### Minimal reproduction project

[QodotTest4.zip](https://github.com/godotengine/godot/files/7927316/QodotTest4.zip)

**Comment by Calinou** [comment]
@YellowAfterlife Can you reproduce this in 3.4.2?

**Comment by YellowAfterlife** [comment]
@Calinou I'm not sure if this can be done in 3.4.2 since the advanced import menu (with ability to set materials per-mesh, which is how I achieved this crash) was introduced after that

**Comment by Setadokalo** [comment]
I'm encountering a similar error myself, using the tbloader plugin and a lightmap node. For me, the error occurs when I bake the lightmap, save and close the scene, and re-open it (the log begins flooding with `Condition "!lm" is true` errors), and if I close the project entirely and re-open it the editor freezes while opening, still flooding the log.
