### ISSUE TITLE
Stretch Mode Canvas Item not working

### ISSUE THREAD

**Issue by stryker313** [godotengine/godot#57134]
### Godot version

v4.0.alpha1.official.31a7ddbf8

### System information

Windows 10 GTx 1060 i5 4690k

### Issue description

Stretch mode canvas does not work.
All elements remain their initial size. Also plagues override resolution, but thats for another issue.

https://user-images.githubusercontent.com/83078010/150829596-441e1684-41ae-4d39-98e5-231d5dcac5c1.mp4

### Steps to reproduce

1. Create UI elements
2. Enable Stretch mode canvas in project settings
3. Run the game at default resolution
4. Run the game at 1920x1080, and you will see that the items do not stretch

### Minimal reproduction project

[Uploading aaaa.zip…]()

**Comment by Calinou** [comment]
@stryker313 The minimal reproduction project failed to upload, please try again.

Also, remember that on Linux, you may be encountering https://github.com/godotengine/godot/issues/55145. As a workaround, try to run the project twice.

**Comment by KoBeWi** [comment]
Not sure what you are expecting, but this works correctly:
![godot windows tools 64_jKgO6O0a8X](https://user-images.githubusercontent.com/2223172/170516622-2bf2c1f0-db6b-43c6-8b63-7cbf6d089ba8.gif)
What you set in viewport width/height is used as a default reference size, so changing it has no effect on scaling. What you are looking for is window width/height override, which is hidden under Advanced Settings.

**Comment by KoBeWi** [comment]
This is explained here: https://docs.godotengine.org/en/latest/tutorials/rendering/multiple_resolutions.html#stretch-mode
These properties were renamed for better clarity.

**Comment by Zireael07** [comment]
It's not made clear enough in https://docs.godotengine.org/en/latest/tutorials/rendering/viewports.html, though. Scale and stretching aren't clarified enough, nor is the meaning of 'size' made clear in the API docs https://docs.godotengine.org/en/latest/classes/class_subviewport.html#class-subviewport
