### ISSUE TITLE
[4.0] Custom fonts not managed properly

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#57138]
### Godot version

4.0alpha 1

### System information

Debian 11

### Issue description

Usually I set my fonts to personalize the editor and in 4.0 I noticed it not work as I expected.
In the follow screen scot you can see the top section is from 3.5 and "interface" is very clear while in 4.0 (the bottom section) the same "interface" is unfocused:
![image](https://user-images.githubusercontent.com/13235119/150835558-6d6c9a68-7d13-4735-804d-3fa268d10c75.png)

### Steps to reproduce

Set custom fonts.

### Minimal reproduction project

NS

**Comment by pycbouh** [comment]
It's not unfocused. It's just bold.

**Comment by git2013vb** [comment]
> It's not unfocused. It's just bold.

Maybe its "double" bold? 
Look in the 3.5:
![image](https://user-images.githubusercontent.com/13235119/150837422-6428db3b-bdeb-46b5-9655-cfcb506a0be9.png)
I see the bold one "Transform" and the normal one "Position". The difference in 3.5 between bold and normal is very clear while in 4.0 is to much.

**Comment by Calinou** [comment]
> Maybe its "double" bold?

No, it uses the bold font that you set in the editor settings. If you wish to disable this behavior entirely, set the same font file to be used both for the main font and bold font.

**Comment by pycbouh** [comment]
> Look in the 3.5:

Just to be clear: it wasn't bold in 3.x. It is bold in 4.x. It's one of the changes to the editor UI.

**Comment by git2013vb** [comment]
> > Look in the 3.5:
> 
> Just to be clear: it wasn't bold in 3.x. It is bold in 4.x. It's one of the changes to the editor UI.

OK, That's fine. The new look not very clear - also I changed fonts because the originals are to tick ;)  . There is a way to set the old one? The letters are not clear and to much attached each other. To set bold it was a not so lucky choice, in  my opinion.

**Comment by akien-mga** [comment]
As mentioned by @Calinou, you can set a non-bold font as "Main Font Bold" (i.e. in your case set "Terminus (TTF) 500.ttf" and it will be the same as in 3.x.

**Comment by git2013vb** [comment]
> As mentioned by @Calinou, you can set a non-bold font as "Main Font Bold" (i.e. in your case set "Terminus (TTF) 500.ttf") and it will be the same as in 3.x.

Oh. thanks .. I missed it  :)
