### ISSUE TITLE
[4.0] Editor don't save docks position

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#57142]
### Godot version

4.0alpha 1

### System information

Debian 11

### Issue description

When I close a project the docks positions are not saved

### Steps to reproduce

Create a empty project 
Move "Node" and "Inspector" dock like in picture then close project.

![image](https://user-images.githubusercontent.com/13235119/150844936-44ca43e1-d119-4801-821c-a3d6738237ee.png)

Reopen it and see where "Node" and "inspector" docks are.

### Minimal reproduction project

NA

**Comment by jmb462** [comment]
Cannot reproduce this issue, neither with alpha1 nor current master, neither under windows 10 and Linux (Ubuntu 21.10)

**Comment by KoBeWi** [comment]
I can reproduce in 90faf04
When you set the layout to the one in the screenshot, the Node dock will return to the right side after restart. Dock positions are saved properly, but looks like there are cases where they aren't. Also floating docks don't get saved at all; they return to their position before floating.
