### ISSUE TITLE
Description of properties in inspector are clipped

### ISSUE THREAD

**Issue by seppoday** [godotengine/godot#57146]
### Godot version

4.0 alpha 1

### System information

Windows 11

### Issue description

Description of properties in inspector are clipped
![Godot_v4 0-alpha1_win64_NQIGB1ZMIZ_description](https://user-images.githubusercontent.com/62170071/150853452-7cac4858-8617-4685-b129-c65119f11eba.png)

### Steps to reproduce

Add node that inherit from Control node and check anchor description.

**Comment by KoBeWi** [comment]
Closing in favor of #57174, which has more details.
