### ISSUE TITLE
Int slider in tree in theme editor preview show grey rectangle

### ISSUE THREAD

**Issue by seppoday** [godotengine/godot#57149]
### Godot version

4.0 alpha 1

### System information

Windows 11

### Issue description

While trying to click on slider in Theme Default Preview. Slider and input box changes to grey rectangle
![Theme editor preview tree in with slider problem](https://user-images.githubusercontent.com/62170071/150856171-75284d6c-6e87-4d98-9eae-ec5076586338.png)

Also, works fine in 3.4.2:
![image](https://user-images.githubusercontent.com/62170071/150856372-49eb267b-6ffd-4e56-8b0f-4dfaee26f72c.png)

### Steps to reproduce

Try to play with slider in tree in preview mode

**Comment by YuriSizov** [comment]
I can no longer reproduce it either.
