### ISSUE TITLE
[4.0] Not clear which script will be closed pressing "X" in editor

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#57145]
### Godot version

4.0alpha 1

### System information

Debian 11

### Issue description

When I have multiple scripts opened is not clear which one I will close if I click to the "X" in editor. See picture:
![image](https://user-images.githubusercontent.com/13235119/150848873-545346d1-512b-4305-8eaa-12e23a2ad5cd.png)

Obvious I know the main.gs is to save it. But  when we have multiple scrips that need to be saved and we will open a script the no need to be saved the first thing to came in my mind is to trigger the "x" to close it. But that "X" is not referred a single script (like any other editors they do).  I was expecting an "x" beside each file in list.

### Steps to reproduce

I create a script the I opened another file.

### Minimal reproduction project

NA

**Comment by pycbouh** [comment]
If you are referring to the cross in the tab above, it’s to close the scene. Scenes are represented by tabs, scripts are represented by list and have no cross icon to close them.

**Comment by git2013vb** [comment]
> If you are referring to the cross in the tab above, it’s to close the scene. Scenes are represented by tabs, scripts are represented by list and have no cross icon to close them.
> 
> It’s also the same in 3.x…

Yeah..  its the same in 3.x.. As I said I was expecting, finally, a change. We already have a icon at right side of tree node. The effort is to add an "x" the the right side of files list. It cant be difficult to add it. Isn't it?

**Comment by pycbouh** [comment]
> Yeah.. its the same in 3.x.. As I said I was expecting, finally, a change. We already have a icon at right side of tree node. The effort is to add an "x" the the right side of files list. It cant be difficult to add it. Isn't it?

For there to be a change, there needs to be a proposal first. That said, you can close scripts with a keyboard shortcut and context menu of the script list.

**Comment by KoBeWi** [comment]
> That said, you can close scripts with a keyboard shortcut and context menu of the script list.

Don't forget middle-click.

**Comment by git2013vb** [comment]
> > That said, you can close scripts with a keyboard shortcut and context menu of the script list.
> 
> Don't forget middle-click.

Yeah.. I have another way: CTRL+F4...
