### ISSUE TITLE
"No projects" popup appears behind the project manager window on macOS (DisplayServer regression)

### ISSUE THREAD

**Issue by jcov28** [godotengine/godot#57152]
### Godot version

4.0alpha1

### System information

MacOS Big Sur

### Issue description

After opening Godot 4alpha1, I cannot access the asset library. After clicking on it, the program crashes.

### Steps to reproduce

Go the Godot Project open area and then click Asset Library

**Comment by Calinou** [comment]
@jcov28 Did you find a solution to this problem? If so, please document it here by commenting :slightly_smiling_face:

**Comment by jcov28** [comment]
**Solution**: A popup windows asking if you want to open "Asset Library" opened behind the Godot Window and I did not see that.

**Comment by Calinou** [comment]
Reopening, as the popup shouldn't open behind the main window in the first place.
