### ISSUE TITLE
Match statement's Dictionary Pattern does not check the existence of keys (for the key-only case)

### ISSUE THREAD

**Issue by cdemirer** [godotengine/godot#57150]
### Godot version

4.0.alpha (fc09d783f)

### System information

Manjaro

### Issue description

The existence of keys does not contribute to the result if there isn't also a value to check.
```gdscript
func _ready():
    match {'A': 'a', 'B': 'b'}:
        {'Same size', 'Different contents (key-only)'}:
            print('It matched!')
```
```
It matched!
```

### Steps to reproduce

Reproducible snippet in Issue description.

**Comment by qtren** [comment]
Pure key matches also doesn't work in some cases... Try to run the following and you will be amazed..

`extends Node2D

func _ready():
	for i in range(1, 4):
		var num:String = str(i)
		match_dict({num:"!!! %s" % num})


func match_dict(d:Dictionary):
	print(d)
	match d:
		{"1"}:
			print("Matched 1")
			print(d["1"])
		{"2"}:
			print("Matched 2")
			print(d["2"])
		{"3"}:
			print("Matched 3")
			print(d["3"])
		{"4"}:
			print("Matched 4")
			print(d["4"])
`
