### ISSUE TITLE
Sun/Environment Preview and Label toolbar color pickers doesn't respect color picker shape and mode editor settings

### ISSUE THREAD

**Issue by fire-forge** [godotengine/godot#57154]
### Godot version

v4.0.dev.custom_build [e09881de9]

### System information

Windows 10, Vulkan

### Issue description

The color picker in the sun preview menu doesn't respect the Default Color Picker Mode and Default Color Picker Shape editor settings. This applies to all 3 color pickers in this menu (Sun, Sky, and Ground Color).

![image](https://user-images.githubusercontent.com/67974470/150864768-1c9bcabb-604d-4abf-bf20-f77a4a724900.png)

![image](https://user-images.githubusercontent.com/67974470/150864370-e3254744-3bee-45e3-8113-9ee662d0d0c9.png)

EDIT: This also applies to the Label toolbar:
![image](https://user-images.githubusercontent.com/67974470/151095043-cc523bd7-e8d8-450c-b723-aa7b8737d307.png)

### Steps to reproduce

* Change the Default Color Picker Mode and Default Color Picker Shape editor settings to something other than the default
* Open a color picker in the 3D Sun/Environment Preview menu

**Comment by Guh-Feng** [comment]
If this is to add the proposal code, then could I attempt this as a first contribution?

**Comment by fire-forge** [comment]
Yeah you can! Anyone can contribute, so go ahead.

**Comment by Guh-Feng** [comment]
#57402
