### ISSUE TITLE
Objects above a refraction material are also displayed as refraction

### ISSUE THREAD

**Issue by gitscher** [godotengine/godot#57160]
### Godot version

Godot 4.0 alpha 1

### System information

Windows 10 64bit Vulkan GeForce RTX 3080 Treiberversion 511.23

### Issue description

![Refraction](https://user-images.githubusercontent.com/94169968/150874140-30736504-5e43-48c7-9858-e6ca5f7dcc2f.png)
Objects above a refraction material are also displayed as refraction
#

![Refraction2](https://user-images.githubusercontent.com/94169968/150874146-663ef1f4-661c-40c9-a0d9-faccfa2da199.png)
at close range
#

![Refraction3](https://user-images.githubusercontent.com/94169968/150874152-2c872c90-8579-4536-a15b-58ca274013a5.png)
and when zoomed out. Is like an ilusion with a second cube in or below the refraction.

### Steps to reproduce

start the project and zoom in and out with the mausrat. then you can see it.

### Minimal reproduction project

[Refraction.zip](https://github.com/godotengine/godot/files/7929228/Refraction.zip)

**Comment by Calinou** [comment]
I can confirm this on `master` fc09d783f (Linux, NVIDIA 495.46).

This also occurs on `3.x` 49df809ca, although the effect isn't as severe there:

https://user-images.githubusercontent.com/180032/150879465-252d6fb7-2494-491d-b5e5-5b940eec45d9.mp4

**Testing project (`3.x`):** [Refraction-3.x.zip](https://github.com/godotengine/godot/files/7929422/Refraction-3.x.zip)

I wonder if some kind of rejection based on the depth buffer can be implemented. cc @clayjohn 
If not, I guess we'll have to document this as an inherent limitation of screen-space refraction.

**Comment by macryc** [comment]
Confirm this is still unresolved in Godot 4 alpha 4

**Comment by gitscher** [comment]
![refraction](https://user-images.githubusercontent.com/94169968/159168070-8e96649f-2687-480a-9c9d-bcdd927cb22d.png)

with Godot 4 alpha 4 it still does not look right.

**Comment by clayjohn** [comment]
When using SCREEN_TEXTURE all opaque objects are captured. I believe this is documented in a few places, but we should add more to the refraction section of the StandardMaterial3D docs https://docs.godotengine.org/en/latest/tutorials/3d/standard_material_3d.html#refraction
