### ISSUE TITLE
CollisionShape2D shape attribute is not animatable

### ISSUE THREAD

**Issue by POWERUPT** [godotengine/godot#57167]
### Godot version

3.4.2 stable

### System information

Windows 10, Ryzen 5 2600

### Issue description

It seems that the shape attribute of the collision shape 2d node is not animatable. When adding the attribute to the animation player, all of the keyframes are constantly synchronized, which means that no animation can happen because the values are always the same.
Before (x is 500; every keyframe is the same, hence the line between them):
![image](https://user-images.githubusercontent.com/36461106/150881833-7e00089d-acae-4fd2-be4b-470e21725e76.png)

After (x is now 100, but across all keyframes):
![image](https://user-images.githubusercontent.com/36461106/150881942-f1e52b00-7ce7-4417-87db-575892013cb9.png)

### Steps to reproduce

1. Make a new project with a collision shape 2d and an animation player.
2. Add a new shape to the collision shape.
3. Add keyframes to animation player of the shape attribute of the created project.
4. Attempt to change one keyframe. All will follow suit

### Minimal reproduction project

[Buggytest.zip](https://github.com/godotengine/godot/files/7929544/Buggytest.zip)

**Comment by POWERUPT** [comment]
Just thought I'd add that when I was first starting with Godot, I had the same issue with sprite animations, but since then I have not found it to be an issue. Just a heads up that it may exist as well, although I could not reproduce it.

**Comment by Calinou** [comment]
You need to add a keyframe on the shape resource's Extents property, not on the Shape resource itself.

**Comment by KoBeWi** [comment]
Yep, you need to animate the `extents`. Animating `shape` puts the Shape resource reference as keyframe. You can swap shapes this way, but not modify them.

**Comment by POWERUPT** [comment]
Hi,
When adding a keyframe there doesn't seem to be an extents property on the collision shape 2d, am I missing something?
![image](https://user-images.githubusercontent.com/36461106/150883067-a7a11b0f-7b80-43a1-9eef-f4aba36c6afd.png)
![image](https://user-images.githubusercontent.com/36461106/150883092-66e04b14-ff0b-4cd8-a83c-a71fa24f1131.png)

**Comment by KoBeWi** [comment]
See this issue #33807
Sub-resources don't appear on the list, you can add their keyframes by clicking the key icon next to them.
![image](https://user-images.githubusercontent.com/2223172/150883409-ee775c4a-b9b5-438e-aef3-1f18afae4d95.png)
If you don't see a key icon, make sure your Animation tab at the bottom is expanded.

**Comment by POWERUPT** [comment]
Alright, thank you for the help!
