### ISSUE TITLE
Previously Opened Class Reference pages empty after restarting Godot

### ISSUE THREAD

**Issue by ranmaru90** [godotengine/godot#5716]
**Operating system or device - Godot version:**
Windows 10 Pro. Latest from GitHub repo.

**Issue description** (what happened, and what was expected):
When scripting, if I search help or open a class reference page, I can read about that class. Right after I saved the project and restarted Godot, then opened that same project again, that class reference page is opened but it displays nothing. I have to close it and then look it up again for it to show the text again.

**Steps to reproduce:**
1. Create a new project, make a scene, put a script on a node, edit the script.
2. Click "Search Help" in the script editor, open a page. Or click on "Classes" and open a page.
3. Now, don't close the opened help page. Save the project and exit Godot.
4. Open Godot again and open back the same project just now. You'll notice that help or class reference page is still opened, as it shows up in the list, but it is empty on the right side.

**Comment by vnen** [comment]
I noticed this too and it's very recent.
