### ISSUE TITLE
Evaluating script snippets in editor gives incorrect result when using hexadecimal/binary literals

### ISSUE THREAD

**Issue by Haydoggo** [godotengine/godot#57171]
### Godot version

v4.0.alpha1.official [31a7ddbf8]

### System information

Windows 10

### Issue description

In the script editor, evalutaing a code snippet (Ctrl+Shift+E) involving a hex or binary literal such as `0xf4` or `0b11110100` sometimes incorrectly evalutates to `0`.

![image](https://user-images.githubusercontent.com/14885846/150888196-1e6e40fc-14df-43b5-8325-d0992958697e.png)

### Steps to reproduce

Current behaviour:

1. Evalutating any mathematical operating involving one or more hex or binary literals evaluates to `0`.
I'd expect example this to evaulate to either `0xf5` or `245`, or to cause no change to stay consistent with examples 2 and 3.
`0xf4 + 0x01` -> `0`
`0xf4 + 1` -> `0`

2. Evalutaing a hex literal by itself causes no change. 
I'd expect this example to evaluate to `244` but that's a design decision rather than a bug
`0xf4` -> `0xf4`

3. Evaluating a snippet using a hex or binary literal in a function causes no change.
`sqrt(0x04)` -> `sqrt(0x04)`
`sqrt(0x04 * 2)` -> `sqrt(0x04 * 2)`

**Comment by Calinou** [comment]
My guess is that this happens because the Expression class doesn't support hexadecimal number literals (and binary number literals, which are also supported in GDScript).
