### ISSUE TITLE
Tooltip boxes not expanding correctly to show multiple lines in editor.

### ISSUE THREAD

**Issue by snailrhymer** [godotengine/godot#57174]
### Godot version

4.0.alpha1.official

### System information

Windows 10

### Issue description

Property tooltip boxes often cut through a line of text:

![image](https://user-images.githubusercontent.com/61291296/150894762-895a44e8-71ec-485a-ba28-92cba6a8299b.png)

![image](https://user-images.githubusercontent.com/61291296/150894803-d3fa9254-7c28-4e2f-9124-81afa9d94a51.png)

The tooltip's size is not consitent, nor is the 'cut hieght':

![image](https://user-images.githubusercontent.com/61291296/150894946-fe92a872-32a1-45bc-9343-0112a91ed0b7.png)

It looks like only single-line tooltips display properly:

![image](https://user-images.githubusercontent.com/61291296/150895258-e581be8d-6ecc-44ce-a33b-947e9d385c30.png)

Altering Windows' app scaling (this settings option:
![image](https://user-images.githubusercontent.com/61291296/150896899-7255f90b-d3bb-472a-be93-5e55b5e1b89a.png)) didn't change the behaviour.

### Steps to reproduce

Open the editor and mouseover a property in the inspector.

**Comment by Chaosus** [comment]
Hmm, I think you can use mouse scrolling now to see the full content of the tooltip.

**Comment by Zireael07** [comment]
@Chaosus: Not everyone has a mouse (I don't, I use a trackpad)

**Comment by Chaosus** [comment]
I guess you can use scrolling by finger too (I cannot test it since I don't have a trackpad):
![test](https://user-images.githubusercontent.com/3036176/151655238-6cbf9479-3d28-4744-9fa5-4c40dce57577.gif)

**Comment by akien-mga** [comment]
It should be possible to calculate the popup size to fit the contents, and maybe just have a max size for very long descriptions to give them a scrollbar.

**Comment by akien-mga** [comment]
I tested some pre-alpha builds, the size issue started between 4.0-dev.20210727 (b4778082d) and 4.0-dev.20210811 (7188cb601): https://github.com/godotengine/godot/compare/b4778082d...7188cb601

**Comment by akien-mga** [comment]
Bisected, it's a regression from #51619. Proves that going for a hack is always going to bite us back :)
CC @Chaosus @godotengine/gui-nodes

**Comment by Chaosus** [comment]
@akien-mga Are you sure? - I reverted it and see no difference - 
![image](https://user-images.githubusercontent.com/3036176/152157430-908e3c0b-d36f-4f57-96ab-7402b45af02f.png)

**Comment by bruvzg** [comment]
Can't test it right now, but seems like RTL in the `EditorHelpBit` do not have `fit_content_height` set, so it's not calculating min. height, which was broken before `#57304` and was updating only after multiple redraws. This might what's causing this be an issue.

**Comment by akien-mga** [comment]
That was the result of the bisect yes, so I'm pretty sure that it caused the regression. But indeed reverting it does not fix the issue in current `master`, probably because the tooltip now has a scrollbar (which was not the case just a couple of weeks ago in 4.0 alpha 1). I assume the scrollbar was added via #57304.

**Comment by akien-mga** [comment]
Adding `set_fit_content_height(true)` does seem to solve the issue (without reverting #51619, which reintroduces the color issue).

**Comment by akien-mga** [comment]
> Adding `set_fit_content_height(true)` does seem to solve the issue (without reverting #51619, which reintroduces the color issue).

I spoke too fast. With only #57547 the bug is still reproducible. I need both to revert #51619 and enable `set_fit_content_height` to solve it.
