### ISSUE TITLE
Godot 4.0 alpha 1 startup crash on Windows 11 with Nvidia Quadro K1000M

### ISSUE THREAD

**Issue by iwangxiaodong** [godotengine/godot#57180]
### Godot version

v4.0.alpha1.official

### System information

Windows 11, Vulkan 1.1.95, NVIDIA Quadro K1000M

### Issue description

Godot 4.0 alpha 1 startup crash/white screen.

### Steps to reproduce

./Godot_v4.0-alpha1_win64_console.cmd or ./Godot_v4.0-alpha1_win64.exe

### Minimal reproduction project

double click - Godot IDE 4.0 alpha 1 exe

**Comment by akien-mga** [comment]
> Windows 11, Vulkan 1.1.95, NVIDIA Quadro K1000M

You seem to have a very old version of Vulkan (released in 2018). Could you try to update your Nvidia GPU drivers?

**Comment by iwangxiaodong** [comment]
![image](https://user-images.githubusercontent.com/16535878/150937085-90a37b38-8127-44ee-b127-c7d537fa0e34.png)

I has been upgraded latest Nvidia GPU driver.

**Comment by iwangxiaodong** [comment]
![image](https://user-images.githubusercontent.com/16535878/150939121-1ff59085-2417-4ee4-98ef-afd10eda41f4.png)

After run, print this info.

thanks.

**Comment by KoBeWi** [comment]
@iwangxiaodong Does it still crash in alpha 7?

**Comment by iwangxiaodong** [comment]
@KoBeWi
![20220501195705](https://user-images.githubusercontent.com/16535878/166144773-4f33bead-34b3-4e66-8ac9-ebae1a2d9327.png)

**Comment by iwangxiaodong** [comment]
Use Godot 4.0 alpha 9 in my PC：

  .\Godot_v4.0-alpha9_win64.exe  --rendering-driver opengl3 -v

![QQ截图20220604155213](https://user-images.githubusercontent.com/16535878/171990243-8a04ae91-c102-4c47-a082-4fa49c301b19.png)

I can open first window, But still can't open the editor main window.


**Maybe:**
  Windows: Improve OpenGL3 driver support, including multiple windows ([GH-60894](https://github.com/godotengine/godot/pull/60894)).

@Calinou @KoBeWi

**Comment by Knand1861** [comment]
with godot.4.11a, what do I do? (https://github.com/godotengine/godot/pull/60894)

**Comment by iwangxiaodong** [comment]
![image](https://user-images.githubusercontent.com/16535878/187661074-18309b6c-5f29-49a0-b2f1-92b1086d368f.png)

.\Godot_v4.0-alpha15_win64.exe  --rendering-driver opengl3

It works!

@Calinou @Knand1861 @KoBeWi

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/58927, as NVIDIA mobile Kepler GPUs don't have Vulkan support (unlike desktop Kepler GPUs).
