### ISSUE TITLE
Error: "Shortcut context node can't be null" when duplicating node

### ISSUE THREAD

**Issue by lemon37564** [godotengine/godot#57188]
### Godot version

v4.0.alpha1.official.31a7ddbf8

### System information

Linux, Vulkan mobile, Nvidia GTX1050 mobile

### Issue description

error shows in the debug terminal when duplicating node, with message: 
```
E 0:00:00:0218   _ready: Shortcut context node can't be null.
  <C++ Error>    Parameter "p_node" is null.
  <C++ Source>   scene/gui/base_button.cpp:385 @ set_shortcut_context()
  <Stack Trace>  test.gd:5 @ _ready()
```
![image](https://user-images.githubusercontent.com/65079334/150973521-62485a3e-a656-468f-89c9-a6f238bcd4b4.png)

### Steps to reproduce

1. create a GridContainer, set columns to 10
2. create a Button as a child node of GridContainer
3. duplicate the button and then add_child(button)
4. example code below

```gdscript
extends GridContainer

func _ready():
	for i in range(99):
		var node := $Button.duplicate()
		self.add_child(node)
```

### Minimal reproduction project

[test-gd4.zip](https://github.com/godotengine/godot/files/7933349/test-gd4.zip)

**Comment by akien-mga** [comment]
CC @godotengine/gui-nodes
