### ISSUE TITLE
Tabs control glitch

### ISSUE THREAD

**Issue by filantus** [godotengine/godot#57181]
### Godot version

v3.5.beta1.official [b9b23d222]

### System information

Windows 10, GLES3

### Issue description

If set tabs switching by hovering on them, and move mouse only on first two, then sometimes tabs not under mouse suddenly selected.

Also in that case, method get_tab_rect periodically returns different result.

### Steps to reproduce

Full example attached in project.zip

Add Tabs control
Create script on Tabs
Create several tabs in script
Connect tab_hover signal to script and make here setting current_tab by recieved tab argument.

### Minimal reproduction project

https://user-images.githubusercontent.com/13046849/150940905-f0d3b5f2-ac30-4b9f-ba74-7dc520fbf32f.mp4

[project.zip](https://github.com/godotengine/godot/files/7931889/project.zip)

**Comment by filantus** [comment]
Great job! Thank you! This fix will be backported in 3.x? @YeldhamDev

**Comment by YeldhamDev** [comment]
@filantus Unlikely for now, as this was fixed as the result of a near complete rewrite of the tab system.
