### ISSUE TITLE
4.0 alpha 1 problem with editor in full screen mode

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#57184]
### Godot version

v4.0.alpha1.official [31a7ddbf8]

### System information

w10 64 radeon vega 8

### Issue description
Video capture in full screen mode seems to have problems but I guess they are out of Godot's control, the screen will go completely black at times.

When you go full screen and hold your cursor for a description (on the button to play the scene) these things appear
You will need to pause the video at 0:00:07 (at 7 seconds) and look at the top edge of the window, then continue playback and note at 0:00:11 that the error message appeared.

https://user-images.githubusercontent.com/19652075/150949542-a3ce103a-03a8-47a5-87be-9e644ef5b11c.mp4

![Captura2](https://user-images.githubusercontent.com/19652075/150949824-5014a6f4-52ed-48fd-8eb9-aaa470ece29b.PNG)

### Steps to reproduce

Enter in full screen mode
Hover (and hold) the cursor over the play scene icon to get the description.

### Minimal reproduction project

...

**Comment by akien-mga** [comment]
It doesn't seem reproducible for me on Mageia Linux with KDE Plasma desktop and AMD Radeon RX Vega M (Mesa 21.3.4).
The issue might be Windows specific.

**Comment by CaelusV** [comment]
win10, nvidia 1060 6gb
v4.0.alpha1.official [31a7ddbf8]

While in fullscreen, hovering for a description produces flashes of black screen.
Clicking on any button with a dropdown menu seems to produce temporary black screens.
Recording in OBS shows black screen almost the entire time while in fullscreen – like in the original video by OP.
NVIDIA Shadowplay produces a much more interesting result, with the ENTIRE screen being filled up by the description when hovering a button. [Recording](https://www.youtube.com/watch?v=eTVZvsHopuE)

This does not occur while fullscreen mode is disabled.

**Comment by DaSlang** [comment]
Something similar also happens on MacOS (BigSur 11.6.2) using Godot 4 Alpha 1 `31a7ddbf8`.

When in fullscreen mode, editor tooltips are not shown correctly:

https://user-images.githubusercontent.com/37884619/151239419-97e59fd8-188a-4555-b461-bd9f1028e8e6.mov

Everything works fine if the fullscreen mode is disabled.

It's also worth noticing that everything is ok when using Godot v3.4.stable.official `206ba70f4`.

**Comment by DaSlang** [comment]
Adding the flag `FLAG_ALWAYS_ON_TOP` to `true` in the `Popup` constructor seems to fix it, at least on MacOS.

https://user-images.githubusercontent.com/37884619/151438979-979682be-a31f-4421-a799-b9a531cd9343.mov

If this can be a sensible answer, I can test this a little bit more and make a pull request if everything works 😄

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by bruvzg** [comment]
It was fixed on macOS for popups, I guess tooltip windows do not have `transient` flag set.

**Comment by bruvzg** [comment]
Tooltip transient flag is set to `false`, changing it to `true` will fix tooltips on macOS. But it might be set to `false` for a reason (need to be tested on other platforms).
https://github.com/godotengine/godot/blob/46053a1be9cc1bc4957280cc76602aead421884c/scene/main/viewport.cpp#L1228

Not sure if it's possible to have other windows on top of full-screen on Windows, I'll experiment with the different window flags, but there's no obvious way to do it.

**Comment by bruvzg** [comment]
It's not an elegant solution, but I do not think it's possible to have it working in exclusive full-screen, either set interface to single-window mode, or #57341.
