### ISSUE TITLE
Fails to build with musl libc, undefined reference to `backtrace'

### ISSUE THREAD

**Issue by 0x6273** [godotengine/godot#57193]
### Godot version

4.0 alpha 1, commit 2b61d02f7ef5cd820020747f55107c6339324495

### System information

Gentoo, with musl libc overlay

### Issue description

When linking, it does not find `backtrace` or `backtrace_symbols`. Unlike glibc, the musl libc does not come with those symbols.

From SCons output:
```
[100%] Linking Static Library core/libcore.linuxbsd.tools.64.a ...
Ranlib Library core/libcore.linuxbsd.tools.64.a ...
[100%] Linking Program bin/godot.linuxbsd.tools.64 ...
/usr/lib/gcc/x86_64-gentoo-linux-musl/11.2.0/../../../../x86_64-gentoo-linux-musl/bin/ld: platform/linuxbsd/crash_handler_linuxbsd.linuxbsd.tools.64.o: in function `handle_crash(int)':
/home/user/Projects/godot/platform/linuxbsd/crash_handler_linuxbsd.cpp:56: undefined reference to `backtrace'
/usr/lib/gcc/x86_64-gentoo-linux-musl/11.2.0/../../../../x86_64-gentoo-linux-musl/bin/ld: /home/user/Projects/godot/platform/linuxbsd/crash_handler_linuxbsd.cpp:80: undefined reference to `backtrace_symbols'
collect2: error: ld returned 1 exit status
scons: *** [bin/godot.linuxbsd.tools.64] Error 1
scons: building terminated because of errors.
[Time elapsed: 00:04:45.680]
```

### Steps to reproduce

1. Have musl libc, and libexecinfo installed
2. Clone repo
3. Run scons

**Comment by 0x6273** [comment]
I managed to find a workaround, patching one of the `SCsub` files. But this is not a proper fix, since it would likely break builds for glibc users.

```diff
diff --git a/platform/linuxbsd/SCsub b/platform/linuxbsd/SCsub
index cec8706fbc..dad19a90d1 100644
--- a/platform/linuxbsd/SCsub
+++ b/platform/linuxbsd/SCsub
@@ -30,3 +30,6 @@ prog = env.add_program("#bin/godot", ["godot_linuxbsd.cpp"] + common_linuxbsd)

 if env["debug_symbols"] and env["separate_debug_symbols"]:
     env.AddPostAction(prog, run_in_subprocess(platform_linuxbsd_builders.make_debug_linuxbsd))
+
+
+env.Append(LIBS=["execinfo"])
```

**Comment by 0x6273** [comment]
> Did you try build with `execinfo=yes`?

I have not tried that, but I got it to link by patching the `SCsub` file in `platform/linuxbsd`. I'm not very familiar with `SCons`, but would it be possible to set this automatically for systems that need execinfo?

**Comment by akien-mga** [comment]
That's already what the code does:
```
    if platform.system().find("BSD") >= 0:
        env["execinfo"] = True

    if env["execinfo"]:
        env.Append(LIBS=["execinfo"])
```

You just need to build with `scons p=linuxbsd execinfo=yes`.

I don't know if there's an easy way to detect the need for `execinfo` on GNU/Linux. If there's a reliable way to check from Python, this could be added to the same check that looks for *BSD.

**Comment by 0x6273** [comment]
I'm not sure if there's a good way to test if libexecinfo is needed. Adding another special case for musl like we already have for BSD is probably the simplest fix.

There's a file `/lib/ld-musl-$ARCH.so.1` on musl systems, so something like this would work:
```python
if glob.glob("/lib/ld-musl-*.so*"):
    env["execinfo"] = True

**Comment by LinuxUserGD** [comment]
See https://github.com/godotengine/godot-proposals/issues/2439
