### ISSUE TITLE
Command line not prompting error on invalid path

### ISSUE THREAD

**Issue by albinaask** [godotengine/godot#57194]
### Godot version

3.4, 4.0a (supposedly)

### System information

Windows 10, AMD Ryzen 2700x, Nvidia 1070ti

### Issue description

Running godot from command line, having godot in PATH, running `godot -e --path <some invalid path>` with invalid path just opens the project manager, not prompting what is wrong in terminal. To make matters worse it starts in low DPI, which looks awful.

### Steps to reproduce

1. Add godot to PATH
2. run `godot -e --path <some invalid path>`
3. Observe incorrect behavior

**Comment by Calinou** [comment]
> To make matters worse it starts in low DPI, which looks awful.

This is likely because the editor-specific codepath isn't triggered when doing this, which means hiDPI support is not forced. This won't be an issue anymore in 4.0 thanks to https://github.com/godotengine/godot/pull/29553.
