### ISSUE TITLE
Script Editor text becomes invisible if first line is empty

### ISSUE THREAD

**Issue by FreegleBarr** [godotengine/godot#57204]
### Godot version

4.0.alpha [30701e3966]

### System information

Ubuntu 20.04, Vulkan Clustered, NVIDIA GeForce MX350

### Issue description

When the first line of any GDScript file is empty, the entire script text becomes invisible. I have also sporadically noticed this happening when opening Shader and GDScript files that didn't have the first line empty, but could not reproduce.

### Steps to reproduce

Open a GDScript file, to the first line, and press enter so that the `extends` default line is on line 2. This should  make the entire script invisible. If undone, the script should become visible again.

### Minimal reproduction project

[TextBug.zip](https://github.com/godotengine/godot/files/7934803/TextBug.zip)

**Comment by Calinou** [comment]
I can confirm this on `master` fc09d783f (but not on 3.4.2).

https://user-images.githubusercontent.com/180032/151006472-6b38d9cd-ade5-468b-86de-5ada211352d8.mp4
