### ISSUE TITLE
ImmediateGeometry::cached_texture is unused

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#5720]
**Operating system or device - Godot version:**
2.0.4.1
and according to current source code

**Issue description** (what happened, and what was expected):

By reading the source code, i've found that ``ÌmmediateGeometry::cached_texture`` is unused, and that it makes the ``texture`` parameter of ``ImmediateGeometry.begin()`` totally useless.

related to #5676 

**Steps to reproduce:**

https://github.com/godotengine/godot/search?utf8=%E2%9C%93&q=cached_textures&type=Code

**Link to minimal example project** (optional but very welcome):

**Comment by reduz** [comment]
It is not unused, it needs to be kept by the node. If not kept, it may be erased if no longer used and the texture stored in the VisualServer will become invalid.

**Comment by SuperUserNameMan** [comment]
Okay, so after talking with @reduz on IRC, the texture parameter can be used to override the texture of the material attached to the ImmediateGeometry.

If you attach a FixedMaterial to your geometry, this material will need at least a diffuse texture or detail texture, or the passed as texture parameter will be ignored.

By default, the geometry node uses the default material which has no texture. 
That's why the texture parameter seemed useless.
