### ISSUE TITLE
Bezier curves do not work properly in Animation Player

### ISSUE THREAD

**Issue by Wokarol** [godotengine/godot#57201]
### Godot version

v4.0.alpha1.official [31a7ddbf8]

### System information

Windows 10

### Issue description

The bezier curve tracks do not work as expected and appear to be broken.

1. Adding key does not work completely
2. Rotation seems to be represented in radians despite it being shown in degrees for non bezier tracks

The error that shows when the attempt to create a key is made:
` scene/resources/animation.cpp:1628 - Condition "arr.size() != 6" is true.
Anim Create & Insert `.
Hence the only option is to create the keys from within the bezier curve editor.

### Steps to reproduce

1. Create empty project
2. Add 2D node with any sprite for visuals
3. Try to create a rotating animation

### Minimal reproduction project

[BrokenAnimations.zip](https://github.com/godotengine/godot/files/7934730/BrokenAnimations.zip)

**Comment by TokageItLab** [comment]
May fixed by #55030.

**Comment by Razoric480** [comment]
It should fix number 1.

2 will need to be addressed separately, since rotation_degrees was removed in favour of the inspector magically converting it. The animation editor as a whole needs to be updated to also do that magic.

**Comment by Wokarol** [comment]
> 2 will need to be addressed separately, since rotation_degrees was removed in favour of the inspector magically converting it. The animation editor as a whole needs to be updated to also do that magic.

Actually, I dig some digging and file editing. Seems like animation editor for non-bezier keys does in fact have that inspector magic while the bezier one does not

**Comment by Razoric480** [comment]
Ah. Might have missed it, then - I'll have to take a quick look.

**Comment by TokageItLab** [comment]
As for the rotation, I've been discussing with @reduz for a while now that the incompatibility of Node3D RotationMode and animation is a problem.

For example, if you record an animation of the Node3D in YXZ using RotationMode: Euler, but change the Euler Order of the object to XYZ, the animation will break. So we discussed that all 3D rotations should be recorded in Quaternion in the animation, but Bezier track separates each element. And that means setting the Quaternion manually.

...This makes it unusable, so we may need a special track, like BezierRotationTrack...?

**Comment by AntonioDell** [comment]
The rotation being displayed in degrees but behaving like radians is still an issue with 4.0.beta2.
Just wanted to check if there is still a need for discussion on how to fix this, or if someone (maybe me) can tackle the issue simply by introducing the radians-degree magic of the property track into the bezier track?

**Comment by Razoric480** [comment]
I'm not planning on doing it, as my timetable is pretty full already, but I think making it more user-usable would be a good idea.

**Comment by TokageItLab** [comment]
Fixed by #55030.
