### ISSUE TITLE
transparent_bg on SubViewport Not Transparent when 3D enabled

### ISSUE THREAD

**Issue by ccuntd** [godotengine/godot#57213]
### Godot version

v4.0.alpha.custom_build [310266051]

### System information

Linux, Vulkan

### Issue description

title

### Steps to reproduce

mash stuff together and do

### Minimal reproduction project

[NOTPBG.zip](https://github.com/godotengine/godot/files/7935870/NOTPBG.zip)
(this one has a cube on layer 2 (top one) and one on layer one (in the middle, which is invisible, because the subviewport also renders skybox (even without enviroment and sun)))

**Comment by Chaosus** [comment]
Duplicate of https://github.com/godotengine/godot/issues/40651

**Comment by CrezyDud** [comment]
thanks, didn't find it when searching if already reported
