### ISSUE TITLE
SamplePlayer: Pitch Random feature like in SamplePlayer2D

### ISSUE THREAD

**Issue by timoschwarzer** [godotengine/godot#5721]
I didn't look at the code, but would it be hard to implement or just a C&P job? (Then I would take a look at it...)

**Comment by ret80** [comment]
https://github.com/godotengine/godot/blob/master/scene/2d/sample_player_2d.cpp
function: SamplePlayer2D::play(const String& p_sample,int p_voice);
You can easily implement the same script for: SamplePlayer

**Comment by RayKoopa** [comment]
I don't think this is current anymore, isn't this implemented via `AudioStreamRandomPitch` for both?

**Comment by akien-mga** [comment]
Indeed, fixed in 3.0 with the audio engine rewrite.
