### ISSUE TITLE
Cyclic resource error when saving .cs file in external editor

### ISSUE THREAD

**Issue by markdibarry** [godotengine/godot#57211]
### Godot version

4.0 alpha1

### System information

Windows 10

### Issue description

If a `.cs` file is open in an external editor and saved, the following error will appear in the Godot output.
![image](https://user-images.githubusercontent.com/21325943/151028203-91b1e026-e262-4766-b916-66f44a6fbc0d.png)

As recommended by @Calinou this is a new version of the same bug mentioned in #27257

### Steps to reproduce

Create new C# project.
Open project in external editor like VSCode.
Save a .cs file.
Refocus back to Godot.

### Minimal reproduction project

[CyclicCSBug.zip](https://github.com/godotengine/godot/files/7935830/CyclicCSBug.zip)

**Comment by L2750558108** [comment]
So when will this issue be resolved? It's been 1 year ...

**Comment by AThousandShips** [comment]
@L2750558108 contributors work at their own pace, no one is paid to do this

**Comment by nongvantinh** [comment]
Couldn't reproduce this bug from master branch at commit 0cce6eb1505f7dd9c0cece2a825b1509cf23f158

**Comment by markdibarry** [comment]
Hasn't been reproducible in ages. Closing.
