### ISSUE TITLE
[3.x] Editor doesn't allow to set mass/weight of RigidBody/RigidBody2D node more than 65535

### ISSUE THREAD

**Issue by Fitch24** [godotengine/godot#57226]
### Godot version

Godot_v3.4.2-stable_win64

### System information

Windows 10 x64

### Issue description

The mass (and weight) property of RigidBody is a float. But in the Editor it's looks like an unsigned short (2-bytes integer). If you try to set mass of RigidBody more than 65535 in the Inspector view, then value will be clamped to 65535. But in script you can set mass to any positive float value and it will be valid (not clamped and works as expected).

### Steps to reproduce

1. Open/Create any project.
2. Open/Create any scene with RigidBody or RigidBody2D node
3. Try to set mass or weight property to 100000 in Inspector

**Comment by akien-mga** [comment]
Fixed by #57242 (also fixed a while ago in `master`).
