### ISSUE TITLE
Visual Script still has the old yielding system

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#57237]
### Godot version

b25c7fe

### System information

N/A

### Issue description

Godot 4 has replaced `yield` with `await`, and with this, removed things like `GDScriptFunctionState` (R.I.P.). Visual Script however, still has nodes such as `VisualScriptYield`, and `VisualScriptFunctionState`, which can be confusing due to the difference with GDScript.

### Steps to reproduce

Search for those nodes in the Visual Script.

**Comment by Anaxan** [comment]
Just in case anybody is not aware - Yield is currently broken in both 3 and 4. So it is more than just a rename required.

We had a discussion about this issue in discord a few months ago so there is definitely community interest.

If any developer is willing to fix this and you require a tester please don't hesitate to ask.

**Comment by Gallilus** [comment]
https://github.com/godotengine/godot-proposals/issues/3036

**Comment by YeldhamDev** [comment]
Closing, as VisualScript is no more.
