### ISSUE TITLE
Transform not taken into account on 3D navmesh baking 

### ISSUE THREAD

**Issue by Scony** [godotengine/godot#57231]
### Godot version

3.x (f2ec36fbcd486badcdca363d95be1f28b5f25e07)

### System information

manjaro linux

### Issue description

When baking 3D navigation mesh using `Both` geometry type and `Group Explicit` source geometry, the transforms of `Spatial` nodes which are holding the meshes/static colliders are not taken into account and thus geometry is misplaced.

![2022-01-25-231223_4480x1440_scrot](https://user-images.githubusercontent.com/1207385/151069165-3c1d71c5-29e4-4e9b-be0a-49d1d91ef46b.png)

### Steps to reproduce

Run `SimpleNavmeshBaking` scene from demo project below

### Minimal reproduction project

[godot-navigation-demos.zip](https://github.com/godotengine/godot/files/7937581/godot-navigation-demos.zip)

**Comment by akien-mga** [comment]
Fixed by #57440.
