### ISSUE TITLE
Godot 4.0alpha1: Linux Kubuntu crashes and works slow.

### ISSUE THREAD

**Issue by chriztheanvill** [godotengine/godot#57243]
### Godot version

4.0.alpha1.official

### System information

Kubuntu 21.10, vulkan, Intel UHD Graphics 620 (rev 07)

### Issue description

In 2D or 3D.
Crashes, works too slow on menus.
Some textures does not appear (Imported project from Godot 3).

And shows this message:
E 0:00:00:0662   _debug_messenger_callback: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
	loader_scanned_icd_add: Could not get 'vkCreateInstance' via 'vk_icdGetInstanceProcAddr' for ICD libGLX_nvidia.so.0
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 141920496
  <C++ Source>   drivers/vulkan/vulkan_context.cpp:157 @ _debug_messenger_callback()

### Steps to reproduce

Just open Godot.
Open menus.

**Comment by Calinou** [comment]
This is likely an issue with your system drivers: https://github.com/godotengine/godot/issues/49358

**Comment by chriztheanvill** [comment]
> This is likely an issue with your system drivers: #49358
> 
> > Some textures does not appear (Imported project from Godot 3).
> 
> Materials need to be set up again when converting a project from Godot 3 to Godot 4, at least until #51950 is merged.

Hi @Calinou 
My laptop has intel (integrated) and nvidia card, and only use intel, but I have installed nvidia-driver-470.
Should I have to uninstall the nvidia-driver?

**Comment by Calinou** [comment]
> My laptop has intel (integrated) and nvidia card, and only use intel, but I have installed nvidia-driver-470.
Should I have to uninstall the nvidia-driver?

If you don't intend on using the dedicated GPU at all, I would recommend removing the NVIDIA driver.

**Comment by chriztheanvill** [comment]
@Calinou 
I uninstalled many drivers. These are the last. What should I have to uninstall?


- conky-all/impish,now 1.11.6-2 amd64 [installed]
- dmraid/impish,now 1.0.0.rc16-8ubuntu5 amd64 [installed]
- libnvidia-compute-470/impish-updates,impish-security,now 470.86-0ubuntu0.21.10.1 amd64 [installed]
- libvdpau1/impish,now 1.4-3build1 amd64 [installed,automatic]
- libxnvctrl0/impish,now 470.57.01-0ubuntu3 amd64 [installed,automatic]
- nvidia-prime/impish,impish,now 0.8.17.1 all [installed]
- nvidia-utils-470/impish-updates,impish-security,now 470.86-0ubuntu0.21.10.1 amd64 [installed]
- ubuntu-drivers-common/impish,now 1:0.9.2.2 amd64 [installed,automatic]
- vdpau-driver-all/impish,now 1.4-3build1 amd64 [installed,automatic]
- xserver-xorg-video-nouveau/impish,now 1:1.0.17-1build1 amd64 [installed,automatic]
-

**Comment by Calinou** [comment]
> I uninstalled many drivers. These are the last. What should I have to uninstall?

If in doubt, leave those packages installed.

**Comment by chriztheanvill** [comment]
> > I uninstalled many drivers. These are the last. What should I have to uninstall?
> 
> It looks like some of those packages may be leftover dependencies (which may be removed using `sudo apt autoremove`). You should definitely keep `ubuntu-drivers-common` and `xserver-xorg-video-nouveau` though.

Just launching vkcube and Godot 4 shows this message:
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

I used this command:
sudo sysctl dev.i915.perf_stream_paranoid=0

The Mesa-intel warning does not show, but godot 4 its still slower than godot 3.

**Comment by Calinou** [comment]
> The Mesa-intel warning does not show, but godot 4 its still slower than godot 3.

Glow is enabled by default in 3D, which is likely why the editor runs slowly. https://github.com/godotengine/godot/pull/49736 disables it by default again (like in Godot 3.x).

**Comment by chriztheanvill** [comment]
After trying.
Godot 4 crashes my PC, 2D or 3D project.
In 2D runs kind of slower than Godot 3, but in 3D it runs more slower than Godot 3, no matter if is glow activated or tonemap.

**Comment by Hoxolotl** [comment]
Issue still exists on Alpha 13, both self compiled and "official version":

On starting godot from the command line in Manjaro (Arch).

`Godot Engine v4.0.alpha13.official.59dcddc45 - https://godotengine.org
ERROR: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        loader_scanned_icd_add: Could not get 'vkCreateInstance' via 'vk_icdGetInstanceProcAddr' for ICD libGLX_nvidia.so.0
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 131830512
   at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:171)
Vulkan API 1.2.0 - Using Vulkan Device #0: AMD - AMD RADV NAVY_FLOUNDER
`
Yes it's a different AMD video card on an asus Strix 15 laptop. Same error thaugh.

**Comment by akien-mga** [comment]
Do you have both Nvidia and AMD cards in the same laptop? Or why do you have Nvidia's proprietary Vulkan drivers installed?

**Comment by Hoxolotl** [comment]
I have the default manjaro drivers installed. Looks like those default drivers are the nvidia ones -somehow-
AMD GPU and CPU in this laptop, so I have no idea how nvidia got in. Guess I'm off to see if I can change that... last time I tried to install AMD Vulkan drivers it almost bricked my laptop so I'll be a bit carefull about installing/removing anything.

pacman -Qqs vulkan                                                                                                                                                                                                                        
lib32-vkd3d
lib32-vulkan-icd-loader
lib32-vulkan-intel
lib32-vulkan-radeon
nvidia-utils
spirv-tools
vkd3d
vulkan-headers
vulkan-icd-loader
vulkan-intel
vulkan-radeon
vulkan-tools

**Comment by Hoxolotl** [comment]
Removed all nvidia stuff, seems I installed it way back because my numpty brain wanted to try using CUDA...
Godot 4 alpha13 still crashes, but for new and interesting reasons not related to this issue. 
Thanks [akien-mga](https://github.com/akien-mga)! That was spot on.

**Comment by clayjohn** [comment]
This appears to be a driver issue on the users end. At any rate there is nothing actionable as the report isn't clearly a bug. If someone runs into a similar sounding issue, please open a new issue with a clear description of your hardware and what settings are required to cause the slowdown/crash
