### ISSUE TITLE
[3.x] ViewportPreview upside-down

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#57246]
### Godot version

3.4.2.stable & 3.x (b18a7f5220)

### System information

Arch Linux, GLES 3, Mesa Intel(R) UHD Graphics (CML GT2)

### Issue description

ViewportPreview is upside-down compared to the corresponding `ViewportTexture`.

| `Viewport.render_target_v_flip` | Off | On |
|----|----|----|
| Screenshot | ![ksnip_20220126-170105](https://user-images.githubusercontent.com/372476/151133555-ae4a0b14-808a-4e74-9443-9e13e359669e.png) | ![ksnip_20220126-170250](https://user-images.githubusercontent.com/372476/151133703-049cd1fe-3ba8-42b8-877d-f9d7478cfd21.png) |

The extra v-flip is done in #55830.

One option is to make the ViewportPreview not v-flip if `Viewport.render_target_v_flip` is on.

I think ViewportPreview should always show what is actually rendered. As already documented, the `Viewport` renders the scene upside-down by default and it's recommended to enable v-flip in most cases.

### Steps to reproduce

Create a 3D scene inside `Viewport` or use the MRP.

### Minimal reproduction project

[ViewportPreview.zip](https://github.com/godotengine/godot/files/7940258/ViewportPreview.zip)

**Comment by akien-mga** [comment]
Yeah I agree with reverting #55830, this was incorrect.

**Comment by timothyqiu** [comment]
Fixed by #57613
