### ISSUE TITLE
Hint label in 2D editor appears at wrong position and pushes zoom controls

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#57253]
### Godot version

1894f3f

### System information

W10

### Issue description

![godot windows tools 64_IjMdMcNjru](https://user-images.githubusercontent.com/2223172/151182401-7bee0ad3-dacb-470d-9ab6-2b2c23d09788.gif)

In 3.x
![godot windows opt tools 64_mTBtxwMTvC](https://user-images.githubusercontent.com/2223172/151182611-b5a2d48b-c84b-4096-963f-0b92c7ac9ce1.gif)

### Steps to reproduce

1. Drag Texture to 2D editor

**Comment by emcguirk** [comment]
I'd like to take this on. Could you describe the problem in some more detail?

**Comment by KoBeWi** [comment]
In `canvas_item_editor_plugin.cpp` you can find `controls_vb` node. It stores the zoom widget and the label that appears when you drag a texture over viewport. The label is normally invisible, but when it appears, it shows above the zoom instead of below it. You can observe the behavior by dragging e.g. `icon.png` over 2D editor.

**Comment by akien-mga** [comment]
Fixed by #57296.
