### ISSUE TITLE
No visible text cursor/caret in input fields or script editor with Display Scale 75%

### ISSUE THREAD

**Issue by proehlen** [godotengine/godot#57251]
### Godot version

v4.0.alpha1.official [31a7ddbf8]

### System information

Ubuntu 20.04.3 LTS. GeForce 940 mx. 

### Issue description

There is no visible text caret/cursor in any input fields or the script editor so you can't see at what position you are editing.

### Steps to reproduce

1. Open Godot 4.0. 
2. Enter text in the Local Projects -> Filter projects field. No cursor / caret visible.
3. Create or open an existing project. 
4. Create or open an existing script
5. Enter text or click in any existing text. No cursor / caret visible.

**Comment by ccuntd** [comment]
the caret is visible, have you changed it in the ubuntu settings, that has some control over the caret

i dont use ubuntu, but yo can still try

**Comment by proehlen** [comment]
> the caret is visible, 

I'm not sure how you think you can see my screen but I beg to differ.

> have you changed it in the ubuntu settings,

No I haven't. It's visible in every other app that I use daily including the one I'm typing this in now.

Nevermind. I'll wait for beta.

**Comment by ccuntd** [comment]
for me it's always on, so maybe blinking is broken and it remains in whaterver it was in last

off always, on always on, you could keep this issue tho, it's still a problem

**Comment by proehlen** [comment]
> @proehlen Which screen resolution are you using, and which editor scale are you using in the Editor Settings? I wonder if this is due to 75% editor scale causing the caret width to round down to 0, making the caret invisible.

@Calinou My screen is 1920x1080 but I have the same problem on my smaller laptop screen.  Is the "editor scale" you are referring to the slider labelled "Custom Display Scale" in the screenshot below? When I reported the issue it was set to the default value of 1. Interestingly however I've changed it and restarted Godot and I can see any visible difference in the gui:

![image](https://user-images.githubusercontent.com/8384068/151361686-012fb3bf-c5ba-4539-91dd-0d3480595290.png)

**Comment by akien-mga** [comment]
"Custom Display Scale" is likely only used if you select "Custom" as the value for "Display Scale".

Your current value is "Auto (75%)", which is what Calinou supposed might be related to the issue. You can try to set it to 100% to see if that solves the issue.

**Comment by proehlen** [comment]
@akien-mga Thanks for explaining it.  I can confirm the caret returns / is visible if I choose either "Auto 100%" or a Custom Display Scale.

**Comment by proehlen** [comment]
Actually I just thought of something that might be relevant. Godot 4 insists on opening up on my laptop screen which is only 1366x768. I always opened Godot 3.x on my desktop 1080p screen because otherwise the ui was too small.  However, like I said, I can't open Godot 4 on my bigger screen. No matter how I launch it, it starts on the small screen.  Perhaps that's why I never noticed the issue prior to Godot 4?

**Comment by Calinou** [comment]
@proehlen [Godot does not support changing the display scale without restarting](https://github.com/godotengine/godot/issues/56341), so it is only set once on startup.

The display choosing logic has changed in Godot 4.0 as part of the DisplayServer refactoring. Also, [implementing support for remembering the window position and size across startups](https://github.com/godotengine/godot/pull/32056) is planned, but doing it correctly is not trivial.

**Comment by proehlen** [comment]
Ok, well my laptop is five years old and you've given me a workaround so I'm happy to use it and play on.  I'll let you decide if you think it's worth addressing for other users or otherwise you can close the issue.  An an aside, I appreciate all you guys have done with Godot. It's been a joy to use.
