### ISSUE TITLE
Godot 4.x uses minimum 20% CPU on Mac while debugging (Intel)

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#57256]
### Godot version

v4.0.alpha1.official [31a7ddbf8]

### System information

Mac OSX (Intel 2019)

### Issue description

**Vulkan Mobile renderer**

Adding `Low processor mode` does not seem to have an effect on CPU usage in the latest alpha release of 4.x

While playing with the settings and trying to understand if I could decrease CPU usage on my Mac I found that enabling this setting does not seem to have an effect.

My mac continues to use around 20% of the CPU for running the window.

### Steps to reproduce

1. Open a project with the Vulkan mobile renderer
2. Enable low CPU mode
3. Set the CPU delay to 40,000

**Comment by Calinou** [comment]
Try enabling **Show Update Spinner** in the editor settings and notice if the spinner in the top-right corner is moving continuously, even if you don't move the mouse.

**Comment by tavurth** [comment]
Hi @Calinou, thanks for your insight it appears you are correct.

I created a basic project and dropped the FPS & the Frames drawn on the screen, while increasing the `low_processor_usage_mode_sleep_usec` to 80,000 which gives the following result:

<img width="500" alt="Screenshot 2022-01-26 at 20 58 07" src="https://user-images.githubusercontent.com/100964/151219733-1a5b4a1c-622b-4842-879f-da381095589b.png">

So it seems like the issue is more that "Godot 4.x uses minimum 20% CPU on Mac (Intel)"

**Comment by tavurth** [comment]
# Godot 3.x

An example from Godot 3.x running the same scene (no sleep):

<img width="500" alt="Screenshot 2022-02-01 at 13 13 54" src="https://user-images.githubusercontent.com/100964/151950306-39c632cf-8c45-4e7c-8d58-2d9bfccd0aca.png">

An example using `low_cpu_mode` (sleep 40,000)

<img width="500" alt="Screenshot 2022-02-01 at 13 15 17" src="https://user-images.githubusercontent.com/100964/151950491-920e02e6-ef8a-4059-9df7-d4514a147f52.png">

# Godot 4.x

Without sleep

<img width="500" alt="Screenshot 2022-02-01 at 13 17 11" src="https://user-images.githubusercontent.com/100964/151950757-e9cf6cbe-e744-4999-ab82-61397c584f4e.png">

Sleep 40,000

<img width="500" alt="Screenshot 2022-02-01 at 13 17 50" src="https://user-images.githubusercontent.com/100964/151950843-d60a3204-9a62-4a92-aafd-fe7d103d2989.png">

# Example project

The project used for these timings can be found here:

https://github.com/tavurth/godot-cpu-test

**Comment by tavurth** [comment]
@Calinou I managed to update my OS and install XCode, here is the profiling information:

<img width="1440" alt="Screenshot 2022-02-01 at 20 44 48" src="https://user-images.githubusercontent.com/100964/152021936-e05fa240-f3cb-41d2-96ca-d9ceb18d846b.png">

Is it safe to share directly the `.trace` file here?

**Comment by tavurth** [comment]
@Calinou @Faless Oh yes I see that in the `_thread_func` the minimum delay is `100 microseconds` or `0.1 ms` between checks, which would explain the high CPU thrash.

Can I just create a PR to increase this to `100 milliseconds` instead?

**Comment by Calinou** [comment]
> Can I just create a PR to increase this to 100 milliseconds instead?

100 milliseconds is likely too high, I'd probably decrease it to 10 milliseconds instead.

**Comment by tavurth** [comment]
Ok thank you, I'll work on that and perform some tests

**Comment by tavurth** [comment]
Seems that cut the CPU usage in half at least.

<img width="500" alt="Screenshot 2022-02-01 at 22 17 17" src="https://user-images.githubusercontent.com/100964/152035785-2643c109-ca44-4d8f-bff7-5e3046385178.png">

And here's the profile report for that change:

<img width="500" alt="Screenshot 2022-02-01 at 22 20 23" src="https://user-images.githubusercontent.com/100964/152036252-a43d5c7d-130f-4f7d-bbd0-d7d90a505945.png">

**Comment by Faless** [comment]
Updated the title to reflect the issue is only relevant to instances that are actively being debugged.
Some performance loss is expected during debugging, and I think 10ms is too much since it's going to be less than once per frame on a 144hz monitor.

**Comment by tavurth** [comment]
@Faless Interestingly I did not have remote debugging enabled in this project. 

Perhaps we can disable this check entirely if the flag is not set in the editor settings.

I will try again with 4.1ms to fit the 144hz refresh rate.

**Comment by tavurth** [comment]
4.1ms seems good with only a 1% increase in CPU usage

<img width="500" alt="Screenshot 2022-02-01 at 22 35 09" src="https://user-images.githubusercontent.com/100964/152038444-5e4d8234-037f-499e-b77f-cdbde2a637c6.png">
