### ISSUE TITLE
Update thorvg to v0.7.1

### ISSUE THREAD

**Issue by fire** [godotengine/godot#57259]
### Godot version

https://github.com/godotengine/godot/commit/9df9dc77a396bcdfe362365e9511de80c1e94fc0

### System information

Windows 11, Nvidia 3000 series

### Issue description

Update thorvg to v0.7.1.

Replace url in thorvg (linux) upgrade script to "0.7.1"

Do a visual confirmation that nothing obvious in the editor startup broke.

## Reference

https://github.com/Samsung/thorvg/releases/tag/v0.7.1

https://github.com/godotengine/godot/blob/master/thirdparty/thorvg/update-thorvg.sh

### Steps to reproduce

Launch godot to check it is the older version.

### Minimal reproduction project

Not applicable.

**Comment by fire** [comment]
If anyone wants to learn how to do this, I can assist.

**Comment by AnilBK** [comment]
> If anyone wants to learn how to do this, I can assist.

Yes,Sure..Guide Me, I would love to learn that.

**Comment by fire** [comment]
Thanks. I appreciate it.
