### ISSUE TITLE
Godot 3.5: Navigation errors

### ISSUE THREAD

**Issue by AurelienCaille** [godotengine/godot#57254]
### Godot version

Godot_v3.5-beta1_win64

### System information

Windows 10 Famille version 21H1

### Issue description

addon used: zylann.hterrain

Adding navigation obstacle during runtime provoke some errors:

E 0:00:00.925   set_navigation_node: Condition "nav" is true.
  <Source C++>  scene/3d/navigation_obstacle.cpp:132 @ set_navigation_node()
  <Pile des appels>Player.gd:5 @ _ready()
                TestGame.gd:7 @ _ready()

E 0:00:01.242   sync: Attempted to merge a navigation mesh triangle edge with another already-merged edge. This happens when the Navigation's `cell_size` is different from the one used to generate the navigation mesh. This will cause navigation problem.
  <Source C++>  modules/navigation/nav_map.cpp:639 @ sync()

### Steps to reproduce

- open reproduction project with godot 3.5
- launch "game"

### Minimal reproduction project
[TestBugNav.zip](https://github.com/godotengine/godot/files/7942716/TestBugNav.zip)

**Comment by akien-mga** [comment]
The reproduction project didn't finishing uploading, could you re-upload it?

**Comment by Scony** [comment]
Merge errors are fixed with #56879 applied (after navmesh re-baking)
Remaining errors are fixed with #56600

**Comment by Scony** [comment]
@akien-mga @Calinou this one is fixed now, can be closed
