### ISSUE TITLE
Picking a screen color with ColorPicker lags in 4.0 alpha 1 (DisplayServer regression)

### ISSUE THREAD

**Issue by DJ-Dav** [godotengine/godot#57258]
### Godot version

4.0.alpha1

### System information

Windows 10, and probably others

### Issue description

When picking a color in the color picker tool, the whole engine lags, and window doesn't close

### Steps to reproduce

Add an exported variable or shader param of type Color to any node, and edit it in the inspector

**Comment by KoBeWi** [comment]
Can't reproduce. There is no FPS drop when picking color.
There is also #46334, so testing is unreliable.

**Comment by akien-mga** [comment]
I think there were other reports about this a while ago, but it was likely fixed since then indeed.
