### ISSUE TITLE
ThorVG: Broken SVG initial import, a reimport fixes it

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#57260]
### Godot version

4.0.dev (9df9dc77a396bcdfe362365e9511de80c1e94fc0)
3.4.2 is not affected.

### System information

Linux, Mageia 9 x86_64

### Issue description

I noticed that when adding SVG images to a project (or forcing a reimport from scratch by deleting the `.godot/` folder and their `.import` files), the images are broken:

![image](https://user-images.githubusercontent.com/4701338/151209182-12c09c1e-4c70-4b69-ad63-8aa79ea0e628.png)

These two should have been the Godot logo (two copies of the same logo with different names).

Note how they're also broken in the filesystem dock:
![image](https://user-images.githubusercontent.com/4701338/151209320-1df94b59-845a-4a04-8c12-34fd5cf5a7f8.png)

Hitting reimport for each SVG (possibly several times) seems to fix them (though not the thumbnails):

![image](https://user-images.githubusercontent.com/4701338/151209562-0bb9558d-9522-4583-9cf8-dcc678cea1d5.png)

This might be specific to this SVG (`icon.svg` from the Godot repo), I haven't tried others to confirm.

### Steps to reproduce

- Copy this repo's `icon.svg` to a new Godot 4 project
- Drag and drop on the 2D viewport to add it to a Sprite, or check it in the Inspector preview

### Minimal reproduction project

[SVGBrokenImport.zip](https://github.com/godotengine/godot/files/7943592/SVGBrokenImport.zip)

**Comment by jgillich** [comment]
Here is a SVG that works fine in 3.4, but doesn't work at all in v4 no matter how often I click reimport
![UIpack_vector](https://user-images.githubusercontent.com/347965/184178792-0e19243f-53f7-469a-b7ef-ab98c46007f6.svg)


```
 ImageLoaderSVG can't create image.
  modules/svg/image_loader_svg.cpp:142 - Condition "p_image->is_empty()" is true. Returning: FAILED
  core/io/image_loader.cpp:65 - Error loading image: res://assets/UIpack_vector.svg
  editor/editor_file_system.cpp:1919 - Error importing 'res://assets/UIpack_vector.svg'.
  Failed loading resource: res://assets/UIpack_vector.svg. Make sure resources have been imported by opening the project in the editor at least once.
```

**Comment by fire** [comment]
I can't reproduce this issue.
