### ISSUE TITLE
(4.0) Attaching a GDNative script to a node crashes Godot

### ISSUE THREAD

**Issue by BlueStaggo** [godotengine/godot#57267]
### Godot version

4.0 alpha 1

### System information

Windows 11

### Issue description

When I try to attach a GDNative script to a node, Godot crashes. There isn't anything in the logs, even with --verbose. I thought that Godot 4 would support GDNative (or GDExtension as it is called now, but it's still GDNative in the editor): it even said in the alpha 1 blog post that GDExtension was available. I expected at least the script to be created and opened in the editor.

### Steps to reproduce

1. Create a new node (or use the red icon.png in the reproduction project).
2. Open the "Attach Node Script" dialog.
3. Select GDNative.
4. Enter a class name.
5. Create the script.
6. Godot will crash.

### Minimal reproduction project

[nonative.zip](https://github.com/godotengine/godot/files/7944047/nonative.zip)

**Comment by Calinou** [comment]
GDNative will be removed in Godot 4.0. It hasn't been fully removed yet, but it will be done soon.

**Comment by BlueStaggo** [comment]
So in a later build, GDNative will be replaced with GDExtension and not crash?

**Comment by Calinou** [comment]
> So in a later build, GDNative will be replaced with GDExtension and not crash?

Yes, but GDNative add-ons will have to be converted to GDExtension to keep working.

**Comment by KoBeWi** [comment]
The GDNative option is not there anymore.
