### ISSUE TITLE
New TileMap editor: Tilemap creates kind of layereffect at the edge of the y-axis when painting a tile

### ISSUE THREAD

**Issue by OlafausBerlin** [godotengine/godot#57266]
### Godot version

4.0.alpha1.official

### System information

Windows 10 , Amd Ryzen5 3500u , Radeon Vega Mobile ,Vulkan Mobile

### Issue description

I have only one Layer in my Tileset but when i paint a Tile Godot draws a kind of layereffect.

https://user-images.githubusercontent.com/50340215/151217085-40ec0368-aec6-4015-9797-954c887354b2.mp4

.

### Steps to reproduce

Take one of the 3 Tiles and paint around of the y-axis edge.

### Minimal reproduction project

[Godot 4 Test.zip](https://github.com/godotengine/godot/files/7943943/Godot.4.Test.zip)

**Comment by gustavi** [comment]
I had the same issue (https://github.com/godotengine/godot/issues/54006) and it looks like it's not a bug but a feature.
