### ISSUE TITLE
Nested classes, preload and const

### ISSUE THREAD

**Issue by supaiku0** [godotengine/godot#5726]
I'm using a class to aggregate some preloads.

``` GDScript
# aggregate.gd
const A = preload("A.gd")
const B = preload("B.gd")
```

and access the classes through aggregate.A.new(), etc.

Now I have something like this:

``` GDScript
# aggregate.gd
const A = preload("A.gd")
const B = preload("B.gd")
const C = B.NestedSomething
const D = B.NestedSomething2
```

I can still access the classes through aggregate.C.new() etc, but the code editor complains with
`Invalid index 'C' in constant expression`

But it still seems to work and compile fine. Using var instead of const removes the editor error, but then it breaks runtime and I can't access the classes anymore.

Is this a bug, a feature or how am I supposed to interpret this behaviour?

(Hopefully, it's understandable I suck at markdown)

**Comment by vnen** [comment]
I fixed the code formatting. I don't really understand what's happening, but it seems that the parser is having some trouble identifying the constant expressions.

**Comment by supaiku-o** [comment]
@vnen Okay, so I can safely ignore the editor complaint for now.

**Comment by DualMatrix** [comment]
This won't compile anymore in the current master. With error `invalid index 'NestedSomething' in constant expression.` 

So I guess this isn't relevant anymore?

**Comment by akien-mga** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment]
I'll close this as nobody else has been able to reproduce this recently. Please comment (with the [issue template](https://github.com/godotengine/godot/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) filled) if you can still reproduce this.
