### ISSUE TITLE
Incorrect offset of property type in the in-editor documentation

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#57269]
### Godot version

9df9dc77a396bcdfe362365e9511de80c1e94fc0

### System information

Windows 10

### Issue description

![image](https://user-images.githubusercontent.com/3036176/151225902-e6c8be06-ffca-4a5b-8e13-decf10bc88e7.png)

### Steps to reproduce

- Open the documentation of `ConvexPolygonShape3D`.
- Change a `Main Font` editor property to something different.

**Comment by akien-mga** [comment]
Confirmed, that's also a regression from #56910 which was quickly mentioned in https://github.com/godotengine/godot/issues/57083#issuecomment-1019529858 but not fixed by #57090.

**Comment by pycbouh** [comment]
It's a regression, aye, but likely from https://github.com/godotengine/godot/pull/56921

**Comment by bruvzg** [comment]
It's most like is a regression from the #56921, also #56921 do not update `min_width` in the `_resize_line` and it's stay `0` if it was reset in the `_shape_line`, which "fixes" the issue as soon as it's resized (so I guess the logic is not working correctly).

**Comment by pycbouh** [comment]
Well, 0 just means shrink to its minimum, which is still true, even after the resize.
