### ISSUE TITLE
"Always show close button in scene tab" option is not saved between sessions

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#5727]
**Operating system or device - Godot version:**
Ubuntu 16.04, 4c4ab140b4569f2700517a13b20127eb7542b3ec

**Issue description** (what happened, and what was expected):
In 2.1 beta "Always show close button in scene tab" option is not saved between sessions.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by mefihl** [comment]
#6056

**Comment by kubecz3k** [comment]
Closing seems it looks like this is a duplicate of more wide issue: https://github.com/godotengine/godot/issues/6056
