### ISSUE TITLE
No binding for Transform3D.sphere_interpolate_with()

### ISSUE THREAD

**Issue by joemicmc** [godotengine/godot#57272]
### Godot version

4.0 alpha 1

### System information

Windows 10

### Issue description

Currently there is no binding for Transform3D.sphere_interpolate_with(). Recently the behaviour for Transform3D.interpolate_with() changed from being spherical linear to linear.

Related to this, perhaps the methods could be renamed to slerp() and lerp() to be consistent with rest of product and easier to understand? Currently I feel that Transform3D.interpolate_with() is ambiguous and doesn't describe what sort of interpolation is used. 

### Steps to reproduce

n/a

**Comment by Calinou** [comment]
> Related to this, perhaps the methods could be renamed to slerp() and lerp() to be consistent with rest of product and easier to understand? Currently I feel that Transform3D.interpolate_with() is ambiguous and doesn't describe what sort of interpolation is used.

Indeed, I raised this point a few weeks ago on the Godot Contributors Char. I think we decided to rename them to `slerp()` and `lerp()` respectively.

**Comment by joemicmc** [comment]
@Calinou unfortunately I have little to no C++ experience... 😅 I can def clone master, create a branch and give it a go though!
