### ISSUE TITLE
Backwards animations with Engine.time_scale set skip the final (first) keyframe

### ISSUE THREAD

**Issue by tcoxon** [godotengine/godot#57271]
### Godot version

3.4.2-stable

### System information

Ubuntu 16.04, GTX970 NVIDIA 384.130, with GLES3 backend

### Issue description

In my project I find that AnimationPlayers sometimes (semi-randomly) skip the final keyframe of an animation. I think that this happening when `Engine.time_scale` is set (which I use to speed up battle animations).

I've been able to create a reproducer for the cases where this happens for an animation that is playing backwards. Forwards animations also seem to be affected in my project, however I haven't been able to reproduce it in isolation.

### Steps to reproduce

1. Run the attached project.
2. The two 'play' buttons play the same animation on the same AnimationPlayer. Play it 'normally' first, and observe that the animated panel & texture end on blackness.
3. Click 'Play Fast' (which plays at 8x speed) and observe that when the animation has finished, the panel is red and the godot logo is visible in the TextureRect.

I expected both to end the same way regardless of the speed of playback.

### Minimal reproduction project

[time_scale_animation_player.zip](https://github.com/godotengine/godot/files/7944529/time_scale_animation_player.zip)

**Comment by Calinou** [comment]
I remember seeing an issue about this (also with forwards animations), but I can't find it right now.

**Comment by tcoxon** [comment]
We're seeing this occur relatively frequently on forwards-playing animations on lower-powered devices, even with `Engine.time_scale` set to `1.0`. It seems like it's related to long frame deltas somehow.

We have a lot of things in our project that wait on `animation_finished` signals that, with this bug, never come--resulting in the game getting stuck in an unplayable state.

**Comment by akien-mga** [comment]
I can confirm the bug in current `3.x` (4ecb9ccb9c88467ccadeb65dffa2dbb0ecf517a9).

I couldn't reproduce it in `master` after a quick and dirty port of the MRP, but that's not to say that it couldn't happen in a more complex one:
[time_scale_animation_player.zip](https://github.com/godotengine/godot/files/8399417/time_scale_animation_player.zip)

**Comment by tcoxon** [comment]
I managed to narrow the bug affecting the forwards-playing animations in my project down to #26887, which has already been fixed in 3.4 and master. My comments about that can be ignored.

For clarity's sake, the bug affecting backwards-playing animations in the reproducer has a different cause and continues to affect 3.4.

**Comment by tcoxon** [comment]
I've reproduced the reverse-animation bug on 4.1.1-stable. 
[Reproducer](https://github.com/godotengine/godot/files/12560142/reverse-anim-bug.zip)

The test scene contains an AnimationPlayer that autoplays an animation with some very closely-spaced keyframes. The animation plays forwards first, and when it finishes it is played backwards.

Expected behavior:
- ABCDDCBA is logged (via calls from the method track)
- After all animations are finished, the icon node is modulated with red.

Observed behavior:
- ABCDD is logged
- After all animations are finished, the icon node has default white modulation
