### ISSUE TITLE
Vulkan: Black screen on launch on macOS

### ISSUE THREAD

**Issue by mjcutshaw** [godotengine/godot#57285]
### Godot version

4.0 Alpha 1

### System information

OS X 10.14.6, Mac Mini, Intel UHD 630

### Issue description

I get a black box for the Godot project manager window with an additional black box that is labeled Please Confirm... I am not able to open projects or create new ones

![Screen Shot 2022-01-26 at 5 57 51 PM](https://user-images.githubusercontent.com/2942523/151263594-60fe0f52-0e5f-4b2d-952e-893e97708ba7.png)

### Steps to reproduce

I have downloaded it twice, today and yesterday. Same result.

I right-clicked a Godot 3,4 project to open with Godot 4 and it opened it. It opened to a black box.

![Screen Shot 2022-01-26 at 6 18 13 PM](https://user-images.githubusercontent.com/2942523/151263534-bd14403f-8ced-4dae-9430-87d6989da7f7.png)
 
Upon closing Godot it crashed.
https://pastebin.com/SJyAHgBK

I opened a Godot 4 project I made on my Linux computer and it resulted in the same black project window. Closing it also caused a crash

The app security setting is set to allow App Store and identified developers. Please let me know if there is anything I can test to help out.

**Comment by Rosthouse** [comment]
Sorry for cramming out this issue. I can reproduce the same error on a Lenovo Yoga 720, running Windows 10.

This laptop runs an Intel UHD 620. Could it be that the integrated GPUs are causing this issue?

**Comment by Calinou** [comment]
@mjcutshaw Can you (or anyone else) still reproduce this bug in [Godot 4.0.beta3](https://godotengine.org/article/dev-snapshot-godot-4-0-beta-3) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by SuperBPM** [comment]
Godot version
4.0 beta 5

System information
OS X 10.13.6 MacBook Pro (13 pouces, mi-2012)
(Intel HD Graphics 4000)

Issue description
Same black screen and blank dialog as above. But this time I don't have to run the command line : "Contents/MacOS/Godot --rendering-driver opengl3" to get there. I just launch the app and get the black screen and blank dialog.

**Comment by Calinou** [comment]
> Same black screen and blank dialog as above. But this time I don't have to run the command line : "Contents/MacOS/Godot --rendering-driver opengl3" to get there. I just launch the app and get the black screen and blank dialog.

This is expected, as OpenGL is used by default in the project manager since 4.0.beta5.

**Comment by clayjohn** [comment]
Can someone please test again on RC3. I think this was fixed as of Beta 9

**Comment by mjcutshaw** [comment]
On RC6, the project manager loads and looks correct. Once the project is opened Godot is black. 

I don't update the computer much unless something breaks with Avid Pro Tools. That software can be fickle. I'm going to close the issue since I don't use that computer anymore with Godot

**Comment by clayjohn** [comment]
For the record, the project manager likely works because it uses OpenGL instead of Vulkan. It sounds like the Vulkan-based renderers aren't working with your computer. It's likely an issue with the GPU drivers that an update would solve. Since you won't be updating or using that computer I'll go ahead and archive this issue

**Comment by FrostBird347** [comment]
I am also experiencing this bug and would like to point out that there is no way to update the gpu drivers drivers on mac without updating the entire operating system, which isn't a viable option for me.
I will also point out that the compatibility renderer does function correctly, likely because it uses opengl 3.
