### ISSUE TITLE
Setting too big icon for custom type can break the editor

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#57286]
### Godot version

3.5 beta1 and probably master

### System information

W10

### Issue description

![image](https://user-images.githubusercontent.com/2223172/151270016-41ea9c3f-1516-4ee8-b274-32f2802dca38.png)
None of the icons adjust texture's size, so using too big texture results in this abomination.

"Fixing" this is probably unfeasible, so at least `EditorPlugin.add_custom_type()` description should mention a standard size for an icon.

### Steps to reproduce

1. Have EditorPlugin with `add_custom_type()`
2. Use some very big texture for the icon

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/20197.

**Comment by fire** [comment]
Hope that this interacts with hidpi where the size might be 3x the normalized pixel size.

**Comment by KoBeWi** [comment]
Ok I just discovered that, just like https://github.com/godotengine/godot/issues/20197, it doesn't happen with `class_name`.
![image](https://user-images.githubusercontent.com/2223172/155903279-455b46f7-6061-4b59-b7fb-ef4fb8ab18e2.png)

**Comment by akien-mga** [comment]
Another example :)
![image](https://user-images.githubusercontent.com/4701338/190639857-5fff2341-26a9-44d4-9702-b6fe27112be5.png)

We "just" need to enforce a max size I believe.
