### ISSUE TITLE
"Save Scene As" causes "No loader found for resource"Error

### ISSUE THREAD

**Issue by amkk** [godotengine/godot#5728]
**Operating] system or device - Godot version:**
Windows7 64bit
tested on 2.1beta and latest head.
**Issue description** (what happened, and what was expected):
"Save Scene As" causes "No loader found for resource" Error in console.
**Steps to reproduce:**
This is only happen when Editor setting "Save path as relative" is checked.
You can use "3d_in_2d" demo project.
Open "3d_in_2d" demo project.
Then "main.scn" save as "main_mod.scn" using "Save Scene As"
Close saved scene.
Open the saved "res://main_mod.scn".
You will see the Error in console:No loader found for resource: res://./player_2d.scn::1
It seems strange path saved.
"res://./player_2d.scn::1" should be "res://player_2d.scn::1"
Note: tscn format works fine.

**Comment by reduz** [comment]
I'm considering the removal of save path as relative in the editor options, given the editor can now rename and move stuff and fix dependencies even if you don't save relative, anyone against this? :P

**Comment by punto-** [comment]
what about the asset sharing stuff? if you want to distribute a scene via
an asset store, it'll be more portable if the paths are relative..

**Comment by reduz** [comment]
asset sharing paths are still absolute
