### ISSUE TITLE
Vulkan: `SCREEN_TEXTURE` mipmaps only cover top left quarter of the screen

### ISSUE THREAD

**Issue by Ansraer** [godotengine/godot#57282]
### Godot version

4.0 official alpha 1 and 4.0 68580ecedda65ec3898a6cdc68193e32a2a1751a (26.1.2022)

### System information

Windows 10 Vulkan

### Issue description

When trying to use the screen_texture in a canvas shader all the mipmaps only cover the top left quarter of the screen. Everything works fine with level 0.
During the entire process, no errors were logged to the console.

<details>
<summary>IMAGE</summary>

![image](https://user-images.githubusercontent.com/6329420/151262922-9af9816c-bd4c-4c41-ab96-fb15d3031496.png)

</details>

### Steps to reproduce

Add the following shader to something that covers the entire screen:

````
shader_type canvas_item;
void fragment() {
	COLOR = textureLod(SCREEN_TEXTURE, SCREEN_UV, 4.0);
}
````

### Minimal reproduction project

see above ^

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/56511 (possible duplicate?).

**Comment by Ansraer** [comment]
I am not certain. I searched other issues before writing this report, but never managed to get the errors logged that are mentioned by other mipmap/screen_texture related issues. And for the top left quarter of the screen, everything works perfectly fine, no matter what else I do. 🤷 

Someone who knows more about how mipmaps are generated in godot than I will need to decide whether or not these issues are connected.

Btw, I can also confirm this issue with the latest master.
