### ISSUE TITLE
Godot 4 Alpha 1 does not read materials created in dev versions

### ISSUE THREAD

**Issue by macryc** [godotengine/godot#57299]
### Godot version

v4.0 alpha 1 official (31a7ddbf8)

### System information

Win10, RTX 2070 mobile

### Issue description

When opening a Godot 4 project in the new official alpha, all scenes that have materials created in earlier pre-alfa versions of Godot 4 show as 'invalid/corrupt'.

### Steps to reproduce

1. Open a pre-alfa dev version of godot 4
2. create a 3d scene, add a mesh and create a standard 3d material
3. apply a albedo texture to the material
4. save the project
5. open the project in Godot 4 official alpha1
6. try to open the tscn - it won't open (corrupt)

**Comment by akien-mga** [comment]
What pre alpha version exactly?

**Comment by macryc** [comment]
> What pre alpha version exactly?

I tried a few of the nightly builds. Eg. v4.0.dev.calinou.f09d88443

**Comment by fire** [comment]
If it’s possible can you provide a test project?

**Comment by akien-mga** [comment]
I can't reproduce the issue when following the above steps with 4.0.dev.20211210, and then opening the same project in 4.0 alpha 1. So indeed a reproduction project seems necessary.

**Comment by macryc** [comment]
BTW, I tried deleting the import folder in alpha1 (.godot) - all assets got reimported on load and the materials worked fine but my animation tree stopped working:(. I saw thousands of this error: E 0:00:05:0378   _process_graph: Condition "!track_cache.has(path)" is true. Continuing.
  <C++ Source>   scene/animation/animation_tree.cpp:911 @ _process_graph()

**Comment by akien-mga** [comment]
I can confirm the issue with the MRP. Reimporting the assets (.tga files) solves it.

The errors are:
```
ERROR: Image format out of range, please see Image's Format enum.
   at: create (core/io/image.cpp:1972)
ERROR: Failed loading resource: res://.godot/imported/RoadBlockade_01_NM.tga-e105eea7cb5e05d743785e5b30425094.s3tc.stex. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:205)
ERROR: Failed loading resource: res://Barrier/RoadBlockade_01_NM.tga. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:205)
```

That's probably because PVRTC format was removed, so the `Image.Format` enum changed, and the values encoded in the imported assets are now invalid.

This was an intentional changes breaking compatibility in 4.0, so this is not a bug per se but a natural consequence of that change. Anyone affected just needs to reimport textures.
