### ISSUE TITLE
Cant zoom in after zooming out to 0% in tileset editor

### ISSUE THREAD

**Issue by Ev01** [godotengine/godot#57292]
### Godot version

Godot 4 alpha 1

### System information

Windows 10

### Issue description

In the tileset editor after zooming out all the way to 0%, zooming in does nothing
The only way to get it back is to reset the zoom.

### Steps to reproduce

1. Add TileMap node
2. Add a tileset to it
3. Zoom out of the tileset until it stops zooming (using mousewheel or - icon)
4. Try to zoom in using the mousewheel or the + icon.

The reproduction project below has a TileMap with the tileset I'm using.

### Minimal reproduction project

[4.0 alpha 1 tileset bug.zip](https://github.com/godotengine/godot/files/7946929/4.0.alpha.1.tileset.bug.zip)

**Comment by Ev01** [comment]
I found that the bug was in `EditorZoomWidget::set_zoom_by_increments(int p_increment_count, bool p_integer_only)` in this check that comes before the zooming code:
```
if (zoom < CMP_EPSILON || p_increment_count == 0) {
	return;
}
```
Changing the line to this fixes it:
```
// Allow the zoom increment to be positive so zooming in is allowed
if (zoom < CMP_EPSILON && p_increment_count <= 0) {
	return;
}
```
Im not sure if this is a good fix or not since Im a newbie and I'm not sure what this check is for. Should I open a new pull request which makes this change?

**Comment by KoBeWi** [comment]
EditorZoomWidget is also used by the 2D editor, but this bug doesn't occur in there. A better fix could be clamping the zoom, so zooming to 0% (which doesn't make sense anyways) is not possible.

**Comment by Ev01** [comment]
Okay, I created a pull request that sets a minimum of 1% zoom. Not exactly sure what dividing zoom by `MAX(1, EDSCALE)` does but its what the zoom_widget does to get the percentage.

A possible issue is if `EDSCALE` were to be higher than 1000 then it would still let you zoom out to 0.00001 zoom, which is the point where it stops letting you zoom.

How do I link the pull request to this issue?

**Comment by KoBeWi** [comment]
> How do I link the pull request to this issue?

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
If you fail to link it, you can edit your message or link manually with the button under milestone.
