### ISSUE TITLE
Game won't play (shows black screen) in Godot 4 alpha 1 when environment node is used

### ISSUE THREAD

**Issue by macryc** [godotengine/godot#57300]
### Godot version

alpha1 official (31a7ddbf8)

### System information

Win10, RTX 2070 mobile

### Issue description

When using the environment node, the 3d project won't play, goes to black screen. Note, this issue was present in earlier pre-alpha dev versions of Godot 4 too, but usually the issue would manifest itself once and on the second trial the game would play normally. In alpha1, the issue is consistent. I've tried playing the game 10 times in a row, it black screened each time. 

### Steps to reproduce

1. start a project, create a 3d scene
2. add some objects
3. add the environment node
4. activate: sdfgi, ssao, volumetric fog, tweak the settings
5. run the scene

**Comment by Calinou** [comment]
@macryc Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by clayjohn** [comment]
No response, so closing
