### ISSUE TITLE
Vulkan: Random background color at each frame in 3D editor on macOS (Intel GPUs only)

### ISSUE THREAD

**Issue by Nebulean** [godotengine/godot#57303]
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

4.0 alpha 1 official

### System information

MacOS 10.15.7, CPU: 2.7GHz dual core i5, GPU: Intel Iris Graphics 6100 1536 MB, Vulkan rendering backend

### Issue description

When I rotate my view in the 3d editor, the background color changes at every frame. The following video shows that.
**(epilepsy warning)**

https://user-images.githubusercontent.com/9269185/151323538-4b88f5a1-65da-4689-828c-7b6fb495b9ae.mov

Additional note: color always starts with white, and when I use another editor and then come back to the 3d editor, the color restarts to white as well.

### Steps to reproduce

Just create a new project and go into the 3d editor

**Comment by alexruetz** [comment]
Does not seem to happen on Macs with M1 Chip.
Tried it with both Vulkan Backends.

**Comment by Calinou** [comment]
@Nebulean Can you reproduce this after switching the rendering backend to **Vulkan Mobile** in the Project Settings?

**Comment by Nebulean** [comment]
I switched to "Forward Mobile" in the project settings, if that's what you meant.
<img width="694" alt="image" src="https://user-images.githubusercontent.com/9269185/152407534-698b0b02-fd50-4ac5-85ed-c25a2e01430a.png">

The results are fairly similar, the only noticable difference being the fact that the grid in the x-z plane changes color as well.
**(EPILEPSY WARNING)**

https://user-images.githubusercontent.com/9269185/152408475-6690b64f-595c-4368-a894-e35db79d3ea2.mov

**Comment by snougo** [comment]
same issue on MacbookPro with intel GPU

**Comment by STUDIOEMBYR** [comment]
Confirmed on 4.0 beta 2
MacBook Air 13, Early 2015
Intel HD 6000
macOS Monterey 12.2.1

It seems to be related to the skybox shader as setting the background mode to solid color solves the flickering issue but setting it to black actually shows a red background, brighter colors slowly get more correct.

**Comment by snougo** [comment]
so I guess I figured out what caused this issue, it seem the DirectionalLight3D, at least it looks like that

https://user-images.githubusercontent.com/64188282/162567259-37998a27-c298-4cee-b161-636004e41398.mov

**Comment by mwillsey** [comment]
I can reproduce this on alpha7, Late 2015 Macbook Pro, Intel Iris Graphics 6100. 

Same fix; toggling preview sunlight fixes it.

**Comment by snougo** [comment]
this issue has been fixed

**Comment by clayjohn** [comment]
I can't reproduce this issue either on an early 2015 intel macbook Intel Iris Graphics 6100. So I will close as fixed. 

If anyone can still reproduce this issue, please let me know
