### ISSUE TITLE
[4.0 a1] Input map keys wiped when upgrading from Godot 3

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot#57311]
### Godot version

4.0 alpha 1

### System information

Linux Manjaro, Vulkan, Intel Kaby Lake

### Issue description

Title.
They're set to "Physical" with no key associated.

### Steps to reproduce

Import a project from Godot 3, I guess? (Running it once may or may not be required)

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
I can confirm this on `master` fc09d783f.

**Comment by Zireael07** [comment]
Same thing applies to Shortcut property of the Button (as in, a Control type, not in a physical button on the keyboard :P )

The bigger the project, the more annoying this is going to be.

**Comment by EricEzaM** [comment]
Yeah, `InputEventKey` changed slightly in 4.0, as did `Shortcut`.

Should this really be handled by some engine code or should some modification be made to one of those project converters floating around?

**Comment by Zireael07** [comment]
I'd go for modifying one of the project converters, AND shipping said converter with the next alpha.

**Comment by KoBeWi** [comment]
> For InputEventKey, it should just be setting the store_command property to true, plus possibly some other minor changes. For Shortcut, it will just be putting the existing event from 3.X into an array of events for 4.0, as shortcuts can now have more than one event assigned.

Also it needs to change `scancode` to `keycode`.

I wouldn't bother with this though. As already said, this should be handled by converters.
