### ISSUE TITLE
Vulkan: Errors printed when closing scene/changing tab

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot#57314]
### Godot version

4.0 alpha 1

### System information

Linux Manjaro, Vulkan, Intel Kaby Lake

### Issue description

When changing scenes/closing them, I get a slew of errors in the output tab, to the tune of:

```
 drivers/vulkan/rendering_device_vulkan.cpp:8401 - Attempted to free invalid ID: 2148952526815314
  drivers/vulkan/rendering_device_vulkan.cpp:8401 - Attempted to free invalid ID: 2149257469493487
servers/rendering/renderer_rd/renderer_storage_rd.cpp:1680 - Condition "!material" is true. Returning: true
  servers/rendering/renderer_rd/renderer_storage_rd.cpp:1667 - Condition "!material" is true. Returning: false
  servers/rendering/renderer_rd/renderer_storage_rd.cpp:1693 - Condition "!material" is true.
  servers/rendering/renderer_rd/renderer_storage_rd.cpp:1705 - Condition "!material" is true.
```

Amount of errors, IDs and line numbers seem to be random.

### Steps to reproduce

Just close a tab/change scene in editor

### Minimal reproduction project

https://github.com/Zireael07/FreeRoamRoguelikeRacerPrototype/tree/4.x

**Comment by clayjohn** [comment]
The ``!material`` errors were fixed by https://github.com/godotengine/godot/pull/57222 already. But I am not sure about the ``Attempted to free invalid ID``. It would be worth testing in Master.
