### ISSUE TITLE
canvas_item shader color uniform values are linear in Godot 4

### ISSUE THREAD

**Issue by ZuBsPaCe** [godotengine/godot#57325]
### Godot version

v4.0.alpha.custom_build [46053a1be]

### System information

Windows 10, Vulkan Mobile, NVIDIA TI 1200

### Issue description

A color uniform passed to a canvas_item shader has unexpected values.

Good: If I specify Black (0, 0, 0, 255), the result is (0, 0, 0, 1).
Good: If I specify White (255, 255, 255, 255), the result is (1, 1, 1, 1).
Bad: If I specify Gray (128, 128, 128, 255), the result is (0.21585, 0.21585, 0.21585, 1), but I would expect (0.5, 0.5, 0.5, 1).

The result is the same, if I set the uniform through the inspector or through set_shader_param.

Here's a screenshot, where I set the grey color and display it on a sprite:
![image](https://user-images.githubusercontent.com/4233942/151447013-7aad824c-eaf2-49db-9794-99611bd34319.png)

The same shader in Godot 3.4 has correct values:
![image](https://user-images.githubusercontent.com/4233942/151447162-58653011-9c4d-4c9b-8ffc-f69d344af6b2.png)

### Steps to reproduce

Add a canvas_item shader like this to a Sprite or ColorRect compare the set color value to the final result:

```gdscript
shader_type canvas_item;

uniform vec4 color : hint_color;

void fragment() {
	COLOR = color;
}
```

### Minimal reproduction project

[godot4-shader-uniform-color.zip](https://github.com/godotengine/godot/files/7953947/godot4-shader-uniform-color.zip)

**Comment by Calinou** [comment]
You need to add `hint_albedo` to use sRGB colors instead of linear. What's strange though is that this shouldn't be needed in 2D, only 3D.

**Comment by clayjohn** [comment]
> You need to add hint_albedo to use sRGB colors instead of linear.

``hint_albedo`` is only for textures. 

I think @Lyuma has a proposal about this. There seems to be a demand for a ``linear_color`` hint that exposes a color picker but keeps the color in linear space. Godot right now assumes that if you want to specify a color, you also want srgb.

**Comment by ZuBsPaCe** [comment]
@clajohn Thanks for your input.

I've looked into it a bit and the source of the problem definitely has to do with following code in renderer_storage_rd.cpp:

```c++
				if (value.get_type() == Variant::COLOR) {
					Color v = value;

					if (p_linear_color) {
						v = v.to_linear();
					}

					gui[0] = v.r;
					gui[1] = v.g;
					gui[2] = v.b;
					gui[3] = v.a;
				} else if (value.get_type() == Variant::RECT2) {

```

If I remove the line `v = v.to_linear();`, my issue disappears and the color in the inspector matches the output of the canvas_item shader.

@lyuma talks about this section of code and about making a proposal about `hint_color_hdr` or something similar. But I could not find a proposal, maybe it's still in the works. Here's his comment: https://github.com/godotengine/godot/issues/54628#issuecomment-971140518

Right now I think that the current behavior in 2D with canvas_item shaders is completely unexpected and a breaking change compared to version 3.4. I want to specify a color in the inspector and use or compare this exact color in the shader without any conversion. But I think I don't know enough about this topic and maybe I'm missing the reason why this change was introduced in the first place? Or should this only apply to 3D?

**Comment by ZuBsPaCe** [comment]
I read about this more and fixed the issue title (just correct me if I'm wrong). I found a great [reddit post](https://www.reddit.com/r/godot/comments/pr9sto/comment/hdnq3h6/?utm_source=reddit&utm_medium=web2x&context=3) about linear/non-linear in Godot.

I think the issue is, that I want my canvas_item shader color uniform values to be non-linear. But due to some changes, they are now linear. Here's a quote from the thread above:

> sRGB is specific to the GLES3 backend to support High Dynamic Range (HDR) rendering in 3D: https://docs.godotengine.org/en/latest/tutorials/rendering/gles2_gles3_differences.html#color-space - canvas item shaders are for 2D which is not HDR by default unless you configure it in the world environment. If you switch to GLES2 the results for spatial shaders might be more what you're expecting but you will be giving up some of the advanced features.

So, is 2D HDR now? I don't think so and I could not find a way in the WorldEnvironment to change that if I switch the mode to "Canvas". So the current behavior only makes sense for spatial shaders, right?

I actually want to do something like this, but can't figure out how to convert the color uniform values to something sensible for the comparison to work:

```shader
shader_type canvas_item;

uniform vec4 color : hint_color;

void fragment() {
	vec4 tex_col = texture(TEXTURE, UV);
	
	if (tex_col.rgb == color.rgb) {
		// Do this
	} else {
		// Do that
	}
}

```

**Comment by Calinou** [comment]
> So, is 2D HDR now?

2D is HDR in both `3.x` (only when using GLES3) and `master`.

**Comment by ZuBsPaCe** [comment]
> 2D rendering is HDR in both 3.x (only when using GLES3) and master. It's how glow can work with overbright colors, even in 2D rendering.

Thanks for your information. That is awesome actually!

Just in case someone else has the same problem like in my last message, which is comparing texture colors to uniform colors, this is my Godot 4 workaround:

```
shader_type canvas_item;

uniform vec4 color_linear : hint_color;

vec4 to_srgb(vec4 col)  {
	return vec4(
		col.r < 0.0031308 ? 12.92 * col.r : (1.0 + 0.055) * pow(col.r, 1.0f / 2.4f) - 0.055,
		col.g < 0.0031308 ? 12.92 * col.g : (1.0 + 0.055) * pow(col.g, 1.0f / 2.4f) - 0.055,
		col.b < 0.0031308 ? 12.92 * col.b : (1.0 + 0.055) * pow(col.b, 1.0f / 2.4f) - 0.055, 
		col.a);
}

bool is_srgb_equal(vec4 col1, vec4 col2) {
	const float diff = 1.0 / 256.0 * 0.5;
	
	return abs(col1.r - col2.r) <= diff && abs(col1.g - col2.g) <= diff && abs(col1.b - col2.b) <= diff && col1.a == col2.a;
}

void fragment() {
	vec4 tex_col = texture(TEXTURE, UV);

	vec4 color_srgb = to_srgb(color_linear);
	
	if (is_srgb_equal(tex_col, color_srgb)) {
		// Do this
	} else {
		// Do that
	}
}
```

to_srgb can be found in core/math/color.h and fortunately works in the shader with nearly no changes. It's ugly, but works. A new color-hint which does that conversion would be nice though.

**Comment by clayjohn** [comment]
Fixed in master by https://github.com/godotengine/godot/pull/66683
