### ISSUE TITLE
Add warning for Windows export when rcedit is not configured but application details are filled in

### ISSUE THREAD

**Issue by EzraT** [godotengine/godot#57320]
### Godot version

v3.5.beta1.official [b9b23d222]

### System information

Only concerns supported versions of Windows

### Issue description

It would be nice if the editor showed a warning about needing rcedit when changing values in the Windows Application export options.

![image](https://user-images.githubusercontent.com/781121/151419783-d4108427-0172-44f6-9f92-8040e375f712.png)

<s>I could be wrong, but Godot does not seem to actually do anything with the options displayed in the screenshot above, instead it just uses the information for Godot Engine itself, is this intended?

If not, this should probably be corrected so that it actually uses the information in the export settings.

It also does not seem to use the custom .ICO file option, the exported executable always has the default Godot icon it seems, even when its given a different .ICO file.
![image](https://user-images.githubusercontent.com/781121/151421295-9bf0c671-f2be-4ed2-963a-4b4328fd4b02.png)
(Using a png file as the icon does not make a difference either)</s>

### Steps to reproduce

This should be self-explanatory, just export whatever project you wish with custom info entered in the application export options. (as shown)

### Minimal reproduction project

Not applicable.

**Comment by Calinou** [comment]
The options will only be taken into account if *all* values are valid. Your file version and product version are invalid, as they *must* use the `x.y.z.w` format (the 4 components are all required).

**Comment by EzraT** [comment]
![image](https://user-images.githubusercontent.com/781121/151430111-3cd0cc7f-02bf-4a42-8115-723f2722bd30.png)
Godot shows this as the default value for the version numbers, this is a bit misleading.
Perhaps it would be a good idea to change the defaults to 1.0.0.0 to avoid confusion.

**Comment by Calinou** [comment]
> Are there any specific requirements for the .ICO file?
> Mine is 32x32 and exported with GIMP.

Yes, see [Changing application icon for Windows](https://docs.godotengine.org/en/stable/tutorials/export/changing_application_icon_for_windows.html) in the documentation. I think the export will fail if the icon is invalid.

**Comment by akien-mga** [comment]
It's not clear to me whether you actually configured rcedit in the Editor Settings? All these fields are going to be ignored if rcedit isn't configured (if that's not the case already, it should show a warning when these fields are non-default but rcedit is not configured).

**Comment by EzraT** [comment]
I was not aware Godot needed a separate program to do this, I probably should have searched in the docs beforehand, sorry about that.
It does indeed work after configuring Godot to use rcedit, a warning about rcedit missing would indeed be nice to avoid confusion.

**Comment by ShrikantMalagi** [comment]
Hey @akien-mga, Can I take up this task? I am new to open source and this would be my first issue. Any guidance is deeply appreciated.

**Comment by akien-mga** [comment]
@ShrikantMalagi There is already a Pull Request that addresses this issue linked above: #57350.
If you started looking into the problem, you're welcome to help review that PR to make sure that it's a correct fix :)
