### ISSUE TITLE
Project manager window initial position not centered on hiDPI displays

### ISSUE THREAD

**Issue by twoco** [godotengine/godot#57324]
### Godot version

v4.0.alpha1.official [31a7ddbf8]
v3.4.2.stable.official [45eaa2daf]

### System information

Windows 10

### Issue description

See #13017 It's an issue we've had several times before.
I thought it was finally fixed in Godot 4. But I think is slightly another reason. The initial window is centered. But it sizes increases after loading. And btw. the first loading window is just white which is a bad UX. But it seems that this is the same window until the project manager is loaded. In this case the initial centered position does not matter anymore, since the window size changes after loading completed. See recorded screen (gif).

![demo](https://user-images.githubusercontent.com/53160891/151446097-fd92963a-7958-49c8-a786-6965e05652a2.gif)

It just feels cheap and annoying when the window behaves like that.

### Steps to reproduce

Start Godot. See the initial small window is centered. But the final window state (bigger size) is not centeres.

My screen resolution is: 3840 x 2160 with 200% scale.

This is what I want (window position center):
![expected](https://user-images.githubusercontent.com/53160891/151447111-8b29cb7f-4504-4e00-b023-646f29eb8aa8.jpg)

Update: Same with Godot 3 I see now. I think it's because the window expanse on loaded.

**Comment by Calinou** [comment]
This is due to the same cause as https://github.com/godotengine/godot/issues/13017. I remember it working correctly at some point, but maybe it never did.

**Comment by twoco** [comment]
The white color of the initial window is not problem. Just the first start(s) was very slow. Looked like window without response. May be solved by first load the window (less as possible) and set a splash and then load the other stuff. But anyway...

The initial position seems to work correctly. The only problem is that the window width and height are changed after loading. Without knowing the code I would guess that either the window position should be centered again or the initial window size should have the same size as the final size. Just some thoughts. But I think you know more about it. :) 

![frame](https://user-images.githubusercontent.com/53160891/151458417-8fa17a1a-dbbd-4b43-b05e-01511bc87d1f.jpg)

**Comment by Calinou** [comment]
> The white color of the initial window is not problem. Just the first start(s) was very slow. Looked like window without response. May be solved by first load the window (less as possible) and set a splash and then load the other stuff.

This is being tracked in https://github.com/godotengine/godot-proposals/issues/3657.

**Comment by twoco** [comment]
Ok, I think my guess wasn't quite right. Don't let that confuse you. The final window (red) size is 2x greater that the initial state (green). So I think it's just because the initial state is just not yet scaled to the OS UI scale, right? So back again, it seems to be the initial cause of that problem. I hope we'll find a solution of this. How does other programs handle that? A workaround could be to start the window maximized. 

![2x](https://user-images.githubusercontent.com/53160891/151459328-1fc8ea13-fe80-4978-bcdf-5bde17aae07e.jpg)

**Comment by Calinou** [comment]
> Ok, I think my guess wasn't quite right. Don't let that confuse you. The final window (red) size is 2x greater then the initial state (green). So I think it's just because the initial state is just not yet scaled to the OS UI scale, right? So back again, it seems to be the initial cause of that problem. I hope we'll find a solution of this. How does other programs handle that?

Other programs handle this by creating the window at the scaled size automatically, rather than scaling the window via window management functions after it is created.

For the record, this scaling behavior was implemented in https://github.com/godotengine/godot/pull/20831.

> A workaround could be to start the window maximized.

That would work too, but I feel it would be too large when you have 1080p of screen real estate available (if not more).

**Comment by TechnicalSoup** [comment]
Having taken a brief look at the code i think the window is rezised based on the editor scale setting (with a minimum value of 1). However after the resize the window is not repositioned to the center of the screen. The code to do that is fairly straight forward, and I've got it working in some sandbox testing I'm doing.

I'm happy to put together a PR that will solve the window not being centered, but looking toward a long term solution if we attempt to read the display scaling from the operating system/platform we may hit a hurdle on Windows, as the current compilation parameters look target a minimum build OS of Windows 7 and this may be too low to use some of the more advanced DPI scaling APIs.

**Comment by Calinou** [comment]
@TechnicalSoup Feel free to open a pull request for this :slightly_smiling_face: 

> I'm happy to put together a PR that will solve the window not being centered, but looking toward a long term solution if we attempt to read the display scaling from the operating system/platform we may hit a hurdle on Windows, as the current compilation parameters look target a minimum build OS of Windows 7 and this may be too low to use some of the more advanced DPI scaling APIs.

Can't we use those APIs conditionally at run-time, similar to enabling ANSI escape codes on Windows 10 (for instance)?
