### ISSUE TITLE
Extending the list of recognized locales

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#5733]
I had to push f07d4f5 to fix errors we were getting since I merged in new WIP translations from Weblate for Bengali and Urdu. Doing this I noticed that we only have a limited set of recognized locales.

I'd like to know what was the motivation for using this set of languages identifiers and not more of them; was it done manually by just adding the most "relevant" languages, or does it come from a specific source?

---

For the reference, here are the glibc locales packaged on my system:

```
aa_DJ
aa_ER
aa_ER@saaho
aa_ET
af_ZA
ak_GH
am_ET
an_ES
anp_IN
ar_AE
ar_BH
ar_DZ
ar_EG
ar_IN
ar_IQ
ar_JO
ar_KW
ar_LB
ar_LY
ar_MA
ar_OM
ar_QA
ar_SA
ar_SD
ar_SS
ar_SY
ar_TN
ar_YE
as_IN
ast_ES
ayc_PE
az_AZ
be_BY
be_BY@latin
bem_ZM
ber_DZ
ber_MA
bg_BG
bhb_IN
bho_IN
bn_BD
bn_IN
bo_CN
bo_IN
br_FR
br_FR@euro
brx_IN
bs_BA
byn_ER
ca_AD
ca_ES
ca_ES@euro
ca_FR
ca_IT
ce_RU
cmn_TW
crh_UA
csb_PL
cs_CZ
cv_RU
cy_GB
da_DK
de_AT
de_AT@euro
de_BE
de_BE@euro
de_CH
de_DE
de_DE@euro
de_LU
de_LU@euro
doi_IN
dv_MV
dz_BT
el_CY
el_GR
en_AG
en_AU
en_BE
en_BE@euro
en_BW
en_CA
en_DK
en_GB
en_HK
en_IE
en_IE@euro
en_IN
en_NG
en_NZ
en_PH
en_SG
en_US
en_ZA
en_ZM
en_ZW
eo_XX
eo_XX.ISO-8859-3
es_AR
es_BO
es_CL
es_CO
es_CR
es_CU
es_DO
es_EC
es_ES
es_ES@euro
es_GT
es_HN
es_MX
es_NI
es_PA
es_PE
es_PR
es_PY
es_SV
es@tradicional
es_US
es_UY
es_VE
et_EE
et_EE.ISO-8859-15
eu_ES
eu_ES@euro
fa_IR
ff_SN
fi_FI
fi_FI@euro
fil_PH
fo_FO
fr_BE
fr_BE@euro
fr_CA
fr_CH
fr_FR
fr_FR@euro
fr_LU
fr_LU@euro
fur_IT
fy_DE
fy_NL
ga_IE
ga_IE@euro
gd_GB
gez_ER
gez_ER@abegede
gez_ET
gez_ET@abegede
gl_ES
gl_ES@euro
gu_IN
gv_GB
hak_TW
ha_NG
he_IL
hi_IN
hne_IN
hr_HR
hsb_DE
ht_HT
hu_HU
hy_AM
hy_AM.ARMSCII-8
ia_FR
id_ID
ig_NG
ik_CA
is_IS
it_CH
it_IT
it_IT@euro
iu_CA
iw_IL
ja_JP
ja_JP.EUC-JP
ka_GE
kk_KZ
kl_GL
km_KH
kn_IN
kok_IN
ko_KR
ko_KR.EUC-KR
ks_IN
ks_IN@devanagari
ku_TR
kw_GB
ky_KG
lb_LU
lg_UG
li_BE
lij_IT
li_NL
lo_LA
lt_LT
lv_LV
lzh_TW
mag_IN
mai_IN
mg_MG
mhr_RU
mi_NZ
mk_MK
ml_IN
mni_IN
mn_MN
mr_IN
ms_MY
mt_MT
my_MM
nan_TW
nan_TW@latin
nb_NO
nds_DE
nds_DE@traditional
nds_DE@traditional.ISO-8859-1
nds_NL
ne_NP
nhn_MX
niu_NU
niu_NZ
nl_AW
nl_BE
nl_BE@euro
nl_NL
nl_NL@euro
nn_NO
nr_ZA
nso_ZA
oc_FR
om_ET
om_KE
or_IN
os_RU
pa_IN
pap_AN
pap_AW
pap_CW
pa_PK
pl_PL
ps_AF
pt_BR
pt_PT
pt_PT@euro
quz_PE
raj_IN
ro_RO
ru_RU
ru_RU.KOI8-R
ru_UA
rw_RW
sa_IN
sat_IN
sc_IT
sd_IN
sd_IN@devanagari
se_NO
shs_CA
sid_ET
si_LK
sk_SK
sl_SI
so_DJ
so_ET
so_KE
so_SO
sq_AL
sq_MK
sr_ME
sr_RS
sr_RS@latin
ss_ZA
st_ZA
sv_FI
sv_FI@euro
sv_SE
sw_KE
sw_TZ
sw_XX
szl_PL
ta_IN
ta_LK
tcy_IN
te_IN
tg_TJ
the_NP
th_TH
ti_ER
ti_ET
tig_ER
tk_TM
tl_PH
tn_ZA
tr_CY
tr_TR
ts_ZA
tt_RU
tt_RU@iqtelif
ug_CN
uk_UA
unm_US
ur_IN
ur_PK
uz_UZ
uz_UZ@cyrillic
ve_ZA
vi_VN
wa_BE
wa_BE@euro
wae_CH
wal_ET
wo_SN
xh_ZA
yi_US
yo_NG
yue_HK
zh_CN
zh_CN.GB18030
zh_CN.GBK
zh_HK
zh_SG
zh_SG.GBK
zh_TW
zh_TW.EUC-TW
zu_ZA
```

**Comment by davidlamhauge** [comment]
I totally agree.
I am living in Denmark, but was born on the Faroe Islands. Greenland and the Faroe Islands are part of Denmark, and I want to be able to translate my games to these languages.

Both countries are on the above list:
Faroe Islands = fo_FO
Greenland = kl_GL

I hope someone can implement it. I would do it if I knew how...

**Comment by akien-mga** [comment]
Alright, I'm about to make a PR to add all the glibc locales mentioned above. To get the proper formatting, I'm using a quick and dirty regex:
- Retrieved tab-separated table from http://lh.2xlibre.net/locales/ into a `locales.txt` file
- `cat locales.txt | sed -e 's/\(.*\)\t— \([A-Z][a-z.*]*\) —\t\([A-Z]\)\([A-Z]*\)\t.*/"\1", \/\/  \2 \(\3\L\4\)/' > locales2.txt`
- `cat locales2.txt | sed -e 's/\(.*\)\t— \([A-Z][a-z]*.*\) —\t\([A-Z]\)\([A-Z]*\) \([A-Z]\)\([A-Z]*\)\t.*/"\1", \/\/  \2 \(\3\L\4\E \5\L\6\)/'` (for countries with two words)
- Fixed the few remaining occurrences manually because my regex fu started showing its limits
