### ISSUE TITLE
Godot 4-Alpha 1 - Tween - Can't create an tween outside of the use scope

### ISSUE THREAD

**Issue by AttackButton** [godotengine/godot#57333]
### Godot version

4.0-alpha 1

### System information

Windows 8 and 10

### Issue description

I need the possibility to stop the tween outside of the scope of the function that it will be used if this `tween` is already running. I tried to create it globally and set it in `_ready()`, the object gets created, but the tween doesn't work.

### Steps to reproduce

Create a global variable and set a tween on it, try to use this variable tween inside of a function.

### Minimal reproduction project
On the MRP just press `ui_down` once and see that the tween callbacks are not called.

[tween_scope_issue.zip](https://github.com/godotengine/godot/files/7955741/tween_scope_issue.zip)

**Comment by KoBeWi** [comment]
You are supposed to create a new Tween each time you animate something. There's no point in creating a Tween and then running it later. Also in your code you will add more Tweeners each time your `_on_timer_timeout()`, so the sequence will become longer.

There is one bug here however. You should be able to call `stop()` at the beginning and then `play()` after you add Tweeners somewhere else, but it doesn't work right now.

**Comment by AttackButton** [comment]
> You are supposed to create a new Tween each time you animate something. There's no point in creating a Tween and then running it later. Also in your code you will add more Tweeners each time your `_on_timer_timeout()`, so the sequence will become longer.
> 
> There is one bug here however. You should be able to call `stop()` at the beginning and then `play()` after you add Tweeners somewhere else, but it doesn't work right now.

Thanks for the fix. For my project I setted and stopped the tween on a dedicated function called `reset_position` just for this setup calling `tween.tween_callback(reset_position)` at the end. This ensures that only one tween is created at a time and no need to check for an empty tween.

For people searching for similar solution:
```
var tween: Tween

func _ready() -> void:
	timer.timeout.connect(_on_timer_timeout)
	default_position = area_2d.position
	reset_position()


func test():
	area_2d.position += Vector2(5)
	timer.wait_time += 1
	timer.start()
	if tween.is_running():
		tween.stop()


func _on_timer_timeout():
	tween.play()


func reset_position():
	tween = create_tween().set_trans(Tween.TRANS_QUAD).set_ease(Tween.EASE_IN_OUT)
	tween.stop()
	tween.tween_property(area_2d, "position", default_position, 5.0)
	tween.tween_callback(reset_position)
```
