### ISSUE TITLE
4.0: Some fonts look less crisp at non-integer editor scale factors compared to `3.x`

### ISSUE THREAD

**Issue by DarkMessiah** [godotengine/godot#57340]
### Godot version

4.0 alpha 1

### System information

Windows 11

### Issue description

Some fonts looks not clear with 125% editor scale on 2560x1440 resolution.

Godot 4.0 alpha 1
![godot4](https://user-images.githubusercontent.com/1756388/151513948-7862e5c4-f993-4457-bc86-a727a564af77.png)

Godot 3.4.2
![image](https://user-images.githubusercontent.com/1756388/151517364-0a7c578d-4695-45a8-b30c-095d5b187be6.png)

https://screenshotcomparison.com/comparison/21047

### Steps to reproduce

Set editor scale to 125%.

**Comment by Calinou** [comment]
This occurs because font glyphs aren't snapped to pixels anymore, while it used to be the case on `3.x`. I wonder if the **Snap Controls To Pixels** project setting is broken.

**Comment by DarkMessiah** [comment]
Some icons in tree looks bit blurry (script icon in tree and icons on top panel over scene). Node names in the tree are cut off from the bottom by a couple of pixels.

**Comment by bruvzg** [comment]
> I wonder if the Snap Controls To Pixels project setting is broken.

It's doing absolutely noting, just setting `snap_controls_to_pixels` variable in the `Viewport`, which is not used anywhere.

> This occurs because font glyphs aren't snapped to pixels anymore

Font rendering functions always snap glyphs to the pixels, but it's doing it in the local control canvas item coordinates. Positions of controls aren't snapped:

Change this option to `true` should fix it, but probably the right way to fix it is to reimplement `Snap Controls To Pixels`.

https://github.com/godotengine/godot/blob/78e3e65e7c38d18128524e0822a106ac76e38800/editor/editor_node.cpp#L610

**Comment by bruvzg** [comment]
In particular, this code is missing from `4.0` for some reason:

https://github.com/godotengine/godot/blob/9cdd110cc3a7affe8c633f24d640c0c729ee6f06/scene/gui/control.cpp#L439-L442
