### ISSUE TITLE
LSP only show one error at a time

### ISSUE THREAD

**Issue by atirut-w** [godotengine/godot#57348]
### Godot version

3.4.2.stable.arch_linux

### System information

(Considered irrelevant)

### Issue description

When editing scripts and making mistakes, Godot's LSP only shows the first error in the script:
![Screenshot from 2022-01-28 19-18-16](https://user-images.githubusercontent.com/25323231/151545673-e7b21daf-07a7-41a1-a837-6862609a25d0.png)
![Screenshot from 2022-01-28 19-18-57](https://user-images.githubusercontent.com/25323231/151545734-321a842a-77a2-41ba-a19f-2438443532e9.png)
![Screenshot from 2022-01-28 19-19-15](https://user-images.githubusercontent.com/25323231/151545773-33824a32-40a4-41ea-b7ee-f60c1f8a52fe.png)

### Steps to reproduce

1. Edit a script with an external editor that supports LSP and can show more than one errors/warnings at once + Something to hook it up to Godot's LSP
2. Make more than one mistake in the script
3. Only one error/warning is shown at a time.

**Comment by pycbouh** [comment]
I think that's just how GDScript parser works in Godot 3. It breaks on the first error.

**Comment by atirut-w** [comment]
Can I expect a fix for this on 3.x any time soon?

**Comment by pycbouh** [comment]
It's not an issue, it's just how the parser works. It's likely impossible to change this in 3.x without reworking the entire thing.

**Comment by atirut-w** [comment]
> It's likely impossible to change this in 3.x without reworking the entire thing.

Sad. It's so useful to be able to see all the errors and warnings, too.
