### ISSUE TITLE
Imported GLTF animations have blending and scale issues

### ISSUE THREAD

**Issue by splitho** [godotengine/godot#57352]
### Godot version

4.0 dev

### System information

Windows 10

### Issue description

I have 2 animations, 1 for idle and 1 for aiming, I created a animation tree,  exactly the same as the one I made for godot 3. 
If I blend between the 2, the weapon bone just goes wild up and down. 
[](https://youtu.be/k0aeWKcoqdg)
[](https://youtu.be/e9Gucxbef6o)

### Steps to reproduce

I have 2 animations, 1 for idle and 1 for aiming, I created a animation tree,  exactly the same as the one I made for godot 3. 
If I blend between the 2, the weapon bone just goes wild up and down. 

### Minimal reproduction project

[Godot 4 Animatin Tree Bug.zip](https://github.com/godotengine/godot/files/7959051/Godot.4.Animatin.Tree.Bug.zip)

**Comment by splitho** [comment]
Godot 4 : https://youtu.be/e9Gucxbef6o
Godot 3 : https://youtu.be/k0aeWKcoqdg

**Comment by fire** [comment]
My first guess is this is not an importing issue but an animation blending issue which is being tracked by @TokageItLab .

**Comment by TokageItLab** [comment]
Dupe #54407

**Comment by splitho** [comment]
Thanks. Didnt' see it !
