### ISSUE TITLE
Bit masks and layers don't update their names in opened property fields

### ISSUE THREAD

**Issue by DrunkenToast** [godotengine/godot#57364]
### Godot version

3.4.2.stable and 4.0.alpha1

### System information

EndeavourOS Linux x86_6, 5.16.2-arch1-1, Plasma 5.23.5 Xorg

### Issue description

When changing a layer or mask name it will not change in the editor properties unless you manually refresh it by selecting another node.

![image](https://user-images.githubusercontent.com/20017197/151593733-a3c99f28-b10c-47d4-ad66-03e50c2c16d4.png)
![image](https://user-images.githubusercontent.com/20017197/151593786-e21d4823-ef84-4cc9-8f85-20f5f1ab5a15.png)

### Steps to reproduce

1. Open a node where you can change the collision layer
2. Change the layer name in project settings
3. Save changes and close the settings
4. Hover over the changed layer name and observe old name
5. Select a different node and reselect the other one (refresh node properties on the side)
6. Hover over the changed layer name and observe new name

Applies to all layer and masks settings (collisions, light, 2d/3d)

**Comment by Calinou** [comment]
@DrunkenToast Does this occur in 3.4.2?

**Comment by DrunkenToast** [comment]
> @DrunkenToast Does this occur in 3.4.2?
@Calinou After testing it with 2d collision layers in godot 3.4.2.stable I can confirm this does happen.

**Comment by Calinou** [comment]
I wonder if the `project_settings_changed` notification can be listened to on `master` to resolve this. In `3.x`, this notification doesn't exist yet, but it's being added by https://github.com/godotengine/godot/pull/53296.

**Comment by jmb462** [comment]
I've updated my PR about renaming layers to fix this issue.

**Comment by DrunkenToast** [comment]
This looks great!
