### ISSUE TITLE
Panning is sometimes clamped too early in 2D

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#5736]
Tested on Godot 2.0.4, 2.1 beta, 2.1.4, 2.1.5 rc1 and 3.0.2 on Windows 10 64 bits

It's been a long time that I can't see some of the GUI elements in a scene of my game, because panning doesn't allows me to go further. I managed to reproduce the issue in 2.1 as well with a similar scene structure, although I didn't tested enough to know if it can happen on simpler scenes.

Here is an example project. Open it, then immediately pan to the right. Notice you cannot fully see the HSlider on the right.
[PanningBlocked.zip](https://github.com/godotengine/godot/files/367311/PanningBlocked.zip)

**Comment by Calinou** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Zylann** [comment]
This still happens in 2.1.4 and 2.1.5 rc1.

**Comment by dakennedyd** [comment]
This bug stills happens in 3.1.1 stable

**Comment by FeralBytes** [comment]
I think I found that this still exists, but as a work around using; "view" > "frame selection" that is far to the right; seemed to fix it in that I get a horizontal scroll bar back.
Godot Version: 3.2.0 Beta 1

**Comment by Calinou** [comment]
@FeralBytes You can also disable **Editors > 2d > Constrain Editor View** in the Editor Settings.

**Comment by FeralBytes** [comment]
@Calinou Thanks, that fixed it!
