### ISSUE TITLE
`Object` `connect` and `emit_signal` could be unexposed as superseded by `Signal` methods

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#57360]
### Godot version

v4.0.alpha1.official [31a7ddbf8]

### System information

Win 64

### Issue description

In the current official alpha build, I can use both GDScript1 and GDScript2 methods to connect and emit signals.
This makes it harder to discover and learn GDScript2 because I'm not pushed by the engine to change habits. 

GDScript1 will also not be marked red while writing the code. Meaning there is no indication for a user this is going to be obsolete going forward.

Alpha1 also allows a mix of both, so as a user who wants to use GDScript2 I never quite know for sure whether I got it all or if part of it is still GDScript1 because I don't get any feedback.

### Steps to reproduce

both of these work:

```
emit_signal("a")
connect("a", self, "react_to_a")
```

```
a.emit()
a.connect(self.react_to_a)
```

### Minimal reproduction project

[signal_test_G4_alpha1.zip](https://github.com/godotengine/godot/files/7959669/signal_test_G4_alpha1.zip)

**Comment by KoBeWi** [comment]
We should probably show a deprecation warning. Or unexpose `connect()`, there's no use-case where it's needed instead of the new syntax (aside from backwards-compatibility, but it can be auto-converted).

**Comment by akien-mga** [comment]
It's worth discussing indeed, but removing these methods does remove a handy and well-known option to connect and emit signals using strings, which can sometimes be a requirement (e.g. if you need to create the string programmatically `"do_action_player%s" % player_id`).

Without these methods, it's still possible, but not the most straightforward:
```gdscript
Signal(self, "mysignal").connect(Callable(self, "mymethod"))
Signal(self, "mysignal").emit()
```

**Comment by KoBeWi** [comment]
> "do_action_player%s" % player_id

That's what signal binds are for:

`signal.connect(do_action_player.bind(player_id))`

tbh I can't think of a use case where you need to use a constructed string for method/signal name.

**Comment by golddotasksquestions** [comment]
I don't know what's the best solution for dynamic naming is since I have almost no GDScript2 experience. But what I do know is that signals are an essential part of Godot and one which is easily among the top3 hurdles (things being asked for help in the community channels) by beginners.

Since it is so essential and integral to Godot, I believe it's very important to make it the least confusing it can be. More syntax styles are therefore not really ideal or helping. I think we would have much less confusion amoungst beginners learning godot, if they need to learn about one syntax logic, not two, the old and the new. 

Coding beginners will see no benefit of using less strings. They will only wonder "Why do I have to use strings here, but write in a completely different manner elsewhere? Why can't I use the string method for everything?". 

Learning these abstract rules of logic is straining enough. Learning multiple variations of doing almost the same thing for no apparent reason makes it even harder.

**Comment by akien-mga** [comment]
> > "do_action_player%s" % player_id
> 
> That's what connection binds are for:
> 
> `signal.connect(do_action_player.bind(player_id))`
> 
> tbh I can't think of a use case where you need to use a constructed string for method/signal name.

Yeah from the top of my mind I can't really think about a good example either. I just wanted to raise it for discussion but that's pretty niche IMO - and thus it might be niche enough that we don't need to keep the compat methods for it.

Using constructed strings to access identifiers (e.g. action names for local multiplayer) is more common, but for signals and method names I never had to resort to such hacks myself.

**Comment by seppoday** [comment]
To be honest I knew that I can connect signal in new way. But it is first time someone told me I can emit signal by using "signalname.emit()". So golddotasksquestions is kinda right.

**Comment by akien-mga** [comment]
There's also `Object.call()` and `Object.call_deferred()` which can be replaced with `Callable.call()` and `Callable.call_deferred()`.

But thinking about it some more, I'm not sure this is a good idea because I'm not sure this is practical/possible to change. The `Object` methods are still needed in the core codebase, and the bindings are probably still relevant for GDExtension and C#.

**Comment by Anaxan** [comment]
I can't seem to make the first example work, if anybody could check this I would appreciate it.

 I would like to use the old syntax for making a custom Visual Script Node. The current method of making a callable variable is a bit cumbersome and I would like to bypass it if possible by using the old connection method.

As well I sometimes use Object,call("method", arguments) when making custom nodes as the current VS call node is broken and will not pass arguments.

**Comment by KoBeWi** [comment]
`connect` actually can't be unexposed, because it's used in connection dialog for UndoRedo. We could rename it to `_connect()`, to hide it from the view as internal method.

**Comment by Zireael07** [comment]
Whichever you decide to do, please update the docs accordingly. I had to fix my connection checks by trial and error as the docs are still somewhat lacking.

**Comment by akien-mga** [comment]
> Whichever you decide to do, please update the docs accordingly. I had to fix my connection checks by trial and error as the docs are still somewhat lacking.

Can you point to the parts which are lacking, and describe what you'd like to see added?

**Comment by Zireael07** [comment]
Most tutorials, as you mentioned. The only way to figure it out was to go to class docs, and it took me embarrassingly long to figure out I needed to look at Callable docs for the last piece of the puzzle.

**Comment by Ansraer** [comment]
I personally am in favour of keeping the string based methods exposed, since I already know that sooner or later I will end up in a situation where I have to construct/modufy the string. But maybe we could hide them somehow?

Don't really use gdscript much so I am not certain if it already supports static methods, but what about the following?
´´´
Signal.emit_signal("a")
Signal.connect("a", self, "react_to_a")
´´´
In addition some warnings could be added to the documentation, informing people about the new way to do this.

**Comment by KoBeWi** [comment]
> I already know that sooner or later I will end up in a situation where I have to construct/modufy the string.

Does this assumption have any base? Did you ever need to construct a signal/method name? Concrete examples would be useful.
Also this would still be possible, but in a different way.

**Comment by Zireael07** [comment]
> Also this would still be possible, but in a different way.

Please document it somewhere.

My use case: I have two or three factions in my game. I could do 
`func _on_whatever()` and pass it the group (or do a chain of ifs within the function checking for it) 

OR (with constructing a method name)
func _on_whatever_ally() and _on_whatever_enemy()

No risk of confusion/forgetting which one is which and/or forgetting to account for a new faction

**Comment by mhilbrunner** [comment]
> > Also this would still be possible, but in a different way.

> Please document it somewhere.

```
x.signalname.connect(Callable(self, "some_func_string"))
```

**Comment by h0lley** [comment]
unfortunately since methods of built-in types cannot be passed as callables (https://github.com/godotengine/godot/issues/58912), I am still stuck using `emit_signal` in places like `tween.tween_callback(emit_signal.bind("my_signal"))`.

**Comment by YuriSizov** [comment]
We've discussed the relevant PR for this issue, and decided it's better to still allow the old methods to exist.

**Comment by golddotasksquestions** [comment]
Why? @YuriSizov

**Comment by YuriSizov** [comment]
See Juan's comment in the linked PR https://github.com/godotengine/godot/pull/57431#issuecomment-1240938231

**Comment by golddotasksquestions** [comment]
This does not explain why both methods should be exposed to GDScript.

**Comment by akien-mga** [comment]
It does. Methods need to be exposed for language bindings to have access to them. Once exposed, it's available for all languages. We can't unexpose them for GDScript only.
