### ISSUE TITLE
Vulkan: Improve SDFGI property adjustment usability

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#57366]
### Godot version

4.0.dev (fc09d783f)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 495.46)

### Issue description

In WorldEnvironment's Environment resource, SDFGI has 3 properties that are linked to each other (others will be modified when you modify one of those):

- **Min Cell Size**
- **Cascade 0 Distance**
- **Max Distance**

Additionally, **Max Distance** depends on the **Cascades** property in SDFGI.

If those properties are initially set to different values, discrepancies may occur, causing the "revert" buttons to act strangely.

To avoid confusion, I think we should remove this kind of linked properties to keep only **Min Cell Size** (which is how one typically adjusts the overall SDFGI detail level). This means **Cascade 0 Distance** and **Max Distance** would be removed, although they could be kept as read-only methods to ease debugging and optimization work.

### Steps to reproduce

- Add a WorldEnvironment node with a new Environment resource.
- Enable SDFGI in the Environment resource.
- Play around with the properties mentioned above.

### Minimal reproduction project

N/A

**Comment by fire** [comment]
Here's an alternative perspective. What would break if we choose `Max Distance`?

**Comment by Calinou** [comment]
> Here's an alternative perspective. What would break if we choose `Max Distance` as the only property?

Max Distance will change depending on the value of the Cascades property, so I don't think it's a good idea.
