### ISSUE TITLE
Unable to run Godot after compiling: Undefined symbol: __gxx_personality_v0 [Ubuntu 20.04, LLVM]

### ISSUE THREAD

**Issue by AlekEagle** [godotengine/godot#57378]
### Godot version

3.4.2 (45eaa2d)

### System information

Linux, Ubuntu

### Issue description

I've tried to compile godot with the GodotSteam module and mono support, and everytime the build finishes, it finishes successfully but the resulting binary throws the error `bin/godot.x11.opt.tools.64.llvm.mono: symbol lookup error: /lib/libmonosgen-2.0.so.1: undefined symbol: __gxx_personality_v0` my system has all of the latest relevant packages needed for building, but it still fails. 

### Steps to reproduce

build with
`scons p=linux tools=yes module_mono_enabled=yes mono_glue=no use_llvm=yes use_static_cpp=yes use_lld=yes -j12`
and try to generate mono glue

**Comment by AlekEagle** [comment]
this is also happening without a mono build

**Comment by Calinou** [comment]
For the record, `__gxx_personality_v0` also appears in https://github.com/godotengine/godot/issues/44987.

**Comment by AlekEagle** [comment]
I saw that one, but I only get the undefined symbol error

**Comment by akien-mga** [comment]
> Linux, Ubuntu

What version? Which Mono packages do you have installed exactly, and from where?

> this is also happening without a mono build

I don't understand what this means - the error is specific to a Mono library, it can't happen with a non-Mono build.

> `bin/godot.x11.opt.tools.64.llvm.mono: symbol lookup error: /lib/libmonosgen-2.0.so.1: undefined symbol: __gxx_personality_v0`

This sounds like a Mono packaging error on your distro. `/lib/libmonosgen-2.0.so.1` is a system package, and if it can't find a symbol that it requires, it's a packaging bug.

It might be related to https://github.com/mono/mono/issues/19628

**Comment by AlekEagle** [comment]
Technically I have KDE Neon, which is just Ubuntu 20.04 with rolling releases for KDE Plasma, other than that I think it can be considered baseline Ubuntu.

As for my mono version, I am using Mono 6.12.0.112.

As for it "happening without a mono build", I worded that wrong and I meant to say that it also happens on a Godot build that lacks Mono support, giving me something along the lines of `bin/godot.x11.tools.64.llvm: symbol lookup error: bin/godot.x11.tools.64.llvm: undefined symbol: __gxx_personality_v0` with a build that lacks Mono support.

the `/libmonosgen-2.0.so` file that is dropped in the bin directory suffers the same issue, as when I add the `.1` suffix on the local file the same error happens.

There are no build errors, as the only output from building is a few warnings about strict type casting for some data that involves a non standard module I'm including which is GodotSteam from Gramps (https://github.com/Gramps/GodotSteam). ldd also shows no missing libraries either, and building with different versions of C and C++ also don't affect this error.

I hope this can help clear up any and everything that was confusing.

**Comment by akien-mga** [comment]
Does it work if you compile with GCC and GNU ld instead of LLVM and lld?

Are you able to compile and run other C++ code with LLVM and lld on that system?

**Comment by AlekEagle** [comment]
i am able to compile to and run other c++ code, and ive tried without llvm and lld

**Comment by akien-mga** [comment]
Can you build with `verbose=yes` and post the output? (just one line with the full build command shown should be enough)

It seems like you're using a C compiler instead of a C++ compiler. Do you have `CXX` defined in your environment? Are you using a wrapper script like `distcc`?

**Comment by AlekEagle** [comment]
nope, just plain gcc and g++ 9, working on a verbose output now

**Comment by AlekEagle** [comment]
[scons-verbose.log](https://github.com/godotengine/godot/files/7990605/scons-verbose.log)

and then another libstdc++ related error
`./bin/godot.x11.tools.64: symbol lookup error: ./bin/godot.x11.tools.64: undefined symbol: __cxa_pure_virtual`

**Comment by AlekEagle** [comment]
I'm really embarrassed, I had an outdated libsteam_api.so in my /lib folder, definitely a mistake I hopefully won't make again.
