### ISSUE TITLE
normalized() vec3 has bug in visual scripts . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot#57373]
### Godot version

Godot 4 dev . .

### System information

Windows 10 . .

### Issue description

The new search bar, is really nice, it's easier, to find stuff . .

However, for some reason vec3 normalized() now doesn't work . .

![Skærmbillede (2833)](https://user-images.githubusercontent.com/83387915/151630550-71116069-65df-4e37-9b3a-958d5e3c02db.png)

![Skærmbillede (2834)](https://user-images.githubusercontent.com/83387915/151630580-333222ed-99aa-4237-8cb2-16a7f607eda3.png)

![Skærmbillede (2835)](https://user-images.githubusercontent.com/83387915/151630588-94ce0cd1-9842-45b9-92fa-190ec03a1cff.png)

![Skærmbillede (2836)](https://user-images.githubusercontent.com/83387915/151630607-0a619161-1dbd-4d82-a2d7-53a922e4a3cb.png)

Or, one doesn't get a simple math box, like before . . It has gotten more complicated, had to tweak box to get it even working . . So, thanks for adding that extra search options, my complaint is now one has to click from search, to search all, to find most of boxes, before it took one click, now it takes two, sigh to even find something, like normalized(), for vec 3 . .

One step forward, two steps back . . .

### Steps to reproduce

Try new search system, the core idea of adding the buttons is quite good, the problem is it takes longer, bec. one has to click an extra button, to even find math boxes, so, it takes longer, and the boxes now appear, to be even worse, to use . .

9 / 10, for new system . . I hope you can figure out these things, and, make .vs even better, I know it's tough work, big thanks, for even trying, thx . . !

### Minimal reproduction project

Make empty scene, search for normalized vec 3 . . .

ps. Thanks for the alpha, hope you make Godot 4 even better, as a dev, thanks for all the work, tears . . <3

**Comment by charlesmlamb** [comment]
ps. I know visual script is a complicated mess, really enjoyed it as a learning tool, and, for smaller projects . . It's how I began to learn GDScript, so, I hope you'll make it a rock - solid learning tool, it's really good for beginners, and fun to learn, makes it easier to understand how coding works, thx . . . !

**Comment by fire** [comment]
Will look into it. Can also ping @Gallilus

**Comment by charlesmlamb** [comment]
Ok, Visual script is almost done, amazing feature . . Will use it, for most of my projects, until I learn to code, like it bit better, but, code is also fun . . .

I give 9.8 / 10, for Godot 4 #thanks . .

**Comment by charlesmlamb** [comment]
Can I say, the new themes are really nice, hoping for bit more customization, or, bug - fixes . . 

![image](https://user-images.githubusercontent.com/83387915/151657674-325cf5cd-5c5c-45bd-a930-1bd45b486c8d.png)

Having customization options help get the right feel, for a user, or, perhaps a project . . . 

![image](https://user-images.githubusercontent.com/83387915/151657716-a00ac724-21ed-451d-b0de-dbcbb8cdbcb8.png)

Really happy with Godot, don't have more requests, look forward to using it for many years, starting with 3D cartoon project . . .

![Animation (6)](https://user-images.githubusercontent.com/83387915/151657740-6d1b4d1c-d3b5-4a74-80a4-efc8f6851e1c.gif)

Also, gonna recommend it to danish media productions, I work in a place, 30 small companies, 150 workers, already begun, spreading the word #thanks . . !

**Comment by Gallilus** [comment]
Hi, @charlesmlamb good to hear you are still checking on visual script.

I understand your problem. When you do rmb you search from Mechinstande3D when dragging out from Vector3 You get quick access to what you are looking for.

In your case, you get a script variable and its Variant information is not recognised by the editor.
![image](https://user-images.githubusercontent.com/20573784/151660562-a4e8c7fb-920b-4613-8180-303f3c00e1d2.png)

And by default, it looks at script relevant functions. So the issue is.
# Why is the VisualScriptPropertySet node not recognising scrip_variable variants from self?

**Comment by charlesmlamb** [comment]
Uhh, I use latest build, not Godot 4 alpha . . So, it may be sort-of different . . .

When I move a vc3 port, get this list . . .

![image](https://user-images.githubusercontent.com/83387915/151681291-1190d57b-1174-486b-93fe-4bc59eaf500b.png)

Basically, nothing . .

I still care about visual script, but bec. of the amazing improvements, have almost nothing left to ask for, though still on look, for better UX, bug - fixes, new features, and UI, it's mostly so good now, I plan on using it for some games, and, try and teach here, there, when have time, thx . . . !

**Comment by KoBeWi** [comment]
VisualScript was removed.
