### ISSUE TITLE
HTML5 game has its own clipboard contents and it is not shared with the system (Firefox)

### ISSUE THREAD

**Issue by CHIESOFTWARE** [godotengine/godot#57382]
### Godot version

3.4.2

### System information

linux ubuntu 21.04 lts

### Issue description

I saw this problem here #12587 and it shows as closed, but it's happening again. 

System clipboard contents cannot be pasted in controls such as LineEdit. The game has its own clipboard contents and it is not shared with the system.

OS.get_clipboard() stays empty unless we copy text from the game itself. Only HTML5

### Steps to reproduce

    Make a scene with a LineEdit.
    Export it to HTML5
    Run it in a browser
    Copy text from any source but the game (eg: the URL bar of the browser)
    Try to paste it in the LineEdit.

**Comment by Ansraer** [comment]
Accessing the clipboard from a webapp is somewhat tricky due to security concerns. AFAIK godot does the best it can when the browser supports the clipboard API. What browser are you using?

https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API

**Comment by Calinou** [comment]
@CHIESOFTWARE Which browser did you try? In my experience, the only browser where clipboard support works reliably with Godot is Chromium-based browsers. It works best when right-clicking to copy/paste using LineEdit/TextEdit's contextual menu. I've never gotten it to work on Firefox though.

**Comment by CHIESOFTWARE** [comment]
Hello @Calinou I am using firefox. I tried it with the context menu of the line edit and with os.get_clipboard

**Comment by Ansraer** [comment]
See the msdn link I posted above. Due to security concerns firefox has parts of the clipboard api disabled, there is nothing godot can do to fix that.

**Comment by Ansraer** [comment]
See the msdn link I posted above. Due to security concerns firefox has parts of the clipboard api disabled, there is nothing godot can do to fix that.

**Comment by CHIESOFTWARE** [comment]
ok @Ansraer , In that case I will leave a note in the game indicating that it should be played from chrome.

**Comment by Ansraer** [comment]
Depending on the type of game you are working on you could also move the input fields out of the game ui and into the html page. You could then use the JS api to get the input from those html input fields.

**Comment by Faless** [comment]
This is documented here: https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_web.html#clipboard

**Comment by nbourre** [comment]
Using FireFox, I had the same problem and manage to fix it with the link provided in this [comment](https://github.com/godotengine/godot/issues/57382#issuecomment-1024903749) 

**Solution** 
1. Configure Firefox flag --> Type `about:config` in the address bar
2. Search for `dom.events.asyncClipboard.readText`
3. Set the value to `true`
4. Restart Firefox (not sure if necessary)
5. Pasting from other apps should work.

**Comment by Ariorick** [comment]
Godot 3.5.1, same problem on Chrome 107.0 for macOs

**Comment by Patashu** [comment]
For future people who click on this issue and don't need a LOT of clipboard access, here is my workaround that I'll be using for my own Godot HTML5 games using the 'prompt' function: https://www.reddit.com/r/godot/comments/17rsemr/how_to_access_the_clipboard_as_a_html5web_godot/

I hope it helps someone out there!
