### ISSUE TITLE
TextureButton hidden behind top_level when it is child of top_level

### ISSUE THREAD

**Issue by danilw** [godotengine/godot#57388]
### Godot version

3.5-beta1

### System information

Linux x11

### Issue description

3.4.2-stable - works as expected
3.5-beta1 - this bug

![1](https://user-images.githubusercontent.com/24825887/151654582-fca28628-1fa8-4943-a80e-2e4ef6471ffd.png)

Every other element stays visible, only TextureButton hidden. (if you click it, it shows, but then when focus lose it hide again)

### Steps to reproduce

Launch example project.

### Minimal reproduction project

[test_UI_order.zip](https://github.com/godotengine/godot/files/7963329/test_UI_order.zip)

**Comment by akien-mga** [comment]
Confirmed locally, it seems to be a regression from #56472. (Doesn't happen on `3.4` where this PR wasn't cherry-picked, but cherry-picking it locally triggers the bug.)
