### ISSUE TITLE
RichTextLabel URL BBCode tag clickbox sizing issues

### ISSUE THREAD

**Issue by Tyrannosaurus1234** [godotengine/godot#57380]
### Godot version

4.0 alpha 1

### System information

Kubuntu 20.10

### Issue description

RichTextLabel [url] BBCode tags' clickable area does not encompass the entire area of the link's display text, it's short by about 1 character. Tested with default font as well as https://fonts.google.com/specimen/Dongle . Furthermore, the clickbox is adversely affected by the font's `spacing_bottom` and `spacing_top` properties, it seems like it does some sort of alpha check, instead of basing the clickbox offset purely on glyph size?

I would expect these links' clickboxes to encompass the entire bounding rect of the display text portion's glyphs. In the picture (dongle font), the green box is clickable with font settings `spacing_top: -12` `spacing_bottom: -4` and input `[url=test]typesetting[/url]`, but the red area isn't.
![rtl](https://user-images.githubusercontent.com/36250109/151641640-0dc53474-60ad-474e-a7d3-56edce87838b.png)

RTL's `meta_underlined` property does not affect this, the underline extends beyond the clickable area.

### Steps to reproduce

1) create a RichTextLabel with BBCode enabled a [url] tag in the text field
2) set up something to catch the meta_clicked signal
3) click around different parts of the meta block
OR
1) open a piece of documentation or GDScript file in the editor
2) hover mouse over last character in a link in the documentation, or the same while holding CTRL and hovering over something with a doc page in the GDScript file

**Comment by Calinou** [comment]
Additionally, it might be a good idea to make the clickbox one or two pixels larger on all sides to make clicking easier, especially on touchscreens.

**Comment by Tyrannosaurus1234** [comment]
Doesn't happen on 3.4.2 - the clickbox is still undersized on the right side (l->r), but just a hair, maybe 2 pixels, and the verticality issue doesn't happen at all.

**Comment by KoBeWi** [comment]
Still valid in alpha 6.

**Comment by Rindbee** [comment]
This is caused by the following code:

https://github.com/godotengine/godot/blob/cf194847468e00de682074a14b2cf4ccf7b69188/scene/gui/rich_text_label.cpp#L1470-L1472

`TextServer::shaped_text_hit_test_position` produces a different offset from the character position than expected.
