### ISSUE TITLE
DataType enumerations are undefined in gdscript

### ISSUE THREAD

**Issue by JBillsDev** [godotengine/godot#57389]
### Godot version

 v3.4.2.stable.official [45eaa2daf]

### System information

Windows 10

### Issue description

The DataType enumerations are not extended to GDScript, and are needed for calling various functions. While the values work for the function calls, this is not convenient, and the enumerations listed in the documentation should work in GDScript.

enum DataType:
DATA_TYPE_COLOR = 0 --- Theme's Color item type.
DATA_TYPE_CONSTANT = 1 --- Theme's constant item type.
DATA_TYPE_FONT = 2 --- Theme's Font item type.
DATA_TYPE_ICON = 3 --- Theme's icon Texture item type.
DATA_TYPE_STYLEBOX = 4 --- Theme's StyleBox item type.
DATA_TYPE_MAX = 5 --- Maximum value for the DataType enum.

IE:
Variant get_theme_item ( DataType data_type, String name, String node_type ) const
PoolStringArray get_theme_item_list ( DataType data_type, String node_type ) const
PoolStringArray get_theme_item_types ( DataType data_type ) const

![image](https://user-images.githubusercontent.com/91576853/151655058-7f69b562-dab3-499d-86e4-993a6642242a.png)

### Steps to reproduce

# Trying to reference the DATA_TYPE enums, but not declared in GDScript

extends Node2D

func _ready() -> void:
	print_debug(DATA_TYPE_STYLEBOX)

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/7963357/test.zip)

**Comment by qarmin** [comment]
It is available in Theme class
```
Theme.DATA_TYPE_COLOR
```

**Comment by JBillsDev** [comment]
I feel so sheepish! Sorry for wasting your time!
