### ISSUE TITLE
Code editor improvement: highlight singletons

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#5739]
I just discovered that it's possible to use auto-load singletons by their names, as if they were global variables.

``` gdscript
PlayerSettings.load()
# Instead of this
get_node("/root/PlayerSettings").load()
```

It would be nice to have them coloured in the code editor because otherwise they look like variables coming from nowhere. Usually, you can look up for the definition of a member or class by searching the file, but if it's a global thing you don't know that by just looking at the code.

**Comment by Calinou** [comment]
This issue still seems to be relevant as of https://github.com/godotengine/godot/commit/b030834b6384d5f57e5fc63db21b643adc86b3da.

**Comment by Zylann** [comment]
Nowadays, something adds up to the intent behind that issue: named classes are also global-scope, maybe it makes sense to highlight them too?
