### ISSUE TITLE
Editor tooltips not scrollable

### ISSUE THREAD

**Issue by snailrhymer** [godotengine/godot#57399]
### Godot version

v4.0.alpha1.official [31a7ddbf8]

### System information

Windows 10

### Issue description

Expected behaviour:
![image](https://user-images.githubusercontent.com/3036176/151655238-6cbf9479-3d28-4744-9fa5-4c40dce57577.gif)

For me, the tooltips are scrollable with neither the mousewheel nor trackpad. They do stop the Inspector from scrolling though, so they are at least taking focus.

### Steps to reproduce

Mouseover a property in the inspector that has a multiline tooltip.
Move the mouse onto the tooltip and try to scroll.

**Comment by snailrhymer** [comment]
Need to check on [252ec22ff9fc2befd6b120fd40b0e008137a0392].

**Comment by Zireael07** [comment]
Why close? Was it fixed in a more recent build? I can't scroll on alpha 1 either...

**Comment by snailrhymer** [comment]
I don't know that scrolling is expected in alpha 1 - [this comment](https://github.com/godotengine/godot/issues/57174#issuecomment-1024840169) alludes to it being added more recently. I'll check to see if I can scroll in a more recent build, and reopen if not.

**Comment by snailrhymer** [comment]
Yep, just needs a later build - tested (78e3e65e7) and could scroll fine (though the default clipping is not ideal).
