### ISSUE TITLE
(4.0) Can't edit font size on multiple objects at once

### ISSUE THREAD

**Issue by seppoday** [godotengine/godot#57398]
### Godot version

4.0 alpha 1

### System information

Windows 11

### Issue description

This is not so much bug but kinda lack of cohesion. For example if i select multiple Label nodes I can modify they modulation and other properties. Simply make change on X nodes at a time.

But if I pick multiple labels. New font menu at the top dissapear and if I want to change font size I need to do it one by one.

One Label:
![image](https://user-images.githubusercontent.com/62170071/151660870-16bc14c5-a678-43e6-9f22-6212b49a03cb.png)

Multiple Labels:
![image](https://user-images.githubusercontent.com/62170071/151660888-15be070e-098d-4a02-8ac5-3cae5ca17d04.png)

### Steps to reproduce

Simply select multiple Labels.

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by NeilKleistGao** [comment]
I'm trying to deal with it. However, there is a question I need to figure out. If I select two labels with different properties (different font sizes e.g.), which value should be displayed in the editor? Or do I need to add another value (like `--` in some editor) to show that these two labels' font sizes are different?

**Comment by seppoday** [comment]
I think Photoshop approach is kinda good in this situation. In Photoshop if you select multiple text layers font size is just not displayed. So leaving empty space in font size property or adding ```--``` as you said is good in idea in my opinion.

**Comment by NeilKleistGao** [comment]
> I think the Photoshop approach is kinda good in this situation. In Photoshop if you select multiple text layers font size is just not displayed. So leaving empty space in font-size property or adding `--` as you said is a good idea in my opinion.
> 
> Word (Microsoft software in general) is doing it same way as Photoshop. Leaving empty space. So it is kinda standard.
> 
> ![image](https://user-images.githubusercontent.com/62170071/152637033-a3333c1b-3619-4c05-8243-32c5a1f8e01f.png)

It's a good example definitely. I also tried some in Word for different colors and fonts. It helps a lot! Thanks.

**Comment by akien-mga** [comment]
Fixed by #57689.
