### ISSUE TITLE
Vulkan memory alloc makes godot 4 fail to start on hybrid GPU setup (AMD integrated/NVIDIA dedicated)

### ISSUE THREAD

**Issue by svelezsaffon** [godotengine/godot#57396]
### Godot version

4.0-alpha1

### System information

Microsoft Windows 11 Home x64-based PC Processor	AMD Ryzen 9 4900HS with Radeon Graphics, 3000 Mhz, 8 Core(s), 16 Logical Processor(s) Installed Physical Memory (RAM)	16.0 GB NVIDIA GeForce RTX 2060 with Max-Q Design

### Issue description

When starting 4.0-alpha1.exe file, the following window appears.

![image](https://user-images.githubusercontent.com/8091482/151659366-8b3db428-e75d-4951-a92c-11a659a9ddf2.png)

### Steps to reproduce

1. Download godot 4 alpha 1, from https://downloads.tuxfamily.org/godotengine/4.0/alpha1/
2. Unpack the .zip file
3. Double click the .exe file

 

### Minimal reproduction project
No minimal reproduction project since the issue happens when starting godot.
_No response_

**Comment by Calinou** [comment]
@svelezsaffon Did you force Godot to run on your dedicated GPU? Try right-clicking the Godot executable and use the **Run with graphics processor** option to try both GPUs available.

**Comment by svelezsaffon** [comment]
@Calinou  thanks for your response, apologies for not giving more info about that. But I am not sure how to force it on dedicated GPU, unless my computer is forcing it without me knowing. I am also not seeing the option you mention.
![image](https://user-images.githubusercontent.com/8091482/151669311-53b4b9e4-e5ac-4cc2-8694-bc25bc581ce7.png)

**Comment by svelezsaffon** [comment]
@Calinou after digging a bit more, I changed the NVidia settings to autos elect and use both GPUs, and issue persisted

![image](https://user-images.githubusercontent.com/8091482/151669680-65f2a64f-891e-4d74-acbf-8c474d82c0ad.png)


Then I tried to force use it NVIDIA gpus, and the issue persisted.
![image](https://user-images.githubusercontent.com/8091482/151669717-b882a07f-d3c8-41f3-8f2c-468b099a69e8.png)

Then I tried to use the integrated GPU and the issue persisted.
![image](https://user-images.githubusercontent.com/8091482/151669758-9caeedb9-0330-44c6-bdf3-8ddb4dd0670d.png)

**Comment by svelezsaffon** [comment]
If I ran the .bat file that comes inside the .zip file, the following error is displayed on the console


```
Godot Engine v4.0.alpha1.official.31a7ddbf8 - https://godotengine.org
WARNING: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        ReadDataFilesInRegistry: Registry lookup failed to get layer manifest files.
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 224900496
     at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:154)
ERROR: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        Failed to open dynamic library "C:\ProgramData\obs-studio-hook\.\graphics-hook32.dll" with error 193
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 224900496
   at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:157)
ERROR: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        setupLoaderTrampPhysDevs:  Failed during dispatch call of 'vkEnumeratePhysicalDevices' to lower layers or loader to get count.
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 224900496
   at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:157)
ERROR: vkEnumeratePhysicalDevices reported zero accessible devices.

Do you have a compatible Vulkan installable client driver (ICD) installed?
vkEnumeratePhysicalDevices Failure
   at: (drivers/vulkan/vulkan_context.cpp:780)
ERROR: Condition "err != OK" is true. Returning: ERR_CANT_CREATE
   at: _window_create (drivers/vulkan/vulkan_context.cpp:1300)
```

**Comment by Calinou** [comment]
> If I ran the .cmd file that comes inside the .zip file, the following error is displayed on the console

The OBS messages can be ignored as per https://github.com/godotengine/godot/issues/56198, but it seems that Godot fails to find any GPU that supports Vulkan on your system. Are your graphics drivers fully up-to-date from AMD and NVIDIA (*not* your laptop OEM or Windows Update)?

**Comment by svelezsaffon** [comment]
@Calinou  NVIDIA GPU is on the latest driver
![image](https://user-images.githubusercontent.com/8091482/151670472-13d4cda0-6bcd-46fa-bfed-40b5bdc4d1d6.png)

**Comment by svelezsaffon** [comment]
@Calinou  I just updated AMD graphics drivers and godot 4 ran perfectly.

![image](https://user-images.githubusercontent.com/8091482/151670929-81f45d80-9b7d-4c41-a817-a002c9bfc589.png)

**Comment by svelezsaffon** [comment]
@Calinou i forgot to thank you for taking the time on this!
