### ISSUE TITLE
Connection icon glitch

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#5740]
Tested on Godot 2.1, Windows 10 64 bits

What happened:
When I click the connections icon next to the nodes in the scene tree, the Nodes dock is focused and shows connections. However, if I click another node's connection icons, the Node dock doesn't updates. The scene tree also shows the node as selected in addition to the ones that were already selected.

What was expected:
update the Node dock and unselect last nodes (or don't modify the selection, because we clicked the icon, not the node itself).

Video showing the behaviour:
[ConnectionsIconGlitch.zip](https://github.com/godotengine/godot/files/367322/ConnectionsIconGlitch.zip)

**Comment by vnen** [comment]
The Node docks shows the *selected* node, so I prefer to change the selection when you click the signals and groups icons.
