### ISSUE TITLE
Node spawning position in AnimationTreeEditor is strange

### ISSUE THREAD

**Issue by TokageItLab** [godotengine/godot#57410]
### Godot version

4.0.dev (2f57a11ed9b383706b72783c0d9b1e869774e08a)

### System information

MacOS 11.6

### Issue description

When you add a Node in AnimationTreeEditor, the Node is added in a far away location.

https://user-images.githubusercontent.com/61938263/151669768-6899d041-8a18-466e-a452-7164cd2ca6e5.mov

This bug is a rather recent regression, so I expect it is caused by some change in the method to get the canvas / window size.

### Steps to reproduce

Add a Node in AnimationTreeEditor.

**Comment by Calinou** [comment]
I can confirm this on `master` fc09d783f (Linux, 100% editor display scale).
