### ISSUE TITLE
New Shader created from the Inspector has wrong shader_type

### ISSUE THREAD

**Issue by Ansraer** [godotengine/godot#57418]
### Godot version

4.0 master

### System information

Windows 10 Vulkan amd 6900xt

### Issue description

When creating a new shader from the inspector of a shader material assigned to the shader_type is set to "canvas_item". This means that even when the shader material is attached to a MeshInstance users end up with a barebones shader that won't work out of the box.

### Steps to reproduce

1. Create MeshInstance (not CSGMesh3D!)
2. Add new shader material
3. Click shader field -> add new shader
4. Wonder why the new shader isn't working without manually switching it to spatial

### Minimal reproduction project

^ see above

**EDIT: see my second comment for more information**

**Comment by Chaosus** [comment]
Are you sure you didn't create a shader with a canvas_item shader type before and just load it into mesh by using this dialog? Because by default Node3D nodes materials should be handled by the engine (see https://github.com/godotengine/godot/pull/52781)

**Comment by Ansraer** [comment]
Yeah, created a new project, opened a new 3d scene, added a MeshInstance3D, added a cube mesh, add a ShadeMaterial, added a new Shader.

The dialog for the new shader always defaults to canvas_item, even when that makes absolutely no sense.

**Comment by Ansraer** [comment]
Thanks for pointing out #52781.
Did some debugging, it looks like the preferred mode is never set properly. When I open the shader_material in the inspector `EditoPrropertyResource::_update_preferred_shader()` is called the way it should be. However, the if-statement in that function that's supposed to detect whether I currently have a child of Node3D selected evaluates as false, and the preferred mode is thus never set to spatial.

**Comment by KoBeWi** [comment]
The description isn't precise. You are not adding shader to MeshInstance3D, but Mesh.

Doesn't work:
![image](https://user-images.githubusercontent.com/2223172/170527778-469f67cb-9362-4b74-93a8-49bf0ee751e1.png)

Works:
![image](https://user-images.githubusercontent.com/2223172/170527967-b2003d1a-f563-41f5-8c9a-a1b1b9e93bed.png)

We could add Mesh as possible type for Spatial shaders, but is it used only in 3D?

**Comment by clayjohn** [comment]
> We could add Mesh as possible type for Spatial shaders, but is it used only in 3D?

Mesh is used in both 2D and 3D, but PrimitiveMeshes are made to only be used in 3D. Internally, they are treated as 3D meshes, so calculating screen rect breaks if they are used in 2D. 

In my opinion, it would be safe to default PrimitiveMeshes to create a spatial shader. 

Also, I think it would be safe to default Mesh to Spatial as Meshes are used way more in 3D than in 2D, so if we have to choose, then we might as well default to spatial
