### ISSUE TITLE
Button inside viewport offsets mouse events when resizing game window

### ISSUE THREAD

**Issue by sicarul** [godotengine/godot#5741]
**Operating system or device - Godot version:**
Godot git master branch - Linux Debian 8

**Issue description** (what happened, and what was expected):
When adding a button inside a viewport, the mouse events work weirdly, it looks like they are all offset by the same amount of pixels as the window has been resized.
https://youtu.be/GO8twhUC6ag

**Steps to reproduce:**
Example project attached, it's a button inside a viewport.

**Link to minimal example project**:
[godot_buttonbug.zip](https://github.com/godotengine/godot/files/367415/godot_buttonbug.zip)

**Comment by akien-mga** [comment]
Indeed, I can reproduce it too. I'm not sure how to port the example to 3.0+ to test there though, as Viewport behaves differently in 3.0+.

**Comment by akien-mga** [comment]
Thanks! Confirmed working on 3.0.7.devel too, so closing as fixed in the 3.0 branch. I doubt we'll ever get it fixed in the 2.1 branch, many changes were done to Viewport in 3.0 to address this kind of issue.
