### ISSUE TITLE
MultiMeshInstance causes incorrect navmesh generation

### ISSUE THREAD

**Issue by macjuul** [godotengine/godot#57421]
### Godot version

v3.5.beta1.mono.official [b9b23d222]

### System information

Windows 10, GLES 3

### Issue description

Navigation mesh baking does not work correctly with MultiMeshInstances, both from the editor and during runtime. It appears as if the mesh rotation and translation is ignored as the navmesh cutout will always appear at the center of the NavigationMeshInstance.

The following screenshot demonstrates the regular MeshInstance cube working correctly, while both fences are generated at the center, and their rotation ignored.

![baked](https://user-images.githubusercontent.com/7606171/151677228-a5698334-a414-4c12-a0e6-8afdf4f6b80c.png)

### Steps to reproduce

- Build a MultiMeshInstance (I did so during runtime and saved the scene to disk)
- Bake the NavigationMeshInstance in the editor, or during runtime
- The navmesh cutout should appear in the wrong location

### Minimal reproduction project

[navmesh-demo.zip](https://github.com/godotengine/godot/files/7964746/navmesh-demo.zip)

**Comment by Calinou** [comment]
cc @Scony

**Comment by Scony** [comment]
Yeah, looks like transforms are messed up under some circumstances.
I believe in case of `MultiMeshInstance` there are two separate problems:
1. There's a transform missing in `_parse_geometry`'s calculations
2. There's a potential misalignment in the case of collecting geometry by group

I'm basically working on a solution right now. It should cover #57231 as well

**Comment by akien-mga** [comment]
Fixed by #57440.
