### ISSUE TITLE
Tooltips disappear when mouse leaves initiating Element

### ISSUE THREAD

**Issue by Sauermann** [godotengine/godot#57425]
### Godot version

v4.0.alpha.custom_build [e4265e86c]

### System information

Linux, Debain 11, Xfce, Nvidia, Vulkan

### Issue description

On Linux with Xfce it is nearly impossible to scroll tooltips, because as soon as the mouse-cursor leaves the item for which the tooltip is generated, the tooltip disappears - even if the mouse is still within the area of the tooltip. 

I would expect, that while the mouse is within the area of a scrollable tooltip, the scrollable tooltip should not disappear.

This also happens in v4.0.alpha1.official [31a7ddbf8]

Might be related to #57399.

### Steps to reproduce

As a prerequisite: Single Window Mode is "Off"

1. Move the mouse over a label so that a tooltip is displayed
2. Move the mouse into the area of the tooltip while still being in the area of the initial label
3. Now I can use the Mousewheel to scroll the tooltip
4. Move the mouse out of the area of the initial label while still being in the area of the tooltip
5. Now the tooltip closes

![o](https://user-images.githubusercontent.com/6299227/151679582-a1096597-788f-49de-a929-eb85ada726c5.gif)

### Minimal reproduction project

Not applicable

**Comment by Calinou** [comment]
Can you reproduce this after enabling **Single Window Mode** in the Editor Settings then restarting the editor?

**Comment by Sauermann** [comment]
If Single Window Mode is "On", I was able to witness the following two behaviors:

1. Move the mouse over a label so that a tooltip is displayed
2. Move the mouse into the area of the tooltip while still being in the area of the initial label
3. Now when I use the Mousewheel, the tooltip disappears and the enclosing properties area handles the scroll event.

Alternatively:

1. Move the mouse over a label so that a tooltip is displayed
2. Move the mouse into the area of the tooltip while still being in the area of the initial label
3. Move the mouse out of the area of the initial label while still being in the area of the tooltip
4. Now the tooltip closes
