### ISSUE TITLE
Rendering issue with shaders and transparency

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#57424]
### Godot version

3.4.2

### System information

PopOS

### Issue description

If this is just me, I apologise.

Take this simple shader, it works fine, and at a value of 0.5 it looks like this:
![Screenshot 2022-01-29 22:22:11](https://user-images.githubusercontent.com/12863685/151679434-a2c500c9-4994-4bf4-91dc-a012cdc37405.png)

```glsl
shader_type canvas_item;
uniform float dissolve_value : hint_range(0.0,1.0);
uniform sampler2D noise_texture;

void fragment() {
	vec4 noise_pixel = texture(noise_texture,UV);  //just a gradient greyscale image
	vec4 current_pixel = texture(TEXTURE, UV);
	if(noise_pixel.r >= dissolve_value)
	{
		COLOR.a-=1f;
	} 
	else 
	{
		COLOR=current_pixel;
	}
}
```
modify the code to be this (replace direct COLOR.a change to a variable):
```glsl
	if(noise_pixel.r >= dissolve_value)
	{
		//COLOR.a-=1f;
		current_pixel.a-=1f;
		COLOR=current_pixel;
	} 
	else 
	{
		COLOR=current_pixel;
	}
```
and you get this

![Screenshot 2022-01-29 22:20:39](https://user-images.githubusercontent.com/12863685/151679404-f6c2d216-d039-43a0-a888-72a60b784463.png)

### Steps to reproduce

As above

**Comment by clayjohn** [comment]
To understand what is happening here, you need to consider the state of the data as you write to it. Particularly, you need to consider what data is in each variable as you read from or write to it. 

In your first example you remove 1 from the alpha value of ``COLOR``, so the value written out of the shader is ``vec4(1.0, 1.0, 1.0, 0.0)`` in other words, it is a completely transparent (but would appear white if not transparent.

In your second example you are taking the value read from your texture and you are subtracting 1 from the alpha. However, the alpha varies in your texture so some pixels are going to end up with a negative alpha. Negative alpha values are not something that GPUs expect or know how to work with, so you end up with odd looking results. Your image would probably look as expected if you changed the first branch to:
```
//COLOR.a-=1f;
current_pixel.a-=1f;
current_pixel.a = max(current_pixel.a, 0.0); // this ensures that the alpha value is at least 0.0 and isn't negative
COLOR=current_pixel;
``` 

One additional thing that may have led to your confusion is how Godot handles the default ``TEXTURE``. When ``TEXTURE`` is not used in a shader, ``COLOR`` is internally assigned the value of the default ``TEXTURE`` at the current pixel ``UV``. However, if you read from ``TEXTURE`` in your shader, then ``COLOR`` is just plain white and you are responsible for setting the value of ``COLOR``. The docs go into more detail about this: https://docs.godotengine.org/en/stable/tutorials/shaders/shader_reference/canvas_item_shader.html#fragment-built-ins

**Comment by chucklepie** [comment]
ah, thanks for the explanation, sorry for the ticket, it can be closed.
