### ISSUE TITLE
Godot 4-alpha-1 : 2D Editor is difficult to zoom in and out with a mouse wheel

### ISSUE THREAD

**Issue by Richard74Huang** [godotengine/godot#57423]
### Godot version

4.0 Alph-1

### System information

Apple M1

### Issue description

2D Editor is difficult to zoom in and out with a mouse wheel but it works fine to zoom in 3D view. 

### Steps to reproduce

It can be easily reproduced in any 2D view.

**Comment by Calinou** [comment]
@Richard74Huang Does it work OK in Godot 3.4.2? See https://github.com/godotengine/godot/issues/28149.

**Comment by Richard74Huang** [comment]
Yes it works fine on 3.x and even works well in a 4.0-dev custom build just 1 week before the alpha-1.

**Comment by Calinou** [comment]
cc @KoBeWi

**Comment by KoBeWi** [comment]
I can't reproduce it on Windows. The zooming code was moved around in #57000, but it's the same as before.

My only suspect would be this:
https://github.com/godotengine/godot/blob/e4265e86ceee1bf08bd92b85b51e969310a08bd6/editor/plugins/canvas_item_editor_plugin.cpp#L1232-L1235
Previously the `p_scroll_vec.y` was `b->get_factor()` (`factor` property of mouse button event), so it's worth checking if it's the same value as before.

**Comment by Richard74Huang** [comment]
canvas_item_editor_plugin.h/cpp has changed a lot in the recent week and it is not easy to understand... On the other hand, magic track pad can zoom the editor perfectly.

**Comment by Plonq** [comment]
This is not just with M1. I have same (I assume) issue on Intel Mac, with alpha 5. If I scroll normally, nothing happens. If I scroll _really fast_, it moves a little bit. Seems to me the velocity threshold is way too high, or something along those lines. As mentioned above, zooming with the trackpad (pinch) is fine.
