### ISSUE TITLE
GDExtension: Scene/resource data can be lost when missing types

### ISSUE THREAD

**Issue by neikeq** [godotengine/godot#57427]
### Godot version

4.0.alpha1 (31a7ddbf8)

### System information

Ubuntu 21.10, Windows 10, macOS Monterey

### Issue description

Opening and saving a scene or resource that makes use of a GDExtension type will result in any data that depends on that type to be lost, including the type attribute itself. 
This is the same that happens if a built-in type cannot be found.
It's the opposite of **scripts** which rely on placeholder instances to persist data.

There are at least 3 reasons why a GDExtension type may be missing:

- The user may have forgotten to install the extension.
- A bug. Not that I know any in particular, but an unexpected failure to load an extension should not result in the potential of losing scene/resource data.
- **The extension may not be built yet.** This is the most likely scenario, specially when using GDExtension as a replacement for scripting.

For this report, I'm using `godot-cpp` as an example. But my main motivation is C#, as we plan to move it to the GDExtension system.

This bug (or unsupported use case) makes GDExtension unsuitable for scripting.

### Steps to reproduce

Using the [godot-cpp demo example](https://github.com/godotengine/godot-cpp/tree/a2633446536cb3ec9e9b3cb67bc67fa478557752/test):

1. Build the extension.
2. Open the main scene in the Godot editor.
3. Edit the node of type `Example` by modifying the `Custom Position` property value.
4. Save the scene. This should result in a change like the following:
    ```diff
    diff --git a/test/demo/main.tscn b/test/demo/main.tscn
    index 4b6a1a4..02176fc 100644
    --- a/test/demo/main.tscn
    +++ b/test/demo/main.tscn
    @@ -6,6 +6,10 @@
     script = ExtResource( "1_c326s" )
     
     [node name="Example" type="Example" parent="."]
    +group_subgroup_custom_position = Vector2(10, 10)
     
     [node name="Label" type="Label" parent="Example"]
     offset_left = 194.0
    ```
5. Close the editor.
6. Delete the extension (either the `res://example.gdextension` file or the native library).
7. Open the main scene again in the Godot editor.
8. Save the scene. Now, this should result in a change like the following (even if you didn't modify anything yourself):
    ```diff
    diff --git a/test/demo/main.tscn b/test/demo/main.tscn
    index 4b6a1a4..33f8ab0 100644
    --- a/test/demo/main.tscn
    +++ b/test/demo/main.tscn
    @@ -5,7 +5,10 @@
     [node name="Node" type="Node"]
     script = ExtResource( "1_c326s" )
     
    -[node name="Example" type="Example" parent="."]
    +[node name="Example" type="Node" parent="."]
    -group_subgroup_custom_position = Vector2(10, 10)
     
     [node name="Label" type="Label" parent="Example"]
     offset_left = 194.0
    @@ -23,5 +26,3 @@ text = "Click me!"
     __meta__ = {
     "_edit_use_anchors_": false
     }
    -
    -[connection signal="custom_signal" from="Example" to="." method="_on_Example_custom_signal"]
    ```

As you can see, we lost the type of the node (changed from `Example` to `Node`), the modified value of the `group_subgroup_custom_position` property, and a connection to a signal from that node.

This data is not recoverable. Even if you build the extension and open the scene again, it's too late.

### Minimal reproduction project

[godot-cpp demo example](https://github.com/godotengine/godot-cpp/tree/a2633446536cb3ec9e9b3cb67bc67fa478557752/test)

**Comment by akien-mga** [comment]
Should be fixed by #57427.
