### ISSUE TITLE
Reset property value icon's incorrect position

### ISSUE THREAD

**Issue by Kay-Eth** [godotengine/godot#57439]
### Godot version

4.0.alpha1

### System information

Windows 11, Vulkan, NVIDIA GeForce RTX 2070 SUPER (511.23)

### Issue description

Reset icon next to property value field is placed incorrectly for any properties that are on a "second level" of property list.
![image](https://user-images.githubusercontent.com/46926490/151695582-487e0096-d7a6-4bd1-b8db-076d0af74560.png)

### Steps to reproduce

Look at issue description.

**Comment by IgorKordiukiewicz** [comment]
It seems to be fixed already
![godot windows tools 32_ZXZMswGFGU](https://user-images.githubusercontent.com/25117425/154777153-918498d8-226f-42ec-82e7-7246d0f68f06.png)

**Comment by akien-mga** [comment]
Fixed by https://github.com/godotengine/godot/pull/58125.
