### ISSUE TITLE
get_node autocomplete doesn't work if the scene is not the focused tab

### ISSUE THREAD

**Issue by Rodeo-McCabe** [godotengine/godot#57433]
### Godot version

3.4.2

### System information

Linux

### Issue description

When using `get_node()` or `$`, if the scene the script is attached to is not the focused tab in the editor, node path completions do not appear. 

### Steps to reproduce

Make 2 scenes. First has a script and some child nodes. Second is empty (actually it doesn't matter what nodes it has).

Open the script on First, then open/focus Second

Attempt to use `get_node` or `$` in first.gd.

```
# first.gd
extends Node2D

# No path completion if First.tscn is closed or not the focused tab
onready var child = $ ...

func my_func(param):
	get_node( ... # no completion here either
```

### Minimal reproduction project

Can provide if really necessary.

**Comment by TheDuriel** [comment]
I suppose the editor could loop through all open scenes, try to find a node the script is used in, and then give suggestions from there. But that means getting autocomplete from different scenes bundled together if you are using the script in multiple. Which is, in my opinion, worse than getting no suggestions.

**Comment by Rodeo-McCabe** [comment]
If this is the desired behavior, this issue can be closed. I just didn't find any other reports of it.
