### ISSUE TITLE
Unicode code point above FFFF not correctly handled

### ISSUE THREAD

**Issue by lucassardois** [godotengine/godot#57438]
### Godot version

Godot Engine v3.4.2 stable 

### System information

Linux, Fedora 34, OpenGL ES 3.0 Renderer: Mesa Intel(R) UHD Graphics 620 (KBL GT2)

### Issue description

Godot doesn't correctly handle unicode code point above FFFF. For instance ⚫, code point: U+26AB works while 🟢, code point: U+1F7E2 doesn't and get transformed into something else.

### Steps to reproduce

The minimal reproduction code is the following:
```
func _ready():
    var works = "\u26AB"
    var bug = "\u1F7E2"
    OS.clipboard = works + " " + bug
```

Produce:
⚫ ὾2

### Minimal reproduction project

[bug-report.zip](https://github.com/godotengine/godot/files/7965680/bug-report.zip)

**Comment by bruvzg** [comment]
Also, relevant for `4.0`, as a workaround you can use:

```gdscript
func _ready():
	var works = "\u26AB"
	var bug = char(0x1F7E2)
	OS.clipboard = works + " " + bug
```
