### ISSUE TITLE
Tabs and White Spaces do not align in Text Editor for some Font sizes

### ISSUE THREAD

**Issue by Sauermann** [godotengine/godot#57441]
### Godot version

v4.0.alpha.custom_build [e4265e86c]

### System information

Debian 11, Vulkan

### Issue description

In the text editor tabs are usually displayed with a width of 4 white spaces.
Depending on the font size, tabs are displayed with a different width.

Example for Code Font Size 16 where the numbers should match in each column:
![image](https://user-images.githubusercontent.com/6299227/151696868-05763079-1844-402a-a597-497a7bfde920.png)

I would expect that for all font sizes, tabs should have the same width as 4 white spaces.

### Steps to reproduce

1. Load minimal reproduction project
2. Open Node.gd in Text editor
3. Change Font Size with Ctrl-Mousewheel

### Minimal reproduction project

[TabWidth.zip](https://github.com/godotengine/godot/files/7965758/TabWidth.zip)

**Comment by Calinou** [comment]
@Sauermann Can you reproduce this in 3.4.2 (which uses a different script editor implementation under the hood)?

**Comment by Sauermann** [comment]
I am unable to reproduce this issue in v3.4.2.stable.official [45eaa2daf].

**Comment by KoBeWi** [comment]
Can't reproduce in alpha 6
@Sauermann Can you test?

**Comment by Sauermann** [comment]
Between alpha 2 and alpha 3 this issue was resolved.
Closing this accordingly.
