### ISSUE TITLE
Signal 'files_dropped' doesn't get emitted

### ISSUE THREAD

**Issue by lapspider45** [godotengine/godot#57442]
### Godot version

v4.0.alpha1.official.31a7ddbf8

### System information

Linux 5.15.16-1-MANJARO x86_64

### Issue description

When files are dropped onto a running project, the `get_tree().files_dropped` signal doesn't get emitted. This was working in 3.4.

### Steps to reproduce

1. Run the MRP
2. Drop any file(s) onto the window
3. Nothing happens. (expected: prints a list of the files)

### Minimal reproduction project

```
# main.gd
extends Control

func _ready():
	get_tree().files_dropped.connect(Callable(self, &"on_files_dropped"))

func on_files_dropped(files:PackedStringArray, _screen:int):
	print(files)
```
[MRP_files_dropped.zip](https://github.com/godotengine/godot/files/7965797/MRP_files_dropped.zip)

**Comment by jmb462** [comment]
```# main.gd
extends Control

func _ready():
	get_tree().get_root().connect("files_dropped", on_files_dropped)

func on_files_dropped(files:PackedStringArray, _screen:int):
	print(files)
```

Connecting this way works for me.

**Comment by IgorKordiukiewicz** [comment]
It works with:
`get_tree().get_root().files_dropped.connect(Callable(self, &"on_files_dropped"))`
In 3.4 the `drop_files()` function was in the `SceneTree` class, but in 4.0 it is in the `Window` class (`_window_drop_files()`).
So perhaps the `files_dropped` signal should get removed from the `SceneTree` or `SceneTree` should connect to the `Window`'s `files_dropped` signal and also emit it?

**Comment by lapspider45** [comment]
Indeed, that seems to work. It's confusing that there is still a `files_dropped` signal in `SceneTree`.
IMO it should be completely removed in favor of `Window.files_dropped`.
