### ISSUE TITLE
RichTextLabel: Fit Content Height Property not working (Godot 4.0)

### ISSUE THREAD

**Issue by INdIEDeV016** [godotengine/godot#57444]
### Godot version

v4.0.alpha.custom_build [30701e396]

### System information

Windows 10, Vulkan Clustered, NVIDIA GeForce GT 1030

### Issue description

RichTextLabel's `fit_content_height` is not working!

As expected from earlier versions of Godot (Godot 3.x), the `fit_content_height` property should not clip the text and the whole text should be visible (by setting the `rect_min_size` of the RichTextLabel to fit the content), and even if the property is turned OFF, then atleast a scroll_bar should be visible.

### Steps to reproduce

Just add a RichTextLabel in the scene and set `fit_content_height` to true.
Scale the RichTextLabel and observe that no ScrollBar appears and the content still clips off

**Comment by KoBeWi** [comment]
This should've been fixed in #57304
Try updaing your build.

**Comment by INdIEDeV016** [comment]
> This should've been fixed in #57304 Try updaing your build.

Yes, it looks fixed in recent versions. Thank You for the help

This issue can be safely closed.
