### ISSUE TITLE
GDScript 2.0: Crash when calling a function that doesn't exist on a node

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot#57448]
### Godot version

4.0 alpha 1

### System information

Linux Manjaro, Vulkan, Intel Kaby Lake

### Issue description

I ran into a complete crash (it took down both the running instance AND the editor). The only thing that the terminal showed was `free() invalid pointer` The crash was repeatable, and only once I was able to see the editor +debugger show me that it had something to do with something with 'distance' in the name.

I figured out, by trial and error, that it was crashing because I am calling a function that doesn't exist in another node. Or maybe because the debugger tries to show something it doesn't like (I've had it barf completely on trying to debug the list of signal connections)

### Steps to reproduce

Open the attached project (for some reason, maybe caches, opening the project twice may be needed to get rid of some load errors)

Delete the sort_intersections_distance function in map_loaded.gd, try to run map_loaded.tscn.

### Minimal reproduction project

Not minimal, sorry :(

https://github.com/Zireael07/FreeRoamRoguelikeRacerPrototype/commit/b621d4696c22ae7d61f79d56fd7253cfaa5004f1

**Comment by Zireael07** [comment]
Had the same thing happen again, with a different script. It's definitely because of the function not existing (I was able to see "Invalid call" for a fraction of a second before everything crashed again, and again, adding the missing function fixed the issue.

More worryingly, in one case it was because I used a wrong String constructor - it wasn't caught by the editor before the run.

Tagging @vnen as it seems GDScript 2.0 has a serious usability/stability problem.

**Comment by Zireael07** [comment]
Note: I might be able to get a debug build of alpha1 after work BUT I don't even know where to start with debugging this, as everything crashes :/

**Comment by Zireael07** [comment]
Good news - I can't get it to crash anymore with alpha2.

Bad news - the debugger still closes very fast so figuring out the actual problem would be next to impossible (especially since this 'invalid call' doesn't show in the output log)

Based on the fact that I'm seeing the same behavior if I put a breakpoint in some scripts... thinking it's related to #56916 or to that other issue where editor/debugger can't handle some Dictionaries.

**Comment by akien-mga** [comment]
Can you still reproduce it in the latest version?

**Comment by Zireael07** [comment]
Don't think so, will reopen if it reoccurs
