### ISSUE TITLE
Some Integer Rect2i calculations are incorrect

### ISSUE THREAD

**Issue by Sauermann** [godotengine/godot#57468]
### Godot version

v4.0.alpha.custom_build [78e3e65e7]

### System information

Debian 11, Vulkan

### Issue description

Rect2i makes some calculation based on floating arithmetic, which do not correctly apply to the integer case.

1. During the calculation of the intersection of the blue (0,0)-(1,1) and red (2,2)-(3,3) rectangle according to the following diagram with Rect2i (integer version) there are inconsistencies.

![rect2i](https://user-images.githubusercontent.com/6299227/151723318-663b6e62-0dc2-42a4-8b30-243129e11c3d.png)

I would expect that the two rectangles do not intersect.

2. A Rect2i should enclose itself

3. Expanding to the positive side does not work

The following code tests this:
```
func _ready():
	var a1 = Rect2i(0, 0, 2, 2)
	var a2 = Rect2i(2, 2, 2, 2)
	print(a1.intersects(a2))
	print(a1.expand(Vector2i(2,2)).has_point(Vector2i(2,2)))
	print(a1.encloses(a1))
```
The code outputs the following result:
```
true
false
false
```

I would expect the following output:
```
false
true
true
```

### Steps to reproduce

Load and run the Minimal reproduction project

### Minimal reproduction project

[Rect2iCalculations.zip](https://github.com/godotengine/godot/files/7968949/Rect2iCalculations.zip)

**Comment by groud** [comment]
Most of those are expected results. The Rect2i does not include its right and bottom borders as within the rectangle.
- a1 and a2 are next to each other, it's normal they don't intersect as their border is not considering as belonging to both rectangle.
- same here, right and bottom border points are not considered as belonging to the rectangle itself.
- i think however that a1 should enclose itself, in such case the fact that `a1.encloses(a1)` returns false looks like a bug.

**Comment by Sauermann** [comment]
> a1 and a2 are next to each other, it's normal they don't intersect as their border is not considering as belonging to both rectangle.

I agree and current behavior is, that a1 and a2 are treated as if they do intersect (`a1.intersects(a2)` -> true), which should be corrected.

> same here, right and bottom border points are not considered as belonging to the rectangle itself.

Since `Vector2i(2,2)` lies on the right and bottom border of `a1`, it does not belong to `a1`. `expand` should return an enlarged Rect2i, so that `Vector2i(2,2)` belongs to the new Rect2i.

`expand` has the following documentation:
https://github.com/godotengine/godot/blob/837e6bdf1859d2054b31730fb71c636f681300da/doc/classes/Rect2i.xml#L73

I would interpret "include" as a synonym for the function `has_point()`.

The following comparison shows this inconsistency:
`a1.expand(Vector2i(2,2)).has_point(Vector2i(2,2))` -> false
`a1.expand(Vector2i(-1,-1)).has_point(Vector2i(-1,-1))` -> true

My suggestion would be to change `expand`, so that it works in a consistent way on all sides.

**Comment by akien-mga** [comment]
I'm a bit concerned by the OP here, the diagram with blue and red rectangles and the given code snippet with `(2, 2)` sizes don't match. I'm afraid that an error in visualization of the data we're talking about doesn't help discussing what should be done at boundaries.

Here's what those two rectangles look like when drawn (factor 100 applied so that it's easier to see):

```gdscript
extends Control

func _draw():
	var a1 = Rect2i(0, 0, 200, 200)
	var a2 = Rect2i(200, 200, 200, 200)
	
	draw_rect(a1, Color.BLUE)
	draw_rect(a2, Color.RED)
```

![image](https://user-images.githubusercontent.com/4701338/151814203-d9ef1b8c-d09d-48a3-bf56-958b04f6263f.png)

As expected, a Rectangle with size (200, 200) starting at (0, 0) will span all the way to the point (200, 200). By convention, it will however not consider points on its right and bottom border as enclosed - so there's no overlap with rectangles starting at (200, 0), (200, 200) or (0, 200).

**Comment by groud** [comment]
> I agree and current behavior is, that a1 and a2 are treated as if they do intersect (a1.intersects(a2) -> true), which should be corrected.

Ah yeah, I agree. Intersect should be corrected so that two rectangles next to each other should not be considered as intersecting.

> Since Vector2i(2,2) lies on the right and bottom border of a1, it does not belong to a1. expand should return an enlarged Rect2i, so that Vector2i(2,2) belongs to the new Rect2i.

I kind of disagree on that, but I agree the documentation is a little bit misleading. For example, if you have a Rectangle defined as `var rect = Rect2i(0, 0, 1, 1)` (Rectangle at position (0,0) and size (1,1)). Then I think that using `rect.expand_to(Vector2i(10,10))` should return a rectangle of size (10, 10), not a rectangle of size (11,11).

I think it is more consistent the way it is right now, but that might be wrong. I think this might depend on the use cases.

**Comment by Sauermann** [comment]
Apologies for my visualization - you are right, that it can be interpreted in a way that was different from my intention.

Please let me correct this
![image](https://user-images.githubusercontent.com/6299227/151815839-65985d13-a284-4a54-8927-73ab1276cd37.png)
The blue rectangle is represented by `var a1 = Rect2i(0, 0, 2, 2)`
The red rectangle is represented by `var a3 = Rect2i(2, 2, 2, 2)`

As for the documentation, the current behavior of `enlarge`can be described as: "Returns a copy of this [Rect2i] expanded, so that the given point lies within or on the right border or on the bottom border of the new [Rect2i]."

**Comment by Sauermann** [comment]
Here is an additional scenario, where I find the current behavior of `expand` inconsistent.

![image](https://user-images.githubusercontent.com/6299227/151832393-b50a09ce-c3b9-4a0b-875f-a042938fc619.png)

The blue dot is represented by `var v1 = Vector2i(0, 0)`
The red dot is represented by `var v2 = Vector2i(2, 2)`

These dots can also be represented by Rect2i's:
The blue dot is represented by `var a1 = Rect2i(v1, Vector2i(1, 1))`
The red dot is represented by `var a2 = Rect2i(v2, Vector2i(1, 1))`

```
a1.expand(v2) = Rect2i(0, 0, 2, 2)
a2.expand(v1) = Rect2i(0, 0, 3, 3)
```

Depending on the order of v1 and v2, I get different results.

This problem does not occur for float numbers, because the size of a single point is 0.

On the other hand there is `merge`, which provides consistent behavior, so there is at least a workaround:
```
a1.merge(a2) = Rect2i(0, 0, 3, 3)
a2.merge(a1) = Rect2i(0, 0, 3, 3)
```

**Comment by akien-mga** [comment]
> These dots can also be represented by Rect2i's:

I think that's an invalid assumption/representation. Points have no area, they cannot be represented by a rectangle of 1x1 dimension. If you want to represent the blue and red dots as Rect2i's, then it would be Rect2i's with no area:

```gdscript
func _ready():
	var v1 = Vector2i(0, 0)
	var v2 = Vector2i(2, 2)
	
	var a1 = Rect2i(v1, Vector2i(0, 0))
	var a2 = Rect2i(v2, Vector2i(0, 0))

	print(a1.expand(v2) == Rect2i(0, 0, 2, 2)) # true
	print(a2.expand(v1) == Rect2i(0, 0, 2, 2)) # true
```

**Comment by Sauermann** [comment]
```
func _ready():
	var v1 = Vector2i(0, 0)
	var a1 = Rect2i(v1, Vector2i(0, 0))
	print (a1.has_point(Vector2i(0, 0))) # false
```
As seen in this example, a1 does not contain the point Vector2i(0,0). The definition of `has_point` forces me to use Rect2i(Vector2i(0, 0), Vector2i(1, 1)) as a representation of the single point Vector2i(0, 0).

Thanks to your explanation, now I see that there are two different views on Rect2i:
- Rect2i denotes an rectangular area of integer-coordinates (the prevalent interpretation)
- Rect2i denotes a set of discrete integer-coordinates in rectangular form (my interpretation)

I will try to wrap my head around it.

**Comment by lawnjelly** [comment]
> I will try to wrap my head around it.

This is why off-by-one errors are one of the most popular errors. :grin: :popcorn:
