### ISSUE TITLE
Disabling internal toast notifications also stops logging to terminal

### ISSUE THREAD

**Issue by Amatrelan** [godotengine/godot#57461]
### Godot version

v4.0.alpha.custom_build [b5c018479]

### System information

Linux, x11, nvidia

### Issue description

Disabling internal errors as toast notifications also disables terminal logging completely.

### Steps to reproduce

Editor -> Editor Settings -> Interface -> Editor -> Show Internal Errors As Toast Notifications to false.

And there is no longer in error messages in terminal where Godot is run, and this is not expected behavior.

**Comment by Calinou** [comment]
cc @groud

**Comment by KoBeWi** [comment]
Can't reproduce in 5636903
@Amatrelan If you can still reproduce this in the newest alpha, more detailed steps would be useful.

**Comment by Amatrelan** [comment]
Ah seems to be fixed now, thanks!
