### ISSUE TITLE
Tree's Row select mode also selects all the individual columns of a TreeItem

### ISSUE THREAD

**Issue by LikeLakers2** [godotengine/godot#57465]
### Godot version

v4.0.alpha.calinou [b25c7fef0]

### System information

Windows 10 21H2; Vulkan Clustered, GTX 1060 6GB, Driver version 456.71

### Issue description

(Note: The images below will be using the Godot 3 theme, as I feel it shows the issue a little more clearly, but the issue occurs on the new Godot 4 theme as well.)

When using the Row select mode in the Tree node, the Tree also draws selection boxes around all of the columns in that row:

![image](https://user-images.githubusercontent.com/1008889/151716890-d50e63ea-d3a0-4aa4-90e3-c03e38eeb5ba.png)

This makes the Row selection look rather ugly. In an attempt to work around this, I tried setting all of the TreeItem's columns to be unselectable, but found myself unable to select the row. I found that the only way to make the row selectable is to set column 0 to selectable:

![image](https://user-images.githubusercontent.com/1008889/151716880-517a12d2-fec0-437d-86e3-b17bae7e0212.png)

...which still incurs the problem of an additional selection box appearing around column 0. Additionally, I now need to click column 0 (not other columns) in order to select the row; and the text in the unselectable columns is not lightened up, as would normally happen when they're selected.

I would expect the Row selection mode to work as follows:
* Selecting any column in a row, whether that column is selectable or not, selects the entire row.
* A selection box is only drawn around the entire row, and not around the individual columns too.
* Column 0 should not need to be selectable for the entire row to be selected.

But instead it works as follows:
* Selecting any *selectable* column selects the entire row. Selecting an unselectable item does not select the row.
* A selection box is drawn around the entire row, and around the individual columns too.
* Column 0 needs to be selectable for the entire row to be selected. Otherwise, only the selectable columns will be selected.

### Steps to reproduce

1. Create a Tree node, and set its Select Mode to Row.
2. (Optional, but helps the issue to be seen) Give the Tree multiple columns.
3. Add some TreeItems to the Tree.
4. Run the scene, and note that selecting a row will select all the individual columns of that row, rather than just the row.

In the details box below is a pre-made script that will set up the scene for you if attached to a Tree node:
<details>
<summary>tree.gd</summary>

```gdscript
extends Tree

func _ready():
	# Optional, but makes this look nice
	self.column_titles_visible = true
	self.hide_root = true
	self.select_mode = Tree.SELECT_ROW
	
	# Set up the columns
	self.columns = 4
	# Column 1
	self.set_column_expand(0, false)
	self.set_column_title(0, "")
	# Column 2
	self.set_column_expand(1, false)
	self.set_column_title(1, "Date")
	# Column 3
	self.set_column_expand(2, false)
	self.set_column_title(2, "Change")
	# Column 4
	self.set_column_title(3, "Reason")
	
	var root = self.create_item()
	
	for i in range(5):
		var item = root.create_child()
		# Column 1
		#item.set_selectable(0, false)
		item.set_text(0, str(i+1))
		# Column 2
		#item.set_selectable(1, false)
		item.set_text(1, str(randf()))
		# Column 3
		#item.set_selectable(2, false)
		item.set_text(2, str(randi() - randi()))
		# Column 4
		#item.set_selectable(3, false)
		item.set_text(3, "Some reason")
```
</details>

### Minimal reproduction project

[godot tree issues.zip](https://github.com/godotengine/godot/files/7966904/godot.tree.issues.zip)

**Comment by Calinou** [comment]
> Column 0 should not need to be selectable for the entire row to be selected.

In this case, how can individual rows be made non-selectable?

**Comment by LikeLakers2** [comment]
> In this case, how can individual rows be made non-selectable?

By separating the row's selectability from column 0's selectability. The two should not be tied anyways, as the developer would expect to be able to set column 0 to unselectable while still allowing the row to be selectable.

**Comment by akien-mga** [comment]
I think you can file a new issue for this in the `godot` repo. I'd tag it `enhancement` but I think it's simple / consensual enough not to require a dedicated proposal, it's just a tiny adjustment to make to existing logic.
