### ISSUE TITLE
`CharacterBody2D.GetSlideCollision()` causes memory leak

### ISSUE THREAD

**Issue by markdibarry** [godotengine/godot#57470]
### Godot version

4.0 alpha1

### System information

Windows 10

### Issue description

When calling `GetSlideCollision()` on a CharacterBody2D, object count will rise, and never free. Garbage Collection does not free it.

### Steps to reproduce

Create CharacterBody2D.
Call `GetSlideCollision()`

### Minimal reproduction project

[Min.zip](https://github.com/godotengine/godot/files/7967377/Min.zip)

**Comment by IgorKordiukiewicz** [comment]
Duplicate: #57073
