### ISSUE TITLE
stepify() is missing or not working

### ISSUE THREAD

**Issue by ryanscottcausecast** [godotengine/godot#57474]
### Godot version

4.0 alpha

### System information

mac 

### Issue description

stepify seems to be missing

### Steps to reproduce

<img width="583" alt="Screen Shot 2022-01-30 at 9 08 07 PM" src="https://user-images.githubusercontent.com/24243219/151734715-0815f64e-4ada-4c9b-8f32-8594439b8e2b.png">

stepify is not found

**Comment by fire** [comment]
The method was renamed. I’m not at computer right now. So will have to link the docs later.

**Comment by fire** [comment]
https://docs.godotengine.org/en/latest/classes/class_%40globalscope.html#class-globalscope-method-step-decimals

**Comment by Chaosus** [comment]
Yes, this is renamed to `snapped`. This is intended and not a bug. Closed.
