### ISSUE TITLE
Weird issues with ParticlesMaterial colour ramp assignments?

### ISSUE THREAD

**Issue by vpellen** [godotengine/godot#57471]
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

v4.0.alpha1.official [31a7ddbf8]

### System information

Windows 10, Vulkan Clustered, NVidia 1050ti

### Issue description

Who likes Rabbit Holes?

The initial problem was simple - I was toying with the alpha's new particle systems, and I noticed that color ramps weren't working for GPU Particles. After a bit of experimentation, I figured out that re-opening the scene fixed this.

So initially I started trying to figure out the exact source of this. I noticed that if you had a functioning gradient texture, you could screw with the gradient and it'd be fine. If you deleted the gradient and then reloaded the scene, new gradients would again be broken. If you deleted the gradient texture itself, it would also break things.

Things started to get weird once I got the bright idea of creating an external GradientTexture1D resource and assigning it directly to the ParticlesMaterial. Creating the texture and assigning it before setting the gradient didn't work. But setting the gradient and _then_ assigning the texture, _did_ work. However, modifying the gradient on the external texture away from the default, _then_ reloading the scene, gave me a corrupted scene error. But I could still open the scene, it just didn't work on startup. Until I randomly deleted the texture file, then the scene refused to open and I couldn't even change the separate particlesmaterial that I'd also set up.

The exact order of the various things I tried has gotten a bit muddy, and I lack sufficient knowledge of the underlying architecture to posit anything other than "things regarding particle material color ramps are kind of screwy and somebody should probably look into that". I have no idea if the issue is in the particles, the textures, or the gradients themselves. But considering this has the potential to corrupt scenes, it might be worth looking into.

### Steps to reproduce

1. Create a new project.
2. Create a new scene.
3. Add a GPUParticles2D node to the scene.
4. Create a new ParticlesMaterial and assign it to the GPUParticles2D node.
5. Through the ParticlesMaterial, create a new GradientTexture1D for either the Color Ramp or Color Initial Ramp property.
6. Through the ParticlesMaterial, create a new Gradient for the GradientTexture1D you just created.
7. Observe that the particle's colors do not change.

### Minimal reproduction project

Not really applicable given that reloading the project often fixes things.

**Comment by Calinou** [comment]
This reminds me of https://github.com/godotengine/godot/issues/42821, which was recently fixed.

**Comment by Jimmio92** [comment]
Having the same issue with GPUParticles3D; color ramp is ignored at best, at worst it crashed once.

**Comment by Chevifier** [comment]
Can Confirm Issue still exist on Linux as well Ubuntu 22.04 LTS

**Comment by dmaz** [comment]
not just color ramps but just using color shows the same issue... just switching scenes seemed to clear it up for me.  before the switch stderr gets
`ERROR: Uniforms were never supplied for set (3) at the time of drawing, which are required by the pipeline
   at: (drivers\vulkan\rendering_device_vulkan.cpp:7716)`  
 - 80193260ff master on windows

**Comment by clayjohn** [comment]
I can't reproduce this issue using Beta8. Can anyone who previously reproduced this issue still reproduce it?

**Comment by firebelley** [comment]
I am currently experiencing this issue:
![image](https://user-images.githubusercontent.com/4622925/213029449-f238e61e-e6d6-4f53-838f-ab7c378d26ce.png)

Interestingly, it only happens when using the "Sphere" emission shape. If I switch to "Sphere Surface" it works as expected. Let me know if I can help provide any more information.

**Comment by firebelley** [comment]
@clayjohn I would but I unfortunately have not been able to figure out how to reproduce the issue. Usually I just notice that my particles are suddenly white. Will update this issue if I figure it out.

**Comment by KoBeWi** [comment]
I think I'm having this issue or some variation of it. I keep getting error that prints the whole shader code i.e. (snippet)
```GLSL
--Main Shader--
    1 | // NOTE: Shader automatically converted from Godot Engine 4.0.2.rc1's ParticleProcessMaterial.
    2 |
...
  173 | 			vec4(-0.328, 0.035,  0.292, 0.0),
  174 | 			vec4(1.250, -1.050, -0.203, 0.0),
  175 | 			vec4(0.000, 0.000, 0.000, 0.0)) * hue_rot_s;
E 176-> 	COLOR = hue_rot_mat * textureLod(color_ramp, vec2(tv, 0.0), 0.0) * color_value;
  177 | 
  178 | 	if (length(VELOCITY) > 0.0) {
  179 | 		TRANSFORM[1].xyz = normalize(VELOCITY);
...
```
and error
```
Unknown identifier in expression: 'color_ramp'.
```
At first I thought something is wrong with one of my custom particle shaders, but today I upgraded to 4.0.2 rc and the error above displays 4.0.2 rc as you can see, which means it can't be my shader, because it was just generated. Which means it's a shader from a vanilla ParticleProcessMaterial.

Something is wrong. I didn't test much, but it might be reproducible with newly created materials with color ramps 1D.

**Comment by IcyChills** [comment]
Happening on my side as well with Godot v4.0.2.stable.mono.official [7a0977ce2]. Using GPUParticles3D. It's strange as it did work the other day on the same version.

**Comment by IcyChills** [comment]
Fixed my issue by enabling Use as Albedo under the Vertex Color from Material Overlay.

**Comment by firebelley** [comment]
I may have found a clue related to this issue. As of 4.0.3.stable, it looks like color initial ramp was previously being incorrectly set as `GradientTexture2D` when it should have been `GradientTexture1D`. When I open an old particle process material with an initial color ramp, I see this error in the output:
```
Failed to set a resource of the type 'GradientTexture2D' because this EditorResourcePicker only accepts 'GradientTexture1D' and its derivatives.
```
Additionally, version control shows that the resource was indeed saved as a GradientTexture2D in the scene file previously (left is old, right is new): 
![image](https://github.com/godotengine/godot/assets/4622925/b7e846ea-a7e7-42da-b3f1-a2fb74c70fb9)

I don't see the white particles that I mentioned previously in the editor, but they are unfortunately still being rendered as white in-game:

![image](https://github.com/godotengine/godot/assets/4622925/407f3fce-3e3b-43a0-85db-4c76e881e65e)

The white blob above is supposed to be red as shown here: 
![image](https://github.com/godotengine/godot/assets/4622925/c7108b3e-1b16-4ce5-b8d9-3ad5de0c0aaa)

The particles render as white for both Forward+ and Compatibility render modes.

Apologies if none of this is helpful/irrelevant, but figured I'd post in case it's useful information. I still haven't been able to identify the exact conditions that cause this to happen.

**Comment by vpellen** [comment]
Checking in on old bugs - since originally making this, various changes have happened to the structure of particle systems. Either as an incidental result of refactoring or an explicit fix, I can no longer reproduce the issue as of 4.3 dev 4, so I'm going to assume it got fixed.

**Comment by Lawrenceku** [comment]
> Fixed my issue by enabling Use as Albedo under the Vertex Color from Material Overlay.

This works fine for just the "color" but not the "emission color"
