### ISSUE TITLE
New in-editor error popups can extend off-screen

### ISSUE THREAD

**Issue by snailrhymer** [godotengine/godot#57472]
### Godot version

v4.0.alpha.custom_build [78e3e65e7]

### System information

Windows 10

### Issue description

The new error popups don't wrap text or otherwise handle longer text, so they can extend off-screen:

![image](https://user-images.githubusercontent.com/61291296/151729218-f265d9bb-bfd8-4ca2-b367-eefbed18ab3c.png)

Since the errors are left-justified as a block, long errors can push shorter ones off-screen:

![image](https://user-images.githubusercontent.com/61291296/151729315-23b9959a-0469-4919-b4e4-4ce4fbc3ed73.png)

Popups don't seem to have been introduced  in v4.0.alpha1.official [31a7ddbf8], so I haven't been able to reproduce the behaviour there.

**Edit: ** The bug also appears in alpha 1.

### Steps to reproduce

Cause a sufficiently long error message to popup in the editor, e.g. with
```
@tool
extends Node

func _process(delta):
    var a
    a.loooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong_function_name()
```
attached to a node in the scene tree.

**Comment by Calinou** [comment]
> Popups don't seem to have been introduced in v4.0.alpha1.official [31a7ddb], so I haven't been able to reproduce the behaviour there.

Toasts were already implemented in 4.0alpha1, but did you make sure to enable them by clicking the bell icon?

**Comment by snailrhymer** [comment]
Okay, confirmed that the toasts go off-screen in alpha 1 too.

> enable them by clicking the bell icon

In alpha 1, this didn't enable them for me ( the same as #56550). It looks like the default behaviour for `show_internal_errors_in_toast_notifications` is `Auto`. In alpha 1, auto disabled them; in the custom build, it enabled them, I think [due to them being official and development, respectively](https://github.com/godotengine/godot/pull/52940#issuecomment-962645679).

**Comment by akien-mga** [comment]
> In alpha 1, this didn't enable them for me ( the same as #56550). It looks like the default behaviour for `show_internal_errors_in_toast_notifications` is `Auto`. In alpha 1, auto disabled them; in the custom build, it enabled them, I think [due to them being official and development, respectively](https://github.com/godotengine/godot/pull/52940#issuecomment-962645679).

See https://github.com/godotengine/godot/issues/56550#issuecomment-1026135966

**Comment by reduz** [comment]
@groud can you implement some EDITOR_DEF for the label maximum width?

**Comment by akien-mga** [comment]
It probably doesn't need to be a setting, just a percentage of the available window width.
