### ISSUE TITLE
Code improvement: Grep Search / Editor Improvements

### ISSUE THREAD

**Issue by gregoryfein** [godotengine/godot#5747]
Hey all, love the engine.  But, I've been having to use other software while using Godot to do things that i am accustomed to doing in other IDEs (IntelliJ, Eclipse, XCode, etc.)  

One of the biggest ones has been "Find Occurences".  I've been using Grep to find all occurrences of a code or the uses of a method.  Being able to quickly find these sorts of relations in the editor would be fantastic, like right clicking a method/variable and "find all usages".  (I know Godot doesn't have right-click, but you get the idea.)

Another would be multi-pane editing.  Only being able to have one GDScript pane open at a time (instead of side-by-side) cuts down on some productivity.  I have been having to keep a Notepad++/TextMate open at the same time with multiple scripts to look at them side-by-side.  

Additionally, the quick open (ctrl + shit + o) is great for Scenes, but it would be nice if it could search for file names of GDScripts as well.

Thanks for all you do, guys.  You're amazing.

For mods: tags to use on this post are probably  "feature proposal", "topic:gdscript", "topic:editor"

**Comment by akien-mga** [comment]
Please avoid opening a single issue for different topics, it makes it hard to discuss and fix the single points.

For an overview of all such proposed improvements, see #2982.

> Additionally, the quick open (ctrl + shit + o) is great for Scenes, but it would be nice if it could search for file names of GDScripts as well.

This is implemented already, via "Quick Open Script" / <kbd>Ctrl+Alt+O</kbd>.

**Comment by gregoryfein** [comment]
I didn't know about that command!  Good to know. :)

I'll add future notes to the thread you posted and close this one, thanks.
