### ISSUE TITLE
4.0-Alpha1-A signal can trigger a connected function, but not an await coroutine

### ISSUE THREAD

**Issue by AttackButton** [godotengine/godot#57499]
### Godot version

4.0-alpha1

### System information

Windows 8 and 10

### Issue description

I don't know if it is only with the `ready signal` when you use `add_child`, but an `await` coroutine is not working as expected, even with that same `ready signal` being capable of calling a connected function.

In the code below (mrp), `add_new_child()` is a `coroutine`, but 1 and 2 will never be printed, but the function `test_func` will be correctly called:

```
extends Node2D

func _ready():
	await add_new_child()
	print("2")
	

func add_new_child() -> void:
	var b = preload("res://b.tscn").instantiate()
	b.ready.connect(test_func) # <-- connecting the ready signal
	add_child(b)
	await b.ready
	print("1")


func test_func() -> void:
	print("test func")
```

### Steps to reproduce

Create a script with an await coroutine with a signal, connect this same signal to a function, see that only the connected function will work.

### Minimal reproduction project

[await_add_child_issue.zip](https://github.com/godotengine/godot/files/7975762/await_add_child_issue.zip)

**Comment by akien-mga** [comment]
The problem is that your `await b.ready` awaits a signal which has already been emitted. Your `b` instance is `ready` right after you add it to the scene tree with `add_child(b)`. If you comment it out, the order of prints makes it clear:
```
B scene
test func
1
2
```

"test func" is printed before "1" because the node is ready right after it enters the scene tree.

**Comment by AttackButton** [comment]
Yeah, I was trying to use the await for this, maybe connecting the function is a better solution for now.
