### ISSUE TITLE
Fix up Android OpenXR support

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#57498]
### Godot version

4.0.dev

### System information

Android

### Issue description

Mostly recording this as a tracking issue for @m4gr3d . 

In PR https://github.com/godotengine/godot/pull/56394 we are adding OpenXR support to Godot. One missing part here is completing the implementation for Android. Due to the nature of Godot in the core we are going to support Khronos' official OpenXR loader which has already been included in the 3rd party folder. Most of the code was ported from the original OpenXR Godot 3 plugin but it needs some finishing touches.

There is an issue that Meta currently uses their own proprietary loader though the assumption is that they will switch over to the Khronos one.

### Steps to reproduce

Not applicable

### Minimal reproduction project

Not applicable

**Comment by korompg** [comment]
The finished version the former PR is #64826.

**Comment by m4gr3d** [comment]
Fixed by https://github.com/godotengine/godot/pull/65798
