### ISSUE TITLE
If a resource is used as a key in a dictionary, it will be replaced by null when saving with ResourceSaver to a .tres file

### ISSUE THREAD

**Issue by iamtoaster** [godotengine/godot#57506]
### Godot version

4.0.alpha1

### System information

Windows 10

### Issue description

If you have a custom resource with exported dictionary in it (let's call it ```ResB```), and you use another custom resource as a key on that dictionary (```ResA```), then try to save it in ```.tres``` format, the resource that was used as a dictionary key will not be saved (replaced by a ```null```) and following message will be printed to console:
```E 0:00:00:0707   _ready: Resource was not pre cached for the resource section, bug?
  <Ошибка C++>   Method/function failed. Returning: "null"
  <Исходный код C++>scene/resources/resource_format_text.cpp:1509 @ _write_resource()
  <Трассировка стека>Main.gd:19 @ _ready()
```
I also found that this error only happens when you try to save to a ```.tres``` file. When I tried to save same resource to a binary ```.res``` everything worked as expected with resource being saved. 

Also found that if you use that same resource (```ResA```) for more than as a dictionary key (say, in an exported variable) in the resource being saved (```ResB```) then the bug does not happen either.

### Steps to reproduce

1. Create two custom resources (```ResA``` and ```ResB```)
2. Make sure ```ResB``` has an exported dictionary which uses instances of ```ResA``` as keys.
3. Add at least 1 entry to the dictionary in ```ResB``` that uses an instance of ```ResA``` as a key.
4. Try to save ```ResB``` to a ```.tres``` file using ```ResourceSaver.save("res://data.tres", ResBInstance)```

### Minimal reproduction project

[ResourcesTest.zip](https://github.com/godotengine/godot/files/7977119/ResourcesTest.zip)
Simply run it. ```res://data.tres``` is the buggy output file, ```res://data.res``` is the same resource but in binary format (and also no bug)

**Comment by Bashar-Ahmed** [comment]
If this issue is available, then I would like to attempt this as a first contribution.

**Comment by Anaxan** [comment]
Hello Bashar-Ahmed

If you do decide to look at this would you be able to look at the Visual Script RSCC bug as well ? 

The report above sounds very similar to the bug and I wonder if the two are related.

Very few people use Visual Script so you are probably not aware but there is a serious bug which causes Visual Scripts to corrupt. It is labeled as a high priority bug so if you are able to fix it you would definitely make a name for yourself as a developer.

**Comment by Zireael07** [comment]
The RSCC bug is something that has been annoying people for good reason, but I seriously doubt it's a good idea for a first time contributor.

**Comment by Anaxan** [comment]
More than an annoyance in my opinion. I would make the argument that Godot 4 will succeed or fail on this one issue.

Imagine it is day 1 after Godot 4 is released. It has been marketed as a 3D engine capable of competing with Unreal. Several thousand Unreal Designers check it out. They try out Visual Script as it is similar to Blueprints. They do a small project and are impressed by Godots' capabilities. They think, hey I kind of like this engine. Then they open up their project the next day and their script is gone. 

Indeed, if I was a developer I would not let this issue rest in the hands of a first time contributor. But if Bashar doesn't tackle it, who will ?

**Comment by Calinou** [comment]
@Anaxan Please don't derail other issues that are unrelated to this particular bug.

**Comment by Anaxan** [comment]
I apoligize for any offense I've caused. That wasn't my intention.

**Comment by iamtoaster** [comment]
I just found out this bug is also present on Godot 3.4.2 stable, can be reproduced with the same project (just remove the ```@``` part of ```@export```s and it will work)

**Comment by Bashar-Ahmed** [comment]
As far as I was able to gather the issue, the `path_cache` is NULL when the `ResourceFormatSaverTextInstance::_write_resource` is being called. Is this how it was meant to be?, because the `path_cache` is the path from which the resource is to be loaded. So what does it signify during saving a Resource. To correct this, we can set `path_cache` within the `ResourceFormatSaverTextInstance::save` function, but since the resource passed in the argument is `const` I was unable to figure out a way of doing it. Any potential solutions?

**Comment by Life4gal** [comment]
Hi everyone, I have a PR that solved this problem.

see #64812  :)

**Comment by Life4gal** [comment]
By the way, I came across this issue because of a bug of `RSCC` :)
