### ISSUE TITLE
Confusing error when assigning a value to a Signal ("Invalid set index 'pressed' with value of type 'bool'.")

### ISSUE THREAD

**Issue by BraindeadBZH** [godotengine/godot#57515]
### Godot version

v4.0.alpha1.official [31a7ddbf8]

### System information

Windows 10

### Issue description

GDScript does not know if we are accessing the property pressed or the signal.
Example:
`_validate_sw.pressed = false` gives `Invalid set index 'pressed' (on base: 'CheckButton') with value of type 'bool'.` with `_validate_sw` being a `CheckButton`. `print(_validate_sw.pressed)` produces `CheckButton::[signal]pressed`.

### Steps to reproduce

1. Add a BaseButton based node to your scene
2. Try to access the pressed property as a boolean

**Comment by akien-mga** [comment]
`pressed` is the name of the signal. The property was renamed to `button_pressed` in #57101.

**Comment by BraindeadBZH** [comment]
What confused me also was that the online doc, even in latest, is still mentioning the pressed property.

**Comment by Calinou** [comment]
> What confused me also was that the online doc, even in latest, is still mentioning the pressed property.

The online class reference is only periodically updated, which is why it doesn't follow pull requests that were merged less than 14 days ago or so.

**Comment by YuriSizov** [comment]
This should've been closed. Also trying to assign to a signal should now raise a different error, as you are trying to write to a constant.
