### ISSUE TITLE
tabContainer node : set_ignore_mouse(true) doesnt work with set_tabs_visible(false)

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#5751]
Godot 2.1 beta
Is it possible to disable clicking on tabs of the tabContainer node?
I noticed that even if I hide it's tabs - they are still clickable. That is not how I want to use the container. I want to change tabs only via code

However I found that if you make the tabs invisible with set_tabs_visible(false)
set_ignore_mouse(true) is completely ignored and they are still clickable - even if not visible!

**Comment by blurymind** [comment]
set_ignore_mouse(true) works only if the tabs are visible - which I think is wrong and a bug

**Comment by kbake** [comment]
`set_ignore_mouse` is no longer available (all four remaining references of it are commented out) so the bug is probably not relevant anymore. Issue #7436 covers the initial question of disabling tabs. I think this can be safely closed.

**Comment by kbake** [comment]
`set_ignore_mouse` is no longer available (the few references to it are commented out), seems that another method `set_mouse_filter` has taken its place. I wasn't able to reproduce this issue; hidden tabs do not appear to be clickable regardless of what mouse filtering is being done, if any.

The initial question is covered in issue #7436. I think this is good to close.

**Comment by bojidar-bg** [comment]
Given that nobody commented to the above, I'm closing this issue as fixed by recent changes and turbulence on master. (feel free to comment if this is not the case)
