### ISSUE TITLE
RoomManager merge_meshes option does not respect the mesh's cast_shadow option

### ISSUE THREAD

**Issue by iwilliams** [godotengine/godot#57527]
### Godot version

3.4 stable

### System information

Ubuntu, GTX 1080

### Issue description

When using the `merge_meshes` option on the `RoomManager`, it doesn't respect the `MeshInstance`'s `cast_shadow` option. This results in the merged mesh casting a shadow even when all of the individual instances had that option set to `Off`.

Setting the portal option to `dynamic` excludes these meshes from being merged, but I think it might be more useful and clear to provide an option for leaving a mesh instance out of the merge process. 

Current behavior:
![image](https://user-images.githubusercontent.com/5215799/152035825-07a81a93-f99c-4975-b607-875c55981cf1.png)

Desired behavior:
![image](https://user-images.githubusercontent.com/5215799/152035921-b327fcfd-67e3-4736-8496-0933ce4c5c1c.png)

### Steps to reproduce

Setup a `RoomManager` node and set it's `merge_meshes` option to `true`. Create a room with several `MeshInstances` of the same mesh and set their `cast_shadow` option to `Off`. Run the scene and look for the merged mesh in the remote scene tree. Observe the `cast_shadow` option reset to it's default.

**Comment by lawnjelly** [comment]
> Setting the portal option to dynamic excludes these meshes from being merged, but I think it might be more useful and clear to provide an option for leaving a mesh instance out of the merge process.

Yes this is a good idea I'll have a look at this tomorrow.

It will be good to be able to fix the bug directly and merge similar meshes with the same `cast_shadow` setting and apply this to the merged mesh, but having a better option to omit a mesh from merging I agree would be useful. Setting to `Dynamic` will work as you say, but it's a little more expensive than when it is `Static`. :+1:

**Comment by iwilliams** [comment]
> > Setting the portal option to dynamic excludes these meshes from being merged, but I think it might be more useful and clear to provide an option for leaving a mesh instance out of the merge process.
> 
> Yes this is a good idea I'll have a look at this tomorrow.
> 
> It will be good to be able to fix the bug directly and merge similar meshes with the same `cast_shadow` setting and apply this to the merged mesh, but having a better option to omit a mesh from merging I agree would be useful. Setting to `Dynamic` will work as you say, but it's a little more expensive than when it is `Static`. +1

Thank you! Loving the `merge_meshes` feature and portal system in general!

**Comment by akien-mga** [comment]
Fixed by #57551.
