### ISSUE TITLE
Particles always being culled when using RoomManager portal system

### ISSUE THREAD

**Issue by iwilliams** [godotengine/godot#57528]
### Godot version

3.4

### System information

Ubuntu, GTX 1080

### Issue description

The docs say to set the particle system's `portal_mode` to `Dynamic` and/or up the `extra_cull_margin` on the `GeometryInstance`, but the only way I can get `Particles` to render is by setting their `portal_mode` to `Global`.

### Steps to reproduce

Setup a `RoomManager` and a room. Add a `Particles` node to it and do the basic setup. Try setting the `portal_mode` to `Dynamic` and messing with the `extra_cull_margin`. Observe your scene with no particles.

**Comment by Calinou** [comment]
cc @lawnjelly

**Comment by lawnjelly** [comment]
I will take a look. Particles are quite tricky, because their AABB is not set at the time of conversion, so it is difficult to decide which room to place them in. In the meantime, I think `Roaming` also works.

**Comment by iwilliams** [comment]
> I will take a look. Particles are quite tricky, because their AABB is not set at the time of conversion, so it is difficult to decide which room to place them in. In the meantime, I think `Roaming` also works.

Looks like `Roaming` does work :+1:.

**Comment by akien-mga** [comment]
Fixed by #57546.
