### ISSUE TITLE
GDScript 2.0: Signal functions cannot be used as callables

### ISSUE THREAD

**Issue by Byteron** [godotengine/godot#57523]
### Godot version

4.0.dev

### System information

Windows 11

### Issue description

![image](https://user-images.githubusercontent.com/24433899/152025805-3019c30a-bcff-43c0-ac7a-20794e164aef.png)
when trying to pass in `finished.emit` (which is `Signal.emit`) into a function that expects a `Callable` I get the following errors
![image](https://user-images.githubusercontent.com/24433899/152025963-905733d4-ce9c-461b-8078-60158e4b1f03.png)
since Signal.emit is just another function I would expect to be able to pass this around as callable.
I did verify that the syntax is correct. I can pass other build-in functions, for example here I am passing `Node2D.look_at` and GDScript does not give me any errors. (though I could probably get an error when running, because it expects an argument, but that is not part of this problem)
![image](https://user-images.githubusercontent.com/24433899/152026166-13a80d95-f5b0-448a-a682-7954774df1ba.png)

### Steps to reproduce

1. create some script with a signal
2. try to pass a signal function into as argument into a function that expects a callable
3. error

### Minimal reproduction project

none, as this it probably takes longer to download, unzip and import an MRP than it takes to create a new project and write a script with signal and function.

**Comment by KoBeWi** [comment]
This is because Signal is a non-object type. Same will happen with e.g. Vector2 or Array. But in case of these types, the error happens at runtime.

**Comment by nonchip** [comment]
> This is because Signal is a non-object type.

well, a non-`Object` object type, technically.

which begs the question, is there a good reason for `Callable` only operating on `Object` methods, not object methods?

**Comment by KoBeWi** [comment]
Classes that don't derive from Object are simple structs passed by value. They aren't tracked by ClassDB (they have their own way to bind methods) and ObjectDB (which means lack of object id, required for Callables). They just aren't capable of being used in Callables and allowing it would require some significant additional code (if it's even possible). So it's a technical limitation.

**Comment by vnen** [comment]
This is the same as #58912: built-in types cannot be used in Callable. I'll close this one since the other is more comprehensive.
