### ISSUE TITLE
Scene derived from Window does not render correctly in the editor (DisplayServer regression)

### ISSUE THREAD

**Issue by ZuBsPaCe** [godotengine/godot#57530]
### Godot version

v4.0.alpha.custom_build [dc4483a3a]

### System information

Windows 10, Vulkan Mobile, NVIDIA TI 1200

### Issue description

I wanted to edit a scene derived from Window in Godot 4 alpha. The scene was created in 3.4 for an add-on. The editor renders the window border, but the content is either black or filled with garbage. Here's a simplified version, only with a button as child:

![image](https://user-images.githubusercontent.com/4233942/152044152-e296ffbf-436b-4f26-9bf3-cdd7d6879f58.png)

The content shows the "View dropdown" because I opened it before and toggled the 'Visible' flag of the window a few times.

The scene renders correctly when I run it:

![image](https://user-images.githubusercontent.com/4233942/152044694-473d5e83-7e87-4cd5-a6ee-a36350fbcc71.png)

### Steps to reproduce

1) Create a new scene derived from button.
2) Open an editor dropdown (for example the 'View' dropdown). Otherwise the content will probably just be black.
3) Toggle 'Window->Flags->Visible' a few times.

### Minimal reproduction project

[godot4-window-render-problem.zip](https://github.com/godotengine/godot/files/7981710/godot4-window-render-problem.zip)

**Comment by MinusKube** [comment]
I believe this has been fixed by #63091
