### ISSUE TITLE
Inspector hints get truncated

### ISSUE THREAD

**Issue by iamtoaster** [godotengine/godot#57536]
### Godot version

4.0.alpha1

### System information

Windows 10

### Issue description

I was unable to find this reported as an issue, sorry if this was reported before.
On Godot 3.4.2 stable when you hover over custom resource used as a key in a dictionary the hint looks like this:
![изображение](https://user-images.githubusercontent.com/22421580/152076808-529a3af9-e3d0-4fa7-84cb-01ad79bd2666.png)
But when I hover over the same key in the same resource but in Godot 4.0.alpha1 I get this:
![изображение](https://user-images.githubusercontent.com/22421580/152076931-3e662d29-8c66-40cb-84d7-9268c10b8f8b.png)
As you can see, compared to older version, the hint is truncated.

In fact I found that a lot of inspector hints use a box too small to hold all of the text on the new 4.0 alpha1, for example:
![изображение](https://user-images.githubusercontent.com/22421580/152078434-ad29d38e-d8f0-4c43-83df-8b1037437c64.png)

### Steps to reproduce

1. Run provided project
2. Open the ```res://data.res``` file
3. Open the ```Data``` dictionary
4. Hover over the first key (which is a custom resource)

### Minimal reproduction project

[ResourceTest-godot3.4.2.zip](https://github.com/godotengine/godot/files/7982916/ResourceTest-godot3.4.2.zip)
[ResourcesTest-godot4.0.alpha1.zip](https://github.com/godotengine/godot/files/7982922/ResourcesTest-godot4.0.alpha1.zip)

Both of archives contain a project that will produce the same ```.res``` file in godot 3.4.2 and godot 4.0.alpha1 respectively.

**Comment by akien-mga** [comment]
Related to #57174.

**Comment by iamtoaster** [comment]
Just tested using #57547 (which closed the related issue), this issue is still present:
![image](https://user-images.githubusercontent.com/22421580/152338502-b2108b2f-7792-4f08-b307-436205eb8443.png)

Windowed to give the tooltip plenty of space:
![image](https://user-images.githubusercontent.com/22421580/152340488-e2c3a3e5-d158-4b93-9bae-86fc01d31caf.png)

Godot version: v4.0.alpha.custom_build [6de5bafd2] (release_debug with lto enabled)
Built and ran on Ubuntu 20.04 container under Arch Linux 5.16.5-arch1-1 host.

**Comment by akien-mga** [comment]
That's probably due to changes in the RichTextLabel logic to split long words. CC @bruvzg
