### ISSUE TITLE
Rotation order Doesn't affect Inspector or Scripts

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#57543]
### Godot version

4.0 Alpha 1

### System information

Windows 11, Vulkan, Nvidia GTX 1050 Ti, 511.23

### Issue description

Rotation Order seems to only affect Gizmo Rotations Properly, using Inspector and Rotate ignores it.

### Steps to reproduce

Change Order of Euler Rotations
Rotate an axis From Inspector
Undo
Rotate the same axis From Gizmo

In MRP Rotate Directional Light X and observe how the sun will end up at two drastically different locations after the same rotation, Only the Gizmo Rotation is accurate, and Inspector will refresh with the accurate data when manipulated in the editor.

### Minimal reproduction project

[Bug.zip](https://github.com/godotengine/godot/files/7986172/Bug.zip)

**Comment by KoBeWi** [comment]
Maybe I'm testing wrong, but I can't reproduce this. Does it still happen in alpha 7? Can you record it?

**Comment by mrjustaguy** [comment]
Godot 4.0 Alpha 7
https://user-images.githubusercontent.com/50302479/166148553-f33b1a66-1a0c-4da3-9278-81411669fd61.mp4

**Comment by Calinou** [comment]
@mrjustaguy Remember that for GitHub video previews to work, you need to have a blank line before *and* after the video URL. I edited your post accordingly, but remember to do this in the future :slightly_smiling_face:

**Comment by mrjustaguy** [comment]
This has been fixed in G4 A11, probably by https://github.com/godotengine/godot/pull/62396
