### ISSUE TITLE
Selecting multiple files in FileSystem dock to Import causes checkboxes to show erroneously to left of import properties

### ISSUE THREAD

**Issue by WolfgangSenff** [godotengine/godot#57545]
### Godot version

4.0.alpha1

### System information

Windows 11, Vulkan

### Issue description

I was going to reimport a bunch of assets at once, and when I held control and clicked on them, I noticed an extra checkbox showing up on the rows for all the import options. See the picture for more.

![GodotAlpha1Issue-ImportCheckboxesOnMultiple](https://user-images.githubusercontent.com/148612/152155410-0a93f7f0-218c-4f31-b726-160d727a2c56.png)

Weird highlighting is mine. :P This issue is incredibly minor and I think would possibly be good for a junior dev or first-timer? (I may try it myself!)

### Steps to reproduce

All I did was go into my current project and select multiple 2D images to import.

### Minimal reproduction project

[Queenship.zip](https://github.com/godotengine/godot/files/7986417/Queenship.zip)

I've attached one, but had to delete some proprietary assets out of the zip. I think it should still work, but I guess we'll find out!

**Comment by akien-mga** [comment]
That's a feature. It lets you select which import settings you want to overwrite for all selected assets. So if they have different configuration initially, you only overwrite the part which you want to change, as opposed to forcing them all to the same config.

**Comment by akien-mga** [comment]
It seems to be covered in the documentation already: https://docs.godotengine.org/en/3.4/tutorials/assets_pipeline/import_process.html#reimporting-multiple-assets
