### ISSUE TITLE
Variables exported with _get_property_list() are not exported on inherited classes

### ISSUE THREAD

**Issue by iuripugliero** [godotengine/godot#57552]
### Godot version

3.4

### System information

Windows 10

### Issue description

Exporting variables to editor inspector with _**_get_property_list()**_ does not export on inherited classes. However if the inherited do have the _**tool**_ command line, it exports sucessfully (exporting through _**export var name : type**_ works in all conditions). Is this by any mean intended?

### Steps to reproduce

Create a new class and export a property with _get_property_list() override. Then instance the class in a scene and extend it with script.

**Comment by Calinou** [comment]
The `tool` status is not automatically inherited. You need to specify it on every child class explicitly.

**Comment by iuripugliero** [comment]
> The `tool` status is not automatically inherited. You need to specify it on every child class explicitly.

But shouldn't the _**_get_property_list()**_ be already overrided on the inherited class? I mean, why does the inherited need the _**tool**_ status if it's not exporting nothing by himself?

**Comment by eh-jogos** [comment]
@iuripugliero As I understand it, the inherited class needs the `tool` keyword so that the editor knows it has to "run" that script in the editor. If the script does not have the `tool` keyword it will not be "run" in the editor, so the `_get_property_list` from the parent class will never be called.

**Comment by KoBeWi** [comment]
See https://github.com/godotengine/godot-proposals/issues/754
Inheriting scripts don't automatically use `@tool`. If a script isn't tool, no method can be called in the editor, including inherited ones. This is a known issue, closing.
