### ISSUE TITLE
Vulkan: Copy paste bug in `renderer_rd/effects_rd.cpp`

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#57559]
### Issue description

https://github.com/godotengine/godot/blob/58324f4df822c7416278cda5bf41662e979f9e31/servers/rendering/renderer_rd/effects_rd.cpp#L1456-L1457

Value of `ss_effects.used_full_mips_last_frame ` is overridden

**Comment by Calinou** [comment]
cc @clayjohn

**Comment by clayjohn** [comment]
The first line: ``ss_effects.used_full_mips_last_frame = use_mips;`` can be deleted.
