### ISSUE TITLE
Imported obj-files (3D-models) not usable when Godot is compiled with double precision floats

### ISSUE THREAD

**Issue by GNSS-Stylist** [godotengine/godot#57554]
### Godot version

v4.0.alpha.custom_build [15db72c53]

### System information

Windows 10, Vulkan

### Issue description

Obj-files (3D-models) added into the project directory can not be used as MeshInstance3D's mesh if godot is compiled with double-precision floats (option float=64). Trying to use imported obj-file (in this case MeshLabCube.obj) leads to following errors (First line and "Dict1" and "Array"-strings added because I tried to find the cause):

>   core\io\resource_format_binary.cpp:602 - type: 0
>   core\io\resource_format_binary.cpp:603 - Method/function failed. Returning: ERR_FILE_CORRUPT
>   Error when trying to parse Variant. Dict1
>   Error when trying to parse Variant. Array
>   Failed loading resource: res://.godot/imported/MeshLabCube.obj-4ecfb58fb3f397871e450daffa9d1ea1.mesh. Make sure resources have been imported by opening the project in the editor at least once.
>   Failed loading resource: res://MeshLabCube.obj. Make sure resources have been imported by opening the project in the editor at least once.
>   Cannot load resource from path 'res://MeshLabCube.obj'.

It is possible to work around this problem by first starting single-precision-version of Godot (compiled from same sources) to generate ".godot"-directory and "*.obj.import"-files. After that the project can be opened with double-precision version as well. If ".godot"-directory and *.obj.import-files are deleted after using the erroneously imported obj-file in the project, the project fails to load in double-precision version:
![image](https://user-images.githubusercontent.com/50438441/152174098-b9d1cc38-6c1b-43e5-91bd-e57cb8f89eca.png)
This also can be fixed by deleting those import-files/dirs and regenerating the files again by loading the project with single-precision-version, although it gives a warning when doing so (which is ok, of course):
![image](https://user-images.githubusercontent.com/50438441/152174427-273dd23a-dbb6-45fe-b6f4-b95634492cc4.png)

While trying to find the cause I made these modification into "core/io/resource_format_binary.cpp" (only added the "Dict x" and "Array"-texts to error strings in function parse_variant(Variant& r_v)):
```
case VARIANT_DICTIONARY: {
	uint32_t len = f->get_32();
	Dictionary d; //last bit means shared
	len &= 0x7FFFFFFF;
	for (uint32_t i = 0; i < len; i++) {
		Variant key;
		Error err = parse_variant(key);
		ERR_FAIL_COND_V_MSG(err, ERR_FILE_CORRUPT, "Error when trying to parse Variant. Dict1");
		Variant value;
		err = parse_variant(value);
		ERR_FAIL_COND_V_MSG(err, ERR_FILE_CORRUPT, "Error when trying to parse Variant. Dict2");
		d[key] = value;
	}
	r_v = d;
} break;
case VARIANT_ARRAY: {
	uint32_t len = f->get_32();
	Array a; //last bit means shared
	len &= 0x7FFFFFFF;
	a.resize(len);
	for (uint32_t i = 0; i < len; i++) {
		Variant val;
		Error err = parse_variant(val);
		ERR_FAIL_COND_V_MSG(err, ERR_FILE_CORRUPT, "Error when trying to parse Variant. Array");
		a[i] = val;
	}
	r_v = a;

} break;
```

Code around line 603 with some debug-output added:

```
default: {
	char errStrBuffer[100];
	sprintf(errStrBuffer, "type: %d", type);
	_err_print_error(FUNCTION_STR, __FILE__, __LINE__, errStrBuffer);
	ERR_FAIL_V(ERR_FILE_CORRUPT);
} break;
```

This is the default-branch of the same switch as the cases above.

I tried to figure out what's going on here, but got quite lost. Looking at the files generated in ".godot"-directory it looked like this could be related to AABB encoded erroneously there (using doubles in the file output from double-version of Godot with the same "variant-id"?). But this is really a guess as I still couldn't find a way to fix this...

### Steps to reproduce

1. Create a 3D-scene with Godot compiled with double-precision floats (option float=64)
2. Add .obj-file to be imported into project directory
3. Try to use the imported file as MeshInstance3D's mesh. This will output the aforementioned errors.

### Minimal reproduction project

[obj_import_bug_double.zip](https://github.com/godotengine/godot/files/7987636/obj_import_bug_double.zip)
Loading this fails in Godot compiled with double-precision floats.

**Comment by Calinou** [comment]
cc @aaronfranke
