### ISSUE TITLE
Godot crashes when I try to open

### ISSUE THREAD

**Issue by arthursiq5** [godotengine/godot#57564]
### Godot version

Godot 3.4.2 default version x86 & x86_64

### System information

Ubuntu 20.04.03 LTS 64 bits Intel Core i3-4170 15 GB RAM NVidia GeForce GT 420

### Issue description

When I try to open the engine on my computer the session is closed and I go back to the login screen and i haven't found anyone with the same problem yet. It's probably some missing dependency, but I don't know which one. How to fix it?

### Steps to reproduce

Try to run the program by clicking on it or through the terminal

**Comment by Calinou** [comment]
Which graphics driver are you using? The Nouveau driver (which is the default unless you installed the proprietary NVIDIA driver) is unstable and is regularly affected by regressions.

**Comment by arthursiq5** [comment]
Yes, is the default, what I need to do?

**Comment by Calinou** [comment]
> Yes, is the default, what I need to do?

You should install the proprietary NVIDIA driver from the driver manager application that came with your Ubuntu installation.

**Comment by arthursiq5** [comment]
It works now, thanks
