### ISSUE TITLE
Area2D+CollisionShape2D: mouse_entered signal received when the cursor moves from Area2D into a Panel

### ISSUE THREAD

**Issue by Sauermann** [godotengine/godot#57588]
### Godot version

v4.0.alpha.custom_build [ca42bfb2a]

### System information

Debian 11, Vulkan

### Issue description

Moving the mouse from an Area2D + CollisionShape2D to a Panel causes the Area2D to receive the following three signals:
1. `mouse_exited`
2. `mouse_entered`
3. `mouse_exited`

I would expect, that an Area2D node would receive only a single `mouse_exited` signal in this situation.

### Steps to reproduce

1. Load and start MRP
2. Move Mouse cursor to the right side of the window, then into the Area2D (clouds)
3. Move mouse cursor from Area2D into the Panel (left side)
4. Console shows output from multiple signals 

### Minimal reproduction project

[BugCollisionShape.zip](https://github.com/godotengine/godot/files/7995079/BugCollisionShape.zip)

**Comment by Calinou** [comment]
@Sauermann Can you reproduce this on 3.4.2?

**Comment by Sauermann** [comment]
Yes, bug is also there.
Here is a reproduction project for v3.4.2.stable.official [45eaa2daf]: [BugCollisionShape3.zip](https://github.com/godotengine/godot/files/7996743/BugCollisionShape3.zip)

**Comment by KoBeWi** [comment]
Can't reproduce in alpha 6
![godot4_llniAbcBx5](https://user-images.githubusercontent.com/2223172/162640512-42c7d333-4626-4df5-be1b-6cc1981e1f74.gif)
Not sure if testing correctly.

**Comment by Sauermann** [comment]
I just tried and can reproduce this issue in current master v4.0.alpha.custom_build [83d267377].

https://user-images.githubusercontent.com/6299227/162640755-ccf26236-3aeb-44c9-a06f-145bb1f2a628.mp4

**Comment by KoBeWi** [comment]
How come are we getting different results? I can't reproduce this at all. Is it system specific or what? (I'm using Windows 10)

**Comment by Sauermann** [comment]
I can reproduce this issue on Windows 10 with alpha 1 and alpha 4 and the given MRP.
Maybe it has to do with the speed of the mouse cursor? (I move the mouse-cursor faster than you)

**Comment by KoBeWi** [comment]
Ok I managed to reproduce it a few times, but it seems random, idk.

**Comment by Sauermann** [comment]
As far as I can tell, it is related to threads, so a bit of randomness is to be expected.

**Comment by Sauermann** [comment]
In the 3.x branch, this got fixed between v3.4.4 and v3.5.1
In the 4.0 branch, this got fixed between alpha11 and alpha12.

Closing this issue.
