### ISSUE TITLE
Area2D+CollisionShape2D: inconsistent mouse_entered signals when coming from Panel 

### ISSUE THREAD

**Issue by Sauermann** [godotengine/godot#57580]
### Godot version

v4.0.alpha.custom_build [ca42bfb2a]

### System information

Debian 11, Vulkan

### Issue description

When moving the mouse cursor from a Panel to a Area2D with a CollisionShape2D, the `mouse_entered` events of the Area2D happen at unexpected locations. The following graphic shows, where they actually happen and where I would expect them to happen.

Could be related to #26181

![image](https://user-images.githubusercontent.com/6299227/152319591-482fd15d-23b4-4838-a4e2-a7723d5dbeca.png)

### Steps to reproduce

1. Load and start MRP
2. move mouse around over the edge of the Area2D
3. see console output, where on_entered signals are happening

### Minimal reproduction project

[BugCollisionShape.zip](https://github.com/godotengine/godot/files/7993366/BugCollisionShape.zip)

**Comment by TheDuriel** [comment]
This is because your Control nodes, Panels in this case, consume all mouse inputs. If you change your Panels mouse filter from STOP to PASS, those inputs will be passed on to control nodes beneath them in the draw order, and eventually make their way to the physics objects as well.

Control nodes process mouse inputs first in all cases, regardless of tree order.

**Comment by Sauermann** [comment]
@TheDuriel Thank you for the explanation. 

Setting Panel.mouse_filter to PASS, does not change the mentioned behavior. (but IGNORE would)
As mentioned in https://docs.godotengine.org/en/latest/classes/class_control.html#enum-control-mousefilter, this is expected behavior. Closing this issue.

For reference, here is the relevant location in the code:
https://github.com/godotengine/godot/blob/7f93eb34cf4b4e900aa9ba185b009fcb409d5d1c/scene/main/viewport.cpp#L1784
