### ISSUE TITLE
setget breaks export hints

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot#57597]
### Godot version

3.4.2

### System information

Windows 7 64-bit

### Issue description

When trying to use export hints for, in this example, to provide a hint with a slider, the slider breaks and the export number itself shows as 1 at all times. If I remove the setget, it works as expected and the number can be changed.

### Steps to reproduce

```
tool
extends Particles

export(float,0,10) var life_height = 1.0 setget _set_life_height

func _set_life_height(value):
	lifetime = value
	
func _ready():
	_set_life_height(life_height)
```

**Comment by kleonc** [comment]
In the `_set_life_height` you're never changing the value of `life_height` so it of course doesn't change (and thus it has its default value which is `1.0`). That's expected behavior. You probably want such setter instead:
```
func _set_life_height(value):
	life_height = value
	lifetime = value
```

**Comment by pycbouh** [comment]
Closing as user error, as explained by @kleonc
