### ISSUE TITLE
3.4.3rc-1 web editor not working

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#57592]
### Godot version

https://editor.godotengine.org/releases/3.4.3.rc1/

### System information

OSX (Chrome)

### Issue description

The web editor no longer seems to be working:

https://editor.godotengine.org/releases/3.4.3.rc1

```
godot.tools.js:380 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'godot.tools.wasm')
    at b.B (godot.tools.js:380:298)
    at startEditor ((index):641:12)
    at (index):667:5
```

### Steps to reproduce

Go here

https://editor.godotengine.org/releases/3.4.3.rc1/

**Comment by SkanerSoft** [comment]
Windows 11, Google Chrome
![1643906915](https://user-images.githubusercontent.com/13809475/152388770-92d76fdf-9e90-494d-b96a-04c7def252fc.png)

**Comment by Calinou** [comment]
I can confirm this on Firefox 96 on Linux:

```
Uncaught (in promise) TypeError: this.i.A is undefined
    B https://editor.godotengine.org/releases/3.4.3.rc1/godot.tools.js:380
    startEditor https://editor.godotengine.org/releases/3.4.3.rc1/:641
    <anonymous> https://editor.godotengine.org/releases/3.4.3.rc1/:667
    promise callback* https://editor.godotengine.org/releases/3.4.3.rc1/:666
    EventHandlerNonNull* https://editor.godotengine.org/releases/3.4.3.rc1/:665
[godot.tools.js:380:281](https://editor.godotengine.org/releases/3.4.3.rc1/godot.tools.js)
```

**Comment by Faless** [comment]
Confirmed, likely a regression from this: https://github.com/godotengine/godot/pull/57482/commits/2f509f1b12c33234a0d8f0e254c727fd92e57720 (https://github.com/godotengine/godot/pull/57482) .
I did forget the CC would complain about that. I'll see if I can tell it to leave the names in the config alone, or revert that commit in case.
