### ISSUE TITLE
Hide Animation editor plugin button if no node selected

### ISSUE THREAD

**Issue by GlaDOSik** [godotengine/godot#5759]
**Operating system or device - Godot version:**
Windows 7 64bit, Godot 2.1 beta 64bit
GPU: GTX 970 - driver version 365.19

**Issue description** (what happened, and what was expected):
The Animation editor button should be hidden, if no AnimationPlayer node is selected. It can lead to idea you can use editor without the AnimationPlayer node. You can crash the editor doing this:

1. Create an empty scene (do NOT add node AnimationPlayer)
2. Create a new animation resource.
3. Copy Resource (gear icon in inspector)
4. Paste Animation (gear icon in animation player)

The other fix would be to disable Animation Tools icon if no node is selected.

**Comment by TheoXD** [comment]
More info please, I can't recreate

**Comment by GlaDOSik** [comment]
Ok. I'm using beta version from the website for Windows 64-bit. I didn't compile it from GitHub source. I would upload the test project but I can replicate it even in new empty one.

![gcrash](https://cloud.githubusercontent.com/assets/3484686/16903260/bff9e26a-4c79-11e6-96f0-d470a0cfcbd5.jpg)

**Comment by TheoXD** [comment]
I know now, your scene is empty, basically you couldn't have any AnimationPlayer, you just opened the Anim editor by clicking on the "Animation" button on the bottom, right? You should change this issue to "Hide Animation editor plugin button if no node selected" to prevent from unintentional use, or something like that.

**Comment by GlaDOSik** [comment]
Yes, that's it. The Animation button is confusing. Will change the name of issue.

**Comment by neikeq** [comment]
I think this was solved by 1247253
