### ISSUE TITLE
GDScript 2.0: Crash, no error message for function signature parent mismatch

### ISSUE THREAD

**Issue by SaveToTheADrive** [godotengine/godot#57601]
### Godot version

v4.0.alpha1.official [31a7ddbf8]

### System information

Win 10

### Issue description

When overloading a function, if there is a mismatch with its parent class signature (specifically with number of args), there will be no error message in the editor (there is such a message in 3.4, for example).

Attempting to use an arg in a subclass that doesn't exist in the parent class will crash the editor.

### Steps to reproduce

Create the following scripts in a project:
```
#subclass.gd
extends Node

class_name Subclass

func foo() -> void:
	pass
```

```
#sub_subclass.gd
extends Subclass

class_name SubSubclass

func foo(bar: Vector3) -> void:
        var baz = bar  #this is allowed
        bar.   #adding the '.' here causes autocomplete to pop up, and crash the editor.
        baz.   #adding the '.' here causes autocomplete to pop up, and crash the editor.
	pass
```

You can assign an argument in this situation, but trying to get an attribute or function from either the arg, or the var it's assigned to will crash the editor.

**Comment by vnen** [comment]
The crash is likely the same as #57414, not related to the function override.

The function signature validation is still a problem for now.
