### ISSUE TITLE
Frequent GPU crashes with Radeon 5700XT

### ISSUE THREAD

**Issue by DKesserich** [godotengine/godot#57602]
### Godot version

4.0 Alpha

### System information

Windows 10 20H2, Vulkan, AMD Radeon 5700XT (21.12.1), Ryzen 3900X, 32GB RAM

### Issue description

When running the editor I will get frequent GPU and system crashes.

### Steps to reproduce

Open the editor for a few minutes.

**Comment by DKesserich** [comment]
Just to note that I did not experience this with a build from commit af451ffaa

**Comment by pycbouh** [comment]
That’s a long list on commits between June 2021 and now. Do you have any particular scene open? I have the same GPU, and also use Windows, and I haven’t experienced anything like that in months in between this commit and alpha.

**Comment by DKesserich** [comment]
I just got it again. Blue screen code is "VIDEO_SCHEDULER_INTERNAL_ERROR."

Happened while I was adjusting light settings.

**Comment by pycbouh** [comment]
So you are working on some scene then? Can you share it?

**Comment by DKesserich** [comment]
Here you go.

**Comment by DKesserich** [comment]
Looks like the zip is too big to be attached. It's on Google drive here: https://drive.google.com/file/d/1gwl8Rxy95dDIj8h4d1GJtwHjGtmGXQIl/view?usp=sharing

**Comment by Calinou** [comment]
@DKesserich Can you (or anyone else) still reproduce this bug in [Godot 4.0alpha8](https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-8) or any later release?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.
