### ISSUE TITLE
(4.0) Can Tween container greyed out properties, but can't animate them using AnimationPlayer or change them in Editor

### ISSUE THREAD

**Issue by seppoday** [godotengine/godot#57603]
### Godot version

4.0 1 alpha

### System information

Windows 11

### Issue description

Hello. I noticed that there is a problem with consistency with positioning control nodes. That's kinda confusing and probably prone to bugs.

1.  In Editor I can't change control child nodes rect_position:
![image](https://user-images.githubusercontent.com/62170071/152421560-4ce9369b-5dab-401a-bcd4-084903f5dcdc.png)
2. In Animaton Player I also cannot do it:
![image](https://user-images.githubusercontent.com/62170071/152421650-40d7de32-ae7e-4eba-8762-b21bf7d2ccd9.png)
3. But using Tween I can:
![image](https://user-images.githubusercontent.com/62170071/152421787-6ecd2f52-18e2-4aab-916b-a94d3c174716.png)

### Steps to reproduce

Try changing control node position in those 3 ways.

**Comment by Calinou** [comment]
Controls within containers cannot be moved manually, as their position will be reset every time the container is updated (e.g. when new elements are added).

I guess we could display a message when a tween tries to set a `rect_` property on a Control node within a container. This check isn't cheap, so it would only be done in debug builds.

**Comment by seppoday** [comment]
Isn't it kinda weird that you can change control rect_position using tween, but not by using Animation Player? I understand that ou can't change it in editor. But Tween and Animation Player difference is kinda weids I guess?

**Comment by Calinou** [comment]
> Isn't it kinda weird that you can change control rect_position using tween, but not by using Animation Player? I understand that you can't change it in editor. But Tween and Animation Player difference is kinda weird I guess?

The Tween change happens via code, while https://github.com/godotengine/godot/pull/30623 only affects the editor. There is currently no mechanism in place to detect changes done to Controls by code.

**Comment by TheDuriel** [comment]
> I guess we could display a message when a tween tries to set a `rect_` property on a Control node within a container. This check isn't cheap, so it would only be done in debug builds.

Really not worth it. There are cases in which you want to do this for legitimate reasons, like animating your UI- And then letting containers take over once you're done.

**Comment by seppoday** [comment]
In my case I was happy that I could animate node via code. I was just supprised that Animation Player way didn't work. So @Calinou we can probably close this one. Sorry for adding unnecesary issue :)

**Comment by GreenCrowDev** [comment]
Sorry to up this one, but this is the closest thing to the problem I'm facing.

I'm trying to find the most flexible way to animate UI in Godot, and I thought I'd have to use the `AnimationPlayer` node.
To my surprise, like shown in this issue, `Control` properties of children of container nodes are greyed out.
I see the point of doing this in the main editor, but I thought that these would be free to change using the `AnimationPlayer`.

So... Is using tweens the only clean way to animate UI inside container nodes?

Or should we expose the aforementioned parameters when animating them in `AnimationPlayer`?

Edit: Using 4.4.1
