### ISSUE TITLE
Clicking GraphNode Crashes Game

### ISSUE THREAD

**Issue by toliaferrode** [godotengine/godot#5761]
**Operating system or device - Godot version:**
Ubuntu MATE 15.10, Godot 2.1-beta

**Issue description** (what happened, and what was expected):
I create a Node, add a GraphNode to it, save my scene, hit play. When I click on the GraphNode in the game it crashes. No debug information or anything on crash either.

**Steps to reproduce:**
Create a GraphNode, play game, and click on the GraphNode.

**Link to minimal example project** (optional but very welcome):
[Test2.zip](https://github.com/godotengine/godot/files/368190/Test2.zip)

**Comment by Qudware** [comment]
Are you sure your GraphNode is a child of a GraphEdit node?

**Comment by vnen** [comment]
I can reproduce this with latest master. Indeed to reproduce I didn't use GraphEdit node, but it shouldn't crash nevertheless.

**Comment by TheoXD** [comment]
It should give warning info like the rest.

**Comment by vnen** [comment]
The problem is [here](https://github.com/godotengine/godot/blob/b0c2801458ed87f6e643c023e86488ee3a16c7f5/scene/gui/graph_node.cpp#L562). It tries to give focus to the parent control, but if the parent is not a Control, this will call a function in a null pointer, thus crashing.
