### ISSUE TITLE
Autocomplete not working for "set_shader_param"/"get_shader_param"

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#57619]
### Godot version

v3.5.beta1.official [b9b23d222]

### System information

w10 64

### Issue description

Autocompletion doesn't work for "set_shader_param" and not for "get_shader_param" and maybe not for other methods either.
This can lead to thinking "am I wrong?" or "am I typing it wrong?" or "set_shader_param is not a material method?".
![Animation](https://user-images.githubusercontent.com/19652075/152514797-05737ff9-9299-4882-8683-6442a1e45b5c.gif)

### Steps to reproduce

write "set_shader_param"

### Minimal reproduction project

...

**Comment by ICatRegister** [comment]
Because `$whatever_node.material` returns the base `Material `class, not the `ShaderMaterial`

**Comment by Torguen** [comment]
Well... how do you have to write it so that it appears in the autocomplete?
I'm trying but I don't see the way.

**Comment by arkology** [comment]
Workaround is `(material as ShaderMaterial)`

**Comment by Torguen** [comment]
Ok, I guess this is the "correct" way.
![Captura](https://user-images.githubusercontent.com/19652075/152521994-bd0bc09b-b683-40ba-bdc3-f77d6611e6be.PNG)
