### ISSUE TITLE
On Error Can't Press F8 To Close Running Game Window

### ISSUE THREAD

**Issue by toliaferrode** [godotengine/godot#5762]
**Operating system or device - Godot version:**
Any OS, any Godot version

**Issue description** (what happened, and what was expected):
If when I press play there's a script or debug error I can't press F8 to close the game window and get back to the editor. I think it would really help usability if we were able to quickly close the window by hitting a key press, instead of having to use the mouse and get the editors focus and then hit the stop button. Can't just click the X button on the window, either. This can really be a hassle if your game window is fullscreen because you can't get back to the editor at that point.

**Steps to reproduce:**
Press play with an error in your script or debug error.

**Link to minimal example project** (optional but very welcome):

**Comment by vnen** [comment]
The thing is when the game stops on an error, it's completely paused, not processing input anymore. But it also focus the editor automatically, so pressing <kbd>F8</kbd> there should just work.

**Comment by toliaferrode** [comment]
It doesn't. I saw a project with the default window size at 800 by 600 and I suspect they did that so they could still reach the controls on errors.

**Comment by Calinou** [comment]
Is this still reproducible in the `master` branch?

**Comment by KoBeWi** [comment]
Well, the editor really is focused on error, even with Fullscreen and Always on Top enabled, so there's no problem closing the game. But when you for whatever reason re-focus on the game window, you can't use F8 (which I guess is expected, as no input is processed then, like mentioned).

**Comment by akien-mga** [comment]
So this is more or less a feature request to make a kill-switch available in running games (possibly only when `TOOLS_ENABLED` is defined *and* not in the editor, otherwise it would kill the editor too...).

I'd suggest opening a proposal on [godot-proposals](https://github.com/godotengine/godot-proposals) if this is still wanted to discuss further and see how to implement it if there's community interest.
