### ISSUE TITLE
More TestObjects?

### ISSUE THREAD

**Issue by toliaferrode** [godotengine/godot#5764]
**Operating system or device - Godot version:**
Any OS, any Godot version

**Issue description** (what happened, and what was expected):
Could we get more primitives like the testcube? Like cylinder, sphere, capsule, plane, and quad?

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by bojidar-bg** [comment]
Sorry, duplicate of #1381
