### ISSUE TITLE
[4.0][BUG] Animation in BlendSpace shift in y axis when blend_value is moving between two node

### ISSUE THREAD

**Issue by CheapMiao** [godotengine/godot#57640]
### Godot version

v4.0.alpha1.official [31a7ddbf8]

### System information

Windows 11

### Issue description

I have recorded the bug and upload the video. [https://youtu.be/0zu7T90w8wY](https://youtu.be/0zu7T90w8wY)
In this video, you can see that I use three node in BlendSpace1D and drag the value, seeing how does the blend effect, but the result is the armature is moving in y axis, which is strange

### Steps to reproduce

[RobotPlayer.zip](https://github.com/godotengine/godot/files/8005433/RobotPlayer.zip)
1. download the zip and get the gltf
2. import the gltf into project
3. you would get two same gltf showing in your file system (It is a known bug, ignore it)
4. open gltf and inherit it,
5. add animationtree and create blendspace1D
6. add idle, run, fast run animation into blendspace
7. drag the blend_value and you can see the armature is moving in y axis, which is strange

### Minimal reproduction project

[ThirdPersonControllerWithMesh.zip](https://github.com/godotengine/godot/files/8005519/ThirdPersonControllerWithMesh.zip)

**Comment by TokageItLab** [comment]
Dupe #54407.

**Comment by CheapMiao** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
