### ISSUE TITLE
Godot4 doesn't launch because of vulkan problems

### ISSUE THREAD

**Issue by dan1338** [godotengine/godot#57645]
### Godot version

4.0-alpha1

### System information

Windows 10, NVIDIA GeForce GTX 1060

### Issue description

I wanted to try out the new 4.0 alpha but all I get is the log below and a windows popup

Windows popup
```
Unable to initialize Video driver

Your video card driver does not support any of the supported Vulkan or OpenGL versions.
Please upgrade your drivers or if you have a very old integrated GPU upgrade it.
```
Cmd log
```
Godot Engine v4.0.alpha1.official.31a7ddbf8 - https://godotengine.org
ERROR: No surface extension found, is a driver installed?
   at: (drivers/vulkan/vulkan_context.cpp:351)
```

I assume this means it failed to initialize the vulkan context, fair game, but why wouldn't it fallback to OpenGL?
I'm not using latest NVIDIA drivers because I was getting artifacts with them, so I will not update.
This PC runs Godot3.4 just fine, does that mean that Godot4 will drop support for anything that doesn't support vulkan?

### Steps to reproduce

Launch the Godot 4 executable

**Comment by dan1338** [comment]
I just noticed #57622, is somewhat similar so this may be considered a duplicate.

**Comment by Ansraer** [comment]
Godot 4 currently only has a vulkan renderer. The opengl renderer is still being worked on and wasnt ready in time for alpha 1.

**Comment by Calinou** [comment]
The GeForce GTX 1060 *does* support Vulkan. Are you using a laptop with hybrid graphics, or a desktop with multiple graphics adapters enabled (e.g. with a monitor on an Intel IGP and another on a dedicated NVIDIA GPU)?

**Comment by Salvakiya** [comment]
Just adding a note here. I had the same issue with my 1660ti and beta 14. updating the NVIDIA Graphics drivers did not work. trying to force godot to use the dedicated graphics via nvidia's control panel did not work. However turning off the integrated graphics in the bios worked.

I thought this odd but also realized my laptop has a Ryzen 7 4800H and I updated those drivers as well. After updating those everything worked fine.

Not sure if Godot should be able to detect which graphics hardware has support for Vulkan and pick that one... or if there is some reason why I could not force a card using the nvidia control panel.

**Comment by RSSpeacemaker** [comment]
> Just adding a note here. I had the same issue with my 1660ti and beta 14. updating the NVIDIA Graphics drivers did not work. trying to force godot to use the dedicated graphics via nvidia's control panel did not work. However turning off the integrated graphics in the bios worked.
> 
> I thought this odd but also realized my laptop has a Ryzen 7 4800H and I updated those drivers as well. After updating those everything worked fine.
> 
> Not sure if Godot should be able to detect which graphics hardware has support for Vulkan and pick that one... or if there is some reason why I could not force a card using the nvidia control panel.

Your solution just fixed my problem as well! Same exact graphics card and processor. Updating my Ryzen drivers fixed the issue.

**Comment by pfjarschel** [comment]
> Your solution just fixed my problem as well! Same exact graphics card and processor. Updating my Ryzen drivers fixed the issue.

Still having the same problem, with the same GPU, but in my case there is no way to disable the integrated GPU. Trust me, I tried A LOT, because almost every vulkan game gives me trouble. There are some, however, that can actually detect the proper gpu, or at least bypass the vulkan check on the integrated.

**Comment by felipeLucio1** [comment]
I've tried the command suggested by error message to rendering with opengl3 driver and it was ok. So, I created a .bat script that executes Godot's launcher and put it into my Destop with a shrotcut. It "solved" problem.
