### ISSUE TITLE
`PoolByteArray.decompress_dynamic()` returns a boolean instead of a decompressed PoolByteArray

### ISSUE THREAD

**Issue by PeterMarques** [godotengine/godot#57644]
### Godot version

3.4.2.stable

### System information

Windows 10

### Issue description

The return of the function does not match the docs, as it its always returning a bolean, never a new, decompressed, PoolByteArray.

### Steps to reproduce

Compress (using 1 or 4).
try to decompress, it returns the bug.

### Minimal reproduction project

[PoolByteArray.decompress_dynamic() BUG.zip](https://github.com/godotengine/godot/files/8006416/PoolByteArray.decompress_dynamic.BUG.zip)

**Comment by Calinou** [comment]
For reference, this was [cross-posted on the Godot forums](https://godotforums.org/discussion/28927/poolbytearray-decompress-dynamic-bug).

**Comment by akien-mga** [comment]
Fixed by #57652.
