### ISSUE TITLE
Base Node Icon in Create New Node Window?

### ISSUE THREAD

**Issue by toliaferrode** [godotengine/godot#5766]
**Operating system or device - Godot version:**
Any OS, Godot 2.1-beta

**Issue description** (what happened, and what was expected):
Can we get the nice white circle icon for the base node next to it in the Create New Node window? We see it in the inspector, but not in the Create Node window. I think it really helps drive home that it's a useful node in some cases and can be used. Like it's not just a tree item to organize everything else.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by bojidar-bg** [comment]
Ping @djrm :smile:

**Comment by akien-mga** [comment]
No need to ping @djrm, `Node` already has an icon. I don't know why it doesn't show in the Create New Node window though.
