### ISSUE TITLE
Problem starting in "Force Maximized" mode

### ISSUE THREAD

**Issue by AncRad** [godotengine/godot#57662]
### Godot version

4.0.alpha1

### System information

OS: Windows 7, CP: i5-2550k Sandy Bridge, two monitors or one monitor

### Issue description

The problem is the incorrect position of the window when running the Godot application in full size mode.
I'm using two monitors: Monitor 1 (3440x1440, bottom); Monitor 2 (1920x1080, top). The same problem occurs when using a single monitor.
I expect that immediately after the application is launched, the window should be at its maximum size and centered on the screen with the window title at the top and no side or bottom edges of the frame.
I get a regular size window outside of the screen.

### Steps to reproduce

I launch an application (project) or Godot scene in full screen mode in any of the following ways:
1. from the console with "--maximazed" argument and "--position" argument;
2. from a script using the `OS.create_instance(args)` method with "--maximazed" and "--position" arguments.
3. from an editor application with EditorSettings "run/window_placement/rect" set to "Force Miximized";

I am also attaching a video. [2022-02-05 16-12-45.zip](https://github.com/godotengine/godot/files/8008102/2022-02-05.16-12-45.zip)
Please note: everything that is gray is the desktop area, the black areas on the top-left and top-right are non-working areas - the cost of the video format.
In the video, I demonstrate triggering the error by running the scene from the editor with the EditorSettings "run/window_placement/rect" set to "Force Miximized".

**Comment by Calinou** [comment]
@AncRad Can you reproduce this on 3.4.2?

**Comment by AncRad** [comment]
> @AncRad Can you reproduce this on 3.4.2?

In version 3.4.2 I can't reproduce this error.
I tried to manipulate the editor settings - it didn't work.

I and also tried to run using `OS.execute(..` - it didn't work out.
I used such an entry:
`OS.execute("E:/GODOT/engine/Godot.exe", PoolStringArray(["--path", "E:/GODOT/projects/ninja/ninja_001", "--position", "758,-1080", "-- maximized"]), false)`, in this entry, the arguments `"--position", "758,-1080"` send the window to the second monitor, and it expands to full size, as I expect according to the EditorSettings "run/window_placement/rect" set to "Force Miximized".

In version 4.0.alpha1  I managed to repeat the bug with a similar entry:
`OS.execute("E:/GODOT/engine/godot4.0/Godot_v4.0-alpha1_win64.exe", PackedStringArray(["--path", "E:/GODOT/projects4.0/123", "--position", "758,-1080", "--maximized"]))`, and the bug was exactly the same as before.
I tried changing the arguments "--maximized" and "--position" in places in both versions of the engine - it didn't affect anything.

**Comment by KoBeWi** [comment]
Still valid in 70eaaf2

**Comment by akien-mga** [comment]
Is this still reproducible in 4.0 RC 2 or later?

According to @bruvzg he can't reproduce it on Windows 11.

**Comment by KoBeWi** [comment]
Yeah seems fixed.
