### ISSUE TITLE
v4.0 - There are distinct results between hex and RGB when changing the same color from an object. The hex one being the right color.

### ISSUE THREAD

**Issue by AttackButton** [godotengine/godot#57663]
### Godot version

v4.0.alpha.custom_build [8b5d6d4cb]

### System information

Windows 8 and 10

### Issue description

As the title says, there are distinct results between hex and RGB when changing the same color from an object. The hex always brings the correct color.

This code:
```
extends ProgressBar

func _ready():
	var bg_style = get("theme_override_styles/bg")
	bg_style.bg_color = Color(0, 41, 255)
#	bg_style.bg_color = Color("#0029ff")

```
will brings:

![image](https://user-images.githubusercontent.com/25422687/152644256-8caa6eb8-a0d3-421f-b850-637912f24b97.png)

And this:

```
extends ProgressBar

func _ready():
	var bg_style = get("theme_override_styles/bg")
#	bg_style.bg_color = Color(0, 41, 255)
	bg_style.bg_color = Color("#0029ff")

```

Will brings this color:
![image](https://user-images.githubusercontent.com/25422687/152644296-239db81d-c73a-41d5-9bda-e549b6f6aa63.png)

### Steps to reproduce

Create a script and try to change the same color of an object (Sprite2D, etc) using it´s hex or RGB.

### Minimal reproduction project

[color_issue.zip](https://github.com/godotengine/godot/files/8008117/color_issue.zip)

**Comment by timothyqiu** [comment]
Parameters of the `Color` constructor are float point values that are typically 0.0~1.0.

You can use `Color(0, 41/255.0, 1)` or `Color8(0, 41, 255)`.

**Comment by Zireael07** [comment]
I think many newcomers will expect the constructor to accept RGB (0-255) instead of 0-1.0. Do we have such a constructor? I think not, and it's probably worth adding.

**Comment by pycbouh** [comment]
> I think many newcomers will expect the constructor to accept RGB (0-255) instead of 0-1.0. Do we have such a constructor? I think not, and it's probably worth adding.

We can’t, it would conflict. Which is why we have Color8.
