### ISSUE TITLE
`class_name` nodes within enabled plugins are no longer displayed in the editor's Create New Node dialog

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#57668]
*Related to https://github.com/godotengine/godot/issues/30048 – however, the plugins are enabled here.*

### Godot version

4.0.dev (fc09d783f)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 495.46)

### Issue description

`class_name` nodes within enabled plugins is no longer displayed in the editor's Create New Node dialog.

### `master`

![image](https://user-images.githubusercontent.com/180032/152652329-ad77245d-bee3-47f6-91c0-d560764c757e.png)

### `3.x`

![2022-02-05_18 27 46](https://user-images.githubusercontent.com/180032/152652315-d9ef0503-e458-4e45-a2da-5508173cba9e.png)

### Steps to reproduce

- Create a new editor plugin in the **Project Settings > Plugins** dialog. Enable the plugin by checking **Activate now?** in the creation dialog.
- Empty the main plugin script, only to leave the following:

```gdscript
@tool
extends EditorPlugin
```

- Add a second script within the add-on directory. In this script, add:

```gdscript
class_name AddonNode
extends Node

func _ready():
	print("Addon node!")
```

- Add a new node in the scene tree dock, search for "Addon". Notice the AddonNode will not appear, while it did in `3.x` while following the same steps.

### Minimal reproduction project

- `master` (broken): [test_class_name_addon_master.zip](https://github.com/godotengine/godot/files/8008480/test_class_name_addon_master.zip)
- `3.x` (working): [test_class_name_addon_3.x.zip](https://github.com/godotengine/godot/files/8008481/test_class_name_addon_3.x.zip)

**Comment by action-script** [comment]
I am having this issue with the [godot-interpolated-camera3d](https://github.com/godot-extended-libraries/godot-interpolated-camera3d) addon.

**Comment by MinusKube** [comment]
Seems to have been fixed since Alpha 11.

**Comment by KoBeWi** [comment]
Doesn't seem to be fixed. You can test it easily with the interpolated camera addon.
![godot_0MMonsmYeq](https://user-images.githubusercontent.com/2223172/195712293-793de3e3-25e5-47f7-a716-1417fd417f48.gif)

**Comment by KoBeWi** [comment]
Nevermind, this is the same as #30048 (it works if the plugin is enabled)
