### ISSUE TITLE
Editor Undo Only Works If Mouse Is Not On Axis Handle

### ISSUE THREAD

**Issue by toliaferrode** [godotengine/godot#5767]
**Operating system or device - Godot version:**
Ubuntu 15.10, Godot 2.0.4.1 or Godot 2.1-beta

**Issue description** (what happened, and what was expected):
Undo only seems to work in a way that after you've transformed or rotated, you then have to take the mouse cursor off the axis gizmo handle and then hit undo. I feel like this is unintuitive as I thought undo was broken all this time.

**Steps to reproduce:**
Change a node's transform or rotation, move the cursor, and then hit undo.

**Link to minimal example project** (optional but very welcome):

**Comment by bojidar-bg** [comment]
Pretty ping, would be nice if this issue isn't drowned (and also would be nice if it is confirmed on master).

**Comment by DualMatrix** [comment]
Tested in master. Undo works properly now.

**Comment by akien-mga** [comment]
Thanks, closing.
