### ISSUE TITLE
Place Random Tile does not work for animations?

### ISSUE THREAD

**Issue by rakkarage** [godotengine/godot#57677]
### Godot version

v4.0.alpha1.official [31a7ddbf8]

### System information

Windows 10

### Issue description

![Animation](https://i.postimg.cc/nV4Z7CGP/Animation.gif)
![Shader](https://i.postimg.cc/90Yhjnfh/Shader.gif)

TileSet animations all start at frame 0? This is fine for water tiles which all have to sync up but sometimes you want to start each animation at a random frame. In Godot 3 (and 4), one can animate tiles with a shader which can use the Place Random Tile check and Probability to either start animations at frame 0 or at a random frame.

	shader_type canvas_item;
	render_mode unshaded;

	uniform sampler2D frames: hint_albedo;
	uniform float count;
	uniform float duration;
	uniform float width;
	uniform float startX = 0;

	void fragment() {
		float frame = floor(mod(TIME, count * duration) / duration);
		float offset = floor((UV.x - startX) / width);
		COLOR = texture(frames, UV + vec2((mod(offset + frame, count) - offset) * width, 0));
	}

To get the shader to work in 4 I had to put it on each frame and select each frame when painting.

I guess the frames could access to a Probability property? Then the Place Random Tile check could be used to indicate if u want a Random Tile based on the probability or not?

Edit: or probability does not even matter when choosing the first frame of an animation.? It is just the mechanism that allows for selecting a random start frame in the shader? This may already be being worked on since check is usable but does nothing when animation selected. thanks

Thanks.

### Steps to reproduce

1. Open TileSetShader.tscn, select all Banner1 frames in TileMap window, check Place Random Tile and draw **random** animated banners
2. Open TileSetAnimation.tscn select Banner1 animation in TileMap window, check Place Random Tile and draw **same** animated banners

### Minimal reproduction project

https://github.com/rakkarage/NewTileMapTest

**Comment by rakkarage** [comment]
i think the problem is that once u make an animation, you can only select the first tile from the animation, so the Place Random Tile button does nothing since you must have multiple tiles selected

the fact that this button does nothing when an animation is selected, and this feature (random animation starting tile) is missing is not a coincidence?

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/6856, as feature proposals are now tracked on the Godot proposals repository.
