### ISSUE TITLE
Vilros retro gaming ps2 controller issue

### ISSUE THREAD

**Issue by Titanium-Rat** [godotengine/godot#57671]
### Godot version

Godot Engine v3.4.2.stable

### System information

Windows 10

### Issue description

Vilros retro gaming gamepad registers the dpad as joystick axis input, it doesn't work unless I plug the joystick axis into inputs and then both dpad and joystick input works correctly, but only if joystick axis input is added at the same time as the dpad input 

### Steps to reproduce

use vilros retro gaming gamepad and assign a movement input to a kinematic body, assign an input get in the project settings>input map, add D-pad. Doesn't work, works when Joystick axis input is also present

**Comment by Calinou** [comment]
@Titanium-Rat Did you mean to close this issue?

This could be an issue with incorrect controller mappings (which are maintained in [another repository](https://github.com/gabomdq/SDL_GameControllerDB)). I don't see `Vilros` within the [game controller database used by Godot](https://github.com/godotengine/godot/blob/master/core/input/gamecontrollerdb.txt) or the [upstream one](https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt).
