### ISSUE TITLE
Select Physics Body Node Instead of Mesh Node

### ISSUE THREAD

**Issue by toliaferrode** [godotengine/godot#5768]
**Operating system or device - Godot version:**
Any OS, any Godot version

**Issue description** (what happened, and what was expected):
When selecting objects in the editor window to reposition, it selects the mesh node instead of the physics body it's attached to. What you get is the mesh moving and the collision shape node and (I think) physics body (rigidbody, static, etc) node staying behind. The only way to work around this is to select the node in the node list.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by TheoXD** [comment]
That's when you would normally use subscenes.

**Comment by toliaferrode** [comment]
Ah, I see! I think I figured it out last night but then forgot. Thanks.

**Comment by TheoXD** [comment]
Not being able to select instances from 3d viewport is a whole other story, fix is coming though. As a quick workaround you can use this for now https://github.com/TheoXD/godot/commit/6bd73baf1c4397e6bf0e9e123feecf9c807bb41f  if you know how to build from source.

**Comment by toliaferrode** [comment]
Thanks!

**Comment by Calinou** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.
