### ISSUE TITLE
v3.5.beta1: Crash when renaming a BlendSpace1D node

### ISSUE THREAD

**Issue by duianto** [godotengine/godot#57702]
### Godot version

v3.5.beta1.official [b9b23d222]

### System information

Windows 10 21H1

### Issue description

Godot v3.5.beta1.official [b9b23d222] crashes,
when renaming a `BlendSpace1D` node in the `AnimationTree`. 

It doesn't crash in:
v3.4.2.stable.official [45eaa2daf]
v3.4.3.rc1.official [894b6d504]

### Steps to reproduce

- Open the attached project
- In the `Scene dock`
- Open the `Player` scene by clicking on the `Open in Editor` button
- In the `Player` scenes `Scene dock`
- Click on the node: `AnimationTree`
- In the bottom `AnimationTree` dock
- Add a node: `BlendSpace1D`
Either by `right clicking`, or by clicking on the top left button: `Add Node...`
and choosing: `BlendSpace1D`
- Rename the node `BlendSpace1D`,
by clicking on the text `BlendSpace1D`, on the second row, to the left of the white dot.
The cursor starts blinking on the text.
- Modify the name, by erasing, adding or replacing one or more characters.
- Confirm the new name by pressing: `enter`

### Observed
Godot crashes.

### Expected
Godot shouldn't crash.

### Notes
This was discovered by following the tutorial:
Beginner's Crash Course 2D Platformer Game in Godot - Game Development Full Course Free
https://www.youtube.com/watch?v=_EvvU3usZkA

The `BlendSpace1D` node is added at 1 h 27 min 28 sec:
https://youtu.be/_EvvU3usZkA?t=5248

The tutorial author is using Godot 3.3.3, and Godot doesn't crash.

### Minimal reproduction project

[pixel adventure project tutorial.zip](https://github.com/godotengine/godot/files/8010078/pixel.adventure.project.tutorial.zip)

**Comment by duianto** [comment]
If this is the same or related to:
Editor crashed in the BlendSpace2d editing interface #37385

Then it might have been fixed by:
Fix crash when undoing node creation of BlendTree editor #56858

**Comment by akien-mga** [comment]
> Beginner's Crash Course

Seems like you go the behavior that the course is teaching ;)

**Comment by akien-mga** [comment]
I can confirm the crash in 3.5 beta 1, and indeed it doesn't seem reproducible in 3.4.2 or 3.4.3 RC 1.

> If this is the same or related to: Editor crashed in the BlendSpace2d editing interface #37385
> 
> Then it might have been fixed by: Fix crash when undoing node creation of BlendTree editor #56858

That seems correct, at least I can't reproduce the crash anymore in latest `3.x` (e898f931299dde91f0857ae188c7a2b27728ffdf). #37385 seemed to exist in earlier versions too so the specific cause for this crash might be different, but #56858 seems to have fixed both. (CC @timothyqiu)
