### ISSUE TITLE
Godot Mono: Some missing methods of EditorPlugin class 

### ISSUE THREAD

**Issue by erayzesen** [godotengine/godot#57717]
### Godot version

3.4

### System information

Linux (Debian Based)

### Issue description

Some Virtual methods of EditorPlugin are missing.  These are fixed in version 4.0, but they are still missing in 3.x versions. 

Some missing methods; 

_Edit()
_Handless()

### Steps to reproduce

I was working on an EditorPlugin inherited class with Godot Mono. I tried overriding Edit and Handless virtual methods.

These methods in GDScript;
```
func edit(object: Object) -> void:
	print("edit %s" % object.get_path())
	edited_object = object

func handles(object: Object) -> bool:
	return object is MySomeObject
```

**Comment by Calinou** [comment]
Can you reproduce this in GDScript?

**Comment by erayzesen** [comment]
```
func edit(object: Object) -> void:
	print("edit %s" % object.get_path())
	edited_object = object

func handles(object: Object) -> bool:
	# Required to use forward_canvas_draw_... below
	return object is MySomeObject
```

**Comment by raulsntos** [comment]
What do you mean by missing? The C# class `EditorPlugin` contains the virtual methods [`Edit(Godot.Object)`](https://paulloz.github.io/godot-csharp-api/3.4/Godot.EditorPlugin.html#Godot_EditorPlugin_Edit_Godot_Object_) and [`Handles(Godot.Object)`](https://paulloz.github.io/godot-csharp-api/3.4/Godot.EditorPlugin.html#Godot_EditorPlugin_Handles_Godot_Object_) that you can override.

**Comment by erayzesen** [comment]
> 

Thank you @raulsntos , it's working well.  I didn't  find any document about that. I was looking some v4.0 c# plugins to implement these codes. As if some documents related to C # and Godot are missing? Anyway I came for the bug report but my problem is solved and I'm happy.

**Comment by Calinou** [comment]
Closing per the above comment.
