### ISSUE TITLE
CharacterBody2D's Basic Movement script template inconsistently uses delta when calculating velocity

### ISSUE THREAD

**Issue by vesk4000** [godotengine/godot#57713]
### Godot version

4.0.alpha1.official [31a7ddb]

### System information

Windows 10

### Issue description

The `Basic Movement` script template that Godot provides when you create a script which extends `CharacterBody2D` is a pretty good starting point. But for some reason, in it, when adding gravity to the vertical velocity the `delta` is considered, but not when calculating the horizontal velocity. This seems a bit inconsistent and likely not intended.

You can see the inconsistency in these two snippets of code from the `physics_process` function in the template:

```gdscript
if not is_on_floor():
	motion_velocity.y += gravity * delta
```
```gdscript
var direction = Input.get_axis("ui_left", "ui_right")
if direction:
	motion_velocity.x = direction * SPEED
else:
	motion_velocity.x = move_toward(motion_velocity.x, 0, SPEED)
```

Here's the whole template:

```gdscript
extends CharacterBody2D

const SPEED = 300.0
const JUMP_FORCE = -400.0

# Get the gravity from the project settings to be synced with RigidDynamicBody nodes.
var gravity = ProjectSettings.get_setting("physics/2d/default_gravity")


func _physics_process(delta):
	# Add the gravity.
	if not is_on_floor():
		motion_velocity.y += gravity * delta

	# Handle Jump.
	if Input.is_action_just_pressed("ui_accept") and is_on_floor():
		motion_velocity.y = JUMP_FORCE

	# Get the input direction and handle the movement/deceleration.
	# As good practice, you should replace UI actions with custom gameplay actions.
	var direction = Input.get_axis("ui_left", "ui_right")
	if direction:
		motion_velocity.x = direction * SPEED
	else:
		motion_velocity.x = move_toward(motion_velocity.x, 0, SPEED)

	move_and_slide()
```

### Steps to reproduce

![Godot 4 Physics Test GIF 3](https://user-images.githubusercontent.com/30286047/152689750-059e8606-b596-48f6-9ad8-43e46bae58b3.gif)

**Comment by Calinou** [comment]
cc @jmb462

**Comment by jmb462** [comment]
cc @fabriceci ;)

**Comment by jmb462** [comment]
As far as I understand, it should be OK.

``delta`` is applied internaly on velocity in ``move_and_slide``.

As gravity is an acceleration, we need to multiply with ``delta`` to increment velocity.

``velocity`` is per second. ``gravity`` is per second**²**.

Waiting for @fabriceci to confirm.

**Comment by fabriceci** [comment]
It's intentional, there are several different things here, the delta can be something confusing. I'm going to take the meter as the unit of distance, so you have:

- Forces (gravity here), unit is in m/s²
- Velocities, unit is m/s
- Final Distance is m.

To add a force (gravity) to a velocity `motion_velocity`, you need to convert the force by multiplying by the delta. As `move_and_slide` is a high-level function, it takes a velocity, so you can pass `motion_velocity` as is. If you use a low level function like `move_and_collide` which takes now a distance, you will have to multiply it by delta before using it.

**Comment by saharsionov66** [comment]
You screamer in i SENT REPORT
