### ISSUE TITLE
Adding many instances of a sphere-shaped `CSGMeshes` to the tree simultaneously lags engine

### ISSUE THREAD

**Issue by MikeFP** [godotengine/godot#57714]
### Godot version

3.4.2.stable

### System information

Windows 10, GLES3, NVIDIA Geforce GTX 1050

### Issue description

The engine lags when trying to add many spheres (16x8 segments) to the tree in the same frame.

Running the 3.2.2.stable build, I got around 30 FPS when spawning 4 spheres at the same time, and 60+ FPS for 1 sphere at a time.

Running the 3.2.4.stable build, it kept 60 FPS up until 6 spheres spawning at the same time.

I expected that number to be a little bit higher, since the shape is not really that complex and is a shared Resource that shouldn't stutter after instancing it for the first time.

### Steps to reproduce

1. Open the reproduction project
2. Run the main scene
3. Use up and down arrow keys to set how many spheres are added. Test values from 1 to 10.
4. Watch the FPS count

If you want, slow down the Timer so it spawns every 1 second, so the stutter is more visible.

### Minimal reproduction project

[mesh-instance-bug.zip](https://github.com/godotengine/godot/files/8010555/mesh-instance-bug.zip)

**Comment by TheDuriel** [comment]
v3.4.stable.official [206ba70f4]

Can confirm, at exactly 4 instanced meshes per tick an extreme spike is shown in the profilers 'idle time'.

Something OP forgot to mention is that they are using CSGMesh nodes.

A significantly more complex, (default values) MeshInstance Node with a Sphere primitive incurs absolutely no performance drops until I am spawning dozens of instances with thousands already on screen.

So @MikeFP , you're just using the wrong node ;P

**Comment by MikeFP** [comment]
@TheDuriel Yep, that's it, thank you!

I wasn't aware there was a difference between using CSGMeshes and MeshInstances. I just chose the latter because I tend to use CSGMesh primitives for prototyping. What should I use them for? Is that an intended behavior/drawback?

**Comment by TheDuriel** [comment]
https://en.wikipedia.org/wiki/Constructive_solid_geometry It's a level _prototyping_ feature, for additive and subtractive mesh merging and collision generation. It is expected to be slow, and extremely slow when things are in motion.

**Comment by MikeFP** [comment]
Thanks for the info.

My main point of confusion that led to this problem was that, coming from Unity, I expected to be able to instance primitive shapes instantly for prototyping, instead of manually setting the shape each time I wanna add a new mesh. So my mind naturally thought that was why CSGShapes were there.

I should've looked more into it before using it.

I'll close this issue, but maybe we should consider adding a better description of those classes in-engine so other beginners don't make the same mistake. (The online docs are great though, only the editor lacks some critical information).

Also, maybe adding new default Nodes for primitives that extend MeshInstance (like MeshSphere and such) could make prototyping faster.

Anyways, thanks for your help!

**Comment by Zireael07** [comment]
@MikeFP note that you can convert csg meshes to normal meshes once you have the desired shape (I'll link the code once I'm at the computer). But in this case you should be fine with a default sphere mesh instance
