### ISSUE TITLE
High Level Multiplayer API

### ISSUE THREAD

**Issue by enigma101** [godotengine/godot#5771]
I think Godot should have a HLAPI for Networked Multiplayer games.  I just discovered Unity3D has this and it pulled me away from Godot for my current project.  

[Here](https://unity3d.com/learn/tutorials/topics/multiplayer-networking/introduction-simple-multiplayer-example?playlist=29690) is the description of how Unity does it.  

[This](http://spark.tools/powerful-game-engine/#Multiplayer) game engine is trying to make multiplayer development easy too.

**Comment by akien-mga** [comment]
That's on the roadmap for 2.2.

**Comment by enigma101** [comment]
Happy to hear that.  Is there any place that explains how it will be done?  I think the way Spark wants to do it sounds the easiest, just check a check box to get sent over the network.  Will there be a service like Unity has to make internet games public?

**Comment by Qudware** [comment]
Wow 2.2 sounds close, the wait is shorter! May I ask where this roadmap is?

**Comment by akien-mga** [comment]
> May I ask where this roadmap is?

Mostly in our minds, it's evolving quite organically as we discuss things on IRC. We'll define it more precisely when 2.1 is released, to make it clearer what we want to focus on. But basically the idea for 2.2 is networking, audio system rewrite, (potentially) static typing for GDScript, (potentially) Mono/C# support, and a couple other improvements we want to make before the big work on 3.0. It will likely also include a lot of bug fixing and improvements in new features of 2.1 like the new EditorPlugin API and the asset sharing library.

**Comment by paper-pauper** [comment]
@akien-mga 

>  (potentially) Mono/C# support

I have to say that I'm very disappointed that our long discussion in #5081 (in which most of us agreed about C# **not** being a suitable language for Godot) did not persuade the team to discard this idea.

I understand the pressure from people who want Godot to be "even cheaper Unity" is strong, however I feel that time would be better invested elsewhere.

**Comment by akien-mga** [comment]
@paper-pauper Well... Ideas guys VS people doing the job, that's a well known scheme in the open source world. @neikeq is working on C# bindings, so if they work, there's no reason no to propose them, even if there's an impossibly long discussion about the cons of using it.

**Comment by Qudware** [comment]
Some people would just write C# for the sake of doing so, out of love (I'd know...).

**Comment by bojidar-bg** [comment]
Hm, I think this issue is closable (in 2.2-legacy and master), correct?

**Comment by akien-mga** [comment]
Indeed :)
