### ISSUE TITLE
SpriteFrames cursor disappears when trying to add sprite and crashes when loading TileSet

### ISSUE THREAD

**Issue by MateusMP** [godotengine/godot#57724]
### Godot version

v4.0.alpha1.official [31a7ddbf8]

### System information

Windows 10, Vulkan API 1.2.182, NVIDIA GeForce RTX 2060

### Issue description

When trying to create an animation in a SpriteFrames resources, I opened an image and when changing vertical/horizontal sizes, the mouse cursor disappears. Godot is still responsive as I can edit the value with my keyboard and see it cut the image accordingly. However, I can not get my cursor back and it is impossible to find my way out of that screen.

Also, I am not sure if I am supposed to be able to load a TileSet, but selecting one will crash without errors in the console. 

### Steps to reproduce

1. Open project attached
2. Open laser_bullet.tres
3. Select the default animation and try to add a new sprite using "Add Frames from a Sprite Sheet"
4. Select sheet.png
5. Try to fiddle with the horizontal/vertical numbers (clicking on the arrows to increase/decrease). The mouse will eventually disappear randomly. I could not find an exact pattern here. Clicking up arrow for horizontal 5 times then down 5 times usually does it for me.

Alternatively, in step 4, select tileset.tres to see it crashing.

### Minimal reproduction project

[BugSheet.zip](https://github.com/godotengine/godot/files/8011084/BugSheet.zip)

**Comment by Calinou** [comment]
cc @groud

**Comment by KoBeWi** [comment]
The other issue sounds the same as #46433
