### ISSUE TITLE
ItemList return index if select empty space.

### ISSUE THREAD

**Issue by alexolin** [godotengine/godot#5772]
Win 10 - Godot 2.1 beta

Bug in ItemList.  ItemList return index if select empty space in itemlist.
Example project in attach.
Gif attached.

[itemlist.zip](https://github.com/godotengine/godot/files/368949/itemlist.zip)
![itemlist](https://cloud.githubusercontent.com/assets/15943158/16914149/82370c1c-4cf8-11e6-8b72-30710324b143.gif)

**Comment by akien-mga** [comment]
I cherry-picked the commit manually and pushed it in your name ;)
I also removed the unused `closest_dist` variable as seen in #5857.
