### ISSUE TITLE
Cannot use any image in new project

### ISSUE THREAD

**Issue by markdibarry** [godotengine/godot#57730]
### Godot version

4.0 dev (9d1626b)

### System information

Windows 10

### Issue description

After creating a new project, all images added to the project (including `icon.png`) are displayed in binary colors and are unable to be added to any node that accepts an image for a texture via drag and drop. If manually added the following error displays:
![image](https://user-images.githubusercontent.com/21325943/152705266-3546f57f-de22-4389-b71b-5bebf657a5a8.png)

### Steps to reproduce

Create new project.
Add Sprite2D.
Try to add `icon.png` as texture.

**Comment by KoBeWi** [comment]
Looks like textures are imported as BitMap by default.

**Comment by Sauermann** [comment]
I can confirm, that this was introduced in bd32dd4a48ba0008dc72c8dcd75f8d41bc510aba.

**Comment by akien-mga** [comment]
CC @fire. That PR inverted the order of priority of all existing importers, all `add_importer| calls would need to be reordered.
