### ISSUE TITLE
New TileSet editor: set_tile doesn't seem to work as documented

### ISSUE THREAD

**Issue by ryanscottcausecast** [godotengine/godot#57733]
### Godot version

4.0alpha

### System information

mac book pro

### Issue description

only seems to write NULL into the map.

### Steps to reproduce

I have included a project that demonstrates this.  

### Minimal reproduction project

[tile_set issue.zip](https://github.com/godotengine/godot/files/8028966/tile_set.issue.zip)

**Comment by groud** [comment]
It would be a little bit more useful to give more details about your issue (like, your scenesetup, your code, etc...)
Also, your MRP is not a valid one, it has no project.godot and it's won't load anyway as it is missing the tiles.png picture.
Please update the MRP.

**Comment by groud** [comment]
I'll close this issue as it's not workable in it's current state. I'll re-open once the MRP is updated.

**Comment by ryanscottcausecast** [comment]
I have updated with a complete project.

**Comment by Ev01** [comment]
Seems to be a duplicate of #57833
