### ISSUE TITLE
Slider "step" property is only partially implemented

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#5773]
The HSlider/VSlider "step" property seems to be only partially implemented. It will work when the user clicks and scrolls mouse wheel at the same time, but won't lock normal mouse sliding to the step values (which makes it quite useless).

It's implemented in **scene/gui/slider.cpp**, starting from line **44**.

**Comment by lordadamson** [comment]
I think it is kind of intended to be this way?
Maybe there should be a property that decides whether it should have discrete values or continuous values?
