### ISSUE TITLE
Resizing a DynamicFont by code can corrupt it

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#5774]
**Operating system or device - Godot version:** Windows 10, Godot 2.1 https://github.com/godotengine/godot/commit/c328693e837f5899b24504caef5a9ee5e4d4cb4e, self-compiled with Visual Studio 2015 Update 2

**Issue description** (what happened, and what was expected): When resizing a DynamicFont by code, it can get corrupt. This was tested with a DynamicFont as a theme's default font.

**Steps to reproduce:** Resize a DynamicFont from code.

**Link to minimal example project** (optional but very welcome): [dpi_scaling.zip](https://github.com/godotengine/godot/files/369030/dpi_scaling.zip) - Use the slider at the top left of the screen to change the GUI scale.

**Comment by reduz** [comment]
call update_changes() after doing changes to a font and it will update it
