### ISSUE TITLE
Control scaling should be relative to the anchor

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#5775]
The scaling of Controls should probably be relative to the anchor. For example, if you set an anchor at Bottom Right, the scaling should operate starting from the bottom left of the screen, not from the Top Left.

Here's an example project which would benefit from this feature: [dpi_scaling.zip](https://github.com/godotengine/godot/files/369036/dpi_scaling.zip)

**Comment by reduz** [comment]
Anchors are meant to be simple, just use containers for these cases

**Comment by vnen** [comment]
This is the same as #2965, right?

**Comment by bojidar-bg** [comment]
@vnen Not really, this is for _scale_, the other is for _size_.

**Comment by Gfurst** [comment]
no, this is exactly the same issue, both as #2965 and #4339 

its not about size or scaling, its that whenever a node changes its size, for whatever reason it may be, it always grows to bottom-right side (or shrinks opposite), regardless of what its anchoring may be, misplacing its expect position

**Comment by reduz** [comment]
This was just fixed, you can change the grow direction of controls now
