### ISSUE TITLE
[4.0] Items and their IMPORT files are making duplicates in file browser

### ISSUE THREAD

**Issue by ArseniyMirniy** [godotengine/godot#57755]
### Godot version

4.0 Alpha 1

### System information

Windows 10

### Issue description

![image](https://user-images.githubusercontent.com/19660324/152793195-4f5e14a4-bd69-4ef7-9226-9674f82cf7d7.png)

Importing models (FBX, OBJ or DAE – doesn't matter) started to cause duplicated entries in the editor (mostly the file browser). It makes impossible to delete them properly up to a full crash of Godot 4 editor or it will brake all scenes, where they've been used.

Then importing other files caused the same issue.

### Steps to reproduce

I was just trying to import the house model to setup shadows properly.
Nothing too special about it.

### Minimal reproduction project

[Godot 4 Import Bug.zip](https://github.com/godotengine/godot/files/8015444/Godot.4.Import.Bug.zip)

**Comment by Rinocrosser** [comment]
The project I've added is just a house walls OBJ, textures from the screenshot are not uploaded, but you can try to add any texture and see, if the issue will be reproduced. If not, I can add a smaller textures version.

**Comment by and-rad** [comment]
This looks very similar to the duplication-on-import bug that #55373 is fixing, see #53871 for a bit of discussion on this. Might be worth a shot to see if that PR fixes all of these.

**Comment by fire** [comment]
I haven't seen this bug for a while now.

**Comment by clayjohn** [comment]
Can anybody still reproduce this issue?

**Comment by aaronfranke** [comment]
No response for over a year, and the related issues https://github.com/godotengine/godot/issues/53871, https://github.com/godotengine/godot/issues/54774, and https://github.com/godotengine/godot/issues/57225 are fixed, by PR #73214, so closing this issue and assuming it is fixed as well.
