### ISSUE TITLE
Can't remove class type from theme

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#57758]
### Godot version

v3.4.2.stable.official [45eaa2daf]

### System information

Any

### Issue description

I can add class items to the theme manager, but can't seem to find a way to remove them (although I can remove all style changes for that style).

This eventually leads to everything being loaded in the style even if I just wanted to try something out.

### Steps to reproduce

1. Create a theme
2. Add a object class to the theme

**Comment by Calinou** [comment]
cc @pycbouh @YeldhamDev

**Comment by YeldhamDev** [comment]
Empty theme class types don't really "exist" to Godot, so once the editor is restarted, they will vanish. However, I can see it would be confusing.

**Comment by tavurth** [comment]
Perhaps just clipping the label length would be enough in that case?

I like the way in some areas of Godot there is a warning triangle, perhaps it's too much if the auto-delete is in place anyway.

**Comment by pycbouh** [comment]
> Empty theme class types don't really "exist" to Godot, so once the editor is restarted, they will vanish. However, I can see it would be confusing.

For the record, I had a reason to keep it this way despite poor UX, but I can't recall what it was and people ask about this all the time, so having a button to explicitly remove the type (via the manage item dialog) is on my TODO list already.

> Perhaps just clipping the label length would be enough in that case?

In 3.5 and master the UX of the dialog was improved to indicate better what the user can do in there (https://github.com/godotengine/godot/pull/55927), but I think it's a bit unreasonable to consider entering Lorem Ipsum in there as a valid case 🙃 

Not sure if OptionButton can clip its label, but if it can, we sure can enable it. It's just not that important under any normal circumstance.

**Comment by tavurth** [comment]
@pycbouh maybe we should leave this open until it's fixed in 3.4.2, or this is not possible to cherrypick back?

**Comment by pycbouh** [comment]
It's not possible to cherry-pick, and it won't be a part of 3.4.x, but I'll make a dedicated 3.x PR once type variations are merged. I could do it now, but I don't want the code to get messy.
