### ISSUE TITLE
New TileMap Editor: deleting the last layer crashes Godot

### ISSUE THREAD

**Issue by ryanscottcausecast** [godotengine/godot#57763]
### Godot version

4.0 alpha1

### System information

mac book pro 2017

### Issue description

The video demonstrates the problem.

Create new tilemap layer, try to remove that last layer, godot crashes.  Was able to reproduce it multiple times.

### Steps to reproduce

Create new tilemap layer, try to remove that last layer, godot crashes.

**Comment by ryanscottcausecast** [comment]
here's a video showing it
https://youtu.be/xW3FwroldDA

**Comment by Calinou** [comment]
cc @groud

**Comment by groud** [comment]
Please provide a minimal reproduction project, I cannot reproduce this on my side:

https://user-images.githubusercontent.com/6093119/152830950-8e734abf-942f-4244-8b17-b8850b09ac3d.mp4

**Comment by KoBeWi** [comment]
Also can't reproduce. Comment with MRP if it still happens in alpha 7+.
