### ISSUE TITLE
Add an extra stretch mode for a "safe zone" on mobiles

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#5776]
As mentioned by @reduz in #4134:

> How about instead of changing keep, which I believe what it does is right, we add an extra stretch mode that does this? It shouldn't be too hard..
> like keep / keep_width / keep_heigh / keep_safe_zone or something else?

**Comment by bojidar-bg** [comment]
If someone gives a reference to an exact algorithm, or pastes a simple psuedocode, I might be happy to work on that one :smile:

**Comment by Calinou** [comment]
Godot 3.0 now has an `expand` aspect scaling mode and TextureRects have a "Cover" property (which scales an image in the best possible way to cover the defined rectangle). Are these enough to cover the functionality proposed in this feature request?

**Comment by bojidar-bg** [comment]
Well, no, since this issue is about the main Viewport, and not TextureRects.

That being said, one can use a TextureRect/ViewportContainer + Viewport to customize the margin positioning.

**Comment by bojidar-bg** [comment]
Actually, isn't this fixed by #10198?

**Comment by Calinou** [comment]
> Actually, isn't this fixed by #10198?

That's the scaling mode I mentioned in my comment. :smiley:

**Comment by aaronfranke** [comment]
Judging by the images in https://github.com/godotengine/godot/pull/4134#issuecomment-200566810, I think this is solved already. If there's something missing that I'm not seeing, we can always continue the discussion and re-open this issue.
