### ISSUE TITLE
AnimationTree, Blend3, Non-looping animation only updates when Godot loses focus

### ISSUE THREAD

**Issue by duianto** [godotengine/godot#57765]
### Godot version

v3.5.beta1.official [b9b23d222], v3.4.3.rc1.official [894b6d5], v3.4.2.stable.official [45eaa2daf]

### System information

Windows 10 21H1

### Issue description

The 2d editor doesn't update to show an animation until Godot loses focus
when dragging a `Blend3` node slider, to an animation that has `Animation Looping` disabled.
In the `AnimationTree dock`.

### Steps to reproduce

- Open the attached project
- In the `Scene dock`, open the `Player` scene
The 2D editor shows the frogs `jump` animation (a single frame) (arms down, front leg up)
- Select the `AnimationTree` node
The `AnimationTree dock` (at the bottom of Godot), only shows the `Blend3` and `Output` nodes on the left side.
- Middle mouse drag to the right, to pan all 5 nodes into view.
- At the bottom of the `Blend3` node, drag the Slider to the right.
When the value is:
  - Greater than `-1` and less than `0`: then it shows the `idle` animation (multiple frames).
  - Greater than `0` and less than `1`: then it flickers quickly between `idle` and `fall`.
  - At `1`:  it shows the `fall` (single frame) animation (arms up, back leg up).

- Drag the slider to the left,

Between `1` and `0`,  it flickers quickly between the `fall` and `idle` animations.
At `0` or greater than `-1`: it shows the `idle` animation.

At `-1`. (the initial position, when the project was first opened)

### Observed

The `idle` animation still plays.

### Expected

The `jump` animation should play.

### Workaround

The `jump` animation is shown, when Godot loses focus.
(when switching to another application: `Alt Tab` or by mouse clicking)

https://user-images.githubusercontent.com/13420573/152838251-b1039cfd-568c-43a3-968d-66af811a182b.mp4

### Cause

The `Blend3` node seems to only show looping animations before Godot loses focus.

This was discovered by changing the animation in the `AnimationTree dock`'s `Animation` node.

https://user-images.githubusercontent.com/13420573/152836005-363ff43c-cb24-42ef-873d-8acb3871f623.mp4

Every other animation plays (`fall`, `idle`, and `run`) in the 2d editor.
The previous animation continues to play when `hit` and `jump` are chosen.

The `hit` and `jump` animations only play when Godot loses focus.

In the `Scene dock`.
Selecting the `AnimationPlayer` node, opens the `Animation dock`.
And switching between the animations, shows that `Animation looping` is
enabled for the animations: `fall`, `idle` and `run`

### Minimal reproduction project

[pixel adventure project tutorial.zip](https://github.com/godotengine/godot/files/8017346/pixel.adventure.project.tutorial.zip)

**Comment by Calinou** [comment]
Can you reproduce this after enabling **Update Continuously** in the Editor Settings?

**Comment by duianto** [comment]
With `Update Continuously` enabled.
It still doesn't update when dragging the slider to `-1`.

But now it changed:
From: Updating when Godot loses focus.
To: Updating when Godot becomes focused (`Alt Tab` twice).

**Comment by TokageItLab** [comment]
I took a look at your project, and I don't think this is a bug.

AnimationTree is blending the animation, which is setting the "Animation parameter" of AnimationSprite. Also, if I look at the Animations in AnimationPlayer, the interpolation mode is set to Discrete, so the animation will not update unless it steps over a key.

How about setting the Animation's interpolation mode to Continuous?

![スクリーンショット 2022-02-08 6 16 05](https://user-images.githubusercontent.com/61938263/152873778-4216bf17-c581-4a3d-a1cb-d7cf3f21d967.png)

**Comment by duianto** [comment]
>the interpolation mode is set to Discrete, so the animation will not update unless it steps over a key.

Ok, that's why dragging the `Blend3` node slider to `-1` doesn't update the Animation in the 2D editor.

The `AnimationTree`, `Animation` node's progress bar never runs.
It's always shown as full.

When the `Animation Looping` is enabled on the `jump` animation.
Then the `AnimationTree`, `Animation` node's progress bar keeps looping,
when the `Blend3` slider is dragged to `-1`.

>How about setting the Animation's interpolation mode to Continuous?

The `jump` animation does update now.

Thanks

---

This "issue" was discovered while following this tutorial:
Beginner's Crash Course 2D Platformer Game in Godot - Game Development Full Course Free
https://www.youtube.com/watch?v=_EvvU3usZkA

The Animations are added at 1h 11m 54s
https://youtu.be/_EvvU3usZkA?t=4314

The tutorial author does set up all animations with `Animation Looping` enabled.
I just missed that part and forgot to enable them on the two animations `hit` and `jump`.

The `AnimationTree` nodes are added,
and the `Blend3` slider is dragged at 1h 40m
https://youtu.be/_EvvU3usZkA?t=5999

It's probably only a small fraction of the people that watch the tutorial,
that makes the same mistake as I did.

But now this thread has the explanation.

---

The other issue is that the animation does update when:
Godot loses focus (with `Update Continuously` disabled)
Godot becomes focused (with `Update Continuously` enabled)

Maybe Godot checks and draws/updates the animation,
based on the `Blend3` node's current slider value,
when Godot loses/gains focus.
