### ISSUE TITLE
Inconsistent capitalization of default scene file names

### ISSUE THREAD

**Issue by jmdejong** [godotengine/godot#57768]
### Godot version

Godot_v4.0-alpha1_linux.64

### System information

recently updated arch linux

### Issue description

When saving a new scene for the first time the default name (without extension) is the name of the root node of that scene but starting with a lowercase letter (even when the root node starts with an uppercase letter).

When saving a branch as a scene and the root of that branch starts with an uppercase letter, the default filename is the name of that branch root as it is, so with an uppercase letter.

I would expect the proposed default filename to be more consistent

### Steps to reproduce

- Create a new project
- Create a root node called `Main`
- Save this scene. It will show `main.tscn` as default filename
- Create a child node called `Player`
- Save the Player branch as a scene. It will show `Player.tscn` as default filename.

**Comment by Calinou** [comment]
cc @KoBeWi

**Comment by KoBeWi** [comment]
The option to change default casing was added in #52597
Seems like it's just not applied in all *cases*.

**Comment by keptsecret** [comment]
Hi, I'm new and I'd like to try working on this.  
I've had a look and it looks like the enum used for the cases is `private` in `editor_node.h`.  
Would making it `public` be a good idea?

**Comment by Calinou** [comment]
> Would making it public be a good idea?

Making the enum public sounds fine to fine.

**Comment by dmaz** [comment]
It would be nice that while fixing this you could also make it respect the choice in Project Settings...  master currently doesn't and just defaults to snake case even if you choose one of the other 2 options

**Comment by ryburnj** [comment]
Hey, new to the scene and I'm just trying to understand. 
In keeping with what's outlined in the docs, we want ALL scene tree nodes' file names to be snake case?
