### ISSUE TITLE
`FileDialog` opens the wrong folder if directory is created at runtime

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#57777]
### Godot version

v3.4.2.stable.official [45eaa2daf]

### System information

Mac OSX (any export)

### Issue description

When creating a directory at runtime, and having the `FileDialog` specify that subdirectory, the `FileDialog` fails and instead lists the users home directory.

### Steps to reproduce

```gdscript
func ensure_directory():
	var dir = Directory.new()
	dir.open("user://")
	dir.make_dir("somedirectory")

func _ready():
        ensure_directory()
```

While also having the `FileDialog` point to the `somedirectory`

**Comment by akien-mga** [comment]
Can you provide a reproduction project? The actual issue is not clear to me from the snippet, this is just creating a folder in `user://`, there's no FileDialog involved.

**Comment by tavurth** [comment]
@akien-mga Yep will do as soon as I've finished up my current flow

**Comment by tavurth** [comment]
@Calinou @akien-mga You can find the example project here:

[godot-file-dialog.zip](https://github.com/godotengine/godot/files/8019441/godot-file-dialog.zip)

This uses this [uuid repo](https://github.com/binogure-studio/godot-uuid) to create a random directory.
It then sets the `current_dir` and `current_path` to that directory.

When you click the button it will open to `res://`

**Comment by timothyqiu** [comment]
@tavurth Make sure to set your `FileDialog`'s `Access` property to `User data` in the Inspector, or use `$FileDialog.access = FileDialog.ACCESS_USERDATA` in code.

**Comment by tavurth** [comment]
@timothyqiu Thank you I missed that in the sample above.

Strange that it was not working in my project however, OK I will close this until I find a way to reproduce it.
