### ISSUE TITLE
InputEventMouseMotion does not work until the window is switched, dragged or resized

### ISSUE THREAD

**Issue by jmdejong** [godotengine/godot#57770]
### Godot version

4.0 alpha1

### System information

Recently updated archlinux, xfce4 desktop, Vulkan API 1.2.203, AMD RADV OLAND
Also tested on cinnamon desktop

### Issue description

When I start a new scene and move the mouse around in the scene I do not get InputEventMouseMotion events.
Clicking or keypresses are registered, but do not change anything.

If I select a different window and then alt-tab back to the game window then I do get InputEventMouseMotion events.
Dragging or resizing the window fixes the problem too.

### Steps to reproduce

- Open the Minimal reproduction project
- Move the mouse around over the window. Maybe even click sometimes
- Check the output of the prints. On my machine it does not show any InputEvenMouseMotions.

### Minimal reproduction project

https://github.com/jmdejong/godot4_alpha_InputEventMouseMotion

**Comment by Sauermann** [comment]
This has been solved in #56548.
