### ISSUE TITLE
Converting scene from 3.x to 4 causes animations to stop looping

### ISSUE THREAD

**Issue by rakkarage** [godotengine/godot#57779]
### Godot version

v4.0.alpha1.official [31a7ddbf8]

### System information

Windows 10

### Issue description

Sprite2D Animations working and looping in 3 stop looping when the containing scene converted to 4

### Steps to reproduce

- checkout reproduction project godot4 branch: `git clone --branch godot4 https://github.com/rakkarage/TestAnimationTree3`
- open project in Godot 4 and save AnimationNew.tscn to trigger conversion (all the other conversions have already been done)
- note idle animations are not looping,
- look at diff to see that looping options were removed, among other changes

### Minimal reproduction project

`git clone --branch godot4 https://github.com/rakkarage/TestAnimationTree3`

**Comment by TokageItLab** [comment]
See https://github.com/godotengine/godot/pull/51950#issuecomment-966032252.

**Comment by Owl-A** [comment]
I'd like to work on this one but I'm unsure where to start. Any help will be much appreciated.

**Comment by rakkarage** [comment]
https://github.com/rakkarage/TestAnimationLoopConvert
- Here is a simple looping animation I made in 3.x.
- When open in 4.x stops looping.

**Comment by Owl-A** [comment]
I get the issue, but I'm not able to track down where in the code-base this problem arises. I looked at the resource import code, but that seems to be alright; I also looked under scene/animation and it seems to be okay as well. Please guide me where in the code-base I should look
