### ISSUE TITLE
follow_focus and ensure_control_visible does not work on scaled scrollcontainer

### ISSUE THREAD

**Issue by elMuso** [godotengine/godot#57778]
### Godot version

3.4.2 stable official [45eaa2eaf]

### System information

Windows 10, Intel HD 4600 OpenGL ES 3.0

### Issue description

So this one has been bugging me, i have some scrollcontainers  that were not following focus, or they were but they went outside the screen to do it.

The problem was that probably scale was not taken up in consideration when calculating the position and visibility of the control node. Everything works fine when the scrollcontainer scale is 1:1

### Steps to reproduce

*Make a scrollcontainer with scale x,y different than 1 and enable autofocus on it
*Populate it with buttons
*Run, and try to go up/down with the up down keys
*everything is offset

**Comment by KoBeWi** [comment]
Control nodes generally don't work well when scaled.

**Comment by Calinou** [comment]
> Control nodes generally don't work well when scaled.

For context, it's better to rely on stretch modes to support [multiple resolutions](https://docs.godotengine.org/en/stable/tutorials/viewports/multiple_resolutions.html) compared to using Control scaling. Control scaling should be reserved for animation purposes, and not for "permanent" effects.

**Comment by elMuso** [comment]
Yes i agree, however i'm in a particular situation.  The font that i want to use only allows the use for rasterized images, which can be translated to bitmapfonts without breaking the license. So to change font size i have to use scale for labels, buttons, etc. 
But yeah, it seems like a personal issue that can be solved with some gdscript. Closing
