### ISSUE TITLE
Scaling3D, MSAA, and other Viewport properties have no effect on macOS

### ISSUE THREAD

**Issue by cybereality** [godotengine/godot#57784]
### Godot version

v4.0.alpha1.official [31a7ddbf8]

### System information

Apple M1 macOS 12.1

### Issue description

Changing the viewport properties directly on the root viewport have no affect on macOS in Godot 4.0.

This code works on Windows and Linux, but does nothing on Mac:
~~~
var viewport = get_viewport()
viewport.msaa = Viewport.MSAA_4X
viewport.scaling_3d_scale = 0.25
~~~
This is the work around I found that works on all operating systems:
~~~
var id = get_viewport().get_viewport_rid()
RenderingServer.viewport_set_msaa(id, Viewport.MSAA_4X)
RenderingServer.viewport_set_scaling_3d_scale(id, 0.25)
~~~

### Steps to reproduce

Use the code I posted above or download the project below. Just play the project on macOS and see the viewport looks normal (no scaling or MSAA) but works fine on Windows and Linux.

### Minimal reproduction project

[MacScaling.zip](https://github.com/godotengine/godot/files/8020583/MacScaling.zip)

**Comment by cybereality** [comment]
Wait, I'm sorry. I just double checked on macOS and it seems my reproduction project does in fact work. But that same code I posted did not work before in my main project and I'm sure it was broken only on Mac (meaning working on Windows and Linux so not a mistake in my code). However, there must have been some additional contributing factor, I will see if I can figure it out.

**Comment by cybereality** [comment]
[MacScaleGI.zip](https://github.com/godotengine/godot/files/8020811/MacScaleGI.zip)

Okay, so I attached a new project. It appears to have something to do with SDFGI, SSIL, or some combination of the two. The code works fine normally. But if you add a WorldEnvironment node and then enable SDFGI and SSIL (or maybe just SSIL) then the scaling stops working. However, it is not consistently reproducible. In the project I uploaded, it happen a few times, then I tried like 10 more times and it worked, without changing any code (just enabling or disabling SDFGI or SSIL). Seems to be some race condition, I'm not sure.

**Comment by Calinou** [comment]
MSAA works on macOS when I last tried it ([only up to 4×](https://github.com/godotengine/godot/issues/56233)), but I didn't couple it with scaling options.

**Comment by cybereality** [comment]
Yes, MSAA works, by itself, on Mac. The issue is that somehow either SSIL or SDFGI block the Viewport properties from working. I only needed msaa, screen_space_aa, and scaling_3d_scale, but it's possible other properties are broken as well. Once you get into this state, you are no longer able to change these properties directly through the viewport, nothing happens. However, changing them through RenderingServer still works.

**Comment by Calinou** [comment]
@cybereality Can you still reproduce this in [4.0.beta1](https://godotengine.org/article/dev-snapshot-godot-4-0-beta-1)?

**Comment by cybereality** [comment]
I can confirm this is no longer an issue on 4.0 beta.
