### ISSUE TITLE
Fullscreen mode cannot be toggled off

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#57787]
### Godot version

26facc054331f8810dba0c040f730111d2b27899

### System information

Windows 10

### Issue description

After the editor screen entered to the fullscreen it cannot be turned back to windowed mode - it just flickers and become fullscreen again:

![fullscreen_bug](https://user-images.githubusercontent.com/3036176/152940486-16ea535e-7637-4aa4-8eb7-d6c4cc46bd17.gif)

This problem affects a debugged project as well.

### Steps to reproduce

Toggle fullscreen in the editor on the current master (26facc054331f8810dba0c040f730111d2b27899). It's a recent regression - it works correctly on Alpha 1.

**Comment by Sauermann** [comment]
On Debian 11 + Xfce, the symptoms are a bit different.
When leaving fullscreen (Shift-F11), the window-borders do not reappear.

**Comment by bruvzg** [comment]
Seems like regression from #54645, seems like this check is not always working:
https://github.com/godotengine/godot/blob/0154ce2c8d66528d617e10b139640fd4c4405c6b/platform/windows/display_server_windows.cpp#L2738-L2740

**Comment by bruvzg** [comment]
#57790 - fix for Windows.

> On Debian 11 + Xfce, the symptoms are the same.

Should be a completely unrelated issue, was it working in alpha 1?

**Comment by Sauermann** [comment]
> Should be a completely unrelated issue, was it working in alpha 1?

You are right. It was not working on Linux in alpha 1. There is already a bug report for that: #55109

**Comment by bruvzg** [comment]
Fix for Linux/X11 - #57794, #55109 is not entirely the same issue, at least part about maximized windows behavior is probably unrelated.
