### ISSUE TITLE
Weird bug with custom resources and duplicated scenes

### ISSUE THREAD

**Issue by Kittenhunter** [godotengine/godot#57803]
### Godot version

4.0 alpha 1

### System information

Windows 10

### Issue description

I'm working on a RPG type of game with some heavy use of Custom Resources (extending "Resource" with a script).
When I'm changing changing the Weapon Scene and Entity Scene to load, then it isn't actually changing the result even if it says so. (Hard to describe)

In the minimal reproduction project I've a structure like:
Entity.gd (Resource)
-> box: Resource

Box.gd (Resource)
-> object: PackedScene

In the main scene, I have a nodes which the same script. The script takes an Entity through @export and instantiates the object of the box of the entity.

I've 2 entities: Player and Enemy
I've 3 boxes: BoxGreen, BoxRed, BoxBlue, BoxPink
And 5 box objects: BoxGreen, BoxRed, BoxBlue (duplicate of BoxGreen and resources made unique), BoxPink and BoxBlue2

### Steps to reproduce

1. Run the project
2. You should see a green and a red box
3. Close the game
4. Open /resources/entities/Player.tres
5. Drag and drop the Resource /resources/boxes/BoxBlue.tres into the "Box" inspector field
6. Run the project
7. You should STILL see a green and a red box, even though you just changed the player box (left) to blue [BUG]
8. Close the game
9. Open /resources/boxes/BoxBlue.tres
10. "Object" field should be BoxGreen
11. Change the "Object" field to /objects/BoxBlue.tscn
12. Run the project
13. You should STILL see a green and a red box [BUG]
14. Re-open the project or use the menu entry Project->Reload Current Project
15. Open /resources/boxes/BoxBlue.tres
16. "Object" field should be BoxGreen [BUG]

Every other box should work, since /objects/BoxBlue.tscn is the ONLY scene which has been duplicated from the BoxGreen.tscn.
If you open BoxBlue.tscn the box is actually blue.

If you look in the remote debugger and select /root/Bug/EntityLoaderPlayer and open Entity/Box in the inspector, you actually see a BLUE box.

### Minimal reproduction project

[ResourceBug.zip](https://github.com/godotengine/godot/files/8024218/ResourceBug.zip)

**Comment by KoBeWi** [comment]
Your green box and blue box have the same UID, see #54774
You can fix this by editing the tscn file and changing the uid in the first line.
