### ISSUE TITLE
Android export error, Execution failed for task ':mergeReleaseNativeLibs'.

### ISSUE THREAD

**Issue by Rodrigo-P-Nascimento** [godotengine/godot#57814]
### Godot version

3.4 stable

### System information

Windows 10, ryzen 5 3500u

### Issue description

 Task :preBuild UP-TO-DATE
> Task :preReleaseBuild UP-TO-DATE
> Task :writeReleaseApplicationId UP-TO-DATE
> Task :analyticsRecordingRelease
> Task :assetPacks:installTime:generateAssetPackManifest UP-TO-DATE
> Task :processReleaseAssetPackManifests UP-TO-DATE
> Task :linkReleaseManifestForAssetPacks UP-TO-DATE
> Task :assetPackReleasePreBundleTask UP-TO-DATE
> Task :compileReleaseRenderscript NO-SOURCE
> Task :generateReleaseResValues UP-TO-DATE
> Task :generateReleaseResources UP-TO-DATE
> Task :mergeReleaseResources UP-TO-DATE
> Task :createReleaseCompatibleScreenManifests UP-TO-DATE
> Task :extractDeepLinksRelease UP-TO-DATE
> Task :processReleaseMainManifest
> Task :processReleaseManifest
> Task :processApplicationManifestReleaseForBundle
> Task :checkReleaseDuplicateClasses UP-TO-DATE
> Task :compileReleaseAidl NO-SOURCE
> Task :generateReleaseBuildConfig UP-TO-DATE
> Task :javaPreCompileRelease UP-TO-DATE
> Task :checkReleaseAarMetadata UP-TO-DATE
> Task :desugarReleaseFileDependencies UP-TO-DATE
> Task :mergeExtDexRelease UP-TO-DATE
> Task :mergeReleaseShaders UP-TO-DATE
> Task :compileReleaseShaders NO-SOURCE
> Task :generateReleaseAssets UP-TO-DATE
> Task :mergeReleaseAssets UP-TO-DATE
> Task :processReleaseJavaRes NO-SOURCE
> Task :mergeReleaseJavaResource UP-TO-DATE
> Task :mergeReleaseJniLibFolders UP-TO-DATE
> Task :mergeReleaseArtProfile UP-TO-DATE
> Task :collectReleaseDependencies UP-TO-DATE
> Task :configureReleaseDependencies UP-TO-DATE
> Task :parseReleaseIntegrityConfig UP-TO-DATE
> Task :writeReleaseAppMetadata UP-TO-DATE
> Task :validateSigningRelease UP-TO-DATE
> Task :processReleaseManifestForPackage
> Task :bundleReleaseResources
> Task :processReleaseResources
> Task :compileReleaseJavaWithJavac
> Task :dexBuilderRelease
> Task :mergeDexRelease
> Task :compileReleaseArtProfile
> Task :mergeReleaseNativeLibs
> Task :mergeReleaseNativeLibs FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mergeReleaseNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeNativeLibsTask$MergeNativeLibsTaskWorkAction
   > Erro nos dados (verificas FAILED

### Steps to reproduce

I was able to export normally, but now I have this error.
I'm working on a game, so I can't put any code snippets here.

**Comment by Calinou** [comment]
@Rodrigo-P-Nascimento Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

Which Java and Android SDK versions are you using?

**Comment by Rodrigo-P-Nascimento** [comment]
> @Rodrigo-P-Nascimento Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.
> 
> Which Java and Android SDK versions are you using? Where did you install them from?

**Comment by m4gr3d** [comment]
Closing due to lack of response.
