### ISSUE TITLE
SpriteFrame Animations UI doesn't have duplicate nor context menu

### ISSUE THREAD

**Issue by RefinedSoftwareLLC** [godotengine/godot#57823]
### Godot version

3.4.2

### System information

Linux

### Issue description

Edit the "SpriteFrames" of an AnimatedSprite.
![image](https://user-images.githubusercontent.com/3934352/153078889-0454d6ff-c949-4128-9c70-1e412e7ce939.png)
Above the animations are buttons for [New Animation] and [Remove Animation] but it is missing a [Duplicate Animation]
Right clicking an animation, doesn't bring up a context menu.
The context menu should at least list [Duplicate Animation] and [Remove Animation].

### Steps to reproduce

Edit the "SpriteFrames" of an AnimatedSprite and try to open the right click context menu on an Animation.
![image](https://user-images.githubusercontent.com/3934352/153078889-0454d6ff-c949-4128-9c70-1e412e7ce939.png)

**Comment by Calinou** [comment]
Closing, as feature proposals should be discussed on the [Godot proposals](https://github.com/godotengine/godot-proposals) repository. This repository is now used for bug reports only.

Make sure to follow the proposal template when opening a new proposal – don't just copy and paste the text you wrote in this issue.

**Comment by RefinedSoftwareLLC** [comment]
In the Scene Tab, you can right click a node to get a context menu with a Duplicate option.
In the FileSystem Tab, you can right click a file to get a context menu with a Duplicate... option.
In the Animations Tab for AnimatedSprite, you can not right click an animation to get a context menu with a Duplicate option.

I disagree that this is a feature request but I will post it there.
