### ISSUE TITLE
New TileSet editor: set_tile only writes NULL

### ISSUE THREAD

**Issue by ryanscottcausecast** [godotengine/godot#57833]
### Godot version

4.0 dev

### System information

2017 macbook pro

### Issue description

Godot version
4.0alpha

System information
mac book pro

Issue description
only seems to write NULL into the map.

Steps to reproduce
I have included a project that demonstrates this.

Minimal reproduction project
[Uploading tile_set issue.zip…]()

### Steps to reproduce

run the included project

### Minimal reproduction project

[tile_set issue.zip](https://github.com/godotengine/godot/files/8028984/tile_set.issue.zip)

**Comment by groud** [comment]
There's an error in your code. You need to specify the `alternative_tile` as 0 as the last argument of your function:
 `$TileMap.set_cell (  layer,  mapcoords,  sourceid, atlascoords, 0) `
 
We should most likely document that, as the default values are for clearing a cell by default.

**Comment by ryanscottcausecast** [comment]
That works.  Thanks.  No way to have known yes, documentation.  :)

**Comment by akien-mga** [comment]
Would it be more expected for users if the default value was `0`, and `-1` had to be passed explicitly to clear the cell?

**Comment by groud** [comment]
> Would it be more expected for users if the default value was 0, and -1 had to be passed explicitly to clear the cell?

Yeah that makes sense.

**Comment by akien-mga** [comment]
Fixed by #58659.
