### ISSUE TITLE
Vulkan: Flood of GI errors when `queue_free()`ing a .tscn containing a OmniLight3D when SDFGI is enabled (!light_storage->owns_light_instance(light_instance))

### ISSUE THREAD

**Issue by macryc** [godotengine/godot#57840]
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

4.0 alpha 1

### System information

Win10, GLES3, RTX 2070 mobile

### Issue description

At runtime, when queue_free()'ing a tscn that contains a omnilight3D node, debugger gets spammed with this error: 
pre_process_gi: Condition "!li" is true. Continuing. <C++ Source>   servers/rendering/renderer_rd/renderer_scene_gi_rd.cpp:1484 @ pre_process_gi(). 
The error doesn't show up when the light node is hidden right before it's freed.

### Steps to reproduce

1. start a 3d scene
2. add a Omnilight3D node, leave it at default settings
3. add a Environment node, turn on SDFGI, volumetric fog, and glow (all at default settings)
4. attach a script to queue_free() the Omnilight3D node on keypress
5. run the game, press the key to queue_free() the Omnilight3D
6. watch above error flood the debug

### Minimal reproduction project

not needed, just do the steps above

**Comment by cptfurball** [comment]
Hey there, thank you all for the hard work! <3

I just want to add that this issue is still happening in Godot 4.0 Alpha 7. Will this be fixed soon? :D

**Comment by alex9099** [comment]
I got this error but i don't use queue_free to remove any lights. Even hiding them (so they shouldn't be accounted to lighting?) continues giving this error. This on a "complex" project, so there must be something conflicting, it's not queue_free in my case

**Comment by cridenour** [comment]
On alpha9 this can happen when I call `get_tree().quit()` on a scene with a larger number of SpotLight3Ds (and SDFGI). Despite the game closing, the debugger hits around 100k errors and then stops.

**Comment by cptfurball** [comment]
I just want to mention that this only happens while trying to remove any light3D nodes with "bake mode" set to "dynamic".
The environment would still need to have SDFGI enabled to replicate this.

Not sure if this is related at all but I hope it sheds some light to the issue.

**Comment by Calinou** [comment]
Quoting a workaround from https://github.com/godotengine/godot/issues/62852:

> A workaround is to set the Node's visibility to false right before you call queue_free() on it.

**Comment by LordOdin** [comment]
Getting this in 4 alpha 14 as well
![image](https://user-images.githubusercontent.com/7879019/185774982-c84c142a-d4af-403c-a949-c77408c14118.png)

**Comment by Chlipouni** [comment]
Not sure it's the same issue, but in my case using "queue_free()" when quitting my main scene generates a lot of errors.
I have a DirectionalLight in my scene, but the errors still happen if i hide it.

Here are the first ones :
![queue_free_errors](https://user-images.githubusercontent.com/6040545/190846105-38ce2f9b-3ebb-4225-9390-945811917b76.jpg)

This behaviour doesn't happen in Godot 3.5 RC1.

**Comment by Calinou** [comment]
@Chlipouni This issue is unrelated.

**Comment by SoapSpangledGames** [comment]
I have also encountered this same problem with tens of thousands of gi errors with SDFGI enabled when deleting a scene that contains lights (spotlights in my case). They go away entirely if I disable SDFGI in the Environment node.

**Comment by viktor-ferenczi** [comment]
MRP can be found in #67380

**Comment by Eman2022** [comment]
Ran into this error reloading current scene, said scene having omnilights. Setting them all not visible before reloading works. Using 4.0 Beta 4.

**Comment by 1029chris** [comment]
We're also experiencing this issue on beta 9. Swapping to a scene with an omnilight in editor will spam this:
![image](https://user-images.githubusercontent.com/15712599/209258996-dfdd1394-b0aa-4227-9bd0-d70998e82b57.png)

**Comment by michael-nischt** [comment]
> We're also experiencing this issue on beta 9. Swapping to a scene with an omnilight in editor will spam this: ![image](https://user-images.githubusercontent.com/15712599/209258996-dfdd1394-b0aa-4227-9bd0-d70998e82b57.png)

We also have the issue when free'ing a scene either with `queue_free()` in the player or closing view in editor. 
Tested with spot-lights and omni-lights. Scenes without lights all are fine.
