### ISSUE TITLE
is there a way for VideoPlayer to play mp4 file

### ISSUE THREAD

**Issue by PkayJava** [godotengine/godot#5784]
is there a way for VideoPlayer to play mp4 file

**Comment by SuperUserNameMan** [comment]
I doubt Godot would include MP4 support.
mp4 is patented.
implementing mp4 support would require to pay royalties, or to download on install and dynamically link at runtime  the cisco mp4 codec dll like does firefox.

**Comment by Calinou** [comment]
[H.264 is patented until 2027.](http://www.osnews.com/story/24954/US_Patent_Expiration_for_MP3_MPEG-2_H_264)

> The last expiration is US 7826532 on 29 nov 2027 [...]

**Comment by PkayJava** [comment]
I am not sure, but somehow, but android support mp4, https://google.github.io/ExoPlayer/guide.html
Could we just allow for specific only android could play mp4, and for other platform just have only interface with empty implementation.

**Comment by vnen** [comment]
While not documented, this might already work for Android/iOS using [`OS.native_video_play()`](http://docs.godotengine.org/en/latest/classes/class_os.html#class-os-native-video-play) function.

**Comment by akien-mga** [comment]
This was a question for the Q&A, not the issue tracker: https://godotengine.org/qa
