### ISSUE TITLE
CSG resize handles unavailable for child CSG models

### ISSUE THREAD

**Issue by balloonpopper** [godotengine/godot#57853]
### Godot version

4.0 alpha 1

### System information

Windows 10

### Issue description

The resize handles of a CSG node that is a child of another CSG node are not available.

Looks to be different to, but potentially related to https://github.com/godotengine/godot/issues/51059

### Steps to reproduce

Create a CSG node (eg. CSGBox3D). Note that it has resizing handles.
Create another CSG node (it doesn't have to be the same CSG type) as a child of that CSG node. It will not have the handles to allow you to resize the node. If you reparent this second CSG node so that it doesn't have a CSG parent, the resize handles become available.

Confirmed that this worked in 3.4.2

**Comment by JamesC01** [comment]
This also affects 3.4.3rc1.

**Comment by Calinou** [comment]
> Confirmed that this worked in 3.4.2

@JamesC01 Can you reproduce this in 3.4.2?

**Comment by JamesC01** [comment]
> > Confirmed that this worked in 3.4.2
> 
> @JamesC01 Can you reproduce this in 3.4.2?

No, it doesn't happen in 3.4.2.

**Comment by Calinou** [comment]
@JamesC01 Can you also reproduce this bug in [3.4.1rc1](https://downloads.tuxfamily.org/godotengine/3.4.3/rc1/)?

Ideally, you [compile the engine from source](https://docs.godotengine.org/en/stable/development/compiling/index.html) and look into [bisecting the regression](https://docs.godotengine.org/en/stable/community/contributing/bisecting_regressions.html) to greatly speed up troubleshooting.

**Comment by JamesC01** [comment]
@Calinou Yes, it affects 3.4.1rc1. I don't think I have the time to compile it right now, but I did come across this, which I believe may be related to the problem: https://github.com/godotengine/godot/pull/56604

**Comment by akien-mga** [comment]
> Yes, it affects 3.4.1rc1.

I assume this was a typo both in Calinou's and James' comments and you mean 3.4.3 rc 1.

CC @SaracenOne

**Comment by JamesC01** [comment]
> > Yes, it affects 3.4.1rc1.
> 
> I assume this was a typo both in Calinou's and James' comments and you mean 3.4.3 rc 1.
> 
> CC @SaracenOne

Yeah, 3.4.3rc1, oops.

**Comment by akien-mga** [comment]
I can confirm the bug, and that reverting the cherry-pick of #56604 fixes it in the `3.4` branch.

I've pushed a revert to `3.4` for now to fix the regression in 3.4.3-stable. I did not revert the change from `3.x` so it still needs a bugfix (and possibly `master` too).

**Comment by gaudecker** [comment]
The early return from #56602 is indeed the culprit.

**Slightly off topic:**
I cannot tell the difference in selection behavior with or without #56602. I can only select CSG nodes by clicking the triangle edges, clicking anywhere else does nothing.

Can #56602 be reverted for 4.0 as well?

**Comment by JamesC01** [comment]
> The early return from #56602 is indeed the culprit.
> 
> **Slightly off topic:** I cannot tell the difference in selection behavior with or without #56602. I can only select CSG nodes by clicking the triangle edges, clicking anywhere else does nothing.
> 
> Can #56602 be reverted for 4.0 as well?

I might be wrong, but I'm sure I remember it improved the selection accuracy. Before, I'd occasionally have to click in a few different places to select a CSG object, but with that update, it seemed to make selecting them easier.

**Comment by gaudecker** [comment]
> I might be wrong, but I'm sure I remember it improved the selection accuracy. Before, I'd occasionally have to click in a few different places to select a CSG object, but with that update, it seemed to make selecting them easier.

I'll do some tests to make sure.
