### ISSUE TITLE
Pressing TAB in Inspector fields moves the focus upwards

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#57854]
### Godot version

3.x (4ed2c8ee08)

### System information

Arch Linux, GLES 3, Mesa Intel(R) UHD Graphics (CML GT2)

### Issue description

Pressing TAB in the video:

https://user-images.githubusercontent.com/372476/153205117-1f2c9554-ad96-462d-95b9-958483dc4aff.mp4

---

Bisecting shows it's introduced in #54174. Reverting the logic changes in `core/input_map.cpp` fixes the issue:

```patch
diff --git i/core/input_map.cpp w/core/input_map.cpp
index 6dd8523377..30f39b57ac 100644
--- i/core/input_map.cpp
+++ w/core/input_map.cpp
@@ -136,7 +136,9 @@ List<Ref<InputEvent>>::Element *InputMap::_find_event(Action &p_action, const Re
 
 		int device = e->get_device();
 		if (device == ALL_DEVICES || device == p_event->get_device()) {
-			if (e->action_match(p_event, p_exact_match, p_pressed, p_strength, p_raw_strength, p_action.deadzone)) {
+			if (p_exact_match && e->shortcut_match(p_event)) {
+				return E;
+			} else if (!p_exact_match && e->action_match(p_event, true, p_pressed, p_strength, p_raw_strength, p_action.deadzone)) {
 				return E;
 			}
 		}
```

Not sure if the changes are intended. CC @nathanfranke 

Inspector tabbing on `master` has been broken in another way for quite sometime (#53832), so not reproducible there. This report is only for `3.x`.

### Steps to reproduce

Make the Inspector inspecting something, click inside a field, and press TAB.

**Comment by akien-mga** [comment]
Fixed by #57864.
