### ISSUE TITLE
GDScript 2.0: GDScript compiler issue with `super` construct

### ISSUE THREAD

**Issue by AncRad** [godotengine/godot#57858]
### Godot version

4.0.alpha1.official.31a7ddbf8

### System information

Windows 7

### Issue description

Godot Editor crashes when attempting to invoke a completion query (command "ui_text_completion_query", Ctrl + Space) on an attribute access operator on a `super()` construct, provided that it must have a return type.

### Steps to reproduce

```GDScript
func to_string() -> String:
	return super() # add a dot at the end of "super()" and wait or press 'Ctrl + Space' (command "ui_text_completion_query")
```

**Comment by object71** [comment]
This also seems to duplicate #57856

**Comment by VikramSGIT** [comment]
Looks like another type detection issue same as #57669

**Comment by KoBeWi** [comment]
Doesn't seem happening anymore in alpha 7.
