### ISSUE TITLE
GDScript 2.0: GDScript compiler crash with function construction

### ISSUE THREAD

**Issue by AncRad** [godotengine/godot#57856]
### Godot version

4.0.alpha1.official.31a7ddbf8

### System information

Windows 7

### Issue description

Godot Editor crash due to GDScript compiler.
The problem arises when the compiler looks for the end of a function and stumbles upon another function that overrides the base function of the class and calls it from itself.

### Steps to reproduce

1. Create a new project;
2. create a new GDScript with extendes from any base class;
3. edit the script with the built-in editor;
4. create a function that overrides the parent class function and calls the base function with the `super()` construct;
5. move the caret to the beginning of the empty line above the created function in step 4, start creating a new function, enter `func func_name`.
As soon as you start typing the first characters of the function name Godot Editor crashes.

```GDScript
extends Node


# then start creating a function like `func foo`


func remove_child(node : Node) -> void:
	#super(node) # uncomment it first
	pass

```

**Comment by KoBeWi** [comment]
Doesn't seem to happen anymore in alpha 7.
