### ISSUE TITLE
3D Editor navigation stops responding when canceled a node translation

### ISSUE THREAD

**Issue by KC098** [godotengine/godot#57868]
### Godot version

4.0 alpha 2

### System information

Windows 10, AMD Radeon HD 8700 Vulkan

### Issue description

When using 3D, using the blender style transform shortcuts, and canceled (right mouse click) the navigation on the viewport stops working

### Steps to reproduce

1. Use the blender style transform shortcuts ([GH-56543](https://github.com/godotengine/godot/pull/56543)).
2. Move node to any axis
3. Cancel (right click)

**Comment by akien-mga** [comment]
CC @rcorre @JFonS

**Comment by imjp94** [comment]
I encountered the same problem, and I noticed 2 things:
- Rotating editor viewport through numpad is still possible, I guess somehow the mouse event are blocked
- Start another transformation and finish it, the 3D editor navigation will works normally again


https://user-images.githubusercontent.com/11486079/153332006-937126af-2a23-4f5d-946b-20165dde2b40.mp4
