### ISSUE TITLE
RPC error is unclear when the function is missing from local script.

### ISSUE THREAD

**Issue by DuendeBrek2** [godotengine/godot#57869]
### Godot version

4.0 alpha 2

### System information

Windows 10

### Issue description

Attempting to perform RPC call from client to server, or from server to client results in respectively: "connected, Unable to get the RPC configuration for the function", and "connected: unable to get the RPC configuration for the function".

According to my knowledge, the code presented in "Steps to reproduce" should be valid, and result in RPC calls making their way to their destination. 

player_connected is being fired, which would indicate that player connection to the server is working, just not the RPC's themselves. 

### Steps to reproduce

**Server Code:** 

```
extends Node

const PORT = 5000
const MAX_PLAYERS = 200

func _ready():
	var server = ENetMultiplayerPeer.new()
	server.create_server(PORT, MAX_PLAYERS)
	multiplayer.peer_connected.connect(self.player_connected)
	multiplayer.peer_disconnected.connect(self.player_disconnected)
	
	multiplayer.set_multiplayer_peer(server)
	print("Server Started at port %s" % PORT)

func player_connected(id):
	print("Player " + str(id) + " connected to Server")
	rpc_id(id, &"testing_to_client")

func player_disconnected(id):
	print("Player " + str(id) + " left the Server")

@rpc(any_peer)
func send_hello():
	print("Hello there!")
```

**Error:**
```
E 0:00:01:0919   player_connected: Unable to get the RPC configuration for the function "testing_to_client" at path: "/root/World". This happens when the method is not marked for RPCs.
  <C++ Error>    Condition "config.name == StringName()" is true.
  <C++ Source>   scene/multiplayer/scene_rpc_interface.cpp:462 @ rpcp()
  <Stack Trace>  Server.gd:19 @ player_connected()
```

**Client Code:**

```
extends Node

func _ready():
	var client = ENetMultiplayerPeer.new()
	client.create_client("127.0.0.1", 5000)
	
	multiplayer.connected_to_server.connect(self.connected)
	
	multiplayer.set_multiplayer_peer(client)

func connected():
	print("connected to game server")
	rpc_id(1, &"send_hello")

@rpc
func testing_to_client():
	print("works")
```

**Error:**

```
E 0:00:00:0942   connected: Unable to get the RPC configuration for the function "send_hello" at path: "/root/World". This happens when the method is not marked for RPCs.
  <C++ Error>    Condition "config.name == StringName()" is true.
  <C++ Source>   scene/multiplayer/scene_rpc_interface.cpp:462 @ rpcp()
  <Stack Trace>  Client.gd:13 @ connected()
```

**Comment by Faless** [comment]
The RPC functions must be defined in both client and server.
What the error is telling you is that you need to define `send_hello` and `testing_to_client` in both client and server.
In general, both scripts **must have the same RPC functions with the same name**.

On the other end, there should also be an error telling you the RPC configuration doesn't match, so if that doesn't happen, that is a bug.

**Comment by Faless** [comment]
Well, in this case it doesn't get to the remote configuration check because the RPC doesn't fire at all since it's not defined in the local script.

**Comment by DuendeBrek2** [comment]
> The RPC functions must be defined in both client and server. What the error is telling you is that you need to define `send_hello` and `testing_to_client` in both client and server. In general, both scripts **must have the same RPC functions with the same name**.
> 
> On the other end, there should also be an error telling you the RPC configuration doesn't match, so if that doesn't happen, that is a bug.

Could you please explain this in more detail, please? I've seen more people than just me being confused by this situation, and now that you mention that the declaration of RPC functions has to be done on both server and client, isn't it a potential security risk for multiplayer games, since you need to have your server code on the client? As much as it's only a duplication, it also means you need to have more code in your scripts, and adjust your 3.x networking workflow to this new approach. What was the reasoning behind the change from one side declaration of RPC functions to this if I may ask?

**Comment by Faless** [comment]
> isn't it a potential security risk for multiplayer games, since you need to have your server code on the client?

Not necessarily, you just need a function with the same name and RPC config, it can be an empty function (i.e. the function content does not have to be the same).

> What was the reasoning behind the change from one side declaration of RPC functions to this if I may ask?

I didn't like the idea too much but it does provide quite some optimization benefits. You can read the discussion here: #35522

**Comment by Duroxxigar** [comment]
> The RPC functions must be defined in both client and server. What the error is telling you is that you need to define `send_hello` and `testing_to_client` in both client and server. In general, both scripts **must have the same RPC functions with the same name**.

This seems wrong. I don't recall it being this way in 3.x, 'nor does it make sense imo. Now, admittingly, all of my games use a listen server approach, so I wouldn't even notice anyway to be honest. I could be wrong on this front as the script would contain both functions anyway. That said, a very common convention is to prefix a function with `server` or `client` to represent the direction it is going. I wouldn't expect for clients to have `server_update_client_name` in their scripts, as that is something that should only exist on the server. So you'd end up doing `rpc_id(1, "server_update_client_name")`. Assuming a dedicated server setup.

With the quoted reply, it sounds to be as though the rpc takes the StringName and assumes it is the calling and destination function name.

**Comment by Faless** [comment]
> I don't recall it being this way in 3.x,

No, it was changed in the PR mentioned above (#35522).

The system already relied on client and server nodes having the same position in tree, now it also also rely on server and client having the same function names in those scripts.

More specifically, the implementation does not send the StringName at all, just an ID which depends on the function name (or more correctly the position in the ordered RPC list for that node).

Note that this is also in line with the new syntax of doing `my_func.rpc()`.

As mentioned before, I didn't like this idea too much originally, but I was convinced (and still am) that consistently using (multiple) RPCs which mismatch from client and server is a very rare case, and even in that case forcing to define the function locally makes the code more readable. E.g.:

```gdscript
extends Node

const PORT = 5000
const MAX_PLAYERS = 200

func _ready():
	var server = ENetMultiplayerPeer.new()
	server.create_server(PORT, MAX_PLAYERS)
	multiplayer.peer_connected.connect(self.player_connected)
	multiplayer.peer_disconnected.connect(self.player_disconnected)
	
	multiplayer.set_multiplayer_peer(server)
	print("Server Started at port %s" % PORT)

func player_connected(id):
	print("Player " + str(id) + " connected to Server")
	testing_to_client.rpc_id(id)

func player_disconnected(id):
	print("Player " + str(id) + " left the Server")

@rpc(any_peer)
func send_hello():
	print("Hello there!")

@rpc
func testing_to_client():
	# Only implemented in the client
	pass
```

**Comment by Duroxxigar** [comment]
I wrote my comment before you posted and then went back to work - I went back and read through the issue. I understand the optimization gains from it, but I am not a fan of implementing boilerplate. I find readability to be subjective as well. Functions will end up existing just to exist, which is not ideal. I don't have a solution to have both worlds currently, other than letting people assign ids in the rpc annotation, then if it is not set, it is automatically generated. But that is just an off the cuff suggestion with little thought put into it.

**Comment by DuendeBrek2** [comment]
> > I don't recall it being this way in 3.x,
> 
> No, it was changed in the PR mentioned above (#35522).
> 
> The system already relied on client and server nodes having the same position in tree, now it also also rely on server and client having the same function names in those scripts.
> 
> More specifically, the implementation does not send the StringName at all, just an ID which depends on the function name (or more correctly the position in the ordered RPC list for that node).
> 
> Note that this is also in line with the new syntax of doing `my_func.rpc()`.
> 
> As mentioned before, I didn't like this idea too much originally, but I was convinced (and still am) that consistently using (multiple) RPCs which mismatch from client and server is a very rare case, and even in that case forcing to define the function locally makes the code more readable. E.g.:

I'm really not sure what to think about it. This seems like a major forceful workflow change. I remember that adjusting to the scene trees needing to be the same position and name was sometimes tricky, and this seems like additional ... overhead? What I can think of the top of my head right now, is that alongside having to sometimes do ghost nodes for the sake of scene tree server-client mirroring, you will also add an additional section, probably on the bottom of every networked scene named something alongside "empty function declarations", and that's also additional place in which you could make a mistake and make the code work in an unexpected way (if the @rpc won't be replicated correctly? Do you need @rpc to have same arguments if you do empty function on either server or client, or just @rpc without brackets?)

As much as it grants performance gain, shouldn't it be made an optional thing, similar to how static casting works, due to the code practices adjustment it requires you to make?

**Comment by Faless** [comment]
> This seems like a major forceful workflow change. I remember that adjusting to the scene trees needing to be the same position and name was sometimes tricky, and this seems like additional ... overhead?

Well, we are trying to provide a consistent workflow, the system was designed since the beginning with idea of client and server running the same scripts, that fact that you could have different RPC names between client and server was mostly a side effect of the implementation.

> Do you need `@rpc` to have same arguments if you do empty function on either server or client, or just @rpc without brackets?)

They also need to have the appropriate arguments, since further optimization (and error checking) is done there.

> As much as it grants performance gain, shouldn't it be made an optional thing, similar to how static casting works, due to the code practices adjustment it requires you to make?

I don't think this can be made optional in an easy way, and as mentioned above this has always been part of the design, the implementation just used to allow something that was not supposed to.

We can of course re-evaluate this design, but we need a proposal detailing why we should allow mismatching RPCs configurations between client and server, i.e. in which cases it is required to do so and why, and how common those cases are.

**Comment by Faless** [comment]
@DuendeBrek2 @Duroxxigar I have closed the issue via #57876 , but if you feel this design decision is a deal-breaker for you please open a proposal [here](https://github.com/godotengine/godot-proposals/issues) so we can keep the conversation going.

**Comment by Duroxxigar** [comment]
Nah - it isn't a deal breaker for me, just wonky in my opinion.

**Comment by Oladipupo** [comment]
100% Wonky and confusing. Ill even say harder to learn than previous godot versions.

**Comment by Calinou** [comment]
@Oladipupo Did you see Faless' comment above?

**Comment by narcissawright** [comment]
> I was convinced (and still am) that consistently using (multiple) RPCs which mismatch from client and server is a very rare case

Is this actually true though? I imagine any client-server architecture would have plenty of RPCs that are intended to be one way. i.e. from Client to Server only, or vice versa.

**Comment by mojoyup** [comment]
> > I don't recall it being this way in 3.x,
> 
> No, it was changed in the PR mentioned above (#35522).
> 
> The system already relied on client and server nodes having the same position in tree, now it also also rely on server and client having the same function names in those scripts.
> 
> More specifically, the implementation does not send the StringName at all, just an ID which depends on the function name (or more correctly the position in the ordered RPC list for that node).
> 
> Note that this is also in line with the new syntax of doing `my_func.rpc()`.
> 
> As mentioned before, I didn't like this idea too much originally, but I was convinced (and still am) that consistently using (multiple) RPCs which mismatch from client and server is a very rare case, and even in that case forcing to define the function locally makes the code more readable. E.g.:
> 
> ```gdscript
> extends Node
> 
> const PORT = 5000
> const MAX_PLAYERS = 200
> 
> func _ready():
> 	var server = ENetMultiplayerPeer.new()
> 	server.create_server(PORT, MAX_PLAYERS)
> 	multiplayer.peer_connected.connect(self.player_connected)
> 	multiplayer.peer_disconnected.connect(self.player_disconnected)
> 	
> 	multiplayer.set_multiplayer_peer(server)
> 	print("Server Started at port %s" % PORT)
> 
> func player_connected(id):
> 	print("Player " + str(id) + " connected to Server")
> 	testing_to_client.rpc_id(id)
> 
> func player_disconnected(id):
> 	print("Player " + str(id) + " left the Server")
> 
> @rpc(any_peer)
> func send_hello():
> 	print("Hello there!")
> 
> @rpc
> func testing_to_client():
> 	# Only implemented in the client
> 	pass
> ```

I have just tried this code concept in the 4 beta 1 and its not sending anything. Maybe I am confused on the syntax still. 
SO, we need the annotation before every function we want to network. I think I go that. But now say I try to print from the server peer of a P2P in the network script, if I make a function after the annotation and have the annotation set to any_peer, and then in a process function do that_func.rpc(), it doesnt do anything. Thoughts? This is me trying to understand the changes so I can change my codes and this example is running just the server peer instance, but I thought "any_peer" would still print no?

**Comment by zurrealStudios** [comment]
I really mean no disrespect for the Developers and the new implementation of the RPC-System. I am a small Developer and my Skills are not so big and as far as I understand the new Method, how the RPC-System works now, is really genious! Big Kudos to you involved in the RPC-Mechanic and to the whole Godot Community and Team!

For me I made two Projects where the Server is a dedicated one: So the Server and the Client (Desktop and Mobile) App have all their own Codes for communicating with each other. Also I was planning on doing a new Project with the Server/Client Seperation.
When I think about doing my first two Projects with the new RPC-System, where I would have to manage those empty Functions on each side, it is a little bit infuriating to think about.

Also as an example: A Highscore Game, where the Highscore is Global for everyone to see and to attribute to it. The Server doesn't need to have the Game in it for storing just Statistics.

Maybe it would be possible to do an fifth RPC attribute (like @rpc(by_name)), where those Functions are called by the Godot 3.4 RPC-Method?

Greetings, and again big Thanks to all the Contributor to the Godot Project :)

**Comment by Faless** [comment]
> Maybe it would be possible to do an fifth RPC attribute (like `@rpc(by_name)`), where those Functions are called by the Godot 3.4 RPC-Method?

The `@rpc` annotation goes before the function definitions, if you don't want to define the function, you cannot use the annotation.
Using the annotation on the remote peer does not provide any information to the local one on how to call those functions (reliable, unreliable, authority, etc).

If you want to specify RPCs without a function (thus losing the benefits of calling RPCs via `my_function.rpc()`), you can use [Node.rpc_config](https://docs.godotengine.org/en/latest/classes/class_node.html#class-node-method-rpc-config) .
```gdscript
func _init():
    rpc_config("server_only_function", {rpc_mode = MultiplayerAPI.RPC_MODE_ANY_PEER})
```
You can then call `rpc("server_only_function", arg1, arg2)`.

But it's really not faster then doing:
```gdscript
@rpc func server_only_function(arg1, arg2): pass
```
which also gives you the benefit of parameter typing (catching errors in the client), and rpc names "spell check" (if you misspell e.g. `server_only_functionZ.rpc` you'll get a break-point in the client, because the function doesn't exists).

**Comment by Brandt-J** [comment]
I am also running in some issues here :(
I just convert my project from Godot 3 to 4 and have, as the others here as well, an authorative dedicated server setup with different functions on Server and Client. 
To make it run, I copied over all functions that the server has also to the client project (keeping signatures the same but replacing function bodies with "pass") and vice versa. But I still get this error:
```
E 0:00:18:0797   process_simplify_path: The rpc node checksum failed. Make sure to have the same methods on both nodes. Node path: world
  <C++ Source>   modules/multiplayer/scene_cache_interface.cpp:80 @ process_simplify_path()
```
Does the order of the functions in the script somehow matter?? They have different orderings in my case. But I thought this should be not of importance?
And: If this error occurs, does this prevent any rpcs to happen from within the respective server/client scripts?

**Comment by ZhangWei-bi** [comment]
I'm on 4.0.3-stable trying to upgrade from 3.3.3

The rpc is successful when I have the `@rpc` and then the same method on both server and client but I still get the same error log on both the server and the client as @Brandt-J but it says Node path: . instead. 

I'm using custom multiplayer.

Using rpc_config does not work at all for me @Faless 

This is a strange decision for both the client and the server to need the same method.

**Comment by ZhangWei-bi** [comment]
Turns out the error I was getting was because you have to have all rpc methods on both the client and server even if you don't rpc one of the methods.

So if I had these two methods on the server, but the client only had TestMethod1

`@rpc
func TestMethod1(arg1, arg2):
	pass

@rpc
func TestMethod2(arg1):
	pass`

And then if you do this on the client rpc_id(1, "TestMethod1", "test1", "test2")

You will get this error: The rpc node checksum failed. Make sure to have the same methods on both nodes. Node path: .

Strange.

**Comment by Kun-guru** [comment]
meanwhile I'm still getting the same error `process_confirm_path: The rpc node checksum failed. Make sure to have the same methods on both nodes. Node path: .` even after ensuring that both the server and the client code have the same rpc functions.. I am using C#

**Comment by Mazianni** [comment]
The clarification given to resolve this issue is insufficient given just how breaking of a change this is.

It only states that there is a checksum mismatch somewhere in a node. I would greatly appreciate even a tiny amount more of debug information so I know *what* is missing, instead of playing twenty questions with previously non-broken code to fulfill a boiler plate requirement.

**Comment by rickdarlington** [comment]
> meanwhile I'm still getting the same error `process_confirm_path: The rpc node checksum failed. Make sure to have the same methods on both nodes. Node path: .` even after ensuring that both the server and the client code have the same rpc functions.. I am using C#

@Kun-guru did you resolve this?  give up?  I'm having the exact same problem right now (using C#, classes are literally identical).

**Comment by Kun-guru** [comment]
> > meanwhile I'm still getting the same error `process_confirm_path: The rpc node checksum failed. Make sure to have the same methods on both nodes. Node path: .` even after ensuring that both the server and the client code have the same rpc functions.. I am using C#
> 
> @Kun-guru did you resolve this? give up? I'm having the exact same problem right now (using C#, classes are literally identical).

Yes @rickdarlington I got past it barely I can say.. I am using a custom multiplayer setup with a gateway and auth server along with the game server. I use custom multiplayer through `SceneMultiplayer` for that. let me give you a snippet of the gateway client and server as well as the game server client and server and hope that gets you somewhere: 

Gateway Client:
```
 public partial class Gateway : Node
    {
        public ENetMultiplayerPeer network;
        SceneMultiplayer GatewayApi;

        public string DEFAULT_IP = "127.0.0.1";
        public int PORT = 9999;

        public Server Server;
        MainScreen MainScreen;
        public bool NewAccount;
        public string username, email, password;

        public override void _Ready()
        {
            network = new();
            GatewayApi = new();
            
        }

        public override void _Process(double delta)
        {
            if (GatewayApi == null)
                return;
            if (!GatewayApi.HasMultiplayerPeer())
                return;
            GatewayApi.Poll();
        }
       
        public void ConnectToServer(string logins, bool newAccount)
        {
            network.CreateClient(DEFAULT_IP, PORT);
            GetTree().SetMultiplayer(GatewayApi, GetPath());
            GatewayApi.MultiplayerPeer = network;
           
            GatewayApi.ConnectionFailed += OnConnectionFailed;
            GatewayApi.ConnectedToServer += OnConnectionSucceeded;
            GatewayApi.ServerDisconnected += OnServerDisconnected;
        }

        public void OnConnectionSucceeded()
        {
        }

        public void OnConnectionFailed()
        {
            GD.Print("Failed to connect to login server");
        }

        public void OnServerDisconnected()
        {
            GD.Print("Gateway disconnected");
        }

        [Rpc(MultiplayerApi.RpcMode.AnyPeer, TransferMode = MultiplayerPeer.TransferModeEnum.Reliable)]
        public void RequestLogin(string _email, string _password)
        {
        }

        [Rpc(MultiplayerApi.RpcMode.Authority, TransferMode = MultiplayerPeer.TransferModeEnum.Reliable)]
        public void LoginResult(bool result, string token)
        {           
        }
    }
```

Gateway Server:
```
public partial class Gateway : Node
{
    public ENetMultiplayerPeer network;
    SceneMultiplayer GatewayApi;
    public override void _Ready()
    {
        network = new ();
        GatewayApi = new();
        StartServer();
    }
    public override void _Process(double delta)
    {
        if (GatewayApi == null)
            return;
        if (!GatewayApi.HasMultiplayerPeer())
            return;
        GatewayApi.Poll();
    }
    public void StartServer()
    {
        network.CreateServer(9999, 2048);
        GetTree().SetMultiplayer(GatewayApi, GetPath());
        Multiplayer.MultiplayerPeer = network;

        GD.Print("Gateway server started");

        Multiplayer.PeerConnected+= PeerConnected;
        Multiplayer.PeerConnected+= PeerDisconnected;
    }
    public void PeerConnected(long clientId)
    {
        GD.Print($"Client {clientId} connected");
    }
    public void PeerDisconnected(long clientId)
    {
        GD.Print($"Client {clientId} disconnected");
    }
    [Rpc(MultiplayerApi.RpcMode.AnyPeer, TransferMode = MultiplayerPeer.TransferModeEnum.Reliable)]
    public void RequestLogin(string email, string password)
    {        
    }
    [Rpc(MultiplayerApi.RpcMode.Authority, TransferMode = MultiplayerPeer.TransferModeEnum.Reliable)]
    public async void LoginResult(bool result, string token, int playerId)
    {       
    }
}
```

Gameserver Client

```
public partial class Server : Node
    {
        ENetMultiplayerPeer network;
        public string DEFAULT_IP = "127.0.0.1";
        public int PORT = 10000;

        public override void _Ready()
        {
            network = new ENetMultiplayerPeer();
            MainScreen = GetNode<MainScreen>("/root/LoginScreen");
        }

        public void ConnectToServer(string token)
        {
            network.CreateClient(DEFAULT_IP, PORT);
            Multiplayer.MultiplayerPeer = network;

            Multiplayer.ConnectionFailed += OnConnectionFailed;
            Multiplayer.ConnectedToServer += OnConnectionSucceeded;
            Multiplayer.ServerDisconnected += OnServerDisconnected;
        }              

        public void OnConnectionFailed()
        {
            GD.Print("Failed to connect");
        }

        public void OnConnectionSucceeded()
        {
            GD.Print($"Net status: {network.GetConnectionStatus()}");
        }

        public void OnServerDisconnected()
        {
            GD.Print("Server went offline");
        }

        [Rpc(MultiplayerApi.RpcMode.AnyPeer, TransferMode = MultiplayerPeer.TransferModeEnum.Reliable)]
        public void RequestNewGame(int selectedGame)
        {
            RpcId(1, nameof(RequestNewGame), selectedGame);
        }
    }
```

Gameserver Server:

```
public partial class Server : Node
    {
        public ENetMultiplayerPeer network;
        SceneMultiplayer ServerApi;
        int Port = 12211;
        int MaxPlayers = 1024;        

        public override void _Ready()
        {
            network = new();
            ServerApi = new();
           
            StartServer();
        }

        public void StartServer()
        {
            network.CreateServer(10000, 2048);
            Multiplayer.MultiplayerPeer = network;            

            GD.Print("Game server started");

            Multiplayer.PeerConnected += PeerConnected;
            Multiplayer.PeerDisconnected += PeerDisconnected;
        }

         public void PeerConnected(long playerId)
        {
            GD.Print($"Player {playerId} connected");
        }

        public void PeerDisconnected(long playerId)
        {
            GD.Print($"Player {playerId} disconnected");
        }

      [Rpc(MultiplayerApi.RpcMode.AnyPeer, TransferMode = MultiplayerPeer.TransferModeEnum.Reliable)]
        public void RequestNewGame(int gameType)
        {
            //implementation
        }
    }
```


Note that they are all running as singletons on the client and as scene root nodes in the server and the nodes have the same name in both client and server in Gateway(client singleton) Gateway(server scene root node) and Server(client singleton) Server (server singleton)

**Comment by rickdarlington** [comment]
@Kun-guru thank you so SO much for the comment and extensive example (on a close issue no less)!  People like you make the Godot community!
