### ISSUE TITLE
if statement is not recognized anymore with freed instances

### ISSUE THREAD

**Issue by Mulham** [godotengine/godot#57861]
### Godot version

3.4.2

### System information

Linux MInt 10

### Issue description

i have this code:
if shield:
		shield.visible = false

when i queue free the "shield" instance it works because it has "if shield" statement, but in the latest version it doesn't read that if statement and gives error "invalid visible property for previously freed instance"

### Steps to reproduce

```gdscript
onready var shield := $shield
func _ready() -> void:
	PlayerData.connect("shield_brocken", self, "shield_brocken")
func _physics_process(delta: float) -> void:
	update_animation(direction)
func update_animation(motion: Vector2) -> void:
        if shield:
		shield.visible = false
		shield.flip_h = false
		shield.offset.x = 0
		shield.offset.y = 0
		shield_anim.stop()
func shield_brocken() -> void:
	get_node("shield").queue_free()
```

**Comment by Mulham** [comment]
> Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot. (The code sample alone doesn't suffice here.)
> 
> > when i queue free the "shield" instance it works because it has "if shield" statement, but in the latest version it doesn't read that if statement and gives error "invalid visible property for previously freed instance"
> 
> Which Godot version did you previously use?

v3.2.3

**Comment by Calinou** [comment]
Try using `if is_instance_valid(shield)` to check for the `shield` instance's validity instead of just `if shield`.

**Comment by akien-mga** [comment]
> > Try using `if is_instance_valid(shield)` to check for the `shield` instance's validity instead of just `if shield`.
> 
> this worked! thanks a lot, but i want to mention in general that when we have hundreds or thousands of lines we don't want to see new bugs appear because of updating the engine. i don't know if i am wrong in this..but thanks for your effort and thank you again

It's not a new bug that appeared, it's an existing, silent bug, which is no longer silent. Your game would have crashed there in a release build, this error let you fix it.

**Comment by Calinou** [comment]
Closing, as the original issue is now resolved.
