### ISSUE TITLE
Replace in Files doesn't update file until project is reopened

### ISSUE THREAD

**Issue by lambferatu** [godotengine/godot#57870]
### Godot version

4.0-alpha2

### System information

Windows 11, Nvidia 1050 Ti, Vulkan

### Issue description

The replace all (no undo) doesn't update the file until the project is reopened

https://user-images.githubusercontent.com/53798244/153260894-827f32d2-11b9-4e36-b42c-02224bc635c2.mp4

Edit:
The video doesn't show for me on some browsers, so I uploaded it:

[video](https://www.youtube.com/watch?v=_wHT9iblIjU)

### Steps to reproduce

1 - Open the replace in files menu with Ctrl + Shift + R
2 - Write the word you want to replace
3 - Write the word you want to replace with
4 - Click on Replace....
5 - Down on the Search Results panel, click on Replace all (no undo)
6 - Nothing happens
7 - Re-open the project, the changes are there

**Comment by Calinou** [comment]
@lambferatu Can you reproduce this in 3.4.2?

**Comment by lambferatu** [comment]
@Calinou No, works fine in 3.4.2

**Comment by IgorKordiukiewicz** [comment]
In `ScriptEditor::_reload_scripts()`:
```
Ref<Script> script = edited_res;
if (script != nullptr) {
	Ref<Script> rel_script = ResourceLoader::load(script->get_path(), script->get_class(), ResourceFormatLoader::CACHE_MODE_IGNORE);
	ERR_CONTINUE(!rel_script.is_valid());
	script->set_source_code(rel_script->get_source_code());
	script->set_last_modified_time(rel_script->get_last_modified_time());
	script->reload();
}
```
In 3.4 `rel_script->get_source_code()` returns updated code. But for some reason in master it returns code before the changes.

**Comment by harrisyu** [comment]
Confirm in Godot 4 alpha 3, same in Find In Files -> Replace.
It actually replaced( writed to file), just not update display.

**Comment by adamscott** [comment]
Could not reproduce in master (1e3919c409).

[Peek 01-12-2022 13-41.webm](https://user-images.githubusercontent.com/270928/205134307-0fd4d363-819c-492c-8622-94a11000c67e.webm)

I imagine the latest major GDScript changes fixed this issue.

**Comment by Calinou** [comment]
> I have seen this and another similar issue: sometimes ctrl + shift + f simply doesn't find all instances of a search term at all version: v4.4.1.stable.official [[49a5bc7](https://github.com/godotengine/godot/commit/49a5bc7b616bd04689a2c89e89bda41f50241464)]

Find in Files works on filesystem data, so if you have unsaved changes in a script, they won't appear in results. This should be tracked in its own issue.
