### ISSUE TITLE
Keyboard shortcut [F] (Center Selection) does not work.

### ISSUE THREAD

**Issue by tomuxmon** [godotengine/godot#5788]
**Operating system or device - Godot version:**
Windows 10 insider preview. Godot steam version (regular version - opt out from betas)

**Issue description** (what happened, and what was expected):
Keyboard shortcut **\[F\]** (Center Selection) does not work. Although it **does** seem to work when "view" menu is opened before using shortcut. **\[Ctrl+F\]** (Frame Selection) works perfectly fine.

**Steps to reproduce:**
![focus_misbehaviour](https://cloud.githubusercontent.com/assets/2006864/16928801/55af1ce4-4d3d-11e6-8a68-c02154796c4f.gif)

**Comment by djrm** [comment]
the mouse has to be inside the viewport for it to work

**Comment by neikeq** [comment]
@djrm Are you sure? If I am not wrong, menu button uses `_unhandled_input` for shortcuts. In other words, it should receive any global input event unless that event was already accepted.

**Comment by djrm** [comment]
@neikeq yes, i dont remember if those events where checked in the unhandled input for canvas item editor, but they are no longer there since shortcuts were added to the menu elements.

**Comment by akien-mga** [comment]
Note that OP is using 2.0.4.1.

**Comment by tomuxmon** [comment]
If my mouse is in viewport yes.. Shortcut does work. But that is inconvenient since i want to focus while re selecting nodes with my mouse.

**Comment by neikeq** [comment]
Oh, I missed it was with 2.0.4.1 but IINW, `MenuButton` handled the events with `_unhandled_input` too before `ShorCut`s were added.

**Comment by djrm** [comment]
but it does the same in 2.1

**Comment by TheHX** [comment]
After some testing i've found the probable source of this issue, looks like the `Tree` node has a built-in search feature(You can test it by focusing the Scene tree and typing the name of a node), and it handles every key press with a valid unicode char.
This feature don't seems to be relevant anymore, since it seems to be added before Godot was open-source.

Relevant core:
https://github.com/godotengine/godot/blob/master/scene/gui/tree.cpp#L2186-L2191
https://github.com/godotengine/godot/blob/master/scene/gui/tree.cpp#L3241-L3261

**Comment by reduz** [comment]
Indeed, either you focus the viewport, or change the shortcut to something that does not conflict.

**Comment by neikeq** [comment]
Is there any reason for SceneTreeDock to have such a feature now that a search field was added?

**Comment by reduz** [comment]
Its a feature of tree, works in all trees

**Comment by reduz** [comment]
I still don't think this needs to be fixed. Blender works much in the same way regarding to viewports.

Instead, I propose we do something different:

1) We should change Tree behavior to work in a bit more standard way regarding bringing up the text editor, either by pressing F2, or clicking on the item when already selected and if the mouse is not moved or clicked again in a bit less than a second, THEN bring up the text editor (check how Unity or Unreal do this).
2) With the above implemented, then we could implement one behavior that is very nice from Unity, which is that doubleclicking an item on the tree will automatically focus it, be it 2D or 3D. 

This should solve the original problem, as not only you will not need to select and item and press F but it will add a pretty nice behavior (doubleclick to select AND go to the object in the 2D or 3D world).

**Comment by djrm** [comment]
yes i think that would be a good behavior

**Comment by punto-** [comment]
Also keep in mind that usually to rename files you don't "double click" on
them, you do a kind of "slow double click", so it's not like we're losing
some standard behavior. F2 is the most standard

**Comment by djrm** [comment]
ok i could try to fix this in the using the proposed behavior

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone (though I think @djrm is working on it, so it might still get fixed before 2.1 is released).
