### ISSUE TITLE
Keyboard input does nothing after opening Project Settings or Editor Settings (DisplayServer regression)

### ISSUE THREAD

**Issue by chriztheanvill** [godotengine/godot#57884]
### Godot version

4.0.alpha3

### System information

Kubuntu 21.10, vulkan, Intel UHD Graphics 620 (rev 09)

### Issue description

Open any options menu or try to rename a node, does not recognize keyboard input.

### Steps to reproduce

Open a menu, like Options, try to edit the display size and nothing.

### Minimal reproduction project

Just, started a new one :D

**Comment by Calinou** [comment]
@chriztheanvill Did it work in 4.0alpha1?

Also, is single-window mode enabled in the Editor Settings? I've had issues with it trying to spawn modal windows outside the editor window, and these modal windows aren't visible when single-window mode is enabled. Those modals will still capture input, causing you to no longer be able to use the editor until you press <kbd>Escape</kbd>.

**Comment by chriztheanvill** [comment]
I've tried with the new alpha, and I can not even rename nodes.

**Comment by chriztheanvill** [comment]
> Are you using a Wayland session? If so, can you reproduce this after switching to a X11 session? I don't remember if Kubuntu defaults to Wayland now (it might).

Yes, no matter if I am on X11 or Wayland if I install nvidia drivers, or uninstall them. I have the same issue.
These areas I can not edit:
![image](https://user-images.githubusercontent.com/37992958/155240526-e94cd3c2-7c53-4057-acb7-aa3997a22c00.png)

![image](https://user-images.githubusercontent.com/37992958/155240618-39441c22-2e01-48c6-aa66-bfa33879e568.png)

Some areas like: Search Files, Filter properties works fine.

**Comment by chriztheanvill** [comment]
Looks like, the new update, and return to X11, solves the problem, but I have this new message:
`WARNING: Property not found: editor/run/time_before_sleep
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/time_before_sleep
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/time_before_sleep
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/solver/default_constraint_bias
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/solver/default_constraint_bias
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/solver/default_constraint_bias
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/run_on_separate_thread
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/run_on_separate_thread
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/run_on_separate_thread
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/solver/contact_recycle_radius
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/solver/contact_recycle_radius
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/solver/contact_recycle_radius
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/solver/solver_iterations
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/solver/solver_iterations
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/solver/solver_iterations
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/default_angular_damp
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/default_angular_damp
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/default_angular_damp
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/physics_engine
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/physics_engine
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/physics_engine
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/sleep_threshold_angular
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/sleep_threshold_angular
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/sleep_threshold_angular
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/default_gravity
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/default_gravity
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/default_gravity
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/default_gravity_vector
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/default_gravity_vector
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/default_gravity_vector
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/sleep_threshold_linear
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/sleep_threshold_linear
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/sleep_threshold_linear
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/default_linear_damp
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/default_linear_damp
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/default_linear_damp
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/solver/contact_max_allowed_penetration
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/solver/contact_max_allowed_penetration
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/solver/contact_max_allowed_penetration
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/solver/default_contact_bias
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/solver/default_contact_bias
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/solver/default_contact_bias
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/solver/contact_max_separation
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/solver/contact_max_separation
     at: _get (core/config/project_settings.cpp:319)
WARNING: Property not found: editor/run/solver/contact_max_separation
     at: _get (core/config/project_settings.cpp:319)
`

**Comment by Calinou** [comment]
Those messages are a known issue, see https://github.com/godotengine/godot/issues/25661.
