### ISSUE TITLE
Tile source names appear over scrollbar

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#57881]
### Godot version

8161e28

### System information

W10

### Issue description

![image](https://user-images.githubusercontent.com/2223172/153296991-475e05c2-32f7-4bfe-8127-09c1b9720774.png)

### Steps to reproduce

1. Open TileSet editor
2. Add a source with long enough name

**Comment by AlbertFay** [comment]
I created a pull request #58073 which fixes the issue with ItemList. 

The FileSystem tab uses `tree.cpp` which doesn't truncate the text properly when the horizontal scrollbar is visible. The Scene tab does it correctly when the visibility buttons are there.
![nonworking preview of tree](https://user-images.githubusercontent.com/65504787/153780217-17177b2b-b8d5-49df-8901-026b21ae8325.gif)
.

**Comment by akien-mga** [comment]
Fixed by #58477.
