### ISSUE TITLE
Make ColorPicker/ColorPickerButton alpha checkerboard use the same contrast as the gradient editor's

### ISSUE THREAD

**Issue by rakkarage** [godotengine/godot#57891]
### Godot version

v3.4.2.stable.official [45eaa2daf]

### System information

Windows 10

### Issue description

When make a transparent gradient the colors items do not match the preview at the top? The last item in the list is fully transparent and invisible... yet is is displayed as "fully" white with the transparent check pattern virtually invisible, and items higher on list are shown with more transparency though they have less?

The items in this list should basically match the preview at the top?

Thanks.

[![Gradient2.gif](https://i.postimg.cc/mrtWDX7v/Gradient2.gif)](https://postimg.cc/xkD4pPx5)

### Steps to reproduce

-  create new Gradient, set Color 1 to transparent, and refresh by selecting a differnt node then the Gradient again (https://github.com/godotengine/godot/issues/33265)
-  add a bunch of new points, and refresh
-  note that last item in list does not appear fully transparent, and items further up list appear more so?

**Comment by rakkarage** [comment]
they do seem to `interpolate()` properly just displayed wrong

**Comment by Calinou** [comment]
Looking at the GIF, I don't understand the problem. It seems to work as expected to me, especially since your last stop is transparent *white*. Interpolation between opaque black and transparent white will result in gray colors in the middle.

**Comment by rakkarage** [comment]
You can go from white to transparent black and exactly the same thing happens. The last color is white instead of transparent. And does not match the preview at top.
[you can ](https://i.postimg.cc/prdmcrkF/Gradient.png)

**Comment by SpeCter** [comment]
Could it be that your color profile for your monitor has a really low contrast? The only difference between the preview und the items in the list is that the checker pattern I can see is that the checker patterns have different grey values for preview and list(the one in the list has a lighter grey)
The last item in your screenshot is not pure white at all on my end, just the checker pattern.

**Comment by rakkarage** [comment]
[![Again.png](https://i.postimg.cc/zfWrzfsm/Again.png)](https://postimg.cc/KKZVQmcQ)

The grid (how we tell alpha) looks the same in both places?

**Comment by Calinou** [comment]
To me, it looks like the checkerboard backgrounds don't match each other. We should change it so both have the same opacity. I prefer the gradient editor's checkerboard as it's more contrasted and makes it easier to distinguish low-opacity colors.

**Comment by kleonc** [comment]
Indeed these checkers are different:

- `GradientEdit`

https://github.com/godotengine/godot/blob/0c7c6401128a61bc2d805c4c7b400df39ffdb657/scene/gui/gradient_edit.cpp#L55-L57
https://github.com/godotengine/godot/blob/0c7c6401128a61bc2d805c4c7b400df39ffdb657/scene/resources/default_theme/theme_data.h#L41-L43

- `ColorPickerButton`
https://github.com/godotengine/godot/blob/0c7c6401128a61bc2d805c4c7b400df39ffdb657/scene/resources/default_theme/default_theme.cpp#L805
https://github.com/godotengine/godot/blob/0c7c6401128a61bc2d805c4c7b400df39ffdb657/scene/resources/default_theme/theme_data.h#L209-L211


No idea why it's made like that. Sounds like a good idea to make these backrounds look/be the same.

**Comment by rakkarage** [comment]
[![Compare.png](https://i.postimg.cc/sgZkMRPp/Compare.png)](https://postimg.cc/G4d7fV52)

Looks like it has changed in 4 alpha 1 already? the two previews now match, but I prefer the Gradient Editor version too. It seems to match other programs more? As alpha lowers, the pattern becomes easier to make out.

Thanks.
