### ISSUE TITLE
Vulkan: LightmapGI dynamic object lighting does not work (objects are fully black)

### ISSUE THREAD

**Issue by jcostello** [godotengine/godot#57890]
### Godot version

v4.0.alpha.custom_build [2c2872912]

### System information

Ubuntu 21.04. RTX 2060

### Issue description

After baking lightmap, Mesh (with uv2) lighting not being affected by GPU Lightmap's probes

![image](https://user-images.githubusercontent.com/1168582/153309371-8094aa63-6b26-41c8-a597-e12adef1126f.png)

### Steps to reproduce

Minimal project

### Minimal reproduction project

[Lightmap.zip](https://github.com/godotengine/godot/files/8036873/Lightmap.zip)

**Comment by Calinou** [comment]
I can still reproduce this as of 4.0.beta6 (Fedora 36, AMD Radeon RX 6900 XT).

**Comment by atirut-w** [comment]
Still happeneing on alpha 11. Any updates on this issue?

**Comment by Calinou** [comment]
> Still happeneing on alpha 11. Any updates on this issue?

There is no ETA for fixing this issue, as we don't know what's causing the bug yet.
