### ISSUE TITLE
Result of "double clicking" node is unexpected

### ISSUE THREAD

**Issue by tomuxmon** [godotengine/godot#5791]
**Operating system or device - Godot version:**
Windows 10 insider preview. Godot steam version.

**Issue description** (what happened, and what was expected):
Someone coming from other engines (editors) would expect node to be centered (\[F\] keyboard shortcut) when "double clicking" it in the editor. 

Not saying you guys should strive to be like them (please do not be like Unity :) ). It is just common in most editors that bouble clicking shows the item (I might be biased since my all dev experience is on windows)

**Double click in Unity Editor:**
![sparty_double_click](https://cloud.githubusercontent.com/assets/2006864/16930889/daf46f54-4d46-11e6-867a-98723681cf20.gif)

**Double click in Unreal Editor:**
![unreal_doubleclick](https://cloud.githubusercontent.com/assets/2006864/16930896/e0b5afde-4d46-11e6-9e1b-3bf1012f7a33.gif)

**Comment by TheoXD** [comment]
But we wouldn't be able to rename stuff quickly like in any operating system, really who is actually right clicking on a file/folder and pressing "rename"? Anyone? No? Honestly? Still no? Ok then xD

**Comment by TheoXD** [comment]
Fast doubleclicking I suppose could work for selection, much slower can be used to rename (as on any operating system)

**Comment by tomuxmon** [comment]
If it is possible to distinguish if either icon or text was doubleclicked, then node could be centered only when icon is doubleclicked. Renaming could be left as is.

**Comment by timoschwarzer** [comment]
@tomuxmon Hm... I would failclick like 50% of all clicks...

**Comment by djrm** [comment]
fixed by #5956
