### ISSUE TITLE
Mesh doesn't get imported to other scene

### ISSUE THREAD

**Issue by whatthesamuel** [godotengine/godot#57922]
### Godot version

4.0 alpha 2

### System information

Windows 10

### Issue description

When I import my character scene to the main scene, the mesh doesn't render. The bones and joints are shown correctly, but all the meshes are not showing at all.

I've double checked if the visibility is set correctly, not sure what else I can do.

The player scene:
![image](https://user-images.githubusercontent.com/31382049/153453826-a0102530-05f4-4e73-a769-5d1b82fdb7b3.png)

the main scene:
![image](https://user-images.githubusercontent.com/31382049/153453918-66fa8549-be3c-4368-a0f7-e3b8070e9e1c.png)

### Steps to reproduce

import mixamo gltf character -> make an inherited scene -> place it in another 3d scene

### Minimal reproduction project

I tried to export the exact scene with the problem but exporting seems to have a problem. will make a new issue

**Comment by KoBeWi** [comment]
Looks similar to #57406, which is resolved.

**Comment by whatthesamuel** [comment]
@KoBeWi That issue doesn't look similar to this one to me, but I'll try on alpha 5 and check if it is fixed in a few hours.

**Comment by whatthesamuel** [comment]
I didn't realize alpha 8 was already out! It seems to be fixed on the alpha 8 version.
