### ISSUE TITLE
[4.0] Drag and drop from Windows Explorer no longer works in Alpha 2

### ISSUE THREAD

**Issue by Rinocrosser** [godotengine/godot#57929]
### Godot version

4.0 alpha 2

### System information

Windows 10

### Issue description

Recently I've reported issue about drag and drop into Godot 4 file browser #57755
In Godot 4 alpha 2 drag and drop isn't working at all.

### Steps to reproduce

Open new project,
Open Windows file explorer
Try to drag and drop a file into Godot file browser

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/50720.

**Comment by jmb462** [comment]
Bisect result : First bad commit : f4ea9cd9f301d3af3a707e330221a4f1e242e7be

**Comment by bruvzg** [comment]
This seems to be causes by `panel->set_transient(true);` added for tooltips, the issue is not Windows specific and also reproducible on macOS, and this change is required to make tooltips work in fullscreen mode both on macOS and Windows.
