### ISSUE TITLE
Exported scenes can't be reimported

### ISSUE THREAD

**Issue by whatthesamuel** [godotengine/godot#57923]
### Godot version

4.0 alpha 2

### System information

windows 10

### Issue description

Exported scenes using project -> tools -> "export gltf" causes godot to recognize them as corrupt files when reimporting.

### Steps to reproduce

create a 3d scene -> project -> tools -> "export gltf" -> import in a new project

**Comment by whatthesamuel** [comment]
I couldn't upload the file because github won't let me attach a gltf file. I uploaded it to google drive now: https://drive.google.com/file/d/17Nk37y9e_Q0-oCbDckFJBbFXMDbkDvG4/view?usp=sharing

**Comment by fire** [comment]
Can you check if you're missing a file with an extension like `.bin` file?

**Comment by whatthesamuel** [comment]
There aren't any .bin file created when I do the export. Am I supposed to get one or do you mean something else?

**Comment by akien-mga** [comment]
Can you still reproduce the issue in 4.0 RC 3 or later?

> There aren't any .bin file created when I do the export. Am I supposed to get one or do you mean something else?

If the file you attached was generated by Godot, then yes it includes a reference to `ybot_export3_10.bin`, so Godot should probably have generated this file.

**Comment by whatthesamuel** [comment]
> 

Well, to be honest, I've been away from godot for some time, waiting for 4.0 stable, and I just downloaded rc3 and found out that the way of dealing fbx files has been changed. Now I can confirm this has been fixed.
