### ISSUE TITLE
Remote Inspector doesn't populate certain node types in double precision build

### ISSUE THREAD

**Issue by BlacRyu** [godotengine/godot#57935]
### Godot version

master v4.0.alpha.custom_build (f21a62b62)

### System information

Windows 10

### Issue description

When the engine is built with double precision (float = "64"), certain nodes will stop working with the remote inspector. Selecting these nodes in the remote scene tree will not populate the inspector, nor will the inspector be cleared if it was already populated by another node's properties.

Here is a non-exhaustive list of node types that are affected:
```
Node2D
Node3D
Control
SkeletonIK3D
CanvasLayer
```

Not all node types are affected by the issue. Some continue to work properly with the inspector, such as the base Node class, Timer, and WorldEnvironment.

**Video example**: ![RemoteInspectorDoublePrecisionBug](https://user-images.githubusercontent.com/10762433/153482714-269e1bbc-d5b2-4cdd-ac28-de7426f13328.gif)

All node types seem to work fine with the remote inspector when the engine is built with single precision floats.

### Steps to reproduce

1. Build the engine with the build option `float = "64"`
2. Create a new project.
3. Add any of the affected node types to the scene tree.
4. Play the scene and try to select any of the affected nodes.

### Minimal reproduction project

[Remote Inspector Double Precision Bug.zip](https://github.com/godotengine/godot/files/8044058/Remote.Inspector.Double.Precision.Bug.zip)

**Comment by Calinou** [comment]
cc @aaronfranke
