### ISSUE TITLE
Regression: InputEvent.is_action_pressed is true for Control+<key> even if only <key> is pressed when not using exact_match

### ISSUE THREAD

**Issue by EIREXE** [godotengine/godot#57943]
### Godot version

3.x c7f09c1318502aafccc5d587b344cfeb84e53010

### System information

Arch Linux

### Issue description

When assigning a key with a modifier to an input event (such as Control+D) it works with is_action_pressed unless exact_match is specified, I believe this is a regression as this was never the behavior before. I can confirm it didn't happen in b423dc05f6fb652d425059c2948683f6d365c94a

### Steps to reproduce

Create a new input event with a modifier such as Control+d and try checking for it in an input event using `InputEvent.is_action_pressed`

### Minimal reproduction project

[mrpok.zip](https://github.com/godotengine/godot/files/8045030/mrpok.zip)

**Comment by Calinou** [comment]
@EIREXE Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by akien-mga** [comment]
Likely related to #54174, CC @nathanfranke.

**Comment by nathanfranke** [comment]
Cannot reproduce

![Input action named test with Control+D set](https://user-images.githubusercontent.com/14253836/153513762-87bb4a12-c451-425c-baf7-be0f19413522.png)

Both `Press 1` and `Press 2` (after I press Control+D) are printed.

```gdscript
func _ready():
	var key := InputEventKey.new()
	key.scancode = KEY_D
	key.control = true
	key.pressed = true
	if key.is_action_pressed("test", false, true):
		print("Press 1")

func _input(event):
	if event.is_action_pressed("test", false, true):
		print("Press 2")
```

**Comment by EIREXE** [comment]
@nathanfranke is exact_match needed now? It used to not be needed

**Comment by nathanfranke** [comment]
With `exact_match` = `true`, Control+D works
With `exact_match` = `false`, D and Control+D work

Is this what you get too?

**Comment by EIREXE** [comment]
> With `exact_match` = `true`, Control+D works With `exact_match` = `false`, D and Control+D work
> 
> Is this what you get too?

Yep, that is what I get, in 3.4.2 only control d works

**Comment by nathanfranke** [comment]
I consider that expected behavior, but maybe we can get other input

**Comment by EIREXE** [comment]
> Well if it's breaking compat it might be problematic. Maybe this should default to `exact_match = true`?

to me that sounds like a good way to do it

**Comment by nathanfranke** [comment]
I would argue that would break more compatibility, since an input map action of `D` would not match `Control+D` by default.

**Comment by akien-mga** [comment]
> I would argue that would break more compatibility, since with `exact_match = true`, an input map action of `D` would not match `Control+D` by default.

Well that's how it behaves in 3.4, no?

```gdscript
func _input(event):
	if event.is_action_pressed("action_d"):
		print("d pressed")
	if event.is_action_pressed("action_ctrl_d"):
		print("ctrl+d pressed")
```

Pressing <kbd>D</kbd> prints `d pressed`. Pressing <kbd>Ctrl+D</kbd> prints `d pressed` and `ctrl+d pressed`.

**Comment by madmiraal** [comment]
I confirm that there has been a change in behaviour in 88e2c513e74754b8322ef0e9e10b620602f90e9e (but no change in behaviour between 3.4 and 3.4.3):

In 88e2c513e74754b8322ef0e9e10b620602f90e9e with Action: Ctrl+D:
Exact match: | False (Default) | True
-- | -- | --
Press D: | **Yes** | No
Press Ctrl+D: | Yes | Yes

In 3.4.3 with Action: Ctrl+D:
Exact match: | False (Default) | True
-- | -- | --
Press D: | No | No
Press Ctrl+D: | Yes | Yes

Pressing D now returns positive for an Action with Ctrl+D whereas before it didn't. Previously the parameter `exact` only affected actions without modifiers. Setting `exact` to `true` prevented pressing `Ctrl+D` from returning positive for an action: D.

In 88e2c513e74754b8322ef0e9e10b620602f90e9e with Action: D:
Exact match: | False (Default) | True
-- | -- | --
Press D: | Yes | Yes
Press Ctrl+D: | Yes | No

In 3.4.3 with Action: D:
Exact match: | False (Default) | True
-- | -- | --
Press D: | Yes | Yes
Press Ctrl+D: | Yes | No

**Comment by EricEzaM** [comment]
> I would argue that would break more compatibility, since with `exact_match = true`, an input map action of `D` would not match `Control+D` by default.
> 
> Right now it behaves as the documentation describes:
> 
> > If `exact_match` is `false`, it ignores the input modifiers for [InputEventKey](https://docs.godotengine.org/en/stable/classes/class_inputeventkey.html#class-inputeventkey) and [InputEventMouseButton](https://docs.godotengine.org/en/stable/classes/class_inputeventmousebutton.html#class-inputeventmousebutton) events

@nathanfranke Sorry, thats probably my bad in the way that I wrote the feature but did not write the doco for it. Doco PR: https://github.com/godotengine/godot/pull/51064 Implementation PR: https://github.com/godotengine/godot/pull/44355.

It would probably be more correct to say 

> If exact_match is false, it ignores **_additional_** input modifiers for InputEventKey... [etc]
