### ISSUE TITLE
Enable convert_text_resources_to_binary in project settings will cause many scenes/resources not to be loaded/display properly in exported game

### ISSUE THREAD

**Issue by Xwdit** [godotengine/godot#57950]
### Godot version

4.0.alpha(d435c51cd)

### System information

Windows11, Nvidia RTX 2060, Vulkan

### Issue description

Enable convert_text_resources_to_binary in project settings will cause many scenes/resources not to be loaded/display properly in exported game. For example, some fonts, some scenes will not display properly.

### Steps to reproduce

1. Enable convert_text_resources_to_binary in project settings for a project with some Sprites/GUIs etc
2. Export the game
3. There is a good chance of noticing obvious resource/graphics errors in the exported game

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/12452.

@Xwdit Can you reproduce this on 3.4.2?

**Comment by fire** [comment]
Fixed by: https://github.com/godotengine/godot/pull/56185 On Reduz's review queue.

**Comment by Xwdit** [comment]
> 与#12452相关。
> 
> @Xwdit你能在 3.4.2 上重现这个吗？



> Related to #12452.
> 
> @Xwdit Can you reproduce this on 3.4.2?

No, everything works fine in 3.4.2

**Comment by akien-mga** [comment]
Fixed by #56185.
