### ISSUE TITLE
Instancing with right-click instances all the scenes

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#5795]
Tested on Godot 2.1 beta, Windows 10 64 bits

Repro:
[InstanceDoingMultiple.zip](https://github.com/godotengine/godot/files/370461/InstanceDoingMultiple.zip)
right-click any of the available scenes in the FileExplorer, and select "instance". Notice the editor will instance all the scenes in the current folder at once (including the opened scene itself, which causes an error).

Expected:
Instance only the selected scene under the selected parent.

**Comment by vnen** [comment]
I can reproduce this on latest master.
