### ISSUE TITLE
Select current project does nothing if scene is not saved.

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot#57958]
### Godot version

3.4.2

### System information

Manjaro, Vega 8 with Ryzen 3200 G

### Issue description

When you hit play for the first time, a window pop up appears if default scene is not selected.

However the select current button does nothing if the current scene being used is not saved yet.

### Steps to reproduce

Create new project.
Create new scene.
Hit play without saving the scene.
Hit select current scene button.

**Comment by Calinou** [comment]
I can confirm this on `master` a086a61ae and `3.x` a086a61ae.

On `master`, pressing Enter to select **Select Current Scene** will make the popup disappear for a split second then appear again.

I guess a good way to fix this would be to pop up the Save As prompt, *then* select the freshly saved scene as the main scene.

**Comment by IgorKordiukiewicz** [comment]
Duplicate: #57135
