### ISSUE TITLE
Instance scenes at current view position by drag and drop

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#5796]
In 2D (and possibly 3D), when nodes are instanced, they are always placed at the origin of the world. This makes me loose time when designing levels because I have to scroll to the origin to get the object and move it back to the place I was editing. The node should instead be positionned where I'm looking at.

In 2.1, a nice addition doing this would also to be able to drag and drop a scene (or right-click create a node) in the main view in order to place it at the mouse position. Currently this is not allowed.

**Comment by vnen** [comment]
Major problem with dragging a scene to the editor is to solve the question: what should be the parent of the instance? This is not trivial and already happens often that users forget to select the parent node before clicking the "Add Node" button.

However, adding the new node/instance to the center of the viewed area might be interesting.

**Comment by Zylann** [comment]
Well, there is always a selected node, and if what you say is true we would also have to remove RMB+instance :p

**Comment by akien-mga** [comment]
There's not always a selected node no.

**Comment by Zylann** [comment]
What happens when you RMB+instance then? Just have the same behaviour but with positionning at mouse pos :)

**Comment by bojidar-bg** [comment]
It is already possible to drag/drop scenes in 2.1.3, so I guess we can mark this as done?

**Comment by Zylann** [comment]
Is it working in 3D? Didn't tested this case

**Comment by Calinou** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Zylann** [comment]
In Godot 3.0.2:
It is not possible to drop a scene if the scene tree is empty (trivial: add it as root).
It is possible to drop a scene/create a node if there is a parent we can put it on, but it still appears at the origin and not where the view is looking at.

**Comment by akien-mga** [comment]
Tested in current master branch:

> It is not possible to drop a scene if the scene tree is empty (trivial: add it as root).

This kind of works but in a buggy way. Dragging a scene in an empty new scene (no root) does work to instantiate it, but it then also adds a new "[empty]" scene tab and focuses it, so it's quite weird.

>  It is possible to drop a scene/create a node if there is a parent we can put it on, but it still appears at the origin and not where the view is looking at, which is the point of this issue.

Indeed, dragging scenes to the viewport will instantiate them at the origin. However dragging images will properly add a Sprite instance at the drag location. Should be easy to fix the former by checking how the latter does it.

**Comment by KoBeWi** [comment]
Dropped scenes now appear where they are dropped at (except when dropping it on non-CanvasItem, see #26075). However it's also affected by #26549

So I guess this issue could be closed?

**Comment by akien-mga** [comment]
Indeed, thanks.
