### ISSUE TITLE
Vulkan: Billboard sprite with alpha tiles its texture when zooming away 

### ISSUE THREAD

**Issue by macryc** [godotengine/godot#57962]
### Godot version

4.0 alpha 2

### System information

Win10, GLES3, RTX 2070 mobile

### Issue description

When using AnimatedSprite3D or GPUParticles3D or CPUParticles3D with a transparent texture on a quad mesh and billboard enabled, the texture will produce weird tiling as you zoom away from it in the editor. This also causes the following set of errors to loop endlessly in the debugger:

E 0:00:15:0817   RendererStorageRD::material_is_animated: Condition "!material" is true. Returning: false
  <C++ Source>   servers\rendering\renderer_rd\renderer_storage_rd.cpp:1751 @ RendererStorageRD::material_is_animated()
E 0:00:15:0820   RendererStorageRD::material_get_instance_shader_parameters: Condition "!material" is true.
  <C++ Source>   servers\rendering\renderer_rd\renderer_storage_rd.cpp:1777 @ RendererStorageRD::material_get_instance_shader_parameters()
E 0:00:15:0822   RendererStorageRD::material_update_dependency: Condition "!material" is true.
  <C++ Source>   servers\rendering\renderer_rd\renderer_storage_rd.cpp:1789 @ RendererStorageRD::material_update_dependency()
E 0:00:15:0827   RendererStorageRD::material_set_shader: Condition "!material" is true.
  <C++ Source>   servers\rendering\renderer_rd\renderer_storage_rd.cpp:1654 @ RendererStorageRD::material_set_shader()

### Steps to reproduce

Start a 3d scene
add AnimatedSprite3D
add a frame texture (texture2d with alpha)
enable alpha
enable billboard
mouse wheel away from the sprite and watch what happens (see attached vid)

https://user-images.githubusercontent.com/82995330/153556553-6d4d0471-8465-4c3a-acd6-a7a9edd17893.mp4

**Comment by Calinou** [comment]
Like in https://github.com/godotengine/godot/issues/57981, can you reproduce this if you set the texture's compression mode to **Lossless** instead of **VRAM Compressed**?

**Comment by macryc** [comment]
> Like in #57981, can you reproduce this if you set the texture's compression mode to **Lossless** instead of **VRAM Compressed**? Also try disabling **Mipmaps** in the import dock and see if the issue persists.

Disabling mipmaps on import does not fix it. Importing as Lossless fixes it.

**Comment by lyuma** [comment]
Closing as likely fixed. I also recall seeing this a year ago but not recently. Reopen or comment if you still hit it in 4.0rc3
