### ISSUE TITLE
Making a Shader use Instance Uniforms, makes the parameter dissapear from inspector

### ISSUE THREAD

**Issue by JoanPotatoes2021** [godotengine/godot#57965]
### Godot version

v4.0.alpha2.official [79077e6c1]

### System information

Windows 10

### Issue description

Shader parameter when set to istance uniform dissapears.

### Steps to reproduce

- Create a shader
- Assign a color uniform
- Set the shader uniform to istance qualifier
- The parameter dissapears
![MakingShaderUniformInstance](https://user-images.githubusercontent.com/88800565/153579548-b0e807c0-2948-491f-9147-9fefa08e027b.gif)

### Minimal reproduction project

[InstanceUniformProject.zip](https://github.com/godotengine/godot/files/8048011/InstanceUniformProject.zip)

**Comment by Chaosus** [comment]
The shader params for instances should be located under Visibility Range:

![image](https://user-images.githubusercontent.com/3036176/153593301-825f3735-20fc-4c77-8173-312d31992594.png)

You may need to reload the scene - changes not applied immediately after adding a change to the shader.

**Comment by JoanPotatoes2021** [comment]
Yep, it's working properly, not a bug, seems like I didn't tested enough

![instanceUniform](https://user-images.githubusercontent.com/88800565/153593989-5972853f-1e96-4ba1-bfeb-e51b59a0b301.jpg)

Maybe we should write in the documentation or give a prompt to let the user know.

Thanks @Chaosus

**Comment by JoanPotatoes2021** [comment]
Not needed, reduz mentioned a re-write for 2D on this [pull #37949](https://github.com/godotengine/godot/pull/37949#issuecomment-615243951)
