### ISSUE TITLE
Zoom with mouse wheel in the new TextureRegion editor

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#5797]
Not much of an issue, but the old TextureRegion editor allowed to use the mouse wheel to zoom in and out. The new one doesn't, and you have to click the buttons on the top right (Windows 10 did that too in its new image viewer and I hate it :p).
Is it possible to have the mouse wheel back please? :3

**Comment by Hinsbart** [comment]
Since the new texture region editor has scrollbars, I would expect it to scroll when using the mouse wheel.
How about shift + wheel for zooming?

**Comment by Zylann** [comment]
I don't expect it to scroll because:
1) that's not how the previous editor behaved
2) there are two scrollbars, moving only one would not make sense

Also I never use the scrollbars, I do everything with the middle button for panning. In the end, scrollbars look like a fallback, or at least a quick view of where I am on the zoomed view.

**Comment by Hinsbart** [comment]
ahh well, most laptops can also scroll horizontally using the touchpad :P 
But yeah, if middle click for panning works, I guess it's not needed then.

**Comment by Hinsbart** [comment]
Oh, this has already been implemented by #6094 ^^

**Comment by akien-mga** [comment]
Indeed :)
