### ISSUE TITLE
Cant hide Windows 11 terminal

### ISSUE THREAD

**Issue by thepromaper** [godotengine/godot#57987]
### Godot version

3.4.2

### System information

Windows 11

### Issue description

![image](https://user-images.githubusercontent.com/72669769/153669198-9f42e737-847e-4fc1-989a-4eb155d1261b.png)
On windows 11 you have the option to make windows terminal the default command line experinece, making godot launch with a window of windows terminal with a CMD tab.

however this is still visible even with Hide Console Window enabled.

### Steps to reproduce

-install windows 11
-go to Privacy & security/for developers
-set windows terminal as default command line
-enable "Hide Console Window" on editor settings.
-restart godot.
-it still apears.

**Comment by akien-mga** [comment]
The "Hide Console Window" option is not supported by Windows Terminal. It was removed in 3.5 (together with refactoring so that no console window is shown automatically #55987).

We don't plan to backport that change to 3.4.x as it breaks compatibility.
