### ISSUE TITLE
CollisionShapes added to inherited scenes are ignored

### ISSUE THREAD

**Issue by henkz1** [godotengine/godot#5798]
**Operating system or device - Godot version:**
ubuntu 16.04, godot: https://github.com/godotengine/godot/commit/b49476a0119bd177341a2e974d62b591117efe3f

**Steps to reproduce:**
- Import scene, set "Custom root Node Type" to RigidBody
- create a new inherited scene with above scene as base
- in the inherited scene add a collision shape, with SphereShape or whatever.

Now instances of this scene will not collide with anything, however if you add a collision shape to
the base scene as well, run your game, then delete the shape from base scene, the inherited scene will keep colliding. But this step has to be repeated each time the base scene is reimported.

I use scn for base and tscn for inherited scene.

edit:
actually you don't have to start the game after creating collisionShape in base scene, just add it and delet it. With debug collision shapes enabled the shape in the inherited scene will be rendered, but the shape in use by physics is actually the one in base scene,which should be deleted.

**Comment by spookdogg** [comment]
Can confirm, however for me the base scene had a CollisionShape2D without any shape data and the instances all had shape data, no instances would collide
My OS was windows 7

Hope my info helps!

**Comment by vnen** [comment]
Likely the same problem as #2314, since CollisionShape nodes are editor helpers and in some cases they are not added to the physics object on start.

**Comment by kubecz3k** [comment]
I think this is fixed now
