### ISSUE TITLE
Game exported to iOS trough test flight or the app store doesn't have localization files

### ISSUE THREAD

**Issue by lucassardois** [godotengine/godot#57991]
### Godot version

Godot Engine v3.4.2 stable

### System information

Linux, Fedora 34, OpenGL ES 3.0 Renderer: Mesa Intel(R) UHD Graphics 620 (KBL GT2)

### Issue description

My exported app localization works as expected on android published on the play store. However on iOS for some reason the app installed trough test flight or the app store isn't localized while the app build from Xcode and running it on a physical device is localized.

### Steps to reproduce

Localize your project and export to xcode then to test flight or the appstore. The locale used is not the one from the system.

**Comment by akien-mga** [comment]
CC @godotengine/ios

**Comment by lucassardois** [comment]
In fact, this looks like this only happen when I add localization trough the xcode iterface to localize permissions access using the plist.

**Comment by naithar** [comment]
What are you using for localization? 
If you are using Xcode localization files, you might have setup localization incorrectly. 
To localize `.plist` files, you should use `InfoPlist.strings` file that are already added to the project. In it you should set localization for each `plist` string, like this `NSCameraUsageDescription = "Camera Permission String";`

**Comment by lucassardois** [comment]
Thanks I was going it the wrong way. It turns out that you must check languages boxes on the `InfoPlist.strings` and not on the file right above.

**Comment by indiejames** [comment]
I'm encountering the same problem with Godot 4.2. I have set up some localizations that work in the editor and work when I install it on my local device using XCode, but they are ignored when installing via TestFlight. I don't quite understand the statement "you must check language boxes." The InfoPlist files seem to be for iOS system things like NSCameraUsageDescription, whereas I'm trying to localize text in my game elements. Is there something I need to do in XCode beyond setting up localization files in the editor?
