### ISSUE TITLE
ItemList.sort_items_by_text() clears the item list 

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#5799]
I have a populated item list with thumbnailed items . When I do a sorting on it - all of it's items disappear.

Either I am doing something wrong or this is a bug in 2.1 beta

**Comment by akien-mga** [comment]
Could you provide a minimal example? (You can drag and drop a zip in the issue to upload it)

**Comment by blurymind** [comment]
@akien-mga  here is a minimal example:
[drag_n_drop_os_BUGWithSorting.zip](https://github.com/godotengine/godot/files/377314/drag_n_drop_os_BUGWithSorting.zip)

to reproduce bug:
1.Drag and drop a bunch of images onto the listitem. This will populate it with items - they are however not sorted by name.
2.Click on the top left button - it triggers the sort_items_by_text() method.

Expected behavior : Sort items by their name 
current behavior: The itemlist gets emptied

**Comment by akien-mga** [comment]
Thanks, I can reproduce it. Nice drag and drop usage :p

Just to be sure it was not an issue related to using icons or the various parameters you defined, I also simplified the example to check that the bug is reproduced with just:
```
func _ready():
	add_item("Some text 1")
	add_item("Hello world")
	add_item("Lorem ipsum")
	add_item("I need coffee")

func _on_Button_pressed():
	sort_items_by_text() # <<<------ BUG!
```

**Comment by akien-mga** [comment]
Found the bug, it's a typo :p

**Comment by akien-mga** [comment]
Need to work a bit more on it though as apparently the sorting behaviour does not work.

**Comment by blurymind** [comment]
Thank you :)
