### ISSUE TITLE
Built In Manual and Search Help Analogous to Built In Class Reference and Search Help

### ISSUE THREAD

**Issue by toliaferrode** [godotengine/godot#5800]
**Operating system or device - Godot version:**
Any OS, any Godot version

**Issue description** (what happened, and what was expected):
I know the project isn't at this point, but I'd like to request a built in manual describing Godot that is analogous to the class reference and search help. You'd access it from the 2D and 3D modes, similar to how you access the class reference and search help from the Script mode. I think it would help a lot of people out.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by akien-mga** [comment]
And what would it contain? :)

**Comment by toliaferrode** [comment]
Well the class reference had nothing in it when it started. :)

As well there were no tutorials at the beginning I would guess.

**Comment by akien-mga** [comment]
Well there are tutorials already (http://docs.godotengine.org/en/latest/), but I don't really see the point in embedding them in the editor (apart from the necessary conversion that would have to be done from reST to something parseable by Godot). The HTML format is much more suitable for such things than an embedded XML parser.

**Comment by toliaferrode** [comment]
Ah maybe you're right about that. I was just thinking since it worked for the class reference then it would work for manuals.

**Comment by akien-mga** [comment]
Personally I don't see this happening, it would be a lot of work for something that would look quite clunky in the end. I'd prefer that this time is spent on improving the documentation :)

**Comment by toliaferrode** [comment]
I agree. Thanks. :)
