### ISSUE TITLE
OccluderShapes don't currently work correctly with shared resources

### ISSUE THREAD

**Issue by lawnjelly** [godotengine/godot#58003]
### Godot version

3.4, 3.5 beta 1

### System information

All

### Issue description

If you duplicate an Occluder (such that the same OccluderShape is used in more than one Occluder) they will not behave correctly, as there is only one Occluder representation in the VisualServer.

So one occluder may appear to occlude things, and the other won't, until you apply "make unique", so that the resource is no longer shared.

This is an oversight on my part (sorry about that folks lol) :blush: not being familiar with how resources are intended to be used for shared data.

So I'm currently redoing some housekeeping so that the Occluders in the VisualServer are split into OccluderInstances (transform etc) and OccluderResources (data) which will fit this paradigm better and solve this bug. This is pretty simple but just a bit time consuming to fix.

### Steps to reproduce

Create an Occluder with OccluderShape, duplicate, then move the second around. Notice how one of them will not correctly occlude objects, until you "make unique".

## Notes
* This is just a stub issue as hopefully I should have this solved in a couple of days. Just in case another beta comes out before then.
* This was present with occluder spheres, but I guess you are less likely to just duplicate these, and I only noticed it with the polys.
* It is perfectly usable in the meantime, just remember to "make unique" after making any duplicates. :+1:

**Comment by akien-mga** [comment]
Fixed by #58141.
