### ISSUE TITLE
Tileset editor does not utilise `InputEventScreenDrag`

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#58014]
### Godot version

v4.0.alpha2.official [79077e6c1]

### System information

Mac OS

### Issue description

In 3.4.2 the tileset editor can be navigated using `InputEventScreenDrag`, however in 4.x this feature seems to be lacking, which is a shame as it's very useful.

### Steps to reproduce

1. Open 4.x editor
2. Create a tilemap
3. Add a tilemap texture
4. Zoom in
5. Try to nagivate using drag events (Mac)

**Comment by Calinou** [comment]
cc @groud @KoBeWi

**Comment by KoBeWi** [comment]
You just need to copy this code
https://github.com/godotengine/godot/blob/d3a6b6daaab4c8dfb7bdf35cc2fe2145ae6c22a1/editor/plugins/canvas_item_editor_plugin.cpp#L1196-L1217
somewhere here
https://github.com/godotengine/godot/blob/d3a6b6daaab4c8dfb7bdf35cc2fe2145ae6c22a1/editor/plugins/tiles/tile_atlas_view.cpp#L44-L48

I was thinking about adding touch controls to ViewPanner, so they could be supported in any editor using that class, but it requires another handler. Not sure if it's worth it.
