### ISSUE TITLE
Multimeshinstance3D use_custom_data can't be set by gdscript

### ISSUE THREAD

**Issue by croxis** [godotengine/godot#58019]
[Tmp2.zip](https://github.com/godotengine/godot/files/8054198/Tmp2.zip)
### Godot version

4.0 alpha 2

### System information

Linux

### Issue description

use_custom_data and cuse_colors can't be set via gdscript when setting up a multimesh in a multimeshinstance3d. Or I failed to read something correctly in the documentation.

```
init
ERROR: Condition "instance_count > 0" is true.
   at: set_use_custom_data (scene/resources/multimesh.cpp:289)
ERROR: Condition "instance_count > 0" is true.
   at: set_use_colors (scene/resources/multimesh.cpp:280)
init: 1 false
```

### Steps to reproduce

In an otherwise empty project:

```
extends MultiMeshInstance3D

func _ready():
	print("init")
	multimesh.instance_count = 1
	multimesh.use_custom_data = true
	multimesh.use_colors = true
	print("init: ", multimesh.instance_count, " ", multimesh.use_custom_data)
```

**Comment by vfig** [comment]
This is a documentation issue. Both [Optimization Using MultiMeshes](https://docs.godotengine.org/en/latest/tutorials/performance/using_multimesh.html) and [Animating thousands of fish with MultiMeshInstance](https://docs.godotengine.org/en/latest/tutorials/performance/vertex_animation/animating_thousands_of_fish.html) note that the transform format, and color/custom options must be set _before_ setting `instance_count`. To quote the latter:

> `instance_count` specifies how many instances of the mesh you want to draw. For now, leave `instance_count` at 0 because you cannot change any of the other parameters while `instance_count` is larger than 0. We will set `instance_count` in GDScript later.

But this restriction is not mentioned at all in the [MultiMesh](https://docs.godotengine.org/en/latest/classes/class_multimesh.html) api reference entry.
