### ISSUE TITLE
Vulkan: Viewport lines redrawn without being cleared

### ISSUE THREAD

**Issue by SushilRagoonath** [godotengine/godot#58011]
### Godot version

4.0 Master branch

### System information

Windows 10 Vulkan Desktop Nvidia Quadro

### Issue description

The lines in the main editor viewport is not being cleared and being redrawn
![Screenshot_1](https://user-images.githubusercontent.com/48589447/153715307-ff9e4325-bb1e-4ed7-b1cc-ad46be0522e5.png)
![Screenshot_2](https://user-images.githubusercontent.com/48589447/153715308-557b19c7-7e57-4323-a395-f982f2112085.png)
![Screenshot_3](https://user-images.githubusercontent.com/48589447/153715310-5473229d-1327-445c-ba44-a5d9220abc35.png)
.

### Steps to reproduce

Started after I exported my project, this caused some other bug so I restarted and now it is like this. Do not know the exact steps to reproduce.

**Comment by SushilRagoonath** [comment]
Update : the issue does not appear in a new scene, but the old scene still has the issue

**Comment by Calinou** [comment]
@SushilRagoonath Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by akien-mga** [comment]
Is this fixed?

**Comment by SushilRagoonath** [comment]
No, but I don't know what is required by the minimal reproduction project. It was experienced by any project. Another important note is that it reset after reloading the scene. I currently not using Godot so I cannot confirm the state of this on master
