### ISSUE TITLE
Godot 4: Wrong documentation page is opened when clicking on `ConfigFile.load()`

### ISSUE THREAD

**Issue by gustavi** [godotengine/godot#58017]
### Godot version

v4.0.alpha2.official [79077e6c1]

### System information

Windows 10 64bit - Vulkan API 1.2.141 - GeForce GTX 1660 SUPER

### Issue description

When you `Ctrl` + click on `load` in `ConfigFile.load()` you are redirected on `GDScript` documentation and not on `ConfigFile` documentation.

Only 4.0 is affected (tested on `4.0-dev.20210727` and `4.0-alpha2`).

### Steps to reproduce

From [documentation](https://docs.godotengine.org/en/latest/classes/class_configfile.html):

```gdscript
var config = ConfigFile.new()
var err = config.load("user://scores.cfg")
```

1. `Ctrl` + `left click` on `load`
2. It open `GDScript.load()` documentation, not `ConfigFile.load()`

### Minimal reproduction project

See 2 lines of code in "Steps to reproduce" section.

**Comment by jmb462** [comment]
In method : https://github.com/godotengine/godot/blob/d3a6b6daaab4c8dfb7bdf35cc2fe2145ae6c22a1/modules/gdscript/gdscript_editor.cpp#L2969

Before parsing the file, it looks for method with the same name in base @GDScript builtin function :
https://github.com/godotengine/godot/blob/d3a6b6daaab4c8dfb7bdf35cc2fe2145ae6c22a1/modules/gdscript/gdscript_editor.cpp#L2986-L2991

As ``load`` method exists in @GDScript; it doesn't even check further.
_lookup_symbol_from_base() isn't call and correct class_name isn't found.
@GDScript method is used as a result.

**Comment by gustavi** [comment]
I also note that `# load()` in a comment is Ctrl clickable and redirect into documentation. Is that an expected behavior ?

**Comment by Calinou** [comment]
> I also note that `# load()` in a comment is Ctrl clickable and redirect into documentation. Is that an expected behavior ? I don't find this behavior in major IDEs.

I'm neutral about it, as you may want to be able to click on it if the code was temporarily commented out. This can also be useful when referencing a function name within a comment.
