### ISSUE TITLE
[4.0 alpha 2] SubViewport Transparent Background setting does not work

### ISSUE THREAD

**Issue by macryc** [godotengine/godot#58015]
### Godot version

4.0 alpha 2

### System information

Win10, GLES3, RTX 2070 mobile

### Issue description

SubViewport Transparent Background setting doesn't do anything when it's on. There is no difference whether it's on or off - I can see the background therefor I can only see what the viewport camera is showing and not the main camera.

### Steps to reproduce

see attached project

### Minimal reproduction project

[Viewport.zip](https://github.com/godotengine/godot/files/8054067/Viewport.zip)

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/40651.
