### ISSUE TITLE
Godot 4 can't rename function in Visual Script

### ISSUE THREAD

**Issue by kreaninw** [godotengine/godot#58021]
### Godot version

v4.0.alpha2.official [79077e6c1]

### System information

Windows 11, Vulkan Clustered, Intel UHD Graphics 620 v30.0.101.1340

### Issue description

I can't rename a newly created function in Visual Script, as shown in the screen recording below:

https://user-images.githubusercontent.com/1403194/153722798-6d3e41bf-5d3b-44ed-9b91-2bb8c4babf88.mp4

I expect to be able to rename the function.

### Steps to reproduce

1. Create a new function.
2. Rename the function.
3. The function won't get renamed.

**Comment by Calinou** [comment]
@kreaninw @jmb462 Can you reproduce this in 3.4.2? (Given the issue title, I don't think so, but it's important to make this explicit :slightly_smiling_face:)

**Comment by kreaninw** [comment]
> 

I am porting my demo from 3.4.3-rc1 to 4.0-alpha2. I can't reproduce this issue in 3.4.3-rc1.
