### ISSUE TITLE
Godot 4 TileMap : duplication of tiles from a scenes collection

### ISSUE THREAD

**Issue by pyacier** [godotengine/godot#58034]
### Godot version

v4.0.alpha2.official [79077e6c1]

### System information

Ubuntu 20.04.3 LTS

### Issue description

In the case of a TileMap with a TileSet where as tile sources there are a scenes collection and a .png. When playing the scene, there seem to be a duplication of the tiles that are scenes.

In the case of an empty TileMap with only ONE tile that is a scene in it, if the scene has a script like this:

`func _ready() -> void:
	print(self)`

That output is like that:
 
`Sprite2D:[Sprite2D:23253222497]
@Sprite2D@2:[Sprite2D:23269999712]`

One of the two is rapidly freed.

### Steps to reproduce

Create a new project.
Create a new Sprite2D with the icon.png as texture and add a script to it with that:

`func _ready() -> void:
	print(self)`

Create a TileMap, add a new TileSet to it.
Create a new scenes collection, drag and drop your Sprite2D.tscn int it.
In the TileMap place one tile.
Play the scene, the output should like that:

`Sprite2D:[Sprite2D:21256733041]`

Stop the scene, go back in the TileSet, drag and drop the icon.png under the scenes collection (not in it).
Play the scene, the output should like that:

`Sprite2D:[Sprite2D:23253222497]
@Sprite2D@2:[Sprite2D:23269999712]`

### Minimal reproduction project

[mrp.zip](https://github.com/godotengine/godot/files/8054671/mrp.zip)

**Comment by KoBeWi** [comment]
The instances are created inside `_update_dirty_quadrants()`. First during `NOTIFICATION_ENTER_TREE` and then in `_tile_set_changed()`. I guess the latter shouldn't normally happen at runtime.

Another thing is that whenever the internals are re-created, the scenes are removed and instantiated again. Should it really happen? If someone uses `force_update()` for whatever (most likely unrelated) reason, their scenes will be reset.

**Comment by riazey** [comment]
Still an issue in alpha11.

I noticed while figuring out this bug existed that only some nodes were being recreated when instanced with `set_cell()`. I added a tree_exited func to see which ones were being "reset" and it seemed like the closer they were to the new cell the more likely they were being reset but that could have been by chance. I replicated this in two fresh projects.

It's been a while but I am still very excited to see this fixed, I really want to try implementing some cool things with scene tiles <3


![be62debf95b2c75ae1e7afb8c581399b](https://user-images.githubusercontent.com/75141902/177875013-b8532e79-dfab-4bf0-b924-495b838ba8bd.png)

![8b5c100a6dab17d6f4c49bcab337767a](https://user-images.githubusercontent.com/75141902/177875034-f61df4e1-9fd2-41ea-b82a-a1140fb244ca.png)

**Comment by salmonmoose** [comment]
This appears to occur to any node based tile and is triggered - my tilemap contains both regular tiles and node based tiles and updates the regular tiles during gameplay - this causes node based tiles to be recreated in their initial positions with new identities.

**Comment by 1Luc1** [comment]
> ...
> Another thing is that whenever the internals are re-created, the scenes are removed and instantiated again. Should it really happen? If someone uses `force_update()` for whatever (most likely unrelated) reason, their scenes will be reset.

> I noticed while figuring out this bug existed that only some nodes were being recreated when instanced with `set_cell()`. I added a tree_exited func to see which ones were being "reset" and it seemed like the closer they were to the new cell the more likely they were being reset but that could have been by chance. I replicated this in two fresh projects.
> ...

As of Godot 4.0.alpha14 I encountered that exact problem, that alternative_tiles from an scenes collection got instantiated again.

I figured out, that this only happens if using `set_cell()` with a layer where y-sort is not enabled. Enabling y-sort for that layer "fixes" this issue, or at least it's a workaround.
