### ISSUE TITLE
Godot 4: variable from members' window doesn't get its type updated correctly in the Visual Script canvas

### ISSUE THREAD

**Issue by kreaninw** [godotengine/godot#58035]
### Godot version

v4.0.alpha2.official [79077e6c1]

### System information

Windows 11, Vulkan Clustered, Intel UHD Graphics 620 v30.0.101.1340

### Issue description

In Godot 4, the variable from the members' window (script variable) doesn't get its type updated correctly as shown in the screen recording below:

https://user-images.githubusercontent.com/1403194/153731457-52be01b3-b21a-46cf-8e88-333d95e080de.mp4

I expect the variable's **PropertyGet** node to show its type correctly. 

### Steps to reproduce

1. Create a variable in the members' window.
2. Drag the variable to the script canvas.
3. Try to change the property in the inspector's window, the variable type will not be updated at all if the property belongs to the script.

**Comment by KoBeWi** [comment]
Can't test, because Script Variables don't appear in 08e540a :/

**Comment by KoBeWi** [comment]
VisualScript was removed in Godot 4.0, so closing.
