### ISSUE TITLE
TileMap randomly freezes the editor while editing

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#58039]
### Godot version

26b21dc

### System information

W10

### Issue description

Sometimes when you edit tiles and exit the editor, this happens:
![cmd_Z1sXb6zVBy](https://user-images.githubusercontent.com/2223172/153735229-9a73baca-be46-4759-bfbf-a7d54c6fcffe.gif)
```
ERROR: Disconnecting nonexistent signal 'changed', callable: TileDataEditor::_tile_set_changed_plan_update.
   at: (core/object/object.cpp:1411)
```
The editor will freeze indefinitely and you need to force-close it.

### Steps to reproduce

1. Have some TileMap
2. Edit it, idk
3. Exit Godot
4. There's a chance this issue happens

**Comment by Dodoveloper** [comment]
Same error for me on Linux, just with a tiny difference:
```
ERROR: Disconnecting nonexistent signal 'changed', callable: TileMap::_tile_set_changed.
   at: _disconnect (core/object/object.cpp:1378)
```
It first happened when editing a TileMap, specifically when trying to add some navigation logic to the tileset.
For me it's somehow escalating to the point that I can't even open the TileMap without triggering this error.

I tried deleting the project's folder under `.local/share/godot/app_userdata/` but no luck.

**Comment by KoBeWi** [comment]
This seems to be happening also when changing scenes and now I just had it happen while editing tiles. It's rather uncommon, but can crash (freeze) the editor.

**Comment by KoBeWi** [comment]
Ok found a 100% way to reproduce it. Just change the layer modulate a lot:
![explorer_cAqRnJmVcv](https://user-images.githubusercontent.com/2223172/188283618-3252a44b-3259-4ac7-b973-6a5be3bd6ed3.gif)

**Comment by KoBeWi** [comment]
I tried to look into the issue based on my last findings, but the bug does not happen in debug builds (at least with the steps above). I got some stack trace in a `release_debug` build, but it's not very useful. The failed disconnection happens as a result of some (SubViewport I think) node being freed. So it might be unrelated and just a result of something else.

**Comment by farfalk** [comment]
hi everyone, on godot4 beta 3 (Windows 10, process spawned through powershell) I'm getting spammed with these errors **everytime I try to paint a physics property on a tileset.** Is this related to this issue in your opinion? It's quite critical, because the editor completely hangs when this happens (and needs a forced shutdown, with potential data loss for unsaved changes)
![image](https://user-images.githubusercontent.com/9095842/196676744-bdc84f1d-ceed-4add-96b2-699481d698e7.png)

**Comment by KoBeWi** [comment]
Yeah looks very similar. It's weird that you get this every time you paint though. Does it happen in a new project?

**Comment by farfalk** [comment]
> Yeah looks very similar. It's weird that you get this every time you paint though. Does it happen in a new project?

I've been trying to replicate the issue in other projects for days, without success... 
In my current project, UNTIL TODAY, it used to happen every time I did this particular sequence of actions:
- Inside the current scene tree, I delete an imported scene containing a single TileMap with an already defined TileSet
- I import another scene containing another TileMap, with another already defined TileSet
- this TileSet doesn't have a physics layer, so I open the imported scene, open the TileSet resource and create one
- I open the tileset menu, select the paint property, and paint the newly created physics layer.
- => hang on error spam.

... but today it doesn't happen anymore. I don't know what to think.

**Comment by farfalk** [comment]
> > Yeah looks very similar. It's weird that you get this every time you paint though. Does it happen in a new project?
> 
> I've been trying to replicate the issue in other projects for days, without success... In my current project, UNTIL TODAY, it used to happen every time I did this particular sequence of actions:
> 
> * Inside the current scene tree, delete an imported scene containing a single TileMap with an already defined TileSet
> * import another scene containing another TileMap, with another already defined TileSet
> * draw some tiles in the scene
> * remember that the TileSet doesn't have a physics layer, so open the imported scene, open the TileSet resource and create one
> * open the tileset menu, select the paint function, and try to paint the newly created physics layer.
> * => editor hangs on error spam.
> 
> ... but today, WITH NO CHANGE AT ALL, it doesn't happen anymore even in the project that used to suffer the error. I don't know what to think.

https://user-images.githubusercontent.com/9095842/197503087-fd15b010-559b-44b4-8c94-f5f12b9efb12.mp4



@KoBeWi I think I got it. It depends only on SPEED of property painting, as you similarly described in https://github.com/godotengine/godot/issues/58039#issuecomment-1236177994. If I paint one tile at a time, it doesn't hang - if I click and drag to paint more than one tile and do it for a while, it begins the error spam.

**Comment by KoBeWi** [comment]
Seems like I can't reproduce it either by using the method I mentioned before, but the issue is pretty random, so I'd wait to see if it's really fixed (which I doubt tbh).

**Comment by KoBeWi** [comment]
Eh, it hasn't happened in a couple of months, so closing for now.
