### ISSUE TITLE
Drop down menus in editor close as soon as mouse enters them on Xmonad (DisplayServer regression)

### ISSUE THREAD

**Issue by cumber** [godotengine/godot#58044]
### Godot version

4.0.dev.custom_built (26b21dc0cb517f9baacdaceafe09285952540d6a)

### System information

Nixos, Xmonad (a tiling window manager)

### Issue description

When I open click on an item in the menu bar at the top, the menu appears but then closes as soon as the mouse moves over it. The same appears to be true of any drop-down menu in the Inspector pane.

I was able to use these menus anyway by using the arrow keys to navigate the menu after clicking to open it.

Right click menus in the scene tree are completely unusable; they appear when I right click but then immediately close.

I suspect this must be somewhat related to other issues reported with child windows in Godot 4.0, like #39596, #37930, and #55415. It may be exactly the same underlying issue and this is just how it manifests in Xmonad, but I couldn't find an issue reporting exactly this symptom.

Reading through those issues to see if this had already reported I did find `--single-window` suggested as a workaround, and it does avoid this problem for me, too.

### Steps to reproduce

Open any menu from the top menu bar, then try to move the mouse over a menu item. The menu closes as soon as the mouse enters it.

I suspect this problem will appear when running Godot 4.0 in an Xmonad session on any distro, which would be easier than setting it up in Nixos if you don't already have nix builds.

### Minimal reproduction project

No specific project is needed to observe the problem.

**Comment by mxnemu** [comment]
Can confirm this also happens on 4.alpha3 XMonad Ubuntu 20.04. It's very easy to reproduce.

**Comment by Calinou** [comment]
Closing per @permelin's comment. Please comment if you can still reproduce this **on Xmonad** (not on any other window manager or OS).

**Comment by cumber** [comment]
I hadn't fired up Godot in a while; I can confirm that I'm no longer having this problem, so I don't have to use --single-window anymore. Thanks!

**Comment by mxnemu** [comment]
Thanks for the fix! I can confirm it's fixed in beta1 on Ubuntu 20.04
