### ISSUE TITLE
Load Errors dialog only show when reloaded the project.

### ISSUE THREAD

**Issue by CSaratakij** [godotengine/godot#5805]
**Operating system or device - Godot version:**
Lubuntu 16.04LTS (32 bit)
Godot Engine version : v.2.0.4.1.stable.official

**Issue description** (what happened, and what was expected):
Assume that you already open the project.
When you remove the assets that node is depends on for example sprite node with loaded image.
After removed the assets and click play(F5), You can't run the game (game crash) and no error dialog about broken dependencies or load errors has show.
Unless, you reload the project and the load errors dialog will show. But it'll never show before you click to play the game.
![after_reload_project](https://cloud.githubusercontent.com/assets/9628627/16945828/f3fcdef2-4dd0-11e6-9b28-fcdadbea834a.png)
//I think load errors dialog should show every time you are about to play the game but the node dependencies is broken.

**Steps to reproduce:**
1) Open the project
2) Remove the assets : images/monster/enemy_dummy_r_96.png
3) Play the project (F5) and the game will crash and load errors dialog will not show.
4) Reload this project
5) Now load errors dialog will show and after you close its dialog and play the game, loads errors dialog will not show.

**Note:**
When you remove the assets in the godot engine, this dialog will warn you about its dependencies.
![when_remove_assets_within_godot_engine](https://cloud.githubusercontent.com/assets/9628627/16946417/97492ef6-4dd3-11e6-91fe-3603c46def05.png) 
But if you remove the assets in the file explorer(default os file explorer not file system's tab in godot engine), you will never know if you accidently broke the dependencies. After click to play the game, no loads errors dialog will show. (same issue)

**Link to minimal example project** (optional but very welcome):
[Test.tar.gz](https://github.com/godotengine/godot/files/371105/Test.tar.gz)

**Comment by Calinou** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.
