### ISSUE TITLE
Removing and re-adding child CSG shape stops collision mechanics

### ISSUE THREAD

**Issue by lfry512** [godotengine/godot#58050]
### Godot version

v3.4.stable.official [206ba70f4]

### System information

Ubuntu 20.04.3 LTS

### Issue description

Hi there, when I remove a 3D collision CSG shape from a scene and add it again, ```intersect_ray``` no longer returns hits but the shape renders normally. I'm not sure if this is a bug but my expectation is that the collision mechanics should still be active upon re-adding the shape to the scene. The shape flag ```use_collision``` is unchanged after removal and re-addition to the scene tree apparently. I tried understanding what might be happening from the ```add_child``` and ```remove_child``` source code but nothing stands out to me.

I attach a minimal test project that tests both in-script and editor instanced collision shape in case that matters.

### Steps to reproduce

Run the minimal reproduction project attached. Double click to remove and add the collision shape. See the console output, after re-adding the collision shape, no hits are triggered when mouse is hovered over object.

### Minimal reproduction project

[ColliderTest.zip](https://github.com/godotengine/godot/files/8055652/ColliderTest.zip)

**Comment by Calinou** [comment]
As a workaround, you can likely modify the CSG shape's geometry slightly after readding it to the scene tree. This will cause it to regenerate its collision.

**Comment by lfry512** [comment]
Thanks Calinou,

> If you enable **Debug > Visible Collision Shapes** and run the project, can you still see the generated trimesh collision for the CSG shape after it was readded to the scene tree?

I do not see a detected collision whether that option is true or false ,upon readding the shape to the tree. In both cases the geometry is not rendered when removed from the tree.

> As a workaround, you can likely modify the CSG shape's geometry slightly after readding it to the scene tree. This will cause it to regenerate its collision.

Thanks for suggestion, this appears to not work either however: After readding, I tried to increase the radial segment and ring count of the CSG sphere and although the assignment works, the rendered shape is not drawn as expected. It appears to have the same parameters as when first initialised.

My current workaround is to just reinitialise it and that does work.

**Comment by akien-mga** [comment]
Fixed by #58938.
