### ISSUE TITLE
[4.0] Alpha 2 - Contextual menus disappearing (DisplayServer regression)

### ISSUE THREAD

**Issue by Rinocrosser** [godotengine/godot#58057]
### Godot version

4.0 Alpha 2

### System information

Windows 10, GPD Win Max 2020

### Issue description

https://user-images.githubusercontent.com/19660324/153767413-a3d560a6-c8a6-4bbb-812d-9c9fd802fc1d.mp4

Instead of being opened and allow me to press something, each contextual menu opens, receives click from cursor position and instantly disappear. This sort of double click only appears in Godot 4.

### Steps to reproduce

Open the project
Right click in file browser, for example

**Comment by Calinou** [comment]
Can you reproduce this after enabling **Single Window Mode** in the Editor Settings then restarting the editor?

**Comment by Rinocrosser** [comment]
> Can you reproduce this after enabling **Single Window Mode** in the Editor Settings then restarting the editor?

Yes, the issue is the same, just the window border of the pop-up is different

**Comment by akien-mga** [comment]
I'm pretty sure this was fixed a while ago.
