### ISSUE TITLE
NavigationRegion2D crashes engine when adding inner outlines

### ISSUE THREAD

**Issue by felaugmar** [godotengine/godot#58051]
### Godot version

v4.0.alpha2.official [79077e6c1]

### System information

Windows 10

### Issue description

`NavigationRegion2D` crashes engine when adding inner outlines.

### Steps to reproduce

The example below was made in v3.4.2.stable.official [45eaa2daf] (with `NavigationPolygonInstance`).

Trying to replicate the same in v4.0.alpha2.official [79077e6c1] (with `NavigationRegion2D`) works as expected when creating the first outline polygon, but crashes when about to finish the second.

![image](https://user-images.githubusercontent.com/11199582/153756608-200b3654-632f-417a-92c8-9c59f4b2f64d.png)

### Minimal reproduction project

The project would crash the engine, so it's best to follow the example in **Steps to reproduce**.

**Comment by Scony** [comment]
Cannot repro on latest `3.x`, linux

**Comment by JoshuaWeissTBS** [comment]
Can confirm

**Comment by smix8** [comment]
Cannot recreate the issue.

Created multiple NavigationRegion2D with such inner outline. Not a single crash and pathfinding with edge merges works just fine. Could even build 10-layered polygon matryoshka with multiple inner outlines stacked without a single issue.

**Comment by felaugmar** [comment]
> Cannot recreate the issue.
> 
> Created multiple NavigationRegion2D with such inner outline. Not a single crash and pathfinding with edge merges works just fine. Could even build 10-layered polygon matryoshka with multiple inner outlines stacked without a single issue.

Are you using a version newer than _v4.0.alpha2.official [79077e6c1]_ ?

**Comment by smix8** [comment]
@felaugmar 
Yes most recent one from today commit 23207fcfddf47f17a749c1fa8424c11769610b31

**Comment by felaugmar** [comment]
🤔 

@Calinou: [@smix8 ](https://github.com/godotengine/godot/issues/58051#issuecomment-1127122515) could not reproduce the issue in recent builds, it was probably already solved.

**Comment by smix8** [comment]
@akien-mga 
Issue solved, can be closed.

**Comment by felaugmar** [comment]
It's probably a good idea to identify what changed that fixed this issue.
If anyone finds any clues about it, please comment here.
