### ISSUE TITLE
WebSockets for Godot

### ISSUE THREAD

**Issue by Biarity** [godotengine/godot#5806]
WebSockets are really simple to use, esp. when creating multiplayer games. I am suggesting there be a WebSocket node in Godot 3. That way one can easily create a client & hook it up to an existing server effortlessly.

I don't know if WebSockets are already supported in the current networking model, but so far I haven't seen mention of it anywhere & I wouldn't know how to implement it using the HTTP nodes. Sorry if this issue is a result of my ignorance.

**Comment by bojidar-bg** [comment]
Better yet, make it a `WebsocketStreamPeer` or similar.

@godotengine/bugsquad I'm tagging this for 2.2, since networking.

**Comment by bojidar-bg** [comment]
@Qudware Oh, and BTW, you can already connect to/serve websockets via the relatively low-level TCP classes.

**Comment by Qudware** [comment]
@bojidar-bg do you know of any resource on how to do that? I tried reading the docs but so far the networking section only has descriptions of simple HTTP requests.

**Comment by vnen** [comment]
There's this: https://github.com/marcosbitetti/Godot-Websocket

**Comment by punto-** [comment]
Websockets will be supported soon, it's part of the tasks we're doing for
the Mozilla prize.

**Comment by paper-pauper** [comment]
@punto- Link for the Mozilla prize you are referring to, please?

**Comment by akien-mga** [comment]
https://godotengine.org/article/mozilla-awards-godot-engine-part-moss-mission-partners-program

**Comment by mclark4386** [comment]
I would love to help with this if possible! Where is the branch this is being worked on?

**Comment by akien-mga** [comment]
@mclark4386 It's not being worked on for the time being, the priority goes to the GLES 3/WebGL 2 renderer for now.

**Comment by mclark4386** [comment]
Ah! Thanks @akien-mga

**Comment by mclark4386** [comment]
@akien-mga Who should I talk to about Websocket integration? I'm about to do it anyways... only makes sense to do it in such a way that everyone can use it!

**Comment by akien-mga** [comment]
Best would be to come around on #godotengine-devel on Freenode's IRC network and discuss it with @reduz if he's up to it :)

**Comment by mclark4386** [comment]
Will do! Thanks!

**Comment by mclark4386** [comment]
Ok, so currently my plan is to base the server off of TCPServer and the Client off of StreamPeerTCP... maybe see if I can't get away with using HTTPClient or request for the handshake. Please let me know if this will not work with any current plans or whatever! Also, open to any thoughts or suggestions! Thanks!

**Comment by AkiraKeals1992** [comment]
https://blog.mozilla.org/blog/2016/06/22/mozilla-awards-385000-to-open-source-projects-as-part-of-moss-mission-partners-program/

> Godot Engine: $20,000. Godot is a high-performance multi-platform game engine which can deploy to HTML5. This award will be used to add support for **Web Sockets**, WebAssembly and WebGL 2.0.

It's been over a year, what's going on? Did reduz and akien take the money and run?

**Comment by RandomShaper** [comment]
I don't get your point. Can you develop that?

**Comment by reduz** [comment]
> So much for helping out FLOSS projects, eh? Pathetic

This feature is still being worked on. but It's difficult to do add without some hack. The idea is to do it in the smoothest way possible. 

Regarding the help from Mozilla, you probably ignore that, after that announcement, there were many months of bureaucracy until the contract could be finally be put into work. We are still in time for delivering, so by the time 3.0 comes out, all the items will be accomplished.

**Comment by mclark4386** [comment]
Sorry I've been so MIA I got a base structure for Websocket handling in C++ and then that project got shutdown at my company and I just haven't had time. I'm happy to make a gist or something if anyone is interested, but it's fairly basic IIRC(initial pairing more or less) so I don't know how useful it'll be.

**Comment by Faless** [comment]
> I'm happy to make a gist or something if anyone is interested

@mclark4386 please do :smile: . I'm exploring the possibility of picking up this task, and your gist would definitely help, at least for reference.

**Comment by mclark4386** [comment]
here is the testing project I made for looking the protocal/getting it going for godot: https://github.com/mclark4386/WebsocketsPlay

**Comment by Faless** [comment]
Update
-
Work in progress for WebSocket Client/Server module using libwebsocket.org here: https://github.com/LudiDorici/godot-lws

**Comment by tximiss** [comment]
how is going websockets integration? It will have secure websockets support?
thank you,

**Comment by sdzyba** [comment]
Is it going to be done before the announced [3.0 beta feature freeze](https://github.com/godotengine/godot/issues/12543)?

**Comment by Dillybob92** [comment]
I actually just finished converting my websocket game server (30k loc js/nodejs) to a TCP one. Because Juan and others said this was going to come out later and I just don't didn't want to wait :P 


Wasn't that difficult, just had to get the messages from the stream and pass them into each game function. 

However, something like this https://www.npmjs.com/package/uws is the most powerful websocket libray for nodejs, and I think I would feel more comfortable switching back to it instead.

Websockets really do make it easier for game developers because you don't have to managing the entire "stream" system. And there are also a lot of benchmark out already.  

With all that said, I think we must give a moment of appreciation to @Faless's valiant efforts to get WS finally implemented into the core. It is truly appreciated and hope this can get into 3.0!

**Comment by mhilbrunner** [comment]
Is it still planned to get this into core? @Faless still working on this?
This should probably be moved to the 3.1 milestone (or be closed?) as the last work done on it was ~1.5 months ago?

**Comment by Faless** [comment]
> Is it still planned to get this into core?

We are still unsure about it, it will likely end up being a GDNative module for 3.0. The library I worked on is `LGPLv2 + static linking exception`, which should be compatible with Godot's MIT without adding restrictions, but still makes some developers uneasy.

> @Faless still working on this?

Yes, but I don't have much time right now, I hope to bring better news at GodotCon 2018 in February by working more on it during the holidays.

> This should probably be moved to the 3.1 milestone

Yes, it makes sense, but I'm still trying to make it available as a `3.0` GDNative module.

**Comment by mhilbrunner** [comment]
No worries, I was just wondering what the status on this was since I'm currently trying to get into the networking side of Godot.

Your work is appreciated :)
Hyped for GodotCon! (And more news on anything Websockets)

**Comment by Faless** [comment]
See https://github.com/LudiDorici/godot-websocket for an implementation of WebSocket client and server with both desktop and and webassembly platform (webassembly is for obvious reasons client only).
It supports both binary and text mode, sub-protocols, and even the new High Level Multiplayer API.

**Comment by akien-mga** [comment]
The websocket module will be merged for Godot 3.1 as we ran out of time for 3.0, so that issue will be solved then.
