### ISSUE TITLE
Godot 4: Visual Script node's Instance Call Mode incorrectly sets the Base Script box to always be the script path even though the Base Type has changed

### ISSUE THREAD

**Issue by kreaninw** [godotengine/godot#58069]
### Godot version

v4.0.alpha2.official [79077e6c1]

### System information

Windows 11, Vulkan Clustered, Intel UHD Graphics 620 v30.0.101.1340

### Issue description

Visual Script node's **Instance Call Mode** incorrectly sets the **Base Script** box to always be the script path even though the **Base Type** has changed. The user is impossible to search the available functions from the selected base type, hence choosing the base type would be meaningless.

In the screen recording below, I show how to add the **as_text()** function that's belonged to the **InputEventKey** base type in Visual Script. However, since the base script is always set to be the script path, I can't call the function from the corresponding base type:

https://user-images.githubusercontent.com/1403194/153777713-3479fb7d-d808-4b99-87f5-5db540b6741a.mp4

This behavior is a regression from Godot 3.4, as shown in the screen recording below:

https://user-images.githubusercontent.com/1403194/153777760-8fc28ce8-f115-4ca0-90fa-04e9185b4ab9.mp4

I expect the **base script to be emptied by default** so it won't conflict with the base type box and I will be able to search available functions based on the selected base type.

### Steps to reproduce

1. Add a call function in Visual Script.
2. Change the call mode to "Instance".
3. Change the base type to "InputEventKey".
4. Search the function that you want to call from the InputEventKey base type. However, you won't be able to search the available functions from the selected base type.

**Comment by Calinou** [comment]
cc @Gallilus

**Comment by Gallilus** [comment]
Calinou, Thanks for pinging me.
This functionality is indeed changed by me.
When creating new nodes it tries to set base script so better suggestions may be given when looking for things.

So I see three possible solutions.
- Keep working is in 2022-02-13.18-55-38.mp4 
- When changing the BaseType we empty BaseScript. [disadvantage: CalMode Self will be less effective after this]
- When BaseType and BaseScript.BaseType is not the same we ignore one [disadvantage: which one do we ignore?]

@kreaninw any thoughts?

**Comment by kreaninw** [comment]
> Calinou, Thanks for pinging me. This functionality is indeed changed by me. When creating new nodes it tries to set base script so better suggestions may be given when looking for things.
> 
> So I see three possible solutions.
> 
> * Keep working is in 2022-02-13.18-55-38.mp4
> * When changing the BaseType we empty BaseScript. [disadvantage: CalMode Self will be less effective after this]
> * When BaseType and BaseScript.BaseType is not the same we ignore one [disadvantage: which one do we ignore?]
> 
> @kreaninw any thoughts?

If the BaseScript isn't emptied by default, setting BaseType would be meaningless as the functions related to the BaseType wouldn't be included in the searchable function list.

When the users change their Call Mode from _Self_ to _Instance_, it means that:

1. They want to apply the function to another object other than self.
2. They want to call the function outside of the ones available in the current BaseType, so they change the BaseType.

The use-case #2 happens all the time, for example, the InputEvent related functions.

My thought on this is to respect the BaseType. We can empty the BaseScript by default. And when the users want to use the other BaseScript, they can specify this manually. 

However, there's one thing I don't understand. Since the users can't change the BaseScript of a function to be called in _self_ mode, why would the emptied BaseScript in _instance_ mode make a function call in _self_ mode be less effective?

**Comment by Gallilus** [comment]
The value in BaseScript is still used when searching Self so if it is empty the current script methods are not available.
I will keep an eye out to empty and reset the BaseScript on edit BaseType and set Self respectively.

**Comment by Gallilus** [comment]
https://github.com/godotengine/godot-proposals/discussions/4126

**Comment by KoBeWi** [comment]
Looks fixed in alpha 9.
