### ISSUE TITLE
Godot 4: all the constructor nodes in Visual Script are missing, only the deconstructors are available

### ISSUE THREAD

**Issue by kreaninw** [godotengine/godot#58070]
### Godot version

v4.0.alpha2.official [79077e6c1]

### System information

Windows 11, Vulkan Clustered, Intel UHD Graphics 620 v30.0.101.1340

### Issue description

All the constructor nodes are missing, only the deconstructors are available, as shown in the screenshot below:

![Screenshot 2022-02-13 195230](https://user-images.githubusercontent.com/1403194/153779181-825c0cc9-bc73-465b-b9ad-a02685fa953b.jpg)

This is a regression from Godot 3.4, as shown in the screenshot below:

![Screenshot 2022-02-13 195704](https://user-images.githubusercontent.com/1403194/153779199-6ddbd72b-91fa-42ae-a829-aeee1566b675.jpg)

I expect to have the constructor nodes to use.

### Steps to reproduce

1. In Visual Script, search for constructor nodes. You won't see any.

**Comment by Calinou** [comment]
cc @Gallilus

**Comment by MisoMosiSpy** [comment]
They are visible (and can be added) if we select "class" and "Search All" options (See attached screenshot). 
However, it does seem odd that destructors are listing when using "Search Base" but, for constructors we need to select "Search All".
![VS_Constructors](https://user-images.githubusercontent.com/52410428/153880740-299ece33-4cb2-414c-b83d-11c6326d19e5.PNG)

**Comment by kreaninw** [comment]
> They are visible (and can be added) if we select "class" and "Search All" options (See attached screenshot). However, it does seem odd that destructors are listing when using "Search Base" but, for constructors we need to select "Search All". ![VS_Constructors](https://user-images.githubusercontent.com/52410428/153880740-299ece33-4cb2-414c-b83d-11c6326d19e5.PNG)

Yes, in Godot 3.4, both the constructors and deconstructors are presented by default.

**Comment by MisoMosiSpy** [comment]
Thanks for confirmation, I studied this code a bit today (when I saw all
entries in the map I realised everything should be there in the Selection
dialog).

I will try to fix the categorisation for the  constructors.
