### ISSUE TITLE
"Index p_gutter = -1 is out of bounds" error spam in TextEdit

### ISSUE THREAD

**Issue by p-r-i-s** [godotengine/godot#58075]
### Godot version

v4.0.alpha2.official

### System information

Windows 10, GTX 980TI, Vulkan

### Issue description

In the following class:

```gdscript
class OrderedMap:
	var data = []
	var label_to_index = {}
	var index_to_label = {}
	
	func clear():
		data = []
		label_to_index = {}
		index_to_label = {}
	
	func get(label: String):
		return data[label_to_index[label]]
	
	func add(label: String, value):
		if label in label_to_index:
			data[label_to_index[label]] = value
		else:
			var new_index = data.size()
			label_to_index[label] = new_index
			index_to_label[new_index] = label
			data.append(value)
	
	func has_label(label: String):
		return label in label_to_index

```
The following error occurs 65 times:
```
scene/gui/text_edit.cpp:4804 - Index p_gutter = -1 is out of bounds (gutters.size() = 4).
  scene/gui/text_edit.cpp:4804 - Index p_gutter = -1 is out of bounds (gutters.size() = 4).
```

### Steps to reproduce

create a .gd file with the pasted code.

### Minimal reproduction project

[debug 4.0.zip](https://github.com/godotengine/godot/files/8057108/debug.4.0.zip)

**Comment by Calinou** [comment]
The project is *not* a minimal reproduction project – it includes a lot of unrelated elements. Please create a project that reproduces the error and is stripped down to a bare minimum.

**Comment by jmb462** [comment]
In [godot/editor/plugins/script_text_editor.cpp](https://github.com/godotengine/godot/blob/444c556c1a318348822a8a771f53b4f4853713fe/editor/plugins/script_text_editor.cpp#L539-L551), line 546

``TextEdit::set_line_gutter_item_color()`` is called with default ``line_number_gutter`` value which is ``-1`` (out of bound)

https://github.com/godotengine/godot/blob/444c556c1a318348822a8a771f53b4f4853713fe/editor/plugins/script_text_editor.cpp#L539-L551

**Comment by novaplusplus** [comment]
Would it be sufficient to fix to simply introduce a check such as this?

`if (highlight_safe && line_number_gutter >= 0) {
...
}`

**Comment by hudmarc** [comment]
This is happening again on the Godot 4.0 Stable release when using an external editor to modify GDScript files (in this case VSCode using the Godot extension)
<img width="890" alt="image" src="https://user-images.githubusercontent.com/44267994/224813746-f7921ff4-5bf8-4c36-896b-f69be48366ba.png">

**Comment by DragonAxe** [comment]
I can confirm this is still happening when using VSCode on v4.0.stable.official [92bee43ad].

I haven't yet tried to create a minimal working example, but I have noticed it seems to happen when I have Godot code editors open while modifying other files in the external editor. If I close Godot editors one at a time, one specific editor seems to be the culprit which doesn't have to be the same file I'm modifying in VSCode to trigger the errors.

**Comment by gokiburikin** [comment]
Also experiencing this in v4.1.rc1.official [1f9e540f1]. I've attached an MRP that requires additional steps to reproduce the issue since deleting the .godot folder makes this issue not appear until you've done them.

[print-spam-mrp.zip](https://github.com/godotengine/godot/files/11918874/print-spam-mrp.zip)

1. Start the project and open bar.gd, foo.gd, and gen.gd
2. Reload the project (Project > Reload Current Project)
3. Run the game and close it
4. You should get 1 error for every line in foo.gd (you can change how many lines are generated in gen.gd)

Seems to only happen when a certain amount of files including the file being generated are open (threading issue?) and only seems to start happening if the project has been reloaded once before (caching issue?)

**Comment by DasGandlaf** [comment]
Happens to me while using Neovim.

**Comment by Xander2tho** [comment]
My solution to that error was to save the parent node that contained the script that caused the error as a scene, personally it worked for me, I hope it also solves your error

**Comment by olivatooo** [comment]
happens when using nvim to edit files externally

**Comment by TheColorRed** [comment]
I don't seem to get this error when I have the following editor setting setup:

![image](https://github.com/godotengine/godot/assets/1571806/de4973a5-98f1-452a-8d91-776767c63eb5)

**Comment by 2fd5** [comment]
Same here, happening for me in "v4.1.1.stable.flathub [bd6af8e0e]" using Vscode

**Comment by AThousandShips** [comment]
Please open a new issue as this is a separate, though similar, bug as the original bug has been solved
