### ISSUE TITLE
EditorExportPlatformJavascript is using CPU when no Javascript export is present in project

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#58082]
### Godot version

v4.0.alpha.calinou [26b21dc0c]

### System information

Mac OSX (Intel 2019)

### Issue description

I was running perf testing again on the latest version as we had some more performance regressions.

I found that the Javascript editor export platform was using 20% of the CPU this time, but I did not have any related export settings in my project.

I would expect that this loop should only be run when the user actually has some use for it. For now I've reduced the timing of the calls from `1 ms` to `6.9 ms` to keep updates in line with 144hz monitors.

https://github.com/godotengine/godot/pull/58081

### Steps to reproduce

1. Run godot 4.x

**Comment by akien-mga** [comment]
Is this still reproducible in 4.0 RC 3 or later?

**Comment by tavurth** [comment]
@akien-mga As of 4.rc.3 my performance is doing great. 

My fairly heavy project runs at around 3% cpu.
However the GPU usage has climbed significantly since 3.5.1 (before around 4-5% now around 8% using compatibility mode)

<img width="852" alt="Screenshot 2023-02-25 at 00 18 02" src="https://user-images.githubusercontent.com/100964/221245045-da1904a3-7183-4e52-9c65-63de4ba9c823.png">

**Comment by tavurth** [comment]
I haven't had time to compile the engine and check for this particular performance issue but the engine is no longer using anything close to 20% of my CPU on the same machine. 

You guys have been doing a great job of optimisation! 👍 

I will close this issue.
