### ISSUE TITLE
GDScript 2.0: `assert(false)` causes a possibly annoying warning to be emitted

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#58087]
### Godot version

4.0.alpha2

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 495.46)

### Issue description

When looking at the reproduction project in https://github.com/godotengine/godot/issues/58075, I noticed that it prints the following warning:

> Assert statement will raise an error because the expression is always false.
> ASSERT_ALWAYS_FALSE

While this is fine for complex conditions that always evaluate to `false`, I feel this is problematic when `assert(false)` is literally written as it's obvious that the condition will always be false. In some cases (such as `match` statements), `assert(false)` is the most concise way to make a project execution pause when an error is reached in debug mode.

### Steps to reproduce

Paste this code in a script in the editor and save it:

```gdscript
extends Node

enum PhysicsEngine {
    DEFAULT,
}

func _ready():
	match ProjectSettings.get_setting("physics/3d/physics_engine"):
		"DEFAULT":
			return PhysicsEngine.DEFAULT
		_:
			assert(false)
```

Notice a warning will appear on the `assert(false)` line.

### Minimal reproduction project

N/A

**Comment by Spowmtom** [comment]
> In some cases (such as match statements), assert(false) is the most concise way to make a project execution pause when an error is reached in debug mode.

I believe it is preferable to use breakpoints in the editor or the `breakpoint` keyword instead.

**Comment by Calinou** [comment]
> I believe it is preferable to use breakpoints in the editor or the breakpoint keyword instead.

`breakpoint` doesn't allow specifiying a custom error message like `assert()` does:

```gdscript
assert(false, "Invalid property value: " + str(value))
```

**Comment by Spowmtom** [comment]
You could combine `breakpoint` with `push_warning`, but I understand why you would want a single command to do both.

**Comment by cameronsteele** [comment]
Similarly, if using assert to catch problems at the end of a loop, the error displays. Will use `breakpoint` as Spowmtom suggested for now.

```
var choiceWeightScanTotal = 0;
for choiceIndex in choiceWeights.size():
	var choiceWeight = choiceWeights[choiceIndex];

	choiceWeightScanTotal += choiceWeight;

	if(randomInt < choiceWeightScanTotal):
		return choices[choiceIndex];

assert(false, "Could not generate a random choice for some reason.");
```
