### ISSUE TITLE
PopupMenu doesn't hide when user clicks outside it

### ISSUE THREAD

**Issue by BeholderVee** [godotengine/godot#58084]
### Godot version

3.4.2.stable.official [45eaa2daf]

### System information

Windows 10

### Issue description

The PopupMenu node doesn't hide when I click outside it. As I understand it, it's supposed to hide by default, unless you set popup_exclusive to true, which I haven't done. Changing this property either way doesn't actually seem to change the behaviour.
Clicking inside the popup does hide it.

https://user-images.githubusercontent.com/74183296/153832734-324ac4b4-1915-4d56-8f17-d075caf2a5ee.mp4

### Steps to reproduce

1. Create a PopupMenu node.
2. Run the scene
3. Click outside the node

### Minimal reproduction project

[PopupBugReport.zip](https://github.com/godotengine/godot/files/8059355/PopupBugReport.zip)

**Comment by timothyqiu** [comment]
For `Popup`s to work correctly, `popup()` has to be used instead of plain-old `show()`.
