### ISSUE TITLE
Confusing docs about `AudioServer.set_device`

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#58096]
### Godot version

3.4.2.stable

### System information

Mac OSX (Intel 2019)

### Issue description

I was trying to fix some of the CPU usage caused by coreaudio running non-stop while the editor runs.

## Associated issues & PRs
https://github.com/godotengine/godot/issues/38154
https://github.com/godotengine/godot/issues/55608
https://github.com/godotengine/godot/pull/38208
https://github.com/godotengine/godot/pull/45948

## Here is the plugin I was working on
https://github.com/tavurth/godot-sound-disabler

## What's not working

```gdscript
ProjectSettings["audio/driver"] = "dummy"
```

### Steps to reproduce

Please see above, sample code can be found here

https://github.com/tavurth/godot-sound-disabler

### Minimal reproduction project

https://github.com/tavurth/godot-sound-disabler

**Comment by Calinou** [comment]
The audio driver can't be changed at run-time, as Godot does not have a way to restart the audio server without restarting the entire project.

**Comment by tavurth** [comment]
> The audio driver can't be changed at run-time

I see, so that `"audio/driver"` is actually used to spawn the project when running as an export.

Makes more sense about why it's not working then.

It would be great to be able to do this, as from the code I linked above a temporary (in-editor) workaround to all those issues would be simple to implement in GDscript, compared to complex in C++.

**Comment by Calinou** [comment]
Actually, `set_device()` has nothing to do with setting the audio *driver*. `set_device()` is meant to set the output device when multiple devices are attached (which is possible with USB or HDMI audio).

**Comment by Calinou** [comment]
> This bug is more about the ProjectSettings["audio/driver"] = "dummy" not working in the editor. I will update the title to reflect that.

Most project settings are not designed to be changed at run-time. Instead, you should use server methods (like AudioServer's), and there is no such method exposed yet.

**Comment by tavurth** [comment]
I see, shall we close this issue then, or revert to the set_device and use as a documentation bug?

**Comment by Calinou** [comment]
> I see, shall we close this issue then, or revert to the set_device and use as a documentation bug?

You can keep this issue open as a documentation issue.
