### ISSUE TITLE
Error message tooltip flickers on hover (DisplayServer regression)

### ISSUE THREAD

**Issue by albinaask** [godotengine/godot#58109]
### Godot version

4.0.alpha_2

### System information

Windows 10, AMD Ryzen 2700x, Nvidia 1070ti

### Issue description

Visual glitch where the tooltip that shows information of a given error flickers instead of lighting up fully, on exit it is hidden correctly

### Steps to reproduce

1. Open Editor
2. Open new GDScript
3. Make code that generates runtime error
4. Tab out of game to editor
5. Look at tab "Errors([some number])" in bottom of editor
6. Observe flicker

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
@albinaask Can you record a video of this happening?

**Comment by albinaask** [comment]
https://user-images.githubusercontent.com/11806563/153949092-371872b5-ca20-4eee-a263-5de073693a17.mp4

**Comment by markdibarry** [comment]
Noticed this too. Was in the middle of another ticket so I forgot to open an issue on this.
Windows 10.

**Comment by Calinou** [comment]
As a workaround, you can likely enable **Single Window Mode** in the Editor Settings and restart the editor.
