### ISSUE TITLE
In Editor Documentation Find: Scrolls all matches on same line as 1st match, 1 View's height up and out of view.

### ISSUE THREAD

**Issue by RefinedSoftwareLLC** [godotengine/godot#58108]
### Godot version

4.0 Alpha 2

### System information

Linux

### Issue description

In Editor Documentation using the find feature scrolls all matches on same line as 1st match, 1 View's height up and out of view.

### Steps to reproduce

Open Script Tab
Click Search Help
Select DisplayServer
Open Search Menu
Click Find
Search for feature
In the Searchbar Click the up and down arrows.
Notice how the Documentation's View scrolls to til the highlighted word `feature` is seen
But the 1st, 2nd, and 3rd match scrolls the window exactly 1 View's Height too high up the document.
All 3 of these matches are on the same line.
4th match to 25th match are scrolled within sight correctly.

**Comment by KoBeWi** [comment]
I think this is related:
![godot windows tools 64_2VcW2OGVyT](https://user-images.githubusercontent.com/2223172/158916685-1cf96a9e-191f-416d-9230-26236f026561.gif)
The help highlights are completely inaccurate. This also happens when you Ctrl+Click something. The help opens with the interesting bit completely out of view. I'm always lost when trying to find something.

**Comment by Anutrix** [comment]
Find feature in documentation seems to broken in multiple ways.

E.g, Searching 'root' in Node Documentation says 10 matches but loops at 3 views. Only first one shows correct view. After 2nd view it just goes back to first result.

**Comment by MewPurPur** [comment]
I'm working on a refactor to this system already. I'll see if I can resolve the scrolling issues while at it.

**Comment by MewPurPur** [comment]
The bug is that RichTextLabel's `search()` function searches for physical lines, not accounting for text wrapping.
