### ISSUE TITLE
Console window missing

### ISSUE THREAD

**Issue by albinaask** [godotengine/godot#58110]
### Godot version

4.0.alpha_2

### System information

Windows 10, AMD Ryzen 2700x, 1070ti

### Issue description

The console window is gone! Toggling the Editor setting "Hide Console Window" does nothing either. I've tested restarting the editor a couple of times without any result. Not sure if this was the case from the get go, or whether godot has has switched some internal setting to never show the console... IDK

### Steps to reproduce

1. Open Godot editor
2. Try locating the console window
3. Fail(hopefully)

### Minimal reproduction project

N/A

**Comment by JoanPotatoes2021** [comment]
Have you tried running the console on cmd? Now by default godot does not show the console on the standard executable.

![console](https://user-images.githubusercontent.com/88800565/153942245-33c798a3-192d-48f5-955f-6b0e619d2523.jpg)

**Comment by Calinou** [comment]
This is intended behavior as @JoanPotatoes2021 said, and was required to play well with Windows Terminal (which is the default on Windows 11).

**Comment by albinaask** [comment]
Thx, just me being silly ;)
