### ISSUE TITLE
Godot 4: Has nodes do not show up by default in Visual Script

### ISSUE THREAD

**Issue by kreaninw** [godotengine/godot#58118]
### Godot version

v4.0.alpha2.official [79077e6c1]

### System information

Windows 11, Vulkan Clustered, Intel UHD Graphics 620 v30.0.101.1340

### Issue description

Visual Script **Has nodes** do not show up by default even though the **Search Visual Script Nodes** is turned on, as shown in the screenshot below:

![Screenshot 2022-02-14 183616](https://user-images.githubusercontent.com/1403194/153951937-ceb6c61d-ef6b-424f-a928-3ccd6c853e98.jpg)

The user has to change the search limits from **Search Base** to **Search All**, as shown in the screenshot below:

![Screenshot 2022-02-14 185003](https://user-images.githubusercontent.com/1403194/153952584-65343fb0-1cdc-45d1-9068-3bf5985a132f.jpg)

This is a regression from Godot 3.4. In Godot 3.4, the user can search for the Has nodes and get the results immediately as shown in the screenshot below:

![Screenshot 2022-02-14 183514](https://user-images.githubusercontent.com/1403194/153952787-aaa06cfc-a982-47a7-9b4c-aa18fcb82b40.jpg)

Note: this issue could be related to issue #58070

### Steps to reproduce

1. Open Visual Script canvas.
2. Right-click and search for "has" nodes. You won't see Visual Script Has nodes by default.

**Comment by Gallilus** [comment]
As you see in the screenshots above.
We are searching the object Node for 'has' and it only finds Node.has_node().
When you select to search all you do not only search the Object but all variants. Then you are able to find Array.has()

So it seems technically correct.
@kreaninw  any ideas on how to communicate this cleaner to the user?

**Comment by kreaninw** [comment]
> As you see in the screenshots above. We are searching the object Node for 'has' and it only finds Node.has_node(). When you select to search all you do not only search the Object but all variants. Then you are able to find Array.has()
> 
> So it seems technically correct. @kreaninw any ideas on how to communicate this cleaner to the user?

This behavior does not make much sense as:

1. Some Visual Script nodes, which does not belong to the script's BaseType, are still appearing as shown in the screenshot below:

![Screenshot 2022-02-26 163003](https://user-images.githubusercontent.com/1403194/155856712-caa3761d-1e07-456f-8f4a-e268332ff643.jpg)

Therefore, why aren't all other Visual Script nodes available as well? For example, Array's Visual Script has node:

![Screenshot 2022-02-26 163825](https://user-images.githubusercontent.com/1403194/155856822-38378f11-b4a8-47ed-a1f3-fc61582d4da9.jpg)

2. The Search box filter would be helpful if the users want to look for all the functions, properties, etc. aimlessly (Godot Docs would be a better place for this). However, most of the time, the users know exactly what function they want to call or what property they want to get or set. 

Therefore this Search box filter only gets in the way of the users' workflow. Instead of just searching for a node that they want to use, then use this newly filter implementation as shown in the screenshot below:

![Screenshot 2022-02-26 165429](https://user-images.githubusercontent.com/1403194/155857295-dc5f427d-9191-4b2b-8aac-824b0bb256cf.jpg)

To filter out some unrelated nodes, it would be much faster for the users to code. Currently, the users need to change this filter search box to "Search All" all the time whenever they want to use some very essential node, for example, any array nodes, dictionary node, vector 3 node, and so on.

The only way to communicate this feature clearer to the users is to remove all the unrelated nodes from the search result. However, that would make this node search window nearly useless by default. As explained above, I don't think this search box filter will make my workflow easier or faster at all.

**Comment by Gallilus** [comment]
https://github.com/godotengine/godot-proposals/discussions/4126
