### ISSUE TITLE
When I open Godot it loads my application, not the editor or the project menu.

### ISSUE THREAD

**Issue by scovelme** [godotengine/godot#5811]
**Operating system or device - Godot version:**
Windows 10
Godot v2.0
**Issue description** (what happened, and what was expected):
What the title says

**Steps to reproduce:**
Create project, write script, save scene, play, stop playing, close Godot

**Comment by vnen** [comment]
This is not a bug, it's the intended way of working. If the executable find a `engine.cfg` on the same folder (or a `data.pck`/`.zip`) it runs the project. You need to move the executable out of the game folder or run Godot with flags (`-pm` for project manager or `-e` for editor).
