### ISSUE TITLE
Cannot change or catch events in main apple menu

### ISSUE THREAD

**Issue by vlyahovich** [godotengine/godot#58116]
### Godot version

v3.4.2.stable.official [45eaa2daf]

### System information

Mac OS Monterey 12.1

### Issue description

I can't seem to find a way to show about window when user clicks on "About" in main menu. It just does nothing.

![Screen Shot 2022-02-13 at 4 09 38 PM](https://user-images.githubusercontent.com/2776343/153946672-e1174110-2872-4ab7-b719-5ca1bdb9621d.png)

### Steps to reproduce

Export game with osx template and you should see this. I filled all fields in export: version, short version, copyright.

But it seems that about button does nothing and actually also prevented from modifications here https://github.com/godotengine/godot/blob/d3a6b6daaab4c8dfb7bdf35cc2fe2145ae6c22a1/platform/osx/display_server_osx.mm#L76

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by bruvzg** [comment]
You can handle about button using `NOTIFICATION_WM_ABOUT` notification:

```gdscript
func _notification(what):
	if what == NOTIFICATION_WM_ABOUT:
		do_your_about_popup()
```

**Comment by vlyahovich** [comment]
> You can handle about button using `NOTIFICATION_WM_ABOUT` notification:
> 
> ```gdscript
> func _notification(what):
> 	if what == NOTIFICATION_WM_ABOUT:
> 		do_your_about_popup()
> ```

It works, thank you! Closing the issue

**Comment by Calinou** [comment]
> You can handle about button using NOTIFICATION_WM_ABOUT notification:

Should there be a default handler that prints a message to standard output (only in debug builds)? This would likely help with discoverability.

```
About dialog was requested by the user. Override `_notification()` with `NOTIFICATION_WM_ABOUT` to display an About dialog in your project.
```

**Comment by vlyahovich** [comment]
> 

This is a good idea to have it visible somewhere. In my case my game was rejected from mac os app store because of not having about window working. After googling I could not find any similar questions. So I opted out for digging source code without a success 😅
