### ISSUE TITLE
Godot 4: function rename dialog in Visual Script doesn't focus on the text box by default

### ISSUE THREAD

**Issue by kreaninw** [godotengine/godot#58127]
### Godot version

v4.0.alpha2.official [79077e6c1]

### System information

Windows 11, Vulkan Clustered, Intel UHD Graphics 620 v30.0.101.1340

### Issue description

When the user renames a function in Visual Script, the focus will be on the OK button instead of the text box. The users will have to click on the text box one more time before they can actually rename a function. This behavior can be seen in the screen recording below:

https://user-images.githubusercontent.com/1403194/153985053-fa2181c9-d81b-4f34-b0c0-144290b89089.mp4

This issue is a regression from Godot 3.4. In Godot 3.4, the users do not need to click on the text box as the focus will be on the text box by default. They can rename the function immediately, as shown in the screen recording below:

https://user-images.githubusercontent.com/1403194/153985330-0c303a2e-69f8-4a54-bf6d-6f8c2209c4d2.mp4

I expect the focus to be on the text box by default since that is the whole reason I go to this menu in the first place.

### Steps to reproduce

1. Create a function in Visual Script.
2. Rename the function. The focus won't be on the text box.

**Comment by jmb462** [comment]
Should be already fixed in master branch via #58026
