### ISSUE TITLE
Godot 4: PropertyGet and PropertySet nodes do not show up by default in Visual Script

### ISSUE THREAD

**Issue by kreaninw** [godotengine/godot#58129]
### Godot version

v4.0.alpha2.official [79077e6c1]

### System information

Windows 11, Vulkan Clustered, Intel UHD Graphics 620 v30.0.101.1340

### Issue description

Visual Script **PropertyGet** and **PropertySet** nodes do not show up by default even though the **Search Visual Script Nodes** is turned on, as shown in the screenshot below:

![Screenshot 2022-02-15 005912](https://user-images.githubusercontent.com/1403194/153990750-cbcaa47d-ec03-4842-8c67-9a4232579706.jpg)

The user has to change the search limits from **Search Base** to **Search All**, as shown in the screenshot below:

![Screenshot 2022-02-15 005957](https://user-images.githubusercontent.com/1403194/153990871-e08525d2-bc84-4552-b745-d7a40e6f58cc.jpg)

I expect to see PropertyGet and PropertySet nodes without having to change the search limits to all. 

Note: this issue could be related to issues #58070 and #58118.

### Steps to reproduce

1. Open Visual Script canvas.
2. Right-click and search for "property" nodes. You won't see Visual Script PropertyGet and PropertySet nodes by default.

**Comment by Gallilus** [comment]
Same as https://github.com/godotengine/godot/issues/58128 look for set and get instead of property.

@kreaninw may this issue be closed?

**Comment by kreaninw** [comment]
> Same as #58128 look for set and get instead of property.
> 
> @kreaninw may this issue be closed?

It's related to the functionality of the newly implemented search filter box. If the team decided to keep the current behavior of the search filter box. Then this issue can be closed.

**Comment by Gallilus** [comment]
https://github.com/godotengine/godot-proposals/discussions/4126
