### ISSUE TITLE
Bizarre bug with PopupMenu submenus when popped up near the bottom of the screen

### ISSUE THREAD

**Issue by EIREXE** [godotengine/godot#58126]
### Godot version

3.x 9bb6f9576d3ce09941c8ae18a033c15a3f98251f
Probably also happens in 4.0

### System information

Arch Linux

### Issue description

The specific setup in the linked MRP causes hovering over the item that opens the submenu to flicker the opening of the submenu for every time the mouse is moved, this seems to be caused by f63bea9ef281be2513b8653a4d2eabd77842a5c9 in fact moving the `pm->popup();` line under `pm->set_scale(get_global_transform().get_scale());` in `_activate_submenu` seems to fix the issue.

It only seems to happen on a setup specifically like the one in the linked MRP, where the submenu item is the first and it has 4 normal items following it, yeah I don't get it either but this is what it does.

### Steps to reproduce

Load the linked MRP and right click anywhere on the screen, hover the "Change type" item and observe how the menu flickers when moving over it, making it impossible to select any of the items.

### Minimal reproduction project

[PopupMenuBug.zip](https://github.com/godotengine/godot/files/8065186/PopupMenuBug.zip)

**Comment by RodZill4** [comment]
@EIREXE @Calinou @akien-mga @YeldhamDev

I have this problem in Material Maker and it is pretty annoying.

It seems autohide areas setup needs the menu to be where it will popup (this depends on its item count, especially if it's near the bottom of the viewport). I modified the draw stuff to display them and they are offset with current 3.x code.

Moving popup() above the if statement seems to break navigating menus with the arrow keys.

I don't think it is that difficult to fix, the "pm->popup();" statement can be moved between the "ui_accept" action stuff and the autohide areas setup, like this:

`	pm->set_position(pos);
	pm->set_scale(get_global_transform().get_scale());

	PopupMenu *pum = Object::cast_to<PopupMenu>(pm);
	// If not triggered by the mouse, start the popup with its first item selected.
	if (pum && pum->get_item_count() > 0 && Input::get_singleton()->is_action_just_pressed("ui_accept")) {
		pum->set_current_index(0);
	}

	pm->popup();

	if (pum) {
		pr.position -= pum->get_global_position();
		pum->clear_autohide_areas();
		pum->add_autohide_area(Rect2(pr.position.x, pr.position.y, pr.size.x, items[over]._ofs_cache));
		if (over < items.size() - 1) {
			int from = items[over + 1]._ofs_cache;
			pum->add_autohide_area(Rect2(pr.position.x, pr.position.y + from, pr.size.x, pr.size.y - from));
		}
	}
}
`

**Comment by akien-mga** [comment]
Fixed by #61686.
