### ISSUE TITLE
Linux: Automatically Make Binary Executable On Export

### ISSUE THREAD

**Issue by toliaferrode** [godotengine/godot#5812]
**Operating system or device - Godot version:**
Ubuntu MATE 15.10, Godot 2.0.4.1, Godot 2.1-beta

**Issue description** (what happened, and what was expected):
I like that the Godot executable ships executable by default now. I think it would be awesome if Godot exported executable binaries by default.

**Steps to reproduce:**
Export your game on Linux, execute, permission dialogue instead of game.

**Link to minimal example project** (optional but very welcome):

**Comment by vnen** [comment]
Duplicate of #527.
