### ISSUE TITLE
Godot 4: Visual Script node search window opens as a non-window popup (DisplayServer regression) when adding a very long description node into the canvas

### ISSUE THREAD

**Issue by kreaninw** [godotengine/godot#58121]
### Godot version

v4.0.alpha2.official [79077e6c1]

### System information

Windows 11, Vulkan Clustered, Intel UHD Graphics 620 v30.0.101.1340

### Issue description

Visual Script node search window (RMB on the canvas) opens as a non-window popup and can't be resized when adding a very long description node into the canvas. I have to restart the engine to fix this issue.

The popup window's corners don't appear to be rounded indicating it's not open as a window. All opened windows in Windows 11 should have round corners. This issue is shown in the screen recording below:

https://user-images.githubusercontent.com/1403194/153957564-418d5994-518e-4982-8fb8-6bfa79c528b2.mp4

This is how the window appears when it works correctly:

![Screenshot 2022-02-14 192203](https://user-images.githubusercontent.com/1403194/153957863-a2d58484-449d-4efe-8419-535c986ac6d7.jpg)

I expect the node search window to open as a window all of the time so I don't have to restart the engine.

Note: See [this comment](https://github.com/godotengine/godot/issues/58121#issuecomment-1066004459) for more info.

### Steps to reproduce

1. Right mouse click at the Visual Script canvas to search for nodes. 
2. Add the `connect()` node.

**Comment by Calinou** [comment]
Can you reproduce this after enabling **Single Window Mode** in the Editor Settings then restarting the editor?

**Comment by kreaninw** [comment]
> 

I can't reproduce this after enabling Single Window Mode in the Editor Settings, as shown in the screen recording below:

https://user-images.githubusercontent.com/1403194/153979257-325eb793-3bb2-486d-8aaa-bd44c0578275.mp4

**Comment by kreaninw** [comment]
I found a way to reproduce this issue 100% of the time. **This issue will occur when I selected and add a node that has a very long description.** In this case, it's the `connect()` node.

I can no longer add the other node after this issue occurred, only the `connect()` node can be added.

It doesn't matter whether I am on the Single Window Mode, as shown in the screen recording below:

https://user-images.githubusercontent.com/1403194/158041516-f73636be-8994-4b9c-962b-5b682a338ebb.mp4

**Comment by derammo** [comment]
I could take this one if nobody else is working on it?

**Comment by Calinou** [comment]
> I could take this one if nobody else is working on it?

Feel free to open a pull request for this :slightly_smiling_face:

**Comment by derammo** [comment]
Not intended as links, so no hashes.  But just to clarify:  61017 is supposed to be the fix and 61010 is a prerequisite, to be able to load visual script files with names that start with r, s, or e.
