### ISSUE TITLE
Godot 4: adding a property set in Visual Script results in getting a property get instead

### ISSUE THREAD

**Issue by kreaninw** [godotengine/godot#58128]
### Godot version

v4.0.alpha2.official [79077e6c1]

### System information

Windows 11, Vulkan Clustered, Intel UHD Graphics 620 v30.0.101.1340

### Issue description

I add a property **set** but get a property **get** instead, as shown in the screen recording below:

https://user-images.githubusercontent.com/1403194/153989626-21ccfdd2-c23c-4b47-a7c3-ac214a5e4cd6.mp4

I expect to get the correct node.

### Steps to reproduce

1. Add a property set in Visual Script. You will get a property get instead.

**Comment by jmb462** [comment]
For an unknown reason to me, you have to press <kbd>CRTL</kbd> to get the setter.
It is design this way in the source code.
Looks strange to me but I won't attempt any change before knowning why this is the case.

**Comment by kreaninw** [comment]
> For an unknown reason to me, you have to press CRTL (while confirming) to get the setter. It is design this way in the source code. Looks strange to me but I won't attempt any change before knowing why this is the case.
> 
> https://github.com/godotengine/godot/blob/98b97d34df7f3ab2cafc3847358c231c3d357b40/modules/visual_script/editor/visual_script_editor.cpp#L3397-L3421

When dragging a variable from the members' window to the Visual Script canvas, you will get a PropertyGet node, but if you hold down CTRL, you will get a PropertySet node. It has been like this since Godot 3 (I've never used Godot 2), except that you would get a VariableGet or a VariableSet node in Godot 3 instead of a PropertyGet or a PropertySet node (VariableGet and VariableSet are deprecated - [#54663 merged PR](https://github.com/godotengine/godot/pull/54663)). 

But in this case, the menu tells the users exactly what node they would've got, as shown in the screenshot below:

**PropertyGet:**

![Screenshot 2022-02-15 185050](https://user-images.githubusercontent.com/1403194/154155460-ced3f887-71bf-4b8e-9b04-84ecd655b4b4.jpg)

**PropertySet**

![Screenshot 2022-02-15 185004](https://user-images.githubusercontent.com/1403194/154155536-1e6e7f89-90b5-4473-9f6c-b778d9037f6d.jpg)

**Comment by kreaninw** [comment]
> I understand the confusion.
> 
> I think you are looking for visual script nodes. Get, Set and Set_variable, Get_variable
> 
> The VisualScriptProperty... class you look for is what describes how the visual script nodes work. that class has a variable/property called ' property' which you may try to set or get from an instance.
> 
> @kreaninw thanks for your feedback. I implemented this search system to make sure everyone may find everything they need. I hope it is an overall improvement to 3.4. Do you understand the difference? Do you have any idea how to improve the search so this may be avoided in the future?
> 
> ![image](https://user-images.githubusercontent.com/20573784/155838258-3109832d-5b63-493a-b79e-cc085002b9b0.png)

I understand the differences compared to 3.4. However, I don't think this is an improvement. Now the users need a lot more steps, from changing this search filter box to "Search All" to search for some very essential nodes that they use all the time, then most of the time they'll also need to enable the class searching that's disabled by default.

I don't think the current search filter box will make anyone coding in Visual Script faster since it adds more steps to get things done. If the goal is to reduce some unrelated nodes from the search result, I think this filter bar would be enough:

![Screenshot 2022-02-26 165429](https://user-images.githubusercontent.com/1403194/155858158-19c58029-8e7c-401e-a309-813571cb1b1f.jpg)

**Comment by Gallilus** [comment]
https://github.com/godotengine/godot-proposals/discussions/4126

**Comment by Gallilus** [comment]
While working on a PR to improve this annoyance I noticed filtering the Show Hierarchy button puts visual script nodes on top.
![image](https://user-images.githubusercontent.com/20573784/161134804-1de5867a-7b2d-429d-8364-ecfbc38dcc7c.png)
