### ISSUE TITLE
GDScript 2.0 : Sometimes Accessing value from a Dictionary from an Autoload script gives an Error

### ISSUE THREAD

**Issue by owstetra** [godotengine/godot#58123]
### Godot version

4.0 Alpha

### System information

Windows 10

### Issue description

For some reasons trying to Access a value from a Dictionary variable in an Autoload script Gives this Error :

` invalid index type "string" for a base of type string`

and won't compile, but if you save the script, restart the project, the error is gone and compile fine

SomeAutoloadScript.gd
`var MyDictionary : Dictionary = {"Item1" : 1, "Item2" : 2}`

PlayerScript.gd
`print(SomeAutoloadScript.MyDictionary["Item2"])`

doing this sometimes gives the error, i don't know why, but it happened in many projects in Godot 4.0 Alpha

### Steps to reproduce

None

**Comment by vnen** [comment]
Honestly, without more information it's really difficult to assess this report. It might be some cache issue as you changed something and it relied on an old state. Probably restarting the scene is enough, or even just changing something in the script to allow it to re-parse.

**Comment by adamscott** [comment]
I suggest to close this issue. More information was asked one year ago, but no answer was given.
