### ISSUE TITLE
Getting an error when trying to export IOS app

### ISSUE THREAD

**Issue by tomasracys505hq** [godotengine/godot#58138]
### Godot version

3.4.2.stable.official

### System information

MacOS Monterey 12.2.1

### Issue description

When trying to export IOS project, it always fails with this error:
```
note: Build preparation complete
note: Building targets in dependency order
error: No profiles for 'com.tomas.testlatestios' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.tomas.testlatestios'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'testlatestios' from project 'testlatestios')
```

### Steps to reproduce

1. Create new empty project with GLES2.
2. Do only necessary steps needed for IOS build -> selecting icons, pvrtc in project settings, filling in some fields.
3. Try to export - it fails.

Attached minimal reproduction project.

### Minimal reproduction project

[testlatestios.zip](https://github.com/godotengine/godot/files/8067687/testlatestios.zip)

**Comment by naithar** [comment]
It's `xcbuild` that's failing. Your export setup might be missing some data that's required.
You should be able open the folder you are exporting your project into. Run Xcode project and fix build errors, they are probably related to the certificates and provisioning profiles not being installed or broken. 
From there you should be able to manually build your game using `Product->Archive`

**Comment by Calinou** [comment]
@tomasracys505hq Can you reproduce this on Godot 3.5.3 or 4.1.3?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.
