### ISSUE TITLE
GUI in 3D Demo Mouse Disappears

### ISSUE THREAD

**Issue by toliaferrode** [godotengine/godot#5814]
**Operating system or device - Godot version:**
Ubuntu MATE 15.10, Godot 2.1-beta

**Issue description** (what happened, and what was expected):
When I click and drag the SpinBox in the 3D GUI up or down the mouse cursor disappears.

**Steps to reproduce:**
Load up the GUI in 3D and click and drag the SpinBox up or down.

**Link to minimal example project** (optional but very welcome):

**Comment by akien-mga** [comment]
I can reproduce this too.

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.
