### ISSUE TITLE
Horizontal Scroll Bar For Node Tab In Editor

### ISSUE THREAD

**Issue by toliaferrode** [godotengine/godot#5815]
**Operating system or device - Godot version:**
Any OS, Godot 2.1-beta

**Issue description** (what happened, and what was expected):
I'm talking about the Node tab which is next to the Inspector tab. This could use a horizontal scrollbar for certain nodes that have long function descriptions. The tool tip is ok for that, but it's kinda fiddly.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by lordadamson** [comment]
what is an example of a node that has a long function descriptions?
And what do you mean by a function description? you mean the name or am I missing something?

**Comment by toliaferrode** [comment]
Sorry, this can be closed now. I opened this pre 2.1.
