### ISSUE TITLE
Docs say get_tree().physics_frame is signal but `await` can't detect it as such

### ISSUE THREAD

**Issue by RefinedSoftwareLLC** [godotengine/godot#58156]
### Godot version

Godot 4.0 alpha 2

### System information

Linux

### Issue description

`await get_tree().physics_frame`'s error message says `physics_frame` is not a signal.
The Docs for `Class: SceneTree` state it is a signal.

### Steps to reproduce

```
await get_tree().physics_frame
print("done")
```
instantly prints done without waiting for physics frame with the debug message:
`W 0:00:00:0555   "await" keyword not needed in this case, because the expression isn't a coroutine nor a signal. <C++ Error>    REDUNDANT_AWAIT`

**Comment by h0lley** [comment]
this is not limited to `physics_frame` specifically, 

I get

```
W 0:00:00:0635   "await" keyword not needed in this case, because the expression isn't a coroutine nor a signal.
  <C++ Error>    REDUNDANT_AWAIT
```

for several signals, including
`await tween.finished`
`await get_tree().process_frame`
`await get_tree().create_timer(0.4).timeout`

This just seems to be an incorrect warning though, the await still seems to work as expected.

**Comment by KoBeWi** [comment]
Sounds like #56265, except signal should definitely be known in this case...

**Comment by RefinedSoftwareLLC** [comment]
@h0lley I am not sure which like of code you are referring to but I want to be clear that the line `await get_tree().physics_frame` is completely skipped and does not work as expected. You can test by putting a print before `await get_tree().process_frame`, a print in inside the _process function and a print below `await get_tree().process_frame`. Run it and in your log it should be `before`, `_process`, `after`, (`_process` * Inf). I incorrectly get `before`, `after`, (`_process` * Inf).

**Comment by RefinedSoftwareLLC** [comment]
@h0lley Sorry, you are right, it is asyncing, I changed my test code and this worked:
```
self.call("a")
self.call_deferred("b")
await get_tree().physics_frame
self.call("c")
```
It prints `a`, `b`, then `c`
If you comment out the await line it will prints `a`, `c`, then `b`.

**Comment by tavurth** [comment]
This also warns on custom signals:

My node:
```gdscript
extends Node

signal built()

func _ready():
    self.emit_signal("built")
```

Another node:
```gdscript
func _ready():
    var other_node = preload("res://my_node.gd").new()
    await other_node.built
```
