### ISSUE TITLE
Godot 4: script variables in Visual Script are always exported

### ISSUE THREAD

**Issue by kreaninw** [godotengine/godot#58158]
### Godot version

v4.0.alpha2.official [79077e6c1]

### System information

Windows 11, Vulkan Clustered, Intel UHD Graphics 620 v30.0.101.1340

### Issue description

The script variables in Visual Script are exported by default regardless of the export toggler, as shown in the screen recording below:

https://user-images.githubusercontent.com/1403194/154159591-05cc7d80-4f65-4b91-b57b-d40cfacb8e03.mp4

And there's no way to turn it off due to the issue [#58072](https://github.com/godotengine/godot/issues/58072).

This is a regression from Godot 3.4.

I expect the variable to be exported **only** when selected.

### Steps to reproduce

1. Create a variable in Visual Script. It will be exported regardless of the export toggler.

**Comment by kreaninw** [comment]
Update: even though the variable always shows in the inspect tab as the exported variable, the users can't change its value in the inspector tab unless they actually exported the variable, as shown in the screen recording below:

https://user-images.githubusercontent.com/1403194/155009546-9f9c82a3-7055-4b16-a556-032d9ce00c15.mp4

**Comment by Gallilus** [comment]
I did a check and this issue seems to be there from V4.0a1.
The `VisualScriptEditorVariableEdit` seems to save the `export variable_parameter`.

So I assume when converting to GDScript 2.0 there is a change in how the export is handled, and as the `export variable_parameter` is no longer found the inspector defaults to showing the variable.

@Calinou Do you know the next person to ping to get more guidance?

**Comment by Calinou** [comment]
> So I assume when converting to GDScript 2.0 there is a change in how the export is handled, and as the export variable_parameter is no longer found the inspector defaults to showing the variable.

VisualScript does *not* compile to GDScript behind the scenes.

> @Calinou Do you know the next person to ping to get more guidance?

I don't know who else is actively working on visual scripting, sorry. I've never worked on it myself.

**Comment by Gallilus** [comment]
> VisualScript does not compile to GDScript behind the scenes. This is probably due to something else.
Indeed.
The problem is that the editor may now interpret "exported" differently than 3.x
