### ISSUE TITLE
Tileset does not detect certain tiles.

### ISSUE THREAD

**Issue by scovelme** [godotengine/godot#5816]
**Operating system or device - Godot version:**
Any

**Issue description** (what happened, and what was expected):
I placed five tiles in a scene for the purpose of making a tileset. When I loaded it into a tilemap on a different scene, only one of the sprites I had placed appeared in the tile placing menu thing.

**Steps to reproduce:**
Create a tileset with more than one tile
Load it on a different scene

**Comment by akien-mga** [comment]
You probably made a mistake when making your tileset, this is not an engine bug (else we'd know about it).
See the docs about making tilesets: http://docs.godotengine.org/en/latest/tutorials/2d/using_tilemaps.html
