### ISSUE TITLE
Running the project from the editor opens off screen due to negative position coordinates being passed by the editor (Linux, multi-GPU setup)

### ISSUE THREAD

**Issue by nPHYN1T3** [godotengine/godot#58178]
### Godot version

3.3.3.stable.offical (appImage)

### System information

Garuda Linux 5.16.9-arch1-1 GTX 1660 GTX 1060

### Issue description

Hitting F6 to test/preview the project opens the window partially off screen (**--position -512,-300**). You need to use a window manager key commands to move it into view where in it's extremely stuttery/laggy in its movement. 

I suspect this is a problem with more than one GPU/XScreen.

### Steps to reproduce

Press F6 to preview your project and note the Window opens mostly off screen with just the bottom right of the window being selectable/viewable.

### Minimal reproduction project

This behavior happens with any project.

Terminal output
Running: $HOME/.local/share/bin/Godot_v3.3.3-stable_x11.64 --path $HOME/godot/test-files/platformer --remote-debug 127.0.0.1:6007 --allow_focus_steal_pid 1917107 **--position -512,-300** res://src/levels/test-level.tscn
Godot Engine v3.3.3.stable.official.b973f997f - https://godotengine.org

**Comment by Calinou** [comment]
Did you change the **Window Placement** settings in the Editor Settings?

Also, are you using multiple monitors? If so, which resolution/DPI do they have?

**Comment by nPHYN1T3** [comment]
#1 No I've never set my window placement. In the options it is:
Rect Centered
Rect Custom Position x 0 y 0
Screen Same as Editor

#1.1 it always launches off screen and has since Godot 2x builds. Editor is on GPU 0 Screen 2, window opens on screen 1 with the minus XY coords I show in the command line.

#2 As stated in the original bug report I'm running Multi GPU/XScreen. DPI is 96, total screens 8, editor on XScreen 0.0 screen 2 (if we're listing screens from a 1 index)

**Comment by Calinou** [comment]
I suppose a workaround would be to clamp position coordinates to always be at least `0, 0`. It'll take a long time for this issue to be properly resolved (if ever), since no contributors have a setup with multiple GPUs and large amounts of monitors.

**Comment by nPHYN1T3** [comment]
Why would anyone need my set up? I mean the issue is how/why does Godot ignore the settings for the window and what is it querying to get the wrong coords?

Keep in mind I don't have all my screens or XScreens set up atm. I had to tear this apart a while back so it's a very 3x3 aligned set up right now. Normally there are screens on the flank of this 3x3 grid. Those I run in separate XScreens because it will cause (comically) issues like this where applications will open in dead spots.

GPU 0 Screen 0: minimum 8 x 8, current 5760 x 1080, maximum 32767 x 32767
DP-0 connected 1920x1080+3840+0 (normal left inverted right x axis y axis) 527mm x 296mm
   1920x1080     60.00*+  59.94    50.00  
   1680x1050     59.95  
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1280x800      59.81  
   1280x720      60.00    59.94    50.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    59.94    59.93  
DP-1 disconnected (normal left inverted right x axis y axis)
DP-2 connected primary 1920x1080+1920+0 (normal left inverted right x axis y axis) 527mm x 296mm
   1920x1080     60.00*+  59.94    50.00  
   1680x1050     59.95  
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1280x800      59.81  
   1280x720      60.00    59.94    50.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    59.94    59.93  
DP-3 disconnected (normal left inverted right x axis y axis)
HDMI-0 disconnected (normal left inverted right x axis y axis)
DP-4 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 527mm x 296mm
   1920x1080     60.00*+  59.94    50.00  
   1680x1050     59.95  
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1280x800      59.81  
   1280x720      60.00    59.94    50.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    59.94    59.93  
DP-5 disconnected (normal left inverted right x axis y axis)

GPU 1 Screen 1: minimum 8 x 8, current 5760 x 1080, maximum 32767 x 32767
DVI-D-0 disconnected (normal left inverted right x axis y axis)
DP-0 disconnected (normal left inverted right x axis y axis)
DP-1 connected 1920x1080+3840+0 (normal left inverted right x axis y axis) 509mm x 286mm
   1920x1080     60.00*+
   1440x900      59.89  
   1280x1024     60.02  
   1280x800      59.81  
   1152x864      75.00  
   1024x768      70.07    60.00  
   800x600       60.32    56.25  
   640x480       59.94  
HDMI-0 connected primary 1920x1080+1920+0 (normal left inverted right x axis y axis) 509mm x 286mm
   1920x1080     60.00*+  59.94    50.00  
   1680x1050     59.95  
   1440x900      59.89  
   1280x1024     60.02  
   1280x800      59.81  
   1280x720      60.00    59.94    50.00  
   1152x864      75.00  
   1024x768      70.07    60.00  
   800x600       60.32    56.25  
   720x576       50.00  
   720x480       59.94  
   640x480       59.94    59.93  
DP-2 disconnected (normal left inverted right x axis y axis)
DP-3 disconnected (normal left inverted right x axis y axis)
DP-4 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 509mm x 286mm
   1920x1080     60.00*+
   1440x900      59.89  
   1280x1024     60.02  
   1280x800      59.81  
   1152x864      75.00  
   1024x768      70.07    60.00  
   800x600       60.32    56.25  
   640x480       59.94  
DP-5 disconnected (normal left inverted right x axis y axis)

**Comment by nPHYN1T3** [comment]
Any ETA of v4 if that's when the fix will drop?
