### ISSUE TITLE
Error ItemList.clear ( )

### ISSUE THREAD

**Issue by DimitriyPS** [godotengine/godot#5817]
Godot 2.0.3

ItemList.clear not removes horizontal lines:
![Imge](http://savepic.ru/10553557.png)

**Comment by akien-mga** [comment]
I don't confirm that, please provide an example and/or steps to reproduce.

**Comment by DimitriyPS** [comment]
Right now I do not have the ability to add an example. If it is necessary I will try to add it tomorrow.

Steps to reproduce:
1. ItemList add to the scene;
2. Fill it up any items;
3. Call ItemList.clear ().

**Comment by vnen** [comment]
I confirm on the latest master.

**Comment by DimitriyPS** [comment]
As I promised demo:
[demo.zip](https://github.com/godotengine/godot/files/375351/demo.zip)
