### ISSUE TITLE
JavaScript editor compilation error: no member named 'is_project_manager' in 'Main'

### ISSUE THREAD

**Issue by liuyang0623** [godotengine/godot#58172]
### Godot version

3.4.2-stable

### System information

error: no member named 'is_project_manager' in 'Main'

### Issue description

error: no member named 'is_project_manager' in 'Main'
![image](https://user-images.githubusercontent.com/30205968/154214419-2faacef9-167b-43b4-bc91-5459e7b0a577.png)

### Steps to reproduce

文档不够详细

**Comment by akien-mga** [comment]
Why close? This seems to be a valid bug.

Note that you're building the `master` branch and not `3.4.2`.
