### ISSUE TITLE
ItemList: VSeparation does not apply on top of first item

### ISSUE THREAD

**Issue by DimitriyPS** [godotengine/godot#5818]
Godot 2.0.3

Item Index = 0 - no indentation top:
![Imge](http://savepic.ru/10609899.png)

**Comment by akien-mga** [comment]
Thanks for including images, it's helpful. It would be nice to include them by dragging and dropping instead of just putting a link though, as then they are hosted on GitHub and directly visible (if savepic.ru removes your images after a while, those issues would become quite hard to read).

**Comment by DimitriyPS** [comment]
>  It would be nice to include them by dragging and dropping instead
As simple as that. I didn't know about this feature.

**Comment by DimitriyPS** [comment]
Can I here ask. I assumed that "HSeparation" works similarly to "VSeparation" left and right. But I don't see any effect. (the indent in the beginning of the line that you see in the screenshot is the transparent icon). Why the need for "HSeparation"? And how to indent the beginning of a line?

**Comment by bojidar-bg** [comment]
@DimitriyPS HSeparation is for grid-mode item lists. :smile: 

Also, is this behaviour consistent with BoxContainers?

**Comment by DimitriyPS** [comment]
[ItemList](http://docs.godotengine.org/en/latest/classes/class_itemlist.html?highlight=itemlist)
This is all the available information. Not much.

> for grid-mode item lists

Can you be more specific?

> Also, is this behaviour consistent with BoxContainers?

Sorry, I don't understand the question.

**Comment by MarianoGnu** [comment]
there's not suposed to be separaton at the top and bottom, seperation does just that: distance beatwhen two items. Instead of that use the top margin and bottom margin

**Comment by DimitriyPS** [comment]
> Instead of that use the top margin and bottom margin
Where are these options?

PS: Information explain the purpose of these fields is not, therefore, rely more on the experimental method.

**Comment by bojidar-bg** [comment]
@DimitriyPS:
> Can you be more specific?

Well, I don't remember how was it possible to use ItemList as a grid, but I'm positive that the Tilemap editor and FileSystem dock both do this.

> Where are these options?

He is talking about the margin properties inherited by the Control class. You would have to set the anchors accordingly for this to work though (a MarginContainer might also help :smile: )

> >Also, is this behaviour consistent with BoxContainers?

> Sorry, I don't understand the question.

Well, I'm asking if using VBoxContainer instead of ItemList does the same or not.

**Comment by DimitriyPS** [comment]
From what was said, I understand that VSeparation works correctly (without errors).

You gave me advice, but unfortunately I do not understand what to do (the language barrier). Perhaps this bug report is erroneous. Perhaps the problem has a solution. I prepared a demo for another bugreport (attached below), It has ItemList. If it is not difficult, please, using the demo show how to solve this problem with the indent of the first paragraph.

[demo.zip](https://github.com/godotengine/godot/files/375360/demo.zip)

**Comment by Anutrix** [comment]
Image Link broken? Says "Non-Image content-type returned".

**Comment by DimitriyPS** [comment]
In fact, in subsequent versions this has been fixed. I thought that appeal was closed.
