### ISSUE TITLE
Godot4: init_library: does not have a library for the current platform.

### ISSUE THREAD

**Issue by SolsticeProjekt** [godotengine/godot#58183]
### Godot version

v4.0.alpha1.official [31a7ddbf8]

### System information

Windows 10

### Issue description

The attached demo project works in current stable, but not in 4.0 alpha.

I get this first error:
```
W 0:00:00:0047   _debug_messenger_callback: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
	ReadDataFilesInRegistry: Registry lookup failed to get layer manifest files.
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 128357280
  <C++ Source>   drivers/vulkan/vulkan_context.cpp:154 @ _debug_messenger_callback()
```

... but I seem to get this with other projects as well, so it's probably not related.

Then ...

`@onready var DLL := preload("res://DLLTest.gdns")` causes ...

```
  E 0:00:00:0632   init_library:  does not have a library for the current platform.
  <C++ Error>    Condition "lib_path.length() == 0" is true.
  <C++ Source>   modules/gdnative/nativescript/nativescript.cpp:1446 @ init_library()
```

The dll is based on a free pascal example which works in current stable.

"Latest" and "Stable" show the same text in the docs, so I don't know what I'm doing wrong.
I had the issue with stable first as well, but that was apparently just me messing something up with the gd* files.

### Steps to reproduce

See attached zip-file.

### Minimal reproduction project

[DLLTest4.zip](https://github.com/godotengine/godot/files/8080274/DLLTest4.zip)

**Comment by SolsticeProjekt** [comment]
Nevermind, I'm an idiot. I've apparently ignored that they need to be changed.
Now I just need to figure out what to actually change, and how.

**Comment by akien-mga** [comment]
Note that GDNative doesn't exist in 4.0 anymore, it has been replaced by GDExtension: https://godotengine.org/article/introducing-gd-extensions

The setup is different, and not extensively documented yet as it's still WIP.

**Comment by SolsticeProjekt** [comment]
> Note that GDNative doesn't exist in 4.0 anymore, it has been replaced by GDExtension: https://godotengine.org/article/introducing-gd-extensions
> 
> The setup is different, and not extensively documented yet as it's still WIP.

Are you sure? It's both still in the engine and the docs as well!

I guess, I can scratch writing dlls directly. There was one freepascal example for 3+, but that's it.
I have zero understanding of how this works, or how to get it to work, and trying to learn how it works hasn't really helped.

I'm no fan of using sockets for IPC with a native process, especially because I'm not convinced zero-copy is supported.

Why does this have to be so unnecessarily complicated?
Why can't we simply have (shared) memory mapping and save people, me included, tons of unnecessary work?

**Comment by akien-mga** [comment]
Yes, I'm sure :)

As I mentioned, the documentation hasn't been updated yet.

Godot 4.0 is in **alpha**, which is an unstable stage of development where features still change on a daily basis and are not meant for use in production. Accordingly, they are not documented yet to the level that you would expect, and this is intended.

If you want it to "just work", you can use Godot 3.4.x, or wait for Godot 4.0 to reach a more stable phase with up-to-date documentation.
