### ISSUE TITLE
Export to Android fails with INSTALL_PARSE_FAILED_NO_CERTIFICATES, Attempt to get length of null array

### ISSUE THREAD

**Issue by mrkdji** [godotengine/godot#58192]
### Godot version

3.4.2, 3.3.4, 3.3

### System information

Windows 10

### Issue description

Since yesterday I was getting this error every time I tried to export to android:
```
Could not install to device: adb: failed to install C:/Users/markd/AppData/Local/Temp/Godot/tmpexport.1645007435.apk: Failure
[INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed collecting certificates for /data/app/vmdl363245540.tmp/base.apk: Failed to collect 
certificates from /data/app/vmdl363245540.tmp/base.apk: Attempt to get length of null array]
Performing Streamed Install
```

I tried to re-install both openJDK and Android Studio as was suggested in this Q&A:
https://godotengine.org/qa/94015/cant-deploy-android-install_parse_failed_no_certificates

But it didn't solve it.
I tried to run godot from the command line with --verbose, and this is the relevant output:
```
Starting signing of the APK binary using C:/Users/markd/AppData/Local/Android/Sdk/build-tools/29.0.2/apksigner.bat
Signing debug binary using:
C:/Users/markd/AppData/Local/Android/Sdk/build-tools/29.0.2/apksigner.bat sign --verbose --ks C:/Users/markd/.android/debug.keystore --ks-pass pass:android --ks-key-alias androiddebugkey C:/Users/markd/AppData/Local/Temp/Godot/tmpexport.1645007693.apk

ERROR: No suitable Java found. In order to properly use the Android Developer
Tools, you need a suitable version of Java JDK installed on your system.
We recommend that you install the JDK version of JavaSE, available here:
  http://www.oracle.com/technetwork/java/javase/downloads

If you already have Java installed, you can define the JAVA_HOME environment
variable in Control Panel / System / Avanced System Settings to point to the
JDK folder.

You can find the complete Android SDK requirements here:
  http://developer.android.com/sdk/requirements.html


Verifying signed build using:
C:/Users/markd/AppData/Local/Android/Sdk/build-tools/29.0.2/apksigner.bat verify --verbose C:/Users/markd/AppData/Local/Temp/Godot/tmpexport.1645007693.apk

ERROR: No suitable Java found. In order to properly use the Android Developer
Tools, you need a suitable version of Java JDK installed on your system.
We recommend that you install the JDK version of JavaSE, available here:
  http://www.oracle.com/technetwork/java/javase/downloads

If you already have Java installed, you can define the JAVA_HOME environment
variable in Control Panel / System / Avanced System Settings to point to the
JDK folder.

You can find the complete Android SDK requirements here:
  http://developer.android.com/sdk/requirements.html


Successfully completed signing build.
Installing to device (please wait...): Samsung SM-A226B
adb: failed to install C:/Users/markd/AppData/Local/Temp/Godot/tmpexport.1645007693.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed collecting certificates for /data/app/vmdl1455162204.tmp/base.apk: Failed to collect certificates from /data/app/vmdl1455162204.tmp/base.apk: Attempt to get length of null array]
Performing Streamed Install
```

At first I managed to solve the issue simply by downloading the oracleJDK as suggested in the error log, but some time later I noticed that of the 4 different versions of Android SDK build-tools I had installed it was always the lowest one to be selected on export:
```
Signing debug binary using:
C:/Users/markd/AppData/Local/Android/Sdk/build-tools/29.0.2/apksigner.bat sign --verbose --ks 
```
As soon as I removed the build-tools versions prior to 30.0.3 I could export again on Android even after having uninstalled the oracle JDK
![image](https://user-images.githubusercontent.com/38851942/154299235-e3626dd6-e08d-4718-a765-f234c9e89ed6.png)

So the proper issue is: 
_When multiple versions of Android SDK build-tools are installed the lowest version is used even if it's lower than the one recommended in the [docs](https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_android.html)_

**Additional Notes:**

- I had no such export error with Godot version 3.2.3, but I had it in Godot 3.3, 3.3.4 and 3.4.2;
- I was able to export to Android just fine a few weeks ago, I believe the problem originated as I recently downloaded a virtual device in order to do some app development;

### Steps to reproduce

- Install a lower version than 30.0.3 of Android SDK build-tools (I tested with 29.0.0);
- Create an empty Godot project and try to export it to Android;

The export should fail with this error:
![image](https://user-images.githubusercontent.com/38851942/154308695-9fd83bc0-e521-4f73-b5b1-71e405612c43.png)

**Comment by mrkdji** [comment]
So I found out that [EditorExportPlatformAndroid::get_apksigner_path()](https://github.com/godotengine/godot/blob/3a6e25017499b5547c7883ebe9c190be03e17135/platform/android/export/export_plugin.cpp#L2009) looks for the first subfolder of "Sdk/build-tools" which contains a `apksigner.bat` script:
___
![image](https://user-images.githubusercontent.com/38851942/154338810-1a3f8133-3826-4d74-9485-aed328c8f63e.png)
```C++
String EditorExportPlatformAndroid::get_apksigner_path() {
	String exe_ext = "";
	if (OS::get_singleton()->get_name() == "Windows") {
		exe_ext = ".bat";
	}
	String apksigner_command_name = "apksigner" + exe_ext;
	String sdk_path = EditorSettings::get_singleton()->get("export/android/android_sdk_path");
	String apksigner_path = "";

	Error errn;
	String build_tools_dir = sdk_path.plus_file("build-tools");
	DirAccessRef da = DirAccess::open(build_tools_dir, &errn);
	if (errn != OK) {
		print_error("Unable to open Android 'build-tools' directory.");
		return apksigner_path;
	}

	// There are additional versions directories we need to go through.
	da->list_dir_begin();
	String sub_dir = da->get_next();
	while (!sub_dir.empty()) {
		if (!sub_dir.begins_with(".") && da->current_is_dir()) {
			// Check if the tool is here.
			String tool_path = build_tools_dir.plus_file(sub_dir).plus_file(apksigner_command_name);
			if (FileAccess::exists(tool_path)) {
				apksigner_path = tool_path;
				break;
			}
		}
		sub_dir = da->get_next();
	}
	da->list_dir_end();

	if (apksigner_path.empty()) {
		EditorNode::get_singleton()->show_warning(TTR("Unable to find the 'apksigner' tool."));
	}

	return apksigner_path;
}
```

I believe that DirAccess::list_dir_begin and DirAccess::get_next iterate on folders in lexicographic order so the exporter ends up choosing the lower version of the build-tools.

One possible solution could be to put all the valid subfolder names into a Vector and sort it (or maybe simply invert it) so that folders relative to a higher version are processed first. What do you think?

**Comment by mrkdji** [comment]
Alternatively one could change the Exporting for Android docs section and recommend to install oracle JDK instead of openJDK

**Comment by warriormaster12** [comment]
I've noticed the same issue on Linux with 3.4.3-rc2. In addition I've successfully managed to build and run an apk when hooking up my phone to my computer and pressing android icon (next to play icon) to build the project. It went successfully without any issues. But when trying to do it through export template, well that's where the issues begin.

**Comment by damnedpie** [comment]
I literally had the same error and it was weird, because it was only throwing it when I had a mobile phone and a MIDI controller plugged into my PC. If it was only the phone and plugged, everything worked fine. In both cases Godot editor was displaying only one device for deployment which was the phone. Kinda strange that periphery plugged can mess this up.

**Comment by m4gr3d** [comment]
@akien-mga This issue should be resolved by https://github.com/godotengine/godot/pull/67668.

Looks like it hasn't been cherry-picked yet.

**Comment by akien-mga** [comment]
Great, I'll get to it eventually for 3.6-beta1.

**Comment by mrkdji** [comment]
Have you already checked if you have more than one version of the build-tools in AppData/Local/Android/Sdk/build-tools? 
I remember that the bug was caused by Godot automatically selecting the lowest build-tools version.

As for the Android  one-click deploy icon sometimes I had to disable and re-enable usb debug on the android device in order for it to show again.

**Comment by frankhuurman** [comment]
Found this reddit page: https://www.reddit.com/r/godot/comments/1204d2u/apksigner_failed_to_execute_warning_when/

And the solution mentioned there worked for me, namely running Godot from the terminal instead of double-clicking to open.
This fixed the apksigner issue for me and the one-click installs work again(the remote debugging doesn't yet but I figure that's something else).

**Comment by frankhuurman** [comment]
> 



> Have you already checked if you have more than one version of the build-tools in AppData/Local/Android/Sdk/build-tools? I remember that the bug was caused by Godot automatically selecting the lowest build-tools version.
> 
> As for the Android one-click deploy icon sometimes I had to disable and re-enable usb debug on the android device in order for it to show again.

Only had 1 build-tools version, all the versions were as stated in the Android Export docs, JAVA_HOME was set properly and it was the OpenJDK version downloaded from the Android Export docs as well, all the terminal stuff worked manually but just the Godot things didn't.

But apparently it runs in a different mode when double-clicked rather than running ./Godot_v4.1.2-stable_linux.x86_64

**Comment by misterwaztaken** [comment]
Should this issue be closed now?

**Comment by heroassem** [comment]
editor/export/editor_export_platform.h:182 - Run: Could not install to device: adb: failed to install C:/Users/Admin/AppData/Local/Godot/tmpexport.1718554870.apk: Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Existing package com.example.project signatures do not match newer version; ignoring!]
  Performing Streamed Install

**Comment by heroassem** [comment]
![Screenshot 2024-06-16 172020](https://github.com/godotengine/godot/assets/165303929/beb763b7-5a02-4d34-9474-7f764bd3ee54)

### My System
windows 10
64bit 
### My engine 
godot 4.2.2
### My Error
` editor/export/editor_export_platform.h:182 - Run: Could not install to device: adb: failed to install C:/Users/Admin/AppData/Local/Godot/tmpexport.1718550563.apk: Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Existing package com.example.project signatures do not match newer version; ignoring!]
  Performing Streamed `Install``

**Comment by xivol** [comment]
It's still not _completed_ on 4.2.2. Android studio builds and runs project just fine but not from godot one button Run on device.  
```Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl764498971.tmp/base.apk: Attempt to get length of null array]```
