### ISSUE TITLE
OpenSimplexNoise Poor Multithreading Performance

### ISSUE THREAD

**Issue by qdeanc** [godotengine/godot#58199]
### Godot version

3.4.2-stable, 4.0-alpha

### System information

Windows 10, Intel Core i7 8700-K

### Issue description

Generating noise using OpenSimplexNoise becomes slower when done across multiple threads.
For example, running unique instances of OpenSimplexNoise on 2 threads makes noise generation twice as slow on both threads.

    extends Node

    #Number of noise gen iterations to do per thread
    export(int)var count = 2000000

    onready var thread0 = Thread.new()
    onready var thread1 = Thread.new()
    onready var thread2 = Thread.new()
    onready var thread3 = Thread.new()
    onready var thread4 = Thread.new()
    onready var thread5 = Thread.new()

    var val0 = 0
    var val1 = 0
    var val2 = 0
    var val3 = 0
    var val4 = 0
    var val5 = 0

    onready var time_start = OS.get_ticks_msec()

    func _ready():
        _dispatch_threads()
	

    func _dispatch_threads():
        #Dispatch thread function
        thread0.start(self, "_thread_function", [thread0, val0, count])
        thread1.start(self, "_thread_function", [thread1, val1, count])
        #thread2.start(self, "_thread_function", [thread2, val2, count])
        #thread3.start(self, "_thread_function", [thread3, val3, count])
        #thread4.start(self, "_thread_function", [thread4, val4, count])
        #thread5.start(self, "_thread_function", [thread5, val5, count])
	
        #Log the thread dispatch
        print("Threads dispatched")

    func _exit_thread(var thread: Thread):
         thread.wait_to_finish()

    func _thread_function(userdata):
        var thread = userdata[0]
        var noise = OpenSimplexNoise.new()
        var val = userdata[1]
        var _count = userdata[2]
	
        while(_count > 0):
            val += noise.get_noise_3d(1,1,1)
            _count -= 1
	
        print("Thread process time: " + str(_time()))	
        call_deferred("_exit_thread", thread)

    func _time():
        var time_now = OS.get_ticks_msec()
        return (time_now - time_start) / 1000.0

### Steps to reproduce

Run the script or run the project and try changing the number of threads via commenting out lines from the _thread_dispatch() function.

### Minimal reproduction project

[OpenSimplexNoise_Multithreading_Test.zip](https://github.com/godotengine/godot/files/8082240/OpenSimplexNoise_Multithreading_Test.zip)

**Comment by Calinou** [comment]
I wonder if https://github.com/godotengine/godot/pull/56718 resolves this.

**Comment by qdeanc** [comment]
I just created the Summator module by following Godot's documentation. (Using 3.4.2-stable source code)
When trying this same test, but calling Summator.add() instead of OpenSimplexNoise.get_noise_3d(), I'm getting the same results:
1 thread takes 0.33 seconds, 2 threads takes about 0.7 seconds each, 3 threads takes around 2.5 seconds each, etc.

Is this intended, maybe?

**Comment by qdeanc** [comment]
[summator.zip](https://github.com/godotengine/godot/files/8086233/summator.zip)
Here are the Summator module files from the tutorial:

**Comment by qdeanc** [comment]
Just tested running 2 threads:
One iteratively calling OpenSimplexNoise.get_noise_3d()
One literately calling Summator.add()

Running these two threads simultaneously and sequentially seems to yield similar processing times, with some expected overhead.

So it seems like multiple instances of the same class cannot run simultaneously, while instances of various classes can.
Is this due to shared memory maybe?

**Comment by qdeanc** [comment]
Doing some more testing and I'm getting different results now.
Simultaneous threads using the same class functions are working better suddenly, but with a lot of overhead.
I'm going to close this issue until I'm more confident in what the issue is exactly.
