### ISSUE TITLE
Exported parameters are not properly read when the instance of a resource has its own script

### ISSUE THREAD

**Issue by gokudomatic** [godotengine/godot#582]
Let say an object (scene) contains a script. And then I create a different script extending the script of the object to apply it to an instance of the object. If I export a parameter in the second script, it will always have the default value at runtime, no matter what I set in the instance's property. There's a diagram explaining it:
![67i6f6](https://cloud.githubusercontent.com/assets/587885/3544897/ab467b06-0871-11e4-8f9b-e0656f204ced.jpg)
In class N2, param2 has a default value, that instance cannot modify. However param1 can be modified.

I created an example for this case. You can download it here:
https://drive.google.com/file/d/0B1UVb9K9E3_8UHhwVllQWV9DLWc/edit?usp=sharing

**Comment by akien-mga** [comment]
I think this has been fixed in c79be97.
