### ISSUE TITLE
Visible seam on smoothed sphere and cylinder shapes

### ISSUE THREAD

**Issue by MythTitans** [godotengine/godot#58207]
### Godot version

3.4.2-stable, v4.0.dev

### System information

Windows 11, Vulkan

### Issue description

When the _Smooth Faces_ option is enabled on CSG sphere and cylinder shapes, they produce a visible seam at the junction of their first and last radial segment.

![sphere_small](https://user-images.githubusercontent.com/1554884/154363151-ffbbe4c5-9ac1-4e3d-bb41-53439f7151a9.png)
![cylinder_small](https://user-images.githubusercontent.com/1554884/154363163-88341398-1ef0-45b4-a860-c4ab6669abb8.png)

### Steps to reproduce

Create a CSGSphere3D or CSGCylinder3D object and the seam should be immediately visible. Adding an OmniLight3D close to it can make the seam even more visible.

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/49800.

**Comment by hoontee** [comment]
Seams no longer occur, however there are still more issues with normals outlined in #49800.

**Comment by MythTitans** [comment]
The same problem is present on torus, can be fixed in PR #59002.
