### ISSUE TITLE
Sprite2D added through script isn't added to the Scenetree

### ISSUE THREAD

**Issue by lambferatu** [godotengine/godot#58217]
### Godot version

4.0.alpha2

### System information

Windows 11, Nvidia 1050 Ti, Vulkan, Android 10, Huawei Nova 5T

### Issue description

Creating an scene with a root node of type Sprite2D, then instantiating as a child node from another scene, doesn't add it to the scenetree on Android

In this example I added a node directly from the editor and other through code. This is how the scenetree look while running on Windows, both nodes appear under Node:

![image](https://user-images.githubusercontent.com/53798244/154388665-98ced034-4af0-48bc-9e79-e056c4ba6bf5.png)

However this is how it looks while running on Android:

![image](https://user-images.githubusercontent.com/53798244/154388976-cf70b2bd-c4d6-4495-8ea6-c1ff5bdc299b.png)

the code is the same in both cases, and these are the results:

Windows:

![image](https://user-images.githubusercontent.com/53798244/154389228-85e9344f-e799-4ffe-bd30-88aa1c102113.png)

Android:

![image](https://user-images.githubusercontent.com/53798244/154389119-918025d9-bb03-4b1c-a256-6744680329d6.png)

This works on version 3.4.2:

![image](https://user-images.githubusercontent.com/53798244/154390388-303016d1-0316-41a3-9985-5282cdc9cce7.png)

![image](https://user-images.githubusercontent.com/53798244/154390105-2299512d-2769-476c-adc5-014fc4dec6cc.png)

### Steps to reproduce

1 - Create an scene with a sprite
2 - Instantiate the scene from another scene through code, something like this:
```
extends Node

var sprite_scene = load("res://Sprite.tscn")

func _ready():
    var sprite = sprite_scene.instantiate()
    sprite.position = Vector2(100, 100)
    add_child(sprite)

```

3 - Run on Android

### Minimal reproduction project

[AndroidTestG4.zip](https://github.com/godotengine/godot/files/8084957/AndroidTestG4.zip)

**Comment by Calinou** [comment]
This is due to case sensitivity, but the editor doesn't warn about it.

The instanced scene is saved as `sprite.tscn`, but you're using `load("res://Sprite.tscn)` in the script.

**Comment by lambferatu** [comment]
@Calinou sorry I didn't see my mistake, the 3.4.2 has the scene name written correctly in the script, here is the project:

[AndroidTest.zip](https://github.com/godotengine/godot/files/8091411/AndroidTest.zip)
