### ISSUE TITLE
Godot 4: all the property nodes in the add node window in Visual Script are missing their setter

### ISSUE THREAD

**Issue by kreaninw** [godotengine/godot#58225]
### Godot version

v4.0.alpha2.official [79077e6c1]

### System information

Windows 11, Vulkan Clustered, Intel UHD Graphics 620 v30.0.101.1340

### Issue description

All the property nodes in the add node window in Visual Script are missing their setter, only the getter is available, as shown in the screenshot below:

![Screenshot 2022-02-17 002626](https://user-images.githubusercontent.com/1403194/154399083-347ed526-bd43-496b-83da-ed3feda3b11f.jpg)

This behavior is inconsistent with some methods that have both the getter and setter of which are presented in the list, as shown in the screenshot below:

![Screenshot 2022-02-16 235207](https://user-images.githubusercontent.com/1403194/154399398-93b4e31c-5d51-45d9-8156-9796424d99aa.jpg)

This issue is a regression from Godot 3.4. In Godot 3.4, both the getter and setter are presented in the list, as shown in the screenshot below:

![Screenshot 2022-02-17 002135](https://user-images.githubusercontent.com/1403194/154399854-a418aea8-81f0-40be-8e65-e84916900187.jpg)

I expect both the getter and setter of all the properties to be presented in the add node window's list.

### Steps to reproduce

1. Open the add node window in Visual Script.
2. Try to add any property node, for example, the transform node. You won't see a way to add the setter of the property you selected.

**Comment by SirQuartz** [comment]
Upon my investigation, it would appear that this segment is the problem.

https://github.com/godotengine/godot/blob/83d26737727f281afcb33f66fea5d09ed6c48d5a/modules/visual_script/editor/visual_script_property_selector.cpp#L892-L901

Other than that, the entire system used to do the searching in 3.x is completely different from the way it's done in 4.0.

**Comment by KoBeWi** [comment]
VisualScript was removed in Godot 4.0, so closing.
