### ISSUE TITLE
Setting FileDialog Visibility to "true" makes Editor unresponsive

### ISSUE THREAD

**Issue by Sauermann** [godotengine/godot#58229]
### Godot version

v4.0.alpha.custom_build [5d5f80b52]

### System information

Linux, Debain 11, Xfce, Nvidia, Vulkan

### Issue description

Setting in the Editor the Visibility Flag of a FileDialog to "true" makes the Editor unresponsive.
I would expect, that the Editor stays responsive.

### Steps to reproduce

1. Load MRP or alternatively add a FileDialog Node
2. Select FileDialog Node in SceneTree
3. Set Visibility flag to "true"
4. Now the Editor becomes unresponsive

### Minimal reproduction project

[BugDialog.zip](https://github.com/godotengine/godot/files/8085997/BugDialog.zip)

**Comment by keptsecret** [comment]
It seems this behavior extends to `AcceptDialog` and `ConfirmationDialog` as well. I'm still trying to figure out why.

**Comment by timothyqiu** [comment]
Looks like something needs to be done when `Engine::get_singleton()->is_editor_hint()` is true.

You can use this `3.x` code as a reference, although many things changed in `master`:

https://github.com/godotengine/godot/blob/747d11b5b977dcd056269bdd90628fdc396eb30b/scene/gui/popup.cpp#L58-L69
