### ISSUE TITLE
Godot 4: Transform3D node in Visual Script can't return its index setting value to blank

### ISSUE THREAD

**Issue by kreaninw** [godotengine/godot#58224]
### Godot version

v4.0.alpha2.official [79077e6c1]

### System information

Windows 11, Vulkan Clustered, Intel UHD Graphics 620 v30.0.101.1340

### Issue description

Transform3D node in Visual Script can't return its index setting value to blank, since the blank list in the menu is missing, as shown in the screenshot below:

![Screenshot 2022-02-16 235610](https://user-images.githubusercontent.com/1403194/154396921-3bf1a447-1e3f-49fc-89a3-5760858bb912.jpg)

This is a regression from Godot 3.4. In Godot 3.4, there's a blank list in the menu so the users don't have to delete the whole node to return the index to blank, as shown in the screenshot below:

![Screenshot 2022-02-16 235507](https://user-images.githubusercontent.com/1403194/154397288-553c3e75-b179-4987-9dfe-26811c276f71.jpg)

You can see this action, which is impossible in Godot 4, in Godot 3.4 from the screen recording below:

https://user-images.githubusercontent.com/1403194/154397452-e256a921-2287-4124-898d-f65220a3c9f1.mp4

I expect the blank list to be available in the index setting menu.

### Steps to reproduce

1. Add a transform node (3D) in Visual Script.
2. Change the node's Set Mode to Basic Type.
3. Change Basic Type to Transform3D.
4. Change its Property to either basis or origin.
5. See in the Index list, there's no blank value to set.

**Comment by KoBeWi** [comment]
VisualScript was removed in Godot 4.0, so closing.
