### ISSUE TITLE
GDParser reports invalid operands syntax error on wrong line

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#5822]
**Operating system or device - Godot version:**
Mageia 6 x64, Godot 2.0.4.1 and git master HEAD.

**Issue description** (what happened, and what was expected):
When typing an invalid expression like `var test = 42 + "a"`, the error is reported at column 0 of the following line.
![spectacle r29012](https://cloud.githubusercontent.com/assets/4701338/16996417/83c9edc8-4eb1-11e6-97de-793d1556f796.png)

If the invalid expression is end with a semi-colon, however, it works fine:
![spectacle j29012](https://cloud.githubusercontent.com/assets/4701338/16996457/aa41bde6-4eb1-11e6-99ae-4f9f84720877.png)

**Comment by bojidar-bg** [comment]
If the game is ran at this point, the debugger would also display the line wrong. With this in mind I ran a few more tests (that only show in runtime):
````gdscript
#(using the float % int, int % float and float % float undefined operators to cause the error)
# Setup
var val = 4.0
const con = 5.0

# Bad
var a = 42 % 5.0
var b = some_undefined_identifier
var c = 5 % (0 + 3 * (2 - 5 * ((0.3) * 4 - 2))) # Works no matter the ( and )
var d = 5/0
var e = 5/(1+2+3-2*(4-3+2))
var f = 5/0 == 4 # Who cares what follows... (contrast with `w`)
var g = {'t':3}['t'] == 5/0 # Who cares whatever complex is before?... (contrast with `z`)
var h = {4: 6, 5/0: 2} # Inside dict keys, even

# Good
var z = 5 % {} # Shows line correctly
var z_ = 5.0 % ([0.5])[0] # Complex expressions __with a dictionary or array__? Go on!
var y = OS.get_window_size().x % 5.0 # Have an identifier? All works
var x = 5 % val # Variables also count
var x_ = 5 % con # huh, constants count too...
var w = 5/0"""""" # String-comment fixes all (unlike normal comments)

````
