### ISSUE TITLE
Importing a scene with a Navmesh does not place a generic navigation node.

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#5823]
**Operating system or device - Godot version:**
Win10 64 bit; ATI 79xx GPU; 24 Gigs RAM; third-gen i7 CPU
Godot 2.1 beta (Built on July20).

**Issue description** (what happened, and what was expected):
Importing a 3D scene with an object containing the -navmesh suffix will create a mesh like it should, but the fact that the importer does not create it as a child of a _navigation_ node means it will not work out of the box.

**Steps to reproduce:**
Create a mesh with the -navmesh suffix and import into Godot, you should see a little notice triangle informing that it's not a child of the required navigation node.

**Comment by Zireael07** [comment]
Is this still the case?

**Comment by Vega-KH** [comment]
This is still a problem.  I was coming to report the same and found this.  I will try to see if I can create a pull request for this, seems it should just be a minor change in the DAE and GLTF importers.

Can anyone give input on this, please: My plan is to just change the parent from spatial to Navigation if there is a child navmesh.  Any problem with this approach?

**Comment by fire** [comment]
Is this still a problem?

**Comment by fire** [comment]
Using https://github.com/godotengine/godot/issues/32712 as the tracking issue.

**Comment by Nehluxhes** [comment]
@fire That's not really the same issue though (and yes this is still a "problem").
#32712 is about the data for the NavigationMeshInstance missing (the points, the polygons), this one is about a parent Navigation node being automatically created.
That's more a convenience feature than a bug I would say, and if it makes senses for a whole scene like in the first post I am not sure how it would work in my project. I am procedurally generating a level with 3d tiles with each of those 3d tiles having its own navmesh and I certainly don't want a navigation node for each tile. Could be a setting in the import menu perhaps?

**Comment by fire** [comment]
For your problem did you look at the navigation server? Reopening.

**Comment by Ace-Dragon** [comment]
Hi.

I've since moved on to the .escn exporter made just for Blender. All of the dev. activity regarding exporters seem to be over there and it's apparently being positioned to eventually replace BetterCollada.

**Comment by fire** [comment]
You may want to review this comment from the escn developer then? https://github.com/godotengine/godot/issues/33057#issuecomment-562910818

**Comment by fire** [comment]
For Godot Engine 3.2, the principal developer activity was getting GLTF2 working via the skinned skeleton (it's a term the Godot developers made up) and the work in progress FBX.

ESCN and Collada didn't get much developer attention in the 3.2 release.

https://docs.godotengine.org/en/latest/classes/class_skin.html

In total, Godot's glTF2 is working for all the models I've tested importing. It has better gltf2 compatibility than Blender, which is a significant problem.

However, there's good news for Blender support. https://github.com/KhronosGroup/glTF-Blender-IO/pull/857 This pull request will make Blender's import on the same level as Godot's import.

However, https://github.com/KhronosGroup/glTF-Blender-IO/pull/857 missed the Blender 2.82 merge window. The pull request is roadmaps for the Blender 2.83 release cycle.

**Comment by Nehluxhes** [comment]
I don't have any problem until this issue is fixed.
I just wanted to point out that automatically having a navigation node being created is not always desirable, so it could be a setting in the import menu and not always enabled.

**Comment by fire** [comment]
https://github.com/godotengine/godot/issues/32712 was merged. I'll wait for the cherry pick to ping again.

**Comment by Calinou** [comment]
Is this still relevant with [NavigationServer in 4.0](https://godotengine.org/article/navigation-server-godot-4-0)?

**Comment by Ace-Dragon** [comment]
> Is this still relevant with [NavigationServer in 4.0](https://godotengine.org/article/navigation-server-godot-4-0)?

It appears to work with the .gltf exporter in version 4.0 alpha.

Closing.
