### ISSUE TITLE
GDScript 2.0: Advanced exports (`_get_property_list()`) don't work

### ISSUE THREAD

**Issue by Dan-Gamin** [godotengine/godot#58239]
### Godot version

v4.0-alpha2

### System information

Windows 10 64-bit, GPU: NVIDIA Geforce GTX 1650 Ti, CPU: AMD Ryzen 7 4800H

### Issue description

I was doing some stuff in Godot 4 and I realize Advanced exports don't work. While `@export`s still work, advanced ones with `_get_property_list` don't. I have no idea why this happens so its probably a bug (unless they changed the syntax since the 4.0 documentation is even less helpful than the 3.x one). I made the code below in the `Steps to reproduce` section almost compatible with 3.x (You have to replace the first line with `tool` instead of `@tool`). And in 3.x it works perfectly.

Please Fix this bug.

### Steps to reproduce

1. Add a `Node`
2. Attach a script to the `Node`
3. Paste in the following code:
```gdscript
@tool 
extends Node

var rotate_enabled: bool = false

func _get_property_list() -> Array:
	var properties: Array = []
	properties.append({
		name = "Rotate",
		type = TYPE_NIL,
		hint_string = "rotate_",
		usage = PROPERTY_USAGE_GROUP | PROPERTY_USAGE_SCRIPT_VARIABLE,
	})
	properties.append({
		name = "rotate_enabled",
		type = TYPE_BOOL,
		usage = PROPERTY_USAGE_DEFAULT,
	})
	return properties
```
4. Click on the `Node`
5. You can't see any catogories

**Comment by object71** [comment]
Btw it seems that it works if you add a custom category first.

```gdscript
properties.append({
    name = "My Properties",
    type = TYPE_NIL,
    usage = PROPERTY_USAGE_CATEGORY,
})

# ... properties outside of group

properties.append({
    name = "My Group",
    type = TYPE_NIL,
    usage = PROPERTY_USAGE_GROUP,
})

# ... properties in your group
```

And order does matter.

**Comment by object71** [comment]
The more I look at it the more I think my workaround is the appropriate approach. 

In your example you are using ```_get_property_list``` to add a script variable with the same name as an existing one. The issue is that the ```var rotate_enabled: bool = false``` is actually read and parsed as a hidden property already so the second one that you add is ignored as long as it is on the same category level.

I don't see a nicer way of exposing this property that you add in a group except by defining a separate category.

**Comment by Dan-Gamin** [comment]
> Btw it seems that it works if you add a custom category first.

Thank you, this works. But it should still work without the catergory. But it seems like #58443 fixes this. Can't wait for this to get fixed!
