### ISSUE TITLE
Vulkan: Grid is a weird black with screen-space reflections enabled

### ISSUE THREAD

**Issue by 9HarshAgarwal** [godotengine/godot#58235]
### Godot version

4.0 alpha 2

### System information

Windows 10, AMD 5600x, Nvidia 3060

### Issue description

![(_) Occult Prototyping - Godot Engine 17-02-2022 04_14_00 PM](https://user-images.githubusercontent.com/28735504/154459793-e2fc02e1-9176-4e2f-bf6e-ca47bc3a9aed.png)
![(_) Occult Prototyping - Godot Engine 17-02-2022 04_14_09 PM](https://user-images.githubusercontent.com/28735504/154459801-0a6cd326-1c23-424d-98ef-b21eca69eaf2.png)

This is how SS-reflections makes the x- and z-axes look (maybe the y-axis as well). IMO, turning on visual effects should never affect the icons/gizmos and only the art in the viewport.

### Steps to reproduce

Turning on effects in World Environments leads to all sorts of visual oddities. SSR is an example but not limited to it.

**Comment by jmb462** [comment]
This axis problem seems similar to #37016.

**Comment by Altair1234** [comment]
I have noticed more viewport "glitches":
![(_) World tscn - Occult Prototyping - Godot Engine 17-02-2022 05_32_54 PM](https://user-images.githubusercontent.com/28735504/154478010-be640c93-83d9-40b7-a2e5-0b62ea9f0b57.png)
![(_) World tscn - Occult Prototyping - Godot Engine 17-02-2022 05_33_00 PM](https://user-images.githubusercontent.com/28735504/154478019-a97db846-3d2e-4274-b644-80f014442986.png)

**Comment by Chaosus** [comment]
Please don't multiply issues in one thread - the first one is already reported and placed in https://github.com/godotengine/godot/issues/37016.

**Comment by Altair1234** [comment]
@Chaosus I was not sure so I grouped it under "viewport issues".

**Comment by Chaosus** [comment]
@Altair1234  There may be one topic (a tracker) and issues are linked to it, but they must be separated from each other since they may be raised for entirely different reasons (and may be fixed separately from each other).

**Comment by WickedInsignia** [comment]
On my PC (GTX1080, Windows 10) SSR doesn't seem to work at all and instead shows the grid through objects in a glitchy way, similar to the screenshots of the sphere attached above. Looks like pretty much the same issue.
SSR has never worked properly in every test version of 4.0 I've used (all the way back to a year ago).

**Comment by Calinou** [comment]
SSR works on my end, but it exhibits random artifacts (which move as the window is resized): https://github.com/godotengine/godot/issues/50151

**Comment by clayjohn** [comment]
This was fixed at some point and is no longer reproducible
