### ISSUE TITLE
Debug console not shown on "export project" with "export with debug"

### ISSUE THREAD

**Issue by stryker313** [godotengine/godot#58241]
### Godot version

Godot 4 Alpha 2

### System information

Windows 10 Intel 4690k GTX 1060

### Issue description

Exporting a game via "export project" with "export with debug" does not show the console
Related : #56884
However, that one is focused on the export all, not "export project", but similar field.

### Steps to reproduce

1. Open Godot 4 ALpha 2
2. Install export templates
3. Export game as project with "export with debug" enabled
4. Game will not have a console

### Minimal reproduction project

[Uploading Bugged Export.zip…]()

**Comment by Calinou** [comment]
Does reverting https://github.com/godotengine/godot/pull/56012 and compiling a debug export template fix the issue for you?

**Comment by Calinou** [comment]
> Otherwise you can ship your debug build with a .bat file that runs the project in a console explicitly, like we do for Godot itself. 

Creating this .bat file automatically for projects exported in debug mode sounds interesting.

**Comment by bruvzg** [comment]
> Creating this .bat file automatically for projects exported in debug mode sounds interesting.

Should be easy to add, I'll take a look tomorrow.

**Comment by akien-mga** [comment]
Should probably be opt-in, and implemented for macOS and Linux debug exports too?

**Comment by Calinou** [comment]
> Should probably be opt-in, and implemented for macOS and Linux debug exports too?

I'm not sure if it needs to be opt-in, unless we want to expose this for projects exported in release mode as well. If you really don't need it for a project exported in debug mode, you can remove the `.bat` file after exporting the project.

**Comment by stryker313** [comment]
I know that this has been fixed now, but is there an example of the .bat file for exported console? I kinda wanna try something before Alpha 5.
