### ISSUE TITLE
add_custom_type's "base" argument should work set to "Node"

### ISSUE THREAD

**Issue by RefinedSoftwareLLC** [godotengine/godot#58248]
### Godot version

4.0 Alpha 2

### System information

Linux

### Issue description

`add_custom_type`'s "base" argument should work set to "Node" but doesn't. Using "Node2D" in place of "Node" does work.

### Steps to reproduce

`script.gd`
```
@tool
extends Node
class_name MyNode
```
`plugin.gd`
```
add_custom_type("MyNode", "Node", script, icon)
#"Add Child Node" -> "Create New Node" -> "MyNode" isn't listed
```
Change "Node" to "Node2D"
`plugin.gd`
```
add_custom_type("MyNode", "Node2D", script, icon)
#"Add Child Node" -> "Create New Node" -> "MyNode" is listed
```
![image](https://user-images.githubusercontent.com/3934352/154530386-922dba42-f059-40c1-bd2a-503ac6f7a7fc.png)

### Minimal reproduction project

[New Game Project.zip](https://github.com/godotengine/godot/files/8090572/New.Game.Project.zip)

**Comment by RefinedSoftwareLLC** [comment]
It took hours to figure out the 2 characters that would work around this bug as there is no error message, add_custom_type just silently fails with no clues as to why...

**Comment by RefinedSoftwareLLC** [comment]
`script.gd`
```
@tool
extends Node
class_name MyNode
```
`plugin.gd`
```
#if class_name == add_custom_type's 1st argument:
add_custom_type("MyNode", "Node2D", script, icon) #"MyNode" is listed under Node (base = extends Node)
```
`plugin.gd`
```
#if class_name != add_custom_type's 1st argument:
add_custom_type("MyNode2", "Node2D", script, icon) #"MyNode2" is listed under Node2D (base = add_custom_type's 2nd argument Node2D)
```

**Comment by adamscott** [comment]
@RefinedSoftwareLLC I found the bug. [There's a check to hide nodes if the node is of a base type](https://github.com/godotengine/godot/blob/master/editor/create_dialog.cpp#L129), like Node or Resource. Unfortunately, it does not check if a custom type implements that base type.

My PR intends to fix that.
