### ISSUE TITLE
GoDot potential bug when using GDScript.

### ISSUE THREAD

**Issue by legionnairex3** [godotengine/godot#58256]
### Godot version

3.3

### System information

2015 MacBook Air, Monterrey OS for Mac

### Issue description

 I think there is a bug with Godot. I am following a tutorial by GDQuest on YouTube. its a basic 2d platform game: I create a player, I insert a graphics rect, I set the collision and create two scripts one is the player script and the other is the actor script, all of the code is in the Action script this is the code:

```
extends KinematicBody2D
class_name Actor

func _physics_process(delta: float) -> void:
	var velocity: = Vector2(300,0)
	move_and_slide(velocity)

```
and it works fine. it moves the block right

but when I modify the code to this:

```
extends KinematicBody2D
class_name Actor

var gravity := 3000.0
var velocity := Vector2.ZERO

func _physics_process(delta: float) -> void:
	velocity.y = gravity * delta
	move_and_slide(velocity)

```
the block is suppose to move down but it just stand still as if the scene froze
and worst is that no matter what I do, if I replace it back to the previous code and run it the code does exactly as with this las code. the demo scene just seems to freeze. The block just won't move at all.

this thing has me stomp

Did I mention I am on a 2015 MacBook Air?

### Steps to reproduce

as mentioned above

**Comment by Dan-Gamin** [comment]
This code works, it just moves really slow. This is probably because you multiplied it by delta (A usually very small number). 
To fix this, multiply the `velocity.y` by `100` aswell. That should fix it.

**Comment by novaplusplus** [comment]
You shouldn't be assigning the Y velocity, you should be incrementing it since gravity is an acceleration not a constant speed.
