### ISSUE TITLE
Scene Import; Material merge issue part deux (Godot is doing a simple scene overwrite in some cases again)

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#5825]
**Operating system or device - Godot version:**
Win10 64 bit; ATI 79xx GPU; 24 Gigs RAM; third-gen i7 CPU.
Godot 2.1 Beta (build from July20)

**Issue description** (what happened, and what was expected):
In more complex cases it seems, the fix to allow proper material merging in the alpha builds of Godot 2.1 seems to have come undone. In the specific case of the following .dae file, the engine is back to doing a simple overwrite (meaning materials have to be re-assigned manually again).

**Steps to reproduce:**
Download the following .dae file, import it to Godot, assign new materials for all slots, and re-import (making sure you have the material merge option checked), all of the materials you assigned in Godot should vanish (with the material index values again reverting to Null).

**zip file (contains the raw scene in Collada format)**
[Test_level5.zip](https://github.com/godotengine/godot/files/374375/Test_level5.zip)

**Comment by TheoXD** [comment]
I would advise from changing imported scenes at all. You can create new scene and use imported scene as a root node.

**Comment by reduz** [comment]
But material merging should work.. if it's not working something is wrong

**Comment by TheoXD** [comment]
Works fine on my end, are you sure you did not miss anything while writing the steps?

**Comment by bojidar-bg** [comment]
Since merging and similar things were removed, is this still valid?

**Comment by Ace-Dragon** [comment]
It turned out it was simply a matter of the material merge option not being checked (in the import dialogue, I checked it and the material merge started working again).
