### ISSUE TITLE
Godot 4: Unable to properly minimize window with borderless active

### ISSUE THREAD

**Issue by iagozeero** [godotengine/godot#58257]
### Godot version

v4.0.alpha2.official (79077e6)

### System information

Windows 10

### Issue description

I had ported nicely a project from 3.x to 4.0.alpha1, proceeded to port from 4.0.alpha1 to 4.0.alpha2 and faced a issue that wasn't happening at 4.0.alpha1. Whenever I try to minimize a borderless window through **DisplayServer.window_set_mode(DisplayServer.WINDOW_MODE_MINIMIZED)**, instead of minimizing nicely how it used to on previous builds, the window is completely gone, like it gets closed, and there is no way to restore it unless by code - but through the editor its clear that it is still running. Happens that this only occurs if the Project Settings has borderless setting enabled, which I managed to realize by getting the same results on a minimal project.

Similar to 3.4.stable's #55897 but for Windows, and started happening at 4.0.alpha2.

### Steps to reproduce

Create a new project with all default settings, change Display->Window's Borderless setting to Active on the Project Settings, create a button on the screen, connect the pressed signal to this script:

```
extends Button

func _on_button_pressed():
	DisplayServer.window_set_mode(DisplayServer.WINDOW_MODE_MINIMIZED)
```

Run and press the created button.

### Minimal reproduction project

[MinimizeBorderlessTest.zip](https://github.com/godotengine/godot/files/8092318/MinimizeBorderlessTest.zip)

**Comment by Enlumis** [comment]
Does not seem to be fully fixed, is it? the functionality is working, window is reducing/closing, but it does not seem to play the builtin os animation, if you close a window on windows, you have that scale out animation and if you reduce a window you get that scale/right out animation. but godot seems to close/reduce in a way that it feels like the window disapear. does not feel os friendly. and that only in a borderless scenario

godot 4.1.1

**Comment by sosasees** [comment]
@Enlumis the animations also do not play for me, but i thought this was a limitation of Linux/X11/Openbox

**Comment by Enlumis** [comment]
to be honnest its probably possible to implement your own close/reduce effect, using transparent window then scaling down the full canvas and delay the call to reduce/close. but seems like a hacky solution

**Comment by panoramix360** [comment]
Did you find a workaround for this issue?

I'm trying to make a minimize ingame button to minimize the game, but it does not work with the Borderless active on Macos.
