### ISSUE TITLE
Loading X509Certificate resource does not work with HTML5

### ISSUE THREAD

**Issue by quiyip** [godotengine/godot#58263]
### Godot version

3.4.2 stable

### System information

Windows 10, GLES2

### Issue description

Loading a certificate resource `certificate.crt` like this:
```
func _ready():
	print(load("res://certificate.crt"))
```
Prints out the following when run in the editor:
```
[X509Certificate:1237]
```
However, if the exact same program is run in the browser like this:

<img width="217" alt="image" src="https://user-images.githubusercontent.com/95621115/154595808-71defbb3-7ec2-47f4-971d-4a51e241b542.png">

The console spits out the following errors:

![image](https://user-images.githubusercontent.com/95621115/154595881-815835f4-070b-4e91-8250-e7c5a5ad6fb9.png)

Loading other resources in the browser seems to be fine, so there seems to be something specifically problematic with `X509Certificate` resources (and perhaps `CryptoKey` resources too).

I tried different browsers, turning off adblocker, clearing all cache & import files, with no luck.

Not being able to load certificates is a great annoyance for anyone attempting to use SSL websockets (`wss://`) in a web game.

### Steps to reproduce

1) Create a `X509Certificate` resource.
2) Attempt to load the resource like this:
```
func _ready():
	print(load("res://certificate.crt"))
```
3) Run the program in the browser via HTML5 export.

### Minimal reproduction project

[cert_doesnt_load_in_web.zip](https://github.com/godotengine/godot/files/8093273/cert_doesnt_load_in_web.zip)

**Comment by Calinou** [comment]
This is caused by the Crypto singleton not being available in HTML5: https://github.com/godotengine/godot-proposals/issues/3574

**Comment by quiyip** [comment]
@Calinou I am confused because user @MarshallJDem in [this thread from 2 years ago](https://www.reddit.com/r/godot/comments/et52fp/how_to_integrate_web_sockets_secure_wss_in_godot/) is using `wss://` sockets in an HTML5 game and claims that the problem is due to browsers rejecting self-signed certificates:
> Just like HTTPS, for WSS you need a certificate and a key. However this can’t just be any certificate. It will need to be an official certificate, issued by a Certificate Authority. You have to do this because web browsers will not take unofficial ones seriously, and will consider them insecure (sorry guys no self signed certificates from openSSL).

But in [his HTML5 game](https://github.com/MarshallJDem/SuperCTF), in `NetworkController.gd` he does this:
```GDScript
func join_server():
    connection_attempts += 1
    client = WebSocketClient.new();
    client.verify_ssl = false;
    # TODO make this work on backend
    var url = "ws://" + Globals.serverIP;
    if Globals.useSecure:
        url = "wss://" + Globals.serverIP;
```
`client.verify_ssl = false`, so the client never actually checks authenticity of the server despite being connected via `wss://`?

But the server still sets the private key and cert...
```GDScript
func start_server():
	print("Starting Server");
	reset_game();
	server = WebSocketServer.new();
	if Globals.useSecure:
		server.private_key = load("res://HTTPS_Keys/linux_privkey.key");
		server.ssl_certificate = load("res://HTTPS_Keys/linux_cert.crt");
	server.listen(Globals.port, PoolStringArray(), true);
	get_tree().set_network_peer(server);
```
So how is this possible? I am asking the developers right now.
I also tried this approach, but the client simply fails to connect because of a handshake error.

If anything, how would you implement high-level multiplayer in an HTML5 game that is served over HTTPS?

**Comment by quiyip** [comment]
Okay, in the live version of the code, `client.verify_ssl` is set to `true`.

**Comment by Calinou** [comment]
> Okay, in the live version of the code, client.verify_ssl is set to true.

Do you mean that `verify_ssl` defaults to different values depending on the platform? I think this is expected, as in HTML5, we can't override the browser's behavior to check SSL certificates' validity. Doing so would create a security risk.

**Comment by quiyip** [comment]
> > Okay, in the live version of the code, client.verify_ssl is set to true.
> 
> Do you mean that `verify_ssl` defaults to different values depending on the platform? I think this is expected, as in HTML5, we can't override the browser's behavior to check SSL certificates' validity. Doing so would create a security risk, so browsers don't allow you to do that.

No, it's just old code and in the newer version, according to the person behind the project, that statement was set to true.
