### ISSUE TITLE
DAE Crashes With Every Model

### ISSUE THREAD

**Issue by SusanaHewitt** [godotengine/godot#58267]
### Godot version

4.0 alpha 2

### System information

Windows 10, GeForce GTX 1650

### Issue description

Any model I try to open on the new alpha 2 of 4.0 causes Godot to crash. PLEASE don't abandon the DAE format because GLB is not ready for characters (animations get exported both from 3ds max and Blender as a single animation and a layer with no animations gets created in the process). DAE worked fine out of both, especially for characters. I have no problems with GLTF/GLB for sets.

Also, it should be noted that the alpha 2 is ridiculously slow to open and compile. And saving a script is a nightmare because it saves everything at once and takes minutes doing so (so simply pressing CTRL+S costs me some eight minutes to build my program, four for saving and another four for compiling--because it saves everything all over again).

### Steps to reproduce

Export an animated character out of 3ds max with OpenCollada.

**Comment by Calinou** [comment]
> And saving a script is a nightmare because it saves everything at once and takes minutes doing so (so simply pressing CTRL+S costs me some eight minutes to build my program, four for saving and another four for compiling--because it saves everything all over again).

This is likely because you saved a large binary resource within a `.tscn` scene or `.tres` resource. This binary resource will be serialized as Base64, which is larger and slower compared to saving a binary `.scn` scene or `.res` resource.

**Comment by SusanaHewitt** [comment]
[DAE_BREAKS_IT.zip](https://github.com/godotengine/godot/files/8099004/DAE_BREAKS_IT.zip)

**Comment by akien-mga** [comment]
You can either convert that scene with mesh data to `.scn` (re-save it with a new extension), or save the mesh resource itself as `.res` (using "Save As" in the inspector).

**Comment by SusanaHewitt** [comment]
Thanks for the response. I did as you advised an although my set remains visible in my .scn scene, it is now invisible (with, naturally, visibility turned on) as a child of my game's scene. This has to be a bug, right?
