### ISSUE TITLE
Broken _input in Godot 3.4.3 RC 2

### ISSUE THREAD

**Issue by SkanerSoft** [godotengine/godot#58274]
### Godot version

Godot 3.4.3 RC 2

### System information

iOS 15.2.1 / iPhone SE / OpenGL ES 2.0 Renderer: Apple A9 GPU

### Issue description

Something has changed since version 3.4.3 RC 2 and 3.4.3 RC 1 in event handling in _input.

Control stopped working with touch input.

https://user-images.githubusercontent.com/13809475/154685976-3e346533-5e0b-456b-b0eb-d3381537ff96.mp4

### Steps to reproduce

Create a scrollable element or implement a control via _input and see how it works. I have scrolling elements with problems, and the controls on the iPhone do not work completely.

**Comment by akien-mga** [comment]
Probably caused by #57604, CC @naithar.
