### ISSUE TITLE
GDExtension Demo Project no longer works

### ISSUE THREAD

**Issue by Sauermann** [godotengine/godot#58273]
### Godot version

v4.0.alpha.tempp.custom_build [b4dc2e91e]

### System information

Debian 11, Vulkan

### Issue description

GDExtension Demo project no longer works since b4dc2e91e6143de6722aede77692fdacbfbe840c. (I verified, that it works with the previous commit)

Error message when loading the Demo project is:

```
SCRIPT ERROR: Parse Error: "Example" was not found in the current scope.
          at: GDScript::reload (res://main.gd:9)
SCRIPT ERROR: Parse Error: Identifier "ExampleRef" not declared in the current scope.
          at: GDScript::reload (res://main.gd:13)
ERROR: Method/function failed. Returning: ERR_PARSE_ERROR
   at: reload (modules/gdscript/gdscript.cpp:874)
ERROR: Condition "p_level <= int32_t(level_initialized)" is true.
   at: initialize_library (core/extension/native_extension.cpp:300)
SCRIPT ERROR: Parse Error: "Example" was not found in the current scope.
          at: GDScript::reload (res://main.gd:9)
SCRIPT ERROR: Parse Error: Identifier "ExampleRef" not declared in the current scope.
          at: GDScript::reload (res://main.gd:13)
ERROR: Method/function failed. Returning: ERR_PARSE_ERROR
   at: reload (modules/gdscript/gdscript.cpp:874)
ERROR: Cannot get class 'Example'.
   at: instantiate (core/object/class_db.cpp:510)
WARNING: Node Example of type Example cannot be created. A placeholder will be created instead.
     at: instantiate (scene/resources/packed_scene.cpp:188)
```

### Steps to reproduce

Compile and run Demo project.

### Minimal reproduction project

Demo project of GDExtension

**Comment by akien-mga** [comment]
CC @poiati

**Comment by poiati** [comment]
> @poiati yes, that article describes the Demo project. Here is the repository: https://github.com/godotengine/godot-cpp

I see, I can't get it running using our current master as well. The `Example` node does not match what's expected from the extension definition, it behaves like a plain `Node`, not like a `Control` with the extension.

![image](https://user-images.githubusercontent.com/21452/154779886-8bdf0374-323c-4d3c-a897-5d42258f567c.png)

I don't know what I'm missing.

**Comment by Sauermann** [comment]
@poiati In some random cases, the project file itself gets unintentionally changed (I could not yet identify, what triggers this exactly). Try to reset the *.gd and *.tscn files its original state from the git repository. This workaround helped me to get around this issue in master.

**Comment by poiati** [comment]
Thank you @Sauermann! The files were indeed in a weird state.
