### ISSUE TITLE
`Request for nonexistent project setting` error when opening Godot

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#58294]
### Godot version

3.5.beta.custom_build.afadd3d12

### System information

Ubuntu 21.10 - Nvidia GTX 970, Gnome shell 40.4 X11

### Issue description

When running Godot project, then this error is shown

```
ERROR: Request for nonexistent project setting: logging/file_logging/enable_file_logging.
   at: set_initial_value (core/project_settings.cpp:122)
ERROR: Request for nonexistent project setting: logging/file_logging/enable_file_logging.
   at: set_builtin_order (core/project_settings.cpp:678)
ERROR: Request for nonexistent project setting: logging/file_logging/enable_file_logging.
   at: set_restart_if_changed (core/project_settings.cpp:126)
ERROR: Request for nonexistent project setting: logging/file_logging/enable_file_logging.
   at: set_ignore_value_in_docs (core/project_settings.cpp:136)
```

it is visible in CI - https://github.com/godotengine/godot/runs/5247414724?check_suite_focus=true

### Steps to reproduce

Just run any project

**Comment by akien-mga** [comment]
Probably a regression from https://github.com/godotengine/godot/commit/b343660dac50c753d227d296358fe1aa40da9c90

**Comment by Vauxinox** [comment]
Happens in 3.4.3 (stable) aswell.

**Comment by akien-mga** [comment]
CC @BimDav

**Comment by BimDav** [comment]
I don't get the error, but I can see a problem coming from https://github.com/godotengine/godot/commit/b343660dac50c753d227d296358fe1aa40da9c90. 
There is kind of an asymetry in `has_setting`: if it is a test to check if it is legal to do `get_setting`, then the added checks from https://github.com/godotengine/godot/commit/b343660dac50c753d227d296358fe1aa40da9c90 seem necessary. But it is also used as a check in 
```
	if (!ProjectSettings::get_singleton()->has_setting(p_var)) {
		ProjectSettings::get_singleton()->set(p_var, p_default);
	}
	ret = ProjectSettings::get_singleton()->get(p_var);

	ProjectSettings::get_singleton()->set_initial_value(p_var, p_default);
	ProjectSettings::get_singleton()->set_builtin_order(p_var);
	ProjectSettings::get_singleton()->set_restart_if_changed(p_var, p_restart_if_changed);
	ProjectSettings::get_singleton()->set_ignore_value_in_docs(p_var, p_ignore_value_in_docs);
	```

In that case we want the restrictive version of `has_setting`, so maybe there should be both versions in the API?

I think it can anyway be reversed for now as the case it fixes is rare...

**Comment by akien-mga** [comment]
> ### Steps to reproduce
> 
> Just run any project

That's not sufficient, which is why some of us couldn't reproduce the issue. #58672 has more details, it happens only when a feature override's default value has been changed (e.g. by disabling file logging on PC).
