### ISSUE TITLE
NavigationObstacle3D does not inherit parent process mode

### ISSUE THREAD

**Issue by Barskt** [godotengine/godot#58300]
### Godot version

4.0 dev alpha 2

### System information

Windows 11 ( Vulkan )

### Issue description

Disabling parent node does not disable NavigationObstacle3D.

### Steps to reproduce

1. Create a **player** CharacterBody3D with navigation movement.
2. Create a **npc** CharacterBody3D with a NavigationObstacle3D ( process mode set to inherit )
3. Disable **npc** process mode
4. **player** will still detect and move around the NavigationObstacle3D

**Comment by keptsecret** [comment]
I've been looking into this and it also seems to apply to `CollisionShape3D` as well. It isn't disabled when the parent is disabled.  
I'm not sure what the behavior for this is supposed to be but I'll look into it further anyways.

**Comment by keptsecret** [comment]
Now that I've had the time to look into it a bit more, it seems to have been fixed or I initially misunderstood your issue.  
I tried it again and NavigationObstacle3D and everything else seems to be disabled properly now.

**Comment by smix8** [comment]
@Barskt 

The avoidance happens in the RVO World which is its own blackbox independent from normal processing mode.
Removing the agent temporary from the navigation Map is the way to pause RVO agents.

The RVO World is different from _process() and _physics_process() that are affected by process_mode and pausing.
Even if the `process_mode` would be inherited (creating other problems) the RVO World with the agent is still active cause the NavigationServer is active, just not updated with new agent positions.

Could try to react to processing mode of parent and remove agent from RVO World when paused and place again if unpaused.

I see that current `NavigationObstacle` node(which is technically just a limited NavigationAgent) has a lot of existing utlity functions of agents not available or exposed for scripting so this should be fixed to deal with such situations.

If you want to disable an agent / obstacle avoidance temporary without deleting the agent you can with the NavigationServer API directly. This requires the agent RID which seem to be unoptainable for NavigationObstacles rightnow which needs to be fixed.

- remove the agent / obstacle from the navigation map and therefor RVO World with `NavigationServer.agent_set_map()` function.
- remove the agent avoidance callback with `NavigationServer.agent_set_callback()` function.
- disconnect the `velocity_computed` signal connection that returns avoidance `safe_velocity` or have a pause toggle inside to not react to it while in pause process_mode.
