### ISSUE TITLE
Godot 4: max_slides and motion_velocity are missing from CharacterBody3D's property selector list in Visual Script

### ISSUE THREAD

**Issue by kreaninw** [godotengine/godot#58305]
### Godot version

v4.0.alpha2.official [79077e6c1]

### System information

Windows 11, Vulkan Clustered, Intel UHD Graphics 620 v30.0.101.1340

### Issue description

`max_slides` and `motion_velocity` are missing from CharacterBody3D's properties list in Visual Script, as shown in the screenshot below:

![Screenshot 2022-02-19 001620](https://user-images.githubusercontent.com/1403194/154784566-60f8ca6f-c8b4-4898-bfae-469ffff3fb70.jpg)

The full list of available properties from CharacterBody3D can be seen in [the official docs](https://docs.godotengine.org/en/latest/classes/class_characterbody3d.html?highlight=character#properties).

I expect all of the properties from CharacterBody3D to be presented in Visual Script.

### Steps to reproduce

1. Add a CharacterBody3D node and attach Visual Script.
2. Add a get node in Visual Script.
3. Seach for `max_slides` and `motion_velocity` in the properties list. You won't find them.

**Comment by megalobyte** [comment]
Similar issue to #58228. See my comment for my thoughts: https://github.com/godotengine/godot/issues/58228#issuecomment-1044105690
I suspect a lot of VisualScript nodes will have this problem

**Comment by KoBeWi** [comment]
VisualScript was removed in Godot 4.0, so closing.
