### ISSUE TITLE
Godot 4: Rotation property tooltips claims to be in radians while actually being in degrees (due to automatic editor conversion)

### ISSUE THREAD

**Issue by doonv** [godotengine/godot#58316]
### Godot version

v4.0-alpha2

### System information

Windows 10 64-bit, GPU: NVIDIA Geforce GTX 1650 Ti, CPU: AMD Ryzen 7 4800H

### Issue description

The `rotation` property claims to be in radians while actually being in degrees. Here is an image of a object being rotated 45 degrees while the tool-tip says it's in radians.
![image](https://user-images.githubusercontent.com/58695417/154803231-76b99369-4956-430c-8465-899ae1381907.png)

### Steps to reproduce

1. Rotate any node that inherits Node2D.
2. The `Rotate` property is in degrees not radians as the tool-tip implies.

**Comment by jmb462** [comment]
``rotate`` is in radians

Seems that the inspector angle editor give us a view in degrees.
Previously, there was a ``rotation_degrees`` property but there is just ``rotation`` now.

That leads to something misleading which you set a degree value in inspector and store a radian value in property.

**Comment by Calinou** [comment]
I wonder if the property range hints can be read by the class reference generation. This would also be useful to mention the suggested minimum, maximum and step values in the class reference.

**Comment by megalobyte** [comment]
This also applies to Node3D rotation

**Comment by RobertSzaszak** [comment]
I got this issue as well. I am unable to clamp the up and down rotation of the camera attached to the player.

```
extends CharacterBody3D

@export var _mouse_sensitivity := 0.0005

func _ready() -> void:
	Input.mouse_mode = Input.MOUSE_MODE_CAPTURED

func _input(event) -> void:
	var mouse_motion = event as InputEventMouseMotion
	if mouse_motion:
		rotation.y -= mouse_motion.relative.x * _mouse_sensitivity
		
		var current_tilt: float = $Camera3D.rotation.x
		current_tilt -= mouse_motion.relative.y * _mouse_sensitivity
		
		$Camera3D.rotation.x = clamp(current_tilt, -90, 90)
```
