### ISSUE TITLE
.scn 3D scene invisible in the editor, but visible in the running project

### ISSUE THREAD

**Issue by SusanaHewitt** [godotengine/godot#58326]
### Godot version

4.0 alpha 2

### System information

Windows 10, GeForce GTX 1650

### Issue description

I have a large set originally saved as a .tscn, and added as a sub node of my game scene. When I converted it to .scn, it became invisible in the editor, even as it remains visible in the compiled game.

### Steps to reproduce

Import a .glb, save it to .tscn, then resave it to .scn. Add that to a game scene.

**Comment by Calinou** [comment]
@SusanaHewitt Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by SusanaHewitt** [comment]
> @SusanaHewitt Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.
> 
> PS: Godot projects are not _compiled_ when you run the project. GDScript is an interpreted language, and it does not need to be compiled to be run.

Noted, thanks (although I could have been using C#). I'll make a short project soon.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
