### ISSUE TITLE
Vulkan: Directional light and shadow layer culling is not rendered correctly

### ISSUE THREAD

**Issue by pracedru** [godotengine/godot#58322]
### Godot version

v4.0.alpha.custom_build [0217d44df]

### System information

Ubuntu 20.04, Vulkan, Nvidia 1060 6GB (510.47.03)

### Issue description

As shown in the sample project the directional light is rendered on Camera3D1 despite being only on layer2.
The shadow from the cube is rendered on Camera3D2 despite only being only on layer1.
The omnilight is culled correctly.

### Steps to reproduce

Open the project and view the output from Camera3D1 and Camera3D2.

### Minimal reproduction project

[Godot4DLLT.tar.gz](https://github.com/godotengine/godot/files/8102586/Godot4DLLT.tar.gz)

*Bugsquad edit (keywords for easier searching): cull mask, cullmask, visibility layer*

**Comment by pracedru** [comment]
As shown on my computer
![image](https://user-images.githubusercontent.com/15041324/154809605-93e97063-6794-471f-95db-e23b8eaa603d.png)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/54613 (which I've renamed to track `3.x` only).

**Comment by Calinou** [comment]
This was fixed in `3.x` by https://github.com/godotengine/godot/pull/61841. A similar fix can be applied to 4.0 according to https://github.com/godotengine/godot/pull/61841#pullrequestreview-1117502238.

cc @markusneg
