### ISSUE TITLE
GLTF import on html5

### ISSUE THREAD

**Issue by ElhamAryanpur** [godotengine/godot#58325]
### Godot version

3.4.2

### System information

Manjaro-latest, i5-4210, geforce 920m

### Issue description

I have been following past issues, proposals, and details on enabling the PackedSceneGLTF for importing gltf on runtime. It works on the editor and a custom export template on native platforms, but not on web. available plugins/modules also don't support web. I have tried both compiling and using prebuilt version through gdnative export of HTML5 with no luck of it working. I also tried custom export template with `module_gltf=yes` flag with no luck there either (taken from a repo's instruction).

I was wondering if I'm missing something or is the web a problem as web editor does work fine.

### Steps to reproduce

1) get the source of godot
2) compile with `scons platform=javascript target=release debug_symbols=no tools=no module_gltf=yes -j8 use_lto=yes use_llvm=yes module_arkit_enabled=no module_mobile_vr_enabled=no module_csg_enabled=no`
3) open a new project, add some gltf files and import them through:
```gdscript
func _ready():
	var path = "res://assets/HUB.glb"
	var gltf = PackedSceneGLTF.new()
	var model = gltf.import_gltf_scene(path)
        add_child(model)
```
4) export the project with the custom built export template
5) run a local server and open it in the browser

**Comment by ElhamAryanpur** [comment]
@fire

**Comment by fire** [comment]
I remember it was slow on the editor build. 

* https://github.com/SIsilicon/Godot-Web-File-Manager
* https://editor.godotengine.org/releases/latest/

**Comment by Calinou** [comment]
Please do not open issues for discussions you've already opened: https://github.com/godotengine/godot-proposals/discussions/4038

Export templates do not feature glTF import functionality (or import functionality in general), regardless of the platform. Editor binaries however do feature glTF import functionality, also regardless of the platform.

It's not possible to backport run-time glTF loading to Godot 3.x, as it relies on backwards-incompatible changes.
