### ISSUE TITLE
GDScript 2.0: "Treat Warnings As Errors" project setting has no effect when enabled

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#58330]
### Godot version

4.0.alpha (6a51999b7)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 495.46)

### Issue description

Enabling **Treat Warnings As Errors** in the Project Settings has no effect. Warnings are still emitted as warnings after the setting is enabled. This only affects the new GDScript implementation, as doing the same works fine in Godot 3.4.2.

This is also a blocker to implementing https://github.com/godotengine/godot-proposals/issues/3531.

### Steps to reproduce

- Enable **Treat Warnings As Errors** in the Project Settings.
- Create a Node2D and attach the following script to it:
```gdscript
extends Node2D

func i_accept_ints_only(_i: int):
	pass

func _ready():
	i_accept_ints_only(12.345)
```
- Save the scene and run the project.
- Notice that only a warning is emitted, and project execution is not paused by the error.

### Minimal reproduction project

[test_gdscript_warnings_as_errors.zip](https://github.com/godotengine/godot/files/8103108/test_gdscript_warnings_as_errors.zip)

**Comment by jmb462** [comment]
It seems that it's not implemented any more in gdscript parser.
