### ISSUE TITLE
hiccup when using preload for msdf and AA enabled fonts

### ISSUE THREAD

**Issue by girng** [godotengine/godot#58341]
### Godot version

v4.0.alpha.custom_build (Feb 11th)

### System information

W10, RX 480, Vulkan

### Issue description

I've noticed some hiccups when adding some scenes with basic text. I isolated it and found enabling `msdf` for the font will trigger it. I've attached an example below.  

I'm not sure if this has been reported, but there is also a small hiccup when `msdf` or `Antialiasing` is not enabled. 

I'm from Godot 2.1.6, and when using dynamic fonts with preload, there was never a hiccup. This makes me believe this is not intended behavior. Thanks for reading

### Steps to reproduce

 - Run the example project, and press the `esc` key 

### Minimal reproduction project

[godot_msdf_bug.zip](https://github.com/godotengine/godot/files/8103475/godot_msdf_bug.zip)

**Comment by girng** [comment]
I found a way to stop the hiccup:
 - Click `Advanced..` on the font's Import tab
 - Go to Size and variations, add a config
 - Go to Glyphs from the character map, and double click Basic Latin
 - Then click Reimport

I'm not sure if this is a bug anymore.  Maybe the Basic Latin glyph could be added somehow so others don't run into this.

**Comment by bruvzg** [comment]
> I've noticed some hiccups when adding some scenes with basic text. I isolated it and found enabling msdf for the font will trigger it.

This is expected, MSDF rendering is too slow to do it on the fly, that's exactly why there's character map to select ranges to pre-render.

> I'm from Godot 2.1.6, and when using dynamic fonts with preload, there was never a hiccup.

[MSDF](https://github.com/Chlumsky/msdfgen/files/3050967/thesis.pdf) is a new node added in the 4.0, there's no equivalent in 3.x or 2.x.

> Maybe the Basic Latin glyph could be added somehow so others don't run into this.

Not sure if it's a good idea, not all fonts have Latin character, and it's not always necessary to have any.

But documentation definitely should be updated to mention it.

**Comment by girng** [comment]
@bruvzg gotchu. Maybe a default config, and char map range could be pre-rendered and created when importing the font. 

Except, as you said it's dependent on that user's font. 

![](https://i.gyazo.com/7ab226b7e63381a7eca631d48d08dea1.png)

There is also this warning, which is good. Maybe it's just part of switching to Godot 4. At the same time, I am a firm believer in `preload` being smooth no matter what

**Comment by Calinou** [comment]
[Font prerendering is now documented](https://docs.godotengine.org/en/latest/tutorials/ui/gui_using_fonts.html#doc-using-fonts-font-prerendering), closing.
