### ISSUE TITLE
How to make an obstacle which moves on its own with a collision box?

### ISSUE THREAD

**Issue by RockZombie4** [godotengine/godot#58345]
### Godot version

v3.4.2.stable.mono.official [45eaa2daf]

### System information

Linux Mint 20.1 Intel CPU 4gb RAM, 500gb storage.

### Issue description

I have recently created a player with a collision box which can move forward and backward, left and right, and can dash. I want to create an obstacle for the player which can move by itself and if the player's collision box collides with the obstacle's collision box, the game currently prints: "You lost!" I tried various amounts of code to make the obstacle move, but none of them worked. I am also not so sure if the collision box works in either the player or the obstacle. This is what I have so far:
![godot](https://user-images.githubusercontent.com/100057184/154833464-95bb10f9-c782-4cf5-8a33-e1ece4892b2d.png)
![gdscript](https://user-images.githubusercontent.com/100057184/154833465-8535c8ac-7cda-40ed-8372-ed95bcf710bb.png)
Can someone please help me?

### Steps to reproduce

`extends KinematicBody2D
export (int) var speed = 200

var velocity = Vector2(250, 250)

func get_input():
	look_at(get_global_mouse_position())
	velocity = Vector2()
	if Input.is_action_pressed("down"):
		velocity = Vector2(-speed, 0).rotated(rotation)
	if Input.is_action_pressed("up"):
		velocity = Vector2(speed, 0).rotated(rotation)
	if Input.is_action_pressed("dash"):
		velocity = Vector2(700, 0).rotated(rotation)
	if Input.is_action_pressed("dash2"):
		velocity = Vector2(-700, 0).rotated(rotation)

func _physics_process(delta):
	get_input()
	velocity = move_and_slide(velocity)
`

**Comment by akien-mga** [comment]
This issue tracker is for *bug reports* exclusively. Please use one of the other community platforms for support: https://godotengine.org/community/
