### ISSUE TITLE
Windows 10 crash on exit

### ISSUE THREAD

**Issue by habamax** [godotengine/godot#5834]
**Operating system or device - Godot version:**
windows 10, godot 2.1 beta

**Issue description** (what happened, and what was expected):
Close godot engine -- crash of godotengine

**Steps to reproduce:**
1. Create and open new project
2. Close godotengine

![image](https://cloud.githubusercontent.com/assets/234774/17013524/cfd87920-4f27-11e6-9331-0cdaccff5467.png)

**Comment by akien-mga** [comment]
Thanks for the report, this has been fixed already (see #5664) and we'll soon push a new beta including this fix.
