### ISSUE TITLE
Typo in Dutch translation

### ISSUE THREAD

**Issue by Sidn3y** [godotengine/godot#58347]
### Godot version

v3.4.2.stable.official [45eaa2daf]

### System information

MacOS

### Issue description

Typo in dutch translation. Animation window. Mouse over the plus sigh says: Niewe animatie. This should be: Nieuwe animatie.
<img width="205" alt="Schermafbeelding 2022-02-20 om 09 59 32" src="https://user-images.githubusercontent.com/31223303/154835597-02cc475a-4ec9-4ff0-958c-c2acf02f0292.png">

### Steps to reproduce

-

**Comment by akien-mga** [comment]
Thanks, fixed in https://hosted.weblate.org/translate/godot-engine/godot/nl/?checksum=5b42097771a18652.

You can fix translations on Weblate yourself if you want, see https://docs.godotengine.org/en/latest/community/contributing/editor_and_docs_localization.html
