### ISSUE TITLE
ViewportTexture is broken when using external textures

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#58353]
### Godot version

3.x (3e0f380c90d11f5d317e9ab7081d6cc41803c2ca)

### System information

Any

### Issue description

When using viewport textures in combination with an XR interface, if that XR interface is using an external texture implementation Viewport textures are broken.

This is because the XR interface will supply the renderer with an alternative render target to render too. `VisualServerViewport::viewport_get_texture` in this case will return the texture RID for the external texture instead of the internal one.

Problem is, we're cashing the internal RID when a viewport is created. To be exact, the correct RID is not available until at least 1 frame is rendered.

As a result the output is blank.

To solve this we probably need to do two things:
1) create the external RID early on but with blank data instead of creating it when it's needed
2) make sure that when our arvr mode changes, we also update our cached RID and update our default proxy

### Steps to reproduce

Use the OpenXR plugin for Godot 3 and use a separated viewport as the ARVR viewport. Then use a texture rect to output the viewports contents to screen. This will result in a blank output as the wrong image is being read from.

### Minimal reproduction project

https://github.com/BastiaanOlij/godot_openxr/tree/preview_workaround

**Comment by akien-mga** [comment]
Fixed by #58357.
