### ISSUE TITLE
Script editor code folding color is influenced by main theme base color

### ISSUE THREAD

**Issue by yikescloud** [godotengine/godot#58379]
### Godot version

3.4.2 stable

### System information

Windows 10

### Issue description

Code folding color is influenced by main theme color. It's hard to see difference when change the code folding color. But when you change the main theme color, the arrow color changes.
Use a  main dark color
![image](https://user-images.githubusercontent.com/9168814/154886338-1f11cafc-25cf-4eef-afb1-18c74906767b.png)
![image](https://user-images.githubusercontent.com/9168814/154886373-4f543af6-668c-4316-a1de-6f8d1f61edb9.png)
Use a main light color
![image](https://user-images.githubusercontent.com/9168814/154886423-33ef885b-8d8c-4bf7-84a6-2b8bf03f761f.png)
![image](https://user-images.githubusercontent.com/9168814/154886440-340246bb-c2aa-44a9-8f68-ba6336c6bc68.png)
Change Code Folding Color doesn't do anything
![image](https://user-images.githubusercontent.com/9168814/154886567-e3b69565-a1e1-4006-ac80-7b386ea9c5be.png)
![image](https://user-images.githubusercontent.com/9168814/154886605-2559c239-9218-4033-9ac5-ddb61806e779.png)

### Steps to reproduce

Use a light theme and a dark theme code editor theme. Change code folding color settings in editor settings.

**Comment by PhoenixFlame101** [comment]
Tested 45eaa2daf1e3d2571a9f31a3421911262ec82f51 (3.4.2-stable) on Ubuntu 21.10

I'm able to reproduce the issue if I change the `Text Editor -> Theme -> Color Theme` setting from 'Adaptive' to 'Custom'. This prevents the code editor from changing its background to match the rest of the application.

The color actually does change very slightly, but the color itself is incorrect.

![image](https://user-images.githubusercontent.com/51199011/154923351-ddeee16d-bace-49c4-aff3-105d0369465e.png)
![image](https://user-images.githubusercontent.com/51199011/154923383-0c2ba4d7-22e7-439e-b01f-a7ed87e3797d.png)

I'll try fixing this if I get the go ahead from one of the maintainers.

**Comment by Calinou** [comment]
> I'll try fixing this if I get the go ahead from one of the maintainers.

Sure, feel free to use a fixed color instead. Make sure it still adapts to the automatic light/dark theme switch in the Adaptive theme (called Default in the `master` branch).
