### ISSUE TITLE
Godot 4 build with doubles fails with llvm on linking with libatomic.a

### ISSUE THREAD

**Issue by croxis** [godotengine/godot#58374]
### Godot version

4.0 dev (b0ba946)

### System information

Arch Linux

### Issue description

```
[ 96%] Compiling core/error/error_macros.cpp ...
[100%] progress_finish(["progress_finish"], [])
[100%] Linking Static Library core/libcore.linuxbsd.double.opt.tools.64.llvm.a ...
Ranlib Library core/libcore.linuxbsd.double.opt.tools.64.llvm.a ...
[100%] Linking Program bin/godot.linuxbsd.double.opt.tools.64.llvm ...
ld.lld: error: unable to find library -l:libatomic.a
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [bin/godot.linuxbsd.double.opt.tools.64.llvm] Error 1
scons: building terminated because of errors.
[Time elapsed: 00:09:12.617]
```

### Steps to reproduce

scons -j12 warnings=all werror=yes platform=linuxbsd tools=yes tests=no production=yes float=64 target=release_debug use_llvm=yes use_lld=yes

**Comment by Calinou** [comment]
This is most likely because you're lacking the static libstdc++ dependency. As a workaround, you can use `use_static_cpp=no` SCons option, but your compiled binary will no longer be distributable with the expectation that it'll work on other people's systems.

**Comment by akien-mga** [comment]
Indeed, Arch doesn't provide `libatomic.a` for some obscure reason. So you should either use GCC, or disable `use_static_cpp`.
