### ISSUE TITLE
Godot 4: TileEditor - Selecting a tile in the property painter will overwrite its value

### ISSUE THREAD

**Issue by creadicted** [godotengine/godot#58384]
### Godot version

4.0.alpha2

### System information

Windows 10

### Issue description

In the paint properties mode, when painting physics or navigation properties. The current polygon I edit is not updated until I click on the tile again. What leads to a problem that every time i want to select a tile, its property is overwritten by the previous one.

I found also a lot of other bugs. Is there a way to report them all at once?

### Steps to reproduce

![godot-4-bug-tile-editor](https://user-images.githubusercontent.com/1899013/154916724-b68a5b8c-3efc-48ca-83eb-2624c9f1feab.gif)

1. Create a tile map
2. Add an image to the tiles
3. Add a physics layer 
4. Edit the property. 
5. Select another tile

**Comment by groud** [comment]
This is expected behavior. You edit the value on the left, then paint it on the atlas. There's no notion of "selected tile" here, for that you should use the select mode instead, and use the polygon editor there.

**Comment by KoBeWi** [comment]
I think being able to "select" tile without editing it would be useful. When you go to select mode, you can't easily copy the value to other tiles. It feels like artificial limitation that you can't both select and paint tiles. But I guess this should go through a proposal (which I was going to submit at some point actually).

**Comment by iMaCHVFX** [comment]
yeah this is a completely unnecessary limitation, having to redo the physics layer for several identical tilesets with different texture is a massive time waste

**Comment by KoBeWi** [comment]
In Paint mode there is actually a picker tool that allows you to click a tile without modifying it. idk if I haven't noticed it when I wrote my previous comment, but it makes it a non-issue.

@iMaCHVFX Sounds like in your case you want either a way to copy the polygons between atlases or a way to duplicate an atlas and swap a texture. There is a workaround for the latter - you can achieve it by manually modifying the TileSet resource file. Though it's error-prone, I think we could add this functionality to the editor.
