### ISSUE TITLE
CanvasItem shows despite not visible in tree

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#58388]
### Godot version

3.x 4e44a151767b4ec512550a073eb24368c1b964bb / 4.0 adf10902c94cf259ce2cbd56d2835a70ee0d86b1

### System information

W10

### Issue description

When you have any CanvasItem directly under CanvasLayer, make the layer invisible and then toggle that item's visibility twice, it will appear and also makes the whole branch appear:
![](https://camo.githubusercontent.com/237b4b646553186e1ed6faa05d2125b7a86a4c312688365b5ae92f3d67980821/68747470733a2f2f636861742e676f646f74656e67696e652e6f72672f66696c652d75706c6f61642f53437a41746465535245646f6e644444712f676f646f742e77696e646f77732e746f6f6c732e36345f51666c50754b7a3168532e676966)
What's weird about this is that `_update_callback()` is not called and the visibility isn't propagated in any way, so this is something related to CanvasLayers and directly to RenderingServer. It doesn't happen for nodes under other CanvasItem.

EDIT:
I didn't really investigate it, but the fact that the bug happens with CanvasLayer and not with CanvasItem suggests that somewhere in RenderingServer, or at whatever part of code is responsible for drawing, there is a condition that checks whether parent CanvasItem is visible and for any other class it just assumes `true`. So this code would need to handle also CanvasLayers.

### Steps to reproduce

1. Add CanvasLayer
2. Add Sprite2D under the layer
3. Make layer invisible
4. Toggle Sprite2D visibility twice

**Comment by techiepriyansh** [comment]
Is this not intended? I suspect there might be a use case where you might want to make all the nodes of a canvas layer invisible and then just make some of its nodes visible by double toggling them.

**Comment by KoBeWi** [comment]
No, it's not intended. If something is hidden, it should be hidden. Also the "visible" state is glitchy, as the node might disappear on another refresh.
