### ISSUE TITLE
Incorrect hint text when zooming in editor

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#58398]
### Godot version

v3.4.3.rc1.official [894b6d504]

### System information

Mac OSX (Intel 2019)

### Issue description

When zooming out as far as possible in the 3D viewport a warning is displayed:

<img width="570" alt="Screenshot 2022-02-21 at 21 37 09" src="https://user-images.githubusercontent.com/100964/155010713-3a956551-3e83-45df-a625-7d22a9a6ba99.png">

However there is now no `View` menu in the toolbar, nor in the Editor settings.

I tried to change the camera settings here, but to no effect:

<img width="713" alt="Screenshot 2022-02-21 at 21 37 54" src="https://user-images.githubusercontent.com/100964/155010795-0c8dcb5f-d7a2-442d-8228-97df920dde9a.png">
 

### Steps to reproduce

Zoom out as far as possible

**Comment by jmb462** [comment]
![image](https://user-images.githubusercontent.com/3649998/155013621-1f9e415e-c246-4ae7-a3e4-58708a9538b3.png)
![image](https://user-images.githubusercontent.com/3649998/155013658-d985c2e7-72ac-4e59-8066-fb64d44c4a0e.png)


Changing the view z-far changes the distance where the grid is visible.

**Comment by tavurth** [comment]
Thank you! I didn't see that portion :)
