### ISSUE TITLE
No normals on glb/glTF mesh import with blend shapes

### ISSUE THREAD

**Issue by dandy-step** [godotengine/godot#58390]
### Godot version

v3.4.3.rc2.mono.official [0ea54d07f]

### System information

Windows 7 x64, GLES3 backend

### Issue description

Importing a glb file generated in Blender (checked with 2.93 and 3.0), if exported with shape keys, seems to render a mesh with no (or invalid) normals in Godot. Importing the glb back into Blender or an online gltf viewer shows the mesh with normals as expected, so it seems like the data is exported correctly and it might be an issue with the Godot importer.
Exporting the mesh by disabling shape key export in Blender renders as expected in Godot.

![2022-02-21 13_10_28](https://user-images.githubusercontent.com/29162970/154962548-6d5d9b1b-bef5-4cb7-aa1d-593ca60f3cbd.png)

![2022-02-21 13_10_25](https://user-images.githubusercontent.com/29162970/154962540-c1c90249-2b50-4b8f-bcf1-756b50bc07fa.png)

### Steps to reproduce

Import the attached project and open one of the included scenes

### Minimal reproduction project

[shapekey.zip](https://github.com/godotengine/godot/files/8109601/shapekey.zip)

**Comment by fire** [comment]
Similiar issues in master. https://github.com/godotengine/godot/issues/58093

**Comment by Cheeseness** [comment]
I believe I was hit with this as well, and it appears to be a duplicate of #58592. PR #59159 which is in 4.3.4 RC2 addressed it for me.

**Comment by tinmanjuggernaut** [comment]
Since this has been resolved, you can close the issue yourself.

**Comment by Cheeseness** [comment]
> Since this has been resolved, you can close the issue yourself.

If I take the time to confirm that what I've experienced is this issue, I'll do just that!

**Comment by dandy-step** [comment]
Confirmed fixed in v3.4.4.rc2.mono.official [69e9e8f87] through the reproduction project. Thank you for the support!

![2022-03-19 11_05_20](https://user-images.githubusercontent.com/29162970/159118553-38cc11f7-4500-40da-a737-986f99dfbb74.png)
