### ISSUE TITLE
Docs for PckPacker flush verbose param are misleading

### ISSUE THREAD

**Issue by SylvanSign** [godotengine/godot#58392]
### Godot version

3.4 stable, but probably All?

### System information

N/A

### Issue description

For this method
```gdscript
Error flush ( bool verbose=false )
```
the docs say
>...If verbose is true, a list of files added will be printed to the console for easier debugging.

which is misleading given the implementation seemingly only prints out messages every 100 files:
https://github.com/godotengine/godot/blob/c55aa03c436fb40f9a42128397b69872d85fb237/core/io/pck_packer.cpp#L257-L264

So for small pck packing with < 100 added files, this will print nothing...

### Steps to reproduce

mostly following the docs in `PckPacker` to produce a minimal example:
```gdscript
extends Node

func _ready() -> void:
	var small_packer = PCKPacker.new()
	assert(OK == small_packer.pck_start("small.pck"))
	assert(OK == small_packer.add_file("res://test.png", "icon.png"))
	assert(OK == small_packer.flush(true))
	# check output and see that nothing is printed
```

**Comment by Calinou** [comment]
I'd say the "every 100 files" check should be removed, and a line should be printed for every exported file instead.
