### ISSUE TITLE
Unexpected behaviour using `control + backspace` in TextEdit

### ISSUE THREAD

**Issue by marcgpuig** [godotengine/godot#58406]
### Godot version

256069eaf00be2340259f896695014d92b1e22ed

### System information

Windows 10

### Issue description

In any TextEdit (and by extension the GD script editor) `control + backspace` doesn't do anything when the cursor is at the very beginning (leftmost or column 0) of the line you are working on.

### Steps to reproduce

1. In the GDScript Editor (or any other TextEdit based editor)
2. Write anything and place the cursor on any line that is not the first line of the text
3. Repeatedly press `control + backspace` 
4. The cursor will get stuck at the beginning of the line without jumping to the previous one

**Comment by marcgpuig** [comment]
I can take this issue myself.

**Comment by Calinou** [comment]
> I can take this issue myself.

Sure, feel free to open a pull request for this :slightly_smiling_face:

**Comment by marcgpuig** [comment]
@Calinou I've just seen that in the current `master` the `control + backspace` delete adjacent spaces one by one and it should delete them all at once. Should I fill another issue or we can track it here too?

Just checked and in `3.4.2` everything works as expected.

**Comment by Calinou** [comment]
> @Calinou I've just seen that in the current master the control + backspace delete adjacent spaces one by one and it should delete them all at once. Should I fill another issue or we can track it here too?

I don't think you need to open a separate issue (or PR) for that. You can batch both fixes together here.
