### ISSUE TITLE
Godot 4: adding Visual Script's Vector3 rotated() and normalized() nodes will crash the engine

### ISSUE THREAD

**Issue by kreaninw** [godotengine/godot#58402]
### Godot version

v4.0.alpha2.official [79077e6c1]

### System information

Windows 11, Vulkan Clustered, Intel UHD Graphics 620 v30.0.101.1340

### Issue description

Adding Visual Script's Vector3 `rotated()` node will crash the engine, as shown in the screen recording below:

https://user-images.githubusercontent.com/1403194/155025777-085ce922-d122-4628-acda-a7832787b5bf.mp4

This is a regression from Godot 3.4. In Godot 3.4, adding Visual Script's Vector3 `rotated()` node will not crash the engine, as shown in the screen recording below:

https://user-images.githubusercontent.com/1403194/155026106-3d06adb7-7322-4fab-ae63-711fb9721322.mp4

I expect to get the node and the engine doesn't crash.

Note: 

- I just notice that not only Vector 3's rotated() node that causes the engine to crash. Vector 3's normalized() node will cause the engine to crash too. See my comment below.
- I don't know whether this issue will be fixed by the merged PR #58327.

### Steps to reproduce

1. Adding Visual Script's Vector3 `rotated()` node.
2. The engine will crash.

**Comment by kreaninw** [comment]
I just notice that not only Vector 3's `rotated()` node that causes the engine to crash. Vector 3's `normalized()` node will cause the engine to crash too, as shown in the screen recording below:

https://user-images.githubusercontent.com/1403194/155028525-71f8c613-907a-4052-9377-c0584450a14c.mp4

I believe that it's not just these 2 nodes that will cause the engine to crash.

Note: these 2 nodes are working fine in Godot 3.4.

**Comment by megalobyte** [comment]
> I don't know whether this issue will be fixed by the merged PR https://github.com/godotengine/godot/pull/58327. 

I just tested this, and it does appear that my PR fixed this? Which is a bit awkward for me, because I [thought](https://github.com/godotengine/godot/pull/58327#issuecomment-1046103149) I was only fixing the one `call` node, but it does make sense that my PR would fix it. Any `VisualScriptFunctionCall` would have caused the same crash

**Comment by akien-mga** [comment]
Fixed by #58327.
