### ISSUE TITLE
Axis Handle Gizmo letters at wrong positions when editor display scale is below 100%.

### ISSUE THREAD

**Issue by PrecisionRender** [godotengine/godot#58408]
### Godot version

v4.0.alpha2.official [79077e6c1]

### System information

Windows 11, Vulkan, Nvidia GeForce RTX 2060 Max-Q

### Issue description

When the display scale is set below 100%, the letters on the Axis Handle Gizmo offset themselves away from the center of their respective handles. This only seems to happen when the display scale is smaller than 100, not at 100 or larger. Here is an image:
![image](https://user-images.githubusercontent.com/89754713/155034544-ff5abf2b-d721-443d-a525-313be0dcbead.png)
Note that I have a 16:9 1920x1080p display, so my screen is not high-DPI.

### Steps to reproduce

1. Open Godot Editor
2. Create a Node3D scene
3. Go to Editor > Editor Settings
4. Set Editor > Display Scale to 75% or custom and set Custom Display Scale below 1

**Comment by Calinou** [comment]
I can't confirm this on `3.x` 6073277cc (75% editor scale):

![image](https://user-images.githubusercontent.com/180032/158691489-c5f6d9eb-4935-4c7a-813c-f770336b89ac.png)

This issue only affects the `master` branch.
