### ISSUE TITLE
Godot 4: get_action_strength() node's str action text box in Visual Script doesn't accept text input

### ISSUE THREAD

**Issue by kreaninw** [godotengine/godot#58401]
### Godot version

v4.0.alpha2.official [79077e6c1]

### System information

Windows 11, Vulkan Clustered, Intel UHD Graphics 620 v30.0.101.1340

### Issue description

`get_action_strength()` node's **str action** text box doesn't accept text input, as shown in the screen recording below:

https://user-images.githubusercontent.com/1403194/155020221-23c232fb-a2d6-458a-8292-ff5d82015282.mp4

The `get_action_strength()` function belongs to the **InputEvent** class.

This is a regression from Godot 3.4. In Godot 3.4, the node accepts text input as shown in the screen recording below:

https://user-images.githubusercontent.com/1403194/155020896-3c42f4d5-6043-443a-9441-b53322094f33.mp4

### Steps to reproduce

1. Add a Visual Script's function call node.
2. Change Call Mode to Instance.
3. Change Base Type to InputEventAction.
4. Due to [issue #58069](https://github.com/godotengine/godot/issues/58069), don't forget to empty the Base Script box.
5. Search for the `get_action_strength()` function.
6. You will get the the `get_action_strength()` node. But you won't be able to type any text in the str action text box.

**Comment by Gallilus** [comment]
I have fixed the multiline editor for the CustomPropertyEditor two times now.
https://github.com/godotengine/godot/pull/52219
https://github.com/godotengine/godot/pull/52218

maybe more effort may be put in streamlining CustomPropertyEditor and Inspector's EditorProperty like https://github.com/godotengine/godot-proposals/issues/3139

(CustomPropertyEditor is the popup you see)

**Comment by KoBeWi** [comment]
VisualScript was removed in Godot 4.0, so closing.
