### ISSUE TITLE
Tileset paint properties: picker disappearing

### ISSUE THREAD

**Issue by coma94** [godotengine/godot#58407]
### Godot version

4.0 alpha (5d5f80b52)

### System information

Majaro KDE, Intel HD grpahics

### Issue description

When editing properties of a tileset, if I go in "select tiles" mode, then "paint properties" mode, the picker disappear. It comes back if I paint any tile with the currently set property (but usually I do not want any tile to be painted..). And then it stays. But if I come back to "select tiles" mode it disappear again.

Before painting, just leaving "select tiles" mode:
![before_pating](https://user-images.githubusercontent.com/627451/155033037-a9c07a0f-3760-401c-ab46-a5ea3581892b.png)

After painting any tile, the picker is back:
![after_painting](https://user-images.githubusercontent.com/627451/155033034-df2dabce-30d1-455c-a482-0011e803752a.png)

### Steps to reproduce

Edit a tileset, go in "select tiles" mode then "paint properties" mode.

**Comment by KoBeWi** [comment]
Can't reproduce in 943b509
![godot windows tools 64_oTu5UPk0sH](https://user-images.githubusercontent.com/2223172/167322980-7925df55-728d-46eb-9943-dc8fe5b6d756.gif)
