### ISSUE TITLE
Container sizing values misbehave when multiple controls inside a container are selected

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#58424]
### Godot version

4.0.alpha3

### System information

Windows 10

### Issue description

When multiple controls inside a container are selected, their `Container sizing` values misbehave and don't work as expected as you can see in the video below:

https://streamable.com/7fl8qz

EDIT: Actual values are correct, they just don't work as expected.

### Steps to reproduce

- Add multiple controls to a container node. 
- Select them and change their `Container sizing` properties.

**Comment by akien-mga** [comment]
CC @godotengine/gui-nodes

**Comment by KoBeWi** [comment]
Fixed.
