### ISSUE TITLE
Incompatibility between Rect2i.expand and Rect2i.has_point

### ISSUE THREAD

**Issue by Sauermann** [godotengine/godot#58431]
### Godot version

v4.0.alpha.custom_build [0beb721c7]

### System information

Debian 11, Vulkan

### Issue description

At the moment `Rect2i.expand(p)` does not reliably expand the `Rect2i`, so that `p` is within the `Rect2i` according to `has_point`.

For the following function
```gdscript
func _ready():
	var r: Rect2i = Rect2i(2, 2, 1, 1)
	var p1: Vector2i = Vector2i(5, 5)
	print(r.expand(p1).has_point(p1))
```
I would expect that it prints `true`, but it prints `false`.

This is made worse by the fact, that in other cases `r` is expanded correctly:
```gdscript
func _ready():
	var r: Rect2i = Rect2i(2, 2, 1, 1)
	var p2: Vector2i = Vector2i(1, 1)
	print(r.expand(p2).has_point(p2))
```
This prints `true`.
So there is no simple and reliable way to expand an `Rect2i` to an `Vector2i`.

### Steps to reproduce

Load and run MRP (or copy the code from above)

### Minimal reproduction project

[BugRect2iIncompatibility.zip](https://github.com/godotengine/godot/files/8117256/BugRect2iIncompatibility.zip)

**Comment by groud** [comment]
This is not a bug, it's a design choice. The expand function make it so the rect move its border up to the given point, however, the right and bottom border are not considered as part of the rect.

As an example, with a TileSet sheet, if you have a tile defined by the `Rect(0, 0, 64, 64)`, then the pixel at position `Vector2i(64, 64)` is not supposed to belong to this tile (it would not be drawn by the algorithm, as it is part of another tile). 
Also, as a consequence, I think having `Rect2i(0, 0, 1,1).expand(63,63)` returning a `Rect(0, 0, 64, 64)` is not intuitive.
So yeah, I am against this change.

This has been discussed a lot in https://github.com/godotengine/godot/issues/57468 already.

**Comment by Sauermann** [comment]
Closing this, since Rect2i is based on a different arithmetic understanding.
