### ISSUE TITLE
Render in runtime window is very different than in viewport

### ISSUE THREAD

**Issue by Acvarium** [godotengine/godot#58435]
### Godot version

v4.0.alpha3.official [256069eaf]

### System information

Ubuntu 21.10. nVidia GeForce GTX 870M with 470.103.01 driver. Vulkan

### Issue description

While view-port render in new Godot 4 looks cool now, runtime looks nothing like it. There is no shadows, fog looks different, scene darker
![scr2022-02-22_001](https://user-images.githubusercontent.com/463177/155181034-14e602d9-2379-4742-8b05-c7a6463a5132.png)

### Steps to reproduce

Open Minimal reproduction project and run it

### Minimal reproduction project

[a3_test1.zip](https://github.com/godotengine/godot/files/8118579/a3_test1.zip)

**Comment by Calinou** [comment]
This is because you are using the default preview sun. This is an editor-only feature by design. To see the sun in the running project, you need to add the preview sun to the scene:

![image](https://user-images.githubusercontent.com/180032/155183617-d8704d2f-05c0-476b-86ef-dff2d9578144.png)

**Comment by Acvarium** [comment]
Thanks
