### ISSUE TITLE
Filament specular models and parametrization causing black artifacts

### ISSUE THREAD

**Issue by darrylryan** [godotengine/godot#58459]
### Godot version

master

### System information

Linux

### Issue description

The commit fe492446111ac9f8ae8186d360cdb2dcebece3da by @clayjohn is causing black artifacts to appear all over the render for me... I've reverted it locally and pulled everything else in from master and it's all fine without that commit.

### Steps to reproduce

I just built with that commit and opened my existing project... I've disabled all the post effects and black artifacts still appear.

**Comment by darrylryan** [comment]
Not sure if the links work in the description so just in case: it seems to be an issue with #fe492446111ac9f8ae8186d360cdb2dcebece3da by @clayjohn

**Comment by akien-mga** [comment]
Please give more information about your system (OS, GPU, GPU drivers version) and your project/scene that exhibits the regression.

**Comment by clayjohn** [comment]
An MRP would be very helpful too so we can narrow down exactly what is causing the issue.

**Comment by darrylryan** [comment]
![Screenshot from 2022-02-23 17-24-07](https://user-images.githubusercontent.com/3797848/155373152-49ab5bf8-67eb-44e3-ae9f-40101af6a7a9.png)

@clayjohn I have applied your proposed fix to my build and it seems to have done the trick. Isn't 1e-4 a bit of an arbitrary number though? I'd have thought it could be clamped to some more scientific limit.

**Comment by clayjohn** [comment]
> @clayjohn I have applied your proposed fix to my build and it seems to have done the trick. Isn't 1e-4 a bit of an arbitrary number though? I'd have thought it could be clamped to some more scientific limit.

It does look a little arbitrary, but I just pulled it from the Filament source code as that is what they use. So this is probably as scientific as we get. They even provided a reference!
https://github.com/google/filament/blob/9914eb84a4d613d609ae77a1d031fadf973db02c/shaders/src/common_material.fs#L10-L15

**Comment by darrylryan** [comment]
![Screenshot from 2022-02-23 17-42-50](https://user-images.githubusercontent.com/3797848/155376384-2a01334e-5299-4dec-8f8c-bdc818761db5.png)

I have to add - now that your tweaks are actually working properly, it looks absolutely phenomenal!
