### ISSUE TITLE
Godot 4 alpha 3: tons of errors when dragging and zooming in the Visual Script's canvas

### ISSUE THREAD

**Issue by kreaninw** [godotengine/godot#58453]
### Godot version

v4.0.alpha3.official [256069eaf]

### System information

Windows 11, Vulkan Clustered, Intel UHD Graphics 620 v30.0.101.1340

### Issue description

There are tons of errors when dragging and zooming in the Visual Script's canvas, as shown in the screen recording below:

https://user-images.githubusercontent.com/1403194/155234665-2ee915a0-c711-412f-8fe6-777f11c928a1.mp4

This is a regression from Godot 4 alpha 2, as shown in the screen recording below:

https://user-images.githubusercontent.com/1403194/155234748-8dab1ff8-dc78-41ab-845b-288eeb949d12.mp4

I don't know which node is causing the error. Therefore I also attached the reproduction project.

### Steps to reproduce

1. Open the **player.vs** in the reproduction project.
2. Try dragging and zooming in the Visual Script's canvas. You will see tons of errors.

### Minimal reproduction project

[G4 Super 3D Targeting System.zip](https://github.com/godotengine/godot/files/8120779/G4.Super.3D.Targeting.System.zip)

**Comment by kreaninw** [comment]
I found the cause of this issue. For some reason, there's a strange node in my Visual Script (previously a `lerp_angle()` node). I don't know why my lerp_angle() node was converted into this strange `posmod` node. After removing this node, this issue disappeared, as shown in the screen recording below:

https://user-images.githubusercontent.com/1403194/156058772-6b1eca39-4cda-4eb5-97aa-881bfdc54e6c.mp4

**Comment by KoBeWi** [comment]
VisualScript was removed in Godot 4.0, so closing.
