### ISSUE TITLE
[Godot 4] Unrecoverable crash if Label font sizes identical, not on all devices

### ISSUE THREAD

**Issue by Pandaqi** [godotengine/godot#58462]
### Godot version

4.0.alpha3

### System information

Windows 11, Vulkan API 1.2.0, AMD Ryzen 5 3600 6-Core Processor, NVIDIA GeForce GTX 1650 SUPER

### Issue description

My project crashes on startup, no error in the logs or message anywhere, but only on a specific computer. (Other Godot projects and games work fine on this computer.)

The details: Windows 11, Vulkan API 1.2.0, AMD Ryzen 5 3600 6-Core Processor, NVIDIA GeForce GTX 1650 SUPER

It's just two labels with the same font size, inside a Node2D, inside a CanvasLayer.

Going into Main.tscn (with NotePad) and changing the font size of the second label to some other number fixes everything and allows the project to open.

It works fine on all other computers. (Windows 10, all of them laptops with Intel processors and NVIDIA graphics. Don't know more details, all of those laptops are really, really old.)

The same issue was also present in earlier alphas of Godot 4.

This is part of a bigger project, but I reduced it to the one point of failure: two labels with the same font size. Modifying that one font size value fixes _everything_.

### Steps to reproduce

Try to open the minimal reproduction project. 

(However, it might work perfectly fine on your device, I've only had this crash on one of my devices.)

### Minimal reproduction project

[Uploading Minimal Reproduction Project (Godot 4 Label Font Size Bug).zip…]()

**Comment by Pandaqi** [comment]
Something went wrong with the project uploading. Here it is:

[Minimal Reproduction Project (Godot 4 Label Font Size Bug).zip](https://github.com/godotengine/godot/files/8125282/Minimal.Reproduction.Project.Godot.4.Label.Font.Size.Bug.zip)

**Comment by Pandaqi** [comment]
Sorry, forgot to remove the autoloading scripts. (A relic from the bigger project from which I extracted this MRP.) Removing them doesn't change anything for me.

I realize this is a weird and specific bug. But on that specific computer, this project does not even open in the editor (without crashing), nor can it run the exported exe (using a different laptop to export the project of course).

The computer is quite new and has no issues with anything else, and I can pin it down to this very particular issue with font sizes.

I'm interested if _anybody_ else can confirm this. If nobody else comes along for whom the project crashes, then I guess it's just some terrible miscommunication somewhere on my specific device, not necessarily a bug within Godot?

**Comment by Calinou** [comment]
> But on that specific computer, this project does not even open in the editor (without crashing), nor can it run the exported exe (using a different laptop to export the project of course).

Could you try to [compile a debug build with MSVC][https://docs.godotengine.org/en/latest/development/compiling/compiling_for_windows.html), run it from a command prompt and paste the crash backtrace here?
