### ISSUE TITLE
Crash when using lightmap_unwrap() with textel_size 0.0

### ISSUE THREAD

**Issue by Coxcopi** [godotengine/godot#58471]
### Godot version

v3.4.2.stable.official [45eaa2daf]

### System information

Windows 10, GLES3, NVIDIA GeForce GTX 1060 6GB

### Issue description

Godot crashes when calling lightmap_unwrap() on an ArrayMesh with a texel_size of 0.0.
If done in a tool script, the whole Editor crashes, else the game just crashes without an error.

### Steps to reproduce

(see reproduction project below)
Game crash:
1. open project
2. run
3. game crashes without any error

Editor crash:
1. open project
2. select MeshInstance
3. run function through exported variable ('Run from Editor') on the MeshInstance
4. editor crashes

### Minimal reproduction project

[Bug.zip](https://github.com/godotengine/godot/files/8126272/Bug.zip)

**Comment by qarmin** [comment]
```
modules/xatlas_unwrap/register_types.cpp:64:35: runtime error: division by zero
thirdparty/xatlas/xatlas.cpp:8302:55: runtime error: inf is outside the range of representable values of type 'unsigned int'
godots: thirdparty/xatlas/xatlas.cpp:536: uint32_t xatlas::internal::nextPowerOfTwo(uint32_t): Assertion `x != 0' failed.
```
I can't even open editor with this project
