### ISSUE TITLE
Godot 4: Visual Script's variable hinting doesn't work

### ISSUE THREAD

**Issue by kreaninw** [godotengine/godot#58484]
### Godot version

v4.0.alpha3.official [256069eaf]

### System information

Windows 11, Vulkan Clustered, Intel UHD Graphics 620 v30.0.101.1340

### Issue description

Visual Script's variable hinting doesn't work, as shown in the screenshot below:

![Screenshot 2022-02-23 232228](https://user-images.githubusercontent.com/1403194/155446797-b8f8cfb9-9652-4ea8-8105-595d58bce782.jpg)

This is a regression from Godot 3.4. For example, if the users set a variable hint to **Enum**, then set the hint strings, the value(int) of the variable would be shown as the hint string accordingly, as shown in the screenshot as shown below:

![Screenshot 2022-02-23 232134](https://user-images.githubusercontent.com/1403194/155447730-c1cf6a96-d6a3-4802-a0b4-108bff264f38.jpg)

I expect the variable hinting to work in Visual Script.

### Steps to reproduce

1. Create a new variable as `int` type in Visual Script.
2. Change the Hint to Enum.
3. Add Hint Strings as much as you want. You won't see the value box change into the  Hint String value.

**Comment by kreaninw** [comment]
I just noticed that hinting for the engine built-in property is working fine, for example, the `rotation_order` from `Node3D` class, as shown in the screenshot below:

![Screenshot 2022-02-25 035442](https://user-images.githubusercontent.com/1403194/155669513-81877172-d878-4dc1-82f8-00ccfb07b9f9.jpg)

But the user-created variable's property will not show the hinting, as shown in the screenshot below:

![Screenshot 2022-02-25 040102](https://user-images.githubusercontent.com/1403194/155670079-78f934c0-181a-420d-83d4-8f1f6e5282bd.jpg)

**Comment by KoBeWi** [comment]
4.0 no longer has VisualScript.
