### ISSUE TITLE
Toggling visibility of a node inside an invisible parent causes the eye icon to stop being greyed out

### ISSUE THREAD

**Issue by Hecksa** [godotengine/godot#58495]
### Godot version

4.0.alpha2

### System information

Windows 10

### Issue description

When nodes are visible, their icons are lighter than when they are not. As a reference, here's how things look by default:

![image](https://user-images.githubusercontent.com/37386245/155519732-dca52a3b-104e-4323-b787-8a9ee0cb4a3a.png)

When you make a node invisible, it greys out the visibility icon of all of its children, as below:

![image](https://user-images.githubusercontent.com/37386245/155518185-f10bc3bb-9be7-4e49-895d-4026a83fe8c8.png)

However, if you hide and then re-show one of those children, this effect is lost:

![image](https://user-images.githubusercontent.com/37386245/155518571-977d424c-0744-48ca-90a6-63c772daa1c4.png)

This behaviour happens in v4.0 alpha 2, and definitely does *not* in v3.4. I don't currently have v3.5 so am unable to check there.

### Steps to reproduce

1. Create a new scene, with any root node, eg a Node2D.
2. Create any child node under the root node, again a Node2D is fine.
3. Click the eye icon of the root node to make it invisible. The eye icon of the child node should desaturate.
4. Click the eye icon of the child node to make it invisible. It will correctly switch to the "closed eye" icon and stay grey.
5. Click the eye icon of the child node again. It will switch back to the "open eye" icon, but will lose its desaturated effect.

**Comment by Hecksa** [comment]
Just realised I've not got 4.0 alpha3 yet, so grabbed it and found things are working fine, although I can't find the original issue or any fix. 

Either way, looks like it's a false alarm, sorry!

**Comment by KoBeWi** [comment]
This was likely fixed by #58315
