### ISSUE TITLE
[Godot 4] import file dialog ui lag

### ISSUE THREAD

**Issue by SimonImming** [godotengine/godot#58501]
### Godot version

v4.0.alpha3.official [256069eaf]

### System information

Ubuntu 21.10 on Wayland Gnome 40.4.0

### Issue description

The import file dialog from the project page is affected by lag. After having the file browser window open for a few seconds, all inputs and mouse movement begins to lag.

I could not reproduce this in other file browser windows in the main editor. The only visible difference to other file browser windows in Godot is that the file browser opened from the import dialog on the projects page has a drop down menu showing the OS file bookmarks in the top right corner of the window.

This bug occurs with all official Godot 4 alpha builds for me, not with 3.x builds (even 3.5 beta). 

### Steps to reproduce

- Open Godot 4 alpha
- In the Project Manager, click on "Import"
- In the Dialog "Import Existing Project", click "Browse" --> "Open a File" window opens
- Wait a few seconds (~2sec for me)
- Try to click something

### Minimal reproduction project

Not required

**Comment by Calinou** [comment]
Can you reproduce this when starting the project manager with the `--single-window` [command line argument](https://docs.godotengine.org/en/stable/getting_started/editor/command_line_tutorial.html)?

**Comment by SimonImming** [comment]
Thanks for the quick response @Calinou 

The bug does not occur when using `--single-window`, neither does it occur on an X11 session.

However, other separate windows (when using multiple windows and on Wayland) don't show that behavior. For example, if I open a project and click on Scene --> Open Scene another window opens which is not affected by any lag. 

So it seems to me that there might be another issue with this specific project import window. Maybe something related to that bookmarks menu? Like the dialog scanning larger parts of the file system?

When starting Godot 4 from the command line, I also noticed the following warning on the command line:
`MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0`
Don't know if that's important, as I haven't noticed any other performance issues so far.

**Comment by KoBeWi** [comment]
Is this still happening in alpha 7?

**Comment by SimonImming** [comment]
@KoBeWi unfortunately yes, it's still the same in alpha 7.

**Comment by SimonImming** [comment]
The bug still persists in beta. I tried to run Godot while also recording with the gnome Sysprof profiler. When the lag occurs, the "Stack traces" graph shows very high spikes. But I'm not very familiar with the profiler, so have no idea what else to do with it. I'm not even sure if it's the right tool for finding the cause of the bug. But if you know how it could provide useful information, please let me know what I should look for and I'll be happy to try it.

**Comment by SimonImming** [comment]
I can't reproduce the bug anymore. I believe this was not directly caused by Godot as I recently installed other updates on my system and now even the older beta and alpha releases that were affected now work as expected. I'll keep an eye on it with the next beta releases but close the issue in the meantime.
