### ISSUE TITLE
Exports With Latest Android Export Templates Crashes At Startup

### ISSUE THREAD

**Issue by ranmaru90** [godotengine/godot#5850]
**Operating system or device - Godot version:**
Windows 10. Latest from GitHub.

**Issue description** (what happened, and what was expected):
Compiled the Android export templates from the latest GitHub source. Exported a game to Android, ran it on an Android device. Crashed at startup.

adb logcat -s godot gives:

https://gist.github.com/ranmaru90/6e516006dd84c2f64c68f1911543adbb

**Steps to reproduce:**
1. Get the latest Godot source.
2. `scons platform=android target=release_debug tools=no android_arch=armv6 android_neon=no -j 2 && scons platform=android target=release tools=no android_arch=armv6 android_neon=no -j 2`
3. Go to platform/android/java and `gradlew build`.
4. Export a game using the generated templates in bin.
5. Install and run the game on an Android device.
6. Crashes at startup.

**Comment by volzhs** [comment]
possibly it's related #5645

**Comment by ranmaru90** [comment]
I reset to previous commits and seems like before commit 370ae3512deda40b2659a1192f302298e269305f it was working fine.

**Comment by akien-mga** [comment]
Are you using an editor build and templates from the same commit?

**Comment by volzhs** [comment]
then there's a possibility to make wrong android template.
I had a similar issue #5779

**Comment by ranmaru90** [comment]
Yeap. All from the same commit.

**Comment by akien-mga** [comment]
Do you have a `platform/android/java/libs/armeabi/` folder with an outdated lib in it? (check the modification date)? If so removing it might fix your issue, and confirm that we have a buildsystem problem.

**Comment by ranmaru90** [comment]
I've recompiled everything again with my usual:

`scons platform=windows target=release_debug tools=yes -j 2 && scons platform=windows target=release_debug tools=no -j 2 && scons platform=windows target=release tools=no -j 2 && scons platform=android target=release_debug tools=no android_arch=armv6 android_neon=no -j 2 && scons platform=android target=release tools=no android_arch=armv6 android_neon=no -j 2`

And my `libs `folder contains a `debug `folder and a `release `folder, and the `armeabi/libgodot_android.so` in each folder is up-to-date.

I used the newly compiled editor and `android_debug.apk `and `android_release.apk` to export and install on my device. It still crashes and I found this

> E/AndroidRuntime( 5075): FATAL EXCEPTION: main
> E/AndroidRuntime( 5075): Process: com.twistedcats.dontbuildhere, PID: 5075
> E/AndroidRuntime( 5075): java.lang.UnsatisfiedLinkError: No implementation found for void org.godotengine.godot.GodotLib.gyroscope(float, float, float) (tried Java_org_godotengine_godot_GodotLib_gyroscope and Java_org_godotengine_godot_GodotLib_gyroscope__FFF)
> E/AndroidRuntime( 5075):        at org.godotengine.godot.GodotLib.gyroscope(Native Method)
> E/AndroidRuntime( 5075):        at org.godotengine.godot.Godot.onSensorChanged(Godot.java:678)
> E/AndroidRuntime( 5075):        at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:405)
> E/AndroidRuntime( 5075):        at android.os.MessageQueue.nativePollOnce(Native Method)
> E/AndroidRuntime( 5075):        at android.os.MessageQueue.next(MessageQueue.java:143)
> E/AndroidRuntime( 5075):        at android.os.Looper.loop(Looper.java:122)
> E/AndroidRuntime( 5075):        at android.app.ActivityThread.main(ActivityThread.java:5281)
> E/AndroidRuntime( 5075):        at java.lang.reflect.Method.invoke(Native Method)
> E/AndroidRuntime( 5075):        at java.lang.reflect.Method.invoke(Method.java:372)
> E/AndroidRuntime( 5075):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
> E/AndroidRuntime( 5075):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
> W/ActivityManager( 7434):   Force finishing activity 1 com.twistedcats.dontbuildhere/org.godotengine.godot.Godot

in my adb logcat, which is similar to the issue #5779 @volzhs  mentioned.

I am going to `git clean -dfx` and try again.

**Comment by ranmaru90** [comment]
Ok, it appears that there is no problem. My bad for not cleaning up.
