### ISSUE TITLE
Godot 4: variables in the Visual Script's members window don't sort by their name

### ISSUE THREAD

**Issue by kreaninw** [godotengine/godot#58509]
### Godot version

v4.0.alpha3.official [256069eaf]

### System information

Windows 11, Vulkan Clustered, Intel UHD Graphics 620 v30.0.101.1340

### Issue description

The variables in the Visual Script's members window doesn't sort by name, as shown in the screenshot below:

![Screenshot 2022-02-24 162348](https://user-images.githubusercontent.com/1403194/155595835-abce0d0a-70c2-4957-97f0-0837d2af7b8e.jpg)

This is a regression from Godot 3.4. In Godot 3.4, the variables will be sorted by name, as shown in the screenshot below:

![Screenshot 2022-02-24 162414](https://user-images.githubusercontent.com/1403194/155595977-c97dc7a6-06c6-438d-a113-ca963767ccd9.jpg)

I expect all the variables to be sorted by name. Moreover, all the functions in Godot 4 are sorted by their name, why not the variables too?

### Steps to reproduce

1. Create some variables in Visual Script.
2. Look at the members' window, the variable won't be sorted by name.

**Comment by raulsntos** [comment]
VisualScriptEditor gets the script variables using the `get_variable_list` [[`3.x`](https://github.com/godotengine/godot/blob/0959ff2fe4e50ad29866ae1f3fba3133fce152b3/modules/visual_script/visual_script.cpp#L652-L658)] [[`master`](https://github.com/godotengine/godot/blob/4dc8214831d1617e7f5f06e8294fb37ea23dae59/modules/visual_script/visual_script.cpp#L565-L568)] method.

It seems in `3.x` it was sorting the variables but in `master` this was changed in PR #39649 and no longer does.

The functions are retrieved using the `get_function_list`, this doesn't sort either but [VisualScriptEditor sorts them](https://github.com/godotengine/godot/blob/4dc8214831d1617e7f5f06e8294fb37ea23dae59/modules/visual_script/editor/visual_script_editor.cpp#L1047) after retrieving, so sorting the variables should probably be done the same way.
