### ISSUE TITLE
New "blender style" shortcuts take effect even when in right click navigation mode

### ISSUE THREAD

**Issue by timshannon** [godotengine/godot#58502]
### Godot version

v4.0.alpha.mono.custom_build [872e8a43c]

### System information

Ubuntu 20.04.3 LTS

### Issue description

The new blender style shortcuts take effect when navigating by holding down the right mouse button.  This becomes an issue if you rebind the controls to those of blender, and try to navigate a scene when you have anything selected.

For example, I've bound `Begin Rotate` to `R` `Begin Scale` to `S` and `Begin Translate` to `G` to match the behavior in blender:
![image](https://user-images.githubusercontent.com/1330485/155557343-e7f1921d-a0df-471e-a355-bdb8e0af00d6.png)

But if you select a mesh, then hold down the right mouse button and use `WASD` to navigate a scene, when `S` is pressed it begins the scaling operation.

### Steps to reproduce

Rebind any of the Begin Scale, Begin Translate, or Begin Rotate to any one of the WASD keys, then select a mesh in a scene, then hold down the right mouse button and navigate around.

**Comment by Calinou** [comment]
cc @rcorre 

I think it's good that manipulation shortcuts work while freelook is enabled, but it should only be the case if the shortcut is *not* already used for movement.

**Comment by rcorre** [comment]
> In the default configuration, this means translation and rotation would still be allowed while in freelook mode – and these are arguably the most common operations.

I haven't used freelook before (I'm just trying it now), but I'm having a hard time picturing how or why any of these should work with freelook enabled. I'm thinking they should all be disabled, and if you want to translate/rotate/scale, you can just release RMB?
