### ISSUE TITLE
Vulkan: Decal and Light3D distance fade uses view plane distance, resulting in unstable fading when the camera rotates (unlike GeometryInstance3D)

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#58513]
### Godot version

4.0.dev (872e8a43c)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 495.46)

### Issue description

Decal's distance fade works using a view plane distance calculation, rather than an actual distance between the camera and the Decal node:

https://github.com/godotengine/godot/blob/80baa1386a5a19ed8ea50082617d2ae9112678fc/servers/rendering/renderer_rd/renderer_scene_render_rd.cpp#L3665-L3676

This means that decals that _should_ be hidden due to distance may be visible again when the camera is rotated. Not only this increases GPU performance demands, but this also makes the image appear less stable in motion. The issue is more noticeable at higher camera FOVs, but even at the default FOV, it's quite visible already.

GeometryInstance3D visibility ranges do not suffer from this issue, as a `distance_to()` function is used. We should use the same formula for all kinds of LOD to ensure consistency, while making sure that LOD does not break with orthogonal cameras.

Since https://github.com/godotengine/godot/pull/58512 uses the same distance fade calculation, it's also affected by this issue.

https://user-images.githubusercontent.com/180032/155622331-54d8f2ee-2370-49ba-aa30-7b836bee7302.mp4

### Steps to reproduce

- Add a MeshInstance3D node with a primitive mesh resource for the decal to be projected on.
- Add a Decal node. Set an Albedo texture (`icon.png` or a new NoiseTexture will do).
- Enable **Distance Fade** on the Decal node.
- Move at least 10 units away from the Decal node, then rotate the camera in the editor slowly.
- Notice the decal will slowly appear again as you rotate the camera, despite being more than 10 units away from the Decal.

### Minimal reproduction project

[test_decal_distance_fade.zip](https://github.com/godotengine/godot/files/8137091/test_decal_distance_fade.zip)

**Comment by elvisish** [comment]
I've got even weirder issues with Decals in 4.0:
https://github.com/godotengine/godot/issues/70231

**Comment by Calinou** [comment]
> I've got even weirder issues with Decals in 4.0: #70231

This is an unrelated issue. Please don't hijack issues with comments like those – just create a new issue instead.

**Comment by elvisish** [comment]
> 

I didn't hijack, how is this not the same issue as I'm having? The decals don't display properly when the camera rotates, exactly the same issue here (except my example has some additional issues).

**Comment by elvisish** [comment]
> > I've got even weirder issues with Decals in 4.0: #70231
> 
> This is an unrelated issue. Please don't hijack issues with comments like these – just create a new issue instead.

I didn't hijack, how is this not the same issue as I'm having? The decals don't display properly when the camera rotates, exactly the same issue here (except my example has some additional issues).

**Comment by Calinou** [comment]
> I didn't hijack, how is this not the same issue as I'm having? The decals don't display properly when the camera rotates, exactly the same issue here (except my example has some additional issues).

You don't seem to have distance fade enabled on the decals (it's disabled by default). Hence, it's a different issue entirely.

**Comment by elvisish** [comment]
> 



> > I didn't hijack, how is this not the same issue as I'm having? The decals don't display properly when the camera rotates, exactly the same issue here (except my example has some additional issues).
> 
> According to that issue's description, you don't seem to have distance fade enabled on the decals (it's disabled by default). Hence, it's a different issue entirely. We can't know for sure anyway as you didn't upload a minimal reproduction project 🙂

Ah okay, I didn't realize this issue was with distance fade, it just seemed very similar to problems I'm having with decals.

**Comment by clayjohn** [comment]
Fixed by https://github.com/godotengine/godot/pull/71709
