### ISSUE TITLE
Tooltips steal focus

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#58515]
### Godot version

80baa13

### System information

W10

### Issue description

![BlackTooltips](https://user-images.githubusercontent.com/2223172/155625673-416881e1-7b83-4443-8157-f91441c00f64.gif)

### Steps to reproduce

1. Open some dialog (e.g. Add Node dialog)
2. Hover over something with a tooltip
3. Tooltip appears
4. Your dialog loses all focus

**Comment by bruvzg** [comment]
Seems like regression from #58420, should be fixed by #58461 or #58490.

**Comment by KoBeWi** [comment]
Fixed by #58490
