### ISSUE TITLE
Inspector focus next Tab key not working

### ISSUE THREAD

**Issue by cgbeutler** [godotengine/godot#58523]
### Godot version

3.4.3.rc2_mono_win64

### System information

Windows 10

### Issue description

The inspector no longer seems to respect the tab key to go to the next field.
Color editing panel doesn't either.
I tried creating a brand new project, in case it was a plugin or something, but the issue persists.

### Steps to reproduce

Create a new scene with a Node2D.
Bring up the node in the inspector.
Click the transform position x field.
Hit tab.
Expect it to go to the next field, it does not.

### Minimal reproduction project

N/A

**Comment by cgbeutler** [comment]
Seems like a big issue. There is a slight chance this is a duplicate, but I couldn't find it in my cursory search.

**Comment by akien-mga** [comment]
Indeed that was a regression in 3.4.3 RC 2, fixed since.

Duplicate of #58460
