### ISSUE TITLE
ColorPickerButton - pick color from screen does not work

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#5853]
There is a tiny pipette button in the pick color dialogue which I assume should let you pick any color from the screen. It however doesnt do anything.

This affects both godot's editor and also using the colorPickerButton node.

To reproduce this:
1. add a colorPickerButton to an empty project or click on such a button somewhere in godot itself
2. Click on the top right pipette button
3. Click anywhere outside of the color picker dialogue - anywhere on the screen

Expected behaviour:

> Mariano Suligoy: Clickng in the screen will pick the color, but also close the color picker

Current behaviour:
Nothing happens. No color is picked and the color picker is closed

tested on both windows and linux - broken on both

**Comment by blurymind** [comment]
@MarianoGnu  That was quick! Thank you :)

I will use this in my app

**Comment by MarianoGnu** [comment]
i've been avoiding fix this for some time, because noone complained yet :tongue: i tryed in the past and failed, give thanks to @reduz who helped me to find how make show_modal work.

**Comment by blurymind** [comment]
Thank you @reduz :) humbly making things awesome behind the scenes again
