### ISSUE TITLE
Godot 4: all the functions in Visual Script are not returning their value type correctly

### ISSUE THREAD

**Issue by kreaninw** [godotengine/godot#58535]
### Godot version

v4.0.alpha3.official [256069eaf]

### System information

Windows 11, Vulkan Clustered, Intel UHD Graphics 620 v30.0.101.1340

### Issue description

All the functions in Visual Script are not returning their value type correctly, for example, the `get_child_count()` should return its value as `int` but it returns as `any` instead, as shown in the screen recording below:

https://user-images.githubusercontent.com/1403194/155761356-e11a2996-963d-428c-9653-5bed83b88b8d.mp4

This is a regression from Godot 3.4. In Godot 3.4, this is working fine as shown in the screen recording below:

https://user-images.githubusercontent.com/1403194/155764076-f88277d7-e78f-4c98-a01e-c188898a59f7.mp4

Note: I don't know whether this issue is caused by [issue #58069](https://github.com/godotengine/godot/issues/58069) or whether it's related to [issue #58035](https://github.com/godotengine/godot/issues/58035).

To work around this issue, I will have to:

1. Change the function call mode to **Instance**.
2. Delete its base script due to [issue #58069](https://github.com/godotengine/godot/issues/58069).
3. Duplicate the function call node. Then, the return value type will be set correctly as shown in the screen recording above.

### Steps to reproduce

1. Add a Visual Script function.
2. See its value return type, it will always be `any`.

**Comment by KoBeWi** [comment]
VisualScript was removed in Godot 4.0, so closing.
