### ISSUE TITLE
`_ready` not called on CPUParticles if not emitting and single shot

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#58534]
### Godot version

v3.4.3.rc1.official [894b6d504]

### System information

Mac OSX (Intel 2019)

### Issue description

When a `CPUParticles` instance is not emitting by default `_ready` is not called when the particle is duplicated.

```gdscript
extends CPUParticles

func _ready():
	self.emitting = true
	get_parent().add_child(self.duplicate(true))
	print("_ready", get_parent().get_children())
```

Maybe this is some `gotcha` about the shared resource?

### Steps to reproduce

[godot-particles.zip](https://github.com/godotengine/godot/files/8142381/godot-particles.zip)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/17903 (possible duplicate?).

**Comment by tavurth** [comment]
I saw that one but in this case it's about the `_ready` function not getting called.

I checked and the node is getting added to the scene, it's weird 🤔

**Comment by tavurth** [comment]
Note that this bug was caused because I was `deep` duplicating the `CPUParticles` which seems to also copy the `_ready` state.

```gdscript
	get_parent().add_child(self.duplicate(true))
```

Should rather be:
```gdscript
	get_parent().add_child(self.duplicate(false))
```
