### ISSUE TITLE
The application is still signed even if the "signed" option is disabled when using Android one-click deploy

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#58540]
### Godot version

v3.5.beta1.official [b9b23d222]

### System information

w10 64

### Issue description

This happens on android.

Option signed deactivated
![Captura](https://user-images.githubusercontent.com/19652075/155789723-7aa1a039-3464-4b2b-bc5c-00fceb364bc6.PNG)

The application is still signed when exporting
![Captura2](https://user-images.githubusercontent.com/19652075/155789745-002328bd-d201-463f-a4f4-26f78e1b440c.PNG)

### Steps to reproduce

see the images

### Minimal reproduction project

...

**Comment by Calinou** [comment]
When using [one-click deploy](https://docs.godotengine.org/en/stable/getting_started/workflow/export/one-click_deploy.html), signing is always enabled no matter the setting's value: https://github.com/godotengine/godot/blob/0393057e36e486b2944e6166e6572327944b2fa7/platform/android/export/export_plugin.cpp#L1849
(5th argument `should_sign` is always set to `true`.)

When exporting traditionally, the signing flag is supposed to be obeyed though: https://github.com/godotengine/godot/blob/0393057e36e486b2944e6166e6572327944b2fa7/platform/android/export/export_plugin.cpp#L2620

**Comment by Torguen** [comment]
The reason is to save time generating the apk by avoiding the signature. I did not know that the latest versions no longer allow unsigned installation.

**Comment by m4gr3d** [comment]
> I am referring to the use in "one click deploy". The reason is to save time generating the apk by avoiding the signature. I did not know that the latest versions no longer allow unsigned installation.

`One click deploy` installs directly to the device, and as @Calinou mentioned, Android does not allow installation of unsigned apk, hence that apk is always signed.

If you want to generate an unsigned apk, you have to use the regular export mechanism.
