### ISSUE TITLE
Parser bug (please report) for forward referenced function used in variable initializer

### ISSUE THREAD

**Issue by strank** [godotengine/godot#58542]
### Godot version

4.0.alpha.custom_build.cfc7c7873

### System information

Linux, Manjaro

### Issue description

ERROR: Parser bug (please report): tried to assign unset node without an identifier.
   at: resolve_class_interface (modules/gdscript/gdscript_analyzer.cpp:655)

Happens at "res://Testing.gd", see below, line "3" (I had to augment the error message to find that - I will file a different proposal/PR to change that).

### Steps to reproduce

Run the following with `godot --headless -s Testing.gd`:

```
extends MainLoop

var INPUT = read_input()

func read_input() -> String:
    return "testing"

## Request quitting main loop immediately by returning true. Not needed for bug reproduction, it's just cleaner!
func _process(_delta: float) -> bool:    
    return true
```

### Minimal reproduction project

See above. File attached here for convenience.

[Testing.gd.txt](https://github.com/godotengine/godot/files/8145003/Testing.gd.txt)

**Comment by strank** [comment]
Just a note regarding the usefulness of the error message, in case somebody else wants to take this up or I don't get to it. I changed the line modules/gdscript/gdscript_analyzer.cpp:655 to:

```
ERR_PRINT(vformat(R"(Parser bug (please report): tried to assign unset node without an identifier. "%s" line %s)", p_class->fqcn, member.get_line()));
```

By default the error message does not contain any indication on what GDScript code caused the problem. There are a few more spots where ERR_PRINT is used in GDScript's parser and analyzer that could probably be improved similarly.

**Comment by ChristianB84** [comment]
I also had this error and had to spend some time trying to find out what in my scripts caused it. Looks like the function that is used for the initialization must be defined before the assignment. So if you move the "read_input" function in the example before the line where it is called to initialize INPUT, the error should disappear.

**Comment by djmaesen** [comment]
i get tons of parser bug errors since beta5 
project was working fine before, now i cant even play a scene

**Comment by anvilfolk** [comment]
I just tested this and got nothing on my console. I added some prints and still got nothing, so I can't really tell whether it fixed anything.

But there are no errors that I could see!

**Comment by anvilfolk** [comment]
It was some issues with indentation being spaces instead of tabs :)

```
> .\bin\godot.windows.editor.dev.x86_64.console.exe --headless -s ..\godot-test\headless.gd
Godot Engine v4.0.beta.custom_build.d99ea3299 - https://godotengine.org

Testing
testing
PS C:\dev\godot>
```

For file
```GDScript
extends MainLoop

var INPUT = read_input()

func read_input() -> String:
	print("Testing")
	return "testing"

## Request quitting main loop immediately by returning true. Not needed for bug reproduction, it's just cleaner!
func _process(_delta: float) -> bool:
	print("testing")
	return true
```

Looks fixed?

**Comment by akien-mga** [comment]
Thanks for testing, closing.
