### ISSUE TITLE
Godot 3.4.3 does not load on Windows 11 (expired signature)

### ISSUE THREAD

**Issue by jguard0** [godotengine/godot#58545]
### Godot version

3.4.3

### System information

Windows 11 Pro

### Issue description

The app does not load. As soon as I double click the icon to open the app the command windows shows for a brief second and disappears but the app never loads.

System Specs.

Processor: AMD Ryzen Threadripper 3990X 64-Core Processor    2.90 GHz
Installed RAM:  128 GB (128 GB usable)
System Type: 64-bit operating system, x64-based processor
Operating System: Windows 11 PRO
OS Build:  22000.527
Version: 21H2 - 10.0.22000

### Steps to reproduce

The app does not load. As soon as I double click the icon to open the app the command windows shows for a brief second and disappears but the app never loads.

**Comment by Calinou** [comment]
@jguard0 Does Godot 3.4.2 run on the same system?

Also, do you get any output if you start the Godot executable from a command prompt?

**Comment by jguard0** [comment]
Hugo,

 

Version 3.4.2 of the App works as expected.

 

I just tried running Godot 3.4.3 from the command line and that seemed to load just fine.

 

Command line output

 

Godot Engine v3.4.3.stable.official.242c05d12 - https://godotengine.org

OpenGL ES 3.0 Renderer: NVIDIA GeForce RTX 3080 Ti/PCIe/SSE2

OpenGL ES Batching: ON

 

The current version 3.4.3 App will not load from double clicking the icon.

 

I hope this helps.

 

Jimmy

**Comment by ChronoDK** [comment]
Maybe it's because the binary isn't signed? Windows 10 complains about that.

**Comment by ChronoDK** [comment]
Actually, the binary does look like it's signed. Not sure why Windows 10 won't trust it then. It was not a problem with the previous versions. Anyway, it's likely the same thing that causes it to not start on Windows 11.

**Comment by akien-mga** [comment]
The signing cert might have expired, I'll check.

**Comment by Psychophylaxis2** [comment]
I cannot start Godot 3.4.3 on Windows 11 unless it is on the primary monitor.

**Comment by mightymochi** [comment]
> Actually, the binary does look like it's signed. Not sure why Windows 10 won't trust it then. It was not a problem with the previous versions. Anyway, it's likely the same thing that causes it to not start on Windows 11.

I am also having the issue of Windows 10 defender saying unknown publisher for anything over 3.4.2 stable.

**Comment by akien-mga** [comment]
We've had a new signing certification since of few months used for 3.5 betas/RCs and 4.0 alphas, so this is fixed.
3.4.3 and 3.4.4 likely still have this issue since they were made before we had the new cert, but an upcoming 3.4.5 should solve it.
