### ISSUE TITLE
Vulkan Clustered: Cull direction flips as camera moves with multiple MeshInstance3Ds using the same mesh at negative and positive scales

### ISSUE THREAD

**Issue by jtnicholl** [godotengine/godot#58546]
### Godot version

v4.0.alpha.custom_build [0393057e3]

### System information

Linux (KDE Neon 5.24) w/ kisak-mesa ppa, Radeon R9 390x, amdgpu driver

### Issue description

When multiple MeshInstance3D nodes are in the scene using the same Mesh resource, and some but not all of the nodes have a negative scale, the nodes at one scale have their cull direction flipped. Moving the camera so that the nodes go in or out of view causes the directions to flip. Continuing to move the camera causes the nodes to repeatedly flip back and forth.

https://user-images.githubusercontent.com/44414418/155821511-84b2fbff-d640-4dd3-99dc-262e2fcb8919.mp4

If _all_ nodes using the same mesh are at a negative scale, they render normally, with negative scale only mirroring the object without affecting its cull direction. The issue also does not occur on the mobile backend, only clustered.

### Steps to reproduce

Create a MeshInstance3D node in the scene and add a mesh. Duplicate it a few times and scatter them around. Set the scale to -1 on an axis for half of them. Half of them will have their cull direction flipped. Move the camera around so they go in and out of view and the cull directions flip back and forth.

### Minimal reproduction project

[ScaleIssue.zip](https://github.com/godotengine/godot/files/8145556/ScaleIssue.zip)
Same scene from the video.

**Comment by cooperra** [comment]
I can confirm that this still happens on 4.0.alpha7.
