### ISSUE TITLE
Invalid call. Nonexistent 'Int' constructor

### ISSUE THREAD

**Issue by leapofazzam123** [godotengine/godot#58553]
### Godot version

3.2.3.stable

### System information

Arch Linux aarch64, GLES2

### Issue description

I'm developing a Progressbar95 clone in Godot and this error pops up

### Steps to reproduce

```python
var systemlist = [
	"Progressbar 3.14",
	"Progressbar 95",
	"Progressbar 98",
]
onready var itemList = get_node("ItemList")
func ready():
	for i in range(systemList):
		itemList.add_item(systemList[i])
		itemList.set_item_tooltip_enabled(i, false)
```

**Comment by KoBeWi** [comment]
The error is a bit vague, but you can't make `range` from a node.
