### ISSUE TITLE
Can't preload a scene in AutoLoad script when the scene's script references the AutoLoad

### ISSUE THREAD

**Issue by lonevox** [godotengine/godot#58551]
### Godot version

4.0.alpha3

### System information

Windows 10

### Issue description

This appears to be a regression in 4.0, as this works in 3.4.3. Running the scene causes a ParserError crash, when I expect it to run fine.

### Steps to reproduce

If you have a simple AutoLoad script like so:
![image](https://user-images.githubusercontent.com/38600896/155838067-4ed926c0-372c-4b24-ba7e-847620b0e0b5.png)

Which preloads this simple scene with just one script:
![image](https://user-images.githubusercontent.com/38600896/155838100-dcd148cc-9708-4b36-af9f-c98f1db31f78.png)

And that script references the AutoLoad script:
![image](https://user-images.githubusercontent.com/38600896/155838123-ab2fec36-2c0c-4038-a96b-e510dcc3152a.png)

Then running the scene causes a crash:
`Parser Error: Could not preload resource file "res://Scene.tscn"`

### Minimal reproduction project

Working project in 3.4.3:
[AutoloadBugGodot3.4.3.zip](https://github.com/godotengine/godot/files/8146324/AutoloadBugGodot3.4.3.zip)

Identical project but in 4.0.alpha3:
[AutoloadBugGodot4.zip](https://github.com/godotengine/godot/files/8146325/AutoloadBugGodot4.zip)

**Comment by lbowers** [comment]
I just came here to report this very issue in alpha 6. Glad to see it's already a known issue. Hope to see it resolved soon.

**Comment by Sebastyle** [comment]
Just had the same issue in `v4.0.alpha13.official [59dcddc45]`  And maybe this is relevant for fixing this: 
When running the project from the editor, one can just 'Continue' twice in the debugger and everything seems to work as expected. This can also be seen in the minimal reproduction project above.

In my case I can even confirm that both the reference to the preloaded scene, aswell as the usage of the autoload works afterwards.

**Comment by zeddyemmy** [comment]
Still present in the v4 beta, and continuing twice also proceeds past it

**Comment by freelancer42** [comment]
Using load instead of preload does work fine though (at least in 4.0-beta1).

Not sure if there's actually any practical difference between load and preload for a variable in an AutoLoad script, if the loading is done at the top (outside of any function)? Either way it gets loaded immediately, right?
