### ISSUE TITLE
Area - area collisions regression

### ISSUE THREAD

**Issue by lawnjelly** [godotengine/godot#58555]
### Godot version

3.5 after templated BVH

### System information

All

### Issue description

Create two areas, make one monitoring, and one monitorable. If you move them the areas across each other, this would detect a collision in all builds up to #55640.

This is a regression me and @pouleyKetchoupp missed when implementing #55640 . I originally wanted the static / area tree to also collide test against everything (flags set to 3) but pouley wanted to keep it as non-colliding (set to 0). This ended up causing a regression here.

This is formalising the bug earlier found by @KoBeWi (pers.comm.).

### Steps to reproduce

As above and below.

### Minimal reproduction project

Run this project in 3.4, or 3.5 beta 1, and you get a message saying the areas have collided. Run it post 3.5 beta 1 after #55640 and you get no message.

[AreaArea_BVHTest.zip](https://github.com/godotengine/godot/files/8146433/AreaArea_BVHTest.zip)

## Fix
This is fixed by #58505 . So we should probably look to merge that or a variation before beta 2 to fix this.

**Comment by akien-mga** [comment]
Fixed by #58557.
