### ISSUE TITLE
Button is rapidly being pressed and unpressed when pressed once

### ISSUE THREAD

**Issue by maksutheam** [godotengine/godot#58564]
### Godot version

3.4.3 (on steam)

### System information

Windows 10, GLES3

### Issue description

When pressing a button once, it will rapidly be pressed and unpressed. I put a simple `if pressed: print("pressed")` script to confirm this.

https://user-images.githubusercontent.com/60304828/155853944-42ec9251-50cb-401d-b142-4f86dcffdd0a.mov

### Steps to reproduce

1. Make a new project
2. Add a button (optional: add a script that prints something when button is pressed)
3. Save and play the scene
4. Press the button

### Minimal reproduction project

[buttonbug.zip](https://github.com/godotengine/godot/files/8147162/buttonbug.zip)

**Comment by Calinou** [comment]
I can't reproduce this on `3.x` 24713a27a (Linux):

https://user-images.githubusercontent.com/180032/155854454-62b443e0-6ff9-4c5d-9721-6d9a0f115337.mp4

**Comment by maksutheam** [comment]
My sincerest apologies, it seems that the "bug" was caused by my Nintendo-controller that was placed face down on the table. I unplugged it in and out, and tested it out with some other projects, and confirmed that this was the issue.

I am very sorry for wasting your time. Next time, I will troubleshoot more thoroughly before making a bug report.
