### ISSUE TITLE
AudioStream2D and AudioStream3D playing doesn't change immediately

### ISSUE THREAD

**Issue by aXu-AP** [godotengine/godot#58560]
### Godot version

v4.0.alpha3.official [256069eaf]

### System information

Windows 10

### Issue description

When playing sound from AudioStreamPlayer2D or 3D, playing property doesn't update immediately. I noticed this when I tried to use my sfx pooling system. If 2 sounds were triggered on same frame, only one would play, since pool checks if a stream is not playing and then uses that stream.

The problem doesn't occur on 3.4.2 so this is a regression.

AudioStreamPlayer doesn't have the same problem.

### Steps to reproduce

```
extends Node

func _ready() -> void:
	var s = AudioStreamPlayer2D.new()
	add_child(s)
	s.stream = load("res://test.wav")
	s.play()
	assert(s.playing)
```
Place in a project that has some sound file in it.

### Minimal reproduction project

[AudioPlayingTest.zip](https://github.com/godotengine/godot/files/9494462/AudioPlayingTest.zip)

**Comment by KoBeWi** [comment]
It might be intended that playing the audio is deferred, but `playing` property could probably update right away.

**Comment by Mickeon** [comment]
I don't think this happens anymore, at least in 4.0?
![image](https://user-images.githubusercontent.com/66727710/188477019-07978486-0d38-46bb-9be0-085cc6ab41da.png)
![image](https://user-images.githubusercontent.com/66727710/188477046-06690da1-3360-404e-bf0c-baac94a810fd.png)

**Comment by aXu-AP** [comment]
Interesting. I tested in v4.0.alpha15.official [432b25d36], still fails.

**Comment by Mickeon** [comment]
Can you link to a small minimal project reproducing this bug?

**Comment by aXu-AP** [comment]
Oh, I didn't see your edit. I added minimal project to op if it's anything worth :'D
