### ISSUE TITLE
redo [Ctrl+y] does not auto repeat in script editor

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#5856]
**Operating system or device - Godot version:**
official 2.1-beta 20160721

**Issue description** (what happened, and what was expected):

When you keep pressing [Ctrl+Z] to undo, it has key-repeat.

When you keep pressing [Ctrl+Y] to redo, key-repeat does not work, and you have to release and press [Ctrl+Y] several time.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by akien-mga** [comment]
Is this still valid in the current master branch? Sounds easy to fix.

**Comment by Paulb23** [comment]
This one can be closed, superseded by #10596 fixed by #10600
