### ISSUE TITLE
GDScript 2.0 Methods' argument autocomplete for variables doesn't popup

### ISSUE THREAD

**Issue by stephen-berry** [godotengine/godot#58561]
### Godot version

v4.0.alpha.calinou [0393057e3]

### System information

Windows 11

### Issue description

Basically, it seems that we have popups which indicate what our parameters are for our method we are calling is like this:
![image](https://user-images.githubusercontent.com/24625454/155849729-b1351222-7fe0-4e50-9cd4-9c1ab5dd3519.png)

but when you start typing, I expect it to also allow me to autocomplete with my existing variables and such, as it does normally like this:
![image](https://user-images.githubusercontent.com/24625454/155849776-5932db87-560c-48c0-8a1f-8eb4e6144ea0.png)

But it won't if I'm typing it inside a method
![image](https://user-images.githubusercontent.com/24625454/155849802-80afc0f9-bbf2-49b3-a15b-837b6198f821.png)

### Steps to reproduce

Steps shown above. This can be done with any function requiring parameters.

### Minimal reproduction project

No need for a reproduction.

*Bugsquad edit (keywords for easier searching): autocompletion*

**Comment by KoBeWi** [comment]
Can confirm this in 6d5d9dd

**Comment by KoBeWi** [comment]
Doesn't seem fixed, at least not fully:
![godot_LMRMlhkEhp](https://user-images.githubusercontent.com/2223172/193430120-a890d971-de93-4097-9202-999c20a1819d.gif)
Using e69b7083d
