### ISSUE TITLE
Godot 4.0: CharacterBody simple movement script template not executing the jump code while pressing multiple arrow keys.

### ISSUE THREAD

**Issue by yosoyfreeman** [godotengine/godot#58572]
### Godot version

Godot 4.0, all versions

### System information

Linux mint, vulkan

### Issue description

While using the simple movement script template, the jump code will not work if you press two arrow keys, with the exception of up + right. Any other combination will stop that piece of the code from activating,

### Steps to reproduce

-Create a simple mesh with a collision shape as floor.
-Add a character body with a capsule collision shape.
-Add the simple movement template script.
-try to jump while pressing down + left (for example)

### Minimal reproduction project

[Example template.zip](https://github.com/godotengine/godot/files/8147401/Example.template.zip)

**Comment by Zireael07** [comment]
Google "keyboard ghosting".

Not a Godot issue

**Comment by Chaosus** [comment]
Indeed, I suggest getting a mechanical keyboard that does not have ghosting.

**Comment by yosoyfreeman** [comment]
> 
Yes, you are right. however, i think that the template is a good example about how the CharacterBody works and it would be great that it have the expected behavior.  In this case, getting the key code of W,A,S,D and space bar would work better out of the box in most cases.

**Comment by Chaosus** [comment]
I think it's simply impossible to physically register the input events (after several buttons are pressed) for the keyboard with ghosting.

**Comment by yosoyfreeman** [comment]
Thank you. both changing the input handling to key codes or adding a comment on the template indicating that the setup possible with the native named inputs may results in problems due to ghosting. Here is a detailed explanation: https://www.microsoft.com/applied-sciences/projects/anti-ghosting 

and this part refers to the "zone" system in keyboards to allow usual key combinations: 

```
 An easy change that keyboard makers utilize is to rearrange the wires such that important key combinations don’t exhibit this problem.  However, all this does is move the problems to other sets of keys, where the user is less likely to notice.

Another possibility is to add extra wires to create more unambiguous cases.  However, this is more expensive as more circuitry is needed to read the extra wires. 
```

**Comment by Zireael07** [comment]
Yes, you're right that the occurrence of ghosting often depends on WHICH keys are pressed.

Unfortunately, the arrows (or WASD) and space for jump are very ingrained in people, as they date back to ZX Spectrum or something like that. So while the template _could_ be changed to work around the issue, there is still no guarantee the ghosting would not happen on some other keyboard/computer setup AND people would have to work against their muscle memory. Not worth it imho

**Comment by KoBeWi** [comment]
The template uses the default `ui_` actions, so it can't be changed to WSAD.
