### ISSUE TITLE
Anchor Big Tiles?

### ISSUE THREAD

**Issue by rakkarage** [godotengine/godot#58574]
### Godot version

v4.0.alpha3

### System information

Windows 10

### Issue description

[![Untitled.png](https://i.postimg.cc/2yYJh2Wj/Untitled.png)](https://postimg.cc/9RxJjP1s)

Is there some way to set the anchor of Big Tiles? I created these three big tiles and they are anchored to center (0.5, 0.5) when they need to be anchored to bottom (0.5, 0.75)?

Please and thanks.

### Steps to reproduce

- attempt to anchor a big tile

**Comment by KoBeWi** [comment]
There's a `texture_offset` property under Rendering tab.

**Comment by rakkarage** [comment]
Thanks! Sorry.
