### ISSUE TITLE
LOD causes bones skinning errors with GLTF import

### ISSUE THREAD

**Issue by yosoyfreeman** [godotengine/godot#58570]
### Godot version

4.0, all versions

### System information

Linux mint, vulkan

### Issue description

When you import a skinned mesh it will not show the last bone and the bone information is missing too. In older versions of godot, the last bones was not show in the editor but the bone worked correctly. Now, it only works on the importing view, but will not work at all in the editor, missing all the bone information as is shown below:

The model on the 3D importer, working right:
![imagen](https://user-images.githubusercontent.com/64601424/155856011-df407902-12f2-4b7e-b598-b06b0d7efb76.png)

The model on the editor: all info about the last bone is missing:
![imagen](https://user-images.githubusercontent.com/64601424/155856042-79451d9f-1cad-4411-a033-932a6764008d.png)

### Steps to reproduce

Import any kind of skinned mesh in .glb format.

### Minimal reproduction project

[Example.tar.gz](https://github.com/godotengine/godot/files/8147331/Example.tar.gz)

**Comment by fire** [comment]
Seems to be related to LOD.

![Screenshot 2022-02-26 at 12-16-11 glTF Viewer](https://user-images.githubusercontent.com/32321/155857828-cdd0124d-1391-4f5e-a2e8-e08d1c0a1b88.png)

![editor_screenshot_2022-02-26T121701](https://user-images.githubusercontent.com/32321/155857845-b130bbda-7662-40a4-ba85-728fee9a60a4.png)

**Comment by fire** [comment]
One can design something similar to https://github.com/godotengine/godot/pull/58548 but for bone id, but I'll be away for the first week of March.

The idea is to check bone similarity.

**Comment by fire** [comment]
Going to pause on this, I would try to subdivide a few times, the lod algorithm in other reports doesn't handle low poly and you don't need auto-lod on low poly.

**Comment by fire** [comment]
I think this issue is still valid in the latest godot 4 master. Can anyone else confirm?

**Comment by yosoyfreeman** [comment]
Yes, there is no option for preventing the LOD system to not reduce 
bones.

**Comment by fire** [comment]
I believe this is fixed by https://github.com/godotengine/godot/pull/65493

**Comment by akien-mga** [comment]
Tested in current `master`, this is fixed indeed.

Original scene (preimported) from the MRP:
![image](https://user-images.githubusercontent.com/4701338/191915724-94317046-e793-4ca4-b664-0676e2faad46.png)

New scene after reimporting:
![image](https://user-images.githubusercontent.com/4701338/191915778-945b5705-6a00-4896-af2e-fd00fd5e1886.png)
