### ISSUE TITLE
GDScript 2.0: Can't use `not` operator (`!`) with `String`, `Dictionary`, or `Array` unless `const`

### ISSUE THREAD

**Issue by Error7Studios** [godotengine/godot#58579]
### Godot version

4.0 alpha 3

### System information

Windows 10

### Issue description

In `Godot 4`, empty `String`, `Array`, and `Dictionary` values convert to `true` booleans, unlike `Godot 3`.
Is this intended?

Also, you can no longer use `not`/`!` in front of said values, unless they're saved into a `const`.

### Steps to reproduce

```gdscript
extends Node

const VALUE = {}

func _ready():
	var val = VALUE				# Error
#	var val := VALUE			# Error (static type)
#	const val = VALUE			# OK
#	const val := VALUE			# OK (static type)
	
	if !val:
		print(val, " is falsy")
	else:
		print(val, " is truthy")
```
### Minimal reproduction project

[Godot4 NOT Operator.zip](https://github.com/godotengine/godot/files/8147877/Godot4.NOT.Operator.zip)

**Comment by dalexeev** [comment]
> ```gdscript
> #	const val = VALUE			# OK
> #	const val := VALUE			# OK (static type)
> ```

In RC 1, all 4 options give the same error (`Invalid operand of type "Dictionary" for unary operator "not".`).

**Comment by YuriSizov** [comment]
Also all 3 types have a method to explicitly test for emptiness that should be used.

**Comment by decree** [comment]
So this is intended behaviour and not a bug?

As i'm porting my old Godot 3.5 project to Godot 4, i have tons of `if not <string>` or `if not <dictionary>` checks which now result to an error. I think the old 3.5 way to do a simple `if not x` was an effective and clean way to check things, because it worked with any variable without or with typing.

**Comment by FilipLundby** [comment]
If this is about consistency, I'm curious why it's allow to test on strings as long you do not use `!` and `not`. For instance in C# `if ("hello world") ...` is not allowed, while in JavaScript you can do both `if ("hello world") ...` and `if (!"hello world") ...`.

	# Prints "A"
	if "Go-dot, or go home":
		print("A")
	else:
		print("B")

	# Prints "B"
	if "":
		print("A")
	else:
		print("B")

	# Invalid operand of type "String" for unary operator "not".
	if !"": 
		print("A")
	else:
		print("B")

To me this seems inconsistent.

Godot 4.0 RC 5

**Comment by Lippanon** [comment]
I also agree it seems inconsistent to allow:
```gdscript
var example_dict :Dictionary = {}
if example_dict:
	pass
```
But not allow `not example_dict`. I use the example above to check the result of `intersect_ray` frequently and finding out I can't check its negation like that made me question if the example above can result in undefined behavior.
