### ISSUE TITLE
(4.0) Exporting your project to HTML or .exe does not work at all...

### ISSUE THREAD

**Issue by seppoday** [godotengine/godot#58573]
### Godot version

4.0 alpha 3

### System information

Windows 10

### Issue description

I've installed template package from tuxfamily.org but Godot does not see html template (it probably does not exist?) and also when I export to .exe my game does not start... 

![explorer_alqO0KRIYT](https://user-images.githubusercontent.com/62170071/155858222-164bf395-bdba-4ad6-b237-eeaf76ab9b87.gif)

![Godot_v4 0-alpha1_win64_bm2kiObeaJ](https://user-images.githubusercontent.com/62170071/155858216-d09d4b02-12ed-494c-893a-2856d6d29dc0.png)
![Godot_v4 0-alpha1_win64_b3t88YFZPP](https://user-images.githubusercontent.com/62170071/155858217-d468f5c1-dce0-4fd8-996c-e350a4e95645.png)

### Steps to reproduce

Hard to tell. Try to export game from zip file below.

### Minimal reproduction project

[Brackeys-Hame-JAm-2022-1.zip](https://github.com/godotengine/godot/files/8147462/Brackeys-Hame-JAm-2022-1.zip)

**Comment by Calinou** [comment]
@seppoday Did you manage to find a solution for this? If so, please document it here by leaving a comment :slightly_smiling_face:

**Comment by souplamp** [comment]
For anyone looking this up like me, HTML export is not supported in Godot 4 (_yet_).

[Calinou explains why](https://godotengine.org/qa/129054/godot-4-html5-webassembly-export):
> ...the OpenGL renderer (required for WebGL) isn't finished yet. WebGPU is far from being finalized, which means it'll be years until the Vulkan renderer can run in HTML5 in some form...

As for Windows executables, I have not run into the same problem; I am using Godot 4 (alpha 4) though, so that might have something to do with it.

**Comment by seppoday** [comment]
> For anyone looking this up like me, HTML export is not supported in Godot 4 (_yet_).
> 
> [Calinou explains why](https://godotengine.org/qa/129054/godot-4-html5-webassembly-export):
> 
> > ...the OpenGL renderer (required for WebGL) isn't finished yet. WebGPU is far from being finalized, which means it'll be years until the Vulkan renderer can run in HTML5 in some form...
> 
> As for Windows executables, I have not run into the same problem; I am using Godot 4 (alpha 4) though, so that might have something to do with it.
> 
> **EDIT:** I think the issue here was the export template itself. seppoday listed they were working with alpha3, but were using the alpha1 export template. If anyone is having the same issue, you can download any Godot 4 alpha version export template from [here](https://downloads.tuxfamily.org/godotengine/4.0/), or through the editor itself.

I tryied alpha 1 and alpha 2 and alpha 3 to export my project. That's why template is listed there. I was using appropriate template. I still don't know what was the problem :)

**Comment by Calinou** [comment]
> Also, am I understanding it correctly that Godot 4 probably won't have HTML export support for a long time, even years? Maybe even not in version 4 but in later versions (5+)?

We can't guarantee that 4.0 will have a working HTML5 export available, but this will likely be done by the time 4.1 is released.

**Comment by souplamp** [comment]
> I tried alpha 1 and alpha 2 and alpha 3 to export my project. That's why the template is listed there. I was using the appropriate template. I still don't know what was (or still is) the problem :)

Oh that makes sense, I'm not sure then. I've been using alpha 4 without export problems, so hopefully whatever caused that was incidentally fixed.
