### ISSUE TITLE
Triplanar sharpness > 180 causes visual glitch

### ISSUE THREAD

**Issue by josefkaragoli** [godotengine/godot#58587]
### Godot version

v4.0.alpha3.official

### System information

Windows 10, Vulkan, Realtek Audio

### Issue description

In a StandardMaterial3D resource, setting triplanar sharpness to anything past 180 degrees causes weird visual glitches - it should be clamped to 180 degrees because it doesn't really make sense for the sharpness to ever be > 180 degrees.
Normal triplanar value:
![image](https://user-images.githubusercontent.com/76781125/155877116-fd93ccb7-4932-4b60-9865-94a2186952e9.png)
Above 180:
![image](https://user-images.githubusercontent.com/76781125/155877095-da0085f1-6bf6-40ad-9a22-93c9c2408fe2.png)

### Steps to reproduce

Create a MeshInstance3D. Add a StandardMaterial3D to its Surface Material Override. Go to UV1 in the material and enable the Triplanar checkbox. Set triplanar sharpness to anything more than 180 and observe the mesh. Should look distorted.

**Comment by josefkaragoli** [comment]
This also happens in previous versions, I tested it in 3.4.3 and the same happened

**Comment by Calinou** [comment]
I can confirm this on `master` 0393057e3. Depending on the mesh, it's possible to notice NaNs being emitted with sharpness values as low as 50. Personally, I'd clamp the upper triplanar value to 50 internally. (It can't be clamped in the inspector as exponential curve editors don't support custom minimum/maximum values.)
