### ISSUE TITLE
Android Portrait Orientation Is Broken

### ISSUE THREAD

**Issue by josephcantrell14** [godotengine/godot#58584]
### Godot version

3.4.3

### System information

Android 9

### Issue description

Portrait orientation does not work in exported Android applications.  I tried to export a build of my application to Android using Godot 3.4.3, and I tried to force the exported application to use the portrait orientation.  I tried setting the Project->Window orientation to portrait and sensor-portrait, but this did not work.  I tried using multiple portrait resolutions in the same Project->Window settings.  I modified the stretch mode.  
To no avail, in the Export->Android settings, I tried disabling immersive mode, disabling classify as game, and enabling the Set Screen Orientation permission.

### Steps to reproduce

I followed this official Godot Docs guide for enabling portrait: https://docs.godotengine.org/en/stable/tutorials/rendering/multiple_resolutions.html#mobile-game-in-portrait-mode

Set the base window width to 720 and window height to 1080.
Set Display > Window > Handheld > Orientation to portrait.
Set the stretch mode to 2d.
Set the stretch aspect to expand. This allows for supporting multiple aspect ratios and makes better use of tall smartphone displays (such as 18:9 or 19:9 aspect ratios).

### Minimal reproduction project

My full project source code, a timer and stopwatch application called Speed Timer, is here: https://github.com/josephcantrell14/SpeedTimer

**Comment by allkhor** [comment]
Can't reproduce on android 11.
Please upload MRP.
Good point about MRP wrote @lawnjelly https://github.com/lawnjelly/Misc/blob/master/MRP.md

**Comment by josephcantrell14** [comment]
I fixed it by clearing my app data.  So, I followed the Godot docs listed above, cleared my app data, and THEN reinstalled.  Thanks for the inspiration!
