### ISSUE TITLE
Rendering problems on intel graphics with acceleration method "sna"

### ISSUE THREAD

**Issue by abitofbyte** [godotengine/godot#5858]
A lot of sprites cause screen to flicker in fullscreen mode. Everything seems to be normal in window mode. Also everything seems to be normal with acceleration method set to "uxa" in xorg.conf. Looks like intel driver overrides vsync parameter causing screen to flicker, even when "TearFree" parameter is disabled in xorg.conf. It turns into a problem since "sna" acceleration method is default by intel driver. The bug was tested on two computers with intel graphics on different linux distros.

Tested on: Linux - Godot v2.1 beta

GPU: Intel® HD Graphics 4600

Example project: [Sprites Flicker Test.zip](https://github.com/godotengine/godot/files/378409/Sprites.Flicker.Test.zip)

**Comment by SuperUserNameMan** [comment]
Does improve if you change your vsync parameter in your graphics drivers and in godot's project setting use_vsync ?

On my radeon, I notice screen flicker only when use_vsync is off. (and set to "let application decide" in the driver)

**Comment by abitofbyte** [comment]
@SuperUserNameMan I have use_vsync parameter on by default.

**Comment by abitofbyte** [comment]
Also I get the same results with use_vsync turned off.

**Comment by SuperUserNameMan** [comment]
It's hard to diagnose without seeing it, because the "flickering" could be related to many things :

- the Intel graphics driver could override the vsync parameters of the game to try to gain some performance.

- there could be some sort of optical illusion due to the fact that you use the same sprite.

- the quality of your display could causes some visual artifacts when contrasted image is moving.

**Comment by abitofbyte** [comment]
@SuperUserNameMan Hmm... I haven't notice any screen flicker running the project with optirun. Then it might be intel driver problem...

**Comment by zaps166** [comment]
Do you use compositing (if yes - which WM)? Do you use "TripleBuffer" in xorg.conf? Which FPS do you have at runtime (use "print_fps")?

What "screen flicker" exactly means? Lower framerate (e.g. visually 30FPS) which can look like "screen flicker" on the example? Or screen tearing (which can happen on SNA even if vsync is enabled and it locks to refresh rate especially on video players)?

Actually I can't reproduce screen flicker on SNA (compisiting disabled, vsync on, DRI2, xf86-video-intel 1:2.99.917+662+gb617f80-1, xorg-server 1.17.4).

---

I think that UXA is better - SNA has problems with screen tearing on some OpenGL apps (e.g. my QMPlay2 even on VA-API or VLC) w/o compositing :smile:

**Comment by abitofbyte** [comment]
@zaps166 I didn't have "TripleBuffer" parameter in my xorg.conf. use_vsync was enabled, so I think the framerate was ~60 fps.

**Comment by abitofbyte** [comment]
Looks like flicker issue is gone. I wonder why... Anyway, closing the issue.
