### ISSUE TITLE
Project Settings window does not appear and locks Godot if it was on secondary screen and then used in a one screen setup (DisplayServer regression)

### ISSUE THREAD

**Issue by MisfitVillage** [godotengine/godot#58591]
### Godot version

4.0.alpha3

### System information

Windows 10, RTX3070 laptop, Vulkan

### Issue description

If you have the Project Settings window dragged to a secondary monitor and exit Godot, later if you open Godot on a one monitor setup there's no way to get into the Project Settings or exit the Project Settings window after you open it so you can't continue using Godot without killing it with the task manager and you can't change any of your project settings until you plug a secondary monitor back in. The Project Settings window probably tries to appear on the location it appeared last, but can't because there's no secondary screen so it just doesn't appear at all and locks you out of using Godot.

The Project Settings window should default to showing on the center of the main screen if no additional screens are detected. I also propose making the Project Settings window not disable interaction with the main Godot window. For instance if you want the project settings window to always be open on a secondary monitor but still be able to work on your project.

### Steps to reproduce

have a dual monitor setup
open Godot
open Project Settings window
drag it to secondary monitor
close Godot
unplug secondary monitor
open Godot
open Project Settings window
can't use Godot anymore, must close through Task Manager

**Comment by Calinou** [comment]
> I also propose making the Project Settings window not disable interaction with the main Godot window. For instance if you want the project settings window to always be open on a secondary monitor but still be able to work on your project.

This is due to the popup having an `exclusive` flag, but I remember there being a reason for this.

**Comment by thebardsrc** [comment]
I can confirm with Alpha 13 that this still happens. Trying on my laptop to open Project Settings and Editor Settings both and they were locking up, and after finding this bug I went and connected my laptop to the docking station where I have a larger screen, and both settings windows were opening just fine in their positions on the larger screen that are outside of the laptop's resolution

**Comment by JanneKilpi** [comment]
I have a similar problem and have to stop using Godot 4.0.3 because I can't open the project settings anymore. Now I have to switch to the old 3 version.

I have three monitors. The main screen is a 32' 4k screen and the two support screens are 28' FullHD screens. I did a course on Udemy and moved the project settings support screen and then it stopped working.

I used Unity for a while and found it too difficult. It was nice to find Godot because it is much easier to use than Unity.

Any chance of getting Godot 4 working? Thanks everybody.

**Comment by JanneKilpi** [comment]
This is the downside of Open Source. You try to get help for half a year and no one tries to help. I tried to buy a Fiverr professional, but no one dares to even try.

I downloaded 4.2 and the same problem persists. Maybe in half a year someone will know?

**Comment by EtiTheSpirit** [comment]
Hey! I just ran into this issue @JanneKilpi 

You can manually fix it by going into the `(PROJECT)/.godot/editor` folder and editing `project_metadata.cfg`. There is a category `[dialog_bounds]` that contains all the positions and sizes of relevant windows, including the project settings menu.
