### ISSUE TITLE
Pause breaks collisions.

### ISSUE THREAD

**Issue by SpectralniyRus** [godotengine/godot#58602]
### Godot version

3.4.3 stable

### System information

Windows 10 LTSC compact, GTX950M, I5-7200U

### Issue description

Let's say you have Player and Spikes nodes, and when they collide, the Player executes the die() method.

The problem is, If you make them collide to each other, stop the game at the same frame, then move the player out of the spikes, then unpause the game, the die() method still executes, despite that Player doesn't collide with spikes anymore.

Essentially the "area_entered" signal just delays until you unpause the game, instead of executing, or just not doing anything.

https://user-images.githubusercontent.com/90066356/155894594-0a6cd3d6-1b12-4c30-9bec-b70b7d694be7.mp4

### Steps to reproduce

1) Make a simple KinematicBody2D node (player), give it a simple moving system, set its pause mode to "process". 

2) Give the player an Area2D node. Connect the "body entered" signal from it to the player, and attach some method to it (die() for instance).

3) Create a new body (spikes), give it an area2D, and set the collision layer so that it can collide with the Player's area2D

4) Make a pause node, that pauses the scene tree when a button is pressed.

5) Launch the game. Press the pause button at the same frame when the Player collides with the spikes.

6) Move Player to the side, so that it doesn't collide with the spikes anymore

7) Unpause the game. Logically the player shouldn't die, since it doesn't collide with the spikes anymore, but it still dies for some reason.

### Minimal reproduction project

I cannot upload zip file for some reason. I uploaded it on [Google drive](https://drive.google.com/file/d/1z_bCywzq4I1k76Ff__lNQm6t47-KnEsC/view?usp=sharing) instead.

**Comment by Calinou** [comment]
> I cannot upload zip file for some reason. I uploaded it on [Google drive](https://drive.google.com/file/d/1z_bCywzq4I1k76Ff__lNQm6t47-KnEsC/view?usp=sharing) instead.

This is because the MRP weighs more than 10 MB, and is therefore unlikely to be a *minimal* reproduction project :slightly_smiling_face:

**Comment by SpectralniyRus** [comment]
> > I cannot upload zip file for some reason. I uploaded it on [Google drive](https://drive.google.com/file/d/1z_bCywzq4I1k76Ff__lNQm6t47-KnEsC/view?usp=sharing) instead.
> 
> This is because the MRP weighs more than 10 MB, and is therefore unlikely to be a _minimal_ reproduction project 🙂 GitHub only allows uploading attachments up to 10 MB each.

My bad. Should i reupload it?

**Comment by Calinou** [comment]
> My bad. Should I reupload it?

It would be best to create a truly minimal reproduction project that weighs less than 10 MB, so you can upload it as an attachment. Google Drive links may stop working for various reasons in the future, but GitHub attachment links are very unlikely to stop working in the future.

**Comment by SpectralniyRus** [comment]
[For debugging.zip](https://github.com/godotengine/godot/files/8149261/For.debugging.zip)

I hope it works now.

**Comment by SpectralniyRus** [comment]
[For debugging.zip](https://github.com/godotengine/godot/files/8149273/For.debugging.zip)

I hope it works now

**Comment by Sauermann** [comment]
I was able to reproduce the described behavior.

The player is about to fall into spikes and even touched the spikes, which means, that he should die. You expect, that he should be able to circumvent the death by using pause to move the character out of the danger zone.
To me the concept "move the player, while the game is paused" feels like cheating.

**Comment by SpectralniyRus** [comment]
"move the player, while the game is paused" is the core concept of my game. The movement mechanic is different from the minimal reproduction project that I sent you, but still similar. 

I'd want player to die immediately, without being able to pause the game, because dying after you "avoided" the spikes feels unfair, and simply annoying. 

Being able to avoid death by pausing the game will work as well. I just don't want the Player to feel that they died when spikes were nowhere nearby.

**Comment by Calinou** [comment]
You could use a very low `Engine.time_scale` value like `0.01` or `0.001` instead of pausing to make sure collisions are still processed as usual.

**Comment by SpectralniyRus** [comment]
It doesn't work. I need to keep the Player's speed at normal. The only way to do it with time_scale is by multiplying the player's speed by 1/time_scale, which messes up movement (The player's speed doesn't drop when he collides with walls).

**Comment by gabu0** [comment]
If I recall correctly, this is due to the fact collisions are all processed at once, most likely before any other code runs (though don't take my word for it, I'm not an expert by any means when it comes to physics). This would mean what happens is: 
1. You move
2. Collisions are processed
3. You pause
4. Your pause code is executed before the collision response of the Area2D

One way to get around this should be executing the pause code a frame after the pause button is pressed, and in the frame it is pressed you clear the player's collision layer bit with the spikes so it is disabled the next frame.
It should also work if you make the player area detect the spikes instead and zero the collision mask bit.

**Comment by SpectralniyRus** [comment]
IT WORKS! :D yey! Huge thanks to everyone who helped me. You saved me.

**Comment by Zireael07** [comment]
Whoa, @gabu0, that's a nice trick! (Hopefully it gets documented somewhere more stable than GH issues)

**Comment by Calinou** [comment]
> Whoa, @gabu0, that's a nice trick! (Hopefully it gets documented somewhere more stable than GH issues)

Where do you think this should be documented? I'm not sure if we can document this in a generic manner.

**Comment by SpectralniyRus** [comment]
> Either under physics, or under pause (as a tip). I'd lean towards the latter

Agreed
