### ISSUE TITLE
Vulkan: PointLight2D shadows vary depending on light rotation

### ISSUE THREAD

**Issue by Dan-Gamin** [godotengine/godot#58607]
### Godot version

v4.0-alpha3

### System information

Windows 10 64-bit, GPU: NVIDIA Geforce GTX 1650 Ti, CPU: AMD Ryzen 7 4800H

### Issue description

I have been trying to improve my games graphics. I added a pointlight to my player. But the shadows were doing weird things. It turns out the shadows are directional. Despite I'm using a pointlight.
Rotated 00 Degrees:
![image](https://user-images.githubusercontent.com/58695417/155899481-be03b7f7-6d2f-49d4-82da-4173534f7fe7.png)
Rotated 90 Degrees:
![image](https://user-images.githubusercontent.com/58695417/155899438-1d37f9f7-355e-4d7e-89d5-204a89a82d64.png)
Editor view:
![image](https://user-images.githubusercontent.com/58695417/155899495-6310f6ae-0d38-4935-9cff-2adf37924a8e.png)

### Steps to reproduce

Use a spotlight with shadows and occluders. See above for more information.

**Comment by Calinou** [comment]
@Dan-Gamin Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.
