### ISSUE TITLE
Weird issues with editor that go away after Alt Tabbing

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#58609]
### Godot version

3fab862

### System information

W10

### Issue description

Since around alpha 2 the editor seems haunted or something. There are few issues that appear randomly and go away as soon as you switch to another window. I never tested if they are really related, but they are all random and get "fixed" the same way. The issues I spotted so far are:
- drag and dropping items in Tree nodes (scene tree/filesystem docks) doesn't show drop preview
- TileMap editor doesn't display ghost tiles (previews) and is glitchy (similar to #24970, but permanently, i.e. lines are drawn with each click)
- script editor doesn't change cursor to IBEAM unless dragging
- tooltips don't appear
- scene tabs stop working, i.e. you can't switch them and middle-click will not delete them
- popup menus stop working (can't click on a toolbar to open menu) and main window becomes "unresponsive", i.e. can't minimize or close it
- hovered button style stops working (as if buttons stopped reacting to hover)
- can't edit collision bits in the inspector

### Steps to reproduce

~~No idea, happens randomly when using editor. Might have something to do with switching between different applications/windows or with dialogs.~~
See https://github.com/godotengine/godot/issues/58609#issuecomment-1152359161

**Comment by djmaesen** [comment]
same weird unresponsive ieditor ssues in godot alpha 4. dont know whats causing it

**Comment by bfeber** [comment]
I think I know one cause for this. Entering something in the inspector's text fields causes the tooltips to not appear until you switch windows!

**Comment by GuidoRevers** [comment]
On my system I can reliably reproduce the bug by clicking Scene -> Save Scene .
One work around to fix it is to manually select a Tile Map Layer to draw on.

**Comment by KoBeWi** [comment]
Ok a reliable way to reproduce this was finally found:

https://user-images.githubusercontent.com/91982860/172355726-f592a73f-e41f-4460-8c82-710be939c6d9.mp4

(this is from #61773)

It may by triggered by other things too, like tooltips, but this one seems to always cause the issue.
