### ISSUE TITLE
HTTPRequest CORS header error on HTML5

### ISSUE THREAD

**Issue by nKatsuhira** [godotengine/godot#58615]
### Godot version

3.4.3.stable only (3.4.2 works fine)

### System information

PopOS 21.10 (Based on Ubuntu 21.10), GLES2 & GLES3, Ryzen 5 5600X, RTX 3060 510.54

### Issue description

System information is very likely not relevant. Multiple people (friends and godot discord) tested it on their machines.

On HTML5 (Debug and Export), the HTTPRequest node encounters a `CORS request did not succeed` or `credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’` with seemingly no way around it, very likely caused by [#57934](https://github.com/godotengine/godot/pull/57934). Works perfectly fine on every other export.

I wanted to get a .JSON from my repo [ThankYou.json](https://raw.githubusercontent.com/nKatsuhira/ThankYou/main/ThankYou.json) and parse it.

### Steps to reproduce

1. Create HTTPRequest and do the bare minimum setup (request and connect request_completed signal)
2. Export or debug in HTML5 on any browser
3. Do a request [Example](https://raw.githubusercontent.com/nKatsuhira/ThankYou/main/ThankYou.json)

### Minimal reproduction project

[minimal_reproduce.zip](https://github.com/godotengine/godot/files/8149684/minimal_reproduce.zip)

**Comment by nisovin** [comment]
Related information: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials

**Comment by Faless** [comment]
Another amazing web standard, we'll need to revert #57934 .

**Comment by aleksfadini** [comment]
I am having this problem as well with 3.4.3. Will have to downgrade.

**Comment by aleksfadini** [comment]
Wonderful! Thank you

My best,
Alessandro

**Comment by oakmage** [comment]
Is this actually fixed in 3.4.4 stable? I just downloaded that version and tried but still have this issue. Version 3.4.2 worked fine.

**Comment by Calinou** [comment]
@oakmage Please open a new issue with a minimal reproduction project attached.

**Comment by oakmage** [comment]
@Calinou Actually, I found that there's a way to configure the headers for my Firebase project. Going to try that first. Thanks.

**Comment by Tonyruhauf** [comment]
I have the same problem with 4.0.1

**Comment by bloemer** [comment]
Godot 4.1 aswell.
why is the fix not passed on, but shows up in a new release?

**Comment by nisovin** [comment]
> Godot 4.1 aswell. why is the fix not passed on, but shows up in a new release?

Are you sure the problem you're experiencing is related to this specific issue? CORS is a big subject, and this was a pretty specific problem.

**Comment by AThousandShips** [comment]
Please open a new issue as requested above
