### ISSUE TITLE
OpenXR resizing preview windows breaks things

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#58620]
### Godot version

4.0.dev 3fab862c590b706aa5c6211415d3854140dbc5d3

### System information

Windows 10 SteamVR

### Issue description

Resizing the window breaks stuff. 

I think this is the same issue we had on Godot 3 but the fix wasn't applied to Godot 4. Basically the issue is that if you use the main viewport for XR, XR overrides the size of the viewport. Resizing the window in turn tries to undo this override, and things get messy.

The fix we did in Godot 3 was to ensure that once XR mode is turned on on the viewport, we start ignoring resizes. 

### Steps to reproduce

Start an XR project, resize the preview window.

### Minimal reproduction project

https://github.com/BastiaanOlij/godot4_openxr_demo

**Comment by akien-mga** [comment]
Is this still reproducible in 4.0 RC 3 or later?

**Comment by BastiaanOlij** [comment]
As far as I can tell this was resolved a while ago, sorry I forgot to update the status of this. Atleast I can't get it to break and I haven't heard anyone complain about it for a long time.

So closing this.
