### ISSUE TITLE
Godot Wont Open

### ISSUE THREAD

**Issue by kimbunner** [godotengine/godot#58621]
### Godot version

4.0 alpha3

### System information

Windows 10

### Issue description

i have gt 530 gpu
and amd procesor

### Problem

Godot Engine v4.0.alpha3.official.256069eaf - https://godotengine.org
vkEnumerateInstanceVersion not available, assuming Vulkan 1.0.

it does not say i have to upgrade my driver its just stuck

**Comment by kimbunner** [comment]
![Screenshot 2022-02-28 151824](https://user-images.githubusercontent.com/61554370/155940650-dc4de577-ec1b-47b7-aebc-fe03b1b6c3e7.png)
here

**Comment by nonunknown** [comment]
this is related to the driver, not the engine, try updating them 

https://developer.nvidia.com/vulkan-driver

**Comment by Calinou** [comment]
NVIDIA Fermi GPUs do not support Vulkan (updating the driver won't fix that). Until an OpenGL renderer is added to Godot 4.x, you'll have to stick to Godot 3.x.
