### ISSUE TITLE
[4.0] Scripts do not save if you choose to save after closing it in the script editor

### ISSUE THREAD

**Issue by Hakunamawatta** [godotengine/godot#58622]
### Godot version

4.0 (234eb83)

### System information

Linux Mint 20.2

### Issue description

If you close an unsaved script in the script editor and choose to save it, the changes won't persist after closing the project. The changes only persist in the same session presumably because of issue #50578.
I believe the issue relates to [this](https://github.com/godotengine/godot/blob/234eb83dfec6daf3795e53236be7b408083f6a2d/editor/plugins/script_editor_plugin.cpp#L765) line, which chooses to only save built-in scripts on closing (the opposite of what the comment says).

### Steps to reproduce

1. Create a new script file
2. Try to close it
3. Choose to save it when it asks whether you want to discard or save changes.
4. Close to the project list
5. Open the project again
6. Open the script (The changes are gone)

**Comment by Calinou** [comment]
cc @KoBeWi

**Comment by KoBeWi** [comment]
Regression from #50352, the condition should be reversed.
