### ISSUE TITLE
Vulkan Mobile backend: Radiance prefiltering worsens rough reflection quality

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#58631]
### Godot version

4.0.alpha (0393057e3)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 495.46)

### Issue description

Radiance prefiltering looks good on the Vulkan Clustered backend, but it doesn't see the same improvements in the mobile backend (running with desktop default settings). Reverting https://github.com/godotengine/godot/pull/58177 restores filtering quality to what it was before in the Vulkan Mobile backend (although the Real-Time filter mode still exhibits the issue).

### Vulkan Clustered

| High Quality | Real-Time |
|-|-|
| ![2022-02-28_15 41 31](https://user-images.githubusercontent.com/180032/156002878-0238913a-d9bc-4cbb-a463-70b497bfb06d.png) | ![2022-02-28_15 42 37](https://user-images.githubusercontent.com/180032/156002885-aab9bbd5-1e62-4d1d-a773-4248d64ffddf.png) |

### Vulkan Mobile

| High Quality | Real-Time |
|-|-|
| ![2022-02-28_15 43 44](https://user-images.githubusercontent.com/180032/156002888-47da3a8b-801b-4e9e-a55b-cc528fe26a4e.png) | ![2022-02-28_15 43 47](https://user-images.githubusercontent.com/180032/156002892-4496b848-f9de-4d33-88ed-18a4a703362c.png) |

<details><summary>Closeups</summary>

##### High Quality

![2022-02-28_15 44 19](https://user-images.githubusercontent.com/180032/156002894-37eca742-6cf3-48bb-834e-c82ebb5f22ca.png)

##### Real-Time

![2022-02-28_15 44 05](https://user-images.githubusercontent.com/180032/156002893-587add74-be22-492a-a702-1b4072fd7276.png)
</details>

### Vulkan Mobile (with https://github.com/godotengine/godot/pull/58177 reverted)

| High Quality | Real-Time |
|-|-|
| ![2022-02-28_15 48 19](https://user-images.githubusercontent.com/180032/156003517-3a9fc284-1cc9-49ee-8f77-b0d8ea67d2c9.png) | ![2022-02-28_15 48 23](https://user-images.githubusercontent.com/180032/156003525-8dae3ad8-1d50-4031-a93d-bafa929a16f0.png) |

<details><summary>Closeups</summary>

##### High Quality

![2022-02-28_15 48 43](https://user-images.githubusercontent.com/180032/156003527-c1f75c33-6a1e-498a-ba5b-9753d42cd706.png)

##### Real-Time

![2022-02-28_15 48 49](https://user-images.githubusercontent.com/180032/156003528-44699ead-324c-43f2-abff-0c20f45573a4.png)
</details>

### Steps to reproduce

- Use an HDRI panorama sky from a website such as [Poly Haven](https://polyhaven.com/).
- Add meshes with rough materials to the scene.
- Switch to the Vulkan Mobile backend in the project settings (search for `back end`).
- Restart the editor.

### Minimal reproduction project

`tests/3d/test_pbr_radiance_high_quality.tscn` and `tests/3d/test_pbr_radiance_real_time.tscn` in https://github.com/Calinou/godot-rendering-tests

**Comment by clayjohn** [comment]
This may be related to mobile not using the full HDR range. I wonder if your clamping PR (https://github.com/godotengine/godot/pull/58164) would fix this

**Comment by Calinou** [comment]
> This may be related to mobile not using the full HDR range. I wonder if your clamping PR (#58164) would fix this

I tried and the clamping doesn't resolve the issue. This is made more evident by https://github.com/godotengine/godot/issues/67172, which only uses a SDR sky (ProceduralSkyMaterial does not use overbright colors in its default settings).

**Comment by Calinou** [comment]
I checked the minimal reproduction project and can confirm this was fixed by https://github.com/godotengine/godot/pull/68511.

### Forward Clustered

High Quality | Real-Time
-|-
![2022-11-11_21 30 30 webp](https://user-images.githubusercontent.com/180032/201427468-74f5fae7-2249-4e8e-a5f6-70d4ddafdf9f.png) | ![2022-11-11_21 31 35 webp](https://user-images.githubusercontent.com/180032/201427482-3c1ab320-1f6d-4508-b5b0-44f10f0fdeec.png)

### Forward Mobile

High Quality | Real-Time
-|-
![2022-11-11_21 31 04 webp](https://user-images.githubusercontent.com/180032/201427474-8b53fdb7-e852-4e85-bf6c-52eabf734431.png)
![2022-11-11_21 31 48 webp](https://user-images.githubusercontent.com/180032/201427487-e91ca20f-fed5-4a88-8c15-51a6d8db746d.png)
