### ISSUE TITLE
godotengine.org website is unresponsive or shows Internal Server Error

### ISSUE THREAD

**Issue by PeterMarques** [godotengine/godot#58639]
### Godot version

website of the godotengine

### System information

browser

### Issue description

Acessing the https://godotengine.org/ result in a incorrect webpage.
![image](https://user-images.githubusercontent.com/32851924/156045218-65a76b6e-4dfa-4ebc-b31a-9caf4ff363ed.png)

### Steps to reproduce

Acess https://godotengine.org/ in a web-browser.

**Comment by PeterMarques** [comment]
and know it does not load. Maybe it is in the process of being fixed

**Comment by PeterMarques** [comment]
Things getting better 
![image](https://user-images.githubusercontent.com/32851924/156045835-0c26f065-02cf-4ed7-b4d9-95b359b54dcb.png)

**Comment by cybereality** [comment]
I'm able to load the downloads page, but clicking anywhere else doesn't work.

**Comment by Calinou** [comment]
The database is currently experiencing issues, which affects the main website, the Q&A and asset library. It seems to be related to exceeded storage quotas, but this is strange as TuxFamily recently increased our database storage quota allowance.

**Comment by akien-mga** [comment]
See https://www.tuxfamily.org/en/news/2022022800, seems TF has been replacing some failing hard drives a few hours ago.

**Comment by HaSa1002** [comment]
The website doesn't work at all anymore

> Missing vendor files, try running "composer install" or use the Wizard installer.

**Comment by akien-mga** [comment]
We're working on it.

**Comment by Calinou** [comment]
The website should be back up now: https://godotengine.org/
