### ISSUE TITLE
GDScript 2.0: Function not accepting typed Array with custom classes as a parameter

### ISSUE THREAD

**Issue by MrZak-dev** [godotengine/godot#58636]
### Godot version

4.0.alpha3

### System information

Window 10

### Issue description

function not accepting custom classes Typed Array as a parameter

### Steps to reproduce

1- Create custom class

**SimpleClass.gd**
```python
class_name SimpleClass

var name

```

2- Create a function that accept 1 param as an array of `SimpleClass`

SomeScript.gd
```python 

func _ready() -> void:
    var simple_class_instance : SimpleClass = SimpleClass.new()
   
    get_array_of_class([simple_class_instance ])

func get_array_of_class(classes : Array[SimpleClass]) -> void:
    print(classes)    
```

You will get an error described as `Cannot convert argument 1 from Array to Array`

**Comment by Verthae** [comment]
This seems to exhibit the same behavior as if you were to send a generic array to a typed array:
```gdscript
func _ready():
  var ary = [1, 2, 3]
  test_func(ary)

func test_func(my_ary : Array[int]):
  print(my_ary)
```
`Cannot convert argument 1 from Array to Array`

I did double check and confirmed that even if you make a variable that is statically typed to `Array[SimpleClass]` it still throws this same error, as if the class isn't properly applying the static typing.

What's interesting -
```gdscript
func _ready():
	var ary1 : Array[String] = ["1", "2"]
	var ary2 : Array[RandoClass] = [RandoClass.new()]
	ary1.append(3)
	ary2.append("245")
	print("Array[String] : ", ary1)
	print("Array[RandoClass] : ", ary2)
```
Output: 
Array[String] : [1, 2]
Array[RandoClass] : [[Node:21206401412], 245]

The Array[String] is properly enforcing the static typing, not allowing an `int` to be appended
The Array[RandoClass] however is failing to enforce this static typing, allowing a `String` to be appended

A type mismatch would bring up an error about an invalid argument before even running the code:
```gdscript
func _ready():
  var ary: Array[int] = [1, 2, 3]
  test_func(ary)

func test_func(my_ary : Array[String]):
  print(my_ary)
```
`Parser Error: Invalid argument for "test_func()" function: argument 1 should be Array[String] but is Array[int].`

**Comment by kleonc** [comment]
Tested in 4.0.beta3+ (040f49ed6e71a6e7f23d763c4b56095cbf319ef7):

> ```python
> func _ready() -> void:
>     var simple_class_instance : SimpleClass = SimpleClass.new()
>    
>     get_array_of_class([simple_class_instance ])
> 
> func get_array_of_class(classes : Array[SimpleClass]) -> void:
>     print(classes)    
> ```
>   
> You will get an error described as Cannot convert argument 1 from Array to Array

Works just fine, no error.

---

> What's interesting -
> 
> ```gdscript
> func _ready():
> 	var ary1 : Array[String] = ["1", "2"]
> 	var ary2 : Array[RandoClass] = [RandoClass.new()]
> 	ary1.append(3)
> 	ary2.append("245")
> 	print("Array[String] : ", ary1)
> 	print("Array[RandoClass] : ", ary2)
> ```
> 
> Output:
>Array[String] : [1, 2]
>Array[RandoClass] : [[Node:21206401412], 245]

No longer the case, the second `append` also fails.

---

> ```gdscript
> func _ready():
>   var ary = [1, 2, 3]
>   test_func(ary)
> 
> func test_func(my_ary : Array[int]):
>   print(my_ary)
> ```
>   
> Cannot convert argument 1 from Array to Array

Still the same error (at runtime).

**Comment by vonagam** [comment]
Okay, since my issue is closed, I guess I'll post here as it is obviously connected.
But mine was specifically about constant aspect of it. What I mean is:

This one will fail, yes:
```gd
func _ready():
  var ary = [1, 2, 3]
  test_func(ary)
```

But this one will not:
```gd
func _ready():
  var ary: Array[int] = [1, 2, 3]
  test_func(ary)
```

But this one will:
```gd
func _ready():
  const ary: Array[int] = [1, 2, 3]
  test_func(ary)
```

**Comment by Cretezy** [comment]
Commenting here with my test case of `map`:

```gdscript
func test(items: Array[int]) -> void: pass

func _ready():
	# Works
	test([1])

	# Doesn't work
	test([1].map(func(x) -> int: x))
```
