### ISSUE TITLE
Room Portal System Duplicates Instantiated Scenes When Saved

### ISSUE THREAD

**Issue by The-Randalorian** [godotengine/godot#58648]
### Godot version

3.4.3

### System information

Windows 10

### Issue description

When using a scene instance within a room, pressing the convert rooms button in the editor will take all of the nodes within the instantiated scene and add them as children to the instantiated scene. If the scene is saved after this, all of these new child nodes will be saved as well, creating duplicated objects. This can be done multiple times, leading to hundreds of duplicate nodes being added as children of the instantiated scene.

Edit: I discovered this only happens when using -room and/or -roomgroup postfixes, like when importing GLBs.

### Steps to reproduce

Instantiate a packed scene inside of a room, convert rooms, and save the current scene. Close and re-open the scene. The contents of the packed scene will now be children of the packed scene instance in the current scene. Converting rooms again and saving will add more duplicated contents.

Edit: You must be using -room and/or -roomgroup postfixes, not the actual room types.

### Minimal reproduction project

[DuplicatingInstancesIssue.zip](https://github.com/godotengine/godot/files/8159172/DuplicatingInstancesIssue.zip)

Edit: added minimal reproduction project.

**Comment by The-Randalorian** [comment]
After attempting to make a minimal reproduction project, I discovered this only happens when using the -room, -roomgroup and other postfixes.

I have added the minimal reproduction project and amended the issue.

**Comment by lawnjelly** [comment]
Just having a first look - it's something to do with it being an instantiated scene, if you make the "SceneBeingIncorrectlyDuplicated" local it works fine. Maybe there are restrictions on deleting / moving nodes within instantiated scenes.

What is happening during the prefix conversion is more complex BTW than regular conversion. It can't directly change the `Spatial` to a `Room`, it has to rename the Spatial, create a Room, then move all the objects across, then delete the original Spatial. It's quite a bit of gymnastics so I'm not totally surprised there are conditions which can muck this up.

Hopefully this should be easy to fix once I've worked it out precisely. :grin:

**Comment by akien-mga** [comment]
Fixed by #58650.
