### ISSUE TITLE
Godot 4: dragging an item from the overflowed variable's members window in Visual Script to the script canvas will move the content inside the window without the user's intention

### ISSUE THREAD

**Issue by kreaninw** [godotengine/godot#58661]
### Godot version

v4.0.alpha3.official [256069eaf]

### System information

Windows 11, Vulkan Clustered, Intel UHD Graphics 620 v30.0.101.1340

### Issue description

Dragging an item from the overflowed variable's members window in Visual Script to the script canvas will move the content inside the window without the user's intention, as shown in the screen recording below:

https://user-images.githubusercontent.com/1403194/156239297-6df5ee4d-b19f-47ad-8846-0b47f11b51de.mp4

This issue makes selecting a function or variable becomes very hard, as the beginning of the content (function name or variable name) will move out of the window and becomes unreadable.

This is a regression from Godot 3.4. In Godot 3.4, this does not happen as shown in the screen recording below:

https://user-images.githubusercontent.com/1403194/156240087-f6cf9056-b4b4-46fa-aa60-b0cbe2d15c85.mp4

I expect the side-scrolling to move only when I want it to.

### Steps to reproduce

1. Create a very long variable in Visual Script.
2. Try dragging the variable to the script canvas. The content in the members' window will move by itself without the user's intention.

**Comment by KoBeWi** [comment]
Fixed by #64822
