### ISSUE TITLE
smooth_trimesh_collision missing in project settings

### ISSUE THREAD

**Issue by valknor** [godotengine/godot#58667]
### Godot version

3.4.3

### System information

Linux, Debian 11 64 bit

### Issue description

I can't find the Smooth Trimesh Collision option in my project settings.

### Steps to reproduce

According to the documentation, it should be here
![Screenshot from 2022-03-01 17-48-26](https://user-images.githubusercontent.com/16293085/156262308-fcae2f55-f60f-4fad-8365-d258576a0577.png)

### Minimal reproduction project

[gammaball.zip](https://github.com/godotengine/godot/files/8165272/gammaball.zip)

**Comment by Calinou** [comment]
The project setting is read once in the Bullet implementation, but its default value isn't defined in `project_settings.cpp` or any other centralized location: https://github.com/godotengine/godot/blob/195b7374b271324fc8dc7f015263dedea1d5a01c/modules/bullet/shape_bullet.cpp#L425-L428

That said, this setting is *only* used when the physics engine is Bullet. GodotPhysics does not have an implementation of this setting (and there are no plans to add it there).

**Comment by Calinou** [comment]
There's an old pull request that aimed to fix the missing documentation: https://github.com/godotengine/godot/pull/42193

However, it would still hide the setting when the project uses the GodotPhysics engine. I think project settings should _never_ disappear depending on other settings – especially if that only occurs after the project is restarted.

I'll open a new pull request that supersedes that PR, while also adding documentation for the setting in question.

**Comment by valknor** [comment]
Thanks Calinou. I was starting to believe I had a buggy install of multiple Godot Engines, since I couldn't predict if / when that option would appear.
