### ISSUE TITLE
Locals Inspector shows wrong values on debugger

### ISSUE THREAD

**Issue by andynosoft** [godotengine/godot#5867]
**Operating system or device - Godot version:**
Windows 10. Godot version 2.0.4.1

**Issue description** (what happened, and what was expected):
Locals Inspector shows wrong values on debugger. When a local variable has a value greater than 65535, the inspector shows 65535

**Steps to reproduce:**

1 - Create a new project. 
2 - Add a root node. 
3 - Attach this script called main.gd to the root node.

extends Node

func _ready():
    var my_integer = 9999999
        print(my_integer)

4 - Put mouse over my_integer and see the value 9999999
5 - In the local's window, shows the wrong number 65535
![1](https://cloud.githubusercontent.com/assets/15801379/17075451/fe935ada-5069-11e6-83a7-322d2e71582d.png)

**Comment by bojidar-bg** [comment]
Would probably be fixed when #3091 is fixed.

**Comment by neikeq** [comment]
@bojidar-bg #3091 is more like an usability issue. Whatever the limit value is, the debugger should not be limited by it.

**Comment by bojidar-bg** [comment]
@neikeq Actually, I realised that #3091 won't help indeed, since the Tree class doesn't reuse the Range class :smile:

**Comment by bojidar-bg** [comment]
Mostly fixed by #5900, though there is still a limit.
A better fix might come with 3.0..

**Comment by akien-mga** [comment]
Is it still valid in 2.1.4-beta2 or 2.1/HEAD (with the new debugger by @Geequlim), or in the master branch (without debugger rework, but still with related changes)?

**Comment by akien-mga** [comment]
Fixed by #22535.
