### ISSUE TITLE
Hidden tilemaps are sometimes visible

### ISSUE THREAD

**Issue by ZuBsPaCe** [godotengine/godot#58695]
### Godot version

v4.0.alpha.custom_build [e6f00a0f7]

### System information

Windows 10, Vulkan Mobile, NVIDIA TI 1200

### Issue description

I sometimes need multiple tilemaps and hide some of them. In the latest godot 4 build, hidden tilemaps are shown in-game. Sometimes even in the editor:

![tilemap-visibility-problem](https://user-images.githubusercontent.com/4233942/156450167-cd2fa44d-ec0b-4d85-93c4-e19c88faa42e.gif)

A bisect of the recent commits shows, that this started to happen after this merged pull request: #58413

The pull request is not directly related to tilemaps it seems. It's possible, that other things are affected, too.

### Steps to reproduce

- Open the repro project
- Hide all tilemaps except one
- Start the game
- Only one tilemap should be visible, but all are visible

- Save the scene and restart the editor.
- Only one tilemap should be visible, but all are visible in the editor.

### Minimal reproduction project

[godot4-tilemap-visibility-problem.zip](https://github.com/godotengine/godot/files/8172959/godot4-tilemap-visibility-problem.zip)

**Comment by Calinou** [comment]
cc @Sauermann

**Comment by KoBeWi** [comment]
Fixed by https://github.com/godotengine/godot/pull/63248
