### ISSUE TITLE
Update opus to version 1.1.3 and opusfile 0.8

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#5870]
See changelog on http://www.opus-codec.org. Related to #5248.

CC @vnen :)

**Comment by akien-mga** [comment]
opusfile 0.8 is not shown on the download page, but it's in the repo too: https://archive.mozilla.org/pub/opus/

**Comment by vnen** [comment]
I'll try that soon.

**Comment by akien-mga** [comment]
Actually I did this myself with 9845bdd and 66dddcf, feel free to double check my changes :)

**Comment by vnen** [comment]
Completely forgot about this. I had some issues at first then postponed forever...
