### ISSUE TITLE
Godot 4.0: Isometric terrains don't auto tile

### ISSUE THREAD

**Issue by audse** [godotengine/godot#58714]
### Godot version

4.0.alpha3.official

### System information

macOS / Big Sur 11.5.2 / AMD Radeon Pro 5300M

### Issue description

Hi,

I'm making an isometric game where the player can customize the shape of their building, so in v3.4, I'm using auto tiles to handle this. I expected the terrain system to produce something similar to this (from 3.4):

<img width="508" alt="v3 4_autotile" src="https://user-images.githubusercontent.com/25091352/156605281-cb5fbbf8-0a5e-4447-a82e-b019525f2ef4.png">

However, even though I have the bit masks set up exactly the same (except for center bit masks) the terrain tool only tiles like this: 

<img width="1792" alt="Screen Shot 2022-03-03 at 10 04 56 AM" src="https://user-images.githubusercontent.com/25091352/156605665-6dede826-d844-43f3-86c5-93afa64a86e0.png">

I am using a full 48 tile set, it's the same set as the previous, but with guidelines for the bit masks. If I paint with a different tile, it just draws that tile over and over:

<img width="443" alt="Screen Shot 2022-03-03 at 10 05 07 AM" src="https://user-images.githubusercontent.com/25091352/156606110-660464db-173c-4a2b-8991-28eac3f61d41.png">

Occasionally one or two tiles will switch/apply auto tiling. I'm not sure what makes that happen, it seems random. 

I tried out a non-isometric tile set as well and it seemed to work as I expected, similar to the first pic, so it's just isometric not working for me.

Thanks for any help!

### Steps to reproduce

I've attached an example project that includes the tile set I'm using, the tile set without pink bit mask guides, and then the same tile set in the reduced (5x3) format. 

I set up the tile set according to the pink bit mask guidelines I drew, which is the same guidelines I used in 3.4. 

Just draw a bit on the `test_map.tscn` file to see the behavior I described. If it's working the same for you, notice that sometimes the tiles do adjust, but never in an expected way.

### Minimal reproduction project

[isometric_terrain_project.zip](https://github.com/godotengine/godot/files/8179337/isometric_terrain_project.zip)

**Comment by Calinou** [comment]
cc @groud
