### ISSUE TITLE
List items are shown twice in the 2D editor's "Show list of selectable nodes at position clicked" mode

### ISSUE THREAD

**Issue by fire-forge** [godotengine/godot#58726]
### Godot version

v4.0.alpha.custom_build [013efeef0]

### System information

Windows 10, Vulkan

### Issue description

When using the 2D editor's "Show list of selectable nodes at position clicked" mode (either through selecting that mode or using Alt+R in Select mode), each list item is shown twice. 

The first set (with icons) is added on button pressed, and the second set (without icons) is added on button release.

![image](https://user-images.githubusercontent.com/67974470/156699593-a842e1ac-5708-47bf-be53-1d0113bf4d61.png)

### Steps to reproduce

1. Add one or more 2D nodes.
2. Enter "Show list of selectable nodes at position clicked" mode or press Alt+R in Select mode.
![image](https://user-images.githubusercontent.com/67974470/156699761-18f4082a-8cb2-4b32-8012-8f1d27fde8f8.png)
3. Click over the area covered by the nodes.
4. When you begin holding the mouse button, the nodes will appear in the list. When you release the mouse button, the nodes will be added to the list a second time.

**Comment by taigi100** [comment]
I can't reproduce this the way it is described in the issue. However, I was able to reproduce it by alt+tabbing / trying to take a screenshot before releasing the mouse button.
I couldn't reproduce it with the normal select tool + alt + right click.
However, I was capable of reproducing it constantly while debugging, in the same manner the issue mentions.

I think it has to do with the fact that the following function gets called twice (I guess once per press, once per release): 
`bool CanvasItemEditor::_gui_input_select(const Ref<InputEvent> &p_event)` - canvas_item_editor_plugin.cpp line 2159 

Also - the dialog seems to be drawing over everything and stays on the screen even with Godot minimized - not sure if it's a Godot issue or something else. 

![Clipboard - March 15, 2022 7 39 PM](https://user-images.githubusercontent.com/10900362/158440468-88c5a2b9-1d13-47c3-b7c0-65d56515a68c.png)

**Comment by fire-forge** [comment]
@taigi100 Thanks for that, I'll try doing it again in the latest alpha and see if that's why it's different for you now than it was when I posted this issue.

> Also - the dialog seems to be drawing over everything and stays on the screen even with Godot minimized - not sure if it's a Godot issue or something else.

I believe that's an issue with popups in general - I've had tooltips, color pickers, and other popups do that as well.
