### ISSUE TITLE
Project can be opened multiple times from Project Manager

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#58723]
### Godot version

3f69ea4

### System information

W10

### Issue description

When you double click a project on project list, it opens the project. But if you keep clicking it until project manager closes, it will spawn multiple instances of the editor.

If the project is starting, further clicks should have no effect.

### Steps to reproduce

1. Open Project Manager
2. Click a project on the list
3. Click it
4. Click again
5. Click
6. Click
7. Keep clicking

**Comment by arkology** [comment]
Not bug but feature :D

**Comment by Calinou** [comment]
> Not bug but feature :D

Running multiple Godot editor instances *on the same project* isn't an officially supported use case. Either way, if you really need it, you can start multiple project manager instances (which can then start multiple editor instances on the same project).
