### ISSUE TITLE
Exported android apk with bigger launcher icon

### ISSUE THREAD

**Issue by wangdong20** [godotengine/godot#58737]
### Godot version

3.3.2 stable

### System information

macOS 12.1, Mac Pro

### Issue description

I just exported project as apk file with only Main 192 * 192 setting the launcher icons. The icon file is 192 * 192 pixels but looks very weird on real Android device and Android Virtual Machine. The launcher icon looks very different than other app icons with bigger size. Should I avoid using main launcher icon setting in Godot export setting?

### Steps to reproduce

Export project as Android apk file with setting Main 192 * 192 launcher icons.
Run apk on Android device or Virtual Machine. My android device is Android4.4, Virtual Machine is Android 8.1.
The launcher icon for the app looks bigger than other app icon and weird.

**Comment by Calinou** [comment]
@wangdong20 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

Remember that your icon should have sufficient margins on all borders as per the Android Adaptive Icons specification. See [Providing launcher icons](https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_android.html#providing-launcher-icons) in the documentation.

**Comment by timothyqiu** [comment]
Judging from your description, it might be Android's [Adaptive Icon](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive) feature.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
