### ISSUE TITLE
Create and preset a Camera nodes from the 3d Viewport Camera

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#5873]
**Operating system or device - Godot version:**
2.0.4.1

**Issue description** (what happened, and what was expected):

It could be handy to be able to create a Camera nodes at the exact same position and orientation than the 3D viewport's camera.

or to be able to position and orient the previewed Camera view the same way we can position and orient the editor's 3d viewport's camera.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by rhulha** [comment]
I wrote a plugin that can snap the camera to a scene object.
Check it out here: https://github.com/rhulha/godotengine_snap_cam_plugin

**Comment by KoBeWi** [comment]
This is possible since 2.1 with Perspective -> Align Selection With View. For more flexible placement options, there's another issue linked above.
