### ISSUE TITLE
[Godot 4.0 Alpha 3] Black screen on Editor Startup

### ISSUE THREAD

**Issue by Aketh-DCT** [godotengine/godot#58746]
### Godot version

4.0.alpha3.official

### System information

Windows 10, Vulkan API 1.1.0, Inter(R) HD 630

### Issue description

When opening any of the Godot 4.0 alpha builds, the screen is completely black. Since my cursor presses can click and use interface button, i assume is some kind of graphical glitch. Resizing does not help and i could't start a project, due to lack of visibility.

### Steps to reproduce

Open Godot 4 Alpha 1-3, with Intel 630 Graphics.

**Comment by Calinou** [comment]
@Aketh-DCT Try updating to the latest driver version *provided by Intel* (*not* your desktop/laptop OEM).

**Comment by Aketh-DCT** [comment]
> @Aketh-DCT Try updating to the latest driver version _provided by Intel_ (_not_ your desktop/laptop OEM).
Updating Drivers seem to fix the problem!
