### ISSUE TITLE
GDScript 2.0: any script with `extends ""` crashes the editor upon being parsed

### ISSUE THREAD

**Issue by otonashixav** [godotengine/godot#58769]
### Godot version

v4.0.alpha3.official [256069eaf]

### System information

Windows 10

### Issue description

This crashes the editor upon being parsed:

```gd
extends ""
```

It should raise an error instead.

### Steps to reproduce

1. Create a new script
2. Replace `Node` with `""` or replace the entire file with `extends ""`, with the intention of specifying a file path.
3. Wait for the idle parse delay to end
4. The editor crashes

Alternatively open `new_script.gd` in the attached project

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/8188791/Test.zip)

**Comment by Jayman2000** [comment]
I [bisected](https://docs.godotengine.org/en/stable/community/contributing/bisecting_regressions.html) this issue, and it looks like 3abb3c0d6e9e81d3ed171162cc5ce2bbe58296e0 introduced this bug.
