### ISSUE TITLE
Creating a uniform in a MaterialShader breaks rendering

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#5877]
Tested on Godot 2.0.4 and 2.1 beta, Windows 10 64 bits

I created a fragment shader for a material on a MeshInstance. But as soon as I create a uniform, the vertex shader is no longer applied and an error spam-prints in the console:

```
ERROR: ShaderGLES2::get_custom_uniform_location: Index p_idx out of size (version->custom_uniform_locations.size()).
   At: .\drivers/gles2/shader_gles2.h:336
```

I expected the vertex shader would be generated if empty, and there should be no error in this shader.

Test project:
[ShaderUniform3D.zip](https://github.com/godotengine/godot/files/379872/ShaderUniform3D.zip)

Open the material override in the MeshInstance, open the shader, select fragment shader, and uncomment the uniform (or create any).
Notice the sphere is now stretched to the whole screen as if no vertex shader was applied.

Because of this I cannot create a terrain shader properly :(

**Comment by akien-mga** [comment]
Rendering was complete redone for 3.0, assuming fixed.
