### ISSUE TITLE
CapsuleMesh generates with inverted tangents

### ISSUE THREAD

**Issue by NineAlexT** [godotengine/godot#58776]
### Godot version

4.0 Alpha 3

### System information

Kubuntu 20.04, Nvidia GTX 1060, Driver 510, Vulkan

### Issue description

![image](https://user-images.githubusercontent.com/60285548/156869134-0ac67190-b55b-4ce6-bca3-c7d18f9986eb.png)
When creating a CapsuleMesh, the mesh has inverted tangents causing  regular shading to appear fine, but normal maps to appear inverted. Not sure how to check for sure it's the tangents but shading appears otherwise normal so that's all I can think of.

### Steps to reproduce

Create a CapsuleMesh, create any other mesh for comparison, apply the same material with a normal map applied, see that the normal map on the CapsuleMesh appears inverted.

### Minimal reproduction project

[CapsuleMeshInverse.zip](https://github.com/godotengine/godot/files/8190036/CapsuleMeshInverse.zip)

**Comment by Calinou** [comment]
Interestingly, this doesn't seem to occur on 3.5.beta 59e84be9b (Linux, NVIDIA 510.60.02):

![image](https://user-images.githubusercontent.com/180032/166337953-8315f530-b85d-4a43-ba3e-f68ae6ba2fcd.png)

**Testing project (`3.x`):** [test_primitive_mesh_tangents_3.x.zip](https://github.com/godotengine/godot/files/8606420/test_primitive_mesh_tangents_3.x.zip)
