### ISSUE TITLE
FileDialog appears super-small

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#58780]
### Godot version

cdd63fa

### System information

W10

### Issue description

```GDScript
$FileDialog.popup_centered()
```
![image](https://user-images.githubusercontent.com/2223172/156882018-c8d85c74-26b9-4885-ba17-6e5c28d05ce5.png)
Default size is probably too small.

### Steps to reproduce

1. Add FileDialog
2. Popup it

**Comment by Calinou** [comment]
Is this also an issue in 3.4.3?

**Comment by KoBeWi** [comment]
No, I only seen it on master.

**Comment by IgorKordiukiewicz** [comment]
This is what it looks like on 3.4.3:
![Godot_v3 4 3-stable_win64_U8cUCHj8rK](https://user-images.githubusercontent.com/25117425/156937738-eb25ba13-b8dc-47c5-a607-b0d3656d52a0.png)

**Comment by KoBeWi** [comment]
Ah, I checked again and indeed it's bugged in 3.x too. But you can easily resize the dialog, because it's a Control, so the issue isn't as apparent.

**Comment by IgorKordiukiewicz** [comment]
> even if you show the dialog, you can't interact with it

I can interact with it in 4.0:

https://user-images.githubusercontent.com/25117425/156938419-97dd39ca-9990-4563-80c5-c99442efe1e0.mp4

**Comment by KoBeWi** [comment]
But I mean in the editor. It's possible to fix the dialog size after it appears, but perfectly it should have correct size from the start.
