### ISSUE TITLE
[3.x] Unable to use `Search Help` menu

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot#58782]
### Godot version

3.x branch 56310caee232582bc83b0c682e814e9fed866e91

### System information

Arch Linux

### Issue description

Same as title -- unable to use the `Search Help` popup.

Seems to be caused by a recent change. Perhaps within the 2-3 weeks range.

### Steps to reproduce

1. Open an empty project.
2. Press F1

The editor should have a darker overlay, but no popup shows up.

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
The help works correctly while inside Script Editor.

**Comment by timothyqiu** [comment]
Bisected and this is since #58315, but backporting #58413 locally does not fix the issue. So there seems still some problem with CanvasItem logic :(

**Comment by timothyqiu** [comment]
After some testing, I think this is related to "top level". `3.x` uses this to make Popups, thus the issue. `master` uses a different approach, so the Search Help dialog is not affected.

Both `3.x` and `master` have the problem that a top level CanvasItem is not rendered if its parent is invisible.

MRP:
* [Top Level Visible 3.zip](https://github.com/godotengine/godot/files/8191943/Top.Level.Visible.3.zip)
* [Top Level Visible 4.zip](https://github.com/godotengine/godot/files/8191931/Top.Level.Visible.4.zip)

**Comment by KoBeWi** [comment]
tbh I totally forgot about toplevel nodes when changing this code; I didn't think it would cause problems. There's also this comment that might be related:
https://github.com/godotengine/godot/blob/92615be68cddfc30b943f5eea942cc3c22b84bb6/scene/main/canvas_item.cpp#L103

**Comment by Sauermann** [comment]
> Both `3.x` and `master` have the problem that a top level CanvasItem is not rendered if its parent is invisible.

This current behavior in `master` is consistent with the description of Top Level: `If true, the node will not inherit its transform from parent CanvasItems.`
Nothing is said about `top_level` changing the the visibility status of the CanvasItem.

**Comment by KoBeWi** [comment]
Toplevel also [stops modulate propagation](https://github.com/godotengine/godot/issues/55033), and it's not mentioned in the documentation either.

**Comment by timothyqiu** [comment]
Top level works by reparenting the CanvasItem's RID in the RenderingServer to the nearest `CanvasLayer` or `Viewport`. i.e. reparent the node virtually. So I think it's the documentation that's incomplete.

**Comment by akien-mga** [comment]
Fixed by #58870.
