### ISSUE TITLE
Unpredictable behaviour when stop on slopes is set to false in a CharacterBody3D.

### ISSUE THREAD

**Issue by yosoyfreeman** [godotengine/godot#58786]
### Godot version

Godot 4.0 alpha 3.

### System information

Linux mint, vulkan

### Issue description

When stop on slopes is set to false, the character will not slide properly along the slope and the behavior is unpredictable. When applying a down force there is almost no slide and it becomes totally static as the  force gets bigger (In this case more down force result in less sliding contrary to the expected behavior).

> ![untitled](https://user-images.githubusercontent.com/64601424/156885817-38202e75-54ca-4068-8dea-38e38fa155a7.GIF) 
The first (red) sphere is set to stop on slopes, the second (green) one is set to false, the third (blue) is also set to false with 10 x force.

i noticed a similar behaviour where sliding along a wall not change the motion_velocity, resulting in an instant stop after leaven the slope.

### Steps to reproduce

-Create a new project.

-Add a mesh with a collider as floor, rotate it a bit (less than 45 degree so is still a floor)

-add a characterbody3d with a force along the y axis.

-set stop on slopes to false.

### Minimal reproduction project

[Bug.zip](https://github.com/godotengine/godot/files/8190776/Bug.zip)

**Comment by Calinou** [comment]
cc @fabriceci
