### ISSUE TITLE
FILE_MODE_OPEN_FILE shows warning that file already exists

### ISSUE THREAD

**Issue by floriandotorg** [godotengine/godot#58795]
### Godot version

4.0.alpha3

### System information

macOS 12.2

### Issue description

Hey Godot team, love your work! I've encountered a bug, a FileDialog with FILE_MODE_OPEN_FILE shows a warning that a file already exists, which of course makes no sense, since you are choosing a file to open.

### Steps to reproduce

Use the following code somewhere in a script:

```
var file_dialog = FileDialog.new()
file_dialog.mode = FileDialog.FILE_MODE_OPEN_FILE
file_dialog.access = FileDialog.ACCESS_FILESYSTEM
_file_dialog_aseprite.popup_centered_ratio()
```

Run it and choose a file, you'll get the following error dialog:
![CleanShot 2022-03-05 at 18 21 02](https://user-images.githubusercontent.com/6143734/156895581-e5ec0bf1-3781-472b-b22b-171cf2aca3a1.png)

**Comment by Calinou** [comment]
@floriandotorg Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

Also, can you reproduce this in 3.4.3?

**Comment by Sauermann** [comment]
Please try replacing
`file_dialog.mode = FileDialog.FILE_MODE_OPEN_FILE`
with
`file_dialog.file_mode = FileDialog.FILE_MODE_OPEN_FILE`

**Comment by floriandotorg** [comment]
Danke @Sauermann! That fixed it. Apparently, `mode` was renamed to `file_mode` and I didn't notice. It's still possible, however, to assign `mode`. Maybe we should trigger a warning in this case? Possibly, we could implement that for all renamed properties? Would it make much easier to migrate code.

**Comment by Calinou** [comment]
> Maybe we should trigger a warning in this case? Possibly, we could implement that for all renamed properties? Would it make much easier to migrate code.

See https://github.com/godotengine/godot-proposals/issues/3902, which only covers methods currently.
