### ISSUE TITLE
Silent fails of Array's map method

### ISSUE THREAD

**Issue by miv391** [godotengine/godot#58796]
### Godot version

v4.0.alpha3.official [256069eaf]

### System information

Windows 10

### Issue description

Documentation says:

> The callable's method should take one Variant parameter (the current array element) and can return any Variant.

In addition of one Variant parameter, also one int parameter seems to work. But if the callable doesn't have any parameters, or the one parameter is for example String or there are more than one parameters, the map method just silently fails. The callable is not called at all.

Expected behaviour would be an error message if the callable cannot be called.

Also, I would recommend using RFC (Request for Comments) styled wording in the documentation. Now the documentation says "should take one Variant parameter". In RFC terminology that means that one Variant parameter is only recommended. However, as one Variant (or int) parameter is required, better wording would be "must take one Variant parameter".

### Steps to reproduce

```gdscript
func test():
	# 1) this works ok
	range(3).map(do_something_with_variant_param)

	# 2) this works ok, although this is against the documentation
	range(3).map(do_something_with_int_param)

	# 3) this silently fails
	range(3).map(do_something)
		
	# 4) this silently fails
	range(3).map(do_something_with_string_param)

	# 5) this silently fails
	range(3).map(do_something_with_two_params)
	

func do_something_with_variant_param(i):
	print('something with variant param ', i)

func do_something_with_int_param(i: int):
	print('something with int param ', i)

func do_something():
	print('something')

func do_something_with_string_param(i: String):
	print('something with String param ', i)

func do_something_with_two_params(a, b):
	print('something with two params ', a, b)
```

**Comment by Calinou** [comment]
cc @KoBeWi 

As for using RFC wording, it's a good idea to do, but it'll take a lot of time to apply evereywhere.

**Comment by KoBeWi** [comment]
Except there are error messages:
![image](https://user-images.githubusercontent.com/2223172/156897476-bca835ac-0649-4b08-9c7b-fb4a6ffe6895.png)

**Comment by miv391** [comment]
> Except there are error messages... 

My bad, I just looked at the Output tab and completely missed the Debug tab.

**Comment by miv391** [comment]
There is no bug, works as expected.

**Comment by Calinou** [comment]
> My bad, I just looked at the Output tab and completely missed the Debug tab.

We should probably find out a way to make errors more obvious in this case.

**Comment by KoBeWi** [comment]
Maybe debugger tab should get focused on errors?

**Comment by Calinou** [comment]
> Maybe debugger tab should get focused on errors?

This could likely end up being annoying, especially if it happens while you're looking at the Output panel.

**Comment by miv391** [comment]
Some suggestions:
- Briefly flash the "Debugger" tab label's background color to red after first error. That might draw programmer's attention without being too annoying. Or if the Debugger tab is already selected, flash Errors tab label's background color
- Move Errors tab to the same level with Output, Debugger Search Results etc. At least for me Errors being under Debugger is a bit unintuitive.
