### ISSUE TITLE
Improve reporting of debug draw modes not working in GLES2

### ISSUE THREAD

**Issue by CoderLel** [godotengine/godot#58792]
### Godot version

3.4.2.stable.mono.official.45eaa2daf

### System information

Windows 10 Home, AMD RADEON HD5450, GLES2

### Issue description

When I try to change the View Mode In the viewport menu, the Display-Related options are all locked 
![DisplayModesLocked](https://user-images.githubusercontent.com/72571267/156892677-39b204aa-0b07-45df-90a8-950bfd46c406.PNG)

### Steps to reproduce

Open a new project
Add a MeshInstance node and give it mesh
Open the viewport menu
Check if the Display-related options are locked

**Comment by Calinou** [comment]
This is a limitation of the GLES2 renderer. If you hover the options, you'll see a tooltip appearing for that reason.

**Comment by akien-mga** [comment]
Fixed by #58794.
