### ISSUE TITLE
Wrong rotation when using RotationX, RotationY or RotationZ

### ISSUE THREAD

**Issue by Developpix** [godotengine/godot#58798]
### Godot version

3.4.2

### System information

Windows 10

### Issue description

Rotation seems to take absolute value of axis vector.

### Steps to reproduce

In 3d make local Up vector point to down and RotateY is inverted. RotateY with Vector3(0, 1, 0) and Vector3(0, -1, 0) are equal but it false.

**Comment by Calinou** [comment]
@Developpix Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by Developpix** [comment]
Hello,
I close this issue because it was a bug in my code.
