### ISSUE TITLE
pinjoint2d staticbody to rigidbody2d behaving strangely

### ISSUE THREAD

**Issue by ryanscottcausecast** [godotengine/godot#58802]
### Godot version

4.0 dev alpha 3

### System information

mac book pro 2019 15" current os

### Issue description

enabling collisions on my rigid body, even though it does not collide with my staticbody in any way, causes the rigidbody to fly off into oblivion, ultimately reporting NaN,NaN as its location.

### Steps to reproduce

run the included project.  works 'fine' when collisions aren't enabled on the rigidbody.  does not work when collision is enabled.

tried removing all the layers from the collisions, this had no beneficial effect.

### Minimal reproduction project

<img width="1676" alt="Screen Shot 2022-03-05 at 2 20 40 PM" src="https://user-images.githubusercontent.com/24243219/156898947-020559ff-6898-48db-9a3f-62f9e0f80656.png">

[pin.zip](https://github.com/godotengine/godot/files/8191417/pin.zip)

**Comment by Calinou** [comment]
@ryanscottcausecast Can you reproduce this in 3.4.3?
