### ISSUE TITLE
Cannot get world-space normal in fragment shader

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#5880]
Tested on Godot 2.0.4, Windows 10 64 bits

I need to get the world-space normal of the model in a fragment shader, however all my attempts have failed so far.
There is no access to `SRC_NORMAL`, which is only available in the vertex shader.
I also tried to use the formula indicated in the [documentation](http://docs.godotengine.org/en/latest/reference/shading_language.html#examples):

``` glsl
// Use reverse multiply because INV_CAMERA_MATRIX is world2cam
vec3 world_normal = NORMAL * mat3(INV_CAMERA_MATRIX);
```

However this throws an error:

```
Error precompiling shader: Invalid arguments to function/constructor: mat3
```

![terraineditor_shader_error](https://cloud.githubusercontent.com/assets/1311555/17079307/551578aa-510c-11e6-9498-2c3b3201450a.png)

Note: if it's actually possible, maybe it's a documentation issue because the above line doesn't works.

**Comment by WalasPrime** [comment]
Related to #5232

**Comment by GlaDOSik** [comment]
Documentation says the INV_CAMERA_MATRIX is mat4 so the example is probably wrong. Btw, did you try put the SRC_NORMAL to VAR1 or VAR2 and get the normal in FS?

**Comment by Zylann** [comment]
@GlaDOSik yes I use that instead, it does the job pretty well (although VARs are limited). The documentation should be updated.

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by quantum-entangler** [comment]
are you sure the example in documentation isn't telling you to do something more:
```
vec4 invcamx = INV_CAMERA_MATRIX.x;
vec4 invcamy = INV_CAMERA_MATRIX.y;
vec4 invcamz = INV_CAMERA_MATRIX.z;
vec4 invcamw = INV_CAMERA_MATRIX.w;

mat3 invcam = mat3(invcamx.xyz, invcamy.xyz, invcamz.xyz);

vec3 world_normal = NORMAL * invcam;
```
;)

**Comment by Zylann** [comment]
Ah, looks like the documentation has been updated since, because I cannot find the initial example anymore.

**Comment by akien-mga** [comment]
So, I understand that was fixed in the docs.

**Comment by RichardEllicott** [comment]
i can't now find this in the docs and keep forgetting, for the record here the world normal, useful for making say cliff top shader (green on top, rocky at sides), is:

`vec3 WORLD_NORMAL = (INV_VIEW_MATRIX * vec4(NORMAL.xyz, 0.0)).xyz;`
