### ISSUE TITLE
Large amount of opened scene tabs isn't handled correctly

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#58817]
### Godot version

ff65d33

### System information

W10

### Issue description

Tested only with empty tabs, but this happens:
![godot windows tools 64_xcU13n3rFL](https://user-images.githubusercontent.com/2223172/156904188-254b9a4b-440e-45f7-9655-cfbd27e4d85f.gif)
When you are on last tab and press the left arrow, it will change the size of tabs, but don't scroll. When you are on the left and press the right arrow, it will jump to the end after few clicks.

### Steps to reproduce

1. Open big number of scene tabs
2. Use the navigation arrows

**Comment by kitbdev** [comment]
Part of this is the tabs size not updating, but it seems to be fixed in 4.1
The other part of this was fixed by #79852
