### ISSUE TITLE
Signal connections don't persist in tool scripts

### ISSUE THREAD

**Issue by ReturnMinusOne** [godotengine/godot#58814]
### Godot version

v3.4.3.stable.mono.official [242c05d12]

### System information

Windows 10 64-bit

### Issue description

Hello,

In tool scripts, the Object.connect() function does not create a persistent connection between an object signal and the linked function.

The connection does work, but the icon doesn't appear next to the object's name in the node list (like it would if it were connected in the editor interface) and the connection is lost when the scene is reloaded.

I don't think this is intentional behaviour; but even if it is, I believe it should be up to the user to disconnect any unwanted functions using the disconnect() method.

### Steps to reproduce

1. Create an object.
2. Create a tool script. In this script, connect anyone of the object's signals to one of its methods, using the Object.connect() function.
3. Run the script. The icon will not appear next to the object's name, and reloading the scene will break the connection.

**Comment by KoBeWi** [comment]
Do you use the `CONNECT_PERSIST` flag?

**Comment by ReturnMinusOne** [comment]
...You are completely right.

Thank you very much. I looked all over the docs, desperate to explore any avenue I could think of, but I totally missed this. I added the flag at the end of the connect() function, and now the icon is visible and the connection holds even when reloading the scene.

So my mistake. Apologies to the developers, and thank you again, KoBeWi.
