### ISSUE TITLE
Bezier curves are difficult to edit if key values are small

### ISSUE THREAD

**Issue by Rodeo-McCabe** [godotengine/godot#58824]
### Godot version

4.0 alpha 3

### System information

Linux

### Issue description

When editing the bezier curves of an animation for which the keyframed values are relatively small, it is difficult to select keys and curve handles, and also difficult to view and manipulate the curves. This is because the bezier editor view has a vertical scale that shows values in the hundreds. When doing small 3D translations or keyframing other things like color values, this becomes problematic.

### Steps to reproduce

1. Create a new 3D scene
2. Add a cube and animate it to move some short distance
3. Open the bezier editor for this animation and attempt to edit the curve

**Comment by Calinou** [comment]
cc @Razoric480

**Comment by Razoric480** [comment]
If you hold down CTRL + ALT and use the scroll wheel, you can zoom vertically. This has been changed from only ALT with the introduction of the ViewPanner class (ba7ed0579296464642f1cc90fe76590467793131).

Alternatively, you can use the Focus Keys shortcut (<kbd>F</kbd>) and it will set the zoom scale to the selected keys (or all keys) based on the animation pane's horizontal and vertical size.

**Comment by Rodeo-McCabe** [comment]
Ah thanks, I didn't try the Ctrl+Alt combo. Focus works well too.

This issue can be closed, but I still think there should be some visual indication of the vertical zoom. A scroll bar on the right side of the bezier editor, maybe?

Thanks for your work on this, I'm really excited about this feature.
