### ISSUE TITLE
Godot crash on startup on Linux ARM64

### ISSUE THREAD

**Issue by rajrebellsquad** [godotengine/godot#58825]
### Godot version

Downloaded from debian repository

### System information

Debian Linux Arm64 

### Issue description

Godot 3 Crash on Debian 10 buster 
Godot has been downloaded from "sudo apt install godot3*"
system info
Debian 10 Buster linux
Arm64
Ram 2 gb 

Output 

![New Log](https://user-images.githubusercontent.com/100519086/156919189-1d26a751-9052-4440-b301-47a3aa5956ac.JPG)

### Steps to reproduce

Start Godot from terminal
'godot3

### Minimal reproduction project

Old Log when launch godot from terminal

shared memfd open() failed: Function not implemented shared memfd open() failed: Function not implemented ALSA lib confmisc.c:767:(parse_card) cannot find card '0' ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM default ERROR: init_device: Condition ' status < 0 ' is true. returned: ERR_CANT_OPEN At: drivers/alsa/audio_driver_alsa.cpp:80. ERROR: initialize: AudioDriverManager: all drivers failed, falling back to dummy driver At: servers/audio_server.cpp:165. OpenGL ES 3.0 Renderer: llvmpipe (LLVM 7.0, 128 bits) handle_crash: Program crashed with signal 11 Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues [1] linux-vdso.so.1(__kernel_rt_sigreturn+0) [0x7fb0bfb4e0] () [2] /lib/aarch64-linux-gnu/libgcc_s.so.1(+0x6800) [0x7fafc85800] () [3] llvm::sys::Memory::protectMappedMemory(llvm::sys::MemoryBlock const&, unsigned int) () -- END OF BACKTRACE -- Aborted

**Comment by Calinou** [comment]
This is a distribution-provided package, which is severely outdated and [not supported anymore](https://docs.godotengine.org/en/stable/about/release_policy.html#release-support-timeline). We don't support Godot 3.2 anymore, so please use a [recent build](https://github.com/hiulit/Unofficial-Godot-Engine-Raspberry-Pi) or [compile one yourself](https://docs.godotengine.org/en/stable/development/compiling/index.html).
