### ISSUE TITLE
Godot4 script font is worse than Godot3

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#58831]
### Godot version

3.4.3 stable, 4.0 alpha3

### System information

Win, Nvidea 765M

### Issue description

Godot 4 script font is considerably wider than the Godot3 script font (in my opinion also much uglier) and there has been **more line space added** between script lines. As a result the Godot4 script font takes up more screen real estate on a similar readable scale.

Since I am working on a Laptop I can't give up on any screen real estate. Any additional line I can see (while I can still read it without straining my eyes) is worth gold. Any line of code which is not wrapped or cut off is worth gold.
In Godot 3 I have to bump up `Main Font` size to 16 and `Code Font` size to 17 to comfortably read. To get a similar visual result in Godot4  I have to set `Main Font` size to 16 and `Code Font` size to 18:

Godot3 script panel:
![godot3_scriptpanel](https://user-images.githubusercontent.com/47016402/156920965-10b36960-69b0-4229-9430-3559a1e57ed2.png)

Godot4 script panel:
![godot4_scriptpanel](https://user-images.githubusercontent.com/47016402/156921850-bc9f31eb-e54c-40ae-b392-a89ef3c2105e.png)

I think Godot3 is font choice is better in every way. For me this change is so bad, I really consider the Godot4 font choice and the added line space a regression. 
I really hope this font choice will be reconsidered before going into beta.

If there is no chance to reconsider it, I would at least hope for an editor setting made available which allows users to easily change back to the Godot3 font and line distance. I know the option to use a custom font exists, but trying to figure out which font Godot3 used for the script panel and then trying to look for a place to download it, and then after all this manual work (who does this?) still not being able to correct the line distance, is just not the experience I would want anyone to have. 

### Steps to reproduce

Compare Script panel between Godot3  and Godot4

### Minimal reproduction project

I used the player script form the [2D Platformer Demo](https://godotengine.org/asset-library/asset/120) here.

**Comment by Rodeo-McCabe** [comment]
For the line spacing there is an option: Editor settings -> Text Editor -> Appearance -> Whitespace -> Line Spacing  
I believe the value is in pixels. It takes a few seconds for the editor to update after you change the value.

It appears to be the same setting as Editor settings -> Text Editor -> Theme -> Line Spacing, but that setting doesn't actually change anything.

For the font, I believe the old font is Source Code Pro, and you can always change it to whatever you'd like: Editor settings -> Interface -> Editor -> Code Font

**Comment by golddotasksquestions** [comment]
@Rodeo-McCabe Oh yes, thank you! I probably tried this but did not see any change, so I thought it must be something else. It's actually just lagging a lot, I have to wait solid 2 seconds for the change to update.

I mentioned in the issue I know I can change the font manually. But why change what works? I don't understand why we need a font that takes more space. It's less readable. You have to increase the line spacing in order to make a wider font equally readable.

**Comment by Rodeo-McCabe** [comment]
> I mentioned in the issue I know I can change the font manually. But why change what works? I don't understand why we need a font that takes more space. It's less readable. You have to increase the line spacing in order to make a wider font equally readable.

I agree, I much prefer "narrow" fonts that don't take much horizontal space. At least for monospace fonts. Changing the font is also annoying because you can't just select a standard system font that you already have, you have to find the .ttf or download one and then use that.

**Comment by Zireael07** [comment]
Counterpoint: I find the Godot4 font much more readable (as someone with frankly poor eyesight)

**Comment by Calinou** [comment]
For reference, the default font was changed here: https://github.com/godotengine/godot/pull/36198

> For the font, I believe the old font is Source Code Pro

The previous font was Hack, not Source Code Pro.

**Comment by KoBeWi** [comment]
> It appears to be the same setting as Editor settings -> Text Editor -> Theme -> Line Spacing, but that setting doesn't actually change anything.

This setting was moved, so you have a leftover. Removed settings still appear in the editor if you have them in configuration file (they aren't deleted automatically).

**Comment by Calinou** [comment]
I did some comparisons between Godot 4.0alpha and my personal VS Code setup (which uses the [Recursive](https://www.recursive.design/) font):

### JetBrains Mono size 14 in Godot (left), Recursive size 13 in VS Code (right)

![image](https://user-images.githubusercontent.com/180032/159192921-41a3da30-34a7-4e62-880d-9cd9f6a3d7eb.png)

### JetBrains Mono size 13 in Godot (left), Recursive size 13 in VS Code (right)

![image](https://user-images.githubusercontent.com/180032/159192924-b89c5df5-2444-4981-bb4c-6a3ce4425c37.png)

### JetBrains Mono size 12 in Godot (left), Recursive size 13 in VS Code (right)

![image](https://user-images.githubusercontent.com/180032/159192925-1dc5cf67-7730-4280-9a01-2f0670177b1c.png)

It's clear that the default line spacing is now too high, so I'd consider decreasing it to 4 or even 2.
