### ISSUE TITLE
GLB imported mesh sometimes becomes empty, sometimes stays, sometimes returns after becoming empty.

### ISSUE THREAD

**Issue by Altair1234** [godotengine/godot#58830]
### Godot version

4.0 alpha 1

### System information

Windows 10, Vulkan, 5600x, 3060

### Issue description

Title. I don't know what are the triggers but sometimes the mesh returns. It is visible in the importer. But in the viewport, it is empty. When I do "new inherited" and look at the MeshInstance's mesh property field, it is empty. And then sometimes it is not.

I apologize if this problem has been reported before.

### Steps to reproduce

Import a GLB model and bring it into a scene.

**Comment by Zireael07** [comment]
Is this reproducible in alpha 2 or alpha 3? (I remember seeing similar problems with alpha 1, but iirc they went away in alpha 2)

**Comment by Altair1234** [comment]
Okay it seems to be working in Alpha 3.
