### ISSUE TITLE
Closing and reopening a scene with a TileMap clears custom data values on the tiles.

### ISSUE THREAD

**Issue by Roberto34** [godotengine/godot#58848]
### Godot version

4.0 alpha3

### System information

Windows 11

### Issue description

If a scene with a TileMap node, with custom data set up on the TileSet resource, is closed, then upon reopening it each tile's custom data value is cleared.

NOTE: the issue pops up only when closing and reopening a scene **without** closing the Godot application. If a scene is closed, and then the application is closed as well, then upon reopening both the tile data should be the same.

Here an example with a boolean custom data type.

Before closing and reopening:
![godot_issue_before](https://user-images.githubusercontent.com/39373241/156942837-4e7a8475-0cba-439f-81bd-8c6195fcaa6e.png)
After:
![godot_issue_after](https://user-images.githubusercontent.com/39373241/156942865-1e7de595-fb18-41ba-a2e5-1ccc9e8f7658.png)

### Steps to reproduce

1. Add a TileMap node to a scene
2. Set up the TileSet and create a custom data layer
3. Set some value for the custom data on any tile
4. Save and close the scene
5. Open the same scene again
6. The custom data values should be all cleared

### Minimal reproduction project

[test 2.zip](https://github.com/godotengine/godot/files/8193570/test.2.zip)

**Comment by Calinou** [comment]
cc @groud

**Comment by KoBeWi** [comment]
Seems to only happen when the TileSet is internal. Works fine when you save it to file.

**Comment by Roberto34** [comment]
Ok, perfect, thank you for the info.
Keep up the good work!

Il lun 7 mar 2022, 12:14 Tomek ***@***.***> ha scritto:

**Comment by agata-wod** [comment]
I am having the issue when the tilemap is on a separate scene file. If the tilemap is instantiated into another scene, the custom data seems to be fine.

**Comment by Liamen94** [comment]
Similar issue in alpha8, Windows 11. It seems to clear physical and navigation layers too, my tileset is internal to the tilemap and saved as a file.

**Comment by nawilliams** [comment]
I'm having the same issue for physics layers in alpha12 on Windows 10. I've been unable to reproduce the issue in a new project, creating a new identical tilemap with the same parameters didn't seem to create the same issue,.

I isolated the broken one into a minimal project in case that would be helpful for tracking down the bug.
[broken_tilemap.zip](https://github.com/godotengine/godot/files/9185631/broken_tilemap.zip)
.
Steps to reproduce in minimal project:
1. Paint physics layers on tileset
2. Save
3. Reload project
4. Tileset physics layers are now gone
