### ISSUE TITLE
Games do not stay on lower resolutions in fullscreen with Vulkan

### ISSUE THREAD

**Issue by mmmegaidiot** [godotengine/godot#58845]
### Godot version

4.0.alpha3

### System information

Windows 10, Geforce GTX 1650 SUPER, Vulkan

### Issue description

The problem is that the resolution I set it at (640x480) is actually at that resolution when windowed. However, when I set it to full screen, it instead resolutes to my whole monitor, instead of staying at the resolution.

### Steps to reproduce

1: Start up Godot
2: Start a new project or use one you already have on hand
3: Go to Project settings > Window 
4: Set a resolution to a lower number (ex. 640x480)
5: Set to fullscreen
6: Start the scene

**Comment by Calinou** [comment]
This is intended behavior, and it hasn't changed with the switch to Vulkan. See the [Multiple resolutions](https://docs.godotengine.org/en/stable/tutorials/viewports/multiple_resolutions.html) documentation for more information.

Note that the `master` branch also allows you to change the 3D rendering scale without affecting 2D rendering (and without [requiring a separate Viewport](https://github.com/godotengine/godot-demo-projects/tree/master/viewport/3d_scaling)). Use the `scaling_3d_mode` and `scaling_3d_scale` project settings for that purpose.
