### ISSUE TITLE
Valid function signature raised an error as invalid signature

### ISSUE THREAD

**Issue by Wildos** [godotengine/godot#58856]
### Godot version

v4.0.alpha.custom_build.53cf5eff9

### System information

Linux Manjaro 5.16.11-2-MANJARO

### Issue description

The code an overridden function with a default value: 
```
func virtual_function(dict_var: Dictionary = {}) -> void:
```
Get the error : `The function signature doesn't match the parent. Parent signature is "void virtual_function(Dictionary = default)".`

The issue was introduced by commit: 1ebcb58e6942582b3c1e4af9de44f5ce21245148

The issue seems to only appear with the argument type being of type: Dictionary, Array or a new type

### Steps to reproduce

Use the following code

Parent class code: 
```
class_name ParentClass
extends Node

func virtual_function_float(_dict_var: float = 0.1) -> void:
	pass

func virtual_function_array(_dict_var: Array = []) -> void:
	pass
	
func virtual_function_typed_array(_dict_var: Array[int] = ([1] as Array[int])) -> void:
	pass

func virtual_function_dictionary(_dict_var: Dictionary = {}) -> void:
	pass

func virtual_function_new_type(_dict_var: NewType = NewType.new()) -> void:
	pass

```

Child class code:
```
extends ParentClass

func virtual_function_float(dict_var: float = 0.1) -> void:
	pass

func virtual_function_array(dict_var: Array = []) -> void:
	pass
	
func virtual_function_typed_array(dict_var: Array[int] = ([1] as Array[int])) -> void:
	pass

func virtual_function_dictionary(dict_var: Dictionary = {}) -> void:
	pass

func virtual_function_new_type(dict_var: NewType = NewType.new()) -> void:
	pass

```

NewType class code:
```
class_name NewType
extends Resource

var test := 12.2
```

### Minimal reproduction project

[signature_error_issue_godot_4.zip](https://github.com/godotengine/godot/files/8196943/signature_error_issue_godot_4.zip)

**Comment by CalebJohn** [comment]
This appears to be fixed in the latest master (4c2a614ad41564ab33eb6515b48e0e5b52ea8b81). I did not bisect for a solution commit, but the following test succeeds on (4c2a614ad41564ab33eb6515b48e0e5b52ea8b81) and fails on (https://github.com/godotengine/godot/commit/1ebcb58e6942582b3c1e4af9de44f5ce21245148).
```gdscript
func test():
	var instance := Parent.new()
	instance.my_function({"a": 1})
	instance = Child.new()
	instance.my_function({"a": 1})
	print("No failure")

class Parent:
	func my_function(_par1: Dictionary = {}) -> void:
		pass

class Child extends Parent:
	func my_function(_par1: Dictionary = {}) -> void:
		pass
```
