### ISSUE TITLE
Deselecting a node with CTRL+BUTTON_LEFT is not updating the selection in 2D Scene view

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#5885]
Deselecting a node with CTRL+BUTTON_LEFT is not updating the selection in 2D Scene view.

1.Create a scene with 2 nodes
2.Select Node1(In scene dock)
3.Hold CTRL and Left Click on Node2 
4.Go to 2D Scene View and see 2 Selections
5.Hold CTRL and Left Click on Node2(Deselect in scene dock)
6.Look at 2D Scene View still 2 Selections

Moving the mouse into the 2D Scene View is updating the View and then shows the correct selection.

**Comment by akien-mga** [comment]
Likely also related, after closing a scene, some overlay elements of the previous scene like grouping icons will still be displayed.

**Comment by bojidar-bg** [comment]
Is this still valid after the refactoring of the 2D scene view?

**Comment by AlexHolly** [comment]
Maybe related since the signal `cell_selected` is not fired on `multi_select`? https://github.com/godotengine/godot/issues/20073
https://github.com/godotengine/godot/blob/c69de2ba46463adeadf90f38660d6b6e034d7e0b/editor/editor_sectioned_inspector.cpp#L300
