### ISSUE TITLE
The grow_direction horizontal/vertical properties are not present anymore

### ISSUE THREAD

**Issue by groud** [godotengine/godot#58857]
### Godot version

4.0

### System information

v4.0.alpha.custom_build [73f92a6e4]

### Issue description

The grow_direction properties, which controls in which way a Control expands when its size is modified is not editable anymore in the inspector:
![2022-03-07-114648_620x1123_scrot](https://user-images.githubusercontent.com/6093119/157016804-fe204600-9def-4411-a208-b95f7324365f.png)

### Steps to reproduce

Create a control node, then edit it.

**Comment by groud** [comment]
cc @pycbouh

**Comment by pycbouh** [comment]
It's hidden on purpose. @reduz wanted it to be controlled by the anchor preset, automatically changing with it to give the user the most expected behavior out of the box. Which is why it is only editable with the custom preset.

**Comment by groud** [comment]
Oh, got it! The grow direction is within the Custom mode of the Anchor Preset.
This should be changed. I definitely need to be able to set the grow direction to center when using the center anchor preset.
I'll make a PR to move it out of the menu.

**Comment by groud** [comment]
> It's hidden on purpose. @reduz wanted it to be controlled by the anchor preset, automatically changing with it to give the user the most expected behavior out of the box. Which is why it is only editable with the custom preset.

Yeah, I figured that out. Sadly, until we implement the grow_direction computed out of the anchors values (this might require a proposal, as we might need to override this default behavior, I am not sure), we need access to grow_direction properties with other presets.

I'll make a PR as a quick fix, but I agree we should discuss the implementation of the computation of grow_direction out of anchors.

**Comment by groud** [comment]
Anyway, closing this as the original situation is expected. I'll if I am able to reproduce the bug again, I'll open another issue.
