### ISSUE TITLE
Game keep running after closing game window.

### ISSUE THREAD

**Issue by carabalonepaulo** [godotengine/godot#58867]
### Godot version

3.4.2 stable

### System information

Windows 11, GLES2, GTX 1650, I5 9ª

### Issue description

When I use the NetworkedMultiplayerENet object, the game continues to run even after I close the game window. There is a gif below exemplifying this.
[Gif](https://i.imgur.com/ECwitHe.gif)

Another problem that I noticed while was recording the gif is that the "print" function is not working for some reason, in the client project I used a Label control to see if the code was really reaching that point.

One more detail: I use two editor running at the same time (one for the client and another one for the server).

### Steps to reproduce

1. Run the server
2. Run the client
3. Close the client

### Minimal reproduction project

[project.zip](https://github.com/godotengine/godot/files/8198608/project.zip)

**Comment by carabalonepaulo** [comment]
Problem solved then, I tried here and everything is working fine if I run the server without opening the editor.
[gif](https://i.imgur.com/B3DrBZR.gif)
How can I work on 2 or more projects at them same time on the same machine?

**Comment by Calinou** [comment]
[The editor should now automatically assign a debug port](https://github.com/godotengine/godot/pull/37067), but I guess it doesn't always work: https://github.com/godotengine/godot/issues/54237
