### ISSUE TITLE
WebM: VP8 and VP9 video codecs

### ISSUE THREAD

**Issue by zaps166** [godotengine/godot#5886]
Is it in still plans?

If yes - has anyone started working on this? If not - I can integrate them with Godot using `libvpx` library (VP8, VP9 - video via libvpx; Vorbis, Opus - audio using existing libraries) :)

Discussion about VP8/VP9 was also in #5226 and #5784.

**Comment by reduz** [comment]
Would be super welcome

**Comment by zaps166** [comment]
In which Godot version this can be added, 2.1 or 2.2 or 3.0 ?

**Comment by akien-mga** [comment]
Not 2.1, but otherwise as soon as it's ready :)

**Comment by zaps166** [comment]
Ok, thanks, I'll push a WIP PR soon :)

**Comment by zaps166** [comment]
Before I'll push a PR, please look here: https://github.com/zaps166/godot/commit/b841555b43cc9220b1884bcc68ce797b82a39420 and read commit message :)

**Comment by reduz** [comment]
wow

**Comment by zaps166** [comment]
Update: https://github.com/zaps166/godot/commit/5a23c729afe118ece95ed9379a76a158c0948858 :smile:

Is it possible to add ASM files via YASM to SCons (libvpx has a lot of them)?

**Comment by reduz** [comment]
can it not be compiled with regular gnu compiler?

**Comment by zaps166** [comment]
Hmm, I think that GCC/Clang/MSVC can't handle YASM syntax (this is not inline assembly, e.g. https://github.com/webmproject/libvpx/blob/v1.6.0/vp8/common/x86/copy_sse2.asm). https://github.com/webmproject/libvpx/blob/v1.6.0/README#L12

I don't know what with other CPUs - which assembler could be used?

**Comment by punto-** [comment]
What's the extension of these asm files? maybe you can just add them to the
sources, and scons knows what to do. Is there an alternate version that the
microsoft compiler can handle too?

**Comment by zaps166** [comment]
@punto- *.asm files (Intel syntax, macro assembler) which should be compiled via YASM. Also libvpx generates some *.c files during compilation.

@reduz The YUV->RGB conversion code is currently the same as in Theora. There are to new options:
- use `libyuv` (not tested, but probably much faster - everything is assembly (SIMD) :) ),
- use GLSL and multitexture (every plane as separate a texture) - I think it is the best method. Example shader is here: https://github.com/zaps166/QMPlay2/blob/master/src/modules/OpenGL2/GLSL/YCbCr.frag.

What should I use? Or use the same as in Theora and improve it in the future?

**Comment by zaps166** [comment]
`libyuv` integrated (about 4x faster, uses inline assembly for GCC and MSVC), `yuv2rgb.h` removed
`libvpx` integrated, but w/o assembly - currently it is slow, but works

also fixed Theora x86 optimizations (SCons bug)

https://github.com/zaps166/godot/commits/webm

**Comment by zaps166** [comment]
x86 (only x86-64 due to missing detection in macros) assembly is almost done. other CPUs are in TODO.

All-in-one commit for testing: https://github.com/zaps166/godot/commit/b56fe6be6cd5b2b956d7da020253f5252fa4107e

WIP branch with more commits (not all-in-one): https://github.com/zaps166/godot/commits/webm

So, most is DONE now. I'm waiting for a feedback (how it works, bugs, etc.) and for a help with SCons (ARM, MIPS, YASM fixes, etc) :)
Do a WIP PR or do it when it will be finished?

I don't use "audio/video_delay_compensation_ms" - what is it? Currently audio is perfectly synchronized with video for me in WebM.

**Comment by punto-** [comment]
There was a big thread a while ago (maybe this one
https://github.com/godotengine/godot/issues/3098) about assembler code for
theora in 32 and 64 bits with the MS compiler, wasn't it fixed then?

**Comment by zaps166** [comment]
While compiling Godot (found when implementing WebM) - the line in theora SCub `env.Append(CCFLAGS=["-DOC_X86_ASM"])` doesn't pass this flag to the compiler... The assembly files are compiled, but not used due to missing flag in C code. I've moved this line to parent SCub file with proper `if` condition - now it compiles with this flag, so should be OK.

Maybe something is wrong with my SCons or it behaves differently between versions?

**Comment by zaps166** [comment]
Hmm... I was doing something else and next I forgot about this patch (nobody commented here) :smile: It'll be nice to finish this feature - has anyone tried it from my fork (I remember that the C++ code is finished, the only problem is in SCons on non-x86 platforms) :) ?

**Comment by reduz** [comment]
oh right, it used a non standard assembly compiler, right?

**Comment by vnen** [comment]
Getting some build errors with MSVC:

```
drivers\webm\libvpx\vp8/common/threading.h(69): fatal error C1083: Cannot open include file: 'semaphore.h': No such file or directory
scons: *** [drivers\webm\libvpx\vp8\vp8_dx_iface.windows.tools.64.webm.obj] Error 2
drivers\webm\libvpx\vp8\common\generic\systemdependent.c(24): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory
scons: *** [drivers\webm\libvpx\vp8\common\generic\systemdependent.windows.tools.64.webm.obj] Error 2
scons: building terminated because of errors.
```

**Comment by zaps166** [comment]
@reduz

Mostly DONE:
- For x86 it must be compiled using `yasm`. I've included most assembly files in SCons which uses system `yasm` assembler (it must be installed system-wide), but it was tested by me only on Linux (and it lacks some files, but performance is good comparing to plain C code).

TODO:
- For MIPS everything is in C code (including SIMD), so files must be properly added to SCons for MIPS.
- For ARM most of SIMD(NEON) code is in C, some files are in assembly, but currently I don't know what is it, but it doesn't look like GNU Assembler. Maybe the Assembly NEON files are not really necessary for good performance, so only C NEON code will be used (properly configure it in SCons).

@vnen 
Thanks for testing in MSVC. Please try with this patch: https://github.com/zaps166/godot/commit/af8d208c69978ada7ed99bd87b6ad916a15af499 . I'll also try MSVC later. I think that it'll fail on YASM, so please download http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win32.exe, rename it to `yasm.exe` and add it to PATH (system-wide). Maybe it will work... (needs tests on all platforms!) :)

**Comment by vnen** [comment]
@zaps166 didn't fail to build C code but SCons is passing some MSVC arguments to YASM:

```
yasm -I drivers/webm/libvpx -f elf64 /nologo /c /Fodrivers\webm\libvpx\vpx_dsp\x86\intrapred_sse2.windows.tools.64.webm.obj drivers\webm\libvpx\vpx_dsp\x86\intrapred_sse2.asm
yasm: warning: can open only one input file, only the last file will be processed
```

This results in no `.obj` file which fails later in the linking phase.

**Comment by zaps166** [comment]
@vnen Right, I've just installed Win7 and VS 2015 on VirtualBox. Problem with elf64 is simple, just replace it in SCons for win32 or win64, but currently I don't know how to **not** pass Visual Studio arguments for yasm :cry:

Configuring SCons (I don't know SCons and Python) for every platform is much more difficult than writing WebM support in C++ :smile:

Is it possible to share precompiled static library for `libvpx` (every platform) and just link Godot for it if `webm` is enabled?

**Comment by akien-mga** [comment]
> Is it possible to share precompiled static library for libvpx (every platform) and just link Godot for it if webm is enabled?

Nope, everything should be buildable from source.

**Comment by zaps166** [comment]
@akien-mga Ok!

Now I'm able to compile Godot (32-bit) using MSVC in Windows :) I'll push commit later.

**Comment by zaps166** [comment]
@vnen Now it should compile and run on Windows :) Could you please try to compile and play WebM video? Supported codecs in WebM: VP8, VP9, Vorbis, Opus.

Rebased branch, one commit: https://github.com/zaps166/godot/commits/webm-all
Old branch, many commits (to know what was changed): https://github.com/zaps166/godot/commits/webm

Tested:
- Windows 7 SP1 VS 2015 32-bit compilation,
- Linux X11 64-bit,
- Linux X11 32-bit (compilation only, because I don't have 32-bit libs in GCC 5.x for linking).

TODO:
- ARM and MIPS CPU architectures,
- Linux ARM,
- Android, macOS, IOS,
- Windows MinGW,
- enable C code for AVX2 and SSSE3 SIMD.

I can't test every platform, it is impossible... At least I can try Android (phone) and macOS (VirtualBox).

**Comment by vnen** [comment]
Working fine on Windows 10 64-bits, built with MSVC.

I couldn't build for Windows with MinGW though (using the Ubuntu Bash on Windows, which should be equivalent to Ubuntu Trusty). It seems to be a configuration problem:

```
drivers/webm/libvpx/vpx_ports/arm_cpudetect.c:173:2: error: #error "--enable-runtime-cpu-detect selected, but no CPU detection method " "available for your platform. Reconfigure with --disable-runtime-cpu-detect."
 #error "--enable-runtime-cpu-detect selected, but no CPU detection method "
```

**Comment by zaps166** [comment]
Fails in ARM code on x86... But it is added for all architectures in SCons (it doesn't fail on MSVC and linux). Could you replace `drivers/webm/libvpx/vpx_ports/arm_cpudetect.c` line 61:

```C
#elif defined(_MSC_VER) /* end !CONFIG_RUNTIME_CPU_DETECT */
```
by
```C
#elif defined(_WIN32) /* end !CONFIG_RUNTIME_CPU_DETECT */
```
and try again?

**Comment by zaps166** [comment]
...Or just don't compile it since ARM is not-yet supported (force-updated `webm-all` branch).

**Comment by reduz** [comment]
What about Android, iOS?

**Comment by zaps166** [comment]
AFAK iOS is only ARM/AArch64.
Android is ARM, x86 and MIPS. Android x86 should work with YASM. MIPS i C-only (with SIMD), but ARM - I don't know how to compile ARM assembly (it is no GAS syntax). Maybe now just use C-code (C SIMD code) and later try to optimize it better using pure ASM files for ARM.

**Comment by zaps166** [comment]
Android x86 and macOS should now compile.

@reduz Does Godot support MIPS CPUs on some platforms?

**Comment by reduz** [comment]
No.. I know some Android devices are MIPS but we don't really support them

**Comment by zaps166** [comment]
@reduz 
> What about Android, iOS?

Android ARMv6, ARMv7 and x86: DONE (tested compilation only).

---

IPhone, OSX, Haiku, BB10, JavaScript, Windows(MinGW), Windows x64, WinRT: Not tested, maybe it works.

All platforms and CPUs should now work - if something is unknown or unsupported it should fallback to slow C code (prints info in console). x86 requires `yasm` in system path (it can be also in Godot directory on Windows).

---

TODO: Minor SSSE3, AVX2 and NEON optimizations (mostly DONE). It can also be done later.

Should I open a PR?

---

https://github.com/zaps166/godot/tree/webm-all (one commit, new Godot) HEAD:6b1444101b3a3005813dfc9a5e29a1ec40ff7dfb
https://github.com/zaps166/godot/tree/webm (a few commits, old Godot) HEAD:6b2317dd81cb806bf0b1856371e77d03c3f16d99

**Comment by reduz** [comment]
yeah, if you can also please make it detect if yasm is available via an
environment variable and print a warning if not found (then fallback to C
code), so users who don't need VP9 are not forced to download yasm.

**Comment by akien-mga** [comment]
One note regarding the added external dependency(ies):
- Please add the unmodified upstream source(s) in its (their) own commit (i.e. just `git add drivers/webm/lib*`)
- If possible, try not to modify their source at all, and just configure what needs to be in the buildsystem or via the driver bindings.
- If you really need to modify the upstream source, please make it in its own commit too, documenting all necessary changes so that they can be reapplied in the future when updating the libs.

**Comment by zaps166** [comment]
@akien-mga

> Please add the unmodified upstream source(s) in its (their) own commit (i.e. just git add drivers/webm/lib*)

Unmodified **all** source files or unmodified only necessary files (to save a lot of repository size, e.g. encoder and MIPS SIMD are not used)?

I use four libraries:
- `libyuv` from `libvpx-1.6.0/third_party`,
- `libvpx` - the VP8/VP9 library,
- `libsimplewebm` which already contains `libwebm` from `libvpx-1.6.0/third_party` - https://github.com/zaps166/libsimplewebm

> If possible, try not to modify their source at all, and just configure what needs to be in the buildsystem or via the driver bindings.

Auto-generated files during `libvpx` configuration are changed (a lot of changes), so I'll do a separate commit for this. Also `libwebm` is modified for easy Android compilation (don't use C++ headers).

**Comment by akien-mga** [comment]
> Unmodified all source files or unmodified only necessary files (to save a lot of repository size, e.g. encoder and MIPS SIMD are not used)?

Only necessary source files would be fine, we don't want indeed to bundle the whole contents of the upstream tarball with their buildsystem, examples, etc.

**Comment by zaps166** [comment]
PR: #6490

**Comment by zaps166** [comment]
PR is merged, so I think this issue can be closed :)

**Comment by Dillybob92** [comment]
@zaps166 Hey, I tried the latest build http://fixnum.org/godot/ here, both [64](http://fixnum.org/godot/16_11_30__11_27_45/tools/godot.windows.tools.64.exe) and 32 bit versions. I'm running on Windows 7, 64-bit

When selecting the .webm video file, godot instantly crashes:

![image](https://cloud.githubusercontent.com/assets/23731618/20784478/45e292c4-b74f-11e6-88aa-53f339f88621.png)

Full error:
```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	godot.windows.tools.64 (1).exe
  Application Version:	2.2.0.0
  Application Timestamp:	a140a138
  Fault Module Name:	godot.windows.tools.64 (1).exe
  Fault Module Version:	2.2.0.0
  Fault Module Timestamp:	a140a138
  Exception Code:	c0000005
  Exception Offset:	0000000000269812
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	781e
  Additional Information 2:	781e5a85ab2727cddc2ddaf44755c6ef
  Additional Information 3:	d5a4
  Additional Information 4:	d5a4b8627b171ec0cc3b651e1bd1c7ca
```

Obviously that error message doesn't really help, but do I need to make a new github issue for this?

**Comment by akien-mga** [comment]
> but do I need to make a new github issue for this?

Yes, as this issue is closed and has been fixed.

**Comment by Dillybob92** [comment]
Oh ok. I just wasn't sure if 2.2 issues were ok to post :P

**Comment by akien-mga** [comment]
Well 2.2 == 3.0, and at some time we want to be able to release it as stable, so yes ;)

**Comment by Calinou** [comment]
Note for future readers stumbling upon this PR from a web search: [built-in WebM support will be removed in Godot 4.0](https://github.com/godotengine/godot/pull/53833) to be [moved to an official extension](https://github.com/godotengine/godot-proposals/issues/3286).
