### ISSUE TITLE
Having more general information icons for the scene panel.

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#5887]
https://dl.dropboxusercontent.com/u/67740160/Scene_Panel.png - the popup node has a warning icon next to it. Clicking on it will tell you about the node's default behaviour. This doesn't appear to be something to _warn_ about, although it's still obviously a notification. Maybe a more general "information"-style icon in addition (for things like this) would be nice?

**Comment by bojidar-bg** [comment]
It is just a warning that it wouldn't show if you just leave it like that in the game.

**Comment by neikeq** [comment]
I agree with OP. Some people (including me) may get annoyed with such permanent warnings that can't be fixed. Specially those who treat warnings are errors.

**Comment by akien-mga** [comment]
Is there any other example than Panel though? Most other warnings that I saw were true warnings that indicated something that would not be working in the game.

For Panel the warning should disappear if the node is hidden, like it would be in the running game; it's intent is to make sure people understand why the popup won't show up in the game even though they made it "visible" in the editor.

**Comment by neikeq** [comment]
@akien-mga You are right. I completely forgot the warning disappears after hiding the Popup (Panel?? :P).

**Comment by akien-mga** [comment]
> the Popup (Panel?? :P).

Got confused by the URL in the OP :p

**Comment by akien-mga** [comment]
So the consensus is "current behaviour is fine".
