### ISSUE TITLE
Cyclic Autoload Singleton Plugin Bug.

### ISSUE THREAD

**Issue by Multirious** [godotengine/godot#58871]
### Godot version

v3.4.3.stable.official [242c05d12]

### System information

Windows 10

### Issue description

Cannot enable plugin because autoload is not declared. Autoload is not declared because plugin is disable.

Reloading project does not help.
You have to remove all the singleton reference to temporary fix the bug.

### Steps to reproduce

1. Make a plugin.
2. Create a singleton script and add to plugin.
3. Create any script that reference to that singleton and add to plugin.
4. Disable the plugin and reload project.
5. Try to enable the plugin and now you can't until you remove that reference.

### Minimal reproduction project

[Cyclic Autoload Singleton Plugin Bug.zip](https://github.com/godotengine/godot/files/8199572/Cyclic.Autoload.Singleton.Plugin.Bug.zip)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/36001, https://github.com/godotengine/godot/issues/32165 and https://github.com/godotengine/godot/issues/21461. This probably can't be fixed until Godot 4.0.

**Comment by takaturre** [comment]
Ran into this or similar problem in Godot 4.0.beta4 (on Win 11). Here's some more info:

### Steps
1. Have a singleton, eg. MyGlobal.
2. Make that singleton preload another class, eg. MySubGlobal (with some static funcs).
3. Refer from that sub-singleton (MySubGlobal) back to the main singleton (MyGlobal).
4. It works fine on the _editor_ (including typing), but press F6 and there's a crash while parsing. (This worked still in v3.5.)

### Pics
![image](https://user-images.githubusercontent.com/16601926/201535589-c3a75242-0659-485f-b1cc-02470f8d8bff.png)

![image](https://user-images.githubusercontent.com/16601926/201535532-27b1d4a6-afaa-4a6c-8342-5a30ec2549c4.png)

### Extra notes
- The error is triggered if MyGlobal is present in a sub script - but only on game side. 
- You can try to work around it, by eg. using another singleton to get the MyGlobal singleton, it will work:
     * For example, make a new singleton called Empty (with empty Node based script), and use `Empty.get_parent().get_node("MyGlobal")` in place of `MyGlobal`. It will work.
     * However. In a more complex project, this simple "hack ref" will tremendously increase the Godot start up time. Without that hack (using MyGlobal directly), the project loads up in about 10 seconds. Using the above Empty hack ref technique, the start up time goes up to about 45-50 seconds..!
         * Note. I also noticed that preloading sub portions (like MySubGlobal) from other sub portions increases startup loading time - so that's why switched back to using the MyGlobal ref. 
- Note that using `var MySubGlobal = load(...) if Engine.is_editor_hint() else null`, will also work. (But then you lose all that precious typing that comes with const preload.)
- This could potentially be solved by #67714

### Minimal reproduction project
[SingletonSelfRef.zip](https://github.com/godotengine/godot/files/9997906/SingletonSelfRef.zip)

**Comment by adamscott** [comment]
@takaturre I tested your MRP and it worked flawlessly on my PR.

**Comment by takaturre** [comment]
Tested both MRP's in v4.0.beta5. The original MRP works, but there's still a compilation error when pressing F6 on the SingletonSelfRef MRP (the problem seems exactly like it was). 

If I understood correctly, #67714 has been merged into beta5, and @adamscott did test this before merge. ... So did something else break it? (And also, should this latter be another issue, since the original mrp works fine?)

**Comment by akien-mga** [comment]
> If I understood correctly, https://github.com/godotengine/godot/pull/67714 has been merged into beta5, and @adamscott did test this mrp before merge. ... So did something else break it?

This PR was merged 11 hours ago. Beta 5 was released 2 days prior, so it doesn't include it :)
