### ISSUE TITLE
Button Pressed TextureStyleBox texture isn't displayed.

### ISSUE THREAD

**Issue by jedesjardins** [godotengine/godot#58874]
### Godot version

3.4.stable

### System information

MacOS Monterey 12.2.1 Intel 16"

### Issue description

The button pressed TextureStyleBox's texture never displays, although the TextureStyleBox's custom content_margin IS used.

### Steps to reproduce

1. Add a TextureStyleBox to a Button's pressed style.
2. Run the project and see that the pressed style box texture isn't displayed.

### Minimal reproduction project

[ButtonTest.zip](https://github.com/godotengine/godot/files/8200330/ButtonTest.zip)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/37527.
