### ISSUE TITLE
small bug scenetree node duplication

### ISSUE THREAD

**Issue by AndHalfAFish** [godotengine/godot#58889]
### Godot version

3.4.2.stable

### System information

windows 10

### Issue description

editor settings > shortcuts > duplicate : set to ctrl+d

works if : 1) 2d/3d view selected, or, 2) script view selected + no scripts open

does not work if : script view selected + script open
=> script keeps focus => ctrl+d results in code duplication rather than node duplication

![bug_scenetree_node_dupl](https://user-images.githubusercontent.com/59080934/157181663-78ef6c6f-d009-49e4-9dfa-e98e2b1312b7.png)

### Steps to reproduce

see issue descr

**Comment by Zireael07** [comment]
Dupe of existing issue. It's fixed in 4.x, but pretty much unfixable in 3.x,

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/52861.
