### ISSUE TITLE
2.1 Beta "stop mouse" no longer stops event when mouse button 4 or 5 is pressed

### ISSUE THREAD

**Issue by UltyX** [godotengine/godot#5888]
2.1 Beta _20160721_ / on Linux

**Issue description** :
When hovering over a control node, with "stop mouse" enabled, and scrolling with the mouse wheel, the control node and its parent node both receive the input_event(event). Happens only for mouse button 4 and 5, normal mouse button presses 1 to 3 are not received by the parent control.

**Link to minimal example project**:
[ui.tar.gz](https://github.com/godotengine/godot/files/380220/ui.tar.gz)

**Comment by eska014** [comment]
Mouse wheel events are intentionally not stopped in order to allow scrolling when hovering over children of a scrollable control (see #4331)
https://github.com/godotengine/godot/blob/73f83fadc82a9fa0fd4a70dec4ecd9d4a8dde6a9/scene/main/viewport.cpp#L1607

Do you have a specific use case where you need different behavior?

**Comment by UltyX** [comment]
Yes, I use scrolling over a control node (map) to tell it to zoom in like in google maps. The event not being stopped causes my game to zoom in the map and unintentionally zoom towards the player character as well.

**Comment by UltyX** [comment]
Ok, to me this issue has been resolved by changing my control node structure to a more tree like form, since the scroll event only travels up the tree. Just had to put controlnodes that react to scroll events into different branches instead of layering them on top of each other.  

![rect4170](https://cloud.githubusercontent.com/assets/12592569/17694048/3a24b92c-63a2-11e6-9f45-a55a11942ad3.png)
