### ISSUE TITLE
Display tile name in "tile choose/pick" menu

### ISSUE THREAD

**Issue by romulox-x** [godotengine/godot#589]
I'd like to be able to display the name of each tile, which I suppose would be the sprite name in the tile editor scene, next to each tile in the left pane when editing tilemaps.  Similar tiles can be difficult to distinguish in this view, especially when they are scaled down.

**Comment by akien-mga** [comment]
Tile names are actually displayed in the tile picker in the current master branch. The PR #592 still has a couple other enhancements that could be useful (alternative row color particularly), but this very issue can be considered fixed already.
