### ISSUE TITLE
Text Editor: The "Col:" label not showing correct value

### ISSUE THREAD

**Issue by allkhor** [godotengine/godot#5890]
**Operating system or device - Godot version:**
Xubuntu 16.04 x64, godot master 8fbe804 

**Issue description** (what happened, and what was expected):
The "Col:" label not showing correct value below line 9.

![col_bug](https://cloud.githubusercontent.com/assets/1049442/17084141/6aba9b5a-51d8-11e6-909c-cd96d0cf67c9.gif)

**Steps to reproduce:**
Open any script.gd file.
Try select text below line 9 and look at col: value.

**Comment by akien-mga** [comment]
I can reproduce this too on Linux.

**Comment by vnen** [comment]
The problem is that the label is at a fixed position, when the number is bigger than one digit, it doesn't fit on the space and goes to the next line, which is off the view. A simple solution would be moving the label a little bit to the left.

**Comment by akien-mga** [comment]
Ah lol, and I was starting to investigate why TextEdit would report bad column numbers :p

**Comment by akien-mga** [comment]
It would be nice to have a better solution for this issue than just increasing a bit the minimum size; with the editor being localized, I'm pretty sure that most languages will have translations for "Line" and "Col" that are longer than English.

Ideally the label's size should be automatically adjusted to the left to fit its contents.

**Comment by akien-mga** [comment]
Setting autowrap to false improves the situation already.

**Comment by vnen** [comment]
> Ideally the label's size should be automatically adjusted to the left to fit its contents.

It did, but @reduz changed it because it was slowing down the editor (864c0e84de9c2a2c5a030ec4ee167f3793e1e962).

**Comment by akien-mga** [comment]
Ah that makes sense. Then I'd propose something like that, WDYT?
```diff
diff --git a/tools/editor/code_editor.cpp b/tools/editor/code_editor.cpp
index 6c8d25a..2c03cb1 100644
--- a/tools/editor/code_editor.cpp
+++ b/tools/editor/code_editor.cpp
@@ -1214,10 +1214,11 @@ CodeTextEditor::CodeTextEditor() {
 
        line_col = memnew( Label );
        status_bar->add_child(line_col);
+       line_col->set_align(Label::ALIGN_RIGHT);
        line_col->set_valign(Label::VALIGN_CENTER);
-       line_col->set_autowrap(true);
+       line_col->set_autowrap(true); // workaround to prevent resizing the label on each change
        line_col->set_v_size_flags(SIZE_FILL);
-       line_col->set_custom_minimum_size(Size2(100,1)*EDSCALE);
+       line_col->set_custom_minimum_size(Size2(140,1)*EDSCALE);
        status_bar->add_child( memnew( Label ) ); //to keep the height if the other labels are not visible
 ```
That ensures proper right-alignment and should give enough space for 3 digit lines + col and maybe a bit longer translations. The drawback of being right-aligned is that the start of the "Line" text changes all the time when moving the caret.

Another alternative is to just offset the label by e.g. 30px, though it would no longer be perfectly on the right ;) But maybe less bothering than a bouncing "Line" text.

Lastly, it would be possible to split this in 4 labels and just give enough place for 4 digit numbers or so.

**Comment by vnen** [comment]
Right-aligning seems a good solution. Four labels might even be better, since the "Line"/"Col" labels would be at fixed positions.

**Comment by akien-mga** [comment]
Yeah, I'm working on the 4 Label solution, I think it's the cleanest one.

**Comment by akien-mga** [comment]
Here's a test with support for 5 digits with the default font: ![spectacle jd8060](https://cloud.githubusercontent.com/assets/4701338/17084497/87ae4a2c-51bf-11e6-85b5-6bd00c076fca.png)
![spectacle lh8077](https://cloud.githubusercontent.com/assets/4701338/17084503/a14677ac-51bf-11e6-90a1-6d4678cb8417.png)

**Comment by akien-mga** [comment]
And with the French translation: ![spectacle yj8227](https://cloud.githubusercontent.com/assets/4701338/17084520/1fbc021e-51c0-11e6-8a92-4d077b51c611.png)

**Comment by neikeq** [comment]
I am confusing. @vnen mentions those labels are on a fixed position, but I remember adding them to a HBoxContainer when working on the search bar.

**Comment by vnen** [comment]
@neikeq that might be the problem, because the Label was resizing every time and by doing so it was also resizing the container, which was slowing everything down until @reduz changed the behavior. So if the size remains the same, even in a container it'll be in a (visually) fixed position.
