### ISSUE TITLE
Script editor dumps "Condition "p_from_line > p_to_line" is true." errors when moving mouse across top threshold

### ISSUE THREAD

**Issue by novaplusplus** [godotengine/godot#58906]
### Godot version

4.0.alpha3

### System information

Windows 10 (but has happened on linux as well)

### Issue description

Super weird. The text editor dumps that error in the console when moving the mouse over the upper threshold to the text editor - but only when the text is arranged in certain ways and scrolled to the right position. See the following.

Scrolled to one position:
![bug1](https://user-images.githubusercontent.com/3247833/157299854-f2e0b75c-5b78-4b8f-82c7-91f04559fb4b.gif)

And then another:
![bug2](https://user-images.githubusercontent.com/3247833/157299869-9bfde84d-ae22-4041-8a3a-fe4df3ba674d.gif)

(I am using a custom theme here but it is still occuring in a completely spotless copy with no changed settings)

From some quick debug outputs in my own build (have not run a full debug build yet though) it looks like at this point `p_from_line` is 1 larger than `p_to_line`

I am unsure if this occurs in other text editor instances.

### Steps to reproduce

Imitate the gifs in the description, pretty much.

### Minimal reproduction project

Not super necessary because of how simple it is, but hey why not:

[bug_test.zip](https://github.com/godotengine/godot/files/8208649/bug_test.zip)

**Comment by novaplusplus** [comment]
Update: This happens in the shader editor too.

**Comment by novaplusplus** [comment]
Cracked open ye olde callstack after getting debugging set up  - 

The function gets its bad data from here: https://github.com/godotengine/godot/blob/master/scene/gui/text_edit.cpp#L3743

**Comment by Paulb23** [comment]
I think the latter (changing the function) probably makes for a better API here.

**Comment by novaplusplus** [comment]
Hmm. I'll give it a shot and toss up a PR soon.

**Comment by akien-mga** [comment]
Fixed by #59007.
