### ISSUE TITLE
Vulkan: Red and orange lettering on editor interface 

### ISSUE THREAD

**Issue by mo-moxi-gd** [godotengine/godot#58908]
### Godot version

4.0 alpha

### System information

Debian Linux 10

### Issue description

Easier to see on the attached...

### Steps to reproduce

Load Editor in Debian 10 using Mesa Vulkan driver

### Minimal reproduction project

Load the editor in Linux

![Screenshot from 2022-03-08 17-31-26](https://user-images.githubusercontent.com/99659600/157320950-3f962760-d1d4-4df5-ba00-08cbc93bebc6.png)
x

**Comment by Calinou** [comment]
> Load Editor in Debian 10 using Mesa Vulkan drive

Are you referring to Lavapipe software rendering? If not, which graphics card model are you using?

**Comment by clayjohn** [comment]
No response, so closing. This error appears to come from texture swizzling not working (I observed the same thing in the early stages of the OpenGL renderer and the early stages of the D3D12 backend) which means it is likely a driver issue
