### ISSUE TITLE
GDScript 2.0: Methods of built-in types are not recognized as `Callable` (missing documentation)

### ISSUE THREAD

**Issue by h0lley** [godotengine/godot#58912]
### Godot version

4.0-alpha3

### System information

Ubunut, Nvidia, Vulkan

### Issue description

Methods of types such as `Signal`, `Array`, or `Dictionary` are not recognized as `Callable`.

Any methods that return void - i.e. mutate in place - would be useful to be able to pass as Callable.
In the case of Signal, we are stuck using Object's `emit_signal` instead.

### Steps to reproduce

Paste into a blank script:
```gdscript
extends Node

signal my_signal
var dict := {}
var arr := []

func _ready():
	var tween = get_tree().create_tween()

	tween.tween_callback(my_signal.emit)
	tween.tween_callback(dict.clear)
	tween.tween_callback(arr.append.bind("item"))
```
Notice errors:
> Cannot find property "emit" on base "Signal".
> Cannot find property "clear" on base "Dictionary".
> Cannot find property "append" on base "Array".

### Minimal reproduction project

skipping as reproduction is just one step

**Comment by KoBeWi** [comment]
This might be a GDScript limitation. You can workaround it with a lambda:
```GDScript
var local_dict = dict
create_tween().tween_callback(func(): local_dict.clear)
```

**Comment by h0lley** [comment]
right, lambdas, thanks for reminding me.
although I encounter another issue here:

```swift
extends Node

signal my_signal

func _ready():
	var tween = get_tree().create_tween()
	my_signal.connect(_on_my_signal)
	tween.tween_callback(func(): my_signal.emit())

func _on_my_signal():
	print("eeey")
```
> Invalid get index 'my_signal' (on base: 'Nil').

Messy workaround:
```swift
	var local_my_signal = my_signal
	tween.tween_callback(func(): local_my_signal.emit())
```

**Comment by KoBeWi** [comment]
So it's as I assumed. Should this be documented somewhere maybe? (e.g. in Callable description)

**Comment by vnen** [comment]
@KoBeWi yeah, documenting is always good. I think adding to Callable is helpful. Also, yes, I think the error message can be improved for this case.

**Comment by FeldrinH** [comment]
Regardless of whether this is a bug per se, it would be nice if this was fixed and you could treat builtins as callables. For example then `directions.map(func(x): return deg_to_rad(x))` could be replaced with `directions.map(deg_to_rad)`, which would be much more readable.

Perhaps there could be some kind of special case that if an identifier with a name is not found but a matching builtin exists then a special proxy callable is created that calls the builtin.

**Comment by rambda** [comment]
Also if built-in methods are callable, signal chaining would be more readable.
e.g. `signal1.connect(func(): signal2.emit())` -> `signal1.connect(signal2.emit)` It's necessary, afaik, when creating a wrapper for another C# class.

**Comment by vnen** [comment]
This isn't a bug because it was designed that way. At this point it should be moved to a proposal but it definitely needs to be properly documented.
