### ISSUE TITLE
Can't set ScrollContainer `horizontal_scroll` value in `_ready()`

### ISSUE THREAD

**Issue by anisc** [godotengine/godot#58914]
### Godot version

3.4

### System information

windows10 , big sur

### Issue description

When changing the property scroll_horizontal from the editor I see the change but when I play the project it doesn't take it in effect. 
I tired to set scroll_horizontal on the ready function it doesn't work neither 
I'm trying to scroll to a specific element inside the scrollcontainer when the scene start  

### Steps to reproduce

create scrollcontainer (attach a script) and control as child populated it with several buttons and change scroll_horizontal in the ready function.

**Comment by Calinou** [comment]
Does `set_deferred("scroll_horizontal", desired_value)` work?

**Comment by anisc** [comment]
@Calinou tried `set_deferred("scroll_horizontal", desired_value)` doesn't work. 
Here is the minimal project,
https://github.com/anisc/scrollContainerMinimal

**Comment by gotnospirit** [comment]
Hi,

with
>func _ready():
>	print(scroll_horizontal)   # prints 0
>	scroll_horizontal = 600
>	print(scroll_horizontal)   # prints 100

we can see that the value is bound to the default max value of a Range object.

If we directly use the GUI to set this property to 600, the first print will be 100.

and with
>func _process(delta):
>	if scroll_horizontal != 600:
>		print(scroll_horizontal)   # prints 0
>		scroll_horizontal = 600

we can see that at the first call of _process, the value of scroll_horizontal is now 0, which also means that even if we just use the GUI to set a starting value, the scrollbar will always start at 0

**Comment by gotnospirit** [comment]
Also, if we save the project after setting the scroll_horizontal to any value using the GUI, we can see that the ScrollContainer.tscn file reflects it, but if you reopen the Godot editor with this project once again, it displays a value of 0 for Horizontal.

I did test it with a custom build of the 3.x branch and the same result with the Godot_v3.4.3-stable_win64.exe build
![Sans titre](https://user-images.githubusercontent.com/12656483/159645766-9d934827-e22e-46ba-aec4-37b489dea804.png)

**Comment by Rindbee** [comment]
I can confirm the issue.
I guess the reason is that the `max` of the internal `ScrollBar` is initialized to `100` (default value). Causes `value` to be clamped between `0` (`min`) and `100` (`max`).

**Comment by stmSi** [comment]
in 3.x repo: `child_max_size` is the key to updating the max value. `child_max_size` value is determined in the `_update_dimensions()`.... then `update_scrollbars()` is where actually max value is set.

I try to put this two functions side-by-side inside `NOTIFICATION_ENTER_TREE` or `NOTIFICATION_READY`... none of them work. So directly inserting them in `set_(h/v)_scroll` works.

in 4.0 repo: `update_scrollbars()`  only is needed inside `set_(h/v)_scroll`.

**Comment by stmSi** [comment]
@Calinou @anisc 
`set_deferred` doesn't work
but `call_deferred` works.
```
func _ready():
	call_deferred("scroll")

func scroll():
	scroll_vertical = get_v_scroll_bar().max_value 
	scroll_horizontal = get_h_scroll_bar().max_value
```
