### ISSUE TITLE
FileSystem gets in blank setting up input.

### ISSUE THREAD

**Issue by chriztheanvill** [godotengine/godot#58911]
### Godot version

4.0.alpha4

### System information

Ubuntu Budgie 21.10

### Issue description

I was setting up the input: Keyboard and Joysticks, then the panel "FileSystem gets in blank. To fix it, I moved the panel to another position, then back to original position.

### Steps to reproduce

Enter to Project >  Project Settings > Input Map, then Add some acctions.
After that, close the Project Settings window.
The FileSystem is in Blank.

**Comment by Calinou** [comment]
@chriztheanvill Can you take a screenshot of the editor when this happens?

Also, can you reproduce this on 3.4.3

**Comment by chriztheanvill** [comment]
![Godot](https://user-images.githubusercontent.com/37992958/157377159-7cc4d6a2-68af-446a-9e1b-3757de50d481.png)

No, in 3.4.3, does not happen.

I've tried to have the same result making another project, but does not happened.

**Comment by nathanfranke** [comment]
Fixed by https://github.com/godotengine/godot/pull/61435
