### ISSUE TITLE
Alpha Scissor does not cast shadows with depth_draw_opaque, even though manually discarding does

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot#58924]
### Godot version

3.4.3.stable

### System information

Windows 10, GLES3, GTX 980Ti

### Issue description

As far as I understand, using alpha scissor should just discard transparent pixels, which means it should be able to cast shadows using "depth_draw_opaque", but it doesn't.

![image](https://user-images.githubusercontent.com/4955051/157436894-6b0d8f01-f75c-4fda-bb06-67a65941129b.png)

Alpha Scissor:
```
shader_type spatial;
render_mode depth_draw_opaque, cull_disabled;
uniform vec4 albedo : hint_color;
uniform sampler2D texture_albedo : hint_albedo;
uniform float alpha_scissor_threshold;

void fragment() {
	vec4 albedo_tex = texture(texture_albedo, UV);
	ALBEDO = albedo.rgb * albedo_tex.rgb;
	ALPHA = albedo.a * albedo_tex.a;
	ALPHA_SCISSOR=alpha_scissor_threshold;
}
```

Manual Discard:
```
shader_type spatial;
render_mode depth_draw_opaque, cull_disabled;
uniform vec4 albedo : hint_color;
uniform sampler2D texture_albedo : hint_albedo;
uniform float alpha_scissor_threshold;

void fragment() {
	vec4 albedo_tex = texture(texture_albedo, UV);
	ALBEDO = albedo.rgb * albedo_tex.rgb;
	if (albedo.a * albedo_tex.a < alpha_scissor_threshold)
		discard;
}
```

It seems that as soon as "ALPHA" gets set in a shader, even if it's just set to "1.0" shadow casting is disabled in "depth_draw_opaque" mode.

EDIT: I'm guessing the shader compiler looks for the ALPHA keywords and puts everything that has it in the transparent render queue? But if both ALPHA and ALPHA SCISSOR is present and depth_draw_opaque is set, I don't think it should send it to the transparent render queue.

### Steps to reproduce

Try out the shaders listed above or open the attached project.

### Minimal reproduction project

[Alpha Scissor Tests.zip](https://github.com/godotengine/godot/files/8214388/Alpha.Scissor.Tests.zip)

**Comment by Ansraer** [comment]
What happens when you use ´depth_draw_alpha_prepass´ instead?

**Comment by Ansraer** [comment]
@Calinou Are you sure this should be catehorized as a bug? I am fairly certain that without the alpha depth prepass this is intended behaviour.

**Comment by Arnklit** [comment]
Well yes it works with `depth_draw_alpha_prepass`, my point is that it should work without, since there is no alpha, it's supposed to just be discarding.

**Comment by Calinou** [comment]
I also agree with Arnklit that the transparent pipeline should not be used here. It lowers performance and causes transparency sorting issues.

**Comment by Ansraer** [comment]
I think I see what the problem is: The moment you use `ALPHA` in your shader `SceneShaderForwardClustered` sets `uses_alpha` to true, which in turn causes `RenderForwardClustered::_geometry_instance_add_surface_with_material` to not set the depth and shadow flags unless you also use `depth_pre_pass`.

I could make a PR to re-enable depth and shadows when people use `ALPHA_SCISSOR `in their shader code. If necessary people could still turn it back off with the `depth_draw_never` or `depth_test_disabled` flags.

**Comment by clayjohn** [comment]
> I think I see what the problem is: The moment you use ALPHA in your shader SceneShaderForwardClustered sets uses_alpha to true, which in turn causes RenderForwardClustered::_geometry_instance_add_surface_with_material to not set the depth and shadow flags unless you also use depth_pre_pass.

While you are correct about 4.0, note that the bug report is for version 3.4.3 so you are looking in the wrong place :)

> I could make a PR to re-enable depth and shadows when people use ALPHA_SCISSOR in their shader code. If necessary people could still turn it back off with the depth_draw_never or depth_test_disabled flags.

I'm not sure about this. 

In GLES3 objects with alpha and alpha scissor should go down the opaque pipeline
https://github.com/godotengine/godot/blob/fd082ec39a2441b370d81de5895d24bc30a88a51/drivers/gles3/rasterizer_scene_gles3.cpp#L2281-L2283

https://github.com/godotengine/godot/blob/fd082ec39a2441b370d81de5895d24bc30a88a51/drivers/gles3/rasterizer_scene_gles3.cpp#L2326

In the MRP it is clear that the alpha-scissored mesh is going down the opaque pipeline (at least the prepass) as it is included in the SSAO. 

Something else is going on here resulting in the material not getting drawn.

**Comment by Ansraer** [comment]
> While you are correct about 4.0, note that the bug report is for version 3.4.3 so you are looking in the wrong place :)

True. But after noticing that this bug existed in 4.0 as well I decided to start there and then try to backport it once I have a working solution.

![image](https://user-images.githubusercontent.com/6329420/157542191-6eb1264f-f474-41fa-8829-0eb011a8e9ee.png)
