### ISSUE TITLE
Black screen on Android when low processor mode was enabled

### ISSUE THREAD

**Issue by lemon37564** [godotengine/godot#58932]
### Godot version

4.0 alpha-4

### System information

Android 9 (phone), Android 11 (tablet)

### Issue description

When the low processor mode is enabled, leave the game temporary and then go back, it will be black screen until the frame is updated

https://user-images.githubusercontent.com/65079334/157463423-738fb95d-b343-4835-b426-211e20d7218a.mp4

.

### Steps to reproduce

1. create a project
2. enable low processor mode
3. export apk
4. install on phone
5. open the game
6. leave the game with home button
7. go back to the game

### Minimal reproduction project

[tested.zip](https://github.com/godotengine/godot/files/8215524/tested.zip)

**Comment by tavurth** [comment]
https://github.com/godotengine/godot/pull/55604
