### ISSUE TITLE
Godot4.0 alpha 4, MacOSX Unable to load .tscn files created by alpha 3

### ISSUE THREAD

**Issue by h5n1xp** [godotengine/godot#58930]
### Godot version

v4.0.alpha4.official [f47097973]

### System information

macOS Big Sur 11.6.3

### Issue description

I have been writing a test project in 4.0 alpha builds to test it. Project file saved by alpha 3 loads in to alpha 4 but Godot just reports an error "Error while loading file 'test.tscn'

### Steps to reproduce

Create a project in Alpha 3, create a 2D scene. Save project.
Load into Alpha 4 and the error occurs.

**Comment by akien-mga** [comment]
I can't reproduce it with a simple project that has a 2D scene (Node2D).

Can you provide the project you're testing with, or more details on the error? There should be plenty of details in the terminal output.

**Comment by h5n1xp** [comment]
> I can't reproduce it with a simple project that has a 2D scene (Node2D).
> 
> Can you provide the project you're testing with, or more details on the error? There should be plenty of details in the terminal output.

Happy to share the project file with you, but I can't share publicly.

**Comment by akien-mga** [comment]
Well I'd be fine with an error log or clearer steps to reproduce as it seems to require more steps than described.

But otherwise yes you can share files privately (see email on my GH profile: https://github.com/akien-mga/) and I can try to extract a minimal reproduction project.

**Comment by h5n1xp** [comment]
Email sent :)

**Comment by akien-mga** [comment]
Thanks for the test project.

As I suspected the log output explains the error:
```
ERROR: No loader found for resource: res://.godot/imported/TileMap.png-327b12daea89996a5fa969985a42d558.stex.
   at: _load (core/io/resource_loader.cpp:213)
ERROR: Failed loading resource: res://TileMap.png. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:205)
ERROR: No loader found for resource: res://.godot/imported/Aarbron SpriteSheet.png-dc6abd42c2e1072e4c9bba7b7f25e222.stex.
   at: _load (core/io/resource_loader.cpp:213)
ERROR: Failed loading resource: res://Aarbron SpriteSheet.png. Make sure resources have been imported by opening the project in the editor at least once.
```
(and plenty more)

That's because `StreamTexture2D` has been renamed to `CompressedTexture2D`. You need to delete the `.godot/imported/` folder to force reimporting the textures, and then it should work fine.

That's an expected change during alpha as we're still improving the API before we freeze it for 4.0 stable.

**Comment by h5n1xp** [comment]
Amazing! Many thanks for solving this 👍
