### ISSUE TITLE
Classes reference: Operators not defined as part of the class.

### ISSUE THREAD

**Issue by Karmavil** [godotengine/godot#58936]
### Godot version

4.0.dev (922348f)

### System information

Debian x64, gcc (GCC) 11.2.0, Python 3.9.9

### Issue description

Operators not defined as part of the class (i.e. operator+ for the Array class) are being overwritten and defined by the tool

### Steps to reproduce

Remove or comment any operator without a description.
Compile.
Generate documentation.
This result in the redefinition of an empty operator

**Comment by akien-mga** [comment]
That's a misunderstand. The class reference XML is generated by `doctool`, everything is shows **is** part of the class.

Array has `operator+`, that's Array concatenation. You shouldn't remove sections from the XML.

**Comment by Karmavil** [comment]
Where? It is not defined, as well as operator!= without arguments

**Comment by Karmavil** [comment]
This was not funny [#59149](https://github.com/godotengine/godot/pull/59149)
But the contribution is welcome and the changes are really useful (IMHO) given the current lack of documentation (description) of the different Variant operator classes.
My PR [#58934](https://github.com/godotengine/godot/pull/58934) is a mess! I did the best I could but honestly I don't know if it possible to sqash considering there are different changes to the file. Should I cancel the PR or you can handle it?

I think there's still a change pending: it is not possible the index opertor (or `operator at`) returns void.
