### ISSUE TITLE
HeightMapShape is too small by one cell in each direction

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#58933]
### Godot version

v3.4.3.stable.official [242c05d12]

### System information

Mac OSX (Intel 2019)

### Issue description

The `HeightMapShape` is too small by one cell in every direction.

`map_width` and `map_depth` set to `300`:
<img width="1024" alt="Screenshot 2022-03-09 at 18 18 14" src="https://user-images.githubusercontent.com/100964/157471844-316a7940-62ba-4feb-8383-61620da99ff8.png">

`map_width` and `map_depth` set to `301`
<img width="1024" alt="Screenshot 2022-03-09 at 18 18 40" src="https://user-images.githubusercontent.com/100964/157471884-ef24b2a9-9912-4d84-afb6-0855038e3dcc.png">

This is exaggerated when scaling the `HeightMapShape`, here it is with size `30` scaled by `10x`:
<img width="1024" alt="Screenshot 2022-03-09 at 18 16 33" src="https://user-images.githubusercontent.com/100964/157472071-ccd8d869-23b9-48cc-9ede-7e6890ab4ffa.png">

And here is it with size `31`:
<img width="1024" alt="Screenshot 2022-03-09 at 18 16 14" src="https://user-images.githubusercontent.com/100964/157472288-78079b74-72fb-472e-81fb-4b69f6067b9f.png">

### Steps to reproduce

Add a `HeightMapShape`, and a `MeshInstance` with the same size.

**Comment by Calinou** [comment]
@tavurth Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by tavurth** [comment]
I assumed this is so simple it did not require a sample but ok:

[godot-heightmap.zip](https://github.com/godotengine/godot/files/8216008/godot-heightmap.zip)

<img width="709" alt="Screenshot 2022-03-09 at 18 42 38" src="https://user-images.githubusercontent.com/100964/157476266-8c32736f-ae0f-4908-82da-cedaee0fc6db.png">

**Comment by Sauermann** [comment]
I can reproduce the behavior in v4.0.alpha.custom_build [922348f4c]

This issue stems from the following (same for `map_height`):
- The name `map_width` indicates a length
- Internally `map_width` is used as the number of vertices (= width - 1)

To solve this issue, either
- the internal calculations change to reflect the fact that `map_width` indicates a length or
- `map_width` could be renamed to `map_width_vertices` or something similar to make it clear, that this is not meant as a size

If there is consensus about which solution is better, I would implement the necessary changes.

Current workaround: use `width + 1`

**Comment by tavurth** [comment]
I think matching the Godot size is better, as almost everything else uses this as their size calculation.

When I spawn a `MeshInstance` of a certain size, it looks like a bug if the `HeightMapShape` I also spawned is a little bit smaller. I guess `unit size` should be standardised.

**Comment by Zylann** [comment]
I haven't implemented the `HeightMapShape` resource, but I can confirm that when talking about heightmaps, one pixel of the heightmap corresponds to a vertex in the final geometry. So if initially you start from a length of 1, that means one 1x1 quad, which needs 2 vertices, so your heightmap should be length+1. I had to account for that too in my plugin, not just for collisions, but rendering as well.

I'm not sure what fix you intend to do though? I guess if you mean changing the meaning of properties of the `HeightMapShape` *resource object* then these properties could use a size unit instead of a pixel unit, I guess?

**Comment by Sauermann** [comment]
Thanks, I believe that it would be better if `map_width` would denote spatial units. Since there were no objections against this solution, I implemented these.

**Comment by Calinou** [comment]
Remember to open a pull request to document this in `3.x`, since we can't change it there.

**Comment by Zylann** [comment]
Note there will be a point of confusion either way: if the properties are in pixels, then they will need a `+1` when wanting a visual length. But if the properties are distance, then working with the pixels will always require a `-1`. However I don't know if enough people use this class directly to get a consensus on changing these properties?
