### ISSUE TITLE
Theme editor incorrectly names tabs in it's TabContiner with auto-generated names

### ISSUE THREAD

**Issue by NineAlexT** [godotengine/godot#58949]
### Godot version

4.0 Alpha 4

### System information

Kubuntu 20.04, Nvidia GTX 1060, Driver 510, Vulkan

### Issue description

![image](https://user-images.githubusercontent.com/60285548/157537136-91327698-009f-4c2a-b5dd-fcec2a43f58d.png)
Tabs in the TabContainer are names things like "@@ 11035" instead of "Color."

### Steps to reproduce

Create a new theme, look at the tab names on the right hand side of the theme editor.

**Comment by Calinou** [comment]
This is likely a regression from https://github.com/godotengine/godot/pull/58687.

cc @YeldhamDev

**Comment by KoBeWi** [comment]
This was already fixed by #58850, but unfortunately the fix wasn't merged in time for alpha.
