### ISSUE TITLE
Godot 4 alpha 4: can't use any image texture in the editor

### ISSUE THREAD

**Issue by kreaninw** [godotengine/godot#58947]
### Godot version

v4.0.alpha4.official [f47097973]

### System information

Windows 11, Vulkan Clustered, Intel UHD Graphics 620 v30.0.101.1340

### Issue description

I can't use any image texture in the editor, as shown in the screen recording below:

https://user-images.githubusercontent.com/1403194/157533915-cf5a77f8-f6e0-431c-9352-1d3e61e63b28.mp4

This is working fine in alpha 3.

I expect to be able to use image files in the engine.

### Steps to reproduce

Drag an image file from the FileSystem window to the 2D view in the editor. You won't be able to use it.

**Comment by akien-mga** [comment]
Delete your `.godot/imported` folder to force a reimport.

**Comment by kreaninw** [comment]
> Delete your `.godot/imported` folder to force a reimport.
> 
> This is expected, the texture types changed name between alpha 3 and alpha 4.

Thanks, it's working now. I will close this issue.
