### ISSUE TITLE
Godot.NET.Sdk cannot be found / Godot.NET.Sdk is not downloading on building first solution

### ISSUE THREAD

**Issue by NS-Unfair** [godotengine/godot#58955]
### Godot version

v3.4.3 stable

### System information

Windows 10 v10.0.19043

### Issue description

I find this VERY frustrating that I can't use C# with Godot because of a documentation issue. The issue is I don't have Godot.NET.Sdk installed on my PC and it prevents Godot from creating a solution. The build tool I am using is MSBuild (VS Build Tools.)

I'm using the zip version of Godot.

Edit: I have recently found out that this is a bug in Godot and not a documentation issue.

### Steps to reproduce

Install the stuff required for Godot mono version (doesn't explain how to install Godot.NET.Sdk)

Install Godot mono version, set MSBuild as the Mono Build Tool, and try running a project using C#.

### Minimal reproduction project

(Any project using C#)

**Comment by rick551a** [comment]
You need to be online when making the solution for the first time. This will download the requisite Godot.NET.Sdk stuff.

**Comment by NS-Unfair** [comment]
Well, it didn't download anything @rick551a. It is broken

**Comment by NS-Unfair** [comment]
@rick551a I have no idea what you are talking about. Can you elaborate on that and give me instructions on how I can actually do this?

**Comment by NS-Unfair** [comment]
Do you mean I have to be connected to the internet when making the solution for the first time?

**Comment by rick551a** [comment]
Sorry about the delay in reply. Heres what worked for me:

1) Install .NET SDK from https://dotnet.microsoft.com/en-us/download/dotnet/3.1

2) in Godot, open Editor -> Editor Settings..., then search for Build Tool. Select dotnet CLI from the dropdown.

3)Now be online for the first c# script you make. That should do it

**Comment by NS-Unfair** [comment]
It still fails to find Godot.NET.Sdk after following these instructions. Is there a manual download for this SDK?

**Comment by rick551a** [comment]
Oh wait, have you installed mono?
https://www.mono-project.com/download/stable/

Looks like a similar issue was raised here, and solved by installing mono:
https://github.com/godotengine/godot/issues/49139

**Comment by NS-Unfair** [comment]
Yes lmao, none of that is the issue. The only thing I need is the freaking Sdk. @rick551a

**Comment by NS-Unfair** [comment]
I can tell you I have everything installed and downloaded for Godot Mono to run. The only thing missing is the Sdk.

**Comment by NS-Unfair** [comment]
I've noticed that the people who have Godot Mono working have built the executable from source. I think the release version is broken.

**Comment by Calinou** [comment]
@NS-Unfair PS: In the future, please use the **Edit** button (located behind the **…** icon in the top-right corner of your comments) instead of multi-posting.

**Comment by rick551a** [comment]
Here, you can use my godot.net.sdk files:

https://ufile.io/buvu3ssm

Extract to C:\Users\YOURUSERNAME

The interesting thing is that there is no godot.net.sdk files for 3.4, it only goes up to 3.3.0!
I wonder if it's still looking for the 3.3.0 godot.net.sdk files in 3.4.x? hmmm

**Comment by njdf18** [comment]
I got
"[fail]: OmniSharp.MSBuild.ProjectLoader
        C:\Program Files\dotnet\sdk\6.0.201\Sdks\Godot.NET.Sdk\Sdk not found. Check that a recent enough .NET SDK is installed and/or increase the version specified in global.json." from OmniSharp Log after updating to 3.4.3
Is it same bug?

**Comment by NS-Unfair** [comment]
@njdf18 yes, it is the same bug.

**Comment by akien-mga** [comment]
CC @godotengine/mono

**Comment by neikeq** [comment]
You don't need the Mono Sdk, just this should be enough:

> Sorry about the delay in reply. Heres what worked for me:
> 
>     1. Install .NET SDK from https://dotnet.microsoft.com/en-us/download/dotnet/3.1
> 
>     2. in Godot, open Editor -> Editor Settings..., then search for Build Tool. Select dotnet CLI from the dropdown.
> 
> 
> 3)Now be online for the first c# script you make. That should do it

Make sure you're online the first time you build, as `Godot.NET.Sdk` is resolved from the NuGet repository.

**Comment by neikeq** [comment]
> 

This doesn't seem to be an error from a build launched by Godot. This seems to be from VSCode?

**Comment by neikeq** [comment]
> I got "[fail]: OmniSharp.MSBuild.ProjectLoader C:\Program Files\dotnet\sdk\6.0.201\Sdks\Godot.NET.Sdk\Sdk not found. Check that a recent enough .NET SDK is installed and/or increase the version specified in global.json." from OmniSharp Log after updating to 3.4.3 Is it same bug?

This doesn't seem to be an error from a build launched by Godot. It seems to be from VSCode's C#/OmniSharp extension?

**Comment by njdf18** [comment]
@neikeq Yes, it is from OmniSharp Log.

"[warn]: OmniSharp.MSBuild.ProjectLoader
        The SDK resolver "NuGetSdkResolver" failed to run. Unable to find fallback package folder 'C:\Users\UserName\AppData\Roaming\Godot\mono\GodotNuGetFallbackFolder'.
[fail]: OmniSharp.MSBuild.ProjectLoader
        C:\Program Files\dotnet\sdk\6.0.201\Sdks\Godot.NET.Sdk\Sdk not found. Check that a recent enough .NET SDK is installed and/or increase the version specified in global.json."
I noticed that there was a [warn] above [fail], so I tried adding a folder called "GodotNuGetFallbackFolder" to C:\Users\UserName\AppData\Roaming\Godot\mono, then it was fixed.

**Comment by wangjianpeng** [comment]
> You don't need the Mono Sdk, just this should be enough:
> 
> > Sorry about the delay in reply. Heres what worked for me:
> > ```
> > 1. Install .NET SDK from https://dotnet.microsoft.com/en-us/download/dotnet/3.1
> > 
> > 2. in Godot, open Editor -> Editor Settings..., then search for Build Tool. Select dotnet CLI from the dropdown.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 3)Now be online for the first c# script you make. That should do it
> 
> Make sure you're online the first time you build, as `Godot.NET.Sdk` is resolved from the NuGet repository.

what's the difference between mono and .not core ? I just want to use mono to develop game for android .is it possible to skip the steps with mono version .

**Comment by aaronfranke** [comment]
@wangjianpeng Mono and .NET Core are two runtimes for C#. Mono is a cross-platform reimplementation of the original .NET Framework, and .NET Core is a rewrite from scratch with more modern APIs. Godot 3.x uses Mono, but you also need the .NET Core SDK installed since it includes more modern tooling such as MSBuild which is able to build Mono projects. Mono itself is optional since Godot ships with its own copy, but I recommend having it installed as well.

However, GitHub is not a support forum, it is a platform for developers to discuss code. If you wish to ask for help or are trying to learn, check out some of the other community channels: https://godotengine.org/community

**Comment by NS-Unfair** [comment]
Right now, I am so f-ing confused. I was told Godot.NET.Sdk downloads automatically, you have to install Godot.NET.Sdk using NuGet, etc. I haven't seen a single mention of having to use NuGet to install Godot.NET.Sdk in the documentation, and Godot isn't downloading it automatically as some users say. The only reason I opened this issue on Github is that I thought this was an actual bug in the code of Godot or someone forgot to add something in the documentation. There's something I'm missing that no one here is mentioning.

If the actual way to install Godot.NET.Sdk was to use NuGet and I was given loads of misinformation, I will rip the door of my room off and throw it outside my window.

**Comment by akien-mga** [comment]
Don't throw your door outside the window, you're going to hurt your back (and passersby...).

The actual way to install Godot.NET.Sdk is that it happens automatically, this is normally transparent to the user. Obviously that didn't happen in your case and that's a bug, and you could work it around by invoking NuGet manually, but that's not the intended workflow.

**Comment by nightblade9** [comment]
I got this error, too. In my case, I had NuGet set up to use different package sources in Visual Studio; somehow, that bled over into Godot (same MSBuild executable, I suppose). Adding a `nuget.config` file specifying the public server only, fixes the problem; but only for new projects. (It didn't do anything until I deleted and recreated my project from scratch.)

Here are the contents, for anyone curious / for future reference.

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <!--To inherit the global NuGet package sources remove the <clear/> line below -->
    <clear />
    <add key="nuget" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```

**Comment by jean-philippe-martin** [comment]
Same bug. This is using v3.4.4.stable.mono.official [419e713a2].

> Pong with C#\Pong with C#.csproj : error : Unable to resolve 'Godot.NET.Sdk (= 3.3.0)' for '.NETStandard,Version=v0.0'.

Godot seems broken out of the box, at least on Windows.

**Comment by p-becker** [comment]
> I got this error, too. In my case, I had NuGet set up to use different package sources in Visual Studio; somehow, that bled over into Godot (same MSBuild executable, I suppose). Adding a `nuget.config` file specifying the public server only, fixes the problem; but only for new projects. (It didn't do anything until I deleted and recreated my project from scratch.)
> 
> Here are the contents, for anyone curious / for future reference.
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <configuration>
>   <packageSources>
>     
>     <clear />
>     <add key="nuget" value="https://api.nuget.org/v3/index.json" />
>   </packageSources>
> </configuration>
> ```

Had the same issue, this fixed it immediately!

To reproduce this, make sure your nuget fallback folder is empty. The default location on windows is `C:/Users/<username/.nuget/packages`

**Comment by kaydenvanrijn** [comment]
> I got this error, too. In my case, I had NuGet set up to use different package sources in Visual Studio; somehow, that bled over into Godot (same MSBuild executable, I suppose). Adding a `nuget.config` file specifying the public server only, fixes the problem; but only for new projects. (It didn't do anything until I deleted and recreated my project from scratch.)
> 
> Here are the contents, for anyone curious / for future reference.
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <configuration>
>   <packageSources>
>     
>     <clear />
>     <add key="nuget" value="https://api.nuget.org/v3/index.json" />
>   </packageSources>
> </configuration>
> ```

This worked for me.

**Comment by LispEngineer** [comment]
Using Godot v3.5 x64 for Windows with Mono, and installing the .NET Core 6.0.400 SDK - I had this same error out of the box with a blank project (with a single CS script added [per docs](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_basics.html)) and with the Pong C# example. Very frustrating OOTB experience. Fortunately the `nuget.config` file from @nightblade9 made the build work. I strongly recommend that this file be auto-created somehow, perhaps at the same time the other C# supporting files are auto-created?

**Comment by scottcjt** [comment]
Same here. Fresh install of godot-v3.5-mono and .NET SDK 6.0 on Windows. Visual Studio is **NOT** installed.

With this kind of _lite_ installation, I first have to go to **Editor Settings** to change the build tool to dotnet CLI, and then add a working NuGet source.

It looks like the document does mention this issue (#5985), but at a counterintuitive place. It is below the "Visual Studio" section, while this issue is not limited to Visual Studio - it is NuGet. There is a similar commit (#43029) in the repo, but I am not sure if Godot IDE will generate a fresh config automatically.

A command-line fix to add a NuGet source:
```
dotnet nuget add source --name nuget.org https://api.nuget.org/v3/index.json
```

**Comment by nightblade9** [comment]
I honestly don't recommend anyone try Godot with C# right now. Godot 4.0 already hit their second beta, and they're well underway to merging in the .NET 6.0 branch in. That will dramatically change the experience, and many of these issues will simply disappear.

**Comment by neikeq** [comment]
Can you paste here the content of the `%APPDATA%\NuGet\NuGet.Config` file? A proper installation should include the `nuget.org` source. I don't know what could be causing it to be missing, but I don't think it should be Godot's responsibility to fix a badly configured .NET build environment. Although, we could include this information in the docs.

**Comment by scottcjt** [comment]
> Can you paste here the content of the %APPDATA%\NuGet\NuGet.Config file?

Before adding a source manually, the file does not exist, i.e.: .NET SDK 6.0 installer does not create this file. After adding the nuget source, it looks normal (and works correctly):

```xml

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>

```

> I don't think it should be Godot's responsibility to fix a badly configured .NET build environment.

I partially agree with it. If this behavior was in fact a security oriented decision, adding it automatically becomes an overstep to user environment.

**Comment by chebwaplus** [comment]
The bad config file could stem from this issue: https://github.com/chocolatey/choco/issues/2233.

Assuming this is the common factor: even if Godot *shouldn't* fix the issue with the config file, maybe at least raise a warning?

For my part, I had the same problem as others here, but once I updated `nuget.config` and ran `dotnet restore` via VSCode, things *finally* worked.  It's worth noting that there were other attempts to debug the issue first, so this may not be the *only* steps required.

**Comment by NS-Unfair** [comment]
@neikeq Definitely looks like a config file that failed to write mid-execution. Here are the contents of .config

```
<?xml version="1.0" encoding="utf-8"?>
<configuration />
```

**Comment by onomatopoetry** [comment]
Step by step for dummies like me:

1. Close your code editor
2. Open a text file
3. Paste in the following:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```
4. Save the text file in the root of your Godot project, name it `nuget.config`
5. Open a terminal. First press the windows key an "R" at the same time, in the small window that appears, type "cmd" and hit enter
7. In the terminal window that opens use `cd` to navigate to the root of your Godot project
8. In the terminal window, enter `dotnet restore`
9. In Godot, double-click your .cs asset in the "FileSystem" tab to reopen your code editor
10. Your code editor should open without errors!

**Comment by sredna43** [comment]
Was having a similar issue, and something that worked for me was to edit the first link of my `.csproj` file to this:
```
<Project Sdk="">
```
(obviously failed, but must have reset something)
and then change it back to
```
<Project Sdk="Godot.NET.Sdk/3.3.0">
```
and built the solution. I can only guess that there was a weird blip while I was setting up my project, and that changing the Sdk that NuGet/OmniSharp was looking for removed some caching or something. Regardless, it may be a bit of a hack-y fix but it worked for me without having to edit any other files.

**Comment by NS-Unfair** [comment]
Godot no longer works again. It can't find the SDK again. I guess I'll have to program in an environment I know I will hate.

**Comment by NS-Unfair** [comment]
Here's more information on the issue. The error has nothing to do with ".csproj" or "NuGet.config" files. It has to do with the SDK file itself not existing at all. The problem is whatever is supposed to download the SDK from the internet is not doing that. Am I missing something?

**Comment by NS-Unfair** [comment]
Error message for dotnet CLI: `C:\Users\User\Desktop (No Sync)\ModScript_Godot\ModScript.csproj(0,0): SDK Resolver Failure: "The SDK resolver "NuGetSdkResolver" failed while attempting to resolve the SDK "Godot.NET.Sdk/3.3.0". Exception: "NuGet.Configuration.NuGetConfigurationException: NuGet.Config is not valid XML. Path: 'C:\Users\[User]\AppData\Roaming\NuGet\NuGet.Config'.`

Error message for MSBuild (Mono): `C:\Users\User\Desktop (No Sync)\ModScript_Godot\ModScript.csproj(0,0): The SDK resolver type "DotNetMSBuildSdkResolver" failed to load. The type initializer for 'Microsoft.DotNet.MSBuildSdkResolver.VSSettings' threw an exception.`

**Comment by NS-Unfair** [comment]
Look at this: https://godotengine.org/qa/111338/where-should-godot-net-sdk-be
I think this post should clear up what my issue is

**Comment by hazymaero** [comment]
What helped for me is that in the terminal at your project location type:
```
dotnet add package Godot.NET.Sdk
```

It will install the SDK and add it to the project solution/.csproj.

**Comment by dogboydog** [comment]
I got this message after moving all of my Godot installs before installing the 4.2 beta 2 on Windows 11: 

MSB4242: SDK Resolver Failure: "The SDK resolver "NuGetSdkResolver" failed while attempting to resolve the SDK "Godot.NET.Sdk/4.2.0-beta.2". Exception: "NuGet.Packaging.Core.PackagingException: Unable to find fallback package folder 'C:\Godot-Manager\versions\Godot_v4.0.3-stable_mono_win64\editor_data\mono\GodotNuGetFallbackFolder'.
   at NuGet.Packaging.FallbackPackagePathResolver..ctor(String userPackageFolder, IEnumerable`1 fallbackPackageFolders)
   at Microsoft.Build.NuGetSdkResolver.NuGetSdkResolver.NuGetAbstraction.GetSdkResult(SdkReference sdk, Object nuGetVersion, SdkResolverContext context, SdkResultFactory factory)
   at Microsoft.Build.NuGetSdkResolver.NuGetSdkResolver.Resolve(SdkReference sdkReference, SdkResolverContext resolverContext, SdkResultFactory factory)
   at Microsoft.Build.BackEnd.SdkResolution.SdkResolverService.TryResolveSdkUsingSpecifiedResolvers(IList`1 resolvers, Int32 submissionId, SdkReference sdk, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath, Boolean interactive, Boolean isRunningInVisualStudio, SdkResult& sdkResult, IEnumerable`1& errors, IEnumerable`1& warnings)"" 
   
   I was previously using  C:/Godot-Manager/versions to hold my  installs of different Godot versions, but moved the installs to  C:/Godot instead. When I did this, I became unable to build my project due to the above error.  I tried searching for where this old path was stored  and deleted `.godot/` from my project and backed up and deleted `C:\Users\username\AppData\Roaming\Godot` but it always used this path and there was no way presented to clear it. Moving all of my Godot installs back to where they were fixed the issue instantly.  Is there a way to clear out this  cached  fallback path so that I can move my Godot installs?

**Comment by raulsntos** [comment]
@dogboydog Godot 4.0 adds configuration to NuGet on opening a project for the fallback folder, this was removed in 4.1, but if you've used Godot 4.0 the NuGet configuration remains. It's safe to remove Godot's NuGet configuration for the fallback folder, you should find it in `%AppData%\NuGet\config\Godot.Offline.Config`.

**Comment by dogboydog** [comment]
@raulsntos  That did the trick. Thanks very much.

**Comment by zxffffffff** [comment]
I compile Godot 4.2 from source code，and I got the same problem

my test code：https://github.com/zxffffffff/start-godot-cpp

<img width="877" alt="image" src="https://github.com/godotengine/godot/assets/34299738/252d03d1-513c-48f8-aefd-bc33f061b5ea">
<img width="392" alt="image" src="https://github.com/godotengine/godot/assets/34299738/b506f646-3fa4-437e-90c7-7de9953369f6">

**Comment by YuriSizov** [comment]
@zxffffffff You need to set up a local feed for nuget packages to get it to work with custom pre-release builds.

It's explained [in this article](https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_with_dotnet.html#nuget-packages). In short, you need to use the `nuget` CLI tool to set up a folder as a source, and then add compiled libraries there. You can use the `--push-nupkgs-local` argument with `build_assemblies.py`, or you can also do it manually after the initial setup using something like this

```
nuget add .\modules\mono\editor\Godot.NET.Sdk\Godot.NET.Sdk\bin\Release\Godot.NET.Sdk.4.3.0-dev.nupkg -source C:\Projects\nuget-feed
nuget add .\modules\mono\editor\Godot.NET.Sdk\Godot.SourceGenerators\bin\Release\Godot.SourceGenerators.4.3.0-dev.nupkg -source C:\Projects\nuget-feed
nuget add .\modules\mono\glue\GodotSharp\GodotSharp\bin\Release\GodotSharp.4.3.0-dev.nupkg -source C:\Projects\nuget-feed
nuget add .\modules\mono\glue\GodotSharp\GodotSharpEditor\bin\Release\GodotSharpEditor.4.3.0-dev.nupkg -source C:\Projects\nuget-feed
```

**Comment by zxffffffff** [comment]
> @zxffffffff You need to set up a local feed for nuget packages to get it to work with custom pre-release builds.您需要为 nuget 包设置本地源，以使其能够与自定义预发布版本一起使用。
> 
> It's explained [in this article](https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_with_dotnet.html#nuget-packages). In short, you need to use the `nuget` CLI tool to set up a folder as a source, and then add compiled libraries there. You can use the `--push-nupkgs-local` argument with `build_assemblies.py`, or you can also do it manually after the initial setup using something like this本文对此进行了解释。简而言之，您需要使用 `nuget` CLI 工具设置一个文件夹作为源，然后在其中添加已编译的库。您可以将 `--push-nupkgs-local` 参数与 `build_assemblies.py` 一起使用，或者您也可以在初始设置后使用类似的方法手动执行此操作
> 
> ```
> nuget add .\modules\mono\editor\Godot.NET.Sdk\Godot.NET.Sdk\bin\Release\Godot.NET.Sdk.4.3.0-dev.nupkg -source C:\Projects\nuget-feed
> nuget add .\modules\mono\editor\Godot.NET.Sdk\Godot.SourceGenerators\bin\Release\Godot.SourceGenerators.4.3.0-dev.nupkg -source C:\Projects\nuget-feed
> nuget add .\modules\mono\glue\GodotSharp\GodotSharp\bin\Release\GodotSharp.4.3.0-dev.nupkg -source C:\Projects\nuget-feed
> nuget add .\modules\mono\glue\GodotSharp\GodotSharpEditor\bin\Release\GodotSharpEditor.4.3.0-dev.nupkg -source C:\Projects\nuget-feed
> ```

It's work, thank you!

First, I call `build_assemblies.py --push-nupkgs-local=./bin/MyLocalNugetSource` to build godot.app (macOS)
Then, call `nuget restore` in my project folder (`dotnet restore` doesn't work for me)

<img width="887" alt="image" src="https://github.com/godotengine/godot/assets/34299738/054fabef-3f2f-4dec-b68a-56adfc7b0334">

**Comment by RexxMaxx** [comment]
Had a similar issue wityh the Godot.Sdk not installing and causing all sorts of grief.

Solution path:
- Gave up on VSCODE
- Installed Visual Studio 2022
- Reset the project as much as I could.  (was using a Godot project as test bed - "mic record"  https://github.com/godotengine/godot-demo-projects/tree/master/audio/mic_record

-  Reset the editor for .dotnet to visual studio
- Discovered the .Net defined in the project was 6 not 8 as was expecting and had imported (was a new laptop build so have ONLY .NET8 )
- Updated the  version to .Net8 in Studio for the Godot project.
- Ta daaa the damn thing worked.

Your issue was probs different.   But putting my soln here as I also tore a door from the wall in frustration .....  Maybe next person won't have to.

**Comment by elusive-code** [comment]
> I got this error, too. In my case, I had NuGet set up to use different package sources in Visual Studio; somehow, that bled over into Godot (same MSBuild executable, I suppose). Adding a `nuget.config` file specifying the public server only, fixes the problem; but only for new projects. (It didn't do anything until I deleted and recreated my project from scratch.)
> 
> Here are the contents, for anyone curious / for future reference.
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <configuration>
>   <packageSources>
>     
>     <clear />
>     <add key="nuget" value="https://api.nuget.org/v3/index.json" />
>   </packageSources>
> </configuration>
> ```

I got very similar issue - apparently by default NuGet only have offline source enabled
```
Registered Sources:
  1.  Microsoft Visual Studio Offline Packages [Enabled]
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
```
Could be checked using command
```
dotnet nuget list source
```
Or in Rider: NuGet > Sources
Or in Visual Studio 2022: Tools > NuGet Package Manager > Package Manager Settings > Package Sources
And you can add ```https://api.nuget.org/v3/index.json``` right there too.

Btw why don't Godot bundle preconfigured .net sdk (with an option of choosing external)? Isn't .net currently under MIT License?

**Comment by dilectiogames** [comment]
Jesus and all the f angels.

this nuget thing is installed inside visual studio, it has the path and everything there.

I keep getting

`Unable to load the service index for source https://api.nuget.org/v3/index.json`

what the hell is this service index and why we put all our eggs on these online repositories. Just pack a godot zip file with all the stuff inside and download it for offline use. I swear to God when the russians will start bombing the data centers all this cloud spread repositories will become a nightmare.

unity may be a bunch of as.les but at least that idiotic hub app managed to download all the stuff needed by the editor.

these open source projects always need to complicate all the things by creating a web of dependencies that one week later not even the main developers know how to get out of it

**Comment by akien-mga** [comment]
@dilectiogames Please avoid ranting on our public issue tracker, as per our [Code of Conduct](https://godotengine.org/code-of-conduct/). This is unwarranted and unproductive.

**Comment by dilectiogames** [comment]
> @dilectiogames Please avoid ranting on our public issue tracker, as per our [Code of Conduct](https://godotengine.org/code-of-conduct/). This is unwarranted and unproductive.

well do you know the answer or you are just posting to consume github resources?

and my "rant" is motivated. there is a big download button on godot page that downloads a a broken version which makes people waste their time and then run away from opensource back to unity.

**Comment by scgm0** [comment]
> > @dilectiogames Please avoid ranting on our public issue tracker, as per our [Code of Conduct](https://godotengine.org/code-of-conduct/). This is unwarranted and unproductive.
> 
> well do you know the answer or you are just posting to consume github resources?
> 
> and my "rant" is motivated. there is a big download button on godot page that downloads a a broken version which makes people waste their time and then run away from opensource back to unity.

Please check the godot compressed package you downloaded. There is a "GodotSharp" folder in it. The sdk is in "GodotSharp/Tools/nupkgs". You only need to configure the local source of nuget to point to this folder to use them. No need to connect to the Internet. How to configure the local source? Go to Google and search it yourself. This is the "common sense" you should learn.

**Comment by dilectiogames** [comment]
the famous godot community helping an user with issues. shameful. really shameful.

this smug attitude is really shameful

**Comment by scgm0** [comment]
> the famous godot community helping an user with issues. shameful. really shameful.著名的 godot 社区帮助用户解决问题。可耻。真是可耻。
> 
> this smug attitude is really shameful这种沾沾自喜的态度真是可耻

你想要答案，而我给你一个答案，如果你不喜欢来自社区的帮助，那么就不要在这里浪费我们的时间，我也不喜欢你的态度。

**Comment by NS-Unfair** [comment]
________________________________

**Comment by NS-Unfair** [comment]
I don't know when, but this issue has been fixed as of an update. C# now works

**Comment by iMartyn** [comment]
For anyone coming here after the "fix" is there if it is still broken for you, here's another "fix" that might work for you :
Go to your Godot project in a command prompt and type the following :
```
dotnet nuget add source https://api.nuget.org/v3/index.json
dotnet add package Godot.NET.Sdk
```
After that it worked for me.  I found this because `dotnet nuget list source` listed no sources, and I don't have VS or Rider to follow `elusive-code`'s instructions.
