### ISSUE TITLE
Keyframe Missing from Animation (gltf)

### ISSUE THREAD

**Issue by 9HarshAgarwal** [godotengine/godot#58968]
### Godot version

4.0 Alpha 3

### System information

Windows 10, AMD 5600x, Nvidia 3060

### Issue description

My animation has 3 keyframes. In Godot, the middle one isn't registering. I'm adding the file so it can be imported in Blender and Godot to see the difference in behaviour.

### Steps to reproduce

New Inherited GLB scene. Use animation player, middle keyframe is removed.

### Minimal reproduction project

[SmallContainer.zip](https://github.com/godotengine/godot/files/8220857/SmallContainer.zip)

**Comment by timothyqiu** [comment]
Disabling "Optimizer" in the import settings seems solve the issue.

**Comment by Altair1234** [comment]
Yup that seems to solve the issue. Might be worth disabling the option by default and putting an "Experimental" warning until root cause is eliminated.

Also for my particular project, there are a zillion keyframes. Is this expected behaviour?

**Comment by timothyqiu** [comment]
> Also for my particular project, there are a zillion keyframes. Is this expected behaviour?

It's the result of exporting eased keyframes I believe. The actual values are sampled on export. You'll get the same zillion keyframes if you import the glb back to Blender :)

**Comment by Altair1234** [comment]
Importing this glb file into Blender completely messes up the mesh. And yes, that does have many keyframes as well.
The same mesh problems were visible in the Advanced Importer in Godot but while using it in my project, everything was okay. Not sure what is going on.

**Comment by TokageItLab** [comment]
Yes, the optimizer obviously produces odd animations. I agree with disabling it by default. That being said, someone might have mentioned that the judgment may be broken about the optimizer's rotation threshold, @fire or @reduz?

**Comment by fire** [comment]
We have a newer compression system that uses bitpacking, its more reliable. Check it.

**Comment by Rodeo-McCabe** [comment]
> We have a newer compression system that uses bitpacking, its more reliable. Check it.

Is this just the `Compression` option in the advanced import dialog? Is it supposed to supersede the optimizer, or can they (theoretically) be used together?

**Comment by fire** [comment]
They can be used together except when keyframes are missing because they're optimized.

**Comment by fire** [comment]
Is this resolved? Do you require expanded documentation to be written?
