### ISSUE TITLE
Editor crashes when using state machine editor

### ISSUE THREAD

**Issue by guilhermefelipecgs** [godotengine/godot#58961]
### Godot version

v4.0.alpha.custom_build [450ebaab9]

### System information

5.16.13-arch1-1

### Issue description

Crashes with no log aparrently.
```
./bin/godot.linuxbsd.tools.64 
Godot Engine v4.0.alpha.custom_build.450ebaab9 - https://godotengine.org
Vulkan API 1.2.203 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 2060 SUPER
 
Editing project: /home/guilherme/Projects/Broken (::home::guilherme::Projects::Broken)
Godot Engine v4.0.alpha.custom_build.450ebaab9 - https://godotengine.org
Vulkan API 1.2.203 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 2060 SUPER
```

### Steps to reproduce

https://user-images.githubusercontent.com/1387165/157566355-31107704-fb89-4350-95b4-bca8584cc7e6.mp4

**Comment by guilhermefelipecgs** [comment]
Maybe the same as https://github.com/godotengine/godot/issues/58960

**Comment by akien-mga** [comment]
> Maybe the same issue as #58960

Very likely, there's plenty of similar crashes around animation code due to this PR.
