### ISSUE TITLE
Allow to set main scene directly in "No main scene defined" popup

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#5896]
This is a small enhancement idea, but it would save time to be able to click "Set current as main" when you want to run the project but no main scene is defined. This way you won't have to close the popup, go to settings, find the option, click open file, find the scene, select it etc.

**Comment by akien-mga** [comment]
Have you tried 2.1-beta? It proposes you to select a scene if no main scene has been defined.

**Comment by Zylann** [comment]
Ah, indeed. That's great! Sorry for the short-lived issue :)
