### ISSUE TITLE
Show a description of nodes into "Create New Node" dialog box

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#5897]
**Operating system or device - Godot version:**
2.1beta

**Issue description** (what happened, and what was expected):

IT could be handy if a description of the selected new node was displayed into the "Create New Node" dialog box. (see screenshot example)

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

![create_new_node_dialog_proposal](https://cloud.githubusercontent.com/assets/9801802/17085109/41912ea4-51d0-11e6-9f8d-9cc4e3802ce3.png)

**Comment by vnen** [comment]
Shouldn't be too hard to make this, unless the help control is more tied to the script editor than I think.

**Comment by akien-mga** [comment]
Note that you already get the short description in a tooltip when there is one: 
![spectacle j14261](https://cloud.githubusercontent.com/assets/4701338/17085149/c9533cfa-51d1-11e6-9484-f5fbb82a37eb.png)

**Comment by SuperUserNameMan** [comment]
@akien-mga : sometime, the short description is not enough to discover or remember the details of a node.
You then have to exit this dialog box, enter the script editor, click the "Classes", search the node again, read, exit the help, go back to "create a new node" to select the node again.
It would be some sort of shortcut.

**Comment by vnen** [comment]
BTW, you can click on the gear icon on the inspector and select "Open in help". No need to go to the script editor.

**Comment by SuperUserNameMan** [comment]
yes, once you have inserted it into the tree already

**Comment by GlaDOSik** [comment]
It's a neat idea. Create New Node window is too wide anyway so the description would fit nicely. The question is who will implement it because it's not a groundbreaking improvement.

**Comment by akien-mga** [comment]
Fixed by dc7139c9 I guess?

**Comment by SuperUserNameMan** [comment]
@akien-mga : I've just managed to compile godot to test it.

The new "short description" box that appear at the bottom of the "Create New Node" dialog box only display the same short description than you get when you hover a node with the mouse cursor.

IMHO, it currently adds no benefits compared to my proposal.

My feature request is still valid.

**Comment by Sslaxx** [comment]
@reduz - any input?

**Comment by akien-mga** [comment]
I guess @reduz didn't even know that the short description appears on hover.

**Comment by volzhs** [comment]
OMG, I didn't know that either so far.

**Comment by Noshyaar** [comment]
According to https://github.com/godotengine/godot/pull/18447 and reduz's [comment](https://github.com/godotengine/godot/pull/18447#issuecomment-387123471) I think the general consensus is that the docs won't be of much use after some times. I'll close this as the dialog changed a lot since this issue was created.
