### ISSUE TITLE
Godot 4: RichTextLabel bold, italic and code Bbcodes aren't applied properly with the default font.

### ISSUE THREAD

**Issue by Dan-Gamin** [godotengine/godot#58988]
### Godot version

v4.0-alpha4

### System information

Windows 10 64-bit, GPU: NVIDIA Geforce GTX 1650 Ti, CPU: AMD Ryzen 7 4800H

### Issue description

The bold (`[b[`), italic (`[i]`) and code (`[code]`) Bbcodes  do not work in Godot 4 with the default font. This may affect other versions too.
I'm sure you could fix this by using separate fonts for separate bbcodes in here:
![image](https://user-images.githubusercontent.com/58695417/157701371-1e66030a-194e-441e-8cdf-3c027ac0d820.png)
But it's still important for it to work with the default font because it can make prototyping easier and I also use it a lot for debug text.
Here is a RichTextLabel with this text applied:
```
Normal
[b]Bold[/b]
[i]Italic[/i]
```
![image](https://user-images.githubusercontent.com/58695417/157700039-c0dfbc43-5434-4cd1-9b47-e68fc53a1882.png)

### Steps to reproduce

1. Create a RichTextLabel
2. Enable the `bbcode_enabled` property.
3. Insert the following text:
```
Normal
[b]Bold[/b]
[i]Italic[/i]
```
4. There are no text effects applied, you can compare with the image above.

**Comment by bruvzg** [comment]
> The bold ([b[), italic ([i]) and code ([code]) Bbcodes do not work in Godot 4 with the default font.

This is expected, there's no bold / italic variants of the default font included.

**Comment by Dan-Gamin** [comment]
> > The bold ([b[), italic ([i]) and code ([code]) Bbcodes do not work in Godot 4 with the default font.
> 
> This is expected, there's no bold / italic variants of the default font included.

@bruvzg I said this:
> But it's still important for it to work with the default font because it can make prototyping easier and I also use it a lot for debug text.

**Comment by bruvzg** [comment]
> Fake bold is implemented by drawing the font several times at slightly different X offsets (and possibly increasing spacing between characters slightly).

There's also [FT_Outline_Embolden](https://freetype.org/freetype2/docs/reference/ft2-outline_processing.html#ft_outline_embolden) function to do the same, not sure which method is better.

**Comment by Dan-Gamin** [comment]
> Including default bold/italic fonts would increase binary size significantly for very little benefit, since the font needs to be included in both editor and export template binaries.
>
> The alternative is to implement support for fake bold/fake italic, which can be useful with custom fonts that do not provide bold/italic variants (or when reducing your PCK size is paramount).

I agree that Godot should be lightweight. I think the alternative is a good idea, since its mostly there because of prototyping, debugging, and people thinking its a bug (like me).

**Comment by bruvzg** [comment]
Here's PR for adding embolden and slant to the default theme (`[code]` is still using the default font) - https://github.com/godotengine/godot/pull/59013

**Comment by miv391** [comment]
How about displaying a warning or an error if you try to use font variants that the used font doesn't contain? Then you don't have to google why your rich text label doesn't work as expected.

**Comment by Dan-Gamin** [comment]
> How about displaying a warning or an error if you try to use font variants that the used font doesn't contain? Then you don't have to google why your rich text label doesn't work as expected.

This is unneeded because #59013 already fixes this by simulating bold and italics with code.
![image](https://user-images.githubusercontent.com/58695417/157850339-e1fdae81-10e7-4bc3-ac8a-3ead0cf95e45.png)

**Comment by nagidev** [comment]
Was this removed? I'm seeing this issue again in 4.2.1. Using custom fonts fixes the issue so its not that big of a deal to me, just curious.

**Comment by nagidev** [comment]
Okay, this only seems to happen when I set the `Preview theme` from the View menu to `Editor theme`. Thus, this only affects people working on editor plugins that use bbcode. The workaround I'm using is to use a custom font for the RichTextLabels in my plugin.

**Comment by YuriSizov** [comment]
@nagidev Ah, of course. Bold, italic, and bold italic fonts for RTL are not configured on the editor theme the same way they are on the default one. This can probably be done though.
