### ISSUE TITLE
"AssetLib" button gets behind "Play project" button

### ISSUE THREAD

**Issue by ricpelo** [godotengine/godot#5899]
**Operating system or device - Godot version:**

Ubuntu 16.04 LTS, 1280x1024 screen, Godot 2.1-rc1.

**Issue description** (what happened, and what was expected):

The "AssetLib" button gets behind "Play project" button.

![bug](https://cloud.githubusercontent.com/assets/616169/17086735/42b1177a-51fa-11e6-8f7a-c702d0453f5e.png)

**Comment by bojidar-bg** [comment]
Yeah, lovely small-screen issues :smile:

**Comment by Hinsbart** [comment]
@ricpelo while this isn't fixed yet for the default scaling, there's now a `VeryLoDPI` option, which greatly improves the screen real estate for small monitors, at the cost of slightly worse visual looks.

**Comment by Calinou** [comment]
This should not be an issue anymore thanks to the UI redesign performed in Godot 3.0. If you are still experiencing problems with overlapping UI elements, try setting the display scaling mode to VeryLoDPI / 75%.
