### ISSUE TITLE
Wrong pop up position of new nodes in animation tree edition (DisplayServer regression)

### ISSUE THREAD

**Issue by jcarlosrc** [godotengine/godot#58990]
### Godot version

4.0 alpha 4

### System information

Windows 10

### Issue description

When adding new nodes in an animation tree, such nodes appear way below clicked position. 

![wrong-offset](https://user-images.githubusercontent.com/8985409/157704800-54f66844-e298-4471-866f-30b9a8ada13a.gif)

### Steps to reproduce

Add nodes to an animation tree.

### Minimal reproduction project

None, just add nodes to an animation tree.

**Comment by Calinou** [comment]
This is a duplicate of another issue (where it occurs with the VisualScript editor instead, which also uses GraphEdit/GraphNode).

**Comment by TokageItLab** [comment]
Dupe of https://github.com/godotengine/godot/issues/57410.
