### ISSUE TITLE
Godot 4 alpha 4: motion_velocity() is completely missing from Visual Script

### ISSUE THREAD

**Issue by kreaninw** [godotengine/godot#59006]
### Godot version

v4.0.alpha4.official [f47097973]

### System information

Windows 11, Vulkan Clustered, Intel UHD Graphics 620 v30.0.101.1340

### Issue description

Now, `motion_velocity()` is completely missing from Visual Script. This property was missing only in the property selector (you can still search for it in the node search window) in Godot 4 alpha 3 (issue #58305). But in Godot 4 alpha 4, it's missing from the node search window too, as shown in the screen recording below:

https://user-images.githubusercontent.com/1403194/157777633-650ca65e-83ad-4c9a-bab4-0efd86af7103.mp4

This issue makes `move_and_slide()`, which is the very essential node in almost every game, impossible to use with Visual Script in Godot 4 alpha 4 since `move_and_slide()` now depends on `motion_velocity()`.

### Steps to reproduce

Search for `motion_velocity()` in Visual Script. You won't find any.

**Comment by Mickeon** [comment]
Hasn't the property just been renamed to `velocity`?

**Comment by kreaninw** [comment]
> 

Wow, thanks. I didn't know that. I look at the [docs](https://docs.godotengine.org/en/latest/classes/class_characterbody3d.html?highlight=motion_velocity#class-characterbody3d-property-motion-velocity) and it's not updated yet.

I will close this issue now.
