### ISSUE TITLE
Shader material with alpha prepass transparency not working

### ISSUE THREAD

**Issue by Hannyson** [godotengine/godot#59008]
### Godot version

4.0.alpha4

### System information

Linux

### Issue description

I created a shader material for a project with procedurally generated meshes, when I set the depth_prepass_alpha option in render_mode, the transparent parts of the displayed texture turn to black. With the others depth_ options, no problems. This depth_prepass_alpha option is what worked the best for my project when it was in 3.x versions.

Test Project : [https://www.udrop.com/6pov/AlphaPrepassBug4.0.zip](https://www.udrop.com/6pov/AlphaPrepassBug4.0.zip)

### Steps to reproduce

Create manually a shader with a transparent texture, a leaf for example. Set the render_mode option to depth_prepass_alpha.
[https://www.udrop.com/6pov/AlphaPrepassBug4.0.zip](https://www.udrop.com/6pov/AlphaPrepassBug4.0.zip)

### Minimal reproduction project

[https://www.udrop.com/6pov/AlphaPrepassBug4.0.zip](https://www.udrop.com/6pov/AlphaPrepassBug4.0.zip)

**Comment by Hannyson** [comment]
Saw issue #59015, with depth_prepass_alpha AND depth_draw_* transparency works.

**Comment by Hannyson** [comment]
I did had this problem with a project converted from 3.4, after recompiling the shaders, by creating new shaders nearly identical to ancients and assigning them to the materials I use, the problem disappears. Maybe this was just a migration problem.

**Comment by clayjohn** [comment]
Can you still reproduce this issue in Beta13? There have been a lot of fixes to transparency that may have fixed this issue. I can't test as it seems your MRP is no longer available.

**Comment by Hannyson** [comment]
I haven't this problem anymore since a long time, I forgot to update this

**Comment by clayjohn** [comment]
Wonderful, great to hear that things are working for you now!
