### ISSUE TITLE
ERROR: RPC '{Method}' is not allowed on node (Mode is 0, master is 1)

### ISSUE THREAD

**Issue by niklaspm** [godotengine/godot#59027]
### Godot version

Godot Engine v3.4.2.stable.mono.official.45eaa2daf

### System information

Windows 10

### Issue description

Hello,

I'm trying to implement a simple chat into my game on top of Godot's multiplayer api. But I`m not allowed to call the rpc function. 

Error message: 
> server_1      | ERROR: RPC 'UserSendsChatMessage' is not allowed on node /root/SceneHandler/GameScene/Camera2D/UI/HUD/Chat from: 1305503127. Mode is 0, master is 1.
server_1      |    at: _process_rpc (core/io/multiplayer_api.cpp:285)

GetNetworkMaster() results in "Network Master is 1" (server as expected)
```c#
GD.Print($"Network Master is {GetNetworkMaster()}");
```

On client and server-side I placed the exactly same node structure:
`./SceneHandler/GameScene/UI/HUD/Chat`
And both got a Chat.cs script attached.

Client-side code:
```c#
    public void AddMessage(string message)
    {
       // simply use Rpc("UserSendsChatMessage", message) results in the same error
        RpcId(1,"UserSendsChatMessage", message);
    }
```

Server-side code:
```c#
   // also tried with [Master]
    [Remote]
    public void UserSendsChatMessage(string message)
    {
        GD.Print("message");
    }
```

Don't know what I`m doing wrong especially if it's working in the exactly same way on other nodes of my project.

Best regards

### Steps to reproduce

See code snippets above and put them on the exactly same hierachical level

**Comment by Calinou** [comment]
Can you reproduce this in GDScript project?

**Comment by Malkverbena** [comment]
@Calinou I had the same issue and  I can reproduce this using only GDScript

**Comment by l2toplist** [comment]
confirm this problem

**Comment by Calinou** [comment]
cc @Faless

**Comment by Faless** [comment]
`Mode is 0` means that the RPC is disabled.
Make sure both client and server have the appropriate RPC annotations.

This seems like an issue with the user code, sadly, I can't debug this further without a minimal reproduction project.

I'll close for now, but if you are encountering this issue, please post a minimal reproduction project so I can investigate and I'll re-open.
