### ISSUE TITLE
Copy property path does not work with project configuration options.

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#59020]
### Godot version

v3.5.beta1.official [b9b23d222]

### System information

w10 64

### Issue description

Do this:
![Captura](https://user-images.githubusercontent.com/19652075/157847951-8f35ffc8-315c-4a85-9265-c85b71ad3cfb.PNG)

You get this:
"size/width"

Shouldn't I get this?:
"display/window/size/width"

If the idea of copy property path is to make things easier, then this is not working here.

### Steps to reproduce

copy the property path of the image attached

### Minimal reproduction project

...

**Comment by Calinou** [comment]
cc @rcorre
