### ISSUE TITLE
In script editor ctrl+click on ProjectSettings causes freeze.

### ISSUE THREAD

**Issue by teebarjunk** [godotengine/godot#59028]
### Godot version

v4.0.alpha4.official [f47097973]

### System information

Kubuntu 21.04, 64-bit, AMD Radeon HD 8800

### Issue description

Typically `ctrl+click`ing on a class in the script editor brings up the relevant built in class documentation viewer.

But every time I `ctrl+click` on `ProjectSettings`, it starts to open, then my computers display freezes, except for the cursor. I can't `alt+tab` or bring up the console to further test what is going on. I just reboot the PC.

I don't get the problem in **v3.5.beta1.official [b9b23d222]**. Every class doc opens fine.

I assume it's because of how large the Project Settings page is, and my CPU is throttling to prevent overheating? So maybe it's just a me thing, and I need a better PC.

### Steps to reproduce

In a script editor type `ProjectSettings` and `ctrl+click` it.

**Comment by bmolyneaux** [comment]
I was unable to reproduce on v4.0.alpha.4.official https://github.com/godotengine/godot/commit/f470979732513436124c01a465b22f948637b5fa on OSX 12.2.1 Apple M1 Pro.

> I assume it's because of how large the Project Settings page is

Indeed, it does take take longer to open ProjectSettings than something like Resource - perhaps about 300ms on this machine.

**Comment by taigi100** [comment]
Unable to reproduce on master branch.
However, it does take longer to open it as mentioned and the script editor is very weird / buggy / not working after I close the Project Settings page. I have to reopen the script to get it working normally.

**Comment by KoBeWi** [comment]
Can reproduce in alpha 7.
As others said, there is no permanent freeze, but loading the documentation page takes exceedingly long.

Seems to be caused by text shaping. The page is just stupidly big, so it takes long to render the text. RenderingServer, which is also huge, has the same issue. Not sure what can be done to optimize it, other than loading in a thread and displaying some progress bar, so it doesn't make the editor unresponsive.

CC @bruvzg

**Comment by bruvzg** [comment]
Can't reproduce with current master on macOS, `ProjectSettings` page is huge and take some time, but it's only 500ms (measured spike width in the Time Profile tool), so can cause visible stutter, but definitely not enough to justify progress bar.

Is it opening faster if you open another page and open it again?

> Unrelated note: with new HashMap2, it is much slower about 2.7 seconds - #60885

**Comment by KoBeWi** [comment]
> it's only 500ms

For me it's 1-2 seconds. It's much more noticeable in debug builds (4-5s), but I guess that irrelevant.

> Is it opening faster if you open another page and open it again?

Yes, if the page is already opened, it just switches instantly.
