### ISSUE TITLE
Can't insert tabs in TextEdit

### ISSUE THREAD

**Issue by Dan-Gamin** [godotengine/godot#59021]
### Godot version

v4.0.alpha4.official [f47097973]

### System information

Windows 10 64-bit, GPU: NVIDIA Geforce GTX 1650 Ti, CPU: AMD Ryzen 7 4800H

### Issue description

You cannot insert tabs in TextEdit with the tab key. It does nothing. However TextEdit still supports tabs. You just can't insert them with the tab key, which is weird.

### Steps to reproduce

Run the Minimal reproduction project provided below and try to insert tabs.

### Minimal reproduction project

[TextEdit.zip](https://github.com/godotengine/godot/files/8231090/TextEdit.zip)

**Comment by bmolyneaux** [comment]
TextEdit expects tab as a unicode key.

The `platform` code treats tab as if it shouldn't be a unicode key - either clearing or just not setting the unicode value of the InputEventKey. Is there a desire to treat control codes differently?

- OSX: the `keycode_has_unicode()` function returns false for tab.
- Windows: sets any unicode value less than 0x20 to 0.
- Linux: seems to do the same.

Here are some alternatives which all appear to work:
A. Change the platform code to treat tab as unicode.
B. Add a workaround in TextEdit to set the unicode value for tab back to 0x9.
C. Add special handling for the tab key in TextEdit.
I'm not sure which would be preferred.

CodeEdit consumes the `ui_text_indent` input action to handle indentation, so this isn't an issue there.

**Comment by KoBeWi** [comment]
Still valid in 748fde8
