### ISSUE TITLE
Pressing anywhere on the Godot editor after USB android export causes another export

### ISSUE THREAD

**Issue by Dan-Gamin** [godotengine/godot#59043]
### Godot version

v4.0.alpha4.official [f47097973]

### System information

Windows 10 64-bit, GPU: NVIDIA Geforce GTX 1650 Ti, CPU: AMD Ryzen 7 4800H

### Issue description

Pressing anywhere on the Godot editor after USB android export causes another export, which is really annoying.

### Steps to reproduce

1. Open up the project of your choice.
2. Plug in an android device via USB (Make sure `USB Debugging` is turned on in the device's settings)
3. Click on the android icon.
4. Once export finished, click anywhere on the editor.
5. It runs the export again. The only way to get out of this is to restart the editor.

**Comment by Calinou** [comment]
@Dan-Gamin Can you reproduce this on 3.4.3?

**Comment by Dan-Gamin** [comment]
> @Dan-Gamin Can you reproduce this on 3.4.3?

@Calinou No I cannot. It works as it should (not exporting every time I click).

**Comment by Dan-Gamin** [comment]
Here is another example of the accidental exports:

https://user-images.githubusercontent.com/58695417/157973876-14728781-73ef-4ada-a9f1-c04c418043a1.mp4

**Comment by KoBeWi** [comment]
Tried in alpha7 and exporting to device crashes the editor, so can't test it.

**Comment by Dan-Gamin** [comment]
I'm using alpha9 and it doesnt happen anymore. So i think its resolved?
