### ISSUE TITLE
Exported game doesn't open (OSX)

### ISSUE THREAD

**Issue by genete** [godotengine/godot#5904]
**Operating system or device - Godot version:**
OSX 10.10.3
Godot 2.0.3 stable official

**Issue description** (what happened, and what was expected):
I export the game for OS X using the following values:
![](https://raw.githubusercontent.com/genete/JetPac/master/images/screenshots/Captura%20de%20pantalla%202016-07-25%20a%20las%2019.23.06.png)

When exported a zip file is produced and once I unzip it I get a app file. Icon looks messed up like in #4219. Then I double click the icon and nothing happens. It seems like if one icon starts to grow in the dock but immediately it vanishes.

**Steps to reproduce:**
Download the project from github, and select export with the above parameters

**Link to minimal example project** (optional but very welcome):
It is **not** a minimal example because I want to **exactly** export this game for OS X and not a minimal example. Minimal examples fails too. But the issue is not the game itself but the export action combined with Godot version and OS X version
https://github.com/genete/JetPac

**Comment by akien-mga** [comment]
For the icon issue I have no clue, but about your game not starting, it's likely because the exporter does not set the executable bit for the binary (see #527). You need to add it yourself, and it should hopefully work (and be kept when you distribute your game as a zipped .app).

**Comment by genete** [comment]
@akien-mga : Thanks for your quick reply and let me know that you're working on it.
This is what I get when inspecting the executability of the produced files. (I didn't change anything)
![](https://raw.githubusercontent.com/genete/JetPac/master/images/screenshots/Captura%20de%20pantalla%202016-07-25%20a%20las%2023.54.57.png)
Can you tell me if it is OK or do I still to change anything?
Thanks in advance

**Comment by akien-mga** [comment]
Ah it's intriguing that the binary (`Contents/MacOS/JetPac`) shows as executable already. But the weirdest is it's timestamp: `21 may 2015`. Are you by any chance still using the templates of Godot 1.1?

**Comment by genete** [comment]
> Ah it's intriguing that the binary (Contents/MacOS/JetPac) shows as executable already. But the weirdest is it's timestamp: 21 may 2015. Are you by any chance still using the templates of Godot 1.1?

How can I know that?

**Comment by akien-mga** [comment]
> How can I know that?

Did you install newer templates since Godot 1.1? :)

**Comment by genete** [comment]
Doh! I didn't!

**Comment by akien-mga** [comment]
You'll find the templates for 2.0.4.1 here: http://download.tuxfamily.org/godotengine/2.0.4.1/Godot_v2.0.4.1_stable_export_templates.tpz

Or for 2.0.3 if you prefer to stick to this version: http://download.tuxfamily.org/godotengine/2.0.3/Godot_v2.0.3_stable_export_templates.tpz

**Comment by genete** [comment]
Fantastic! It worked! Thank you thank you thank you!

**Comment by genete** [comment]
Only still the icon issue. Close the bug
