### ISSUE TITLE
RichTextLabel shadows ignore text alpha.

### ISSUE THREAD

**Issue by teebarjunk** [godotengine/godot#59042]
### Godot version

v4.0.alpha4.official [f47097973]

### System information

Kubuntu 21.04, 64-bit, AMD Radeon HD 8800

### Issue description

`RichTextLabel` shadow alpha isn't multiplied by the alpha of the text. The included *minimal reproduction project* shows that `RichTextEffect` has the same problem.

```
Some [color=#ffffffff]100% alpha[/color] text.
Some [color=#ffffff80]50% alpha[/color] text.
Some [color=#ffffff00]0% alpha[/color] text.
```
![Screenshot_20220311_135648](https://user-images.githubusercontent.com/18387401/157936119-8d2a1319-26d1-4367-aaa3-5c5352d28747.png)

### Steps to reproduce

Create a `RichTextLabel`.
Enable **Theme Overrides/Colors/Font Shadow Color**.
Enable BBCode.
Paste:
```
Some [color=#ffffffff]100% alpha[/color] text.
Some [color=#ffffff80]50% alpha[/color] text.
Some [color=#ffffff00]0% alpha[/color] text.
```

### Minimal reproduction project

[temp_rich_text_shadows.zip](https://github.com/godotengine/godot/files/8234571/temp_rich_text_shadows.zip)

**Comment by Calinou** [comment]
@teebarjunk Can you reproduce this in 3.4.3 as well?
