### ISSUE TITLE
[Editor] Show in File Manager shows the folder rather than the selected file

### ISSUE THREAD

**Issue by lexum0** [godotengine/godot#59046]
### Godot version

3.4.3, 3.4.4.rc1

### System information

macOS

### Issue description

Right click a file in the FileSystem dock, click Show in File Manager and it will open the folder without selecting the file. 

The API to use in macOS is ```NSWorkspace.shared.activateFileViewerSelecting(url)```

### Steps to reproduce

Steps are above in the Issue description

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot-proposals/issues/3251.
