### ISSUE TITLE
Impossible to switch to a scene containing `_BASE_` on exported project

### ISSUE THREAD

**Issue by gustavi** [godotengine/godot#59059]
### Godot version

v4.0.alpha4.official [f47097973]

### System information

Windows 10 64bit - Vulkan API 1.2.141 - GeForce GTX 1660 SUPER

### Issue description

The `_ready()` method is not called on exported projects (tested on Windows only) when you switch on a scene containing the `_BASE_` string, **event in comments**.

It may be related to the following line: https://github.com/godotengine/godot/blob/33c907f9f5b3ec1a43d0251d7cac80da49b5b658/modules/gdscript/gdscript.cpp#L831

### Steps to reproduce

1. Create a scene A
2. Create a scene B containing `_BASE_` anywhere
3. Add `get_tree().change_scene("res://B.tscn")` in scene
4. Try it on editor, it's work fine
5. Export project and try it, the scene is not loaded

### Minimal reproduction project

[bug-base.zip](https://github.com/godotengine/godot/files/8237250/bug-base.zip)

**Comment by gustavi** [comment]
After few git blame I found the origin of the problem: 

- Introduced 5 years ago but for `%BASE%` https://github.com/godotengine/godot/commit/f61e8695c9952928d19e6896bc412b638927b25c
- Updated 5 months ago after in an improvement https://github.com/godotengine/godot/commit/9d5b80705912d85c3c7301ac0ea0afbf9372a660#diff-2d47041c61b0e94d891650482b0cf9398f22729abdc811f94c2b7da902ed392fR830

The bug was not spotted since the probability to have `%BASE%` was really low. After the improvement the probability to have this on a file is definitely not so low (I found it with a variable named `ENTER_BASE_CAMP`).

**Comment by akien-mga** [comment]
CC @vnen @fabriceci
