### ISSUE TITLE
Websocket not firing "server_disconnected" signal outside of browser when usin gd_mp_api

### ISSUE THREAD

**Issue by viindicater** [godotengine/godot#59055]
### Godot version

3.4.2 stable

### System information

Windows, Android

### Issue description

the `server_disconnected` signal does not fire in windows and android native clients, only browser when using websocket server and client with the "gd_mp_api" parameter set to true. 

Side Note(s):
- worked fine with enet, but that's not compatible with browser
- Not sure if the issue persists when setting that to false [unrelated and would require me to fully rewrite my netcode so I have no reason to test]

### Steps to reproduce

- create a websocket server 
- create a websocket client and connect to the server.
- terminate the server
 
 and the clients [unless browser] won't fire "server_disconnected" signal

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/36945.
