### ISSUE TITLE
Export to iOS failed - requires a provisioning profile.

### ISSUE THREAD

**Issue by NeroNekro** [godotengine/godot#59066]
### Godot version

>=3.4.3

### System information

MacOS 12.2.1

### Issue description

Hello,

I tried to export my app for iOS and get the following error:
error: "beautifulAppName" requires a provisioning profile. Select a provisioning profile in the Signing & Capabilities editor.

With the old version 3.4.2 it works fine. I get this error with 3.4.3, the version 3.4.4 RC1 don't accept the export tools or doesn't installed it, but this is a different problem :)

`
note: Build preparation complete
note: Building targets in dependency order
error: "beautifulAppName" requires a provisioning profile. Select a provisioning profile in the Signing & Capabilities editor. (in target 'beautifulAppName' from project 'beautifulAppName')
** ARCHIVE FAILED **

`

### Steps to reproduce

Make a Project GLES3
Export to iOS
Get the error

**Comment by naithar** [comment]
Might be related to the https://github.com/godotengine/godot/issues/58138#issuecomment-1052585087. Comment should provide you with the steps on how to address and fix the issue.

You should be able to use 3.4.4 RC1 export templates after manually renaming templates folder from `3.4.4-rc1` to `3.4.4.rc1`. Editor should display full path to the export templates location.

**Comment by NeroNekro** [comment]
> Might be related to the [#58138 (comment)](https://github.com/godotengine/godot/issues/58138#issuecomment-1052585087). Comment should provide you with the steps on how to address and fix the issue.
> 
> You should be able to use 3.4.4 RC1 export templates after manually renaming templates folder from `3.4.4-rc1` to `3.4.4.rc1`. Editor should display full path to the export templates location.

Thanks for your help. I think it were multiple problems. Bug and misconfiguration in Xcode. Xcode change my signature settings on update.
