### ISSUE TITLE
Type casting from `float` to `int` with constructor casting produce warning.

### ISSUE THREAD

**Issue by sent44** [godotengine/godot#59060]
### Godot version

4.0 alpha 4

### System information

Windows 10

### Issue description

When casting the type from float to int with `int(number)` give `NARROWING_CONVERSION` warning in both editor and play mode debugger. It should not raise this warning.

Note: `number as int` is work as expect.

### Steps to reproduce

Write this code
```GDScript
var number: float = 3.2
print(int(number)) # NARROWING_CONVERSION
print(number as int) # ok
```

**Comment by ThreeMileJump** [comment]
This bug also affects statements with mixed types in unpredictable ways

var x: int = 0
var y: int = 3

x = int(3.0/2.0)    # this is OK
x = int(3/2.0)       # this is OK
x = int(y/2.0)       # this gives the narrowing warning

**Comment by sent44** [comment]
> x = int(3.0/2.0) # this is OK
> x = int(3/2.0) # this is OK
> x = int(y/2.0) # this gives the narrowing warning

Constant number equation is kind of resolve by engine before run game.
So `x = int(3/2.0)` will become `x = 1` before run.
While `x = int(y/2.0)` in this case `y` is variable, unknow value, so it won't be resolve before runtime, the engine will leave `x = int(y/2.0)` as it is, so narrowing conversion should be raise. Not unpredict.
