### ISSUE TITLE
Font outlines are anti-aliased

### ISSUE THREAD

**Issue by markdibarry** [godotengine/godot#59068]
### Godot version

4.0dev (35c8d33)

### System information

Windows 10

### Issue description

#59013 seems to have caused a regression where all font outlines are anti-aliased without a way to turn it off.
Pretty sure this is a known issue, but decided to make a formalized bug report.
Example below of what it looks like:
![image](https://user-images.githubusercontent.com/21325943/158021218-579a74ac-404d-4699-9e57-a89d0ae3cac3.png)

![image](https://user-images.githubusercontent.com/21325943/158021210-f6301829-2d4b-4399-99ed-49a56034a13c.png)

### Steps to reproduce

Add a text-based node. Add text. Add font-outline.

**Comment by bruvzg** [comment]
Can't reproduce.

With AA disabled in the font import settings, outlines in the running project are not anti-aliased, in the editor it's always a bit blurry (but this is how editor viewport work and has nothing to do with the font rendering).

#59013 should not have any effect on AA, but you might need to reimport fonts if they were first imported before it was merged.

**Comment by markdibarry** [comment]
Ah you were right. If they weren't before (probably were), anti-aliasing is default for imported fonts, and #59013 or some other recent merge reset that for existing projects.

Closing as resolved due to user error.

**Comment by Calinou** [comment]
> If they weren't before (probably were), anti-aliasing is default for imported fonts

Antialiasing was always enabled by default for imported DynamicFonts, both in 3.x and `master`.
