### ISSUE TITLE
Godot 4: Using a variable node from another script will generates an error in Visual Script

### ISSUE THREAD

**Issue by kreaninw** [godotengine/godot#59070]
### Godot version

v4.0.alpha4.official [f47097973]

### System information

Windows 11, Vulkan Clustered, Intel UHD Graphics 620 v30.0.101.1340

### Issue description

In Godot 4, the user can copy any Visual Script node (except for function nodes) to be used in another script. However, the destined script will generate an error on a variable node, as shown in the screen recording below:

https://user-images.githubusercontent.com/1403194/158023832-a76200c0-f8fd-4aef-95bc-cd9fc2ea49ff.mp4

This is due to the fact that the editor doesn't copy the variable value from the _source_ script to the _destined_ script as well, thus the destined script failed because the variable hasn't been established yet. 

I expect the variable to be created and preserved its value and type automatically in the destined script. 

### Steps to reproduce

1. Create a variable in Visual Script.
2. Copy the variable node (in the canvas) to another Visual Script file.
3. Print the copied variable in `_ready` function. You will see an error.

**Comment by KoBeWi** [comment]
VisualScript was removed in Godot 4.0, so closing.
