### ISSUE TITLE
InputEventScreenTouch on touch screen counts its index indefinitely even after restart

### ISSUE THREAD

**Issue by kreaninw** [godotengine/godot#59079]
### Godot version

v4.0.alpha4.official [f47097973], v3.4.3.stable.official [242c05d12]

### System information

Windows 11, Vulkan Clustered, Intel UHD Graphics 620 v30.0.101.1340

### Issue description

`InputEventScreenTouch` on touch screen counts its index indefinitely even after restart, as shown in the screen recordings below:

**Godot 4:**

https://user-images.githubusercontent.com/1403194/158034111-95aaa033-db44-4311-9afe-969d93f762b5.mp4

**Godot 3:**

https://user-images.githubusercontent.com/1403194/158034134-7f0cb9d7-2db7-4d2e-8a40-c82e42a2b5e2.mp4

However, when it responds to the touch that's emulated from a mouse click within the engine, it will always return 0 (I assume it will return 1, 2, 3, ... on multi-touch).

I expect `InputEventScreenTouch` to return its index according to the number of concurrent touches, as explained in the [docs](https://docs.godotengine.org/en/latest/classes/class_inputeventscreentouch.html?highlight=inputeventscreen#class-inputeventscreentouch-property-index).

### Steps to reproduce

1. Open the reproduction project according to your Godot version.
2. Run the project, touch inside the window, then look at the print value. The index value will count indefinitely on touch screen input but it will return its index correctly on touch emulated from a mouse click. 

### Minimal reproduction project

**Godot 4:** 

[G4Test.zip](https://github.com/godotengine/godot/files/8238408/G4Test.zip)

**Godot 3:**

[G3test.zip](https://github.com/godotengine/godot/files/8238412/G3test.zip)

**Comment by madmiraal** [comment]
This is not a bug. It's the desired behaviour. godotengine/godot-docs#4431 reports the problem with the documentation. The bigger problem is that there is an inconsistency between platforms. This issue is discussed in godotengine/godot-proposals#3772, which proposes that all platforms (and the documentation) be updated to provide a perpetually incrementing index to uniquely identify each touch.
