### ISSUE TITLE
Collapsed nodes in the shader graph

### ISSUE THREAD

**Issue by arturjpv** [godotengine/godot#5908]
Mac OSX El Capitan - Godot 2.1 RC.

When deleting a node in shader graph, with other nodes selected all selected nodes are "collapsed" at the mouse position.

To reproduce:
- Open a shader graph with some nodes
- Select some of them (sometimes they are automatically selected)
- Delete one node (clicking on x)
- Move the mouse -> all selected nodes are collapsed. (if you double click when deleting this does not happen)

**Comment by akien-mga** [comment]
CC @MarianoGnu.

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone (though an early fix would of course be very welcome).

**Comment by akien-mga** [comment]
The visual shader editor was removed (temporarily) from 3.0, and will be readded in 3.1. Since the code will be different, assuming this issue won't apply anymore (if it does, please open a new issue about it or comment here).
