### ISSUE TITLE
Tree does not fill VBoxContainer unless Expand is also checked

### ISSUE THREAD

**Issue by Erfa** [godotengine/godot#59097]
### Godot version

v3.4.2.stable.official [45eaa2daf]

### System information

Windows 10, GLES3, NVIDIA GeForce GTX 1080 (511.79)

### Issue description

If you place a Tree in a VBoxContainer, it does not fill the space vertically like other nodes do with "Fill" selected, unless you also set it to _expand_ vertically. In my case I only wanted the tree to fill the size that it needs, not expand to the whole container.

https://user-images.githubusercontent.com/148950/158058165-4c77473a-664e-473e-8723-d494265eb398.mp4

### Steps to reproduce

1. Create a project with a Control root and add a VBoxContainer
2. Add a Tree to the VBoxContainer and optionally some elements before and after it to see how they behave
3. Attach a script to the Tree that creates some children
4. Experiment with turning the Tree's "Expand" property on/off under "Size Flags Vertical", while "Fill" is turned on

### Minimal reproduction project

[vboxcontainer-tree.zip](https://github.com/godotengine/godot/files/8239428/vboxcontainer-tree.zip)

**Comment by KoBeWi** [comment]
Vertical "Fill" doesn't have effect in VBoxContainer. The reason other controls fill their space is that they have minimum size (e.g. label will always display whole text). Tree doesn't have minimum size, because it has a scroll bar, thus you need to explicitly tell it that it should take all available space or give it a minimum size.

**Comment by Erfa** [comment]
That does make it hard to do thing like placing a label, a tree, and a grid view in a vertical column and have a common scroll bar for all of them. If anyone know how to do that feel free to elaborate.

Seems like for increased composability Tree shouldn't even have a scrollbar unless placed in a ScrollContainer.

**Comment by KoBeWi** [comment]
Ah, there is `scroll_vertical_enabled` property in Tree. If you disable it, it will no longer shrink.

**Comment by Erfa** [comment]
Hm, is there? Sounds like a good workaround, but I don't see `scroll_vertical_enabled` in the docs for [Tree](https://docs.godotengine.org/en/stable/classes/class_tree.html?highlight=scroll_vertical_enabled). It is in the docs for [ScrollContainer](https://docs.godotengine.org/en/stable/classes/class_scrollcontainer.html#class-scrollcontainer-property-scroll-vertical-enabled) though.

**Comment by KoBeWi** [comment]
Looks like it's only available in Godot 4.0. You can [check the alpha here](https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-4) to see if that's what you need.

**Comment by Erfa** [comment]
I see, that is good news. I'll probably just adjust my UI to have expanded Trees for now and consider changing it back once 4.0 is in beta. Thanks!
