### ISSUE TITLE
Autocompletion not working inside method calls

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#59091]
### Godot version

6721290

### System information

W10

### Issue description

![godot windows tools 64_Rm6YePOuan](https://user-images.githubusercontent.com/2223172/158040836-09ebea89-4281-4885-ac06-d4a646a26d0c.gif)

### Steps to reproduce

1. Add a script to Node2D
2. Try to print position
3. Notice that you don't get autocompletion inside `print()`

**Comment by Chaosus** [comment]
`print` accepts any number of arguments thats why that sequence is show

**Comment by Chaosus** [comment]
Ah I see - you expected to see a popup with members instead of function signature.

**Comment by KoBeWi** [comment]
Actually a duplicate of #58561
