### ISSUE TITLE
NavigationAgent2D/3D.get_nav_path() returns stale path

### ISSUE THREAD

**Issue by Shou** [godotengine/godot#59104]
### Godot version

3.5 beta, master

### System information

NixOS

### Issue description

When `NavigationAgent2D.get_nav_path()` (or 3D) is executed, it returns a stale path unless `update_navigation()` is called first, and `update_navigation()` isn't exposed to GDScript -- this can for example result in confusing implicit behaviour where nothing is navigating if one relies on `get_nav_path()` exclusively. Should one of these options be considered?

* `update_navigation()` should be called in `set_target_location()`
* `get_nav_path()` should call `update_navigation()`
* `update_navigation()` should be exposed in GDScript

I'm happy to submit a PR and update docs if necessary.

Relevant files

* https://github.com/godotengine/godot/blob/0f5455230c8955be0c6533574bd3d5b6f50792b6/scene/2d/navigation_agent_2d.cpp
* https://github.com/godotengine/godot/blob/0f5455230c8955be0c6533574bd3d5b6f50792b6/scene/3d/navigation_agent_3d.cpp

### Steps to reproduce

1. Call `.get_nav_path()` without first calling `get_next_location`, `get_final_location`, or `is_navigation_finished()`.

**Comment by akien-mga** [comment]
CC @godotengine/navigation @Scony

**Comment by Scony** [comment]
From the code it looks like it should be fairly safe to call `update_navigation()` in `set_target_location()`. @Shou can you create such a PR and annotate me?

**Comment by Shou** [comment]
@Scony made the PR now ^

**Comment by smix8** [comment]
A function to receive the full path without triggering any updates is required for many use case like debug draw or other sophisticated navigation behaviour.

Maybe this is a function naming issue but for me `get_nav_path()` always was supposed to serve a full "stale" path and NOT to do updates. The docs clearly state "Returns the path from start to finish in global coordinates." so please consider that is all I (and maybe others) would expect it to do without side effects.

**Comment by smix8** [comment]
Note that if you want to move an actor manually like in old Godot you do not need to use a NavigationAgent Node.

You can use `NavigationServer2D.map_get_path(get_world_2d().get_navigation_map())` from any Node2D inheriting Node (or same with 3D) to get a fresh path array.
