### ISSUE TITLE
Expose Drag And drop to gdscript more

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#5911]
This is a continuation of 
https://github.com/godotengine/godot/issues/5625

basically Godot master now has support for drag and drop - but it is not complete. It has a number of missing key elements.

 [ ]Ability to determine on which node the files have been dropped on - Currently drag and drop event is triggered regardless of where on the application window you drop the files. As a result your application can not have more than one drag and drop areas.

I tried doing it with focus_enter and focus_exit signals and a variable. Didnt work. Focus enter signal requires the user to click on the node - which doesnt work with drag and drop.

[ ] The 'Screen' value is always returning a 0 -

> @TheHx What does the 'screen' (string) value do? I noticed that it always returns a zero.
> 
> @TheHX  :
> I'm not sure, but i think the screen parameter is index of the from where the files are dragged, but as it seems the feature is not implemented:
> https://github.com/godotengine/godot/blob/master/platform/windows/os_windows.cpp#L767
> https://github.com/godotengine/godot/blob/master/platform/x11/os_x11.cpp#L1531
> https://github.com/godotengine/godot/blob/master/platform/osx/os_osx.mm#L330

I suggested adding a on_files_dropped signal to GUI nodes in godot - but I am not sure if thats the best solution.

Another suggestion is to add a signal to nodes that fires when the mouse has hovered on them. As noted earlier focus_enter and focus_exit dont work in this case because they trigger only if the user clicks. Cant click while you are dragging a file.

So if anyone has any idea how to do this properly or has a workaround - thanks in advance. :)

**Comment by blurymind** [comment]
I might be able to do a workaround with a variable and a mouse enter and mouse exit signal
https://godotengine.org/qa/3207/mouse_enter-signal-is-not-triggered

But it would be so much easier if there was a way - an option to trigger the drag and drop signal only if the cursor dragging the files is above a specific node during a drop

**Comment by vnen** [comment]
I'm not sure if this should be tied to a node. What I think is that drop should report the mouse position, so you can determine if it's in a valid place.

**Comment by blurymind** [comment]
@vnen  that would work too! :D 
I have been playing with making a small app in godot ever since, and managed to get this working. 

I used the on_mouse_enter() and on_mouse_exit() signals to determine if the user's mouse is hovering over the area (store it in a variable) or not and execute an appropriate action - depending on the case of where the files have been dropped
