### ISSUE TITLE
Godot editor sometimes crashes when resources are moved into another folder

### ISSUE THREAD

**Issue by SchattenPirat** [godotengine/godot#59116]
### Godot version

3.4.2

### System information

Windows 11, RTX 3080, GLES3

### Issue description

Description:
When I created some scenes, scripts etc and I want to rearrange them in my project structure. For instance move a scene from the root folder into my scene folder the editor crashes quite often. Not always but quite often.

Does the editor produces some error log? Maybe I can attach it then. I am quite new to Godot.

Operating System:
Windows 11 21H2 Build 22000.438

Godot version:
 3.4.2.stable

Thanks Bernd

### Steps to reproduce

Move a resource in the file system of the godot editor from the root folder to a subfolder. It crashes estimated every third time.

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/29266.

**Comment by Calinou** [comment]
I can't reproduce this on 3.6.beta 92aedd506 (Linux).

I get this error in the Output panel though:

```
Another resource is loaded from path 'res://scenes/example/example.gd' (possible cyclic resource inclusion)
```

**Comment by me2beats** [comment]
I've just got crash in Godot 4.1 dev 4 when moving folder with texture pack. I've downloaded the texture pack and copy pasted it to the wrong place so I move it to res and got crash.
