### ISSUE TITLE
FileDialog filters "*" can't be parsed properly by tscn

### ISSUE THREAD

**Issue by Kermer** [godotengine/godot#5912]
**Operating system or device - Godot version:**
Win7 x64, Godot v2.1rc1

**Issue description** (what happened, and what was expected):
App crashes if there's FileDialog in the scene. It works/looks more like a stopping scene right after running it.

**Steps to reproduce:**
Just add FileDialog anywhere to the scene.

**Link to minimal example project** (optional but very welcome):
^ Up ^

**Comment by hetdegon** [comment]
I noticed this as well. Seems to be because in tscn format there's no filter defined. I solved it by adding something like "filters = StringArray( "*" )" to the tscn file.

**Comment by akien-mga** [comment]
Indeed, it chokes with when running on:
```
ERROR: poll: res://Control.tscn:30 - Parse Error: Expected string
   At: scene/resources/scene_format_text.cpp:473.
ERROR: load: Condition ' err!=OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:142.
```
It doesn't crash though, it just fails loading the scene.

As mentioned by @hetdegon, the line 30 mentioned in my error message is:
```
filters = StringArray(  )
```

**Comment by Kermer** [comment]
Also changing amount of filters in the Inspector allows the scene to be loaded. (You can use clear_filters() after it's loaded)

**Comment by bojidar-bg** [comment]
Can confirm...
