### ISSUE TITLE
CSGPolygon in mode Path makes RigidBody bounce

### ISSUE THREAD

**Issue by LukoFoks** [godotengine/godot#59120]
### Godot version

3.4.2.stable

### System information

Windows 11, GLES3, Intel® Iris® Xe Graphics

### Issue description

*CSGPolygon* in mode Path and with generated Collision makes a *RigidBody* unexpectedly bounce.

https://user-images.githubusercontent.com/63813215/158077075-6a3cb6d2-e968-44db-a957-baede518238b.mp4

*CSGPolygon* in mode Depth and with generated Collision makes a *RigidBody* correctly smoothly move.

https://user-images.githubusercontent.com/63813215/158077172-ae652437-276c-4218-88f3-c59b88de548a.mp4

Bug does not happen to *KinematicBody*.

### Steps to reproduce

- Add Node: *Path*
- Add Points to *Path*
- Add Node: *CSGPolygon*
- Set *CSGPolygon* Property:
  - Mode: Path
  - Assign: Path
  - Use Collision: On
- Add Node: *RigidBody*
- Set *RigidBody* Property:
  - Mode: Character
- Add Node to *RigidBody*: *CollisionShape*
- Set *CollisionShape* Property:
  - Shape: New *BoxShape*
- Add Node to *RigidBody*: *MeshInstance*
- Set *MeshInstance* Property:
  - Shape: New *BoxShape*
- Add Script to *RigidBody*
```GDScript
extends RigidBody

func _integrate_forces(state):
	apply_central_impulse(Vector3.FORWARD / 4)
```

### Minimal reproduction project

[Bug.zip](https://github.com/godotengine/godot/files/8240504/Bug.zip)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/50463 (likely a duplicate, unless you can't reproduce this when the CSGPolygon is manually converted to a MeshInstance using a script).

3 things to try:

- Try enabling **Smooth Trimesh Collision** in the Project Settings (only effective for Bullet).
- Try increasing **Physics Fps** to 180 or 240 in the Project Settings.
- Try switching the 3D physics engine to **GodotPhysics** in the Project Settings.

**Comment by LukoFoks** [comment]
I confirm duplicate
- [3D rotating/spinning RigidBody bumpy collisions with Trimesh Static Body](https://github.com/godotengine/godot/issues/50463)
- [[Bullet] 3D RigidBody collisions with static collision shapes still bumpy](https://github.com/godotengine/godot/issues/46596)

**Comment by LukoFoks** [comment]
> This is likely a duplicate of that issue, unless you can't reproduce this when the [CSGPolygon is manually converted to a MeshInstance using a script](https://github.com/godotengine/godot-proposals/issues/182).

I converted *CSGPolygon* to *MeshInstance* using a script and created a trimesh collision from it.
```GDScript
_update_shape()
var mesh = MeshInstance.new()
mesh.mesh = get_meshes()[1]
mesh.create_trimesh_collision()
add_child(mesh)
```
On *CSGPolygon* turned off `Use Collision` .
Bug still persists.

## Alternative

- `create_convex_collision()` does not create a correct collision.

![Convex](https://user-images.githubusercontent.com/63813215/158233276-a56a0424-9058-42c1-8c3c-da04d605b567.png)

- `create_multiple_convex_collisions()` is not precise enough

![MultiConvex](https://user-images.githubusercontent.com/63813215/158233468-28b06fcf-25ba-43ea-a859-8077dad64cdd.png)
