### ISSUE TITLE
Godot SplashScreen Android 12 and later

### ISSUE THREAD

**Issue by MiqueiasDevGames** [godotengine/godot#59151]
### Godot version

3.4.3

### System information

Linux

### The solution for Godot Splash Screen on android

Imagine a SplashScreen that ends at the exact moment your main scene loads.

Can you imagine? Now stop imagining and contemplate:
[https://github.com/MiqueiasDevGames/Godot-SplashScreen-Android-12](https://github.com/MiqueiasDevGames/Godot-SplashScreen-Android-12)

Godot developers might as well adapt this project to work natively on Godot.

Who wants this functionality natively in Godot, comment here, leave your thumbs up and share.

### Steps to reproduce

Imagine a SplashScreen that ends at the exact moment your main scene loads.

Can you imagine? Now stop imagining and contemplate:
[https://github.com/MiqueiasDevGames/Godot-SplashScreen-Android-12](https://github.com/MiqueiasDevGames/Godot-SplashScreen-Android-12)

**Comment by Calinou** [comment]
Closing, as feature proposals should be discussed on the [Godot proposals](https://github.com/godotengine/godot-proposals) repository. This repository is now used for bug reports only.

Make sure to follow the proposal template when opening a new proposal – don't just copy and paste the text you wrote in this issue.
