### ISSUE TITLE
[Godot4 a2]Base class can't recognize Sub class parameter

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#59154]
### Godot version

v4.0.alpha2.official [79077e6c1]

### System information

Window2 10

### Issue description

![1](https://user-images.githubusercontent.com/35988767/158290185-55f7763d-8f1c-44ee-857f-acefe3d7ecf4.PNG)
![2](https://user-images.githubusercontent.com/35988767/158290200-ab83c24a-d98f-4ea9-9ffa-9fb20bb08aef.PNG)
![3](https://user-images.githubusercontent.com/35988767/158290204-7797dd38-3f74-45ed-9307-4f5d5d281f65.PNG)
![4](https://user-images.githubusercontent.com/35988767/158290210-b79a8efd-ad5c-472b-bedb-d475ac6c3266.PNG)

### Steps to reproduce

Please run the reproduction project.

### Minimal reproduction project

[SubClsTest.zip](https://github.com/godotengine/godot/files/8249535/SubClsTest.zip)

**Comment by vnen** [comment]
I can't reproduce this in current master, I assume it has already been fixed.
