### ISSUE TITLE
Documentation to support HIDPI  in project

### ISSUE THREAD

**Issue by DimitriyPS** [godotengine/godot#5916]
Godot 2.1

I already asked the community [(linc),](https://godotengine.org/qa/6388/hidpi-in-projects) but as I suspected, is too new.

I repeat, with the release of version 2.1, actual question "HIDPI support in projects". As I understand it, now there are such means in the Arsenal of Godot.

I looked at the project settings dialogue, and found some interesting new properties:
![0000](https://cloud.githubusercontent.com/assets/11189223/17131553/ad8cd4d0-5326-11e6-9589-96d9eaa1fe39.png)

I test them all turned and ran the demo. The demo used a standard skin Godot. I get the expected result - support HIDPI. But when I used the demo with a different skin... I needed a magnifying glass.

Need to document support HIDPI in projects.

P.S.: Please advise me how can I correctly implement support for HIDPI in your project. For me it is very important. I want to make sure that do not have to redo it.

**Comment by akien-mga** [comment]
We do need some documentation on making themes yes, including how to make them support HiDPI.

**Comment by DimitriyPS** [comment]
**akien-mga**, this question... it requires detailed documentation... or You can give a few quick tips in advance?

**Comment by akien-mga** [comment]
I don't know how to do this either, but have a look at #5243 and 816b3fa.

**Comment by akien-mga** [comment]
Basically you need to create two themes, one for lodpi and one for hidpi. Then you can likely use `OS.get_screen_dpi()` to see if your game is running in lodpi or hidpi, and load the corresponding theme from script.

@reduz Should the logic in 816b3fa be improved to allow defining two custom themes in the settings (lodpi/default and hidpi), so that the `use_hidpi_theme` property can be used for user themes too?

**Comment by Calinou** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by DimitriyPS** [comment]
This question concerned the writing of an article in the documentation. That those who develop games taking into account different screens (Ldpi,Hdpi) could correctly adapt the interface of the project.

This can be solved in different ways (I found a way to solve this problem), so I would like to have recommendations from Godot developers. I think it's still relevant. But not perhaps there standard recommendations-then can be close this message.

**Comment by akien-mga** [comment]
Moved to godotengine/godot-docs#1933.
