### ISSUE TITLE
Video trailer to showcase Godot features (version-agnostic)

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#5917]
We're now dangerously nearing the 2.1 release (it's more or less release ready now, but we should take the time to prepare some proper PR material before announcing it IMO), so here comes the now obligatory issue about making a cool video trailer for Godot 2.1.

Having such a video would be great for our blog post + maybe landing page + Steam store and, last but not least, for the official press release we'll send all over the world for the press to make some noise about us.

If we don't manage to make a new video in time for the release, we can of course reuse the games showcase done in #3877; what I have in mind here though is something that would show the editor a bit more, and maybe try to highlight the killer features of Godot as a game engine. If we do have a new video for 2.1, I still plan to use the games showcase for the PR anyway, two videos are better than one ;)

I'll start writing some ideas about the contents in the next comment, please add yours :)

**Comment by Sslaxx** [comment]
If we're going editor-side for the video, 2.2 with its (beginning) visual scripting implementation would be a more major milestone. Do we, strictly speaking, _need_ a release video for every non-major release?

**Comment by akien-mga** [comment]
2.1 is a major release, it's 6 months of work.

**Comment by akien-mga** [comment]
To give more context about what we should IMO aim for: Godot is basically unknown outside in the gamedev industry. For this release, we want to send a proper press release to hundreds of press contacts, and thus get some of them to publish news articles about Godot and its new release.

That means that the target of our press release, and thus of the accompanying video, should be mostly people who never heard about Godot; we need to convey the killer features of Godot in a short video, to make those people want to give it a try.

In other words, we probably shouldn't focus on making a "What's new in Godot 2.1" kind of video changelog, but more a quick teaser / trailer / overview of what we find the most interesting (albeit still visually relevant, we need the video to be visually striking, so we can't spend too much time explaining deep API concepts) as of Godot 2.1.

We could basically try to put in a video the contents of our [Features page](https://godotengine.org/features); not all of it of course, but showcase 8 - 12 concepts that make Godot unique would be awesome.

**Comment by punto-** [comment]
We are also dangerously close to Gamescom, if we could have something to take there, it'd be great :)

**Comment by djrm** [comment]
i would suggest a narrated video, something like the gnome release videos, https://www.gnome.org/news/2016/03/gnome-3-20-released/, i agree with akien, it should should show what godot is, what are the advantages of using it, and its core features.

**Comment by her001** [comment]
I am again offering to edit the video (and more).

**Comment by neikeq** [comment]
@djrm I remember we also talked about that on one of the irc meetings, but it was about making devlogs. Of course, the problem is finding a narrator with good voice that would volunteer to do it :)

**Comment by Dillybob92** [comment]
For what it's worth, one thing I think that not a lot of people know about Godot is how amazing the UI elements are. Window popups, item listings, dropdown boxes, file dialog, input fields, context menus (now new in 2.1) -- etc, etc (just off the top of my head). Not a lot of game engines come with all these elements done natively, or even available. It makes creating game interfaces extremely easy and the ability to do complex UI's fairly easier since we get access to the draw method on basically anything.

**Comment by Zylann** [comment]
Would narration imply translation in multiple languages?

**Comment by freemanfromgodotengine** [comment]
Narrative video would mean (if we want it to sound normal and not amateurish):
- preparing script with text that needs to be recorded;
- paying for the voice actor.

For example maybe this two voices
[man 1](http://www.thevoicerealm.com/view-profile-artist.php?artist_id=1211)
[man 2](http://www.thevoicerealm.com/view-profile-artist.php?artist_id=1063)
or if we prefere women's voices:
[woman 1](http://www.thevoicerealm.com/view-profile-artist.php?artist_id=1277)
[woman 2](http://www.thevoicerealm.com/view-profile-artist.php?artist_id=792)

Total cost probably $140 - $185 for the INTERNET USE / EXPLAINER & WHITEBOARD VIDEOS / CLIENT PUBLIC WEB USE license 
depending on recording time 1 or 2 minutes (text recording 85 - 300 words)

Unless we aim for subtitles only promo video, similar to 
[promo video example 1](https://www.youtube.com/watch?v=lL1eFi-tG9A) 
[promo video example 2](https://www.youtube.com/watch?v=w9rkhCUAHT0)

**Comment by Dillybob92** [comment]
$185 seems awfully expensive just for a 1 - 2 minute voiceover. For example, [this guy on fiver](https://www.fiverr.com/markc1542/record-a-professional-voice-over-up-to-60-seconds-in-length?context=adv.cat_12.subcat_16&context_type=rating&pckg_id=1&pos=6&funnel=b4cd1e09-4412-4c74-ba5b-586dfb410d33), sounds amazing and it's only 10-15$ for 300 words.

**Comment by freemanfromgodotengine** [comment]
@Dillybob92 Looks like you have found an alternative - guy should be added to alternativeto.net ;)
I think he would not cost $15 for 300 words, rather $75 with "For Commercial Use" License if I counted correctly, but his voice should work and he has all that is needed to do it right.

**Comment by akien-mga** [comment]
I'm still more in favour of a video with good on-screen-display than with a narrative voice over, but if you guys want to work on the latter why not :) Please just keep in mind that 2.1 is imminent, so ideally it would be good to have something ready within a week or so (and of course, it will be what we can manage in so little time - we can always make some more awesome with more time after the release).

**Comment by freemanfromgodotengine** [comment]
@akien-mga video with on-screen-display would be just fine. Voice could add that extra production value, but on the other hand @punto- more than once was explaining presentation problems and I remember that he was trying to talk during presentation to explain things happening on screen and that case the voice-over would be just in his way.

**Comment by neikeq** [comment]
Yeah, I am not sure if a narrator is a good idea for the trailers. It makes sense for devlogs though, and you don't need a professional narrator for a devlog, just someone from the community that volunteers :)

**Comment by Bonfi96** [comment]
I'd say on screen display + translated youtube subs (something like [this video from unity](https://www.youtube.com/watch?v=AJ6Mkx1KEns)) for something that's along the "look how cool is godot right now" line. Instead for a proper devlog, a narrating dev playing around in the editor with examples is far better as in this kind of video focuses more on the technical side of things.

**Comment by freemanfromgodotengine** [comment]
@Bonfi96 And we definitely have to show possibility of removing/editing the splash screen for free ;)

**Comment by djrm** [comment]
i will list some topics that i think would be good to have in the video

- Briefly explain about the concept of free engine
- show the kind of games that can be done
- explain a little bit how the games are made (scene system and that stuff)
- showcase the editor and its tools, also the things that it supports

and i think that would be it for a short introductory video

**Comment by neikeq** [comment]
^ and:
- Show what's new in 2.1

**Comment by akien-mga** [comment]
> Show what's new in 2.1

Actually going by @djrm's proposed topics, I wouldn't particularly mention 2.1 features; the main issue with showing what's new in a given version, is that as soon as a new version is out, your video becomes obsolete.

> The problem is with that list is that it would need a narrator. We are too close to 2.1. I wouldn't think of anything too complex at this point.

I guess we could convey the ideas behind what @djrm proposed using only video and on-screen-display. For example something like "Scene inheritance and customization" as OSD and a short video snippet showing a new inherited scene being created and customized in a few clicks.

**Comment by freemanfromgodotengine** [comment]
@her001 and I, we came up with this list of Godot's important feature that should be shown:
- is free and open
- is multiplatform
- is available on Steam
- deploys games across desktop, mobile and web.
- has internationalized editor UI
- works great with HiDPI/Retina screens
- integrated editor
- debugging/profiling
- scripting language
- animation system
- attracts unique, friendly and helpful people to it's community (irc, Q&A, forum) - you will find artists, musicians, hobbyists as well as pro-programmers all participating in Godot's community!
- has new asset sharing platform.
- editor customization, including fonts, themes, and keybindings
- live editing
- Context sensitive editor UI
- complete UI system, including context menus
- ...
- has easily removable/editable splash screen.

Did we miss anything important?

**Comment by her001** [comment]
To be clear, this will be condensed and reorganized before being used in the video.

**Comment by djrm** [comment]
i dont think 'is available on steam' is a compelling feature.

> has easily removable/editable splash screen

i dont think this is worth mentioning, it is like directly comparing to unity. what its more important about the openess and freedom, is that you can do whatever you want with the engine, no EULA, terms of service or hidden conditions or costs. Also the ability to modify the engine to your needs.

also i think for the in introductory video it will be more important to mention the Scene system  and how it is used to create games in a modular and easy way.

**Comment by Bonfi96** [comment]
@djrm I think that to start raising in popularity godot has to start comparing with other "free" engines. I come from unity and as a person who didn't knew almost anything about game development I know that something like "aviable on steam" or "removable splash screen" is, for a newbie, as important as the advanced technical features. Godot is getting more and more popular but it still misses a wide community as unreal or unity have. If more people gets interested in godot, even people who doesn't know anything about game dev, the more tutorials will pop up online, people who knows stuff will be encouraged to share their knowledge, more people would work on docs making it easier for other newbies to try the engine.  With 2.1 and the editor usability overhaul I think it's the right time for godot to get more and more appealing to "the masses".

**Comment by neikeq** [comment]
We are really close to 2.1 release. We should collaborate with screen recordings if we want to get in time. IMO we should only showcase what's new in this release, since we are running out of time.

I took freeman's list and added/modified some stuff:

- Free and open source with a great community (I put both together)
  - Here we could just have a short screen capture of our github repository and some of the community sites.
- Available on Steam
  - I would make this a part of the previous point
- Multi-platform + deploys games across desktop, mobile and web
  - We could have short screen captures of the editor running on different systems and a video of a games running on an android/iOS device, the web and desktop (we could re-use an existing one with the consent of the author).
- ~~Integrated editor~~ (This is pretty obvious)
- Debugging/profiling
- Scripting language
- Animation system
- Live editing
- Context sensitive editor UI _(how would you show this?)_
- Godot's UI system
  - Notice I removed "context menus" from this point. Godot's UI always supported context menus. It's just a PopupMenu, but the editor was not using it.
- Scene system
  - Recording some complex scene tree could work

##### New in 2.1:

- Works great with HiDPI/Retina screens
  - Will need someone with HiDPI/Retina screen to record it.
- Profiler
- Asset sharing platform
- Key bindings customization
- Dynamic fonts
  - The easiest way to showcase this is probably by zooming a TextEdit.
- Editor internationalization
  - Very short screen captures of the editor with different languages.
- New plugin API
  - Not sure if we have any plugin to showcase. Maybe a screenshot of the EditorPlugin docs, or someone could show a custom dock.
- Custom themes (do we have any beautiful custom theme to showcase?)
- Live script reloading (not sure how this could be shown)
- Context menus
- Editor drag & drop
- Script editor usability improvements
  - Incremental search (search bar)
  - Better highlighting (there are some good syntax themes to showcase)
  - Smart function matching in code-completion
- Automatic re-import and reload of assets and scenes when changed
- Preview resources in the inspector
- New AnimatedSprite features

It would be good if we could record some of those features accompanied with good looking games.

**Comment by vnen** [comment]
> Context sensitive editor UI (how would you show this?)

This might be easy to show by clicking on SamplePlayer, AnimationPlayer nodes, and editing a theme.

**Comment by akien-mga** [comment]
Regarding the video for the 2.1 release announcement, I can now give you guys a deadline: as I won't be available from tomorrow till Sunday, and we're not really ready with the release announcement yet, I plan to release 2.1-stable on Monday, Aug 8th (UTC evening). So if you can have a video ready by the week-end, it would be perfect.

I see tons of great ideas above, so in case you want to work on something a bit more complex that will take more time, it's fine too. In such a scenario, take all the time you need, but try to make it as far as possible version-agnostic, so that it does not become obsolete too fast :)

Another possibility on the video battlefront would be to do an actualised version of our games showcase to feature recent games like A Game of Changes and Marble Machine. That would of course imply reworking the music track to fit in new entries, and maybe also using slightly longer footages for each game (and thus reworking the music too) as @punto- mentioned.

So, various possibilities, pick what you guys feel like working on, you'll rock in any case :D
Over and out for a short holiday! (Ok only tomorrow, tonight I want to publish 2.1 RC2 first ;)).

**Comment by twirlimp** [comment]
@neikeq Just adding that there's actually a Tiled importer plugin linked on the Trello page under the relevant feature.

**Comment by akien-mga** [comment]
2.1 is now released, so I renamed the issue to repurpose it ;) I still think that it would be awesome to have a new video that showcases Godot features, maybe as far as possible in a version agnostic way.

To give the temperature, on Steam we're showcasing Godot with the official presentation video of Godot 1.1, so it starts with "What's new in Godot 1.1"... :)

**Comment by Hinsbart** [comment]
Bump, as we're approaching 3.0 :)

**Comment by reduz** [comment]
we are working on it with Calinou

**Comment by akien-mga** [comment]
Don't forget about this, Godot 3.0 is coming :)

**Comment by freemanfromgodotengine** [comment]
And we are always waiting for... Godot. :)

**Comment by gururise** [comment]
Doesn't this video meet the requirements?
https://www.youtube.com/watch?v=4v3qge-3CqQ

**Comment by akien-mga** [comment]
No, as great as it is, 30 min talk is not an awe-inspiring trailer :)

**Comment by akien-mga** [comment]
CC @NathanLovato This is an old issue and partly outdated, but some of the discussion above might still be relevant for an upcoming showcase of Godot features.

As before, there's potential for making two different videos with different use cases:
- What's new in Godot 3.1 (for the release announcement)
- General overview of Godot features (to put on the website, Steam, itch.io, etc.)

**Comment by NathanLovato** [comment]
A good overview/trailer takes a ton of work to make. We could take care of it if we can get some help to gather outstanding footage, as it's mostly what it boils down to if you want to sparkle interest.

I've spent a lot of time browsing the web and getting in touch with people to find projects like these to only find a few. More than just the features, you want to show them in the context of an impressive game project. If we're talking about a trailer to appeal to people who don't know/use Godot.

Would you like us to produce something like that? I can produce a concrete outline after I come back from Tokyo, and we can iterate on that. But we'll need help from the community to gather footage and demo material as I don't have enough to make a striking video. Through a post on the website and community channel?

A what's new video is a lot simpler. As it's for the users and returning users you don't need as high production value. I can give you an outline to build upon by the end of the week as well. Does that sound good to you? 
If so may we close this issue, and may i.open two new ones with the wip outline, for the community to give feedback on?

**Comment by NathanLovato** [comment]
Also do you want a narrated video as suggested above? If so we can make it so it works both with and without sound (for social networks)

**Comment by akien-mga** [comment]
Yeah, the overview trailer is more a long term wish and there's no hurry to work on it. We can however start planning the outline indeed, and gather some footage from community members with cool looking projects that could showcase features.

The what's new video should be the focus for now, as we'll need it by mid/late January for the 3.1 release if all goes well.

I don't think either should be narrated, only some text overlay maybe to name features as we see them and maybe give some interesting details. It's indeed better if people can watch them without sound and still get the point - and it removes/reduces the need for localization. And we can use epic music :P

>  If so may we close this issue, and may i.open two new ones with the wip outline, for the community to give feedback on?

Agreed, thanks!
