### ISSUE TITLE
Vulkan: Crash when adding CPUParticles3D

### ISSUE THREAD

**Issue by kicknbrit** [godotengine/godot#59171]
### Godot version

4 alpha 3 dev

### System information

Win 10, Nvidia mx250, i7 1050U

### Issue description

Cpu particles crash godot whenever I assign anything other than a quadmesh to their 'mesh' slot.

### Steps to reproduce

Create a node3d. Add a cpu particle node as child. Add a planemesh or cubmesh to cpu particles 'mesh'. Play scene. It crashes for me.

**Comment by Snowapril** [comment]
I have an interest in this issue but cannot reproduce that crash. I did all in the **Issue description** contents but the crash never caused. Do you have any minimal reproduction project?

**Comment by kicknbrit** [comment]
I mean if it's not crashing for anyone else we can just close the issue. I'm kind've busy atm and I don't have time to put anything together. I would have to pull the scene out of a large project to create the mrp.

**Comment by AndreyKopylov** [comment]
same for me, crash when I tried add GPUParticles3D to character node
