### ISSUE TITLE
Mouse cursor disappears after adjusting environment preview sky light parameters

### ISSUE THREAD

**Issue by Clewless** [godotengine/godot#59174]
### Godot version

4.0 alpha 4 [f47097973]

### System information

Vulkan, Windows 11, Nvidia GTX 1060, intel i5 11400

### Issue description

After clicking the three dots on the top of the editor preview to adjust the properties of the sky light and adjusting the angular altitude or the azimuth with the sliders, the mouse cursor no longer displays while Godot is open
![Screenshot (6)](https://user-images.githubusercontent.com/20273340/158454922-d86d5e06-84c4-4835-aac3-9fc7728e03be.png)
.

### Steps to reproduce

In a new project, adjust the azimuth or angular altitude settings of the sun with the sliders from the drop down menu above the preview window.

**Comment by Calinou** [comment]
I remember seeing another issue reporting this already, but I can't find it right now.
