### ISSUE TITLE
Empty section when right-clicking multiple instances in scene tree

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#59196]
### Godot version

4.0 9d732aa / 3.x

### System information

Windows 10 x64

### Issue description

![image](https://user-images.githubusercontent.com/2223172/158611107-d2467dec-2644-4313-8c9d-b9049bac75e3.png)
This appears, because "Change Type" is not available for instances. One of the separators should be gone in this case.

### Steps to reproduce

1. Instance a couple of scenes
2. Select them (don't select non-instanced node)
3. Right-click the selection

**Comment by ebot102** [comment]
Hey there! I'm new to developing the project and would like to try and tackle this issue. Since it looks like the issue exists in multiple versions, would it be best to fix it in the 3.x version or the 4.0 version?

**Comment by KoBeWi** [comment]
It should be fixed in 4.0 first. The commit can then be cherry-picked.
