### ISSUE TITLE
Prettier print for array of Vector

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#5919]
```gdscript
var arr = [Vector2(1,2), Vector2(3,4)]
print(arr)
```

This prints ``[1,2, 3,4]``
It would be great if it prints ``[(1,2), (3,4)]``

**Comment by neikeq** [comment]
I guess the same applies to Vector3, right?

**Comment by volzhs** [comment]
@neikeq definitely :)

**Comment by bojidar-bg** [comment]
@alketii See what you've done! :smile:
