### ISSUE TITLE
[Godot 4.0] Error when loading a resource in alpha4 (works well with alpha3)

### ISSUE THREAD

**Issue by Chlipouni** [godotengine/godot#59206]
### Godot version

Godot_v4.0-alpha4_win64

### System information

Windows 10

### Issue description

My project works well with Godot_v4.0-alpha3_win64.

When I open it whith the official alpha4 build, I have the following errors :
`Godot Engine v4.0.alpha4.official (c) 2007-2022 Juan Linietsky, Ariel Manzur & Godot Contributors.
--- Debug adapter server started ---
--- GDScript language server started ---
  servers/rendering/renderer_rd/renderer_storage_rd.cpp:1026 - Condition "!tex" is true.
  No loader found for resource: res://.godot/imported/Frame.png-29d0f84feb7a1f1ccad084d133c86798.stex.
  Failed loading resource: res://images/Frame.png. Make sure resources have been imported by opening the project in the editor at least once.
  modules/gdscript/gdscript_analyzer.cpp:655 - Parser bug (please report): tried to assign unset node without an identifier.
  No loader found for resource: res://.godot/imported/Frame Accent.png-295b64d7751d05150b9723afc0444c03.stex.
  Failed loading resource: res://images/Frame Accent.png. Make sure resources have been imported by opening the project in the editor at least once.
  modules/gdscript/gdscript_analyzer.cpp:655 - Parser bug (please report): tried to assign unset node without an identifier.
  No loader found for resource: res://.godot/imported/Frame Mute.png-7e4cac43146192378e928285d2ca0caf.stex.
  Failed loading resource: res://images/Frame Mute.png. Make sure resources have been imported by opening the project in the editor at least once.
  modules/gdscript/gdscript_analyzer.cpp:655 - Parser bug (please report): tried to assign unset node without an identifier.
  No loader found for resource: res://.godot/imported/Frame Mute Accent.png-bf162d08f713f2d35bd89a049e7f030c.stex.
  Failed loading resource: res://images/Frame Mute Accent.png. Make sure resources have been imported by opening the project in the editor at least once.
  modules/gdscript/gdscript_analyzer.cpp:655 - Parser bug (please report): tried to assign unset node without an identifier.
  res://scripts/Chord.gd:15 - Parse Error: Could not preload resource file "res://images/Frame.png".
  res://scripts/Chord.gd:16 - Parse Error: Could not preload resource file "res://images/Frame Accent.png".
  res://scripts/Chord.gd:17 - Parse Error: Could not preload resource file "res://images/Frame Mute.png".
  res://scripts/Chord.gd:18 - Parse Error: Could not preload resource file "res://images/Frame Mute Accent.png".
  modules/gdscript/gdscript.cpp:874 - Method/function failed. Returning: ERR_PARSE_ERROR
  No loader found for resource: res://.godot/imported/Fretboard.png-e0d7ff4ce277515b30e01
  ...`

### Steps to reproduce

Juste open a scene that have this issue in alpha4.
Works well in alpha3.

### Minimal reproduction project

If necessary, I can prepare a minimal project with one scene that cause this issue.

**Comment by KoBeWi** [comment]
You need to delete the `.godot` directory (make sure the project is not opened when doing so). StreamTexture was renamed, so all imports are broken.

**Comment by Calinou** [comment]
This will be fixed in 4.0alpha5 by https://github.com/godotengine/godot/pull/58894.

**Comment by akien-mga** [comment]
I don't think so, that PR was included in alpha 4 AFAIR. A reimport is needed either way.
