### ISSUE TITLE
Standard color name returns non-standard color code.

### ISSUE THREAD

**Issue by hazarek** [godotengine/godot#59215]
### Godot version

3.4.3 stable

### System information

it does not matter

### Issue description

Standard color name (`brown`) returns non-standard color code. The standard brown color code is `#a52a2a` `Color.brown.to_html(false)` gives `#a62929`.  I just tried the brown. I haven't checked other color constants. I'm sure they are also problematic.

## 
```gdscript
extends Node

func _ready():
	var c := Color.brown.to_html(false) # -> a62929
	# Standard X11/HTML Brown -------------> a52a2a - rgb(165, 42, 42)
	print(c)
	#a62929
```

## Godot Documentation
https://docs.godotengine.org/en/latest/classes/class_color.html#color
> You can also create a color from standardized color names by using the string constructor or directly using the color constants defined here. The standardized color set is based on the [X11 color names](https://en.wikipedia.org/wiki/X11_color_names).

Additional resource;
https://www.w3.org/TR/css-color-3/#ref-X11COLORS

### Steps to reproduce

[gd.tumeo.space playground example](https://gd.tumeo.space/KYDwLsB2AmDOAEA5A9tYAodAzArpAxvAPoBOwAhtAJ4AUAlAFzoCQAbuSfIQwLzwDCyADbISAOgBGJZAHdIYsMiIALMAFshNLOSGxgdeAGJ4AWgB88cgDYATAE57LYwGUw5GB2jwAGgEZfAPQAEgAqALIAMvAAQtJypiaJScmJFuQArDbkWabwJADmEjS+VukANPAALDYV1XQsAA4kAJaQYDT49cyG1vb2QA)

### Minimal reproduction project

[gd.tumeo.space playground example](https://gd.tumeo.space/KYDwLsB2AmDOAEA5A9tYAodAzArpAxvAPoBOwAhtAJ4AUAlAFzoCQAbuSfIQwLzwDCyADbISAOgBGJZAHdIYsMiIALMAFshNLOSGxgdeAGJ4AWgB88cgDYATAE57LYwGUw5GB2jwAGgEZfAPQAEgAqALIAMvAAQtJypiaJScmJFuQArDbkWabwJADmEjS+VukANPAALDYV1XQsAA4kAJaQYDT49cyG1vb2QA)

**Comment by Calinou** [comment]
I can reproduce this on `master` fb2802578 as well.

**Comment by taigi100** [comment]
Just checked - I think this bug extends to many other colors, not only Brown. `ALICE_BLUE` and `ANTIQUE_WHITE` also seem a little bit off.
