### ISSUE TITLE
Post Request with SSL doesn’t work (mbedtls error)

### ISSUE THREAD

**Issue by NeroNekro** [godotengine/godot#59216]
### Godot version

3.4.3

### System information

MacOS 12

### Issue description

My App make some request to my server. The GET requests works fine and one POST request works too, but my last post request to upload a image in base64 doesn't work.

This error shows up in Xcode:
thirdparty/mbedtls/library/ssl_tls.c:3746: mbedtls_ssl_flush_output() returned -26752 (-0x6880)

I read a problem with lets encrypt and add the certificate from github/godot/thirdparty/certs to my project settings, but it doesn't help.

```gdscript
var query = http_client.query_string_from_dict( {"file": base_64, "format": img.get_format(), "privacy": accepted_privacy, "terms": accepted_term})
var headers = ["Content-Type: application/x-www-form-urlencoded", "Authorization: Bearer "+ connector.token]
print("Try HTTP Request")
$POSTRequest.connect("request_completed", self, "get_upload_status")
var result = $POSTRequest.request(connector.server_url + "upload", headers, connector.ssl, HTTPClient.METHOD_POST, query)
if result != 0:
    print("HTTP Error: " + str(result))

connector.ssl = True
connector.server_url = https://myserver.tld/somepath
```

On my Testsystem without SSL it works very well.

### Steps to reproduce

Make Post Request with a Base64 File

**Comment by Calinou** [comment]
```
thirdparty/mbedtls/library/ssl_tls.c:3746: mbedtls_ssl_flush_output() returned -26752 (-0x6880)
```

This refers to the `MBEDTLS_ERR_SSL_WANT_WRITE` error code: https://github.com/godotengine/godot/blob/master/thirdparty/mbedtls/include/mbedtls/ssl.h#L169

**Comment by NeroNekro** [comment]
> @NeroNekro Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.
> 
> ```
> thirdparty/mbedtls/library/ssl_tls.c:3746: mbedtls_ssl_flush_output() returned -26752 (-0x6880)
> ```
> 
> This refers to the `MBEDTLS_ERR_SSL_WANT_WRITE` error code:
> 
> https://github.com/godotengine/godot/blob/178961a6dc14155c0e65ec0040a2b2b328550317/thirdparty/mbedtls/include/mbedtls/ssl.h#L168-L169

I uploaded a test project on google drive.

[https://drive.google.com/file/d/1jftSIF-UyOX55_SNZOpL4-Cagkcc3uAW/view?usp=sharing](https://drive.google.com/file/d/1jftSIF-UyOX55_SNZOpL4-Cagkcc3uAW/view?usp=sharing)

I had configured a testserver or you change the link in connector.gd.

Server side code:
`
secure_token = "266d0c79shtsvjsfg7706f25db22d88effa139c01b7f19eea2edf3c6919ee2cf995976d17%="

def check_token(header):
    token = header.split()[1]
    if token == secure_token:
        return True
    else:
        return False

@cat_v1.route("/upload", methods=["POST"])
def upload_cat_image():
    if check_token(request.headers.get('Authorization')):
        image = request.form.get('file')
        filetype = request.form.get('format')
        terms = request.form.get('terms')
        privacy = request.form.get('privacy')
        filename = str(uuid.uuid4())
        with open("api/cat/uploaded_images/" + filename + ".png", "wb") as fh:
            fh.write(base64.b64decode(image))
        ImagesTMP.insert(filename=filename,
                         filenameBackup="",
                         extension=filetype).execute()
        return "{'status': 'yes'}"
    return "{'status': 'no'}"
`

**Comment by Calinou** [comment]
@NeroNekro Please surround large blocks of text with triple backticks like this:

\`\`\`
text here
\`\`\`

This prevents them from taking too much space and also makes sure issue references aren't accidentally created. I edited your comment, but remember to do this next time :slightly_smiling_face:

**Comment by NeroNekro** [comment]
> @NeroNekro Please surround large blocks of text with triple backticks like this:
> 
> ``` text here ```
> 
> This prevents them from taking too much space and also makes sure issue references aren't accidentally created. I edited your comment, but remember to do this next time 🙂

yes, of course. sorry for the circumstances.

A few more information:
The server side code is written with python-flask
I renewed all my certificates, but the same error.
On my browser I get the information that the certificate is valid and secure.

**Comment by NeroNekro** [comment]
This error message comes up, if the server not responding or something else. Server side fix was the solution. thanks for your help
