### ISSUE TITLE
Autocompletion for Mesh.PRIMITIVE_xxxx does not work in script editor

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#5922]
**Operating system or device - Godot version:**
2.0.x
2.1.rc1

**Issue description** (what happened, and what was expected):

``PRIMITIVE_xxxx`` constants do not appear into the autocompletion box when typing ``Mesh.PRIMITIVE_``.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by SuperUserNameMan** [comment]
Same goes with ``FixedMaterial.FLAG_xxx``.

On the other hand if I  ``var mat = FixedMAterial.new();``, then ``mat.FLAG_xxx``` works.

**Comment by bojidar-bg** [comment]
Can confirm with all classes' constants :smile:

**Comment by SuperUserNameMan** [comment]
well, with current HEAD it works. 
I think it can be closed.
