### ISSUE TITLE
The internal node is shown when OBJ is imported

### ISSUE THREAD

**Issue by fire** [godotengine/godot#59221]
### Godot version

178961a6dc14155c0e65ec0040a2b2b328550317 (closest estimate godot master version)

### System information

Fedora 35, Nvidia 3000 series

### Issue description

When importing OBJ as Scene, the file fail to import correctly.

### Steps to reproduce

1. download obj
2. Change obj import to type Scene
3. Open obj
4. Notice there's an extra ImporterMesh
5. Expect it to be the name of the obj and not the internal node.

### Minimal reproduction project

![image](https://user-images.githubusercontent.com/32321/158715745-d41f1e68-5b20-4496-a96c-f9d29bcb1748.png)
[OBJ Game Project.zip](https://github.com/godotengine/godot/files/8279000/OBJ.Game.Project.zip)

**Comment by akien-mga** [comment]
Still reproducible I guess?

![image](https://user-images.githubusercontent.com/4701338/221423104-19d7f474-2a8e-4e50-b6eb-f3a5d5e62374.png)

Also that rendering bug :|

**Comment by akien-mga** [comment]
Actually after deleting the `.godot` folder it seems fixed :)

![image](https://user-images.githubusercontent.com/4701338/221423544-a8220f6f-a5ec-4a04-bdd3-3610bbdfb891.png)
