### ISSUE TITLE
[GodotPhysics] Godot 4.0 hangs with multi-threaded 3D physics 

### ISSUE THREAD

**Issue by CheesecakeCG** [godotengine/godot#59220]
### Godot version

4.0 9d732aa0c

### System information

Arch Linux, KDE 5.24.3, Mesa 21.3.7, AMD Radeon RX 460, Kernel 5.16.14-zen1-1-zen

### Issue description

Godot freezes when "Run On Separate Thread" is enabled for 3D physics. And this is gets spammed in the terminal:
```
ERROR: Condition "p_elem->_root != this" is true.
   at: remove (./core/templates/self_list.h:80)
```

[Here is the full log.](https://github.com/godotengine/godot/files/8278174/log.txt)
This might be the same issue as #35017
 

### Steps to reproduce

1. Enable `physics/3d/run_on_separate_thread` 
2. Wait for Godot to freeze

**Comment by rburing** [comment]
The provided steps do not produce the error in 4.0 RC 3.
