### ISSUE TITLE
Vulkan: DirectionalLight3D PSSM 2 Splits exhibits shadow acne not present in other modes, and shadows are unstable

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#59232]
### Godot version

4.0 Alpha 4

### System information

Windows 11, Vulkan, Nvidia GTX 1050 Ti, 511.23

### Issue description

2 Split mode has severe Shadow Acne issues, unrelated to Shadow Resolution (both Orthogonal and 4 Split don't have Any issues in the same example) and the Shadows are unstable with 2 Splits (they jitter as the camera moves) again, unlike the other modes.

### Steps to reproduce

Switch Between Orthogonal or 4 Split Mode and 2 Split mode and Observe the differences

### Minimal reproduction project

[Bug.zip](https://github.com/godotengine/godot/files/8283451/Bug.zip)

**Comment by Calinou** [comment]
Shadow stabilization is performed here: https://github.com/godotengine/godot/blob/ae312b4fd2680e8609653f8a005bf1038aa6468a/servers/rendering/renderer_scene_cull.cpp#L2156-L2162

There doesn't appear to be a condition for the number of splits used. However, using PSSM with 2 splits will result in a non-square shadow map texture for each square (with the first split in the top half, and the second split in the bottom half).
