### ISSUE TITLE
Baking a Navmesh does not work at runtime

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#59235]
### Godot version

v3.5.beta2.official [7a4f9dfb1]

### System information

Mac OSX (Intel 2019)

### Issue description

Baking a Navmesh works in the editor but when calling `bake_navigation_mesh()` from the `_ready` function there is no change to the navigation mesh, and the `bake_finished` signal is never called.

Originally reported in https://github.com/godotengine/godot/issues/59218 but I will split it out here as this seems important.

### Steps to reproduce

1. Open the sample repository [godot-navigation-bug.zip](https://github.com/godotengine/godot/files/8283884/godot-navigation-bug.zip)
2. Run the game
3. You will see the stale navigation mesh and it does not update

<img width="600" alt="Screenshot 2022-03-17 at 13 14 42" src="https://user-images.githubusercontent.com/100964/158787516-4c38dfa1-6386-4ae1-9be1-70ef2caba6be.png">

### Minimal reproduction project

[godot-navigation-bug.zip](https://github.com/godotengine/godot/files/8283884/godot-navigation-bug.zip)

**Comment by Calinou** [comment]
When procedurally generating a level at load, you probably need to wait for 1-2 frames before baking the navmesh.

**Comment by tavurth** [comment]
Hmm, I tried with `get_tree().create_timer(1)` but it still wasn't building, perhaps something is wrong with my understanding of how to layout the scene?

<img width="306" alt="Screenshot 2022-03-17 at 20 19 08" src="https://user-images.githubusercontent.com/100964/158857724-ba0fef82-c752-4664-9ef0-51a73860deda.png">

**Comment by tavurth** [comment]
After looking through some of the code I realised that perhaps it was building, but just very slowly.

I spawned only two meshes instead of the 20 or 40 I was spawning before, and now the Navmesh does build but it takes around 20-30 seconds for 2 meshes.

This issue now seems to be related to https://github.com/godotengine/godot/issues/57148

@Calinou do you want me to close this one in favour of that?

**Comment by tavurth** [comment]
Closing, it should be fixed by this PR when it's reviewed:

https://github.com/godotengine/godot/pull/57411
