### ISSUE TITLE
[Godot 4] Change the editor profile make the dock file system blank

### ISSUE THREAD

**Issue by Dams4K** [godotengine/godot#59236]
### Godot version

4.0.dev

### System information

Ubuntu 20.04.4 LTS

### Issue description

When i change my editor profile, the dock file system become blank.

Before changing my profile:
![Capture d’écran de 2022-03-17 11-01-16](https://user-images.githubusercontent.com/82527785/158787758-6c2f270f-1e53-422c-928e-c27e96e9ea4e.png)

After:
![Capture d’écran de 2022-03-17 11-01-39](https://user-images.githubusercontent.com/82527785/158787705-cdd1999a-3614-4620-b38c-35d3403427e7.png)

If I float the dock and close it, it goes back to normal

### Steps to reproduce

Create new project, go to manage editor feature profiles then change profile, see what happened to the dock file system

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/58911.

**Comment by nathanfranke** [comment]
Fixed by https://github.com/godotengine/godot/pull/61435
