### ISSUE TITLE
Function return values are always zero/null/false in 4.0 release export

### ISSUE THREAD

**Issue by Byteron** [godotengine/godot#59239]
### Godot version

4.0 alpha 4

### System information

Windows 11, AMD CPU & GPU

### Issue description

When exporting to a release build, it appears that functions don't return the correct value.
![image](https://user-images.githubusercontent.com/24433899/158805644-c2f88dbf-9c86-4740-a9d0-b3ec024c121d.png)
![image](https://user-images.githubusercontent.com/24433899/158805726-6c283745-1fbe-4764-a39b-601101ddb8e0.png)

### Steps to reproduce

1) write function returning a non-default value
2) print called function (to some text label since release does not do console print)
3) export in release mode
4) see results

**Comment by Xwdit** [comment]
I have the same problem, waiting for a fix.....

**Comment by novaplusplus** [comment]
Re-posting my comment since I didn't realize the one I replied to was a duplicate -  I believe I've encountered this as well (windows and linux, my own build). Somehow I managed to make it work once, but never again.

**Comment by Xwdit** [comment]
> Re-posting my comment since I didn't realize the one I replied to was a duplicate - I believe I've encountered this as well (windows and linux, my own build). Somehow I managed to make it work once, but never again.

For now, as a temporary solution, we can use the release_debug build to avoid this problem, which usually works fine when you don't print anything you don't want the user to see. The binary size I compiled with msvc is only 2MB larger than the release version

**Comment by novaplusplus** [comment]
I'm in no hurry to release anything anyway, I have mostly been wanting to do it to do some performance comparisons of things I'm doing, but I can wait on that. Still, it's super baffling when running into this issue for the first time.

**Comment by souplamp** [comment]
Here's an MIP to test this.
[return.zip](https://github.com/godotengine/godot/files/8356693/return.zip)

My hunch is that _return_ is calling the object's constructor and returning that instead. It's always returning the right object type, just not the same value.

**Comment by akien-mga** [comment]
Another simple MRP from #62345:
```gdscript
extends Node

func _ready():
	print(get_true_hint())    # false
	print(get_true_nohint())  # null
	print(get_true_cast())    # 0

func get_true_hint() -> bool:
	return true

func get_true_nohint():
	return true

func get_true_cast() -> int:
	return int(true)
```
