### ISSUE TITLE
Save branch as scene on a control node also adds hidden nodes to the scene

### ISSUE THREAD

**Issue by kilojool** [godotengine/godot#59243]
### Godot version

4.0.alpha4.official

### System information

Windows 10

### Issue description

When using the Save Branch as Scene on a more complicated control node such as GraphEdit, the "hidden" nodes are also saved to the scene.
![Skärmklipp](https://user-images.githubusercontent.com/2656574/158834701-73189913-7698-41fd-8a1e-cffd7654cbf5.PNG)

### Steps to reproduce

Add any Control node which contains "hidden" nodes, such as a TabContainer or GraphEdit, and then right click and choose Save Branch as Scene on it or it's parent.

**Comment by KoBeWi** [comment]
Duplicate of #54960
