### ISSUE TITLE
Console spams `Vulkan: Early suboptimal swapchain.` when saving scene

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#59248]
### Godot version

v4.0.alpha.mono.custom_build [9d732aa0c]

### System information

manjaro KDE

### Issue description

Console keeps spamming:

```
Using present mode: VK_PRESENT_MODE_FIFO_KHR
Vulkan: Early suboptimal swapchain.
Vulkan: Swapchain is suboptimal.
Vulkan: Early suboptimal swapchain.
Vulkan: Swapchain is suboptimal.
Vulkan: Early suboptimal swapchain.
Vulkan: Swapchain is suboptimal.
Vulkan: Early suboptimal swapchain.
Vulkan: Swapchain is suboptimal.
Using present mode: VK_PRESENT_MODE_FIFO_KHR

```

and when not focused keeps saving the scene in a infinite loop:

https://user-images.githubusercontent.com/58845030/158879049-545dd151-f0fa-4e2d-b6d0-55d2988243ef.mp4

**IMPORTANT**
this only happens if you enable this option:

![image](https://user-images.githubusercontent.com/58845030/158879676-2dde5903-4a5d-496a-9c63-39bce25c09ec.png)

### Steps to reproduce

* Open a new project
* Enable the option mentioned above in editor settings
* go to another window

### Minimal reproduction project

N/a

**Comment by Calinou** [comment]
This issue is probably not related to the use of a Mono build.

**Comment by nonunknown** [comment]
yeah, I was talking with raulsntos, and for sure its not related!

**Comment by akien-mga** [comment]
I can reproduce this on Linux, when running in verbose mode (`settings/stdout/verbose`, also applies to the editor after restart).

This happens simply when pressing Ctrl+S to save a scene. A progress dialog window is shown and that's probably what is responsible for this error. Would be good to know if it happens on Windows/macOS or if it's Linux specific.

**Comment by akien-mga** [comment]
> and when not focused keeps saving the scene in a infinite loop:

If this still happens, I would suggest opening a new issue for it, as it's not related to the Vulkan error. It would be related to focus handling in the multiple windows.

**Comment by KoBeWi** [comment]
Does it still happen in alpha 7?

**Comment by nonunknown** [comment]
seems fixed!!!
