### ISSUE TITLE
[Godot 4] "files_dropped" signal doesn't work

### ISSUE THREAD

**Issue by kevinloustau** [godotengine/godot#59251]
### Godot version

v4.0.alpha.custom_build [e142c10fc]

### System information

Windows 11

### Issue description

Use the **files_dropped** signal to drag and drop file from os to godot app.

### Godot 3x
```rust
func _ready():
	get_tree().connect("files_dropped", self, "on_drop")

func on_drop(file, screen):
	print(file)
```

### Godot 4x
- Create a scene with a **Window** node.
- attach a new script.
- connect the **"files_dropped"** signal to the script.
- print the "files" arg from the signal function.
=> In my case, nothing is printed

### Minimal reproduction project

[DropFileTest.gd godot 3x.zip](https://github.com/godotengine/godot/files/8292652/DropFileTest.gd.godot.3x.zip)
[DropFileTest.gd godot 4x.zip](https://github.com/godotengine/godot/files/8292653/DropFileTest.gd.godot.4x.zip)

**Comment by KoBeWi** [comment]
Looks like #57442, except you are using a sub-window. This might be a limitation and it's possible the signal only works with main window or non-embedded windows.

**Comment by kevinloustau** [comment]
> Looks like #57442, except you are using a sub-window. This might be a limitation and it's possible the signal only works with main window or non-embedded windows.

You are right, it looks like https://github.com/godotengine/godot/issues/57442

I create a sub-window because I found the "files_drop" on this class only:
![img](https://i.ibb.co/2vkjnzc/Screenshot-2022-03-18-013904.jpg)

**Comment by KoBeWi** [comment]
Window is a root node of the scene tree, so you should use `get_tree().get_root().files_dropped` instead of `get_tree().files_dropped`.

**Comment by kevinloustau** [comment]
Working ! The correct current syntax is the following:
```rust
get_tree().root.files_dropped.connect(func(files, other): print(files))
```

**Comment by KoBeWi** [comment]
Looks like the signal has a wrong definition. It passes current screen as second argument, but it's not mentioned in the docs.

Also I did confirm that it only doesn't work with embedded sub-windows. If you do `get_viewport().gui_embed_subwindows = false`, any window will be able to receive files.
