### ISSUE TITLE
EditorPlugin can only add nodes to the Scene Root node

### ISSUE THREAD

**Issue by lexum0** [godotengine/godot#59253]
### Godot version

3.4.3, 3.4.4.rc2, 3.5 beta 2 

### System information

macOS

### Issue description

Using an EditorPlugin and duplicating a node or adding a new node only works on the nodes on the top level, right below the Scene Root node

If you use ```get_tree().get_edited_scene_root()``` as the parent node it will add the node you specify. Otherwise, it will only add the node if it's a child of the Scene Root. Adding to a deeper level in the hierarchy will fail to add the node

### Steps to reproduce

Open attached project, click a node, then click Duplicate and repeat with nodes at a different level

https://user-images.githubusercontent.com/2546522/158902144-6a8bc5f9-61e9-4a3e-9790-b721f6c4dcc0.mov

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/8292836/Test.zip)

**Comment by lexum0** [comment]
This code will show the problem when adding a new CSGBox instead of using duplicate, so the problem appears to be in the adding process
```# Duplicate manually
	var objParent = obj.get_parent()
	if obj is CSGBox and !(objParent is CSGCombiner):
		var box = CSGBox.new()
		box.width = obj.width
		box.height = obj.height
		box.depth = obj.depth
		box.material = obj.material
		box.material_override = obj.material_override
		box.transform = obj.transform
		
		addNode(box, objParent)

func addNode(node, parent):
	parent.add_child(node)
	node.set_owner(parent)
```

**Comment by KoBeWi** [comment]
Change `node.set_owner(parent)` to `node.set_owner(parent.owner)`
You didn't set the owner correctly, so the node doesn't show up in the scene tree (but it's added normally).

**Comment by lexum0** [comment]
@KoBeWi Is this specified in the docs or should it be added?

**Comment by KoBeWi** [comment]
I don't know tbh. The thing is that nodes only appear in the scene tree dock if their `owner` variable points to the scene root. I've seen a couple of issues opened by people confused by this. Not sure if we have it documented somewhere or where it should be documented.

**Comment by lexum0** [comment]
I just tested it and no matter what node I use as the parent, using ```parent.owner``` will correctly add it. I haven't found anything about it, I suggest adding this explanation or at least the solution to the ```.owner``` documentation. The only thing I was able to read about is that adding a node that you want to save must set the owner (which is still confusing) but didn't find anything about using the parent.owner property instead. I'd say and propose that instead this should be done either automatically by ```add_child()```, or via a parameter flag in ```add_child()```, where you just say what node to add it to similar to doing it in the editor. Having to deal with an invisible owner which we never do via the editor is confusing for doing a simple operation as adding a node

Thank you so much for the answer @KoBeWi, I spent (and wasted) a lot of time with this issue.

**Comment by KoBeWi** [comment]
@lexum0 
This is actually mentioned in `add_child()` description (see the note):
https://docs.godotengine.org/en/stable/classes/class_node.html#class-node-method-add-child
and in this tutorial:
https://docs.godotengine.org/en/stable/tutorials/plugins/running_code_in_the_editor.html#instancing-scenes

> I'd say and propose that instead this should be done either automatically by add_child(), or via a parameter flag in add_child(), where you just say what node to add it to similar to doing it in the editor.

You can open a proposal here: https://github.com/godotengine/godot-proposals

**Comment by Calinou** [comment]
There's already a proposal on the subject: https://github.com/godotengine/godot-proposals/issues/390

**Comment by lexum0** [comment]
> This is actually mentioned in `add_child()` description (see the note):
> https://docs.godotengine.org/en/stable/classes/class_node.html#class-node-method-add-child

It says: "```The node owner. A node can have any other node as owner (as long as it is a valid parent, grandparent, etc. ascending in the tree)```"

> and in this tutorial:
> https://docs.godotengine.org/en/stable/tutorials/plugins/running_code_in_the_editor.html#instancing-scenes

It says ```# Parent could be any node in the scene```

They never mention "call ```.owner```" for it to work

**Comment by Calinou** [comment]
> It says # Parent could be any node in the scene

> They never mention "call .owner" for it to work

The tutorial page says:

> Be sure to set the scene root as the owner of all the nodes created this way or the nodes won't be visible in the editor.

I guess this should be emphasized.

**Comment by lexum0** [comment]
> The tutorial page says:
> 
> > Be sure to set the scene root as the owner of all the nodes created this way or the nodes won't be visible in the editor.
> 
> I guess this should be emphasized.

Oh I get you, this is they key part, it's not the same what the tutorial says to the solution @KoBeWi provided. Setting the Scene Root as the owner only allows you to add nodes to the Scene Root, exactly the issue I described. Using the solution provided by @KoBeWi works with any node I give it as a parent
