### ISSUE TITLE
Vulkan: SpotLight3D + WorldEnvironment fog causes jaggedness due to clustering issues

### ISSUE THREAD

**Issue by 9HarshAgarwal** [godotengine/godot#59262]
### Godot version

4.0 Alpha 3

### System information

Windows 10, 3060

### Issue description

My Spotlight is at 500 Energy. 
![Screenshot 18-03-2022 12_03_58 PM](https://user-images.githubusercontent.com/28735504/158950481-45e9abf6-590d-4a17-8e44-0aa857938074.png)

### Steps to reproduce

WorldEnvironment Fog
Spotlight
Crank on the energy

**Comment by mrjustaguy** [comment]
these are clusters that fail to get the light applied, similar issue can be found with reflection probes..
