### ISSUE TITLE
sometimes editor freeze when CTRL+S a scene.

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#5927]
**Operating system or device - Godot version:**
2.1rc1 official win64 windows 8.1

**Issue description** (what happened, and what was expected):

Sometimes (it happened twice this local tonight), the editor freeze after a CTRL+S with the "Saving scene" toolbar at 100%.

Duno if related, but I was editing tool scripts.

This is the first project i'm working on seriously using 2.1, so can't say if it's a new behavior.

**Steps to reproduce:**

CTRL+S 

**Link to minimal example project** (optional but very welcome):

**Comment by SuperUserNameMan** [comment]
It never happened again since then.

**Comment by akien-mga** [comment]
I'd propose to close the issue then if it's not reproducible, as it would be hard to try to fix it without more debugging input.

**Comment by SuperUserNameMan** [comment]
Indeed.
I did not close it sooner by myself just in case some one would have confirmed this bug after I bumped it. But now, i think it's time to close it.
