### ISSUE TITLE
Adding a uniform in CanvasItemShader breaks rendering

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#5928]
Tested on Godot 2.1 rc1, Windows 10 64 bits

In order to fix my problem with [Polygon2D's transparency](https://github.com/godotengine/godot/issues/5151), I tried to write a shader that outputs alpha according to transparency. But I found again that adding any uniform in a CanvasItemShader produces the same bug as in https://github.com/godotengine/godot/issues/5877 (which was on 3D materials).

Note: surprisingly, it doesn't seems to affect Sprites.

Repro:
[CanvasShaderUniform.zip](https://github.com/godotengine/godot/files/385046/CanvasShaderUniform.zip)
Open the material on the Polygon2D, edit the shader. Uncomment the uniform.

I didn't managed to find a workaround to have a transparent Polygon2D :(

**Comment by bojidar-bg** [comment]
@akien-mga Given that this sounds like it breaks CanvasItem shaders completely, it might be required for 2.1 :smile: 

@Zylann What about CanvasItemShaderGraph-s, are they broken as well?

**Comment by Zylann** [comment]
@bojidar-bg I never used them, I still have to learn how they work but I prefer write code anyways.

**Comment by akien-mga** [comment]
@bojidar-bg Unless it's a regression from 2.0, I don't think it's blocking.

**Comment by akien-mga** [comment]
Assuming fixed in master as that code was rewritten for the new renderer. The issue might still affect 2.1.x though, but at this stage it's likely better that we focus rendering issues on 3.0+.
