### ISSUE TITLE
Editor: rotation of children is reset when container is refreshed

### ISSUE THREAD

**Issue by avnerh1** [godotengine/godot#59306]
### Godot version

3.4.2.stable

### System information

Windows 10, GLS3

### Issue description

I put TextureButtons inside GridContainer, and set the rotation for each of the buttons individually. 
Whenever the GridContainer is redrawn in the GUI editor (e.g. its size or location change), all rect_rotation values of the buttons in it return to 0 and therefore they are all displayed wrong.

### Steps to reproduce

As mentioned above

**Comment by KoBeWi** [comment]
This is intended, controls inside container are managed by the container and you can't change their position/size/rotation/scale. You even get this warning when trying to do so in the editor:
![image](https://user-images.githubusercontent.com/2223172/159121641-3bdf0672-9966-40df-9556-62277ed21af9.png)
In 3.4 it's possible to edit these properties from the inspector, but this should not be done and is blocked in 4.0.

**Comment by avnerh1** [comment]
@KoBeWi Thanks for your reply.
It's understood that the container should determine the position of its children, and also the size (if the control expands) but why change the rotation? Rotation is not part of positioning. 
A test case would be creating a button with the writing upside down and positioning it in a grid. There is no straight way to do it.

**Comment by KoBeWi** [comment]
> There is no straight way to do it.

You can put a Control in the container, put your rotating node as a child of that Control and set anchor preset to full rect. This way your rotating control will be properly sized, but will bypass container limitations.

There was once a proposal to allow disabling container sorting, but it was rejected:  https://github.com/godotengine/godot-proposals/issues/3123
