### ISSUE TITLE
AnimationTree blend position not  as expect

### ISSUE THREAD

**Issue by ywaby** [godotengine/godot#59304]
### Godot version

master

### System information

debian testing

### Issue description

blend animation in AnimationTree (xfade, add, blendspace, etc.) not work as expect

https://user-images.githubusercontent.com/12198203/159103660-1b03029b-a5e1-469e-8e96-cff9442fb89a.mp4

### Steps to reproduce

1. open project.
2. change blend value
3. see position change

### Minimal reproduction project

[animtree_blend_err.zip](https://github.com/godotengine/godot/files/8308464/animtree_blend_err.zip)

**Comment by TokageItLab** [comment]
@ywaby Which commit hash did you use? I think most of blend bug has been removed latest master, please test it.

**Comment by ywaby** [comment]
OK, It's fixed.
