### ISSUE TITLE
Godot Crashes when exporting to Linux and Windows

### ISSUE THREAD

**Issue by sairam4123** [godotengine/godot#59307]
### Godot version

3.5beta2

### System information

Windows 10, Nvidia GeForce GTX 1050, 27.21.14.5771

### Issue description

Godot crashes whenever I try to export to Windows or Linux, it seems to crash after the export has been completed.
Here's a video showcasing it: [Video](https://www.youtube.com/watch?v=_UPX7PpU-JM)

### Steps to reproduce

1. Download my game project from the link given below.
2. Export the project for Windows, Mac and Linux.
3. Observe Godot crashing for Windows and Linux and not for Mac.

### Minimal reproduction project

[Project is available here.](https://github.com/OpenSkyCity/Godot-Road-Builder-3D/commit/26b7d5c46a1458c0fe17fec548a0ad2d8695107c)

**Comment by sairam4123** [comment]
For anyone who stumble upon this message:
![image](https://user-images.githubusercontent.com/61322406/159110801-a36e3702-701d-4676-aab4-485ca8c38a19.png)
Restarting the project should fix it.

**Comment by sairam4123** [comment]
Exported build is crashing too. I just tried it out. I have uploaded it in the [itch.io](https://sairam4123.itch.io/roadsystemtest-openskycity).

**Comment by sairam4123** [comment]
FYI: I couldn't reproduce the issue in an empty project. I have updated the working exported executables in my project's releases area. [Build](https://github.com/OpenSkyCity/Godot-Road-Builder-3D/releases)

**Comment by Thorben-Denzer** [comment]
I can confirm that the issue does not exist in version 3.4.2.

**Comment by NameKhan72** [comment]
I can confirm that the issue does not happen when using version 3.4.2

**Comment by sairam4123** [comment]
3.5beta1 works, so it's a regression!

**Comment by INdIEDeV016** [comment]
Have you checked any logs that are generated due to crash?

**Comment by sairam4123** [comment]
> Have you checked any logs that are generated due to crash?

I couldn't find any. Could you guide me to find them?

**Comment by INdIEDeV016** [comment]
> > Have you checked any logs that are generated due to crash?
> 
> I couldn't find any. Could you guide me to find them?

It's found here (see image). Check the `logs` folder in that directory
![image](https://user-images.githubusercontent.com/80198819/160238866-a0ac5965-a01d-479f-b6ac-dcb179a43b53.png)
