### ISSUE TITLE
Using INV_PROJECTION_MATRIX in gdshader causes editor to 100% cpu and hang on or after compilation.

### ISSUE THREAD

**Issue by danger-dan** [godotengine/godot#59302]
### Godot version

4.0 dev 35eec4d

### System information

popOS! (Ubuntu), RTX2060, Vulkan

### Issue description

Editor uses 100% cpu and hangs on compilation of a shader. This happens as soon as the builtin INV_PROJECTION_MATRIX is added to the code. The only useful logs i could get which may or may not be related is:

   at: _compile_variant (servers/rendering/renderer_rd/shader_rd.cpp:280)
ERROR: Error compiling Fragment shader, variant #7 (
#define MODE_MULTIPLE_RENDER_TARGETS
).
   at: _compile_variant (servers/rendering/renderer_rd/shader_rd.cpp:276)
ERROR: Failed parse:
WARNING: 0:72: '' : all default precisions are highp; use precision statements to quiet warning, e.g.:
         "precision mediump int; precision highp float;" 
ERROR: 0:2054: 'inv_projection_matrix' : undeclared identifier 
ERROR: 0:2054: '' : compilation terminated 
ERROR: 2 compilation errors.  No code generated.

   at: _compile_variant (servers/rendering/renderer_rd/shader_rd.cpp:277)
ERROR: code:

### Steps to reproduce

create new project, add new shader resource and start writing - using INV_PROJECTION_MATRIX.

tested with:

void fragment(){
	float depth = texture(DEPTH_TEXTURE, SCREEN_UV).x;
	vec3 ndc = vec3(SCREEN_UV * 2.0 - 1.0, depth);
	vec4 view = INV_PROJECTION_MATRIX * vec4(ndc, 1.0);
}

**Comment by clayjohn** [comment]
Looks like we need to do something like this in the fragment shader
https://github.com/godotengine/godot/blob/35eec4de40ed25eeb4423fcd6ae65936db9961ec/servers/rendering/renderer_rd/shaders/scene_forward_clustered.glsl#L263-L264

``INV_PROJECTION_MATRIX`` is renamed to ``inv_projection_matrix`` by Godot's shader compiler. But the fragment shader only has access to ``scene_data.inv_projection_matrix`` so we need to define ``inv_projection_matrix`` somewhere above the user's fragment shader code.
