### ISSUE TITLE
Import script problem

### ISSUE THREAD

**Issue by pkowal1982** [godotengine/godot#5931]
**Operating system or device - Godot version:**
Ubuntu 14.04 / Win7 64b, Godot_v2.1_rc1

**Issue description** (what happened, and what was expected):
Minimal import script taken from docs gives error on import.

**Steps to reproduce:**
Copy script from docs to file, try to import any scene with post-import script set.

**Link to minimal example project** (optional but very welcome):
Example project in attachment.
[import_scrtipt_bug.zip](https://github.com/godotengine/godot/files/386007/import_scrtipt_bug.zip)

**Comment by vnen** [comment]
This is an issue with the documentation, you have to `return scene` at the end of the function.

**Comment by pkowal1982** [comment]
OK, created PR on docs:
https://github.com/godotengine/godot-docs/pull/213

**Comment by akien-mga** [comment]
Thanks, fixed by https://github.com/godotengine/godot-docs/pull/213 then.
