### ISSUE TITLE
Cannot start Godot 4  - undefined symbol: snd_dlpath

### ISSUE THREAD

**Issue by ManyHatsOfLinux** [godotengine/godot#59318]
### Godot version

Godot 4 Alpha 4 

### System information

Ubuntu 20.04.4 LTS

### Issue description

Godot 3 loads just fine, any attempt to run Godot alpha 3 or alpha 4 results in this. 
What sticks out to me is this line, /lib/x86_64-linux-gnu/libasound.so.2: undefined symbol: snd_dlpath

Might I be missing a library of some kind?

Godot Engine v4.0.alpha3.official.256069eaf - https://godotengine.org
Vulkan API 1.2.131 - Using Vulkan Device #0: AMD - AMD RADV POLARIS10
/lib/x86_64-linux-gnu/libasound.so.2: undefined symbol: snd_dlpath
 
ERROR: Stream texture file is corrupt (Bad header).
   at: _load_data (scene/resources/texture.cpp:478)
ERROR: Failed loading resource: res://.import/GuiScrollArrowRight.svg-623ebef1a4a29bb0f062b30ad2f110bb.stex. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:205)
ERROR: Failed loading resource: res://theme/GuiScrollArrowRight.svg. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:205)
ERROR: res://browser/main.tscn:4 - Parse Error: [ext_resource] referenced nonexistent resource at: res://theme/GuiScrollArrowRight.svg
   at: load (scene/resources/resource_format_text.cpp:467)
ERROR: Failed loading resource: res://browser/main.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:205)
ERROR: Failed loading scene: res://browser/main.tscn
   at: start (main/main.cpp:2509)
ERROR: 1 RID allocations of type 'P11GodotBody3D' were leaked at exit.
ERROR: 1 RID allocations of type 'P11GodotArea3D' were leaked at exit.
ERROR: 1 RID allocations of type 'P12GodotSpace3D' were leaked at exit.
ERROR: 1 RID allocations of type 'P11GodotArea2D' were leaked at exit.
ERROR: 1 RID allocations of type 'P12GodotSpace2D' were leaked at exit.
ERROR: 2 RID allocations of type '6NavMap' were leaked at exit.
ERROR: 2 RID allocations of type 'N21RendererSceneRenderRD11ShadowAtlasE' were leaked at exit.
ERROR: 1 RID allocations of type 'N21RendererSceneRenderRD15ReflectionAtlasE' were leaked at exit.
ERROR: 1 RID allocations of type 'N17RendererStorageRD12RenderTargetE' were leaked at exit.
ERROR: 2 RID allocations of type 'N17RendererStorageRD7TextureE' were leaked at exit.
ERROR: 1 RID allocations of type 'N18RendererCanvasCull6CanvasE' were leaked at exit.
ERROR: 1 RID allocations of type 'N16RendererViewport8ViewportE' were leaked at exit.
ERROR: 1 RID allocations of type 'N17RendererSceneCull8ScenarioE' were leaked at exit.
WARNING: 3 RIDs of type "StorageBuffer" were leaked.
     at: _free_rids (drivers/vulkan/rendering_device_vulkan.cpp:8956)
WARNING: 1 RID of type "UniformBuffer" was leaked.
     at: _free_rids (drivers/vulkan/rendering_device_vulkan.cpp:8954)
WARNING: 1 RID of type "Framebuffer" was leaked.
     at: _free_rids (drivers/vulkan/rendering_device_vulkan.cpp:8954)
WARNING: 4 RIDs of type "Texture" were leaked.
     at: finalize (drivers/vulkan/rendering_device_vulkan.cpp:9260)
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: cleanup (core/object/object.cpp:2020)

### Steps to reproduce

In Terminal, execute ./Godot_v4.0-alpha3_linux.64

**Comment by ManyHatsOfLinux** [comment]
42:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] [1002:67df] (rev e7)
	Subsystem: XFX Pine Group Inc. Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] [1682:c580]
	Kernel driver in use: amdgpu
	Kernel modules: amdgpu
42:00.1 Audio device [0403]: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere HDMI Audio [Radeon RX 470/480 / 570/580/590] [1002:aaf0]
	Subsystem: XFX Pine Group Inc. Ellesmere HDMI Audio [Radeon RX 470/480 / 570/580/590] [1682:aaf0]
	Kernel driver in use: snd_hda_intel
	Kernel modules: snd_hda_intel

**Comment by Calinou** [comment]
You need to remove the `.godot/` folder within your project while the editor is closed, then try to open the editor again.

**Comment by akien-mga** [comment]
This is actually not about `.godot/` but about the `.import/` folder from a 3.x project:

```
ERROR: Stream texture file is corrupt (Bad header).
at: _load_data (scene/resources/texture.cpp:478)
ERROR: Failed loading resource: res://.import/GuiScrollArrowRight.svg-623ebef1a4a29bb0f062b30ad2f110bb.stex. Make sure resources have been imported by opening the project in the editor at least once.
at: _load (core/io/resource_loader.cpp:205)
```

It should be deleted.

**Comment by Calinou** [comment]
Should Godot 4 ignore the `.import/` folder to avoid this kind of issue?

**Comment by akien-mga** [comment]
Sure, but I'm not sure how easy it would be to implement (while forcing a reimport and reset of the referenced imported files in `.import` files, as it happens when the `.import/` folder is missing).

**Comment by Calinou** [comment]
Do you have a `project.godot` file within your home folder? If so, this will cause _all_ files within your home folder to be imported as resources. This is why you should _not_ create a project right in your home folder, and always put it in a subfolder instead (I recommend `$HOME/Documents/Godot/`).

**Comment by ManyHatsOfLinux** [comment]
You are right Calinou, I will keep this in mind going forward. I will start storing projects outside of Home Folder. I appreciate the advise.

**Comment by XsongyangX** [comment]
Hello, I am experiencing this issue on WSL 2. Godot starts despite this error message.

```
[21:32:39] song@DESKTOP-CBDKVRK:~/installations/Godot_v3.5.1-stable_mono_x11_64$ ./Godot_v3.5.1-stable_mono_x11.64
Godot Engine v3.5.1.stable.mono.official.6fed1ffa3 - https://godotengine.org

================================================================

================================================================
OpenGL ES 3.0 Renderer: D3D12 (NVIDIA GeForce RTX 3070 Laptop GPU)
Async. shader compilation: OFF
/lib/x86_64-linux-gnu/libasound.so.2: undefined symbol: snd_dlpath

Mono: Log file is: '/home/song/.local/share/godot/mono/mono_logs/2022-10-29_21.32.41_4577.log'
```
