### ISSUE TITLE
AnimationTree doesn't work in 3.5.beta2

### ISSUE THREAD

**Issue by rambda** [godotengine/godot#59317]
### Godot version

3.5.beta2

### System information

Windows 10, GLES3

### Issue description

AnimationTree doesn't work in 3.5.beta2, but works in 3.5.beta1.

Click play in any AnimationNodeAnimation in a AnimationNodeStateMachine in bottom panel gives no response,
AnimationNodeBlendTree doesn't work too.
If use AnimationNodeStateMachinePlayback,
```
playback.get_travel_path() == []
playback.get_current_node() == ""
playback.is_playing() == False
```

### Steps to reproduce

See reproduction project.

### Minimal reproduction project

[AnimationTreeBug.zip](https://github.com/godotengine/godot/files/8309443/AnimationTreeBug.zip)

**Comment by timothyqiu** [comment]
AnimationTree in the MRP works the same for me on 3.5.beta1, 3.5.beta2, and current 3.x.

Do you have any detail instructions?

**Comment by akien-mga** [comment]
The attached project also works the same for me in 3.4.4.stable, 3.5.beta1, 3.5.beta2, and latest `3.x`.

No answer from OP, so assuming this was not a bug.
