### ISSUE TITLE
Unable to load float=32 created binary resource  on float=64

### ISSUE THREAD

**Issue by fire** [godotengine/godot#59320]
### Godot version

db5271dd34ea2b1894e1e2cf9ee9519c84142608 (closest)

### System information

Fedora 35, Nvidia 3000 series

### Issue description

Godot cannot load scn in float=64 when they're from float=32. Errors for Vector\<Vector2>, Vector\<Vector3>, Vector\<Color>.

`Vector2 size is NOT 8!"`

```c++
	case VARIANT_PACKED_VECTOR2_ARRAY: {
			uint32_t len = f->get_32();

			Vector<Vector2> array;
			array.resize(len);
			Vector2 *w = array.ptrw();
			if (sizeof(Vector2) == 8) {
				f->get_buffer((uint8_t *)w, len * sizeof(real_t) * 2);
#ifdef BIG_ENDIAN_ENABLED
				{
					uint32_t *ptr = (uint32_t *)w.ptr();
					for (int i = 0; i < len * 2; i++) {
						ptr[i] = BSWAP32(ptr[i]);
					}
				}

#endif

			} else {
				ERR_FAIL_V_MSG(ERR_UNAVAILABLE, "Vector2 size is NOT 8!");
			}

			r_v = array;

		} break;
```

### Steps to reproduce

Builds of godot with float=64 fail to load binary serialized PackedScene defined as float=32.

1. create a resource with these types in godot float=32
2. open in float=64
3. See variant error

### Minimal reproduction project

[Double Import Game Project.zip](https://github.com/godotengine/godot/files/8310434/Double.Import.Game.Project.zip)

**Comment by Zylann** [comment]
It may have to check for `FileAccess::real_is_double` instead

**Comment by Zylann** [comment]
@fire can you try with #59324

**Comment by fire** [comment]
Testing.
