### ISSUE TITLE
Input Map UI issue: action and the add button is half hidden

### ISSUE THREAD

**Issue by teki** [godotengine/godot#5932]
**Operating system or device - Godot version:**

OS X 10.11.6, godot 2.1 RC1
13" Retina mac

**Issue description** (what happened, and what was expected):

Entry of new action is half hidden.

**Steps to reproduce:**

- open Project Settings/Input Map
- try to enter a new action

**Link to minimal example project** (optional but very welcome):

Screen shot:
<img width="1323" alt="screen shot 2016-07-27 at 11 01 37 pm" src="https://cloud.githubusercontent.com/assets/5516/17176041/2393ecd6-544e-11e6-8b6a-35d26f784947.png">

**Comment by akien-mga** [comment]
Probably an issue for Retina / hidpi, i.e. one of the components doesn't take into account the editor scaling as it should.
