### ISSUE TITLE
Raycast2D get_collision_point() uses local coordinates when hitting a shape from inside

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#59335]
### Godot version

4.0.alpha3

### System information

Ubuntu 20.04.3 LTS

### Issue description

In RayCast2D, get_collision_point() is supposed to use global coordinates, but in the specific case where Hit From Inside is enabled and the collision happens from inside, the function returns the local coordinates from the shape's origin. The docs claim the coordinates must always be global. This is wildly inconsistent, so I wouldn't call it a documentation error.

### Steps to reproduce

For example:
- Create a 2D scene and add RayCast2D and CharacterBody2D with a rectangle CollisionShape2D
- Move them far from the origin to see the issue clearly.
- In RayCast2D, enable "Hit From Inside"
- Attach a script to the Node2D and print $RayCast2D.get_collision_point() in process
- Try starting the project with the raycast starting inside the shape and outiside of it. Compare the results.

### Minimal reproduction project

[Raycast bug.zip](https://github.com/godotengine/godot/files/8310354/Raycast.bug.zip)

**Comment by rburing** [comment]
Confirmed, and the same issue is present in 3D.
