### ISSUE TITLE
Export doesn't display any status

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#59333]
### Godot version

81c2d7a

### System information

Windows 10 x64

### Issue description

Exporting a project looks like this right now:
![godot windows tools 64_qllZqsf5R9](https://user-images.githubusercontent.com/2223172/159142048-ebee601e-60a1-41a5-a3c9-2b2b214c6391.gif)
The export dialog simply freezes and then unfreezes when export finishes. No progress, no status. You don't even know if the export succeeded or anything has happened if you don't look into the output tab.

### Steps to reproduce

1. Export project

**Comment by Dan-Gamin** [comment]
When exporting to android its even worse because the entire screen goes black while its exporting.

**Comment by KoBeWi** [comment]
Seems fixed in c50febf
