### ISSUE TITLE
Save/Load cubemap .tres format problem

### ISSUE THREAD

**Issue by pkowal1982** [godotengine/godot#5933]
**Operating system or device - Godot version:**
Win7 64b, Godot_v2.1_rc1

**Issue description** (what happened, and what was expected):
Can't load cubemap saved in .tres format.

**Steps to reproduce:**
Create new project and then create new cubemap.
Set all sides to some file, it can be default Godot icon.
Save cubemap in suggested .tres format.
Close editor then open it once again.
Open previously saved cubemap and look at the files list: only left file is non empty,
probably something is messed up on cubemap export.

**Link to minimal example project** (optional but very welcome):
[cubemap_bug.zip](https://github.com/godotengine/godot/files/386146/cubemap_bug.zip)

**Comment by reduz** [comment]
just do not save the cubemaps in tres format, use binary or the .cube extension like in the demos
in any case, it should eventually load, so will check

**Comment by akien-mga** [comment]
Cubemaps are no longer supported in 3.0, so "fixed" :)
