### ISSUE TITLE
Cubemap TSCN/TRES

### ISSUE THREAD

**Issue by Elinvention** [godotengine/godot#5934]
**Operating system or device - Godot version:**

Debian Testing, mesa 12.0.1, godot 2.1.rc1.custom_build

**Issue description** (what happened, and what was expected):

Cubemaps are broken if saved as a sub-resource in a TSCN scene or as TRES resources. Looking at the very heavy generated file, it seems Godot saves the textures inside the file in text format, instead of simply referencing them! When playing the scene there is no sky. If you save the same scene as SCN or the resource as CBM there is no problem.

**Steps to reproduce:**

Add a world environment to a TSCN scene, new environment, set mode to cubemap, new cubemap, edit the cubemap adding the 6 required textures such as http://opengameart.org/content/sky-box-sunny-day/, save the scene, the saved .tscn file weights a lot of MBs! Run the scene and there is no sky...

**Comment by bojidar-bg** [comment]
Related to #4240

**Comment by bojidar-bg** [comment]
Is this still valid on master/3.0?

**Comment by Elinvention** [comment]
Now it works as expected, thanks! By the way, is it possible to convert an old project to Godot 3.0?

**Comment by bojidar-bg** [comment]
@Elinvention Yeah, don't worry, it would be an exporter in 2.1.3/2.1.4 (2.1.3 WIP preview, 2.1.4 final, I guess)
