### ISSUE TITLE
glTF files don't import properly if Use FBX is enabled in Project Settings

### ISSUE THREAD

**Issue by Rodeo-McCabe** [godotengine/godot#59356]
### Godot version

4.0 alpha 4

### System information

Linux

### Issue description

By default, the option Project Settings > filesystem/import/fbx/use_fbx is enabled. Add a .gltf or .glb file to the project. The editor will hang until it loses focus and is refocused, then the file will be imported ... however after importing the files can't be opened and the editor says it is corrupt.

Disabling the Use FBX option solves all that.

### Steps to reproduce

Simply add a glTF file and attempt to open it. Then disable the Use FBX option and reimport it to see that it works now.

### Minimal reproduction project

Will provide if necessary. A glTF is all that's needed.

**Comment by Calinou** [comment]
Is the Use FBX project setting still needed in 4.0? We should probably remove it unless there's a good reason to keep it.

cc @RevoluPowered

**Comment by fire** [comment]
Should be removed in master. https://github.com/godotengine/godot/pull/59691

**Comment by akien-mga** [comment]
That's pretty weird, I don't know why the FBX importer would impact glTF imports. But indeed, it's removed with #59691 so this is likely fixed.
