### ISSUE TITLE
Replace all produce crash

### ISSUE THREAD

**Issue by larvasapiens** [godotengine/godot#5935]
S.O: Arch Linux 64 bits
Godot Version: v2.1_beta_20160712_x11.64 and Godot_v2.1_rc1_x11

Issue Description: Godot crashes when using "Replace All" for a character that has only one instance in the script.
Steps to reproduce:
  1 - Select a character you want to replace. I tested with '+' and '-'. Make sure your character is only once in the script. In my case, the only '+' instance I have is in this line:  aux.set_translation(get_translation()+Vector3(aux.direccion.x,1,aux.direccion.z))
  2 - In the Replace bar (Ctrl + r), write your desired character and the string you want to replace it. In my case, that would be '+' and ' + '.
  3 - Press "Replace All" (Just "Replace" won't produce a crash)

Note: This bug is nor present in Godot_v2.0.3_stable_x11.64

**Comment by neikeq** [comment]
I cannot recreate it. An example script could be of help (or a backtrace).

**Comment by bojidar-bg** [comment]
@larvasapiens Are you replacing with the same string as the original?

**Comment by neikeq** [comment]
@bojidar-bg I couldn't recreate it that way either. That should work fine.

**Comment by larvasapiens** [comment]
Sure, here is a sample script:

 ```
extends Sprite3D

func _ready():
	var a=1+2

```

Replace '+' with ' + ' (space, plus, space).

**Comment by djrm** [comment]
i can reproduce on fedora using the example code

**Comment by batmanasb** [comment]
I can reproduce on Linux Mint using Godot 2.1-RC1 with the sample sample script

**Comment by djrm** [comment]
this only happens when using replace all and only one character will be replaced

**Comment by neikeq** [comment]
Ok, I see why it is happening. Gonna fix it tomorrow.
