### ISSUE TITLE
Main font size, code font size and line spacing editor settings no longer apply without restarting the editor

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#59365]
### Godot version

4.0.alpha (21466daf4)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 495.46)

### Issue description

The main font size, code font size and line spacing editor settings no longer apply without restarting the editor.

This does not occur in Godot 3.4.3 or in earlier 4.0 alphas. In those versions, changing those settings applies after waiting 1-2 seconds.

This may be related to recent font handling changes. cc @bruvzg 

### Steps to reproduce

- Create a new script to see changes made to the code font size and line spacing, then switch to the Script tab to view the script.
- Open **Editor > Editor Settings…**.
- Change **Interface > Editor > Main Font Size**, **Interface > Editor > Code Font Size** and **Whitespace > Line Spacing**.
- Observe that changes don't apply until you quit and restart the editor.

### Minimal reproduction project

N/A

**Comment by bruvzg** [comment]
Probably caused by #53839 - which limits, reloading of the editor theme to the `interface/theme` and `text_editor/theme` (fonts are in `interface/editor`, along with the other settings).
