### ISSUE TITLE
AnimationNodeBlendTree cannot be set up programmatically.

### ISSUE THREAD

**Issue by KnightNine** [godotengine/godot#59378]
### Godot version

3.4.2-stable

### System information

Windows 10

### Issue description

I want to set up an `AnimationNodeBlendTree` programmatically so I don't have to set it up via the editor for every scene that uses this animation tree script, but this seems to be impossible.
The `AnimationNodeOutput` isn't included, so I create and add an output node in the script below, but whatever I connect to this output node does nothing. 
I assume there must be a property that assigns the output node to the `AnimationNodeBlendTree` but I can't find anything after looking through the property lists of the `output_node` and the `AnimationTree` with `get_property_list()`.

I don't think this to be intended as there's then no purpose for being able to create new `AnimationNodeBlendTree`s via GDScript.

There's nothing about this in https://docs.godotengine.org/en/stable/classes/class_animationnodeblendtree.html
nor in https://docs.godotengine.org/en/stable/classes/class_animationnodeoutput.html

### Steps to reproduce

This is the test script within my AnimationTree, 
(assign an AnimatonPlayer with an animation named "Idle" to this AnimationTree)
I'll likely include a minimal reproduction project tomorrow if there's no solution by then.

This code should run the "Idle" animation but does nothing, and it runs without error:
```gdscript
func _init():
	
	
	
	#setup blend tree
	tree_root = AnimationNodeBlendTree.new()
	
	#add output node
	var output_node = AnimationNodeOutput.new()
	tree_root.add_node("Output", output_node)
	
	#plug in animation node 
	var animation_node = AnimationNodeAnimation.new()
	animation_node.animation = "Idle"
	tree_root.add_node("Anim", animation_node)
	
	#connect Transition node to output
	tree_root.connect_node ( "Output", 0, "Anim" )
	
	active = true
```

**Comment by timothyqiu** [comment]
The output node exists, its name is `output`, not capitalized. Also don't forget to set `active` to `true` after everything is set up.

**Comment by KnightNine** [comment]
> ```gdscript
> add_node("Output", output_node)
> ```

Oh, I thought it (the output node's default name) was capitalized since the node's name is capitalized in the editor:
![Capture](https://user-images.githubusercontent.com/34152090/159236175-a04e171e-f14c-4285-a973-addb7875cc3e.PNG)




I'll remove the BONUS BUG add `active = true` to the end of the sample functions.

**Comment by KnightNine** [comment]
The solution for my issue is that the output_node/`AnimationNodeOutput` **MUST** be named "output" to function.

so this works now:
```gdscript
#setup blend tree
	tree_root = AnimationNodeBlendTree.new()
	
	#add output node
	var output_node = AnimationNodeOutput.new()
	tree_root.add_node("output", output_node)
	
	#plug in animation node 
	var animation_node = AnimationNodeAnimation.new()
	animation_node.animation = "Idle"
	tree_root.add_node("Anim", animation_node)
	
	#connect Transition node to output
	tree_root.connect_node ( "output", 0, "Anim" )
	
	active = true

```

**Comment by timothyqiu** [comment]
@KnightNine You don't have to call `add_node`, it exists by default, like in the editor.

**Comment by KnightNine** [comment]
so the only real issue is that:
-"the output node is named "output" but is shown as "Output" in the editor." (instead of being documentation the display name should probably just be "output")
and this info should be added to the docs as it might not be obvious when creating a new `AnimationNodeBlendTree` via script:
-"the output node exists by default in the `AnimationNodeBlendTree`."
