### ISSUE TITLE
Custom classes only work at the root of a project 

### ISSUE THREAD

**Issue by TheLastStudio** [godotengine/godot#59380]
### Godot version

v4.0.alpha4.official.f47097973

### System information

Windows 10, Vulkan Clustered, NVIDIA GeForce GTX 1050

### Issue description

If I want to create a new class_name, I must place it in the res:// directory. If I place it in some folder res://new_dir, when I click "create a new node", I won't see mine there.

### Steps to reproduce

Create script in res://new_dir/test1.gd
```
extends Node
class_name Test1
```
Create script in res://test2.gd
```
extends Node
class_name Test2
```
Press "+" button (create new node)
Test2 will be in the list, but Test1 not.

**Comment by KoBeWi** [comment]
Can't reproduce, can you attach a minimal project?
