### ISSUE TITLE
Viewport result is 8% too small

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#59397]
### Godot version

v3.5.beta2.official [7a4f9dfb1]

### System information

Mac OSX (Intel 2019)

### Issue description

When rendering a viewport, the resulting image is 8% too small.

### Steps to reproduce

1. Render an image with defined borders to a viewport
2. Render resulting viewport texture
3. Render the original texture side-by-side

Note the differences:
<img width="1552" alt="Screenshot 2022-03-22 at 00 15 51" src="https://user-images.githubusercontent.com/100964/159365094-4ee81ebc-a79a-458b-8f84-7c86aba6349d.png">

When I move the slider to `1.08` (i.e. `108%` the texture repeats properly)

<img width="1552" alt="Screenshot 2022-03-22 at 00 16 21" src="https://user-images.githubusercontent.com/100964/159365184-5ac0d297-d66c-4f2e-8b33-e0f0ba19f912.png">

### Minimal reproduction project

[godot-viewport-bug.zip](https://github.com/godotengine/godot/files/8319295/godot-viewport-bug.zip)

**Comment by tavurth** [comment]
Workaround: 

Scale your Viewports UV coordinates by `108%`

**Comment by kleonc** [comment]
@tavurth No bug in here, that's what you're rendering inside that `Viewport` (the `TextureRect` inside it is stretched):
![Godot_v3 4 3-stable_win64_VuU9EUNL9v](https://user-images.githubusercontent.com/9283098/159386233-6ccc7a52-2c6b-4a9d-a312-8ecb1d5c500c.png)

**Comment by tavurth** [comment]
Hmm, interesting. Thank you for double checking @kleonc!

I was trying to recreate a bug in my game, and this seemed to be it. ok I will try to find the issue again.
