### ISSUE TITLE
Blender-style transform shortcuts do not disable "use local space" mode on activation

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#59392]
### Godot version

4.0 alpha 3

### System information

linux

### Issue description

If the "use local space" option is enabled when using a blender-style transform shortcut, the transformation will not follow the mouse.

https://user-images.githubusercontent.com/71937306/159298382-5a5c0955-bab2-48ba-a2df-a0ab6dbb2ad0.mp4

### Steps to reproduce

 1. rotate an object
 2. enable "use local space"
 3. transform the object using the blender shortcut (which has to be configured explicitely in editor shortctus: `Spatial Editor > Begin Translate Transformation`)

**Comment by rcorre** [comment]
Good catch! Disabling `local_coords` at the start of a transform causes the gizmo to jump -- would it be better to hide the gizmo entirely during blender-style transforms? I vaguely remember hearing that idea at some point.


https://user-images.githubusercontent.com/2496231/159478874-5f98accd-0bbf-4d07-b1c0-36222e70351b.mp4

**Comment by mieldepoche** [comment]
> would it be better to hide the gizmo entirely during blender-style transforms?

That's how blender does it at least.

**Comment by maiself** [comment]
This has broken object local space transforms initiated by dragging on the gizmo. The gizmo now toggles to world space during the transform and then back to local after.

**Comment by akien-mga** [comment]
Could you open an issue to keep track of the regression? Or should we revert the PR for now and do another attempt taking care of both use cases?

**Comment by maiself** [comment]
Everything seems to be working again. 👍
