### ISSUE TITLE
The focus is not released as expected

### ISSUE THREAD

**Issue by Rindbee** [godotengine/godot#59406]
### Godot version

v4.0.alpha4.official [f47097973]

### System information

Linux Mint 20.3, Vulkan (both), NVIDIA GeForce GTX 1050 Ti

### Issue description

The editor cannot switch panels and tabs after a period of use. Now I feel like I have found the reason, the popup context menu.

### Steps to reproduce

New/Open a project, and enter the editor. 

Right-click on a dock A (for example, the file system dock) to open the context menu A-popup. Then left-click in anywhere, A-popup will be hidden. 

After doing this several times, the mouse it may not interact with any other editor/dock anymore, the dock A locks the focus.

This lock will be unlocked when the entire editor loses the focus.

**Comment by Sauermann** [comment]
After bisecting this bug, it looks like it got introduced in #58490.

**Comment by akien-mga** [comment]
CC @bruvzg

**Comment by gregkrsak** [comment]
I'm using Lubuntu, and find that if I minimize the Godot app and then maximize it again, this issue clears.

**Comment by nonunknown** [comment]
I can confirm in manjaro linux: v4.0.alpha.mono.custom_build [d7d528c15]

**Comment by jcarlosrc** [comment]
It happens in Windows too.

**Comment by Sauermann** [comment]
I was able to find the cause of this problem.

The following happens:
1. Press the RMB down on the Tree-Item in FileSystem Dock
2. The popup RMB-menu opens
3. Release the RMB
  3.1. The input event is sent from the OS to the currently active window: the popup menu
  3.2. The input event never reaches the main viewport and so the main viewports `gui.mouse_focus_mask` never gets released.

I believe, that one way to solve this problem could be to open the popup menu on RMB mouse release and not on RMB mouse down.

Also I found the following workaround:
- click anywhere with the RMB.

**Comment by Rindbee** [comment]
> I was able to pinpoint the cause of this problem.
> 
> This bug appears only with `interface/editor/single_window_mode == off`.
> 
> The following happens:
> 
> 1. Press the RMB down on the Tree-Item in FileSystem Dock
>    1.1. The popup RMB-menu opens
> 2. Release the RMB
>    2.1. The input event is sent from the OS to the currently active window: the popup menu
>    2.2. The input event never reaches the main viewport and so the main viewports `gui.mouse_focus_mask` never gets released.
> 
> Also I found the following workaround:
> 
> * click anywhere with the RMB.

I can confirm this.

And I find the second RMB-click will open a new RMB-menu, then the second menu will be quickly hidden. 

https://user-images.githubusercontent.com/30386067/160260140-3aaa3993-f6f0-4a0e-b7a0-f0fd1ceab7e0.mp4
