### ISSUE TITLE
Can't click on far right of editor window due to a control being added from a `tool` script

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#59433]
### Godot version

v3.5.beta2.official [7a4f9dfb1]

### System information

Mac OSX (Intel 2019)

### Issue description

It seems I can't click on the far right of the `Scene Tree` part of the editor window in `3.5`.

https://user-images.githubusercontent.com/100964/159645926-a9b64f8c-3488-4848-9490-496b62ff2bd1.mov

### Steps to reproduce

This strangely does not happen in all projects, perhaps something is overlaying the top of this area?

1. Try to click to hide something

**Comment by tavurth** [comment]
This problem is caused by a tool script that adds a control in the `_ready` function.

[debug-problem.zip](https://github.com/godotengine/godot/files/8330898/debug-problem.zip)

<img width="1552" alt="Screenshot 2022-03-23 at 10 48 01" src="https://user-images.githubusercontent.com/100964/159649046-9d8131a5-bd0e-4e5d-8dc1-043586a59db9.png">

I think it's better to only allow access to the editor DOM from `EditorPlugin` type `tool` scripts to prevent this issue.

**Comment by KoBeWi** [comment]
> I think it might be better to only allow access to the editor DOM from EditorPlugin type tool scripts to prevent this issue.

This isn't really possible. `tool` scripts run in the editor and they have to be handled carefully. You can crash the editor by simply modifying your scene in a wrong way, so such safe-guards wouldn't be helpful anyway.
