### ISSUE TITLE
Hide "Normal Map" import setting when not using VRAM compression mode

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot#59435]
### Godot version

3.4.3.stable

### System information

Windows 10, GLES3, GTX 980Ti

### Issue description

The Normal Map setting only affects textures when they are set to VRAM Compression.

If this is correct, then we should hide the Normal Map fold down like we do with the "HDR Mode" drop down.

Also is this correct? I understand that it should not be affected when choosing Uncompressed, but shouldn't Lossless and Lossy be able to only use two texture channels for a smaller texture like VRAM Compression does?

![image](https://user-images.githubusercontent.com/4955051/159649970-f3fb9864-e206-4e1a-908a-85fa2d1145ef.png)
![image](https://user-images.githubusercontent.com/4955051/159650053-61ee33fa-dbe9-44e3-9844-551e8722c0fe.png)

### Steps to reproduce

1. Open the import settings for a normal map in godot.
2. Set the mode to Lossless or Lossy and set Normal Map to Enable and select Reimport.

### Minimal reproduction project

Included a normal map to test on.
![nor_test](https://user-images.githubusercontent.com/4955051/159649755-04dc716f-b434-4e65-86dd-c43737207ffd.png)

**Comment by Calinou** [comment]
> Also is this correct? I understand that it should not be affected when choosing Uncompressed, but shouldn't Lossless and Lossy be able to only use two texture channels for a smaller texture like VRAM Compression does?

This is only possible for image formats that support RG channels. I don't think this is available for uncompressed images.

**Comment by Arnklit** [comment]
> > Also is this correct? I understand that it should not be affected when choosing Uncompressed, but shouldn't Lossless and Lossy be able to only use two texture channels for a smaller texture like VRAM Compression does?
> 
> This is only possible for image formats that support RG channels. I don't think this is available for the internal uncompressed image format, and lossless compression (PNG/WebP) definitely doesn't support this.

OK, then I think the option should be hidden when selecting those formats.
