### ISSUE TITLE
Adjusting `CanvasLayers` layer on runtime, does not update _gui_input handling to match the visual rendering

### ISSUE THREAD

**Issue by Arecher** [godotengine/godot#59448]
### Godot version

3.4.stable

### System information

Windows 10, GLES3

### Issue description

It seems that updating the `layer` of a `CanvasLayer` during runtime, only changes the visual rendering of the nodes, and does not change order in which input gets handled. Which means that nodes that visually get rendered behind other nodes, due to their CanvasLayer's layer, can still act as if they are up front (and block/handle input).

![Issue_Bug](https://user-images.githubusercontent.com/10502115/159765552-8421855b-635f-445b-900f-bb26f492f90b.gif)
_After changing the CanvasLayer's layer on the right button, the button shows itself to be visually in front. However, hover feedback shows that actually, the Control on the left is still considered to be the top one._

A mismatch between visuals and collision handling happens more often in Godot (`Controls` `clip_content` only clips visuals, not input, and `Controls` `show_behind_parent`), but those behave consistently and there are ways to make the input follow the visuals. However, there doesn't seem to be a way to make sure the input follows the visuals when adjusting the CanvasLayer's layer property. Plus the fact that on start-up, Controls in a higher CanvasLayer **do** also handle their input first/block Controls on lower CanvasLayers. Only after adjusting the layer on runtime, does the input not follow the visual order. So there is definitely an inconsistency, even if CanvasLayers were never meant to adjust input handling.

![Issue_WorkingProperly](https://user-images.githubusercontent.com/10502115/159767967-c8c4b9e9-f555-4bab-94d6-8e56d7a95c6b.gif)
_This shows the controls behaving as expected, before the render order is changes by changing the CanvasLayers layer_

I would expect changing the layer of a Canvaslayer to be up front, to automatically also adjust those nodes to take input before nodes that are rendered behind them. Or at the very least, there should be an option/method that could make it so. At the moment, there is no way that I know of to work around this issue.

### Steps to reproduce

*open the Reproduction Project below*

1) Hover both buttons
_Notice that the button rendered behind only becomes yellow when the button rendered in front is not blocking the input._
2) Click the button the right. 
_This will update the CanvasLayer's layer to 100, meaning the button on the right will be rendered in front of the left Button._
3) Hover the buttons, and especially the area in which they overlap.
_You would expect that hovering the area in which the buttons intersect, to only show the Button that is rendered in front as being 'hovered' (yellow), but instead the button that is rendered behind is showing it is hovered._

### Minimal reproduction project

[issue_canvaslayerdoesnotupdateguiinput.zip](https://github.com/godotengine/godot/files/8335542/issue_canvaslayerdoesnotupdateguiinput.zip)

**Comment by Arecher** [comment]
This issue is similar to [#50678](https://github.com/godotengine/godot/issues/50678), but that report seems to be specifically about `WindowDialogs` having a similar issue on Startup. However, if that WindowDialog is changed out for any regular Control, the issue isn't there anymore. This issue seems to be with any Control, and specifically after changing the layer on runtime.

I do suspect the issues are related, since `WindowDialogs` might use a similar system to CanvasLayers to adjust their rendering.

**Comment by Sauermann** [comment]
At the moment, mainly the Nodes position within the SceneTree influences event processing. The layer of the canvas has no impact on events.

**Comment by Arecher** [comment]
> At the moment, mainly the Nodes position within the SceneTree influences event processing. The layer of the canvas has no impact on events.

Right, I thought that might be the case, so I checked for that. But in the reproduction project, the CanvasLayer with the higher layer, is higher in the tree. Meaning on start-up, the Control that is rendered behind (lower layer) should, if the SceneTree is the one that determines processing, be handled as if it is up front. But it isn't.

And adjusting the position of the CanvasLayer in the SceneTree on runtime has no influence on which node gets processed either.

**Comment by Arecher** [comment]
I agree with this issue being in part a documentation issue. Canvaslayers should definitely mention that they are only a visual tool, and do not adjust the processing order.

However, after some more testing in the reproduction project, there is definitely something odd/inconsistent going on. The SceneTree order doesn't handle the processing order properly (if CanvasLayers are involved?). I adjusted the Controls to raise the CanvasLayers when they are clicked, meaning the Canvaslayer that is rendered in front, should also process input first. But that doesn't work consistently, raising the CanvasLayer doesnt always mean the nodes in that Layer will be processed first.


![Issue_RaisingDoesNOTHandleProcessingProperly2](https://user-images.githubusercontent.com/10502115/159970597-60959fa0-cc3d-4897-a151-6fb6c2caab3b.gif)
_The X and V indications are here to indicate whether the proccessing of the Controls follows the rule of **Lower down the SceneTree gets processed first**_
_At the start, the processing happens in reverse order of how the nodes are in the scene tree. Then, upon raising (& changing the layer) of the right control, the processing follows the scene tree. Raising the left control will continue to behave properly, but then raising the right control for a **second** time, will have the nodes be processed in the wrong order again_

To me this seems like it could only be a bug, but if there is an explanation, i'd love to understand what's going on. Here is the (updated) reproduction project: [issue_canvaslayerdoesnotupdateguiinput2.zip](https://github.com/godotengine/godot/files/8343843/issue_canvaslayerdoesnotupdateguiinput2.zip)



Lastly, I was wondering if there is a way to have nodes be processed in a certain order, regardless of their SceneTree Position, since that's what I would need for my project. If there isn't, perhaps CanvasLayers would be a good way to add that functionality for the future.

**Comment by Arecher** [comment]
Would it be possible to cherrypick this bugfix for 3.6? 🙏
