### ISSUE TITLE
Unable to bind Vector3 argument to a signal when multiple arguments are needed

### ISSUE THREAD

**Issue by devloglogan** [godotengine/godot#59446]
### Godot version

4.0.alpha4

### System information

Windows 10

### Issue description

Engine crashes when attempting to bind multiple arguments to the timeout signal if one of them is a Vector3. I will provide a screenshot on how to easily reproduce this.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/95497005/159754340-952ba143-c67b-4f87-bd3b-be5b855be329.png)

After pressing the connect button, engine will crash.

**Comment by KoBeWi** [comment]
Can't reproduce in alpha7. Some similar bug was fixed recently.
