### ISSUE TITLE
***Error precompiling shader: Expected ')' in expression

### ISSUE THREAD

**Issue by supaiku-o** [godotengine/godot#5944]
Somewhere in between 2f8910185ea42a4b401a98b04f869562c87ffed6 and c0e3c1fe7a869b36063b89271977ea0bdeda34a9 my shader breaks. :(

I use a textureshader found in the second post here: http://godotdevelopers.org/index.php?topic=15504.0

At 2f8910185ea42a4b401a98b04f869562c87ffed6 everything was still working, but today I pulled the latest changes, something broke and I get the following error

> ***Error precompiling shader: Expected ')' in expression
error 12:0

I think this classifies as a regression and is imo a blocker for 2.1.

**Comment by akien-mga** [comment]
This might be a regression from 2150855.

**Comment by supaiku-o** [comment]
@akien-mga It's saved as a .tres file.

**Comment by supaiku-o** [comment]
The culprit is eefca1ada97a6bc5db38936d23da323a78b2044d.
