### ISSUE TITLE
Websocket returns SSL errors connecting to Twitch Pub/Sub server.

### ISSUE THREAD

**Issue by ynot01** [godotengine/godot#59458]
### Godot version

3.4.4.stable

### System information

Windows 10

### Issue description

Upon connection, two errors are printed and the socket is immediately closed.
```
Connected with protocol:
thirdparty/mbedtls/library/ssl_tls.c:4649: mbedtls_ssl_handle_message_type() returned -30848 (-0x7880)
thirdparty/mbedtls/library/ssl_tls.c:8634: mbedtls_ssl_read_record() returned -30848 (-0x7880)
Closed, clean: False
```

### Steps to reproduce

1. Copy the Websocket's client snippet from https://docs.godotengine.org/en/stable/tutorials/networking/websocket.html into a Node's script
2. Set `websocket_url` to `"wss://pubsub-edge.twitch.tv"`

### Minimal reproduction project

[websocket_minimal.zip](https://github.com/godotengine/godot/files/8337742/websocket_minimal.zip)

**Comment by Faless** [comment]
`-0x7880` means `MBEDTLS_ERR_SSL_PEER_CLOSE_NOTIFY`, i.e. the remote server is closing the connection.

As far as I understand you need authentication to access their API, so they are simply closing the connection because it's missing ([see their JS example](https://github.com/twitchdev/pubsub-javascript-sample/blob/main/main.js#L94-L115)).

**Comment by ynot01** [comment]
> `-0x7880` means `MBEDTLS_ERR_SSL_PEER_CLOSE_NOTIFY`, i.e. the remote server is closing the connection.
> 
> As far as I understand you need authentication to access their API, so they are simply closing the connection because it's missing ([see their JS example](https://github.com/twitchdev/pubsub-javascript-sample/blob/main/main.js#L94-L115)).

I do not believe that any such authentication is required on the initial connection, and it is not documented anywhere that it is required. Authentication is only required when calling topics via sending messages through the socket.

Using https://www.piesocket.com/websocket-tester to connect to `wss://pubsub-edge.twitch.tv` allows connection very easily (notably without instant disconnection & errors), and sending the message `{"type": "PING"}` proves to work flawlessly, leading me to believe this is an issue on Godot's side.

![](https://i.imgur.com/IzFj9NJ.png)

**Comment by Faless** [comment]
Oh, I see the problem, the demo is immediately sending the message "Test packet" upon connection:

```
func _connected(proto = ""):
	# This is called on connection, "proto" will be the selected WebSocket
	# sub-protocol (which is optional)
	print("Connected with protocol: ", proto)
	# You MUST always use get_peer(1).put_packet to send data to server,
	# and not put_packet directly when not using the MultiplayerAPI.
	_client.get_peer(1).put_packet("Test packet".to_utf8())
```

And it's sending it in binary mode (which is the default). Their server does not like binary mode, so it immediately closes the connection. You need to the write mode to text before sending any message:

```
func _connected(proto = ""):
	_client.get_peer(1).set_write_mode(WebSocketPeer.WRITE_MODE_TEXT)
	_client.get_peer(1).put_packet('{"type": "PING"}'.to_utf8())
```

Will work and you will receive the pong correctly.

```
Godot Engine v3.5.beta.custom_build.fa08c0c85 - https://godotengine.org
OpenGL ES 2.0 Renderer: NVIDIA GeForce GTX 980/PCIe/SSE2
 
Connected with protocol: 
Got data from server: { "type": "PONG" }
```

**Comment by Faless** [comment]
Sorry, closed by mistake, please confirm it works on your side, but that should be it :)
