### ISSUE TITLE
Vulkan: Error spam when assigning Skeleton2D to Polygon2D

### ISSUE THREAD

**Issue by palia5** [godotengine/godot#59451]
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

4.0 alpha 3

### System information

Pop!_OS 20.04 LTS - GTX 1060 Mobile - Vulkan mobile

### Issue description

When attempting to follow the [2D skeletons tutorial](https://docs.godotengine.org/en/stable/tutorials/animation/2d_skeletons.html#doc-2d-skeletons), the texture on the polygons disappears when I assign a skeleton2D to the polygons. 

Output starts filling up with below error:

```
drivers/vulkan/rendering_device_vulkan.cpp:4044 - Condition "!vertex_buffer_owner.owns(p_src_buffers[i])" is true. Returning: RID()
  drivers/vulkan/rendering_device_vulkan.cpp:7272 - Condition "!vertex_array" is true.
  The vertex format used to create the pipeline does not match the vertex format bound.
  drivers/vulkan/rendering_device_vulkan.cpp:4044 - Condition "!vertex_buffer_owner.owns(p_src_buffers[i])" is true. Returning: RID()
  drivers/vulkan/rendering_device_vulkan.cpp:7272 - Condition "!vertex_array" is true.
  The vertex format used to create the pipeline does not match the vertex format bound.
  drivers/vulkan/rendering_device_vulkan.cpp:4044 - Condition "!vertex_buffer_owner.owns(p_src_buffers[i])" is true. Returning: RID()
  drivers/vulkan/rendering_device_vulkan.cpp:7272 - Condition "!vertex_array" is true.
  The vertex format used to create the pipeline does not match the vertex format bound.
  drivers/vulkan/rendering_device_vulkan.cpp:4044 - Condition "!vertex_buffer_owner.owns(p_src_buffers[i])" is true. Returning: RID()
  drivers/vulkan/rendering_device_vulkan.cpp:7272 - Condition "!vertex_array" is true.
  The vertex format used to create the pipeline does not match the vertex format bound.
  drivers/vulkan/rendering_device_vulkan.cpp:4044 - Condition "!vertex_buffer_owner.owns(p_src_buffers[i])" is true. Returning: RID()
  drivers/vulkan/rendering_device_vulkan.cpp:7272 - Condition "!vertex_array" is true.
  The vertex format used to create the pipeline does not match the vertex format bound.
  drivers/vulkan/rendering_device_vulkan.cpp:4044 - Condition "!vertex_buffer_owner.owns(p_src_buffers[i])" is true. Returning: RID()
  drivers/vulkan/rendering_device_vulkan.cpp:7272 - Condition "!vertex_array" is true.
  The vertex format used to create the pipeline does not match the vertex format bound.
  drivers/vulkan/rendering_device_vulkan.cpp:4044 - Condition "!vertex_buffer_owner.owns(p_src_buffers[i])" is true. Returning: RID()
  drivers/vulkan/rendering_device_vulkan.cpp:7272 - Condition "!vertex_array" is true.
  The vertex format used to create the pipeline does not match the vertex format bound.
  drivers/vulkan/rendering_device_vulkan.cpp:4044 - Condition "!vertex_buffer_owner.owns(p_src_buffers[i])" is true. Returning: RID()
  drivers/vulkan/rendering_device_vulkan.cpp:7272 - Condition "!vertex_array" is true.
  The vertex format used to create the pipeline does not match the vertex format bound.
  drivers/vulkan/rendering_device_vulkan.cpp:4044 - Condition "!vertex_buffer_owner.owns(p_src_buffers[i])" is true. Returning: RID()
  drivers/vulkan/rendering_device_vulkan.cpp:7272 - Condition "!vertex_array" is true.
  The vertex format used to create the pipeline does not match the vertex format bound.
  drivers/vulkan/rendering_device_vulkan.cpp:4044 - Condition "!vertex_buffer_owner.owns(p_src_buffers[i])" is true. Returning: RID()
  drivers/vulkan/rendering_device_vulkan.cpp:7272 - Condition "!vertex_array" is true.
  The vertex format used to create the pipeline does not match the vertex format bound.
  drivers/vulkan/rendering_device_vulkan.cpp:4044 - Condition "!vertex_buffer_owner.owns(p_src_buffers[i])" is true. Returning: RID()
  drivers/vulkan/rendering_device_vulkan.cpp:7272 - Condition "!vertex_array" is true.
  The vertex format used to create the pipeline does not match the vertex format bound.
  drivers/vulkan/rendering_device_vulkan.cpp:7272 - Condition "!vertex_array" is true.
  The vertex format used to create the pipeline does not match the vertex format bound.
  drivers/vulkan/rendering_device_vulkan.cpp:7272 - Condition "!vertex_array" is true.
  The vertex format used to create the pipeline does not match the vertex format bound.
  drivers/vulkan/rendering_device_vulkan.cpp:7272 - Condition "!vertex_array" is true.
  The vertex format used to create the pipeline does not match the vertex format bound.
  drivers/vulkan/rendering_device_vulkan.cpp:7272 - Condition "!vertex_array" is true.
  The vertex format used to create the pipeline does not match the vertex format bound.`
```

### Steps to reproduce

Follow the steps in the [2D skeletons tutorial](https://docs.godotengine.org/en/stable/tutorials/animation/2d_skeletons.html#doc-2d-skeletons).

### Minimal reproduction project

[2dSkeletonIssue.zip](https://github.com/godotengine/godot/files/8336237/2dSkeletonIssue.zip)

**Comment by YeeveX** [comment]
Had this also happening in windows with a GTX1060 3gb

**Comment by jonSP12** [comment]
> Had this also happening in windows with a GTX1060 3gb

Does that mean the skeleton2D feature is working ?

**Comment by Zireael07** [comment]
Most likely you have some remnants of GTA still lingering...

**Comment by akien-mga** [comment]
> Most likely you have some remnants of GTA still lingering...

Some applications install Vulkan layers in the Windows registry, and don't clean it up on uninstall. You'll have to remove it manually from `\HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan`.

**Comment by jonSP12** [comment]
> > Most likely you have some remnants of GTA still lingering...
> 
> Some applications install Vulkan layers in the Windows registry, and don't clean it up on uninstall. You'll have to remove it manually from `\HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan`.

you mean hiting delete on this reg ?
Ive already deleted all other reg entries related with social, this is the only one
![bug2](https://user-images.githubusercontent.com/77213594/168590147-29cf9098-208d-4a02-890d-451323046998.png)

there are still 3 jason entries left in the folder below, related to steam and riva tuner statistcs. Is it ok to deleted all the entries and leave only the default ?
![bug3](https://user-images.githubusercontent.com/77213594/168590456-d0ce58ce-c0dc-4676-9748-7cc48e9a2e92.png)

**Comment by jonSP12** [comment]
[edit]
deleting the reg path solved it the error no longer appears.
but the sprite is still missing after adding the skeleton 2d

**Comment by elmordo** [comment]
Hi, I confirm the bug about missing sprites (Polygon2D) on Pop!_OS 22.04 LTS and NVIDIA GeForce GTX 1050 Ti.

**Comment by Hazarth** [comment]
I also just encountered this bug on Kubuntu 22.04 LTS and NVIDIA GeForce RTX 3050 Ti Laptop. 

Weird thing is, when I move the Polygon2D node around, it tries to render the sprite, but then it immediately disappears in a split second... so while redrawing it's drawing the polygon, but probably crashes right after (though there is no error log in the console)

![polygonBug](https://user-images.githubusercontent.com/30556348/198887854-eefac95c-caff-4366-a0c9-7ec4f9bf70a6.gif)

**Comment by jonSP12** [comment]
The image is upsideDown ( not inverted ), maybe that is why it disapears once the skeleton2D gets in.
--


![Image](https://user-images.githubusercontent.com/77213594/202650303-82d91cf1-b695-4d7c-8260-da8c8815b049.png)

**Comment by clayjohn** [comment]
Looking into this issue now. As a brief update, you can ignore the bug and assign bones as normal. Once bones are assigned to the Polygon2D the errors will go away and the Polygon2D will re-appear

**Comment by barrrettt** [comment]
godot 4.0beta5 when asing skeleton2d to polygon2d
![image](https://user-images.githubusercontent.com/47840319/202822265-13671123-56ef-4915-831d-52c9b03bcd79.png)
error :fearful: 
![image](https://user-images.githubusercontent.com/47840319/202822299-781c15be-fa7b-49b4-8932-1f5f233f9c1e.png)

No vertex array was bound, and render pipeline expects vertices.
  drivers/vulkan/rendering_device_vulkan.cpp:7717 - Condition "!vertex_array" is true.

every few miliseconds.
