### ISSUE TITLE
Godot 3.4.4-stable iOS export Xcode linking gives a segmentation fault for `debug` template (fixed in updated templates)

### ISSUE THREAD

**Issue by uvokin33** [godotengine/godot#59455]
### Godot version

3.4.4 stable

### System information

MacOS 12.3

### Issue description

After export for iOS I can't open project in Xcode, in 3.4.3 stable same project with same settings opens and builds fine
<img width="439" alt="image" src="https://user-images.githubusercontent.com/6631021/159817604-51f484a4-0c7b-476d-bde7-74cf1fd7acf2.png">

### Steps to reproduce

Export project for IOS(debug/release), try to open `.xcodeproj` in Xcode 

### Minimal reproduction project

[ios-test.zip](https://github.com/godotengine/godot/files/8337513/ios-test.zip)

**Comment by Calinou** [comment]
@uvokin33 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by uvokin33** [comment]
@Calinou added archive to description

**Comment by akien-mga** [comment]
CC @godotengine/ios

**Comment by bruvzg** [comment]
Seems like this is some issue with the export template packaging.

The Xcode project in the export template contains `$pbx_locale_file_reference` line, which is not part of `3.4.4`

https://github.com/godotengine/godot/blob/419e713a29f20bd3351a54d1e6c4c5af7ef4b253/misc/dist/ios_xcode/godot_ios.xcodeproj/project.pbxproj#L40-L46

But it is present in the `3.x` (it's part of #58733, which is back ported for 3.5 but not for 3.4.4).
https://github.com/godotengine/godot/blob/788abafb77172d8069428568f0be039f0a85b66a/misc/dist/ios_xcode/godot_ios.xcodeproj/project.pbxproj#L41-L47

I have no idea why the file from the wrong branch get to the package (might be some issue with the [build scripts](https://github.com/godotengine/godot-build-scripts)).

**Comment by bruvzg** [comment]
Actually, there are also `MoltenVK` references, so it's `4.0` project template files, that were packaged, instead of `3.4.4`.

**Comment by bruvzg** [comment]
Same with the macOS export template, it also contains files from master (in this case it will run, but won't have proper icon and app information set).

**Comment by akien-mga** [comment]
Damn :| Thanks for catching and reporting this early, I'll re-upload the export templates using the correct scripts.

**Comment by akien-mga** [comment]
This should now be fixed, you'll have to redownload the export templates locally to solve the issue.

You may also want to redownload the macOS editor binary which has changed slightly (but that's not necessary to solve this issue, the changes are just on some metadata).

**Comment by akien-mga** [comment]
I'll keep this open and pinned for some time so that other users notice the hotfix.

**Comment by uvokin33** [comment]
@akien-mga I redownloaded editor and export templates and now project opens in Xcode, but not building
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/6631021/159896820-2a6786a6-a886-4b80-9807-867a8f1a2b1f.png">

**Comment by akien-mga** [comment]
@uvokin33 Thanks for testing, @bruvzg could confirm the same issue. We're looking into why it happens, seems like the binary might have been corrupted. The `release` template should work in the meantime.

**Comment by akien-mga** [comment]
@uvokin33 Could you test these updated export templates? https://github.com/godotengine/godot/releases/download/3.4.4-stable/Godot_v3.4.4-stable_export_templates.tpz

**Comment by uvokin33** [comment]
@akien-mga this template works fine

**Comment by akien-mga** [comment]
Great, thanks for testing!

**Comment by uvokin33** [comment]
Thanks for fixing)
