### ISSUE TITLE
3.5.beta, MarginContainer, reset buttons overlap text

### ISSUE THREAD

**Issue by duianto** [godotengine/godot#59469]
### Godot version

v3.5.beta2.official [7a4f9dfb1]

### System information

Windows 10 21H2

### Issue description

`Godot 3.5.beta` added reset buttons to the `MarginContainer` inspector properties:
`Theme Overrides > Constants > Margin Right` (Top, Left, and Right)

But the reset buttons are offset, to far to the left,
this makes them overlap the property name's last word.

![Godot_v3 5-beta2_win64_ptSzlkP80n](https://user-images.githubusercontent.com/13420573/159928093-f00fcba6-0614-4151-ab3b-612585f47cb3.png)

### Steps to reproduce

- Start: `Godot 3.5.beta2`
- Add a new node: `MarginContainer` (Node > Control > Container)
- In the inspector, click on: `Theme Overrides`
it unfolds the text: `Constants`
- Click on: `Constants`
it unfolds four properties:
```
Margin Right
Margin Top
Margin Left
Margin Bottom
```
- Change the value of the margins,
for example, by clicking on the up arrow on the right side of the input box.

### Observed

A reset button (circular arrow), appears to the left of the input box.
But the reset button appears too far to the left, this makes it overlap the last word.

![Godot_v3 5-beta2_win64_ptSzlkP80n](https://user-images.githubusercontent.com/13420573/159928093-f00fcba6-0614-4151-ab3b-612585f47cb3.png)

There is an empty area between the reset button and the input box.
It hides the last letters of the property name. (most likely to make room for the reset button)

### Expected

The reset button shouldn't overlap the text.

### Notes

The reset button seems to have been added in the `Godot 3.5 beta`.

Because the issue is observed in:
- v3.5.beta2.official [7a4f9dfb1]
- v3.5.beta1.official [b9b23d222]

The `MarginContainer` properties don't have a reset button in `Godot 3.4.4`.

![Godot_v3 4 4-stable_win64_vpEbvvcsQE](https://user-images.githubusercontent.com/13420573/159928528-8942e334-95d2-410c-b575-3150bed98285.png)

**Comment by lawnjelly** [comment]
This looks fixed to me. Can reopen if incorrect.
