### ISSUE TITLE
Cubemap clear side and mixing RGB/RGBA problems

### ISSUE THREAD

**Issue by pkowal1982** [godotengine/godot#5946]
**Operating system or device - Godot version:**
Ubuntu 14.04, Win7 64b, Godot_v2.1_rc1

**Issue description** (what happened, and what was expected):
When you set side of cubemap you can't clear it in editor. It gives:
`ERROR: CubeMap::set_side: Condition p_image_empty() is true...`

When you try to create cubemap with RGB and RGBA images it fails with:
`ERROR: RasterizerGLES@::texture_set_data: Condition texture->format != p_image.get_format...`

Clearing sides should be possible.
As for mixing different texture formats, if it's not possible it should at least give some meaningful error.

**Steps to reproduce:**
Open example project.
Create new CubeMap.
Add icon.png (saved in RGBA mode) as left side.
Try to add icon_rgb.png (RGB mode) as right side.
It will give you an error.
Now try to clear left side with dropdown menu.
It gives another error.

**Link to minimal example project** (optional but very welcome):
[cubemap_bug.zip](https://github.com/godotengine/godot/files/387980/cubemap_bug.zip)

**Comment by Calinou** [comment]
Since cubemaps were removed in favor of panorama skies as of Godot 3.0, I'm closing this.
