### ISSUE TITLE
[HTML5 Request]The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.

### ISSUE THREAD

**Issue by Atem1995** [godotengine/godot#59462]
### Godot version

3.4.4 stable

### System information

window 10 

### Issue description

"Access to fetch at 'https://atem1995.github.io/game_library/D/Dodge%20the%20Creeps.pck' from origin 'http://localhost:8060' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'."
I tried to download PCK resources from GitHub remote server, but obviously I failed.
I don't understand why。。。

### Steps to reproduce

#

**Comment by Atem1995** [comment]
https://gist.github.com/natrim/1a19f4b7668e0474897f3f28171f3b33?permalink_comment_id=4108811#gistcomment-4108811
By the way, if someone wants to gzip the *.pck or *.wasm. Iwrite an idea above link.

**Comment by akien-mga** [comment]
I don't have experience with it myself, but you should read https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS and the error you get should make sense.

It might be that the problem is with github.io and if so there's no way around it.

**Comment by Atem1995** [comment]
> 
When I use Python's http Server, 'Access-Control-Allow-Origin' cannot be set to *, otherwise the same error will be reported. But the official document is recommended to be set to *, so I don't know what to do.

**Comment by akien-mga** [comment]
Did you see this?
![image](https://user-images.githubusercontent.com/4701338/159893759-c08a0b7b-8fed-4456-a291-f9dc21d60bcd.png)

**Comment by Atem1995** [comment]
> Did you see this? ![image](https://user-images.githubusercontent.com/4701338/159893759-c08a0b7b-8fed-4456-a291-f9dc21d60bcd.png)

Oh,Thank you very much! I finally make it.Thank you, my dear friend! Godot is amazing!
