### ISSUE TITLE
Skeleton3D pos/rot/scl issue when blending animations via animation blend tree

### ISSUE THREAD

**Issue by macryc** [godotengine/godot#59477]
### Godot version

Godot 4 alpha 5

### System information

Win10, RTX2070

### Issue description

I originally raised this issue a few months ago under: https://github.com/godotengine/godot/issues/55838.

It was recently closed in https://github.com/godotengine/godot/pull/57675

But the issue still remains. The problem is that the 3d skeleton's root bone becomes skewed in all 3 aspects: position, rotation, scale when blending between 2 skeletal animations using the animation blend tree.

The recent merge fixes only the position, while scaling and rotation issues remain.

The only commit so far that fixes the issue properly is this one:
https://github.com/godotengine/godot/pull/54205/commits

### Steps to reproduce

See original issue here: https://github.com/godotengine/godot/issues/55838

**Comment by TokageItLab** [comment]
@macryc Is the rest of root bone of your model Transform3D(Quaternion(0,0,0,1),Vector3(0,0,0))? I need a sample project to determine the cause.

**Comment by macryc** [comment]
Hi guys, please close this issue. Upon further inspection, it's not the Blend2/3 node that is causing issues anymore. It's the Add2/3 node now. 
I've raised another bug report for this - #59536
