### ISSUE TITLE
Vulkan: View-dependant SSAO artifact in center of screen when half-size is enabled

### ISSUE THREAD

**Issue by NineAlexT** [godotengine/godot#59471]
### Godot version

4.0 Alpha 5

### System information

Kubuntu 20.04, Nvidia GTX 1060, Driver 510, Vulkan

### Issue description

A dark vertical line appears in SSAO in the center of the screen when half-size is enabled in the project settings. the line appears to be view-dependant and can only be seen from certain angles.
Half size:
![image](https://user-images.githubusercontent.com/60285548/159952055-104725c4-8046-44b2-9b69-aeb6dd1cb378.png)
Full res:
![image](https://user-images.githubusercontent.com/60285548/159952276-428fba86-b21d-4aed-88d1-54a2645bf648.png)

### Steps to reproduce

Create a new scene, add some objects, enable AO look at the scene from different angles. I think it's pretty obvious in the regular view, but the SSAO debug view makes it even more apparent.

### Minimal reproduction project

[SSAO artifact.zip](https://github.com/godotengine/godot/files/8343091/SSAO.artifact.zip)

**Comment by mrjustaguy** [comment]
This is related https://github.com/godotengine/godot/issues/51564#issuecomment-897700747
