### ISSUE TITLE
4.0 Alpha 5 regression: Color blending with alpha channel by AnimationTree is broken

### ISSUE THREAD

**Issue by jcarlosrc** [godotengine/godot#59474]
### Godot version

4.0 Alpha 5

### System information

Windows 10

### Issue description

When using an Animation Tree  it changes properties to default values after an animation is ended. As an example, in the minimal project attached:
* If we use the AnimationPlayer directly, it works as expected (transparency to 0) (first video).
* If we use the AnimationTree, it resets ColorRect to a default white (1,1,1,1) color value (second video).

This occurs for any property on any node. The problem is new, Alpha 4 did not preset it. Imported animations from Blender seems not to be affected.

https://user-images.githubusercontent.com/8985409/159957515-f3aa843f-b6b6-4c6c-a5cf-8dc2b060bbe5.mp4

https://user-images.githubusercontent.com/8985409/159957539-43f6a082-1c78-4fb2-894f-587d72a52659.mp4

### Steps to reproduce

In the attached minimal project, enable or disable "Use animation tree" option and run the project to see the behavior as in the videos.

### Minimal reproduction project

[BugReport02_4alpha5.zip](https://github.com/godotengine/godot/files/8343304/BugReport02_4alpha5.zip)

**Comment by Calinou** [comment]
cc @TokageItLab

**Comment by nonunknown** [comment]
just a question, the animationplayer in question was made local?

**Comment by jcarlosrc** [comment]
> just a question, the animationplayer in question was made local?

Yes, animations were made inside Godot. Those are which have the problem.

**Comment by jcarlosrc** [comment]
It is a simple animatio

> > just a question, the animationplayer in question was made local?
> 
> Yes, animations were made inside Godot. Those are which have the problem.

It is a simple Animation Player node in main scene which changes the color of a child node, the color rectangle.

**Comment by TokageItLab** [comment]
I think this is a bug caused by Variant::zero() actually using an initial value instead of zero: we want Color(0,0,0,0) but it return Color(1,1,1,1), maybe we should create separate functions like Variant::zero() and Variant::init().

**Comment by TokageItLab** [comment]
At least this seems to be a special case bug for the alpha value of Color. I have sent a fix so that `Variant::zero()` explicitly returns `Color(0,0,0,0)` for blending as #59490.

**Comment by jcarlosrc** [comment]
This is not exclusive of color. Animated collision shapes also go back to its default (0,0,0) position in a similar behavior.

> For now, this seems to be a special case bug for the alpha value of Color. I have sent a fix so that `Variant::zero()` explicitly returns `Color(0,0,0,0)` for blending as #59490.

**Comment by TokageItLab** [comment]
@jcarlosrc Can you test #59490?

**Comment by TokageItLab** [comment]
Note: It may be that it should be mentioned in the documentation, but if one of the two animations to be blended is missing a track, it will be blended with the zero value.

**Comment by jcarlosrc** [comment]
If a track is missing in the other animation it should not be blended. This is the behavior of all versions previous to 4.0 alpha 5. Otherwise, we will need to insert a track for every property ever keyframed in any animation to avoid a bad mixing. This does not make sense.

**Comment by TokageItLab** [comment]
It creates an incongruity that the blended result will not always be the same, and we decided in discussions with reduz that it is an edge case.
