### ISSUE TITLE
Clarify why HTML5 export templates are missing in 4.0 alpha builds

### ISSUE THREAD

**Issue by chosia** [godotengine/godot#59476]
### Godot version

4.0.alpha3

### System information

MacOS 10.15.7

### Issue description

I cannot export project to webassembly. It seems that the webassembly export templates are missing. I can download export templates for 4.0.alpha3, but 'webassembly_release.zip' and 'webassembly_debug.zip' are missing:
<img width="904" alt="Screenshot 2022-03-24 at 17 43 58" src="https://user-images.githubusercontent.com/29225521/159967690-2d1e861a-af4e-4894-b881-37b34cc39f58.png">
<img width="729" alt="Screenshot 2022-03-24 at 17 44 17" src="https://user-images.githubusercontent.com/29225521/159967734-631a2ee7-c06c-4dee-865a-96f932ee7dee.png">
<img width="762" alt="Screenshot 2022-03-24 at 17 44 29" src="https://user-images.githubusercontent.com/29225521/159967774-ff5e04cf-d76c-44a9-8079-54a3c07a8f31.png">

### Steps to reproduce

Project -> Export...

**Comment by Calinou** [comment]
HTML5 support is currently missing in Godot 4 because there is no production-ready OpenGL renderer yet. This is required for WebGL support, as Vulkan currently can't be used in a reliable manner on HTML5 (WebGPU isn't mature enough yet).

**Comment by Calinou** [comment]
We could make hide the option to create an HTML5 export preset for now, and replace it with a placeholder as was proposed for consoles: https://github.com/godotengine/godot/pull/42359

What do you think?

**Comment by akien-mga** [comment]
I didn't really like the placeholder proposal back then so I wouldn't introduce it now.
We can maybe make the HTML5 export code `DEV_ENABLED` only, so contributors can still access it in `debug` builds to test future HTML5 templates but it won't be in release builds.
