### ISSUE TITLE
Endless stream of errors in 2.1rc1 high DPI

### ISSUE THREAD

**Issue by Qudware** [godotengine/godot#5949]
On Windows 10, v2.1rc1, high dpi 2K display:

Launching the old Godot 2.0.x works fine. Completely not working in 2.1rc1. I get an endless (literally) stream of errors in the terminal that opens with Godot.

Set Godot to launch in high DPI mode in the settings, relaunch, and this should happen (never works again). I am on a 2736x1824 at 267 PPI display.

[Error dump on gist](https://gist.github.com/Qudware/6807a3bf9c52e965cdb2c6687e0e41c7)

I should note that after ~8 mins it opens the project manager, when selecting a project it completely crashes!

**Comment by bojidar-bg** [comment]
Looks related to either the libpng update or the asset library...

**Comment by akien-mga** [comment]
Or the 2x png images are bogus.

**Comment by Qudware** [comment]
Aight, I spent this morning trying to fix this without success. I tried disabling high DPI scaling, and this time I didn't get any errors, it just crashed. Same results when using Windows Troubleshooter. It seems the 'hi dpi' setting is stored somewhere else like in the registry/appdata & I can't make it go away (even though I'd love me some high DPI). Guess I'll be using the older version for now! Tell me if I could be of any help.

**Comment by eska014** [comment]
On Windows, the editor settings are located in `C:\Users\USERNAME\AppData\Roaming\Godot\editor_settings.tres`.

As a workaround to change back to LoDPI mode for now, you'll want to change

    global/hidpi_mode = 2

to

    global/hidpi_mode = 1

**Comment by vnen** [comment]
> Or the 2x png images are bogus.

That seems to be the case. Here is a section of the generated header for HiDPI (all of them have the same data):
```
static const unsigned char icon_add_track_hidpi_png[]={
0x89,0x50,0x4e,0x47,0xa
};
```

Now, why this affects only Windows? Since this data is generated by a Python script, what could be different in the platform?
