### ISSUE TITLE
Animated CpuParticles with texture atlasas are compleatly broken. 

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#59494]
### Godot version

3.4.4 stable

### System information

KDE neon 20.04

### Issue description

It seems texture atlases with cpu particles are completely broken with godot.
I have a 64x40 texture of 8x8 sprites and I have clipped it with a texture atlas to (0,16,16,8) and have the material to use non looping 2x1 particle animation with a animation speed of 1.

Yet it is jumping from the first frame all the way to frame count + 3
![image](https://user-images.githubusercontent.com/2453707/160022259-606d3763-81d5-4b53-a256-379f5b01ba7a.png)
![image](https://user-images.githubusercontent.com/2453707/160022432-7d54eb2c-ee91-4455-aa34-c734822d2975.png)
![image](https://user-images.githubusercontent.com/2453707/160022465-58b12baf-eace-4ae8-bc48-ff5f93c5688d.png)
![image](https://user-images.githubusercontent.com/2453707/160022490-563f0eee-a295-4513-bf8f-225576e2c16e.png)
![image](https://user-images.githubusercontent.com/2453707/160022511-22d4e773-1f43-4cc4-9092-94f9104678f7.png)

### Steps to reproduce

Mess with the cpu particle editor idk, it was working fine until I changed it from 8 frames to 4 and then to 2

### Minimal reproduction project

no.

**Comment by Calinou** [comment]
> 3.3 stable

[Godot 3.3.x is not supported for bug fixes anymore](https://docs.godotengine.org/en/stable/about/release_policy.html#release-support-timeline), so please upgrade to [3.4.3](https://godotengine.org/article/maintenance-release-godot-3-4-3) and check if the issue still occurs there.

**Comment by Shadowblitz16** [comment]
my version is 3.4.4 sorry

**Comment by adamscott** [comment]
> Mess with the cpu particle editor idk, it was working fine until I changed it from 8 frames to 4 and then to 2

Please, try at least to reproduce your issue before creating a new issue. And please refrain using sentences like "completely broken", as it does not share any valuable information about the issue. Thank you.

**Comment by Shadowblitz16** [comment]
@adamscott The problem is idk what causes the issue.
I was just messing with cpu particles because normal particles don't support sprite animation. when I changed it to 4 frames it stopped working.
I will see if I can reproduce if I can ever get around the self referencing limitation

**Comment by adamscott** [comment]
> @adamscott The problem is idk what causes the issue.
> I was just messing with cpu particles because normal particles don't support sprite animation. when I changed it to 4 frames it stopped working.

Issues on GitHub are not made to debug your project. They are made to report issues with the program itself. If Godot does not work as you intend to, it does not mean that there's necessarily an issue about it.

I suggest you to join [Godot Engine - Q&A](https://godotengine.org/qa/) to post questions about your issues with your project or [join the Discord](https://discord.com/invite/4JBkykG) to chat with other developers. Then, if an issue still exists, report it.

**Comment by Shadowblitz16** [comment]
There IS a issue when Godot particle animations suddenly break and a restart doesn't fix it.
I don't have the data anymore so I'm closing this.

**Comment by adamscott** [comment]
Just found this out in the documentation after taking time to test your project file.

> `AtlasTexture` cannot be used in an [AnimatedTexture](https://docs.godotengine.org/fr/stable/classes/class_animatedtexture.html#class-animatedtexture), cannot be tiled in nodes such as [TextureRect](https://docs.godotengine.org/fr/stable/classes/class_texturerect.html#class-texturerect), and does not work properly if used inside of other `AtlasTexture` resources.

In other words, setting particles H frames and V frames is subdivising an AtlasTexture, which it cannot be used as. I suggest you split the sprites file manually to isolate the frames you want. Then, use h and v frames to animate the CPUParticles2D.

**Comment by Shadowblitz16** [comment]
> Just found this out in the documentation after taking time to test your project file.
> 
> > `AtlasTexture` cannot be used in an [AnimatedTexture](https://docs.godotengine.org/fr/stable/classes/class_animatedtexture.html#class-animatedtexture), cannot be tiled in nodes such as [TextureRect](https://docs.godotengine.org/fr/stable/classes/class_texturerect.html#class-texturerect), and does not work properly if used inside of other `AtlasTexture` resources.
> 
> In other words, setting particles H frames and V frames is subdivising an AtlasTexture, which it cannot be used as. I suggest you split the sprites file manually to isolate the frames you want. Then, use h and v frames to animate the CPUParticles2D.

Ya this doesn't really seem like it's good for workflow since it requires us to edit our sprite sheets in a external image editor and reimport them. 

It would be much nicer if we could use any texture type and use endless nested textures.
