### ISSUE TITLE
[GodotPhysics] Trimesh collision kill my FPS 

### ISSUE THREAD

**Issue by Noiros** [godotengine/godot#59491]
### Godot version

4.0 alpha 5

### System information

Windows 11, GLES3, Rx 5700 XT, Ryzen 7 3600x

### Issue description

if you enter a narrow place that is colliding trimesh, fps will start to die

demonstrative video, just watch the fps at the top left:
https://www.youtube.com/watch?v=rWlTYH-SchE

### Steps to reproduce

make a hole in a mesh then, generate a trimesh collision and bring a character into it and look at your FPS

For minimal project just open the game and press up arrow.

### Minimal reproduction project

[minimal coll lag.zip](https://github.com/godotengine/godot/files/8345964/minimal.coll.lag.zip)

**Comment by Calinou** [comment]
I think this is expected, especially if your entire level is a single TriMesh collision shape (which can be *very* complex).

One solution is to add invisible barriers to prevent players from getting stuck in that kind of corner.

**Comment by Zireael07** [comment]
Dupe/related to #48587 ?

**Comment by Noiros** [comment]
> I think this is expected, especially if your entire level is a single TriMesh collision shape (which can be *very* complex).
> 
> One solution is to add invisible barriers to prevent players from getting stuck in that kind of corner. This will also make gameplay less frustrating :slightly_smiling_face: 

yes, but even in the minimal project, with simple cube with a hollow the fps dies

**Comment by yosoyfreeman** [comment]
> 

I personally don't think this is expected.  A drop while working with complex colliders is expected, but dropping to almost 0 fps in a common use case like that seems a bit exaggerated. It could be great to check if the results are similar with older versions of Godot.

**Comment by Noiros** [comment]
my game was before in 3.x and no lag appeared at these places

**Comment by Calinou** [comment]
> my game was before in 3.x and no lag appeared at these places

Did you use Bullet or GodotPhysics in 3.x?

**Comment by Noiros** [comment]
In 3.x i use Bullet (DEFAULT) and in 4.0 DEFAULT (GodotPhysics)

**Comment by Calinou** [comment]
> In 3.x i use Bullet (DEFAULT) and in 4.0 i use DEFAULT (GodotPhysics)

If you still have access to the 3.x project, can you try switching to GodotPhysics there and see if you can reproduce this issue? This would rule out any 4.0-specific regressions.

**Comment by Noiros** [comment]
I tried in the original game in 3.x and no lag, I also redid exactly the minimal project and just a small decrease of the fps at the collision

[minimal coll lag 3.x.zip](https://github.com/godotengine/godot/files/8356092/minimal.coll.lag.3.x.zip)

**Comment by fabriceci** [comment]
I retested the minimal project on both latest version, the situation seems to be a lot much better now, could you confirm @Noiros ?

Godot 4 alpha 10: 590 FPS -> 550 fps ( -~40 FPS during the collision in the hole)
Godot 3.5 rc4 (with same environment and light) : 462 FPS stable

**Comment by akien-mga** [comment]
I don't know if this was fixed, but the MRP isn't showing the issue being described.

Like @fabriceci, I have a very minimal FPS drop when triggering the collision in the hole, which is not unexpected.
I go from 570 FPS to 430 FPS. The same happens in 4.0 alpha 5 (as for the original report and 4.0 RC 5).

So I think the issue probably still exists, but it's better described and tracked in #57313.
