### ISSUE TITLE
Adding a node to a group or removing from group in Godot 4 Alpha puts an error in the output logs and doesn't update visual list.

### ISSUE THREAD

**Issue by Bitlytic** [godotengine/godot#59492]
### Godot version

v4.0.alpha4.official [f47097973]

### System information

Windows 10

### Issue description

When managing groups in a scene, if I select a node to add or remove to/from a group, it logs this to output:
` core/object/undo_redo.cpp:333 - Error calling method from signal '_group_selected': 'GroupDialog::_group_selected': Method not found.`

This also fails to update the visual list of nodes in the group until you close and reopen the `Manage Groups` window, but does actually succeed in adding the node to the group.

### Steps to reproduce

1. Switch from `Inspector` to `Node` panel in Godot Editor
2. Switch to `Groups` tab
3. Manage Groups
4. Add a group if there are none, otherwise select an existing group
5. Select a node in current scene
6. Add to group

### Minimal reproduction project

[MinimalGroupExample.zip](https://github.com/godotengine/godot/files/8346033/MinimalGroupExample.zip)

**Comment by akien-mga** [comment]
Fixed by #59497.
