### ISSUE TITLE
Zoom in/out shortcuts not working

### ISSUE THREAD

**Issue by bryanrieger** [godotengine/godot#59519]
### Godot version

v4.0.alpha5.official [d7d528c15]

### System information

macOS 12.3 MacBook Pro w/M1 Pro, 32GB

### Issue description

Zoom in/out (⌘ command + '=', ⌘ command + '-') shortcuts don't work, while ⌘Command + '1' (100%) works as expected.

### Steps to reproduce

Attempt to zoom in/out using the shortcut keys.

**Comment by Calinou** [comment]
@bryanrieger Do the same shortcuts work in 3.4.4?

**Comment by bryanrieger** [comment]
> @bryanrieger Do the same shortcuts work in 3.4.4?

Yup.

**Comment by EricEzaM** [comment]
It may be solved by https://github.com/godotengine/godot/pull/59468
You can try downloading the build artifact and see if it works. 
https://github.com/godotengine/godot/actions/runs/2034530249
