### ISSUE TITLE
Godot 4 alpha 5 rmb menus stopped accepting clicks

### ISSUE THREAD

**Issue by mlepage** [godotengine/godot#59532]
### Godot version

Godot 4 alpha 5

### System information

Windows 11

### Issue description

Using Godot 4 alpha 5 for the first time, new project, just world scene (2D tilemap) and player scene (sprite).

After about an hour, the rmb menus stopped working. They show, but clicks go through them.

E.g. if I right click on a node to rename it, it doesn't rename, the click goes through to the scene tree underneath the menu.

### Steps to reproduce

Not sure, this was basic initial usage of the engine, it just started happening, sorry. I didn't see any dialogs or warnings or errors.

**Comment by KoBeWi** [comment]
Could be related to #59287 maybe.

**Comment by mlepage** [comment]
Just happened again. I suspect something to do with focusing out of Godot into another window (e.g. browser) and then returning to Godot.

**Comment by KoBeWi** [comment]
Closing in favor of #61758, which is the same issue, but a bit more clear.
