### ISSUE TITLE
Change of the blending Skeleton3D bone rotations from 3.x makes confuse

### ISSUE THREAD

**Issue by macryc** [godotengine/godot#59536]
### Godot version

4.0 alpha 5

### System information

Win10, GLES3, RTX 2070 mobile

### Issue description

When adding animations in animation blend tree (via Add2/Add3 node) some bones rotate incorrectly and end up in weird positions after the animation is fully added.
Watch this vid. I am adding a back crawl animation to a forward crawl. In both, the legs should be trailing behind the torso, yet the right leg is twisting oddly as if it was either unaffected by the Add operation, or incorrectly affected.
I was able to replicate this issue with different animation Adds and a different bone is affected by this issue each time

https://user-images.githubusercontent.com/82995330/160230168-773f96df-f77d-4676-b8ca-7a0721c94a57.mp4

.

### Steps to reproduce

Start a 3d scene
Import a Mixamo (or other) skleleton with at least 2 animations 
add a AnimationTree
create new AnimationNodeBlendTree
add a Add2 and connect the 2 animations
slide the add amount to see smooth adding

**Comment by TokageItLab** [comment]
NodeAdd had been working strangely since 3.x to begin with and made confusion #37661. Now that the blending algorithm has changed in 4.0, I think it needs to be corrected correctly.

**Comment by TokageItLab** [comment]
@macryc By the way, do you have a comparison video with 3.x? To begin with, 4.0 includes rest in the pose, so additive animation must be extracted by some means. (Ref: https://github.com/godotengine/godot-proposals/issues/2700)
In other words, the 4.0 add will apply rest twice if the same animation as in 3.x is used without modification.

**Comment by macryc** [comment]
> @macryc By the way, do you have a comparison video with 3.x? To begin with, 4.0 includes rest in the pose, so additive animation must be extracted by some means. (Ref: [godotengine/godot-proposals#2700](https://github.com/godotengine/godot-proposals/issues/2700)) In other words, the 4.0 NodeAdd will apply rest twice if the same animation as in 3.x is used without modification. So the above video looks like a bug but may be the correct behavior...

This issue was introduced in Godot 4 alpha 5. It didn't exist in alpha 4. So it's not a Godot 3.x vs Godot 4 thing. Rather, it looks like it could have been introduced unintentionally while fixing the root bone bug?

**Comment by macryc** [comment]
For comparison, this is the exact same scene in Godot 4 alpha 4. Works fine here.
https://user-images.githubusercontent.com/82995330/160231497-f72fb17d-bc3f-4ab0-bdb9-aefb73ef71a4.mp4

**Comment by TokageItLab** [comment]
@macryc The blend method changed in alpha 5 should probably add animations with NodeAdd correctly. As we have added in the past with https://github.com/godotengine/godot/issues/37661#issuecomment-615510819 and https://github.com/godotengine/godot/pull/34134#issuecomment-763752698, they will add correctly if the inconsistencies in the blend order are removed.

In other words, in the previous inconsistent blends, NodeAdd and NodeBlend behaved almost identically.

**Comment by macryc** [comment]
You can see from the vids that the issue is affecting one bone. It affects different bones with each Add - it's difficult to see a pattern here. It's inconsistent and results in unpredictable behavior which makes Add operations quite unusable, at least for skeletons.

**Comment by TokageItLab** [comment]
It is obvious. I say again, in order to perform correct addition in Godot 4, one must at least extract the additive animation https://github.com/godotengine/godot-proposals/issues/2700. However, the ability to extract additive animation has not yet been implemented, so after it is added, the behavior of NodeAdd must be normalized. (In Godot 3, all animations were implicitly imported as Additive Animations.)

**Comment by macryc** [comment]
Alright, thanks.
I think the issue is obvious by now but just in case, here's another occurrence. This one shows the issue more clearly, I think. Adding (blending, in this case, but the root cause is the same) an aiming animation to a walking_with_rifle animation. The left forearm bone rotates at the root as opposed to simply blend into the aiming animation: 
https://user-images.githubusercontent.com/82995330/160235996-054096c4-73b3-4445-9a6a-c3efa5a2982d.mp4

**Comment by macryc** [comment]
> ~It is obvious. I say again, in order to perform correct addition in Godot 4, at first, one must at least extract the additive animation [godotengine/godot-proposals#2700](https://github.com/godotengine/godot-proposals/issues/2700). However, the ability to extract additive animation has not yet been implemented, so after it is added, the behavior of NodeAdd should be fixed. (In Godot 3, all animations were implicitly imported as Additive Animations.)~
> 
> Sorry, I correct my misunderstand above, for Additive Animation it was extracted by init_lot/rot/scl in BlendTree. However, I just tested it and it was adding correctly in my environment.
> 
>  2022-03-26.19.50.10.mov 
> @macryc Can you send a sample project of a broken case?

I will post it in a bit. But clearly, in your vid at 0:08 the hands are gone completely awry when adding the running anim...

**Comment by TokageItLab** [comment]
@macryc Please make sure it is not due to the optimizer, just to be sure. If one of the animation tracks is missing, the animation will be blended with the rest.

**Comment by macryc** [comment]
[4_alfa4_FPS - add issue.zip](https://github.com/godotengine/godot/files/8355228/4_alfa4_FPS.-.add.issue.zip)
here's the project. Go to 'crawler' scene, open the animation tree and slide the Add2 node called 'problem'.

**Comment by TokageItLab** [comment]
@macryc I tested the sample project and the animations definitely seemed to add animations correctly.
The behavior of NodeAdd is like rotating an elbow 90deg and then rotating the elbow another 90deg. The correct behavior is that when large animations are added to each other, the bones may break.

**Comment by macryc** [comment]
I understand it's behaving as intended, but my point is that the intention is incorrect for many reasons:
1. you can't expect users to only be blending/adding simple animations
2. sequential adding/blending as you described will always result in unwanted/unpredicted bone positions, like in my aiming example where the end state seems to be correct but on they way to that end state there is unwanted elbow rotation occurring (and this is a very simple blend)

So what are the plans? Is this going to be addressed?

**Comment by TokageItLab** [comment]
@macryc The problem with your uploaded arms appears to be simply a quaternion interpolation problem. Is that not complemented by the shortest distance? Can you send a sample project?

**Comment by macryc** [comment]
> @macryc The problem with your uploaded arms video seems to be simply a quaternion interpolation problem. Is that not complemented by the shortest distance? Can you send a sample project?

OK but how do I solve this 'quaternion interpolation problem'? As you can see in the vid I'm simply blending 2 animations.
I will try and extract this but the project (and my animation tree) is massive...

**Comment by TokageItLab** [comment]
@macryc AnimationBlend is not allowed to rotate more than 180 degrees with reference to rest. Please make sure that there is no unreasonable rotation of the elbow.

> you can't expect users to only be blending/adding simple animations

Need to explain actual use cases for approving. Animation blending and addition are based on pure mathematics and nothing more. There are plans for retargeting and IK improvements in the meantime, but AnimationTree will have little to no further role in that.

**Comment by macryc** [comment]
Here's the player scene. It's obviously not built for sharing so you will see the anim tree is a bit messy.
Find the Blendnode called 'gun righclick aiminig' and scroll the slider to see how the left elbow rotates all over the place before it reaches the correct position. This should be a smooth blend.
[ThePlayer_extract.zip](https://github.com/godotengine/godot/files/8355315/ThePlayer_extract.zip)
.

**Comment by TokageItLab** [comment]
@macryc I can't open it and determine the cause since it only contains tscn. But I think probably there is a problem with the T-pose and the actual bones that are being rotated.

**Comment by macryc** [comment]
[ISSUE DEMO.zip](https://github.com/godotengine/godot/files/8355376/ISSUE.DEMO.zip)
Sorry forgot to add the animations. Try this.

Btw, why would the Tpose suddenly be a problem? It's a Mixamo import.

**Comment by macryc** [comment]
> Need to explain actual use cases for approving. Animation blending and addition are based on pure mathematics and nothing more. There are plans for retargeting and IK improvements in the meantime, but AnimationTree will have little to no further role in that.

On this. One huge use case is mocap animations like Mixamo. Most 3d games made in Godot use them. If we can't add/blend those imported anims in Godot then that will be a deal breaker for the community. So the math behind add/blend will definitely need to be improved.

**Comment by TokageItLab** [comment]
@macryc Your model's rest is not T-pose.

<img width="585" alt="スクリーンショット 2022-03-26 21 38 43" src="https://user-images.githubusercontent.com/61938263/160242598-2800efcb-4822-46b9-8b36-73cb5a79b32c.png">

Disable AnimationTree, play the t-pose and click "apply all poses to rest," then clear the AnimationTree cache (restarting Godot is a sure way to do this) and try blending again.

https://user-images.githubusercontent.com/61938263/160242886-88f493a0-1888-4ee3-a48d-d0de1cf47d93.mov

[ISSUE DEMO_fixed.zip](https://github.com/godotengine/godot/files/8355566/ISSUE.DEMO_fixed.zip)

As I have said many times before, the rotation of the blend is based on rest, so the model needs to be imported in a pose that is as close as possible to the middle of the range of motion for all joints https://github.com/godotengine/godot/pull/57675#issuecomment-1037668326. This is similar to the reason Unity's Humanoid does bike poses. This is not a reason why motion capture data cannot be used, as it only sets the correct model rest. And that is the role of the importer, not BlendTree's role.

**Comment by TokageItLab** [comment]
@Zireael07 The animation team plans to implement a T-poser as a post-process importer. However, I agree with you that we need to detect the pose closest to the T-pose/Apose before we can force the T-pose to be generated.
cc @fire @lyuma @SaracenOne

**Comment by macryc** [comment]
> In other words, the 4.0 NodeAdd will apply rest twice if the same animation as in 3.x is used without modification. So the above video looks like a bug but may be the correct behavior...

@TokageItLab can you explain this a little more? Does this mean that 4.0 additive animation adds its rotations on top of the base animation's current rotation? Trying to understand what's initial vs. rest pose (i believe this is the bone's pose in Tpose) and pose (actual current pose vs. rest pose). And what's actually being added and to what...?

**Comment by TokageItLab** [comment]
@macryc I was misunderstood about that and have already corrected it here. https://github.com/godotengine/godot/issues/59536#issuecomment-1079658125

However, if your model does not have a rest (a model where all bones meet at the origin with InitPose), the base pose will be added twice. In short, the difference from InitPose will be added.

**Comment by macryc** [comment]
@TokageItLab What I'm trying to understand is the difference between a bone's initial pose and rest pose.
I thought that initpose was simply a pose without rotations (quat(0,0,0,1)) and rest pose was te pose as per the model's T-pose (which is almost always rotated ve. initpose).
Is this correct?

**Comment by TokageItLab** [comment]
@macryc I mean InitPose is one of the functions that can be selected from the viewport options when the Skeleton is selected.

<img width="424" alt="スクリーンショット 2022-03-31 14 41 27" src="https://user-images.githubusercontent.com/61938263/160984381-99be04fd-dc76-47b2-bfde-2dea1db43cd2.png">

Using it, all bones of the model will be rest pose, and NodeAdd will add the differences from the rest pose to each other.›
