### ISSUE TITLE
MeshInstance3Ds casts shadows onto their Visibility Parent

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot#59538]
### Godot version

4.0.alpha5

### System information

Windows 10, Core i7 5820k, GeForce 980TI

### Issue description

When using visibility parent and fading, the low lod object will cast shadows on the high lod object during the fade.

![Godot_v4 0-alpha5_win64_GfBaUGZTem](https://user-images.githubusercontent.com/4955051/160232668-7b2858fc-0f53-4f48-a786-2a3094e3b30f.gif)

Would it be possible for the lod variations not to cast shadows onto each other during the fade?

### Steps to reproduce

1. Create a new scene with a MeshInstance3D, set the mesh to a cube and it's visibility begin range to 10 and it's begin margin to 1. Set it's fade mode to self.
2. Create another MeshInstance3D, set it's mesh to a sphere and set it's visibility parent to the cube.
3. Move back and forth to see the issue when fading between the two.

OR: Open the attached project and move closer and farther away from the object to see the issue.

### Minimal reproduction project

[HLODTests.zip](https://github.com/godotengine/godot/files/8355052/HLODTests.zip)

**Comment by Arnklit** [comment]
After some more thought on this, I assume it wouldn't  be possible to only apply some objects shadows to some objects as they are all rendered in a single shadow map. I'm guessing shadow bias will normally solve this issue when the lod models are more similar in shape?

Closing.

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot/issues/55367, which could partially alleviate this issue by rendering shadows less often.
