### ISSUE TITLE
how to add new font to editor font

### ISSUE THREAD

**Issue by 2dogtwo** [godotengine/godot#59533]
### Godot version

3.4.4

### System information

debian10 linux aarch64

### Issue description

I don't know English, so the following text description comes from online translation. If there is any mistake, I'll say sorry first.
I installed debian10 with proot of Android phone and successfully compiled Godot of arm64. Later, when I operated with VNC, I found that all text input places of Godot Editor could not receive Chinese characters from Android system input method well. Some could be displayed and some could not. Then I wanted to use the input method in Debian system to solve the problem, but I found that the input method could not be enabled at all. I tried the Google input method of IBus Pinyin and fcitx, but the Chinese input method could not be enabled. I don't know whether it's a system problem or a Godot problem. Input methods can be used normally in other linux software.
Therefore, there are two ways to solve the problem. One is to add new fonts to support text from Android input method, but I don't know what to do. The other is to enable Chinese input method for Godot.

### Steps to reproduce

![S20326-09414790](https://user-images.githubusercontent.com/86821334/160220255-b85615a4-e45b-4226-a4e2-dab6a0af8683.jpg)
![S20326-09420525](https://user-images.githubusercontent.com/86821334/160220257-0e9016db-9d8f-4473-95df-ae0c2526ac8d.jpg)

**Comment by Calinou** [comment]
IME support on Linux requires https://github.com/godotengine/godot/pull/53682 to be merged first.
