### ISSUE TITLE
AnimationTree gets confused when the root node of AnimationPlayer is changed.

### ISSUE THREAD

**Issue by darthLeviN** [godotengine/godot#59549]
### Godot version

3.4.3

### System information

Ubuntu 20.04.3 LTS, GLES 2, Nvidia 740m

### Issue description

After you change the root node of a `AnimationPlayer` , `AnimationTree` gets confused and no longer produces any result.
it seems to lose the control of the AnimationPlayer or something. clearing caches and queues of the `AnimationPlayer` solves nothing.

my guess is there needs to be a function to flush the animation tree caches and stuff. but i **found no such thing**. 
.calling request_ready() after changing the tree root **did not** work
.deactivating the animation tree, setting it's anim_player to "", waiting few frames and seeing it back to the AnimationPlayer **did not** help.

edit : after more testing, using different animation players and changing `anim_tree` seems to show similar issues. not sure if the behaviour is the same, but the issue persists. seems like AnimationTree really needs a flush/reset mechanism. for now i'm just gonna use different animation trees and have only one active at a time.

### Steps to reproduce

Create an animation player, create an animation tree, make sure you have a secondary root node for your animation player and then change the root node to the secondary at runtime.

### Minimal reproduction project

[animation tree bug.zip](https://github.com/godotengine/godot/files/8355705/animation.tree.bug.zip)

**Comment by TokageItLab** [comment]
Indeed, the timing of when the AnimationTree's BlendCache is flushed is quite limited. I have to restart Godot or reopen the scene every so often for that reason...
