### ISSUE TITLE
Scons VS compiler not found with VS 2022

### ISSUE THREAD

**Issue by bucket91** [godotengine/godot#59541]
### Godot version

3.3.3

### System information

Windows 10

### Issue description

Software details:
Scons 3.1.2
Visual Studio 2022 (2019 only available for mac)
python 3.7 and 3.8
Godot 3.3.3

Note:
I installed VS in a different drive and my main target is to export for android with plugins.

Issue:
when ever I type scons in my cmd this blob appears

scons: Reading SConscript files ...

scons: warning: No version of Visual Studio compiler found - C/C++ compilers most likely not set correctly
File "E:\godot-3.3.3-stable_master\godot-3.3.3-stable\SConstruct", line 3, in <module>

scons: warning: No version of Visual Studio compiler found - C/C++ compilers most likely not set correctly
File "E:\godot-3.3.3-stable_master\godot-3.3.3-stable\SConstruct", line 67, in <module>
Automatically detected platform: windows
Configuring for Windows: target=debug, bits=default
Using MinGW
Couldn't parse CXX environment variable to infer compiler version.
YASM is necessary for WebM SIMD optimizations.
WebM SIMD optimizations are disabled. Check if your CPU architecture, CPU bits or platform are supported!
TypeError: argument of type 'ListAction' is not iterable:
  File "E:\godot-3.3.3-stable_master\godot-3.3.3-stable\SConstruct", line 647:
    SConscript("modules/SCsub")
  File "c:\users\dell\appdata\local\programs\python\python37\lib\site-packages\scons\SCons\Script\SConscript.py", line 660:
    return method(*args, **kw)
  File "c:\users\dell\appdata\local\programs\python\python37\lib\site-packages\scons\SCons\Script\SConscript.py", line 597:
    return _SConscript(self.fs, *files, **subst_kw)
  File "c:\users\dell\appdata\local\programs\python\python37\lib\site-packages\scons\SCons\Script\SConscript.py", line 286:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "E:\godot-3.3.3-stable_master\godot-3.3.3-stable\modules\SCsub", line 26:
    env.split_lib("modules", env_lib=env_modules)
  File "E:\godot-3.3.3-stable_master\godot-3.3.3-stable\methods.py", line 398:
    if "-Wl,--start-group" in env["LINKCOM"] and "-Wl,--start-group" in env["SHLINKCOM"]:

### Steps to reproduce

try to export android game with plugins

**Comment by akien-mga** [comment]
You should update your SCons version to the latest release which supports VS 2022.

**Comment by bucket91** [comment]
yes I tried that but then godot doesn't recognize scons
after reading the sconscript it says no module named "scons"

**Comment by akien-mga** [comment]
That means SCons was not installed properly and is not in PATH. How did you install it?

**Comment by bucket91** [comment]
I installed it with pip
note: I installed VS in E:/ instead of c:/..../program files

**Comment by bucket91** [comment]
Problem solved! 
similar issue solved in [https://godotengine.org/qa/66758/scons-doesnt-find-the-visual-studio-compiler](url)

**Comment by bucket91** [comment]
Nope, still doesn't work!
I have installed VS in /program files (x86) 
Can anyone suggest me other solutions?
Might it be a problem with VS 2022?
Any help would ne appreciated,
thanks in advance!

**Comment by Calinou** [comment]
It might be worth checking if the `master` branch can build with Visual Studio 2022, but I don't think it currently does.
