### ISSUE TITLE
Wrong translation in italian language for AnimationPlayer node key options

### ISSUE THREAD

**Issue by alecas93** [godotengine/godot#59559]
### Godot version

3.4.3.stable.official

### System information

Xubuntu 21.10, GLES 3

### Issue description

![Istantanea_2022-03-26_19-14-48](https://user-images.githubusercontent.com/72086642/160252170-88fb2fa9-e2df-498c-b94b-98f09926213b.png)
The translation should be "Maschera di traslazione per inserimento chiavi."

### Steps to reproduce

Set Godot language to Italian and create an AnimationPlayer node

**Comment by Calinou** [comment]
Translations are managed on Weblate, so I would recommend fixing the translation there: https://hosted.weblate.org/projects/godot-engine/godot/it/

The translation update will land in future Godot releases.

**Comment by alecas93** [comment]
Oh ok thanks, I didn't know it but I think (hope) I just corrected it
