### ISSUE TITLE
node.get_name() from every Richtextlabel is not the text in my scene and get_class() = nil

### ISSUE THREAD

**Issue by NeroNekro** [godotengine/godot#59563]
### Godot version

3.4.4

### System information

macOS 12.3

### Issue description

Hello,

when I normally call get_name for a node, I get the name entered in the scene. With RichtextLabel I only get a @@ and a number (@@1). Furthermore, I do not get a return value when I call get_class().

Shouldn't the name be output by RichtextLabel or is that an error?

```py
translate_tree(get_tree().get_root())
func translate_tree(node):
		for N in node.get_children():
			if N.get_child_count() > 0:
				#print("["+N.get_name()+"]")
				self.translate_tree(N)
			else:
				print("- "+N.get_name())
				print(N.get_class())
```

Output example:
Node
- TextureRect
TextureRect
- img
TextureRect
- Sprite
Sprite
- ColorRect
ColorRect
- @@5
VScrollBar
- btn_last_cat
Button
- @@6
Timer
- @@7
Timer
- @@8
Timer
- TextureRect

### Steps to reproduce

Create a Richtextlabel in your scene
use the function node.get_class() or node.get_name()

### Minimal reproduction project

[_Link_](https://drive.google.com/file/d/1oOeQ-zgLTimmdwlTeEwGGiUjvlYwCNJ4/view?usp=sharing)

**Comment by Calinou** [comment]
@NeroNekro Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

Also, remember that RichTextLabel has an internal ScrollContainer node as a child.

**Comment by sent44** [comment]
The `translate_tree()` function print the deepest child nodes. If uncomment that print line, `RichTextLabel` will appear.

**Comment by NeroNekro** [comment]
> The `translate_tree()` function print the deepest child nodes. If uncomment that print line, `RichTextLabel` will appear.

Yes, my fault. I did not think about it.
