### ISSUE TITLE
[4.0] Directories containing `project.godot` are not shown in dialogues.

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#59578]
### Godot version

v4.0.alpha.calinou.f0407ad14

### System information

Linux, Nvidia 1650GTi, Vulkan

### Issue description

Here is an example open dialogue:
![Directory_Missing](https://user-images.githubusercontent.com/324679/160280901-2e3d028f-6811-42f5-91c8-4345f156a8f4.png)

There is a directory missing from here, `Source`. It's not showing up. Any directory with `project.godot` inside it does not show up; typing the directory name will still take you there.

### Steps to reproduce

Try to import/edit a project. May happen with other related (non-`res://`) dialogues.

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
This is not a bug, `project.godot` denotes another project and they are ignored on purpose.
If it wasn't like that before, likely #46638 changed it.

**Comment by Sslaxx** [comment]
I assume that it is intended for if the projects are already listed in the project manager. That was not the case here - these projects were *not* listed there and the directories were not showing.

**Comment by KoBeWi** [comment]
Ah if it happens in Project Manager then it's a bug. The folders are supposed to be filtered only in editor.

**Comment by akien-mga** [comment]
CC @Ev1lbl0w - we seem to be a bit too thorough in the results we filter out, as indeed folders with `project.godot` need to be visible for the "Import" / "Scan" dialogs in the Project Manager.
