### ISSUE TITLE
Release builds of project breaks a node-based state machine

### ISSUE THREAD

**Issue by souplamp** [godotengine/godot#59570]
### Godot version

4.0.alpha4

### System information

Windows 10, Vulkan

### Issue description

Implemented a node-based state machine in Godot 4.0 alpha4. It switches states as intended on debug builds, **but it doesn't work on release builds.**

I can't identify what exactly was causing this in a larger project; attached is a recreation with as few moving parts as possible for simplicity if someone could help me identify the cause.

**How It Works:**
Player node has a script, whose "_input" function will call a child node (called "state machine") function similarly called "input". This state machine node acts as a gate between its two children, "first" and "second", which both have their own "input" functions. Check the state machine's script for more details, but the simple explanation is that it flips between two node references for first and second nodes. Whatever the active state is, state machine passes the InputEvent from the player script down to the active state.
This functionality is used for switching. Both states' input functions will wait for the player to press the [tab] key. Once pressed, it returns the reference to the _other_ state. If you're in "first" and hit tab, it goes to "second", and vise versa.

**As @Calinou pointed out, this is related to #59239. I've tested the node references, and they're valid until you try to return them. It seems return is broken for any object type.**

### Steps to reproduce

Please see the attached MIP.

### Minimal reproduction project

[State Machine.zip](https://github.com/godotengine/godot/files/8356581/State.Machine.zip)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/59239.

**Comment by souplamp** [comment]
The references are only breaking when they're returned, so this is definitely the same issue. Closing as duplicate. Thank you Calinou :)
