### ISSUE TITLE
GDScript 2.0: ERROR: Parser bug (please report): tried to assign unset node without an identifier.

### ISSUE THREAD

**Issue by bruce965** [godotengine/godot#59581]
### Godot version

v4.0.alpha5.official.d7d528c15

### System information

Windows 10, Vulkan API 1.2.176 - Using Vulkan Device #0: AMD - AMD Radeon(TM) Graphics

### Issue description

Parser bug

### Steps to reproduce

```gdscript
extends Node

func get_at(x: int, y: int):
	return 0

func set

# test
func _init(data: PackedByteArray = PackedByteArray()):
	super()
```

As soon as I type an underscore after `func set`, Godot crashes with error:

```
ERROR: Parser bug (please report): tried to assign unset node without an identifier.
   at: resolve_class_interface (modules/gdscript/gdscript_analyzer.cpp:656)
```

### Minimal reproduction project

[crash_in_v4.0.alpha5.official.d7d528c15.zip](https://github.com/godotengine/godot/files/8357826/crash_in_v4.0.alpha5.official.d7d528c15.zip)

**Comment by Salvakiya** [comment]
you also get this error message when doing this

![image](https://user-images.githubusercontent.com/6888784/164756496-9217e4f4-869b-45a5-9624-f2ac90cdada6.png)

**Comment by Chaosus** [comment]
@bruce965 I cannot reproduce this issue at alpha 7:

![image](https://user-images.githubusercontent.com/3036176/165938598-ca906fc6-b014-4ffa-a5fd-414ec26e578d.png)

Maybe it's fixed, can you check it again?

**Comment by bruce965** [comment]
@Chaosus It doesn't crash for me either anymore on alpha 7.
Thank you for the reminder!
