### ISSUE TITLE
(4.0) Sky Shader doesn't recognize COLOR attribute

### ISSUE THREAD

**Issue by paddy-exe** [godotengine/godot#59593]
### Godot version

v4.0.alpha.custom_build [fec248699]

### System information

Win10, AMD - Radeon RX 580 Series

### Issue description

A simple Sky shader doesn't recognize the COLOR attribute. The default shader of ProceduralSkyMaterial works perfectly fine on the other hand.

Error log:
```
Vulkan API 1.2.0 - Using Vulkan Device #0: AMD - Radeon RX 580 Series

    1 |
    2 |
    3 | shader_type sky;
    4 |
    5 | void fragment() {
E   6->         COLOR = vec3(1.0, 1.0, 1.0);
    7 | }
    8 |
SHADER ERROR: Unknown identifier in expression: 'COLOR'.
          at: (null) (:6)
ERROR: Shader compilation failed.
   at: (servers\rendering\renderer_rd\renderer_scene_sky_rd.cpp:96)
ERROR: Condition "!version" is true. Returning: RID()
   at: ShaderRD::version_get_shader (C:\Users\Patrick\Documents\Coding\GameDev\GodotDev\godot-builds\godot\servers/rendering/renderer_rd/shader_rd.h:140)
```

I also tried the example Sky shader from the [documentation ](https://docs.godotengine.org/en/latest/tutorials/shaders/shader_reference/sky_shader.html?highlight=Sky)with the same result:
```
shader_type sky;

void fragment() {
    if (AT_CUBEMAP_PASS) {
        // Sets the radiance cubemap to a nice shade of blue instead of doing
        // expensive sky calculations
        COLOR = vec3(0.2, 0.6, 1.0);
    } else {
        // Do expensive sky calculations for background sky only
        COLOR = get_sky_color(EYEDIR);
    }
}
```

### Steps to reproduce

1. Open Minimal reproduction project
2. Open shader file called Testshader.gdshader

### Minimal reproduction project

[StylizedSkyShader.zip](https://github.com/godotengine/godot/files/8358178/StylizedSkyShader.zip)

**Comment by clayjohn** [comment]
Sky shaders don't have a ``fragment()`` processor function. Their main function is ``sky()``. In your code replace ``fragment`` with ``sky`` and it should work.

**Comment by paddy-exe** [comment]
@clayjohn The documentation still gives the examples with all the shader code in a fragment function though. Just wanted to inform you so it can get updated accordingly

**Comment by clayjohn** [comment]
Thanks! I've made a bug report in the docs-repo so we can track this issue there.
