### ISSUE TITLE
Using If inside of While Freezes

### ISSUE THREAD

**Issue by CatastrophicDino** [godotengine/godot#59609]
### Godot version

3.4.4

### System information

Windows 10, GLES2, Intel Core i5-3330

### Issue description

My code to get all images in a Directory doesn't work as using If inside of While freezes the game

`func dir_contents(path):

	var dir = Directory.new()
	dir.open(path)
	dir.list_dir_begin()
	var file_name = dir.get_next()
	while file_name != "":
		if file_name.ends_with("png") == true:
			print(file_name.trim_suffix(".png"))
			#add_item(file_name.trim_suffix(".png"), load(file_name))
			file_name = dir.get_next()`

This happens in both the Debug and the Main Build

### Steps to reproduce

while Value == Condition:*
     If AnotherValue == Condition:*
          Thing.doSomething()
          print("Did Something")

**Comment by Haydoggo** [comment]
Looks like this is a bug in your code rather than in the engine. You've put `file_name = dir.get_next()` inside of your `if` statement, so if `file_name` ever does _not_ end with "png", `file_name` will never be updated, and your `while` loop will never exit, resulting in your program freezing.

**Comment by CatastrophicDino** [comment]
Ah, I skipped past that when reviewing, thanks!
