### ISSUE TITLE
Cannot update shader global uniform in runtime

### ISSUE THREAD

**Issue by corintho** [godotengine/godot#59645]
### Godot version

v4.0.alpha5.official [d7d528c15]

### System information

MacOS 12.2.1; Intel UHD Graphics 630 1536 MB

### Issue description

I declared a shader global uniform color and I expected to be able to change it during runtime, but I can't.

I am currently trying to update it using `ProjectSettings.set_setting`, but the value it not updated during runtime.

I expected it to reflect the new value in the shader after setting it.

### Steps to reproduce

The attached project has a main scene with a script attached to it, that changes the global uniform color to GREEN. But the plane is still rendered with the RED color, from the initial settings in the project

### Minimal reproduction project

[global_uniform_test.zip](https://github.com/godotengine/godot/files/8366232/global_uniform_test.zip)

**Comment by Calinou** [comment]
> I am currently trying to update it using ProjectSettings.set_setting, but the value it not updated during runtime.

Most project settings are only read when the project starts. You probably need to use something else to change them at run-time.

I see a ShaderGlobalsOverride node, but it doesn't have any exposed methods or properties.

**Comment by corintho** [comment]
@Calinou thanks for the information.
I was able to track it down through that Node, and in code it can be done using `RenderingServer.global_variable_set`
I just tested it and it works as expected
Not sure if this bug is still valid, since it is not possible to do it using a Node, although I do not know if that is intended.
Or if it is just more documentation needed
