### ISSUE TITLE
Vulkan: Rendering Issues on AMD GPU

### ISSUE THREAD

**Issue by ellogwen** [godotengine/godot#59640]
### Godot version

4.0alpha5

### System information

AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (8) @ 2.100GHz
Tried with Wayland and Xorg

### Issue description

I have a lot of rendering issues all over the place, using the alpha5 of godot 4. Even in an empty project with just a window control (see screenshot where there are render artefacts in an empty window control)
Sometimes it's on a control, sometimes on parts of the spatial viewport, or the file picker.

![image](https://user-images.githubusercontent.com/22261975/160454285-54f203ba-e769-46d1-be83-b9501167014f.png)

Sometimes I have crashes, sometimes just warnings

```
Godot Engine v4.0.alpha5.official.d7d528c15 - https://godotengine.org
WARNING: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
	loader_scanned_icd_add: Driver /usr/lib/libvulkan_radeon.so supports Vulkan 1.2, but only supports loader interface version 4. Interface version 5 or newer required to support this version of Vulkan (Policy #LDP_DRIVER_7)
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 124482176
     at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:156)
WARNING: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
	loader_scanned_icd_add: Driver /usr/lib/libvulkan_intel.so supports Vulkan 1.2, but only supports loader interface version 4. Interface version 5 or newer required to support this version of Vulkan (Policy #LDP_DRIVER_7)
```

Sometimes it crashes with errors in the console
```
ERROR: Condition "_first != nullptr" is true.
   at: ~List (./core/templates/self_list.h:106)
ERROR: Condition "_first != nullptr" is true.
   at: ~List (./core/templates/self_list.h:106)
ERROR: 3 shaders of type SceneForwardClusteredShaderRD were never freed
   at: ~ShaderRD (servers/rendering/renderer_rd/shader_rd.cpp:702)
ERROR: Condition "_first != nullptr" is true.
   at: ~List (./core/templates/self_list.h:106)
ERROR: 15 RID allocations of type 'N17RendererStorageRD4MeshE' were leaked at exit.
ERROR: Condition "_first != nullptr" is true.
   at: ~List (./core/templates/self_list.h:106)
ERROR: 12 RID allocations of type 'N17RendererStorageRD8MaterialE' were leaked at exit.
ERROR: 3 RID allocations of type 'N17RendererStorageRD6ShaderE' were leaked at exit.
WARNING: 12 RIDs of type "UniformBuffer" were leaked.
     at: _free_rids (drivers/vulkan/rendering_device_vulkan.cpp:9098)
WARNING: 3 RIDs of type "IndexArray" were leaked.
     at: _free_rids (drivers/vulkan/rendering_device_vulkan.cpp:9098)
WARNING: 3 RIDs of type "IndexBuffer" were leaked.
     at: _free_rids (drivers/vulkan/rendering_device_vulkan.cpp:9098)
WARNING: 15 RIDs of type "VertexBuffer" were leaked.
     at: _free_rids (drivers/vulkan/rendering_device_vulkan.cpp:9098)
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: cleanup (core/object/object.cpp:1988)
ERROR: Resources still in use at exit (run with --verbose for details).
   at: clear (core/io/resource.cpp:479)
```

### Steps to reproduce

-

### Minimal reproduction project

[RenderIssues.zip](https://github.com/godotengine/godot/files/8365014/RenderIssues.zip)

Edit: Github upload did fail, I upload it again
[Uploading RenderIssues.zip…]()

**Comment by Calinou** [comment]
Which Linux distribution version are you using? If you're using an old kernel/Mesa version, I recommend upgrading to a newer distribution version or looking for newer versions using third-party repositories.

**Comment by ellogwen** [comment]
I am using: Kernel 5.10.105-1-MANJARO

**Comment by clayjohn** [comment]
Are you still experiencing this issue with Beta14?

If so, can you try updating to newer drivers? It sounds like you are using drivers from 2018 which are likely a little bit too out of date

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
