### ISSUE TITLE
Editor closes immediately on startup

### ISSUE THREAD

**Issue by GTcreyon** [godotengine/godot#59642]
### Godot version

v3.4.4.stable.official.419e713a2

### System information

Windows 10

### Issue description

Sometimes, the editor closes itself immediately on startup (before the splash screen or project list appears). Once this happens, it will continue to do this on all subsequent startups until the computer is restarted. There is no output to the console other than ```Godot Engine v3.4.4.stable.official.419e713a2 - https://godotengine.org```. This does not change when running Godot from command line, nor as administrator, nor with the --verbose argument.

### Steps to reproduce

Open Godot_v3.4.4-stable_win64.exe. Sometimes, this will occur. I don't know when or why.

**Comment by Calinou** [comment]
Do you have a project saved within the same folder as the editor binary? If so, this will cause the project to be run instead of opening the editor.

**Comment by GTcreyon** [comment]
No, I don't. The folder is empty aside from the executable and the .cmd file that came with it. It's a freshly-extracted zip.

Note that this has happened on previous versions too. This isn't 3.4.4-specific. I should've mentioned that before, apologies.

**Comment by Calinou** [comment]
Which GPU model do you have? Do you have a laptop with hybrid graphics (NVIDIA Optimus/AMD Enduro) or a desktop with multiple GPU outputs in use?

**Comment by GTcreyon** [comment]
I don't entirely understand what that means, sorry; I'm more or less hardware-illiterate. I have a desktop with two monitors, if that helps.

**Comment by Calinou** [comment]
> I don't entirely understand what that means, sorry; I'm more or less hardware-illiterate. I have a desktop with two monitors, if that helps.

Try the following steps:

- Press <kbd>Windows + R</kbd> key combination.
- Enter `dxdiag` in the Run dialog that appears and press <kbd>Enter</kbd>.
- Accept the driver signature check.
- Wait a few seconds for the DXDiag dialog to appear, then go to its **Display** tab.
- Look at the name of graphics adapter and paste it here.

**Comment by GTcreyon** [comment]
![image](https://user-images.githubusercontent.com/67928545/160488103-87303882-387c-46c1-8761-9ae92e40f9fa.png)
Is this what you mean?

**Comment by GTcreyon** [comment]
They're both connected to the GPU, yes.

**Comment by GTcreyon** [comment]
I have not experienced this in 3.5.x.

**Comment by Calinou** [comment]
Closing per the above comment.
