### ISSUE TITLE
AssetLibrary In-editor no Functionality

### ISSUE THREAD

**Issue by ShuiDev** [godotengine/godot#59646]
### Godot version

3.4.4.stable.official.419e713a2

### System information

Windows 10

### Issue description

The asset library fails to load, console throws the following error:

`ERROR: Condition "!category_map.has(r["category_id"])" is true.`

### Steps to reproduce

Open Godot(Steam)
Use AssetLibrary

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/53996.
