### ISSUE TITLE
Typing the "return" keyword auto-corrects to "KEY_RETURN"

### ISSUE THREAD

**Issue by JulienGio** [godotengine/godot#5964]
**Operating system or device - Godot version:**
Windows, using Godot 2.1 RC1

**Issue description** (what happened, and what was expected):
When editing a gd script, if you type `return` followed by a newline, it 'smartly' replaces it with `KEY_RETURN`

**Link to minimal example project** (optional but very welcome):
http://imgur.com/a/KwJ56
![ss](https://cloud.githubusercontent.com/assets/20727749/17254928/21bba89e-55b7-11e6-95eb-8d2c8cc97b04.jpg)

**Comment by Zylann** [comment]
Also why is draw_texture_rect_region matched?

**Comment by vnen** [comment]
This might be solved easily if `return` is added to the auto-completion list.

**Comment by rgrams** [comment]
Also "false" tends to give you "ERR_FILE_ALREADY_IN_USE".

**Comment by JulienGio** [comment]
Closed because I remade a more general issue #5972

**Comment by bojidar-bg** [comment]
... you could have edited the original post, but anyway
