### ISSUE TITLE
Android not loading png files from filesystem

### ISSUE THREAD

**Issue by HEAVYPOLY** [godotengine/godot#59650]
### Godot version

3.x + Add full support for Android scoped storage by M4gr3d 

### System information

Android 10, Android 11

### Issue description

On Android, loading a png from filesystem gives err 0 OK, but file has length of 0 and doesn't load.

On Desktop and iOS the same code works and loads image, prints correct file length

Not sure if this helps but also getting these errors on Android
E 0:00:01.378   make_dir_recursive: Could not create directory: /data
E 0:00:04.829   _load_from_buffer: Condition "buffer_size == 0" is true. Returned: ERR_INVALID_PARAMETER

If trying to load from Pictures dir, EG  "/storage/emulated/0/Pictures/b.png", also get a crash on Android

### Steps to reproduce

```
func load_test_texture():
    var path
    path ="user://Textures/beerglassb.png"
    $Sprite.texture = load_external_tex(path)

func load_external_tex(path):
    var tex_file = File.new()
    var err = tex_file.open(path, File.READ)
    var bytes = tex_file.get_buffer(tex_file.get_len())
    var img = Image.new()
    var data = img.load_png_from_buffer(bytes)
    var imgtex = ImageTexture.new()
    imgtex.create_from_image(img)
    prints("LOAD EXTERNAL TEX ", path, err, img, tex_file.get_len())
    tex_file.close()
    return imgtex
```
    

### Minimal reproduction project
[imageloadingandroid.zip](https://github.com/godotengine/godot/files/8508578/imageloadingandroid.zip)

_No response_

**Comment by Calinou** [comment]
> 3.x + Add full support for Android scoped storage by M4gr3d

For reference, this is https://github.com/godotengine/godot/pull/51815.

**Comment by HEAVYPOLY** [comment]
Another piece of info, not sure if helpful:

On Android, if using image.load(path) or img.load_png_from_buffer(bytes):
image.get_format() prints 0, and I get a flat gray image

On desktop and iOS, get_format() prints 5 and displays image correctly.

**Comment by HEAVYPOLY** [comment]
Rebased on today's 3.x and pngs are now loading.
