### ISSUE TITLE
[4.0] Text rendering inside a SubViewport breaks when changing the height of the window with "canvas_items" stretch mode.

### ISSUE THREAD

**Issue by Zorochase** [godotengine/godot#59652]
### Godot version

4.0.alpha5

### System information

Windows 11, Vulkan, Nvidia GTX 1060 

### Issue description

When changing the height of the main window, with display/window/stretch/mode set to "canvas_items", any text rendered by a SubViewport in a SubViewportContainer (with either a Label or a RichTextLabel) will cease to render properly; glyphs become blank white rectangles. This won't happen if the text is not rendered by a SubViewport; if the stretch mode is set to "disabled" or "viewport"; or if you only adjust the window's width, and not height. To further illustrate the issue, here's a video of it happening:

https://user-images.githubusercontent.com/101901701/160507400-9a5cbbde-0b05-48c7-95d5-2411ed6bb2c8.mp4

 

### Steps to reproduce

If you run the MRP's main scene, and try to adjust the window's size in height, you should see that the letters of the text of the two Labels turn into rectangles.

### Minimal reproduction project

[font_issue_mrp.zip](https://github.com/godotengine/godot/files/8367083/font_issue_mrp.zip)

**Comment by bruvzg** [comment]
Seems like viewport resize is changing oversampling but not triggering redraw.
