### ISSUE TITLE
Restore inapp (improvement)

### ISSUE THREAD

**Issue by ret80** [godotengine/godot#5967]
**Operating system or device - Godot version:**
ios - godot 2.x.x

**Issue description** (what happened, and what was expected):
Now there are no such opportunities as the restore inapp. Of course you can finish it but soms as micro transactions are supported out of the box that would not like to make your bike.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by ret80** [comment]
added change itself. everything is working. fill someone can please
https://yadi.sk/d/Pe2cj5UhtmgKD

**Comment by Calinou** [comment]
@ret80 Is this still relevant in the current `master` branch?

**Comment by Calinou** [comment]
It seems this has been implemented in #16901, closing.
