### ISSUE TITLE
[GodotPhysics] Unpredictable behaviour when applying forces to rigidbodies (Edited).

### ISSUE THREAD

**Issue by yosoyfreeman** [godotengine/godot#59670]
### Godot version

Godot 4.0 Alpha 5

### System information

Linux mint

### Issue description

As a  project for testing godot 4.0 i'm doing a few character controllers. While doing the RigidBody version i found that some gravity movement is always applied Even when you force the `linear_velocity` to be a `Vector3.ZERO`. This results in a jitter while being on a slope and prevents the character to folly stops.

https://user-images.githubusercontent.com/64601424/160605210-56ec54b4-a953-486a-afd0-e6fc2075451d.mp4

(In this case gravity scale is set to 10 for the problem to be seen easily, but happens with any scale except 0)

This happens no matter you set the speed to 0 in `physics update` or accesing the BodyDIrectState in integrate forces.

For now, as a workaround, set the gravity scale to 0 and apply gravity as a force.

### Steps to reproduce

Creaty a rigidbody, force the velocity to be always 0. The body will move anyway.

### Minimal reproduction project

[BugPhysics gravity.zip](https://github.com/godotengine/godot/files/8371127/BugPhysics.gravity.zip)

**Comment by yosoyfreeman** [comment]
Ok, i have found that is not the way gravity is applied, but any force. If you apply a force for example with `apply_central_force` and just after that you set `the linear_velocity` to 0 it still moves.

**Comment by masteroftime** [comment]
I don't think this is really a bug. The RigidBody still moves, because gravity and other forces are integrated after _physics_process and _integrate_forces have run, leading to a nonzero velocity. The problem can be solved by setting the [custom_integrator](https://docs.godotengine.org/de/stable/classes/class_rigidbody.html#class-rigidbody-property-custom-integrator) property of the RigidBody.

I checked Godot 3.4.4 and RigidBody behaves the same. This behavior is also stated in the [documentation](https://docs.godotengine.org/de/stable/classes/class_rigidbody.html) of the RigidBody class.

**Comment by akien-mga** [comment]
Indeed, rigid bodies are affected by gravity by design. Aside from the above suggestion to use a custom integration, you can likely also set the default gravity to 0 in project settings of you don't want Earth-like Newtonian physics.

**Comment by yosoyfreeman** [comment]
> I don't think this is really a bug. The RigidBody still moves, because gravity and other forces are integrated after _physics_process and _integrate_forces have run, leading to a nonzero velocity. The problem can be solved by setting the [custom_integrator](https://docs.godotengine.org/de/stable/classes/class_rigidbody.html#class-rigidbody-property-custom-integrator) property of the RigidBody.
> 
> I checked Godot 3.4.4 and RigidBody behaves the same. This behavior is also stated in the [documentation](https://docs.godotengine.org/de/stable/classes/class_rigidbody.html) of the RigidBody class.

Applying forces is just modifying the linear velocity of and object, as so, they should follow a linear order. Right now, the velocity that you get do not represent the real velocity of the object. 

Also, using `custom_integrator` do not resolve the issue in any way. That results in the inability to apply any kind of forces on the object, even in `integrate_forces`, and we are not trying to remove the forces, we want to control them. This not only apply for gravity, but any force manually applied to.  The ability to control forces in a predictable way is core to the creation of physic characters, and right now you cant take the usual approaches in any other engine.

Right now, from a game developer view, the better way to apply a force is to directly manipulate the linear velocity each frame (which is not recommended in other engines, due to the fact that you can work in a predictable way using the add_force methods of each engine, and in Godot it set that you should never do that even when doing it right produce better results.)

May not be a bug in Godot terms (i think it is) but the warning on the docs about manipulating the linear velocity should be change.
