### ISSUE TITLE
remove_control_from_container() is missing

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#5968]
In Godot 2.1 rc1, the EditorPlugin API has a function to add controls to containers, `add_control_from_container(int container, Control control)`, but I don't see a `remove_control_from_container(int container, Control control)`. Is it missing?

**Comment by vnen** [comment]
I bumped into this too, but you don't actually need it. Just call `free()` on the added control.

**Comment by RodeoMcCabe** [comment]
Calling `free()` doesn't work in v3 alpha 1. There also is still no `remove_control_from_container()`.

**Comment by akien-mga** [comment]
@Zylann @vnen Does it still need better documentation or a dedicated method?

**Comment by vnen** [comment]
I think it does need a dedicated method. Freeing *should* work, but I also think that one might need to remove the control without freeing.
