### ISSUE TITLE
ColorPickerButton has wrong mouse colliders with stretch mode canvas_items

### ISSUE THREAD

**Issue by BMagnu** [godotengine/godot#59685]
### Godot version

4.0.dev (bc9dd15f0)

### System information

Windows 10, Vulkan Clustered, RTX 2070 Super

### Issue description

When a ColorPickerButton is used in a project whose window stretch mode is set to canvas_items, the ColorPickerButton will have its mouse collider areas not over the actual rendered color picker area (rather, I suspect, at the unscaled position).

### Steps to reproduce

1. Set the project to have the canvas_items stretch mode
2. Place a ColorPickerButton (ideally not at 0,0, as there the offset due to the disregarded stretching is a lot smaller)
3. Run, and resize the window (or set a different window override size in the settings, as in the attached project)
4. Try to pick a color on the ColorPicker. Instead of clicks on the actual color picker working, the collider is (in the example project) offset to the bottom right

### Minimal reproduction project

[ColorPickerButtonMWE.zip](https://github.com/godotengine/godot/files/8377346/ColorPickerButtonMWE.zip)

**Comment by Sauermann** [comment]
Please try with current master. This has been solved by #59118.
