### ISSUE TITLE
Child classes cannot use parent classes' enums as a type

### ISSUE THREAD

**Issue by PrecisionRender** [godotengine/godot#59684]
### Godot version

v3.4.1.stable.official [aa1b95889], v4.0.alpha5.official [d7d528c15]

### System information

Windows 11, Vulkan, Nvidia GeForce RTX 2060 Max-Q

### Issue description

When creating an enum in a parent class, a child class cannot use the enum as a type. This makes overriding methods that take the enum as a parameter impossible, unless the parameter is set up without a type. I'm not sure if this is desired behavior or not, but it seems like an issue. Note that this happens in the 4.x branch as well as the 3.x branch.

### Steps to reproduce

1. Create a class in GDScript with a new script
2. Extend that class with a new script
3. Create an enum in the parent class
4. Try to set a variable's type to the enum

### Minimal reproduction project

[EnumTest.zip](https://github.com/godotengine/godot/files/8376600/EnumTest.zip)

**Comment by DaGamingWolf** [comment]
perhaps, but i don't experience the issue as described. you can indeed use the enum of a parent class as a type. the problem only occurs when it's the parents' parent class(or higher on the inheritance tree) specifically.

**Comment by dalexeev** [comment]
The bug is not reproducible in 4.0.3 and master. Probably fixed by #69590. In 3.x, enums as types are not supported at all.
