### ISSUE TITLE
[Android Editor] Mouse cursor is displayed as `I` icon in the top part of the screen.

### ISSUE THREAD

**Issue by bruvzg** [godotengine/godot#59697]
### Godot version

3.5 beta 3 (official build)

### System information

Android 12 on Poco F3, with Bluetooth mouse and keyboard connected.

### Issue description

In the top part of the screen, the mouse cursor is always displayed as a text input `I` icon.

https://user-images.githubusercontent.com/7645683/160881384-69cf4805-7f8b-4303-8272-e1b1bd94aa19.mp4

Have not looked at Android code, but I guess there's an invisible native text input area, that is used to handle text input or something like this.

### Steps to reproduce

- Run the editor on android.
- Connect Bluetooth mouse.
- Move cursor to the top part of the screen.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Note for testers: you need a hardware mouse (typically Bluetooth) to reproduce this :slightly_smiling_face: 

> Have not looked at Android code, but I guess there's an invisible native text input area, that is used to handle text input or something like this.

I wonder if the Android API lets you change the mouse cursor when hovering specific controls. That said, here, it would be better to make clicks pass through the invisible text field entirely.

An alternative would be to position the text field to be outside the viewport, but I'm not sure if Android allows this.

**Comment by m4gr3d** [comment]
Issue has been resolved in the latest versions of the Godot Android Editor.
