### ISSUE TITLE
Changing script editor cut (`ctrl + x`) keybinding in Editor Settings does nothing

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#59695]
### Godot version

v3.5.beta2.official [7a4f9dfb1]

### System information

Mac OSX (Intel 2019)

### Issue description

Changing the keyboard shortcut for cut does not have any effect.

<img width="894" alt="Screenshot 2022-03-30 at 18 22 45" src="https://user-images.githubusercontent.com/100964/160871453-2d7d7a97-9c4e-4336-be9f-dff47d703000.png">

`ctrl + x` will still cut the whole line or selected text.

Relevant issue:
https://github.com/godotengine/godot/issues/59441

### Steps to reproduce

1. Change the cut keybinding
2. Enter the script editor
3. Press `ctrl + x`

**Comment by Calinou** [comment]
Did you try restarting the editor after changing the shortcut?

**Comment by tavurth** [comment]
Yes, this issue persists across restarts

**Comment by Paulb23** [comment]
Pretty sure this is a duplicate of #50972, due to hardcoded shortcuts, fixed in master by #43663.
