### ISSUE TITLE
Crash when using set_custom_viewport()

### ISSUE THREAD

**Issue by PangolinGiLA** [godotengine/godot#59692]
### Godot version

3.4.4.stable

### System information

Arch Linux

### Issue description

Godot game window crashes without feedback in editor when using `set_custom_viewport()` second time, if the previous viewport was removed (before setting it for the second time).

### Steps to reproduce

1. Download minimal reproduction project
2. Run the project
3. Press the button on the screen two times
4. Game window crashes

### Minimal reproduction project

[crash.zip](https://github.com/godotengine/godot/files/8380864/crash.zip)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/53445.

**Comment by timothyqiu** [comment]
Fixed by #59724
