### ISSUE TITLE
false error: Index p_contact_idx out of size

### ISSUE THREAD

**Issue by jtaart** [godotengine/godot#5970]
Operating system: Windows 8.1 (64-bit) 
Godot version: Godot_v2.1_rc1_win64

Issue description: Godot_v2.0.3_stable_win64 seems to run this code just fine, but in Godot_v2.1_rc1_win64 it creates an error.

error: `Index p_contact_idx out of size (body->contact_count).`

I'm pretty sure I'm not out of index, because my index is coming from get_colliding_bodies(), and it works fine in 2.0.3. (or it could be my code, idk)  

code:
```
func _integrate_forces(state):
	
	for i in get_colliding_bodies():
		if i in get_tree().get_nodes_in_group("wallSlide"):	
			print(i.get_name())
		
			var vec_0 = state.get_contact_local_normal(get_colliding_bodies().find(i)) 			
			set_linear_velocity(vec_0 * speedCassV.length()/1.45 + speedCassV  )
			turnWithMovement()
			return
```

screen-cap: http://i.imgur.com/Z9CUDsq.jpg

**Comment by bojidar-bg** [comment]
@jtaart it is likely that `get_colliding_bodies` is returning the bodies for the _previous_ frame, and if one of them was present, but now isn't, it would throw the error. Maybe you should use `state.get_contact_count` and `state.get_contact_collider` for this.

**Comment by jtaart** [comment]
Thanks, @bojidar-bg you were right, and I should have look though Physics2DDirectBodyState more. (I'm still trying to grasp the state stuff). I wonder why it let me get away with it in 2.0.3

Here is the new code that seems to work well. (guess someone can shut this issues down or do I do it some how?)

```
func _integrate_forces(state):
	
	for i in range(state.get_contact_count()):
		var contact = state.get_contact_collider_object(i) 
		print(contact.get_name()) 
		if contact in get_tree().get_nodes_in_group("wallSlide"):
			var vec_0 = state.get_contact_local_normal(i) 
			
			set_linear_velocity(vec_0 * speedCassV.length()/1.45 + speedCassV  )
			turnWithMovement()		
			return
```
