### ISSUE TITLE
macOS shows scene prematurely when changing fullscreen with code

### ISSUE THREAD

**Issue by ztc0611** [godotengine/godot#59743]
### Godot version

3.3.4-stable, 3.4.4.stable

### System information

MacOS Monetary 12.3, GLES3, Apple M1

### Issue description

This is possibly not actually a bug and might just be an unfortunate consequence of systems working as intended. If that is the case, apologies.

This happens when making a project that has an option to change your fullscreen state in-game, meaning you need to adjust fullscreen with code, from my knowledge requiring an autoload. (Mine reads/writes to a custom user settings file in user://)

If you launch a scene on MacOS and the project is set to adjust fullscreen in this way it doesn't do any updates before finishing the "enter fullscreen" animation, during which it shows the scene prior to any scripts running. This problem does not happen under any other circumstances I can find on MacOS. Uncertain about Windows or Linux.

I know using an Autoload means the code should execute with first priority, but I'm unsure if it should be this extreme. It is possible that the splash screen is technically being hidden prematurely, but I am unsure on that regard.

https://user-images.githubusercontent.com/28269330/161080636-2b1879e7-a204-4ad3-b131-4fcff094b3a0.mp4

### Steps to reproduce

Make an autoload that sets the window to fullscreen mode on boot.

In the main scene, make a ColorRect and give it a script to make it free itself during _ready(). Launch the project.

### Minimal reproduction project

[MacOS_FS_Ready.zip](https://github.com/godotengine/godot/files/8390411/MacOS_FS_Ready.zip)

**Comment by Calinou** [comment]
cc @bruvzg
