### ISSUE TITLE
New Blend file import doesn't handle lights

### ISSUE THREAD

**Issue by timshannon** [godotengine/godot#59748]
### Godot version

v4.0.alpha.mono.custom_build [a647fb3e6]

### System information

Ubuntu 21.04 using Blender 3.1.1

### Issue description

I was testing out the new Blend file import added here: https://github.com/godotengine/godot/pull/54886 and it works great, except lights don't seem to get imported, even when Punctual Lights are selected in the import settings.

The same issue does not apply when using GLTF files directly.

### Steps to reproduce

Start a new project with the new blend import option enabled and the editor setting path set to the blender executable.

Import any blender scene with lights.  The default import settings include punctual lights, however disabling or enabling them seems to have no impact.

### Minimal reproduction project

[Bug.zip](https://github.com/godotengine/godot/files/8391082/Bug.zip)

**Comment by fire** [comment]
It's a small typo.

```
> git diff
diff --git a/modules/gltf/editor/editor_scene_importer_blend.cpp b/modules/gltf/editor/editor_scene_importer_blend.cpp
index 2587c095e1d..337a1e981aa 100644
--- a/modules/gltf/editor/editor_scene_importer_blend.cpp
+++ b/modules/gltf/editor/editor_scene_importer_blend.cpp
@@ -85,7 +85,7 @@ Node *EditorSceneFormatImporterBlend::import_scene(const String &p_path, uint32_
        } else {
                parameters_arg += "export_cameras=False,";
        }
-       if (p_options.has(SNAME("blender/nodes/lights")) && p_options[SNAME("blender/nodes/lights")]) {
+       if (p_options.has(SNAME("blender/nodes/punctual_lights")) && p_options[SNAME("blender/nodes/punctual_lights")]) {
                parameters_arg += "export_lights=True,";
        } else {
                parameters_arg += "export_lights=False,";
```

**Comment by fire** [comment]
After the diff.

![image](https://user-images.githubusercontent.com/32321/161103009-ab5aca7e-efd6-4f9a-9707-594af8c83464.png)
