### ISSUE TITLE
GridMap selection preview isn't cleared when another GridMap node is selected

### ISSUE THREAD

**Issue by fazil47** [godotengine/godot#59742]
### Godot version

v4.0.alpha.custom_build [b0df742cb]

### System information

Windows 11, Vulkan Clustered, Nvidia 1650

### Issue description

The `GridMap` selection preview is retained even after selecting another `GridMap` node.

https://user-images.githubusercontent.com/18116695/161081561-834a4a67-5c48-4881-b54f-993afafe8543.mp4

### Steps to reproduce

- Open `main.tscn`
- Select the forest `GridMap` node and place some tiles
- Select the desert `GridMap` node and notice the selection preview hasn't changed

### Minimal reproduction project

[gridmap_bug.zip](https://github.com/godotengine/godot/files/8390496/gridmap_bug.zip)
Assets from the [Kaykit mini game variety pack](https://kaylousberg.itch.io/kay-kit-mini-game-variety-pack)

**Comment by Sauermann** [comment]
Related to #58624

**Comment by fazil47** [comment]
Closed it by accident.
