### ISSUE TITLE
Mesh menu 'Create Trimesh Static Body' opperation creates CollisionShape3D with invalid name

### ISSUE THREAD

**Issue by RocketPunches** [godotengine/godot#59744]
### Godot version

Godot_v4.0-alpha5_win64

### System information

Windows 10

### Issue description

When using the Create Trimesh Static Body option in the viewport Mesh menu the CollisionShape3D added to the StaticBody3D is given a name that is recognized as invalid by the editor, starting with @@ followed by a series of 5 digits. Starting to rename the node but clicking away throws an error saying that the @ symbols are invalid. I haven't tried to reference the name that's created here somewhere else, but if it's invalid here I'd expect it to cause an error elsewhere. 

![image](https://user-images.githubusercontent.com/32081610/161081824-5f772e4c-afcd-40c5-8e35-057f04fb636f.png)

Expected Result: The format of the current name itself is largely irrelevant, as I would expect the node to be called CollisionShape3D anyways - in line with other node naming conventions.

### Steps to reproduce

1. Create a new Node3D based scene
2. Add a MeshInstance3D, select any mesh option like BoxMesh
3. Select the added MeshInstance3D, and click into the 'Mesh' menu at the top of the 3D Viewport
4. In the dropdown, select 'Create Trimesh Static Body'

**Comment by Calinou** [comment]
cc @KoBeWi
