### ISSUE TITLE
[3.4.4] c# - [Tool] attribute is not inherited

### ISSUE THREAD

**Issue by Flavelius** [godotengine/godot#59745]
### Godot version

3.4.4.stable.mono.official

### System information

Windows10 / Ubuntu 20.04

### Issue description

When applying the [Tool] attribute to an abstract class and inheriting from it, the editor doesn't seem to treat the inherited concrete class as a tool script. Only when the [Tool] attribute is duplicated into this class aswell does it work as expected.
This leads to errors if the base class expects to be able to execute certain logic on getters and setters for example.

### Steps to reproduce

Create an abstract base class with the [Tool] attribute. Inherit from it without applying it there aswell and add a property with some setter logic for example GD.Print(). compile/build the solution and test setting the property value from the inspector to trigger the logic.

**Comment by Flavelius** [comment]
[MRP.zip](https://github.com/godotengine/godot/files/8390827/MRP.zip)

**Comment by Calinou** [comment]
As far as I know, this is intended behavior and also happens in GDScript.

**Comment by Flavelius** [comment]
> As far as I know, this is intended behavior and also happens in GDScript.
Then this is not a sensible default, as [Tool] implies a declared requirement of the script in question for working correctly.
This should not be broken by consumers by default.
[Tool(mode=off)] or something similar could be an option if inheritors want to explicitly break functionality.
