### ISSUE TITLE
Visual shader editor blocks misbehave after another block gets deleted

### ISSUE THREAD

**Issue by Bonfi96** [godotengine/godot#5974]
**Operating system or device - Godot version:**
Windows 10, Godot 2.1 rc1

**Issue description** (what happened, and what was expected):
Blocks in the visual shader editor get locked to the mouse after deleting another block.

**Steps to reproduce:**
Open the visual shader editor, crete any block, delete it by clicking on the X.
Sometimes one of the other blocks will follow the mouse around the editor

**Comment by vnen** [comment]
Duplicate of #4869.

**Comment by akien-mga** [comment]
Actually duplicate of #4433 too :)
