### ISSUE TITLE
TextEdit::insert_text_at_cursor() doesn't work?

### ISSUE THREAD

**Issue by Keyaku** [godotengine/godot#5975]
**Operating system or device - Godot version:**
Mac OS X 10.11.6 - Godot-master

**Issue description** (what happened, and what was expected):
I'm attempting to build a Command box _a la_ Valve's Source engine. When the TextEdit node receives an "Enter" action, I process the command. The problem is, if the cursor isn't placed at the end of the command, it places an unwanted newline character. Since this is supposed to accept multiple lines, I can't clean out all `\n` entirely.

So I grab the position of the cursor before processing the command and select the newline (which works according to `get_selection_text()`), but when I use `insert_text_at_cursor()`, nothing happens and the string is untouched.

However, [I take a look at the code](https://github.com/godotengine/godot/blob/master/scene/gui/text_edit.cpp#L3206) and see nothing wrong, hence the question mark in the title.

**Steps to reproduce:**  

1. Connect TextEdit node to `InputEvent()` signal
2. Receive an "Enter" action
3. Grab cursor position and select the newline
4. Erase selection by using `insert_text_at_cursor()`
5. Test it by entering any string and placing the cursor anywhere but the end
6. Press Enter/Return

**Link to minimal example project**:
https://db.tt/u58X6rku

If you're using the example project, just go to steps 5 and 6.

**Comment by Dillybob92** [comment]
I get `Parser Error: Unexpected token: Constant:` after I press enter..?

**Comment by Keyaku** [comment]
That's something I'm going to fix later; that error is due to the formatting of the temporary GDscript, but it's not the main issue.

Like I previously mentioned:

1. Test it by entering any **String** and placing the cursor anywhere but the end
2. Press Enter/Return

An example would be:
"Hello" (Press enter with the cursor to the rightmost side).

This works fine and is shown in the label above.

Now, do the same but this time **place the cursor anywhere but the end**. Then, you'll understand what's this issue about.

**Comment by Keyaku** [comment]
For some reason, I managed to find out that TextEdit::get_text() yields the modified string, but get_line() does not. This is getting weirder by the minute.

I'll open a more complete and thorough issue if I find any details.

**Comment by vnen** [comment]
BTW, your "minimal project" is not minimal. If your issue is with `insert_text_at_cursor()` then you should make a project using only that so it's easier to understand what's going on and thus easier to fix the bug. It might also help you debugging your code and pinpoint where it's really failing (which seems to just have happened).

**Comment by Keyaku** [comment]
@vnen I've been debugging this almost all day, but I only pinpointed my problem a few seconds ago.

My problem was sleep-related because I was forgetting to update the string after removing the pesky newline.

I'm so sorry about this.
