### ISSUE TITLE
Polygon2D.offset doesn't work.

### ISSUE THREAD

**Issue by hazarek** [godotengine/godot#59754]
### Godot version

Godot 3.4.4 stable / Godot 4 Alpha 5

### System information

macOs monterey gles2 / vulkan

### Issue description

Adjusting the offset does not affect the vertex positions

## Doc
[Polygon2D.offset](https://docs.godotengine.org/en/stable/classes/class_polygon2d.html#class-polygon2d-property-offset)

> The offset applied to each vertex.

### Steps to reproduce

```gdscript
extends Polygon2D

func _ready():
	print(polygon, offset)
	offset = Vector2(879, 54)
	print(polygon, offset)

# [(0, 0), (100, 0), (0, 100)](0, 0)
# [(0, 0), (100, 0), (0, 100)](879, 54)
```

<img width="441" alt="offset" src="https://user-images.githubusercontent.com/36481442/161108821-65123c48-2812-4771-833d-caeb35803dd5.png">

Also `Polygon2D.position` does not affect vertices. and what is the difference between `offset` and `position` ?

**Comment by Sauermann** [comment]
Neither `offset` nor `position` change the numbers in the `PackedVector2Array`.
But both are used for displaying the Polygon. For me it works as expected.
Do the values affect how the polygon is displayed for you? They should.

The difference of them is the order, in which they are applied:

1. `Polygon2D.position` is applied relative to the parent nodes coordinate system (and also rotation, scale and skew).
2. `Polygon2D.offset` is applied relative to the polygons coordinate system.
3. The values from `PackedVector2Array` are used for drawing.

**Comment by hazarek** [comment]
Collision and geometry functions produce incorrect results, because the apparent and real positions are different. For example the visible polygon and the return value will be different. This is unexpected behavior for me;

```gdscript
extends Node2D

@onready var pl: Polygon2D = get_node("Polygon2D")

func _ready():
	pl.offset = Vector2(0, 100)
	
func _process(delta):
	var p = get_global_mouse_position()
	if Geometry2D.is_point_in_polygon(p, pl.polygon):
		pl.color = Color.BLACK
	else:
		pl.color = Color.YELLOW
```

**Comment by Sauermann** [comment]
Can you please be more precise, what you mean by the "offset bug". It would help if you could describe your expected behavior.

Also my code can be simplified to
``` GDScript
func _process(delta):
	if Geometry2D.is_point_in_polygon(pl.get_local_mouse_position() - pl.offset, pl.polygon):
		pl.color = Color.BLACK
	else:
		pl.color = Color.YELLOW
```

**Comment by hazarek** [comment]
But the coordinate I see on the screen and the actual value are different. offset only provides a virtual view. This is so ridiculous to me.

<img width="1207" alt="Ekran Resmi 2022-04-01 19 14 31" src="https://user-images.githubusercontent.com/36481442/161302620-2650481f-cd8b-4a06-ae33-f04600f3a7d9.png">

offset should be added automatically with get() set() to the vertices coordinates;

```gdscript
for i in $Polygon2D.polygon.size():
     $Polygon2D.polygon[i] += $Polygon2D.offset
```

**Comment by Sauermann** [comment]
Thank you, now I understand your issue: You want to change all vectors of the polygon in a single step.

Try this:
``` GDScript
func _ready():
	var t: Transform2D = Transform2D()
	t = t.translated(Vector2(0, 111))
	pl.polygon = pl.polygon * t # apply the transform to all elements of the polygon
	print(pl.polygon)
```

**Comment by edzillion** [comment]
I found it wasn't possible to use the multiply operator on between a `PoolVector2Array` and a `Transform2D`, this worked for me:

```gdscript
func _ready():
	var t: Transform2D = Transform2D()
	t = t.translated(Vector2(0, 111))
	pl.polygon = t.xform(pl.polygon) # use xform to transform to all elements of the polygon
	print(pl.polygon)
```
