### ISSUE TITLE
node that have arabic names can't be referenced from code

### ISSUE THREAD

**Issue by yzn-h** [godotengine/godot#59783]
### Godot version

4.0.alpha5

### System information

Linux pop os 21.10, i7-8550U

### Issue description

when making a child node with Arabic name and trying to referencing it in code you can't

https://user-images.githubusercontent.com/63852512/161247928-58d3834a-8c69-4a99-a802-ff5c4c2c3a5c.mp4

### Steps to reproduce

make any node
make child node and name it اختبار
make a script in the parent node
reference the child node `@onready var test = $اختبار`

**Comment by timothyqiu** [comment]
You have to quote the path in this case if I remember correctly.

```
@onready var test = $"اختبار"
```
