### ISSUE TITLE
Inconsistency in the animation player with FPS.

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#59784]
### Godot version

v3.5.beta3.official [3c0d32562]

### System information

w10 64

### Issue description

I select metering by FPS.
Then I select that I want to move the time bar frame by frame, so I select the value 1.
But this has not changed, the value 1 still refers to time, that is, seconds, that is, 1 second, not 1 frame.
Conclusion, it is confusing to set an animation for only 1 frame because the duration of the animation still counts in time, in seconds, but I selected that I want to use the time measurement by FPS.
So I think animation duration should now be per FPS, not per seconds.
If you select 30, you are referring to 30 fps, not 30 seconds.

In the video you can see that although I selected FPS, when I press play the value 1 is reached after 1 second, that is, the player continues to show the time rule using seconds.

https://user-images.githubusercontent.com/19652075/161248554-b3f9cd8b-2322-4ed9-95da-da232fd0c9d0.mp4

![Captura](https://user-images.githubusercontent.com/19652075/161249407-9e61456c-df89-4ff8-b63b-e7a3fd40e915.PNG)

### Steps to reproduce

see the video

### Minimal reproduction project

...

**Comment by Calinou** [comment]
I don't really understand what's going on. All the fields seem to go from seconds to FPS when you adjust the dropdown (*especially* the timeline, I'm 100% sure that was implemented as I saw it on the initial blog post).

**Comment by Torguen** [comment]
It seems.
The confusion comes when you press PLAY then the timer starts ticking and 1 second elapses from frame 0 to frame 1, so this looks confusing.
I selected FPS but why does it take 1 second from frame 0 to frame 1?
I invite you to try to make an animation that lasts only 1 second. The meters won't do any good and you'll have to do it by chance and keep testing and executing continuously without really knowing if the animation lasts only 1 frame.

Why did you mark it as a discussion? I think it's an implementation problem.
The implementation of the usability of the animationplayer through FPS is not correctly done.

**Comment by TokageItLab** [comment]
The FPS related issue is probably a GUI update timing issue.
