### ISSUE TITLE
AnimationPlayer does not play according to keyframes | Trying to get real 24fps on animations.

### ISSUE THREAD

**Issue by shafnaz** [godotengine/godot#59785]
### Godot version

3.4.4

### System information

Windows 10

### Issue description

Hi guys,

There is this issue I'm having with the wave next to the big number. At one keyframe the wave is at its end, the next keyframe it should jump back to the start position. When playing, you can see the wave moving back, which is not correct.
Editor view gif:
![issue_1](https://user-images.githubusercontent.com/37254287/161260129-1a8434d1-41ac-4295-8fc4-edc0bd60658e.gif)
Run view gif:
![issue_2](https://user-images.githubusercontent.com/37254287/161260228-dbf2b69f-e306-491e-9f38-71dc1ad2e94f.gif)

### Steps to reproduce

Open the attached file in your Godot, play the animation and check it out. "number_four_transform5" is the wave.
Drag with the time slider is what it should look like, however, play the animation, and you see how the wave sneaks back to its starting position.

### Minimal reproduction project

[number_four.zip](https://github.com/godotengine/godot/files/8397450/number_four.zip)

**Comment by timothyqiu** [comment]
I tried dropping this file to glTF viewers like [this one](https://github.khronos.org/glTF-Sample-Viewer-Release/) and [this one](https://gltf-viewer.donmccurdy.com/), the wave animation looks the same.

Maybe the last keyframe can be tweaked.

**Comment by shafnaz** [comment]
Indeed. however, that won't solve the problem. it's the playback that is important. I work a lot with 3d applications like Maya and 3DS Max.
Recently I have been testing out Unity. In Unity, this is not an issue. There has to be a way to playback animation by the specified fps. The animation needs to play at 24fps, this way these weird behaviors won't be seen. 

I could try just going keyframe by keyframe, but that would seem to use more processing.

**Comment by Calinou** [comment]
> There has to be a way to playback animation by the specified fps. The animation needs to play at 24fps, this way these weird behaviors won't be seen.

This can be done by setting the keyframe interpolation mode to Nearest, or using the Manual animation process mode and stepping through the animation manually.

**Comment by shafnaz** [comment]
![image](https://user-images.githubusercontent.com/37254287/161342518-ff6c0a88-53d4-420f-ab62-85db66a1043b.png)

@Calinou Alright, after giving it a try, no luck. The "nearest" sounds like a great idea, however, it does not work with gaps between keyframes, but why does Godot create these gaps?  In Blender, all the frames have keys. Godot removes keyframes. Is there a way to keep the keyframes when imported?

**Comment by Calinou** [comment]
> @Calinou Alright, after giving it a try, no luck. The "nearest" sounds like a great idea, however, it does not work with gaps between keyframes, but why does Godot create these gaps? In Blender, all the frames have keys. Godot removes keyframes. Is there a way to keep the keyframes when imported?

You can disable the animation optimizer in the Import dock, but it sounds like using manual stepping is a better idea in your case.

**Comment by shafnaz** [comment]
Awesome
