### ISSUE TITLE
MacOS : Godot 4.0 crashes on project opening or running

### ISSUE THREAD

**Issue by glepache** [godotengine/godot#59781]
### Godot version

v4.0.alpha5.official.d7d528c15

### System information

Imac end 2012 i5 - MacOS 10.14.6- NVIDIA GeForce GTX 680MX

### Issue description

1) Create a new project in the project explorer and try to edit it : Godot will crash before opening the editor.
Or
2) Open a project by drag-and dropping the .project to the application : the editor will open. However, when trying to run the project, nothing will happen (no message except "--- Debugging process started ---")

The last error seen before the crash is :
```
ERROR: Could not create child process: /Applications/Godot.app
   at: create_process (drivers/unix/os_unix.cpp:390)
```

Might be related to issue #58985 as the VK_ERROR_INITIALIZATION_FAILED message appears, see below. However, the symptoms are a bit different, as I can't open the editor. As recommended in the ticket, I've tried deleting shader_cache without any effect.

When opening Godot, I get the following console message :

```
/Applications/Godot.app/Contents/MacOS/Godot
arguments
0: /Applications/Godot.app/Contents/MacOS/Godot
Current path: /Users/rataime
Godot Engine v4.0.alpha5.official.d7d528c15 - https://godotengine.org
Vulkan API 1.1.198 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 680MX
[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Render pipeline compile failed (Error code 1):
Compiler encountered an internal error.
ERROR:  - Message Id Number: 0 | Message Id Name: 
	VK_ERROR_INITIALIZATION_FAILED: Render pipeline compile failed (Error code 1):
Compiler encountered an internal error.
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_PIPELINE, Handle 140723555883008
   at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:159)
ERROR: vkCreateGraphicsPipelines failed with error -3 for shader 'ClusterRenderShaderRD:0'.
   at: render_pipeline_create (drivers/vulkan/rendering_device_vulkan.cpp:6596)
[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Render pipeline compile failed (Error code 1):
Compiler encountered an internal error.
ERROR:  - Message Id Number: 0 | Message Id Name: 
	VK_ERROR_INITIALIZATION_FAILED: Render pipeline compile failed (Error code 1):
Compiler encountered an internal error.
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_PIPELINE, Handle 140723563701760
   at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:159)
ERROR: vkCreateGraphicsPipelines failed with error -3 for shader 'ClusterRenderShaderRD:0'.
   at: render_pipeline_create (drivers/vulkan/rendering_device_vulkan.cpp:6596)
 
Registered camera Caméra FaceTime HD (intégrée) with id 1 position 0 at index 0
Editing project: /Users/rataime/Documents/Devel/Godot/Chem (::Users::rataime::Documents::Devel::Godot::Chem)
ERROR: Could not create child process: /Applications/Godot.app
   at: create_process (drivers/unix/os_unix.cpp:390)
```
Note that, until Registered camera, the messages don't prevent the project selector from running.

I've attached the result of the command `env MVK_DEBUG=1 MVK_CONFIG_LOG_LEVEL=4 /Applications/Godot.app/Contents/MacOS/Godot > mvk_log.txt 2>&1`
[mvk_log.txt](https://github.com/godotengine/godot/files/8396590/mvk_log.txt)

### Steps to reproduce

1) Create a new project in the project explorer and try to edit it
Or
2) Open a project by drag-and dropping the .project to the application, then run it

Reproduced on 4.0alpha5, 4.0alpha3, 4.0alpha1, but not on 3.4.4. 

### Minimal reproduction project

Create a new project, then try to edit it

**Comment by bruvzg** [comment]
This mac should have some [Metal support](https://support.apple.com/en-us/HT205073) and 10.14 is supported by MoltenVK, but it's likely do not have full set of Metal feature required to run Godot.

I would not expect Godot 4.0 to properly run on anything below macOS 10.15 and GPU with Metal feature set 2.1:

> iMac models from 2015 or later
> MacBook Pro models from 2016 or later
> MacBook models from 2016 or later
> iMac Pro models from 2017 or later

**Comment by glepache** [comment]
I see, thanks everyone.
This computer indeed reports that Metal is supported, but not in its latest feature set :
`Metal: Supported, feature set macOS GPU family 1, version 4`
I don't mind too much as this is my secondary computer, but would it be possible to display an error message when the feature set isn't supported ? I'd be inclined to think that #58985 has the same issue.

**Comment by bruvzg** [comment]
Even if it won't properly run, crash seems to be unrelated to the GPU, I think I see what's wrong, will fix in a moment.

**Comment by hiulit** [comment]
I'm using macOS BigSur (11.16.2) - Intel Iris Pro 1536 MB
Godot: v4.0.alpha5.official

I get this error:

```
Godot Engine v4.0.alpha5.official.d7d528c15 - https://godotengine.org
Vulkan API 1.1.198 - Using Vulkan Device #0: Intel - Intel Iris Pro Graphics
[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Render pipeline compile failed (Error code 2):
Compiler encountered an internal error.
ERROR:  - Message Id Number: 0 | Message Id Name: 
	VK_ERROR_INITIALIZATION_FAILED: Render pipeline compile failed (Error code 2):
Compiler encountered an internal error.
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_PIPELINE, Handle 140215928220160
   at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:159)
ERROR: vkCreateGraphicsPipelines failed with error -3 for shader 'ClusterRenderShaderRD:0'.
   at: render_pipeline_create (drivers/vulkan/rendering_device_vulkan.cpp:6596)
```

but If I wait a couple of minutes, it opens.

```
Registered camera Càmera FaceTime HD with id 1 position 0 at index 0
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...     153 completed.

[Procés completat]
```
