### ISSUE TITLE
2.1 RC1, Win32 export template not working

### ISSUE THREAD

**Issue by rgrams** [godotengine/godot#5979]
**Operating system or device - Godot version:** 2.1 RC1, from the website. 

**Issue description** (what happened, and what was expected):
The windows 32-bit export template is not actually 32 bit, or something else weird. I tried both the release and debug versions on a 32-bit Windows XP machine, got the message: " . . . is not a valid Win32 application".

**Comment by TheoXD** [comment]
Could it be because of those commits?
https://github.com/godotengine/godot/commit/b48fd16add3669219ad38c27f7db7fc2d5e32130
https://github.com/godotengine/godot/commit/0bc589a0c7a12c80f4e365724586174e2e7c9dbd
I don't have anything this old so I can't test.

**Comment by TheoXD** [comment]
Also want to note that WinXP is not officially supported, Godot uses Win7 API.

**Comment by akien-mga** [comment]
Windows XP doesn't understand recent binaries, so it seems as "not valid *Windows XP* 32-bit applications".

**Comment by akien-mga** [comment]
To confirm that the issue is Windows XP and not the Godot 2.1 RC1 binaries, could you try 2.0.x binaries?

**Comment by TheoXD** [comment]
Oh RC1 binaries are 6 days old, feels like yesterday. Then it's not those commits, I thought resource get corrupted.

**Comment by rgrams** [comment]
It's always worked on XP before

**Comment by rgrams** [comment]
OK, yeah, it's the same with the official 2.0.4.1. I guess before I've always used builds compiled on something older than what the official binaries are compiled on? I've never seen this happen before. That's annoying, but . . . closing.
