### ISSUE TITLE
"Sun and Environment Settings" Popup no longer receives Key Input Events

### ISSUE THREAD

**Issue by Sauermann** [godotengine/godot#59796]
### Godot version

v4.0.alpha.custom_build [74ff5921d]

### System information

Linux, Debain 11, Xfce, Nvidia, Vulkan

### Issue description

The "Sun and Environment Settings" Popup no longer receives key input events. It is no longer possible to change parameters by keyboard.
Bisecting this issue shows that it was introduced in #58490
Fixing this issue by making the popup focused, will likely hide the issue, that causes #59722 or maybe it is the same.

https://user-images.githubusercontent.com/6299227/161280206-249e19f9-4b9e-43a4-b7b3-62ee38eaaec4.mp4

### Steps to reproduce

1. Open Editor
2. Create Node3D
3. Open Sun and Environment Settings
4. Select Sky Energy entryfield
5. Push number-buttons on keyboard

### Minimal reproduction project

Editor issue

**Comment by Calinou** [comment]
cc @bruvzg
