### ISSUE TITLE
Turn off filter "The blur" on 2D files added to a directory in Godot project directory

### ISSUE THREAD

**Issue by HexBlit** [godotengine/godot#59803]
### Godot version

4.0-alpha-5

### System information

macOS Big Sur 11.6.4, NVIDIA GeForce GT 750M 2GB

### Issue description

In Godot 3.x, when you drag 2D assets into a folder you would then have to go to the import tab in Godot editor and uncheck the filter which gets turned on by default. Which is something newer developers do not know that they have to do that. 

There might even be some import flow that avoids that.. but I have never seen it. 

For Godot 4 alpha-5 I see that some things have moved, but if you do the same thing and import 2D files and create a new Sprite they are blurred. When I go look for disabling the "Filter" I see a list in the inspector, but disabled is not an option and not sure this is even correct. 

It would be awesome if when you imported 2D assets you told Godot you needed the filter instead of it auto-blurring your asset.
<img width="3180" alt="turn-off-filter-godot-4 0" src="https://user-images.githubusercontent.com/1005054/161330539-a3db0625-da0d-40a1-9b9f-3381384c0630.png">
 

### Steps to reproduce

- Create a new 2D project 
- Create a Sprite2D node
- Use any of the assets from kenny - https://www.kenney.nl/assets (or your own 2D assets) 
- Copy the 2D assets into your project, i generally copy mine into an assets folder (as i usually git repo my assets for updates)
- Add that 2D asset to the sprite
- Notice that the asset is blurred. 

### Minimal reproduction project

Or just use the associated projects I have been working on for my tutorial series on getting started with Godot 4.

[shmup-demo-3.x.zip](https://github.com/godotengine/godot/files/8400513/shmup-demo-3.x.zip) - Godot 3.4.3 project
[shmup-demo-4.x.zip](https://github.com/godotengine/godot/files/8400515/shmup-demo-4.x.zip) - Godot 4.0-alpha-5 project

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/57679 and https://github.com/godotengine/godot/issues/50592.

The filter will *not* be disabled by default, as most people are not doing 2D pixel art games (and disabling filter has adverse effects for non-pixel art games).

**Comment by HexBlit** [comment]
Thanks, the default in project settings I think is a big win. Setting it to Nearest on the Sprite did work for me (I had thought I tried that earlier) 

Just a random thought, on the Texture import, we have multiple Import As, options, (Texture2D, Image, Font Data), instead of hiding the magic on low resolution textures could make an import as "Pixel" or some such name. Then it is still up to the developer but it is recognized just as much as any other image type.

**Comment by Calinou** [comment]
Closing, as the original issue is resolved.

> Just a random thought, on the Texture import, we have multiple Import As, options, (Texture2D, Image, Font Data), instead of hiding the magic on low resolution textures could make an import as "Pixel" or some such name. 

As I said, this is not technically possible in 4.0 because texture flags are set in the *usage* location rather than the texture file itself. There is no 1:1 mapping between texture files and their usage locations – a single texture can be used in multiple places.
