### ISSUE TITLE
Basis(Vector3, Vector3, Vector3) in GDScript in Godot 4 appears to take the arguments as rows, rather than columns (axes)

### ISSUE THREAD

**Issue by dsnopek** [godotengine/godot#59806]
### Godot version

4.0-alpha5

### System information

Linux, Vulkan, 1070M

### Issue description

This started because I was having a chat on Discord with a user that was convinced that `Basis(Vector3, Vector3, Vector3)` in Godot 3 actually took in matrix rows, rather than the columns (the axes). Part of the reason he thought this, is that printing out the `Basis` will show the matrix as rows:

![Godot 3](https://user-images.githubusercontent.com/191561/161361756-06d60ee4-99fd-4cdf-a985-bcbe7d4a22b9.png)

So, I was going to make a PR to fix the printing of `Basis`.

However, when I went to go try the same code in Godot 4 (where I would have to make a PR first) the results were even more surprising -  `Basis(Vector3, Vector3, Vector3)` _does_ appear to take the rows as arguments in Godot 4:

![Godot 4](https://user-images.githubusercontent.com/191561/161361791-83c43321-9f26-41aa-85b0-8f227e693ee3.png)

Is this a purposeful change that needs a docs fix? Or, is this a bug?

### Steps to reproduce

Here's the code from my screenshot above:

```
	var x = Vector3(0.707107, -0.707107, 0)
	var y = Vector3(0.707107, 0.707107, 0)
	var z = Vector3(0, 0, 1)
	
	var basis = Basis(x, y, z)
	
	print ("x: ", x)
	print ("y: ", y)
	print ("z: ", z)
	
	print ("Basis as string: ", basis)
	
	print ("basis.x: ", basis.x)
	print ("basis.y: ", basis.y)
	print ("basis.z: ", basis.z)
```

We are passing in an x axis of `Vector3(0.707107, -0.707107, 0)` but the `basis.x` is `(0.707107, 0.707107, 0)`. I would have expected them to be the same (and on Godot 3, they are the same)!

**Comment by akien-mga** [comment]
CC @aaronfranke @lawnjelly

**Comment by lawnjelly** [comment]
No idea, consult the source code. `core/math/basis.h` in both cases.

There might be a difference in printing as strings, I think in both cases it says the elements are stored transposed for performance. I usually just swizzle these till it works. :smiley:

**Comment by dsnopek** [comment]
> No idea, consult the source code. core/math/basis.h in both cases.

So, in C++, `Basis(Vector3, Vector3, Vector3)` has always taken rows.

But in GDScript in Godot 3, `Basis(Vector3, Vector3, Vector3)` takes the columns (axes):

https://docs.godotengine.org/en/stable/classes/class_basis.html?highlight=Basis#class-basis-method-basis

I'm not sure where in the engine it made the signature different for GDScript? But it must have been doing some conversion somewhere.

However, in GDScript in Godot 4,  `Basis(Vector3, Vector3, Vector3)` takes rows, just like in C++. The question is: is this on purpose, and we should update the docs? Or, was this an oversight, and we should re-add whatever mechanism made that constructor work differently in GDScript (just like in Godot 3)?

**Comment by dsnopek** [comment]
I found the code in Godot 3 that converts `Basis(Vector3, Vector3, Vector3)` to take columns (axes):

```
	static void Basis_init1(Variant &r_ret, const Variant **p_args) {
		Basis m;
		m.set_axis(0, *p_args[0]);
		m.set_axis(1, *p_args[1]);
		m.set_axis(2, *p_args[2]);
		r_ret = m;
	}
```

https://github.com/godotengine/godot/blob/3.x/core/variant_call.cpp#L1064

Looking in variant_call.cpp in the 'master' branch, there there doesn't appear to be an equivalent method.

**Comment by fire** [comment]
Whatever changes made please ensure that it matches c++.

Previously there was multiple problems in 3.x with Basis not matching C++.

**Comment by aaronfranke** [comment]
@fire Basis uses rows in C++ for optimization reasons (AFAIK), but using columns is vastly more intuitive for users. The exposed behavior for users should very likely be columns.
