### ISSUE TITLE
Update the default environment file

### ISSUE THREAD

**Issue by atirut-w** [godotengine/godot#59809]
### Godot version

v3.4.3.stable.official [242c05d12]

### System information

N/A

### Issue description

When you create a new project, the default env file only have one trailing newline:
![Screenshot-2022-04-02,18-37-54](https://user-images.githubusercontent.com/25323231/161381338-fab09976-46dd-4a4f-a608-ab704215090c.png)

But when you do anything to cause Godot to save stuff, the file ends up having two newlines added:
![Screenshot-2022-04-02,18-38-41](https://user-images.githubusercontent.com/25323231/161381362-19dbd092-e8c7-4ab3-bc5f-0ac11efb1a1e.png)

I know this is a very small issue but it's been getting on my nerves each time I start a new project as a Git repo.

### Steps to reproduce

1. Create new project
2. Check the content of `default_env.tres`(only one trailing newline)
3. Do stuff(create new scenes, Ctrl + S, etc.)
4. Two newlines are added to `default_env.tres`

### Minimal reproduction project

N/A

**Comment by atirut-w** [comment]
The closing keyword in #59813 didn't work for some reason.

**Comment by Calinou** [comment]
> The closing keyword in #59813 didn't work for some reason.

It didn't work because the pull request wasn't merged on the repository's default branch. Unfortunately, GitHub doesn't provide a way to change this behavior.
