### ISSUE TITLE
Function name autocompletion, followed by Ctrl + Z, deletes opening parenthesis, disrupts undo history

### ISSUE THREAD

**Issue by ReturnMinusOne** [godotengine/godot#59805]
### Godot version

v3.4.4.stable.mono.official [419e713a2]

### System information

Windows 10

### Issue description

If the function autocomplete feature is used after the user has typed the parentheses, undoing the change will erase the opening parenthesis, and the rest of the function name will remain no matter how many Undo actions are executed:

https://user-images.githubusercontent.com/35435781/161359437-04909c76-8412-4a99-bd41-5cb1f6235692.mp4

### Steps to reproduce

1. Type a function name, with parentheses.
2. Go back before the parentheses and autocomplete it to a longer function name.
3. Undo multiple times.

**Comment by akien-mga** [comment]
Fixed by #60231.
