### ISSUE TITLE
LineEdit Right-Click clearing selection

### ISSUE THREAD

**Issue by madmiraal** [godotengine/godot#59808]
### Godot version

3.x (99c07c92eb)

### System information

Ubuntu 21.10

### Issue description

In `LineEdit`, when text is selected, you can no longer right-click and cut or copy the selected text, because, when right-clicking, the selection is cleared.

This affects 3.5-beta2 and beta3, it works fine in 3.4.4, 3.5-beta1 and master.

### Steps to reproduce

In a `LineEdit`, select some text, then try right-click and cut or copy the selected text.

### Minimal reproduction project

[RightClickCut.zip](https://github.com/godotengine/godot/files/8402188/RightClickCut.zip)

**Comment by madmiraal** [comment]
Git bisect points to 0ffacff998476b3947deeebb3e63a3f4cd942598 #54353 cc @ConteZero

**Comment by ConteZero** [comment]
When right-clicking a NOTIFICATION_FOCUS_EXIT is received and this code is executed:

```
if (deselect_on_focus_loss_enabled) {
	deselect();
}
```
This does not happens on master branch, so I don't know if this is a bug on 3.x branch or not.

I think that the correct behavior is to NOT send the NOTIFICATION_FOCUS_EXIT when right-clicking, all the program that I've tested do not lose field focus when you right click on it.

**Comment by madmiraal** [comment]
`LineEdit` receives a `NOTIFICATION_FOCUS_EXIT`, because the `PopupMenu` that the right-click creates grabs the focus:
https://github.com/godotengine/godot/blob/fa9b77dbe3d3483e075fc410eb083a033a35743e/scene/gui/popup.cpp#L187
So receiving a `NOTIFICATION_FOCUS_EXIT` is not a bug in 3.x. It just works very differently than in 4.0.

If this isn't easily fixable, we should revert 0ffacff998476b3947deeebb3e63a3f4cd942598.

**Comment by ConteZero** [comment]
I've already tried to comment line 187 on popup.cpp but the the `NOTIFICATION_FOCUS_EXIT` continues to be received from `LineEdit` when right-clicking.

Anyway I've coded a workaround that should avoid the text deselection.

**Comment by akien-mga** [comment]
Fixed by #59827.
