### ISSUE TITLE
FileDialog cannot change directory

### ISSUE THREAD

**Issue by atngames** [godotengine/godot#59828]
### Godot version

3.5 beta3

### System information

linux

### Issue description

When a FileDialog pops-up, it has two bugs.
1 - The already documented small window #58780
2 - It is impossible to change directory (like in master : #58772) in user mode or ressource mode.

### Steps to reproduce

Create a Control,
Attach a FileDialog and a script that popup in _onready()
change resize to true (otherwise you can't even see the folder content)
Try to change directory

### Minimal reproduction project

[test_filedialog.zip](https://github.com/godotengine/godot/files/8404058/test_filedialog.zip)

**Comment by keptsecret** [comment]
On the latest 3.x, 1 seems to have already been fixed (it defaults to a larger size) and for 2, the problem occurs only on user mode so I'll look into that.

**Comment by akien-mga** [comment]
Fixed by #59838.
