### ISSUE TITLE
Missing GDScript binding for RenderingDevice::vertex_array_create

### ISSUE THREAD

**Issue by LaneSun** [godotengine/godot#59837]
### Godot version

4.0.alpha5.official.d7d528c15

### System information

Gentoo GNU/Linux, Vulkan, Intel UHD 770

### Issue description

I am trying to use native GLSL shaders (not for computation, but for rendering) through the RenderingDevice interface.

I've written the following code (I'm cross-referencing `rendering_device.cpp`, there may be some misunderstandings, please correct me if any) :

```
extends Node2D

@onready var rd := RenderingServer.get_rendering_device()

func _ready():
	var shader_file: RDShaderFile = load("res://test-glsl/test.glsl")
	var shader_spirv: RDShaderSPIRV = shader_file.get_spirv()
	var shader := rd.shader_create_from_spirv(shader_spirv)
	
	var points := PackedFloat32Array([
		0, 0, 0,
		0, 1, 0,
		1, 1, 0,
	])
	var points_bytes := points.to_byte_array()
	var colors := PackedFloat32Array([
		0, 1, 0,
		1, 0, 0,
		0, 0, 1,
	])
	var colors_bytes := colors.to_byte_array()
	
	var vertex_buffers := [
		rd.vertex_buffer_create(points_bytes.size(), points_bytes),
		rd.vertex_buffer_create(colors_bytes.size(), colors_bytes),
	]
	
	var vertex_attrs = [RDVertexAttribute.new(), RDVertexAttribute.new()]
	vertex_attrs[0].format = RenderingDevice.DATA_FORMAT_R8G8B8_SNORM
	vertex_attrs[0].location = 0
	vertex_attrs[1].format = RenderingDevice.DATA_FORMAT_R8G8B8_UNORM
	vertex_attrs[1].location = 1
	var vertex_format = rd.vertex_format_create(vertex_attrs)
	
	var blend = RDPipelineColorBlendState.new()
	blend.attachments.push_back(RDPipelineColorBlendStateAttachment.new())
	
	var framebuffer = rd.framebuffer_create_empty(Vector2i(200, 200))
	
	var pipeline := rd.render_pipeline_create(
		shader,
		rd.screen_get_framebuffer_format(),
		vertex_format,
		RenderingDevice.RENDER_PRIMITIVE_TRIANGLES,
		RDPipelineRasterizationState.new(),
		RDPipelineMultisampleState.new(),
		RDPipelineDepthStencilState.new(),
		blend
	)
	
	print(rd.render_pipeline_is_valid(pipeline))
	
	var draw_list := rd.draw_list_begin(framebuffer, RenderingDevice.INITIAL_ACTION_CLEAR, RenderingDevice.FINAL_ACTION_CONTINUE, RenderingDevice.INITIAL_ACTION_CLEAR, RenderingDevice.FINAL_ACTION_CONTINUE)
	rd.draw_list_bind_render_pipeline(draw_list, pipeline)
	var vertex_array := rd.vertex_array_create(3, vertex_format, vertex_buffers)
	rd.draw_list_bind_vertex_array(draw_list, vertex_array)
	rd.draw_list_draw(draw_list, false, 1)
	rd.draw_list_end()
```

During the writing process, I found that the `RDPipelineColorBlendState` object was missing some methods (`create_blend` and `create_disabled`) that caused me to get an error when using `RDPipelineColorBlendState.new()` directly, but it was not a serious problem. I later found the corresponding function in the source code and simulated the behavior of `create_disabled`.

The problem was that when I tried to bind `vertex_array` to `draw_list`, I found that `RenderingDevice` didn't provide the method `vertex_array_create` (this is true, I'm not sure if it's missing or a bug, but I did find the function `_vertex_array_create` in the source code for binding to ClassDB, but it is not actually bound to ClassDB). I've since looked up the creation process in the source, and determined that there is no other way for me to get around this, so I've filed this issue.

I guess the Alpha6 version will be compiled in a few days, so hopefully this issue will be resolved before then :smile: 

Translated with DeepL, sorry for my poor English.

Related Files: [rendering_device.cpp](https://github.com/godotengine/godot/blob/dbd560cb688fed317bfea4d2d630d93e47ac9780/servers/rendering/rendering_device.cpp)

### Steps to reproduce

Press F1 and type "vertex_array_create", you will find it :smile:

**Comment by egiezen** [comment]
I hope this method will be implemented soon, so we can use the abstraction layer to draw things as well. This is quite important.
