### ISSUE TITLE
Add ARMv7 (32-bit), x86 and x86_64 downloads for the official Android editor

### ISSUE THREAD

**Issue by Unknownman21229** [godotengine/godot#59835]
### Godot version

3.5 beta 3

### System information

Android, Processor: Exynos 7580

### Issue description

When you use the apk download it's incompatible

### Steps to reproduce

Get a Samsung Galaxy a5 (2016)
Try to install the apk

**Comment by Calinou** [comment]
The editor APK currently only contains ARMv8 (64-bit) libraries, not ARMv7 (32-bit) libraries which are required on old devices.

**Comment by m4gr3d** [comment]
The provided apk now contains libraries for all supported architectures.
