### ISSUE TITLE
Inconsistent behavior of add_exception() in RayCast (3D) in the 3.5 beta.

### ISSUE THREAD

**Issue by persephonesPoms** [godotengine/godot#59839]
### Godot version

3.5 Beta 3

### System information

Windows 10, GLES3. NVIDIA GeForce GTX 1660

### Issue description

This issue is very specific, and hard to describe. It seems to occur when a collider is created, referenced, destroyed, unreferenced, and then the process is repeated. I recommend simply looking at the minimal reproduction project to get a better idea of what exactly is happening.
The way the issue manifests is that add_exception() fails to properly disable interaction between the raycast and the collider. 
Unfortunately, I don't have enough understanding of Godot's inner workings to make a guess as to why this happens.

**EDIT**

After doing some further investigation, it seems like the issue may be with the raycast retaining exceptions for freed nodes. I'm still uncertain but it seems like it may be the case, as cleaning up the raycast's exception list with clear_exceptions() seems to prevent the issue.

### Steps to reproduce

Raycast Code from the reproduction project.

```gdscript
var new_area 
var ref

func _physics_process(delta):
        #Moving the raycast. May not be necessary.
	global_transform.origin.y = rand_range(5,5.2)
	if is_colliding():
		var att = get_collider()
		print("colliding with: " + str(att))
		if Input.is_action_just_pressed("ui_accept"):
			if ref != null:
				if !ref.get_ref():
					new_area = null
			if new_area != null:
				new_area.queue_free()
				new_area = null
			if new_area == null:
				new_area = load("res://Scen.tscn").instance()
				ref = weakref(new_area)
				for i in new_area.get_node("Stuff").get_children():
					add_exception(i)
			get_parent().add_child(new_area)
			new_area.get_node("Stuff").get_children().size()
			var patt = new_area.get_node("Stuff").get_child(0) 
			#no idea if this is nessecary
			new_area.global_transform.basis = Basis((att.global_transform.basis.get_rotation_quat()*(patt.transform.basis.get_rotation_quat()).inverse()))
			new_area.global_transform.basis = new_area.global_transform.basis.rotated(patt.global_transform.basis.z,deg2rad(180))
			new_area.global_transform.basis = new_area.global_transform.basis.rotated(patt.global_transform.basis.y,deg2rad(90))
			new_area.global_transform.origin = att.global_transform.origin-(Transform(new_area.global_transform.basis,Vector3.ZERO)*patt.transform).origin
			new_area.global_transform.origin = att.global_transform.origin-(Transform(new_area.global_transform.basis,Vector3.ZERO)*patt.transform).origin
			print(new_area)
			
	if Input.is_action_just_pressed("ui_down"):
		if new_area != null:
			new_area.queue_free()
			new_area = null
```

### Minimal reproduction project

Instructions:
Watch the print output.
Repeatedly press ENTER and DOWN ARROW.
Most of the time, it works fine. Occasionally, it breaks down and the raycast exceptions do not get added.
[Minimal Reproduction of Raycast Issue.zip](https://github.com/godotengine/godot/files/8404981/Minimal.Reproduction.of.Raycast.Issue.zip)

**Comment by Calinou** [comment]
@spiderQuentin Please surround large blocks of text with triple backticks like this:

\`\`\`
text here
\`\`\`

This prevents them from taking too much space and also makes sure issue references aren't accidentally created. I edited your comment, but remember to do this next time :slightly_smiling_face:

**Comment by spiderQuentin** [comment]
> @spiderQuentin Please surround large blocks of text with triple backticks like this:
> 
> ``` text here ```
> 
> This prevents them from taking too much space and also makes sure issue references aren't accidentally created. I edited your comment, but remember to do this next time 🙂

Oh thank you! I was wondering why the formatting was off.

**Comment by akien-mga** [comment]
I tried the reproduction project but I'm not sure I understand what I should be looking for in the print output exactly. It consistently prints `colliding with: AreaExtend2:[Area:1269]` from the start on each frame, and pressing Enter prints the reference of the newly added Spatial.

The example project is fairly complex so I'm not sure what the intended behavior is.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
