### ISSUE TITLE
[Mono] `Node.Call()` silently fails

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#59830]
### Godot version

v4.0.alpha.mono.custom_build [a647fb3e6]

### System information

manjaro KDE

### Issue description

When you use `Node.call()` if the args of the function doesnt exacly matches the target node's function it doesnt report to the user that the target function doesnt exists!

PS: I tested only in C# but not sure about gdscript

### Steps to reproduce

* create a script
* copy the following script:
```gdscript
extends Node

func _ready() -> void:
  call("test_func") # should not work because test_func has a number argument, but godot doesnt report this user mistake
  pass

func test_func(number:float) -> void: print(number)

```

```cs
public partial class Test : Node
{

  public override void _Ready()
  {
    Call("TestFunc"); //should not work because test_func has a number argument, but godot doesnt report this user mistake
  }
  
  public void TestFunc(float number)
  {
    GD.Print(number);
  }
}
```

### Minimal reproduction project

N/a

**Comment by KoBeWi** [comment]
Can't reproduce in GDScript:
![image](https://user-images.githubusercontent.com/2223172/161424464-0b6dac33-b6e1-4cd6-8e41-92ba67e51d62.png)
Could be C#-only.

**Comment by nonunknown** [comment]
thanks for testing, so its C# only!

**Comment by GeorgeS2019** [comment]
@KoBeWi  @nonunknown  could the discussion [here ](https://github.com/godotengine/godot/issues/59871#issuecomment-1088022342)be relevant? Explain why c# only.

**Comment by GeorgeS2019** [comment]
@nonunknown  I am tracing which godot4 commit support working mono build. Please keep us update of which commit use.

**Comment by raulsntos** [comment]
I tested and managed to reproduce this in v3.5.beta3.mono.official [3c0d32562] so it's not exclusive to 4.0.
I can also confirm is C# only.
