### ISSUE TITLE
Sprites are not displayed correctly

### ISSUE THREAD

**Issue by InkRobert** [godotengine/godot#59831]
### Godot version

3.5 beta 3

### System information

Windows 11 Pro

### Issue description

I have a sprite for the monitor screen, I also have separate sprites for the buttons, but for some reason a large sprite overlaps other sprites when viewed from a certain angle, but a smaller sprite is in front of a large sprite
![0001](https://user-images.githubusercontent.com/91805483/161428338-eb085ae6-4ba7-4408-b39a-e8ea4cc27bef.png)
![002](https://user-images.githubusercontent.com/91805483/161428349-6a1434b0-634d-4956-a0b5-5b81e4bf8337.png)

### Steps to reproduce

Just move the small sprite in front of the big sprite

**Comment by Zireael07** [comment]
Please post a minimal reproduction project. It can be Z-fighting, it can be transparency sorting issues...

**Comment by InkRobert** [comment]
Here, try to just move the camera in the editor around the big sprite and you will see how the small sprite disappears
[Mini_Project.zip](https://github.com/godotengine/godot/files/8404759/Mini_Project.zip)

**Comment by InkRobert** [comment]
> Пожалуйста, опубликуйте минимальный проект воспроизведения. Это может быть Z-файтинг, это может быть вопросы сортировки прозрачности...

Here, try to just move the camera in the editor around the big sprite and you will see how the small sprite disappears
[Mini_Project.zip](https://github.com/godotengine/godot/files/8404768/Mini_Project.zip)

**Comment by Calinou** [comment]
This is a [transparency sorting issue](https://docs.godotengine.org/en/stable/tutorials/3d/3d_rendering_limitations.html), which is inherent to 3D rendering. There is no way to fully resolve it, but you can avoid it by using alpha testing (alpha scissor) instead of alpha blending. You can also play with the Render Priority option in the material, but it won't work in all cases.
