### ISSUE TITLE
Exporting a GDScript array loads it in COW mode

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#5984]
Tested in Godot 2.1 rc1, Windows 10 64 bits

I want to export the data of a terrain node I'm developping, so the heightmap gets saved. However, I realized Godot loads the array in COW mode, making it impossible to modify properly.
The only workaround I can think of in my use case is... well, copy the entire data into a new array in _ready() D:

Repro:
[ExportArrayCOW.zip](https://github.com/godotengine/godot/files/392191/ExportArrayCOW.zip)

``` gdscript
export var moo = []

func _ready():
    enlarge(moo)
    print("2) back in _ready, size of moo is " + str(moo.size()))

func enlarge(moo_arg):
    moo_arg.resize(2)
    print("1) Size of moo is " + str(moo_arg.size()))
```

Run the main scene, observe the first size is 2, but the caller gets an unmodified array.

Related to https://github.com/godotengine/godot/issues/5277.

**Comment by Keyaku** [comment]
That's because it's copying the data as an argument and you're not returning it, which points to caller's `moo` to be unaffected while the other (now unreferenced) `moo_arg` was actually resized.

You have quite a few possibilities:

1. Alter `moo` directly instead of passing it as argument
2. Send `moo` as argument and return it, resulting in a call like this: `moo = enlarge(moo)`

Either way, the function `enlarge()` could very well be a static function in this case.

**Comment by vnen** [comment]
GDScript should always pass arrays by reference. COW mode is pretty much a bug that can't be solved without breaking compatibility, so you have to work around it (by returning the new array and reassigning the variable, as @Keyaku pointed out).

**Comment by reduz** [comment]
will fix the COW issue by 3.0, where we expect to break compatibility

**Comment by ret80** [comment]
and when the 3.0 version?

**Comment by akien-mga** [comment]
When it's ready.

**Comment by ret80** [comment]
@akien-mga Given that version goes from 8 to 10 months (average figures take 9) it is possible to calculate the approximate time. For example if after 2.1.0 will once 3.0 is 9-10 months. and 2.2.0 if the 3.0 version, and all will be 18 months at best. We would like to know how many more planned 2.x versions?
PS
Who can fill #5967?
I changed "paymentQueue" and added "restored"

**Comment by akien-mga** [comment]
2.1 comes in a couple days, 2.2 in a couple months, and 3.0 likely in Q1 or Q2 2017.

**Comment by bojidar-bg** [comment]
COW mode was removed in master/3.0 already.
