### ISSUE TITLE
Debug navmesh throws errors if navmesh is not pre-baked

### ISSUE THREAD

**Issue by Scony** [godotengine/godot#59845]
### Godot version

3.x

### System information

manjaro linux

### Issue description

In case of runtime 3D navmesh baking it's pretty normal to not have pre-baked (empty) navmesh when running the scene.
If one enables `Debug->Visible Navigation` flag in the above situation, 2 non-critical errors are being thrown:
```
ERROR: Condition "array_len == 0" is true.
   at: mesh_add_surface_from_arrays (servers/visual_server.cpp:1065)
ERROR: Condition "len == 0" is true.
   at: add_surface_from_arrays (scene/resources/mesh.cpp:797)
```

### Steps to reproduce

1. Create a 3D scene with intact `NavigationMeshInstance`
2. Enable `Debug->Visible Navigation` flag
3. Run the scene

### Minimal reproduction project

N/A

**Comment by timothyqiu** [comment]
Fixed by #59846 and #59893
