### ISSUE TITLE
"Error opening file: icon.png" in Project Manager

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#5985]
In Godot 2.1 rc1, Windows 10 64 bits

I get these errors everytime Godot displays or refreshes the list of projects.
```
ERROR: ImageLoader::load_image: Error opening file: icon.png
   At: core\io\image_loader.cpp:54
```
It makes the search feature slower because of all the prints.
It also happened in 2.1 beta and 2.0.4, but not in red: `ERROR OPENING FILE: icon.png`.

I thought it could be related to https://github.com/godotengine/godot/issues/2658 but I see it is about Ubuntu. Apparently a fix https://github.com/godotengine/godot/pull/2652 was merged before in 2015 but the error is still there.

**Comment by akien-mga** [comment]
You probably have old projects in your project manager, which still used the incorrect `icon="icon.png"` in their `engine.cfg` instead of `icon="res://icon.png"`.

**Comment by Zylann** [comment]
I performed all the replace I could and it removes errors, but some projects still have this problem. But I cannot know which of them because the error doesn't gives any context :s

**Comment by akien-mga** [comment]
I guess you have old demos in there, you should probably replace them by the up-to-date ones.

**Comment by Zylann** [comment]
Ok I see the error might come from projects that were outside of my workspace directory, so my search didn't detected them. I selected all projects, removed them, then scanned again my directory and now there is no error.
