### ISSUE TITLE
Error in console: FileAccessWindows::close: Condition ' rename_error ' is true

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#5986]
Godot 2.1 rc1 Windows 10 64 bits

I get this error everytime I close a project, even if I delete the AppData config:

```
ERROR: FileAccessWindows::close: Condition ' rename_error ' is true.
   At: drivers\windows\file_access_windows.cpp:139
```

It happens even on new empty projects.

**Comment by draconequis** [comment]
I'm getting this, too.  It doesn't seem to affect any Godot app, but I'd like to know what's causing it and if it should be addressed.

**Comment by bojidar-bg** [comment]
Error comes from here: [`file_access_windows.cpp:146`](https://github.com/godotengine/godot/blob/2a0ddc1e89ec7b947152c8d0cb132d58f2c00a81/drivers/windows/file_access_windows.cpp#L146)

Why is another question :smile:

**Comment by KoBeWi** [comment]
Does this still happen? I guess it was project-specific.

**Comment by akien-mga** [comment]
I haven't seen new reports about this for a while, so I guess it's no longer reproducible in 3.1.
