### ISSUE TITLE
Closing everything in script workspace prevents mouse input

### ISSUE THREAD

**Issue by Jayman2000** [godotengine/godot#59876]
### Godot version

v4.0.alpha5.official [d7d528c15]

### System information

Arch Linux (I don’t know how to give a version for this), AMD Ryzen 5 3600 (x86_64), AMD Radeon RX 580 Series, Vulkan Clustered.

### Issue description

If you close everything that’s open in the script workspace, then the editor will start ignoring your mouse. Minimizing Godot and then bringing it back up will make Godot pay attention to your mouse again.

### Steps to reproduce

1. Open any project.
2. Go to Help > Search Help.
3. Double click on any of the results to open its documentation.
4. In the script workspace’s list of open scripts/docs, right click and choose “Close All”.
5. Try clicking on anything in the editor.
6. Minimize the editor.
7. Return to the editor.
8. Try clicking on anything in the editor.

**Comment by KoBeWi** [comment]
Can't reproduce, using Windows 10.

**Comment by Calinou** [comment]
@Jayman2000 Do you have an error message about transient windows in the terminal when this occurs?

**Comment by Jayman2000** [comment]
> @Jayman2000 Do you have an error message about transient windows in the terminal or Output panel when this occurs?

No, here’s what I get:

```
[jayman Godot]$ ./Godot_v4.0-alpha5_linux.64 
Godot Engine v4.0.alpha5.official.d7d528c15 - https://godotengine.org
Vulkan API 1.2.0 - Using Vulkan Device #0: AMD - AMD RADV POLARIS10
 
Editing project: /home/jayman/Desktop/Godot/Projects/4/test (::home::jayman::Desktop::Godot::Projects::4::test)
Godot Engine v4.0.alpha5.official.d7d528c15 - https://godotengine.org
Vulkan API 1.2.0 - Using Vulkan Device #0: AMD - AMD RADV POLARIS10
 
[jayman Godot]$ 
```

**Comment by PucklaMotzer09** [comment]
Can not reproduce on Garuda Linux (Arch) (QTile), Godot 4 Beta 2
Intel CPU and AMD GPU

**Comment by Jayman2000** [comment]
> Can not reproduce on Garuda Linux (Arch) (QTile), Godot 4 Beta 2
> Intel CPU and AMD GPU

I can’t reproduce it either.
