### ISSUE TITLE
Editor settings fail to load after a shortcut is removed

### ISSUE THREAD

**Issue by rgrams** [godotengine/godot#5987]
. . . follow-up after discussion in #5373 . . . 

**Operating system or device - Godot version:** 2.1 RC1, Windows 7

**Issue description** (what happened, and what was expected):
If I remove a default editor shortcut (by clicking on the X button next to it in editor settings -> shortcuts), and restart the editor, it has an error and fails to load editor_settings.tres, resetting everything back to the defaults. 

Screenshot of the error: http://i.imgur.com/U7kMWW2.png

Settings files that fail to load for me: ( @reduz ) 
[Bad editor_settings 1.zip](https://github.com/godotengine/godot/files/392419/Bad.editor_settings.1.zip)
[Bad editor_settings 2.zip](https://github.com/godotengine/godot/files/392420/Bad.editor_settings.2.zip)

**Comment by bojidar-bg** [comment]
It comes from https://github.com/godotengine/godot/blob/master/core/variant_parser.cpp#L979

Related to #5912
