### ISSUE TITLE
Ability to export a variable without showing it in the inspector

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#5988]
I am making a custom node and an editor plugin to edit it. This involves a few variables in the node that I need to export so the data is saved. But some of them make little sense in the editor, are too hard to be edited this way, or are impossible to be checked for changes (array/dict). So I need to hide them... but if I remove `export`, the data is lost.

If it doesn't exists already, could we have a way to hide exported variables in the inspector?
Note: the Unity equivalent is [HideInInspector].

**Comment by neikeq** [comment]
You can override `_get_property_list` and return your properties specifying only the `PROPERTY_USAGE_STORAGE` usage (the default one if `PROPERTY_USAGE_DEFAULT` which is the equivalent to `PROPERTY_USAGE_STORAGE | PROPERTY_USAGE_EDITOR`).

Example:

``` GDScript
func _get_property_list():
	return [
		{
			"name": "Prop1",
			"type": TYPE_STRING,
			"usage": PROPERTY_USAGE_STORAGE
		},
		{
			"name": "Prop2",
			"type": TYPE_VECTOR2,
			"usage": PROPERTY_USAGE_STORAGE
		},
		{
			"name": "Prop3",
			"type": TYPE_INT,
			"usage": PROPERTY_USAGE_STORAGE
		}
	]
```

**Comment by Zylann** [comment]
Thanks for the solution :)
But if I do that, `export` becomes useless and I have to rewrite all variables that had it inside this method, even if I want to hide only a few. Sounds like a lot to write in a scripting language where a shortcut already exists, isn't it?

**Comment by neikeq** [comment]
AFAIK You don't have to rewrite your variables if the property name is the same as the variable.

About specifying it as a Material type you use `hint` and `string_hint` for that.

Example:

``` GDScript

var my_material

func _get_property_list():
    return [
        {
            "name": "my_material",
            "type": TYPE_OBJECT,
            "usage": PROPERTY_USAGE_STORAGE,
            # Here we specify it's a resource type
            "hint": PROPERTY_HINT_RESOURCE_TYPE,
            # Now we specify the concrete type (which is "Resource" by default IINW)
            "string_hint": "CanvasItemMaterial"
        }
    ]
```

**Comment by neikeq** [comment]
If you want to make this possible with the `export` keyword, I would rename the issue to something more clear, like requesting the ability to specify the property usage (`PROPERTY_USAGE_*`) in `export`.

**Comment by timoschwarzer** [comment]
I think there should be someting like `export silent (int) var whatever = 0`

**Comment by Zylann** [comment]
`export hidden (int) var whatever = 0` ?

**Comment by bojidar-bg** [comment]
@Zylann Why not put them the other way around? `hidden export(int) var whatever = 0`

Also, here are a few more variations (only some of them involve a new token):
````gdscript
hidden export(int) var whatever = 0 # New token - hidden
export(hidden, int) var whatever = 0
export(storage, int) var whatever = 0
export(PROPERTY_USAGE_STORAGE, int) var whatever = 0 # @neikeq
storage(int) var whatever = 0 # new token - storage
export(int) var _whatever = 0 # notice the underscore -- backward compatible?
````

**Comment by timoschwarzer** [comment]
Yes, hidden or invisible or whatever. Just some keyword before or after export

**Comment by henriiquecampos** [comment]
I think we need to pass another argument to export the variable. In my case I want to show a variable only if a condition fits, if not, the variable is hidden.

**Comment by neikeq** [comment]
IINW, @reduz had plans to modify the `export` keyword to be more similar to PropertyInfo.

**Comment by Zylann** [comment]
@henriiquecampos In Unity this is done easily due to the inspector being shown through immediate mode GUI. If it were to be possible to hide or show a variable dynamically in Godot, you would either expose it from another panel, or show/hide it dynamically with custom script code (if that's possible). a `hidden` keyword would then just be a shortcut to say "this one will always be hidden".

**Comment by arypbatista** [comment]
It would be really useful to have some way to hide an export variable. When working with script inheritance there are some export variables that make sense on parent scripts but automatically handled by sub-scripts. Both intended to be used by the user.

Another work around is for all parent scripts to be abstract classes and only subclasses to export variables, but well...

**Comment by Calinou** [comment]
**Bugsquad note:** This issue still seems to be relevant as of commit https://github.com/godotengine/godot/commit/d87307d850186d27d2c27c5916ec8c4744c14979. There is a workaround available, but the proposed `hidden` keyword hasn't been implemented yet.

**Comment by KoBeWi** [comment]
Souns like a candidate for annotations (#20318)
@export would have current behavior
@serialize could work like hidden export

**Comment by mrzapp** [comment]
Is anyone on this feature? If not, I'll try to make time and make a pull request

**Comment by timoschwarzer** [comment]
@mrzapp Doesn't seem like someone is working on it. But before proceeding, I'd recommend you to talk with the maintainers (@reduz @vnen) about which proposal they'd prefer.

**Comment by takaturre** [comment]
Stupid question: Does not `set_meta` in practice function like a hidden export variable ? 1. The data is serialized and saved along the scene or resource just like an export variable, 2. But it's hidden from the "editor user" unlike export variables.

**Comment by Zylann** [comment]
meta has a different purpose. There is no point relying on it with a script you already know, the point is, you can `set/get` meta on any object without having to put a script on it, or even know if it has one.

**Comment by Flavelius** [comment]
This seems to have been reported in 2016 and i want to add that it's still very much wanted. Now that c# is there and _GetPropertyList is bugged for it, the workaround mentioned above can not be applied. Being able to hide but serialize properties is a not so uncommon requirement.

**Comment by KoBeWi** [comment]
A proposal was created that basically covers this issue: https://github.com/godotengine/godot-proposals/issues/1056
So closing, move the further discussion there.
