### ISSUE TITLE
`AcceptDialog` scaled wrong in editor when using display scale.

### ISSUE THREAD

**Issue by RoniPerson** [godotengine/godot#59882]
### Godot version

3.4.4.stable

### System information

Windows 10

### Issue description

I am using `AcceptDialog` in an editor plugin. When I set the display scale in the editor settings to 125% the ok button extends over the borders of the dialog. By resizing with the mouse the buttons get positioned inside.

![grafik](https://user-images.githubusercontent.com/67514656/161591079-4b3b4c4c-90dc-47be-8093-44b4e7a613b3.png)

### Steps to reproduce

- create an editor plugin
- create a scene and add an `AcceptDialog`
- add an script and let it popup somehow
- change the display scale to 125%

**Comment by kleonc** [comment]
Can't reproduce, please upload mininimal reproduction project.

**Comment by lostminds** [comment]
I just encountered what I think is this same bug in 4.2.dev5 and it's not editor or plugin-related as the tags here would suggest but it simply seems like the layout containers/rules for the AcceptDialog are configured incorrectly. What I was trying to do is to get retina HiDPI support by on windows by setting the content_scale_factor for the window and scaling the size by the same factor. This generally works, even if it's weird that this isn't handled automatically by the project hiDPI setting being enabled as I'd expect. 

However, for the AcceptDialog it seems the vertical offset of the buttons is also affected by resizing the window when the content is scaled. So as you can see below, when scaling both the window size and content_scale_factor the result is that the buttons move more than intended and at 2x (macOS "retina" scaling) the buttons are outside the dialog making it unusable.

https://github.com/godotengine/godot/assets/17763524/b7b74d4a-bc08-4eb9-93fa-e8d72093f5f2

This is of course on 4.2, but it sounds like it's the same bug that was present in 3.4

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you add the requested details this can be reopened
