### ISSUE TITLE
Re-importing loop when using a plugin

### ISSUE THREAD

**Issue by ArcFutahito** [godotengine/godot#5990]
Linux x86, Godot 2.1 beta

After using Tileset Importer by Nullifier https://github.com/Nulifier/GodotTileSetImporter and importing created tileset into the scene, my godot is stuck in an infinite loop of reimporting the tileset.res. Deactivating plugin doesn't help. Only if resource is deleted from the project it stops trying to reimport it.

**Comment by Sslaxx** [comment]
Has this plugin worked with previous versions of Godot (such as 2.0.x)? I also note it's not been updated in two years, and various things (such as the plugin/module interface) have changed somewhat in that time.

**Comment by ArcFutahito** [comment]
Not sure, I've added it only to 2.1. Still, I don't think it's plugin's fault.

**Comment by bojidar-bg** [comment]
Related/duplicate of #4919?

**Comment by ArcFutahito** [comment]
I'd say yes

**Comment by akien-mga** [comment]
Is this still valid in 2.1.x and in master/3.0-alpha?

**Comment by ArcFutahito** [comment]
I'll check it in a couple of days.

**Comment by ArcFutahito** [comment]
Can't reproduce
