### ISSUE TITLE
[OSX] DirAccessUnix.current_is_dir return false after changing dir

### ISSUE THREAD

**Issue by profelis** [godotengine/godot#5991]
**Operating system or device - Godot version:**
OSX, Godot master git version

**Issue description** (what happened, and what was expected):

**Steps to reproduce:**
```
String dir = "/Applications/";
DirAccess *da = DirAccess::create(DirAccess::ACCESS_FILESYSTEM);
  if (da->change_dir(dir)==OK){
    print_line(da->current_is_dir() ? "DIR" : "NOT DIR"); // NOT_DIR
}
```

**Link to minimal example project** (optional but very welcome):

**Comment by vnen** [comment]
That's not what `current_is_dir()` does. From the [documentation](http://docs.godotengine.org/en/latest/classes/class_directory.html#class-directory-current-is-dir):

> Return whether the current item processed with the last `get_next` call is a directory (`.` and `..` are considered directories).

So this function is meant to be using when you listing the directory contents with `list_dir_begin()` and `get_next()`.

**Comment by profelis** [comment]
Ups, thanks! Close issue
