### ISSUE TITLE
Camera in Frustum mode has got minimal FOV of 90 degrees

### ISSUE THREAD

**Issue by Kobrar** [godotengine/godot#59914]
### Godot version

3.4.4

### System information

Ubuntu 20.04, Intel i5-2410u

### Issue description

```fov``` of a ```Camera``` in ```PROJECTION_FRUSTUM``` mode is determined by ```size``` rather than ```fov```. ```size```, however, probably because of the ```PROJECTION_ORTHOGONAL```, is limited to 0.1 < ```size``` < 16384. I have empirically determined, that an object of size 10.0 viewed from a distance of 5.0 in mode ```PROJECTION_FRUSTUM``` with tightest fov achieved by setting ```size``` to 0.1 fills the view. That results in fov of 90 degrees. This is outside of the usual range. Default fov is 70.0 in ```PROJECTION_PERSPECTIVE``` and often 60.0 is used. I need about 12.0 degrees in my application. The restriction on ```size``` does not make sense for ```PROJECTION_FRUSTUM```. Also I'm probably the first person who needs Y-shearing, which is why I encountered this problem.

### Steps to reproduce

1. Set Camera to ```PROJECTION_FRUSTUM``` mode.
2. Try to achieve a tight fov of below 90 degrees.

Alternatively
1. Create 2 cameras.
2. Set one to ```PROJECTION_PERSPECTIVE``` mode and ```fov``` 90.
3. Set the other ```PROJECTION_FRUSTUM``` mode and ```size``` 0.1.
4. Notice how the view is the same between the two cameras.
5. Try to achieve a tighter view from the ```PROJECTION_FRUSTUM``` mode and fail.

**Comment by Calinou** [comment]
> 3.2.3

[Godot 3.2.x is not supported for bug fixes anymore](https://docs.godotengine.org/en/stable/about/release_policy.html#release-support-timeline), so please upgrade to [3.4.3](https://godotengine.org/article/maintenance-release-godot-3-4-3) and check if the issue still occurs there.

**Comment by Calinou** [comment]
I can confirm this on `master` 10dc3284f (Linux, NVIDIA). Setting the Frustum camera's `size` property to 0.01 in a script has no effect, as the value is clamped in the C++ code.
