### ISSUE TITLE
Godot editor APK not installing on Xiaomi Redmi S2

### ISSUE THREAD

**Issue by cihanaknn** [godotengine/godot#59928]
### Godot version

3.5.3 android beta

### System information

Phone model: Xiaomi Redmi S2 (32GB)Android vers:9    Chipset=Qualcomm Snapdragon 625 MSM8953 CPU core:8 64 bit GPU:Adreno 506

### Issue description

I got an error while installing the application. Then I investigated the cause of the error and tried again from a different APK installer. The error I got was:INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113
 The application does not contain native code compatible with your device please fix this

### Steps to reproduce

INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113

**Comment by Calinou** [comment]
Your device's SoC supports ARMv8 (64-bit ARM), which is strange as [ARMv8 is the only library type currently included within the APK](https://github.com/godotengine/godot/issues/59835).

This makes me think that the ROM you're using is 32-bit, presumably to save on RAM. I didn't even know Google allowed this…

**Comment by akien-mga** [comment]
Is it about the Android editor as Calinou assumed, or a build of your own project? If the latter, you might have simply exported an APK without arm64v8 library.

**Comment by akien-mga** [comment]
No answer, closing.
