### ISSUE TITLE
GraphNode title gets trimmed instead of resizing the node

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#59924]
### Godot version

4.0 c630c2001dbe2e25e0d372bd22ce85cdc2822eb0

### System information

Windows 10 64 bits GLES3 GeForce GTX 1060 6GB/PCIe/SSE2

### Issue description

I want to give a title to a GraphNode, which can also change later. However it keeps getting trimmed instead of resizing the node. In Godot 3, the node resizes correctly.

![image](https://user-images.githubusercontent.com/1311555/161843804-bcd0c251-0203-43a5-b492-f879346a3b82.png)

I debugged it a little, it seems it could have been introduced when TextServer was added. When the minimum size of the node is computed, `title_buf` is queried for its size, unfortunately TextServer always trims it to a much smaller size for some reason, so it never resizes...

### Steps to reproduce

My use case is programmatic, but it can be reproduced in editor.
Create a GraphEdit, add a GrapNode to it, and start typing a title. Observe the node doesn't resize as you reach the width of the node.

**Comment by RechieKho** [comment]
I will try to tackle this problem.
I found out that as long as the title's text does not get longer than the UI title bar, it resize well. As soon as the length of the title exceed the title bar, the minimum size of the node won't change. So the minimum size of the node update only update when the title text is changed **and** the length of the title text is shorter than the title bar of the node. I think making it update the minimum size of the node at all time will fix the problem.

**Comment by Zylann** [comment]
Updated my PR, it was referring to the wrong issue ^

**Comment by RechieKho** [comment]
I see, good to know that this is fixed
