### ISSUE TITLE
GDScript 2.0: `rpc` and `rpc_id` do not work without arguments

### ISSUE THREAD

**Issue by Noiros** [godotengine/godot#59939]
### Godot version

4.0 alpha 6

### System information

Windows 11, GLES3, Rx 5700 XT, Ryzen 7 3600x

### Issue description

the rpc or rpc_id works only when it has an argument
(it is a regression, in alpha 4 the project sends correctly)

### Steps to reproduce

simply open the server project and the client project and launch them both, the server sends only the packet with argument

### Minimal reproduction project

[RPC Bug (fast patch plz).zip](https://github.com/godotengine/godot/files/8426839/RPC.Bug.fast.patch.plz.zip)

**Comment by Noiros** [comment]
I could also notice that on headless server a lot of packet doesn't pass

on ubuntu (headless)
![image](https://user-images.githubusercontent.com/66034941/162004990-ac12481d-d334-4512-b2ea-4e7bb001305d.png)

same in local 
![image](https://user-images.githubusercontent.com/66034941/162005129-d6af6882-0cfb-48fa-82ff-d2dc7418eaa0.png)

**Comment by mhilbrunner** [comment]
Just to clarify: There is no error message, but without arguments, it just does nothing?

**Comment by Noiros** [comment]
my bad, no problem in alpha 5 but in alpha 6 yes, and here is the server side warning:
![image](https://user-images.githubusercontent.com/66034941/162023167-37f74847-b8be-45b8-9262-77b9211fa606.png)

**Comment by mhilbrunner** [comment]
cc @Faless

**Comment by Noiros** [comment]
okay, thanks you

**Comment by KoBeWi** [comment]
Closing in favor of #65689, which is the same issue.
