### ISSUE TITLE
Implement 3D editor touchscreen controls in the editor

### ISSUE THREAD

**Issue by Entonnado** [godotengine/godot#59938]
### Godot version

Godot 3.5.0 beta for android

### System information

Android 11 

### Issue description

The app is a revolutionary thing but there are no option to scroll through the main 3d UI ... The android users are stuck in the same position of the screen while they open it 

Also the options are too small and when we try to enlarge the UI most option goes hidden..... 

Also please make the Android app more mobile friendly please. 

### Steps to reproduce

Adding option to scroll through the 3d interface 

Making app mobile friendly .....you can refer the it's magic game Engine UI for making this mobile friendly

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot-proposals/issues/3931.
