### ISSUE TITLE
Always on-top dialogs have extra length at the bottom that copies whatever is underneath the dialog (DisplayServer regression)

### ISSUE THREAD

**Issue by PhoenixFlame101** [godotengine/godot#59945]
### Godot version

v4.0.alpha.custom_build [77843355a]

### System information

openSUSE Tumbleweed 20220403, KDE Plasma 5.24.4, X11, Intel UHD Graphics 630

### Issue description

Always on top dialogs appear to take up more space that the actual visible size, and this extra space copies what is underneath the dialog.

So far, I have observed this behavior with the (Re)Importing Assets dialog and the Pre-Import Scene dialog. It's probably an issue for all similar dialogs, but I can't confirm since the disappear almost immediately and it's very to test them.

![image](https://user-images.githubusercontent.com/51199011/162023108-adef3ebd-e145-482f-80a3-75df8bff2e27.png)

https://user-images.githubusercontent.com/51199011/162022613-bdbfaf33-fa44-4efd-abaa-891a8b42d592.mp4

I understand this might be very low-priority, but i still felt that I should report it.

### Steps to reproduce

- Import any assets to a project to trigger the (Re)Importing Assets dialog and drag another window under it to show the extra area
- While any asset should work, a large asset will give you more time to test since it takes longer to import. You can use something like this .obj file - [waterworks.zip](https://github.com/godotengine/godot/files/8428848/waterworks.zip).
- You can also go to Advanced import settings for the .obj file to trigger the Pre-Import Scene dialog

**Comment by PhoenixFlame101** [comment]
This issue might also need a `needs testing` label or something similar since the `display_server` file is different for different platforms and display servers.

Would appreciate it if people using other display managers or platforms can help me figure out if this is specific to X11 or not.

**Comment by akien-mga** [comment]
Is this still reproducible in the latest 4.0 betas?

**Comment by PhoenixFlame101** [comment]
Seems to be fixed after the dialog was changed!

I'm unable to reproduce it on beta 12 and `master` both. Closing the issue.
