### ISSUE TITLE
_ready() is not called in controls loaded by plugins

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#5994]
Godot 2.1 rc1 Windows 10 64 bits

I made a scene in order to design a part of my plugin's UI, so I can instance it easily. However I noticed that _ready() is not called at all, making the main script unable to initialize properly.

The doc is showing an example with _enter_tree(), which makes me think that it's intented. But why? _ready() would be as useful in tools as it is in games.

**Comment by Zylann** [comment]
Ooops. Forgot the `tool` keyword.

**Comment by Sslaxx** [comment]
Could some sort of warning by Godot be given in cases like this?

**Comment by Zylann** [comment]
@Sslaxx how would Godot know? You could instance things in the scene without actually requiring scripts on them to have the `tool` keyword. However, if you instance things in the editor it is possible to have a warning.
