### ISSUE TITLE
 Unsupported class file major version 62 on custom android build

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot#59948]
### Godot version

3.3.3 stable

### System information

Vega 8, Rizen 3200G, manjaro OS

### Issue description

I get compiler errors when trying to compile an android build with admob ads.
Using 3.3.3 because that's the last version supported by the admob plugin.

Seems a version issue with current android studio.

Here's the error console output.

```

FAILURE: Build failed with an exception.

* Where:
Settings file '/home/cris/Documentos/GitHub/Godot-4/Japanese Vocab Teacher/android/build/settings.gradle'

* What went wrong:
Could not compile settings file '/home/cris/Documentos/GitHub/Godot-4/Japanese Vocab Teacher/android/build/settings.gradle'.
> startup failed:
  General error during semantic analysis: Unsupported class file major version 62
  
  java.lang.IllegalArgumentException: Unsupported class file major version 62
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:196)

```

### Steps to reproduce

Try to compile an android apk with admob ads.

**Comment by Calinou** [comment]
From a [quick web search](https://javaf1.com/snippet/unsupported-class-file-major-version-error-solution):

> A typical use case using IntelliJ or Android Studio IDE with gradle build tool. If you have a project that uses JDK 14 with gradle 6.3 and you upgrade the JDK to version 16 then you get the error Unsupported class file major version 60 because gradle 6.3 is not compatible with Java 16. So the root cause is independent from your IDE. It can be also Eclipse, Visual Studio Code or any other.
>
> The solution is to use comaptible JDK and gradle versions. See [Java major numbers](https://en.wikipedia.org/wiki/Java_class_file#General_layout) and [gradle compatibility matrix](https://docs.gradle.org/current/userguide/compatibility.html).

**Comment by ca3games** [comment]
> From a [quick web search](https://javaf1.com/snippet/unsupported-class-file-major-version-error-solution):

Thanks, I wasn't able to find a solution that applies to godot, and maybe this issue would appear later to more godot users when they google it.

So, which are the required gradle and JDK versions for godot 3.3.3?

**Comment by Calinou** [comment]
> So, which are the required gradle and JDK versions for godot 3.3.3?

Which JDK version are you currently using? I'd probably try using OpenJDK 8 as usual.

**Comment by ca3games** [comment]
> Which JDK version are you currently using? I'd probably try using OpenJDK 8 as usual.

Using the AUR version of the JDK that comes in manjaro store.
The manjaro store says 18-1 as version to install.

**Comment by ca3games** [comment]
Thanks, can confirm now the error dissapears if you remove jdk 18 and install openjdk8
Will leave this issue page now for future google searches.
:)
