### ISSUE TITLE
Cannot create a new folder via in-editor file manager

### ISSUE THREAD

**Issue by AssimiIation** [godotengine/godot#59959]
### Godot version

Godot_v4.0-alpha6_linux.64

### System information

Linux Ubuntu 21.10 Intel® Core™ i7-10875H CPU @ 2.30GHz × 16 RTX 2060 Vulkan render

### Issue description

When attempting to create a new folder by right-clicking in the FileSystem dock and selecting "New Folder..." and after entering a folder name the error message "Could not create folder. File with that name already exists" pops up no matter which name is entered, even when the file manager is empty

### Steps to reproduce

- Open a brand new Godot 4.0 alpha 6 project
- Right click in FileSystem dock area
- Select "New Folder..." and enter a name
- Regardless of the name entered, error prompt "Could not create folder. File with that name already exists" pops up, folder is not created

**Comment by akien-mga** [comment]
Thanks for reporting this issue. It's the same as #59956 which has already been fixed, will be solved in the next build.
