### ISSUE TITLE
Help page is not rendered correctly after reopening the Editor

### ISSUE THREAD

**Issue by hurikhan** [godotengine/godot#5995]
**Operating system or device - Godot version:**
Arch Linux x86_64 - Godot Engine v2.1.rc1.custom_build (0b595f94c47a9144dbe9c200a8057558b0c4f839)

**Issue description** (what happened, and what was expected):
Still opened help pages from a previous Editor session are not rendered correctly.

Newly opened (ok - rendered with different fonts):
![Help page newly opened](https://i.snag.gy/V8lWJE.jpg)

Still opened (not ok - rendered with a single font):
![Help page still opened](https://i.snag.gy/mSU7bt.jpg)

**Steps to reproduce:**
1. Open a random project in the Editor
2. Switch to the "Script" view
3. Close all help pages
4. Open a help page (e.g. AABB) <-- rendered ok
5. Close the Editor
6. Reopen the same project in the Editor
7. Switch to the "Script" view
8. Select the already opened help page <-- rendered not ok

**Comment by bojidar-bg** [comment]
I have a strange feeling that this was fixed on master, can you confirm?

**Comment by akien-mga** [comment]
Assuming fixed, at least we haven't had newer references to it in almost a year.
