### ISSUE TITLE
Animation Tree fakes default keyframes for non-keyframed values

### ISSUE THREAD

**Issue by jcarlosrc** [godotengine/godot#59961]
### Godot version

4.0 alpha 5 and alpha 6

### System information

Windows 10

### Issue description

Tracks that are not keyframed should not be animated. However, Animation Tree is using default values (at least for position and color) as they were keyframed values, causing animation issues.

In the videos: First, The expected behavior (Godot 4.0 Alpha 4 and all previous version): Sphere does not move because it is not keyframed in the one shot animation. Second, Alpha 5 and 6: the sphere moves to its default (0,0,0) position, however there is not keyframed at all at that position.

 This issue happens also with color. To see it, make the Color Rect node visible and play the game. Transparency goes back to 0 causing scene not to be visible. This can not be an on-purpose behavior, because each animation should contain a track for every single node and position to behave properly, which does not make sense.

https://user-images.githubusercontent.com/8985409/162071322-1e266946-d754-4daf-bdef-c447adb3d223.mp4

https://user-images.githubusercontent.com/8985409/162071347-8b116b85-5596-457a-946f-685b2eb53a3b.mp4

### Steps to reproduce

Play the game with alpha 4 and alpha 6 versions. Pressing "Enter" activates the one shot animation, showing the bug.

### Minimal reproduction project

[BugReportAnimTreeAlpha6.zip](https://github.com/godotengine/godot/files/8430623/BugReportAnimTreeAlpha6.zip)

**Comment by TokageItLab** [comment]
As written in https://github.com/godotengine/godot/issues/59474#issuecomment-1078598772. At least the ColorRect behavior is a bug, but the missing key animation is now blended with the initial value, which is an ideal change to make the blending result always consistent.

**Comment by jcarlosrc** [comment]
First, the color rect behavior is not an isolated bug, is the result of the same behavior. 
Secondly. As I can see it, it does not make sense. If we have an animation with just one track and need to mix it with another animation having 100 tracks. We want it just to mix the one track. However, we will need to copy all the 100 tracks and its keyframes to have the desired effect? In the videos avobe, I will need to copy all the keyframes for the sphere position to make it still. In this case is only one position, but it could be much more complex.This was never an issue before and should not become one now.
Third: Keyframing values the user never intented to keyframe can not be an ideal solution at all. If we keyframe a value and only one value is because we want that behavior. Mixing with a default value is the same as keyframing a value that was never intended to be keyframed.

**Comment by TokageItLab** [comment]
If we don't want to blend with the 0 value, we need at least some intended default value similar to the ResetTrack solution.
@reduz Do you think AnimationLibrary will solve this?

**Comment by jcarlosrc** [comment]
@TokageItLab Please consider the following minimal situation: We have two properties p and q. We have animations A1 and A2 with keyframes for both p and q. And a third animation B with only keyframes for q. We want to mix A1 or A2 with B, replacing only property q. Imagine p and q as legs and arms. We only want to replace arms, but let legs unaltered. We want keyframes for property p to be played unaltered and replace q with B. How could we achieve this under the current behavior?
 * If we mix A1 or A2 with B, the engine will create a default keyframe for p in B, causing property p to change (as seen in the videos).
 * If we "complete" animation B to include property p, we will need to decide how. If we copy A1, it will mess up animation A2 when we want to mix B with A2. The only solution is creating another B, to match with each A. This is not a solution, because we could have many A, and will need to create as many B, leading to an exponential number of copies just for a simple behavior.

The solution is just not mixing property p, which does not have keyframes in B. In this way, only keyframed tracks get mixed, which makes sense.

**Comment by jcarlosrc** [comment]
> As a result of the fix in #59490, the missing Color track is indeed blended with the transparent value, but it is not a bug. It is just blended with the init value (zero). The bug in #59474 is due to the fact that the default Alpha value for Color is actually 1 instead of 0. This breaks the alpha channel blend even when the Color track is not missing. You must first understand the difference.
> 
> If we don't want to blend with the 0 value, we need at least some intended default value similar to the ResetTrack solution.
> 
> @reduz Do you think AnimationLibrary will solve this?

Yes, the color is a bug because it has not a missing track. My fault.

**Comment by TokageItLab** [comment]
Not blending one of the tracks when there is a missing track creates inconsistency. For example, it makes a huge difference in blending at 0 and 0.01, moreover the same blend value can produce very different results depending on when the blending is done.

I think there is a way to minimize blend tracks is for the user to insert an intended default keyframe as ResetTrack, but that implementation was rejected once https://github.com/godotengine/godot/pull/57675#issuecomment-1067953220, so we need to discuss with @reduz whether to implement this again, or an alternative implementation.

**Comment by jcarlosrc** [comment]
The user cannot define a proper default keyframe value because it is not possible. Any default keyframe will mess up another animation. For instance, if we define idle leg pose as default, it will mess up a run animation. And if we define a run default, it will mess up the idle animation. 
While some inconsistency is indeed a problem, the current implementation has created a bigger problem in the basics of animation. Now it is not possible to mix arms without messing up legs. This is a core animation feature. We can't even use track filtering because it does not work. In the minimal project try to fix the sphere position filtering the oneShot to allow onlynly box position track: It does not work. The sphere still moves to the default position. Right now animation tree is just broken.

**Comment by TokageItLab** [comment]
As I explained above, "do not blend" is incorrect. It is correct to say "treat the weight as 1.0 for the non-missing tracks".

I say again, this is problematic from a consistency and technical standpoint: it is unnatural to have no animation when the weight is 0, but to have animation with a weight of 1 when the weight is 0.01. Also, the fact that it is only done on certain tracks means that the end result of the blend will be different depending on the order in which the animations are played.

My idea is to record the position of the sphere as a default value in ResetTrack. For example, Skeleton::Bone uses Rest instead of zero as its default value. This means that ResetTrack will act as Rest for animations other than Skeleton::Bone. This will cause missing tracks to be blended with the Reset animation's track value. A Skeleton::Bone never have more than one Rest; any value that is not a Rest should be treated as a PoseAnimation. Likewise, any value away from the Reset track as the default value should be keyframed as an animation.

**Comment by jcarlosrc** [comment]
Let's say we record the position of the sphere as a Reset Track. This will solve that specific case. But what if we want to mix the same box animation with another sphere animation. Such Reset track will get blended. However we just want the the new sphere values to show and mix only box values. We will need to keyframe the new sphere values also in the box animation. Imagine this happening to a fourth sphere animation we want to blend with the same box animation. We will need to create another box animation just to store the new sphere values. And if we consider other tracks, let's say a triangle? We will need to create box animations with all the combinations of sphere and the other tracks.

**Comment by TokageItLab** [comment]
You just need to record ResetAnimation as the default value for the box as well. Also, if the problem is that the combination of spheres and boxes is huge, then just separate the AnimationTree for that.

**Comment by jcarlosrc** [comment]
@TokageItLab I am not sure we understand each other. Please open the minimal project in this message, there is also a video. The box has a walk and idle animations. The sphere has a Hello animation and there is also a Reset animation. I just want the sphere to say hello and let the box play idle-walk. The animation tree set up is straightfoward: a Transition to choose idle or walk for the box and a OneShot to mix the sphere movement. It is not working in Alpha 6. Now, please try yourself to fix the project and get the desired behavior: let the box playing idle and walk freely and mix the hello sphere animation. I will really apreciate it having the solution.

[BugReportAnimTreeAlpha6.zip](https://github.com/godotengine/godot/files/8457887/BugReportAnimTreeAlpha6.zip)


https://user-images.githubusercontent.com/8985409/162594285-3fed91e7-d5ea-4e73-b3dc-03a6acb9f518.mp4

**Comment by TokageItLab** [comment]
@jcarlosrc I salvaged the ResetTrack solution as #60093. By the way your filter settings are inverted.

If it merge #60093 and set the filters correctly, it should work as you want.

https://user-images.githubusercontent.com/61938263/162601001-eacc23a7-3ade-4c50-994e-be958503a80e.mov

**Comment by jcarlosrc** [comment]
So Alpha 5 / 6 is indeed broken and needs fixing by merging the required commit.

Please consider that this was a minimal example that should run out of the box without hacks or workarounds. I wish the provided solution is scalable to complex scenes and gives us a practical and simple workflow just as we had until G4Alpha 4. 

Consider that with the provided solution we will need to add tracks for all animated objects to every animation in the animation tree. If we animate a new object, we will need to add it also to all pre-existing animations. Maybe there can be an automated solution. I still think that users should not be forced to make keyframes for things we dont want to be animated. The engine should accept that and process it adequately. It is more efficient and simpler that each animation to only have the keyframes it really needs.

Thanks again.

**Comment by TokageItLab** [comment]
It is not "broken" but rather "inconvenient."

In fact, as you said, it is possible to work around this by duplicating the animation track so that it is not missing, but I know it is inconvenient and we need to merge #60093 as an enhancement.

@jcarlosrc If you are able to build Godot, it would be appreciated if you could test it and send me feedback/consensus, but if not, in the meantime, please answer if the video I sent you above works as you think it should.
