### ISSUE TITLE
`rpc(StringName("function_name"))` no longer works in 4.0 alpha 6

### ISSUE THREAD

**Issue by DanielKinsman** [godotengine/godot#59972]
### Godot version

4.0alpha6

### System information

arch linux

### Issue description

In alpha 5 `rpc(StringName("function_name"))` worked whereas in alpha 6 it doesn't and only `rpc("function_name")` works.

Please close this if it is intended and just undocumented or whatever, or if I'm not supposed to be reporting bugs for alphas.

### Steps to reproduce

Run the minimal reproduction project

### Minimal reproduction project

[rpctest.zip](https://github.com/godotengine/godot/files/8440704/rpctest.zip)

**Comment by Faless** [comment]
Related to #59939 .
When calling `rpc` with a `StringName` and no other arguments the call fails in the gdscript vm.
Will need some further investigation as it seem a gdscript and/or core binding issue.

**Comment by Faless** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/59939 which has more details.
