### ISSUE TITLE
Godot doesn't recognize new FBX files

### ISSUE THREAD

**Issue by svprdga** [godotengine/godot#59978]
### Godot version

4.0.alpha6.official [e4f0fc50f]

### System information

Linux Mint, Vulkan, GTX 1070

### Issue description

The engine is not automatically recognizing FBX files. 

FBX assets cannot be used right now (I don't know if there is any new requirement for this kind of files in Godot 4).

### Steps to reproduce

1. Create a new 3D project.
2. Drag and FBX file to the files dock.
3. Alternatively, add directly a FBX file to the project using the system files browser.

**Comment by akien-mga** [comment]
See https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-6, you should download FBX2glTF linked in the blog post and set a path to it in the editor settings.

This will be improved in future releases to make it clearer (https://github.com/godotengine/godot/pull/59810) but for now this is intended behavior.

**Comment by svprdga** [comment]
Thank you.
