### ISSUE TITLE
Leading spaces may push text outside `Label` autowrap boundary in 3.x

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#59985]
### Godot version

3.x (14856b1dbd7b428341f00f8819d53935d555b72c)

### System information

Arch Linux, GLES 3, Mesa Intel(R) UHD Graphics (CML GT2)

### Issue description

When autowrap is enabled, long leading spaces in `Label` may push text outside the boundary.

| Left Align | Center Align | Right Align | Fill |
| -- | -- | -- | -- |
| ![ksnip_20220407-221947](https://user-images.githubusercontent.com/372476/162221153-018e3c44-815e-497e-b179-25428456149e.png) | ![ksnip_20220407-222001](https://user-images.githubusercontent.com/372476/162221162-70133d89-c3e9-4342-bc93-ff720e56a0dc.png) | ![ksnip_20220407-222013](https://user-images.githubusercontent.com/372476/162221166-9935d538-4e2d-43f7-985a-5ec724cc8b1b.png) | ![ksnip_20220407-222024](https://user-images.githubusercontent.com/372476/162221168-5a4d994e-ed3c-454d-a8f7-f59f0c3b3d4e.png) |

Not in `master`. I believe it has been like this for quite a few versions.

### Steps to reproduce

Create a Label, enable Auto Wrap, put lots of spaces before actual text.

### Minimal reproduction project

[LabelSpace.zip](https://github.com/godotengine/godot/files/8443780/LabelSpace.zip)

**Comment by ZheisterCoding** [comment]
Hi, i would like to attempt on this issue :)

**Comment by ZheisterCoding** [comment]
Hi, this issue seems fine in the master, how do I work on it on other branches? the other branches have these issue, do I fix this issue in the other branches?

**Comment by timothyqiu** [comment]
> do I fix this issue in the other branches?

Yes. TextServer on `master` fixed lots of typography bugs but it's not like backportable. So this only has to be fixed on the `3.x` branch.

**Comment by ZheisterCoding** [comment]
alright, ill try attempting this issue :)

**Comment by akien-mga** [comment]
Fixed by #60233.
