### ISSUE TITLE
Error when using Blender import but not GLTF directly: "Invalid image definition in glTF file, it should specific an 'uri' or 'bufferView'."

### ISSUE THREAD

**Issue by timshannon** [godotengine/godot#59986]
### Godot version

v4.0.alpha.mono.custom_build [9c6c71bbd]

### System information

Ubuntu 21.04 using Blender 3.1.1

### Issue description

I get import errors with specific scenes when using the blender import workflow that don't happen when importing a gltf or glb file directly.

The errors are as follows:
```
  Invalid image definition in glTF file, it should specific an 'uri' or 'bufferView'.
  Invalid image definition in glTF file, it should specific an 'uri' or 'bufferView'.
  Invalid image definition in glTF file, it should specific an 'uri' or 'bufferView'.
  modules/gltf/gltf_document.cpp:3255 - Index image = 1 is out of bounds (state->images.size() = 0).
  modules/gltf/gltf_document.cpp:3255 - Index image = 2 is out of bounds (state->images.size() = 0).
  modules/gltf/gltf_document.cpp:3255 - Index image = 0 is out of bounds (state->images.size() = 0).

```

### Steps to reproduce

The error only seems to happen in very specific circumstances so see the attached project to replicate it.

You need to have a blender file which:
1) Has a linked collection
2) In that linked collection there are materials with packed textures
3) The Materials "Unpacked Enabled" option needs to be disabled in the Godot Blender Import settings

If I export a GLTF file with matching settings to those in the blender import, I don't get any errors.  If I change any of the above values (for example, appending the collection rather than linking, or unpacking textures in the linked collection), there is no error.  This might point to this being a Blender issue, however I have no issues with these scenes when I export to GLTF directly.

A possibly solution to this may be to export to GLB if materials aren't getting unpacked?

### Minimal reproduction project

[Bug.zip](https://github.com/godotengine/godot/files/8443789/Bug.zip)

**Comment by Calinou** [comment]
cc @fire

**Comment by fire** [comment]
I'm wonder if it's a blender bug. @julienduroure

**Comment by julienduroure** [comment]
Is that a glTF file autogenerated by Godot during .blend import?
What are the option used during Blender export by Godot?

Is the "Keep original" option is checked?
In that case, I can confirm the bug.

**Comment by timshannon** [comment]
Looks like it: https://github.com/godotengine/godot/blob/master/modules/gltf/editor/editor_scene_importer_blend.cpp#L187

![image](https://user-images.githubusercontent.com/1330485/162272248-d2fb6f40-67f0-4d6a-ad10-62d3defefc21.png)

**Comment by timshannon** [comment]
@julienduroure  I'm not seeing an issue for this here: https://github.com/KhronosGroup/glTF-Blender-IO

Do you want me to open one?

**Comment by julienduroure** [comment]
Hello,

If you disable unpack images option in Godot, it can't work with your file, and this is not really a bug.
You are using packed images, but original paths to files are kept.
You are exporting glTF from Blender using "keep original textures", these filepaths are used. But files are not found if they are moved.

"Keep original" should not be used with packed files. This is probably why there is an unpack option, on by default. With this option, all textures are in godot project directory.

**Comment by timshannon** [comment]
I see.  Sounds like the keep original should be set, in sync with the unpack enabled option then, as opposed to hard-coded like it is now.

I appreciate the insight.

**Comment by julienduroure** [comment]
I open a ticket.
In that case, I think this is better to not export texture. It will be better than export an invalid glTF file

https://github.com/KhronosGroup/glTF-Blender-IO/issues/1618

**Comment by aaronfranke** [comment]
In Godot 4.3 stable and Blender 4.2, this is fixed. Note: The minimal reproduction project is still broken in Blender 4.1.
