### ISSUE TITLE
FBX import using FBXtoglTF not working

### ISSUE THREAD

**Issue by stryker313** [godotengine/godot#59996]
### Godot version

4.0 Alpha 6

### System information

Windows 10 Nvidia GTX 1060 Intel i5 4690k

### Issue description

FBX animations that I attempt to import do not import.
I have set the fbx2gltf path, and still nothing. The file will be in the editor, but it has a red x through it.
For reference, I put the fbx2gltf.exe that I used in the minimal repo project

```
modules/gltf/editor/editor_scene_importer_fbx.cpp:83 - FBX conversion to glTF failed with error: 105.
  editor/editor_file_system.cpp:1928 - Error importing 'res://smallMesh@Praying (1).fbx'.
```
This happens with animations of all FBX type, regardless of origin.

### Steps to reproduce

1. Set you fbx2gltf filepath to the FBX2glTF.exe
2. Move an fbx file into your project directory using your file manager (not dragging directly into the editor)
3. The fbx file will not import (fbx file has a red x through it)

### Minimal reproduction project

[FBXimportbug.zip](https://github.com/godotengine/godot/files/8446305/FBXimportbug.zip)

**Comment by akien-mga** [comment]
It's choking on the parentheses in the file name:
```
sh: -c: line 1: syntax error near unexpected token `('
sh: -c: line 1: `"/home/akien/Projects/godot/toolchains/FBX2glTF" "--pbr-metallic-roughness" "--input" ""/home/akien/tmp/godot/bug/FBXimportbug/smallMesh@Praying (1).fbx"" "--output" ""/home/akien/tmp/godot/bug/FBXimportbug/.godot/imported/smallMesh@Praying (1)-ffb1f0ad0b110cb34540e145f57fa585.glb"" "--binary" 2>&1'
```

Might be missing escaping / I might have removed the ones @fire put by mistake when reworking both FBX and Blender importers.

**Comment by stryker313** [comment]
I renamed the file to "anim" and it still doesn't import.

**Comment by akien-mga** [comment]
It imports OK for me when renamed to `anim.fbx`:
![image](https://user-images.githubusercontent.com/4701338/162305597-8413d542-d81e-4418-b1de-8395f40d02a5.png)

**Comment by stryker313** [comment]
![Desktop Screenshot 2022 04 07 - 17 03 56 81](https://user-images.githubusercontent.com/83078010/162307172-0443fe8d-d0f8-4965-97c2-1169f31a0184.png)

**Comment by stryker313** [comment]
Just to confirm, it IS the fbx2gltf.EXE from [V-Sekai fork] for windows 10 that I am suppose to be using? I don't really understand what the issue could be...

**Comment by akien-mga** [comment]
> Just to confirm, it IS the fbx2gltf.EXE from [V-Sekai fork] for windows 10 that I am suppose to be using? I don't really understand what the issue could be...

Yeah, I just tested with the latest version from https://github.com/V-Sekai/FBX2glTF/releases/tag/v0.12.9-p2 and it works fine for me on Linux.

It's worth noting that the V-Sekai readme mentions that on Windows it requires MSVC redistributable, maybe that's missing on your end? https://github.com/V-Sekai/FBX2glTF#platform-binaries

Can you try to run FBX2glTF.exe manually from the command line? With e.g. this command:
```
FBX2glTF.exe --pbr-metallic-roughness --input anim.fbx --output anim.glb --binary
```

**Comment by fire** [comment]
I can reproduce the bug. I don't know why yet.

**Comment by fire** [comment]
`g .fbx` fails to import.

**Comment by stryker313** [comment]
[anim.zip](https://github.com/godotengine/godot/files/8446578/anim.zip)
result

**Comment by stryker313** [comment]
```
Warning: node /RootNode/Eyes_Source_Cylinder.001 uses unsupported transform inheritance type 'eInheritRrSs'.
         (Further warnings of this type squelched.)
Animation mixamo.com: [0 - 206]
Wrote 7407405 bytes of binary glTF to anim.glb.
```

**Comment by fire** [comment]
Expected "broken" result.

![image](https://user-images.githubusercontent.com/32321/162318174-d0727942-ba82-4370-a234-6c73b1c0f74e.png)

**Comment by fire** [comment]
https://github.com/godotengine/godot/issues/57895 can be resolved by disabling lods.

![image](https://user-images.githubusercontent.com/32321/162319440-4eb61bf1-e922-4aba-af9c-6191f950890b.png)

**Comment by stryker313** [comment]
Will report back on the MSVC in a bit.

**Comment by akien-mga** [comment]
> Will report back on the MSVC in a bit.

Your test above shows that running `FBX2glTF.exe` worked and generated a `.glb`. So it seems to work fine, you seem to have the required components.

It's weird if it still doesn't work in the Godot editor though, as it runs the same command.

**Comment by fire** [comment]
Looks good https://github.com/akien-mga/godot/commit/d4b54e35f962373c23a9034f4f96f8fb02cb45db if it works on the test case with fbx2gltf on Windows.

**Comment by akien-mga** [comment]
@stryker313 Once the Windows CI builds finished for #59998, you should be able to find a Windows editor binary to download here: https://github.com/godotengine/godot/actions/runs/2111701311

Could you try it and confirm if it fixes the FBX import issue with a name that contains `(`? It might be that this bug was actually Unix specific though, and if so the bug you're experiencing even with `anim.fbx` might be different.

**Comment by stryker313** [comment]
@akien-mga yeah it works now 🍡 
![Desktop Screenshot 2022 04 07 - 17 55 56 26](https://user-images.githubusercontent.com/83078010/162326465-f2d576d9-1bdc-4a75-8ca1-4ffed8174c20.png)

**Comment by akien-mga** [comment]
Great, so the double quoting was also a problem on Windows (would end up as `"FBX2glTF.exe" "--input" ""anim.fbx"" ...` which likely doesn't work on Windows.
