### ISSUE TITLE
.blend import on armatures does not account for rest position

### ISSUE THREAD

**Issue by stryker313** [godotengine/godot#59999]
### Godot version

4.0 Alpha 6

### System information

Windows 10 Nvidia GTX 1060 Intel i5 4690k

### Issue description

If you import an fbx file into a .blend file, save it, then import it into Godot, the animation works fine.
However, the armature/skeleton does not retain the rest position, despite the .blend file still having the original rest position.
![Desktop Screenshot 2022 04 07 - 17 36 54 53](https://user-images.githubusercontent.com/83078010/162325031-d94efbef-2851-41a0-82f0-05d11c2e68e8.png)
![Desktop Screenshot 2022 04 07 - 17 38 43 85](https://user-images.githubusercontent.com/83078010/162324998-00e98d7a-03c3-4e96-838e-d5ec688c7a9b.png)

The only way to preserve the rest is to  have the .blend saved with the rest pose set, however, this then removes the animation

### Steps to reproduce

1. Import any animation into blender (fbx file)
2. Set the pose of the armature to pose position
3. Save the .blend file
4. Import the .blend file into Godot
5. Open the file in godot
6. Click show rest pose only on the skeleton.
Voila.

### Minimal reproduction project

[MissingRestPose.zip](https://github.com/godotengine/godot/files/8447027/MissingRestPose.zip)

**Comment by fire** [comment]
FBX to gltf exports use the first frame of the first animation. We worked around it using a `RESET` animation track in Godot.

There may still be a bug in fbx2gltf https://github.com/V-Sekai/FBX2glTF/issues/1 related to the first frame of gltf.

**Comment by fire** [comment]
Blend files once converted from the native format uses the gltf exporter. @julienduroure Did I get this description correct?

**Comment by julienduroure** [comment]
I just proposed this PR in glTF-Blender-IO to manage REST pose as default TRS pose for joints node:
https://github.com/KhronosGroup/glTF-Blender-IO/pull/1621

**Comment by fire** [comment]
Merged into Blender 3.2. Closing.
