### ISSUE TITLE
Some shortcuts in editor stop working

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#60005]
### Godot version

748fde8

### System information

Windows 10 x64

### Issue description

I wanted to use Command Palette, but noticed that I can't use shortcut. Then I discovered that some shortcuts just stop working randomly, like undo or redo (sometimes one of them and sometimes both). The base issue is easy to reproduce, but I don't know what determines which shortcuts work and which not.

### Steps to reproduce

1. Right after starting the editor
2. Press Ctrl + Shift + P to open Command Palette
3. Close it
4. Try using shortcut again

**Comment by jayypluss** [comment]
May be related to #54274 and #28511

**Comment by KoBeWi** [comment]
No, this is easy to reproduce. Just use the Command Palette shortcut twice (Ctrl + Shfit + P). The "difficult" part is determining which shortucts are affected, because not all get disabled (actually I don't remember other shortcut with this problem, so maybe it's command palette problem 🤔).

The PR you linked does not fix it.

**Comment by bruvzg** [comment]
In case of `Command Palette` it's a conflicting shortcut (<kbd>Ctrl/Cmd</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd> for both):
https://github.com/godotengine/godot/blob/104af08e9d7c8308c2dd6cad89a0caee774043a0/editor/editor_node.cpp#L6820
https://github.com/godotengine/godot/blob/104af08e9d7c8308c2dd6cad89a0caee774043a0/editor/plugins/canvas_item_editor_plugin.cpp#L5319
