### ISSUE TITLE
Brace matching does not work

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#60001]
### Godot version

ae2d53c

### System information

Windows 10 x64

### Issue description

Godot 3
![image](https://user-images.githubusercontent.com/2223172/162332519-51fc2116-e297-4f79-97e9-f76e3ca70250.png)
Godot 4
![image](https://user-images.githubusercontent.com/2223172/162332559-0b089493-7d29-4052-8a43-c79dc32af2fd.png)
Previously the matching braces would be underlined when caret is next to them. This doesn't seem to work in 4.0.

### Steps to reproduce

1. Add any text with `()` to script editor
2. Place caret next to a brace
3. No underline, nothing

**Comment by Jason-Patrick** [comment]
I would like to take a crack at this for my first open source issue.

**Comment by adamscott** [comment]
> I would like to take a crack at this for my first open source issue.

Feel free to submit a PR.

**Comment by Jason-Patrick** [comment]
After tracing/debugging I can confirm that the matching logic is still in working order; the matching braces are detected. I can also confirm that the logic to generate the rects are still being called without error, and that they are also passed down to `draw_rect()` on line 1235 in text_edit.cpp. From there I can follow the stack trace through `draw_rect()` to `canvas_item_add_rect()` to the match function for `Item::Command::TYPE_RECT`. At the end of that function are the calls to RenderingDeviceVulkan, and it's there where my understanding of the code isn't really clear. If someone else would like to take a look, or can point me in a possible spot to look, please feel free. I would hate to hold this up, if someone can at this point do it faster, but I hope this has at least saved some debugging time for someone else.

**Comment by KoBeWi** [comment]
Ok this is weird
![image](https://user-images.githubusercontent.com/2223172/175525820-c33835cd-86f4-4d06-827e-b6ddf159ebe4.png)
As you can see, brace matching works. But not always. It works for me on one machine, but on another it doesn't. I wonder if it's some editor setting that disables it or it depends on... idk what xd

**Comment by KoBeWi** [comment]
Ok found it. It doesn't appear on 100% display scale, but it works on 125%.
