### ISSUE TITLE
Fails to create a new folder in the FileSystem panel.

### ISSUE THREAD

**Issue by hidemat** [godotengine/godot#60006]
### Godot version

4.0 alpha 6

### System information

Windows 10 NVIDIA GeForce GTX 1050

### Issue description

When I try to create a new folder in FileSystem I get an error saying the folder already exists, but it doesn't.
![image](https://user-images.githubusercontent.com/6559151/162338937-3e91677e-9aa9-47c4-b1d8-79de03a9e99e.png)
![image](https://user-images.githubusercontent.com/6559151/162338966-14dadb40-275e-4628-b139-aea625b6f7f2.png)

### Steps to reproduce

Try to create a new folder in the FileSystem panel

**Comment by KoBeWi** [comment]
Thanks for reporting this issue. It's the same as https://github.com/godotengine/godot/issues/59956 which has already been fixed, will be solved in the next build.

**Comment by hidemat** [comment]
Oh woops. Sorry I tried searching for it but I couldn't find it. I think because I was searching only for open issues.
