### ISSUE TITLE
Build error on FreeBSD due to ThorVG (`alloca.h`)

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#60003]
### Godot version

4.0.alpha (ae2d53cd)

### System information

FreeBSD 13.0 on Cirrus CI

### Issue description

I get a build error on FreeBSD 13.0:

```
Compiling thirdparty/thorvg/src/loaders/svg/tvgXmlParser.cpp ...
thirdparty/thorvg/src/loaders/svg/tvgXmlParser.cpp:30:14: fatal error: 'alloca.h' file not found
    #include <alloca.h>
             ^~~~~~~~~~
1 error generated.
scons: *** [thirdparty/thorvg/src/loaders/svg/tvgXmlParser.linuxbsd.opt.tools.64.o] Error 1
```

Full log: https://cirrus-ci.com/task/5485473287110656
CI setup files: https://github.com/Calinou/godot-ci-freebsd

There's another instance of an `alloca.h`-related build failure on FreeBSD, which occurred a long time ago: https://github.com/godotengine/godot/issues/6238

This issue doesn't affect `3.x` as ThorVG is only used on `master`.

### Steps to reproduce

- Build Godot's `master` branch on FreeBSD. You can use Cirrus CI if you don't want to set up a VM locally.

### Minimal reproduction project

N/A

**Comment by fire** [comment]
Seems the fix is https://github.com/godotengine/godot/pull/17135/files:

```
#ifdef __linux__
#include <alloca.h>
#include <alloca.h>
#endif
#if defined(__FreeBSD__) || defined(__OpenBSD__)
#include <stdlib.h>
#define PTHREAD_BSD_SET_NAME
#endif
```
