### ISSUE TITLE
Find a witty joke to make for the 6000th issue

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#6000]
We're about to reach the issue number #6000, so it would be nice to brainstorm about a witty joke we could make at this occasion, like we did for #3000.

All the OCD'ed watchers of this repo would likely be very grateful to see a funny non-issue opened just for the sake of it - thus preventing it from being taken by an actually meaningful issue we would have to put some work on. 

Any ideas? :grin:

**Comment by JulienGio** [comment]
![wfgori](https://cloud.githubusercontent.com/assets/20727749/17301903/c429c138-5819-11e6-8299-532e75fcee34.jpg)

> Original: http://bizarro.com/wp-content/uploads/sites/172/2014/02/bz-panel-02-20-14.jpg

**Comment by bojidar-bg** [comment]
@akien-mga Unfortunately it throws an error:
> Error, self referential item `godotengine/godot/issue/6000`, can't complete DirectedAcyclicGraph<GithubIssue>* (instanced as Tree<MarkupPage>*)

**Comment by TheoXD** [comment]
let's create 2999 fake issues and jump right to 9000th already? xD

**Comment by akien-mga** [comment]
> let's create 2999 fake issues and jump right to 9000th already? xD

Challenge accepted!

**Comment by spookdogg** [comment]
> let's create 2999 fake issues and jump right to 9000th already? xD

this but 3000 instead so it's the funny joke number :^)

**Comment by akien-mga** [comment]
OP should really stop opening pointless issues like that and wasting everyone's time...
