### ISSUE TITLE
cannot move object on blue axis

### ISSUE THREAD

**Issue by Marqin** [godotengine/godot#6001]
**Operating system or device - Godot version:**
OS X, Steam version and current github HEAD too. Not tested other OSes/versions.

**Issue description** (what happened, and what was expected):
I cannot drag objects on blue axis.

**Steps to reproduce:**
Create empy project and add test cube or open one of demos.

Probably it's a "feature" that prevents you from moving object on axis which you are near (angle-wise) with your camera, which imho should be changed.

![screen](http://i.imgur.com/onI1OX6.png)

**Comment by Marqin** [comment]
After I move my camera a little for first time, blue axis gets unblocked. But it's blocked before that. Clearly a bug.

**Comment by raould** [comment]
For whatever it is worth, I have it, too. Linux Ubuntu 16.04.1 x86_64 running MATE desktop. Godot version "Godot_v2.1-stable_x11.64"

**Comment by DualMatrix** [comment]
Could not reproduce in master.

**Comment by akien-mga** [comment]
Thanks, assuming fixed.
