### ISSUE TITLE
Cannot type @, £, $ etc because Opt(Alt) + 1, 2, 3... are taken by changing editor 

### ISSUE THREAD

**Issue by KuuttiProductions** [godotengine/godot#60013]
### Godot version

4.0.alpha4

### System information

MacOS 12.3.1, Vulkan, M1 Pro

### Issue description

Cannot type letters like @ because they would be typed with Option + number but those are taken by shortcuts switching between 2D, 3D and script editors. You can ofcourse change the shortcuts but it still doesn't let me type the letters I want. 

### Steps to reproduce

On a Mac try to type @ in script editor. It will switch to 3D editor

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/54303. Can you try building the latest `master` branch and see if this issue persists?

**Comment by KuuttiProductions** [comment]
Alright seems like #54303 is the same. Closing it now
