### ISSUE TITLE
Enable Export PCK/ZIP without templates

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#6002]
Currently the "Export PCK/Zip" is only enabled if a target platform is selected and the templates are installed. Since this is platform-independent, it should be always enabled.

**Comment by vnen** [comment]
Well, this is solved for 3.0. Should 2.1 have this functionality too?

**Comment by eon-s** [comment]
@vnen yes, please :D

**Comment by Zireael07** [comment]
@vnen: Yes please.

**Comment by Listwon** [comment]
@vnen Any clues where to start to port this functionality to 2.1?

**Comment by vnen** [comment]
Fixed by #12040.
