### ISSUE TITLE
Animation adding/pasting results in wrong animation of AnimationTree

### ISSUE THREAD

**Issue by Dadaskis** [godotengine/godot#60038]
### Godot version

3.4.4.stable

### System information

Windows 7 x64, GLES3, Nvidia Geforce GT1030

### Issue description

Hi! That's the first issue i post at Github :)

I'm trying to make life of animator easier by combining walking and weapon animations from different models. We don't want to make a big animation tree which has all the weapon animations we will use. Instead we want to replace such animations. Sadly our attempt to do that went a bit wrong.

So we are sure that
1. Skeletons are exact same
2. Even the models can be exact same, but have different animations

What's wrong? It's easier to show that. This is what we got...
![WRONG](https://user-images.githubusercontent.com/37717199/162511324-8669b98a-e924-4b44-babf-eceaa7e7c3ee.PNG)

And this is what we want to get:
![RIGHT](https://user-images.githubusercontent.com/37717199/162511360-9206b70c-3165-4a70-aeff-d6bbb870662a.PNG)

As you see, positioning of arms is completely different. This is exact same models, but one of them has different animation which will be added to the another one.

And this issue is possible to reproduce not only using any code. You can just copy-paste it by hand and it will result like that.

This problem was reproduced at MacOS and Windows 10, by other teammates, so it's not really connected to specific build of Godot.

It was tested at v3.4.2. and there was the same problem

### Steps to reproduce

1. Open the project
2. Open "res://reproducing.tscn" scene
3. Run this scene

There is actually one more way to do that, without code.
1. Open the project
2. Open "res://assets/pistol_anim/pistol_0_test_anim.glb" model (choose "Open Anyway")
3. Pick "AnimationPlayer" node
4. In animations window pick the "weapon_idle" animation
5. Copy it
6. Open "res://assets/base/human_anims.glb" model (choose "Open Anyway")
7. Pick "AnimationPlayer" node
8. Paste animation

As result it pastes the animation wrong.

### Minimal reproduction project

[Animation Combine Problem.zip](https://github.com/godotengine/godot/files/8454911/Animation.Combine.Problem.zip)

**Comment by Calinou** [comment]
@Dadaskis The minimal reproduction project didn't upload (likely because you clicked away from the text field while it was still uploading). Try editing your post and upload it again.

**Comment by Dadaskis** [comment]
Updated the reproduction project

**Comment by TokageItLab** [comment]
Is bone rest the same? 3.x uses rest relative values for animations. So the model rest may differ depending on the order of the animations in the model being imported.

**Comment by Dadaskis** [comment]
@TokageItLab i don't really know how to check that. How to do that?

And just in case also asking a question, how to make it valid if it's not the same?

**Comment by TokageItLab** [comment]
@Dadaskis For 3.x, there is a Bone Rest Matrix field in the Skeleton inspector near the Bone Pose Matrix. Or, you can make all Bone Poses `Transform(Quaternion(0,0,0,1),Vector3(0,0,0))` and see if there is any difference.

It is possible to copy and paste all Bone Rest Matrixes, but if it is tedious, make sure that the model you are importing has an animation with no animation (e.g. T-pose) imported first.

**Comment by Dadaskis** [comment]
![image](https://user-images.githubusercontent.com/37717199/180621767-5fade863-5597-477d-91cc-6d17498392f3.png)

After some time i decided to return to this problem. Why? Blender GLTF export takes TOO MUCH time to export all animations. So keeping it as one file only is not an option.

@TokageItLab thank you a lot for your help. 

As you all see on the image, this character has T-pose. It doesn't really matter which pose it has, you must follow these steps:
1. Make sure ALL modifiers have no effect on bone positions. Just disable inverse kinematics and other stuff.
2. Make sure all of your files exported with the same current action, like i show in the image (all of the files have "_init_pose")

Again, @TokageItLab, thank you. All of the stuff i reported is not a bug. Still, i would like to ask for some sort of warning if rest poses are not the same, probably this can help people.

Also, just a bit of offtopic stuff which is yet connected to this problem. If you work with such stuff, i highly suggest you to make Blender plugin to export character with "_init_pose" action selected automatically

Closing since this is not a bug.
