### ISSUE TITLE
CharacterBody3D's up_direction property is unsettable.

### ISSUE THREAD

**Issue by Verifitas** [godotengine/godot#60033]
### Godot version

v4.0.alpha6.official.e4f0fc50f

### System information

N/A

### Issue description

The property `up_direction` cannot be set in CharacterBody3D instances.  `up_direction` is locked to the default value of `Vector3(0, 1, 0)`.

### Steps to reproduce

Instantiate a CharacterBody3D with the following GDScript.

```
extends CharacterBody3D

func _ready():
	# Cannot set with direct access.
	up_direction = Vector3.ZERO
	assert(up_direction == Vector3.ZERO, "up_direction should match what it was just set to")
	
	# Same with the setter/getter.
	set_up_direction(Vector3.ZERO)  
	assert(get_up_direction() == Vector3.ZERO, "up_direction should match what it was just set to")
```

**Comment by Calinou** [comment]
cc @fabriceci

**Comment by Verifitas** [comment]
I've just noticed that it's exclusively Vector3.ZERO that it does not accept.   In fact, there's an entire error I missed.

`E 0:00:00:0707   _ready: up_direction can't be equal to Vector3.ZERO, consider using Floating motion mode instead.`

Should this be the case?  Maybe it's the documentation that's not caught up yet.  The documentation for CharacterBody3D in this snapshot says `If set to Vector3(0, 0, 0), everything is considered a wall. This is useful for topdown games.`

**Comment by fabriceci** [comment]
Good finding, the documentation does not seem to be up to date, I will update it!

**Comment by marstaik** [comment]
Errr, the `up_direction` is a normal, and normals can't be zero or a lot of math breaks down. I went and took a quick glance at CharcaterBody3D and it is used a lot for floor siding and other calculations which would break down with zero.

So it's definitely the docs that need to be updated

**Comment by Verifitas** [comment]
Ah.  Makes sense.  Given the documentation, I'd just assumed it was an analog/rename of the old snap vector which _could_ be zero.  My bad.
