### ISSUE TITLE
Editor subwindows should use a subtle border to be distinguishable from the background when the window manager doesn't display drop shadows

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#60047]
### Godot version

4.0.alpha (bf153b82c)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 510.60.02)

### Issue description

If you disable drop shadows for windows in your window manager settings, subwindows will appear to "blend in" with the editor main window depending on the background color. This can be confusing.

This is only an issue since DisplayServer was used for multiple window support. This is not an issue when using single-window mode or in `3.x`.

![image](https://user-images.githubusercontent.com/180032/162548145-822c6cf1-0e59-40db-92a2-2cb0eef2839a.png)

### Steps to reproduce

- Disable compositing on your window manager (<kbd>Alt + Shift + F12</kbd> on KDE/KWin).
- Open a class reference page, then close it.
- Open the Project Settings.
- Notice how the window "blends in" with the background.

### Minimal reproduction project

N/A

**Comment by YeldhamDev** [comment]
`PopupMenu`s suffer a lot from this problem too. Whatever single-window mode is enabled or not:
![image](https://user-images.githubusercontent.com/30739239/182481162-6a9a58d4-e488-48ff-af00-441c30a3f34e.png)

**Comment by KoBeWi** [comment]
Seems fixed
![image](https://user-images.githubusercontent.com/2223172/212981542-a9d75b06-a519-4e7e-b742-b9731da49ad0.png)
