### ISSUE TITLE
Input Mapping : changing Device ID does not save (keeps reverting to Device 0)

### ISSUE THREAD

**Issue by mohammedzero43** [godotengine/godot#60065]
### Godot version

4.0 alpha 6

### System information

Win11 , Nvidia MX 450

### Issue description

I try to change the Joystick Device ID in Input Mapper, however it always goes back to Device 0
![bug screenshot](https://gcdnb.pbrd.co/images/2teHZqI9VBog.png?o=1)

### Steps to reproduce

1- Create Joystick button/axis mapping , and assign it to device 1 ~ 7 
2- re-open the dialogue (or the project file as text) to see that all inputs are still (Device 0)

**Comment by jmb462** [comment]
Shouldn't have been fixed by https://github.com/godotengine/godot/pull/59514 ?

**Comment by SirQuartz** [comment]
> Shouldn't have been fixed by #59514 ?

Possibly, it just hasn't been merged yet.
