### ISSUE TITLE
Error instancing scene as editor tool: Condition ' signal_map.has(p_signal.name) ' is true

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#6006]
Tested on Godot 2.1 rc1 Windows 10 64 bits

I get this error when I launch this test project:
[PluginInstanceSignalError.zip](https://github.com/godotengine/godot/files/395117/PluginInstanceSignalError.zip)
This project contains a plugin that instances a custom control scene. This scene contains a HButtonArray. If I remove it, i don't get the error.

It's possibly related to https://github.com/godotengine/godot/issues/6005.

**Comment by akien-mga** [comment]
Is this still valid in the current master branch?

**Comment by Zylann** [comment]
For 3.0 or 2.1.4?

**Comment by akien-mga** [comment]
I meant master, so 3.0. But it would be interested to know for 2.1.3/the 2.1 branch too :)

**Comment by akien-mga** [comment]
Can't reproduce in 2.1.4, and `HButtonArray` doesn't exist anymore in the master branch.
