### ISSUE TITLE
Crash when clicking a resource property in the inspector while no scene is open

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#60077]
### Godot version

4.0 83d26737727f281afcb33f66fea5d09ed6c48d5a

### System information

Windows 10 64 bits GLES3 GeForce GTX 1060 6GB/PCIe/SSE2

### Issue description

I have a resource containing another. If I open it in the inspector and click the property, Godot crashes.

![image](https://user-images.githubusercontent.com/1311555/162587416-03283e16-6410-47f2-b105-8fe8932a23fa.png)

`EditorPropertyResource::_resource_selected` assumes there is an open scene, causing an access violation.

### Steps to reproduce

1) Close all scenes
2) Create a GradientTexture
3) Assign `gradient` to a new Gradient in place
4) Save the GradientTexture as a .tres file
5) Double-click the .tres file in the file system to open it in the inspector
6) Click the `gradient` property: observe a crash

### Minimal reproduction project

[InspectorEditSubResourceCrash.zip](https://github.com/godotengine/godot/files/8457567/InspectorEditSubResourceCrash.zip)

**Comment by timothyqiu** [comment]
From #59496, CC @KoBeWi

Maybe it should skip when the resource is a builtin subresource.
