### ISSUE TITLE
Changing default gltf import settings fills project.godot with animation clip data

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot#60072]
### Godot version

3.4.4.stable.arch_linux

### System information

Linux 5.16.16-arch1-1

### Issue description

Changing the defaults for a scene import creates a large diff in the project.godot file, including a bunch of lines like:

```
+[importer_defaults]
+
+scene={
+"animation/clip_1/end_frame": 0,
+"animation/clip_1/loops": false,
+"animation/clip_1/name": "",
+"animation/clip_1/start_frame": 0,
+"animation/clip_10/end_frame": 0,
+"animation/clip_10/loops": false,
+"animation/clip_10/name": "",
+"animation/clip_10/start_frame": 0,
+"animation/clip_100/end_frame": 0,
+"animation/clip_100/loops": false,
+"animation/clip_100/name": "",
+"animation/clip_100/start_frame": 0,
+"animation/clip_101/end_frame": 0,
+"animation/clip_101/loops": false,
+"animation/clip_101/name": "",
+"animation/clip_101/start_frame": 0,
... many more ...
```

Would it be possible to only record non-default settings, or at least not record clip settings for clips > `animation/clips/amount`?

Relates to #20994, but this is not a file that can be gitignored.

### Steps to reproduce

1. Open a new project in a git repository with a clean index
2. Add a gltf file
3. On the import settings, change `materials/storage` to "built in"
4. Click "Preset" and "Set as Default for Scene"
5. Check `git status`, see a large diff in `project.godot`

**Comment by aaronfranke** [comment]
This issue is a different symptom, but the same cause as #48189.

This does not occur in Godot 4.0 and later, only 3.x. As for fixing this in 3.x, it's a minor issue, and it's better to not change the behavior in 3.x which is supposed to be stable. Closing as fixed.
