### ISSUE TITLE
List of weird things with Godot UI

### ISSUE THREAD

**Issue by jeancallisti** [godotengine/godot#60074]
### Godot version

3.4.2 stable

### System information

Windows 10

### Issue description

**This is an exhaustive list of counter-intuitive things with Godot UI. It will grow with time.**
The kind of things that confuse the newcomer and make them hate Godot before they even get to like it.
The kind of things that smell like "Blender UI" before they fixed it (if you remember the old days)

Fix it or not, I don't care, but don't say that no one warned you : 

**1) Position of "Asset library" button.**

the asset library button is next to the "View" buttons (2D, 3D, Script).
Conceptually, those other buttons are meant to let the user choose under which "perspective" they want to see the asset (most often, the scene) currently open: Do they want to see it as a 2D thingy? A 3D thingy? A text? etc.
And then there's the Asset Lib button, which has nothing to do with any of that. the Asset library button is meant (conceptually) to be used on a global level and applies to the whole project.
So why is it hidden there? Why is it not with the project settings? Or above the FileSystem panel? Or in the top menu? Etc. Mystery.

**2) How the asset library opens**

The asset library appears in a tab, but... Not in its own tab.
It steals the tab of whatever asset was currently open.
Worse, it does not rename the tab. It still seems like *my* asset is open but the tab wears its name, except it now displays a list of assets to download instead. 
Now I can't close the asset library without closing my own asset. I have to do the awkward thing of remembering how I was currently displaying my asset (2D? 3D? script?) and click on the corresponding button to bring it back how it was.
Shoo! Get your own tab, asset library!

**3) When a new scene is created, it's not really created**

So I go to the FileSystem panel and right-click on a folder, then "new scene". A popup appears to let me enter the name. I click OK.
Aaaand... the scene has not been created?
I mean : Nothing changed on the screen. Nothing appeared in the folder (!). And no new tab appeared.

Upon closer inspection, the tab that was currently open is now titled "empty". What the hell does that mean.

As you've understood by now, I'm acting naive, but no one (and I mean, no one) could guess that you're now supposed to create a root node before you can even save the scene and see it appear in its folder. For any normal human being, if you click "OK" then the scene is supposed to have been somehow created. 
At least, make the new scene appear in its own tab instead of stealing the tab currently open (it looks extra awkward if you were currently displaying the Assets library!)

**4) How do I close a project?**

In every app in the world, in the top menu, the **leftmost** menu is for the app itself -- or at least the main, biggest entity (usually, the project). _Then_ you have other menus, more to the right, for other smaller things.

Not in Godot : The scene is leftmost and the project comes second.
So when you want to close the project, it becomes awkward. If you're a beginner then you need to remember that the "Scene" is not the boss here. It's not your project. The project is your project. And even when you click on that menu, there's no "Close" entry. It's awkwardly named "Exit".

**5) Rename : Never the same number of clicks**
 
- In the scene hierarchy, **double-click** to rename
- In a SpriteFrames resource (bottom panel), **single click** on an animation in the list of animations
- In the FileSystemPanel, clicking **doesn't** rename. You need to right-click-->Rename

**6) Clicking outside of a dropdown menu actually does click**

- Go to the inspector
- Expand any property that has a dropdown.
- Click outside of it, for example just on the right of it to exit (that is, collapse) it again
- Oh noes! It turns out that the area just to the right of it was the "delete" button. By collapsing your resource you deleted it.
- that's because in most UIs, clicking outside of a dropdown makes it **lose focus,** (but doesn't actually do the click wherever you clicked). In godot it does!
- 

**7) No shortcut to open the help page of a native function (?)**
- Open a .gd script
- Highlight any native function name (e.g. highlight word "printerr")
- You can't press F1 or whatever shortcut to display the help page
- You have to press F1 and then type again printerr to find the help page (if it exists! Can't know for sure until you've done that)

**8) No shortcut to teleport to function definition**
- Create a new .gd script
- Create local function. for example _func _myFunction():_
- Somewhere else in the same file, write a line of instruction that calls function _myFunction
- highlight it
- No shortcut to go to _myFunction 's definition (for comparison: you'd press F12 in Visual Studio). If you don't know where that function is located then you have to do Shift+Ctrl+F to do a full search on it every time.

**Comment by Calinou** [comment]
It's probably better to use the [Discussions tab of the godot-proposals repository](https://github.com/godotengine/godot-proposals/discussions) for things like this, since this issue tracker is now dedicated for bug reports only.

**Comment by KoBeWi** [comment]
> When a new scene is created, it's not really created

This is already tracked in #34524

> So when you want to close the project, it becomes awkward.

Is there anyone who uses Close option instead of the window's X button or Alt+F4?

**Comment by jeancallisti** [comment]
> It's probably better to use the [Discussions tab of the godot-proposals repository](https://github.com/godotengine/godot-proposals/discussions) for things like this

I will move it there when I'm done wit this initial splurt of reporting. For now it just keeps growing as I see it.

**Comment by Calinou** [comment]
I'd also consider taking a look at https://github.com/godotengine/godot-proposals/issues/645 and giving your feedback on that proposal.

**Comment by ssokolow** [comment]
I have a big bunch of additions to the list that center around the non-orthogonality of Godot's two actual tab bars and one *de facto* vertical tab bar combined with a gap in the conceptual model of the Scene and FileSystem panels.

Should I open something in the Discussions tab or wait for you to do it?
