### ISSUE TITLE
3D model [OBJ] import error

### ISSUE THREAD

**Issue by svprdga** [godotengine/godot#60071]
### Godot version

v4.0.alpha6.official [e4f0fc50f]

### System information

Linux Mint, Vulkan, GTX 1070

### Issue description

I have imported a 3D model in form of OBJ format and I can add it to the world, but the texture is not automatically added to it.

I have tried it with the current Godot 3 and works correctly.

### Steps to reproduce

1. Create a 3D world
2. Download OBJ version of: https://sketchfab.com/3d-models/skara-brae-orkney-house-2-e12c4389a6154bf5a72b74c34a1823b8
3. Try to add this mesh with its texture to the world

**Comment by akien-mga** [comment]
Seems fixed as of 4.0 RC 5:
![image](https://user-images.githubusercontent.com/4701338/221422425-fa89872a-5a5a-4d47-ad6c-905f646dc191.png)
