### ISSUE TITLE
Layout preset buttons not showing for Window / Popup nodes and their children Control nodes

### ISSUE THREAD

**Issue by AndersonDeMatos** [godotengine/godot#60088]
### Godot version

v4.0.alpha6.official [e4f0fc50f]

### System information

Linux Pop!_OS 21.10, Nvidia GT710, Nvida X Server Settings 470.75.01

### Issue description

When we create a Window or a Popup node and we select them in the scene tree in the editor, they don't get the rectangle highlight and red circles to used to resize the nodes. The same happens to any of their children that inherit Control (probably other types too), and the buttons with the presets for anchors and sizing don't appear either, making it almost impossible to layout the GUI inside Window or Popup nodes.  It is possible to layout the GUI via the Inspector tab changing the property `layout_mode` to Anchors (when possible), but that's not very convenient.
The theme for those nodes don't seem to be working properly either.

### Steps to reproduce

Add a Window or any Popup node to the scene tree;
Add a Control as a child and some other node that inherits control as its child
Try to layout the GUI.

### Minimal reproduction project

[popup_test.zip](https://github.com/godotengine/godot/files/8457963/popup_test.zip)

**Comment by KoBeWi** [comment]
This is basically #39387 and #20619
Window is a Viewport, so any child Control editing won't work. Looks like that issue is more important to fix now. Also some better support for editing Windows would be useful too.
