### ISSUE TITLE
Compilation failed, all UUID invalid, cannot load any ressources or scenes

### ISSUE THREAD

**Issue by Noiros** [godotengine/godot#60087]
### Godot version

4.0 alpha 6

### System information

Windows 11, GLES3, Rx 5700 XT, Ryzen 7 3600x

### Issue description

It look like all .import files are unlinked, deleting the .import files and letting godot recreate them didn't fix the problem.
The engine seems unable to edit the .tscn alltogether.
The problem happend right after I move the assets files around.

Unfortunately I cannot provide my project as it isn't open source.

Here are the relevant error logs:
[godot.log](https://github.com/godotengine/godot/files/8457902/godot.log)

### Steps to reproduce

The problem happend right after I move the assets files around. but idk how to reproduce that

**Comment by Calinou** [comment]
Can you reproduce this issue when moving files around in a brand new project? If not, there's probably nothing we can do to troubleshoot this.

**Comment by Noiros** [comment]
I don't really know how to reproduce the bug but I managed to isolate a scene and its resources from my game and impossible to launch the compiled game after the export, the same bug as for the whole game

[import bug minimal.zip](https://github.com/godotengine/godot/files/8458881/import.bug.minimal.zip)

**Comment by Noiros** [comment]
the problem persists even after deleting the .godot and .import

**Comment by Noiros** [comment]
The problem fixed itself after re-importing the project ~50 X 😅, I still have sometimes the same problem when I move assets but it fixes itself a week later ...
