### ISSUE TITLE
Bug in emulation TouchScreenButton 

### ISSUE THREAD

**Issue by alexolin** [godotengine/godot#6008]
Win 10 - 2.1 rc1

If use in project TouchscreenButton (in project setting - emulate_touchscreen=true) in editor (or in exporting for Windows Desktop)  - touchscreenButton allow press other hidden button (any type) under on TouchScreenButton
Project and gif added.

[hidebuttonpress.zip](https://github.com/godotengine/godot/files/396207/hidebuttonpress.zip)
![animation1](https://cloud.githubusercontent.com/assets/15943158/17322959/a7b9757c-58a8-11e6-9d2a-0886b710cbf8.gif)

**Comment by RandomShaper** [comment]
Does this keep happening?

**Comment by volzhs** [comment]
I can confirm that 2.1.2-stable has this bug.
And 2.2 custom build does not have this bug.

**Comment by bojidar-bg** [comment]
@volzhs What about 2.1/HEAD (.3)?

**Comment by volzhs** [comment]
I need to build one.

**Comment by volzhs** [comment]
@RandomShaper @bojidar-bg 
I built 2.1.3 with 2.1/HEAD (33a2c5def0f55ef67196e35ac3309d3f9b70d967) and tested with it.
I confirmed that it works fine with 2.1.3.

**Comment by bojidar-bg** [comment]
Ok closing as fixed and soon-to-be-released then :smiley:
