### ISSUE TITLE
Project freezes after hittinng play button

### ISSUE THREAD

**Issue by amap1380** [godotengine/godot#60099]
### Godot version

Godot Engine v3.4.4.stable.mono.official.419e713a2

### System information

Ubuntu 20.04 LTS

### Issue description

After playing any project the fps drops to one and process time reaches 1000ms.
![image](https://user-images.githubusercontent.com/58068218/162619292-25a74a6e-88e8-478a-b300-938968ae514c.png)

### Steps to reproduce

Create a project.
Make a main scene.

**Comment by Calinou** [comment]
@amap1380 Did you manage to find a solution to this issue? If so, please document it here by commenting :slightly_smiling_face:

**Comment by amap1380** [comment]
> @amap1380 Did you manage to find a solution to this issue? If so, please document it here by commenting slightly_smiling_face

I turned off Vsync in the project setting.
Whenever I turned it on again it happens again.

**Comment by amap1380** [comment]
I just realized whenever I focus on the editor itself it happens.

**Comment by amap1380** [comment]
I just realized it happens when I focus on the editor itself.
