### ISSUE TITLE
Can't do basic editor things

### ISSUE THREAD

**Issue by jujumumu** [godotengine/godot#60092]
### Godot version

4.0 alpha 5

### System information

MacOS Version 11.6.2

### Issue description

When I try to interact with the editor many expandables are broken. I can't open project settings, editor settings, delete nodes set meshes in MeshInstance3D and much more. The following video demonstrates some of those issues.

https://user-images.githubusercontent.com/52044956/162600343-e50480f2-bd3c-4dcf-aa07-d3525c7d7c0c.mov

### Steps to reproduce

Create new project and try to open the project settings

**Comment by ZheisterCoding** [comment]
Hi, this will be my first open source contribution for GoDot! Can I try attempting on this issue? @Chaosus

**Comment by Chaosus** [comment]
Of course, you are welcome to do it @ZheisterCoding.

**Comment by ZheisterCoding** [comment]
Thanks!

**Comment by KoBeWi** [comment]
Did you try alpha 6?

**Comment by jujumumu** [comment]
I just downloaded and tried with Godot 4 alpha 6 and I can do all the things I couldn't in the video.
