### ISSUE TITLE
Bugs when assigning textures to default-named sprites

### ISSUE THREAD

**Issue by Rubicandt** [godotengine/godot#601]
System: Ubuntu 14.04 LTS

Occurence: Pong tutorial
Process:
1. Add node "Node2d"
2.  Add Node2d's child node "Sprite".  Leave name unaltered
3.  Set Sprite's texture: left_pallet.png
-- error 1: displays as nearly-flat horizontal line in editor.  Does not render as such in the test run.
4.  Add Node2d's child node Sprite "Sprite 2"
5.  Set Sprite 2's texture: right_pallet.png
-- error 2: any prior size edits to "Sprite" will be inherited in the editor.  Does not render as such in the test run.
-- error 3: size edits to the above for proper viewing will warp their representations in the test view.

bug-free process:
1.  Create Node2 node.
2.  Add all child sprite nodes.
3.  Rename sprite nodes accordingly.
4.  Set textures for each respective node.

**Comment by akien-mga** [comment]
Thanks for the detailed procedure. I tested it on  bd736e5 and could not reproduce any of the above issues, so they have likely been fixed.
