### ISSUE TITLE
Error with shader script that uses "INSTANCE_ID" and "async_hidden"

### ISSUE THREAD

**Issue by RockyMadio** [godotengine/godot#60105]
### Godot version

Godot_v3.5-beta3_win64

### System information

Windows 10

### Issue description

Error: !get_uniform: Condition "!version" is true. Returned: -1

This occures when a shader that uses **INSTANCE_ID** has _async_hidden_ to its render_mode header. 
One instance of this could cause the error to appear 30+ in the debug console.

### Steps to reproduce

1. Create a shader script
2. Append "async_hidden" to render_mode
3. Make use of INSTANCE_ID anywhere.
4. Launch the scene

**Comment by Calinou** [comment]
cc @RandomShaper

**Comment by RandomShaper** [comment]
For the records, `INSTANCE_ID` doesn't seem to be a key ingredient.

**Comment by RockyMadio** [comment]
I seem. I was testing with just a few shaders that randomize detail atlas based on their copy ID.

"Asyn_hidden" might cause issue in every shader script, I think.

**Comment by akien-mga** [comment]
Fixed by #60183.
