### ISSUE TITLE
Very long text in LineEdit causes Godot not responding

### ISSUE THREAD

**Issue by miv391** [godotengine/godot#60107]
### Godot version

v4.0.alpha6.official [e4f0fc50f]

### System information

Windows 10

### Issue description

Godot UI stops responding when you select a very long text pasted to LineEdit. It is, of course, not a good idea to paste this much text, but if you do it by accident, you cannot easily delete the text you pasted.

I would suggest that every LineEdit in Godot UI should have a reasonable Max Length set.

### Steps to reproduce

1. Paste 1 million characters long text to "Select a setting or type its name" text field in the Project Settings dialog.
2. Press Ctrl-A (to select all text).

**Comment by miv391** [comment]
I might even suggest changing LineEdit's default Max Length to, let's say, 1000 characters. My guess is that more than 99% LineEdit use cases never need longer Max Length. Having a default Max Length of decent size would prevent many kind of problems caused by huge strings. 

When the use case _really_ requires longer texts, the developers can change the Max Length longer. If the developer tests the application even once with a long text, it is impossible to not to set the Max Length to proper value from the default 1000. Currently, as the default is unlimited, most of the time developers do not even think about setting the Max Length.

**Comment by Calinou** [comment]
I'd avoid setting a default limit that is too low, but setting the limit to 10,000 by default should still prevent freezes.

**Comment by bruvzg** [comment]
>    Paste 1 million characters long text to "Select a setting or type its name" text field in the Project Settings dialog.
>    Press Ctrl-A (to select all text).

Interesting, I would expect pasting and editing extremely long text to be slow, but selection causing the issue is strange. Adding a reasonable limit is OK, but probably worth checking what's exactly is causing slowdown.

**Comment by bruvzg** [comment]
Found the issue - #60136, with this change, selection should be instant regardless of the length of the text, but I guess some reasonable limitation is good to have anyway (maybe 64 K).
