### ISSUE TITLE
Camera H/V offset is not applied to camera preview and needs to restart editor

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#6011]
**Operating system or device - Godot version:**
2.1rc1 w64
2.0.4.1 w64

**Issue description** (what happened, and what was expected):

The 3d camera H/V offset parameter is not applied in real time to the camera preview into the 3d viewport.
The editor needs to be restarted.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by DualMatrix** [comment]
Seems to still be relevant in master. Not super knowledgeable about the 3D camera though.

**Comment by karliss** [comment]
I couldn't repeat it with Godot 3.1 beta4 on Linux.

**Comment by aaronfranke** [comment]
This bug doesn't exist in 3.1.0 stable. The camera preview updates live with any change.
