### ISSUE TITLE
Camera H/V offset is not exposed to gdscript

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#6012]
**Operating system or device - Godot version:**
2.1rc1
2.0.4.1

**Issue description** (what happened, and what was expected):

THe 3D camera has a H/V offset available into the Inspector. But this parameter and related methods are not exposed to gdscript.

On the other hand, Camera2D has a set of set/get_h/v_offset() methods.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by JulienGio** [comment]
This is barely an enhancement.
A lot of paramaters that are in the inspector don't have dedicated getters/setters. You can always use `set(property, value)` to change any property to the wanted value. http://docs.godotengine.org/en/latest/classes/class_object.html?highlight=set#id4
The parameter **property** is a string corresponding to the property you want to set (note: if you hover over a parameter in the inspector, the tooltip(example below) will show the parameter name), and **value** is the desired value for that property.

So, in your case @SuperUserNameMan you can type for example `set("h_offset", 3.5)`

Tooltip thing I was talking about:
![tooltip_example](https://cloud.githubusercontent.com/assets/20727749/17369285/ffb4c912-5997-11e6-9cf7-bee02a44e7bd.jpg)

Also, one last thing, there is a `get(` function as well that works the same way :wink: 
http://docs.godotengine.org/en/latest/classes/class_object.html?highlight=set#id1
