### ISSUE TITLE
【Crash】Godot4.0 alpha6, when you export a model from Blender without exporting materials。。。

### ISSUE THREAD

**Issue by Atem1995** [godotengine/godot#60139]
### Godot version

Godot4.0 alpha6

### System information

Window 10

### Issue description

Godot4.0 alpha6, when you export a model from Blender without exporting materials, the material in the model import bar is empty and cannot be clicked, and the program will crash as soon as you click it
![1](https://user-images.githubusercontent.com/52338846/162732688-36a730c5-ae2a-409d-a5c3-297972e5f9ed.PNG)
![2](https://user-images.githubusercontent.com/52338846/162732718-3100031a-0e08-4e2e-9cca-0bb600fda97d.PNG)
.

### Steps to reproduce

#

**Comment by Atem1995** [comment]
By the way, will godot 4.0-stable support HTML5 platform？When can we have a test for it?

**Comment by Calinou** [comment]
> By the way, will godot 4.0-stable support HTML5 platform？When can we have a test for it?

Godot 4.x will only support HTML5 once a production-ready OpenGL renderer is implemented. This will take a while to materialize, and may only be done by the time Godot 4.1 is released.
