### ISSUE TITLE
`match` statement performs strict type checking unlike `if`, causing it to fail unexpectedly when comparing String to StringName

### ISSUE THREAD

**Issue by djmaesen** [godotengine/godot#60145]
### Godot version

4.0 alpha5

### System information

linux

### Issue description

im trying to use "match" statement when an animation has finished.
however it doesnt work anymore. print debug doesnt see the match of an animation name

an "if" statement does work however

### Steps to reproduce

```gdscript
func _on_animation_player_animation_finished(anim_name):
		
	if anim_name == "Fire":
		isfiring = false
	
		
	match anim_name:
		"Fire":
			isfiring = false
			print_debug("no match, anim_name=", anim_name)`
```

**Comment by Calinou** [comment]
PS: Code blocks should use triple backticks like this (with an optional language name for syntax highlighting):

\`\`\`gdscript
code here
\`\`\`

I edited your post accordingly, but remeber to do this in the future :slightly_smiling_face:

**Comment by cdemirer** [comment]
`match` is more strict than `==` and only matches if the types are the same, and `anim_name` is `StringName` in 4.0. 
https://docs.godotengine.org/en/latest/classes/class_animationplayer.html#signals

It works with:
```gdscript
match anim_name:
	&"Fire":
		pass
```

**Comment by Calinou** [comment]
> it used to work fine in godot3.

Godot 3.x didn't have a StringName type exposed to GDScript, so everything was a String – including `anim_name` in your example.

> so this is the new syntax i should be using then?

Yes :slightly_smiling_face:

**Comment by djmaesen** [comment]
> > it used to work fine in godot3.
> 
> Godot 3.x didn't have a StringName type exposed to GDScript, so everything was a String – including `anim_name` in your example.
> 
> > so this is the new syntax i should be using then?
> 
> Yes slightly_smiling_face

ok so no bug then
works fine now, tnx!

**Comment by name-here** [comment]
Is there any logic behind `match` being more strict than `==`?  It seems kinda unintuitive.  Do other languages do that?

**Comment by djmaesen** [comment]
> Is there any logic behind `match` being more strict than `==`? It seems kinda unintuitive. Do other languages do that?

i use it to test many anim_names at once. its much cleaner code imo
my example was just one anim_name but my script tests multiple at once 
```gdscript
func _on_animation_player_animation_finished(anim_name):
	match anim_name:
		
		&"Hide":
			isequipped = false
		&"Weild":
			isequipped = true
		&"ReloadA":
			isreloading = false
		&"ReloadB":
			isreloading = false
		&"Fire":
			isfiring = false
		&"FireLast":
			isfiring = false
```

**Comment by Clonkex** [comment]
> Is there any logic behind `match` being more strict than `==`? It seems kinda unintuitive. Do other languages do that?

I agree, it seems unintuitive.

**Comment by tinmanjuggernaut** [comment]
I just ran into this and disagree with the current design. Philosophically, `match` is only supposed to be syntactic sugar for `if a == b` statements.

```
var property: StringName = "alpha"

#matches
if property == "alpha":
     pass

# doesn't match, but should
match property:
    "alpha":
          pass
```

To have `match` and `if` function differently is poor design and a bug IMO.

Also, in GD3, String was supposed to provide unique references, so I could type "alpha" everywhere, or pass it in functions or compare it and it would only pass/compare the reference rather than copying or comparing each letter like a C array.

In GD4, String still says `Strings are reference-counted and use a copy-on-write approach, so passing them around is cheap in resources.` which suggests they should still be unique like StringNames which makes it seem that the latter class is redundant. 

StringName further says `You will usually just pass a String to methods expecting a StringName and it will be automatically converted`, but that's clearly not happening here with `match`.

**Comment by Zireael07** [comment]
> To have match and if function differently is poor design and a bug IMO.

Seconded

**Comment by Calinou** [comment]
I also think `match` should perform loose type matching like `if`, but this is something @vnen should decide. It may also have performance implications to be considered.

**Comment by djmaesen** [comment]
i have no problem using an 'if' statement instead of match, i only posted it cause the syntax was changed

**Comment by tinmanjuggernaut** [comment]
> i have no problem using an 'if' statement instead of match, i only posted it cause the syntax was changed

That's fine, and I'm glad you have a solution. This is now no longer about your individual issue. It's about a philosophical design choice in the language that needs to be worked out for all Godot game devs. So far about 6 people have expressed a desire for reverting the change and no people or reasons for keeping the new behavior.

**Comment by dalexeev** [comment]
See also:

* #74462
* #74872
