### ISSUE TITLE
Selection hitbox messed up on sprite with repeated texture

### ISSUE THREAD

**Issue by Ev01** [godotengine/godot#60141]
### Godot version

4.0 alpha6

### System information

Windows 10, Vulkan Desktop

### Issue description

When I create a sprite with a repeated texture, clicking on the sprite in some areas does not select it.

![godot_select_bug](https://user-images.githubusercontent.com/42711659/162735618-6c1f7c76-57a6-40ee-b869-d6f8e3269d5a.png)

Clicking on any part of the sprite I've highlighted in yellow behaves normally and selects the sprite as expected, but clicking on any other part of the sprite behaves as if I clicked on empty space and deselects the sprite.

### Steps to reproduce

1. Create a sprite with **repeat set to enabled** or mirror
2. Set a **TextureRegion** on the sprite that is larger than the sprite
3. Click on any part of the sprite directly below or to the right of the original. This will select it as normal.
4. Click on any part of the sprite that **is not** directly below or to the right of the original. **This will deselect it** instead of selecting it.

### Minimal reproduction project

[Selection Bug - 4.0 alpha6.zip](https://github.com/godotengine/godot/files/8463883/Selection.Bug.-.4.0.alpha6.zip)

**Comment by Calinou** [comment]
Does it work on Godot 3.4.4?

**Comment by sriramun** [comment]
> Does it work on Godot 3.4.4?

No — the repeat feature was introduced in 4.0 if I'm not wrong.

**Comment by akien-mga** [comment]
Confirmed still reproducible in 4.1 beta 3. CC @kleonc

Note: To open the MRP successfully, make sure to first delete the `.godot` folder, as the imported WebP is incompatible with 4.0-stable and later.

**Comment by kleonc** [comment]
The cause is here:
https://github.com/godotengine/godot/blob/e74bf831c2d3ece79b849405f03999281f807648/scene/2d/sprite_2d.cpp#L312-L333
Currently it's always executing the else block.

**Comment by kleonc** [comment]
> Does it work on Godot 3.4.4?

And for reference it works fine in 3.x, as texture repeat flags are checked accordingly in there:
https://github.com/godotengine/godot/blob/7cfd984e73d6d7d5b29f4079ea7f0e34bf67420b/scene/2d/sprite.cpp#L327-L328
