### ISSUE TITLE
Edited Shortcut Key on Editor Settings follows Scene Undo Redo system

### ISSUE THREAD

**Issue by ScotFlux** [godotengine/godot#6014]
Win 10 x64 - 2.1rc1 at 3eb3752

=> happened:
Edited Shortcut Key on Editor Settings follows Scene Undo Redo system.

=> expected:
Edited Shortcut Key on Editor Settings should not follow Scene Undo Redo system. It should be independent, so that when I press Ctrl+Z, Modified Shortcut Key doesn't revert to it's original state (default value)

![editorsettings_shortcuts_-_follows_undoredo_system](https://cloud.githubusercontent.com/assets/10663548/17342437/6952d456-5923-11e6-8fa3-15ad5f0b502e.png)

**Steps to reproduce:**
1.) Open a project using Godot (3eb3752 or later)
2.) Goto Editor Settings --> Shortcuts --> Edit or Change a Shortcut Key
3.) Close Editor Settings window
4.) Press Ctrl+Z (undo)
5.) Our edited shortcut key back or reverted to its default state.
6.) Press Shift+Ctrl+Z (redo)
7.) Our edited shortcut key going to a state where we had modified it.

**Link to minimal example project** (optional but very welcome):
None

**Comment by ScotFlux** [comment]
Enhancement? Come on my awesome man... This is a real bug. Oh, I'm crying... Is this going to be expected to happen when Godot 2.1-stable released?

Shortcuts intended to be modifiable and must be persistent once modified, isn't it?

@Paulb23 if you have a time, please take a look this issue. If I'm not mistaken, this feature (Distraction Free Mode & Fullscreen Mode) was your cool creation.

**Comment by Paulb23** [comment]
The lines that need changing are [here,](https://github.com/godotengine/godot/blob/master/tools/editor/settings_config_dialog.cpp#L209) [here,](https://github.com/godotengine/godot/blob/master/tools/editor/settings_config_dialog.cpp#L224) and [here](https://github.com/godotengine/godot/blob/master/tools/editor/settings_config_dialog.cpp#L275). Though do editor shortcuts need an undo / redo system as normal settings don't?

**Comment by bojidar-bg** [comment]
The reason this is not a bug is that it is semi-intended behaviour -- e.g. it does what it has to do, by providing the user with a way to change shortcuts. It has the ugly side-effect of reusing the editor's  undo/redo, but I don't know a lot of people that would first change the shortcuts, then proceed to undo their current creation. Also, the undo-redo information is gone after restarting the editor, and I don't think anyone would change shortcuts every day. If anyone of @godotengine/bugsquad  thinks this is an actual bug, he can change the label easily.

**Comment by ScotFlux** [comment]
I understand it very clear my awesome bugsquad. Practically I do not have that problem, because I can easily modify the shortcut to match KEYS i ever want and then compile Godot.

But, as always... I will always hate when people who comes from other engines insult/downing Godot just for a very simple thing. Shortcut in this case. Let's take a look at Notepad++, Blender, Cinema4D, Modo, Maya, etc. all modifiable shortcut key is made persistent just follow what defined by user.

> I don't think anyone would change shortcuts every day

That's why modifiable shortcut key in almost (if not all) softwares made to be persistent (a.k.a saved) for user preference. So, that they do no need to change it every day. But, in current Godot state, they (people who want to use shift+B instead of Ctrl A) will need to change the modified shortcut not only everyday, but also every Ctrl+Z pressed. xD

@Paulb23 I'm not affected by this issue, because I modify the key I want to use before compiling Godot by myself. Who the one affected by this issue? It's Godot reputation.

> do editor shortcuts need an undo / redo system as normal settings don't?

IDK, but shortcut key is currently affected by Scene Undo Redo system, which must not happen.

If shortcut key (which is intended to be modifiable) can't follow what user want (let's say, John Carmack wants to change ctrl+A to shift+B), then it's surely a bug.

But, if you guys, still with your awesome style, It's ok. I will not give my opinion again in this regard. This time, I could not be wrong. haha lol

**Comment by bojidar-bg** [comment]
@ScotFlux Wait, it resets at the next Ctrl-Z, or it shares the undo/redo stack with the other parts of the editor? (e.g. if you put a shortcut, then move a sprite around, would Ctrl-Z undo _both_?)

**Comment by ScotFlux** [comment]
Yes, that it is. I managed to make a video on my new shiny channel.

ShortCut Settings Bug Godot 2.1stable

[https://www.youtube.com/watch?v=50lGryhfjhw](url)

**Comment by bojidar-bg** [comment]
@ScotFlux No, you didn't test what I told you :laughing:. I said _first_ assign the shortcut, __then__ move the sprite around, _and finally_ press Ctrl-Z.

**Comment by ScotFlux** [comment]
Can't reproduce it that way. Then, it did not undo both. It happened if something like this done : 

case 1:
assign shortcut (1) -> add node sprite (2) -> press Ctrl+Z Two times  ==>>  Shortcut back to previous state + sprite node gone

case 2:
add node rigidbody2d (1) -> assign shortcut (2) -> add node sprite (3) -> add node collisionshape2d (4) -> press Ctrl+Z Three times  ==>> Shortcut back to previous state + sprite node gone + collisionshape2d node gone + rigidbody2d still there

**Comment by bojidar-bg** [comment]
Ok, it would remain as "enchancement" then, since it doesn't revert at the first Ctrl-Z, but only when you have cleared the undo/redo stack items after the shortcut change. As mentioned by the tags, it should be relatively easy to fix for a future 2.1.1 or 2.2 :smile: 

@ScotFlux Thanks for the testing.

**Comment by clouds56** [comment]
Affected by this and it's a weird feature, be confused at the first time.
Vote for not adding shortcut change into undo stack, and I think it doesn't take much time to fix.
