### ISSUE TITLE
[Suggestion] Visually Linking Nodes

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#6015]
One thing that I think will help _tremendously_ with map creation is the ability to link nodes together on the scene editor.  This idea came from using the `ImpactJS` engine years ago. 

Example:
![](http://impactjs.com/files/weltmeister-tutorial-entities.png)

Godot's version:
![untitled](https://cloud.githubusercontent.com/assets/10387670/17345326/49ca7a76-58ba-11e6-89d8-7285d8ab7688.png)
I'm not sure if this is possible already (havn't found anything yet :8ball: ), but I think this would make complex map creation much easier. And also resulting in much more complex games / maps being created with Godot :)

**Comment by reduz** [comment]
Don't really understand what this is

**Comment by Zylann** [comment]
I looks like a visual representation of referencing nodes withing other nodes. For example, Warp Trigger would teleport the player to WarpTo, which is done by referencing WarpTo into WarpTrigger.

This is nice, but it can actually be done already, it just needs a bit of `tool` code. A generic implementation would inspect the node's properties, and if one is a NodePath or a Node, find that node and draw a line between the source and destination.

**Comment by Dillybob92** [comment]
@reduz Sorry, bad at explaining things, @Zylann basically hit the nail on the head.

**Comment by bojidar-bg** [comment]
Blender does this nicely with dashed bluish lines between objects that referred by another.

Basically, as @Zylann said, we need to get all `export(NodePath)` properties, and connect the centres of the nodes related (with or without an arrow).

I think I requested this before, but I can't find the issue. Maybe I was just thinking of it :wink:

**Comment by puppetmaster-** [comment]
Look at this [video](https://www.youtube.com/watch?v=vsxB4L6rufo) he has implemented something similar.

**Comment by bojidar-bg** [comment]
I was able to make a quick-and-(very)-dirty EditorPlugin with GScript for this:
![image](https://cloud.githubusercontent.com/assets/5276727/17364566/8b855024-5989-11e6-85e9-1eaa72328706.png)

The hardest part was getting access of the scene, but it's doable with workarounds :wink:

I might upload it to the asset library, unless someone thinks it should be in core. (Also, it currently isn't done for 3D, but it shouldn't be too hard.)

**Comment by rgrams** [comment]
@bojidar-bg  That's sweet. How did you get which nodes to check? I'm assuming you didn't go through the whole tree.

**Comment by bojidar-bg** [comment]
Actually, I realised that most of what I've done should be thrown away, since it is way too hackish. But that would be another day :smile: 

@reduz Do you think this can/should go into core?

**Comment by spookdogg** [comment]
This sounds like a REALLY cool idea, maybe make it an option in editor settings or "Edit" panel? (the panel with the pixel snap etc.)
would definitely +1 into making it a core feature

**Comment by NSasquatch** [comment]
Maybe add it as an option when exporting variables? Something like this:

    export(NodePath, true, "#ffffff", "dotted") var node

**Comment by akien-mga** [comment]
*Bug triage note:* The original issue reporter closed all their issues before deleting their account. If you are affected by a similar issue/want a similar feature, please file a new ticket (referencing this one if it contains useful information) so that it can be further looked at and eventually resolved.
