### ISSUE TITLE
Datetime string does not take decimal fraction into account

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#60173]
### Godot version

3.x (8f4f3841313c7cbb70a8e7370952ab42b5d292da) master (788f355ad2f8c1826f5e55477249934d45d62891)

### System information

Arch Linux, GLES 3, Mesa Intel(R) UHD Graphics (CML GT2)

### Issue description

Unix time taken/returned by APIs are `int64_t`s. The only exception is `get_unix_time_from_system()` which returns a `double`.

`get_unix_time_from_datetime_string()` parses ISO 8601 datetime string into unix time. But fraction of seconds are allowed in an ISO 8601 string. It currently ignores the fraction part:

```
2022-01-02T03:04:05.6789  => 1641092645
2022-01-02T03:04:05       => 1641092645
```

So the result of calling `get_datetime_string_from_unix_time()` with the return value of `get_unix_time_from_datetime_string()` is not the same as the original input.

### Steps to reproduce

Run this script with `-s`:

```gdscript
extends SceneTree

func _init():
	print("===== Start =====")

	var str1 := "2022-01-02T03:04:05.6789"
	var str2 := "2022-01-02T03:04:05"

	print("%-25s => %s => %s" % [str1, Time.get_unix_time_from_datetime_string(str1), Time.get_datetime_string_from_unix_time(Time.get_unix_time_from_datetime_string(str1))])
	print("%-25s => %s => %s" % [str2, Time.get_unix_time_from_datetime_string(str2), Time.get_datetime_string_from_unix_time(Time.get_unix_time_from_datetime_string(str2))])

	print("====== End ======")
	quit()

```

It produces:

```
===== Start =====
2022-01-02T03:04:05.6789  => 1641092645 => 2022-01-02T03:04:05
2022-01-02T03:04:05       => 1641092645 => 2022-01-02T03:04:05
====== End ======
```

**Comment by timothyqiu** [comment]
This is not a Linux specific issue. Unix timestamp is available on all the platforms (in `Time`).

**Comment by timothyqiu** [comment]
@aaronfranke Do you think we should use `double` for all timestamps, or we should error/warn for datetime strings with decimal fraction?

**Comment by aaronfranke** [comment]
@timothyqiu There's a lot of things to consider if we want to support sub-second precision.

Sure, we could parse the fractional part when converting a string into a timestamp and make the timestamp be a double. But how much precision do we want to support, and for what duration? Doubles can do seconds for millions of years, but milliseconds will only work for thousands of years, and microseconds probably already don't work.

What about when converting to a string, how many decimal places do we want? I guess it would have to be specified in an argument. How would we represent this in a Dictionary? Would we have an integer for the number of milliseconds, microseconds, nanoseconds, or maybe just store a double that stores the fractional part?

To be honest, it's easy to just handle this manually. If you're parsing a string you can just split based on `.`, pass the left side to the Time singleton, and interpret the right side as a float. Likewise, if you're going the other way and building a string from a number, just pass the int-casted value to the Time singleton, convert the decimals to a string and concatenate it. And I don't know how often this is needed. Is it worth adding complexity to this API if it's not a commonly used feature and it's easy to work around?

**Comment by timothyqiu** [comment]
> And I don't know how often this is needed. Is it worth adding complexity to this API if it's not a commonly used feature and it's easy to work around?

This is because `Time.get_unix_time_from_system()` returns a `double` as timestamp. It does not work well with other APIs that takes a timestamp.

**Comment by aaronfranke** [comment]
That method uses `double` because that's what the internal `OS` class provides. ¯\\\_(ツ)_/¯ Yeah we can document it.
