### ISSUE TITLE
emit_signal() doesn't checks if the signal exists

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#6017]
Tested on Godot 2.0.4 and 2.1 rc1, Windows 10 64 bits

When emit_signal() is called in GDScript, you can actually send one that was never declared with the `signal` keyword.
This is error-prone because you can end up emitting a signal successfully while it's actually a wrong one that was never declared. It took me some time to debug this in my project, to realize I made a typo in `emit_signal`.

I expected an error to occur when sending a non-existent signal, because that's the point of declaring them with `signal`.

Repro:
[EmitSignalNoCheck.zip](https://github.com/godotengine/godot/files/398326/EmitSignalNoCheck.zip)
Play main scene, click on the button.

**Comment by neikeq** [comment]
Agree. At least in debug builds.

**Comment by Hinsbart** [comment]
I just tried this.
It seems like it's a common thing for the internal classes to try to emit non existing signals...
Running any project with this error check in place generates ~5k of these errors per second. :/
