### ISSUE TITLE
On Quit To Project Manager Dialogues Don't Go To Home Directory

### ISSUE THREAD

**Issue by toliaferrode** [godotengine/godot#6018]
**Operating system or device - Godot version:**
Ubuntu MATE 15.10, Godot 2.1-rc1

**Issue description** (what happened, and what was expected):
Upon going to the Project Manager from the editor (hitting CTRL + SHIFT + Q) the New Project and Import dialogues don't go back to the home directory like they do if you'd just launched it from the executable. Instead the New Project and Import dialogues go to the directory where the Godot executable is. It's inconvienant because my Godot is in "/opt/" (although others might put it in /usr/bin) and my Godot projects are in "/home."

**Steps to reproduce:**
Place Godot some where other than in "/home" and from the editor hit CTRL + SHIFT + Q.

**Link to minimal example project** (optional but very welcome):

**Comment by akien-mga** [comment]
Confirmed in the current master and 2.1 branches. It should be quite easy to fix.

**Comment by Shin-NiL** [comment]
You can set your default project path, this way it will always be open on the project manager.

**Godot 2.1**
Settings -> Editor Settings -> Global -> Default Project Path

**Godot 3**
Editor -> Editor Settings -> Filesystem -> Directories -> Default Project Path

**Comment by toliaferrode** [comment]
@Shin-NiL Thank you so much!

**Comment by ivodopiviz** [comment]
This doesn't seem to be valid anymore as of c2c82a6ea. At least under Linux.

**Comment by akien-mga** [comment]
It's indeed fixed in 3.0/the master branch (always defaults to $HOME regardless of $pwd), and still valid in 2.1 (defaults to $pwd initially, then after going back to project manager, defaults to executable directory).

**Comment by akien-mga** [comment]
At this stage I doubt we'll work on fixing this in the 2.1 branch as it's quite minor, so closing as fixed in 3.0.
