### ISSUE TITLE
Misplaced tooltips when the mouse cursor leaves the window

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#60184]
### Godot version

v3.5.beta3.official [3c0d32562]

### System information

win10 64

### Issue description

This also happens occasionally in the editor.
That informative text simply stays there when the cursor is outside the area for that text.

https://user-images.githubusercontent.com/19652075/163037574-5e85d17e-6749-4afa-81d0-381e091d5db2.mp4

### Steps to reproduce

See the video

### Minimal reproduction project

...

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/59950 (possible duplicate?).

**Comment by KoBeWi** [comment]
Actually both issues are duplicate of #46737

**Comment by Torguen** [comment]
True, I did not remember that I had already reported it.
