### ISSUE TITLE
Multitouch with Apple Pencil + Finger does not work

### ISSUE THREAD

**Issue by pfeodrippe** [godotengine/godot#60190]
### Godot version

3.4.4

### System information

Ipad 8th generation with OS 14.6

### Issue description

Cannot use Apple Pencil + Finger at the same time, only when one is released that the other starts to work.

Finger + Finger works fine.

### Steps to reproduce

Run the Game of Life (Shader) sample (see below)

### Minimal reproduction project

https://godotengine.org/asset-library/asset/842

**Comment by fire** [comment]
@JFonS maybe you have some special insight?

**Comment by pfeodrippe** [comment]
Opened https://github.com/godotengine/godot/pull/60224 @fire @JFonS.
