### ISSUE TITLE
font setting of theme is ignored

### ISSUE THREAD

**Issue by pseidemann** [godotengine/godot#60222]
### Godot version

v3.4.4.stable.official [419e713a2]

### System information

macOS 12.3.1 (21E258)

### Issue description

Creating a theme, which is set as the default theme inside the project settings, lets me change the font color of a button, but the setting for the font type is just ignored, even though the different font is visible in the preview.

### Steps to reproduce

1. Create theme, set button font
2. Set theme as default in project settings
3. Add a button to the scene

### Minimal reproduction project

[bug_font.zip](https://github.com/godotengine/godot/files/8485096/bug_font.zip)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/48477 and https://github.com/godotengine/godot/issues/33902 (possible duplicate?).

**Comment by KoBeWi** [comment]
This might've been fixed in 3.5

**Comment by raulsntos** [comment]
Yes, it was fixed in #55497
