### ISSUE TITLE
Godot 4: Transparent materials don't render over materials with refraction on

### ISSUE THREAD

**Issue by macryc** [godotengine/godot#60232]
### Godot version

4.0 alpha 6

### System information

Win10, GLES3, RTX 2070 mobile

### Issue description

A transparent material does not render when there is a different material behind it that has refraction turned on. See below: I'm adding a transparent smoke texture to a plane mesh that hovers over the ground plane underneath. I'm toggling refraction on/off on the ground plane.

https://user-images.githubusercontent.com/82995330/163331744-e622384f-cbdc-4ca4-8d63-629b7e19672e.mp4

:

### Steps to reproduce

Create a plane mesh (mesh A) and add a standard material to it
Enable alpha and refraction on the material
Create another mesh (mesh B) with a new standard material
Enable alpha on mesh B material and put a transparent texture into abledo
Rotate the view so that Mesh B is in front of Mesh A
Notice how Mesh B material doesn't render

**Comment by Calinou** [comment]
This is a [rendering limitation](https://docs.godotengine.org/en/stable/tutorials/3d/3d_rendering_limitations.html#transparency-sorting) of the 3D engine, as refractive materials are always transparent. You may be able to alleviate this by changing **Render Priority** on the transparent materials, but it won't work in all situations.

**Comment by macryc** [comment]
> This is a [rendering limitation](https://docs.godotengine.org/en/latest/tutorials/3d/3d_rendering_limitations.html#transparency-sorting) of the 3D engine, as refractive materials are always transparent. You may be able to alleviate this by changing **Render Priority** on the transparent materials, but it won't work in all situations.

Does that mean that we can't, eg, make smoke particles over a transparent water surface that has refraction on ?

**Comment by Calinou** [comment]
> Does that mean that we can't, eg, make smoke particles over a transparent water surface that has refraction on ?

Did you try adjusting the Render Priority property?

**Comment by macryc** [comment]
@Calinou Yep. No change:(

**Comment by Calinou** [comment]
> @Calinou Yep. No change:(

Can you try creating the same scene setup in 3.x and see if it looks correct?

**Comment by macryc** [comment]
It looks correct in 3.x.
Also, I've rebooted Godot, set the ground refracted surface's material to the lowest render priority (-128) and indeed I can now see the smokelet over it. It looks a little washed out but it's there.

**Comment by QbieShay** [comment]
This is an issue specifically with large transparent surfaces interacting with one another. Since tansparent objects are either rendered before or after another transparent object and they cannot intersect, there aren't a lot of ways to fix this. Level design should account for those limitations. Making an extra back buffer copy per each refractive object would be tremendously expensive.

**Comment by QbieShay** [comment]
Closing this as I don't think there's any realistic solution on the engine side for this issues.

**Comment by Zireael07** [comment]
I guess it could be documented better that refraction is transparency in practice

**Comment by QbieShay** [comment]
I found the documentation here: https://docs.godotengine.org/en/4.1/tutorials/3d/standard_material_3d.html#refraction

If you think it can be improved don't hesitate to open an issue/pr on the documentation repo ^^
