### ISSUE TITLE
v4 Crashing when selecting material in import window

### ISSUE THREAD

**Issue by oskarious** [godotengine/godot#60236]
### Godot version

4.0-alpha6

### System information

Windows 10

### Issue description

I am running into a crash where if you have an imported model (.glb in my case) where there are no materials specified, godot will crash when selecting the empty material. Not much more to it to be honest, just needs to handle when there are no materials specified in the imported model (or scene I guess in gltf's case).

![bild](https://user-images.githubusercontent.com/16356364/163358038-ffb333e8-c27d-4ec6-ad62-8149d178e375.png)

### Steps to reproduce

- Create a model and omit any materials.
- Import into godot
- Double click the model resource to open the "Advanced Import Settings" window
- Go to the materials tab
- Click the empty/missing material
- Observe godot crashing

### Minimal reproduction project
[EmptyMaterialCrash.zip](https://github.com/godotengine/godot/files/8488122/EmptyMaterialCrash.zip)
The reproduction project includes 2 meshes where one has a material included and the other is missing materials so you can observe when it crashes and when it does not

**Comment by fullhamalti** [comment]
Duplicate of #54807

**Comment by oskarious** [comment]
> Duplicate of #54807

Oops, you are correct, I thought I had searched for it, but apparently not good enough. Thanks!
