### ISSUE TITLE
Alpha 6: 2d animation name bug in editor

### ISSUE THREAD

**Issue by useyourfeelings** [godotengine/godot#60244]
### Godot version

Godot 4 Alpha 6

### System information

win10

### Issue description

Create 2 animations in an AnimatedSprite2D node, 
Click anim_2 while editing anim_1's name.
mess

### Steps to reproduce

Create 2 animations in an AnimatedSprite2D node, 
Click anim_2 while editing anim_1's name.

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/55769.
