### ISSUE TITLE
Unsafe reads may occur when switching quickly between sections in Settings dialog

### ISSUE THREAD

**Issue by Rindbee** [godotengine/godot#60259]
### Godot version

v4.0.alpha4.official [f47097973], v4.0.alpha5.official [d7d528c15], v4.0.alpha6.official [e4f0fc50f], commit 97a8d0785700d4c89a58bac442651725d84b5e83

### System information

Linux Mint 20.3, Vulkan, NVIDIA GeForce GTX 1050 Ti

### Issue description

In Editor Settings/Project Settings, ~~changing settings may result in `property_not_found` warnings.~~ quickly cycle through sections to open, `property_not_found` warnings will appear. Easier to appear after changing settings in Editor Settings Dialog.

Please pay attention to the name of the property to be obtained in the warning, ~~dirty~~ unsafe reading may occur ~~here~~ when the names of the properties are constructed.

![captrue](https://user-images.githubusercontent.com/30386067/163912188-73c155eb-d38b-44a3-8195-9a87e5ef2d6b.png)

This may be the culprit behind the crash caused by modifying the settings. As changes to some settings take effect immediately. Just a personal guess.

Easier to reproduce in Editor Settings than in Project Settings, probably because changes in Editor Settings are saved on the fly.

### Steps to reproduce

~~https://user-images.githubusercontent.com/30386067/163513278-f6d8b814-ebf8-4ce4-abb0-619926d61563.mp4~~

https://user-images.githubusercontent.com/30386067/163909268-63d27203-bb98-4cba-82f5-6627a140418d.mp4

**Comment by Rindbee** [comment]
I suspect some startup crashes are also related to this.

**Comment by timothyqiu** [comment]
This is not dirty read. It's `EditorProperty` checking for invalid property cache (in `NOTIFICATION_PROCESS` at regular intervals).

Unlike regular Objects, `ProjectSettings` prints a warning when calling `_get()` with nonexistent property, and provides a separate `has_setting` to check for property existence.

**Comment by Rindbee** [comment]
@timothyqiu I mean that a dirty read occurs when the name of the "property" is constructed, not when "_get()" is called.
"property_prefix" is cached and not updated in time. When using the property name, the property name is constructed using the cached "property_prefix".

**Comment by timothyqiu** [comment]
`property_prefix` is only for the "Copy Property Path" feature and several display purposes. It has nothing to do with `EditorProperty`'s cache, i.e. the cache keys don't contain property prefix.

`SectionedEditorInpsector` uses a proxy object to feed `EditorInspector`. The prefix/section is added on the fly when accessing the proxy object's properties.

**Comment by Rindbee** [comment]
I'm not very familiar with the mechanics here, but shouldn't this situation be called a dirty read?

One of the blue part and the red part is dirty, right?

![captrue](https://user-images.githubusercontent.com/30386067/163912188-73c155eb-d38b-44a3-8195-9a87e5ef2d6b.png)

**Comment by timothyqiu** [comment]
Should the action be called a dirty read if:

* what the action does it to check whether it's dirty
* when no cache is involved when reading

But anyway, it does not make much sense bikeshedding about how we name the issue.

**Comment by Rindbee** [comment]
Yeah, regardless of the cause, the read is unsafe in terms of the result.
