### ISSUE TITLE
Vulkan: Texture glitch, flipping around

### ISSUE THREAD

**Issue by theblooopz** [godotengine/godot#60254]
### Godot version

4.0 alpha 6

### System information

Windows 10

### Issue description

https://user-images.githubusercontent.com/44142101/163490584-44a80e24-0022-4a30-bc04-5bc4180d17b8.mp4

### Steps to reproduce

Look at it.

**Comment by Calinou** [comment]
@wcbx Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
