### ISSUE TITLE
Vulkan: Unshaded CanvasItem is being affected by CanvasModulate (unlike in `3.x`)

### ISSUE THREAD

**Issue by h0lley** [godotengine/godot#60250]
### Godot version

v4.0.alpha6.official [e4f0fc50f]

### System information

Ubuntu, Nvidia, Vulkan

### Issue description

In Godot 3, an unshaded CanvasItem would not be affected by CanvasModulate.
This is no longer the case in the current version.

![image](https://user-images.githubusercontent.com/23386940/163473354-ea32a64e-afe4-4d13-879d-75b7b21a0d43.png)

### Steps to reproduce

1. Create a blank project
2. Create a scene
3. Add a Sprite2D node, use icon.png
4. Add a CanvasModulate node, set a dark modulation color
5. Notice the sprite is being affected
6. Add a CanvasItemMaterial to the Sprite2D and set it to unshaded
7. Notice the sprite is still being affected

### Minimal reproduction project

[godot_4_canvas_modulate_unshaded.zip](https://github.com/godotengine/godot/files/8492118/godot_4_canvas_modulate_unshaded.zip)

**Comment by pavlexander** [comment]
I still have the same issue in `4.2.1.stasble.mono.official`

`Unshaded` has no effect on node visibility when `CanvasModulate` node is present..
