### ISSUE TITLE
Mesh Imported with -col doesn't generate lightmap UVs

### ISSUE THREAD

**Issue by Syntaxxor** [godotengine/godot#60257]
### Godot version

4.0.alpha6, 4.0.alpha5

### System information

Windows 10

### Issue description

When I import a mesh via glTF or Blender importers (I haven't checked the other formats), with the Light Baking option set to "Static Lightmaps," it only generates lightmap UVs on meshes without the -col tag.

### Steps to reproduce

Make a file in Blender which has an object with the -col tag and an object without, and import it into Godot. Set Light Baking to Static Lightmaps. The object without the tag will have a UV2, and the object with the tag will not.

### Minimal reproduction project

[LightmapUVTest.zip](https://github.com/godotengine/godot/files/8493293/LightmapUVTest.zip)

**Comment by Calinou** [comment]
Can you reproduce this on 3.4.4?

**Comment by Syntaxxor** [comment]
> Can you reproduce this on 3.4.4?

@Calinou No, I cannot. In 3.4.4, the mesh with -col gets its lightmaps generated normally.

**Comment by Syntaxxor** [comment]
Decided to check in 3.5.beta3, and it generates properly there, too.

**Comment by lyuma** [comment]
Isolated the problem to `resource_importer_scene.cpp` `_pre_gen_shape_list()`

```cpp
static void _pre_gen_shape_list(Ref<ImporterMesh> &mesh, Vector<Ref<Shape3D>> &r_shape_list, bool p_convex) {
	ERR_FAIL_NULL_MSG(mesh, "Cannot generate shape list with null mesh value");
	ERR_FAIL_NULL_MSG(mesh->get_mesh(), "Cannot generate shape list with null mesh value");
	if (!p_convex) {
		Ref<ConcavePolygonShape3D> shape = mesh->create_trimesh_shape();
		r_shape_list.push_back(shape);
	} else {
		Vector<Ref<Shape3D>> cd;
		cd.push_back(mesh->get_mesh()->create_convex_shape(true, /*Passing false, otherwise VHACD will be used to simplify (Decompose) the Mesh.*/ false));
		if (cd.size()) {
			for (int i = 0; i < cd.size(); i++) {
				r_shape_list.push_back(cd[i]);
			}
		}
	}
}
```
Calling `get_mesh()` will generate and cache the mesh prematurely before all import settings have been fully applied.

One call to `get_mesh()` is unused and just for a log check. The other is only for convex. We could trivially fix trimesh+lightmap UV by moving the ERR_FAIL into the else case, but to do better we need to move `create_convex_shape` into importer mesh, or else clear the ImporterMesh cache afterwards.

It's also frustrating that the `-col` generation code is completely separate from the advanced importer collider generation code. they are so similar, yet different. I bet the convex colliders are not optimized when going through this code path.

**Comment by clayjohn** [comment]
@lyuma I wonder if this has the same root cause as https://github.com/godotengine/godot/issues/64746

**Comment by lyuma** [comment]
sounds like it. All of this code is duplicated because we do the check for "-col" and "-navmesh" and such, and then we chek the advanced importer settings. but the code is subtly different and done at a different point in the import process so it's extremely confusing.
