### ISSUE TITLE
Unexpected rotation animation blending result (quaternion slerp vs animation blending)

### ISSUE THREAD

**Issue by nsf** [godotengine/godot#60262]
### Godot version

4.0 alpha 6

### System information

Linux, Vulkan

### Issue description

I have a simple blend tree setup where I blend two animations. Each animation consists of a single quaternion keyframe. Thus it's not even an animation per se. Of course this is a minimally reproducable example, in real use case I blend between proper two animations.

So, basically, I blend between two quaternions and I expect the result of such blend operation to be equivalent to "slerp" between two quaternions, in particular the shortest rotation path needs to be taken, however animation blending gives a different result. Here are the two videos of it.

Quaternion slerp using tweens and a script (this is what I expect):

https://user-images.githubusercontent.com/12567/163518457-f889e684-9ed3-4832-9500-48a4d1f990cf.mp4

And this is the blending between two animations using AnimationTree:

https://user-images.githubusercontent.com/12567/163518495-e6c1659e-0565-4807-888d-8ff06483eb45.mp4

I've seen some recent pull requests in this area, where code does some quaternion magic to make it "right", e.g. https://github.com/godotengine/godot/pull/57675, might be related.

Perhaps this small use case might be helpful.

### Steps to reproduce

Run the test project, by default it will play the tween animation and you can inspect the AnimationTree node in the editor by activating it first.

### Minimal reproduction project

I've pushed the test project to github: https://github.com/nsf/GodotSlerpTest

**Comment by nsf** [comment]
Additional note:

**Comment by TokageItLab** [comment]
@nsf I think it maybe solved by #60093 and #60235. So If you are using ValueTrack or Rotation3DTrack, you need RESET track to determine the direction of rotation; if you are using Rotation3DTrack **with Bone**, you need set the correct Rest.　I know this thing needs to be added to the documentation later.

If you can build engine please test it or wait next alpha.

**Comment by TokageItLab** [comment]
I tested, probably it seems fine with RESET.

https://user-images.githubusercontent.com/61938263/163677663-e5575a70-901b-4bbb-a381-8685ef255b12.mov

**Comment by nsf** [comment]
Yes, I just compiled it from git and I can confirm it works fine with RESET track. Thanks.
