### ISSUE TITLE
Distraction Free Mode does not open in Godot 3.4.4 MAC via shortcut

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#60268]
### Godot version

3.4.4 Stable

### System information

MacOS Monterey 12.3.1

### Issue description

When in the "Script" view pressing:

Control+Command+D

Does not switch to the Distraction free mode. I need to manually click on the icon to switch to this mode.

### Steps to reproduce

1) Open any script
2) Press: Control+Command+D

You will find the distraction free mode does not open.

The only way to get it to open via shortcuts is to change the default shortcut buttons to something else, such as CTRL+D.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Check in the editor settings' Shortcuts tab if any other shortcut is bound to <kbd>Ctrl + Cmd + D</kbd> by default. If so, the shortcut is likely not triggered because it conflicts with another shortcut.
