### ISSUE TITLE
Methods aren't being called in the animation track

### ISSUE THREAD

**Issue by GamesOnAcidzz** [godotengine/godot#60264]
### Godot version

Godot 4 Alpha 6

### System information

Windows 10

### Issue description

I tried calling a method in the animation track and it just doesn't work

### Steps to reproduce

add a method in the animation track

**Comment by Calinou** [comment]
@GamesOnAcidzz Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by GamesOnAcidzz** [comment]
so sorry it was my bad, I didn't know the blend filters also filter methods
