### ISSUE TITLE
Godot 4 alpha 6 : Can't load Albedo Texture in StandardMaterial3D.

### ISSUE THREAD

**Issue by Berkru** [godotengine/godot#60279]
### Godot version

4.0 alpha 6 [ e4f0fc50f ]

### System information

ubuntu 21.10

### Issue description

Can't load Albedo Texture in StandardMaterial3D or even in a custom shader.

### Steps to reproduce

1) Add a meshInstance3D
2) add a StandardMaterial3D to it.
3) try to load any texture.
(Also doesn't work for my custom shader)

**Comment by Calinou** [comment]
@Berkru Can you upload the texture here in question? (Compress it within a ZIP archive if you can't drag and drop it here.)

**Comment by Berkru** [comment]
> @Berkru Can you upload the texture in question here? (Compress it within a ZIP archive if you can't drag and drop it here.)

There was something broke with the .import files, I just deleted them and it seems godot re-imported the files, which are working just fine now. The textures are normal jpgs.
