### ISSUE TITLE
Flipping Sprite with Large Texture behaves weird

### ISSUE THREAD

**Issue by timoschwarzer** [godotengine/godot#6027]
**Operating system or device - Godot version:**
Linux, 2.0.4.1

**Issue description** (what happened, and what was expected):
Having a Sprite with a Large Texture:

Normal:
![image](https://cloud.githubusercontent.com/assets/8849554/17381150/d4663eb6-59ca-11e6-9d33-48f76c6f4e81.png)

H-Flipped:
![image](https://cloud.githubusercontent.com/assets/8849554/17381147/ccf2f2f0-59ca-11e6-94a6-327bb8c26a63.png)

**Comment by Chaosus** [comment]
Checked and it seems to be not reproducable in current master, and non-critical for 2.1 branch(if even exist now, 2.0.4.1 is very old version). _Closed by bugsquad._
