### ISSUE TITLE
Error given when trying to export an enum from autoload script

### ISSUE THREAD

**Issue by psdao1102** [godotengine/godot#60283]
### Godot version

3.4

### System information

Windows 10, GLES3

### Issue description

When trying to export an enum for the UI to use in a dropdown, if you specify the type as an enum in an autoloaded script, it gives this error: ` Parse Error: invalid index '<type>' in constant expression`

### Steps to reproduce

Create an autoloaded script, then create a scene, then try to export the enum from your autoloaded script, in your scene

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/14681.
