### ISSUE TITLE
Interpret comma as decimal point in editor

### ISSUE THREAD

**Issue by rumangerst** [godotengine/godot#6028]
**Operating system or device - Godot version:**
Linux (Manjaro) - v2.2 alpha (git custom build)

**Issue description** (what happened, and what was expected):
If you use a German keyboard layout (and maybe other layouts), the "decimal point" is a comma. If you insert numbers into the editor's fields (e.g. the translation) it would be nice if this comma would be automatically replaced by a decimal point. Blender does the same and it this little fix would enhance the workflow.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by RayKoopa** [comment]
Should this get closed? A previous PR implementing this (as far as I can see) has been merged.

**Comment by akien-mga** [comment]
Yep, fixed by #13240.
