### ISSUE TITLE
Typing in font size in RichTextLabel crashes Engine

### ISSUE THREAD

**Issue by thomashempel** [godotengine/godot#60289]
### Godot version

4.0.alpha6

### System information

Windows 11

### Issue description

When adding a RichtextLabel to an Interface you can change the font size in the toolbar by clicking the arrows. But if you type in a font size directly, the editor thinks for a second and crashes. 

### Steps to reproduce

Add a RichtextLabel and try to type in a font size in the toolbar

![Screenshot 2022-04-16 041220](https://user-images.githubusercontent.com/354084/163657692-f98d2228-b55f-49df-9948-bcf33157c746.png)

**Comment by Calinou** [comment]
Which value did you try to enter? Large values can cause the engine to crash due to the rendered font size being too large for the font rasterizer to handle.

**Comment by Zireael07** [comment]
Do we have a warning for those? I have a label in viewport that's size 60 or something and it works, I wonder if it depends on GPU...

**Comment by Calinou** [comment]
> Do we have a warning for those? I have a label in viewport that's size 60 or something and it works, I wonder if it depends on GPU...

Rasterization happens on the CPU. Performance largely depends on the power of two of the font size – it's recommended to avoid exceeding 64.

**Comment by thomashempel** [comment]
That was my first thought too but it doesn't matter what value I type in. It crashes every time. Happy to provide more information if needed.

**Comment by thomashempel** [comment]
Short update, I tried to create a demo project, but I can't reproduce the issue in a clean project. Even in my own project, where I encountered the issue in the first place, settings the font size works now. 
No idea why it is working now, since I have literally changed nothing. So I guess this can be closed.
