### ISSUE TITLE
AnimationTree unexpected blend node results - drift on x axis

### ISSUE THREAD

**Issue by shuvit-game** [godotengine/godot#60306]
### Godot version

v4.0.alpha.calinou [3d8c971ff]

### System information

Windows10, Vulkan

### Issue description

Blend2 and Blend3 AnimationTree nodes are producing unwanted movement on my character rig. Seems to be only on or related to x axis.

If it's something with the rig, advanced apologizes, it's driven me mad.

https://user-images.githubusercontent.com/38700738/163685814-c7564b61-2f0e-4c0e-803a-7ad697137c5e.mp4

4

### Steps to reproduce

Not sure if this is specific to my rig, but it may be related to not having a root or master bone.

### Minimal reproduction project

[anim_blend_test.zip](https://github.com/godotengine/godot/files/8500397/anim_blend_test.zip)

**Comment by TokageItLab** [comment]
@shuvit-game Ahhh indeed. This is a clear case of quaternion approximation by exp map causing errors. Thanks for sharing this with us. Using slerp to interpolate quaternions in blending by #60308, this issue will be fixed.

https://user-images.githubusercontent.com/61938263/163689347-e99a3eb4-9a23-4dd9-a252-02ea65fba450.mov

**Comment by shuvit-game** [comment]
That was quick! Thank you very much for doing the work.

**Comment by shuvit-game** [comment]
This fixed the main issue and some others that I was having, but I noticed this specific blend is still having issues, the opposite foot doesn't have the issue and i haven't identified any other problems:

https://user-images.githubusercontent.com/38700738/163726564-e69430e9-4b96-4240-b2c9-70901dab75c2.mp4

**Comment by TokageItLab** [comment]
This is probably due to the fact that the Hips are animated on a nearly 180 degree rotation from Rest. I would predict that after the motion of rotation the character would be facing backwards.

If you want to blend with the character facing backward, it is safe to rotate the character by Scripting the Node. But, if you really want to solve that on BlendTree, we should make to be able to update Rest in the middle of animation process, or possibly PhaseNode #57959 might help with that.

**Comment by shuvit-game** [comment]
The problem above appears to be related to my rest pose, and not any issues. Initial testing shows that rotating the rest -90 solves it.

**Comment by shuvit-game** [comment]
Update: rotating the rest introduced a whole bunch of new issues and broke other blends.

**Comment by TokageItLab** [comment]
So I recommend to rotate the character as Node with using script with root motion or something, please test it or send sample project.

**Comment by TokageItLab** [comment]
Or, as I said in A, if we could mark the option to do a blend that always takes the shortest path, taking into account the previous frame, I think this would solve the problem completely.

But to do that I need to think about blending that takes the shortest path considering the previous frame and does not cause inconsistencies in more than 3 blends... I will think about it for a while...

**Comment by TokageItLab** [comment]
@shuvit-game Alright, I sent some RootMotion fixes as #60336 and #60349. After they are merged, try to change the way the character rotates in your project by referring to sample project in #60349.

If that does not solve the problem, we will need to discuss #29458 again.

**Comment by TokageItLab** [comment]
I have found a problem with the root motion (https://github.com/godotengine/godot-proposals/issues/4418), please wait a while until it is fixed.

**Comment by TokageItLab** [comment]
@shuvit-game #60774 is now merged, please try using RootMotion to take the rotation that changes the orientation of the character from the Hips transform as a rotation of the Root bone.

**Comment by shuvit-game** [comment]
Thanks, will do as soon as I can. Looks promising.

**Comment by shuvit-game** [comment]
@TokageItLab After just brief playing with my current project, this seems to have resolved the issues. I will open a new issue if further testing reveals anything. I think most previous issues were one-shot related.
