### ISSUE TITLE
GDScript 2.0: String class does not have constructor for type float

### ISSUE THREAD

**Issue by EvanNibbe** [godotengine/godot#60305]
### Godot version

v4.0.alpha.custom_build.7bb963efe

### System information

Ubuntu 20.04.3 LTS

### Issue description

The String class in GDScript does not have a constructor for float.  GDScript 1.0 has this, and my personal project code needs a way to store floating point values inside strings efficiently.
My code looks like 
(on the C++ side, float key_str_at(int i) {return key_str[i];} //where key_str is a simple array of floating point values.
ClassDB::bind_method(D_METHOD("key_str_at"), &RigidDynamicBody3D::key_str_at); //makes this function available in GDScript, which works fine after compilation)
if test_count<10: #/*test_count is*/ var test_count: int=0 #declared at the start of the script.
			var msg: String="The key_str is: ["
			for i in range(45):
				msg+=String(key_str_at(i))+", "
			print(msg+"]")
			test_count+=1 

#Note: I am working with the alpha 5 build, so if this problem was solved in alpha 6, then I will migrate to that.

### Steps to reproduce

All you need to do to see that the bug exists is, in GDScript, write
var thing: float=1.3
var msg: String=""
msg+=String(thing)
print(msg)

### Minimal reproduction project

n/a, you can just download godot v4 and start a new project to see the error.

**Comment by RedHeadphone** [comment]
GDScript String doesn't have constructor for `int`,`bool` too

**Comment by Sauermann** [comment]
Instead of using `String(x)` please try `str(x)`.

**Comment by Zireael07** [comment]
Personally in 4.x I use var2str() for tons of stuff where I used to do str() or String()

**Comment by adamscott** [comment]
I'm closing because alternatives as `str()` and `var2str()` exist to convert `int` and `float` to `String`.
