### ISSUE TITLE
Input Map dialog messed up.  2.1RC2

### ISSUE THREAD

**Issue by floydnunez** [godotengine/godot#6030]
Mac OSX El Capitan. Godot 2.1 RC2

I wanted to add an input map for a joystick button, but the dialog to do so is compressed.

-Go to Project Settings.
-Go to the "Input Map" tab.
-Press "+" on any input and choose "Joy Button" or "Joy Access".
-The little window that lets you choose which joystick and which button is messed up.

<img width="1245" alt="screen shot 2016-08-03 at 23 35 12" src="https://cloud.githubusercontent.com/assets/1719570/17389553/558e654c-59d3-11e6-8984-45421be79b45.png">

**Comment by akien-mga** [comment]
Can't reproduce on Mageia 6 with a 1920x1080 resolution, so I assume it's hidpi-specific.

**Comment by Sslaxx** [comment]
Anyone able to test this on Windows? If it doesn't reproduce there, mark with platform:osx tag?

**Comment by akien-mga** [comment]
I don't think it's OSX-specific, it's a UI size bug, so the culprit is likely HiDPI / Retina, which can also be used on Linux or Windows.

**Comment by neikeq** [comment]
I could reproduce it with HiDPI mode.
