### ISSUE TITLE
Animation Tree Transition Node Capped at 31 inputs

### ISSUE THREAD

**Issue by stryker313** [godotengine/godot#60307]
### Godot version

4.0 Alpha 6

### System information

Windows 10 Nvidia GTX 1060 Intel i5 4690k

### Issue description

You cannot create a transition node with more than 31 inputs

### Steps to reproduce

1. Create an animation tree
2. Create a transition node
3. Try to set the number of inputs above 31

### Minimal reproduction project

No project needed

**Comment by Calinou** [comment]
I guess it's using a 32-bit variable as a bitfield, with 1 of the inputs being reserved (or the variable being signed).

**Comment by TokageItLab** [comment]
It is purely due to the fact that `MAX_INPUTS` is set to `32` in `animation_blend_tree.h`, but why there is an upper limit to it is not clear without a closer look.

**Comment by stryker313** [comment]
Aight I'll be on standby. If `MAX_INPUTS ` is simply arbitrary, do I close this and move it to GIP?

**Comment by TokageItLab** [comment]
Most the reason `MAX_INPUTS` exists is because it was too much work to create a GUI. In fact, it is probably not necessary to have `MAX_INPUTS`, but a lot of work is required just for the GUI. One workaround that comes to mind is to chain TransitionNode.

**Comment by stryker313** [comment]
Chaining transition nodes works, but the idea of increasing the input cap is that it allows for an easier method of animation in regards to certain types of games/styles.

Lets say you have a fighting game, where the character has 100 different moves.
blocks
attacks
hits
misc

It is very simple to call 
animationTree.set("parameters/animations/current",4)-->attack
animationTree.set("parameters/animations/current",5)-->block
animationTree.set("parameters/animations/current",97)-->attack97

You don't have to worry about disabling previous states

You don't have to keep track of all the oneshot node names (animationTree.set("parameters/Attack1/active",true)) This can become problematic in a game that has a lot of animations

The tree can look somewhat cleaner.

It is possible to use chained nodes for this, however, you then have to consider more factors when designing your tree.
(ie. position of the transitions relative to each other)
(ie. disabling the other transitions when 1 is suppose to be active. Transition nodes don't revert to state 0 automatically)

The ability to use 1 massive transition node eliminates these misc factors, and overall offers a cleaner way to use transitions for handling large amounts of simple animations.

**Comment by aXu-AP** [comment]
If you need to have 100 states, likely building full state machine will work better. If you don't need the functionality it offers, just calling AnimationPlayer directly sounds way easier.
