### ISSUE TITLE
Visual script node ' set_albedo ' doesn't work . .

### ISSUE THREAD

**Issue by charlesmlamb** [godotengine/godot#60320]
### Godot version

Godot 4.0 . .

### System information

Windows 10 . .

### Issue description

Just a quick bug ??

In Godot 3.4, this works . . .

![image](https://user-images.githubusercontent.com/83387915/163719464-8ba1c667-ea19-42bc-a4ea-54de2bd0dd78.png)

It changes an albedo, on a simple mesh . . . In Godot 4, this causes an error . . .

![image](https://user-images.githubusercontent.com/83387915/163719595-b2adf9e4-4662-4c45-a091-bed2e26f84f9.png)

I tried connecting both ports, from the 'get_material', either way, an error, something about 'index' . .

So, I'm not sure, does this make sense . . I guess, should one start reporting bugs now, I've been reporting a ton, and, feel a bit tired, and, want to take a break, and, perhaps only report when Godot 4 is near, to RC, just, very tired, though, the engine rocks, of thinking of new things, and, making 'noob' suggestions, I know now most of them were not that useful, in the sense, engine pros, coders knew better, wanted to say thanks, for help / explanations . . :'-)) . .

Not sure, do you want reports for visual script atm, I've been wondering if the system might be under review, or, big re-factor, and, these things are right now just supposed to be there . .

Anyway, hoping for some advice, 1. when do you want to start getting bug reports for Godot 4, not even sure it's a bug, there's an error, etc . . . 2. Is it not required atm, because of some big coding changes, and, 3. How many bug reports do you want / ie., how much will you find yourself, sort-of, how important is it that the Godot community does this, not sure, do you know about these bugs, I guess, those are some questions, so I know when to report bugs, and, how much :-)) . .

Thanks, engine is getting good, Godot 4 is good improvement, over-all it's 9 / 10 +, however, now some things that worked in Godot 3, stopped working, etc . .

### Steps to reproduce

The above code doesn't work, in Godot 4, not sure it's a bug . .

Anyway, looking forward to see what happens in visual script, also, bec. I have used visual shaders, and, it has helped me learn how coding systems work / make demos/prototypes, :-OO . . . 10 / 10 feature, for beginners, learning, and, making something fast, hope you could make it better, in a cool way . . . .

**Comment by Calinou** [comment]
You're trying to get a material from a box that doesn't exist, as you're trying to ask for a `null` instance of BoxMesh to pass its Material.

Also, you should pass the material and not the box instance (which is currently `null`) to set the albedo property.

**Comment by charlesmlamb** [comment]
Uhhh, well, I just got the ' get_material ', from the inspector, and, tried to connect it, it worked in Godot 3, and, still does . .

The ' set_albedo ' is also just from the inspector . .

Ok, made it work . . 

![image](https://user-images.githubusercontent.com/83387915/163723540-e28e167c-4acc-4eb4-a0f1-41ca2393fa35.png)

Also had to use the ' get_mesh ', and, add that to the ' get_material ' . .

It's an amazing system, wow, is it complex, 10.2 / 10 . . :-)) . .

**Comment by Calinou** [comment]
Closing, as this isn't a bug.
