### ISSUE TITLE
Grid x and y axis doesn't draw fully

### ISSUE THREAD

**Issue by JohnnyLeone** [godotengine/godot#6032]
**Operating system or device - Godot version:**
MacOS 10.11.6
4K Monitor

**Issue description** (what happened, and what was expected):
If i use the 2D editor the x and y axis are not fully drawed. This only happens since 2.1 and in combination with a 4K Monitor. With version 2.0 everything alright.

**Steps to reproduce:**
Open Godot 2.1 RC2 and go to 2D Mode

**Link to minimal example project** (optional but very welcome):
<img width="2043" alt="bildschirmfoto 2016-08-04 um 12 20 55" src="https://cloud.githubusercontent.com/assets/2356368/17398623/fa3317e0-5a3d-11e6-8ed7-47cda9e1809a.png">

**Comment by bojidar-bg** [comment]
Can confirm, seems like it is limited by the bounding box of the scene.

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.
