### ISSUE TITLE
4.0 GradientTexture2D does not return an image with get_image() right away

### ISSUE THREAD

**Issue by Verthae** [godotengine/godot#60333]
### Godot version

4.0 alpha 6 build

### System information

Windows 10

### Issue description

`GradientTexture2D` does not return an image object from `get_image()` during `_ready()`, but if you give it more time it generates.
![image](https://user-images.githubusercontent.com/88465477/163738193-d0170717-ecab-4317-a639-30f21e263a7d.png)

A `GradientTexture1D` doing the same will get a valid `Image` object immediately.

### Steps to reproduce

Create a TextureRect.
Assign a GradientTexture2D to the texture
Give the TextureRect a script that simply prints out `texture.get_image()` in `_ready()`
Run the project and notice that output states: `[Object:Null]`
await for a SceneTreeTimer's timeout and print `texture.get_image()` again
notice that it now has a proper `Image` reference.

### Minimal reproduction project

[TextureNoData.zip](https://github.com/godotengine/godot/files/8502721/TextureNoData.zip)

**Comment by Calinou** [comment]
cc @Geometror
