### ISSUE TITLE
Prevent creating projects in folders that can "brick" the editor until moved

### ISSUE THREAD

**Issue by lolbugsnstuff** [godotengine/godot#60332]
### Godot version

3.3.4 flathub

### System information

Chromebook 32bit ran on linux

### Issue description

As soon as I open up Godot it has a tab (and this is the only tab) stating that Error: Can't run project: no main scene defined in the project.
It's just a white box that states that message and no matter what I do I cannot get past this stage, any help?

### Steps to reproduce

To reproduce these circumstances you need to on a Chromebook open a new project once recently download it, leave it empty and leave (I was checking out the software and then left) after that this error message will pop up. 

### Minimal reproduction project

[https://docs.google.com/presentation/d/1LyO5Yk52BFnr1MXw4soUyyKtkWC20i3Dj7SF7u_hLps/edit#slide=id.p](url for the error message)

**Comment by KoBeWi** [comment]
When you run Godot executable inside a project directory, it will run the project instead of opening the editor (unless you run with `-e` argument).

**Comment by Calinou** [comment]
You probably created a project folder directly within your home directory (`/home/<username>`). Don't do this, as Godot will try to run the project in the default working directory for applications that are started.

**Comment by lolbugsnstuff** [comment]
Thanks, I've managed to open godot again.

**Comment by Calinou** [comment]
Reopening, as we should still prevent creating projects in locations that can "brick" the editor.

**Comment by nathanfranke** [comment]
Hmm, I am definitely going to implement something to prevent users from creating a project as their home directory / executable directory. I vaguely remember importing my entire home directory with Godot Engine™, I forget if it broke my install :laughing: 

However, I feel like this could be an engine bug. On linux, we can already pass `--project-manager` using a desktop file, to avoid this completely. What steps would need to be taken to automatically use this flag on Windows/Mac?

**Comment by Calinou** [comment]
Fixed by https://github.com/godotengine/godot/pull/74964.
