### ISSUE TITLE
Project Manager blank window on Windows

### ISSUE THREAD

**Issue by mpalomas** [godotengine/godot#60348]
### Godot version

v4.0.alpha.custom_build.690fefe43

### System information

Windows 10, Radeon 5700XT latest drivers, Vulkan

### Issue description

When I launch Godot built from latest sources (690fefe43), all I get is a project manager window completely blank, nothing showing up inside. I can only close the window, and I never reach the editor.

I launched the binary with -v but no errors in the log. Then I tried to delete all the Godot config files in my AppData: did not help, same issue.

Everything works fine on my workstation, I can play AAA Vulkan based games on Steam, UPlay...

[godot-launch-logs.txt](https://github.com/godotengine/godot/files/8506331/godot-launch-logs.txt)
s

### Steps to reproduce

All I did was:
- git clone
- scons target=release_debug -j 12
Build completely successfully, then I launched .\bin\godot.windows.opt.tools.64.exe -v

**Comment by Calinou** [comment]
Does it work if you start the project manager with `--rendering-driver opengl3 --single-window`?

**Comment by mpalomas** [comment]
So I rebooted my machine, and then Windows told me I needed to reboot again, because of hardware changes (last hardware change was 2 years ago...), anyway I obliged and oh problem solved: the default Vulkan backend works and I can see the project manager! OpenGL is crashing but I don't mind as long as Vulkan works.
Anyway, sorry for the noise, Windows can be frustrating and unpredictable.

**Comment by Calinou** [comment]
> OpenGL is crashing but I don't mind as long as Vulkan works.

I forgot OpenGL was currently broken in `master`, so there's no way it could have worked anyway.
