### ISSUE TITLE
4.0 Custom Project Settings with feature tags are displayed incorrectly

### ISSUE THREAD

**Issue by Lielay9** [godotengine/godot#60352]
### Godot version

4.0alpha6

### System information

Windows 10 Vulkan, Nvidia 1050TI (Reproduced on desktop 2080TI)

### Issue description

Expected:

![Expected](https://user-images.githubusercontent.com/40064911/163835052-aa864352-0993-4817-8b5d-606a1c33178b.jpg)

Got:

![Got](https://user-images.githubusercontent.com/40064911/163835097-427f1efd-d7b5-4ca6-930d-e2a206e21021.jpg)

Names are only displayed incorrectly; the project.godot-file has correct names, the tooltips use correct paths and the settings can be referred from the expected paths from code. Based on a quick test it seems that all tags produce similar results depending on their length.

Also a relevant comment from @Calinou:
> This is likely a regression from [godotengine/godot#58706](https://github.com/godotengine/godot/pull/58706) ... I've been able to reproduce this too but I don't know exactly why it's broken.

Also also. When trying to reproduce this bug, I found out that the reset-icons next to the custom project settings don't reset the value to the default variable value but instead delete the setting altogether. (In 3.x there are no reset-icons). If not linked to this issue, then perhaps another bug.

### Steps to reproduce

Add a custom project setting that has a feature tag. (.windows, .android etc.)

**Comment by Calinou** [comment]
cc @timothyqiu

**Comment by Rindbee** [comment]
May be related to the code here.
https://github.com/godotengine/godot/blob/690fefe43ee74c0ae3ed5642f3aefbeb711f9d1c/editor/editor_inspector.cpp#L2679-L2688

```
feature_tag = name_override.right(dot); 
```
Here should be the substring to the right of the "."

**Comment by timothyqiu** [comment]
@Rindbee Yeah, the behavior of `right()` changed on `master`. This is a cherry-pick mistake I made :(

**Comment by Rindbee** [comment]
Darkening of the labels also seems to be an issue.

**Comment by timothyqiu** [comment]
The labels are darkened when it's an override. When the dot is lost, it's not darkened.
