### ISSUE TITLE
GUI type variations don't work

### ISSUE THREAD

**Issue by DimitriyPS** [godotengine/godot#60351]
*Bugsquad edit: This refers to https://github.com/godotengine/godot/pull/57942.*

### Godot version

3,5 b4

### System information

All OS

### Issue description

I create a theme with inherited style:
![0000](https://user-images.githubusercontent.com/11189223/163835193-88d5b929-e6ad-4890-8313-a260ee12d2b3.png)
I want to make a style selection, but there is none:
![111111](https://user-images.githubusercontent.com/11189223/163835682-22bd9d76-1829-452e-94ab-9eabd5f7c87e.png)

### Steps to reproduce

1. Open a project
2. Make a style selection for the button

### Minimal reproduction project

[Т2.zip](https://github.com/godotengine/godot/files/8506702/2.zip)

**Comment by KoBeWi** [comment]
Bbbbutton should appear on the list (it's correctly configured as subtype of Button). Same issue in 4.0

**Comment by timothyqiu** [comment]
This is expected. Only type variantions in the project's default theme (`gui/theme/custom`) will be listed in the dropdown.

See description in #50169.

**Comment by KoBeWi** [comment]
Seems like all is documented under `set_type_variation()`, so this can be closed.

**Comment by DimitriyPS** [comment]
And this greatly limits the use ... for example, now I use a code-generated theme ... and in another project I have two code-generated interface themes at once.

This innovation... looked very useful.

**Comment by KoBeWi** [comment]
You can't select them from list, but you can write the type by manually.

You can open a [proposal](https://github.com/godotengine/godot-proposals) if you want this changed, but this might require complex changes to Theme, as stated in the original PR.

**Comment by DimitriyPS** [comment]
Well, at least now I understand why it didn't work for me. I won’t write an application for revision ... I guess I won’t see it in the coming years ... so it makes no sense for me to focus on this.

**Comment by DimitriyPS** [comment]
Experimented a bit... I can't do it in the editor, but I can do it in code. And yes! It is very comfortable!
