### ISSUE TITLE
Vulkan: Massive performance hit when rendering transparent objects

### ISSUE THREAD

**Issue by novemberist** [godotengine/godot#60364]
### Godot version

Godot 4.0 dev, commit 690fefe43ee74c0ae3ed5642f3aefbeb711f9d1c

### System information

Fedora Linux 36 Beta, Vulkan, Gnome 42 (Wayland), Radeon RX580 (Mesa 22)

### Issue description

I know that a certain performance hit is to be expected when rendering objects that have transparent parts. The official Godot documentation specifically suggests that transparent objects in a scene should be kept to a minimum. However, in practice, for certain kinds of assets, there is just no way around using transparent textures to avoid an otherwise insane vertex count, which is also very bad for performance (e.g. grass, foliage, trees etc.)

I've been playing around with grass and tree assets inside Godot lately and noticed that the performance hit is insane. Even a simple tree with a couple of planes and transparent textures easily brings my framerate down from 200 to something like 40, when using Alpha Scissor or Depth Pre-Pass with Depth Draw set to "Opaque Only". 

I understand that these are mostly limitations by the way graphics rendering works and that in production a lot of trickery is involved to keep the amount of overdraw low. However, there are a lot of games that use a lot of foliage and trees and still perform well. I can't imagine that this would be currently possible with Godot and think there might be something wrong with transparency rendering.

The attached example might be a little extreme, but should illustrate the issue. It uses GPUParticles3D to render 20.000 patches of grass on a plane. Enabling transparency (Depth Pre-Pass with Opaque Only Depth Draw) reduces the framerate from around above 300 to below 30. 
![Bildschirmfoto vom 2022-04-19 02-29-30](https://user-images.githubusercontent.com/7927471/163899850-d7b7cc30-a54e-4eb4-a471-455e52846fa7.png)
![Bildschirmfoto vom 2022-04-19 02-29-12](https://user-images.githubusercontent.com/7927471/163899870-7dfb8c4b-6fa7-4bc2-9ca7-64e876bfe235.png)

### Steps to reproduce

see minimal reproduction project

### Minimal reproduction project
[transparency_test.zip](https://github.com/godotengine/godot/files/8509012/transparency_test.zip)

**Comment by mrjustaguy** [comment]
First off, Shadows are off for these types of effects for grass in 99% of instances, and secondly I don't think grass uses such high res textures.. 1k is overkill for grass, and that's possibly also hurting your performance massively. Replacing with Icon.png which is 64x64 instead of 1024x1024 increased the FPS by a Huge margin, around 4-5x the performance with Alpha Scissor. I was unable to modify the Grass texture and down res it to give a more accurate comparison..

**Comment by novemberist** [comment]
If the texture resolution was the problem, there would be a noticeable performance hit with or without transparency, which isn't the case here. I don't think icon.png serves well for a comparison, since it hardly has any transparent areas. The issue here ist not the low FPS of the example scene, but the extreme FPS difference between Alpha on and off. Shadows don't make much of a difference as far as i can tell.

**Comment by Calinou** [comment]
- Can you reproduce the performance dip after disabling **Depth Prepass** in the Project Settings?
- Can you reproduce the performance dip on a similar scene in 3.x (in GLES3)?

**Comment by novemberist** [comment]
@Calinou thank you for the extensive testing. I will try something similar with Godot 3 and report back, but i guess I will have to write a custom shader for the grass first, since the particle node in Godot 3 ist much less powerfull. The binary Data in the scene ist probably the generated point texture for the emission shape. I didn't realize it was that big, sorry. As a side note: Performance becomes much better when setting the particle scale back to 1. Probably because a smaller particle causes less overdraw?

**Comment by novemberist** [comment]
Just for the record: I can no longer reproduce the massive performance hit from my example project on my new GPU (Intel Arc 750), Fedora 37, Mesa-git. The difference between transparency on and off is more like 20% now and I am well above 100 FPS  with most post-processing options enabled. Now I don't know if something in Godot's renderer changed in the past month or if this is just a case of a more beefy GPU / driver improvements. Anyway, since I can no longer reproduce this with the original setup, I will close this issue in favor of newer reports that might come in once Godot 4 is out and gets more widespead adoption.
