### ISSUE TITLE
Material w/ ViewportTexture Color Inaccuracy (a lot brighter)

### ISSUE THREAD

**Issue by KnightNine** [godotengine/godot#60365]
### Godot version

3.4.2-stable

### System information

Windows 10

### Issue description

I am using color rects to generate a color palette at runtime for a 3D mesh, but I have found that the color shown from the material with the viewport texture is way brighter when compared to a material set to the same `albedo_color` as the color rect's `color`.
![Capture](https://user-images.githubusercontent.com/34152090/163902798-4b698b11-46a5-4dc8-87e9-c983611fbcf2.PNG)

I'd expect it to be the same color.

### Steps to reproduce

- create two MeshInstances with Quat meshes
- create a viewport and material with viewport texture assigned to one of the meshes through a spatial material's `albedo_texture`
- create a color rect within the viewport that covers the whole viewport, set its `color` to something
- set a spatial material to the other quat mesh, with its `albedo_color` to the same color as the color rect.
- observe the difference in shade between the two materials.

### Minimal reproduction project

[Mesh Test.zip](https://github.com/godotengine/godot/files/8509142/Mesh.Test.zip)

**Comment by novemberist** [comment]
Might be related to what @BastiaanOlij has written in this Tweet recently: https://twitter.com/mux213/status/1514029396671479810

**Comment by novemberist** [comment]
I think the texture of your Viewport Mesh Instance is multiplied by the Albedo color of that mesh (in your case is white), which makes it brighter than the other MeshInstance, where you only have an Albedo color and no texture.

**Comment by KnightNine** [comment]
@novemberist  
In rummaging around the settings, I found a flag called `flag_albedo_tex_force_srgb` in the **material** (not the texture) that fixed this issue. 
gonna do some further testing to make sure.

not sure how the solution in https://twitter.com/mux213/status/1514029396671479810 works because ticking `keep 3d linear` in the viewport does nothing.

**Comment by KnightNine** [comment]
yup, it seems to work!

**Comment by Calinou** [comment]
> (maybe the functionality is depreciated or does not work in 3.4.2)

**Keep 3D Linear** is still effective in 3.4.x, both in GLES3 and GLES2. It's just not what you need in this case.
