### ISSUE TITLE
Fails to use input method when renaming nodes

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#60372]
### Godot version

1d21779

### System information

Arch Linux, GLES 3, Mesa Intel(R) UHD Graphics (CML GT2)

<i>Busquad edit:</i> also presented on Windows (https://github.com/godotengine/godot/issues/62476)

### Issue description

This happens since alpha4. Cannot reproduce on `3.x`.

When renaming nodes in the Scene dock:

* Sometimes, I can't even switch input method on (Ctrl-Space produces a space).
* When input method is on:
    * The IME window sometimes flickers: Everytime I press a key, it shows for a brief moment and seems immediately canceled.
    * The IME window sometimes don't appear at all. All key presses goes directly into the `LineEdit`.

IME works fine in other `LineEdit`s in the editor interface. Renaming animation/library in the Animation Library editor have the same issue. Maybe it's a `Tree` issue?

### Steps to reproduce

1. Create a Node.
2. Double click to rename it.
3. Try to switch IME on (e.g. CTRL-SPACE for fcitx5).
4. Type something when IME is on.

**Comment by timothyqiu** [comment]
Bisected and this behavior is introduced since #58490

CC @bruvzg

**Comment by KoBeWi** [comment]
Not sure if related, but #58490 still has unresolved review comment that is still relevant: https://github.com/godotengine/godot/pull/58490#pullrequestreview-917135673

**Comment by timothyqiu** [comment]
I tried the fix that review comment suggests, this issue is still there.

BTW, I also found that the issue is not reproducible when using single window mode.

**Comment by Rindbee** [comment]
Presumably I enabled **Share the same input method among all applications** in IBus Preferences, so this bug affects me less.

![1](https://user-images.githubusercontent.com/30386067/176119696-3e9b6f53-96d0-40a2-9c39-da1a31f89b6e.gif)

It behaves like the picture above for me most of the time. 

After the problem occurs, click on a external program, and then continue, it is normal.

**Comment by akien-mga** [comment]
Is this still reproducible in the latest 4.0 betas?

**Comment by timothyqiu** [comment]
Still reproducible in 4.0.beta11.

**Comment by bruvzg** [comment]
Should be fixed by https://github.com/godotengine/godot/pull/70052
