### ISSUE TITLE
Deselect multiple nodes by clicking on the current focused node shows solid color

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#60371]
### Godot version

1d21779

### System information

Arch Linux, GLES 3, Mesa Intel(R) UHD Graphics (CML GT2)

### Issue description

![Peek 2022-04-19 19-28](https://user-images.githubusercontent.com/372476/163994764-278dafef-cb35-495f-9356-37cdf56d4a7b.gif)

Clicking on focused node (the node with a border) results in a solid color. Clicking on non-focused node works fine.

On `3.x`, doing this starts renaming the node.

### Steps to reproduce

1. Click node A
2. Control-click node B
3. Click node A again

**Comment by KoBeWi** [comment]
The solid color is the same as clear color. AFAIK renaming opens a LineEdit popup, so it's probably glitching and shows empty Viewport.

**Comment by keptsecret** [comment]
In my testing, it seems it only happens in a very specific case as well. If the node A is below node B and is clicked first, then this doesn't happen. It only happens if node A is above node B.

**Comment by akien-mga** [comment]
Is this still reproducible in the latest 4.0 betas?

**Comment by timothyqiu** [comment]
Seems fixed. It correctly starts renaming the node in beta11.
