### ISSUE TITLE
change Language selection to radio button

### ISSUE THREAD

**Issue by Marqin** [godotengine/godot#6038]
This should use radio button, not checkbox:
![zrzut ekranu 2016-08-04 o 18 35 05](https://cloud.githubusercontent.com/assets/959429/17410091/84393b66-5a72-11e6-95f0-8fd73a85acf1.png)

Because it looks like it's possible to choose multiple languages for one script.

**Comment by Calinou** [comment]
Isn't this a styling issue, ie. replacing the check mark with a dot?

**Comment by vnen** [comment]
@voithos the original issue is about the New Script dialog. But that was solved as well, so this can be closed.
