### ISSUE TITLE
Mouse position does not work in @tool scripts

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#60390]
### Godot version

f4b0c7a

### System information

Windows 10 x64

### Issue description

Attach this script to any Node2D on a scene:
```GDScript
@tool
extends Node2D

func _physics_process(delta: float) -> void:
	print(get_local_mouse_position())
```
Reload scene. It will always print (0, 0).

EDIT:
This is related to the fact that the nodes on scene are inside a SubViewport. I was able to get mouse position from the main viewport and use transform magic to get what I wanted.

### Steps to reproduce

See above.

**Comment by akien-mga** [comment]
Is this still reproducible in the latest 4.0 betas?

**Comment by KoBeWi** [comment]
Yes.

**Comment by FeralBytes** [comment]
@KoBeWi How did you do this: "This is related to the fact that the nodes on scene are inside a SubViewport. I was able to get mouse position from the main viewport and use transform magic to get what I wanted."
Also this also applies if the tool tries for get_global_mouse_position().
Edit I figured it out, I needed to do this:  
```
get_tree().get_root().get_mouse_position()
```

**Comment by KoBeWi** [comment]
`root` is the scene root node.
```GDScript
func get_local_mouse_workaround(root: Node2D) -> Vector2:
	var container: SubViewportContainer = root.get_parent().get_parent()
	var viewport := root.get_viewport()
	var screen_mouse := container.get_local_mouse_position() / viewport.global_canvas_transform.get_scale()
	var translation := viewport.global_canvas_transform.get_origin() / viewport.global_canvas_transform.get_scale()
	return screen_mouse - translation
```
