### ISSUE TITLE
Esc, Delete & Mouse right click did nothing on Godot android.

### ISSUE THREAD

**Issue by MrElfajar** [godotengine/godot#60393]
### Godot version

3.5, 4.0 alpha 6

### System information

Poco x3

### Issue description

Nothing happen when using **Delete** button on keyboard or using  **mouse** **right** **click.**

### Steps to reproduce

- connect mouse & keyboard  bluetooth using OTG
- run Godot

**Comment by Calinou** [comment]
I remember reading somewhere that right mouse button is hardcoded as a back button Android, and only custom ROMs can override this.

**Comment by MrElfajar** [comment]
Yes it's back button by default. But in godot **editor** **mode** it just do nothing, when in **run** mode it acts like **back** again.

**additional info :**
- some keys registered as unknown when adding shortcut binding
- there are apps that can override the behavior of the mouse right click like, VNC Viewer, Exagear Emulator, Pojav Launcher etc.

**Comment by Calinou** [comment]
> But in godot editor mode it just do nothing

The back button is disabled while in the editor to avoid accidentally exiting the editor.
