### ISSUE TITLE
Failed to compile mono project (error MSB3248)

### ISSUE THREAD

**Issue by LuizAntonioPereira** [godotengine/godot#60392]
### Godot version

v3.2.stable.mono

### System information

Windows 10 Pro , GLS2 , RX550

### Issue description

![image](https://user-images.githubusercontent.com/19380442/164217543-8f849d94-b33f-4b1b-be3c-5c3dfccdcfce.png)
Projeto "Godot Space.sln" (Build destino(s)):
	Message: Compilando a configuração de solução "Tools|Any CPU".
	Projeto "Godot Space.csproj" (destinos padrão):
		C:\Program Files\Mono\lib\mono\msbuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(2101,5): error MSB3248: O parâmetro "SearchPaths" tem um valor inválido "D:\Users\Cliente\Documents\GitHub\GodotSpace\.mono\assemblies\Debug\        .winmd". Illegal characters in path. [D:\Users\Cliente\Documents\GitHub\GodotSpace\Godot Space.csproj]
	Projeto de compilação pronto "Godot Space.csproj" -- FALHA.
Projeto de compilação pronto "Godot Space.sln" -- FALHA.

### Steps to reproduce

I created the new project. I have mono installed and visual studio but when I play this error appears.

### Minimal reproduction project

[GodotSpace.zip](https://github.com/godotengine/godot/files/8520940/GodotSpace.zip)

**Comment by rick551a** [comment]
It sounds like a problem with your MSBuild installation.

See: 
https://godotengine.org/qa/68382/issue-with-building-in-mono

and:
https://stackoverflow.com/questions/54438756/how-to-fix-a-visual-studio-build-error-msb3248-parameter-searchpaths-has-in

**Comment by Chaosus** [comment]
cc @neikeq Should be closed?

**Comment by akien-mga** [comment]
Godot 3.2.stable is an old release and not supported anymore. Please upgrade to 3.4.4 or later and make sure that you have either an up-to-date MSBuild from Visual Studio, or (better) dotnet CLI from .NET Core 3.1.
