### ISSUE TITLE
Application crashes at start on Windows 10

### ISSUE THREAD

**Issue by karcel** [godotengine/godot#60399]
### Godot version

Godot Engine v3.2.3.stable.official

### System information

Windows 10

### Issue description

When I download game from https://blinry.itch.io/oh-my-git and upack it I try to run the game. However when started first level right when started typing whole app crashed. Since then any other try to run game again ends in freeze on intro screen.

### Steps to reproduce

1. Download windows package from https://blinry.itch.io/oh-my-git
2. Unpack it.
3. Run oh-my-git application file.
4. Proceed to first level.
5. Start typing   ---- > First crash of the game
6. Restart the game ---- > Another crashes when starting the game

Issue is reproducible even after fresh redownload.

### Minimal reproduction project

None.

**Comment by Calinou** [comment]
Is this your post? https://itch.io/t/2062564/game-doesnt-start-on-windows-10

Please don't report engine issues here before confirming that the issue is not related to the project itself.

**Comment by karcel** [comment]
@Calinou no it's not my post... As a user I do not have a power on engine which is packed in the downloaded zip file - probably README with proper steps how to run the game would be useful then.

**Comment by karcel** [comment]
Shall I Open new one issue when it is still not resolved? It is closed without any resolution.

**Comment by Calinou** [comment]
> Shall I Open new one issue when it is still not resolved? It is closed without any resolution.

No, please use other [community channels](https://godotengine.org/community) for that.
