### ISSUE TITLE
Visual Script editor is too small

### ISSUE THREAD

**Issue by Marqin** [godotengine/godot#6039]
Visual Script editor is too small. There should be an option to get VS editor (that window with graph and those two lists on left) to another window and fullscreen it.

Because it's not a code it cannot be opened in external editor, and Godot has too small window to edit it comfortably.

![zrzut ekranu 2016-08-04 o 18 39 40](https://cloud.githubusercontent.com/assets/959429/17410167/d7b2be5c-5a72-11e6-8755-c373f7fab344.png)

**Comment by reduz** [comment]
Yeah,  I think eventually we should add an option to maximize the central
panel

**Comment by neikeq** [comment]
Yeah. It would be nice to have something like a distraction free mode. Here is my proposal:

- <kbd>Shift</kbd>+<kbd>F11</kbd>: Hide all docks except the central panel.
- <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>F11</kbd>: Hide everything except the central panel.

Please, someone get on that already!

**Comment by reduz** [comment]
I swear I remember seeing a PR for this at some point, but haven' t found
it or seen it again either

On Thu, Aug 4, 2016 at 1:59 PM, Ignacio Etcheverry <notifications@github.com

**Comment by neikeq** [comment]
Trust me, if there was a PR for this I would know.

BTW, the shortcuts I mentioned above seem to be already taken by some strange options in the editor:

![What the hell is this?](https://cloud.githubusercontent.com/assets/7718100/17412603/e7b4701a-5a7d-11e6-8ac2-dbc327952db8.png)

We have to look for a different one :(

**Comment by rgrams** [comment]
Serious sarcasm in here

**Comment by rgrams** [comment]
On a serious note: I used Unreal's Blueprints for a while before moving to Godot. One of the biggest issues was how much space they took up on the screen. I was constantly zooming in and out and panning around, often for things that would be one short line of text code. Hopefully that's considered in the design of Godot's visual scripting.

**Comment by Marqin** [comment]
In UE you can group nodes into groups, I wonder if Godot will have that feature. Also the same with VS->C++ compiler

**Comment by reduz** [comment]
Ah I know I've seen something like this. Maybe we need to add buttons for
this.

Regarding space, Godot splis functions in a graph for each, so that should
help I hope.

**Comment by rgrams** [comment]
@reduz Yeah, splitting each function is good. I'm not sure if it's what Marqin meant, but in UE you could also select any nodes you wanted and group them into a "collapsed graph" which appeared as one node with all the inputs and outputs and a custom title. Then you double-clicked to open it as a graph. 

The worst size difference between text and nodes is with math operations and other common functions that are only 1-3 characters in text, but nodes can only get so small. UE had them as condensed nodes with no title bar, but they weren't actually much smaller. [See here](https://docs.unrealengine.com/latest/images/Support/Builds/ReleaseNotes/2015/4_9/image_40.jpg) . That link also shows the Math node they added to help the problem. You can type in an equation and it automatically adds the right input pins for you. (It's also a collapsed graph that you can open if you want.) That's not the perfect solution either, but it's good when you have one long chunk of math.

**Comment by Marqin** [comment]
Yes this is what I meant with grouping.

**Comment by reduz** [comment]
Ahhh, well, here you can make a function I guess :P

You will be able to make nodes using script (be it c++, gd or visual
itself) so that should hopefully cover it

**Comment by Zylann** [comment]
Don't we have a distraction-free mode already? It maximizes the main view, so I guess it should do the same with the VS editor.

**Comment by reduz** [comment]
We should add visible buttons to it.. pr welcome

**Comment by vnen** [comment]
The shortcuts @neikeq mentioned works on the script editor, so they already work on the visual script editor too.

**Comment by ScotFlux** [comment]
Yes, Distraction Free Mode and Fullscreen Mode already in Godot. If any of you watched my recent video on Facebook, you should have already saw I'm playing with those features. But, until now Editor Settings --> Shortcuts has a bug, as it following Scene Undo-Redo System. Instead, Shortcuts must be independent from Scene Undo-Redo System. Unfortunately, my reported issue ( #6014  ) flagged as Enhancement instead of Bug. But, I could be wrong though. haha :laughing: lol

**Comment by mercurysama** [comment]
We can't use a fullscreen mode, because We use Visual Scrip tab with the inspector...

**Comment by reduz** [comment]
Ah, good point, you need the docks to use visual script properly.
One idea I had was to move the list of opened scripts to a dock to save
space, not sure how useful that would be,

**Comment by Zylann** [comment]
@reduz I agree with that, there are docks (or containers) I completely never use when scripting. This makes me think about this issue https://github.com/godotengine/godot/issues/5473

**Comment by toger5** [comment]
just found that issue.
there is distraction free now.
So we can close

**Comment by reduz** [comment]
Not only that, the list of scripts open and visual script panel share
layout, so they use a lot less space.
