### ISSUE TITLE
Moving resource renames dependents to *.depren

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot#60412]
### Godot version

v4.0.alpha.custom_build [f4b0c7a1e]

### System information

Arch Linux 5.15.34-1-lts

### Issue description

Note that the scene and script were not open.

![2022-04-21 12-55-23](https://user-images.githubusercontent.com/14253836/164521850-e8bae105-8ea6-4cf7-b200-60a7b04a7e7e.gif)

### Steps to reproduce

1) Move the script to a different directory or move the entire directory

### Minimal reproduction project

[test1.zip](https://github.com/godotengine/godot/files/8533553/test1.zip)

**Comment by Calinou** [comment]
Can you reproduce this on 3.4.4?

**Comment by nathanfranke** [comment]
Cannot reproduce in 3.4.4 nor 3.5.beta4

**Comment by markdibarry** [comment]
This still seems to be happening on alpha 7.

**Comment by Calinou** [comment]
cc @timothyqiu

**Comment by timothyqiu** [comment]
@markdibarry Can you provide some instructions on how to reproduce it? The steps in OP works fine for me.

**Comment by markdibarry** [comment]
I haven't delved into a new project to make a minimal reproduction, but here's a project with a build off of `cbdc33b`.
In this case, `MetalHockeyStick.tscn` is an inherited scene from `HockeyStick.tscn`.



https://user-images.githubusercontent.com/21325943/166110068-36f05e8d-2626-4fa5-9636-950a459d6d07.mp4

**Comment by markdibarry** [comment]
Built from a commit yesterday, and still having the issue. Created a minimal repro:
[Depren_bug.zip](https://github.com/godotengine/godot/files/8599057/Depren_bug.zip)

**Comment by timothyqiu** [comment]
I am unable to reproduce the extra `.depren` file with the MRP on Arch Linux. Maybe only reproducible on Windows? (I don't have access to a Windows machine right now, so I am not sure.)

**Comment by markdibarry** [comment]
I am on a Windows machine, so that may be the case.

**Comment by nathanfranke** [comment]
I cannot reproduce on Arch (same setup as original post)

**Comment by markdibarry** [comment]
Did a fresh build this morning on another Windows machine, and MRP still has the issue, so I guess we can confirm it's Windows (not sure about Mac) specific.

**Comment by akien-mga** [comment]
CC @godotengine/windows

**Comment by bruvzg** [comment]
Seems like `ResourceLoaderText` is holding multiple references to the source file, and one `unref` is not enough (before making FileAccess/DirAccess ref. counted, `close` call was leaving a bunch of invalid file access handles).
