### ISSUE TITLE
Area2d collision too soon (inaccurate) when scaled

### ISSUE THREAD

**Issue by Sp3ci3s8472** [godotengine/godot#60417]
### Godot version

3.4.2-stable and 3.4.4-stable

### System information

Windows 10

### Issue description

I'm having problems with collisions when the Area2D node is scaled to accommodate for the shape of a "shield" and "projectile", both having an elliptic appearance. In my case the scale of the area2D node is something in the range of 0.7,0.3.
On the axes where the ellipsoid is smallest collisions happen too soon; on the axes where the ellipsoid is biggest the collisions register correctly. When I set the scale of my area2D node to 1,1 collisions are working as expected.

My setup is as follows, two times the following node setups
Area2d with childs:
Sprite
CollisionShape2D (Sphere)

To make sure everything was setup correctly I ran my game with visible collision shapes (--debug-collisions). See screenshot included where a breakpoint is triggered at moment of "impact".
![image](https://user-images.githubusercontent.com/11257250/164556084-f288f577-cb65-43b3-919f-470dd4c4d04b.png)

Notice that the shapes are drawn correctly

I use the mono version of Godot in combination with C#, but it doesn't matter if I start in Rider or Godot itself.

### Steps to reproduce

Have a scene with 2 area2D nodes that are shaped like a spheroid. Test the collisions.
Set a breakpoint to check for the collision.

### Minimal reproduction project

[Area2dBugTest.zip](https://github.com/godotengine/godot/files/8535366/Area2dBugTest.zip)

**Comment by Calinou** [comment]
Scaling collision shapes is not supported, especially in a non-uniform manner. Use a CollisionPolygon with the shape of an ellipse instead.

**Comment by Sp3ci3s8472** [comment]
> 

Will they be supported in Godot 4?
Can a CollisionPolygon be scaled in a non-uniform manner?
Can a CollisionPolygon be scaled in a uniform manner?

If all are no, then I probably will create my own collision system without those limits. Since I need these shapes to be defined at runtime, creating them beforehand is not possible. 
If the last one can be done I might be able to create a CollisionPolygon with a formula at runtime given a certain scale ratio, I need some time to figure that out.
As you might have seen in my project, I only have a Main node (which is a node). In my game the rest of the things are either loaded from textfiles or are procedural.

**Comment by Calinou** [comment]
> Will they be supported in Godot 4?

Probably not, unless a contributor does the required job.

> Can a CollisionPolygon be scaled in a non-uniform manner?
> Can a CollisionPolygon be scaled in a uniform manner?

No, as CollisionPolygon is just a helper that generates CollisionShapes.

**Comment by Sp3ci3s8472** [comment]
> Probably not, unless a contributor does the required job.
Well perhaps some day, Sadly I'm not well versed in C (yet) and I first want to finish my project. 
> You can create CollisionPolygons at run-time too with a script 🙂
Cool, I will use that!
