### ISSUE TITLE
Input.parse_input_event() doesn't generate Node._input calls when called from Node._input (4.0)

### ISSUE THREAD

**Issue by Lielay9** [godotengine/godot#60416]
### Godot version

4.0 Alpha 6

### System information

Windows 10, Vulkan, Nvidia 1050TI

### Issue description

Input.parse_input_event() doesn't generate Node._input calls when called from Node._input, unlike in 3.x. When called outside of Node._input, the calls are generated as expected. 

If this is a new limitation, it should be documented in the Input.parse_input_event() -description which currently reads:

_Feeds an [InputEvent](https://docs.godotengine.org/en/latest/classes/class_inputevent.html#class-inputevent) to the game. Can be used to artificially trigger input events from code. Also generates [Node._input](https://docs.godotengine.org/en/latest/classes/class_node.html#class-node-method-input) calls._

### Steps to reproduce

```
extends Node

func _input(event):
	if event.is_action("ui_cancel"):
		var action : = InputEventAction.new()
		action.action = "ui_accept"
		action.pressed = event.is_pressed()
		# Works in 3.x
		Input.parse_input_event(action)
		# Works in 3.x and 4.0
		Input.call_deferred("parse_input_event", action) 
		
	if event.is_action_pressed("ui_accept"):
		print(event)
```

**Comment by Sauermann** [comment]
I was able to reproduce this issue on Windows, but was unable to reproduce this on Linux Debian Xfce X11. (Tested with Alpha 6)

**Comment by Lielay9** [comment]
Not sure what changed but this doesn't seem to be a problem in Alpha 13([59dcddc45]) anymore. I don't have a Mac to test whether this issue is/was present there but since it works on Windows (and Linux wasn't having issues) I'll close.

**Comment by shanayyy** [comment]
> Not sure what changed but this doesn't seem to be a problem in Alpha 13([59dcddc45]) anymore. I don't have a Mac to test whether this issue is/was present there but since it works on Windows (and Linux wasn't having issues) I'll close.
I have the same issue
Godot v4.3.beta2 - macOS 14.5.0 - GLES3 (Compatibility) - Apple M2 Pro - Apple M2 Pro (10 Threads)

**Comment by Lielay9** [comment]
> > Not sure what changed but this doesn't seem to be a problem in Alpha 13([59dcddc45]) anymore. I don't have a Mac to test whether this issue is/was present there but since it works on Windows (and Linux wasn't having issues) I'll close.
> 
> I have the same issue Godot v4.3.beta2 - macOS 14.5.0 - GLES3 (Compatibility) - Apple M2 Pro - Apple M2 Pro (10 Threads)

I'm still unable to reproduce in Windows in the v4.3.beta2.official [b75f0485b].

I'll recommend you to open a new issue with the specifics of the issues you're facing.
