### ISSUE TITLE
Shaders wont compile in 3d

### ISSUE THREAD

**Issue by PSVita-Dev** [godotengine/godot#60428]
### Godot version

3.3.stable

### System information

vita,GLES2, PowerVR SGX543MP4+

### Issue description

i have been trying to run my 3d godot game on the sony playstation vita (https://github.com/SonicMastr/godot) .
unfortunately the scene shader fails to compile 
this only happens in a 3d scene. 2d works
![Screenshot_20220422_130333](https://user-images.githubusercontent.com/80003809/164702702-84b482a7-bb63-4a5c-b168-8906f820bc51.png)
.

### Steps to reproduce

try to run any 3d game on the vita

**Comment by Calinou** [comment]
The Vita port is a third-party port, and is not maintained by the Godot developers. Please report issues related to this port to the port's author, not us.
