### ISSUE TITLE
Material sphere and mesh preview may be displayed at the same time in the Advanced Import Settings dialog

### ISSUE THREAD

**Issue by njdf18** [godotengine/godot#60425]
### Godot version

v4.0.alpha6.official / v4.0.alpha.mono.custom_build

### System information

Windows11, Vulkan, NVIDIA GT 1050 Ti

### Issue description

If you select a material to view and close the window straight, the material sphere and the model will be displayed at the same time.
(Sorry for my poor English)

![godotBug2](https://user-images.githubusercontent.com/86307226/164688575-954681ba-8a34-4b20-bdb3-7b96b07fd8f9.gif)

### Steps to reproduce

1. Import any 3D model that has material
2. Open Advanced Settings window
3. Select a material and close the window straight
4. Open it again

### Minimal reproduction project

[Squash the Creeps.zip](https://github.com/godotengine/godot/files/8539925/Squash.the.Creeps.zip)

**Comment by MightiestGoat** [comment]
Fixed it https://github.com/godotengine/godot/pull/60674/commits
