### ISSUE TITLE
Plugin EditorProperty, call method failed

### ISSUE THREAD

**Issue by ValentinChCloud** [godotengine/godot#60429]
### Godot version

3.4.2.stable

### System information

Windows 10, OpenGL ES 3.0 Renderer

### Issue description

My custom plugin check if object is type `my_audio_res` (custom class_name). If true, it adds a button. When button clicked it call a custom method in object `play()`, to play the audiostream,
But it fails, even if `object.has_method("play") ==> true`

I tested, I can call native method from Resource/Reference/Object.  like `get_rid() ` but not custom one.

### Steps to reproduce

I'm trying to add a button in inspector when object is `my_audio_res` (custom class_name) is true.
(This is basicaly what is done in the presentation: 
[Overthrowing the MonoBehaviour Tyranny in a Glorious Scriptable Object Revolution by Richard Fine]( https://www.youtube.com/watch?v=6vmRwLYWNRo) time code 37:00)

I'm using information from [inspector plugin tutorial ](https://docs.godotengine.org/en/stable/tutorials/plugins/editor/inspector_plugins.html) to create custom plugin

1 - Create custom resource script and create a new ressource 
```
extends Resource

class_name my_audio_res

export(AudioStream) var audio

func play(audiosource):
	audiosource.stream = audio
	audiosource.play()
```

2 - Custom plugin
Mostly the same as in tutorial execpt  the `EditorProperty`

```
extends EditorProperty

var property_control = Button.new()
var audiostream = AudioStreamPlayer.new()

func _init():
	# Add the control as a direct child of EditorProperty node.
	add_child(property_control)
	add_child(audiostream)
	# Make sure the control is able to retain the focus.
	add_focusable(property_control)
	
	# Setup the initial state and connect to the signal to track changes.
	property_control.text = "Preview"
	property_control.connect("pressed", self, "_on_button_pressed")

func _on_button_pressed():
	# Ignore the signal if the property is currently being updated.
	if (updating):
		return
	play_sound()

func play_sound():
	
	#DEBUG BLOCK
	print("Object has method 'play' : ",get_edited_object().has_method("play")) # True, can acces method
	print("Object has var 'audio' : ", get_edited_object().audio) #True, can acces var members 
	#
	get_edited_object().play(audiostream) #Failed,invalid call, nonexistent function play 
```
3 - `Invalid call. Nonexistent function 'play' in base 'Resource (audio_resource.gd)'.`

![godot_issue](https://user-images.githubusercontent.com/26431997/164708148-7e74e3e3-7f63-487c-a959-7e3ae7a8ee62.png)

### Minimal reproduction project

[bug_object_editor.zip](https://github.com/godotengine/godot/files/8540509/bug_object_editor.zip)

Select ` example_audio_play.tres` in editor, a button appears on top of audio.

**Comment by ValentinChCloud** [comment]
My bad, I don't think this is an issue.

**Comment by Zireael07** [comment]
Your resource needs to be a tool script to work in editor. This is true for plugins, too.
