### ISSUE TITLE
Add a "deselected" signal to ItemList

### ISSUE THREAD

**Issue by DimitriyPS** [godotengine/godot#6044]
**OS All, Godot 2.1:**

I want to offer a small improvement ItemList.
In some cases, it would be great to get the ItemList from the signal in the case of full of disable the selection of its Items.

**Comment by eska014** [comment]
I don't understand what you mean by "signal in the case of full of disable the selection of its Items".
Do you want a new signal? Or a new argument for an existing signal?

You can bind the ItemList (or any other variable) to a connection, so it's always passed as an argument:

```
func test():
    var itemlist =  get_node('ItemList')
    itemlist.connect( 'item_selected', self, 'connected_function', [itemlist] )

func connected_function( item_index, itemlist ):
    itemlist.some_function()
```

**Comment by DimitriyPS** [comment]
I will prepare soon a simple example on GDScript.

**Comment by DimitriyPS** [comment]
It would be nice to have Itemlist a new signal: when selection is deactivated the items.

I have prepared a small demo showing this signal.
[DEMO.zip](https://github.com/godotengine/godot/files/417641/DEMO.zip)

**Comment by bojidar-bg** [comment]
Ah, finally got it... so, you want a signal for no selection XD. Next time speak English.

A good name for this might be `item_deselected` probably, though I'm not sure about this.

**Comment by DimitriyPS** [comment]
>> Next time speak English.

Sorry ... I try as best I can.

**Comment by AlexHolly** [comment]
I can't see a way to force a selection, so that it is not possible to deselect and have no selection at all.
I think with this signal my issue can be solved.

So `item_deselected(item)` needs to be fired after `item_selected` OR maybe it also has a next parameter like this? `item_deselected(old_item, new_selection)` so that I can check `new_selection==null`

Any other ideas?

**Comment by DimitriyPS** [comment]
Yes, in Godot 3 it is not true. Can be closed.
