### ISSUE TITLE
the return value of Vector2.angle_to_point is not correct in godot 3.x

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#60453]
### Godot version

3.x

### System information

Mac OS

### Issue description

in godot 4
printt(Vector2.ZERO.angle_to_point(Vector2.ONE))
0.78539818525314

in godot 3.4.4
printt("3.x", Vector2.ZERO.angle_to_point(Vector2.ONE))
3.x	-2.356194

according to this image

https://raw.githubusercontent.com/godotengine/godot-docs/master/img/vector2_angle_to_point.png
the result return in godot 4 is as expected.

### Steps to reproduce

just run
printt(Vector2.ZERO.angle_to_point(Vector2.ONE))

**Comment by Chaosus** [comment]
This is different because the order has been reversed: https://github.com/godotengine/godot/pull/43072. I don't think back porting this to 3.x is a good idea - it may break a lot of user code.

**Comment by timothyqiu** [comment]
> according to this image
> 
> https://raw.githubusercontent.com/godotengine/godot-docs/master/img/vector2_angle_to_point.png the result return in godot 4 is as expected.

The image is updated for 4.0 in  https://github.com/godotengine/godot-docs/commit/65345e94ee73d11918109120e4ea9ecfab02fcf8. Maybe the documentation should link to the corresponding one.

**Comment by towai** [comment]
yeah, this threw me for a little loop when i was just now reviewing someone else's code and found that the actual return value was different than expected based on the image that the in-editor doc linked to for reference. backporting would be a wrong move, but the 3.x doc definitely needs to link to the old image.

**Comment by Calinou** [comment]
The image was updated in https://github.com/godotengine/godot-docs/pull/5777, but the class reference link still needs to be updated by opening a pull request against this repository's `3.x` branch.

**Comment by towai** [comment]
> The image was updated in [godotengine/godot-docs#5777](https://github.com/godotengine/godot-docs/pull/5777), but the class reference link still needs to be updated by opening a pull request against this repository's `3.x` branch.

should this be done to the xml file in `godot/3.4` or is this a case where editing the .rst directly is fine/preferable? i'm looking at both right now and could change either just as easily.

**Comment by Calinou** [comment]
> > The image was updated in [godotengine/godot-docs#5777](https://github.com/godotengine/godot-docs/pull/5777), but the class reference link still needs to be updated by opening a pull request against this repository's `3.x` branch.
> 
> should this be done to the xml file in `godot/3.4` or is this a case where editing the .rst directly is fine/preferable? i'm looking at both right now and could change either just as easily.

The XML file in godotengine/godot should be edited, as the rST file in godotengine/godot-docs is automatically generated from the XML file.

Pull requests against the stable branch should be opened against the `3.x` branch, not `3.4`. We can cherry-pick what's applicable to `3.4` after the pull request was merged in `3.x`.

**Comment by towai** [comment]
> Pull requests against the stable branch should be opened against the `3.x` branch, not `3.4`. We can cherry-pick what's applicable to `3.4` after the pull request was merged in `3.x`.

My bad, somehow I just straight up didn't see that branch in the list when I glanced at it at first. Created #60573 on 3.x

**Comment by akien-mga** [comment]
Fixed by #60573.
