### ISSUE TITLE
No audio in HTML5

### ISSUE THREAD

**Issue by manglemix** [godotengine/godot#60455]
### Godot version

3.4.4

### System information

HTML5

### Issue description

My game has a simple music player autoload
I have verified that this does in fact work when debugging in the editor, but when debugging in browser, there is no audio.
In my export presets, I have PWA enabled, and export type as regular instead of threads. This is because Threads does not seem to work for iOS when ran from itch.io. Regardless, I have also verified that Threads does not work as well. I am fairly certain that the songs are in that path, because I do not restrict what files are exported, and the loading of the game takes longer than usual.

### Steps to reproduce

A link to my game is here https://manglemix.itch.io/bolatest

The code for the autoload is:
```
extends AudioStreamPlayer


const SONG_FOLDER := "res://songs/"

var songs := []
var song_index := 0


func _ready():
	var dir := Directory.new()
	if dir.open(SONG_FOLDER) != OK:
		return
	if dir.list_dir_begin(true) != OK:
		return
	
	var song_name := dir.get_next()
	while not song_name.empty():
		if song_name.ends_with(".import"):
			song_name = dir.get_next()
			continue
		var song = load(SONG_FOLDER + song_name)
		if not song is AudioStream:
			push_error(song_name + " is not an audio file!")
			song_name = dir.get_next()
			continue
		songs.append(song)
		song_name = dir.get_next()
	
	songs.shuffle()
	stream = songs[0]
	song_index = 1
	play()
	# warning-ignore:return_value_discarded
	connect("finished", self, "_on_finished")


func _on_finished():
	song_index += 1
	if songs.size() == song_index:
		song_index = 1
		songs.shuffle()
		stream = songs[0]
		return
	stream = songs[song_index]
	play()
```

**Comment by Calinou** [comment]
Does it work if you statically assign a music file to your AudioStreamPlayer autoload (e.g. using `stream = preload("res://path/to/song.ogg")`?

**Comment by manglemix** [comment]
> Does it work if you statically assign a music file to your AudioStreamPlayer autoload (e.g. using `stream = preload("res://path/to/song.ogg")`? The run-time file choosing logic may not work in an exported project (even outside of HTML5).

Yes preloading like this those work. This is my bad, I didn't realize that this was an issue

**Comment by asperkraken** [comment]
You may also check if Silent Mode on your iOS device is on. This disables sound by default on itch.io launches on Safari.
