### ISSUE TITLE
Help importing an image the way it appears when designed in software like Inkscape

### ISSUE THREAD

**Issue by ajk2196** [godotengine/godot#60461]
### Godot version

v3.4.2.stable.official [45eaa2daf]

### System information

Windows 10, 2 X RTX 2070 Super, AMD 3700X

### Issue description

Hi, I have been trying to learn UI and UX and have taken the project to make a calculator app for Android phone (Redmi Poco F1). I am facing a serious issue that I haven't been able to solve for three days now, and hence, I have lost all my hopes and am finally posting it here since this is the last hub I think that should solve my problem. If it does not get solved here, then I most probably will have to close this project and will never look back at Godot ever again. Anyways, here goes my problem:

I have been trying to import an image to use as a texture for a button. I have attached the screenshot below.
![screenshot](https://user-images.githubusercontent.com/90527174/164892320-4189e129-b132-4a21-9e1f-d75d8f878241.png)
If you open up this screenshot (zoom in the image), you will see that none of the image textures are perfect as they should be. For instance, have a look at the 'Converter' button in the screenshot, the letters are badly distorted. Here is the converter button image that I am trying to use (its an original one). (All images are raster, just like this Converter button below, but are perfect when viewed in default photos and image viewer of Microsoft.)
![convbutton](https://user-images.githubusercontent.com/90527174/164892380-5889b69e-a153-4726-97c2-1bc861de9884.png)
Not only this one, the Degree and Radian button are also badly distorted, you can zoom into the screenshot and see it. I am attaching the Degree buttons image here. The actual button is so badly distorted that both 'e's at the end of degree are not even identical.
![Degrees](https://user-images.githubusercontent.com/90527174/164892674-d3432d08-8263-43ae-8840-a013249d5bd6.png)
As you can see, the image above is so clear and well anti-aliased, its hard to notice any artifacts. The 'Degree', 'Radian', 'Playstore' and many more buttons in the actual app are distorted - you can check by zooming in the screenshot. I have tried all advices available online to import them with clear and non-distorted edges, but none of those methods could give me a non-distorted button.

This was the case with raster images. Now lets come to the fonts - which definitely are something like vector graphic. In the screenshot, the calculation query and answer are fonts - which too are badly anti-aliased. Tried everything with them as well - but only found disappointment in the end.

I kindly request you to please help me find a solution to these problems. Please point me where I am wrong. If you could demonstrate how to use these texture in a way that they appear in the app exactly as they do generally, it would be really helpful. The window screen size that I am using for this app is 1000x500 pixels. I have anti-aliasing turned on. Let me know if you want to know about further settings.

[NOTE: THE BUTTON IMAGES ARE PURELY WHITE, THEREFORE THEY ARE NOT APPEARING WHERE I HAVE MENTIONED THEM AS GITHUB TOO HAS A WHITE BACKGROUND. IF YOU PLACE THE CURSOR IN THE EMPTY SPACE, IT WILL TURN INTO A HAND AND THEN YOU CAN RIGHT CLICK, SAVE THE IMAGE AND VIEW IT LOCALLY. THERE ARE TOTAL THREE IMAGES IN THIS ISSUE. OR YOU COULD OPEN UP DEVELOPER TOOLS AND CHANGE THE GITHUB'S BACKGROUND COLOUR TO MAKE THE REMAINING IMAGES VISIBLE.]

The pure white areas in the image below are resource images of my app (Coverter and Degree). Right click on them to download the images.
![Screenshot (243)](https://user-images.githubusercontent.com/90527174/164893327-83e03113-1f90-40bd-b177-7d13a79c2e8e.png)

### Steps to reproduce

Must be tried in an Android device (phone). Add a texture rect or a button, add one of the images above as its texture and play on Android phone.

**Comment by Calinou** [comment]
Try enabling **Allow Hidpi** in the Project Settings, then export the project for Android again.

**Comment by ajk2196** [comment]
You are a wizard of Godot, Calinuo! Thanks a lot. I was really not expecting the problem to get solved this fast! I did not tell you my  stretch mode settings, yet you guessed them to be absolutely correct. This entire thing was almost like you threw a dart in the darkness and hit the target. Your settings have improved the quality, however, minor pixel distortion still remains that is noticeable when paid attention to and only when animation is played because the animated sprites consist of shadows. 

This should be closed now, but the issue is that this type of pixel distortion problem persists for graphics of smaller size. The fonts with smaller size are performing well with the settings you have suggested (I just tried them), however, the small-sized graphics are still getting either blurred or pixel-distorted - depending on their import settings. The font size I used for this was '9'. The small sized graphics are not performing to have the same clarity as small-sized fonts.

**Comment by Calinou** [comment]
> The fonts with smaller size are performing well with the settings you have suggested (I just tried them), however, the small-sized graphics are still getting either blurred or pixel-distorted - depending on their import settings.

There is no way to completely avoid this. You simply can't render something on screen in a clean manner if it has to be downsized. It either has to be blurry (when mipmaps are enabled) or grainy (when mipmaps are disabled).

**Comment by ajk2196** [comment]
Ok. Then I think that this matter is solved.
