### ISSUE TITLE
low_processor_mode black screen on android when switching back to app

### ISSUE THREAD

**Issue by Nazzaroth2** [godotengine/godot#60465]
### Godot version

3.5.beta4

### System information

Android 12, GLES3, Samsung Galaxy S10+, Android SDK 31

### Issue description

What happens:
When switching between android apps, or when minimizing all apps and reopening the godo-app the screen stays black. When a touch-sensitive object is on the screen, a new press on the screen refreshes and show the app-content again.

What should happen:
When switching back to the app the content should show up right away.

Additional Info:
As far as i have a recollection of these issues, this bug was also present before, just as the flickering issues. Those got fixed in the new beta-releases.
Before i made a custom build of godot with the forced-frame-redraw fix (sadly i can't remember what thread it was). That custom build did not have the black-screen issue the official beta-builds have.

### Steps to reproduce

Using low_proccessor_mode in 3.5beta4 and exporting to android. Then switching to another app and back to godot-app.

**Comment by Calinou** [comment]
This should have been fixed by https://github.com/godotengine/godot/pull/59606, but it wasn't fully fixed.

**Comment by Nazzaroth2** [comment]
alright, i played around a little bit more and found a workaround for this problem. If anyone needs a quick fix until the bug is correctly fixed try this:

depending on your setup either add a control-node that never gets deleted or make an autoloaded control node.
Then add this code to the node:
```
func _notification(what):
	if what == MainLoop.NOTIFICATION_WM_FOCUS_IN:
		if visible:
			self.hide()
		else:
			self.show()
```
This will toggle the visibility of the controlnode every time the app gets focused again, forcing a frame refresh (i guess?) and thus making sure the app gets shown immediatley.
