### ISSUE TITLE
Vulkan: `get_image()` of main Viewport is full black

### ISSUE THREAD

**Issue by abochar** [godotengine/godot#60476]
### Godot version

v4.0.alpha6.official [e4f0fc50f]

### System information

Windows 11, Vulkan, Nvidia 3080Ti (511.79)

### Issue description

I am trying to get main viewport image, but it is full black (0,0,0,1)

![image](https://user-images.githubusercontent.com/35319858/164916437-336c6614-a1c3-4fc1-aae1-773a1d7ecd1e.png)

![image](https://user-images.githubusercontent.com/35319858/164916522-6efe0b6d-65e5-4aac-878f-17a777ec6e8f.png)

### Steps to reproduce

Get main Viewport image and save it to png or get_pixel()

### Minimal reproduction project

[Viewport Bug.zip](https://github.com/godotengine/godot/files/8547678/Viewport.Bug.zip)

**Comment by KoBeWi** [comment]
You are trying to get the texture before anything is initialized. It's recommended to wait at least 2 frames before trying to acquire texture from a newly created viewport. Just add this at the beginning of your method:
```GDScript
await get_tree().process_frame
await get_tree().process_frame
```
I think we should have this documented.

**Comment by Haledire** [comment]
This seems like something you typically cover with waiting for the RenderingServer (formerly VisualServer) and getting the resulting image after `frame_post_draw` emits:

```
await RenderingServer.frame_post_draw
```
vs 3.x
```
yield(VisualServer, "frame_post_draw")
```

ie: doing this results in getting the viewport image just fine
```
func _ready():
	await RenderingServer.frame_post_draw
	var vpimg = get_viewport().get_texture().get_image().save_png("res://vptest.png")
```
![image](https://user-images.githubusercontent.com/164616/164951265-b8fcffa9-a220-4d54-b77c-7bf01f97069e.png)

**Comment by abochar** [comment]
@KoBeWi , @Haledire Thank You! About `await RenderingServer.frame_post_draw` and `await get_tree().process_frame`,  does it pause app or only node when waiting?

**Comment by KoBeWi** [comment]
It only pauses the method that called it.
