### ISSUE TITLE
grab_focus stopped working without call_deferred

### ISSUE THREAD

**Issue by ArcFutahito** [godotengine/godot#6048]
godot alpha 2.2 (5 aug build) linux x86

When I switched to new build (from 2.1 alpha), grab_focus stopped working everywhere. Script snippet: 

Conditions are satisfied (checked with print). Grab_focus refuses to work without doing call_deferred. With call_deferred grab_focus works. 
`func grab():`
` get_node("BattleMenu/VBoxContainer/Attack").grab_focus()`
`if (event.is_action_released("ui_accept") && !event.is_echo() && state == 'Idle'):`
` get_node("Main Menu").set_disabled(true)`
` battle.play("popup")`
` if get_node("BattleMenu/VBoxContainer/Attack").get("disabled") == false:`
`  print("blerb")`
`  call_deferred('grab')`
` elif get_node("BattleMenu/VBoxContainer/Magic").get("disabled") == false:`
`  get_node("BattleMenu/VBoxContainer/Magic").grab_focus()`
` elif get_node("BattleMenu/VBoxContainer/Special").get("disabled") == false:`
`  get_node("BattleMenu/VBoxContainer/Special").grab_focus()`
` elif get_node("BattleMenu/VBoxContainer/Items").get("disabled") == false:`
`  get_node("BattleMenu/VBoxContainer/Items").grab_focus()`
` get_tree().set_pause(true)`
` state 			= 'BattleMenu'`

**Comment by reduz** [comment]
I don't think I understand this much, but there can be only one control
with focus at the same time..

also get("disabled") and .disabled is the same

**Comment by ArcFutahito** [comment]
@reduz Well, yeah, I know that. I check for each button and if it's active I grab focus (that's why elif). 
The thing is, grab_focus doesn't work unless you make a separate function and do it through call_deferred

**Comment by Hinsbart** [comment]
@ArcFutahito could you provide a simple test-case project for this?
I can't seem to be able to reproduce this.

**Comment by eska014** [comment]
On Github, use 4 spaces in front of multiple lines of code to retain indentation.

Looks to me like you accidentally call your own function `grab()` instead of `grab_focus()` for `"BattleMenu/VBoxContainer/Attack"`. So instead of:

    if get_node("BattleMenu/VBoxContainer/Attack").get("disabled") == false:
    	call_deferred('grab')

try:

    if get_node("BattleMenu/VBoxContainer/Attack").get("disabled") == false:
    	get_node("BattleMenu/VBoxContainer/Attack").grab_focus()

**Comment by ArcFutahito** [comment]
@eska014, I agree with bojidar_bg. Just no. Don't.
@Hinsbart yeah, making one

**Comment by ArcFutahito** [comment]
[Test.tar.gz](https://github.com/godotengine/godot/files/404392/Test.tar.gz)
@Hinsbart @reduz here's a test project

**Comment by eska014** [comment]
A Control node that is not visible (i.e. itself or one of its parent has `is_hidden() == true`) cannot grab focus.
In this case, the `"BattleMenu"` node is hidden when `grab_focus()` is called on its child `"VBoxContainer/Attack"`.

The `"popup"` animation sets visibility to true, but the animation only starts playing later, in idle time.

So, before `grab_focus()`, call `get_node("BattleMenu").show()`, or maybe better, modify only `opacity` and leave `visibility` as `true`.

====

This is not the only node where hiding causes the node to also be disabled in other ways. Maybe we should move away from the `visiblity` idea completely and refactor this property and related methods to say `enabled` and `disabled` or such instead. A case for #5696, this property is already notorious anyway.

**Comment by ArcFutahito** [comment]
Wow, I didn't know that. Ok that sounds fair (still I wonder why 2.1 alpha is ok with grabbing focus and 2.2. alpha is not, but oh well). 
I guess I'm closing this issue?

**Comment by eska014** [comment]
This was changed in 3185ce64c5c27c3ce7c4ce755bfc890bac172f04 to fix #5354.
The change makes sense, but as I said, it's unexpected for a property called visibility to have so much impact on game flow. If anyone wants to opine on this, use the Refactoring issue linked above.

closing this as you suggested

**Comment by reduz** [comment]
It was actually a bug that was fixed
