### ISSUE TITLE
Admob Plugin crashing the Android export APK + Localize implementation of all monetizing methods directly into Godot Core Framework.

### ISSUE THREAD

**Issue by ajk2196** [godotengine/godot#60494]
### Godot version

3.4.4 Stable

### System information

Windows 10, 2 X RTX 2070 Super, AMD 3700X

### Issue description

Firstly, Please don't mark this off as to be posted in Godot-Admob's github page, for I think that monetization should be something that must be focussed on. All of us love our hobbies, for most Godot users, it is making games - and imagine being able to earn from our hobbies even a tad-bit of amount - it would be like a dream come true. Therefore, I think that all monetization methods must be implemented directly into Godot core framework and must be maintained with every release. Godot is far from being industry standard atleast for now, but having a well supported monetization framework and ease of its implementation will definitely attract young/new generation of enthusiasts who want to get into making games. Not only that, it would be a demonstration of how easy it is working with Godot - just like having a gaming-dedicated coding language (GDScript). Everyone does a good deal of research before choosing a game engine - and coming across problems like not being able to monetize; or being extremely difficult to implement monetization methods will be a big turn off and drive away a good deal of learners.

Now coming to my problem, what I am facing is that I am placing all the folders and files of Admob Plugin as explained. Now when I export the app, it runs well. At this point, just the plugin folders have been placed, the 'Use Custom Build' and 'Godot Admob' are disabled in Export Settings. Now, when in the export settings, if I just enable the 'Use Custom Build' and 'Godot Admob', then export the app and run it, it crashes in Android phone, while runs perfectly when testing on PC. I don't even get to see the splash screen in Android phone. **Note that at this point, I haven't even added the Admob node anywhere in the scene.** There is some problem caused after enabling the 'Use Custom Build' and 'Godot Admob' that is causing the crash. It is hard to say whats the problem. I tried adblogcat after looking online, but really couldn't get anything as I have not used it before and don't know how to detect whats causing the problem.

### Steps to reproduce

Download the Admob plugin from here: [Admob Plugin](https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/releases/tag/v5.1.0)

This tutorial has been referenced on the plugin page to follow in order to successfully implement the Godot Admob Plugin: [Youtube Video](https://youtu.be/0a6EvlNgLL0). Page reference: [Here](https://github.com/Shin-NiL/Godot-Android-Admob-Plugin)

Add a blank scene, copy paste the folders and files as explained in the video, go to export settings and enable 'Use Custom Build' and 'Godot Admob' and then export the APK. Run the APK in Android phone, the crash should happen.

**Comment by Calinou** [comment]
Please don't ask support questions here, as this issue tracker is meant to be used for bug reports only. Use one of the other [community channels](https://godotengine.org/community) instead.

Also, feature proposals should be made on the Godot proposals repository. However, there are no plans to officially integrate ad SDKs in Godot core since they're usually under proprietary licenses.
