### ISSUE TITLE
Scene Loads Improperly In-game

### ISSUE THREAD

**Issue by imapiratemon** [godotengine/godot#605]
Here's the forum post: 
http://www.godotengine.org/forum/viewtopic.php?f=11&t=786&p=3665#p3665

Basically playing the scene from the editor runs perfectly fine, but if I run my menu screen scene first then from the menu screen I load up the same scene the framerate is unbearable and at least one script just doesn't function anymore. Thanks!

**Comment by akien-mga** [comment]
As the link is dead due to forum move, and the issue in itself has very little details regarding what the problem was, let's archive this one.
