### ISSUE TITLE
Cursor hidden after dragging an EditorSpinSlider in the inspector (DisplayServer regression)

### ISSUE THREAD

**Issue by action-script** [godotengine/godot#60526]
### Godot version

4.0.alpha.custom_build.faddbcfc0

### System information

5.10.105-1-MANJARO x86_64,  Intel Core i7-9750H, NVIDIA TU106M [GeForce RTX 2070 Mobile] 

### Issue description

The mouse cursor disappears when inputting a value at the UI by using the keyboard and moving the mouse right afterward.
The moused gets 'trapped' on the input field and can no longer be used.
Sometimes the cursor gets released after right-clicking but other times I have to close and relaunch the app.

While the mouse cursor is hidden, the middle click and right click still can move the viewport, but the rest of the UI is not working.

https://user-images.githubusercontent.com/5758550/165278432-1893fc31-10f5-4f35-bb91-86324b1a799a.mp4

In the video, you can see how the cursor disappears from the screen right after updating the value of the UI field. It can not be seen, but I'm moving the mouse and clicking all the time until the cursor comes back.

Expected behavior:
The cursor should not be hidden (trapped) if not clicking on the input value or driving the input field box.

### Steps to reproduce

1. select an input field
2. input a value with the keyboard
3. press enter
4. move the mouse out of the input field

**Comment by Calinou** [comment]
Can you reproduce this after enabling **Single Window Mode** in the Editor Settings then restarting the editor?

**Comment by action-script** [comment]
> Related to #46433.
> 
> Can you reproduce this after enabling **Single Window Mode** in the Editor Settings then restarting the editor?

After enabling *Single Window Mode* the hidden cursor problem **seems to be gone**

**Comment by KoBeWi** [comment]
Can't reproduce on Windows 10. Might be system-specific.

**Comment by action-script** [comment]
> Can't reproduce on Windows 10. Might be system-specific.

I just tested again with **4.0 6eee2f1df** and the hidden cursor behavior is still happening when the **Single Window Mode** is **disabled**.

System information
5.10.105-1-MANJARO x86_64, Intel Core i7-9750H, NVIDIA TU106M [GeForce RTX 2070 Mobile]
