### ISSUE TITLE
Confusing "throw an error" in documentation

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#60520]
### Godot version

3.x (8f4f384) master (788f355)

### System information

Arch Linux, GLES 3, Mesa Intel(R) UHD Graphics (CML GT2)

### Issue description

In the classref, there are a few places where "throw an error" is used:

https://github.com/godotengine/godot/blob/8c2b9801fd7046beb431b299eb31b3633287fa65/doc/classes/Object.xml#L300

https://github.com/godotengine/godot/blob/8c2b9801fd7046beb431b299eb31b3633287fa65/doc/classes/Performance.xml#L72

It confuses people using C# and people who are new to GDScript. Sounds like it will throw an exception in C#, or GDScript has some sort of exception mechanism. But all this does is printing an error message.

### Steps to reproduce

Search the class reference.

**Comment by PureAsbestos** [comment]
I am a new contributor and I'd like to help with this. I am currently tracking down instances of this language use in the classref

**Comment by PureAsbestos** [comment]
There are 3 instances in `Peformance` and 4 in `Object`.
I couldn't find any others in the classref, though there seem to be a couple in the tutorials as well that should be looked at.
