### ISSUE TITLE
Floating point errors in inspector

### ISSUE THREAD

**Issue by spookdogg** [godotengine/godot#6054]
**Operating system or device - Godot version:**
Windows 7 - 2.0.4.1

**Issue description** (what happened, and what was expected):
When attempting to change the rotation of a node in the inspector, you'll occasionally get floating point errors
for instance, if I was to change the rotation to 90 and press enter, i'd get 90.000001

**Steps to reproduce:**
add sprite
attempt to change rotation in inspector
observe number after pressing enter

**Link to minimal example project** (optional but very welcome):

**Comment by reduz** [comment]
i think this was fixed in 2.1

**Comment by spookdogg** [comment]
> i think this was fixed in 2.1

ah... 
If it was, feel free to close

**Comment by vnen** [comment]
I believe this was fixed by 9151eb591dcab408d3a7e4d9e3b3874c2e281acf. You can try the 2.1-RC2 version in which this is fixed.
