### ISSUE TITLE
Connections dialog Extra Call Argument menu is missing many types

### ISSUE THREAD

**Issue by fire-forge** [godotengine/godot#60544]
### Godot version

v4.0.alpha.custom_build [7b9fd0da6]

### System information

Windows 10

### Issue description

The connection dialog is missing many types. Other type selectors, including the array, dictionary, metadata, and project settings editors have all of the types.

| Connection Dialog | Array Editor |
---|---
| ![image](https://user-images.githubusercontent.com/67974470/165399945-73ee5b3c-1b17-46d6-9d19-5cf005599b33.png) | ![image](https://user-images.githubusercontent.com/67974470/165400080-d0b67b05-6449-4ce9-908d-e1e8588eab25.png) |

### Steps to reproduce

* Select a node
* Switch to the Signals tab in the Node dock
* Double-click a signal to open the connection dialog
* In the bottom-right corner, click Advanced
* Click the dropdown button below "Add Extra Call Argument" in the top-right to see an incomplete list of types

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/pull/32624.
