### ISSUE TITLE
Incorrect signal handling when removing an AnimationLibrary from an AnimationPlayer

### ISSUE THREAD

**Issue by badlogic** [godotengine/godot#60566]
### Godot version

504708ae21b9722ddbf33a2d557a6a9ed0d70855

### System information

Windows 10, but not related to OS or hardware

### Issue description

When removing an `AnimationLibrary` from an `AnimationPlayer` via `AnimationPlayer::remove_animation_library`, `AnimationPlayer::_unref_anim()` is called for all animations:

https://github.com/godotengine/godot/blob/master/scene/animation/animation_player.cpp#L1379

`AnimationPlayer::_unref_anim()` disconnects the player from the animation for signal `tracks_changed`. 
https://github.com/godotengine/godot/blob/master/scene/animation/animation_player.cpp#L1394

However, the player is never actually connected to the animation in the first place. Supposedly, `AnimationPlayer::_ref_anim()` should be used to do that. However, that method is never called anywhere.

Thus, when calling `AnimationPlayer::remove_animation_library()`, the call to `disconnect()` fails for each animation in the library, as the connection was never setup.

```
E 0:00:01:0100   _ready: Attempt to disconnect a nonexistent connection from '[Animation:-9223372012779470470]'. Signal: 'tracks_changed', callable: 'AnimationPlayer::_animation_changed'.
  <C++ Error>    Condition "signal_is_valid" is true.
  <C++ Source>   core\object\object.cpp:1408 @ Object::_disconnect()
  <Stack Trace>  animation-unref-failure.gd:7 @ _ready()
```

### Steps to reproduce

1. Open the provided reproduction project below with the Godot editor compiled from the SHA for this issue.
2. Run the `animation_unref_failure.tscn` Scene
3. Observe the error in the debugger log.

```
E 0:00:01:0100   _ready: Attempt to disconnect a nonexistent connection from '[Animation:-9223372012779470470]'. Signal: 'tracks_changed', callable: 'AnimationPlayer::_animation_changed'.
  <C++ Error>    Condition "signal_is_valid" is true.
  <C++ Source>   core\object\object.cpp:1408 @ Object::_disconnect()
  <Stack Trace>  animation-unref-failure.gd:7 @ _ready()
```

### Minimal reproduction project

[animation_unref_failure.zip](https://github.com/godotengine/godot/files/8573394/animation_unref_failure.zip)

**Comment by voylin** [comment]
Can confirm this issue. Working on the finite state machine in the godot-project-demos for making it ready for 4.0 and I'm having the same errors.
