### ISSUE TITLE
AnimationPlayer::apply_reset fails due to incorrect animation name set on aux_player

### ISSUE THREAD

**Issue by badlogic** [godotengine/godot#60564]
### Godot version

504708ae21b9722ddbf33a2d557a6a9ed0d70855

### System information

Windows 10, but irrelevant

### Issue description

When saving a scene with an `AnimationPlayer` that has `reset on save` checked, and when a `RESET` animation is found in the player's animation library, `AnimationPlayer::apply_reset()` fails to actually reset the properties. Here's why:

To apply the reset animation, an auxiliary `AnimationPlayer` is created and the `RESET` animation is added to its `default` animation library.
https://github.com/godotengine/godot/blob/master/scene/animation/animation_player.cpp#L2013-L2014

 However, the call to `AnimationPlayer::set_assigned_animation` passes in `RESET` instead of `default/RESET`
https://github.com/godotengine/godot/blob/master/scene/animation/animation_player.cpp#L2015

Which subsequently triggers this precondition, preventing the animation to be set:
https://github.com/godotengine/godot/blob/master/scene/animation/animation_player.cpp#L1673

Subsequently, the call to `AnimationPlayer::seek` also fails, as no animation is set on the player:
https://github.com/godotengine/godot/blob/master/scene/animation/animation_player.cpp#L2019

This means the properties keyed by `RESET` are actually not reset, and the scene is saved with whatever the current property values are, despite `reset on save` being checked for the `AnimationPlayer`.

### Steps to reproduce

1. Create a new scene
2. Create a `Sprite2D`
3. Create an `AnimationPlayer`
4. Create a new animation in the `AnimationPlayer`
5. key any property of the `Sprite2D` while having the new animation open in the animation player editor.
6. Click `OK` when asked if a `RESET` animation should be created
7. While still having the new animation open in the animation player editor, save the scene

Result:
The precondition in `AnimationPlayer::set_assigned_animation` fails, as the `RESET` animation is not in the `animation_set` of the player. Subsequently, `AnimationPlayer::seek` also fails, as no animation was set.
```
ERROR: Condition "!animation_set.has(p_anim)" is true.
   at: AnimationPlayer::set_assigned_animation (scene\animation\animation_player.cpp:1673)
ERROR: Condition "!playback.current.from" is true.
   at: AnimationPlayer::seek (scene\animation\animation_player.cpp:1719)
```

The keyed properties are thus not reset, and the scene is saved without the `RESET` animation actually being applied.

### Minimal reproduction project

I'll send a PR instead.

**Comment by akien-mga** [comment]
Fixed by #62336.
