### ISSUE TITLE
GDScript 2.0: "Parser Bug (Please Report)" on scene preloading

### ISSUE THREAD

**Issue by StalfFromValenwood** [godotengine/godot#60572]
### Godot version

v4.0.alpha7.official [3e9ead05f]

### System information

Windows 10

### Issue description

![image](https://user-images.githubusercontent.com/73066705/165640570-0d46fac9-a9e0-400b-820d-b9cb3d9f827e.png)

I added a RPC function to my player code when the game stopped working at launch, while preloading the player scene.
The function is not called anywhere, I have other functions with the same RPC config and yet it was working before.
I had the issue in alpha 6 and tried alpha 7 to see if it was resolved.

### Steps to reproduce

Not sure, it seems to be an unexpected behaviour. The function that is triggering the error is this one :

```
@rpc(any_peer, reliable, call_remote)
func request_update_enabled():
	rpc_id(Network.api.get_remote_sender_id(), "sync_enabled", enabled)
```
You just need a node with this code, and another one preloading it. It is enough to stop Godot for me.
The node calling the preload is an AutoLoad in my case.

### Minimal reproduction project

[GDScript 2.0 Parser Bug with RPCs.zip](https://github.com/godotengine/godot/files/8578430/GDScript.2.0.Parser.Bug.with.RPCs.zip)

**Comment by Calinou** [comment]
> I am sorry, I can not upload the minimal reproduction project, Github does not accept it for some reason.
I hope I can find a way to send it to you, as this error may occur following a lot of unrelated situations.

This is likely because the attachment is not a ZIP file, or because it's larger than 10 MB.

**Comment by StalfFromValenwood** [comment]
I had stripped the project down to the bare minimum except I left the .godot folder... fixed !

**Comment by StalfFromValenwood** [comment]
Apparently the problem is related to `get_remote_sender_id()` because the project is running fine after I changed the function to :

```
@rpc(any_peer, reliable, call_remote)
func request_update_enabled(from_id:int):
	rpc_id(from_id, "sync_enabled", enabled)
```

**Comment by vnen** [comment]
This error does not exist anymore, I assume this already has been fixed.
