### ISSUE TITLE
Vulkan: CanvasLayer makes child OptionButton option list display incorrectly

### ISSUE THREAD

**Issue by jumpy-lion** [godotengine/godot#60570]
### Godot version

v4.0.alpha6.official [e4f0fc50f]

### System information

Windows 7, NVIDIA GTX 750 Ti

### Issue description

Clicking on OptionButton that is a child of CanvasLayer makes option list appear not directly below it, but about half screen away to the bottom-right.

### Steps to reproduce

Create CanvasLayer node, attach OptionButton child node to it, click the button in game.

**Comment by arkology** [comment]
Please provide info about your gpu. May be related to #58314

**Comment by jumpy-lion** [comment]
The list displays properly if no camera node is in use.
