### ISSUE TITLE
I can't use C# in godot mobile. How can i fix that?

### ISSUE THREAD

**Issue by Bna4** [godotengine/godot#60578]
### Godot version

3.5 beta

### System information

Android

### Issue description

How do I use C# Because it is not in the application.
How can I use it within the application on the phone, and are there additional files to download?
I hope for a solution to the problem as soon as possible because there is no place for a solution.

### Steps to reproduce

nothing

### Minimal reproduction project

nothing

**Comment by akien-mga** [comment]
I assume you mean the Android editor. There's no C# support planned for it at this stage. Maybe later, but this adds significant complexity (if possible at all to run MSBuild on Android) which is not in our priorities.

**Comment by Bna4** [comment]
> I assume you mean the Android editor. There's no C# support planned for it at this stage. Maybe later, but this adds significant complexity (if possible at all to run MSBuild on Android) which is not in our priorities.

this is bad

**Comment by lewiji** [comment]
> this is bad

Microsoft don't provide or support the dotnet SDK or cli tools for Android, there's not much that can be done about that. Maybe it's possible by installing Linux in Termux and installing the arm builds on there, but it's unlikely to be a fully supported or productive setup.

You can run C# .NET apps compiled on a PC for android,  but you can't develop and compile C# code on android, to the best of my knowledge, right now. This isn't a Godot specific problem.
