### ISSUE TITLE
Android app name dont support translate to traditional chinese

### ISSUE THREAD

**Issue by Skyfrit** [godotengine/godot#6058]
**Operating system or device - Godot version:**
android
Godot_v2.1_rc2

**Issue description** (what happened, and what was expected):
I try to translate my android app name to traditional chinese, but without success.

So I open the apk file and realize it only have folder values-zh

This means the android app name only support translate to simplified chinese

![untitled](https://cloud.githubusercontent.com/assets/20874456/17456823/a9f472b2-5c16-11e6-9a41-e09e6da50db8.jpg)

**Comment by reduz** [comment]
please check platform/android/java

in the resources folder you should be able to see the available languages.
If any is missing feel free to add it (as long as it's supported by Android
I guess)
the exporter will recognize it

**Comment by akien-mga** [comment]
Fixed by #6061, #6062 and #6063.
