### ISSUE TITLE
Invalid `.gdc` file loaded in editor crashes Godot

### ISSUE THREAD

**Issue by Kakcalu13** [godotengine/godot#60589]
### Godot version

v3.4.4.stable.official [419e713a2]

### System information

macOS Monterey, Apple M1 using GLES2 in Godot

### Issue description

- Add `something.gdc` in the folder, Godot crash instantly. 

### Steps to reproduce

- Open this zip
- Go to terminal inside the root of Godot project.
- Type "nano something.gdc" in your terminal
- Type anything, it doesn't matter as long as there's a string
- Go back to Godot.
Crashed on its own.

### Minimal reproduction project

[delete_this.zip](https://github.com/godotengine/godot/files/8584730/delete_this.zip)

**Comment by Kakcalu13** [comment]
https://user-images.githubusercontent.com/65916520/165804064-d9525c0e-98d4-435d-a5b8-0ba27140c32d.mp4

Tested it on linux, it does the same thing on Linux. This linux has v3.4.stable.official [206ba70f4]

**Comment by Calinou** [comment]
`.gdc` is the file extension used for GDScript bytecode. This is only used in exported project PCKs – it's not meant to be used directly within the editor.

**Comment by Kakcalu13** [comment]
That explains a lot.

I was using csv data. I notice that export doesn't include csv_data generated right before export command line ran. So, I changed the csv data file from `csv_data.csv` to `csv_data.gdc` and it worked well through command line export. 

Is it possible to just leave it alone without crash the Godot? I have one gd script to read the file with gdc using file programming?

**Comment by Calinou** [comment]
> I was using csv data. I notice that export doesn't include csv_data generated right before export command line ran. So, I changed the csv data file from csv_data.csv to csv_data.gdc and it worked well through command line export.

After selecting a resource in the FileSystem dock, you can set its import mode to **Keep File (No Import)** in the Import dock.

**Comment by Kakcalu13** [comment]
I'm going to test it on [3.5-beta4](https://downloads.tuxfamily.org/godotengine/3.5/beta4/)

I will update you. If this is no longer issue in 3.5, would you like me to close this ticket? The original issue was for 3.4.4-stable but I didn't realize 3.5 is the newest. I originally thought 3.4.4-stable was the newest (exclude Godot 4)

Also is it possible to suppress the error log for gdc when I just wanted to hold it for code to read inside the gdc file?




> > I was using csv data. I notice that export doesn't include csv_data generated right before export command line ran. So, I changed the csv data file from csv_data.csv to csv_data.gdc and it worked well through command line export.
> 
> After selecting a resource in the FileSystem dock, you can set its import mode to **Keep File (No Import)** in the Import dock. In the Export dialog, you'll need to specify `*.csv` in the non-resource export filter for the file to be included in the exported project.

The problem is that it doesn't upload to export with changed data in csv_data.csv. Let me re-test that and I will make a new issue. For now, let's not worry about this.

**Comment by bruvzg** [comment]
I can reproduce the crash with 3.4.4 but not with current 3.x on macOS. There's no debug symbols, and therefor no usable crash log, but it seems to be crashing inside the OpenGL driver, so an attempt to load GDC might corrupt unrelated memory (and not necessity fixed in 3.5).

> I can't reproduce this on a blank project on 4.0.alpha https://github.com/godotengine/godot/commit/212989d467b2ab091fe0d78b4ca09e76f9c92e0d.

4.0 do not have bytecode support, add won't try to load it.

**Comment by Kakcalu13** [comment]
Is this expected? 
<img width="998" alt="Screen Shot 2022-04-28 at 1 46 08 PM" src="https://user-images.githubusercontent.com/65916520/165815419-2c236a6c-38c7-47a4-8192-5b4724a23e2f.png">


Left is 3.5-beta4 and right is pycharm.

gdc file doesn't display data while pycharm is able to display data

**Comment by Calinou** [comment]
> Is this expected?

Yes, as Godot tries to import the `.gdc` file as a resource and fails. You'll need to rename the file extension to `.csv` and tell Godot not to import the file as I said above.

**Comment by Kakcalu13** [comment]
Since this issue is no longer exist in 3.5, I think it is safe to close this issue. Yes?

**Comment by Kakcalu13** [comment]
Closing as it's fixed in 3.5+
