### ISSUE TITLE
Label3D missing offset property

### ISSUE THREAD

**Issue by stryker313** [godotengine/godot#60593]
### Godot version

4.0 Alpha 7

### System information

Windows 10 Nvidia GTX 1060 Intel i5 4690k

### Issue description

Label 3D is missing the offset property.

Sprite 3D and Animated Sprite3D both have this property.

The only way to get somewhat of a close result to this, is to change the font orientation and use spaces.

### Steps to reproduce

1. Open a label3D node
2. Attempt to locate the offset property

### Minimal reproduction project

None needed.

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by stryker313** [comment]
> having a separate offset property is convenient for animation purposes (for relative animations without dummy nodes).
This. The problem I ran into is that I need to have the label hinge around the origin, however, without offset its not really feasible. The solution for this atm is to write a custom node that calls look_at() towards the main camera.
