### ISSUE TITLE
Script templates ignored in Godot 4

### ISSUE THREAD

**Issue by Kehom** [godotengine/godot#60591]
### Godot version

4.0

### System information

Windows 10

### Issue description

The `script_templates` directory seems to be completely ignored by Godot 4.0. I tried alpha versions 1, 5, 6 and 7.
I have attempted to used:

* `%APPDATA%\Godot\script_templates`
* `res://script_templates`
* And the `script_templates` subdirectory when running Godot as portable, with the `._sc_` file within the binary executable.

I was unable to test this on Linux as Godot 4 simply crashes before even showing the project list.

### Steps to reproduce

- Create a simple script template file and place it within one of the `script_template` directories.
- Run Godot 4.
- Attempt to create a new script using that template. The template list will contain just the two default built-in options.

**Comment by KoBeWi** [comment]
The template structure has changed, they are now grouped by base type. Your templates should go to `res://script_templates/Node` or whatever class you want to use.
