### ISSUE TITLE
Erratic scrolling on Android when pressing on an element

### ISSUE THREAD

**Issue by blurrred** [godotengine/godot#60600]
### Godot version

3.4.4

### System information

Manjaro Linux

### Issue description

If you press down on some types of nodes inside a scrollable node and begin to scroll, the screen jumps around.

### Steps to reproduce

All you need to do is try scrolling on some nodes in a scrollable container and you'll see how it jumps around instead of being smooth. Ideally it would either be completely still or scroll as normal.

### Minimal reproduction project

[Mobile Scrolling Bug.tar.gz](https://github.com/godotengine/godot/files/8587129/Mobile.Scrolling.Bug.tar.gz)

**Comment by Calinou** [comment]
This is likely fixed by either https://github.com/godotengine/godot/pull/47931 or https://github.com/godotengine/godot/pull/52128.

**Comment by blurrred** [comment]
Here is a video of the issue.

At first I show scrolling as normal, when I don't begin the scroll on a button.

Then I show twice the erratic scrolling that occurs if I begin the scroll with my finger on a button.

As I was doing this, I noticed that the erratic scrolling *doesn't* occur if I hold the button down for a second. It only occurs if I quickly scroll immediately after pressing down on the screen.

https://user-images.githubusercontent.com/7478730/166170061-f7db0928-6764-48e3-ba4d-b5c7e81a5bde.mp4
