### ISSUE TITLE
Shading Language : Godot Alpha 7 Unknown identifier

### ISSUE THREAD

**Issue by Berkru** [godotengine/godot#60605]
### Godot version

4.0 alpha 7

### System information

ubuntu 21.10

### Issue description

on the shader code: 
MODELVIEW_MATRIX = INV_CAMERA_MATRIX * mat4(CAMERA_MATRIX[0],WORLD_MATRIX[1],vec4(normalize(cross(CAMERA_MATRIX[0].xyz,WORLD_MATRIX[1].xyz)), 0.0),WORLD_MATRIX[3]);

 INV_CAMERA_MATRIX returns a error : 
 error(19): Unknown identifier in expression: 'INV_CAMERA_MATRIX'.

### Steps to reproduce

just try to use the shader I upload below.

### Minimal reproduction project

[grass.gdshader.zip](https://github.com/godotengine/godot/files/8587550/grass.gdshader.zip)

**Comment by Chaosus** [comment]
`INV_CAMERA_MATRIX` has been renamed to `VIEW_MATRIX` (see https://github.com/godotengine/godot/pull/59268)
