### ISSUE TITLE
Error message for reaching maximum number of concurrent DNS queries is not explicit.

### ISSUE THREAD

**Issue by Mickeon** [godotengine/godot#60602]
### Godot version

3.x

### System information

Windows 10

### Issue description

After https://github.com/godotengine/godot/pull/59445 upped the maximum concurrent DNS queries at any given time, it is much less likely to reach the limit, but not impossible. And should it occur, the console outputs:
```
Condition ' resolving == IP::RESOLVER_INVALID_ID ' is true. returned: ERR_BUG
```

This error message can potentially be very confusing. misleading and, compared to most other error messages in Godot, it looks quite cryptic. If the users doesn't know where to look, it's bound to cause a few headaches
Ideally, it should tell the user exactly what happened (the query limit has been reached), and potentially instruct the user on how to fix it (_tone down the requests, or increase the limit, the latter of which should probably not be encouraged_)

### Steps to reproduce

No need.

**Comment by Calinou** [comment]
https://github.com/godotengine/godot/pull/59445 added error messages, but I'm confused as to why they're not printed on your end.
