### ISSUE TITLE
color distortion on iPhone

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#60611]
### Godot version

3.4.4

### System information

Mac OS 12.3.1

### Issue description

The colors on iPhone is not exactly the same as the value set.

for example, 
I set a color 0x55aa6a for a panel, and run the project on a iPhone, the color is a little dim, I get a screenshot and  
pick its color in photoshop, the value is 6ba870.

Also, when  import a image, the  image run on iPhone has color distortion.

But the run on Mac OS, the color value is the same as what is set.

### Steps to reproduce

add a panel
set a color value
export to iOS
run on iPhone
get a screenshot
check the color value in photoshop

**Comment by alexzheng** [comment]
<img width="483" alt="mac" src="https://user-images.githubusercontent.com/1130047/166084533-c044c545-c48e-4ed9-9c1e-6ee062bb5afe.png">
![iPhone](https://user-images.githubusercontent.com/1130047/166084539-952e4729-e607-467f-822c-71434be2b187.PNG)

**Comment by alexzheng** [comment]
gles 3 
2d
It's not related to a particular node or color value, any colors has that issue.

**Comment by STUDIOEMBYR** [comment]
Bit of a long shot here but does this still haven if you disable "true tone" in your phone's settings?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.
