### ISSUE TITLE
Godot detects keystrokes ONLY after another key/mouse button is pressed

### ISSUE THREAD

**Issue by Gjakrov** [godotengine/godot#60620]
### Godot version

3.4.4.stable.official (From Steam)

### System information

Windows 10, GLES3, Intel HD Graphics 610

### Issue description

I used Godot normally with my Void Linux install, no problems at all with the engine.
Bad things began when I switched to Windows 10, more specifically with the keyboard/mouse in general while using the engine.

_**The actual issue is this:**_

Godot only detects i've pressed a key ONLY after you press it again or another key/mouse button is pressed down, this being extremely annoying and makes the program impossible to use properly.

### Steps to reproduce

**_Steps:_**

1. Just open Godot
2. Try to press a key
3. You'll notice nothing happens
4. When you press the same key again, another key or the mouse the previous keystroke will be finally detected and so on...

### Minimal reproduction project

https://user-images.githubusercontent.com/92241184/165916419-e47d1301-da2e-4b13-a02d-19ba7c6d960f.mp4

**Comment by akien-mga** [comment]
Sounds like #23069 which is an Intel driver bug. Which driver version do you have, and can you try updating it?

**Comment by Gjakrov** [comment]
Hello! and thank you for asking:

> Sounds like #23069 which is an Intel driver bug. Which driver version do you have, and can you try updating it?

24.20.100.6170

It's the latest one for my GPU.

P.D: Graphics running on Celeron G3930

**Comment by akien-mga** [comment]
> 24.20.100.6170

Yeah that's very old, and the bug was fixed in 25.20.100. But indeed Intel seems not to provide its latest drivers for Celeron G3930 anymore :|

Does this workaround work for you?
https://github.com/godotengine/godot/issues/23069#issuecomment-573348919

**Comment by Gjakrov** [comment]
> Does this workaround work for you? [#23069 (comment)](https://github.com/godotengine/godot/issues/23069#issuecomment-573348919)

Nope, sadly it doesn't

**Comment by akien-mga** [comment]
And does it work if you start Godot with the `--verbose` flag?

Note that that will use it for the project manager but it's not automatically propagated to the editor process when opening a project, so it might solve the bug for the project manager but not the editor (but you can enable `verbose_stdout` in the Project Settings which should also affect the editor after a restart).

**Comment by Gjakrov** [comment]
> And does it work if you start Godot with the `--verbose` flag?
> 
> Note that that will use it for the project manager but it's not automatically propagated to the editor process when opening a project, so it might solve the bug for the project manager but not the editor (but you can enable `verbose_stdout` in the Project Settings which should also affect the editor after a restart).

Well, that fixed the issue like magic. All of a sudden, just like it appeared :P

**Comment by akien-mga** [comment]
Great, then it's indeed the same bug as #23069. We don't really know what causes it and why `--verbose` fixes it, but since it's fixed in newer Intel drivers, only a handful of old devices are left unfixed (and work fine on Linux with Mesa). So you'll probably have to keep using this workaround on this computer for the foreseeable future.
