### ISSUE TITLE
Idle Time spike when NavigationAgent is present

### ISSUE THREAD

**Issue by gramozilho** [godotengine/godot#60621]
### Godot version

3.5.beta2 and 3.5.beta4 

### System information

Windows 10, GLES3, NVIDIA GeForce RTX 2070 Super

### Issue description

If a NavigationAgent is a child of NavigationMeshInstance there is noticeable lag even when not in use. 
Profiler shows a big spike in Idle Time not coming from any script function. Removing the NavigationAgent and running the scene again removes the spike.
![image](https://user-images.githubusercontent.com/26416853/165918527-4816b269-55f5-4b0f-94d9-c07647fd8ff6.png)
Happens with or without baked NavMesh.
Moving the NavigationAgent somewhere else also removes the spike.
Issue spotted when adding a NavigationAgent node to a RigidBody in character mode to move to a destination (3.4.beta2)

### Steps to reproduce

Add a Navigation node, a NavigationMeshInstance as child and a NavigationAgent as child of that.
Run with the Profiler on.
Running the same scene without the NavigationAgent 

### Minimal reproduction project

Both Main (scene with valid NavMesh) and MinimumTest (just the 3 nodes mentioned above).

[NavigationIdleTimeExample.zip](https://github.com/godotengine/godot/files/8589790/NavigationIdleTimeExample.zip)

**Comment by akien-mga** [comment]
This might be a duplicate of #56838 which was fixed recently. The fix will be included in 3.5 beta 5.

Could you test latest CI builds from the `3.x` branch to confirm? https://github.com/godotengine/godot/actions/runs/2244474520
Alternatively if you can build `3.x` from source, that would work too.

**Comment by gramozilho** [comment]
@akien-mga yes, the problem is gone after building from source. Closing the issue then.
