### ISSUE TITLE
[4.0] a7 – FBX file import is enabled, but no FBX2glTF path is configured

### ISSUE THREAD

**Issue by Rinocrosser** [godotengine/godot#60630]
### Godot version

4.0 alpha 7

### System information

Windows 10

### Issue description

The FBX support is still broken. Here I dropped the FBX file, it's visible in Windows Explorer, but not inside the editor:

![image](https://user-images.githubusercontent.com/19660324/165967480-cada0e38-d830-46be-bf75-9c9b2d994882.png)

### Steps to reproduce

- Try to import FBX
- See nothing
- Check error log to find: modules/gltf/register_types.cpp:92 - FBX file import is enabled, but no FBX2glTF path is configured. FBX files will not be imported.

**Comment by akien-mga** [comment]
See the release notes for 4.0 alpha 6: https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-6

The new importer uses an external tool which is a lot better at importing FBX files than the previous importer.

**Comment by Rinocrosser** [comment]
> The new importer uses an external tool which is a lot better at importing FBX files than the previous importer.

Still not very convenient and this "a lot better" isn't better for me (since the internal tool worked just fine, and this one require some extra steps, which breaks the whole Godot magic of a solid tool). How about using both tools and the external would be OPTIONAL, since it's required, when the internal one fail?

**Comment by akien-mga** [comment]
It definitely didn't work fine with Blender FBX for many users... #44402

> Yet again, I suggest to use both.

That's not possible. You can't detect which FBX would be supported by which importer, you have to import, and the user has to see if what they get is what they expect.

**Comment by kzerot** [comment]
Maybe it would be better to ease user experience with automated download&&install this tool? Just like with export templates. 
So user just will be asked "Do you want to install fbx support?" and so on. Does FBX2glTF license allows it?

**Comment by akien-mga** [comment]
> Maybe it would be better to ease user experience with automated download&&install this tool? Just like with export templates. So user just will be asked "Do you want to install fbx support?" and so on. Does FBX2glTF license allows it?

Ideally yes, but FBX2glTF depends on the FBX SDK and so the user needs to approve that license to use it.
We could parse the license file to display it in the editor and ask the user to accept, which is the workflow I'd favor, but we'll need to check that we're legally allowed to integrate it this way.

**Comment by nathanfranke** [comment]
I propose bundling a `thirdparty/` FBX library with the editor.

Auto-downloading sounds like a bad idea.
1) It is phoning home (or someone else's home).
2) Could download malicious software if we do not control the server.
3) Auto-downloading proprietary (FBX SDK) software with an EULA defeats the purpose of open source.

**Comment by akien-mga** [comment]
> Auto-downloading proprietary (FBX SDK) software with an EULA defeats the purpose of open source.

*Using* FBX defeats the purpose of open source. It's a proprietary format. People should really use glTF 2.0 instead, but for now we have to make do with users wanting FBX support.

> I propose bundling a `thirdparty/` FBX library with the editor.

Well, that's what the previous, not really functional reverse engineering of FBX based on the Assimp parser was. It didn't work well.

Another option is to use [OpenFBX](https://github.com/nem0/OpenFBX), but implementing it in a way that produces a scene useful to Godot is probably at least 6 months of work for someone very familiar with both FBX and Godot. So while this would be nice (provided that OpenFBX works well on a wide range of FBX scenes), this is not as simple as you make it sound.

The FBX2glTF tool depends on the proprietary FBX SDK so it cannot be vendored in `thirdparty/`.

**Comment by MHillier98** [comment]
Currently running v4.0.beta1.official [20d667284] and also ran into this - I had to restart the editor for the importer to work, so some kind of messaging about that would be nice if nothing else.  Related issue: https://github.com/godotengine/godot/issues/63695

However I would also agree this is annoying to set up as I had to google for the alpha 6 announcement to figure out what this new feature was, and to find a link to download the V-Sekai fork.

**Comment by fire** [comment]
I am listening, have been swamped so I wasn't able to take on the changes in https://github.com/godotengine/godot/pull/59810.

**Comment by Kimedero** [comment]
Where is the FBX2Gltf too located?

**Comment by clayjohn** [comment]
Closing as the engine [automatically gives you a popup](https://github.com/godotengine/godot/pull/59810) to configure FBX2GLTF along with a [link](https://godotengine.org/fbx-import) to download it. The FBX2GLTF vs builtin FBX support issue has been debated to death already and the people responsible for doing the work and actually maintaining the imports all agree that this is the better option, both for user experience and for our development. team.

**Comment by Hobart2967** [comment]
> ### Godot version
> 4.0 alpha 7
> 
> ### System information
> Windows 10
> 
> ### Issue description
> The FBX support is still broken. Here I dropped the FBX file, it's visible in Windows Explorer, but not inside the editor:
> 
> ![image](https://user-images.githubusercontent.com/19660324/165967480-cada0e38-d830-46be-bf75-9c9b2d994882.png)
> 
> ### Steps to reproduce
> * Try to import FBX
> * See nothing
> * Check error log to find: modules/gltf/register_types.cpp:92 - FBX file import is enabled, but no FBX2glTF path is configured. FBX files will not be imported.
> 
> ### Minimal reproduction project
> _No response_

You can reactivate fbx support within project settings, not editor settings. Just search for fbx within the project settings (tested with advanced settings on)
