### ISSUE TITLE
Subresources no longer nest in Inspector

### ISSUE THREAD

**Issue by clayjohn** [godotengine/godot#60640]
### Godot version

4.0 (675594e9cd36506593dcd4b0019861dd64f1dd8e)

### System information

Pop OS 22.04 

### Issue description

Introduced by #60500 When editing subresources they open on their own page in the inspector instead of nesting. 

Interesting note, when running Alpha 7 from a different computer running Windows 10, Inspecter nesting worked just fine

_After clicking on sky in Environment:_
![Screenshot from 2022-04-29 14-12-45](https://user-images.githubusercontent.com/16521339/166069927-23716175-31c8-4c73-887c-01f21e747ce2.png)

### Steps to reproduce

1. Open Editor
2. Add a WorldEnvironment node to the scene
3. Add an environment to the world environment
4. Open the Environment
5. set background to sky
6. create a sky
7. create a ProceduralSkyMaterial
8. click on another node
9. Save
10. Click on the worldenvironment
11. click on the Sky

After some further testing it looks like this isn't so simple, on a new scene when the resources are being created for a first time nesting works, but if you click on another node, save and then come back it stops working.

It will open in its own page

### Minimal reproduction project
[3Dtest.zip](https://github.com/godotengine/godot/files/8595080/3Dtest.zip)

**Comment by KoBeWi** [comment]
Can't reproduce in 91f9a48ad
![godot windows tools 64_YXHg65OGh8](https://user-images.githubusercontent.com/2223172/166073658-162e550c-34db-4dfd-8dd4-ddb165c89416.gif)
