### ISSUE TITLE
Websocket minimal example not working on Godot 4 alpha 7

### ISSUE THREAD

**Issue by Kazuo256** [godotengine/godot#60647]
### Godot version

4.0.alpha7.official [3e9ead05f]

### System information

Linux Mint 19.3 Cinnamon

### Issue description

It seems that a regression in the latest alpha build makes websocket connections close before (or as soon as) they are established.

### Steps to reproduce

1. Run the latest minimal websocket demo
2. The output says that the connection was closed (not clean) and no message about the test packet is printed

On Godot 4 alpha 6 the demo prints the expected packet exchange messages.

### Minimal reproduction project

[The minimal websocket demo](https://github.com/godotengine/godot-demo-projects/tree/master/networking/websocket_minimal)

**Comment by zhouzhipeng** [comment]
encountered the same problem , using 4.0 alpha7 ,  the language server and remote debug server not work,  which are working correct on alpha6.

**Comment by dsnopek** [comment]
I was also seeing `WebSocketClient` not connecting in Godot 4.0-alpha7, but compiled the latest master (e3371a53f845079e7f2bf67bbd76ace26c080978) and it appears to connect fine now.

**Comment by akien-mga** [comment]
Indeed, this was fixed by #60761.
