### ISSUE TITLE
Vulkan: Incorrect indirect lighting coloring in LightmapGI

### ISSUE THREAD

**Issue by Hakimvira** [godotengine/godot#60648]
### Godot version

Godot 4 Alpha 7

### System information

Windows 11, RTX 3050, 472.12, Vulkan Clustered

### Issue description

In this test, the boxes did not take into account the indirect lightning from the colored wall.
![cornell_box_4_7](https://user-images.githubusercontent.com/62761946/166091313-d604918a-23ad-4704-a489-84dd482167a6.png)
I thought this is the intended behavior until I tested with Godot 3.4.4 using the same model
![cornel_box_3 4 4](https://user-images.githubusercontent.com/62761946/166091332-06c7b1f4-6470-40d2-8e9b-456669817223.png)
The Godot 3.4.4 produced much better result with the same settings. Another problem is the generated UV2s are not saved when I exited the program. 

### Steps to reproduce

1. Open the project
2. Open cornell_box.tscn
3. Unwrap UV2 because Godot did not save the previous UV2s

### Minimal reproduction project

[cornell_box_test.zip](https://github.com/godotengine/godot/files/8596106/cornell_box_test.zip)

**Comment by Calinou** [comment]
> Another problem is the generated UV2s are not saved when I exited the program.

Generating UV2 from imported scenes should be done using the Import dock, *not* the Mesh menu at the top of the 3D editor viewport.

**Comment by Calinou** [comment]
This is no longer an issue as of 4.4.dev 9e6098432:

![Image](https://github.com/user-attachments/assets/26ee3be3-b6c9-4c07-aae2-dd5c968e3773)

(It was probably resolved earlier.)
