### ISSUE TITLE
Vulkan: Blocky glow after splitting tonemapper into its own class

### ISSUE THREAD

**Issue by GNSS-Stylist** [godotengine/godot#60658]
### Godot version

v4.0.alpha.custom_build [957644a4a]

### System information

Windows 10, RTX2060, Vulkan

### Issue description

Glow got blocky after recent refactoring ( 3b2267ba6d0db3e6db4a0f95c58f7c7e300fec92 ).

Some shapes with "oversaturated colors", Before:
![image](https://user-images.githubusercontent.com/50438441/166105331-81e06071-4aa4-4759-a76c-33e5959f6abe.png)
After:
![image](https://user-images.githubusercontent.com/50438441/166105336-219b73df-428d-4eda-b2b2-9e62127f69af.png)

(In these images the blockiness doesn't look as pronounced as in some others where there are more detailed shapes).

For anyone stumbling upon this: You can (for now at least) work around this by reverting the changes by the aforementioned commit.

### Steps to reproduce

Add something glowy into 3D-scene (I don't know if this affects 2D) and enable glow.

### Minimal reproduction project

[BlockyGlow.zip](https://github.com/godotengine/godot/files/8596870/BlockyGlow.zip)

**Comment by Calinou** [comment]
cc @BastiaanOlij
