### ISSUE TITLE
Reloadable for GDNative in 3.5 Beta appears broken since Beta 3

### ISSUE THREAD

**Issue by atsmith6** [godotengine/godot#60653]
### Godot version

v3.5.beta3.official [3c0d32562]

### System information

Windows 10, GLES 3, RTX 2070

### Issue description

Dynamically uploading a GDNative DLL when switching Godot to the background in Windows has stopped working between beta 2 and beta 3.

### Steps to reproduce

1. Use any project with a GDNative DLL.
1. Notice that in 3.5 Beta 1 and 3.5 Beta 2 you can switch Godot to the background and then the GDNative DLL is unloaded and the handle released allowing the DLL to be recompiled/replaced without restarting Godot.
1. In **3.5 Beta 3** and **3.5 Beta 4** the GDNative DLL is not unloaded when Godot is switched to the background and cannot be recompiled because the target output file is still locked by Godot.  You can test this easily by trying to delete the DLL with Windows explorer.  You will get the error message "The action can't be completed because the file is open in Godot Engine."
1. Note that I have determined that when you switch to the background then the function **godot_gdnative_terminate()** is called so it appears that Godot is going through the motions but that ultimately it's not releasing the handle to the DLL causing the file to be locked.  When you switch to the foreground **godot_gdnative_init()** and **godot_nativescript_init()** are both called but it's on the same instance of the DLL that was loaded when Godot was switched to the background.

As stated above if I open the project in Godot 3.5 Beta 1 or Godot 3.5 Beta 2 this all works fine.  If I open the project using 3.5 Beta 3 or 3.5 Beta 4 then the DLL remains in memory and can't be recompiled as described above.

**Comment by akien-mga** [comment]
That's pretty weird, I don't see any change between 3.5 beta 2 and 3.5 beta 3 that could cause this a priori: https://github.com/godotengine/godot/compare/7a4f9dfb15a6817135e753b286cd5b767119d08b...3c0d32562b558b60abe382f2a132f4ea0f25b380

Would you be able to bisect between the two versions? (i.e. 7a4f9dfb for 3.5 beta 2 and 3c0d325 for 3.5 beta 3, though I'd start by making sure that you can reproduce the bug in a custom build of 3c0d325 and not in a build of 7a4f9dfb).

**Comment by atsmith6** [comment]
Hi I'm not certain whether the comment was addressed to me or is essentially internal discussion now.  In case it's addressed to me I'll answer.  If not please feel free to ignore what follows.  I am verbose only to ensure I give you the best transfer of information that I am able.

1. I can confirm that with the publicly available build v3.5.beta2.official [7a4f9dfb1] I can overwrite the GDNative DLL every time the Godot Editor is sent to the background assuming the game is not running.
2. I can confirm that with the publicly available build v3.5.beta3.official [3c0d32562] I **cannot** overwrite the GDNative DLL when Godot Editor is sent to the background regardless of whether the game is.
3. I have also tested this with v3.5.beta1.official [b9b23d222] where I can overwrite the DLL.
4. I have also tested this with v3.5.beta4.official [b6968ab06] where I **cannot** overwrite the DLL.

To be through I also ensured I tried it all again after a reboot and also added custom logging to a file in the godot_gdnative_terminate(), godot_gdnative_init(), godot_nativescript_init() to understand what's going on.

Something that may give a hint as to where the regression/change underlying this might be is that sometimes (not always) in Beta 2 there is a pause when I quit (either by clicking the Windows X or get_tree().quit()).  And when the app does quit a few seconds later logging showed that tree teardown didn't happen properly.  However in Beta 3, though the library does not have it's handle released, the scene that was torn down properly (i.e. getting the NOTIFICATION_WM_QUIT_REQUEST and NOTIFICATION_WM_QUIT_REQUEST notifications for example).

Regarding making a custom build I am brand new to Godot and don't know how to build and debug it yet, let alone where in the source code to look.  Working on it but I still have a little while to go before I can be particularly useful.  Really sorry :(

**Comment by atsmith6** [comment]
Some new information.  After starting up my machine this morning I have now reproduced this DLL-not unloading issue in Beta 2 as well.  Odd thing is it was happily releasing the DLL yesterday all day using Beta 5.  Today it's no longer releasing it in Beta 5 or Beta 2.  The code in the DLL itself hasn't changed (as in I reverted it to what was definitely working yesterday).  I don't know whether this observation is useful but thought I would add it as the fact it is happening in Beta 2 means it may not be caused by [ 50ba2d3 ] as previously thought.  Hope that helps.

**Comment by atsmith6** [comment]
More testing using Beta 5:  I keep my versions if Godot in the path `C:\Program Files\GodotEngine`.  When I copied the executable out of this location to a custom `D:\Programs\Godot` it stopped holding onto the DLL.  I tried this after creating a custom build of Beta 5.  The problem doesn't happen with the custom build, but does with the one I downloaded despite using the same git commit.   However as said it stops happening if I run the downloaded executable from a different custom location.

Given that Beta 5 didn't lock the DLL yesterday even though it was running from `C:\Program Files\GodotEngine` but did today, I will use it from `D:\Programs\Godot` and report back if the DLL locking reappears while running from the custom location.

**Comment by atsmith6** [comment]
Ok I've confirmed it.  If I run Godot from some location (eg. D:\Directory1) then it allows me to rebuild the GDNative DLL all day.  After I shut down and reload the next day I can't replace the DLL while Godot is running.  If I copy Godot to a new directory (or rename the directory to, eg D:\Directory2, then I can rebuild the DLL all day while Godot is running.  When I shutdown and restart the next day I can't replace the DLL while Godot is running again, until I rename the directory to something new again.  Very strange.  I have tried this with Beta2, Beta3, Beta5 and a locally built Beta5.  Consistent across all builds.

**Comment by atsmith6** [comment]
I have figured out what the problem is.  This bug is a side effect of that issue which triggers the Windows Compatibility System to flat the godot executable as not safe to free DLLs in turn causing windows to ignore calls to `FreeLibrary()`.  I have raised a new bug #61543 which properly and clearly details what is happening.  I am closing this bug as a duplicate.
