### ISSUE TITLE
Instancing `AnimatedSprite3D` in GLES3 cause memory leak

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#60669]
### Godot version

4.0.alpha.custom_build. cbdc33bcf

### System information

Ubuntu 21.10 - Nvidia GTX 970, Gnome shell 40.4 X11

### Issue description

```
func _process(delta):
	var temp_variable104 = AnimatedSprite3D.new()
	temp_variable104.queue_free()
```
shows at the end this error
```
ERROR: Condition "instance->base_type == RenderingServer::INSTANCE_NONE" is true.
   at: instance_set_base (servers/rendering/renderer_scene_cull.cpp:616)
ERROR: 99 RID allocations of type 'N5GLES34MeshE' were leaked at exit.
```

### Steps to reproduce

Above

**Comment by clayjohn** [comment]
Should be fixed by https://github.com/godotengine/godot/pull/60643
