### ISSUE TITLE
Materials reset upson closeing project and reopening it 

### ISSUE THREAD

**Issue by coobenguy** [godotengine/godot#60676]
### Godot version

4.0 alpha 7

### System information

windows 10

### Issue description

when you put a texture on an OBJ and save the project and reopen, the texture will be gone and you will have to set it up again.
I also get an error about not having a a path to FBX2gltf but Im not using FBX in the first place.

### Steps to reproduce

import obj file into scene. setup its textures. save file. reopen file. 

### Minimal reproduction project

[textures disapear.zip](https://github.com/godotengine/godot/files/8598265/textures.disapear.zip)

**Comment by clayjohn** [comment]
> when you put a texture on an fbx and save the project and reopen, the texture will be gone and you will have to set it up again.
I also get an error about not having a a path to FBX2gltf but Im not using FBX in the first place.

Just to clarify, are you using FBX? In the first sentence you say you put a texture on an FBX, but in the second you say you are not using FBX.

Is this bug reproducable with other formats or just FBX?

**Comment by coobenguy** [comment]
oh sorry my bad, No Its using an OBJ

**Comment by coobenguy** [comment]
there I changed it

**Comment by clayjohn** [comment]
Ah, in that case it appears connected to https://github.com/godotengine/godot/issues/23707 and https://github.com/godotengine/godot/issues/36173

**Comment by Calinou** [comment]
Set the material on the Surface Material Override property located outside the Mesh resource:

![image](https://user-images.githubusercontent.com/180032/166157366-99462813-a0e1-44d1-a9f5-f6b8b2159505.png)

Do not set the material within the Mesh resource itself. I've tested this locally and the material is successfully preserved across restarts.
