### ISSUE TITLE
Missing mesh when running on oculus quest 2 (GLES2, OpenXR)

### ISSUE THREAD

**Issue by lejar** [godotengine/godot#60670]
### Godot version

3.4.4-stable, v3.5.beta4.official [b6968ab06]

### System information

Windows 10, Oculus Quest 2 (GLES2, OpenXR)

### Issue description

What is wrong:
	Run the project directly on the headset, then look down and see the model missing from between the two arrows. The model is visible when running over oculus link.

What should happen:
	The model should be visible.

When running with remote debugging on, the following errors show up when running directly on the oculus (they do not show up when running over oculus link):
Errors in 3.4.4:
	E 0:00:00.446   mesh_add_surface: Condition "array.size() != array_size" is true.
	  <C++ Source>  drivers\gles2\rasterizer_storage_gles2.cpp:2440 @ mesh_add_surface()
	E 0:00:00.448   instance_set_surface_material: Index p_surface = 0 is out of bounds (instance->materials.size() = 0).
	  <C++ Source>  servers\visual\visual_server_scene.cpp:642 @ instance_set_surface_material()
	E 0:00:01.013   mesh_surface_get_array: OpenGL ES 2.0 does not allow retrieving mesh array data
	  <C++ Source>  drivers\gles2\rasterizer_storage_gles2.cpp:2650 @ mesh_surface_get_array()

Errors in v3.5.beta4.official [b6968ab06]
	E 0:00:00.489   mesh_add_surface: Condition "array.size() != array_size" is true.
	  <C++ Source>  drivers\gles2\rasterizer_storage_gles2.cpp:2440 @ mesh_add_surface()
	E 0:00:00.491   instance_set_surface_material: Index p_surface = 0 is out of bounds (instance->materials.size() = 0).
	  <C++ Source>  servers\visual\visual_server_scene.cpp:642 @ instance_set_surface_material()
	E 0:00:01.168   mesh_surface_get_array: OpenGL ES 2.0 does not allow retrieving mesh array data
	  <C++ Source>  drivers\gles2\rasterizer_storage_gles2.cpp:2650 @ mesh_surface_get_array()
	E 0:00:01.168   mesh_surface_get_array: OpenGL ES 2.0 does not allow retrieving mesh array data
	  <C++ Source>  drivers\gles2\rasterizer_storage_gles2.cpp:2650 @ mesh_surface_get_array()

### Steps to reproduce

How to setup minimal project:
	Import project

	Editor > Editor Settings > Export > Android
		Set the android SDK path

	setup android export
		Project > Export > Android
		Custom Template > Debug
			set to bin/android_debug.apk in the project path
		Keystore > Debug
			set to your keystore you create with https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_android.html#create-a-debug-keystore

	Debug > Deploy with Remote Debug

Run the project directly on the headset, then look down and see the model missing from between the two arrows. The model is visible when running over oculus link.

### Minimal reproduction project

https://mega.nz/file/awARkD5T#WvKPvsdfRXXFFEaPhmjsSxLp5YXEfJl3RcnoYnu2zIo

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/28298.

**Comment by lawnjelly** [comment]
Are you sure you are using the correct export templates?

Retrieving mesh data was enabled in cherry picked #40235 from July 2020, a find in files does not seem to find the string "does not allow retrieving" in the current 3.x, and the line numbers of your error messages do not tally up to the source files.

**Comment by lejar** [comment]
You're absolutely correct, I actually had the export misconfigured to use the incorrect android_debug.apk! I can confirm that, after using the correct export template, the issue was resolved and I can see all of my meshes.
Thank you for the help @lawnjelly
