### ISSUE TITLE
Infinite stack frame adding issue on click an object in debugger

### ISSUE THREAD

**Issue by rohanrhu** [godotengine/godot#60672]
### Godot version

v3.4.4.stable.mono.official [419e713a2]

### System information

Windows 11

### Issue description

Meow.... There is something wrong here:

![debugger-bug](https://user-images.githubusercontent.com/1125150/166123537-c92dfefa-7c25-41dc-a424-825c7083c3ae.gif)

I think the issue is that when you have a getter method but it has an error, this issue happens.

### Steps to reproduce

* Stop at a breakpoint
* Click to an object that has a getter method with error

**Comment by Calinou** [comment]
Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by rohanrhu** [comment]
> @rohanrhu Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

Hiii @Calinou I will when I have time 😊

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
