### ISSUE TITLE
godot online editor just dosen't load on iOS (iPad)

### ISSUE THREAD

**Issue by Alidonis** [godotengine/godot#60687]
### Godot version

3.4.4 stable, web editor

### System information

iOS 15.4.1 , 9th generation ipad,tested on safari/brave browser

### Issue description

once pressing start on the web editor, the website locks without reason, probably just not being able to load.

### Steps to reproduce

1. get an iPad, on the latest stable iOS version
2. open the web editor and press 'start editor'

### Minimal reproduction project

this does not affect projects

**Comment by Alidonis** [comment]
I also just tested it with the ofline editor packag, same results.

**Comment by Calinou** [comment]
iOS 15.3.1 and later have SharedArrayBuffer support: https://caniuse.com/sharedarraybuffer

However, I'd expect the Godot web editor to do something too advanced not supported by iOS Safari.

**Comment by Alidonis** [comment]
That would be an option , if i had a mac. now since apple wants customers to buy a mac before seeing the inspector console, i can't.... any other ideas?

**Comment by Alidonis** [comment]
i could use a understandable guide, if that's avaiable

**Comment by kylewlacy** [comment]
I was able to reproduce this from my iPad Pro (2018). I opened <https://editor.godotengine.org> and clicked "Start Godot editor" with the default version of Godot selected (3.4.4 currently). I checked the iOS Web Inspector via my MacBook and saw the following error in the console show up within a second:

```
[Error] Unhandled Promise Rejection: RangeError: Out of memory
	Memory (godot.tools.js:26:102)
	(anonymous function) (godot.tools.js:26:102)
	(anonymous function) (godot.tools.js:380:645)
	promiseReactionJob
```

I did some cursory searching about the error and a number of results showed up for other WebAssembly projects on iOS. It seems like the amount of Wasm memory requested by Godot currently is just more than iOS is willing to give.

**Comment by Calinou** [comment]
The web editor specifically requests a higher amount of initial memory, and I don't think that can be removed: https://github.com/godotengine/godot/blob/daa055d479916b9fdb9b6cf3bc6aa822f35a2be6/platform/javascript/detect.py#L89-L91

**Comment by aura12434script** [comment]
> J'ai pu reproduire cela à partir de mon iPad Pro (2018). J'ai ouvert https://editor.godotengine.org et cliqué sur « Démarrer l'éditeur Godot » avec la version par défaut de Godot sélectionnée (3.4.4 actuellement). J'ai vérifié l'inspecteur Web iOS via mon MacBook et j'ai vu l'erreur suivante apparaître dans la console en une seconde :
> 
> ```
> [Error] Unhandled Promise Rejection: RangeError: Out of memory
> 	Memory (godot.tools.js:26:102)
> 	(anonymous function) (godot.tools.js:26:102)
> 	(anonymous function) (godot.tools.js:380:645)
> 	promiseReactionJob
> ```
> 
> J'ai fait quelques recherches rapides sur l'erreur et un certain nombre de résultats sont apparus pour d'autres projets WebAssembly sur iOS. Il semble que la quantité de mémoire Wasm demandée par Godot soit actuellement juste supérieure à ce qu'iOS est prêt à donner.

[Error] Unhandled Promise Rejection: RangeError: Out of memory
	Memory (godot.tools.js:26:102)
	(anonymous function) (godot.tools.js:26:102)
	(anonymous function) (godot.tools.js:380:645)
	promiseReactionJob
