### ISSUE TITLE
Better rendering of VS nodes when they are positioned in top to down manner

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#6069]
**Operating system or device - Godot version:**
72748d1363d090f33d5ca6b9c00142b5e8f7d78f

**Issue description** (what happened, and what was expected):
Currently VS layout force on programmer straight horizontal left to right positioning of VS nodes. 
There is nothing wrong with that, but basically every VS script will also need to allow position nodes under each other (lets say new line), currently representation for this scenario is not very readable:
![topdown1](https://cloud.githubusercontent.com/assets/6129594/17479646/ee788884-5d73-11e6-8bf2-d86e85ae8359.png)

![topdown2](https://cloud.githubusercontent.com/assets/6129594/17479650/f1ae57a4-5d73-11e6-88a9-4394f7cf5565.png)

I think there are three ways of solving this,
1. Have lines connection that acts a little more like bezier curves:
![betterlines](https://cloud.githubusercontent.com/assets/6129594/17479813/0c84a032-5d75-11e6-9884-4daf51af6113.png)
2. When there is no way to avoid another VS node, line could get little more alpha in that part:
![betterlines1](https://cloud.githubusercontent.com/assets/6129594/17480054/49e12102-5d76-11e6-8785-8fe1ce66a31c.png)
3. Dynamically move output connection points in response to VS node movement:
![betterlines2](https://cloud.githubusercontent.com/assets/6129594/17479910/92933e86-5d75-11e6-8379-37e8ff072121.png)

Obviously mix of those three would be the best.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by alabd14313** [comment]
It is better to be a way for nodes grouping (with a label node), too.

**Comment by vnen** [comment]
@alabd14313 you can make groups with functions and custom nodes, but this is unrelated to the issue in question.

**Comment by reduz** [comment]
I'll use bezier instead of cosine and make nodes sightly transparent so you
can see the connections on the back. Will also try to see if antialiasing
can be enabled..

**Comment by winipcfg** [comment]
I like flowchart but it looks like people don't like it and prefer a modern presentation

**Comment by djrm** [comment]
i guess this has been solved

**Comment by kubecz3k** [comment]
Agree, it's a lot better now:
![vs_connections](https://user-images.githubusercontent.com/6129594/27970054-a30984a8-634d-11e7-8f92-36f196684815.png)

**Comment by reduz** [comment]
Btw, how are you seeing vs so faf?

On Jul 7, 2017 2:51 PM, "kubecz3k" <notifications@github.com> wrote:

Agree, it's a lot better now:
[image: vs_connections]
<https://user-images.githubusercontent.com/6129594/27970054-a30984a8-634d-11e7-8f92-36f196684815.png>

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/issues/6069#issuecomment-313749706>,
or mute the thread

**Comment by kubecz3k** [comment]
@reduz looks very nice. I'm checking it from time to time, to report some new bugs :) But haven't done in it anything yet. Guess after porting project to 3.0 I will implement some small functionality purely in VS so I will be able to give better feedback. Also my personal hopes for using VS from my programmer perspective is to write most of the logic traditionally and link it visually in some specific scenarios, like AI based on some kind of visual FSM.
