### ISSUE TITLE
[4.0] VisualShaders: Alpha output disappeared in CanvasItem shaders

### ISSUE THREAD

**Issue by DrCanvas** [godotengine/godot#60694]
### Godot version

v4.0.alpha7.official [3e9ead05f]

### System information

Windows 10

### Issue description

Alpha output is not shown in **CanvasItem** shaders (probably after #60175):
![alpha 7 - canvas item](https://user-images.githubusercontent.com/65372494/166155154-d436b47b-afca-4f28-8351-e0fd39d836c3.jpg)

It's strange, since in **Spatial** shaders it's still here:
![alpha7 - node 3d](https://user-images.githubusercontent.com/65372494/166155321-f86cef98-9555-45fa-99de-dc09155f4a94.jpg)

### Steps to reproduce

1. Create a new VisualShader.
2. Select the CanvasItem mode.

### Minimal reproduction project

Not Required.

**Comment by Calinou** [comment]
cc @Geometror

**Comment by Geometror** [comment]
The "Color" node input is now of type Vector4, so the alpha channel is the 4th component of that vector.
I think this was changed in #60439 by @Chaosus:

> Removed "alpha" input ports and combine it with "rgb" to form a Vec4 output

Maybe Chaosus forgot to change it for Spatial shaders :)

**Comment by Chaosus** [comment]
The ALPHA and COLOR of spatial shaders are reference to different built-ins, so there is no error. In the original PR I stated "linked to the same built-in".

**Comment by DrCanvas** [comment]
I don't think it was a good change. In shaders it's quite common to control the alpha channel separately. This change forces you to use more compose/decompose nodes.  It makes everything more complicated and messy.

![shaderVs](https://user-images.githubusercontent.com/65372494/166199433-145dac1c-eb36-4fd1-a5f0-71d016d3b093.jpg)
.

**Comment by Zireael07** [comment]
Seconding @DrCanvas - some of my shaders manipulate only color or only alpha. Actually, manipulating both is somewhat rare across 3 of my projects

**Comment by Chaosus** [comment]
Yeah, probably input ports of Output node need to be expandable, or this change should be reverted
