### ISSUE TITLE
Import armature animation/uv texture from blender

### ISSUE THREAD

**Issue by alabd14313** [godotengine/godot#6070]
Arch Linux
Godot 2.0.4/2.2Alpha
Please open this simple scene that imported from blender through better collada.
There isn't any problem in 2.0.4. but in 2.1 and 2.2 there is a bug in armature and uv textures:
[tree_old.tar.gz](http://www.mediafire.com/download/5ke1999vf1o68ho/tree_old.tar.gz)

**Comment by bojidar-bg** [comment]
I can confirm that it looks pretty weird in 2.1/2.2-alpha, though it is fine 2.0.3
@alabd14313 Which version did you use to import the scene? Can you reimport it in 2.1/2.2?

**Comment by bojidar-bg** [comment]
I'm bisecting...

**Comment by bojidar-bg** [comment]
Ok, here is the result:
````
fe49ac19df042595d9858fec0fad0ee02224bb47 is the first bad commit
commit fe49ac19df042595d9858fec0fad0ee02224bb47
Author: Saracen
Date:   Fri Feb 12 16:27:45 2016 +0000

    Fixed hardware-accelerated skinning support.

:040000 040000 8beecf148af590c8bd332b28e8324ced074c1822 a42a25497f06d9f300b9029c08f1a9770c10d11b M      drivers
````

So, fe49ac19df042595d9858fec0fad0ee02224bb47 should be the problem.

**Comment by bojidar-bg** [comment]
@SaracenOne  Any ideas? :smile:

**Comment by SaracenOne** [comment]
I've got to head out for a bit, but I'll take a look once I get back.

**Comment by bojidar-bg** [comment]
@SaracenOne Ping. :smiley:

**Comment by Calinou** [comment]
This issue is likely no longer relevant as of the switch to OpenGL ES 3.0. Feel free to comment if you can still reproduce this bug on Godot 3.0.2 or newer.
