### ISSUE TITLE
State machine is not blending animations correctly

### ISSUE THREAD

**Issue by guilhermefelipecgs** [godotengine/godot#60710]
### Godot version

4c2a614ad41564ab33eb6515b48e0e5b52ea8b81

### System information

Linux 5.17.5-arch1-1

### Issue description

Consider these two animations:
![Screenshot from 2022-05-02 12-33-26](https://user-images.githubusercontent.com/1387165/166262290-da3868a0-7cdc-4f83-847e-f87fdfa1f736.png)

![Screenshot from 2022-05-02 12-33-29](https://user-images.githubusercontent.com/1387165/166262315-49c6c7a4-9ded-4b66-b96a-1f2f2debd493.png)

This is what is happening:

https://user-images.githubusercontent.com/1387165/166260937-f3ad7883-b868-4a7e-a8b2-322301c9aab3.mp4

But this is what was expected:

https://user-images.githubusercontent.com/1387165/166264704-b70bb0a2-0a34-40de-86de-1efc9008c2d4.mp4

git bisect took me to this commit b06d253920ba540831c0ce078b95c399623be5fc

### Steps to reproduce

Open the minimal reproduction project and see the CollisionShape radius disappear and godot logo flickering.

### Minimal reproduction project

[Bug AnimationTree.zip](https://github.com/godotengine/godot/files/8604099/Bug.AnimationTree.zip)

**Comment by guilhermefelipecgs** [comment]
It also caused a bug with crossfade animation in this example below but this one can only be tested on my branch https://github.com/godotengine/godot/pull/24402.

Expected:

https://user-images.githubusercontent.com/1387165/153728643-f62b9fac-e06b-4aa5-a73a-0cc56a5919c1.mp4

Now:

https://user-images.githubusercontent.com/1387165/166269986-0fb1281a-96cb-4a2c-966b-f339a11ec581.mp4

**Comment by TokageItLab** [comment]
See https://github.com/godotengine/godot/pull/60093. New blend animation needs RESET track for consistency.

**Comment by TokageItLab** [comment]
Closed by https://github.com/godotengine/godot-docs/pull/6322
