### ISSUE TITLE
Ability to find function fast in VS

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#6071]
**Operating system or device - Godot version:**
72748d1363d090f33d5ca6b9c00142b5e8f7d78f

**Issue description** (what happened, and what was expected):
Currently in VS when we want to use function from node, we have to go into inspector tab and deal with a long list of functions. At the moment there is no way to use keyboard to faster find what we are looking for:
![manyfunc](https://cloud.githubusercontent.com/assets/6129594/17480413/17004da6-5d78-11e6-906c-908310aebc68.png)

It would be a lot better if we could use fuzzy matching to find this function faster. It would be even more better if we could do this from inside VS editor, **without** looking for Inspector tab (**which is not visible** anyway when we are working with VS in fullscreen). 
I imagine it could look more or less like this:
![fuzzy_function](https://cloud.githubusercontent.com/assets/6129594/17480506/84b50a44-5d78-11e6-8759-d39a17190f8e.png)

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by TheoXD** [comment]
It's not directly related to VS. This sill have to be done across the entire editor since it's just using PROPERTY_HINT_ENUM, but we can make search appear for item list larger than for example 10 items.

**Comment by kubecz3k** [comment]
@TheoXD I'm not sure what is exact relation of this issue to VS but I think it's the place where this is needed the most. I'm using Godot, for more than a year now and I never had idea to add feature like this, while after 30 minutes with VS I was feeling real pain when I needed to call yet another one function with current interface.

**Comment by reduz** [comment]
I want to implement this via connecting to empty space, then you can choose
to call a function (which can be detected by contex) and open up a nice
dialog for this. This nice dialog could also be used instead of that long
dropdown list.

**Comment by kubecz3k** [comment]
Tested in b276d92c8a63887df011032bc95d98bbb9c51c70 
![vs_drag_drop](https://user-images.githubusercontent.com/6129594/28743424-cee039de-7449-11e7-8b8c-5ec7f19d0c7e.gif)
it's solved now :+1:

**Comment by reduz** [comment]
you can drag to empty space too

**Comment by kubecz3k** [comment]
@reduz not sure, there is some other way than what's on gif? 
Or you meant something like that: 
![emptyspacedrag](https://user-images.githubusercontent.com/6129594/28746398-d97e1252-748b-11e7-9994-c612c5b2f24a.gif)
? 
Actually in that case, what's missing for me is ability to run buildin function, in the menu there is only 'condition' 'switch' 'operator' 'sequence' 'while' and 'return'
