### ISSUE TITLE
Acceleration from constant force grows exponentially

### ISSUE THREAD

**Issue by LucidaDragon** [godotengine/godot#60717]
### Godot version

3.2.3.stable.mono

### System information

Windows 10, GLES 3

### Issue description

Task:
Applying a constant force to a RigidBody2D using add_force and _integrate_forces using a mass of 100 and a force with a magnitude of 1000.

Expected result:
The RigidBody2D will accelerate at 10 units/s^2, as indicated by the force divided by the mass.

Actual result:
Determining the acceleration by storing the previous physics step's velocity, taking the difference with the current velocity, and dividing by the delta time shows that the acceleration is not constant.

### Steps to reproduce

1. Create an empty scene with Node2D at its root.
2. Add a RigidBody2D as a child of the Node2D.
3. Set the mass of the RigidBody2D to a known value.
4. Set the gravity scale of the RigidBody2D to 0.
5. Add a Sprite as a child of the RigidBody2D for visual reference.
6. Add a texture to the sprite.
7. Set the linear and angular dampening for the project to zero.
8. Add the following as a script to the RigidBody2D:

```gdscript
extends RigidBody2D

var force: float = 1000
var last_velocity = Vector2(0, 0)

func _physics_process(delta):
	var stated = force / mass
	var actual = (linear_velocity - last_velocity).length() / delta
	print("Stated: ", stated, ", Actual: ", actual)
	last_velocity = linear_velocity

func _integrate_forces(state):
	state.add_central_force(Vector2(force, 0))
```

### Minimal reproduction project

[MinimalReproduction.zip](https://github.com/godotengine/godot/files/8607110/MinimalReproduction.zip)

**Comment by Calinou** [comment]
PS: Code blocks should use triple backticks like this (with an optional language name for syntax highlighting):

\`\`\`gdscript
code here
\`\`\`

I edited your post accordingly, but remember to do this in the future :slightly_smiling_face:

**Comment by James103** [comment]
Can reproduce in Godot 3.5 beta 4.

From the [documentation](https://docs.godotengine.org/en/stable/classes/class_rigidbody2d.html#class-rigidbody2d-method-add-central-force):
> * void add_central_force ( [Vector2](https://docs.godotengine.org/en/stable/classes/class_vector2.html#class-vector2) force )
> 
> Adds a constant directional force without affecting rotation

Since you're calling `add_central_force` every physics tick, the force vector that's passed in is being added to the total applied force every physics tick; therefore, the acceleration is somewhere around 600 units per second **cubed** instead of the expected 10 units per second squared.

Try calling `add_central_force` only once in `_ready` as shown below and see if that fixes the acceleration (it does on my system).
```gdscript
extends RigidBody2D

var force: float = 1000
var last_velocity = Vector2(0, 0)

func _ready():
	self.add_central_force(Vector2(force, 0))

func _physics_process(delta):
	var stated = force / mass
	var actual = (linear_velocity - last_velocity).length() / delta
	print("Stated: ", stated, ", Actual: ", actual)
	last_velocity = linear_velocity
```

**Comment by Zireael07** [comment]
Another take: many people use _force but want _impulse or vice versa?

**Comment by LucidaDragon** [comment]
@Calinou Thank you for the format changes.

@Zireael07 For my actual use case I am changing the forces every tick, so apply a force once at the start doesn't work in this case.

Your suggestion to use impulse seems counter to the documentation:

> Applies a positioned impulse to the body. An impulse is time-independent! Applying an impulse every frame would result in a framerate-dependent force. For this reason it should only be used when simulating one-time impacts (use the "_force" functions otherwise).

This also seems to go against the apparent purpose of _integrate_forces, which is to accumulate forces acting on a body for every tick.

Additionally applying an impulse in the integrate forces state produces an acceleration of ~6000 as suggested by the documentation with it being tied to frame rate.

My expectation would have been that things like impacts would be added by impulses during physics ticks and things like directional forces (i.e. custom gravity, physics thrusters, etc.) would be with add_force in _integrate_forces. Evidently I may be wrong in that expectation, but then it doesn't seem like there's a middle ground between "a permanent force applied to the object in a particular direction that can not be changed" and "a single-frame impulse applied to an object instantly regardless of delta time".

Am I missing something crucial here?

**Comment by James103** [comment]
Alternatively, reset the total applied force before reapplying the forces. This can be done in `_integrate_forces` at the beginning of the function as shown below:
```gdscript
func _integrate_forces(state):
	self.set_applied_force(Vector2.ZERO)
	state.add_central_force(Vector2(force, 0))
```

**Comment by LucidaDragon** [comment]
@James103 This works perfectly, thank you.
