### ISSUE TITLE
Impossible to bind Control+D on InputMap of Project settings when code editor is in background

### ISSUE THREAD

**Issue by Sygmei** [godotengine/godot#60725]
### Godot version

3.4.3 stable

### System information

ArchLinux

### Issue description

Whenever we try to bind "Control + D" in the "InputMap" section of Project settings, the code editor catches the "Control + D", duplicates the current line and the binding does not show in the keybinding popup.

### Steps to reproduce

- Open code editor
- Open Project Settings (code editor in the background)
- Create new Action
- Create new "Key" binding
- Try to associate "Control + D" keybinding

**Comment by Calinou** [comment]
This is likely fixed in `master` as part of the input propagation rework, but it can't be backported to `3.x`.
