### ISSUE TITLE
Using Viewport as texture with one ColorRect works fine in the editor, but does not work at runtime.

### ISSUE THREAD

**Issue by meowyih** [godotengine/godot#60720]
### Godot version

Both v3.5.beta4.official and v3.4.4 stable

### System information

Window 11 with default project setting

### Issue description

> summary
If we add a ColorRect in viewport and try to use it as a ViewportTexture, it shows in the Godot editor, but won't work at runtime.

> Reproduce using attached project
Open the attached project Godot, you can see a white rectangle at the bottom-left.
Then Press F5 (Play), the rectangle does not show up in the application.
[ReadViewportInColorRectShader.zip](https://github.com/godotengine/godot/files/8608727/ReadViewportInColorRectShader.zip)

### Steps to reproduce

Assume window resultion is 1024x600

1. Create a project and allocate scene as below

－Node2D
－－+Viewport
－－－ +ColorRect

2. Change Viewport size to 1024, 600
3. Change ColorRect size to 100, 100
4. Add another ColorRect below Node2D and rename to ColorRectCanvas

－Node2D
－－+Viewport
－－－ +ColorRect
－ColorRectCanvas

5. Change ColorRectCanvas size to 1024, 600
6. Add shader material for ColorRectCanvas, set shader "Resource -> Local to Scene" to true , and write a shader as below:

shader_type canvas_item;

uniform sampler2D viewport_texture;

void fragment()
{
	vec4 clr = texture( viewport_texture, UV );
	COLOR = clr;
}

7. Assign the viewport_texture to the Viewport under Node2D.

8. In the 2D editor preview, you can see the ColorRectCanvas draws a color rectangle correctly.

9. But if we press F5 (Play), we cannot see anything at the runtime.

### Minimal reproduction project

[ReadViewportInColorRectShader.zip](https://github.com/godotengine/godot/files/8608722/ReadViewportInColorRectShader.zip)

**Comment by timothyqiu** [comment]
Setting the `Viewport`'s Update Mode to Always seems solve the issue.

**Comment by novemberist** [comment]
This is currently also an issue in Godot 4. Setting Viewport's Update Mode to "Always" doesn't help

![Bildschirmfoto vom 2022-06-14 02-40-07](https://user-images.githubusercontent.com/7927471/173469962-1b3625a7-c2ee-4c7b-88be-2ca47d93d2ca.png)

**Comment by Calinou** [comment]
@meowyih Did you find a solution to this problem? If so, please document it here by commenting :slightly_smiling_face:

**Comment by meowyih** [comment]
> @meowyih Did you find a solution to this problem? If so, please document it here by commenting 🙂

As @timothyqiu mentioned, set Viewport's update mode to Always can fix this problem in Godot 3.5. And in Godot 4.0 alpha 15, that solution also works to me. So I closed this issue. The sample project for 4.0 is attached below.

[Issue60720.zip](https://github.com/godotengine/godot/files/9484075/Issue60720.zip)

**Comment by opponent019** [comment]
I seem to be having the same issue with Godot 4.5.1 with Compatibility renderer and having the viewport's update mode set to Always. Works fine in editor but is pink in runtime and I get an error from _setup_local_to_scene that the path to the viewport node is invalid.
