### ISSUE TITLE
Ability to enter inside VS node function with double click

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#6072]
**Operating system or device - Godot version:**
72748d1363d090f33d5ca6b9c00142b5e8f7d78f

**Issue description** (what happened, and what was expected):
When we are working with multiple VS custom function nodes It would be super convenience if VS editor would allow us to double click on a node to enter 'inside'. If the function inside which we are entering is at the same time scene root, it would be the best if new scene tab would be opened.
It would allow us to move within the 'code' very quickly. 
![doubleclickonfunc](https://cloud.githubusercontent.com/assets/6129594/17481320/d8131e2a-5d7c-11e6-9833-773185ec7b44.png)

hint: it would be the best if it would work not only for vs scripts but for ordinary gdscripts as well

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by kubecz3k** [comment]
Tested on b276d92c8a63887df011032bc95d98bbb9c51c70, it's still valid

**Comment by fire** [comment]
As mentioned in the gsoc status report we're working on group visual script node. This is the ability to save groups of visual script nodes as resources and then import as a node.

https://godotengine.org/article/gsoc-2019-progress-report-1-part-1

**Comment by fire** [comment]
Closing this bug in favour of #8046
