### ISSUE TITLE
Ability to copy VS nodes between scripts

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#6073]
**Operating system or device - Godot version:**
72748d1363d090f33d5ca6b9c00142b5e8f7d78f

**Issue description** (what happened, and what was expected):
**UPDATE: it's possible to duplicate nodes with ctrl+D, so only 'between scripts' part is left.**

It would be awesome if we could just select and copy VS nodes (multiple ones as well as single one).
Also, copying nodes should be possible between different VS scripts.

This would allow us to create a 'palette' of the most commonly used nodes so we didn't need to find them in top down menu all the time. It would make working with VS a little more similar how painters work in graphic program, where they are making small palette of colors in a handy place and they are using a sampler when they want to change color.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by reduz** [comment]
Ctrl-D duplicates nodes, it works with multiple nodes.

**Comment by reduz** [comment]
as for between scripts, I guess that should be added yeah, like some sort
of clipboard.

**Comment by kubecz3k** [comment]
@reduz roger! Updated first post title/description to reflect this :)

**Comment by kubecz3k** [comment]
Tested on b276d92c8a63887df011032bc95d98bbb9c51c70, it's solved now

**Comment by eon-s** [comment]
I wonder if this could allow to make #8046 too (or directly solves it?).

**Comment by kubecz3k** [comment]
@eon-s well I haven't found any way to have scripts templates. You need to open script yourself, select some nodes, click ctrl+c. Then you can do ctrl+v in the same script to duplicate or in another one...

**Comment by eon-s** [comment]
@kubecz3k but in the same way that is copied to clipboard could it be saved to a file?
