### ISSUE TITLE
How to solve the problem of sprite rendering order?

### ISSUE THREAD

**Issue by PoisonousGame** [godotengine/godot#60748]
### Godot version

v3.4.4 stable official

### System information

Win11  GeForce GTX1060 6GB

### Issue description

The character (KinematicBody2D3) has 3 sprites, two of which are sword and shield. The sword and shield are located behind the cha sprite at the beginning. I want to play the sword drawing animation, and the sword sprite is located in front of the cha sprite. This effect can be achieved with z_index. However, when the character is placed on the map and moved, due to the z_index rendering problem, the sword and shield are hidden behind the tree
![动画](https://user-images.githubusercontent.com/39994989/166638613-bbdb26e4-03ff-430e-bdb8-592fd8c16503.gif)
![Screenshot 
![Screenshot 2022-05-04 151707](https://user-images.githubusercontent.com/39994989/166638628-fd724dbf-3fb0-4752-9741-3f038f3eb614.png)
2022-05-04 131653](https://user-images.githubusercontent.com/39994989/166638620-f26a0882-8755-4716-91cc-65e40ace90d9.png)
.
![Screenshot 2022-05-04 151707](https://user-images.githubusercontent.com/39994989/166640081-df26aa12-f47d-4301-b7f4-361d2783b0ea.png)
I am wondering if the sprite z_index in the scene can not affect its z_index in the global

### Steps to reproduce

Create a new kinematicbody, then add a few sprites, add animationplay and animate the z_index of one or two sprites. Put the kinematicbody scene under the Ysort node of the map with the tree in it.

### Minimal reproduction project

none

**Comment by Calinou** [comment]
@PoisonousGame Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by PoisonousGame** [comment]
I solved this problem by calling the VisualServer.canvas_item_set_draw_index(sword.get_canvas_item(),index) function in the animation. Now I can call this function to change the rendering order of the sword at different keyframes, e.g. the sword is behind the character at the beginning and in front of the character after the sword is drawn. It would be nice if there was a property to set the rendering order in the animation. Currently, I need to implement it myself.

**Comment by Calinou** [comment]
> It would be nice if there was a property to set the rendering order in the animation. Currently, I need to implement it myself.

This needs a [proposal](https://github.com/godotengine/godot-proposals) to see if it has sufficient community support.

Either way, I'll close this issue as this isn't a bug.
