### ISSUE TITLE
Ability to call VS func for external Node

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#6075]
**Operating system or device - Godot version:**
72748d1363d090f33d5ca6b9c00142b5e8f7d78f

**Issue description** (what happened, and what was expected):
I think there should be VS node which could allow us to make a function call on an VS node which is holding scene with a script. Let me illustrate this:
![callfuncinnode](https://cloud.githubusercontent.com/assets/6129594/17481903/8656c804-5d7f-11e6-9b0b-c3db71f017e4.png)

**If we could have this kind of node together with https://github.com/godotengine/godot/issues/6071 then calling a functions in VS would be a breeze**, just dragdrop node from scene, connect with callFuncNode and type couple of letters with fuzzy matching to find proper function. 

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by kubecz3k** [comment]
After investigation it seems it's possible to call function in object that is declared this way with VS `CallInstance` node, but only for predefined types. There is no VS node which take node from the input and allows to call function wrote by user.

**Comment by TheoXD** [comment]
Somewhat similar to my suggestion as I understood https://github.com/godotengine/godot/issues/5145  Juan really wants to keep godot context based, so selecting a node will close visual editor.

**Comment by kubecz3k** [comment]
@TheHX Drag and drop of regular nodes in VS mode is already working... the issue is about 'new type of visual script block' (that's what I mean every time when Im saying about 'VS nodes'). As far as I was speaking with reduz on irc, there should be that kind of block already and in fact this is a bug.

**Comment by TheoXD** [comment]
I didn't know drag&drop of scene nodes into editors existed, it's buggy as hell but it's working. Simetimes it switches context, sometimes it doesn't.

**Comment by TheoXD** [comment]
BTW you tagged wrong guy xP

**Comment by kubecz3k** [comment]
@TheoXD  hah as always :D

**Comment by kubecz3k** [comment]
@TheoXD yeah it's working, if you are doing your dragging fast it's always working fine for me on my low res screen :)

**Comment by TheoXD** [comment]
I'm even doing it with a stylus, no matter how fast I drag it, it's always a coin flip. Maybe it's frame dependent so it performs differently depending.

**Comment by kubecz3k** [comment]
@TheoXD yeah switching context is a real thing... I think it would be better if editor would switch context only when 'mouse press up' event is finished at the tree with scene nodes.

**Comment by kubecz3k** [comment]
@TheoXD I opened new issue about this https://github.com/godotengine/godot/issues/6079

**Comment by reduz** [comment]
Tried mouse press up long ago and it makes the whole experience feel more
sluggish. For visual script will implement a lock, as I think there is no
other way, gdscript will not lock, but dragging nodes should work already,
did you try it?

On Aug 8, 2016 5:02 PM, "kubecz3k" <notifications@github.com> wrote:

@TheoXD <https://github.com/TheoXD> yeah switching context is a real
thing... I think it would be better if editor would switch context only
when 'mouse press up' event is finished at the tree with scene nodes.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/issues/6075#issuecomment-238337882>,
or mute the thread

**Comment by reduz** [comment]
Ah, maybe we could use mouse up only for when gdscript is being edited and
for main editor switch

**Comment by kubecz3k** [comment]
@reduz dragging basically works, but sometimes it's hard to drag node from scene tab to VS sheet because context is switching. For example spatial node is switching context to 3d editor... while I after very small training dont have any problems with draging spatials to VS sheet, it seems in some environments it's a lot harder. (Or maybe TheoXD is dragging some other nodes?)

**Comment by TheoXD** [comment]
@kubecz3k, it's as you described, dragging a spatial node into VS editor just doesn't always work, no matter how fast I drag it, even if I left click when mouse is on the move.

**Comment by TheoXD** [comment]
I see there is restore_script_editor_on_drag inside scene_tree_dock.cpp that I assume is supposed to switch back to script editor, you can almost see it working as it switches to spatial editor then back to script editor very quickly, but sometimes it just doesn't.

**Comment by kubecz3k** [comment]
solved in b276d92c8a63887df011032bc95d98bbb9c51c70
