### ISSUE TITLE
Godot mono 3.5 beta5 fails to export

### ISSUE THREAD

**Issue by Jupither** [godotengine/godot#60753]
### Godot version

v3.5.beta5.mono.official [815f7fe63]

### System information

Win10.0.19043, Ryzen 4800HS, GTX 1660Ti

### Issue description

Exporting project fails without error message in beta5.
No Data_XYZ is created. For larger (not the included example) project the *.pck becomes only a fraction of its expected size (1.5MB instead of +90MB). 
Tried turning off rcedit & signtool, but no change.
Only tested on Win10.

Loading same project into v3.5.beta4.mono.official [b6968ab06] exports fine.

### Steps to reproduce

Attached project can be exported in 3.5b4, but in 3.5b5 the "data_XYZ" directory is not created.

The project work when run in the editor, but as export the mono-code seems to not be executed. 
E.g. the button do not work in the exported version.

### Minimal reproduction project

[3.5_B5_monotest.zip](https://github.com/godotengine/godot/files/8619767/3.5_B5_monotest.zip)

**Comment by akien-mga** [comment]
This was confirmed by @bruvzg, who fixed it in #60752. I'll keep the issue open and pinned for a couple of days as other users might run into it in 3.5 beta 5.

**Comment by akien-mga** [comment]
Fixed by https://github.com/godotengine/godot/pull/60752.
