### ISSUE TITLE
Font oversampling scales the font size

### ISSUE THREAD

**Issue by Geometror** [godotengine/godot#60785]
### Godot version

4.0dev (11b9435) 

### System information

Windows 10 and Manjaro Linux 21.2.6

### Issue description

When enabling oversampling in the font import settings, the font size changes based on the oversampling factor:

![change factor](https://user-images.githubusercontent.com/50084500/166912705-148e25fa-8fc0-44f2-ad19-a24ec1fbb90b.gif)

Interestingly, this only happens when the font size is equal to the default font size. When changing the font size via the theme override, it looks normal for all values != 16:

![font size ](https://user-images.githubusercontent.com/50084500/166913139-cb46c329-40ad-45b9-a7d2-21822148eabc.gif)

### Steps to reproduce

1. Create a Label.
2. Import an arbitrary font.
3. Change the oversampling factor via the font import settings.
4. Add a font override to your Label and use the imported font there.

### Minimal reproduction project

-

**Comment by akien-mga** [comment]
CC @bruvzg @Calinou
