### ISSUE TITLE
It's hard to D&D nodes from scene tree to VS sheet

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#6079]
**Operating system or device - Godot version:**
Ubuntu 16.04 72748d1363d090f33d5ca6b9c00142b5e8f7d78f

**Issue description** (what happened, and what was expected):
It's possible to drag and drop nodes from scene tree to visual script board. 
Unfortunately there is problem with context switching. While for me relatively fast drag always works fine,  it seems on other devices it's very hard to drag node on VS sheet.  I was talking about this with @TheoXD here: https://github.com/godotengine/godot/issues/6075#issuecomment-238337278 He was surprised it's even possible, and he have real problems with doing this, so it's probably somehow resolution/fps/system dependent.

I think **context should be switched only when 'mouse_press_up' event occurs** inside scene tree tab.

**Comment by kubecz3k** [comment]
I think context should be switched only when 'mouse_press_up' event occurs  inside scene tree tab.

**Comment by TheoXD** [comment]
I'm on Windows 10 but I doubt it's OS related.

**Comment by kubecz3k** [comment]
I tested on a b276d92c8a63887df011032bc95d98bbb9c51c70  It's solved now. You can drag drop to have list of object methods, or hold ctrl to put the reference to object itself :+1: 
![vs_drag_drop](https://user-images.githubusercontent.com/6129594/28743412-95cfb1f6-7449-11e7-90e3-166057ed4940.gif)
