### ISSUE TITLE
No way to set title and executable icon on linux

### ISSUE THREAD

**Issue by Stuffe** [godotengine/godot#60826]
### Godot version

3.3.stable

### System information

Linux Mint 20.3

### Issue description

On windows we can use tools like "ResourceHacker" to change the icon and title of the executable, but there seems to be no way to do this on Linux.

See: https://cdn.discordapp.com/attachments/850737218759032892/971527553850441768/unknown.png

### Steps to reproduce

Export any game to Linux

**Comment by Calinou** [comment]
Linux does not have a concept of executable icons like Windows does. Icons are set using the X11 API by the process itself when running.

**Comment by SysError99** [comment]
If you want to export your application icon on Linux platform, there several ways to achieve it, and it has nothing to do with Godot, or at least if no one going to contribute resource implementing automation, and it does not even apply evenly across distributions and may present more hassles than help.

First, the easiest one, is to create supplement icon to launch your application. The format has `.desktop` file extension. Majority of Linux distributions support this file format (with some has more security restrictions, however both GNONE and KDE support it)

Second, is to pack your Godot game into `AppImage`. This is cleanest way to implement icons but not trivial and does not look right across distributions. Manjaro used to not support its icons but later supported it.

**Comment by Stuffe** [comment]
After Calinou explained it should be working, I realized the issue was with the icon file. It has now been resolved, thank you for the help
