### ISSUE TITLE
Making a material unique with emission enabled will result in incorrect editor colors

### ISSUE THREAD

**Issue by stryker313** [godotengine/godot#60849]
### Godot version

4.0 Alpha 7

### System information

Windows 10 Nvidia GTX 1060 Intel i5 4690k

### Issue description

If you make a unique material on a material with emission enabled, it will glitch out in the editor

https://user-images.githubusercontent.com/83078010/167247342-c0a21dd1-1a6e-445c-83e1-59ad7ee6d929.mp4

When making a copy of the material, pasting to another object, then making unique, the red will turn to white.

In the game, it is fine.

However, the colors are inaccurate in the editor

When you exit the editor and return, the colors will be fine again.

The editor issue only exists when you make a copy of a material, then make that material unique.

### Steps to reproduce

Create 2 meshes
Create a material3d on 1 mesh
Set emission to true
Set albedo and emission color to color other than white
Copy material from mesh 1 to mesh 2
Make material on mesh 2 unique
Editor will glitch the colors out

Again, this does not affect the game. The colors are correct in game. However, the editor is inaccurate.

### Minimal reproduction project

[MaterialBug (2).zip](https://github.com/godotengine/godot/files/8644781/MaterialBug.2.zip)

**Comment by codespren** [comment]
Bug happens here too but not only in the editor but in game also when making material unique from the code. macOS, AMD Radeon Pro 5500M.

Code:

`		scene = (PackedScene)ResourceLoader.Load<PackedScene>("res://data/scenes/scene.tscn");
		meshInstance = (MeshInstance3D)scene.Instantiate();
		SphereMesh mesh = (SphereMesh)meshInstance.Mesh.Duplicate();
		meshInstance.Mesh = mesh;
		StandardMaterial3D material = (StandardMaterial3D)mesh.SurfaceGetMaterial(0).Duplicate(); // X
		mesh.SurfaceSetMaterial(0, material);
		AddChild(meshInstance);

                StandardMaterial3D material = (StandardMaterial3D)meshInstance.Mesh.SurfaceGetMaterial(0);
                material.EmissionEnabled = true;
`

After that the emission is very bright, basically white. If I remove Duplicate() from the line marked with X it works correctly.

**Comment by elvisish** [comment]
This still seems to be an issue, duplicating a material from the mesh at runtime and setting it as a material override, then turning emission on just shows solid white.

**Comment by solitaryurt** [comment]
Experiencing this same bug.

**Comment by elvisish** [comment]
> I wonder if https://github.com/godotengine/godot/pull/77326 helps this at all. It turns out we weren't properly freeing materials when geometry was duplicated 

Is this available for testing? I gave up trying to get emissions to show as non-white unless it was set to 0.03, and then it looks really weak and not emissive at all. It definitely sounds like having two of the same material simultaneously would cause something like this.

**Comment by Calinou** [comment]
> Is this available for testing? 

It's not in 4.0.3, but you can build the `master` branch or use the artifacts linked in that PR: https://docs.godotengine.org/en/latest/contributing/workflow/testing_pull_requests.html

**Comment by FelixNemis** [comment]
Aha! I've narrowed down what causes this I think.
I got the exact same broken state on a new material that I manually copied all properties on, so I tired not setting some emission related properties and found out it was emission_texture that makes it happen.

And yup, you can reproduce the bug in the editor too by simply setting a material's emission texture and then clearing it.
So I guess something is going wrong when it's being set to null

**Comment by FelixNemis** [comment]
So yeah a workaround for this is to create a new material and copy all the properties into it except not the emission texture unless you have one.

**Comment by spacehare** [comment]
i was able to get this working by setting a full-black emission texture.
![image](https://github.com/godotengine/godot/assets/38092970/e5426422-a30c-4b26-9501-245112e7eac7)

**Comment by elvisish** [comment]
> i was able to get this working by setting a full-black emission texture. ![image](https://user-images.githubusercontent.com/38092970/271098236-e5426422-a30c-4b26-9501-245112e7eac7.png)

Afraid this didn't work for me:
![image](https://github.com/godotengine/godot/assets/16231628/ef368cd2-6092-436c-a070-7b066c909cf4)
(how it should look)
How it looks in game:
![image](https://github.com/godotengine/godot/assets/16231628/babe6d02-8205-4f70-832d-035731fddd1c)
