### ISSUE TITLE
Clicking on unsaved/unique material after creation results in unpredictable behavior

### ISSUE THREAD

**Issue by stryker313** [godotengine/godot#60847]
### Godot version

4.0 Alpha 7

### System information

Windows 10 Nvidia GTX 1060 Intel i5 4690k

### Issue description

When you create a new material, save the scene, exit your project, re - enter your project, and click on the material in the inspector,
the material acts unpredictably.

https://user-images.githubusercontent.com/83078010/167246290-b40d79ad-685c-402e-84e5-1488345218f1.mp4

When you initially create a material, you can click it, and it will expand and contract

However, if you exit your project, and re -enter, when you click on a material, it will open to a seperate inspector window, making
it really awkward to edit materials.

### Steps to reproduce

Create a scene
Create a mesh
Create a material
Click on it a couple times to verify that it will expand and contract.
Exit your project
Re - Enter your project
Open your scene
Click on the material again
The material will open a seperate inspector window, instead of expanding and contracting.

### Minimal reproduction project

[MaterialBug.zip](https://github.com/godotengine/godot/files/8644749/MaterialBug.zip)

**Comment by PucklaMotzer09** [comment]
I can not reproduce this bug in v4.0.beta.custom_build [bbac8198f]. If I follow the reproduction steps the Material opens the same way as it does when creating it.

**Comment by akien-mga** [comment]
Thanks for testing. Closing as fixed. Please comment if this is still reproducible.
