### ISSUE TITLE
2.1 rc2 crashes on macOS Sierra beta

### ISSUE THREAD

**Issue by pgregory** [godotengine/godot#6084]
**Operating system or device - Godot version:**
macOS Sierra beta
Godot 2.1 rc2

**Issue description** (what happened, and what was expected):
When running Godot 2.1 on macOS Sierra beta, it crashes immediately

**Steps to reproduce:**
Just run 2.1 rc2 on Sierra

**Link to minimal example project** (optional but very welcome):

Attached is the crash report dump.
[crash.txt](https://github.com/godotengine/godot/files/408591/crash.txt)

**Comment by akien-mga** [comment]
This part of the crash report seems to hint at a possible issue due to #6021:
> 6   com.apple.AppKit              	0x00007fff89386126 -[NSStatusBar init] + 186

If it works on current non-beta OSX, it's likely a bug/badly obsoleted instruction in Sierra though. CC @marcelofg55.

**Comment by marcelofg55** [comment]
Hi pgregory, can you try this patch: https://gist.github.com/marcelofg55/f04b3472a9b7d5999f10a54e0135f013
I don't have a Sierra beta to test, I'm running Yosemite myself.

**Comment by pgregory** [comment]
Can confirm that patch works when applied to the code at commit d4c44485d... on macOS Sierra. I built with scons platform=osx arch=x64 and ran clean, showed the same crash as reported. Applied the patch and built again, worked fine. 

Haven't extensively tested, but it loaded my WIP game and it seemed to work fine.

Paul

**Comment by akien-mga** [comment]
Awesome work guys. @marcelofg55 If you can make a quick PR, I'll make a hotfix build for OSX before releasing 2.1-stable (won't redo the tag though, I don't think it would be worth the trouble as it's already several hours old and many users have noticed it).

**Comment by reduz** [comment]
Heh seems we already have 2.0.1 material :P

**Comment by reduz** [comment]
Sorry, 2.1.1

**Comment by akien-mga** [comment]
Hehe yeah. I'm including the fix in the official OSX binaries though, that can't hurt. People building 2.1-stable from source would still have the bug, but well, it's only on Sierra beta :)

**Comment by akien-mga** [comment]
And it's Murphy's Law, there must always be a somewhat critical bug discovered just after a release :p

**Comment by akien-mga** [comment]
Actually I'll release 2.1 without this fix even for the OSX build, as apparently Travis is playing against me: https://travis-ci.org/GodotBuilder/godot-builds/builds/150981798
The builds run fine, but the deploy step fails due to missing ruby... though it worked this morning and all the days before that. I'll replace the binaries for the sake of it as soon as I can get a proper travis deploy.

**Comment by akien-mga** [comment]
So, Travis finally started behaving so I packaged the new OSX binaries (both for the editor and the export templates) and pushed them online. It's too late for the likely big number of users who already downloaded 2.1-stable, but at least for new users it will be fixed. So if we get duplicates of this bug report, we can advise users to try to redownload from the official website to get the fixed version.

**Comment by pgregory** [comment]
Can confirm the current binary works fine on macOS Sierra beta. Thanks everyone.
