### ISSUE TITLE
ord function not recognized

### ISSUE THREAD

**Issue by navy-cap-echo** [godotengine/godot#60857]
### Godot version

v4.0.alpha7.official [3e9ead05f]

### System information

Windows 10

### Issue description

The function ```ord``` is not recognized, giving the following error : 
```**Function "ord()" not found in base self.**```

### Steps to reproduce

Create script
In the function ```_ready()```, add ```print( ord("A" )  )```

**Comment by Chaosus** [comment]
`ord` has been replaced by `unicode_at` String's method: so you need to just write "A".unicode_at(0)

**Comment by navy-cap-echo** [comment]
Ok Thanks
Just do not forget to update the documentation accordingly.

**Comment by akien-mga** [comment]
> Ok Thanks Just do not forget to update the documentation accordingly.

Can you point us at the documentation you refer to?

**Comment by navy-cap-echo** [comment]
Sorry for the response time.

In almost all languages, you have the chr() and the ord() function referenced together, because they are opposite ! And if you use one, you normally use the other too !

IMHO, it would be nice to have the information 

> the ord has been replaced by unicode_at String's method: so you need to just write "A".unicode_at(0)

with the `char()` function [see doc](https://docs.godotengine.org/en/latest/classes/class_@gdscript.html?highlight=ord%20char#class-gdscript-method-char) 

BTW. It's so weird to have the char() function which is compatible with ASCII code but not it's opposite the ord().
Couldn't you make the ord() function to encapsulate the unicote_at(0) call ?
