### ISSUE TITLE
Current DB missing/not exposed from/in AudioStreamPlayer3D

### ISSUE THREAD

**Issue by stryker313** [godotengine/godot#60850]
### Godot version

4.0 Alpha 7

### System information

Windows 10 Nvidia GTX 1060 Intel i5 4690k

### Issue description

There is no property to access an AudioStreamPlayer3D's current DB value.

In certain audio visualizers, the audio server is used to get the current DB values.
Audio server has various functions to get DB output, however, that is for the generalized sum of all audio in a given bus.

Despite that the waveforms are visual in a stream, which could correlate to some form of output
![Desktop Screenshot 2022 05 07 - 05 13 50 95](https://user-images.githubusercontent.com/83078010/167247702-375f5a76-2a61-4d22-83b3-870f5d3bc446.png)

there is no option to see what the current db output is for a given AudioStreamPlayer3D node.

### Steps to reproduce

1. Create an AudioStreamPlayer3D node
2. Try to access the current DB value from a playing node. You can't/it is not exposed. You can only access it from the AudioServer; however this will be the summation of ALL sounds going into a particular bus, not the single node you want to get values from.

### Minimal reproduction project

No project needed

**Comment by Calinou** [comment]
Closing, as feature proposals should be discussed on the [Godot proposals](https://github.com/godotengine/godot-proposals) repository. This repository is now used for bug reports only.

Make sure to follow the proposal template when opening a new proposal – don't just copy and paste the text you wrote in this issue.
