### ISSUE TITLE
Unable to update shader uniforms for tiles in TileMap

### ISSUE THREAD

**Issue by damasko** [godotengine/godot#6085]
Hi, i'm confused about how TileMap works. I have a shader that receives some parameters, when i configure the scene i'm able to set the shader uniforms, but after export it to a tilemap and add it to my scene, the methods for get a tile just returns a vec2 with tile position, so i cannot update the shader uniforms anymore.
What am I doing wrong?

**Comment by eska014** [comment]
The shader parameters are set from the Material. You access the material of a tile through its TileSet:

```
# Retrieve TileSet
var tileset = tilemap.get_tileset()

# Retrieve ID of tile within TileSet
var tile_id = tileset.find_tile_by_name( 'wall' )

# Access material
tileset.tile_get_material( tile_id ).set_shader_param( 'param_name', value )
```

**Comment by damasko** [comment]
Thanks for the response. If i understood correctly, all tiles with the same id shares the material and changes in a tile may affect the repeated tiles. To be more precise, if i want to self-illuminated a tile with a normal map based in a light position, color, etc, will this changes affect other tiles in the map?

**Comment by eska014** [comment]
All tiles with the same ID share one material, one shader and the values of uniforms.

If you want differing normal maps for the same tile, you'll have to duplicate the tile in the tileset to split it into several IDs (or detect which normal map to use from the shader, if the data available in the shader is sufficient).

**Comment by MarianoGnu** [comment]
ligths will affect every tile independently, but you if you want to change an uniform in an specific tile, every tile will get the change too.

**Comment by damasko** [comment]
Ok i got it! Thanks to all for the responses.

**Comment by MarianoGnu** [comment]
I'll close this issue for now, if there's something wrong with corrent implementation i'll rwopen it? But this is the expected behaviour
