### ISSUE TITLE
Acessing onready variables from extended script returns null

### ISSUE THREAD

**Issue by stryker313** [godotengine/godot#60852]
### Godot version

4.0 Alpha 7

### System information

Windows 10 Nvidia GTX 1060 Intel i5 4690k

### Issue description

Lets say you have an "Item" class
![Image3](https://user-images.githubusercontent.com/83078010/167248291-07528aa2-8182-4eee-a958-656839bd654b.jpg)

Base scene is Item
Attached script is Item
class_name is Item

you set an onready variable; lets call it item_property1

item_property1 = 1

You instance scene "Item" in a new scene
![Image4](https://user-images.githubusercontent.com/83078010/167248298-e24bc564-cebe-4253-8aea-fce5d7d56471.jpg)

You unattach the script, and attach a new script.
Lets call it "ItemBall"
"ItemBall.gd" extends from "Item.gd".
Therefore, in this new scene, lets call it ItemBall.
You should be able to access the properties in "Item.gd"
However, if you try to, it will return null.
![Image5](https://user-images.githubusercontent.com/83078010/167248315-9e10c153-f502-4dd2-9481-9ecd38693fff.jpg)

This issue has existed in multiple Godot 4 versions, but definitely prevalent in Alpha7.

It will be fixed if you remove onready from variable names in the base class, however, this is problematic.

https://user-images.githubusercontent.com/83078010/167248382-94108c1c-7a9a-4a37-ac84-05be81124173.mp4

### Steps to reproduce

Create a base scene (Item.tscn)
Create a script for this scene (Item.gd)
Give it a basic class_name (Item)
Instance this scene in a new scene.
Save this scene as (ItemBall)
Unnattach the script
Attach a new script (ItemBall.gd)
extend this script from Item.gd
Try to access properties in Item.gd, they will return null (Run itemBall.tscn, it will try to print Item.gd property)

### Minimal reproduction project

[ScriptExtensionBug.zip](https://github.com/godotengine/godot/files/8644820/ScriptExtensionBug.zip)

**Comment by Lielay9** [comment]
At least for me, if the extended class has either _ready() or any onready -variables, the base _ready() will be overriden, which in return means no onready-calls i.e. variables remain unassigned. To counteract it, one must call the _ready()-method of the base class from the extended:

Base class:

![image](https://user-images.githubusercontent.com/40064911/167295357-ae492a0e-af69-4384-9e36-0ae5101ded3e.png)

Extended Class:

![image](https://user-images.githubusercontent.com/40064911/167295430-0c39baf3-9ae2-46e9-9067-57db2883c3ba.png)

If this is intended, as it probably should be (as it is a basic form of overriding), the caveats of using onready-variables could be documented.

**Comment by KoBeWi** [comment]
Yes, it's a duplicate.
btw you can use `super()` instead of `super._ready()`.
