### ISSUE TITLE
Language server disconnects on Linux

### ISSUE THREAD

**Issue by claychinasky** [godotengine/godot#60869]
### Godot version

Godot 4.0alpha7

### System information

popOS(ubuntu) 22.04, RTX 2080, Vulkan

### Issue description

Language server not able to properly connect client vscode extension, vim, emacs when using external editor setting turned on (on popOS(ubuntu based) and Solus Linux)
The same Godot version and same external editors with extensions works on Windows 10 without a problem.

In vscode, notification pops up, giving an error that LSP connection has failed, forcing to reconnect to LSP server gives this errors in Godot.
```
[LSP] Connection Taken
[LSP] Disconnected
```
I wanted to debug the TCP connection via vscode extension debugger verbose mode but failed to do so. Because I have no experience how it works.

### Steps to reproduce

Create a new project with Godot 4.0alpha7
Create a node2D and attach a gdscript
Set use external editor in settings
Open vscode with godot-tools extension installed
Navigate to folder that project exists

**Comment by StrayDragon** [comment]
Same issue here, macOS Monterey version 12.2.1.

And how to enable LSP verbose logging, I try to pass `--verbose` when open it but see nothing useful messages about LSP

**Comment by StrayDragon** [comment]
Hey, I just tested the problem on Win10 and MacOS with [Godot4-alpha8](https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-8) and [VSCode godot-tools extension (v1.3.0)](https://github.com/godotengine/godot-vscode-plugin/releases/tag/1.3.0), this problem has been solved, Linux should work normally too, please try it on new alpha version.

**Comment by akien-mga** [comment]
Indeed, this was a bug in alpha 7, should be fixed in alpha 8.
