### ISSUE TITLE
Implement version check for export templates

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#6086]
**Operating system or device - Godot version:**
Any OS, Godot 2.1-stable.

**Issue description** (what happened, and what was expected):
Many users forget to update their export templates when trying a new version of Godot (especially testing releases such as betas and RCs) and end up facing crashes in their exported games.

The editor should have a way to check the version of the export templates, and refuse them if they don't match the editor version.

Alternatively, we could enforce as of 2.2 that templates should be installed in a versioned path, and the editor would only look into the versioned path that matches its version. This would allow to use several versions of Godot with templates concurrently.

**Comment by bojidar-bg** [comment]
Trello card links #3341 though.

**Comment by reduz** [comment]
We forgot to do it  for 2.1.. lets move it for 2.2

**Comment by akien-mga** [comment]
Done already for 3.0 several months ago.
