### ISSUE TITLE
Node2D and Spatial .to_world/.to_local(Vector2/Vector3) methods

### ISSUE THREAD

**Issue by WalasPrime** [godotengine/godot#6087]
I have come across this issue/idea some time ago, fortunately it wasn't a big project, but now I've noticed this again: there are no "simple" methods for space-vector operations for nodes (jumping between local and global coordinate system with raw vectors). There is a lot of methods for translating and looking_at etc. but imagine this simple scenario:
1. An enemy with an Area2D is walking around the scene, listening for objects
2. Player enters the Area2D, a script receives a proper signal
3. The enemy should now raycast to check if the player is really visible
4. RayCast2D requires a local-space cast coordinate, proper calcuation would be `aimPoint = to_local(PlayerObj.get_global_pos())`

Since there is no function like that the dev has to figure out some matrix math to properly do this, basically wasting time and probably writing buggy code.

My suggestion is to implement four new methods:

```
Vector2 Node2D.to_local(Vector2)
Vector2 Node2D.to_world(Vector2)
Vector3 Spatial.to_local(Vector3)
Vector3 Spatial.to_world(Vector3)
```

`to_local()` transforms a vector to local coordinate system - eg. `to_local(get_global_pos()) -> (0,0)`
`to_world()` transforms a vector to global coordinate system - eg. `to_world(Vector2(0,0)) -> =get_global_pos()`

This would help a lot with game logic that does some more analytic work for other purposes than "looking at" (or at least would enable things like "look at the object, but try to predict it's destination in 50 ms" -> `look_at(Target.to_world(velocity*prediction_time)))`.

Garry's Mod's Wiremod Expression2 language had those two little methods on vectors, thanks to those I never really had to do any matrix math at all. Kind of missing them here.

**Comment by Heybye44** [comment]
Will this be added in Godot 3.0?
