### ISSUE TITLE
Wrong presentation when erased the last tile by right click

### ISSUE THREAD

**Issue by dkl78167816** [godotengine/godot#60883]
### Godot version

3.4.4 stable_win64

### System information

windows11

### Issue description

When I using right click to erase tiles, the last tile is erased but still exist in 2D editor.
![image](https://user-images.githubusercontent.com/32244400/167289658-f71aa8ac-a323-4108-a006-972cbd15becd.png)

If I change to other node, the tile goes.
![image](https://user-images.githubusercontent.com/32244400/167289726-77f8fdf2-a60d-4cfd-92a1-37aeedc923ee.png)

### Steps to reproduce

I am a newbee here, feel free to close it if I just make a stupid mistake.
PLZ! :)

**Comment by Calinou** [comment]
@dkl78167816 Did you find a solution to this problem? If so, please document it here by commenting :slightly_smiling_face:
