### ISSUE TITLE
OS.execute should output PackedByteArray?

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#60897]
### Godot version

v4.0.alpha7.official [3e9ead05f]

### System information

windows10 64bit

### Issue description

When I execute my PowerShell command on PowerShell's window, it output like this:
![1](https://user-images.githubusercontent.com/35988767/167334470-56649817-950f-4bd4-afd3-5f1dc1f9b67a.PNG)
And I coding GDScript like this:
![2](https://user-images.githubusercontent.com/35988767/167334545-6736547f-3b04-4b93-92f1-9335cccf2f6d.PNG)
But It prints like this:
![3](https://user-images.githubusercontent.com/35988767/167334597-10641820-2ebd-4f5e-84f0-c207e096980e.PNG)
Because PowerShell return not valid UTF-8, so I think maybe OS.execute should output PackedByteArray and I can code like this for solve this problem:
![4](https://user-images.githubusercontent.com/35988767/167334955-0fab997e-6e8b-434b-978a-86ce23305796.PNG)

### Steps to reproduce

Please run the reproduction project

### Minimal reproduction project

[OsExecTest.zip](https://github.com/godotengine/godot/files/8648569/OsExecTest.zip)

**Comment by timothyqiu** [comment]
> Because PowerShell return not valid UTF-8

FYI: This behavior is not limited to PowerShell, using Command Prompt has the same issue if I remember correctly.

As the default output encoding on Windows is system locale dependent, I seems that we should either use `PackedByteArray` instead of `String`, or find a way to retrieve the "Unicode" output.

**Comment by bruvzg** [comment]
`PackedByteArray` won't help, Windows console output default to ASCII, so it's not sending full characters through the pipe.
Normally, encoding can be set be the shell (using `chcp` command) or app that's writing to the console `SetConsoleOutputCP`, but seems like it can't be set by the parent process.
