### ISSUE TITLE
Option to keep mouse cursor inside window boundaries

### ISSUE THREAD

**Issue by probedrone** [godotengine/godot#6091]
**Windows 7 - Godot version: V2.1 RC1**

Sorry for not including much information on this, but Godot desperately needs a way to lock
the mouse window inside a window without it making the cursor and mouse stuck in the center of the screen.

This will help both developers and end users and keep away an immense amount of frustration.

Thank you

**Comment by vnen** [comment]
As a workaround you could use [`Input.warp_mouse_pos()`](http://docs.godotengine.org/en/latest/classes/class_input.html#class-input-warp-mouse-pos) to move the mouse when it leaves the window boundary, though I think this requires polling since I can't find a signal emitted when the mouse leave the window (which could also be a good addition).

**Comment by reduz** [comment]
Problem is that, even when I know all the datatypes, I don't understand
what the icons are, and there inst really any way to associate them to
something.

This is why I gave up in icons in the first place and used small text. As
pretty as they look, I don't feel they are an improvement in this case but
quite the contrary.

**Comment by vnen** [comment]
@reduz, you replied to the wrong email :stuck_out_tongue_closed_eyes:. I guess you meant to post on #6082.

**Comment by probedrone** [comment]
Either way just warping is very buggy in of itself and an inefficient way to achieve it. 
either way it would be a much needed addition to include a mouse in window capture. 
Especially for games that make heavy use of the mouse.

**Comment by bojidar-bg** [comment]
This was seemingly added in #7162, what's left?

**Comment by mrcdk** [comment]
PR https://github.com/godotengine/godot/pull/7162 caused this issue https://github.com/godotengine/godot/issues/10949

**Comment by akien-mga** [comment]
Fixed by #7162.
