### ISSUE TITLE
Document using GPUParticles2D collision

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#60910]
*Related to https://github.com/godotengine/godot/issues/60909.*

### Godot version

4.0.alpha7

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 510.60.02)

### Issue description

GPUParticles2D collision isn't implemented yet (unlike in GPUParticles3D):

![image](https://user-images.githubusercontent.com/180032/167512300-554be04a-637c-4e3f-a0b0-92affea0dbff.png)

### Steps to reproduce

- Look for GPUParticles2D collision shape nodes in the Create New Node dialog.

### Minimal reproduction project

N/A

**Comment by MightiestGoat** [comment]
The 2D particles system is rendered through the 3D particles system. Should I separate them?

**Comment by MightiestGoat** [comment]
The 2D particles are rendered through the 3D particles system. Should I separate them?

**Comment by clayjohn** [comment]
2D particle collisions were already added in https://github.com/godotengine/godot/pull/48894 so I am marking this as a documentation issue.
