### ISSUE TITLE
AABB::Grow incorrect doc or code

### ISSUE THREAD

**Issue by profelis** [godotengine/godot#6092]
**Operating system or device - Godot version:**
All

**Issue description** (what happened, and what was expected):
AABB.grow_by increase double amount https://github.com/godotengine/godot/blob/a895e2e372c9df2a9972f38134ae0ea9c8bf45a8/core/math/aabb.h#L389-L391

[Documentation version](http://docs.godotengine.org/en/latest/classes/class_aabb.html#class-aabb-grow) 
> Return a copy of the AABB grown a given amount of units towards all the sides.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by reduz** [comment]
yes, that's exactly what it does, and the code is fine

**Comment by profelis** [comment]
Hm, my bad. Thanks

**Comment by bojidar-bg** [comment]
@profelis The trick is that you are pushing each side by a given amount, so you have to move the start and the end respectively. But since it is size, not end, you would move it by twice the amount, to account for the changed position.
