### ISSUE TITLE
[BUG] 2.1 stable has made nodes/sprites slightly turn

### ISSUE THREAD

**Issue by lewislepton** [godotengine/godot#6093]
**Operating system or device - Godot version:**
mac osx yosemite
godot 2.1

**Issue description** (what happened, and what was expected):
the walls in my recent project have seemed to have started to lean a bit, really spinning slightly. ive given some screenshots to show. this was not the same in the RC2 release. but it shows this slight imperfection in the walls

<img width="919" alt="screen shot 2016-08-09 at 22 24 10" src="https://cloud.githubusercontent.com/assets/11299322/17534227/14ddd0e4-5e80-11e6-8eb5-254cf201cd9b.png">

<img width="901" alt="screen shot 2016-08-09 at 22 24 14" src="https://cloud.githubusercontent.com/assets/11299322/17534229/1975e524-5e80-11e6-92bb-8689209f0532.png">

**Comment by reduz** [comment]
this is seriously weird, do you think you could make a simple test project?

**Comment by lewislepton** [comment]
ok. ill try and get something done tonight for you

**Comment by reduz** [comment]
thanks!

**Comment by lewislepton** [comment]
hm. i have a feeling its from projects made in RC2. because a clean project in stable 2.1 seems fine. weird

**Comment by lewislepton** [comment]
i did just make a quick project, clean from 2.1 and seems fine. though the RC2 one is still odd

**Comment by lewislepton** [comment]
yeah. i think it has to do with RC2 and stable. i just started again in stable. all fine now. lucky just started the project, so no big deal

**Comment by Sslaxx** [comment]
Need to make the disclaimers about not using pre-release versions for actual projects more prominent, perhaps?

**Comment by akien-mga** [comment]
I don't see a reason why RC2 would cause such an issue. There were only a handful of fixes between RC2 and stable.
