### ISSUE TITLE
CSV can't change the result

### ISSUE THREAD

**Issue by Kakcalu13** [godotengine/godot#60934]
### Godot version

v3.4.stable.official [206ba70f4]

### System information

Linux 20.04 (had this issue from M1 and Windows 10)

### Issue description

I was expecting it to be able to read the new data from csv every time. See here video (Stop at 10 seconds, anything further is just repeated and show how quick it is)

https://user-images.githubusercontent.com/65916520/167722748-3a89ced5-21b2-46ef-9590-1ac59ad9dc23.mp4

SO when I export it to website. See here

https://user-images.githubusercontent.com/65916520/167723525-d72aed57-775b-4506-af16-df8b60a70ee9.mp4

### Steps to reproduce

1) export the project to html/ or in the root (whichever)
2) `http-server` (from npm)
3) Open `127.0.0.1:8080` in your browser.
4) Update csv_data randomly. See it makes no difference. 

### Minimal reproduction project

[delete_this.zip](https://github.com/godotengine/godot/files/8665076/delete_this.zip)

**Comment by Calinou** [comment]
This is likely due to browser caching the response data. You need to configure the web server so it does **not** cache the CSV file that is sent to the browser. This is typically done by configuring the response headers to contain some kind of no-cache directive, or shorten the expiration delay.

**Comment by Kakcalu13** [comment]
Your answer leads me to solved the main goal which I was originally trying to fix in first place. This doesn't resolve with the current issue but since it solved the goal, this is no longer an issue for me. Thank you so much for your quick reply!

Closing this now
