### ISSUE TITLE
When duplicating an area3d with collisionshape inside, the shape doesn't show on the editor

### ISSUE THREAD

**Issue by alex9099** [godotengine/godot#60952]
### Godot version

4.0 alpha8

### System information

Arch linux, Nvidia 1060 (laptop), vulkan

### Issue description

When duplicating an area3d node (with a collision shape defined) on the tree it will only show the shape if i hit the collisionshape3d node

### Steps to reproduce

Add a area3d

Add a collisionshape inside of it

Set a shape on the collisionshape (in this case i set boxshape3d)

Duplicate the area3d (which would also duplicate the collisionshape with it)

Move the area3d node -> no shape will be shown until pressing the collisionshape node on the tree

**Comment by Calinou** [comment]
@alex9099 Can you reproduce this on 3.4.4?

**Comment by alex9099** [comment]
I can't reproduce that bug on v3.4.4.stable.official

![image](https://user-images.githubusercontent.com/7517045/168025270-d5ebb6b3-9138-4e6d-916f-4e3ca278b57d.png)

![image](https://user-images.githubusercontent.com/7517045/168025424-a07ef52f-41e1-437f-9c9c-cd653b89ccf9.png)


(3.4.4 vs 4.0alpha8 after dupplicating)
