### ISSUE TITLE
Typed PackedVector2Array variable silently converts any non-Vector2 assigned element to `Vector2(0, 0)`

### ISSUE THREAD

**Issue by BeayemX** [godotengine/godot#60969]
### Godot version

v4.0.alpha.custom_build [917fd6574]

### System information

Linux Mint - Vulkan API 1.2.131 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1080

### Issue description

I ran into the issue when using `Geometry2D.merge_polygons` and assigned the return value to a falsely typed variable.

**I think it's better to jump to the reproduction steps to understand it.**

I have a function that returns an `Array` of `PackedVector2Array`s.
When the return value is assigned to a **correctly** typed variable everything works as expected.
When the return value is assigned to an **incorrectly** typed variable the array becomes `[(0, 0)]`, without throwing any error.

I am not sure if this is expected or a bug.
I also don't know if this has been reported previously because I didn't quite know what to search for.

### Steps to reproduce

This code

```gdscript
func _ready():
	var arr : Array = get_array()
	var pack : PackedVector2Array = get_array()

	print(arr)
	print(pack)

func get_array() -> Array:
	var pack = Array()

	var arr1 = PackedVector2Array()
	arr1.append(Vector2(1, 1))
	arr1.append(Vector2(2, 2))
	pack.append(arr1)

	return pack
```

produces this output:
```
[[(1, 1), (2, 2)]]
[(0, 0)]
```

**Comment by akien-mga** [comment]
I agree that this should return an error.

Simpler reproducer:
```
var pack : PackedVector2Array = [PackedVector2Array([Vector2(1, 1), Vector2(2, 2)])]
print(pack)  # [(0, 0)]
```
Or even:
```
var pack : PackedVector2Array = [1, 2]
print(pack)  # [(0, 0), (0, 0)]
```
Or:
```
var pack : PackedVector2Array = [self]
print(pack)
```

So any element, whatever its type, is converted to `Vector2(0, 0)` if it's not a Vector2 already.
