### ISSUE TITLE
4.0.alpha8 crashes on startup on macOS unless started via Rosetta

### ISSUE THREAD

**Issue by yedpodtrzitko** [godotengine/godot#60973]
### Godot version

4.0.alpha8 (official)

### System information

MacOS 11.6.5, MacBook Air (M1, 2020)

### Issue description

- Godot crashes as soon as it's opened
- crash does not happen when it's opened via Rosetta
- previous version (4.0.alpha7) works fine too
- traceback from the crash dialog (too long for insert it directly here): https://pastebin.com/g3x9gL6G

### Steps to reproduce

- open the editor in native mode (not via Rosetta), that's it

**Comment by Ansraer** [comment]
Alpha 8 not working on macos is a known bug. Check the end of the alpha 8 blogpost. The team is already incestigating the problem.

**Comment by Calinou** [comment]
See the *Known issues* section of https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-8. In the meantime, you can keep using 4.0.alpha7.

**Comment by akien-mga** [comment]
That's probably related to https://github.com/godotengine/build-containers/pull/104, we're using LLVM 14 on Fedora 36 which might be too recent for Xcode 12.4 which we're using.

I'm currently working on updating to Xcode 13.3.1 SDKs, still using LLVM 14 for now, and if that doesn't work I'll try Xcode 13.3.1 with LLVM 13 (which should be closer to what Apple validated).

> crash does not happen when it's opened via Rosetta

That's interesting, so it might also be the arm64 build which doesn't work as expected. CC @bruvzg

**Comment by akien-mga** [comment]
I uploaded a new build which should work fine: https://downloads.tuxfamily.org/godotengine/4.0/alpha8/Godot_v4.0-alpha8_osx.universal.zip

(Built on Fedora 34 with LLVM 12, like previous builds.)

I did not rebuild / re-upload the export templates though, so macOS exports might still crash on `arm64`.

**Comment by yedpodtrzitko** [comment]
ot: sorry for the horrible initial name of this issue, I'll do better next time.

**Comment by duchainer** [comment]
So, in more layman terms, if I want to build a custom Godot4 editor for MacOS, do I need to touch up the Sconstruct file?

**Comment by bruvzg** [comment]
> So, if I want to build a custom Godot4 universal editor .app for MacOS like I used to, do I need to touch up the Sconstruct file or my XCode version? And starting at which commit?

No changes necessary. It was an issue with osxcross cross-building environment on Linux, building with Xcode should work without issues.

**Comment by duchainer** [comment]
Oh thanks. 
I do use a linux box with osxcross to compile the Godot4 universal (both ARM-64 and x86_64) version of it (I used to compile the Godot3 version with modules)
So should I use a different version than `osxcross_sdk=darwin20.4` and if so, on which commit would that have changed?

(Sorry if I'm dense and you already answered that :sweat_smile: )

**Comment by bruvzg** [comment]
> So should I use a different version than `osxcross_sdk=darwin20.4` and if so

No, `20.4` SDK works with LLVM 12, so there's no reason to update SDK.

**Comment by duchainer** [comment]
Gotcha. Thanks again for the precision :smile:

**Comment by akien-mga** [comment]
> I uploaded a new build which should work fine: [downloads.tuxfamily.org/godotengine/4.0/alpha8/Godot_v4.0-alpha8_osx.universal.zip](https://downloads.tuxfamily.org/godotengine/4.0/alpha8/Godot_v4.0-alpha8_osx.universal.zip)

Closing as this new build solves the issue. Alpha 9 should also be fine, I confirmed that Clang 14 was the problem so we're now building macOS binaries on Fedora 36 but which a self-compiled Clang 13.0.1 and Xcode 13.3.1, which works fine.
