### ISSUE TITLE
White line appears in Animated Sprite 3D

### ISSUE THREAD

**Issue by RiadOkba** [godotengine/godot#60983]
### Godot version

3.4.4 stable

### System information

Windows 10

### Issue description

Dear,

A white line (sometime grey) appears at the edge of a picture (animated sprite 3d). It appears on F5 or F6 debug. It also appears on win executable...

![Capture](https://user-images.githubusercontent.com/67765342/168173407-20b98a7d-c3cb-4d3f-a632-bed586b04009.JPG)
![Capture1](https://user-images.githubusercontent.com/67765342/168173415-f11c0a18-2e6f-4f3f-8c20-0865767f7480.JPG)
![Capture3](https://user-images.githubusercontent.com/67765342/168173421-6a3d1fc8-9638-4081-ab08-a52e22c1d903.JPG)

Note: when I try to resize the window, it seems to vanish and appear again according to the window size...

The config I have changed from a default settings are:
![settings](https://user-images.githubusercontent.com/67765342/168174044-edfa9530-8d74-4725-9047-07dfab72f796.JPG)

Thanks a lot

Regards,
Riad

### Steps to reproduce

I used AnimatedSprite3D and added some animation
![AnimatedSprite3d](https://user-images.githubusercontent.com/67765342/168174395-313eda47-80bc-428b-acb9-06f3757a4151.JPG)

**Comment by RiadOkba** [comment]
I wanted to add that there's "Alpha Cut" parameter under Flags of the AnimatedSprite3D Inspector. When I put this parameter to disable it seems to fix definitely the problem BUT it will produce a weird image as a result (edge of any content in the picture will look very sharp)
![FakeSolution](https://user-images.githubusercontent.com/67765342/168175262-b26048da-8db9-4ef9-9996-5bf4c87f14ad.JPG)

**Comment by Calinou** [comment]
This is caused by floating-point precision errors in the UV mapping, since the texture is being upscaled (it's not displayed at 1:1 size). Try disabling **Repeat** on the texture's import options. If that doesn't work, add a transparent 1-pixel border around the sprite's edges in an image editor.

**Comment by RiadOkba** [comment]
Thanks a million Calinou!

Disabling Import>Flags>Repeat makes it work as intended...
