### ISSUE TITLE
Input Map right mouse click event does not trigger event when not is_pressed()

### ISSUE THREAD

**Issue by wattsUpJaz** [godotengine/godot#60985]
### Godot version

v3.4.4.stable.official [419e713a2]

### System information

macOS Monterey v12.3.1

### Issue description

Input Map actions that capture the right click mouse input ("r_click") do not generate a "r_click" event when the right mouse button is released. This makes acting on right mouse button releases impossible if using the Input Map. Input Map actions that capture left clicks do not have this issue. I believe the right click actions should behave the same as the left click actions.

A current workaround to this issue is to check the button_index of the event manually:
```
if event is InputEventMouseButton:
	if event.button_index == BUTTON_LEFT:
		var pressed = true if event.is_pressed() else false
		_update_message("left pressed  = " + str(pressed))
	elif event.button_index == BUTTON_RIGHT:
		var pressed = true if event.is_pressed() else false
		_update_message("right pressed = " + str(pressed))
```

### Steps to reproduce

While running the scene in the reproduction project, click on the screen and a message detailing the action will print to Output. If the `use_input_map` variable is false then the output will print the behavior captured by manually checking the event's `button_index`. If true, the output will print the behavior captured by the two custom input map actions "l_click" and "r_click".

 The bug is found when comparing the output of a left and right click when `use_input_map = true`:
<img width="747" alt="Screen Shot 2022-05-12 at 12 00 57 PM" src="https://user-images.githubusercontent.com/15367315/168175150-1b6bd71b-cd6c-4d23-88eb-b7a576aad34c.png">

or comparing the output of a right click when `use_input_map` is true, and then false:
<img width="747" alt="Screen Shot 2022-05-12 at 11 59 24 AM" src="https://user-images.githubusercontent.com/15367315/168174981-56ff7c22-3fac-43cd-a52e-282ca9744067.png">

A "r_click action = False" message should be in both logs, created when the right mouse button is released.

### Minimal reproduction project

[IsPressedBug.zip](https://github.com/godotengine/godot/files/8682830/IsPressedBug.zip)

**Comment by kleonc** [comment]
The bug is in the MRP, you're checking `event.is_action_pressed("r_click")` instead of `event.is_action("r_click")`:
```
if event.is_action("l_click"):
	var pressed = true if event.is_pressed() else false
	print("l_click action = " + str(pressed))
elif event.is_action_pressed("r_click"): ### INCORRECT CHECK ###
	var pressed = true if event.is_pressed() else false
	print("r_click action = " + str(pressed))
```
This works fine:
```
if event.is_action("l_click"):
	print("l_click action = %s" % event.is_pressed())
elif event.is_action("r_click"):
	print("r_click action = %s" % event.is_pressed())
```

**Comment by wattsUpJaz** [comment]
Oh shoot thank you!! Super sorry for the dumb mistake 😅
