### ISSUE TITLE
Editor properties do not reflect theme was cleared

### ISSUE THREAD

**Issue by habamax** [godotengine/godot#6098]
**Operating system or device - Godot version:**
Windows 10
Godot 2.1

**Issue description** (what happened, and what was expected):
If you create a new theme for a button then goto theme details and back: custom font settings disappear.
Now if you clear theme -- custom font settings are still hidden and you cannot change anything font related until you switch to another node and back.

**Steps to reproduce:**
as above

**Link to minimal example project** (optional but very welcome):

**Comment by KoBeWi** [comment]
Fixed in 3.1
