### ISSUE TITLE
load_threaded_request() combined with awaiting a timer fails when loading the same resource twice

### ISSUE THREAD

**Issue by trianglebreaker** [godotengine/godot#60988]
### Godot version

4.0 alpha 8

### System information

Windows 10

### Issue description

Using ```ResourceLoader.load_threaded_request()``` to load a resource while also using ```await get_tree().create_timer().timeout``` to wait (eg. for a loading animation to complete) will work the first time, but running it a second time to reload the same resource results in ```ResourceLoader.load_threaded_request()``` loading a null object instead.

### Steps to reproduce

Use ResourceLoader to load a resource.

```
ResourceLoader.load_threaded_request(path_to_resource)
while true:
	if load_status == ResourceLoader.THREAD_LOAD_LOADED:
		break
	await get_tree().create_timer(0.5).timeout
	load_status = ResourceLoader.load_threaded_get_status(path_to_resource)
var resource = ResourceLoader.load_threaded_get(path_to_resource)
```

Add a timer somewhere in the function outside the while loop.

```
await get_tree().create_timer(0.5).timeout
```

The resource will load properly once, but on the second run it will be null; instantiating it will cause an error.

### Minimal reproduction project

[LoadError.zip](https://github.com/godotengine/godot/files/8682927/LoadError.zip)
The project replicates the error with scenes. Use ```KEY_1``` and ```KEY_2``` to control scene switching.

**Comment by volokh0x** [comment]
I can confirm the issue with `alpha8` but not with `beta5`. Could you reproduce the error with a more recent [version](https://downloads.tuxfamily.org/godotengine/4.0/) of the engine?

**Comment by fatduckling** [comment]
Just checked with Godot 4 RC1 and issue seems to be resolved, thanks
