### ISSUE TITLE
When you create a class with "class_name" and use it in other files, restarting the project will prompt an error

### ISSUE THREAD

**Issue by skyatgit** [godotengine/godot#60997]
### Godot version

4.0

### System information

Windows11

### Issue description

When you create a class with "class_name" and use it in other files, restarting the project will prompt an error

### Steps to reproduce

1. make a file "Test.gd"
class_name Test
extends Node
2.use it in other files
extends Node2D
func _ready():
	var a=Test.new()
3.save and reload current project
![image](https://user-images.githubusercontent.com/42607334/168231929-d89dcb90-57be-4e6a-8df1-5d3e734b30f8.png)

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/8684987/Test.zip)

**Comment by KoBeWi** [comment]
Can't reproduce, the MRP doesn't give any error.
What version are you using?

**Comment by skyatgit** [comment]
alpha 7 and alpha 8

**Comment by KoBeWi** [comment]
Is the error supposed to show when I open the project or do I have to do something extra?

Also the dialog you shown in the screenshot isn't an error, it just indicates an external change. Shouldn't appear on startup though.

**Comment by skyatgit** [comment]
yes,it will show when you open the project

**Comment by skyatgit** [comment]
https://user-images.githubusercontent.com/42607334/169034607-1ab24935-b016-4a8e-83b4-36b13b42c0de.mp4

**Comment by skyatgit** [comment]
I wonder if it's the problem of windows permissions, but I've started Godot with administrator permissions

**Comment by KoBeWi** [comment]
Yes, it was in Documents.

**Comment by skyatgit** [comment]
I changed another computer, but the problem still exists

**Comment by skyatgit** [comment]
Is it possible that I use Chinese windows to cause this problem

**Comment by KoBeWi** [comment]
I use Windows 10, so maybe 11 is the problem, idk

The fact that you see this dialog means that file modified time has changed. Maybe you could check if it's really modified (by checking the time in Windows explorer) and if yes, find out what modifies it. But I guess the latter might be difficult.

**Comment by skyatgit** [comment]
OK, I'll test it on the win10 system tomorrow

**Comment by Zireael07** [comment]
I think "class_name" is a red herring here. Modified time/"newer on disk" prompt are known to be fishy on some OS/hardware.

**Comment by skyatgit** [comment]
However, if you do not use this class in other files, this prompt will not appear

**Comment by Chaosus** [comment]
And I've seen this bug regularly in my internal projects, and the project attached to the topic demonstrates it perfectly...

**Comment by skyatgit** [comment]
I want to know if the problem is in the process of saving the project, if there is no problem when I open your project

**Comment by nathanfranke** [comment]
I can reproduce it on my personal project. Linux 5.15.40-1-lts.

Deleting `.godot` works around it, not sure for how long though.

**Comment by nathanfranke** [comment]
Man, this took a while: [test2.zip](https://github.com/godotengine/godot/files/8718075/test2.zip)
 
With this MRP, I can reproduce it even when `.godot` is deleted (it is not even included in the zip). With OP's MRP, I can only reproduce with the original `.godot`. This should make debugging a lot easier.

![image](https://user-images.githubusercontent.com/14253836/169091882-392a997f-7feb-4a89-838b-799333e92e08.png)

**Comment by KoBeWi** [comment]
Still can't reproduce.

**Comment by skyatgit** [comment]
@KoBeWi Are you using your own compiled version，or download from https://downloads.tuxfamily.org/godotengine/4.0/alpha8/Godot_v4.0-alpha8_win64.exe.zip

**Comment by skyatgit** [comment]
New discovery！When I use the alpha1 version to do this, and then use other versions to do this, this problem will not occur again
@KoBeWi @nathanfranke @Chaosus @Zireael07

**Comment by nathanfranke** [comment]
The MRP I posted should still be reproducible on the latest master. Can you elaborate on "other versions"?

**Comment by skyatgit** [comment]
Please open the project with alpha1 version first，Then you can use any alpha version

**Comment by skyatgit** [comment]
This problem is affected by C:\Users\XX\AppData\Roaming\Godot\editor_settings-4.tres

**Comment by nathanfranke** [comment]
@skyatgit have you tried running my MRP?

**Comment by skyatgit** [comment]
@nathanfranke  I ran your MRP and no errors occurred

**Comment by skyatgit** [comment]
The higher version of godot4 is not add "text_editor/behavior/files/auto_reload_scripts_on_external_change = true" when creating C:\Users\XX\AppData\Roaming\Godot\editor_settings-4.tres

**Comment by skyatgit** [comment]
@KoBeWi That's why you won't repeat this problem

**Comment by vfig** [comment]
What seems to be happening:
  1. The dependent script is first getting loaded by `GDScriptCache::get_shallow_script` (via `GDScriptCache::finish_compiling()`) when the scene and its root script is loaded, because the root script has it as a dependency. This creates a resource with a zero `last_modified_time`. This resource is added to the resource cache.
  2. `ScriptEditorPlugin::set_window_layout()` tries to load the script again, because it is open in a tab in the script editor. This load is satisfied by the cache, and so the edited resource is set to this zero-last_modified_time script.
  3. At the end of `ScriptEditorPlugin::set_window_layout()`, it calls `_test_script_times_on_disk()`, which compares last_modified_time of its edited resource with the time on disk to see if they are equal. Because the script was loaded with a zero `last_modified_time`, the two times are never equal. So the script is flagged as needing reload.
  4. When the `text_editor/behavior/files/auto_reload_scripts_on_external_change` setting is false, the flag from (3) causes the "The following files are newer on disk" dialog to be displayed.
  5. While the dialog from (4) is still on screen, the ScriptEditor receives a NOTIFICATION_WM_WINDOW_FOCUS_IN notification, and calls `_test_script_times_on_disk()` again, which erroneously results in a second dialog.

**Comment by linkpy** [comment]
I am on Linux (Pop_OS!) and I have the same issue on 4a11.
It seems to be related with class_name as well in my case.

[Godot 4 Bughunt.zip](https://github.com/godotengine/godot/files/9032761/Godot.4.Bughunt.zip)

**Comment by stephannv** [comment]
I'm using 4.0.alpha12 and I'm getting this dialog too every time I open my project.
My setup: macOs Monterrey 12.4, Apple Sillicon (M1 Max).

**Comment by NineHearts** [comment]
I'm having same issue in 4.0 alpha 14 using in window 11.

**Comment by zbpan-sh** [comment]
I'm having same issue in 4.0 alpha 16, macOs (apple silicon M1).

**Comment by isaacwilliams** [comment]
Same issue, 4.0 alpha 16, MacOS M1 Mac.
