### ISSUE TITLE
Some HTML player bugs

### ISSUE THREAD

**Issue by deatharrow** [godotengine/godot#61]
For platformer example, there's no sound. Checked in Chrome, Opera and Firefox.

The platformer example can't run in IE11. All I can see is a grey background.

I the 3D platformer example you can't see the 3d models for player and the enemy. Also the sky texture is missing.

**Comment by akien-mga** [comment]
The HTML5 has evolved a lot since Feb 2014, it still has bugs but probably different ones, so let's archive this one.
