### ISSUE TITLE
Asset Library not working behind proxy (also applies to HTTPClient and HTTPRequest)

### ISSUE THREAD

**Issue by gaconkzk** [godotengine/godot#6100]
___

***Bugsquad edit:** No need to further confirm this issue. It's already been confirmed several times.*

___

**Operating system or device - Godot version:**
Ubuntu 16.04

**Issue description** (what happened, and what was expected):
When running godot, if we are behind a proxy, the environment http_proxy https_proxy not applied
**Steps to reproduce:**
Run godot behind a proxy

**Link to minimal example project** (optional but very welcome):

**Comment by vickylance** [comment]
Any updates on this?

**Comment by akien-mga** [comment]
Well it's over a year old. Is it still reproducible in the current master branch/3.0-beta1?

**Comment by vickylance** [comment]
@akien-mga I tried the latest stable version which is 2.1, will try with the master branch tomorrow and let you know

**Comment by fxdave** [comment]
The export template manager also doesn't have proxy settings.

**Comment by ian-p-cooke** [comment]
still an issue in v3.03 (win64)

**Comment by Mikerhinos** [comment]
Unfortunately, same problem with v3.0.5 stable (win64)

**Comment by prmsrswt** [comment]
I am also facing this issue with Godot v3.0.5-1 on Arch Linux.

**Comment by Irrgeist** [comment]
Same issue with V3.1.alpha.custom_build.ebc07ad on Windows 10 64 bit

**Comment by russellsch** [comment]
Same issue on v3.0.6.stable.official on Windows 10 64-bit

**Comment by menip** [comment]
Is this still an issue?

**Comment by Necco-Z** [comment]
Still an issue. Running v3.1.1.stable.official on ubuntu 19.04

**Comment by dougneves** [comment]
Same issue, running v3.1.1.stable.official on MacOS Mojave 10.14.5

**Comment by Knochi** [comment]
still a problem with godot 3.2.1.stable.official behind company proxy with authentication.

**Comment by aamir-abbas** [comment]
Godot 3.2.2 is consistent with the "behind proxy (with authentication)" issue.

**Comment by kevung** [comment]
It is still a problem with godot 3.3.stable.official behind company proxy.

**Comment by almusx** [comment]
not working with authenticated proxy

**Comment by velderyx** [comment]
still cant connect to internet using proxy
