### ISSUE TITLE
Godot one player control two character first character forward not work

### ISSUE THREAD

**Issue by tiglapiles** [godotengine/godot#61019]
### Godot version

3.4.4.stable

### System information

OS: EndeavourOS,Arch Linux; CPU: AMD ryzen 5900hx

### Issue description

This is a game one player can control two characters，left hand control left character and right hand control right character，When I set project inputmap use W,A,S,D control left character, use left, right, top, bottom arrow control right character, there exist a situation that left W button not working：

### Steps to reproduce

Like player1  move code in _process is：
```
var velocity: Vector3

func _process() -> void:
    ...

    dir.x = Input.get_action_strength("left_move_right")-Input.get_action_strength("left_move_left")

    dir.z = Input.get_action_strength("left_move_back") - Input.get_action_strength("left_move_forward")

   ...
```
player2 code is
```
var velcocity: Vector3
func _process() -> void:
    ...

    dir.x = Input.get_action_strength("right_move_right") - Input.get_action_strength("right_move_left")

    dir.z = Input.get_action_strength("right_move_back") - Input.get_action_strength("right_move_forward")

    ...
```

### Minimal reproduction project

When I first press right forward button，left forward button W not working.

**Comment by akien-mga** [comment]
This is likely keyboard ghosting and not a Godot bug. You can test on https://drakeirving.github.io/MultiKeyDisplay/

**Comment by tiglapiles** [comment]
> 

thanks for reply, and you are right.
