### ISSUE TITLE
Godot 4 mono will always open the script tab, even when an external editor is configured

### ISSUE THREAD

**Issue by macjuul** [godotengine/godot#61015]
### Godot version

v4.0.alpha.mono.custom_build [edda6ee9f]

### System information

Windows 10, Mono, Visual Studio 2022 external editor

### Issue description

When opening a C# script either from the FileSystem or from the Scene tree, besides opening in your configured external editor, Godot will always open the script tab, which is naturally undesired.

I have tracked down and found a fix for this behavior ~~and will open a PR shortly~~. PR with fix: #61016

### Steps to reproduce

- Create a new cs file
- Configure an external editor
- Open from the FileSystem dock

### Minimal reproduction project

Not applicable, should affect all projects

**Comment by VonWeier** [comment]
4.0的alph版本什么时候有mono版本？
