### ISSUE TITLE
[Godot4] OS.get_unique_id() bug?

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#61023]
### Godot version

v4.0.alpha8.official [cc3ed63af]

### System information

Windows 10, 64bit

### Issue description

In Godot 4:
![捕获](https://user-images.githubusercontent.com/35988767/168413328-01f1c0d8-79a5-445e-8387-c2c9c15b4f66.PNG)
In Godot 3.4:
![捕获2](https://user-images.githubusercontent.com/35988767/168413332-7df53a53-407b-4220-a4ae-fda8c0c71dfc.PNG)

### Steps to reproduce

Please run the reproduction project.

### Minimal reproduction project

[GetUniqueIdTest.zip](https://github.com/godotengine/godot/files/8692359/GetUniqueIdTest.zip)

**Comment by Calinou** [comment]
[`OS.get_unique_id()`'s documentation](https://github.com/godotengine/godot/blob/4fabc2b6a4eabd83523e84ae0b1ec2fa1d619069/doc/classes/OS.xml#L542) does not mention that the string is not guaranteed to be the same across releases. I'm not sure if this is a reasonable guarantee to make.
