### ISSUE TITLE
function interrupted or called by multiple threads

### ISSUE THREAD

**Issue by loanMaster** [godotengine/godot#61030]
### Godot version

3.4.4

### System information

Windows 10, GLES2 and GLES3

### Issue description

I have a simple scene which calls a function whenever a button is pressed.
The same function is called when a key is pressed on the keyboard.

When I quickly press the button followed by pressing a key board key I expect:
-the function is called twice
-the first call of the function completes before the function is called again

However the callback function does not complete its execution before being called a second time.
Which means that the function call is either interrupted or a second thread calls the function.

Is this the expected behavior? How can one ensure thread-safety?

### Steps to reproduce

Create a project and a scene (Node2D).
Add another Node2D and some children to it. Create a button and add it to the newly created Node2D.
Connect your scene to the "pressed" event of the button.
Implement the "_unhandled_input" function in the same scene and call the same callback function.

The callback function has some loop iterating over the children of the Node2D.
When the scene is run and the button is pressed followed by quickly pressing a key, the callback function is called twice.
However the callback function no longer completes its execution before being called a second time.

### Minimal reproduction project

[project.zip](https://github.com/godotengine/godot/files/8692975/project.zip)

**Comment by Zireael07** [comment]
Why close immediately after reporting?

**Comment by loanMaster** [comment]
Just had to retest sth.

**Comment by kleonc** [comment]
Ok, I've checked it out and it seems like hiding a button (`child.visible = !child.visible`) which is currently considered by the Viewport as the one being focused by the mouse (it is hovered) triggers sending an unpress mouse button event which results in triggering button's `pressed` signal (if button is setup to emit it on mouse release). Something like that.

So no threading is involved here, hiding the button in such specific setup triggers its `pressed` signal to be emitted (and hence your callback is called in the middle of the previous one).

As a workaround for now changing button's [`action_mode`](https://docs.godotengine.org/en/stable/classes/class_basebutton.html#class-basebutton-property-action-mode) from `ACTION_MODE_BUTTON_RELEASE` to `ACTION_MODE_BUTTON_PRESS` might work.

**Comment by loanMaster** [comment]
My bad. Thank you for the clarification.
