### ISSUE TITLE
HTTPRequest not downloading images correctly.

### ISSUE THREAD

**Issue by FabiGjuzi** [godotengine/godot#6103]
I am using the new HTTPRequest node to download images ,but the downloaded images are corrupted or the downloaded bytes are not in the right order I suppose .I am using Godot 2.1 Stable.
![script](https://cloud.githubusercontent.com/assets/12370622/17556800/0948fbce-5f15-11e6-8029-b04988f00891.jpeg)
![bad_img](https://cloud.githubusercontent.com/assets/12370622/17556803/0bb82272-5f15-11e6-9c97-43053622d93d.jpeg)
![original_img](https://cloud.githubusercontent.com/assets/12370622/17556807/0d895382-5f15-11e6-88b8-3c37c5e345bf.jpeg)

**Comment by volzhs** [comment]
I tested it with same URL and same code on Windows 10, Godot 2.2 alpha.
I couldn't reproduce this.
The downloaded file shows exactly same image and has same bytes.

**Comment by akien-mga** [comment]
Can someone reproduce this, or should it be closed?

**Comment by alketii** [comment]
Tested several times in Linux and Android with JPG and PNG formats and it worked like a charm.
I used set_download_file()  before making request.

**Comment by avril-gh** [comment]
> Can someone reproduce this (...)

Yes, there seem to be some issue in HTTPClient.
In short - it comes from interaction betwin http.poll() / http.read_response_body_chunk()

In long version -

As example, try [HTTP client class Example](https://github.com/godotengine/godot-docs/blob/2.1/learning/features/networking/http_client_class.rst) to download big image file (let it be 100KB JPG file)

The image will get chunked (its ok, as expected),
and then while in loop of assembling chunks into RawArray (lines 84-85) 'something' will get wrong.

You will see that HTTPClient's `http.get_response_body_length()` gave correct lenght of image file, however RawArray's rb.size() is different.
So without even looking at file, at the end we obviously get here something different than we expected.
...and to visualise what we got you may look at image in first post of this issue - it looks exacly like this.

The fishy thing happens in lines 84-85
 ```
# While there is body left to be read
http.poll()
var chunk = http.read_response_body_chunk() # Get a chunk
    # BUT we might randomly get broken chunks here
```
It looks like, http.read_response_body_chunk() is called immediately after http.poll() which in some case does not let http.poll() to finish its work (???) so we get unready/broken data ?
Anyway - IF we add OS.delay_usec(1) after http.poll() - everything magically works great.

 ```
# While there is body left to be read
http.poll()
OS.delay_usec(1) # added it here
var chunk = http.read_response_body_chunk() # Get a chunk
    # NOW with OS.delay_usec() added, we always get what been expected
```

Thats how it is and where it lurks.

**Comment by alketii** [comment]
@avril-gh thats HTTPClient and this bug is for HTTPRequest. I don't know if they are related, could have the same backend though.

**Comment by mhilbrunner** [comment]
HTTPRequest uses HTTPClient internally.
Could not reproduce this using current master, couldn't reproduce #11963 anymore either.

Maybe this should be closed and reopened in case somebody encounters it using a more recent version.

**Comment by akien-mga** [comment]
Assuming fixed, please comment/open a new issue if it's not the case.
