### ISSUE TITLE
Switching to Corsair Audio device casues CTD with Spectrum Analyzer bus effect.

### ISSUE THREAD

**Issue by uvmain** [godotengine/godot#61052]
### Godot version

3.4.4.stable, Corsair HS70 Pro, Corsiar iCue software v.4.14.179

### System information

Windows 10

### Issue description

The editor and an exported exe both instantly crash to desktop when switching TO my Corsair HS70 Pro wireless headphones via Windows audio device selector if an audio bus has a spectrum analyzer effect added. It launches fine when this device is already selected (and plays audio). I can then switch device to my onboard Realtek and the audio will continue to play. If I then switch to the Corsair headset, the editor instantly crashes to desktop.

### Steps to reproduce

Launch editor with onboard audio selected in Windows.
Add a Spectrum Analyzer effect to the Audio Bus.
Via Windows, select the Corsair HS70 Pro audio device.

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/8695006/test.zip)

**Comment by Zireael07** [comment]
I believe a generic "crash when switching audio devices" was already reported?

**Comment by Calinou** [comment]
@uvmain Can you (or anyone else) still reproduce this bug in 3.5.2 and 4.0.3 or any later release?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.
