### ISSUE TITLE
FastNoiseLite domain_warp_fractal_type defaults to the wrong value

### ISSUE THREAD

**Issue by h0lley** [godotengine/godot#61050]
### Godot version

v4.0.alpha8.official [cc3ed63af]

### System information

Ubuntu, Nvidia

### Issue description

the options for domain_warp_fractal_type are as follows:

- DOMAIN_WARP_FRACTAL_NONE = 0
- DOMAIN_WARP_FRACTAL_PROGRESSIVE = 1
- DOMAIN_WARP_FRACTAL_INDEPENDENT = 2

where the default (according to the inspector) is DOMAIN_WARP_FRACTAL_PROGRESSIVE.
no setting is serialized when saving with DOMAIN_WARP_FRACTAL_PROGRESSIVE.

however when loading the scene, the texture is then generated with DOMAIN_WARP_FRACTAL_NONE.

### Steps to reproduce

1. create a new Node2D scene
2. add a Sprite2D node, plug in a NoiseTexture and a FastNoiseLite
3. enable Domain Warp
4. notice that Fractal Type defaults to Progressive in the inspector. effectively however, None is used. confirm this by switching to None and back to Progressive.
5. save the scene with Progressive. reopen the scene, notice it's still set to Progressive but None is used.

**Comment by Calinou** [comment]
cc @Geometror
