### ISSUE TITLE
UWP Exporter doesn't copy the GDNative DLL to the final APPX

### ISSUE THREAD

**Issue by ElCosmoXD** [godotengine/godot#61060]
### Godot version

v3.4.4.stable.official.419e713a2

### System information

Windows 11, GLES3, Nvidia GeForce GT 1030.

### Issue description

Hello, I'm exporting a UWP project that contains a DLL file but when I export the project the DLL is missing, Here are some screenshots about it:

![1](https://user-images.githubusercontent.com/37759352/168490761-caa893f0-a2b0-48fe-a232-b643208fe9a7.png)
![2](https://user-images.githubusercontent.com/37759352/168490765-115886d4-dcb2-4888-859a-13066764a934.png)

(game/ folder)
![3](https://user-images.githubusercontent.com/37759352/168490767-b6c009b5-3548-4dde-aa66-931e31b44920.png)

![imagen](https://user-images.githubusercontent.com/37759352/168491275-100d1dbb-98e5-4193-871c-60e7f5d0c5f2.png)

### Steps to reproduce

1. Add the dll to the project
2. Export the project
3. Try to execute it or see the contents inside the APPX file

### Minimal reproduction project

[UWP Game.zip](https://github.com/godotengine/godot/files/8695822/UWP.Game.zip)

**Comment by ElCosmoXD** [comment]
I fixed it by adding a function to copy the dynamic libraries, I will close this issue and I will open a pull request.

**Comment by Geometror** [comment]
This should be kept open until the PR fixing this issue is approved and merged :)

**Comment by akien-mga** [comment]
Fixed by #61262.
