### ISSUE TITLE
Vulkan: Unexpected behaviour of `DEPTH_TEXTURE` or `INV_VIEW_MATRIX`

### ISSUE THREAD

**Issue by ilpwpsfu** [godotengine/godot#61065]
### Godot version

Godot 4.0 alpha 7

### System information

Windows 11

### Issue description

I've tried to make simple water shader with refraction with Godot 4, but was unable to get world position by depth properly.
It seams to be still affected by view since closer camera is to the plane, closer to reality world position becomes. Also there is a strange outline appears. In Godot 3 same code works fine. The only difference is change CAMERA_MATRIX to INV_VIEW_MATRIX.
It might be an expected behaviour since there are no docs yet and i could get something wrong. Fix me if that's the case.

[Godot 4 screenshot](https://ibb.co/sF5frpY)
[Godot 4 screenshot (Camera closer to the plane)](https://ibb.co/1ZFv89R)
[Godot 3 screenshot](https://ibb.co/4p29pyC)

### Steps to reproduce

All you need is to create a cube, a big plane and a shader material applied to the plane.

Godot 4 shader:
```glsl
shader_type spatial;
render_mode world_vertex_coords, unshaded;

varying vec3 world_pos;

void vertex() {
	world_pos = VERTEX;
}

void fragment() {
	float d = texture(DEPTH_TEXTURE, SCREEN_UV).r;
	vec3 s = texture(SCREEN_TEXTURE, SCREEN_UV).rgb;
	
	vec3 ndc = vec3(SCREEN_UV, d) * 2. - 1.;
	vec4 world = INV_VIEW_MATRIX * INV_PROJECTION_MATRIX * vec4(ndc, 1.);
	vec3 depth_pos = world.xyz / world.w;
	
	float depth_mix = float(world_pos.y > depth_pos.y);
	depth_mix *= float(d != 1.);
	
	ALBEDO = vec3(depth_mix);
}
```

Godot 3 shader:
```glsl
shader_type spatial;
render_mode world_vertex_coord, unshadeds;

varying vec3 world_pos;

void vertex() {
	world_pos = VERTEX;
}

void fragment() {
	float d = texture(DEPTH_TEXTURE, SCREEN_UV).r;
	vec3 s = texture(SCREEN_TEXTURE, SCREEN_UV).rgb;
	
	vec3 ndc = vec3(SCREEN_UV, d) * 2. - 1.;
	vec4 world = CAMERA_MATRIX * INV_PROJECTION_MATRIX * vec4(ndc, 1.);
	vec3 depth_pos = world.xyz / world.w;
	
	float depth_mix = float(world_pos.y > depth_pos.y);
	depth_mix *= float(d != 1.);
	
	ALBEDO = vec3(depth_mix);
}
```

**Comment by Calinou** [comment]
> Also there is a strange outline appears.

This is a known issue: https://github.com/godotengine/godot/issues/55755

**Comment by clayjohn** [comment]
In Vulkan ndc depth has a range 0-1, so it should not scaled into the -1 to 1 range. 

You will likely find the docs beneficial here as they explain how to get world space depth from the DEPTH_TEXTURE https://docs.godotengine.org/en/latest/tutorials/shaders/advanced_postprocessing.html

**Comment by ilpwpsfu** [comment]
Somehow I haven't noticed this quote about vulkans ndc. Thanks.

**Comment by clayjohn** [comment]
Please let me know if that fixes the issue for you! If we can keep digging to try to figure out the bug.

**Comment by clayjohn** [comment]
No response so closing
