### ISSUE TITLE
Vulkan: GPUParticles3D are invisible if spawned at the same location as an attractor's origin

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#61066]
### Godot version

4.0.alpha8

### System information

Fedora 36, GeForce GTX 1080 (NVIDIA 510.68.02)

### Issue description

While working on https://github.com/godotengine/godot/pull/61068, I noticed GPUParticles3D are invisible if spawned at the same location as an attractor's origin:

https://user-images.githubusercontent.com/180032/168498557-7aacc5ee-b86b-400c-bf84-03b4622630d4.mp4

This can be worked around by moving the particle slightly, or using an emission shape other than Point (so that particles will *almost* never spawn at the exact same location as the attractor's origin).

Disabling interpolation or adjusting Fixed Fps does not fix this issue.

If you change **Fixed Fps** (causing the particle system to reinitialize), you will notice a brief flash of particles zooming around. This is also visible when using **Scene > Reload Saved Scene**.

**Epilepsy warning: The video below contains bright flashing.**

https://user-images.githubusercontent.com/180032/168498574-7f21ea5c-e215-47a2-9b48-a6b78b8211fa.mp4

### Steps to reproduce

- Add a GPUParticles3D node with a draw pass and a process material.

### Minimal reproduction project

[test_particle_attractor_zero.zip](https://github.com/godotengine/godot/files/8696280/test_particle_attractor_zero.zip)
**Epilepsy warning: Brief flashing may occur when opening the editor or running the scene.**

**Comment by somnathsarkar** [comment]
This is because of a divide-by-zero error in `particles.glsl`

```glsl
dir = normalize(rel_vec)
```

Since normalize is indefinite for zero vectors. Replacing normalize with `normalize_direction` defined below fixes the issue:

```glsl
vec3 normalize_direction(vec3 direction){
	const float EPSILON = 0.001;
	if(length(direction)<EPSILON){
		return vec3(0.0);
	}
	return normalize(direction);
}
```

The flash of particles doesn't seem to be related to Attractors, changing the Fixed Fps causes particles to flash around the scene whether or not Attractors are present.

**Comment by Calinou** [comment]
@somnathsarkar Good catch! Feel free to open a pull request for this :slightly_smiling_face:
