### ISSUE TITLE
Mouse cursor gets stuck and locked in the viewport when tweaking sliders v2

### ISSUE THREAD

**Issue by gerrywastaken** [godotengine/godot#61062]
### Godot version

{"major":4, "minor":0, "patch":0, "hex":262144, "status":"alpha8", "build":"official", "year":2022, "hash":"cc3ed63af68ea9262bf8015d34aa6dd6327112e8", "string":"4.0-alpha8 (official)"}

### System information

Ubuntu 20.04.2 LTS - Linux 5.4.0-110-generic - GeForce GTX 1080 Ti

### Issue description

My issue is identical to what was described by the author of https://github.com/godotengine/godot/issues/11893 and many other participants of that issue. However, that is closed and we were asked to create a new issue with reproduction steps: https://github.com/godotengine/godot/issues/11893#issuecomment-418886151

The core issue is that when selecting clicking in the slider boxes and adjusting them, it is very common for my cursor to end up stuck in the box. Then as soon as I move the cursor my scene starts changing as if I had still held down a button on the slider. Sometimes this does not actually update the value, other times it does.

I've actually noticed this bug more frequently on Godot v4 compared to when I was using v3 and can reproduce it on the latest Alpha 8. So I spent a few hours trying to figure out how to replicate the consistently and simply.

https://user-images.githubusercontent.com/71481/168492062-5373854d-675a-4207-884c-02948c9fcb31.mp4

### Steps to reproduce

These steps describe just one situation in which this happens.  The issue seems quite random, but my hope is that these reproducible steps will lead to the core issue.

1. create a new project
2. create a 3D scene
3. Add a mesh 3D  (just for visualization of the issue)
4. Change it to a box mesh (again for visuals)
5. open its transform section
6. click once on right on the "x" label
7. double click twice quickly directly on the "z" label
8. if the text in the z section is all completely highlighted you have done this quick enough. If not, the bug may not have triggered, so repeat step 6
9. start moving your mouse and you will notice it's strangely locked to the mesh movement, but often the transform numbers are not updating... (although I've had instances where they do update). However, your mouse cursor is always missing and causing the value to change within the scene, even if it's not updating in the inspector.
10. left-click. Notice that the position of the mesh springs back to before you started moving it (at 29 seconds in the video)
11. right-click and you get your mouse cursor back (at 34 seconds in the video)

### Minimal reproduction project

Just a single cube mesh in a scene. That's it :shrug: 
[mouse_issue_godot_v4_alpha_8.zip](https://github.com/godotengine/godot/files/8695928/mouse_issue_godot_v4_alpha_8.zip)

**Comment by Calinou** [comment]
Can you reproduce this after enabling **Single Window Mode** in the Editor Settings then restarting the editor?

**Comment by gerrywastaken** [comment]
@Calinou I cannot. So I guess this must be a new issue related to the support for multiple windows. One thing I forgot to mention which might be significant. I wasn't able to reproduce the above steps if I made the inspector panel wider.

**Comment by gerrywastaken** [comment]
I just worked out the reason why sometimes the number in the inspector panel updates. Once in a locked mouse state, if you first left click then they won't ever update. However, if the first thing you do is right click then the numbers start updating then right-click the inspector numbers do not change as things change in the main viewport. However, if the first thing you do when getting into a locked mouse state is right click then the numbers will start changing and the object will not reset back to the original position as described in my replication steps. This scenario is the one I found myself in the most. It was annoying as it was often after I'd just clicked on the input and typed the exact value I wanted, only to have it overwritten when I moved my mouse.

I'm glad there is at least a workaround for me. Thank you!

**Comment by gerrywastaken** [comment]
Oh one other thing, given that it's related to windows I'm wondering if this is related to the fact that I'm using i3wm as my window manager. If you cannot reproduce the steps above then that might be the difference.

**Comment by gerrywastaken** [comment]
@Calinou I noticed you set the `platform: windows` tag, but i think it should be `platform:linuxbsd`

**Comment by KoBeWi** [comment]
Sounds similar to #46433
The issue was on Windows and got fixed already.

**Comment by gerrywastaken** [comment]
@KoBeWi I'm curious if people are able to replicate this on other systems?

**Comment by squidink7** [comment]
It still happens for me on Godot 4 alpha 11 (linux), just enabled single window mode and will report if it happens again.

**Comment by Skywolf285** [comment]
Still happens on Beta2. Running Linux as well.

I found that the easiest way to reproduce is by double clicking a property and holding down the mouse button on the second click, then dragging it away from the property. Usually takes two tries but always works for me.

For me the mouse usually doesn't return when right-clicking however and I'm forced to alt+f4 Godot. (fortunately you get a prompt asking you to safe any unsaved changed which you can navigate using the keyboard, so I haven't lost work due to this yet).

**Comment by akien-mga** [comment]
I'm pretty sure this was fixed a while ago. Please let us know if you can still reproduce this in 4.0 RC 3 or later.
