### ISSUE TITLE
[3.5beta5] vibrate_handheld() on iOS does 1 haptic pulse

### ISSUE THREAD

**Issue by oeleo1** [godotengine/godot#61063]
### Godot version

3.5.beta5

### System information

iOS, iPhone 12

### Issue description

On iOS the `Input.vibrate_handheld(duration_ms: int = 500)` used to do exactly that - vibrate for half a second.

In this 3.5.beta5 version, the same call to `Input.vibrate_handheld()` results in a single haptic tick, which is quite different than a 500ms vibration.

### Steps to reproduce

Run a project on iOS with `Input.vibrate_handlheld()`

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot/pull/60397.

cc @timoschwarzer

**Comment by timoschwarzer** [comment]
Opened two PRs :)

**Comment by timoschwarzer** [comment]
> On iOS the Input.vibrate_handheld(duration_ms: int = 500) used to do exactly that - vibrate for half a second.

Fun fact @oeleo1: The vibration had a fixed duration of 400ms before. The `duration_ms` parameter was completely ignored. (And apparantly I ignored it with my previous changes as well)

**Comment by oeleo1** [comment]
@timoschwarzer Thanks for fixing it!
