### ISSUE TITLE
Theme editor have duplicates of the same class items

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#61077]
### Godot version

e8520044e735ce8d7fafb4ef9397f6177449abbd

### System information

Windows 11

### Issue description

Not sure why it's happening, but I think it looks incorrect:

![image](https://user-images.githubusercontent.com/3036176/168567566-8a3578a1-f00d-4e23-b854-4b85211e6f9f.png)

### Steps to reproduce

Create a new theme and open Manage Theme Items dialog

### Minimal reproduction project

No need - too easy to reproduce

**Comment by YuriSizov** [comment]
This shouldn't be related to the theme editor itself — that thing hasn't been changed in months.

**Comment by akien-mga** [comment]
Might be related to the changes to HashMap, I had to fix some bugs in Theme in #60881, maybe there are more. This looks like maybe it's showing the class name where it should be showing property names (so typically using a key instead of a value in the HashMap).

**Comment by YuriSizov** [comment]
Nah, it should be [type](https://user-images.githubusercontent.com/11782833/116259367-69f03580-a77e-11eb-91e3-10dda603892f.png). But HashMap changes look like a good candidate indeed. Might be some grouping logic that got broken.

**Comment by YuriSizov** [comment]
Okay, I think I know what's going on here. `Theme::get_type_list` was reworked alongside the HashMap PR losing this desired behavior. I believe, that in the old implementation an intermediate `Set` was used to guarantee uniqueness. But now the method's logic was simplified and the incoming `List` is just passed to various type list functions.

You can notice, that the duplicated types are duplicated as many times as there are different kinds of theme items in them.

Unfortunately, the old `Set` was removed, so unless there are new options for containers guaranteeing uniqueness, this needs to be done by hand.
