### ISSUE TITLE
Tile map painting preview doesn't automatically update.

### ISSUE THREAD

**Issue by TomJuri** [godotengine/godot#61089]
### Godot version

4.0.alpha8

### System information

Windows 11 (Dev Channel), Radeon RX590

### Issue description

When creating a TileMap under a Node2D, adding TileSet, Texture atlas and then selecting the tiles to paint, the preview always stays where the mouse last was. It only updates when zooming in or out or pressing right-click. (Only applies when multiple tiles are selected.)

### Steps to reproduce

Create Project.
Add Node2D.
Add TileMap.
Add TileSet.
Add TextureAtlas.
Select Tiles to draw.

### Minimal reproduction project

any project.

**Comment by KoBeWi** [comment]
![godot windows tools 64_154U9mJWhX](https://user-images.githubusercontent.com/2223172/168700123-15e19f6d-f117-4e58-a8ba-460d2e6b59ef.gif)
Can't reproduce, unless I misunderstood something. Can you add a video or at least some screenshots?

This sounds like one of #58609's symptoms.

**Comment by TomJuri** [comment]
Yes, you are right! I've also noticed while originally writing this issue, it only occurred sometimes. So it's a duplicate of #58609
> * TileMap editor doesn't display ghost tiles (previews) and is glitchy (similar to [Tilemap editor draws lines #24970](https://github.com/godotengine/godot/issues/24970), but permanently, i.e. lines are drawn with each click)
