### ISSUE TITLE
Connection lines in `GraphEdit` looks distorted

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#61086]
### Godot version

9efb134469b09e3cb893fc9056f8b7e5b1a98e8f

### System information

Windows 11

### Issue description

Self-explaining problem:

![image](https://user-images.githubusercontent.com/3036176/168601930-95471317-63a1-4216-a528-faa2d19d5ef1.png)

### Steps to reproduce

Open any VisualShader/script and try to connect to any node

### Minimal reproduction project

No need

**Comment by akien-mga** [comment]
Likely regression from #60463.

**Comment by Chaosus** [comment]
@akien-mga Seems not related and caused by something else:
![image](https://user-images.githubusercontent.com/3036176/168608661-112f851a-04be-4534-b53a-74bc690ac80e.png)
^^ screenshot from reverted commit

**Comment by Chaosus** [comment]
I've bisected it to 746dddc0673d7261f19b1e056e90e6e3a49ef33a
