### ISSUE TITLE
Regression: classes "not declared in the current scope" on runtime only

### ISSUE THREAD

**Issue by Benedani** [godotengine/godot#61084]
### Godot version

v4.0.alpha.custom_build [d6e7dcbea]; unmodified master built with `scons -j8 platform=x11 tools=yes target=release_debug bits=64`

### System information

Linux

### Issue description

Accessing classes (as a static type, or by using a static function as in the example) was broken in #60999 and result in this error on runtime.
<img src="https://user-images.githubusercontent.com/18270989/168594671-26cde7d9-85df-456b-a607-e0001265f8be.png" width=75%></img>
<img src="https://user-images.githubusercontent.com/18270989/168594780-3d873a67-247b-478e-ad39-159938d711a7.png" width=60%></img>
4b013a9 works:
<img src="https://user-images.githubusercontent.com/18270989/168611320-24aaaabe-5c9d-4e4b-97a9-c3d15182e66c.png" width=75%></img>

### Steps to reproduce

1. Create a class and name it using `class_name`.
2. Try to access that class in another script.

### Minimal reproduction project

[class_static_typing_error.zip](https://github.com/godotengine/godot/files/8700112/class_static_typing_error.zip)

**Comment by Uniformbuffer3** [comment]
I'm also experiencing this error, look like Godot fails to resolve custom class names in general. A side effect of this problem is that is no more possible to extends custom classes because Godot cannot resolve their names, breaking the entire class system.
