### ISSUE TITLE
Vulkan: No TRANSMISSION fragment built-in in shader

### ISSUE THREAD

**Issue by Partho29** [godotengine/godot#61098]
### Godot version

4.0.dev

### System information

Windows 11, GLES3, Nvidia Gtx 1650ti

### Issue description

There is no TRANSMISSION built-in in shader. I am pretty new to Godot so I don't know if it's a bug, future implementation or have been changed to something else. 

In Godot 3, it is there but in 4 it has been removed but other built-ins are present like ALBEDO, NORMAL_MAP, etc with a slight change in naming. But I can't see the same for transmission.

If it is a silly issue and has an easy workaround, kindly post a reply with solution.

### Steps to reproduce

TRANSMISSION = transmission.rgb + texture(texture_transmission, SCREEN_UV).rgb;

**Comment by Calinou** [comment]
cc @Chaosus

**Comment by clayjohn** [comment]
Looks like it was made a part of SSS here: https://github.com/godotengine/godot/pull/37678

**Comment by Chaosus** [comment]
Yeah, looks like it was renamed to `SSS_TRANSMITTANCE_COLOR`. Not a bug, closed.
