### ISSUE TITLE
Bug mouse captured in Windows8

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#6109]
**Operating system or device - Godot version:**
Windows 8, Godot 2.1

**Issue description** (what happened, and what was expected):
The capture of the mouse during the rotation of the camera, game is lags.

**Steps to reproduce:**
Input.set_mouse_mode(2)

! In Linux is working fine.

**Link to minimal example project** (optional but very welcome):
[mouse_captured_lags_windows8.zip](https://github.com/godotengine/godot/files/412293/mouse_captured_lags_windows8.zip)

**Comment by alexforbes** [comment]
I am also experiencing this issue on some Windows 10 machines.  Works fine on my Windows machine but a friend experiences lag and memory usage slowly but steadily increases.

Linux also working fine for me
.

**Comment by DimaKiva** [comment]
As well :(

**Comment by Calinou** [comment]
There isn't enough information in this issue (such as hardware specifications on which this issue happens), so I'm closing this. Please comment if you can still reproduce this on Godot 3.0 or newer.
