### ISSUE TITLE
shortcut parity with blender(or sync/import config)

### ISSUE THREAD

**Issue by Elmapul** [godotengine/godot#6110]
its a bit anoying to have different shortcuts for any program i use, it break the workflow.
there is anyway to import an configuration file defining shortcuts for common features? 
(eg: blender use: g for translate, r for rotate, s for scale)

or to export the godot shortcut config to blender? (or keep their configuration sync)

**Comment by Calinou** [comment]
Duplicate of #3995 (which also has more information).
