### ISSUE TITLE
Vulkan Clustered: Light clustering artifacts with OmniLights and SpotLights on Apple M1

### ISSUE THREAD

**Issue by KuuttiProductions** [godotengine/godot#61108]
### Godot version

4.0.alpha7

### System information

MacOS 12.3.1, Vulkan Clustered, Apple M1 Pro

### Issue description

https://user-images.githubusercontent.com/74451594/168745048-3e584f4d-77fd-4ef9-a6c8-759abc2dda99.mov

### Steps to reproduce

Make a black scene and add a spotlight. Get close to the surface with lot's of the light being on the screen. You should see black spots appearing on the screen. 

### Minimal reproduction project

[Project.zip](https://github.com/godotengine/godot/files/8705839/Project.zip)

**Comment by Calinou** [comment]
These are clustering artifacts. See https://github.com/godotengine/godot/issues/45469.

**Comment by isaacwilliams** [comment]
FYI, in my test cases is appears to be no longer happening in Godot Beta 4 — potentially after https://github.com/godotengine/godot/pull/67915

**Comment by eviltrout** [comment]
I can also confirm that in Godot 4 Beta 4 I am no longer seeing the artifacts.

**Comment by clayjohn** [comment]
I'm not surprised that https://github.com/godotengine/godot/pull/67915 would fix this issue. 

Closing now as fixed by https://github.com/godotengine/godot/pull/67915

If someone can reproduce this issue in Beta 4 or later we can reopen
