### ISSUE TITLE
Crash on same name that declare with function call

### ISSUE THREAD

**Issue by jaydonteh** [godotengine/godot#6111]
**Operating system or device - Godot version:**
Windows 10 - v2.1-stable_win64.exe

**Issue description** (what happened, and what was expected):
Declaring a var with a name and try to attach a function to a same name, it will crash.

**Steps to reproduce:**
Just declare a var and call a function with the same name.
var asd = asd.xxxxx _crash_

**Comment by akien-mga** [comment]
Can't reproduce on Linux (Mageia, 64-bit), so I assume it's a Windows-specific issue. Another Windows user reported something similar on FB.

**Comment by vnen** [comment]
This happens only if the declaration is outside of any function.

**Comment by vnen** [comment]
Ugh, it's the same as #4641 (infinite recursion), but in a another place...

**Comment by reduz** [comment]
does this still happen? some issues that reference this are closed
