### ISSUE TITLE
Addons files not show in "FileSystem" windows automatic

### ISSUE THREAD

**Issue by mefihl** [godotengine/godot#6112]
**Operating system or device - Godot version:**
Windows 10, Godot 2.1 stable

**Issue description** (what happened, and what was expected):
After install addon from assetlib, new addon not show in "FileSystem" windows until switch on other application and go back to godot.

**Steps to reproduce:**
1. Install addon.
2. Look on "FileSystem" window.

**Link to minimal example project** (optional but very welcome):

**Comment by akien-mga** [comment]
Confirmed, I've seen that too while testing.

**Comment by bojidar-bg** [comment]
Is this still an issue (probably yes, but anyway..)

**Comment by KoBeWi** [comment]
Fixed since 3.0
