### ISSUE TITLE
OccluderShapeSphere::_bind_methods: error when try to run using simulator after iOS export

### ISSUE THREAD

**Issue by attunemm** [godotengine/godot#61139]
### Godot version

3.4.4 stable

### System information

macOS Monterey v 12.2 , GLES2

### Issue description

Using the "Best available mirror" export templates from Godot, I exported my game for iOS. The game was able to build, but when I tried to run on any simulator, the below error was thrown each time. I tried creating a completely empty Godot project (just a blank screen), and got the same error. 
After build:
- The launch screen image displayed, then
- The following error was thrown (truncated to the number of lines that were visible on the screen):
stickeynotes`OccluderShapeSphere::_bind_methods: Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
    0x1032e08e0 <+0>:   pushq  %rbp
    0x1032e08e1 <+1>:   pushq  %r15
    0x1032e08e3 <+3>:   pushq  %r14
    0x1032e08e5 <+5>:   pushq  %r13
    0x1032e08e7 <+7>:   pushq  %r12
    0x1032e08e9 <+9>:   pushq  %rbx
    0x1032e08ea <+10>:  subq   $0x88, %rsp
    0x1032e08f1 <+17>:  leaq   0x278(%rip), %rdi         ; OccluderShapeSphere::set_spheres(Vector<Plane> const&)
    0x1032e08f8 <+24>:  xorl   %esi, %esi
    0x1032e08fa <+26>:  callq  0x1032e2420               ; MethodBind* create_method_bind<OccluderShapeSphere, Vector<Plane> const&>(void (OccluderShapeSphere::*)(Vector<Plane> const&))
    0x1032e08ff <+31>:  leaq   0x9102c2(%rip), %rdx      ; "set_spheres"
    0x1032e0906 <+38>:  movl   $0x1, %edi
    0x1032e090b <+43>:  movq   %rax, %rsi
    0x1032e090e <+46>:  xorl   %ecx, %ecx
    0x1032e0910 <+48>:  xorl   %r8d, %r8d
    0x1032e0913 <+51>:  callq  0x1038c81b0               ; ClassDB::bind_methodfi(unsigned int, MethodBind*, char const*, Variant const**, int)
    0x1032e0918 <+56>:  movq   0xb23da1(%rip), %rdi      ; (void *)0x00000001032e0d80: OccluderShapeSphere::get_spheres() const
    0x1032e091f <+63>:  xorl   %esi, %esi
    0x1032e0921 <+65>:  callq  0x1032e2810               ; MethodBind* create_method_bind<OccluderShapeSphere, Vector<Plane> >(Vector<Plane> (OccluderShapeSphere::*)() const)
    0x1032e0926 <+70>:  leaq   0x9102a7(%rip), %rdx      ; "get_spheres"
    0x1032e092d <+77>:  movl   $0x1, %edi
    0x1032e0932 <+82>:  movq   %rax, %rsi
    0x1032e0935 <+85>:  xorl   %ecx, %ecx
    0x1032e0937 <+87>:  xorl   %r8d, %r8d
    0x1032e093a <+90>:  callq  0x1038c81b0               ; ClassDB::bind_methodfi(unsigned int, MethodBind*, char const*,

### Steps to reproduce

1. Create / open a 2D game in Godot 3.4.4. Can be a blank game.
2. Export for iOS using the Best available mirror templates and uncheck "export with debug"
3.  Open with XCode.
4. Adjust XCode settings for the target as needed to get the game to build. (Typically, I have to update the Signing & Capabilities team, exclude arm64 from "Any iOS Simulator SDK" under release.)
5. Add iOS simulators, then select an ipad or iphone from the list  (I've tried iPad 9th generation and iPhone 6)
6. Clean build folder
7. Click run
The project should build, but then give the error related to OccularShapeSphere

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/8711914/test.zip)

**Comment by Calinou** [comment]
Can you reproduce this issue when running the exported project on another platform (such as macOS)?

Also, does this occur when exporting the project to iOS *with debugging enabled*?

**Comment by lawnjelly** [comment]
I've just tried a release export of 3.4.4 (using the downloaded templates) on linux and it works fine. I was of course wondering if I'd done something wrong in the binding.

But I'm now wondering if it could be using the wrong version export template (or a cached version of something), most likely 3.3 template with 3.4 export, as OccluderSpheres were introduced in 3.4. I have no idea what error message would be expected in this situation (normally I would expect the version mismatch would be checked earlier somewhere).

**Comment by attunemm** [comment]
Thank you, Hugo!
The simulator runs without error when I enable debugging.
Do you know if debugging should be enabled for all iOS exports, or just
when using the simulator?

**Comment by Calinou** [comment]
> Do you know if debugging should be enabled for all iOS exports, or just
when using the simulator?

Debugging should be enabled only when you are troubleshooting issues. Otherwise, you should strive to export in release mode to get smaller binaries and better performance.

**Comment by lawnjelly** [comment]
It is possible something is being compiled out in release that is required. But it is strange that it seems to work on some platforms, but not iOS.

The `ClassDB::register_class<OccluderShapeSphere>();` in `register_scene_types.cpp` is enclosed in a `#ifndef _3D_DISABLED` (with the idea that it not be available when 3D is compiled out). Whether that has anything to do with it I don't know.

**Comment by Calinou** [comment]
It might be worth checking whether this issue is fixed in [3.5rc1](https://godotengine.org/article/release-candidate-godot-3-5-rc-1).

**Comment by attunemm** [comment]
> It might be worth checking whether this issue is fixed in [3.5rc1](https://godotengine.org/article/release-candidate-godot-3-5-rc-1).

I just checked in 3.5rc1, and was able to run in the simulator _without debugging enabled_ without getting the OccluderShapeSphere error. Yay!

**Comment by Calinou** [comment]
Closing, as this is resolved in 3.5rc1 (and possibly earlier betas).
