### ISSUE TITLE
EditorPlugin node is not present in 'create new node' window

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#6113]
**Operating system or device - Godot version:**
2.1.0 stable

**Issue description** (what happened, and what was expected):
Since this https://github.com/gau-veldt/godot/commit/c73014bf1d1458d8d470dec8ab87df2aef3be5fa commit `EditorPlugin` node is not present in `Create new node` dialog window. The commit was a fix for https://github.com/godotengine/godot/issues/3263 issue, but I think it was to wide and this node was not meant to be hidden in first place.  As far as I can see other nodes probably hidden by this commit probably indeed were not intended for users to be use, but `EditorPlugin` node is quite crucial when creating tool scripts, and necessity to add it each time to the tree from script and not beeing able to make it scene root feels little dirty to me.  
Besides it even has cool icon that was meant to be presented in inspector :)

**Comment by vnen** [comment]
AIUI the `Editor*` nodes were removed from the dialog because they don't run on the game. So if you add an `EditorPlugin` node and export with a non-tools build, what would happen?

**Comment by reduz** [comment]
Will just runtime error

**Comment by bojidar-bg** [comment]
I guess adding an "Enable editor-only nodes" or similar (since that's pretty bad) checkbox in the node add list might do it

**Comment by kubecz3k** [comment]
Hmm but that means that every project that's using EditorPlugin node will always throw runtime error in production build?

**Comment by bojidar-bg** [comment]
@kubecz3k Those won't be instanced at non-editor runtime anyway

**Comment by neikeq** [comment]
I agree with the option proposed by @bojidar-bg. It would be useful for those building editor plugins.

**Comment by reduz** [comment]
EditorPlugin is meant to be hidden. Editing it in the scene tree makes no
sense.
It will only make users break scenes and not understand why. It already
happened, so I'm against having them in there.
