### ISSUE TITLE
material on surface of MeshInstance2D not work

### ISSUE THREAD

**Issue by PKU-lzk** [godotengine/godot#61147]
### Godot version

3.3.4 stable

### System information

Windows 11, GLES3,  NVIDIA GeForce RTX 2080 Ti (512.20)

### Issue description

I create a MeshInstance2D with a triangle ArrayMesh and texture icon.png. It has no effect when I set a shader_material with the following shader to its unique surface. 
```cpp
shader_type canvas_item;
void fragment() {
	COLOR.rgb = vec3(1.0, 1.0, 1.0);
}
```
While the material of the MeshInstance2D node works.

### Steps to reproduce

create a MeshInstance2D node with the following script
```gdscript
extends MeshInstance2D

func _ready():
	var arrays = []
	arrays.resize(Mesh.ARRAY_MAX)
	arrays[Mesh.ARRAY_VERTEX] = PoolVector2Array([
		Vector2(0, 0), Vector2(0, 512), Vector2(512, 0)
	])
	arrays[Mesh.ARRAY_TEX_UV] = PoolVector2Array([
		Vector2(0, 0), Vector2(0, 1), Vector2(1, 0)
	])
	arrays[Mesh.ARRAY_INDEX] = PoolIntArray([
		0, 1, 2
	])
	texture = load("res://icon.png")
	mesh = ArrayMesh.new()
	mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
	var new_material = ShaderMaterial.new()
	new_material.shader = Shader.new()
	new_material.shader.code = \
"""
shader_type canvas_item;
void fragment() {
	COLOR.rgb = vec3(1.0, 1.0, 1.0);
}
"""
	mesh.surface_set_material(0, new_material)
#	material = new_material
```

### Minimal reproduction project

[Mesh2D_surface_material.zip](https://github.com/godotengine/godot/files/8715272/Mesh2D_surface_material.zip)

**Comment by Calinou** [comment]
Duplicate o
f https://github.com/godotengine/godot/issues/51578.
