### ISSUE TITLE
Put the engine on steam as a free download

### ISSUE THREAD

**Issue by ekaris** [godotengine/godot#6114]
**Issue description** (what happened, and what was expected):
Put the engine on steam as a free download like blender, to help spread the word about it and gather new volunteers along the way

**Steps to reproduce:**
Use early access on steam to submit the project.

**Comment by reduz** [comment]
It's already there..

**Comment by akien-mga** [comment]
https://lmddgtfy.net/?q=godot%20steam

**Comment by ekaris** [comment]
Sorry I didn't see it, but speaking of steam I also say itch.io gog.com etc...

**Comment by Sslaxx** [comment]
For some of those it might be harder than it seems.
