### ISSUE TITLE
Domain Warp isn't moving with the offset of the FastNoiseLite Resource

### ISSUE THREAD

**Issue by Gamemap** [godotengine/godot#61160]
### Godot version

v4.0.alpha8.official [cc3ed63af]

### System information

Windows 11 64 Bit, Vulkan

### Issue description

If I use the offset setting (with domain warp disabled) to change the Noise position everything moves in the direction but if I enable domain warp the edge between the cells isn't moving with the offset.

I hope you can see the changed settings in the video (no code used only the inspector) but if you need I can create a minimal reproduction project.

Domain Warp disabled:

https://user-images.githubusercontent.com/71942164/169098257-e7e5fee7-e070-4fde-b050-b31a27c1b082.mp4

Domain Warp enabled:

https://user-images.githubusercontent.com/71942164/169098343-7627795a-b491-4e72-8416-82dd762d284f.mp4

### Steps to reproduce

1. Create a NoiseTexture
2. add a FastNoiseLite
3. Change the Noise Type to Cellular
4. change the Fractal Type to None
5. change the Return Type to Cell Value
6. Enable the Domain Warp
7. change the Fractal Type to None
8. Move the Noise with the offset

**Comment by Calinou** [comment]
cc @Geometror
