### ISSUE TITLE
Feature request for Visual Scripting: Copy, Cut and Paste nodes between the scripts

### ISSUE THREAD

**Issue by procedural** [godotengine/godot#6117]
I tried to select the nodes and press Ctrl + C for copy or Ctrl + X for cut and in another script Ctrl + V for paste: nothing happens...

It's an important feature because text-based GDScript allows you refactor code easily by copy and pasting code around, so :)

So far I'm having a blast with Visual Scripting, thank you for making it happen!

**Comment by procedural** [comment]
Also, copy-pasting functions, variables and signals between the scripts...

**Comment by vnen** [comment]
Duplicate of #6073.

**Comment by procedural** [comment]
@vnen oh, thanks, didn't noticed that one!
