### ISSUE TITLE
3.5rc1 Clear Recent Files returns out of bounds error

### ISSUE THREAD

**Issue by devlein** [godotengine/godot#61179]
### Godot version

3.5rc1

### System information

Windows 11

### Issue description

If you try to _Clear Recent Files_ in the script editor you get an out of bonds error and the list isn't cleared.

![grafik](https://user-images.githubusercontent.com/104411913/169230796-1b08bacf-ee22-4995-a558-addfa8262651.png)

`editor/plugins/script_editor_plugin.cpp:486 - Index p_idx = 1 is out of bounds (rc.size() = 1)`

It doesn't matter how many files are listed. In 3.4.4, 3.5b5 and 4.0a8 it's working as intendet.

### Steps to reproduce

Open any script and click "Clear Recent Files"

**Comment by timothyqiu** [comment]
#61102 backported #57330. It contains a breaking change that makes `PopupMenu`'s default ID 0-based instead of 1-based.

**Comment by akien-mga** [comment]
Indeed. It was discussed on Rocket.Chat that this wouldn't break compat but obviously this does, it's probably best to revert for 3.5 as it will break all user code.

**Comment by akien-mga** [comment]
> Or maybe only the `PopupMenu` change should be reverted? The `OptionButton` change seem relatively safe to me.

Yeah I think this change is not meant to be there, it was done in #57330 to fix a regression from #54647, which is *not* being backported.

**Comment by okla** [comment]
Sorry for that. Wasn’t sure if I should backport PopupMenu changes too or only OptionButton ones. Should have discussed this better. Also, that’s why a commit should never contain two (or more) distinct changes.

**Comment by akien-mga** [comment]
Fixed by #61181.
