### ISSUE TITLE
StreamPeerTCP client blocked on STATUS_CONNECTING

### ISSUE THREAD

**Issue by CarlCochet** [godotengine/godot#61197]
### Godot version

4.0.dev (fda397b5b)

### System information

Windows 10

### Issue description

I am trying to connect to a TCP server via GDScript to read data sent from Python. 
The code for the TCP client in GDScript is taken from here: https://www.bytesnsprites.com/posts/2021/creating-a-tcp-client-in-godot/

I tested this code on Godot 3.4.4 and Godot4 alpha [fda397b5b]. In Godot 3.4.4, everything worked perfectly, data was read from the TCP server and a "ack" response was sent back that I could read from my Python script. However, in Godot4, the blocked on connecting to host. 

Note that from my Python script I know that the GDScript is indeed attempting to connect, as the TCP server recognizes the client and therefore sends him the data. But on the GDScript side, it stays as STATUS_CONNECTING and never switches to STATUS_CONNECTED. 

The code was slightly altered for Godot4 since a few changes were made to GDScript in this version, namely: 

- `PoolByteArray` was changed to `PackedByteArray`
- signals were refactored to use the new emission syntax
- the `yield` timer was replaced with the `await` syntax. 

### Steps to reproduce

- Open a local TCP server
- Try to connect to it with the code linked in description and modifications that were described

On Godot3 it should work and Godot4 should stay stuck in CONNECTING. 

### Minimal reproduction project

I do not have a minimal TCP server creation script but one is linked with the rest of the code example in the description.

For the Godot projects: 
- Godot4: [simenv-godot4.zip](https://github.com/godotengine/godot/files/8732094/simenv-godot4.zip)
- Godot3: [TestTCP_godot3.zip](https://github.com/godotengine/godot/files/8732101/TestTCP_godot3.zip)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/60664. This was supposed to be fixed by https://github.com/godotengine/godot/pull/60761.

**Comment by Faless** [comment]
You need to `poll` the `StreamPeerTCP` to update its state after #59582 .
This is intended, and also mentioned in the [updated docs](https://github.com/godotengine/godot/pull/59582/files#diff-53565745d4ca203713b04f09788d1418e8017119c254b187982077ea8f16dd16), though it could clarified.

**Comment by CarlCochet** [comment]
Indeed I looked at the incorrect version of the docs, thanks!

**Comment by olixis** [comment]
For me, still not working on godot4 beta10, get_status() always returns "connecting/1" and poll() always returns "NONE/0" enums. On the server side it says that the client is connected.
