### ISSUE TITLE
connect() autocompletion for custom signals

### ISSUE THREAD

**Issue by ackens** [godotengine/godot#6120]
It would be nice if the autocompletion for connect() function included user-defined signals(with the "signal" keyword).
Like

```
signal my_signal

func _ready()
     connect( *this would suggest "my_signal" as well* , self, "_on_my_signal")
```

**Comment by MarianoGnu** [comment]
this looks like it's fixed already, can you confirm?

By the other hand, looks like emit_signal function is not autocompleting at all, y did a quick fix for this, but i have an unrelated opened pull request and not the time to setup a new branch right now

**Comment by akien-mga** [comment]
In my tests it works if the scene that loads this script is open, and it doesn't work if it's not open - but that's the same behaviour for autocompletion of node names, etc., so not specific to custom signals.
