### ISSUE TITLE
CSGMesh with assigned mesh crashes editor

### ISSUE THREAD

**Issue by TitanNano** [godotengine/godot#61200]
### Godot version

v3.5.rc1.official [f33899d5b]

### System information

macOS 12, M1 Pro, GLES 3

### Issue description

When trying to open a scene that contains a CSGMesh with an assigned mesh, the engine crashes.

```
ERROR: FATAL: Index p_index = 1 is out of bounds (((Vector<T> *)(this))->_cowdata.size() = 0).
   at: operator[] (./core/vector.h:49)
Trace/BPT trap: 5
```

### Steps to reproduce

1. create a new 3D scene
2. add a CSGMesh node
3. assign a mesh to the node
4. save project
5. reload current project
6. open scene

### Minimal reproduction project

[GodotCSGMeshCrasher.zip](https://github.com/godotengine/godot/files/8733174/GodotCSGMeshCrasher.zip)

**Comment by Calinou** [comment]
@TitanNano Does it crash in 3.4.4 or previous 3.5 betas?

**Comment by TitanNano** [comment]
@Calinou no crash in 3.4.4. Other betas I haven't tested yet.

**Comment by TitanNano** [comment]
| Version | Crash |
|---------|-------|
| 3.5 Beta 1 | ✅ |
| 3.5 Beta 2 | ✅ |
| 3.5 Beta 3 | ✅ |
| 3.5 Beta 4 | ✅ |
| 3.5 Beta 5 | 💥 |

**Comment by akien-mga** [comment]
I didn't bisect but this could be caused by #59381 maybe, CC @gaudecker.
