### ISSUE TITLE
top texture of cubemesh rotated 180°

### ISSUE THREAD

**Issue by Drachenbauer** [godotengine/godot#61229]
### Godot version

v3.4.3

### System information

Windows 11, GLES3, Intel(R) UHD Graphics

### Issue description

If i put two mesh instances one with a cubemesh and one with a planemesh next to each other, apply the same texture and rotate the perspective until she positive end of the x-axis points to the right, the texture on the planemesh appears upright, but the one ontop of the cubemesh appears upsidedown
![texture rotated](https://user-images.githubusercontent.com/47259059/169573393-23fd6b19-8e96-4dd0-be61-b18a831b4704.png)
left side: cubemesh with upside down top texture 
right side: two planemeshes aligned with the top and bottom of the cube

Why it´s rotated this way on the cube?

### Steps to reproduce

just every time using a cubemesh

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/19143.

**Comment by Drachenbauer** [comment]
it seems like it is the normal behavior of cubemesh.
i just wonder, why the developers made the top texture appear this way around.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
