### ISSUE TITLE
3.5 RC1 Mono crashes on project manager

### ISSUE THREAD

**Issue by okla** [godotengine/godot#61234]
### Godot version

3.5 RC1

### System information

Windows 10, GeForce 1060

### Issue description

Freshly installed Godot editor 3.5 RC1 Mono crashes right after a project manager screen is presented

### Steps to reproduce

1. Download and unpack Godot editor 3.5 RC1 Mono
2. Launch editor

### Minimal reproduction project

Not sure how to collect a crash report

**Comment by akien-mga** [comment]
Indeed, that's a know issue. See #61176.
