### ISSUE TITLE
GLB/GLTF import, texture sampling missing on imported materials

### ISSUE THREAD

**Issue by alazifk** [godotengine/godot#61232]
### Godot version

4.0 alpha 7

### System information

Win 10

### Issue description

I tried importing a *.glft model from blender with the albedo filtering set to "closest". The resulting mesh has linear-mipmap filtering instead.

In *.glft textures may reference a sampler:
```
    "textures": [
        {
            "sampler": 0,
            "source": 2
        }
    ]
```
Samplers hold filtering and wrapping data:
```
    "samplers": [
        {
            "magFilter": 9729,
            "minFilter": 9987,
            "wrapS": 10497,
            "wrapT": 10497
        }
    ]
```
https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#_filtering

[gltf_texture.h](https://github.com/godotengine/godot/blob/master/modules/gltf/gltf_texture.h) does not mention the sampler, so I assume it is just missing and that the wrapping settings are not imported either.

### Steps to reproduce

Try importing a *.glft with filtering mode `NEAREST`/`LINEAR`. Model is provided in the attachment.
Then check `Mesh/Surface1/Material/Sampling/Filter` or zoom deep into the provided models dead, uncaring eyes and fail to see pixels.

### Minimal reproduction project

[nearest_cube.zip](https://github.com/godotengine/godot/files/8743557/nearest_cube.zip)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/45206 (which is the same issue, but in `3.x` where texture filtering modes are defined on *textures* and not on *materials*).

This will be fixed by https://github.com/godotengine/godot/pull/59481 once it's merged.
