### ISSUE TITLE
GDScript 2.0: Lambda parsing error if followed by an `if` statement

### ISSUE THREAD

**Issue by giffi-dev** [godotengine/godot#61231]
### Godot version

4.0.alpha8

### System information

Windows 10

### Issue description

Something gets parsed wrong if lambda decleration is followed by an if statement.

### Steps to reproduce

This snippet of code gives an error "Expected 'else' after ternary operator condition."
```gdscript
func _ready() -> void:
	var my_lambda := func():
		print("hello world")
	if 0.0 == 0.0:
		my_lambda.call()
```

If there's something in between the if statement and the lambda decleration the code gets correctly parsed, for example.
```gdscript
func _ready() -> void:
	var my_lambda := func():
		print("hello world")
	print("hello world")
	if 0.0 == 0.0:
		my_lambda.call()
```

**Comment by AndersonDeMatos** [comment]
I had encountered the same bug in alpha 8.0 using Linux Mint 20.3 Cinnamon. 
![Screenshot from 2022-05-22 21-39-10](https://user-images.githubusercontent.com/72280012/169723740-be32b011-207a-48f3-9d29-9ec92c6e81ab.png)
If I toggle the comment off on the line where the `pass` keyword is, the code works as expected.
