### ISSUE TITLE
Vulkan: Shader compilation stutter when materials enter the view frustum for the first time (unless cached)

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#61233]
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

4.0.alpha8

### System information

Fedora 36, GeForce GTX 1080 (NVIDIA 510.68.02)

### Issue description

A noticeable shader compilation stutter occurs when materials enter the view frustum for the first time (unless cached). This is more visible on lower-end CPUs/GPUs which take a longer time to compile shaders.

Labeling `regression`, as [ubershaders](https://github.com/godotengine/godot/pull/53411) make it possible to avoid the initial stutter (on cold cache) in 3.5 with GLES3.

### Steps to reproduce

- Open the minimal reproduction project. If you can't notice shader compilation stuttering in that project, try https://github.com/godotengine/godot-demo-projects/pull/743 instead.
- Run the project and wait for stuttering to occur due to shader compilation.
- Run the project a second time and notice there won't be stuttering anymore.
- Remove the shader cache folder (`.godot/shader_cache/` within the project folder).
- Run the project again, and notice stuttering occurring once again.

### Minimal reproduction project

[test_shader_compilation_stutter.zip](https://github.com/godotengine/godot/files/8743855/test_shader_compilation_stutter.zip)

**Comment by tinmanjuggernaut** [comment]
GD4 Beta4 still stutters quite a bit on load with a lot of assets. You need to force precompilation of shaders.

https://github.com/godotengine/godot/pull/53411#issuecomment-935537126

https://github.com/godotengine/godot/pull/46330#issuecomment-786280648

**Comment by Calinou** [comment]
> what now?

I think adding a true asynchronous shader compilation mode is the way to go – essentially mimicking [dxvk-async](https://github.com/Sporif/dxvk-async) behavior. It causes objects to be temporarily invisible until their shaders are compiled, but this is far preferable to stutter in 99% of situations.

**Comment by clayjohn** [comment]
Hopefully we can do most of it in time for the stable release.

**Comment by warriormaster12** [comment]
Since VkGraphicsLibrary extension is available almost with every single gpu vendor, could that solution be considered for stuttering problem 🤔

**Comment by warriormaster12** [comment]
Would be interesting to try and implement it since I've been doing multiple personal vulkan projects and I'd like to put it to use.

**Comment by jcarlosrc** [comment]
The problem is still present in 4.1 (Mobile at least).

**Comment by cosmoddd** [comment]
Still an issue on desktop as well.  Able to reproduce by clearing the cache shaders in my project file and NVIDIA cache folder, then restarting the game.  Only happens the first time.

**Comment by elvisish** [comment]
Is it not possible for Godot 4.x to use the asynchronous compilation technique 3.5 does? I'm having huge stutters whenever I turn a light on or add a light to the scene (even when using preload()) and I'm not sure what the current workaround is.

**Comment by warriormaster12** [comment]
I don’t think that adding a light to the scene causes a pipeline compilation🤔 though someone more knowledgeable can correct me. Does the stutter happen every single time when you add a light?

**Comment by elvisish** [comment]
> I don’t think that adding a light to the scene causes a pipeline compilation🤔 though someone more knowledgeable can correct me. Does the stutter happen every single time when you add a light?

It happens the first time a new light is added or turned on, but then it's fine each time you do it after (as if it's become cached).

**Comment by warriormaster12** [comment]
It is cached. Pipeline caching was introduced in 4.1 on top of shader caching. You can find it in `user://vulkan` folder. Deleting that folder will most likely trigger the stutter again unless your gpu driver has made its own cache.

**Comment by cosmoddd** [comment]
I can retrigger the stutter by deleting specific cache files in my graphics card settings folders.  This resets the process of re-caching.  When a new shader or post processing effect is enables it happens then, too.  When the game is launched on a version update, it happens though not as severe. Would need to test further to provide feedback there.  

I look longingly at Steam's  "precompile vulkan shaders" message which comes up when I launch certain games through that platform.  I'm wondering if there's something to be gleaned from that approach.

**Comment by elvisish** [comment]
> It is cached. Pipeline caching was introduced in 4.1 on top of shader caching. You can find it in `user://vulkan` folder. Deleting that folder will most likely trigger the stutter again unless your gpu driver has made its own cache.

Are lights considered shaders to be cached, though? I'm only having this issue with lights, I'm not even having trouble with changing materials it just seems to happen when lights are enabled or added to the scene enabled.

**Comment by Calinou** [comment]
> I look longingly at Steam's "precompile vulkan shaders" message which comes up when I launch certain games through that platform. I'm wondering if there's something to be gleaned from that approach.

This works by making users compile and upload shaders after they're done playing a game. It works because Steam has such a large network of users that you're almost guaranteed to be able to download a compiled shader that matches your OS, GPU and driver version (all 3 need to match exactly).

It is possible for Godot games on Steam to use this approach if they use a Vulkan-based rendering method.

**Comment by warriormaster12** [comment]
Geaphics pipeline library could help with invisible meshes in async compilation by creating a fast linked pipeline first before doing final optimized version and by recycling pipeline stages as much as possible. But it would require first to have async compilation infrastructure in place if we want to take advantage of that extension.

**Comment by warriormaster12** [comment]
At least that’s my understanding that I got after writing GPL draft pr.

**Comment by elvisish** [comment]
Here's a clip someone sent me of them playing a game I'm beta testing through Steam (so it's built and run via Steam), you can see a huge lag when the flashlight goes on the first time and not subsequent times (the flashlight is already added to the scene on ready, this is enabling it):

https://github.com/godotengine/godot/assets/16231628/89dcd418-b0bc-45a8-a9c9-7b02844d1773

Here's another when a light is removed from the scene, and one after when a light behind the wall is instatiated (it's not seen in this clip):

https://github.com/godotengine/godot/assets/16231628/8f1bee39-1a5c-41c6-96af-3b0b792f3c67

This seems like an issue with compilation stutter, is this expected behavior with lights being added to the scene/enabled?

**Comment by TokisanGames** [comment]
Shaders are compiled per lighting setup, or at least they were in gd3. The only reliable way we've found to reduce stutter is force precompilation. I linked instructions in my comment above.

**Comment by elvisish** [comment]
> Shaders are compiled per lighting setup, or at least they were in gd3. The only reliable way we've found to reduce stutter is force precompilation. I linked instructions in my comment above.

Essentially the 4.x version of this? https://github.com/Brandt-J/ShaderPrecompiler

I think for the time being a built-in node or even an addon like this would be a good immediate solution so people can avoid as much stutter as possible out-of-the-box (as you mentioned in your comment, 99% of the stuttering https://github.com/godotengine/godot/pull/46330#issuecomment-786280648)

**Comment by elvisish** [comment]
I forked Brandt-J's to 4.x: https://github.com/elvisish/ShaderPrecompiler4x

It seems to work okay from what I can tell, but this should hopefully serve as a bandaid until something can be implemented in 4.x.
