### ISSUE TITLE
2d rigid body go fast as light

### ISSUE THREAD

**Issue by TOP420** [godotengine/godot#61241]
### Godot version

3.4.4

### System information

Windows 11

### Issue description

so im working on kinematic to rigid body interactions but im running into this issue where the rigid body wont stop moving unitil I start moving again

### Steps to reproduce

1. kinematic body with script attatched like this:
2.

```gdscript
extends KinematicBody2D

export (float) var speed
# Declare member variables here. Examples:
# var a = 2
# var b = "text"
var random = RandomNumberGenerator.new()

# Called when the node enters the scene tree for the first time.
func _ready():
	print("Started Up")
	print(scale)
	speed *= 100

# Called every frame. 'delta' is the elapsed time since the previous frame.
#func _process(delta):


#	pass

func _physics_process(delta):
	var random_number = random.randf_range(-0.5,0.5)
	var speed2 = -speed*delta
	
	if Input.is_key_pressed(KEY_W):
		move_and_slide(Vector2(0,speed2),Vector2.ZERO,false,4,4/PI,false)
	if Input.is_key_pressed(KEY_S):
		move_and_slide(Vector2(0,-speed2),Vector2.ZERO,false,4,4/PI,false)
	if Input.is_key_pressed(KEY_A):
		move_and_slide(Vector2(speed2,0),Vector2.ZERO,false,4,4/PI,false)
	if Input.is_key_pressed(KEY_D):
		move_and_slide(Vector2(-speed2,0),Vector2.ZERO,false,4,4/PI,false)
	for i in get_slide_count():
		var collision = get_slide_collision(i)
		if collision.collider.get_class() != "StaticBody2D":
			print(collision.collider.get_class())
			collision.collider.apply_impulse(Vector2.ZERO,-collision.normal*50)
```

3. Add rigid body
4. play
5. while block is on you press and release w really fast
https://user-images.githubusercontent.com/105966575/169641476-f45e3119-1fef-49f0-b370-bd8676a388a9.mp4

zip project:
[COCTD1.zip](https://github.com/godotengine/godot/files/8747197/COCTD1.zip)

**Comment by Calinou** [comment]
PS: Code blocks should use triple backticks like this (with an optional language name for syntax highlighting):

\`\`\`gdscript
code here
\`\`\`

I edited your post accordingly, but remember to do this in the future :slightly_smiling_face:

**Comment by MewPurPur** [comment]
Minimal script:
```extends KinematicBody2D

func _physics_process(delta):
	if Input.is_action_pressed("ui_up"):
		move_and_slide(Vector2.UP*100, Vector2.ZERO, false, 4, 4/PI, false)
	for i in get_slide_count():
		var collision = get_slide_collision(i)
		if collision.collider is RigidBody2D:
			collision.collider.apply_impulse(Vector2.ZERO, -collision.normal*50)```

**Comment by TOP420** [comment]
ok thanks I will make sure to change to backticks for code

**Comment by TOP420** [comment]
I changed the can sleep to off but its still doing the thing that the video shows

**Comment by Hiiamwilliam** [comment]
I think it's not a bug. On the documentation of `get_slide_count` and `get_slide_collision` it's implied that results are cached: 

> Returns * _information about collision that happened_ * during the last call to [move_and_slide] [...]

In OP's code, `move_and_slide` is called only when a key is pressed during `physics_process`. So if you press a key really fast and let go, during a single physics frame `move_and_slide` will be called, caching collision information. Since it applies impulse every frame, the `RigidBody` will be flung upwards as shown.

**Comment by TOP420** [comment]
seems to be working now thanks!
