### ISSUE TITLE
GDScript 2.0: Parser bug when no preload path given

### ISSUE THREAD

**Issue by snailrhymer** [godotengine/godot#61248]
### Godot version

v4.0.alpha8.official [cc3ed63af]

### System information

Pop!_OS 22.04 LTS 64-bit

### Issue description

A parser error is printed when preload is used without a path:

` modules/gdscript/gdscript_analyzer.cpp:656 - Parser bug (please report): tried to assign unset node without an identifier.`

### Steps to reproduce

Add the following to a Node:
```gdscript
extends Node

var preloaded_var = preload()
```
The error is printed whenever the script is reparsed, until a path is added to the preload.

**Comment by Calinou** [comment]
@_CHANGEME Can you (or anyone else) still reproduce this bug in [Godot 4.0.beta16](https://godotengine.org/article/dev-snapshot-godot-4-0-beta-16) or any later release?
