### ISSUE TITLE
project setting/render/shadows_enabled has no effect on DirectionalLight

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#6124]
**Operating system or device - Godot version:**
2.0.4.1 win64 official
2.1stable win64 official

**Issue description** (what happened, and what was expected):

It seems that the project setting Render / shadows_enables has no effect on DirectionalLight's shadows.

It only has an effect on OmniLights.

(btw SpotLight shadows seems broken)

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by Calinou** [comment]
There is no longer a project setting to toggle shadow rendering as of Godot 3.0, so this issue is no longer relevant.
