### ISSUE TITLE
"... drivers/vulkan/vulkan_context.cpp:159 @ _debug_messenger_callback()" Error in Output

### ISSUE THREAD

**Issue by dcrawl** [godotengine/godot#61252]
### Godot version

4.0 dev alpha 8

### System information

MacOS 12.3.1 Arm64

### Issue description

I just created a new empty project with a Node2D as root of the only scene and ran it.  I get the following error in the output:

E 0:00:00:0055   _debug_messenger_callback: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
	vkCreateDevice: Attempting to create a VkDevice from a VkPhysicalDevice which is from a portability driver without the VK_INSTANCE_CREATE_ENUMERATE_PORTABILITY_BIT_KHR bit in the VkInstanceCreateInfo flags being set and the VK_KHR_portability_enumeration extension enabled. In future versions of the loader this VkPhysicalDevice will not be enumerated.
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 5235283456
  <C++ Source>   drivers/vulkan/vulkan_context.cpp:159 @ _debug_messenger_callback()

### Steps to reproduce

After compiling Godot 4, I created a new project.
Chose the Node2D as the root. 
Saved
Marked Main Scene
Run
Error appears in output

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/8747865/Test.zip)

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by vitorventurin** [comment]
up

**Comment by Calinou** [comment]
> up

Which Godot version can you reproduce this on, and what specs does your device have?

**Comment by DatBrute** [comment]
v4.0a9

RTX 3050

**Comment by akien-mga** [comment]
Is this still reproducible in 4.0 RC 3 or later?

**Comment by dcrawl** [comment]
I'm not seeing the error when I use the released binary version.  I haven't tried to compile it myself since the binaries were released.  I created a new project using the Forward+ option which I'm guessing is the same as the options I had before.

**Comment by akien-mga** [comment]
Great! Closing as fixed then.
