### ISSUE TITLE
Redo the creation of the root node doesn't updates the scene tree

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#6125]
Tested on Godot 2.1, Windows 10 64 bits

When I delete the root node, then undo, then redo, the node is created again but not shown in the hierarchy. Adding a second node shows the tree again.

Repro:
1) Create empty scene
2) Add a root node
3) Undo
4) Redo: notice the node doesn't appears

**Comment by suptoasty** [comment]
I have also been experiencing this bug on Linux Mint 18, using Godot Engine 2.1 64-bit Stable.
