### ISSUE TITLE
Error while setting Expand Icon using Multi-Select

### ISSUE THREAD

**Issue by dcrawl** [godotengine/godot#61267]
### Godot version

4.0 dev alpha 8

### System information

MacOS 12.3.1 Arm64

### Issue description

I received this series of errors after I must-selected three buttons and clicked the Expand Icon checkmark.  Then I unchecked it and got the second error.

  core/object/undo_redo.cpp:326 - Error calling UndoRedo method operation 'refresh': 'EditorInspector::refresh': Method not found.
MultiNode Set expand_icon
  core/object/undo_redo.cpp:326 - Error calling UndoRedo method operation 'refresh': 'EditorInspector::refresh': Method not found.
MultiNode Set expand_icon

### Steps to reproduce

Create a new project.
Create a Control node as the scene root
Add two buttons as children
Select both buttons and click the Expand Icon check mark.

### Minimal reproduction project

[Uploading Test.zip…]()

**Comment by Calinou** [comment]
This is an error I've seen numerous times when toggling various properties. It's not specific to Expand Icon.

**Comment by kleonc** [comment]
`EditorInspector::refresh` was removed in #45879 but seems like there are some leftover `UndoRedo` actions trying to call it.
