### ISSUE TITLE
Add scaling image in list addon to one size

### ISSUE THREAD

**Issue by mefihl** [godotengine/godot#6127]
**Operating system or device - Godot version:**
Windows 10, Godot 2.1 stable.

**Issue description** (what happened, and what was expected):
List addon are not in one vertical line. To prevent this add scaling image to one size.
![66666666666666666666666666666666666](https://cloud.githubusercontent.com/assets/5302754/17614677/643c197c-6068-11e6-8b93-5693bf5a4c3b.png)

**Steps to reproduce:**
Open Assetlib.

**Link to minimal example project** (optional but very welcome):

**Comment by mefihl** [comment]
I'am fix this by very dirty code ;): https://github.com/mefihl/godot/commit/501391c659f25a87b29db5217d30643403501450.
This code change size of image icon to constant value 80,80.

**Comment by Calinou** [comment]
It seems this has been fixed a while ago, closing.
