### ISSUE TITLE
Creating CSGs Crashes Godot

### ISSUE THREAD

**Issue by bjr29** [godotengine/godot#61289]
### Godot version

v4.0.alpha8.official [cc3ed63af]

### System information

64 Bit Windows 10

### Issue description

I created a csg box in my scene and it caused a crash, I tested other csgs and got the same result. I can't reload the scene if the csg was in it.

### Steps to reproduce

Create a csg box object anywhere in the scene.

**Comment by akien-mga** [comment]
Probably a duplicate of #61200, fixed by #61213.
