### ISSUE TITLE
Asset store is ignoring zip files root folder

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#6129]
**Operating system or device - Godot version:**
Godot 2.1.0 stable

**Issue description** (what happened, and what was expected):
I moved all my plugins into single repository and created zip files manually, inside zip I have folder structure like "addons/plugin_name/...".
It turned out that when users are downloading those plugins they are unziped in project root folder instead of addons.
The way how it works currently is probably dictated by the way how github creates archives. Archives from github have additional artificial root folder with repositor-commitHash name, and this is why assetlib is removing this directory.
I think there is need to recognize if archive is from github or not, guess simple check for root folder name would be enough (if it's named addons then no need to remove root folder).
Also I think  this can be solved with docs for now, but I in the future some recognition mechanism would be cool.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by bojidar-bg** [comment]
Is this still an issue with newer assetlib?

**Comment by akien-mga** [comment]
There's no longer support for providing home made zips, so no.
