### ISSUE TITLE
Viewport Nonsense!

### ISSUE THREAD

**Issue by Neuroburst** [godotengine/godot#61298]
### Godot version

3.4.stable

### System information

Windows 10, OpenGL ES 3.0 Renderer: AMD Radeon(TM) Graphics

### Issue description

If I make a custom viewport texture with the viewport path as "/root/" and save it as a file, I can make a sprite with the viewport texture and have nonesense!!!

Result:
![image](https://user-images.githubusercontent.com/69093127/169724825-bc695f0e-b081-4a37-affa-2ebd32088fe3.png)

To be completely honest, I'm not sure anyone cares about this bug lol

### Steps to reproduce

Look at the simple project and follow the directions!

### Minimal reproduction project

[Viewport Nonsense.zip](https://github.com/godotengine/godot/files/8750616/Viewport.Nonsense.zip)

**Comment by timothyqiu** [comment]
This is expected. `/root` is an absolute node path that points to the root Viewport.

You can see that Viewport in the remote scene tree:

![ksnip_20220523-092216](https://user-images.githubusercontent.com/372476/169726262-5b88f051-98af-4db1-98b2-0a376d23b9b5.png)

**Comment by Neuroburst** [comment]
but why is the root viewport rendering the editor itself?

**Comment by timothyqiu** [comment]
You may have heard before that the Godot editor _is_ a game powered by the engine itself. So the editor interface is just a scene of the "Editor Game". Thus using `/root` to get node in the editor is accessing the editor's root Viewport.

**Comment by Neuroburst** [comment]
ohh thanks

this is funny, but I'll just close it
