### ISSUE TITLE
No way to easily remove invalid tiles outside the texture

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#61296]
### Godot version

01d383a

### System information

Windows 10 x64

### Issue description

I have a tileset and somehow it got some tiles outside the visible area. Now it keeps spamming errors about it like 
```
ERROR: Cannot create tile. The tile is outside the texture or tiles are already present in the space the tile would cover.
   at: (scene/resources/tile_set.cpp:3854)
ERROR: The TileSetAtlasSource atlas has no tile at (28, 4).
````
and I can't do anything about it aside from editing the tres file manually or making the tiles smaller and removing what shouldn't be there (but this requires reloading the project, as the invalid tiles won't simply appear).

There should be some way to remove tiles outside the texture size.

### Steps to reproduce

1. Create a tileset texture
2. Fill it with tiles
3. Crop it
4. Some tiles are now outside the texture and will spam you forever

### Minimal reproduction project

[Tilebreak.zip](https://github.com/godotengine/godot/files/8750482/Tilebreak.zip)
Example broken tileset.

**Comment by em-s-h** [comment]
I have the same issue, I hope a better way of removing invalid tiles is added soon.

**Comment by Isenther** [comment]
Oh, this is a problem from way back 2022, its quite annoying, it should be made so that the tiles outside the texture are simply deleted.

**Comment by qalmurri** [comment]
If you have a 32x32.png spritesheet for Isometric. In Tilemap, use Isometric 32x32 first, then import spritesheet 32x32.png. If so, set the Tilemap to 32x16. It's like a reversal method. You have to try it

**Comment by YashConnorJade** [comment]
Remove tile outside the texture is greyed out. How can I fix it???

**Comment by KoBeWi** [comment]
That means there are no tiles outside texture or they are not detected (#85661). Do you get any errors?
