### ISSUE TITLE
Asset lib is unable to download zips from Github releases

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#6131]
**Operating system or device - Godot version:**
2..1.0

**Issue description** (what happened, and what was expected):
I have one repository with all my plugins. When I want to make a release I'm zipping them, creating new github release and upload those zips to release. The problem is that Godot asset store for some reason is unable to download those zips, I got 403 code:
![403](https://cloud.githubusercontent.com/assets/6129594/17619881/9a2f4e9e-6088-11e6-8cfc-98daab15289b.png)

Zip links comes from here: 
https://github.com/kubecz3k/KivanoGodotPlugins/releases/tag/InitialRelease

**Comment by kubecz3k** [comment]
@bojidar-bg could you take a look at this?

**Comment by bojidar-bg** [comment]
I'll be HDD-less until Monday, can't have a look until then, sorry

**Comment by akien-mga** [comment]
Haven't experienced this recently.
