### ISSUE TITLE
`Camera2D.get_camera_screen_center()` does not return desired position

### ISSUE THREAD

**Issue by ron0studios** [godotengine/godot#61318]
### Godot version

3.4.4-stable

### System information

Arch linux

### Issue description

When using the function get_camera_screen_center() to fetch the position of a camera, with limits and drag margins applied,m the function always returns (0,0) regardless of where the camera is positioned. I am trying to implement a camera-to-camera transition system.
The camera has set limits, but no smoothing or enabled drag margin
However, here's the weird part that got me to write this issue in the first place, once I set the camera to be current, the get_camera_screen_center() DOES return the correct value. Is this something to do with the camera not adjusting itself beforehand?

### Steps to reproduce

- create a camera that follows the player (source)
- have a transition camera that is a global autoload camera
- create another camera to transition to (destination)
- have a function that Tweens between source.get_camera_screen_center() to destination.get_camera_screen_center()
- the camera transitions to (0,0) and then snaps jaggedly to the actual camera position

**Comment by Calinou** [comment]
@ron0studios Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened

**Comment by rnoriega31** [comment]
Can confirm this still happens in `4.3.stable`.

**Comment by Calinou** [comment]
@rnoriega31 Could you upload a minimal reproduction project?

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
