### ISSUE TITLE
gdscript: @export does not support custom hints (e.g. `suffix:`)

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot#61325]
### Edit 2023-11-30, on 4.2.stable:

I should clarify exactly what the current behavior is. `@export` does not support any arguments, there is no `@export_custom` yet.

`@export_range` doesn't work for me in 4.2.stable: `@export_range(0.0, 1.0, 0.001, "suffix:m")`

However, I managed to solve my use case with this: `@export_range(0.0, 90.0, 0.001, "radians_as_degrees")`

For a suffix of °

---

### Godot version

v4.0.alpha.custom_build [a76db3459]

### System information

Arch 5.15.41-1-lts

### Issue description

```gdscript
@export_custom("suffix:m") var pos: Vector3
```

Should result in:
![image](https://user-images.githubusercontent.com/14253836/169866918-ded9a330-b499-4ee2-8c7c-9c8bf0bb3e19.png)

The basic fix is pretty simple:

1) https://github.com/godotengine/godot/blob/master/modules/gdscript/gdscript_parser.cpp#L115

```diff
- register_annotation(MethodInfo("@export"), AnnotationInfo::VARIABLE, &GDScriptParser::export_annotations<PROPERTY_HINT_NONE, Variant::NIL>);
+ register_annotation(MethodInfo("@export", { Variant::STRING, "hint" }), AnnotationInfo::VARIABLE, &GDScriptParser::export_annotations<PROPERTY_HINT_NONE, Variant::NIL>, 1);
```

2) https://github.com/godotengine/godot/blob/master/modules/gdscript/gdscript_parser.cpp#L3543

```diff
- variable->export_info.hint_string = Variant::get_type_name(export_type.builtin_type);
+ variable->export_info.hint_string += "," + Variant::get_type_name(export_type.builtin_type);
```

But this won't complain if it's invalid (e.g. `@export("suffix:m") var flag: bool`).

### Steps to reproduce

1. Try exporting a variable with a suffix

**Comment by RadiantUwU** [comment]
On godot v4.2.1.stable.mono.official [b09f793f5]
```gdscript
@export_range(0, 4273.15, 0.01, "or_greater", "suffix:K") var melting_point: float = 273.15
```
works as expected

**Comment by AThousandShips** [comment]
That's not what was asked for, you can use `suffix` without `PROPERTY_HINT_RANGE`, so this requires dedicated syntax
