### ISSUE TITLE
Editor Log doesn't activate scroll immediately when needed

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#61324]
### Godot version

a76db34

### System information

Windows 10 x64

### Issue description

![godot windows tools 64_Gmkk8PKIX4](https://user-images.githubusercontent.com/2223172/169857780-c41598da-36b8-4b31-a379-222eae9fe2b2.gif)

### Steps to reproduce

1. Print something that's longer than Output box height
2. You can't scroll
3. The scroll appears when you switch to another tab and back

**Comment by AlbertFay** [comment]
The scroll in the Output only seems to appear when the window is not in focus. I created a script to run fill the Output with test lines and ran it with Play Scene (F6). While the running scene was focused, the text would automatically add the scroll, but when the main window was selected, the text would not automatically add the scroll.


This is when running the scene then clicking the main window before text in Output would fill.
![Output scroll not showing](https://user-images.githubusercontent.com/65504787/171054486-d84a5365-5e90-4df7-a164-4dcad2f9db2e.gif)


This is when running the scene and leaving the scene as focused window. The scroll appears.
![Output scroll showing](https://user-images.githubusercontent.com/65504787/171054595-5087ccc4-6fb0-4ed8-81ae-6410bd2db326.gif)

Inside, in `rich_text_label.cpp` the function `void RichTextLabel::_process_line_caches()` is suppose to determine whether the scroll is visible or not.
