### ISSUE TITLE
Godot 3.5 RC1 crashes Project Manager, crashes trying to exit Editor, extremely slow

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot#61331]
### Godot version

3.5 RC1

### System information

Windows 7 64-bit

### Issue description

The project manager crashes when clicking a project to open, but the editor opens. Then if I try to exit the editor, it crashes. The project manager is slow to load, the editor is slow to load the project and finally the game itself runs slowly and jittery.

### Steps to reproduce

1. Download 3.5 RC1.
2. Open any project made with 3.4 in it.

**Comment by Chaosus** [comment]
Please provide more information about your system: CPU model, video card series and video driver version.

**Comment by akien-mga** [comment]
Does it crash on *any* project? Or only specific ones? If the latter, what kind of features are you using in these projects?

**Comment by elvisish** [comment]
> Please provide more information about your system: CPU model, video card series and video driver version.
CPU model: Intel i7-4700MQ
video card series: Nvidia GeForce GT 755M/Intel HD Graphics 4600
video driver version: 425.31

**Comment by elvisish** [comment]
> Does it crash on _any_ project? Or only specific ones? If the latter, what kind of features are you using in these projects?

It's a new project I started a few days ago, no special features just gridmap and some AnimateSprite3D nodes.

**Comment by elvisish** [comment]
Here's the project manager crash:
```
 Problem Event Name:	APPCRASH
        Application Name:	Godot_v3.5-rc1_win64.exe
        Application Version:	3.5.0.0
        Application Timestamp:	00000000
        Fault Module Name:	Godot_v3.5-rc1_win64.exe
        Fault Module Version:	3.5.0.0
        Fault Module Timestamp:	00000000
        Exception Code:	c0000005
        Exception Offset:	0000000002852a27
        OS Version:	6.1.7601.2.1.0.256.1
        Locale ID:	2057
        Additional Information 1:	e639
        Additional Information 2:	e639ed969b2d1b2f1a2f7674cba4e69c
        Additional Information 3:	3484
        Additional Information 4:	3484d60399985e369cecd162201dfa15
```
And here's the Editor crash:
```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	Godot_v3.5-rc1_win64.exe
  Application Version:	3.5.0.0
  Application Timestamp:	00000000
  Fault Module Name:	Godot_v3.5-rc1_win64.exe
  Fault Module Version:	3.5.0.0
  Fault Module Timestamp:	00000000
  Exception Code:	c0000005
  Exception Offset:	0000000002852a27
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	2057
  Additional Information 1:	e639
  Additional Information 2:	e639ed969b2d1b2f1a2f7674cba4e69c
  Additional Information 3:	3484
  Additional Information 4:	3484d60399985e369cecd162201dfa15
```

**Comment by lawnjelly** [comment]
Also it would be helpful to know some background info, especially whether t has worked "correctly" in the past with earlier versions. Have you changed computer / OS / GPU recently, or is the only change the Godot version?

If it has worked in the past it would be really helpful if you can pinpoint which version of Godot this started happening with (e.g. does it work in 3.5 beta 4, but not in 3.5 RC1). Does it work in 3.4.4?

This also needs a minimal reproduction project, if it doesn't occur with a blank project.

Running a debug build might be useful for more crash info, although @Calinou just has releases up to 3.4.4:
https://github.com/Calinou/godot-debug-builds/releases

**Comment by elvisish** [comment]
> Also it would be helpful to know some background info, especially whether t has worked "correctly" in the past with earlier versions. Have you changed computer / OS / GPU / graphics drivers recently, or is the only change the Godot version?
Nothing has changed whatsoever.
> If it has worked in the past it would be really helpful if you can pinpoint which version of Godot this started happening with (e.g. does it work in 3.5 beta 4, but not in 3.5 RC1). Does it work in 3.4.4?
3.4.4 stable works fine, 3.5 beta 5 works fine.
> This also needs a minimal reproduction project, if it doesn't occur with a blank project.
I'll try to get one, my current one has all my art and such in that I need to remove.
> Running a debug build might be useful for more crash info, although @Calinou just has releases up to 3.4.4: https://github.com/Calinou/godot-debug-builds/releases
I'll run a debug when there's a 3.5 RC1 build.

**Comment by elvisish** [comment]
> Can you test 3.5 RC 2? https://downloads.tuxfamily.org/godotengine/3.5/rc2/Godot_v3.5-rc2_win64.exe.zip

Tried RC1 again, and while it isn't slow now and the project manager isn't crashing for some reason (?? I ahven't changed anything since last night!) it still crashes the editor on closing, RC2 also does this.

**Comment by elvisish** [comment]
> Can confirm crashes in `3.5.rc1`:
> 
> * After closing the Project Manager:
> 
> ```
> Leaked instance: Image:7200 - Resource path:
> Hint: Leaked instances typically happen when nodes are removed from the scene tree (with `remove_child()`) but not freed (with `free()` or `queue_free()`).
> Orphan StringName: Image
> StringName: 1 unclaimed string names at exit.
> Segmentation fault
> ```
> 
> * After closing an empty project:
> 
> ```
> Leaked instance: Image:19025 - Resource path:
> Hint: Leaked instances typically happen when nodes are removed from the scene tree (with `remove_child()`) but not freed (with `free()` or `queue_free()`).
> Orphan StringName: Image
> StringName: 1 unclaimed string names at exit.
> Segmentation fault
> ```
> 
> If it helps, that's the leaked image: ![jCLSubFTaX](https://user-images.githubusercontent.com/9283098/170050471-5a4667ca-3dc9-4afe-b9a2-bb7b8991313c.png)
> 
> No crashes in `3.5.rc2`.

Can this be hotfixed? I'd like to use 3.5 but I'm worried about it with this crash, I'm not sure if it will break projects or not.

**Comment by kleonc** [comment]
> No issues for me with 3.5 RC2.

Glad to hear that! But I see you've edited it from:

>I have the crashes in 3.5 RC2. Can this be hotfixed? I'd like to use 3.5 but I'm worried about it with this crash, I'm not sure if it will break projects or not.

So what's changed / why you stated initially it crashed in 3.5 RC2? Did it crash in 3.5 RC2 for you at all or have you been testing different version or something like that?

Also what about your previous comment:

>Tried RC1 again, and while it isn't slow now and the project manager isn't crashing for some reason (?? I haven't changed anything since last night!) it still crashes the editor on closing, RC2 also does this.

Did it indeed crash in RC2 or maybe it was a false report?

**Comment by elvisish** [comment]
> > No issues for me with 3.5 RC2.
> 
> Glad to hear that! But I see you've edited it from:
> 
> > I have the crashes in 3.5 RC2. Can this be hotfixed? I'd like to use 3.5 but I'm worried about it with this crash, I'm not sure if it will break projects or not.
> 
> So what's changed / why you stated initially it crashed in 3.5 RC2? Did it crash in 3.5 RC2 for you at all or have you been testing different version or something like that?
> 
> Also what about your previous comment:
> 
> > Tried RC1 again, and while it isn't slow now and the project manager isn't crashing for some reason (?? I haven't changed anything since last night!) it still crashes the editor on closing, RC2 also does this.
> 
> Did it indeed crash in RC2 or maybe it was a false report?

Sorry, it was a stupid mistake, I didn't change my shortcut to the new exe! :o

**Comment by akien-mga** [comment]
Closing as fixed then.
