### ISSUE TITLE
Panel colors are not displayed correctly

### ISSUE THREAD

**Issue by ArcFutahito** [godotengine/godot#6133]
Godot 2.2 alpha x86 linux
Bug: When color is set, it's value is reduced somewhere in the engine (http://imgur.com/a/Vw4bm). When setting color to #FF0000 resulting color is #800000 if you set it to #800000 it's going to be #400000 and so on. 
Steps to reproduce: Create a panel with a custom theme, add Stylebox Flat and set color to #FF0000

**Comment by akien-mga** [comment]
Is this still valid in the current master branch?

**Comment by ArcFutahito** [comment]
I'm all over the place right now. I'll build godot again and test it today/tomorrow

**Comment by ArcFutahito** [comment]
Ok so I got 

modules/gdnative/godot/godot_input_event.cpp: In function 'float* godot_input_event_screen_drag_get_speed_y(godot_input_event*)':
modules/gdnative/godot/godot_input_event.cpp:304:14: error: 'class InputEvent' has no member named 'screen_drag'
  return &ie->screen_drag.speed_y;
              ^~~~~~~~~~~
scons: *** [modules/gdnative/godot/godot_input_event.x11.tools.64.o] Error 1
scons: building terminated because of errors.

when trying to build. Bad time for updates, huh? :D

**Comment by nunodonato** [comment]
tested in master, couldn't reproduce

**Comment by ArcFutahito** [comment]
Got fixed somewhere along the line.
