### ISSUE TITLE
3.5rc1 Navigation2D: Cutouts in NavigationPolygonInstance not recognized by pathfinding if done in code

### ISSUE THREAD

**Issue by goddommitdom** [godotengine/godot#61334]
### Godot version

3.5.rc1.official [e86d840d4]

### System information

Windows 10, GLES3

### Issue description

I keep reading that the proper way to interface with NavigationAgent2D is to cut out the StaticBody2D collision polygons from the NavigationPolygonInstance navigation polygon; however, attempting to do so results in polygons being visually removed, but not being treated as removed by any pathfinding.

The triangle was cut into the NavigationPolygonInstance in-editor; the trapezoids were done via code. As you can see, only the triangle actually registers as a "no-walk zone" despite the cut-out areas visually being cut out, and the NavigationPolygonInstance being disabled and re-enabled to refresh.

The polygons that are cut-out in code are ignored both with NavigationAgent2D and with the older get_simple_path() method.

![NavigationIssue](https://user-images.githubusercontent.com/45529332/169899246-0444682a-c132-4a45-a618-bcd3c7b5c5a3.gif)

### Steps to reproduce

Edit a NavigationPolygonInstance's navigation_polygon via code. Included is a MRP. I've included a bool in Player.gd to switch between using NavigationAgent2D and the older get_simple_path(); neither method recognizes the cutout areas done in code.

### Minimal reproduction project

[NavigationPolygon.zip](https://github.com/godotengine/godot/files/8757807/NavigationPolygon.zip)

**Comment by akien-mga** [comment]
CC @smix8 @Scony

**Comment by smix8** [comment]
Seems some of the more recent navigation fixes did not make it to the 3.5.RC1 in time.
In most recent Godot 3.x build the navpoly updates the navigationmesh correctly and the MRP works without these issues.

Your custom navmesh cutout code works fine. I also tested with all collision objects disabled and the agent stays on the new cutout navmesh all the time.

Note that for your current MRP movement code to work in the most recent Godot 3.x build you need to enabled the "avoidance enabled" bool on the NavigationAgent2D that was recently added.

**Comment by goddommitdom** [comment]
Thanks for the link, appreciated!

**Comment by Calinou** [comment]
Closing, as this will be resolved in 3.5rc2 which should be released in a few days' time.
