### ISSUE TITLE
Dragging Control nodes is super slow

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#61343]
### Godot version

a76db34

### System information

Windows 10 x64

### Issue description

This is more prominent in debug builds, but when you drag a Control node, the movement is extremely lagging:
![](https://chat.godotengine.org/file-upload/xiGGand4pLHPsKKpr/godot.windows.tools.64_EP7jes1pi1.gif)
I debugged a bit and seems like the inspector is refreshed twice with each movement.

### Steps to reproduce

1. Create a new User Interface scene
2. Add any Control child
3. Drag it around

**Comment by Calinou** [comment]
I can confirm this on 4.0.alpha 992317957 (Linux, NVIDIA 510.68.02).

**Comment by ArneStenkrona** [comment]
Dragging a control node makes a call to `Control::_edit_set_state()` (in control.cpp) which in turn calls `Control::_set_layout_mode() `which seems to be the culprit. I commented out this call to `_set_layout_mode()` which eliminated the performance issues entirely for me.

For an actual solution I have this in mind. Within `Control::_set_layout_mode()` there is currently a check for whether or not the mode is actually being changed. It looks like this:

```
...
if ((int)get_meta("_edit_layout_mode", p_mode) != (int)p_mode) {
	list_changed = true;
}
...
```
If this if-statement fails the method still proceeds, although without the `list_changed` flag set to true. Assuming that this method's only purpose is to set the mode, it is safe to return from the function if the current layout mode is the same as the new mode. Adding an else-block with a simple `return` solves the performance issues for me.

I'm very new to the godot code base so I might be missing something. But if this sounds like a reasonable approach I can issue a pull request with this change to `Control::_set_layout_mode()`

**Comment by KoBeWi** [comment]
I investigated this a bit and seems like it's a regression from #59185

**Comment by ArneStenkrona** [comment]
I notice the method is adding the `"_edit_layout_mode"` meta regardless of whether or not the mode is `LAYOUT_MODE_POSITION `or `LAYOUT_MODE_ANCHORS`, then proceeds to remove this meta if the mode is `LAYOUT_MODE_POSITION` (which I guess is the default value, thus redundant):

```
...
set_meta("_edit_layout_mode", (int)p_mode);

if (p_mode == LayoutMode::LAYOUT_MODE_POSITION) {
    remove_meta("_edit_layout_mode");
...
```

Only adding the `"_edit_layout_mode"` meta if the mode is `LAYOUT_MODE_ANCHORS` also fixes the performance issue. To me this seems like the most straightforward solution. I'll create a pull request with this fix.
