### ISSUE TITLE
Compile error if target=release

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#6134]
**Operating system or device - Godot version:**
compile on Windows 10 with MSVC 14. Godot current head (b9e8bddf19a277b6a5302ec1e12ace780ed86b12)

**Issue description** (what happened, and what was expected):
```
core\variant_call.cpp(1196): error C2039: 'arg_names': '_VariantCall::FuncData' is not member.
core\variant_call.cpp(1209): error C2039: 'return_type': '_VariantCall::FuncData' is not member.
core\variant_call.cpp(1211): error C2039: 'return_type': '_VariantCall::FuncData' is not member.
```

**Steps to reproduce:**
scons platform=windows tools=no **target=release**
scons platform=android tools=no **target=release**

**Comment by eska014** [comment]
Thought at first this is related to #6055, but `git blame` points to Visual Script. phew...

**Comment by volzhs** [comment]
oh, and I disabled visual script module.
