### ISSUE TITLE
NavigationMesh generation does not use the mesh offsets in MeshLibrary 

### ISSUE THREAD

**Issue by getpos** [godotengine/godot#61344]
### Godot version

3.5rc1

### System information

Pop!_OS 22.04

### Issue description

When baking navmeshes for gridmaps it doesn't use the individual mesh transform set in the MeshLibrary, which makes the navmeshes become offset from the gridmap.

Example:

![2022-05-24-093841_1920x1080_scrot](https://user-images.githubusercontent.com/39038795/169921213-58934e4c-067b-482b-8c57-abd98b477e38.png)

### Steps to reproduce

In the minimal reproduction project, simply generate a navmesh in the Gridmap scene.

### Minimal reproduction project

[NavigationMeshLibraryBug.zip](https://github.com/godotengine/godot/files/8758627/NavigationMeshLibraryBug.zip)

**Comment by akien-mga** [comment]
CC @smix8. FYI, support for individual mesh transforms in MeshLibrary was added recently in https://github.com/godotengine/godot/pull/52298, it can likely be added to NavigationMesh too.
