### ISSUE TITLE
Directory walking doesn't work in HTML5 release build, but does in debug

### ISSUE THREAD

**Issue by quantumedbox** [godotengine/godot#61356]
### Godot version

3.4.4.stable

### System information

Windows 10

### Issue description

When running this code piece on debug, everything works as expected:

```gdscript
static func files_in_dir(path: String) -> PoolStringArray:
  var result := PoolStringArray()
  var dir := Directory.new()
  if dir.open(path) != OK:
    push_error("Cannot open " + path)
    return result
  assert(dir.list_dir_begin(true) == OK)
  var file = dir.get_next()
  while not file.empty():
    result.push_back(path + file)
    file = dir.get_next()
  dir.list_dir_end()
  return result


func _ready() -> void:
  for file in files_in_dir("res://"):
    print(file)
```

Output:
```
res://.import [index.js:347:16](http://localhost:50502/index.js)
res://Node.gd.remap [index.js:347:16](http://localhost:50502/index.js)
res://Node.gdc [index.js:347:16](http://localhost:50502/index.js)
res://Node.tscn [index.js:347:16](http://localhost:50502/index.js)
res://default_env.tres [index.js:347:16](http://localhost:50502/index.js)
res://icon.png [index.js:347:16](http://localhost:50502/index.js)
res://icon.png.import [index.js:347:16](http://localhost:50502/index.js)
res://project.binary [index.js:347:16](http://localhost:50502/index.js)
```

But nothing is outputted in release

### Steps to reproduce

Export listed below reproduction project in HTML5 in release and run it

### Minimal reproduction project

[reproduction.zip](https://github.com/godotengine/godot/files/8761269/reproduction.zip)

**Comment by quantumedbox** [comment]
Right, it doesn't work in native executable release build either, I imagine it has something to do with how projects are exported?
Couldn't find any information about this behaviour

**Comment by Calinou** [comment]
Can you check if this occurs in [3.5rc1](https://godotengine.org/article/release-candidate-godot-3-5-rc-1)? Also check if this occurs when removing the type hint declarations.

**Comment by quantumedbox** [comment]
> 

Same symptoms without type hints both on 3.4.4.stable and 3.5rc1

**Comment by quantumedbox** [comment]
...Oh, that's just me being an idiot. I put list_dir_begin() in assert.

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot-proposals/issues/502.
