### ISSUE TITLE
PopupMenu switches monitors and does not respect position in @tool mode (DisplayServer regression)

### ISSUE THREAD

**Issue by krisscox** [godotengine/godot#61358]
### Godot version

4.0.alpha8.official [cc3ed63af]

### System information

Windows 10 21H1, AMD Ryzen 7 4800S, NVIDIA 2060 Max-Q (Laptop)

### Issue description

In @tool mode PopupMenu changes to a different monitor on subsequent popup() calls, and has incorrect position when on the monitor with the editor running, not respecting position.x value.

**I have found this only occurs when Godot is not running on the primary monitor**

To give a better idea of my setup, I have a small laptop with an external monitor connected. Godot runs on the secondary monitor as it's larger, 

### Steps to reproduce

WIth 2 monitors (in my case a laptop and secondary screen), put Godot on the secondary monitor, create a PopupMenu and call Popup(). Subsequent clicks change the monitor the popup is displayed on, with position not being respected. This only happens when Godot is not on the primary monitor.

### Minimal reproduction project

[Example.zip](https://github.com/godotengine/godot/files/8761727/Example.zip)

**Comment by Calinou** [comment]
Can you reproduce this after enabling **Single Window Mode** in the Editor Settings then restarting the editor?

**Comment by krisscox** [comment]
I can confirm that single window mode stops this issue from occuring

**Comment by KoBeWi** [comment]
Can't reproduce, popup always appears at the correct position. Also Windows 10.

**Comment by OkariBattleRD** [comment]
Google lead me to this, but I figured out a good workaround by using `popup_on_parent`

`func _on_background_gui_input(event):
	if event is InputEventMouseButton:
		var button : InputEventMouseButton = event
		if button.is_pressed() && button.button_index == MOUSE_BUTTON_RIGHT:
			var rect = Rect2(button.global_position, Vector2.ZERO)
			right_click_menu.popup_on_parent(rect)`
