### ISSUE TITLE
godot4 singleton (autoload) can't use self to connect method to signal

### ISSUE THREAD

**Issue by aanishacharyaa** [godotengine/godot#61353]
### Godot version

Godot_v4.0-alpha8_linux.64

### System information

linux mint

### Issue description

it won't accept this line
loading_timer.connect("timeout",self,"loading")

with error 
Parser Error: Invalid argument for "connect()" function: argument 2 should be Callable but is res://global/helper_functions.gd

where helper_functions.gd is singleton

### Steps to reproduce

```gdscript
var is_loading = false 
var loading_timer = Timer.new()

func ready():
	loading_timer.autostart = false
	loading_timer.waititme = 1
	loading_timer.oneshot = false
	loading_timer.connect("timeout",self,"loading")
	add_child(loading_timer)
```

**Comment by Calinou** [comment]
The signal connection syntax has changed in 4.0. It should now be `loading_timer.timeout.connect(self.loading)`.

PS: Code blocks should use triple backticks like this (with an optional language name for syntax highlighting):

\`\`\`gdscript
code here
\`\`\`

I edited your post accordingly, but remember to do this in the future :slightly_smiling_face:

**Comment by groud** [comment]
As Calinou said, this is expected. You should either use `loading_timer.timeout.connect(self.loading)` or even `loading_timer.connect("timeout", self.loading)`.
