### ISSUE TITLE
Tween set_loops() without arguments is always detected as infinite

### ISSUE THREAD

**Issue by SilencedPerson** [godotengine/godot#61369]
### Godot version

3.5 beta5

### System information

Windows 10

### Issue description

Cannot make an infinite loop even when the tween has interval.
![image](https://user-images.githubusercontent.com/82024211/170052726-2db3d47f-3e91-4dae-87f5-5e58ebbb7481.png)
![image](https://user-images.githubusercontent.com/82024211/170052998-69e82ce2-7545-44df-b828-ebcb43e574e7.png)

### Steps to reproduce

Put this into the script.

```GDScript
func _ready():
	var t = create_tween()
	t.set_loops()
	t.tween_interval(0.5)
	t.tween_callback(self,"print_test")
	
func print_test():
	print(1)
```

**Comment by KoBeWi** [comment]
This is fixed in newest rc, update Godot.
