### ISSUE TITLE
Viewport HDR and post-processing not working as before

### ISSUE THREAD

**Issue by antourenein** [godotengine/godot#61367]
### Godot version

3.5 rc1-rc2

### System information

Windows 10, GLES3, NVIDIA GTX 850M

### Issue description

Using a Viewport containing a 3D mesh with an emissive spatial material and bringing it to a 2D scene with post processing by using a Sprite with ViewportTexture or ViewportContainer is showing different results, compared to beta 5.

Beta 5: 
![image](https://user-images.githubusercontent.com/79013106/170039413-3843da02-b6d5-4e1c-bed3-a3940d917ae7.png)

RC1 and RC2:
![image](https://user-images.githubusercontent.com/79013106/170039507-6bd0b521-58e6-41f7-ac54-1ea592c55602.png)

### Steps to reproduce

Create a scene with the following sctructure:

![image](https://user-images.githubusercontent.com/79013106/170040904-14ac149e-060c-4eb7-bdf0-eb390ee01a19.png)

Settings:
World Environment Background: Canvas
Tonemapping: Linear, Exposure: 0.25
Glow: ON, Intensity 2.8, Strength 0.6, Blend Mode Additive, Bicubic Upscale ON

Viewport: Transparent BG ON
MeshInstance: Any default mesh, Spatial Material with Albedo set to black (000000), Emission ON with white (ffffff) color and Energy 10

(Note: using HDR colors in albedo instead of emission gives the same results, so I assume it is a problem with HDR in general)

Open the scene in beta 5 and then RC1 or RC2 to see the difference.

### Minimal reproduction project

The scene above:

[GlowTest.zip](https://github.com/godotengine/godot/files/8762925/GlowTest.zip)

**Comment by Calinou** [comment]
This is likely a regression from https://github.com/godotengine/godot/pull/54585.

**Comment by clayjohn** [comment]
This doesn't appear to be a bug. What is happening here is that both the 3D scene and the 2D scene are using the same Environment (in the MRP the WorldEnvironment is a child of the root Control node and the Viewport does not have "Own World" enabled). Therefore the tonemapper (particularly the exposure setting) is getting applied twice. 

In 3.4, in this test scene tonemapping is only applied after the 2D pass becuase tonemapping is skipped when "Transparent BG" is enabled. But now becuase we can tonemap transparent viewports, the tonemapping is applied twice. 

The solution is to check off "Own World" on the Viewport and the scene will then look like it did in 3.4.
