### ISSUE TITLE
Relationship lines draw for invisible TreeItems

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#61372]
### Godot version

df9dae2

### System information

Windows 10 x64

### Issue description

![image](https://user-images.githubusercontent.com/2223172/170075926-8e6501dc-43d7-4f34-a7f7-db83706836f7.png)
#60061 didn't handle relationship lines properly.
CC @monkeyman192 

### Steps to reproduce

1.
```GDScript
func _ready() -> void:
	var tree = $Tree as Tree
	tree.create_item().set_text(0, "Root")
	tree.create_item(tree.get_root()).set_text(0, "Child 1")
	tree.create_item(tree.get_root()).set_text(0, "Child 2")
	tree.get_root().get_first_child().get_next().set_visible(false)
```
2. Enable `theme_override_constants/draw_relationship_lines` in $Tree
3. Run

**Comment by monkeyman192** [comment]
Ah whoops! 😅 I didn't even realise this was an option when testing...
I'll open a PR with a fix 😄
