### ISSUE TITLE
[3.5 RC2] NavigationAgent2D regression; velocity computed signal doesn't fire

### ISSUE THREAD

**Issue by Depriety** [godotengine/godot#61378]
### Godot version

3.5.rc2

### System information

Windows 10, 64 bit

### Issue description

I started writing a simple 2d top-down navigation system in 3.5 RC1, tested it just now in RC2 and the actors that were using the system no longer moved. Quickly figured out that this was due to the ```velocity_computed(safe_velocity)``` signal no longer being received from their NavigationAgent2D, and thus not calling ```move_and_slide```. I've managed to recreate the issue and attached a minimal reproduction project.

### Steps to reproduce

When opening the attached project in 3.5 RC1, when you launch the scene, the actor on the right side of the screen should draw a path around the obstacle in the middle and navigate around it, moving to the left side of the screen and stopping once it has reached the targeted Position2D node. You should also be able to note "computed" being printed to the output on every physics frame.

Opening the same project in 3.5 RC2, when launching the scene, the actor should still draw the path but not move. There should also not be anything printed to the output.

The only script in the project is attached to the KinematicBody2D.

### Minimal reproduction project

[bugComputeVelocity_minimal_reproduction_project.zip](https://github.com/godotengine/godot/files/8765166/bugComputeVelocity_minimal_reproduction_project.zip)

**Comment by smix8** [comment]
Not a bug. Avoidance was changed between rc1 and rc2.

The NavigationAgent2D now has an "avoidance_enabled" bool toggle that is disabled by default.
Avoidance was eating a lot of performance behind the scene for no reason if someone would not use avoidance.

You need to enable avoidance by choice in 3.5.rc2 if you want to receive the safe_velocity signal.

**Comment by Depriety** [comment]
Oh wow, I can't believe I missed that! Apologies for the false alarm.
