### ISSUE TITLE
cannot use PackedSceneGLTF after export project to .exe file

### ISSUE THREAD

**Issue by ciompzhangdi** [godotengine/godot#61393]
### Godot version

godot 3.4.2

### System information

Windows 10

### Issue description

In XR/3D projects we need to save some cute 3D models that we create or see in the scene, and then  we can transfer 3D model to other users or servers. most important, we can modify it in other software like Blender. 

PackedSceneGLTF provide a very important methid to export 3D model files, which support quite a few useful features.
The only problem is I cannot use PackedSceneGLTF after export project to .exe file. (in the release executable file)

### Steps to reproduce

func save_scene(path, node_path):
	var scene = get_node(node_path)
	var to_save = PackedSceneGLTF.new ()#here is the error, PackedSceneGLTF is not declared  (in the release executable file)
	to_save.export_gltf(scene, path, 0)

**Comment by timothyqiu** [comment]
This class is editor only: https://docs.godotengine.org/en/3.5/classes/class_packedscenegltf.html

**Comment by Calinou** [comment]
Closing per @timothyqiu's comment. Run-time glTF loading and saving will only be available in Godot 4.0.
