### ISSUE TITLE
get_class() inheritance oddness

### ISSUE THREAD

**Issue by NationalityNZ** [godotengine/godot#61396]
### Godot version

4.0 alpha 8 win 64 bit

### System information

Windows 10

### Issue description

Perhaps not a bug, but behavior unexpected enough that it might qualify as a bug. Overwriting get_class() seems to be the standard way of testing inheritance of custom classes, but this method seems to be broken in the newest build.

```
extends Node

class_name MyCoolClass


func _ready():
	print(get_class())
	
	
func get_class()->String:
	return "MyCoolClass"
```

This will return "Node" instead of "MyCoolClass". However...

```
extends Node

class_name MyCoolClass


func _ready():
	print(self.get_class())
	
	
func get_class()->String:
	return "MyCoolClass"
```

...this will correctly return "MyCoolClass".

My intuition says that both pieces of code should probably return "MyCoolClass", but I know Godot has some wrinkles when it comes to custom classes so who knows.

### Steps to reproduce

Just make a new project and make a node with the scripts attached.

**Comment by Calinou** [comment]
> but this method seems to be broken in the newest build.

Did you try this in older versions (including 3.4.4)?

**Comment by NationalityNZ** [comment]
No, I didn't, I went straight for Godot 4 because it had some features that I needed. And actually, though it's superficially like that issue you mentioned, the real issue is that get_class() is calling on the base class functions rather than the inherited functions. I don't really think "get_class()" and "self.get_class()" should produce different results.

**Comment by Syndicist** [comment]
For the record, when doing the same in 3.x, both statements:

```
print(get_class())
print(self.get_class())
```

return the same value, and will return whatever you overwrite get_class() to return and respects inheritance when doing so. Meaning...
```
extends Node
class_name MyCoolClass

func get_class()->String:
	return "MyCoolClass"
```
```
extends MyCoolClass
class_name MyCoolChildClass


func _ready():
	print(self.get_class())
```
... Will print "MyCoolClass"

**Comment by dalexeev** [comment]
Overriding non-virtual native methods is not supported, in fact you only shadow them. See #72608.

**Comment by YuriSizov** [comment]
Indeed, this is not valid code, as Godot doesn't allow to override engine methods which are not exposed as virtual.
