### ISSUE TITLE
Godot4.0.dev with GLES3 backend.

### ISSUE THREAD

**Issue by smohantty** [godotengine/godot#61398]
### Godot version

4.0.dev

### System information

Ubuntu GLES3 with Wayland backend (wayland-egl)

### Issue description

I am trying to add a wayland backend to Godot4.0 with GLES3 as there is no support for Vulkan for the target device.

I am getting a Runtime error in Shader Comiplation.

ERROR: CanvasShaderGLES3: Vertex shader compilation failed:
0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.00 ES, 3.00 ES, 3.10 ES, and 3.20 ES

   at: _display_error_with_code (drivers/gles3/shader_gles3.cpp:216)
ERROR: Method/function failed.

I can't figure it out how its choosing this version GLSL 3.30 ? any pointer will be really helpfull.

Note: If I run with X11 and GLES3(by disabling Vulkan backend in build file) the application runs fine.

So I am just wondering what parameter/configuration am missing .

Thanks for all the help.

### Steps to reproduce

As this code is experimental currently can't be reproduced without building my local code.

https://github.com/smohantty/godot/tree/opensource

Buid:
    scons -j16 platform=linuxbsd vulkan=no opengl3=yes x11=no wayland=yes

**Comment by Calinou** [comment]
> I am trying to add a wayland backend to Godot4.0 with GLES3 as there is no support for Vulkan for the target device.

Out of curiosity, have you seen https://github.com/godotengine/godot/pull/57025?

If you're interested in helping on Wayland support, I'd recommend joining the [Godot Contributors Chat](https://chat.godotengine.org/) :slightly_smiling_face:

**Comment by Calinou** [comment]
@smohantty Out of curiosity, are you still working on this?

**Comment by Calinou** [comment]
Closing due to lack of response. See https://github.com/godotengine/godot/pull/57025 for further developments on native Wayland support. In the meantime, XWayland can be used to run Godot on Wayland-based desktop environments.

**Comment by poVoq** [comment]
This is still an issue. The rather popular Pinebook Pro Laptops with a Mali T860 and Mesa Panfrost drivers only support OpenGL 3.1 and OpenGL ES 3.1.

So Godot fails to start as there is no OpenGL 3.3 support, but it could in theory work on OpenGL ES 3.1.
