### ISSUE TITLE
Android build fails on Master

### ISSUE THREAD

**Issue by vkbsb** [godotengine/godot#6139]
**Operating system or device - Godot version:**
git / master

**Issue description** (what happened, and what was expected):
android compilation fails

**Steps to reproduce:**
pull latest code from repo and compile for android.

**Link to minimal example project** (optional but very welcome):

**Comment by vkbsb** [comment]
There are a couple of more errors even after this fix.

**Comment by volzhs** [comment]
could be duplicated #6134

**Comment by bojidar-bg** [comment]
@volzhs I think, dupe of both :smile:
