### ISSUE TITLE
cannot save changes of blendshape

### ISSUE THREAD

**Issue by ciompzhangdi** [godotengine/godot#61399]
### Godot version

godot 3.4.2

### System information

Windows 10

### Issue description

when i save current scene to gltf file，the value of  blendshape is still 0。
I can only open gltf again after saving, find the position of the "’weight={}" and write the value again.
The bug is easy to fix.
![image](https://user-images.githubusercontent.com/31799027/170202440-03f1110e-0c86-422d-befa-c7d6b0b9847b.png)
open it!
![image](https://user-images.githubusercontent.com/31799027/170202302-c2382c84-7720-4bde-b52a-cd0259d3d061.png)

### Steps to reproduce

After using get_blend_shape_list() we can find blendshape's position, we can write it again.

```gdscript
# rebuid is a dictionary ,like {blend_shape:{name1:0，name2:0，}}....
func get_blend_shape_list(gltf_data, rebuild):
	var weights = []
	var record_string = []
	for mesh in gltf_data["meshes"]:
		if rebuild["blend_shape"].keys()[0] in mesh["extras"]["targetNames"]:
			for i in range(len(mesh["extras"]["targetNames"])):
				for j in rebuild["blend_shape"].keys():
					if mesh["extras"]["targetNames"][i] == j:
						mesh["weights"][i] = rebuild["blend_shape"][j]
						record_string = mesh["extras"]["targetNames"]
						continue
			weights = mesh["weights"]
	return {"weights":weights, "record_string":record_string}
```

**Comment by Calinou** [comment]
> when i save current scene to gltf file，the value of blendshape is still 0。

Godot does not support saving glTF scenes. It can only load them.
