### ISSUE TITLE
Godot 3.5 rc2 export template error for Win Desktop builds

### ISSUE THREAD

**Issue by Winterslice** [godotengine/godot#61392]
### Godot version

3.5 rc2

### System information

Windows 10

### Issue description

On Godot 3.5 rc2, when trying to build for Windows Desktop, it throws the following error:

![GodotExportBug](https://user-images.githubusercontent.com/32410139/170156746-90cadb2b-5a11-47db-bca1-a988d9ec1c46.png)

I've tried redownloading the export templates multiple times, but the problem persists on multiple projects.

Happens with 3.5 rc1 as well.

### Steps to reproduce

Build any project using Godot 3.5 rc2 export templates.

**Comment by Winterslice** [comment]
This still happens in rc3, I'm completely unable to make Windows builds.

**Comment by akien-mga** [comment]
CC @bruvzg

**Comment by bruvzg** [comment]
Can't reproduce, Windows exports are working fine.
Please check if it's the same with the new empty project, and if not, provide MRP. Also try downloading `.tpz` using browser and installing from file, sometimes downloads from the `tuxfamily.org` seems to fail in the middle of file.

**Comment by bruvzg** [comment]
Also, check the editor output log, are there any extra errors?

**Comment by Winterslice** [comment]
Found the problem -- the unconfigured rcedit tool is preventing export, which is being misreported as missing/corrupted export templates.

This should probably be clarified.

Also I don't think it's mentioned anywhere that rcedit is required for a successful build? Only the yellow warning label about changing the icon and app information data.

**Comment by bruvzg** [comment]
You can uncheck "modify resources" in the export settings, and it will work without it.

I'm not sure if it should fail or just show a warning (it won't be able to change the icon as expected, so export is not fully successful). But error messages definitely need improvement.

**Comment by mojoyup** [comment]
Yeah, I just got updated to 3.5 on Steam and I get this now coming from 3.4.4. I'm not sure how to get rid of it but I need to export for Steam application, therefore I NEED the application data and icons.

**Comment by akien-mga** [comment]
@mojoyup What error are you getting? This was fixed, and it should now provide ample information about what you should do if an export doesn't work.

**Comment by mojoyup** [comment]
![Capture](https://user-images.githubusercontent.com/29804613/183303307-3dec2cab-8cc4-43ba-a8e2-8ca722a2ed3e.PNG)

**Comment by akien-mga** [comment]
You need to configure rcedit in the Editor Settings with the path given by that warning. See https://docs.godotengine.org/en/stable/tutorials/export/changing_application_icon_for_windows.html#changing-the-file-icon

**Comment by mojoyup** [comment]
ok, thank you for the help. Ill try it now
