### ISSUE TITLE
Godot 3.4.3+ is missing Mono "Wait For Debugger" options

### ISSUE THREAD

**Issue by 31** [godotengine/godot#61401]
### Godot version

3.4.3-stable_mono_win64 onwards

### System information

Windows 10

### Issue description

In 3.4.2 Godot Mono, you can enable Wait For Debugger in the project settings:

![image](https://user-images.githubusercontent.com/331300/170218658-177c6df5-d6c4-4b59-81e0-35bb0b70054a.png)

In 3.4.3 and 3.4.4, this category no longer exists:

![image](https://user-images.githubusercontent.com/331300/170218855-60ee0c09-fec6-4b51-9870-68e92007f119.png)

The only change in a related area I see in [the 3.4.3 release notes](https://godotengine.org/article/maintenance-release-godot-3-4-3) is https://github.com/godotengine/godot/pull/56835. Could it be that moving the `GLOBAL_DEF`s into a different scope means they aren't called when needed and don't set up the project settings options anymore?

### Steps to reproduce

Open a project in 3.4.3 or 3.4.4 Godot Mono, open the project settings, and scroll down.

**Comment by akien-mga** [comment]
Indeed, you identified the problematic change correctly. The scope is not the issue per se, but the early return when running the editor is. That means these settings are never defined in the editor.

**Comment by akien-mga** [comment]
Feel free to make a PR to move them back (and maybe add a comment like `// Make sure to define those in editor too for Editor Settings.`). This should likely be PR'ed against the `master` branch and we'll cherry-pick for 3.5 and 3.4.5.

**Comment by 31** [comment]
Thanks, submitted PR https://github.com/godotengine/godot/pull/61430 with the change. (Took me a while to resurrect my C++ build environment. 😄)

**Comment by akien-mga** [comment]
Fixed by #61430.
