### ISSUE TITLE
Vulkan: Enabling MSAA with SSAO causes artifacts to appear on AMD Polaris GPUs

### ISSUE THREAD

**Issue by ZeroTheOtaku** [godotengine/godot#61415]
### Godot version

4.0 Alpha 7

### System information

Windows 10, Radeon RX560, GLES3/Vulkan

### Issue description

MSAA Causing blocks to appear on screen when moving camera and in gameplay
Tried enabling SSAA and still have same problem.

![image](https://user-images.githubusercontent.com/96438890/170334171-546bf95b-49cc-4e6d-b426-683a03f5fc42.png)

The problem occurs when SSAO is enabled in the world environment and MSAA is enabled

![image](https://user-images.githubusercontent.com/96438890/170339221-a1a34697-ac66-4d57-bfaf-c22bcc26ce2a.png)

### Steps to reproduce

Set MSAA to 4x 
Use a World Environment node
Enable SSAO
Move camera/view around till problem occurs (mainly happens when pointing on a top angle view onto objects)

### Minimal reproduction project

[MSAA Problem.zip](https://github.com/godotengine/godot/files/8773655/MSAA.Problem.zip)

**Comment by Calinou** [comment]
> 4.0

Please specify the *exact* version you're using (i.e. which alpha or commit hash), as 4.0 stable isn't released yet.

**Comment by ZeroTheOtaku** [comment]
Alpha 7

**Comment by SmartySmart702** [comment]
I tried it with Godot alpha 7 and 8 and I could not reproduce the bug.
Win 10, GTX 1070.

**Comment by Matzerath** [comment]
I can recreate this problem exactly, I am currently using Godot 4.0 beta 10, graphics card is a RadeonRX 580. With MSAA on at 4X, turning on SSAO causes artifacts when moving around, artifacts are gone when SSAO turned off. Problem shows up in an external Godot game I downloaded from Itch.io as well, 'Limspace'. Limspace does not have an option to turn SSAO on/off, I'm assuming that it is on.

**Comment by Calinou** [comment]
I can't reproduce this on 4.0.beta f692b4768 (Linux, Radeon RX 6900 XT, Mesa RADV). This could be an issue specific to Polaris GPUs (and maybe also scoped to Windows).

![image](https://user-images.githubusercontent.com/180032/209449421-76edd884-e532-4175-a695-d295cf4a7b5e.png)

Updated MRP to work with recent 4.0 betas: [MSAA Problem2.zip](https://github.com/godotengine/godot/files/10299087/MSAA.Problem2.zip)

**Comment by TacoGuyAT** [comment]
Having the same issue here on Windows 10 with Polaris GPU. Tested on Godot 4.0, 4.0.2 and 4.0.3-rc2 (with C# support for each of these).
![image](https://github.com/godotengine/godot/assets/35270005/d9fa5ebc-adb0-4646-8694-0d22acbd5499)
![image](https://github.com/godotengine/godot/assets/35270005/e61341d9-ec5a-4e6b-8f82-ce0001407fce)


#### MSAA 4x/8x and SSAO:
![image](https://github.com/godotengine/godot/assets/35270005/2fa0214b-97d8-4d9e-b2a5-c3fffed252f8)

## !!! Photosensitive warning !!!

https://github.com/godotengine/godot/assets/35270005/19337d28-de7e-4cc3-b21d-a7023ab0fdb8

#### MSAA 4x/8x and SSIL:
![image](https://github.com/godotengine/godot/assets/35270005/d0cd92fd-0863-4bd7-9e1d-179bb26be18e)

#### MSAA 4x/8x and SDFGI:
![image](https://github.com/godotengine/godot/assets/35270005/079ab84f-d144-46b3-9cb2-43da5e3b91b2)

#### MSAA 2x with SDFGI, SSAO and SSIL (simultaneously) looks somewhat normal:
![image](https://github.com/godotengine/godot/assets/35270005/784a3eb7-6fea-48a0-8415-2fa4ba09434a)

#### Though, comparing to no AA, it causes some fuzzy borders:
![image](https://github.com/godotengine/godot/assets/35270005/b096b128-33e3-4284-aa32-967a3a32a1c5)

Related issues: #76258 , #64144

(None of these problems are present when MSAA is disabled. Same glitches occur in the editor too.)

**Comment by TacoGuyAT** [comment]
> I can't reproduce this on 4.0.beta [f692b47](https://github.com/godotengine/godot/commit/f692b476869c14023b342c12efc21cb5cd6002b7) (Linux, AMD Radeon RX 6900 XT, Mesa RADV). This could be an issue specific to Polaris GPUs (and maybe also scoped to Windows).
> 
> ![image](https://user-images.githubusercontent.com/180032/209449421-76edd884-e532-4175-a695-d295cf4a7b5e.png)
> 
> Updated MRP to work with recent 4.0 betas: [MSAA Problem2.zip](https://github.com/godotengine/godot/files/10299087/MSAA.Problem2.zip)

Able to reproduce the issue on this exact project, though, after importing and opening only FXAA was enabled. MSAA was turned off in it for some reason.

![image](https://github.com/godotengine/godot/assets/35270005/d53fea8d-edc4-4ec6-bfba-e98b49124f0a)
(Godot 4.0.3-rc2, hash is 2ac4e3bb3)

**Comment by TacoGuyAT** [comment]
Fuzzy borders appear on GTX 1660 Ti GPU, but not SDFGI, SSIL and SSAO problems

#### MSAA 4x and SSAO:
![image](https://github.com/godotengine/godot/assets/35270005/c7d28ce9-ac9f-4236-b325-a57d2a890b6f)
![image](https://github.com/godotengine/godot/assets/35270005/22a92675-cce7-4ec9-a538-7b9b54adfa96)
![image](https://github.com/godotengine/godot/assets/35270005/2c081d20-634d-49c1-bfb8-56adfaded9de)

![image](https://github.com/godotengine/godot/assets/35270005/fb7290ea-c25d-454b-aedf-f1b789921128)
![image](https://github.com/godotengine/godot/assets/35270005/f602969c-18cc-4f7d-97df-152150b2c0b1)

(Engines are 4.0.3-rc2 2ac4e3bb3 and 4.0.3 5222a99f5)

**Comment by darksylinc** [comment]
This is a driver bug specific to AMD Polaris on Windows + MSAA.

The problem is that the Depth during the Depth Prepass does not match exactly the Depth during the forward pass; despite Godot asking for invariant gl_Position and using the exact code with the same data.

A workaround is to disable MSAA.

I will try to contact AMD to see if they can fix it.

**Comment by Calinou** [comment]
@ZeroTheOtaku Can you test [4.3.dev2](https://godotengine.org/article/dev-snapshot-godot-4-3-dev-2/) to see if the issue is resolved there?

**Comment by Matzerath** [comment]
I have tested, and have so far not noticed any artifacts or other visual glitches after several builds, or in the main engine window for the project. I've tried this with all effects that previously caused this problem, plus MSAA x4. There may be more subtle side-effects, I was mostly looking for the very obvious artifacting that covered the entire screen, which seems to be fixed.

**Comment by Calinou** [comment]
Thanks for checking :slightly_smiling_face: Closing then.

**Comment by TacoGuyAT** [comment]
Regression, the issue is back in 4.4 dev4, though artifacts look different.

#### dev3, intended look:
![Image](https://github.com/user-attachments/assets/c8499f29-8fbc-443a-ae5c-327fa4f55658)
![Image](https://github.com/user-attachments/assets/a07343bc-6b0f-4582-872d-9fd9b834d5ed)

#### dev4:
![Image](https://github.com/user-attachments/assets/988ba0d3-865b-4b31-8450-5cd894443405)
![Image](https://github.com/user-attachments/assets/71a20264-bfe0-4d52-931e-b596d72b1066)

> In addition, the issue now might occur in the editor, but not in the game:
![Image](https://github.com/user-attachments/assets/cf1c5ae8-622f-4c4d-a3b2-32f2aad4b116)

**Comment by TacoGuyAT** [comment]
> [@TacoGuyAT](https://github.com/TacoGuyAT) what GPU and OS? Thanks

Hi, sorry for not mentioning, it's the same RX 580 + Windows 10 21H2 config as was tested previously in this issue. Tried both latest (25.5.1) and previous version of drivers (24.9.1), but the issue persists.

![Image](https://github.com/user-attachments/assets/8634e4e2-d7e3-4629-bcc7-efab7a386e20)

**Comment by clayjohn** [comment]
@TacoGuyAT we saw a lot of heavy development in the 4.4 release cycle. So looking at dev 4 isn't really representative of the current state. Have you also tested 4.4.1 stable and confirmed that the issue exists there?

**Comment by TacoGuyAT** [comment]
> > [@TacoGuyAT](https://github.com/TacoGuyAT) we saw a lot of heavy development in the 4.4 release cycle. So looking at dev 4 isn't really representative of the current state. Have you also tested 4.4.1 stable and confirmed that the issue exists there?
> 
> Yes, I encountered issue on 4.4.1 and tracked it back to dev4.

Just in case, the issue appears on 4.5 dev3 too:

![Image](https://github.com/user-attachments/assets/b70b36c4-6eac-4607-8610-c75acde9bc51)
![Image](https://github.com/user-attachments/assets/43eb704c-e6d4-4f35-b0e2-eea54b56eb9b)

**Comment by TacoGuyAT** [comment]
> [@clayjohn](https://github.com/clayjohn) back then in 2023 when I looked into this, I was very convinced it was a driver bug. More specifically, a race condition pertaining either the resolve step or the depth buffer. This was clear because I could repro on RenderDoc and see how the artifacts _changed_ every time RenderDoc redraw the scene.
> 
> But because we had a ton of validation errors regarding MSAA, I could simply not submit it to AMD. But we fixed those with the Render Graph. I'd want to send this bug repro to AMD before they drop Polaris from their supported GPUs.
> 
> [@TacoGuyAT](https://github.com/TacoGuyAT) does this happen with the "Minimal reproduction project"? (So I can send it to AMD). If not, can you upload a MRP we can take a look at? Thanks.

Yes, the screenshots with triangular mesh are the MRP project, but original MRP has MSAA disabled for some reason, which is the option that breaks stuff.

Here's the fixed one I check this issue on, it doesn't require additional manual setup:
[MSAA Problem.zip](https://github.com/user-attachments/files/20166156/MSAA.Problem.zip)

**Comment by TacoGuyAT** [comment]
I tracked regression back to https://github.com/godotengine/godot/pull/98701 , specifically reverting changes in this file: https://github.com/DarioSamo/godot/blob/5216ef5f9cb9479989b58aaab797a87a61899630/servers/rendering/rendering_device_graph.cpp
I can't fix it properly myself (at least at the moment), but I hope it can be helpful. By the way, can this issue be reopened back again? It would be nice to have it open, so people could actually find it as an occurring issue.

**Comment by TacoGuyAT** [comment]
I was able to fix this issue by reverting [this line](https://github.com/godotengine/godot/blob/f62fdbde15035c5576dad93e586201f4d41ef0cb/servers/rendering/rendering_device_graph.cpp#L588) back to write_usage = true. (#112937)

## 4.5.1 stable:
<img width="2560" height="1570" alt="Image" src="https://github.com/user-attachments/assets/cc601502-6c22-42fe-82f2-64ac2341bd44" />

## master:
<img width="2560" height="1569" alt="Image" src="https://github.com/user-attachments/assets/496e9772-b430-40a2-be73-05913ccac2d2" />

**Comment by akien-mga** [comment]
> By the way, can this issue be reopened back again? It would be nice to have it open, so people could actually find it as an occurring issue.

It would have been really better to open a new issue, especially since you identified it to be a regression from a change in 4.4, while this issue was fixed in 4.3. A new bug with similar symptoms doesn't mean that an old fixed bug should be reopened, but that a new issue should be created (and it can refer back to the previous similar issue for additional context).

But now given that there's been significant discussion and debugging of the new bug in this ticket, let's repurpose it I guess.
