### ISSUE TITLE
Can't find any way to set blendmode for Tiles

### ISSUE THREAD

**Issue by x1212** [godotengine/godot#6142]
**Operating system or device - Godot version:**
Any version on any OS so far

**Issue description** (what happened, and what was expected):
You can set materials and blendmodes on TileMap but they don't do anything.
You can also set Materials for individual Tiles of a TileSet but there seems to be no way to set their blendmode.

In theory you can work around this by using a material with a shader that uses screensample to do the custom blending in the fragment-shader but that doesn't work that well for some platforms, especially if want to have several TileMaps for multiple Layers.

**Steps to reproduce:**
- create scene with a TileMap and draw some Tiles in that Map
- change Material and/or blendmode on that TileMap -> no changes visible
- try to change the blendmode on the Tiles in the TileMaps TileSet where you can set the Material -> there is no such option

**Link to minimal example project** (optional but very welcome):
if needed I will upload one ... but it should be easy enough to reproduce already

**Comment by bojidar-bg** [comment]
Seems like we should save the blendmode in the tileset as well.

**Comment by akien-mga** [comment]
Fixed by #7170.
