### ISSUE TITLE
ConfirmationDialog wrong position buttons

### ISSUE THREAD

**Issue by Chrisanthos** [godotengine/godot#6143]
**Operating system or device - Godot version:**
Windows 10-64 bit - 2.1-stable

**Issue description** (what happened, and what was expected):
What happened : 

![capture](https://cloud.githubusercontent.com/assets/20664041/17643646/13d77898-6179-11e6-8135-ac376634ba16.PNG)

What was expected :

![capture_2](https://cloud.githubusercontent.com/assets/20664041/17643651/26ee779c-6179-11e6-90ab-960db7311a72.PNG)

**Steps to reproduce:**
I have create a button and when i click it to open the pup up(ConfirmationDialog). The popup it shows but the OK button and the Cancel button at wrong position (Picture 1). When i try to move the popup the buttons get the right position (Picture 2).

**Comment by bojidar-bg** [comment]
@neikeq Any possible connection to your recent Container PRs? :smile:

**Comment by vnen** [comment]
I saw this happening *on editor*. When I ran the game it showed in the right position. Is this the same case?

**Comment by neikeq** [comment]
@bojidar-bg nope :P

**Comment by neikeq** [comment]
Is the issue also present in 2.0.x branch?

**Comment by Chrisanthos** [comment]
I don't know for older versions

**Comment by vnen** [comment]
Fixed by #6423.
