### ISSUE TITLE
Web editor does not launch, getting black screen.

### ISSUE THREAD

**Issue by mward25** [godotengine/godot#61438]
### Godot version

Godot 3.5 RC 2

### System information

Windows 11 last updated on 5-25-2022, and Arch Linux updated just a few days ago. Tested on Chrome, and Firefox on both Arch Linux and Windows. Using auto as the webgl renderer. Both my windows machine and my Linux machine are laptops, My windows machine has a 5000 series Ryzen 7 and an RTX 3060. My Linux machine has an intel graphics card and a GeForce GT 525M.

### Issue description

I am seeing a black screen on the web editor after I select Start Godot Editor. I tried waiting for 20 minutes after clicking the button, and nothing changed within that time. I have also tried it on multiple computers under both Google Chrome, and Mozilla Firefox.

NOTE: Works in Godot 3.5 RC 1.

NOTE: Disabling Malwarebytes Browser Guard (this is the only browser extension I have) does **NOT** effect it,  and my Linux machine does not have any browser extensions.

Web Console Output From Windows Machine On Google Chrome:

```
Godot Engine v3.5.rc2.official.5f9bc7ea5 - https://godotengine.org
godot.tools.js:337 OpenGL ES 3.0 Renderer: WebKit WebGL
godot.tools.js:337 Async. shader compilation: OFF
godot.tools.js:337  
godot.tools.js:337 WARNING: Asset Library not available, as it requires SSL to work.
I @ godot.tools.js:337
godot.tools.js:337    at: ProjectManager (editor/project_manager.cpp:2597) - Asset Library not available, as it requires SSL to work.
I @ godot.tools.js:337
08105a12:0x5629b Uncaught (in promise) RuntimeError: null function or function signature mismatch
    at Object::notification(int, bool) (08105a12:0x5629b)
    at Node::propagate_notification(int) (08105a12:0xf9a4f)
    at Node::set_name(String const&) (08105a12:0x430ef)
    at ProjectManager::_notification(int) (08105a12:0x7c76da)
    at ProjectManager::_notificationv(int, bool) (08105a12:0xe37369)
    at Object::notification(int, bool) (08105a12:0x5629b)
    at Control::_size_changed() (08105a12:0xfd263)
    at Control::_notification(int) (08105a12:0x98acbf)
    at Control::_notificationv(int, bool) (08105a12:0x5b170)
    at ProjectManager::_notificationv(int, bool) (08105a12:0xe37362)
36godot.tools.js:337 Output buffer has not enough frames! Skipping output frame.
I @ godot.tools.js:337
V @ godot.tools.js:167
d.port.onmessage @ godot.tools.js:175
```

NOTE:
I also just want to say that this is my first bug report, so if there is anything that I did wrong, please let me know.

### Steps to reproduce

Go to https://editor.godotengine.org/releases/3.5.rc2/, then click Start Godot editor.

**Comment by Calinou** [comment]
I can confirm this on 3.5.rc2 (Firefox 100, Fedora 36):

![image](https://user-images.githubusercontent.com/180032/170549314-43e9a68d-ef12-4fba-9416-2aadd34901e7.png)

**Comment by akien-mga** [comment]
Fixed by https://github.com/godotengine/godot/pull/61409.
