### ISSUE TITLE
AnimationPlayer `Call Method` executes twice

### ISSUE THREAD

**Issue by Jegber** [godotengine/godot#61431]
### Godot version

3.4.4.stable.official [419e713a2]

### System information

MacOS 12.3.1, also tested in Windows 10

### Issue description

AnimationPlayer `Call Method` is executed twice when the key is placed at the very end of the animation.

### Steps to reproduce

1. Create a Scene with an AnimationPlayer as a child of the main node
2. Create a new animation
3. Add a `Call Method Track`
4. At the very end of the of the track, place a key referencing a function in the parent node's script

When the animation is triggered, the function referenced by the key will execute twice.

### Minimal reproduction project

https://github.com/Jegber/godot-animationplayer-bug _(bugsquad edit: fixed the link)_
(Github won't let me upload a .zip for some reason. This repository is a project which replicates the bug.)

To see the bug in this project, simply Play either the World scene or the Player scene. Press Space to swing your sword. The key called at the end of the Player's attack animation will be executed twice.

This bug has apparently been around for a while now: https://godotengine.org/qa/74053/why-is-my-animationplayer-calling-this-method-twice

**Comment by Trudzen** [comment]
This bug seems also to exist in Godot 4 if the AnimationPlayer is part on an AnimationTree and you call the animation over AnimationNodeStateMachinePlayback.start(...) more than one time. First method call happens directly after the animation started and at the end of the animation as it should be.

**Comment by kleonc** [comment]
Present in `3.5.beta1`, seems fixed since `3.5.beta2` (most likely fixed by #54827).
cc @timothyqiu

**Comment by timothyqiu** [comment]
Yeah, if I comment out the state change in the method, it's the same endless loop as in #50636.

@Jegber you can try the recent 3.5.rc2.

**Comment by Jegber** [comment]
Verified bug no longer appears in 3.5.rc2. Thanks all!
