### ISSUE TITLE
Unexpected portal culling when reparenting and transforming

### ISSUE THREAD

**Issue by Splagoon** [godotengine/godot#61447]
### Godot version

v3.4.4.stable.official [419e713a2]

### System information

Windows 10, GLES3, NVIDIA GeForce GTX 1080 (30.0.15.1179)

### Issue description

When using portal culling, roaming objects will disappear unexpectedly when I reparent them and transform them.
For example, given the following scene tree:
- Room
  - Spatial1
    - VisualInstance (roaming)
  - Spatial2

If Spatial1 and Spatial2 have different global transforms, reparenting the roaming VisualInstance from Spatial1 to Spatial2 and then updating the VisualInstance's global transform to match Spatial1's global transform (i.e. changing the parent but keeping the same global transform) results in the VisualInstance getting culled. It's possible to make the VisualInstance reappear by either:
1. Deactivating the portal system
2. Changing the VisualInstance's portal mode to global
3. Moving the VisualInstance some distance away from where it disappeared

I've attached a sample project showing the VisualInstance disappearing when portal culling is on, but not when portal culling is off. Given that the camera and both spatials are all in the same room, ideally the VisualInstance should not get culled when reparented and moved.

### Steps to reproduce

1. Download and launch the example project
2. Use Space to reparent the ball
3. Use BackSpace to toggle the portal system on/off

- Pressing Space while the portal system is ON will cause the ball to disappear
- Pressing Space while the portal system is OFF has no visible effect

### Minimal reproduction project

Here's the .zip: [PortalRepro.zip](https://github.com/godotengine/godot/files/8781531/PortalRepro.zip)
Also uploaded to GitHub: https://github.com/Splagoon/GodotPortalRepro

**Comment by Calinou** [comment]
There have been many fixes to portals and rooms in 3.5 betas/RCs. Can you test [3.5rc2](https://godotengine.org/article/release-candidate-3-5-rc-2)?

**Comment by Splagoon** [comment]
I just tested v3.5.rc2.official [5f9bc7ea5] and it's still reproducible

**Comment by Calinou** [comment]
cc @lawnjelly

**Comment by lawnjelly** [comment]
Great MRP, was easy to fix. Many thanks. :+1:

**Comment by akien-mga** [comment]
Fixed by #61523.
