### ISSUE TITLE
I can get instance_id of Object in GDNative but can't get Object by instance_id

### ISSUE THREAD

**Issue by NicholasShatokhin** [godotengine/godot#61445]
### Godot version

3.3.stable

### System information

Windows 10, Windows 11

### Issue description

I can get instance_id of any Object using method:
`int64_t instance_id = obj->get_instance_id();`
or by result of code:
`		Physics2DDirectSpaceState* space_state = get_world_2d()->get_direct_space_state();
		const Array res = space_state->intersect_point(mouseGlobalPos, 1, godot::Array(), CursorCollisionLayer);
		if (!res.empty())
		{
			const Dictionary result = (Dictionary)res[0];
			mousePointsToObject = result[Variant("collider_id")];
		}`

But I can't use this id to get the Object back.

I tried:

`godot_object* instanceInt = godot_instance_from_id(mousePointsToObject);
Object* instance = (instanceInt) ? (Object*)godot::nativescript_1_1_api->godot_nativescript_get_instance_binding_data(godot::_RegisterState::language_index, instanceInt) : nullptr;
`

But got an error:

`Error	LNK2019	unresolved external symbol godot_instance_from_id referenced in function "public: void __cdecl godot::PlayerController::_process(float)"`

Is it possible? I see that issues https://github.com/godotengine/godot/issues/28478 and https://github.com/godotengine/godot/pull/34986 are closed but can't find how to use it.

### Steps to reproduce

1. Get the id of object: 
`int64_t instance_id = obj->get_instance_id();`
2. There is no way to get appropriate object from given id

**Comment by NicholasShatokhin** [comment]
I temporary solved it by wrapper class:

`
#pragma once

#include "Core/Types.h"
#include "GameAgent.h"

#include <Dictionary.hpp>
#include <Node.hpp>

class SceneObjectsManager
{
public:
	SceneObjectsManager()
	{
		sceneObjects.clear();
	}

	template <class T>
	void registerObject(T* gameAgent);

	void destroyObject(int instance_id)
	{
		if (sceneObjects.has(instance_id)) {
			sceneObjects[instance_id].call("queue_free", nullptr, 0);
			sceneObjects.erase(instance_id);
		}
	}

	bool isInstanceExists(int instance_id)
	{
		return sceneObjects.has(instance_id);
	}

	void registerAgent(godot::GameAgent* gameAgent)
	{
		registerObject<godot::GameAgent>(gameAgent);
	}
	void registerNode(godot::Node* node)
	{
		registerObject<godot::Node>(node);
	}

	godot::GameAgent* getAgentByInstanceId(int instance_id)
	{
		if (!sceneObjects.has(instance_id)) {
			return nullptr;
		} else {
			return sceneObjects[instance_id];
		}
	}

	godot::Node* getNodeByInstanceId(int instance_id)
	{
		if (!sceneObjects.has(instance_id)) {
			return nullptr;
		}
		else {
			return sceneObjects[instance_id];
		}
	}

public:
	static constexpr s64 NULL_REFERENCE = -1;

protected:
	godot::Dictionary sceneObjects;
};

template<class T>
inline void SceneObjectsManager::registerObject(T* object)
{
	if (object) {
		sceneObjects[object->get_instance_id()] = object;
	}
}

`

But I'm waiting for function **instance_from_id**

**Comment by Faless** [comment]
This is possible in godot 4 (gdextension) via:
```
ObjectDB::get_instance(p_id);
```
in https://github.com/godotengine/godot-cpp/blob/master/include/godot_cpp/core/object.hpp#L161

In GDNative, there seem to be a `godot_instance_from_id` ( https://github.com/godotengine/godot-headers/blob/219afc98f7e80664584f3988d7861aeaa31bbd8d/gdnative/gdnative.h#L298 ), which you should be able to use via:
```
godot::Object *obj = godot::detail::get_wrapper<Object>(godot::core_1_2_api->godot_instance_from_id(id));
```

**Comment by m4nu3lf** [comment]
@NicholasShatokhin
This code seems to be working for me in 3.x now

```
godot_object* instanceInt = godot_instance_from_id(mousePointsToObject); Object* instance = (instanceInt) ? (Object*)godot::nativescript_1_1_api->godot_nativescript_get_instance_binding_data(godot::_RegisterState::language_index, instanceInt) : nullptr; 
```

**Comment by Faless** [comment]
Closing as fixed, feel free to comment if this is still an issue.
