### ISSUE TITLE
Theme colors not updating after upgrade to Godot 2.1

### ISSUE THREAD

**Issue by fractilegames** [godotengine/godot#6145]
This happens in my application in the editor (on Xubuntu 16.04 x86_64) and when running on Android 5.0 device.

In a panel script I fetch current theme using get_theme(), modify its colors and call set_theme() with the modified theme. Previously (in Godot 2.0) this changed colors in all child controls immediately. Now the new colors show only after the controls are "activated" (e.g. mouse-over on button or label text changes). 

I assume that setting the theme no longer causes redrawing of controls.

**Comment by fractilegames** [comment]
Finally managed to work around the issue. I need to make a copy of the theme instance.

This does NOT work (worked in 2.0):

var theme = get_theme()
theme.set_color("font_color", "Button", color)
set_theme(theme);

This works:

var theme = get_theme().duplicate()
theme.set_color("font_color", "Button", color)
set_theme(theme);

**Comment by Calinou** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by AlexHolly** [comment]
Setting the same theme is beeing prevent by this.
https://github.com/godotengine/godot/blob/master/scene/gui/control.cpp#L2151

Resetting the same theme makes normally no sense. I think the actual issue is that 
`theme.set_color("font_color", "Button", color)` is not updating the theme (set the value but no visual change in Game/Editor).

Without a live update, working on themes is pretty hard since the default preview is not showing all Controls.

**Comment by AlexHolly** [comment]
https://github.com/godotengine/godot/commit/ab9bbce3114d476bc00bf19aa5eaec6998f29514
x11

Selecting a Node in Scene Tree uses 100% CPU

1. Create a new Theme for a Control
2. Use "Create From Current Editor Theme"
3. Create a new Control and select between first and second Node.
