### ISSUE TITLE
Pressing Option + 4 to enter `$` opens asset library tab on macOS

### ISSUE THREAD

**Issue by mcihad** [godotengine/godot#61468]
### Godot version

4.0 beta8

### System information

MacOS Monterey Radeon Pro 555 2 GB

### Issue description

When I press Option+4 for the $ character in the script editor in the engine, it switches to the asset library window. I delete this shortcut from Editor->Editor Settings->Shortcuts, when I restart the editor, the old shortcut comes back. Doesn't save shortcuts

### Steps to reproduce

Go to Editor -> Editor Settings -> Shortcuts
Type Open Asset Library in the search box.
Delete the shortcut with the X icon. Restart the engine. You'll see it's back to the way it was

**Comment by Calinou** [comment]
I can't reproduce this on 4.0.alpha 2e8862887 on Linux. This is likely a macOS-specific issue as that platform has a whole bunch of OS-specific code to handle shortcut overrides.

> 4.0 beta8

You meant 4.0.alpha8 :slightly_smiling_face:

**Comment by mcihad** [comment]
> You meant 4.0.alpha8 🙂
Yes, I'm sorry. I hope to say 4.0 beta 8 one day.

**Comment by mcihad** [comment]
> I can't reproduce this on 4.0.alpha [2e88628](https://github.com/godotengine/godot/commit/2e8862887c07708ea0d4cb015902c3001ea6f495) on Linux. If I clear the shortcut associated to the asset library in the Editor Settings' Shortcuts tab, it's still cleared after I restart the editor.
> 
> This is likely a macOS-specific issue, as that platform has a bunch of OS-specific code to handle shortcut overrides.
> 
> > 4.0 beta8
> 
> You meant 4.0.alpha8 🙂

Yes, I'm sorry. I hope to say 4.0 beta 8 one day.

**Comment by DavidMag** [comment]
I have the same issue for with "option+2" for typing @, tested on all or almost all alphas including the latest (4.0.alpha10).

Can do a screen recording if it would help.

**Comment by DavidMag** [comment]
Still present in alpha14, here comes a video

https://user-images.githubusercontent.com/22000931/184981395-510af71a-bb19-44ed-9e1c-3fef41e48684.mp4

**Comment by Calinou** [comment]
Can you reproduce this issue in 3.5?

**Comment by DavidMag** [comment]
No but discovered something interesting, seems to be two separate issues that have poped up in Godot 4.

**First**: The modified shortcuts gets reset when reloading the project.

**Second**: In 3.5 I could still write `© @ £ $` in the script editor and asset search input field which in Swedish keyboard layout is `alt + 1/2/3/4` even though the shortcuts used those commands.

Here is a video when trying in 3.5:

https://user-images.githubusercontent.com/22000931/184989289-43575a63-820b-45da-bb89-3050fb5d22bf.mp4
