### ISSUE TITLE
OS.get_window_safe_area() returns incorrect size on Android when not in fullscreen

### ISSUE THREAD

**Issue by madmiraal** [godotengine/godot#61467]
### Godot version

3.4.4, 3.5 RC2 and master

### System information

Android 8

### Issue description

`OS.get_window_safe_area()` uses the display size not the window size; so when Godot is not in full-screen mode e.g. when immersive mode is disabled, and the window size is not the display size, the calculations for `get_window_safe_area()` are wrong. 

### Steps to reproduce

Disable immersive mode. Call `OS.get_window_safe_area()`.

**Comment by Calinou** [comment]
To clarify, Android API level < 28 refers to Android 8 and below.

**Comment by madmiraal** [comment]
Actually the problem applies to all versions of Android not just to earlier versions of Android. `OS.get_windows_safe_area()` is using the display size not the window size to calculate the safe area; so when immersive mode is disabled, and the window size is smaller than the display size, the `OS.get_windows_safe_area()` calculations are wrong.

**Comment by sosasees** [comment]
¿are there any updates?.
this issue seems to be complately forgotten for 11 months.

**Comment by Alex2782** [comment]
> get_display_safe_area ( ) const
> Returns the unobscured area of the display where interactive controls should be rendered.

Does this description mean that the virtual keyboard should also be taken into account?

![Bildschirmfoto 2024-01-02 um 02 57 23](https://github.com/godotengine/godot/assets/41921395/b8b41bf6-dd13-4d7a-a182-387e48e87a16)

**Comment by sosasees** [comment]
> > get_display_safe_area ( ) const
> > Returns the unobscured area of the display where interactive controls should be rendered.
> 
> Does this description mean that the virtual keyboard should also be taken into account?

yes, this means the safe area is smaller when the keyboard blocks part of the screen.

**Comment by Alex2782** [comment]
Did it work properly in the past?

----------------
> get_display_cutouts ( ) const
> 
> Returns an [Array](https://docs.godotengine.org/en/stable/classes/class_array.html#class-array) of [Rect2](https://docs.godotengine.org/en/stable/classes/class_rect2.html#class-rect2), each of which is the bounding rectangle for a display cutout or notch. These are non-functional areas on edge-to-edge screens used by cameras and sensors. Returns an empty array if the device does not have cutouts. See also [get_display_safe_area](https://docs.godotengine.org/en/stable/classes/class_displayserver.html#class-displayserver-method-get-display-safe-area).
> 
> Note: Currently only implemented on Android. Other platforms will return an empty array even if they do have display cutouts or notches.

**This function does not return any data** (on my Samsung Tab, Android 13)

and `DisplayCutout cutout = insets.getDisplayCutout();` is also `= null`
https://github.com/godotengine/godot/blob/13a0d6e9b253654f5cc2a44f3d0b3cae10440443/platform/android/java/lib/src/org/godotengine/godot/GodotIO.java#L189

the following line means, from Android 9+
`if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) `

**Comment by Alex2782** [comment]
https://developer.android.com/develop/ui/views/layout/edge-to-edge

This topic is very complex, on my Google Pixel 4a can test it, `cutout` is not `null`


![Bildschirmfoto 2024-01-02 um 03 52 07](https://github.com/godotengine/godot/assets/41921395/f64adfc2-0fe6-4acd-9f64-89eedf40c584)

**Comment by Alex2782** [comment]
> uses the display size not the window size

I am trying to find solutions for this, with no guarantee of success 😃

**Comment by Alex2782** [comment]
What else should be tested?

https://github.com/godotengine/godot/assets/41921395/6a08baad-aab7-4242-a43d-3a8bc320b650
