### ISSUE TITLE
Godot shows an error in console if you're using C# 10 feature "File-Scoped namespaces" (ERROR: Failed to determine namespace and class for script)

### ISSUE THREAD

**Issue by valkyrienyanko** [godotengine/godot#61485]
### Godot version

3.4.4.stable.mono

### System information

Windows 10 64-bit

### Issue description

C# 10.0 added a new feature "[File scoped namespaces](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/file-scoped-namespaces)"

If you try to use this feature you will get a error that will flash before your eyes just before the game is done building but you can see the error clearly in VSCode console. (I opened Godot through VSCode)
```
ERROR: Failed to determine namespace and class for script: res://Scripts/UI/Inventory/ControlInventory.cs. 
Parse error: Unexpected token: Symbol
```
![image](https://user-images.githubusercontent.com/6277739/170807609-71b1e1c1-3b6e-43aa-8995-71496ed016ab.png)

The game seems to run fine. The error is the only annoying thing to see everything the game is started.

Having file-scoped namespaces would make scripts alot easier to read.

### Steps to reproduce

Convert any namespace in any script to a file-scoped namespace. Notice the error in the console just before game start.

With file-scoped namespace
![image](https://user-images.githubusercontent.com/6277739/170807619-a92ded06-b917-4c4e-8f2f-f5bc11753075.png)

Without file-scoped namespace
![image](https://user-images.githubusercontent.com/6277739/170807635-0b306787-f38e-4611-ad82-e97f06cfaf06.png)

**Comment by raulsntos** [comment]
Fixed by #56427
