### ISSUE TITLE
Regression with blend_add and ViewportContainer

### ISSUE THREAD

**Issue by jambonsupreme** [godotengine/godot#61484]
### Godot version

v3.5.rc2.official [5f9bc7ea5]

### System information

Windows 10 - GLES3 - RX 6700XT - AMD Software: Adrenalin Edition 22.5.2

### Issue description

Shaders that use blend_add exhibit a strange behaviour when viewed trough a ViewportContainer. This doesn't seem to happen with ViewportTextures.

![v3 5 rc2 official  5f9bc7ea5](https://user-images.githubusercontent.com/26414993/170801442-9f1f90a8-2d19-4927-bae0-b3112ec8eec2.jpg)

This is how it looks in Godot 3.4.4

![v3 4 4 stable official  419e713a2](https://user-images.githubusercontent.com/26414993/170801391-d5645a4b-df41-4a36-97e9-ddb9f5a33013.jpg)

### Steps to reproduce

1) Make a scene as such

![tree](https://user-images.githubusercontent.com/26414993/170801463-99c936e5-5014-4bf9-8719-5f7a96a66703.jpg)

2) Assign a shader with blend_add to the mesh

### Minimal reproduction project

I found this issue in my own project and I managed to reproduce it in a brand new project created in v3.5.rc2.official [5f9bc7ea5]

[blend_add bug.zip](https://github.com/godotengine/godot/files/8790138/blend_add.bug.zip)

**Comment by clayjohn** [comment]
Can you clarify what versions you are seeing this issue in?

At the top of your post you say 3.5 rc2 but at the bottom you say 3.4.5 rc2 (which doesn't exist). I'm guessing you mean to say 3.5 rc2 both times right?

**Comment by jambonsupreme** [comment]
Sorry I meant v3.5.rc2, I corrected the post

**Comment by clayjohn** [comment]
I have tested in 3.x (which will become 3.5 rc3) and it looks like this.
![Screenshot from 2022-05-27 19-16-28](https://user-images.githubusercontent.com/16521339/170805813-2fa5a4b9-9b84-4dc3-be20-fa80d77afd6f.png)

That is correct right? If so I will go ahead and close this bug report as already fixed. :)

**Comment by jambonsupreme** [comment]
I have built 3.5.x on linux and I can confirm that it's fixed. Closing the issue
