### ISSUE TITLE
Setting any Decal extends component down to zero, make it endlessly spam error (Condition "det == 0" is true.)

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#61491]
### Godot version

1f690f197a4fb0809afb2f59bf78e4d3d89fd847

### System information

Windows 11

### Issue description

![decal_bug](https://user-images.githubusercontent.com/3036176/170820720-87a1af5b-1764-4278-8a6e-4ca7b9ab2994.gif)

### Steps to reproduce

Create a `Decal` and try to change any component of `Extends` to zero.

### Minimal reproduction project

Too easy to reproduce.

**Comment by Calinou** [comment]
Note that this can also be reproduced by setting the Decal node's scale property to `Vector3(0, 0, 0)` (or any of its parents).

[test_decal_scale_0.zip](https://github.com/godotengine/godot/files/9116643/test_decal_scale_0.zip)
