### ISSUE TITLE
Option to choose frames or seconds display in AnimationPlayer's timeline

### ISSUE THREAD

**Issue by joelgomes1994** [godotengine/godot#6149]
The timeline in AnimationPlayer, by default, shows the time in seconds, and the cursor snaps to the seconds subdivisions instead of individual frames.

![timeline](https://cloud.githubusercontent.com/assets/19820741/17646452/74534bf8-61a0-11e6-9297-1502568b8f66.png)

This is not good when importing an external animation made through frames reference (like importing from Blender), and when is needed to have more precision too. I suggest to add an option to toggle the individual frames display (changing the grid and snapping as well).

And a question: Godot have an animation frame rate parameter? Thanks.

**Comment by Dillybob92** [comment]
Changing steps to 0 would allow for individual frames I think?

**Comment by akien-mga** [comment]
Fixed by 42032669238bdc807bc7b8f03fff87e6cb5847f1.
