### ISSUE TITLE
Peers list not updating when host leaves

### ISSUE THREAD

**Issue by hk-32** [godotengine/godot#61506]
### Godot version

4.0 Alpha 11

### System information

Windows 10

### Issue description

I'm using the `ENetMultiplayerPeer` class for testing multiplayer in Godot 4 and simply when running the game as a client, the `multiplayer.get_peers()` function still returns an array with length 1 after the host quits. And also the signal `peer_disconnected` does not fire upon the host leaving, only `server_disconnected` fires. I find that very inconsistent, especially because both `peer_connected` and `connected_to_server` fire when we connect to the server. I'm aware that, in the case of the host leaving, there won't be any further communication between clients but I still think our local list of connected peers should update to reflect the change. And I'm not even sure if these are bugs or just design choices as for some people the `server_disconnected` might be enough to just quit the game and return to menu because by then, the session is over anyways. But I still believe `get_peers()` should return the new list with the host removed. It doesn't make sense for `peer_connected` to fire when connecting to the server and for `peer_disconnected` to not fire when disconnecting from the server.

Also one more thing/inconsistency is that the signal `peer_connected` fires before `connected_to_server` when we connect to the server as a client. As `connected_to_server` signifies a successful connection and `connection_failed` signifies a failed connection, these are the first things we would want to know when connecting to a server. Or maybe `connected_to_server` should be eliminated because `peer_connected` achieves the same thing with a check or maybe `peer_connected` shouldn't fire when connecting to the server, then we won't have to fix `peer_disconnected` not firing on the host leaving.

My Issues
1.  `peer_disconnected` not firing when host leaves
2. `get_peers()` still returning an array that includes the host
3. `connected_to_server` should fire before `peer_connected` when connecting to the server

### Steps to reproduce

Literally the most basic `ENetMultiplayerPeer` project on localhost.

### Minimal reproduction project

[MultiplayerTest.zip](https://github.com/godotengine/godot/files/8791617/MultiplayerTest.zip)

**Comment by Calinou** [comment]
cc @Faless

**Comment by Faless** [comment]
Closing as fixed in `master` (will be in `beta5`) via #67917 .
