### ISSUE TITLE
`AnimationStateMachine` editor initially shows the top-left corner of the view instead of scrolling to the center

### ISSUE THREAD

**Issue by jacks0n9** [godotengine/godot#61500]
### Godot version

3.4.3 stable mono

### System information

MacOS 12.2

### Issue description

In the AnimationTree node, when I go to edit it, I can't see the nodes I created, I can see them in the parameters tab, and the code controlling it still works, but the nodes are invisible. I can add new nodes, they work, but I still can't see the ones I added previously. I tried saving the tree root as a scene, creating a new AnimationTree node, and setting that scene as the tree root, same problem.
<img width="1436" alt="Screen Shot 2022-05-27 at 7 12 59 PM" src="https://user-images.githubusercontent.com/67214151/170831633-367556a8-8e2d-4ec9-870c-d4b791f962b0.png">

### Steps to reproduce

I don't think I can find a way to reproduce it reliably, so here is how to use the project. Go into the `players/player.tscn` scene, click on AnimationTree node, no content. I'm sorry there is more than just the buggy part in there, but the project is still relatively minimal, so it should work.

### Minimal reproduction project

[godotbug.zip](https://github.com/godotengine/godot/files/8791389/godotbug.zip)

**Comment by kleonc** [comment]
Your nodes are in there, just scroll to the center of the view:
![f4XKgFTwQY](https://user-images.githubusercontent.com/9283098/170834266-1b3a4f45-277d-4216-b58a-1a8ea7161ff4.gif)

So the issue is that the scrollable area is quite big and when you open it it initially shows the top left corner, not the center.

**Comment by kleonc** [comment]
Actually `graph_offset` is being saved within `AnimationNodeStateMachine` resource. In your case within the scene file:
```
[sub_resource type="AnimationNodeStateMachine" id=16]
states/Attack/node = SubResource( 33 )
states/Attack/position = Vector2( 282, 178.562 )
states/Idle/node = SubResource( 15 )
states/Idle/position = Vector2( 287, 79.3281 )
states/Run/node = SubResource( 22 )
states/Run/position = Vector2( 548, 78.75 )
transitions = [ "Idle", "Run", SubResource( 23 ), "Run", "Idle", SubResource( 24 ), "Idle", "Attack", SubResource( 34 ), "Attack", "Idle", SubResource( 35 ) ]
start_node = "Idle"
graph_offset = Vector2( -1740, -525 )
```

And `AnimationNodeStateMachineEditor` respects such saved `graph_offset`. That part is fine I guess.

However, the saved `graph_offset` refers to the top left corner of the view which might be problematic. For example if you'd edit the state machine in a big view (e.g. distraction free mode + expand bottom panel), then save, then close the editor, then open the project again and then finally start editing state machine again then it would open in a small default view and the saved `graph_offset` for the big view would be kinda unrelevant. I guess saving graph offset for the center of the view would make more sense? :thinking:

**Comment by jacks0n9** [comment]
Yoooo thanks sounds like it's not a bug imma close this issue!
