### ISSUE TITLE
Vulkan: Low-roughness reflections from reflection probes look blocky

### ISSUE THREAD

**Issue by clayjohn** [godotengine/godot#61511]
### Godot version

Master (1f690f1)

### System information

Windows 10, RX 5600 XT Vulkan-clustered

### Issue description

When using reflection probes in combination with materials with a low roughness (0.01 - 0.25) it appears like a faint, but very low res version of the reflection is layered on top of the higher-res sharp reflection.
![Screenshot (273)](https://user-images.githubusercontent.com/16521339/170843745-f00d6aed-ad76-4267-b9b5-5d4052abcff5.png)

On the surface, it appears like the issue comes from the fact that our downsampled mipmap version of the reflections uses a 64x64 base size:
https://github.com/godotengine/godot/blob/1f690f197a4fb0809afb2f59bf78e4d3d89fd847/servers/rendering/renderer_rd/renderer_scene_sky_rd.cpp#L399-L408

But I am not sure that is the problem as that code has been in place for a long time and the problem is just being noticed now. And that code comes from the original fast filter implementation (paper [here](https://www.activision.com/cdn/research/paper_egsr.pdf))

Thank you to @Lyuma and Unfa for spotting this one and discussing on RocketChat

### Steps to reproduce

Run the MRP. This issue appears whenever roughness is low (under 0.25) and reflection probes are used. 

### Minimal reproduction project

[reflection-test-bug.zip](https://github.com/godotengine/godot/files/8792197/reflection-test-bug.zip)

**Comment by Calinou** [comment]
I can confirm this on 4.0.alpha 2e8862887 (Linux, NVIDIA 510.68.02).

Appearance with the Vulkan Mobile backend:

![image](https://user-images.githubusercontent.com/180032/170843902-db8c8cde-1513-4bcb-8aee-659da83d1f12.png)
