### ISSUE TITLE
(3.5) Label3D buggy when DynamicFont oversampling is working

### ISSUE THREAD

**Issue by wareya** [godotengine/godot#61517]
### Godot version

3.5

### System information

Windows 10

### Issue description

The Label3D node backported to 3.x in https://github.com/godotengine/godot/pull/61276 exhibits weird glyph scaling and linewrapping behavior when the project's window viewport scaling mode is set to 2d and dynamicfont oversampling is not disabled:

https://user-images.githubusercontent.com/585488/170848056-e038fe1c-c663-4d46-81e6-ddb45c9591ab.mp4

One of these issues, the unstable linewrapping, is <https://github.com/godotengine/godot/issues/56399>.

The other issue, with the individual glyphs being missized and misplaced, is specific to Label3D, and is why I'm opening a new issue. Updating the text or width of the Label3D after shrinking the window does not cause the missized/misplaced glyphs to re-flow.

4.0 probably does not have the first issue. I have no idea whether 4.0 would have the second issue.

### Steps to reproduce

1) Make sure dynamic font oversampling is enabled in project settings
2) Set project window viewport scale mode to "2D"
3) Put a dynamicfont and some text in a Label3D. Enable autowrap and reduce the width property to something that wraps
4) *Run the project,* resize the game window, and observe brokenness. (these issues don't happen in-editor)

You can add an identical autowrapping Label node with the same font, text, and width if you want to compare line wrapping oddities.

**Comment by Calinou** [comment]
The fix is likely to disable font oversampling on fonts used in a Label3D. However, font oversampling can sometimes be useful for Label3Ds that are used with **Fixed Size** and **Billboard** at the same time.

**Comment by Calinou** [comment]
> Or maybe with runtime-generated SDFs?

Unlike `master`, Godot 3.x doesn't support generating SDFs from DynamicFont files

**Comment by akien-mga** [comment]
Fixed by #61535.
