### ISSUE TITLE
Project manager - unicode problem

### ISSUE THREAD

**Issue by mefihl** [godotengine/godot#6151]
**Operating system or device - Godot version:**
Windows 10, Godot 2.1 stable

**Issue description** (what happened, and what was expected):
In "Project Manager" popup window example "New Project" not display unicode character 

**Steps to reproduce:**
1. Set Polish translation.
2. Open "Project Manager".
3. Look on "Project Path:" label.

![22288888888888](https://cloud.githubusercontent.com/assets/5302754/17649036/d2a3d8f6-6229-11e6-9380-726936fb5533.png)

Text label is "cieka do projektu:" and should be "Ścieżka do projektu:".

**Link to minimal example project** (optional but very welcome):

**Comment by bojidar-bg** [comment]
Note that the ó in the title is good

**Comment by mefihl** [comment]
Yes, window title string display ok, problem is with labels.

**Comment by mefihl** [comment]
This problem i'm see in other windows too, example in "Quick open scene".

**Comment by akien-mga** [comment]
I guess our font lacks extended latin glyphs.
