### ISSUE TITLE
3D lighting reduced energy/range in-game vs in-editor

### ISSUE THREAD

**Issue by alib86** [godotengine/godot#61525]
### Godot version

3.5.rc2 Mono 64bit (GLES3)

### System information

Windows 10, Nvidia GTX2060

### Issue description

I haven't been able to look into it in detail yet, but the scene that has been looking consistently same up to 3.5 Beta 4 now looks noticeably darker. Lit only with an OmniLight:
-In-game it looks as if light's range and energy values have been significantly reduced.
-In-editor it looks normal/as expected (and as it always did in previous versions).

Here's a screenshot editor vs in-game: (expected result is the editor look)
![godot lighting bug](https://user-images.githubusercontent.com/6481532/170884818-2da245f5-0bf8-4d84-979e-c13a43795d48.jpg)

### Steps to reproduce

Not quite sure, as the rest of the scenes look normal. This is a CSG box with collision containing an OmniLight for lighting. Will try to provide a reproduction project if I can find the time.

Checked back to back with Beta 4 with no changes, Beta 4 looks normal/same as editor rendering. Nothing fancy going on in this scene.

### Minimal reproduction project

[MinRepProj2.zip](https://github.com/godotengine/godot/files/8794337/MinRepProj2.zip)

**Comment by Calinou** [comment]
@alib86 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by alib86** [comment]
Using GLES3 (adding this information to main issue).

I will try to provide a minimal reproduction project soon.

**Comment by alib86** [comment]
So I tried to reproduce this now with the same light and values in a similar simple scene, but that works as expected. 

In my project the initial scene is quite large with many meshes/materials/lights and a different world environment, from there I remove the whole world from the tree and transition into this small room scene with its own light/world environment (keeping the same camera/player). Initial large scene renders as expected, but the room does not. I suspect this scene switch is causing an issue?

Just to confirm, this is how the exact same project looks in 3.5 Beta 4:
![image](https://user-images.githubusercontent.com/6481532/170887020-b69432a2-c06b-4ad1-b5f1-d63ab4f17d0e.png)

**Comment by clayjohn** [comment]
Are you rendering to a Viewport before rendering to the main screen? There have been some changes to how transparent viewports work recently as a result, it is possible that post-processing effects are applied twice.

**Comment by alib86** [comment]
@clayjohn Yes, I have a main viewport which I use to downscale the size to get a low-res look. Tree is like this:

-Control
--ViewportContainer
---Viewport
----Spatial (World)
-----Large Scene (renders normal)
(then I remove Large Scene and add the below)
-----Room Scene (renders dark)

There is a transition script between Large and Room scenes, which removes one and re-adds the other keeping the same Camera (Camera is inside World scene). Large scene always renders normal, room scene always renders dark independent on how many times I switch between them.

By post processing effects do you mean the WorldEnvironment values in these scenes? I don't have any other custom processing setup with the viewport, except the mentioned changing of the size for downscaling.

**Comment by alib86** [comment]
Update: Ok I added the same viewport setup to the min reproduction project and I think that's what's causing this. The camera gets wonky for some reason so I'll try to figure that out and upload it.

**Comment by clayjohn** [comment]
I believe the change I am thinking of was made after beta 5. To be clear, I'm not sure why it is causing your issue as it only applies to Transparent Viewports, but it is possible there is something I am missing. 

My guess is that something you are doing is now triggering the post-processing pass to apply twice, once while rendering the viewport and once while rendering the main scene. 

When doing 3D-in-2D like this it is important to ensure that your Viewport has ``own_world`` enabled so that it doesn't share a 3D world with the main viewport. In the scene heirarchy posted above the renderer may think that the room scene and large scene still need to be rendered to the main Viewport

**Comment by alib86** [comment]
@clayjohn Added a MRP to the main post. I'm not sure what I did wrong but the camera is not pointing at the right place - and sorry about the messy project, just threw it together - but if you run the project with 3.5 Beta 4 vs 3.5 RC2, you will see there is a perceptible difference in the rendered lighting:

(Beta 4 left / RC2 right)

![image](https://user-images.githubusercontent.com/6481532/170888847-4f649a1d-2269-4356-a39f-b59a607c2924.png)

**Comment by clayjohn** [comment]
I ran the attached MRP in 3.4.4 3.5 RC1 and 3.5 RC2 and got identical results in all three cases. 

Are you sure the attached MRP consistently reproduces the bug?

**Comment by alib86** [comment]
@clayjohn I don't think I ever used 3.4.4 but before 3.5 betas I used 3.4.1 stable which renders as expected (same as 3.5 Beta 4). I had the same scene without any changes back in 3.3.x and possibly 3.2.x versions which also did not cause any (noticeable) changes. 

I can give 3.4.4 a try if you want, but I can confirm with this MRP 3.4.1 stable and 3.5 Beta 4 render the same, vs 3.5 RC2 which is significantly different. Tried multiple times now and consistently get the same results.

Are you able to test either with 3.5 Beta 4 or 3.4.1 stable to compare? I would say maybe it's something to do with my environment but I open the exact same project with different Godot versions and get these different results.

**Comment by clayjohn** [comment]
Here is a screenshot running your MRP. 3.4.1 is on the left and 3.5 rc2 is on the right. 
![Screenshot from 2022-05-29 14-00-33](https://user-images.githubusercontent.com/16521339/170891287-d08d72ea-460c-4b49-86f5-a60b4732d2e7.png)

**Comment by alib86** [comment]
@clayjohn But are you running it directly as it is? The Control.tscn which is set up as the startup scene should be adding (via attached C# script) a CSG room (inverted cube) around this red cube, where the camera is wonky (couldn't figure this out) and will be pointing at a corner which displays the above white walls with yellow light casting on them. Just viewing a spatial without viewport does not change the render as you show.

**Comment by alib86** [comment]
Fixed and simplified MRP: (also updated in main post)
[MinRepProj2.zip](https://github.com/godotengine/godot/files/8794338/MinRepProj2.zip)

Please give it a try with this 3.5 Beta 4 vs RC2, Control.tscn should be your startup scene. I get these results:
RC2 left, Beta 4 right:
![image](https://user-images.githubusercontent.com/6481532/170892147-e98942e8-77a6-45d3-8e82-537d7d34e1be.png)

**Comment by alib86** [comment]
Update: switching on Transparent BG on the viewport fixes the issue for the room scene, but the prior large scene with sky is now not rendering as expected.

**Comment by alib86** [comment]
Just tested with 3.5 RC3, the issue seems to be resolved in my project and the attached MRP. Have the old behavior/rendering back. Thanks guys!

**Comment by clayjohn** [comment]
Wonderful! Thanks for testing again and updating us!
