### ISSUE TITLE
Node's editor description property tooltip is only updated when the scene is opened

### ISSUE THREAD

**Issue by iamtoaster** [godotengine/godot#61521]
### Godot version

v4.0.alpha8.official [cc3ed63af]

### System information

5.17.9-1-MANJARO Linux

### Issue description

When you add editor description to a node, you would expect that it would work immediately and show up in a node tooltip. As it stands, you have to reopen the scene for the nodes editor description to take effect.

### Steps to reproduce

1. Create a new project
2. Add a node (any node inherited from `Node`, I used `Node3D`) to the scene tree
3. Add a description to the node using node inspector
4. Save the scene (you can also do it after the next step, no difference)
5. Hover over the node in the scene tree and notice that the description you just added does not show up
6. Close and open the scene again
7. Hover over the node again to see description properly showing up

### Minimal reproduction project

[sample_project.zip](https://github.com/godotengine/godot/files/8792863/sample_project.zip)
A simple project with one scene with one node that has description applied to it. Any change to that description will only take effect after saving, closing and reopening the scene, as described above.

https://user-images.githubusercontent.com/22421580/170857896-cab6063c-3173-40c8-a8c4-65e59a49f1df.mp4

**Comment by Calinou** [comment]
This has always been an issue – [I even noted it in the initial implementation](https://github.com/godotengine/godot/pull/31389).
