### ISSUE TITLE
Could add node with same name under same tree node

### ISSUE THREAD

**Issue by puppetmaster-** [godotengine/godot#6152]
**Operating system or device - Godot version:**
Windows 7 64bit - Godot_v2.1-stable_win64.exe

**Issue description** (what happened, and what was expected):
Can create nodes with same name under same tree node.
![same_named_node](https://cloud.githubusercontent.com/assets/10463138/17649106/dbf8d576-622b-11e6-948f-d7ab3c26be05.png)
As expected I can't edit or delete the node in game scene.

**Steps to reproduce:**
Create scene game
Create scene player **without** camera2d
add instanced player scene to game
select player scene and add camera2d
open player scene add camera2d

You only can see the problem when checkbox **Editable Children** is selected.
![same_named_node_2](https://cloud.githubusercontent.com/assets/10463138/17652294/fe3178ee-6278-11e6-8d3b-c1f25cec95bf.png)

I don't know if its a bug or not, but it was confusing when editor tells you, you can't delete the node. :smile: 

Bug Project: [http://www.file-upload.net/download-11850356/same_name_bug.zip.html](http://www.file-upload.net/download-11850356/same_name_bug.zip.html)

**Comment by bojidar-bg** [comment]
Some initial debugging:
When we edit the "Camera2D" child via the "editable children" checkbox, we get this:
```ini
#...

[node name="player" parent="." instance=ExtResource( 3 )]

[node name="Camera2D" parent="player"]

rotating = true

[editable path="player"]

#^Note: we can safely remove this line, but then the Camera2d
# won't show up anymore (though the changes would remain)
```
But the attached scene has it like this:
```ini
#...

[node name="player" parent="." instance=ExtResource( 3 )]

[node name="Camera2D" type="Camera2D" parent="player"]

anchor_mode = 1
rotating = false

#....
```

Comparing the two lines, it seems like that the attached scene has only one major difference -- the `type="Camera2D"` attribute. So, this is somewhat related to #6215.

**Comment by Zireael07** [comment]
Still an issue, at least in 3.0 export of my project. Will be checking if it's present in 2.1.3, too.

**Comment by Noshyaar** [comment]
Still present in 3.0.2

**Comment by akien-mga** [comment]
Cherry-picked for 3.0.7.
