### ISSUE TITLE
Sprite image import is stretched when dragged into canvas

### ISSUE THREAD

**Issue by archangelamy** [godotengine/godot#61528]
### Godot version

v3.4.4.stable.official [419e713a2]

### System information

Mac OS Monterey ver 12.4

### Issue description

After having loaded an image into my project, I created a sprite and dragged the image into the window. However, the image is importing stretched out vertically. 
<img width="1184" alt="testdot" src="https://user-images.githubusercontent.com/106490546/170888162-5ee118f1-a0ea-490f-9572-f0fe9cb0bc02.png">

Very new at Godot/Github so please excuse me if I'm missing something obvious or if this is the wrong place.

### Steps to reproduce

Create new scene -> right click -> add new node (sprite) -> drag image file onto canvas.

**Comment by clayjohn** [comment]
Can you please post more information about the scene that this is in (even better if you can provide an [MRP](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project))?

Is there a chance the parent node is scaled?

**Comment by archangelamy** [comment]
[TestProject.zip](https://github.com/godotengine/godot/files/8794165/TestProject.zip)
MRP attached - under Node 2D scaled, I'm seeing x and y are both set to 1.

**Comment by kleonc** [comment]
Indeed the parent node is scaled:
![D8lE2fy3Ef](https://user-images.githubusercontent.com/9283098/170890545-5c69829d-6131-47b3-bb92-46dc634c0358.png)

It works as expected, there's no bug in here.

---

>Very new at Godot/Github so please excuse me if I'm missing something obvious or if this is the wrong place.

Indeed such report doesn't belong here, it's a simple user error / misunderstanding. In case you have doubts whether you're missing something obvious etc. please try reaching for help in other [community channels](https://godotengine.org/community) like Godot QA, Discord, Reddit, etc. (there are many helpful people in there too). :slightly_smiling_face:
