### ISSUE TITLE
Don't use absolute paths in imported resources

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#6153]
Tested on Godot 2.1, Windows 10 64 bits

I broke again my project because I moved it to another folder, but mesh resources are pointing to an absolute path. I can see that when hovering the red cross in the File Explorer.
It also seems to be the case for sounds. I remember seeing an issue about this, but wasn't able to find it.

**Comment by Zylann** [comment]
I made more tests on master, and apparently Godot imports files just fine when they are modified, even if I rename a part of the path. But I'd like to know why there is an absolute path in the imported resource, because it's a bit disturbing:

![absolute_path_in_smp](https://cloud.githubusercontent.com/assets/1311555/17838264/5d18fe86-67c9-11e6-8370-eb156e3ba69d.png)

**Comment by bojidar-bg** [comment]
BTW, is this valid in master, or just on 2.1 (since the new import system and stuff)?

**Comment by DualMatrix** [comment]
Tested in master, resource path seems to be relative now.

**Comment by akien-mga** [comment]
Should be fixed since 3.0 indeed.
