### ISSUE TITLE
Can't change color of splitcontainer

### ISSUE THREAD

**Issue by Remixful** [godotengine/godot#61534]
### Godot version

3.3.stable

### System information

Windows 10, GLES2, NVIDIA GTX 970

### Issue description

I've tried messing around with the theme options for the HSplitContainer, but I was unable to change the color of the divider. It's stuck to this plain gray.

### Steps to reproduce

Create a HSplitContainer and try to change the divider's color.

**Comment by fire-forge** [comment]
Having a divider modulate theme option for SplitContainer would be nice to have.

As a workaround, you can either color the image used for the divider or change the `self_modulate` property to color it.

**Comment by Mickeon** [comment]
I don't understand the issue, why is using `modulate` or `self_modulate` the workaround rather than the exact solution?

**Comment by fire-forge** [comment]
@Mickeon Most Control nodes that display images (like Button, ItemList, etc.) have a theme color for modulating the image only, but SplitContainer doesn't.

**Comment by Mickeon** [comment]
I was trying to implement this but I am struggling to even have a SplitContainer show its image on master...
