### ISSUE TITLE
Android Editor ignores input from specific keyboards (Samsung cover tablet detected as gamepad)

### ISSUE THREAD

**Issue by univeous** [godotengine/godot#61542]
### Godot version

3.5 rc2 and 4.0 alpha8

### System information

Android 12

### Issue description

When I play around with Godot on my Samsung tablet with the official keyboard cover, Godot Editor seems to ignore my keyboard input.

I can use the keyboard to code script normally, but I can neither use the keyboard for UI navigation (up, down, left, right, tab, etc.), nor can I add any of the keyboard keys to the input map. 

When I run the game, all keyboard keys are invalid. If I press randomly, the editor gives the following error.
![image](https://user-images.githubusercontent.com/40604180/171019577-e9f82200-1891-49de-b4b4-9bf81710fe15.png)
It seems that Godot incorrectly considers the keyboard to be a controller.

### Possible useful information

Although I haven't tried it yet, I assume that a Bluetooth keyboard or a keyboard connected via USB works fine (since I don't see the relevant issues).
The official keyboard cover does not connect via Bluetooth or USB, but via the pogo pin on the tablet.

### Steps to reproduce

Open Godot Editor on a Samsung tablet with keyboard cover.

**Comment by madmiraal** [comment]
Related to #47656

**Comment by univeous** [comment]
Closing - I can't reproduce this issue in Godot 4.4 dev5.

Maybe Samsung's system update did something?
