### ISSUE TITLE
animation 'method invocation' doesnt always work in godot4

### ISSUE THREAD

**Issue by djmaesen** [godotengine/godot#61546]
### Godot version

4.0 alpha8

### System information

linux

### Issue description

script method invocation doesnt always work in godot4 alpha

### Steps to reproduce

dont really know how.

**Comment by djmaesen** [comment]
![screen](https://user-images.githubusercontent.com/95492794/171050215-3a32a4b1-6a56-443b-b5bd-f064e83c5f0f.jpg)

**Comment by djmaesen** [comment]
![screen1B](https://user-images.githubusercontent.com/95492794/171050475-c5efe0ef-d5e2-4437-afee-9089e7657ac6.jpg)
im also getting these errors since alpha8

**Comment by KoBeWi** [comment]
This needs a minimal reproduction project.

**Comment by djmaesen** [comment]
> This needs a minimal reproduction project.

strange thing is that it works on some models and others dont.
dont really know how to make a minimal repo project, i dont want to share my assets

**Comment by djmaesen** [comment]
heres a repo project
invoke method doesnt get called
[testproject.zip](https://github.com/godotengine/godot/files/8806906/testproject.zip)

**Comment by KoBeWi** [comment]
There is no method track in the project:
![image](https://user-images.githubusercontent.com/2223172/171440668-1455fa4b-d8ee-4f40-b9e4-010a64e7b134.png)

I think this is due to:
![image](https://user-images.githubusercontent.com/2223172/171440730-6513b3b5-a4b8-4c5d-b4ab-a4e4b130574c.png)

So this is not a bug. You are not supposed to edit imported animations. Make them unique first.

**Comment by djmaesen** [comment]
@KoBeWi 

i saved a new inherited scene and i cant still add an invoke method to the animations
seems like a strange design decision.

**Comment by Zireael07** [comment]
@djmaesen: IIRC the way to do this is to save animation to a resource (*.res/tres) and then load it and 'make unique'. (Disclaimer: I only did it once some time ago so I may be wrong)

**Comment by djmaesen** [comment]
> There is no method track in the project: ![image](https://user-images.githubusercontent.com/2223172/171440668-1455fa4b-d8ee-4f40-b9e4-010a64e7b134.png)
> 
> I think this is due to: ![image](https://user-images.githubusercontent.com/2223172/171440730-6513b3b5-a4b8-4c5d-b4ab-a4e4b130574c.png)
> 
> So this is not a bug. You are not supposed to edit imported animations. Make them unique first.

how do u make a animation unique? there should be an option on import settings to save animations as unique imo.
i cant load animations into an animationplayer of a new inherited scene

**Comment by KoBeWi** [comment]
I don't know what's the intended workflow tbh, you can right-click the animation library in the inspector and make it unique:
![image](https://user-images.githubusercontent.com/2223172/172637593-61faf879-9d9b-4504-a9c0-88e260f51d76.png)
It doesn't get rid of the warning, but adding method track seems to work.

**Comment by djmaesen** [comment]
> I don't know what's the intended workflow tbh, you can right-click the animation library in the inspector and make it unique: ![image](https://user-images.githubusercontent.com/2223172/172637593-61faf879-9d9b-4504-a9c0-88e260f51d76.png) It doesn't get rid of the warning, but adding method track seems to work.

i cant add animations to a new library on my end (i cant even open a new library) even tho they are saved on disk
i guess ill have to get rid of the "call method" option. it clearly doesnt work. this is really bad

**Comment by djmaesen** [comment]
@KoBeWi 
in alpha9 'manage animation labraries ' button 'make unique' is unclickable , so is every other button in the library options

**Comment by djmaesen** [comment]
i just checked godot 3.4 and u there u can add an invoke method without making the animation unique first.
why is this changed? its so much easier to just edit a new inherited scene of the animated model

**Comment by KoBeWi** [comment]
Does it save properly though?

**Comment by djmaesen** [comment]
> Does it save properly though?

ah , no. i was wrong, sorry
still cant figure out on how to make an animation unique in godot 4 alpha 9 though

**Comment by KoBeWi** [comment]
This basically repeats what I already said but
![godot_bHqfjToJGk](https://user-images.githubusercontent.com/2223172/173442315-ebbe3258-a46f-4a68-8992-34c314d37300.gif)
This is the test project you attached. Does it look differently for you?

**Comment by djmaesen** [comment]
making the animations unique was indeed the solution
ive also managed to get rid of the errors
