### ISSUE TITLE
Tricky name on Font Import option

### ISSUE THREAD

**Issue by EdwardAngeles** [godotengine/godot#6154]
Hi.

In the Font Import Panel there is an option named "Disable Filter" that has to be 'On' if we want to import the bitmap font without filter and 'Off' if we want it with filter. Wouldn't be easier to just name the option "Filter" or "Use Filter" (as in DynamicFonts) an have it 'On' or 'Off' if we want to use filter or not? What you guys think?

![font_import](https://cloud.githubusercontent.com/assets/6760623/17652091/fe78f2b4-6241-11e6-9259-38aeed21ba0c.png)

**Comment by reduz** [comment]
no, not possible because once textures are imported, they are shared
between all font users

**Comment by EdwardAngeles** [comment]
I think I didn't explain myself well.
In a nutshell: Rename "Disable Filter" to "Filter".

Silly usability thingy but I'm just saying.

**Comment by bojidar-bg** [comment]
:+1: :+1: and :+1: again. Misleading options are the worst we can have around those menus.

**Comment by akien-mga** [comment]
Fine by me to rename it to "Filter" / "Enable Filter" or "Use Filter" and switch the default value to true.
