### ISSUE TITLE
Imported pck files containing scripts using class_name do not work, all references break

### ISSUE THREAD

**Issue by madmachinations** [godotengine/godot#61556]
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

3.4.3 stable / 4.1.1 stable

### System information

Linux, PopOS 20.04, GLES2, Intel Iris Plus Graphics G7, Mesa 21.2.2

### Issue description

If you have declared global classes using `class_name` in your project, and you then export the project to a `.pck` file to be imported into a different project; All the references to these scripts/classes will break and the pack won't work.

### Steps to reproduce

Create a project which includes a globally referenced class that has been declared using `class_name`, export this project to a `pck` file.

Create a second project which imports this pack file, and tries to load any scene whose script references that globally declared class.

Attempt to run the second project, it will fail. Debugger reports being unable to read the byte code in the script file.

But if you remove any references to this globally declared class in the first project, export the pack again, and attempt to load the second project with the new pack just using some basic scripting and no global classes - it works just fine.

### Minimal reproduction project

[game_test.zip](https://github.com/godotengine/godot/files/8804016/game_test.zip)

This file contains two projects:

A *game* project which includes a global class declared with `class_name`, that has been exported to a `.pck` file.

That pack file is inside the *launcher* project, which attempts to import and load the main scene from that pack file.

It breaks with the error specified above.

If you remove the three lines in the first project that reference and use the global `Shibble` class, and re-export the pack into the second project - it will run fine.

**Comment by Calinou** [comment]
Class name information is stored in `project.godot`and is exported as `project.binary` in the PCK. Unfortunately, this file cannot (and shouldn't) be overridden by another PCK loaded at run-time, so this is not technically possible to support with the current GDScript implementation.

**Comment by HaSa1002** [comment]
You can overwrite `_global_script_classes` using the overrides.cfg, causing a whole other can of worms. If one really wants to support these types maybe add a custom loader that registers them into the `_global_script_classes` in the ProjectSettings. Idk. This is super cheasy...

**Comment by dlstar89** [comment]
Remove my comment if not relevant but same issue is with Godot 4 (4.0.2), so far as mentioned above the only way to go around this is to load('script_path').new(), using class_name of the class i.e. TestClass.new() causes error

**Comment by dlstar89** [comment]
@HaSa1002 by any chance do you know if the same can be done for Godot 4, as in is there a way to override global classes definition or something in the override.cfg?

**Comment by HaSa1002** [comment]
Nope this was changed in the rebuild of GDScript. The GDScript team may know how to handle that nowadays. I dunno but maybe you can load the script and perform a reload? Like `load(user://unsafe.gd).reload()` no idea

**Comment by madmachinations** [comment]
This is still a problem in Godot 4.1.1, any global classes which are imported via a pck file do not register

**Comment by teddybear082** [comment]
Glad I found all of this and now know I am not crazy after spending several hours this morning trying to get custom classes to register.  Although I think I would have rather found out I was an idiot doing something wrong rather than finding out that godot 4 broke this functionality that was present in godot 3.x to add custom classes into override.cfg.

**Comment by jbromberg** [comment]
Can confirm this issue is still prevalent and basically breaks exporting your game as a pck or zip if you're using custom classes defined via `class_name`

**Comment by jbromberg** [comment]
This also leads to issues with identifying dependencies correctly. If I have a node with a script that references a static method of another script identified via `class_name`, that is not exported with the pck as a dependency of that script and the connection is lost and the script fails to execute.
