### ISSUE TITLE
Populating MultiMeshInstance causes an editor crash.

### ISSUE THREAD

**Issue by D1gitalCuts** [godotengine/godot#61553]
### Godot version

3.5 RC2

### System information

Windows 11, GLES3

### Issue description

The "Populate MultiMesh" context dialogue causes a crash. 
This issue was definitely not present in 3.5 beta 4, haven't checked other versions between Beta4 and RC2.

### Steps to reproduce

In the project attached below, select the MultiMeshInstance node, open the "Populate Surface" dialogue and select the target surface and source mesh accordingly. Now, clicking "Populate" will cause a crash.

### Minimal reproduction project

[MultimeshCrashMVP.zip](https://github.com/godotengine/godot/files/8802351/MultimeshCrashMVP.zip)

**Comment by clayjohn** [comment]
This error message seems to indicate that an existing mesh is necessary. 
https://github.com/godotengine/godot/blob/a837accc5d058e4eec29f4d854da8cb9f55a97cf/editor/plugins/multimesh_editor_plugin.cpp#L54-L67
Although that doesn't really make sense as a new multimesh is created.

I think a simple check for whether the multimesh exists is fine.

**Comment by akien-mga** [comment]
Fixed by #61718.
