### ISSUE TITLE
Pixel perfect collisions don't work

### ISSUE THREAD

**Issue by return2monki** [godotengine/godot#61557]
### Godot version

3.4.4

### System information

Windows 10, GLES3, Intel HD Graphics 620

### Issue description

I'm making a small grid based game and I have a problem where if I have 2 16x16 Collisionshape2d rectangles next to eachother they WILL collide.

### Steps to reproduce

project contains:
debug>visible collision shapes
add 2 area2ds, collisionshape2d, colorrect
check if they overlap in a script by showing/hiding colorrect

Run the game then move the area2ds in the scene view, the colorrect will show if they overlap or hide if they don't.

if you change the position or scale to 0.999 they will not overlap and fixes the problem, but that feels cheap. I'm just wondering what the problem is. The colorrects default to visible so you have to change pos or scale before seeing the problem.

Also changing the stretch mode to viewport makes the collisionshapes look bad in game with debug enabled, but that's only visual and doesn't seem to impact actual collisions.

### Minimal reproduction project

[test123.zip](https://github.com/godotengine/godot/files/8804784/test123.zip)

**Comment by return2monki** [comment]
> The first is most likely a floating point accuracy issue. Godot's 2D physics engine is NOT meant for pixel perfect games.

But how can there be a floating point problem if they are just 2 stationary square collision shapes that are on whole number coordinates?

**Comment by Deozaan** [comment]
> But how can there be a floating point problem if they are just 2 stationary square collision shapes that are on whole number coordinates and 16x16 in size?

I think it's because floating point numbers can't always represent whole numbers accurately. Even though they may look like integers, they're actually stored internally as floats, with all the imprecision that entails.

**Comment by return2monki** [comment]
> > But how can there be a floating point problem if they are just 2 stationary square collision shapes that are on whole number coordinates and 16x16 in size?
> 
> I think it's because floating point numbers can't always represent whole numbers accurately. Even though they may look like integers, they're actually stored internally as floats, with all the imprecision that entails.

Yea I know they're all floats, I just thought that the accuracy issue would only apply if you have a big number or did some weird calculations that causes it.

The part that confuses me is that when I print a float or Vector2 in godot it shows me a correctly rounded number like 10.0, so it isn't actually showing the real number that's being stored? Even if I subtract from a number [it still doesn't show this output.](https://www.geeksforgeeks.org/floating-point-error-in-python/)

Anyway, I saw that Godot 4 is coming with [Vector2i](https://docs.godotengine.org/en/latest/classes/class_vector2i.html) so that could solve this.

Gonna close this but if anyone has more info I appreciate that as well.
