### ISSUE TITLE
SurfaceTool triangle strips don't create faces in a Mesh

### ISSUE THREAD

**Issue by MandL27** [godotengine/godot#61552]
### Godot version

3.4.4.stable.mono

### System information

Windows 10 21H1

### Issue description

I'm creating a triangle strip along a curve with SurfaceTool, committing it to a MeshArray, then assigning that to a MeshInstance. If I use the `TriangleStrip` primitive type, subsequently calling `CreateTrimeshCollision()` on the MeshInstance fails, and the Mesh says it has zero faces despite rendering properly. If I instead use the `Triangles` primitive type and include duplicate verts appropriately (012132 instead of 0123), everything works as expected. I first suspected this was related to #38391, but the fix there of calling `Mesh.GetFaces().Count()` does nothing and still reports zero faces.

### Steps to reproduce

* Create a SurfaceTool using `Mesh.PrimitiveType.TriangleStrip`.
* With it, create a quad:
```cs
st.AddNormal(Vector3.Up);
st.AddVertex(Vector3.Right);
st.AddNormal(Vector3.Up);
st.AddVertex(Vector3.Zero);
st.AddNormal(Vector3.Up);
st.AddVertex(Vector3.Forward + Vector3.Right);
st.AddNormal(Vector3.Up);
st.AddVertex(Vector3.Forward);
```
* `AddIndex()` may be used here but is redundant with the ordering given.
* `Commit()` it to an ArrayMesh and assign that to a MeshInstance.
* Call `CreateTrimeshCollision()` on the MeshInstance. This should error and produce nothing.
* Change the primitive type to `Triangles` and add the following before committing:
```cs
st.AddIndex(0);
st.AddIndex(1);
st.AddIndex(2);
st.AddIndex(1);
st.AddIndex(3);
st.AddIndex(2);
```
* This should run fine and produces a collision mesh as expected.
The included repro project generates with `Triangles` by default. To use `TriangleStrip`, comment the call to `STTriangles()` and uncomment the call to `STTriStrip()`.

### Minimal reproduction project

[STTest.zip](https://github.com/godotengine/godot/files/8801573/STTest.zip)

**Comment by clayjohn** [comment]
Looking through the code, it looks like it is designed to only work with primitive type ``Triangles``. That is not to say it can't work with other primitive types, but it won't be trivial to extend it.

Internally ``create_trimesh_collision()`` calls ``generate_triangle_mesh()`` which only works with triangles. One option is to convert the mesh to using the triangles primitve before generating the triangle mesh. Another option is to extend ``generate_triangle_mesh()`` to support other primitive types.
