### ISSUE TITLE
enet fails building on Windows, Android, iOS (missing enet/unix.h)

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#6156]
**Operating system or device - Godot version:**
Current master branch.

**Issue description** (what happened, and what was expected):
See travis build report: https://travis-ci.org/godotengine/godot/builds/152330609

```
In file included from modules/enet/networked_multiplayer_enet.h:5:0,
                 from modules/enet/networked_multiplayer_enet.cpp:1:
modules/enet/enet/enet.h:18:23: fatal error: enet/unix.h: No such file or directory
 #include "enet/unix.h"
                       ^
```

**Comment by vkbsb** [comment]
pull request #6160

**Comment by vkbsb** [comment]
I was able to fix this issue for android/ios but not for windows :(

**Comment by Razzlegames** [comment]
Is there anyway we can wait to merge pull requests until the Travis builds succeed?

**Comment by punto-** [comment]
How hard would it be to make enet use the tcp/udp abstraction layer,
instead of the OS apis directly? that would make it actually portable, and
we already have those implemented for each OS

**Comment by reduz** [comment]
I checked it and it's not a very good absraction

**Comment by Zylann** [comment]
I just compiled Godot master successfully on Windows, was this fixed? Or is it only Travis?

**Comment by vnen** [comment]
It was fixed for Windows, but still failing for non-tools builds.

**Comment by akien-mga** [comment]
> Is there anyway we can wait to merge pull requests until the Travis builds succeed?

That's what we do, but @reduz does not do pull requests, he pushes directly to master, thus skipping the PR travis build.
