### ISSUE TITLE
signal "velocity_computed" does not seem to work in 3.5rc2

### ISSUE THREAD

**Issue by e-Forest** [godotengine/godot#61561]
### Godot version

3.5 rc2

### System information

Windows 11

### Issue description

In the test-project a character(RigidBody) has to find a way around some boxes.

With Godot 3.5 rc1 all works well.

With Godot 3.5 rc2 it does not work.
It seems that the signal "velocity_computed" is not triggered.

### Steps to reproduce

![scene](https://user-images.githubusercontent.com/50156472/171181279-f66c1145-2348-4f4b-ae34-ce2abe5be1cc.jpg)

`
extends RigidBody

func _ready():
	$NavAgent.connect("velocity_computed",self,"_on_velocity_computed")
	$NavAgent.set_target_location(Vector3.ZERO)

func _physics_process(delta):
	var distance_next_location = $NavAgent.get_next_location() - global_transform.origin
	var distance_target = $NavAgent.get_target_location() - global_transform.origin
	var direction = (distance_next_location).normalized()
	
	if distance_target.length() > $NavAgent.target_desired_distance:
		$NavAgent.set_velocity(direction*$NavAgent.max_speed)
	else:
		$NavAgent.set_velocity(Vector3.ZERO)
		

func _on_velocity_computed(safe_velocity):
	linear_velocity = safe_velocity

`

### Minimal reproduction project

[test_project.zip](https://github.com/godotengine/godot/files/8805350/test_project.zip)

**Comment by Zireael07** [comment]
To compute velocity, you need to have a tickbox checked on. It used to be automatically done, but now isn't for performance.

The PR that changed it is #61235
