### ISSUE TITLE
Regression: NavigationAgent doesn't calculate path since 3.5-rc2

### ISSUE THREAD

**Issue by warriormaster12** [godotengine/godot#61560]
### Godot version

3.5-rc2

### System information

Arch Linux AMD Ryzen 2500U GLES3

### Issue description

I've noticed when developing a game that with version 3.5-rc2 navigation agents no longer move to target location at all while in 3.5-rc1 build they are capable to do so. I'll use this github repo as an example since it's one of the projects affected by the regression. I have other project as well that is affected by the issue but I can't share the code for it.

https://github.com/warriormaster12/FinalStand

### Steps to reproduce

1. Open the project
2. Launch game
3. character should move but it doesn't with rc2 build, rc1 build still works.

**Comment by Zireael07** [comment]
Found the PR that changed things: #61235
