### ISSUE TITLE
Weird particle phenomenon

### ISSUE THREAD

**Issue by PoisonousGame** [godotengine/godot#61570]
### Godot version

V4.0 alpha8.official cc3ed63af

### System information

Win11  GeForce GTX1060 6GB

### Issue description

When I fire a fireball with particles, weird beams appear on the screen.

### Steps to reproduce

Check the file, fire by space

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/8806685/Test.zip)

![动画](https://user-images.githubusercontent.com/39994989/171217335-1fb2452a-a710-4cfa-a902-70bde4977759.gif)

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/56691 (same cause).
