### ISSUE TITLE
SoftBody attachment points get messed up after open project with 3.5 RC2

### ISSUE THREAD

**Issue by GameDevR** [godotengine/godot#61581]
### Godot version

v3.5.rc2.official [5f9bc7ea5]

### System information

Windows 11, GLES3, AMD Radeon RX 5700

### Issue description

If I open up an Godot project created with an previous version (e.g. 3.4 stable) and open it in 3.5 RC2, the attachment points of the SoftBody node gets messed up in the scene file (/ get removed and all values are null).

Before loading with 3.5 RC2:
```
attachments/0/point_index = 58
attachments/0/spatial_attachment_path = NodePath("..")
attachments/0/offset = Vector3( 0.428571, 1, 0.191715 )
attachments/1/point_index = 61
attachments/1/spatial_attachment_path = NodePath("..")
attachments/1/offset = Vector3( -0.428571, 1, 0.191715 )
```

After loading with 3.5 RC2:
```
attachments/0point_index = null
attachments/0spatial_attachment_path = null
attachments/0offset = null
attachments/1point_index = null
attachments/1spatial_attachment_path = null
attachments/1offset = null
```

If I run the project I also see following error message twice in the errors tab: 
```
E 0:00:00.729   _update_cache_pin_points_datas: Spatial node not defined in the pinned point, this is undefined behavior for SoftBody!
  <C++ Source>  scene/3d/soft_body.cpp:773 @ _update_cache_pin_points_datas()
```

### Steps to reproduce

* Extract the attached example project (same as my other issue: https://github.com/godotengine/godot/issues/57974)
* Check Main.tscn with editor and check the attachments part (everything is fine)
* Open the project with 3.5 RC2 version and save/run it
* Afterwards check again the Main.tscn file -> attachments part is messed up

### Minimal reproduction project

[SoftbodyIssue.zip](https://github.com/godotengine/godot/files/8809336/SoftbodyIssue.zip)

**Comment by akien-mga** [comment]
I can confirm the bug, it's a regression from #61141. I'll send a fix shortly.
