### ISSUE TITLE
Node.find_children() does not recurse with recursive=true

### ISSUE THREAD

**Issue by vfig** [godotengine/godot#61608]
### Godot version

v4.0.alpha8.official.cc3ed63af

### System information

Windows 10

### Issue description

`Node.find_children()` should recurse through all descendant nodes when `recursive` is true; so calling `find_children("", "Node3D", true)` should be returning all descendants that inherit from Node3D. But instead it only returns the immediate children, regardless of what is passed for `recursive`.

![bug_find_children](https://user-images.githubusercontent.com/81129/171442325-45aabd3c-a2ef-471a-912b-4b5888365674.png)

### Steps to reproduce

With the attached project, run the main scene, and check what is printed.

### Minimal reproduction project

[bug_find_children.zip](https://github.com/godotengine/godot/files/8815601/bug_find_children.zip)

**Comment by fire** [comment]
I recommend aligning the name / documentation instead of changing the behavior which needs a proposal.

**Comment by vfig** [comment]
Duplicate of #54939
