### ISSUE TITLE
Adding script templates to project or editor folder does not make it appear on the "Create New Script" Dialogue

### ISSUE THREAD

**Issue by eh-jogos** [godotengine/godot#61614]
### Godot version

4.0.alpha8

### System information

Manjaro Linux, Vulkan

### Issue description

I've added a template script to the project folder `res:://script_templates/` like I used to do in Godot 3.x but it is not showing up on the Create new script dialogue.

I tried to add it directly to the editor `script_templates` folder and it also did not work, I use the editor in self contained mode.

Tried to take a look at the latest documentation, but it doesn't seem like I'm doing anything different:
https://docs.godotengine.org/en/latest/tutorials/scripting/creating_script_templates.html

Even tried to copy-paste the example in the documentation but got nothing.

### Steps to reproduce

Start a new project, extract the attached zip file (it's just the "script_templates" folder with two files, the one I use and the example from the documentation) on the root folder of any godot 4.0 project and try to create a new script.

### Minimal reproduction project

[script_templates.zip](https://github.com/godotengine/godot/files/8818542/script_templates.zip)

**Comment by timothyqiu** [comment]
In 4.0, you have to put the template script inside a folder with the name of your target class.

e.g. If your template script targets any `Node`, then it has to be at `res://script_templates/Node/some_name.gd`.

**Comment by eh-jogos** [comment]
Thanks a lot @timothyqiu

**Comment by NationalityNZ** [comment]
This was tripping me up big time. This really needs to be added to documentation.

**Comment by eh-jogos** [comment]
@timothyqiu using %BASE% or the other placeholders on my template is not working on alpha9. Have they changed and is this another obsolete documentation problem or should I open a separate issue for it?

**Comment by timothyqiu** [comment]
@eh-jogos Ah, yes, these `%XXX%` were changed to `_XXX_`. So it's `_BASE_` now in 4.0.

You can open an issue in [godot-docs](https://github.com/godotengine/godot-docs) repository to request an update of the documentation.

**Comment by eh-jogos** [comment]
@timothyqiu Thanks a lot! Will open the issue there then!

**Comment by KoBeWi** [comment]
I opened the docs issue: https://github.com/godotengine/godot-docs/issues/5887
