### ISSUE TITLE
Black Screen on Android after Export from Godot 3.5 RC3

### ISSUE THREAD

**Issue by RodrigoMedeirosRS** [godotengine/godot#61620]
### Godot version

3.5 RC3

### System information

Android with Gles 3 render.

### Issue description

When a build export project from 3.4.4 everthings works fine, when i export my project from 3.5 RC3, i get a black screen after loading.

### Steps to reproduce

1) Add spatial node.
2) Add a camera.
3) Export to android (using Gles 3).
4) Try to run it.

### Minimal reproduction project

[TesteAndroid.zip](https://github.com/godotengine/godot/files/8820048/TesteAndroid.zip)

**Comment by Calinou** [comment]
@RodrigoMedeirosRS Which Android device model (and Android version) did you test this on?

**Comment by RodrigoMedeirosRS** [comment]
@Calinou i have remade all export tests using 3.5 RC3 into a Redmi Note 5 (Android 9) and into Samsung S6 Light, the build have worked into all scenarios. I think I must have been using the wrong export template yesterday (RC2 with the RC3 Editor), sorry about the mistake.
