### ISSUE TITLE
Shapekeys: when changing several shapekey values the character material becomes incorrect

### ISSUE THREAD

**Issue by WuotanStudios** [godotengine/godot#61627]
### Godot version

4.0.alpha7.official[3e9ead05f]

### System information

Windows, Vulkan API 1.2.0, Intel NUC Canyon, AMD Radeon RX Vega M GL

### Issue description

When several shapekey values are changed on the character (in the editor), the material on the character is temporarily altered. e.g. the eyes turn black, there are light / gray areas on the face, etc..

see my tweet: https://twitter.com/WuotanStudios/status/1532278581883117568?s=20&t=QVkD-cl4Rs-rpb6cIdOivQ
and my screenshot:
![Screenshot](https://user-images.githubusercontent.com/101058770/171601433-11731827-d053-41da-ac97-76dd6d1f1fdf.png)
 

### Steps to reproduce

use the attached file in a new project.
go to the character shapekeys and change several (random) shapekeys to max values (1).
When i am testing it, 1 up to 2 shapekeys can be changed without any troubles.
From 3+ the issues start to appear.

### Minimal reproduction project

because the character file has several hundred MB (even as zip file) i have uploaded it on my google drive.

Here is the download link: 
https://drive.google.com/file/d/1x5np6_RtyOrbuFBtMju3nW8RKO8ZIYu1/view?usp=sharing

**Comment by ModularNucleus** [comment]
Likely related to #55812 and fixed in #61217 .

**Comment by WuotanStudios** [comment]
Great! You guys are fast :-D
