### ISSUE TITLE
Typehints on inner classes don't recognize the class if returned by a co-routine (await)

### ISSUE THREAD

**Issue by dsnopek** [godotengine/godot#61635]
### Godot version

v4.0.alpha9.official.fc18891db

### System information

Linux, Vulkan, 1070M

### Issue description

I've been working on porting the Nakama client to Godot 4. In Godot 3, it uses this pattern where there's a bunch of "namespaces" (*.gd scripts with lots of inner classes - they are automatically generated from Swagger definitions).

While working on this, I discovered that typehints don't recognize the class if returned by a co-routine (await). I get an error like:

```
Trying to assign value of type '' to a variable of type 'MyNamespace.gd'.
```

This may be related to issue #61567

### Steps to reproduce

I've included a minimal reproduction project below, but here is the key code (from the Main.gd in the project) to illustrate the problem:

```gdscript
extends Node2D

func _ready():
	# This works fine!
	var n: MyClass = await create_normal_class_async("Normal")
	print (n)
	
	# And this does too...
	var i: MyNamespace.InnerClass1 = create_inner_class("Inner")
	print (i)
	
	# But this gets the runtime error :-(
	var ia: MyNamespace.InnerClass1 = await create_inner_class_async("Inner Async")
	print (ia)

func create_normal_class_async(p_value: String) -> MyClass:
	await get_tree().process_frame
	return MyClass.new(p_value)

func create_inner_class(p_value: String) -> MyNamespace.InnerClass1:
	return MyNamespace.InnerClass1.new(p_value)

func create_inner_class_async(p_value: String) -> MyNamespace.InnerClass1:
	await get_tree().process_frame
	return MyNamespace.InnerClass1.new(p_value)
```

### Minimal reproduction project

[godot-4-await-typehint-bug.zip](https://github.com/godotengine/godot/files/8825145/godot-4-await-typehint-bug.zip)

**Comment by vnen** [comment]
It might be the same as #61567, can't reproduce on current master.
