### ISSUE TITLE
In AudioStreamPlayer when you change "Start Offset" or "End Offset" inspector, AudioClips Track does not show the key correctly anymore 

### ISSUE THREAD

**Issue by tugbayatilla** [godotengine/godot#61630]
### Godot version

3.4.4 stable

### System information

MacBook Pro (16-inch, 2021), Apple M1 Pro, Monterey

### Issue description

https://user-images.githubusercontent.com/16705175/171620356-fddca795-c51b-4bb9-b2fd-2b83191174a8.mov

### Steps to reproduce

Follow the instructions at page https://docs.godotengine.org/en/stable/tutorials/animation/introduction.html

1. Add a [AudioStreamPlayer](https://docs.godotengine.org/en/stable/classes/class_audiostreamplayer.html#class-audiostreamplayer) to the Scene Tree and setup a stream using an audio file you put in your project.

2. Click on "Add track" (Add track) on the animation panel's track controls.
3. AudioPlayback Track
4. select an audio
5. insert keys
6. select key and try to change Start Offset or End Offset from the inspector
7. the key span, will collapse.
8.

**Comment by kleonc** [comment]
> ### Minimal reproduction project
> 
> _No response_

Please provide MRP for easier troubleshooting.

**Comment by kleonc** [comment]
Not a bug, the in-inspector sliders have just big limits set and hence a slight drag changes the offset much, making the offset be greater than the audio clip length (and thus cutting the whole clip off).
