### ISSUE TITLE
TileMap.request_move command not available in C#

### ISSUE THREAD

**Issue by MaiconMichel** [godotengine/godot#61634]
### Godot version

3.5

### System information

Windows 11

### Issue description

TileMap.request_move command not available in C#

### Steps to reproduce

TileMap.request_move write in C#

**Comment by kleonc** [comment]
There's no `request_move` method/property in the whole Godot code base (including `TileMap`). So not sure what this report is supposed to be about.

In case of any doubts please reach for help in other [Community channels](https://godotengine.org/community) (like Q&A / Discord / Reddit etc.) first. This is a bug tracker, not a place to ask for help.
