### ISSUE TITLE
Is GLU a required dependency?

### ISSUE THREAD

**Issue by sambler** [godotengine/godot#6164]
**Operating system or device - Godot version:**
godot master (2.1)

**Issue description** (what happened, and what was expected):
Within [drivers/gl_context/glew.h](https://github.com/godotengine/godot/blob/master/drivers/gl_context/GL/glew.h#L1186) glu.h is included. Godot is not linked to libGLU and removing `#include<GL/glu.h>` does not break the build.

Is glu.h/libGLU required (or planned) to build godot properly or can this dependency be removed?

**Comment by Sslaxx** [comment]
Linux/Mac OS/Unix only?

**Comment by vnen** [comment]
AFAIK this `glew.h` is external code and copied as it is. Not sure if it's worth adding custom patches to it just to trim it down, especially if does not make any difference.

**Comment by sambler** [comment]
I get that just copying an external file is easy and the extra include makes little difference to the build of godot and little difference to the user installing it.

What I am looking at is the packaging systems. Having 3 or 4 supported system versions built to run on x86, amd64, ppc, ppc64, arm, aarm64, sparc64 soon adds up. Each build of godot needs to install libGLU so it will compile and get packaged, not having to install files that aren't needed helps reduce the load of the package building servers when most are a limited resource run by non-profits. Then there is dependency rebuilds - a minor patch to libGLU means godot needs to be rebuilt when it doesn't make a difference to the final binary.

**Comment by sambler** [comment]
Actually for anyone coming across this - we can use CXXFLAGS+=-DGLEW_NO_GLU to disable the inclusion of glu.h and remove the dependency.

Maybe this could be added in SCsub to have it always disabled?

**Comment by akien-mga** [comment]
Fixed in the master branch, GLEW was replaced by GLAD.
