### ISSUE TITLE
`%` uses NodePath color even when not part of NodePath

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#61646]
### Godot version

1baee21

### System information

Windows 10 x64

### Issue description

Minor regression from #61440 (I assume at least)
![image](https://user-images.githubusercontent.com/2223172/171751143-33fc574c-8ae2-4281-87fa-67fd42fda2ce.png)
It shouldn't be green.

### Steps to reproduce

1. Use `%` as modulo operator
2. Notice it's colored like NodePath instead of operator

**Comment by MewPurPur** [comment]
%'s coloring behavior is consistent with that of $ now. So I honestly think `%Node` is just not fit as a replacement for `get_node("%Node")` and it should require a fuller $%

**Comment by KoBeWi** [comment]
Nah, `%Node` is fine, just `%` shouldn't use NodePath coloring when used alone.

**Comment by MewPurPur** [comment]
Not just standalone - things like `19%3` and `"I am %s the Espeon"%"Mew Pur Pur" also trigger the color change. I suppose it requires knowledge of whether its current context is as a binary or a unary operator
