### ISSUE TITLE
Tilemap really slow with few tiles

### ISSUE THREAD

**Issue by pixel-boy** [godotengine/godot#61645]
### Godot version

4.0 alpha 9

### System information

Windows 10, Vulkan, NVIDIA GeForce GTX 1060

### Issue description

The tilemap editor becomes very slow when a certain number of tiles are added (only on alpha 9) someone suggested it could be changes to the HashMap.

Videos to show the difference between the alpha 8 and 9 version:

Alpha 9 ( Slow ) 

https://user-images.githubusercontent.com/16109919/171746421-452c019b-95cf-4757-8dec-7998d736c775.mp4

Alpha 8

https://user-images.githubusercontent.com/16109919/171746493-125f8b91-b4d9-4fcf-bf6b-0a1dab73f6a4.mp4

### Steps to reproduce

Just fill a Tilemap node with a certain number of tiles

### Minimal reproduction project

[BugTilemapAlpha9.zip](https://github.com/godotengine/godot/files/8828085/BugTilemapAlpha9.zip)

**Comment by Calinou** [comment]
@pixel-boy Remember that for GitHub video previews to work, you need to have a blank line before *and* after the video URL. I edited your post accordingly, but remember to do this in the future :slightly_smiling_face:

**Comment by Dan-Gamin** [comment]
I also noticed this. I thought my computer was just slow lmao

**Comment by Geometror** [comment]
Finally found the underlying issue that's causing this regression: The poor default hashing function for Vector2i (and likely some other types). I just switched it with a few other hash functions (still testing which works best, currently using a murmur3 based one), but it's already as fast as it was before (with RBMap). I will open a PR later.

**Comment by akien-mga** [comment]
Fixed by #61934.
