### ISSUE TITLE
Trying to return a value when the return type is void is silently ignored

### ISSUE THREAD

**Issue by miv391** [godotengine/godot#61657]
### Godot version

v4.0.alpha9.official [fc18891db]

### System information

Windows 10, OpenGL ES 3.0 Renderer: GeForce GTX 1060 6GB/PCIe/SSE2

### Issue description

If a function has untyped parameters and function's return type is `void`, trying to return a value is silently ignored without any error or warning messages.

However, if the function has typed parameters or no parameters at all, then an error message is given as expected. The following functions give an error `Parser Error: Cannot return value of type "int" because the function return type is "null".`

```gdscript
# gives an error message as expected
func fully_typed(i: int) -> void:
	return i + 1

# gives an error message as expected
func fully_typed_without_parameters() -> void:
	return 1
```

This bug report is only about the missing error message. But in my opinion there is also a bigger issue which can been seen from the error message which says that the return type is `null`, although it actually is `void`. I have made a [proposal](https://github.com/godotengine/godot-proposals/discussions/4045) about fixing the `void`/`null` types.

### Steps to reproduce

```gdscript
# no error message
func only_return_value_typed(i) -> void:
	return i + 1
```

**Comment by Calinou** [comment]
> But in my opinion there is also a bigger issue which can been seen from the error message which says that the return type is null, although it actually is void. I have made a https://github.com/godotengine/godot-proposals/discussions/4045 about fixing the void/null types.

I think we can add a special case for the void return error message:

> `Parser Error: Functions with return type "void" cannot return any value.

**Comment by miv391** [comment]
> I think we can add a special case for the void return error message:

That would be an improvement. But still the big issue is that a function with return type `void` returns `null`, which definitely is not "nothing". For example this code:

```gdscript
func void_return_type(i) -> void:
	pass
		
func test():
	print([1,2,3].map(void_return_type))
```

outputs `[null, null, null]`. In my opinion trying to use void function with `Array.map` should be an error. But this is not just an error message issue, `void` should just be totally unassignable to anything.

**Comment by dalexeev** [comment]
I also wanted to report this issue.

3.x|4.0-dev
-|-
![](https://user-images.githubusercontent.com/47700418/208362148-aa8fbbd1-a226-453e-b05d-fb2d5c88ed91.png)|![](https://user-images.githubusercontent.com/47700418/208362066-5e62ae89-a49e-4b61-bf6a-ef787036f77c.png)
![](https://user-images.githubusercontent.com/47700418/208360914-97e5fb2f-8f14-4703-88c3-3022913aeee4.png)|![](https://user-images.githubusercontent.com/47700418/208361006-944c6a57-26fe-488f-89cd-052679d7c753.png)
![](https://user-images.githubusercontent.com/47700418/208361301-c151a060-024e-4acb-8caa-b229cfd8e079.png)|![](https://user-images.githubusercontent.com/47700418/208361219-e8714cd3-727d-4ce0-a720-2a5698ec680c.png)
![](https://user-images.githubusercontent.com/47700418/208361465-e7d5df60-eb16-496d-a39a-697234ea0100.png)|![](https://user-images.githubusercontent.com/47700418/208361525-b3b21fd0-47fc-480e-84aa-2596cd7351be.png)
![](https://user-images.githubusercontent.com/47700418/208361777-10c5f31f-45ad-4198-8600-ad1304a3cce7.png)|![](https://user-images.githubusercontent.com/47700418/208361855-b9f867ba-f158-4ec3-9537-ce0ed78d46b3.png)

By the way, the error message should also be fixed.

3.x:

![](https://user-images.githubusercontent.com/47700418/208362436-2579a43b-7a5c-4b5d-af69-a765b3ab9fe8.png)

4.0-dev:

![](https://user-images.githubusercontent.com/47700418/208362547-237f937b-64be-4274-9491-a2037fa7c745.png)
