### ISSUE TITLE
3.4.4 Shape keys lead to incorrect shading GLES3

### ISSUE THREAD

**Issue by PerplexedPeach** [godotengine/godot#61685]
### Godot version

3.4.4.stable

### System information

Windows 10, GLES3, NVIDIA RTX 2060, driver 512.95

### Issue description

Symptoms seem similar to #58516 and #61627 where shading becomes incorrect due to the activation of shape keys.
Inside blender, the model does not change shading in unrelated regions when changing facial shape keys.
Imported via glb (and reimported with various settings that I will explain later), activating shape keys cumulatively changes certain regions on the body in a consistent and progressive way. Here is a video demonstrating this, with sliders set up to control shape keys, and a periodic blink that changes a single blink shape key from 0 to 1 and down.

https://user-images.githubusercontent.com/48222967/171980554-5cc2f1fc-dcc7-495f-9067-7747f8370a28.mp4

Note that the most of the shape keys are for the face only and should not affect the body.

The import part of the shading nodes for the body:
![image](https://user-images.githubusercontent.com/48222967/171982516-4194556c-7ff9-40b6-84c5-a353f107f492.png)

### Steps to reproduce

I could not reproduce this on simpler models such as a cube or the suzanne monkey textured with base color but no normal map. I suspect it has something to do with normal maps.

### Minimal reproduction project

The whole project is close to 1GB so I will refrain from posting it unless necessary.

**Comment by PerplexedPeach** [comment]
More details: at exactly when the sum of blend shape weights is 1, there are grey polygonal patches, mostly along the z axis as shown below:
![image](https://user-images.githubusercontent.com/48222967/172010361-0ff2b6cb-fd23-4783-a935-3278dd02ca7c.png)
When the total blend shape weights go below or above 1, the grey polygons go away (presumable incremental distortion of normals still occur).

Will investigate shaders and the imported materials.

**Comment by PerplexedPeach** [comment]
Turning off normals on the head and body removes the grey polygons, but still leads to progressive darkening shading with more blend shapes
![image](https://user-images.githubusercontent.com/48222967/172021145-f1889b31-0e14-479c-b7a6-c1d99db5d61f.png)

**Comment by PerplexedPeach** [comment]
**Managed to solve this issue by checking Tangents when choosing to export from blender to .glb**

![image](https://user-images.githubusercontent.com/48222967/172026147-01077159-1613-4146-8c39-8deb51645b4f.png)

Discussed the problem on discord and the conclusion seems to be a problem from Godot being allowed to compute tangents on blend shapes, and it doing so incorrectly. Note that the grey rectangles occurred near the center axis when the tangent could equally point left or right. If it defines it differently than how blender does it, it might lead to artifacts similar to what I've observed.

Is it possible to suppress generation of tangents in Godot? If there are no good sources of tangents, simply warn the users that they should export with tangents? This kind of issue is not that trivial to track down.

**Comment by clayjohn** [comment]
I'm not super familiar with the import code for blendshapes, but it may be difficult to warn the user about missing tangents at import time as the importer has no knowledge about how the mesh is going to be used. 

If the underlying issue is tangents being calculated incorrectly, then I would think the solution would be to correctly calculate tangents rather than to disable generating tangents altogether.

**Comment by PerplexedPeach** [comment]
Correctly calculating tangents may or may not take a lot of work to track down why they're incorrect in the first place. If the band-aid solution of warning about missing tangents is also non-trivial to implement, then it might be better to fix computing tangents. I'd prefer a warning, or even an error where it crashes because you're missing tangents (but let the users know about it).

**Comment by PerplexedPeach** [comment]
Seems like this issue is not entirely resolved by exporting with tangents. On some blend shapes it still results in distorted tangents 
![image](https://user-images.githubusercontent.com/48222967/172500579-537ec52d-8dc1-422e-8fab-6d9f1dd24e45.png)

**Comment by PerplexedPeach** [comment]
Unfortunately I can no longer replicate my fix from before. Even exporting with tangents (and shape key tangents) still results in distorted tangents 
![image](https://user-images.githubusercontent.com/48222967/172513318-2341d544-4a29-4070-9f9b-6e033c40f2e6.png)

**Comment by clayjohn** [comment]
Hmmm, in that case, it may be an issue of blending blendshapes, or it could be an issue with the blendshapes themselves. More investigation is needed in any case.

**Comment by PerplexedPeach** [comment]
Yes, will investigate the source hopefully sometime soon. Downloaded godot's source and have it loaded up in CLion, but am busy with the current project (have a version of the body mesh that works mostly) and actual work...

**Comment by PerplexedPeach** [comment]
Ok I solved the issue, which seemed to be caused by exporting non-deforming bones. By default, glTF exports non-deforming bones for some reason. Exporting only deforming bones resolved this issue 👍 (see below where it's located for Blender 3.2's glTF plugin)
![image](https://user-images.githubusercontent.com/48222967/172979533-7ebb4ea2-87d9-4023-84a0-295e7d87d2ee.png)

**Comment by Calinou** [comment]
Reopening, as this should be documented (and fixed on either Godot or the Blender exporter's side).

**Comment by Iakobs** [comment]
Hi, sorry to comment on this old issue, but this is still happening in Godot 4.3 in the Compatibility renderer, did this got fixed?
