### ISSUE TITLE
"Node not found" message for deleted children when reloading a scene

### ISSUE THREAD

**Issue by austin-benoit** [godotengine/godot#61683]
### Godot version

v4.0.alpha.custom_build [1baee2189]

### System information

Linux Mint 20.3, kernel version 5.15.0-33-generic

### Issue description

After deleting multiple children in my scene, whenever I switch tabs back to that scene, I will get a warning for each child telling me that the node could not be found.

![godotbug](https://user-images.githubusercontent.com/7575664/171980501-d468cede-21dd-4c4f-828e-3017917bf64d.png)

```
  Node not found: "Tile2" (relative to "/root/@@16215/@@656/@@657/@@666/@@668/@@674/@@680/@@681/@@682/@@704/@@705/@@745/@@746/@@9069/@@8890/@@8891/@@8892/@@8893/@@8894/@@8895/MainScene").
  Node not found: "Tile3" (relative to "/root/@@16215/@@656/@@657/@@666/@@668/@@674/@@680/@@681/@@682/@@704/@@705/@@745/@@746/@@9069/@@8890/@@8891/@@8892/@@8893/@@8894/@@8895/MainScene").
  Node not found: "Tile4" (relative to "/root/@@16215/@@656/@@657/@@666/@@668/@@674/@@680/@@681/@@682/@@704/@@705/@@745/@@746/@@9069/@@8890/@@8891/@@8892/@@8893/@@8894/@@8895/MainScene").
  Node not found: "Tile" (relative to "/root/@@16215/@@656/@@657/@@666/@@668/@@674/@@680/@@681/@@682/@@704/@@705/@@745/@@746/@@9069/@@8890/@@8891/@@8892/@@8893/@@8894/@@8895/MainScene").
```

### Steps to reproduce

1. Create a new project.
2. Create a main scene.
3. Create a scene for an object, in this case "Tile."
4. Bring many (I do 4) Tile instances into the main scene.
5. Save the scene and close the editor.
6. Reopen the editor.
7. Select all 4 tiles and delete them at one time.
8. Change tabs to a different scene (ex: the Player scene)
9. Change tabs back to the main scene and see the warnings. I've tested and for me they persist even after saving and reopening the engine again.

### Minimal reproduction project

Steps 1-5 were taken to produce this project. Start at step 6 to produce the bug
[bugdemo.zip](https://github.com/godotengine/godot/files/8836986/bugdemo.zip)

**Comment by GeoTech-Alex** [comment]
I have been unable to replicate this issue on 1f4f73f860 using Windows 11 with the mrp provided.

**Comment by vnen** [comment]
I could reproduce in current master following the steps. It seems related to the multi-select with nodes.

**Comment by SaracenOne** [comment]
Working on a fix. It seems to be down the EditorSelectionHistory cleanup_history method not accounting for multi-select nodes.
