### ISSUE TITLE
Raycast 3d

### ISSUE THREAD

**Issue by kimbunner** [godotengine/godot#61688]
### Godot version

v3.5 RC 3

### System information

Windows 10, Nvidia Geforce gtx 560

### Issue description

get_name not working

Here Is The Code I Use
```
extends RayCast

func _physics_process(delta):
	if Input.is_action_just_pressed("interact"):
		if is_colliding():
			var obj = get_collider()
			print(obj.get_name())
```

### Steps to reproduce

I Tried Printing The Raycast Collider But It DInt Worked

**Comment by Zireael07** [comment]
Collider is the physics body. Most likely you want their parent.

Not a bug and shouldn't be reported here but asked on the forums.

**Comment by kimbunner** [comment]
K Try My Best Not To Post Again Here
