### ISSUE TITLE
Ability to modify Animation player in inherited scenes.

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#6169]
**Operating system or device - Godot version:**

**Issue description** (what happened, and what was expected):
It's little limited that there is no way to modify animations in inherited scenes. Especially that scene inheritance is often used when importing models from blender. We discuss this with reduzio on irc and here a solution proposed by him:

 _reduz_: As I mentioned before, the easy way would be, in the new animation dialog, an option to make it an "extension" animation, where you can choose an existing one. The new one would have the tracks of the old animation in non-editable fashion, and allow you to add new ones to it which you can edit
 _reduz_:  both old and new will remain there, but you will likely use the new one
 _reduz_: if the base one is modified, the new one simply appends it's tracks.
 _reduz_: this could be used in other situations too, i found often that I want to make two animations similar but with some modification (ie, for two enemies, even in 2D)

**But don't think this would solve all the problems, take a look at usecase below.**

**Comment by kubecz3k** [comment]
Totally unsure when reduzio will have time for this, but for now will leave 2.2 milestone.

**Comment by kubecz3k** [comment]
It would be good if we could also _**remove**_ tracks in inherited animation. My usercase: I have 3d animation in blender, some of the bones in blender are not touched in this animation. Despite this when importing to Godot all the bones are baked into animation. Each time when reimporting model I need to manually go into animations and remove redundant tracks or else my `AnimationTreePlayer` node wont blend animations correctly. 
It's very tiresome, and it's easy to forget about this and leave the model with a bug. (not mentioning the fact every member of a team need to know about this and know how to fix)

**Comment by kubecz3k** [comment]
It's not possible any longer to modify animation player that are inside dae scenes. So in 3.0 it's not possible at all to, for example to use `call function` track in imported models.

**Comment by reduz** [comment]
I think this worked, but you have to import animations as external. This
will merge them when you re-import. For built-in animations it won't work.

**Comment by kubecz3k** [comment]
Thanks for the tip, will make use of it for sure!

**Comment by RoyBerube** [comment]
I've run into this issue as well while testing Godot 3. The loop setting is not saved for animations imported from a DAE file unless you use some trickery.

A work-around is to rename each track and then it will be saved into the tscn file. The animation track name has to be different than the one imported from the DAE file or it will not save any information.

**Comment by CowThing** [comment]
I don't think the external animations are working. I tried having animation import as external and checked the option to keep custom tracks. But editing the animation still doesn't save the changes. The solutions I use is to select the AnimationPlayer and use Make Sub-Resources Unique in the inherited model scene.

**Comment by kubecz3k** [comment]
@CowThing you still need to save animation resource manually, saving the scene is not enough.

**Comment by reduz** [comment]
@kubecz3k it should save the animations when you save the scene, if its not doing it i think its a bug

**Comment by kubecz3k** [comment]
@reduz actually when I think about this right now, I think I mistaken this issue with https://github.com/godotengine/godot/issues/12801 So not sure if my previous comment is valid.

**Comment by Cobradabest** [comment]
I'm having this issue with function calls. I create one in an animation from an instanced scene, save the scene, reopen it, it's gone...

**Comment by kubecz3k** [comment]
@Cobradabest Ensure you are importing animations to external files. Then explicitly open the file in animation player before modyfications, and after you do your modifications ensure its saved as external file by overriding the animation file (with save icon inside AnimationPlayer).

**Comment by akien-mga** [comment]
`AnimationTreePlayer` is deprecated in Godot 3.1 and will be removed in Godot 3.2. It is replaced by `AnimationTree`, which was written from scratch and likely fixes/deprecates this issue.

If the issue is still relevant in some form with `AnimationTree` in Godot 3.1, please open a new issue about it (potentially linking this one if there is relevant discussion to keep track of).
