### ISSUE TITLE
[4.0a9] inconsistent sRGB in canvas_item shaders

### ISSUE THREAD

**Issue by DatBrute** [godotengine/godot#61697]
### Godot version

4.0 alpha 9 (d9daf3869)

### System information

Windows 11, GLES3, NVIDIA GeForce RTX 3050

### Issue description

Comparing a uniform to COLOR in 4.0 gives inconsistent results for unknown reasons. Likely having to do with sRGB/linear conversion.

### Steps to reproduce

Provided is a working (non-bugged) minimal reproduction in v3.5, and a non-working (bugged) minimal reproduction in v4.0.

Open srgb_3.5 in Godot v3.5-rc1. Open srgb_4.0a9 in Godot v4.0 alpha 9. Note the difference in color: srgb_3.5 has colored the correct area, and srgb_4.0a9 has colored the wrong area.

Then in srgb_4.0a9, click on Sprite->Inspector->Material->Shader->Shader Param, and set the sensitivity to 0.01, which is the same as srgb_3.5's sensitivity. Note how the shader now does nothing.

### Minimal reproduction project

[srgb_3.5.zip](https://github.com/godotengine/godot/files/8838407/srgb_3.5.zip)
[srgb_4.0a9.zip](https://github.com/godotengine/godot/files/8838416/srgb_4.0a9.zip)

**Comment by Chaosus** [comment]
probably related to https://github.com/godotengine/godot/pull/55029, cc @clayjohn

**Comment by clayjohn** [comment]
Before 4.0 releases we will need to do a comprehensive audit of where we are converting between linear and sRGB and what color space various options take place in.
