### ISSUE TITLE
Dropped VS node goes to the visual scripting board's center instead of mouse cursor position

### ISSUE THREAD

**Issue by agameraaron** [godotengine/godot#6170]
Linux Mint 64bit MATE 17.3 
Godot version: 2.2 alpha (Aug 14th) 3db36684b183adbec93cce9fe91182186e389e06

When I drag from the "Available Nodes:" section and release my mouse, the visual node appears under my cursor, but as soon as I move it, it goes to the center of the board. This is unexpected behavior as it should follow directly under the cursor instead of going off screen as soon as it's movable.

Video: https://www.youtube.com/watch?v=jUHMtXavsmA

**Comment by Hinsbart** [comment]
closing, seems fixed.

**Comment by agameraaron** [comment]
Thanks!
