### ISSUE TITLE
Glow Mix blend mode doesn't work when FXAA is enabled

### ISSUE THREAD

**Issue by BraqueDown** [godotengine/godot#61717]
### Godot version

v4.0.alpha.custom_build [0df0a07ab]

### System information

Windows 10, Vulkan Clustered, RTX 3070 (512.15)

### Issue description

When FXAA is turned on, the Glow effect will not render at all when using the Mix blend mode. This also occurs with the Vulkan Mobile backend.

### Mix 0.5, FXAA Disabled
![Glow Mix FXAA Disabled](https://user-images.githubusercontent.com/43602802/172053912-820f8b48-0c60-4e13-a3db-4972f34ae541.png)

### Mix 0.5, FXAA Enabled
![Glow Mix FXAA Enabled](https://user-images.githubusercontent.com/43602802/172053970-ee8edc8a-4096-4681-bfa7-676f56c45fd2.png)

### Steps to reproduce

1. Create a new project, then a new scene.
2. Add meshes and lighting to support the glow effect.
3. Create a WorldEnvironment node, turn on Glow, and set Blend Mode to Mix.
4. Set `rendering/anti_aliasing/quality/screen_space_aa` in Project Settings to FXAA.

### Minimal reproduction project

[Bloom Mix Broken.zip](https://github.com/godotengine/godot/files/8840095/Bloom.Mix.Broken.zip)

**Comment by Calinou** [comment]
Glow is done *before* FXAA if the glow blend mode is Mix: https://github.com/godotengine/godot/blob/126e4d0a5b182a2eea4e49e21344e376acdbba8c/servers/rendering/renderer_rd/shaders/effects/tonemap.glsl#L451-L457

**Comment by clayjohn** [comment]
It looks like glow is done in linear space when using the Mix mode. FXAA takes a bunch of samples and blends between them trying to smooth outliers. Because the central sample (the only one that gets glow applied) will naturally differ, it is getting smoothed out. 

My guess is that we just need to swap the order of mix glow and FXAA and it should work fine. I.e. calculate FXAA before applying glow. Someone will need to check that doing so doesn't break anything though.

**Comment by clayjohn** [comment]
> But should that be completely canceling out the darkening effect of mix mode?

I'm sorry, I don't know what you mean.

**Comment by BraqueDown** [comment]
Mix mode blends the glow effect with the base image, rather than compositing it on top like Add, Screen, or Softlight. The higher the mix factor is, the more glow, and the less of the base image is visible.

If your mix glow has only localized highlights (high threshold value), then the base image will be mixed with black, making the image darker relative to the glow.


### 0.7 Mix
![image](https://user-images.githubusercontent.com/43602802/173275673-1b41c5ed-4e7c-4c28-8ce0-811a31fc3865.png)

### 0.9 Mix
![image](https://user-images.githubusercontent.com/43602802/173275727-39f4de5c-c174-4b20-8f1c-52b81d58e538.png)

### 1.0 Mix (All Glow, No Base)
![image](https://user-images.githubusercontent.com/43602802/173275799-8effc5fc-3092-455f-a584-a147ef944e4a.png)


Correct me if I'm wrong, but from what I read from you, it sounds like FXAA could dim the actual glow effect, but the darkening should still happen, but no mixing is happening at all.

### 1.0 Mix (FXAA ON)
![image](https://user-images.githubusercontent.com/43602802/173276307-93588d39-b2d2-4d31-ad38-56db14228ce2.png)

**Comment by BraqueDown** [comment]
>...but when FXAA reads from the other pixels, they do not have glow applied (because they are reading from the full screen texture)

Ah! That makes a lot more sense. So it sounds like the solution is indeed to perform FXAA first, like the other blend modes.
You mentioned that Mix glow is performed in linear space; is that why FXAA is performed second in this case?

**Comment by clayjohn** [comment]
@BraqueDown I don't know why FXAA was placed after it, but it's the reason they both take place before tonemapping and conversion to sRGB.
