### ISSUE TITLE
Property tooltips are cut-off on Linux (DisplayServer regression)

### ISSUE THREAD

**Issue by mordae** [godotengine/godot#61712]
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

v4.0.alpha9.official [fc18891db]

### System information

Fedora 35, Vulkan, RX Vega 64

### Issue description

Property tool tips are cut-off. It seems as if the buffer is too short.
The tool tip window itself is sized properly and different for every property as it should be.

![tooltips-cut-off](https://user-images.githubusercontent.com/666693/172040617-20bba952-8c8b-46b6-8d7e-3b37d889adae.png)

### Steps to reproduce

1. Open new project.
2. Open project settings.
3. Hover on property.

*Bugsquad edit (keywords for easier searching): cut, clip, cutoff*

**Comment by mordae** [comment]
I forgot to add, this is with GNOME at Xorg. Wayland disabled.

**Comment by jgillich** [comment]
Same here, issue did not exist in alpha 8.

Fedora Silverblue 36, Ryzen 2400G, X11/GNOME

**Comment by RechieKho** [comment]
For me (v4.0.alpha.custom_build [0df0a07ab]), it works well, no such issue.

Debian, X11/GNOME

**Comment by Mr-L-oof** [comment]
I use wayland with swaywm and I've been encountering this issue.

**Comment by Calinou** [comment]
> Maybe @Calinou knows how this is supposed to work/knows who would know?

I haven't worked much on the GUI system, maybe @bruvzg or @KoBeWi will know a better solution than me.

**Comment by KoBeWi** [comment]
Can't reproduce on Windows. All reports so far pretty much confirm this only exists on Linux.

**Comment by xix-xeaon** [comment]
Confirmed X11/KDE. Also happens with the properties in the inspector.

**Comment by blipk** [comment]
Confirm that this is still persistent in v4.0.alpha14 on Gnome Wayland

**Comment by akien-mga** [comment]
See also duplicate #62496 for some details. Notably:

https://github.com/godotengine/godot/issues/62496#issuecomment-1172365241

> I can reproduce it on Mageia 9, it's a regression introduced between 4.0 alpha 8 (good) and alpha 9 (bad).
> A similar issue existed in earlier alphas and was fixed a few months ago, it seems something broke that fix again.

https://github.com/godotengine/godot/issues/62496#issuecomment-1198553018

> The issue seems to happen only with multiple window support enabled, because otherwise it doesn't happen, as can be seen below.

**Comment by bruvzg** [comment]
> Seems like my hunch in https://github.com/godotengine/godot/issues/62496#issuecomment-1172368856 was correct, I finally took the time to bisect between 4.0 alpha 8 and alpha 9, and I landed on https://github.com/godotengine/godot/commit/cfcdfc38e275d8766e69621a001422030e515173.

OK, I have checked this change again, tooltips do not use threaded mode, but I think I see what might be causing it - #64783. I'll test it tomorrow, since it's not reproducible on macOS and Windows and there might be underlying bug in the X11 window handling as well.
