### ISSUE TITLE
Zooming using mouse wheel in 2D editor is inverted

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#61716]
### Godot version

25908c17c9a8665f81e5f55e0853212036f05b77

### System information

Windows 11

### Issue description

Zooming using mouse wheel is inverted in 2D editor (while it's correct in 3D and editor interface).

### Steps to reproduce

Open 2D editor and try to scroll.

**Comment by Chaosus** [comment]
I think It was introduced by https://github.com/godotengine/godot/pull/61690 cc @againey

**Comment by againey** [comment]
It sure was, sorry!  I'll fix.

**Comment by Calinou** [comment]
Fixed by https://github.com/godotengine/godot/pull/61719
