### ISSUE TITLE
Godot 4 alpha 9 regression: hint_color shows a shader compilation error.

### ISSUE THREAD

**Issue by jcarlosrc** [godotengine/godot#61720]
### Godot version

4.0 Alpha 9

### System information

Windows 10

### Issue description

"hint_color" keyword is shown as an error in spatial shaders.

### Steps to reproduce

Make a spatial shader using the hint_color keyword. E.g, "uniform vec4 albedo_color : hint_color;"

**Comment by Calinou** [comment]
`hint_color` is now `source_color`.
