### ISSUE TITLE
Vehicle and wheel import hints do not work in v4

### ISSUE THREAD

**Issue by jgillich** [godotengine/godot#61733]
### Godot version

alpha 9

### System information

Fedora Silverblue 36, Ryzen 2400G

### Issue description

Importing vehicles and wheels using `-vehicle`/`-wheel` suffixes in Blender files does not work anymore in v4. The feature is still documented in the latest docs: https://docs.godotengine.org/en/latest/tutorials/assets_pipeline/importing_scenes.html#create-a-vehiclebody-vehicle

Not sure if it has been removed intentionally, if yes the docs need to be updated. But I'd really like to see this feature returned, especially since there is another bug with inherited scenes not being updated.

Godot 3 vs Godot 4:

![Screenshot from 2022-06-05 10-44-06](https://user-images.githubusercontent.com/347965/172070107-04f9b508-430f-4073-baef-4b4b974ae1e0.png)

### Steps to reproduce

1. Create meshes in blender with -vehicle and -wheel suffixes
2. Import the file into Godot

**Comment by fire** [comment]
I thought were still working hm.

Are you able to look into this?

**Comment by fire** [comment]
The scanner is here.

https://github.com/godotengine/godot/blob/master/editor/import/resource_importer_scene.cpp#L579

**Comment by jgillich** [comment]
Found it, vehicle/wheel imports were removed in 97a3a662205d598dad195fa72d2dcb2f19c21088 by @reduz 

It seems that there are considerations to deprecate/remove `VehicleBody3D` for 4.0 and I'm assuming that was the reason for dropping the importers. Is there consensus on the future of `VehicleBody3D`?

**Comment by Calinou** [comment]
> It seems that there are considerations to deprecate/remove VehicleBody3D for 4.0 and I'm assuming that was the reason for dropping the importers. Is there consensus on the future of VehicleBody3D?

The plan was originally to remove VehicleBody3D and VehicleWheel3D from core, and reimplement them with GDExtension. However, this is is unlikely to happen by now, so I think both will remain in core.

**Comment by jgillich** [comment]
Cool, I'll try to restore the importers
