### ISSUE TITLE
Vulkan: StandardMaterial3D with any transparency does not cast shadows

### ISSUE THREAD

**Issue by jasonallen** [godotengine/godot#61730]
### Godot version

v4.0.alpha8.official [917fd6574]

### System information

Mac OSX 12.4, M1 Pro

### Issue description

I'm unable to get a material to render a shadow when I set any transparency other than "Disabled":

![image](https://user-images.githubusercontent.com/102696/172068065-8cfecba9-7a1b-4681-b45f-de2af8f6527d.png)

This seems related to https://github.com/godotengine/godot/issues/50344 but that seems fixed.

### Steps to reproduce

1. Create a scene with a directional light and flat terrain that accepts shadows
2. Create a Mesh3D with a quad, give it a StandardMaterial3D and a texture with alpha in it.
3. Position it so you can see the shadow casted on the flat terrain.
4. Now set the material "Transparency" to anything other than "Disabled"

==! The shadow disappears.

### Minimal reproduction project

[shadow_test.zip](https://github.com/godotengine/godot/files/8840681/shadow_test.zip)

**Comment by tinmanjuggernaut** [comment]
On GD4 Alpha13 Win10/64, I can get a shadow using depth prepass mode or alphascissors. Not with Alpha hash or alpha.

![image](https://user-images.githubusercontent.com/632766/181913124-07193554-bd3c-46ed-a99e-017b9fd191fb.png)

**Comment by tinmanjuggernaut** [comment]
Also ProximityFade (part of the transparency pipeline) has no shadow, only self-shadows. No PF on the right. The rock looks weird because of #63675.

![image](https://user-images.githubusercontent.com/632766/182019134-85ccc38e-d309-4745-86db-dccdbeb39a42.png)

**Comment by Calinou** [comment]
> Also ProximityFade (part of the transparency pipeline) has no shadow, only self-shadows.

Alpha blending is used for materials with proximity fade enabled, so this is expected.

**Comment by tinmanjuggernaut** [comment]
@Calinou Can this be added to the gd4 roadmap and material tracker https://github.com/godotengine/godot/issues/56333?

**Comment by Calinou** [comment]
I can't reproduce the original issue anymore on 4.0.alpha13 (Linux, NVIDIA 515.57):

![image](https://user-images.githubusercontent.com/180032/183613888-c649fbb5-b72a-4412-ba99-2336ef7f2a6b.png)

Please continue the discussion about the proximity fade issue in https://github.com/godotengine/godot/issues/63675.

**Comment by wouldntsavezion** [comment]
The other proximity fade issue (#63675) is about z-ordering, and this issue is about shadows on different transparency modes, but this still leaves the fact that proximity fade doesn't have shadows at all, even though it can properly be used to fade with modes that have shadows such as alpha scissor.
