### ISSUE TITLE
Length vector function in Visual Shader Nodes is not distinguishable in their dimension forms

### ISSUE THREAD

**Issue by paddy-exe** [godotengine/godot#61734]
### Godot version

v4.0.alpha.custom_build [3dac7ff87]

### System information

Win10

### Issue description

This is what it looks like in the alpha 9 build and newer:
![image](https://user-images.githubusercontent.com/38077837/172071879-61bab0fd-e2d1-4030-8c94-1aad32152c0e.png)

For better readability it should probably look more like this:
![image](https://user-images.githubusercontent.com/38077837/172072014-bdc90773-3e26-4f88-be47-616b65bd872d.png)

### Steps to reproduce

1. Create MeshInstance
2. Create VisualShader
3. Open "Add Node..." dialog

**Comment by LightningAA** [comment]
This isn't just for length

https://github.com/godotengine/godot/blob/86976daea96898609899fd3f210018070a36eda3/editor/plugins/visual_shader_editor_plugin.cpp#L5454-L5610

**Comment by paddy-exe** [comment]
@LightningAA This doesn't apply to the others because you can see what vectors are for the input in the output icon type. That's not possible for the length function since it always returns a float
