### ISSUE TITLE
Can't save nor instanciate scene

### ISSUE THREAD

**Issue by FaerDerr** [godotengine/godot#61743]
### Godot version

4.0 Alpha 9

### System information

Windows 10, NVIDIA RTX 2060

### Issue description

Might be a duplicated, couldn't find similar error for alpha 9.

Tried to instanciate an ennemy scene, got this error : 
```
E 0:00:00:0700   resolve_class_interface: Parser bug (please report): tried to assign unset node without an identifier.
  <Source C++>   modules/gdscript/gdscript_analyzer.cpp:656 @ resolve_class_interface()
```
![image](https://user-images.githubusercontent.com/20193149/172129000-6f28030a-14ee-46fa-8193-4b65a812fb50.png)

### Steps to reproduce

- Create the ennemy scene
![image](https://user-images.githubusercontent.com/20193149/172129095-93403e41-b44a-4f70-b27d-803940bfc732.png)

- Create a "Ennemy.gd" script. 
![image](https://user-images.githubusercontent.com/20193149/172129271-7dd3d9b4-9978-4ebe-b0e1-bfead39b5e08.png)

- extends ennemy.gd sript in the specific ennemy script
![image](https://user-images.githubusercontent.com/20193149/172129225-541a1b59-b8c0-429b-acc2-7450d30c4bb6.png)

- Launch game, crash, reload, can't save.

### Minimal reproduction project

Current project :
MainScene is linked to F5, so you can just start from there.
Screenemies is the instanciate ennemy
[Robot Survivalist.zip](https://github.com/godotengine/godot/files/8843133/Robot.Survivalist.zip)

**Comment by adamscott** [comment]
This is a difficult issue to debug. This isn't a MRP, as there's a lot of code. And since alpha 9, it's difficult to open the project without detecting scene corruptions.

@FaerDerr Could you upload an updated MRP if the issue still happens?

**Comment by vnen** [comment]
@FaerDerr ping

The error message doesn't even exist anymore, much of this code changed since this was open. If there is no answer I'll assume it's fixed and close this.

**Comment by FaerDerr** [comment]
Yes This can be closed, no error like that on rc2 from what I've been testing this week ! :)
