### ISSUE TITLE
`notify_property_list_changed()` causes backwards/reversed text entry with `String @export var` (`@export_multiline` = OK)

### ISSUE THREAD

**Issue by Error7Studios** [godotengine/godot#61749]
### Godot version

4.0 alpha 9

### System information

Windows 10

### Issue description

Entering text in an `@export var` `String` field with `notify_property_list_changed()` at the end of the setter function causes text to be entered backwards.

The caret moves to the beginning of the string after each typed character.

### Steps to reproduce

https://user-images.githubusercontent.com/60025044/172140913-0bc461d8-53c5-4b21-991e-c83a4abadade.mp4

```gdscript
@tool
extends Node

#@export var: OK
#@export var & notify_property_list_changed(): texts gets entered backwards
#@export_multiline = OK

var _text := ""
#@export_multiline var text := "":
@export var text := "":
	get: return _text
	set(__v):
		_text = __v
		notify_property_list_changed()
```

### Minimal reproduction project

[Backwards Text Bug.zip](https://github.com/godotengine/godot/files/8843605/Backwards.Text.Bug.zip)

**Comment by Error7Studios** [comment]
> Why are you calling notify_property_list_changed()?
I had some issues in a larger project where stuff wasn't refreshing in the editor, so I just started putting that in all my tool setter funcs out of habit.

I can just take it out, I suppose.

**Comment by KoBeWi** [comment]
Yeah you should only use this when a list of properties has changed. Unless you are overriding `_get_property_list()`, you won't need it.

**Comment by Error7Studios** [comment]
Ok, thanks. Got it.
Will mark as closed.
