### ISSUE TITLE
Line Edit text sometimes selects more than intended

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#6174]
**Operating system or device - Godot version:** 2.1 stable

**Issue description** (what happened, and what was expected):
When highlighting text in a **Line Edit node**, sometimes the highlighted text that gets selected selects more than what you are trying to select.

Example:
![](https://i.gyazo.com/6e4120ec8b9763639f1bd0ae3c89c88d.gif)

Font style seems irrelevant, tested it without my custom font still happening.  Doesn't happen for Text Edit nodes though (so if anyone is having a problem with this now, can probably resize a text edit node for a temporary fix)

**Comment by bojidar-bg** [comment]
@Dillybob92 Is HDPI on? Asking because it looks like it selects two times more than what it should.

**Comment by Dillybob92** [comment]
@bojidar-bg Nope and I just went ahead and tested it with it enabled, still same.  Weird how it doesn't happen in a Text Edit node though

**Comment by neikeq** [comment]
Does it happen with click drag and with backwards selection only?

**Comment by Dillybob92** [comment]
@neikeq Yep click drag. And no, happens with forward selection too. (Just tested again):
![](https://i.gyazo.com/2a7fa1e128a1cbef6e492eb82cd7f5d1.gif)

**Comment by bojidar-bg** [comment]
Heh, this time it seems like it selects only half of what it should :smile:

**Comment by akien-mga** [comment]
I can reproduce it too with a simple LineEdit with default font, the selection is very jumpy.
