### ISSUE TITLE
[Godot 4] The editor crashed after opening a scene that has missing dependencies

### ISSUE THREAD

**Issue by njdf18** [godotengine/godot#61748]
### Godot version

v4.0.alpha.mono.custom_build (9b78d6) 

### System information

Windows11, Vulkan, NVIDIA GT 1050 Ti

### Issue description

It happens when I was trying to open a scene has missing dependencies in version 9b78d6.
I have built a newer version(f805ecf) on June 3rd, the bug also occurs in that version.

And, I got this log on console windows.
![Bug2](https://user-images.githubusercontent.com/86307226/172138761-bd3da876-2a0b-4fe3-ae44-0ba25a314d61.png)

### Steps to reproduce

![Bug2 step](https://user-images.githubusercontent.com/86307226/172139836-04fe472c-f4b8-43a3-b8cf-cbcb9d032f34.gif)

### Minimal reproduction project

[Master Bug.zip](https://github.com/godotengine/godot/files/8843570/Master.Bug.zip)

("SplashScreen" has missing dependencies because it was copied from another project, this is not a bug.)

**Comment by ComanderKai77** [comment]
@KoBeWi I did also use a regular build without C# support.

**Comment by raulsntos** [comment]
It seems the crash is caused by #61371, I reverted the commit and no longer get a crash

**Comment by raulsntos** [comment]
It seems to be caused by #61371, I reverted the commit and no longer get a crash.

**Comment by njdf18** [comment]
I just tested it on latest master branch, It won't happen again.
I will close it.
