### ISSUE TITLE
Context Menu stops capturing mouse input after some unknown trigger

### ISSUE THREAD

**Issue by cridenour** [godotengine/godot#61758]
### Godot version

4.0-alpha9 (however others have reported since alpha7)

### System information

Windows 10

### Issue description

At some point in a work session, the editor will spawn context menus and dropdown menus that do not respond to mouse input. Keyboard navigation continues to work. Restarting the editor / reloading the current project will fix.

### Steps to reproduce

1. Use the editor using alpha9 (potentially since alpha7). Potential triggers could be other pop ups, editing text fields, etc. 
2. At some point, the context menus, dropdowns and even the Collision Mask component will stop capturing mouse clicks.

**Comment by KoBeWi** [comment]
I noticed that too, but it's quite rare. Happens after using the editor for some time.

**Comment by JackNewley** [comment]
Noticed this too after working with SkeletonIK. Also after waking up from window hibernate.

**Comment by RedMser** [comment]
Still present in latest master. Workaround is to enable single-window mode, for anyone who's having this issue.

I also don't need to restart Godot to fix it, since most of the time it fixes itself by closing and re-opening the same menu (this at least works for the "select resource" dropdown menu, or the "scene/project" menu at the top).

**Comment by KoBeWi** [comment]
This is still happening, or at least partially. Sometimes a popup is unresponsive, but it works again when you close and reopen it.

**Comment by Zylann** [comment]
I am porting my plugin to Godot 4.0.1, and I noticed a similar issue after doing some specific actions.

I have an importer dialog, which popups some child dialogs to let the user pick images, then the user can click "OK", which pops up a progress window on top of the importer dialog, then that window closes and another window pops up saying "Complete!".
After this happens, ALL popup menus of the editor stopped responding to mouse clicks. They popup, they hover, but clicking does nothing, and rather the event goes to what's behind them.

The issue mysteriously goes away after doing the same process again, but it's quite random.
I could not see any error occur in the editor output.

**Comment by phkeese** [comment]
I have the same problem in v4.0.3.stable.mono.official [5222a99f5]

**Comment by KoBeWi** [comment]
I haven't seen this bug for a long time, probably fixed in 4.2.
