### ISSUE TITLE
[Godot 4] The editor crashes when reloading any project or closing the editor

### ISSUE THREAD

**Issue by njdf18** [godotengine/godot#61759]
### Godot version

v4.0.alpha.mono.custom_build (f805ecf)

### System information

Windows11, Vulkan, NVIDIA GT 1050 Ti

### Issue description

Here is the log.
![Bug3](https://user-images.githubusercontent.com/86307226/172207455-2ee036e4-2a61-46b0-8990-c919a5f83f23.png)

### Steps to reproduce

1. Open any project.
2. close the editor or reload project.

### Minimal reproduction project

(No need)

**Comment by Calinou** [comment]
The backtrace is unfortunately not useful, as it was generated from a build that doesn't contain debug symbols. Try [building the editor from source](https://docs.godotengine.org/en/latest/development/compiling/compiling_for_windows.html) with MSVC (not MinGW) to get an useful crash backtrace.
