### ISSUE TITLE
TouchScreenButton touch simulation unreliable, only reacts to double click

### ISSUE THREAD

**Issue by mandmeier** [godotengine/godot#61750]
**EDIT** I updated to the latest stable version 3.4.4 and this is working now!

### Godot version

3.3.3

### System information

Apple M1

### Issue description

Hopefully reproducible example attached with a TouchScreenButton over the Godot face:

![image](https://user-images.githubusercontent.com/26724996/172155594-30f7a8df-1942-4944-8215-db79e350f364.png)

 Signals are connected from the button to the Node2D.gd script. For some reason I have to double click it to fire the press and release signals (the output is from a double click). Single click does not work. However, when I start the scene and click many times for 20s or so, single clicks are sometimes (but not always) accepted. Very confusing.

Emulate Touch from Mouse in Project settings is enabled with 0.15 Touch Delay. I also tried 0 Touch Delay, which had no effect. Anybody know what is going on here? My best guess is that the simulated touch has some lag and sometimes does not go through.

I also sometimes (but not always) get an error upon click:
```
E 0:00:03.704   emit_signal: Error calling method from signal 'pressed': 'KinematicBody2D(Player.gd)::_on_TouchControl_pressed': Method not found..
  <C++ Source>  core/object.cpp:1257 @ emit_signal()
```
Not sure if this error is related tho but I'm leaving it here for now. My Node2D was originally a KinematicBody2D named Player.gd.

This is my first time developing for mobile and if I can't reliably simulate touch in Godot I don't see how I can accomplish anything...

### Steps to reproduce

Node structure:
```
Node2D (with script)
- Sprite
- Touch Screen Button (overlaid over sprite with 2 signals connected to Node2D)
```
Node.2D script:

```
extends Node2D
func _on_TouchScreenButton_pressed():
	print("PRESS")

func _on_TouchScreenButton_released():
	print("RELEASE")
```

Then run the scene and try clicking on the button

### Minimal reproduction project

[TapTest.zip](https://github.com/godotengine/godot/files/8844176/TapTest.zip)

**Comment by Calinou** [comment]
[Godot 3.3.x is not supported for bug fixes anymore](https://docs.godotengine.org/en/stable/about/release_policy.html#release-support-timeline), so please upgrade to [3.4.4](https://godotengine.org/article/maintenance-release-godot-3-4-4) and check if the issue still occurs there.

**Comment by mandmeier** [comment]
**EDIT**: I updated to the latest stable version 3.4.4 and this is working now!
