### ISSUE TITLE
Ability to set custom shortcut keys for Animation Editor

### ISSUE THREAD

**Issue by therealrobster** [godotengine/godot#6175]
**Operating system or device - Godot version:**
OS X 10.11.6 - Godot V2.1

**Issue description** (what happened, and what was expected):
I want to use shortcut keys for the animation editor.  To go forward frame by frame.  Currently these are ctrl + left arrow and ctrl + right arrow.  The problem is, that is also the OS X shortcut keys to move between desktops.  I'd like to request we can choose custom keys for the animation editor frame by frame movement so we don't interfere with the default OS X keys.

**Steps to reproduce:**
Load up OS X, multi desktop and press ctrl + left arrow and ctrl + right arrow

Thank you....

**Comment by bojidar-bg** [comment]
I think this is fixed in 2.2/master, no?

**Comment by Calinou** [comment]
@bojidar-bg Indeed, all editor shortcuts can now be changed as of 3.0. The default also seems to be `Cmd + Left/Right` on macOS, so the original conflict should be solved out of the box.
