### ISSUE TITLE
Changes to `Window`'s theme don't propagate

### ISSUE THREAD

**Issue by AaronRecord** [godotengine/godot#61765]
### Godot version

Godot 4 alpha 9

### System information

Win11

### Issue description

https://user-images.githubusercontent.com/50304111/172254360-1b9bceb3-bf3c-4d8d-a184-d4dd54d052ba.mp4

I'm currently working on a fix

### Steps to reproduce

See above

### Minimal reproduction project

[MRP.zip](https://github.com/godotengine/godot/files/8848299/MRP.zip)

**Comment by LightningAA** [comment]
The same thing is true of the custom theme defined in the project settings
