### ISSUE TITLE
Light 2D Item cull Mask

### ISSUE THREAD

**Issue by jonSP12** [godotengine/godot#61760]
### Godot version

3.5 rc3

### System information

windows10 GLS3

### Issue description

The light2D layer mask doesnt seem to work

It only works when set to 1, 
If its set to 2, the light disapears

![light2D](https://user-images.githubusercontent.com/77213594/172209726-2e5c1e87-623f-4bed-ab87-66bdcd9aaeb6.png)

### Steps to reproduce

make light2D node
set Item cull Mask to layer 2

set a sprite light mask to layer 2

**Comment by jonSP12** [comment]
its working after all, i was changing the layer mask in the parent node.
it must be changed in the respective node

**Comment by RechieKho** [comment]
Yea, if you want the light mask affects the Sprite2D, you gotta set in the Sprite2D's property and not its parent. This is the same as Godot version 3.4.4. So there is no problem.

**Comment by jonSP12** [comment]
> Yea, if you want the light mask affects the Sprite2D, you gotta set in the Sprite2D's property and not its parent. This is the same as Godot version 3.4.4. So there is no problem.

but the kinematicBody2D has a light mask property, there...

**Comment by RechieKho** [comment]
I know. It seems weird to me, too at first glance. The truth is that the
Light Mask setting is ONLY for that node and do NOT influence the child
node. KinematicBody2D renders nothing to screen, the Node that renders
visuals is Sprite2D.

**Comment by akien-mga** [comment]
For the record, I closed this on behalf of the Code of Conduct team, as the OP was banned due to harassing contributors. They're restricted from further interacting so this issue cannot progress. If someone confirms that the issue is still reproducible, you can open a new issue.
