### ISSUE TITLE
add Constructor node to Visual Script

### ISSUE THREAD

**Issue by Marqin** [godotengine/godot#6176]
add Constructor node to Visual Script, that will allow to construct basic types

example usage:
![example_constructor](https://cloud.githubusercontent.com/assets/959429/17727717/808de7da-645b-11e6-80e1-5ed7cabffd54.png)

@reduz

**Comment by kubecz3k** [comment]
Check if you are not looking for a  `functions` -> `property set` -> `basic type set` .

**Comment by Marqin** [comment]
@kubecz3k no. This one you said:

* need input vector, not constructs one
* can only set one property, not construct with all like in **GDScript**

**Comment by Marqin** [comment]
@kubecz3k 

I want [constructor](https://en.wikipedia.org/wiki/Constructor_(object-oriented_programming)) that works like GDscript one.

So something like `Vector2(x,y,z)` which can be applied to other function.

**Comment by kubecz3k** [comment]
@Marqin actually it dont need input vector, you can set values by clicking on the `(0,0,0)` button.

**Comment by Marqin** [comment]
@kubecz3k without input it gives this error:
![zrzut ekranu 2016-08-17 o 09 46 54](https://cloud.githubusercontent.com/assets/959429/17728459/a1556d54-645f-11e6-99f9-a3ff2c7856c6.png)

But even if it doesn't need. There is still the second point.

**Comment by Marqin** [comment]
@kubecz3k well, the same you can remove Class constructors from GDScript and say:

> Why you need `Vector2(x,y)` when you can `var v = Vector2(); v.x = x; v.y = z;`

**Comment by fire** [comment]
Already done.

![godot windows tools_2018-10-11_14-47-35](https://user-images.githubusercontent.com/32321/46835988-9d0b7e80-cd64-11e8-8162-aafef6eb3e15.png)
