### ISSUE TITLE
SubViewport renders as pink box

### ISSUE THREAD

**Issue by jgillich** [godotengine/godot#61771]
### Godot version

83421cd06f8aeacc69d666e0e695333fdaa80377

### System information

Fedora Silverblue 36, Ryzen 2400G

### Issue description

Creating a `SubViewportControl` with a `SubViewport` node renders as a pink box as shown here:
![Screenshot from 2022-06-07 10-23-14](https://user-images.githubusercontent.com/347965/172334306-263278fc-a2de-4c47-ada5-b3779d3c1e8a.png)

If you assign a World3D, your objects become invisible in the editor view. Sometimes I'm also seeing an empty rendering instead of the pink color.

### Steps to reproduce

Download the reproduction project or:

1. Create `SubViewportContainer` and a `SubViewport` nodes, resize if necessary
2. Add a `MeshInstance` with a simple box shape and a `Camera3D` in the viewport
3. Observe resulting pink box in the editor preview and at runtime

### Minimal reproduction project

[SubViewport-demo.zip](https://github.com/godotengine/godot/files/8851547/SubViewport-demo.zip)

**Comment by Zireael07** [comment]
IIRC this was already reported but I can't find it...

**Comment by jgillich** [comment]
Ah, you're probably thinking of https://github.com/godotengine/godot/issues/55471

As others have mentioned, setting update mode to "Always" does not help. But it's describing the same issue so I'm closing this one.
