### ISSUE TITLE
Unable to initialize Video driver: Windows 10, Godot-mono

### ISSUE THREAD

**Issue by VirtualMaestro** [godotengine/godot#61778]
### Godot version

3.4.4-stable-mono, 3.5-rcX-mono

### System information

Windows 10 x64,  Sapphire RX 580 Nitro, Intel HD Graphics 530+

### Issue description

Hello guys,
For a couple of months, Godot worked fine, and just last week, it stopped working. The startup shows a popup with a message:
"Unable to initialize Video driver. Your video card driver does not support any of the supported OpenGL versions."  
I've tried diff Godot-mono versions: 3.4.4 and all the 3.5 RC. 

My system (all drivers and OS updates are up to date):
OS: Windows 10 Home (x64) Build 19043.1741 (21H1)
CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
Video Card (ext):  Sapphire RX 580 Nitro+  (driver version 22.5.2)
Video Card (int): Intel HD Graphics 530 (Skylake-S GT2) [S0/R0] [ASUS]

I've also tried another engine (Unity), and it works fine (maybe it is based on DirectX).
It is something with my system since Godot worked before (maybe after the usual video driver update?), but perhaps you have some thoughts or workaround.

Thank you in advanced  

### Steps to reproduce

Launch any version of the Godot.

**Comment by clayjohn** [comment]
Can you roll back to your previous version of your drivers and see if it starts to work again?

**Comment by clayjohn** [comment]
Have you also tried using both your intel and your dedicated graphics cards? An update could have broken the way that graphics cards are selected by the driver.

**Comment by VirtualMaestro** [comment]
You were right, it seems like OS wants to run Godot on the dedicated AMD video card, and Godot doesn't support the AMD cards.
When I manually switched to the integrated Intel card, Godot worked well.
It is a pity that Godot doesn't work with dedicated video cards, but nevertheless, the issue is solved and can be closed, I guess.
Many thanks!
![Godot_integrated_card](https://user-images.githubusercontent.com/426870/172452511-ffc7cfce-e097-48b8-bfda-2abe4f73d3d5.png)

**Comment by clayjohn** [comment]
> It is a pity that Godot doesn't work with dedicated video cards, but nevertheless, the issue is solved and can be closed, I guess.

Godot should work fine on an RX 580. 

When you updated your graphics drivers how did you do it? Is it possible you have only been updating your intel drivers and not your AMD drivers?

**Comment by Calinou** [comment]
> @Calinou Do you know of other users having issues with RX 580 (or similar) cards?

Not that I know of, and I don't have any AMD graphics card.

**Comment by VirtualMaestro** [comment]
For the one who will face such an issue. 
In this case, it was my bad since, by mistake, I've plugged my both monitors (HDMI, DisplayPort) into the motherboard instead of the graphics card (thanks to AMD engineers for the hint).
