### ISSUE TITLE
AnimatedTextures don't work with atlases

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot#61774]
### Godot version

3.5 RC3

### System information

Windows 7 64-bit

### Issue description

Trying to use atlases with animatedtextures don't work, the animations don't play even though the atlas is set-up correctly. It was previous referenced here: https://github.com/godotengine/godot/issues/37860 and here: https://github.com/godotengine/godot/issues/37977 but was closed without much information and it definitely seems as though this should be supported (and is incredibly confusing why it doesn't if you've gone to the trouble of setting one up).

### Steps to reproduce

- create an animatedtexture
- add an atlas as the frame textures
- watch the animatedtexture not animate

**Comment by KoBeWi** [comment]
As said in the comment linked in the issue:

> This approach is very, very efficient and works for both 2D and 3D. In exchange, It does not support atlas or spritesheets (which makes sense, as that those are client-side and this is server side).

I don't know what more you want to know. This is done for performance reasons and is not going change.

[It's already documented as a known limitation](https://docs.godotengine.org/en/latest/classes/class_animatedtexture.html#description), so the discussion should go to a [proposal](https://github.com/godotengine/godot-proposals).

**Comment by KoBeWi** [comment]
Yeah I linked to another issue that linked to a Twitter post, so it could be difficult to find. Here's the original comment: https://twitter.com/reduzio/status/1018869909781180427
