### ISSUE TITLE
[3.5 RC3 - Mono] NavigationMesh resource has unusual property names.

### ISSUE THREAD

**Issue by viksl** [godotengine/godot#61781]
### Godot version

3.5 RC3 mono

### System information

Windows 10, Nvidia gtx 1660Ti, latest drivers, GLES3

### Issue description

Firstly, I'm not sure if this is a bug in some parser, intended or ... so I apologize if this is how it's meant to be.

If you check NavigationMesh you will find property names such (__ is a double underscore):
```
public NavigationMesh.SourceGeometryMode Geometry__sourceGeometryMode
public string Geometry__sourceGroupName
public float Cell__size
```

These come from some gdscript names which contain a slash (/) so I'm not sure what is an exact C# format for this that's why I'm not sure if this is a bug or not, I just can't find what else in godot to compare this to.

### Steps to reproduce

Check the NavigationMesh properties.

**Comment by Calinou** [comment]
cc @smix8

**Comment by smix8** [comment]
That is not a navigation issue but I guess C-Sharp API ugliness.

The NavigationMesh exposes scripting properties with a slash which I personally do not like but that is how Godot currently rolles with this. I guess the use of slashes has historic reasons for inspector grouping. I would prefer a general use of underscores for properties that are just a single variable and not a path.

**Comment by akien-mga** [comment]
It looks like these properties were already named with a slash in 3.4, so I guess it's not a regression from the new navigation server?

So we have two possibilities, either leave it be for 3.x and just improve the naming in 4.0 (if not done already), or change the naming now for 3.5 and add compatibility code in `_set` / `_get` to reuse values from 3.4. But the 3.5 release is imminent so there isn't much time to do this.

**Comment by smix8** [comment]
Not sure about <3.5 compatibility and adding so many setter and getters as we already broke the resource compatibility in 3.5 by changing the default properties and the clamp errors a little in multiple PRs and the NavigationServer needs a proper cell size set for merging so all old NavigationMesh resources need to be updated and rebaked by users anyway. The dedicated set and get functions are still the same for the properties so some compatibility remains.

**Comment by akien-mga** [comment]
@smix8 It shouldn't require a lot of setters and getters, just something like this (untested):
```cpp
#ifndef DISABLE_DEPRECATED
bool NavigationMesh::_set(const StringName &p_name, Variant &p_value) {
	String name = p_name;
	if (name.find("/") != -1) {
		// Compatibility with pre-3.5 "category/path" property names.
		name = name.replace("/", "_");
		set(name, p_value);
		return true;
	}
	return false;
}

bool NavigationMesh::_get(const StringName &p_name, Variant &r_ret) const {
	String name = p_name;
	if (name.find("/") != -1) {
		// Compatibility with pre-3.5 "category/path" property names.
		name = name.replace("/", "_");
		r_ret = get(name);
		return true;
	}
	return false;
}
#endif // DISABLE_DEPRECATED

**Comment by viksl** [comment]
I'm not sure if I I should report this to reopen this or open a new issues so I'd like to ask, I noticed more unusual names in the RC4, in this case it's on KinematicBody, for example Collision__safeMargin, Motion__syncToPhysics. Again double underscores. I'm not really sure how to check the api for more appereances, I use a decompiler in my IDE to check it out but I right now don't know how to search the whole appi at least for these double underscore cases to report them all.

Should I open a new issue, please? @akien-mga

**Comment by viksl** [comment]
Oh thanks, I'm and idiot. Sorry for polluting it here. Have a nice day :)
