### ISSUE TITLE
DampedSpringJoint2D.set_length() doesn't affect attached bodies

### ISSUE THREAD

**Issue by genete** [godotengine/godot#6178]
**Operating system or device - Godot version:**
OSX 10.10.3 Godot 2.1 stable official

**Issue description** (what happened, and what was expected):
I have two bodies (static and rigid) attached by a DampedSpringJoint2D node. When using GDScript I call set_length() with a different length or call set_rest_length() with a different rest length, the rigid body doesn't react at all. I expect that it would moves when any of the two lengths are modified on run time.

**Steps to reproduce:**
Create two 2D bodies (static and rigid) and attach them with a DampedSpringJoint2D. Create one script to change the length or/and the rest length of the spring at run time.
Notice how the rigid body doesn't react at all.

**Link to minimal example project** (optional but very welcome):
[SpringTest.zip](https://github.com/godotengine/godot/files/421982/SpringTest.zip)

Usage: 
Please be sure that Debug options has collision shapes visible.
Use up and down arrows to change spring length.

Script used:

```
extends DampedSpringJoint2D

var length=100
var new_length=100

var node_a_path
var node_b_path

func _ready():
    set_process_input(true)
    set_fixed_process(true)
    node_a_path=get_node_a()
    node_b_path=get_node_b()
    pass

func _fixed_process(delta):
    if length==new_length:
        return
    length=new_length
    set_node_a("")
    set_node_b("")

    set_rest_length(length)
    set_length(length)

    set_node_a(node_a_path)
    set_node_b(node_b_path)

    pass

func _input(event):
    if event.is_action_pressed("ui_up") and not event.is_echo():
        new_length+=10
    if event.is_action_pressed("ui_down") and not event.is_echo():
        new_length-=10
    pass
```

**Comment by bojidar-bg** [comment]
I guess the bodies are sleeping?

**Comment by genete** [comment]
No, they are alive. Static is always steady as its nature but rigid moves a bit when project start accommodating to the spring and gravity reactions. See the attached project example.

**Comment by genete** [comment]
Commenting the lines:

```
    set_node_a("")
    set_node_b("")

....

    set_node_a(node_a_path)
    set_node_b(node_b_path)

```
gives the same result.

**Comment by genete** [comment]
Aaah,
solved:

Changing the script to this fixes the issue:

```
func _fixed_process(delta):
	if length==new_length:
		return
	length=new_length

	get_node(node_b_path).set_sleeping(false)

	set_rest_length(length)
	set_length(length)

	pass
```

Notice that body b is the rigid body.

**Comment by bojidar-bg** [comment]
Anyway, I think that the spring should automatically awake the two bodies when its length changes..

**Comment by mateka** [comment]
On my Windows 10 machine, in latest stable Godot, when I change script to:`extends DampedSpringJoint2D

var length=100
var new_length=100


func _ready():
	set_process_input(true)
	set_fixed_process(true)

func _fixed_process(delta):
	if length==new_length:
		return
	length=new_length

	set_rest_length(length)
	set_length(length)

func _input(event):
	if event.is_action_pressed("ui_up") and not event.is_echo():
		new_length+=10
	if event.is_action_pressed("ui_down") and not event.is_echo():
		new_length-=10
	pass`
everything works just fine.

I really do not know, why You change bodies in _fixed_process when they are not changed at all.

**Comment by Anutrix** [comment]
Is this issue present in 3.1 or master branch?

**Comment by NihilAleph** [comment]
Hello! First time trying to contribute! ^^ Anyway, I tested this on master @ 64c9b7ffcfbb4c6fc58eb188c7cb9ed513853f3a and it seemed to work fine!

**Comment by bojidar-bg** [comment]
Closing as fixed, per the above comments. If someone can reproduce it in 3.2.x or in master, it might be reopened.
