### ISSUE TITLE
`PoolStringArrays` have wierd behaviour on `Resource`

### ISSUE THREAD

**Issue by bend-n** [godotengine/godot#61799]
### Godot version

3.4.4.stable.arch_linux

### System information

ArchLinux x11

### Issue description

`PoolStringArray` `Resources` exhibit strange behaviour.
Array does not update.

### Steps to reproduce

```gd
extends Node

class Item:
	extends Resource
	var items : PoolStringArray = []

func _ready():
	print(prepare_item().items)

func prepare_item()->Item:
	var item := Item.new()
	item.items.append("hello")
	item.items.append("world")
	print(item.items)
	return item
```

### Minimal reproduction project

[bug.zip](https://github.com/godotengine/godot/files/8858969/bug.zip)

**Comment by Zireael07** [comment]
Duplicate of https://github.com/godotengine/godot/issues/59598, which was fixed via better documentation.

Basically, intended.

**Comment by bend-n** [comment]
WHAT!

**Comment by bend-n** [comment]
@Zireael07

https://user-images.githubusercontent.com/70787919/172551808-8e6620cd-fa6e-47ff-963e-24e35523d504.mp4

is this related?

**Comment by Zireael07** [comment]
No, I think it's a separate issue (And first I'd triple check that your variables are the type you think they are)
