### ISSUE TITLE
Not being able to install android version

### ISSUE THREAD

**Issue by L4z4r1** [godotengine/godot#61791]
### Godot version

4.0 dev

### System information

Android 10

### Issue description

When I tried to download the APK it worked, but when tried to install it, it said app not installed.
![Screenshot_2022-06-07-22-47-42-626_com google android packageinstaller](https://user-images.githubusercontent.com/107078837/172482178-d184bcc5-e3e7-46c1-928d-b26ec4b572af.jpg)

(Translation: app not installed; done)

### Steps to reproduce

Download app and try to install it

**Comment by Calinou** [comment]
@L4z4r1 What device model do you have? The current Android editor releases only include 64-bit ARM libraries, so 32-bit ARM and x86 devices are not supported.

**Comment by proti1** [comment]
@L4z4r1 do you have previous build of Editor installed?
if so try uninstalling if first
fresh install fixed it for me 😅

**Comment by akien-mga** [comment]
This should work fine now. Please let us know if it still doesn't.

**Comment by Ieida** [comment]
I have the exact same problem. Fixed it by including 32bit and 64bit binaries in the export settings. I guess the device I was testing as 32bit... something I completely forgot about.
