### ISSUE TITLE
Lines around meeting edges of 3D Meshes

### ISSUE THREAD

**Issue by Travistyse** [godotengine/godot#61796]
### Godot version

4.0 Alpha 9

### System information

Windows 11, Vulkan, RTX 2070

### Issue description

![image](https://user-images.githubusercontent.com/14159864/172507031-8ad941c3-206f-4289-8a47-efca06e6129e.png)

[MinExampleTile.zip](https://github.com/godotengine/godot/files/8857345/MinExampleTile.zip)

Included the Blender file as MinExampleTile.zip

I can't for the life of me stop these lines from appearing. I've tried increasing the scale, overlapping, adjusting the camera angle.. nothing. No settings seem to fix it as far as I've been able to tell. 

This happens with and without lighting / shading.

### Steps to reproduce

Import meshes, put them beside each other perfectly, and watch as the meshes effectively add a tiled outline :(

### Minimal reproduction project

[MinExample.zip](https://github.com/godotengine/godot/files/8857341/MinExample.zip)

**Comment by Zireael07** [comment]
Been reported a couple times. I am having a hard time typing the correct words into the search, though.

**Comment by Travistyse** [comment]
> Been reported a couple times. I am having a hard time typing the correct words into the search, though.

I'll close it as a duplicate then - didn't see this when I googled for it either so with neither of us seeing it I at least don't feel so bad.

**Comment by Zireael07** [comment]
I only know because I happened to report it a couple years back in the early 3.x era :)

**Comment by Travistyse** [comment]
Hopefully it's something that can be fixed now that the renderer has been updated - I know that that's been what most rendering related bugs and features have been waiting on. But if this weren't the Godot community I'd be pretty concerned lol but it's not like I haven't seen worse from other engines - at least with Godot if it comes down to the eleventh hour I can just binge some Vulkan tutorials and pray I can fix it myself.
