### ISSUE TITLE
wrapf documentation inconsistent with its behavior

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#61801]
### Godot version

3.x (d51fc369b732c662ebfa911a7a4d1bf7a10ea66b)

### System information

Any

### Issue description

This was reported on Weblate against the `3.x` docs, but it's likely the same in `master` (didn't test but the code and docs are the same).

The `wrapf` documentation gives this example:
```gdscript
# Infinite loop between 5.0 and 9.9
value = wrapf(value + 0.1, 5.0, 10.0)
```

But if you run this code with e.g.:
```gdscript
var value = 0

func _process(_delta):
    value = wrapf(value + 0.1, 5.0, 10.0)
    print(value)
```

It prints:
```
5.1
5.2
5.3
5.4
5.5
5.6
5.7
5.8
5.9
6
6.1
6.2
6.3
6.4
6.5
6.6
6.7
6.8
6.9
7
7.1
7.2
7.3
7.4
7.5
7.6
7.7
7.8
7.9
8
8.1
8.2
8.3
8.4
8.5
8.6
8.7
8.8
8.9
9
9.1
9.2
9.3
9.4
9.5
9.6
9.7
9.8
9.9
10
5.1
5.2
5.3
```

So it seems to wrap between 5.1 and 10.0.

Either the docs or the implementation are wrong.

### Steps to reproduce

See above.

### Minimal reproduction project

See above.

**Comment by Chaosus** [comment]
(Confirmed in 4.0) I think it's a bug in the implementation ^^.
