### ISSUE TITLE
GPUParticles2D distorted randomly

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#61806]
### Godot version

c09d830

### System information

Windows 10 x64

### Issue description

https://user-images.githubusercontent.com/2223172/172606083-8ede3ce1-7e93-47c0-85be-44132076dce3.mp4

Happens in my project, but I can't reproduce it outside even when using the same scenes. I don't know what is causing it.

### Steps to reproduce

1. Use GPUParticles2D
2. No idea

**Comment by Chaosus** [comment]
Duplicate of https://github.com/godotengine/godot/issues/56691
