### ISSUE TITLE
Cannot drag and drop file to @export_file field

### ISSUE THREAD

**Issue by quantumcode-martin** [godotengine/godot#61811]
### Godot version

4.0.aplha9

### System information

Windows 10

### Issue description

When you create an export file field (`@export_file("*.tscn) my_var` for example), you can only select a file using the "Open a file" button.
It is impossible to drag and drop a file to the corresponding field. It would be much better in terms of usability.

### Steps to reproduce

1. Create a scene
2. Add a script
3. Declare an exported file variable (`@export_file my_var`) and save
4. Try to drag and drop a file to the field from your FileSystem

**Comment by KoBeWi** [comment]
It was the same in 3.x, the name of export just changed.
