### ISSUE TITLE
Vulkan: MultiMeshInstance3D Mesh distorted

### ISSUE THREAD

**Issue by SmartySmart702** [godotengine/godot#61825]
### Godot version

Godot 4.0 alpha 9

### System information

Win 10

### Issue description

MultiMesh is distorted and at high counts you can see it flickering in front of your camera.

### Steps to reproduce

Create a basic scene where you are able to look around (move the camera away from the origin).
Add a MultiMeshInstance at the center: Transform Format 3D, Mesh > New Box Mesh, Instance Count > Try 1 and 5000
Press play and move your camera.

Camera3D script:
```gdscript
extends Camera3D

var mouse_sensivity = 0.01

func _unhandled_input(event):
	if event is InputEventMouseMotion:
		rotation.y -= event.get_relative().x * mouse_sensivity
		rotation.x -= event.get_relative().y * mouse_sensivity
		rotation.x = clamp(rotation.x, deg2rad(-89.9), deg2rad(89.9))

	elif event is InputEventKey:
		if event.keycode == KEY_ESCAPE:
			get_tree().quit()
```

**Comment by Calinou** [comment]
@SmartySmart702 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by SmartySmart702** [comment]
Minimal reproduction project:
If you cannot see any issue:
Select the MultiMeshInstance3D, clear the MultiMesh and add a new one.
Set Transform Format to 3D, set Instance Count to 10000, use BoxMesh as Mesh

[MultiMesh_Flickering_Test.zip](https://github.com/godotengine/godot/files/8871052/MultiMesh_Flickering_Test.zip)

**Comment by SmartySmart702** [comment]
Easy workaround is to set the transform manually.

**Comment by clayjohn** [comment]
I have taken a look at the MRP, but I am a little confused, it looks like in the MRP the instance transforms are never set and instead the instance transform array is filled with garbage data. 

Can you clarify how you have set the instance transforms in producing the MRP?
