### ISSUE TITLE
Some missing Uralic locales

### ISSUE THREAD

**Issue by WilllRU** [godotengine/godot#61828]
**Godot Version 3.4.4** 

**Missing Locales**
Komi-Zyrian (kv_RU) and Skolt Sami (sms_FI) are being localized for use in Godot project "QoreBit" 

**[URL to the documentation page (if already existing):](https://docs.godotengine.org/en/stable/tutorials/i18n/locales.html?highlight=locales)**

Komi-Zyrian:
https://kv.wikipedia.org/wiki/%D0%9C%D0%B5%D0%B4%D1%88%D3%A7%D1%80_%D0%BB%D0%B8%D1%81%D1%82_%D0%B1%D0%BE%D0%BA

Skolt Sami incubator:
https://incubator.wikimedia.org/wiki/Wp/sms/Ouddseidd

Localization on github:
https://github.com/WilllRU/QBLang_List

**Comment by bruvzg** [comment]
4.0 have it supported - see [locales.h](https://github.com/godotengine/godot/blob/7e0c54e292f2813878d178bbb691a419ed6fb295/core/string/locales.h) (it is in the list of languages, but 4.0 will accept any locale code, even if it's not listed).

3.x have a limited list of locales - see [translation.cpp](https://github.com/godotengine/godot/blob/e9ca65207e3d66b6f2115d5311306d858d5ffc28/core/translation.cpp) and IIRC 3.x won't load anything not in this list. We probably should backport #52969 to 3.x, but it seems like too big of a change to do for 3.5.

**Comment by WilllRU** [comment]
Thank you for the information!
