### ISSUE TITLE
Editor freezes/crashes when TIME is used inside a shader function

### ISSUE THREAD

**Issue by Grumoth** [godotengine/godot#61845]
### Godot version

4.0 Custom (ae78928232bc309de571caab0e864b686c96e289)

### System information

Arch Linux Kernel Version: 5.15.41-1-MANJARO (64-bit)  NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2 Vulkan

### Issue description

If you use TIME inside the fragment() function it doesn´t break, but if you use it inside a function, the editor will freeze/crash.

Tested in Alpha 9  and it works well apparently,

example:
ALBEDO=color.rgb*sin(TIME*speed); //<- This is OK

but this is not:

vec3 _this_breaks(){
    return color.rgb*sin(TIME*speed);
}
void fragment() {
    ALBEDO=_this_breaks();
}

The log brings a 3500 lines error ending with:
3413 | #endif
3414 | }
3415 | 
3416 | 
   at: _compile_variant (servers/rendering/renderer_rd/shader_rd.cpp:280)
ERROR: Condition "!shader_singleton->shader.version_is_valid(version)" is true.
   at: set_code (servers/rendering/renderer_rd/forward_clustered/scene_shader_forward_clustered.cpp:169)

### Steps to reproduce

- Open node_3d.tscn
- Open bug_time.gdshader
- Uncomment either the function  _this_breaks() and ALBEDO=_this_breaks()

### Minimal reproduction project

[Bug_Shader_time.zip](https://github.com/godotengine/godot/files/8869264/Bug_Shader_time.zip)

**Comment by Calinou** [comment]
cc @clayjohn
