### ISSUE TITLE
Running the game before saving issue

### ISSUE THREAD

**Issue by iammangod96** [godotengine/godot#6184]
**Operating system or device - Godot version:**
Windows 8.1

**Issue description** (what happened, and what was expected):
When I run a scene that is not saved, it prompts me first to save the game. That is perfectly good. But after saving it forgets to call run. I have to press run by myself again to make it run. So I think the run function is not being called in that particular routine.

**Steps to reproduce:**
As stated above.

**Link to minimal example project** (optional but very welcome):

**Comment by iammangod96** [comment]
Please refer me to the filename concerned with this issue. I really want to do it myself if the issue is justified.

**Comment by bojidar-bg** [comment]
@iammangod96 I think it is editor_node.cpp
