### ISSUE TITLE
Subclass cannot be inherited from other subclass in autoload using its naming alias

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#61848]
### Godot version

a2c016e997fbff4c1af6f3c7220de7bfe1e59105

### System information

Windows 11

### Issue description

Nested class from autoload cannot be accessed in the other script file using autoload name (only full path):

![image](https://user-images.githubusercontent.com/3036176/172854517-d5d3d46a-d009-42a1-9c01-3f83a642e760.png)

while this is ok:

![image](https://user-images.githubusercontent.com/3036176/172854728-aa4ff233-9143-41cd-835a-0600088e7bad.png)

### Steps to reproduce

Create autoload GDScript file like :

```
extends Node

class A:
	pass
```
(call it `Global.gd`)

Create a GDScript and fill it like:
```
extends Node

class B extends Global.A:
	pass
```

<i>EDIT: Actually is not even for 2nd case - it inherits autoload itself instead of nested class</i>

### Minimal reproduction project

[class_test.zip](https://github.com/godotengine/godot/files/8870597/class_test.zip)

**Comment by rune-scape** [comment]
just tested that #68374 fixes this
