### ISSUE TITLE
AnimationTree process the extra frame when restarting Animation by some Nodes

### ISSUE THREAD

**Issue by TokageItLab** [godotengine/godot#61853]
### Godot version

4.0.dev (b36447f6f09ac608bfa76dda6a50ac92c7040077)

### System information

MacOS 11.6

### Issue description

When selecting a state, NodeTransition and NodeOneShot internally seeks and restarts the animation after it has played once, but processes the last frame at the time of restart.

https://user-images.githubusercontent.com/61938263/172902205-cf5b3476-891d-44f4-8839-aa1f3b17f8bb.mov

### Steps to reproduce

Play the animation once using NodeTransition or NodeOneshot, then change the state and play it again.

### Minimal reproduction project

[node_t_state.zip](https://github.com/godotengine/godot/files/8872383/node_t_state.zip)

**Comment by Rindbee** [comment]
It could be that the internal `time` is not reset while reseek in `AnimationNodeAnimation::process`.

**Comment by TokageItLab** [comment]
The pingpong issue will be resolved in #68992. The only remaining issue is the first frame of OneShot and Transition.
