### ISSUE TITLE
After maximizing window, enabling borderless does not cover the entire screen

### ISSUE THREAD

**Issue by lesleyrs** [godotengine/godot#61871]
### Godot version

3.4.4

### System information

Windows 10, GLES3, Intel HD Graphics 620

### Issue description

https://i.imgur.com/wiUEReB.png (the open space while game is running)

There's a little bit of space on the bottom and right side and for some reason it goes off screen at the top.

Not doing anything special just turning on borderless in-game after maximizing.

I tried setting window size manually but then the borderless window appears half off screen towards the bottom right, similar to what happens when I don't have hidpi turned on for normal windowed game. After changing the window size numbers I still can't get it to look just right.

### Steps to reproduce

Maximize window>borderless through code

**Comment by return2monki** [comment]
Still happens on 3.5, will check again once 4.0 is out

**Comment by marzecdawid** [comment]
@return2monki Could you please make a better screenshot showing the problem, for example a full screen image?

**Comment by return2monki** [comment]
@marzecdawid 

https://i.imgur.com/qmjUynn.png - maximized (normal)

https://i.imgur.com/p6RmWaz.png - from maximized to borderless

I think borderless going upwards off screen and leaving some empty space is wrong behaviour? What I want to happen is that it fills the screen excluding task bar. But I couldn't get it to work by manually setting values.

**Comment by lesleyrs** [comment]
Fixed in Godot 4 by seperating fullscreen and exclusive fullscreen (although it caused some new issue with not being able to revert fullscreen into windowed original position after maximizing it seems)
