### ISSUE TITLE
Animation editor - key creation mask ignored when creating new tracks

### ISSUE THREAD

**Issue by k7771911** [godotengine/godot#61907]
### Godot version

v4.0.alpha.custom_build [b9375ea7f]

### System information

MaOS

### Issue description

The mask appears to be ignored, only the last selected mask created a new track

![image](https://user-images.githubusercontent.com/38134085/173111117-9f863d80-45dc-4925-80d6-0aa4a528bc7b.png)

### Steps to reproduce

Select a mask and click Insert Key

**Comment by Calinou** [comment]
> Select a mask and click Insert Key

What mask are you referring to? Can you take a screenshot or upload a minimal reproduction project?

**Comment by k7771911** [comment]
These toggles are called _masks for inserting keys_ in the interface, clicking the Create Key button should create tracks and insert keys for the selected properties.

![image](https://user-images.githubusercontent.com/38134085/173112370-aba340fd-09ad-4fdd-94d6-3f2b761265eb.png)

**Comment by KoBeWi** [comment]
Can't reproduce
![godot windows tools 64_gql6Czf3cU](https://user-images.githubusercontent.com/2223172/173119799-0e977d41-6fb8-4449-90b1-ca891aaa6f10.gif)

**Comment by k7771911** [comment]
> Can't reproduce
Interesting, is that 4.0? How come you don't get a prompt asking you to confirm the creation of the new tracks?
