### ISSUE TITLE
Cubemap bug

### ISSUE THREAD

**Issue by tavotell** [godotengine/godot#6191]
**Operating system or device - Godot version:**
Ubuntu 15.10 (64 Bits) - Godot 2.1 Stable

**Issue description**
Cubemap is wrong saved when scene is closed and open again

**Steps to reproduce:**
- Create a scene, with spatial node as root, and camera and WorldEnviroment as children, create and set cubemap with all images
- Save scene (if you execute scene, you see that cubemap doesn't work)
- Close scene
- Open scene (cubemap disappeared)
- If you edit cubemap, you see that only Left image is configured, the others are in blank.

**Link to minimal example project**
Minimal example project and screenshots:
https://mega.nz/#!1IcAzJxL!7TzTeaT5iInpNSFYx_jKlinOLzMzVhfVn3l2M2aMy6U

**Comment by Calinou** [comment]
Cubemap support was removed in Godot 3.0 in favor of panorama skies, so this issue is no longer relevant.
