### ISSUE TITLE
CanvasItemEditor mouse wheel only zooming in one direction

### ISSUE THREAD

**Issue by k7771911** [godotengine/godot#61914]
### Godot version

v4.0.alpha.custom_build [b9375ea7f]

### System information

MacOS

### Issue description

The mouse wheel only zooms out, seem related to https://github.com/godotengine/godot/pull/61719

https://github.com/godotengine/godot/blob/b9375ea7fc135f5468dcfb8c80b51a945ac14155/editor/plugins/canvas_item_editor_plugin.cpp#L1292

Should probably be something like this:
`zoom_widget->set_zoom(zoom * ((zoom_widget->get_zoom() / zoom - 1.f) * ABS(p_scroll_vec.y) + 1.f));`

### Steps to reproduce

Move the wheel, observe the zoom

**Comment by KoBeWi** [comment]
Zoom works normally on Windows 10, but I noticed that it misbehaves sometimes (as it it was zooming in the wrong direction for a few steps, randomly).
