### ISSUE TITLE
Using shortcut on Button generates `mouse_exited` signal on the selected collider

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#61924]
### Godot version

b9375ea7fc135f5468dcfb8c80b51a945ac14155

### System information

Windows 11

### Issue description

If the user previously select a collider by using mouse (with emitted `mouse_entered` signal), and then pressed a shortcut connected to the button, it would generate `mouse_exited` signal which is incorrect:

![shortcut_bug2](https://user-images.githubusercontent.com/3036176/173176578-0ce8a342-3a35-4b70-8e73-0cd94fbc0ae1.gif)

### Steps to reproduce

It is better to be tested with a provided project - run it and press `B` key to see that mouse_exited signal generates incorrectly.

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/8883383/test.zip)

**Comment by rburing** [comment]
Bisected to https://github.com/godotengine/godot/commit/9d7d20a978fccf7b2871dc388f16b87b4b686144. The test project remade to work near that old version of Godot is attached: [test_mouse_exited.zip](https://github.com/godotengine/godot/files/9552046/test_mouse_exited.zip)

cc @EricEzaM

**Comment by EricEzaM** [comment]
Is it because focus is being taken by the button? Adding accept event for the button was correct I think (that pr linked above). but if the button triggering causes some signals to fire which in turn make the mouse exit event trigger, then that should be investigated if it is the desired behaviour.

**Comment by rburing** [comment]
The mouse exit being triggered is undesired behavior IMHO.

Picking is happening in [scene/main/viewport.cpp](https://github.com/godotengine/godot/blob/master/scene/main/viewport.cpp) based on input events. Could you take a look?

Maybe it's something to do with `is_input_handled()`.

**Comment by EricEzaM** [comment]
I might have time to look on the weekend. If anyone else is interested in investigating further - please go ahead.

**Comment by EricEzaM** [comment]
This is happening because of this:
https://github.com/godotengine/godot/blob/6991e9b43d0954018e1a82fa4cb28af42632ae92/scene/main/viewport.cpp#L3039-L3040

As soon as input is set as accepted, mouse exit is called:
https://github.com/godotengine/godot/blob/6991e9b43d0954018e1a82fa4cb28af42632ae92/scene/main/viewport.cpp#L2279

This was added here #29579 (cc @mrcdk (if you are still around) or @RandomShaper (who approved the logic behind the addition)), to fix #29575. Any thoughts about what we should do about this?

**Comment by EricEzaM** [comment]
In trying to fix this as well as keep the fix from #29575, here is what I have.

https://user-images.githubusercontent.com/41730826/193043339-e762cf6c-8f41-49a4-a851-32ecdb5afbd3.mp4

**Comment by Chaosus** [comment]
@EricEzaM Do you have progress with that? If you doubt - you can create two PRs for each case and decision will be chosen on the PR meeting
