### ISSUE TITLE
script not running when project starts

### ISSUE THREAD

**Issue by Benjistu52** [godotengine/godot#61921]
### Godot version

v3.4.4.stable.official [419e713a2]

### System information

windows11

### Issue description

I am new to Godot and wrote my first script in gdscirpt which is this 
```
extends Area2D

export var speed = 400.0

func _procces(delta):
	var direction = Vector2(0,0)
	if Input.is_action_pressed("up"):
		direction.y -= 1
	if Input.is_action_pressed("down"):
		direction.y += 1
	if Input.is_action_pressed("right"):
		direction.x += 1
	if Input.is_action_pressed("left"):
		direction.x -= 1
		
	position += direction * speed * delta
```
I know GDscript is based of of python, which is a language I know. The script is attached to an area2d component which has a sprite and collision shape 2d component as children. I made the input maps. I don't get any errors and yet when I run the project and used WASD or the arrow keys nothing happens, It's like it's not running.

### Steps to reproduce

I don't know how to go about reproducing this, it just came with the download for me.

### Minimal reproduction project

project file 
[test2d 2.zip](https://github.com/godotengine/godot/files/8882703/test2d.2.zip)

**Comment by Rubonnek** [comment]
Change `_procces` to `_process` on the fifth line.

**Comment by Benjistu52** [comment]
thank you
