### ISSUE TITLE
GDScript 2.0: Documentation claims that nested typed collections are supported, but they're not

### ISSUE THREAD

**Issue by assertchris** [godotengine/godot#61923]
### Godot version

4 alpha 9

### System information

macOS 12.4 M1

### Issue description

The [docs show an example of nested typed collections](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_exports.html#doc-gdscript-exports), which is a syntax I arrived at before finding the documentation demonstrating it.

The editor shows a syntax error when attempting this: https://github.com/godotengine/godot/blob/68bf4eb100a6b49133157b0ecf8c55119b575be8/modules/gdscript/gdscript_parser.cpp#L3060

Are nested typed collections supposed to be supported?

### Steps to reproduce

```
extends Resource
class_name GameLevel

enum types {
	wall_t_l,
	wall_t,
	wall_t_r,
	wall_r,
	wall_b_r,
	wall_b,
	wall_b_l,
	wall_l,
	empty,
	player,
	crate,
	dot,
	door,
}

@export var name := "New level"

@export var layout : Array[Array[types]] = [
	[types.wall_t_l, types.wall_t, types.wall_t, types.wall_t, types.wall_t, types.wall_t, types.wall_t_r],
	[types.wall_l, types.empty, types.empty, types.empty, types.empty, types.empty, types.wall_r],
	[types.wall_l, types.empty, types.empty, types.empty, types.empty, types.empty, types.wall_r],
	[types.wall_l, types.empty, types.empty, types.empty, types.empty, types.empty, types.wall_r],
	[types.wall_l, types.empty, types.empty, types.empty, types.empty, types.empty, types.wall_r],
	[types.wall_l, types.empty, types.empty, types.empty, types.empty, types.empty, types.wall_r],
	[types.wall_b_l, types.wall_b, types.wall_b, types.wall_b, types.wall_b, types.wall_b, types.wall_b_r],
]
```

**Comment by Calinou** [comment]
This was added in https://github.com/godotengine/godot-docs/pull/5752, but I didn't check whether the syntax was actually allowed.

**Comment by assertchris** [comment]
I can confirm `Array[Array]` works, but is there a way to hint to the property inspector that the enum and select boxes should be used instead of integer fields?
