### ISSUE TITLE
Binding external library with c++ custom module (OpenCV)

### ISSUE THREAD

**Issue by azoozs** [godotengine/godot#61938]
### Godot version

3.4 from source

### System information

Windows 10

### Issue description

Can someone give me an example of how to integrate the Opencv library with the C++ custom module? And how will the SCsub file? Will it work on android?

### Steps to reproduce

I have downloaded:
opencv-4.6.0-vc14_vc15.exe
https://github.com/opencv/opencv/releases/tag/4.6.0

**Comment by Calinou** [comment]
Please don't ask support questions here, as this issue tracker is meant to be used for bug reports only. Use one of the other [community channels](https://godotengine.org/community) instead.
