### ISSUE TITLE
Introduce callback function to custom modules

### ISSUE THREAD

**Issue by wkubiak** [godotengine/godot#6193]
**Operating system or device - Godot version:**
Windows 10 x64 - Godot 2.1 stable

**Issue description** (what happened, and what was expected):
During talks on IRC about how a custom module can register itself with the main loop in order for it to handle process notifications by itself, there was still the issue as to how the module could self-initialize itself.

The registering part would be solved by this call:
`OS::get_singleton()->get_main_loop()->connect("idle_frame",this,"mystep")`

@reduz proposed an idea that a callback could be introduced which would call every module when the main loop is created and when it's removed, which would effectively solve the issue of signaling a module that it should initialize itself.

**Comment by Calinou** [comment]
Is this still relevant in the current `master` branch?

**Comment by Calinou** [comment]
@_CHANGEME Can you (or anyone else) still reproduce this bug in [Godot 3.2.3](https://godotengine.org/article/maintenance-release-godot-3-2-3) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.
