### ISSUE TITLE
OS.move_to_trash() not functioning or poorly documented

### ISSUE THREAD

**Issue by NationalityNZ** [godotengine/godot#61942]
### Godot version

4.0 Alpha 9

### System information

Windows 10

### Issue description

Using OS.move_to_trash always produces a generic failure (error code 1). This could be due to my windows configuration, or it could also be due to a bug, or it could be because OS.move_to_trash() is very minimally documented.

### Steps to reproduce

Run the project and click the button.

```
func _on_button_pressed():
	var result = OS.move_to_trash("res://test.txt")
	print(result)
```

### Minimal reproduction project

[Move_To_TrashProject.zip](https://github.com/godotengine/godot/files/8884618/Move_To_TrashProject.zip)

**Comment by Calinou** [comment]
Did you disable the system trash in your Windows settings, or did you set a file size limit on it?

**Comment by NationalityNZ** [comment]
I can manually send files to the recycling bin, which I suppose means it is not disabled and not file size limited. My recycling bin is on a different hard drive from my godot projects if that makes a difference.

**Comment by Calinou** [comment]
> My recycling bin is on a different hard drive from my godot projects if that makes a difference.

This could be the cause of the issue. Can you reproduce this issue on a project created on the same hard drive?

**Comment by NationalityNZ** [comment]
My recycle bin is in the default location C:
Also, 3.4.4 apparently doesn't have OS.move_to_trash()
I will test whether putting it on the same directory helps.

**Comment by NationalityNZ** [comment]
I put a test project on the same drive as the recycling bin and unfortunately it didn't work. This was a new project.

**Comment by Calinou** [comment]
> Also, 3.4.4 apparently doesn't have OS.move_to_trash()

It's only exposed since 3.5rc: https://github.com/godotengine/godot/pull/60542

**Comment by bruvzg** [comment]
`move_to_trash` do not globalize path, therefore require a full real path (like `c:/something/`). Since `res://` in the exported project point to the contents of read only PCK, `move_to_trash` on `res://something` is not valid use anyway. But probably it should be considered a bug since it should be usable on `user://` files.

**Comment by Torguen** [comment]
This is also happening on Android.
godot version v3.5.1.stable.official [6fed1ffa3]

**Comment by Calinou** [comment]
> This is also happening on Android. godot version v3.5.1.stable.official [[6fed1ff](https://github.com/godotengine/godot/commit/6fed1ffa313c6760fa88b368ae580378daaef0f0)]

Please open a new issue with a minimal reproduction project attached.

**Comment by Calinou** [comment]
> Do I have to upload a tscn file?
< apk?
> ?¿?

A minimal reproduction project is a ZIP archive that contains *all* the project files, including `project.godot`.
