### ISSUE TITLE
[3.5rc3 mono] Scene crashes on scene reload while navigation (with avoidance) is processing.

### ISSUE THREAD

**Issue by viksl** [godotengine/godot#61944]
### Godot version

3.5rc3 mono

### System information

Windows 10, Nvidia gtx 1660Ti, latest drivers, GLES3

### Issue description

If you play a scene where you use navigation server and agents (not nodes, though maybe it happens with nodes too), you set everything in motion and then anytime try the scene reload (code below) the game video freezes and crashes after a while.
Godot editor itself doesn't crash.
There's no error or any message in the output in the editor and there's no output in window console either.
(since there's no messages maybe there's some threading problem when reloading but I have no idea?)

Code used to reload:
`GetTree().ReloadCurrentScene();`

If navigation is set up but callback isn't set (so navigation agents are not moving) then reload works just fine it seems.
Since navigation server is new in 3.5 I can't compare with previous versions but reloading scene in 3.4 works just fine for moving kinematicbody.

### Steps to reproduce
A. With minimal reproduction project:
1. Play the scene.
2. When it's loaded press left mouse button
3. It freezes at this point, wait a bit until it crashes completely

B. Setting it up on your own
Set up navigation scene with a navigation server and some agent, set the agent in motion with a callback (set agent's parent a KinematicBody for movement).

After that set an unhandled_input override for a mousebutton press and reload the scene through the input (crashes for both deferred and underferred calls).

(make sure to use navigation server directly not nodes, although some tests with nodes can be done extra too)

### Minimal reproduction project
[35rc3TestNavServer.zip](https://github.com/godotengine/godot/files/8885650/35rc3TestNavServer.zip)

**Comment by Calinou** [comment]
@viksl Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by viksl** [comment]
> 

I have it in plan but I can't do it today, I'll try to get it down tomorrow.

**Comment by viksl** [comment]
I've added the minimal project file, if someone tests this just play the scene and then after the scene loads press left mouse button and wait a bit until it crashes.

**Comment by Calinou** [comment]
cc @smix8

**Comment by smix8** [comment]
I have no test prereq and ability to debug c# projects. Please test with godot gdscript projects first to rule out that anything is a c# api bug. Then provide gdscript project as mrp and not mono project.

You basically void all warranty on SceneTree functions if you circumvent by using server api directly. The SceneTree reload function is not aware what you do custom on the NavigationServer and it can only act on what is inside the SceneTree which is Nodes. If you do not use Nodes and work with server api directly you are responsible for any cleanup, e.g. removing agent callbacks that have object refs that the reload deletes, and not the SceneTree.

**Comment by viksl** [comment]
@smix8 I see. I can add the gdscript project but is it even needed, if removing agent callbacks is meant to be done before reload then it's a problem on my end not the engine and I crash it simply because of my negligence?

**Comment by smix8** [comment]
Well yes and no. While it is your responsibility to cleanup if you use the server api directly with a test project I could try to add a validation somehwere on the navigationserver so it does at least not crash when the objects get invalid from clearing the scene.

**Comment by viksl** [comment]
> 

Ok I'll reply with a gdscript project.

**Comment by viksl** [comment]
[NavServerCrashTest.zip](https://github.com/godotengine/godot/files/8891051/NavServerCrashTest.zip)

Ok, here it is, I tried to remove everything that seemd ok to remove to keep really just the bare minimum.
Is this ok with you?
