### ISSUE TITLE
get_stream_name not working as expected?

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#6196]
**Operating system or device - Godot version:**
Ubuntu Linux 16.04 64-bit
Godot 2.2 alpha (Git)

**Issue description** (what happened, and what was expected):
http://docs.godotengine.org/en/latest/classes/class_streamplayer.html#class-streamplayer-get-stream-name indicates that it should return a string. Using a node ("/root/music_manager") to load streams, get_stream_name appears to return nothing (as in, it prints nothing - not even something like "[AudioStreamOGGVorbis:614]" which is what I'd expect given the description of the function).

**Link to minimal example project** (optional but very welcome):
https://dl.dropboxusercontent.com/u/67740160/Streamplayer_Singleton.7z

See Scripts/music_manager.gd line 40.

**Comment by eska014** [comment]
You can give a name to a resource (like a stream) using `set_name()`, but by default the name is just empty.

If you want the file path of the stream, you can call `stream_player.get_stream().get_path()`

If you want a string like `[AudioStreamOGGVorbis:614]`, convert the stream itself to a string using `str()`: `str( stream_player.get_stream() )`
That string consists of the concrete type followed by the instance ID. If you just want a unique ID, you can retrieve the instance ID directly as an int using `stream_player.get_stream().get_instance_ID()`

**Comment by Sslaxx** [comment]
http://docs.godotengine.org/en/latest/classes/class_node.html#class-node-set-name - set_name changes the name the node is referred to by.

"Return the name of the currently assigned stream" is the description for get_stream_name, where the name is a "field inside the file". This doesn't sound like it's to do with the node name, which is why the instance ID sounds to be more likely.

**Comment by eska014** [comment]
When you load a file in Godot, what you get is almost always of the type `Resource`, including streams. These resources, similar to nodes, can have a name, retrieved and modified using `set_name` and `get_name`.

`stream_player.get_stream_name()` is essentially just a shorthand for `stream_player.get_stream().get_name()`, unless no stream is set for the player, in which case you get `<No Stream>`.

**Comment by akien-mga** [comment]
Fixed by cba805225 for 2.1.

For master, it seems to be mostly unimplemented, so reclassifying as a bug.

**Comment by reduz** [comment]
vorbis does not seem to support getting a stream name... so kicking indefinitely

**Comment by reduz** [comment]
sorry, i mean stb_vorbis

**Comment by reduz** [comment]
Will close this because it's impossible to fix unless stb_vorbis implements it. Feel free to reopen if that ever happens.
