### ISSUE TITLE
[4.0 alpha 9] How can I set a property directly if it has a setter.

### ISSUE THREAD

**Issue by Daylily-Zeleen** [godotengine/godot#61977]
### Godot version

v4.0.alpha9.official [d7d528c15]

### System information

Windows 11, Vulkan, GeForce GTX 1060

### Issue description

I trying to migrate my 3.x plugin to 4.0, which I use many async setter functions.
These async setter functions can be call with `yield()` outside the object self.

In 3.x, we can append `self.` before the property to determine set directly or call setter function.

In 4.0, I try to define a async functions, and call it in property's setter( because set a property can't work with  `await` ).
However, I found it set a property which has setter must call its setter, whether  append `self.` or not.

The test script.
```
@tool
extends EditorScript

var set_count := 0

var prop:
	set(v):
		print("set in setter")
		_set_async(v)

# this issue is not about await async function.
func _set_async(v):
	print("set in func:")
	set_count+=1
	if (set_count>3): 
		printerr("avoid crush")
		return
	# This line will call the setter again
	prop = v
	await get_editor_interface().get_tree().process_frame

func _run():
	prop = true


```
The output :
```
set in setter
set in func:
set in setter
set in func:
set in setter
set in func:
set in setter
set in func:
  avoid crush
  Resumed function '_set_async()' after await, but class instance is gone. At script: res://new_script.gd:24
  Resumed function '_set_async()' after await, but class instance is gone. At script: res://new_script.gd:24
  Resumed function '_set_async()' after await, but class instance is gone. At script: res://new_script.gd:24

```

I know to add a behind property like `filed` and `property` in C# can deal this problem, but this behavior is too different to 3.x, and I must change huge code in this project. 

### Steps to reproduce

Just copy the script code and run in editor.

**Comment by KoBeWi** [comment]
It's impossible, see the docs: https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_basics.html#properties
We could have a special method that bypasses the setter, but it needs a [proposal](https://github.com/godotengine/godot-proposals).
