### ISSUE TITLE
GDScript Search Help empty after creating an Object Script

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#61970]
### Godot version

4.0 Alpha 9

### System information

Windows 11, Vulkan, Nvidia GTX 1050 Ti, 512.15

### Issue description

GDScript Documentation goes missing when a new script is created inheriting from Object (or other non-node classes)

### Steps to reproduce

Open Scripting Tab
Open Search Help -> List Visible
Create New Script Inheriting from Object (or other non-node classes)
Open Search Help -> List Empty

### Minimal reproduction project

MRP is impossible to create as reloading the project fixes it.

**Comment by Calinou** [comment]
Can you reproduce this on 3.4.4?

**Comment by mrjustaguy** [comment]
No, albeit There seems to be an empty doc created in 3.4.4 as a result

**Comment by AThousandShips** [comment]
Can someone verify this is still an issue on latest `master` or 4.0.3? I think it has been fixed

**Comment by AThousandShips** [comment]
Was updating my above PR and was at that point "relying" on this to not make some improvements 😆, but fortunately I verified it still wasn't possible just to make sure I wasn't missing something and presto!
