### ISSUE TITLE
FileDialog custom Text label overlaps with default Path label

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#6199]
**Operating system or device - Godot version:**
2.1stable
2.0.4.1

**Issue description** (what happened, and what was expected):

Into FileDialog, the custom Text label is overlapped with the default "Path" label.

![filedialog_label_overlap](https://cloud.githubusercontent.com/assets/9801802/17780336/4d4328de-656b-11e6-95a0-6ef732fcf4d8.png)

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by SuperUserNameMan** [comment]
a workaround is :

````
my_filedialog.get_child(1).set_align( Label.ALIGN_CENTER );
````
or
````
my_filedialog.get_child(1).set_align( Label.ALIGN_RIGHT );
````

**Comment by mateka** [comment]
My proposition is to place child dialog contents under label in AcceptDialog. Thank to that, custom text and FileDialog Path label will not overlap.
