### ISSUE TITLE
Inspector side scroll bar disappears 

### ISSUE THREAD

**Issue by RefinedSoftwareLLC** [godotengine/godot#620]
woe, unique glitch, Inspector Scroll bar disappears when viewing an "Animation Player Node" while the window is maximized. Reappears when not maximized.

**Comment by akien-mga** [comment]
I can hardly reproduce the issue, if I place the dock in such a manner that it would require a scroll bar, I reach the limit there:
![inspector](https://cloud.githubusercontent.com/assets/4701338/10853505/b2a1945c-7f36-11e5-8a5f-507afb55c873.jpg)
If I put the dock a bit lower, there is then a scrollbar. So at the limit position there are indeed a couple pixels cut off at the bottom, but that's a very minor issue.

**Comment by akien-mga** [comment]
I propose to close it for now; if there's a real need to fix this cosmetic glitch, I guess a pull request will come :)
