### ISSUE TITLE
Viewport mode stretching with Keep aspect creates letterboxing with window size override that is an exact multiple of the base window size on both axes

### ISSUE THREAD

**Issue by GithubPrankster** [godotengine/godot#62007]
### Godot version

4.0.alpha9.official.fc18891db

### System information

Windows 10, Vulkan, GTX 1060 3GB

### Issue description

![image](https://user-images.githubusercontent.com/33995085/173467189-edf5d1cb-3616-417d-84b7-236edfe629be.png)

When working with a lower resolution Viewport size meant to be scaled to perfectly fit a window of higher size (for uses like retro games), the **Keep** aspect option works but creates odd extra pixels at the top and bottom. 

![image](https://user-images.githubusercontent.com/33995085/173467266-679928fd-f0f1-42f5-9368-343eec35b683.png)
![image](https://user-images.githubusercontent.com/33995085/173467306-8b926f8a-fbed-41c8-b0b9-b7659257c8fe.png)

Considering the tested window size of **(1280,720)**, I identified that the actual window size became **(1290,730)**.

Testing **(640,360)** yielded a similar result.
![image](https://user-images.githubusercontent.com/33995085/173467964-e24dbf22-eacc-4d04-a1d8-77522aa59c9e.png)

### Steps to reproduce

Set **Viewport Width** and **Height** to 320x180.
Set **Window Width** and **Height Override** to a multiple of the **Viewport Width** and **Height**.
Set **Stretch Mode** to Viewport.
Set **Aspect** to **Keep**.

For the minimal reproduction project, open it with **Godot Engine 4.0 alpha 9**.

### Minimal reproduction project

[window_test.zip](https://github.com/godotengine/godot/files/8895271/window_test.zip)

**Comment by Calinou** [comment]
@GithubPrankster Can you reproduce this in 3.4.4?

**Comment by GithubPrankster** [comment]
> Can you reproduce this in 3.4.4?
Currently unavailable in my computer right now but I can confirm the latest release candidate of 3.5 does not have this issue, and 3.4.4 very likely doesn't as well.

**Comment by GithubPrankster** [comment]
Now that I'm home, I've also noticed that **Letting the window be resizeable does _not_ cause this issue**.

**Comment by GithubPrankster** [comment]
As of the commit I am testing, v4.0.alpha.custom_build [18159a657], this issue does not appear anymore and Viewport mode stretching with Keep aspect doesn't create letterboxing anymore.
