### ISSUE TITLE
MultiplayerSynchronizer does not sync properties on scene root

### ISSUE THREAD

**Issue by jgillich** [godotengine/godot#62027]
### Godot version

136f84fc3549fa22b700d80f86216c484174ffb6

### System information

Fedora Silverblue 36, Ryzen 2400G

### Issue description

MultiplayerSynchronizer does not sync properties if they are located on the root node of a scene. Instead they remain at their initial values. I have tested this with `CharacterBody2D` and `CharacterBody3D` nodes, not sure if it would be the same with a simple `Node` at the scene root.

### Steps to reproduce

Get the reproduction project: https://github.com/jgillich/gotodot-mp-repro (run with at least version 0df0a07ab86381c1580a0a38d11ec44c4c9fddf7, not alpha9)

1. Run 3 instances:
```
godot --server
godot --client
godot --client
```
2. In one of the client windows, use A/D or Left/Right to move your character
3. Observe how the position in the other client window does not update
4. Repeat the steps above but add `--use-child` to the run arguments
5. Observe how the position updates in all clients when a character is moved

There is potentially another bug, if you uncomment the `create_player` line in `world.gd` so the server is also a player, and then try to join with a client, you get a bunch of errors. In the bomber example the server is also a player, but I haven't managed to figure out what the difference is.

### Minimal reproduction project

https://github.com/jgillich/gotodot-mp-repro

**Comment by Calinou** [comment]
cc @Faless

**Comment by danhealy** [comment]
It also works if you make a standard node the parent of `CharacterBody2D`, i.e. if `..` is not the root of the scene

**Comment by Faless** [comment]
This is fixed after #62961 with the following small change to the gdscript code (adding `await get_tree().process_frame`):

```diff
diff --git a/world.gd b/world.gd
index 32e01b3..f481f3d 100644
--- a/world.gd
+++ b/world.gd
@@ -16,7 +16,8 @@ func _enter_tree():
 
                print('server listening on localhost 12100')
                multiplayer.set_multiplayer_peer(peer)
-               #create_player(multiplayer.get_unique_id())
+               await get_tree().process_frame
+               create_player(multiplayer.get_unique_id())
        else:
                peer.create_client("localhost", 12100)
                multiplayer.set_multiplayer_peer(peer)
```

Spawning on a child during the `_ready()` phase of the parent has known issues, and we should probably document that while try to make an internal fix.

I'll leave this issue open for now since it has nice keywords for search, but I should probably open a dedicated issue soon.

**Comment by jgillich** [comment]
One more thing I've noticed while testing is that MPSynchronizer bypasses property setters. Is this expected or a bug?

**Comment by jgillich** [comment]
@Faless I made #63308

Haven't bothered to make a reproduction project since you already have an idea, lmk if you'd like one
