### ISSUE TITLE
_get_property_list() does not work unless tool specified

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#62024]
### Godot version

3.5 a0f70c58196ad6c879926f8b40f1c2c083114d8f

### System information

Linux

### Issue description

If I add script like this:
```gdscript
func _get_property_list():
	var ret = [
		{"name": "stuff", "type": TYPE_INT}
	]
	return ret
func _get(property):
	match property:
		"stuff":
			return 0

```

no "stuff" property in inspector. However when I add "tool" keyword on top of the script, it works.
```gdscript
tool
func _get_property_list():
	var ret = [
		{"name": "stuff", "type": TYPE_INT}
	]
	return ret
func _get(property):
	match property:
		"stuff":
			return 0
```
Checked on Spatial and Node but I think it works everywhere this way now. I believe a few weeks ago
everything was working fine. Any ideas?

### Steps to reproduce

See the description.

### Minimal reproduction project

Just see above.

**Comment by Calinou** [comment]
I think this is expected. How can the editor call `_get_property_list()` if the script isn't running in the editor?

**Comment by slapin** [comment]
I remember this working as alternate to exports. Let me check with 3.4.

**Comment by slapin** [comment]
Yea
