### ISSUE TITLE
Offset in PathFollow infinite increment

### ISSUE THREAD

**Issue by BalamChaac** [godotengine/godot#6202]
**Operating system or device - Godot version:**
OSX 2.1 stable

**Issue description** (what happened, and what was expected):
The offset of the PathFollow continues incrementing indefinitely, it should increment until the maximum length of the curve3D. 
**Steps to reproduce:**
`path_follow.set_offset(path_follow.get_offset() + speed)`

**Link to minimal example project** (optional but very welcome):

**Comment by bojidar-bg** [comment]
What should happen with "looping" path follows? Should we just wraparound the value?
