### ISSUE TITLE
[2.x] Allowing *Player.play/set_stream to return ERR_FILE_UNRECOGNIZED etc.

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#6203]
**Operating system or device - Godot version:**
OS is N/A.
Godot 2.2 Alpha (Git)

**Issue description** (what happened, and what was expected):
If supplying one of the stream node play functions (and probably other related nodes/functions like set_stream) a file that is invalid for it to play back, it reports on the debugger that it is ERR_FILE_UNRECOGNIZED. It does not, however, actually return this value to the application itself.

It would be nice if the set_stream/play and related functions (for example, StreamPlayer.play) could also return this and other appropriate ERR_ values so that any calling function/node could respond accordingly - for example, a music player application could remove the offending file from its playlists.

**Comment by bojidar-bg** [comment]
Well, you would usually get this from load/preload, but yeah

**Comment by Sslaxx** [comment]
Yeah, but take this line for example: `set_stream (load (MusicToLoad))` - although you shouldn't really be doing it like this, load may be able to return the error values but set_stream cannot.

**Comment by akien-mga** [comment]
Well `set_stream` expects an `AudioStream` resource, and not a file, so it shouldn't return `ERR_FILE_UNRECOGNIZED`. It's your job to load your stream properly and do error management:
```
var stream = load(MusicToLoad)
if stream == OK:
    set_stream(stream)
```

**Comment by Sslaxx** [comment]
OK. I set up a very broken OGG file (a text file, in fact) as a test. MusicToLoad was set to point to it:
`	var MusicToPlay = load (MusicToLoad)
	print (MusicToLoad, " == ", MusicToPlay)`

This does this:
`res://Assets/Audio/Music/I_AM_EXAMPLE.ogg == [AudioStreamOGGVorbis:580]`

Load does _not_ return Nil, ERR_FILE_UNRECOGNIZED or any other error status, as you imply it will. It returns what appears to be a valid stream.

https://dl.dropboxusercontent.com/u/67740160/6203_Demonstration.7z contains a minimal demonstration. One fake OGG file (I_AM_EXAMPLE.ogg) that is loaded via _ready in global_space.gd.

The "Errors" tab in the Debugger pane reports three errors:
- Method/Function Failed, returning ERR_FILE_UNRECOGNIZED (music_manager.gd:38, global_space.gd:7)
- Condition 'p_channels!=1 && p_channels!=2 && p_channels!=4 && p_channels!=6 ' is true. returned ERR_INVALID_PARAMETER (music_manager.gd:38, global_space.gd:7)
- Condition '!stream_valid' is true. returned: ERR_UNCONFIGURED (music_manager.gd:47, global_space.gd:7)

Adding:
`	if (MusicToPlay):
		print ("YES")
	else:
		print ("NO")
		return (false)`
Straight underneath the `print (MusicToLoad, " == ", MusicToPlay)` results in "YES" being printed.

**Comment by Sslaxx** [comment]
Bump. I know #9793 for 3.x has been fixed/closed, but has anything been done with this for 2.x?

**Comment by Sslaxx** [comment]
Closing, as not really relevant any more.
