### ISSUE TITLE
Baked Lightmap Fails to Render when Asynchronous Shader Compilation Active and Use Bicubic Sampling is Disabled

### ISSUE THREAD

**Issue by daniel-abbott** [godotengine/godot#62047]
### Godot version

eda10e3a89b9939e7d9b5e22505c0a2b11c80d18

### System information

Windows 10, GLES3, NVIDIA GeForce RTX 3070 Laptop GPU/PCIe/SSE2

### Issue description

Commit eda10e3a89b9939e7d9b5e22505c0a2b11c80d18 appears to have introduced an issue where, using the GLES3 backend with async shader compilation enabled and bicubic sampling is disabled, lightmaps will fail to render. Reverting the changes from just this commit restores expected functionality.

Bicubic Sampling OFF / Shader Asynchronous + Cache (also occurs with only Asynchronous):
![image](https://user-images.githubusercontent.com/26112479/173677209-16d4e1db-bb70-4c0b-abb3-dc67fd14475f.png)

Either Bicubic Sampling ON or Shader Synchronous Compilation:
![image](https://user-images.githubusercontent.com/26112479/173677391-0cb07a60-0247-48f2-9b77-a5fdd8fb26d8.png)

Included is a small repro project with simple geometry, a baked lightmap, and bicubic sampling disabled. Loading the project alone (using a build from the mentioned commit) should demonstrate the issue, as the lightmap will not be visible in the editor.

### Steps to reproduce

In a new project, add lightmappable geometry, some bakeable lighting and a camera, and bake lightmaps. Make certain that Use Bicubic Sampling is disabled, and then run the project (or save, close, and re-open the project) - lightmaps will not be visible until Use Bicubic Sampling is enabled or shader compilation is set to Synchronous.

### Minimal reproduction project

[62021_repro.zip](https://github.com/godotengine/godot/files/8903545/62021_repro.zip)

**Comment by akien-mga** [comment]
Fixed by #62068.
