### ISSUE TITLE
csharp keywords 'foreach` appears mispelled

### ISSUE THREAD

**Issue by filipworksdev** [godotengine/godot#62049]
### Godot version

3.x  and 4.0 upstream

### System information

Windows 10, GLES3, Iris Xe

### Issue description

The line in question is here 

https://github.com/godotengine/godot/blob/5a76d7128a38e5e46c373a83e396b755d4971da8/modules/mono/utils/string_utils.cpp#L148

It lists `forech` which I think should be `foreach` but is  missing an `a` 

Edit: I don't think I needed to make an issue request for such a small thing but I couldn't find any other way to bring this to the attention of devs. Sorry! Please let me know in the future if I find a small issue like this how should I report it. 😊

### Steps to reproduce

None needed

**Comment by kleonc** [comment]
> Edit: I don't think I needed to make an issue request for such a small thing but I couldn't find any other way to bring this to the attention of devs. Sorry! Please let me know in the future if I find a small issue like this how should I report it. blush

It's fine like this, nothing to be sorry about! Thanks for the report! If you're capable of fixing such simple issue yourself then I think just straight up opening a PR with the fix (without opening an issue for it) would be fine. But if you're not going to fix this yourself then I think opening an issue is the way to go. :slightly_smiling_face:

**Comment by filipworksdev** [comment]
I am capable but I don't have a copy of 4.0 in my computer atm haha.

**Comment by n1kk-7** [comment]
Would you mind if I try to fix this? I'm very new to open source, to the point that I started searching about contributing just 2-3 days ago. This issue seems like a beginner-friendly problem, it could be a good point to start from. 

Just to clarify, all I need is to change 'forech' to 'foreach'? 
Thanks for helping out.

**Comment by kleonc** [comment]
> Just to clarify, all I need is to change 'forech' to 'foreach'?

Yes, the other keywords seems correct in there (but you could double check).
