### ISSUE TITLE
Renaming an animation state machine node while actively playing an animation crashes the editor.

### ISSUE THREAD

**Issue by tdaven** [godotengine/godot#62056]
### Godot version

4.0.dev (15740c37a3)

### System information

Linux, 64-bit, Fedora 36, AMD RX 590, Vulkan

### Issue description

Renaming a node of an animation state machine while the animation tree is actively playing the animation crashes the editor.  This is caused by the currently playing animation not getting renamed, which later results in a failure to find the correct node.

### Steps to reproduce

Create project,

**Comment by guilhermefelipecgs** [comment]
I didn't see any `crash`, when renaming the animation it just stops playing because the transition hasn't been updated correctly.
