### ISSUE TITLE
RichTextLabel.get_content_height() doesn't work

### ISSUE THREAD

**Issue by Remixful** [godotengine/godot#62050]
### Godot version

3.4.4.stable

### System information

Windows 10

### Issue description

I've filled a richtextlabel with text or bbcode. `get_content_height` returns bogus values like `-1404838 `or even `0` in some cases.
I'd try with different fonts and sizes with the [font] tag in bbcode too.

### Steps to reproduce

Create rich text labels and use RichTextLbale.get_content_height()
Or try the attached project and read the print outputs.

### Minimal reproduction project
[richtextlabeltest.zip](https://github.com/godotengine/godot/files/8904063/richtextlabeltest.zip)

**Comment by Calinou** [comment]
Can you try 3.5.rc3? This should be fixed now: https://github.com/godotengine/godot/issues/52634
