### ISSUE TITLE
CPUParticles3D spawn at world root position

### ISSUE THREAD

**Issue by djmaesen** [godotengine/godot#62055]
### Godot version

4.0 alpha8

### System information

linux

### Issue description

cpu particles spawn at world origin even if i set different transform

### Steps to reproduce

im trying to spawn a particle system at a given position, however they always instantiate at the worlds' root 
maybe my code is wrong or is it a bug?
~~~
var impactparticles = particles.instantiate()
	get_tree().get_root().add_child(impactparticles)
#self is a placed decal in the scene
	impactparticles.transform.origin = self.transform.origin
	impactparticles.emitting = true
~~~
if i set particle to local coordinates i get the same result

**Comment by djmaesen** [comment]
> `transform.origin` is _local_ origin. To set global origin, use `global_transform.origin`. You probably want to set the impact particles's global origin to the raycast hit location's global origin.

already tried that, same result

**Comment by Calinou** [comment]
@djmaesen Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by djmaesen** [comment]
[particletest.zip](https://github.com/godotengine/godot/files/8912321/particletest.zip)
@Calinou  here u go

**Comment by and-rad** [comment]
This is actually just a small mistake with your code. You instantiate the particle system before you set the position of the decal.

If you change the decal's `_ready` function to something like `emit_particles` and then call this function explicitly after setting the decal's position in `placeparticle.gd`, the problem will go away: 
```
impact.global_transform = impact.global_transform.orthonormalized()
impact.emit_particle()
```

**Comment by djmaesen** [comment]
> This is actually just a small mistake with your code. You instantiate the particle system before you set the position of the decal.
> 
> If you change the decal's `_ready` function to something like `emit_particles` and then call this function explicitly after setting the decal's position in `placeparticle.gd`, the problem will go away:
> 
> ```
> impact.global_transform = impact.global_transform.orthonormalized()
> impact.emit_particle()
> ```
tnx, will try it

**Comment by djmaesen** [comment]
ok it was my fault in the code. it works now.
close this topic please, tnx
