### ISSUE TITLE
Import Mesh - Normals option sometimes doesn't work.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#6206]
**Operating system or device - Godot version:**

Windows, G2.1

**Issue description** (what happened, and what was expected):

The checkbox for Normals in import mesh behaves a bit quirky.

I started an import of a set of meshes, and didn't check the Normal option.  I of course didn't get any lightning, and I chose to reimport, and checked the option.  It worked for the first, however, when I went to reimport the other meshes with the same missing option, the dialog remembers my selection, and the option appears checked, but must not be capturing it.  As I have to uncheck and recheck it for it to import with Normals.  Otherwise it will not work, even though the option is now checked by default.

**Comment by Calinou** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
Is this being closed as fixed, or no longer reproducible, or something else?

**Comment by avencherus** [comment]
@akien-mga Sorry no description.  Most likely culprit was me doing some naive, that's not too far past when I started learning game development.  Can't reproduce it in an old 2.1.4 project at least.

![godot 2 1 4 stable_2018-09-22_00-28-06](https://user-images.githubusercontent.com/13004169/45907150-84601680-bdff-11e8-85a7-2386b3618c5f.png)

![godot 2 1 4 stable_2018-09-22_00-32-24](https://user-images.githubusercontent.com/13004169/45907162-8f1aab80-bdff-11e8-8f87-321b2e329d5d.png)

Was looking fine at least.
