### ISSUE TITLE
`OptionButton` requires double click to hide its popup in the editor

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#62062]
### Godot version

ccd9378aac6b9faecce6e5cc2d97e5e5ce971f4b

### System information

Windows 11

### Issue description

Closing the popup requires double click to close (instead of single one) - I think it's provide bad user experience:

![option_button_bug](https://user-images.githubusercontent.com/3036176/173770740-deb1c845-967c-4505-8406-afdd99892f4e.gif)

Seems only Godot editor is affected by this bug.

### Steps to reproduce

^^

**Comment by Calinou** [comment]
> Seems only Godot editor is affected by this bug.

I've had issues with popups not closing when clicking away in https://github.com/godotengine/godot-demo-projects/pull/743.

**Comment by Maran23** [comment]
MenuButton as well. Looks like timing matters, if you wait 2 seconds, everything behaves normal. When you do a fast double click (the second click can also be somewhere else), the popup will open but the second click will still count.

**Comment by YeldhamDev** [comment]
Can't reproduce this on GNU/Linux. Can anyone reproduce this on macOS?

**Comment by Chaosus** [comment]
@YeldhamDev Are you sure? - `Single window mode` should be disabled in the editor settings to make it visible.

**Comment by YeldhamDev** [comment]
@Chaosus Quite sure:
![](https://i.imgur.com/k5zd6Sz.gif)

**Comment by Chaosus** [comment]
Then it may be a windows-only platform bug.

**Comment by codecustard** [comment]
@Chaosus, Possibly Windows 11 (to be more specific).
Tested on Windows 10 Home and I can't reproduce the bug.

**Comment by Chaosus** [comment]
This seems to be fixed in the recent beta builds.
