### ISSUE TITLE
TileMap: tiles from a scene collection are re-created each time a new cell is added

### ISSUE THREAD

**Issue by DarkMessiah** [godotengine/godot#62078]
### Godot version

4.0.alpha10

### System information

Windows 11, RTX 3070 TI

### Issue description

If you use a Scene Collection in a TileMap, when you add a new cell to a TileMap, all tiles in a layer are re-created.

![Godot_v4 0-alpha10_win64_erFrZOpnB6](https://user-images.githubusercontent.com/1756388/173898780-67500f3d-9d1e-4fb1-a51a-cf872d96a188.gif)

**Scene Tile:**
![image](https://user-images.githubusercontent.com/1756388/173902472-ca4bc390-a5ee-4c1e-8065-4d5ac4cd5f9b.png)

**Code:**
```gdscript
extends Node2D

func _ready():
	randomize()
	var r = randf()
	var g = randf()
	var b = randf()
	$Label.text = name
	$Label2.text = str(get_instance_id())
	$Sprite2D.modulate = Color(r, g, b)
```

### Steps to reproduce

1) Create a Scene Collection in a TileSet and add a scene to it.
2) Set few cells in a TileSet at runtime.
3) All nodes in a layer will re-created every time you set a new cell.

### Minimal reproduction project

[SceneTiles.zip](https://github.com/godotengine/godot/files/8912047/SceneTiles.zip)

**Comment by Calinou** [comment]
cc @groud

**Comment by KoBeWi** [comment]
Seems like same issue as #58034
