### ISSUE TITLE
Importing / Exporting gltf from godot duplicates the roots

### ISSUE THREAD

**Issue by fire** [godotengine/godot#62070]
### Godot version

778a9fce77322b1f0ab3014d586f2c451dc56da2

### System information

Windows 11, Nvidia 3000 series

### Issue description

![image](https://user-images.githubusercontent.com/32321/173845710-61c626d4-b35e-40ba-96c8-cd60c8ffcf0b.png)

### Steps to reproduce

Take the character from https://github.com/godotengine/godot/issues/57895 and export the gltf from Godot Engine 4.

Error: There are two roots.

### Minimal reproduction project

See https://github.com/godotengine/godot/issues/57895

**Comment by and-rad** [comment]
Does this also happen with non-skeletal meshes? I'm asking because I noticed recently that when importing a skeleton *from* a gltf file, the skeleton root is also kinda duplicated: a skeleton is created as a child of a node that is named after the skeleton as it's named in Blender. Maybe they're related and something is off about how skeleton nodes are created and parsed for gltf files.

**Comment by fire** [comment]
Can you post a sample project?

**Comment by and-rad** [comment]
Here you go:
[SkeletonPlusOne.zip](https://github.com/godotengine/godot/files/8916069/SkeletonPlusOne.zip)

The file contains a Blend file with a simple skeleton, the exported .glb file that is imported to Godot, and a minimal project with the skeleton imported. Notice how the parent node of the Skeleton3D in the imported file is named "skel", which is actually the skeleton's name in the Blender file.

**Comment by aaronfranke** [comment]
Exporting a scene as GLTF causes every node to be duplicated, not just the root nodes. Here's another minimal reproduction project. [62070.zip](https://github.com/godotengine/godot/files/9174845/62070.zip)

<img width="550" alt="Screen Shot 2022-07-23 at 6 37 13 PM" src="https://user-images.githubusercontent.com/1646875/180626336-e6ecf25f-f273-46b8-8f02-408efd154e05.png">
