### ISSUE TITLE
Wrong UV mapping when atlasing enabled for 3D objects

### ISSUE THREAD

**Issue by RandomShaper** [godotengine/godot#6207]
**Operating system or device - Godot version:**
Godot 2.1, Win 10 x64

**Issue description** (what happened, and what was expected):
Atlas generation plays bad with `GridMap`/`MeshLibrary`: the atlas is generated according to the settings in image groups and the meshes have it assigned instead of the original textures, but the UV mapping is wrong so the whole atlas image is mapped instead of the relevant region.
**UPDATE:** It looks as though atlasing doesn't work at all for 3D. Whilst I detected the issue with grid maps, I found it also breaks imported scenes.

**Steps to reproduce:**
1. Create a `MeshLibrary` with at least two meshes with different textures.
2. Create a `GridMap` making use of both meshes.
3. Add all textures to a texture group and enable atlas generation.
4. Run the game.

**Comment by RandomShaper** [comment]
These paragraph is in the docs:

> Atlases can be a nice solution to save some space on GUI or 2D artwork by packing everything together. The current importer is not as useful for 3D though (3D Atlases are created differently, and not all 3D models can use them).

I need some clarification on why 3D models cannot use atlases on under which exact circumstances. I could try improving support for it if I understood that,

**Comment by reduz** [comment]
Well, they could, but for each texture you bind, you would have to pass the
region.. which would be really inefficient.
Alternatively you could change the UVs but that would need to be done
offline.

**Comment by RandomShaper** [comment]
I'd take the offline approach. I'll think about it and submit a PR if I get
to do something good.

By the way, just to get it completely, why for 2D it's not an issue? It's
because of less expected state changes or so?

**Comment by RandomShaper** [comment]
I'm not sure at which engine component should this be done. If I get some guidace I could try to implement it myself. `FixedMaterial`s would be a good starting point, I guess.

Anyway, in the meantime, this could be considered a feature proposal.

**Comment by Calinou** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.
