### ISSUE TITLE
A problem with spatial materials, especially in parameters, specifically in (billboard mode)

### ISSUE THREAD

**Issue by yasser5elmedlaa** [godotengine/godot#62086]
### Godot version

3.5-rc3

### System information

windows 8.1 - gles(2.0)

### Issue description

When working on the particle system 3D, there is an important problem due to the failure of this tool (billboard mod) don't work in the spatial materials. There is another very, very important thing to upgrade the particles system, (billboard mod) must be placed in the visual materials. And the last important thing is that the parameters of the materials must be controlled by the node of the particle system 3D

### Steps to reproduce

A problem with spatial materials, especially in parameters, specifically in (billboard mode)

**Comment by Calinou** [comment]
@yasser5elmedlaa Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
