### ISSUE TITLE
Can't Embed .pck when using rcedit to change ICO.

### ISSUE THREAD

**Issue by RitleHub** [godotengine/godot#62109]
### Godot version

3.4.4 Stable Official

### System information

Windows 10, gtx 1660 super, GLES3, AMD Ryzen 5 3500x

### Issue description

After exporting an embed .pck project that O set its icon using rcedit and setting the path to icon in the export option, I get an error when trying to open the exported file.

![image](https://user-images.githubusercontent.com/89964227/174078228-b78e872b-b4cc-4fc4-aa36-215808a1da15.png)

**The error:**

![image](https://user-images.githubusercontent.com/89964227/174078507-f57067f3-8258-459c-b3c9-e70513bd587e.png)

Is it possible to fix? Or do I have to choose between embed .pck or my custom icon?

Notes
* I use Godot's 3.4.4 export template

### Steps to reproduce

1) I Set up an ICO file with these sizes. (256x256, 128x128, 64x64, 48×48, 32x32, 16x16)

2) Followed to docs to reference rcedit, and change icon path in the export options.
https://docs.godotengine.org/en/3.5/tutorials/export/changing_application_icon_for_windows.html

**Comment by bruvzg** [comment]
It should be fixed in `3.5` and `4.0`. For `3.4` you can work it around by adding an icon to the copy of template executable manually and setting it as a custom template in the export settings.

**Comment by akien-mga** [comment]
Closing as per the above comment.

**Comment by anderlli0053** [comment]
> It should be fixed in `3.5` and `4.0`. For `3.4` you can work it around by adding an icon to the copy of template executable manually and setting it as a custom template in the export settings.

Do you maybe know which pull request does close / fix this issue?  Can you paste the Issue ID?

**Comment by bruvzg** [comment]
> Do you maybe know which pull request does close / fix this issue? Can you paste the Issue ID?

https://github.com/godotengine/godot/pull/60580 + https://github.com/godotengine/godot/pull/60752 (3.5)
https://github.com/godotengine/godot/pull/56093 + https://github.com/godotengine/godot/pull/60751 (4.0)

**Comment by anderlli0053** [comment]
> > Do you maybe know which pull request does close / fix this issue? Can you paste the Issue ID?
> 
> #60580 + #60752 (3.5) #56093 + #60751 (4.0)

Thank you
