### ISSUE TITLE
Doc: older UI in “Learning step by step” [enhancement]

### ISSUE THREAD

**Issue by palrogg** [godotengine/godot#6210]
The [“learning step by step”](http://docs.godotengine.org/en/latest/tutorials/step_by_step/_step_by_step.html) pages are great but some parts use older versions of Godot:

* older version of scene inspector in [Instancing, step by step](http://docs.godotengine.org/en/latest/tutorials/step_by_step/instancing.html#instancing-step-by-step)
 (I had to click the button with a link icon, instead of "plus", which now adds a node)  → <img width="240" alt="scene_inspector" src="https://cloud.githubusercontent.com/assets/12730304/17823836/ac5250d6-662c-11e6-90a1-1c69ac234e08.png">
* .scn instead of .tscn scene in [Instancing](http://docs.godotengine.org/en/latest/tutorials/step_by_step/instancing.html) and [Scripting](http://docs.godotengine.org/en/latest/tutorials/step_by_step/scripting.html)

If it may be useful, I can extend this list, as I'm going through these tutorials right now.

Thanks a lot for your work!

[Edit: typo]

**Comment by vnen** [comment]
Moved to demo repository: godotengine/godot-docs#228.
