### ISSUE TITLE
Godot 3.5 - Changing Node Visibility While Physics Interpolation Active Dramatically Increases Draw Calls

### ISSUE THREAD

**Issue by daniel-abbott** [godotengine/godot#62111]
### Godot version

108792a62d3be1b7985d970506b40ec646705f3e

### System information

Windows 10, GLES3 and GLES2, NVIDIA GeForce RTX 3070 Laptop GPU/PCIe/SSE2

### Issue description

Commit 54a4806a06c1f336cfa25c23192e83e0764dcc1a introduces a bug where draw calls will increase dramatically when node visibility is set false and then true while physics interpolation is active. The increase in draw calls is not cumulative, however it appears to be permanent once visibility has been changed.

In the small reproduction project included, using the GLES3 backend, draw calls will start at 4 (expected), drop to 0 when all nodes hidden (expected), but then increase permanently to 19 when nodes are visible again (hiding and then showing again will remain at 19 calls). Naturally, this will be more pronounced in GLES2 because this scene includes lights. This can quickly lead from dozens or hundreds of draw calls becoming thousands, and massively impact rendering performance.

### Steps to reproduce

Hide/show nodes in an actively running scene with physics interpolation enabled, and make sure there's a way to see active draw calls.

### Minimal reproduction project

[visibility_interpolation_bug.zip](https://github.com/godotengine/godot/files/8919558/visibility_interpolation_bug.zip)

**Comment by clayjohn** [comment]
cc @lawnjelly

**Comment by akien-mga** [comment]
Fixed by #62211.
