### ISSUE TITLE
Right click on an instance / object in the Scene tree and "Copy path" to then paste in script editor

### ISSUE THREAD

**Issue by therealrobster** [godotengine/godot#6211]
**Operating system or device - Godot version:**
Any OS

**Issue description** (what happened, and what was expected):
I'm regularly finding reference to instances using get_node("").  I would love to be able to right click on an instance in my scene tree and "copy path" so I can paste it into the script editor without having to work it out in my head.  It would speed up the workflow and reduce errors.

**Comment by reduz** [comment]
ah, I made it so it's now possible to drag it, but forgot that, will add it
the next days

**Comment by therealrobster** [comment]
Dragging is even better.  Great idea.  Thank you

**Comment by akien-mga** [comment]
I think this was implemented in the current master branch, right?

**Comment by Calinou** [comment]
This feature has been implemented in Godot 3.0, so I'm closing this issue. You can also drag-and-drop the node onto the script editor.

!["Copy Node Path" in the scene tree context menu](https://user-images.githubusercontent.com/180032/38617444-61912042-3d97-11e8-99bb-79facdf10327.png)
