### ISSUE TITLE
MultiplayerSynchronizer using a ton of bandwidth with a SceneReplicationConfig of only spawn

### ISSUE THREAD

**Issue by cridenour** [godotengine/godot#62127]
### Godot version

v4.0.alpha10.official [4bbe7f0b9]

### System information

Windows 10

### Issue description

From my understanding of the new system, a MultiplayerSynchronizer is required on nodes spawned with MultiplayerSpawner to keep their attributes in sync. However, in my game there are nodes that are spawned that only need a single sync. 

Given the spawn/sync distinction in the SceneReplicationConfig, I have set up these attributes to sync on spawn. However, even when the SceneReplicationConfig is only spawn variables, there is a huge amount of bandwidth being used as the number of nodes add up. Setting the interval on these synchronizers to 5s will obviously reduce bandwidth but I would think it shouldn't be using any at all.

### Steps to reproduce

Launch attached project (I adapted the project from #62027 for simplicity). Use Debug -> Run Multiple Instances. 

Run one as a host (using the in game menus) and have the others join. Then watch the network of the host and watch the bandwidth skyrocket as more "static" scenes are replicated, despite not needing any syncing. 

### Minimal reproduction project

[godot-sync-bandwidth-concern.zip](https://github.com/godotengine/godot/files/8924520/godot-sync-bandwidth-concern.zip)

**Comment by fire** [comment]
@cridenour Someone mentioned this was a good example of using the MultiplayerSynchronizer. Would you be interested in submitting it as a demo?

@aaronfranke Can tell you more if you're interested.

**Comment by cridenour** [comment]
Yea - I would love to. I adapted another issue's project for this one and added chaotic spawning but I can clean it up / start a simple one with a network manager and couple types of spawn/sync.

**Comment by GregHilston** [comment]
@cridenour As someone who's experimenting with Godot 4 Alpha 13, and experiencing what I believe is a bug, a simple example of how you have spawn/sync setup would be super appreciated!

Once I work through my issue, I'm looking to package up a repo of the game Pong and write up an example how Godot 4 networking myself.

**Comment by cridenour** [comment]
@GregHilston I think we were talking on Discord about your issue a couple days ago - I don't have any other demo projects right now. 

Let me know if you file a bug with a minimum reproduction - I can take a look and test as well.

**Comment by GregHilston** [comment]
@cridenour Oh, I apologize, I did not recall your handle. My bad.

Understood, I'll create a minimum project highlighting my issue when I'm back at my desktop. Appreciate your willingness to look it over :)

**Comment by cridenour** [comment]
@GregHilston no worries - I doubt they are even the same.

**Comment by GregHilston** [comment]
Oh yeah, I do not think I'm having the same issue as this original comment mentioned. I was more so commenting on a minimum viable networking example. Sorry for the confusion

**Comment by nathanfranke** [comment]
In case it helps i updated the bomber demo in godot demo projects for the latest multiplayer. PR is still open.

**Comment by GregHilston** [comment]
@nathanfranke okay awesome, thanks for letting me know. I'll look for that example and work through what it does differently than what I do.

Thanks so much!

**Comment by GregHilston** [comment]
@cridenour I ended up posting this issue:

https://github.com/godotengine/godot/issues/64129

I didn't minimize it, but its just a pong example with not much going on.
