### ISSUE TITLE
Navigationagent3d stop moving after alpha 8

### ISSUE THREAD

**Issue by Asarmir** [godotengine/godot#62129]
### Godot version

4.0 alpha 10

### System information

HP Pavilion Gaming Latop 15-dk0xx windows 11

### Issue description

NavigationAgent3d follow player just fine from godot 4.0 alpha 3 to 8. When alpha 9 came out agent became a rock and stood still. Waited until alpha 10 to see if it was a glitch in the martix. Alpha 10 still stands still.

 I am still a novice at coding but in alpha 8 this line var velocity = (target - global_transform.origin).normalized() * moveSpeed will change the vector3 every tick on _physics_process. However in alpha 9 and 10 when veolcity is printed it stays the same vector3 every tick never changing.

### Steps to reproduce

```gdscript
look_at(Target.global_transform.origin, Vector3.UP)
$NavigationAgent3D.set_target_location(Target.global_transform.origin)
		
if $NavigationAgent3D.distance_to_target() <= 0.6: 
	set_velocity(Vector3.ZERO)

elif $NavigationAgent3D.is_target_reachable():
	var target = $NavigationAgent3D.get_next_location()
	var velocity = (target - global_transform.origin).normalized() * moveSpeed
	$NavigationAgent3D.set_velocity(velocity)
			
	move_and_slide()
```

### Minimal reproduction project

Sorry for the delay. It was midnight and my brain wasn't going to let me build the file. I have recreated the issue. Tested and navigation agent follows in alpha 8 but does not follow in alpha 10.
[AgentNavi.zip](https://github.com/godotengine/godot/files/8927292/AgentNavi.zip)
_

**Comment by Chaosus** [comment]
cc @smix8

**Comment by Calinou** [comment]
@Asarmir Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by smix8** [comment]
This is not a navigation bug. There were some changes to the physics `CharacterBody3D` in the alphas.

Your `velocity` should be red colored in the script editor. This tells you that the `var velocity` in your script overshadows the `velocity` member of the `CharacterBody3D`, rename it to something else.

**Comment by Asarmir** [comment]
It did not give me a red color for velocity. It was a blue - teal color. Also there was no warning due to it overshadowing. I tired to rename the variable and it still does not move.

 However, I went back and name velocity per your suggestion vel set $naviagent.set_velocity(vel) then added the line velocity = vel.... now it's working. I feel like a moron.  Sorry for the trouble. Thanks smix8

so the code now looks like this:

look_at(Target.global_transform.origin, Vector3.UP)
$NavigationAgent3D.set_target_location(Target.global_transform.origin)
		
if $NavigationAgent3D.distance_to_target() <= 0.6: 
	set_velocity(Vector3.ZERO)

elif $NavigationAgent3D.is_target_reachable():
	var target = $NavigationAgent3D.get_next_location()
	var vel = (target - global_transform.origin).normalized() * moveSpeed
	$NavigationAgent3D.set_velocity(vel)
        velocity = vel
			
	move_and_slide()

**Comment by Asarmir** [comment]
Nope I'm a lair. Godot gave me a warning but I ignored it in ignorance. My deepest apologize.
