### ISSUE TITLE
Error in console when open Godot

### ISSUE THREAD

**Issue by mefihl** [godotengine/godot#6214]
**Operating system or device - Godot version:**
Windows 10, Godot https://github.com/godotengine/godot/commit/6efbe9342a35584ff410f3c016ad1c219729d9c9

**Issue description** (what happened, and what was expected):
![99999999999999999999](https://cloud.githubusercontent.com/assets/5302754/17830095/e0724430-66c1-11e6-8a40-6cf0c916cca0.png)

**Steps to reproduce:**
Open Godot, look console window.

**Link to minimal example project** (optional but very welcome):

**Comment by vnen** [comment]
Related to #5733.
