### ISSUE TITLE
Godot keeps rearranging scene animation frames

### ISSUE THREAD

**Issue by MrTanoshii** [godotengine/godot#62143]
### Godot version

v3.4.4.stable.mono.official [419e713a2]

### System information

Win10

### Issue description

Godot keeps rearranging the scene animation frames

Screenshot of `MainLevel.tscn` git changes
![Screenshot 2022-06-17 151532](https://user-images.githubusercontent.com/47116127/174289099-31f473bd-cf8b-4c87-89f9-74573e0d50d6.png)

It will also at random include or exclude the space between the animations closing curly and square brackets, that is
```
animations = [ { ..... }]
```
or sometimes
```
animations = [ { ..... } ]
```

### Steps to reproduce

- Close and Reopen project containing a scene with `AnimatedSprite` containing multiple animations playing
- Play the game

**Comment by Calinou** [comment]
@MrTanoshii Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by MrTanoshii** [comment]
Here you go~

[literate-couscous.zip](https://github.com/godotengine/godot/files/8927778/literate-couscous.zip)

![Screenshot 2022-06-17 172331](https://user-images.githubusercontent.com/47116127/174306876-fa7cdd4a-bf7c-492a-8618-40615f0dd204.png)

Note: GitHub has amazing name suggestions

**Comment by Listwon** [comment]
I've just encountered the same issue (rearranging frames leading to unnecessary changes in scene file) in non-mono v3.4.4.stable. It seems like while we are adding new animations (with animation frames editor open), they are sorted alphabetically, but later (saving scene without animation frames dock open) rearranged using other type of sorting.

**Comment by akien-mga** [comment]
Fixed by #62977.
