### ISSUE TITLE
unable to launch Godot 4 alpha9 

### ISSUE THREAD

**Issue by tonybamm** [godotengine/godot#62141]
### Godot version

version 4 - alpha 9

### System information

Ryzen 5600H, Windows 11, RTX-3060 (Latest Driver) Laptop

### Issue description

Cannot launch Godot 4 alpha 9. Following Error during launching:
Assertion Failed
Program:...
File: thirdparty/vulkan/vk_mem_alloch
Line: 14054
![image](https://user-images.githubusercontent.com/15382811/174281342-50707a2f-9ec6-4aa4-a82a-a2800b69d180.png)

### Steps to reproduce

Just launch the Godot_v4.0-alpha9_win64.exe

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/57708. Check the solutions outlined in that issue.
