### ISSUE TITLE
The editor cannot interact when AcceptDialog is root and its visible property is enabled (DisplayServer regression)

### ISSUE THREAD

**Issue by Rindbee** [godotengine/godot#62145]
### Godot version

v4.0.alpha9.official [fc18891db]

### System information

Linux Mint 20.3, Vulkan, NVIDIA GeForce GTX 1050 Ti

### Issue description

When `AcceptDialog` is root and its `visible` property is enabled, the editor can no longer be interacted with.

The same goes for AcceptDialog derived classes

### Steps to reproduce

1. Adding `AcceptDialog` as root and enabling its `visible` property. 
2. Or make scene root for an `AcceptDialog` with `visible` property enabled.

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/61764.
