### ISSUE TITLE
Add_animation() no longer exists

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot#62140]
### Godot version

4.0 alpha 10

### System information

Linux Manjaro, Vulkan, Intel Kaby Lake

### Issue description

I was using add_animation() (in a script inheriting AnimationPlayer) to create animation from code (for a replay system)

In alpha 10, this function no longer exists. I think it's a bug, since remove_animation() is still a thing. 

Probably an unintended side effect of the PR that added animation libraries?

### Steps to reproduce

Attempt to use add_animation(), see script error

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
`add_animation()` is now part of AnimationLibrary and is exposed to scripting: https://github.com/godotengine/godot/blob/362f53ff02c381ea94640baa16e84e6f6956efef/doc/classes/AnimationLibrary.xml#L10-L16

**Comment by Zireael07** [comment]
What about remove_animation() then? Why can we only add animations via AnimationLibrary but remove them directly in player?

**Comment by TokageItLab** [comment]
Since the path to the AnimationLibrary can be specified with `/`, it seems like it could exist in AnimationPlayer as a function that parses the path and adds the Animation to the AnimationLibrary.

**Comment by timothyqiu** [comment]
> I think it's a bug, since remove_animation() is still a thing

`remove_animation()` is not there as of `alpha 10`. (Argument hint setup for `remove_animation` still exists though.)

**Comment by Zireael07** [comment]
@timothyqiu: Good point, that was me being misled by the hint.

**Comment by TokageItLab** [comment]
These have already been removed from the core.
