### ISSUE TITLE
Crashed (2D)

### ISSUE THREAD

**Issue by Scream034** [godotengine/godot#62155]
### Godot version

4.0.alpha10

### System information

Windows10 GPU: AMDR7250 200 series VULKAN3D

### Issue description

when I change the worldeniv. to canvas the crashed.

### Steps to reproduce

• create the worldeniv.
• change the background to canvas.
• crashed...

### Minimal reproduction project

just change worldeniv/background to _cavnas_ and **crashed**.

**Comment by Scream034** [comment]
please repair it!

**Comment by Scream034** [comment]
please repair it!

**Comment by Zireael07** [comment]
dupe of #62079 (one of the first things that show up when you search for "Canvas" - did you try searching before posting?)

**Comment by Scream034** [comment]
> dupe of #62079 (one of the first things that show up when you search for "Canvas" - did you try searching before posting?)
