### ISSUE TITLE
load_threaded_request() failed to load resources when using sub threads

### ISSUE THREAD

**Issue by TheDeafCreeper** [godotengine/godot#62159]
### Godot version

4.0 Alpha 9

### System information

OS: EndeavourOS Linux x86_64 | Kernel: 5.18.3-arch1-1

### Issue description

When loading resources with load_threaded_request() setting use_sub_threads to false successfully loads the resource, however setting it to true causes it to fail.

Expected Result:
    load_threaded_request(X, "", true) loads the resources at path X to be retrieved with load_threaded_get()

Actual Result:
    load_threaded_request(X, "", true) causes the following error(s) to occur:
```
ERROR: res://Assets/sprite_frames/chevalier/ChestDefault.tres:1926 - Parse Error: [ext_resource] referenced nonexistent resource at: res://Assets/player_classes/chevalier/chestDefault/sprites/idle/67.5Degrees-frame01.tres
   at: _parse_ext_resource (scene/resources/resource_format_text.cpp:159)
ERROR: res://Assets/sprite_frames/chevalier/ChestDefault.tres:1926 - Parse Error: [ext_resource] referenced nonexistent resource at: res://Assets/player_classes/chevalier/chestDefault/sprites/idle/67.5Degrees-frame01.tres
   at: load (scene/resources/resource_format_text.cpp:704)
ERROR: Failed loading resource: res://Assets/sprite_frames/chevalier/ChestDefault.tres. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:205)
```

Other Notes:
The resources failing to load are (from what I can see) SpriteFrames and AtlasTextures.

When making the minimum reproduction project using sub threads started working once I deleted enough stuff so maybe it's related to the size of some of the resources?

### Steps to reproduce

You should just be able to download then open and run the minimal reproduction project.

### Minimal reproduction project

[MinimalProject.zip](https://github.com/godotengine/godot/files/8931353/MinimalProject.zip)

**Comment by tinmanjuggernaut** [comment]
@Calinou Can this get added to the gd4 roadmap?

I have the same issue in 52aae6d4f. Win11/64.

I also have an MRP I can upload if desired. It has only a few objects. subthreads = false seems to work ok. Subthreads = true, and **different objects** fail to load each time, **with different error messages**. The loaded scene runs fine without error messages by itself. But when loaded w/ subthreads it suddently can't access perfectly valid resources, randomly. 

Example errors. Notice the last line, which only sometimes appears.

```
ERROR: Threading loading resource'res://assets/shield/WoodShield.tres failed: Source specified: 'res://assets/shield/WoodShield.tscn' but was not called by it.
   at: (core/io/resource_loader.cpp:317)
ERROR: res://assets/shield/WoodShield.tscn:3 - Parse Error: [ext_resource] referenced broken resource at: res://assets/shield/WoodShield.tres
   at: load (scene/resources/resource_format_text.cpp:472)
ERROR: Failed loading resource: res://assets/shield/WoodShield.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:221)
ERROR: res://GameScene.tscn:68 - Parse Error: [ext_resource] referenced nonexistent resource at: res://assets/shield/WoodShield.tscn
   at: _parse_ext_resource (scene/resources/resource_format_text.cpp:165)
WARNING: Node './WoodShield' was modified from inside an instance, but it has vanished.
     at: instantiate (scene/resources/packed_scene.cpp:178)

```

**Comment by RandomShaper** [comment]
I may be able to check this one.
