### ISSUE TITLE
`animate_physical_bone` is now limited to editor only, but it should be able to be used in the running project

### ISSUE THREAD

**Issue by hakuhan** [godotengine/godot#62166]
### Godot version

4.0

### System information

Windows 11

### Issue description

![image](https://user-images.githubusercontent.com/18411187/174422547-e6fe9796-4f13-4ec8-b13a-0a688d112fba.png)
Skeleton3d has animate_physical_bone property. And it can make physical bones animated. But now it just work at editor. I tried to commets these "editor only" codes. And functions for Skeleton3D works fine. Please check it.

### Steps to reproduce

1. Create physical bone as tutorial.
2. Set collision showing.
3. You can see that physical bone not animated. (animate_physical_bone value is true defaultly)

**Comment by hakuhan** [comment]
![image](https://user-images.githubusercontent.com/18411187/174423055-187ed5b1-3787-4f5f-b0cf-4a3be3a09772.png)
This is the version cause this issue(Not working for my needs:))

**Comment by Calinou** [comment]
> 4.0

There is no 4.0 stable release yet. Which alpha release or commit hash are you using?

**Comment by hakuhan** [comment]
> > 4.0
> 
> There is no 4.0 stable release yet. Which alpha release or commit hash are you using?

Hi! I test it at alpha 10. I checked the history of this change and I think it appeared 10 month ago.

**Comment by Calinou** [comment]
This change was made by https://github.com/godotengine/godot/commit/5ffed49907618e3c7e7e2bddddcc8449d0b090a6. cc @TwistedTwigleg

**Comment by TwistedTwigleg** [comment]
I unfortunately do not have time to look into this, or really anything Godot development related currently. That said, the change to make the bones animate only in the editor was unintentional though, I'm not sure why I changed it when I made the IK stuff. I think it can be safely reverted.

**Comment by hakuhan** [comment]
I comment "is_editor_hint". And animate_physical_bone works. I have no idea who can finally modify it. I just tested animate physical bone.

**Comment by Calinou** [comment]
> I comment "is_editor_hint". And animate_physical_bone works. I have no idea who can finally modify it. I just tested animate physical bone.

Feel free to open a pull request for this :slightly_smiling_face:

**Comment by hakuhan** [comment]
Hi! @TwistedTwigleg. Can I ask you to review my pull request for this modification?

**Comment by TwistedTwigleg** [comment]
I can review it if you link it. I cannot test it though, my machine is not setup for compiling Godot source currently.
