### ISSUE TITLE
[Godot 4] Display bug when removing current editor feature.

### ISSUE THREAD

**Issue by njdf18** [godotengine/godot#62165]
### Godot version

v4.0.alpha.mono.custom_build (2a92176)

### System information

Windows11, Vulkan, NVIDIA GT 1050 Ti

### Issue description

As what I mentioned in the title.

### Steps to reproduce

![bug3](https://user-images.githubusercontent.com/86307226/174422141-edf8850e-3c12-4e57-8f19-597091f19281.gif)

### Minimal reproduction project

(Maybe No Need)

**Comment by KoBeWi** [comment]
Doesn't seem to be happening anymore.
