### ISSUE TITLE
It's impossible to change physic mode for instanced/inherited physic objects

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#6216]
**Operating system or device - Godot version:**

**Issue description** (what happened, and what was expected):
If you create a scene with physic object node as a root, and then you instance it, you will be unable to change physic mode in this instanced scene: 
![instancedbodiesproperties](https://cloud.githubusercontent.com/assets/6129594/17830971/3cf50092-66dd-11e6-9d2f-d8b7e65514e2.gif)

**Steps to reproduce:**
1. Create a scene with a rigid body as a root.
2. Instance this scene and change physic mode
3. (optionally) Inherit scene from 1 and change physic mode, then instance it.

**Link to minimal example project** (optional but very welcome):
[InstancedPhysicPropertyNotUpdated.zip](https://github.com/godotengine/godot/files/428261/InstancedPhysicPropertyNotUpdated.zip)

**Comment by kubecz3k** [comment]
retested today on  e12b422c90f3f866d133ea5ab797fb37f675e019  (3.0 alpha). 
It's still valid. 
Created new reproduction project for 3.0: 
[issue: Physic mode change in instance.zip](https://github.com/godotengine/godot/files/1205421/issue.Physic.mode.change.in.instance.zip)

**Comment by pwab** [comment]
Saw this issue on the #4778 tracker list.
Tested the provided reproduction project with **3.0 beta2** and can confirm the issue only for **GodotPhysics**.

![issue-6216-beta2](https://user-images.githubusercontent.com/19271185/34650940-7cf32da2-f3c9-11e7-97c6-6356b41d0614.png)
