### ISSUE TITLE
InputEventScreenTouch and InputEventMouseButton mismatch bug

### ISSUE THREAD

**Issue by Lasuch69** [godotengine/godot#62161]
### Godot version

3.4.4 Flatpak, 4.0 alpha 10

### System information

Fedora 35 Linux

### Issue description

When i tried to create joystick for a mobile game i encountered issue with godot mismatching events in an if statement.

![Screenshot_20220618_000534](https://user-images.githubusercontent.com/71460040/174406904-773f496e-15d4-4160-a3c3-9f430bbd87d2.png)

In this if statement i want to only run this code if the event is touch input related. Meanwhile godot passes mouse related events too, even with every emulation disabled. Resulting in instant crash when accessing index because (it is done on unwanted event in the first place).

Sadly this bug is impossible at least for my implementation to workaround and is critical for development because without touch control for debug on mobile i can't do much.

### Steps to reproduce

Emulation from touch to mouse or other way around doesn't matter on or off. To reproduce try to filter in an if statement touch related events, you will notice that it doesn't work.

### Minimal reproduction project

Godot 4.0 alpha 10 project [Bug.zip](https://github.com/godotengine/godot/files/8931598/Bug.zip)

**Comment by KoBeWi** [comment]
While the mouse part sounds like a bug (although maybe not if you are doing it on desktop...), you have an error in your code. You forgot `is` before `InputEventScreenTouch`.

**Comment by Lasuch69** [comment]
> 

lmao i'm going to sleep
