### ISSUE TITLE
Immersive mode not working (Android)

### ISSUE THREAD

**Issue by pfspace** [godotengine/godot#62169]
### Godot version

3.5 RC4

### System information

Android 8, 9 and 10

### Issue description

The immersive mode is not working. The status bar is always visible.
Worked fine on 3.5 RC 2 and  RC 3.

Thank you.

### Steps to reproduce

Just export the project

**Comment by Calinou** [comment]
Possible regression from https://github.com/godotengine/godot/pull/61472. cc @madmiraal

**Comment by madmiraal** [comment]
@pfspace, please provide an MRP which includes your `export_presets.cfg`, because it works fine for me.

#61472, provided a fix that will display the status bar (as well as the navigation bar) if the Android export setting `screen/immersive_mode` is disabled.

**Comment by pfspace** [comment]
@madmiraal probably my mistake, I'm sorry. Immersive mode box was not checked at the export template. 

I never checked that box before and the all the projects worked in immersive mode when exported from 3.4.4, 3.5 RC2 and 3.5 RC3.

In the end, that checkbox wasn't working before and I was unaware of it. It works now and I thought it was a bug. lol

My bad, I'm sorry.

Thank you.
