### ISSUE TITLE
Pausing tree disables white-listed `Area2D`'s signals

### ISSUE THREAD

**Issue by markdibarry** [godotengine/godot#62180]
### Godot version

3.5 RC4

### System information

Windows 10

### Issue description

When pausing the scene tree, and an `Area2D` is white-listed to process while paused, the `body_entered` signals are not fired.

https://user-images.githubusercontent.com/21325943/174443994-07604fb1-872c-4970-9832-774e41b76f69.mp4

### Steps to reproduce

1. Create a scene with a white-listed branch.
2. Have the branch contain a moveable body and `Area2D`
3. Set `Area2D`'s `body_entered` signal to notify when body has entered.
4. pause tree and move body over `Area2D`

### Minimal reproduction project

[CollisionBug.zip](https://github.com/godotengine/godot/files/8933823/CollisionBug.zip)

**Comment by Zireael07** [comment]
I believe this has already been reported.

**Comment by markdibarry** [comment]
I looked through https://github.com/godotengine/godot/issues/45334 but I couldn't find it.

**Comment by Zireael07** [comment]
https://github.com/godotengine/godot/issues/61420 I think is what I remember. Not all issues are listed on the tracker

**Comment by markdibarry** [comment]
Ah! That one is specific to 4.0, and has a different result with the new pause system, causing the signal to be removed entirely or throw errors.

**Comment by lapspider45** [comment]
Workaround: call `Physics2DServer.set_active(true)` after pausing the tree.

A side effect of `get_tree().paused = true` is to disable the physics engine. It is documented, just not very clearly:
https://docs.godotengine.org/en/stable/classes/class_scenetree.html#class-scenetree-property-paused

**Comment by markdibarry** [comment]
Hm. This does resume the physics server, but still seems like an unintentional side-effect. It's a far-reaching workaround, because with the pause system currently, it means either:
1. White-listed nodes don't behave as white-listed (physics disabled for all).
2. Paused nodes don't behave as paused (physics enabled for all).

**Comment by Calinou** [comment]
I don't think this can be resolved unless something like https://github.com/godotengine/godot/pull/46191 is backported in a backwards-compatible manner, which sounds too difficult to do.

**Comment by markdibarry** [comment]
@Calinou The mentioned rewrite introduces it's own set of (worse?) `Area2D` bugs (mentioned a few comments above), but you're absolutely right. It's probably not worth spending the effort to backport the fix to 3.x in the long-run and just focus on 4.0. It seems like, for now, the best solution is either a custom pause system in 3.x or wait for `Area2D` to be fixed in 4.0.

As reference for anyone else who needs to be able to pause in 3.x without this bug, nodes have the following methods you can use to emulate a custom system, by iterating through a branch:
`set_physics_process()`
`set_physics_process_internal()`
`set_process()`
`set_process_internal()`
`set_process_input()`
Keep in mind it can be brittle so node reparenting should be kept to a minimum.

**Comment by markdibarry** [comment]
Closing since it can't be fixed in 3.x
