### ISSUE TITLE
Ability to refresh editor Filesystem tree from plugin

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#6219]
**Operating system or device - Godot version:**

**Issue description** (what happened, and what was expected):
Basically I have created plugin with witch user is able o create new folder with scene and script file. Unfortunately those new folders/files are invisible. To make them visible user need to un-focus godot editor and focus it again. 

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by reduz** [comment]
A tracker for plugin feature requests would be great

**Comment by kubecz3k** [comment]
@reduz roger that! Will create one in Monday, in meantime you can just use  'plugin' label: https://github.com/godotengine/godot/labels/topic:plugin

**Comment by kubecz3k** [comment]
Not all of this are the job for you hovewer, since we were also used to label with this label issues which can be _resolved_ by external plugin.

**Comment by vnen** [comment]
Now you can use `EditorFileSystem.scan()` for this.
