### ISSUE TITLE
low_processor_usage_mode documentation differs in project settings dialog tooltip and online documentation and in editor documentation

### ISSUE THREAD

**Issue by dorjoosoft** [godotengine/godot#62202]
### Godot version

3.5.RC4

### System information

windows 10

### Issue description

**low_processor_usage_mode** documentation differs in project settings dialog tooltip and online documentation and in editor documentation. In project setting tooltip and online documentation it says "this setting only works on desktop platforms" but in offline documentation it says that "can improve battery consumption on mobile".

![Screenshot (3)](https://user-images.githubusercontent.com/3175411/174468065-f84e037f-8ef1-4c99-a821-c93f5a46558c.png)
![Screenshot (4)](https://user-images.githubusercontent.com/3175411/174468067-ec25c927-c1fb-4beb-866d-d5908b8c7cf1.png)

### Steps to reproduce

just read and compare highlighted parts of attached images.

**Comment by Calinou** [comment]
Low processor mode used to be discouraged for use on mobile platforms, but it's been fixed in 3.5: https://github.com/godotengine/godot/pull/59606

The online class reference is only tracking 3.4 currently. It will track 3.5 once a stable version is released.
