### ISSUE TITLE
Godot method ToSignal not working, or working badly on C#

### ISSUE THREAD

**Issue by solar-core** [godotengine/godot#62229]
### Godot version

3.4.4-stable.mono

### System information

Windows 11, GLES3, Nvidia 3070

### Issue description

I am rewriting a small project from a gdscript to C#, and i have an issue in HUD.cs, there is a method ```await ToSignal(_messageTimer, "timeout");``` that when we reach it, it just do nothing, the timer is set to 5 second, but nothing happing after the timeout. And i have added 
```
public override void _Process(float delta)
{
	Console.WriteLine(_messageTimer.TimeLeft);
}
```
into HUD.cs to see the timer TimeLeft, but when i reach the ToSignal, it just stops on 5 seconds

### Steps to reproduce

1-Download Minimal reproduction project
2-Press start button
3-Wait 5 seconds (It's another timer, not the HUD timer)
4-Gray screen appears(This is the error)
5-You can look at the console logs, to see it will stuck at 5 seconds
6-Also you could set break point after the ToSignal method, to see that it's not reachable

### Minimal reproduction project

[Coin Dash project.zip](https://github.com/godotengine/godot/files/8936291/Coin.Dash.project.zip)

upd: edited godot version

**Comment by Calinou** [comment]
> 4.4-stable

Did you mean 3.4-stable?

Note that the latest version available is 3.4.4. I recommend upgrading first to see if the issue has bee nresolved there.

**Comment by solar-core** [comment]
@Calinou Sorry, edited the version.
Yes i am testing it on 3.4.4 
![image](https://user-images.githubusercontent.com/57063825/174498799-5472f6d1-ae13-4d79-99b2-39bf5cdfb689.png)

**Comment by raulsntos** [comment]
The timer is never firing the `timeout` signal because you free it with the rest of the scene. The gray screen you describe is the clear color since you destroy the root node of your scene so there's nothing. In the `Main.GameOver` method you are calling `QueueFree` on the `Main` instance instead of on the `child` variable.

```csharp
private void GameOver()
{
	_playing = false;
	_gameTimer.Stop();
	foreach (var child in _coinContainer.GetChildren())
	{
		if (child is Coin)
		{
			// This part is calling QueueFree on the Main instance, it's the same as this.QueueFree()
			// You should be calling ((Node)child).QueueFree()
			QueueFree();
		}
		else
		{
			const string message = "Coin is null!";
			GD.PushError(message);
			throw new NullReferenceException(message);
		}
	}

	_hud.ShowGameOver();
	_player.Destroy();
}
```

In case of any doubts please reach for help in other [Community channels](https://godotengine.org/community) (like Q&A / Discord / Reddit etc.) first. This is a bug tracker, not a place to ask for help.
