### ISSUE TITLE
Scene Unique Name disables itself randomly

### ISSUE THREAD

**Issue by winston-yallow** [godotengine/godot#62228]
### Godot version

v3.5.rc4.official [e047c5006]

### System information

Debian GNU/Linux 11 (bullseye)

### Issue description

I use the new "Scene Unique Name" feature quite a lot in my GUI scenes, and sometimes the checkbox just unchecks itself randomly and the node is not accessible via `%` anymore. The fix in those cases is simply to re-enable it, but it is a bit annoying.

### Steps to reproduce

I am honestly not sure as this appears to be a bit random to me. I made a new project from scratch with just a few nodes and weren't able to reproduce it, but then after a while it unchecked itself again. No clue what exactly caused this, I was just looking around in the interface and then ran the project again. Wasn't able to really come up with a reliable reproduction.

**Comment by KoBeWi** [comment]
Maybe you clicked the % icon in scene tree? It removes the flag.

**Comment by winston-yallow** [comment]
Arghhhhh ok, uhm, kinda embarrassing. I was apparantly clicking on it by accident and didn't notice immediately. I'm not used to stuff there disabling settings (before scene unique names at worst it would be a script that opens). So I guess due to my muscle/visual memory I just clicked at positions that previously didn't had any effect. Now that I am aware of this, I didn't encounter the ~~bug~~ *feature* again...

I wonder if a popup confirmation would be good? Anyway, that would be more fit as a proposal so I'll close this
