### ISSUE TITLE
`RefCounted<T>` are not freed in C#

### ISSUE THREAD

**Issue by markdibarry** [godotengine/godot#62224]
### Godot version

4.0.dev (728e8de)

### System information

Windows 10

### Issue description

This combines previous bug reports highlighting `Tween`, `Material`, and `Resource` memory leaks.

As @raulsntos pointed out, the current issue is instances inheriting from `RefCounted<T>` are never freed and are never collected by the GC, even when forcing collection. This is visible in the Godot monitor, viewing that `Object`s stay in memory and `Resource` count only goes up.

### Steps to reproduce

Use an instance of something inheriting from `RefCounted<T>`, like `Tween`, `Material`, or `Resource`.
Let its reference count go to 0.
Collect GC manually.
Object/Resource count does not decrease.

### Minimal reproduction project

This tween MRP should be sufficient, but occurs with any `Resource`, `Material`, etc.

[TweenBug4.zip](https://github.com/godotengine/godot/files/8935861/TweenBug4.zip)

**Comment by GeorgeS2019** [comment]
@raulsntos should this issue be added into milestone 4.0?

**Comment by GeorgeS2019** [comment]
@markdibarry 

Please check[ if this is related](https://github.com/godotengine/godot/issues/59585)?

**Comment by markdibarry** [comment]
This will be solved in master/4.0 once https://github.com/godotengine/godot/pull/64089 is merged. Tested as fixed in said branch.

**Comment by neikeq** [comment]
Actually, the PR that fixes this is #64302. The commit is currently included in #64089 to make it more convenient to test, but it should be stripped before merging.
