### ISSUE TITLE
Import Texture3D fail with a 512*16 resolution

### ISSUE THREAD

**Issue by Hannyson** [godotengine/godot#62237]
### Godot version

4.0.alpha10

### System information

Linux Archlinux

### Issue description

Import a 512*16 pixels image in the jpg, png or bmp format, with type Texture3D, fail with the following message :

Data for slice index 0 (mapped to layer 0) differs in size (supplied: 37452) than what is required by the format (37448)

Export of the project works, running the project fail.

### Steps to reproduce

Import a 512*16 image pixels with type Texture3D, with arguments Slices horizontal 32 and Slices vertical 1

**Comment by clayjohn** [comment]
Can you please provide an MRP?

**Comment by Hannyson** [comment]
The problem did go away after restarting godot a few times

**Comment by Hannyson** [comment]
I do not use Texture3D anymore since a long time, I don't know if this problem is still here
