### ISSUE TITLE
"No loader found" error when loading an image file created with Directory.copy( )

### ISSUE THREAD

**Issue by roby405** [godotengine/godot#62232]
### Godot version

3.4.4.stable

### System information

Windows 10

### Issue description

I'm getting the "No loader found for resource: res://folder/grid.png.       at: (core/io/resource_loader.cpp:278)" error when I copy a *.png file in a folder inside res:// and then I load the copied file as a texture in TextureRect. When the scene runs for the first time, I will get this error and the texture remains empty. If I stop the program and run it again, it will work without displaying any errors. This happens every time I copy a new different file to the folder or delete the copied files and recopy them. It works normally when overwriting files.

### Steps to reproduce

Create a scene with just a TextureRect. Attach this script to it with path modifications:

```
extends TextureRect

func _ready():
	var dir = Directory.new()
	var toPath = "path/to/image.png"
	var fromPath = "path/from/image.png"
	dir.copy(fromPath, toPath)
	texture = load(toPath)
```

Run the scene twice. fromPath can be internal or external.

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/8936414/test.zip)

**Comment by KoBeWi** [comment]
The texture needs to be imported before use. Use `Image.load()` if you want to use it immediately.
