### ISSUE TITLE
Starting the editor delay regression

### ISSUE THREAD

**Issue by lawnjelly** [godotengine/godot#62244]
### Godot version

3.x (3.5 RC4?, not present RC3)

### System information

Linux Mint 20.1
Intel Core i5-7500T
8gb RAM
Intel HD Graphics 630

### Issue description

After building the editor after #61995, I noticed that the editor seemed to be taking longer at startup (and the project manager). Switching between "synchronous" and "asynchronous" seems to change the delay.

### Steps to reproduce

Switching from "synchronous" to "asynchronous" seems to create the delay.

Measured startup in debug:
3828 ms (sync)
4278 ms (async)

I haven't thoroughly investigated this, but was worth a mention as any increase in startup time can be problematic for debugging / development.

### Minimal reproduction project

N/A.

**Comment by akien-mga** [comment]
CC @RandomShaper @Calinou

**Comment by RandomShaper** [comment]
What kind of asynchronous support does the editor report on your system? Full native or via secondary context?

**Comment by lawnjelly** [comment]
> What kind of asynchronous support does the editor report on your system? Full native or via secondary context?

Full native support.

**Comment by lawnjelly** [comment]
Ok this is much worse. BeatInvaders which is a more complex game, took:
Async : 16401 ms
Sync: 1977 ms

**Comment by RandomShaper** [comment]
Can you try clearing the shader cache? I have a suspicion.

**Comment by lawnjelly** [comment]
> Shader caching in general tends to have a lot of overhead on the first run, also on 4.0.alpha. I think we'll need to add something like [godotengine/godot-proposals#3657](https://github.com/godotengine/godot-proposals/issues/3657) to 3.x as well.

This isn't just the first run though, even once cached, it still seems quite a bit slower. While it may be advantageous to run in the editor as far as catching bugs is concerned (especially on betas), are there any other advantages? Because if it impedes startup time / stability it might be nice to be able to easily switch it off in the editor / project manager. Should there be a separate setting for editor and for projects?

**Comment by RandomShaper** [comment]
@lawnjelly, @timothyqiu, thanks for the info you provided. I think it all boils down to a change I mistakenly reverted from my last PR.

**Comment by lawnjelly** [comment]
> Might be fixed by #62251, please confirm and close.

Just pulled latest 3.x, unfortunately no change. And no output in `shader_cache` again. I'll look more in the morning.

**Comment by RandomShaper** [comment]
To be sure we're on the same page, is the slowdown the same as before the latest bug my recent PR caused and which was fixed by another? In other words, is the current slowdown the same as when the change to async in the editor was just merged?

**Comment by lawnjelly** [comment]
> To be sure we're on the same page, is the slowdown the same as before the latest bug my recent PR caused and which was fixed by another? In other words, is the current slowdown the same as when the change to async in the editor was just merged?

Yup, delay seems the same.

**Comment by lawnjelly** [comment]
Fixed by #62302 .
