### ISSUE TITLE
No liquid layout on resizing

### ISSUE THREAD

**Issue by iammangod96** [godotengine/godot#6225]
**Operating system or device - Godot version:**
Windows 8.1
Godot v.2.1.stable

**Issue description** (what happened, and what was expected):
When I resize godot only half of the engine is shown to me. What should happen is the most essential parts shown be floated to the resized screen. So right now I am getting this - 
![Please click here to see the image](https://cloud.githubusercontent.com/assets/15985211/17835357/9fc1a1c6-6787-11e6-9995-1af5aa320511.png)

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by Calinou** [comment]
I'm closing this, since it is possible to enable the editor's distraction-free mode if one needs more horizontal space for editing scripts.
