### ISSUE TITLE
important problem in (ٍSpatial Material)

### ISSUE THREAD

**Issue by yasser5elmedlaa** [godotengine/godot#62253]
### Godot version

3.5-rc4

### System information

windows 8.1 - gles(2.0)

### Issue description

(Billboard Mode) in (Spatial Material)  is not working 
![error](https://user-images.githubusercontent.com/24312003/174633878-e28fe4a2-f82a-4438-b884-352e869543a5.PNG)

### Steps to reproduce

It is an important tool for making a Particels system

**Comment by Calinou** [comment]
@yasser5elmedlaa Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by JohanAR** [comment]
[particles_3.5_gles2.0.zip](https://github.com/godotengine/godot/files/9541172/particles_3.5_gles2.0.zip)

Works fine in v3.5 stable on Linux at least, but here's what should ought to be a minimal reproduction problem afaik

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.
