### ISSUE TITLE
Godot will not compile due to an error

### ISSUE THREAD

**Issue by FlavoredCactus** [godotengine/godot#6227]
**Operating system or device - Godot version:**
Windows 10 64bit, https://github.com/godotengine/godot/commit/61cb8fd76c78ce2d27b5738e84c773ae4ec284e1

**Issue description** (what happened, and what was expected):
Build will fail due to:
In file included from platofrm\windows\os_windows.cpp:54:0:
platform\windows\joystick.h:35:20: fatal error: dinput.h: No such file or directory #include <dinput.h>

complilation terminated

should be noted that before the build starts i'm given the message
MSVC not detected, attempting Mingw.
- gcc detected.

I was also able to build a few months back

**Steps to reproduce:**
scons platform=windows

**Link to minimal example project** (optional but very welcome):

**Comment by manokara** [comment]
Well, it seems your MinGW install is missing the DirectX headers. Visual Studio's compiler (MSVC) was not found, but MinGW was. But the way you said it you have Visual Studio installed and it compiled fine before, right? A VS update may have changed something somewhere and scons can't find it anymore.

**Comment by reduz** [comment]
Use mingw-w64. Regular mingw is not supported

**Comment by FlavoredCactus** [comment]
@reduz how would i go about using mingw-w64?
