### ISSUE TITLE
Animation Player doesn't properly save settings

### ISSUE THREAD

**Issue by Ansraer** [godotengine/godot#62287]
### Godot version

4.0 alpha10

### System information

Windows 10, amd 6900XT, vulkan clustered

### Issue description

For some reason saving doesn't properly work for Animation Players. I definitely encountered (and can reproduce) this with the loop option, but suspect that some of the other animation-related bugs I am currently fighting with are caused by this as well.
Might add to this issue once I have a better idea of why stuff isn't working.

When you enable looping for an animation track in the Animation Player Godot correctly detects and indicates that the scene was modified and also behaves properly when you save it: The animation is played in the viewport of the scene itself and in the viewport of any other scenes that use an instance of the scene.

However, when I launch the project with the play button the animation is only played once.
If I restart the editor the animation no longer loops in the viewport either and the loop button has been unclicked.

### Steps to reproduce

Enable looping in the animation player and add a simple animation tree that directly feeds the animation into the output.
The animation should now loop in the viewport. If you now launch the project the animation is only played once.

(Note: During my testing, the animation was from an animation library, not sure if that is relevant)

### Minimal reproduction project

Can't share my assets :sad:

**Comment by Calinou** [comment]
> Where is the loop button located?

On the right of the Animation bottom panel:

![image](https://user-images.githubusercontent.com/180032/175143565-be3dbe62-0bfe-47e9-bf13-ff5cd1a12689.png)

**Comment by Maran23** [comment]
I can't reproduce this, I may have another look tomorrow. 
A Minimal reproduction project would be helpful here. You may can use some dummy assets or the godot icon, in case you don't want to share yours.

**Comment by Ansraer** [comment]
A friend managed to figure out the problem. Apparently whether or not a track is looping is saved in the animation track and not the animation player. This means that I need to enable looping **before** I import the animation library with the import preview window for every animation I want to loop.

If you import an animation library with looping disabled and want to enable it later the button in the bottom panel only temporarily shows the result in the editor preview window.

**Comment by Whimfoome** [comment]
Is this related to [#55002](https://github.com/godotengine/godot/issues/55002)

**Comment by Ansraer** [comment]
Huh, yeah that looks like it might be the same issue. imo the loop button should either be entirely disabled or directly open that popup when clicked, I totally missed that small warning symbol.
