### ISSUE TITLE
Property linking doesn't work in MultiNodeEdit

### ISSUE THREAD

**Issue by fire-forge** [godotengine/godot#62283]
### Godot version

v4.0.alpha10.official [4bbe7f0b9]

### System information

Windows 10

### Issue description

The new property linking feature doesn't work in MultiNodeEdit (https://github.com/godotengine/godot/pull/59125)

It does work in AnimationMultiTrackKeyEdit though.

### Steps to reproduce

* Create a Node2D node
* Select it and edit the x or y of the scale property. Both x and y will change because the property is linked.
* Add another Node2D node.
* Select both of the nodes and edit the x or y of the scale property shown in the inspector. The other axis value will not change, even though they are linked. Toggling the link button does nothing.

This happens with other linked properties as well, such as `Control.scale` and `CanvasLayer.scale`

**Comment by KoBeWi** [comment]
I checked this, but have no slightest idea why would this happen. The linked property gets updated correctly, but then its value is reset, so it appears as if it wasn't changing. Not sure what could be resetting it or why.
