### ISSUE TITLE
Low frame rate in Firefox

### ISSUE THREAD

**Issue by novalis** [godotengine/godot#62296]
### Godot version

v3.4.4.stable.mono.official [419e713a2]

### System information

OpenGL ES 3.0 Renderer: Radeon R9 200 Series (on Firefox 101 on Debian)

### Issue description

Dodge The Creeps runs at a low FPS -- about 35 -- when exported to HTML5 and run in Firefox.  It gets 60 FPS in Chromium (version 103), on the same machine.

My machine is:
AMD Radeon RX 5600 XT (NAVI10, DRM 3.40.0, 5.10.0-14-amd64, LLVM 11.0.1)
AMD Ryzen 5 2600X Six-Core Processor
64 gigs of RAM

### Steps to reproduce

I just replaced the seconds counter in the creeps demo with a FPS counter (using Performance.TIME_FPS).  But probably there's a better way to measure FPS.

**Comment by Calinou** [comment]
Firefox + WebGL + Linux is much slower than Chromium. This is not exclusive to Godot, but it's documented anyway: https://docs.godotengine.org/en/latest/tutorials/export/exporting_for_web.html

There is no workaround for this, except on Wayland.
