### ISSUE TITLE
Menu titled "Create New Animation" when changing animation name

### ISSUE THREAD

**Issue by ratHippo** [godotengine/godot#62315]
### Godot version

3.4.4

### System information

MacOS 12.3

### Issue description

When renaming an animation, the popup menu looks like this:
<img width="230" alt="Screen Shot 2022-06-22 at 5 02 10 PM" src="https://user-images.githubusercontent.com/91836375/175084070-1eeefe28-ea1e-46db-a9da-650bfe4e917c.png">
the menu should be titled something like "Rename Animation" instead.

### Steps to reproduce

1. Create an AnimationPlayer node
2. Create a new animation
3. Rename the animation

**Comment by ratHippo** [comment]
Already fixed by #61106

**Comment by Calinou** [comment]
Reopening, as this should be fixed in Godot 3.x anyway (https://github.com/godotengine/godot/pull/61106 can't be cherry-picked).

**Comment by akien-mga** [comment]
Fixed by #62333.
