### ISSUE TITLE
subviewport environment looks different than normal camera environment

### ISSUE THREAD

**Issue by djmaesen** [godotengine/godot#62316]
### Godot version

4.0 alpha10

### System information

linux

### Issue description

when assigning the same environment to a subviewport with camera , the environment effects look different.

no subviewport >
![screen1B](https://user-images.githubusercontent.com/95492794/175094522-e92cb87e-3de7-448d-a9de-398b57ababfc.jpg)
with subviewport>
![screen](https://user-images.githubusercontent.com/95492794/175094548-66b771d5-e0b7-4bf7-957e-3d1c3f8c1849.jpg)

### Steps to reproduce

create an environment setup , create a subviewport container>subviewport> 2nd camera with cull mask
attach the same environment to the 2 cameras.

**Comment by clayjohn** [comment]
Can you please upload an MRP?

**Comment by djmaesen** [comment]
> Can you please upload an MRP?
> 
> The top one looks like it is using local reflections from something liked baked lighting, or a reflection probe, while the bottom one looks like it is getting a little bit of the sky reflections incorrectly. Is there a a chance that the 2nd camera's cull mask is culling a reflectionProbe, VoxelGI, or Lightmap?

no reflection probes, or voxel GI nor lightmaps are used in my screenshots. after some more tests i suspect it has to do with the 'glow' parameter

**Comment by djmaesen** [comment]
i think ive found the problem, if your environment uses volumetric fog it makes the glow parameter have higher values somehow when using it in a subviewport.

**Comment by djmaesen** [comment]
> Can you please upload an MRP?
> 
> The top one looks like it is using local reflections from something liked baked lighting, or a reflection probe, while the bottom one looks like it is getting a little bit of the sky reflections incorrectly. Is there a a chance that the 2nd camera's cull mask is culling a reflectionProbe, VoxelGI, or Lightmap?

is there a way to enable reflection probes to a second camera and viewport? if i set a reflectionprobes' layers to include the camera, the models don't get the reflection data from it.

**Comment by clayjohn** [comment]
ReflectionProbes should be attached to a given world the way other VisualInstances are. So it should be shared if the Viewports use the same world and not shared if they use different worlds. 

Without an MRP I can't really figure out any more about what is going on in your particular instance.

**Comment by djmaesen** [comment]
> ReflectionProbes should be attached to a given world the way other VisualInstances are. So it should be shared if the Viewports use the same world and not shared if they use different worlds.
> 
> Without an MRP I can't really figure out any more about what is going on in your particular instance.
i posted a repo in this issue >
https://github.com/godotengine/godot/issues/62358

**Comment by clayjohn** [comment]
Bumping to 4.x. Without an MRP we are unable to take any steps towards debugging this issue.

**Comment by clayjohn** [comment]
Closing due to lack of response. If someone else is facing this issue and can provide an MRP, then we can re-open it
