### ISSUE TITLE
Vulkan Mobile: Rendering glitches on Adreno GPUs

### ISSUE THREAD

**Issue by Alexia-AT-Digitecnology** [godotengine/godot#62329]
### Godot version

4.0.dev-alpha10

### System information

Android

### Issue description

I tested a godot basic game made with Godot 4 alpha 10 (a cube and a camera) in different devices. In devices with Adreno chipset it appears gitches and black screen, but in Mali devices it works correctly.

I attach the results for each device:

Xiaomi Redmi 9T (Adreno device):
![imagen](https://user-images.githubusercontent.com/18708610/175192746-112ca919-a746-44b5-a656-61bb0b032f96.png)

Samsung a30s (Mali device):

![imagen](https://user-images.githubusercontent.com/18708610/175192842-73fa57c9-1fc8-4dac-b825-080e7cbc8e6c.png)

LG G6 (Adreno device)

![imagen](https://user-images.githubusercontent.com/18708610/175193088-0218f255-ecdc-49d8-ac7d-f4a8eb9c261f.png)

### Steps to reproduce

Adreno device:

- Unpack the project
- Connect a Adreno GPU phone in debugging mode
- Run in phone
- It will show a black screen or glitches

Mali device:

- Unpack the project
- Connect a Mali GPU phone in debugging mode
- Run in phone
- It will show the game correctly

### Minimal reproduction project

Project: [MyXRProject.zip](https://github.com/godotengine/godot/files/8963080/MyXRProject.zip)

**Comment by Alexia-AT-Digitecnology** [comment]
I created a project in Unity in Vulkan mobile (the same) and there are no glitches, some emulators are using the vulkan backend using adreno gpu and have no problems. Maybe must debug with renderdoc or anything...

**Comment by Alexia-AT-Digitecnology** [comment]
Godot 4 project (Vulkan) APK: https://drive.google.com/file/d/1MtcN9a7uXFFEJQ5h4JYaUQaAOUSwRnvR/view?usp=sharing
Unity Project APK: https://drive.google.com/file/d/1WWoFshINYI0h9Wrbv_7yXajFDc1E-gzt/view?usp=sharing

If any are experienced in vulkan can test both or test the Godot project in a a Mali GPU and Adreno with RenderDoc and see the differences in a specific frame.

**Comment by Calinou** [comment]
This is a bug in the Adreno driver. Bugs in the Adreno driver are also what prevented https://github.com/godotengine/godot/pull/52500 from being merged.

Unfortunately, I think the only way to fix this is to improve the OpenGL renderer so it can be used in production. The Vulkan Mobile driver will likely not get significantly worked on before 4.0's release.

**Comment by Alexia-AT-Digitecnology** [comment]
Really @Calinou?? 2017 effect again (like Godot 3 has)?? LOL Adreno crappy drivers again? ROFLMAO. I'm going to cry. :( I need leisure to debug it (I'm working and studying hard), but in August I will have the end of the weeks as leisure to be with it. But I need to study a lot of Vulkan (for me is a new API, I'm stucked in OpenGL). It will be a challenge. I have tons of Adreno devices here.

**Comment by Alexia-AT-Digitecnology** [comment]
I have good news. The project runs now on my Adreno GPU since alpha 11. There is an screenshot in my Redmi 9T.

![Redmi 9T](https://user-images.githubusercontent.com/18708610/186497271-17a86e97-76b2-4a9e-be09-5d568b93d07a.png)

[Alpha 11 APK](http://files.digitecnology.com/My%20Xr%20Project-alpha11.apk)
[Alpha 14 APK](http://files.digitecnology.com/My%20Xr%20Project-alpha14.apk)

The TPS Demo isn't working, branch 4.0-dev is a lot of buggy because it has 3.x script data and some inconsistencies. I will make 4.0 demos. I will maintain informed of these demos I will make and give screenshots and links to test here.

**Comment by Calinou** [comment]
Closing per the above comment.
