### ISSUE TITLE
Cannot attach "pressed" signal from button to script in GDNative

### ISSUE THREAD

**Issue by treeman0013** [godotengine/godot#62328]
### Godot version

3.4.4.stable

### System information

Linux KDE Neon 5.25 

### Issue description

When I was trying to connect a signal to my node "button" in my game with gdnative, I ran into an issue. I cannot press the button without it giving me the error: _Error calling method from signal pressed. _on_loadmods_pressed method not found_
I have tried this on two seperate game projects, and they both do the same thing, leading me to believe it is a bug in the system.

### Steps to reproduce

1) Compile the project below for your platform (Mine was Linux)
2) assign the target binary in the .GDNLIB file
3) run the project and press the Control Button.

### Minimal reproduction project

[Uploading BugReport.zip…]()

**Comment by Calinou** [comment]
@treeman0013 The minimal reproduction project didn't upload (likely because you clicked away from the text field while it was still uploading). Try editing your post and upload it again.

**Comment by treeman0013** [comment]
I am stupid. I did not put the class in the register_class file
