### ISSUE TITLE
[Suggestion] GDScript Inline ColorPicker

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#6232]
**Operating system or device - Godot version:** 21
**Suggestion description** (what happened, and what was expected):
Just thought of something pretty cool a moment ago and thought I'd share! 
If a `Color` type is being edited or if the mouse is hovering over it for xx milliseconds, show a color picker.  Example:

![image](https://cloud.githubusercontent.com/assets/10387670/17844243/1ed5d234-67ec-11e6-9f32-81f808f818f5.png)

**Comment by Calinou** [comment]
We can use the contextual right-click menu (introduced in 2.1) for this.
