### ISSUE TITLE
MultiplayerSpawner not working when instantiated on client after the host

### ISSUE THREAD

**Issue by Astro9731** [godotengine/godot#62320]
### Godot version

v4.0.alpha10.official [4bbe7f0b9]

### System information

Windows 10

### Issue description

I've been getting some very buggy behavior with the MultiplayerSpawner when instantiating it

If you're connected to a server as a client, and instantiate a scene containing a MultiplayerSpawner AFTER the host has already instantiated that same scene & the host has already instantiated scenes for the MultiplayerSpawner to spawn, the MultiplayerSpawner just won't work on the client

The following error will be spit out by the client:
![error](https://user-images.githubusercontent.com/92401278/175098941-ec820113-2626-40e2-ac3b-b571a7b88236.png)

### Steps to reproduce

Simply load a scene containing a MultiplayerSpawner as a client after the host has already loaded that same scene & has instantiated scenes for the MultiplayerSpawner to spawn

### Minimal reproduction project

[MultiplayerSpawner bug.zip](https://github.com/godotengine/godot/files/8960343/MultiplayerSpawner.bug.zip)

**Comment by jgillich** [comment]
I've also come across this in #62027. What is odd is that the multiplayer_bomber example works fine, and [I believe it creates the server scene first](https://github.com/godotengine/godot-demo-projects/blob/4.0-dev/networking/multiplayer_bomber/gamestate.gd#L111). So it seems this problem only occurs when you join a bit later than the server
