### ISSUE TITLE
forward_canvas_gui_input not recognize tablet pressure

### ISSUE THREAD

**Issue by yikescloud** [godotengine/godot#62332]
### Godot version

3.4.4 stable

### System information

windows10

### Issue description

forward_canvas_gui_input() return  mouseMotion event 's pressure 1 or 0, no pressure even I use a graphic tablet. Pressure works good on normal control2D scene.

### Steps to reproduce

Make a Addon, then paste these codes in plugin.gd:
```
func forward_canvas_gui_input(event:InputEvent):
	if event is InputEventMouseMotion:
		print(event.pressure)
	return true
```

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
