### ISSUE TITLE
Control Node Transform Field removed by parent container.

### ISSUE THREAD

**Issue by tex111** [godotengine/godot#62331]
### Godot version

4.0 alpha 10

### System information

Windows 10

### Issue description

When you have a control node who's transform is being controlled by a parent, Hbox, MarginContainer, ect, The transform field is removed. I understand not wanting the user to be able to change it but that is where information about the node's current size is. This is critical information for keeping track of UI scales across scenes and maintaining UI consistency. 

Here is a basic use case. I want to make a button in a HBox perfectly square. I cannot do this if I don't know it's current size.

Please leave it and make it read only.

### Steps to reproduce

![example](https://user-images.githubusercontent.com/55551426/175206846-afd67091-e7d6-4866-a3e1-54d6e6faa19c.PNG)

**Comment by and-rad** [comment]
Isn't that what the `Container Sizing` group is for? Disable horizontal and vertical stretching, set an appropriate minimum size, and make sure that the contents of the button are properly clipped.

![container](https://user-images.githubusercontent.com/8700280/175249345-b5c3043c-92ff-42d4-aef9-c27faef72c8e.PNG)

**Comment by tex111** [comment]
That would work I suppose, but it seems to be a workaround. Why do i need to do so many steps just to get basic info like rect size? How hard would it be to make it a read only field when a child? In the example you gave, container is greyed out so I know it is possible.

**Comment by tex111** [comment]
I am aware and specifically complaining about it. 

My particular use case is that I try to match UI Proportions across nodes in a scene and between scenes. I also make heavy use of containers. Even though I may not be setting it directly, I often do my adjustments in the parent node as seems to be the expected behavior pattern, I am checking rect_size hundreds of times in a work session. 

Because it obscures that data, Godot 4 will greatly reduce my ability to work efficiently. I made a complaint in the discord a few days ago and a few people were also frustrated with this UI behavior. Thus, I came here to post and hopefully get it changed while still in alpha.

**Comment by and-rad** [comment]
So you need to be able to see and change those values at design time and not at runtime?

**Comment by tex111** [comment]
> So you need to be able to see and change those values at design time and not at runtime?

I need to see them even if I cannot change them. I have no problem with the paradigm of child sizes being controlled by the parent container.

**Comment by aaronfranke** [comment]
This is caused by PR #55157.

I'm trying to debug a UI, and part of this process is that I need to see how big something is at runtime. Since Godot no longer displays the position and size for children of a container in the remote debugger, this makes it impossible to debug my issue without lots of print statements in my code to print out the size.

![Screenshot from 2022-06-27 18-56-59](https://user-images.githubusercontent.com/1646875/176058747-26de3175-5272-497d-a4e0-0a54baa1930c.png)
