### ISSUE TITLE
GDScript 2.0: Calling new on custom class with a class_name fails

### ISSUE THREAD

**Issue by Jimmio92** [godotengine/godot#62360]
### Godot version

4.0.alpha10

### System information

Windows 10, Ryzen 7 3rd gen, X570, 32GiB DDR4, AMD Radeon RX 590

### Issue description

I have a script at "res://Classes/PID.gd" which defines `class_name PID`.

When I try to use my class in another script, I am able to reference it as a type, however when I call new on it, I get "Invalid call. Nonexistent function 'new' in base 'GDScript'".

In other words this does **NOT** work:
`@onready var _walk_pid: PID = PID.new()`

Where as this does work:
`@onready var _walk_pid: PID = preload("res://Classes/PID.gd").new()`

The PID class has three optional arguments in its _init function, however removing them does not affect the outcome.

### Steps to reproduce

I really hope it's reproducible elsewhere or I'll look insane to everyone here :tong

1) Create a GDScript named Foo.gd
2) Line 2 `class_name Foo`
3) Create another GDScript (name doesn't matter)
4) Attempt to create an instance of Foo using `Foo.new()` in `func _ready()` or using `@onready`

5 optional) Attempt to create an instance of Foo using `preload("res://Foo.gd").new()` and verify that does indeed work.

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/62292.
