### ISSUE TITLE
All underscore methods in Animation Nodes are not callable

### ISSUE THREAD

**Issue by stryker313** [godotengine/godot#62379]
### Godot version

4.0 Alpha 9

### System information

Windows 10 Nvidia GTX 1060 Intel i5 4690k

### Issue description

Extension of #62340, potential dupe, so may close in favor of this one.

Methods relating to AnimationNode that have underscores are not callable.

_get_parameter_list,
_get_parameter_default_value,
_has_filter,
_get_child_by_name
_get_caption

Attempting to use these methods will throw errors.

### Steps to reproduce

Try to call any of the above methods in their respective classes. The editor says that the function does not exist within the given class.

### Minimal reproduction project

[BrokenAnimationTree.zip](https://github.com/godotengine/godot/files/8977272/BrokenAnimationTree.zip)

**Comment by KoBeWi** [comment]
These methods are virtual. You are supposed to implement them, not call. Same in #62340

**Comment by Calinou** [comment]
By the way, these methods have a "virtual" hint which displays next to them in the class reference.

Still, the descriptions should be reworded to start with "Called when…".

**Comment by stryker313** [comment]
So how would you access the data provided by the virtual functions? What do you mean by "implement"?

My understanding is

```
extends AnimationNode

func _get_parameter_list():
\\Do stuff
pass
```

But according to the docs...
`Array _get_parameter_list() virtual const`
`Gets the property information for parameter. Parameters are custom local memory used for your nodes, given a resource can be reused in multiple trees. Format is similar to Object.get_property_list().`

So how would you access the information? (In this case, it claims to return an array)

**Comment by Calinou** [comment]
> So how would you access the information? (In this case, it claims to return an array)

This is meant to be used by add-ons that implement their own animation nodes. You are expected to *implement* `_get_parameter_list()` and return an Array with the exposed parameters yourself.

On existing animation nodes, you *cannot* call those methods to get the information yourself. It's only used internally within the editor anyway.
