### ISSUE TITLE
Godot - Dimension - Monitor "15" - "1024x768"

### ISSUE THREAD

**Issue by daniloprogramador1991** [godotengine/godot#6237]
My problem is this.
My Monitor is "15" "1024x768".
As there program to reduce the dimensions of the stand element on element ?.
I'm from Brazil.
I am a beginner in godot engine.
I'm using Google Translate to communicate.

![captura de tela de 2016-08-22 08-50-56](https://cloud.githubusercontent.com/assets/18791768/17854679/b41fa870-684a-11e6-96c3-80d5fbcf0281.png)

**Link to minimal example project** (optional but very welcome):

**Comment by reduz** [comment]
I guess we'll have to add more scaling options other than hidpi/lodpi. Some
people asked for middpi, and I suppose verylodpi would work too

**Comment by quantum-entangler** [comment]
1 idea in theory at least would be to change default font to otf/vector font and icons to vector art too, this way it will be much easier to achieve scalable interface...

**Comment by Calinou** [comment]
Icons are already available in vector format, and the font is already used as a .ttf/.otf (Droid Sans and Source Code Pro).

**Comment by SuperUserNameMan** [comment]
Here is a workaround I used when I was using godot on a 11 inch 1024*600 netbook under LinuxMint :
- the ``xrandr`` allowed me to set a higher virtual screen resolutions.

I could emulate a fullscreen 1600*900 resolution by downscaling it to the physical resolution, or I could keep the physical pixel size and pan and scan the virtual resolution (the 1600*900 desktop was scrolling when the mouse cursor reached the border of the physical 1024*600 viewport).

**Comment by akien-mga** [comment]
@reduz added "very low DPI" and "mid DPI" in the current master branch, so this should be fixed. I don't think it would be automatically detected and applied (as it makes the icons look not so good), but you can select very low DPI and have a usable editor on this small resolution. Improving the looks of the icons in such a case would be a matter for another issue, so closing as fixed.
