### ISSUE TITLE
Tabs tab_clicked and tab_changed not firing

### ISSUE THREAD

**Issue by Sp3ci3s8472** [godotengine/godot#62385]
### Godot version

3.4.4-stable

### System information

Windows 10

### Issue description

Given the following simple class in c#:
``` using Godot;
namespace FancyInventoryNamespace
{
    public class InventoryTab : Tabs
    {         
        public InventoryTab()
        {
            Name = "Inventory"; 
            Connect("tab_clicked", this, nameof(OnTabClicked));
            Connect("tab_changed", this, nameof(OnTabClicked));
        }
        private void OnTabClicked(int tab)
        {
            GD.Print("Tab switched " + tab);
        }
    }
}
```

Somehow the signals don't fire when I click to change tabs. The signals are connected since I can disconnect them and I get an error when I try to connect them another time. 
Changing tabs just works fine and the tabs switch. However, it does not print "Tab switched".

I found a similar issue which has been solved:
https://github.com/godotengine/godot/issues/10051
and one on reddit:
https://www.reddit.com/r/godot/comments/jj8p7y/why_isnt_tab_clicked_working/

The signals tab_changed and tab_selected from the TabContainer work without problems.

### Steps to reproduce

See the minimal reproduction project.

### Minimal reproduction project

[TabTest..zip](https://github.com/godotengine/godot/files/8980039/TabTest.zip)

**Comment by Calinou** [comment]
cc @YeldhamDev

**Comment by YeldhamDev** [comment]
Can't reproduce it in any version (3.4, 3.5, and master).

**Comment by Sp3ci3s8472** [comment]
> Can't reproduce it in any version (3.4, 3.5, and master). Does this also happen with GDScript on your end, or just with C#?

I only tried it in C#. I'm not proficient in GDScript, but I will try it tomorrow. Better yet, I will try to run it on my laptop tomorrow which runs PopOS just to make sure it is not my Windows system being weird.

To be sure I retested it. I can reproduce it in 3.4.2, 3.4.4. I also tried multiple target frameworks net472 and netstandard2.1.

Did you try my sample project that I uploaded? 
Also as stated, the signals from the TabContainer work; I have problem with the Tabs node signals. (just to make sure :))

**Comment by YeldhamDev** [comment]
I previously just tested it by creating a quick project.

But examining your code, it seems that you misunderstood how `TabContainer` works. The `TabContainer` node will generate its own tabs for each `Control` node inside of it, the signals should be connected from it.

`Tabs` is basically a `TabContainer` without the "container" part, needing you to create tabs manually via code.
