### ISSUE TITLE
Godot 4 Unable to drag from Window / Popup

### ISSUE THREAD

**Issue by filantus** [godotengine/godot#62384]
### Godot version

v4.0.alpha10.official [4bbe7f0b9]

### System information

Windows 10, GLES3

### Issue description

Sorry if it's not considered as a bug. But there is a problem. With new Godot 4 Window or Popup can't drag anything and drop outside (of a Window or a Popup). See video below.

I've tried to toggle some Window options like 'popup_window', 'wrap_controls', 'transient', 'handle_input_locally'. But it's not helps.

### Steps to reproduce

https://user-images.githubusercontent.com/13046849/175649378-07b03d91-151c-448b-a590-78c50f234255.mp4

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/8980024/test.zip)

**Comment by 316902108** [comment]
https://user-images.githubusercontent.com/48303560/175798504-79356071-10e4-4014-88aa-a5f2a4222239.mp4

**Comment by filantus** [comment]
> 1656084021765.mp4
@316902108 I think it's another issue. In my case dragging within modal Window is works fine. But can't move any drag preview beyond borders of modal Window.

**Comment by filantus** [comment]
For clarification. In my case dragging is not stops when i move cursor outside of modal Window. If move cursor from modal Window and back then drag preview will be shown. But outside of modal Window drag preview is not displayed and drop also not work. In same time drag and drop of same item but not from modal Window is works fine. See video:
https://user-images.githubusercontent.com/13046849/175811814-a0c33996-d4de-479e-b981-3ea38a5e1f2a.mp4

**Comment by Sauermann** [comment]
You describe two issues:
- Can't drag and drop from embedded window to root viewport. This is a known issue and tracked in #28522
- Drag Preview only works within the embedded window. This is a known issue and tracked in #67186

Consolidating this as a duplicate with the other two bug-reports.
