### ISSUE TITLE
Can't compile for server on FreeBSD

### ISSUE THREAD

**Issue by deasek** [godotengine/godot#6238]
Godot version: latest source
OS version: FreeBSD 10.3-RELEASE-p3

When compiling for server (platform=server) on FreeBSD compilation fails at very beginning stage.
Error message:

```
scons: Building targets ...
g++ -o platform/server/godot_server.server.tools.64.o -c -g2 -Wall -DDEBUG_ENABLED -DDEBUG_MEMORY_ENABLED -DFREETYPE_ENABLED -DDEBUG_MEMORY_ALLOC -DSCI_NAMESPACE -DENABLE_DEPRECATED -DSERVER_ENABLED -DUNIX_ENABLED -DMUSEPACK_ENABLED -DSQUISH_ENABLED -DVORBIS_ENABLED -DOPUS_ENABLED -DTHEORA_ENABLED -DTHEORALIB_ENABLED -DPNG_ENABLED -DDDS_ENABLED -DPVR_ENABLED -DJPG_ENABLED -DWEBP_ENABLED -DSPEEX_ENABLED -DTOOLS_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DXML_ENABLED -DETC1_ENABLED -Icore -Icore/math -Itools -Idrivers -I. -Iplatform/server -Idrivers/freetype -Idrivers/freetype/freetype/include -Idrivers/freetype/include platform/server/godot_server.cpp
In file included from core/typedefs.h:37:0,
                 from ./main/main.h:37,
                 from platform/server/godot_server.cpp:29:
platform/server/platform_config.h:29:20: fatal error: alloca.h: No such file or directory
 #include <alloca.h>
                    ^
compilation terminated.
scons: *** [platform/server/godot_server.server.tools.64.o] Error 1
scons: building terminated because of errors.

```

On FreeBSD terminal clone repository, enter it and type:

> scons platform=server

COMMENT:
I was able to fix above error by adding:

```
#ifdef __linux__
#include <alloca.h>
#endif
#if defined(__FreeBSD__) || defined(__OpenBSD__)
#include <stdlib.h>
#define PTHREAD_BSD_SET_NAME
#endif

```

to the 

> platform/server/platform_config.h

but then another has error appeared:

> g++ -o modules/enet/register_types.server.tools.64.o -c -g2 -Wall -DDEBUG_ENABLED -DDEBUG_MEMORY_ENABLED -DFREETYPE_ENABLED -DDEBUG_MEMORY_ALLOC -DSCI_NAMESPACE -DENABLE_DEPRECATED -DSERVER_ENABLED -DUNIX_ENABLED -DMUSEPACK_ENABLED -DSQUISH_ENABLED -DVORBIS_ENABLED -DOPUS_ENABLED -DTHEORA_ENABLED -DTHEORALIB_ENABLED -DPNG_ENABLED -DDDS_ENABLED -DPVR_ENABLED -DJPG_ENABLED -DWEBP_ENABLED -DSPEEX_ENABLED -DTOOLS_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DXML_ENABLED -DETC1_ENABLED -Icore -Icore/math -Itools -Idrivers -I. -Iplatform/server -Idrivers/freetype -Idrivers/freetype/freetype/include -Idrivers/freetype/include modules/enet/register_types.cpp
> In file included from modules/enet/networked_multiplayer_enet.h:5:0,
>                  from modules/enet/register_types.cpp:31:
> modules/enet/enet/enet.h:18:23: fatal error: enet/unix.h: No such file or directory
>  #include "enet/unix.h"
>                        ^
> compilation terminated.
> scons: **\* [modules/enet/register_types.server.tools.64.o] Error 1

**Comment by Calinou** [comment]
To fix the ENet compilation error, you may need to modify [its SCsub](https://github.com/godotengine/godot/blob/master/modules/enet/SCsub).

**Comment by neikeq** [comment]
Please, don't kill me for labelling this as linux.
