### ISSUE TITLE
android app not installed bug on latest release candidate 

### ISSUE THREAD

**Issue by Cube5x59999** [godotengine/godot#62381]
### Godot version

3.5 rc

### System information

samsung galaxy tab a with armv8l processer

### Issue description

when i install apk it says app not installed

### Steps to reproduce

install 3.5 rc apk of godot

### Minimal reproduction project

i cant create project

**Comment by Cube5x59999** [comment]
im new to godot too

**Comment by Calinou** [comment]
> samsung galaxy tab a with armv8l processer

Which Galaxy Tab A model is this *exactly*?

**Comment by akien-mga** [comment]
What version do you refer to exactly with "3.5 rc"?

**Comment by Cube5x59999** [comment]
1. galaxy tab a
2. 3.5 rc mean 3.5 release candidate

**Comment by Cube5x59999** [comment]
3. im android 11

**Comment by Cube5x59999** [comment]
umm tab a 2018 model

**Comment by Cube5x59999** [comment]
2018/2020 idk

**Comment by Cube5x59999** [comment]
FIXED AT NEW RC 4 CLOSING ISSUE

**Comment by Calinou** [comment]
@Cube5x59999 In the future, please use the **Edit** button (located behind the **…** icon in the top-right corner of your comments) instead of multi-posting.
