### ISSUE TITLE
Mesh doesn't show if his parent changes from an invisible one to a invisible one

### ISSUE THREAD

**Issue by sfdldsfldkfsldf** [godotengine/godot#62391]
### Godot version

4.0 alpha 10

### System information

Linux (Ubuntu)

### Issue description

Mesh that changes parent from an invisible one to a visible one stays invisible, even tho he and all of his parents are set as visible.

### Steps to reproduce

1. add a visible scene as a child of a visible node
2. mark the parent as invisible
3. move the child to an invisible node
4. the mesh will stay invisible

**Comment by Calinou** [comment]
@sfdldsfldkfsldf Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by sfdldsfldkfsldf** [comment]
Seen what was the problem: the node stayed in the previous position (inside the player) and didn't update it when the parent changed. Still an issue i think
