### ISSUE TITLE
[Godot 4.0] Objects that are illuminated by more than 16 lights become unlit

### ISSUE THREAD

**Issue by MyStarrySpace** [godotengine/godot#62395]
### Godot version

4.0.dev (alpha 10)

### System information

Windows 11 Pro version 10.0.22000 Build 22000, NVIDIA GeForce RTX 2060, Game Ready Driver v511.79, Vulkan

### Issue description

It was stated that the limit to the number of lights illuminating an object is 16. I would expect that after that point, additional lights would not affect the shading of the object. However, what actually happens is that the entire lighting on the object disappears completely, as if there were no lights at all.

### Steps to reproduce

1. Create a new project
2. Create an object where the light is visible
3. Add 16 lights with light textures and correct settings
4. Add the 17th light to break the lighting

**Comment by Calinou** [comment]
@MyStarrySpace Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by Calinou** [comment]
@MyStarrySpace Can you (or anyone else) still reproduce this bug in [Godot 4.0alpha16](https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-16) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.

**Comment by tremisabdoul** [comment]
[Uploading 17 light bug preview.zip…]()
Hello ! 
I have the same problem one of my projects so if i can help you with this minimal reproduction project there it is ! 
Have a good day :D

**Comment by tremisabdoul** [comment]
(Godot 4.0 beta 9 project) 
[17 light bug preview.zip](https://github.com/godotengine/godot/files/10316839/17.light.bug.preview.zip)
