### ISSUE TITLE
Save dialog's file name no longer starts selected.

### ISSUE THREAD

**Issue by icecoldtofu** [godotengine/godot#62400]
### Godot version

v3.5.rc4.official [e047c5006]

### System information

Windows 10, Intel Graphics, GLES3

### Issue description

The file name field in the save dialog is no longer selected when the dialog opens.

Looks like the same regression as https://github.com/godotengine/godot/issues/56329 that was fixed in 4.0 a few months ago.

### Steps to reproduce

Try to save a resource or a scene.

**Comment by timothyqiu** [comment]
Fixed by #62196
