### ISSUE TITLE
Vulkan: 3D visuals involving reflections are broken (hardware dependent)

### ISSUE THREAD

**Issue by jtnicholl** [godotengine/godot#62404]
### Godot version

v4.0.alpha.custom_build [21c79d751]

### System information

Linux (Fedora 36), Radeon R9 390X w/ amdgpu driver

### Issue description

After #62133 was merged, any scene with a sky background or ReflectionProbes causes the errors:
```
ERROR: Condition "shader.is_null()" is true.
   at: cubemap_roughness (servers/rendering/renderer_rd/effects/copy_effects.cpp:1033)
```
and
```
ERROR: Condition "!version" is true. Returning: RID()
   at: version_get_shader (./servers/rendering/renderer_rd/shader_rd.h:140)
```
to print to the console several times upon loading the scene or updating the reflection probes. All objects in the area of a reflection probe or anywhere in a scene with a sky background appear as scrambled colors or pitch black. It seems worse on Vulkan clustered, but happens on mobile too. Clustered also causes glow to appear far too strong.
Reverting #62133 and deleting .godot/shader_cache/ from the project fixes the issues. There are likely other visual issues as well but I didn't test much beyond opening the projects I already had.
![Screenshot_20220625_152404](https://user-images.githubusercontent.com/44414418/175787961-4269de1e-1c86-42eb-93af-b58ec66dbb93.png)

### Steps to reproduce

Open any 3D scene with a ReflectionProbe, or with an environment using a sky background (including the editor preview environment)

### Minimal reproduction project

[BrokenShaders.zip](https://github.com/godotengine/godot/files/8985435/BrokenShaders.zip)

**Comment by BastiaanOlij** [comment]
@jtnicholl can you test if this fixes it for you: https://github.com/godotengine/godot/pull/62420  ?

**Comment by jtnicholl** [comment]
Yep, that fixes it for me. The error messages and the visual bugs are both gone.
