### ISSUE TITLE
Cannot parse shader with ternary condition written in specific way

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#62402]
### Godot version

21c79d75153733b84533957228d0c267ef340a80

### System information

Windows 10 64 bits GLES3 GeForce GTX 1060 6GB/PCIe/SSE2

### Issue description

I wanted to give a try at the code from https://iquilezles.org/articles/biplanar/ but found Godot is unable to parse it.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/1311555/175786637-c2974aa0-8488-40a5-aedb-300ac6330836.png)
```glsl
    ivec3 ma = (n.x>n.y && n.x>n.z) ? ivec3(0,1,2) :
               (n.y>n.z)            ? ivec3(1,2,0) :
                                      ivec3(2,0,1) ;
```
```
Invalid argument to ternary operator: 'bool, ivec3, bool'.
  Shader compilation failed.
```

Workaround:
Add parenthesis to the nested ternary.
```glsl
    ivec3 ma = (n.x>n.y && n.x>n.z) ? ivec3(0,1,2) :(
               (n.y>n.z)            ? ivec3(1,2,0) :
                                      ivec3(2,0,1) );
```

### Minimal reproduction project

[ShaderParserTests.zip](https://github.com/godotengine/godot/files/8985389/ShaderParserTests.zip)

**Comment by Chaosus** [comment]
I have troubles to solve that issue a while ago (spent several hard hours). Maybe someone else could solve that.
