### ISSUE TITLE
ParalaxLayer offset settings is not offseting the layer to correct position

### ISSUE THREAD

**Issue by svelezsaffon** [godotengine/godot#62427]
### Godot version

3.4.4 stable 3.5 rc2 4.0 alpha 9

### System information

Microsoft Windows 11 Home x64-based PC Processor	AMD Ryzen 9 4900HS with Radeon Graphics, 3000 Mhz, 8 Core(s), 16 Logical Processor(s) Installed Physical Memory (RAM)	16.0 GB NVIDIA GeForce RTX 2060 with Max-Q Design

### Issue description

The parallax offset property, is not offsetting the mirroring starting point of a parallax layer.

ParallaxLayer node has a x,y offset property, this property should make the mirroring start from a given offset position. if the User sets this property, the paralax layer is always offset to x=0 y=0

**Current behavior**
Paralax offset values is always 0,0. Appears to be that the paralax offset is not taking place

**Expected behavior**
Paralax offset starting point to be equal to the one the user set on the offset property

### Steps to reproduce

Scene setup

1. Add a 2d Scene
2. Add a ParallaxBackground node, child of the scene
3. Add ParallaxLayer as a child of the ParallaxBackground 
4. Add a sprite, can be godot logo. child of ParallaxLayer 
3. Add ParallaxLayer as a child of the ParallaxBackground 
4. Add a sprite, can be godot logo. child of second ParallaxLayer
5. Select second parallax layer
6. Click mirroring
7.  set offset to 64

**Scene Set up**
![image](https://user-images.githubusercontent.com/8091482/175812708-e9e063c9-682f-4268-b6fe-fe93ee96c947.png)

**Parallax configuration**
![image](https://user-images.githubusercontent.com/8091482/175812756-779def72-1aa2-425f-8081-b8dd939b9344.png)

### Minimal reproduction project

Project on godot 3.4.4 version
[paralax_offset_issue.zip](https://github.com/godotengine/godot/files/8986511/paralax_offset_issue.zip)

Project on godot 4 alpha 9 version
[paralax_issue_4.zip](https://github.com/godotengine/godot/files/8986529/paralax_issue_4.zip)

**Suggestions**
On the enter tree notification code, the orig_offset variable is being overwritten by the node's position
https://github.com/godotengine/godot/blob/d5cd990414f6dfde9617dd8428ddfdd924bd15c9/scene/2d/parallax_layer.cpp#L98

`			orig_offset = get_position();`

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/23243.

**Comment by svelezsaffon** [comment]
Oh! sorry @Calinou ! I should have verified other bugs. We can close this one.
