### ISSUE TITLE
Rigid Body does not pass scaling properties to its child nodes.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#6242]
I understand that Rigid Bodies in Godot don't scale, but it seems like they aren't forwarding the scaling downward in the hierarchy for sprites and such to receive it.

It appears in the editor to be working, but when the script runs that is not what I get in the actual run time.

For now I have to write GDScript to pass along the transformations manually.

![scaling bug](https://cloud.githubusercontent.com/assets/13004169/17861415/af93da20-6899-11e6-80b6-455d0769eb3c.jpg)

**Comment by bojidar-bg** [comment]
Currently RigidBody2D nodes overwrite their scale to (1,1). There is already an issue for this #1505, so closing as a duplicate.
