### ISSUE TITLE
cam stoping in ver 3.4.4

### ISSUE THREAD

**Issue by Nicccolisaylors** [godotengine/godot#62422]
### Godot version

3.4.4 stable

### System information

windows 10

### Issue description

I was adding a cam but halfway this is the main cam it stoped 

### Steps to reproduce

step one do a project
step two  add a cam
step three test to see the assets work.
 

### Minimal reproduction project

it is in all projects

**Comment by Calinou** [comment]
@Nicccolisaylors Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
