### ISSUE TITLE
CanvasItem visibility not refreshed correctly when it enters tree

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#62437]
### Godot version

898e09e

### System information

Windows 10 x64

### Issue description

![godot_32mwms4Wro](https://user-images.githubusercontent.com/2223172/175843313-17154352-c3ed-4823-9440-629dbcdc3efc.gif)
Does not happen in 3.x

### Steps to reproduce

1. Add Sprite2D as a child of Node2D
2. Make Node2D invisible
3. Move the sprite under another node that is visible
4. Sprite stays invisible

**Comment by KieranCarden** [comment]
I was about to make a similar issue but saw this was just opened. I've noticed that if you have invisible nodes when opening a project, those nodes are visible and need to be toggled twice to go back to being invisible.
![visible_nodes](https://user-images.githubusercontent.com/4044137/175981438-db5d24d0-1b0e-4696-a47e-734be6f3ba07.png)
`Grass` tilemap and `Outside` tilemap I've changed to hidden, but both are visible on project load despite still marked as hidden.

@KoBeWi If I should make this as a separate issue let me know - sounded similar enough though that it might be the same bug?

**Comment by KoBeWi** [comment]
Yeah it's likely the same bug.

**Comment by Rindbee** [comment]
I noticed that the parent node had to be made invisible manually, so the problem might be related to `_propagate_visibility_changed`.

Also affected are `NOTIFICATION_VISIBILITY_CHANGED` notifications for child nodes, may cause child nodes to emit visibility_changed signals.

Maybe this can be fixed at `first_draw`.

**Comment by Rindbee** [comment]
Is `NOTIFICATION_VISIBILITY_CHANGED` emitted when `visible` toggles, or when the result of `is_visible_in_tree()` changes?

**Comment by Rindbee** [comment]
Now, it should be quickly fixed by #63248.


> Also affected are `NOTIFICATION_VISIBILITY_CHANGED` notifications for child nodes, may cause child nodes to emit `visibility_changed` signals.

I'm not sure if this needs to be fixed.
