### ISSUE TITLE
Generating log folders when disabled

### ISSUE THREAD

**Issue by RitleHub** [godotengine/godot#62430]
### Godot version

3.5 RC 4

### System information

Windows 10, gtx 1660 super, GLES3, AMD Ryzen 5 3500x

### Issue description

I tried to disable logging through the editor.
It works but the folder of Godot and the project's name is still being generated for no reason. (When running the build)
*Note - this is happening on a release and debug. (the logs folder is empty though)

![image](https://user-images.githubusercontent.com/89964227/175823302-3332340a-d158-4a25-bfdf-2ea273c602af.png)

This is the path of generation - C:\Users\<username>\AppData\Roaming\Godot\app_userdata\\<Project's name>

Should it create folders for no reason or am I missing here something?

### Steps to reproduce

1) Create a project, add an initiative scene and change the settings as shown in the photo above.
2) Run the project (debug / release)
3) Check if the folders described above exist.

**Comment by akien-mga** [comment]
That's not only the logs folder, that's the `user://` path where you can write data. It has to be created because like `res://`, it's expected to be valid.

**Comment by RitleHub** [comment]
Why does it have to be created if it's empty? It doesn't make sense to me. Anyway in my opinion there should be an option to disable it. Maybe with some warning because it's ```user://```.

**Comment by Calinou** [comment]
The userdata folder is always created when the project starts, because the project will need whenever you write anything to `user://`. Deferring this requirement to the user would result in a lot of bug reports being opened :slightly_smiling_face: 

Creating a folder doesn't take up any disk space, so I don't see a reason to disable it.

**Comment by KoBeWi** [comment]
Related: #21799

**Comment by RitleHub** [comment]
This seems like a good idea to leave it as it is, but in my opinion, it needs some more customization.

By that I mean to have the ability to change the ```user://``` directory path to the same path as the executable or build. (Could also add the option to control the file's name.)
It looks more professional to me and it lets developers decide what suits them best. 
Although the current option should probably stay as default, and still is a good solution, this can be improved/enhanced.

**Comment by Calinou** [comment]
> By that I mean to have the ability to change the user:// directory path to the same path as the executable or build. (Could also add the option to control the file's name.)

This is already being tracked in https://github.com/godotengine/godot-proposals/issues/2474, so I'll close this in issue in favor of https://github.com/godotengine/godot-proposals/issues/2474.
