### ISSUE TITLE
Async mode HIDDEN breaks shadows

### ISSUE THREAD

**Issue by crazyStewie** [godotengine/godot#62431]
### Godot version

tested both on 3.5.rc4 and 3.x (af4e3cb)

### System information

Manjaro gnome, running x11, on a gtx 1060-6GB, proprietary nvidia driver version 515.48.07-7 from the official manjaro repository, GLES 3

### Issue description

When using the Async mode HIDDEN on a spatial material, shadows fail to render.
<details>
  <summary>Output with Async Mode set to VISIBLE</summary>

 ![Screenshot from 2022-06-26 14-35-48](https://user-images.githubusercontent.com/30158085/175826887-a3af22b8-b4ea-44ec-ad99-4dc395bf1710.png)
  
</details>

<details>
  <summary>Output after switching Async Mode to HIDDEN</summary>

![Screenshot from 2022-06-26 14-39-13](https://user-images.githubusercontent.com/30158085/175826962-3df0e738-8d95-4285-afb2-b66205105427.png)
  
</details>

The only difference on the scene between those 2 outputs is the async mode on both meshes (they share the same material),
Everything else (camera, lights, world environment) stays the same

I also made a renderdoc capture of both outputs (using the 3.5.rc4 release) : [renderdoc_captures.zip](https://github.com/godotengine/godot/files/8987144/renderdoc_captures.zip)

### Steps to reproduce

Add some lights with shadows enabled and some mesh instances to a scene so that shadows are visible and run it, the shadows should appear normally. Switch the async mode on the mesh instances material to HIDDEN and run the scene again, and the shadows are gone.

### Minimal reproduction project

[AsyncShadows.zip](https://github.com/godotengine/godot/files/8987157/AsyncShadows.zip)
The project used for the screen captures, the material is set to Visible by default, switching to Hidden and running the scene should make the shadows disappear

**Comment by Calinou** [comment]
cc @RandomShaper

**Comment by RandomShaper** [comment]
Regression from #60183. PR fixing it coming _very_ soon.

**Comment by Calinou** [comment]
Fixed by https://github.com/godotengine/godot/pull/62432.
