### ISSUE TITLE
Thread.start() doesn't accept default parameter?

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#62438]
### Godot version

Godot_v3.4.4-stable

### System information

Windows 10

### Issue description

I coding like this:
![1](https://user-images.githubusercontent.com/35988767/175848157-5a566698-b96b-4e8e-8524-e3b3ae8cb8af.PNG)
![2](https://user-images.githubusercontent.com/35988767/175848160-ba05e432-6ff6-4c08-bc86-38192564ce62.PNG)
Run my project and press Enter key, it report error:
![3](https://user-images.githubusercontent.com/35988767/175848235-fe3b6aca-c3d1-4070-bd55-aaef8a479067.PNG)
It's like because of subclass!

### Steps to reproduce

Please run my reprocution project.

### Minimal reproduction project

[ThreadTest.zip](https://github.com/godotengine/godot/files/8988205/ThreadTest.zip)

**Comment by akien-mga** [comment]
Fixed by #62440.
