### ISSUE TITLE
`apply_force` and `apply_impulse` functions not handled by covnerter tools

### ISSUE THREAD

**Issue by addmix** [godotengine/godot#62434]
### Godot version

4.0 alpha 10

### System information

Win10 64bit

### Issue description

4.0 converter tools do not properly convert 3.x `apply_force` and `apply_impulse` functions, which both had their arguments reordered (3.x is (position, force), 4.0 is (force, position)).

### Steps to reproduce

Convert 3.x project with `apply_force` or `apply_impulse` functions to 4.0

**Comment by Calinou** [comment]
For reference, this is about the converter added in https://github.com/godotengine/godot/pull/51950. cc @qarmin
