### ISSUE TITLE
Sometimes close tab button becomes unresponsive

### ISSUE THREAD

**Issue by lufog** [godotengine/godot#62442]
### Godot version

v4.0.alpha10.official (4bbe7f0b9)

### System information

Windows 11, Vulkan Clustered, GeForce 1660 (516.40)

### Issue description

Sometimes the close tab button becomes unresponsive. Closing a tab via the context menu works fine. Although it’s a little inconvenient when, instead of the context menu of the tab, another context menu of two items opens (you can see it on the video).

https://user-images.githubusercontent.com/10379487/175871986-e09b8248-5332-4e41-8c1f-20dcc44ebebc.mp4

### Steps to reproduce

Not sure how to describe the reproduction steps. The problem does not always appear, but quite often, while working in the editor.
Maybe it has something to do with periodically stuck tab thumbnails. Because of this, I disabled them in the settings.

**Comment by MinusKube** [comment]
This seems to have been fixed by #62824
