### ISSUE TITLE
iOS 16 , HTML5 ( both GLES2 and GLES3)  are NOT working 

### ISSUE THREAD

**Issue by nne998** [godotengine/godot#62445]
### Godot version

3.4.4 /  3.5.0 RC7

### System information

iOS 16 beta 3

### Issue description

iOS 16 , HTML5 ( both GLES2 and GLES3)  are NOT working .  
Open the exported html5 page with safari on iOS 16,  it keep reloading, then crashed.

### Steps to reproduce

1、 Godot project export to HTML5 (GLES2 or GLES3)
2、 Serve to web
3、 Open safari on my iPhone (system updated to iOS 16 beta 3),  then visit the url.

### Minimal reproduction project
Simply visit this exported page at the following url:
[https://dl.lookingpet.com/temp/ios16_test/game.html](https://dl.lookingpet.com/temp/ios16_test/game.html)

source code:
[ios16_test1.zip](https://github.com/godotengine/godot/files/9060230/ios16_test1.zip)

**Comment by Chaosus** [comment]
Duplicate of https://github.com/godotengine/godot/issues/62445

**Comment by akien-mga** [comment]
I'm not sure that's the same issue, we need to know what the actual errors are. AFAIK current Safari should support WebGL 2.

**Comment by clayjohn** [comment]
> Webpage exported keep reloading, and safari reported a loading error.

Can you post the text of the errors you receive?

**Comment by nne998** [comment]
> > Webpage exported keep reloading, and safari reported a loading error.
> 
> Can you post the text of the errors you receive?

Here is the screenshot:
![IMG_0055](https://user-images.githubusercontent.com/148901/176143445-3129be61-803a-4c5d-ae14-a5a43dda39ff.PNG)

**Comment by nne998** [comment]
I recorded a video:
https://user-images.githubusercontent.com/148901/176145128-5d71051b-2866-4b20-b380-34597202468e.MP4

**Comment by akien-mga** [comment]
Could you get logs from Safari's Web Inspector? Not familiar with it myself but it seems it needs to be set up on a Mac to debug the iOS Safari from macOS Safari: https://appletoolbox.com/use-web-inspector-debug-mobile-safari/

**Comment by nne998** [comment]
> Could you get logs from Safari's Web Inspector? Not familiar with it myself but it seems it needs to be set up on a Mac to debug the iOS Safari from macOS Safari: https://appletoolbox.com/use-web-inspector-debug-mobile-safari/

There is no errors on safari's console output:
<img width="702" alt="WX20220628-174004@2x" src="https://user-images.githubusercontent.com/148901/176147340-d859fc77-a2c2-452b-bdfc-dbe53dfb9cd5.png">

**Comment by nne998** [comment]
<img width="836" alt="111" src="https://user-images.githubusercontent.com/148901/176153044-c642c106-6d5d-4946-8a2b-f183fbe1e7b3.png">

**Comment by Faless** [comment]
You seem to be using the JavaScript<->Godot interface, and there seem to be errors in your code:
```
ERROR: No interface 'game' registered
ERROR: No interface 'eventFn' registered
```

Those errors happen when `JavaScript::get_inferface` function cannot find the JavaScript object which you are requesting it to get.

- Does the project work on desktop browsers?
- Can you provide a minimal reproduction project?
- If not, can you at least provide a link where we can check the exported game?

There isn't much more we can do otherwise with the current information as this seem to be a problem with your JavaScript code but we have no way to verify it.

**Comment by nne998** [comment]
> You seem to be using the JavaScript<->Godot interface, and there seem to be errors in your code:
> 
> ```
> ERROR: No interface 'game' registered
> ERROR: No interface 'eventFn' registered
> ```
> 
> Those errors happen when `JavaScript::get_inferface` function cannot find the JavaScript object which you are requesting it to get.
> 
> * Does the project work on desktop browsers?
> * Can you provide a minimal reproduction project?
> * If not, can you at least provide a link where we can check the exported game?
> 
> There isn't much more we can do otherwise with the current information as this seem to be a problem with your JavaScript code but we have no way to verify it.


Hi, the project work find on desktop, ios 14/15, andoid etc.   But Not good on  ios 16.

**Comment by nne998** [comment]
> > Even I create a fresh new project , it is the same issue.
> 
> Could you get logs from Safari's Web Inspector **of the fresh new project**?


Hi, there is no special error log for the fresh new project:

<img width="734" alt="WX20220707-115214@2x" src="https://user-images.githubusercontent.com/148901/177687074-84b4ce5f-b9fd-4d72-9e26-2dfa68580629.png">


And this is the simple demo project (create a fresh new project, add a simple button control , then export to html5):
[ios16_test1.zip](https://github.com/godotengine/godot/files/9060223/ios16_test1.zip)

**Comment by nne998** [comment]
updated: iOS 16 beta 3,  same issue.

**Comment by michaldev** [comment]
I have the same problem with iOS 16 beta 2-3 and godot 3.5 (latest rc).

**Comment by nne998** [comment]
This is a big problem, please fix, thank you

**Comment by akien-mga** [comment]
See #63525 for another MRP and hosted web game:

> Simply visit this exported page at the following url:
> [https://dl.lookingpet.com/temp/ios16_test/game.html](https://dl.lookingpet.com/temp/ios16_test/game.html)
>
> project source code:
> [ios16_test1.zip](https://github.com/godotengine/godot/files/9197050/ios16_test1.zip)

**Comment by michaldev** [comment]
> See #63525 for another MRP and hosted web game:
> 
> > Simply visit this exported page at the following url:
> > https://dl.lookingpet.com/temp/ios16_test/game.html
> > project source code:
> > [ios16_test1.zip](https://github.com/godotengine/godot/files/9197050/ios16_test1.zip)

It doesn't work on iOS 16.

**Comment by akien-mga** [comment]
[According to this tweet](https://mobile.twitter.com/BrendanDuncan42/status/1552425062791544832), this might be due to a regression in iOS 16 beta 3 which has been fixed in beta 4: https://bugs.webkit.org/show_bug.cgi?id=242294

It seems like it was just released, please upgrade and let us know if that solves the crash.

**Comment by michaldev** [comment]
Problem solved. I've tested on iOS 16 beta 4.

**Comment by nne998** [comment]
Yeah！It's fixed!!
