### ISSUE TITLE
Clicking on nodes in the scene tree emits errors:  `Condition "!pointer_mode" is true. Returning: String()`

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#62461]
### Godot version

c41e4b10c3317f837d4b3ece2fb725a8067d884b

### System information

Windows 11

### Issue description

![bug](https://user-images.githubusercontent.com/3036176/175973739-268b0fea-547c-4121-9e48-042075e74510.gif)

### Steps to reproduce

Simply click on any node - it also emits at any scene loading

**Comment by vnen** [comment]
I think I fix that in #62470
