### ISSUE TITLE
dlopen failed: cannot locate symbol "in6addr_any"

### ISSUE THREAD

**Issue by AbanoubNassem** [godotengine/godot#62464]
### Godot version

4.0.alpha10

### System information

(Android Device)Oppo Mirror 5 Android 5.1 (Lollipop), ColorOS 2.1

### Issue description

Android app crashes with the following:
```

E/art     (32345): dlopen("/data/app/org.godotengine.godot4-1/lib/arm/libgodot_android.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "in6addr_any" referenced by "libgodot_android.so"...
E/AndroidRuntime(32345): FATAL EXCEPTION: main
E/AndroidRuntime(32345): Process: org.godotengine.godot4, PID: 32345
E/AndroidRuntime(32345): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "in6addr_any" referenced by "libgodot_android.so"...
E/AndroidRuntime(32345): 	at java.lang.Runtime.loadLibrary(Runtime.java:372)
E/AndroidRuntime(32345): 	at java.lang.System.loadLibrary(System.java:988)
E/AndroidRuntime(32345): 	at org.godotengine.godot.GodotLib.<clinit>(GodotLib.java:48)
E/AndroidRuntime(32345): 	at org.godotengine.godot.Godot.initializeGodot(Godot.java:461)
E/AndroidRuntime(32345): 	at org.godotengine.godot.Godot.onCreate(Godot.java:602)
E/AndroidRuntime(32345): 	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
E/AndroidRuntime(32345): 	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
E/AndroidRuntime(32345): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
E/AndroidRuntime(32345): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
E/AndroidRuntime(32345): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
E/AndroidRuntime(32345): 	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1971)
E/AndroidRuntime(32345): 	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:311)
E/AndroidRuntime(32345): 	at org.godotengine.godot.FullScreenGodotApp.onCreate(FullScreenGodotApp.java:69)
E/AndroidRuntime(32345): 	at com.godot.game.GodotApp.onCreate(GodotApp.java:45)
E/AndroidRuntime(32345): 	at android.app.Activity.performCreate(Activity.java:6085)
E/AndroidRuntime(32345): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
E/AndroidRuntime(32345): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2373)
E/AndroidRuntime(32345): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
E/AndroidRuntime(32345): 	at android.app.ActivityThread.access$900(ActivityThread.java:164)
E/AndroidRuntime(32345): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1377)
E/AndroidRuntime(32345): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(32345): 	at android.os.Looper.loop(Looper.java:150)
E/AndroidRuntime(32345): 	at android.app.ActivityThread.main(ActivityThread.java:5408)
E/AndroidRuntime(32345): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(32345): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(32345): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
E/AndroidRuntime(32345): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
E/WindowState(  877): getStack: Window{895cd7f u0 Starting org.godotengine.godot4} couldn't find taskId=21 Callers=com.android.server.wm.WindowState.getDisplayContent:891 com.android.server.wm.WindowState.getWindowList:1517 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2934 com.android.server.wm.WindowManagerService.removeWindowLocked:2824 
E/WindowState(  877): getStack: Window{895cd7f u0 Starting org.godotengine.godot4} couldn't find taskId=21 Callers=com.android.server.wm.WindowState.getDisplayContent:891 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2939 com.android.server.wm.WindowManagerService.removeWindowLocked:2824 com.android.server.wm.WindowManagerService.removeWindowLocked:2739 
```

### Steps to reproduce

export apk to Android

**Comment by Calinou** [comment]
> MacOS Vulkan API 1.1.198 - Using Vulkan Device #0: AMD - AMD Radeon Pro 455

Is the exported project running on the device crashing, or is the *editor* running on your Mac crashing? Judging from the log, it's the former, but please clarify just in case.

Also, what's your Android device model and version?

**Comment by AbanoubNassem** [comment]
> > MacOS Vulkan API 1.1.198 - Using Vulkan Device #0: AMD - AMD Radeon Pro 455
> 
> Is the exported project running on the Android device crashing, or is the _editor_ running on your Mac crashing? Judging from the log, I assume it's the former, but please clarify just in case.
> 
> Also, what's your Android device model and version?

sorry for the confusion , I have updated the issue.

**Comment by wadim-al** [comment]
Same here, can reproduce on Android 6.0.1 with 4.0.beta1



`
--------- beginning of crash
09-16 20:08:17.634  5736  5736 E AndroidRuntime: FATAL EXCEPTION: main
09-16 20:08:17.634  5736  5736 E AndroidRuntime: Process: org.godotengine.game1spaceshooter, PID: 5736
09-16 20:08:17.634  5736  5736 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "in6addr_any" referenced by "/data/app/org.godotengine.game1spaceshooter-2/lib/arm64/libgodot_android.so"...
09-16 20:08:17.634  5736  5736 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary(Runtime.java:372)
09-16 20:08:17.634  5736  5736 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1076)
09-16 20:08:17.634  5736  5736 E AndroidRuntime: 	at org.godotengine.godot.GodotLib.<clinit>(GodotLib.java:51)
09-16 20:08:17.634  5736  5736 E AndroidRuntime: 	at org.godotengine.godot.Godot.initializeGodot(Godot.java:499)
09-16 20:08:17.634  5736  5736 E AndroidRuntime: 	at org.godotengine.godot.Godot.onCreate(Godot.java:637)
09-16 20:08:17.634  5736  5736 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
09-16 20:08:17.634  5736  5736 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
09-16 20:08:17.634  5736  5736 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
09-16 20:08:17.634  5736  5736 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
09-16 20:08:17.634  5736  5736 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
09-16 20:08:17.634  5736  5736 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1971)
09-16 20:08:17.634  5736  5736 E AndroidRuntime: 	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:311)
09-16 20:08:17.634  5736  5736 E AndroidRuntime: 	at org.godotengine.godot.FullScreenGodotApp.onCreate(FullScreenGodotApp.java:69)
09-16 20:08:17.634  5736  5736 E AndroidRuntime: 	at com.godot.game.GodotApp.onCreate(GodotApp.java:45)
09-16 20:08:17.634  5736  5736 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6321)
09-16 20:08:17.634  5736  5736 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
09-16 20:08:17.634  5736  5736 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
09-16 20:08:17.634  5736  5736 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2535)
09-16 20:08:17.634  5736  5736 E AndroidRuntime: 	at android.app.ActivityThread.access$1100(ActivityThread.java:154)
09-16 20:08:17.634  5736  5736 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1396)
09-16 20:08:17.634  5736  5736 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-16 20:08:17.634  5736  5736 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
09-16 20:08:17.634  5736  5736 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5582)
09-16 20:08:17.634  5736  5736 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-16 20:08:17.634  5736  5736 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-16 20:08:17.634  5736  5736 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
`

**Comment by alextrevisan** [comment]
Same here, Android 6.0.1, Godot v4.0.beta2.official [f8745f2f7]

```
2022-10-07 21:43:35.200 7145-7145/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.godotengine.testandroid, PID: 7145
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "in6addr_any" referenced by "/data/app/org.godotengine.testandroid-1/lib/x86_64/libgodot_android.so"...
        at java.lang.Runtime.loadLibrary(Runtime.java:373)
        at java.lang.System.loadLibrary(System.java:1076)
        at org.godotengine.godot.GodotLib.<clinit>(GodotLib.java:51)
        at org.godotengine.godot.GodotLib.initialize(Native Method)
        at org.godotengine.godot.Godot.initializeGodot(Godot.java:499)
        at org.godotengine.godot.Godot.onCreate(Godot.java:637)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1971)
        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:311)
        at org.godotengine.godot.FullScreenGodotApp.onCreate(FullScreenGodotApp.java:69)
        at com.godot.game.GodotApp.onCreate(GodotApp.java:45)
        at android.app.Activity.performCreate(Activity.java:6279)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2499)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2606)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1444)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5654)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:782)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:672)

```

**Comment by m4gr3d** [comment]
@akien-mga According to https://github.com/cernekee/ics-openconnect/issues/37#issuecomment-422830206, this is a NDK build issue which occurs on certain devices and versions of Android when selecting an NDK target api > 21.

Our ndk Android target api was updated from `18` to `24` in https://github.com/godotengine/godot/pull/36919 due to [Android vulkan requirements](https://developer.android.com/ndk/guides/graphics/getting-started#preparing), so there is no easy fix and it looks like we may have to drop vulkan support for Android devices that don't have Android 7 (api 24) or higher.
