### ISSUE TITLE
Game on Retina Display (OSX)

### ISSUE THREAD

**Issue by paezao** [godotengine/godot#6246]
**Operating system or device - Godot version:**
OSX El Capitan 10.11.2 - Godot 2.1

**Issue description** (what happened, and what was expected):
Editor is working correctly but Game is not high dpi on a retina display. I've set the game width and height to 640x400 and the game is showing using the real monitor resolution instead of the high dpi for better visual quality.

**Steps to reproduce:**
Just set a resolution like 640x400 using a retina display on OSX and run the game, the window will be a lot smaller than expected.

**Comment by reduz** [comment]
Check display settings, there is an option somewhere to enable it for the
game

**Comment by paezao** [comment]
I have use_hidpi_theme ON and allow_hidpi ON.

Is there any other option?

**Comment by Calinou** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.
