### ISSUE TITLE
 core/math/transform_2d.cpp:49 - Condition "det == 0" is true.

### ISSUE THREAD

**Issue by AbanoubNassem** [godotengine/godot#62463]
### Godot version

3.4.4 , 3.5 , 4.0.alpha10

### System information

MacOS, OpenGL ES 2.0 Renderer: AMD Radeon Pro 455 OpenGL Engine

### Issue description

trying to add `Bone2D` to `Skeleton2D` , and it keep showing this in the output:

` core/math/transform_2d.cpp:49 - Condition "det == 0" is true.`
 
and it happens also when trying to `Reset to rest pos`

### Steps to reproduce

just adding `Bone2D` to `Skeleton2D` will trigger the error

### Minimal reproduction project

https://github.com/AbanoubNassem/godot-Skeleton2D:
goto Node2D scene > select Skeleton2D > Reset to Rest Pos

**Comment by AbanoubNassem** [comment]
> Related to #47757 and #60287.
> 
> I suppose something is being scaled to 0 on an axis when it's not meant to be.
> 
> @AbanoubNassem Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

done , I have updated the issue with the project

**Comment by Calinou** [comment]
@AbanoubNassem The minimal reproduction project is 404. If you can still reproduce this issue on 4.0.rc2, please upload the project somewhere it can be reached :slightly_smiling_face:

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.

PS: Since no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) is available anymore, please upload one as well to ease troubleshooting.

**Comment by minec-c** [comment]
##I'm using godot 3.5 and I fix the error **ERROR: Condition "det == 0" is true.   at: affine_invert (core/math/transform_2d.cpp:49)** by  using the following code (yeah, I'm adding bone2d through code):
bone2D.rest = Transform2D(Vector2(1,0),Vector2(0,1),Vector2(11,11))
##The 'x' value and 'y' value of Vector2(11,11)  can be what ever you want, those are just the position on the viewport.
