### ISSUE TITLE
[Script Editor] Allow scrolling past code

### ISSUE THREAD

**Issue by alxxlc** [godotengine/godot#6247]
Allowing the user to scroll past the code to give space between the end of code and the bottom of the Godot window would help a lot. This would stop the user from having to look at the very bottom of their screen in order to write script at the very bottom of their file. SublimeText has this feature and I've included a screenshot of it to show what I mean.

![sublimescreen](https://cloud.githubusercontent.com/assets/1102632/17871909/646c6604-6883-11e6-86e2-ca576c6abd65.png)

As it stands right now, the script editor in Godot does not allow you to scroll past the final line of code being placed on the final line of the editor. SublimeText handles this feature the best way I've seen and it would be great if Godot could reproduce it. ST allows the user to scroll completely past the code all the way down until the final line of code has reached the top line of the editor.

This feature can be worked around right now by just creating a bunch of empty lines at the end of the code but that just feels sloppy and it would be nice if that didn't need to be done.

**Comment by vnen** [comment]
There's already an option for that (though disabled by default):

![godot windows opt tools 32_2016-08-22_18-38-07](https://cloud.githubusercontent.com/assets/5599796/17872704/aaa6c024-6897-11e6-878d-a56e6876638b.png)

**Comment by alxxlc** [comment]
That's great! It works exactly like I was hoping too. I missed those settings when I was looking for a setting like that.

That's definitely something that I think should be a default setting. Thanks for the quick response and help!

**Comment by LightningAA** [comment]
I agree this should be the default setting, is there a reason it isn't?
