### ISSUE TITLE
Chinese input method don't work when renaming a Node ?

### ISSUE THREAD

**Issue by linyangqi** [godotengine/godot#62476]
### Godot version

4.0 alpha 10

### System information

Windows 11

### Issue description

Some other input field is able to directly use Chinese pinyin input method.
However, when I was trying to rename a Node in a scene tree after pressing f2, pinyin input won't work.
 -- the input is locked to English and I couldn't switch, just like no input field is detected.
Probably because when renaming a Node, OS hasn't found that there was a input filed. (other input field worked correctly)

(now I am having to use clipboard to rename Nodes into Chinese )

### Steps to reproduce

just rename a Node from SceneTree, and try inputting Chinese character using pinyin.

**Comment by Rindbee** [comment]
Windows version of #60372.

**Comment by Chaosus** [comment]
Duplicate of #60372
