### ISSUE TITLE
Can't revert exported node

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#62481]
### Godot version

5ab59ee

### System information

Windows 10 x64

### Issue description

When you export Node (after #62470) and assign anything, you won't be able to revert it.
![godot windows tools 64_kTIti8ptYC](https://user-images.githubusercontent.com/2223172/176166616-4a9bcb68-22fc-459d-b1b5-434a2869fe72.gif)
Revert won't clear the node and when you clear it using the button on the right, the arrow doesn't disappear.
(EDIT: The worst part about it is that you will get `NodePath("")` in your tscn that you can't remove without editing the scene manually)

This happens because the revert value of the property is of type `NIL`, while it becomes `NODE_PATH` after being assigned. Thus it can't back to the original value, because it has different type.
The default should be empty NodePath.

### Steps to reproduce

1. Add export variable of type Node
2. Assign some node
3. Try to revert it
4. Good luck

**Comment by Haydoggo** [comment]
Looks like this has been resolved at some point, revert button works fine for Node exports in 4.0 stable
