### ISSUE TITLE
Can't Export or save a scene on Android

### ISSUE THREAD

**Issue by MohamedHelmy03** [godotengine/godot#62488]
### Godot version

3.5 beta 3 (Android Version)

### System information

Android 8.1.0

### Issue description

I am using the **android** version of **Godot** Engine and I can't save my 3D scene, Every time I try to save it **crashes** and my work _wiped,_ I have tried to make a simple 2d game instead and yet again my work _wiped_ and the application ****crashes****.

### Steps to reproduce

Simple 3d scene, adding staticbody as the ground, and a simple cube with it's animation

**Comment by MohamedHelmy03** [comment]
> @MohamedHelmy03 What Android device model are you using?
> 
> While saving a scene shouldn't crash, I don't think _exporting_ a project is currently supported in the Android editor (especially as you can't run any of the exported files directly from the device).

Thank you for your fast response
My Device model is "Samsung Galaxy Tab A6 (2016)"
The App is working good on this device, in 3D Scene it have some lag but this isn't a problem for me.

**Comment by akien-mga** [comment]
Could you test the Android editor from 3.5 RC 5? https://downloads.tuxfamily.org/godotengine/3.5/rc5/Godot_v3.5-rc5_android_editor.apk

Also, are you able to retrieve `adb logcat` logs from the device to get details on the crash?

**Comment by MohamedHelmy03** [comment]
> Could you test the Android editor from 3.5 RC 5? https://downloads.tuxfamily.org/godotengine/3.5/rc5/Godot_v3.5-rc5_android_editor.apk
> 
> Also, are you able to retrieve `adb logcat` logs from the device to get details on the crash?
> 
> CC @m4gr3d

It Actually Work, But After I Changed My Device Language To English (USA)

**Comment by m4gr3d** [comment]
@MohamedHelmy03 what language was it crashing with. We'll try to repro to see if we can isolate the issue.

**Comment by MohamedHelmy03** [comment]
> @MohamedHelmy03 what language was it crashing with. We'll try to repro to see if we can isolate the issue.

Arabic

**Comment by akien-mga** [comment]
I seem to reproduce crashes on my Xiaomi Poco F1 in English with 3.5 RC 5. I'll try to get logs later today.

**Comment by akien-mga** [comment]
Fixed by #62729.
