### ISSUE TITLE
Assigning a value to specified vector component does not working

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#62484]
### Godot version

5ab59ee7df1d344dccc9deef375faa46deb63b8d

### System information

Windows 11

### Issue description

The following code does not assign a correct position to `MeshInstance` node:

```
extends Node3D

@onready var mi = $MeshInstance3D

func _ready():
	var v = Vector3(1, 2, 3)
	mi.position.x = v.x
	mi.position.y = v.y
	mi.position.z = v.z
	print(mi.position)
```

It's printing (0, 0, 0) while it should be (1, 2, 3).
Seems like a recent regression.

### Steps to reproduce

^^

### Minimal reproduction project

[VectorComponentBug.zip](https://github.com/godotengine/godot/files/9000575/VectorComponentBug.zip)

**Comment by cdemirer** [comment]
Regression from #62462.
See: https://github.com/godotengine/godot/pull/62462#discussion_r908361641
