### ISSUE TITLE
Property hint not being used (regression in 3.5.rc4)

### ISSUE THREAD

**Issue by cromerc** [godotengine/godot#62493]
### Godot version

3.5-rc5

### System information

Linux Mint 20.3, Nvidia 1650

### Issue description

When using an exported property hint from GDNative/godot-cpp, it no longer shows the expected types, instead it lists all resource types. And if you try to do a quick load, it shows all resource types in the project as well instead of just Packed Scenes.

This regression started in 3.5-rc4 and is still present in 3.5-rc5. However it worked as expected in 3.5-rc3.

This is the code used to register the property:
`register_property<Main, Ref<PackedScene>>("level", &Main::set_level, &Main::get_level, NULL, GODOT_METHOD_RPC_MODE_DISABLED, GODOT_PROPERTY_USAGE_DEFAULT, GODOT_PROPERTY_HINT_RESOURCE_TYPE, String("PackedScene"));`

Here are some images to show what is happening:
[Click the node to see exported property for the PackedScene](https://postimg.cc/z3sQDS8Q)

[Result(3.5-rc4 and rc5)](https://postimg.cc/zy5PKzLS)

[Expected result(3.5-rc3)](https://postimg.cc/WdnY7BgR)

### Steps to reproduce

1. Build GDNative library.
2. In godot select node that has the GDNative script attached.
3. Try to choose a PackedScene resource.

### Minimal reproduction project

[project.zip](https://github.com/godotengine/godot/files/9003662/project.zip)

This project if run with 3.5-rc4 or rc5 has the regression. I included both the windows and linux GDNative libs already compiled to test it out with.

**Comment by akien-mga** [comment]
This is likely due to #61996 which added new property hints, so godot-headers (and godot-cpp) likely just need syncing.

**Comment by akien-mga** [comment]
Should be fixed by https://github.com/godotengine/godot-cpp/tree/3.x, could you confirm? (Needs recompiling the libs of course)

**Comment by cromerc** [comment]
Yes, that fixed it. Thanks.
