### ISSUE TITLE
AnimationPlayer's advance(0) updates property to first key found in track with UPDATE_DISCRETE, while advance(delta) doesn't

### ISSUE THREAD

**Issue by Streq** [godotengine/godot#62491]
### Godot version

v3.4.4.stable.official [419e713a2]

### System information

Ubuntu 20.04.3 LTS

### Issue description

When an animation track has its first key at a non-zero time, and the mode is set to UPDATE_DISCRETE, `animationPlayer.advance(0)` will update the property to that key, regardless of the position of said key within the track, this is also the case when an animation is set to autoplay. 
This behavior is contradicted by the behavior AnimationPlayer has when `play()` is called, where the property isn't updated until its position in the animation is reached.

Simply put, for this animation:
![image](https://user-images.githubusercontent.com/8540266/176235628-a23a11b2-47c5-4d03-9233-98d1ae682c3f.png)

the code
```
$AnimationPlayer.play("anim")
$AnimationPlayer.advance(0)
```
will instantly update the color to red
while the code
```
$AnimationPlayer.play("anim")
```
will only do so when the animation reaches 0.5 seconds.

### Steps to reproduce

1) Set up a scene like this
![image](https://user-images.githubusercontent.com/8540266/176244291-95bed967-6434-48c6-b68b-2781a773ff96.png)

2) Each AnimationPlayer with these two animations
![image](https://user-images.githubusercontent.com/8540266/176244781-d357badb-b9e5-4302-b749-292cc5324de6.png)
![image](https://user-images.githubusercontent.com/8540266/176244743-fdf05333-bbd7-4a2f-81b3-c1554662ea8e.png)

(notice the track's update mode is marked as discrete) 

3) Attach this script to the node named "advance_0"
```
extends Node2D

func _ready():
	$AnimationPlayer.play("anim")
	$AnimationPlayer.advance(0)
```

4) Attach this script to the node named "no_advance"
```
extends Node2D

func _ready():
	$AnimationPlayer.play("anim")

```

5) Run the scene
6) Notice one sprite is always red(the child of advance_0) while the other remains blue for the time it takes the animation to reach the key frame of the modulate (one second in this example)
![Peek 2022-06-28 14-25](https://user-images.githubusercontent.com/8540266/176245029-ca587345-65b7-4222-908b-4558b8229150.gif)

EDIT: this incongruence is also observed when advance(delta) is called, where delta is a non-zero value, meaning the following code, with $AnimationPlayer's playback set to manual, 
```
extends Node2D

func _ready():
	$AnimationPlayer.play("anim")
func _physics_process(delta):
	$AnimationPlayer.advance(delta)
```
won't instantly update the property to the first found key in the track, the way advance(0) will.

### Minimal reproduction project
[advance_0_bug.zip](https://github.com/godotengine/godot/files/9003483/advance_0_bug.zip)

**Comment by pfertyk** [comment]
Hi! I've submitted a fix, but I'm not sure if it's the right direction ... According to the comment that I've deleted, setting `delta` to 0 means this should work like `seek`. And the behavior of `advance(0)` is the same as `seek(0, true)`, for the mode `UPDATE_DISCRETE`. So, perhaps it's the behavior of the `play` method that should be changed? Could someone provide more info here? :)

**Comment by Streq** [comment]
@pfertyk I'm inclined to believe play() is the one working correctly, though there seems to be a bit of ambiguity: 
- on one hand, according to one of the [tutorials](https://docs.godotengine.org/en/stable/tutorials/animation/introduction.html): 
``` 
"Discrete: Only update the property on keyframes."
```
It seems clear that play() is the one working correctly

- but then the [documentation for Animation](https://docs.godotengine.org/en/stable/classes/class_animation.html) says

```
UPDATE_DISCRETE = 1 --- Update at the keyframes and hold the value.
```
 Which _may_ leave room to interpret that once you play an animation, it should instantly update to the last keyframe on the track (because that would be the value "held" since the last keyframe).
Still, the interpretation that it should only update the value when a keyframe is actually reached seems more intuitive.

**Comment by TokageItLab** [comment]
As I commented in https://github.com/godotengine/godot/pull/62714#issuecomment-1234901434, probably `play()` which acts like a CAPTURE mode, is the wrong behavior.

**Comment by pfertyk** [comment]
I've updated the PR and added a comment, sorry it took me a month :( Please let me know if the solution is correct now.
