### ISSUE TITLE
Recursive search in tree seems to be broken

### ISSUE THREAD

**Issue by Pacifist-Penguin** [godotengine/godot#62505]
### Godot version

4.0.alpha10

### System information

macOS catalina 10.15.7

### Issue description

While trying to make a simple [main menu] (https://github.com/Pacifist-Penguin/godot-main-menu) I ran into an issue with autofocus (or rather lack thereof) in the TabContainer. To fix this, I had to use a recursive tree search, which doesn't seem to work properly.

```gdscript
extends VBoxContainer

func _ready():
	_find_node_to_focus(self)

func _find_node_to_focus(node: Control):
	for child in node.get_children():
		if (child.get_focus_mode() == 2):
			print(child)
			child.grab_focus()
			return
		else:
			_find_node_to_focus(child)
```

Expected behavior:
script prints one button and focuses on it

What I got:
prints N buttons
focuses the first button in the last container

### Steps to reproduce

Just run the MinimalReproducableBugReport.tscn i guess

### Minimal reproduction project

[minimal-reproducable-recursion-bug.zip](https://github.com/godotengine/godot/files/9006747/minimal-reproducable-recursion-bug.zip)

**Comment by Rindbee** [comment]
This is not a bug, the return of the subcall does not affect the loop of the superior call.

In this case, it is recommended to return a boolean value, or add a member variable as a flag to judge whether to break the loop.

**Comment by KoBeWi** [comment]
```GDScript
func _find_node_to_focus(node: Control) -> bool:
	for child in node.get_children():
		if (child.get_focus_mode() == 2):
			print(child)
			child.grab_focus()
			return true
		else:
			if _find_node_to_focus(child):
				return true
	return false
```
