### ISSUE TITLE
Black screen when trying to load a project in Web editor

### ISSUE THREAD

**Issue by mward25** [godotengine/godot#62509]
### Godot version

3.5-rc5

### System information

Arch Linux (updated jun 27) Nvidia 3060 and integrated amd graphics. Using gles2.

### Issue description

you get a black screen when trying to load a project (even an empty one).
previously worked with Godot 3.5-rc1.

### Steps to reproduce

Start the editor, create a new project, then click edit.

### Minimal reproduction project

An empty project will cause this error, so I did not see the need to upload an empty project, if I am wrong please let me know.

**Comment by akien-mga** [comment]
Can you test other RCs to pinpoint when the provmel started?

Could you also post terminal logs from running Godot in verbose mode when it fails?

**Comment by Zireael07** [comment]
I assume provmel is problem?

**Comment by akien-mga** [comment]
Let's consolidate in #62520 which is the same issue.
