### ISSUE TITLE
Search Help: Empty results list when nothing is in the filter box

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot#62508]
### Godot version

3.5rc, 4.0alpha

### System information

windows

### Issue description

I just wanted get a list of all signals in all classes.
So I opened Search help, wasn't ready for surprises.
I selected "signals only" - the results list was so empty.
Same with "properties" , not "classes" this is kinda outstanding.

![image](https://user-images.githubusercontent.com/16458555/176340538-7571e9da-f572-4e51-a9b5-0025257cfc4f.png)

### Steps to reproduce

Press F1 to open Search Help.
Set to Signals Only / something else.
You will see an empty list of signals.
Tested with 3.5, 4.0, windows.

**Comment by Phischermen** [comment]
This appears to be the same behavior in Godot 3.3 too. I'm guessing it's the same in Godot 3.4 too. I notice too that at least 2 characters need to be typed before results start to show. I think I would also prefer seeing a full list of properties, signals, and methods when the search bar is empty.

**Comment by AThousandShips** [comment]
I can take a look at this if that's okay

**Comment by AThousandShips** [comment]
Additionally, constructors and operators do not show up at all, even with searches, this seems to be from #53452 where constructors and operators were separated from other methods but help search did not get updated to reflect this

I'll take a look at a solution to this

**Comment by AThousandShips** [comment]
I've worked out a change for this and I'll open a PR for it if this is an enhancement that's wanted, I'm new to contributing so not sure exactly what the workflow is (and didn't manage to figure it out from the documentation sorry) so not wanting to open a PR if it's the wrong thing to do

**Comment by Phischermen** [comment]
Awesome! Have you seen this [page?] (https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html) It lists the steps for making a PR.

**Comment by AThousandShips** [comment]
I have! And been learning the ropes for that! Thank you
