### ISSUE TITLE
Camera Zoom acting differently on Mac and Windows

### ISSUE THREAD

**Issue by vitorventurin** [godotengine/godot#62519]
### Godot version

4.0 alpha

### System information

Windows,  MacOSX

### Issue description

extends Camera2D

func zoom_to_player(player_position):
	global_position = player_position
	self.zoom = Vector2(1.6, 1.6) ### Running on Windows, it zooms in, while on MacOSX, it zooms out
	set_process(false)

### Steps to reproduce

No steps necessary.  Just run on Mac and Windows, to see the difference

### Minimal reproduction project

No steps necessary.  Just run on Mac and Windows, to see the difference

**Comment by akien-mga** [comment]
> 4.0 alpha

4.0 has been in alpha for 6 months :) Please specify which alpha build you're using exactly (alpha 10, or specific commit you built yourself, etc.).

**Comment by Calinou** [comment]
Camera2D zoom was inverted in https://github.com/godotengine/godot/pull/57392.

**Comment by akien-mga** [comment]
I think this was a misunderstanding from using two different versions of Godot before and after that change.
