### ISSUE TITLE
Window has `unresizable` and `unfocusable` properties, breaking the usual convention of always-positive properties

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#62529]
### Godot version

4.0.alpha10

### System information

Fedora 36, GeForce GTX 1080 (NVIDIA 510.68.02)

### Issue description

The Window class has `unresizable` and `unfocusable` properties. However, in 4.0, properties are generally expected to always be in positive form. Therefore, I suggest inverting those properties' behavior and renaming them to `resizable` and `focusable` respectively (similar to how the `resizable` project setting is in 3.x.

### Steps to reproduce

- Add a Window node and look at its properties.

### Minimal reproduction project

N/A

**Comment by YeldhamDev** [comment]
I agree, but considering this is a breaking change and we're close to release, we either do it right now, or leave it for 5.0.

**Comment by akien-mga** [comment]
It's too late to change this now.
