### ISSUE TITLE
Strange output on debug console.

### ISSUE THREAD

**Issue by FlavoredCactus** [godotengine/godot#6252]
**Operating system or device - Godot version:**
https://github.com/godotengine/godot/commit/2cf781d3c66cbc53739ff91d4608ac979ae17262 windows 10 64 bit, compiled with mingw-64

**Issue description** (what happened, and what was expected):
Booted up the compiled executable, strange text in output. made a quick test with printing text, text displayed in engine output but not the cmd output. getting strange gibberish instead
![4kieepj](https://cloud.githubusercontent.com/assets/6185415/17885168/f8700d2c-68e9-11e6-8ba8-604a2bc5ec4f.png)

**Steps to reproduce:**
scons platform=windows
wait for compile, compile finishs
launch godot.

**Link to minimal example project** (optional but very welcome):

**Comment by ktksgit** [comment]
**Operating system or device - Godot version:**

Same issue with:
Built for Windows 7 and Godot 64 Bit
MinGW-w64 with gcc 4.8.3
Godot 2.1 branch (commit 9c8ecb45f8)
Godot master branch

![godot gcc4 8 3-non-sense](https://cloud.githubusercontent.com/assets/11790344/21957677/1dd056b6-da9c-11e6-84ce-7f9006481e07.jpg)

**Commits**:

commit 5b27f05e7e Godot 2.1 branch
OR commit f28ff8a208 Godot master branch

Discussion here: #7116
@akien-mga

**Fixing this issue at gcc 4.8.3 with reverting the above mentioned commits:**

or in other words, using lowercase %s

```
#ifdef __MINGW32__
	if (p_stderr)
		fwprintf(stderr, L"%s", wbuf);
	else
		wprintf(L"%s", wbuf);
#else // MSVC
```
![godot gcc4 8 3](https://cloud.githubusercontent.com/assets/11790344/21957675/147a58f0-da9c-11e6-9131-7a97193fbd7e.jpg)

(note: compiling without ssl support)

**Comment by vnen** [comment]
So this is dependent on GCC version?

**Comment by ktksgit** [comment]
Maybe.
If we would know which compiler version @jay3d and @FlavoredCactus are using

**Comment by FlavoredCactus** [comment]
I wish i remembered. since this incident i started using linux to compile since its must easier.  according to my original post it was compiled with mingw-64

**Comment by akien-mga** [comment]
Someone with both MSVC and MinGW needs to look into this and find the proper formats :) http://stackoverflow.com/questions/17700797/printf-wprintf-s-s-ls-char-and-wchar-errors-not-announced-by-a-compil

**Comment by Faless** [comment]
> Someone with both MSVC and MinGW needs to look into this and find the proper formats :)

I think the proper way should be to use `%ls` which specifies the compiler that the parameter is a pointer to a wchar_t, so no matter what compiler/standard library we use it should work.
See [cpp reference](http://en.cppreference.com/w/cpp/io/c/fwprintf), conversion specifier 's':
```
If the l specifier is used, the argument must be a pointer to the initial element of an array of wchar_t. 
```

It seems to compile and output just fine with both MinGW and MSVC (although I was affected by this bug, so the original poster of #7116 could double check)
