### ISSUE TITLE
Vulkan: Error spam when SSIL is enabled in a specific scene

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#62525]
### Godot version

4.0.alpha (44516d1a5)

### System information

Fedora 36, GeForce GTX 1080 (NVIDIA 510.68.02)

### Issue description

While testing https://github.com/godotengine/godot/pull/62478, I went for the MRP of https://github.com/godotengine/godot/issues/56723 and noticed it spams error messages whenever SSIL is enabled in the Environment resource:

```
ERROR: Uniforms supplied for set (2):
Set: 1 Binding: 0 Type: Image Writable: Y Length: 1
are not the same format as required by the pipeline shader. Pipeline shader requires the following bindings:
Set: 0 Binding: 0 Type: CombinedSampler Writable: Y Length: 1
Set: 1 Binding: 0 Type: Image Writable: Y Length: 1
Set: 2 Binding: 0 Type: Image Writable: N Length: 1
   at: compute_list_dispatch (drivers/vulkan/rendering_device_vulkan.cpp:8250)
```

No screen-space indirect lighting is visible in the 3D editor viewport. No other features are enabled in Environment.

This doesn't occur in a brand new project with SSIL enabled, only with the MRP linked below.

### Steps to reproduce

- Download the minimal reproduction project below and import it.

### Minimal reproduction project

https://github.com/godotengine/godot/files/7854794/test_ssil_3.zip

**Comment by cridenour** [comment]
I'm seeing this error spam in an upgraded project and can't find a root cause. Just a new scene in an old project, no WorldEnvironment or default environment, with a camera, light and gltf mesh (CSG has no issues) will spam these errors. But with the same asset on a new project, no errors.

**Comment by HunterNN** [comment]
Same problem here. Older project spamming those errors, but when I rebuild it in a new project with the same settings and environment, the errors are gone. In my project the gpu particles triggers those errors (as soon as it emmits, even without particle material).

**Comment by Calinou** [comment]
> Same problem here. Older project spamming those errors, but when I rebuild it in a new project with the same settings and environment, the errors are gone. In my project the gpu particle triggers those errors (as soon as it emits, even without particle material). SSIL is not active in my project.

This is an unrelated issue, likely related to https://github.com/godotengine/godot/issues/57471.

**Comment by HunterNN** [comment]
> > Same problem here. Older project spamming those errors, but when I rebuild it in a new project with the same settings and environment, the errors are gone. In my project the gpu particle triggers those errors (as soon as it emits, even without particle material). SSIL is not active in my project.
> 
> This is an unrelated issue, likely related to #57471.

I don't think it is related to your suggestion, since the error came up with alpha 11. In Alpha 10 it worked without any errors. Now the particles aren't even visible. Also I don't have to add particle material to get the error.

**Comment by cridenour** [comment]
If you haven't looked at this reply in #62803 - check it out. The user shader_cache likely contains the culprit.

https://github.com/godotengine/godot/issues/62803#issuecomment-1178265235

Go to Project -> Open User Data Folder, delete shader_cache and reload the editor. Errors gone, no project changes needed.

**Comment by Calinou** [comment]
Closing per @cridenour's comment. Please continue the discussion about shader cache invalidation in https://github.com/godotengine/godot/issues/63056 :slightly_smiling_face:
