### ISSUE TITLE
Godot Web Editor 3.5 RC5 fully broken (since 3.5 RC 3)

### ISSUE THREAD

**Issue by belzecue** [godotengine/godot#62520]
### Godot version

3..5 RC5 Web Editor version

### System information

Any combination of Linux/Windows Chrome/Firefox and GPU

### Issue description

~~The old Web Editor (3.4.4-stable) at https://editor.godotengine.org/releases/latest/ works for me until I try to run a simple project (rotating cube), at which point it just shows a grey screen.  This web editor instance seems to produce a lot of errors in the browser console but nonetheless seems to work fine right up to the failure point described above.~~ _EDIT: Ignore, I was missing a camera in this 3d scene!_

The new Web Editor (3.5 RC5) at https://editor.godotengine.org/releases/3.5.rc5/ never makes it to the editor for me. I can create a new project but that's as far as I can go in any Chrome/Firefox on Windows/Linux.  It never shows the editor as loaded and ready, just a black screen.  I get the same outcome from my modest Linux NUC with integrated Intel graphics and my games-ready Windows desktop with dedicated GPU (GTX 980).

I posted about this issue on Reddit to canvas how widespread the issue is, or if it was just something at my end.

https://www.reddit.com/r/godot/comments/vmiizy/godot_online_web_editor_never_works_for_me_how/

I got only two responses from the 4K views to date, both confirming the RC5 web editor was not working in the same manner I had described.  Based on my testing across a high end and low end system, plus the two confirmatory responses from Reddit, I am inclined to think the web editor is in a declining state of operation.  Based on the lack of responses to my Reddit post, it seems very few people use the web editor -- which is a shame because I consider it a clever and useful tool for quick prototyping and learning Godot while away from your usual devices.

Thanks for taking a look into this.

### Steps to reproduce

I can collect more detailed browse console error logs etc. upon request, but I'm fairly sure that devs will be able to repro this for themselves without much effort by inspecting the browser console while accessing the stable and RC5 instances of the web editor.

### Minimal reproduction project

Probably not required, but will record a video upon request.

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/57592 and https://github.com/godotengine/godot/issues/61438.

**Comment by belzecue** [comment]
FYI still broken in RC6.

https://user-images.githubusercontent.com/1931303/177997344-fc088680-0f3e-49bd-89bd-8d7ab8d9f291.mp4

.

**Comment by belzecue** [comment]
Confirmed working now for RC6!  Thanks for the super speedy fix.
