### ISSUE TITLE
Unity can use Rigidbody.MovePosition() to pierce the enemy, How to do it with godot?

### ISSUE THREAD

**Issue by PoisonousGame** [godotengine/godot#62526]
### Godot version

v3.4.4 stable official

### System information

Win11  GeForce GTX1060 6GB

### Issue description

Unity can use Rigidbody.MovePosition() to pierce the enemy, how does godot do it?
https://docs.unity3d.com/ScriptReference/Rigidbody.MovePosition.html

![image](https://user-images.githubusercontent.com/39994989/176485773-7c1a4b4e-53bb-43ff-b6b8-cd2315839292.png)

When rigidbody is set to kinematic, RigidBody.MovePosition ignores collisions, so MovePosition can be used to pierce the enemy. How to do it with godot?

### Steps to reproduce

/

**Comment by akien-mga** [comment]
This issue tracker is for bug reports, not for user support. Please use other community platforms for this (e.g. Discord, Reddit, Forum, etc.).
