### ISSUE TITLE
Godot Vibrate Null Pointer Exception

### ISSUE THREAD

**Issue by likeich** [godotengine/godot#62537]
### Godot version

3.4.4

### System information

Samsung Galaxy J7 Prime Android 8.1

### Issue description

I received a null pointer exception in the vibration code of Godot on Android. I only received two reports of this issue so it seems to be pretty rare
![Screenshot_20220630-072645_Play Console](https://user-images.githubusercontent.com/57882701/176557368-9166cf36-afe0-4d07-be58-747bb391e932.jpg)
.

### Steps to reproduce

I couldn't reproduce it,

### Minimal reproduction project

Unknown.

**Comment by Calinou** [comment]
@likeich Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

Can you list the device specs and Android versions on which the crash occurred?

**Comment by madmiraal** [comment]
@likeich This is not a Godot issue. This is an Android issue.

We both check for a null pointer and the version of Android that is running before calling `vibrate`:
https://github.com/godotengine/godot/blob/0328664bb5e738ca9a463a497d83795759ff608d/platform/android/java/lib/src/org/godotengine/godot/Godot.java#L429-L435
The crash report provided indicates that the null pointer exception occurs much later in [`Parcel`](https://developer.android.com/reference/android/os/Parcel) an Android container for messages used for reading and writing data of various types.

Note: This is probably a bug in a particular version of Android that probably/hopefully has already been fixed. There were some changes done about seven months ago to deprecate various unsafe `Parcel `APIs: https://android.googlesource.com/platform/frameworks/base/+log/master/core/java/android/os/Parcel.java that addressed a number of existing Android bugs. And the line referenced in the crash report doesn't currently point to any obvious source of a null pointer exception: https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/os/Parcel.java

**Comment by likeich** [comment]
@madmiraal alright, thanks for looking into it!
