### ISSUE TITLE
debug_print option for printing stuff to the debugger window?

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#6253]
**Operating system or device - Godot version:**
OS is N/A, Godot version? 2.0 and up I guess.

**Issue description** (what happened, and what was expected):
Inspired by https://twitter.com/ProbDenis/status/741981375604137984 - when running a game in debug mode (be it in the editor or using a debug-enabled export option), it'd be nice to have a print_debug command (or similar), so that certain types of messages don't get printed in a release game (if run from terminal or whatnot).

Functionally it should be identical to print as-is, other than it not printing to stdout but stderr.

**Comment by vnen** [comment]
Right now you can use `if OS.is_debug_build(): print("text")`.

**Comment by Sslaxx** [comment]
Hadn't been aware of the existence of `OS.is_debug_build`, nice to know something like that exists. But yes, a debug_print would be a little less work there all the same.

**Comment by bojidar-bg** [comment]
@Gastronok The problem with printerr is that it won't show up in the editor at all, which decreases its utility a lot.

**Comment by Calinou** [comment]
Since it is possible to easily implement this feature by adding a very short function to a singleton, I'm closing this. (It is also more flexible this way.)
