### ISSUE TITLE
Texture2DArray update_layer() not working

### ISSUE THREAD

**Issue by alazifk** [godotengine/godot#62535]
### Godot version

4.0 alpha 10

### System information

Win 10, Vulkan Mobile

### Issue description

`void update_layer(image: Image, layer: int)` inherited from ImageTextureLayered when used on a Texture2DArray produces error:
```
E 0:00:00:0874   _ready: Condition "texture.is_valid()" is true.
  <C++ Source>   scene/resources/texture.cpp:3019 @ update_layer()
  <Stack Trace>  TexArray.gd:16 @ _ready()
```

### Steps to reproduce

It is easiest to just run the provided minimal reproduction project because there is some setup involved.

### Minimal reproduction project

[TextureArrayUpdate.zip](https://github.com/godotengine/godot/files/9013823/TextureArrayUpdate.zip)

**Comment by clayjohn** [comment]
Looks like the error should be ``!texture.is_valid()``

https://github.com/godotengine/godot/blob/79fd068a10e9976bf76d16e7cdf749693c9d4200/scene/resources/texture.cpp#L3019

**Comment by KoBeWi** [comment]
Or `is_null()`

**Comment by alazifk** [comment]
@clayjohn I have tested that and it works. Not sure it is the right thing to check though, since I assume ` ImageTextureLayered::update_layer` should do the same checks as `ImageTexture::update`.

```
void ImageTexture::update(const Ref<Image> &p_image) {
	ERR_FAIL_COND_MSG(p_image.is_null(), "Invalid image");
	ERR_FAIL_COND_MSG(texture.is_null(), "Texture is not initialized."); // <---
	ERR_FAIL_COND_MSG(p_image->get_width() != w || p_image->get_height() != h,
			"The new image dimensions must match the texture size.");
	ERR_FAIL_COND_MSG(p_image->get_format() != format,
			"The new image format must match the texture's image format.");
	ERR_FAIL_COND_MSG(mipmaps != p_image->has_mipmaps(),
			"The new image mipmaps configuration must match the texture's image mipmaps configuration");

	RS::get_singleton()->texture_2d_update(texture, p_image);

	notify_property_list_changed();
	emit_changed();

	alpha_cache.unref();
	image_stored = true;
}
```
```
void ImageTextureLayered::update_layer(const Ref<Image> &p_image, int p_layer) {
	ERR_FAIL_COND(!texture.is_valid()); // <---
	ERR_FAIL_COND(p_image.is_null());
	ERR_FAIL_COND(p_image->get_format() != format);
	ERR_FAIL_COND(p_image->get_width() != width || p_image->get_height() != height);
	ERR_FAIL_INDEX(p_layer, layers);
	ERR_FAIL_COND(p_image->has_mipmaps() != mipmaps);
	RS::get_singleton()->texture_2d_update(texture, p_image, p_layer);
}
```
