### ISSUE TITLE
Vulkan: SDFGI broken in `master` (works in 4.0.alpha10)

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#62533]
### Godot version

4.0.alpha (44516d1a5)

### System information

Fedora 36, GeForce GTX 1080 (NVIDIA 510.68.02)

### Issue description

SDFGI is pure black, even when the mesh is marked as static and Read Sky Light is enabled:

### 44516d1a5 (broken)

![2022-06-29_20 12 48](https://user-images.githubusercontent.com/180032/176506997-a156f235-61d4-4304-9b02-8a919d7061eb.png)

### 4.0.alpha10 (working)

![2022-06-29_20 12 09](https://user-images.githubusercontent.com/180032/176506990-aa8655fe-d5f0-43e2-b96a-627e35757972.png)

VoxelGI works in both 4.0.alpha 10 and 44516d1a5.

### Steps to reproduce

- Add a MeshInstance node or several to see light bouncing.
- Enable SDFGI in WorldEnvironment.

### Minimal reproduction project

[test_sdfgi.zip](https://github.com/godotengine/godot/files/9013059/test_sdfgi.zip)

**Comment by SirQuartz** [comment]
I cannot reproduce this (built from commit ce6c4ab86):
<img width="1407" alt="screenshot" src="https://user-images.githubusercontent.com/62965063/176602994-10b26944-e27b-4121-985a-3535b4b73e3f.png">

System Information:
Windows 10
AMD RX 480

**Comment by Calinou** [comment]
I can't reproduce this on daa055d47.
