### ISSUE TITLE
Editor Plugin Ideas, Improvements, Suggestions, etc. Issue.

### ISSUE THREAD

**Issue by reduz** [godotengine/godot#6254]
The Editor plugin API in Godot was mostly done with wishful thinking, and as a way to have a stable and clean API to editor functions (which may vary over time internally, or are not clean enough). 

However, I'm positive that a lot of functionality for what you can do in the editor is missing from this API, thus inaccessible for plugins. 

This issue is for you to write what kind of functions, objects, functionalities, etc. are missing for you, or you would like to be able to access so we add them in the next Godot version.

Feedback very welcome!

**Comment by ndee85** [comment]
Here is a list of features/fixes.

- Fix this mouse offset bug #1885
- Make selected nodes from EditorPlugin.get_selection().add_node(node) also be set in the properties panel or expose a function that can do it
- store editorplugin data in with the addon which is loaded when opening the editor
- function to create thumbnails for scenes

**Comment by neikeq** [comment]
- Expose CanvasItemEditor and SpatialEditor viewports to GDScript #3992

**Comment by leezh** [comment]
+1 on the mouse offset bug. Currently using a messy hack to get it to work.

Also, the ability to show/hide the gizmos in 2D/3D when editing custom nodes. Functionally it doesn't matter since input can be captured, but it would be a nice visual improvement.

**Comment by GlaDOSik** [comment]
- Print() should print to editor output
- Fix this bug #6244
- I don't know if this is a problem on my side but when I made a new node in script and added it as a child to selected node (from callback edit()), the Scene dock didn't update itself
-  Function to generate a thumbnail from script. I would like to make code minimap plugin
- Expose the names of icons in default Theme. I would like to use editor icons to make the look of my plugin consistent. I think I could call `get_base_control().get_theme().get_icon` but I'm not sure where to get the name and type arguments.

**Comment by EdwardAngeles** [comment]
- Draw custom stuff in the scene view from the EditorPlugin so we can draw gizmos for our own Node.

**Comment by Keetz** [comment]
- Communicate directly with the running game/live scene tree from a plugin being able to set a property, call a function and such

- +1 on 'print()' should print to editor output

**Comment by eska014** [comment]
- I haven't found a way to set proper child margins in WindowDialog for nice looking GUIs (C++ AcceptDialog uses `set_child_rect()`, not exposed). Currently I'm copying the margins from `AcceptDialog::get_label()`

- Expose something like CreateDialog for import plugins that create a scene (for root node type selection as in Collada importer)
	- Instead of some sort of CreateDialog, this would be a better long-term solution if feasible: #6215

**Comment by neikeq** [comment]
> - Draw custom stuff in the scene view from the EditorPlugin so we can draw gizmos for our own Node.

> @EdwardAngeles

That's what my comment above is about. You need access to CanvasItemEditor and SpatialEditor viewports/canvases in order to draw on them.

**Comment by GlaDOSik** [comment]
Is there a way of sharing data between plugins? I think it should be possible but some sort of standardized interface would be appreciated.

**Comment by gau-veldt** [comment]
See #5786 
There should be a way for plugins to add a panel to the main editing tab (2D, 3D, Script, etc) in a similar manner like AssetLib does.  Useful for plugins requiring lots of real estate (say such as a plugin to manage a game project's git from within the editor).  Right now there's no way to actually get an editor control into that region.

**Comment by Zylann** [comment]
- Review `edit()` relevance? I feel like `edit` is not really needed in the API, or maybe it needs better behaviour. I began using the `edit()` callback as a way to know when an object I care about is selected, however it is not called when the object is deselected, and in the end I completely based my plugin on the Selection object as I get more info and events.

- Add a way to know when the scene is saved, so the plugin can also save extra data that is not necessarily exported stuff

- Automate custom control deallocation: when a plugin create custom controls, the editor can easily know who created them (owner?) and free them.

- Automate custom type unregistration (same as above)

**Comment by bojidar-bg** [comment]
> Easier access to the cameras (I only know how to get the 3D one, which is an argument of forward_spatial_input_event. The 2D event has no camera argument.)
> @Zylann 

There is no Camera in 2D -- there is just canvas transform AFAIK

**Comment by Zylann** [comment]
@bojidar-bg well, that's what I meant.

**Comment by carlixyz** [comment]
Hi
- Fix the visual Shader editor when you delete something inside there and it automatically hooks your mouse with the output box dragging it at random to anywhere (It's really annoying)
- Add FULLY right click button menu options in the FileSystem navigator to work with the folders icon and not only in the resources. Oh, and when you click anywhere inside this window give the option to create and rename folders (and the option to open it too in the file manager).
- Something crazy: add the option to use the GDscript editor down alongside with the bottom output/debugger/animation window just like the shader editor
(so you can see what's happening in scene).
- Maybe something like an output("print only in debug output") function and use the print() for the console and general purpose.
- Fix the MultiMeshInstance use in Inspector (I know there's the button in the scene menu bar but what's the whole point of the inspector then?)
- I think Project settings should be with the rest of the settings, I know it isn't there for legacy reasons but at least set one entry there as an alternate option.

**Comment by GlaDOSik** [comment]
- I'm with @Zylann about `edit()` relevance. I even think we don't really need make_visible and handles callbacks. EditorSelection has everything we need. And those callbacks act weirdly. If I select a node, I got two edit() callbacks (with same node) and three make_visible callbacks. At least this should be fixed.

- EditorSelection.get_selected_nodes() doesn't return every selected node, if you want to select nodes on multiple tree levels. Like if you select two childs and then their parent, only parent is in the last selection.
![godotselection](https://cloud.githubusercontent.com/assets/3484686/18108748/06bea800-6f0e-11e6-9d97-5028f39d829a.gif)


Could someone verify my two problems please? I hope I'm not doing something wrong.

**Comment by reduz** [comment]
@ndee85 

> Fix this mouse offset bug #1885
fixed
> Make selected nodes from EditorPlugin.get_selection().add_node(node) also be set in the properties panel or expose a function that can do it
added an inspect_object() function to EditorPlugin so it's up to you to do it now
> store editorplugin data in with the addon which is loaded when opening the editor
I think you have get_state() / set_state() to store state in a scene-specific way, is this not enough?
> function to create thumbnails for scenes
Added access to EditorResourcePreview and EditorResourcePreviewGenerator, so you can now request and generate previews for all data types, including your custom ones.
> draw custom stuff from the EditorPlugin
Added proper API for forward_canvas_input_event, forward_draw_over_canvas and update_canvas to EditorPlugin, this should allow you to draw any kind of gizmo for your edited objects.
>enable automatic soft reload for tool scripts
This is already supported, isn't it?

**Comment by reduz** [comment]
@neikeq not kind of sure if I want to expose those, since they may change and are not super clean. What kind of functionality would you like to use from them?

**Comment by reduz** [comment]
@eska014 Added binding to set_child_rect(), will remove this function in 3.0 and make this control behave more container-like (so anything is expanded inside automatically)

**Comment by reduz** [comment]
@gau-veldt Just return true when asked: has_main_screen() in EditorPlugin and it's added as a main plugin after 2D, 3D, Script, etc.

**Comment by neikeq** [comment]
I only wanted them for drawing. Does `forward_draw_over_canvas` work with the SpatialEditor too?

**Comment by reduz** [comment]
@neikeq for Spatial editor you can use a node anywhere for drawing, or you have the Gizmo API.

**Comment by reduz** [comment]
@EdwardAngeles this should be already covered

**Comment by reduz** [comment]
@Zylann , @GlaDOSik  : edit() is meaningful because most Godot editor works on the premise that editors pop up when needed. When selecting and deselecting, you don't necesarily get an edit() call.

The rest sounds like a bug :P

**Comment by reduz** [comment]
@GlaDOSik selection issues should be solved. MultiNodeEdit I suppose you are free from ignoring it. Not sure if it has any use for you, as you can already get the selection.

**Comment by reduz** [comment]
@Zylann I noted for Godot 3.0 to make plugins unregister the custom types and controls they created automatically. Will not do it now because a lot of existing stuff will break.

**Comment by gau-veldt** [comment]
@reduz already tried that func has_main_screen(): return true.  The plugin is not given a control representing that area to actually be able to use it.

**Comment by GlaDOSik** [comment]
@reduz 

> @GlaDOSik selection issues should be solved. MultiNodeEdit I suppose you are free from ignoring it. Not sure if it has any use for you, as you can already get the selection.

Well, I want to know if user selected multiple nodes.  In this case, there is a problem with callback order. If I select a node, I'm getting `handles(object)` callback first and after that signal `selection_changed()`. That means I can't decide how to handle current selection. My brightest idea was to yield in handles and wait for signal `selection_changed()`. It kinda worked but throwed a lot of errors.

So I think the order should be changed. I need `selection_changed()` first and then callback handles.

**Comment by Dillybob92** [comment]
Okay so I was thinking of this idea when diving into the plugins tutorial. The documentation is well-written btw!

Suggestion:
- Ability to add custom items to the context menu scene tree menu.

Example:
![image](https://cloud.githubusercontent.com/assets/10387670/25988234/16459ade-36ac-11e7-8391-a5287f8dc29c.png)

For example, I'm writing a script that will export my levels into json format to be used on my server. Instead of having the node highlighted, then clicking on the button, we can just right  and click our custom menu item to be executed. However, this is just icing on the cake and honestly not sure what everyone thinks, but I think it'll be a cool feature down the road

**Comment by RodeoMcCabe** [comment]
> I noted for Godot 3.0 to make plugins unregister the custom types and controls they created automatically. Will not do it now because a lot of existing stuff will break.

@reduz How stable is the plugin API now? This is something that still needs to be done in 3.0 AFAIK (using alpha1, not recent builds).

**Comment by bfloch** [comment]
Hi @reduz I still see the issue with get_selected_nodes as described by @GlaDOSik in https://github.com/godotengine/godot/issues/6254#issuecomment-243595724 (v2.1.4)

I only get either child nodes or the parent. But if both parent and child is selected only the parent is returned.

Can you point me at the commit that is supposed to fix this or is this something fixed in 3.0?
Thanks!

**Comment by bfloch** [comment]
Ok I think "get_transformable_selected_nodes" in master is what I was expected.
Do you think this can be backported to 2.1.x?

**Comment by remorse107** [comment]
I would like to see MultiNodeEdit exposed to GDScript so that at the very least you can iterate over the collection yourself.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
