### ISSUE TITLE
move_and_collide will change KinematicBody2D's property scale

### ISSUE THREAD

**Issue by yuyw** [godotengine/godot#62544]
### Godot version

3.4.4.stable.official [419e713a2]

### System information

Windows 10, GLES3, Intel HD Graphics 620 (27.20.100.9616)

### Issue description

Calling **move_and_collide** in physics_process will switch value x and y of its property **scale**, e.g. Vector2(-1, 1) -> Vector2(1, -1). No matter the parameter rel_vec for move_and_collide and the return value (KinematicCollision2D) is null or not.

Please pay attention that the behavior of _KinematicBody2D_ is **NOT** changed anymore -- correct look like, correct movement and so on even readback property _scale_ is changed.

I found the above issue while developing my fighter game. The Player 2 is turn around by setting its scale.x = -1. Everything works well until I read back its property scale for some calculation.

### Steps to reproduce

1. Add node _KinematicBody2D_ in tree
2. Set property **scale** of this node as **scale.x** = -1 in function __ready_. Now scale is _Vector2(-1, 1)_ and Sprite on this node is flipped on horizontal direction.
3. Call **move_and_collide** in function __physics_process_, no matter value of the input parameter _rel_vec_
4. Check again the property scale by printing its out then can find its value is changed to Vector2(1, -1). Sprite keeps correct looks like.

**Comment by KoBeWi** [comment]
That's how scale works in 2D, see #17405

**Comment by yuyw** [comment]
@KoBeWi Many thanks for your so prompt support!

I read [https://github.com/godotengine/godot/issues/17405](url) and try the code to modify property **transform** by calling **set_transform**, yes its x and y work well to flip Sprite and more important is its value is read back correctly. Thus my calculation get correct result for player 2.

But could you please help to point out why is "how scale works in 2D" -- I'm still confused why scale swap its x and y.

**Comment by KoBeWi** [comment]
You can find more info here #37376 and in the linked issues.
It's about transform representation in 2D.

**Comment by yuyw** [comment]
@KoBeWi OK many thanks to link more discussions. Now I know something about this point. Hope there will be clear solution since there are so many guys are confused about such weird behavior.
