### ISSUE TITLE
I can't compile for android

### ISSUE THREAD

**Issue by FabriicioMelo** [godotengine/godot#62541]
### Godot version

3.4.4

### System information

Windows 10

### Issue description

I tried for more than 3 hours to compile for android in version 3.4.4, using and not using android studio, but I only managed to compile by going back to version 3.2.1 that I had already installed on my pc, I was always getting the error "apksigner error #1".

### Steps to reproduce

I did the step by step from the Godot website
https://docs.godotengine.org/en/latest/tutorials/export/exporting_for_android.html

### Minimal reproduction project
[Project Pet.zip](https://github.com/godotengine/godot/files/9015710/Project.Pet.zip)

**Comment by akien-mga** [comment]
The issue tracker is for bug reports, but this isn't a bug, it's a configuration issue on your end (which still needs to be determined). I would suggest using one of the other community platforms to get help figuring out what is missing from your setup: https://godotengine.org/community

Typically this might be that you don't have the right version of build tools (30.0.3 or later) or Java (11).
