### ISSUE TITLE
`@onready` fields in parent class aren't executed

### ISSUE THREAD

**Issue by linkpy** [godotengine/godot#62554]
### Godot version

4.0a10

### System information

PopOS!

### Issue description

NodeA : 
```gdscript
@onready var var_a = get_tree()

func _ready():
    print("hello there, from NodeA")
```

NodeB : 
```gdscript
extends NodeA

@onready var var_b = get_tree()
```

If you add a `NodeB` node, after the `_ready` : 
- `var_a` is null
- `var_b` isn't
- The `print` statement is never executed

Adding a `_ready` to NodeB doesn't change this behaviour. The only workaround is to add a `_ready` and manually call `super` in it.

### Steps to reproduce

See above

### Minimal reproduction project

[bug.zip](https://github.com/godotengine/godot/files/9020018/bug.zip)

**Comment by akien-mga** [comment]
This was supposed to be fixed by #62255, and @nathanfranke also reported it as still unfixed but then it somehow got resolved? Can you confirm that you're using the yet-unannounced 4.0 alpha 11 / d631ee3307990a94c75d687fe2269af031886f4b?

**Comment by linkpy** [comment]
@akien-mga Oh sorry I mistyped the version number. I am using alpha 10.
I'll compile godot at the given commit and try again to confirm.

**Comment by KoBeWi** [comment]
You can get alpha11 build here: https://downloads.tuxfamily.org/godotengine/4.0/alpha11/ (it's not yet published)

In any case, this is fixed.

**Comment by linkpy** [comment]
Indeed it is with a11.
