### ISSUE TITLE
FlowContainer icons are too light in Light Theme

### ISSUE THREAD

**Issue by Sosasees** [godotengine/godot#62553]
### Godot version

3.5.rc5.official [ae6059793]

### System information

Debian Linux x64 v10, AMD RX 550, Openbox WM, Compton compositor

### Issue description

the _HFlowContainer_ and _VFlowContainer_ icons keep their _Default_ theme color in _Light_ theme.
this makes good contrast in _Default_ theme but bad contrast in _Light_ theme.

### Steps to reproduce

1. switch editor theme to _Light_
2. click _Add Node_ in the _Scene_ panel
3. navigate to _Node > CanvasItem > Control > Container > FlowContainer > *FlowContainer_
4. see this:
![](https://user-images.githubusercontent.com/66305550/176662987-5273c74f-1bc9-4d49-aeea-ccf974a329b9.png)

### Minimal reproduction project

not needed because this issue can be tested easily in any Godot project

**Comment by KoBeWi** [comment]
The icon colors are automatically converted for light themes, so FlowContainer might be using wrong color (different than other icons).

**Comment by Sosasees** [comment]
> FlowContainer might be using wrong color (different than other icons)

in other words, does that mean that the color code is off by at least 1 bit?

**Comment by KoBeWi** [comment]
Yeah the color needs to match exactly.

**Comment by Sosasees** [comment]
in ``editor/icons/``
i tried editing ``HFlowContainer.svg`` and ``VFlowContainer.svg``,
but i found that the color code is already the same as in ``Control.svg``.

if the color code isn't off, what else could cause the bug?
or was it instantly fixed by someone else? i can't tell until the next Godot 3.x version (release candidate or stable) since i am not good with compiling software myself.

**Comment by akien-mga** [comment]
Fixed by #62559.
