### ISSUE TITLE
Error loading font in editor on OpenBSD 7.1

### ISSUE THREAD

**Issue by omar-polo** [godotengine/godot#62552]
### Godot version

v3.5.rc.custom_build.ae6059793

### System information

OpenBSD 7.1-CURRENT, amdgpu

### Issue description

Fonts don't render on Godot 3.5 rc5, and neither on rc4.  Godot 3.4.4 is fine though!

![image](https://user-images.githubusercontent.com/47739920/176659387-b6d0616b-f3e2-4f2b-8b86-b7e0eaf63bc3.png)

Just to be sure I deleted ~/.config/fontconfig, ~/.config/godot and ~/.local/share/godot too, but to no avail.

This happens only with the Godot Editor; I am able to run games from pck files just fine.

### Steps to reproduce

Just run Godot:

```
% godot-tools
Godot Engine v3.5.rc.custom_build.ae6059793 - https://godotengine.org
OpenGL ES 3.0 Renderer: AMD Radeon Vega 11 Graphics (RAVEN, DRM 3.42.0, 7.1, LLVM 13.0.0)
Async. shader compilation: OFF

ERROR: Error loading font.
   at: _load (scene/resources/dynamic_font.cpp:182)
ERROR: Error loading font.
   at: _load (scene/resources/dynamic_font.cpp:182)
ERROR: Error loading font.
   at: _load (scene/resources/dynamic_font.cpp:182)
...
```

**Comment by omar-polo** [comment]
Yes, I only tried rc4 and rc5.  I'll try to see if rc1, 2 and 3 shows the same problem too and then will try with git bisect.

**Comment by bruvzg** [comment]
The only cause I can think is converting editor fonts to WOFF2, system freetype might be built without brotli support.

**Comment by omar-polo** [comment]
@bruvzg Yes, that's it!  I just tried with rc1 (which had the same issue); once it's built without `builtin_freetype=no` (i.e. with the bundled one) the text rendering works again! \o/

just for curiosity, what was the motivation to move to WOFF2?  Isn't it for the web?

Thanks!

**Comment by akien-mga** [comment]
Yeah it makes the editor 5 MB smaller: #59510

A fourth option to the ones I listed above would be:

4. Allow using system fonts in the editor (and provide a way to only rely on those and skip the builtin fonts), which is something @bruvzg is working on IINM.

But short term I would recommend going with 1. or 2. (1. is best if that's possible for the OpenBSD system package).

**Comment by omar-polo** [comment]
Well, it's outside of my area of expertise, but I doubt 1. is viable (in a short term at least.)  fontconfig is part of [xenocara](https://github.com/openbsd/xenocara) (OpenBSD' version of Xorg) and so is part of the base system.

I guess that for the short term I can go with 2. (using the built-in freetype) hoping it doesn't break.  Option 4 seems really interesting too :)

Thanks!

**Comment by omar-polo** [comment]
I've updated the OpenBSD Godot package to 3.5 using the bundled freetype for the time being.  I've also added a link to the other issue.

Thanks for quickly spotting the issue and for adding a warning in scons, that would have helped!
