### ISSUE TITLE
`print_rich` not working

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#62560]
### Godot version

daa055d479916b9fdb9b6cf3bc6aa822f35a2be6

### System information

Windows 11

### Issue description

Using that function in the code has no effect on the output eg the provided input: 

```
	print_rich("[code][b]Hello world![/b][/code]")
```

Simply prints out  ```[code][b]Hello world![/b][/code]``` without effects which should be applied.

![image](https://user-images.githubusercontent.com/3036176/176730861-77849dd9-8a09-4ba3-9e8d-bb826dfb0929.png)

Color and other tags are not working for me too.

### Steps to reproduce

Create a script - paste code with `print_rich` and run the project

### Minimal reproduction project

Too easy to reproduce.

**Comment by voylin** [comment]
I'll quickly check this when I have time, when I rebased I saw it working within the terminal. I think I know what the issue may be.

**Comment by voylin** [comment]
![Screenshot from 2022-07-01 02-56-22](https://user-images.githubusercontent.com/56970759/176745370-4712d718-2b77-4237-8e6e-701144d85afb.png)
When running the project it prints as expected in the terminal, however, it does not do so inside the Godot editor.

In print_string.cpp on line 172 the while loop get's skipped for some reason not passing the bool for rich text. When I made the print_rich() function I had this problem in the beginning as well, but then I started making the script inside of the Godot editor bigger to print more different kinds of rich text and it started working as expected in the Godot editor as well. My test project works find, but indeed when only creating a program with a single print_rich, then it only gets printed correctly in the terminal.

Will try to fix this asap!

**Comment by voylin** [comment]
Was able to fix it. Wasn't easy as vs code was not working along nicely (as usual). Just passing through the correct type was all that was needed.

![Screenshot from 2022-07-01 04-39-13](https://user-images.githubusercontent.com/56970759/176763118-7e6dc712-1632-4856-b5a2-71317dfa80ae.png)

**Comment by Calinou** [comment]
> @Calinou Sorry about this, fixed it as soon as I could.

No worries :slightly_smiling_face: Thanks for looking into fixing this!
