### ISSUE TITLE
[3.x] ProjectManager freezes upon project creation and Editor freezes when attempting to run the main scene

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot#62564]
### Godot version

3.x at a7559fcb6ef230d9b64f6f71bd7bdd87da7ffcbb

### System information

Arch Linux

### Issue description

Creating a new project or attempting to run a project will freeze the Project Manager or the Editor respectively.

Caused by #62557

### Steps to reproduce

There are two ways to reproduce this.

1. Create a new project using the Project Manager and try to edit the project.

OR

2. Run a project through the Editor (F5).

### Minimal reproduction project
Creating a new project or using an an empty project will suffice. Depends on how the bug is triggered.

**Comment by akien-mga** [comment]
Thanks for testing and reporting it so fast. It was a bit a leap of faith to cherry-pick this so late for 3.5, let's see if we find a solution quickly or if a revert of the cherry-pick is better.

**Comment by Rubonnek** [comment]
Reopening since #62573 hasn't been cherry picked into `3.x` yet -- nightly builds are still freezing.

**Comment by akien-mga** [comment]
It has the cherrypick label and I review those almost on a daily basis with regard to the upcoming release, so I don't really need issues to be kept open when I know I'll fix them with a cherry-pick before the next release.

**Comment by Rubonnek** [comment]
Oh, I see. I will keep that in mind from now on. Thanks.
