### ISSUE TITLE
On android, exporting with a debug template, changing in runtime a property doesn't work

### ISSUE THREAD

**Issue by somebody1121** [godotengine/godot#62566]
### Godot version

v4.0.alpha.custom_build [daa055d47]

### System information

MIUI 13 (Android 12), Poco x3 pro (Adreno 640)

### Issue description

I've been experimenting on making simple text animations, with the animation player making fade in a text work, but using tweens doesn't (at least on my mobile phone), and spams this error (I've selected the part that appears no to repeat):  

`28.267 22603 22639 E godot   : USER ERROR: Condition "!pipeline" is true.
06-30 21:01:28.267 22603 22639 E godot   :    at: draw_list_bind_render_pipeline (drivers/vulkan/rendering_device_vulkan.cpp:7350) - Condition "!pipeline" is true.
06-30 21:01:28.267 22603 22639 E godot   : USER ERROR: Condition "!uniform_set" is true.
06-30 21:01:28.267 22603 22639 E godot   :    at: draw_list_bind_uniform_set (drivers/vulkan/rendering_device_vulkan.cpp:7425) - Condition "!uniform_set" is true.
06-30 21:01:28.267 22603 22639 E godot   : USER ERROR: This render pipeline requires (0) bytes of push constant data, supplied: (64)
06-30 21:01:28.267 22603 22639 E godot   :    at: draw_list_set_push_constant (drivers/vulkan/rendering_device_vulkan.cpp:7533) - Condition "p_data_size != dl->validation.pipeline_push_constant_size" is true.
06-30 21:01:28.267 22603 22639 E godot   : USER ERROR: No render pipeline was set before attempting to draw.
06-30 21:01:28.267 22603 22639 E godot   :    at: draw_list_draw (drivers/vulkan/rendering_device_vulkan.cpp:7550) - Condition "!dl->validation.pipeline_active" is true.
`

### Steps to reproduce

Just animate something using tweens

### Minimal reproduction project

[AndroidTweenBug.zip](https://github.com/godotengine/godot/files/9022735/AndroidTweenBug.zip)

**Comment by Calinou** [comment]
This Vulkan rendering issue is unrelated to using tweens. It's because you changed a property using a tween, and changing that property is what causes the Vulkan error.

**Comment by somebody1121** [comment]
The error appear recently when i start experimenting with tweens so i thought that they were the cause...

**Comment by somebody1121** [comment]
I recompile the templates against the latest master and just works. I don't know what fixed it, but it's fixed.
