### ISSUE TITLE
Importing Folder of models, import loading bar breaks (DisplayServer regression)

### ISSUE THREAD

**Issue by RyqShaw** [godotengine/godot#62561]
### Godot version

4.0.alpha10

### System information

Windows 10

### Issue description

Visual for Loading bar goes to bottom right and jitters. The progress bar did not move, and there was a black box where the import bar should have been. The project works as intended after all the files have been imported.

https://user-images.githubusercontent.com/62477104/176742710-88421d69-07c6-4da2-91c7-e30ac4c9c843.mov

### Steps to reproduce

Open a new project, drag and drop a folder with glb assets to import.

### Minimal reproduction project

These were the files I imported. I dragged in the GLTF format folder, but the problem could exist for other formats.

[kenney_natureKit_2.1.zip](https://github.com/godotengine/godot/files/9022133/kenney_natureKit_2.1.zip)

**Comment by Calinou** [comment]
This is a general issue with all EditorProgress usage within the editor.

Can you reproduce it after enabling **Single Window Mode** in the Editor Settings then restarting the editor?

**Comment by RyqShaw** [comment]
After enabling single window mode and restarting, the loading bar does not go to the bottom right, but it does go unresponsive. Shortly after started responding again, and everything was normal. Here is another video if that helped

https://user-images.githubusercontent.com/62477104/176798680-8dde91fa-154e-4268-b663-e9a32a0cedc2.mp4

**Comment by akien-mga** [comment]
Seems fixed in 4.0 RC 3, at least for me on Linux the kenney asset pack imports properly (after configuring FBX2glTF as prompted by a dialog).
