### ISSUE TITLE
AnimationTree: travelling directly to a state inside a SubStateMachine doesn't work, even though the transition is valid.

### ISSUE THREAD

**Issue by eh-jogos** [godotengine/godot#62576]
### Godot version

4.0.alpha10

### System information

Manjaro Linux, Nvidia proprietary drivers, Vulkan Clustered

### Issue description

So this is the animation tree for my beat em up character
![image](https://user-images.githubusercontent.com/13070158/176789869-2cf02acb-4035-4094-84d5-64c24a297720.png)

I added the hurt and knockout states today, and it made a whole mess of it, since you can go from any ground state to any hurt state and from almost any state to knockout_launch.

I was trying to see if I could organize or do this in a better way, as I still have more attacks and grab/throws to add, when I noticed we can now add transitions directly to another state inside an AnimationNodeStateMachine! Wonderfull! In fact I had not done jump as an AnimationNodeStateMachine because I needed to be able to go to the "falling" state at any time, but now that I know I can create transitions directly to it, I was able to reorganize my AnimationTree like this:

![image](https://user-images.githubusercontent.com/13070158/176790203-2b45ab2c-29f4-49d3-af18-8623fe9debed.png)
Much better!

But when I tried to code the transitions, it doesn't work.
If, for example, I do:
```
_playback.travel("attack_group/attack1")
```
I get:
```
E 0:00:00:0569   _travel: Condition "!p_state_machine->states.has(p_travel)" is true. Returning: false
  <C++ Source>   scene/animation/animation_node_state_machine.cpp:179 @ _travel()
```
([link to github source I got from right clickig error](https://github.com/godotengine/godot/blob/4bbe7f0b98de72d6dd77d5ade4b761de375bcf66/scene/animation/animation_node_state_machine.cpp#L179))

Even though this:
```
var state_machine = _animation_tree.tree_root["nodes/state_machine/node"] as AnimationNodeStateMachine
var value = state_machine.has_transition("idle", "attack_group/attack1")
_playback.travel("attack_group/attack1")
print("value: %s"%[value])
```
prints `true`:
![image](https://user-images.githubusercontent.com/13070158/176790690-0b5fafa2-a370-4e42-ac8e-ec5e7cb1867b.png)

So when I ask AnimationNodeStateMachine if the transition is valid through GDScript, I get a `true`, but apparently the AnimationNodeStateMachinePlayback can't find it.

If needed I can provide prints from the "child" state machines or from the transitions in the inspector, I was just trying to not spam the description with even more images.

### Steps to reproduce

Use the MRP below, or:
1. Create a Scene with at least two animations
2. Create an AnimationTree with a AnimationNodeStateMachine as root
3. Add one animation directly and another inside a new AnimationNodeStateMachine
4. Connect the outside animation directly to the inside animation
5. Try to travel to it.

### Minimal reproduction project

[broken_animation_tree.zip](https://github.com/godotengine/godot/files/9023891/broken_animation_tree.zip)

The default scene has everything set up, just run it and use the arrow keys to try to play different animations
![image](https://user-images.githubusercontent.com/13070158/176791218-ede3d690-9659-4590-9519-3f4f09c77e18.png)

Only `ui_right` and `ui_down` will work, as they are transitions between the "idle" state and the "move_group" state, both which are on the same AnimationNodeStateMachine. 
![image](https://user-images.githubusercontent.com/13070158/176791591-632d936a-b352-46d7-b283-a0e4d997f1d2.png)

`ui_up` and `ui_left` which are transitions from "idle" directly to AnimationNodeAnimations inside the "move_group" AnimationNodeStateMachine, will not work, even though they'll print that the transition is valid (when you are coming from idle)
![image](https://user-images.githubusercontent.com/13070158/176791631-e3363a6d-d25e-4ade-a38a-a473b7eb1ef8.png)

**Comment by guilhermefelipecgs** [comment]
At the moment travel only works for states in the same state machine. I think I can change that. I'll take a look.

**Comment by eh-jogos** [comment]
@Calinou Shouldn't this be tagged as 4.0? As connections to states inside another AnimationNodeStateMachine are not available on 3.x (at least up to 3.4), and this is only a bug if I can make this connections in the editor but not travel to them in runtime.

**Comment by eh-jogos** [comment]
@TokageItLab just noticed this was moved to 4.x, wouldn't it be better to remove the UI that allows for connecting a state node directly to a child state node of another state machine? I mean, if I can't travel to it, why can I connect it?

Or is this a problem only when trying to use ` travel`  from code, but if you use conditions for auto-traveling it works?

**Comment by TokageItLab** [comment]
cc @SaracenOne @guilhermefelipecgs
