### ISSUE TITLE
`XRInterface.trigger_haptic_pulse()` throws error `Parameter "tracker" is null.`

### ISSUE THREAD

**Issue by addmix** [godotengine/godot#62570]
### Godot version

4.0 alpha 11

### System information

Windows 10

### Issue description

`XRInterface.trigger_haptic_pulse()` throws error `Parameter "tracker" is null.` any time it is called, no matter what argument is passed.

### Steps to reproduce

1. call `XRInterface.trigger_haptic_pulse()`
2. profit

### Minimal reproduction project

[minimum vr.zip](https://github.com/godotengine/godot/files/9023730/minimum.vr.zip)

**Comment by Calinou** [comment]
@addmix Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by addmix** [comment]
Updated to include a minimal reproduction project.

**Comment by addmix** [comment]
You can still use haptics, but it appears to use the wrong tracker names, the XRInterface still uses the default OpenXR tracker names, `"/user/hand/right"` and `"/user/hand/left"`. I would assume the XRInterface should use the tracker name that Godot assigns rather than the default?

![image](https://user-images.githubusercontent.com/38119387/177221861-05344d0a-d091-4870-b427-c353dc5d62bf.png)

**Comment by addmix** [comment]
Seems to be fixed as of beta 17.

**Comment by RadixSeven** [comment]
Thank you, @addmix The minimal reproduction project helped me understand how to use trigger_haptic_pulse.
