### ISSUE TITLE
[3.5 RC 5] GLES3 projects with Asynchronous shaders causing `_gl_debug_print` errors.

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#62590]
### Godot version

3.5 RC5

### System information

Linux, Nvidia 1650GTi, GLES3

### Issue description

Running a GLES3 project with Godot 3.5 RC5 appears to cause the following (non-fatal) error:
`E 0:00:00.347   _gl_debug_print: GL ERROR: Source: OpenGL	Type: Undefined behavior	ID: 131222	Severity: Medium	Message: Program undefined behavior warning: The current GL state uses a sampler (0) that has depth comparisons disabled, with a texture object (0) with a non-depth format, by a shader that samples it with a shadow sampler. Using this state to sample would result in undefined behavior.
  <C++ Source>  drivers/gles3/rasterizer_gles3.cpp:124 @ _gl_debug_print()`

GLES2 does not cause this error. Things appear to run as expected despite said error(s).

### Steps to reproduce

Run any GLES3 project.

**Comment by lawnjelly** [comment]
Would you be able to try testing it with asynchronous shaders turned off? `project_settings/rendering/gles3/shaders/shader_compilation_mode` set to synchronous. This is just in case it is something in the ubershader that is causing a problem.

**Comment by Sslaxx** [comment]
No issues with `shader_compilation_mode` set to `synchronous`.

**Comment by akien-mga** [comment]
The next build has `Synchronous` as default again, so the "regression" part is solved. The bug still exists when choosing `Asynchronous + Cache` so will need to be looked into.

**Comment by akien-mga** [comment]
Fixed by #62628.
