### ISSUE TITLE
Input.get_vector() does not respect Input.action_press()

### ISSUE THREAD

**Issue by WolfgangSenff** [godotengine/godot#62593]
### Godot version

3.5.rc5

### System information

Windows 11

### Issue description

Working on a tutorial using simulated input, I noticed that if you use Input.action_press() to simulate input, it will not be picked up, no matter what values you use, in Input.get_vector(). The reason appears to be that at some point or another, the raw_strength of the simulated action is set to 0, and that's what get_vector() uses. The action_strength has the correct value, but because it uses the raw_strength, get_vector() returns Vector2(). This might be intentional, but I'm not sure. I have attached a repro project - it's fairly big, didn't bother to create a new one, just the one I'll be using for my tutorial.

I suppose for some reason this might be on purpose, but it seems like in other parts of the codebase, the raw_strength is actually the same as the normal strength, so it's confusing to me why this would differ, especially if I set the strength directly in my Input.action_press() call (it is not set that way currently, but it's easy enough to manipulate).

In the repro project below, it *is* possible to work around this by manually building the vector, but I don't really see why I shouldn't be able to use Input.get_vector().

### Steps to reproduce

1. Download the repro project
2. Run the game
3. On the left, drag the button down by tapping on the screen and moving said button down
4. Observe the printed values

Quick edited note:
You can repro the desired behavior by using the arrows or WASD to generate the values I would expect from Input.get_vector().

### Minimal reproduction project

[UnidentifiedFlyingAwesome.zip](https://github.com/godotengine/godot/files/9028931/UnidentifiedFlyingAwesome.zip)

**Comment by Calinou** [comment]
cc @aaronfranke

**Comment by aaronfranke** [comment]
Do we want raw strength to contain simulated input? We'd need to do one of these three things:
* Make the raw strength value change based on the simulated input.
* Make Input.get_vector look at both raw and non-raw strength.
* Make Input.get_vector only look at non-raw strength. This is how https://github.com/godotengine/godot/pull/42976 worked until @groud suggested we use a circular deadzone with no axis deadzones, but users have complained about this behavior anyway https://github.com/godotengine/godot-docs/issues/5378

**Comment by WolfgangSenff** [comment]
I'm not sure if it's actually a useful suggestion, but what about a set_vector function that's publicly available? Could simulate it that way, and it could do it in such a way that get_vector just works.

**Comment by YeldhamDev** [comment]
I would like to add that this bug also makes inputs from `TouchScreenButton`s be ignored.

**Comment by akien-mga** [comment]
Fixed in 4.0 by #59911 and in 3.6 by #66480.
