### ISSUE TITLE
Browser extensions "stealing" input from html export

### ISSUE THREAD

**Issue by RPicster** [godotengine/godot#62606]
### Godot version

3.5RC4

### System information

Windows 10

### Issue description

When using browser extensions that use shortcuts, e.g. for navigation, those shortcuts "steal" the input of html5 exported Godot projects.

### Steps to reproduce

- Install an extension that uses keyboard shortcuts for input. (e.g. [Vimium C on Chrome](https://chrome.google.com/webstore/detail/vimium-c-all-by-keyboard/hfjbmagddngcpeloejdejnfgbamkjaeg))
- Browse to https://editor.godotengine.org/
- Create a new project
- As the name enter `Hello`
- Vimium will capture "H" (Shift + H) as the shortcut to go back in browser history.

### Minimal reproduction project

Not neccessary, see above.

**Comment by RPicster** [comment]
Adding to the "bug report" - Yes I am fully aware that this is in part a problem of using said extension(s).
But, I am working on a project where keyboard input + html5 is mandatory and it's not just Vimium. Vimium is a good example as it captures so many different key.

I asked in the Vimium github issues for solutions - it's the "desired" behaviour and in this case I was suggested to turn off Vimium. But on other extensions (e.g. [Key Jump](https://chrome.google.com/webstore/detail/key-jump-keyboard-navigat/afdjhbmagopjlalgcjfclkgobaafamck?hl=de)) it's not just easily deactivable.

I tested a local workaround that seemed to work:
replacing `<body>` with `<body contenteditable=true>` - This seemed to work and stopped extensions from capturing those inputs (as it is now treated like an input field).

The question now would be if this behaviour could be implemented as the default behaviour in the html5 export.

**Comment by Faless** [comment]
Fixed via #62607

**Comment by Faless** [comment]
> The question now would be if this behaviour could be implemented as the default behaviour in the html5 export.

Setting `contenteditable=true` is not an option, since that has it's own specific meaning, which we don't want, and can easily break on different browsers/platforms:
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contenteditable

If you need to customize the HTML to account for your specific setup, you can set a [custom HTML page on export](https://docs.godotengine.org/en/stable/tutorials/platform/customizing_html5_shell.html)

**Comment by RPicster** [comment]
The PRs that I mentioned do not fix this problem, they fix a general problem that leads to a wrong cursor under certain circumstances.

I know that I can setup a custom html, but my specific setup is not the problem here.

Like I said, even the original web editor of Godot suffers from this problem.

Is there another solution to this that you know of?

**Comment by Faless** [comment]
> The PRs that I mentioned do not fix this problem, they fix a general problem that leads to a wrong cursor under certain circumstances.

The PR allows you to fix it via a custom HTML page (without having the wrong cursor).

> Is there another solution to this that you know of?

You should ask the extensions developers, it's clearly them who steal the input by modifying the HTML content. Nothing we can do about that as far as I know.

And given they told you to disable the extension, I guess there is no solution beside not using an extension that breaks web pages.

**Comment by Faless** [comment]
Did you try opening an issue on their github? https://github.com/KennethSundqvist/key-jump-browser-extension

**Comment by Faless** [comment]
They seem to use capture on purpose, i.e. they **actively want** to steal events at the `window` level (as soon as they arrive):
https://github.com/KennethSundqvist/key-jump-browser-extension/blob/master/src/content.js#L44-L45

With this in mind (see [event flow](https://www.w3.org/TR/uievents/#event-flow)) I'm pretty confident there is nothing we can do about it.

They should just fix their extension.
