### ISSUE TITLE
editor bitmask UI doesn't properly account for mouse position

### ISSUE THREAD

**Issue by addmix** [godotengine/godot#62617]
### Godot version

4.0 alpha 11

### System information

Windows 10

### Issue description

https://user-images.githubusercontent.com/38119387/176973861-c6e02e33-fae8-4d5a-88c4-9e1c0c778a96.mov

Here is a video of the issue, I've narrowed it down that the bitmask UI only receives the updated mouse position when you click and drag on one of the layer buttons. clicking without movement will click on the last button that was clicked while moving the mouse. 

### Steps to reproduce

For current functionality you must click and drag to update the mouse position to a button, then click on the button a second time.

**Comment by Calinou** [comment]
This behavior is by design (so that clicking "between" two checkboxes still checks one box, which is less frustrating). However, it should keep updating the mouse position while moving the mouse while pressed.

**Comment by addmix** [comment]
The issue is that clicking on a box does not toggle the box, unless you click and drag, then click again.

Clicking on a box will not properly updated mouse position, will not toggle the selected box.

Presently, you must click and drag on the desired box to update the mouse position, then click a second time which then toggles the box.

The box highlight also only updates when you click + hold and drag over the boxes.

Here is a more descriptive video.

https://user-images.githubusercontent.com/38119387/176975620-1cde0e35-9160-4cf3-95d2-0d36f2d6800b.mov

**Comment by addmix** [comment]
I've also found this only happens with scenes opened in the editor, this does not happen to scenes that are already open when the editor launches.

**Comment by addmix** [comment]
I tested with the most recent version of alpha 11, can't reproduce, closing for now.
