### ISSUE TITLE
3D KinematicBody doesn't use collision exceptions.

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#6261]
**Operating system or device - Godot version:**
Windows 10 64bit - Godot 2.1 stable

**Issue description** (what happened, and what was expected):
Using `A.add_collision_exception_with(B)` where A or B is a KinematicBody wont work. The bodies will still collide. It doesn't matter what the other PhysicsBody is, as long as one of them is a KinematicBody.

**Comment by Silvea12** [comment]
This bug still exists in 2.1.2, using Arch Linux, x86_64. Please get on this.

**Comment by CowThing** [comment]
This is no longer an issue in Godot 3.0 stable.

**Comment by Silvea12** [comment]
I'd say go for it and close it if it's no longer relevant.
