### ISSUE TITLE
ShaderIssue in HTML5 when using shaders entailed in Zylann's Heightmap Terrain

### ISSUE THREAD

**Issue by nan0m** [godotengine/godot#62621]
### Godot version

v3.4.4.stable.official.419e713a2

### System information

Windows 10, GLES3, GTX 765M, Chrome & Firefox Browser

### Issue description

When playing scenes as html5 there are shader issues if using the Classic4 shader and the Multisplat16 shader which are part of zylanns heightmap plugin. Instead of displaying the underlying materials everything is black.
I expected the engine to display these materials correctly.

In Editor:
![Screenshot_2](https://user-images.githubusercontent.com/74869542/176980116-3dd5de5f-a0ad-48b8-be71-36e4bdf0f2be.png)
 When running HTML5 scene in Chrome or Firefox: (Added console log with errors)
![Screenshot_1](https://user-images.githubusercontent.com/74869542/176980134-7a325f70-e43d-403b-b960-820c3948a8b2.png)
:

### Steps to reproduce

1. Open the project,
2. In HTerrain Node in Inspector go to Rendering and Shader Type and select either
3. `Multisplat16`, `Classic4`, or `Multisplat16Lite`
Run the scene as HTML5

### Minimal reproduction project

[ShaderIssue.zip](https://github.com/godotengine/godot/files/9032105/ShaderIssue.zip)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/45532.

**Comment by fabian-bubla** [comment]
Thank you.  That was very helpful! For anyone else with the same issue:
On my textures I needed to set Compression from VRAM to Lossless as @Calinou said.
I also had to disable Mipmaps on them. This will allow you to use the Classic4Lite shader in web export.

The addon can also generate packed texture arrays, you need to use the same import settings on the generated packed texture arrays to be able to use Multisplat16Lite, and Multisplat16 textures.

The Classic4 shader I sadly could not get to work with this.

**Comment by Calinou** [comment]
It sounds like this is a documentation issue that should be addressed in the plugin's documentation, so I'd recommend opening an issue on https://github.com/Zylann/godot_heightmap_plugin.
