### ISSUE TITLE
Cursor disappears when dragging to adjust values in Preview Environment panel

### ISSUE THREAD

**Issue by WickedInsignia** [godotengine/godot#62620]
### Godot version

4.0 Alpha 10

### System information

Windows 10, GTX1080, i7 6700

### Issue description

The mouse cursor will disappear when dragging to adjust any value in the Preview Environment panel.
The value will stop changing if the drag motion is halted, and cannot be changed again by further dragging after the cursor has disappeared.
If the user clicks once while the cursor is gone, the panel will close and the cursor will appear in the outliner panel.

### Steps to reproduce

- Open a new project
- Attempt to change any value in Preview Sun/Environment by dragging in its text box (such as sun energy).

**Comment by Calinou** [comment]
This should have been fixed by https://github.com/godotengine/godot/issues/57383.

Can you reproduce this after enabling **Single Window Mode** in the Editor Settings?

**Comment by WickedInsignia** [comment]
The issue does seem to be resolved while using Single Window Mode.
