### ISSUE TITLE
Linux window freeze when unfocusing while loading window open

### ISSUE THREAD

**Issue by 3top1a** [godotengine/godot#62635]
### Godot version

Godot 4.0 alpha 11 from godotengine.org

### System information

Arch linux, i3 WM, Vulkan @ NVIDIA GeForce GTX 1050 Ti, driver 515.48.07

### Issue description

When there's a operation that opens a loading window (e.g. saving, importing) and refocusing the editor window, it completely freezes.
This seems to only happen when the editor is not visible (e.g. another virtual desktop/workspace).

Logs (some of it may be my unported project):
```
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  42 (X_SetInputFocus)
  Serial number of failed request:  8026
  Current serial number in output stream:  8026
ERROR: BUG: Unreferenced static string to 0: physics_process_internal
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: _update_script_names
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: GizmoLightmapGI
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: EditorRect2D
   at: unref (core/string/string_name.cpp:129)
WARNING: Property not found:
     at: _get (core/config/project_settings.cpp:319)
ERROR: Method argument to Callable constructor must be a non-empty string
   at: Callable (core/variant/callable.cpp:276)
ERROR: BUG: Unreferenced static string to 0: PrevScene
   at: unref (core/string/string_name.cpp:129)
ERROR: Method argument to Callable constructor must be a non-empty string
   at: Callable (core/variant/callable.cpp:276)
```

### Steps to reproduce

- Open any project (can be empty)
- Save or import
- Switch to a different workspace/virtual desktop (might also work when minimizing)
- Wait
- Godot's window freezes, no new frame is drawn
- Godot now needs to be closed with htop through SIG_TERM, ^C does nothing, nor does WM_CLOSE

Video (3.3MiB):
https://user-images.githubusercontent.com/57371001/177003823-a9649355-0fd6-4ce3-870a-dff4f778f9e5.mp4

### Minimal reproduction project

An empty project will do

**Comment by Rindbee** [comment]
Using i3wm, this is often encountered when opening the editor and then switching workspaces.

**Comment by Calinou** [comment]
Can you reproduce this after enabling **Single Window Mode** in the Editor Settings?

**Comment by 3top1a** [comment]
No.

**Comment by 3top1a** [comment]
Just a little find, removing line [3646](https://github.com/godotengine/godot/blob/master/platform/linuxbsd/display_server_x11.cpp#L3646) in [display_server_x11.cpp](https://github.com/godotengine/godot/blob/master/platform/linuxbsd/display_server_x11.cpp) seems to be a valid workaround.
