### ISSUE TITLE
Checkbox style "Hover Pressed" not working if set in theme and not as theme override

### ISSUE THREAD

**Issue by Piralein** [godotengine/godot#62642]
### Godot version

3.4.4.stable and 3.5.rc5

### System information

Windows 10, GLES 3

### Issue description

Using the theme to apply styles to the "CheckBox" control node doesn't work for the "Hover Pressed" style.
Using the style override of the node with the same styleboxes works.
![image](https://user-images.githubusercontent.com/48352564/177010790-26e8685b-2948-4a5d-a629-9fdf75a6ded0.gif)

### Steps to reproduce

- Create a theme and add normal, hover, pressed and hover_pressed styles to the checkbox.
- Add a checkbox node and aplly the theme.
- Add the same styles to a second checkbox node without theme, but theme overrides.

### Minimal reproduction project

[TestProject.zip](https://github.com/godotengine/godot/files/9033380/TestProject.zip)

**Comment by Piralein** [comment]
I guess its the `if (has_stylebox("hover_pressed") && has_stylebox_override("hover_pressed")) {` in button.cpp line 107?

**Comment by akien-mga** [comment]
Fixed by #62644.
