### ISSUE TITLE
RichTextLabel's BBCode is reset to the initial value when the window is resized if a DynamicFont is used

### ISSUE THREAD

**Issue by mishkarch** [godotengine/godot#62640]
### Godot version

3.5 RC 5

### System information

Windows (I think it's not matter)

### Issue description

A RichTextLabel using a DynamicFont and bbcode_enabled = true if at start in scene inspector bbcode_text was not empty will reset to the initial value its text on resizing the window. This happens when the text is set with append_bbcode or add_text.

Looks like an old problem #22203

### Steps to reproduce

Create a RichTextLabel and give it a DynamicFont. Enable BBCode, enter some text in bbcode_text inspector property. And call append_bbcode. Text will be reset on resizing the window.

### Minimal reproduction project

[https://github.com/mishkarch/RichTextLabelBug](https://github.com/mishkarch/RichTextLabelBug)
Press space to add some text to initial text then resize the window.

**Comment by Calinou** [comment]
As a workaround, disabling font oversampling in the Project Settings should prevent the font from being re-rendered when the window size changes (at the cost of looking pixelated or blurry at higher-than-default resolutions).

**Comment by instr3** [comment]
I would like to report a similar issue even when ``bbcode_enabled = false``.

That is to say, if ``bbcode_enabled = false`` but you have non-empty ``bbcode_text``, resizing the window will also cause this issue despite the fact that bb code is not enabled at all.

**Comment by OsakiTsukiko** [comment]
Yea, this issue has been around for a while now. #24173 describes this issue, but it's flagged as solved in #31028, yet the issue still persists.

Similar issues (#22203, #24173, #27027)

**Comment by akien-mga** [comment]
Fixed by #70593.
