### ISSUE TITLE
Include option to disable !=, ==, === icons in text editor

### ISSUE THREAD

**Issue by tinmanjuggernaut** [godotengine/godot#62654]
### Godot version

Godot 4 e093cfdf0

### System information

Win 10/64 NVIDIA GeForce GTX 1060/PCIe/SSE2

### Issue description

This may seem like an ungrateful nitpick, but it would be appreciated if the option to disable the conversion of 
`!=` into this icon 
![image](https://user-images.githubusercontent.com/632766/177022388-39da010f-e469-4640-b201-9091aa2518fd.png)
would be great. I can't find any option to disable it in the editor settings.

This goes for any other text replacing icons. 
I've also found `==` turns into 
![image](https://user-images.githubusercontent.com/632766/177022461-608c2902-8805-45df-a4d0-ed793d80496c.png)
and `===` turns into 
![image](https://user-images.githubusercontent.com/632766/177022473-01556278-2f46-4162-91fa-f731788420fc.png)
, though I don't even know if that's an operator.

While it may be nice for some users, I think it's less readable, and I can't type ![image](https://user-images.githubusercontent.com/632766/177022388-39da010f-e469-4640-b201-9091aa2518fd.png)
 so don't want to see it in my code. 

### Steps to reproduce

Type `!=` in the editor.

**Comment by Rindbee** [comment]
You can avoid this by overriding `interface/editor/code_font` with another font.

**Comment by Calinou** [comment]
This is already available as the contextual ligatures editor setting.

**Comment by tinmanjuggernaut** [comment]
I see the setting, thank you. TIL what `contextual ligatures` means. Note there is no editor description for the option.

**Comment by Calinou** [comment]
> Note there is no editor description for the option.

This is pending for https://github.com/godotengine/godot/pull/48548 to be merged. It's stuck on a CI issue though.

**Comment by Poonaka** [comment]
We should reconsider having this on by default, it's pretty confusing/annoying. I use Visual Studio, VS code and Jetbrains Rider and have never seen ligatures used before.

**Comment by Calinou** [comment]
> We should reconsider having this on by default, it's pretty confusing/annoying. I use Visual Studio, VS code and Jetbrains Rider and have never seen ligatures used before.

See https://github.com/godotengine/godot/issues/63865.
