### ISSUE TITLE
Wrong resolution of html5 on android devices.

### ISSUE THREAD

**Issue by ninetones** [godotengine/godot#62655]
### Godot version

3.3~

### System information

Android 11

### Issue description

Wrong display resolution on android devices when a project is exported to html5.
These are screenshots captured on my android mobile.
(I don't have iOS device)

- exported with godot 3.2.3
<image src="https://user-images.githubusercontent.com/25213070/177022232-d91fef8d-483d-40de-82ae-5598f3233591.png" width="400px">

- exported with godot 3.3 and later
<image src="https://user-images.githubusercontent.com/25213070/177022234-2084409c-023c-45ff-89e0-0b7a50d27b4c.png" width="400px">

OS.window_size.x seems like dp width of the display.
Canvas resolutions are different too.

Open these exported html links by mobile .
https://ninetones.github.io/godot_test_mobile_resolution/export3.2.3/
https://ninetones.github.io/godot_test_mobile_resolution/export3.3/
https://ninetones.github.io/godot_test_mobile_resolution/export3.4.4/

### Steps to reproduce

Export a godot project to html5 and upload it to a web server and open on android mobile.

### Minimal reproduction project

https://github.com/ninetones/ninetones.github.io/tree/main/godot_test_mobile_resolution

**Comment by akien-mga** [comment]
This is an intentional change, 3.3+ defaults to enabling HiDPI support on Web too, and not just on other platforms. You can change it in the project settings if you don't want it to handle HiDPI.

**Comment by Calinou** [comment]
Closing per the above comment.
