### ISSUE TITLE
Build process stops with error (Win7, Godot 2.2)

### ISSUE THREAD

**Issue by stayseek** [godotengine/godot#6265]
**Operating system or device - Godot version:**
Win7SP1 64-bit, Godot master branch (cloned 21-23 of august)

**Issue description**:
Build process stops there:

cl /Focore\io\stream_peer.windows.tools.64.obj /c core\io\stream_peer.cpp /TP /T
P /nologo /Z7 /DDEBUG_ENABLED /DDEBUG_MEMORY_ENABLED /DD3D_DEBUG_INFO /Od /MT /G
d /GR /nologo "/IC:\Program Files (x86)\Windows Kits\10\/Include" /DWINDOWS_ENAB
LED /DRTAUDIO_ENABLED /DWIN32 /DTYPED_METHOD_BIND /DGLES2_ENABLED "/IC:\Program
Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "/IC:\Program Files (x86)\M
icrosoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "/IC:\Program Files (x86)\Windows
 Kits\10\include\10.0.10586.0\ucrt" "/IC:\Program Files (x86)\Windows Kits\NETFX
SDK\4.6.1\include\um" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.105
86.0\shared" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\um"
"/IC:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\winrt" /I "/IC:/P
rogram Files/Microsoft DirectX SDK (March 2009)/Include" /D_WIN64 -DFREETYPE_ENA
BLED -DDEBUG_MEMORY_ALLOC -DSCI_NAMESPACE -DENABLE_DEPRECATED /DMSVC /GR -DMUSEP
ACK_ENABLED -DSQUISH_ENABLED -DVORBIS_ENABLED -DOPUS_ENABLED -DTHEORA_ENABLED -D
THEORALIB_ENABLED -DPNG_ENABLED -DDDS_ENABLED -DPVR_ENABLED -DJPG_ENABLED -DWEBP
_ENABLED -DSPEEX_ENABLED -DTOOLS_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -D
XML_ENABLED -DETC1_ENABLED -DGLEW_ENABLED -DGLEW_STATIC /Icore /Icore\math /Itoo
ls /Idrivers /I. /Iplatform\windows /Iplatform\windows\include /Idrivers\freetyp
e /Idrivers\freetype\freetype\include /Idrivers\builtin_zlib\zlib /Icore\io /Idr
ivers\freetype\include /Imodules\enet
stream_peer.cpp
c:\deps\godot\core\io\stream_peer.cpp(495) : warning C4715: 'StreamPeerBuffer::g
et_partial_data': not all control paths return a value
c:\deps\godot\core\io\stream_peer.cpp(547) : error C4716: 'StreamPeerBuffer::dup
licate': must return a value
scons: *** [core\io\stream_peer.windows.tools.64.obj] Error 2
scons: building terminated because of errors.

**Steps to reproduce:**
Visual Studio Community 2015, Phyton 2.7.11, Scons 2.5.0
scons platform=windows

**Comment by volzhs** [comment]
There is PR #6239 for this.

**Comment by stayseek** [comment]
Fixed with #6239
