### ISSUE TITLE
Editor layout reset discrepancy

### ISSUE THREAD

**Issue by RandomShaper** [godotengine/godot#6266]
**Operating system or device - Godot version:**
2.2, Win 10 x64

**Issue description** (what happened, and what was expected):
Picking _Settings -> Editor Layout -> Default_ doesn't provide the actual default layout when a blank project is created.

**Steps to reproduce:**
1. Create a new project.
2. Pick _Settings -> Editor Layout -> Default_.
3. Note how the layout has changed although it should stay the same.

**Comment by volzhs** [comment]
Are you using it in English?

**Comment by RandomShaper** [comment]
Yes.

**Comment by akien-mga** [comment]
Confirmed, also mentioned in #5242.
