### ISSUE TITLE
SDFGI: World axes visible in reflections and cascades

### ISSUE THREAD

**Issue by WickedInsignia** [godotengine/godot#62670]
### Godot version

4.0 Alpha 11

### System information

Windows 10, GTX1080, i7 6700

### Issue description

World axes show in SDFGI reflections and in cascade view when enabled.
Disabling requires reopening the scene to take effect.
![SDFGI_WorldAxisReflectionBug](https://user-images.githubusercontent.com/70243134/177041633-4fa7b593-7cc2-4fd2-b9d8-2e9146a9fa78.JPG)
![SDFGI_WorldAxisReflectionBug02](https://user-images.githubusercontent.com/70243134/177041637-1b5f7e61-bff6-445e-9d4e-29a15e815263.JPG)

### Steps to reproduce

- Open new project
- Add CSG sphere
- Give it a fully reflective metallic material
- Activate SDFGI
- World axes will be visible in reflections of the sphere and in cascade view.

### Minimal reproduction project

[Uploading SDFGI_AxisInReflectionsBug.zip…]()

**Comment by mrjustaguy** [comment]
https://github.com/godotengine/godot/pull/62649 fixes this probably, test with the artifact from that PR.

**Comment by akien-mga** [comment]
Fixed by #62649.
