### ISSUE TITLE
A MeshInstance2D node

### ISSUE THREAD

**Issue by WalasPrime** [godotengine/godot#6267]
Basically there is no way to use OpenGL primitives in 2D, while in 3D you can use the SurfaceTool and a MeshInstance. Polygon2D is limited (still it is useful), and it also assumes edges do not intersect with eachother (also you can't render with PRIMITIVE_LINE_STRIP for example).

2D Meshes might make use of the Z coordinate, so basically only a MeshInstance2D would be needed (SurfaceTool, MeshDataTool could stay the same).

Thoughts?

**Comment by bojidar-bg** [comment]
Sounds like a duplicate of #2914, but I'm not sure. In any case, we can easily have a commit that fixes both.

@WalasPrime Do you think we should/can close this in favour of the other, or do you consider it better if they remain separate?

**Comment by WalasPrime** [comment]
Oh yeah, sure
