### ISSUE TITLE
GDScript should allow linebreaks inside function calls

### ISSUE THREAD

**Issue by eevee** [godotengine/godot#6268]
This produces a syntax error, at least in the editor ("Error parsing expression, misplaced: '\\n'"):

```
return Vector2(
    x, y)
```

This works fine:

```
return (Vector2(
    x, y))
```

It looks like newlines are ignores within free parentheses, but not within the parentheses used for a function call.  Python allows either.

**Comment by Zylann** [comment]
You should usually be able to write this instead:
```gdscript
return Vector2( \
    x, y)
```

**Comment by eevee** [comment]
Yeah, but backslashes are _super_ ugly, make it more awkward to edit that statement later, and set off warning lights in the Python part of my brain.  :)
