### ISSUE TITLE
Godot 4 doesn't open on Debian, Vulkan driver crash

### ISSUE THREAD

**Issue by Sosasees** [godotengine/godot#62685]
### Godot version

4.0 alpha 11

### System information

Debian Linux x64 v10, AMD RX 550, Openbox WM

### Issue description

when i try to run the _Godot 4.0 alpha 11 64-Bit_ executable, i get this wall of error messages:
![image](https://user-images.githubusercontent.com/66305550/177051570-0d91aa13-8d99-48dc-b004-4f5606e4d77f.png)

in this issue, i want to focus on just line 12:
``Project is missing: /home/poppy/gd_proj/gd4alpha2/test/project.godot``

it's looking for a project that doesn't exist:
1. i had renamed the ``gd_proj`` folder to just ``gd``
2. there's no ``gd4alpha2`` folder in the ``gd`` folder

### Steps to reproduce

1. download & unpack Godot 4.0 alpha 11 from the [official blog post](https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-11).
   i tried ``Godot_v4.0-alpha11_linux.64.zip``
3. run it in terminal emulator
4. notice the error messages

### Minimal reproduction project

no Godot project necessary

**Comment by akien-mga** [comment]
The "project is missing" warning is not related, it's just the last thing Godot could print before crashing for another reason.

The reason is that your Vulkan drivers are broken, most likely because you're running an old version of Debian with old Mesa and LLVM. The solution would be to update Debian to a newer release with more recent drivers.

**Comment by Sosasees** [comment]
thanks. i didn't know that Debian 11 released already,
and that the upgrade process is different from your everyday ``sudo apt update&&sudo apt upgrade -y``,
and that the early-version Vulkan drivers in Debian 10 caused Godot 4 to not start.

i updated to Debian 11 and Godot 4 starts like it should.
