### ISSUE TITLE
[GDScript 2.0] Constant array/dictionary inconsistency 

### ISSUE THREAD

**Issue by AThousandShips** [godotengine/godot#62680]
### Godot version

90c33ed

### System information

Windows 10

### Issue description

Accessing constant arrays and dictionaries with index/key from a variable does not trigger an error:
```gdscript
const dict : Dictionary = { "A":[0] }
const ind_c = "A"
dict["A"][0] = 1 # Causes error
dict[ind_c][0] = 1 # Causes error
var ind_v = "A"
dict[ind][0] = 1 # Does not
```
It appears to be caused by a failure to set the type of such a subscript to constant, where as the case with a literal is folded into a constant expression (which isn't possible for a variable as the index/key is not known at compile time)

### Steps to reproduce

See above

**Comment by AThousandShips** [comment]
From what I can tell and some minor testing it would be here:
https://github.com/godotengine/godot/blob/90c33edf3b291a12db3fc8ddb4925807ad0cf5de/modules/gdscript/gdscript_analyzer.cpp#L3275

With the first clause making a constant base with constant index/key a constant expression (thus folding it to the actual value) but the subsequent clause ignores any constness of the base type

**Comment by AThousandShips** [comment]
I believe adding a simple fix solves this but I don't know if I'm well versed enough in the inner workings of GDScript to handle such a PR

**Comment by cdemirer** [comment]
I think it wouldn't be easy to do this currently, but since read-only Array/Dictionary was introduced recently (#61127) it'll probably be possible in GDScript soon.
