### ISSUE TITLE
PathFollow2D erratically moves object along path / does not move object on path correctly when object has positional offset to PathFollow2D

### ISSUE THREAD

**Issue by Dante3085** [godotengine/godot#62686]
### Godot version

3.4.4.stable

### System information

Windows 11

### Issue description

I tried to move a Camera2D along the following path, by tweening "unit_offset" from 0.0 to 1.0 in 5 seconds.
<img src="https://user-images.githubusercontent.com/26558776/177051498-9b66f4aa-6572-4cb4-9f55-920b6a238191.png" width=50% height=50% />

The result didn't seem quite right. Not the path I defined above from my perspective.
<img src="https://user-images.githubusercontent.com/26558776/177051571-fe610474-d7b2-4a3e-891c-388063945813.gif" width=50% height=50% />

The problem was that the Camera2D had a positional offset relative to it's parent node, like in the following image:
<img src="https://user-images.githubusercontent.com/26558776/177051842-01508828-8700-4df5-b933-0495c184f804.png" width=50% height=50% />

Set that offset to (0, 0) and it works:
<img src="https://user-images.githubusercontent.com/26558776/177051909-ae01b85c-1616-4505-b2c9-ab884ffb45b2.gif" width=50% height=50% />

Maybe this is intended behaviour, but it looks weird to me, so I thought I'd post it here.
I understand that this is probably not specific to Camera2D, but that is where the issue appeared for me.

### Steps to reproduce

1. Have a Camera2D in a scene setup like in the following image:
<img width="193" alt="image" src="https://user-images.githubusercontent.com/26558776/177051751-cd6fc9a8-8147-41be-a93b-56bfd37c2b62.png">

2. Define a Curve2D on the Path2D.
3. Make the Camera2D have a positonal offset relative to the PathFollow2D parent node (Like above, in the issue description).
4. Tween the unit_offset from 0.0 to 1.0 in 5 seconds.

### Minimal reproduction project

[path_following_bug_mrp.zip](https://github.com/godotengine/godot/files/9035305/path_following_bug_mrp.zip)

**Comment by kleonc** [comment]
It looks to behave correctly, you have enabled the path follower rotating according to the path:
![pRU436Gucf](https://user-images.githubusercontent.com/9283098/177053626-b8aa6525-8101-40e4-a654-96c31247820b.png)

And thus camera's local position (yellow line in the GIF below) is preserved according to its rotated parent (`PathFollow2D`):
[path_following_bug_mrp_debug.zip](https://github.com/godotengine/godot/files/9035408/path_following_bug_mrp_debug.zip)

![pp1qTTfoql](https://user-images.githubusercontent.com/9283098/177055005-8a1aecea-ced2-4aac-ae1e-724fce4f8956.gif)

**Comment by Dante3085** [comment]
Ok, I'll close the issue then.
