### ISSUE TITLE
TextureRegion does not update when the values are changed.

### ISSUE THREAD

**Issue by Kiaazad** [godotengine/godot#62694]
### Godot version

v3.4.4.stable.official [419e713a2]

### System information

Windows 10, GLES3, Nvidia 2070s

### Issue description

When adjusting my patch margins the lines in TextureRegion don't update, I have to click another node and click back to see the changes.
![image](https://user-images.githubusercontent.com/33455007/177078633-82363839-9422-4198-b9f1-c2fea6f12cf9.png)

### Steps to reproduce

Create a 9 patch node and change the patch margins fields in the inspector.

**Comment by KoBeWi** [comment]
This is only relevant to 3.x branch, as region editor was reworked in 4.0.

**Comment by akien-mga** [comment]
Fixed by #62766.
