### ISSUE TITLE
Node2D Z-Index ignored when Y-Sort enabled

### ISSUE THREAD

**Issue by xentripetal** [godotengine/godot#62715]
### Godot version

4.0.alpha11

### System information

Windows 10, Vulkan Clustered, 3080 TI 512.15

### Issue description

Z Index does not affect rendering order for tilemap layers when layers have y sort enabled. I might be wrong, but I assumed each Z-layer would only Y-Sort on its own layer.

### Steps to reproduce

See minimal reproduction project.
1. Open the tile_map.tscn scene
2. See the purple bars visible over the green background

The purple bars are on a negative z-index and should not be visible.

### Minimal reproduction project

[zindex.zip](https://github.com/godotengine/godot/files/9041587/zindex.zip)

**Comment by Calinou** [comment]
cc @groud

**Comment by xentripetal** [comment]
Couldn't get the engine to build locally to verify but it seems like this 

https://github.com/godotengine/godot/blob/master/scene/2d/tile_map.cpp#L1133

should be
```c
int z_index = tile_data->get_z_index() + get_layer_z_index(q.layer);
```

**Comment by xentripetal** [comment]
After some further testing the issue is unrelated to tilemaps. The same issue is present for any Node2Ds. If you have nested elements with y-sort and z-relative enabled, the render ordering does not account for relative z-levels.

<img width="798" alt="Screen Shot 2022-07-07 at 7 22 16 AM" src="https://user-images.githubusercontent.com/8892276/177772136-ff8d5824-7fd1-4cd0-951d-3d1d403a389d.png">
In this screenshot, the expected behavior is that the bottom row is entirely above the top row. Instead, z-level seems to only be affected for the parent elements and the z-rel childs are all treated as being on z-level=0. 

[zindex 2.zip](https://github.com/godotengine/godot/files/9063429/zindex.2.zip)

**Comment by xentripetal** [comment]
I have a working fix [here](https://github.com/godotengine/godot/compare/master...xentripetal:godot:master).

However I haven't worked in C++ since college so I think it would be better if someone more knowledgeable than me reviewed or implemented it themselves before I push a PR for it.

**Comment by groud** [comment]
> I have a working fix [here](https://github.com/godotengine/godot/compare/master...xentripetal:godot:master).

I think the `tile_map.cpp` part makes sense in your changes. I can't tell for the remaining part though (reduz should have a look), but if it solves your issue I think it might be good.

Could you open a PR?
