### ISSUE TITLE
Ask user to create a path if it doesn't exist

### ISSUE THREAD

**Issue by MasonAsh** [godotengine/godot#6271]
Whenever a user is prompted to pick a path, if they type a path that doesn't exist, godot should offer to create the path for the user.

Currently, if the path doesn't exist godot simply says "the path must exist" and doesn't allow you to proceed.

![godot-issue](https://cloud.githubusercontent.com/assets/1817000/17942033/b7335c72-6a03-11e6-9c8e-225acd76ab7e.png)

The above example comes from the project manager, however, this issue appears in the import plugins as well. 

IMO there should be a popup asking the user to confirm if they would like to create the directory.

**Comment by Calinou** [comment]
This is no longer an issue as of Godot 3.0, as the project creation dialog was improved.

![Project manager creation dialog](https://user-images.githubusercontent.com/180032/38609188-bb301154-3d7d-11e8-9dfc-ed52f7cdd892.png)
