### ISSUE TITLE
Quaternion get_axis() proving unreliable...?

### ISSUE THREAD

**Issue by novaplusplus** [godotengine/godot#62711]
### Godot version

4.0.dev

### System information

Should not matter?

### Issue description

I have been waffling on whether this is something I'm doing wrong, or an actual problem, but I am tentatively leaving it here. I have been digging deeply into the docs and source code but have yet to find anything that tells me of something I can do. I suppose the worst that will happen is it gets closed and someone tells me some magic I didn't think of...

I am doing some manipulation of rigidbodies by way of altering the angular velocity, similar to what's being done here: https://docs.godotengine.org/en/latest/tutorials/physics/rigid_body.html#the-look-at-method

In my case, the code looks like this:

```
var cur_rot := global_transform.basis.get_rotation_quaternion()
var tgt_rot := new_basis.get_rotation_quaternion()

var rot_delta := tgt_rot * cur_rot.inverse()

var rot_angle := rot_delta.get_angle()
var rot_axis := rot_delta.get_axis()

state.angular_velocity = rot_axis * (rot_angle / state.step)
```

I have seen this same approach done elsewhere nearly verbatim, but it seems to be unreliable here. I found, though, that the get_axis() is not returning a proper normalized vector unless the two rotations differ sufficiently. You have to adjust the rotation beyond quite a noticeable threshold, leading to a significant amount of "aliasing":

https://user-images.githubusercontent.com/3247833/177184496-5a8b3834-07a6-496c-94a7-9d9868c248d5.mp4

(mind the programmer art...)

I've tried it with multiple physics ticks and solver iterations, by the way, but it's pretty much the same behaviour on all of them (within reason, of course). So it's not really the delta per-tick but rather the absolute difference between the rotations.

I can normalize the axis variable, which does improve it, but it still leads to problems and occasional errors as things get fed a non-normalized vector. I looked into the source for the engine and noticed this:

```
Vector3 Quaternion::get_axis() const {
	if (Math::abs(w) > 1 - CMP_EPSILON) {
		return Vector3(x, y, z);
	}
	real_t r = ((real_t)1) / Math::sqrt(1 - w * w);
	return Vector3(x * r, y * r, z * r);
}
```

CMP_EPSILON is set to 0.00001, so compare this to the sorts of values I am getting from the quaternion's w value when near the center (the "dead zone"):

```
0.99999612569809
0.99999618530273
```

So.. something just seems funny here. Is this arising from a 32/64 bit floating point issue somewhere? It feels like something is not working as it should.

I admit - I barely understand quaternions. I can kind of conceptualize them being constructed and deconstructed from and to an axis vector and angle value, but beyond that they are a black box to me.

So I have no idea. Maybe I'm missing something horrifically obvious and wasting everyone's time. If that's the case, then sorry. I am losing my mind just a little bit.

update:
I tried a 64-bit build to see if it made any difference but it didn't. Oh well.

### Steps to reproduce

Described above

**Comment by novaplusplus** [comment]
Incidentally while looking through this, I noticed get_angle() returns a `float`, shouldn't it instead return `real_t` ?

```
float Quaternion::get_angle() const {
	return 2 * Math::acos(w);
}
```

**Comment by logzero** [comment]
Floats have about seven digits precision.
 
Quaternion xyz is the rotation axis premultiplied with the sine of the rotation half-angle and w is the cosine of the half-angle. It is a more elegant way to handle rotations than using axis angle or euler angles.

**Comment by novaplusplus** [comment]
just going to assume I was doing something wrong I think
