### ISSUE TITLE
nativelib plugin not loading

### ISSUE THREAD

**Issue by hani09876** [godotengine/godot#62730]
### Godot version

3.5 Rc 5 

### System information

dont have any idea

### Issue description

![image](https://user-images.githubusercontent.com/92350126/177295054-cc079bba-089e-492b-b6aa-462eab4af1d9.png)
the nativelib addon isnt working

### Steps to reproduce

i dont know

**Comment by akien-mga** [comment]
You should report this to the nativelib addon developer, not Godot developers.

**Comment by hani09876** [comment]
> You should report this to the nativelib addon developer, not Godot developers.

the problem is only on this version of godot. then why should i report the plugin author?
![image](https://user-images.githubusercontent.com/92350126/177298813-dadeb107-d152-49f9-9f7f-42893827fffc.png)

**Comment by hani09876** [comment]
> There's no guarantee that a plugin, which I don't even know, would work on any Godot version. Maybe this one requires specific Godot versions. It refers to some repository which is likely one that the plugin author needs to create for specific Godot versions, and they likely haven't done so for 3.5 yet.
> 
> But that's just speculation, and most importantly: it's the plugin author's job to find out why their plugin doesn't work and if that's a plugin issue or a Godot issue, not ours.

yeah you are right. but i saw on some release that they do some changes to run this plugin. 
![image](https://user-images.githubusercontent.com/92350126/177303616-7cb05743-3c3f-4696-8416-f316c099cdfd.png)
here is an example

**Comment by akien-mga** [comment]
That's about load native libraries on Android. This has nothing to do with this "nativelib" plugin, which, again, we don't know of. There are thousands of plugins for Godot, we don't know or test all of them.

**Comment by Calinou** [comment]
NativeLib is https://drmoriarty.github.io/nativelib/, but it's a third-party resource.
