### ISSUE TITLE
The profiler doesn't works when vsync is disabled

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#6273]
Tested on Godot 2.1, Windows 10 64 bits

When vsync is disabled, running the profiler results in weird behaviour.
The graph shows vertical lines, and most of the timing info is missing in the left panel. Sometimes it appears for one frame or two, but quickly disappear.
Clicking in the graph often makes the game to freeze and suspend the profiling session.

When vsync is enabled, the profiler works fine, however if I click in the graph, the line where I clicked seems to move and shift at a different rate than the graph.

Related thread on Q/A: https://godotengine.org/qa/7242/how-to-use-the-profiler?show=7242#q7242

**Comment by Calinou** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Zylann** [comment]
In 3.0.2 this issue doesn't really happen, but the profiler still behaves in an impractical way: https://github.com/godotengine/godot/issues/17155

**Comment by akien-mga** [comment]
Closing this one as fixed then.
