### ISSUE TITLE
build

### ISSUE THREAD

**Issue by zara6697** [godotengine/godot#62736]
### Godot version

3.4.4 stable

### System information

all platform and OS

### Issue description

Dear all,
I have downloaded 3.4.4 stable version code from here and build it with the following instruction.
scons platform=windows bits=64 -j4
the generated .exe file is not the same as the Godot_v3.4.4-stable_win64.exe. my project runs well with Godot_v3.4.4-stable_win64.exe but it  does not run well with generated .exe file.
I could not find what is the reason.
Could you please describe what could be the reason of this problem?
Best regards.

### Steps to reproduce

this is the instruction for building:
scons platform=windows bits=64 -j4

**Comment by akien-mga** [comment]
This issue tracker is for engine bugs, not user support. Please use one of the other [community platforms](https://godotengine.org/community/) for support.

Here you should indeed use the `target` option to configure the optimization level: https://docs.godotengine.org/en/stable/development/compiling/introduction_to_the_buildsystem.html#target
And probably use `production=yes` to get Link-Time Optimization too.

**Comment by zara6697** [comment]
Dear all,
Thanks for your reply. Sorry for the wrong position for asking question.
By setting target the problem is solved.
Thanks.
