### ISSUE TITLE
Curve2D.get_baked_points() does return an empty array

### ISSUE THREAD

**Issue by Dante3085** [godotengine/godot#62734]
### Godot version

3.4.4.stable

### System information

Windows 11

### Issue description

Curve2D.get_baked_points() returns empty array, even thought the Curve2D is clearly defined in the editor:

<img width="720" alt="image" src="https://user-images.githubusercontent.com/26558776/177321810-23579783-3f65-45d4-954b-6e5205e0a36b.png">

1. Had a Path2D node in a scene for a while.
2. Decided to add a Curve2D to that Path2D.
3. After adding Curve2D, called get_baked_points()[0] on Curve2D, but error implied that array is empty.
4. After closing engine and doing something else for a while, it just worked.

### Steps to reproduce

Don't know how to reproduce. I will provide additional information when I get it.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
