### ISSUE TITLE
2D movement gizmos always work in global coordinates despite being rotated

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#62732]
### Godot version

4e7223c

### System information

Windows 10 x64

### Issue description

![godot windows tools 64_VeecI3EiEe](https://user-images.githubusercontent.com/2223172/177313283-b9553937-86ff-473f-8eb8-1f574e1f2042.gif)
They should either not rotate or properly move in local space.

This does not happen with scale gizmos.

### Steps to reproduce

1. Rotate a 2D node
2. Enable move tool
3. Move the node

**Comment by Calinou** [comment]
Is this reproducible in 3.4.4? cc @ZakharE

**Comment by ZakharE** [comment]
@Calinou I cannot reproduce it on branch 3.4 and 3.X. There is no such functionality at all.  There is no gizmos that   I can drag

**Comment by trflorian** [comment]
I observe the same behaviour in Godot 4.1.1.stable.official  [bd6af8e0e] on Linux 20.04.6 LTS
