### ISSUE TITLE
Camera2D get_camera_screen_center() does not immediately update when global_position is changed.

### ISSUE THREAD

**Issue by Dante3085** [godotengine/godot#62740]
### Godot version

3.4.4.stable

### System information

Windows 11

### Issue description

`Camera2D.get_camera_screen_center()` reports the same position before and **directly** after setting the cameras `global_position`.  When calling `get_camera_screen_center()` again after presumably the camera has gone through the next iteration of the game loop, the correct position is reported.

### Steps to reproduce

```
print(get_camera_screen_center())
global_position = Vector2(500, 500)
print(get_camera_screen_center())
```

### Minimal reproduction project

[camera2D_center_bug.zip](https://github.com/godotengine/godot/files/9047789/camera2D_center_bug.zip)

**Comment by Calinou** [comment]
This may not be fixable due to how the camera center is computed. Consider using `yield(get_tree(), "idle_frame")` to delay the code below that line by 1 frame.

**Comment by Dante3085** [comment]
@Calinou You're suggestion doesn't work when smoothing is enabled.
