### ISSUE TITLE
GPUParticles2D Jitter when SceneTree is Paused

### ISSUE THREAD

**Issue by floere** [godotengine/godot#62743]
### Godot version

v4.0.alpha10.official [4bbe7f0b9]

### System information

macOS 12.3.1 (21E258), Metal GPUFamily Apple 7, Vulkan

### Issue description

When pausing the scene tree, I expected all particles to remain in place. Instead, particles jitter between two points. Not all particles do this, on pattern appears to be whether a texture is used or not. See the video below for an example.

In this video, the GPUParticles2D clouds remain static (as expected) but the small GPUParticles2D squares do not (the issue). 

https://user-images.githubusercontent.com/3022/177381429-e008789a-c727-4bb0-85c6-f01327e9a0c7.mp4

This issue is potentially related to #50824. But whether it is depends on the implementation.

### Steps to reproduce

1. Add a GPUParticles2D to the scene, with standard particles emitting.
2. Pause the SceneTree after a while: `get_tree().paused = true`.
3. Observe the jitter.

### Minimal reproduction project

[Particles2DJitter.zip](https://github.com/godotengine/godot/files/9048238/Particles2DJitter.zip)

**Comment by Calinou** [comment]
Does the workaround listed [here](https://github.com/godotengine/godot/issues/50824#issuecomment-994093239) work? If so, this is the same cause as https://github.com/godotengine/godot/issues/50824.
