### ISSUE TITLE
[3.x] Some node icons use the Godot 4 colors

### ISSUE THREAD

**Issue by fire-forge** [godotengine/godot#62750]
### Godot version

v3.5.rc4.official [e047c5006]

### System information

Windows 10

### Issue description

Some node icons are using the Godot 4 color scheme, which is slightly more saturated, instead of the Godot 3 color scheme.

### Label3D
![image](https://user-images.githubusercontent.com/67974470/177412825-78a82766-ab36-4102-9491-964a759c925a.png) ![image](https://user-images.githubusercontent.com/67974470/177414264-11349e92-bf05-403f-a9b6-f6efda6d8edd.png)

### H/VFlowContainer
![image](https://user-images.githubusercontent.com/67974470/177413186-22de1106-5ae2-4325-baac-283e5b4bc2c2.png)
![image](https://user-images.githubusercontent.com/67974470/177414035-7ec438e2-b936-4247-8bd1-cf35b4c0edf7.png)

### CPUParticles2D
![image](https://user-images.githubusercontent.com/67974470/177414515-37a17cae-7278-45ea-8ed9-3ecc30645088.png) ![image](https://user-images.githubusercontent.com/67974470/177414343-a0227f51-66ff-41df-9412-6ed55e74329f.png)

### Steps to reproduce

Check `Label3D.svg`, `HFlowContainer.svg`, and `VFlowContainer.svg` and `CPUParticles2D.svg` in the Godot source code.

**Comment by akien-mga** [comment]
Fixed by #62762.
