### ISSUE TITLE
AssetLib handling of asset upgrades

### ISSUE THREAD

**Issue by puppetmaster-** [godotengine/godot#6277]
*Bugsquad edit.*

**Godot version:**
2.1.3, current master

When upgrade assets / reinstalling a new version, the editor will by default deselect all files with the same filename as in the previously installed version. This is non-optimal in the case of a plugin that users typically wouldn't edit, and for which they'd which the new files to overwrite the old ones (and actually the orphaned old files to be removed).

Long story short, we need better handling of asset versions, with the ability for the project and the assetlib to keep track of installed versions, and to replace them by newer version. Files with user-side modifications that would be overwritten during an upgrade should be backed up.

------------

That makes no sense when asset is from category tools (possible also other category).
![image](https://cloud.githubusercontent.com/assets/10463138/17902246/d5d65ce4-6966-11e6-8e61-1873e2b02500.png)

I added it first on this repro https://github.com/godotengine/asset-library/issues/52

**Comment by akien-mga** [comment]
I don't understand the issue.

**Comment by puppetmaster-** [comment]
I'll check if problem still exists.

**Comment by puppetmaster-** [comment]
Problem still exists... v2.1.3

If you download something from the asset store and there exist an (old) version all duplicated files get automatically deselected.
It should not deselect the files in the list. That makes no sense, especially if it is a tool (category).

**expect**
If asset store has never version it should overwrite all local files per default.

**Comment by bojidar-bg** [comment]
Related: #5947, #7202 (and probably a duplicate to some extent, not sure)

**Comment by puppetmaster-** [comment]
I will close this issue, it is already very old and if there is still a demand I will apply for it again at the new dedicated Godot Improvement Proposals ([GIP](https://github.com/godotengine/godot-proposals)) issue tracker.
