### ISSUE TITLE
Open file by clicking on its name/path in editor

### ISSUE THREAD

**Issue by caryoscelus** [godotengine/godot#6278]
Would be nice to be able to open file by clicking (or ctrl+click, or at least as right-click option, or hotkey) on its name in script editor.

Related: #2982

**Comment by Calinou** [comment]
This feature is now implemented as of Godot 3.0, closing.

![Ctrl+click to open script in editor](https://user-images.githubusercontent.com/180032/38615643-ae33f588-3d91-11e8-9980-7b01119e87fd.png)
