### ISSUE TITLE
Editor crashes when I try to access the NORMAL_ROUGHNESS_TEXTURE

### ISSUE THREAD

**Issue by guilhermefelipecgs** [godotengine/godot#62780]
### Godot version

48738868309b09be1cad21d73a2a9221bfd8f838

### System information

5.18.9-arch1-1

### Issue description

I'm trying to access the `NORMAL_ROUGHNESS_TEXTURE` but whenever I put it in the shader the editor crashes with a huge log.

### Steps to reproduce

Add this shader to a mesh instance

```
shader_type spatial;

void fragment() {
    texture(NORMAL_ROUGHNESS_TEXTURE, UV);
}
```

**Comment by clayjohn** [comment]
This same issue was reported again in https://github.com/godotengine/godot/issues/63217.

https://github.com/godotengine/godot/issues/63217 contains more information and reproduction steps, so closing this PR in favour of https://github.com/godotengine/godot/issues/63217
