### ISSUE TITLE
[Feature Request] Auto Spritesheet Slicing 

### ISSUE THREAD

**Issue by meem40** [godotengine/godot#6279]
@godotengine  should have auto spritesheet slicing, which will greatly enhance productivity for 2D game development. For example unity has a very good .png sprite sheet slicer, it automatically(most of the time accurately) slices the entire sheet into individual sprites which also enhances game performance as only one texture has to be loaded on the memory and each sprite will have its own bounds.

**Comment by MarianoGnu** [comment]
There's an autoslice implementation already, just open the Texture Region editor as you usually do with sprites and change the SnapMode to AutoSlice. Then click on any of the rects to selectits region.
Also hold control to expand current rect to the new rect bounds

**Comment by meem40** [comment]
Thank you very much, i totally missed the bottom tab for texture region.
