### ISSUE TITLE
MultiplayerSynchronizer property strings are inconsistent; `::` vs `:` delimiter

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot#62799]
### Godot version

v4.0.alpha.custom_build [09e12ba9b]

### System information

Arch on 5.18.9-arch1-1 

### Issue description

colons

![image](https://user-images.githubusercontent.com/14253836/177653068-0a08dfa0-8c90-4c58-b31d-8d9ead3f6f51.png)

### Steps to reproduce

1) Make a basic node setup with these exports:

  ```gdscript
  @export var dragging_from_inspector: int
  @export var adding_through_dialog: int
  @export var adding_manually: int
  ```

2) Add each property to the synchronizer using the methods described.

### Minimal reproduction project

[test5.zip](https://github.com/godotengine/godot/files/9058936/test5.zip)

**Comment by Calinou** [comment]
cc @Faless
