### ISSUE TITLE
ShaderMaterial not working in CanvasItem and spamming infinite errors

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#62803]
### Godot version

09e12ba

### System information

Windows 10 x64

### Issue description

This happens when you assign new ShaderMaterial to a sprite:
![godot windows tools 64_YvJGqUIxar](https://user-images.githubusercontent.com/2223172/177664798-0b206c6f-080d-40a6-9455-2856b6020260.gif)
It becomes invisible and spams hundreds of errors per second.

The errors are similar as in #62525, but the issue is recent and doesn't seem related.

### Steps to reproduce

1. Add Sprite2D
2. Add ShaderMaterial

**Comment by akien-mga** [comment]
Clear your `.godot/shader_cache/` folder and that should solve it.

The problem is that we don't do proper cache invalidation when breaking rendering changes happen.

**Comment by KoBeWi** [comment]
Removing shader cache indeed fixed the issue.

**Comment by cridenour** [comment]
> Removing shader cache indeed fixed the issue.
> 
> EDIT: Worth to note that there are 2 shader cache folders - in .godot directory and in user directory. You need to delete them both.

*Thank you!* Not finding the user shader_cache was keeping me on alpha 10.
