### ISSUE TITLE
Connecting signal to inherited function shouldn't create a new one

### ISSUE THREAD

**Issue by caryoscelus** [godotengine/godot#6280]
**Godot version:** 9c6175db11ff72603ae58789a462b33ec1e910f8

**Issue description** (what happened, and what was expected):
When signal is connected through editor (i.e. not code) to inherited function (e.g. Node-based: queue_free, emit_signal, etc), a new function with that name is created. Better behavior would be to detect that function exist and automatically deselect "Create Function" option and indicate that the function is already defined on parent class.

**Comment by kubecz3k** [comment]
Well I'm rather happy with how this works currently. If you have inherited function and you are connecting new signal to it you usually will want to extend this function...

**Comment by caryoscelus** [comment]
Do you usually extend `queue_free`, `emit_signal` and alike?

Not sure about 'normal' inherited functions - i think there are cases where you want and cases where you don't want to extend. So maybe this behavior should only apply to 'system' functions, which are rarely extended.

**Comment by bojidar-bg** [comment]
Well, you can uncheck the "create new function" toggle if you don't want a new function, no?

Also, what if I write "queue_free", then see it unchecks and write "_signal_queue_free", should it recheck? 

What if I write "qf", uncheck it for some reason, then write "queue_free", and finally write "_cleanup", should it end up checked or unchecked?

**Comment by caryoscelus** [comment]
Could be made an option. Or changing only if user hasn't touched checkbox. But to decide what's optimal one has to study typical usecases and workflow and i don't use Godot these days. I can only say that in my workflow back when i created the issue, it was somewhat annoying to either uncheck each time or delete created function.

**Comment by kubecz3k** [comment]
Well I think the most elegant way to deal with this would be to make the checkbox to remember it's previous state.

**Comment by akien-mga** [comment]
This seems to be fixed as of Godot 3.2.1. Connecting a signal to a builtin class method does not create a callback, unless it is a virtual method, in which case this is intended.
