### ISSUE TITLE
_process(delta) not called in VR

### ISSUE THREAD

**Issue by Ranplax** [godotengine/godot#62817]
### Godot version

3.4.stable

### System information

Windows 10

### Issue description

The attatched minimal version of the project creates a few simple asteroids that rotate around saturn. The rotate script, which lets the asteroids rotate does so in the _process(delta) function.

In the 3D Version of the project, this _process() function is called and the rotation is working.
In the VR Version of the project, this _process() function is not called, therefore the asteroids are not rotating in VR. 
If however, the _process() function is called manually in the vr._process() function, the rotation does work.
This can be seen by commenting out the return statement in vr.gd.

In both scene, 3D and VR, the objects and loaded identically by the scene_decoder.gd and the rotate script is applied in this decoder. This is happening in the create_object(...) function, line 267.

### Steps to reproduce

1. Download the OpenVR module from the assetLib
2. Start the 3D Programm, press f to enable free flight and move to the object. The asteroids should rotate. Press h for further help.
3. Start the VR Programm, the asteroids should be static. 
4. In vr.gd, comment out the return statement in the _process(delta) function to see a working version in VR

### Minimal reproduction project

[godot.zip](https://github.com/godotengine/godot/files/9063307/godot.zip)

**Comment by Calinou** [comment]
cc @BastiaanOlij

**Comment by Ranplax** [comment]
We were able to identify the bug and fix it. The issue was caused by a mistake from us, hence this issue is obsolete now.

**Comment by Calinou** [comment]
@Ranplax Did you find a solution to this problem? If so, please document it here by commenting :slightly_smiling_face:

**Comment by Ranplax** [comment]
Hmm, i guess 'we identified the issue' might have been pushing it a bit. We did a general restructure within our project and this resulted in fixing the problem. Due to that, it is unfortunately not exactly clear what caused or fixed it, sorry.
