### ISSUE TITLE
Features list in export window shows misplaced comma and space

### ISSUE THREAD

**Issue by samdze** [godotengine/godot#62815]
### Godot version

4.0 master

### System information

macOS 12.4

### Issue description

![Godot 2022-07-07 at 13 27 37](https://user-images.githubusercontent.com/19392104/177763042-52ad6a1f-4e6d-47c2-a1db-1fcef0997718.png)

### Steps to reproduce

Add an export preset and go to the Features tab.

**Comment by akien-mga** [comment]
I can reproduce the bug on Linux.

It's pretty weird though as the code that handles this seems correct to me:

https://github.com/godotengine/godot/blob/95ddc8cccc2ad14ff8731b96f3764c88d202f9d3/editor/project_export.cpp#L368-L378
