### ISSUE TITLE
Compiling for Android on Windows fails

### ISSUE THREAD

**Issue by madmiraal** [godotengine/godot#62810]
### Godot version

master (f60cb2931c74d68b19b18c15442c1043d2ebb884)

### System information

Windows 11 21H2, Android

### Issue description

Building for Android on Windows currently fails. This is a regression from 39ed39900e34e10f40d0d06ed358d2641d7f3315 (#59167), which added [thirdparty/zstd/decompress/huf_decompress_amd64.S](https://github.com/godotengine/godot/commit/39ed39900e34e10f40d0d06ed358d2641d7f3315#diff-5e087c5e7e789af198d41e864c0912fa47c4158c024879fa253a8ba1b4f692e2).

With `android_arch=armv7`:
```
C:\Android\android-sdk/ndk/23.2.8568313/toolchains/llvm/prebuilt/windows-x86_64/arm-linux-androideabi/bin/as -o thirdparty\zstd\decompress\huf_decompress_amd64.android.opt.armv7.o thirdparty\zstd\decompress\huf_decompress_amd64.S
=====
scons: *** [thirdparty\zstd\decompress\huf_decompress_amd64.android.opt.armv7.o] Error 1
b"thirdparty\\zstd\\decompress\\huf_decompress_amd64.S: Assembler messages:\r\nthirdparty\\zstd\\decompress\\huf_decompress_amd64.S:33: Error: bad instruction `zstd_hide_asm_function(HUF_decompress4X1_usingDTable_internal_bmi2_asm_loop)'\r\nthirdparty\\zstd\\decompress
```
With `android_arch=arm64v8`:
```
C:\Android\android-sdk/ndk/23.2.8568313/toolchains/llvm/prebuilt/windows-x86_64/aarch64-linux-android/bin/as -o thirdparty\zstd\decompress\huf_decompress_amd64.android.opt.armv8.o thirdparty\zstd\decompress\huf_decompress_amd64.S
=====
 scons: *** [thirdparty\zstd\decompress\huf_decompress_amd64.android.opt.armv8.o] Error 1
b"thirdparty\\zstd\\decompress\\huf_decompress_amd64.S: Assembler messages:\r\nthirdparty\\zstd\\decompress\\huf_decompress_amd64.S:33: Error: unknown mnemonic `zstd_hide_asm_function' -- `zstd_hide_asm_function(HUF_decompress4X1_usingDTable_internal_bmi2_asm_loop)'\r\nthirdparty\\zstd\\decompress
```
With `android_arch=x86`
```
C:\Android\android-sdk/ndk/23.2.8568313/toolchains/llvm/prebuilt/windows-x86_64/i686-linux-android/bin/as -o thirdparty\zstd\decompress\huf_decompress_amd64.android.opt.x86.o thirdparty\zstd\decompress\huf_decompress_amd64.S
=====
scons: *** [thirdparty\zstd\decompress\huf_decompress_amd64.android.opt.x86.o] Error 1
b"thirdparty\\zstd\\decompress\\huf_decompress_amd64.S: Assembler messages:\r\nthirdparty\\zstd\\decompress\\huf_decompress_amd64.S:33: Error: no such instruction: `zstd_hide_asm_function(HUF_decompress4X1_usingDTable_internal_bmi2_asm_loop)'\r\nthirdparty\\zstd\\decompress
```
With `android_arch=x86_64`
```
C:\Android\android-sdk/ndk/23.2.8568313/toolchains/llvm/prebuilt/windows-x86_64/x86_64-linux-android/bin/as -o thirdparty\zstd\decompress\huf_decompress_amd64.android.opt.x86_64.o thirdparty\zstd\decompress\huf_decompress_amd64.S
=====
scons: *** [thirdparty\zstd\decompress\huf_decompress_amd64.android.opt.x86_64.o] Error 1
b"thirdparty\\zstd\\decompress\\huf_decompress_amd64.S: Assembler messages:\r\nthirdparty\\zstd\\decompress\\huf_decompress_amd64.S:33: Error: no such instruction: `zstd_hide_asm_function(HUF_decompress4X1_usingDTable_internal_bmi2_asm_loop)'\r\nthirdparty\\zstd\\decompress
```
Note: Each architecture uses it's own `as` assembler compiler; so there is no need to specify the architecture as done in #62587 (the fix for Macos).

### Steps to reproduce

On Windows on the master branch run:
- `scons platform=android android_arch=armv7`
- `scons platform=android android_arch=arm64v8`
- `scons platform=android android_arch=x86`
- `scons platform=android android_arch=x86_64`
 

### Minimal reproduction project

N/A

**Comment by madmiraal** [comment]
The problem exists when building on Macos too, but only for `android_arch=x86_64`, and only during linking:
```
ld: error: core/libcore.android.opt.x86_64.a(huf_decompress_amd64.android.opt.x86_64.o): not an ELF file
```

**Comment by madmiraal** [comment]
Compile logs for all architectures for all OSes: https://github.com/madmiraal/godot/actions/runs/2628194052

**Comment by akien-mga** [comment]
> The problem appears to be that the as [preprocessing](https://ftp.gnu.org/old-gnu/Manuals/gas-2.9.1/html_node/as_26.html) does not do macro processing, file handling or anything else you may get from your C compiler's preprocessor.

That page also states:

> You can do include file processing with the .include directive (see section [.include "file"](https://ftp.gnu.org/old-gnu/Manuals/gas-2.9.1/html_node/as_95.html#SEC97)). You can use the GNU C compiler driver to get other "CPP" style preprocessing, by giving the input file a `.S' suffix.

Does changing the `#include` to `.include` fix it?

I'm surprised `android_arch=x86_64` fails as it should actually be able to compile and use such assembly. That's the only reason why `android` is not excluded from compiling that file.

Anyway, the simplest solution is just to add some ugly logic in the `SCsub` to try to narrow down to only explicit `x86_64` for Linux, macOS and Windows and not bother about Android/iOS `x86_64`. I'll PR something.

**Comment by madmiraal** [comment]
> Does changing the #include to .include fix it?

Even changing the `#if ZSTD_ENABLE_ASM_X86_64_BMI2` to `#if 0` doesn't fix it. It's simply ignored.

**Comment by bruvzg** [comment]
> Does changing the #include to .include fix it?

This break macOS build.

**Comment by bruvzg** [comment]
> I'm surprised android_arch=x86_64 fails as it should actually be able to compile and use such assembly. That's the only reason why android is not excluded from compiling that file.

I can confirm this on macOS, for some reason `S` file is compiled into the Mach-O not ELF file.

**Comment by bruvzg** [comment]
> I can confirm this on macOS, for some reason S file is compiled into the Mach-O not ELF file.

I case of macOS, it's fixable by adding `ASFLAGS`, to the Android `detect.py` (alongside equivalent `CCFLAGS` and `LINKFLAGS`):

```
env.Append(ASFLAGS=target_option)
```

**Comment by bruvzg** [comment]
Unlike build on Windows, build on macOS seems to be using `clang` binary instead of `as` to build `S` file, which might be the reason includes/pre-processing work.

I guess it might be worth trying to replace it for other platforms (have not tested):

```diff
-env["AS"] = bin_utils_path + "/as"
+env["AS"] = compiler_path + "/clang"
```

**Comment by bruvzg** [comment]
> I guess it might be worth trying to replace it for other platforms (have not tested):

This seems to be working on Windows and macOS - https://github.com/godotengine/godot/pull/62813
