### ISSUE TITLE
--no-window argument opens editor when running --export

### ISSUE THREAD

**Issue by nabware** [godotengine/godot#62828]
### Godot version

4.0.alpha11 (afdae67cc)

### System information

Manjaro Linux 21.3.2, Vulkan API 1.2.0, NVIDIA GeForce GTX 1070 (515.57)

### Issue description

When I run `godot --export "Linux/X11" --no-window`, the Godot editor opens for a couple of seconds and then closes. I expect Godot to export without opening the editor when using the `--no-window` argument.

The [docs](https://docs.godotengine.org/en/latest/tutorials/editor/command_line_tutorial.html) state Godot will run with an invisible window.

Maybe related to #43752, #43948

### Steps to reproduce

run `godot --export "Linux/X11" --no-window`

**Comment by akien-mga** [comment]
There's no `--no-window` option anymore, use `--headless` for this: https://github.com/godotengine/godot/blob/master/main/main.cpp#L333
