### ISSUE TITLE
AnimationPlayer's RESET track defaults to Continuous for discrete properties

### ISSUE THREAD

**Issue by Streq** [godotengine/godot#62822]
### Godot version

v3.4.4.stable.official [419e713a2]

### System information

Ubuntu 20.04.3 LTS

### Issue description

When a new track is created for a discrete property, like a resource, or a bool, the RESET track for that property is created in continuous mode, which sometimes (couldn't figure out the reproduction conditions) results in said property not resetting when the RESET animation is played (this is fixed by manually setting the track to Discrete).

### Steps to reproduce

- Create a new scene consisting of an AnimationPlayer
- Create a new animation
- While the Animation Panel is open click on the keyframe button ![image](https://user-images.githubusercontent.com/8540266/177824792-bba48b45-ab4a-45f4-9f4d-f7174b0aa29a.png) for the property Reset On Save (though any boolean property will do)
- When prompted leave as is and click create 
![image](https://user-images.githubusercontent.com/8540266/177825159-57c11a25-1eaa-408b-8b84-c6b0c9a24ccf.png)
- Notice the track in the RESET animation is set to Continuous
![image](https://user-images.githubusercontent.com/8540266/177825260-aa355987-7c36-4131-864e-107abb5e2427.png)
- While the track in the actual animation is set to Discrete
![image](https://user-images.githubusercontent.com/8540266/177829659-f1760ad2-8d11-4f5b-bcb2-cab413dd031e.png)

### Minimal reproduction project

(omitted since it occurs while editing and it can be reproduced using a scene composed of just an AnimationPlayer)

**Comment by Calinou** [comment]
cc @RandomShaper

**Comment by KoBeWi** [comment]
Pretty sure the update mode shouldn't affect the property resetting. The track has only one key, so it's irrelevant.

**Comment by Streq** [comment]
@KoBeWi the specific instance where this quirk became, or rather uncovered, a bug involved a shader material property not being reset in the RESET animation, until the mode was set to Discrete, I can still reproduce it in my project, but I couldn't isolate the bug, I'll try to come up with a minimal reproduction project.
