### ISSUE TITLE
Black screen when opening a project in the web version [3.5.rc6]

### ISSUE THREAD

**Issue by bitbotzgames** [godotengine/godot#62836]
### Godot version

v3.5.rc6.official.f05cecdc4

### System information

Windows 10, OpenGL ES 3.0 Renderer: WebKit WebGL, NVIDIA GeForce GTX 1660 Driver Version: 497.29

### Issue description

Edge version: 103.0.1264.49 (Offizielles Build) (64-Bit)
(Also happens in Chrome)
I disabled all my edge extensions.

Edge shows me some errors:

![Unbenannt](https://user-images.githubusercontent.com/83534976/177990828-a6d9b2a9-91a6-4dc1-9db2-4b690a9d920a.png)

### Steps to reproduce

Open the web version of the 3.5.rc6 Godot version.
Start the editor, create a new project and open it.
After a few seconds the editor should become black.

(This also happend to me when i open an existing project)

### Minimal reproduction project

_No response

_

**Comment by akien-mga** [comment]
This was supposed to be fixed by #62531 but apparently there's still some case not handled @Faless.

**Comment by akien-mga** [comment]
Fixed by ad5fdcc0f3d8c0715429f2d533f577748b477f01.

**Comment by akien-mga** [comment]
I've uploaded a fixed build for 3.5 RC 6, it should be fine now. (You might need a hard refresh to make sure you get the new version built from 861e15554398c98630b905c8f2273477bdba5f99.)
