### ISSUE TITLE
Project Converter: Wrong @rpc annotations

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot#62832]
### Godot version

5268efdcd9b8e07ed8363f6f32a343392ab4acdf

### System information

n/a

### Issue description

Looks like it's using `@rpc(any)`, `@rpc(auth)`, `@rpc(sync)`.

Correct: `@rpc(any_peer)`, `@rpc(authority)`, `@rpc(call_local)` and related.

Also there seems to be `sync func` which I don't think is valid.

https://github.com/godotengine/godot/blob/master/editor/project_converter_3_to_4.cpp#L3727-L3789

### Steps to reproduce

1)

**Comment by qarmin** [comment]
Can you list all the 3.x -> 4.0 network keyword name changes?
My knowledge of network topics in Godot is rather poor, so I am not able to verify their correctness.
About the conversions present in the converter I once asked @Faless, but looks that now this info is outdated or I messed something when preparing conversions.

**Comment by nathanfranke** [comment]
`remote` -> `@rpc(any_peer)`
`remotesync` -> `@rpc(any_peer, call_local)`
`puppet` -> `@rpc`
`puppetsync` -> `@rpc(call_local)`

These should print a warning (if possible):

> The `master` and `mastersync` rpc behavior is not officially supported anymore. Try using another keyword or making custom logic using `get_multiplayer().get_remote_sender_id()`

`master` -> `@rpc`
`mastersync` -> `@rpc(call_local)`

**Comment by raulsntos** [comment]
As far as I know the `sync` and `slave` keywords were deprecated but still in exist in 3.x for compatibility so some user might still be using them and we may want to add a conversion for them. See #22087 for context.

Essentially, `sync` is the same as `remotesync` and `slave` is the same as `puppet`. So I guess:

`sync` -> `@rpc(any_peer, call_local)`
`slave` -> `@rpc`
