### ISSUE TITLE
SWF animation file to Godot

### ISSUE THREAD

**Issue by meem40** [godotengine/godot#6283]
There is already a c++ port of SAM project for godot http://gizmothunder.blogspot.com/2015/03/flash-animations-in-godot-engine.html which allows SWF to convert into its separate node. Will this support be possible directly inside Godot in the future?  like Just drag and drop SWF files to create vector animation directly within the engine? 
http://gizmothunder.blogspot.com/2015/03/flash-animations-in-godot-engine.html
https://github.com/vkbsb/godot_sam
https://github.com/raymondlu/super-animation-samples

**Comment by vnen** [comment]
I fixed the link formatting in the OP. Just paste the link address if you don't want to add any different text.

I don't this will make to the core, but it can be made as a separate module.

**Comment by Chaosus** [comment]
Yeah, its better to be plugin. The Flash itself is deprecated and unsafe technology(and the animation format is proprietary, which is not allowed to be included to Godot core). Closed.

**Comment by jkb0o** [comment]
There some good stuff https://github.com/funexpected/godot-flash-module
