### ISSUE TITLE
Changes to themes that a control indirectly inherit items from don't cause the control to update

### ISSUE THREAD

**Issue by AaronRecord** [godotengine/godot#62844]
### Godot version

3.4.4

### System information

Windows 11

### Issue description

https://user-images.githubusercontent.com/50304111/178061867-15132533-2f5b-432b-a46d-19a3465304ce.mp4

See also https://github.com/godotengine/godot/issues/61765
See also https://github.com/godotengine/godot/issues/63889
### Steps to reproduce

^^

### Minimal reproduction project

[mrp.zip](https://github.com/godotengine/godot/files/9074765/mrp.zip)

**Comment by YuriSizov** [comment]
I'd probably split this issue in two. The issue about indirect dependency inside of the tree is solved by https://github.com/godotengine/godot/pull/62845, but the issue with project theme/default theme changing would likely require some different solution.

**Comment by AaronRecord** [comment]
Opened a new issue https://github.com/godotengine/godot/issues/63889
