### ISSUE TITLE
[3.5.rc6] Viewport HDR Warning can't go away when rendering usage is set to 2D

### ISSUE THREAD

**Issue by oeleo1** [godotengine/godot#62841]
### Godot version

3.5.rc6

### System information

Windows

### Issue description

Setting the Viewport rendering usage to 2D or 2D Without Sampling generates a Warning about HDR being used but ignored, although HDR is disabled in the project settings (Rendering Depth HDR is off). Can't get rid of that warning. The 2D buffer usage is desired as it is the best speed/space tradeoff for 2D games without advanced effects.

### Steps to reproduce

Create a scene tree and add a Viewport node. Change its usage to 2D or 2D Without Sampling

![image](https://user-images.githubusercontent.com/40200623/178043663-bf31d171-16f3-45ac-88aa-7bf5dbc3e612.png)

### Minimal reproduction project

[Viewport_HDR_Warning.zip](https://github.com/godotengine/godot/files/9073497/Viewport_HDR_Warning.zip)

**Comment by Calinou** [comment]
The HDR project setting only affects the root viewport if I'm not mistaken. However, if the root viewport doesn't use HDR, then I suppose enabling HDR in subviewports is useless in most situations.

**Comment by oeleo1** [comment]
While I agree with this, the question about HDR being used selectively in viewports remains debatable. We don’t use it, but people might.

The problem here is more that the HDR setting is not exported in the side panel interface of the editor in order to be able to shut the (legitimate) warning. So the easy way out is to export that property together with the buffer usage in the side panel without entering the HDR usage debate across viewports.

**Comment by oeleo1** [comment]
The other thing that makes sense is to make all viewports follow the HDR setting of the root viewport at init time. Thus by adjusting the HDR in the projet settings one forgets about configuring other viewports, unless it is done by script explicitly. This is orthogonal to the idea of exposing the HDR setting in the editor. In any case this warning is annoying both ways :-)

**Comment by Calinou** [comment]
> The other thing that makes sense is to make all viewports follow the HDR setting of the root viewport at init time.

Unfortunately, doing so will waste memory and decrease performance in a lot of scenarios.

**Comment by oeleo1** [comment]
OK this is fixed in 3.5.1.rc1 by (https://github.com/godotengine/godot/pull/65063)
