### ISSUE TITLE
Downscaled goto function/line windows

### ISSUE THREAD

**Issue by profelis** [godotengine/godot#6285]
**Operating system or device - Godot version:**
Mac OS (retina display, hiDPi mode) Godot latest (9c6175db11ff72603ae58789a462b33ec1e910f8)

**Issue description** (what happened, and what was expected):
Goto function/line windows are downscaled (like in lodpi mode)
https://i.gyazo.com/c1342e454b09d0795b663fa017e123db.png
In same time help/open file windows looks normal

Note: In Latest Godot 2.1 stable release goto function/line don't have this problem

**Comment by bojidar-bg** [comment]
Can someone reconfirm that his issue is still valid (on master and on 2.1/HEAD (2.1.3-rc2))?

**Comment by KoBeWi** [comment]
I tested it in stable releases and none of them seem to have the issue. Sadly I can't compile at the mentioned commit, but since no one else confirmed the issue in few years, I assume this was fixed at some point.
