### ISSUE TITLE
Vulkan: Normal map on MeshInstance2D doesn't work anymore

### ISSUE THREAD

**Issue by SneaK1ng** [godotengine/godot#62855]
### Godot version

v4.0.alpha d26442e70

### System information

Win10, Vulkan API 1.2.189  GeForce GTX 1060

### Issue description

The normal map for MeshInstance2D in Godot 4.0 doesn't work:
![image](https://user-images.githubusercontent.com/6891132/178107677-ee10301f-11db-415b-9806-a97d86c4c47d.png)

Displayed correctly in 3.3.2
![image](https://user-images.githubusercontent.com/6891132/178107731-bc17ea29-37f0-4cbe-b4cc-32d18e322695.png)

**mesh_instance_2d.cpp Line 35-43:**
Is it not being used?

> void MeshInstance2D::_notification(int p_what) {
> 	switch (p_what) {
> 		case NOTIFICATION_DRAW: {
> 			if (mesh.is_valid()) {
> 				draw_mesh(mesh, texture);
> 			}
> 		} break;
> 	}
> }

### Steps to reproduce

1. Create a new Scene
2. Add a MeshInstance2D
3. Set the Mesh/Texture/Normalmap properties of MeshInstance2D
4. Add a PointLight2D to the Scene
5. Can't see any effects of the Normal Map

### Minimal reproduction project
[Test.zip](https://github.com/godotengine/godot/files/9077257/Test.zip)

**Comment by SneaK1ng** [comment]
Should use a CanvasTexture?
[https://github.com/godotengine/godot/commit/84d734da0e4dc4f0076c61a7178d8ad7b9f3b616](url)

> Refactored 2D shader and lighting system
> -**Removed normal/specular properties from nodes**
> -**Create CanvasTexture, which can contain normal/specular channels**
> -Refactored, optimized and simplified 2D shaders
> -Use atlas for light textures.
> -Use a shadow atlas for shadow textures.
> -Use both items aboves to make light rendering stateless (faster).
> -Reorganized uniform sets for more efficiency.

**Comment by Calinou** [comment]
> Should I use a CanvasTexture?

Yes, but I don't know if MeshInstance3D properly supports them.

**Comment by cobolfoo** [comment]
I can confirm I have the same problem with normal maps but with 2D Sprite

**Comment by Calinou** [comment]
> I can confirm I have the same problem with normal maps but with 2D Sprite

Which Godot version are you using? Can you upload a minimal reproduction project?
