### ISSUE TITLE
Can't disconnect signals in inherited scenes

### ISSUE THREAD

**Issue by Lorespo** [godotengine/godot#62851]
### Godot version

v3.5.rc6.official (f05cecdc4)

### System information

Windows 10

### Issue description

When i try to disconnect a signal inside a inherited scene and then close and re-open the scene the Signal is still connected to the same method

### Steps to reproduce

Step 1: create a scene, add a node and a script attached to it
Step2: connect a signal to the script
Step3: inherit the scene
Step4: disconnect the signal in the inherited scene
Step5: save, close and re-open the inherited scene

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/12373.
