### ISSUE TITLE
Can't copy node path with Ctrl-Shift-C if Property selected.

### ISSUE THREAD

**Issue by ondesic** [godotengine/godot#62866]
### Godot version

3.5 rc6

### System information

Windows 11

### Issue description

If you open Project menu and select any setting, then when you use Ctrl+Shift+C on a node, it will copy the Project setting path and not the selected Node.

### Steps to reproduce

Open project
Open the "Project|Project Settings" window.
You can select any property, but just for fun, under the "Application/Config" page, select "Description"
close the Project settings window.
Select a Node and press Ctrl+Shift+C.

Now paste the path that was selected.  Instead of the Node path, you will get "application/config/description".

### Minimal reproduction project

[TestStorage.zip](https://github.com/godotengine/godot/files/9077971/TestStorage.zip)

**Comment by Calinou** [comment]
This may be a regression from https://github.com/godotengine/godot/pull/39404. cc @rcorre

**Comment by rcorre** [comment]
I can repro this in 3.5, but not in 4.0.

**Comment by akien-mga** [comment]
Fixed by #63197.
