### ISSUE TITLE
`SkeletonModificationStack3D.strength` distorts bones when using SkeletonModification3DLookAt

### ISSUE THREAD

**Issue by vfig** [godotengine/godot#62877]
### Godot version

v4.0.alpha11.official [afdae67cc]

### System information

Windows 10

### Issue description

When a `SkeletonModificationStack3D` has a `SkeletonModification3DLookAt`, setting its`strength` to a value between 0.0 and 1.0 does not blend the rotation, but instead skews things:

https://user-images.githubusercontent.com/81129/178138189-42cccf95-5fe3-4716-8896-b34c73a138b9.mp4

### Steps to reproduce

Run the MRP, which animates between strength=0.0 and strength=1.0.

### Minimal reproduction project

[bug_skeletonmodifier3d_strength.zip](https://github.com/godotengine/godot/files/9078750/bug_skeletonmodifier3d_strength.zip)

**Comment by Calinou** [comment]
cc @TwistedTwigleg

**Comment by TokageItLab** [comment]
Closed by #63588.
