### ISSUE TITLE
Sometimes I get `Failed to create Windows OS window` after undo/redo actions (DisplayServer regression)

### ISSUE THREAD

**Issue by lufog** [godotengine/godot#62875]
### Godot version

v4.0.alpha11.official [d631ee330]

### System information

Windows 11, Vulkan Clustered, GeForce 1660 (516.59)

### Issue description

https://user-images.githubusercontent.com/10379487/178137177-2e42a274-43ac-4e29-b467-6957fdd12cf4.mp4

### Steps to reproduce

This happens quite rarely, usually when working with `Control` nodes and using undo/redo extensively.

**Comment by Maclay74** [comment]
I have the same problem on v4.0.beta1.mono.official [4ba934bf3]

But for me it's a matter of a few seconds after I start the editor.

**Comment by akien-mga** [comment]
Can this still be reproduced in the latest 4.0 betas?

**Comment by lufog** [comment]
@akien-mga, since the opening of this issue, this problem has reproduced for me only once, in one of the first beta versions. At the moment I can't reproduce it.

**Comment by akien-mga** [comment]
Thanks, closing as likely fixed then.
