### ISSUE TITLE
macos requires release and debug template paths for custom release exports

### ISSUE THREAD

**Issue by nabware** [godotengine/godot#62873]
### Godot version

4.0.alpha11 (afdae67)

### System information

Manjaro Linux 21.3.2, Vulkan API 1.2.0, NVIDIA GeForce GTX 1070 (515.57)

### Issue description

In my Github Actions workflow, I need to set both "custom_template/release" and "custom_template/debug" to export a custom release build. If I only set the "custom_template/release" path, Godot errors out because it looks for the export template in the default location.

I expect to only have to set custom template release path if I'm only exporting a release build which is the case for windows and linux exports.

```
ERROR: Cannot export project with preset "macos" due to configuration errors:
No export template found at the expected path:
/home/runner/.local/share/godot/templates/4.0.alpha11/osx.zip
```

### Steps to reproduce

remove setting the debug path below to reproduce error

`sed -i -e 's|custom_template/release=.*|custom_template/release="godot-export-templates/macos-latest/osx.zip"|g' -e 's|custom_template/debug=.*|custom_template/debug="godot-export-templates/macos-latest/osx.zip"|g' export_presets.cfg`

`./godot-binary --headless --export macos`

**Comment by nabware** [comment]
Closing as I'm no longer tracking this. I'll continue setting the debug path with the release template path.

**Comment by akien-mga** [comment]
Well it's still inconsistent with other platforms so it should be fixed.

**Comment by sroarty** [comment]
I'd like to work on this issue. 🙂

**Comment by akien-mga** [comment]
Sure, go ahead. The problem should be around here:

https://github.com/godotengine/godot/blob/0056acf46fc88757cae9d9f6fe9805f0eec1cd09/platform/macos/export/export_plugin.cpp#L1747

**Comment by sroarty** [comment]
I'm still very new to the codebase and I'll have to explore export templates further, but:
https://github.com/godotengine/godot/blob/0056acf46fc88757cae9d9f6fe9805f0eec1cd09/platform/macos/export/export_plugin.cpp#L1768-L1772
This behavior seems unique from other platform exports. I'm going to test adapting the code pattern from the ios export.
