### ISSUE TITLE
What's up with the for loop and strings?

### ISSUE THREAD

**Issue by Remixful** [godotengine/godot#6287]
**Operating system or device - Godot version:**
Windows 10 - v2.1.stable.official on Steam

**Issue description** (what happened, and what was expected):
Some empty character is showing up when I use the "for x in string:" loop.

**Steps to reproduce:**
```
	var myString = "foo"
	for i in myString:
		print(i)
```
**Output:**
![image](https://cloud.githubusercontent.com/assets/8620268/17990560/f94dc5e6-6b04-11e6-9577-ff3f29070a17.png)

Nothing strange yet. Even if you were to loop this, you'd still get "foofoofoo". Why? Because empty strings won't get printed. 

But what if we do this?
```
	for i in myString:
		var printMe = "*" + i + "*"
		print(printMe)
```

**Output:**
![image](https://cloud.githubusercontent.com/assets/8620268/17990647/8f5f572a-6b05-11e6-836f-166b4bc9cb4e.png)

This is when things start to get strange.

We can try this too:
```
    for i in myString:
        print(i.length())
```
**Output:**
![image](https://cloud.githubusercontent.com/assets/8620268/17990837/60b76f3c-6b07-11e6-8817-0f4c43b38d8e.png)

What's causing this? Of course you can just do "for i in range(0,myString.length())" instead, but it doesn't change the fact that there is still a problem with "for i in myString".

**Comment by vnen** [comment]
Likely the null terminating character of the string is also going to the iterator.

**Comment by vnen** [comment]
For reference, this PR added iteration to strings: #5443.

**Comment by Sslaxx** [comment]
Could this be backported to the 2.1.x branch?

**Comment by neikeq** [comment]
@akien-mga Another good candidate to cherry-pick.
