### ISSUE TITLE
Vulkan: Strange black line artifact in SSAO when Half Size is enabled

### ISSUE THREAD

**Issue by josefkaragoli** [godotengine/godot#62881]
### Godot version

d26442e709f6361af9ac755ec9291bb43f2cd69b

### System information

Windows 10, GTX 1060 6GB

### Issue description

When SSAO quality is set to above "Low (Fast)" a weird line appears directly in the middle of the screen - it seems like some visual artifact - It always appears, but when `ssao_detail` is lowered the artifact is less visible, albeit still there.

SSAO OFF
![image](https://user-images.githubusercontent.com/76781125/178143225-aa4c6c77-3b3f-4cb9-a567-bfffde426ae6.png)

SSAO on Medium
![image](https://user-images.githubusercontent.com/76781125/178143277-032f0b3a-ddcc-4b35-ae6a-03dce3d9fae1.png)

SSAO on Low
![image](https://user-images.githubusercontent.com/76781125/178143283-1a2cdc5a-38d3-4a07-8355-a6f0e14c0a04.png)

I think it doesn't show on low because Low doesn't use the detail pass in SSAO though I'm not sure.

### Steps to reproduce

Open any scene in godot. Enable SSAO in the WorldEnvironment, and if you can't see the strange line then increase Detail and Intensity of the SSAO.

**Comment by mrjustaguy** [comment]
Half Resolution used?

**Comment by josefkaragoli** [comment]
Yes, everything at its default settings

**Comment by Calinou** [comment]
This line will move around when you resize the viewport (which happens when resizing the editor window).

**Comment by mrjustaguy** [comment]
Turn off Half resolution, as if the height/width of half the resolution are not both integers you get issues with it.

I've experienced a similar issue in shipped games (such as Ark Survival Evolved a UE4 title where SSAO had such Lines appearing) where on settings when Screen Space Effects are using half resolution when the Screen Resolution is such that half of it doesn't return Integer values for both.

**Comment by Calinou** [comment]
**Minimal reproduction project:** [test_ssao_half_size.zip](https://github.com/godotengine/godot/files/9079562/test_ssao_half_size.zip)

I can notice flickering when resizing the viewport with Half Size enabled in the Project Settings, but everything looks OK when Half Size is disabled:

### SSAO Half Size enabled (default)

https://user-images.githubusercontent.com/180032/178156065-5ded9a9d-983c-40ff-8d31-1f710de166d5.mp4

### SSAO Half Size disabled

https://user-images.githubusercontent.com/180032/178156068-94012856-2cf1-4989-95f0-76bb72de90b5.mp4

I don't notice a line in the middle in either though.

**Comment by clayjohn** [comment]
May be fixed by https://github.com/godotengine/godot/pull/72838
