### ISSUE TITLE
Add Method Track can be accepted immediately and will just do nothing

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#62893]
### Godot version

d26442e

### System information

Windows 10 x64

### Issue description

![godot_Ta4CY1X5bO](https://user-images.githubusercontent.com/2223172/178156821-08aa91f3-071a-4c00-a57f-bc0434206de1.gif)
The OK button should be disabled until a node is selected.

### Steps to reproduce

1. Add AnimationPlayer and Animation
2. Click Add Track -> Add Method Track
3. Just press OK without touching anything else

**Comment by Calinou** [comment]
I can confirm this on 3.5.rc 875a0dba5.
