### ISSUE TITLE
Error in Editor Settings about hint range step

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#62897]
### Godot version

d26442e

### System information

Windows 10 x64

### Issue description

![image](https://user-images.githubusercontent.com/2223172/178160330-1512eb75-e5ac-40f9-a39e-470873402ad0.png)
caused by
https://github.com/godotengine/godot/blob/d26442e709f6361af9ac755ec9291bb43f2cd69b/editor/editor_node.cpp#L6116
This line wasn't changed in 2 years, so the error was probably introduced recently by adding some hint validation.

### Steps to reproduce

1. Open Editor Settings
2. Filter for "step"
3. Click Inspector tab on the left

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot/pull/58763.
