### ISSUE TITLE
Groups of arguments binded with chained `Callable.bind` calls are appended in reversed call order

### ISSUE THREAD

**Issue by kleonc** [godotengine/godot#62891]
### Godot version

4.0.alpha11

### System information

N/A

### Issue description

Currently `callable.bind(a1, a2).bind(b1, b2)` is equivalent to `callable.bind(b1, b2, a1, a2)`. I think it should be equivalent to `callable.bind(a1, a2, b1, b2)`.

### Steps to reproduce

Run this script:
```gdscript
@tool
extends EditorScript

func _run():
	f.bind(1, 2, 3).call(0)
	f.bind(1, 2).bind(3).call(0)
	f.bind(1).bind(2, 3).call(0)
	f.bind(1).bind(2).bind(3).call(0)
	
func f(a, b, c, d) -> void:
	prints(a, b, c, d)
```
Output:
```
0 1 2 3
0 3 1 2
0 2 3 1
0 3 2 1
```

Expected output:
```
0 1 2 3
0 1 2 3
0 1 2 3
0 1 2 3
```

**Comment by cdemirer** [comment]
Technically, this is [documented behavior](https://docs.godotengine.org/en/latest/classes/class_callable.html?highlight=Bound%20arguments%20are%20passed%20after%20the%20arguments%20supplied%20by%20call.#class-callable-method-bind).

But I agree that it's not intuitive (especially when following Python terminology).

**Comment by vnen** [comment]
So, this is not really a bug, it's just the way `bind()` works. That is, it always bind the last arguments. Taking that into account it is really expected behavior. A Callable for a function with 2 parameters is the same as a Callable for a function with 4 parameters that has 2 bound arguments, so it shouldn't reorder the already bound ones.

**Comment by AThousandShips** [comment]
Closed by #76158 clarifying the order

**Comment by YuriSizov** [comment]
Yeah, I agree.

**Comment by AntonBogun** [comment]
While this is documented behaviour, it doesn't seem to be "right" behaviour. I want my bind to act in the "first argument bound comes first" way, but it seems there isn't any way to extend Callable to add an "alt_bind()" or something like that.
I suppose this isn't that big of a deal but I would still greatly prefer to having to think backwards about my arguments. I will try to inverse this by creating a singleton and seeing how that goes, but it would be preferable to have a built-in alternative bind that works as one would expect.
If there is any other solution to this I'm unaware of, please let me know.
