### ISSUE TITLE
TextEdit warp mode not working

### ISSUE THREAD

**Issue by Uniformbuffer3** [godotengine/godot#62902]
### Godot version

v4.0.alpha.custom_build [d26442e70]

### System information

Linux PopOS Intel HD Graphics 4600 on Mesa 22.0.1

### Issue description

Hi, while trying to implement a text box with multiple lines i have noticed that setting `warp_mode` to `Boundary` on a `TextEdit` node do not works correctly: it disables the bottom scroll bar, but the text after the boundary is not visible nor in a new line, seems it is simply clipped out. 

Seems the same problem also apply to `TextEdit` elements that are parts of the Godot editor, both when writing directly in the `TextEdit` box and when writing in the window generated after clicking on the "expand" button.

Thanks for listening and thanks for the hard work done to develop and maintain this marvelous engine.

### Steps to reproduce

Add a `TextEdit` node to a scene, set `warp_mode` to `Boundary` and try to write a long text inside.

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by bruvzg** [comment]
Seems to be working for me, can you provide a reproduction project?

https://user-images.githubusercontent.com/7645683/178266217-b305c8a4-866b-4411-a354-ba0b94e91814.mov

In any case, it's probably should be updated to make use of all wrap modes supported by the `TextServer`, not just `None`/`Boundary`.

**Comment by Uniformbuffer3** [comment]
Hi, i did some additional tests and look like i misinterpreted how the feature behave: it wrap on a new line words that are separated by spaces, while very long words are just clipped out. Unfortuantely that was exactly my case, so i didn't realize how it works.

I'm so sorry for the noise, i was using the feature wrong and it's my fault, so there is no bug to fix.
