### ISSUE TITLE
Label won't start scene with rect_scale as zero if child to containers

### ISSUE THREAD

**Issue by Vitorgus** [godotengine/godot#62904]
### Godot version

3.4.4

### System information

Windows 10

### Issue description

Whem working on a project, I wanted to keep a text hidden, to show it later when an event occurs. I had the following structure: `Node2D (root) > CanvasLayer > ColorRect > CenterContainer > Label`. To hide the label, I set the `rect_scale` property to `Vector2.ZERO` on the script's `_ready()` function, but when the sene plays, the label won't start hidden, and have the `rect_scale` set to the default value of `Vector2.ONE`.

If I try to set the scale to zero during the scene's execution, it works. The problem seem to be only at the start of the scene.

If I remove the `CenterContainer` and have the `Label` as a direct child of the `ColorRect`, it will start hidden with no problems.

### Steps to reproduce

- Create a new scene with Node2D as root
- Create the following node structure `CanvasLayer > ColorRect > CenterContainer > Label`
- Grab a font from google fonts just so you can increase the label's font size and see the text properly (optional)
- Set the label's text to anything you'd like, and color to black
- Create a `Button` node as a child to the root
- Attatch the following script to the root node
```gdscript
extends Node2D

onready var CenterLabel = $CanvasLayer/ColorRect/CenterContainer/Label

func _ready() -> void:
	CenterLabel.rect_scale = Vector2.ZERO


func _on_Button_pressed() -> void:
	CenterLabel.rect_scale = Vector2.ZERO
```
- Connect the button `pressed` signal to the script
- Run the scene, and the text will still be visible. Click the button, and the text dissapears.

### Minimal reproduction project

Minimal reproduction: [Label Bug Step By Step.zip](https://github.com/godotengine/godot/files/9080603/Label.Bug.Step.By.Step.zip)

I'm also attaching a test project that has a few other nodes as the label's parent to check if the problem was with the `CenterContainer` node:
- No parent, label as a direct child to ColorRect
- MarginContainer
- Container (the base node for the containers)
- HBox
- VBox
- PanelContainer
- ScrollContainer
- AspectRatioContainer

Only the 'no parent' and `Container` ones seem to hide the text at the start of the scene. All hide on button click.

[Label Tween Bug Tests.zip](https://github.com/godotengine/godot/files/9080604/Label.Tween.Bug.Tests.zip)

**Comment by timothyqiu** [comment]
This is how `Container` currently works. It'll update position/size/rotation/scale of its children when necessary.

A `Container` is not required if all you want is to keep the `Label` at center. You can set the label's anchors to 0.5, margins to 0.0, and grow directions to Both.

**Comment by KoBeWi** [comment]
In 4.0 the scale isn't even available for controls inside a Container, so the issue is irrelevant.

If you want to hide your Label, you can just change visibility to `false` (in CenterContainer it doesn't affect layout), or set modulate alpha to 0. Scaling to 0 isn't really a good way to hide something xd
