### ISSUE TITLE
EditorResourcePicker does not support custom types with base_type correctly

### ISSUE THREAD

**Issue by SekoiaTree** [godotengine/godot#62912]
### Godot version

3.4.4.stable

### System information

Pop!_OS 22.04

### Issue description

When setting base_type on an EditorResourcePicker to a custom type, it is impossible to set it to an instance of that type (or any subtypes) without creating it directly from there.
![image](https://user-images.githubusercontent.com/51149447/178281047-5e8c5462-68e4-4ad6-9ec7-2bc20b93e913.png)
The console is also repeatedly sent the following line:
```
 Cannot get class 'MyCustomType'.
 Cannot get class 'MyCustomType'.
 Cannot get class 'MyCustomType'.
 Cannot get class 'MyCustomType'.
 Cannot get class 'MyCustomType'.
 Cannot get class 'MyCustomType'.
 Cannot get class 'MyCustomType'.
 Cannot get class 'MyCustomType'.
 Cannot get class 'MyCustomType'.
 Cannot get class 'MyCustomType'.
 Cannot get class 'MyCustomType'.
 Cannot get class 'MyCustomType'.
 Cannot get class 'MyCustomType'.
 Cannot get class 'MyCustomType'.
 Cannot get class 'MyCustomType'.
 Cannot get class 'MyCustomType'.
 Cannot get class 'MyCustomType'.
 Cannot get class 'MyCustomType'.
 Cannot get class 'MyCustomType'.
 Cannot get class 'MyCustomType'.
 Cannot get class 'MyCustomType'.
 Cannot get class 'MyCustomType'.
 Cannot get class 'MyCustomType'.
 Cannot get class 'MyCustomType'.
 Cannot get class 'MyCustomType'.
 Cannot get class 'MyCustomType'.
 Cannot get class 'MyCustomType'.
 Cannot get class 'MyCustomType'.
 Cannot get class 'MyCustomType'.
 Cannot get class 'MyCustomType'.
 Cannot get class 'MyCustomType'.
 Cannot get class 'MyCustomType'.
```
(copy pasted all, if the count is relevant).
I tried to traceback the problem but couldn't find anything weird, I imagine it's to do with the Editor not having all the classes? idk. Calling get_allowed_types() works perfectly.

### Steps to reproduce

Create a custom resource type with a class_name, as well as an instance of that resource as a tres. Create an addon that sets the base_type of an EditorResourcePicker to the name of that custom resource type. Attempt to add the instance into that EditorResourcePicker.

### Minimal reproduction project

[EditorResourcePickerBug.zip](https://github.com/godotengine/godot/files/9084641/EditorResourcePickerBug.zip)

**Comment by Calinou** [comment]
This is likely caused by https://github.com/godotengine/godot/issues/21789.
