### ISSUE TITLE
New uniform variable system in shaders

### ISSUE THREAD

**Issue by Knand1861** [godotengine/godot#62924]
### Godot version

4.11 alpha

### System information

Windows 11

### Issue description

First: I could not figure out the way that I can specify both hint + default value and instance_index();

Second: If I declare a global uniform in the shader script, project crashes on next loading; WORKAROUND: deleting the declaration with notepad before launch and then retyping it again, once loaded. [they work fine during the session (yes, I added global in project settings)]

Third: Instance keyword makes hints disappear and makes GDscript helpless in controlling the value in any way [It defaults to 0, as for float] - delete instance keyword and it works again.

I thought, that stating all these three issues in one place is a way to simplify the process of discussion and fix, if anyone intends to.

### Steps to reproduce

shader:

```
shader_type canvas_item;
instance uniform float opacity :hint_range(0.0, 1.0, 0.1)=0.5;

void fragment(){
	vec4 color = texture(TEXTURE,UV);
	color.a-=opacity;
	COLOR = color;
}
```

sprite with an area2d and collisionshape:
```
extends Sprite2D


func _on_area_2d_area_entered(area):
	material.set_shader_param("opacity",1.0)
```

**Comment by Calinou** [comment]
> I thought, that stating all these three issues in one place is a way to simplify the process of discussion and fix, if anyone intends to.

This isn't actually how it works. You need to open one issue per bug, so that they can be tracked and fixed individually.

**Comment by Calinou** [comment]
Superseded by https://github.com/godotengine/godot/issues/62943.
