### ISSUE TITLE
PoolVector2Array: cannot initialize with array 

### ISSUE THREAD

**Issue by Voaz** [godotengine/godot#62927]
### Godot version

3.4.4

### System information

Manjaro Linux, Vulkan, AMD RADV NAVI14

### Issue description

documentation claims that PoolVector2Array has optional way to initialize with generic array.
please see constructor description https://docs.godotengine.org/en/stable/classes/class_poolvector2array.html?highlight=poolvector2array
I've tried several ways to initialize and draw a Line2D but nothing worked except appending Vector2s
here is what I tried (commented out are the variants which didn't work):
```
shape = [[0, 0], [100, 0], [100, 100], [0, 100]]
func draw_shape(shape):
	var l = Line2D.new()
	l.width = 10
	l.points = make_pool_vector(shape)

#	l.points = PoolVector2Array(shape)
#      l.points = PoolVector2Array([[0, 0], [100, 0], [100, 100], [0, 100]])
#	l.points = PoolVector2Array([0, 0, 100, 0, 100, 100, 0, 100])

	add_child(l)

func make_pool_vector(data) -> PoolVector2Array:
	var pv: PoolVector2Array
	for i in data:
		pv.append(Vector2(i[0],i[1]))
	return pv
```

### Steps to reproduce

in the description

**Comment by just-like-that** [comment]
That should work:
PoolVector2Array([Vector2(0, 0)])
You need your coords wrapped in Vector2/3 values.

See also following discussion:
[alternative vector type notation](https://github.com/godotengine/godot-proposals/issues/3719)
