### ISSUE TITLE
InputEventJoypadMotion will trigger multiples on_value_changed with hslider

### ISSUE THREAD

**Issue by Levrault** [godotengine/godot#62932]
### Godot version

3.4.4 (and 3.3.4, 3.5-rc6)

### System information

Windows 10

### Issue description

Hi all, 
If you map `ui_left `and `ui_left` with the left joystick of a controller (xbox one in this case), when using a hslider, the on changed value event will be trigged multiples times. 

![image](https://user-images.githubusercontent.com/1162446/178392628-b6b1ceb7-fd87-472e-bc6c-8381ff1dd071.png)

e.g. a hslider with a step of 5%, with the stick, the value increase randomly from 10% to 20%, while using the direction cross will only trigger a 5% step.

https://user-images.githubusercontent.com/1162446/178392471-b41b5954-1482-45d8-adf1-8ad2027e1635.mp4

I think InputEventJoypadMotion should only be trigger once to match industry standard.

If this isn't a duplicate, I would be interested to take a look and create a PR if this is a good "first issue".

Thanks

### Steps to reproduce

1 - Create a minimal project with a hslider
2 - Remap ui_left, ui_right to the left joystick
![image](https://user-images.githubusercontent.com/1162446/178392854-69af922a-49bc-47cf-b76c-6a6080380268.png)
3 - Create a hslider
4 - Change the value with the joystick

### Minimal reproduction project

[hslider_issue.zip](https://github.com/godotengine/godot/files/9088786/hslider_issue.zip)

**Comment by gotnospirit** [comment]
Reproduced with a XBox One controller via USB on 3.x custom build. Doesn't seem like a "controller drift" problem

**Comment by gotnospirit** [comment]
Up-to-date one, last commit in log is 3f02013

**Comment by Levrault** [comment]
@Calinou hi, I wrote the wrong version (I tested both on 3.3.4 and 3.4.4), same behaviour on both version

**Comment by gotnospirit** [comment]
Same with 4.0 alpha 10.

I think the problem isn't with the code for controller but how the slider reacts to stick's inputs.
If you push the stick to left/right and do not release, the slider will stop at some position (may have moved more than once), but sometimes when you release it, it will move again in the same direction.

So in this case, I think the desirable behaviour should be to detect delta is the same direction as previously received one, and therefore the slider should not react to it, and when inside the deadzone, consider it as released.

**Comment by Levrault** [comment]
Could it be related to _gui_input? I remembered creating a custom carousel field. All action where trigged inside the _gui_input. But when using an analog stick, both action_pressed were trigger (both when using and released), resulting in a quite fast navigation

https://user-images.githubusercontent.com/1162446/178615774-71f480de-c82c-4b0f-8bb6-f9cf6058299f.mp4

```
func _gui_input(event: InputEvent) -> void:
	if event.is_action_pressed("ui_left"):
		_on_Previous_value()
		return

	if event.is_action_pressed("ui_right"):
		_on_Next_value()
		return
```

I fixed it by checking the raw strengh


```
func _gui_input(event: InputEvent) -> void:
	if event is InputEventJoypadMotion:
		if event.get_action_strength("ui_left") == 1:
			_on_Previous_value()
			return
		if event.get_action_strength("ui_right") == 1:
			_on_Next_value()
			return
		return
	
	if event.is_action_pressed("ui_left"):
		_on_Previous_value()
		return

	if event.is_action_pressed("ui_right"):
		_on_Next_value()
		return
```

https://user-images.githubusercontent.com/1162446/178615791-a9acd41c-6356-42d0-896b-dbc2c6129d6b.mp4

I saw the same behavior in `slider.cpp`

```
void Slider::_gui_input(Ref<InputEvent> p_event) {
	if (!editable) {
		return;
	}
	...
	if (!mm.is_valid() && !mb.is_valid()) {
		if (p_event->is_action_pressed("ui_left", true)) {
			if (orientation != HORIZONTAL) {
				return;
			}
			set_value(get_value() - (custom_step >= 0 ? custom_step : get_step()));
			accept_event();
		} else if (p_event->is_action_pressed("ui_right", true)) {
			if (orientation != HORIZONTAL) {
				return;
			}
			set_value(get_value() + (custom_step >= 0 ? custom_step : get_step()));
			accept_event();
		} else if (p_event->is_action_pressed("ui_up", true)) {
			if (orientation != VERTICAL) {
				return;
			}

			set_value(get_value() + (custom_step >= 0 ? custom_step : get_step()));
			accept_event();
		} else if (p_event->is_action_pressed("ui_down", true)) {
			if (orientation != VERTICAL) {
				return;
			}
			set_value(get_value() - (custom_step >= 0 ? custom_step : get_step()));
			accept_event();
		} else if (p_event->is_action("ui_home") && p_event->is_pressed()) {
			set_value(get_min());
			accept_event();
		} else if (p_event->is_action("ui_end") && p_event->is_pressed()) {
			set_value(get_max());
			accept_event();
		}
	}

```

Should we add someking of exception to check when an event input is of type `InputEventJoypadMotion ` ?

**Comment by Calinou** [comment]
Slider inputs will likely need special handling to behave well with InputEventJoypadMotion. They should not be ignored – otherwise, you would only be able to use the D-pad to move a slider (which is poor UX).

**Comment by Levrault** [comment]
I poorly express myself, I mean by exception, directly handling `InputEventJoypadMotion` as their own type on action inside the slider. Instead of behing managed by `p_event->is_action_pressed("ui_up", true)` should we check the `get_action_strength` when we handle a  `InputEventJoypadMotion`.

I not really familiar with the basecode so maybe there is a better solution to fix this behavior.

**Comment by gotnospirit** [comment]
Maybe it's a bit too much but, what about introducing an _InputEvent::is_action_held_ method with a delay parameter?
And then, gui components could optionally switch between _is_action_pressed_ and _is_action_held_

**Comment by Levrault** [comment]
I did a first quickfix based on what has been done in `Viewport.cpp`. Seems to work fine but I need to test further before creating a PR. 

I would also like to improve the whole behavior, but I'm not sure if I should do it right now or create a proposal (Could @Calinou help my on this one, thanks) ?
- If we quickly move the axis to the left or right, it should only increment by one step
- If we held the stick to the left or right, it should increment the step until we unheld the stick (could be easier for user with motion issue)

**Comment by Calinou** [comment]
> I would also like to improve the whole behavior, but I'm not sure if I should do it right now or create a proposal

It's probably a good idea to create a proposal for this.

Ideally, sliders should behave like this with both keyboard and gamepad input. Thanks to the operating system, keyboards will automatically provide echo events, but gamepads don't, so this behavior needs to be manually implemented for gamepad input. I suggest using a delay of 0.5 seconds and a repeat rate of 20 repeats/second, similar to Windows' default rate for repeating keyboard input.

https://user-images.githubusercontent.com/180032/179607471-058e2611-76dd-48ea-a858-2726d9132ed0.mp4

**Comment by BlooRabbit** [comment]
Hello, it would be great to have an is_echo() function for gamepads, which would avoid this issue. Reproducing this in GDscript with timers in each interface code is feasible but generates a lot of unnecessary code.  This solution would enable gamedevs to use the function when needed (UI) and leave it be when not needed (gameplay).

**Comment by Calinou** [comment]
> Hello, it would be great to have an is_echo() function for gamepads, which would avoid this issue. 

Gamepads never send echo inputs, so `is_echo()` would be invalid.

Instead, we should look into properly handling analog stick UI inputs out of the box. This is entirely feasible but requires manually implementing echo inputs in certain UI nodes (such as Slider and SpinBox).

**Comment by Levrault** [comment]
I tried and add the same behavior to every node (slider, popup menu, item list, tree etc) but it seems more like a workaround (it is also my first PR so my lack of experience in c++ and Godot source code could be the real issue). 

Even if a gamepad doesn't have an echo, could we implement a behavior inside Input to re-trigger an event. maybe for an UI exclusive mode? 

Or we could list witch component to prioritize like the slider and popup menu and add the echoing

**Comment by BlooRabbit** [comment]
I understand that "Gamepads never send echo inputs, so is_echo() would be invalid" -> my point is that as a gamedev I need an is_echo() function (or equivalent) for gamepads in order to avoid detect input signals in certain situations (mainly UI). I can reproduce it with a timer in GDscript but it is tedious and ridiculous to reproduce for every game UI. Currently porting an interface game to Switch, I realize how important this is and if Godot is to be used for console games, this issue is a real problem.
