### ISSUE TITLE
Compilation Error (Windows)

### ISSUE THREAD

**Issue by PixelWizzard** [godotengine/godot#6293]
The compilation process went fine, until stream_peer.cpp

`e:\godot-binaries\godot-master\core\io\stream_peer.cpp(495) : warning C4715: "StreamPeerBuffer::get_partial_data": Not all control elements returned a value.
e:\godot-binaries\godot-master\core\io\stream_peer.cpp(547) : error C4716: "StreamPeerBuffer::duplicate": Must return a value
scons: *** [core\io\stream_peer.windows.tools.32.obj] Error 2
scons: building terminated because of errors.`

**Comment by akien-mga** [comment]
Fixed by #6239.
