### ISSUE TITLE
Instance uniforms are not implemented for 2D shaders

### ISSUE THREAD

**Issue by Knand1861** [godotengine/godot#62943]
### Godot version

4.11 alpha

### System information

Windows 11

### Issue description

Instance keyword makes hints disappear and makes GDscript helpless in controlling the value in any way [It defaults to 0, as for float]; 
Delete instance keyword, and it works again.

![Untitled](https://user-images.githubusercontent.com/53999633/178458919-3932b888-dfba-4533-9c26-314ba5549ddf.png)

### Steps to reproduce

shader:
```
shader_type canvas_item;
instance uniform float opacity :hint_range(0.0, 1.0, 0.1)=0.5;

void fragment(){
	vec4 color = texture(TEXTURE,UV);
	color.a-=opacity;
	COLOR = color;
}
```
sprite with an area2d and collisionshape:
```
extends Sprite2D


func _on_area_2d_area_entered(area):
	material.set_shader_param("opacity",1.0)
```

**Comment by Calinou** [comment]
I guess this is because the editor isn't aware of per-instance uniforms. These were likely designed to be changed via code first and foremost.

**Comment by KoBeWi** [comment]
I tried :<
https://github.com/KoBeWi/godot/commit/9220e5eb8844a723e9a40c06164feadef80c5e9a
The uniforms show up in the inspector, but in a wrong place and editing them has no effect. Also the implementation is trash. But maybe it will be useful as a starting point for someone.

**Comment by riazey** [comment]
This is still a major issue in the beta, I noticed it wasn't included in the 4.0 roadmap was it decided that having this new shader feature be unavailable for 2D in the full 4.0 release? 

I might be blind so just double checking cuz I was super looking forward to it for my color pallette swapping xD

**Comment by Calinou** [comment]
> I noticed it wasn't included in the 4.0 roadmap was it decided that having this new shader feature be unavailable for 2D in the full 4.0 release?

We don't know whether this feature will be added in time for 4.0. It all depends on a motivated contributor being able to implement this :slightly_smiling_face:

**Comment by Praytic** [comment]
What is the workaround for instance uniforms for `canvas_item` shaders? We have like 600 instances of duplicated shader code...

**Comment by Anixias** [comment]
> What is the workaround for instance uniforms for `canvas_item` shaders? We have like 600 instances of duplicated shader code...

The current workaround is to add this:
```glsl
varying vec4 MODULATE;

void vertex()
{
    MODULATE = COLOR;
}
```

Then you can access `MODULATE` in the fragment shader.
