### ISSUE TITLE
GDScript 2.0: Unusual autocomplete "new(" inside member variable

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot#62945]
### Godot version

v4.0.alpha.custom_build [d26442e70]

### System information

Arch on 5.18.10-arch1-1 

### Issue description

weird autocomplete

### Steps to reproduce

Type at the top of a script:

```gdscript
var x = ""
```

And hit enter on the first autocomplete:

![image](https://user-images.githubusercontent.com/14253836/178544476-fc0c78a8-424f-4ec3-a1c8-40e4bd2a69b8.png)
![image](https://user-images.githubusercontent.com/14253836/178544496-3a711388-62f8-4346-b83c-a44d291825e4.png)

same thing happens with 

`var x = [""]`
`var x = $`

**Comment by cdemirer** [comment]
It's not just arrays:
```gdscript
var x = "
```
```gdscript
var x = $
```

**Comment by dalexeev** [comment]
The bug is still present in master. Postponed to 4.x because this is a usability issue, not a critical bug and #78288 already has a 4.x milestone.
