### ISSUE TITLE
Code folding doesn't fold comment lines at the end of an indented section

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#62944]
### Godot version

v3.5.rc6.official [f05cecdc4]

### System information

win10 64

### Issue description

The method collapse does not cover all the code belonging to the method.
In this gif there is a method in which its last line is commented, when the method collapses this line is out of range.

![Captura2 gif](https://user-images.githubusercontent.com/19652075/178456644-28c5b2ef-a551-442c-8f0a-63ca4bbb1f37.gif)

### Steps to reproduce

Add a line of code to a method, for example "return".
Add a commented line of code.
Collapse the method.

### Minimal reproduction project

...

**Comment by akien-mga** [comment]
Fixed by #63113.
