### ISSUE TITLE
Vulkan: Normal buffer view broken when using MSAA on NVIDIA GPUs

### ISSUE THREAD

**Issue by WrobotGames** [godotengine/godot#62955]
### Godot version

v4.0.alpha11.official [afdae67cc]

### System information

Windows 11, Vulkan Desktop, GTX1060 with 516.59 studio drivers

### Issue description

Normal buffer view breaks when enabling MSAA. 

Images:
_Normal buffer without MSAA_ 
![image](https://user-images.githubusercontent.com/66079814/178523962-36e91654-38a5-4a23-b409-1ebf50923b05.png)
_Normal buffer with 2x MSAA_
![image](https://user-images.githubusercontent.com/66079814/178524116-cea58a29-a9db-4617-83b3-68dbaeb03ca8.png)

### Steps to reproduce

1. Add any mesh to 3D scene
2. Check normal buffer (Click perspective -> Display advanced -> normal buffer)
3. Enable MSAA (2x, 4x or 8x doesn't matter)
4. Check normal buffer

**Comment by WrobotGames** [comment]
Closed issue, problem is gone in (not specifically) Godot 4.0 beta 16.

**Comment by WrobotGames** [comment]
The issue still persists, but only on NVIDIA cards. Since I opened this issue I have switched to AMD, so this should have been closed.

**Comment by Calinou** [comment]
I can confirm this on 4.0.rc 493e932c8 (Linux, GeForce RTX 4090 with NVIDIA 525.85.05):

No MSAA | 2× MSAA | 2× MSAA (second try) | 4× MSAA | 8× MSAA
-|-|-|-|-
![Screenshot_20230211_172830](https://user-images.githubusercontent.com/180032/218269857-ac19cca8-06f7-47fd-adbb-e83664d69458.png) | ![Screenshot_20230211_172836](https://user-images.githubusercontent.com/180032/218269859-17e28bb9-de3f-4853-9193-b14ea033c293.png) | ![Screenshot_20230211_172855](https://user-images.githubusercontent.com/180032/218269864-d792c912-3861-4f0c-9955-a5efd81eb2b1.png) | ![Screenshot_20230211_172840](https://user-images.githubusercontent.com/180032/218269860-1ae6dede-9176-41e0-8715-3da72aec4c5f.png) | ![Screenshot_20230211_172844](https://user-images.githubusercontent.com/180032/218269862-01015bf2-1ef6-474b-bab2-0402c805d7f3.png)
