### ISSUE TITLE
GDScript Variable Inheritance

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#6295]
**Operating system or device - Godot version:** 2.1

**Issue description** (what happened, and what was expected):
I am horrible at explaining things so I made this picture. I think re-referencing the variable is kind of "bland", (I mean, it works), but when I have 10 or so plus variables things kind of get out of hand. And I wish I could just inherit the variables from a node and use them without using the `.variable` notation to reference. For example:
![1234](https://cloud.githubusercontent.com/assets/10387670/18022222/eb345266-6ba1-11e6-8903-1cad3d99642e.png)

We can use a keyword `inherit` and then give it a parameter to the node we want to inherit the variables from.  This would ofcourse be an optional feature, but yeah

**Comment by Zylann** [comment]
Inheriting from an instance? Why? How?
Inheritance doesn't works that way. I also don't like this, because it makes variables come from multiple scopes. Also, what is going to happen if the "inherited" node is destroyed while the game is running? What if you change its type?
I find the `.variable` notation a lot cleaner, because you know where it comes from. I don't know of any language doing that, or maybe Lua with metatable tricks (thought I think you can do something similar with `_get` in GDScript already?)

**Comment by vnen** [comment]
The concept itself is not unprecedented, it seems the same as [Visual Basic's `With` statement](https://msdn.microsoft.com/en-us/library/wc500chb.aspx). Here's a sample so you can get the feel:

```VB
Private Sub AddCustomer()
    Dim theCustomer As New Customer

    With theCustomer
        .Name = "Coho Vineyard"
        .URL = "http://www.cohovineyard.com/"
        .City = "Redmond"
    End With

    With theCustomer.Comments
        .Add("First comment.")
        .Add("Second comment.")
    End With
End Sub

Public Class Customer
    Public Property Name As String
    Public Property City As String
    Public Property URL As String

    Public Property Comments As New List(Of String)
End Class
```

The proposal itself is not good though. This thing should be scoped to a small region and not defined globally in the file. Also, you're using `get_node()`, which will only work when the node is on the tree, it can't be called too soon or too late, so when will it be? Not to mention you're adding new scopes to the script, which means new lookups and hence will decrease performance.

With something like VB does it, I'd be more keen to accept.

**Comment by Zylann** [comment]
I also prefer the `with`, because it's more predictable. Note, it can be achieved already by the use of fluent interfaces https://en.wikipedia.org/wiki/Fluent_interface
