### ISSUE TITLE
Tree node - "Selected" and "Selected Focus" highlights are rendered on top of TreeItem's buttons

### ISSUE THREAD

**Issue by andreswx** [godotengine/godot#62951]
### Godot version

4.0 alpha11

### System information

Macbook Air M1 2020

### Issue description

When Tree node's "Select mode" is set to "Row", both "Selected" and "Selected Focus" highlights are rendered on top of TreeItem's buttons.
If "Selected Focus" is overridden with StyleBoxFlat using a solid color, the buttons will not be visible, but will still be there and can be clicked.
The buttons should be rendered on top.

Also, when Tree node's "Select mode" is set to "Row", when a TreeItem is selected, both the row and the TreeItem's "middle part" highlight are rendered. The middle part is highlighted twice.
In this "Select mode", Only the row should be highlighted.

![Screen Shot 2022-07-12 at 10 42 52](https://user-images.githubusercontent.com/4397516/178504549-8f3dd844-2baa-401d-a8b2-a05510e42ce2.png)

### Steps to reproduce

The minimal reproduction project has two trees. Selecting an item on each tree will show that the problem happens with both the "Selected" and "Selected Focus" highlights.

Both item's buttons are bellow the highlights. The "Selected Focus" style override on one of the trees can be changed to a solid color to verify that the buttons on that tree will no longer be visible when the item is selected.

### Minimal reproduction project

[tree-bug-test.zip](https://github.com/godotengine/godot/files/9096070/tree-bug-test.zip)

**Comment by Calinou** [comment]
The minimal reproduction project didn't upload (likely because you clicked away from the text field while it was still uploading). Try editing your post and upload it again.

**Comment by andreswx** [comment]
Sorry, I didn't notice that. I uploaded it again.

**Comment by MGilleronFJ** [comment]
Is this the same issue? Just selecting one row:
![image](https://user-images.githubusercontent.com/105369548/190161068-35e9453a-5a20-4080-9c12-aecd09bc8c4f.png)

In Godot 3.5.

**Comment by YeldhamDev** [comment]
@MGilleronFJ No, change `select_mode` to `SELECT_ROW` if you want for only one row to be selected.
