### ISSUE TITLE
Extreme Android slowdown when copying files with scoped storage 

### ISSUE THREAD

**Issue by ondesic** [godotengine/godot#62969]
### Godot version

3.5 rc6

### System information

Windows 11

### Issue description

If I copy a file over to the "user://" directory, it takes 65 milliseconds.
However, If I allow permission to **Manage_External_Storage**, **Read_External_Storage** and **Write_External_Stoage** I can copy a file to a new directory int the Documents folder...yet, doing so takes over 5000 milliseconds!

Though this slowdown may also occur with other instances of trying to use a file in storage, this extreme slowdown for sure occurs with file copying.  

### Steps to reproduce

Take turns commenting out line 21 and 22.  One uses the "user://" directory, the other uses the phone's regular storage.
Make sure each time you install it, you allow and accept the two permissions, **then close and run again** to see effects.

### Minimal reproduction project

I usually use C#, but made it in GDScript to speed up the testing.
[Storage.zip](https://github.com/godotengine/godot/files/9097956/Storage.zip)

**Comment by Calinou** [comment]
cc @m4gr3d

**Comment by m4gr3d** [comment]
@ondesic Do you have a reference for the time it takes to perform a copy on versions of the release candidate prior to the scoped storage inclusion (or on the current stable version)?

**Comment by ondesic** [comment]
@m4gr3d  I don't have an exact number but before the inclusion the app started as fast as the the "user://" version did.  I would say close to 65.

**Comment by m4gr3d** [comment]
@ondesic Thanks for uncovering the issue and providing an easy repro project!
This was key in helping me quickly track the regression.

Don't hesitate to open other issues if you encounter further regressions.

**Comment by ondesic** [comment]
@m4gr3d Oh no.  More Scoped Storage bugs.  Using the same project, **uncomment** the button code.  Now, once again take turns commenting out line 21 and 22. One uses the "user://" directory, the other uses the phone's regular storage.
Make sure each time you install it, you allow and accept the two permissions, then close and run again to see effects.

Press the button and watch how long it takes to execute the simple file code.  With the "user://" directory the code runs as fast as the desktop.  With Scoped Storage it takes over 5 sec.

PS.  I can open a new issue if you would like.

**Comment by madmiraal** [comment]
@ondesic, Have you tested it with #63242? If it's not fixed with #63242, then yes, you should open a new issue.

**Comment by ondesic** [comment]
@madmiraal I'm sorry, i don't know how to test this.  Is there some code i need to use before trying to access a file in storage?  
All I know is that with the latest 3.5 rc7, if I try to access a file in scoped storage, it bogs down the app to a crawl.  Copy Dir had been fixed though.

**Comment by madmiraal** [comment]
@ondesic, @akien-mga should be able to confirm, but as far as I know, #63242 was included in RC7. So, yes I'd open a new issue.
