### ISSUE TITLE
Condition 'det==0' is true

### ISSUE THREAD

**Issue by Remixful** [godotengine/godot#6296]
**Operating system or device - Godot version:**
Windows 10 - v2.1.stable.official on Steam

**Issue description**:
Debug errors with set_transform and scaling to Vector2(0,0). This is most likely a very minor issue, but it won't hurt to still report this issue. I'd also like to include that I crashed once already after debugging the project.

**Steps to reproduce:**
Create a 2D Sprite node and add a Button child node. 
In the _ready() function:
`set_transform(Matrix32(get_transform().scaled(Vector2(0,0))))`

![image](https://cloud.githubusercontent.com/assets/8620268/18026091/777a0f8c-6c0a-11e6-8fd0-b973d78d9d71.png)

**Comment by mateka** [comment]
I have added simple check in viewport. But maybe there should be some checks in nodes, which hides node when its new transform makes it hidden?

**Comment by akien-mga** [comment]
Fixed by #6743.
