### ISSUE TITLE
OptionButtons popup is off if triggered through code for the first time

### ISSUE THREAD

**Issue by Pacifist-Penguin** [godotengine/godot#62960]
### Godot version

4.0.alpha11.official [afdae67cc]

### System information

macOS catalina 10.15.7

### Issue description

That's how it looks like if you open it with a hotkey for the first time:
![image](https://user-images.githubusercontent.com/75931217/178547570-bc4343d0-5168-45cc-a494-4fe328d074d6.png)

That's how it looks like if you click on it / open it with ui_accept for the first time (doesen't matter if subsequent times you open it with code)
![image](https://user-images.githubusercontent.com/75931217/178549880-77784ae2-271f-4efb-8da5-1ba7de74f1b5.png)

That's how code looks like:
```gdscript
extends OptionButton

@onready var popup = self.get_popup()

# it doesn't matter if the node is actually focused, but it's here to check how it works with ui_accept
func _ready():
	self.grab_focus()

func _unhandled_input(event):
	if event.is_action_pressed("ui_open_option_button_popup"):
		popup.visible = not popup.visible
```

### Steps to reproduce

1. Open minimal reproduction project.
2. Don't touch anything and just press shift

### Minimal reproduction project

[OptionButtonBug.zip](https://github.com/godotengine/godot/files/9095368/OptionButtonBug.zip)

**Comment by Sauermann** [comment]
Please use [`show_popup()`](https://docs.godotengine.org/en/latest/classes/class_optionbutton.html#class-optionbutton-method-show-popup) for opening the popup. This is the dedicated function for your use-case.

`popup.visible = not popup.visible` in your MRP works as expected. It just makes the popup visible at the location where it currently is, so I believe, there is no problematic behavior here.

**Comment by Pacifist-Penguin** [comment]
> Please use [`show_popup()`](https://docs.godotengine.org/en/latest/classes/class_optionbutton.html#class-optionbutton-method-show-popup) for opening the popup. This is the dedicated function for your use-case.
> 
> `popup.visible = not popup.visible` in your MRP works as expected. It just makes the popup visible at the location where it currently is, so I believe, there is no problematic behavior here.

Hi.
It seems that this method didn't exist in afdae67. Anyway, this problem was solved by [this PR](https://github.com/godotengine/godot/pull/66748)
Thanks!
