### ISSUE TITLE
CanvasModulate node doesn't affect Sprite2D with "add" blend mode.

### ISSUE THREAD

**Issue by magpie514** [godotengine/godot#6297]
**Operating system or device - Godot version:**
Ubuntu Linux 16.04 64b, godot version d015d93

**Issue description** (what happened, and what was expected):
I just found that CanvasModulate now affects only child nodes unlike before, which is incredibly convenient, but it doesn't seem to alter Sprite2D whose blend mode is set to Add.
![snapshot12](https://cloud.githubusercontent.com/assets/323651/18026440/9f79ca4a-6c46-11e6-96a1-579b722881ca.png)
While I can see many reasons to keep alpha-blended effects from inheriting the modulation (to darken the background but keep the lights shiny), this is slightly inconvenient as seen in the example screenshot, which is trying to fade the entire background. Perhaps some toggle could be added to allow both things?

**Steps to reproduce:**
Add a Sprite2D with blend mode set to "Add" somewhere as a children of CanvasModulate, then change color of CanvasModulate.

**Comment by Calinou** [comment]
I can confirm this still occurs as of commit https://github.com/godotengine/godot/commit/584ca0f156cec64c259382895e105cf27566a987. This occurs with any blend mode other than **Mix**, and will also occur if the light mode is set to **Unshaded** (although that part might be intended).

**Demo project:** [canvasmodulate_add.zip](https://github.com/godotengine/godot/files/3390235/canvasmodulate_add.zip)

The image below is a scene with a red CanvasModulate node, a Sprite with the **Mix** blend mode to the left and a Sprite with the **Add** blend mode to the right:

![Comparison](https://user-images.githubusercontent.com/180032/61186894-fb0a2100-a66a-11e9-9e71-a3e7512a607e.png)

**Comment by TheSofox** [comment]
On v3.5.3.stable.official [6c814135b] the problem still seems to be there:
![image](https://github.com/godotengine/godot/assets/3089525/3191af9d-0713-467a-b3b2-a7b8b217021e)

But the latest version v4.3.dev.custom_build [655e93d58] seems to have been fixed:
![image](https://github.com/godotengine/godot/assets/3089525/7f4fde90-b466-4e4c-b3ae-ceb0962b037f)
