### ISSUE TITLE
Android Runnable icon doesn't show up anymore

### ISSUE THREAD

**Issue by Sosasees** [godotengine/godot#62971]
### Godot version

3.4 stable, 3.5 RCs 5–8

### System information

PC: Linux | Phone: Samsung Android 11 / Samsung Android 12

### Issue description

(i tested on an Sammsung Android 11 phone and a Samsung Android 12 tablet.
in this issue, i use the word 'Phone' interchangeable for 'Phone' and 'Tablet'.)

Godot used to show the Android icon next to the Play icon
when i had an Android phone with USB Debugging enabled
plugged into the computer
and the Godot project had an Android export template set to Runnable.

Now the icon doesn't appear anymore.
Maybe the USB Debugging authorisation is missing,
but i never saw the Accept/Decline dialog again.

The only way to test an app is to export it from the Export menu and then run ``adb install <apk-filename>`` in the terminal, which is just 2 more steps
but tedious because i have to do it often.
when i went to export from the Terminal for the first time in a while, the Accept/Decline dialog Did show up on my phone.

### Steps to reproduce

1. add an Android export template in the dialog from the _Project > Export..._ menu option
2. it's automatically set as Runnable
3. close the Export dialog in Godot
4. enable USB debugging on your Android device
5. plug the Android device into your computer
6. look for the Android icon next to the Play icon.
   notice how it doesn't show up.

### Minimal reproduction project

[A minimal project with the Android export template](https://github.com/godotengine/godot/files/9100102/android-export-test.zip).
It lets you skip steps 1 to 3 from "Steps to reproduce".

**Comment by Calinou** [comment]
Follow the [Troubleshooting section of One-click deploy](https://docs.godotengine.org/en/latest/tutorials/export/one-click_deploy.html#troubleshooting) in the documentation.

**Comment by madmiraal** [comment]
I can confirm that it works for me; so this is not a bug in Godot.

If you can build for Android and your device shows up in `adb devices` then the only reason the runnable icon won't show is if it cannot find `adb`. It looks for `adb` in the `platform-tools` folder of the SDK folder configured in `export/android/android_sdk_path` in the Editor Settings.

**Comment by Sosasees** [comment]
what should i set editor setting ``export/android/android_sdk_path`` to?
i have set it to ``~/.android/sdk``

**Comment by madmiraal** [comment]
> what should i set editor setting export/android/android_sdk_path to?
i have set it to /home/poppy/.android/sdk

This is probably wrong. You should follow the instructions in the documentation: https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_android.html

If you've installed Android Studio, and used the default location, it will probably be `/home/poppy/Android/Sdk`, then you need to ensure you've also installed the Platform Tools and confirm that `adb` is in `/home/poppy/Android/Sdk/platform-tools`.

If you need more help please use one of the Godot community forums: https://godotengine.org/community. Github Issues are for tracking Godot bugs, which this is not.

**Comment by Sosasees** [comment]
fixed in Godot 4

**Comment by RadixSeven** [comment]
In Godot 4.0.3, look for the remote debug icon (a monitor with a "play" triangle inside) rather than the "Android" icon.

I spent several hours looking for the Android icon and going through many reboots and resettings of `adb` (which worked fine from the command line).

**Comment by Sosasees** [comment]
@RadixSeven thank you, but i already know this.
if i didn't, i could not debug on Android and confirm that the issue is fixed
