### ISSUE TITLE
WebSocketPeer::get_current_outbound_buffered_amount()  does not return the correct value

### ISSUE THREAD

**Issue by merlinmanthey** [godotengine/godot#62991]
### Godot version

3.4.4-stable

### System information

Ubuntu 22.04

### Issue description

The function 

WebSocketPeer::get_current_outbound_buffered_amount()

does not return the proper value. It is always returning 0. 

I have debugged the godot engine code and I think I have found the issue, but unfortunately I do not know how to fix it.
Going down the call stack I can state the following:
- WebSocketPeer::get_current_outbound_buffered_amount()   itself does return the correct value
- variant_call.cpp (1194) does still have the correct return value, but as "r_ret" is nullptr, the value is lost here
`	if (r_error.error == Variant::CallError::CALL_OK && r_ret) {
		*r_ret = ret;
	}`

- in gdscript_function.cpp (1046) the boolean "call_ret" is false, and therefore the the argument r_ret is set to nullptr
 ```
       if (call_ret) {
	        GET_VARIANT_PTR(ret, argc);
	        base->call_ptr(*methodname, (const Variant **)argptrs, argc, ret, err);
       } else {
	        base->call_ptr(*methodname, (const Variant **)argptrs, argc, nullptr, err);
       }
```
- The value of "call_ret" is set in gdscript_function.cpp (1018)
`			bool call_ret = _code_ptr[ip] == OPCODE_CALL_RETURN;`

Seems the OPCODE for the function call is wrong. I'd like to provide a patch to fix this issue, but I have no Idea where to start, any hints ?

**Background:**
I'm developing an application where the clients have to send several MB of data to the server when connected. The data is sliced in packets (each ~60kb) and one packet is sent every game-loop iteration.
To have some form of rate-control, I'd like to have the value of  get_current_outbound_buffered_amount() to decide if the client should send more data now or postpone to a later iteration. 
If I send too much data i'm getting the following error:

`ERROR: Condition "_out_buf_size && (wslay_event_get_queued_msg_length(_data->ctx) + p_buffer_size >= (1ULL << _out_buf_size))" is true. Returned: ERR_OUT_OF_MEMORY`

"too much data" is a very variable term as it seems strongly dependent on the network connection. 

### Steps to reproduce

- create a WebSocketClient
- connect to a WebSocketServer
- get a WebsSocketPeer to the server (id 1)
- call get_current_outbound_buffered_amount()

var websocket_peer:WebSocketPeer = get_tree().network_peer.get_peer(1)
var outbound_packets = websocket_peer.get_current_outbound_buffered_amount()

break at wsl_peer.cpp (289) and climb down the call stack

**Comment by Calinou** [comment]
@merlinmanthey Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by merlinmanthey** [comment]
I am not able to provide a minimal reproduction project at the moment. I'll re-open the ticket when i have one
