### ISSUE TITLE
When calling a static function from an inherited script, subcalls are not dispatched to the inheriting script's functions

### ISSUE THREAD

**Issue by BimDav** [godotengine/godot#62998]
### Godot version

3.4.4-stable, 4.0 alpha 11

### System information

Windows 10

### Issue description

In parent.gd:
```
extends Node
static func get_number() -> int:
    return 0

static func get_next_number() -> int:
    return get_number() + 1
```

In child.gd:
```
extends "res://parent.gd"
static func get_number() -> int:
    return 1
```
Calling `load("res://child.gd").get_next_number()` returns 1, while it should return 2.

Following the calls in a c++ debugger, it seems that when we are inside the parent's `get_next_number()`, all information about child is lost.

### Steps to reproduce

Run the provided sample project

### Minimal reproduction project

[test_static_inheritance.zip](https://github.com/godotengine/godot/files/9112707/test_static_inheritance.zip)

**Comment by shrubbgames** [comment]
I just ran into this in 4.2.1 as well.

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/72973

This has more details and some commentary

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened
