### ISSUE TITLE
Visual Scripting - Game crash after close

### ISSUE THREAD

**Issue by mefihl** [godotengine/godot#6299]
**Operating system or device - Godot version:**
Windows 10, Godot https://github.com/godotengine/godot/commit/d015d93b8f94f55b26f874781ac7fd0a53e68227

**Issue description** (what happened, and what was expected):
Always after close game with running  scene with code create with Visual Scripting, game crash. After debugging in Visual Studio:
`Exception thrown: write access violation.
ringptr->prev was 0x1.
If there is a handler for this exception, the program may be safely continued.`

line 299 
`ringptr->prev->next = ringptr->next;`
in function `void MemoryPoolStaticMalloc::_free(void *p_ptr)` in file "memory_pool_static_malloc.cpp".

**Comment by Chaosus** [comment]
Closed as not detected in the current master.
