### ISSUE TITLE
Player's "CharacterBody3D" doesn't rotate with Platforms

### ISSUE THREAD

**Issue by Corruptinator** [godotengine/godot#63004]
### Godot version

v4.0.alpha11.official [afdae67cc] (Alpha Unstable Build)

### System information

Windows10 64bit, Vulkan, RTX 2080 Super

### Issue description

I noticed that the Player's CharacterBody3D is not rotating along with platforms that are also CharacterBody3D. In the (In-Progress) Documentation, it says:

`Moves the body based on velocity. If the body collides with another, it will slide along the other body rather than stop immediately. If the other body is a CharacterBody3D or RigidDynamicBody3D, it will also be affected by the motion of the other body. You can use this to make moving and rotating platforms, or to make nodes push other nodes.`

![RotationBug](https://user-images.githubusercontent.com/5027750/179056721-2bb80db9-1a4d-4184-81dd-e7a5d0d2f24c.gif)

Through the Gif shown above, it kinda does rotate along with the platform... SLOWLY. I can also share the project file folder in case someone wants to take a look and experiment the bug.

### Steps to reproduce

Create a Node3D, then two CharacterBody3D nodes: One the Player and the other the rotating platorm.

Player's Code should be provided with the built in GDScript Template provided by the engine, while the platform code simply uses `rotate_y(.005)` to rotate.

Control the player and place the player on the rotating platform and you'll be able to see the rotation bug.

### Minimal reproduction project

[Multiplayer_Test.zip](https://github.com/godotengine/godot/files/9114429/Multiplayer_Test.zip)

**Comment by Calinou** [comment]
cc @fabriceci
