### ISSUE TITLE
"Error" images showing up in asset library previews.

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#6302]
**Operating system or device - Godot version:**
OS is N/A, but latest Git pull as of time of typing.

**Issue description** (what happened, and what was expected):
The install/preview window for assets plugins appears to be/is pointing to missing image file(s). See here:
![missing_symbols](https://cloud.githubusercontent.com/assets/324679/18027082/517cf672-6c51-11e6-8cce-6f6f0e058483.png)

I assume these are the rating stars, or are supposed to be?

**Comment by djrm** [comment]
That was ok in 2.1, i dont know if its related but there are lots of missing icons

![screenshot from 2016-09-07 20-10-29](https://cloud.githubusercontent.com/assets/1103897/18333728/42696474-7537-11e6-91f0-0217011471de.png)
![screenshot from 2016-09-07 20-10-14](https://cloud.githubusercontent.com/assets/1103897/18333729/43b5d3ee-7537-11e6-96ea-5cdff767c7e0.png)

**Comment by reduz** [comment]
Weird, did anything change?

**Comment by djrm** [comment]
not in the icons, and as far as im concerned it is not related to the specific components i.e. asset_library_editor_plugin

**Comment by reduz** [comment]
This may be fixed now, please test

**Comment by reduz** [comment]
I found the issue, what is weird is why it didn't break before :|

**Comment by Sslaxx** [comment]
Asset preview window appears to be fixed, at least.

**Comment by vnen** [comment]
Closing as fixed then.

**Comment by eon-s** [comment]
Sometimes happens if you move something like the scene tree panel to another location

**Comment by eon-s** [comment]
Appears when playing a sample too but only in the Sample library panel, not on the inspector buttons of the sample.

![godotimageerror](https://cloud.githubusercontent.com/assets/10215987/18680274/63c28e46-7f39-11e6-8576-8c953d4e6bad.png)

**Comment by reduz** [comment]
sample library is gone, if you see any of those again, please open again or file a new one
