### ISSUE TITLE
Image importing no longer working

### ISSUE THREAD

**Issue by philomelus** [godotengine/godot#63025]
### Godot version

4.0a12

### System information

Windows 10 Pro x64

### Issue description

I cannot duplicate or load an imported image.  After looking into it further, I attempted to run demo viewport/screen_capture, and it has a similar issue:  When pushing the screen capture button, nothing happens.  In the code, if you step through the callback for the button, it attempts to get a copy of the resource.  The return in always null.
From my project, I am use load (even tried ResourceLoader.load) to load a PNG image that was imported as an Image (rather than a Texture2d as is the default), and when I call duplicate on the loaded image, I get nothing back.
Interestingly, I have an assert(image != null) before the duplicate call, and even though the debugger shows it as null, the assert never fails.  The various calls made on the image also don't fail, but also don't appear to do anything.
I was using a local build of 4.x, but I also tried this with Alpha 12, with the same results.

### Steps to reproduce

Load and run demo_project viewport/screen_capture.  Attempt to capture screen by pushing screen capture button.  Nothing happens.

### Minimal reproduction project

demo_project/viewport/screen_capture

**Comment by akien-mga** [comment]
Try to delete the `res://.godot/imported` folder if it was generated before alpha 11.

**Comment by philomelus** [comment]
I restarted from scratch with the 4.0a12 local build, so there weren't any existing imports.  I was having other issues when I attempted to import my 3.5x local build version (which both GD and C# versions work fine with), and I couldn't figure out what I needed or not any longer (e.g. the font .tres are no longer needed, but they don't get removed on import, so I wasn't sure what to do).

**Comment by jeffgamedev** [comment]
Hi, I've been able to recreate the issue in a minimum project. I have attached in a zip file
[image_load_issue_min_project.zip](https://github.com/godotengine/godot/files/9123073/image_load_issue_min_project.zip)
.

**Comment by aaronfranke** [comment]
I did a bisect and this was broken by #60739, specifically d2900429e81175a9f48240b180f1d8e3ab52865c CC @KoBeWi

**Comment by aaronfranke** [comment]
In the above test project, replacing these lines:

```gdscript
	new_texture = ImageTexture.new()
	new_texture.create_from_image(image)
```

with these lines:

```gdscript
	new_texture = ImageTexture.create_from_image(image)
```

causes the image to successfully load.

**Comment by KoBeWi** [comment]
`create_from_image()` is now static, so you can't call it on an existing ImageTexture. Just skip `ImageTexture.new()`.
The screen capture demo should be updated.

**Comment by philomelus** [comment]
I can confirm that this fixes the issues I'm having.

As for the cannot duplicate or load an imported image, I meant it literally:

`@onready var i = load("image.png")`
`var d = i.duplicate()`

d would still be null in the debugger, even though this never failed:

`assert(d != null)`

I saw there was bug about variables in the debugger not showing correctly, so maybe that is partially to blame.

Regardless, switching to static call fixes it in both my project and the demo code.  Didn't occur to me that this was a documentation issue ...

**Comment by KoBeWi** [comment]
Ah, now that you mention it, ImageTexture code examples weren't updated.

Also the most reliable way to test if something works is printing it. If the variable is null in the debugger then it's debugger bug xd

**Comment by philomelus** [comment]
From my perspective, I was immediately attempting to `create_from_image` the result of the duplicate() call;  Since the variable showed as null after the duplicate(), and the create_from_image was also not working, I really had no idea which was the real cause.

At least its an easy fix;  Just wish it had occurred to me, so I could have prevented creating an issue for it (or maybe created an issue for the real cause, or just fixed it and pushed a pull request, or ...).
