### ISSUE TITLE
AnimatableBody Nodes doesn't rotate Player's CharacterBody Node

### ISSUE THREAD

**Issue by Corruptinator** [godotengine/godot#63027]
### Godot version

v4.0.alpha11.official [afdae67cc] (Alpha Unstable Build)

### System information

Windows10 64bit, Vulkan, RTX 2080 Super

### Issue description

This is a similar issue to: https://github.com/godotengine/godot/issues/63004
where the player isn't rotating with the platform, but on AnimatableBody Nodes.

Additionally, the AnimatableBody's `Sync To Physics` only allows one Animation Layer to play at a time, rather than use all animation layers. As such Movement and Rotation on separate animation layers cannot work while Sync to Physics is active.
![AnimatableBodyBug2](https://user-images.githubusercontent.com/5027750/179167163-8d47c85b-51e7-4fcf-b0ab-e94af001820f.gif)

![AnimatableBodyBug3](https://user-images.githubusercontent.com/5027750/179167793-aef4a3ed-870f-4361-a2bc-b2c925601a52.gif)

The Sample Project will be provided below for testing.

### Steps to reproduce

Once again its similar to the CharacterBody rotation issue, (https://github.com/godotengine/godot/issues/63004) but replace/change the CharacterBody with AnimatableBody Nodes.

Use AnimationPlayer to make the platform move.

Also test the `Sync To Physics` cause it only (again) allows one animation layer to play at a time, not more than.

### Minimal reproduction project

[AnimatedBody.zip](https://github.com/godotengine/godot/files/9118552/AnimatedBody.zip)

**Comment by Calinou** [comment]
cc @fabriceci
