### ISSUE TITLE
Cameras don't work when put into a spatial node

### ISSUE THREAD

**Issue by sanyi12** [godotengine/godot#63034]
### Godot version

3.4.4 stable

### System information

Windows 10 GLES3 

### Issue description

making a simple point and click game, the player gets into an area and signals to a camera to get current. This happens until I organize the project, moving all cameras into a simple spatial node. After that cameras no longer work. Deleting the spatial node makes no difference as the problem remains. 

### Steps to reproduce

check the zip

### Minimal reproduction project

[godera.zip](https://github.com/godotengine/godot/files/9120750/godera.zip)

**Comment by Calinou** [comment]
@sanyi12 Did you resolve the problem? If so, please comment here and document the solution :slightly_smiling_face:
