### ISSUE TITLE
Godot 4.0 doesn't allow us to edit label color

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#63051]
### Godot version

4.0 alpha 11

### System information

KDE neon 5.25

### Issue description

You can't change the color of a label in a theme.

### Steps to reproduce

- Create a theme resource
- Add label
- Goto color tab and see there is nothing.

### Minimal reproduction project

[AstroWars.zip](https://github.com/godotengine/godot/files/9124034/AstroWars.zip)

**Comment by KoBeWi** [comment]
You need to override it in Theme Editor first.
![image](https://user-images.githubusercontent.com/2223172/179326654-f870988e-f08d-4acf-a692-1c4099461dba.png)

**Comment by Shadowblitz16** [comment]
@KoBeWi  Odd Idk why the option didn't show up then. Reopening the project up and rechecking if it was there seems to work.
