### ISSUE TITLE
EditorPlugin can't use scripts/scenes in subfolders

### ISSUE THREAD

**Issue by StraToN** [godotengine/godot#6305]
**Operating system or device - Godot version:**
2.1 master 3b676439789e5816a66e935f4d98accacc698943

**Issue description** (what happened, and what was expected):
A plugin can't use GDScripts and Scenes placed in subfolders. Currently it seems required to have them placed in the root plugin folder.
In the example downloadable below, the button's caption should change on click.
Console displays error:  scene/resources/scene_format_text.cpp:122 - Couldn't load external resource: res://Scripts/button.gd

**Steps to reproduce:**
Download the example plugin below.
Unzip it in a new Godot project (you should have an "addon/" folder).
Enable the plugin.
The dock appears on the left, but clicking it has no effect.

**Link to minimal example project** (optional but very welcome):
https://cloud.murgia.fr/index.php/s/fvPx2aQwtbaEilp

**Comment by GlaDOSik** [comment]
EditorPlugin can use resources in subfolders. Are you sure your project structure is valid? There's an engine.cfg inside your plugin folder. My structure looks like this: GodotPlugins/addons/Wireframe Tool. engine.cfg is in GodotPlugins, plugin.cfg is in Wireframe Tool.

**Comment by StraToN** [comment]
@GlaDOSik no difference with the structure you described. I moved engine.cfg in the root folder, but this makes no difference for the plugin since what we put in the project using the plugin is the addons/ folder. With your structure, that means the engine.cfg file is not included.

**Comment by vnen** [comment]
This is not really a bug. The problem is that `res://Scripts/button.gd` required by the  is not an existing file, it should be `res://adddons/test-plugin/Scripts/button.gd`. If I fix that and also set the `button.gd` to be a `tool` script it works.

**Comment by StraToN** [comment]
Seems ok actually. I think I still have some problems with paths, since a plugin is meant to be run only as a plugin, not as both a plugin AND a stand-alone Godot "game". 
Closing as it seems resolved.
