### ISSUE TITLE
Shader cache folder should be versioned to avoid using stale, incompatible cached shaders

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#63056]
### Godot version

4.0.alpha11

### System information

Fedora 36, GeForce GTX 1080 (NVIDIA 510.68.02)

### Issue description

The shader cache folder should be versioned to avoid using stale, incompatible cached shaders. See https://github.com/godotengine/godot/issues/62525 and https://github.com/godotengine/godot/issues/62803 for issues caused by old shader caches lingering around and still being used by recent Godot alphas.

Cache invalidation should ideally happen whenever the *commit hash* changes, or when any other part of the version identifier (including patch) changes.

This is currently only an issue with the Vulkan rendering backends, not OpenGL (as OpenGL in `master` doesn't have shader caching to my knowledge).

### Steps to reproduce

- Open an project made on an older 4.0 alpha in the latest `master` branch.
- Notice that Vulkan shader issues may pop up in the console.

### Minimal reproduction project

N/A

**Comment by RandomShaper** [comment]
I updated my PR to do versioning as suggested here.
