### ISSUE TITLE
Shader uniform vec4 array shows as PackedFloat32Array, breaking future uniforms with the same name.

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot#63064]
### Godot version

v4.0.alpha.custom_build [ae5668f81]

### System information

Arch on 5.18.11-arch1-1

### Issue description

See reproduction steps, as it goes through more thoroughly

### Steps to reproduce

1) Make a shader with some working uniforms

    ```glsl
    shader_type canvas_item;

    uniform vec3 my_array1[4];
    uniform vec3 my_array2[4];

    ```
    ![shader parameters](https://user-images.githubusercontent.com/14253836/179347606-fdc57e50-2e12-4edf-b197-1ee875050fe4.png)

2) Change one of them to a vec4 array:

    ```glsl
    uniform vec4 my_array1[4];
    ```
    Array type changes to PackedFloat32Array which kinda makes sense, but the values are still Vec3
    ![image](https://user-images.githubusercontent.com/14253836/179347639-ec584fe4-c8b0-4a32-a44c-305c85fc5463.png)

3) Rename it to `my_array` without the number and it changes to this:

    Since it's a new variable name, it's pretty much the expected behavior.

    ![image](https://user-images.githubusercontent.com/14253836/179347659-c4af7b88-94b8-4e63-b323-c7dbace034cf.png)

4) Change it back to a vec3 array:

    Same variable name so the bug happens. The type changes to PackedVector3Array but the values are still floats.

    ![image](https://user-images.githubusercontent.com/14253836/179347695-59ec1d50-0fea-4a07-ae6e-a6483eaf8494.png)

### Minimal reproduction project

(Right after step 1) [test15.zip](https://github.com/godotengine/godot/files/9125430/test15.zip)

**Comment by reptofrog** [comment]
I'm still running into this on 4.1.3

**Comment by TheDanDLion** [comment]
i'm running into this on 4.2.1 as well

![image](https://github.com/godotengine/godot/assets/47982752/f287fba8-7fcc-4864-8c3c-5c6c80e8a00d)
