### ISSUE TITLE
Incorrect property types in extension_api.json

### ISSUE THREAD

**Issue by VladoCC** [godotengine/godot#63066]
### Godot version

4.0.alpha12

### System information

Windows 10

### Issue description

Information about properties of classes in `extension_api.json` appears to be incorrect in some cases.

There are cases where int turns into list of two elements:
* SkeletonModificationStack2D and SkeletonModificationStack3D
    - Property: modification_count
    - Expected value (as in docs): int
    - Actual value (as in json): Modifications,modifications/
* Curve, Curve2D and Curve3D
    - Property: point_count
    - Expected value (as in docs): int
    - Actual value (as in json): Points,point_
* ItemList and PopupMenu
    - Property: item_count
    - Expected value (as in docs): int
    - Actual value (as in json): Items,item_
* MenuButton and OptionButton
    - Property: item_count
    - Expected value (as in docs): int
    - Actual value (as in json): Items,popup/item_
* SkeletonProfile
    - Property: group_size
    - Expected value (as in docs): int
    - Actual value (as in json): Groups,group/
    - Property: bone_size
    - Expected value (as in docs): int
    - Actual value (as in json): Bones,bone/
* TabBar
    - Property: tab_count
    - Expected value (as in docs): int
    - Actual value (as in json): Tabs,tab_    

And there are also a few of a different type. This ones are not documented, but can be accessed through GDScript.   
Getters and setters are also empty strings for them.
* AudioStreamRandomizer
    - Property: streams
    - Expected value (as in docs): **not documented**
    - Actual value (as in json): stream_
* TileMap
    - Property: layers
    - Expected value (as in docs): **not documented**
    - Actual value (as in json): layer_
* TileSet
    - Property: occlusion_layers
    - Expected value (as in docs): **not documented**
    - Actual value (as in json): occlusion_layer_
    - Property: physics_layers
    - Expected value (as in docs): **not documented**
    - Actual value (as in json): physics_layer_
    - Property: terrain_sets
    - Expected value (as in docs): **not documented**
    - Actual value (as in json): terrain_set_
    - Property: navigation_layers
    - Expected value (as in docs): **not documented**
    - Actual value (as in json): navigation_layer_
    - Property: custom_data_layers
    - Expected value (as in docs): **not documented**
    - Actual value (as in json): custom_data_layer_

### Steps to reproduce

1. Get `extension_api.json`
2. Check for yourself

**Comment by VladoCC** [comment]
While auto-completion for GDScript shows options described in part 2, this code:
```
TileSet.new().occlusion_layers
```
wouldresult in error `Invalid get index 'occlusion_layers' (on base: 'TileSet').`

**Comment by raulsntos** [comment]
Those properties seem to all be using the `ADD_ARRAY` or `ADD_ARRAY_COUNT` macros. The macros add the property to `ClassDB` with this code:

https://github.com/godotengine/godot/blob/ae5668f81e9ed7ae9e9a13b120d89de884b718be/core/object/class_db.cpp#L872-L882

Those methods create a `PropertyInfo` with the `class_name` set to `{label},{prefix}` (e.g.: `Points,point_`) or `{prefix}` (e.g.: `stream_`).

Then, `extension_api_dump` gets the type from the `PropertyInfo` with this code:

https://github.com/godotengine/godot/blob/ae5668f81e9ed7ae9e9a13b120d89de884b718be/core/extension/extension_api_dump.cpp#L41-L68

And ends up returning when `class_name` is not empty and uses it as the type which is incorrect in this case.

When the property usage is set to `PROPERTY_USAGE_ARRAY` the `class_name` is used by the EditorInspector to create a dedicated array editor for the array.

I guess we need to add a check for `PROPERTY_USAGE_ARRAY` in `extension_api_dump::get_type_name` like this:

```diff
diff --git a/core/extension/extension_api_dump.cpp b/core/extension/extension_api_dump.cpp
index d5c49b01e9..fb07103a4c 100644
--- a/core/extension/extension_api_dump.cpp
+++ b/core/extension/extension_api_dump.cpp
@@ -49,6 +49,9 @@ static String get_type_name(const PropertyInfo &p_info) {
 	if (p_info.type == Variant::INT && (p_info.usage & (PROPERTY_USAGE_CLASS_IS_ENUM | PROPERTY_USAGE_CLASS_IS_BITFIELD))) {
 		return String("enum::") + String(p_info.class_name);
 	}
+	if (p_info.type == Variant::INT && (p_info.usage & PROPERTY_USAGE_ARRAY)) {
+		return "int";
+	}
 	if (p_info.class_name != StringName()) {
 		return p_info.class_name;
 	}

```

But I don't know if this is entirely correct.
