### ISSUE TITLE
GDScript 2.0: Enumerations defined in class_name classes are not considered constant

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#63076]
### Godot version

4.0.dev

### System information

Linux

### Issue description

Enumerations from classes registered with class_name can no longer be used in a static way.

### Steps to reproduce

Use an enum from a class_name class in a match statement:

```gdscript
class_name RegisteredClass

enum Enum {
	A,
	B,
}
```

```gdscript
const A = RegisteredClass.Enum.A # error

func _init():
	match val:
		RegisteredClass.Enum.A: # error
			pass
		RegisteredClass.Enum.B:
			pass
```
Error: Expression in match pattern must be a constant.

**Comment by Calinou** [comment]
Did it work in previous 4.0.alphas?

**Comment by jtnicholl** [comment]
Your example code gives no errors for me, I can't replicate this on current master branch or with alpha 11.

> ### Godot version
> 
> 4.0.dev

Which commit/alpha version was this? Maybe it's been fixed already.

**Comment by Jummit** [comment]
That's very weird, I get this error inside a large workspace but not in a clean project. Must be some erroneous state of the GDScript parser. Closing as hard to reproduce.
