### ISSUE TITLE
TileMap image sometimes disappear

### ISSUE THREAD

**Issue by CodeLazier** [godotengine/godot#63070]
### Godot version

4.0 a12

### System information

win10 vulkan desktop

### Issue description

Moving or scaling is a chance to cause the image to disappear in TileMap, and by the way this issue has not been found in TileSet yet.

![tilemapb](https://user-images.githubusercontent.com/14953625/179355161-b365ba81-db1c-49ca-af0c-21fa576799fb.gif)

### Steps to reproduce

add tilemap node set tileset add tile image

**Comment by MewPurPur** [comment]
It has also happened to me at certain zoom levels.

**Comment by groud** [comment]
Yeah I noticed that big too but I have no clue where it comes from. I feel it might come from the rendering code but I can't be sure.

**Comment by KoBeWi** [comment]
Another similar issue is that the background will disappear sometimes:
![godot windows tools 64_aaW4XegUfK](https://user-images.githubusercontent.com/2223172/180602328-f0ff6f40-574d-4f31-bffe-facc339d97d1.gif)
