### ISSUE TITLE
Wrong PointLight2D position on parallax layers when camera is active

### ISSUE THREAD

**Issue by Cowa** [godotengine/godot#63101]
### Godot version

v4.0.alpha12.official [2c11e6d9e]

### System information

macOS, Linux and Windows 10

### Issue description

The PointLight2D position on parallax layers is off when a camera is active.

In my example, a flashlight is attached to the player.

When camera is disabled the light illuminate the parallax layer at the right position:
<img width="631" alt="Capture d’écran 2022-07-17 à 09 48 33" src="https://user-images.githubusercontent.com/1422403/179389109-aba09d5a-3338-4ecb-ae28-b2a084a6f437.png">

When camera is enabled the light position is off:
<img width="634" alt="Capture d’écran 2022-07-17 à 09 48 49" src="https://user-images.githubusercontent.com/1422403/179389114-7ba91285-4158-405d-a908-5a4d2af9678f.png">

Video of the minimal reproduction project:

https://user-images.githubusercontent.com/1422403/179389256-7b54426c-4857-4525-87da-0ed712e618e9.mov

### Steps to reproduce

How to use the minimal reproduction project:

- 'arrows' to move player
- 'enter' to toggle on/off the camera

### Minimal reproduction project

[parallax-light2d-camera-bug.zip](https://github.com/godotengine/godot/files/9127203/parallax-light2d-camera-bug.zip)

**Comment by Calinou** [comment]
Can you reproduce this with the same setup on 3.4.4?

**Comment by Cowa** [comment]
@Calinou on 3.4.4 it works correctly.

I found this issue while porting a project from 3.4 to 4.0
