### ISSUE TITLE
Navigation2D bug

### ISSUE THREAD

**Issue by cjmxp** [godotengine/godot#6310]
**Operating system or device - Godot version:**
windows  godot v2.2.alpha

**Issue description** (what happened, and what was expected):
2D navigation is not the shortest path

![image](https://raw.githubusercontent.com/cjmxp/godotbug/master/testpath/bug.png)

[recastnavigation](https://github.com/recastnavigation/recastnavigation)

**Link to minimal example project** (optional but very welcome):
[testpath](https://github.com/cjmxp/godotbug/tree/master/testpath)

**Comment by Calinou** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by bojidar-bg** [comment]
Could confirm with the OP's test project, after converting to 3.0. (run with "Visible Navigation" on)
[testpath3.0.zip](https://github.com/godotengine/godot/files/1898443/testpath3.0.zip)
![image](https://user-images.githubusercontent.com/5276727/38612067-3988d508-3d8e-11e8-967f-60ad785fc6fc.png)

**Comment by Zireael07** [comment]
I believe I saw the same thing reported for 3.0 (not sure if release version or one of the alphas/betas).
