### ISSUE TITLE
Godot Crashes On Start

### ISSUE THREAD

**Issue by berensn** [godotengine/godot#63112]
### Godot version

3.4.4-stable mono

### System information

Win 11, Ryzen 5 3600, 32GB RAM, Radeon 5700XT 

### Issue description

Godot fails to launch 

![image](https://user-images.githubusercontent.com/7515745/179431390-b2d2f999-82e8-437b-969e-b10e49f7bb45.png)

From the log:
`Config attempting to parse: 'D:/Gaming/Godot/GodotSharp/Mono/etc\mono\config'. (in domain Mono, info)
Image addref mscorlib[0000000019a87510] (asmctx DEFAULT) -> D:/Gaming/Godot/GodotSharp/Mono/lib/mono/4.5/mscorlib.dll[0000000019bb33c0]: 2 (in domain Mono, info)
Prepared to set up assembly 'mscorlib' (D:/Gaming/Godot/GodotSharp/Mono/lib/mono/4.5/mscorlib.dll) (in domain Mono, info)
AOT: image 'D:/Gaming/Godot/GodotSharp/Mono/lib/mono/4.5/mscorlib.dll.dll' not found: The system cannot find the file specified.
 (in domain Mono, info)
AOT: image 'D:/Gaming/Godot/GodotSharp/Mono/lib/mono/aot-cache/amd64/mscorlib.dll.dll' not found: The system cannot find the path specified.
 (in domain Mono, info)
Assembly mscorlib[0000000019a87510] added to domain GodotEngine.RootDomain, ref_count=1 (in domain Mono, info)
Assembly mscorlib[0000000019a87510] added to domain GodotEngine.Domain.Scripts, ref_count=2 (in domain Mono, info)
`
[2022-07-17_12.14.10_24232.log](https://github.com/godotengine/godot/files/9128073/2022-07-17_12.14.10_24232.log)

Its looking for mscorlib.dll.dll and not finding it. I checked the folder its looking in and mscorlib.dll exists but not the double extension file.

Also, the folder D:/Gaming/Godot/GodotSharp/Mono/lib/mono contains the directories 4.5 and v4.0, but not aot-cache

### Steps to reproduce

Download the 3.4.4 x64 mono verson of [godot ](https://downloads.tuxfamily.org/godotengine/3.4.4/mono/Godot_v3.4.4-stable_mono_win64.zip)from the website, extract and run the Godot_v3.4.4-stable_mono_win64.exe file

**Comment by Calinou** [comment]
@berensn Can you (or anyone else) still reproduce this bug in [Godot 3.5](https://godotengine.org/article/godot-3-5-cant-stop-wont-stop) or any later release?

**Comment by berensn** [comment]
Godot 3.5 mono does not have this issue on Win11.

**Comment by Calinou** [comment]
> Godot 3.5 mono does not have this issue on Win11.

Closing as resolved then.
