### ISSUE TITLE
Font options in toolbar missing after font refactor

### ISSUE THREAD

**Issue by KieranCarden** [godotengine/godot#63133]
### Godot version

v4.0.alpha12.official [2c11e6d9e]

### System information

Windows 10

### Issue description

After the font refactor for Alpha 12, the font options in the toolbar is no longer present. Having these options at a glance, automatically register font families, and in the toolbar made working with fonts substantially easier, rather than having to navigate to theme overrides every time.

Alpha 11
![font-options-toolbar](https://user-images.githubusercontent.com/4044137/179431395-8db7a61b-e833-4ce6-91f1-65b13b1080b5.png)

Alpha 12
![font-options-toolbar_a12](https://user-images.githubusercontent.com/4044137/179431472-68c525c0-6596-407f-ae28-66af9c92d3c1.png)

### Steps to reproduce

1. Create a new project
2. Add any control node that uses text (Label, RichTextLabel, LineEdit, etc)
3. Select node, notice options missing from toolbar

### Minimal reproduction project

Two projects for ease of testing and not having to reimport between the two versions.

[font-options-toolbar_a11.zip](https://github.com/godotengine/godot/files/9128890/font-options-toolbar_a11.zip)
[font-options-toolbar_a12.zip](https://github.com/godotengine/godot/files/9128891/font-options-toolbar_a12.zip)

**Comment by Chaosus** [comment]
cc @bruvzg

**Comment by bruvzg** [comment]
It was removed in favor of https://github.com/godotengine/godot/pull/62139, toolbar was causing issues on a small screens and was inconsistent with the rest of editor UI.

**Comment by akien-mga** [comment]
Indeed, this is by design. Similar functionality will come back in a different form in future alphas :)
