### ISSUE TITLE
self in setget

### ISSUE THREAD

**Issue by razvanc-r** [godotengine/godot#6313]
I have the feeling that using `self.` is kind of expensive but I like using `self.` because it gives me clear code. Anyway, I wanted to use `setget` for some experimentation and I found that I am unable to use `self.` in these functions giving an error such as `Parser Error: Must use 'vel_max' instead of 'self.vel_max' in setter.`. Why is that? And can this be "fixed"? I say "fixed" cause I see this is a GDScript compilation error so I guess this is the intended behavior but it doesn't make sense to have `self.` available everywhere except in this one place. I think it's a usability flaw. I know it's minor thing :D

**Comment by punto-** [comment]
If you use self.variable = value, it triggers the setter of the variable,
so if you use it inside the setter it'll be an infinite loop

**Comment by reduz** [comment]
I think someone optimized the use of self actually, so it's as fast as not
using it

**Comment by razvanc-r** [comment]
@punto- well it does make sense and I know that Python also uses a hidden variable when working with `@property`. But I still feel like it's inconsistent. Why does it trigger an infinite loop when using `self.`, but it doesn't without? I mean, even without `self.` you're still accessing and setting the same variable are you not?

@reduz that's great :). Yay improvements!

**Comment by punto-** [comment]
Because there needs to be a way to be able to use the variable from the
setter without triggering an infinite loop, this is as good as any :) The
setter actually sets the value of the variable, so most of the time it
needs to manipulate it, especially if there's no getter.

**Comment by razvanc-r** [comment]
I understand that, except I don't understand why adding `self.` would trigger the loop while not adding it will not, since in both cases you're still refering to the same class variable, that's what I don't get. With or without `self.` it's the same variable, unless... in the background the engine makes a hidden variable that isn't accessible from GDScript directly or something on these lines. Now that I look at the docs there are two things:

`var x = 'something' setget set_x, get_x`

and then there's

`var x setget set_x, get_x`

Alright, I was using the first version and I just couldn't get why you have to use `x` inside of `set_x` for example, without `self.`, but now I see that it isn't mandatory to use it, you can very well use a different variable such as `self.__x` for example which you would treat as being "hidden". I propose to make this work as in Python and only have `var x setget set_x, get_x` allowed and use some other variable inside of `set_x` & `get_x`, not `x` itself. Or maybe it's just me and I'm the only one confused about it :)...

**Comment by Calinou** [comment]
I'm closing this since there does not seem to be a clear consensus as to whether this is a bug.
