### ISSUE TITLE
`FBX file import is enabled, but no FBX2glTF path is configured` warning printed even if FBX import is disabled

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#63144]
### Godot version

1c6148aa86c4a3b8d5c292da69ffacc2f3a46eb8

### System information

Windows 11

### Issue description

I've noticed that warning always printing at startup even if FBX import is disabled:

![image](https://user-images.githubusercontent.com/3036176/179501277-edb43043-0e14-40c9-9d17-b0f9cffa7326.png)

### Steps to reproduce

Just run the editor.

**Comment by jtnicholl** [comment]
I can't replicate this, I think it was fixed when the enabled property was moved from editor settings to project settings.

**Comment by Calinou** [comment]
Closing per @jtnicholl's comment.
