### ISSUE TITLE
Toggling distraction-free mode reset scroll position when in editor reference

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#63152]
### Godot version

happens in 4.0.alpha12, does *not* happen in 3.5rc6

### System information

linux

### Issue description

https://user-images.githubusercontent.com/71937306/179535454-12bbc15d-7fce-4044-8644-601dc56055a1.mp4

This also happens when scrolling in distraction-free mode and going back to the regular mode.

### Steps to reproduce

see video

**Comment by Calinou** [comment]
cc @bruvzg 

Note that changing the editor theme in the Editor Settings will also do that.

**Comment by kitbdev** [comment]
Toggling distraction-free mode resets can't be reproduced in 4.0.4 or later.
Changing the theme resets can't be reproduced in 4.1.3 or later.

**Comment by akien-mga** [comment]
Closing as fixed.
