### ISSUE TITLE
Discrepancy between built-in animation and same animation saved to file from imported gltf

### ISSUE THREAD

**Issue by tom-jk** [godotengine/godot#63158]
### Godot version

v4.0.alpha12.official [2c11e6d9e]

### System information

Linux Mint 20, Vulkan Clustered, Nvidia RTX 2060 SUPER (510.73.05-0ubuntu0.20.04.1)

### Issue description

**Case**
To add extra tracks to animations in an imported .gltf, the animation must be saved to its own file.

**Expectation**
When the animation file is saved (and otherwise unmodified), it seems correct to expect that opening an inherited scene and playing it in the animationplayer should give the same results as if the animation were not saved seperately (built-in).

**Problem**
Some transform tracks go missing in the saved animation. As a result, those transforms can be improperly set.

![godot_savedanimdiscrepency_tracks](https://user-images.githubusercontent.com/64640811/179553604-26c24e07-1bbd-4cc9-8568-dbdcdc254c67.gif)
_from the MRP: notice the missing eye position tracks._

### Steps to reproduce

1. Open the MRP godot project.
2. facerig.gltf -> new inherited scene.
3. select animationplayer node. Then, optionally, select skeleton3D and select one of the eyes to see bone transforms.
4. in animation dock, switch to these animations:
4.1. action_sad - it looks fine.
4.2. action_sus - it looks fine.
4.3. action_sad again - it looks broken.

![godot_savedanimdiscrepency_problem](https://user-images.githubusercontent.com/64640811/179557300-527c593d-9942-44c6-9ffe-8f01de8f8a42.gif)

5. Close the scene, open facerig.gltf, go to animations -> action_sad -> save to file -> uncheck enabled, and reimport.
6. New inherited scene and repeat step 4 - with the animation built-in, it does not break.

When viewing bone transforms, notice how the eye position is normally (+/-0.5, 1.5, 0), and (0, 0, 0) when broken.

https://user-images.githubusercontent.com/64640811/179577278-7cfb62e8-e632-4cb2-980a-93c8462f67f5.mp4

_Video shows the process of creating a new godot project, exporting the gltf from blender, and comparing results with built-in versus saved animation._ 
**0:00** - the animations inside blender
**0:18** - creating godot project
**0:34** - exporting from blender
**0:50** - turning off animation optimizer
**0:58** - the animations inside godot (built-in)
**1:15** - enabling save to file for action_sad anim
**1:27** - the animations inside godot, action_sad now broken (at **1:37**)
**1:49** - disabling save to file again, anims ok again

### Minimal reproduction project

[SavedAnimDiscrepency.zip](https://github.com/godotengine/godot/files/9133592/SavedAnimDiscrepency.zip)

includes .blend file and godot project.

The .blend and .gltf were made/exported from Blender 3.2.1, and contain an armature with four bones (root -> mouth, eye.r, eye.l) and four animations/actions (action_happy, action_sad, action_sus, and action_default).

The godot project has the .gltf set to use a saved animation file for the action_sad animation.

**Comment by TokageItLab** [comment]
> Some transform tracks go missing in the saved animation. As a result, those transforms can be improperly set.
Perhaps it is an Optimizer problem; disable the Optimizer and import the animation with the `IfPresent` setting.

**Comment by tom-jk** [comment]
Optimizer is already disabled and IfPresentForAll is used (can be seen at 0:50 in the video).

**Comment by TokageItLab** [comment]
If so, then it is likely that RestTrack is not properly set. See #59536.

**Comment by TokageItLab** [comment]
Oh, there certainly seems to be something wrong. I'll look into it in more detail later.

**Comment by TokageItLab** [comment]
The problem seems to be that `_save_animation_to_file()` is done before `IfPresentForAll` is applied in the importer. I am working on the animation importer now and will fix it later.

**Comment by TokageItLab** [comment]
May will be fixed #63138. Please check it if you possible.

**Comment by tom-jk** [comment]
Can confirm that 63138 appears to fix this.
