### ISSUE TITLE
updating image using Image.get_data()

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#6315]
**Operating system or device - Godot version:**
2.x

**Issue description** (what happened, and what was expected):

It could be handy if we could modify the content of an `Image` by writing directly into the `RawArray` returned by `Image.get_data();` in gdscript.

**Steps to reproduce:**

```
var img = Image( 320, 200, false, Image.FORMAT_GRAYSCALE );

print( img.get_data()[ 456 ] );

img.get_data()[ 456 ] = 123;

print( img.get_data()[ 456 ] );
```

**Link to minimal example project** (optional but very welcome):

**Comment by Calinou** [comment]
This is now possible by accessing the `data` directory, which itself contains a `data` PoolByteArray:

```gdscript
func _ready():
    var image = Image.new()
    image.create(320, 200, false, Image.FORMAT_L8)
    print(image.data.data)
    image.data.data[456] = 123
    print(image.data.data[456])
```
