### ISSUE TITLE
Boxy visual artifacts and black lines on mesh

### ISSUE THREAD

**Issue by paddy-exe** [godotengine/godot#63153]
### Godot version

v4.0.alpha12.official [2c11e6d9e]

### System information

Windows 10, Vulkan, AMD Radeon 580 Series (GPU)

### Issue description

Running the Godot4Beginners course shows these visual artifacts on all meshes:
![image](https://user-images.githubusercontent.com/38077837/179491233-7f0dcbd7-94f7-48ab-8876-8e12ee5e8a56.png)
![image](https://user-images.githubusercontent.com/38077837/179491293-51706142-b468-4f43-84d2-9e7ba5ff0328.png)
![Godot4Artifacts](https://user-images.githubusercontent.com/38077837/179491518-62523142-23bb-413e-9f4f-cc0385b3693f.gif)

I do get these error messages:
```
  servers/rendering/renderer_rd/storage_rd/mesh_storage.cpp:702 - Condition "!mesh" is true.
  servers/rendering/renderer_rd/storage_rd/mesh_storage.cpp:683 - Condition "!mesh" is true.
  servers/rendering/renderer_rd/storage_rd/mesh_storage.cpp:213 - Condition "!mesh" is true.
  drivers/vulkan/rendering_device_vulkan.cpp:8594 - Attempted to free invalid ID: 1179440969154721
  servers/rendering/renderer_rd/storage_rd/mesh_storage.cpp:217 - deleting mesh with active instances
Switch Scene Tab
  servers/rendering/renderer_rd/storage_rd/mesh_storage.cpp:702 - Condition "!mesh" is true.
  servers/rendering/renderer_rd/storage_rd/mesh_storage.cpp:683 - Condition "!mesh" is true.
  servers/rendering/renderer_rd/storage_rd/mesh_storage.cpp:213 - Condition "!mesh" is true.
  servers/rendering/renderer_rd/storage_rd/mesh_storage.cpp:217 - deleting mesh with active instances

```

### Steps to reproduce

Running the project

**Comment by Calinou** [comment]
@paddy-exe Can you still reproduce this in 4.3.dev5 or later? If so, please upload a MRP.

**Comment by paddy-exe** [comment]
@Calinou 4.3 dev6 indeed fixes this issue
![grafik](https://github.com/godotengine/godot/assets/38077837/80c52dac-3e78-46d3-912e-db1b482adb02)
