### ISSUE TITLE
The `New TextFile...` window is a global file-system explorer

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#63155]
### Godot version

4.0.alpha12

### System information

linux

### Issue description

The `FileSystem dock > RMB > New TextFile...` dialog allows exploring the whole file system (outside of res://).

### Steps to reproduce

try creating a new TextFile

**Comment by KoBeWi** [comment]
This might be intended for whatever reason as the dialogs access resource directory by default.
Also it's the same in 3.5 when you create text file from script editor.
CC @Paulb23

**Comment by Paulb23** [comment]
Yeah this is intended, `TextFiles` are not project files but any text file you want to edit, so there is no reason to limit it to the project.
