### ISSUE TITLE
Placing tiles while holding right click softlocks Godot

### ISSUE THREAD

**Issue by bibizu** [godotengine/godot#63160]
### Godot version

v3.4.stable.official [206ba70f4]

### System information

Windows 10

### Issue description

Godot will have features stop working after placing tiles while holding the erase button.

### Steps to reproduce

On any tile map with a tile set:

1. Hold down the erase button (right mouse button) while in placing mode.
2. Press the place button (left mouse button) twice.

The engine will softlock--deleting nodes, changing variables, and switching scenes are some examples of things that do not work.
Restarting the engine will fix the issue.

Recording of the bug:

https://user-images.githubusercontent.com/104801209/179577165-c5de0f04-4e8b-4591-bf1f-ee32bbf00f84.mp4

### Minimal reproduction project

[BugReport.zip](https://github.com/godotengine/godot/files/9134398/BugReport.zip)

**Comment by Calinou** [comment]
@bibizu Remember that for GitHub video previews to work, you need to have a blank line before *and* after the video URL. I edited your post accordingly, but remember to do this in the future :slightly_smiling_face:

**Comment by akien-mga** [comment]
Fixed by #63167.
