### ISSUE TITLE
Nix build fails to detect vulkan (or any video backend)

### ISSUE THREAD

**Issue by IllustratedMan-code** [godotengine/godot#63162]
### Godot version

4.0.dev(f00803b)

### System information

NIXOS, nvidia 1650 Max-q

### Issue description

Nix build of godot (using [this flake](https://github.com/IllustratedMan-code/Godot-Flake)) fails to start and gives this error message:

```
Godot Engine v4.0.alpha.custom_build - https://godotengine.org
ERROR: Could not initialize Vulkan
   at: DisplayServerX11 (platform/linuxbsd/display_server_x11.cpp:4744)
Your video card driver does not support any of the supported Vulkan or OpenGL versions.
Please update your drivers or if you have a very old or integrated GPU, upgrade it.
If you have updated your graphics drivers recently, try rebooting.
ERROR: Unable to create DisplayServer, all display drivers failed.
   at: setup2 (main/main.cpp:1715)
ERROR: BUG: Unreferenced static string to 0: interface_added
   at: unref (core/string/string_name.cpp:131)
```

- I have verified that vulkan is functioning correctly: vkcube works without a hitch
- opengl is also available and functioning

How does godot detect the video driver?  Nix uses non-standard paths for executables, so if godot is scanning for some hardcoded directory, that may be the culprit.

Any Ideas?

### Steps to reproduce

This is easily reproduced using [this nix flake](https://github.com/IllustratedMan-code/Godot-Flake). Make sure that opengl and vulkan are enabled using the following configuration.nix snippet:

```
hardware.opengl.enable = true;                                                                     
hardware.opengl.driSupport = true;
environment.systemPackages = with pkgs; [glxinfo vulkan-tools];
```

**Comment by IllustratedMan-code** [comment]
@akien-mga

**Comment by akien-mga** [comment]
All those are `dlopen`'ed too with special wrappers.

What does the NixOS documentation say about `dlopen`ing libraries? It's a very common use case for a lot of applications.

**Comment by jgillich** [comment]
You don't want to use patchelf when building from source; instead, make sure the binary is built via the correct rpath to begin with. Also, you're missing `vulkan-loader` in your build inputs, `systemPackages` has no effect on builds.

Perhaps the audio driver issue would be fixed by adding the `pkg-config alsa --libs` flag? Because that's what the nixpkgs derivation does.

**Comment by akien-mga** [comment]
> Perhaps the audio driver issue would be fixed by adding the `pkg-config alsa --libs` flag? Because that's what the nixpkgs derivation does.

We wrap optional dependencies intentionally so that they get `dlopen`ed at runtime if they're available. This make Godot binaries portable on all Linux distros (aside from NixOS I guess) without forcing users to install system libraries they might not want/need.

Currently we wrap:
- asound: https://github.com/godotengine/godot/blob/master/drivers/alsa/asound-so_wrap.h
- pulse: https://github.com/godotengine/godot/blob/master/drivers/pulseaudio/pulse-so_wrap.h
- speechd: https://github.com/godotengine/godot/blob/master/platform/linuxbsd/speechd-so_wrap.h
- udev: https://github.com/godotengine/godot/blob/master/platform/linuxbsd/libudev-so_wrap.h

And eventually we'll also wrap all x11 and wayland libs so that the same binary can run on either display server and also on headless servers.

**Comment by jgillich** [comment]
I was referring to adding a patch to the Nix flake, this is 100% a matter of packaging and it doesn't concern Godot itself.

**Comment by IllustratedMan-code** [comment]
I was trying to avoid patches as they aren't really sustainable as far as I know ( I would have to maintain it by making more patches ). `LD_LIBRARY_PATH` didn't seem to work for me either. I was trying to avoid its use anyway, as from https://github.com/NixOS/nixpkgs/issues/85817#issuecomment-619200028, `LD_LIBRARY_PATH` is an "impermanent, and ugly hack ".

Adding Vulkan loader to buildInputs doesn't seem to work, even when combined with the other solutions.
 `autoPatchelfHook` didn't work either, though I think I might be able to make it work with some more configuring. 

I'm not sure how I would add the `RPATH` during the build itself. 
> instead, make sure the binary is built via the correct rpath to begin with. 

How do I do this?

I'm pretty new to building stuff with nix, but my end goal is being able to develop godot using nix, so would like to avoid any impermanent solutions.

**Comment by jgillich** [comment]
Patches are very common across nixpkgs, and you don't have to update them all that often. IMO

> How do I do this?

It appears that we can pass linker arguments via the scons LINKFLAGS argument. Something like this:

```
sconsFlags = "platform=linuxbsd LINKFLAGS='-rpath=${vulkan-loader}/lib -rpath=${alsa-lib}/lib -rpath=${libpulseaudio}/lib'";

```

There appears be an issue with incorrect escaping in the scons builder though

**Comment by akien-mga** [comment]
> There appears be an issue with incorrect escaping in the scons builder though

Yeah I noticed a while ago that specifying 2+ arguments to `LINKFLAGS` didn't work. Might have a closer look eventually but if someone wants to check it and make a PR (like same bug for other `*FLAGS`), feel free to.

**Comment by jgillich** [comment]
Hmm that's not going to work anyway, apparently LINKFLAGS are passed to gcc?

```
       > [Initial build] Linking Program bin/godot.linuxbsd.tools.64 ...
       > g++: error: unrecognized command-line option '-rpath=/nix/store/5vzbm61y6zcmn7dcjx145x874zfwfysv-libpulseaudio-15.0/lib'
```

scons --help says
```
 LINK: Linker
    default: None
    actual: gcc
```
Shouldn't that be ld?

**Comment by akien-mga** [comment]
Most buildsystems nowadays call g++ or clang++ directly for the linking step, and the compilers call the relevant linker internally. To pass this kind of linker options you should use `-Wl,-rpath=...`.

**Comment by jgillich** [comment]
In that case we can actually do this:
```
sconsFlags = "platform=linuxbsd LINKFLAGS=-Wl,-rpath=${vulkan-loader}/lib,-rpath=${alsa-lib}/lib,-rpath=${libpulseaudio}/lib";
```
Still gives me the Vulkan error from above, but perhaps this helps with `use_volk=no`, idk. compiled times are very long so I think I'm giving up :grin:

**Comment by IllustratedMan-code** [comment]
I managed to get it working using the runtimeDependencies attribute! My flake that I linked should now be functional. This solved the audio and vulkan issues. The autoPatchElf hook is present in the flake, but it might not be necessary. 

My plan is to clean it up a little, then try to add it to the godot github. With a little more work, there could be an official overlay so that newer versions of godot are easily available for the nix package manager.

**Comment by turboMaCk** [comment]
It seems godot uses dlopen quite heavily [and more and more over time](https://github.com/godotengine/godot/commit/2dd5a792bb95f564574449a0ccbf2ad31bf57e45)

Even if you get vulkan-loader glu and x11 stuff into rpath binary will fail in runtime on current master:

```
  readelf -d result/bin/godot | grep PATH
 0x000000000000001d (RUNPATH)            Library runpath: [/nix/store/w5mlarq8mk5s6yacsnj6r4vs3cw7i95m-glu-9.0.2/lib:/nix/store/7s72wy4q3sy6p9kvf2hyj7lhmv9cvckg-libX11-1.8.1/lib:/nix/store/ar5q71s83h89vb1svx4bfx3lz11bdpq3-libXcursor-1.2.0/lib:/nix/store/z0k7wwpyl91v4g1zsl8pvj1vw6bqn5va-libXinerama-1.1.4/lib:/nix/store/2d2ffx6zzyffn5cm0qafvs73bbm1hv48-libXi-1.8/lib:/nix/store/qk6427azzgb2kdv7958jj71a53gv6x8p-libXrandr-1.5.2/lib:/nix/store/gpa8dhckvkyzw1blng40nhwvv8kpg0km-libXext-1.3.4/lib:/nix/store/lx3zjgvqhs4j8qf3b8hglb8mr8nhxmcx-libXfixes-6.0.0/lib:/nix/store/mfdqir05xfvkah061ypckh3acl11sq6j-vulkan-loader-1.3.231.0/lib:/nix/store/fm32hqp9kl0a0zncnv96zc9d9rjk4rh5-alsa-lib-1.2.7.2/lib:/nix/store/qk9xwkgq79qjh38a1fn0phgkpx5apg29-dbus-1.14.4-lib/lib:/nix/store/0k59nnzig81k59rl4xbi1wswlqbwlx9n-fontconfig-2.14.0-lib/lib:/nix/store/bm529sa3x74q6i0w4dyi1fcs35a7a2pk-systemd-252.1/lib]
```

```
./result/bin/godot 
Godot Engine v4.0.beta.custom_build - https://godotengine.org
Your video card driver does not support the selected OpenGL version.
Please try updating your GPU driver.
If you have updated your graphics drivers recently, try rebooting.
ERROR: Unable to create DisplayServer, all display drivers failed.
   at: setup2 (main/main.cpp:2018)
ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools11BucketLargeE
   at: ~PagedAllocator (./core/templates/paged_allocator.h:140)
ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools12BucketMediumE
   at: ~PagedAllocator (./core/templates/paged_allocator.h:140)
ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools11BucketSmallE
   at: ~PagedAllocator (./core/templates/paged_allocator.h:140)
ERROR: BUG: Unreferenced static string to 0: interface_added
   at: unref (core/string/string_name.cpp:131)
```

I'm wondering why it is but I'm also afraid to dig further as this might be a rabbit hole. In any case you can get older beta for godot 4 from nixpks already. Updating it to be compatible with recent changes in master looks like a bit of work though.

**Comment by IllustratedMan-code** [comment]
The trick from the build in nixpkgs seems to be adding things to runtime dependencies. Unfortunately, I no longer have time to work on this, and it seems like it would take a lot of maintenance. I'll go ahead and close for now.

**Comment by turboMaCk** [comment]
nixpkgs currently package beta 10 https://github.com/NixOS/nixpkgs/pull/208160

and newly there is PR open for update to beta 14 https://github.com/NixOS/nixpkgs/pull/212156 So I would recommend all nixos user use version from nixpkgs.

**Comment by Ashvith10** [comment]
@turboMaCk can `dlopen()` be "patchelf-ed"? Or can I at least patch the path it points to, after the export?

I am trying to export project in Guix, but the game binary keeps failing. By patching the debug and release executable for x86_64, Linux in `$HOME/.local/share/godot/export_templates/4.5.stable/`, I was able to resolve the issue with `ld-linux-x86-64.so.2` by setting the interpreter from `/lib/ld-linux-x86-64.so.2` to `<path-to-glibc>/lib/ld-linux-x86-64.so.2`, but it still wouldn't run the way it was intended to.

```console
$ ./First\ Game.x86_64 
libfontconfig.so.1: cannot open shared object file: No such file or directory
Godot Engine v4.5.stable.official.876b29033 - https://godotengine.org
libX11.so.6: cannot open shared object file: No such file or directory
ERROR: Can't load Xlib dynamically.
   at: DisplayServerX11 (platform/linuxbsd/x11/display_server_x11.cpp:6741)
WARNING: Display driver x11 failed, falling back to wayland.
     at: setup2 (main/main.cpp:3220)
libwayland-client.so.0: cannot open shared object file: No such file or directory
WARNING: Can't load the Wayland client library.
     at: init (platform/linuxbsd/wayland/wayland_thread.cpp:4287)
ERROR: Could not initialize the Wayland thread.
   at: DisplayServerWayland (platform/linuxbsd/wayland/display_server_wayland.cpp:1903)
ERROR: Can't create the Wayland display server.
   at: create_func (platform/linuxbsd/wayland/display_server_wayland.cpp:1873)
ERROR: Unable to create DisplayServer, all display drivers failed.
Use "--headless" command line argument to run the engine in headless mode if this is desired (e.g. for continuous integration).
   at: setup2 (main/main.cpp:3230)
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: cleanup (core/object/object.cpp:2514)
```

When I try setting RPATH for `libx11` and `libfontconfig`, it starts throwing Segmentation Fault.
