### ISSUE TITLE
Sprite3D depth rendering does not work as intended with multiple overlapping Sprite3Ds.

### ISSUE THREAD

**Issue by SilencedPerson** [godotengine/godot#63182]
### Godot version

3.5 rc6

### System information

OpenGL ES 2.0 Renderer: Intel(R) HD Graphics 5500

### Issue description

Sprite3Ds do not respect depth properly.

### Steps to reproduce

1) Put 2 Sprite3Ds into the scene.
2) Set one of the Sprite3D's translation to (-1.5,0,2)
3) move the Camera around. Reproducible inside the editor's 3D viewport.

![image](https://user-images.githubusercontent.com/82024211/179670239-b7c9929f-4c69-44a7-8714-c8b082084a23.png)

### Minimal reproduction project

[minimal reproduction project.zip](https://github.com/godotengine/godot/files/9137692/minimal.reproduction.project.zip)
Press Right On you Keyboard to see the issue.

**Comment by lawnjelly** [comment]
Am guessing it is assuming that the `Sprite3D` has transparency (alpha). For alpha to work it has to sort the polys, rather than rely on z buffer. And sorting by poly / object for transparency often suffers from this sort of problem.

**Comment by SilencedPerson** [comment]
That is bad...
I was planning to use it for user generated panoramas.
If i may, what are my alternatives? Would rendering it onto a plane help with this?
