### ISSUE TITLE
HBoxContainer result looks different in editor and game

### ISSUE THREAD

**Issue by SkyfallWasTaken** [godotengine/godot#63196]
### Godot version

v3.4.4.stable.official.419e713a2

### System information

Windows 10, GLES2, Intel(R) HD Graphics 2000, latest driver version

### Issue description

In the editor, the back button is not right next to the "Options" text.
![image](https://user-images.githubusercontent.com/55807755/179740118-319dd5be-13ec-47e6-94f3-3593fab37b44.png)
But in the actual game, it is:
![image](https://user-images.githubusercontent.com/55807755/179740189-48d87b3e-51aa-4350-9ae7-d7a0f44f0355.png)

### Steps to reproduce

1. Open the repro project
2. Verify that the button is not near the text
3. Open the build and see that it's now near the text

### Minimal reproduction project

[ReproProject.zip](https://github.com/godotengine/godot/files/9140670/ReproProject.zip)

**Comment by Flavelius** [comment]
In the repro project, the icon is also next to the text - and expected to be, the way it's set up.
![grafik](https://user-images.githubusercontent.com/8841352/179916422-339f7928-460c-4fdd-8255-3d99a7b34c9e.png)

**Comment by SkyfallWasTaken** [comment]
That's weird, it's also working for me in both projects. The TextureButton left margin isn't saving for some reason (I set it to 40, but it keeps changing to 225) In the debug build however, it changes back to 225. This _could_ be a bug, but more likely I'm doing something wrong tbh

**Comment by Flavelius** [comment]
You're using a container here, this is supposed to override/control those properties based on the size flags of children. What you're trying to model (one control centered the other left aligned) requires a different hierarchy of containers

**Comment by Calinou** [comment]
Closing per @Flavelius's comment. This is expected behavior.

**Comment by SkyfallWasTaken** [comment]
Sorry for wasting your time then.
