### ISSUE TITLE
Dead link in documentation

### ISSUE THREAD

**Issue by Drachenfels** [godotengine/godot#632]
On this page:

https://github.com/okamstudio/godot/wiki/advanced

On bottom there is a link:

https://github.com/okamstudio/godot/wiki/external_editor

But pressing it leads to:

https://github.com/okamstudio/godot/wiki

WIth error message like:

"You do not have permission to update this wiki."

I guess it's not expected behaviour.

**Comment by akien-mga** [comment]
The page is indeed missing, I marked the link as striked through. The GH repo should retire soon anyway.
