### ISSUE TITLE
The file dialog for `New TextFile...` doesn't scope to the clicked project folder

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#63200]
### Describe the project you are working on

protos with 4.0

### Describe the problem or limitation you are having in your project

`FileSystem dock > RMB > New TextFile...` opens a file dialog without setting its open path to the clicked folder (it start at `res://` and then opens the last visited directory on subsequent popups).

(N.B.: the opened dialog is a global file explorer, which I reported as a bug, and therefore does not open `res://` but its global path equivalent)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Make the dialog start in the clicked folder (or of course the folder the clicked resource lives in).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

/

### If this enhancement will not be used often, can it be worked around with a few lines of script?

it will be used often

### Is there a reason why this should be core and not an add-on in the asset library?

its about making a feature usable

**Comment by mieldepoche** [comment]
> It also is not scoped to the project and uses full file system access instead

Global file system access is a feature aparently: https://github.com/godotengine/godot/issues/63155#issuecomment-1189334528

**Comment by Cretezy** [comment]
Video example:

https://user-images.githubusercontent.com/2672503/210655082-3d0055e9-c063-4736-9b1d-30ff685712f7.mp4
