### ISSUE TITLE
Vulkan: Toggling the SSAO Half Size option in Project Settings causes memory leak

### ISSUE THREAD

**Issue by xiaowangxu** [godotengine/godot#63202]
### Godot version

v4.0.alpha11.official [afdae67cc]

### System information

Windows 11, Vulkan, Nvida RTX 2080 Ti

### Issue description

when ssao is enabled and turn off the ssao/half_size option in Project Setting will cause memory leak
turn on half_size:
<img width="703" alt="HalfSizeOn" src="https://user-images.githubusercontent.com/45325000/179780200-35e6907c-036b-4301-bfec-74208fcecf6f.png">
turn off half_size:
<img width="670" alt="HalfSize" src="https://user-images.githubusercontent.com/45325000/179780311-4b92e0d9-18ed-4aaf-a241-8240e9ac26c7.png">
<img width="704" alt="HalfSizeOff" src="https://user-images.githubusercontent.com/45325000/179780336-906a6925-99aa-49b9-89eb-8a3d994b6d24.png">

### Steps to reproduce

Open any scene in godot. Enable SSAO in the WorldEnvironment, and toggle the ssao/half_size option in Project Setting and you will see the memory difference in the debugger

### Minimal reproduction project

[SSAO_Bug.zip](https://github.com/godotengine/godot/files/9142178/SSAO_Bug.zip)

**Comment by clayjohn** [comment]
Does the memory usage continue increasing each frame or does it only increase once and then stay static?

**Comment by SmartySmart702** [comment]
Tested for ~3 minutes and it increased continuously.

**Comment by SmartySmart702** [comment]
Same for SSIL. 
Even for this:
AO: on, half size on
SSIL: off, half size off 

Note that SSIL is disabled but "Half Size" of SSIL still causes a memory leak (because AO is enabled?)

**Comment by BastiaanOlij** [comment]
Hmmm, yeah would be good to check if my PR already deals with it or else see if I can fix it in there as any fix will probably be lost due to the merge conflicts not picking this up properly.

That said, the code for allocating and freeing buffers used by these effects was all over the place and should be more readable in my PR. It should be easier to check and see if we forget to free something.

**Comment by allenwp** [comment]
I just tested with [revision 0a420c4](https://github.com/godotengine/godot/commit/0a420c478761d49b5f973ff292e1f3e4a63613b3), which should include @BastiaanOlij's PR on a local debug build of the editor and was able to reproduce the memory leak with the minimal reproduction project. The leak happened when either SSAO or SSIL was enabled. When both were disabled, no measurable memory leak was shown in he Debugger Monitor.

**Comment by BastiaanOlij** [comment]
Thanks @allenwp , I'll have a closer look as soon as I can, most of my PR was restructuring, not changing how it works but it should be easier now to compare allocations and whether they are being freed up.

**Comment by BastiaanOlij** [comment]
Not sure if this could be related to this issue, it may be a flow on effect, but I couldn't find any memory leak in SSAO (yet, I'll do more testing).
I did find a leak in VoxelGI: #64139 which could be triggered as SSAO is triggered.

**Comment by BastiaanOlij** [comment]
Can this be re-tested on the latest master?

**Comment by allenwp** [comment]
@BastiaanOlij This time I tested using a `release_debug` build, built with MSVS 14.3 x86_64 and the latest official alpha release.

Memory leak reproduced using the reproduction project that is attached to initial comment of this issue on 0a420c478761d49b5f973ff292e1f3e4a63613b3, v4.0.alpha16.official [86dd3f312], and 79b21e96ad7a154e6c64a88150c98bd4dea52e91 (latest master).

**Comment by BastiaanOlij** [comment]
Thanks Allen, I'm going to try and see if I can reproduce it at this end.

**Comment by BastiaanOlij** [comment]
I think I fixed it, see PR #65738
