### ISSUE TITLE
Emitted signal with parameters unbound has incorrect error for unexpected argument count.

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot#63213]
### Godot version

v4.0.alpha.custom_build [d6b1dd485]
(Still reproducible following merge of dae5edf41c2287dea794c6a3a9d686479e71f10b)

### System information

Arch on 5.18.11-arch1-1

### Issue description

"Method expected 1 arguments, but called with 1.."
Can the extra `.` be fixed also?

```gdscript
extends Node

func _on_scene_child_entered_tree(_extraneous_parameter_unbound) -> void:
	print("hello")
```

```
E 0:00:04:0869   emit_signalp: Error calling from signal 'child_entered_tree' to callable: 'Node(scene.gd)::_on_scene_child_entered_tree': Method expected 1 arguments, but called with 1..
  <C++ Source>   core/object/object.cpp:1025 @ emit_signalp()
```

### Steps to reproduce

1) Bind signal child_entered_tree with 1 argument unbound.
2) Add an extraneous parameter to the callback.

### Minimal reproduction project

[test15.zip](https://github.com/godotengine/godot/files/9144311/test15.zip)

**Comment by Rindbee** [comment]
This **Receiver Method** is a manually modified function, not the automatically generated one.

For parameters in the final **Receiver Method** parameter list, if divided by where they come from, currently, they can be divided into **3** categories, as I explained with different colors in the picture of https://github.com/godotengine/godot/pull/60143#issuecomment-1095404236 (there, I added another one, the signal source, to increase flexibility of the connection dialog).

![1](https://user-images.githubusercontent.com/30386067/180094876-e0819c61-fc8e-4fa0-83d3-16e26cc35d19.jpg)

If the parameters are classified, the unbind here belongs to the parameters in the callable, and the **N** subsequent call parameters will be ignored. The effect eventually results in the removal of the last **N** parameters before the callable parameters in the parameter list.

**Comment by Rindbee** [comment]
The main reason is that Callable may be nested, so the cost of counting the number of parameters may be a bit large.

**Comment by bitwes** [comment]
Not 100% sure if this is the same issue, but if you bind an extra parameter when connecting you get the same kind of misleading error.  It says "expected X, but called with X" when it should be "expected X, but called with X+1"

The code:
```gdscript
extends SceneTree

signal the_signal(one)

func signal_callback(one):
    print(one)

func _init():
    var callback = signal_callback.bind("two")
    the_signal.connect(callback)
    the_signal.emit('foo')

    quit()
```
The error:
```
ERROR: Error calling from signal 'the_signal' to callable: 'SceneTree(demo_signal_parameter_error.gd)::signal_callback': Method expected 1 arguments, but called with 1.
```
