### ISSUE TITLE
NOTIFICATION_VISIBILITY_CHANGED is fired twice if the Control was initially not visible

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#63212]
### Godot version

5a6b13b8bb128a0e10cccab8f212b1ed15cea425

### System information

Windows 10 64 bits GLES3 GeForce GTX 1060 6GB/PCIe/SSE2

### Issue description

When I set `visible = true` on a PanelContainer that was initially not visible when starting the scene, it triggers the `NOTIFICATION_VISIBILITY_CHANGED` twice. It expected it to happen only once. Subsequent toggles of `visible` trigger the notification only once.

### Steps to reproduce

```
- Root (Node)
    - PanelContainer (hidden, with panel.gd)
```
panel.gd
```gdscript
extends PanelContainer

func _unhandled_input(event):
	if event is InputEventKey:
		if event.pressed:
			if event.keycode == KEY_E:
				visible = not visible

func _notification(what: int):
	if what == NOTIFICATION_VISIBILITY_CHANGED:
		print("Visibility changed ", visible)
```
Launch game, press E, observe:
```
Visibility changed true
Visibility changed true
```

### Minimal reproduction project

[VisibilityChanged.zip](https://github.com/godotengine/godot/files/9144120/VisibilityChanged.zip)

**Comment by Rindbee** [comment]
May be caused by this.
https://github.com/godotengine/godot/blob/8d15814e6a211646a04478978224fd1af41a75cc/scene/main/canvas_item.cpp#L74-L87
