### ISSUE TITLE
Vulkan: Using `NORMAL_ROUGHNESS_TEXTURE` causes the current shader to be invalid 

### ISSUE THREAD

**Issue by EIREXE** [godotengine/godot#63217]
### Godot version

e37525896e0000feecf1d556c67b652b7e8da3da

### System information

Arch Linux, RADV

### Issue description

using the `NORMAL_ROUGHNESS_TEXTURE` sampler in a spatial shader causes the shader compiler to return:

`   at: _compile_variant (servers/rendering/renderer_rd/shader_rd.cpp:280)
ERROR: Condition "!shader_singleton->shader.version_is_valid(version)" is true.
   at: set_code (servers/rendering/renderer_rd/forward_clustered/scene_shader_forward_clustered.cpp:169)`

The error seems to happen specifically because the NORMAL_ROUGHNESS_TEXTURE can be both a texture2DArray or a texture2D depending on whether or not USE_MULTIVIEW is defined:

`ERROR: 0:2086: 'sampler2D' : sampler-constructor first argument must be a *texture* type matching the dimensionality and sampled type of the constructor `

### Steps to reproduce

Write a shader
use `NORMAL_ROUGHNESS_TEXTURE`

### Minimal reproduction project

[ShaderMRP.zip](https://github.com/godotengine/godot/files/9144969/ShaderMRP.zip)

**Comment by EIREXE** [comment]
updated with new info

**Comment by stylemistake** [comment]
Here's a bit more info about it:

Source shader:

```glsl
shader_type spatial;

void fragment() {
  vec4 nr = texelFetch(NORMAL_ROUGHNESS_TEXTURE, ivec2(UV), 0);
  ALBEDO = vec3(nr.r, nr.g, 0.0);
}
```

Compiled output:

```glsl
vec4 m_nr=texelFetch(sampler2D(normal_roughness_buffer, material_samplers[1]), ivec2(uv_interp), 0);
albedo=vec3(m_nr.r, m_nr.g, 0.0);
```

Compilation error:

```
ERROR: Failed parse:
WARNING: 0:78: '' : all default precisions are highp; use precision statements to quiet warning, e.g.:
         "precision mediump int; precision highp float;" 
ERROR: 0:2084: 'sampler2D' : sampler-constructor first argument must be a texture type matching the dimensionality and sampled type of the constructor 
ERROR: 0:2084: '' : compilation terminated 
ERROR: 2 compilation errors.  No code generated.
```


However, if you look up how GI shader uses the buffer, you find this:

https://github.com/godotengine/godot/blob/b3bd08207032ca146319f4b25654bcddd31ee401/servers/rendering/renderer_rd/shaders/environment/gi.glsl#L597

Is using `material_samplers[1]` the correct thing to do?

PR that could be related: https://github.com/godotengine/godot/pull/54063

**Comment by marcosbitetti** [comment]
Remains in v4.0.beta.custom_build [98da707df]
