### ISSUE TITLE
Facebook SDK for Android

### ISSUE THREAD

**Issue by alketii** [godotengine/godot#6322]
Since networking is getting better in Godot, it is quite useful to have Facebook SDK, specially for Android.
It is a great tool for login and for finding players with ease.

https://developers.facebook.com/docs/android/

Thanks.

**Comment by Calinou** [comment]
[It's proprietary](https://github.com/facebook/facebook-android-sdk/blob/master/LICENSE.txt), so it should be done as an optional module.

**Comment by Calinou** [comment]
I'm closing this issue since this should be implemented as a module (or using GDNative). Third-party implementations already exist such as [xsellier/godotandroid](https://github.com/xsellier/godotandroid) and [SShin-NiL/shinnilfb](https://github.com/Shin-NiL/shinnilfb)
