### ISSUE TITLE
Visual scripting nodes have flipped names

### ISSUE THREAD

**Issue by samvila** [godotengine/godot#6325]
**Operating system or device - Godot version:**
Windows 7, 64 bit & Windows 10, 64 bit. Godot Alpha v2.2 (http://www.purpleorangegames.com/godot/)

**Issue description** (what happened, and what was expected):
The visual scripting nodes;  Get Variable and Set Variable seems to have flipped names. When adding a Get Variable node it shows: "Variable Set" and the node behaves as a node set, in the other side if you add a Set Variable node then the node looks like a get node instead.

**Steps to reproduce:**
Just add one get variable node and one set variable node, it's clear that they seem to be flipped in their names.

**Link to minimal example project** (optional but very welcome):

**Comment by reduz** [comment]
Plese revert, currently working on visual script and doing large changes

**Comment by akien-mga** [comment]
Well it should be trivial to rebase your own commit to fix the merge conflict that would arise... but OK, will revert.

**Comment by reduz** [comment]
I guess I should spend some time to Improve my git fu :/

**Comment by akien-mga** [comment]
Well here it would be relatively easy:
```
git commit -a 'Refactored stuff in VisualScript'
git pull --rebase
// git yells that there is a conflict in `modules/visual_script.cpp`
// open the file, ctrl+f "<<<<<", fix the conflict, save
git add modules/visual_script.cpp
git commit
git log  // should be all good
git push
```

**Comment by akien-mga** [comment]
Should I revert anyway, or do you want to drop by on IRC when you rebase and @bojidar-bg and I will make sure you can resolve the conflict without harm? :)
