### ISSUE TITLE
Button is pressed itself and non-stop

### ISSUE THREAD

**Issue by andresleonardobg** [godotengine/godot#63259]
### Godot version

3.4 estable and previous versions

### System information

windows 10, ryzen 5 3400g, integrated graphics vega 11

### Issue description

when a put a Control/BaseButton/Button node, just the button without any script, run the project, I clicked it the button and it pressed over and over itself and non-stop, the console dont give me any error. I think this is a error from my computer beacause I tested my project in other computer and every button works. So I hope find some help here to find out what happens. thank you.
![error](https://user-images.githubusercontent.com/70084357/180055251-e1860a3d-2d83-4822-9be7-4088e87d3279.gif)

### Steps to reproduce

> create new project
> add control node
> add child button node
> run it 
> test the button

### Minimal reproduction project
this is the project what I currently work
[project.zip](https://github.com/godotengine/godot/files/9152817/project.zip)

**Comment by Calinou** [comment]
I can't reproduce this on 3.5.rc 51e2c1990 (Linux) (running `scenes/test.tscn` in the MRP). It works as expected both when clicking and pressing <kbd>Space</kbd> (which presses the currently focused button as per UI conventions).

https://user-images.githubusercontent.com/180032/180070906-6cbfa0ed-6563-4bc2-a789-abd789b4dac0.mp4

**Comment by anderlli0053** [comment]
Maybe would be good to mention that solution somewhere in the docs...

**Comment by Calinou** [comment]
> Maybe would be good to mention that solution somewhere in the docs?

Unfortunately, I don't know where this could be documented.

**Comment by anderlli0053** [comment]
> > Maybe would be good to mention that solution somewhere in the docs?
> 
> Unfortunately, I don't know where this could be documented. This is a highly specific issue to encounter after all.

It is yes, but generally speaking, it should be documented somewhere that one should disconnect / reconnect or whatever, all the joysticks / controllers / gamepads to avoid having input sensory problems with Godot, specifically buttons and possibly other "pressable" GUI elements.

**Comment by Calinou** [comment]
> It is yes, but generally speaking, it should be documented somewhere that one should disconnect / reconnect or whatever, all the joysticks / controllers / gamepads to avoid having input sensory problems with Godot, specifically buttons and possibly other "pressable" GUI elements.

This is actually a bug: https://github.com/godotengine/godot/issues/45628
