### ISSUE TITLE
drag-and-dropping a scene to the viewport doesn't instance it as a child of the currently selected node anymore

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#63268]
### Godot version

4.0.alpha12 (works in 3.5.rc6)

### System information

linux

### Issue description

Drag and dropping a tscn file to the viewport instances it in the current scene.
It is added as a child of the root of the scene wereas it should be added as a child of the currently selected node.

### Steps to reproduce

1. drag a tscn file in the viewport in a scene where the selected node isn't the root.

**Comment by dzil123** [comment]
This is intentional, see #51011 and godotengine/godot-proposals#2381.

**Comment by KoBeWi** [comment]
Yes you need to hold Ctrl now.
