### ISSUE TITLE
`TileSet` doesn't expose methods involving custom data layer name

### ISSUE THREAD

**Issue by kleonc** [godotengine/godot#63276]
### Godot version

4.0.dev (a9e4eac7b965450234c7a4fb2de1346a23ca67f2)

### System information

N/A

### Issue description

You can't set/get/etc. the names of the custom data layers from scripting. [Example user trying to find these](https://www.reddit.com/r/godot/comments/w40o5w/is_there_any_way_to_get_the_names_of_a_tilesets/).

Methods for this are already available:
https://github.com/godotengine/godot/blob/a9e4eac7b965450234c7a4fb2de1346a23ca67f2/scene/resources/tile_set.h#L476-L485

But they're not binded/exposed, no idea if there's any reason behind this:
https://github.com/godotengine/godot/blob/a9e4eac7b965450234c7a4fb2de1346a23ca67f2/scene/resources/tile_set.cpp#L3356-L3360

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by groud** [comment]
That looks like an oversight, I don't see why those functions could not be exposed.
