### ISSUE TITLE
Resolution on tiled 3 monitor setup

### ISSUE THREAD

**Issue by Larpon** [godotengine/godot#6327]
**Operating system or device - Godot version:**
Kubuntu 16.04 non-horizontal 3 monitor setup - Godot version 2.1 stable

**Issue description** (what happened, and what was expected):
The resolution of the Project Manager and editor is pixelated, compact and unusable:

Image here is from a 1920x1080 resolution
![image](https://cloud.githubusercontent.com/assets/768942/18066050/e7ef6202-6e36-11e6-8ec7-3e098bc1cd4f.png)

**Steps to reproduce:**
Issue arises with this monitor setup
![image](https://cloud.githubusercontent.com/assets/768942/18065834/ef2aba40-6e35-11e6-8457-1f9e6efb09dc.png)

**Comment by Hinsbart** [comment]
Could be a duplicate of #6096.
Does this also happen using one of these monitors alone or just in mult-monitor mode?

**Comment by Larpon** [comment]
@Hinsbart I think it's a duplicate - I've checked on a single monitor and it's the same problem - I haven't got any libXrandr errors though. I assumed (wrongly) it was the 3 monitor setup :) - closing as it is a very likely duplicate of #6096
