### ISSUE TITLE
The script editor has sudden interruptions with the writing of text

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#63274]
### Godot version

v3.5.rc6.official [f05cecdc4]

### System information

win10 64

### Issue description

In the script editor, if you hold down a key to repeat a letter, you notice that the repeat breaks, then the repeat continues.
These interrupts occur even if you don't hold down the key, that is, even if you are typing code at normal speed, you will notice these interrupts.

This doesn't happen in notepad.

https://youtu.be/x8EbcdoEYVc

Edit 1 hour later:
Now it seems to be working properly, I have no idea what could have caused those interruptions.

### Steps to reproduce

See the video

### Minimal reproduction project

...

**Comment by Calinou** [comment]
>  Now it seems to be working properly, I have no idea what could have caused those interruptions.

Do you have a gamepad connected? Did you accidentally enable Sticky Keys by pressing <kbd>Shift</kbd> 5 times in a rapid succession?

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
