### ISSUE TITLE
SpinBox signal "mouse_enter" - it's incorrect works

### ISSUE THREAD

**Issue by DimitriyPS** [godotengine/godot#6328]
**OS All / Godot 2.1:**

![00000](https://cloud.githubusercontent.com/assets/11189223/18079032/5edc9870-6e97-11e6-9b4a-588e026ca169.png)

In the screenshot I pointed out the green area of the component where the signal "mouse_enter" works, red area of the component where the signal "mouse_enter" does not work. I understand that the is a combined component. Nevertheless, I expect that the signal will work on the entire area of the component.

I attach the demo:
[DEMO.zip](https://github.com/godotengine/godot/files/444194/DEMO.zip)

**Comment by groud** [comment]
I think #19785 should be fixed in order to resolve this issue.
