### ISSUE TITLE
--convert-3to4 messes up thread arguments

### ISSUE THREAD

**Issue by and3rson** [godotengine/godot#63292]
### Godot version

4.0-alpha12

### System information

ArchLinux

### Issue description

```
# Before --convert-3to4:
thread.start(self, "_load_scene", [map_filename, target_spawn])

# After:
thread.start(self,Callable("_load_scene",[map_filename),target_spawn])

# Expected output:
thread.start(Callable(self, "_load_scene").bind(map_filename, target_spawn))
```

### Steps to reproduce

1. Create a project in Godot 3.x which uses `Thread.new().start` with bound parameters
2. Run Godot 4.x with --convert-3to4
3. Observe incorrect Callable syntax

**Comment by Calinou** [comment]
cc @qarmin
