### ISSUE TITLE
Script editor right click menu Clear bug

### ISSUE THREAD

**Issue by jtaart** [godotengine/godot#6329]
Godot version:  Godot_v2.1-stable_win64

Issue description: 

In the script editor right click menu there is an option to clear the whole script. When you click this there seem to be no way to recover your script. 

-all the undos seem to be wiped
-also if you close with out save, the gdscript text file is still cleared 

I lost a couple of hours of work, but if I was someone that did not back up stuff a lot, it could have been a disaster.  

video:  [https://youtu.be/6S7uuFptb0U]

**Comment by Hinsbart** [comment]
This has been (incidentally) fixed by #6640.
