### ISSUE TITLE
--convert-3to4 incorrectly escaping quotes when using signal yields

### ISSUE THREAD

**Issue by and3rson** [godotengine/godot#63291]
### Godot version

4.0-alpha12

### System information

ArchLinux

### Issue description

`--convert-3to4` improperly escapes quotes when converting `yield(obj, "signal")` to `await obj.signal` format:

```gdscript
# Original:

[sub_resource type="GDScript" id=269]
script/source = "extends ColorRect
# ...
    yield(self.fade_out(), \"finished\")
# ...
"

# After conversion:
[sub_resource type="GDScript" id=269]
script/source = "extends ColorRect
# ...
    await self.fade_out().\finished\
# ...
"
```

This leads to a broken escape (`\f`) in the editor:

![image](https://user-images.githubusercontent.com/190107/180276551-cdf82d32-a743-4d6b-ab7d-89b8d80c19c1.png)

### Steps to reproduce

1. Create a project in Godot 3.x that uses `yield(obj, signal)` syntax
2. Run Godot 4.x with `--convert-3to4` parameter
3. Observe broken quote escapes

**Comment by Calinou** [comment]
`2to3`? Isn't it `3to4`?

**Comment by and3rson** [comment]
> cc @qarmin
> 
> PS: `2to3`? Isn't it `3to4`?

Sorry, you're right. Those were terrible flashbacks from Python 3.x times.

**Comment by and3rson** [comment]
There seems to be a test covering this in 24f45bd533c, but it still seems to reproduce
