### ISSUE TITLE
Arrays in resources dont save in the inspector if they are a tool script

### ISSUE THREAD

**Issue by AlaraBread** [godotengine/godot#63301]
### Godot version

4.0 alpha 12

### System information

Ubuntu 22.04

### Issue description

If I create a resource with a tool script and an exported array, and edit it in the inspector, it does not save the values in the array when closing and reopening the scene.

The same issue does not happen if it is not a tool script.
The same issue does not happen for exported ints, or exported dictionaries.

### Steps to reproduce

Create a resource with this script:
```gdscript
@tool
extends Resource
class_name MyResource

@export var my_property:int = 0
@export var my_array:Array[int]
```

and a scene with this script
```gdscript
extends Node2D

@export var my_resource:Resource
```

Set the resource in the inspector.

Then, add some elements to the array.

Press ctrl+s to save the scene.

Then, close the scene and reopen it.

The data that you entered into the array is now gone.

### Minimal reproduction project

[ResourceBug.zip](https://github.com/godotengine/godot/files/9163426/ResourceBug.zip)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/50920.

This may be a duplicate of another issue, but I can't find it right now.

**Comment by AlaraBread** [comment]
This no longer occurs in RC1
