### ISSUE TITLE
Cannot compile on Debian: UnsupportedVersion: Unknown version None

### ISSUE THREAD

**Issue by qianjunakasumi** [godotengine/godot#63305]
### Godot version

4.0-alpha12 (2c11e6d9efc42370a8d7537eaff8b1ea78a283e5)

### System information

Debian 11 (5.10.0-15-amd64)

### Issue description

Trying to generate the solution (https://docs.godotengine.org/en/latest/development/cpp/configuring_an_ide/visual_studio.html)  on Debian 11, but got `UnsupportedVersion: Unknown version None`

![image](https://user-images.githubusercontent.com/53565118/180355816-4d0a3b85-767f-439d-9e4b-1a4ab195993b.png)

I also referred to the following information: https://docs.godotengine.org/en/latest/development/compiling/compiling_for_windows.html#development-in-visual-studio-or-other-ides 
and some issues, but in vain.

Any help is appreciated.

#### Version

scons: `v4.3.0` (also tried in `v4.0.1`)

mingw-w64: `8.0.0-1`

![image](https://user-images.githubusercontent.com/53565118/180358604-62aac7f6-3360-4926-9577-f4d821557117.png)
![image](https://user-images.githubusercontent.com/53565118/180358636-c3483cba-d386-4a72-91d1-d0b6670553c5.png)

### Steps to reproduce

`scons -j32 platform=windows vsproj=yes use_mingw=yes`

**Comment by akien-mga** [comment]
There's no Visual Studio on Linux, so you wouldn't be able to use this.

**Comment by qianjunakasumi** [comment]
It is recommended to state this in the documentation to avoid more people getting stuck like me.  Thanks for your help!

**Comment by akien-mga** [comment]
> It is recommended to state this in the documentation to avoid more people getting stuck like me.

You might have missed it but I think it's explicit enough in the intro?

![image](https://user-images.githubusercontent.com/4701338/180409172-3dbed232-eb10-42f3-9eb8-8b48c56eb81f.png)

We should still fix the fact that it throws a Python error though, we can prevent using this option when we know it can't work.

**Comment by qianjunakasumi** [comment]
Maybe I thought mingw should do the job because of `platform=windows`, but I was wrong, it only uses  VS

**Comment by akien-mga** [comment]
To clarify, to cross compile for Windows on Linux, you will indeed use MinGW. That's the only option available, MSVC (Visual Studio compiler) is only available on Windows.

The relevant documentation for you is https://docs.godotengine.org/en/latest/development/compiling/compiling_for_windows.html#cross-compiling-for-windows-from-other-operating-systems (cross-compilation). Though it might be partially outdated, I don't think you need to setup those `PREFIX` env variables anymore, it should Just Work™ with mingw-gcc installed.
