### ISSUE TITLE
Variant::can_convert doesn't work for STRING ?

### ISSUE THREAD

**Issue by touilleMan** [godotengine/godot#6331]
Hi,

Wandering into godot code, I reached [Variant::can_convert](https://github.com/godotengine/godot/blob/master/core/variant.cpp#L432):
```c++
bool Variant::can_convert(Variant::Type p_type_from,Variant::Type p_type_to) {
	...
	const Type *valid_types=NULL;
	const Type *invalid_types=NULL;
	...
	// set valid_types or invalid_types
	...
	if (valid_types) {
		...
	} else if (invalid_types) {
		int i=0;
		while(invalid_types[i]!=NIL) {
			if (p_type_from==invalid_types[i])
				return false;
			i++;
		}
	}
	return false;
}
```

It seems if `valid_types` is empty, `can_convert` can only return `false` no matter what `invalid_types` is.
I have the felling something's wrong here, isn't it ? :smile:

**Comment by akien-mga** [comment]
I guess the logic was that the last `return false;` should come after the while in the `if (valid_types)`, and there should be a `return true;` after the while in the `else if (invalid_types)`.
