### ISSUE TITLE
ProgressBar should reflect "allow greater" values in the percent label

### ISSUE THREAD

**Issue by Shou** [godotengine/godot#63311]
### Godot version

v3.5.beta.custom_build [3c0d32562]

### System information

NixOS

### Issue description

`ProgressBar` currently doesn't reflect values that exceed `max_value` when `allow_greater = true`, while sibling `Range` descendant `SpinBox` does correctly display values above `max_value` in this scenario. Does it make sense for `ProgressBar`s to display >100% labels when `allow_greater = true` and `percent_visible = true` given that `value` is clamped to `max_value` when `allow_greater = false` anyway and this is a visual component not really meant as a data store? (the only scenario I can think of where clamping the label to "100%" when `allow_greater = true` is useful is when someone wants to use it as a data store)

Relevant code:

* `3c0d32562` (my build): https://github.com/godotengine/godot/blob/3c0d32562b558b60abe382f2a132f4ea0f25b380/scene/gui/progress_bar.cpp#L66
    * Specifically `get_as_ratio()` since it clamps between `min_value` and `max_value`, we probably just want a `value / max_value * 100` instead here.
* `master`: https://github.com/godotengine/godot/blob/653f95282ccd31a4e38a157bb7845405079de371/scene/gui/progress_bar.cpp#L104

### Steps to reproduce

Set `allow_greater = true` and `value = 150` and the label doesn't match the value, it's clamped to "100%" despite `allow_greater = true`.

**Comment by Calinou** [comment]
I think allowing values larger than 100% to display makes sense, but make sure it doesn't mess up rounding when using large values. (In other words, "101%" shouldn't display when the value is actually 100% with large maximum value.)
