### ISSUE TITLE
`@onready` vars from inherited scripts are initialized after ones from the inheriting scripts

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot#63329]
### Godot version

master / 4.0 dev (tested on 79463aa5defb083569d193658a62755223f14dc4, but it's not a recent bug)

### System information

Ubuntu 22.04 x86_64

### Issue description

`@onready` vars from inherited scripts are initialized after ones from the inheriting scripts. This is wrong, it should be the other way around. The expected behavior is that the base class's `@onready` vars are initialized first.

### Steps to reproduce

Run the minimal reproduction project. The scripts below are copied from the reproduction project.

<img src="https://user-images.githubusercontent.com/1646875/180506930-df00462c-a658-4bab-b69e-e6e0a7126056.png" data-canonical-src="https://user-images.githubusercontent.com/1646875/180506930-df00462c-a658-4bab-b69e-e6e0a7126056.png" width="245" height="177" />

```gdscript
class_name Base
extends Node

@onready var child = $Child
```

```gdscript
extends Base

@onready var grandchild = child.get_node(^"Grandchild")

func _ready():
	print(grandchild)
```

Expected behavior: `child` from the base class should be initialized first, and then `grandchild` should be initialized.

Actual behavior: `grandchild` tries to initialize before `child` is ready, and Godot shows an error.

Some other tests you can do with this reproduction project:
* If you move `child` out of Base and into the top of the other script, it works.
* If you comment out `grandchild` and make the ready function print `child` instead, it works. This shows that `child` is indeed being initialized, but just too late. I found some other bugs about it not being initialized at all - this is not that bug.

### Minimal reproduction project

[TestOnReadyOrder.zip](https://github.com/godotengine/godot/files/9169886/TestOnReadyOrder.zip)

**Comment by jitspoe** [comment]
This is how the _ready functions work in general, and it has always kind of bothered me.  I keep expecting the parent's stuff to be ready by the time the child's _ready is called, but it's not.  You can work around it by setting variables in the _enter_tree() function, but there's no, like "@onentertree" -- maybe that would be a viable workaround, since changing the ready order would probably break a bunch of things.  Though maybe 4.x would be the time to make the change if it's going to happen.  I don't know.  I think this is more of a design discussion than a bug, though.

**Comment by aaronfranke** [comment]
@jitspoe That won't work, because accessing child nodes is only possible once those child nodes have been added to the tree. The parent is added before the children, so when `_enter_tree()` is run on the parent, the child nodes have not been added yet.

**Comment by jitspoe** [comment]
Interesting.  It worked in my case, but maybe it was because I was adding a premade scene with children, and those scenes get added with the children or something?
