### ISSUE TITLE
Input Events don't work on UWP (regression in 3.5.rc6 due to input accumulation being turned on by default)

### ISSUE THREAD

**Issue by ElCosmoXD** [godotengine/godot#63322]
### Godot version

v3.5.rc6.official [f05cecdc4]

### System information

Windows 11

### Issue description

If you run a exported project on UWP, The application will render the scene and will call the main functions like `_ready`, `_process`and `_draw`but if you try to get the events like `InputEventKey`or `InputEventMouseButton`using the `_input` function you won't get any event.

In this video you can see it, I'm pressing multiple keys but nothing happens:

https://user-images.githubusercontent.com/37759352/180492449-b44f3e73-1aea-4420-8ae0-de6299d70ab9.mp4

This is what you should see:

https://user-images.githubusercontent.com/37759352/180492815-be9295fb-d0a7-4f28-9ddf-490f699690a8.mp4

### Steps to reproduce

1- Create a Node and attach a Script to it (I tested this with GDScript and GDNative)
2- In the script add the `_input(event)` function
3- Print the `event` variable or try to check if the function was called.

### Minimal reproduction project

[UWP Project.zip](https://github.com/godotengine/godot/files/9169565/UWP.Project.zip)

**Comment by akien-mga** [comment]
Does it work if you call `Input.set_use_accumulated_input(false)` in the `_ready` of your main scene?
And does it work with 3.4.4 or 3.5 RC 5 or earlier?

CC @RandomShaper

**Comment by ElCosmoXD** [comment]
I tested calling `Input.set_use_accumulated_input(false)` and now it works, Thanks. 
And I couldn't test this on other versions but at least when you call the `Input.set_use_accumulated_input(false)` on Godot 3.5 RC6 works.

**Comment by akien-mga** [comment]
It's still a bug, it means accumulated input doesn't work on UWP, and now that it's the default, it's a problem.

**Comment by ElCosmoXD** [comment]
I just tried the sample project with Godot 3.4.4 and it works without calling `Input.set_use_accumulated_input(false)`, So as you say the accumulated input doesn't work on UWP at least in the version 3.5 RC.6.
