### ISSUE TITLE
Font.get_string_size() always return the same size without checking the font size, which has different behavior from Godot 3.x

### ISSUE THREAD

**Issue by meowyih** [godotengine/godot#63328]
### Godot version

v4.0.alpha12.official [2c11e6d9e]

### System information

Windows 11

### Issue description

In Godot 3.x, Font.get_string_size( string ) calculates the entire string size depends on font size. 
But in Godot 4.0, the same function always return the string size with default font size, which is 16px. Even I change font size to 64px or larger, I still get the same size as 16px one.

The problem happens in both Label and RichTextLabel.

### Steps to reproduce

1. Create a Label
2. Create a theme under that label
3. Add a "Label" type in theme and assign a normal_font to it.
4. Change the font size of "normal_font" from 16px to any larger size.
5. Attach a script and run the code below:

// this one works in both Godot 3 and Godot 4
print( $Label.get_combined_minimum_size() ) # return the correct size

// Godot 3.x code
// print( $Label.get_font("font").get_string_size($Label.text) ) # return the correct size

// Godot 4.0 code
print( $Label.theme.get_font("font", "Label").get_string_size($Label.text) ) # always return same size as 16px font

The exact same problem happens also in RichTextLabel. 
Since RichTextLabel cannot use get_combined_minimum_size() to get the correct string size, Font.get_string_size() is the only way to get it and has to be fixed.

### Minimal reproduction project

[Uploading GetStringSizeBug.zip…]()

**Comment by bruvzg** [comment]
Size is no longer property of the `Font`, it's completely independent. You can pass font size as a second argument to the `get_string_size`.

e.g., `print($Label.get_font("font").get_string_size($Label.text, $Label.get_font_size("font_size")))` 

See https://docs.godotengine.org/en/latest/classes/class_font.html#class-font-method-get-string-size

**Comment by bruvzg** [comment]
Edit: docs actually outdated a bit, in alpha 12 it includes alignment and width to allow getting size of the FILL aligned string, it should be:

```
print($Label.get_theme_font("font").get_string_size($Label.text, HORIZONTAL_ALIGNMENT_LEFT, -1, $Label.get_theme_font_size("font_size")))
```

**Comment by bruvzg** [comment]
Also, in case of `Label` you might want to use `get_multiline_string_size` instead (with the same arguments).
