### ISSUE TITLE
Allow specifying exit value on quit()

### ISSUE THREAD

**Issue by caryoscelus** [godotengine/godot#6333]
Might be not useful in games per se, but will be very useful for automated testing.

**Comment by profelis** [comment]
Just for fun, try to kill self process `OS.kill(OS. get_process_ID())` exit code should be equal to 143 or something near

**Comment by caryoscelus** [comment]
@profelis thanks, that actually would work for time being :D
Didn't know there was API to kill random processes in Godot.

**Comment by Calinou** [comment]
The `OS` singleton now has an `exit_code` property, which can be used to set the exit code the process will exit with when `get_tree().quit()` is called.
