### ISSUE TITLE
Inspector, Project Settings, Editor Settings retain scroll position across nodes/tabs, sometimes resulting in a blank space

### ISSUE THREAD

**Issue by snailrhymer** [godotengine/godot#63334]
### Godot version

v4.0 master [fe929d478]

### System information

popOS, Vulkan

### Issue description

When switching between nodes in the the scene tree, the scroll position of the last selected node seems to be used to set the scroll position of the newly selected node. When the new node's inspector doesn't have a scrollbar, this can mean the inspector appears empty:

https://user-images.githubusercontent.com/61291296/180580152-4f626106-660e-4e0b-828d-6f3f6dfbe89f.mp4

(note that dropdowns etc did appear - I had the recording software set to record the window)

Showing or collapsing a section in the inspector causes it to be redrawn correctly.

The bug doesn't happen in the "Node" tab - both signals and groups display properly.

Doesn't happen in alpha 12.

### Steps to reproduce

Scroll far down in the inspector on one node, then switch to another.

### Minimal reproduction project

-

**Comment by Rindbee** [comment]
I can reproduce it in 653f95282ccd31a4e38a157bb7845405079de371

**Comment by Rindbee** [comment]
Regression introduced by #63295.

**Comment by snougo** [comment]
this issue also appera in 3.5 rc7

https://user-images.githubusercontent.com/64188282/182329227-42371065-80a8-45cc-a5ff-b11b2618ce07.mov

**Comment by snailrhymer** [comment]
> this issue also appera in 3.5 rc7

Tested on [17e8fa863], and it's fixed for `3.x` now (see [here](https://github.com/godotengine/godot/issues/63417#issuecomment-1193872206)).
