### ISSUE TITLE
[3.5 RC 7] flicker on some materials when Shader Compilation Mode = Asynchronous + Cache

### ISSUE THREAD

**Issue by mrezai** [godotengine/godot#63346]
### Godot version

3.5 RC7

### System information

Ubuntu 22.04, GLES3, Geforce 1030

### Issue description

By runnig https://github.com/miskatonicstudio/intrepid in Godot v3.5-rc7, you can see some flickering(something like shadow) on cryopod's door in the start of the game when Shader Compilation Mode = Asynchronous + Cache.
I found out reverting of #62628 will fix the problem.

### Steps to reproduce

clone https://github.com/miskatonicstudio/intrepid and run it in Godot multiple times in Synchronous and Asynchronous Compilation Mode to see the difference.
The problem appears after showing this picture  and before door will be opened:

![Screenshot from 2022-07-23 18-40-18](https://user-images.githubusercontent.com/5120436/180608848-78eeac42-643d-4a3c-aff7-08618a52467d.png)

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
Fixed by #64096.
