### ISSUE TITLE
OptionButton text property doesn't load

### ISSUE THREAD

**Issue by GlaDOSik** [godotengine/godot#6335]
**Operating system or device - Godot version:**
Godot 2.1 stable 64 bit, Windows 7

**Issue description** (what happened, and what was expected):
OptionButton text property filled through editor doesn't load. It is saved to scene but when you load it again, it doesn't show. Setting text property in GDScript works fine.

[Sample project](https://drive.google.com/open?id=0B8mFWyZk6SLEdU5Qc2ZoeHFQZmc)

**Comment by vnen** [comment]
Can you provide a minimal sample project?

**Comment by GlaDOSik** [comment]
It's easy to test but yeah, no problem.

**Comment by vnen** [comment]
Looking better I'm not sure if this is really a bug. The text of an OptionButton is the selected option. Since you can't add options via editor, there's no text at all. This property is only available because it's inherited from the Button node.

**Comment by GlaDOSik** [comment]
I see. Thought it's the name of selector what is shown when nothing is selected. I'll close the issue then.
