### ISSUE TITLE
Export for Windows Desktop exits with code 1 when not using rcedit

### ISSUE THREAD

**Issue by and3rson** [godotengine/godot#63353]
### Godot version

3.5-rc6, 3.5-rc7

### System information

Ubuntu Latest (Ubuntu 22.04 LTS) in Docker

### Issue description

When exporting a Godot project in Docker (`ubuntu:latest`) with a headless binary, the following output is generated:

```
# ...
ERROR: Expected Image data size of 256x256x2 (without mipmaps) = 131072 bytes, got 174762 bytes instead.
# ...
WARNING: Resources Modification: Could not start rcedit executable, configure rcedit path in the Editor Settings (Export > Windows > Rcedit).
     at: add_message (editor/editor_export.h:251)
# ...
savepack: end
ERROR: Project export for preset "Windows Desktop" completed with errors.
   at: _fs_changed (editor/editor_node.cpp:814)
reimport: end
# ...
# exit code is 1
```

The build is still generated, but `godot` binary exits with code 1 and thus fails the CI pipeline. Temporary fix is to add `|| true` to suppress the error, but then you lose ability to detect **actual** build failures.

Strangely, I could not reproduce this on my main machine (which is also running Linux). The build is generated normally and the exit code is 0. Here are the logs from my host:

```
# ...
ERROR: Expected Image data size of 256x256x2 (without mipmaps) = 131072 bytes, got 174762 bytes instead.
        reimport: step 2: icon.png
Unicode error: invalid skip
Unicode error: invalid skip
rcedit (build/win/k3.exe): 002c:err:winediag:getaddrinfo Failed to resolve your host name IP

savepack: begin: Пакування steps: 102
        savepack: step 2: Збереження файлу: res://addons/antialiased_line2d/antialiased_line2d.gdc
        savepack: step 2: Збереження файлу: res://.import/antialiased_line2d.svg-9243613cd101e058db6c37ff468932c4.stex
# ...
# exit code is 0
```

Both Docker and host have `wine` installed and don't have `rcedit` installed, but the errors are different. I can't understand what's happening here. Any ideas why is the build failing? Is it due to `rcedit`?

### Steps to reproduce

1. Download & unpack the test project, then run `docker build -t test .`
2. The project is built successfully, but godot exits with code 1

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/9174277/test.zip)

**Comment by and3rson** [comment]
Updated description with a minimal reproduction project.

**Comment by bruvzg** [comment]
There is a new export config option to disable `rcedit`, `application/modify_resources` (change it to `false` to disable `rcedit`). When it's disabled, it won't print a warning and will have `0` exit code.

Related: https://github.com/godotengine/godot/pull/62907

**Comment by and3rson** [comment]
@bruvzg That worked, thank you! Also #62907 seems like a great solution, I wish it was merged earlier - that would have saved me a lot of time :)
