### ISSUE TITLE
[3.5 RC 7 Mac OS X] Please confirm it launches on Mac

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#63362]
### Godot version

3.5 RC 7

### System information

Mac OS X

### Issue description

After i download and unzip, I double click on Godot.app and I either get this message or nothing happens. Any thoughts? Mac log files show nothing related to godot

From Finder
![Screen Shot 2022-07-23 at 1 14 25 PM](https://user-images.githubusercontent.com/930478/180621395-f8fbf8d7-3fff-48f9-9eaa-2f34320af2a8.png)

From Forklift
![Screen Shot 2022-07-23 at 1 08 57 PM](https://user-images.githubusercontent.com/930478/180621311-1849269b-d704-4cab-a70b-025a9808cd35.png)

### Steps to reproduce

Download [Godot_v3.5-rc7_osx.universal.zip](https://downloads.tuxfamily.org/godotengine/3.5/rc7/Godot_v3.5-rc7_osx.universal.zip)

unzip and execute Godot.app

**Comment by Calinou** [comment]
Which macOS version are you using, and what Mac model do you have?

**Comment by wyattbiker** [comment]
Godot Worked on the previous 3.4.5 beta.

MacBook Pro
![image](https://user-images.githubusercontent.com/930478/180622107-a63b9e93-380d-4e24-8570-65f69a1208c9.png)

**Comment by wyattbiker** [comment]
Worked on previous godot 3.4.5 beta.

![image](https://user-images.githubusercontent.com/930478/180622209-1cd6f7b4-e952-466e-8240-51043d48300a.png)

**Comment by wyattbiker** [comment]
If it helps, I can manually run the godot executable in the Godot.app package contents (~/Downloads/Godot.app/Contents/MacOS/godot) . Shows the project list, but if I try to edit, it says missing files. Maybe will give you a hint.

**Comment by wyattbiker** [comment]
Tested backwards in time. The last one that works is Godot_v3.4.4-stable_osx.universal and Godot_v3.4.5-rc1_osx.universal

**Comment by ajreckof** [comment]
Just tried it on my M1 Mac there is no problem on the arm64 build at least.

**Comment by akien-mga** [comment]
Maybe the build got corrupted, the buildsystem has some memory issues sometimes. CC @bruvzg

**Comment by bruvzg** [comment]
> Maybe the build got corrupted, the buildsystem has some memory issues sometimes. 

It's working fine on macOS 12.4 (both native Apple Silicon and Rosetta).

**Comment by wyattbiker** [comment]
Hello, I re-downloaded the zip and tried it again and it works. v3.5.rc7.official [e71cf7c56]

Was there a rebuild? No change to my system not even a reboot. I will close for now.

**Comment by akien-mga** [comment]
There was no rebuild, your first download must have been corrupted.
