### ISSUE TITLE
Dependency editor doesn't work after editor restart

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot#63366]
### Godot version

v4.0.alpha.custom_build [667cef39b]
Not reproducible on 3.4.4.stable
Not reproducible on 3.5.rc7

### System information

Arch on 5.18.12-arch1-1

### Issue description

Before:
![image](https://user-images.githubusercontent.com/14253836/180622150-793cf0cd-fa12-45b2-a696-1543dbb17206.png)

After:
![image](https://user-images.githubusercontent.com/14253836/180622166-5e408c42-2605-43f5-b007-bd342b2c5f88.png)

### Steps to reproduce

1) Make a scene with a dependency
2) Rename the dependency externally
3) Restart the editor
4) Open the scene

### Minimal reproduction project

[empty.zip](https://github.com/godotengine/godot/files/9174624/empty.zip)

**Comment by Calinou** [comment]
Can you reproduce this on 3.x?

**Comment by nathanfranke** [comment]
Thanks for the suggestion. Not reproducible, updated post to reflect.
