### ISSUE TITLE
Navigation2DAgent 'velocity_computed' signal returns a Vector3 as safe_velocity

### ISSUE THREAD

**Issue by LakshayaG73** [godotengine/godot#63370]
### Godot version

3.5 RC 7

### System information

Windows 11

### Issue description

The description says it all, Navigation2DAgent 'velocity_computed' signal returns a Vector3 as safe_velocity. 

The signal connection via the editor also doesn't work, and i'm using Navigation2DServer.agent_set_callback(nav_agent.get_rid(), self, "_on_NavigationAgent2D_velocity_computed") to set it up. 

### Steps to reproduce

Straightforward to reproduce with any NavigationAgent2D in a NavigationRegion.

**Comment by Calinou** [comment]
cc @smix8

**Comment by smix8** [comment]
> The description says it all

That the Navigation2DAgent returns a Vector3 with the `velocity_computed` signal is not true so this needs an MRP.

**Comment by Mach565** [comment]
> > The description says it all
> 
> That the Navigation2DAgent returns a Vector3 with the `velocity_computed` signal is not true so this needs an MRP.

But it is true
https://github.com/godotengine/godot/blob/8a00d7c847931d6213201998c225785b3339224c/scene/2d/navigation_agent_2d.cpp#L107

**Comment by smix8** [comment]
This issue is created for Godot 3.5 RC7 which has a different PropertyInfo.

The Navigation2DAgent node converts the Vector3 avoidance velocity received from the NavigationServer to Vector2 before emitting the signal. This is done in both 3.5. and 4.0 master. The reason why Godot 4 has a Vector3 in the signal PropertyInfo is because GDScript2.0 for a long time was very stupid about everything. Maybe it is not needed anymore and can be replaced in Godot 4.0 but did not test.

**Comment by Mach565** [comment]
> This issue is created for Godot 3.5 RC7 which has a different PropertyInfo.
> 
> The Navigation2DAgent node converts the Vector3 avoidance velocity received from the NavigationServer to Vector2 before emitting the signal. This is done in both 3.5. and 4.0 master. The reason why Godot 4 has a Vector3 in the signal PropertyInfo is because GDScript2.0 for a long time was very stupid about everything. Maybe it is not needed anymore and can be replaced in Godot 4.0 but did not test.

Ah, my bad. You're correct about the Vector2 thing, sorry.

**Comment by LakshayaG73** [comment]
Perhaps it has something to do with how I'm connecting the signal? 

`Navigation2DServer.agent_set_callback(nav_agent.get_rid(), self, "_on_NavigationAgent2D_velocity_computed"`

**Comment by smix8** [comment]
The NavigationServer does not know that you are registering an avoidance agent intended for a 2D actor as all avoidance agents on the NavigationServer are technically 3D agents and there is no distinction. This is why by default the avoidance velocity signal with the Vector3 first lands on the Navigation2DAgent node with function  `_avoidance_done` which does the conversion to Vector2 and then emits the  `velocity_computed` Signal with the Vector2. If you do not connect to these functions and signals you need to do the Vector3->Vector2 conversion manually by omitting the y-axis of the Vector3.

**Comment by smix8** [comment]
@LakshayaG73
Could you solve the avoidance callback issue?

**Comment by LakshayaG73** [comment]
This issue is not a blocker for me as I am able to do the conversion manually and it works fine. 

However, is there something I can do while setting up my navigation system to not need this workaround?

**Comment by smix8** [comment]
If you create your own callbacks with the NavigationServer API the answer is no. The NavigationServer will always give you a Vector3. The conversion is only part of the NavigationAgent node when connected to the _avoidance_done() function.

So I guess we can close this issue?

**Comment by LakshayaG73** [comment]
Yes
