### ISSUE TITLE
AnimatedSprite3D: atlases do not work (+ example prj)

### ISSUE THREAD

**Issue by ret80** [godotengine/godot#6338]
**Operating system or device - Godot version:**
godot 2.1 Android

**Issue description** (what happened, and what was expected):
Atlases do not work for AnimatedSprite3D
Run example PC and Android  and see the difference.

**Steps to reproduce:**
1 create a AnimatedSprite3D.
2 add pictures to it
3 create an atlas of these frames
4 launch scene

**Link to minimal example project** (optional but very welcome):
https://yadi.sk/d/R6ToHiOZugfzS

**Comment by ret80** [comment]
add example project

**Comment by volzhs** [comment]
Adding screenshot would make more attention.

**Comment by ret80** [comment]
In the evening, I add screenshots.
PS
Screenshots do not understand why when there is a sample project :(

**Comment by akien-mga** [comment]
Because we all have a life, a work, and we can't just handle all issues in 5 days. Providing an example project is great, but it still won't guarantee that anyone will take some of their free time to test the issue. A screenshot makes it more visual and may help grab the attention of whoever thinks he could fix the bug.

**Comment by ret80** [comment]
ok

**Comment by ret80** [comment]
PC:
![image](https://cloud.githubusercontent.com/assets/233268/18256434/0f03a31c-73be-11e6-88ed-fb08c756ff18.png)

Android:
![screenshot_2016-09-05-23-13-32](https://cloud.githubusercontent.com/assets/233268/18256946/c00dc31c-73c4-11e6-93f7-bc1b51a57611.png)

**Comment by ret80** [comment]
found out the reason why this is happening.
``` 
void AnimatedSprite3D::_draw() {

Vector2 uvs[4]={
		final_src_rect.pos / tsize,
		(final_src_rect.pos+Vector2(final_src_rect.size.x,0)) / tsize,
		(final_src_rect.pos+final_src_rect.size) / tsize,
		(final_src_rect.pos+Vector2(0,final_src_rect.size.y)) / tsize,
	};
```
tsize is equal to the size of the frame rather than atlas.

**Comment by bojidar-bg** [comment]
Is this issue still present on master, and if so, shouldn't we fix it already :wink:

**Comment by Calinou** [comment]
This appears to have been fixed by https://github.com/godotengine/godot/commit/91140904ccb79f1e5db4daf3bde70e24d406b0c7 a while ago, closing.
