### ISSUE TITLE
The problem of garbled codes in zip

### ISSUE THREAD

**Issue by zuiaiyangyang3** [godotengine/godot#63386]
### Godot version

3.3.4

### System information

win10

### Issue description

Project export .zip package.
Why the code is garbled. Can you fix it?
The Chinese file name is used.

Forget it if the variable can't be used.
The file name should always let me use the Chinese name.
![image](https://user-images.githubusercontent.com/61361272/180643502-fe302f6a-04cf-48fa-8636-a6cd8c18c222.png)

### Steps to reproduce

The problem of garbled codes in zip

### Minimal reproduction project

The problem of garbled codes in zip

**Comment by Rindbee** [comment]
I guess it should be an encoding and decoding problem, `UTF8` is used in some places, and `GBK` is used in others.

**Comment by Calinou** [comment]
@zuiaiyangyang3 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
