### ISSUE TITLE
Basis.toAxisAngle return NaN as angle

### ISSUE THREAD

**Issue by fabriceci** [godotengine/godot#63397]
### Godot version

4.0.dev #b3df275

### System information

MacOS 11.6

### Issue description

When the rotation angle is very small, the angle returned is NaN.

### Steps to reproduce

In c++:

```c++
Basis bugNan(1.00000024, 0 , 0.000100001693, 0, 1, 0, -0.000100009143, 0, 1.00000024);
bugNan.get_axis_angle(axis, angle);
print_line(angle) // NaN
```

**Comment by fire** [comment]
@TokageItLab did the quaternion verseion of this.

**Comment by TokageItLab** [comment]
Yeah I recall that I changed it to return an initial Quaternion `Quaternion(0, 0, 0, 1)` when AxisAngle is very small.

**Comment by fabriceci** [comment]
I found the issue in Basis, I will open a PR. The  `arcos()` function receive a value greater than one, so it returns `NaN`,  I clamped the value to avoid the issue. I was wondering if we could put a debug code to find this kind of problem for `arcos`/`arcsin`.
