### ISSUE TITLE
Add SRP (secure remote password) functionality to networking API

### ISSUE THREAD

**Issue by gau-veldt** [godotengine/godot#6341]
https://en.wikipedia.org/wiki/Secure_Remote_Password_protocol

Adding such functionality gives a way to have authenticated peers (and/or encryption) without requiring use of a "~~trusted~~expensive third party" (certificate authority).  "The SRP protocol has a number of desirable properties: it allows a user to authenticate themselves to a server, it is resistant to dictionary attacks mounted by an eavesdropper, and it does not require a trusted third party. It effectively conveys a zero-knowledge password proof from the user to the server."

The key form of the protocol may be used to provide lightweight encryption once session is authenticated, useful to stop MITM (peer impersonation and packet injection) attacks.  MITM is of particular relevance to mobile games (two words: ~~airport/restaurant~~open wifi).

PS: If Godot embeds OpenSSL the article above mentions OpenSSL 1,0,1 and higher has SRP support.  Of the listed libraries providing SRP, at least one of them has Godot-compatible MIT license (The Legion of the Bouncy Castle).

**Comment by est31** [comment]
I also have an implementation of SRP: https://github.com/est31/csrp-gmp

It doesn't rely on openssl or anything, only on libgmp, which is a much smaller library, and which has a mini version that can be easily bundled with software.

**Comment by mhilbrunner** [comment]
Godot 4.0 supports DTLS encryption with the ENet implementation (see https://godotengine.org/article/enet-dtls-encryption).

This should help against eavesdropping and MITM attacks.

If you need additional security in the form of authentication on top of that (and that is not specific to a certain game or use case), please submit a proposal for that in the proposals repository.

**Comment by est31** [comment]
DTLS is no replacement to SRP. Most importantly it requires certificates, which require domain names. Not everyone running domain names can provide certificates. Yes you could theoretically turn verification off but then you can't detect MITM attacks any more.

**Comment by Calinou** [comment]
@est31 Isn't game authentication typically performed against a REST API behind an HTTPS server nowadays?

**Comment by est31** [comment]
Sending passwords in the clear via REST is a big danger and should be avoided. If someone hacks your infra, they have access to all the passwords of your users. Better use dedicated protocols like SRP. You can run them over REST and HTTPS if you like.

> > Not everyone running domain names can provide certificates.
>
> What about Let's Encrypt?

Good point. But a) it's not easy especially for non technical people, aka the server operators, and b) not everyone running servers can get domain names. Let's encrypt doesn't give you certificates for ip addresses.

**Comment by Calinou** [comment]
> Sending passwords in the clear via REST is a big danger and should be avoided. If someone hacks your infra, they have access to all the passwords of your users.

Obviously, passwords should be hashed when they're stored in the database :slightly_smiling_face:

**Comment by est31** [comment]
@Calinou of course this should be done, but hashing doesn't help you if someone hacks the infra and reads the passwords of ongoing logins arriving from clients before they are being compared with values in the database. For the time period of the hack, any logins would be readable. I meant that.

**Comment by mhilbrunner** [comment]
>DTLS is no replacement to SRP

I didn't want to imply that it would be. But it does offer protection against MITM attacks and eavesdroppers.

If you need authentication beyond that, you will usually need to implement that yourself based on your needs, or use a third-party implementation or middleware like Firebase that offers such.

I know of no game engine that offers built-in SRP support (or other auth mechanisms).
If you want, you can also use C# in Godot to use C# libraries for this or GDNative to bind your own.

Still, if there is a general demand (and general solution) for this, there is the proposals process as mentioned above.

**Comment by josephbmanley** [comment]
Just popping in to say, I would love to see a SRP implementation in vanilla Godot.

**Comment by Calinou** [comment]
@josephbmanley Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.
