### ISSUE TITLE
Settings dialog sometimes hides options

### ISSUE THREAD

**Issue by rick551a** [godotengine/godot#63417]
### Godot version

Godot_v3.5-rc7_mono_win64

### System information

Win10 x64, Nvidia

### Issue description

Clicking on a settings category with a long list of options causes settings from another category to disappear.
Did not appear on 3.4.4 stable.

### Steps to reproduce

1)Open Editor Settings
2)Click a category on left with long list of options, like 'Highlighting'
3)Scroll down to bottom of 'Highlighting' options page
4)Now, click category 'Indent' on left
5)Notice options for 'Indent' category are not shown

This also works with Project settings:

 'rendering quality'->scroll down to bottom of ->then click '2D' catgeory below it

**Comment by Rindbee** [comment]
Appears to be the 3.x version of #63348.

**Comment by akien-mga** [comment]
Fixed by be50514 (reverting problematic commit for 3.5).
