### ISSUE TITLE
ItemList scrolling from GDScript - Impossible

### ISSUE THREAD

**Issue by DimitriyPS** [godotengine/godot#6343]
**All OS / Godot 2.1**

Judging from the discussion:
[linc](https://godotengine.org/qa/7535/richtextlabel-itemlist-scrolling-from-gdscript)

Impossible ItemList scrolling from GDScript. Although this functionality is obviously needed.

**Comment by eska014** [comment]
ItemList has scrolling though, for example the tile palette in the TileMap editor is an ItemList.
It shows up when there's not enough space to display all items

**Comment by DimitriyPS** [comment]
So I have a lot of items and the strip appeared. Then the user can perform operations on the ItemList. Now I need to scroll components ItemList at the beginning from GDScript. How to do it?

**Comment by GlaDOSik** [comment]
Yeah, ItemList needs function `get_v_scroll()` like RichTextLabel has.

**Comment by char0xff** [comment]
If anyone is reading this, in 3.0 there is <code>ItemList.ensure_current_is_visible()</code>, which is simpler and should work for most cases.

**Comment by Railwanderer** [comment]
@char0xff Dosen't work for me. Do I need to call it deferred?
I renamed my ItemList to Log, don't wonder:

$Log.add_item(m)
$Log.ensure_current_is_visible( )
