### ISSUE TITLE
Vulkan: Updating shader global sampler2D results in pink texture (works in 4.0.alpha10)

### ISSUE THREAD

**Issue by CoreAidan** [godotengine/godot#63442]
### Godot version

4.0.alpha12

### System information

Windows 10

### Issue description

when calling `RenderingServer.global_variable_set("global_var", value)` on an sampler2D I expected the global value to be updated with the new texture. but it instead results in a pink texture.

![image](https://user-images.githubusercontent.com/8986360/180817487-1f80fbe6-79ec-4a26-84a9-e91e64ea7d60.png)
![image](https://user-images.githubusercontent.com/8986360/180817833-9a90fdaa-dc95-42f2-a699-6890b5bf6e2c.png)
![image](https://user-images.githubusercontent.com/8986360/180817911-7731c3d2-cd3d-404e-91ad-51435d208cf4.png)
![image](https://user-images.githubusercontent.com/8986360/180817970-145276fb-95bf-4069-a64d-7450d92258c5.png)

NOTE: the sample project works as expected in 4.0.alpha10

### Steps to reproduce

1. create a new Shader Global with the type of sampler2D
2. add a shader with reference to the new shader global unifrom
3. override the global texture with a new texture via a script using RenderingServer.global_variable_set("global_var", value)
4. verify the new texture is now pink which is incorrect and should be the new texture

### Minimal reproduction project

[GlobalShaderUniformBug.zip](https://github.com/godotengine/godot/files/9182704/GlobalShaderUniformBug.zip)

**Comment by Calinou** [comment]
If you can [compile the engine from source](https://docs.godotengine.org/en/stable/development/compiling/index.html), you could look into [bisecting the regression](https://docs.godotengine.org/en/stable/community/contributing/bisecting_regressions.html) to greatly speed up troubleshooting.

**Comment by CoreAidan** [comment]
Sorry first time compiling Godot. I ended up bisecting the regression leading to this commit hash d2900429e81175a9f48240b180f1d8e3ab52865c

**Comment by akien-mga** [comment]
`create_from_image` is now static and returns an `ImageTexture`, check its updated documentation.

**Comment by CoreAidan** [comment]
It looks like creating the image via the static function does fix that issue.
![image](https://user-images.githubusercontent.com/8986360/181512956-110c210d-3895-490b-ad7b-927ab6094fe4.png)

also since retesting on the latest this issue seems to have been fixed using the function on a new class as well as calling the static function.
