### ISSUE TITLE
Editor crashes when trying to save scene with TextureProgress node

### ISSUE THREAD

**Issue by lonesurvivor** [godotengine/godot#6344]
**Operating system or device - Godot version:**
Windows 7, Godot 2.1 stable

**Issue description** (what happened, and what was expected):
Trying to save a scene while having a TextureProgress node in it crashes the editor. The debug window says:

> ERROR: Vector<class Variant>::operator []: Condition ' p_index<0 || p_index>=size() ' is true. returned: aux
> At: c:\projects\godot-builds\godot\core\vector.h:132

Tested it several times. It didn't happen once or twice out of about ten tries. 

It doesn't happen in the latest 2.2 alpha build. It also doesn't happen if I load a scene with the above elements from the 2.2 alpha build in the 2.1 stable and save it there. So it may be fixed already, but I found only #5599 about this bug, and that one got already fixed in 2.1. So i decided to report it anyway.

**Steps to reproduce:**
Make a new scene. Add a TextureProgress node as root node or as a child of a CanvasLayer. Save.

**Comment by MarianoGnu** [comment]
Please test it since i can't reproduce the issue

**Comment by sketchyfun** [comment]
I'll compile and test it when I get home from work later. Was the variable not being initialised before?

**Comment by MarianoGnu** [comment]
since initial value was 0 i didn't care about initialization on the class constructor, now i defaulted it to 0

**Comment by sketchyfun** [comment]
I've just compiled and tested it on windows and it seems to have fixed the problem for me :)
