### ISSUE TITLE
Mono build fails with invalid literal suffix 'i' (C3688)

### ISSUE THREAD

**Issue by antonWetzel** [godotengine/godot#63445]
### Godot version

4.0.dev (3bd74cd)

### System information

Windows 10

### System
MSVC version 14.3
arch: amd64
bits: 64

### Problem

    >scons p=windows tools=yes module_mono_enabled=yes mono_glue=no
does not compile

### Cause
```cpp
// modules\mono\mono_gd\gd_mono_marshal.h 265
MATCHES_Vector4i = (MATCHES_int && (sizeof(Vector4i) == (sizeof(int32_t) * 4i)) &&
```
throws error C3688 because `4i` has an unknown suffix

### Solution
use `4` instead of `4i` (see `Vector3i`)

```cpp
// modules\mono\mono_gd\gd_mono_marshal.h 271
MATCHES_Vector3i = (MATCHES_int && (sizeof(Vector3i) == (sizeof(int32_t) * 3)) &&
```

### Steps to reproduce

    >scons p=windows tools=yes module_mono_enabled=yes mono_glue=no
with a fresh clone

### Minimal reproduction project

      -

**Comment by antonWetzel** [comment]
Additional `>scons p=windows tools=yes module_mono_enabled=yes` fails, because `Join`, `IsEmpty` and `Stringify` are generated for `Vector4` and `Vector4i` without `Vector4` or `Vector4i` being defined.

**Comment by raulsntos** [comment]
#63219 added `Vector4`, `Vector4i` and `Projection` but the mono module hasn't implemented them yet so compilation will fail.
