### ISSUE TITLE
Switch block for VS

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#6345]
**Issue description** (what happened, and what was expected):
It would be awesome to have switch block in VS. For example can't imagine how to create readable State Machine implementation without such block. Let me illustrate this: 
![switch](https://cloud.githubusercontent.com/assets/6129594/18133187/e0d896aa-6f99-11e6-9d66-f31616ddd539.png)

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by profelis** [comment]
Will be great to add switch operator to GDScript too

**Comment by kubecz3k** [comment]
At current moment switch is present in VS. I remember it was even working, but currently it's impossible to use it. Closing this one, and will open new issue.

**Comment by kubecz3k** [comment]
@akien-mga just a note: at the time this was a valid feature request, so not sure about that archived label  :)

**Comment by akien-mga** [comment]
Right :)
