### ISSUE TITLE
The editor crashes when removing exported categories from a tool script 

### ISSUE THREAD

**Issue by MagdielM** [godotengine/godot#63455]
### Godot version

4.0.alpha12.official [2c11e6d9e]

### System information

Windows 10

### Issue description

In a tool script, removing a category exported using `@export_category` while an object that has this tool script attached is being inspected will crash the editor.

### Steps to reproduce

From a new project:

1. Create a tool script and attach it to whichever object it extends.
2. Use the @export_category annotation to add a category.
3. Export one or more properties.
4. Inspect the object with the tool script attached.
5. Remove the `@export_category` annotation.
6. Save the script.

From the reproduction project:

1. Open `new_resource.tres` in the inspector.
2. Open `TestResource.gd` and remove the `@export_category` annotation.
3. Save the script.

### Minimal reproduction project

[Tool Script Category Crash Repro.zip](https://github.com/godotengine/godot/files/9183851/Tool.Script.Category.Crash.Repro.zip)

**Comment by AntonioDell** [comment]
Hi, I would like to tackle this issue if I may :smile: 
I was able to reproduce this on linux Pop!_OS 22.04 with the given project, thank you for providing it!

**Comment by Calinou** [comment]
> Hi, I would like to tackle this issue if I may smile

Feel free to open a pull request for this :slightly_smiling_face:

**Comment by YuriSizov** [comment]
Seems to have been fixed by https://github.com/godotengine/godot/pull/63583.
