### ISSUE TITLE
It's impossible to create custom function without sequence port in VS

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#6346]
**Issue description** (what happened, and what was expected):
It would be nice if we could create 'getters' functions without sequence ports in VS. 
Take a look at "calculateCurrentState" function in script below:
![switch](https://cloud.githubusercontent.com/assets/6129594/18133297/435f279e-6f9a-11e6-919c-87eeff7127a0.png)

**Comment by reduz** [comment]
haha you rock, I was implementing exactly this right now

**Comment by bojidar-bg** [comment]
Was it implemented anyway? :laughing:

**Comment by akien-mga** [comment]
> Was it implemented anyway?

Ping.

**Comment by kubecz3k** [comment]
As far as I can tell this is still not working:
![vs1](https://cloud.githubusercontent.com/assets/6129594/26244185/0a587776-3c8f-11e7-874f-b3d986cd317f.png)

function that returns value:
![vs2](https://cloud.githubusercontent.com/assets/6129594/26244207/1b73e266-3c8f-11e7-9639-6053e12561f9.png)

**Comment by kubecz3k** [comment]
I realized I was testing this with quite old build of Godot. 
Sorry for eventual confusion.
I have compiled a75623f436c215e107ede321afa08a1897552deb and tested again, but the results are the same:
![vs3](https://cloud.githubusercontent.com/assets/6129594/26246319/d46e82fe-3c98-11e7-82ff-62f45ba78ed2.png)

**Comment by novemberist** [comment]
@kubecz3k possibly related to this issue? https://github.com/godotengine/godot/issues/9170 It just seems like custom functions never return anything in Visual Script, even if they are called in sequence.

**Comment by kubecz3k** [comment]
@novemberist might be true, we will need to recheck when any of those will be solved :+1:

**Comment by reduz** [comment]
I think @MarianoGnu was working on fixing custom functions (or was it someone else?)

**Comment by MarianoGnu** [comment]
Not me at least, but this is really weird, if you drag the property from inspectoy to add a getter instead of a SelfCall does it work?
