### ISSUE TITLE
'Sugar' conditional function VS block 

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#6348]
**Operating system or device - Godot version:**

**Issue description** (what happened, and what was expected):

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by kubecz3k** [comment]
sorry for this, dont think it's possible to delete issue entirelly

**Comment by SuperUserNameMan** [comment]
you are pardoned.

![obama_thanksgiving_turkey_pardon_2009](https://cloud.githubusercontent.com/assets/9801802/18134906/53ce1102-6fa0-11e6-897b-8927881e76e7.jpg)

**Comment by kubecz3k** [comment]
@SuperUserNameMan woooh what a relief! :D
