### ISSUE TITLE
Color's alpha is set to one when setting `h`, `s`, or `v`.

### ISSUE THREAD

**Issue by linkpy** [godotengine/godot#63487]
### Godot version

4a12

### System information

linux

### Issue description

```
func _ready() -> void:
	var col = Color(0.5, 0.5, 0.5, 0.5)
	print(col)
	col.h = 0
	print(col)
```

Outputs : 

``` 
(0.5, 0.5, 0.5, 0.5)
(0.5, 0.5, 0.5, 1)
```

### Steps to reproduce

See above

### Minimal reproduction project

See above

**Comment by akien-mga** [comment]
Regression in 4.0, it's fine in 3.x.
