### ISSUE TITLE
Numpad Home and End keys appear to do nothing

### ISSUE THREAD

**Issue by halfheart-games** [godotengine/godot#63485]
### Godot version

v4.0.alpha12.official [2c11e6d9e]

### System information

Manjaro Ruah 21.3.5

### Issue description

With Num Lock off, I expect the Home and End key on the numeric keypad to act like the dedicated Home and End keys on a full sized keyboard. Home (KP7) should move the cursor to the start of a line, and End (KP1) should move the cursor to the end of the line. Instead both keys appear to do nothing.

This is a problem on a laptop which only has the Home and End keys on the numeric keypad. I also tested on a full sized keyboard and got the same results.

With Num Lock on both keys produce the expected number.

### Steps to reproduce

- Open any script file in the editor
- Ensure Num lock is off
- Try using the Numpad Home and End keys on a line with at least one word on it

### Minimal reproduction project

[numpad_issue.zip](https://github.com/godotengine/godot/files/9189146/numpad_issue.zip)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/57826 and https://github.com/godotengine/godot/issues/31988.

**Comment by PucklaMotzer09** [comment]
I have tested this on v4.0.beta.custom_build [bbac8198f] (beta2) on Garuda Linux. This issue does not occur for me. I have a Razer Blackwidow keyboard. Without Num Lock the Home and End keys work as expected.

**Comment by akien-mga** [comment]
Fixed by #66773.
