### ISSUE TITLE
Error in AnimationPlayer 3D mappings

### ISSUE THREAD

**Issue by InkRobert** [godotengine/godot#63492]
### Godot version

3.5 rc7

### System information

Windows 11 Pro, GLES3 and Vulkan(for Godot 4.0)

### Issue description

AnimationPlayer has some bugs in the 3D space, namely, some functions are not displayed. In the video I demonstrated this error:

https://user-images.githubusercontent.com/91805483/181018652-0c18e482-fcc8-49b7-a42e-3563993299a4.mp4

### Steps to reproduce

Adding keys to the AnimationPlayer track

**Comment by Calinou** [comment]
@InkRobert Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

Also, can you reproduce this on 3.4.4?
