### ISSUE TITLE
rooms and portal seems broken

### ISSUE THREAD

**Issue by samuncle** [godotengine/godot#6349]
I'm trying to optimise my scene by using room and portals to separate the 3d scene into multiple areas. The objects inside the room are properly culled except when you look through the portal you can't see anything.

1) is this an issue with godot? 
2) or maybe I'm using portals in a wrong manner 

I posted an example in the qa 
https://godotengine.org/qa/6667/how-to-use-rooms-and-portals-in-3d

Sam

**Comment by LeonardMeagher2** [comment]
Going to pile onto this

1) Rooms "room" is misleading it requests an "Area" in the editor, states it needs to be a "Room" in the docs and actually needs to be "RoomBounds"

_needs area_
![image](https://cloud.githubusercontent.com/assets/1546044/18140275/a628bd9e-6f69-11e6-8c64-0e30dbdba1f1.png)
_docs say Room_
![image](https://cloud.githubusercontent.com/assets/1546044/18140293/b74bd99e-6f69-11e6-8756-0e292db1cea7.png)

2) When creating RoomBounds changing the Geometry Hint size crashes godot

_loading roombounds works, but changing Geometry Hint Size crashes_
![issue](https://cloud.githubusercontent.com/assets/1546044/18141055/dec60d48-6f6c-11e6-90f2-8bedf6538135.gif)

**Comment by samuncle** [comment]
Okay, but I still don't understand how to make it works. I created the scene and it seems to load a RoomBound. The issue is mainly we can't see through the portal. Is there an demo with a room working + a portal ?

**Comment by reduz** [comment]
rooms and portals are gone, so this is gone too.
they will be re-added in 3.1 with a completely different implementation

**Comment by tr0q** [comment]
Very frustrating. I just ran into this problem and now basically have to wait for a couple of years? How it's even possible to have a 3d engine without any occlusion culling

**Comment by reduz** [comment]
not a couple of years, but a few months. 3.0 will come out without a few things (GLES2, shader graphs and occlussion culling among other things), but this is high priority to add back afterwards

**Comment by reduz** [comment]
again, apologies. Godot 3 is a massive engine clean-up which needed to be done. We prefer to release a first version missing a few things than delay the release a few more months. We haven't had a major release in almost a year.

**Comment by tr0q** [comment]
Few months until 3.1? Sure, that's faster than expected. 
Those missing few things are really important for my current project. Anyway, I think it will take some extra time until 3.x will be usable and reliable (lack of docs, bugs, missing features etc), will it be possible to adopt new occlusion culling to 2.x, or internals it will be based on are way too different in 3.0?

**Comment by reduz** [comment]
@tr0q yeah the idea after 3.0 is making smaller releases more often

**Comment by LikeLakers2** [comment]
Apologies for bumping this issue, but 

>they will be re-added in 3.1 with a completely different implementation

Will this happen in 3.2, since 3.1 is in a feature freeze?
