### ISSUE TITLE
Specular values not working (as intended or at all)

### ISSUE THREAD

**Issue by WrobotGames** [godotengine/godot#63509]
### Godot version

v4.0.alpha12.official [2c11e6d9e]

### System information

Windows 11, Vulkan Desktop, Multiple Devices

### Issue description

When changing the specular value in a godot spatial shader, it is expected that the specular lightings-strength _(the specular reflection is part of this)_ changes. This does not work correctly in godot right now. 

_- Specular 0.5:_ is the default, there should be a specular reflection
_- Specular 0.0_: should look the same as specular disabled (I tested this in Blender Cycles, Blender Eevee, Unity and Unreal, so it's save to say that it should be this way)
_- Specular Off:_ There should't be a specular reflection

_Note: all boxes have roughtness set to 0.3_
### Toon specular Model
(This specular model did work correctly in godot 3.4.4)
As visible in the pictures there is absolutely no difference between specular 0.5 and 0.0, changing the specular value has no impact.
![image](https://user-images.githubusercontent.com/66079814/181093421-273a67ee-15cf-4908-badd-0df38aa9fdd2.png)
### SchickGGX specular model
With specular set to SchilickGGX (Default model). The specular reflection does become a bit lighter when lowering the specular. (This was also 'wrong' in godot 3.4.4)
![image](https://user-images.githubusercontent.com/66079814/181092351-044404d5-34ad-4197-93ae-8e1cf7b82a38.png)
### Why does this matter
It is impossible right now to get a mesh with one part with specular and another part without. An example is a terrain, where the cliffs would be specular and the grass texture wouldn't

### Steps to reproduce

Have a mesh with a low roughness (Not 0) with an omnilight above it. Look at the specular reflection, then change the specular, note the change (That isn't there)

### Minimal reproduction project

[Specular.zip](https://github.com/godotengine/godot/files/9192882/Specular.zip)
Open the Scene.tscn

**Comment by WrobotGames** [comment]
To add to the comparison with godot 3.4.4, every specular model worked correctly except SchickGGX.

**Comment by clayjohn** [comment]
This behaviour currently isn't a bug. Godot uses a more physically "correct" model while most other engines/Frameworks use specular to also adjust the strength of the specular lobe. That being said, I agree that Godot differs from every other major engine in this regard and it is causing users a lot of frustration.

The behaviour your looking for has been proposed in https://github.com/godotengine/godot-proposals/issues/4818 and was previously discussed extensively in https://github.com/godotengine/godot/issues/40753

Closing this as this feature proposal should be tracked in the feature-proposals repo.
