### ISSUE TITLE
VisualShader "connections" array doubles in size after external edits

### ISSUE THREAD

**Issue by RedMser** [godotengine/godot#63508]
### Godot version

4.0.dev (222e489d)

### System information

Windows 10

### Issue description

When editing a VisualShader externally (e.g. via Git operations) while the VisualShader is also open in Godot, re-saving it in Godot will double the length of the "connections" array.

This does not seem to happen for VisualScript files.

### Steps to reproduce

- Create a VisualShader file
- Add a single node and a connection. In my case, opening the file in a text editor shows following connections: `nodes/fragment/connections = PackedInt32Array(2, 0, 0, 0)`
- Keep the shader editor open, and simply save the shader file in your text editor (no changes are needed)
- When focusing Godot Editor again, it should detect a change and reload the file
- After reload, press Ctrl+S in Godot
- Reload the file in your text editor, it will now contain `nodes/fragment/connections = PackedInt32Array(2, 0, 0, 0, 2, 0, 0, 0)`
- Keep repeating this to rapidly multiply the size of your VisualShader file

**Comment by RedMser** [comment]
This happens because `VisualShader::_set` is used when reloading the resource. And inside, `connect_nodes_forced` is used, which does not check for the connection already existing.

Not sure what the correct solution would be, however.

**Comment by Calinou** [comment]
cc @Chaosus

**Comment by Chaosus** [comment]
I guess not much we can do beside adding a check to prevent this from happening.
