### ISSUE TITLE
Evaluate Selection returns invalid GDScript for Infinities/NaN

### ISSUE THREAD

**Issue by RedMser** [godotengine/godot#63503]
### Godot version

4.0.dev (835da447)

### System information

Windows 10

### Issue description

When using Evaluate Selection of script editor, it can return invalid GDScript when a function returns a positive or negative infinity, or NaN.

### Steps to reproduce

- Create new project
- Create a new script and open it. Enter following:
```
INF
-INF
NAN
```
- Select these three lines of code, press Ctrl+Shift+E, they turn into invalid GDScript:
```
inf
inf_neg
nan
```
- Same goes for functions that can return these values naturally, such as `linear2db(0)`.

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot/pull/53699 and https://github.com/godotengine/godot/pull/53698.
