### ISSUE TITLE
In single-window mode, "open script" dialog is tiny

### ISSUE THREAD

**Issue by RedMser** [godotengine/godot#63504]
### Godot version

4.0.dev (835da447)

### System information

Windows 10, 100% editor scale, second monitor with 125% DPI scale (but godot is on main screen with 100% DPI scale)

### Issue description

**When in single-window mode only**, the open script dialog is tiny and not centered: ![image](https://user-images.githubusercontent.com/5117197/181083261-5196b92e-1cbe-439e-acb4-9b812cac91d0.png)

For comparison, this is how the open scene dialog looks like in single-window mode: ![image](https://user-images.githubusercontent.com/5117197/181083393-3f28ae84-bd81-4201-b1ec-5105e841d05b.png)

And in multi-window mode, the open script dialog shows fine as well:
![image](https://user-images.githubusercontent.com/5117197/181083736-75108c56-903f-4f17-a8b9-ccc070e2e4f6.png)

### Steps to reproduce

- Enable single-window mode in the editor
- Open the create script dialog
- Click on either of the file selector buttons ![image](https://user-images.githubusercontent.com/5117197/181083156-2993eef6-c6c0-40e0-9c97-ba34362d7423.png)
- The open dialog appears at the top left corner with a small size, as in the first screenshot

**Comment by Calinou** [comment]
@redmser Can you reproduce this on 3.4.4?

**Comment by RedMser** [comment]
> Can you reproduce this on 3.4.4?

@Calinou No, the popup is as big as other file selectors. It is also a lot bigger than in all of the above screenshots (like 80% of the main window size).

**Comment by Calinou** [comment]
cc @KoBeWi

**Comment by KoBeWi** [comment]
The problem is that `get_visible_rect()` is a Viewport method and position is always (0, 0).

Maybe the method should be virtual and include position in Window's override. Or maybe a different method should be used.
(it dates back to the original multi-window support PR, not sure why you pinged me; ping reduz >_>)
