### ISSUE TITLE
Resizing window breaks Label3D when using "canvas_items" stretch mode due to font oversampling

### ISSUE THREAD

**Issue by RedMser** [godotengine/godot#63507]
### Godot version

4.0.dev (222e489d)

### System information

Windows 10, Vulkan Clustered

### Issue description

Label3D turns into white rectangles when resizing the window if using "canvas_items" stretch mode.

![image](https://user-images.githubusercontent.com/5117197/181090087-8b23d64a-331e-40ef-808e-5924ba449396.png)

### Steps to reproduce

To re-create the MRP:
- Create a simple 3D scene with camera pointing at a Label3D with text on it
- Set Project Setting `display/window/stretch/mode` to `canvas_items`

Now you have the same setup as the MRP. Finally to get the broken behavior:
- Launch the game and resize the game window

### Minimal reproduction project

[resize_window_label3d.zip](https://github.com/godotengine/godot/files/9192625/resize_window_label3d.zip)

**Comment by Calinou** [comment]
cc @bruvzg 

I remember encountering this during Label3D's development, but it was fixed back then.
