### ISSUE TITLE
GDScript 2.0: Cannot use default values with typed arrays

### ISSUE THREAD

**Issue by Kubulambula** [godotengine/godot#63502]
### Godot version

4.0.alpha12

### System information

Windows 10

### Issue description

When using typed arrays as type for function arguments you cannot use default values.

For untyped arrays this is not an issue
```gdscript
func _ready():
	foo()
	bar()

# OK
func foo(optional_arr: Array = []):
	print(optional_arr) # []

# Also OK
func bar(optional_arr: Array = [1]):
	print(optional_arr) # [1]
```

But when using typed arrays it always results in error.
`Type of default value for parameter "optional_typed_arr" (Array) is not compatible with parameter type (Array[ *INSERT TYPE* ]).`
```gdscript
func _ready():
	foo()
	bar()


func foo(optional_typed_arr: Array[Resource] = []):
	print(optional_typed_arr)


func bar(optional_typed_arr: Array[int] = [1]):
	print(optional_typed_arr)
```

### Steps to reproduce

Just copy and paste the above example to any project

**Comment by ajreckof** [comment]
I think this is a more general bug not sure if it has been reported yet but you currently can't assign an untyped Array to a typed array so this code will raise the same error: 
```
Var typed_array : Array[int] = [1]
```
Essentially it is because [1] is interpreted as an untyped array and there is not implicit conversion from untyped array to typed arrays

**Comment by MaasTL** [comment]
A small addition:
![Screenshot from 2022-12-06 14-27-14](https://user-images.githubusercontent.com/92362428/205927125-5ab25c7f-df7f-41d6-b4b9-24bc546cb170.png)
I'm using `PackedStringArray` but Error says `Array[String]`
