### ISSUE TITLE
Arranging GraphNodes when a self-connection exists crashes scene.

### ISSUE THREAD

**Issue by ThunderSmotch** [godotengine/godot#63501]
### Godot version

4.0alpha12 (2c11e6d9efc42370a8d7537eaff8b1ea78a283e5)

### System information

Windows 10

### Issue description

When working with GraphEdit and GraphNodes, if we have a node self-connecting -- where the connection goes from one of its output ports into its own input ports -- then selecting and arranging the nodes crashes the scene/editor.

This happens both when launching a scene or using an in-editor plugin. 
It also happens if the arranging is being called by pressing the button or by calling the function arrange_nodes().

Behaviour expected: Self-connections should be ignored in the rearrangement.

### Steps to reproduce

1. Create a scene with a GraphEdit node.
2. Add a child GraphNode and a child label to said GraphNode
3. Enable both right and left slots of GraphNode.
4. Add a script to GraphEdit and on_ready connect the GraphNode to itself.
5. Launch scene, select node and try arranging them by clicking the button. 
6. Scene crashes.

### Minimal reproduction project

[BugArrangeNodes.zip](https://github.com/godotengine/godot/files/9192028/BugArrangeNodes.zip)

**Comment by Calinou** [comment]
Can you reproduce this on 3.4.4 or 3.5.rc7?

**Comment by ThunderSmotch** [comment]
The function `arrange_nodes` is not available in neither of those releases.
It was added in (12fc3f1eefbe43a17e88f43f805e3c118459b7a8).

**Comment by akien-mga** [comment]
Fixed by #63838.
