### ISSUE TITLE
Calling _set() and using property assigning syntax is different

### ISSUE THREAD

**Issue by caryoscelus** [godotengine/godot#6351]
**Operating system or device - Godot version:**
both 2.1 official & latest git tested

**Issue description** (what happened, and what was expected):
With custom `_set`, it's possible to set "non-existing" (not defined by var) values by directly calling `_set()`, but not using normal assigning (`a.b = c` or `a["b"] = c`). As i understand `_set`, it is supposed to be equivalent to using assigning operator (it is, in fact, called when using operator, but then error is thrown).

**Steps to reproduce:**
- implement custom _get & _set
- try _set with name that is not defined via var => works
- try = with the same name => doesn't work: after calling custom _set, fails with "Invalid index" error.

**Comment by bojidar-bg** [comment]
I'm not sure about this... when you do `object.xxx` in GDScript, you don't do `object.get('xxx')`, even if you might use `.get('xxx')` on a normal variable, as they are implicitly listed as properties... (same goes for `.set`)

**Comment by Calinou** [comment]
This may not be a bug at all; should this be closed?

**Comment by vnen** [comment]
Is this still a problem? Note that you should return `true` from the `_set()` method to let the engine know the property exists.

**Comment by ThakeeNathees** [comment]
```
bool _set(property: String, value: Variant) virtual
Virtual method which can be overridden to customize the return value of set().
Sets a property. Returns true if the property exists.
```
the behavior is in the documentation, and this issue should be closed

**Comment by Calinou** [comment]
Closing per @ThakeeNathees' comment.
