### ISSUE TITLE
Visual shader connections are very hard to work with

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#63526]
### Godot version

v4.0.alpha.custom_build [c4389f774]

### System information

Linux Fedora, Radeon RX 590

### Issue description

Connecting pins in visual shaders is rather frustrating.
When shaders become of small-medium size ( 5+ nodes) already the zoom level required to work with it makes the connections super hard to work with.

### Steps to reproduce

Create a visual shader with some complexity, for example
![image](https://user-images.githubusercontent.com/7917475/181218785-641b9c68-35cd-4921-a426-273fe8d8fdf7.png)

I am reporting this as a bug because the usability is so impaired that I think it should count as a bug.

### Minimal reproduction project

This is the specific shader I'm working on ( License CC-BY-ND-NC 4.0 for now)

[CrystalAoEShield.zip](https://github.com/godotengine/godot/files/9197195/CrystalAoEShield.zip)

**Comment by QbieShay** [comment]
Of note, it seems somehow related to the panning of the view?
https://gfycat.com/breakablewigglybernesemountaindog

**Comment by Chaosus** [comment]
I'm not sure how to reproduce it:
 ![test](https://user-images.githubusercontent.com/3036176/181230003-cf476c39-74ee-4f3a-afa9-d4cceb8ea672.gif)
There were some problems with it in the past, but I thought I've fixed them on the past.. Maybe it's a `GraphEdit` issue - try to check `VisualScript` about it.

**Comment by akien-mga** [comment]
> Fixed in v4.0.alpha.custom_build [[c4389f7](https://github.com/godotengine/godot/commit/c4389f774a32c857d60bdb9ac2222a35a62763eb)]

I'm confused, that's the same version where you reported it as broken, what changed?
