### ISSUE TITLE
inconsistency in the error returned by the editor when calling str without arguments

### ISSUE THREAD

**Issue by ajreckof** [godotengine/godot#63539]
### Godot version

4.0£.alpha12

### System information

MacOS Monterey 12.4 MacbookPro with M1 chip

### Issue description

When calling `str()` without arguments the editor will return this error :
<img width="662" alt="Capture d’écran 2022-07-25 à 16 47 05" src="https://user-images.githubusercontent.com/66184050/181271458-70e9fe6b-581a-4fa4-8799-ff3352762fb1.png">

I'm not sure wether other functions might have the same problem. I tried a few like min max and print but none of them have this strange behaviour.

### Steps to reproduce

call `str()` without arguments

**Comment by fisher2470** [comment]
Seems like the definition for this function doesn't pass an expected value to CALL_ERROR_TOO_FEW_ARGUMENTS, I can add a pull request for this

**Comment by Calinou** [comment]
> Seems like the definition for this function doesn't pass an expected value to CALL_ERROR_TOO_FEW_ARGUMENTS, I can add a pull request for this

Feel free to open a pull request for this :slightly_smiling_face:

**Comment by fisher2470** [comment]
Pull request added here: https://github.com/godotengine/godot/pull/63546
