### ISSUE TITLE
GDScript 2.0: Cannot parse match with typeof() and enum constants from other script

### ISSUE THREAD

**Issue by cassandrus** [godotengine/godot#63535]
### Godot version

Godot Engine v4.0.alpha12.official

### System information

Windows 10

### Issue description

When enum from another script (**auto-load singleton**) is used as case for a match expression, it fails with "**Expression in match pattern must be a constant**".
Built-in enums like TYPE_STRING work as expected. Enums declared in the same script work too.

I've decided not to add this report as part of https://github.com/godotengine/godot/issues/52033 as error texts are different. Also, I've recently filed report to https://github.com/godotengine/godot/issues/44375 where I also had problems with enums from singleton but on static typing (**perhaps problems are related**).

_Followup:
I tried to use script that is declared through **class_name** insted of singleton auto-load script. It works this way. So the problem is only with singleton declarations (I;m starting to doubt if this is intended?)._

Error:
![image](https://user-images.githubusercontent.com/97176349/181256905-6575022d-7ba1-4f78-bf62-3348f4bef040.png)

### Steps to reproduce

Just use enum from another script. I've also added mini-project to save your time.

### Minimal reproduction project

[game-client_test2.zip](https://github.com/godotengine/godot/files/9199195/game-client_test2.zip)

**Comment by AntonioDell** [comment]
I'm looking into it :)

**Comment by AntonioDell** [comment]
@cassandrus @Calinou Actually after much debugging I think this may not be an error, it could be intended behavior.
In the example project, the autoload in Project settings is created from the GameSettings.tscn, not the GameSettings.gd.
When changing this to GameSettings.gd, the error dissappears.
Now I am unsure whether or not an enum declared in an autoloaded node should be global, the example in the documentation shows an autoloaded script, so if it is a feature, it is not explicitly stated in the documentation ([see here](https://docs.godotengine.org/en/latest/tutorials/scripting/singletons_autoload.html#global-gd)).

**Comment by cassandrus** [comment]
If it has common reason with [#44375](https://github.com/godotengine/godot/issues/44375) (and it's very much possible as it's the same project and "incorrecly enabled" auto-load singleton), it's still a bug as it shows "parser error" there instead of any sane explanation.
For about intended behavior, I'm not sure, maybe more experienced devs can say, but in case of [#44375](https://github.com/godotengine/godot/issues/44375), using these globals actually works in runtime without issues, so I don't see why it shouldn't work in parser.

**Comment by AntonioDell** [comment]
@cassandrus You are correct. In Godot 3 it was possible to set a node as autoload and have access to it's script variables. 
F.e. config.tscn has script config.gd, config.gd has variable base_url, config.tscn is set as autoload with name Config and the following would work:
`var specific_url = $Config.base_url + "/specific".
In Godot 4 we need to set config.gd as autoload for this to work.
This is definitely a bug and it is stated in the [docs](https://docs.godotengine.org/en/latest/tutorials/scripting/singletons_autoload.html): 
> Note that autoload objects (scripts and/or scenes) are accessed just like any other node in the scene tree.

This should be supported.

**Comment by MarianoGnu** [comment]
@cassandrus i don´t think your code example makes sense, when you call `typeof(x)` it will always return a value from `Variant::Type`, in this case `TYPE_INT` and if it ever enter a match condition it will be the one whose index matches with `TYPE_INT`

i think the right example would be 
```
var x = GameSettings.ActorPositionType.FLOOR
match x:
    GameSettings.ActorPositionType.FLOOR:
        print("floor")
    [...]
```
that being said, the error still occurs, i am wondering if it could have to do with the order in which the GdScript parser analizes the sources

**Comment by adamscott** [comment]
Could not reproduce on master (fcba87e) as I ran the MRP sucessfully, without any errors (neither the editor nor the runtime)! I consider this issue fixed. @akien-mga
