### ISSUE TITLE
EditorSpinSlider loses click hold if mouse moves outside of input box

### ISSUE THREAD

**Issue by tinmanjuggernaut** [godotengine/godot#63544]
### Godot version

4.0alpha12

### System information

Win 10/64 NVIDIA GeForce GTX 1060/PCIe/SSE2

### Issue description

When grabbing a slider in the inspector, you can click the circle and slide the values left and right. However if the mouse leaves the light blue box, the slider loses your held click. You then have to look away from the 3D viewport, then find and click the little circle again to resume adjusting the values. It's rather annoying when making adjustments to materials and many other items.

![image](https://user-images.githubusercontent.com/632766/181299262-9f25ee20-4913-495a-a43a-6cd566f1ed91.png)

Switching the editor to Single Window Mode has no effect.

### Steps to reproduce

Make a material, adjust the sliders, move the cursor outside of the input box, get annoyed.

### Minimal reproduction project

n/a

**Comment by Calinou** [comment]
Can you reproduce this in 3.4.4 or 3.5.rc7?

**Comment by tinmanjuggernaut** [comment]
Works as expected in 3.5. Slider retains click hold, as the mouse moves anywhere. So I can keep my eyes on the viewport and not worry about where the mouse is.

**Comment by DNKpp** [comment]
As a side note, range properties created via gdextension also suffer from this bug, thus it is not limited to that material slider.

**Comment by DNKpp** [comment]
As digging through the code, I found some potentially related issue
```cpp
void EditorSpinSlider::_grabber_gui_input(const Ref<InputEvent> &p_event) {
	Ref<InputEventMouseButton> mb = p_event;

	if (grabbing_grabber) {
		if (mb.is_valid()) {
			if (mb->get_button_index() == MouseButton::WHEEL_UP) {
				set_value(get_value() + get_step());
				mousewheel_over_grabber = true;
			} else if (mb->get_button_index() == MouseButton::WHEEL_DOWN) {
				set_value(get_value() - get_step());
				mousewheel_over_grabber = true;
			}
		}
	}

	if (mb.is_valid() && mb->get_button_index() == MouseButton::LEFT) {
		if (mb->is_pressed()) {
			grabbing_grabber = true;
			if (!mousewheel_over_grabber) {
				grabbing_ratio = get_as_ratio();
				grabbing_from = grabber->get_transform().xform(mb->get_position()).x;
			}
		} else {
			grabbing_grabber = false;
			mousewheel_over_grabber = false;
		}
	}

	Ref<InputEventMouseMotion> mm = p_event;
	if (mm.is_valid() && grabbing_grabber) {
		if (mousewheel_over_grabber) {
			return;
		}

		float scale_x = get_global_transform_with_canvas().get_scale().x;
		ERR_FAIL_COND(Math::is_zero_approx(scale_x));
		float grabbing_ofs = (grabber->get_transform().xform(mm->get_position()).x - grabbing_from) / float(grabber_range) / scale_x;
		set_as_ratio(grabbing_ratio + grabbing_ofs);
		update();
	}
}
```
The current code expects the user to press the left mouse button while simultaneously spinning the mouse wheel (for me this seems somewhat complicated). The common behavior of such a feature is to simply react on the mouse wheel spin when the cursor is over the slider. Can't imagine, that this is intended, but I wanted to ask before I do anything further.

**Comment by tinmanjuggernaut** [comment]
Should work exactly as Godot 3 IMO. Grab slider, it slides no matter where the mouse moves until released.

Independent of the mouse click, if the wheel is changed while the mouse hovers in the box, it should change the value.

I think it should ignore the mouse wheel if it's already clicked and held.

**Comment by Yogoda** [comment]
I confirm the fix in https://github.com/godotengine/godot/pull/63598 works.
