### ISSUE TITLE
Range-based objects (eg: ProgressBar) do not emit changed signal

### ISSUE THREAD

**Issue by ShadowKyogre** [godotengine/godot#6354]
**Operating system or device - Godot version:**

Arch Linux - version 2.2.r5266.1b80eda

The part after last dot refers to the git hash you should be looking at.

**Issue description:**

I tried connecting a Range's `changed` signal, but that never fires. However, the `value_changed` signal fires just fine.

**Steps to reproduce:**
1. Use a range node of any type
2. Connect a function to the `changed` signal
3. Set step, max, or min programmatically

**Link to minimal example project**:
https://github.com/ShadowKyogre/godot-tests_range-changed

**Relevant code in godot source code**:
https://github.com/godotengine/godot/blob/master/scene/gui/range.cpp

**Comment by reduz** [comment]
This is intended, you have value_changed for this, but this class is a mess and will be rewritten after 3.1 is out to make more sense.
