### ISSUE TITLE
Color Picker value box doesn't continuously update

### ISSUE THREAD

**Issue by tinmanjuggernaut** [godotengine/godot#63545]
### Godot version

4.0alpha12

### System information

Win 10/64 NVIDIA GeForce GTX 1060/PCIe/SSE2

### Issue description

Almost all aspects of the color picker update in realtime. Grab the color wheel circle, or any RGBA/HSV/RAW sliders and the selected color in the middle, and the tint of any viewport objects this material is applied to update in realtime as you move the mouse around. However the right lightness box marked in red only updates on `pressed` or `released`. Moving the mouse around does not update the color. If you switch to HSV, V does update the lightness, and it even updates the right side slider in realtime. Only that right box doesn't have realtime updates.

![image](https://user-images.githubusercontent.com/632766/181303130-87350e9c-246a-4bcb-86cd-14327018d3ff.png)

### Steps to reproduce

See above.

**Comment by Calinou** [comment]
Can you reproduce this in 3.4.4/3.5.rc7?

**Comment by tinmanjuggernaut** [comment]
3.5 does not have a value box on the right, nor a color wheel. All options update in realtime.

![image](https://user-images.githubusercontent.com/632766/181305911-1d4359df-0fd0-4564-a6b2-01bf7b25b6ec.png)

**Comment by Rindbee** [comment]
Caused by the code here:
https://github.com/godotengine/godot/blob/7281f0f2381394a33300901a04fba100c5af79d9/scene/gui/color_picker.cpp#L1001-L1005

It should be judged by `actual_shape`, not `current_mode`.
