### ISSUE TITLE
Godot website is down due to TuxFamily outage

### ISSUE THREAD

**Issue by DriftWare07** [godotengine/godot#63554]
### Godot version

3.4.stable GLES2

### System information

Not an editor issue

### Issue description

godotengine.org won't connect, and the mirrors are down. Because of this, It is no longer possible to download Export Templates and there are no other places to get them. Is the website under maintenance? I've run a few speedtests and my internet is fine...

### Steps to reproduce

go to godotengine.org.
The connection times out.

**Comment by Calinou** [comment]
TuxFamily is having an outage right now, and we have no ETA when everything will be back up.

**Comment by DriftWare07** [comment]
Thanks

**Comment by Calinou** [comment]
Reopening, as the website is still down right now.

**Comment by akien-mga** [comment]
It's back online: https://godotengine.org/

**Comment by Calinou** [comment]
Reopening, as the website is down again: https://www.tuxfamily.org/en/news/2022073100

**Comment by wjagodfrey** [comment]
Can I ask why the engine uses such an unreliable host? This isn't the first time this has happened.

Certainly detracts from the appeal of the engine if the site doesn't even stay up.

**Comment by Calinou** [comment]
> Can I ask why the engine uses such an unreliable host? This isn't the first time this has happened.

We went with TuxFamily because it was a low-cost option back when we had very limited funding. While we could move to another host by now, it would require a lot of time investment which we can't do just yet.

Uptime has historically been pretty good, but the heatwaves occurring in France and other countries are giving datacenters a hard time. This isn't exclusive to TuxFamily – even Google has been affected by this in the UK.

**Comment by Chaosus** [comment]
Seems it was fixed yesterday. Closed.

**Comment by serikmcc-dev** [comment]
As of today, I am also receiving a 500 internal server error on the godotengine.org site:

```
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at modo@staff.tuxfamily.org to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.
```

**Comment by Zireael07** [comment]
Too many people want to get 3.5 :P server went down some time ago
