### ISSUE TITLE
GDSHADER: Instanced uniform variable with shader hint color_source returns no value.

### ISSUE THREAD

**Issue by A-Lamia** [godotengine/godot#63566]
### Godot version

v4.0.dev.custom_build

### System information

Windows 10, Vulkan, GTX 780Ti

### Issue description

Instanced vector 3 with color_source hint returns no value while just a normal vector 3 with no color_source hint does. 
Instanced color_source should return the value picked from mesh instance.

### Steps to reproduce

Create a new shader with a instance uniform of vector 3 with color_source hint, add that variable to ALBEDO in fragment shader, apply material to mesh surface 0, adjust color on mesh instance to see no result.

### Minimal reproduction project

[shader_instance_bug.zip](https://github.com/godotengine/godot/files/9206057/shader_instance_bug.zip)

**Comment by JohanAR** [comment]
This might be the same issue that I ran into yesterday. Default values for color_source aren't applied, but if I set them using gdscript it works.

I think this regression was introduced between Thursday and Sunday last week, if that helps.

**Comment by A-Lamia** [comment]
It's not just default values but even instanced parameters.

**Comment by YuriSizov** [comment]
@Chaosus It seems https://github.com/godotengine/godot/pull/63766 didn't fix that, according to @A-Lamia

**Comment by JohanAR** [comment]
#63766 fixed my issue at least

**Comment by A-Lamia** [comment]
It's still not working, and if you duplicate something it's like it defaults to the last known value. This same project is also supplied above.
https://ss.lamia.io/i/godot.windows.opt.tools.64_XYzvqImFn.mp4

**Comment by A-Lamia** [comment]
@JohanAR Interesting, what is your build hash ?

**Comment by JohanAR** [comment]
@A-Lamia I'm on 9ec6de1767292b5cbc1ebdc7b262ef1d9c63df9a

Though I did realize we were doing slightly different things. It looks like you're using "Surface Material Override" for the Mesh, while I'm using "Material Override" for the GeometryInstance3D. I'm not sure how this is expect to work since the Shader Params seem to be associated with the GeometryInstance3D, though I would say it mostly seems to not be an issue either way for me.

Though for some reason Shader Params -> Color turns into x, y and z values, and stops showing an actual color, when I'm playing around in your project. Changing xyz still updates the material/shader in real time

**Comment by A-Lamia** [comment]
@JohanAR In my project only the second sphere is an instance with color_source the 3rd and 4th sphere is showing that the same functionality works with out the color_source hint just with x,y,z, and the first sphere is testing out floats.

**Comment by Chaosus** [comment]
I'm not sure, I understand - it's fixed for myself:
![bugfix](https://user-images.githubusercontent.com/3036176/182174681-bacc938b-6191-4e6f-8c62-9559dd647bc6.gif)

**Comment by A-Lamia** [comment]
> I'm not sure, I understand - it's fixed for myself: ![bugfix](https://user-images.githubusercontent.com/3036176/182174681-bacc938b-6191-4e6f-8c62-9559dd647bc6.gif) [ ![bugfix](https://user-images.githubusercontent.com/3036176/182174681-bacc938b-6191-4e6f-8c62-9559dd647bc6.gif) ](https://user-images.githubusercontent.com/3036176/182174681-bacc938b-6191-4e6f-8c62-9559dd647bc6.gif) [ ](https://user-images.githubusercontent.com/3036176/182174681-bacc938b-6191-4e6f-8c62-9559dd647bc6.gif)

are you on windows ? I did a fresh release build.

**Comment by A-Lamia** [comment]
@Chaosus it might be on my end, i did an other build just now and i can't even run godot now so i need to see what the hell just happened 
https://ss.lamia.io/i/godot.windows.opt.64_u8c6DoWPM.png

**Comment by A-Lamia** [comment]
@Chaosus Everything seems to be working fine.
