### ISSUE TITLE
Strange variable connection in VS

### ISSUE THREAD

**Issue by djrm** [godotengine/godot#6357]
I dont think this should be possible
![screenshot from 2016-08-28 19-15-09](https://cloud.githubusercontent.com/assets/1103897/18149572/885565e6-6fa6-11e6-831d-d4110f7a90d1.png)

**Comment by akien-mga** [comment]
Is it still possible, or was this fixed?

**Comment by djrm** [comment]
Still possible in the latest master

**Comment by bojidar-bg** [comment]
Can confirm as well :smile:
