### ISSUE TITLE
Assets are being distorted on monitors that are not a 16 * 9 aspect ratio when Window is on Viewport / Expand mode

### ISSUE THREAD

**Issue by Tekuzo** [godotengine/godot#63579]
### Godot version

v3.4.4.stable.official [419e713a2]

### System information

M1 Macbook Air 2020

### Issue description

I am working on a project that is going to be released on Mobile and on PC / Mac / Linux.

Following the [documentation here](https://docs.godotengine.org/en/stable/tutorials/rendering/multiple_resolutions.html?highlight=stretch#stretch-mode), I put my Stretch Mode to Viewport and the Aspect to Expand, and I have also set the base resolution of the game to 720 * 720, as I wish to support both portrait and landscape displays.

720p is a 16 * 9 resolution, and when I run my game on a 16 * 9 aspect display, the game looks pristine. But when I run my game on a monitor that has a 16 * 10 aspect ratio, there is some distortion of the assets.

Based on the documentation that I linked, the expectation is that if I have my Window settings set to Viewport / Expand, the engine is supposed to not scale the assets and instead show more of the negative space (kind of like a camera being pulled back from a subject). It seems that even on Viewport / Expand mode, some scaling is being applied to the textures and assets in the scene.

My Desktop PC has a Portrait and Landscape 1440p monitor
My laptop has a 16 * 10 monitor, which is where I see the distortion of the assets.

Here is the game running at 1440p landscape (no distortion)
![Linux No Distortion](https://user-images.githubusercontent.com/6944363/181521600-45de17cc-c31f-4028-9943-dd0d0495ea99.png)

Here is the game running at 1440p portrait (no distortion)
![Linux Port No Distortion](https://user-images.githubusercontent.com/6944363/181521721-50035d70-79ca-47ea-a1fc-34a7e22bdd8c.png)

Here is the game running on my laptop at 1440 * 900 (distortion)
<img width="1440" alt="Screen Shot 2022-07-21 at 8 56 40 PM" src="https://user-images.githubusercontent.com/6944363/181521905-e6c4fbc2-2a6a-4f1d-9a82-b6e3be1be834.png">

You can see the distortion in the lines being drawn on the game board, and on the text.

### Steps to reproduce

Start a new project, set its window size to 720 * 720
Put the Window mode on Viewport / Expand
Run the game on a monitor that has a different aspect ratio than 16 * 9

### Minimal reproduction project

I have attached a sample project that can be run to see the distortion when run in full screen on a monitor that is 16 * 10.

[Sample Project.zip](https://github.com/godotengine/godot/files/9210267/Sample.Project.zip)

**Comment by Calinou** [comment]
The distortion is due to uneven pixel scaling.

I suggest you use the `2d` stretch mode instead of `viewport` for your use cases.

**Comment by Tekuzo** [comment]
> The viewport stretch mode is meant to be used by pixel art games. I suggest you use the 2d stretch mode instead of viewport for your use cases.

My game's assets are pixel art, which is why I had the Viewport and Aspect settings set this way.

When I change the Stretch Mode to 2D from Viewport, the text starts to look better, but the lines drawn at the edges of the game board are still distorted.

![Screen Shot 2022-07-28 at 11 55 30 AM](https://user-images.githubusercontent.com/6944363/181584060-906ee045-c25f-41d3-a3db-399247d7801f.png)

I suppose that if nothing can be done, then I will just leave it as is. I suspect that most of my users will have a 16*9 display, and this will be a moot issue.

**Comment by Tekuzo** [comment]
I was under the assumption that if you had the settings set to Viewport / Expand that Fractional Pixel Scaling wouldn't happen because it would only scale if it was able to maintain the aspect ratio.

**Comment by Calinou** [comment]
You need to install and configure https://github.com/Yukitty/godot-addon-integer_resolution_handler.

**Comment by Tekuzo** [comment]
Ok, Thanks. I will try it out.

Should I close this issue then?

**Comment by Tekuzo** [comment]
Thank you very much for the assistance too. It is very appreciated.
