### ISSUE TITLE
Int parsed as float when loading a dictionary from JSON.

### ISSUE THREAD

**Issue by hetdegon** [godotengine/godot#6359]
**Operating system or device - Godot version:**
Ubuntu 16.04 64b, Godot version fc70824 (probably any previous version as well)

**Issue description** (what happened, and what was expected):
Integers in a dictionary loaded from JSON are unusable to reference indices in arrays, apparently, despite looking like an int, sounding like an int, etcetera, it's not an integer. This is a very serious issue that can cause endless hard-to-spot bugs in games if not handled with utmost care.

**Steps to reproduce:**
I am loading some data from json files. That data contains some integers that are used to reference an index in a normal array. 
If done from a regular, gdscript dictionary, (such as `var mydict  = { value = 5 }` then I can do `print(myarray[mydict.value])` and as long as there's an index 5 in the array, that will work, no problem.

The problem comes if I acquire the same dictionary (with "`value = 5`") from json. Then it will fail. After spending some time debugging the issue, I came to the conclusion that the only way to get it to work is to "cast" the json-provided integer (like `print(myarray[int(mydict.value)])`). Meaning that, somehow, value doesn't contain an integer despite it having no decimal part in the json file.

**Link to minimal example project** (optional but very welcome):
Demonstration of this bug as-is: [Node.tscn.zip](https://github.com/godotengine/godot/files/449041/Node.tscn.zip)
Demonstration that casting to int solves it: [Node2.tscn.zip](https://github.com/godotengine/godot/files/449045/Node2.tscn.zip)

**Comment by hetdegon** [comment]
After discussing it on IRC, it could be convenient for the built-in json parser to automatically handle numbers without decimal parts as integers. That would prevent this issue and make results more consistent.

**Comment by Zylann** [comment]
Please note the JSON standard doesn't defines int and float, just number. Externally-generated JSON may or may not do the difference, and possibly round floats making them look as ints or vice versa.

**Comment by hetdegon** [comment]
Since the whole issue came from the problem described in #6361, I'd better close this up to clean up spurious issues.
