### ISSUE TITLE
Godot 4 Alpha dont load projects

### ISSUE THREAD

**Issue by VictorRandall** [godotengine/godot#63591]
### Godot version

4.0 alpha versions, official releases in the archives

### System information

Linux Mint

### Issue description

i have already tried update everything, but every time i open a project in godot 4.0 i just crashes with the following message:
```shell  
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.alpha12.official (2c11e6d9efc42370a8d7537eaff8b1ea78a283e5)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] linux-gate.so.1(__kernel_sigreturn+0) [0xf7fceb70] (??:0)
-- END OF BACKTRACE --
================================================================
```
 but before that, it reports two errors:
 ```
 ERROR: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
	/usr/lib/x86_64-linux-gnu/libvulkan_intel.so: wrong ELF class: ELFCLASS64
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 247537936
   at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:159)
ERROR: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
	/usr/lib/x86_64-linux-gnu/libvulkan_radeon.so: wrong ELF class: ELFCLASS64
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 247537936
   at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:159)
 ```

### Steps to reproduce

[godot 4.0 alpha 12](https://downloads.tuxfamily.org/godotengine/4.0/alpha12/) is the most recent version that has this error, but it also happens with other versions of alpha builds

**Comment by akien-mga** [comment]
Can you provide more details on your system and OS version? You seem to be running an x86_32 version of Linux?

This hasn't been tested much, there might be bugs indeed.

**Comment by VictorRandall** [comment]
i have tried both 32 bits and 64 bits and it also has this same bug, but here is some info about what i am using:
![image](https://user-images.githubusercontent.com/63934726/181625924-61e5f438-8e20-4332-96ae-b56b6d387935.png)
here its in more details:
![image](https://user-images.githubusercontent.com/63934726/181626746-fedcbccf-6729-4184-93f3-a2942c508ad4.png)
![image](https://user-images.githubusercontent.com/63934726/181626538-2df8ee12-67b7-4639-972f-ce1933763258.png)

**Comment by akien-mga** [comment]
Your Linux Mint version is extremely old and its Vulkan drivers are basically broken. You should upgrade to a newer distro and that should solve it.

**Comment by VictorRandall** [comment]
oh ok

**Comment by Calinou** [comment]
Closing, as this isn't an issue we can resolve on our end until an OpenGL fallback is added (https://github.com/godotengine/godot/issues/58927).

**Comment by SLiV9** [comment]
> Your Linux Mint version is extremely old and its Vulkan drivers are basically broken. You should upgrade to a newer distro and that should solve it.

I don't see how the 2019 LTS release of a popular OS counts as "extremely old", seeing as Windows 10 was released in 2015 and Windows 7 still has significant market share.

I agree that this is unsolveable the without OpenGL fallback, though.

**Comment by akien-mga** [comment]
> I don't see how the 2019 LTS release of a popular OS counts as "extremely old", seeing as Windows 10 was released in 2015 and Windows 7 still has significant market share.

Well:

- Linux Mint 19 is based on Ubuntu 18.04.
- Ubuntu 18.04 likely got feature frozen sometime in late 2017.
- The Vulkan 1.0 **specification** was released in 2016. It took years for drivers to be compliant.

So in the context of Vulkan support, Linux Mint 19, Ubuntu 18.04 or Debian 9 are indeed too old. I wish those distros would provide newer Mesa versions but since they don't, users who care about gaming should definitely update to recent OSes (Ubuntu 22.04, Fedora 36, etc.).
