### ISSUE TITLE
Attempting to put null into a typed array of Object (and derivatives) fails

### ISSUE THREAD

**Issue by Yagich** [godotengine/godot#63608]
### Godot version

4.0a13

### System information

Linux/Ubuntu 22.04

### Issue description

`TypedArray`s of type `Object` (and derivatives) do not accept `null`. This is inconsistent with declaring a variable, typing it as `Object` or derivatives, and setting it to null.

### Steps to reproduce

1. Make a `TypedArray` of type `Object`
2. Try to set any of its elements to `null`

**Comment by ajreckof** [comment]
I made a minimal reproduction project based on what i understand of the bug but could not replicate it
[test.zip](https://github.com/godotengine/godot/files/9218977/test.zip)
I might have made false assumption if it is the case could you please add a minimal reproduction project?

**Comment by vysker** [comment]
Facing the same issue. Reproducible:

	var nodes: Array[Node] = []
	nodes.resize(1)
	print(nodes[0]) # Prints <null>
	nodes[0] = Node.new()
	print(nodes[0]) # Prints <Node#47445968338>
	nodes[0] = null
	print(nodes[0]) # Prints <Node#47445968338>

I tried working around the issue by using `Array.remove_at` and `Array.insert`, but that doesn't work either. Example:

	var nodes: Array[Node] = []
	nodes.resize(1)
	print(nodes[0]) # Prints <null>
	nodes[0] = Node.new()
	print(nodes[0]) # Prints <Node#45298484672>
	nodes.remove_at(0)
	nodes.insert(0, null) # Silently fails with '_input: Condition "!_p->typed.validate(p_value, "insert")" is true. Returning: ERR_INVALID_PARAMETER'
	print(nodes[0]) # Fails with "Out of bounds get index '0'"

So my other workaround is to use a Dictionary instead.
