### ISSUE TITLE
Rename a child node in base scene will lost all children of that node in inherited scenes  

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#63611]
### Godot version

3.4.4

### System information

Mac OS  

### Issue description

I have a base menu and create some inherited scenes from that menu, and add some nodes in  inherited scenes and saved.
However, after rename a child node (not the root node) in the base menu, all children of that renamed node lost in  inherited scenes. 
It's terrible, all of my work for inherited scenes lost.

### Steps to reproduce

add scene A
add any node as child, name it NodeA 
save this scene

create a inherited scene B from scene A
add any node as child of NodeA in scene B
save scene B

rename NodeA to any name in  scene A
save it
the Children of NodeA lost in scene B

In the mini project, just rename the node named Node in base scene, the child of Node will lost in the inherited scene.

### Minimal reproduction project

[RenameNode.zip](https://github.com/godotengine/godot/files/9217360/RenameNode.zip)

**Comment by KoBeWi** [comment]
This is fixed in 3.5 (#60893)

**Comment by alexzheng** [comment]
It's a little different from deleting a node.
It would be better if the children can just remain under the renamed node.

**Comment by alexzheng** [comment]
It's a little different from deleting a node.
It would be better if the children can just remain under the renamed node.

**Comment by KoBeWi** [comment]
That's not possible unfortunately, because the inherited scene does not know about the rename.
It would require some refactoring tools for the editor.

**Comment by alexzheng** [comment]
Rename a file name will modify all scenes using that file, will it be possible take that solution?

**Comment by KoBeWi** [comment]
It might be possible this way actually, but it's more complicated than fixing dependencies.

**Comment by alexzheng** [comment]
yes, it require first matching the base scene file name and then match the old node name.
It's just a suggestion.

**Comment by KoBeWi** [comment]
You can open a proposal if you want.
