### ISSUE TITLE
AnimationTree node and AnimationPlayer node do not show their fields when I click them

### ISSUE THREAD

**Issue by gravit22** [godotengine/godot#63621]
### Godot version

Godot 4.0 13 alpha

### System information

Ubuntu 22.04 GTX 1060

### Issue description

AnimationTree node and AnimationPlayer node do not show their fields when I click them. 
Before everything worked fine(in alpha 12 version). I just ckicked the node and field with animations opened when I click AnimationPlayer, for AnimationTree, it is the same problem. 
It doesn't work only when you are in scripting mode. 

### Steps to reproduce

I attached the project. 
Just open the project.
Click "Script" tab.
Then click AnimationTree or AnimationPlayer node. 
You should not notice any field appear. 

### Minimal reproduction project

[Bug_report.zip](https://github.com/godotengine/godot/files/9219502/Bug_report.zip)

**Comment by tefusion** [comment]
This is caused by #63344. Go to editor settings->Text Editor->Behavior->Navigation and disable "Stay In Script Editor On Node Selected", then behavior is the same as in alpha 12.

I think it's intentional, but it might be better to split the setting into two since animation player doesn't switch to another editor and just switches the bottom panel out.

**Comment by danhealy** [comment]
This bug also applies to the `MultiplayerSynchronizer` / `Replication` tab. 

https://streamable.com/3kamgu

I believe this is a bug, because you can get in a state where you have one `MultiplayerSynchronizer` node selected but it's actually editing a different node.

https://streamable.com/v2edvp

**Comment by alfredbaudisch** [comment]
> This is caused by #63344. Go to editor settings->Text Editor->Behavior->Navigation and disable "Stay In Script Editor On Node Selected", then behavior is the same as in alpha 12.
> 
> I think it's intentional, but it might be better to split the setting into two since animation player doesn't switch to another editor and just switches the bottom panel out.

Unfortunately it's not intentional, the AnimationPlayer should still show. I'll take a look.

**Comment by alfredbaudisch** [comment]
> This bug also applies to the `MultiplayerSynchronizer` / `Replication` tab.
> 
> https://streamable.com/3kamgu
> 
> I believe this is a bug, because you can get in a state where you have one `MultiplayerSynchronizer` node selected but it's actually editing a different node.
> 
> https://streamable.com/v2edvp

@danhealy this is also fixed by #63813

**Comment by RokeJulianLockhart** [comment]
![Screenshot_20230929_110355](https://github.com/godotengine/godot/assets/42837531/33cfc7f5-978e-49b5-bf94-b5bc50fee568) ![Screenshot_20230929_110406](https://github.com/godotengine/godot/assets/42837531/3b55d2b4-57e8-44b2-9175-a70460bc06d9)

Am I having the same issue? They seemed to stop loading altogether after I once tried loading the animations from the scripts pane.

**Comment by RokeJulianLockhart** [comment]
I think I am having the same issue now – switching once to the AnimationPlayer node fixed it. All I had to do was switch to it once.
