### ISSUE TITLE
mesh.create_shape() doesn't work in headless run

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#63623]
### Godot version

4.0 dev 8b059d47f669eba45c0ee4331be16c0faddafc0a

### System information

Ubuntu 18.04 / 22.04 / Windows 11

### Issue description

We have discovered that in our online game people can walk through objects, since our game is server-authoritative we quite quickly realized the problem must be related to our server not being able to generate collision shapes.
After some further investigation we narrowed it down to the --headless flag that we are using for our servers

Using any of the functions from:
* Mesh.create_convex_shape()
* Mesh.create_trimesh_shape()

will return null and print such errors:
```
ERROR: Condition "vertex_data.size() == 0" is true. Returning: Array()
   at: mesh_create_arrays_from_surface_data (servers/rendering_server.cpp:1392)
ERROR: Condition "a.is_empty()" is true. Returning: Ref<TriangleMesh>()
   at: generate_triangle_mesh (scene/resources/mesh.cpp:210)
ERROR: Condition "!tm.is_valid()" is true. Returning: Vector<Ref<Shape3D>>()
   at: convex_decompose (scene/resources/mesh.cpp:687)
ERROR: Convex shape simplification failed, falling back to simpler process.
   at: create_convex_shape (scene/resources/mesh.cpp:331)
ERROR: Condition "vertex_data.size() == 0" is true. Returning: Array()
   at: mesh_create_arrays_from_surface_data (servers/rendering_server.cpp:1392)
ERROR: Condition "a.is_empty()" is true. Returning: Ref<ConvexPolygonShape3D>()
   at: create_convex_shape (scene/resources/mesh.cpp:338)j
```

### Steps to reproduce

1. Add MeshInstance to a scene, ensure it has some model
2. From code call `var collision = MeshInstance.mesh.create_convex_shape(true, true)`
3. Print `collision` var
4. Run this with --headless flag, observe that `collision` var is null, observer all the generated errors

Reproduction with sample project
1. Open project in editor so all the assets are imported, exit editor
2. Start it in with `--headless` flag look at the error log

### Minimal reproduction project

[collision_headless_generation.zip](https://github.com/godotengine/godot/files/9220093/collision_headless_generation.zip)

**Comment by kubecz3k** [comment]
I just tested in Godot.3.4.4 and it works as intended there

**Comment by kubecz3k** [comment]
Seems I got it fixed locally, will create the pr in Monday

**Comment by jeffgamedev** [comment]
> Seems I got it fixed locally, will create the pr in Monday

Thank you for taking care of this Jakub!!
