### ISSUE TITLE
TileMap node doesn't work - can't see grid/tiles + console errors

### ISSUE THREAD

**Issue by warriordog** [godotengine/godot#63633]
### Godot version

4.0.alpha13

### System information

Windows 10, Vulkan (either mode), Ryzen 3 1200, GTX 980

### Issue description

The new TileMap node does not work properly. The grid (including all terrain tiles) does not show up after clicking the node in the scene tree sidebar. Additionally, attempting to change any tiles (using the bottom editors) causes this error to be infinitely spammed in the console:
`ERROR: Rect2i size is negative, this is not supported. Use Rect2i.abs() to get a Rect2i with a positive size.`
The editors in the bottom panel (TileMap and TileSet) both work fine. Its just the node itself which seems to be broken.

Example of invisible terrain grid. The grid that _is_ visible is just the normal 2D editor grid, not the TileMap grid.
![GD4TilesBug](https://user-images.githubusercontent.com/5315704/181803286-69208b6b-721f-4db4-a7f8-795e7c7ff2e1.PNG)

Example console output: [GD4TilesBug.log](https://github.com/godotengine/godot/files/9221704/GD4TilesBug.log)

### Steps to reproduce

1. Create a new 2D scene
2. Add a TileMap node
3. Add a TileSet and configure some tiles
4. Attempt to add a tile to the map
5. [bug here] Tile will not be added and console spam will start

### Minimal reproduction project

Minimal reproduction project: [GD4TilesBug.zip](https://github.com/godotengine/godot/files/9221710/GD4TilesBug.zip)

**Comment by KoBeWi** [comment]
Actually the issue is that your TileMap has infinite scale for whatever reason:
![image](https://user-images.githubusercontent.com/2223172/181830511-d295840b-264f-48d5-9492-c74c1d10842d.png)

**Comment by warriordog** [comment]
> Actually the issue is that your TileMap has infinite scale for whatever reason:
> ![image](https://user-images.githubusercontent.com/2223172/181830511-d295840b-264f-48d5-9492-c74c1d10842d.png)
> 
> I'm confused on how is that even possible 🤔

Nice catch, thanks! I have no idea how that happened - this was a brand new project and I didn't touch the scale.

**Comment by Calinou** [comment]
I wonder if "inf" properties in the editor should be displayed in red, as they're almost never intentional.
