### ISSUE TITLE
Sliders and color picker loses focus when dragging outside of rect

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#63645]
### Godot version

v4.0.alpha.custom_build [8cb51a642]

### System information

Linux Fedora, Radeon RX 590

### Issue description

Controls seem to lose mouse focus while dragging. Happens with sliders and color picker at least.

### Steps to reproduce

Drag a slider or a color on a color picker
https://gfycat.com/physicalgratefulauklet

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/63544.

**Comment by KoBeWi** [comment]
Can no longer reproduce in rc5.
