### ISSUE TITLE
Adding Systemfont to Button or Label property causes font property panel to display extraneous characters

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#63652]
### Godot version

v4.0.alpha13.official [59dcddc45]

### System information

Mac OS X (Catalina) 10.15.7

### Issue description

Add SystemFont to  Button or Label. then click on it. Will show extraneous characters on the panel.

![image](https://user-images.githubusercontent.com/930478/181836362-f686a47d-d821-43ed-a7b5-2254768f25ca.png)

![image](https://user-images.githubusercontent.com/930478/181836125-8a17bd13-ec76-406a-9bd6-afdade3cc13f.png)

### Steps to reproduce

Add Button or Label
Add SystemFont
Click on SystemFont

**Comment by akien-mga** [comment]
What's your monitor(s) resolution?

**Comment by bruvzg** [comment]
Seems like font preview is not scaled correctly with the editor resolution.

A system font on the screenshots doesn't have a name set, so it's actually using a fallback default theme font, so it's not specific to `SystemFont` (font preview plugin is common for all types of fonts).

**Comment by wyattbiker** [comment]
Resolution, 1440x900 MacBook Pro laptop if you still need it.
