### ISSUE TITLE
Build failing on Fedora (modules/text_server_adv/text_server_adv.cpp:1362: error: 'hb_font_set_synthetic_slant' was not declared in this scope)

### ISSUE THREAD

**Issue by Calandiel** [godotengine/godot#63658]
### Godot version

4.0 ( 9094262 )

### System information

Fedora Linux 35 (Workstation Edition)

### Issue description

After following the instructions from the [documentation](https://docs.godotengine.org/en/latest/development/compiling/compiling_for_linuxbsd.html#doc-compiling-for-linuxbsd) (using the "one liner" for Fedora), calling `scons` ends with the following error message:
```
modules/text_server_adv/text_server_adv.cpp: In member function 'bool TextServerAdvanced::_ensure_cache_for_size(TextServerAdvanced::FontAdvanced*, const Vector2i&) const':
modules/text_server_adv/text_server_adv.cpp:1362: error: 'hb_font_set_synthetic_slant' was not declared in this scope
 1362 |                 hb_font_set_synthetic_slant(fd->hb_handle, p_font_data->transform[0][1]);
      | 
```
I verified that all requirements are met and have sufficient versions.
After doing some research of my own, it looks to me like this function should be declared in the scope (its included through `hb.h` and `text_server_adv.h`). I'd expect Godot to compile without any issues after following documentation and I'm not sure what could be causing this error.

### Steps to reproduce

Clone the repository and follow the steps laid out in the documentation for compiling on Linux.

### Minimal reproduction project

n/a

**Comment by akien-mga** [comment]
What scons command do you run exactly?
Could you run with `verbose=yes` and post the full compiler invocation for this file?

CC @bruvzg

**Comment by bruvzg** [comment]
Are you trying to build with system HarfBuzz (`builtin_harfbuzz=false` flag)? `hb_font_set_synthetic_slant` function was added in HarfBuzz 3.3.0, system version might be older.

Or it might be using system headers in favor of built-in for some reason.

**Comment by spellcard199** [comment]
Hello. I can confirm that building fails on Fedora 35 with the same error using both `scons compiledb=yes` and `scons compiledb=yes use_llvm=yes`. I tried checking out previous commits and rebuilding and it seems to me (never studied nor used C++ before) that commit 1bb56d92980c268a24d826a342ed4c44e7058b5a is the last one compiling successfully. Maybe something is happening in the next commit, cc5135959b8d7956e93c566916352f5818f008f1?

> Could you run with verbose=yes and post the full compiler invocation for this file?

Building with `scons compiledb=yes verbose=yes`, I think this should be the line relative to `modules/text_server_adv/text_server_adv.cpp`, 

```
[ 22%] g++ -o modules/text_server_adv/text_server_adv.linuxbsd.tools.64.o -c -std=gnu++17 -DU_HAVE_LIB_SUFFIX=1 -DU_LIB_SUFFIX_C_NAME=_godot -DICU_DATA_NAME=icudt71l.dat -DICU_STATIC_DATA -g3 -pipe -pthread -Wall -Wshadow-local -Wno-misleading-indentation -DDEBUG_ENABLED -DDEV_ENABLED -DNO_EDITOR_SPLASH -DTOUCH_ENABLED -DFONTCONFIG_ENABLED -DALSA_ENABLED -DALSAMIDI_ENABLED -DPULSEAUDIO_ENABLED -D_REENTRANT -DDBUS_ENABLED -DJOYDEV_ENABLED -DUDEV_ENABLED -DX11_ENABLED -DUNIX_ENABLED -D_FILE_OFFSET_BITS=64 -DVULKAN_ENABLED -DGLES3_ENABLED -DTOOLS_ENABLED -DMINIZIP_ENABLED -DZSTD_STATIC_LINKING_ONLY -DUSE_VOLK -DVK_USE_PLATFORM_XLIB_KHR -DGLAD_ENABLED -DGLES_OVER_GL -Ithirdparty/libpng -Ithirdparty/glad -Ithirdparty/volk -Ithirdparty/vulkan -Ithirdparty/vulkan/include -Ithirdparty/zstd -Ithirdparty/zlib -Iplatform/linuxbsd -I. -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/libxml2 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -Ithirdparty/harfbuzz/src -Ithirdparty/icu4c -Ithirdparty/icu4c/common -Ithirdparty/msdfgen -Ithirdparty/freetype/include -Ithirdparty/graphite/include modules/text_server_adv/text_server_adv.cpp
```

**Comment by bruvzg** [comment]
> `... -I/usr/include/harfbuzz ... -Ithirdparty/harfbuzz/src ...`

So system version is included first.

https://github.com/godotengine/godot/commit/cc5135959b8d7956e93c566916352f5818f008f1 added CFLAGS for `fontconfig`, which depend on `FreeType` which might depend on `HarfBuzz` (depending on config).

Probably we should prepend built-in includes, instead of appending to ensure it's include in correct order.
We can also include compile time `HarfBuzz` version check for `hb_font_set_synthetic_slant`, since this call is not essential. I'll check it with an older versions tomorrow, to assess how much stuff is missing and if it's worth adding checks.

Meanwhile, try building it with [this line](https://github.com/godotengine/godot/blob/5595f2406a743a5a8f85d7e5642efa3c5ca18702/modules/text_server_adv/SCsub#L120) changed to `env_harfbuzz.Prepend(CPPPATH=["#thirdparty/harfbuzz/src"])`.

**Comment by akien-mga** [comment]
I don't understand why system includes are present at all if not using `builtin_harfbuzz=no` or similar.

**Comment by bruvzg** [comment]
> I don't understand why system includes are present at all if not using

System includes are most likely from `fontconfig`:
https://github.com/godotengine/godot/blob/cca072aa8672633a235e9187ee6873d9f165e003/platform/linuxbsd/detect.py#L305

**Comment by spellcard199** [comment]
> Meanwhile, try building it with [this line](https://github.com/godotengine/godot/blob/5595f2406a743a5a8f85d7e5642efa3c5ca18702/modules/text_server_adv/SCsub#L120) changed to env_harfbuzz.Prepend(CPPPATH=["#thirdparty/harfbuzz/src"]).

That specific line wasn't working, however I noticed that line 149 was somehow similar, so I applied the same fix you suggested to [that line](https://github.com/godotengine/godot/blob/5595f2406a743a5a8f85d7e5642efa3c5ca18702/modules/text_server_adv/SCsub#L149), changing it to     `env_text_server_adv.Prepend(CPPPATH=["#thirdparty/harfbuzz/src"])`, and it built successfully. Thank you.

**Comment by Calandiel** [comment]
I caught up with the discussion. The output of running with `verbose=yes` was the same as the one spellcard199 reported. Trying the suggested fix worked for me too. Thank you!
I was able to reproduce these errors on a fresh installation of Fedora 35 and the suggested changes worked there as well.
