### ISSUE TITLE
Mouse wheel is not configurable shortcut key

### ISSUE THREAD

**Issue by oliverKuha** [godotengine/godot#6366]
**Operating system or device - Godot version:**
Mac OS X 10.11.6 Godot 2.1 Stable

**Issue description** (what happened, and what was expected):
Mouse wheel is not configurable as a shortcut key. Current default behavior makes trackpad almost unuseable in godot.

**Comment by genete** [comment]
+1

**Comment by Noshyaar** [comment]
Still reproducible/relevant in 3.1 master 9ad1800

**Comment by Calinou** [comment]
Closing in favor of #38326, which essentially covers the same issue (but with more information).
