### ISSUE TITLE
AnimationTree AnimationNodeStateMachine only shows 'End node' when child of another StateMachine

### ISSUE THREAD

**Issue by ncollie42** [godotengine/godot#63660]
### Godot version

4.0 (0cd049e41), 4.0 alpha13 (59dcddc45)

### System information

Linux, x11, nvidia

### Issue description

AnimationNodeStateMachine does not show a 'End' node when it's not a child of another Statemachine. 

Meaning that it's not directly usable from a BlendTree, BlendSpace1D, BlendSpace2D, or if it's the main node in Tree Root of AnimationTree.

tree_root.get_node("StateMachine).get("states/End/position") shows it's still located in the same position as if it was there but it's not visible.

![Screenshot from 2022-07-29 16-10-53](https://user-images.githubusercontent.com/52465548/181860776-8eaf0e97-2c5c-44e0-9a3d-a57501cd18b4.png)
![Screenshot from 2022-07-29 16-11-11](https://user-images.githubusercontent.com/52465548/181860777-797196d2-02e9-4fda-9581-dc13bc2b5cb7.png)

### Steps to reproduce

1. Create a AnimationTree
2. Assign a AnimationNodeStatemachine to tree root
   -  Observe no 'End' node
3. Add another Statemachine
   - Observer 'End' node 

### Minimal reproduction project

[StateMachine.zip](https://github.com/godotengine/godot/files/9223939/StateMachine.zip)

**Comment by ncollie42** [comment]
It is part of this commit: https://github.com/godotengine/godot/commit/e7056c195deb6a7cab4b58be549566234565759c

It looks like it is an intended check to not include the end node unless the statemachine is parented to another statemachine.
https://github.com/godotengine/godot/blob/7199314eb39408da4f9f7286452c980a3d3da1c9/scene/animation/animation_node_state_machine.cpp#L886-L888

This change limits the use of statemachines and blendTrees together

**Comment by guilhermefelipecgs** [comment]
@ncollie42 I think you misunderstood how the end node works. It is only used inside sub state machines (it's exactly like that in version 3.x). They are useless when we talk about blend tree. That's why it was removed. The behavior of the state machine inside a blend tree was not affected, it works normally as in version 3.x.

**Comment by ncollie42** [comment]
@guilhermefelipecgs you're right I don't fully understand how the end node works, but how can we explain state machines not returning to blendtrees? 
![Screenshot from 2022-08-01 10-00-41](https://user-images.githubusercontent.com/52465548/182203443-183eb068-4592-403f-96bd-352007acd8ea.png)

This is something that works in 3.x but not in 4.0. would you say its unrelated to your changes?

**Comment by guilhermefelipecgs** [comment]
ah yes, you're right, for `OneShoot` it will really be a problem, it makes sense now. I will take a look at it.
