### ISSUE TITLE
Exported variable appears doubled in object inspector

### ISSUE THREAD

**Issue by mcihad** [godotengine/godot#63668]
### Godot version

4.0-13 Alpha

### System information

Linux-Ubuntu 22.04 Vulkan RTX 3050

### Issue description

exported variable appears double in object inspector

### Steps to reproduce

exported variable appears double in object inspector

### Minimal reproduction project

[Godot4Game.zip](https://github.com/godotengine/godot/files/9225651/Godot4Game.zip)

**Comment by mcihad** [comment]
![Screenshot from 2022-07-30 10-54-52](https://user-images.githubusercontent.com/74842/181883208-64059392-90eb-4518-ac22-eb73fab29d8a.png)

**Comment by ThunderSmotch** [comment]
Can confirm, also happening to me using Godot 4.0 - Alpha 13.

**Comment by akien-mga** [comment]
Possibly a regression from #58443, CC @object71 @YuriSizov.

**Comment by kleonc** [comment]
#63454 was reopened [because of what is reported here](https://github.com/godotengine/godot/issues/63454#issuecomment-1199771986), possibly could be closed again in favor of this issue.

**Comment by YuriSizov** [comment]
Probably should, because it is no longer related to categories.

I guess it's time to rewrite this hacky method and test it again thoroughly.

**Comment by mbrlabs** [comment]
There is still weirdness going on when using categories, but it's a bit different. Sure let's close the other issue.

```gdscript
extends Node

@export_category("foo")
@export var my_string: String

@export_category("bar")
@export var my_int: int
```

![image](https://user-images.githubusercontent.com/8750135/181905894-50723607-09da-41a0-b7dc-ba6b2b6c2e5b.png)

**Comment by YuriSizov** [comment]
> There is still some weirdness going on when using categories, but it's a bit different. 

It's the same as OP, it's just that the duplicates aren't grouped.

**Comment by object71** [comment]
Duplication only seems to happen when it is not a tool script.

**Comment by object71** [comment]
I will look into that method once more to see if we can rewrite it cleanly

**Comment by object71** [comment]
Can you test again with the open pull request? Removed the function ```_update_script_class_properties``` as a whole as it tried to do something which was too hacky - to rearrange properties. It is prone to bugs as it duplicated and tries to classify and move properties around but that could be achieved by the properties actually being classified correctly in the first place.

**Comment by mcihad** [comment]
same problem exists on macos system
<img width="1546" alt="Screen Shot 2022-08-01 at 09 58 44" src="https://user-images.githubusercontent.com/74842/182091016-74df7bc2-202f-405b-ba38-5ed49ed2a885.png">

**Comment by stylemistake** [comment]
@object71 your PR #63712 fixes it.
