### ISSUE TITLE
Godot 4.0 Alpha 13 Threaded Physics causes Crashing

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#63671]
### Godot version

4.0 Alpha 13

### System information

Windows 11, Vulkan, Nvidia GTX 1050 Ti, 512.15

### Issue description

Regression in Alpha 13 (not found in Alpha 12)

Running a Scene with Physics running on a Thread causes a crash within several minutes of running.

### Steps to reproduce

Set Physics to run on a Separate Thread
Run any Scene (F6)
Wait a couple of minutes for Crash to occur

### Minimal reproduction project

Only setting Physics to run on a Separate Thread (2d & 3d) is required to reproduce, nothing else matters

**Comment by akien-mga** [comment]
Possibly related to #63354.

**Comment by akien-mga** [comment]
Confirmed in https://github.com/godotengine/godot/issues/63786, see that issue for stacktrace and a project where it happens.

**Comment by fire** [comment]
```
[[gnu::noinline]] // Required for testing `this` == nullptr; else c++/clang optimizes away
static bool _is_nullptr(void* self) { return self == nullptr; }
```

https://stackoverflow.com/questions/40783056/safely-check-if-this-is-null

**Comment by lyuma** [comment]
I suspect this is actually the same issue as #67333 . I think the comment that the stack trace was different was incorrect. the stack trace in this issue matches what I ran into on the other control scene bug
