### ISSUE TITLE
AnimatedSprite spritesheet support

### ISSUE THREAD

**Issue by robertdhernandez** [godotengine/godot#6367]
This might be a duplicate of #344, but that issue is over 2 years old so I thought it'd be better to make a new one instead to bring fresh discussion.

---

It's inconsistent for Sprite to handle spritesheets and AnimatedSprite to handle multiple image sprites. Sprite should be just a simple Node that renders a 2D image with a definable sub region. It shouldn't also do sprite animations -- that's what AnimatedSprite is for: a sprite that has multiple frames defined by a SpriteFrame (or multiple images) and animates it very simply. If users want more customized sprite animations, they can use an AnimationPlayer; otherwise the AnimatedSprite handles majority of animated sprite cases in an easy format.

The other issue with Sprite doing animations, is that animating them requires an AnimationPlayer, which becomes really tedious to adjust the Sprite:frame for each key for each animation (unless I'm unaware of a better method).

**Comment by razvanc-r** [comment]
Yes, I also feel that this is a bit strange, and somewhat inconsistent if you think about the naming, `Sprite` vs `AnimatedSprite`, why is `Sprite` capable and `AnimatedSprite` not?

**Comment by eon-s** [comment]
@robertdhernandez is easy to animate using frames and AnimationPlayer (just +1 each frame).

But is true of the inconsistency, it should support spritesheets too.
Maybe AnimatedSprite is too old, perhaps not even needed with the new plugins around.

**Comment by reduz** [comment]
You can use AtlasTexture, which works similar to a SpriteSheet, but I think
there is no easy tool to do this.

**Comment by razvanc-r** [comment]
@eon-s I digress, it isn't as easy when you want to play with speed. You have to work with the less intuitive `Speed` option of `AnimationPlayer` and/or do scale the keyframes, both options meaning you have to do maths so I personally at least prefer the easier `AnimatedSprite` option. It would be great if either `AnimatedSprite` get the option of working with sprite sheets or have the `AnimationPlayer` work in FPS as well, not just time in seconds. If `AnimationPlayer` would receive FPS option it would probably mean the end of `AnimatedSprite`, but oh well...

**Comment by Noshyaar** [comment]
Still reproducible/relevant in 3.1 master 9ad1800 : there's no easy way to use spritesheet with animatedsprite

**Comment by eon-s** [comment]
I wonder if may be better to add separate image support (and texture track preview if possible) for use with AnimationPlayer and start deprecating AnimatedSprite.

**Comment by aedart** [comment]
GoDot has some really powerful features, yet the 2D animation part is somewhat troublesome. I too would like an "easier / consistent" way to use both individual images (e.g. via the AnimatedSprite) and sprite-sheets / atlas, when animating. It's not that the current version doesn't work; it's doable once you gotten the hang it. Yet, when working with pre-made sprite-sheets, it's just more demanding to setup your animations, in comparison to other game-engines (or editors). 

As @eon-s already wrote, it might be a better solution to simply scratch AnimatedSprite, and allow Animation Player to offer sprite-sheet / atlas support. Furthermore, if the animation player also could allow setting frame-per-second directly, then this could be really great.

**Comment by KoBeWi** [comment]
Fixed in 3f76d2c2
