### ISSUE TITLE
Documentation versioning

### ISSUE THREAD

**Issue by profelis** [godotengine/godot#6369]
Now exist only `latest` build version of documentation http://readthedocs.org/projects/godot/
Will be great to compile/publish documentation every major release (2.0, 2.1, ... latest)

And yes, previous version can be found in builds log http://readthedocs.org/projects/godot/builds/

**Comment by bojidar-bg** [comment]
Can you reopen this issue on https://github.com/godotengine/godot-docs?

**Comment by profelis** [comment]
@bojidar-bg done. But I found docs for 2.1 major version. Looks promising
