### ISSUE TITLE
Editor Settings in next tab become invisible after scrolling, until you go back and forth again

### ISSUE THREAD

**Issue by MJacred** [godotengine/godot#63699]
### Godot version

4.0 Alpha 13

### System information

Ubuntu 20.04.1

### Issue description

scroll content in editor settings, change tab, then whole tab content is hidden.  
switch tabs again.  
switch back -> it reappears

### Steps to reproduce

Just open editor and:

[bug.webm](https://user-images.githubusercontent.com/6639237/182002978-8daecdb9-cc25-456d-acb5-c5c5049d4946.webm)

**Comment by Calinou** [comment]
Can you reproduce this in 4.0.alpha12?

**Comment by MJacred** [comment]
Cannot reproduce in 4.0 alpha 12. Works fine there

**Comment by snailrhymer** [comment]
Looks like the same thing as #63334 - I tested #63348 and it fixes this issue too (as well as analogous behaviour in Project Settings).

**Comment by MJacred** [comment]
Sounds reasonable, thanks @snailrhymer !

Will close this issue, because it seems to be a duplicate of https://github.com/godotengine/godot/issues/63334
