### ISSUE TITLE
Error in MeshStorage::mesh_free in Skeleton with atleast 2 bones in Editor

### ISSUE THREAD

**Issue by tefusion** [godotengine/godot#63693]
### Godot version

4.0.alpha12,  4.0.alpha13, v4.0.alpha.custom_build.cca072aa8

### System information

Linux Manjaro

### Issue description

When opening an inherited scene/adding a imported glb to a scene that contains a skeleton with at least one bone with a parent bone  Godot throws

```
servers/rendering/renderer_rd/storage_rd/mesh_storage.cpp:702 - Condition "!mesh" is true.
servers/rendering/renderer_rd/storage_rd/mesh_storage.cpp:683 - Condition "!mesh" is true.
servers/rendering/renderer_rd/storage_rd/mesh_storage.cpp:213 - Condition "!mesh" is true.
servers/rendering/renderer_rd/storage_rd/mesh_storage.cpp:217 - deleting mesh with active instances
```
and when closing the scene again
```
  servers/rendering/renderer_rd/storage_rd/mesh_storage.cpp:702 - Condition "!mesh" is true.
  servers/rendering/renderer_rd/storage_rd/mesh_storage.cpp:683 - Condition "!mesh" is true.
  servers/rendering/renderer_rd/storage_rd/mesh_storage.cpp:213 - Condition "!mesh" is true.
  drivers/vulkan/rendering_device_vulkan.cpp:8744 - Attempted to free invalid ID: 514073225592918
  servers/rendering/renderer_rd/storage_rd/mesh_storage.cpp:217 - deleting mesh with active instances
```

I also tested on 4.0.alpha11 and didn't have/see any issues there. 

### Steps to reproduce

1. Create bone with at least one parent bone in Blender
2. export glb to Godot
3. open inherited scene

### Minimal reproduction project

[Skeleton Mesh Free Bug.zip](https://github.com/godotengine/godot/files/9227528/Skeleton.Mesh.Free.Bug.zip)

**Comment by MJacred** [comment]
Got same errors (and more) in https://github.com/godotengine/godot/issues/54719#issuecomment-1200286429 while reimporting glb file

**Comment by tefusion** [comment]
Just figured out that when copying said skeleton to another scene it will have a new hidden MeshInstance as a ChildNode, might be the mesh which causes issues.

**Comment by MJacred** [comment]
I remember from Godot 3.x that importing a skeleton without mesh was not possible - not sure if that changed.

So the way to go was to export skeleton with dummy mesh plane and delete said dummy using code, then you assemble your character or whatever with other mesh-only files.

**Comment by tefusion** [comment]
> I remember from Godot 3.x that importing a skeleton without mesh was not possible - not sure if that changed.
> 
> So the way to go was to export skeleton with dummy mesh plane and delete said dummy using code, then you assemble your character or whatever with other mesh-only files. Once you save your assembly (the whole process via code), it has a skeleton + mesh. Then there was no issue.

Problem stays the same when using a skeleton with a mesh so I don't think that's it

**Comment by MJacred** [comment]
As I encountered the same errors with a model which has both, that's true. But just in case you encounter other issues.
