### ISSUE TITLE
Add comment to Blender/FBX import paths in Editor Settings

### ISSUE THREAD

**Issue by MJacred** [godotengine/godot#63695]
the **Enabled** fields were moved from Editor Settings to Project Settings. There they have comments referring to the import paths in the Editor Settings.

But vice versa is missing.

Therefore, **add a reference documentation to the import path field's tooltips in Editor Settings, pointing back to Project Settings boolean flags as part of the Advanced Settings**.

It's confusing that these import paths are enabled in Project Settings and just dropped in Editor Settings without explanation about where they are enabled/disabled.

Old:

![old placement](https://user-images.githubusercontent.com/3036176/179501277-edb43043-0e14-40c9-9d17-b0f9cffa7326.png)

Current:

![new placement](https://user-images.githubusercontent.com/6639237/181997010-53acc6cb-40f9-4b36-a4f7-59f466978730.png)

_original issue below_

```
### Godot versions

4.0 alpha 12  
4.0 Alpha 13

### System information

Ubuntu 20.04.1

### Issue description

Settings "filesystem/import/fbx/enabled" and "filesystem/import/blender/enabled" (https://github.com/godotengine/godot/blob/master/doc/classes/ProjectSettings.xml)

still seen here: https://github.com/godotengine/godot/issues/63144
(https://github.com/godotengine/godot/commit/1c6148aa86c4a3b8d5c292da69ffacc2f3a46eb8 on Windows  11)

is gone in Alpha 13:

![image](https://user-images.githubusercontent.com/6639237/181997010-53acc6cb-40f9-4b36-a4f7-59f466978730.png)

Also did not find them project settings.

Also, I get the `FBX file import is enabled, but no FBX2glTF path is configured. FBX files will not be imported.` warning on project startup. If the documentation is correct, the default value is TRUE, but I cannot check that (without creating a Editor Plugin).

### Steps to reproduce

Create a new empty project or open any existing one.
* enabling the advanced settings in project settings makes no difference (completely restarting editor after toggling also does not help)

### Minimal reproduction project

_No response_

```

**Comment by jtnicholl** [comment]
Did you enable advanced settings in the project settings? It won't show up unless you do.

**Comment by MJacred** [comment]
Yes, I enabled the advanced settings in project settings. Issue persists. Completely restarting editor also does not help

**Comment by KieranCarden** [comment]
I haven't updated to alpha 13 yet, but in 12 I see the options in project settings.
![settings](https://user-images.githubusercontent.com/4044137/184045502-6fd22293-cc19-4568-8f11-295f6fb48cbd.png)

**Comment by MJacred** [comment]
Thanks @KieranCarden, they are stored in project settings… and there they have a description pointing at the Editor Settings. So vice versa should be done and **add a reference documentation in Editor Settings, pointing back to Project Settings boolean flags as part of the Advanced Settings**.

**Comment by Calinou** [comment]
> add a reference documentation in Editor Settings

This was done in https://github.com/godotengine/godot/pull/48548, but not all editor settings have documentation yet as some of them are registered too late to be caught by doctool.

**Comment by MJacred** [comment]
I updated the issue title and description, so it's actually a documentation/description issue.

**Comment by varunlmxd** [comment]
is this issue still open? can you assign me this issue and can I work on this issue ?

**Comment by jtnicholl** [comment]
> is this issue still open? can you assign me this issue and can I work on this issue ?

If you want to work on it just go ahead, issues don't usually get assigned. That said, as Calinou mentioned above:

> not all editor settings have documentation yet as some of them are registered too late to be caught by doctool.

This means it isn't as simple as adding a description into the EditorSettings.xml file, some significant work needs to be done. I don't think the "good first issue" label is accurate.
