### ISSUE TITLE
Inspector resource previews are very small

### ISSUE THREAD

**Issue by fire-forge** [godotengine/godot#63701]
### Godot version

v4.0.alpha13.official [59dcddc45]

### System information

Windows 10

### Issue description

Inspector resource previews are small. Previously they were 64px tall, but now they are much shorter.

Alpha 13:
![image](https://user-images.githubusercontent.com/67974470/182003617-1c27df66-11bb-4e00-b957-341936bff74e.png)

Alpha 12:
![image](https://user-images.githubusercontent.com/67974470/182003792-c02bc5f4-9306-4049-9e12-007efd3d3538.png)

### Steps to reproduce

* Create a MeshInstance3D
* Add a BoxMesh to it
* The resource preview is short

This also applies to other resources with previews, including Texture.

**Comment by Calinou** [comment]
I can confirm this on 66d1bb84c380910a50e3176124da5c8821e93097 (Linux) and have been able to reproduce this for a week or so.

**Comment by nongvantinh** [comment]
@reduz on commit d1ddee225830b28171de031bd1f1918ced21b38f, he changed `EditorResourcePicker::_update_resource_preview`  intended.

Should I revert to the old one?

**Comment by fire-forge** [comment]
@nongvantinh Thanks for finding the commit. The changes on this line seem to be that cause of the issue: https://github.com/godotengine/godot/pull/63265/files#diff-c2c807db528ea8403dc5953981d00248bc891451924ac938477ea719bffd6632R108

Replacing `MIN` with `MAX` in both places on that line will probably fix the bug.
