### ISSUE TITLE
Autocomplete matching should be case insensitive, otherwise case mismatch leads to confusing results

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#63706]
### Godot version

v4.0.alpha13.official [59dcddc45]

### System information

Mac OS X (Catalina) 10.15.7

### Issue description

Autocomplete is too broad that includes any letters typed in.

![image](https://user-images.githubusercontent.com/930478/182007104-b415ed31-6461-488f-85f6-12e330c912ea.png)

### Steps to reproduce

See screen shot

### Minimal reproduction project

see screen shot

**Comment by AaronRecord** [comment]
I believe this behavior is intentional, it allows you to type something like "rb" to bring up Rigidbody

**Comment by ajreckof** [comment]
I think is that it isn't ranked. What I mean is that results that does not need fuzzy search should be above as they are way more accurate. I thought this was already done but it might not be.

**Comment by wyattbiker** [comment]
> I think is that it isn't ranked. What I mean is that results that does not need fuzzy search should be above as they are way more accurate. I thought this was already done but it might not be.

Yes should be ranked and should not be case sensitive.

**Comment by object71** [comment]
Looking at a possible implementation in code we can simply create a custom sorter that will be run around the end of ```CodeEdit::_filter_code_completion_candidates_impl()``` which gives a rank to values that have the letters closer to one another and have values closer to the beginning of the class name. We can even tweak this sorter to give higher priority to built-in types like int, string, etc.

![image](https://user-images.githubusercontent.com/19205853/182201103-99257628-69c8-43ee-ae1d-6c90891fc1da.png)

Something in the line of:

```cpp
struct CodeCompletionRankComparator {
	_FORCE_INLINE_ bool operator()(const ScriptLanguage::CodeCompletionOption &p, const ScriptLanguage::CodeCompletionOption &q) const {

		if (p.matches.is_empty() || q.matches.is_empty()) {
			return false;
		}

		auto distance_between_tokens_accumulator = [](int current, const Pair<int, int> &pos) {
			return current + (pos.second - pos.first);
		};

		int p_distance_between_matches = std::accumulate(p.matches.begin(), p.matches.end(), p.matches[0].first, distance_between_tokens_accumulator);
		int q_distance_between_matches = std::accumulate(q.matches.begin(), q.matches.end(), q.matches[0].first, distance_between_tokens_accumulator);

		return p_distance_between_matches > q_distance_between_matches;
	}
};
```

**Comment by wyattbiker** [comment]
Most of the time, devs will know they are looking for something that begins with '**xyz**'. Autocompletion is meant for typing faster, then possibly for lookup (and if you don't know, you consult the docs).

Trying to be clever about it with spaced out characters matching in the middle is counter intuitive and a hindrance. 

I think the priority should be all strings that _begin_ with **xyz** at the top of list. Any strings that match **xyz** _substring_ fall at the end in the list. No fuzzy logic or mixed in characters.

**Comment by ajreckof** [comment]
I think there are people using fuzzy search and it is in fact good when you miss a letter or forgot there is something in between. But I think that it should be ordered as follow:
- starts with the exact string
- contains the exact string
- Contains the letters in this order ( maybe this should be changed or removed but removing it or changing it should be done in it's separate issue/proposal)

The questions would be how should they be order inside of it.For the first two going by lexicographic order should be good. For the last one I would go for how many part there is in the fuzzy search has search results with a ton of small parts are the ones we want to get rid of.

**Comment by wyattbiker** [comment]
Sounds good. Should it also be case insensitive?

**Comment by ajreckof** [comment]
I think it should be case insensitive as you might forgot to put them or put two instead of one at the end. Maybe it would be good to make case sensitive match ranked higher but not sure if it is that important

**Comment by ajreckof** [comment]
Just finally got the time to test it out. So first effectively i can reproduce your results but it is not about ranking as it seems it is already implemented but only that it is case sensitive and that you are missing the leading case for `String`. 
<img width="490" alt="Capture d’écran 2022-08-02 à 05 09 37" src="https://user-images.githubusercontent.com/66184050/182283547-7cfc8883-ab44-4dd6-b3bd-9bd02113a5fd.png">
So the solution is only to make it case insensitive as a lot of people (me included) forget sometimes the leading case
