### ISSUE TITLE
MaterialShader with swizzled UV2 can't compile

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#6370]
**Operating system or device - Godot version:**
2.1 and 2.0.4.1 win64 stable official.

**Issue description** (what happened, and what was expected):

When I use UV2.x or UV2.y into a Vertex Shader, the shader compilation fails with this error (that i could not copy past as text ) :

![vertex_shader_uv2](https://cloud.githubusercontent.com/assets/9801802/18204272/2efe8a6e-711c-11e6-8da8-acc3794b9a94.png)

**Steps to reproduce:**

```
VERTEX.xyz = VERTEX.xyz + NORMAL.xyz * UV2.x ;
```

if you replace UV2.x with UV.x, or with a constant it will work.

**Link to minimal example project** (optional but very welcome):

**Comment by SuperUserNameMan** [comment]
might be related to #1633

**Comment by quantum-entangler** [comment]
yeah, I don't think UV2 ever worked for me, although i haven't tried lightmapping(since I don't use light maps) perhaps uv2 does work for that.

**Comment by akien-mga** [comment]
That might get solved with the new shader language that @reduz is working on for 3.0 - or might be forgotten, so let's keep it around until it's fixed for real :)

**Comment by reduz** [comment]
closed due to shader code being rewritten for 3.0
