### ISSUE TITLE
Environment with background mode canvas breaks editor and menus on Mac

### ISSUE THREAD

**Issue by Weetbix** [godotengine/godot#63720]
### Godot version

v4.0.alpha13.official [82811367c]

### System information

M1 Macbook Air, Mac OSX Monterey 12.4

### Issue description

When enabling background mode: `Canvas`, the view port doesnt show my assets anymore, but also all the godot menus go blank:
<img width="874" alt="image" src="https://user-images.githubusercontent.com/492636/182024696-fa900677-951a-4b3a-af85-7c3f36870abb.png">

### Steps to reproduce

- Create a new project
- Choose either renderer (It happens with both)
- Create a 2D node
- Add a world environment
- In the environment, set the Background mode option to `canvas`
- Note the viewport goes grey, all the menus also go grey.

**Comment by arkology** [comment]
Duplicate of https://github.com/godotengine/godot/issues/52467

**Comment by Weetbix** [comment]
@arkology Ahhh thank you! I searched but didn't get any hits 🙏

**Comment by AdilDevStuff** [comment]
The same happens on wndows too! Happening from alpha 1.
