### ISSUE TITLE
Can't choose an autocomplete if a mouse pointer is moving

### ISSUE THREAD

**Issue by lanalancia** [godotengine/godot#63726]
### Godot version

3.4.4.stable

### System information

Windows 10

### Issue description

There's an autocompletion hint in a code editor. User can choose a variable, function, etc. The issue is, an autocompletion works only if a mouse pointer standing still. It's not a problem for a most users. I'm using a Virtual Desktop and it's impossible to hold virtual reality controllers still. Also this issue might affect people with tremor as it's complicated forr them to hold sttill a regular mouse

### Steps to reproduce

1) open any project, create any script at GD native or C#
2) start typyng any character to open an autocompletion suggestion
3) move mouse 
4) while moving a mouse, click on a suggestion

Expected result: suggestion is chosen

Actuall result: autocompletion is closed

### Minimal reproduction project

No need. Can be reproduced on an empty project. I have attached a short video footage instead 

https://user-images.githubusercontent.com/96468948/182026794-e8124e6c-6adb-4f8e-8145-349efb315ce9.mp4

**Comment by Calinou** [comment]
The issue is that selecting text causes the caret to move, and therefore cancels the autocompletion dialog. This behavior makes sense when clicking far away, but it shouldn't happen when clicking on the dialog itself.
