### ISSUE TITLE
Observing fast moving Particles2D from a fast moving object causes visual glitch. 

### ISSUE THREAD

**Issue by UltyX** [godotengine/godot#6373]
**bugsquad edit:** issue is still present in 3.0 Reproduction project is in this comment: https://github.com/godotengine/godot/issues/6373#issuecomment-321977789

--------------

Linux Kubuntu 14.04 Godot v2.1stabel 

**Issue description**: Observing fast moving particles from a fast moving object that goes in the same direction makes the particles look jumpy like they are in two places at once.  

**Steps to reproduce:** 
Add player (rigid or kinematic body) and move it fast in one direction with attached current Camera2D.
Add Particles2D to the world and set set_initial_velocity( player.get_linear_velocity() ) and set set_pos(player.get_pos() ). 

**Link to minimal example project**:
[moving_particels.tar.gz](https://github.com/godotengine/godot/files/452465/moving_particels.tar.gz)
( spawns particles on hit return )

**Use case**: Creating hit debris in a space shooter that fly s independent alongside of the ship.

**Comment by mateusak** [comment]
If you're just gonna set it's velocity the same as the player, why make it world?

**Comment by UltyX** [comment]
> If you're just gonna set it's velocity the same as the player, why don't parent it to the player?

So when the player turns the particles keep their speed and direction.

**Comment by bojidar-bg** [comment]
Can confirm from time to time on my game [planetoidee](https://github.com/KOBUGE-Incubator/planetoidee/tree/b83d25a4198f4863d90bbc258334a868bbf8f101). It looks like it is related to global coordinates in my case at least.

**Comment by kubecz3k** [comment]
Can you guys confirm it's still present in 3.0?

**Comment by UltyX** [comment]
The bug is still present. I made a 3.0 compatible minimal example and tested it with alpha 1 and a build of todays master branch. There also might be another 3.0 related bug in the particle system, spawning the test particles had some randomness in its velocity even though I turned all attributes relating to randomness to 0.

Minimal example:
[particels.tar.gz](https://github.com/godotengine/godot/files/1219750/particels.tar.gz)

**Comment by kubecz3k** [comment]
@UltyX thank you for test and example

**Comment by Noshyaar** [comment]
The reproducing project is no longer work with the current master 9ad1800. It still shows some visual glitches but I'm not sure if it's the same as described by OP.

**Comment by UltyX** [comment]
This bug is no longer present in the 3.2.beta4 version of the engine. I updated the reproduction example in case this becomes relevant again in the future. 

Minimal example (resolved):
[particels.tar.gz](https://github.com/godotengine/godot/files/4014175/particels.tar.gz)
