### ISSUE TITLE
Nullify the effects of transform from model to view space to clip space using "" POSITION = vec4(VERTEX, 1.0); "" not working in vulkan

### ISSUE THREAD

**Issue by AmadMuhammad** [godotengine/godot#63748]
### Godot version

Godot_v4.0-alpha13_win64

### System information

Windows 10, Vulkan, Nvidia RTX 3050 (516.59) 

### Issue description

So i was following the Advanced post processing Godot tutorial form the docs(latest) which seems to have been updated for Godot 4 , to get a full screen quad to stay attached to the camera always we bypass its transformations from model to view space to clip space using "" POSITION = vec4(VERTEX, 1.0); "" so it stays in front of the camera all the time this previous like does not work the quad geometry just disappears .

### Steps to reproduce

create new 3d scene with a meshinstance quad of 2x2 size and attach a shader material to it edit the shader and paste the below.

```glsl
shader_type spatial;

varying mat4 CAMERA;

void vertex(){
	POSITION = vec4(VERTEX, 1.0);  //this in not working 
	CAMERA = INV_VIEW_MATRIX;
}

void fragment() {
	float depth = texture(DEPTH_TEXTURE, SCREEN_UV).x;
	vec3 ndc = vec3(SCREEN_UV * 2.0 - 1.0, depth);
	
	vec4 view = INV_PROJECTION_MATRIX * vec4(ndc, 1.0);
	view.xyz /= view.w;
	float linear_depth = -view.z;
	
	vec4 world = CAMERA * INV_PROJECTION_MATRIX * vec4(ndc, 1.0);
	vec3 world_position = world.xyz / world.w;
	
	ALBEDO = vec3(.5);
	ALPHA = depth;
}
```

### Minimal reproduction project

[Bug_Report_Test_Scene.zip](https://github.com/godotengine/godot/files/9229821/Bug_Report_Test_Scene.zip)

**Comment by Calinou** [comment]
PS: Code blocks should use triple backticks like this (with an optional language name for syntax highlighting):

\`\`\`glsl
code here
\`\`\`

I edited your post accordingly, but remember to do this in the future :slightly_smiling_face:

**Comment by makamekm** [comment]
I can repeat this (4.alpha.14)
```glsl
//THIS SHADER MUST BE APPLIED TO A QUAD (MeshInstance) WITH A SIZE OF (2, 2)
//Extra Cull Margin on the quad should be turned up all the way!

shader_type spatial;
render_mode unshaded;

void vertex() {
	POSITION = vec4(VERTEX, 1.0); // this in not working
}

void fragment() {
	ALBEDO = vec3(1.0, 0.0, 0.0);
}
```

**Comment by Calinou** [comment]
Remember that NDCs are different in Vulkan compared to OpenGL: https://docs.godotengine.org/en/latest/tutorials/shaders/advanced_postprocessing.html?highlight=ndc

The shader needs to be adjusted to account for this.

**Comment by FZelin** [comment]
> I can repeat this (4.alpha.14)
> 
> ```glsl
> //THIS SHADER MUST BE APPLIED TO A QUAD (MeshInstance) WITH A SIZE OF (2, 2)
> //Extra Cull Margin on the quad should be turned up all the way!
> 
> shader_type spatial;
> render_mode unshaded;
> 
> void vertex() {
> 	POSITION = vec4(VERTEX, 1.0); // this in not working
> }
> 
> void fragment() {
> 	ALBEDO = vec3(1.0, 0.0, 0.0);
> }
> ```

I don't know if this is a bug
But it looks like the vertices are reversed

You can write it like this

```glsl
//THIS SHADER MUST BE APPLIED TO A QUAD (MeshInstance) WITH A SIZE OF (2, 2)
//Extra Cull Margin on the quad should be turned up all the way!

shader_type spatial;
render_mode cull_front,unshaded; //cull_front can turn it round

void vertex() {
	POSITION = vec4(VERTEX, 1.0); // this in not working
}

void fragment() {
	ALBEDO = vec3(1.0, 0.0, 0.0);
}
```

**Comment by AmadMuhammad** [comment]
@FZelin your suggestion fixed it but why is this happening?

**Comment by clayjohn** [comment]
Either the documentation needs to change to add cull front in the shader, or the QuadMesh can have ``flip_faces`` enabled when it is created. Either is a valid option

**Comment by Scony** [comment]
IMHO `flip_faces` should be enabled by default - that would make porting from Godot 3 easier.

**Comment by Scony** [comment]
Btw. this issue is a duplicate of https://github.com/godotengine/godot/issues/58337
CC @Calinou

**Comment by Chaosus** [comment]
Duplicate of #58337
