### ISSUE TITLE
ColorPicker hue slider (HSV and OKHSL modes) is rotated 90 degrees

### ISSUE THREAD

**Issue by JohanAR** [godotengine/godot#63775]
### Godot version

v4.0.alpha.custom_build [9ec6de176]

### System information

Xubuntu 22.04

### Issue description

Colors on the slider is drawn in the wrong direction

![image](https://user-images.githubusercontent.com/4918549/182152292-2f0c8f7e-1044-4081-98b2-0f9ba7fcc6ea.png)

### Steps to reproduce

Open the color picker, set mode to HSV or OKHSL

**Comment by akien-mga** [comment]
CC @Vitika9 @KoBeWi
