### ISSUE TITLE
Kinematic body does not have physics body option

### ISSUE THREAD

**Issue by Sohamsg77** [godotengine/godot#63772]
### Godot version

3.4.4

### System information

Windows 10

### Issue description

My player just passes through the objects 

### Steps to reproduce

![image](https://user-images.githubusercontent.com/100157206/182142667-99c6ac41-861d-4626-9275-afad88c28421.png)
![image](https://user-images.githubusercontent.com/100157206/182142728-f3f8d7cc-e7fa-4c52-b53a-7c7c2c9b7718.png)

**Comment by Chaosus** [comment]
Please provide a simple example project.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
