### ISSUE TITLE
Particle System Improvement

### ISSUE THREAD

**Issue by mateusak** [godotengine/godot#6377]
Godot's particle system is very simple and does its job very well, but some things can be added to it:

- Random lifetime
- Collision
- Take out the delay it takes to emit particles when emitting is marked or make a emit() function
- Array of colors to choose randomly
- Fix randomness "bug" where if the param is 0 it doesn't do anything. Suggestion: make it more controllable, like if I put direction 10 and random direction 5 then it do 10 + randi_range(-5, 5)
- Graph of size during lifetime

Off topic: add randi_range(min, max). No more cyber-bulling to integers!

**Comment by Sslaxx** [comment]
Seen #6235 then, regarding the random numbers?

**Comment by mateusak** [comment]
@Sslaxx No I didn't. But that's something that I don't see why it's not implemented yet. I mean, they made the hard part, the float version, but skipped the easy one.

**Comment by rgrams** [comment]
IMO each particle parameter should be input as a Vector2: Max and Min. That would be easy and let you choose any range you like.

**Comment by rgrams** [comment]
See also #3994, #4003, and #4294

**Comment by freemanfromgodotengine** [comment]
I will add to this particle improvement general subject. 
It would be great if Godot particle system was able to do things similar to [Hayate Particle Turbulence](http://maxproude.com?p=160) that was available in Unity's Assetstore for previous version of Unity.
Especially two features:
- particles "turbulence" generated from Sine, Cosine, Perlin, Animation Curves, Textures and Audio.
- particles leaving trail.

Watch it in action on https://youtu.be/vG-0RO7e48U

There was a similar request before, so also add #4250

**Comment by reduz** [comment]
currently working on new particle system, this kind of stuff will be
possible

**Comment by maxim-sheronov** [comment]
Hi @reduz 
Is current existed particle system in master branch a **new particle system**? Or is it old and will be replaced in the future?

**Comment by Sslaxx** [comment]
#7199 - related to this issue - is still open.

**Comment by akien-mga** [comment]
If some of the features proposed here are still relevant in the current master branch, I would suggest to add them to this tracker: #20473.
