### ISSUE TITLE
OKHSL Circle (ColorPicker) is too washed out

### ISSUE THREAD

**Issue by JohanAR** [godotengine/godot#63778]
### Godot version

v4.0.alpha.custom_build [9ec6de176]

### System information

Xubuntu 22.04

### Issue description

The color wheel for OKHSL looks washed out. I think it's because it draws sRGB when the fragment shader in Godot 4 expects COLOR to be linear.

![image](https://user-images.githubusercontent.com/4918549/182154905-99d91792-77b9-42df-b40e-152d56cbfc54.png)

### Steps to reproduce

Set inspector to use OKHSL Circle, then open the color picker.

**Comment by Calinou** [comment]
cc @fire

**Comment by fire** [comment]
See https://github.com/godotengine/godot/issues/61697

- [x] Test using red
- [x] Red is wrong. https://bottosson.github.io/misc/colorpicker/ HSV: 0, 100, 100 HSL: 29, 100, 57. RGB: 255, 0, 0
