### ISSUE TITLE
HSV and OKHSL circles are mirrored compared to other programs

### ISSUE THREAD

**Issue by JohanAR** [godotengine/godot#63779]
### Godot version

v4.0.alpha.custom_build [9ec6de176]

### System information

Xubuntu 22.04

### Issue description

So this is a very minor "issue" but I thought I'd log it anyway in case someone wants to do something about it.

ColorPicker hue wheels, both HSV and OKHSL in Godot are mirrored compared to all the other color pickers that I've found. Everybody else seems to use this direction, where 90 degree hue is straight up:

![image](https://user-images.githubusercontent.com/4918549/182157281-efd928d9-eaf0-49f6-b172-b0b78cff294a.png)

While in Godot, 90 degree hue is straight down:

![image](https://user-images.githubusercontent.com/4918549/182157695-d3c8bb88-e966-4a02-b2b6-cd7124c3beb8.png)

### Steps to reproduce

Set the inspector to use one of the circle modes and open the color picker

**Comment by Calinou** [comment]
cc @fire

**Comment by FyiurAmron** [comment]
well, no, but yes, but no, however I would just say this is highly opinionated. See e.g. this standard-ish Win color picker: 
![image](https://user-images.githubusercontent.com/11016998/182164945-edb34bb2-1250-4f38-ace7-f7020d8084ca.png)

It has 0 deg on top, and increases hue value CCW.

But I do agree that many gfx programs actually use the "0 deg on the right, 90 deg on top" convention:

![image](https://user-images.githubusercontent.com/11016998/182165269-811b2f61-8161-47cc-a1b9-47110d7b8fe8.png)

However, there are many notable examples which don't: (this one's from newest Blender)

![image](https://user-images.githubusercontent.com/11016998/182165555-e4b64398-272a-4019-a90b-85f777d3ea47.png)

OTOH, I'd honestly say that having the hue CW is more intuitive to me, and it's just the apps that do the CCW are wrong here.

#itsAFeature IMVHO (maybe just add an option to select CW vs CCW if someone considers this blocking for him?)

**Comment by fire** [comment]
I don't see anything actionable here. Is this correct?

**Comment by JohanAR** [comment]
@fire seems like it's a matter of preference, with no definite right or wrong answer. I'm just used to having Y+ upward, X+ to the right, 0 degrees towards (0, 1) and 90 degrees towards (1, 0), and the examples I found agreed with that :)

**Comment by Calinou** [comment]
Closing per the above comments.
