### ISSUE TITLE
OKHSL Circle (ColorPicker) fails to render high saturation colors on first open 

### ISSUE THREAD

**Issue by JohanAR** [godotengine/godot#63777]
### Godot version

v4.0.alpha.custom_build [9ec6de176]

### System information

Xubuntu 22.04

### Issue description

OKHSL Circle is rendered all-white when opening a highly saturated color for the first time:

![image](https://user-images.githubusercontent.com/4918549/182153349-f7ec721e-cab7-4386-8a0a-44d49251f7ed.png)

However, if I touch one of the sliders the circle is redrawn with better colors (though not the correct colors, but I'll open a separate issue for that). After this the color picker can be closed and reopened, and this does not happen again.

![image](https://user-images.githubusercontent.com/4918549/182153791-bc2ef7c4-8ec2-4c41-bfe5-7ddbd8f3dec9.png)

### Steps to reproduce

Set Godot inspector to use OKHSL Circle. Create a project containing something with a color, which is set to high saturation (e.g. #fd00ff, #00ff00), save and close.

Open the project again and click the color.

Move the slider back and forth.

**Comment by Calinou** [comment]
cc @fire

**Comment by fire** [comment]
Can someone assist me with this? I have limited capacity and working on the color is not the same okhsl bug.

**Comment by JohanAR** [comment]
I can try to investigate it a little bit

**Comment by JohanAR** [comment]
Think I've got it. Just need to test a little bit more and clean up.
