### ISSUE TITLE
Documentation: @GDScript and @GlobalScope are at the bottom of the list

### ISSUE THREAD

**Issue by fire-forge** [godotengine/godot#63799]
### Godot version

v4.0.alpha.custom_build [98c1fb396]

### System information

Windows 10

### Issue description

The `@GDScript` and `@GlobalScope` items are at the bottom of the list in the documentation search window. They used to be at the top.

![image](https://user-images.githubusercontent.com/67974470/182262258-5a281834-822e-4026-a83d-bd13adc620ee.png)

### Steps to reproduce

* Press F1
* Look at the top and see that `@GDScript` and `@GlobalScope` are not there
* Scroll to the bottom to find them

**Comment by AThousandShips** [comment]
Fixed by:
* https://github.com/godotengine/godot/pull/77554
