### ISSUE TITLE
Error in console while duplicate a node from instanciate scene with animations

### ISSUE THREAD

**Issue by Datoh** [godotengine/godot#63796]
### Godot version

4.0alpha13 (82811367)

### System information

Windows 10

### Issue description

When duplicate a Node that is an instancied child scene that conatins an AnimationPlayer, I have error in the log:
```
E 0:00:00:0924   _ready: Attempt to disconnect a nonexistent connection from '[Animation:-9223372010933976578]'. Signal: 'tracks_changed', callable: 'AnimationPlayer::_animation_changed'.
  <C++ Error>    Condition "signal_is_valid" is true.
  <C++ Source>   core/object/object.cpp:1295 @ _disconnect()
  <Stack Trace>  test.gd:4 @ _ready()
```

### Steps to reproduce

Create a "child" scene with a Sprite and an AnimationPlayer with at least one animation.
Create a scene which contains the instancied "child" scene.
Add a script to the scene which duplicate the "child" scene and add it to the root

### Minimal reproduction project

[Bug_duplicate_animation.zip](https://github.com/godotengine/godot/files/9237359/Bug_duplicate_animation.zip)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/62288.
