### ISSUE TITLE
Godot keeps on crashing whenever i test my game.

### ISSUE THREAD

**Issue by Noopch** [godotengine/godot#63800]
### Godot version

3.4.4

### System information

Windows 10

### Issue description

as soon as i test my game, it keeps on saying "Godot is not responding, reporting issue to microsoft". the game doesnt even start. whats more baffling is that theres not a lot on screen, but it still crashes anyways

### Steps to reproduce

theres no code in the game yet, its just an asset and its sprite

**Comment by Calinou** [comment]
@Noopch Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by bend-n** [comment]
How does this "need testing"? It needs information!

**Comment by Noopch** [comment]
even if i dont add any code it just crashes, im also using GLES3

**Comment by bend-n** [comment]
upload the folder, images and everything.

**Comment by Noopch** [comment]
nevermind, its working now!
