### ISSUE TITLE
Pressing delete after selecting a SpriteFrame animation frame deletes the selected node

### ISSUE THREAD

**Issue by tioalexis** [godotengine/godot#63804]
### Godot version

v4.0.alpha.calinou [8243c7ab5]

### System information

Windows 10

### Issue description

[Preview](https://i.imgur.com/A33hVvv.mp4)

Pressing the delete key after selecting a SpriteFrame animation frame deletes the selected node instead of the selected animation frame. The delete key should be context-aware and should always delete the last item the user has selected.

This seems to be working fine in the FileSystem panel where it deletes the selected file instead of the node in the scene.

### Steps to reproduce

1. Create a new project.
2. Create a new SpriteFrame resource.
3. Add animation frames to the SpriteFrame resource.
4. Create a new scene with an AnimatedSprite2D node.
5. Assign the SpriteFrame resource to the AnimatedSprite2D node.
6. Select a frame in the SpritFrames panel.
7. Press the delete key.
8. A prompt saying "Delete node" appears.
9. Press OK.
10. The node is deleted in the scene.

**Comment by KoBeWi** [comment]
Deleting animation doesn't have shortcut.

**Comment by EricEzaM** [comment]
Do we try add a shortcut for it? Otherwise this can be closed.

**Comment by KoBeWi** [comment]
If it's not complicated then why not.

**Comment by EricEzaM** [comment]
None of those buttons have shortcuts though, if we add it to delete, should they all get one? I suppose why not, if the shortcut context is set properly it won't interfere with anything else most likely.

**Comment by TheYellowArchitect** [comment]
Pressing delete after selecting a spriteframe animation, should delete the spriteframe.
But also when you select an animation (not a frame), and press Delete, it should delete the animation (it currently also deletes AnimatedSprite2D node)
