### ISSUE TITLE
You cannot click frames in "Select Frames" to remove from selection

### ISSUE THREAD

**Issue by idbrii** [godotengine/godot#63811]
### Godot version

3.4.4.stable

### System information

Win10

### Issue description

(I'm brand new to Godot.)

Clicking to deselect frames in the "Select Frames" window doesn't work. After more experimentation I can drag from frame 1 to frame 2 to keep frame 1 selected, but unselect frame 2.

I'd expect that clicking on a single frame would toggle its state and that dragging would either toggle the states of the frames dragged over or the toggled state of the clicked frame to be applied to all dragged over frames.

https://user-images.githubusercontent.com/43559/182316711-84084ecb-d695-4cf8-8338-9a76903f4bb7.mp4

### Steps to reproduce

1. Create Node
1. Add AnimatedSprite child
1. find the Frames property in the Inspector and click "[empty]" -> "New SpriteFrames". Click again to open the "SpriteFrames" panel.
1. Click the grid icon
1. Open a spritesheet.
1. Select the correct row/column sizes.
1. Click on some of the spritesheet frames to select them.
1. Click on some of the selected spritesheet frames to unselect them.

## Expected
They are unselected.

## Actual
Nothing happens when you click on a selected sprite.

**Comment by kleonc** [comment]
>You cannot click frames in "Select Frames" to remove from selection

You can, when pressing <kbd>Control</kbd>. I've noticed that after looking into the source code. So yeah, I agree, it's not obvious/intuitive.
Current drag-toggling is also strange/unintuitive. I'd just remove it and make selecting/deselecting be done by LMB/RMB press (including dragging).

**Comment by pjalsGit** [comment]
Didn't you already report this in #63810?

**Comment by idbrii** [comment]
@pjalsGit I mentioned it there, but #63810 is a general workflow issue and this piece seemed like actual broken behaviour. The contributing guide said:

> The golden rule is to always open one issue for one bug. If you notice several bugs and want to report them, make sure to create one new issue for each of them.

So I figured this was worth separating.

**Comment by Calinou** [comment]
Can you test 3.3.4 to see if the issue exists there? I wonder if this is a regression from https://github.com/godotengine/godot/pull/47802, which was first introduced in 3.4.

**Comment by idbrii** [comment]
@Calinou The issue does not exist in 3.3.4.

Testing with Godot_v3.3.4-stable_win64, I can click to toggle frame selection. I cannot drag select to do anything:

https://user-images.githubusercontent.com/43559/184446374-450216c7-5d1f-4db6-b5db-b490154f549f.mp4

**Comment by Calinou** [comment]
@idbrii Can you reproduce this in any of the [3.4 betas and RCs](https://downloads.tuxfamily.org/godotengine/3.4/) to determine when the regression started?

**Comment by kleonc** [comment]
It got broken when cherry-picking, one line change (L127/R155) was incorrectly not picked :
https://github.com/godotengine/godot/commit/ad7a6102aed9ca25524d169570c29a599ab8e2a5#diff-3e7f486c64d2a3de1a4c3fcde4afc7705675df0adf3af634f78f67ebbaf4bddbL127-R156
https://github.com/godotengine/godot/commit/891681a5a328dd80630f1e75c7b8430d32125511#diff-3e7f486c64d2a3de1a4c3fcde4afc7705675df0adf3af634f78f67ebbaf4bddbR155-R156

I'll open a PR.

**Comment by akien-mga** [comment]
Fixed by #64358.
