### ISSUE TITLE
Graph nodes change width while being dragged around

### ISSUE THREAD

**Issue by UgisBrekis** [godotengine/godot#6381]
**Operating system or device - Godot version:**
Windows 10, Godot Engine v2.2.alpha.custom_build(however I've noticed this behavior in previous versions as well)

**Issue description** (what happened, and what was expected):
The graph nodes start to grow in width when being dragged around. I noticed that this behavior happens when the node gets past the center of graph editor, however that could also be when the node get's past the certain location of the grid. This also happens when I pan around with middle mouse. 

**Steps to reproduce:**
Add node, place it past center position and start dragging around- it's size will change. For a preview please have a look at gif. 
The current issue is about Visual Script editor, however this can also be achieved in Shader Graph editor as well. 

**Link to minimal example project** (optional but very welcome):
![shader_graph_node_scale](https://cloud.githubusercontent.com/assets/9309589/18224106/fb63f5d4-71c2-11e6-86f9-2f2318d9640a.gif)

**Comment by quantum-entangler** [comment]
same issue exists with shadergraph(and has existed since 1.0) and at this point I's assume with animationtree nodes too although shadergraph nodes expand along the other axis affecting their height.

**Comment by reduz** [comment]
wow never realized that.. fantastic numerical precission issue..

**Comment by fire** [comment]
Is this still happening in master?

**Comment by sparkart** [comment]
No, tested this with version: 3.2.dev #30891 and seems to be fixed.

**Comment by fire** [comment]
Thanks.
