### ISSUE TITLE
Problems in exporting IOS projects

### ISSUE THREAD

**Issue by jl1872002** [godotengine/godot#63821]
### Godot version

4.0 -  alpha 13

### System information

mac 11.5.2

### Issue description

Images.xcassets/launchimage.launchimage   was not exported!

error:
Cannot open directory '/Users/xxxx/godotTest/GodotOutput/output/GodotOutput/Images.xcassets/LaunchImage.launchimage/'.

### Steps to reproduce

1 exporting IOS projects

![image](https://user-images.githubusercontent.com/5889641/182362407-4449e3dd-9d24-4d2e-9e6e-040b0a68f0ac.png)

![image](https://user-images.githubusercontent.com/5889641/182362527-abe09236-574a-45f1-bafb-ad4a6db4e01c.png)

![image](https://user-images.githubusercontent.com/5889641/182362783-59570673-ccaa-4120-a750-46c92af4ce7b.png)

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/63841, which has more information.
