### ISSUE TITLE
Editor: CTRL-X deletes whole SceneTree from Help View

### ISSUE THREAD

**Issue by just-like-that** [godotengine/godot#63828]
### Godot version

v3.4.5.stable.official [f9ac000d5]
This behavior happens at least with all V3.4.* versions.

### System information

Windows 10

### Issue description

By pressing Ctrl-X instead of Ctrl-C in currently shown help page leads to cut out of last selected node from active Scene Tab.
This might be the whole SceneTree in some cases, in other cases it's just part of the actual tree w/o warning.
So basically nodes in the background are deleted (cut-out) although the command was applied to the current open Help.
Pressing Ctrl-C instead behaves like normal and copies text from the Help page into Clipboard and NOT any selected node.

### Steps to reproduce

Have any project you like - big or small - it does NOT matter.

In the Scene Tab make the root Scene Tree node the selected one by placing your cursor there via mouse button click.
(Any node will do.)

Open Help via F1 to lookup some info.

For instance, in the now open Popup search for Geometry class and open help with its description.

Select any text you like from this help page - e.g. the method name of build_box_planes(...)

and (accidentally like in my case) press CTRL-X "CUT" instead of CTRL-C "COPY"
 
and all your nice scene tree nodes are gone.

Variation:
Pressing DEL instead of CTRL-X brings at least a warning and asks politely if I want to delete the node.

### Minimal reproduction project

N/A - user interaction involved in the editor.

**Comment by EricEzaM** [comment]
Thanks - this issue is being tracked here #52861.

Will link this there and close this one as a duplicate. It is indeed the same issue as #63831, where shortcuts can be triggered on 'background' elements.
