### ISSUE TITLE
Godot 4 simple button app takes over 40 seconds to launch 

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#63836]
### Godot version

v4.0.alpha13.official [59dcddc45]

### System information

Mac OS X (Catalina) 10.15.7

### Issue description

When I run the button app it takes 40 seconds before it shows the screen. This includes a compiled exported .app.
 Using GD3 it is pretty much instant. 

I don't know if it's related to some errors I see in the debugger or maybe its because alpha has too much debugging code in it. See attached.

![image](https://user-images.githubusercontent.com/930478/182437301-0a30345b-fb13-4bb3-871b-9af8aefbc01f.png)

### Steps to reproduce

Create a simple one button scene. 
Run it.

**Comment by Calinou** [comment]
When using Vulkan, starting a project for the first time (or after a engine or graphics driver update) will always be slower than OpenGL due to the shader cache having to be generated: https://github.com/godotengine/godot-proposals/issues/3657

**Comment by wyattbiker** [comment]
What should I do to be able to do some reasonable testing. Do I need to install MoltenVK? Any documentation as it relates to Godot 4?

**Comment by Calinou** [comment]
> What should I do to be able to do some reasonable testing.

The OpenGL renderer in 4.0.alpha13 is broken, so you unfortunately can't test it for now.

> Do I need to install MoltenVK?

No, as MoltenVK is already included with Godot 4.0 (pre)releases. You only need to install the Vulkan SDK (which includes MoltenVK) when compiling Godot from source.
