### ISSUE TITLE
Editor: InputMapping destroys the source code silently in the background

### ISSUE THREAD

**Issue by just-like-that** [godotengine/godot#63831]
### Godot version

3.4.X

### System information

Windows 10

### Issue description

Commands of shortcuts are being carried out in the background if 
any key combination in an input mapping of a project is also a shortcut of the editor during entering such a key combination.
 
The Keyboard mapping is also a Shortcut of the editor and is being passed through.

The currently active input mapping dialog should block every shortcut from being carried out in the background.

### Steps to reproduce

Open input map via [Project]->[Project Settings]->Tab: [InputMap]

Add a new action with name e.g. "code_twist" by entering name and pressing button "Add".

Go to action and make a key mapping by pressing plus "+" icon and selecting Key.

Now enter Alt + "Cursor UP" / Alt + "Cursor DOWN" whatever your prefer.

Your currently active source code file lines are getting muddled up a little bit in the background because these are valid shortcuts for MOVE DOWN or MOVE UP. 

### Minimal reproduction project

N/A - user interaction with the editor.

**Comment by just-like-that** [comment]
There is a high chance that this has something to do with the same behavior of this:
[https://github.com/godotengine/godot/issues/63828](https://github.com/godotengine/godot/issues/63828)

**Comment by Calinou** [comment]
This is likely fixed in 4.0 since editor input handling was rewritten.

**Comment by just-like-that** [comment]
So for the time being ourselves have to switch off specific editor shortcuts like Alt + "Cursor UP" / Alt + "Cursor DOWN" prior to using them in our own input mapping.

**Comment by EricEzaM** [comment]
As with https://github.com/godotengine/godot/issues/63828, this type is issue is tracked here: #52861

Thanks for the detailed reports. If the issue gets fixed in 3.X, they will help with testing to ensure such cases are all fixed.
