### ISSUE TITLE
Alpha 13 has reoccurring trouble with png assets

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot#63832]
### Godot version

4.0 alpha 13

### System information

Linux Manjaro, Vulkan, Intel Kaby Lake

### Issue description

>   modules/webp/image_loader_webp.cpp:148 - Condition "r[0] != 'W' || r[1] != 'E' || r[2] != 'B' || r[3] != 'P'" is true. Returning: Ref<Image>()
>   scene/resources/texture.cpp:684 - Condition "img.is_null() || img->is_empty()" is true. Returning: Ref<Image>()
>   Failed loading resource: res://.godot/imported/car at night.png-b44051ef36e5668aa1e358f4486b1816.ctex. Make sure resources have been imported by opening the project in the editor at least once.
>   Failed loading resource: res://hud/car at night.png. Make sure resources have been imported by opening the project in the editor at least once.
>   scene/resources/resource_format_text.cpp:171 - res://hud/main_menu.tscn:17 - Parse Error: [ext_resource] referenced non-loaded resource at: res://hud/car at night.png
>   Transient parent has another exclusive child.

( The last line is probably a red herring, and repeat ad infinitum for EVERY png asset in the project as I try to open related scenes)

### Steps to reproduce

Open a project that worked in previous alphas in alpha 13. Problem will temporarily go away upon forcing reimport (i.e. nuking .imported) but then will reappear after relaunching Godot later.

Is super annoying because affected project will open in editor, at least partially, but NOT run (and with NO errors in output upon trying to run), and because it was seemingly fixed earlier.

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
This shouldn't happen once `.godot/imported` has been deleted, unless you re-open that project in older alphas.

**Comment by korompg** [comment]
I'm exporting for android and I get this error for both png and jpg files. Tried exporting with .godot/imported deleted too but the same thing happens.

**Comment by korompg** [comment]
Tried with bmp format too. Same error. Here's my minimal reproduction project. It's for VR and I'm testing it on a Quest 2. Also I'm exportin from Linux (Ubuntu 20.04) if that counts.
[godot_4_alpha13_resource_loading_test.zip](https://github.com/godotengine/godot/files/9259869/godot_4_alpha13_resource_loading_test.zip)

**Comment by korompg** [comment]
Deleting .godot/imported won't fix it for me.

**Comment by korompg** [comment]
So, there are some inconsistencies here. When I export the apk, the .godot/imported folder contains 3 .etc2.ctex files each corresponding with the 3 image files in the project folder. These are supposed to be the compressed texture files the installed app loads when running. But when I run it, for some reason it looks for the .s3tc.ctex files which don't get exported into the apk and I get these errors:

USER ERROR: Unable to open file: res://.godot/imported/icon.bmp-9d1de709bb464c1beb38c8bc584bca25.s3tc.ctex.
at: _load_data (scene/resources/texture.cpp:823) - Condition "f.is_null()" is true. Returning: ERR_CANT_OPEN
USER ERROR: Failed loading resource: res://.godot/imported/icon.bmp-9d1de709bb464c1beb38c8bc584bca25.s3tc.ctex. Make sure resources have been imported by opening the project in the editor at least once.
at: _load (core/io/resource_loader.cpp:222) - Condition "found" is true. Returning: Ref<Resource>()
USER ERROR: Failed loading resource: res://icon.bmp. Make sure resources have been imported by opening the project in the editor at least once.
at: _load (core/io/resource_loader.cpp:222) - Condition "found" is true. Returning: Ref<Resource>()

Why does this happen?

![Screenshot from 2022-08-04 15-57-27](https://user-images.githubusercontent.com/102245985/182865322-5a030d4a-2c72-4252-be28-afa6617cfc40.png)

**Comment by akien-mga** [comment]
That's because the Quest 2 was updated to advertise support for S3TC, which is so uncommon on Android that Godot is not designed to handle it properly and so it doesn't export S3TC for Android.

This was worked around in 3.4.5 and 3.5 with https://github.com/godotengine/godot/pull/62909.
We can do the same for 4.0 until we decide to refactor this further if/when we see a use for S3TC on mobile (which only a few devices can use).

So it's not the same issue as @Zireael07's in the end.

**Comment by Zireael07** [comment]
Closing then, since it looks resolved on my end. Hopefully won't happen again
