### ISSUE TITLE
Geometry2D.segment_intersects_circle missing in latest master

### ISSUE THREAD

**Issue by and3rson** [godotengine/godot#63845]
### Godot version

4.0-alpha13

### System information

ArchLinux

### Issue description

Not sure if this is a regression, if the function has been moved somewhere, or if it was considered obsolete. In 3.x, it's available as `Geometry.segment_intersects_circle`

Meanwhile, other helper functions including `segment_intersects_segment` are still available in 4.x.

### Steps to reproduce

1. `Geometry2D.segment_intersects_circle(...)`
2. Error: Static function "segment_intersects_circle()" not found in base "Geometry2D".

Missing in 4.x: https://docs.godotengine.org/en/latest/search.html?q=segment_intersects_circle&check_keywords=yes&area=default
Available in 3.x: https://docs.godotengine.org/en/stable/search.html?q=segment_intersects_circle&check_keywords=yes&area=default

**Comment by Calinou** [comment]
References to `segment_intersects_circle` in the issue tracker: https://github.com/godotengine/godot/issues?q=segment_intersects_circle

**Comment by kleonc** [comment]
Seems like the binding got lost when splitting in #39051. Method was moved, the binding was removed. So it's just a matter of re-adding the binding in [`Geometry2D::_bind_methods()`](https://github.com/godotengine/godot/blob/2c0c76c415f1b8b7d46f63d12b12ef56c8c85f4d/core/core_bind.cpp#L934).

**Comment by hakro** [comment]
I gave it a go. Let me know if I missed something.
