### ISSUE TITLE
Impossible to set SVG Scale in Import Defaults

### ISSUE THREAD

**Issue by noidexe** [godotengine/godot#63840]
### Godot version

v4.0.alpha12.official [2c11e6d9e]

### System information

Manjaro Linux, RTX 2060 SUPER, Vulkan

### Issue description

When importing SVGs it is possible to set the import scale using the Import panel. However there is no way to set a per project default since "SVG scale" doesn't appear in Project Settings->Import Defaults->Texture2D nor there is a SVG Importer to choose.

### Steps to reproduce

- Open Project Settings
- Go to Import Defaults
- Select Texture2D
Expected: SVG scale should appear as a property since it's imported as Texture2D
Actual: No SVG scale property present

### Minimal reproduction project

Doesn't apply

**Comment by KoBeWi** [comment]
Might be related to #56850
