### ISSUE TITLE
Camera set_frustum_offset(value) not working in 3.5

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot#63849]
### Godot version

3.5.rc7

### System information

Windows 10

### Issue description

Trying to set `set_frustum_offset(value)` on a 3D perspective camera does nothing, using `get_frustum_offset()` returns whatever it is set to, but the camera itself does not look any different. The docs mention using it for y-shearing, but this does not seem possible.

### Steps to reproduce

1. Add a camera node to the scene with a script
2. Set the `set_frustum_offset()` value
3. Nothing changes about the camera's appearance

**Comment by Calinou** [comment]
You need to set the camera's perspective mode to Frustum, not Perspective or Orthogonal.

**Comment by elvisish** [comment]
> For frustum offset to work, you need to set the camera's **Projection** mode to Frustum, not Perspective or Orthogonal.

I think this should be mentioned in the docs, especially when the linked article is referencing Doom's y-shearing technique, which I'm not sure can be accomplished using a perspective camera at all without access to the camera matrix (which I don't believe Godot has?)

**Comment by Calinou** [comment]
> which I'm not sure can be accomplished using a perspective camera at all without access to the camera matrix (which I don't believe Godot has?)

As I mentioned in https://github.com/godotengine/godot-proposals/issues/2713#issuecomment-1203565263, it can be done already :slightly_smiling_face:
