### ISSUE TITLE
Minimap bottom area selects/drags code instead

### ISSUE THREAD

**Issue by jgillich** [godotengine/godot#63842]
### Godot version

515552860b2eb1ac5f10e7266507a3e92f824fde

### System information

Fedora Silverblue 36, Ryzen 2400G

### Issue description

The bottom area of the code minimap cannot be used to scroll the code window, mouse inputs are instead sent to the underlying editor, resulting in code being selected/dragged.

https://user-images.githubusercontent.com/347965/182465164-a5c020ae-d48b-4521-8074-350864d8d677.mov

### Steps to reproduce

1. Open a file with ~300 LOC
2. Attempt to scroll from the bottom of the minimap

**Comment by MewPurPur** [comment]
Can't reproduce on an Ubuntu 22

**Comment by jgillich** [comment]
Me neither, appears to be fixed

**Comment by jgillich** [comment]
I spoke too soon. When the window is maximized, it does not happen. But when the window is attached to the right half of the screen, it does: https://streamable.com/936lwj

Can you try reproducing it like that?

**Comment by jgillich** [comment]
Also doesn't happen in non-maximized mode when not snapped to either side of the screen. Very odd, might be related to GNOME somehow..
