### ISSUE TITLE
Unknown, silent locking up with a project.

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#6384]
**Operating system or device - Godot version:**
Godot 2.1+. Ubuntu 16.04 64-bit, also tested on Windows 8.1 64-bit.

**Issue description** (what happened, and what was expected):
This project silently locks up when you attempt to load it. No warnings or errors are printed on the terminal. CPU core usage shoots up to 100%+. On Linux, the only way to kill the process was from the terminal.

Further investigation by @SuperUserNameMan appeared to pinpoint the issue to Assets/UI/Themes/Default.tres, in particular the `[ext_resource path="res://Assets/Fonts/Roboto-Regular-16-bitmap.fnt" type="BitmapFont" id=1` line, though replacing the font does not resolve the issue. Editing the .tres file (or deleting it outright) also does not resolve this.

**Steps to reproduce:**
Unsure, but see link to project where this issue arose.

**Link to minimal example project** (optional but very welcome):
https://dl.dropboxusercontent.com/u/67740160/Rogue_State_Lock.7z

**Comment by vnen** [comment]
The `radial_fill/initial_angle` property of the `nodRootMain/panCapitalists/Love_Hate_Bar` node on the `res://Scenes/scnMain.tscn` has an immensely huge value (2.60751e+24). Since the TextureProgress [decrements in steps of 360](https://github.com/godotengine/godot/blob/ee37c2f4330e9bd247576b5834cd2660cb520e13/scene/gui/texture_progress.cpp#L221) to normalize into the basic range, it takes way too long.

Not sure how that value got there, but if you open the scene file in a text editor and replace the value for zero the scene then loads fine.

**Comment by Sslaxx** [comment]
Odd, because I have no idea either. As far as I were aware all values were within normal limits. It had not been something I'd edited.

**Comment by SuperUserNameMan** [comment]
@vnen : here this value is set to 1.3776e-38.
Even if I replace by 0.0, I still can't load the project.

**Comment by vnen** [comment]
@SuperUserNameMan you've seen another node. 1.3776e-38 is a very tiny number (probably made from float imprecision) but this gives me an insight: if the `-` is replace by a `+` the number changes a lot. Maybe there's a problem with the code that converts to the notation.

**Comment by SuperUserNameMan** [comment]
@vnen : yes i confirm that i confused liberals and capitalists nodes.

**Comment by mateusak** [comment]
That could be replaced by

	if(p_angle>360)
		p_angle-=360 * floor(p_angle / 360);
	elif (p_angle<0)
		p_angle+=360 * ceil(p_angle / -360);
	rad_init_angle=p_angle;
	update();

Although I don't know C++ that's how I'd do it in GDScript.

**Comment by vnen** [comment]
I believe using `fmod(p_angle, 360)` should be enough.

**Comment by mateusak** [comment]
I don't really understand fmod(). I mean it should return the remainder, right? But it's float based, so the remainder should always be 0. Why is it not?

**Comment by vnen** [comment]
@mateusak `fmod()` is also the remainder but it doesn't allow more decimal places than the operands, so it's not always exact, thus there's a remainder. It's literally the same as the current code (subtracting a fixed value until the result is smaller).

**Comment by mateusak** [comment]
I see. Thanks!

**Comment by Sslaxx** [comment]
Coming back to this with the intent of closing it: is it fixed? By pull #6427 or others?

**Comment by bojidar-bg** [comment]
Well, should be impossible to reproduce the issue, though it would be nice if we replace similar `while` loops with `fmod`.

**Comment by Sslaxx** [comment]
OK, going to close this one. Sounds like the `while`/`fmod` situation could do with a general discussion/tracker issue regarding optimisations.
