### ISSUE TITLE
New TileMap Editor can push Inspector off-screen

### ISSUE THREAD

**Issue by snailrhymer** [godotengine/godot#63851]
### Godot version

v4.0.alpha13.official [59dcddc45]

### System information

Pop!_OS 22.04 LTS

### Issue description

https://user-images.githubusercontent.com/61291296/182488791-fe85793c-00bb-4d4b-9b47-cff5a32ec75a.mp4

When items are added to the top bar of the tilemap editor, the inspector can be pushed off screen. This is particularly problematic on lower-resolution monitors - on a 1280x1024 the inspector is nearly entirely offscreen with the editor maximised.

### Steps to reproduce

Add a tilemap to an empty scene and click on the bucket fill tool. Shrink the editor window until the inspector is forced off screen.

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/31133 (same cause, but needs to be fixed in a different location).
