### ISSUE TITLE
Vulkan: LightOccluder2D casts weird shadows after an occluder polygon is edited

### ISSUE THREAD

**Issue by FluffyLuffie** [godotengine/godot#63850]
### Godot version

4.0 3b39f00

### System information

Windows10, AMD Radeon RX 5700 XT, Vulkan

### Issue description

LightOccluder2D bugs out when dragging the polygon points in editor.

https://user-images.githubusercontent.com/76981608/182487047-7cda7e68-1faf-4a55-98bb-101f68d93a89.mp4

### Steps to reproduce

Drag around the points on the LightOccluder2D polygon.

### Minimal reproduction project

[gd4Test.zip](https://github.com/godotengine/godot/files/9246139/gd4Test.zip)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/55806 (but not the same issue).
