### ISSUE TITLE
Android IAP: Leave in core or create a separate module?

### ISSUE THREAD

**Issue by jlopezcur** [godotengine/godot#6385]
I worked on Android IAP from the core, I will made a PR for this, but a doubt come to me: It is a module like, is there any interest on make this as a module or better leave in the code?

If you want to see this working you can see on:
https://godotdevelopers.org/forum/discussion/17400/monty
(I dont want to put the Google Play link directly beacouse this is for developing purpose only, not for promo)

I want to put other doubt on the table:
I'm thinking that the best way to make a good export to Android with modules is by separating the code of creating a template into a plugin like the asset manager (with gradle), the plugin will be able to compile templates and export to Android (for example), and all modules could be dropped and customize the entire exportation. It this in mind or something?

Comments are very appreciated :)
Thanks!

**Comment by ArcFutahito** [comment]
Godot doesn't target Android "by default". All vendor specific features should come in modules IMHO.

**Comment by volzhs** [comment]
take a look #3936 discussion too

**Comment by reduz** [comment]
I was thinking of creating a "google" module, for providing all the
standard Google APIs, including IAP, Google Play, etc.

**Comment by vnen** [comment]
I still think IAP can be abstracted with a common interface for all platforms. Having one for each means you need to write conditional code and be acquainted with different API to do the same thing.

**Comment by avril-gh** [comment]
> I was thinking of creating a "google" module, for providing all the
> standard Google APIs, including IAP, Google Play, etc.

wow, that could be great thing

**Comment by punto-** [comment]
If it depends on more or less standard APIs of Android, leaving it in the
main tree saves you from re compiling all the templates when you need to
build, which can get annoying, although not so much if it's limited to just
Android. An IAP module for Amazon Store would be an external module for
sure..

**Comment by mefihl** [comment]
> I was thinking of creating a "google" module, for providing all the
standard Google APIs, including IAP, Google Play, etc.

Yes please ;)

**Comment by jlopezcur** [comment]
I have a lot of work on this area created:
- Google Analytics (https://github.com/jlopezcur/GodotGoogleAnalytics)
- Firebase (as Google Analytics)
- Admob (As is now in other repos and in my own: https://github.com/jlopezcur/GodotAdmob)
- GooglePlayGamesServices (https://github.com/jlopezcur/GodotGooglePlayGameServices but need a complete refactoring):
    - Achievements
    - Leaderboards
    - Saved games, Snapshots on the cloud (not published on repo yet)
    - Client connections (solved a lot of problems on network disconnection and first connections)
- Share (A better way to share as launch an intent in the correct way, not only a link)
- Google IAP (worker)

All of this are working on the game: https://play.google.com/store/apps/details?id=com.kloder.monty

A lot can be done on GooglePlayGamesServices as:
- Real-time multiplayer
- Turn-base multiplayer (In our next game we are planning to use it)
- Events and quest
- Game gifts
- Player stats
- Nearby connections (In our next game we are planning to use it)
- Video recording

I find some problems for a modules implementation that work right without compiling new templates:
- GooglePlayGamesServices required that a file with the configuration (google-services.json) to be on: platforms/android/java
- GooglePlayGamesServices and the new APIs (classpath 'com.google.gms:google-services:3.0.0') need some changes on platforms/android/build.gradle.template

These are common problems encounter in create a module independant ecosystem, how this could be done?

@reduz 
"I was thinking of creating a "google" module, for providing all the
standard Google APIs, including IAP, Google Play, etc."

So this mean that the IAP move from the core to a module, right?

**Comment by lukaskotik** [comment]
@jlopezcur Wow! That is something that I missed a lot in Godot engine. I would like to see it as easily to access all these functionalities as possible (in core).

**Comment by Heryhelder** [comment]
> I was thinking of creating a "google" module, for providing all the
standard Google APIs, including IAP, Google Play, etc.
Is it still alive for Godot 3? Maybe provide "google" module in AssetLib is a good thing

**Comment by m4gr3d** [comment]
Closing as the described functionality can be made available through an [Android plugin](https://docs.godotengine.org/en/stable/tutorials/plugins/android/android_plugin.html).
