### ISSUE TITLE
Exporting a project to Linux oo Windows no longer works (regression from 4.0.alpha12 -> alpha13)

### ISSUE THREAD

**Issue by LD2Studio** [godotengine/godot#63860]
### Godot version

4.0.alpha13

### System information

Kubuntu 20.04, Intel i5-2500, 16Go, NVIDIA GTX1650

### Issue description

When i want to export my project to Linux or Windows, a error message appeared.
```
Failed to open 
  ./editor/export/editor_export_platform.h:150 - Prepare Template: Failed to copy export template.

```
However, it work with Alpha 12. 

### Steps to reproduce

Just export with an empty project to Linux or Windows.

**Comment by akien-mga** [comment]
See the update on the alpha 13 post, this was hotfixed a few hours after the release, you should redownload your editor build: https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-13

**Comment by LD2Studio** [comment]
I had not seen that the bug fix was so fast. Thanks
