### ISSUE TITLE
Vulkan: Sky orientation is incorrect when using Camera3D's Frustum projection mode with non-zero frustum offset

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#63863]
### Godot version

4.0.alpha (1839cae8a)

### System information

Fedora 36, GeForce GTX 1080 (NVIDIA 515.57)

### Issue description

Sky orientation is incorrect when using Camera3D's Frustum projection mode with non-zero frustum offset:

https://user-images.githubusercontent.com/180032/182549989-daa6609a-69a2-44b3-a575-649cabc266c3.mp4

This does not occur on 3.5.rc f9db8fa70. The expected behavior is that the horizon line remains at the same height relative to the floor, like in the video contained in https://github.com/godotengine/godot/issues/63864.

### Steps to reproduce

Download the MRP below, run the project and move the mouse around. (The MRP aims to simulate [Y-shearing](https://zdoom.org/wiki/Y-shearing), see https://github.com/godotengine/godot-proposals/issues/2713#issuecomment-1203565263.)

### Minimal reproduction project

[test_y_shearing_master.zip](https://github.com/godotengine/godot/files/9249002/test_y_shearing_master.zip)

**Comment by EnlightenedOne** [comment]
FYI I haven't traced where yet but I think the underlying issue causing the frustum to be misaligned has been fixed on main already.
