### ISSUE TITLE
FileDialog not showing buttons until moved

### ISSUE THREAD

**Issue by ruipsrosario** [godotengine/godot#6386]
**Operating system or device - Godot version:**
PC - Windows 10 64bit - Godot 2.1 (stable)

**Issue description** (what happened, and what was expected):
I have a project in which I created two FileDialog instances. When I press a button to show the Dialogs, they show up without the "Cancel" or "Open" buttons. However, if I move them, even if just a pixel, they start showing the buttons (and they show them correctly any time after that).

This is a GIF recording of it happening on my project: http://recordit.co/29jPWiz10S

Also, while creating the example I noticed that the buttons show up way below the Dialog when it is shown. The reason it doesn't happen in the example (anymore) or in my project is because the size of the dialog makes the buttons get off screen (when I discovered it the Dialog was still small).

**Steps to reproduce:**
Add a FileDialog that covers most of the screen
Add a button
Wire the button to show the dialog

**Link to minimal example project** (optional but very welcome):

The link for the minimal example project:
https://www.dropbox.com/s/8c4v080k0wgsqx8/FileDialog%20Issue.zip?dl=1

**Comment by bebae** [comment]
Should be fixed by #6423

**Comment by akien-mga** [comment]
Closing then, feel free to comment and ask to reopen if the bug is actually not fixed.
