### ISSUE TITLE
Code ligatures shouldn't apply on literal strings

### ISSUE THREAD

**Issue by xix-xeaon** [godotengine/godot#63865]
### Godot version

v4.0.alpha13.official [59dcddc45]

### System information

Linux

### Issue description

Code ligatures shouldn't apply to literal strings. The text should show exactly the text that it actually is. When printed etc the ligature will not be shown. And, we don't know how the string is going to be used anyway.

Currently:
![image](https://user-images.githubusercontent.com/1330325/182561352-42979b57-374c-4fcd-a1ef-e302a0415fa1.png)

Should be:
![image](https://user-images.githubusercontent.com/1330325/182561192-866a2f5b-8dd3-4cf6-806f-3f4979b9b324.png)

Also, ligatures shouldn't be on by default. If you type some characters, those are the characters that should be displayed. If the user wants something different they can make that choice manually. Ligatures are confusing for beginners too.

### Steps to reproduce

Type `"<="` in the text editor.

**Comment by Calinou** [comment]
In most other editors, ligatures do work within strings. Example in VS Code: 
![image](https://user-images.githubusercontent.com/180032/182564373-ba0f1708-c66f-4312-86e7-6b0982788a47.png)

**Comment by xix-xeaon** [comment]
I saw a Reddit post about this and while the original poster liked ligatures, most upvoted comments believe it should be disabled by default, since they're confusing for beginner. Non-beginners also have very mixed feelings about them. 
https://www.reddit.com/r/godot/comments/ysl3eg/i_so_much_like_the_new_editor_of_godot_4_the_font/

Also, I just realized I've been teaching some other programming courses this semester and we've been using VS Code and it certainly does not show ligatures for any of my students nor on my work computer. I installed VS Code on my own Linux computer a few weeks ago and I just made a fresh install on a Windows VM and neither shows ligatures.

**Comment by bruvzg** [comment]
> Code ligatures shouldn't apply to literal strings. The text should show exactly the text that it actually is. When printed etc the ligature will not be shown. And, we don't know how the string is going to be used anyway.

With the current implementation of the code highlighter and TextEdit/CodeEdit, there is no way to do it (ligatures can be enabled/disabled for the whole text only).

Highlighting will need to be applied when processing/shaping text, not when drawing it. And since any change in the code can change highlighting of the all subsequent lines, so it's probably will need asynchronous update mode (or editing begging in of the large files might cause stutters).
