### ISSUE TITLE
Editor Hangs importing Collada File

### ISSUE THREAD

**Issue by amedlock** [godotengine/godot#6387]
First, thanks for making this software, enjoying it so far.

**Operating system or device - Godot version:**
Windows 7 64 bit Professional
Godot version: 2.1 stable

**Issue description** (what happened, and what was expected):
Importing the attached dae file causes the editor to stop responding. I let it run for 5 minutes before killing it.

**Steps to reproduce:**
Import -> Mesh.  Select attached DAE file.  Left generate tangents and weld vertices checked.

**Link to minimal example project** (optional but very welcome):
[Lowres_man.zip](https://github.com/godotengine/godot/files/453588/Lowres_man.zip)

PS. I saw the other bug about godot.exe being on a different drive than the file.  This is not the case here.

**Comment by amedlock** [comment]
I tried looking for small angles like #6384 but still locks the editor.  My cpu only goes to 25% also.

**Comment by vnen** [comment]
I can reproduce but there's a caveat: Mesh import only let's me select `.obj` files. To select a `.dae` I have to set the filter as "All Files". So the editor is not expecting a Collada file there.

**Comment by amedlock** [comment]
I see.  I didn't realize you had to import scene for dae.  Thought it would just pull the mesh.  
Should I close this then?
