### ISSUE TITLE
Changes to default project theme don't update right away

### ISSUE THREAD

**Issue by AaronRecord** [godotengine/godot#63889]
### Godot version

ea4b8de

### System information

Windows 11

### Issue description
Setting the default project theme for the first time:

https://user-images.githubusercontent.com/50304111/182706699-26757f10-6a46-4ddb-87a2-0eacd95baf66.mp4

After restarting editor:

https://user-images.githubusercontent.com/50304111/182706752-b253e564-bff1-4045-ba5e-4091bb4a4458.mp4

In theory I don't see why this should require an editor restart in the first place. Also as a side note I think the project default font could be removed as well as you should already be able to do this by assigning a default project theme with a default font.

See also https://github.com/godotengine/godot/issues/62844

### Steps to reproduce

See above

### Minimal reproduction project

[MRP.zip](https://github.com/godotengine/godot/files/9254903/MRP.zip)

**Comment by AaronRecord** [comment]
Some other possibly relevant issues I found:
https://github.com/godotengine/godot/issues/39785
https://github.com/godotengine/godot/issues/48477
https://github.com/godotengine/godot/issues/56520
https://github.com/godotengine/godot/issues/60930

**Comment by KoBeWi** [comment]
Interesting...

https://user-images.githubusercontent.com/2223172/221440127-e16a6343-b499-44c3-83f1-9bebd2587b11.mp4

**Comment by YuriSizov** [comment]
Yeah, of course. There is simply no mechanism for propagating global theme changes to controls. Bu there will be.
