### ISSUE TITLE
glb import is not the same between versions

### ISSUE THREAD

**Issue by EmmaCreations** [godotengine/godot#63883]
### Godot version

4.0 dev

### System information

Windows 11, AMD Ryzen 3900X, RTX 2070 S

### Issue description

I created a 3D model and imported it in Godot 4 as a glb. The animation broke and parts of the mesh did not follow the skeleton properly. I loaded the same model into Godot 3 and there were no issues with the animation.

https://user-images.githubusercontent.com/83244706/182676673-7b6622a9-55ea-4853-9a9b-1389dd2e1701.mp4

https://user-images.githubusercontent.com/83244706/182676685-fedf750a-9f16-4d01-82ab-119877a1f137.mp4

### Steps to reproduce

Create a rig in Blender,
1 - Export as glb, import to Godot
1.1 - Drop the blender file in Godot
2 Animation doesn't play properly

### Minimal reproduction project

[Project.zip](https://github.com/godotengine/godot/files/9253940/Project.zip)

**Comment by Zireael07** [comment]
4.0 dev spans half a year now. Which commit?

Most likely this is animation auto-optimization acting up again. Find it in Godot and disable it.

**Comment by EmmaCreations** [comment]
I'm sorry I have not been up to speed. Where is that located?

**Comment by Calinou** [comment]
> I'm sorry I have not been up to speed. Where is that located?

The optimizer can be disabled in the Import dock after selecting the gltf/glb file in the FileSystem dock.

**Comment by fire** [comment]
Somehow the older import of the animation was kept. If you delete the .godot folder and let it reimport, I was able to get the animation to look the same as https://threejs.org/editor/.

**Comment by fire** [comment]
![image](https://user-images.githubusercontent.com/32321/182772592-f8a367d7-3495-411a-b103-321e5f48913f.png)


The keyframe should be solid.

**Comment by EmmaCreations** [comment]
This did not work for me, the animation is still broken

**Comment by TokageItLab** [comment]
It is unclear what you mean by some of the meshes not tracking. From the video above, I can only say that it is an Optimizer issue that is causing the animation to be wonky.
Please confirm that you have disabled Optimizer and then tell me the commit hash for 4.0.dev.

**Comment by EmmaCreations** [comment]
I meant that the meshes for the shoes were not tracking to the armature properly, you can see in the video that they do not follow the skeleton the way they should. Turning off the optimizer fixed it, and this isn't any build you can currently download. This is from me building the engine from the latest source code at the time(the videos show 4.0.alpha.mono)
