### ISSUE TITLE
Misspelled resource works

### ISSUE THREAD

**Issue by EdwardAngeles** [godotengine/godot#6389]
**Operating system or device - Godot version:**
Ubuntu / Linux - Godot 2.1 Estable

**Issue description** (what happened, and what was expected):
This works on desktop without issues: `extends "res://scripts//powerup.gd"` (notice the two slashes)
And it shouldn't work.

On the other hand, on android it makes the screen flick and the game crashes.

**Comment by akien-mga** [comment]
I think it should work on both desktop and android. On Unix a double slash does not invalidate the path AFAIK.
