### ISSUE TITLE
Tagging code

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#6390]
We were discussing different ways to make code tagging in Godot in #6371 and, since this idea is a little bit different, I'll make a separate discussion for it. 

**Why we need code tagging:** 
As projects grow, you get more and more code you need to manage. It's very likely that you forget about some incomplete, outdated or buggy block of code in some file. Code tagging can help with that, by showing code that needs attention.

**How this should work:** 
- By default there should be a list of commonly used tags like [Incomplete], [Needs fixing], [To do] etc.
- Users should be able to create their own tags
- Tag properties: name, background color
- In context menu of highlighted code, there should be [Apply Tag] dropdown menu. After user selects tag from it, background color behind selected lines of code should change to tag color
  ![screenshot at 2016-09-04 14 33 47](https://cloud.githubusercontent.com/assets/10696955/18230905/451507dc-72b2-11e6-84c7-ffabcd0f0251.png)
- [Metrics] button on the panel with [Tutorials] and [Classes] could show the window with list of files with tagged code as well as percentage of tagged code in file/project

**Comment by hubbyist** [comment]
This approach will need meta data keeping for tags which is hidden but implanted into code. This is not practical IMO. Tags must be written in comments and must be editable with any text editor as well. Thus just a list of user defined words to be highlighted as suggested in https://github.com/godotengine/godot/issues/6371#issuecomment-244493004, is more practical I think.

**Comment by Noshyaar** [comment]
Still reproducible/relevant in 3.1 master 9ad1800 : there aren't yet support for such functionality.

**Comment by vnen** [comment]
I think this could be provided as a plugin in the AssetLib. I don't see the demand to have this integrated in the editor (and it's not a regular feature of IDEs AFAIK).

**Comment by Noshyaar** [comment]
Agreed. This should be done as a plugin. Closing as out of scope.
