### ISSUE TITLE
ColorPicker SpinBox makes the cursor disappear on drag

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#63903]
### Godot version

255e077

### System information

Windows 10 x64

### Issue description

![zqN1U9VC1I](https://user-images.githubusercontent.com/2223172/182833830-21b172d1-33c0-49ea-872c-e33f2cef7d1d.gif)
Dragging the value is not possible. You need to press Escape or click somewhere away to make the cursor appear. Does not seem to happen with SpinBoxes in other places. Only happens in the editor, runtime ColorPickers are fine (related to popups?).

### Steps to reproduce

1. Open any ColorPicker in the inspector (e.g. for `modulate` property)
2. Try dragging SpinBox arrows

**Comment by CrackedP0t** [comment]
I was able to replicate this on Windows 10 and version c80540f9a20b45d107b9bed1e749571a83492337

**Comment by TheDuriel** [comment]
Potentially related #60526 #62620 #58793

I remember this happening with the GraphEdit spinbox it has for changing zoom (can't find the issue), it was then fixed for spinbox at some point.
