### ISSUE TITLE
Custom alt-prefixed editor shortcuts not working when inside script editor

### ISSUE THREAD

**Issue by and3rson** [godotengine/godot#63904]
### Godot version

3.5-rc8

### System information

ArchLinux
WM: River (Wayland). Not sure if this is relevant though.

### Issue description

Custom alt-prefixed shortcuts do not work in Script editor. Ctrl-prefixed shortcuts work fine.

### Steps to reproduce

1. Set `editor/quick_open` shortcut to `Alt-P`
2. Open 2D/3D/AssetLib tab
3. Hit `Alt-P` - pop-up appears
4. Open Script tab
5. Hit `Alt-P` - letter `p` is typed in source code.

### Minimal reproduction project

Any project

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/63888 (same cause).
