### ISSUE TITLE
S3TC support for Godot 4.0 for Android export

### ISSUE THREAD

**Issue by korompg** [godotengine/godot#63909]
### Godot version

4.0 alpha 13

### System information

Ubuntu 20.04, Vulkan, NVIDIA  GeForce GTX 1070 Ti

### Issue description

First mentioned in #63832.

I'm trying to export my VR project for Android to be used on a Meta Quest 2. But when running on the device, it fails to load my texture resources (png, jpg, bmp formats).

The files exported into the apk:

![Screenshot from 2022-08-04 15-57-27](https://user-images.githubusercontent.com/102245985/182870125-27769da1-f4ca-492e-8e6d-dddfced62428.png)

The errors I get in Logcat:

USER ERROR: Unable to open file: res://.godot/imported/icon.bmp-9d1de709bb464c1beb38c8bc584bca25.s3tc.ctex.
at: _load_data (scene/resources/texture.cpp:823) - Condition "f.is_null()" is true. Returning: ERR_CANT_OPEN
USER ERROR: Failed loading resource: res://.godot/imported/icon.bmp-9d1de709bb464c1beb38c8bc584bca25.s3tc.ctex. Make sure resources have been imported by opening the project in the editor at least once.
at: _load (core/io/resource_loader.cpp:222) - Condition "found" is true. Returning: Ref()
USER ERROR: Failed loading resource: res://icon.bmp. Make sure resources have been imported by opening the project in the editor at least once.
at: _load (core/io/resource_loader.cpp:222) - Condition "found" is true. Returning: Ref()

The required .s3tc.ctex files exist in my local .godot/imported folder but they won't get exported into the apk.

### Steps to reproduce

1. Use the latest master build.
2. Make a basic OpenXR project that uses either png, jpg or bmp files as texture resources.
3. Export the project for Android, install it to a Meta Quest 2 then launch it.

### Minimal reproduction project

This project works in the editor but not on the Quest 2:
[godot_4_alpha13_resource_loading_test.zip](https://github.com/godotengine/godot/files/9260529/godot_4_alpha13_resource_loading_test.zip)

**Comment by akien-mga** [comment]
Could you test #63918?

**Comment by korompg** [comment]
I've rebuilt the engine using the latest master branch but It's still looking for the S3TC files:

USER ERROR: Unable to open file: res://.godot/imported/icon.png-487276ed1e3a0c39cad0279d744ee560.s3tc.ctex.
at: _load_data (scene/resources/texture.cpp:823) - Condition "f.is_null()" is true. Returning: ERR_CANT_OPEN
USER ERROR: Failed loading resource: res://.godot/imported/icon.png-487276ed1e3a0c39cad0279d744ee560.s3tc.ctex. Make sure resources have been imported by opening the project in the editor at least once.
at: _load (core/io/resource_loader.cpp:222) - Condition "found" is true. Returning: Ref<Resource>()
USER ERROR: Failed loading resource: res://icon.png. Make sure resources have been imported by opening the project in the editor at least once.
at: _load (core/io/resource_loader.cpp:222) - Condition "found" is true. Returning: Ref<Resource>()
USER ERROR: res://Main.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://icon.png
at: load (scene/resources/resource_format_text.cpp:486) - res://Main.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://icon.png
USER ERROR: Failed loading resource: res://Main.tscn. Make sure resources have been imported by opening the project in the editor at least once.
at: _load (core/io/resource_loader.cpp:222) - Condition "found" is true. Returning: Ref<Resource>()
USER ERROR: Failed loading scene: res://Main.tscn
at: start (main/main.cpp:2689) - Condition "!scene" is true. Returning: false

Should I change something in the project?

**Comment by akien-mga** [comment]
Did you also build the Android export template with this commit?

**Comment by korompg** [comment]
Reinstalled the alpha 13 export template and the build template. Same errors. Anything else I should do?

**Comment by korompg** [comment]
Okay, tried with rebuilt export templates too. Same issue persists.

**Comment by korompg** [comment]
I wasn't supposed to check the 'Custom Build' option, right?

**Comment by korompg** [comment]
Okay, using the rebuilt export templates and with the 'Use Custom Build' option unchecked I'm not getting these errors anymore. Thanks for everything!
