### ISSUE TITLE
Error when using macros in shaders.

### ISSUE THREAD

**Issue by jk7c** [godotengine/godot#63927]
### Godot version

4.0 alpha 13

### System information

GNU/Linux Pop Os 20.04 GPU: Nvidia GeForce GTX 1070ti.

### Issue description

The shader editor throws an error if I use a macros multiple times in one line of code.

No work
![BUG](https://user-images.githubusercontent.com/75779389/182950897-359b0e3c-edff-471a-b927-664678539e6a.png)

Work
![BUG2](https://user-images.githubusercontent.com/75779389/182950927-7db87feb-03dc-485d-8757-0954ba6f79de.png)

### Steps to reproduce

Define a macros and try to use it multiple times in one line of code.

**Comment by Calinou** [comment]
cc @Chaosus

**Comment by bitsawer** [comment]
Can confirm, one of the culprits might be this in expand_macros():

```
		// Remove expanded macro and recursively replace remaining.
		p_defines.remove_at(i);
```

The loop should try to expand macros until it no longer finds anything to expand and it naturally should not remove any defines during that loop. Looks like this regression happened when the regex was replaced with normal string logic. The whole expansion code feels unnecessarily complex too, I should have some free time to check this out, unless Chaosus wants to try.

**Comment by onion108** [comment]
I have the same problem. What should I do other than waiting someone to fix the bug?
