### ISSUE TITLE
Vulkan support on older Macbook

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#63920]
### Godot version

v4.0.alpha13.official [59dcddc45]

### System information

Mac OS X (Catalina) 10.15.7

### Issue description

My Macbook Pro 2012 has  Intel HD 4000 and Nvidia GeForce GT 650M GPUs.

Nvidia GeForce GT 650M on the Macbook Pro 2012 is no longer supported neither by Nvidia or by Apple with newer drivers to support metal/vulkan. They had some licensing fight so the Nvidia GPU is disabled. 

In addition Intel will not support Vulkan on the Intel HD 4000 GPU. 

Any ideas other than a new Mac to test Godot 4.

### Steps to reproduce

Compiled from source according to the instructions 

[https://docs.godotengine.org/en/latest/development/compiling/compiling_for_macos.html](https://docs.godotengine.org/en/latest/development/compiling/compiling_for_macos.html
)

**Comment by fire** [comment]
Can you try opengl mode?

**Comment by Calinou** [comment]
> Any ideas other than a new Mac to test Godot 4.

Yes, use the `--rendering-driver opengl3` command line argument. Note that in 4.0.alpha13, that renderer is broken, so you need to compile from source.
