### ISSUE TITLE
AnimationPlayer wrong key property for Control nodes

### ISSUE THREAD

**Issue by Dodoveloper** [godotengine/godot#63948]
### Godot version

Godot_v4.0-alpha13_linux.64

### System information

Manjaro Linux, kernel 5.18.14-1-MANJARO 

### Issue description

This looks like a simple one.

Basically when trying to move a `Control` node via the `AnimationPlayer`, if you insert a key using the translation mask on top of the editor, the engine will create a `rect_position` property in the AnimationPlayer. 
![image](https://user-images.githubusercontent.com/17781050/183051465-bb16a29c-84a4-4426-84e1-606444cac082.png)

This triggers some errors, thus the animation is not working.
```
scene/animation/animation_player.cpp:1132 - Failed setting key 'rect_position' at time 0 in Animation '' at Node '/root/@@15622/@@38769', Track 'TextureRect:position'. Check if the property exists or the type of key is right for the property.
```

Instead, using the Inspector dock correctly creates a `position` track for the node.

### Steps to reproduce

1. Create a scene with a `Control` node
2. Add an `AnimationPlayer` and create an animation
3. Insert a key using the translation mask on top of the editor
4. Now a `rect_position` track is created, but it should be `position`

### Minimal reproduction project

[AnimPlayerBug.zip](https://github.com/godotengine/godot/files/9267584/AnimPlayerBug.zip)

**Comment by Calinou** [comment]
`rect_position` was renamed to `position`, so this should be easy to fix.
