### ISSUE TITLE
GDScript parser bug: Trying to advance past the end of stream

### ISSUE THREAD

**Issue by James103** [godotengine/godot#63946]
### Godot version

Since Godot Engine v4.0.alpha12.official
(Originally reported in Godot Engine v4.0.alpha13.official)

### System information

Windows 10, 64-bit

### Issue description

During parsing/autocomplete of the function name when typing `func ...`, the GDScript parser logs the following line:

```
GDScript parser bug: Trying to advance past the end of stream.
```

This line is logged once every time 300ms passes between consecutive characters typed while writing the function name in `func ...` at the end of the script. It is also logged when saving the script

This line is logged here: https://github.com/godotengine/godot/blob/44d3c8402ebc0d1e77936dbf909a1ddcb48ab193/modules/gdscript/gdscript_parser.cpp#L407

### Steps to reproduce

Create a new script and write the following code, making sure to type the last line slowly (pace one letter every &#x2248;500ms):
```gdscript
extends Node

func abcdefg
```
Then, save the script and notice additional lines of `GDScript parser bug: Trying to advance past the end of stream.` in the log.

Alternatively, open the attached project below, during which the parser reports additional errors like above.

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/9267213/test.zip)

**Comment by Calinou** [comment]
Can you reproduce this in earlier 4.0 alphas?

**Comment by James103** [comment]
Bisecting through the alpha releases:
* Godot 4.0 alpha 10 does not have this issue.
* Godot 4.0 alpha 11 does not have this issue.
* Godot 4.0 alpha 12 does have this issue.

Therefore, one of the (most likely GDScript related) changes between alpha 11 and alpha 12 is causing this issue.

**Comment by CassianoBelniak** [comment]
Still happening on Godot 4.0 alpha 2.
Same reproduction steps.

**Comment by clapik** [comment]
still seeing this error Godot 4.0 beta 8

**Comment by MeBadDev** [comment]
this is in Godot 4.0 alpha 10

**Comment by MeBadDev** [comment]
![image](https://user-images.githubusercontent.com/94725241/210780095-d398b3ce-fea6-4b6d-84f2-4b06053174fb.png)
and i get those weird icons while reproducing

**Comment by laingawbl** [comment]
Still there in 4.0 beta 12.

**Comment by titusio** [comment]
In 4.0 beta 14 as well.

**Comment by AnidemDex** [comment]
Still valid in v4.0.rc5.official [6296b4600]

**Comment by pacomesoual** [comment]
Sill happening in 4.0 stable :
![image](https://user-images.githubusercontent.com/89353285/223382583-f50b16a9-2bfe-4999-b8e8-08620d5f8174.png)

**Comment by chandujr** [comment]
The error went away after I switched to another script and made some changes and came back to the original script. I'm also in the 4.0 stable build.
