### ISSUE TITLE
Next script shortcut fires twice in Script Editor

### ISSUE THREAD

**Issue by sbalia** [godotengine/godot#63947]
### Godot version

3.4.5.stable.mono

### System information

macOS Monterey v12.5

### Issue description

When you press `Cmd + Shift + .` (Next script), code below executes twice:

https://github.com/sbalia/godot/blob/f9ac000d5dc0d1014fa347fb2f23069b294d511a/editor/plugins/script_editor_plugin.cpp#L2572-L2575

Attaching a gif
![demoScriptEditor](https://user-images.githubusercontent.com/18215177/183041993-3278f350-d6d3-44e6-85f6-e1bd39ada934.gif)

On the gif, I traversed through files twice with the shortcut Previous script and then started doing it in this combination: Next Script, Previous Script.
It's clear that when using the Next script, it doesn't jump to the next script, but instead to the following script after "next" .

### Steps to reproduce

1. Create more than two scripts (can be empty);
2. Press the Next script shortcut

### Minimal reproduction project

Any project

**Comment by EricEzaM** [comment]
Cannot reproduce on Windows 10 in 4.0 or 3.5.1 stable.

**Comment by akien-mga** [comment]
Doesn't seem reproducible on 3.4.5 stable on Linux either. Might be macOS specific? Otherwise I have no idea. CC @bruvzg

**Comment by bruvzg** [comment]
I can reproduce it with both 4.0 and 3.x, seems like it's specific to `Cmd + Shift + . ` (it's also double trigger other events).
