### ISSUE TITLE
gdshader's uniform int inconsistent with const int when converted to float

### ISSUE THREAD

**Issue by Streq** [godotengine/godot#63955]
### Godot version

v3.4.5.stable.official [f9ac000d5]

### System information

Ubuntu 20.04.3 LTS
AMD Radeon RX 6700 XT
Kernel driver in use: amdgpu

### Issue description

Simply put, the following shader will always call discard

```glsl
shader_type canvas_item;
uniform int palette_size = 3;
const int palette_size2 = 3;


void fragment(){
    if (
        palette_size == palette_size2 &&
        float(palette_size) == float(palette_size2) &&
        1.0/float(palette_size) != 1.0/float(palette_size2)
    ){
        discard;
    }
    COLOR = texture(TEXTURE, UV);
}
```
Precision modifiers don't seem to alter the outcome.
```glsl
shader_type canvas_item;
uniform highp int palette_size = 3;
const highp int palette_size2 = 3;


void fragment(){
    highp float float_palette_size = float(palette_size);
    highp float float_palette_size2 = float(palette_size2);

    if (
        palette_size == palette_size2 &&
        float_palette_size == float_palette_size2 &&
        1.0/float_palette_size != 1.0/float_palette_size2
    ){
        discard;
    }
    COLOR = texture(TEXTURE, UV);
}
```

### Steps to reproduce

Use the provided shader as a material for any sprite

### Minimal reproduction project

[shader_bug.zip](https://github.com/godotengine/godot/files/9267979/shader_bug.zip)

**Comment by Calinou** [comment]
I can't reproduce this on 3.5 (Linux, NVIDIA 515.57).

![image](https://user-images.githubusercontent.com/180032/183237900-c45a53bb-fbd4-4176-9cd2-2e5c0e1525eb.png)

Which graphics card model and driver are you using? This may be a bug in the driver.

**Comment by Streq** [comment]
@Calinou I've considered the possibility (after opening this issue) that it was a hardware issue, I've updated the issue with the GPU info

**Comment by Calinou** [comment]
Godot 4.0 has a shader warning system which warns you when performing floating-point comparison with `==`. It tells you to compare with an epsilon value instead, e.g. `if (value > 0.001)` or `if (value > 0.999 || value < 1.001)`.
