### ISSUE TITLE
Confusing rename node  errors in the AnimationTree

### ISSUE THREAD

**Issue by CodeLazier** [godotengine/godot#63952]
### Godot version

godot4.0 a13

### System information

win10 vulkan

### Issue description

![at](https://user-images.githubusercontent.com/14953625/183054127-8a720ca3-fa72-47fa-b3b6-241ac7d7578f.gif)

### Steps to reproduce

add AnimationTree node,add node rename node name.

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/58822.
