### ISSUE TITLE
Cannot import editor themes / error while saving editor theme

### ISSUE THREAD

**Issue by matthjes** [godotengine/godot#6395]
**Operating system or device - Godot version:**
Windows 10, Godot 2.1-stable_win64

**Issue description** (what happened, and what was expected):
I wanted to import some editor themes from [here](https://github.com/Geequlim/godot-code/tree/master/styles/syntax), however, after selecting a theme file nothing happens. I also receive an "Error while saving theme" when I try to save a theme.

**Steps to reproduce:**
1) Open a script file.
2) Import a theme or save a theme

**Comment by Paulb23** [comment]
I can't seem to reproduce on Linux or Windows. Only thing I can think of are you trying to save the theme as `default`?

**Comment by matthjes** [comment]
I can save the default theme under a new name. However, if I change some colors and import the theme again nothing happens.
I get the "Error while saving theme" error when I click on "Save Theme".

Is there some log output I can look at to see if some error is thrown?

Here is my exported theme file. I've change the background color to "ff000000" (default text selected color), but nothing changes when I load the theme.

```
[color_theme]

background_color="ff000000"
base_type_color="ffa3ffd4"
brace_mismatch_color="ffff3333"
breakpoint_color="33cccc66"
caret_background_color="ff000000"
caret_color="ffaaaaaa"
comment_color="ff676767"
completion_background_color="ff2b2a31"
completion_existing_color="21dfdfdf"
completion_font_color="ffaaaaaa"
completion_scroll_color="ffffffff"
completion_selected_color="ff424244"
current_line_color="264c7fcc"
engine_type_color="ff83d3ff"
function_color="ff66a1cd"
keyword_color="ffffffb3"
line_number_color="66aaaaaa"
mark_color="66ff6666"
member_variable_color="ffe64d59"
number_color="ffeb9531"
search_result_border_color="ff197219"
search_result_color="ff0c3f0c"
selection_color="ff7b5dbd"
string_color="ffef6ebd"
symbol_color="ffbadfff"
text_color="ffaaaaaa"
text_selected_color="ff000000"
word_highlighted_color="26cce5e5"
```

**Comment by Paulb23** [comment]
I've just download your theme and it seems to work fine, the bit that seems off is the "Error while saving theme" message when clicking on "Save Theme". 

Could you check that you've selected your theme in the drop down under`Settings -> Editor Settings -> Text Editor -> Color Theme`

Also when re-importing / editing externally the currently loaded theme, Godot will not reload the file. To do this you have to click `File -> Reload Theme` in the Script Editor.

**Comment by matthjes** [comment]
Ok, I'm stupid. Here is what I did (and thought it would change the theme):
Open a script file -> File -> Import Theme -> Reload Theme

I did not know I have to import the themes this way and then open Settings -> Editor Settings -> Text Editor -> Color Theme to actually change the theme...

It's working now, thanks for your help. One last thing: how can I remove themes from the theme list?

**Comment by Paulb23** [comment]
It will switch theme on a `save-as` proving it's saved in the correct directory but, maybe this should be extended to importing themes as well?

To remove a theme delete the theme file in `~/.godot/text_editor_themes/` for linux or`%APPDATA%/Godot/text_editor_themes/` for windows.

**Comment by matthjes** [comment]
I would remove the Import and Save Theme menu items from File and put everything in Settings -> Editor Settings. This way everything is at one place.

Thanks again, I deleted the themes I won't need.
