### ISSUE TITLE
Changing the editor settings path has no effect

### ISSUE THREAD

**Issue by RayKoopa** [godotengine/godot#6396]
**Operating system or device - Godot version:**
Windows 10 x64, v2.1.stable.official (also noticed this in 2.0)

**Issue description**
I could change the path for the editor settings, but when restarting the editor, the old default path is set again.

**Steps to reproduce:**

1. Open the **Editor Settings**.
2. Under **Resource**, change the value of the **Path** property (being the expanded `%APPDATA%/Godot/editor_settings.tres` path yet).
3. Enter a new path (I ensured the directory exists, and at a 2nd try also copied the `editor_settings.tres` file there).
4. Close the **Editor Settings** window.
5. Restart the editor.
6. Check the settings. The **Path** value is back at `%APPDATA%/Godot/editor_settings.tres`.

**Comment by reduz** [comment]
haha that value is not meant to be edited, I'm surprised it allowed you to, will check that it's not exposed

**Comment by RayKoopa** [comment]
Any other way to reposition the file then? AppData sucks portability wise... ;3

**Comment by vnen** [comment]
@RayKoopa you can use the [self contained mode](http://docs.godotengine.org/en/latest/reference/packaging_godot.html#self-contained-mode).

**Comment by RayKoopa** [comment]
Looks just like what I needed, thanks.

**Comment by akien-mga** [comment]
Other than the self contained mode, you can't really reposition the settings file as Godot would have no setting file to tell itself where the setting file is... :D

**Comment by RayKoopa** [comment]
Yeah, I wondered if a start-up parameter exists.

**Comment by akien-mga** [comment]
Not that I know of, but it could likely be added.
