### ISSUE TITLE
Godot 3.5 quits unexpectedly

### ISSUE THREAD

**Issue by dariemlazaro** [godotengine/godot#63967]
### Godot version

3.5.stable

### System information

Windows 11, GLES ES 2.0, Intel(R) HD Graphics (8.15.10.2900)

### Issue description

Godot editor crashes when opening some scenes or other projects from previous versions.

### Steps to reproduce

Open a prevoius project and try all scenes. some open and some cause crash.

### Minimal reproduction project

[benteng takeshi.zip](https://github.com/godotengine/godot/files/9270583/benteng.takeshi.zip)

**Comment by akien-mga** [comment]
I tried the attach project but all scenes open without problem for me with 3.5.stable on Linux.

**Comment by dariemlazaro** [comment]
In a new project when trying to import a glb or gltf it crashes, the same with those converted to scenes in version 3.4.2.

**Comment by dariemlazaro** [comment]
I tested the project on another PC with windows 11 but Intel HD 3000 graphics and it works perfectly and does not close, however it does not detect that it has GLES 3.1. Apparently my graphics is incompatible with Godot, the errors that appear in the console refer to MSAA is not supported.

**Comment by Calinou** [comment]
> I tested the project on another PC with windows 11 but Intel HD 3000 graphics and it works perfectly and does not close, however it does not detect that it has GLES 3.1.

Intel Sandy Bridge IGPs don't support the GLES3 renderer, as they lack support for OpenGL 3.3.

**Comment by mirh** [comment]
GLES3 and GL 3.3 are two different things (I could swear that there are also some features of the former that aren't even present in the later). And sandy bridge actually supports both in linux. 
On windows they don't, and on top of that using W10 breaks it [even further](https://github.com/pal1000/save-legacy-intel-graphics). 
p.s. 8.15.10.2900 isn't even the last driver available
p.p.s. even if I were 100% correct though, I guess there would still be a bug to fix here.. no crash is ever justifiable.

**Comment by Calinou** [comment]
@dariemlazaro Can you still reproduce this on Godot 3.5.3 or 4.1.3?

**Comment by dariemlazaro** [comment]
@Calinou I have changed my laptop and got an 8th generation Intel core i3 processor. Since then I haven't had that problem. And I could no longer replicate it. So I think this ticket can be closed.
