### ISSUE TITLE
Input.parse_input_event does not cause actions/buttons to be pressed.

### ISSUE THREAD

**Issue by bitwes** [godotengine/godot#63969]
### Godot version

3.5 stable

### System information

2016 Macbook Pro macOS Catalina 10.15.7

### Issue description

In 3.4, calling `Input.parse_input_event` for a key-press or action-press event would cause `Input` to report that the key/action was pressed when using `is_action_pressed`, `is_action_just_pressed`, `is_key_pressed`.  In 3.5 these all return `false`.  I did not test `is_action_just_released` since I couldn't programmatically cause the action to be pressed.

### Steps to reproduce

Run the Minimal reproduction script.

3.4 Output
```
jump pressed = True
jump just pressed = True
Y pressed = True
```

3.5 Output
```
jump pressed = False
jump just pressed = False
Y pressed = False
```

### Minimal reproduction project

``` gdscript
extends SceneTree

func _init():
    # -- Action checks --
    InputMap.add_action("jump")
    var action_event = InputEventAction.new()
    action_event.action = 'jump'
    action_event.pressed = true

    Input.parse_input_event(action_event)
    print("jump pressed = ", Input.is_action_pressed('jump'))
    print("jump just pressed = ", Input.is_action_just_pressed('jump'))
    
    # -- Key checks --
    var key_event = InputEventKey.new()
    key_event.pressed = true
    key_event.scancode = KEY_Y

    Input.parse_input_event(key_event)
    print('Y pressed = ', Input.is_key_pressed(KEY_Y))


    quit()
```

**Comment by akien-mga** [comment]
Does it work if you call `Input.use_accumulated_input = false`?

CC @RandomShaper

**Comment by bitwes** [comment]
That fixes it.

**Comment by bitwes** [comment]
With `use_accumulated_input` enabled, I found that if you `yield` before checking then it works as expected.

```
    Input.parse_input_event(key_event)
    yield(get_root().get_tree().create_timer(.1), 'timeout')
    print('Y pressed = ', Input.is_key_pressed(KEY_Y))
```
prints `Y pressed = True`.  

This also worked for `is_action_pressed`.  `is_action_just_pressed` still reported `false` but that is to be expected since we wouldn't be checking on the same frame with the `yield`.  

There's probably not a bug here, just another case of not reading the release notes.  II need rework GUT's input mocking and I'll create a new issue if I find something actually wrong.  

Thanks.

**Comment by bitwes** [comment]
Yet again, I reacted too fast.  Reading the 3.4 documentation it appears that use_accumulated_input was enabled by default in 3.4.  So this behavior might be unintended.

**Comment by akien-mga** [comment]
Its not enabled by default in 3.4, the documentation was wrong.

**Comment by bitwes** [comment]
Ahhh, ok.  That is probably the cause then.  I will be re-examining my Input Mocking approach to understand the implications of the flag.  I'll post back any findings.

**Comment by RandomShaper** [comment]
Instead of yielding on a timer, you can call `Input.flush_buffered_events()`.

**Comment by bitwes** [comment]
`Input.flush_buffered_events()` will work well as a fix for this.  I can add a flag to call this everytime my input mocker sends an event through `Input`.  This will make it behave the way it used to when `use_accumulated_input` was disabled, and it is backwards compatible.

Between adding this flag and adding some documentation about `use_accumulated_input` everything works.

Thanks for your help.
