### ISSUE TITLE
StringName comparsion missing `Array.has(String)` and `String in Array`

### ISSUE THREAD

**Issue by Amatrelan** [godotengine/godot#63965]
### Godot version

v4.0.alpha.custom_build [8f05263bd]

### System information

Linux

### Issue description

When using groups, now defined as StringName. So many functionalities have stopped working when comparing `"value"` (String). This comes apparent when there are places where `String` has been replaced by `StringName`, and there is no error that those aren't comparable. Also in the documentation, there is pointed out that those two (String, StringName) has compare operation.

Because there is no error in a wrong way to compare it causes problems, example wrong way to compare is:
`"some" in get_groups()`. This should raise an error if it's not comparable.

For clarification, I don't need those to work! But I would love to get error when those don't work as expected.
Ex error:
`Array[StringName].has(Variant) Variant has to be same type as Array data, was String expected StringName `

### Steps to reproduce

- Create empty project.
- Add `Node` as root.
- Add node to group `some`.
- Add script with content on below

```gdscript
extends Node

func _ready():
	for each in get_method_list():
		if "test_" in each.name:
			print("%s returns %s" % [each.name, call(each.name)])

func test_one() -> bool:
	return "some" in get_groups()
		
		
func test_two() -> bool:
	for each in get_groups():
		if each == "some":
			return true
	return false
	
func test_three() -> bool:
	return get_groups().has("some")
	
func test_four() -> bool:
	for each in get_groups():
		match each:
			"some":
				return true
			_:
				return false
	return false
```

Output:
```
test_one returns false
test_two returns true
test_three returns false
test_four returns false
```

**Comment by tinmanjuggernaut** [comment]
Test two and four are documented in #60145. This demonstrates issues with StringName conversion with `in`, `has`, and `Node.get_groups()`.
