### ISSUE TITLE
Godot Scenes/Project Crash Upon Play

### ISSUE THREAD

**Issue by ryancito02** [godotengine/godot#6397]
**Operating system or device - Godot version:**
Arch (Rolling Release) Linux. Godot 2.1 32 bit.

**Issue description** (what happened, and what was expected):
Tried out several godot-demo-projects. All crash unexpectantly after pressing the PLAY button.
Errors in console -
https://postimg.org/image/nm2orqpgl/

**Steps to reproduce:**

Open 32 bit 2.1 Godot in Linux, "./Godot..."
New Project -> Open Scene -> Play.

**Link to minimal example project** (optional but very welcome):
https://github.com/godotengine/godot-demo-projects

**Comment by akien-mga** [comment]
Your image is offline, it's better to include images directly by drag and drop or to copy paste errors.
What demos are you trying?

**Comment by ryancito02** [comment]
My image is looking fine to me.

I am trying multiple demos, all crash. 
Makes me suspect I do not have a depencency installed.

However, under "wine godot.." I can run the demos perfectly.

![selection_003](https://cloud.githubusercontent.com/assets/17111990/18259669/162bb0e0-73d6-11e6-923d-24261eddff4d.png)

Here's the image again.

**Comment by akien-mga** [comment]
How are you running the demos, and what is `stage.scn`?
The path should look like this:
```
running: /home/akien/Projects/godot/godot.git/bin/godot.x11.tools.64 -path /home/akien/Projects/godot/godot-demo-projects/3d/kinematic_char -rdebug localhost:6007 -p 0x0 res://level.scn
```

In your case you have `res://godot-demo-projects/3d/kinematic_char/level.scn`, which is bogus. There is no `stage.scn` file in the kinematic_char demo either.

It sounds like you have a project initialized in `/home/cortanium/Downloads/Godot2/` (which an `engine.cfg`, and a `stage.scn` there, and you're trying to load a the `godot-demo-projects/3d/kinematic_char/level.scn` file directly from this project, which is not working as the `level.scn` scene expects to find its data in `res://`, not in `res://godot-demo-projects/3d/kinematic_char/`.

**Comment by ryancito02** [comment]
I go into the demos directory, and go under 3D, than kinematic or whichever demo I wish to load.
I then do a recursive copy on everything in the directory (et. cp -r ~/Downloads/godot-demo-projects/3d/kinematic_char/* ~/Downloads/Godot2/ ) and than proceed to open the Linux version of Godot and try to run the program. Repeating these steps works perfectly for the WINE version of Godot, the exe, but they do not work for the Linux.

**Comment by akien-mga** [comment]
It would be much simpler to just scan the demos folder and load them in the project manager.
What's the output of `find ~/Downloads/Godot2/` ?

**Comment by akien-mga** [comment]
AFAICT this must have been a user error, as the paths and files discussed above make very little sense, and I don't see what could trigger this in Godot. Thus, closing.
