### ISSUE TITLE
Building 3.5-stable with Visual Studio 2017 fails

### ISSUE THREAD

**Issue by z80** [godotengine/godot#63975]
### Godot version

3.5-stable

### System information

Windows 10

### Issue description

Godot 3.5-stable compile attempt in Visual Studio 2017 command line tools window fails with the following output:

> main\tests\test_theme.cpp(58): error C2232: '->Variant::~Variant': left operand has 'class' type, use '.'
> main\tests\test_theme.cpp(58): note: This diagnostic occurred in the compiler generated function 'TestTheme::Fixture::Fixture(void)

It is found experimentally that this error is caused by lines 55, 56, and 57 of main/tests/test_theme.cpp. If these lines are commented, compilation succeeds:

> 	} const valid_data[Theme::DATA_TYPE_MAX] = {
> 		{ Theme::DATA_TYPE_COLOR, Color() },
> 		{ Theme::DATA_TYPE_CONSTANT, 42 },
> 		//{ Theme::DATA_TYPE_FONT, Ref<Font>(memnew(BitmapFont)) },
> 		//{ Theme::DATA_TYPE_ICON, Ref<Texture>(memnew(ImageTexture)) },
> 		//{ Theme::DATA_TYPE_STYLEBOX, Ref<StyleBox>(memnew(StyleBoxFlat)) },
> 	};

If either of the three lines is uncommented, the error is back.

### Steps to reproduce

Just run 

> scons p=windows tools=yes

in Visual Studio 2017 command line tools terminal window.

**Comment by timothyqiu** [comment]
This is probably a compiler bug. Works fine in recent versions of Visual Studio.

It's complaining about the compiler generated function using `->` to access the object's destructor instead of `.` :expressionless:  

I'll try to find a workaround.

**Comment by akien-mga** [comment]
Fixed by #63989.
