### ISSUE TITLE
Flickering colors/Garbled text with latest AMD Driver 22.7.1

### ISSUE THREAD

**Issue by JayCee-101** [godotengine/godot#63973]
### Godot version

3.5.stable

### System information

Windows 10, AMD Radeon 5500 XT, AMD Driver 22.7.1

### Issue description

Flickering green and red squares, garbled text, appear in specific areas of the editor UI while hovering objects, and also in-game as objects move.

### Steps to reproduce

Hover over elements in the Project Manager screen. 

![Screenshot 2022-08-05 114115](https://user-images.githubusercontent.com/79587945/183146472-9d873dea-c200-4432-a62e-db3353b5e980.png)

**Comment by Calinou** [comment]
Can you reproduce this in 3.4 and older releases? You can download them [here](https://downloads.tuxfamily.org/godotengine/).

Also, could you reproduce this before updating your graphics driver?

**Comment by JayCee-101** [comment]
Reinstalled 22.7.1 for testing.

Artifacts reproduced in:
3.4.5.stable
3.4.stable
3.3.stable
3.2.stable
3.1.stable
3.0.stable

Cannot reproduce in 2.1.stable and earlier.
Cannot reproduce with drivers prior to 22.7.1 (Optional).

Can consistently reproduce with 22.7.1.

**Comment by akien-mga** [comment]
It would be good to report that to AMD directly as it's apparently a regression in their drivers specifically.

**Comment by JayCee-101** [comment]
> It would be good to report that to AMD directly as it's apparently a regression in their drivers specifically.

I reported the issue through their Bug Tracker in the Radeon Software, though I'm not sure where else to report it.

**Comment by JayCee-101** [comment]
Here's the issue in-game with a moving sprite.

https://user-images.githubusercontent.com/79587945/183254165-8bd855fe-5771-44ca-9e88-588ad3dae749.mp4

**Comment by JayCee-101** [comment]
Problems persist in driver version 22.8.1 released today. New bug report sent to AMD with additional screenshots/videos and specific mentions to OpenGL regression.

**Comment by JayCee-101** [comment]
It appears to have at least temporarily been fixed for myself by doing a complete clean reinstall of the drivers and AMD software:

- Uninstall all AMD software.
- Restart in Safe Mode
- Use DDU (Device Driver Uninstaller) software to remove all traces of the drivers.
- Restart to normal Windows
- Reinstall 22.8.1

I will reopen the issue if problems persist.
