### ISSUE TITLE
`AspectRatioContainer` cant rotate.

### ISSUE THREAD

**Issue by bend-n** [godotengine/godot#63982]
### Godot version

3.5.stable

### System information

ArchLinux x11

### Issue description

It resets the `rect_rotation` to 0 when `resized` is emitted.

### Steps to reproduce

- Open minimum reproduction scene in editor. 
- It should look like:
![image](https://user-images.githubusercontent.com/70787919/183229067-18fd5239-03aa-4f16-9325-02a11d944617.png)
- Run.
- Observe: (the rotation was reset)
![image](https://user-images.githubusercontent.com/70787919/183229100-3405ce52-8610-4d80-9efc-36a07312279d.png)

### Minimal reproduction scene

```
[gd_scene format=2]

[node name="Control" type="CenterContainer"]
anchor_right = 1.0
anchor_bottom = 1.0

[node name="AspectRatioContainer" type="AspectRatioContainer" parent="."]
margin_left = 461.0
margin_top = 150.0
margin_right = 961.0
margin_bottom = 650.0
rect_min_size = Vector2( 500, 500 )
rect_rotation = 180.0

[node name="ColorRect" type="ColorRect" parent="AspectRatioContainer"]
margin_right = 500.0
margin_bottom = 500.0
color = Color( 0.623529, 0.25098, 0.25098, 1 )
```

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/59306. Your AspectRatioContainer is child of a CenterContainer, so it cannot be rotated or scaled.

**Comment by bend-n** [comment]
Ah, so i have to rotate the centercontainer? I see, that makes sense. 

My bad.
