### ISSUE TITLE
Android editor not opening any project on devices with scoped storage

### ISSUE THREAD

**Issue by Swarkin** [godotengine/godot#63981]
### Godot version

3.5 Android

### System information

Samsung Galaxy S20 FE 5G
Android 12

### Issue description

Clicking on "Edit" will not open the project, but instead open the default template.
Clicking play does run the project normally, but nothing shows up in the Editor.

### Steps to reproduce

Click on 'Edit'

### Minimal reproduction project

Any project

**Comment by Swarkin** [comment]
Update: It seems to be unable to read res:// folder at all
![Screenshot_20220806-015834_Godot Editor](https://user-images.githubusercontent.com/102416174/183225067-2e7905a1-622d-48cc-a803-6e116a8f0d0c.png)

**Comment by Calinou** [comment]
This sounds like a scoped storage-related regression.

**Comment by Swarkin** [comment]
I have found a workaround (not a permanent fix tho);
Resetting the app's data allows me to view and edit a project normally *once*.
More details:
https://drive.google.com/file/d/17VnFaMENv-xXYkHsxdfF2Bac8dyjl-eL/view?usp=drivesdk

**Comment by m4gr3d** [comment]
@Swarkin @AndyAnon14 The first time you open the Godot Android Editor, there should be a prompt asking for some storage related permissions. Did you provide access when requested?

**Comment by AndyAnon14** [comment]
Yes, when prompted to for file permissions, full permissions were given to Godot. My assumption is that the setting is not being saved, therefore when you exit the editor and go back into it, it does not show the project files. The indication that has prompted me to believe that is the case is that, in Settings, under Apps, when you look at the permissions for Godot, it shows that it does not have any permission other then full network access.

**Comment by francocurotto** [comment]
I have this exact same problem. I tested and it also occurs 3.5-rc8, but 3.5-rc7 works fine.

**Comment by Swarkin** [comment]
Sorry for the delayed reply.
@m4gr3d The app asked for the "All file access" permission (Not the usual "Files and media" permission tho)
![Screenshot_20220813-005954_Settings](https://user-images.githubusercontent.com/102416174/184454928-95fdb0f0-d6b1-4c6d-84c1-c76972d15091.png)
...which I've accepted. 
Permissions tab shows nothing:
![Screenshot_20220813-010019_Permission controller](https://user-images.githubusercontent.com/102416174/184454930-03182dc5-c942-4cbb-bd10-a0a3489a018a.png)

**Comment by m4gr3d** [comment]
I was able to reproduce the issue myself.. definitely a regression because I had tested that scenario before and it was working as expected.
I'll investigate what may be the cause of the issue.
