### ISSUE TITLE
Curve texture in visual shader should default to no-repeat for the curve

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#63993]
### Godot version

v4.0.alpha.custom_build [557953d84]

### System information

Linux Fedora, Radeon RX 590

### Issue description

Curvetextures repeat by default in visual shader, which causes unexpected behaviour.
https://gfycat.com/fatalsnoopyalaskajingle

### Steps to reproduce

Use mrp, play animation in animation player, open "shattershield" shader, navigate to the texture uniform node, change repeat mode.

### Minimal reproduction project

[ShatterShield.zip](https://github.com/godotengine/godot/files/9274803/ShatterShield.zip)

**Comment by Calinou** [comment]
This isn't possible in 4.0 anymore as the filter/repeat flag is now set in the usage location (i.e. the uniform), as opposed to the texture in 3.x.

**Comment by QbieShay** [comment]
@Calinou there's a curvetexture node in VS, I suppose that could be changed to use the right sampler flags?

**Comment by Chaosus** [comment]
I think adding a checkbox to this node is not a bad idea.
