### ISSUE TITLE
platform/x11/speechd-so_wrap.h:88:10: fatal error: 'libspeechd.h' file not found

### ISSUE THREAD

**Issue by madmiraal** [godotengine/godot#63990]
### Godot version

3.x (9be7c49a5d6dda496d6f700b00a9994532be04b6)

### System information

Ubuntu 22.04

### Issue description

When trying to build the 3.x branch I get a warning:
```
Warning: Speech Dispatcher development libraries not found. Disabling Text-to-Speech support.
```
However, the build still fails:
```
platform/x11/speechd-so_wrap.c:86:10: fatal error: 'libspeechd.h' file not found
```
So the build system is aware that I don't have the speech dispatcher development libraries installed, but it still creates the wrapper, and then it is unable to use it.

Related to #63642

### Steps to reproduce

Ensure the speech dispatcher development libraries are not installed.
Try build the Godot 3.x branch on Linux.

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
Fixed by #63991.
