### ISSUE TITLE
Quit to Project List shortcut wrong for macOS

### ISSUE THREAD

**Issue by Blanen** [godotengine/godot#64007]
### Godot version

4.0.dev

### System information

macOS 12.3 macbook air m1 2020 base specs

### Issue description

<img width="467" alt="image" src="https://user-images.githubusercontent.com/7236824/183260199-9e5aa929-fe30-42eb-bb34-b58730364bcd.png">

Quit to Project List shortcut says "Shift+Alt+Q" but I don't have an Alt key. Cmd+Shift+Q log me out of my mac. Cmd+Ctrl+Q locks my mac. Cmd+Option+Q does nothing. 

Relevant code is:
https://github.com/godotengine/godot/blob/master/editor/editor_node.cpp#L6624

Both 

	ED_SHORTCUT_AND_COMMAND("editor/quit_to_project_list", TTR("Quit to Project List"), KeyModifierMask::CMD + KeyModifierMask::SHIFT + Key::Q);

and

	ED_SHORTCUT_OVERRIDE("editor/quit_to_project_list", "macos", KeyModifierMask::SHIFT + KeyModifierMask::ALT + Key::Q);

Cmd+Option+Q seems like a possible option instead.

I could make the PR

### Steps to reproduce

Have macOS.
Use Godot.

**Comment by akien-mga** [comment]
Did you mean to close this?
