### ISSUE TITLE
Can't reopen a project after working on materials and shaders

### ISSUE THREAD

**Issue by FroggEater** [godotengine/godot#64001]
### Godot version

4.0.alpha13

### System information

macOS 12.4, M1

### Issue description

Here's the log: https://pastebin.com/3XgnQu1i

My current project doesn't open - at all - after closing the editor after some work on materials/shaders. Renaming my materials or shaders folder seems to allow me to open it again. There are no issues while actually working on them, seems that the problem occurs when trying to load them.

Redownloading Godot (and deleting the editor data inbetween) or deleting the local .godot folder don't resolve the issue.

### Steps to reproduce

I've had trouble pinpointing the root cause, last time it happened I was editing .gdshader files attached to ShaderMaterials, all in a multi-pass setup, and visualizing the changes in a test scene I had saved for that purpose. After saving everything (while it all worked as expected) yesterday and quitting the editor, I haven't been able to open the project again today.

### Minimal reproduction project

I'll put a minimal reproduction project as soon as I manage to reliably reproduce the issue.

**Comment by KoBeWi** [comment]
@FroggEater Does the issue still occur in rc3?

**Comment by KoBeWi** [comment]
Closing, comment if it still occurs.
