### ISSUE TITLE
Tilemaps made in 3.x are lost when opening in 4.x

### ISSUE THREAD

**Issue by and3rson** [godotengine/godot#64006]
### Godot version

3.5-rc8, 4.0.dev

### System information

ArchLinux

### Issue description

Tileset data as well as tilemap itself loses all tile configurations and renders a blank tilemap when using Godot 4.x to open project with tilemap made in 3.x.

### Steps to reproduce

- Create project with tilemap in Godot 3.5-rc8
- Open project in Godot 4.0.dev
- Observe blank tilemap. Textures are still in the list, but no configured tiles are visible.

3.x:
![image](https://user-images.githubusercontent.com/190107/183260282-1679ac1b-042a-44b2-9e50-9e6e79f409fd.png)

4.x:
![image](https://user-images.githubusercontent.com/190107/183260314-3afded85-83e1-4a03-8bb9-7e31eb110c50.png)
(nothing in "Patterns" and "Terrains" as well)

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/9275524/test.zip)

**Comment by Calinou** [comment]
Is there any tilemap converter in place yet? cc @qarmin

**Comment by and3rson** [comment]
@qarmin Is this something I could help with? Tilemap migrations are probably the only thing that prevents us from fully witnessing all the beauty of 4.0.

**Comment by qarmin** [comment]
I checked tilemaps in both 3.x and 4.0 version, but looks for me that converter cannot really handle such differences between this two versions.

I think that better and easier would be to add compatibility mode when loading tilemaps.

**Comment by and3rson** [comment]
@qarmin Would that be doable? I think there are really many games that use 3.x TileMap (including our ongoing projects) and it would be a real blocker to migrate to 4.x. Another solution would be to port entire 3.x's TileMap as some sort of LegacyTileMap to preserve full backward compatibility since TileMaps in 4.x seem very incompatible with 3.x.

**Comment by groud** [comment]
The conversion should be more or less automatic already, I implemented a few things to make sure at least atlases gets converted correctly.
Though to make it clear, don't expect full retro-compatibility from 3 to 4. There will be a lot of situations where automatic conversion is not possible.

**Comment by and3rson** [comment]
@groud Sounds awesome! Are autotiles converted as well?

**Comment by groud** [comment]
I checked the MRP, and it seems like the only tile present is an autotile one. Sadly, autotiles cannot be converted automatically from 3.x to 4.x, and thus require manual work. Could you confirm the tiles in your original project were using autotiles too ?
Otherwise, I think we can close this issue with #72173.
