### ISSUE TITLE
Use `VARIANT_BITFIELD_CAST()` consistently for all flag enums

### ISSUE THREAD

**Issue by TemesaGames** [godotengine/godot#64005]
### Godot version

3.5

### System information

PopOS

### Issue description

When I get the list of script variables of a node by calling the get_property_list() method, the properties related to export variables comes with the value 8199 in "usage" instead of 8192 used for the flag PROPERTY_USAGE_SCRIPT_VARIABLE. I cannot find this new flag in the Docs and neither in the GlobalScope.xml.

### Steps to reproduce

Create a script with some export variables, use the get_property_list() in the _ready() method and analyze the "usage" key of the script variables (that come at the end of the list).

**Comment by timothyqiu** [comment]
Property usage is a [bit field](https://en.wikipedia.org/wiki/Bit_field).

8199 is a combination of 1, 2, 4, and 8192. (`PROPERTY_USAGE_STORAGE`, `PROPERTY_USAGE_EDITOR`, `PROPERTY_USAGE_NETWORK`, and `PROPERTY_USAGE_SCRIPT_VARIABLE`.)

**Comment by Calinou** [comment]
Closing per @timothyqiu's comment. (I remember already telling you about bitfields elsewhere…)
