### ISSUE TITLE
`Condition "!parent_2d" is true.` error for `TileMap` with `bake_navigation=true` and no `Navigation2D` parent

### ISSUE THREAD

**Issue by kleonc** [godotengine/godot#64011]
### Godot version

3.5.stable

### System information

N/A

### Issue description

`TileMap` with `bake_navigation=true` and no `Navigation2D` ancestor/parent (or non-`Node2D` node between them) results in errors:
```
E 0:00:00.509   get_relative_transform_to_parent: Condition "!parent_2d" is true. Returned: Transform2D()
  <C++ Source>  scene/2d/node_2d.cpp:356 @ get_relative_transform_to_parent()
E 0:00:00.519   get_relative_transform_to_parent: Condition "!parent_2d" is true. Returned: Transform2D()
  <C++ Source>  scene/2d/node_2d.cpp:356 @ get_relative_transform_to_parent()
```

Seems like a regression from #61996, cc @smix8.

### Steps to reproduce

Add a `TileMap` and set `bake_navigation` to true.

Errors (on run / reparenting nodes etc. in the editor):
![TeKagG4MQh](https://user-images.githubusercontent.com/9283098/183262267-a2bce01b-0686-47ac-b9bf-afd0b6fd9fcc.png)![Godot_v3 5-stable_win64_kGUvIfh2OV](https://user-images.githubusercontent.com/9283098/183262217-e623719c-5683-4d9d-8bce-b3edcf98b9ba.png)![BSuEaOFXgG](https://user-images.githubusercontent.com/9283098/183262218-7974c787-0fc7-4405-a219-e9a678648f21.png)

No errors:
![rQhRmZEkPc](https://user-images.githubusercontent.com/9283098/183262224-dadb9e22-bf28-4134-9f1f-4f57fa95644b.png)![4902QvFokT](https://user-images.githubusercontent.com/9283098/183262225-aacd8356-ad0e-464b-8fe0-d106df2e251e.png)

**Comment by akien-mga** [comment]
Fixed by #64013.
