### ISSUE TITLE
ColorPicker Placement in Create Node Dialog

### ISSUE THREAD

**Issue by DarkiStar** [godotengine/godot#64032]
### Godot version

3.5 stable

### System information

Windows 10

### Issue description

Hello,

the ColorPicker Node on my system appears inside the Container Group (see Screenshot). I wonder if this is indented or not?

![image](https://user-images.githubusercontent.com/23613040/183277735-52da8892-efd6-41fd-9b2c-328667f577ea.png)

### Steps to reproduce

Add a node in the editor and look under BoxCointainer group.

**Comment by Calinou** [comment]
This is expected, as ColorPicker inherits from BoxContainer.

**Comment by KoBeWi** [comment]
> I wonder if this is indented or not?

Yes.
