### ISSUE TITLE
Multiple graphical issues with the Ubershader

### ISSUE THREAD

**Issue by LRFLEW** [godotengine/godot#64040]
### Godot version

3.5-stable

### System information

Windows 10 21H1 (OS Build 19043.1826), GLES3, Nvidia GTX 1080 Ti (Driver 516.59)

### Issue description

In the comments of godotengine/tps-demo#130, we discovered a few graphical issues when using asynchronous shader compilation when the ubershader is in use. A few of these issues are regressions from 3.5 release candidates / betas. Since these are all related to the Ubershader, I'm making this as one issue report to avoid spamming. If this would work better broken up into multiple issues, let me know and I'll make the other issues.

## Inconsistent Lighting

Lighting doesn't seem to be work correctly with the ubershader. Bisecting showed that this is a regression caused by #62628. Notably, the lighting seems to flicker as more shaders get compiled. Below is a video comparison showing the issue. The first video used 1fa9c75, while the second video used its parent commit 64caa62.

https://user-images.githubusercontent.com/607715/183283972-57f8d086-8f82-4fb7-847b-00add490a476.mp4

https://user-images.githubusercontent.com/607715/183283977-9bd13c45-a4d2-4d4f-8a3e-dea91ce503cc.mp4

## Black Bullets

The bullets are rendered as completely black with the ubershader, when they should be white. Bisecting showed that this is a regression caused by #57674. Below is an image comparison showing the issue. The first used 3eee2f4, while the second used its parent commit 7c49b8e.

![Image of commit 3eee2f4, showing the bullets rendered as black](https://user-images.githubusercontent.com/607715/183285027-12c8ffd3-3f0d-4802-b923-1333a86f9067.png)

![Image of commit 7c49b8e, showing the bullets rendered as white](https://user-images.githubusercontent.com/607715/183285013-3d936117-f920-4c00-af7c-079922e24439.png)

## Glowing Objects Don't Glow

Multiple objects in the game, including the robot's eyes and the bullets, don't have their glowing appearance with the ubershader. The objects do appear to still cast light (easiest seen with the bullets), so it's an issue with the objects' own appearance. This does **not** appear to be a regression, since it occurs all the way back with #53411. Both videos posted before show the issue with the robot's eyes clearly. Below is an image of what the bullets look like with the specialized shaders compiled for comparison with the previous image.

![Image showing the bullets rendered with a glowing effect](https://user-images.githubusercontent.com/607715/183285018-8db918ad-9c9c-49ed-ba3f-05c8a65d5011.png)

### Steps to reproduce

Open the project from [godotengine/tps-demo](https://github.com/godotengine/tps-demo), and change the setting `rendering/gles3/shaders/shader_compilation_mode` to Asynchronous. You can also change it to Asynchronous + Cache, but it's easier to repeat the testing with the cache disabled. You also might also want to clear the driver's shader cache at `%LOCALAPPDATA%\NVIDIA\GLCache` by deleting any folders that exist there, otherwise the driver will compile the shaders too quickly to see what the Ubershader is doing.

### Minimal reproduction project

Tested using godotengine/tps-demo@c1c4cc2

**Comment by Zireael07** [comment]
Someone else just complained of auto-exposure being "flickery", is that likely a related/dupe to your first point?

**Comment by LRFLEW** [comment]
@Zireael07 Possibly. You can ask that person to test if the flickering occurs in [3.5 RC 5](https://downloads.tuxfamily.org/godotengine/3.5/rc5/) (the last release candidate without that PR merged). If it isn't "flickery" on that version, then it's likely the same issue. If not, then it's probably something else (maybe related to the last point here).

**Comment by akien-mga** [comment]
Fixed by #64096.
