### ISSUE TITLE
Godot don't support Greek Characters

### ISSUE THREAD

**Issue by Chrisanthos** [godotengine/godot#6404]
**Operating system or device - Godot version:**

Linux - Ubuntu 16.04.1 - Godot : 2.1-stable

**Issue description** (what happened, and what was expected):

Am trying to make a Greek language game but Godot not showing the text. :|

**Steps to reproduce:**
- Make any Control node with Text
- Try to type in Greek

**Link to minimal example project** (optional but very welcome):

**Comment by vnen** [comment]
Do you have set a font with Greek characters?

**Comment by reduz** [comment]
does the text appear in the editor?

**Comment by Chrisanthos** [comment]
@vnen No i have not set a font.

@reduz The text does not appear.

**Comment by reduz** [comment]
I wonder if our DroidSans has greek.. it should have should it not?

**Comment by inferno986return** [comment]
@reduz According to FontSquirrel it does support the entire Greek alphabet. Being a former operating system UI typeface I would be surprised at its omission if there was one.

https://www.fontsquirrel.com/fonts/droid-sans

**Comment by vnen** [comment]
It appears in the inspector, but not on the control itself:

![godot windows opt tools 64 2 1_2016-09-10_23-17-19](https://cloud.githubusercontent.com/assets/5599796/18414765/c6919fa6-77ac-11e6-8c1a-5d6628bca11b.png)

@reduz is DroidSans the default font for in-game controls too?

**Comment by bojidar-bg** [comment]
Any status on this issue?

**Comment by reduz** [comment]
This is not a bug, the default internal engine font is latin-only. If you
import a TTF or OTF with greek chars, they will display fine..

**Comment by volzhs** [comment]
This is a little bit related to #8998, but need to be increased "default" exported engine file size.

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
Godot's font supports Greek characters now (I think since Godot 2.1 at least).
