### ISSUE TITLE
Debugger report error running scene [F6]

### ISSUE THREAD

**Issue by mo-moxi** [godotengine/godot#64042]
### Godot version

v3.5.stable.official [991bb6ac7]

### System information

Debian Linux 10, Intel Graphics HD 4000, GLES3

### Issue description

Debugger report:

E 0:00:00.476   Invalid (float) numeric constant
  <C++ Source>  :7

 running a scene

### Steps to reproduce

Play the attached file in Godot 3.5 stable

### Minimal reproduction project

file:///home/mem/Godot/Projects/godot-practice/SideScroller/Level.zip

**Comment by Calinou** [comment]
> file:///home/mem/Godot/Projects/godot-practice/SideScroller/Level.zip

To upload a file, you need to drag-and-drop the file in the text field, not its path. And don't click away until the file is done uploading :slightly_smiling_face:

**Comment by akien-mga** [comment]
You need to fix your shader code to make sure that floats use a dot. `1.0` or possibly `1.0f`, not `1` or `1f` (Godot used to support the latter but it's illegal in GLSL so we removed support for it for consistency).
