### ISSUE TITLE
`Image.rotate_90()` exhibits scaling artifacts

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#64048]
### Godot version

v4.0.alpha13.official [59dcddc45]

### System information

Windows 10, 64bit

### Issue description

Image.rotate_90 not perfect, look:
![Cap](https://user-images.githubusercontent.com/35988767/183290059-8dc0dcb9-b57e-4d65-bcef-7739e045fbbb.PNG)

### Steps to reproduce

Please run the reproduction project

### Minimal reproduction project

[RotTest.zip](https://github.com/godotengine/godot/files/9276746/RotTest.zip)

**Comment by Calinou** [comment]
cc @Chaosus
