### ISSUE TITLE
SubViewport display a pink/blue square

### ISSUE THREAD

**Issue by fabriceci** [godotengine/godot#64055]
### Godot version

Godot 4 alpha 13

### System information

MacOS 11.6

### Issue description

I was unable to use a SubViewport as a texture:

![Screenshot 2022-08-07 at 15 41 17](https://user-images.githubusercontent.com/6397893/183293755-b743a0c1-dcbe-463f-bf4a-fc37aa30f987.png)

### Steps to reproduce

Add a SubViewport and add the Godot icon inside it  and check the preview.

**Comment by Calinou** [comment]
Can you reproduce this in previous 4.0 alphas? You can download them [here](https://downloads.tuxfamily.org/godotengine/4.0/);

**Comment by fabriceci** [comment]
@Calinou Yes in alpha 13-12-4-2 and the master, I also tried #63306 but doesn't fix the issue.

**Comment by fabriceci** [comment]
I tried #62938 #63091 they don't help either.

**Comment by Noiros** [comment]
same issue on windows with same scene and with 3d camera (on alpha 13, 11, 10, 9)

**Comment by mieldepoche** [comment]
(alpha 13)
Setting `size_2d_override_stretch` to `true` and `render_target_update_mode` to `Always` solves this problem on my end.

**Comment by fabriceci** [comment]
@mieldepoche thanks! Indeed put `render_target_update_mode` to `always` solve the issue.

The issue seems to be that the Viewport is not detected as being visible (although it is).

**Comment by Rindbee** [comment]
This seems to be a duplicate of #55471, I have a try in #62854.
Refer to https://github.com/godotengine/godot/issues/55471#issuecomment-1179535202, https://github.com/godotengine/godot/pull/62854#issue-1299673343.

**Comment by fabriceci** [comment]
Duplicate of #55471.
