### ISSUE TITLE
Time.get_unix_time_from_system() in 3.5 returns a float without the msecs

### ISSUE THREAD

**Issue by Reneator** [godotengine/godot#64059]
### Godot version

v3.5.stable.official [991bb6ac7]

### System information

Windows 10

### Issue description

Im currently migrating my project from OS.get_system_time_msecs() to use the new and recommended Global class Time. As i need downwards compatability with older save-games that have the entire date-time as msecs, i found out i could use `Time.get_unix_time_from_system() * 1000.0` to get the same number. (source: https://godotengine.org/qa/130003/why-was-getting-milliseconds-system-time-removed-in-godot-4)

But on my system the number returned by  `Time.get_unix_time_from_system()` is actually missing the msecs:

![image](https://user-images.githubusercontent.com/24807557/183298030-93cef259-274a-41b7-8bdb-07dffab7b120.png)

Whereas in Godot 4 alpha 13 it gets the msecs:

![image](https://user-images.githubusercontent.com/24807557/183298060-3d7d5035-cd4e-41ca-b8c9-bc2a2e278c36.png)

### Steps to reproduce

Run

```
func _process(delta):
	print("%.6f" % Time.get_unix_time_from_system())
```
	
and check the output in the console.

**Comment by akien-mga** [comment]
Fixed by #64101.

**Comment by Reneator** [comment]
Thanks a lot!

**Comment by darkconsole** [comment]
what is the best way to file a regression? 4.2.1 is doing it XD

![image](https://github.com/godotengine/godot/assets/9095897/0824423e-0f2f-4a2e-b715-5eae4eb28d2e)
