### ISSUE TITLE
Debugging opens window as maximized and is ignoring Width/Height settings, MacOS

### ISSUE THREAD

**Issue by danielkariv** [godotengine/godot#64056]
### Godot version

3.5stable

### System information

MacOS 12.5, Macbook Pro M1.

### Issue description

When playing projects in editor, the window is openned as maximized instead of running with given width/height settings.
Notice: it doesn't happen when exported, the window is opens as was set in settings.
For example with default settings:
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/38776931/183295495-0f48c381-c990-4733-bf39-289e5a511875.png">
It opens the new window like this:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/38776931/183295521-94bd2f2e-bd7e-4bb9-8c5b-d98a88317ee0.png">

 

### Steps to reproduce

Create new project and basic scene (in my case it was just a Control node), and play that scene.

**Comment by Calinou** [comment]
Enable **Allow Hidpi** in the project settings and try again.

**Comment by danielkariv** [comment]
> Enable **Allow Hidpi** in the project settings and try again.

Tried it now, it doesn't solve it, it just make the UI smaller but the window itself still opens as maximized.

**Comment by Calinou** [comment]
In the Editor Settings, double-check that **Run > Window Placement** is set to its default value.

**Comment by danielkariv** [comment]
> 

You are right, it seems to be set to **Force Maximized** and changing it to **Centered** does deliver the right behavior (Atleast what it was before).
Now when creating new project it stays **Centered**, so I guess it fine now. 
Considering that it is a engine settings, it is probably a change in my local device and not from engine side.
So I think we can close this issue.

Note: I was working with Godot 4 alpha builds for a good while, so maybe a change there has changed the engine settings in Godot 3.X.
