### ISSUE TITLE
MultiplayerSynchronizer not working

### ISSUE THREAD

**Issue by colin-h** [godotengine/godot#64053]
### Godot version

4.0.alpha13

### System information

MacOs

### Issue description

When adding a `MultiplayerSynchronizer` node to my `CharacterScene` I expect the default configuration to work. By "work" here I mean successfully send packets to the server on the other end of the wire.

Instead, when I create a new character node, the synchronizer attempts to send a packet but throws the following error:
```
ERROR: Condition "!sync || !sync->get_replication_config().is_valid()" is true. Continuing.
   at: _send_sync (scene/multiplayer/scene_replication_interface.cpp:444)
```

I found that if I uncheck the "Public Visiblity" checkbox. The error message disappears... however it does not seem that the spawn packets get to the clients.
<img width="280" alt="Screen Shot 2022-08-07 at 8 29 36 AM" src="https://user-images.githubusercontent.com/5582627/183293170-0ef16e3a-eb82-4f6c-ae08-7c9d2c157ea0.png">
 

### Steps to reproduce

1. Run a headless server instance of the repro project. `<path_to_godot> --path <path_to_project> --server --headless` 
2. Run a client instance of the project using the Editor or the following command: `<path_to_godot> --path <path_to_project>` 
3. See error appear in server terminal
<img width="568" alt="Screen Shot 2022-08-07 at 8 33 42 AM" src="https://user-images.githubusercontent.com/5582627/183293343-f609edb9-840e-43ff-8d31-a476484fe3f2.png">
.

### Minimal reproduction project
[sync_bug.zip](https://github.com/godotengine/godot/files/9276916/sync_bug.zip)

**Comment by jgillich** [comment]
Your replication config is empty, you need to add the property. Once I do, this works fine.
![Screenshot from 2022-08-09 12-25-55](https://user-images.githubusercontent.com/347965/183626813-76995143-e47e-4518-8a01-46017a763cc6.png)

If the replication window doesn't open try a master build, it's bugged in alpha13

**Comment by colin-h** [comment]
Just a ui bug in alpha 13

**Comment by alexeocto** [comment]
> Your replication config is empty, you need to add the property. Once I do, this works fine. ![Screenshot from 2022-08-09 12-25-55](https://user-images.githubusercontent.com/347965/183626813-76995143-e47e-4518-8a01-46017a763cc6.png)
> 
> If the replication window doesn't open try a master build, it's bugged in alpha13

took me hours to spot that thing. I don't see it mentioned at all on the docs. this saved me.
