### ISSUE TITLE
using set_cell() function in Tilemap will report a bug after setting offset of the tile

### ISSUE THREAD

**Issue by EXSPIRAVIT1104OFFICIAL** [godotengine/godot#64062]
### Godot version

4.0.alpha13.official (59dcddc45)

### System information

Windows 10, Vulkan, NVIDIA GeForce RTX 3050 Laptop GPU

### Issue description

The tilemap set_cell() function will produce a bug report (get_tile_effective_texture_offset: Condition "!tile_set" is true. Returning: Vector2i()) after setting the offset of the tile and enable the local to scene option

### Steps to reproduce

Create a new Tilemap node.
Create a new Tileset and set the Tile offset to any number.
Enable local to scene option
Write code to set the tile to any position.

**Comment by timothyqiu** [comment]
I'm unable to reproduce this with the given steps.

Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.
