### ISSUE TITLE
Program crashed with signal 11

### ISSUE THREAD

**Issue by ChromiumOS-Guy** [godotengine/godot#64061]
### Godot version

flatpak version 3.4.4 stable

### System information

linux debian 11

### Issue description

 
================================================================
 handle_crash: Program crashed with signal 11
 Engine version: Godot Engine v3.5.stable.flathub (991bb6ac74ac8c09d7683041b50a8ced3a2defb1)
 Dumping the backtrace. Please include this when reporting the bug on: https://github.com/godotengine/godot/issues
 [1] /usr/lib/x86_64-linux-gnu/libc.so.6(+0x39510) [0x7f2033753510] ()
 [2] /app/bin/godot-bin() [0xb6adc2] ()
 [3] /app/bin/godot-bin() [0xb077f8] ()
 [4] /app/bin/godot-bin() [0x2e578be] ()
 [5] /app/bin/godot-bin() [0x2eef352] ()
 [6] /app/bin/godot-bin() [0xb786a8] ()
 [7] /app/bin/godot-bin() [0xb077f8] ()
 [8] /app/bin/godot-bin() [0x2e578be] ()
 [9] /app/bin/godot-bin() [0x30b1883] ()
 [10] /app/bin/godot-bin() [0x2f7c600] ()
 [11] /app/bin/godot-bin() [0x34da915] ()
 [12] /usr/lib/x86_64-linux-gnu/libpthread.so.0(+0x83ba) [0x7f2033a513ba] ()

### Steps to reproduce

try to make a thread pool then run a interactive loader on it that also saves the progress inside of the task (inside the thread pool task array)

this line crashes everything when trying to add child
get_tree().get_root().add_child(resource)
after that there is code that cleans the tree from unwanted scenes
all the avoid another bug where get_tree().change_scene_to() 
doesn't work it maybe adds sometimes but never deletes

i have the code here you can attach it to other code to make it work

### Minimal reproduction project

```

func __load_scene_interactive(data, task): # handels polling and scene switching
	if OS.can_use_threads(): # double check if platform supports aysnc (no fallback if it failes)
		var loader = ResourceLoader.load_interactive(data[0])
		var path = data[0]
		var print_to_console = data[1]
		if loader == null and task.target_argument == null: # complains about invalid paths
			print("Resource loader unable to load the resource at path")
			return
		
		var t = OS.get_ticks_msec()
		
		while OS.get_ticks_msec() - t < max_load_time: # polling / loading selected scene and updating progress for loading bar
			var err = loader.poll()
			if err == ERR_FILE_EOF:
				#Loading Complete
				var resource = loader.get_resource().instance()
				get_tree().get_root().add_child(resource)
				print("i")
				for child in get_tree().get_root().get_children(): # gets children of root and queue_free() them if they are not a singleton
					if autoload_names.has(child.get_name()): # checks if the childs name is valid for exclusion from queue_free() by looking up its name and seeing if it exist in Globals.autoload_names
						pass
					elif child == resource:
						pass
					else:
						child.queue_free()
				if print_to_console:
					print(path.get_file()," is complete!")
				break
			elif err == OK:
				#Still loading
				var progress = float(loader.get_stage())/loader.get_stage_count()
				task.progress = progress * 100
				if print_to_console:
					print(path.get_file()," is at %",progress * 100," completion!")
			else:
				print("Error while loading file") # if err isn't ERR_FILE_EOF(completed) or OK(still loading) the something Is preventing the file from loading
				break
		yield(get_tree(),"idle_frame") # makes it possible to see end result
```

**Comment by Calinou** [comment]
@ChromiumOS-Guy Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot. (The code sample is not a complete reproduction project as it won't work on its opwn.)

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
