### ISSUE TITLE
PR #63388 broke LSP on Linux

### ISSUE THREAD

**Issue by permelin** [godotengine/godot#64064]
### Godot version

v4.0.alpha.custom_build [f2ddd8172]

### System information

Linux

### Issue description

#63388 replaces `///` with `//` in LSP file paths, which apparently fixes #63205 on Windows. But `file:///` is entirely correct on Linux and much LSP functionality is now broken on Linux as a result. For example, externally modified script files are not reloaded and features like _go to definition_ does not work in the LSP client.

The console is spammed with these two errors:

```
ERROR: Attempt to open script 'file:/home/<snip>' resulted in error 'File not found'.
   at: load_source_code (modules/gdscript/gdscript.cpp:1062)
ERROR: Attempt to open script 'file://home/<snip>' resulted in error 'File not found'.
   at: load_source_code (modules/gdscript/gdscript.cpp:1062)
```
I reverted commit 3fa943fe23 locally and that fixed the problem.

Ping @A-Lamia and sorry for reporting a bug on your first commit.

### Steps to reproduce

1. Open Godot editor on Linux.
2. Connect an editor via LSP.
3. Notice the errors in the Godot console.
4. Notice that modified script files are not reloaded in Godot.

**Comment by A-Lamia** [comment]
No problems i was unable to know if there was issues on other OS's asked around but no one said anything. Would this also be an issue for macOS ?

**Comment by A-Lamia** [comment]
@akien-mga is there a function to check the OS that is currently running ?

**Comment by permelin** [comment]
> Would this also be an issue for macOS ?

Yes, I think it would. An absolute path on Linux or macOS starts with `/` instead of `C:` which is why we get the third slash in `file:///`.

> is there a function to check the OS that is currently running ?

`OS.get_name()` but I wonder if there isn't a cleaner solution than using that. First step should be to figure out where the bad path comes from on Windows. Is it sent by the LSP client or generated by Godot?

**Comment by A-Lamia** [comment]
well i was planning to hotfix it then figure out the root issue id imagine this bug would annoy a lot of people.

**Comment by permelin** [comment]
Since LSP is just JSON, I dumped the traffic on port 6008 and the path seemingly comes straight from the client.
```JSON
{
  "method":"textDocument\/didSave",
  "params":{
    "text":"\n\n",
    "textDocument":{
      "uri":"file:\/\/\/home\/p\/Godot\/Test\/test.gd"
    }
  },
  "jsonrpc":"2.0"
}
```

You did this in your commit:
```C++
path = path.replace("%3A", ":");
```
But was that necessary? Further down `uri_decode()` is called on the path and it does the same thing.

**Comment by A-Lamia** [comment]
@permelin for some reason when i was debugging the it would leave uri_decode with `%3A` still there, i had first "fixed" the `///` problem but was still getting errors and when i followed the memory uri_decode didn't  change it for what ever reason.

**Comment by A-Lamia** [comment]
might have found the issue doing tests

**Comment by A-Lamia** [comment]
I have possibly fixed the issue just making sure everything is working fine, found a couple issues that are sort of related. Will push a PR soon.
