### ISSUE TITLE
Selecting a .tscn entry in filesystem and clicking a node (in Scene) does not switch from editor to 2D view.

### ISSUE THREAD

**Issue by DarkiStar** [godotengine/godot#64063]
### Godot version

3.5 stable

### System information

Windows 10

### Issue description

I a pretty sure that it was possible to switch to 2d view (when you are in the script editor) by selecting a .tscn file and selecting a node in the scene window.
With 3.5 stable it is only possible to switch to 2d by selecting the "2D" label on the top ("2D","3D","Script","AssetLib").

### Steps to reproduce

Create a project (user interface)
Add a scene
Add nodes
Add a script
Edit the script
try to switch back to ui editor

**Comment by TheDuriel** [comment]
This is a "feature" now, as of 3.5 https://github.com/godotengine/godot/pull/63344

**Comment by DarkiStar** [comment]
Ah. I was not aware of that change. Thank you.
Please close this ticket then.

**Comment by DarkiStar** [comment]
Ah. I was not aware of that change. Thank you.
Please close this ticket then.
