### ISSUE TITLE
get_current_dir returns the wrong path on Android

### ISSUE THREAD

**Issue by mgschwan** [godotengine/godot#64074]
### Godot version

3.5.stable

### System information

Oculus Quest 2

### Issue description

get_current_dir() returns the path without res:// at the beginning. 

This behavior has changed from previous versions and is inconsistent with the behavior on other platforms, so it is most likely a bug.

On linux get_current_dir() does return the correct res:// path

### Steps to reproduce

Please test on Android

```
var dir = Directory.new()
dir.open("res://some/valid/path/here")
print (dir.get_current_dir())  # This will print some/valid/path/here instead of res://some/valid/path/here

```

**Comment by nathanfranke** [comment]
Yes, I have this exact issue! Caused an infinite loop in some code that iterates recursively.

Fixed by changing `dir.get_current_dir()` to whatever you opened with earlier (my case, `current`).
