### ISSUE TITLE
The Desktop Icon of the exported executable is blurry

### ISSUE THREAD

**Issue by Nikzea** [godotengine/godot#64073]
### Godot version

3.5 Steam version

### System information

Windows10

### Issue description

The Desktop Icon of the executable is blurry and I don't know how to fix this. I already redownloaded rcedit, cleared the cache, restarted the computer and reexported the project, but it is still blurry. (the .pck is not embeded)
![Capture](https://user-images.githubusercontent.com/81244063/183304716-b099643b-957b-4b1c-8fc5-bd008b7528c5.PNG)
Please help me

 

### Steps to reproduce

It worked fine 2 weeks ago, but yesterday, when I wanted to export my game, a error message appeared, saying I would need to update to 3.5. After the update finished, I exported the game, but for some reason the Desktop icon was really blurry.

**Comment by Calinou** [comment]
This is not a Godot issue. The `.ico` file you're using needs to contain all the sizes required for proper hiDPI support. There's an ImageMagick command listed in the [documentation](https://docs.godotengine.org/en/stable/tutorials/export/changing_application_icon_for_windows.html#creating-an-ico-file) which you can use for this purpose.

**Comment by Nikzea** [comment]
Thank you for the reply
The .ico file contains all sizes which are suggested in the docs, also it worked earlier only after the update it doesn't work
[Ico.zip](https://github.com/godotengine/godot/files/9277408/Ico.zip)
.

**Comment by SilencedPerson** [comment]
![image](https://user-images.githubusercontent.com/82024211/183309102-aa6421aa-9b11-4ee1-af05-eebc70227595.png)
I zoomed in on it, it works in windows by itself so that means Godot malforms it no?
Could you download resource hacker and check if the icon is properly overridden?

**Comment by Outseet** [comment]
download image magic display then converts the png to ico using this command:
magick convert icon.png -define icon:auto-resize=256,128,64,48,32,16 icon.ico

then add it to you're project and export it to a different folder then it's good

**Comment by Nikzea** [comment]
Silenced Person i downloaded resource hacker what now?

Outseet i already have a ico file why do it again?

**Comment by Outseet** [comment]
@Nikzea because it's giving more quality and resolution are great and also it'S better and faster than do it your self and it's in Godot documentation I think using image magic display is going to fix it

**Comment by Outseet** [comment]
@Nikzea also change the export to a new path

**Comment by SilencedPerson** [comment]
> Silenced Person I downloaded resource hacker what should I do now?
> 
> Outseet I already have a ico file why do it again?

![image](https://user-images.githubusercontent.com/82024211/183311890-4275bb1e-7219-49e0-94bd-e5020f9008bd.png)
drag and drop your game.exe into the resource hacker
![image](https://user-images.githubusercontent.com/82024211/183311939-260ffa99-da77-4468-9a41-060b6aec4b40.png)
You should see something like this but the godot icon will be replaced by your icon.

is that correct?

**Comment by Outseet** [comment]
@SilencedPerson  yes it's correct he need that his .ico file have all the resolution:
256,128,64,48,32,16
and this by using a software scale it like gimp or fastest way is using [ImageMagick](https://imagemagick.org/index.php)

**Comment by SilencedPerson** [comment]
> @SilencedPerson yes it's correct he need that his .ico file have all the resolution: 256,128,64,48,32,16 and this by using a software scale it like gimp or fastest way is using [ImageMagick](https://imagemagick.org/index.php)

Outseet, his Icon does indeed have all the correct resolutions, we are trying to determine if Godot malforms it. ImageMagic won't help in this case as we are not determining if he has correct formatting but if Godot has a bug or not.

**Comment by Outseet** [comment]
> > @SilencedPerson yes it's correct he need that his .ico file have all the resolution: 256,128,64,48,32,16 and this by using a software scale it like gimp or fastest way is using [ImageMagick](https://imagemagick.org/index.php)
> 
> Outseet, his Icon does indeed have all the correct resolutions, we are trying to determine if Godot malforms it. ImageMagic won't help in this case as we are not determining if he has correct formatting but if Godot has a bug or not.

i was using gimp and it'S giving me blurry icon and I have all resolution when I used ImageMagick it worked and it's great

**Comment by Outseet** [comment]
wait i have found something did you Clear the Icon Cache it maybe works I found it on youtube and [documentation](https://docs.godotengine.org/en/stable/tutorials/export/changing_application_icon_for_windows.html)

**Comment by SilencedPerson** [comment]
That is still not the point, his icon is correct.
Godot should be able to use it.

Please, stop read the issue again, he did clear his cache and the ICON did work in the past.

**Comment by Outseet** [comment]
> That is still not the point, his icon is correct. Godot should be able to use it.
> 
> Please, stop pointlessly commenting and read the issue again, he did clear his cache and the ICON did work in the past.

ok but i use the same version and it's working maybe it's a bug

**Comment by blipk** [comment]
>  he did clear his cache and the ICON did work in the past.

Clearing font icon caches in windows is notoriously unreliable, something could have corrupted on one export, and then be fixed but windows might not decide to display it for another few days.

**Comment by Nikzea** [comment]
Sorry for only replying now, but I went to bed.
![Capture2](https://user-images.githubusercontent.com/81244063/183412262-2b3e7e67-5c36-41c7-979a-a794244a1dec.PNG)
You can also download the exe on itch
https://nikzea.itch.io/marble-testing-facility

**Comment by Nikzea** [comment]
Oh I think I see the Problem for some reason the images are assigned to the wrong resolution

**Comment by SilencedPerson** [comment]
Yep, they seem to be in inverse order. Can you somehow verify that this is problem with the ICON? Or does this happen in Godot?
It seems to me that it is the later, since the icon works before the project is imported.

**Comment by Nikzea** [comment]
I reversed the order in gimp but it still shows the same in Resource Hacker and the icon is still blurry.

**Comment by Nikzea** [comment]
I reversed the order in gimp and now resource hacker shows it in the right order but it is still blurry.

**Comment by Nikzea** [comment]
SilencedPerson it should be a Problem with the new Godot version because in 3.4 it worked fine and I didn't change anything in the ico file since than.

**Comment by akien-mga** [comment]
CC @bruvzg

**Comment by bruvzg** [comment]
Godot do not do anything to the icon, it's only feeding it to the `rcedit`, so it's probably something with the export template. The only 3.5 change that might be responsible for is this is - https://github.com/godotengine/godot/pull/57850

**Comment by Nikzea** [comment]
I solved the problem, after exporting to linux the icon is now how it should be.
![Capture](https://user-images.githubusercontent.com/81244063/183431319-aef3dc43-cc7c-4076-b82c-2eeecb1a31a3.PNG)

**Comment by SilencedPerson** [comment]
So Godot holds your icon ransom until make a linux export. Good.

**Comment by SuzukaDev** [comment]
I can confirm this bug, it was driving me crazy D:
(I did everythig as the doc says, my icon had all the sizes, I made it using the imagick command (but also tried GIMP, online generators, etc)). But nothing.
After exploring the .exe in Resource Hacker I saw that it was also pairing wrongly the image and the resolution.

The thing that worked was also reverseing the order of the .ico:
A) In Gimp
![res](https://user-images.githubusercontent.com/52723367/188304300-69aa8649-ae14-404b-b38c-de09c481ef90.png)

B) Reverseing the order of sizes in the magick command:
Using this:
`magick convert icon.png -define icon:auto-resize=16,32,48,64,128,256 icon.ico`

Instead of `resize=256,128,64,48,32,16` (as the [doc says](https://docs.godotengine.org/es/stable/tutorials/export/changing_application_icon_for_windows.html#creating-an-ico-file)).

Both things worked correctly, and I also tried the to use the "reversed" icon normally in other folders and shortcuts and they work as expected. Seems like the order is only relevant for Godot when exporting.

**Comment by dannygaray60** [comment]
I recently had the same problem. Using godot 3.5.1 stable. As much as I use magisk and the command to clear cache (following everything the documentation says) and the icon still appears blurry. 
![Captura de pantalla 2022-11-16 213523](https://user-images.githubusercontent.com/30391210/202348737-363d7125-0b58-4c7a-96da-95cc1dcdd0ac.png)

Attached .ico file and .exe file
[icons.zip](https://github.com/godotengine/godot/files/10027518/icons.zip)

**Comment by bruvzg** [comment]
So the issue is size order, rcedit only set it correctly if new icon have the same order as icon already in the executable.

https://github.com/godotengine/godot/pull/57850 icon has it reversed, so only icons with `16,32,48,64,128,256` sizes will work, and with old icon only `256,128,64,48,32,16` was working, it's not directly related to the compression.

**Comment by bruvzg** [comment]
ICO format is quite simple, so I guess we can preprocess ICOs (and allow generating one from PNG) and correct the size order during export.

**Comment by wlwl2** [comment]
I've submitted two pull requests to resolve this issue in the docs. One for the order reversal and another for some troubleshooting tips after the order is fixed: https://github.com/godotengine/godot-docs/pull/8564.
