### ISSUE TITLE
ui_accept Key Press Not Detected While Moving Up Left or Down Right

### ISSUE THREAD

**Issue by dragifon** [godotengine/godot#64086]
### Godot version

v3.5.stable.official [991bb6ac7]

### System information

Linux Mint 20.3 x86_64 

### Issue description

Pressing ui_accept is not detected while holding ui_up and ui_left, or ui_down and ui_right. In the attached project this presents as no message being printed to output panel when pressing spacebar or enter key while moving up left or down right.
Might be related to issue #63972 

### Steps to reproduce

1. Start game
2. Open Output panel
3. Hold ui_left and ui_up, or hold ui_right and ui_down
4. Press ui_accept
5. Read Output panel to see message did not print 

### Minimal reproduction project

[BUG ui_accept Not Detected.zip](https://github.com/godotengine/godot/files/9277827/BUG.ui_accept.Not.Detected.zip)

**Comment by Zireael07** [comment]
Are you using a gamepad or a keyboard?

**Comment by Calinou** [comment]
Are you 100% certain that other programs are able to see the same key combination? If not, this is likely a hardware issue (keyboard ghosting), which can be fixed by getting a keyboard with antighosting functionality.

**Comment by Sslaxx** [comment]
If this is a gamepad, could this be #63972?

**Comment by dragifon** [comment]
@Zireael07  @Sslaxx  Using the keyboard built into my laptop.
@Calinou  Just tested it in other programs and, yes it appears those key combinations don't work on my laptop. Weird. Never would have considered that.
