### ISSUE TITLE
Bezier editor in animation player has no inspector for keyframes

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#64097]
### Godot version

v4.0.alpha.custom_build [862da78ee]

### System information

Linux Fedora, Radeon RX 590

### Issue description

When clicking on keyframes in the bezier editor in 4.x, there is no inspector for the keyframes, which makes inserting precise values highly challenging.

Godot3:
![image](https://user-images.githubusercontent.com/7917475/183386323-cb1da69c-acd4-4ab9-a803-aae9a0540f28.png)

Godot4
![image](https://user-images.githubusercontent.com/7917475/183385415-367b83ae-9acd-45d1-a94a-555d95d6af36.png)

### Steps to reproduce

Create an animation with curve keyframes, open the curve editor, observe no inspector.

**Comment by fire** [comment]
See also https://github.com/godotengine/godot/pull/57920

**Comment by TokageItLab** [comment]
Perhaps there is an error getting the key? I think the inspector process is not being performed due to the error. 

The key selection signal argument in the Bezier Editor was incorrect and has been fixed in #64647. Please check if that fixes it.
