### ISSUE TITLE
GDScript 2.0: Global ‘var’ in autoload script extended from ‘Object’ is 'null' when running game

### ISSUE THREAD

**Issue by CheapMeow** [godotengine/godot#64091]
### Godot version

v4.0-alpha13_win64

### System information

Windows 11

### Issue description

I have a var 'a' in genum.gd and set this gd as autoload script, naming GEnum
But when i use 'GEnum.a' in other script, debugger shows GEnum is null

```
E 0:00:03:0082   start: Script does not inherit from Node: res://core/genum.gd
  <C++ 错误>       Condition "!valid_type" is true. Continuing.
  <C++ 源文件>      main/main.cpp:2476 @ start()
```

![image](https://user-images.githubusercontent.com/88229072/183331227-56b43855-f765-49c6-8004-3b23566fd52c.png)

### Steps to reproduce

1.set this gd as autoload script, naming GEnum

```gdscript
extends Object

var a = 1
```

2.use GEnum in other script

```gdscript
extends Node2D


# Called when the node enters the scene tree for the first time.
func _ready():
	print(GEnum.a)
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	pass
```

3.run, debugger shows GEnum is null

### Minimal reproduction project

[reproduction.zip](https://github.com/godotengine/godot/files/9278466/reproduction.zip)

**Comment by 1Luc1** [comment]
changing the gdautoscript  GEnum to extend from Node works.

```
extends Node
var a = 1
```

**Comment by qarmin** [comment]
This is expected,
Godot create node, attach script to it and at the end just put it below root node.
Docs - https://docs.godotengine.org/en/stable/tutorials/scripting/singletons_autoload.html
