### ISSUE TITLE
sync_to_physics with move_and_slide_with_snap throws errors

### ISSUE THREAD

**Issue by nezvers** [godotengine/godot#64102]
### Godot version

v3.5.stable.official [991bb6ac7] AND v3.4.4.stable.official [419e713a2]

### System information

Windows 10 

### Issue description

KinematicBody2D with enabled synt_to_physics and using move_and_slide_with_snap throws errors.
```
E 0:00:00.759   move_and_collide: Functions move_and_slide and move_and_collide do not work together with 'sync to physics' option. Please read the documentation.
  <C++ Source>  scene/2d/physics_body_2d.cpp:1051 @ move_and_collide()
  <Stack Trace> IdlePlayer.gd:11 @ _process()
```
```
velocity = move_and_slide_with_snap(velocity, Vector2.DOWN * 6, Vector2.UP, true)
```

### Steps to reproduce

KinematicBody2D with enabled sync_to_physics
And code:
```
 var velocity: = Vector2.ZERO

func _process(delta:float)->void:
#func _physics_process(delta:float)->void:
	velocity.y += 5.0 * 60 * delta
	velocity = move_and_slide_with_snap(velocity, Vector2.DOWN * 6, Vector2.UP, true)
```
I'm adding an example project to press on an issue that Godot still struggles with vertically moving platforms, and that's how I found the bug (trying to solve it). Problem mentioned in #59966

### Minimal reproduction project

[BUG_sync_to_physics.zip](https://github.com/godotengine/godot/files/9281204/BUG_sync_to_physics.zip)

**Comment by akien-mga** [comment]
I don't understand what the problem is. The error tells you that you can't use `sync_to_physics` with m`move_and_slide` (and `move_and_slide_with_snap` is just a variant of `move_and_slide`). So it's not a bug, it's just not a supported feature, by design.

**Comment by nezvers** [comment]
My bad then. I assumed it's because triggering from `_process` is messing with sync to physics. And nothing else helped to sync with a platform.
What movement methods are left to move a KinematicBody with sync_to_physics?
