### ISSUE TITLE
AnimationTreePlayer don't play autoqueued animations

### ISSUE THREAD

**Issue by steelxtreme** [godotengine/godot#6411]
**Operating system or device - Godot version:**
OpenSuse Leap 42.1 64 bits
godot  2.2 alpha custom build 64 bit

**Issue description** (what happened, and what was expected):
I have setup an animation with auto queue enabled but when the animation ends is not playing next animation in queue by using AnimationTreePlayer.

**Steps to reproduce:**
Create AnimationPlayer, add two animations(anim1 and anim2 ), set Next (auto queue) from anim1 to anim2. Add AnimationPlayer to AnimationTreePlayer and animation node with anim1, start AnimationTreePlayer and auto queue doesn't work.

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
`AnimationTreePlayer` is deprecated in Godot 3.1 and will be removed in Godot 3.2. It is replaced by `AnimationTree`, which was written from scratch and likely fixes/deprecates this issue.

If the issue is still relevant in some form with `AnimationTree` in Godot 3.1, please open a new issue about it (potentially linking this one if there is relevant discussion to keep track of).
