### ISSUE TITLE
Animation Player stutters when set to continuous between same frames for big sprite sheets and frame > 100

### ISSUE THREAD

**Issue by pixelriot** [godotengine/godot#6412]
Godot v2.1 (tested on Linux and Windows)

When animating a sprite sheet with an Animation Player set to continuous interpolation and two key frames are inserted, both with the same value, the animation jumps to a different frame inbetween. This causes a stuttering in the animation.

**Steps to reproduce:**
Set up an Sprite Sheet with an animation Player. 
Set interpolation to continuous.
Insert a frame at t = 0.1 and the same frame at t = 1.0 (or so).
Play the animation or scrub through the timeline.
The frame will change.

**Comment by Dillybob92** [comment]
"Set up an Sprite Sheet with an animation Player. "

Do you mean a sprite with an attached animation player node, or a animated sprite node.

Can you please give an example file, thx :)

**Comment by pixelriot** [comment]
I mean a sprite with an attached animation player node.
I will upload an example later this evening :)

**Comment by pixelriot** [comment]
I've performed a bit more testing and found out that the bug only appears for very big sprite sheets and only if the frames of the animation are somehow over 100.

Please open the attached file and play the animation. You'll see that the frames in the middle of the animation change, although they shouldn't.


[animsprite.zip](https://github.com/godotengine/godot/files/460048/animsprite.zip)

**Comment by bojidar-bg** [comment]
Can confirm with attached same project and 2.1/HEAD

**Comment by bojidar-bg** [comment]
Looks related to floating-point precision to me, though I'm not completely sure at this point.

**Comment by Noshyaar** [comment]
Still reproducible/relevant in 3.1 master 9ad1800

**Comment by Calinou** [comment]
@pixelriot Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by KoBeWi** [comment]
This is fixed since at least 3.1.2
