### ISSUE TITLE
Multiple gridmaps in same scene cause issues with mesh selection

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot#64126]
### Godot version

3.5.rc7

### System information

Windows 10

### Issue description

If using multiple gridmaps in the same scene and switching between them, the editor will try to pick the MeshLibrary item from the previously selected gridmap's meshlibrary and choose it in the newly selected gridmap. If it doesn't have the mesh item, it will display an error:
```
scene/gui/item_list.cpp:237 - Index p_idx = 1 is out of bounds (items.size() = 1).
Requested for nonexistent MeshLibrary item '4'.
```
It will also no longer allow you to select a new mesh item from the meshlibrary until you go back to the previous gridmap and select an item number the other gridmap has.

The chosen item should be separated between each gridmap, so switching between them keeps the item chosen last independently.

### Steps to reproduce

1. Add two gridmaps to a scene
2. Have them both use separate MeshLibraries of different sizes
3. Pick an item from one gridmap meshlibrary for painting with and switch to the other gridmap
4. Godot will attempt to select the previously chosen item from the other gridmap in the newly chosen gridmap, and won't allow you to pick the correct item.

**Comment by rburing** [comment]
The problem seems to be here:

https://github.com/godotengine/godot/blob/c2eaaef1497f8ad557aea9a14e2b3e0582fcfe54/modules/gridmap/editor/grid_map_editor_plugin.cpp#L898-L900

Note the upper bound is not checked before selecting.

It would be better UX to store one index per `MeshLibrary`, but where should the indices be saved?

cc @YeldhamDev

**Comment by YeldhamDev** [comment]
> It will also no longer allow you to select a new mesh item from the meshlibrary until you go back to the previous gridmap and select an item number the other gridmap has.

I can't reproduce that part. Both master and the latest stable still allow to select another item.

> It would be better UX to store one index per MeshLibrary, but where should the indices be saved?

I think for now it should just check the upper bound and select that instead, as memorizing the index is more of a feature than a bug.

**Comment by elvisish** [comment]
> > It will also no longer allow you to select a new mesh item from the meshlibrary until you go back to the previous gridmap and select an item number the other gridmap has.
> 
> I can't reproduce that part. Both master and the latest stable still allow to select another item.

Try playing around for a while, it seems to happen randomly. I have to restart Godot when it happens, or else I have to pick the corresponding lowest possible index in the other gridmap's meshlibrary.
