### ISSUE TITLE
android export : apk not signed

### ISSUE THREAD

**Issue by 2439905184** [godotengine/godot#64143]
### Godot version

3.4.4-stable

### System information

Windows10

### Issue description

when use stable-template apk to export debug apk, apk is not singed
I have setup android sdk and openjdk11.
and tried write debug.keystore in export panel
look this  
![image](https://user-images.githubusercontent.com/29478722/183585131-ca7e7801-9f4c-409d-8987-6189893e0269.png)

### Steps to reproduce

when use stable-template apk to export debug apk, apk is not singed
I have setup android sdk and openjdk11.
and tried write debug.keystore in export panel

### Minimal reproduction project

[export-3.4.4-android-bug.zip](https://github.com/godotengine/godot/files/9287834/export-3.4.4-android-bug.zip)

**Comment by werryxgames** [comment]
Go to apksigner.bat in SDK and append to start of file this:
```
@echo %* >> C:\Users\<your user>\apksigner_run.txt
```
Export again
Write in console
```
type C:\Users\<your user>\apksigner_run.txt
```
Write in console
```
cd "<path_to_apksigner_dir>"
apksigner <result of previous command>
```
Then write here results of commands

**Comment by 2439905184** [comment]
I have modfiy the apksigner.bat , But I can't find apksigner_run.txt
![image](https://user-images.githubusercontent.com/29478722/185031914-1b19b468-78f2-4bb8-8c23-1f18d4d16c27.png)
![image](https://user-images.githubusercontent.com/29478722/185031930-97c441cc-9b71-4f95-b6d8-8eb91aa47b9d.png)
![image](https://user-images.githubusercontent.com/29478722/185031952-75050d85-eab8-4888-9b20-5b0d73c63148.png)

**Comment by 2439905184** [comment]
maybe apksigner.bat is not been called?

**Comment by 2439905184** [comment]
if I use apksigner.bat outside godot.
This apk is signed.
![image](https://user-images.githubusercontent.com/29478722/185035467-068fecd2-8c42-40e0-bccc-89fa75763216.png)
```bat
F:
cd sdk\build-tools\30.0.3
apksigner.bat sign --ks E:\debug.keystore --ks-key-alias androiddebugkey --ks-pass pass:android D:\Desktop\work\export-3.4.4-android-bug\debug.apk
pause
```

**Comment by werryxgames** [comment]
If you can't find D:\apksigner_run.txt and apk signed when command runned in cmd, specify correct SDK path in Godot settings. Godot didn't call modified apksigner.bat, THIS should be problem. Did D:\apksigner_run.txt appeared after cmd run?

**Comment by 2439905184** [comment]
![image](https://user-images.githubusercontent.com/29478722/185773591-b35462e6-27e1-4b6b-a536-89a3b953e0b7.png)
![image](https://user-images.githubusercontent.com/29478722/185773596-51c510f7-f712-4011-a46e-5e78eb074fd4.png)
I think it is right

**Comment by werryxgames** [comment]
Did D:\apksigner_run.txt appear after cmd run and do you use debug.keystore (didn't rewrite in project export settings)?

Last question. Have you another version of build-tools (except 30.0.3)?

**Comment by 2439905184** [comment]
> If you can't find D:\apksigner_run.txt and apk signed when command runned in cmd, specify correct SDK path in Godot settings. Godot didn't call modified apksigner.bat, THIS should be problem. Did D:\apksigner_run.txt appear after cmd run?

Hi I found the apksigner_run.txt
But I think it is written when I use cmd to call it 
[apksigner_run.txt](https://github.com/godotengine/godot/files/9390445/apksigner_run.txt)

**Comment by 2439905184** [comment]
> Did D:\apksigner_run.txt appear after cmd run and do you use debug.keystore (didn't rewrite in project export settings)?
> 
> Last question. Have you another version of build-tools (except 30.0.3)?

Yes I have some different build-tools.
![image](https://user-images.githubusercontent.com/29478722/185821038-ccb670a7-dc2c-4857-a908-0f9d9653e3c6.png)

**Comment by werryxgames** [comment]
Move all versions, except 30.0.3 to other directory or delete, before exporting in Godot.

If you need to use this versions for another application, generate new SDK and leave this for Godot (with 1 version of build-tools - 30.0.3)

**Comment by 2439905184** [comment]
thanks .

**Comment by 2439905184** [comment]
I remember old verisons of godot can call apksinger , and I put build-tools (different version) together .

**Comment by werryxgames** [comment]
If it works, please close this issue
