### ISSUE TITLE
V Align Top does not work for label

### ISSUE THREAD

**Issue by DarkiStar** [godotengine/godot#64141]
### Godot version

3.5 stable

### System information

Windows 10

### Issue description

I put a Label and a RichTextLabel into a HBoxContainer and set the RichTextLabel to Min_Size (300,300).
The normal Label has the attribute "V Align Top" set but is shown as if it was set to Center.

![image](https://user-images.githubusercontent.com/23613040/183582208-2f22a93e-b7a1-486d-939c-f7606e6ecc3a.png)

### Steps to reproduce

see above

**Comment by Calinou** [comment]
This is expected. You need to increase the Label's min rect size (specifically, its height) for this to work.
