### ISSUE TITLE
Editor can get stuck when performing operations related to window-derived classes (DisplayServer regression)

### ISSUE THREAD

**Issue by Rindbee** [godotengine/godot#64159]
### Godot version

v4.0.alpha.custom_build [c2eaaef14]

### System information

Linux Mint 20.3

### Issue description

When using the editor for a while, it may get stuck (there's basically nothing to change when you realize the delay). The last thing highlighted tends to be an object of a window-derived class:
1. Progress bar when saving changes
2. Popup menu for menu button
3. Settings dialog

### Steps to reproduce

It has been going on for about a week, and the specific cause cannot be determined, nor can it be stably reproduced.

**Comment by KoBeWi** [comment]
@Rindbee Does this still happen?

**Comment by Rindbee** [comment]
The issue seems to have been fixed in rc3.

**Comment by Rindbee** [comment]
Not completely repaired.

![1](https://user-images.githubusercontent.com/30386067/220814566-482b4415-6fca-4adf-b947-d44eb8c7f127.png)

This time it was reproduced by constantly modifying the scene and then saving it. After repeating this operation many times, the * next to the scene name will not disappear with `ctrl+s` press. It comes up when I'm about to try to open the scene file in an external program.

It is reproduced in i3wm.
