### ISSUE TITLE
Custom Module not working in linux

### ISSUE THREAD

**Issue by RameshRavone** [godotengine/godot#6416]
Linux - Ubuntu 16.04

I just started with module development and followed the Tutorial on docs and created "Sumator::Sumator" which worked well and then I tried renaming the code with "Newmod::Newmod" now its not working.

 is there any restriction on naming the module.

**Comment by vnen** [comment]
Define what "not working" means. Does it give any error? Does it just do nothing?

Also, make sure you renamed all references. You might have missed something.

**Comment by RameshRavone** [comment]
Parser Error: Identifier not found: Newmod

and I used command

find modules/newmod/ -type f -exec sed -i -e 's/sumator/newmod/g' {} \; 
find modules/newmod/ -type f -exec sed -i -e 's/Sumator/Newmod/g' {} \; 

And I checked the code too

**Comment by RameshRavone** [comment]
God I hate these happens,, I pulled latest code from github and now it works.

Sorry guys,
