### ISSUE TITLE
Resource loaded in a tool script has variables equal to null

### ISSUE THREAD

**Issue by Skyofflad** [godotengine/godot#64162]
### Godot version

4.0 alpha 13

### System information

Kubuntu 20.04

### Issue description

When I load a resource file in a tool script, some of it's variables are equal to null.

In godot v3.4.4 it works fine.

The file:
```gdscript
extends Resource
class_name TestRes
@export var integer: int = 1
@export var string: String = 'a'
@export var vect: Vector2 = Vector2(1,1)
@export var node: Node = Node.new()
@export var arr: Array = ['a', 1]
@export var dict: Dictionary = {
	'a': 1,
	'b': 2
}
```
Script that loads the resource
```gdscript
@tool
extends Node
var res: Resource = preload("res://testRes.tres")
func _ready():
	print('int = ', res.integer)
	print('string = ', res.string)
	print('vector2 = ', res.vect)
	print('node = ', res.node)
	print('array = ', res.arr)
	print('dictionary = ', res.dict)
```
Output:
```
int = 1
string = a
vector2 = (1, 1)
node = null
array = null
dictionary = null
```

### Steps to reproduce

Mentioned above

### Minimal reproduction project

[ResourceVarsTest.zip](https://github.com/godotengine/godot/files/9291719/ResourceVarsTest.zip)

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/67653, which has more information about the issue at hand.
