### ISSUE TITLE
(4.0) Surface material overrides are not applied instantly anymore when switching meshes

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#64163]
### Godot version

4.0.alpha13

### System information

linux

### Issue description

https://user-images.githubusercontent.com/71937306/183679276-d3a59887-300b-470b-b8cd-c584a0a7f9e9.mp4

- Saving then reloading the scene works.
- This works as expected in 3.5 official: the new mesh uses the surface material override instantly.

### Steps to reproduce

As seen in the video:
 1. Create a MeshInstance with any mesh,
 2. add a surface material override to it,
 3. swap the mesh with a new one.

**Comment by nongvantinh** [comment]
Can I take this issue?

**Comment by Calinou** [comment]
> Can I take this issue?

Sure :slightly_smiling_face:

**Comment by mcsantiago** [comment]
I can verify this is also an issue for MacOS 4.0.alpha
