### ISSUE TITLE
Unexpected program termination or black screen when creating node in Android editor

### ISSUE THREAD

**Issue by werryxgames** [godotengine/godot#64166]
### Godot version

3.5.stable

### System information

Android 10, GLES2 project (GLES3 available), Redmi 9C

### Issue description

When trying to create node, Godot Editor unexpected terminates, or stopping (like infinite process in main thread). It should create new node

### Steps to reproduce

Create new project with GLES2
Create Control or Node2D
Change resolution in Editor settings to lesser (for example 200% > 75%)
Click "Save and restart"
Run Godot Editor again
Open previously created project from menu
Click on "+" (It will be blue, like pressed or focused, but nothing will work. If you, don't closing Godot Editor go to recent apps and open it again, you will see only black screen)

**Comment by Calinou** [comment]
> Change resolution in Editor settings to lesser (for example 200% > 75%)

Out of curiosity, why are you doing this? Everything will be unreadable on such a small screen.

**Comment by lawnjelly** [comment]
Could be worth mentioning if you are using a different language from Engish, as this could be something to do with font rendering, and English has likely been tested more. Does it also reproduce with English set to the language (presuming it wasn't from your other issue)?

**Comment by werryxgames** [comment]
@Calinou, 200% is default (#64165)
@lawnjelly, I tried to change language, but it don't changing (Editor->Settings->Editor's language). I changed it to en and clicked "Save and restart" (did it 3 times) and language don't changed (#64214)

**Comment by Calinou** [comment]
> I changed it to en, clicked "Save and restart" 

You need to exit the editor manually for the setting to be saved.

**Comment by werryxgames** [comment]
https://user-images.githubusercontent.com/103959882/183912187-29c5b869-9d2e-4ad9-9a74-5806efe20670.mp4

Sorry for low quality video. My system recorder records vertical video if started in vertical orientation and horizontal video is 2-3 times lower quality. In video english language, still crashes.

In video nothing was added after red arrow (no video editing)

**Comment by Calinou** [comment]
cc @m4gr3d

**Comment by m4gr3d** [comment]
@werryxgames This is a known issue that has been addressed by #64420.
