### ISSUE TITLE
Use a lower editor scale by default on 720p mobile displays

### ISSUE THREAD

**Issue by werryxgames** [godotengine/godot#64165]
### Godot version

3.5.stable

### System information

Android, GLES2, Xiaomi Redmi 9C 720x1600 269dpi

### Issue description

By default Godot's resolution is 200%, but there is no inspector with 200%. Can't edit any node's property. I can change resolution in settings, but I want default resolution to be usable

![Screenshot_2022-08-09-18-34-17-699_org godotengine editor v3](https://user-images.githubusercontent.com/103959882/183696165-ef1d40c4-08a8-4711-813d-0b456f76311b.jpg)
![Screenshot_2022-08-09-18-39-09-299_org godotengine editor v3](https://user-images.githubusercontent.com/103959882/183696895-7bb78f07-c155-4e43-b293-4575d456c663.jpg)

### Steps to reproduce

Download stable Godot Editor 3.5 APK from official releases on Redmi 9C
Install downloaded file
Create or open any project

**Comment by akien-mga** [comment]
I think small UI is fine, it should definitely fit the screen. If it's too small to be comfortably usable it's still better than seeing only a quarter of the UI :)

**Comment by m4gr3d** [comment]
> Android, GLES2, Xiaomi Redmi 9C 720x1600 269dpi

@werryxgames If your dpi is `269`, then you should be falling in the `DENSITY_HIGH` bucket and have your scale set automatically to `150%` based on the logic [here](https://github.com/godotengine/godot/blob/1806e414b81a960be12eaa4774f3ecaabcd414ad/platform/android/java/lib/src/org/godotengine/godot/GodotIO.java#L147).

Can you validate your dpi is correct, and that you haven't overwritten the default scale selected for your dpi.

**Comment by werryxgames** [comment]
![Screenshot_2022-08-15-07-39-58-309_com finalwire aida64](https://user-images.githubusercontent.com/103959882/184578052-7b5ec035-2e9d-4ce8-b118-2fcff5d34045.jpg)
![Screenshot_2022-08-15-07-46-03-452_org godotengine editor v3](https://user-images.githubusercontent.com/103959882/184578329-5c17bc7a-6c2b-4f9b-8007-65ba6ab044bb.jpg)

**Comment by m4gr3d** [comment]
@werryxgames Does the editor fully fit with the `150%` or below scaling?

**Comment by werryxgames** [comment]
150%
![Screenshot_2022-08-15-10-43-41-714_org.godotengine.editor.v3.jpg](https://user-images.githubusercontent.com/103959882/184596005-402a6bdb-dbe5-456f-abab-0a27a985fa37.jpg)

**Comment by werryxgames** [comment]
125% is the best
![Screenshot_2022-08-15-10-47-55-541_org.godotengine.editor.v3.jpg](https://user-images.githubusercontent.com/103959882/184596616-6c814ee5-db96-40e6-b810-08cc951da4f6.jpg)

**Comment by werryxgames** [comment]
But for example you can add "Show Inspector" button (or with icon), that will show fullscreen inspector. Button will only show, when there is no visible inspector, or it don't show fully (like 150% screenshot)

**Comment by Zireael07** [comment]
Actually this is a good idea also for those people on desktops who want more space for the rest of the editor...

**Comment by Calinou** [comment]
> But for example you can add "Show Inspector" button (or with icon), that will show fullscreen inspector. Button will only show, when there is no visible inspector, or it don't show fully (like 150% screenshot)

See https://github.com/godotengine/godot-proposals/issues/1441.

**Comment by FransiskusFeroz** [comment]
idk if i could do java i would make godot for android a seperate version

**Comment by m4gr3d** [comment]
Fixed by https://github.com/godotengine/godot/pull/71838
