### ISSUE TITLE
Backside of a Label3D isn't affected by light when shaded is toggled on.

### ISSUE THREAD

**Issue by lesleyrs** [godotengine/godot#64174]
### Godot version

3.5

### System information

Windows 10, GLES2, Intel HD Graphics 620

### Issue description

Title, it does work correctly in GLES3 though.

https://i.imgur.com/TdDMD85.png

### Steps to reproduce

Label3d, shaded, add a light and check the back.

**Comment by Calinou** [comment]
Unlike GLES3, GLES2 does not have a way to detect whether a face is front-facing or not in a shader. This is likely why shading of double-shaded faces behaves differently.

**Comment by return2monki** [comment]
Your solution works perfect! Didn't realize negative scale would flip it, you can close this whenever. 👍
