### ISSUE TITLE
Physics sometimes broken? (Don't know what to name this)

### ISSUE THREAD

**Issue by SeanRamey** [godotengine/godot#64179]
### Godot version

3.5.stable.arch_linux

### System information

Operating System: EndeavourOS KDE Plasma Version: 5.25.4 KDE Frameworks Version: 5.96.0 Qt Version: 5.15.5 Kernel Version: 5.18.16-arch1-1 (64-bit) Graphics Platform: X11 Processors: 6 × Intel® Core™ i5-8400 CPU @ 2.80GHz Memory: 15.6 GiB of RAM Graphics Processor: NVIDIA GeForce GTX 1070/PCIe/SSE2 Manufacturer: Gigabyte Technology Co., Ltd. Product Name: Z370 AORUS Gaming WIFI

### Issue description

I have created 2 projects.

In the first (and original) project, when the character falls to the floor and collides, it slows the game down to around 1 frame every 4 seconds. In the second project, in which I've tried to recreate the first one, it simply works as expected and doesn't slow the game down to a crawl. I cannot find any significant differences between these two projects, so I'm reporting this as a bug.

### Steps to reproduce

I don't really know. Just open my test projects and hit play.

Video of the broken physics in project1:
https://user-images.githubusercontent.com/3057229/183747908-3b5cab6c-b564-4e85-bf05-801770161e83.mp4

Video of the working physics in project2:
https://user-images.githubusercontent.com/3057229/183748006-38213079-0029-40e4-8c17-1d35f95c8f00.mp4

### Minimal reproduction project

[First project with original issue: pikmin.zip](https://github.com/godotengine/godot/files/9294107/pikmin.zip)
[Second project that doesn't have the issue: pikmin2.zip](https://github.com/godotengine/godot/files/9294110/pikmin2.zip)

**Comment by Calinou** [comment]
Both projects seem to have the same amount of polygons in their convex collision shapes (4 for the floor, 1154 for the character).

However, as you can see, 1154 vertices is way too much for a player. See https://github.com/godotengine/godot/issues/48587.
