### ISSUE TITLE
Implement physics interpolation in 2D (already implemented in 3.x)

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#64182]
### Godot version

v3.5.stable.official [991bb6ac7]

### System information

Mac OS X (Catalina) 10.15.7

### Issue description

Have a very simple parallax background and a moving RigidBody2D. It jitters every few seconds scrolling. I am just using add_force() once to get it going.

### Steps to reproduce

1. Create a new scene with Node2D. 
2. Add ParallaxBackground and ParallaxLayer Texture background
3. Set the mirror to same size as Texture
4. Add a RigidBody2D with a Sprite, Camera and Collision2D
5. Check Camera2D as current
6. Add a force of 25 to Rigidbody2D
7. Run the project.
8. 

Notice that every few seconds the Spite snaps/jitters.

### Minimal reproduction project

Open and click run. Watch every few (maybe 10) seconds it bounces.

[ParallaxTest.zip](https://github.com/godotengine/godot/files/9294200/ParallaxTest.zip)

**Comment by lawnjelly** [comment]
Physics interpolation is not yet implemented for 2D.

**Comment by Zireael07** [comment]
Drive by comment: I'm not certain physics interpolation is implemented in 4.0 at all (whether for 3D or 2D). Could this be clarified in docs?
