### ISSUE TITLE
Anisotropic texture filtering does not work in Godot 4.0

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot#64187]
### Godot version

4.0.alpha13

### System information

Windows 10, Core i7 5820k, GeForce 980TI

### Issue description

Anisotropic filtering does not appear to work in Godot 4.0. Setting it to disabled and 16x results in an identical image.

![image](https://user-images.githubusercontent.com/4955051/183762888-79a8b6f4-1649-48fa-97b7-80a806c6170a.png)

By comparison, it works fine in 3.5. Left side of the image below has anisotropic disabled, right side has it enabled x16 and you can clearly see the sharper textures on the right.

![image](https://user-images.githubusercontent.com/4955051/183763356-e40ac731-e9b9-40ba-a3ed-9869dd9b8ca8.png)

### Steps to reproduce

Open the attached project.

### Minimal reproduction project

[anisotropic_test.zip](https://github.com/godotengine/godot/files/9294712/anisotropic_test.zip)

**Comment by Calinou** [comment]
You need to set the sampling mode to Linear Mipmap Anisotropic in the StandardMaterial3D.

**Comment by Arnklit** [comment]
Ah grand, sorry for the noise, did not find this when I looked for it. I gotta say I didn't think there was any chance this was a setting on  the material now ':-). Yeah enabling it by default would be lovely.
