### ISSUE TITLE
Navigation2D.get_simple_path no longer seems to yield a path to the desired point in Godot 3.5

### ISSUE THREAD

**Issue by jrdoughty** [godotengine/godot#64197]
### Godot version

3.5-beta1

### System information

Windows-11, GLES2

### Issue description

My RTS project yields fine paths using Navigation2D's get_simple_path in 3.4. However, the same project in 3.5 gets paths that are incorrect in that they don't navigate the terrain, and don't reach my end point.

### Steps to reproduce

replication steps, click/drag over the unit, then right click a place several tiles away. In 3.4, the unit will work its way to the target. In 3.5 it will often move a little ways, but then stop. You'll also see I'm printing the click position and the last path's position, and they are not the same Vector2D cord.

### Minimal reproduction project

My repo: https://github.com/jrdoughty/godot-rts
[RTS.zip](https://github.com/godotengine/godot/files/9296004/RTS.zip)

**Comment by smix8** [comment]
You need to fix your TileSet navigation polygon when you import from Godot 3.4. The TileMaps in versions < 3.5 stored the navpolygons in a broken format (with square navpolygon cells you didn't notice it too much). If you load an older saved TileMap resource with baked navigation tiles in Godot 3.5 it is very certainly unusable data.

If fixed the returned path by the navigation system is not the issue, a debug line shows that it is working correctly.

![navcollisionbug](https://user-images.githubusercontent.com/52464204/183847958-f6912852-ca04-4a0e-9b8b-b73df72540c7.png)

There are issues in that project related to your KinematicBody and Collision use that you need to solve. Since the navpolygon was broken I did not see your old layout but you need to have enough margin between the navpolygon and the collision ore else your units will get stuck around corners by collision. The navigation polygon needs to define the areas where the center point of you unit can move, it does not account for your collision size.

**Comment by jrdoughty** [comment]
Thanks I'll play with this after work and see how it comes out! Was this issue mentioned in any of the release notes? Very possible I overlooked it

**Comment by smix8** [comment]
@jrdoughty Not specifically, more a generalized statement that compatibility was kept within reason because the entire navigation system was changed the actual navigation changelog was so long that only 3 summarized points with a link to all the pullrequests were included.

**Comment by jrdoughty** [comment]
Ah, thanks, that statement makes more sense now. I'm having issues, but it's possible its an issue between the chair and keyboard. I tried blowing away my map and tileset and starting them from scratch. I'm able to get them back to where they were, but not better. To be clear in case I'm a moron who missed a step, I created the tileset resource, added the texture, created the grass region, went to the navigation and with grid snapping on and created a box over the grass tile. I may need to check out a tutorial to make sure I'm not missing a step. Going to continue to play with it a bit.

**Comment by jrdoughty** [comment]
Ok... I can't figure out what I'm doing wrong (I can be an idiot some times, so bear with me). I made a new project in 3.5 and ran into a couple issues:
- changing cell size didn't allow me to break up my tileset into smaller 8x8 tiles. I was stuck with 32x32 tiles no matter what I attempted to change in the TileMap.
- I went ahead and just used the 32x32 tiles and added a nav square over the tile. I turned on 'Visible Navigation' and can see it across the tilemap
- I then used the get_simple_path and fed it two cords (0,0 and 54,80) and set a Line2D's points to be the path. It didn't show
- I then loaded up the project in 3.4 and as was the case before, it works as expected.

I can imagine the nav mesh is still the issue, but I don't see where I should have been able to fix it?

[RTSRedux.zip](https://github.com/godotengine/godot/files/9313197/RTSRedux.zip)

**Comment by smix8** [comment]
You need to enable "bake_navigation=true" on the TileMap or it will not create navigation regions from the baked tile navpolygons.
Note that you cannot call a navigation path immediately in the _ready() function as the NavigationServer requires a physics_frame to sync the added tile regions.

**Comment by jrdoughty** [comment]
Where can I set that? I don't see it in the editor under TileMap or TileSet. I tried setting it in a script's ready function for the TileMap and didn't have any luck either as it said bake_navigation wasn't declared in the context. I opened the TileMap in the tscn file and added "bake_navigation=true" in case there was maybe just an editor issue, but when I hit play, it got scrubbed from the scene file.

**Comment by jrdoughty** [comment]
doing a search of the godot repo, it looks like thats a variable in gridmap? 

https://github.com/godotengine/godot/search?q=bake_navigation

**Comment by smix8** [comment]
@jrdoughty
In Godot 3.5 it is under TileMap -> Navigation -> Bake Navigation, in Godot 3.4 this property does not exist because navigation is static and cannot be toggled on / off.

**Comment by jrdoughty** [comment]
let me redownload godot 3.5 and see if something got goofed

**Comment by jrdoughty** [comment]
I was on Godot_v3.5 beta1

When I downloaded Godot_v3.5 stable I was good to go

**Comment by jrdoughty** [comment]
I updated the initial bug report to be accurate, sorry about that. I'm in business

**Comment by jrdoughty** [comment]
lesson learned, don't rename your executable
