### ISSUE TITLE
Asset Library Projects in Project Management Window leads unusually high %CPU

### ISSUE THREAD

**Issue by LiuJiLan** [godotengine/godot#64203]
### Godot version

v3.5.stable.official [991bb6ac7]

### System information

macOS 12.5 (21G72), 2.4 GHz 8Core Intel Core i9, Radeon Pro Vega 20 4 GB

### Issue description

# After selecting Asset Library Projects in the Project Management Window, the CPU usage will soar.

PS: `CPU usage` refers to the %CPU column of the CPU column of the Mac Activity Monitor

- When I launch Godot, in Project Manager Windows, selecting `Local Projects`, CPU usage is around 5.0%;
- When I open a  project, in editor's interface, CPU usage at first will be around 50%, then it will fall back to around5%; (Loading, I understand, it's normal)

# BUT
- When I launch Godot, in Project Manager Windows, selecting `Asset Library Projects`, CPU usage will rapidly increase to 400~500%;

**And then there will be two cases, depending on what to do next:**
1.  After selecting `Asset Library Projects` and then selecting `Local Project`s, the CPU usage will not drop back. It will remain at 400~500%;
2. After selecting `Asset Library Projects`, choose to enter the `editor's interface`, the CPU usage will fall back to the normal level;

### Steps to reproduce

First, launch Godot, in Project Manager Windows, selecting `Asset Library Projects`.
Then, wait for the cooling fan to start roaring.

**Comment by timothyqiu** [comment]
Probably a duplicate of #51530.

Please try the workaround mentioned in that issue (or try disabling `asset_library/use_threads` in Editor Settings).

**Comment by LiuJiLan** [comment]
Disabling `asset_library/use_threads` works. Thanks so much.
