### ISSUE TITLE
Improve error message when trying to use `class_name` in built-in script

### ISSUE THREAD

**Issue by Demozo** [godotengine/godot#64213]
### Godot version

4.0-alpha13

### System information

Windows 11

### Issue description

Given this class:

```
class_name Data

var someVariable: int
```

In a built-in script:
```
extends Node

func _ready():
    var data = Data.new() # Invalid call.
```
However, this works:
```
extends Node

var Data = preload("res://Scripts/Data.gd")

func _ready():
    var data = Data.new()
```

### Steps to reproduce

Outlined above.

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot/issues/25579.

It's probably not possible to support built-in scripts with `class_name`, but we should improve the error message when attempting to do so.

**Comment by Calinou** [comment]
> I don't see a reference to built-in scripts in the issue? It refers to a `Data.gd`.

Second paragraph of the issue description says:

> In a built-in script:

**Comment by KoBeWi** [comment]
This is a bug, see #51538 (includes a workaround)
