### ISSUE TITLE
Change font in theme

### ISSUE THREAD

**Issue by werryxgames** [godotengine/godot#64216]
### Godot version

3.5.stable

### System information

Windows 11

### Issue description

Can't change font in theme for TextEdit (don't tested other nodes).

When I click on font, it expanded in 3.4.x.stable, but now it don't. Also don't appear in inspector.

It can be solved if save font from earlier version of Godot to file (.tres) and set it

### Steps to reproduce

1. Use already created theme from earlier version of Godot (don't tested creating new)
2. Add TextEdit with data from menu
3. Clear selection from menu
4. Exit menu
5. Go to "Font" tab in appeared TextEdit
6. Create new DynamicFont in "font" field
7. Click on it

**Comment by Calinou** [comment]
I believe there were theming changes done between 3.4 and 3.5.

Either way, here's a 3.5 project with a custom TextEdit font: [test_font.zip](https://github.com/godotengine/godot/files/9300305/test_font.zip)

**Comment by AnidemDex** [comment]
Can't replicate v3.5.stable.official [991bb6ac7]

https://user-images.githubusercontent.com/7025991/184066826-7309884d-caa5-4f99-8096-4c3b4b33913a.mp4

**Comment by werryxgames** [comment]
Sorry, used unofficial version. Works in 3.5
