### ISSUE TITLE
Unable to change language

### ISSUE THREAD

**Issue by werryxgames** [godotengine/godot#64214]
### Godot version

3.5.stable

### System information

Android 10, Xiaomi Redmi 9C

### Issue description

Unable to change editor's language (from ru to en)

### Steps to reproduce

Create any project
Go to editor settings
Try to change language in Interface>Editor>Editor's language (can't change language to write correct names)
Click "Save and Restart"
Open Godot Editor on phone again to see, that nothing changed (in settings language still ru)

**Comment by akien-mga** [comment]
Thanks for the report!

That's the same issue as #60353 I believe.
