### ISSUE TITLE
Godot 4.0.alpha13.offical Navigation2d: NavigationAgent2d does not avoid Obstacles2d

### ISSUE THREAD

**Issue by Keryx42** [godotengine/godot#64220]
### Godot version

4.0.alpha13.offical

### System information

macOs Big Sur, M1, Vulkan

### Issue description

# Expectation
The agent should avoid the Obstacle2d nodes.

# Current Behaviour
The agent get's stuck in the wall

<img width="504" alt="image" src="https://user-images.githubusercontent.com/22496462/183913619-9b0924f7-1930-4b6d-b712-a8b7b9aefd89.png">

I also thought it's kinda strange that you can not assign an Obstacle to a specific navigation layer

# Other

This is my first bug report. It may be that I use the system completely wrong.  But I talked to some oder Users with similar problems. We all came to the conclusion that the behaviour is odd.

Thanks for creating this beautiful engine. Feel free to ask any questions :)

### Steps to reproduce

I created an example Repository for directly showing the problem with minimal effort. Just open the project and hit play :)

https://github.com/Keryx42/GodotNavigation2d

If you wan't to recreate the problem by yourself. I did the following:
- Create a tilemap
- Make one tile completly navigatable
- Create an area while only using that navigatable tile
- Create an CharacterBody2d with an NavigationAgent2D
- Let the Navigationagent travel to a position2d of your choice
- Put some RidgitDynamicBody2d Nodes with Obstacle2d Node in the way the to block the direct path
- The Character will get stuck on the RidgitDynamicBody2d

### Minimal reproduction project

Same code as in the linked Repository  https://github.com/Keryx42/GodotNavigation2d

[Navigation2d.zip](https://github.com/godotengine/godot/files/9300475/Navigation2d.zip)

**Comment by Calinou** [comment]
Try enabling visible navigation to debug the effective shape and path taken.

**Comment by smix8** [comment]
Your navigation path goes right through the obstacles as every tile below has a navigationmesh and you are using avoidance obstacles while not moving your actor with the avoidance `safe_velocity` from the NavigationAgent.

You need to commit you calculated velocity to the NavigationServer with NavigationAgent2D.set_velocity() and connected to the  `velocity_computed` signal for the avoidance callback. When you receive the `safe_velocity` with the signal move your actor with this velocity and not with you calculted, unsafe one.

Apart from that obstacles are intended as a last resort option for constantly moving objects that cannot be (re)baked to a navigation mesh efficiently so you shouldn't use obstacles for such a static wall setup. Instead replace the wall tiles with tiles that have no navigationmesh and your actor will move around them with just regular pathfinding while "avoiding" the overhead and problems of avoidance calculations altogether.

**Comment by Keryx42** [comment]
# About the solution
Thanks so for for the help :)
The approach using the velocity_computed signal worked out fine.
So the Obstacles2d  + avoiding  functionality is behaving correctly

# About the use of obstacles
I also read that obstacles are the last resort. In my game I plan on let the player place buildings.
So I need a ground tilemap layer which is 100% navigationmesh covered.
Using a second Layer for placing a building does not seem to work with the navigation. The building has no navigation mesh, only a collision. But as the ground still has a navigation mesh it results in the character  getting stuck in the building.
So maybe I also make a big mistake here ^^°

<img width="1370" alt="Tilemap" src="https://user-images.githubusercontent.com/22496462/184030663-72c43ccb-a8a4-4189-86ea-0f35bfd585e0.png">

# For future readers with similar problems
I keep the main branch in my example as it was when I reported my problem
https://github.com/Keryx42/GodotNavigation2d/tree/main

I also added a second branch with the working solution based on @smix8 explanation
https://github.com/Keryx42/GodotNavigation2d/tree/feature/avoid-obstacles

**Comment by smix8** [comment]
> Using a second Layer for placing a building does not seem to work with the navigation.

Layers alone are not the issue but you cannot stack multiple navigation regions on top of each other or the NavigationServer can no longer merge them together.

> So I need a ground tilemap layer which is 100% navigationmesh covered.

If you cannot update your Tiles for whatever reason I would use the TileSet as a pure backdrop and move the navigation to a NavigationPolygonInstance. You can use the Geometry2D class to merge or intersect sections inside the navpolygon for every building or other static object you want to place and this will reflect in the navigationmesh immediately without relying on the avoidance. Using obstacle avoidance for many buildings in close proximity will only get your actors behave unpredictable or get them stuck.

**Comment by McSora** [comment]
I got some - maybe stupid (sorry in advance 😅) questions on that matter...

1)
@smix8 
> *If you cannot update your Tiles for whatever reason*

I'm not exactly sure of what approach you were thinking about. Let's forget the boxes in the sample for a moment. Imagine a Tree that would barely cover half of a tile, so you'd still see the underlying tile. By "*updating your Tiles*" would you recommend accessing the TileMap node and replacing the tile that has navigation data with an identically looking tile without navigation data? Because this would mean holding each walkable tile as duplicate in the tileset (and i'd find that a pretty messy aproach 😅..) Or would there be a viable way to access one specific tile's instance of navigationpolygon and simple delete that one so that the navigationserver would miss that tile afterwards? 🤔 

2)
Are the TileMap tiles' navigation areas somehow *merged* behind the scenes? Like would there be one single navigation polygon tracked by the NavigationServer2D for example that one could manipulate? Like I'd make a TileMap, have tiles with navigationdata and build a walkable layer with these tiles. Now enter the box (from the sample project). Would it be possible to simply access that mentioned "global" Navpolygon and "cut out" the shape the box would use? 🤔

**Comment by Zireael07** [comment]
@McSora Likely yes, there is one asset in the assetlib that cuts out shapes in NavMesh (the 3D version) by using AABB.

**Comment by smix8** [comment]
TileMaps with baked tile navpoly have the inherited issue that you need to switch tiles if you want to modify the navigation as navigation regions cannot overlap. That is why I recommend to use TileMaps only as a texture backdrop for games that need dynamic navigation that changes a lot at runtime or have natural shapes that do not follow the tile layout. The TileMap with baked navigation creates a navigation region for each tile with a baked navpoly on the NavigationServer and those regions get merged by proximity / vertex. A NavigationPolygonInstance,navpoly can be edited easily and utility classes like Geometry2D exists as well to help with this.

**Comment by smix8** [comment]
@Keryx42 Is this issue solved?

**Comment by Keryx42** [comment]
Yes thanks so much.
I still have to figure out a good way a for a smooth movement when cutting out areas from the NavigationPolygonInstance. But this is not related to the obstacle avoidance.

**Comment by creadicted** [comment]
> Yes thanks so much. I still have to figure out a good way a for a smooth movement when cutting out areas from the NavigationPolygonInstance. But this is not related to the obstacle avoidance.

Hey @Keryx42 
Have you managed to "cut" a fully enclosed collision poly from a navmesh?

**Comment by wayrboy** [comment]
> Your navigation path goes right through the obstacles as every tile below has a navigationmesh and you are using avoidance obstacles while not moving your actor with the avoidance `safe_velocity` from the NavigationAgent.
> 
> You need to commit your calculated velocity to the NavigationServer with NavigationAgent2D.set_velocity() and connect to the `velocity_computed` signal for the avoidance callback. When you receive the `safe_velocity` with the signal move your actor with this velocity and not with you calculted, unsafe one.
> 
> Apart from that obstacles are intended as a last resort option for constantly moving objects that cannot be (re)baked to a navigation mesh efficiently so you shouldn't use obstacles for such a static wall setup. Instead replace the wall tiles with tiles that have no navigationmesh and your actor will move around them with just regular pathfinding while "avoiding" the overhead and problems of avoidance calculations altogether.

Hi, I am trying to delete a piece of the navigation area with Geometry2D, I tried intersect_polygons(), but I don't know why no effect, empty array returned
