### ISSUE TITLE
 In shaders, group_uniforms break when too many uniforms (> 12) are used

### ISSUE THREAD

**Issue by ClemensOlivae** [godotengine/godot#64226]
### Godot version

Godot 4.0 alpha 13

### System information

Windows 10

### Issue description

Using group_uniforms in a shader with more than 12 uniforms will break the groups, making them unusable.

### Steps to reproduce

Use the attached projet, and uncomment the proper line in the shader

or

Create a new spatial shader and paste this code.

```glsl
shader_type spatial;

group_uniforms Group1;
uniform bool a;

group_uniforms Group2;
uniform bool b;

group_uniforms Group2.subgroup1;
uniform bool c;

group_uniforms Group2.subgroup2;
uniform bool d;
uniform bool e;
uniform bool f;
uniform bool g;
uniform bool h;
uniform bool i;
uniform bool j;
uniform bool k;
uniform bool m;



void fragment() {
	// Place fragment code here.
}

```
![group_uniforms](https://user-images.githubusercontent.com/64355481/183940336-689a7bf3-ddb2-48cb-a584-e479d91f84c3.png)

If you add an uniform in any of these groups or subgroups the groups will break. At least one will disappear.
For example, adding a uniform in subgroup1 will make subgroup2 disappear!

### Minimal reproduction project

[group_uniforms.zip](https://github.com/godotengine/godot/files/9301439/group_uniforms.zip)

**Comment by garychia** [comment]
It seems that this line of code breaks the hierarchical structure of the uniforms and commenting that out seems to solve the problem.
https://github.com/godotengine/godot/blob/159664bd93ea29ea32e8af3a2be119aa701dc9f0/scene/resources/material.cpp#L292

**Comment by Chaosus** [comment]
Cannot be reproduced in beta 1. Seems like its already fixed. Closed.
