### ISSUE TITLE
Lightmaps baked in GLES 3 appear as black in GLES2

### ISSUE THREAD

**Issue by atirut-w** [godotengine/godot#64244]
### Godot version

v3.5.stable.official [991bb6ac7]

### System information

Fedora Linux 36 (Workstation Edition), GTX 1660

### Issue description

Lightmaps baked in GLES 3 appears as black in GLES2. Changing settings such as disabling HDR does not fix the problem.

Interestingly, lightmaps baked in GLES 2 appears normally on GLES 3, although HDR lightmap looks darker than expected in GLES 2. This issue may also be related to #46442

GLES3:
![image](https://user-images.githubusercontent.com/25323231/184020272-5f6c9057-6900-41cc-be60-7e9e3f4b26fc.png)

GLES2:
![image](https://user-images.githubusercontent.com/25323231/184020368-f5308e19-ee38-41dc-a8a5-066a32f9a8b4.png)

### Steps to reproduce

1. Bake any scene in GLES 3
2. Save the changes, switch to GLES 2 and restart.
3. Objects with lightmap appear as black.

### Minimal reproduction project

[Lightmap Problems.zip](https://github.com/godotengine/godot/files/9304075/Lightmap.Problems.zip)

**Comment by Calinou** [comment]
This is expected. To bake lightmaps that work with both GLES3 and GLES2, you need to disable atlases before baking lightmaps in GLES3.
