### ISSUE TITLE
C# prints small numbers with scientific notation, which is inconsistent with GDScript

### ISSUE THREAD

**Issue by Bartusew** [godotengine/godot#64240]
### Godot version

3.5 stable mono 64-bit

### System information

Windows 10

### Issue description

Method of Raycast node ( 3D type of it,   I'm not tried out is this also happening in 2D :/ ) called "GetCollisionNormal()" in C# (or "get_collision_normal()" in GDscript) is giving weird results in C#

 The results in my case are like so:
 
![image](https://user-images.githubusercontent.com/103317718/184003122-53e0b70e-c235-464f-9070-2d99d3d9eacc.png)

 - ps sorry if I wrote something incorrectly I wish it's still readable and understandable

### Steps to reproduce

I setuped simple scene with 2 raycast nodes 
 - one with C# printing surface normal 
![image](https://user-images.githubusercontent.com/103317718/184004690-47aa0642-133f-49c8-8c69-549bbd5db077.png)
 - second one doing the same thing as first but with GDscript
![image](https://user-images.githubusercontent.com/103317718/184004775-b506fd75-4dfb-423a-be21-6296a7f0715a.png)
 
both are in the same spot

and also "static body" node with "CollisionShape" and "MeshInstance" as child nodes

![image](https://user-images.githubusercontent.com/103317718/184003940-c703343e-82ff-4c27-b144-717049482c2a.png)

### Minimal reproduction project

[Godot 64-bit mono version Raycast issue Scene.zip](https://github.com/godotengine/godot/files/9303595/Godot.64-bit.mono.version.Raycast.issue.Scene.zip)

**Comment by raulsntos** [comment]
This is because GDScript is only printing up to 6 decimal places and C# is using scientific notation because the value is very small, if you force C# to also print 6 decimal places you should see the same printing in the console:

```csharp
GD.Print($"C# normal: {GetCollisionNormal().ToString("N6")}");
```

**Comment by Bartusew** [comment]
Ok I understand that. I even do my own clanky way arout this by adding GDscript into raycast node and then parent node with C# script attached to it read that information. But just I said this is that much clanky... But even then C# is getting informations from Godot written in C++ is this means C++ also have other type of notation. If GDscript can have good results without any tricks then why C# users need to struggle with this. I'm just saying I can find and implement that solution but doing that every single time is just weird Godot should have this fixed. There will be users with solutions but just I said why people need to struggle with this every single time :/

**Comment by Zireael07** [comment]
It's not a matter of "good" or "bad" results, just a matter of notation used.

**Comment by Bartusew** [comment]
So I should check that issue as closed now? I don't know is this just my bad and do I should not sending this issue or Its good to know that something like this is happening and It need to be fixed?

**Comment by Calinou** [comment]
I'm not sure if overriding C#'s behavior here is something we should do. Any opinions?

**Comment by raulsntos** [comment]
We can't override the `ToString` method of C# BCL types such as `float`, we could change the `ToString` implementation of `Vector3` but then it would be inconsistent with the BCL types. I think most C# developers would expect the current behavior so I'd leave it as is.

**Comment by Calinou** [comment]
Closing per @raulsntos' comment.
