### ISSUE TITLE
KinematicBody2D can't move while it stack by another KinematicBody2D with zero velocity

### ISSUE THREAD

**Issue by kaluluosi** [godotengine/godot#64255]
### Godot version

3.5 stable

### System information

Win10, Core I7-9700,RTX2080

### Issue description

I want to clone the NES game Chip 'n Dale- Rescue Rangers.
Every thing is just fine. But there is some problem found.
![GIF](https://user-images.githubusercontent.com/1620585/184058899-b4af0e4e-e040-40c7-bdbd-99008fcab7ac.gif)

The KinematicBody2D on left， we call it K1，right we call it K2.

While K1 jump on K2 , it can move on top of K2.
While K1 is moving on top, K2 can move normally to.

But something bag is come while K1 just stand on top of K2 with zero velocity(just stop), then K2 can't move any way.

I thought while collision count is more than 2, the slide is not work correctly.

### Steps to reproduce

just look description.

**Comment by kaluluosi** [comment]
well，I think i have figure out.
The problem is is was appling gravity every _physic_process.

```gdscript
func _physics_process(delta:flaot):
        ...
        velocity.y += self.default_gravity*gravity_scale*delta
        velocity = character.move_and_slide(velocity,Vector2.UP)
        ...
```

and it stuck while other kinematicbody2d stack on top.

I make it only apply gravity while on floor.
```gdscript
func _physics_process(delta:flaot):
        ...
       if not is_on_floor():
            velocity.y += self.default_gravity*gravity_scale*delta
            velocity = character.move_and_slide(velocity,Vector2.UP)
        ...
```
and it works.

**Comment by Calinou** [comment]
Closing, as this is expected behavior when gravity is constantly applied (even when on floor).
