### ISSUE TITLE
Scene Unique Names are not accessible after serialization/deserialization

### ISSUE THREAD

**Issue by stuartfulton** [godotengine/godot#64251]
### Godot version

3.5

### System information

Windows 10

### Issue description

Nodes that are marked as having scene unique names are not accessible using get_node("%UniqueName") syntax if they are instantiated and rehydrated from serialized data, meaning that if a Godot user loads a saved game and expects to be able to target deserialized nodes using % syntax, they are not able to do so.

I would expect to be able to access a rehydrated node with the same name and unique_name_in_owner as the original, with the same get_node("%UniqueName") syntax.

### Steps to reproduce

I've attached a minimal project that reproduces the issue.

The project contains a moving sprite and a button that says Reload Unique Scene. Run the project and click the button. The button handler deletes the sprite, which is a scene marked as % unique in the editor and moved every frame with get_node("%UniqueScene"), it creates a new scene from the same resource, gives it the same name (after renaming the original,) sets unique_name_in_owner to true, adds it to the tree, attempts to access it with get_node("%UniqueScene") and fails, with some output logging and an error.

Thanks. :)

### Minimal reproduction project

[UniqueNameSerializationTest-main.zip](https://github.com/godotengine/godot/files/9305301/UniqueNameSerializationTest-main.zip)

**Comment by timothyqiu** [comment]
This is becasue "Scene Unique Name" is relative to its owner.

The newly instanced `new_scene` is the root of its own scene so it does not have any owner. Enabling `new_scene.unique_name_in_owner` won't have any effect until an owner is set.

The MRP will work if you add `new_scene.owner = self` after `add_child(new_scene)`.

**Comment by stuartfulton** [comment]
That makes perfect sense, thanks! :)
