### ISSUE TITLE
FSR in Godot 4 not implemented correctly.

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#64254]
### Godot version

4.0.dev 317ced8204d80367c445963fc989de320c6f9a68

### System information

Any

### Issue description

As I'm working on restructuring a lot of the render internals I discovered that FSR isn't working at all and that fixes we've done in the past actually disabled FSR all together and just resulted in rendering happening at full resolution.

When FSR is enabled we calculate two resolutions in `RendererViewport::_configure_3d_render_buffers`:
- the "internal_width/internal_height" which is the scaled down resolution at which we want to render.
- the "target_width/target_height" which is our output resolution (the size of our viewport).

In `RendererSceneRenderRD::render_buffers_configure` we now allocate our render buffers. 
- `rb->internal_texture` becomes our buffer at our scaled down resolution
- `rb->upscale_texture` becomes an intermediate buffer at our output resolution
- `rb->texture` becomes our final output buffer (or that is the intention here)

The idea here is that we render all our 3D using our `rb->internal_texture`, so all at a lower resolution, for performance reasons. This should be used all the way until the end. Our end can be found in `RendererSceneRenderRD::_render_buffers_post_process_and_tonemap`.

This is where things go wrong.
First off, the most important bit to understand is that nearly at the end we apply our tonemapping:
`tone_mapper->tonemapper(rb->internal_texture, texture_storage->render_target_get_rd_framebuffer(rb->render_target), tonemap);`

Note here that we are taking our `rb->internal_texture` as input, and then output to `texture_storage->render_target_get_rd_framebuffer(rb->render_target)` which is what ends up being displayed on screen. The tonemap shader automatically performs bilinear scaling if our internal texture is a lower resolution, all good.

In the next segment we do FSR: `RendererCompositorRD::singleton->get_effects()->fsr_upscale(rb->internal_texture, rb->upscale_texture, rb->texture, Size2i(rb->internal_width, rb->internal_height), Size2i(rb->width, rb->height), rb->fsr_sharpness);`

This takes our `rb->internal_texture` and upscales it writing the result into `rb->texture`. However `rb->texture` is never consumed, this output is lost.

There are two ways of fixing this:

1. Move FSR to before Tonemapping, and then have tonemapping read from `rb->texture` and output to our render buffer. The problem here is that Tonemapping also performs glow which uses our blur textures, which are at an incorrect resolution for this
2. Have tonemapping write out into an intermediate if FSR is enabled, and have FSR read from this intermediate and output to our render target (this is what I'm currently implementing as a fix).

### Steps to reproduce

Turn on FSR on any project.

**Comment by Je06jm** [comment]
AMD recommends doing FSR upscaling after applying the tonemap to the image

**Comment by BastiaanOlij** [comment]
@Je06jm thanks, that is how its implemented now. 

This should now work properly as #63901 was merged.
