### ISSUE TITLE
Interpolation of shearing Transform2D getting unintended results

### ISSUE THREAD

**Issue by bombzj** [godotengine/godot#64252]
### Godot version

3.5.stable, 4.0.dev

### System information

Windows 10 x64

### Issue description

with a Shearing Transform2D as follows
![image](https://user-images.githubusercontent.com/19320748/184053112-ed335bd9-962c-4fb0-86a0-54431d96e8ad.png)

After interpolation, it changes to ((1, 0), (-0, 1.414214), (0, 0))

code as follows
`var t = Transform2D()`
`t.y = Vector2.ONE`
`var result = t.interpolate_with(t, 0.5)`
`print(result)`

### Steps to reproduce

GDScript
extends Node2D

func _ready():
	var t = Transform2D()
	t.y = Vector2.ONE
	var result = t.interpolate_with(t, 0.5)
	print(result)

### Minimal reproduction project
[interp.zip](https://github.com/godotengine/godot/files/9305522/interp.zip)

**Comment by lawnjelly** [comment]
I'm not sure the existing `interpolate_with` code is meant to deal with shearing. It seems to decompose into origin, rotation (float), scale (Vector2) and interpolate these.

Dealing with interpolating complex bases is not trivial afaik, so I'm not surprised it doesn't attempt it.

(I resort to lerping in the physics interpolation, when such bases are detected. This is not "correct" but can work through small deltas to bases .. albeit with some warping. I don't know if there is a general solution for this problem that will work for large differences, would need a mathemagician.)

**Comment by bombzj** [comment]
Transform2D contains 3 Vector2 (origin, x, y) which is basically a 3x2 matrix, decompose it into origin, rotation, scale will lose a float in information. Maybe decomposing it into origin, rotation, shear/skew(y), scale will do better. May I have a try(PR) on this?

**Comment by lawnjelly** [comment]
> Transform2D contains 3 Vector2 (origin, x, y) which is basically a 3x2 matrix, decompose it into origin, rotation, scale will lose a float in information. Maybe decomposing it into origin, rotation, shear/skew(y), scale will do better. May I have a try(PR) on this?

Sure, feel free to have a go, you need no permission to try a PR! :grin:
