### ISSUE TITLE
RigidBody2D get_colliding_bodies() not reporting contacts

### ISSUE THREAD

**Issue by spookdogg** [godotengine/godot#6425]
**Operating system or device - Godot version:**
Windows 7 - 2.1

**Issue description** (what happened, and what was expected):

get_colliding bodies() does not seem to be reporting any contacts in RigidBody2D

**Steps to reproduce:**

every frame, test get_colliding_bodies(), set the rigidbody in a situation you know it will be colliding and observe results

**Link to minimal example project** (optional but very welcome):
(obviously based off of HeartBeast's Tutorial)
[Breakout.zip](https://github.com/godotengine/godot/files/460289/Breakout.zip)
(debugging info about the ball is printed to console)

**Comment by vnen** [comment]
This is not a bug, you need to increase the number of the "Contacts Reported" property. It is `0` by default, so it won't report anything.

**Comment by spookdogg** [comment]
ah.. sorry...
The tooltip is a little confusing however, from what it says I thought it only capped the number of contacts reported if the number was greater than 0
(kinda like visible characters with RichTextLabel)
