### ISSUE TITLE
TextureProgress node has -nan as default Initial Angle value, causes crash upon save

### ISSUE THREAD

**Issue by sketchyfun** [godotengine/godot#6426]
**Operating system or device - Godot version:**
Windows 7 - Stable 2.1 from website

**Issue description** (what happened, and what was expected):

When adding a TextureProgress node, the Initial Angle value under Radial Fill is "-nan" by default.

 If you try and save the scene without changing it, Godot crashes. Because of this I'm unable to create an example, but it's pretty straight forward to recreate.

A stranger version of this bug actually occurred in my main project, except it didn't cause Godot to crash. Instead it caused the player (Kinematic) to fall straight through the static body below it. As soon as I changed the Initial Angle value on the TextureProgress bar I was using to a valid value like 0 , the problem went away and collisions worked again.

**Steps to reproduce:**

Add a TextureProgress node to any scene, the default value in the Initial Angle box under Radial Fill will be "-nan". Saving at this point will crash Godot, or if you saved that part of the tree off as its own scene and instanced it, it does other weird stuff 

**Link to minimal example project** (optional but very welcome):

**Comment by sketchyfun** [comment]
It also just caused my player scene to lose all the signals the various nodes had set up, like area enter/exit, timer timeout etc, so it's definitely causing some pretty serious issues

**Comment by MarianoGnu** [comment]
Please test it since i can't reproduce the issue

**Comment by Sslaxx** [comment]
Sounds like #6384.
