### ISSUE TITLE
Collapse button looks blurry and not sharp enough

### ISSUE THREAD

**Issue by CodeLazier** [godotengine/godot#64264]
### Godot version

4.0 a13

### System information

4.0 Win10 Vulkan

### Issue description

![bl](https://user-images.githubusercontent.com/14953625/184084946-d371eff5-804b-48c4-bdb1-b33c2531be1f.png)

### Steps to reproduce

open editor

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/57331.
