### ISSUE TITLE
AnimationNodeTransition will not play animation if any one of the input node is empty (Not only playing node but also any other nodes)

### ISSUE THREAD

**Issue by hakuhan** [godotengine/godot#64278]
### Godot version

4.0.alpha15

### System information

Windows10

### Issue description

Transition node will not working if on of the node's animation is empty.
For instance at following picture shows. Actually locomotion's animation is ok. But animtion in control_anim is empty(It will be set in runtime) When I play games. Locomotion will not be able to play. because control_anim has empty anim.
![image](https://user-images.githubusercontent.com/18411187/184168473-6a5ad974-a423-427e-acff-d620f0a4e4f0.png)

### Steps to reproduce

1. Open any project.
2. Create animiation tree.
3. Create transition node.
4. Create two nodes to be the inputs.
5. Set animation at one node empty.
6. Transition cannot play event playing node has animation.

### Minimal reproduction project
[TransitionBugMinProject.zip](https://github.com/godotengine/godot/files/9482343/TransitionBugMinProject.zip)

_No response_

**Comment by TokageItLab** [comment]
I think it is a design issue. The cache for blending is not generated correctly, so any empty animation connections should not be allowed from the start.

**Comment by hakuhan** [comment]
When I set any animation for empty node. It will play currectlly. But when I delete animation in "control_anim" at runtime(play over then delete animation) "locomotion" will not working suddenly.

**Comment by hakuhan** [comment]
OneShot node has no such problem.

**Comment by TokageItLab** [comment]
Perhaps it is a StateMachine issue? @fire @SaracenOne

**Comment by hakuhan** [comment]
@fire  @SaracenOne It is the same in alpha15. I think it is a bug.

**Comment by TokageItLab** [comment]
@hakuhan Please send MRP.

**Comment by hakuhan** [comment]
> @hakuhan Please send MRP.

Got it. I will send it after work.

**Comment by hakuhan** [comment]
Hi! @TokageItLab  I uploaded a MRP!

**Comment by TokageItLab** [comment]
I investigated. Between alpha 12 and 13, sync was implemented in NodeTransition, and the animation iteration process was changed to correctly handle sync.

Previously, unused branches in a transition would be completely passed through if there was no sync, but now they are iterated regardless of whether they are synced or not, so if an animation is not set at any point in the tree, an error will be generated.

This error may disappear after the optimization process commented in [A](https://github.com/godotengine/godot/issues/65199#issuecomment-1234406228), but in any case I can't say that this behavior is a bug. Animation should always be set as long as it is part of the tree.

**Comment by hakuhan** [comment]
> I investigated. Between alpha 12 and 13, sync was implemented in NodeTransition, and the animation iteration process was changed to correctly handle sync.
> 
> Previously, unused branches in a transition would be completely ignore that process if there was no sync, but now they are iterated regardless of whether they are synced or not, so if an animation is not set at any node in the tree, an error will be generated.
> 
> This error may disappear after the optimization process commented in [#65199 (comment)](https://github.com/godotengine/godot/issues/65199#issuecomment-1234406228), but in any case I can't say that this behavior is a bug. Animation should always be set as long as it is part of the tree.

Ok. Got it.

**Comment by TokageItLab** [comment]
@hakuhan  Can you check #68593? I still don't understand much about the problem you are encountering, but I would have to say that if that PR does not fix it, then the animation tree has a specification that must be set animation .

**Comment by hakuhan** [comment]
> @hakuhan Can you check #68593? I still don't understand much about the problem you are encountering, but I would have to say that if that PR does not fix it, then the animation tree has a specification that must be set animation.

Sorry for late reply. I set a default animation currently. I will check it when my busy project state is done.

**Comment by hakuhan** [comment]
Hi! @TokageItLab. From my test at 4.0 stable. This issue is gone. Thanks very much!
