### ISSUE TITLE
Text glitches when using a custom font and when Snap Control To Pixels and GPU Pixel Snap are turned off (and a temporary fix)

### ISSUE THREAD

**Issue by momcilo-2** [godotengine/godot#64294]
### Godot version

3.5.stable

### System information

Fedora 36, AMD RENOIR, GLES3

### Issue description

The characters in labels look weird (in my case, their tops look cut off). It seems to only affect labels which **have a custom font and whose anchors have been changed** (from the default top-left).

Turning Snap Control To Pixels or GPU Pixel Snap on fixes it, but they make animations which modify scale choppy.
Resizing the window sometimes makes it go away.

How to fix: Change the scale of the affected label from 1 to 1.001. _(Changing it to 1.01 almost fixes it.)_

### Steps to reproduce

1. Turn off the _Snap Control to Pixels_ and _GPU Pixel Snap_ options in _Project Settings_
2. Add a new label
3. Add a custom dynamic font to it and change its anchor

### Minimal reproduction project

_The zip file is in one of the replies below_

**Comment by Calinou** [comment]
@2150m Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by 2150m** [comment]
[textglitching.zip](https://github.com/godotengine/godot/files/9316721/textglitching.zip)

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
