### ISSUE TITLE
Selection in Editor Help is not accurate

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#64292]
### Godot version

67d4015

### System information

Windows 10 x64

### Issue description

![godot_nkBHH0s3oN](https://user-images.githubusercontent.com/2223172/184251959-c9420552-677e-46bb-88c5-ad8f44113e74.gif)
It's off by 1 character.

EDIT:
Actually it only happens in code blocks.

### Steps to reproduce

1. Open some help page
2. Try to select text in a code block

**Comment by Calinou** [comment]
Selection within tables likely has some issues. In `master`, code blocks are located within a table with 1 row and 1 column to add padding on the background (and make the background span the entire line).

**Comment by YuriSizov** [comment]
Is this still an issue? There have been some fixes to RTL and tables.

**Comment by KoBeWi** [comment]
Yes.
