### ISSUE TITLE
Any way to modify theme of group titles in the inspector ?

### ISSUE THREAD

**Issue by Geequlim** [godotengine/godot#6430]
**Operating system or device - Godot version:**

Godot 2.1

**Issue description** (what happened, and what was expected):

![2016-09-08 17-33-11](https://cloud.githubusercontent.com/assets/6964556/18344617/963385a4-75ea-11e6-956f-74786b65d037.png)

I don't know how to set the color or styletexture with the group titles in the inspector. 

The default color of the group titles may not fit for new custom themes.

**Comment by akien-mga** [comment]
This image from @Geequlim makes it pretty clear that this issue really needs to be fixed for proper editor theming :)

![](https://camo.githubusercontent.com/2dd9386ff8050cabcaaa39f70836e561ac817467/68747470733a2f2f63646e2e7261776769742e636f6d2f47656571756c696d2f6465706f742f6d61737465722f696d616765732f676f646f742f6172635f6c696768745f48694450492e706e67)

**Comment by Geequlim** [comment]
Colors in `Theme/Editor` section below  cannot be saved.
![qq20160909-0](https://cloud.githubusercontent.com/assets/6964556/18386981/70b4f92e-76cc-11e6-82f9-26b13153e5fc.png)

@reduz I think these color properties are designed for that, are they?

**Comment by rollenrolm** [comment]
I had the same issue some time ago and tried to solve it in #5892. The last iteration of that patch is a proper solution suggested by @reduz, and it works fine.

**Comment by akien-mga** [comment]
Merged. @Geequlim Can you confirm that it fixes the issue?

**Comment by Geequlim** [comment]
Yes it does fixed the issue, thanks @rollenrolm !
