### ISSUE TITLE
HTTPClient: support gzip http responses

### ISSUE THREAD

**Issue by cjthomp** [godotengine/godot#6433]
**Operating system or device - Godot version:**

OS X 10.11.6, godot v2.1

**Issue description** (what happened, and what was expected):

Some web APIs `gzip` all responses by default (no option to change or no control of the server) and I can't find a way in godot to `ungzip` it (which makes the response useless gibberish).

Is this something planned, or a possibility?

**Comment by vnen** [comment]
Godot already has zlib, so adding this should not be hard.

**Comment by punto-** [comment]
This would be good to have. As a workaround tho, you can send a header from
the client saying you only support certain types of content encoding you
support. Here's some reference:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding

We should be able to support gzip and deflate with the libraries we have.

**Comment by cjthomp** [comment]
In theory, but not every api is well-behaved

**Comment by opcon** [comment]
I think this issue can be closed for 3.0 with the merging of #9274 and #9634.

A gzipped (or other compressed) response from the server can now be handled as follows:

```gd
# rb is a PoolByteArray containing the server response
# headers is a dictionary containing response headers
if headers['Content-Encoding'] == 'gzip':
	rb = rb.decompress(rb.size()*10, File.COMPRESSION_GZIP)
```

The only issue is not knowing how big the uncompressed file size, which is needed for the decompress() function.

**Comment by akien-mga** [comment]
Could you add something about this to the documentation of PoolByteArray maybe?

**Comment by opcon** [comment]
@akien-mga not sure which part you want me to document, the handling of compressed server responses specifically? I'm happy to do that

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
@godotengine/network Still relevant in the master branch I guess?

**Comment by Faless** [comment]
@akien-mga yes, this could be documented using HTTPClient to make a well formed request, and GZIP/DEFLATE when reading back from the server for 3.1, and maybe we could implement auto-deflate in HTTPRequest in 3.2 via dedicated property.

**Comment by Wavesonics** [comment]
What is the status of this? auto-deflate/inflate would be a pretty nice feature.

`HttpClient` has a `request_raw` making it easy to send compressed data, but `HttpRequest` does not. That might also be a nice feature to add.

**Comment by Calinou** [comment]
@Wavesonics As far as I know, nobody has started working on this yet.

**Comment by Wavesonics** [comment]
@Calinou I'm going to take a crack at it and submit a PR, should I base it off of the 3.2 branch? or master?

**Comment by Calinou** [comment]
@Wavesonics Please base it off `master`, as it's where all pull requests should be made (unless they don't apply to `master` for some reason).

**Comment by Faless** [comment]
Closing via #38944 which implemented it in `HTTPRequest`.
