### ISSUE TITLE
Error "The end quaternion must be normalized" when AnimationTree is active if blended animations contain un-normalized rotation track

### ISSUE THREAD

**Issue by WuotanStudios** [godotengine/godot#64340]
### Godot version

4.0.alpha13

### System information

Windows 11 Pro, GLES3, Intel i7-8705G, AMD Radeon RX Vega M GL

### Issue description

I've animated the bones in the AnimationPlayer "Anim_Hand_ctrl".
In the AnimationTree "L_Hand_ctrl_Anim_Tree" i've made 2x BlendSpace1D and connected each other through Add2.

As soon as the AnimationTree is active the error "The end quaternion must be normalized" and keeps appearing with every new frame.

And after a few minutes the fps starts to drop.
It seems that this error has an affect on the processor/memory too.

Animated bones: 

hand.L
![image](https://user-images.githubusercontent.com/101058770/184444924-490ae62c-b99b-4a74-b028-538daa940a7e.png)

hand.R
![image](https://user-images.githubusercontent.com/101058770/184445014-80e4ba46-cd27-4f09-956d-c3025dca9add.png)

the error message in the output:
![image](https://user-images.githubusercontent.com/101058770/184445093-21cf730b-d53c-4fed-99a2-60a7b5fbd1a3.png)

The projectfile on github:
https://github.com/WuotanStudios/GodoDudeMannequin

### Steps to reproduce

Download the project from github:
https://github.com/WuotanStudios/GodoDudeMannequin

in the file "GodoDude Mannequin" open the project.godot file.

Select the AnimationTree "L_Hand_ctrl_Anim_Tree" and if not already activated, activate the AnimationTree
![image](https://user-images.githubusercontent.com/101058770/184445631-75dd244e-bd4d-4ea3-b18a-63264e966fd0.png)

### Minimal reproduction project

Download the project from github:
https://github.com/WuotanStudios/GodoDudeMannequin

**Comment by WuotanStudios** [comment]
it seems the add2 in the AnimationTree causes this error.
As soon as i decouple one of the two blend2 nodes, the error doesn't appear anymore.

see here in my tweet vid: 

https://twitter.com/WuotanStudios/status/1558201495115407360?s=20&t=Qv70kOoLOHPByel4CHZ-uA

**Comment by WuotanStudios** [comment]
No, the add2 isn't the problem.
If i connect the blendspace1D directly to the output, the same error keeps appearing

**Comment by WuotanStudios** [comment]
just tested in Godot 4 alpha.14
Same issue / error appears

**Comment by WuotanStudios** [comment]
just tested my older FPS Arm Rig/IK in Godot 4.alpha.14.
I also animated bones there and i also used the AnimationTree the same way.
But in this case the error does not appear.

i made a short video about that test:
https://twitter.com/WuotanStudios/status/1558378175037669377?s=20&t=7_pWm_lxO2ozYxbQZ1innA

**Comment by TokageItLab** [comment]
I investigated a linked your project, this problem is caused by the fact that some animations (`RESET` and `ledt_hand_normal_pose`) have un-normalized track (`hand.L`). @WuotanStudios Can you determine which process in the workflow caused it?

At least it is not a BlendTree's bug, but we can improve the UI somewhat, e.g., displaying non-normalized tracks in error message. I'll see if some improvements can be made as enhancement later.

**Comment by WuotanStudios** [comment]
> I investigated the linked your project, this problem is caused by the fact that some animations (`RESET` and `left_hand_normal_pose`) have un-normalized track (`hand.L`). @WuotanStudios Can you determine which process in the workflow caused it?
> 

Hello TokageltLab, i don't know what process caused this issue. 
I will redo the project (since i've learned how to use the Godot IK tools better), 
and will pay attention if this issue happens again.
