### ISSUE TITLE
C++ error on storing viewport node in variable

### ISSUE THREAD

**Issue by Lalafella** [godotengine/godot#64348]
### Godot version

3.5.stable

### System information

Window 10

### Issue description

When I store viewport node in a variable to use it later, it gave me a lot of [getornull: Condition "!id_map.has(p_rid.get_data())" is true. Returned: __null] which flooded my debugger stack. It is not gamebreaking but sure is pretty annoying one.

The fix is to do not store viewport node in variable and using get_node to call its function instead but it is not entirely fixed and can still happen sometimes.

### Steps to reproduce

I ran this code in my SceneChanger which is in autoload. 

func _ready():
	yield(get_tree() , "idle_frame")
	
	if get_tree().get_current_scene().has_node("map_viewport_container/map_viewport"):
		map_viewport = get_tree().get_current_scene().get_node("map_viewport_container/map_viewport")

	if map_viewport and map_viewport.get_children().size() > 0 :
		for map in map_viewport.get_children():
			if map.is_in_group("Map_Scene"):
				current_map_scene = map
				break
	battle_scene_container = get_tree().get_current_scene().get_node("battle_scene_container")
	
	
I remove map_viewport variable and replace them with get_tree().get_current_scene().get_node("map_viewport_container/map_viewport") instead and it is fixed but I still get the problem again sometimes.

**Comment by Calinou** [comment]
This is likely a dangling reference: https://github.com/godotengine/godot/issues/41360

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
