### ISSUE TITLE
Godot allowing adding files and folders with special characters (etc / \ : * " |)

### ISSUE THREAD

**Issue by MeBadDev** [godotengine/godot#64347]
### Godot version

v3.4.4 stable official

### System information

Windows 10, Git and Github Desktop

### Issue description

When creating a new file/scenes/scripts, Godot allows special characters which let your VCS to broke (you can't commit)

I expect it not allowing special characters in file name

### Steps to reproduce

1. Create a new godot project (or open an existed one)
2. Click "New Scenes" in the File System
3. Enter some special characters
4. Save It

**Comment by Calinou** [comment]
The editor should already prevent you from creating files with characters not allowed on Windows, [with a few exceptions](https://github.com/godotengine/godot/issues/38198).

Some of the characters you mentioned *are* legal to have in version control, but it's possible that the app you're using doesn't handle files with those character names well. This isn't something we can fix on our end.

**Comment by MeBadDev** [comment]
I've change the tile because I realized windows allow !@#$%
