### ISSUE TITLE
Visual scripting on Android causes flashing loading screen and no content.

### ISSUE THREAD

**Issue by samvila** [godotengine/godot#6435]
**Operating system or device - Godot version:**
Nightly build from http://www.purpleorangegames.com/godot/ (Date: 09/08/16). Windows 10 64 bit and Windows 7 64 bit.  Android device: Samsung Galaxy S4.

**Issue description** (what happened, and what was expected):
Using this nightly build I can generate a valid APK that works perfectly on my mobile phone but when using visual scripting it generates an APK that only shows the Godot loading screen and flashes all the time, doesn't display the project at all, it only shows the flashing loading screen.

**Steps to reproduce:**
Any visual script will cause this problem, same project without the visual script runs just fine.

**Link to minimal example project** (optional but very welcome):

**Comment by akien-mga** [comment]
Obligatory question: did you update your export templates to match the Godot version you're using?

**Comment by samvila** [comment]
Hi,

I'm using the export templates from 2.1, the link from my previous comment doesn't display any export template so I don't know how to access, if you provide these files I can give a try to see if the problem persists.

**Comment by volzhs** [comment]
@samvila you should use same version of editor and templates.
Try this one. http://fixnum.org/godot/

**Comment by akien-mga** [comment]
Yes, it's normal that it crashes as 2.1 templates don't know what Visual Script is.

**Comment by samvila** [comment]
I get this message when I try to download the export templates:

Gateway Anti-Virus Alert

This request is blocked by the Firewall Gateway Anti-Virus Service. Name: XPACK.A_2499 (Trojan)

I don't know if it's just me or something is wrong with that file. I will try to download this file from home later on an give it a try just to confirm or dismiss this issue.

Thanks.

**Comment by samvila** [comment]
OK, I tried that link but only has export templates for Linux, Windows and Mac so I cannot try the Android export. Do you guys have any other link with the right export template for Android?

**Comment by vnen** [comment]
@samvila this one has export templates with Android: https://archive.hugo.pro/godot/

**Comment by samvila** [comment]
The link from vnen totally works. You were correct, that was the problem. Sorry about the report. At least I did some testing for you. All seems to be working fine. The only thing I cannot find on these builds are the live editing like in this video: https://www.youtube.com/watch?v=50Vw4e6JPOI

**Comment by akien-mga** [comment]
Glad that it works :)

**Comment by vnen** [comment]
@samvila it's in the same place, but now called "Sync Scene Changes".
