### ISSUE TITLE
Visibility Enabler above Particle Emitter causes "Condition "!is_inside_tree() is true" Error

### ISSUE THREAD

**Issue by riazey** [godotengine/godot#64379]
### Godot version

4.0.alpha14

### System information

Windows10, Vulkan Clustered, GeForce GTX 1080

### Issue description

When adding a VisibleOnScreenEnabler2D and then a GPU Particles node ( I only tested it with this one) below causes an error.

![image](https://user-images.githubusercontent.com/75141902/184518297-03e02c1b-8eb7-44bd-a8d8-bc6d7feb150c.png)

### Steps to reproduce

Create the below node (processing material makes no difference) > Run > Reverse Profit.

![image](https://user-images.githubusercontent.com/75141902/184518496-28d9829e-6185-4d06-9805-ec55743f4025.png)

**Comment by Calinou** [comment]
I can't reproduce this on 4.0.alpha 29492f908 (Linux). Running the project doesn't print any message. Both GPUParticles2D nodes have a process material and texture set:

![image](https://user-images.githubusercontent.com/180032/184537521-ef13cde6-92e1-46f3-99c6-ecb9bc72b69d.png)

**Comment by tinmanjuggernaut** [comment]
I also cannot reproduce on Win11/64, RTX 3070, Vulkan, Alpha 14.

`! is_inside_tree()` means the node is not attached to the scene tree. But if you can see it in the inspector Scene tab, it is attached to the scene tree so it's an odd error to get in this case.

**Comment by riazey** [comment]
Tried this again just in case and it produced the same results on a fresh project with no other programs open right at startup.

@Calinou I downloaded your minimal project as well and tried it, the notifier worked but I started getting the error again once I changed it to an enabler, I'm not sure why on my original project it was still triggering even with the notifier so I had assumed it was both, will update the title.

@tinmanjuggernaut It happens when the scene is instanced in the node tree for the first time, either by the engine on startup or at runtime, if I were to instantiate this scene I get the error every time it is instantiated.


![image](https://user-images.githubusercontent.com/75141902/184873355-81454cb5-cbc4-46d3-8bbb-80fe61cbd343.png)

**Comment by IvanIG3** [comment]
Hi! I also found this error, but for 3D, with a VisibleOnScreenEnabler3D and a GPUParticles3D. The two nodes must be under the same parent to trigger the error.
I'm working with Godot 4.0.stable.

**Comment by IvanIG3** [comment]
This is still an issue in 4.0.3.

**Comment by IvanIG3** [comment]
This is still an issue in 4.1.1.
