### ISSUE TITLE
Make popup windows / grid column widths resizable

### ISSUE THREAD

**Issue by RayKoopa** [godotengine/godot#6437]
**Operating system or device - Godot version:**
Windows 10 x64 - Godot 2.1 stable

**Issue description** (what happened, and what was expected):
So I'm sitting here using one of these huge 2560x1440 monitors at default DPI. Godot runs maximized. Opening the editor settings popup window for example makes it that wide that it starts to become hard to trace back the setting value on the far right to the setting's name on the left.

I tried to resize the window, but it seems to be of fixed width. That's a little annoying. (It even just closes when simply trying to hit the border but missing it thus clicking the main application window, or just scrolling outside of it above the main window, but that's another topic).

On top of that, I cannot resize the columns of the grid showing me those settings (to shrink - or better, even autofit - the setting's name column). I saw it was possible in some older version of Godot, but the headers are gone.

Can it be made possible to show these column headers again or (even better IMHO) make those popup windows resizable?

**Steps to reproduce:**
Buy a monitor which is far too huge, open settings window, enjoy (or not).

**Comment by bojidar-bg** [comment]
Closing since the PR mentioning it got merged, and it looks someone forgot the `fix`/`fixes` keyword again... (feel free to comment if it shouldn't be closed yet)

**Comment by RayKoopa** [comment]
Grid columns are still not resizable tho

**Comment by bojidar-bg** [comment]
@RayKoopa Yeh, but we have #7133 for this.

**Comment by RayKoopa** [comment]
Noice
Burninate this horrible issue then!
