### ISSUE TITLE
Inspector buttons are missing padding on the right side

### ISSUE THREAD

**Issue by fire-forge** [godotengine/godot#64371]
### Godot version

v4.0.alpha14.official [106b68050]

### System information

Windows 10

### Issue description

Inspector buttons are missing padding on the right side of the text.

| Alpha 13 | Alpha 14 |
---|---
| ![image](https://user-images.githubusercontent.com/67974470/184504374-8cef0821-cdd4-4d17-a619-8ff10f2b2905.png) | ![image](https://user-images.githubusercontent.com/67974470/184504282-ce62bc3f-7fc0-40e3-b7a8-6e898463f622.png) |
| ![image](https://user-images.githubusercontent.com/67974470/184504385-92c77f80-3b23-463b-96c9-1b6dd7ecb9a6.png) | ![image](https://user-images.githubusercontent.com/67974470/184504313-f6e7a273-1460-47a0-a215-615e07842259.png) |
| ![image](https://user-images.githubusercontent.com/67974470/184504392-47e51e15-a0d0-494d-b0ac-61a29b0fb6cd.png) | ![image](https://user-images.githubusercontent.com/67974470/184504333-7d2051a8-e937-4482-b0e6-f286024016bd.png) |

### Steps to reproduce

* Select a node.
* Look at the Add Metadata button at the bottom of the inspector.

**Comment by Calinou** [comment]
I can confirm this on 4.0.alpha 29492f908 (Linux). This can be seen in the project manager when the Remove Missing button is visible in the sidebar:

![image](https://user-images.githubusercontent.com/180032/184509272-a8721221-ba04-4e64-ab87-d2193acdbca4.png)
