### ISSUE TITLE
Instantiated scene changes reset, when animation player in that scene uses "Reset on Save"

### ISSUE THREAD

**Issue by TicklesTheBrain** [godotengine/godot#64376]
### Godot version

4.0 alpha 14

### System information

Windows 10, Radeon 5500 XT

### Issue description

When making changes to an instantiated scene (e.g. changing its position), the changes will be lost on scene save if there is a animation track resetting those variables inside the animation player in that scene, with "Reset on save" option checked.

I think this is expected behavior, when editing the scene itself directly, the "reset on save" tooltip even explains it quite nicely. But if I instantiate that scene inside another one, this leads to a lot of head scratching when any changes are lost on every save. Not sure if this is expected behavior or not, but even if it is I would have at least expected some visibility on what is happening, since I can't even see the offending animation player in the scene tree.

### Steps to reproduce

1. in main scene. move the instantiated node2D scene a bit in the editor.
2. save the scene
3. The changes are reset.

### Minimal reproduction project

[godot_test.zip](https://github.com/godotengine/godot/files/9332126/godot_test.zip)

**Comment by Calinou** [comment]
cc @RandomShaper, as they implemented the animation reset track feature.

**Comment by TicklesTheBrain** [comment]
Ok, I don't think this is a bug anymore. I was just misunderstanding how animating root node of the scene works. In short - you shouldn't do it. Adding in another Node2D at the top, solves my problem.

Still think it would be useful to see warning when changing properties that are going to be reset on save, but I don't think this is very important.
