### ISSUE TITLE
Vulkan: GPU Hangs/Freezes immediately after running

### ISSUE THREAD

**Issue by MagiaPotagia** [godotengine/godot#64387]
### Godot version

v4.0.alpha13.official [59dcddc45], v4.0.alpha14.official ["106b68050"], Master

### System information

Arch Linux, XFCE4, AMD Curacao PRO [Radeon R7 370 / R9 270/370 OEM], amdgpu drivers, Vulkan (radv mesa), AMD FX-8320E Eight-Core Processor

### Issue description

Upon starting Godot 4, starts the Project Manager window, but freezes the entire desktop environment (mouse moves, but xfce4 totally freezes and theres no keyboard input) before it can draw it, forcing me to reboot the operating system.

After reboot the following command gives this information
```
$ sudo journalctl -k -b -1
Aug 14 05:16:10 arch kernel: [drm:amdgpu_job_timedout [amdgpu]] *ERROR* ring gfx timeout, signaled seq=3119, emitted seq=3122
Aug 14 05:16:10 arch kernel: [drm:amdgpu_job_timedout [amdgpu]] *ERROR* Process information: process godot.linuxbsd. pid 1030 thread godot.linuxbsd. pid 1030
Aug 14 05:16:10 arch kernel: amdgpu 0000:01:00.0: amdgpu: GPU recovery disabled.
```
This happens in kernels: Linux 5.19.1-arch2-1 and linux-lts 5.15.60-1

Because I can't get feedback from Godot, because the operating system freezes, I need help figuring out a way to print possible errors into a file after reboot, tried the following:
```
$ ./godot.linuxbsd.opt.tools.64 -d > crash
$ cat crash 
Godot Engine v4.0.alpha.custom_build.f2a616841 - https://godotengine.org
Vulkan API 1.2.0 - Using Vulkan Device #0: AMD - AMD RADV PITCAIRN
```
It didn't mange to write anything helpful for tracking down the problem.

In one of the attempts it printed in the terminal something about "shader_rd", this could be something totally unrelated and misleading but that is why I need to figure out a way to print errors and debug information into a file.

### Steps to reproduce

The freeze occurs in versions:
Godot 4.0 alpha 14
Godot 4.0 alpha 13
Build of Master (platform=linuxbsd target=release_debug)

It can be avoided by using flags --rendering-driver opengl3

Godot 4.0 alpha 12 (v4.0.alpha12.official ["2c11e6d9e"]) starts up properly, so the issue starts in alpha 13

**Comment by MagiaPotagia** [comment]
I'm still having this freezing issue with alpha15, I couldn't get any important error messages from godot.
I think godot computes shaders (?) when you execute it and that freezes it for me.
No one else seems to have this issue (leave a comment if you do) so it could probably be something with the kernel, vulkan or amdgpu misbehaving with my graphics card.
(Sorry for accidentally closing this issue, I'm new to this site and I thought there was going to be a confirmation prompt)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/65145. This may be a driver bug.

**Comment by akien-mga** [comment]
Let's consolidate this issue in #65409 as it appears to be the same and there's been more debugging done there.
