### ISSUE TITLE
Scene tab: selection is applied to hidden nodes when filtering

### ISSUE THREAD

**Issue by jgillich** [godotengine/godot#64399]
### Godot version

ad247899ab924cc7ab9e6d4ee8bde56265f1a3d0

### System information

Fedora Silverblue 36, Ryzen 2400G

### Issue description

When filtering nodes in the scene tab, selection does not work correctly. I'd expect that I can select the search results and nothing else, but that's not how it works. Instead, all nodes in-between are also secretly selected and actions such as cutting nodes (Ctrl+X) produce unexpected results.

Here is a video demostrantion. First, we try to drag-move nodes, which does not work at all (should it? I guess respecting the node hierarchy is difficult, but perhaps it could be allowed if all nodes have the same parent). Then we do Ctrl+X, which also cuts node that were not visibly selected.

https://user-images.githubusercontent.com/347965/184549440-ba6412db-653c-4548-b68e-9f6a8a0d6523.mov

### Steps to reproduce

1. Create nodes named A, B, AA, BB, AAA in that exact order
2. Filter for `A` and use copy or cut on the selected nodes
3. Observe how B and BB were also affected by the action

**Comment by Calinou** [comment]
Can you reproduce this in 3.5?

**Comment by jgillich** [comment]
No, this does not happen in 3.5.
