### ISSUE TITLE
Normal map doesnt work 

### ISSUE THREAD

**Issue by singam96** [godotengine/godot#6440]
Godot 2.1 custom build

after assigning normal map for a material , the mesh becomes black.

export normal maps from blender and use it in godot

**Comment by RandomShaper** [comment]
I could look at this if you provide a sample project.

**Comment by reduz** [comment]
which format are you exporting, how are you exporting and how are you
importing?

**Comment by gindar** [comment]
try this: http://docs.godotengine.org/en/stable/tutorials/3d/importing_3d_scenes.html#force-generation-of-tangent-arrays

**Comment by bojidar-bg** [comment]
@singam96 Please, reply to the above questions, otherwise this issue might be closed as invalid.

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by singam96** [comment]
Ohh sorry for late reply.... Ok i will check  :)

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.
