### ISSUE TITLE
Search Help locks editor in single-window mode (DisplayServer regression)

### ISSUE THREAD

**Issue by Capital-EX** [godotengine/godot#64402]
### Godot version

v4.0.alpha14.official [106b68050]

### System information

Manjaro 21.3.6 Ruah on Linux 5.10, Xfce4, Xfwm4

### Issue description

When clicking the "Search Help" button while using `--single-window`, the editor window for it will not display. Additionally, this will cause the popup window to block all input. There is no keyboard nor mouse input that can restore control and thus the editor process must be killed.
![image](https://user-images.githubusercontent.com/13488718/184552775-3a4813c6-e162-4c76-9cd3-f8655e549680.png)

Further more I am forced to use `--single-window` mode due to issue #56536.

### Steps to reproduce

1. Open Godot
2. The Script Editor
3. Click "Search Help"
4. Editor will become unusable.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Are you on a multi-monitor setup? If so, this is likely because the Search Help window's saved bounds are located outside the editor window.

**Comment by Capital-EX** [comment]
> Are you on a multi-monitor setup? If so, this is likely because the Search Help window's saved bounds are located outside the editor window.

Yes, I'm using a setting that has a 1920x1080 Wacom Tablet display and a 3440x1140 Ultra-wide Dell display.

**Comment by KoBeWi** [comment]
@Capital-EX Does it still happen? Sound like it should've been fixed by #61336

**Comment by Capital-EX** [comment]
After some testing, I ended up getting this error in Godot:
```
ERROR: Window 0 spawned at invalid position: (2780, 484).
   at: popup (scene/main/window.cpp:1554)
```

As well as having the window spawn in away I can't move:

![Screenshot_20230225_102026](https://user-images.githubusercontent.com/13488718/221365111-5285ac94-b870-46e1-bd51-fbe745ac354b.png)

However, it may have been a fluke as I can't see to trigger that again and don't know how I needed up in that state.

**Comment by KoBeWi** [comment]
That error appears when the window was previously opened on another screen and it's no longer available. It's mostly informative, because it then forces the window on the correct screen.
