### ISSUE TITLE
ShaderMaterial textures show up empty even if they have correct UID and path references

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#64409]
### Godot version

v4.0.alpha.custom_build [b062e2ca9]

### System information

Windows 10 64 bits GLES3 GeForce GTX 1060 6GB/PCIe/SSE2

### Issue description

I opened a project I've been keeping up to date with Godot 4 over the past months and this time I found out my textures didn't show up in the game. Turns out the textures I had assigned in the material all show up as "Empty":

![image](https://user-images.githubusercontent.com/1311555/184557509-e72d45bb-bec1-48db-9c36-fe2c986dfc64.png)

Even though in the `.tres` file, the UID and paths seem to be both correct.

I tried deleting `.imported`, `shader_cache` and `uid_cache` to reimport the project, but that didn't solve the issue.

### Steps to reproduce

I'm not sure about the reproduction steps, so I froze my project as-is and stripped it down to just one material and its dependencies. So far it still happens in that version.
Just open `solar_system/materials/planet_material_grassy.tres`, observe textures are all empty, then inspect what's in the `.tres` file and see that all information is correct and texture uniforms are not supposed to be empty.

[https://zylannprods.fr/dl/godot/SolarSystem4_not_finding_textures.zip](https://zylannprods.fr/dl/godot/SolarSystem4_not_finding_textures.zip)

**Comment by tinmanjuggernaut** [comment]
I've had no problem with many materials and shaders converted from gd3.

I downloaded your project, copied the material, and in my copy I reattached the textures and saved it. Reopened the project and the new material retained the textures.

Here's the difference between the two files.

```
--- planet_material_grassy.tres 2022-08-16 17:34:49.624141100 +0800
+++ "planet_material_grassy - Copy.tres"        2022-08-16 17:39:28.389392700 +0800
@@ -9,11 +9,11 @@
 [resource]
 render_priority = 0
 shader = ExtResource("1")
-shader_param/u_block_local_transform = null
-shader_param/u_lod_fade = null
-shader_param/u_mountain_height = 10000.0
-shader_param/u_side_albedo_texture = ExtResource("2_ylcsf")
-shader_param/u_side_normal_texture = ExtResource("3_780vy")
-shader_param/u_top_albedo_texture = ExtResource("2")
-shader_param/u_top_normal_texture = ExtResource("4")
-shader_param/u_transition_mask = null
+u_block_local_transform = null
+u_lod_fade = null
+u_mountain_height = null
+u_side_albedo_texture = ExtResource("2_ylcsf")
+u_side_normal_texture = ExtResource("3_780vy")
+u_top_albedo_texture = ExtResource("2")
+u_top_normal_texture = ExtResource("4")
+u_transition_mask = null

```

**Comment by Zylann** [comment]
I am aware creating new materials probably works. What I am reporting here is an existing material with valid data loading incorrectly (or if it is invalid somehow, I'd like to know what mistake there is)

**Comment by tinmanjuggernaut** [comment]
Changed by @Chaosus https://github.com/godotengine/godot/pull/62972

Here:
https://github.com/godotengine/godot/commit/886c2d9681e83d8e1aed2a793f5d8136c2a98c4e#diff-067f83187419fe00fff5ff7d7e726ff4bd3f6be24ea0920d990ff495a151b7bc

Regression PR: 
https://github.com/godotengine/godot/pull/64092
