### ISSUE TITLE
Navigation Agent 3D "Target Desired Distance" Ignored using _integrate_forces() function

### ISSUE THREAD

**Issue by KC098** [godotengine/godot#64415]
### Godot version

3.5

### System information

Windows 10 GLES3 AMD Radeon HD 8730M

### Issue description

When using the Navigation Agent, target desired distance property is being ignored when using the _integrate_forces function

### Steps to reproduce

1. Create a RigidBody node
2. Add a Collision Shape node as children
3. Add Navigation Agent as children of the rigidbody
4. Add a Script to the RigidBody node
5. Paste this into the script
```gdscript
func _ready() -> void:
	_get_follow_target_position()
	
func _get_follow_target_position():
	$NavigationAgent.set_target_location([SOMENODE].global_transform.origin)

func _integrate_forces(state: PhysicsDirectBodyState) -> void:
	_get_follow_target_position()
	if $NavigationAgent.is_target_reached():
		print("forces reached")

func _physics_process(delta: float) -> void:
	if $NavigationAgent.is_target_reached():
		print("process reached")
	

```
6. Play
7. It should only print "process reached"

**Comment by Calinou** [comment]
@KC098 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

Related to https://github.com/godotengine/godot/issues/62532. Have you tried adjusting Target Desired Distance in various ways?

**Comment by smix8** [comment]
No it is not ignored.

If you use `NavigationAgent.set_target_location()` you are requesting a path update which resets the internal state e.g. sets `target_reached = false` which makes `NavigationAgent.is_target_reached()` return false.

**Comment by KC098** [comment]
Oh I see, thanks for clarifying. Also, I don't think the documentation states that. Something along the lines of "Note: when calling '`_set_target_location()`' inside a '`_integrate_forces()`' will cause the path to reset wich makes the '`is_target_reach()`' always return false. Instead, call it using '`_physics_process()`'."

**Comment by Calinou** [comment]
Reopening, as this still needs to be documented.

**Comment by smix8** [comment]
@Calinou  What do you want to document? The documentation has it as a stick note.

> Note: After set_target_location() is used it is required to use the get_next_location() function once every physics frame to update the internal path logic of the NavigationAgent.

and the function set_target_location() states:

> This will clear the current navigation path.

I don't think we need to state every single interal value that gets reset on a navigation path clear.
