### ISSUE TITLE
Feature Tags not being added to editor runs

### ISSUE THREAD

**Issue by DPMakerQB** [godotengine/godot#64419]
### Godot version

3.5.0

### System information

Windows 10

### Issue description

I have a project with two export presets. One export preset has the "demo" feature tag. I set that export preset as "Runnable".

When I press "Play", the "demo" feature tag is not set during testing. The "demo" feature tag is present if I actually export the game.

### Steps to reproduce

1. Add a `print(OS.has_feature("demo")` at the start of any project.
2. Create an export preset that has the "demo" feature tag
3. Set the export preset to "Runnable"
4. Press "Play" on the editor window to run the game as you would normally during development
5. The console should say `false`, even though the runnable preset is currently set to have the demo tag

### Minimal reproduction project

[godot_issue.zip](https://github.com/godotengine/godot/files/9335560/godot_issue.zip)

**Comment by Calinou** [comment]
This is expected. "Runnable" means that the preset is available in one-click deploy, but one-click deploy is currently only implemented for Android and HTML5. It's being implemented for desktop platforms in https://github.com/godotengine/godot/pull/63312, but only for 4.0.

**Comment by DPMakerQB** [comment]
Thank you!

**Comment by avnerh1** [comment]
> This is expected. "Runnable" means that the preset is available in one-click deploy, but one-click deploy is currently only implemented for Android and HTML5. One-click deploy is being implemented for desktop platforms in #63312, but only for 4.0.

Does it mean that custom features cannot be set when running from the editor? What is the suggested way to debug them, then?
