### ISSUE TITLE
"Save Branch as Scene" on node with "Scene Unique Name"

### ISSUE THREAD

**Issue by ctrlraul** [godotengine/godot#64425]
### Godot version

3.5.stable

### System information

Windows 10

### Issue description

Using "Save Branch as Scene" on node with "Scene Unique Name" enabled creates a new scene with it's owner node having Scene Unique Name enabled.

![image](https://user-images.githubusercontent.com/47065615/184602256-e216e3b3-9087-4bc3-b16d-5748dc555444.png)

### Steps to reproduce

1. Create a new scene
2. Add a child node to the scene
3. Enable "Scene Unique Name" on the child node
4. Use the "Save Branch as Scene" context menu option on the child node

### Minimal reproduction project

[Scene Unique Name Bug.zip](https://github.com/godotengine/godot/files/9336027/Scene.Unique.Name.Bug.zip)

**Comment by Mickeon** [comment]
I confirm this also happens in Godot 4.
