### ISSUE TITLE
Files can only be opened once on Android (scoped storage regression)

### ISSUE THREAD

**Issue by JonnathanFG** [godotengine/godot#64434]
### Godot version

3.5 stable

### System information

android - 12

### Issue description

The files in godot only open once, when you go back in it does not load the files (Empty World)
Running the game everything works fine 

### Steps to reproduce

Enter godot for the second time

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/63949.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
