### ISSUE TITLE
Texture on imported .blend/gltf-separated files have wrong colors

### ISSUE THREAD

**Issue by Eisendroid** [godotengine/godot#64431]
### Godot version

4.0 Alpha 14

### System information

Manjaro 21.3.6 with Linux Kernel 5.10.136-1, Nvidia GTX1080ti, Driver Version 515.65.01, Vulkan

### Issue description

Texture on Imported mesh has different colors, dependent on the chosen method/file.
All files have been exported by Blender 3.2.2
At the export options in Blender, i always chose "Geometry" -> "Materials" -> "Export"

Files formats tested:
 - .blend (wrong colors)
 - gltf separated (wrong colors)
 - glb binary (correct colors)
 - gltf embedded (correct colors)

 

![Colors1](https://user-images.githubusercontent.com/72012005/184618021-21eeb86e-543c-4c51-88a7-240fab557788.png)

When you look closer, you can even see some grainy pattern

![Colors2](https://user-images.githubusercontent.com/72012005/184618216-b9a87397-7429-4801-8fb5-2290bff6abc0.png)

### Steps to reproduce

1. Open Blender, create plane, apply black and white texture
2. Export with the specific file format, standard options
3. Add to Godot Scene
4. Add WorldEnvironment, set Background Energy to 0
5. Add DirectionalLight3D

### Minimal reproduction project

[Bug Project.zip](https://github.com/godotengine/godot/files/9336848/Bug.Project.zip)

**Comment by Calinou** [comment]
Pixel art textures should have their texture compression mode set to Lossless in the Import dock. Otherwise, it's expected that they look bad.

**Comment by Eisendroid** [comment]
Sry for my mistake. Looked for hours everywhere except in the import dock of the texture itself.
