### ISSUE TITLE
mouse_entered signal is not working if mouse mode has been set to MOUSE_MODE_CAPTURED when mouse is outside the window

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#64438]
### Godot version

4.0.dev 49ac05550e4ce3b3489fad0a2addd907af1f5898

### System information

Ubuntu 22.04, 6700xt

### Issue description

When mouse is outside the window when `Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)` is called, then after calling Input.set_mouse_mode(Input.MOUSE_MODE_VISIBLE) GUI is not behaving properly (it has no idea that mouse is hovering over them) and some signals like `mouse_entered`/`mouse_exited` are not called. 

https://user-images.githubusercontent.com/6129594/184652538-00145e90-497b-45bb-b7db-d221ba1b1517.mp4

### Steps to reproduce

1. Create new project
2. In ready add 
```
    await(get_tree().create_timer(5).timeout)
    Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)
```
3. Add also
```
func _input(event: InputEvent) -> void:
	if event.is_action_pressed("ui_cancel"):
		Input.set_mouse_mode(Input.MOUSE_MODE_VISIBLE)
```
4. Add two buttons to the main scene of the project
5. Start the project, move your mouse outside the window
6. When mouse gets captured click 'escape'
7. Ensure to not move mouse outside the window at any point from now on
8. Click one of the buttons, note that they are not highlighting when mouse is hovering over them

Alternative is to get reproduction project and follow steps from video attached above

### Minimal reproduction project

[MouseOverIssue.zip](https://github.com/godotengine/godot/files/9337775/MouseOverIssue.zip)

This investigation was kindly sponsored by The Mirror

**Comment by kubecz3k** [comment]
I investigated it and I have a proposal for the fix
I will create PR soon

**Comment by Sauermann** [comment]
This problem (which doesn't happen on Windows) comes from the fact, that the linuxbsd- and windows-display-servers behave differently. I opened a PR, that solves this difference.
