### ISSUE TITLE
v4.0-alpha14 launcher/project manager freezes after opening a popup and closing it again

### ISSUE THREAD

**Issue by chibbi** [godotengine/godot#64433]
### Godot version

v4.0.alpha14.official [106b68050]

### System information

Windows 10, RTX 2080SUPER, 32GB RAM, Ryzen 1600

### Issue description

I just downloaded the alpha 14 for godot 4.0, and it showed me some old projects. I didn't want to delete the content of those projects, but did want to remove them from the launcher.
So i selected them and pressed "Remove" without ticking the "Also delete project contents" box.
After that the Popup closed itself and the launcher was unresponsive (Windows did not gray out the Window it just did not do anything). I could open another Popup (ex. About) but the popup window was/is completly broken and not what youd expect.

After testing other things like selecting a project and doing anything else after it, i have come to the conculsion that it has nothing to do with removing the project or selecting a project its just, that as soon as you had a popup open and closed it again, the window is broken.

Opened About:
![grafik](https://user-images.githubusercontent.com/68948051/184629517-867d98c0-b484-4945-ab0d-67b5323ee3ae.png)

Closed About:
![grafik](https://user-images.githubusercontent.com/68948051/184629567-b6c6e957-56ec-4327-9efa-e77dff89d8f6.png)

Tried to create a new project:
![grafik](https://user-images.githubusercontent.com/68948051/184629621-ff000ab8-2df3-4824-8a52-2028166be82c.png)

#### This also breaks the "New Project popup" when trying to change the project directory:
![grafik](https://user-images.githubusercontent.com/68948051/184630151-d1bcae25-9fdd-45a6-a8b1-79d7b9720ac6.png)

I hope that it is not already documented and at the right place, i looked through the issues but did not find it. 

### Steps to reproduce

1. open launcher/project manager
2. open any popup (ex. new project or removing a project or about)
3. close that popup
4. try to use the launcher in any way

opening new project and then closing that popup seems to sometimes close the launcher after a few seconds, but opening about and then closing about again seems to completly break it.

### Minimal reproduction project

no project necessary

**Comment by bruvzg** [comment]
Do you have RivaTuner Statistics Server running? Try disabling it or adding an exception for Godot. RTSS seems to be incompatible with multi window Vulkan apps - see #57937.

**Comment by chibbi** [comment]
Ah okay thanks, 
Oh i didn't find that because i used the "is:issue is:open milestone:4.0 label:bug" filter from the link in the blog and the issue is not part of the 4.0 project.
