### ISSUE TITLE
RID as default value are empty in extension_api.json 

### ISSUE THREAD

**Issue by touilleMan** [godotengine/godot#64442]
### Godot version

4.0-rc13

### System information

n/a

### Issue description

RID as default value are not serialized properly, for instance `PhysicsServer2D::joint_make_pin`

```python
{
	"name": "joint_make_pin",
        [...]
	"arguments": [
		{
			"name": "joint",
			"type": "RID"
		},
		{
			"name": "anchor",
			"type": "Vector2"
		},
		{
			"name": "body_a",
			"type": "RID"
		},
		{
			"name": "body_b",
			"type": "RID",
			"default_value": ""  # <== ?????
		}
	]
},
```

This is because `Variant::get_construct_string` is use for the serialization which doesn't support serialization of `RID`:
https://github.com/godotengine/godot/blob/7c7ce7dcd7430d8503d6f74bb49c68892bc31dca/core/extension/extension_api_dump.cpp#L528

`Variant::get_construct_string` doesn't support serialization of `RID` and default to an empty string:
https://github.com/godotengine/godot/blob/7c7ce7dcd7430d8503d6f74bb49c68892bc31dca/core/variant/variant_parser.cpp#L1886-L1887

## The main issue

We represent the default value in ClassDB as an *instance* of `RID` which doesn't tell us we don't care about *this* instance (i.e. the default value is in fact "a new instance of `RID` is going to be created each time you call the function")

I think the easier solution would be to add a workaround in `extension_api_dump.cpp` (typically adding `"RID()"` as `default_value` if the argument type is `RID` and it has a default value set).

Of course this is not perfect given this way `extension_api.json` also don't provide the "this default value should be generated before each use". However we can fix this by adding a `reusable_default_value` boolean flag (that would only be true for RID).

## Bonus issue

I'm not sure why `Variant::get_construct_string` doesn't serialize `RID` :thinking:
It is also the case for `Callable` and `Signal`.

It means Dictionary/Array containing RID/Callable/Signal are not properly serialized as they will be displayed as `[, , ,]`

In the case this behavior is expected, shouldn't we add a warning when trying to serialize RID/Callable/Signal ?

### Steps to reproduce

n/a

**Comment by AThousandShips** [comment]
Got a PR open for this, due to default serialization
