### ISSUE TITLE
``Directory`` methods returning ``Error``-Type cause ``stack corruption``-debug errors

### ISSUE THREAD

**Issue by DNKpp** [godotengine/godot#64446]
### Godot version

4.0.alpha 14 and alpha 13

### System information

Windows 11; Visual Studio 2022

### Issue description

I attempted to read all files in a given directory. This code is called inside of a ``Node::_read()`` overriden function.

```cpp
TreeNodeFactory::TreeNodeFactory(std::initializer_list<tree_directory_def> directories)
{
	auto* resourceLoader = gd::ResourceLoader::get_singleton();

	for (const auto& [path, type] : directories)
	{
		if (gd::Directory dir{}; dir.open(path.data()) == gd::OK)
		{
			// do something here
		}
		else
		{
			// print error message here
		}
	}
}
```

The code itself seems to be working, but on every execution of ``dir.open()`` I receive the following error:
![image](https://user-images.githubusercontent.com/761844/184667620-e2d7ef52-02de-49ad-9c5d-f96d5f2ac655.png)

Here is the call stack:
![image](https://user-images.githubusercontent.com/761844/184667677-88853e89-0b37-4290-999c-ef3cf249b728.png)

The appearing message in the executable:
![image](https://user-images.githubusercontent.com/761844/184668515-5a6f7e0f-de48-48b3-bb50-9a7d4d82b935.png)

Clicking ignore (multiple times) let the program continue without any obvious issues.

I did some testing and it seems any method of ``Directory`` which is returning an ``Error``-Type causes this error message too. Other functions returning for example a bool (tested with ``file_exists()``, ``dir_exists()`` and even the following call to ``get_files()``) do not cause any runtime error messages.

### Steps to reproduce

I didn't do any tests within a small sample project. If necessary I can do that.

**Comment by Calinou** [comment]
@DNKpp Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by RiederAlex** [comment]
This has the same characteristics as #64455

**Comment by derammo** [comment]
Yes, this is the same bug as the one you just linked.   The other issue explains how it happens from the code perspective, and this one confirms that it is happening with alpha 13.
