### ISSUE TITLE
Text Editor Autocompletion should suggest keywords

### ISSUE THREAD

**Issue by RayKoopa** [godotengine/godot#6445]
**Operating system or device - Godot version:**
Windows 10 x64 - Godot Stable 2.1

**Issue description** (what happened, and what was expected):
When typing code in the GDScript text editor, the autocompletion never suggests keywords such as `if`, `true`, etc. This makes it a little annoying to quickly tab them into the code without fully writing the keyword out. Especially when wanting to insert a line break with Enter right after a `pass`, it inserts another word then.

**Steps to reproduce:**
Begin to type GDScript code. In my example, when tabbing `if` away I got `stepify` instead, and for `pass` I got `PAUSE_MODE_PROCESS` inserted.

**Comment by kukiric** [comment]
I gave this a try and added all reserved keywords to the completion list, but some entries (like "pass") are several items down, and it also lists a few things that don't make sense in a function scope (like "extends").

I'm not sure if I should keep it like this, as it's already functional, or if I should improve ranking (like eg. prefer similar casing so constants don't pop up when typing a keyword or identifier), and only add specific keywords into the completion code (which I'm afraid may cause the completion engine to go out of sync with the language if any keywords are added or removed).

Thoughts?

**Comment by RayKoopa** [comment]
I think it's fine. Maybe the completion list gets some icons in the future to show what's a method, class, keyword, etc.. And maybe some filter (sorry that I always look at Visual Studio :/) Close the issue?

**Comment by kukiric** [comment]
No need to close, this issue is still unresolved. I'll probably take another go at it after the holidays, and someone else can still take it on if they feel like it.

**Comment by kukiric** [comment]
I am no longer working on this issue. Real life has taken over, and I haven't done enough research to find a better solution other than just hardcoding the keywords, which would cause them to appear in all sorts of weird contexts (like inside of an if/while conditional, or while typing out parameters for function calls, etc).

**Comment by mhilbrunner** [comment]
Fixed by https://github.com/godotengine/godot/pull/18531

**Comment by breakmt** [comment]
This is not working in 3.0.4 stable
