### ISSUE TITLE
godot 3.5, Invalid target platform "android" 

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#64450]
### Godot version

3.5

### System information

Mac

### Issue description

I have everything setup correctly, and I can alway build for android for godot source below  3.5.

However in 3.5:

scons platform=android target=release_debug android_arch=arm64v8

scons: Reading SConscript files ...
Invalid target platform "android".
The following platforms were detected:

	iphone
	osx
	server

Please run SCons again and select a valid platform: platform=<string>
pro:godot-3.5-stable yizheng$ 

### Steps to reproduce

run scons platform=android target=release_debug android_arch=arm64v8

**Comment by alexzheng** [comment]
ANDROID_SDK_ROOT missed.

**Comment by vladlugovskoy** [comment]
You are my hero!
