### ISSUE TITLE
Creating a new Shader Include creates a new file, but the editor seems unaware of it

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#64466]
### Godot version

Godot 4.0 alpha14

### System information

Windows 10 64 bits GLES3 GeForce GTX 1060 6GB/PCIe/SSE2

### Issue description

In the new text shader editor, you can create a new Shader or Shader Include. If you create a Shader Include, it will ask for a file name, create that file and then you can edit it.
But the editor seems unaware that the shader is from a file. It still shows `ShaderInclude:-9223370360341091303` as its name, and doing `File -> Save File` opens a new file dialog as if the file didn't exist.

![image](https://user-images.githubusercontent.com/1311555/184701150-bcb73484-4f7d-41b7-b04d-7921726ca583.png)

Trying to save over the file does not solve it.

### Steps to reproduce

1) In any project, open the Shader Editor by clicking on the `Shader Editor` button in the bottom panel
2) Choose `File` -> `New Shader Include`
3) In the dialog that opens, choose a file name and click `Create`
4) Observe the file is created but the editor acts as if the current shader isn't linked to that file.
5) Try to save it using Save As and overwrite the file: observe this doesn't fix the issue.

**Comment by bitsawer** [comment]
Thanks for the report! I can no longer reproduce this issue and I didn't manage reproduce this earlier this year near Godot 4.0 launch, so I think this was fixed at some point during the general Godot 4.0 stabilization work. I'm closing this as completed, but feel free to comment here or re-open the issue if you can still reproduce this.
