### ISSUE TITLE
Shader.has_uniform() incorrectly reports uniforms as missing

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#64467]
### Godot version

Godot 4.0 alpha14

### System information

Windows 10 64 bits GLES3 GeForce GTX 1060 6GB/PCIe/SSE2

### Issue description

I'm writing node configuration warnings that check shaders for specific uniforms required for some features to work in a node, but it seems no matter which uniform I test, `has_uniform` always return `false`. I need to be able to check them.

Workaround:
```gdscript
static func shader_has_uniform(shader: Shader, uniform_name: String) -> bool:
	var uniforms = RenderingServer.shader_get_shader_uniform_list(shader.get_rid())
	for uniform in uniforms:
		if uniform.name == uniform_name:
			return true
	return false
```

### Steps to reproduce

1) Have a shader with `vec3 uniform test_color;` which uses it, for example outputting to `ALBEDO`
2) Create a script which loads the shader and calls `shader.has_uniform("u_test_color")`
3) Observe it prints `false`, instead of `true`.

### Minimal reproduction project

[ShaderHasUniform.zip](https://github.com/godotengine/godot/files/9339392/ShaderHasUniform.zip)

**Comment by Chaosus** [comment]
Fixed by https://github.com/godotengine/godot/pull/68513
