### ISSUE TITLE
Inconsistancy in scaling logic for render buffers

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#64478]
### Godot version

4.0.dev 5a8d786ef9dcfd5b206ec3eeb5e369930e773acc

### System information

Any

### Issue description

Currently we support bi-linear and FSR scaling of our viewports which allow us to render 3D content at a lower resolution and then scale this up for final display.

Our current setup makes some assumptions that are not always true and currently scaling on the mobile renderer when subpasses are used is broken because we can't perform the final pass that copies the result into the render target for the viewport.

Right now we don't communicate to the renderer which scaling is used but rely on misinforming the render implemention as follows:
- for bi-linear both internal size and target size are set to the scaled down resolution
- for FSR the internal size is the size at which we render 3D content, and target size is the correct size for our render target (i.e. viewport size)

This needs to change, we need to pass the correct render target size to the render implementation for both bi-linear and FSR. This way we can detect in setting up our subpasses that the final tonemapping step which also does scaling, needs to be a separate pass.

This also results in us having to pass the scaling method to the render implementation so the right code is being called. 

I do suggest adding `VIEWPORT_SCALING_3D_MODE_OFF` to `ViewportScaling3DMode` so we do not need to constantly check if the internal size and target size are different. There was some discussion about exposing this to the end user because we can't hide properties that do not apply in project settings. I.e. the user can now set `VIEWPORT_SCALING_3D_MODE_OFF` with scaling set to 2.0 and assume this should do something.
We could omit the OFF setting from the project settings and purely use this internally.

That is, simply do:
```
class RenderingServer : public Object {
	...
	enum ViewportScaling3DMode {
		VIEWPORT_SCALING_3D_MODE_BILINEAR,
		VIEWPORT_SCALING_3D_MODE_FSR,
		VIEWPORT_SCALING_3D_MODE_MAX,
		VIEWPORT_SCALING_3D_MODE_OFF = 255, // for internal use only
	};
	...
}

void RendererViewport::_configure_3d_render_buffers(Viewport *p_viewport) {
	...
	if (scaling_3d_scale == 1.0) {
		scaling_3d_mode = VIEWPORT_SCALING_3D_MODE_OFF;
	}
	...
}
```
and only from this point onwards this scaling mode is used.

### Steps to reproduce

n/a

### Minimal reproduction project

n/a

**Comment by BastiaanOlij** [comment]
@Calinou @clayjohn let me know your feedback on this, I could add this into my render buffers PR. I kinda ran into this issue while working on that.

**Comment by clayjohn** [comment]
Sounds fine to me. I don't think anyone was thinking about sub passes when this was first implemented, so this change makes sense. 

I'm indifferent about exposing a VIEWPORT_SCALING_3D_MODE_OFF mode

**Comment by akien-mga** [comment]
Fixed by https://github.com/godotengine/godot/pull/71309.
