### ISSUE TITLE
SceneTreeTween not updating when Pause Mode is active (Process mode is on)

### ISSUE THREAD

**Issue by Gooodgis** [godotengine/godot#64479]
### Godot version

3.5

### System information

Windows 10

### Issue description

When the tree scene is paused, the SceneTreeTween won't tween animations. Even when the node that the script is attached to is set to Process.

![image](https://user-images.githubusercontent.com/111324003/184758279-f629d3bf-b1f6-40af-941b-a452191050c0.png)

### Steps to reproduce

- Write a tween using the SceneTreeTween
- Set the Node with tween script's pause mode to "Process"
- Set Pause to "true" while tween is animating or before animation
- Tween will then stop playing

### Minimal reproduction project

[TweenPauseBug.zip](https://github.com/godotengine/godot/files/9343930/TweenPauseBug.zip)

**Comment by timothyqiu** [comment]
The `SceneTreeTween` in the MRP is created by calling `get_tree().create_tween()` so it's not bound to any Node by default.

To bind it to `Sprite`, you can either call `tween.bind_node($Sprite)` or create it by `$Sprite.create_tween()`. The scene tree tween will then respect the bound node's pause mode.

You can also call the scene tree tween's own `set_pause_mode` if you want it to always process.

**Comment by KoBeWi** [comment]
See the comment above.

**Comment by Gooodgis** [comment]
> The `SceneTreeTween` in the MRP is created by calling `get_tree().create_tween()` so it's not bound to any Node by default.
> 
> To bind it to `Sprite`, you can either call `tween.bind_node($Sprite)` or create it by `$Sprite.create_tween()`. The scene tree tween will then respect the bound node's pause mode.
> 
> You can also call the scene tree tween's own `set_pause_mode` if you want it to always process.

Thanks so much for clearing that up!
