### ISSUE TITLE
Vulkan: FPS is always twice the refresh rate of the screen on macOS

### ISSUE THREAD

**Issue by ellipticaldoor** [godotengine/godot#64475]
### Godot version

4.0.alpha14.official

### System information

macos monterey 12.5

### Issue description

When displaying the fps of the game I see twice the framerate that should be when doing vsync, for example in a 60hz monitor it will tell its going at 120fps, and in a 144hz monitor it will tell is going at 288fps.

This happens only on macos when using moltenvk

### Steps to reproduce

You can create an new label and just display the fps counter

```
func _process(delta):
	$FPS_COUNTER.text = str(Engine.get_frames_per_second())
```

**Comment by bruvzg** [comment]
Seems like MoltenVK bug - https://github.com/KhronosGroup/MoltenVK/issues/1407

**Comment by Calinou** [comment]
For reference, this issue was also reported in https://github.com/godotengine/godot/issues/56355#issuecomment-1003178026.

**Comment by Calinou** [comment]
Fixed on macOS 13.0 (this is a macOS issue): https://github.com/KhronosGroup/MoltenVK/issues/1407

**Comment by acadiansith** [comment]
This may have been fixed for the other renderers, but I am experiencing this issue in the Vulkan (Compatibility) renderer on macOS 13.4.1. On my 60 Hz display, the Forward+ and Mobile renderers cap correctly at 60 FPS, but the Compatibility renderer is double at 120 FPS. (see #79569).

**Comment by bruvzg** [comment]
> Vulkan (Compatibility)

Compatibility is OpenGL not Vulkan.

**Comment by dlej** [comment]
Just going off of what `Help > Copy System Info` says:
> Godot v4.1.stable - macOS 13.4.1 - Vulkan (Compatibility) - Apple M1 - Apple M1 (8 Threads)

**Comment by acadiansith** [comment]
Just going off of what `Help > Copy System Info` says:
> Godot v4.1.stable - macOS 13.4.1 - Vulkan (Compatibility) - Apple M1 - Apple M1 (8 Threads)

**Comment by Calinou** [comment]
> Just going off of what Help > Copy System Info says:

This is a known issue, which is being fixed in some PR (I can't find it right now).
