### ISSUE TITLE
Godot won't go above 90 FPS when using V-Sync on macos with a 120 Hz screen

### ISSUE THREAD

**Issue by dortamiguel** [godotengine/godot#64474]
### Godot version

3.5.stable

### System information

macos monterey 12.5

### Issue description

The new m1 macbooks pro have a 120hz screen and it seems like when using vsync the fps are not going above 90fps.

Weirdly if the window looses the focus and you switch fast again to it then then vsync will stop working and it will produce thousands of fps.

### Steps to reproduce

You can create an new label and just display the fps counter

```
func _process(delta):
	$FPS_COUNTER.text = str(Engine.get_frames_per_second())
```

You will need any monitor that goes above 60hz

**Comment by Calinou** [comment]
Can you reproduce this when using the GLES2 renderer?

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
