### ISSUE TITLE
GradientTexture2D shows grainy on particles

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#64499]
### Godot version

v4.0.alpha.custom_build [862da78ee]

### System information

Linux Fedora, Radeon RX 590

### Issue description

Texture appears grainy and noisy. Not sure if it's a particle issue, a 

![Screenshot from 2022-08-16 16-11-17](https://user-images.githubusercontent.com/7917475/184901390-8d60988a-f306-4f33-9761-4e284d8429ec.png)
![image](https://user-images.githubusercontent.com/7917475/184901578-0cf56e23-5732-4216-bbf3-e583a7bf17e8.png)

Getting a lot of those: 
```
ERROR: Condition "!li" is true. Continuing.
   at: pre_process_gi (servers/rendering/renderer_rd/environment/gi.cpp:1893)
ERROR: Condition "!li" is true. Continuing.
   at: pre_process_gi (servers/rendering/renderer_rd/environment/gi.cpp:1893)
ERROR: Condition "!li" is true. Continuing.
   at: pre_process_gi (servers/rendering/renderer_rd/environment/gi.cpp:1893)
ERROR: Condition "!li" is true. Continuing.
   at: pre_process_gi (servers/rendering/renderer_rd/environment/gi.cpp:1893)
ERROR: Condition "!li" is true. Continuing.
   at: pre_process_gi (servers/rendering/renderer_rd/environment/gi.cpp:1893)
ERROR: Condition "!li" is true. Continuing.
   at: pre_process_gi (servers/rendering/renderer_rd/environment/gi.cpp:1893)
ERROR: Condition "!li" is true. Continuing.
```

### Steps to reproduce

Download MRP

### Minimal reproduction project

[01_torch.zip](https://github.com/godotengine/godot/files/9351802/01_torch.zip)

**Comment by Calinou** [comment]
The particle's material uses the Alpha Hash transparency mode, which is known to be broken: 

![image](https://user-images.githubusercontent.com/180032/184902145-de90ebf3-7d93-47b5-bbb4-ca0a90a3bd7e.png)
