### ISSUE TITLE
Disable UWP export in Mono build

### ISSUE THREAD

**Issue by woubuc** [godotengine/godot#64490]
### Godot version

3.5 stable mono

### System information

Windows 11

### Issue description

When exporting a Mono project, UWP is an option in the list. However, UWP exports are not supported for Mono projects and no UWP export templates exist for the Mono build. So the result is confusion when after installing the export templates, the export window still says it can't find the template for UWP. So it would make sense to disable the UWP option in Mono builds.

I think it would also be helpful to mention the lack of Mono support on the UWP export page in the docs. Right now this is only mentioned as an aside on the C# scripting overview page.

After searching the issues I found that there is *some* chatter around Mono UWP support in #20271 (among others), but it seems that there's a lot of complexity and it doesn't look like proper C#/Mono UWP exports will make it into Godot any time soon. So I think disabling the UWP option in the UI to prevent confusion would be a good solution for the time being.

### Steps to reproduce

1. Create a project in a Mono build
2. Install export templates
3. Create UWP export configuration
4. See the error at the bottom of the export window saying that it can't find the UWP export templates

**Comment by Calinou** [comment]
We may want to hide the UWP export entirely in 4.0, as it's broken in a lot of cases.

For 3.6, I was considering hiding it by default, unless an editor setting is enabled to display the option. It's also pretty broken there, but there may be a handful of people relying on it.

**Comment by woubuc** [comment]
> We may want to hide the UWP export entirely in 4.0, as it's broken in a lot of cases.

So should I take this to mean that, in practice, UWP builds are not actually supported in Godot?

I'm exploring the options to test console builds of my game on Xbox through the Creators Program, but that's only possible for UWP apps. So if the UWP build target is broken and fixing it is not a priority, I would need to reconsider that plan.

It might also be useful to not list UWP as a primary supported export target alongside Windows builds in the docs like it is now, if it's known to be broken.

**Comment by Calinou** [comment]
> So should I take this to mean that, in practice, UWP builds are not actually supported in Godot?

Indeed, I consider them too broken to be usable.

> I'm exploring the options to test console builds of my game on Xbox through the Creators Program

Remember that publishing through the Creators Program will not only limit the maximum resource usage, but will also cause your game to be only visible in a "hidden" section of the store. This isn't the best choice for organic traffic :slightly_smiling_face:

**Comment by woubuc** [comment]
> Going through the full console export process is more expensive, but it'll result in a far better product for end users.

I'm well aware of the limitations of UWP/Creators Program, and I do intend to do a "proper" release if I ever actually make anything worth releasing.

My goal at this point is just to be able to test my game on the actual hardware. To get a feel for how it plays and to see how the game deals with stuff like pausing, swapping between games & other console-specific stuff, as well as give testers a way to install the game without having to mess with developer settings on their console. And for that kind of experimentation, the "DIY" approach through the Creators Program is just a lot easier & faster (not to mention more cost-effective).

In any case, it doesn't look like that's gonna be possible with Godot.

> UWP is also on the verge of being formally deprecated, so nobody is really motivated to fix it.

Ah, that explains some things. I wonder if, when it's formally deprecated, there will be a replacement for the Creators Program because today it still specifically requires UWP.. Guess we'll have to wait and see!


I'll leave this issue open for now but feel free to close it if/when UWP support in Godot is officially dropped.

**Comment by wkubiak** [comment]
I can confirm that UWP has been deprecated for new releases on Xbox for close to a year now. Creators Program still exists. My guess is that they don't want to drop all the games which have been already published via CP, but at some point they might disable new submissions.

@woubuc I don't think the Xbox Creators Program should be used as a form of public alpha/beta test release for people to test how a game plays on the console.

**Comment by akien-mga** [comment]
Fixed by #64778.
