### ISSUE TITLE
Remove step in the particle default so it uses the default of the editor instead

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#64504]
### Godot version

v4.0.alpha.custom_build [2e24b7653]

### System information

Linux Fedora, Radeon RX 590

### Issue description

Setting a different float step setting for the editor has no effect on particle materials.
This can make it really really difficult to fine tune small-scale effects.

### Steps to reproduce

Make a particle system, change damping, change editor setting for float precision, observe that damping still has a step of 0.1.

**Comment by Calinou** [comment]
The more I think about it, the more I fail to see any concrete use cases for `default_float_step`. Instead, every property should have a small enough step to cover every reasonable use case. This is what we end up doing anyway :slightly_smiling_face:
