### ISSUE TITLE
Inherited methods not working on iOS export (for example .tr())

### ISSUE THREAD

**Issue by DavidMag** [godotengine/godot#64508]
### Godot version

4.0.alpha14

### System information

MacOS Monterey 12.5, MacBook Pro 16" (intel), Forward Mobile

### Issue description

When trying to use translations I get an error message when using exported iOS-app, works fine in editor.
This only occurs when setting text to text keys through code.

```
2022-08-16 22:03:51.347594+0200 Godot_Ios_Issues[89078:6541997] USER SCRIPT ERROR: Parse Error: Function "tr()" not found in base self.
r: Function "tr()" not found in base self.
USER SCRIPT ERROR: Parse Error: Function "tr()" not found in base self.
   at: GDScript::reload (res://label.gd:6) - Parse Error: Function "tr()" not found in base self.
````

### Steps to reproduce

set text to a text key, export to iOS.

`label.text = "MY_TEXT_KEY"`

### Minimal reproduction project

To avoid the size from getting to big I won't include an export but just say the word and I will provide that as well.
[godot_ios_issues_tr.zip](https://github.com/godotengine/godot/files/9354274/godot_ios_issues_tr.zip)

**Comment by DavidMag** [comment]
Ping @Calinou 

**Additional information and screenshots**
Noticed that I get the same issue when trying to use `has_method()` so probably affects all or some inherited methods in some manner.

**First label set through the editor:**
<img width="273" alt="image" src="https://user-images.githubusercontent.com/22000931/185110940-d083e18f-b3fd-4d9c-bd56-f1317e39ba80.png">

**Others are set by following scripts:**

```gdscript
extends Label

func _ready() -> void:
	text = "tr - %s" % tr("TEXT_KEY_2")
```

```gdscript
extends Label

func _ready() -> void:
	text = "has_method(\"update\") == %s" % has_method("update")
```

```gdscript
extends Label

func _ready() -> void:
	text = "self.tr - %s" % self.tr("TEXT_KEY_2")
```

```gdscript
extends Label

func _ready() -> void:
	text = "self.has_method(\"update\") == %s" % self.has_method("update")
```

```gdscript
extends Label

func _ready() -> void:
	text = "super.tr - %s" % super.tr("TEXT_KEY_2")
```

```gdscript
extends Label

func _ready() -> void:
	text = "super.has_method(\"update\") == %s" % super.has_method("update")
```

**Running from Godot editor:**
<img width="624" alt="Screenshot 2022-08-17 at 13 23 11" src="https://user-images.githubusercontent.com/22000931/185121838-48475a58-6f0b-473f-8406-0db5fb2213f1.png">

**Running macOS export:**
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/22000931/185121948-edd332d7-0020-451e-a83b-49ae0325a97c.png">

**Running iOS export:** (Swedish because my phone has Swedish as language)
![image](https://user-images.githubusercontent.com/22000931/185122080-c438b6a8-19ed-49b3-86ef-8a77d0eb1b13.png)


**Interesting log snippets from Xcode:**

```
2022-08-17 13:25:02.999154+0200 Godot_Ios_Issues[93894:6888987]    at: _ready (res://Label5.gd:4) - Invalid call. Nonexistent function 'has_method' in base 'Label ()'.
USER SCRIPT ERROR: Invalid call. Nonexistent function 'has_method' in base 'Label ()'.
   at: _ready (res://Label5.gd:4) - Invalid call. Nonexistent function 'has_method' in base 'Label ()'.
```

```
USER SCRIPT ERROR: Parse Error: Function "has_method()" not found in base Label.
   at: GDScript::reload (res://Label7.gd:4) - Parse Error: Function "has_method()" not found in base Label.
 Invalid call. Nonexistent function 'has_method' in base 'Label ()'.
```

```
2022-08-17 13:25:01.765734+0200 Godot_Ios_Issues[93894:6888987]    at: bind_methodfi (core/object/class_db.cpp:1291) - Condition "has_method(instance_type, mdname)" is true. Returning: nullptr
   at: bind_methodfi (core/object/class_db.cpp:1291) - Condition "has_method(instance_type, mdname)" is true. Returning: nullptr
b.cpp:1291) - Condition "has_method(instance_type, mdname)" is true. Returning: nullptr
   at: bind_methodfi (core/object/class_db.cpp:1291) - Condition "has_method(instance_type, mdname)" is true. Returning: nullptr
69328+0200 Godot_Ios_Issues[93894:6888987]    at: bind_methodfi (core/object/class_db.cpp:1291) - Condition "has_method(instance_type, mdname)" is true. Returning: nullptr
   at: bind_methodfi (core/object/class_db.cpp:1291) - Condition "has_method(instance_type, mdname)" is true. Returning: nullptr
```

**Full Xcode log:**
[full_xcode_log.log](https://github.com/godotengine/godot/files/9359489/full_xcode_log.log)

**Comment by DavidMag** [comment]
> Haven't tested this theory yet but I never had issues with methods like add_child() or such so seems to only affect methods inherited from Object

Regarding this, I tested to add `get_path()` and `get_parent().name` and it works fine so could be something there

**scripts:**
```
extends Label

func _ready() -> void:
	text = get_path()
```

```
extends Label

func _ready() -> void:
	text = get_parent().name
```

**Screenshot from Godot editor:**
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/22000931/185150484-2b035a5e-9917-410b-9b54-1c5ecafe5bf6.png">

**Screenshot from macOS export:**
<img width="1894" alt="image" src="https://user-images.githubusercontent.com/22000931/185151167-ece6e487-7b4f-4cf8-ae76-52e07bcea669.png">

**Screenshot from iOS export:**
![image](https://user-images.githubusercontent.com/22000931/185151550-758d0d00-f328-44a9-992b-8271a4bf2114.png)

**Comment by vnen** [comment]
It's probably the same as #63089, I can't reproduce the issue.
