### ISSUE TITLE
Suggestion:  Material sphere display as option

### ISSUE THREAD

**Issue by 1000h** [godotengine/godot#6450]
When editing a material in the visual editor, there is no button to hide the sphere.  This causes there to be a very limited amount of space to view parameters of the material and is really annoying.

**Comment by bojidar-bg** [comment]
I think this is a dupilicate of #6542 (I prefer closing this one, since the other has way more publicity), am I correct?

**Comment by Noshyaar** [comment]
Closing/Moving to #6542, also the issue is still relevant in 9ad1800 3.1 master
