### ISSUE TITLE
Vulkan Clustered: BaseMaterial3D Alpha Transparency has no effect on alpha scissor textures, regardless of MSAA level

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#64501]
*Related to https://github.com/godotengine/godot/issues/64500.*

### Godot version

4.0.alpha14 (could be reproduced as early as 4.0.alpha5, but not in 4.0.alpha4)

### System information

Fedora 36, GeForce GTX 1080 (NVIDIA 515.57)

### Issue description

There is a very subtle effect on alpha hash materials (most noticeably with the Clip blend mode), but alpha scissor materials don't seem to be affected in any way.

This can be reproduced only with the Vulkan Clustered backend. **When using Vulkan Mobile, alpha antialiasing works** regardless of the MSAA level chosen (although it'll look slightly different depending on MSAA level). Note that alpha-to-coverage isn't expected to work with the OpenGL renderer, as GLES 3.0 doesn't feature an API to enable it.

It's also interesting to note that even when using Vulkan Clustered, alpha-to-coverage seems to have an effect in the 3D material preview in the inspector.

I remember alpha-to-coverage working in Vulkan Clustered back when https://github.com/godotengine/godot/pull/40364 was just merged.

cc @marstaik 

*The images below have been scaled 200% with nearest-neighbor filtering for easier comparison. Click to view at full size.*

No MSAA | 2× MSAA
-|-
![2022-08-16_16 42 24_msaa_disabled](https://user-images.githubusercontent.com/180032/184909274-2d771d23-bed3-4785-8393-6d56fc1b9e0f.png) | ![2022-08-16_16 42 14_msaa_2x](https://user-images.githubusercontent.com/180032/184909270-43ee067d-33c3-4dfe-9e44-274f1cf73fd1.png)

4× MSAA | 8× MSAA
-|-
![2022-08-16_16 41 32_msaa_4x](https://user-images.githubusercontent.com/180032/184909257-47ff172f-5893-4d61-ab49-4dd6a3d02741.png) | ![2022-08-16_16 42 34_msaa_8x](https://user-images.githubusercontent.com/180032/184909276-38fe197c-2e04-4b9d-b5db-424610240d7e.png)

### Steps to reproduce

- Add a MeshInstance3D with a BoxMesh.
- Assign a new StandardMaterial3D to the BoxMesh.
- Set the material's transparency mode to Alpha Scissor, with the alpha antialiasing mode set to Alpha Edge Blend.
- Add a NoiseTexture as the material's albedo texture, with FastNoise resource and a color ramp that sets its low values to be fully transparent.

### Minimal reproduction project

[test_alpha_to_coverage.zip](https://github.com/godotengine/godot/files/9352081/test_alpha_to_coverage.zip)

**Comment by Calinou** [comment]
I bisected the issue to 30a89b3f98d5a7cb3b5b037b5aa1f58b6e2d7455. cc @Ansraer

**Comment by Ansraer** [comment]
I am still on vacation and dont have access to a gpu right now. Can't think of any reason why my PR would have broken MSAA, so I will have to to investigate more once I am back home.

Just to clarify, this bug only occurs on vulkan clustered outside the editor?

**Comment by Calinou** [comment]
> Just to clarify, this bug only occurs on vulkan clustered outside the editor?

It occurs in the editor too, but only in Vulkan Clustered.
