### ISSUE TITLE
Particle billboarding shader uses the x scale for both x and y

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#64505]
### Godot version

v4.0.alpha.custom_build [2e24b7653]

### System information

Linux Fedora, Radeon RX 590

### Issue description

This code
```
mat4 mat_world = mat4(normalize(INV_VIEW_MATRIX[0]) * length(MODEL_MATRIX[0]), normalize(INV_VIEW_MATRIX[1]) * length(MODEL_MATRIX[0]),normalize(INV_VIEW_MATRIX[2]) * length(MODEL_MATRIX[2]), MODEL_MATRIX[3]);
```
Should be changed to:
```

	mat4 mat_world = mat4(normalize(INV_VIEW_MATRIX[0]) * length(MODEL_MATRIX[0]), normalize(INV_VIEW_MATRIX[1]) * length(MODEL_MATRIX[1]),normalize(INV_VIEW_MATRIX[2]) * length(MODEL_MATRIX[2]), MODEL_MATRIX[3]);
```

Note the second length uses MODEL_MATRIX[1] instead of 0.

### Steps to reproduce

Use a XYZ scale curve on a particle system

**Comment by YuriSizov** [comment]
I'll mark it as a good first issue I guess, since the OP has the solution right in there. But maybe @QbieShay you want an easy PR under your belt? 😛

**Comment by smartyc30** [comment]
Hi, I am a first time contributor, and I'd like to take care of this issue for you guys if it's still open.

**Comment by YuriSizov** [comment]
@smartyc30 There is actually a PR open now, as of yesterday. Sorry!
