### ISSUE TITLE
Skipping duplicate build file in Copy Bundle Resources build phase: XX/en.lproj/InfoPlist.strings

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#64516]
### Godot version

3.5

### System information

Mac

### Issue description

When multiple translation files add, the exported iOS has duplicated build file
![11111111](https://user-images.githubusercontent.com/1130047/185013097-6a382007-0ca2-499f-add8-3fbc7135138b.jpg)
![22222222](https://user-images.githubusercontent.com/1130047/185013113-6773dee4-2b8b-4f30-a45b-408744c7e215.jpg)

### Steps to reproduce

multiple translation files
export iOS project
build 
 warning:

Showing Recent Messages
Skipping duplicate build file in Copy Bundle Resources build phase: XXXXXXXX/en.lproj/InfoPlist.strings

**Comment by Calinou** [comment]
The entries should be merged together, as it's valid to have several translation files per language (usually to split them into more manageable components).

cc @bruvzg
