### ISSUE TITLE
Renaming a node by doubleclicking on it is buggy

### ISSUE THREAD

**Issue by TotCac** [godotengine/godot#6452]
**Operating system or device - Godot version:**
Godot last GIT build
Windows 7 64bit

**Issue description** (what happened, and what was expected):
Troubles while trying to rename a node by double-clicking on it. It's seems buggy because working randomly

**Steps to reproduce:**
Add a node, then double click on it to rename it. Not working 100% times

**Link to minimal example project** (optional but very welcome):

**Comment by Sslaxx** [comment]
Whilst it doesn't fix the issue, selecting a node and then pressing F2 will allow you to rename it.

**Comment by gau-veldt** [comment]
I can confirm I get this issue also in x11 using 2.2a

**Comment by gau-veldt** [comment]
PS: It might be good to include rename in the RMB drop-down for good measure.

**Comment by bojidar-bg** [comment]
Probably the issue is related to the editor considering the double-click as a drag + drag, adrag + click, or a click + drag.

**Comment by volzhs** [comment]
as my experience, double click has about 1 second term would enable rename field.
a little bit faster than 1 second, it focus to selected.
a little bit slower than 1 second, does nothing.
it would be good to enable rename if double click label, and focus it when double click node icon, IMO.

**Comment by djrm** [comment]
i guess this may be confusing because if you click an item, and wait more than 800ms then the count restarts so you have to double click the selected element in an interval from 400ms to 800ms maybe increasing the edit interval to 400ms to 1s

**Comment by RebelliousX** [comment]
This still is not fixed for me. I need to "triple" click a node to rename it!! How come?!

**Comment by vnen** [comment]
@RebelliousX Works fine for me in the current master. Are you sure your build was made after the fix?

**Comment by RebelliousX** [comment]
@vnen Hmm, interesting, I pulled the changes before building, I will pull from master and rebuild.
