### ISSUE TITLE
Scrolling outside Popup areas makes it disappear

### ISSUE THREAD

**Issue by floydnunez** [godotengine/godot#6453]
Mac OSX El Capitan, Godot v2.1.stable.official

I have a Button marked as a toggle, to show and hide a Popup. I connected its "togged(bool pressed)" event to a script on the Popup, that uses "hide()" and "show()" to do the actual job.

<img width="464" alt="screen shot 2016-09-11 at 10 48 10" src="https://cloud.githubusercontent.com/assets/1719570/18417683/4943b0d2-780d-11e6-9831-0c30a69be66c.png">
<img width="378" alt="screen shot 2016-09-11 at 10 42 37" src="https://cloud.githubusercontent.com/assets/1719570/18417660/9273e2f0-780c-11e6-8630-6a5875caef29.png">

This works as expected, except that if I scroll over the button with my touchpad (aka dragging two fingers on it) or using the scroll wheel on my mouse, the Popup disappears. The debugger says that the Popup loses its visibility. It is not moved around, and using the debugger to make it visible again fixes it until the scroll is done again. The code in the button is not being triggered (the 'unpressed! hiding!' message doesn't show up).

I think it is not about the button specifically. Replacing the code with a toggle that depends on a variable and instead using the button's pressed method does nothing to fix it. Also it seems that scrolling over some other areas of the screen hides the popup as well. But my minimal example uses a button to show the popup. The Popup documentation doesn't mention anything about this behavior. It doesn't work the other way either: scrolling doesn't make the popup visible.

Checking the "Exclusive mode" option on the Popup inspector seems to fix it as well (scroll won't make the Popup disappear), but at least on my example it prevents pressing the button again without using the enter key (the mouse won't function to press the mouse) which is odd too.

[demo_bug.zip](https://github.com/godotengine/godot/files/466017/demo_bug.zip)

I include the example project.

Do note that including a ScrollContainer on the Popup still lets the ScrollContainer to scroll correctly, when scrolling OVER it. It is only when scrolling outside the Popup that this happens

<img width="661" alt="screen shot 2016-09-11 at 11 11 41" src="https://cloud.githubusercontent.com/assets/1719570/18417812/91de0ab0-7810-11e6-9d4c-a23a80fc63ae.png">

[demo_bug_with_scroll.zip](https://github.com/godotengine/godot/files/466021/demo_bug_with_scroll.zip)

**Comment by RayKoopa** [comment]
Yep, the editor "suffers" from the same issue. If you scroll outside of popups, they disappear. Editor has this with the settings windows, scrolling outside of them closes them.

**Comment by Noshyaar** [comment]
Still reproducible/relevant in 3.1 master 9ad1800 : scrolling outside popup makes it disappear
