### ISSUE TITLE
C# project generated as .NET Framework 4.7.2 project?

### ISSUE THREAD

**Issue by Clonkex** [godotengine/godot#64558]
### Godot version

3.5.stable.mono.official [991bb6ac7]

### System information

Windows 10, GLES3

### Issue description

[The documentation](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_basics.html) says C# support is implemented using Mono 6.x with full support for C# 8.0. However, when I create a new C# script the resulting auto-generated Visual Studio project is set up for .NET Framework 4.7.2. I don't understand why this is and I'm not sure how to get around it.

Am I missing something? I'm fairly new to Godot but not new to C#. I want my C# 8.0 features! 🙂 

### Steps to reproduce

- Create a new Godot project
- Set the external editor to Visual Studio
- Create a new C# script
- Open the generated Visual Studio solution. The project will be a .NET Framework project configured for .NET 4.7.2.

**Comment by Calinou** [comment]
> I'm fairly new to Godot but not new to C#. I want my C# 8.0 features! 

While some C# 8.0 language features are supported, full C# 8.0 support won't be available in Godot 3.x. It'll only come in 4.0 thanks to the [move to .NET 6](https://github.com/godotengine/godot/pull/64089).
