### ISSUE TITLE
Instance loses it's "Editable children" flag after renaming. Affects saved edits too

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#6455]
Godot 2.2 alpha latest build, linux x86
Renaming an instance with "Editable children" makes it lose the flag.

**Comment by ArcFutahito** [comment]
After renaming my instances, labels that I edited inside them reverted back to instance default.

**Comment by Noshyaar** [comment]
Still reproducible/relevant in 3.1 master 9ad1800

**Comment by Calinou** [comment]
Closing in favor of #20409, which has more information about the issue at hand.
