### ISSUE TITLE
[3.5] FlowContainer resets size of child controls to zero when Expand is checked.

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#64556]
### Godot version

v3.5.stable.official [991bb6ac7]

### System information

Mac OS X (Catalina) 10.15.7

### Issue description

Both FlowContainers H or V will reset the corresponding X or Y size of child Controls to zero (E.g. TextureRect or TextureButton) if you check the Expand checkbox on the Controls.  Also the scale is reset.

Looks like Label is similar issue. If you size the Label manually then try to type text, it gets reset to text size.

### Steps to reproduce

1. Add CanvasLayer to a project
2. Add an HFlowContainer as a child
3. Add a TextureRect to the container and an image.
4. Click the Expand button. The size changes to zero erasing any settings that you may have done.

### Minimal reproduction project

[FlowContainer.zip](https://github.com/godotengine/godot/files/9367154/FlowContainer.zip)

**Comment by KoBeWi** [comment]
This is not a bug. BoxContainer, FlowContainer, CenterContainer ect. will by default shrink their child Controls to their minimum size. TextureRect and TextureButton with Expand enabled (Ignore Texture Size in 4.0) have 0 minimum size, so they are shrunk to nothing. You either need to set their minimum size manually or enable `Expand` under `Size Flags` category.

Also Containers will set the position/size/scale/rotation of the underlying controls automatically, hence the reset.
