### ISSUE TITLE
Disabling warnings for GDScript does not work

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#64559]
### Godot version

dbd15243621ec595742b18abc4c26f3cb2e00f3d

### System information

Windows 11

### Issue description

Warnings appearing regardless of the state of that flag:

![image](https://user-images.githubusercontent.com/3036176/185299371-f5fecbb7-e013-4eae-9dfd-792e7caf5dc0.png)

### Steps to reproduce

- Create a new project with default scene
- Attach a default script:

```
extends Node3D


# Called when the node enters the scene tree for the first time.
func _ready():
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	pass

```

- Try to disable that option and run the debugging.

### Minimal reproduction project

Too easy to reproduce even with default script

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/56592.
