### ISSUE TITLE
Invalid target platform "javascript"

### ISSUE THREAD

**Issue by zzyYesimola** [godotengine/godot#64567]
### Godot version

3.5

### System information

Windows Server 2019, NVIDIA GeForce GTX 1650, Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz

### Issue description

Command Line:

D:\Desktop\Dev\Godot\> scons platform=javascript tools=no target=release javascript_eval=no
scons: Reading SConscript files ...
Invalid target platform "javascript".
The following platforms were detected:

        windows

Please run SCons again and select a valid platform: platform=<string>

--------------------------
I tried to **reinstall everything**, but it doesn't work.

Translate by Google

### Steps to reproduce

scons platform=javascript tools=no target=release javascript_eval=no

**Comment by Calinou** [comment]
Please don't ask support questions here, as this issue tracker is meant to be used for bug reports only. Use one of the other [community channels](https://godotengine.org/community) instead.

**Comment by Disa-Kizonda** [comment]
> Please don't ask support questions here, as this issue tracker is meant to be used for bug reports only. Use one of the other [community channels](https://godotengine.org/community) instead.

🤓

**Comment by akien-mga** [comment]
@Disa-Kizonda Please don't bump 2 year old closed issues to provide no useful information, that's inappropriate (and spams a lot of users who watch the issue tracker).

**Comment by Disa-Kizonda** [comment]
lol
