### ISSUE TITLE
"Show in File Manager" from context menu does nothing if path contains a `#` character

### ISSUE THREAD

**Issue by Avtem** [godotengine/godot#64568]
### Godot version

v3.5.stable.official [991bb6ac7]

### System information

Windows 7 x64 SP1, Intel(R) HD Graphics 4000

### Issue description

**Show in File Manager** menu does nothing (expected behavior is to open that file in explorer.exe).
So, after i started recording video to show how to reproduce the bug, the bug actually didn't happen and i almost immediately found the cause. On my computer i have thousands folders that start with `#` in their name. And **Show in File Manager** menu does nothing if project path contains '#' character. (please watch the video that proves it)

It would be really nice if Godot would be able to support all possible folder names that Windows user can create. That is literally any unicode character except `\ / : * ? " < > | ` like Chinese characters or characters like ♥ , ⁇

### Steps to reproduce

- Create a new project **in a path that has '#' in it**
- In **FileSystem** dock right-click **Icon.png** and choose **Show in File Manager**
- Nothing will happen

### Minimal reproduction project

[#bugissue.zip](https://github.com/godotengine/godot/files/9372444/bugissue.zip)
The project **must** contain '#' character in it. Otherwise bug won't happen.

https://user-images.githubusercontent.com/65607782/185373423-1ce67b19-e14f-4257-9c05-5a1c58545c0b.mp4

**Comment by KoBeWi** [comment]
Can't reproduce in 4.0 on Windows 10.
Can you check if it works for you in 4.0 alpha?

**Comment by giffi-dev** [comment]
Under linux (arch to be specific), using a '#' in front of a folder name caused for the project root folder to be opened instead of the folder in which the resource i right clicked was in.

https://user-images.githubusercontent.com/47903526/185393218-270f6430-0484-43e6-8476-1c8d6bbd7c00.mp4

**Comment by Avtem** [comment]
> Can't reproduce in 4.0 on Windows 10. Can you check if it works for you in 4.0 alpha?

Godot_v4.0-alpha13_win64 doesn't launch at all:

Your video card driver does not support any of the supported Vulkan or OpenGL versions.
Please update your drivers or if you have a very old or integrated GPU upgrade it.

**Comment by Calinou** [comment]
> My integrated GPU: Intel(R) HD Graphics 4000

This IGP doesn't have Vulkan support, but you can force Godot 4.0 to run using the `--rendering-driver opengl3` [command line](https://docs.godotengine.org/en/stable/tutorials/editor/command_line_tutorial.html) argument. Note that you'll need to open an existing project directly as the command line argument isn't passed from the project manager to the editor.

**Comment by Avtem** [comment]
Tried to launch with command line `Godot_v4.0-alpha13_win64.exe --rendering-driver opengl3 project.godot`, but it almost instantly crashes

**Comment by Calinou** [comment]
Try 4.0.alpha14 – the OpenGL renderer was broken in 4.0.alpha13.

**Comment by kleonc** [comment]
Most of the commands like "Show in File Manager" run something like:
```cpp
OS::get_singleton()->shell_open(String("file://") + path);
```
and the issue is it's not always working. Simple test (Windows) after creating directory `C:/#Test/`:
```gdscript
@tool
extends EditorScript

func _run():
	# These don't work:
#	OS.shell_open("file://C:/#Test/") # That's what engine would trigger.
#	OS.shell_open("file://C:/%23Test/")
#	OS.shell_open("file:///C:/#Test/")

	# These work:
#	OS.shell_open("C:/#Test/")
#	OS.shell_open("file:///C:/%23Test/")
```
