### ISSUE TITLE
Scene Importer can't specify scene file format when first imported.

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#6456]
I'm importing scene and I can only import it as .scn when I want .tscn.

**Comment by lordadamson** [comment]
may I ask what is a .tscn file?

**Comment by n-pigeon** [comment]
@lordadamson
It's like scn but human readable text based scene file format, it is meant to replace xml and xscn.

**Comment by reduz** [comment]
you don't want .tscn because 3D data as text is huge and takes a lot to
load.

**Comment by n-pigeon** [comment]
@reduz Thx for clarification. I take it :)
