### ISSUE TITLE
Inverse Kinematics gets wild when Speed param is above 1 [+test file]

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#6457]
I've made simple rig to test InverseKinematics node.

Changed params:
- Iterations to 1 (default 100 was insanely slow, probably should be changed)
- Speed to 2 (default 0.2)

Problem exists on Ik Bone, when Speed is above 1 it starts to shake a lot.

Test file: 
[IK_Demo.zip](https://github.com/godotengine/godot/files/466222/IK_Demo.zip)

PS
Other noticed problems is that Skeleton Node doesn't display last bone in chain but I will add separate issue for that.

**Comment by n-pigeon** [comment]
I this Iterations param even needed?

**Comment by akien-mga** [comment]
The IK module was contributed by @slapin, but not thoroughly review back then and not much tested either (at least judging by community discussions or issues). So there might be room from improvement, PRs welcome :)

**Comment by songproducer** [comment]
Disabling the last bone stops the flickering

**Comment by slapin** [comment]
Iterations parameter indicates iterations per step, speed indicates
adaption per iteration. when speed is too high, it will start to oscillate
as it is harder to stabilize.
The rom for improvement lies in angle constraints in IK and pole target.

**Comment by songproducer** [comment]
@slapin Thanks for the explanations, I was just wondering about the iterations parameter.

When I run the project I get a lot of errors:
Index p_bone out of size (bones.size())

Do you have any ideas how to fix this?

**Comment by songproducer** [comment]
Just worked it out - the last bone in the tree can't be used in the IK node, so I created a leaf bone.

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by n-pigeon** [comment]
Yes :)

**Comment by akien-mga** [comment]
The IK module was dropped in 3.0, so this is no longer applicable.
