### ISSUE TITLE
[3D] Severe lag when running a scene with shadow resolution of 16384 and WorldEnvironment, yet the editor is fine.

### ISSUE THREAD

**Issue by Y-VRN** [godotengine/godot#64582]
### Godot version

3.5.stable.official (991bb6ac7)

### System information

Windows 10 Home 21H1, Intel Core i5-8250U, GLES3, NVIDIA GeForce MX130, 8GB RAM and 2GB VRAM

### Issue description

I expect the game to run just as fast as the editor's preview.

https://user-images.githubusercontent.com/97438474/185447763-9a22bd8f-de56-45ea-ad1f-4ee549f1dbc9.mp4
*(i messed up the recording, whoops)*

Running a scene with a shadow resolution of 16384 causes FPS to drop to 30 or below, with slow load times (splash screen is skipped sometimes) and the possibility of actually crashing the editor (not always). This also causes background sounds (e.g. music from a web browser) to distort, although that could be due to the fact I have other processes running. GPU would max to 100%, or stutter from 0 to 100 and vice versa (perhaps readying the scene for one frame was having issues). Apparently, WorldEnvironment increases the lag as well. The most severe I got was the game would run even less than 1 FPS, and then speed up to 30-60 for a minimum of 1 second.

All these occurrences do not show up in the editor. The editor only uses 50-70%.

Reducing shadow resolution to 8192 still causes noticeable, but lesser lag. 

The scene in which this occurred was very simple: flat materials (only albedo) WorldEnvironment with SSAO, bloom, and procedural sky, a controllable character, a large platform to walk on, and some obstacles for physics testing.

Attempting to change DirectionalLight from Optimized to Stable does not help. Setting Shader Compilation Mode in Project Settings to Async + Cache did nothing either. Even removing my character did no help. Setting the resolution is the only solution, but I don't find it acceptable.

### Steps to reproduce

Preparing an empty baseplate with a bunch of objects and one DirectionalLight should already be sufficient.

Set the shadow resolution to 16384, or higher if the editor still hasn't stuttered.

WorldEnvironment also increases lag too, perhaps with Bloom, Procedural Sky, and SSAO (heaviest effect).

To much better visualize, have a controllable camera or a fast day/night cycle (using DirectionalLight).

Try running the game.

### Minimal reproduction project

This is the simplest I could get the lag to show: A baseplate, a bunch of cubes for showing shadows, a spinning DirectionalLight (day/night cycle), and shadow resolution at 16384. The key to seeing the lag is to have a high-resolution shadow, still enough to be fast in the editor, but slow enough to cause problems when running the project.

[GD 3.5 MRP 1 8.19.2022.zip](https://github.com/godotengine/godot/files/9376153/GD.3.5.MRP.1.8.19.2022.zip)

**Comment by Calinou** [comment]
You are likely running out of VRAM by having *two* Godot instances run with very high shadow settings at the same time.
