### ISSUE TITLE
Skeleton Node doesn't display last bone in chain

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#6458]
As in title.

Test file: 
[IK_Demo.zip](https://github.com/godotengine/godot/files/466223/IK_Demo.zip)

**Comment by AndreaCatania** [comment]
I've tested it with a mixamo skeleton and it has the same problem.

**Comment by n-pigeon** [comment]
Ups I think it might be not a bug just missing leaf bones ^^'
