### ISSUE TITLE
Intellisense Issues with Arrays

### ISSUE THREAD

**Issue by RefinedSoftwareLLC** [godotengine/godot#646]
Intellisense should automatically detect if a variable is an array. This could be done by finding the "var label = []" line and if it is set to an array or empty array assume it is always an array.

When typing an array out it should display Intellisense options as follows {Intellisense popup in curly brackets}...

    var label = [] #previously somewhere else in code
    lab
    { label }
    label
    { no intellisense popup }
    label. 
    {
    # on the following lines show argument summeries in Intellisense popup but when selected do not copy what is between the () to code. Also place cursor between ().
    .append(var value)
    .clear()
    .empty()
    .erase(var value)
    .find(var value) # returns int
    # on previous line show the comment in Intellisense popup but when selected do not copy the comment to code.
    .hash() # returns int
    # on previous line show the comment in Intellisense popup but when selected do not copy the comment to code.
    .insert(int pos, var value)
    .invert()
    .push_back(var value)
    .remove(int pos)
    .resize(int pos)
    .size() # returns int
    # on previous line show the comment in Intellisense popup but when selected do not copy the comment to code.
    .sort()
    .sort_custom(Object obj, String func)
    .Array(...)
    # replace argument summery with ... when documentation should be referenced.
    }

**Comment by akien-mga** [comment]
This has actually been implemented already in 1.1 I believe.
