### ISSUE TITLE
Inverse Kinematics feature "Pole Target"

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#6460]
Would be great if IK Node supported "Pole Target" Spatial node that tells IK Solver in which direction it should bend.

Blender IK Constraint can be used for reference.

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by n-pigeon** [comment]
Yes :)

**Comment by akien-mga** [comment]
The IK module was dropped in 3.0, so this is no longer applicable.
