### ISSUE TITLE
Button group signal "pressed" not triggered

### ISSUE THREAD

**Issue by floppyhammer** [godotengine/godot#64604]
### Godot version

v3.5.stable.official [991bb6ac7]

### System information

Windows 11, GLES3

### Issue description

Button group signal "pressed" cannot be triggered when any button in the group is pressed.

### Steps to reproduce

Add some buttons to a button group, connect the "pressed" signal, click any button in the group.

### Minimal reproduction project

[Uploading ButtonGroupSignal.zip…]()

**Comment by floppyhammer** [comment]
What's wrong with Github? I can't upload the test project even when I'm on another computer.
<img width="309" alt="image" src="https://user-images.githubusercontent.com/28705694/185550580-3ede511e-25e7-4913-b504-5abde6088d00.png">

**Comment by kleonc** [comment]
I'd guess your buttons are not toggleable? Seems like `ButtonGroup` works only for toggleable buttons:
https://github.com/godotengine/godot/blob/35cfaafda8073f700c9d2fe42a43d3d81eaaea67/doc/classes/ButtonGroup.xml#L6-L9

I guess this signal should be called something like `toggled_on` in the first place to avoid confusion... or just `toggled` and be also emitted for the button being toggled off. But this can't be changed in 3.x, it would break compatibility. However maybe `ButtonGroup` could be changed/improved in 4.0? :thinking:

**Comment by floppyhammer** [comment]
@kleonc You're right. Making all member buttons togglable does work. Is there any reason for all member buttons to be togglable? I don't see an obvious reason for this limitation.

**Comment by kleonc** [comment]
> Is there any reason for all member buttons to be togglable?

I can be only guessing, seems like it was simply made specifically for radio buttons (only one button in a group can be pressed at once).

> I don't see an obvious reason for this limitation.

Same, it's rather a design choice. I think potential changes are a subject for a [proposal](https://github.com/godotengine/godot-proposals) though. `ButtonGroup` seems to work as intended (whether we like it or not).

**Comment by KoBeWi** [comment]
This is already documented.

>Group of [Button]. All direct and indirect children buttons become radios. Only one allows being pressed.[member [BaseButton.toggle_mode] should be [code]true[/code].
