### ISSUE TITLE
The alternative tile popup menu can't be opened

### ISSUE THREAD

**Issue by MinusKube** [godotengine/godot#64600]
### Godot version

v4.0.alpha.custom_build [2e24b76535dceb9cf18ab8ece3304ed92948c1b5]

### System information

Windows 10

### Issue description

The alternative tile popup menu is not openable anymore, when you right click on an alternative tile inside a TileSet, nothing happens.

### Steps to reproduce

1. Create a tile set
2. Create an alternative tile
3. Right click on the alternative tile

**Comment by blipk** [comment]
Can confirm this issue as well on standard v4.0alpha14 and 13.
I thought there was just no way to delete them.
