### ISSUE TITLE
Scene Hierarchy Panel cropped when selecting a Tilemap Node

### ISSUE THREAD

**Issue by diegomachado** [godotengine/godot#6461]
**Operating system or device - Godot version:**
Macbook Pro Retina 13 - El Capitain 10.11.6
Godot 2.1

**Issue description** (what happened, and what was expected):
When selecting a Tilemap node, the Scene view splits into 2 panels: 1 to select the tile and 1 to show the scene. Creating this Tiles Panel 'pushes' the Scene Hierarchy Panel (along with Inspector Panel) to the right, off-screen. Also, I can't resize back to what it was, like the tilemap editor has a minimum width that it has to respect.

It's expected not to be pushed / resized and be able to resize the panel.

I've took a screenshot to show how it looks on my notebook:
http://imgur.com/CUJfu1O

**Steps to reproduce:**
Open any project with a Tilemap and select the Tilemap node.

**Link to minimal example project** (optional but very welcome):
I'm using the Kinematic Character Demo

**Comment by diegomachado** [comment]
Just tested the same version of Godot on my friend's MacBook that is the same model and OS version of mine and this bug does not occur. 

I will investigate further to see if there are other apps managing the screen. 
Any other tips on what it may be, please let me know.

**Comment by diegomachado** [comment]
Ok, I figured this out. This only occurs when I select the Tilemap Node and the Animation Panel is open. (as shown in my screenshot)

Should I change the issue title?

**Comment by bojidar-bg** [comment]
Some screens from #6879 and #7178 (without needlessly mentioning their authors):

![](https://cloud.githubusercontent.com/assets/12082018/20577371/3f8472a4-b1c2-11e6-9543-2a2d86fbdf79.png)

![](https://cloud.githubusercontent.com/assets/10428035/19617915/3ddfbf18-981c-11e6-9e07-2f44a57037b1.png)

**Comment by HassanHeydariNasab** [comment]
I have a 4:3 monitor. there isn't any problem on v2.1 but I have same problem on v2.1.3 and v3
