### ISSUE TITLE
Area only work with Box collision shape

### ISSUE THREAD

**Issue by CristianoSimao** [godotengine/godot#64615]
### Godot version

3.5

### System information

Linux Fedora 35 - CPU AMD Ryzen 3 2200 G - GLES2

### Issue description

The Area node should display a error if the user add a collision shape that is not the type box informing that other types like concave or trimesh will not work.
I spend various hours to discover this.

### Steps to reproduce

1 - add a Area node
2 - add a Trimesh or convave mesh as collision shape
3 - try detect the body_entered function
4 - only will work if use Box collision shape

**Comment by skyace65** [comment]
Please provide a minimal reproduction project. I have created one and Area works with a ShpereShape3D.
[AreaTest.zip](https://github.com/godotengine/godot/files/9383298/AreaTest.zip)

**Comment by CristianoSimao** [comment]
When generate a collision Trimesh from a simple cube or concave collision from a imported model from Blender, this will not work.
Here are the test files.
Test and will not work. Change the collision to BOX and will work.
[TestArea.zip](https://github.com/godotengine/godot/files/9383806/TestArea.zip)

**Comment by skyace65** [comment]
Ok I see you opened this for 3.5, not 4.0. My confusion came from your PR being opened on the master branch. Regardless this isn't an accurate description of the issue. Area does not only work with box shape collision, convex shapes and other selectable shapes such as sphere do work.

**Comment by rburing** [comment]
Closing this in favor of https://github.com/godotengine/godot/issues/64588 which has a more accurate description.

See https://github.com/godotengine/godot/issues/64588#issuecomment-1223980207 for an explanation of the behavior.
