### ISSUE TITLE
[elf/linux] provide very old glibc in SDK

### ISSUE THREAD

**Issue by sylware** [godotengine/godot#64629]
### Godot version

master/main

### System information

elf/linux OSes

### Issue description

Sorry, I thought about this right after posting my last comment! :(

A much cheaper mitigation: in godot SDK, do provide a very old glibc, and make the build system link the game binaries against this one. Then, devs could use a modern distro to work and build on, and their binaries should be safe against the  planned obsolescence from GNU symbol/module versioning.

### Steps to reproduce

same than before: build game binaries on a recenc glibc/linux, try to run them on a older glibc/linux (~2years), won't work because of GNU symbol/module version.

**Comment by Calinou** [comment]
> in godot SDK, do provide a very old glibc,

This is already done in https://github.com/godotengine/build-containers.

**Comment by sylware** [comment]
well, for the self-compiled binaries, to have an already there and ready to link, really old, glibc could be a great quality of life improvement for devs.

Well, well, you are now aware of the core of the pb now (c++ and gcc/glibc devs, as always...). Maybe we'll achieve clean binary compatibilty in the near future if those devs do decide to behave.

Feel free to close the issue as you see fit.

**Comment by akien-mga** [comment]
We already provide SDKs that use an old glibc, see https://github.com/godotengine/buildroot/
