### ISSUE TITLE
`@GDScript` function names are highlighted when they shouldn't

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#64621]
### Godot version

4.0.alpha14

### System information

Ubuntu 20.04.3 LTS

### Issue description

![image](https://user-images.githubusercontent.com/85438892/185643677-9aeb688d-42c8-4a45-8a6a-bae76ee0f025.png)

This is allowed, although it does send a warning. Other function names do not trigger function highlighting until you add `(` after, even those of `@GlobalScope`, but those of `@GDScript` do.

### Steps to reproduce

Type `var str` in GDScript

### Minimal reproduction project

Too simple to send a project for

**Comment by Calinou** [comment]
Shouldn't global scope function names be reserved keywords anyway?

**Comment by MewPurPur** [comment]
I dunno, we could decide that this, instead, is the real issue. Global scope functions are not usable as callables, afaik.

**Comment by Mickeon** [comment]
They should not be reserved, I don't think. They cannot be passed as callables. But in this case specifically, even if GDScript encourages more explicit variable names, "str" is a fairly common shorthand used during String manipulations.
