### ISSUE TITLE
Using VR in the Godot 4.0 Alpha 14 build freezes/crashed Graphics Driver

### ISSUE THREAD

**Issue by MrEvilOnGitHub** [godotengine/godot#64633]
### Godot version

4.0 Alpha 14

### System information

Win11, Ryzen 3600x, RX 6600XT, Latest drivers (Adrenalin 22.8.1), HTC Vive system

### Issue description

Launching a minimal project to test VR on the Alpha caused the Graphics Drivers to first freeze and whitescreen, then they reset and the engine crashed

### Steps to reproduce

Launch the attached Project using the in-engine run button

### Minimal reproduction project

[Godot4.0Alpha14 VR Test.zip](https://github.com/godotengine/godot/files/9384293/Godot4.0Alpha14.VR.Test.zip)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/64584.
