### ISSUE TITLE
Vulkan: Directional LightmapGI does not look correct with emissive surface light

### ISSUE THREAD

**Issue by atirut-w** [godotengine/godot#64645]
### Godot version

v4.0.alpha14.official [106b68050]

### System information

N/A

### Issue description

When using lightmap GI, specular lobes and reflections looks broken for lights from emissive objects. May be related to #63016

Cornell box model from [McGuire CG Archive](https://casual-effects.com/g3d/data10/index.html#mesh5)

https://user-images.githubusercontent.com/25323231/185727307-09692f20-2ab1-469f-b617-3ce20207a238.mp4

### Steps to reproduce

1. Set up a static scene with everything having their UV2 unwrapped, and preferably with only lighting from emissive objects.
2. Add LightmapGI, enable directional mode and bake.

**Comment by Calinou** [comment]
LightmapGI directional mode only provides *rough* reflections – it's not designed to provide sharp reflections like ReflectionProbe.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/81556, which shows cases where directional lightmaps are broken and has a MRP available.

Regarding the lack of specular lobes for direct light, see https://github.com/godotengine/godot/issues/63016.
