### ISSUE TITLE
Lost icons after change editor layout

### ISSUE THREAD

**Issue by Geequlim** [godotengine/godot#6464]
**Operating system or device - Godot version:**

Godot 2.2 complied with latest commit
Platform:  Arch Linux x64

**Issue description** (what happened, and what was expected):
![ezgif-162447193](https://cloud.githubusercontent.com/assets/6964556/18436490/2df941b0-792b-11e6-83fa-14b794f34459.gif)

**Comment by akien-mga** [comment]
Does that happen with the default theme too, or only with custom ones?

**Comment by bojidar-bg** [comment]
Another example from @avril-gh:
![](https://cloud.githubusercontent.com/assets/3224132/19814324/0c3fbce8-9d3e-11e6-85ae-4556f10fdd33.gif)

@akien-mga I'd say, yes ^^

Also, related to #6302

**Comment by akien-mga** [comment]
Does this affect the 2.1 branch too, or only master?

**Comment by avril-gh** [comment]
@akien-mga 
looks like its only in master

@reduz 
According to my researches this bug is caused by commit  https://github.com/godotengine/godot/commit/1bf684cea274db7c58b3f62a77ad4de3980c14dc

**Comment by avril-gh** [comment]
https://github.com/godotengine/godot/pull/7145 fixes  https://github.com/godotengine/godot/issues/6464 , https://github.com/godotengine/godot/issues/6443 , https://github.com/godotengine/godot/issues/6302

tested as seen at images in https://github.com/godotengine/godot/pull/7145
