### ISSUE TITLE
LSP added empty insertText element to signals in 3.5

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot#64666]
### Godot version

3.5.stable

### System information

Linux 5.19.1-arch2-1

### Issue description

Given the following script:

```
extends Enemy
class_name Wolf

func die():
	print("die")
	tween.interpolate_property(self, "modulate", Color.white, Color.transparent, 1.0)
	yield(tween, "tween_al<cursor is here>
	tween.interpolate_property(get_parent(), "modulate", Color.white, Color.transparent, 1.0)
	tween.connect("tween_all_completed", get_tree(), "change_scene", ["res://menus/Victory.tscn"])
	tween.start()
```

The LSP offers the completion item "tween_all_completed". In 3.4, accepting this completion inserts the text "tween_all_completed". In 3.5, the same suggestion appears, but accepting it inserts empty text (erasing what you've typed so far)

I'm using neovim's builtin LSP client.

Here are the LSP logs: 
[34.log](https://github.com/godotengine/godot/files/9387831/34.log)
[35.log](https://github.com/godotengine/godot/files/9387830/35.log)

In 3.4, the LSP response looks like this:
```
{  data = "Tween::tween_all_completed",  kind = 23,  label = "tween_all_completed"}
```

In 3.5  the LSP response looks like this:

```
{  data = "Tween::tween_all_completed",  insertText = "",  kind = 23,  label = "tween_all_completed"}
```

I suspect that if insertText is missing, label is used, but if insertText is present, that is used. We should either set insertText or omit it.

### Steps to reproduce

1. Open the example project
2. Open "Wolf.gd" in an external editor configured to the godot LSP
3. Position the cursor at the end of the `yield` line
4. Start typing "tween_al"
5. Accept the completion

### Minimal reproduction project

[example2.zip](https://github.com/godotengine/godot/files/9387834/example2.zip)

**Comment by HolonProduction** [comment]
The only way an empty insertText is passed nowadays is when options from the smart resolve feature are added. So #96684 would fix this (there is currently no completion for this specific case but this is part of other issue reports)
