### ISSUE TITLE
texelFetch behavior changed at Godot 4.0 Alpha 12

### ISSUE THREAD

**Issue by ChristianKaltenecker** [godotengine/godot#64669]
### Godot version

4.0 Alpha 12

### System information

ArchLinux; Nvidia GeForce RTX 3070 Ti; Vulkan

### Issue description

Given the following script to deliver the position of an item:

```gdscript
var position := Icon.global_position.floor()
var image := Image.new()
image.create(1,1, false, Image.FORMAT_RGBAF)

# Store the position in the red and green channel
image.set_pixel(0, 0, Color(position.x, position.y, 0, 0))

var texture := ImageTexture.new()
texture.create_from_image(image)
material.set_shader_param("position", texture)
```
I am using the following shader:
```glsl
// Get the position data
vec4 texel = texelFetch(position, ivec2(0, 0), 0);
// The following line works, however:
//texel = vec4(482.0, 258.0, 0.0, 0.0);

// Distance from this pixel to the light source then normalize
float dist = distance(texel.xy, frag_position);
dist = min(dist / 100.0, 1.0);

COLOR = vec4(dist, dist, 1.0, 0.5);
```
However, beginning with Godot 4.0 Alpha 12, the behavior of texelFetch seems to have changed and only gets the coordinates (0, 0) as x and y coordinates.
This bug is still included in the current Alpha 14.
In Godot 4.0 Alpha 11, it worked as it should.
Is this a bug or have I missed something?

Thanks in advance for your help!

### Steps to reproduce

1. Open the project and execute the Main scene `Main.tscn`
2. The bug should be easily visible if the blue area is in the left upper corner and not at the position of the icon
3. Compare it with Godot 4.0 Alpha 11

### Minimal reproduction project

[TestProject.zip](https://github.com/godotengine/godot/files/9388012/TestProject.zip)

**Comment by clayjohn** [comment]
I don't think anything has changed in the code that would change how texelFetch behaves. Have you verified that the image is still created correctly?

**Comment by ChristianKaltenecker** [comment]
I have verified via the debugger that the position is encoded correctly into the image. 
The problem occurred in another codebase (in a game I develop), but was easily reproducible via the minimal reproduction project. Most interestingly, the behavior changed from Alpha 11 to Alpha 12. 

The image in both Alpha versions is still rendered correctly. Therefore, I have set the alpha of the shader to 0.5.

I also searched in the change log and issue list for something interesting regarding this issue, but failed to find something that could be related to this issue...

**Comment by ChristianKaltenecker** [comment]
As further information:
Using the minimal reproduction project above, I have now also reproduced it on Windows 11 (Nvidia RTX 3070 Ti) with Godot 4.0 Alpha 11 and Alpha 12 by starting the project.

**Comment by clayjohn** [comment]
I ran your test project through NVidia NSight to debug it and the shader appears to be working correctly. The issue is with the texture. Between Alpha 11 and Alpha 12 ``create_from_image()`` was [changed](https://github.com/godotengine/godot/pull/60739) to a function that returns the created image. 

e.g. ``texture.create_from_image()`` became ``texture = ImageTexture.create_from_image()``. In your code you end up just throwing your texture away and passing an invalid texture to the shader. 

Changing your texture creation code to the following fixes your issue:
```
var texture := ImageTexture.create_from_image(image)
material.set_shader_param("position", texture)
```

**Comment by ChristianKaltenecker** [comment]
Thank you very much for your help! I completely missed that change.
