### ISSUE TITLE
Tooltips are invalid within a SubViewport (DisplayServer regression)

### ISSUE THREAD

**Issue by linkpy** [godotengine/godot#64689]
### Godot version

4a14

### System information

Garuda Linux

### Issue description

![image](https://user-images.githubusercontent.com/2700596/185787268-dd769c23-a616-42a4-a437-3efd6367c7c9.png)
*Tooltip of a TreeItem*

Only happens when `SubViewport.gui_embed_subwindows` is set to true.

### Steps to reproduce

see below

### Minimal reproduction project

[smoll.zip](https://github.com/godotengine/godot/files/9388908/smoll.zip)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/61712 (possible duplicate).

**Comment by linkpy** [comment]
> Related to #61712 (possible duplicate).

Tooltips works correctly for us with 4a14, Garuda Linux (X11). 
We get black tooltips only when the viewport's  `gui_embed_subwindows` is set to true. All other tooltips works correctly. We have to set this option to true as the viewports are then rendered in 3D space.

**Comment by Rindbee** [comment]
It is related to viewport drawing order, #63091 can fix it.

**Comment by akien-mga** [comment]
I don't reproduce the issue with the MRP on Mageia 9 X11, using 4.0 alpha 14 and d5606503b47a98a5d1d925b2b655760dab850e6e.

This might be a driver specific issue, what GPU and drivers are you using?

For me it works fine with both AMD Radeon RX Vega M and Intel HD 630, both using Mesa 22.1.7.

```
$ inxi -CSG
System:    Host: cauldron Kernel: 5.19.3-desktop-1.mga9 x86_64 bits: 64 Desktop: KDE Plasma 5.25.4 Distro: Mageia 9 mga9 
CPU:       Info: Quad Core model: Intel Core i7-8705G bits: 64 type: MT MCP cache: L2: 8 MiB 
           Speed: 3100 MHz min/max: 800/3100 MHz Core speeds (MHz): 1: 3100 2: 3100 3: 3100 4: 3100 5: 3100 6: 3100 7: 3100 
           8: 3100 
Graphics:  Device-1: Intel HD Graphics 630 driver: i915 v: kernel 
           Device-2: Advanced Micro Devices [AMD/ATI] Polaris 22 XL [Radeon RX Vega M GL] driver: amdgpu v: kernel 
           Device-3: Cheng Uei Precision Industry (Foxlink) HP Wide Vision FHD Camera type: USB driver: uvcvideo 
           Display: x11 server: Mageia X.org 1.21.1.4 driver: loaded: intel,v4l resolution: 1920x1080 
           OpenGL: renderer: Mesa Intel HD Graphics 630 (KBL GT2) v: 4.6 Mesa 22.1.7
```

**Comment by akien-mga** [comment]
> It is related to viewport drawing order, #63091 can fix it.

I've tested it and confirmed that it solves this issue. (But not #61712 so it's unrelated.)
