### ISSUE TITLE
Highlighting's "Function Color" description calls "Function Definition Color" "Declaration"

### ISSUE THREAD

**Issue by Mickeon** [godotengine/godot#64684]
### Godot version

v4.0.alpha.custom_build [0c5f25495]

### System information

Windows 10

### Issue description

![image](https://user-images.githubusercontent.com/66727710/185785824-38ac1330-cec6-44e9-a35a-590c03ccbbb1.png)

Which one would it be?

### Steps to reproduce

Look at the Theme's Highlighting settings

### Minimal reproduction project

No need.

**Comment by KoBeWi** [comment]
I think both are technically correct. Functions in GDScript are declared and defined at the same time.

**Comment by Mickeon** [comment]
So the description should be changed to "definition" for consistency?

**Comment by KoBeWi** [comment]
Yeah consistency is good.
