### ISSUE TITLE
in godot,export h5 to use http nodes error.

### ISSUE THREAD

**Issue by wzc1392969921** [godotengine/godot#64681]
### Godot version

3.4.3

### System information

windows

### Issue description

it is api write by python-flask.
![1](https://user-images.githubusercontent.com/58593965/185775060-962d7388-d122-4a82-b759-45d3cba5f281.png)

just like this.
![2](https://user-images.githubusercontent.com/58593965/185775065-cfc68e5f-dde5-4e11-b6fc-4ac34b2ce836.png)

now,this is my GDS.
![3](https://user-images.githubusercontent.com/58593965/185775088-71f926f1-07ae-4587-86ff-880fd0db3365.png)

in windows,it is right.
![444](https://user-images.githubusercontent.com/58593965/185775107-0491702a-a921-4712-992d-23cbf2042778.png)

but when i export the h5,Some problems arise。
![555](https://user-images.githubusercontent.com/58593965/185775149-2d8a48de-9836-4357-b28b-5aee53c9da52.png)

except JAVAscript, how can i use HTTP nodes in godot export H5?

### Steps to reproduce

like picture

### Minimal reproduction project

none

**Comment by Calinou** [comment]
@wzc1392969921 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by PoolloverNathan** [comment]
Due to browser restrictions, it is usually not possible to make web requests. If you want your server to be visible on the web, you need to set up the proper CORS headers.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
