### ISSUE TITLE
SubViewport's `get_window_id` results in error with specific nodes

### ISSUE THREAD

**Issue by linkpy** [godotengine/godot#64687]
### Godot version

4a14

### System information

Garuda Linux

### Issue description

![image](https://user-images.githubusercontent.com/2700596/185786853-4b171cc5-8f29-4dc9-91fa-0dc60d3ba765.png)

```
#1  0x000055555a47e4ef in Tree::gui_input (this=0x555563a4def0, p_event=...) at scene/gui/tree.cpp:3482
3482                                            drag_touching = DisplayServer::get_singleton()->screen_is_touchscreen(DisplayServer::get_singleton()->window_get_current_screen(get_viewport()->get_window_id()));
(gdb) p get_viewport()->get_window_id()
$15 = -1
```

This error occurs when a Tree node is within a SubViewport. [SubViewports doesn't have associated windows so always returns -1](https://github.com/godotengine/godot/blob/master/scene/main/viewport.cpp#L4077) and we think a different behavior should happen (either no error or returning the parent viewport's window id?).

### Steps to reproduce

see below

### Minimal reproduction project

[smoll.zip](https://github.com/godotengine/godot/files/9388892/smoll.zip)

**Comment by linkpy** [comment]
Is it really a linuxbsd issue? SubViewport's code isn't platform dependent so the same issue should be present on Windows or Mac.

**Comment by Calinou** [comment]
The error message is emitted in `display_server_x11.cpp`, which makes me think the issue is OS-specific.

It's also worth checking whether this occurs when the **Embed Subwindows** project setting is disabled.

**Comment by linkpy** [comment]
> The error message is emitted in `display_server_x11.cpp`, which makes me think the issue is OS-specific.
 
Indeed, but that error should be present for other platforms as the window ID given is `WINDOW_ID_INVALID` (-1). The error is printing from `display_server_x11.cpp`, but the actual issue comes from `Tree` passing `WINDOW_ID_INVALID` to the display server.

> It's also worth checking whether this occurs when the **Embed Subwindows** project setting is disabled.

The same error appears.

**Comment by linkpy** [comment]
Same issue happens in a15.
Same issue happens on Windows, so not platform specific.

![image](https://user-images.githubusercontent.com/2700596/189950546-5d15724f-e472-4d83-a5fc-9f40daec5192.png)

**Comment by linkpy** [comment]
Same issue in a17.

**Comment by linkpy** [comment]
@Calinou Possible to reclassify this issue?
