### ISSUE TITLE
A regression in the networking code in Godot 4

### ISSUE THREAD

**Issue by sygi** [godotengine/godot#64699]
### Godot version

v4.0-alpha14

### System information

Linux. Ubuntu 22.04.1

### Issue description

Networking doesn't work in the newest build. The ENet server starts and the port gets opened, but the client gets stuck in the "connecting" phase forever (a separate issue is that it doesn't timeout after 30s). The same issue happens when starting a Websocket server (with TCP).

I tested the same setup in the stable version (3.5), and there it works fine, which suggests the problem is not with my local setup.

Relatedly, are there tests in the engine code that would have caught this? Is there a convenient way for making such tests in the game project itself?

### Steps to reproduce

Run the following code in a new project, start twice with commandline arguments: 1 and 2:

```
extends Node2D

const SERVER_PORT = 54321
var peer = ENetMultiplayerPeer.new()
var multiplayer_api = null

func _ready():
    var first_arg = OS.get_cmdline_args()[0]
    var pid = first_arg.to_int()
    if pid == 1:
        err = peer.create_server(SERVER_PORT, 4)
    else:
        err = peer.create_client("127.0.0.1", SERVER_PORT)
      
    multiplayer_api = multiplayer.create_default_interface()
    multiplayer_api.multiplayer_peer = peer
```

**Comment by Calinou** [comment]
> Relatedly, are there tests in the engine code that would have caught this? Is there a convenient way for making such tests in the game project itself?

Making automated networking tests is a complicated affair, so I'm afraid not.

**Comment by sygi** [comment]
I tested it a bit more, and the previous alphas don't have `multiplayer.create_default_interface()` method, only `get_multiplayer()`. When I changed to the latter, everything works. In fact, with `get_multiplayer`, it also works in v14. 

It looks like either I didn't understand how to use `create_default_interface` or it's that part which was introduced recently but doesn't work yet.

Thanks!

**Comment by hani09876** [comment]
> Can you reproduce this on earlier 4.0 alphas? You can download them [here](https://downloads.tuxfamily.org/godotengine/4.0/).
> 
> > Relatedly, are there tests in the engine code that would have caught this? Is there a convenient way for making such tests in the game project itself?
> 
> Making automated networking tests is a complicated affair, so I'm afraid not. Pull requests are welcome, but the unit test system is not designed to run entire projects. For this purpose, a dedicated project running on CI would make more sense.

Sir please add this multiplayer system on godot 3.5

**Comment by Calinou** [comment]
> Sir please add this multiplayer system on godot 3.5

The new multiplayer system won't be backported to 3.x, as it relies on backwards-incompatible changes.

**Comment by hani09876** [comment]
> > Sir please add this multiplayer system on godot 3.5
> 
> The new multiplayer system won't be backported to 3.x, as it relies on backwards-incompatible changes.

Then sir.. i want to make a multiplayer game and publish it on play store.. suppose you download my app then create a server on my app. And ask your friends to join the server who are in japan, chaina, uk. 



My question is how can i make my user able to create their own server and connect their friends on that server..

**Comment by akien-mga** [comment]
@hani09876 This is not the place to ask support questions and general advice for making games. We use GitHub to drive the development of the engine and those discussions need to stay focused. Please use other platforms for this.

**Comment by Faless** [comment]
The OP is using it's own MultiplayerAPI without adding it to the tree which will not work (because it doesn't get polled, and multiplayer functions called from node will not be routed through it).

You don't need to create the multiplayer API manually if you are not overriding it's methods.
From the demo, you just want to use the default multiplayer API, so just:

```
    multiplayer.multiplayer_peer = peer
```
I.e. set the peer for the [multiplayer property of node](https://docs.godotengine.org/en/latest/classes/class_node.html#class-node-property-multiplayer) (not your own local instance).

```
extends Node2D

const SERVER_PORT = 54321
var peer = ENetMultiplayerPeer.new()

func _ready():
    var first_arg = OS.get_cmdline_args()[0]
    var pid = first_arg.to_int()
    if pid == 1:
        err = peer.create_server(SERVER_PORT, 4)
    else:
        err = peer.create_client("127.0.0.1", SERVER_PORT)
      
    multiplayer.multiplayer_peer = peer
```
