### ISSUE TITLE
Leaving dock area releases mouse button

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#64695]
### Godot version

0c5f254

### System information

Windows 10 x64

### Issue description

Seems like some recent regression.
![ShDLmLrHNW](https://user-images.githubusercontent.com/2223172/185801413-f947e29a-6397-4d09-b958-185011348495.gif)
Tested only with tile editor.

### Steps to reproduce

1. Open tile editor (add tilemap with tileset etc)
2. Drag to select tiles
3. Leave tile area while dragging
4. The drag is cancelled

**Comment by Zylann** [comment]
Might be related to a similar behavior I found with sliders in the inspector: if I grab one and dare moving the mouse outside of the slider's rectangle, I loose grab of it.

**Comment by tinmanjuggernaut** [comment]
@Zylann That is tracked in #63544 and allegedly fixed in #63598.

**Comment by DNKpp** [comment]
To be honest, the root cause might be the same as the one for the slider (the dragged widget will be set invisible, because the cursor went out of the view-port), but the slider fix will probably not fix this.
