### ISSUE TITLE
Export hint for Layers bit doesn't set correct bit on new object

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot#64706]
### Godot version

3.5.rc7

### System information

Windows 10

### Issue description

I have a Layers export hint:
`export(int, LAYERS_3D_PHYSICS) var bounds_mask`

![image](https://user-images.githubusercontent.com/16231628/185811061-eb8f6e16-2d8e-4253-bf57-42102e70c407.png)
And I set it on a newly created StaticBody:
```gdscript
bounds_box = StaticBody.new()
bounds_box.name = "BoundsBox"
bounds_box.set_collision_layer_bit(0,false)
bounds_box.set_collision_mask_bit(0,false)
bounds_box.set_collision_layer_bit(bounds_mask,true)
add_child(bounds_box)
```
But for some reason beyond my crude understanding of bitwise operations, it's sets this layer as something completely different at runtime:
![image](https://user-images.githubusercontent.com/16231628/185811124-ecc59af4-73c9-4869-a55e-b42a896b41f4.png)

### Steps to reproduce

1. Create an export hint for a layer
2. Create node at runtime and clear default layer and mask bits
3. Set the export layer on a newly created node
4. Observe incorrect layer set at runtime

**Comment by Calinou** [comment]
@elvisish  Did you find a solution to this problem? If so, please document it here by commenting :slightly_smiling_face:

**Comment by elvisish** [comment]
> @elvisish Did you find a solution to this problem? If so, please document it here by commenting 🙂

I was using `set_collision_layer_bit` instead of `collision_layer = ` which manually sets the entire collision layer setting.
