### ISSUE TITLE
Mouse Input coordinates are wrong in fullscreen when hiDPI mode is enabled

### ISSUE THREAD

**Issue by BigZaphod** [godotengine/godot#64705]
### Godot version

v3.5.stable.official [991bb6ac7]

### System information

macOS 12.5.1 (21G83), Apple M1 Max MacBook Pro

### Issue description

I was attempting to implement a simple dragging mechanic and noticed it worked fine in windowed mode but the mouse input coordinates went all wrong after making the game window fullscreen. Here's a video showing what happens on my machine when I run the attached sample project:

https://user-images.githubusercontent.com/453721/185809093-d823fbaf-c6f6-4f0a-8c3d-72d5e186005f.mov

### Steps to reproduce

Run the attached project on macOS (no idea if this also happens on Windows) and then click and drag from the Godot icon. It should drag out a smaller godot icon that follows the mouse around and disappears when you let go of the button.

If I disable the "Allow hiDPI" project setting, then it appears to work fine in fullscreen.

### Minimal reproduction project

[Godot HighDPI Input Bug.zip](https://github.com/godotengine/godot/files/9389882/Godot.HighDPI.Input.Bug.zip)

**Comment by Calinou** [comment]
The project uses the `2d` stretch mode, so you likely need to multiply/divide mouse coordinates by the automatically scale factor.

**Comment by Calinou** [comment]
You likely need to multiply/divide mouse coordinates by the automatically scale factor

**Comment by BigZaphod** [comment]
I appreciate the workaround, but why in the world should game code have to do this? Isn't handling this kind of stuff exactly what using an engine is *for*?

**Comment by BigZaphod** [comment]
> Duplicate of #34805.
> 
> The project uses the `2d` stretch mode, so you likely need to multiply/divide mouse coordinates by the automatically determined scale factor.

I appreciate the workaround, but why in the world should game code have to do this? Isn't handling this kind of stuff exactly what using an engine is *for*?

**Comment by Calinou** [comment]
> I appreciate the workaround, but why in the world should game code have to do this? Isn't handling this kind of stuff exactly what using an engine is for?

There are likely some cases where having the unscaled mouse coordinates is useful, but I don't know which ones exactly. Scaling mouse coordinates automatically would also break all projects that rely on the current coordinate system, so this can only be considered for 4.0.
