### ISSUE TITLE
Ruler tool line displays above text

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#64704]
### Godot version

0c5f254

### System information

Windows 10 x64

### Issue description

![image](https://user-images.githubusercontent.com/2223172/185808881-da5a09f1-b192-4644-9faf-a333730cb444.png)
Probably wrong order of drawing.

### Steps to reproduce

1. Use ruler tool (R) in 2D editor
2. Looks very closely when line and text overlap

**Comment by Calinou** [comment]
I can reproduce this on 3.5 too.

PS: It might be worth enabling a font outline on the bold ruler text, so that it's readable on any background.
