### ISSUE TITLE
Physics doesn't factor in scale

### ISSUE THREAD

**Issue by robertdhernandez** [godotengine/godot#6470]
**Operating system or device - Godot version:**
Windows 10 - Godot Engine v2.2.alpha.custom_build dc6eefdbf2b3f9362dbb571e9fb2f3df60760c04

**Issue description** (what happened, and what was expected):
Changing the scale of an object that uses Rigidbody2D resets the scale at run-time. 

**Steps to reproduce:**
Create a Rigidbody2D node
Attach a sprite for visual feedback (or print ```get_scale()```)
Change the scale on the Rigidbody2D node to any other value
Run the game

**Comment by robertdhernandez** [comment]
I found the problematic line [here](https://github.com/godotengine/godot/blob/dc6eefdbf2b3f9362dbb571e9fb2f3df60760c04/scene/2d/physics_body_2d.cpp#L455), and after making a dumb workaround (caching the scale), I discovered the root problem: the physics engine doesn't take scale into account.

**Comment by akien-mga** [comment]
I guess it's the same bug as #5734.
