### ISSUE TITLE
Changing single element of Gradient.colors via code doesn't work

### ISSUE THREAD

**Issue by ktostam0** [godotengine/godot#64718]
### Godot version

4 alpha 14

### System information

Fedora Linux

### Issue description

When I try to modify a single element of Gradient.colors with `gradient.colors[0] = Color.RED` or `gradient.colors.set(0, Color.RED)` it has no effect. Maybe it's an expected behaviour, but it used to work in older alphas.

### Steps to reproduce

Create a Node and attach a script:
```
extends Node


func _ready() -> void:
	var gradient: Gradient = Gradient.new()
	gradient.colors[0] = Color.PINK
	gradient.colors.set(0, Color.PINK)
	print(gradient.colors)
```

### Minimal reproduction project

[bug_report.zip](https://github.com/godotengine/godot/files/9392862/bug_report.zip)

**Comment by Chaosus** [comment]
I pretty sure it was reported before for the other class (which using an array for something else but similar).

**Comment by KoBeWi** [comment]
Yes, it's the same as #62857
You can use the same workaround.

**Comment by kelliedlynch** [comment]
I'm still having this issue in 4.4. Cannot set a color value in a gradient with .colors[] or with set_color(). It looks like the workaround described is to set .colors to a new array, but that does not work either. Am I misunderstanding the workaround, or is there really no way to update a gradient via code?

**Comment by KoBeWi** [comment]
Tested and this works for me:
```GDScript
extends Sprite2D

func _ready() -> void:
	var gradient: Gradient = texture.gradient
	gradient.colors = [Color.BLACK, Color.BLUE]
```
Make sure the new array size matches point count.

Also the workaround is not setting the whole array, you can update specific color using `set_color(point_idx, color)`, so e.g. `colors[0] = Color.RED` becomes `set_color(0, Color.RED)`.

**Comment by kelliedlynch** [comment]
Ah, my mistake--it turns out I had a shader overwriting the value. All is well.
