### ISSUE TITLE
vsproj solution generation with Mono module fails with ModuleNotFoundError

### ISSUE THREAD

**Issue by GeorgeS2019** [godotengine/godot#64715]
### Godot version

4.0 dev  master (#64089)

### System information

Windows 11

### Issue description

```
ModuleNotFoundError: No module named 'modules.mono'; 'modules' is not a package:
  File "c:\godot\SConstruct", line 865:
    methods.generate_vs_project(env, GetOption("num_jobs"))
  File "methods.py", line 821:
    import modules.mono.build_scripts.mono_configure as mono_configure
```

### Steps to reproduce

scons.exe p=windows tools=yes module_mono_enabled=yes  tools=yes  vsproj=yes target=release_debug num_jobs=10

### Minimal reproduction project

- Git clone
- Build according to the step above

**Comment by GeorgeS2019** [comment]
A propable [fix ](https://github.com/godotengine/godot/pull/64089#issuecomment-1214191277)is discussed here.

**Comment by willnationsdev** [comment]
neikeq mentions that they hope to have fixed this in [this comment](https://github.com/godotengine/godot/pull/64089#issuecomment-1221712035), but I am still experiencing this issue on my Windows machine when building from 6e390fa9.

**Comment by GeorgeS2019** [comment]
The merge remove many files, not sure if all are important
![image](https://user-images.githubusercontent.com/49812372/186602853-c091296f-5ae9-4141-b53f-9cf447e79dee.png)

**Comment by GeorgeS2019** [comment]
After Merge

![image](https://user-images.githubusercontent.com/49812372/186603003-c5770596-e975-4c95-9da9-e18e83ba876b.png)

**Comment by GeorgeS2019** [comment]
## here are the hack I made to get vsproj to work with the dotnet6

 #### [SConstruct](https://github.com/neikeq/godot/blob/0876ddfbe63f7a9fdf2a9995b17059fc8daf1c9b/SConstruct#L52)

```
_helper_module("mono_reg_utils", "modules/mono/build_scripts/mono_reg_utils.py")
```


#### [method.py](https://github.com/neikeq/godot/blob/0876ddfbe63f7a9fdf2a9995b17059fc8daf1c9b/methods.py#L820)
```
# import modules.mono.build_scripts.mono_reg_utils as mono_reg 
import mono_reg_utils as mono_reg
```

### Copy the missing file 
https://github.com/godotengine/godot/blob/master/modules/mono/build_scripts/mono_reg_utils.py

### Run this build script
```
scons.exe p=windows tools=yes module_mono_enabled=yes  tools=yes vsproj=yes  num_jobs=10
```

**Comment by GeorgeS2019** [comment]
use both `num_jobs=6` and `-j6`

**Comment by GeorgeS2019** [comment]
#### Below this line add 
https://github.com/godotengine/godot/blob/8c1dc0c7eaa4ac498372e55d04920a9a3ef678be/SConstruct#L52

_helper_module("mono_reg_utils", "modules/mono/build_scripts/mono_reg_utils.py")

**Comment by GeorgeS2019** [comment]
### Replace this line
https://github.com/godotengine/godot/blob/8c1dc0c7eaa4ac498372e55d04920a9a3ef678be/methods.py#L821

//# import modules.mono.build_scripts.mono_reg_utils as mono_reg 
import mono_reg_utils as mono_reg

**Comment by GeorgeS2019** [comment]
### Copy the missing file 
https://github.com/godotengine/godot/blob/master/modules/mono/build_scripts/mono_reg_utils.py

### Run this build script

use both `num_jobs=6` and `-j6`
```
scons p=windows num_jobs=6 -j6 module_mono_enabled=yes vsproj=yes
```

**Comment by neikeq** [comment]
Closing as I assume this is no longer an issue after f784fb200034629318df122b0651a00de2d7007e.
