### ISSUE TITLE
svg <feOffset> does not work in Godot

### ISSUE THREAD

**Issue by xmyhhh** [godotengine/godot#64713]
### Godot version

3.3.4

### System information

windows 11, GLES3

### Issue description

The <feOffset> SVG filter primitive does not work in Godot.
![image](https://user-images.githubusercontent.com/31955947/185838964-38c2b215-8176-4b63-94e4-1ae2478e4423.png)
The above is what the SVG looks like in Edge and below is what the SVG looks like in Godot. (Notice that the black shadow at the bottom disappears)
![image](https://user-images.githubusercontent.com/31955947/185839142-720395ae-aac7-4a04-91f1-38637a932bcd.png)

### Steps to reproduce

I've put the entire SVG source code below, and you can test it by importing it directly

### Minimal reproduction project

<svg width="300" height="506" viewBox="0 0 300 506" fill="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<g filter="url(#filter0_d_1441_16275)">
<rect width="300" height="500" rx="30" fill="black" fill-opacity="0.85" shape-rendering="crispEdges"/>

<rect x="0.5" y="0.5" width="299" height="499" rx="29.5" stroke="white" shape-rendering="crispEdges"/>
</g>
<defs>
<filter id="filter0_d_1441_16275" x="0" y="0" width="300" height="506" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
<feFlood flood-opacity="0" result="BackgroundImageFix"/>
<feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha"/>
<feOffset dy="6"/>
<feComposite in2="hardAlpha" operator="out"/>
<feColorMatrix type="matrix" values="0 0 0 0 0.0235294 0 0 0 0 0.0235294 0 0 0 0 0.0235294 0 0 0 1 0"/>

<feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_1441_16275" result="shape"/>
</filter>
</defs>
</svg>

**Comment by xmyhhh** [comment]
<svg width="300" height="506" viewBox="0 0 300 506" fill="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<g filter="url(#filter0_d_1441_16275)">
<rect width="300" height="500" rx="30" fill="black" fill-opacity="0.85" shape-rendering="crispEdges"/>


<rect x="0.5" y="0.5" width="299" height="499" rx="29.5" stroke="white" shape-rendering="crispEdges"/>
</g>
<defs>
<filter id="filter0_d_1441_16275" x="0" y="0" width="300" height="506" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
<feFlood flood-opacity="0" result="BackgroundImageFix"/>
<feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha"/>
<feOffset dy="6"/>
<feComposite in2="hardAlpha" operator="out"/>
<feColorMatrix type="matrix" values="0 0 0 0 0.0235294 0 0 0 0 0.0235294 0 0 0 0 0.0235294 0 0 0 1 0"/>

<feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_1441_16275" result="shape"/>
</filter>
</defs>
</svg>

**Comment by xmyhhh** [comment]
`<svg width="300" height="506" viewBox="0 0 300 506" fill="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<g filter="url(#filter0_d_1441_16275)">
<rect width="300" height="500" rx="30" fill="black" fill-opacity="0.85" shape-rendering="crispEdges"/>


<rect x="0.5" y="0.5" width="299" height="499" rx="29.5" stroke="white" shape-rendering="crispEdges"/>
</g>
<defs>
<filter id="filter0_d_1441_16275" x="0" y="0" width="300" height="506" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
<feFlood flood-opacity="0" result="BackgroundImageFix"/>
<feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha"/>
<feOffset dy="6"/>
<feComposite in2="hardAlpha" operator="out"/>
<feColorMatrix type="matrix" values="0 0 0 0 0.0235294 0 0 0 0 0.0235294 0 0 0 0 0.0235294 0 0 0 1 0"/>

<feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_1441_16275" result="shape"/>
</filter>
</defs>
</svg>
`

**Comment by xmyhhh** [comment]
![hotRankBackground](https://user-images.githubusercontent.com/31955947/185839575-24aabf78-0622-4ad1-a926-e7d9b6fb8df0.svg)

**Comment by Calinou** [comment]
Can you test this in 4.0.alpha14? Godot 3.x uses the unmaintained nanosvg library, which only supports a small subset of the SVG specification. In comparison, Godot 4.0.alpha uses ThorVG, which supports more features (but it still won't support Inkscape-only features);

**Comment by bluenote10** [comment]
ThorVG seems to target SVG Tiny 1.2 spec, and SVG Tiny in general does not support `<filter/>` tags at all, if I understand it correctly. So I don't think this is specific or limited to `feOffset`, but all filter defs.

This looks like a pretty unfortunate limitation, because it makes it impossible to import UI elements from SVGs that involve e.g. a drop shadow effect, which is relatively popular for UIs.

There are a few open issues on ThorVG side related to that:

https://github.com/thorvg/thorvg/issues/374
https://github.com/thorvg/thorvg/issues/1367

**Comment by Calinou** [comment]
Closing, as this is now documented by https://github.com/godotengine/godot-docs/pull/7354 and https://github.com/godotengine/godot-docs/pull/7593. SVG support should be improved upstream.
