### ISSUE TITLE
Non uniform scale in particles causes billboard to shear when there's an angle

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#64722]
### Godot version

v4.0.alpha.custom_build [2e24b7653]

### System information

Linux Fedora, Radeon RX 590

### Issue description

The quad in the video has two scale curves:
![image](https://user-images.githubusercontent.com/7917475/185897560-7726f5e1-4e24-4b01-9f0a-cc714c58fce8.png)
So on the Y axis, it's supposed to grow, but on the X axis, it will grow and then shrink.
In the second part of the video, you can see is working correctly on a straight quad, but when the quad gains an angle (first part of the video) the billboard shears the quad.
I believe that this is just a wrong order of transformations applied (scale after rotation) but it's all in a single matrix, so I'm not sure how to fix it.

https://user-images.githubusercontent.com/7917475/185897444-773dcc78-6d64-4c47-b268-8362516665e1.mp4

### Steps to reproduce

This is actually a bit complex due to https://github.com/godotengine/godot/issues/64505, please download MRP.

### Minimal reproduction project

**THIS IS A SINGLE TSCN FILE!! NOT A PROJECT**

[BillboardShear.zip](https://github.com/godotengine/godot/files/9393407/BillboardShear.zip)

**Comment by Calinou** [comment]
> THIS IS A SINGLE TSCN FILE!! NOT A PROJECT

For future reference, I recommend converting it to a project by following these steps:

1. Place the .tscn file in a folder
2. Create an empty `project.godot` file in the same folder (e.g. `touch project.godot`)
3. Open Godot (`godot -e`), run the project and set the main scene
4. ZIP the folder

This allows other users to reproduce the issue without having to follow these steps manually.
