### ISSUE TITLE
[right] and [center] alignment in RichTextLabel keeps space before a line wrap

### ISSUE THREAD

**Issue by CorentinBrule** [godotengine/godot#64738]
### Godot version

v3.5.stable.official [991bb6ac7]

### System information

Windows 11

### Issue description

the [right] BBCode tag for right alignement in RichTextLabel does a bad behaviour. He keeps space before a line wrap instead of avoid space. He does the good thing in a line break.

Actual :
![bad-right-align](https://user-images.githubusercontent.com/9805733/185969438-138576fa-83b0-4091-85f5-567ee62826c5.png)

expected :
![good-right-align](https://user-images.githubusercontent.com/9805733/185970994-2a5b25b1-a9e1-48bc-abf5-685f6fa903b1.png)

### Steps to reproduce

create a RichTextLabel, enable BBCode and write a text between [right] and [/right] of a length greater than the width of the RichTextLabel rect to cause line wraps.

### Minimal reproduction project

[gui_rich_text_bbcode.zip](https://github.com/godotengine/godot/files/9396035/gui_rich_text_bbcode.zip)

**Comment by akien-mga** [comment]
CC @bruvzg @timothyqiu

**Comment by bruvzg** [comment]
The same is true for 4.0, seems like we need to trim edge spaces for the right alignment in the similar way we do for fill.

**Comment by CorentinBrule** [comment]
if it helps: `Label` elements with `Align` property on `Right` has the right behaviour :)

**Comment by akien-mga** [comment]
This should also be trimmed for `[center]`, see #64779 for a MRP (CC @rokasv).
