### ISSUE TITLE
NetworkedMultiplayerCustom throwing "Invalid packet received. Unabled to find requested cached node" on RPC call

### ISSUE THREAD

**Issue by jarommadsen** [godotengine/godot#64736]
### Godot version

3.5.stable

### System information

Windows 10

### Issue description

I've been testing the NetworkedMultiplayerCustom class with the Discord Game SDK and have hit a snag.

I'm able to connect two players together and send packets between them but when the client makes an RPC call to the server it throws the "Invalid packet received. Unabled to find requested cached node" error. Did some digging in the source code to figure out where this error was coming from and it seems like the node wasn't properly cached beforehand?

Strangely if I send an RPC call from the server to the client it seems like it gets processed fine.

I am wondering if this has anything to do with my usage of a placeholder scene? I have tested this though with the NetworkedMultiplayerENet peer successfully with not changes to anything but the initial connection so I suspect there is something missing in the NetworkedMultiplayerCustom implementation.

### Steps to reproduce

You'll need two instances of Discord running with two accounts available to test with. You can follow Discord's instructions [here](https://discord.com/developers/docs/game-sdk/sdk-starter-guide#testing-locally-with-two-clients) or you can download their official and Canary builds and log into two separate accounts with each.

Run the project with the console open to observe the output.

1. Build the project with the `Node2D/Lobby/Controls/Discord Controls/Discord` node's `discordFlop` set to `On` and hit run.
2. Open another build of the project but set `discordFlop` to off and then hit run.
3. You should have two instances running now, one with "Discord Instance 0" and one with "Discord Instance 1".
4. Click invite on one of the buttons and Discord should prompt you with an invite dialog. Sometimes it doesn't work the first time you initiate the request and you'll have to close the game and try again.
5. Invite the other Discord instance's player. This instance will become the host.
6. Click "Join Game" from the invited Discord instance. This instance is the client.
7. Both games should now have a "Commit" button. Click "Commit" from the client and observe the error from the console on the host instance.

### Minimal reproduction project

[SpaceshipHotPotato - Copy.zip](https://github.com/godotengine/godot/files/9395297/SpaceshipHotPotato.-.Copy.zip)

**Comment by dsnopek** [comment]
I haven't had a chance to run the project, but I had some thoughts from looking at the code:

```
    void _PlayerConnected(System.Int64 lobbyId, System.Int64 playerId)
    {
        otherUserPeerId = playerId;
        client.EmitSignal("peer_connected", (int)playerId);
    }
```

It seems like this would emit "peer_connected" with the Discord ID, rather than 1 when this is the client. Maybe it should be something like you have in `_PacketReceived()`:

```
client.EmitSignal("peer_connected", isHost ? (int)playerId : 1);
```

If "peer_connected" is never emitted with peer id 1, then the path cache for that peer will never get setup. This would be my 1st guess as to what might be happening :-)

**Comment by jarommadsen** [comment]
Heeeey! I think that might have been it! Discord is a bit weird and only emits that signal for existing players so the host wasn't ever even getting that called.

> If "peer_connected" is never emitted with peer id 1, then the path cache for that peer will never get setup. 

This would be good commentary for either the tutorial or even in the docs I'd think. I only thought to add this when I saw your code example in https://github.com/godotengine/godot/pull/64585

**Comment by jarommadsen** [comment]
Gah! You're the best @dsnopek! Looks like that was the issue after all. And with that, Discord Game SDK integration is working!!! So strange it didn't throw the peer_id error instead. Pretty hidden functionality that Godot is also keeping track of the peerId's under the hood as well, although it makes sense.

**Comment by rcorre** [comment]
I found this issue searching for the same error with a custom multiplayer peer. For anyone else who finds this, my error was emitting "peer_connected" only on the server, but it must be emitted on clients too. The docs are misleading, so I opened https://github.com/godotengine/godot/pull/73942
