### ISSUE TITLE
Lightmap UV doesn't generate if physics body is enabled in blender import settings

### ISSUE THREAD

**Issue by prototype5885** [godotengine/godot#64746]
### Godot version

4.0.alpha14

### System information

Windows 11, Desktop Vulkan, NVIDIA RTX 2070

### Issue description

Using the blender import, lightmap baking doesn't work (I think it's not generating UV2 map) for select meshes if physics body is generated for them.

### Steps to reproduce

In the reproduction project, in the blender_test.blend import settings, it has 2 cubes and 1 other mesh. One cube has generate physics enabled, the other doesn't. The one with generate physics enabled has non functioning lightmap baking. After disabling physics body generation for that cube and reloading the scene, the lightmap baking works as intended.

### Minimal reproduction project

[Lightmap Bug.zip](https://github.com/godotengine/godot/files/9396616/Lightmap.Bug.zip)

**Comment by Calinou** [comment]
I think this is expected, as RigidBodies will be moving. Baked lightmaps cast onto them will be invalid.

**Comment by prototype5885** [comment]
> I think this is expected, as RigidBodies will be moving as soon as they're added to the scene. Baked lightmaps cast onto them will be invalid if the object moves. (In some cases such as for moving platforms or doors, this can be a reasonable compromise, but you shouldn't use RigidBody for those anyway.)

its supposed to work with static body, like the main ground/wall where your character actually walks

**Comment by Calinou** [comment]
I can confirm this on 4.0.alpha 0c5f25495 (Linux, NVIDIA 515.57).

Left has StaticBody generation disabled, right has StaticBody generation enabled:

![image](https://user-images.githubusercontent.com/180032/186013280-3bb31e42-68e5-43d9-ab69-c0f464a52c6d.png)

Also, it should be noted in the scene tree (which you can view by right-clicking the imported scene and enabling **Editable Children**), the StaticBody is a child of the MeshInstance3D, not the other way around. I'm used to it being the other way around…

**Comment by clayjohn** [comment]
I tracked this down to a single line:
https://github.com/godotengine/godot/blob/d93b66ad4d6b1dae42cc318c16224d03bd1a1472/editor/import/resource_importer_scene.cpp#L1936

This if statement ensures that we only only lightmap info, UV2s, LODs, etc. if there is no existing mesh. However, when enabling physics (which happens earlier) we create the mesh as it is needed to generate the collision shape. 

Removing this if statement is enough to fix the bug and it appears to not introduce any regressions. But I really don't know enough about importer stuff to be confident about that. Hopefully someone from the Importer team can weigh in
