### ISSUE TITLE
Build Mono module on Windows 11 throws RuntimeError: File Not found.

### ISSUE THREAD

**Issue by MrBBBaiXue** [godotengine/godot#64765]
### Godot version

4.0.dev (commit ebd966acee)

### System information

Windows 11 x64 10.0.22000.856, Vulkan

### Issue description

When compile godot with module_mono_enabled=yes on Windows 11, Scons throws error below:
```
PS F:\Github\godot> scons -j6 platform=windows target=release_debug module_mono_enabled=yes
scons: Reading SConscript files ...
Configuring for Windows: target=release_debug, bits=default
Found MSVC version 14.3, arch amd64, bits=64
Found .NET Core Sdk root directory: C:\Program Files\dotnet
RuntimeError: File not found: C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Host.win10-x64\6.0.7\runtimes\win10-x64\native\libnethost.lib:
  File "F:\Github\godot\SConstruct", line 852:
    SConscript("modules/SCsub")
  File "C:\Users\user\anaconda3\lib\site-packages\SCons\Script\SConscript.py", line 660:
    return method(*args, **kw)
  File "C:\Users\user\anaconda3\lib\site-packages\SCons\Script\SConscript.py", line 597:
    return _SConscript(self.fs, *files, **subst_kw)
  File "C:\Users\user\anaconda3\lib\site-packages\SCons\Script\SConscript.py", line 285:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "F:\Github\godot\modules\SCsub", line 34:
    SConscript(base_path + "/SCsub")
  File "C:\Users\user\anaconda3\lib\site-packages\SCons\Script\SConscript.py", line 660:
    return method(*args, **kw)
  File "C:\Users\user\anaconda3\lib\site-packages\SCons\Script\SConscript.py", line 597:
    return _SConscript(self.fs, *files, **subst_kw)
  File "C:\Users\user\anaconda3\lib\site-packages\SCons\Script\SConscript.py", line 285:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "F:\Github\godot\modules\mono\SCsub", line 12:
    mono_configure.configure(env, env_mono)
  File "F:\Github\godot\modules\mono\build_scripts\mono_configure.py", line 45:
    check_app_host_file_exists("libnethost.lib" if os.name == "nt" else "libnethost.a")
  File "F:\Github\godot\modules\mono\build_scripts\mono_configure.py", line 36:
    raise RuntimeError("File not found: " + file_path)
```

My folder structure in `C:\Program Files\dotnet\packs\`
![image](https://user-images.githubusercontent.com/17956756/186062053-19deba72-df07-42fd-ac96-f0f702ddbd22.png)

I can find `libnethost.lib` in `C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Host.win-x64\6.0.8\runtimes\win-x64\native`
![image](https://user-images.githubusercontent.com/17956756/186062665-4eba22b3-3d51-4abd-abab-546e3ebbd105.png)

Run `dotnet --info`  returns:

```
PS F:\Github\godot> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614

运行时环境 (Runtime Environment):
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.400\

global.json file:
  Not found

Host:
  Version:      6.0.8
  Architecture: x64
  Commit:       55fb7ef977

.NET SDKs installed:
  5.0.102 [C:\Program Files\dotnet\sdk]
  6.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

Seems it's a windows-only issue that dotnet's RID is still win10-x64 even on Windows 11? Maybe we should use a more reliable way to scan libnethost.lib.

### Steps to reproduce

1. Clone godot repo.
2. Install Visual Studio 2022 17.3.1 with .NET Desktop workload.
3. Build with  `scons -j6 platform=windows target=release_debug module_mono_enabled=yes`

### Minimal reproduction project

None.

**Comment by GeorgeS2019** [comment]
[vsproj solution generation with Mono module fails with ModuleNotFoundError](https://github.com/godotengine/godot/issues/64715)

>A propable [fix ](https://github.com/godotengine/godot/pull/64089#issuecomment-1214191277)is discussed here.

```
ModuleNotFoundError: No module named 'modules.mono'; 'modules' is not a package:
  File "c:\godot\SConstruct", line 865:
    methods.generate_vs_project(env, GetOption("num_jobs"))
  File "methods.py", line 821:
    import modules.mono.build_scripts.mono_configure as mono_configure
```

**Comment by raulsntos** [comment]
To find `libnethost.lib` we first try with a path formed in this way:

https://github.com/godotengine/godot/blob/d5606503b47a98a5d1d925b2b655760dab850e6e/modules/mono/build_scripts/mono_configure.py#L106-L115

The `runtime_identifier` is determined as `win-x64` in your case which seems correct and the `app_host_version` is determined by executing `dotnet --list-runtimes` and trying to get the first one that matches the right version (should be `Microsoft.NETCore.App` and at loosely `6.0`).

If the formed path is not found then it falls back to using `dotnet --info` to get the runtime identifier and use that to form the path which fails, so both ways failed to form a valid path.

I think the first way should have worked but it seems the `dotnet --list-runtimes` is returning `6.0.7` as the version while the path you have is `6.0.8`, that seems to be a problem with .NET packaging so **check if there is an update of the .NET SDK** that fixes this.

**Comment by derammo** [comment]
I just hit this too.  Maybe reconsider whether this can really be closed if it is super normal for people to hit this when they try to compile the C# feature?   Maybe our SConstruct should actually check for this situation?
