### ISSUE TITLE
Editor cant edit scenes nor resources

### ISSUE THREAD

**Issue by thepromaper** [godotengine/godot#64761]
### Godot version

3.5 stable 

### System information

OS:windows 10 21H2 x64

### Issue description

https://user-images.githubusercontent.com/72669769/186052617-bc196f2e-ccc2-490d-bcee-931b6b7d201d.mp4

I cant modify tilesets, add nodes, change visibility or switch scenes, when i close the currently edited scene the editor freezes and closes, re-opening it fixes the problem, however it happens often on complex scenes.

Most of the changes im able to do on this state dissapear when the scene (and therefore editor) is closed.

godot is running on C:\Program Files (x86)\Godot, the only program using the project files is aseprite which does not have problems normally, the editor just re-imports things when aseprite writes.

### Steps to reproduce

- Open a complex scene (the one im testing has 867 nodes)

**Comment by Calinou** [comment]
> godot is running on C:\Program Files (x86)\Godot

While it may work, I recommend not installing Godot to Program Files, as it will not be able to write files in that folder. This is especially the case if your project files are also located in Program Files (which should **never** be the case).

**Comment by thepromaper** [comment]
I moved godot out of program files to another partition, the project files are on the partition, and it doesnt fix the problem nor does running godot as admin.

**Comment by thepromaper** [comment]
cmd doesnt seem to provide a lot of info either.

When trying to add a tile to a tileset and edit it:
![image](https://user-images.githubusercontent.com/72669769/186304879-cc3db9c1-3320-4542-9620-38cf38b4d64f.png)
`The tileset doesnt have tile with ID "22"`
![image](https://user-images.githubusercontent.com/72669769/186304901-bd416ebb-c02c-401f-8a2e-c5304245f6e0.png)
`Condition "!tile_map.has(p_id)" is true. Returned: Array()`


When trying to undo any action done while the editor is "frozen":
![image](https://user-images.githubusercontent.com/72669769/186305083-a3b267bd-793a-4206-a7c2-6840dc861e21.png)
`Condition "action_level > 0" is true.`

When adding a node to the tree:
![image](https://user-images.githubusercontent.com/72669769/186305183-a59a376b-b41d-4344-a75a-d15771e1f6c5.png)
`Condition "p_node->is_inside_tree()" is true.`

Trying to change scenes doesnt print anything, it just doesnt.

**Comment by Calinou** [comment]
@thepromaper Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by thepromaper** [comment]
I havent been able to add a minimal reproduction project because i dont yet understand what part is causing issues, but i have discovered some things:

- It doesnt necesarilly happen when recovering focus.
- You can switch to scenes that are instanced inside the scene you are currently editing (you cant change anything in there either), so perhaps it has something to do with not being able to load files?

ill keep checking when it happens and upload the minimal project when possible

**Comment by thepromaper** [comment]
I haven't been able to reproduce it easily so i'll close it.
