### ISSUE TITLE
Function to get the readable names of gamepad buttons (and vice versa)

### ISSUE THREAD

**Issue by rgrams** [godotengine/godot#6476]
**Feature Request:**
It would be awesome if there were built-in functions to get a user-readable name of a gamepad/joystick button from its button_index, and vice versa. This functionality already exists for keyboard keys with `OS.get_scancode_string()` and `OS.find_scancode_from_string()`. Functions to get the names of joystick axes would be cool too. 

There are already [global constants](http://docs.godotengine.org/en/latest/classes/class_@global%20scope.html?highlight=JOY_) that match up joystick axis and button names with their button indices, but they're not terribly useful on their own.

**Comment by Hinsbart** [comment]
Should this be in `OS` like `get_scancode_string()` or in `Input`, like the rest of the joystick functions?

**Comment by rgrams** [comment]
I would put it in `Input` personally. From a game making standpoint it doesn't have much to do with the OS.
