### ISSUE TITLE
Sprite/Image/Texture Editor/Creator

### ISSUE THREAD

**Issue by Duskitty** [godotengine/godot#6477]
So as an artist who also uses godot to work on games, i found it rather time consuming having to back and forth between a sprite editor and have to export all the time and such, So i came up with a rather rough mockup for a sprite editor, i dont know how to Code or anything as im mainly an artist, so any feedback on my idea would be helpful

![godot engine - platformer - player tscn - _00029](https://cloud.githubusercontent.com/assets/13949321/18490191/91a21246-79c6-11e6-9374-755db680cbdb.png)

**Comment by bojidar-bg** [comment]
Might be doable as a plugin, unless some of the core devs wants it in core :smile:

**Comment by blurymind** [comment]
I would love to give it a shot to write one, but I am not even sure what node to use in godot in order to do pixel painting.
There was a user interested in this a while ago on facebook - he wanted to make an animation editor in godot

**Comment by reduz** [comment]
if you save a png file to the disk, it will be reloaded automatically, it
shouldn't be time consuming..  maybe something is wrong in the workflow?

**Comment by blurymind** [comment]
The workflow is good,
However when you rapidly prototype games and don't have any assets to play with, having the ability to create a simple placeholder sprite inside the game engine - be it a square of some color - is a nice thing to have.

Also if you have it built into the editor- it makes you feel like you are working in a full fledged game studio - not just a game engine with an editor.
We could take example from Game maker Studio's success, and other engines that have a built in sprite editor- clickteam fusion and construct2.

That said, there is an interesting plugin for simple pixel editing being developer here:
https://github.com/cwkx/godot-pixel-painter

**Comment by spyres** [comment]
Seems like a waste of time.  Just set your graphics app to use the godot project as it's default save position and then any updated save will auto update in your project.  That's not tedious at all and perhaps better because you then have the full power of your graphics app and not something stripped down that's been integrated.

**Comment by akien-mga** [comment]
Yes I agree that this would be out of scope of a game engine. There are great tools for vector and raster graphics, many of which are free and open source, and do way more things than we could even dream of implementing, if it weren't completely tangential to our work as game engine developers. Our purpose is to *use* assets, not create them - asset creation is a domain in its own right and we shouldn't spread our resources thin when there is no practical gain for the user.

If there's a use case for a trivial sprite editor à la MSPaint, it could easily be implemented as a plugin, but not in the main engine.
