### ISSUE TITLE
Let editor get focus on breakpoint hit

### ISSUE THREAD

**Issue by RandomShaper** [godotengine/godot#6478]
This is a usability feature request.

**Comment by reduz** [comment]
I did this but it doesn't work in all platforms, where are you testing?

**Comment by RandomShaper** [comment]
Windows only.

**Comment by reduz** [comment]
I implemented OS_Windows::move_window_to_foreground() (os_windows.cpp:2157).
On Linux and OSX I managed to get this to work, but It seems to be not
working for some reason on Windows, if you would like to give it a try
figuring out why be welcome (not currently on Windows myself at the moment).

**Comment by RandomShaper** [comment]
Have a look a my #6479.
