### ISSUE TITLE
Panels don't resize or resize improperly

### ISSUE THREAD

**Issue by Xartorx** [godotengine/godot#64785]
### Godot version

v4.0.alpha.mono.custom_build [70ceba291]

### System information

Windows 10 / 3080 Ti

### Issue description

After opening any project (new or old) i can't resize any panels on the right or bottom, and left panel is resizing improperly (doesn't starts immediately, see incl. video)

https://user-images.githubusercontent.com/2698825/186174960-dc51e775-9860-4730-ae61-0389cd558771.mp4

Tested both Mono and non-Mono editor.

### Steps to reproduce

1. Open editor
2. Try to resize panels

### Minimal reproduction project

N/A (literally clean project)

**Comment by akien-mga** [comment]
That's a regression from #64676, @KoBeWi is working on it.

**Comment by Xartorx** [comment]
@akien-mga oh, i was already in the middle of bisecting this. Good to know.

**Comment by vzuzik** [comment]
jfyi. panels resizing was broken by this commit https://github.com/godotengine/godot/commit/185b1a5bd333c5e75da5219e66cb759b5e6c3684
