### ISSUE TITLE
GDScript documentation generator: brief description and description do not work in subclasses

### ISSUE THREAD

**Issue by fire-forge** [godotengine/godot#64807]
### Godot version

v4.0.alpha14.official [106b68050]

### System information

Windows 10

### Issue description

GDScript documentation generator brief description and description do not work in subclasses. 

### Example code:
```gdscript
class_name Class

## Brief description.
##
## Description.

class Subclass:
	## Brief description.
	##
	## Description.
	
	pass
```

| Class | Subclass |
---|---
| ![image](https://user-images.githubusercontent.com/67974470/186289222-27ed0b91-e03b-4ab0-b911-a04c315fade2.png) | ![image](https://user-images.githubusercontent.com/67974470/186289062-9dfb0f17-90b6-423b-be63-8654864a45cd.png) |

### Steps to reproduce

* Create a script.
* Copy and paste this code into the script:
```gdscript
class_name Class

## Brief description.
##
## Description.

class Subclass:
	## Brief description.
	##
	## Description.
	
	pass
```
* Press F1 and open the documentation page for `Class`. The description is visible.
* Open the documentation page for `Class.Subclass`. The description is not visible.

**Comment by dalexeev** [comment]
https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_documentation_comments.html#examples

```gdscript
## Documenting an inner class.
##
## The same rules apply apply here. The documentation must
## immediately precede the class definition.
##
## @tutorial: http://the/tutorial/url.com
class Inner:

    ## Inner class variable v4.
    var v4

    ## Inner class function fn.
    func fn(): pass
```

**Comment by fire-forge** [comment]
@dalexeev Thanks for that. This issue can be closed then.
