### ISSUE TITLE
Engine for General Computing

### ISSUE THREAD

**Issue by sirinath** [godotengine/godot#6481]
There definitely more application in GoDot than gaming. One area is visual scripting like in [LabView](http://www.ni.com/labview/).

**Comment by akien-mga** [comment]
I don't understand the message here. Do you want Godot to become a general computing engine to make things like LabView? This won't happen, Godot is a game engine.

**Comment by sirinath** [comment]
Having visualisations, visual scripting and LA means it is not too difficult to take this direction also. It can be a Game Engine at heart but also tailored for other applications. Then you can have one tool to do everything.

**Comment by akien-mga** [comment]
That's still pretty vague (no clue what LA even is), and hardly related to Godot's core business. Visual scripting is already included, but it's intended to develop games, not scientific applications. There are tons of toolkits better suited for such uses.

Also, see http://docs.godotengine.org/en/latest/reference/faq.html#i-have-a-great-idea-that-will-make-godot-better-what-do-you-think

**Comment by sirinath** [comment]
LA - linear algebra

**Comment by punto-** [comment]
You're free to use the engine for anything you like, but any new feature
will be considered first for what it can do to improve game development.
That doesn't mean it'll be rejected right away if it's useful for something
else, but it can't interfere with game development, which is what we do.

**Comment by sirinath** [comment]
Sounds good.

**Comment by Qudware** [comment]
Sorta how Unity3D advertises non-game uses on their website, I'd say that's all there is to do.

**Comment by akien-mga** [comment]
Archiving as this is not really a task that should or will be done by Godot core developers; modules are welcome to implement such features, but should likely be discussed with interested developers in a relevant place (new repo for the module, forum topic, etc.)
