### ISSUE TITLE
headless engine crash when performing create_convex_shape on a mesh with invalid skin data

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#64816]
### Godot version

4.0.dev 49ac05550e4ce3b3489fad0a2addd907af1f5898

### System information

Ubuntu 18.04 / Ubuntu 22.04, 6700xt

### Issue description

We have found a .glb file which is crashing our server, it's happening when calling Mesh.create_convex_shape() in headless mode.
The crash is happening in 
https://github.com/godotengine/godot/blob/master/servers/rendering_server.cpp#L1260
, the direct cause of the crash is the fact that `sr` array is null (https://github.com/godotengine/godot/blob/master/servers/rendering_server.cpp#L1069)

Worth to note that in Godot 3.3.2:
- I could not reproduce the issue
- Upon importing asset 3.3.2 actually imported and created material files next to asset file, in Godot4 such files are never created, it smells a bit like the issue might be related to Godot4 import logic?

### Steps to reproduce

1. Download minimal reproduction sample
2. Open it once in editor, allow editor to import all the assets
3. Now open it again with `—headless` startup flag
4. Crash should occur

### Minimal reproduction project

[CrashOnMeshGeneration1.zip](https://github.com/godotengine/godot/files/9414408/CrashOnMeshGeneration1.zip)

This investigation was kindly sponsored by The Mirror

**Comment by akien-mga** [comment]
No answer, so assuming fixed.
