### ISSUE TITLE
Encoding problem with translations (i18n)

### ISSUE THREAD

**Issue by Ashe1626** [godotengine/godot#64821]
### Godot version

3.5 stable mono

### System information

Windows 11

### Issue description

Hello!
I tried adding i18n to my project and started testing translations in french. I took good care to encode my csv file in UTF8. It works fine for simple letters but it gets tricky when I start trying to print accents like éèêàïç. I see completely different characters in the middle of my words. This is how the word "Paramètres" is rendered:
![image](https://user-images.githubusercontent.com/111970845/186389841-c6c8bd6b-4025-4750-b54a-9b370bd6ed5c.png)
I see this problem only when using the interface. When I translate text in C# and print it to the console it prints correctly.

### Steps to reproduce

Create a csv file with a fr column and translate any key to "Paramètres"
Import the translations
Put the key in a button name
Run the project
The è should not print correctly

**Comment by Xstoudi** [comment]
Can you send your font file? Does it support accents?

**Comment by Ashe1626** [comment]
I can't link .ttf files but ok thanks for the hint I'll look into it
