### ISSUE TITLE
Securing code/Export encryption key revamp

### ISSUE THREAD

**Issue by Triangle345** [godotengine/godot#6483]
Currently the only way to encrypt Godot scripts is using the export encryption key by recompiling the entire Godit tool chain.  Recompiling everything seems a bit crazy just to secure one's scripts.  

Instead of recompiling the entire tool chain maybe Godot can create a small binary driver and hide a key in there. This binary driver can then be used to run unencrypt the script and start the app.

**Comment by reduz** [comment]
Compiled in the binary is a little more difficult to find. Still far from
perfect though :P

**Comment by reduz** [comment]
The idea is that, in the end, you still need a custom compiled version of
the engine to run the game. What you find as a bug is exactly the intention.

**Comment by akien-mga** [comment]
Closing then, as it's a feature.
