### ISSUE TITLE
AssetLib causes Godot Engine to lag-freeze when using a slow internet speed

### ISSUE THREAD

**Issue by ivanskodje** [godotengine/godot#6484]
**Operating system or device - Godot version:**
v2.2.alpha.custom_build

**Issue description** (what happened, and what was expected):
Using a slow internet connection appears to make Godot Engine freeze and lag while it attempts to fetch plugins. Note that these are assumptions based on what is going on.
This happens every time I do it. Internet speed is around 5-50kb/s and can be up to around 200kb/s on rare occasions.

Another issue is when I click away from AssetLib; it does not stop attempting to download the assetlib. Not a big deal, but can be a pain when you accidentally press AssetLib due to lag/freezes.

**Steps to reproduce:**
- Have slow internet connection
- Start Godot Engine v2.2 alpha.custom_build
- Select AssetLib 
- (Optional) Unselect AssetLib

---

I could not find any previous issues mentioning about this.

**Comment by bojidar-bg** [comment]
Can confirm, that one is really terrible

**Comment by Noshyaar** [comment]
Is this the same as #17051? If it is, it still relevant in master.

**Comment by akien-mga** [comment]
It's the same as #17051 yes, I'll close as duplicate as the latter has more recent activity.
