### ISSUE TITLE
Blender check expects executable and selector in editor forces folder

### ISSUE THREAD

**Issue by antonWetzel** [godotengine/godot#64848]
### Godot version

4.0.dev (https://github.com/godotengine/godot/commit/d0a2a4c98195eb8a43713286b5b865dfbed05163)

### System information

Windows 11

### Issue description

The check from https://github.com/godotengine/godot/pull/64758 only enables Blender if the path points to an executable, but the selection dialog only accepts folders.

The Importer worked with the folder as path (probably still works) and works with the executable as path, but throws errors that `<path>/Blender.exe/Blender.exe <args>` is not a valid child process

If the path is empty the popup-dialog wants a folder and the import works until reboot.

### Steps to reproduce

1. open editor settings
2. go to Filesystem -> Blender -> Blender 3 Path
3. the select dialog is a folder selector

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/9418779/Test.zip)
Editing the user editor settings to point to the executable works.
Choosing the folder in the editor does not work.

**Comment by akien-mga** [comment]
CC @jtnicholl @fire
