### ISSUE TITLE
Changing type in import dock should not require editor restart

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#64856]
### Godot version

4.0.alpha 14

### System information

Windows 10

### Issue description

Changing the type of a .glb model to AnimationLibrary is expected to be a common operation. Currently, this requires restarting the Godot editor for every file changed.

From a jitsi conversation with reduz, changing the type of a resource to an incompatible type (for example, PackedScene -> AnimationLibrary) should not require an editor restart.

![dialog showing import restart needed](https://user-images.githubusercontent.com/39946030/186525847-fb85b5c7-0955-4d72-8934-cd08b0517940.png)

The unknown question is which cases of texture types can avoid a restart.
What about going to Keep File (no import) and back?

### Steps to reproduce

1. Import a gltf document
2. Change the Import As to Animation Library and click Import
3. A confirmation dialog pops up asking the user to save all scenes and restart.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot-proposals/issues/2500.

**Comment by cyraid** [comment]
> Related to [godotengine/godot-proposals#2500](https://github.com/godotengine/godot-proposals/issues/2500).

How is this related to the proposal mentioned in #2500 ? This proposal mentions when changing import type it Godot shouldn't have to restart every time.

**Comment by lyuma** [comment]
It looks like **proposal** godotengine/godot-proposals#2500 (*beware*: not bug #2500 which is unrelated) is related in terms of allowing changing the default import type, which would reduce the need to change the type after the fact:

> There should be a way to specify, for a given extension (e.g. png, obj, csv), what should be the default ResourceImporter used to import any newly added asset with this extension.
> 
> This should likely be a project setting, ...

So it is not the entire solution to this issue but might mitigate how often the import settings need to be changed, for some file formats.

I think for .glb in particular, godotengine/godot-proposals#2500 would not address the issue, becasue the most common workflow is to bring in a character and then also bring in sets of animations. Those are almost always in the same format: all .fbx or all .glb, because they are often created in the same modeling software (such as Blender, Maya). Furthermore there are many non-animation assets brought in as .glb files, so it would be unreasonable to change .glb to default to AnimationLibrary in an actual project.

**Comment by cyraid** [comment]
@lyuma I would think being allowed to have, say, an import group of assets (like Unity) would solve a lot too. For example, an aseprite file has animation and texture assets, etc. FBX would have animation, model data, materials, etc. Currently you can embed or extract with advanced 3D importer, but what about other formats that have multiple assets? It would be nice to see a group for the asset in the filesystem tree under that asset and click and drag as appropriate. This would solve having to change the 'type' as it would import into the current asset group, thus changing the need to restart when changing type?

**Comment by lyuma** [comment]
You can solve this with the advanced importer workflow, since it can extract animations into animation files. one approach that could work would be if something could automatically create a library with these extracted animations.

There's a bit of redundancy in terms of AnimationLibrary import workflow vs the advanced importer anim.res extraction workflow, which seems to be the favorite of some people I asked recently.

What if the "group" concept could be done by the filesystem automatically if a .import file is detected with advanced import settings that extracts to a group of resources? Just an idea.

**Comment by cyraid** [comment]
> What if the "group" concept could be done by the filesystem automatically if a .import file is detected with advanced import settings that extracts to a group of resources? Just an idea.

Yup. You'd have my vote then.

I'll have to check more into the advanced import settings.

**Comment by AThousandShips** [comment]
Does this still apply after:
* #78890

**Comment by lyuma** [comment]
Pretty sure this was fixed.
![image](https://github.com/godotengine/godot/assets/39946030/d46bbb33-52b7-40f9-8e6f-29bde9203548)
Comment or re-open if this issue still happens.
