### ISSUE TITLE
Comma key listed as "Colon". 

### ISSUE THREAD

**Issue by rgrams** [godotengine/godot#6485]
**Operating system or device - Godot version:** 
Any? I'm using the fixnum build from Sept 12th. 64-bit Win 7. 

**Issue description** (what happened, and what was expected):
The comma key shows up as "Colon" in the input map, or from `OS.get_scancode_string`. 

I thought at first this might be some weird keyboard layout thing, but I couldn't find any other keys that have the wrong name associated with them. 

**Steps to reproduce:**
Project Settings >> Input Map >> Add a new "Key" event to any action and press the comma key, it will say "Colon" instead.

**Comment by bojidar-bg** [comment]
Can't confirm on Arch Linux (QWERTY keyboard) - Godot alpha 2.2, no idea which commit exactly.

@rgrams What's your operating system?

**Comment by reduz** [comment]
Maybe a Windows bug

**Comment by akien-mga** [comment]
> What's your operating system?

cf. > 64-bit Win 7.

**Comment by CowThing** [comment]
I can confirm this happens on Windows 10 64bit, using Godot 2.1 stable. I have a QWERTY keyboard if that matters.

**Comment by rgrams** [comment]
Ah, yeah whoops, I forgot to mention it may very well be a Windows thing. If I map something to the so called "Colon" key on windows, then build and try on Linux (Ubuntu), that key doesn't work.

**Comment by vnen** [comment]
I do have some trouble with `OS.get_scancode_string` since I use a keyboard with Brazilian layout. While still a QWERTY, the accents and punctuation are in different places. Godot reports as if it were a US layout.

**Comment by Noshyaar** [comment]
I can't reproduce on Antergos. Could any Windows users confirm that it's still happening?

**Comment by CowThing** [comment]
Yes this still happens on Windows using Godot 3.0.2

**Comment by avencherus** [comment]
@Noshyaar Using Windows 10, just discovered this issue this morning.  The comma is reporting scancode 58.

**Comment by reduz** [comment]
Windows key mappings are here:
https://github.com/godotengine/godot/blob/master/platform/windows/key_mapping_win.cpp
feel free to give a try seeing if it can be fixed

**Comment by avencherus** [comment]
@rodolforg Seems like it, at least from what I can see in my own project.

**Comment by rodolforg** [comment]
I don't use Windows, so I can test it.
