### ISSUE TITLE
Some Controls in the Editor reset to their minimum size after restart

### ISSUE THREAD

**Issue by Mickeon** [godotengine/godot#64851]
### Godot version

v4.0.alpha.custom_build [d0a2a4c98]

### System information

Windows 10

### Issue description

Typically, I recall the editor remembering each panel's proportions, but this no longer happens consistently anymore.

For example, after increasing the Script List's size and restarting the editor, it keeps getting set to its minimum size. This is not the only time this occurs, but it's the most consistent I've been able to document.
![image](https://user-images.githubusercontent.com/66727710/186515399-4b7db68e-98b2-49ba-be56-a0eafadf1f02.png)

### Steps to reproduce

Resize the Script List in the Script Editor, Restart the Editor, look at the Script List again.

### Minimal reproduction project

No need

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/64785.
