### ISSUE TITLE
Editor: Right sidebar gets priority when resizing

### ISSUE THREAD

**Issue by jgillich** [godotengine/godot#64866]
### Godot version

6e390fa9abf2101f8772c4ef6694471153105636

### System information

Fedora Silverblue 36, Ryzen 2400G

### Issue description

The right sidebar gets priority over the main content when resizing the window, and the initial size barely makes a difference:

[Screencast from 25-08-22 05:40:20.webm](https://user-images.githubusercontent.com/347965/186569688-1c5b2807-95bd-4870-be4c-a70abeb413d3.webm)

Doesn't happen with the left sidebar, and it must have been a very recent change, AFAIK my last build from 1-2 days ago did not have this problem. #64800 may be related @KoBeWi 

### Steps to reproduce

1. Resize window? =)

**Comment by Rindbee** [comment]
It may be better to calculate the offset relative to the side of the child control without expand enabled. Currently it seems to be calculated from the left by default.

**Comment by KoBeWi** [comment]
@Rindbee If you have an idea for a fix, feel free to open PR. Otherwise the SplitContainer changes are going to be reverted :/
