### ISSUE TITLE
GDscript is slowed down by new lines and comments

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#6487]
**Operating system or device - Godot version:**
2.x official

**Issue description** (what happened, and what was expected):

I was doing some micro benchmarking to find out best way to optimize my scripts for speed.

And I've discovered that empty lines and comments have an impact on performances.

Indeed, it is more obvious when running the script from the editor or in debug mode.
But the release mode is still affected.

**Steps to reproduce:**

you can test by yourself the minimal project below,
and/or have a direct look at the source here :
https://github.com/SuperUserNameMan/gdscript_micro_benchmarking/blob/master/gdscript_opt_test.gd#L156

basicaly, i've put 100 comments into a for loop, 100 empty lines into an other for loop, etc, and compared the delta time in ms.

In editor/debug mode :
````
100 comments : 2441 ms
100 empty lines : 2472 ms
multi line pass : 274 ms
single line pass : 222 ms
````

In release mode :
````
100 comments : 998 ms
100 empty lines : 1043 ms
multi line pass : 272 ms
single line pass : 249 ms
````

**Link to minimal example project** (optional but very welcome):

https://github.com/SuperUserNameMan/gdscript_micro_benchmarking

**Comment by SuperUserNameMan** [comment]
Edit : indeed this "slow down" is negligible outside of large loops. Which means that it should be  without consequences for most common usage.

**Comment by reduz** [comment]
yeah empty lines are left there with an instruction used for breakpoint.
On release, empty lines are removed.

**Comment by SuperUserNameMan** [comment]
@reduz : i exported to release mode. It is faster, but empty lines still have an impact.
I gave a look at the compiler source code, and it seems to me that only the OPCODE_LINE from the IF statements are removed on release.
But the other OPCODE_LINE seems not filtered :
https://github.com/godotengine/godot/blob/37f1e86108a84c9b371e37c3854d8a03c8aea743/modules/gdscript/gd_compiler.cpp#L1006

**Comment by Zylann** [comment]
Does this means we can break on empty lines? So I can step in blank lines and comments? That's fun :p

**Comment by SuperUserNameMan** [comment]
BTW,

I've found that gdscript performances are dramaticaly lower when godot is cross-compiled with Mingw64 from Linux to Windows.
On IRC, they said it is a known issue.


My micro benchmarking shown that official Godot releases for Windows are up to 10 time faster than custom cross-compiled versions.

**Comment by bojidar-bg** [comment]
I'm thinking... can't we drop OP_LINE, and make an OP_BREAKPOINT instead? That would imply recompiling GDScripts when there is a new breakpoint, but we might be able to resume execution just fine  afterwards ^^.

**Comment by Zylann** [comment]
@SuperUserNameMan this https://github.com/godotengine/godot/issues/4313
