### ISSUE TITLE
[3.x] ShaderMaterial inspector does not show next_pass under Material base

### ISSUE THREAD

**Issue by Jimmio92** [godotengine/godot#64873]
### Godot version

3.5.stable

### System information

Windows 10, AMD Radeon RX590, GLES3

### Issue description

SpatialMaterials inherit from Material which provides a Next Pass parameter, allowing for multiple rendering passes.

ShaderMaterials inherit from Material which for some reason does not provide a Next Pass parameter in the inspector. I assume this parameter exists on the base Material always.

I have confirmed that setting `next_pass` programmatically does in fact work as expected, so I'm even more convinced it's the inspector not showing the property.

### Steps to reproduce

1) Create a MeshInstance
2) Assign a new SpatialMaterial to the surface slot 0
3) Enter into the SpatialMaterial; confirm Material has Render Priority and Next Pass
4) Back out into MeshInstance; assign a new ShaderMaterial replacing the SpatialMaterial in slot 0
5) Enter into the ShaderMaterial; no Next Pass is available under Material, only priority

**Comment by Jimmio92** [comment]
For some reason it wouldn't allow me to attach a minimal reproduction project showing it working as intended when set programmatically.

[next_pass Shader Material.zip](https://github.com/godotengine/godot/files/9422228/next_pass.Shader.Material.zip)

**Comment by clayjohn** [comment]
The ``next_pass`` property appears once you assign a spatial shader to the ``shader`` slot:
![Screenshot from 2022-08-28 16-24-17](https://user-images.githubusercontent.com/16521339/187098928-5368c575-6a7d-4322-89fd-11cd9ec06549.png)

``next pass`` is unavailable when using canvas item and particle shaders, so it doesn't appear until you assign a spatial shader.
