### ISSUE TITLE
Memory leak when resizing FileDialog in Editor, Godot 4.0.alpha14

### ISSUE THREAD

**Issue by Swarkin** [godotengine/godot#64906]
### Godot version

4.0.alpha14

### System information

Windows 10 v.21H2 |Latest nvidia graphics driver v.516.94

### Issue description

FileDialogs dont show the correct content and cause a memory leak when resizing them (both only in editor)
https://drive.google.com/file/d/15uHv6vsXHWwqLiyd9Nnfa_B4vo15HHP8/view?usp=sharing

Worth mentioning; Hiding the FileDialog gets the editor's Ram usage back to ~800mb instantly.

### Steps to reproduce

- Create a FileDialog -> Noticeable visible glitches
- Resize it -> Memory leak and high CPU usage

**Comment by Xstoudi** [comment]
It still happens on master as of c8ef12a03a81c931480be41739ba5789415c4675
CPU usage spike when resizing even if game is not started.
RAM usage spike in both cases.

**Comment by Calinou** [comment]
Can this be reproduced on 3.5?

**Comment by Swarkin** [comment]
I wasnt able to reproduce it there @Calinou.

**Comment by Swarkin** [comment]
Just noticed my stupidity, its alpha 14, not 12.. Sorry

**Comment by YuriSizov** [comment]
Is this still an issue in the latest beta? Can you upload a repro project here, if so?

**Comment by Swarkin** [comment]
@YuriSizov Working in beta13. Not sure if it should change to the `Custom Font` specified in the project settings. I recently switched my GPU from Nvidia to AMD, so maybe should confirm this on Nvidia too?

![image](https://user-images.githubusercontent.com/102416174/213862677-8913098c-7de4-4096-ac56-af4882744ba2.png)

**Comment by YuriSizov** [comment]
> so maybe should confirm this on Nvidia too?

If you suspect it might be the source of this problem, sure.

**Comment by YuriSizov** [comment]
@Swarkin Have you been able to confirm the issue further? If you're going to test it again, please use the most recent version of Godot 4. I'm going to close this issue based on your previous response, but if you still can reproduce it under other circumstances you mentioned, do let me know.
