### ISSUE TITLE
MSVC builds are broken

### ISSUE THREAD

**Issue by SaracenOne** [godotengine/godot#64904]
### Godot version

f03ac21ea8bf04b5ac0243706facdbde45ba7385

### System information

Windows 10, Vulkan, Intel® Core™ i7-8700K, Nvidia GTX 1080 (471.11)

### Issue description

Bisected issue to this #55778. Seems to consistently break with the error 'Arch argument should not be used when using VCINSTALLDIR' when compiling with the Visual Studio toolchain regardless whether the arch argument is absent or any other are seemingly used. Seems to compile fine though if this block of code is outright removed:
```    """Set up env to use MSVC manually, using VCINSTALLDIR"""
    print(env["arch"])
    if env["arch"] != "auto":
        print(
            """
            Arch argument is not supported for MSVC manual configuration (VCINSTALLDIR configured).
            Architecture depends on the Native/Cross Compile Tools Prompt/Developer Console (or Visual Studio settings) that is being used to run SCons.
            As a consequence, the arch argument is disabled. Run scons again without arch argument (example: scons p=windows)
            and SCons will attempt to detect what MSVC compiler will be executed and inform you.
            """
        )
        raise SCons.Errors.UserError("Arch argument should not be used when using VCINSTALLDIR")```
```
### Steps to reproduce

Simply attempt to run SCons with the MSVC toolchain. This is the command I'm using
`"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64 && scons platform=windows`

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
I believe @bruvzg is working on cleaning this up.

**Comment by aaronfranke** [comment]
We should probably have it either allow `auto` or the same value as the MSVC manual configuration's arch, and only error if the arch mismatches what the MSVC configuration is providing.

**Comment by bruvzg** [comment]
I guess custom version of `detect_arch()` to detect environment and set default `arch` value (for both MSVC and MinGW, with a test runs of compiler and windres in case of MinGW), and check for mismatching arch when using `vcvarsall`.

**Comment by akien-mga** [comment]
BTW, this part is not urgent, but the whole Windows `detect.py` seems really convoluted and outdated. It could use a thorough cleanup.

**Comment by SaracenOne** [comment]
Yeah, there are messages to that effect. I know I pointed this whole regression out earlier, but it felt right to properly log this issue as soon as possible so it can be tracked

**Comment by RandomShaper** [comment]
Same here. But it seems it just works if I don't call any of the `vcvars*.bat` before invoking SCons.

Aside, @SaracenOne, `x86_amd64` in your command line has drawn my attention. That's meant for cross-compiling to x64 from a 32-bit host, isn't it? I just call `vcvars64.bat`, which boils down to `vcvarsall.bat" x64` for native x64 compilation.

**Comment by Zylann** [comment]
I don't use `vcvars*.bat` but still get this error when running scons from a VS 2019 command prompt
```
D:\PROJETS\INFO\GODOT\Engine\godot4_fork>scons p=windows target=debug -j4
scons: Reading SConscript files ...

            Arch argument is not supported for MSVC manual configuration (VCINSTALLDIR configured).
            Architecture depends on the Native/Cross Compile Tools Prompt/Developer Console (or Visual Studio settings) that is being used to run SCons.
            As a consequence, the arch argument is disabled. Run scons again without arch argument (example: scons p=windows)
            and SCons will attempt to detect what MSVC compiler will be executed and inform you.

NameError: name 'SCons' is not defined:
  File "D:\PROJETS\INFO\GODOT\Engine\godot4_fork\SConstruct", line 509:
    detect.configure(env)
  File "./platform/windows\detect.py", line 497:
    setup_msvc_manual(env)
  File "./platform/windows\detect.py", line 121:
    raise SCons.Errors.UserError("Arch argument should not be used when using VCINSTALLDIR")
```

**Comment by RandomShaper** [comment]
Do you have the `VCINSTALLDIR` env variable set?

**Comment by bruvzg** [comment]
Here's an almost finished fix (MSVC part should work, but need some extra work on MinGW detection and cleanup) - https://github.com/godotengine/godot/pull/64921

**Comment by Zylann** [comment]
@RandomShaper I don't see it in system or user variables. I don't know if the VS 2019 command line is adding more. I never had to deal with this before.

**Comment by RandomShaper** [comment]
@Zylann, then I guess you can just unset it from Widows advanced settings to have your builds working again even while this issue exists. (Well, or alternatively unset it manually —`SET VCINSTALLDIR=`— on every ocassion.)

**Comment by Zylann** [comment]
Also for some reason my CI builds fine with MSVC https://github.com/Zylann/godot_voxel/actions/runs/2937174477

**Comment by derammo** [comment]
This may be obvious, but unsetting VCINSTALLDIR is not an option for people with multiple installed compilers.     We really should be testing with the officially supported way of doing Visual Studio command line builds (which is via the platform/arch specific command prompts) and not just with the default command prompt.     https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-170

Thanks for already developing a fix bruvzg!
