### ISSUE TITLE
Allow signals to be connected from other objects

### ISSUE THREAD

**Issue by razvanc-r** [godotengine/godot#6492]
At the moment the only way to connect a signal to a method is within the node that emits the signal. Please enhance this so we can connect from other `Node`s as well. It will ease decoupling quite a bit. For example say I have a `game` node that emits the signal `game_over`. I don't want the `game` object to know about a `control` `overlay` node, but I want the `overlay` node to know when `game` emits the `game_over` signal. The only way to do it now is to get `overlay` inside `game` and do `connect("game_over", overlay, "_on_game_over")`. It would be really helpful if we could do something like this inside of the `overlay` node: `connect(game, "game_over", self, "_on_game_over"). In essence saying that `overlay` should observe the `game_over` signal from `game` object and trigger `_on_game_over`. This would mean that the `game` object doesn't need to know about the `overlay`.

**Comment by akien-mga** [comment]
You can already do this. In `overlay.gd`:
```
get_node("path/to/game").connect("game_over", self, "_on_game_over")
```

**Comment by razvanc-r** [comment]
Oh right! How dumb am I :)... completely forgot to reference the node like that... doh! Thanks :)
