### ISSUE TITLE
Increase the default number of "Objects Drawn" to higher number than 4096

### ISSUE THREAD

**Issue by thloh85** [godotengine/godot#6493]
**Operating system or device - Godot version:**
All, tested on Windows 10 Pro and Mac OS X

**Issue description** (what happened, and what was expected):
I tried to create 10k instance of object, but it only renders 4096 of it (from Debugger -> Objects Drawn I can see that), and some objects went undrawn... Is this expected?

**Steps to reproduce:**
As mentioned above

**Link to minimal example project** (optional but very welcome):

**Comment by bojidar-bg** [comment]
Can confirm on arch linux (x86_64 I think), with godot 2.2 alpha (whichever commit happened to be installed at the time, no idea)

**Comment by SuperUserNameMan** [comment]
I rememebr seeing an option to change this number into the project settings. Is this parameter ignored  ?

**Comment by thloh85** [comment]
I don't see any parameters there. Mind to point out which parameters I should be setting?

**Comment by SuperUserNameMan** [comment]
@thloh85 : project settings -> rasterizer -> max_render_elemets = 4096

**Comment by thloh85** [comment]
@SuperUserNameMan : Cool that actually works!!!
I'm changing the title. We should really increase the default number as this will cause confusion for first time users that objects are missing.

**Comment by Zylann** [comment]
Could be good investigating why this option exists? Maybe increasing this number has a downside we don't know of.

**Comment by Sslaxx** [comment]
@Zylann - the most obvious downside that comes to mind is performance.

**Comment by thloh85** [comment]
A quick update from a test that I have. I've updated the max_render_elements to 20000, but still the max "Objects Drawn" is 8192. We may need to look into why it is limited at 8k objects

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
Default max elements is now 65536, closing.
