### ISSUE TITLE
RichTextLabel conversion Color to [color= ]

### ISSUE THREAD

**Issue by DimitriyPS** [godotengine/godot#6494]
**OS All / Godot 2.1**

I already asked the community:
[link](https://godotengine.org/qa/6494/richtextlabel-and-color)

But I never got the right answer. I will repeat here.
I have in the global script there is a variable of type Color. I need to use this color in the tag RichTextLabel [color]. How do I convert to the format of the tag [color]?

If the method to convert exist - advise it to me. If it is not - it is worth adding to GDScript.

**Comment by akien-mga** [comment]
See http://docs.godotengine.org/en/latest/reference/bbcode_in_richtextlabel.html#built-in-color-names

**Comment by bojidar-bg** [comment]
To be fair, `[color=`<kbd>red</kbd>`,`<kbd>green</kbd>`,`<kbd>blue</kbd>`]` might be a good idea...

**Comment by DimitriyPS** [comment]
It's not that. I was hoping You will read the discussion on the [link](https://godotengine.org/qa/6494/richtextlabel-and-color)... But I have already answered there :-)
