### ISSUE TITLE
Replication Subpanel Not Made Visible When MultiplayerSynchronizer is Clicked While in "Script View" 

### ISSUE THREAD

**Issue by Eoin-ONeill-Yokai** [godotengine/godot#64944]
### Godot version

4.0.dev (046c69b2a567)

### System information

Manjaro Linux

### Issue description

Generally, the replication bottom-docked panel will show up when clicking on a MultiplayerSynchronizer node. However, if the user goes into script view while another node is selected (Node3D, for instance) and then tries to click on the MultiplayerSyncrhonizer there, the replication bottom panel will not show up.

### Steps to reproduce

Add a Node3D. Add a MultiplayerSynchronizer child node.
Click on Node3D. And then click MultiplayerSynchronizer. Notice how the bottom panel contents change.
Click back on the Node3D and switch to scripting view.
Now click on MultiplayerSynchronizer. The bottom panel does not update like before.

### Note...
I think that it's probably the most important that this view works in scripting mode, as most networking node interaction will probably happen by users who are actively scripting complicated networked behavior.

**Comment by KoBeWi** [comment]
Can't reproduce in the newest beta.
