### ISSUE TITLE
Editor plugin ability to open given scene in editor

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#6495]
**Issue description** (what happened, and what was expected):
It might be good idea to have a way to open scene file in the editor from EditorPlugin.

**Comment by bojidar-bg** [comment]
That would be nice to extend to all types of resources (probably opening them up in the inspector and/or script editor).

**Comment by kubecz3k** [comment]
@bojidar-bg I specified scene because reduz said he recently added ability to inspect object (so you can load script and inspect it and it will be opened in editor). Not sure how many types are currently supported in this api, but as far as I understand scenes are not.

**Comment by kubecz3k** [comment]
solved by #9566
