### ISSUE TITLE
Godot 4 Master .NET 6 - Crash when loading C# Script resource

### ISSUE THREAD

**Issue by AlmightyLaxz** [godotengine/godot#64953]
### Godot version

4.0.alpha.mono.custom_build [dc4193b47]

### System information

Arch Linux, Headless, 32GB RAM, i9-9900K

### Issue description

While porting a project to master dc4193b47 I encountered many memory related crashes in both the editor and while starting play mode through Jetbrains Rider.

Crash messages in the command line in both the editor and game always look memory related, though half the time there is no message at all. Here's a sample of the crash messages - they are almost always one line with no backtrace.
`free(): invalid pointer`
`free(): invalid next size (fast)`
`malloc(): invalid next size (unsorted)`

With a lot of trial and error and some gdb tracing I've narrowed the 'trigger' down to the loading of a C# Script Resource.
Loading a C# Script Resource through GD.Load(), ResourceLoader.Load() or ResourceLoader.ResourceLoader.LoadThreadedGet() all trigger a crash.
It also crashes when the script Resource is loaded as part of another scene.

I managed to make a very simple reproduction project which loads a Node-derived C# Script Resource 300 times.
Something interesting to note is the crash seems to depend on the number of fields & properties.
On my machine 38 private bools in the loaded class will crash consistently while if there are only 10 it will not crash.

Other notes:
- It seems to be somewhat inconsistent, about 20% of the time I can successfully run my game without a crash
- Things can get into a state where the editor will crash consistently whenever the project is opened, running `dotnet clean` solves it
- I've built the engine on both my main machine and a clean XUbuntu VM, crash is present in both

Installed dotnet-sdk package version is: 6.0.8.sdk108-1

### Steps to reproduce

1. Build the solution
2. Run the project, the crash occurs in headless mode as well as with the GUI, run with headless for more minimal reproduction
`./godot.linuxbsd.opt.tools.x86_64.mono --path "./godot_master_dotnet6_scriptload_crash" --headless`
3. Crash should occur after the first 'About to GD.Load res://Crasher.cs' is output

### Minimal reproduction project

[godot_master_dotnet6_scriptload_crash.zip](https://github.com/godotengine/godot/files/9437657/godot_master_dotnet6_scriptload_crash.zip)

**Comment by raulsntos** [comment]
> On my machine 38 private bools in the loaded class will crash consistently while if there are only 10 it will not crash.

We use a `stackalloc` when the property count is less than 32, otherwise we use `NativeMemory.Alloc` so maybe it's related.
