### ISSUE TITLE
Windows 10: Resize with Win+Arrow and mouse mode confined doesn't always adjust confined area

### ISSUE THREAD

**Issue by goblinJoel** [godotengine/godot#64966]
### Godot version

3.5, also 4.0.alpha14

### System information

Windows 10, GLES2

### Issue description

Similar to https://github.com/godotengine/godot/issues/21768, if I resize the game window while using `MOUSE_MODE_CONFINED`, it keeps confining the mouse to the old area.

This happens if I maximize resize the window with `Win+Up`. It also doesn't work with certain other `Win+Arrow` sequences. It seems to work fine when I snap to the left or right with `Win+Left` or `Win+Right`, but not when I revert by pressing `Win+Right` or `Win+Left`, respectively. (Interestingly, if after doing `Win+Left` and unsnapping with `Win+Right`, I hover over the left edge and click+drag to resize the window, mouse confinement gets dropped entirely.)

At any time, if I Alt+Tab away and then back in, mouse confinement corrects itself.

Just in case it matters, I'm using two monitors (in Extend destkop mode).
I'm using Godot 3.4.5 but checked in 3.5 as well, and it's still an issue there.
I'm using GLES2 and haven't tested GLES3.

### Steps to reproduce

Example sequence showing several glitches.

1. In a `_ready()`, add `Input.set_mouse_mode(Input.MOUSE_MODE_CONFINED)`.
2. Project Settings > Display > Window: enable resizable and set the width/height to something smaller than your screen size.
3. Launch the project
4. Move the mouse around. It is confined to the window area.
5. Press Win+Up to maximize the window. Click in the window and move the mouse around. It is confined to the previous window area.
6. Press Win+Down to revert. Click in it and move the mouse around. It is confined correctly.
7. Press Win+Left to snap the window to the left half of the screen. Move the mouse around. It is confined to the new window area.
8. Press Win+Down to snap to the botton-left. Click inside and move around. Mouse is confined to the previous area.
9. Press Win+Up again, then Win+Right to get back to the original size. It is confined to the left, but you can hover over the left edge. Click and drag it. Mouse confinement breaks.

At any time, if you Alt+Tab away and then back in, mouse confinement corrects itself.

**Comment by Calinou** [comment]
Can you reproduce this on [4.0.alpha14](https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-14)?

**Comment by goblinJoel** [comment]
Surprisingly, yes! I downloaded 4.0.alpha14 win64, made a blank project with a single Node3D that set mouse to confined in _ready(), set the window size to 1280x720 to match what I was doing in 3.5, and got the same results in my reproduction steps.

I did notice I goofed one step in the sequence, which I'll edit. But basically, Win+Up and Win+Down don't appear to change whatever rectangle mouse confinement uses.

**Comment by goblinJoel** [comment]
For any Googlers, here's the workaround I'm currently using:
```
# some node that's always around
func _ready():
	var _err = get_viewport().connect('size_changed', self, '_on_Viewport_size_changed')
	Input.set_mouse_mode(Input.MOUSE_MODE_CONFINED)


func _on_Viewport_size_changed() -> void:
	# print('size changed')
	# workaround for https://github.com/godotengine/godot/issues/64966
	# Win+Up/Down while cursor confined doesn't update confinement rect
	Input.set_mouse_mode(Input.MOUSE_MODE_VISIBLE)
	Input.set_mouse_mode(Input.MOUSE_MODE_CONFINED)
```

This seems to fix it for me by flipping confined mode off and back on whenever the viewport changes size.
