### ISSUE TITLE
Variable wrongly colored as numeric constant

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#64973]
### Godot version

202f0f2

### System information

Windows 10 x64

### Issue description

I think there are some similar issues already but
![image](https://user-images.githubusercontent.com/2223172/187052753-74ea55f6-24c0-4dfd-917e-367d26fc5659.png)
Looks like it tries to interpret `b` as binary literal.

### Steps to reproduce

Try code above.

**Comment by akien-mga** [comment]
Likely a regression from https://github.com/godotengine/godot/pull/63326 @MewPurPur

**Comment by MewPurPur** [comment]
Looking into it.

**Comment by MewPurPur** [comment]
When the highlighter is inside a number, some non-numerical symbols are considered part of the number. `b` is one, there's also `e`, `x`, `.`, and `_`

I'll get it fixed
