### ISSUE TITLE
Godot 4 Alpha 14 Expanding an Exported @tool Array in the Inspector Crashes the Editor

### ISSUE THREAD

**Issue by xCISACx** [godotengine/godot#64979]
### Godot version

v4.0.alpha14.official.106b68050

### System information

Windows 11, Vulkan, RTX 3060 Mobile, 516.94

### Issue description

Creating a tool script with an exported Array, attaching it as a node to another node and attempting to expand the exported array in the Inspector crashes the editor.
After re-opening the project, the exported Array can be expanded as expected.
Dictionaries don't make it crash, for example, but arrays of seemingly any type do.

I made a short gif showcasing this bug so it's easier to understand:

![ToolExportBug4](https://user-images.githubusercontent.com/37281623/187055849-4adb9333-f501-4392-8cdc-1785ad94479f.gif)

### Steps to reproduce

1 - Create a tool script.
2 - Export an array through it using @export.
3 - Add it as a child node to another node.
4 - Attempt to expand the array in the Inspector.

The editor will crash.

Code example:

```
@tool
class_name Class
extends Node2D

@export var array : Array[Vector2i]
```

### Minimal reproduction project

This project will only work the first time it is opened and new exported arrays will need to be created for subsequent times.
[ExportedValueArrayBug.zip](https://github.com/godotengine/godot/files/9439021/ExportedValueArrayBug.zip)

**Comment by EricEzaM** [comment]
Can't reproduce - could you try again and see if you still get it?

**Comment by ChristophTheSchmidt** [comment]
I encountered the same or very similiar bug in beta 2:
[https://github.com/godotengine/godot/issues/67631](url)

**Comment by vnen** [comment]
I can't reproduce this. It might have been fixed as there has been changes on how exported typed arrays are handled.
