### ISSUE TITLE
prints string with quotation mark but sometimes not

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#64976]
### Godot version

v4.0.alpha14.official [106b68050]

### System information

Windows 10, 64bit

### Issue description

![1](https://user-images.githubusercontent.com/35988767/187053584-9beabb04-f34f-4553-a905-30a4dad332ce.PNG)
![2](https://user-images.githubusercontent.com/35988767/187053598-a2276d2a-3c74-4988-9be0-9b0e7d3e4ac2.PNG)

### Steps to reproduce

Please run the reproduction projection.

### Minimal reproduction project

[PrintStringTest.zip](https://github.com/godotengine/godot/files/9438916/PrintStringTest.zip)

**Comment by timothyqiu** [comment]
The JSON representation of string `hello` is `"hello"` (the quotation marks are part of the string).

So `d1` and `d2` _are_ different strings, the same as:

```gdscript
var d1 := '"hello"'
var d2 := 'hello'
```
