### ISSUE TITLE
FXAA exhibits artifacts not present in NVIDIA's reference implementation

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#64985]
### Godot version

4.0 Alpha 14

### System information

Windows 11, Vulkan, Nvidia GTX 1050 Ti, 512.15

### Issue description

Godot's FXAA implementation creates unusual wave-like patterns on the image.
![0 25 FXAA](https://user-images.githubusercontent.com/50302479/187069664-37d643d1-73a7-4075-b295-128909c6a5b1.png)
![FXAA Test](https://user-images.githubusercontent.com/50302479/187069695-77f4488a-28e4-4864-923c-e01b065ae4e1.png)

Comparison (Native res rendering (1.0 render scale), taken in the current dx12 branch for Nvidia Driver FXAA to work):

No FXAA
![No FXAA](https://user-images.githubusercontent.com/50302479/187070294-d2f42485-91a0-41c8-9acb-052cf63f6348.png)

Godot FXAA
![Godot FXAA](https://user-images.githubusercontent.com/50302479/187070309-bbc6580e-bb33-4726-be1b-c0aa16a638a6.png)

Nvidia Driver FXAA
![Nvidia FXAA](https://user-images.githubusercontent.com/50302479/187070343-254095f6-92bf-4810-b1eb-7cd4a58f8c7d.png)

### Steps to reproduce

Add some geometry to look at and enable FXAA.
Lowering the Resolution Scale makes the artifacts easier to see, but they also happen on smaller (screen space) more complex objects at full res

**Comment by Calinou** [comment]
Godot uses a different implementation of FXAA compared to the reference one for simplicity reasons. The official NVIDIA implementation is open source, but it's much more complex as it exposes several quality knows (which are usually not relevant anymore in 2022).

**Comment by clayjohn** [comment]
The screenshots make it look like the sampling coordinates are slightly off leading to some wrapping artifacts. I note especially how in corners like in the "r" and "W" you can see floating pixels.

**Comment by mrjustaguy** [comment]
https://github.com/godotengine/godot/pull/37819 screen shot from implementation also has this issue it seems.. at the top, there's a floating red pixel next to the red box

**Comment by mrjustaguy** [comment]
I've been doing more testing, and 3.5 also suffers from this issue.

**Comment by mrjustaguy** [comment]
I've made a project where I've made a Post Processing FXAA Step, and ported the Godot FXAA to the GDShaders to play around with, and I think I've found what the issue is with Godot's FXAA Implementation.

The Direction Vector is messed up, which would explain why there seem to be sampling issues

`dir.x = -((lumaNW + lumaNE) - (lumaSW + lumaSE));` should only determine the direction based on brightness along the X axis, but if you simplify the terms to `dir.x = -(lumaN-lumas)` you see that if north is brighter, you get a negative value, if the south is brighter, you get a positive value. North and South are on the Y axis, not X axis.
The term should be `dir.x = lumaE-lumaW` (term is simplified) so that when the East is brighter, you get a positive value (pointing right) and when the West is brighter you get a negative value (pointing left), or Inverted, I'm still unclear if dir should point to brighter or darker side.
The same holds true for the Y axis
`dir.y = ((lumaNW + lumaSW) - (lumaNE + lumaSE));` is simplified to `dir.y = lumaW-lumaE` which is wrong for the y axis, and should be `dir.y = lumaS-lumaN`

From testing it doesn't seem like it matters if the direction is pointing from brighter to darker or the other way around, so here's the corrected directions
`dir.x = (lumaNE + lumaSE) - (lumaNW + lumaSW);` (x axis where west is negative, east is positive)
`dir.y = (lumaSW + lumaSE) - (lumaNW + lumaNE);` (y axis where north is negative, south is positive)

**Comment by clayjohn** [comment]
@mrjustaguy Great work! Will you be making a PR?

**Comment by mrjustaguy** [comment]
I don't really use Git so it'd probably be a better idea for someone else to make a PR.

**Comment by clayjohn** [comment]
I wasn't able to get improved visuals with the code changes above. So I looked into the [original source](https://www.geeks3d.com/20110405/fxaa-fast-approximate-anti-aliasing-demo-glsl-opengl-test-radeon-geforce/3/) to see if there is an explanation (there isnt) but I noticed we sample the wrong pixel positions. 

(Zoom in to see differences)
Test scene:
![Screenshot from 2022-09-26 10-57-25](https://user-images.githubusercontent.com/16521339/192355543-c3f341d0-a3dc-49df-bd87-f3cac80db9f4.png)

Test scene with FXAA in master:
![Screenshot from 2022-09-26 10-57-50](https://user-images.githubusercontent.com/16521339/192355902-69528def-c11b-4fc1-a9f3-01ffb62a18a1.png)


Test scene with fix proposed here:
![Screenshot from 2022-09-26 11-03-14](https://user-images.githubusercontent.com/16521339/192355540-67a1cca2-0981-4215-bda8-be8a4016eb43.png)

Test scene without fix from here, but with improved sample positions:

![Screenshot from 2022-09-26 11-30-56](https://user-images.githubusercontent.com/16521339/192355537-c097d648-f7e6-4579-bdfc-27c0132c7ac3.png)

**Comment by mrjustaguy** [comment]
Yeah my bad, the ghosting introduced looked like AA in the case I was testing on and the solution seemed to make sense on the surface..
