### ISSUE TITLE
C#: Exported games fail to load hostfxr

### ISSUE THREAD

**Issue by paulloz** [godotengine/godot#64983]
### Godot version

1f9b992d85fb974c7aa1fadaf2d1b4ff59850137

### System information

Windows 10

### Issue description

Hey 😄 

With the mono module, exported games crash as soon as they start. This happens with templates compiled in `release` and in `release_debug`. My editor itself is built in `debug`.  
Running them through the console script yields the following errors.
```
ERROR: Can't open dynamic library: C:/Users/paulloz/Desktop/Builds/Sandbox/data_Sandbox-G4NET6/hostfxr.dll, error: Error 193: %1 is not a valid Win32 application.
   at: (platform\windows\os_windows.cpp:257)
ERROR: Can't open dynamic library: C:/Users/paulloz/Desktop/Builds/Sandbox/data_Sandbox-G4NET6/Sandbox-G4NET6.dll, error: Error 193: %1 is not a valid Win32 application.
   at: (platform\windows\os_windows.cpp:257)
ERROR: .NET: Failed to load hostfxr
   at: (modules\mono\mono_gd\gd_mono.cpp:435)
```

I believe @raulsntos was saying the same kind of thing occurs on Linux regarding hostfxr. However, the two first errors here may not have their counterpart on other platforms.  

I must note that specifically on Windows 10 (x86_64), exports templates weren't compiling at first. I had to apply the following patch, that I'm not confident is valid, especially the second part.

```diff
diff --git a/modules/mono/mono_gd/gd_mono.cpp b/modules/mono/mono_gd/gd_mono.cpp
index 0532cc915b..16bbc6a672 100644
--- a/modules/mono/mono_gd/gd_mono.cpp
+++ b/modules/mono/mono_gd/gd_mono.cpp
@@ -270,7 +270,7 @@ load_assembly_and_get_function_pointer_fn initialize_hostfxr_self_contained(
        int i = 1;
        for (const String &E : cmdline_args) {
                HostFxrCharString &stored = argv_store.push_back(str_to_hostfxr(E))->get();
-               argv.write[i] = stored.ptr();
+               argv.write[i] = (const char_t *)stored.ptr();
                i++;
        }

@@ -356,7 +356,7 @@ godot_plugins_initialize_fn initialize_hostfxr_and_godot_plugins(bool &r_runtime
        print_verbose(".NET: hostfxr initialized");

        int rc = load_assembly_and_get_function_pointer(get_data(assembly_path),
-                       str_to_hostfxr("GodotPlugins.Game.Main, " + assembly_name),
+                       get_data(str_to_hostfxr("GodotPlugins.Game.Main, " + assembly_name)),
                        HOSTFXR_STR("InitializeFromGameProject"),
                        UNMANAGEDCALLERSONLY_METHOD,
                        nullptr,
```
This is an attempt to fix the following compilation errors.
```
modules\mono\mono_gd\gd_mono.cpp(273): error C2440: '=': cannot convert from 'const char16_t *' to 'T'
        with
        [
            T=const char_t *
        ]
modules\mono\mono_gd\gd_mono.cpp(273): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast)
modules\mono\mono_gd\gd_mono.cpp(359): error C2664: 'int (const char_t *,const char_t *,const char_t *,const char_t *,void *,void **)': cannot convert argument n from '`anonymous-namespace'::HostFxrCharString' to 'const char_t *'
modules\mono\mono_gd\gd_mono.cpp(359): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
```

### Steps to reproduce

Should be really easy to reproduce:
* Create a project
* Add a C# script
* Export
* Run the exported game

**Comment by raulsntos** [comment]
In your case it seems the `hostfxr.dll` exists but could not load it, I don't know enough about the Windows platform to know what may be the cause (it also seems unable to load the game DLL).

The error I'm getting in Linux is just `ERROR: .NET: Failed to load hostfxr` but in my case `libhostfxr.so` does not exist in the assemblies dir. I looked into this and found that it was using RID `linux-x86` instead of `linux-x64` because we determine the arch by looking at the features and the feature for 64bits arch was renamed, I wish it would have failed exporting instead of publishing an invalid output though :pensive:

**Comment by neikeq** [comment]
> I wish it would have failed exporting instead of publishing an invalid output though 

That's because the 32-bit part is done as a fallback instead of checking if the bits was in the features list like we do with 64-bit. We should change that (specially now that we will be adding arm in the future) and throw when no arch is detected.

**Comment by paulloz** [comment]
> Your patch makes sense to me but I'm also not confident enough to approve it 😅. You can open a PR and wait for **neikeq** to review it.

I will dig a bit more into it based on your branch and do that 👍

**Comment by TopherLee513** [comment]
I can't find anywhere else to bring this up, so I'm not sure if it's a unique issue from something I did wrong or if more users are affected... Anyway: Linux Mint 21 / Ubuntu 22.04 Jammy

Most of the errors I've gotten associated with hostfxr have been fixed by:

- Uninstalling dotnet-sdk-6.0 that I installed using packages.microsoft

```bash
sudo apt purge dotnet* && sudo apt purge aspnetcore*
sudo rm /etc/apt/sources.list.d/microsoft-prod.list
```
- and installing dotnet-sdk-6.0 from Jammy repositories

 ```bash
sudo apt update && sudo apt install dotnet-sdk-6.0
```

Source: https://github.com/dotnet/core/issues/7699

However, Godot is still trying to load fxr from "/usr/share/dotnet/host/fxr" when it's installed to "/usr/lib/dotnet/host/fxr"...
But it's not crashing now and I can edit and build seemingly fine.

**Comment by blubbers122** [comment]
> I can't find anywhere else to bring this up, so I'm not sure if it's a unique issue from something I did wrong or if more users are affected... Anyway: Linux Mint 21 / Ubuntu 22.04 Jammy
> 
> Most of the errors I've gotten associated with hostfxr have been fixed by:
> 
> * Uninstalling dotnet-sdk-6.0 that I installed using packages.microsoft
> 
> ```shell
> sudo apt purge dotnet* && sudo apt purge aspnetcore*
> sudo rm /etc/apt/sources.list.d/microsoft-prod.list
> ```
> 
> * and installing dotnet-sdk-6.0 from Jammy repositories
> 
> ```shell
> sudo apt update && sudo apt install dotnet-sdk-6.0
> ```
> 
> Source: [dotnet/core#7699](https://github.com/dotnet/core/issues/7699)
> 
> Set the environment variable DOTNET_ROOT to the dotnet install path: For me:
> 
> ```shell
> export DOTNET_ROOT=/usr/lib/dotnet
> ```


The exact issue I was running into. It works for me now after making those changes. Thanks so much for sharing!
