### ISSUE TITLE
Vulkan: Setting volumetric fog size and depth to 512 causes severe visual glitches

### ISSUE THREAD

**Issue by josefkaragoli** [godotengine/godot#64998]
### Godot version

006915b4824a91c0e0fc95ac6aa2f70908a0a027

### System information

i7 6700K, 32GB ddr4 memory, gtx 1060 6gb

### Issue description

 I accidentally set volumetric fog size and volumetric depth to 512 which caused the engine to crash, upon reopening the engine looks like this:
![image](https://user-images.githubusercontent.com/76781125/187089070-8709a810-6f73-4245-8d88-56a700e883ba.png)

I attempted to clear my shader cache in appdata and in project folder but it didn't work

### Steps to reproduce

- Go into project settings 
- Set volumetric fog size and volumetric depth to 512

### Minimal reproduction project

This seems to be project-independent

**Comment by Calinou** [comment]
> I accidentally set volumetric fog size and volumetric depth to 512 which caused the engine to crash, upon reopening the engine looks like this:

This is a project setting, so it should have no bearing on the project manager as it doesn't read any project settings.

**Comment by josefkaragoli** [comment]
Recompiling the engine solved the issue.
