### ISSUE TITLE
No node path highlight in `for` loop

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#65008]
### Godot version

v4.0.alpha.custom_build [4f1a98fc4]

### System information

Windows 10 x64

### Issue description

![image](https://user-images.githubusercontent.com/2223172/187095637-858c780b-a94f-4f79-8137-2ce96ad057dc.png)
![image](https://user-images.githubusercontent.com/2223172/187095611-c6899a75-cb3e-4fc9-bc88-a5562b1bac14.png)
NodePath is not recognized inside a loop. Probably another issue from https://github.com/godotengine/godot/pull/63326
CC @MewPurPur

EDIT:
Another similar case:
![image](https://user-images.githubusercontent.com/2223172/187098016-5780fbbe-a334-44d3-a717-b9099800be8e.png)

### Steps to reproduce

See code above.

**Comment by MewPurPur** [comment]
Oh damn, I didn't think of this...

Basically, the `is_binary_op` check misfires as it thinks `else` is a variable. Tough luck, I'm starting to think the tokenizer would be necessary to get proper highlighting here.
