### ISSUE TITLE
LSP not offering signal name completion in 3.5

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot#65000]
Given the following script:

```gdscript
extends Spatial

func _ready():
	get_tree().create_timer(1.0).connect("ti<cursor_here>
```

In 3.4, the LSP will offer "timeout" as a completion.
In 3.5, the LSP will not offer any completions.

This sounds similar to https://github.com/godotengine/godot/issues/64666, but in this case, instead of offering a completion that inserts empty text, the LSP is not offering a completion at all.

I'm using neovim's 0.7.2's builtin lsp client.

**Comment by rcorre** [comment]
Apprently `gh` cli bypasses the form. Sorry.

**Comment by Calinou** [comment]
Superseded by https://github.com/godotengine/godot/issues/65001.
