### ISSUE TITLE
Cannot find property "xform" on base "Basis"

### ISSUE THREAD

**Issue by tinmanjuggernaut** [godotengine/godot#65004]
### Godot version

Godot 4 Alpha 14

### System information

Windows 11/64, RTX 3070, Vulkan

### Issue description

`Basis.xform()` is in the [Basis class](https://github.com/godotengine/godot/blob/9efa5a8fc9ce6bfc375511ebe1deeec7ad5ef42a/core/math/basis.h#L304) ~~and it appears to be bound~~, however it doesn't work.

```
var bone_transf_obj: Transform3D
var bone_rotate_axis_obj: Vector3 = bone_transf_obj.basis.xform(bone_rotate_axis)

# Cannot find property "xform" on base "Basis".
# Function "xform()" not found in base Basis.

```

### Steps to reproduce

See above.

**Comment by akien-mga** [comment]
It has been replaced by directly using the `*` operator (`basis * vec` for xform, the other way around for xform_inv). But it's weird that there would still be a binding for it, it might be an oversight.

**Comment by tinmanjuggernaut** [comment]
There is no exposure to GDScript or the manual pages. I was just looking through the C++ code.

I compared the results of [the C++ code](https://github.com/godotengine/godot/blob/9efa5a8fc9ce6bfc375511ebe1deeec7ad5ef42a/core/math/basis.h#L304) in gdscript with the results from the * operator and the return value Y is negative, all the time. I don't know if that matters:

```
Vector3 Basis::xform(const Vector3 &p_vector) const {
	return Vector3(
			rows[0].dot(p_vector),
			rows[1].dot(p_vector),
			rows[2].dot(p_vector));
}

func xform(p_basis: Basis, p_vec: Vector3) -> Vector3:
	return Vector3(p_basis.x.dot(p_vec), p_basis.y.dot(p_vec), p_basis.z.dot(p_vec))

# Results from xform(): (-.991, -0.012, -0.135)
# Results from * operator: (-.991, 0.012, -0.135)
```

**Comment by akien-mga** [comment]
The C++ code operates on rows but your GDScript reproduction operates on columns (axes).

**Comment by tinmanjuggernaut** [comment]
Ok, thanks. I was also looking in the wrong C++ file. I don't see any binding.
