### ISSUE TITLE
Constructor never called in editor in C# 4.0

### ISSUE THREAD

**Issue by markdibarry** [godotengine/godot#65007]
### Godot version

4.0.dev (f38ea254f3)

### System information

Windows 10

### Issue description

When a constructor is defined in a script, it is not called in the editor unless it's a tool script. This locks setting script export default values to constant property defaults, and prevents any way of overriding defaults in inherited scripts.

### Steps to reproduce

Create a script with an exported property, and set the value in a constructor.
Note in the editor the value stays the default for that type.

Alternatively, call `GD.Print()` in a scripts constructor.
It will not be displayed when the scene is opened.

### Minimal reproduction project

[ConstructorBug.zip](https://github.com/godotengine/godot/files/9440503/ConstructorBug.zip)

**Comment by Calinou** [comment]
cc @neikeq

**Comment by neikeq** [comment]
This was changed on purpose because calling the constructor was confusing to many users. The source generator creates a static method that returns the default values. I think it's the same in GDScript (values set in `_init()` have no effect on the default value).

**Comment by markdibarry** [comment]
That's interesting. Good to know it was an intentional change. Is there any planned way to allow for default values to be set in inherited classes, or calculated values?

**Comment by lyuma** [comment]
@markdibarry I asked in RocketChat and was told that the best way to allow custom values in constructor or overrides of virtual functions such as [_GetPropertyList](https://haxegodot.github.io/godot/godot/Object.html#_GetPropertyList)() was to declare the class `[Tool]` and add a bit of code into the ready function (you may need other checks for physics_process, process_internal and so on.)
This is how you'd do it in GDScript
```gd
func _ready():
    if Engine.is_editor_hint():
        set_process(false)
        return
```

Here's the equivalent code in C#
```cs
public override void _Ready()
{
    if (Engine.isEditorHint()) {
       setProcess(false);
    }
}
```

I come from Unity and I appreciate that they allow class instances to exist in editor, but do not call any Start or Update methods unless you add `[ExecuteInEditMode]`. I had expected Godot's `[Tool]` to act the same way, but it seems that it avoids instantiating the class entirely in the editor, and instead holds onto the values in the inspector in a sort of placeholder object.

I personally think the change to non-tool classes is a mistake and creates more work to do certain simple things. But once you know the system and you know how to use tool scripts while avoiding unwanted process events, the workaround will get the job done.

**Comment by markdibarry** [comment]
@lyuma Thanks for the research! For the most part, my test projects in 4.0 over the last year have been as you say. This all-or-nothing choice does unfortunately force a significant amount more setup to add basic non-static defaults, regardless of how simple or complex a scene is, but it makes complete sense to keep it consistent with GDScript.

For reference for anyone else looking for this functionality, the best workaround I've found to allow for a basic constructor-esque setup (and have recommended to others the past few months) is to make every script in each project a tool script by default. This can be very dangerous, and can have a lot of unintended consequences, but it helps if you make a series of extension methods to determine if the script is being run:
- In Editor
- In Single Scene Debug Mode
- In Game

This may seem a little overkill, but with Godot providing so many very different scenarios of how code is executed (and how the tree is arranged), tool scripts lead to very difficult debugging and hard to track errors, so a defensive system is important. This does make things more complex, and I'm sure this does have some performance cost, but it does make it a much better and more flexible system than currently provided. Once you commit to this format, adding a basic constructor is very easy.

I'm going to keep this open for the next day, just for any further comments, otherwise I'll close this as unplanned.

**Comment by neikeq** [comment]
To be clear, I'm open to hearing more about this. If there's a general opinion that this should be changed back, I'm fine with that. But we need more voices. This was changed due to many reports, so it can't be changed back without more feedback.

**Comment by paulloz** [comment]
My two cents: I think the current 4.x behaviour is more logical / better. The fact constructors were secretly called in editor always seemed like a quirk and caused a lot of confusion. I think with lots of people having learned the ins and outs, and having put together workarounds in Godot 3, we're bound to see a few issues among the lines of "I used to do x because of y and now it doesn't work".

**Comment by neikeq** [comment]
One thing I'm considering is adding an alternative to `[Tool]` that constructs the object and keeps it attached, but doesn't call other methods. That could be useful for those who want the old behaviour. Also it wouldn't be a hacky solution like the temporary object workaround was in 3.x.
