### ISSUE TITLE
Gdscript: It's impossible to override _process function

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#6500]
**Operating system or device - Godot version:**
Godot 2.1 stable

**Issue description** (what happened, and what was expected):
When you override `_process` method in script that's an offspring, and the ancestor have it's own implementation of `_process` both implementation will be called (first the offspring then ancestor).

**Steps to reproduce:**
Extend script with logic inside `_process` and override this method. Both implementations will be called.

**Link to minimal example project** (optional but very welcome):
[OvverrideProcess.zip](https://github.com/godotengine/godot/files/475028/OvverrideProcess.zip)

**Comment by bojidar-bg** [comment]
Well, that's fully intended :smile:

**Comment by reduz** [comment]
This is a feature, not a bug (it's documented) you can try calling another
function
from _process and override that

**Comment by reduz** [comment]
callbacks get called at all levels, back when we had Squirrel programmers
used to forget calling the parent functions all the time for callbacks they
handled different and it was kind of a mess.

**Comment by kubecz3k** [comment]
What I can say? All that time I'm writing in gdscript and was not aware of that. I believe I had problem with this in the past... will need to recheck my projects :P

**Comment by gloryofrobots** [comment]
I found notion of this feature only in one place

> However, remember that functions such as _init, and most notifications such as _enter_tree, _exit_tree, _process, _fixed_process, etc. are called in all base classes automatically, so this should be only for calling functions you write yourself.

I think, it needs to be written in big red caps letters

**Comment by MelimeliDev** [comment]
@gloryofrobots 
That... needs to be in documentation... Somewhere in here:

http://docs.godotengine.org/en/latest/reference/gdscript.html

**Comment by vnen** [comment]
I still think it would be better to not call the parent callback automatically. The current behavior is not flexible and you can't count which function will be called first, if the parent or the child. In my experiments, `_process` is called by the child class first but `_ready` runs in parent class first.

I can see the use in doing something like this:

```gdscript
func _process(delta):
    # prepare stuff for parent calculations
    ._process(delta) # call parent process
    # process something with parent's results
```

This has the same problem as `_init()` and hinders the possibilities of OOP design.

**Comment by gloryofrobots** [comment]
In parents  I use something like this

```gdscript
func _on_process(delta):
    pass

func _process(delta):
    _on_process(delta)
```
And in subclasses I still can  forget to call ```._on_process()```
 It would be better to not call the parent callback automatically, but if it is really necessary, maybe it would be better just to forbid overriding of special methods like _process

**Comment by Sslaxx** [comment]
If processing order of inherited and parent functions is unpredictable then that should be classified as a bug.

**Comment by gloryofrobots** [comment]
How about separate keyword for special methods?
```gdscript
method _ready(delta):
     # I will call parent _ready automatically
     pass

func _my_ready(delta):
     # I will call parent _my_ready manually
     ._my_ready(delta)
```

**Comment by Zylann** [comment]
I wonder why this is closed, it looks quite relevant to me.

**Comment by jaacko-torus** [comment]
I honestly find it quite counter intuitive. And I find what @vnen to much better as it is very explicit and you don't have to search and go into the rabbit hole that is godot issues page to find why it works the way it does.

**Comment by douglasvini** [comment]
this is a confusing "feature", is not intuitive, and is illogical in a OOP mindset. i got frustrated a lot before i discover this is intended.

**Comment by SamuelNewhouse** [comment]
I'm lucky I stumbled across this issue. I've spent days trying to figure out why something wasn't working properly and it turns out this is the problem. This is completley unintuitive considering it's the opposite of how every other engine and OOP in general works.

**Comment by mrimvo** [comment]
I can understand the reasoning and I do support the way these functions are called, but it still causes serious problems when trying to extend engine classes. Because you have no chance to control if and when the hard coded super class methods will be called. As a result, _extending engine classes in GDScript is barely supported_ in the moment, [see also this issue](https://github.com/godotengine/godot/issues/38294).

I thought quite a bit about it, and from the various options available, I think this one might be the best: introduce a new keyword `override`:

```
override func _process(delta):
  if we_want:
    ._process(delta)
```

So essentially, `override` will prevent to super classes' implementations of this function to be called. The user opts-in to that behavior and is then able to call the super method when/if he wants.

I might open another ticket with this proposal, since extending engine-classes is something that is essentially broken in godot the moment.

**Comment by bluenote10** [comment]
@vnen Do you have plans to touch this topic for your big (and great!) 4.0 refactorings?

What about the following solution:

1. We could leverage annotations (https://github.com/godotengine/godot-proposals/issues/828) to opt-out from auto base calls. For instance, your example would become:

```gdscript
@no_auto_basecall
func _process(delta):
    # prepare stuff for parent calculations
    ._process(delta) # call parent process
    # process something with parent's results
```

This would also allow to completely omit the base call, achieving true `override` semantics.

2. Methods without `@no_auto_basecall` would still have an implicit base call, but ideally in a well defined order, i.e., consistently parent class first, or child class first. By defaulting to the old behavior, the feature should be largly backwards compatible.

**Comment by Calinou** [comment]
@bluenote10 This behavior was already removed in the GDScript rewrite. The documentation has been updated accordingly.

**Comment by bluenote10** [comment]
@Calinou Thanks for the hint. I've indeed found [some code](https://github.com/godotengine/godot/blob/6d4d8349b69fb1f80e0b62c0f57ad8de0818f577/modules/gdscript/gdscript_parser.cpp#L2395-L2418) on the `godot/master` branch, which indicate the change you mention. But on `godot-docs/master` the [`gdscript_basics.rst`](https://github.com/godotengine/godot-docs/blob/master/getting_started/scripting/gdscript/gdscript_basics.rst) still seens to document the 3.2 behavior with implicit super calls.

<details>
<summary>Relevant section</summary>

---

![image](https://user-images.githubusercontent.com/3620703/89036750-853c2a80-d33d-11ea-8ec7-b2bd8f63a09a.png)
</details>

Would be curious to read up on the planned solution.

**Comment by Calinou** [comment]
@bluenote10 The [pull request updating the documentation](https://github.com/godotengine/godot-docs/pull/3623) hasn't been merged yet, that's why.

**Comment by TheBeautifulOrc** [comment]
This annoyed me as well, so I made a proposal (https://github.com/godotengine/godot-proposals/issues/2162).

**Comment by levilindsey** [comment]
Is there a list of all such non-overridable functions anywhere? Again and again, I find that it would be super helpful for my work if I had any way of knowing whether a given built-in function is overridable.

It gets pretty tedious having to figure it out each time by overriding a function, adding print statements in different places, and running my game.

**Comment by akien-mga** [comment]
@levilindsey That's fixed in `master`, but in 3.x the methods which get called at multiple levels are the virtual engine callbacks defined in `Node` and `Object`, such as `_ready`, `_process`, `_input`, etc. Basically the methods starting with an underscore and marked virtual in https://docs.godotengine.org/en/stable/classes/class_node.html and https://docs.godotengine.org/en/stable/classes/class_object.html

Maybe a few more similar ones like `_draw` in `CanvasItem`.

Those methods are "entry points" for the engine to run the main loop, which is why they historically behaved differently from common OOP/class inheritance expectations.
