### ISSUE TITLE
When using AnimationNodeStateMachine as the root of AnimationTree, BlendTree and Animation nodes do not appear in AnimationTree Parameters

### ISSUE THREAD

**Issue by wmsteinhardt** [godotengine/godot#65002]
### Godot version

4.0 alpha14

### System information

Windows 10

### Issue description

![StateMachineProblem](https://user-images.githubusercontent.com/46137605/187092907-a6da68eb-acb5-4b13-a0c4-85cd77762bf4.JPG)

I have been trying to use a State Machine as the root node of my AnimationTree.  

However, I noticed that after adding Animation and BlendTree nodes to my State Machine, they do not appear as Parameters - I am therefore unsure how to access their properties with code, since using the AnimationPlayer methods directly does not work when using the AnimationTree.

### Steps to reproduce

1. Create new scene with AnimationPlayer and AnimationTree nodes as children of a node that does have animations (necessary to add animations to the State Machine)
2. Configure target of the AnimationTree to be the AnimationPlayer as usual.
3. Add one of each object (Blendspace1D, Blendspace2D, State Machine, BlendTree, Animation) to the State Machine root.
4. Note that neither BlendTree nor AnimationTree are present in the parameters.

### Minimal reproduction project

[AnimationTreeStateMachineRoot.zip](https://github.com/godotengine/godot/files/9440451/AnimationTreeStateMachineRoot.zip)

**Comment by lyuma** [comment]
The included project did not contain any nodes in the BlendTree which had parameters, so it is expected behavior to have no parameters in the inspector for that BlendTree.

If I add a TimeScale node into the BlendTree, the properties indeed show up in the inspector:
![image showing BlendTree with a TimeScale node](https://user-images.githubusercontent.com/39946030/187096278-06db5675-67c7-4b5d-87df-82bc0894495c.png)

Let me know if there is something I missed.

**Comment by lyuma** [comment]
Pasting some discussion from Discord:

> I was just looking for any means to modify Animation parameters from code when using the StateMachine root
> Like playback speed and direction

Playback speed is controlled with a TimeScale node as I show in my screenshot
direction may be configurable with a negative timescale.

> so I have to use a BlendTree?
> Like if you have a StateMachine that just has the AnimationNodes, you cannot control playback speed?
> They have to be within BlendTrees?

That's a good question. I believe yes, you need to make a simple BlendTree with a TimeScale node and the Animation node for each animation with a custom speed
![image showing BlendTree parameters](https://cdn.discordapp.com/attachments/908062856459743262/1013571271440748634/unknown.png)
