### ISSUE TITLE
Remote tree is uneditable

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#65034]
### Godot version

0024ba8

### System information

Windows 10 x64

### Issue description

![](https://chat.godotengine.org/file-upload/AosAfzj6GNmE7sQQP/Clipboard%20-%2029%20sierpnia%202022%2013:56)
All controls are disabled. Might be caused by #63282
CC @SaracenOne 

The remote tree was bugged anyway (#54977), so this is a mildly serious issue.

### Steps to reproduce

1. Run a project
2. Open remote tree
3. Click node

**Comment by Zireael07** [comment]
Drive by: remote tree also seemed to have (before this regression) focus problems. I'll be looking at one node, then the remote tree refreshes or something and goes back to another node, and even clicking on back/forth arrows won't help, it'll just decide to basically get stuck on this one.
