### ISSUE TITLE
In the game mode, the vehicle wheels are displayed as in a mirror.

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#6503]
**Operating system or device - Godot version:**
Ubuntu 16.04

**Issue description** (what happened, and what was expected):
In the game mode, the vehicle wheels (mesh) are displayed as in a mirror.

**Link to minimal example project** (optional but very welcome):
[Test project.zip](https://github.com/godotengine/godot/files/475352/Test.project.zip)
![2016-09-15 23-55-01](https://cloud.githubusercontent.com/assets/11325733/18559517/1d8319f6-7baa-11e6-89f2-6f64a5a89613.png)

**Comment by kubecz3k** [comment]
@DimaKiva Would you be able to provide sample project?

**Comment by bojidar-bg** [comment]
Are you scaling them by any chance?

**Comment by DimaKiva** [comment]
> sample

[Test project.zip](https://github.com/godotengine/godot/files/475352/Test.project.zip)

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.
