### ISSUE TITLE
GLES2 Viewport in 2D mode with enabled HDR shows warning but HDR can't be disabled through the inspector

### ISSUE THREAD

**Issue by kleonc** [godotengine/godot#65033]
### Godot version

3.5.stable

### System information

N/A

### Issue description

- `Viewport.hdr = true` by default,
- HDR is not supported in GLES2 hence not shown in the inspector (thus can't be disabled),
- HDR is not supported for `USAGE_2D`, `USAGE_2D_NO_SAMPLING` hence a warning is shown in such case.

Meaning in GLES2 viewports set to 2D usage by default show a HDR warning (while HDR is not supported in GLES2 anyway) which you can't easily get rid of. You'd need to manually edit the scene file to add `hdr = false` override or temporarily switch to GLES3 to turn it off in the inspector.

cc @Calinou (#49967). Probably this warning shouldn't be shown in GLES2 at all?

### Steps to reproduce

1. Create GLES2 project.
2. Add Viewport node, set some size to it, set it's mode to `USAGE2D`.
3. See the warning with no way to disable HDR in the inspector:
![Godot_v3 5-stable_win64_So0c6ZpdCp](https://user-images.githubusercontent.com/9283098/187187880-3c8ddf7d-b56f-43a5-b438-f65167960650.png)
![ekbUmH1Y1d](https://user-images.githubusercontent.com/9283098/187187882-24408e32-c45d-4d25-9dc2-2d8434e3d00c.png)

**Comment by Calinou** [comment]
> Probably this warning shouldn't be shown in GLES2 at all?

Indeed, this warning shouldn't be displayed in GLES2 as that renderer lacks HDR support entirely.

**Comment by akien-mga** [comment]
Fixed by #65063.
