### ISSUE TITLE
Skeleton bones have invalid icons

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot#65037]
### Godot version

v4.0.alpha.custom_build [e60086f98]

### System information

Arch on 5.19.2-arch1-1

### Issue description

![image](https://user-images.githubusercontent.com/14253836/187203737-e72ddbb8-1a61-4d00-b9d9-ef7631be6e9c.png)

### Steps to reproduce

Open MRP, right click mesh, new inherited scene, click skeleton

### Minimal reproduction project

Just copied this MRP from # 56458
[BoneAABBWarnings.zip](https://github.com/godotengine/godot/files/9444587/BoneAABBWarnings.zip)

**Comment by TokageItLab** [comment]
Maybe related by #65044

**Comment by YuriSizov** [comment]
> Maybe related by #65044 or #63358?

Very unlikely.

**Comment by YuriSizov** [comment]
It's probably a regression from https://github.com/godotengine/godot/pull/62845. `Skeleton3DEditor` doesn't seem to have any code that would react on the editor theme changes. Instead it only updates itself on enter tree. And after https://github.com/godotengine/godot/pull/62845 we don't have the theme available on ENTER_TREE.

While this is technically a regression from https://github.com/godotengine/godot/pull/62845, the solution is to properly handle THEME_CHANGED notification, as does the rest of the editor.
