### ISSUE TITLE
Collisions with `WorldBoundaryShape2D` do not take margin or motion into account

### ISSUE THREAD

**Issue by rburing** [godotengine/godot#65047]
### Godot version

4.0-alpha14

### System information

any

### Issue description

![worldboundaryshape2d_margin](https://user-images.githubusercontent.com/229837/187239913-22dbd239-a123-4115-9eaa-b1b2c34a9e1c.png)

### Steps to reproduce

1. Create a `StaticBody2D` node and add a `WorldBoundaryShape2D` collision shape.
2. Create a `CharacterBody2D` with the default script and add a collision shape.
3. Place the character on top of the world boundary.
4. Run the scene. Expect to be able to move on the boundary, watch the character being unable to move.

### Minimal reproduction project

[BouncyWorldBoundary2D.zip](https://github.com/godotengine/godot/files/9445982/BouncyWorldBoundary2D.zip)

**Comment by Calinou** [comment]
Can this also be reproduced in 3.x? What about 3D?

**Comment by rburing** [comment]
The 3D issue is https://github.com/godotengine/godot/issues/61080 which I fixed in https://github.com/godotengine/godot/pull/64936.

From a glance, `3.x` is missing the same code that I added to fix the issues in `master`, so `3.x` has the same issues.

The PRs should be trivial to backport.
