### ISSUE TITLE
Duplicate Search menu in script editor

### ISSUE THREAD

**Issue by gau-veldt** [godotengine/godot#6505]
**Operating system or device - Godot version:**
x11 Godot 2.2a dc6eefdbf2b3f9362dbb571e9fb2f3df60760c04

**Issue description** (what happened, and what was expected):
I get a bug where there's two search menus?!?!?
(see the screenshot).  Vanilla 2.2a editor,no plugins.
![screenshot](https://cloud.githubusercontent.com/assets/1862162/18560284/c972dca4-7b2f-11e6-87c7-c302ffd65ccc.png)
When this is happening CTRL+F fails to work.

May be related to #6471

**Steps to reproduce:**
Use the script editor in course of ordinary use.  At some point, it happens.

**Link to minimal example project** (optional but very welcome):

**Comment by akien-mga** [comment]
I don't see anything wrong on this screenshot...

**Comment by akien-mga** [comment]
Oh ok I finally spotted it.

**Comment by gau-veldt** [comment]
Maybe I should have circled the menu.  It wasn't meant to be a page out of Where's Waldo, but rather an unedited screencap of the problem.

**Comment by bojidar-bg** [comment]
To explain for those that can't see it yet: The top script bar has "File, Search, Edit, **Search**, Debug" displayed

**Comment by Faless** [comment]
I found a way to reproduce this:

1. Open the script editor and have at least one open script and no open help tabs.
2. Press "Classes" and open any class (eg. "Object")
3. Close the newly opened help tab with ctrl+w.
4. bug appears
