### ISSUE TITLE
reload is falsely(?) detected as a built-in function

### ISSUE THREAD

**Issue by jgillich** [godotengine/godot#65058]
### Godot version

051f24b067642a241d0a4acbb1b7644e11700bfc

### System information

Fedora Silverblue 36, Ryzen 2400G

### Issue description

Valid: defining a `reload` function
```gdscript
class B:
	func reload():
		pass
```

Not valid: defining `reload` on a class that extends a custom class
```gdscript
class A extends Node3D:
	func abc():
		pass
		
class B extends A:
	func reload():
		pass
```
```
Line 6:The function signature doesn't match the parent. Parent signature is "int reload(bool = default)".
```

Valid again if the parent class also defines `reload`

```gdscript
class A extends Node3D:
	func reload():
		pass
		
class B extends A:
	func reload():
		pass
```

But if we try to call `reload`, it tells us it doesn't exist
```gdscript
class A extends Node3D:
	func abc():
		pass
		
class B extends A:
	func abc():
		reload()
```
```
Line 7:Function "reload()" not found in base self.
```

I have no idea what's right or wrong here as I could not find a built-in `reload` function, but the compiler result is clearly very inconsistent.

### Steps to reproduce

See above

**Comment by KoBeWi** [comment]
`reload()` is a method in Script class.

**Comment by jgillich** [comment]
I see, so the real issue here is that this works at all, right?

On a related note: There is a large number of common words used by built-in functions. The rename from `update` to `queue_redraw` is a really good move, perhaps we could take a similar step here and rename `reload` to `reload_script`?

**Comment by KoBeWi** [comment]
Well `reload()` is a function of Script, so it should only be available in *Script objects* (i.e. objects of class Script), while the scripts attached to nodes are *script instances*. So there is definitely some bug here, especially if it's inconsistent.

**Comment by vnen** [comment]
This is the same as #71994, it is already fixed.
