### ISSUE TITLE
Insert keyframe button uses old "rect_" Control members

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#65071]
### Godot version

v4.0.alpha.custom_build [dfc76dc26]

### System information

Linux

### Issue description

The auto-keyframe functionality uses "rect_position", "rect_size" etc, which got renamed.

### Steps to reproduce

* Add a control node and an animation player
* Create an animation and enable autokeyframes
* Move and rotate the node
* Observe the error or a crash:

`  scene/animation/animation_player.cpp:1104 - Failed setting key 'rect_rotation' at time 0 in Animation '' at Node '/root/@@15089/@@633/@@634/@@643/@@645/@@651/@@657/@@658/@@659/@@681/@@682/@@720/@@721/@@8664/@@8493/@@8494/@@8495/@@8496/@@8497/@@8498/AnimationPlayer', Track '.:rect_rotation'. Check if the property exists or the type of key is right for the property`

**Comment by akien-mga** [comment]
Did you mean to close this?

**Comment by Jummit** [comment]
Yes, sorry, I should've made that clear. I was using an outdated version of Godot 4.
