### ISSUE TITLE
Scene not saving while using CTRL+S when in full script view (CTRL+Shift+F11)

### ISSUE THREAD

**Issue by Tybobobo** [godotengine/godot#6508]
**Operating system or device - Godot version:**
v2.2.alpha.custom.build

**Issue description** (what happened, and what was expected):
~~Script~~ _Scene_ not saving using CTRL+S when in full script view (CTRL+Shift+F11)

**Steps to reproduce:**
1. Open existing script
2. Press CTRL+Shift+F11 (to enable full script view)
3. Make changes until you see an asterisk (*) next to the script file to indicate unsaved changes
4. Press CTRL+S (This is where it goes wrong by not saving)

**Comment by merumelu** [comment]
Ctrl+Alt+S is used to save scripts, Ctrl+S only saves the scene. It's the same in default view.

**Comment by merumelu** [comment]
Wait, turns out Ctrl+S does save the script in full script view. :smile:
It works for me thought. Using custom build from 827a9aa8294e7e2405f645579cc3e7044f3be079.

**Comment by Tybobobo** [comment]
Obs; I meant it does not save project

**Comment by Tybobobo** [comment]
Closing issue, since it is no longer relevant and works just fine.
