### ISSUE TITLE
Image PNG flags maintenance problem

### ISSUE THREAD

**Issue by RandomShaper** [godotengine/godot#6509]
You can set flags for individual images but those also available globally on the image loader (`filter`, `gen_mipmaps` and `repeat`) only get saved in the _.png.flags_ file if they differ,
[as per this code](https://github.com/godotengine/godot/blob/f1e1910ae435c255745773bf37a60d798f9412fb/drivers/png/resource_saver_png.cpp#L63-L71).

I wonder if the `ImageTexture` flags should be tri-state, that is: on, off or default, the latter to let the global image loader behavior happen.

I think the global flags shouldn't affect how per-image flags are stored because you may end up losing information.

By the way (and sorry if it's in the docs but I can't find it), for textures imported to .tex files, does this work the same? If not, how does local-global flags overridance work for them?

**Comment by reduz** [comment]
closing as this is obsoleted in 3.0
