### ISSUE TITLE
LabelSettings' `font_color` not taken into account anymore (4.0 alpha 15)

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#65096]
### Godot version

4.0 alpha 15 (used to work in alpha 14)

### System information

linux

### Issue description

Migrating from alpha 14, LabelSettings all work except for the `font_color` property.
Adding a custom font seem to solve the problem.

https://user-images.githubusercontent.com/71937306/187499681-177df2a1-7760-455a-b43a-e20b5d17d8e7.mp4

### Steps to reproduce

1. in a Label node create a new LabelSettings resource
2. tweak the font color

**Comment by bruvzg** [comment]
Can't reproduce. Is there custom font / font color set in the theme overrides or default project theme? Is it an old project? If so, try reimporting fonts.

**Comment by mieldepoche** [comment]
On a new project this only happens if editor setting `gui/theme/default_font_multichannel_signed_distance_field` is enabled.

**Comment by bruvzg** [comment]
> On a new project this only happens if editor setting gui/theme/default_font_multichannel_signed_distance_field is enabled.

OK, I can confirm this with MSDF, fix - https://github.com/godotengine/godot/pull/65098
