### ISSUE TITLE
EditorFileDialog has missing icons (4.0.alpha15 regression)

### ISSUE THREAD

**Issue by RedMser** [godotengine/godot#65090]
### Godot version

4.0.dev (889c522a)

### System information

Windows 10

### Issue description

Export template file browser dialog has error icons everywhere. Other dialogs of same kind (like "Open Scene") work fine.

![image](https://user-images.githubusercontent.com/5117197/187477876-b9be6103-8fd6-4946-ad0e-3e7e74273df9.png)

Maybe related to the EditorFileDialog access mode `ACCESS_FILESYSTEM` used here?

### Steps to reproduce

- Open Project -> Export dialog
- Create e.g. windows export target
- Open file browser for custom template

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot/issues/65037 which is the same issue, and should have been resolved about 10 hours ago.

**Comment by clayjohn** [comment]
I'm seeing this issue in multiple other places most prominently in the mesh inspector preview and the material inspector preview

**Comment by akien-mga** [comment]
CC @AaronRecord @YuriSizov

**Comment by MeshVoid** [comment]
![image](https://user-images.githubusercontent.com/35863328/187780856-f06c8423-b762-4d59-8d22-c6f003006f1a.png)
Experiencing the same with the icons in material editor
