### ISSUE TITLE
Node3D Linked scale does not work for multiple objects

### ISSUE THREAD

**Issue by tinmanjuggernaut** [godotengine/godot#65099]
### Godot version

Godot 4 Alpha 15

### System information

Windows 11/64, RTX 3070, Vulkan

### Issue description

Linked scaling works for one object, but not when two or more are selected. Neither entering nor sliding the value.

![image](https://user-images.githubusercontent.com/632766/187506784-9a09a4bd-80d6-4f44-b283-bd272a4cc3e5.png)

### Steps to reproduce

* Select two objects. 
* Adjust transform/scale/x. 
* Y and Z are not affected.

**Comment by tinmanjuggernaut** [comment]
@Calinou Can this get triaged, tagged and added to the roadmap please?

**Comment by Calinou** [comment]
I can confirm this on 4.0.alpha daec089c3.

**Comment by Rindbee** [comment]
A duplicate of #62283.
