### ISSUE TITLE
"in x" and "in ... x.keys()" behaving differently on dictionary, also debugger shows null even though it has data

### ISSUE THREAD

**Issue by jacopofar** [godotengine/godot#65091]
### Godot version

3.5.stable

### System information

Linux (Fedora 36, 64 bit)

### Issue description

My GDScript code produces different results when checking the presence of a key in a dictionary using `in` directly or on the `keys()` array.

Unfortunately, this happens only with a complex dictionary built dynamically after loading JSONs from a service, if I recreate a small dictionary to reproduce the bug it disappears. Also, the debugger shows the dictionary as `[null]` but it has data inside, seems the issue https://github.com/godotengine/godot/issues/36801 but I can reproduce it all the time.

This is the code:

```gdscript
print("tileset_textures: ", tilesets_textures)
if not gid in tilesets_textures[candidate_gid]["animations"]:
	print("cannot find gid: ", gid)
	print("visible animations:", tilesets_textures[candidate_gid]["animations"])
	print("check using in: ", gid in tilesets_textures[candidate_gid]["animations"])
	print("check using in keys(): ", gid in tilesets_textures[candidate_gid]["animations"].keys())

	for k in tilesets_textures[candidate_gid]["animations"].keys():
		print("type of ", k, " is ", typeof(k))
		print("equality check ", k == gid)
```

the output is:
```
tileset_textures: {1:{animations:{}, calculated_size:1536, image_height:3072, image_width:512, texture:[ImageTexture:1292], tile_height:32, tile_width:32}, 1537:{animations:{1539:[{duration:150, gid:2248}, {duration:150, gid:2264}, {duration:150, gid:2347}, {duration:150, gid:1549}]}, calculated_size:1024, image_height:2048, image_width:512, texture:[ImageTexture:1295], tile_height:32, tile_width:32}}
cannot find gid: 1539
visible animations:{1539:[{duration:150, gid:2248}, {duration:150, gid:2264}, {duration:150, gid:2347}, {duration:150, gid:1549}]}
check using in: False
check using in keys(): True
type of 1539 is 3
equality check True
```
I printed the types because I assumed it was a type error (the dictionary is built from a JSON), but it's an integer and as you can see the check gives different results when done using keys() and the dictionary itself, and the debugger doesn't show the content of the dictionary at all.

If I just replace the check with `in .... .keys()` I get errors later because the key is not found. It seems the key is visible when using `.keys()` but not when using `in` on the dictionary itself.

### Steps to reproduce

Unfortunately I could not pinpoint where the bug happens, when creating a small test dictionary it disappears, but can be reproduced adding the JSONs of the project

The procedure is this:

* clone the reference game, essentially a set of Tiled maps:

  `git clone git@github.com:jacopofar/reference_game.git`
* start a web server in the folder `python3 -m http.server`, will listen at port 8080
* start the scene `MapFromJSON` in the Godot project. It will download a few JSONs from the server and rebuilt the Tiled map using sprites. That's when the issue above happens, specifically when trying to reconstruct an animated tile

### Minimal reproduction project

[load-tiled-world.zip](https://github.com/godotengine/godot/files/9454487/load-tiled-world.zip)

**Comment by timothyqiu** [comment]
A potential cause is that your id is sometimes `float` and sometimes `int`. And numbers parsed from JSON are always `float`. Comparing equality of floating-point values are risky.

When adding elements into the animations dictionary, changing the key from `int(tile_extra_metadata["id"]) + firstgid` into `int(tile_extra_metadata["id"] + firstgid)` seems to fix the issue.

But yeah, `in dict` should be equivalent to `in dict.keys()` anyway.

**Comment by Zireael07** [comment]
> But yeah, making in dict equivalent to in dict.keys() is more natural probably.

Definitely.

**Comment by jacopofar** [comment]
Thanks @timothyqiu , indeed changing the line 33 into `var firstgid = int(tileset["firstgid"])` to cast the key to int did eliminate the issue. And thanks for the explanation, it would have been hard to figure out.

Strange behavior, usually the hash for values that are equal is the same, I guess the equality in GDScript is something similar to Javascript `==`.

Also I found out that `print` in Godot hides the decimals in float values, so `print(float(3.0))` and `print(int(3.0))` both show `3`, while float maybe should be something like `3.0` to mark the difference. I found it's an issue already discussed here https://github.com/godotengine/godot-proposals/issues/1693

The attached files can still be used to reproduce the issue with the debugger

**Comment by Calinou** [comment]
> I guess the equality in GDScript is something similar to Javascript ==.

GDScript is a strongly typed language, so no, it's not intended to work like JavaScript's `==`.

**Comment by jacopofar** [comment]
I cannot reproduce this bug anymore at least in the last 3 betas 12, 13 and 14.

**Comment by akien-mga** [comment]
Thanks, closing as fixed then.
