### ISSUE TITLE
RayCast3D constantly detects collision even when none is present

### ISSUE THREAD

**Issue by Ophiolith** [godotengine/godot#65102]
### Godot version

4.0 alpha 15

### System information

WIndows 10 build 19044

### Issue description

**Issue:**
I'm using a RayCast3D node to check for collisions above my character's 'head', in order to disable un-crouching and jumping if necessary. This RayCast3D does not clip my collision capsule, and the game environment above my character has no immediate colliding objects. I call the node in script using `@onready var headchecker = $Head/HeadChecker`, and get it to print an error whenever collision is detected using the following:
```
func _process(delta):
	if headchecker.is_colliding:
		push_warning("BONK")
```

**Result:**
This spams the console with 'BONK' warnings as fast as Godot can update. In my full project it engages the logic written to prevent the character from un-crouching and _never disengages it_. Simply put, the raycast is detecting collision where it objectively should not.

**Expected behaviour:**
Run the project, raycast only detects collision on geometry with collision shapes.

**Other notes:**
This behaviour has been present since alpha 10 if not further back

![image](https://user-images.githubusercontent.com/24281932/187513632-5971bd56-1515-4d65-a084-42ed1ca1899c.png)
As can be seen, the raycast is not intersecting with the character's collision shape, and has no obstructive geometry above it.

![image](https://user-images.githubusercontent.com/24281932/187513889-e08ea090-a8d7-4c89-a0c2-1d2c26d708a4.png)
Copy of the raycast's properties. It is worth noting that this behaviour remains _even if the raycast is disabled_

### Steps to reproduce

- Attach RayCast3D to CharacterBody3D
- Call Raycast3D in script with `@onready var`
- Trigger warning or other behaviour using `.is_colliding`

### Minimal reproduction project

[RayCastCollide_MinRepro.zip](https://github.com/godotengine/godot/files/9455573/RayCastCollide_MinRepro.zip)

**Comment by rburing** [comment]
The `RayCast3D` node has a *method* (not a property) named `is_colliding`. To determine if the ray is colliding with something, you must *call* the method and use the return value. That is, write `if headchecker.is_colliding()` with the parentheses (calling the method) instead of without the parentheses (not calling the method, just referring to it).
