### ISSUE TITLE
Integrated docs (Editor Help) display is broken in 4.0 alpha 15

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#65114]
### Godot version

4.0 alpha 15

### System information

linux

### Issue description

| alpha 14                                                                                                        | alpha 15                                                                                                        |
|-----------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------|
| ![image](https://user-images.githubusercontent.com/71937306/187537453-f6e91b1f-13ce-4f0b-b2e7-f0542b7ae447.png) | ![image](https://user-images.githubusercontent.com/71937306/187537339-ebc5b30d-c6e4-4386-9352-42a7d6d973b9.png) |

This happens regardless of the project.
While testing back and forth with a14 and a15 I got *once* a15 to display docs correctly (if I remember correctly) but was not able to reproduce since.

### Steps to reproduce

Open the docs in 4.0.alpha15

**Comment by bruvzg** [comment]
Seems like something wrong with the theme propagation, it is displayed correctly if you change any of the theme related editor settings, to trigger update.

**Comment by Rindbee** [comment]
If it's only happening for the first time, it's probably a regression from #59226.

**Comment by bruvzg** [comment]
> If it's only happening for the first time, it's probably a regression from https://github.com/godotengine/godot/pull/59226.

Most likely related to  #65037, #65090, and other issues related to ENTER_TREE, THEME_CHANGED notification handling changes.

**Comment by akien-mga** [comment]
CC @AaronRecord @YuriSizov

**Comment by akien-mga** [comment]
As mentioned in #65149 it seems to use the default project font.
