### ISSUE TITLE
Adding custom OS Theme to your game (windowed only)

### ISSUE THREAD

**Issue by ivanskodje** [godotengine/godot#6511]
If you are creating a game, or perhaps more likely game tool (perhaps a "Battle.net" type of app for your game); it would be highly relevant to add the customization option that will give you the ability to  change the window theme.

Currently, you can remove the window altogether; and kinda fake "your own window theme", but it is not possible (to my knowledge) to add transparency in the background in order to design your own. You would also have to find a way to move the window yourself. (I have not tried this yet, so I cant say for sure if this is even possible right now)

I would love to see window theme customization implemented; or at least supported (so it would be up to us to do the hard work). Some day, perhaps. :)

This is how the default Windows 8 Theme make your window (which is windowed) look like:
![](https://i.imgur.com/tvx4PCy.png)

Here are a few good examples of custom window themes that blends with the game;
**Battle.net**
![](http://i.imgur.com/lMOrw78.jpg)

**League of Legends**
![](http://i.imgur.com/RPraQfr.jpg)

**Comment by SuperUserNameMan** [comment]
I don't know if it changed with recent Windows versions, but in a not so far past, the "custom window border theme" of an application was drawn by the application itself.

This kind of application used a borderless window inside of which they drawn their own borders, tittle bar and buttons, and handled the resizing by themselve too.

Into the project settings, you could enable the Display / borderless_window option.

**Comment by Tybobobo** [comment]
To my knowledge there is no way to add transparency in the background (so you see your computer desktop); so you are limited to a perfectly square window, no?

**Comment by SuperUserNameMan** [comment]
yes, rectangle opaque window only.

from the not so far past i was talking about, transparent window background would require that Godot setup opengl to render into a "device independent bitmap" (which is a Win32 internal picture format) and to do some over complicated stuff to draw this bitmap into the transparent window client. It would be slow.

**Comment by Noshyaar** [comment]
Still reproducible/relevant in 3.1 master 9ad1800 : AFAIK there's still no way to make transparent window

**Comment by Calinou** [comment]
Per-pixel transparency was implemented in https://github.com/godotengine/godot/pull/14622. It's also possible to implement window controls and dragging yourself (see [this tutorial](https://www.youtube.com/watch?v=alKdkRJy-iY)), so I'll close this issue.

**Comment by bruvzg** [comment]
> It's also possible to implement window controls and dragging yourself (see this tutorial)

This implementation is completely wrong and will not work consistently, mouse and windows gonna run out of sync quickly on any OS.

**Comment by bruvzg** [comment]
There's new PR for window decoration logic - #23972 (supersedes #16512).
