### ISSUE TITLE
Editor exits when opening a project with theme/default_font_antialiasing but without default font

### ISSUE THREAD

**Issue by jbuechner** [godotengine/godot#65126]
### Godot version

4.0.alpha15.official

### System information

win10

### Issue description

Opening a project with the given setting but without a default font, causes the editor to close before opening the project.

### Steps to reproduce

1. Create a new project
2. Project -> Project Settings
3. Show Advanced
4. Set default font antialiasing to LCD sub-pixel
5. Save & Restart

alternatively open the `project.godot` file and add the line

```
[gui]
theme/default_font_antialiasing=2
```

### Minimal reproduction project

[repro.zip](https://github.com/godotengine/godot/files/9458528/repro.zip)

**Comment by Calinou** [comment]
cc @bruvzg
