### ISSUE TITLE
EditorFileDialog freezes the editor

### ISSUE THREAD

**Issue by jtnicholl** [godotengine/godot#65122]
### Godot version

v4.0.alpha.custom_build [8fa9d1ae4]

### System information

Linux (Fedora 36)

### Issue description

When opening a file dialog in certain projects the editor freezes while maxing out a CPU thread. It only happens if recent directories contains two of the same directory, one with a slash at the end and one without. Which is something that happens sometimes, I don't know if there's already an issue open for that or how to reproduce it.
From doing a `git bisect` this seems to be a regression caused by #63552. That PR involves some `for` loops so I think it's getting stuck in an infinite loop, but I couldn't figure out where.

### Steps to reproduce

1. Open the MRP (contains a `.godot/editor/recent_dirs` file that will cause the bug)
2. Right click on FileSystem -> New Resource and select any resource type (or open an EditorFileDialog by some other means)
3. Blank window pops up, editor freezes and maxes out a CPU core

### Minimal reproduction project

[EditorStuck.zip](https://github.com/godotengine/godot/files/9457734/EditorStuck.zip)

**Comment by akien-mga** [comment]
CC @RedMser

**Comment by RedMser** [comment]
Can confirm. Was missing a change in `EditorNode::disambiguate_filenames`. Uploading a fix for it.

**Comment by compmstr** [comment]
@RedMser I made a mistake with my original comment: there aren't relative paths in the `recent_dirs` file, it's a full path with the same prefix.
I was trying to not put my name in a comment, but my Github profile has my name aways :facepalm: 
So my `recent_dirs` file contains:
```
/home/corey/programming/godot/
/home/corey/programming/godot
```
I'll try checking out your branch to see if that fixes it though.

**Comment by RedMser** [comment]
> there aren't relative paths in the `recent_dirs` file, it's a full path with the same prefix.

Ah I see. Well it found us another bug then, which is good to get fixed :D

But in that case, I don't think this will fix it either. I'm on Windows, where absolute paths start with a drive letter, so this might only happen on Linux. I'll try to reproduce...

**Comment by compmstr** [comment]
Ah, I also just found out that it's any duplicate paths, with or without a trailing slash.
So if I change to:
```
/home/corey/programming/godot/
/home/corey/programming/godot/
```
I see the same issue
