### ISSUE TITLE
Vulkan: VRAM-compressed textures have incorrect hue on Android (red and blue swapped)

### ISSUE THREAD

**Issue by Duskitten** [godotengine/godot#65127]
### Godot version

V4.0.alpha15.official [432b25d36]

### System information

Android, Vulkan Renderer, [Galaxy S9+](https://www.gsmarena.com/samsung_galaxy_s9+-8967.php), Android V10

### Issue description

Basically, when you put in a colored Emission texture, there appears to be an offset, I tested with various colors it would seem
Green = Green?
Blue = Orange
Purple = Red
Teal = Yellow

Which leads me to believe the default materials may have an issue
The Issue only appears on android (I cant test on IOS)
Everything works fine in the editor itself though, so I'm not 100% sure what's going on with it.

### Steps to reproduce

Use A15 release build
Turn off all Lighting
Create a Colored PNG Emission map for the materials
Add to BaseMaterial3D, and give enough Emission for it to show
Add a world Environment with enough bloom to see emissions
Compile and Run on android

### Minimal reproduction project

Attached below is a Zip with A simple setup scene, It contains a colored emissive map (purple) that shows up as Red on the android export

[Android_MaterialBug.zip](https://github.com/godotengine/godot/files/9458619/Android_MaterialBug.zip)

**Comment by Calinou** [comment]
Did you test with albedo textures and general lighting? I remember seeing an issue with inverted hues on old Android devices.

**Comment by Duskitten** [comment]
> Did you test with albedo textures and general lighting? I remember seeing an issue with inverted hues on old Android devices.

In my regular Project, yes, it works fine for albedo, and normal lighting, it's explicitly the emission map that appears to be messing up

**Comment by Duskitten** [comment]
After a bit more work, I noticed godot seems rather random with this issue, sometimes the textures go inverted, other times they dont, ive compared images that work, and ones that dont, and there seems to be no real difference in terms of format, or anything, so this may be a bigger issue than I thought

**Comment by Duskitten** [comment]
Putting this out as a temporary workaround for this issue:

- Import Image
- Add Image to spot you'd like
- Make Image in spot unique
- (optionally) save unique image as TSCN

This seems to prevent the issue from happening entirely as it converts to a non-imported format

**Comment by Duskitten** [comment]
Another Workaround, When importing the textures, Set them to "Lossless" or "Vram Uncompressed" in the import panel, this also appears to cause textures to work properly in 3D on mobile

The other options cause the following:
Lossy : Faded Appearance
Vram Compressed: Inverting issue
Basis universal:Simply causes the image to break and not work as emissive, just adds it to the color itself

**Comment by Duskitten** [comment]
After some testing, I learned this applies to all textures on said material

**Comment by coati-time** [comment]
Maybe I'm having the same issue as well.
In my case, I dealt with it by swapping the red and blue in the shader.

Here is the code for swapping colors by shader that I tried.
https://github.com/coati-time/Godot4ColorTest/blob/main/switchRandB.tres

I guess depending on the version of Android, Godot needs an implementation to convert OpenGL RGBA byte arrays to ARGB byte arrays.
I'm newbie to Godot so I don't know, but is there already a build-settings to swap R and B for Android?
https://stackoverflow.com/questions/56389357/convert-opengl-rgba-byte-array-to-android-argb-byte-array

Thanks for your effort.

**Comment by akien-mga** [comment]
Likely a problem in using the etcpak importer, CC @godotengine/import.

**Comment by Calinou** [comment]
> Likely a problem in using the etcpak importer, CC @godotengine/import.

The problem doesn't occur on desktop, and only seems to be reproducible in Vulkan so far. I'm not sure if ETC2 compressed texture support is implemented in OpenGL in Godot 4.0.beta.

**Comment by fire** [comment]
I don't have access to an android device, but I do have an iphone.

**Comment by BastiaanOlij** [comment]
I can confirm that this is happening with some consistency, here is a capture (with renderdoc) on my pixel 6:
![image](https://user-images.githubusercontent.com/1945449/204995996-be77dea0-c8b4-4551-adff-8b772692e84b.png)

Here is the same project on Windows:
![image](https://user-images.githubusercontent.com/1945449/204996563-27863877-56bb-48fa-8667-e1c973e74854.png)

I can also confirm with renderdoc the textures were loaded with colors swapped.

It seems to be related to ETC though I do not know why some materials are using the correct color and some aren't.

I've had the same happen on a Meta Quest 2 and can confirm that turning off compression on images has them loading correctly.

**Comment by BastiaanOlij** [comment]
Ok, further investigating with renderdoc, all textures with the format `ETC2_RGB8_UNORM` are wrongly colored:
![image](https://user-images.githubusercontent.com/1945449/205044185-3e518f56-84a6-4aa3-93a1-285141cc54b8.png)

Correctly colored textures have the format `R8G8B8A8_UNORM`
![image](https://user-images.githubusercontent.com/1945449/205044294-ec5d6772-a2c7-4742-b9fa-38ecd58d4e94.png)

I wonder if this is going wrong for RGB images (images without an alpha channel), whether it just shifts everything
