### ISSUE TITLE
Excessive padding is present in all tooltips

### ISSUE THREAD

**Issue by Mickeon** [godotengine/godot#65136]
### Godot version

v4.0.alpha.custom_build [c40855f81]

### System information

Windows 10

### Issue description

Every tooltip in the editor, even custom ones, have way too much padding to the right and bottom. I swear it wasn't this much before:

![image](https://user-images.githubusercontent.com/66727710/187645263-efb94174-f7cf-4418-8ec4-9d2c6b697d67.png)
![image](https://user-images.githubusercontent.com/66727710/187646071-9879490c-8fe5-414c-841d-c238531f3dc8.png)
![image](https://user-images.githubusercontent.com/66727710/187646411-2d7e3107-2a87-407d-90da-007d6404f4d1.png)

The padding *seems* proportional to how long or tall the inside text is.

This started happening around the same time as https://github.com/godotengine/godot/issues/64851. There also was a PR that added "If the value is the same, return" to most setters in Control classes, that may have caused this.

### Steps to reproduce

Hover on anything capable of displaying a tooltip.

### Minimal reproduction project

No need.

**Comment by L4Vo5** [comment]
This seems to be fixed in alpha17 and beta1

**Comment by Mickeon** [comment]
That is correct, although I'm not sure what PR to thank.
