### ISSUE TITLE
ItemList tooltip does not update when Itemlist scrolls

### ISSUE THREAD

**Issue by Brickcaster** [godotengine/godot#6514]
**Operating system or device - Godot version:**
Godot Master ( 16/9/2016 )

**Issue description** (what happened, and what was expected):
When mousing over a ItemList element, a tooltip will display.  If the arrow keys are used to change the selection until the ItemList scrolls, the tooltip remains static while the item under the mouse cursor stays the same.  Expected behavior is for the tooltip to change either on any key input or when the ItemList scrolls.

**Steps to reproduce:**
Create an ItemList.
Population ItemList with more elements than can be displayed.
Click an item to give the ItemList focus and select that item.
From here, do not touch mouse.
Observe the tooltip.
Press up/down arrows until the ItemList scrolls.
Tooltip remains static even though mousedover element does not match tooltip. **Unexpected Behavior**

**Link to minimal example project** (optional but very welcome):
https://www.dropbox.com/s/mz1gb2k0oyq0cxf/Godot%202.1%20ItemListScrolling%20bug%20demo.zip?dl=0

**Comment by Brickcaster** [comment]
On looking through item_list.cpp, get_tooltip is not ever called.  Nor is it called in control.cpp.  This appears to be a wider issue overall with anything that uses tooltips.

**Comment by Brickcaster** [comment]
Researching this issue further, it seems related to viewport.cpp . If a control mode moves for whatever reason, it never gets the mouseexit signal which would lead to the tooltip expiring.

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Brickcaster** [comment]
I tested this in Godot 3.0.2.  Scrolling via the arrow keys still causes this bug to occur.

![image](https://user-images.githubusercontent.com/13324089/39397990-88ff0784-4ad5-11e8-9768-05be5f9ab149.png)

Scrolling via the mouse wheel causes the tool tip to disappear, but the new one does not appear as expected.

![image](https://user-images.githubusercontent.com/13324089/39397971-7141505c-4ad5-11e8-84ba-958e14a771fb.png)

**Comment by reduz** [comment]
I don't understand this issue and the demo project does not work

**Comment by reduz** [comment]
Closing as I am not sure this is even a bug. Please feel free to reopen with a demo project attached if something is found
