### ISSUE TITLE
set_custom_mouse_cursor no longer working with ImageTexture.create_from_image()

### ISSUE THREAD

**Issue by Kyle-Mendes** [godotengine/godot#65154]
### Godot version

4.0 Alpha 15

### System information

Mac OS

### Issue description

In earlier alphas,  I was using `Input.set_custom_mouse_cursor` with an `ImageTexture` to generate custom mouse cursors on the fly.  This is no longer working, however.

```gdscript
current_seed = selected_seed

var texture = load(mouse)
var image = texture.get_image()
image.crop(64, 64)

var seed_image = selected_seed.icon.get_image()
seed_image.resize(32, 32, 0)

image.blend_rect(seed_image, Rect2(0, 0, 32, 32), Vector2(0, 0))
var mouse_image = ImageTexture.new()
mouse_image.create_from_image(image)

Input.set_custom_mouse_cursor(image) # <--- error
```

```
E 0:00:10:0189   _on_seed_inventory_item_gui_input: Condition "!texture.is_valid()" is true.
  <C++ Source>   platform/macos/display_server_macos.mm:2979 @ cursor_set_custom_image()
  <Stack Trace>  InventoryManager.gd:79 @ handle_select_seed()
                 SeedInventoryItem.gd:34 @ _on_seed_inventory_item_gui_input()
```

### Steps to reproduce

Really, it seems like setting a custom mouse cursor with anything that wasn't directly loaded as a `Texture` isn't working in the latest alpha. I've tried with Images, ImageTextures, and neither is working.  Sample code is included above.

**Comment by Zireael07** [comment]
create_from_image() became a static function in... a 12 I think, and it keeps catching people unawares

**Comment by Kyle-Mendes** [comment]
> create_from_image() became a static function in... a 12 I think, and it keeps catching people unawares

Ah! That did it thank you 😅. I think not getting an error caught me off guard.
