### ISSUE TITLE
Editor spawns hundreds of processes on startup to call xdg-user-dir

### ISSUE THREAD

**Issue by permelin** [godotengine/godot#65157]
### Godot version

v4.0.alpha.custom_build [f6714581c]

### System information

Linux

### Issue description

Not a bug but a quality-of-life issue and I really don't know if this is worth looking into. I won't be the least bit mad if you reject this issue.

When I start the editor on my Linux machine it spawns 807 processes (in sequence, not in parallel) to run `xdg-user-dir DESKTOP`. If I start the editor with a `--path` it "only" does it 606 times.

I changed `OS_LinuxBSD::get_system_dir()` to instead return early with a hardcoded path and that took startup time from 8.8 to 7.5 seconds (as measured with the new `--startup-benchmark`) on a small scene.

### Steps to reproduce

To see how many times this happens during startup, here are a couple of different, ugly ways I can think of:
Add a `print_line()` to `OS_LinuxBSD::get_system_dir()`
or
Create a shell script called `xdg-user-dir` which does `echo $@ >> ~/xdg.log` and put it somewhere in your PATH before where the proper `xdg-user-dir` lives. Then `wc -l ~/xdg.log`.

**Comment by permelin** [comment]
If you follow by poor advice to create a shadow `xdg-user-dir` script, please remember to remove it once you're done testing, or other apps will behave weirdly. Don't ask me how I know.

**Comment by Calinou** [comment]
I agree the value should be cached, as it's not going to change at run-time.
