### ISSUE TITLE
GridMap - Crash when Octant size is set to 0

### ISSUE THREAD

**Issue by jmf** [godotengine/godot#6515]
**Operating system or device - Godot version:**
Archlinux, custom-built godot version a75f5f039e31e20d985937f63cb2c8b90734160c

**Issue description** (what happened, and what was expected):
Two different, seemingly related bugs occur:
1.
When the parameter "Octant Size" of a gridmap is set to 0, the editor crashes. This only happens when there are already tiles set in the GridMap.
2.
When there are no tiles set and "Octant Size" is set to 0, it is set to 1 by godot, when I add a tile after that the program also crashes.

**Steps to reproduce:**
Download and open the example project linked below.
1. Set a tile in the gridmap, then set "Octant Size" to 0. It should result in a crash
2. Alternatively, set "Octant Size" to 0 before setting a tile. Godot sets it to "1". Then set a tile. This should also trigger a crash.

**Link to minimal example project** (optional but very welcome):
A minimal example:
https://my.mixtape.moe/vvntlo.zip

**Comment by vitvakatu** [comment]
Actually, I cannot reproduce this issue. 
Linix Mint 17.3 x64, latest dev build at that time ([c05ff57](https://github.com/godotengine/godot/commit/c05ff0577fd9cc39a6968e65743f7d7da711bfe2))
Octant size is locked in range from 1 to some_number. In case of manual assign to zero, it goes to 1 automatically.

**Comment by jmf** [comment]
@vitvakatu Have you tried it with my project? The crash only occurs when at least one tile is set in the gridmap. If no tile is set, the lock is applied.

**Comment by vitvakatu** [comment]
@jmf What have I done: I opened your project, open new_scene, then chose TileMap. I clicked on some tile in TileMap, than tried to change Octant Size for this tile to 0. You know the rest of the story. If I didn't do it wrong way, it seems to be really strange.

**Comment by jmf** [comment]
@vitvakatu With "set in the gridmap", I meant "placed on the gridmap within the scene".
Only selecting the tile isn't enough, it has to be placed in the scene to make this bug happen.
Sorry if I wasn't quite clear.

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by jmf** [comment]
This bug doesn't occur in the latest version of godot any more.
