### ISSUE TITLE
Godot flags c# script names with dashes as valid

### ISSUE THREAD

**Issue by ozoromo** [godotengine/godot#65166]
### Godot version

3.3

### System information

Linux (irellevant)

### Issue description

C# will not compile if the class name has a dash in it, godot however marks names with dashes in them as valid and lets users create scripts with "faulty names"

### Steps to reproduce

Create a c# script with a dash (`-`)  in its name

**Comment by Calinou** [comment]
> 3.3

[Godot 3.3.x is not supported for bug fixes anymore](https://docs.godotengine.org/en/stable/about/release_policy.html#release-support-timeline), so please upgrade to [3.5](https://godotengine.org/article/godot-3-5-cant-stop-wont-stop) and check if the issue still occurs there.
