### ISSUE TITLE
PlaceHolderTexture2D generates bad UV

### ISSUE THREAD

**Issue by alazifk** [godotengine/godot#65165]
### Godot version

4.0 Alpha 15

### System information

Win 10, Vulkan Mobile

### Issue description

`PlaceHolderTexture2D` appears to generate an UV that is 1/4th of the size it should have. This becomes an issue when you use it together with `TextureArray2D`.

![Capture](https://user-images.githubusercontent.com/93336644/187793296-a727a2e5-b4bc-4c98-9b4f-03b2c9071ff0.JPG)
(above: texture array, placeholder UV, below: regular sprite and UV)

The UV looks correct in the Inspector preview but not rendered. I assume fixing it will break its inspector preview.

### Steps to reproduce

Make a `Sprite`, set its texture to `PlaceHolderTexture2D`, set its size to something sane and check its UV. Reproduction project provided.

### Minimal reproduction project

[TextureArrayTestAlpha15.zip](https://github.com/godotengine/godot/files/9465440/TextureArrayTestAlpha15.zip)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/65159.

**Comment by alazifk** [comment]
You may disregard https://github.com/godotengine/godot/issues/65159, that was just me misinterpreting the issue. The bug is purely related to `PlaceHolderTexture2D`. I've only included the texture array stuff in the minimal reproduction project because once the bug is fixed it should work correctly as well.

**Comment by alazifk** [comment]
Placeholder textures that are not power of 2 look like cut off versions of the next power of 2.
A better and updated minimal reproduction project: [TextureArrayUV.zip](https://github.com/godotengine/godot/files/9540217/TextureArrayUV.zip)

**Comment by GrauBlitz** [comment]
Maybe unrelated, but i have a problem with Noise2DTextures in a Canvas Shader. All UVs > 1.0 mess up the texture if i try the same with a spatial shader everything works as expected. Setup is a MeshInstance2D with the shader set as material at the CanvasItem property.

**Comment by Calinou** [comment]
You need to enable **Repeat** on the CanvasTexture or the node itself.

**Comment by GrauBlitz** [comment]
You mean CanvasItem->Texture->Repeat = Enabled? I already set this before, the issue persists.
![shader2](https://user-images.githubusercontent.com/69392170/204026928-b00e5bfd-44ad-41f1-a6f4-079d6839021d.PNG)

**Comment by clayjohn** [comment]
> You mean CanvasItem->Texture->Repeat = Enabled? I already set this before, the issue persists. ![shader2](https://user-images.githubusercontent.com/69392170/204026928-b00e5bfd-44ad-41f1-a6f4-079d6839021d.PNG) The shader itself is in short just something like this:
> 
> `COLOR.rgb = texture(n0_fog, 0.5f + UV);`

You need to specify texture repeat in the shader itself:
```
uniform sampler2D n0_fog : repeat_disable, filter_nearest;
```
More info in the docs: https://docs.godotengine.org/en/latest/tutorials/shaders/shader_reference/shading_language.html#uniforms

**Comment by clayjohn** [comment]
To follow up on the OP, this is a documentation issue. The PlaceHolderTexture is meant to take the place of a texture (for headless platforms for example), it is not meant to be used as an actual texture. In the hardware a PlaceHolderTexture always has a size of 4x4 and may not carry any of the properties that you set on the CPU-side. 

See the docs: https://docs.godotengine.org/en/latest/classes/class_placeholdertexture2d.html
