### ISSUE TITLE
Isometric Tilemap Chunk Render Order

### ISSUE THREAD

**Issue by FluffyLuffie** [godotengine/godot#65177]
### Godot version

4.0 1c037c8

### System information

Windows10, AMD Radeon RX 5700 XT, Vulkan

### Issue description

In isometric tilemaps, the render order of the tiles are bugged.
The number of "incorrect" tiles in a row is in the following formula:

If even cell_quadrant_size: cell_quadrant_size / 2 - 1
If odd cell_quadrant_size: cell_quadrant_size  - 1
Example: if 16 then 16 / 2 - 1 = 7, if 7 then 7 - 1 = 6.

![Illustration](https://user-images.githubusercontent.com/76981608/187839502-57acca06-1d41-45ab-b40c-3ee6004fdd70.png)

### Steps to reproduce

Change the cell_quadrant_size of the tilemap.

### Minimal reproduction project

[IsoTilemap.zip](https://github.com/godotengine/godot/files/9467123/IsoTilemap.zip)

**Comment by FluffyLuffie** [comment]
The pattern also repeats to the side every cell_quadrant_size tiles.

**Comment by groud** [comment]
This is the expected behavior, as a quadrant are optimized by building a single CanvasItem. You need to enable Y-sort on the TileMap node and the TileMap layer and it should be solved.

**Comment by clapik** [comment]
@FluffyLuffie @groud probably worth noting this on the docs somewhere. Also, this _expected_ behavior is not user-friendly, I thought it was a bug and couldn't figure out how to resolve for a while.
