### ISSUE TITLE
Android export custom build and release mode error

### ISSUE THREAD

**Issue by DexterFstone** [godotengine/godot#65176]
### Godot version

3.5

### System information

Windows 7

### Issue description

Hi, when trying to export on android with custom build and release mode I get an error

the error when happening I'm using release mode and custom build

Export no custom build and release mode = OK
export custom build and debug mode = OK

FAILURE: Build failed with an exception.

    What went wrong:
    Execution failed for task ':lintVitalAnalyzeRelease'.
    > Could not resolve all files for configuration ':lintClassPath'.
    > Could not find lint-gradle-30.0.3.jar (com.android.tools.lint:lint-gradle:30.0.3).
    Searched in the following locations:
    https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle/30.0.3/lint-gradle-30.0.3.jar
    > Could not find lint-30.0.3.jar (com.android.tools.lint:lint:30.0.3).
    Searched in the following locations:
    https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint/30.0.3/lint-30.0.3.jar
    > Could not find lint-checks-30.0.3.jar (com.android.tools.lint:lint-checks:30.0.3).
    Searched in the following locations:
    https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-checks/30.0.3/lint-checks-30.0.3.jar
    > Could not find lint-api-30.0.3.jar (com.android.tools.lint:lint-api:30.0.3).
    Searched in the following locations:
    https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-api/30.0.3/lint-api-30.0.3.jar
    > Could not find intellij-core-30.0.3.jar (com.android.tools.external.com-intellij:intellij-core:30.0.3).
    Searched in the following locations:
    https://dl.google.com/dl/android/maven2/com/android/tools/external/com-intellij/intellij-core/30.0.3/intellij-core-30.0.3.jar
    > Could not find kotlin-compiler-30.0.3.jar (com.android.tools.external.com-intellij:kotlin-compiler:30.0.3).
    Searched in the following locations:
    https://dl.google.com/dl/android/maven2/com/android/tools/external/com-intellij/kotlin-compiler/30.0.3/kotlin-compiler-30.0.3.jar
    > Could not find uast-30.0.3.jar (com.android.tools.external.org-jetbrains:uast:30.0.3).
    Searched in the following locations:
    https://dl.google.com/dl/android/maven2/com/android/tools/external/org-jetbrains/uast/30.0.3/uast-30.0.3.jar
    > Could not find aapt2-proto-4.1.0-alpha01-6193524.jar (com.android.tools.build:aapt2-proto:4.1.0-alpha01-6193524).
    Searched in the following locations:
    https://dl.google.com/dl/android/maven2/com/android/tools/build/aapt2-proto/4.1.0-alpha01-6193524/aapt2-proto-4.1.0-alpha01-6193524.jar

### Steps to reproduce

.

**Comment by Calinou** [comment]
The download link works for me. Are you behind a proxy that could potentially block it?

**Comment by DexterFstone** [comment]
I use vpn and links work for but in godot I get error

**Comment by akien-mga** [comment]
You might need to configure your proxy in the editor settings:
![image](https://user-images.githubusercontent.com/4701338/187983007-80e4ed07-cce5-465f-b49b-f12ffc2dcba1.png)

CC @timothyqiu

**Comment by DexterFstone** [comment]
no, it's not work

> You might need to configure your proxy in the editor settings: ![image](https://user-images.githubusercontent.com/4701338/187983007-80e4ed07-cce5-465f-b49b-f12ffc2dcba1.png)
> 
> CC @timothyqiu

**Comment by timothyqiu** [comment]
> You might need to configure your proxy in the editor settings

This proxy only applies to editor features using `HTTPClient`/`HTTPRequest` e.g. export template downloading and the AssetLib.

Gradle needs its [own proxy settings](https://docs.gradle.org/3.3/userguide/build_environment.html#sec:accessing_the_web_via_a_proxy).

**Comment by DexterFstone** [comment]
> > You might need to configure your proxy in the editor settings
> 
> This proxy only applies to editor features using `HTTPClient`/`HTTPRequest` e.g. export template downloading and the AssetLib.
> 
> Gradle needs its [own proxy settings](https://docs.gradle.org/3.3/userguide/build_environment.html#sec:accessing_the_web_via_a_proxy).

tnx, it's work

**Comment by Calinou** [comment]
Reopening, as this needs to be documented in the Exporting for Android page (along with Custom builds for Android).

**Comment by AThousandShips** [comment]
Was this documented? If so could you please link to where so its easier to tell
