### ISSUE TITLE
Label & RichTextLabel.visible_ratio does not work in Godot 4.0 alpha 15

### ISSUE THREAD

**Issue by meowyih** [godotengine/godot#65195]
### Godot version

v4.0.alpha15.official [432b25d36]

### System information

Window11 64bits

### Issue description

The Label & RichTextLabel property, "visible_ratio", does not work in both editor and GDScript. I cannot change the value in editor. If I change it in GDScript, nothing happens. 
This property was called "percent_visible" before alpha 15.

### Steps to reproduce

1. Create a new project.
2. Create a 2D scene
3. Add Label under Node2d
4. Type some text in Label and try to change the "Visible Ratio" property. The value 1.0 is non-changeable.

![螢幕擷取畫面 (276)](https://user-images.githubusercontent.com/32887778/187925294-d659e902-d8ed-4658-9a61-b221a67352e6.png)

### Minimal reproduction project

[LabelVisible.zip](https://github.com/godotengine/godot/files/9470178/LabelVisible.zip)

The exact same project works fine in alpha 14, which the property name was "percent_visible" ("Percent Visible" in editor).

**Comment by Calinou** [comment]
The property was renamed by https://github.com/godotengine/godot/pull/64665. cc @Mickeon

**Comment by Mickeon** [comment]
May have been caused by https://github.com/godotengine/godot/pull/64670 and the aforementioned PR after a "bad" merge, I'm going to check.
