### ISSUE TITLE
AnimationBlendTree performance issue

### ISSUE THREAD

**Issue by TokageItLab** [godotengine/godot#65199]
_Originally posted by @JoanPotatoes2021 in https://github.com/godotengine/godot/issues/53752#issuecomment-1233597471_

I am facing breaking perfomance loss if I use physics in process_callback of animation tree, which I wanted because I wanted to have a constant root_motion velocity despite the fps, which points to this issue.

However I didn't wanted to spam another issue because it might be related to alpha perfomance? I didn't saw anything about optmizing animation trees or perfomance issues related to animations though, here's a gif showing my problem,

![AnimationTree_SeverePerfomanceLoss_onProcessCallback_Physics](https://user-images.githubusercontent.com/88800565/187806697-7843c06a-5b14-4948-b33a-37a8376e7ee2.gif) _-note that gif was rendered to 20 fps_

I might not be using animation trees correctly, but this seems how it was supposed to work? Here's how is structured, it was designed for a third person shooter. I saw this type of animation tree being done for other projects, is it that costly to blend multiple animations? I am a little worried to be honest,

![2](https://user-images.githubusercontent.com/88800565/187807030-88733437-96ce-49b9-ab1d-8dfd90e5f65a.jpg)

Why I am getting so much perfomance loss setting the process callback to physics? I would expect just like Calinou pointed out, to limit the update rate of the animations,

That gif was on an complete empty project, my skeleton have 107 bones, the tree is very complex and I have a lot of animations but by no means should it drop so low, something's going on. On my full project it drops from 240 fps to ~5-20 fps with just 5 characters with meshs and this very same animation tree and skeleton.

**REF**
v4.0.alpha15.official [432b25d36]
Windows 10, Nvidia Geforce GTX 1050 TI, Vulkan

**Comment by JoanPotatoes2021** [comment]
**Fire**, I am uploading a test project, all the animations and the test model are done by me, so they are royalty free for Godot, plus if anyone buys my game in the future the game assets are easily exctractable so I am not worried about them, and honestly mixamo has better animations than me 🌜 ,

Running this test project I get to ~5 fps, the characters were duplicated using `Ctrl+D` in the editor and are saved as a separate scene `"Sample_Character"`, this is the same way I work on my WIP third person project I mentioned previously, I am running a script to randomize oneshots of the animation tree to give more chaos to the tests, don't know if this helps the optmizations tests or not,

[AnimTree_PerfomanceTest.zip](https://github.com/godotengine/godot/files/9470222/AnimTree_PerfomanceTest.zip)

![AnimationTree_perfTest](https://user-images.githubusercontent.com/88800565/187927698-c949a19a-f6d5-4dc0-aa25-c9919afd3d31.jpg)

In my game I plan to have 20 to 30 characters at the same time, mind you not all of them would be human, which might be the most expensible characters in the game, more if possible would be also great, so having this perfomance with only 5-6, I will need to explore alternatives to improve it.

My current workflow for this project is to have the rig separated from the characters, this is done exporting a animation rig from blender, with all it's animations in the NLA, and a linked duplicated rig with no animations in the NLA used to hold the skinning information for any meshes, this way in Godot I import the .gltf mesh and change the skeleton to the one that has all animations. This allows me to group assets into separate .gltf files, which helps managing assets from blender,

**TokageItLab**, the `animation_tree` node is duplicated, but the `tree_root` is saved as a resource .tres, I tried to create a animation_tree node in a autoload and pass to the actors but couldn't resolve assigning the animation player in the actors, it failed silently. Now I am interested in what you mentioned with transfer only poses,

One of the optmizations I plan to work on is to reduce the amount of oneshots I have using transition nodes to group them, this in theory should reduce the amount of inactive one shots mixed in the tree, and maybe I can work something out with the blend nodes as well, 

![animation_tree_grouping](https://user-images.githubusercontent.com/88800565/187930362-21932e0d-d168-4cdd-9b83-788b8175baf5.jpg)


Another idea I tried was to edit the tree_root nodes itself, reusing the same structure, swapping animations using gdscript, but this requires each tree_root to be unique or changing one tree_root node all character using that tree_root would also change that animation node, so in theory this can also work with a specialized small tree unique for the player, if the player needs way more animations than npcs,

**Comment by TokageItLab** [comment]
For animation, we already have the following three plans for optimization:

- Multi-threaded blend animation
- Reduced computation when blend amount is 0
- Improved pose update algorithm in Skeleton3D

**Comment by JoanPotatoes2021** [comment]
So I re-worked the animation tree to a new system, project file below, using fewer nodes whenever possible to achieve the same result as my previous prototype, here's how the second prototype animation tree looks:

![AnimationTree_PerfomanceTest_Transitions](https://user-images.githubusercontent.com/88800565/190220636-5b0f740a-3a6b-47dd-a44a-53ef09dd632a.jpg)

This new system looses a lot of blending which I had in my previous test, but it's easier to work with, I thought this system would improve the perfomance because transitions nodes should be easier to optmize, seems it's not the case, running the new prototype it behaved identical to the other, about ~5-6 fps,

[AnimTree_PerfomanceTest_Transition.zip](https://github.com/godotengine/godot/files/9568547/AnimTree_PerfomanceTest_Transition.zip)


![AnimationTree_PerfomanceTest_Transitions_02](https://user-images.githubusercontent.com/88800565/190223318-dd73a182-38fd-4891-a9b3-69a4aa7308c9.jpg)
