### ISSUE TITLE
SpotLight3d contribution to volumetric fog inconsistant when shadows are enabled or disabled

### ISSUE THREAD

**Issue by SilentPenguin** [godotengine/godot#65190]
### Godot version

4.0.alpha15.official (432b25d36)

### System information

Windows 11 Pro (OS Build 22000.918), Vulkan Clustered, i74770k x86_64, GTX 1080 SLI x2 (driver version 516.94)

### Issue description

Spotlight's fog contribution is inconsistant in the latest version of godot alpha with a fully updated device.

With shadows disabled, the light contributes to fog volume's lighting as expected. With shadows enabled, the Spotlight will only contribute to the fog volume's light under specific instances of distance from view and view angle.

Factors I have tested that influence contribution:
* Enabling and disabling a spotlight's shadows.
* Distance from view, but the light will not fade out, it's contribution will come and go at different distances.
* Angle of light in view.

Factors I have tested that do not appear to influence contribution:
* Scene geometry.
* Environmental Volume Fog.
* A Light's Shadow settings besides Enabling and disabling.
* Fog Volume resolution.
* Shadow atlas size.
* Disabling SLI.

This occurs both in the editor and when playing the project.

Below demonstrates the issue, the light on the left has shadows disabled, the right has shadows enabled.

![image](https://user-images.githubusercontent.com/186290/187893903-98315f77-15dd-4793-a845-703ee564a6da.png)

### Steps to reproduce

1. Create a new scene with a world environment, enable volumetric fog and insert some fog into the scene, either globally, or with a fog volume.
2. Insert a Spotlight3D, enable shadows on it.
3. Reorientate the view around until you find an angle and distance where its contribution disappears.
4. Disable shadows on the created light and note that contribution returns.

### Minimal reproduction project

[spotlight-reproducton.zip](https://github.com/godotengine/godot/files/9469257/spotlight-reproducton.zip)

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/57722.

**Comment by SilentPenguin** [comment]
Closing as dupicate.

**Comment by SilentPenguin** [comment]
closing as duplicate
