### ISSUE TITLE
`Font.get_string_size()` returns different value between alpha 14 and alpha 15 using non-default font

### ISSUE THREAD

**Issue by meowyih** [godotengine/godot#65198]
### Godot version

v4.0.alpha15.official [432b25d36]

### System information

Window11 64bits

### Issue description

$Label.get_string_size() returns different value between alpha 14 and alpha 15. The size I got in alpha 14 is correct, and alpha 15 returns a value that shorter than alpha14. 
It only happens when I use custom font. The default font works fine.

### Steps to reproduce

1. Create an 2D scene and add Label under Node2d.
2. Create a new theme and assign to Label. 
3. Assign the Font file for Label in theme. The font I used here is Google's NotoSansTC Font.
4. Try the code below:

```
func _ready():
	$Label.text = "文文文文文文"
	
	var text_size = $Label.get_theme_font("font").get_string_size( \
		$Label.text, HORIZONTAL_ALIGNMENT_LEFT, -1, \
		$Label.get_theme_font_size("font_size"))
	
	print( text_size )
```

In alpha 14, the text_size is (96,24). In alpha 15, the text_size is (72, 23). 

In both alpha 14 and 15, $Label.get_theme_font_size("font_size") returns 16, which is the correct default font size.

### Minimal reproduction project

[GetStringSize.zip](https://github.com/godotengine/godot/files/9470542/GetStringSize.zip)

**Comment by akien-mga** [comment]
Probably a theme propagation regression from #62845.

**Comment by YuriSizov** [comment]
> Probably a theme propagation regression from #62845.

I'm not sure.

This is a method of `Font`, not `Label`, and from the user report and my own testing of their MRP `$Label.get_theme_*` calls return the same data in both 14 and 15 (namely, the font size is 16). If there were issues with that, this probably wouldn't be true. And the content is rendered all the same, despite different values returned by `get_string_size`.

There were a number of changes to fonts in the meantime. Maybe @bruvzg has an insight?

**Comment by bruvzg** [comment]
It seems to be an issue with theme not set during `_ready`, try running in from a button click callback (or `_draw`), instead of `_ready`, and it will be correct.

<img width="390" alt="Screenshot 2022-09-01 at 23 33 07" src="https://user-images.githubusercontent.com/7645683/188006963-91e6c6e7-5f67-4849-a9b5-e1ffc56a7836.png">

**Comment by YuriSizov** [comment]
@bruvzg Thanks, I got it! That's a bit unexpected, but it seems that ENTER_TREE and READY happen in the same frame in this case, and thus deferred THEME_CHANGED call happens after READY.

Alright, I'll work on improving our setup tomorrow to avoid deferred calls (cc @AaronRecord).
