### ISSUE TITLE
Godot profiler is incorrect

### ISSUE THREAD

**Issue by 1419427247** [godotengine/godot#65208]
### Godot version

v4.0.alpha15.official

### System information

Windows10,Vulkan

### Issue description

/(ㄒoㄒ)/~~

### Steps to reproduce

https://user-images.githubusercontent.com/33598732/187963798-708a4489-3c8e-4bf8-9549-2c0e3bdd32e4.mp4

**Comment by Calinou** [comment]
Superseded by https://github.com/godotengine/godot/issues/65209.
