### ISSUE TITLE
Godot 4 - Game doesn't run on my Android phone (Moto G6, android 9)

### ISSUE THREAD

**Issue by Ajrarn777** [godotengine/godot#65217]
### Godot version

4.0.14

### System information

Android 9, vulkan

### Issue description

Game doesn't run on my android phone ([Moto G6](https://www.gsmarena.com/motorola_moto_g6-9000.php), Android 9).
I see the launching Godot boot screen logo, then nothing.

I have created a new app to test, same problem. 

When the remote debug is attached, I got thousand of logs like those:
```
E 0:00:22:0472   draw_list_draw: Condition "!dl" is true.
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:7747 @ draw_list_draw()
E 0:00:22:0472   framebuffer_format_get_texture_samples: Condition "!E" is true. Returning: TEXTURE_SAMPLES_1
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:4079 @ framebuffer_format_get_texture_samples()
E 0:00:22:0472   _generate_version: Condition "pipeline.is_null()" is true. Returning: RID()
  <C++ Source>   servers/rendering/renderer_rd/pipeline_cache_rd.cpp:60 @ _generate_version()
E 0:00:00:0569   _window_create: Condition "err != OK" is true. Returning: ERR_CANT_CREATE
  <C++ Source>   drivers/vulkan/vulkan_context.cpp:1461 @ _window_create()
E 0:00:00:0618   texture_create: Format 'R8_Uint' does not support usage as storage image.
  <C++ Error>    Method/function failed. Returning: RID()
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:1831 @ texture_create()
```

### Steps to reproduce

Create new app, run on android.

**Comment by dave2** [comment]
I'm also getting this (ironically with the same phone) using 4.0 alpha 16.

**Comment by Ajrarn777** [comment]
@dave2 It is not ironic, that's a hint ;) . 
Now we need to find other phones with the same issue, and the link between them. 

It was shipped with android 8, and upgraded to 9... maybe something like that.

**Comment by Zireael07** [comment]
A much more likely link is the GPU the device uses.

**Comment by dave2** [comment]
I tried my game on another device, this time a Samsung Galaxy Tab S3. Also running Android 9, and with a Adreno 530 GPU (different to the Moto G6 but same family). Same errors.

**Comment by dave2** [comment]
As of beta 3, I no longer get a looping set of errors about creating a 2-pass render, but it now just exits fairly early with this error:

```
E 0:00:00:0934   texture_create: Format 'R8_Uint' does not support usage as storage image.
  <C++ Error>    Method/function failed. Returning: RID()
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:1829 @ texture_create()
```

Followed by a warning from a singleton being imported. It doesn't appear to get as far as `_ready()` on a script on the root of the default scene. Could be something broken in a singleton but there's no error messages for them.

**Comment by clayjohn** [comment]
Looks like the main error here was fixed by https://github.com/godotengine/godot/pull/67227. So closing in favour of https://github.com/godotengine/godot/issues/67430 which reports the "R8_Uint" bug more specifically.

**Comment by Ajrarn777** [comment]
I confirm, issue is fixed in beta 3

Thanks for the follow up..

**Comment by salvin18** [comment]
Just wanted to share, in android export, If MSAA 3d is set to 2x, it renders 3d scenes as a black screen. UI components render fine.
Tested on Pixel 2xl with android 11
