### ISSUE TITLE
[4.0] (Label/RichTextLabel) Spaces don't display after newline.

### ISSUE THREAD

**Issue by Scarm2** [godotengine/godot#65215]
### Godot version

v4.0.alpha.custom_build

### System information

Windows 11, Vulkan, RTX 2060 Super (516.59)

### Issue description

This is not reproducible in 3.x

If you put spaces after a newline, they don't get drawn. No errors in the console though.
I don't know if it's intended (probably isn't) and I haven't seen anyone report this.

![image](https://user-images.githubusercontent.com/82760388/187975658-6cece7c2-5df3-4283-8d30-774c9baafc53.png)
![image](https://user-images.githubusercontent.com/82760388/187975345-f6ee5f55-6d6d-497b-86fa-ff2e1af7b21c.png)

No matter how many spaces are, it won't draw. This happens both in Label and RichTextLabel.
Restarting both Godot and the project doesn't fix the issue.

### Steps to reproduce

1. Open a project
2. Place a Label node
3. Attempt the process from **Issue Description**
4. Check if the spaces render

### Minimal reproduction project

**_None_**

**Comment by Mickeon** [comment]
I remember there was a `trim_edges()` somewhere in there in the text rendering code itself that prevented me from adding extra spaces when I tried to in https://github.com/godotengine/godot/pull/65140.

Yyeah, this didn't happen before, essentially voiding https://github.com/godotengine/godot/pull/64733.
![image](https://user-images.githubusercontent.com/66727710/187981428-0497df2e-397c-416a-af20-173e5bf2ff71.png)

**Comment by bruvzg** [comment]
I guess https://github.com/godotengine/godot/pull/65073 is trimming is too aggressively, should not do it after `\n` break.
