### ISSUE TITLE
Mono with real_t = double does not work

### ISSUE THREAD

**Issue by antonWetzel** [godotengine/godot#65219]
### Godot version

4.0.dev 8c7be635

### System information

Windows 11

### Issue description

Mono does not work if the Editor has double as real_t.

### Steps to reproduce

1. Build with `scons module_mono_enabled=true float=64`
1. Editor has `.mono` in name but nothing from Mono works

**Comment by akien-mga** [comment]
Did you build the assemblies and host them on a local Nuget repo?
https://github.com/godotengine/godot/blob/master/modules/mono/README.md

**Comment by antonWetzel** [comment]
`--generate-mono-glue` does not work, the editor acts like mono is disabled

**Comment by antonWetzel** [comment]
The Problem was with a cashed ´modules\modules_enabled.gen.h`, a clean rebuild solves the problem.
