### ISSUE TITLE
Support 64-bit ARM (ARMv8) on Android

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#6524]
Supporting 64-bit ARM (aka. ARMv8) on Android (along with the creation of fat binaries, containing both ARMv7 and ARMv8) would be nice, since it could offer small performance improvements. Many devices from this year such as the OnePlus 3 support ARMv8.

@reduz said it should be relatively easy, it should be a matter of adding a new compilation target for the `libgodot_android.so` file.

**Comment by bvbfan** [comment]
https://github.com/godotengine/godot/pull/6724
It's really not tested, hope it help :+1:

**Comment by Calinou** [comment]
Seems to be implemented as https://github.com/godotengine/godot/pull/9838 was merged.
