### ISSUE TITLE
Mono and float=64 do not work together

### ISSUE THREAD

**Issue by antonWetzel** [godotengine/godot#65246]
### Godot version

4.0 dev

### System information

Windows 11

### Issue description

- `./modules/mono/build_scripts/build_assemblies.py` has no flag for float=64 nor automatic detection
- `Color.cs` is missing some casts to float if `Real_t_is_double` is set manually
- Editor crashes without error at unknown stacktrace if CSharp Assemblies with 32 bit floats are used

### Steps to reproduce

1. `scons module_mono_enabled=true float=64`
2. `<binary> --generate-mono-glue --modules/mono/glue
3. - `./modules/mono/build_scripts/build_assemblies.py ...`

**Comment by AlmightyLaxz** [comment]
I also encountered this at the same time :)
#65251 will fix it

**Comment by antonWetzel** [comment]
Closed by https://github.com/godotengine/godot/pull/65251 and https://github.com/godotengine/godot/pull/65259 thanks to https://github.com/AlmightyLaxz.
