### ISSUE TITLE
PopupMenu.set_item_checked() checks item with index + 1

### ISSUE THREAD

**Issue by RayKoopa** [godotengine/godot#6526]
**Operating system or device - Godot version:**
Windows 10 x64, 2.1 stable

**Issue description** (what happened, and what was expected):
Hence the following code and result:
![wtf](https://cloud.githubusercontent.com/assets/9631152/18609324/b1f36824-7cff-11e6-8bb6-51f6f20c891f.png)
I don't do more than that. It looks like set_item_checked checks the item with the (index + 1) which was provided for `add_check_item`.

This might be a bug or me just misunderstanding the menu API again...

**Comment by vnen** [comment]
I'm pretty sure this is 0-indexed, so the `MENU_WALL` should be `0`, not `1`.

**Comment by RayKoopa** [comment]
Wait, shouldn't it be the index I provide with `add_check_item()` to start with?

**Comment by vnen** [comment]
As per the docs, you provide an `id` not the `index`, which are different things. I don't know what the `id` can be used for though there's `get_item_ID(int index)` and `get_item_index(int id)` functions.

**Comment by RayKoopa** [comment]
Ew, I see... guess things are getting a bit complicated then, but thanks for the help (I close it since it's not a bug... though a pretty silly way to handle menu items IMHO =D).

**Comment by akien-mga** [comment]
IMO that's something for the 3.0 refactoring, the current API is quite confusing IMO. @reduz did not want to change it until now as it would break compatibility.

**Comment by RayKoopa** [comment]
Oh thanks god! That sounds amazing and will double my donation when it's out... and yeah, I thought it will break existing things for now. But at least I'm not alone with my opinion =3
