### ISSUE TITLE
`SceneTreeTween`s `tween_property` TypeMismatch Error when `final_val` is given as int, when property is float

### ISSUE THREAD

**Issue by Arecher** [godotengine/godot#65274]
### Godot version

3.5.stable

### System information

Windows 10, GLES3

### Issue description

This is definitely more of an enhancement than a bug, but since it does seem to be a regression, I decided to report it (rather than propose it).

`SceneTreeTweens` that `tween_property` a **float** property, throw a TypeMismatch error when the `final_val` argument is an **int**. This did not happen with `Tween`s. They took the int values, and presumed them to be floats if required.

It is also inconsistent with the `duration` argument, which can be provided as a float OR an int, and does not error either way.

![image](https://user-images.githubusercontent.com/10502115/188249098-08cbe044-9a2c-4bfc-943b-d4395e256d9c.png)
_a small overview of the different Tweens and this issue_

We use Tween/SceneTreeTween mostly to modify the rect_position/rect_size of Control nodes, which we always set at whole numbers/pixels. This means I keep running into these errors, which invalidate the set-up tweens, and crashes the project when they are further modified.

_I do understand that certain properties are typed specifically as floats, and cannot take ints at all. However, in many instances within Godot, providing an int where a float was expected is completely valid, as it is with setting rect_position. The fact that SceneTreeTweens break this seems undesirable._

### Steps to reproduce

See MRP.

1. Create SceneTreeTween, with tween_property. Tween a float property, such as a position.x
2. Provide an **int** value as a `final_val` argument
3. Start the tween (`ui_left` in MRP)
4. You will have gained an Error
![image](https://user-images.githubusercontent.com/10502115/188249332-0bb7746e-6196-48e2-aa94-bb3683623448.png)

### Minimal reproduction project

[SceneTreeTweenIntVFloat.zip](https://github.com/godotengine/godot/files/9481579/SceneTreeTweenIntVFloat.zip)

**Comment by timothyqiu** [comment]
Should be fixed once #65072 is cherry-picked.
