### ISSUE TITLE
Game crashed with "Internal Script Error! - opcode #13 (report please)."

### ISSUE THREAD

**Issue by galbacarys** [godotengine/godot#6528]
**Operating system or device - Godot version:**
Ubuntu 16.04, x86_64
Godot v2.1.Stable.Official

**Issue description** (what happened, and what was expected):
My game is frequently crashing, sometimes showing the above error (with the following text: `Condition 'p_index<0 || p_index>=size()' is true. returned: aux` in the error window) and sometimes without either happening. I was able to get a stack trace on the script where it happened, and it looks like this:

```
func _fixed_process(delta):
    # do some stuff
    # ....
    if position.length() > MAX_DIST:
        free()
    if collider.is_colliding(): # <-- FAILS HERE
        free()
```

`collider` is a KinematicBody2D with a CollisionPolygon2D as its child. (I don't know if I did this part right, as collisions haven't been working so far in my game anyway).

**Steps to reproduce:**
Run a script containing the above code. Watch things explode. Feel the cold steely grip of despair.

With my game specifically: Hold the space bar to launch a space ship, and make it fly off screen. It will occasionally trigger the error.

**Link to minimal example project** (optional but very welcome):

[Kinetic Defense Force](https://github.com/galbacarys/KineticSpaceDefense)

**Comment by volzhs** [comment]
Is it because of `free()`?
http://docs.godotengine.org/en/latest/tutorials/step_by_step/scripting_continued.html?highlight=queue_free#creating-nodes

**Comment by galbacarys** [comment]
Yup-switched to `queue_free()` and the issue seems to be fixed. Thanks!

**Comment by galbacarys** [comment]
Just realized-this should probably print a more helpful error message. With more experimentation I noticed that, for example, calling `free()` during a signal handler causes an error message, that might be useful to add in this case.

**Comment by Sslaxx** [comment]
Maybe free should be obsoleted/removed and queue_free moved over to take its place.

**Comment by volzhs** [comment]
`free()` is needed if just instance it, not add it to scene tree, and free it manually. I used it in my personal project.
AFAIK, `queue_free()` works only instance is inside tree, doesn't it?
