### ISSUE TITLE
Can't return an `int` in `float`-returning functions

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#65286]
### Godot version

4.0 alpha 15

### System information

linux

### Issue description

```gdscript
func f() -> float:
    return 0
```
![image](https://user-images.githubusercontent.com/71937306/188273039-c9ae29fa-7e7f-487d-8f8f-a582b252ec27.png)

It may make sense to error out on implicit `float` -> `int` conversion but in this example `int`s should be casted automatically and without warning, or at least I don't see why they would not.

### Steps to reproduce

see above

**Comment by Calinou** [comment]
In my opinion, implicit `int -> float` conversion should be allowed – but not the other way around as it loses precision.

**Comment by MGilleronFJ** [comment]
`int -> float` can cause truncation if the integer has more than 7 digits (a bit more when using 64-bits). So it's more about allowing it anyways for convenience. `int -> float` rather causes less unintented loss of data than `float -> int`.

**Comment by vonagam** [comment]
`float -> int` implicit conversion does has a warning called `NARROWING_CONVERSION`.
