### ISSUE TITLE
Alpha 15. Using Tween to interpolate 3D rotation gives different behaviour in alpha 15 vs. alpha 14

### ISSUE THREAD

**Issue by ModularNucleus** [godotengine/godot#65287]
### Godot version

4.0 alpha 14

### System information

Windows 10.

### Issue description

**In alpha 14:**
- When either using Tween.interpolate_value() or Tween.tween_property() to interpolate the rotation of a Node3D towards another Node3D (to make it a "rotation follower"), the code in the included MRP gives a reasonable and expected result. The Script for the MeshInstance3D includes to different functions that can be commented out to switch between the two different approaches.
- With interpolate_value():

https://user-images.githubusercontent.com/91982860/188273309-5fbb8911-aba0-4ca6-b58a-6c327734c295.mp4

**In alpha 15:**
- When using the function with Tween.interpolate_value(), the rotation of the interpolated Node3D ("the follower") is erratic and never stops again:

https://user-images.githubusercontent.com/91982860/188273331-c0a733ee-5454-4a91-b2c5-0815ca66eba2.mp4

- When using the function with Tween.tween_property(), the console spams:
"E 0:00:01:0158   slerp: The end quaternion must be normalized.
  <C++ Error>    Condition "!p_to.is_normalized()" is true. Returning: Quaternion()
  <C++ Source>   core/math/quaternion.cpp:125 @ slerp()
"

Now, I'm not sure if there is something wrong with my code - but since there is a large difference in behaviour between the two alphas, maybe there is a regression somewhere?

### Steps to reproduce

- Open the MRP in alpha 14 and 15
- Use the left and right arrow keys to spin the "Rotator" Node3D "left" or "right". The "Follower" MeshInstance3D's rotation is interpolated towards the rotation of "Rotator".
- Observe the reasonable results in alpha 14 and the erratic behaviour in alpha 15.

[Tween Interpolation Test.zip](https://github.com/godotengine/godot/files/9482977/Tween.Interpolation.Test.zip)

**Comment by kleonc** [comment]
@ModularNucleus There's actually no MRP provided.

**Comment by ModularNucleus** [comment]
@kleonc Whoops, sorry about that. I have attached it to the original post now.

**Comment by TokageItLab** [comment]
Maybe it is regression by https://github.com/godotengine/godot/pull/64678 and https://github.com/godotengine/godot/pull/65131. I will send fix PR.

**Comment by TokageItLab** [comment]
I have looked at the project and it is probably not a bug.

Alpha14 could handle unnormalized quaternions, but the quaternion interpolation is wrong to begin with. However, the broken quaternions were normalized after they were set in Node3D. Again, this interpolation does not respect the tween expression and is broken.

Since Alpha15, quaternions are now interpolated correctly by slerp, so they will not interpolate unless they are normalized quaternions. Also, there was a mistake with the tween in your project.

```gdscript
func tween_interpolate_value(delta: float) -> void:
	var a: Quaternion = self.quaternion
	var b: Quaternion = target.quaternion
	
	if not a.is_equal_approx(b):
		quaternion = tw.interpolate_value(a, a.slerp(b, 0.5), delta, 0.05,
				Tween.TRANS_SINE, Tween.EASE_IN_OUT)
```
↓
```gdscript
func tween_interpolate_value(delta: float) -> void:
	var a: Quaternion = self.quaternion
	var b: Quaternion = target.quaternion
	
	if not a.is_equal_approx(b):
		self.quaternion = tw.interpolate_value(a, a.inverse() * b, delta, 0.05,
				Tween.TRANS_SINE, Tween.EASE_IN_OUT)
```

The delta_value in tween_interpolate_value needs to be set to the value of the difference such as `a.inverse() * b`, not `a.slerp(b, 0.5)`. However, it seems to me that using a tween at such a small distance is the wrong way to use a tween in the first place.

**Comment by ModularNucleus** [comment]
@TokageItLab Thank you for taking a look. You're right, setting it to "a.inverse() * b" fixes the erratic interpolation (I'm a novice programmer, hence the disclaimer).

The console still spams the error even if I normalize() the quaternions first. But perhaps that is not what you meant? Anyway, if this is expected behaviour, then it is of course fine by me. Using a tween for this is probably the wrong choice, as you say.

**Comment by TokageItLab** [comment]
Yes, it is a bit odd to get an error even though it is normalized. Also needs to be fixed regarding the Transform3D tween. I will continue to work on fixing it.
