### ISSUE TITLE
HTML5 export fails to run with error "USER WARNING: Could not create 3D renderbuffer, status: 36054"

### ISSUE THREAD

**Issue by dsnopek** [godotengine/godot#65304]
### Godot version

v4.0.alpha.custom_build [2deb6a711]

### System information

Chrome, GLES3

### Issue description

At the moment, 3D projects exported to HTML5 will fail to run (right after loading) with the error:

```
USER WARNING: Could not create 3D renderbuffer, status: 36054
```

I suspect that it's related to the changes from PR #63901, but I don't really know.

### Steps to reproduce

1. Create a new project
2. Go to "Project settings..." and turn on "Advanced Settings"
3. In "Rendering" -> "Driver" set the "Driver Name" to "opengl3"
4. Restart the editor
5. Create a new scene with a Node3D as the root
6. Add a MeshInstance3D with a box mesh
8. Add a Camera3D that is pointing at the Cube, and set it to current
9. Save the scene, run the project, and use the current scene as the main scene when prompted
10. **Verify that you can see the cube when running on the desktop!**
11. Export the game to HTML5
12. Use the "Run exported HTML the system's default browser" button in the upper-right (the one that looks like the HTML5 logo, but the normal run button)
13. **You'll see the loading bar and then blackness**
14. If you look in the browser's developer console, you'll see the error message mentioned above

### Minimal reproduction project

[godot4-gles3-rb.zip](https://github.com/godotengine/godot/files/9483560/godot4-gles3-rb.zip)

**Comment by BastiaanOlij** [comment]
Not sure what changed that could have caused this because I don't think I've changed how render buffers are created on GLES3, only some organizational things changed. The big changes were all in the RenderDevice side.

Especially seeing it all still works on desktop, I'm not too familiar with the HTML side of things, maybe @clayjohn can have a look? Hopefully it's something simple.

**Comment by dsnopek** [comment]
> Not sure what changed that could have caused this because I don't think I've changed how render buffers are created on GLES3, only some organizational things changed. The big changes were all in the RenderDevice side.

It was just a guess! It could be something else entirely. Weird things can break WebGL - it's closer to GLES than OpenGL, and can be stricter (or just different) than OpenGL. But rendering is one of my weaker areas so I'm a little bit out of my depth here :-)
