### ISSUE TITLE
Text editor should not have focus after crash to prevent unwanted input

### ISSUE THREAD

**Issue by 1000h** [godotengine/godot#6530]
**Operating system or device - Godot version:**
2.1 stable windows 8.1

**Issue description** (what happened, and what was expected):
When you are holding down an input key and the game testing halts/crashes, if the text editor is open, the key starts typing in the text editor, and you are bound to ctrl-z every time you have an issue.  Gaaah!!
Want not the input to continue once game test has stopped
**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by henriquelalves** [comment]
Just for the sake of making it clear, I messed up the commits before I realized I was trying to solve this issue on the wrong PR, haha. The PR in which I corrected it is #6847.
