### ISSUE TITLE
Add a way to change weight_scale on runtime

### ISSUE THREAD

**Issue by MarianoGnu** [godotengine/godot#6531]
Today i've been using the AStar pathfinding class, and it works really well, but i found myself with a problem, i wanted change the scale of some points to prevent the player from moving over there, but there's no way to change it. Other way to do it was removing all the conections and add them back again, but chaging the weight scale is easier imo, besides, my game will most likely need to have different weight scales for every character (sinces some of them walks, other rides a horse and others flyes) and terrain weigth is linked to this.
So there are 2 things i'd like to be able to do:
1. have a set_weight_scale(int point_id) function
2. have a set_custom_weigth_calculator(object, string function_name)
func function_name(int point_from, int_point_to)

**Comment by reduz** [comment]
I am still unconvinced about how it works with weight.

1) Should weight be a multiplier or an extra distance?
2) Should weight be by node or connection?

**Comment by MarianoGnu** [comment]
Well, in some cases you don't want weight to be related to distance, this was the case in the first time i used AStar, in a tabletop board game, i was doing the movement of the pieces around the table, and there was no weight on the nodes at all, except when there was another player in the middle.
that's why i recomended delegating the weight to a custom function, passing the id of the nodes from and to you are moving, you can access to the position, distance and weight scale using the functions already available on the AStar API, if you just want to make linear movements you could just use the formula it's already builtin.

**Comment by cefleet** [comment]
Another need to have weights at runtime is lets say that unit A can go over water at 3x speed and unit B can go over water at 0.5x speed. Well when it is unit A's turn the weights need to be different than when it it is Unit Bs turn. I'd say keep it a multiplier. 
Now by Node or Connection.. I really don't have an opinion.

**Comment by reduz** [comment]
probably doing what Mariano suggests (a callback to get weight)  might work
too?

**Comment by cefleet** [comment]
I wrote a long comment basically repeating when Mariano said and realized I just repeated him. Currently I add and remove connections before each units turn. But yeah.. what he said.

**Comment by MarianoGnu** [comment]
another point on calculatin weights, right now weights are per node, now imagine a node in the top of the cliff, you probably want your AI to jump down the cliff (in other words, a one way collision) but not the oposite way, because he can't jump higth enought to reach the other side, this means it needs a one way connection, a way to solve it is using the function i described and use a raycast to check if it's possible to move from one point to the other. also imagine a map with a mountain, it's posible to move up and down the mountain, but maybe you want to have a bigger weigth if you are climbing up.

**Comment by bojidar-bg** [comment]
Closing as fixed by #8146, feel free to comment/reopen if this is not the case.
