### ISSUE TITLE
Export to AAB file does not work in v4.0.alpha15

### ISSUE THREAD

**Issue by trash-max** [godotengine/godot#65324]
### Godot version

v4.0.alpha15.official.432b25d36

### System information

Ubuntu 22.04.1 LTS, Mesa Intel® Graphics (RKL GT1) (630) Vulkan API 1.2.0

### Issue description

The file "android_source.zip" from export templates for 4.0.alpha 15 does not contain the necessary libraries for building and publishing the application.

Play console check returning error: “This release is not compliant with the Google Play 64-bit requirement. The following APKs or App Bundles are available to 64-bit devices, but they only have 32-bit native code”

### Steps to reproduce

Just try export AAB with v4.0.alpha15 and check it with bundletool or upload on Play Console
I solved the problem by directly copying file android_source.zip from 4.0.alpha14 folder.

**Comment by akien-mga** [comment]
For reference, some libraries were indeed missing from the alpha 15 export templates due to a build script error.
