### ISSUE TITLE
Expose Image::set_indexed_pixel, get_indexed_pixel, set_palette methods for GDScript

### ISSUE THREAD

**Issue by mishapsi** [godotengine/godot#6532]
I've been trying to work indexed_alpha images.  Currently there's no way to work with the raw array you get from Image.get_data().  While you can edit the palette values of the returned raw array, there doesn't exist a method to set the modified raw data for the image.  So I dug around the source code noticed these methods, though I'm uncertain as to whether they are complete, they sound exactly like what I am looking for, and if they are functional it'd be nice to expose them to GDscript.  I've tried to edit the source code myself, haven't had any luck to edit the core Image class.  Any help would be appreciated, thanks!

**Comment by bojidar-bg** [comment]
Slightly bumping, especially given that @reduz refactored the Image class.

Did anything related to the issue change? :smile:

**Comment by ElfEars** [comment]
As far as I can see these functions neither exist in the latest stable version or the latest beta.
A shame as they would be really useful for many effects.

**Comment by reduz** [comment]
Indexed image formats are not supported in modern OpenGL, so it's pointless to support them. You can do the same effects with shaders if you want anyway.

**Comment by Noshyaar** [comment]
I'll close this as wontfix. If there are demands for this functionality, you can still discuss.
