### ISSUE TITLE
PanoramaSky: PNG looks terrible, HDR stuck on "(re)Importing Assets"

### ISSUE THREAD

**Issue by venilark** [godotengine/godot#65332]
### Godot version

4.0 Alpha 15

### System information

Windows 10

### Issue description

Given Godot's lack of Cubemap support, I had to use an online tool to convert a cubemap to an equirectangular image so it can be used with the PanoramaSky. I converted it and to my surprise it looks awful when imported into Godot.

Here is what it looks like when opened in Blender
![blender](https://user-images.githubusercontent.com/98270528/188324223-00349b31-24e2-45d5-9263-6faec1a5ff2a.PNG)

same in Godot after the conversion
![godot](https://user-images.githubusercontent.com/98270528/188324248-59743993-8511-499d-8353-36b5541ee63f.PNG)

So I converted to HDR using another online tool, it worked and it looked good, but now every time I try to drag it onto the "PanoramaSkyMaterial>Panorama" slot I get this
![reimporting](https://user-images.githubusercontent.com/98270528/188324306-6dba0bbf-1dca-4dc3-bc1e-f1b0b1142199.PNG)

If it is a matter of adjusting some options so the PNG image looks good then that would be fine for me but nothing I tried worked, image always looks terrible.

### Steps to reproduce

Try to drag sky-panorama.hdr onto the "PanoramaSkyMaterial>Panorama" slot, as soon as it makes contact with the viewport you'll get the "(re)Importing Assets".

### Minimal reproduction project

Due to file size I can't upload the whole project, just create a WorldEnvironment, add the PNG one first to see how it looks once imported and then drag the HDR one onto that slot for the reimport error.
[HDR-PNG-panoramas.zip](https://github.com/godotengine/godot/files/9485113/HDR-PNG-panoramas.zip)

**Comment by Calinou** [comment]
VRAM compression makes this kind of pattern look quite bad, so I recommend switching the PNG image to use Lossless compression in the import dock.

**Comment by venilark** [comment]
> The freeze on importing HDR images is already being tracked in #61948.
> 
> As for PNG quality: VRAM compression makes this kind of pattern look quite bad, so I recommend switching the PNG image to use Lossless compression in the import dock. Make sure to do this _after_ the texture is detected to be used in 3D, as Godot will revert it to VRAM Compressed otherwise.

Thank you now it looks good, I think it shouldn't revert the settings you chose but at least it works.
If I change the Panorama texture at runtime it should keep the latest settings, right? So technically once Godot knows I want that texture to be used for 3D (by doing what you told me in a test scene for example) and to be Lossless it shouldn't modify anything ever again in any scene.

**Comment by Calinou** [comment]
> If I change the Panorama texture at runtime it should keep the latest settings, right?

Yes, the Detect 3D flag is only set once per texture.
