### ISSUE TITLE
The editor continuously redraws in an empty project regardless of which main screen is selected

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#65339]
### Godot version

v4.0.alpha.custom_build [b8977ca33]
v4.0 alpha15

### System information

Windows 10 64 bits GLES3 GeForce GTX 1060 6GB/PCIe/SSE2

### Issue description

I found various similar issues for Godot 3 and others in Godot 4 describing specific parts of the editor, but I noticed the update spinner shows that Godot is constantly redrawing, even in an empty project, regardless of which main screen is open. By default it is set to `update when changed`, so constant redraws when idle is not expected.

### Steps to reproduce

Have the update spinner shown. Open any project, just make it so no scenes are open. Observe it spins constantly.

**Comment by Calinou** [comment]
I can confirm this on 4.0.alpha15 and 4.0.alpha daec089c3, but not 4.0.alpha14. I'm looking into bisecting this as we speak.

**Comment by Calinou** [comment]
I bisected the regression to f02d45ce0c35c9cd98fb4bee8456a97e9e0927ac. cc @bruvzg
