### ISSUE TITLE
set_window_mouse_passthrough only works in certain areas on the screen

### ISSUE THREAD

**Issue by pgorley** [godotengine/godot#65337]
### Godot version

v3.5.stable.official [991bb6ac7]

### System information

OpenGL ES 3.0 Renderer: Apple M1 Pro

### Issue description

When using OS.set_window_mouse_passthrough, the area where the Polygon2D actually prevents clicks seems to be arbitrary.

<img width="1060" alt="Screen Shot 2022-09-04 at 2 28 36 PM" src="https://user-images.githubusercontent.com/422288/188328261-6096d516-3e25-49ba-a8ec-8bf6e41e638a.png">

### Steps to reproduce

In the Minimal reproduction project, launch the ClickThroughTest.tscn scene.

- Click the toggle on the left area.
- Notice that you should be able to click through all areas of the window except for the highlighted polygon2d on the left side.
- Untoggle the left side

- Click the toggle on the right area.
- Notice that everything can be clicked through.  The polygon2d on the right side does not prevent clicking through.
- You may not be able to untoggle the right side since all clicks are going through the app. You may need to kill the app.

### Minimal reproduction project

[ClickThroughTest.zip](https://github.com/godotengine/godot/files/9485275/ClickThroughTest.zip)

**Comment by Calinou** [comment]
I wonder if this is an issue caused by macOS' lowDPI fallback. Try enabling **Allow Hidpi** in the project settings, and use the `2d` stretch mode in the project settings to make the UI scale as you increase the window size.

**Comment by pgorley** [comment]
Thanks for the quick response.  However, I tried enabling hiDPI and enabled 2D stretch mode. The problem still exists, but not it's exacerbated - depending on how much your drag the window, the left side polygon2d is no longer respected (it does seem as though the area which is blocked from passthrough is scaled).
 
<img width="685" alt="Screen Shot 2022-09-04 at 2 56 43 PM" src="https://user-images.githubusercontent.com/422288/188329225-e712a3a4-971b-45a9-8675-0f64754de231.png">

**Comment by bruvzg** [comment]
`OS.set_window_mouse_passthrough` takes a polygon as an array of points `PoolVector2Array` not as `Polygon2D` node, so it won't be aware of the position of `NoClick2` node, and both of the polygons will cover the same area in the top-left corner of the window.

You should either manually add offset to each point of the array before passing it to the function, or move `NoClick2` node to the `0, 0` position and adjust points to cover the desired area.

**Comment by pgorley** [comment]
Aha, I had the offset and position messed up. I duplicated the first NoClick area and that caused all my problems.

Thanks all for the quick and pertinent responses.
