### ISSUE TITLE
ProxyTexture missing in Godot 4 alpha 15

### ISSUE THREAD

**Issue by ywmaa** [godotengine/godot#65349]
### Godot version

4.0.alpha15

### System information

linux pop os 22.04

### Issue description

as title says

### Steps to reproduce

try to assign a proxy texture, you won't find it.
or open an old project from previous alphas it will return an error for proxy textures

**Comment by clayjohn** [comment]
Proxytexture was intentionally removed in https://github.com/godotengine/godot/pull/64595. The reason is in the PR.
