### ISSUE TITLE
get_datetime_* functions can return wrong values 

### ISSUE THREAD

**Issue by miv391** [godotengine/godot#65377]
### Godot version

00fa4e23e4b967291034ea7bb018dea638b37e8f

### System information

all OSes

### Issue description

This was first noticed by aaronfranke in another issue: https://github.com/godotengine/godot/issues/60327#issuecomment-1101453623

In https://github.com/godotengine/godot/blob/master/core/os/time.cpp this function is used to return datetime dict:

```c++
Dictionary Time::get_datetime_dict_from_system(bool p_utc) const {
	OS::Date date = OS::get_singleton()->get_date(p_utc);
	OS::Time time = OS::get_singleton()->get_time(p_utc);
	Dictionary datetime;
	datetime[YEAR_KEY] = date.year;
	datetime[MONTH_KEY] = (uint8_t)date.month;
	datetime[DAY_KEY] = date.day;
	datetime[WEEKDAY_KEY] = (uint8_t)date.weekday;
	datetime[DST_KEY] = date.dst;
	datetime[HOUR_KEY] = time.hour;
	datetime[MINUTE_KEY] = time.minute;
	datetime[SECOND_KEY] = time.second;
	return datetime;
}
```

Date and time parts are fetched using separate `get_date` and `get_time` calls. If the `get_date` call is made just before day ends (e.g. 2022-01-31 23:59:59.999999) and `get_time` call is made on the next day (e.g 2022-02-01 00:00:00.0000001) the resulted datetime dict will be 2022-01-31 00:00:00.0000001, which is wrong by 24 hours. The same problem is in `get_datetime_string_from_system` function.

This could be fixed by adding to `core/os/os.h` a new `get_datetime` function which would get both date and time using just one OS call.

### Steps to reproduce

I haven't actually seen this bug to happen and the bug would be quite hard to reproduce as the timing must perfect.

**Comment by gotnospirit** [comment]
My commit was from a 3.x, but I will port it for master and make a PR
