### ISSUE TITLE
Label's set_text method works like if it was called like this: set_text(tr("key"))

### ISSUE THREAD

**Issue by Rocket-Buddha** [godotengine/godot#6538]
Operating system or device - Godot version:

Fedora 24 - 64 Bits. Godot 2.1

Issue description (what happened, and what was expected):

What happened: Label's text was changed by translation string with these key.
What was expected: Label text was changed by a number (or by any other string).

Steps to reproduce:
1. Import translation with number key.
2. Try to change label's text by code. For example: label.set_text("1")

**Comment by bojidar-bg** [comment]
Umm... that's a feature actually :smile: Not sure if there is any way to get it off though.

**Comment by Rocket-Buddha** [comment]
I think that it'd be better if the API allow me to decide when get the translation and put it in to a control and when set a string directly in to this. I need to implement a countdown whit strings numbers, i'll put numbers on translations sheet and implement a matching logic between the number and the key but i don't think that i be the best solution. Thanks a lot!

**Comment by txzeenath** [comment]
IMO it should stay as it us unless an override is added (like raw_set). The main benefit of the translation system in godot is that it replaces all matches. If you don't want it replaced then it shouldn't be in the translations :-p

**Comment by Rocket-Buddha** [comment]
I understand your point of view but i'm implementing translations keys with numbers. In this case i need to set numbers 3, 2 and 1 in a label control (countdown). Should i change my translations keys? i don't know...

**Comment by vnen** [comment]
This just needs better documentation. It can't be changed because otherwise it's impossible to use translated text when setting via editor. You would *have* to set via script to be able to translate, making it very cumbersome.

**Comment by akien-mga** [comment]
Moved the documentation need to godotengine/godot-docs#1932.
