### ISSUE TITLE
Custom types no longer have a grayed icon

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#65383]
### Godot version

[00fa4e2](https://github.com/godotengine/godot/commit/00fa4e23e4b967291034ea7bb018dea638b37e8f)

### System information

Windows 10 x64

### Issue description

Nodes added with `add_custom_type()` used to have gray icon.
![image](https://user-images.githubusercontent.com/2223172/188512796-37d1e0fa-f290-46ed-835d-c62f8dcdd71e.png)
Now they dont.
![image](https://user-images.githubusercontent.com/2223172/188512770-68af97ea-430b-40df-9555-9a1b32095727.png)

I noticed that tool script icons now use accent color. Maybe that PR caused the issue.

### Steps to reproduce

1. Add the MRP to some project
2. Create TestSprite
3. Observe the script icon

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/9491998/test.zip)

**Comment by Mickeon** [comment]
[Oops](https://github.com/godotengine/godot/pull/65088)

**Comment by KoBeWi** [comment]
I checked and that PR is not the cause.

**Comment by Mickeon** [comment]
I fixed the colouring not being darkened, but at its core it seems like `EditorNode::get_singleton()->get_object_custom_type_base(p_node)` does not return a Script, or at least not the right now.

**Comment by ItsNL** [comment]
I have tried your test project. If you write class_name to the script of your class, it grays the script icon.
![image](https://user-images.githubusercontent.com/109873547/188516988-3fffe8e2-b866-44d8-ab21-6dae0569abd5.png)
![image](https://user-images.githubusercontent.com/109873547/188516990-f33c55e4-091b-44c8-a431-4cd151dca2dc.png)
But when you restart the project, it says it is conflicting with a global class:
![image](https://user-images.githubusercontent.com/109873547/188517390-48a6194a-fffa-4483-ab1a-4b4c42dd0058.png)

**Comment by Mickeon** [comment]
Is the problem that the custom type is not registered correctly, at all?

**Comment by ItsNL** [comment]
> Is the problem that the custom type is not registered correctly?

Looks like

**Comment by atngames** [comment]
The icon is not gray if I use class_name in beta3 either

**Comment by KoBeWi** [comment]
Seems fixed on master.
