### ISSUE TITLE
"Config file does not exist" when templates is a symlink

### ISSUE THREAD

**Issue by caryoscelus** [godotengine/godot#6539]
**Operating system or device - Godot version:**
Debian GNU/Linux - both 2.1 & git master

**Issue description** (what happened, and what was expected):
I removed `.godot/templates` and symlinked templates directory from another place and Godot started complaining about non-existing config:

```
WARNING: create: Config file does not exist, creating.
   At: tools/editor/editor_settings.cpp:337
```

And as it said, Godot indeed created new config file, deleting old one. Since it however didn't touch `templates` link, this behaviour persisted and each time i loaded Godot, i got empty config.

**Steps to reproduce:**
- replace `templates/` directory inside `~/.godot` with symlink to directory with templates
- launch godot

**Comment by bojidar-bg** [comment]
Another symlink issue, maybe we should start a tracker @vnen @akien-mga ?

**Comment by akien-mga** [comment]
Seems to work fine now in the current master branch (631cf67) on Linux.
