### ISSUE TITLE
XRControllers do not track in projects created in alpha 15.

### ISSUE THREAD

**Issue by addmix** [godotengine/godot#65395]
### Godot version

4.0 alpha 15

### System information

Windows 10

### Issue description

In any OpenXR project created in alpha 15, controllers do not track and output is flooded with errors. Projects made in other alphas function in alpha 15, it only applies to newly created projects.

Output of minimum reproduction project:

```OpenXR: Running on OpenXR runtime:  Oculus   1.75.0
Godot Engine v4.0.alpha15.official.432b25d36 - https://godotengine.org
OpenXR: XrGraphicsRequirementsVulkan2KHR:
 - minApiVersionSupported:  1.0.0
 - maxApiVersionSupported:  1.0.0
OpenXR: Requested Vulkan version exceeds the maximum version this runtime has been tested on and is known to support.
- desired_version  1.2.0
- minApiVersionSupported  1.0.0
- maxApiVersionSupported  1.0.0
Vulkan API 1.2.0 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1070
 
OpenXR: failed to create action  default_pose ! [ XR_ERROR_PATH_UNSUPPORTED ]
OpenXR: failed to create action  haptic ! [ XR_ERROR_PATH_UNSUPPORTED ]
OpenXR: failed to suggest bindings for  /interaction_profiles/htc/vive_tracker_htcx ! [ XR_ERROR_VALIDATION_FAILURE ]
OpenXR: Found supported reference space  XR_REFERENCE_SPACE_TYPE_VIEW
OpenXR: Found supported reference space  XR_REFERENCE_SPACE_TYPE_LOCAL
OpenXR: Found supported reference space  XR_REFERENCE_SPACE_TYPE_STAGE
OpenXR: Found supported swapchain format  VK_FORMAT_R8G8B8A8_UNORM
OpenXR: Found supported swapchain format  VK_FORMAT_R8G8B8A8_SRGB
OpenXR: Found supported swapchain format  VK_FORMAT_B8G8R8A8_UNORM
OpenXR: Found supported swapchain format  VK_FORMAT_B8G8R8A8_SRGB
OpenXR: Found supported swapchain format  VK_FORMAT_R16G16B16A16_SFLOAT
OpenXR: Found supported swapchain format  VK_FORMAT_B10G11R11_UFLOAT_PACK32
OpenXR: Found supported swapchain format  VK_FORMAT_D16_UNORM
OpenXR: Found supported swapchain format  VK_FORMAT_D32_SFLOAT
OpenXR: Found supported swapchain format  VK_FORMAT_D24_UNORM_S8_UINT
OpenXR: Found supported swapchain format  VK_FORMAT_D32_SFLOAT_S8_UINT
OpenXR: Found supported swapchain format  VK_FORMAT_BC1_RGBA_UNORM_BLOCK
OpenXR: Found supported swapchain format  VK_FORMAT_BC1_RGBA_SRGB_BLOCK
OpenXR: Found supported swapchain format  VK_FORMAT_BC2_UNORM_BLOCK
OpenXR: Found supported swapchain format  VK_FORMAT_BC2_SRGB_BLOCK
OpenXR: Found supported swapchain format  VK_FORMAT_BC3_UNORM_BLOCK
OpenXR: Found supported swapchain format  VK_FORMAT_BC3_SRGB_BLOCK
OpenXR: Found supported swapchain format  VK_FORMAT_BC6H_UFLOAT_BLOCK
OpenXR: Found supported swapchain format  VK_FORMAT_BC6H_SFLOAT_BLOCK
OpenXR: Found supported swapchain format  VK_FORMAT_BC7_UNORM_BLOCK
OpenXR: Found supported swapchain format  VK_FORMAT_BC7_SRGB_BLOCK
OpenXR initialised successfully
Using swap chain format: VK_FORMAT_R8G8B8A8_SRGB
OpenXR: Failed to get interaction profile for 277197189284016 [ XR_ERROR_PATH_UNSUPPORTED ]
OpenXR: Failed to get interaction profile for 277197189284017 [ XR_ERROR_PATH_UNSUPPORTED ]
OpenXR: Failed to get interaction profile for 277197189284018 [ XR_ERROR_PATH_UNSUPPORTED ]
OpenXR: Failed to get interaction profile for 277197189284019 [ XR_ERROR_PATH_UNSUPPORTED ]
OpenXR: Failed to get interaction profile for 277197189284020 [ XR_ERROR_PATH_UNSUPPORTED ]
OpenXR: Failed to get interaction profile for 277197189284021 [ XR_ERROR_PATH_UNSUPPORTED ]
OpenXR: Failed to get interaction profile for 277197189284022 [ XR_ERROR_PATH_UNSUPPORTED ]
OpenXR: Failed to get interaction profile for 277197189284023 [ XR_ERROR_PATH_UNSUPPORTED ]
OpenXR: Failed to get interaction profile for 277197189284024 [ XR_ERROR_PATH_UNSUPPORTED ]
OpenXR: Failed to get interaction profile for 277197189284025 [ XR_ERROR_PATH_UNSUPPORTED ]
OpenXR: Failed to get interaction profile for 277197189284026 [ XR_ERROR_PATH_UNSUPPORTED ]
OpenXR: Failed to get interaction profile for 277197189284027 [ XR_ERROR_PATH_UNSUPPORTED ]
OpenXR: Failed to get interaction profile for 277197189284016 [ XR_ERROR_PATH_UNSUPPORTED ]
OpenXR: Failed to get interaction profile for 277197189284017 [ XR_ERROR_PATH_UNSUPPORTED ]
OpenXR: Failed to get interaction profile for 277197189284018 [ XR_ERROR_PATH_UNSUPPORTED ]
OpenXR: Failed to get interaction profile for 277197189284019 [ XR_ERROR_PATH_UNSUPPORTED ]
OpenXR: Failed to get interaction profile for 277197189284020 [ XR_ERROR_PATH_UNSUPPORTED ]
OpenXR: Failed to get interaction profile for 277197189284021 [ XR_ERROR_PATH_UNSUPPORTED ]
OpenXR: Failed to get interaction profile for 277197189284022 [ XR_ERROR_PATH_UNSUPPORTED ]
OpenXR: Failed to get interaction profile for 277197189284023 [ XR_ERROR_PATH_UNSUPPORTED ]
OpenXR: Failed to get interaction profile for 277197189284024 [ XR_ERROR_PATH_UNSUPPORTED ]
OpenXR: Failed to get interaction profile for 277197189284025 [ XR_ERROR_PATH_UNSUPPORTED ]
OpenXR: Failed to get interaction profile for 277197189284026 [ XR_ERROR_PATH_UNSUPPORTED ]
OpenXR: Failed to get interaction profile for 277197189284027 [ XR_ERROR_PATH_UNSUPPORTED ]
```

### Steps to reproduce

Create minimum OpenXR project in alpha 15
Observe

### Minimal reproduction project

[minimum vr.zip](https://github.com/godotengine/godot/files/9493111/minimum.vr.zip)

**Comment by addmix** [comment]
Looks like the same issue is present in alpha 14 too, not sure how far back it goes.

**Comment by addmix** [comment]
Opening the project in previous, known-functional alphas does not fix the problem either, and deleting cached files doesn't fix it either. Opening a new project in Alpha 15 I did manage to get this one-off error:

(There were 8 of these in the debugger)
![image](https://user-images.githubusercontent.com/38119387/188703014-eaf4e6a1-21fe-46e5-8677-ac5134e6aadf.png)

**Comment by addmix** [comment]
Issue still present in Alpha 16

**Comment by BastiaanOlij** [comment]
Sorry guys, still need to look into this. As far as I can tell the issue is the added HTC tracker entries in the action map. Either there is a bogus entry that ended up in there or the system is not reacting the way I expect it to when HTC tracker support is not installed.

A potential work around is to open up the action map (action map tab in the bottom mid section) and just remove the HTC tracker entry from the list.

**Comment by addmix** [comment]
> A potential work around is to open up the action map (action map tab in the bottom mid section) and just remove the HTC tracker entry from the list.

If this workaround does not work, another workaround is to make create your project in alpha 10, run it for the first time with OpenXR enabled, then transfer it to your desired version.

**Comment by ForestKatsch** [comment]
[Here's](https://host.zlsadesign.com/HJ9YPXS-i) an `openxr_action_map.tres` modified to remove the trackers, and I can confirm controllers work correctly with this file. (Removing the trackers from the action map in the Godot UI doesn't work - there are still some stray references in the file.)

**Comment by BastiaanOlij** [comment]
It would be good to test #67529, I think that may solve the issue.

**Comment by alcomposer** [comment]
Unfortunately @ForestKatsch's action map is still the only one that works for me. Quest 2, Arch Linux.

**Comment by BastiaanOlij** [comment]
Hmm, I just verified that with this PR it works on Rift S, I'll test with Quest 2 as well..

**Comment by BastiaanOlij** [comment]
Found one more issue, this now works correctly on Quest 2, so https://github.com/godotengine/godot/pull/67529 fixes the issue completely for me.

**Comment by Haydoggo** [comment]
This issue still applies for me in 4.0.2 stable.
Using HTC Vive Cosmos. So far the only actions that have restored controller tracking have been using the previously linked modified `openxr_action_map.tres` file, and strangely enough, switching from SteamVR to VIVE Console as my OpenXR runtime (But that seems to come with other issues).

Using Godot 4.0.2, SteamVR 1.25.7, HTC Vive Cosmos, VIVE Console 2.1.23.2, Windows 10

**Comment by Calinou** [comment]
@Haydoggo Are you sure this is not caused by https://github.com/godotengine/godot/issues/69937? If this is the case, then please open a new issue with a minimal reproduction project attached.

**Comment by Haydoggo** [comment]
I'd previously tried changing the controller poses thanks to that very issue but didn't get any different behaviour. Though after reading your comment today, I decided to double check the behaviour, and now I can't reproduce the issue at all, even with `default` poses on the controllers and the auto generated `openxr_action_map.tres`. Maybe my computer/SteamVR just needed a restart?

I'll come back to this if the issue crops up again in the future.
