### ISSUE TITLE
XML Parser does not strip outtag of CDATA

### ISSUE THREAD

**Issue by D2klaas** [godotengine/godot#65416]
### Godot version

3.5.0

### System information

Windows 10

### Issue description

When parsing a XML with a CDATA part. The CDATA content can be read via get_node_name() (wich is odd .. imho).
The CDATA outtag "]]>" is still attached at the end of the string but should not be part of the content (name).

### Steps to reproduce

execute this code on any node

```

	var xmlBuffer = "<a><![CDATA[my cdata content goes here]]></a>"
	var xml:XMLParser = XMLParser.new()
	xml.open_buffer(xmlBuffer.to_ascii())
	while true:
		if xml.read() != OK:
			return
		
		match( xml.get_node_type() ):
			1:
				print("NODE_ELEMENT: "+xml.get_node_name())
			5:
				print("NODE_CDATA: "+xml.get_node_name())

```

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/51380.

Note that XMLParser is mostly used internally by the engine (which doesn't use CDATA blocks), so it may take a while for this to be fixed.

**Comment by gotnospirit** [comment]
The problem is in `xml_parser.cpp`, the if block at line 140 overwrites the `cDataEnd` found in the previous while loop.
This change was introduced at 3f89287ddbe
If we negate the condition of this if statement, everything is ok, but it may have side-effect

**Comment by Calinou** [comment]
cc @timothyqiu
