### ISSUE TITLE
Baking octree generates a PNG file in project root (baked_octree.png)

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#6541]
**Operating system or device - Godot version:**
Debian GNU/Linux

**Issue description** (what happened, and what was expected):
Light baking generated a file baked_octree.png at the toplevel which is not removed ([responsible code](https://github.com/godotengine/godot/blob/bc6e750f957864d866bad94236212d1a87cebd2d/tools/editor/plugins/baked_light_editor_plugin.cpp#L146)). Godot can instead 1) use a tmpfile with a fixed prefix and remove the file afterwards, 2) provide a path as an option to store the octree lightmap 3) avoid storing it as a file completely.

**Steps to reproduce:**
Add a light with baking enabled under a BakeLightInstance node and press Bake button.

**Link to minimal example project** (optional but very welcome):

**Comment by Sslaxx** [comment]
Toplevel? You mean of the project, or $HOME?

**Comment by volzhs** [comment]
I think the "Toplevel" means root directory of each project.

**Comment by tagcup** [comment]
I meant project root, of course. (I believe the alternative would be / rather than $HOME, which is not writable by ordinary users anyway).

**Comment by akien-mga** [comment]
Please try to use a meaningful issue title next time :)

**Comment by tagcup** [comment]
Sure thing, sorry about that! I somehow overlooked it.

**Comment by bojidar-bg** [comment]
I assume this is now obsolete with GIProbe, right?

**Comment by volzhs** [comment]
@bogidar-bg for master yes

**Comment by tagcup** [comment]
Right, in current master, it's commented out in `editor/plugins/baked_light_editor_plugin.cpp`

**Comment by tagcup** [comment]
Closing as 2.x issues are apparently being closed now per #3610

**Comment by akien-mga** [comment]
That one would still be worth fixing IMO.

**Comment by akien-mga** [comment]
And should be easy, the file should just be written to the project-specific config folder in ~/.godot/config/<project+hash>/`.

**Comment by tagcup** [comment]
I don't think that PNG file is needed at all. It was probably there for debugging and I assume whoever introduced it forgot to remove it

**Comment by akien-mga** [comment]
Thanks, I'll just drop it then.

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.
