### ISSUE TITLE
A way to turn off the material preview in the Inspector?

### ISSUE THREAD

**Issue by Megalomaniak** [godotengine/godot#6542]
**Operating system or device - Godot version:**
Godot 2.1, any OS.

**Issue description** (what happened, and what was expected):
_This is a feature request._

I don't really like the new shader material preview in the inspector, I am already previewing my materials in the viewport and it's kind of a waste of space in the inspector, IMO.

![Illustration](http://picload.org/image/rdrrwclo/inspector_matpreview.png)

Since I couldn't find an option for it:
Would it be possible to get an option to turn it off in the Engine Settings > Inspector Tab.

:sparkles: Pretty please? :sparkles:

**Comment by Dillybob92** [comment]
I wish this would be possible for 2d textures too. I am using a large spritesheet and when clicking on the node godot will freeze for 200 to 600ms (dependent on how large the spritesheet [texture] is).  Only happens if the preview thumbnail is there.  So +1 from me for an option to disable texture/material previews

**Comment by Zylann** [comment]
That freeze looks like something that should be handled asynchronously.

**Comment by KursonSerg** [comment]
I want to help with this issue and have done some research.
The reason for freeze is synchronous resource loading in function `ResourceLoader::load()` (see call stack below)
`1   ResourceLoader::load                           resource_loader.cpp 160
2   EditorNode::load_resource                      editor_node.cpp     515
3   FileSystemDock::_file_option                   filesystem_dock.cpp 951
4   FileSystemDock::_select_file                   filesystem_dock.cpp 594`
What is the best way to deal with this problem: make loading async or just check for hidden preview before loading?
@akien-mga @Zylann

**Comment by KursonSerg** [comment]
It seems like easy fix for freeze is not possible because resource properties are not available without loading.
So as I can see
>So +1 from me for an option to disable 2d texture and material thumbnail previews

can't give expected result (absence of freeze)

**Comment by nunodonato** [comment]
is this still relevant for v3?

**Comment by quantum-entangler** [comment]
@nunodonato 
Well, unless the UI in 3.0 is radically different, yes I would expect this to be relevant still. Note that the opening post is about saving screen real-estate more than anything else. Mind you this is just a guess since as a windows user i can't test 3.0 as of right now. It doesn't really run on windows(7 x64 SP1 here, using GeForce 750m on the laptop and RX480 on the desktop) for me yet, lots of openGL related errors( #8148 ).

**Comment by kimjiy9607** [comment]
I checked the #10659 mentioned above. This is closed one and the post said "fixes #6542". So Im wondering if this is also fixed or not.

**Comment by Calinou** [comment]
@kimjiy9607 This seems to still not have been implemented as of 3.2 beta4.

**Comment by Anutrix** [comment]
I think this can be considered fixed. Clicking smaller preview hides/shows larger preview.
In 4.0:
![Capture88](https://user-images.githubusercontent.com/11459028/85919020-7c12f600-b885-11ea-8767-f2e39bc6374f.png)
On clicking smaller preview-
![Capture89](https://user-images.githubusercontent.com/11459028/85919022-7ddcb980-b885-11ea-9a32-aae06c98c386.png)

In 3.2.1:
![Capture90](https://user-images.githubusercontent.com/11459028/85919101-052a2d00-b886-11ea-8057-b79755c4c3ef.png)
On clicking smaller preview-
![Capture91](https://user-images.githubusercontent.com/11459028/85919125-2723af80-b886-11ea-8bf3-e00bd199eb0f.png)

**Comment by akien-mga** [comment]
Indeed, this was fixed in 3.1.

**Comment by Megalomaniak** [comment]
Since proposals now belong elsewhere this should have indeed been closed a while ago.

@Anutrix If collapsing the preview also hides all the parameters then it is not an acceptable solution. The whole point was to not have the preview waste screen real-estate while wanting to browse the parameters in the inspector.
