### ISSUE TITLE
Building Godot from source fails silently on Windows 8.1

### ISSUE THREAD

**Issue by dynamite-ready** [godotengine/godot#6543]
I'm currently trying to build Godot from source (master) on Windows 8.1. 
I'm using Python 2.7.12 and Scons 2.5.0.

When I run - "`C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" amd64 && scons platform=windows` - the command line prints:

```
scons: Reading SConscript files ...
You need to define ANGLE_SRC_PATH to the path of ANGLE source root.
No valid target platform selected.
The following were detected:
        windows

Please run scons again with argument: platform=<string>
scons: done reading SConscript files.
scons: Building targets ...
scons: `.' is up to date.
scons: done building targets.
```

 With no clear error, I check the /bin folder, but no "godot.windows.tools.*.exe" file is built.
What might I be doing wrong?

**Comment by akien-mga** [comment]
Double check your `platform` argument, the log you have would happen if you mistyped it (e.g. `platform=window`).

**Comment by dynamite-ready** [comment]
Ah...

In the hope of helping anyone stumbling across this issue, I installed the requirements (Python, Scons, etc) correctly, but added .bat files to the System32 folder instead of adding Python and Scons to the system PATH...

In doing that, both Scons and Python _appeared_ to work, but after I deleted the .bat files, and append the program locations to the PATH variable, the build works.

**Comment by bojidar-bg** [comment]
Closing as resolved then...
