### ISSUE TITLE
Multi-line tooltips are blacked out

### ISSUE THREAD

**Issue by Trashtalk217** [godotengine/godot#65439]
### Godot version

v4.0 (9142904c2)

### System information

Arch Linux (Intel  UHD Graphics 620) with Vulkan

### Issue description

![image](https://user-images.githubusercontent.com/24552941/188734852-14be03ef-7bd8-450c-89c6-1864af1ef854.png)

I can't read my tooltips :(.

### Steps to reproduce

1. Open any project.
2. Hover mouse over multi-line tooltip

Other info:

I get this warning.
```
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
Vulkan API 1.2.0 - Using Vulkan Device #0: Intel - Intel(R) UHD Graphics 620 (KBL GT2)
```

**Comment by Trashtalk217** [comment]
This is a regression since this problem is not happening in the latest stable 3.5 release.

**Comment by Calinou** [comment]
This was already reported by https://github.com/godotengine/godot/issues/61712 and should have been fixed by https://github.com/godotengine/godot/pull/64783. However, your build is more recent than that commit.

**Comment by Trashtalk217** [comment]
I have no explanation for this, but I pulled from upstream today and it seems to have resolved itself.
![image](https://user-images.githubusercontent.com/24552941/189449069-0fbcf834-1457-4bb6-b93a-a52d5dadddb6.png)
Feel free to close this issue.
