### ISSUE TITLE
double = in variable declaration not detected

### ISSUE THREAD

**Issue by slimelaboratory** [godotengine/godot#65436]
### Godot version

v4.0.alpha15.official [432b25d36]

### System information

Win 10, intel, vulkan, RTX 2070

### Issue description

`func declare(ex : float):
   my_var == ex`

Im high right now and was writing some stuff. Took me a while to figure out why my state machine wasnt changing states. My function, identical to the example above, did not throw any error when executing.

### Steps to reproduce

/

### Minimal reproduction project

/

**Comment by Calinou** [comment]
`my_var == ex` is a standalone expression, and is therefore valid (even if it makes no sense to do this check on its own line).

If you check the bottom-right of the script editor, you'll see a warning appearing:

![image](https://user-images.githubusercontent.com/180032/188746209-2a430bec-3b30-4575-9336-83b9a68fd38d.png)

I tested this on 4.0.alpha 432c4c40a, but 3.x has the same warning implemented.
