### ISSUE TITLE
Vulkan: GPUParticles3D instantiate gives visual artifacts 

### ISSUE THREAD

**Issue by ncollie42** [godotengine/godot#65443]
### Godot version

4.0 alpha 15

### System information

Fedora x11 NVIDIA GeForce GTX 970

### Issue description

instantiating particles occasionally leaves visual artifacts and/or effects shadows for a single frame.
![Screenshot from Screencast from 09-06-2022 01:17:45 PM webm - 1](https://user-images.githubusercontent.com/52465548/188744346-b967535f-0858-4ef5-b6d2-5c82d3ea31b2.png)

instantiating a lot of GPUParticle3D at once makes it more obvious, bellow I instantiate 20 new GPUParticle3D on the left side every .05 seconds and queue_free after 1 second. Having the same total amount of active emitters running does not give the same artifacts as instancing and freeing.  

[Screencast from 09-06-2022 02:27:49 PM.webm](https://user-images.githubusercontent.com/52465548/188743405-3d7782d3-147d-4c54-a1ab-c18fd4a15ca8.webm)

### Steps to reproduce

[GPUparticle3D.zip](https://github.com/godotengine/godot/files/9501090/GPUparticle3D.zip)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/56691 (likely due to the same cause).

**Comment by henriquelalves** [comment]
Just posting an ugly hack for this issue. Apparently this was fixed in a project I'm working in by restarting the GPUParticles (to delete all current particle geometries), and giving sufficient time between stop emitting particles and deleting the scene.

Ugly code:
```
func _kill() -> void:
	# This is a fix for the flickering problem of particles: https://github.com/godotengine/godot/issues/65443
	# We have to restart the particles and give sufficent amount of time before deleting the node,
	# so particles won't flicker on the last position they were rendered
	$Bullet/GPUParticles3D.restart()
	$Bullet/GPUParticles3D.emitting = false
	await get_tree().physics_frame
	await get_tree().physics_frame
	await get_tree().physics_frame
	
	queue_free()
```
