### ISSUE TITLE
Godot Master crashing on opening editor on latest commit (possibly Mono related)

### ISSUE THREAD

**Issue by OtherCannon** [godotengine/godot#65445]
### Godot version

v4.0.alpha.mono.custom_build.432c4c40a

### System information

Windows 10, Vulkan

### Issue description

I'm currently using a custom Godot 4 build w/ Mono support and the godot_voxel module by Zylann. Yesterday, the build was working completely fine, however, on pulling master and building again, Godot now immediately crashes when I attempt to open a project, be it a preexisting project made in my Godot build or a brand new project. Attached is a screenshot of my terminal output on attempting to open a project.
![image](https://user-images.githubusercontent.com/57022816/188749718-3e73cb2f-fa36-4f5b-bd27-790d2bd34003.png)

Additional notes: Although I don't believe that the issue is in any way related to the godot_voxel module, as it appears to be related to Mono, I can recompile without the voxel module if needed.

### Steps to reproduce

1. Build Godot from the latest commit, with module_mono_enabled=yes and float=64
2. Use the steps in modules/mono/README.md to build the glue and nuget repos with float 64 support
3. Run Godot
4. Create a new project
5. Attempt to open the project

### Minimal reproduction project

Not needed, all that's needed is a Godot build updated to the latest commit.

**Comment by Calinou** [comment]
There is no more Mono in the `master` branch – it was replaced by .NET 6.

**Comment by OtherCannon** [comment]
@Calinou Sorry, I meant .NET 6 but in the modules folder and in the scons argument it's still referred to as Mono so I thought I'd keep the naming consistent

**Comment by AlmightyLaxz** [comment]
432c4c40a is able to open .NET projects fine for me. Did you regenerate the 'mono' glue while building?
Full build should look like this:
```
scons float=64 p=linuxbsd tools=yes module_mono_enabled=yes mono_glue=no target=release_debug
.\bin\godot.linuxbsd.double.opt.tools.x86_64.mono --generate-mono-glue modules/mono/glue --headless
scons float=64 p=linuxbsd tools=yes module_mono_enabled=yes mono_glue=yes target=release_debug
.\modules\mono\build_scripts\build_assemblies.py --godot-output-dir .\bin --push-nupkgs-local C:\Pathto\MyLocalNugetSource --float=64
```

Clearing the nuget cache has helped in the past for me.
`dotnet nuget locals -c all`
Then restore inside your project folder
`dotnet restore`
Maybe `dotnet clean` to remove build outputs too

**Comment by paulloz** [comment]
> Full build should look like this

That second `scons` command is not needed any more. The `mono_glue` argument doesn't do anything.

**Comment by Jayman2000** [comment]
@AlmightyLaxz
> ```
> .\modules\mono\build_scripts\build_assemblies.py --godot-output-dir .\bin --push-nupkgs-local C:\Pathto\MyLocalNugetSource --float=64
> ```

I’m on Arch Linux and running:

```bash
./modules/mono/build_scripts/build_assemblies.py --godot-output-dir ./bin
```

fixed it for me. I think that this might just be a documentation bug. [The “Compiling with Mono” guide doesn’t mention the `build_assemblies.py` script at all.](https://docs.godotengine.org/en/latest/development/compiling/compiling_with_mono.html)

**Comment by OtherCannon** [comment]
@AlmightyLaxz Like paulloz said, the building is different and you don't need to run scons twice. Also, I'd like to add that in case it wasn't clear in my initial post, my build *was* working before, and I've changed nothing about the build script. It was only yesterday that I started getting the error when I tried to edit a project. Additionally, running the commands didn't work either, I'm still getting the same errors as before.

**Comment by OtherCannon** [comment]
I ran the build again, and I noticed that during the build_assemblies script it seems like a few projects are restored targeting .NET Framework and a warning is thrown. I don't know if that's intentional or a holdover from using mono, but here's the screenshots just in case
![image](https://user-images.githubusercontent.com/57022816/188985276-ebe8ed88-9524-423a-9a92-070f5ec23fbc.png)
![image](https://user-images.githubusercontent.com/57022816/188985406-87b4b79f-9322-4f2f-9e07-bfbfffaf26ff.png)

**Comment by paulloz** [comment]
@Jayman2000 
> I think that this might just be a documentation bug. [The “Compiling with Mono” guide doesn’t mention the `build_assemblies.py` script at all.](https://docs.godotengine.org/en/latest/development/compiling/compiling_with_mono.html)

This part of the documentation has not been re-written for 4.x yet, since everything is still WIP. That's why there's a README file in the module folder.


@OtherCannon 
> I noticed that during the build_assemblies script it seems like a few projects are restored targeting .NET Framework and a warning is thrown

AFAIK this has never been problematic.

**Comment by OtherCannon** [comment]
Just figured out the problem, turns out that I had enabled double support (which changes the name of the godot exe), but forgot to update my build .bat to use the updated path when building the glue. Sorry for the needless issue, and thanks for everyone's help!
