### ISSUE TITLE
Project setting Rendering/Node name casing not work while custom class node instantiate in scene

### ISSUE THREAD

**Issue by kaluluosi** [godotengine/godot#65454]
### Godot version

3.5 stable

### System information

Win10, Core I7-9700,RTX2080

### Issue description

![image](https://user-images.githubusercontent.com/1620585/188785973-10bbe2c3-d344-4c74-93a4-b147e91c6994.png)

![image](https://user-images.githubusercontent.com/1620585/188786024-14242603-db92-4f2e-9e62-a33126c72491.png)

![image](https://user-images.githubusercontent.com/1620585/188786035-98665ffc-6e4b-4d50-8d9a-6cb4b4ea37b0.png)
![image](https://user-images.githubusercontent.com/1620585/188786127-d268b2cf-902b-499e-9304-ffa6a80bbdf7.png)

### Steps to reproduce

see description

**Comment by ryburnj** [comment]
I've just worked on another name casing issue, keen to give this one a go!
