### ISSUE TITLE
Generated iOS launch screen images don't match the orientation project setting

### ISSUE THREAD

**Issue by michael-garofalo** [godotengine/godot#65470]
### Godot version

3.5.1 (RC 1)

### System information

macOS 12.5.1

### Issue description

![Screen Shot 2022-09-07 at 6 52 40 AM](https://user-images.githubusercontent.com/62625227/188861751-d73af48e-b4c9-4dc5-adb8-94db8e581945.png)

### Steps to reproduce

I was just testing ARKit with Godot, when I noticed that the default Godot splash screens were not matching the orientation of the device. If you look at Images.xcassets > LaunchImage in Xcode, you can see that there's a problem with the orientation of the images.

**Comment by Calinou** [comment]
These templates seem to be generated at export-time, as the default templates are just blank images: https://github.com/godotengine/godot/tree/master/misc/dist/ios_xcode/godot_ios/Images.xcassets/LaunchImage.launchimage
