### ISSUE TITLE
NavigationAgent is born navigating to (0,0,0)

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#65472]
### Godot version

3.5.stable, 4.0.dev (fffdbb38e3)

### System information

Arch Linux, GLES 3, Mesa Intel(R) UHD Graphics (CML GT2)

### Issue description

A NavigationAgent node is born navigating to `(0, 0, 0)`, and `is_navigation_finished()` returns false (if the character is far from that location).

I understand that it can be explained as the target location's default value is `(0, 0, 0)` so the agent wants to navigate to that location. But the initialization of `navigation_finished` shows that navigation is intended to be finished by default, and I think it's more convenient than the current behavior too.

https://github.com/godotengine/godot/blob/019253512d75eb5e012772921ace6c092d8f5380/scene/3d/navigation_agent_3d.h#L70

NavigationAgent is currently using an empty nav path to signal pathfinding request. So calling methods like `is_navigation_finished()` and `get_next_location()` on a fresh NavigationAgent always triggers a pathfinding towards `(0, 0, 0)`.

A proper dirty flag as metioned in https://github.com/godotengine/godot/pull/65452#issuecomment-1239032959 might help, I think.

### Steps to reproduce

Run the MRP. Or setup a simple navigation scene where all the character does is to move toward wherever the NavigationAgent tells it to go to.

### Minimal reproduction project

[DefaultTarget.zip](https://github.com/godotengine/godot/files/9506282/DefaultTarget.zip)

**Comment by smix8** [comment]
While calling `set_target_location()` before anything else is a requirement for the navigationagent use a pathfinding query with movement to the origin vector when some of the other navigationagent functions are called first should indeed be prevented with a flag.
