### ISSUE TITLE
Canvas item shader SRC_VERTEX wrong in TileMap

### ISSUE THREAD

**Issue by RandomShaper** [godotengine/godot#6547]
**Operating system or device - Godot version:**
Windows 10x x64, (almost) latest master

**Issue description** (what happened, and what was expected):
`SRC_VERTEX` for `CanvasItemShader`s is expected to be relative to it's local space, ~~but when texture region is in effect, it's offset by the position of the sub-rect in the full texture.
Is this intended behavior? Won't this also change shader output when the game is packaged with atlasing?~~, but when used for tiles in a `TileMap` it's relative to the current quadrant instead of the current individual cell.
Is this intended behavior?

I see that `TileMap` builds a `CanvasItem` for every quadrant so what the docs say about `SRC_VERTEX` is still true and probably this behavior is expected, but then what would be a workaround to get the cell-local vertex in the shader code?

**Steps to reproduce:**
N/A

**Link to minimal example project** (optional but very welcome):
Probably if I can devote some more time.

**Comment by akien-mga** [comment]
Closing for now, but feel free to reopen if you can confirm it in the current master branch.

**Comment by ghtyrant** [comment]
I have encountered this issue in Godot v3.2.3.stable.mono.official

Unless I'm missing something this makes it impossible to create continuous shaders for tile maps.
See the following image for an example:
![image](https://user-images.githubusercontent.com/51596/100765779-2a543600-33f8-11eb-87b6-c20b64011f3d.png)

This is a simple TileMap with the following shader:

```
shader_type canvas_item;

uniform mat4 globalTransform;
varying vec2 worldPos;

void vertex() {
    worldPos = (globalTransform * vec4(VERTEX, 0.0, 1.0)).xy;
}

void fragment() {
    vec4 currentColor = texture(TEXTURE, UV)
    currentColor[0] = 0.0f;
    currentColor[1] = worldPos[0] / (32.0f*32.0f);
    currentColor[2] = worldPos[1] / (18.0f*32.0f);
    COLOR = currentColor;
}
```

**Comment by Calinou** [comment]
@ghtyrant Please open a new issue with a minimal reproduction project attached.
