### ISSUE TITLE
Godot 4.0 (16) - web - ReferenceError: SharedArrayBuffer is not defined

### ISSUE THREAD

**Issue by michaldev** [godotengine/godot#65488]
### Godot version

4.0 alpha 16

### System information

MacOS, Chrome, Safari, Firefox

### Issue description

I'm testing web build in new alpha build. This works only by icon click (in right top). When I try to export game (truck town or own 2d, clean view with 1 button) I got error like this:
`index.js:9 Uncaught (in promise) ReferenceError: SharedArrayBuffer is not defined`

### Steps to reproduce

Just click export and select web, next run exported html with any server (eg. python3 -m http.server)

**Comment by Calinou** [comment]
>  next run exported html with any server (eg. python3 -m http.server)

You need to enable threads in the web server. This can't be done with an one-liner command in Python, but you can use a Python script that you run like in this PR: https://github.com/godotengine/godot/pull/64886

Closing, as this is a web server configuration we have no control over.
