### ISSUE TITLE
press enter trigger button press

### ISSUE THREAD

**Issue by abderman** [godotengine/godot#65480]
### Godot version

3.5

### System information

Windows 11. gless 3, nvidia  geforce 1650 GTX

### Issue description

after pressing button node when ENTER/SPACE pressed button node is trigered

### Steps to reproduce

create Button node and assign action to
run aplication
press button
now when ENTER/SPACE pressed Button Node is triggered

### Minimal reproduction project

[tst.zip](https://github.com/godotengine/godot/files/9507434/tst.zip)

**Comment by Calinou** [comment]
This is expected. The button receives focus, which allows the keyboard to press it. This is done for accessibility purposes :slightly_smiling_face: 

You can disable button focusing in the Button node properties in the inspector (**Focus Mode**).
