### ISSUE TITLE
Windows 10: Title bar not changing color while in dark mode

### ISSUE THREAD

**Issue by Kubulambula** [godotengine/godot#65492]
### Godot version

4.0.alpha16

### System information

Windows 10

### Issue description

When launching the Godot editor with dark mode enabled, the title bar stays white, but the other UI elements switch to dark mode (also white) so they cannot be seen properly. 

This also happens to any child window when it is created even when the main window has the black title bar.

![dark_mode](https://user-images.githubusercontent.com/72454967/188956866-8f2614d9-4968-4f04-a303-1cc0abfc8498.gif)

This effect disappears as soon as the window is unfocused or resized. Dragging it around does nothing as well as switching from project manager to the editor.

### Steps to reproduce

Launch the editor either directly or trough console

**Comment by Kubulambula** [comment]
It is also mentioned [here](https://github.com/godotengine/godot/pull/65026#issuecomment-1233694259)

**Comment by Calinou** [comment]
https://github.com/godotengine/godot/pull/65262 will resolve this. I'm afraid Windows 10 doesn't have proper dark theme title bar support

As a workaround, set your accent color to `#333333` (the darkest allowed custom color) in the Windows theme settings, and make sure the accent color is used to tint focused windows' title bar.

**Comment by naphipps** [comment]
Doing the following fixed the dark mode title bar on Windows 10 for me:
```cpp
//include <dwmapi.h> and link to dwmapi.lib

LPCSTR subkey = "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize";
LPCSTR value = "SystemUsesLightTheme";
DWORD word = 0;
DWORD size = sizeof(DWORD);
LSTATUS status = RegGetValueA(HKEY_CURRENT_USER, subkey, value, RRF_RT_DWORD, nullptr, &word, &size);
bl is_dark_mode = status == ERROR_SUCCESS && word == 0;

if (is_dark_mode)
{
	HWND native_window = (HWND)GetNativeWindow();
	BOOL value = true;
	DwmSetWindowAttribute(native_window, 20, &value, sizeof(value));

	WPARAM wparam{};
	LPARAM lparam{};
	wparam = FALSE;
	CallWindowProcA(_prev_window_procedure, native_window, WM_NCACTIVATE, wparam, lparam);
	wparam = TRUE;
	CallWindowProcA(_prev_window_procedure, native_window, WM_NCACTIVATE, wparam, lparam);
}
```
For some reason, deactivating the title bar, then activating it again works... Feel free to use the DefWindowProcA instead of CallWindowProcA. I happen to subclass my window procedure in my project.

I started on this topic over on [pull 65026](https://github.com/godotengine/godot/pull/65026) and found my way here as well.
