### ISSUE TITLE
Apk not designed for tablets - possible "Support Large" and "Support Xlarge" export option problem.

### ISSUE THREAD

**Issue by freemanfromgodotengine** [godotengine/godot#6550]
**Operating system or device - Godot version:**
Linux Xubuntu 14.04 64-bit, Godot 2.1-alpha and Godot 1.1 - both custom compile.

**Issue description** (what happened, and what was expected):
After properly uploading apk to Google Play Developer Console, Google gives me following notification
![Message from Google Play](https://cloud.githubusercontent.com/assets/11817561/18644993/bdd4cc34-7eab-11e6-82b8-4e3f6f492050.png)

My export settings about screen sizes look like this
![Godot Export Options](https://cloud.githubusercontent.com/assets/11817561/18645027/e2ce0d2a-7eab-11e6-929e-bab43f41c1f8.png)

**Steps to reproduce:**
To see the notification in Google Plays Development Console you need to choose one of your apps from your app's list and go to Statistics. 
![Google Play Statistics](https://cloud.githubusercontent.com/assets/11817561/18645485/a60bbbe2-7ead-11e6-9758-6b3a13cdec13.png)
Then in the middle of stats page, which shows "Android Version" stats by default, ![Android Version](https://cloud.githubusercontent.com/assets/11817561/18645531/d8b6f32c-7ead-11e6-84fe-d1126eafa27f.png)
you need to change it to "Tablets", and in the lover part of the page you should be able to  see something like this

![Stats with the Tablet notofication](https://cloud.githubusercontent.com/assets/11817561/18645564/f97d54e8-7ead-11e6-9860-a0a5119db631.png)

**Comment by Shin-NiL** [comment]
My app published using 2.1-stable (custom build) doesn't have this issue.

**Comment by lukaskotik** [comment]
It seems as https://github.com/godotengine/godot/issues/4144 that has been fixed in 2.1 stable.
