### ISSUE TITLE
Godot 4: Animation tracks from earlier alpha versions are empty

### ISSUE THREAD

**Issue by macryc** [godotengine/godot#65502]
### Godot version

4.0 alpha 14-16

### System information

Win10, GLES3, RTX 2070 mobile

### Issue description

All key frames in animation tracks created prior to alpha 14 are empty. The animations are still listed under the AnimationPlayer node, and they each have the animation tracks but all keyframes are gone.

### Steps to reproduce

Open alpha 12 and create a Animation player node
Add an animation and set a few keyframes
Save project
Open project in alpha 16 (or 15)
Open the animation player to view the animations
Select the animation you created in alpha 12, open it - the track is there but there are no keyframes

### Minimal reproduction project

not needed

**Comment by TokageItLab** [comment]
What type of track, all of type?

**Comment by akien-mga** [comment]
Seems to be the same issue as #66964. We can't guarantee an easy upgrade path between alphas, but we aim to have it working from 3 to 4.
