### ISSUE TITLE
Lambert Wrap is brighter then Lambert

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#65515]
### Godot version

4.0 Alpha 16

### System information

Windows 11, Vulkan, Nvidia GTX 1050 Ti, 512.15

### Issue description

Lambert Wrap shader seems to be resulting in much brighter light compared to Lambert.

After a quick search I've found https://www.youtube.com/watch?v=fREhhAyyStk and at 9:35 shows the expected result in a custom shader implementing it. The video further explains what is wrong with Lambert Wrap in Godot's implementation, and should be helpful to anyone fixing the shader.

### Steps to reproduce

Shine a Light on an Object with Lambert Wrap Shader, and compare the brightness with Lambert.
With Roughness 0, Lambert Wrap should look identical to Lambert at the same settings, it does not.

**Comment by Calinou** [comment]
Can you reproduce this on 3.5?

**Comment by mrjustaguy** [comment]
I can reproduce in 3.5. Here's 3.5 Reproduction Project
[Shader.zip](https://github.com/godotengine/godot/files/9528948/Shader.zip)

The issue is in https://github.com/godotengine/godot/blob/master/servers/rendering/renderer_rd/shaders/scene_forward_lights_inc.glsl although I'm not sure where you'd have to divide by PI to get the right result without breaking other shader modes.
