### ISSUE TITLE
SubViewports are not rendered in expected order

### ISSUE THREAD

**Issue by ZuBsPaCe** [godotengine/godot#65545]
### Godot version

4.0 dev (5803a1d)

### System information

Windows 10, Vulkan Mobile

### Issue description

In my projects, I use multiple SubViewports to render soft shadow maps which I combine in another SubViewport. I then render the result either as a fullscreen sprite or in a shader

This worked nicely until recently:

![CustomShadowMapping](https://user-images.githubusercontent.com/4233942/189221146-5b45ce74-9e83-43a9-aa59-69b0c950003a.gif)

As you can see, there is a slight delay of the final shadow map when the light moves.

A bisect led me to this pull request, which introduced this delay: https://github.com/godotengine/godot/pull/63091

I made a small repro attached below, where a green circle and a red dot move along with the mouse position. The red dot should always stay in the center of the green circle. You can switch between 2 modes:

![SubViewportDelayMode1](https://user-images.githubusercontent.com/4233942/189223181-4eacbe4b-1b4f-4333-a8f3-9a3990bfb19f.png)

![SubViewportDelayMode1](https://user-images.githubusercontent.com/4233942/189223202-fcf919b2-c9de-40b9-a0af-eadbfce90986.gif)

This works correctly. SubViewport1 is rendered first. The transparent ViewportTexture is used in a Sprite.

![SubViewportDelayMode2](https://user-images.githubusercontent.com/4233942/189223642-63fa96cf-8b54-4f61-a8b0-946feefd9bc8.png)

![SubViewportDelayMode2](https://user-images.githubusercontent.com/4233942/189223654-088a145b-a8b3-4b4e-8bcd-45016aa803b2.gif)

This does not work correctly. SubViewport1 should be rendered first, then SubViewport2. But Godot renders SubViewport2 first. That's why the red dot lags one frame behind.

Reason: The pull request https://github.com/godotengine/godot/pull/63091 fixed the render order of nested SubViewports. But it does not consider, that siblings should be rendered top to bottom. See _sort_active_viewports() in renderer_viewport.cpp. Unfortunately I have no idea how to retrieve the order there...

### Steps to reproduce

Switch between both modes in the Repro Project by pressing the button on the top and move the mouse.

### Minimal reproduction project

[SubViewportDelay.zip](https://github.com/godotengine/godot/files/9530569/SubViewportDelay.zip)

**Comment by Rindbee** [comment]
In most cases, windows are sorted in activation order rather than the order in the tree. So, the order in the tree does not matter, there is also no record of the order of siblings in `RendererViewport`.

For cases like `SubViewport` activated by default (visible), it is sorted in the order of entering tree. So a workaround is to adjust the order of `SubViewport` in the tree.

**Comment by ZuBsPaCe** [comment]
Thanks for your input @Rindbee.

Thanks for your input. There are actually 2 workarounds:

1) I can put the SubViewport, which needs to render first, below the other SubViewport. But this gets awkward if many SubViewports are involved.

2) You suggestion works, but first I did not understand, why I need to do it in this order:

```gdscript
# Deactivate viewports first
RenderingServer.viewport_set_active($SubViewport1.get_viewport_rid(), false)
RenderingServer.viewport_set_active($SubViewport2.get_viewport_rid(), false)

# Activate viewports again
RenderingServer.viewport_set_active($SubViewport2.get_viewport_rid(), true)
RenderingServer.viewport_set_active($SubViewport1.get_viewport_rid(), true)
```

For some reason I needed to first activate the viewport which should render last...

I looked at RendererViewport::_sort_active_viewports() more closely and found the problem:

```c++
while (!nodes.is_empty()) {
  Viewport *node = nodes[0];
  nodes.pop_front();

  result.insert(0, node);

  for (Viewport *child : active_viewports) {
    if (child->parent != node->self) {
      continue;
    }

    if (!nodes.find(child)) {
      nodes.push_back(child);
    }
  }
}
```
The code did push_back the siblings into the nodes list. Then it pops the first one but inserts it into result at the beginning. This reverses the order of the siblings. I fixed this behavior in the following pull request.

**Comment by TheYellowArchitect** [comment]
This is kinda off-topic to the problem, but more related to your implementation @ZuBsPaCe  , as you wrote in the OP alongside the gif. I am curious as I plan to implement that "dynamic light" feature myself with a topdown camera. I thought the classic way for this is https://docs.godotengine.org/en/stable/tutorials/2d/2d_lights_and_shadows.html but you have made me think twice now.

Why do you use 2 viewports for this mechanic/feature? Isn't that more expensive to render than the link above? Or is it even cheaper? Could you detail on pros/cons, or why you chose this approach?

**Comment by ZuBsPaCe** [comment]
@TheYellowArchitect 

I'm implementing custom Soft Shadows based on an algorithm which is explained here: https://slembcke.github.io/SuperFastSoftShadows

Therefore I completely bypass the shadows and lights which Godot provides. Basically, I provide a shader with occluder meshes and the shader extrudes all meshes from the position of a light source. I need to do this for each light, basically rendering the same scene multiple times. That's why I need multiple SubViewports.

In a second step I combine all those SubViewports in another  SubViewport, which combines all light colors and shadows into a single texture which I can finally use to render the real scene.

Why am I doing this? 

1) I don't like the soft shadows Godot provide. They simply do not look accurate enough for my taste.

2) I like the challenge... :)

If you're interested. you can take a look at the v4 branch of my Godot Starter Template and open the scenes in the FlatLighting Folder: https://github.com/ZuBsPaCe/godot-base-code

My advice: Stick to Godot Soft shadows if you want to create a game the fast way. It's a lot simpler and more reliable. Only try to do shadows yourself, if you're interested how they work, but beware: It's not easy and takes a lot if time.

**Comment by TheYellowArchitect** [comment]
Thank you for posting your method in detail, it was fascinating to read (e.g. using Godot but not its lighting system), and you have made me curious if it will be more performant than Godot's native soft shadows. For the game I will make, it needs hard shadows, so I cannot even consider soft shadows. Add the fact that I am a newbie with Godot (haven't even done the tutorial I linked) and newbie with shaders as well. So, your suggestion at the end, to stick to godot soft shadows does applies to me, even if I had to use soft shadows hahaha

Regardless, I have bookmarked that link you provided, as I lack the skills to make use of it now, but maybe in a year or so it will be useful. I wish you success in your project, it does sound hard (pun lightly intended ;)

**Comment by rpahut** [comment]
So, the order was supposed to be made "topological" child to parent, but was flipped by mistake? Shouldn't this have resulted in the rendering order SubViewport1,SubViewport2 , contrary to what is initially reported?

It bothers me that the fix claims that *now* the order is top-to-bottom, whereas fixing should have get it to the originally intended topological bottom-to-top. It is hard to make sense of.

Then still, if it really is top to bottom now, this is kind of arbitrary. Topological bottom-to-top seem to be the convention for the Godot; expecting the tree to function as a flat ordered list for the portals specifically would be odd.
