### ISSUE TITLE
Viewport draws over editor when zoomed

### ISSUE THREAD

**Issue by Hinsbart** [godotengine/godot#6555]
**Operating system or device - Godot version:**
current master
**Issue description** (what happened, and what was expected):
I think this gif speaks for itself:
![viewport_bug](https://cloud.githubusercontent.com/assets/8281916/18650808/7fae7074-7ec7-11e6-9e1d-4fb635b0a66a.gif)

**Steps to reproduce:**
Open the splitscreen platformer demo and zoom in on the main scene.

**Comment by vnen** [comment]
Seems the same as #6172,

**Comment by Hinsbart** [comment]
Oh, yes it does.
Closing as duplicate then.
