### ISSUE TITLE
Mesh `save_to_file` in scene import does not work if physics is enabled on the node

### ISSUE THREAD

**Issue by jtnicholl** [godotengine/godot#65553]
### Godot version

v4.0.alpha.custom_build [95c35417c]

### System information

Linux (Fedora 36)

### Issue description

The option to save meshes to their own files when importing a scene does not have any effect if generate physics is enabled on the node which has that mesh.

### Steps to reproduce

1. Open the advanced scene importer
2. Enable generate physics on a MeshInstance3D in the scene
3. On that mesh associated with that node, enable save to file and choose a path
4. Hit reimport. Notice the mesh isn't saved to a file. Disabling generate physics and reimporting makes it appear.

### Minimal reproduction project

[SaveMesh.zip](https://github.com/godotengine/godot/files/9531618/SaveMesh.zip)

**Comment by clayjohn** [comment]
This has the same cause as https://github.com/godotengine/godot/issues/64746 Accordingly I'll close this in favour of #64746
