### ISSUE TITLE
Godot 4: External editor not opened from errors in debugger

### ISSUE THREAD

**Issue by yedpodtrzitko** [godotengine/godot#65554]
### Godot version

v4.0.alpha16.official [86dd3f312]

### System information

MacOS 12.15.1, MacBook Air (M1, 2020)

### Current Behaviour
- when Godot is [configured to use external editor](https://docs.godotengine.org/en/latest/tutorials/editor/external_editor.html), clicking on errors in Debugger -> Stack Frames (see example screenshot below) wont open the editor.

### Expected Behaviour
- clicking on the error opens external editor on relevant file/line

![Screen Shot 2022-09-09 at 10 21 37](https://user-images.githubusercontent.com/162526/189253359-fede64d3-f7c1-44db-82ba-06ee2d3e0451.jpg)

### Steps to reproduce

- enable external editor as described in https://docs.godotengine.org/en/latest/tutorials/editor/external_editor.html
    - in my tested case it's VSCode configured as described in https://github.com/godotengine/godot-vscode-plugin#godot
    - exec path: `/Applications/Visual Studio Code.app/Contents/MacOS/Electron`
    - exec flags: `{project} --goto {file}:{line}:{col}`

- attach Godot script to a node with error in it, eg: ```func _ready(): foo```
- run scene with given script
- click on the error in Debugger -> Stack Frames when it occurs

### Minimal reproduction project

[errorscript.zip](https://github.com/godotengine/godot/files/9531672/errorscript.zip)

**Comment by yedpodtrzitko** [comment]
I discovered there's a variable `DEBUG_WITH_EXTERNAL_EDITOR` in the source code. That lead me to searching further and I eventually discovered there's an option in the builtin editor's menu "Debug -> Debug with External Editor" and it's [documented here](https://docs.godotengine.org/en/stable/tutorials/scripting/debug/overview_of_debugging_tools.html#script-editor-debug-tools-and-options). 

So it works as intended, but the discoverability could be improved. I can imagine having the checkbox " Debug with External Editor" in the same menu where the checkbox "Use External Editor" is (ie. Editor Settings -> Text Editor -> External Editor).

**Comment by zaftnotameni** [comment]
this exact same problem is still happening in godot 4.3-beta6 and the option mentioned here to "use external editor when debugging" seems to be gone

**Comment by realh** [comment]
> this exact same problem is still happening in godot 4.3-beta6 and the option mentioned here to "use external editor when debugging" seems to be gone

You may be looking in the wrong place, especially if you're using MacOS. The main menu has a Debug sub-menu, which doesn't contain the "Debug with external editor" setting. But if you select the Script tab, that has its own menu bar, where you can find the option as described.

**Comment by Morokiane** [comment]
Why is this debug option not in the External editor settings? What an obscure place for this option.
