### ISSUE TITLE
Various height and line separation issues with `RichTextLabel`

### ISSUE THREAD

**Issue by markdibarry** [godotengine/godot#65551]
### Godot version

4.0.dev (d2a6a187f4)

### System information

Windows 10

### Issue description

1. A noticeable amount of padding has been added to the top of every RTL. Overriding the line separation does not affect this:
![image](https://user-images.githubusercontent.com/21325943/189246894-29eb091a-9750-44b4-8453-a9ab4247f273.png)
![image](https://user-images.githubusercontent.com/21325943/189246932-2ba9b804-3a39-4d84-b904-81a56e332e4c.png)

2. Previously, certain methods like `line_count()` provided outdated data until the next process. The data now remains incorrect until physics_process. Not sure if this was an intentional change, but worth noting.

3. Loading and focusing RTL nodes in the editor is now much slower and causes the editor to freeze for a second or two sometimes.

4.  `fit_content_height` gets the wrong height, and seems to ignore theme overrides like `line_separation` and `outline_size` (though I believe it may have ignored outline prior to this).
![image](https://user-images.githubusercontent.com/21325943/189247518-466792fa-f95d-4ed1-91ac-9dce1c3def95.png)

Hard to say which commit caused this, but it seems it was within the last week.

### Steps to reproduce

Load up MRP, and mess with settings referenced above.

### Minimal reproduction project

[RTLBug.zip](https://github.com/godotengine/godot/files/9531355/RTLBug.zip)

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by bruvzg** [comment]
> A noticeable amount of padding has been added to the top of every RTL. Overriding the line separation does not affect this

It is determined by the font ascender. Why would line separation affect it?

> Previously, certain methods like line_count() provided outdated data until the next process. The data now remains incorrect until physics_process. Not sure if this was an intentional change, but worth noting.

In 3.x you should not expect it to return the correct value until the next frame is drawn. In 4.0 it depends on multithreaded mode, it's ether after drawing next frame or after receiving `finished` signal.

_Note: RTL draw should actually happen, if it's invisible it won't be updated._

> Loading and focusing RTL nodes in the editor is now much slower and causes the editor to freeze for a second or two sometimes.

Can't reproduce.

> fit_content_height gets the wrong height, and seems to ignore theme overrides like line_separation and outline_size (though I believe it may have ignored outline prior to this).

Seems like a bug, I guess, line separation should not be applied to the last line if it's negative. The same issue is present in 3.x.

I'm not sure if we should do anything with the outlines, it's applied only when drawing and not changing any of the text metrics. Taking it into account would overcomplicate text drawing quite a bit.

**Comment by markdibarry** [comment]
@bruvzg 

> It is determined by the font ascender.

You're right. I'm not sure why I thought otherwise. I usually test the master branch with a custom pageable text display node. Some of the changes to when text is finished processing over the last few commits caused it to behave unpredictably, and this probably was less noticeable before, but compounded with these changes made it seem out of place. I can just use negative positioning on the RTL to fix it.

> In 4.0 it depends on multithreaded mode

This is interesting. Normally, menus and dialog shouldn't display until text has been processed for displaying, but `Control` nodes can be tricky in the first place since their positioning/size isn't guaranteed to be finished/correct in the `_ready()` method. I'll spend some more time with this.

> Can't reproduce.

I'll try to make a MRP.

> Seems like a bug, I guess, line separation should not be applied to the last line if it's negative.

This was fixed in earlier master builds, but seems re-introduced. However, that bug was based on the `get_content_height()`, `get_line_offset()`, and `get_paragraph_offset()` ignoring extra or negative line separation applied with themes or overrides. This seems to be the same issue, but I'll double check.

> I'm not sure if we should do anything with the outlines,

You're probably right. It's a nice to have, since margin and line separation needs manually applied based on the outline size, but that can be applied via custom user methods.

**Comment by markdibarry** [comment]
Ah, I found the issue. I just hadn't updated things since the Font Variation introduction, so all of the top/bottom spacing was off. Closing due to user error.
