### ISSUE TITLE
Crash when opening invalid XML scene

### ISSUE THREAD

**Issue by andynosoft** [godotengine/godot#6556]
**Operating system or device - Godot version:**
Windows 10 . Godot Version 2.1 stable

**Issue description** (what happened, and what was expected):
I was trying to open a .tscn file. By mistake, I hit an XML file. Godot crashes. 

This looks silly, but somebody could lost unsaved work if it happens.

**Steps to reproduce:**
Open a project which has XML file. Go to Open Scene, and select that wrong XML File.

**Link to minimal example project** (optional but very welcome):

Open godot demos. Open 3d In 2D example. Click on Scene -> Open Scene. Select player.xml.
Godot crashes.

![zxc](https://cloud.githubusercontent.com/assets/15801379/18655831/699d5a70-7ec2-11e6-96d9-3eb805f3c449.png)

**Comment by akien-mga** [comment]
There is no XML file in the 3D in 2D demo:
```
$ find .
.
./player.scn
./player_2d.scn
./engine.cfg
./robot_demo.png
./icon.png
./main.scn
./player_3d.scn
```
Are you using demos from Godot 1.1 or earlier?

**Comment by germanandino** [comment]
That's weird. I can't find that XML file on the latest 2.1 demos. I'll check it again when I get home.

**Comment by germanandino** [comment]
It looks like I had an old XML file. 

[player.zip](https://github.com/godotengine/godot/files/491483/player.zip)

**Comment by akien-mga** [comment]
For the reference, for whom wants to fix this issue:
- Download the above zip archive
- Check that opening that XML file still triggers the bug
- Run the editor through a debugger and open the XML file
- Find where it crashes, prevent it and raise an error instead (no need to try to fix loading that XML, it's a corner case)

**Comment by Zireael07** [comment]
I thought XML is no longer a valid scene format, therefore it simply won't attempt to open it?

**Comment by akien-mga** [comment]
Hm that's a good point. And it seems to be a corner case (no other users affected), so probably not worth keeping around for the 2.1 branch.
