### ISSUE TITLE
Softbody3D disappears randomly

### ISSUE THREAD

**Issue by Mikeysax** [godotengine/godot#65570]
### Godot version

4.0-alpha16

### System information

PopOS 22.04, 5.19.0-76051900-generic kernel, Ryzen 6800h, Radeon 6700m, amdgpu, Vulkan

### Issue description

I have a SoftBody3D node with a flat mesh with culling disabled and it keeps disappearing. You can still see the shadow sometimes but the shadow also disappears sometimes as well.

[godo4alpha16softbodybug.webm](https://user-images.githubusercontent.com/15805689/189348733-b4adf98f-f154-448f-8e23-ca9e050b9c0c.webm)

### Steps to reproduce

- BoneAttachment to neck of skeleton
- SoftBody3D as child to bone attachment 
![Screenshot from 2022-09-09 08-25-50](https://user-images.githubusercontent.com/15805689/189349465-00b41e8e-b9d1-46cd-acc1-41e527d942cd.png)
- Culling mode disabled
![Screenshot from 2022-09-09 08-24-23](https://user-images.githubusercontent.com/15805689/189349391-30d61976-8367-4b44-bcd5-18f0e56f7a47.png)
- Camera values set at runtime:
![Screenshot from 2022-09-09 08-30-00](https://user-images.githubusercontent.com/15805689/189350223-71bef10b-c2db-4468-bdab-99bdbfb79b3e.png)
- Camera values set on node:
![Screenshot from 2022-09-09 08-30-52](https://user-images.githubusercontent.com/15805689/189350355-e6e12d8a-947a-4f78-8d8f-2ad1dc9bc171.png)
- Other shader values on cape:

![Screenshot from 2022-09-09 08-33-18](https://user-images.githubusercontent.com/15805689/189350801-72d0f81d-89b2-458e-81a2-118a865370b8.png)

**Comment by Calinou** [comment]
@Mikeysax Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

Also, try setting **Extra Cull Margin** on the MeshInstance3D to a very high value like 10000.

**Comment by Mikeysax** [comment]
> @Mikeysax Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.
> 
> Also, try setting **Extra Cull Margin** on the MeshInstance3D to a very high value like 10000. This will rule out whether frustum culling is the issue.

Yes, this seems to have resolved it. I set Extra Cull Margin to 1000+ and it no longer disappears. Is this the solution or is there a bigger issue?
