### ISSUE TITLE
GLTF Importer - Unwanted removal of '.' from Blender object names upon importing in Godot

### ISSUE THREAD

**Issue by JoanPotatoes2021** [godotengine/godot#65593]
### Godot version

v4.0.alpha16.official [86dd3f312]

### System information

Windows 10

### Issue description

The gltf file open in a notepad

![AutomaticUnwantedRename02](https://user-images.githubusercontent.com/88800565/189460165-ea298443-a69a-46bf-995d-3baacedd1f3c.jpg)

Gltf file open in godot

![AutomaticUnwantedRename01](https://user-images.githubusercontent.com/88800565/189460169-0bb3c8a4-f106-48d9-b2d4-e16ddbff83c9.jpg)

The `.` get's removed from names, mixing the duplicate number with the actual name of the object, this makes it fairly hard to get the preffix of the object name, this turns to be a small inconvenience to anyone exporting from blender that needs the name to be the same as their source.

I was working on a system to import a series of mesh_instances to become multi_meshes, using `EditorScenePostImport` scripts, the idea is to assign it to bigger maps and automatically handles duplicated objects as multi_meshes.

The workaround is to use another symbol `'#'` instead, but names should stay consistent,

### Steps to reproduce

Import any duplicated object from Blender which has `.001`, the `'.'` get's removed and the result object name is changed, it should stay the same as from the Blender export, names can be useful to automate a lot of stuff, an example would be this: https://docs.godotengine.org/en/stable/classes/class_editorscenepostimport.html the name of the imported objects can change how it's imported into the engine, just like `-colonly` works for collision imports from meshes.

**Comment by gotnospirit** [comment]
Node names with a "." are invalid:

https://github.com/godotengine/godot/blob/27e132347324318567419ac5039d51338d7d4f0e/core/string/ustring.cpp#L4486-L4496

I guess your best option is to use another symbol

**Comment by jtnicholl** [comment]
Blender has a bulk rename tool (shortcut is Ctrl+F2) you can use to quickly change all the periods to something else. I would recommend an underscore, a number sign is how you start a comment in GDScript so you won't be able to get the node using the $ notation (assuming such a name is valid at all, not sure).

**Comment by JoanPotatoes2021** [comment]
Aha, there it was, I searched a bit, but mostly on the importer code, and yea, I never tested trying to rename a node with `'.'` to see what happens, I would guess that's because `../` can be used as `get_parent()`,

![AutomaticUnwantedRename03](https://user-images.githubusercontent.com/88800565/189486696-a026e653-8abf-418d-a6ed-dc792ab038dc.jpg)

While the easiest solution is another symbol, the safest way would be to add some word suffix before the numbering, mostly because symbols can change in the future, and you can't bulk rename your gltf data easily, so something like `_x_` or `__` as a workaround should be safer,

jtnicholl - Now for Blender a custom script should work easier than the rename tool, because you have account for duplicated names with your custom suffix before it, because if you ever rename one, duplicate it, then rename back again, all other copies are broken, it's a workflow issue, I have some ideas to deal with that,

So this is an issue more people will encounter if they work with duplicated data from Blender not just object names, but it isn't going to change anytime soon due to how Godot works, so closing as not planned 🌜
