### ISSUE TITLE
Identical sub-expressions to the left and to the right of the '!=' operator: joints_0.size() != joints_0.size()

### ISSUE THREAD

**Issue by fire** [godotengine/godot#65602]
### Godot version

8899f1eec213620c421ba16c07cf1b3681c5a25d

### System information

Windows 11, GLES3, RTX 3000

### Issue description

https://github.com/godotengine/godot/blob/8899f1eec213620c421ba16c07cf1b3681c5a25d/modules/gltf/gltf_document.cpp#L2676

> V501 There are identical sub-expressions to the left and to the right of the '!=' operator: joints_0.size() != joints_0.size() gltf_document.cpp 2676

Found by pvs studio.

### Steps to reproduce

Code review by pvsstudio.

### Minimal reproduction project

This is found by static analysis.

**Comment by fire** [comment]
Condition should be  `ERR_FAIL_COND_V(joints_0.size() != joints_1.size(), ERR_INVALID_DATA);`

**Comment by Sarfraz-droid** [comment]
Hi, Can i fix this issue?
