### ISSUE TITLE
Recurring check. The 'if (err)' condition was already verified in line 149. gdscript_cache.cpp 150

### ISSUE THREAD

**Issue by fire** [godotengine/godot#65603]
### Godot version

8899f1eec213620c421ba16c07cf1b3681c5a25d

### System information

Windows 11, GLES3, RTX 3000

### Issue description

https://github.com/godotengine/godot/blob/bc419e1c5ee3a0cd8c4156b2e65d94f6f46c7543/modules/gdscript/gdscript_cache.cpp#L149-L151

> V571 Recurring check. The 'if (err)' condition was already verified in line 149. gdscript_cache.cpp 150

Use ERR_FAIL_COND_V(err, "");  without the if (err) check.

### Steps to reproduce

Static analyis by pvsstudio and using the capture execution mode.

### Minimal reproduction project

Use godot engine.

**Comment by voylin** [comment]
Made a pull request to change these lines.
