### ISSUE TITLE
The if statement is equivalent to the 'else' statement. scene/resources/text_line.cpp 281

### ISSUE THREAD

**Issue by fire** [godotengine/godot#65606]
### Godot version

8899f1eec213620c421ba16c07cf1b3681c5a25d

### System information

Windows 11, GLES3, RTX 3000

### Issue description

https://github.com/godotengine/godot/blob/8899f1eec213620c421ba16c07cf1b3681c5a25d/scene/resources/text_line.cpp#L277-L284

Both clauses of the if and else are the same.

V523 The 'then' statement is equivalent to the 'else' statement. text_line.cpp 281

### Steps to reproduce

Static analyis by pvsstudio and using the capture execution mode.

`scons target=release_debug vsproj=yes bits=64 compiledb=yes warning=no test=yes deprecated=no platform=windows bits=64 custom_modules=../godot-modules-groups`

### Minimal reproduction project

Use godot engine project.

**Comment by bruvzg** [comment]
Probably a leftover of extra spacing being part of TextLine.
