### ISSUE TITLE
Deleting AnimationTree node with Delete key doesn't delete, shows error.

### ISSUE THREAD

**Issue by MarioMey** [godotengine/godot#65615]
### Godot version

3.5 stable

### System information

Debian 11, AMD Ryzen™ 5 3400G with Radeon™ RX Vega 11 Graphics

### Issue description

When pressing Delete key in a AnimationNodeBlendTree node, it stays in the grid (it isn't deleted) and Godot shows this error:

    • core/object.cpp:1242 - Error calling method from signal 'delete_nodes_request': 'AnimationNodeBlendTreeEditor::_delete_nodes_request': Method expected 0 arguments, but called with 1..

In Godot 4.0 Alpha 12, node is correctly deleted.

### Steps to reproduce

- Create AnimationPlayer node
- Create AnimationTree node
- In AnimationTree Inspector, create a AnimationNodeBlendTree
- Link AnimationTree with AnimationPlayer
- Go to AnimationTree
- Create any node (e.g Animation)
- Click on node
- Press Delete key.
- Look at Output messages.

**Comment by kleonc** [comment]
Changes done in #61112 to `AnimationNodeBlendTreeEditor` were not backported in #61145. Adding the missing part to 3.x should solve this issue.

**Comment by akien-mga** [comment]
Fixed by #69384.
