### ISSUE TITLE
[C#] Building a multi-project solution fails on Linux

### ISSUE THREAD

**Issue by Maclay74** [godotengine/godot#65612]
### Godot version

3.5 with Mono

### System information

Ubuntu-latest

### Issue description

I need to add an additional project to my solution. 
It works fine on Windows, builds and runs fine.

When I try to use CI and build it on Linux, it fails. When I remove second project, it builds fine again.

One project log: 
```
/home/runner/.local/share/godot/godot_executable/Godot_v3.5-stable_mono_linux_headless_64/godot /home/runner/work/tiny-screen/tiny-screen/TinyScreen/project.godot --export WindowsDesktop /home/runner/.local/share/godot/builds/WindowsDesktop/Tiny-Screen.exe
  Godot Engine v3.5.stable.mono.official.991bb6ac7 - https://godotengine.org/
   
  Mono: Log file is: '/home/runner/.local/share/godot/mono/mono_logs/2022-09-10_10.15.14_3714.log'
  reimport: begin: (Re)Importing Assets steps: 1
  	reimport: step 0: icon.png
  mono_project_debug_build: begin: Building project solution... steps: 1
  	mono_project_debug_build: step 0: Building project solution
  mono_project_debug_build: end
```

Two projects log:
```
/home/runner/.local/share/godot/godot_executable/Godot_v3.5-stable_mono_linux_headless_[64](https://github.com/Maclay74/tiny-screen/runs/8283937635?check_suite_focus=true#step:5:68)/godot /home/runner/work/tiny-screen/tiny-screen/TinyScreen/project.godot --export WindowsDesktop /home/runner/.local/share/godot/builds/WindowsDesktop/Tiny-Screen.exe
  ERROR: Failed to export project: Failed to build project
     at: godot_icall_GD_pusherror (modules/mono/glue/gd_glue.cpp:249)
  System.Exception: Failed to build project
    at GodotTools.Export.ExportPlugin._ExportBeginImpl (System.String[] features, System.Boolean isDebug, System.String path, System.Int32 flags) [0x0007e] in <bed92dbb5b1347a8b0257804b875f39f>:0 
    at GodotTools.Export.ExportPlugin._ExportBegin (System.String[] features, System.Boolean isDebug, System.String path, System.Int32 flags) [0x0000b] in <bed92dbb5b1347a8b0257804b875f39f>:0 
  Godot Engine v3.5.stable.mono.official.991bb6ac7 - https://godotengine.org
   
  Mono: Log file is: '/home/runner/.local/share/godot/mono/mono_logs/2022-09-10_10.22.27_3[67](https://github.com/Maclay74/tiny-screen/runs/8283937635?check_suite_focus=true#step:5:71)9.log'
  reimport: begin: (Re)Importing Assets steps: 1
  	reimport: step 0: icon.png
  mono_project_debug_build: begin: Building project solution... steps: 1
  	mono_project_debug_build: step 0: Building project solution
  mono_project_debug_build: end
```

### Steps to reproduce

1. Create a new project
2. Add C# solution to it
3. Open solution in any IDE and add a new project (For instance, c# library for .net framework)
4. Make sure it builds on Windows
5. Try to build it on Linux

### Minimal reproduction project

https://github.com/Maclay74/test-godot-linux

[multi-project-solution.zip](https://github.com/godotengine/godot/files/9540211/multi-project-solution.zip)

**Comment by raulsntos** [comment]
Your MRP is missing the `ClassLibrary1` project but, when I create it, it builds fine for me so I can't reproduce.
I cloned https://github.com/Maclay74/tiny-screen and tried to build it. The `MSBuild (Mono)` Build Tool works but `dotnet CLI` fails with this error:

```
/usr/lib/dotnet/dotnet6-6.0.108/sdk/6.0.108/Microsoft.Common.CurrentVersion.targets(1217,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.7.2 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/media/raulsntos/Data/GodotProjects/TESTS/tiny-screen/plugins/SteamLibrarySource/SteamLibrarySource.csproj]
```

This is because the `SteamLibrarySource` project is using an old-style csproj instead of the new SDK-style. Old-style csproj files are not supported by dotnet CLI (see https://github.com/dotnet/sdk/issues/8931#issuecomment-350167706).

My recommendation is to upgrade to the new SDK-style project if you can; otherwise, change the Build Tool to `MSBuild (Mono)` in Linux but be aware that it tends to cause issues which is why we recommend `dotnet CLI` and default to it instead.

---

This issue only applies to 3.x because in 4.0 we are removing support for the `MSBuild (Mono)` Build Tool since we are moving to .NET 6.0.

**Comment by Maclay74** [comment]
Wow, that's... impressive! 
Sorry for the wrong archive and thanks a lot for your pro-active action with my actual project.
I converted my project and now it builds fine! Thanks a lot for your help.
