### ISSUE TITLE
CXX command line option is ignored when using MinGW

### ISSUE THREAD

**Issue by mattiascibien** [godotengine/godot#6561]
**Operating system or device - Godot version:**
Windows 10 x64. Latest goto master

**Issue description** (what happened, and what was expected):
When using `scons platform=windows CXX=<custom-compiler>` and MinGW is autodetected the compilation still starts using gcc and not the custom compiler provided. I expected to invoke the build using the custom compiler provided. When using the Visual Studio Command Prompt it is running fine.

I am trying with clang as CXX but I am not sure if this is a problem with scons itself.

**Steps to reproduce:**
See above

**Link to minimal example project** (optional but very welcome):
N/A

**Comment by SuperUserNameMan** [comment]
have you give a look at [platform/windows/detect.py](https://github.com/godotengine/godot/blob/7a27d5d9e7db4a52b1c9dcac474f6478d3c17efa/platform/windows/detect.py) ?

It is pretty hacked to work with MSVC and Mingw only.

When MinGW is detected, this script set ``env['CXX'] = mingw_prefix+"g++"``. ( [line 357](https://github.com/godotengine/godot/blob/7a27d5d9e7db4a52b1c9dcac474f6478d3c17efa/platform/windows/detect.py#L357) )

I don't know what is the default value of CXX before this line, but maybe it could be tested somewhere around this line, and into ``can_build()``.

**Comment by SuperUserNameMan** [comment]
also, if you decide to update this script and publish a PR, please take into account this pending PR which adds support to standalone MSVC compilers.
https://github.com/godotengine/godot/pull/6501

**Comment by mattiascibien** [comment]
@SuperUserNameMan thanks for the help. I will have a look onto it.

**Comment by akien-mga** [comment]
This is likely still the case nowadays, but I don't think it will be fixed in the near future. Setting up the compiler toolchain on Windows is not trivial and even if the `CXX` override was respected, you'd still have to override `CC`, `AR`, `LINK` and other things to match the target environment.

As there's already #6560 for supporting Clang on Windows, closing.
