### ISSUE TITLE
Error message when using define in 

### ISSUE THREAD

**Issue by esmeraldaliaj** [godotengine/godot#65610]
### Godot version

4.0 alpha 16

### System information

Windows 10 & Linux

### Issue description

I am testing shader macros and encountered the following.

The code below:
![image](https://user-images.githubusercontent.com/5569899/189479173-f0e148cc-b91c-47a7-b2b2-9ace6eb24758.png)

throws the following error.
![image](https://user-images.githubusercontent.com/5569899/189479189-2d0e19ae-ae6e-4e8f-bd49-d12e1cbe97d7.png)

Is this a bug, or something not supported by Godot.

### Steps to reproduce

Any shader with the code above.

**Comment by Chaosus** [comment]
It's not a bug - basically you've inserting `float;` (with semicolon) to the middle of next line.
