### ISSUE TITLE
Anisotropic Filtering Level has no effect.

### ISSUE THREAD

**Issue by CoreTaxxe** [godotengine/godot#65614]
### Godot version

4.0-alpha16

### System information

Windows 11, Vulkan, RTX 3070 V. 516.94

### Issue description

Anisotropic Filtering Level has no effect on textures

Disabled
![image](https://user-images.githubusercontent.com/47256718/189482101-aaf788a9-7b3c-4ede-a35d-8f8a8c9f1e4f.png)

16x
![image](https://user-images.githubusercontent.com/47256718/189482087-e52884ef-447b-4ac0-aedb-e11fddb59923.png)

Material properties : (No filter does any significant change)
![image](https://user-images.githubusercontent.com/47256718/189482136-5ca26084-29a0-4861-a344-f980aefd71ed.png)

Texture import
![image](https://user-images.githubusercontent.com/47256718/189482167-f06f2894-a858-4590-8b3b-aba1cd2a165b.png)

on-run camera looks very distorted as well
![image](https://user-images.githubusercontent.com/47256718/189483252-71ffe676-1fa3-4ec6-aa02-efba9f9afdbc.png)

### Steps to reproduce

1. Create a new project. 
2. Select any texture with fine lines as tri-planar ground texture. 
3. Look from far above or in distance

**Comment by Zireael07** [comment]
Does anisotropic filtering level have an effect on non-triplanar materials? This is likely to be related to the fact it's triplanar

**Comment by CoreTaxxe** [comment]
Not as far as I can tell.
![image](https://user-images.githubusercontent.com/47256718/189487996-7d177e42-3777-41f3-89cc-1b68ffee3ba2.png)


vs godot 3.5


![image](https://user-images.githubusercontent.com/47256718/189488153-31fd23d5-fde9-4f84-a8a0-d950af061a65.png)

**Comment by mrjustaguy** [comment]
you aren't using Nearest*Linear Mipmap Anisotropic

**Comment by CoreTaxxe** [comment]
Because as I said this doesn't change anything.

**Comment by mrjustaguy** [comment]
I have been unable to reproduce, switching between linear mipmap and linear mipmap anisotropic works for me in a16, though I am on a GTX 1050 Ti and with older drivers.

**Comment by CoreTaxxe** [comment]
No its not disabled (also it works in 3.5 just fine)
Ive tested master and for what ever reason non-triplanar looks better with ansi filtering yet triplanar looks still jagged

**Comment by Calinou** [comment]
**Mipmaps > Generate** is disabled on your texture, so the texture does not contain any mipmaps. Therefore, there is no way anisotropic filtering can be performed.
