### ISSUE TITLE
[Godot 4] Gdscript parser bug and invalid cast error

### ISSUE THREAD

**Issue by Multfinite** [godotengine/godot#65620]
### Godot version

4.0 alpha 16

### System information

Windows 10

### Issue description

Hello. I have got the following messages from editor:
![image](https://user-images.githubusercontent.com/17569259/189486380-15ec7557-3990-416a-95d6-c5ffa713b158.png)
and got the following when i run the code in editor:
![image](https://user-images.githubusercontent.com/17569259/189486570-60fb29fc-4c46-403e-bfaf-1f307b68b7c1.png)
![image](https://user-images.githubusercontent.com/17569259/189486402-e280d117-ff24-4124-b054-cbf7ccb38168.png)
![image](https://user-images.githubusercontent.com/17569259/189486455-c4d48d0f-160d-4032-a89b-dbace686068a.png)
when definitions are:
![image](https://user-images.githubusercontent.com/17569259/189486619-267c08aa-535c-4fa0-9537-969efd9a3de9.png)
![image](https://user-images.githubusercontent.com/17569259/189486627-22a0bec1-241b-45d4-a558-119dfae22817.png)

Script did not execute now and drops with error. Also, i did not receive this error earlier when i test the project (but  i receive similiar messages earlier without crash).
I catch this error on godot 4 alpha 14 and godot alpha 16.

### Steps to reproduce

Just try to run a main scene from editor.

### Minimal reproduction project

[ParserBugReport.zip](https://github.com/godotengine/godot/files/9540633/ParserBugReport.zip)

**Comment by isaacwilliams** [comment]
I've been getting this too — unable to build my project. Was able to build _sometimes_ after moving to alpha 16, but it's now stopped entirely.

- Godot 4.0.alpha16
- MacOS Monterey

<img width="771" alt="Screen Shot 2022-09-12 at 8 25 15 am" src="https://user-images.githubusercontent.com/819616/189551433-af169b02-9f6a-484a-ae98-bf810ebd672e.png">

<img width="702" alt="Screen Shot 2022-09-12 at 8 23 19 am" src="https://user-images.githubusercontent.com/819616/189551409-a4f71eff-302f-4be1-baa8-4ddfce810d26.png">

**Comment by isaacwilliams** [comment]
FWIW, the example project provided doesn't build for me, and upon opening it for this first time, I got this message:

<img width="899" alt="Screen Shot 2022-09-12 at 8 33 53 am" src="https://user-images.githubusercontent.com/819616/189551803-4d334b29-0f70-4fc2-8c3e-f86cb0b1790f.png">

... which is the same message I've been repeatedly getting for my project on open (random selection of changed files each time)

<img width="906" alt="Screen Shot 2022-09-12 at 8 02 40 am" src="https://user-images.githubusercontent.com/819616/189551819-d1e61d45-0da9-4995-a897-342a554e5f73.png">

The builds stopped working entirely after I deleted the hidden `.godot/editor` cache folder to see if there was some incorrect data in there from moving between alpha versions.

**Comment by Chaosus** [comment]
@isaacwilliams it was already reported in https://github.com/godotengine/godot/issues/60997

**Comment by isaacwilliams** [comment]
@Chaosus thanks — removed my comment to not confuse this issue

**Comment by Multfinite** [comment]
![image](https://user-images.githubusercontent.com/17569259/193463062-bb0432b6-3ca5-4bce-b311-f5f1c25bda27.png)

**Comment by anvilfolk** [comment]
Can folks retest this? The MRP provided is not minimal at all, and the project needs to be ported to more recent versions, e.g. `@rpc(call_local)` needs to become `@rpc("call_local").

And if anyone has a small MRP, it would be very welcome :)

**Comment by vnen** [comment]
> Can folks retest this? The MRP provided is not minimal at all, and the project needs to be ported to more recent versions, e.g. `@rpc(call_local)` needs to become `@rpc("call_local").

Ping @Multfinite

**Comment by isaacwilliams** [comment]
FWIW I haven’t don’t think I’ve seen this since the betas

**Comment by adamscott** [comment]
Will close the issue. @Multfinite, if you encounter that bug with a new 4.0 or 4.1 build, don't hesitate to tell us. We'll reopen the issue.
