### ISSUE TITLE
[Godot4] Vehicle wheel rotation error when steering

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#65652]
### Godot version

v4.0.alpha16.official [86dd3f312]

### System information

Windows 10, 64bit

### Issue description

I create a vehicle and with 4 wheels. 2 for traction and steering, 2 for nothing.
![image](https://user-images.githubusercontent.com/35988767/189523040-1d2f00f6-fa97-4cfa-b0a7-49c4425af650.png)
And 2 for nothing.
![image](https://user-images.githubusercontent.com/35988767/189523052-ec4727ee-c5ee-4aba-8ea5-f7283631634c.png)

And attack code like this:
![image](https://user-images.githubusercontent.com/35988767/189524279-6a991eea-6b49-4cbb-9931-a73bda9a39ba.png)

When forward and back only, every thing was ok:

https://user-images.githubusercontent.com/35988767/189525387-706a6541-4087-4c85-b604-f5f98c4812e1.mov

But when steering, the traction wheels rotation error:

https://user-images.githubusercontent.com/35988767/189525480-27f70f26-c2bc-456b-b49e-0b8da4b66394.mov

### Steps to reproduce

Please run the reproduction project

### Minimal reproduction project

[VehicleTest.zip](https://github.com/godotengine/godot/files/9542355/VehicleTest.zip)

**Comment by BastiaanOlij** [comment]
This project is now working properly in current master however the steering is not in degrees, it is in radians, so 15 radians results in the wheels becoming backwards and the car reversing thrust when steering.

**Comment by akien-mga** [comment]
Closing then.
