### ISSUE TITLE
Tween not setting global_pos properly

### ISSUE THREAD

**Issue by Shin-NiL** [godotengine/godot#6565]
**Operating system or device - Godot version:**
Godot 2.1 Stable, Ubuntu 16.04 and Android 6

**Issue description** (what happened, and what was expected):
I'm using Tween to move a Sprite to a new global position (37, 545), but at the end of the transition, it's being placed at (36.999989, 545) and sometimes at (36, 545). 

**Steps to reproduce:**
Create a Sprite with a Tween node child and try this code:

```
extends Sprite

onready var tween = get_node("Tween")

func _ready():
    var new_pos = Vector2(37, 545)
    tween.interpolate_method(self , "set_global_pos", get_global_pos(), new_pos, 0.3, Tween.TRANS_SINE , Tween.EASE_IN)
    tween.start()
    yield(tween, "tween_complete")
    print(get_global_pos())
```

**Link to minimal example project** (optional but very welcome):

**Comment by volzhs** [comment]
yeah, end value of `Tween` is not correct in some case.
```gdscript
var test_value = 0

func on_tween_complete(a,b):
	print(test_value)  # prints 123456792

func _ready():
	var tw = Tween.new()
	add_child(tw)
	tw.interpolate_property(self, "test_value", 0, 123456789, 0.3, Tween.TRANS_LINEAR, Tween.EASE_IN, 0)
	tw.connect("tween_complete", self, "on_tween_complete")
	tw.start()
```

**Comment by Shin-NiL** [comment]
The issue reported by @volzhs isn't Tween related. Reading the code I saw that what happens here is that all the int values are converted to real before tweening. You can see a similar behavior just converting the 123456789 value to float:

`    print(123456789.0) # prints 123456792`
