### ISSUE TITLE
Godot 4 fails to run on Pop OS

### ISSUE THREAD

**Issue by ruineka** [godotengine/godot#65667]
### Godot version

Godot Engine v4.0.alpha16.official

### System information

Pop OS 22.04

### Issue description

The program fails to start up with the follow command line listings.
[godot_dump.txt](https://github.com/godotengine/godot/files/9543414/godot_dump.txt)

### Steps to reproduce

Attempt to open the program.

**Comment by ruineka** [comment]
It looks to be an issue with glibc breaking compatibility. Version 3.5 works just fine.

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/65409.
