### ISSUE TITLE
Cannot extend an Inner Class

### ISSUE THREAD

**Issue by bitwes** [godotengine/godot#65666]
### Godot version

4.0.alpha16.official.86dd3f312

### System information

OSX 10.15.7

### Issue description

When you attempt to `extend` an Inner Class it extends the base script instead.

### Steps to reproduce

Given:
`res://has_inner_classes.gd`
```
class InnerClassA:

    func hello():
        print('world')
```

`res://main.gd`
```
extends SceneTree

var HasInnerClasses = load('res://has_inner_classes.gd')

class ExtendsInnerClassA:
    extends "res://has_inner_classes.gd".InnerClassA

func _init():
    var inst = ExtendsInnerClassA.new()
    if(inst is HasInnerClasses):
        print('instance is a HasInnerClasses')
    if(inst is HasInnerClasses.InnerClassA):
        print('instance is a InnerClassA')

    quit()
```

Running `main.gd` in 3.5.stable.official.991bb6ac7 prints:
```
instance is a InnerClassA
```
Running `main.gd` in 4.0.alpha16.official.86dd3f312 prints:
```
instance is a HasInnerClasses
```

### Minimal reproduction project

[Godot4ExtendInnerClass.zip](https://github.com/godotengine/godot/files/9543356/Godot4ExtendInnerClass.zip)

**Comment by Chaosus** [comment]
I've tested it, and it seems to be fixed at 11e1c83309e7e7c15018c8b2c6456fa294116244 (probably by https://github.com/godotengine/godot/pull/68374).
