### ISSUE TITLE
Shader: gradient png behaves wrong compared to GradientTexture in Texture2D

### ISSUE THREAD

**Issue by CheapMeow** [godotengine/godot#65662]
### Godot version

v4.0.alpha16.official [86dd3f312]

### System information

Ubuntu 22.04.1 LTS,GeForce RTX 2060 Mobile,TU106M,Vulkan

### Issue description

When using gradient png i made, the mesh appear some green or blue or purple lines

![图片](https://user-images.githubusercontent.com/88229072/189539096-de4df66e-11e0-49b0-b172-4e9fc13a7a95.png)
![图片](https://user-images.githubusercontent.com/88229072/189539114-7c9cbf60-d2e8-489c-b69d-d28e1429eb0c.png)

but if using the interal GradientTexture in Texture2D, dirty lines disappear

![图片](https://user-images.githubusercontent.com/88229072/189539150-a6eb15d0-d072-43d3-9367-077295501111.png)
![图片](https://user-images.githubusercontent.com/88229072/189539235-5d594159-4337-447a-af4f-582b9cf6326c.png)

what makes the difference between the two? I  just  see  the tutorial [Unity Shader Graph - Slash Shader Effect Tutorial](https://www.youtube.com/watch?v=9Nv28O2OIoQ) and unity dont have the probllem, so it feels like a bug

### Steps to reproduce

1.Open p_sword_slash.tscn
2.Open details panel of CPU Particles 3D, open visual shader in material
3.Link each Texture2D  to Pow, see the difference

### Minimal reproduction project

[Reproduction.zip](https://github.com/godotengine/godot/files/9543100/Reproduction.zip)

**Comment by Calinou** [comment]
This is not a bug – this loss of quality on the texture is caused by VRAM compression, which is automatically enabled on textures that are used in 3D.

Select the PNG in the FileSystem dock, go to the Import dock, set compression to **Lossless** then click Reimport.
