### ISSUE TITLE
GDScript fail to call methods with variable arguments under certain conditions.

### ISSUE THREAD

**Issue by Faless** [godotengine/godot#65689]
### Godot version

4.0-dev

### System information

Linux

### Issue description

This is a generalized issue for #59939 .

After some digging I found out that the GDScript VM encounters an error when calling methods with variable arguments (e.g. `rpc`/`rpc_id`/`call_group`/etc) and certain conditions are met:

1 - No extra arguments are passed beside the minimum required.
2 - All arguments match the expected type (i.e. no type conversion is needed).

So:

```gdscript
get_tree().call_group("some_group", &"some_method") # Works.
get_tree().call_group(&"some_group", &"some_method") # Method/function failed.
```

See the "steps to reproduce below" for more examples.

Note that this does not appear to be an issue with StringName specifically, I've tried changing the type of `rpc` from StringName to String and the behavior ended up being swapped (failing when passing a String, working when passing a StringName).

### Steps to reproduce

Run this script (or see the attached project):

```gdscript
func _ready():
	var g = &"some_group"
	var m = &"some_method"
	get_tree().call_group(g, m) # Works.
	get_tree().call_group("some_group", "some_method") # Works.
	get_tree().call_group("some_group", &"some_method") # Works.
	get_tree().call_group(&"some_group", &"some_method") # Method/function failed.
```

### Minimal reproduction project

[proj_vaargs_bug.zip](https://github.com/godotengine/godot/files/9546324/proj_vaargs_bug.zip)

**Comment by KoBeWi** [comment]
I did investigate that issue once and here are more details: https://github.com/godotengine/godot/issues/61975#issuecomment-1161070923
