### ISSUE TITLE
Invalid call to function 'start' in base 'Thread'. Expected 2 arguments. [Godot 4 alpha]

### ISSUE THREAD

**Issue by 1SMOL** [godotengine/godot#65703]
### Godot version

v4.0.alpha16.official [86dd3f312]

### System information

Fedora Linux 36, Windows 11

### Issue description

While following a documented tutorial involving using threads, trying to run the project leads to the error `Invalid call to function 'start' in base 'Thread'. Expected 2 arguments.`

### Steps to reproduce

Using the currently available UPNP tutorial that uses threads _should_ reproduce this error.

**Comment by Calinou** [comment]
I think the documentation is outdated – the threading APIs have changed since Godot 3.x.
