### ISSUE TITLE
In the code editor, replace dialog would have to show the last matching pair

### ISSUE THREAD

**Issue by Rocket-Buddha** [godotengine/godot#6570]
Feature proposed: 
In the code editor, replace dialog would have to show the last matching pair.

![screenshot from 2016-09-20 20-33-17](https://cloud.githubusercontent.com/assets/4625251/18692923/0dfd026a-7f9e-11e6-91ea-4c39b32b787e.png)

![screenshot from 2016-09-20 20-36-47](https://cloud.githubusercontent.com/assets/4625251/18692948/322d75f2-7f9e-11e6-8dd1-cfbc123ca46b.png)

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
No answer, and I don't understand what the feature request is about, so closing.
