### ISSUE TITLE
RemoteTransform2D doesn't work with all `CanvasItem`s, despite documentation saying so

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot#65716]
### Godot version

v4.0.alpha15.official [432b25d36]

### System information

Arch on 5.19.6-arch1-1

### Issue description

> RemoteTransform2D pushes its own Transform2D to another CanvasItem derived Node (called the remote node) in the scene.

However, I can't select `Control`s.
![image](https://user-images.githubusercontent.com/14253836/189730081-114578b1-4608-4864-9900-f22aba40c617.png)

Code will need to be refactored by a large amount to expand this feature to CanvasItem, because it looks like canvas items don't have `set_global_transform`, `set_transform`, `set_scale`, etc.?

### Steps to reproduce

1) Create a RemoteTransform2D
2) Try changing remote_path to a `Control`

### Minimal reproduction project

N/A

**Comment by lmsonic** [comment]
Now stable documentation for [RemoteTransform2D](https://docs.godotengine.org/en/stable/classes/class_remotetransform2d.html) says:
> RemoteTransform2D pushes its own [Transform2D](https://docs.godotengine.org/en/stable/classes/class_transform2d.html#class-transform2d) to another [Node2D](https://docs.godotengine.org/en/stable/classes/class_node2d.html#class-node2d) derived node (called the remote node) in the scene.

**Comment by AThousandShips** [comment]
Closing as per the above comment
