### ISSUE TITLE
TGA import/loading does not support 16-bits-per-pixel files

### ISSUE THREAD

**Issue by Ithamar** [godotengine/godot#65715]
### Godot version

all

### System information

all

### Issue description

Currently, the TGA loading code in Godot fails on 16-bits TGA files. Looking at the code it seems this has simply not been implemented.

Would a PR to add this be accepted?

### Steps to reproduce

Try to import a TGA file that uses 16-bits per pixels (RGB565 or RGBA5551).

**Comment by Calinou** [comment]
> Would a PR to add this be accepted?

Sure :slightly_smiling_face:

**Comment by Ithamar** [comment]
Actually, looking further into the TGA reading code it also seems to assume that the alpha channel stored is always valid, while there is a bit in the header to indicate if this is the case (if the alpha isn't valid, it is simply ignored and replaced with 0xff).

Should I make a separate PR for that or would an "improve TGA file support" PR fixing both issues be ok?
