### ISSUE TITLE
GDScript 2.0 : Trying to iterate on a null value.

### ISSUE THREAD

**Issue by hkrbl43** [godotengine/godot#65710]
### Godot version

4.0 alpha-16

### System information

Xubuntu 20.04, Vulkan, Intel UHD 630.

### Issue description

When using a CharacterBody2D to detect collision , an error occurs: `Trying to iterate on a null value. ` It actually worked in Godot 3.x , but not working in Godot 4.0

Here is a reference image of my code:
![gdscript error](https://user-images.githubusercontent.com/107879733/189693584-a96721a9-d9c9-40a4-b422-e7a97f0b972c.png)

### Steps to reproduce

This issue can be reproduced by running this piece of code in _physics_process(delta):

` func detect_collision(): 
 for i in get_last_slide_collision():
		var collision = get_slide_collision(i) 
		if collision:
                   print("Collided with " , collision.get_collider()) `

**Comment by KoBeWi** [comment]
You sure it worked in 3.x? You should use `get_slide_collision_count()` for the loop.

**Comment by gotnospirit** [comment]
https://docs.godotengine.org/fr/stable/classes/class_kinematicbody2d.html#class-kinematicbody2d-method-get-slide-collision

**Comment by KoBeWi** [comment]
So as I said, you likely mixed functions. There is no way it worked in 3.x (and I actually tested that it doesn't).

Closing. Please provide a minimal reproduction project if you still think it's an issue.
