### ISSUE TITLE
MSAA 4x/8x Prevents Camera3D CameraAttributesPhysical From Focusing

### ISSUE THREAD

**Issue by tinmanjuggernaut** [godotengine/godot#65724]
### Godot version

Godot 4 Alpha 16

### System information

Windows 11/64, RTX 3070, Vulkan

### Issue description

When using CameraAttributesPhysical with Camera3D, then setting MSAA_3D to 4x or 8X, the image goes blurry, and frustum_focus_distance has no effect. 

MSAA 2X or disabled works fine. The other blur quality and method settings don't have any effect. The other AA methods don't appear to be affected.

@clayjohn 

### Steps to reproduce

See above.

**Comment by clayjohn** [comment]
Sounds like it may be related to an issue with MSAA that was introduced recently and fixed earlier today (in https://github.com/godotengine/godot/pull/65676). Can you try again in latest master and see if you can reproduce the issue?

**Comment by tinmanjuggernaut** [comment]
Yes it does, thank you.
