### ISSUE TITLE
HTTPClient (Godot) does not work

### ISSUE THREAD

**Issue by Dunkhan** [godotengine/godot#65722]
### Godot version

v3.5.stable.mono.official [991bb6ac7]

### System information

Windows 10

### Issue description

The godot [HTTPClient](https://docs.godotengine.org/en/stable/tutorials/networking/http_client_class.html), when copying the code from the official tutorial on that page, does not appear to work. it prints the message "Resolving" and then the message "Connecting" over and over until the user ends the process.

I may have made an error or the tutorial might be out of date but I thought this was worth reporting either way. I know I can use an HTTPRequest node but I do not want to have to hack around using a node for something that I was intending to set up as a singleton service. It is a huge architecture restriction to have to use a node instance for this.

### Steps to reproduce

create an HTTPClient instance and try to access it in the way that the tutorial describes

OR

download the project here: https://github.com/Dunkhan/GodotHttpBug
Uncomment the line marked "HTTPClient"
comment out the other test lines
Run the program

THEN

Watch the console for output

### Minimal reproduction project

https://github.com/Dunkhan/GodotHttpBug

**Comment by raulsntos** [comment]
You are trying to connect to host `https://www.reddit.com` on port `80` which is HTTP, the port for HTTPS is 443.

**Comment by Dunkhan** [comment]
Right you are, looks like a problem between keyboard and chair. I will just close this.
