### ISSUE TITLE
VehicleWheel was inside the ground

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#65739]
### Godot version

v3.5.stable.official [991bb6ac7]

### System information

Windows 10, 64bit

### Issue description

![image](https://user-images.githubusercontent.com/35988767/189864916-a30708ae-4585-4bf3-b802-ad1bdcd08201.png)

### Steps to reproduce

/

### Minimal reproduction project

[WheelTest.zip](https://github.com/godotengine/godot/files/9555547/WheelTest.zip)

**Comment by Zireael07** [comment]
dupe of #45339 (seriously, did you search for "vehicle wheel", it's one of the first results)

**Comment by CsloudX** [comment]
> dupe of #45339 (seriously, did you search for "vehicle wheel", it's one of the first results)

Sorry, I'm not. Should I close this issue?

**Comment by akien-mga** [comment]
No worry :) And the minimal project you made will be useful for testing.

Closing as duplicate of #45339.
