### ISSUE TITLE
ImageTexture create_from_image doesn't work with Godot 4

### ISSUE THREAD

**Issue by ricardoalcantara** [godotengine/godot#65730]
### Godot version

4.0.alpha16.official.86dd3f312

### System information

Linux Manjaro, GeForce GTX 1060 6GB (Vulkan)

### Issue description

I tried to generate a Image to set a Sprite with an ImageTexture just filled with black and it doesn't work with Godot 4. The example came from a project that works file with Godot 3

### Steps to reproduce

Create an Image;
Fill with Black;
Create an ImageTexture from image;
Set a Sprite2D

### Minimal reproduction project

https://github.com/ricardoalcantara/godot-fow-tutorial

**Comment by gotnospirit** [comment]
The `es` [documentation](https://docs.godotengine.org/es/stable/classes/class_imagetexture.html#class-imagetexture-method-create-from-image) is not up-to-date

[ImageTexture.create_from_image](https://docs.godotengine.org/en/latest/classes/class_imagetexture.html?highlight=create_from_image#class-imagetexture-method-create-from-image) is now a static method which returns a new texture
https://github.com/godotengine/godot/blob/16228ba3e27b57df48256fcdf34670a25b3d52b0/scene/resources/texture.cpp#L170

You can remove your `fogTexture` var and replace with this
```
fog.texture = ImageTexture.create_from_image(fogImage)
```
https://github.com/ricardoalcantara/godot-fow-tutorial/blob/7a0a54c901f0918dd57c8f1c3f4517fe9cdddb85/World.gd#L36

**Comment by ricardoalcantara** [comment]
I totally missed it, now it works!
