### ISSUE TITLE
C# File.FileExists(string path) is non static

### ISSUE THREAD

**Issue by al1-ce** [godotengine/godot#65744]
### Godot version

3.5.stable.mono

### System information

Win 11

### Issue description

In c# bindings method FileExists described as:
```c#
[GodotMethodAttribute("file_exists")]
public bool FileExists(string path);
```
Opposed to Godot docs:
```c#
bool file_exists ( String path ) static
```

### Steps to reproduce

As Described in issue description.

**Comment by raulsntos** [comment]
According to the [3.5 docs](https://docs.godotengine.org/en/stable/classes/class_file.html#class-file-method-file-exists):

![image](https://user-images.githubusercontent.com/3903059/190006598-97c7b85c-ca78-4e10-8807-7c6984d0a98e.png)

The `file_exists` method is not static in 3.x, it was only made static in 4.0.
