### ISSUE TITLE
Inspector grouping not user friendly when debugging

### ISSUE THREAD

**Issue by TokisanGames** [godotengine/godot#65741]
### Godot version

16228ba3e

### System information

Windows 11/64, RTX 3070, Vulkan

### Issue description

When debugging, Inspector grouping 
* has too many headers, and 
* should have an option to expand by default.

I think this was caused by https://github.com/godotengine/godot/pull/62707

When debugging, properties of all objects are grouped and collapsed by default, even if they don't even have a script. Eg. a Node2d shows Node, with Path variable collapsed. 

![image](https://user-images.githubusercontent.com/632766/189868458-c44aac01-0c41-4f8a-b565-7d04219d7d0f.png)

And when I do have a script, I get groups I didn't specify.

![image](https://user-images.githubusercontent.com/632766/189869298-40c5c442-9e8f-4dd6-b404-3dac6e0faf7e.png)

We even get multiple tiers. If these are items for cell.gd, why do I need Constants, AND cell.gd, Members, AND cell.gd? Why not just have one header and remove the other 3? And maybe Node as well.

![image](https://user-images.githubusercontent.com/632766/189869635-3df4df28-6701-43b8-91b4-317f63fcc8f8.png)

Finally, the biggest annoyance is that they're all collapsed by default.

If I expand or click expand-all, then when I click back on the node, they're all collapsed again. The extra clicks are quite annoying when I'm debugging as I constantly have to open everything back up to view the properties.

### Steps to reproduce

n/a

**Comment by KoBeWi** [comment]
> should have an option to expand by default.

Check Disable Folding editor setting.

**Comment by tinmanjuggernaut** [comment]
Thank you. But this disables folders entirely. Everything gets expanded and there is no option to collapse anything. On materials, it's handy to see which collapsed properties have been changed. 

We need a happy medium. Before, debugging properties were readily available. Now they are buried sometimes 2 levels deep, every time a node is selected.

**Comment by KoBeWi** [comment]
I bisected and this was casued by #65520 (which, ironically, fixed the remote inspector)
CC @SaracenOne

**Comment by KoBeWi** [comment]
The issue has reappeared and exists in 4.2 dev6. Reopening.
