### ISSUE TITLE
Image.lock() missing in Godot 4 Alpha17

### ISSUE THREAD

**Issue by Griefchief** [godotengine/godot#65761]
### Godot version

4.0.alpha17.official

### System information

Windows 10, Vulkan

### Issue description

Image.lock() and Image.unlock() functions have dissapeared from the Image class. They were needed in Godot 3 for Image.set_pixel() to be performant. Since we switched to Vulcan, they might, or might not be needed. Creating this just in case, close or continue with based on need.

### Steps to reproduce

Not needed: Open Alpha17 Godot 4 look at Image class documentation.

### Minimal reproduction project

Not needed

**Comment by Griefchief** [comment]
@Zylann  FYI

Potentially connected to #65762 https://github.com/godotengine/godot/issues/65762

**Comment by Zylann** [comment]
The API doesnt require to use a locking pattern anymore, `get_pixel` and `set_pixel` can be used directly. It is not related to the other issues though.

**Comment by akien-mga** [comment]
Yes this removal is intentional.

**Comment by CycloneRing** [comment]
this made image very slow. also it require to lock unlock by engine internal and this will cause double copy if using set_data, am I wrong?
