### ISSUE TITLE
drop_data is called only if can_drop_data is true

### ISSUE THREAD

**Issue by Elinvention** [godotengine/godot#6577]
Godot 2.2 on Debian testing.

If I drop something where can_drop_data return false, drop_data is not called, so I can't know when I drop something where I can't.

**Comment by LeonardMeagher2** [comment]
what's a use case for this behavior? (just curious)

**Comment by reduz** [comment]
yeah this was changed in 2.1 because a lot of users considered it a bug

**Comment by Elinvention** [comment]
An use case is inventories: https://github.com/RodZill4/godot_inventory. He had to hack around this missing Godot's functionality.

**Comment by akien-mga** [comment]
Maybe there should be another callback for when you drop data where you can't?

**Comment by Elinvention** [comment]
I'd like to make this change and I tried to add a `drop_data_outside` callback and I added code wherever `drop_data` appears in the code. However, it doesn't work and callback is not called. What I don't understand is the code of `Control::drop_data` in `scene/gui/control.cpp`. Copy and rename is not enough... can someone help me? Can I open a pull request with my not working changes?

**Comment by Elinvention** [comment]
Oh, I forgot about this... In the mean time I found a better solution that needs no modifications of the engine (https://github.com/Freedom-Hunter/Freedom-Hunter/blob/master/src/inventory.gd).
