### ISSUE TITLE
Exported iOS Xcode project not working

### ISSUE THREAD

**Issue by marius-se** [godotengine/godot#65772]
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

4.0.alpha17

### System information

macOS 12.5, iPhone 11 Pro with iOS 15.6.1, Vulkan 1.3.216.0

### Issue description

When running an exported default 3D Godot project (Camera + Cube) on iOS I get a black screen and the following error message: `MTLCompiler: Compilation failed with XPC_ERROR_CONNECTION_INTERRUPTED`. The error message appears over and over again for around 60 seconds. After +-60 seconds the error message stops appearing and the game shows up.

Could this be related to something like [this Apple thread](https://developer.apple.com/forums/thread/661529)?

### Steps to reproduce

Create a new Godot project, add a Camera + MeshInstance. Export to iOS. Run Xcode project on a real iOS device.

**Comment by marius-se** [comment]
This might be related to #65234 and #64471?

**Comment by jcurtis06** [comment]
I am also having this issue, iOS 16, iPhone 11, MacBook Pro M1. The splash screen appears, then the screen goes black... except in my case, it doesn't seem like the game ever loads.

I pasted the entire error from Xcode into a Pastebin [here](https://pastebin.com/t3127p9v)

**Comment by marius-se** [comment]
Looking at your Pastebin I get the same `USER ERROR: Condition "!classes.has(ti.inherits)" is true.` error IIRC. (In addition to the `MTLCompiler: Compilation failed with XPC_ERROR_CONNECTION_INTERRUPTED`

**Comment by jcurtis06** [comment]
@marius-se just out of curiosity, what Macbook do you have? @undefinedhuman is using the same laptop as me; it could possibly be a compatibility issue with Apple Silicon?

**Comment by marius-se** [comment]
@jcurtis06 M1 Pro (MacBook Pro). I also have an Intel one I could test with tonight.

**Comment by finpingvin** [comment]
I am having the same issue on an Intel macbook pro

**Comment by marius-se** [comment]
Ah good to know - forgot to check this last week.

**Comment by ViktorEvil** [comment]
same on an M1 Pro and iPhone 11

**Comment by keeganstothert** [comment]
same on m1, MacOS Ventura, Xcode 14.1

**Comment by akien-mga** [comment]
CC @bruvzg

**Comment by marius-se** [comment]
Closing since this is fixed on master now. (since #68740)
