### ISSUE TITLE
SkeletonModification3D Bone Name field isn't dropdown and typing bone name is buggy

### ISSUE THREAD

**Issue by Mikeysax** [godotengine/godot#65781]
### Godot version

4.0-alpha17

### System information

PopOS 22.04, 5.19.0-76051900-generic kernel, Ryzen 6800h, Radeon 6700m, amdgpu, Vulkan

### Issue description

When adding a SkeletonModification3D to Skeleton3D for bone IK:

1) The bone name field isn't a dropdown for selecting bones:

![Screenshot from 2022-09-14 08-27-37](https://user-images.githubusercontent.com/15805689/190154217-501eeb67-c200-4e4d-9077-1b6601c6dbc6.png)

2) Bone Name also only allows entering one character at a time:

[Kooha-2022-09-14-08-33-34.webm](https://user-images.githubusercontent.com/15805689/190154732-dce1025a-669d-431e-b9d0-c76bc4ed01ea.webm)

3) Bone Name also only allows typing from left to right sometimes, see 14 seconds in:

[Kooha-2022-09-14-08-35-45.webm](https://user-images.githubusercontent.com/15805689/190155825-28be9a88-c7e4-4430-9f05-715579f9c39b.webm)

### Steps to reproduce

Add a SkeletonModificationStack3D to a Skeleton3D

**Comment by fire** [comment]
See https://github.com/godotengine/godot/pull/65768 for proposed changes.

**Comment by Calinou** [comment]
> Bone Name also only allows entering one character at a time:

This is because the inspector is refreshed every time the property's value changes. This should be avoided on string properties as it doesn't work correctly.

**Comment by TokageItLab** [comment]
SkeletonModification3D is no longer available.
