### ISSUE TITLE
Control rect_position coordinates are rounded to integer

### ISSUE THREAD

**Issue by elektito** [godotengine/godot#65785]
### Godot version

3.5.stable

### System information

Linux (Ubuntu 20.04), GLES2, RTX 2070

### Issue description

I was trying to create a ColorRect node with non-integer values in rect_position, that I noticed that the coordinates of the drawn rectangle always seem to be at integer positions. See for example:

![godot-control-bug](https://user-images.githubusercontent.com/28643/190184992-662f5b3c-3507-43b9-ba5e-2d5c53264f35.png)

As you see, rect_position is (-3.5, -5), but the actual rectangle seems to be drawn at (-4, -5). In the above image, the grid is drawn at 1px steps. Even the selection rectangle is at the correct location, but the drawn rectangle itself is not.

This does not happen only in the editor. I managed to confirm that by adding a rectangular CollisionShape2D with the same size and position, enabling "visible collision shapes" and running the scene. The collision rectangle does not match the ColorRect.

This issue seems to happen with other control nodes as well.

### Steps to reproduce

1. Create a new scene.
2. Set grid steps to 1px/1px, and primary lines at every 1 step.
3. Add a ColorRect node, set it's rect_size to (7, 10) and rect_position to (-3.5, -5).
4. Observe the position is not correct.

### Minimal reproduction project

[control-bug.zip](https://github.com/godotengine/godot/files/9567400/control-bug.zip)

**Comment by kleonc** [comment]
You need to disable `gui/common/snap_controls_to_pixels` in the `Project Settings` (and trigger redrawing the ColorRect in the editor, e.g. by hiding and showing it).

**Comment by elektito** [comment]
Ah, that makes sense now. Thanks.
