### ISSUE TITLE
Add Array.last()

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#6579]
Currently, to get the last element of an array we have to write `array[array.size()-1]`, which is a bit tedious given how many times this case happens.
Could we have an `array.last()` method like STL does with `back()`?

**Comment by felaugmar** [comment]
Hey, I'm able to do that, it's really simple.

But I have a doubt about the array files at `/godot/core/array.h \ cpp`;
Just by changing the files and modifying the `/doc/base/classes.xml` to match, the new "version" of my array will work?

--
I saw this is different from Custom modules that we 'bind' the methods, that's the why of my doubt.

**Comment by Hinsbart** [comment]
@felaugmar no it won't be exposed to gdscript automatically, you still have to bind it.
The binding for array methods happens in `core/variant_call.cpp` specifically [here](https://github.com/godotengine/godot/blob/master/core/variant_call.cpp#L460-L483) and [there](https://github.com/godotengine/godot/blob/master/core/variant_call.cpp#L1566-L1587).

**Comment by supaiku-o** [comment]
Just for record, it should return null on an empty array right?
And while we are at it, please let's also consider a `array.first()` function.

**Comment by felaugmar** [comment]
@Hinsbart, thx, I'll see if I can figure out how the binding works (it seems a little complex) and if I can understand, I'll contribute with both functions.

@Zylann `array.last()`
@supaiku-o `array.first()`

**Comment by bojidar-bg** [comment]
Note that we support `array[-1]` syntax just fine, so this might be useless nowdays.

**Comment by Zylann** [comment]
@bojidar-bg oh! Brilliant, I didn't know that :)

**Comment by Zylann** [comment]
Actually, I wonder if it's really coherent with the C++ side. I don't see access by negative index in Array and Vector, only error.

**Comment by felaugmar** [comment]
Well, I did the functions, it's working, but faulty and is not so simple as I thought.
I can't figure out how to bind with the `Variant` returning value directly and how to break in editor in case of `_p->array.size() == 0`.

--
Well, temporarily, I give up of editing the core, it's missing some knowledge for me to do this.
😢

**Comment by Zylann** [comment]
@felaugmar usually I think error checking is done with something like
```cpp
ERR_FAIL_COND(size() == 0, "The array is empty");
```

**Comment by bojidar-bg** [comment]
Should this be closed, or you prefer it staying open?

**Comment by Zylann** [comment]
I don't mind if nobody else wants this, I use [-1] now in GDScript. I would eventually like to have it in C++ because I saw it's not there, but I don't really need it now.

**Comment by bojidar-bg** [comment]
Retagging for core then...

**Comment by Kazuo256** [comment]
I would like to try implementing this. From what I gather from @felaugmar's attempt, I have to:

1. Implement methods `Array::front` and `Array::back` in `core/array.{h,cpp}`
2. Raise an error if the array is empty
3. Update the bindings in `core/variant_call.cpp`
4. Update the documentation in `doc/base/classes.xml`
5. Write tests?

Is that correct?

**Comment by Hinsbart** [comment]
@Kazuo256 yes :)

**Comment by Kazuo256** [comment]
Alright. I'll probably come back to ask some things when I get to the tests.

**Comment by Kazuo256** [comment]
I just noticed I actually wrote `front`/`back`, but the original proposal was `first`/`last`. Is there a preferred one? Or should make aliases?

Besides this point, I've finished steps 1 through 4. Time for tests. Is there a guide or quick reference I can follow for this?

**Comment by vnen** [comment]
Godot has no automated tests.

**Comment by Kazuo256** [comment]
OK. Then I only need to know which name to use.

**Comment by Zylann** [comment]
When I first wrote the issue I was not really bothering about the names, as long as they are meaningful. Front and back sound fine, it's like STL :)

**Comment by vnen** [comment]
Solved by #7149.

**Comment by mustafa3max** [comment]
This method gives the last value
`listPoint [listPoint.size () - 1]`
But I cannot use it in conditional sentences
If there are repeating items in the list
Is there another solution?

**Comment by Zylann** [comment]
Either repeat it or use a temporary var
```gdscript
var last = listPoint[listPoint.size() - 1]
if last and last or last:
    # ...
```
