### ISSUE TITLE
Scene importer doesn't make use of imported texture files

### ISSUE THREAD

**Issue by tagcup** [godotengine/godot#6580]
**Operating system or device - Godot version:**
Debian GNU/Linux

**Issue description** (what happened, and what was expected):
Importing a collada results in a .scn file, and additional .tex files. It appears that the importer-generated .scn file doesn't make use of these .tex files; instead, it stores an additional internal copy of the textures data within the .scn file, and I'm not entirely sure but this data might even be uncompressed (judging by the file sizes, more on this below).

I expected that the generated .scn file would make use of generated .tex file. Furthermore, I wouldn't expect any non-compressed texture data to be stored anywhere.

**Steps to reproduce:**
I tested this with a Better Collada Exporter generated .dae file, which uses 4 textures:
- Using VRAM compression, it created 5 texture files totaling around 22MBs and a .scn file around 34MB.
- Using WebP compression, it created 5 texture files totaling around 800KB and a .scn file again around 34MB.
- After editing the materials in the scene with Godot to use the generated .tex files, the .scn file reduced to ~2MB.

I tested this with a totally different dae file, with similar results.

**Link to minimal example project** (optional but very welcome):

**Comment by bojidar-bg** [comment]
I think this is fixed on master by the new import method, but should we keep it around for 2.1.x?

**Comment by tagcup** [comment]
The import happens behind the scenes now, sure, but has the code that does the actual import been rewritten too?

**Comment by tagcup** [comment]
2.x issue, closing
