### ISSUE TITLE
4.0: Cannot extend a script through the editor (create button does nothing)

### ISSUE THREAD

**Issue by WolfgangSenff** [godotengine/godot#65827]
### Godot version

4.0.alpha17

### System information

Windows 11

### Issue description

![image](https://user-images.githubusercontent.com/148612/190404704-f2329ec9-f739-47ce-9e55-38842b6ed692.png)

Whenever I hit the Create button on this dialog, nothing happens. This error shows up in the output:

![image](https://user-images.githubusercontent.com/148612/190404865-4e80a4d1-645e-4ca7-9b98-af301959aaa4.png)

### Steps to reproduce

1. Create a base scene and give it a script
2. Inherit that scene (easiest, but if you just try to extend it as-is and change the name, it still doesn't work)
3. In inherited scene, extend the given script.
4. Note the create button gives the error mentioned.

### Minimal reproduction project

[ExtendScriptBug.zip](https://github.com/godotengine/godot/files/9575270/ExtendScriptBug.zip)

Note that there are at least two scenes here where this is a problem. I've added a Temp folder that shows it a bit more clearly, but it also happens with Dishwasher, inheriting from interactable.

**Comment by WolfgangSenff** [comment]
Note that if I give my base type a class name, it works, so it seems this is specifically when providing a string as the type its inheriting from.

**Comment by Touff-97** [comment]
I have a similar issue with a thrown error in **Godot Beta 1**:

![imagen](https://user-images.githubusercontent.com/29293987/190924163-8624161f-763e-4600-b6d2-3746c085ca88.png)

I'm trying to extend a script in this screenshot
