### ISSUE TITLE
Editor stuck in "The following files are newer on disk" after deleting file

### ISSUE THREAD

**Issue by es1024** [godotengine/godot#65824]
### Godot version

v4.0.alpha17.official.22a09fef5 

### System information

Ubuntu 20.04

### Issue description

Deleting a text file on disk and the directory it's in outside of the editor that is currently opened in the editor results in a "The following files are newer on disk", where all three buttons do the same thing: close the popup and immediately open it back up again.
- Reload silently fails (file does not exist and thus cannot be reloaded, but user is not informed of this aside from the popup appearing again)
- Cancel fails (instead of giving up on the file)
- Resave fails (because the directory does not exist)

Forcefully closing the editor (e.g. with `kill`) and reopening it resolves the issues.

### Steps to reproduce

1. Create a project.
2. Create a new directory under the project, add a new text file under the directory, and open it for editing within Godot.
3. Delete the directory (outside of Godot, e.g. using `rm`).
4. The editor will now show a "The following files are newer on disk" prompt that will reappear when any button on it is clicked. The editor now needs to be closed forcefully.

**Comment by PucklaMotzer09** [comment]
I tried to reproduce this issue, but it does not occur. All that happens is that the text file stays opened with the previous contents and the debug output says:
```
  Cannot open TextFile 'res://super_file.txt'.
  Cannot load text file 'res://super_file.txt'.
  editor/plugins/script_editor_plugin.cpp:2580 - Condition "!rel_text_file.is_valid()" is true. Continuing.
```

## System Information

+ OS: Garuda Linux (Arch), QTile
+ Version: v4.0.beta.custom_build [4ba934bf3]

**Comment by es1024** [comment]
After a bit more testing, it seems like the Resave button falls into this loop if the directory that the file was in is also deleted at the same time, but works if the file is the only thing deleted -- I've edited the issue to clarify this.

**Comment by FyiurAmron** [comment]
@es1024 for me even removing an open _file_ outside of the editor produces quirky behaviour - the only option that does anything in the dialog is "Resave", which recreates the file. Reload/Cancel/window close buttons don't work. Does this also happen for you? (see https://github.com/godotengine/godot/issues/65912)

**Comment by es1024** [comment]
@FyiurAmron Yes. Reload fails as it should (file doesn't exist) but could ideally give an error instead. Cancel is broken if the file is gone (you should be able to, but can't give up on the file). Resave fails if the directory doesn't exist (cannot recreate file because target directory is missing). The combination of all three results in this issue, where the editor is stuck with the prompt until restart.
