### ISSUE TITLE
Vulkan: Godot 4.0 Beta.1 doesn't open on outdated NVIDIA drivers

### ISSUE THREAD

**Issue by derickfelix** [godotengine/godot#65838]
### Godot version

Godot Engine v4.0.beta1.official.20d667284

### System information

Windows 10, Intel(R) HD Graphics 520, NVIDIA GeForce 930M

### Issue description

After clicking the executable, a white window appears for a few seconds and then it disappear.
![image](https://user-images.githubusercontent.com/20743967/190481023-f598bc7b-f917-41e7-9bbc-9934c3d774b3.png)

The cmd window remains there, it displays this information

![image](https://user-images.githubusercontent.com/20743967/190480563-41a45798-8623-4b2f-9902-4930e44803ab.png)

It works normally on 3.x versions, all 4.x I tried had the same issue.

### Steps to reproduce

You just have to open the executable.

**Comment by Calinou** [comment]
The GeForce 930M has a Maxwell GPU, so it should be able to support Vulkan. Make sure to install the latest driver version from nvidia.com (*not* Windows Update, *not* your laptop's OEM).

**Comment by gotnospirit** [comment]
I had the same issue with my 850M, but installing the latest driver (516.69) solved the problem

**Comment by swashdev** [comment]
Opening Godot 4.0.beta1.official.20d667284 on Windows 10 64-bit gave the following messages in the console:

```
Godot Engine v4.0.beta1.official.20d667284 - https://godotengine.org
Vulkan API 1.2.0 - Using Vulkan Device #1: NVIDIA - GeForce GTX 1650 with Max-Q Design
ERROR: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
        vkCreateDevice:  Failed to create device chain.
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 1818399573664
   at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:171)
ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: _create_device (drivers/vulkan/vulkan_context.cpp:1257)
```

Downloading the latest game-ready driver for my card resolved the issue and the editor now opens as normal.

**Comment by derickfelix** [comment]
I updated the drivers and it is working now, thanks.
