### ISSUE TITLE
Visual Scripting: 'Wait' node doesn't work when using a 'Condition' node.

### ISSUE THREAD

**Issue by samvila** [godotengine/godot#6583]
**Operating system or device - Godot version:**
Nightly build from http://www.purpleorangegames.com/godot/ (Date: 09/21/16). Windows 10 64 bit

**Issue description** (what happened, and what was expected):
Please see this sample image with a simple set up: http://pasteall.org/pic/show.php?id=106959
Even using _ready instead of _process it never prints the string after the 'condition' node. This problem has been confirmed by 2 other users on the IRC channel.

**Steps to reproduce:**
Recreate the image from above, you can use _ready instead of _process if you want.

**Link to minimal example project** (optional but very welcome):
http://pasteall.org/pic/show.php?id=106959

**Comment by vnen** [comment]
Still a problem #10175. Sample project: [test.zip](https://github.com/godotengine/godot/files/1209346/test.zip).

**Comment by reduz** [comment]
dang.. now I will have to re-learn how the visual script VM works to fix this bug..

**Comment by akien-mga** [comment]
> dang.. now I will have to re-learn how the visual script VM works to fix this bug..

I hope it's commented :P
