### ISSUE TITLE
When using Find in Files and Replace, Replace does not replace the matched strings immediately, only after an Editor restart

### ISSUE THREAD

**Issue by alfredbaudisch** [godotengine/godot#65834]
### Godot version

4.0-alpha17

### System information

Windows 10

### Issue description

Trying to replace strings with Find in Files does nothing at first:

![ReplaceUseless](https://user-images.githubusercontent.com/248383/190460816-9c1ab170-866b-47e9-b847-c0b423532bdf.gif)

Even if you run the game or Save All, the replacements are not done. But as soon as you close or restart the editor, the replacements are committed. Looks like they get buffered?

### Steps to reproduce

- Create two scripts and save them
- Write something and open Find in Files. Search any string and click Replace...
- Click `Replace all`, nothing happens.
- Close or restart the editor.
- Check the scripts, the replacements are there.

**Comment by Zireael07** [comment]
What happens if you manually open the script instead of clicking in the search results? What happens if you reopen?

**Comment by alfredbaudisch** [comment]
> What happens if you manually open the script instead of clicking in the search results? What happens if you reopen?

Just tried here, same effect (i.e. no replacement made).

**Comment by alfredbaudisch** [comment]
Update on the issue with further information.

**Comment by Calinou** [comment]
I remember seeing a very similar issue reported, but I can't find it right now.
