### ISSUE TITLE
Loop button displays wrong state

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#65849]
### Godot version

c2babb6

### System information

Windows 10 x64

### Issue description

The loop in AnimationPlayer button is 3-state, but it no longer cycles between states. It's either pressed or not pressed and shows wrong icon. E.g. when you press it twice, it changes to pingpong animation, but it will appear non-looping. Icon changes to pingpong after scene reload.
![godot_IYOa51wzjR](https://user-images.githubusercontent.com/2223172/190515139-a3c4275e-051d-490c-afbf-6eb025cda199.gif)

Seems like recent regression.

### Steps to reproduce

1. Add AnimationPlayer
2. Add Animation
3. Click the loop button twice
4. Save
5. Reload the scene
6. Check the loop button

**Comment by gotnospirit** [comment]
https://github.com/godotengine/godot/blob/c2babb65580d4dce3a0fc8834dd05fe177227b6e/editor/animation_track_editor.cpp#L1448-L1457

I think the call to `update_values` should be moved after `undo_redo->commit_action`, so icon & press state of the loop button will be in-sync with the new mode

**Comment by gotnospirit** [comment]
While testing this, I noticed that if you play the animation in ping-pong mode and then change to linear (while playing backward), the animation will keep playing backward

**Comment by TokageItLab** [comment]
I think this is probably due to a change in the timing of icon fetching. CC @YuriSizov

**Comment by YuriSizov** [comment]
If it gets an icon, even if it's a wrong one, that means that the theming is working correctly. That said, theme utilization code in `animation_track_editor.cpp` needs a lot of improvement.

@gotnospirit is mostly correct. The call to update values (which is what changes the icon and the state of the button) is missing from the actual act of changing the loop mode. The UndoRedo action needs to call into this method as well as the other branch does.
