### ISSUE TITLE
Vulkan Mobile: Decal and light Cull Mask is not working

### ISSUE THREAD

**Issue by jcarlosrc** [godotengine/godot#65848]
### Godot version

4.0 Beta 1

### System information

Windows 10

### Issue description

Setting a cull layer does not have any effect when using vulkan mobile. In the minimal project, a decal and a light have cull layer as none. However, both are shown on a box that is at visual layer = 2.

### Steps to reproduce

Set a cull layer to a decal or light.

### Minimal reproduction project

[DecalCull.zip](https://github.com/godotengine/godot/files/9579224/DecalCull.zip)

**Comment by Calinou** [comment]
Can you reproduce this on previous [4.0 alphas](https://downloads.tuxfamily.org/godotengine/4.0/)?

**Comment by jcarlosrc** [comment]
Seems like Alpha 16 and 17 had the same problem.

**Comment by alcomposer** [comment]
DirectionalLight3D Looks like it honours cull layer on mobile vulkan, while Spot & Omni doens't.

[Screencast from 22-10-22 02:06:29.webm](https://user-images.githubusercontent.com/12004932/197234393-82c051b1-c438-403f-a4c8-7b2b40939fd1.webm)
[test_cull_light.zip](https://github.com/godotengine/godot/files/9840459/test_cull_light.zip)

**Comment by jcarlosrc** [comment]
Still valid in Beta 6.

**Comment by clayjohn** [comment]
This may have been fixed for Omni and Spot lights in https://github.com/godotengine/godot/pull/70638

**Comment by Flavelius** [comment]
Decal cull mask doesn't seem to work for me on forward+ either. it get's projected onto everything regardless of the cull mask value (beta 11).
