### ISSUE TITLE
Godot 4.0 Beta 1 HTML Export doesn't run in browser

### ISSUE THREAD

**Issue by QushyQushy** [godotengine/godot#65852]
### Godot version

4.0 Beta 1

### System information

Garuda Linux 5900HX, 6800M with Firefox

### Issue description

Export a game with Godot 4.0 Beta 1 with WebGL Template. It throws this error when tried to run it through Firefox and Chrome on Desktop. Also tried on tablet with Firefox, Chrome and Qwant, same result. The WebGL preview of the Editor launches fine but since I'm using database information for this project hangs as well.

The error in the console is this:

```
Uncaught (in promise) ReferenceError: SharedArrayBuffer is not defined
    Godot https://dev.eligence.eu/puzzle/index.js:9
    Engine https://dev.eligence.eu/puzzle/index.js:626
```

It should be noted that I migrated the project from Godot 3.5.

### Steps to reproduce

Export a game with Godot 4.0 Beta 1 with WebGL Template.
Try to run it on a browser outside of the editor preview.

### Minimal reproduction project

The project is proprietary so I can't share it but if need be I can make a minimal reproduction project.

**Comment by Calinou** [comment]
You need to configure the web server to send the correct headers for HTML5 threads to work: https://docs.godotengine.org/en/latest/tutorials/export/exporting_for_web.html#threads

**Comment by vkbsb** [comment]
@Calinou  isn't threads only required for the GDExtension build? Is this a required feature for web exports now?

**Comment by akien-mga** [comment]
Yes Godot 4.0 requires thread support on all platforms.

**Comment by tripodsan** [comment]
even with enabled `SharedArrayBuffer`, my game just hangs chrome and eventually crashes.
