### ISSUE TITLE
Godot 4.0 Beta 2 - Screen tearing and black screens while using the engine on Wayland

### ISSUE THREAD

**Issue by RaphGL** [godotengine/godot#65856]
### Godot version

4.0 beta

### System information

Fedora 36, NVIDIA GeForce GTX 1050

### Issue description

Screen tearing and black screens:
![image](https://user-images.githubusercontent.com/28673457/190528957-044767a6-372d-4c97-8ee7-db7119df15bf.png)
Every time I'm on the engine itself this occurs, it displays a black screen or there's screen tearing, taking a few seconds to go back to normal and display whatever.

### Steps to reproduce

The issue appears consistently when:
- Opening Godot 4
- Opening dialogs

Sometimes when:
- Resizing the window

**Comment by Calinou** [comment]
Are you using X11 or Wayland? On NVIDIA, Wayland has many known issues and it's recommended to stick to X11.

**Comment by RaphGL** [comment]
@Calinou I'm using Wayland. NVIDIA on Wayland has been working pretty well for me, both steam games and godot 3.5 had no issues whatsoever (using the proprietary nvidia drivers - kmod-nvidia on fedora 36). 

So I enabled Single Window Mode on the editor and restarted the engine, the black screens, screen tearing and slow downs (zooming in and out was very buggy) increased. I logged out and logged back in with Xorg, the issues seem to be mostly solved but when opening up the engine it still shows a black screen for a second or two, after that there's no black screens, but there's still a flicker when a new window is opened (editor settings, playing a scene) for about 2-5 ms there's a black screen before anything else appears

**Comment by RaphGL** [comment]
Hi, so I moved over back to Arch Linux and while the engine does flicker a little bit it's only at opening new windows now and it lasts for half a second and then it pretty much never happens. So the gravity of the bug might be influenced by the nvidia drivers I'm using on Fedora (I had terrible performance every time I plugged my laptop to an HDMI cable for example).

**Comment by RaphGL** [comment]
Beta 2 solved the issue for me

**Comment by xyproto** [comment]
I still have this issue. Tested with 4.0 beta2 on Arch Linux using Sway + Wayland and NVIDIA GTX 1060.

Especially the menus are flickering a lot, every time the mouse is moved over for instance the word that says "Scene".

**Comment by ywmaa** [comment]
Me too, it happens for me on Beta2 
Nobara Project 36 (based on fedora), Wayland, RTX 3070 mobile.
If I switch to xorg session I don't get the issues, only in Wayland.

**Comment by RaphGL** [comment]
this bug doesn't occur anymore, so I will  be closing this issue.
