### ISSUE TITLE
Clicking Add Metadata button in the Inspector crashes Godot

### ISSUE THREAD

**Issue by msvisualization** [godotengine/godot#65855]
### Godot version

Godot_v4.0-beta1_win64.exe [20d667284]

### System information

Windows 10 64-Bit, AMD Ryzen 7 3700X 8-Core Processor 3.60 GHz, GeForce RTX 2070 Super (Driver 516.94), Vulkan

### Issue description

Clicking the Add Metadata button after attaching a new script to a new 2D or 3D node causes an abrupt crash.

### Steps to reproduce

1. Create new project using Vulkan Clustered
2. Create a new 2D or 3D scene
3. Attach a new script with default settings
4. Click Add Metadata button in the Inspector
5. Scene crashes

(This happens with or without saving the scene file before clicking the Add Metadata button)

### Minimal reproduction project

[New Game Project3.zip](https://github.com/godotengine/godot/files/9579606/New.Game.Project3.zip)

**Comment by gotnospirit** [comment]
https://github.com/godotengine/godot/blob/95df3e7c88f4c044a46b45239a3d447a71f05446/editor/editor_inspector.cpp#L4016-L4017

should be
```
add_meta_dialog->set_title(TTR("Add Metadata Property"));
```

**Comment by gotnospirit** [comment]
same problem here
https://github.com/godotengine/godot/blob/95df3e7c88f4c044a46b45239a3d447a71f05446/editor/editor_inspector.cpp#L3990-L3991

**Comment by gotnospirit** [comment]
```
_show_add_meta_dialog OK 'GDScript'
cast KO
```

I would add that the title of the `add_meta_dialog` should be updated in a else block of
https://github.com/godotengine/godot/blob/95df3e7c88f4c044a46b45239a3d447a71f05446/editor/editor_inspector.cpp#L4009
