### ISSUE TITLE
Mouse pan & zoom in the AnimationEditor

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#6585]
Everytime I use the AnimationEditor I'm a bit frustrated that it doens't supports pan & zoom like some other scrollable editors.
It would also be useful to navigate longer/complex animations.
Would it be possible to be able to scroll by holding middle-click and zoom horizontally by using the wheel?

**Comment by vnen** [comment]
If you mean the AnimationPlayer, I'm able to pan with middle-drag. For zoom there's only a slider.

**Comment by Hinsbart** [comment]
And it looks like the wheel is already in use for the vertical scroll here.

![anim_wheel](https://cloud.githubusercontent.com/assets/8281916/18783463/42f555a4-818c-11e6-8474-7b45fecc1227.gif)

**Comment by vnen** [comment]
I'd use <kbd>Ctrl</kbd>+Scroll to zoom, the same as the script editor.

**Comment by Zylann** [comment]
Yeah, given the structure of the widget, it makes sense.
