### ISSUE TITLE
Vulkan Mobile: Fog and Volumetric Fog do not take visual effect

### ISSUE THREAD

**Issue by jcarlosrc** [godotengine/godot#65860]
### Godot version

4.0 Beta 1

### System information

Windows 10

### Issue description

Enabling Fog or Volumetric Fog does not make any visual effect on meshes. Fog makes effect on the sky though. Volumetric Fog does not make effect at all. In the minimal project, both Fog and Volumetric Fog are applied with density = 1, however only Fog makes sky green but neither of them have any effect on meshes.

![Captura de Tela (122)](https://user-images.githubusercontent.com/8985409/190533528-eda083a1-d599-4e8e-8c69-2904f375a940.png)

### Steps to reproduce

Apply fog or volumetric fog to a scene.

### Minimal reproduction project

[Uploading FogBugBeta1.zip…]()

**Comment by clayjohn** [comment]
There are two issues here:
1. We need to document better that Volumetric fog is only supported on the clustered renderer (its mentioned in the [Volumetric fog doc](https://docs.godotengine.org/en/latest/tutorials/3d/volumetric_fog.html), but not in the [Environment class reference](https://docs.godotengine.org/en/latest/classes/class_environment.html))
2. There appears to be a bug with the regular fog in the mobile renderer, it should affect meshes

**Comment by jcarlosrc** [comment]
As an observation, regular fog used to affect only meshes, not skies. So it has an inverted behavior.
