### ISSUE TITLE
[4.0 Beta1 Mono] - Vector2 type is float, but all instances of float in API replaced with double.

### ISSUE THREAD

**Issue by Anixias** [godotengine/godot#65869]
### Godot version

4.0 Beta1 Mono

### System information

Windows 10 64-bit

### Issue description

The underlying type of `Vector2` is `float`, whereas the API has replaced most instances of `float` with `double`. This gives casting errors when using a `Vector2` and, say, `double delta`. Sure, it can be casted, but seems unusual to not have a `double` version of vectors.

### Steps to reproduce

N/A

**Comment by raulsntos** [comment]
Duplicate of https://github.com/godotengine/godot/issues/65313 and https://github.com/godotengine/godot-proposals/issues/5403
