### ISSUE TITLE
Text color of key in Command Palette isn't adjusted

### ISSUE THREAD

**Issue by EXSPIRAVIT1104OFFICIAL** [godotengine/godot#65874]
### Godot version

v4.0.beta1.official [20d667284]

### System information

Windows 10, Vulkan, NVIDIA GeForce RTX 3050 Laptop GPU

### Issue description

The color of the key in the command Palette is still light colored in a light-colored theme, the rest of the editor text is dark colored.
![image](https://user-images.githubusercontent.com/80319225/190538015-b7f057d6-2a06-47dd-8578-79a079dd0550.png)
![image](https://user-images.githubusercontent.com/80319225/190538035-6259044f-f08b-4db9-b32e-bedca865a25e.png)

### Steps to reproduce

set editor theme to 'Light'
go to Command Palette

**Comment by EliasVincent** [comment]
The "Solarized (Light)" theme has the same issue:

![Godot_v4 0-beta1_win64_Y6fCrXYD7O](https://user-images.githubusercontent.com/59402820/190651718-84b25d4a-8f05-42f0-9a71-298ce348c7cb.png)

I looked into it and one thing that stuck out to me in `editor/editor_command_palette.cpp` at line 133 is that the shortcut_text color is just set as pure white, regardless of theme it seems: 

```
Color c = Color(1, 1, 1, 0.5);
```

Changing this to something darker like `Color c = Color(0.4, 0.4, 0,4, 0.5);`, the shortcut text now appears visible with the "Light" theme:

![godot windows tools x86_64_8iHmv4H6w6](https://user-images.githubusercontent.com/59402820/190655308-fd022f24-675e-4e77-a26a-37a900555c8e.png)

So this shortcut_text color should be altered to take a color from the theme.
