### ISSUE TITLE
expose ImmediateGeometry.get_aabb() to gdscript

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#6587]
**Operating system or device - Godot version:**
2.1

**Issue description** (what happened, and what was expected):

I could not find a way to get the AABB of ``ImmediateGeometry``.

In C++ there is a ``ImmediateGeometry.get_aabb()`` which is not exposed to GDscript yet.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by reduz** [comment]
I think it needs to be exposed in GeometryInstance

On Thu, Sep 22, 2016 at 12:35 PM, SuperUserNameMan <notifications@github.com

**Comment by SuperUserNameMan** [comment]
well ... i've created the binding and made some tests, and for unknown reasons, the size of the returned AABB is always 0.

i tested it with an ImmediateGeometry UV sphere.

**Comment by SuperUserNameMan** [comment]
ok, i've found why the returned AABB size was always 0.

It's because the ``empty`` property is never set to false here :
https://github.com/godotengine/godot/blob/master/scene/3d/immediate_geometry.cpp#L72
