### ISSUE TITLE
C#: Cannot export generic Godot.Collections types

### ISSUE THREAD

**Issue by tex111** [godotengine/godot#65883]
### Godot version

4.0 beta1 mono

### System information

windows 10

### Issue description

When I try to export a List<> string property I get a compiler error.

The type of the exported property is not supported: 'SaveData.Notifications'

 (I don't know how to escape <> but it is written properly in code)
[Export()] public List<string> Notifications { get; set; } = new();

### Steps to reproduce

Make a C# resource script. Make a List<> string property that is exported. Build the solution.

**Comment by domportera** [comment]
What kind of compiler error? You should specify in your report

I'm getting a compiler error on a simple enum type I made

`C:\ProjectFolder\Godot.SourceGenerators\Godot.SourceGenerators.ScriptPropertyDefValGenerator\GodotExtensions.ObjectExt_ScriptPropertyDefVal_Generated.cs(13,70): The name 'DebugMode' does not exist in the current context`

**Comment by tex111** [comment]
Understood. Thank you and post is now updated.

**Comment by raulsntos** [comment]
@tex111 `System.Collections.Generic.List<T>` is not a variant type and is, therefore, currently unsupported.

@domportera Your error sounds different from this report, can you open a new issue with a minimal reproduction project?

**Comment by tex111** [comment]
> @tex111 `System.Collections.Generic.List<T>` is not a variant type and is, therefore, currently unsupported.
> 
> @domportera Your error sounds different from this report, can you open a new issue with a minimal reproduction project?

What should we be using instead?

**Comment by tex111** [comment]
> > @tex111 `System.Collections.Generic.List<T>` is not a variant type and is, therefore, currently unsupported.
> 
> What should we be using instead?

**Comment by tex111** [comment]
If I instead use Godot.Collections.Array or Godot.Collections.Dictionary I get this error. 

modules/mono/glue/runtime_interop.cpp:1233 - Attempted to convert an unmarshallable managed type to Variant. Name: 'Godot.Collections.Array`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].

 modules/mono/glue/runtime_interop.cpp:1233 - Attempted to convert an unmarshallable managed type to Variant. Name: 'Godot.Collections.Dictionary`2[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[BaseCharacter, Aether Aeon, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].

So I am unclear on what data structure should be used.

**Comment by raulsntos** [comment]
You should be able to use `Godot.Collections.Array` and `Godot.Collections.Dictionary` just fine. Can you share a minimal reproduction project?

**Comment by tex111** [comment]
[Godot Collections Issue.zip] (https://github.com/godotengine/godot/files/9582875/Godot.Collections.Issue.zip)
Here you go. Run to see the godot collections.

**Comment by tex111** [comment]
After further testing it could be an issue with the connection to the external editor. I am using Jetbrains Rider.

[Godot Collections Issue.zip](https://github.com/godotengine/godot/files/9582936/Godot.Collections.Issue.zip)
When you open the project then open the contained .cs file the unmarshallable managed type errors show up.
