### ISSUE TITLE
[UI] New project window is too big and buttons are off screen

### ISSUE THREAD

**Issue by mohammedzero43** [godotengine/godot#65889]
### Godot version

4.0 beta 1

### System information

Android 11, one plus nord 2

### Issue description

I tried to create a new project with a fresh install of Godot 4.0 beta 1 , but the pop up window was too big on the default screen DP (360 DP)
![20220916_141953](https://user-images.githubusercontent.com/10077145/190618322-865c27ce-2f7b-49b8-ad8c-1af742928328.jpg)

### Steps to reproduce

Try to create a new project in android editor with low DPI (360 in my case)

**Comment by akien-mga** [comment]
I think we need to tweak the "DPI to EDSCALE" logic further, this does look like too big a scale for this device.

Also worth keeping in mind as we refactor the project creation dialog @clayjohn to add even more options.

**Comment by Other-Zone** [comment]
I had the same problem,but i just changed the DP in the developer settings in my phone and it started working normally.I think it would be the same for you if you could try.

**Comment by Musclorman** [comment]
Idem for me.
- google translate -
- Original french text -
Il serait bon de mêttre un acces aux paramêtres de l'éditeur sur l'écran des projet dans toutes les versions ainsi qu'une option pour pouvoir déplacer des fenêtres avec plusieurs doigts sur l'écran et un racourcis clavier manette et souris.

Une option pour forcer GLES2 ou GLES3 avant d'ouvrir un projet serait pas mal ainsi qu'une option pour paramêtrer ou compiler un projet depuis ce même ecran de projets.
La possibilitée de creer des racourcis manettes et claviers midi dans l'editeur et l'ecran de projets serait pas mal aussi.
La compatibilitée avec le MIDI in et out serait bien pour pouvoir creer des applications de création musicales par exemple...
Toutes ces idées concernent Godot en général et pas seulement la version mobile.

-Translate-
It would be good to put access to the editor settings on the project screen in all versions as well as an option to be able to move windows with several fingers on the screen and a keyboard shortcut for joystick and mouse.
An option to force GLES2 or GLES3 before opening a project would be nice, as well as an option to configure or compile a project from this same project screen.
The possibility of creating shortcuts for joysticks and midi keyboards in the editor and the project screen would also be nice.
Compatibility with MIDI in and out would be good to be able to create music creation applications for example...
All of these ideas relate to Godot in general and not just the mobile version.


Bye

**Comment by m4gr3d** [comment]
> I think we need to tweak the "DPI to EDSCALE" logic further, this does look like too big a scale for this device.
> 
> Also worth keeping in mind as we refactor the project creation dialog @clayjohn to add even more options.

I think we need to take into account both the DPI of the device and the its screen size as well. Our screens have a minimum expected screen size, so this may cause us to disable support for devices below a certain threshold.

An alternative is to also look into supporting `portrait` orientation for the editor, but that requires a much more complex rethinking of the editor layout.
