### ISSUE TITLE
Softbody3d attachments offset not correct

### ISSUE THREAD

**Issue by hakuhan** [godotengine/godot#65887]
### Godot version

4.0 beta1

### System information

Windows 10

### Issue description

When creating a softbody plane for a single capsule mesh. Offset of attachments is wrong.

### Steps to reproduce

1. Create CharacterBody3d.
2. Create Softbody3d.
3. Attach softbody3d node to characterBody3d node by pins.
4. Run and test (You should create camera and so on).

### Minimal reproduction project

[SoftbodyIssue.zip](https://github.com/godotengine/godot/files/9582950/SoftbodyIssue.zip)

**Comment by hakuhan** [comment]
Here's the screenshort:
![image](https://user-images.githubusercontent.com/18411187/190615438-f2d8391c-f14e-4052-8d4d-3d4c1a1afae3.png)

**Comment by fire** [comment]
I have some interest debugging this. Need to find a good time.

**Comment by rburing** [comment]
What problem do you see exactly? Please clarify. If you add little `MeshInstance3D` spheres as children of the `CharacterBody3D` node, with their **local** positions set to the offsets which are specified on the `SoftBody3D` node, it seems that the soft body is being pinned correctly:

![softbody3d_pinpoints](https://user-images.githubusercontent.com/229837/190709599-12269eb9-7541-44f2-a2c5-7a9e5440fdfe.png)

This is from my testing on Linux; I don't see any problem with attachment offsets.

**Comment by hakuhan** [comment]
> What problem do you see exactly? Please clarify. If you add little `MeshInstance3D` spheres as children of the `CharacterBody3D` node, with their **local** positions set to the offsets which are specified on the `SoftBody3D` node, it seems that the soft body is being pinned correctly:
> 
> ![softbody3d_pinpoints](https://user-images.githubusercontent.com/229837/190709599-12269eb9-7541-44f2-a2c5-7a9e5440fdfe.png)
> 
> This is from my testing on Linux; I don't see any problem with attachment offsets.

Thanks for your replay! I tested in windows and the pins are just in the center of attachment point. I will test it and report it clarify if it is an issue!

**Comment by hakuhan** [comment]
I cannot reproduce it when I switch a new computer. Yes it acts like what you said @rburing . Yesterday I test this min project at desktop and the attachments offsets are always the same even I regenerate these pins. But it shows correct today. I will test it more at that desktop computer.
![image](https://user-images.githubusercontent.com/18411187/190836396-317646df-be89-46c0-996a-7f2bdf324e2e.png)
