### ISSUE TITLE
Bug with multidimensional arrays of nodes C#

### ISSUE THREAD

**Issue by 4CoDev** [godotengine/godot#65885]
### Godot version

v4.0.beta1.mono.official [4ba934bf3]

### System information

macOS Monterey 12.0.1, M1 Pro

### Issue description

Application does not build when using multidimensional arrays of nodes in C#.
<img width="1174" alt="Снимок экрана 2022-09-16 в 14 54 11" src="https://user-images.githubusercontent.com/95243328/190613505-1904c580-46fb-49b9-a9fe-6230a5c9d994.png">
<img width="502" alt="Снимок экрана 2022-09-16 в 14 54 21" src="https://user-images.githubusercontent.com/95243328/190613524-31228f50-ae97-4820-9c49-7f398d48a576.png">

### Steps to reproduce

Just create a multidimensional array of nodes in C#

### Minimal reproduction project

[ArrayOfNodesCS.zip](https://github.com/godotengine/godot/files/9582937/ArrayOfNodesCS.zip)

**Comment by antonWetzel** [comment]
The current source generators ignore the rank of CSharp arrays. A possible workaround is ` Godot.Collections.Array<Godot.Collections.Array<Node>>`, but some nice properties of 2d arrays are lost.

Notes
- `Node[][]` crashes the source generator
- Disabling multidimensional arrays in the source generator is easy, but interoperability is not possible
- Adding multidimensional arrays to the source generators is very hard.

**Comment by Xyotic** [comment]
Ran into the same issue. What impact does #65946 have on existing projects?
Will this just "fix" the issue or are there certain limitations on how we can use multidimensional arrays of nodes in godot4?

**Comment by antonWetzel** [comment]
(I think) The generated code is used for interaction with the engine and gdscript (`[Export]`, `set_defered`, ...), you can use multidimensional arrays as much as you like in csharp-land.
