### ISSUE TITLE
Kinematicbody node missing ?

### ISSUE THREAD

**Issue by JetDev162** [godotengine/godot#65893]
### Godot version

4.0 beta

### System information

windows 10 Vulcan Clustered and Vulcan Mobile

### Issue description

No Kinematicbody2d or 3d nodes ?
I cant create a 3d caractor without ?

### Steps to reproduce

Create Kinematic node there is none

**Comment by Ghashy** [comment]
Hello) there is CharacterBody node instead now

**Comment by akien-mga** [comment]
This is covered in the 4.0 beta 1 blog post, please read it in detail before opening bug reports: https://godotengine.org/article/dev-snapshot-godot-4-0-beta-1

This GitHub tracker is for well-defined bug reports and not for general questions - you can ask this e.g. in the #godot4 channel on Discord and you'll also get an immediate answer without notifying all contributors :)
