### ISSUE TITLE
Godot4 using > 80% of the CPU when moving a directional light

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#65894]
### Godot version

Beta 1

### System information

MacBook Pro (13-inch, 2019) 2.4 GHz Quad-Core Intel Core i5

### Issue description

When starting a blank project in the new Godot4 beta I see >80% of the CPU being used at all times.

The godot editor also frequently becomes unresponsive, showing as `Not responding` in the task manager.

### Steps to reproduce

1. Open a blank project in Godot beta 4 (1st beta)
2. Add a directional light
3. Move the directional light every frame

### Minimal reproduction project

[godot_directional_light.zip](https://github.com/godotengine/godot/files/9591697/godot_directional_light.zip)

```gdscript
extends DirectionalLight3D

func _process(delta):
	var amount = delta / 4
	self.rotation.y += amount
```

**Comment by tavurth** [comment]
<img width="1440" alt="Screenshot 2022-09-16 at 13 19 09" src="https://user-images.githubusercontent.com/100964/190635970-bd822cac-871c-4c87-8e99-66f73a78ffc9.png">
<img width="1440" alt="Screenshot 2022-09-16 at 15 34 14" src="https://user-images.githubusercontent.com/100964/190636058-a7f52533-b3d8-4041-9b1c-567619261226.png">

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/64708.

**Comment by tavurth** [comment]
> Related to #64708.

Could be but in the above comment I have a screenshot showing the godot window unobstructed in the foreground 🤔

**Comment by tavurth** [comment]
Hmm I tried to build godot 4 to check this in a profiler but then I created a new project and the issue disappeared.

The original project I opened was actually the one referenced in this issue: https://github.com/godotengine/godot/issues/53969

So this issue still persists, but it seems now it has become a CPU bound operation.

**Comment by tavurth** [comment]
[godot_directional_light.zip](https://github.com/godotengine/godot/files/9591697/godot_directional_light.zip)

This is the project which causes the CPU drop @bruvzg

**Comment by tavurth** [comment]
@Calinou is this expecting too much from the renderer? 

We are moving the directional light every frame after all 🤔

**Comment by Calinou** [comment]
> We are moving the directional light every frame after all thinking

Yes, this should be avoided when possible. AAA games that feature day/night cycles will generally move the light only 20 times per cycle or so, snapping between increments every so often (with a small period of continuous transition).

**Comment by bruvzg** [comment]
> [godot_directional_light.zip](https://github.com/godotengine/godot/files/9591697/godot_directional_light.zip)
>
> This is the project which causes the CPU drop

It's the same, 7-8% on M1 mac, probably it's an issue with a older Intel GPUs.

**Comment by clayjohn** [comment]
@tavurth How is your performance when using the realtime update mode? When updating every single frame the realtime update mode is likely a better option than then automatic mode. In either case though, updating the sky every frame on a low powered integrated GPU is probably going to consume a large portion of your frame budget. I recommend setting the DirectionaLight3D's ``sky_mode`` to ``LIGHT_ONLY`` so that the sky is not updated every frame along with the sun.

**Comment by tavurth** [comment]
Ok this is weird but I now have around 18% CPU usage in the same scene.

The only thing I've changed is renaming the folder.

Could it be that Godot4 is somehow re-using the cached shaders from the previous Godot3 version?

Renaming the folder back does not bring back the CPU usage however.

I will close this for now as sadly non-reproducible 🤷
