### ISSUE TITLE
No obvious way to erase while painting tileset terrains

### ISSUE THREAD

**Issue by Dizeeee** [godotengine/godot#65904]
### Godot version

4.0 Beta 1

### System information

Windows 10, Ryzen 5900x, Nvidia GTX 1080ti

### Issue description

The tileset terrain painter doesn't provide an obvious way to erase changes. I would expect either right clicking or a dedicated erase button at the top of the tileset editor to fill this role.

![image](https://user-images.githubusercontent.com/17105387/190663308-9c573845-c240-448c-9361-edfe3e7b1a98.png)

### Steps to reproduce

.

**Comment by KoBeWi** [comment]
This applies to all TileSet data editors.

**Comment by KoBeWi** [comment]
Ah I misunderstood that proposal.
This is being implemented by https://github.com/godotengine/godot/pull/65903

**Comment by akien-mga** [comment]
Fixed by #65903.
