### ISSUE TITLE
Godot is not compatible with OpenGL 2.1, but it should be compatible

### ISSUE THREAD

**Issue by zaps166** [godotengine/godot#6591]
**Operating system or device - Godot version:**

Godot 2.1 official / custom build from GIT; Windows 7; old Intel graphics which supports OpenGL 2.1:
```
Mobile Intel(R) 4 Series Express Chipset Family from Intel
OpenGL version 2.1.0 - Build 8.15.10.2869 is supported
```

It doesn't work also on VirtualBox drivers.

**Issue description** (what happened, and what was expected):

- Current behavior: Godot crashes at startup without any useful information.

- Expected behavior: Godot runs on this platform, because it can run there. Otherwise show information about incompatible OpenGL driver and close without crash.

**Steps to reproduce:**

Run Godot and expect crash on OpenGL 2.1 on Windows.

**Additional information:**

On Linux and Mesa OpenGL 2.1 drivers - Godot works properly (on the same hardware), because Mesa is new and Mesa is cheating :)

As far I found 11 function which are compatible with GLES 2.0 and OpenGL 3.0 (not OpenGL 2.1):
- `glGenFramebuffers`,
- `glGenerateMipmap`,
- `glGenRenderbuffers`,
- `glBindRenderbuffer`,
- `glBindFramebuffer`,
- `glCheckFramebufferStatus`,
- `glDeleteRenderbuffers `,
- `glDeleteFramebuffers`,
- `glFramebufferTexture2D`,
- `glRenderbufferStorage`,
- `glFramebufferRenderbuffer`.

Every function listed above are supported with "EXT" suffix (e.g. `glGenerateMipmapEXT`). Replacing it in `rasterizer_gles2.cpp` allows Godot to run and play/edit 2D game on old Intel driver (VirtualBox shows white window and GLSL link error in console, but doesn't crash).

Godot should use functions with `EXT` suffix for OpenGL < 3.0 and it should check every pointer on initialization (instead of checking the OpenGL version).

**Comment by Calinou** [comment]
I don't think it's worth supporting such old graphics chipsets (which perform *very* poorly), especially since we're moving forward with Godot 3.0's renderer (based on GLES 3.0, even though GLES 2.0 will be kept too but not really maintained).

You might have better luck on Linux by the way; those chipsets tend to have newer OpenGL there.

**Comment by SuperUserNameMan** [comment]
well, at least it should display [the warning dialog box ](https://github.com/godotengine/godot/pull/5909)before crashing.

we should also test for this 9 functions individually.

**Comment by zaps166** [comment]
@SuperUserNameMan 
Of course replacing with `EXT` prefix is very bad and it won't compile or it won't work properly on good new drivers (this was only for testing purpose), but I'll try to do:

```c++
if (!glGenFramebuffers)
    glGenFramebuffers = glGenFramebuffersEXT;
```

or just check GL extensions and assign correct pointer.

Also here https://github.com/godotengine/godot/pull/5909 is is good to check all pointers which are not from OpenGL 1.0 instead of checking version only :)

**Comment by SuperUserNameMan** [comment]
I've made a patch here :
https://github.com/SuperUserNameMan/godot/commit/5bc1d73c19b950f7b072847ad5fec2d3460c47b5

could you test it ?

**Comment by zaps166** [comment]
@SuperUserNameMan Doesn't work, still crash (but properly detects it)... Maybe pointers are assigned later in other function?

**Comment by zaps166** [comment]
Aaah, I forgot about `glBindFramebuffer`, sorry (also added to first post) :)

**Comment by SuperUserNameMan** [comment]
and does it work when you add it ?

**Comment by zaps166** [comment]
Also `glDeleteFramebuffers`, I forgot to note every function I've checked, so I'm still investigating, sorry (linking is very slow, I don't know why it is so slow on Windows...) :)

**Comment by SuperUserNameMan** [comment]
it's my fault too, i did not add all the functions listed into the extension spec, and I should have been more carefull.

**Comment by SuperUserNameMan** [comment]
In case one more is missing, here is the full list :
````
			glIsRenderbuffer = glIsRenderbufferEXT;
			glBindRenderbuffer = glBindRenderbufferEXT;
			glDeleteRenderbuffers = glDeleteRenderbuffersEXT;
			glGenRenderbuffers = glGenRenderbuffersEXT;
			glRenderbufferStorage = glRenderbufferStorageEXT;
			glGetRenderbufferParameteriv = glGetRenderbufferParameterivEXT;
			glIsFramebuffer = glIsFramebufferEXT;
			glBindFramebuffer = glBindFramebufferEXT;
			glDeleteFramebuffers = glDeleteFramebuffersEXT;
			glGenFramebuffers = glGenFramebuffersEXT;
			glCheckFramebufferStatus = glCheckFramebufferStatusEXT;
			glFramebufferTexture1D = glFramebufferTexture1DEXT;
			glFramebufferTexture2D = glFramebufferTexture2DEXT;
			glFramebufferTexture3D = glFramebufferTexture3DEXT;
			glFramebufferRenderbuffer = glFramebufferRenderbufferEXT;
			glGetFramebufferAttachmentParameteriv = glGetFramebufferAttachmentParameterivEXT;
			glGenerateMipmap = glGenerateMipmapEXT;
````

**Comment by zaps166** [comment]
Adding both: `glBindFramebuffer` and `glDeleteFramebuffers` works.

So it is a good idea to replace all pointers even if are not used in sources :)

**Comment by SuperUserNameMan** [comment]
cool ! 
I'll update the PR then :)

**Comment by zaps166** [comment]
:+1: 

`also, Godot should not segfault anymore when incompatible video drivers
are detected.` - maybe remove the "TODO" comment from sources?

**Comment by zaps166** [comment]
Btw. the "- " prefix looks weird in console output: ` WARN_PRINT("- `, `exit(1)` works properly for me (doesn't crash).

**Comment by SuperUserNameMan** [comment]
ok, i'll update it that way too

**Comment by zaps166** [comment]
Ok, I'll check on real hardware (old Intel), currently checked on VirtualBox only

**Comment by SuperUserNameMan** [comment]
here is the new link (i thought it would be updated but was not) :
https://github.com/SuperUserNameMan/godot/commit/9d072770894ace0d4c325f47c5d1b7fc86c43d94

**Comment by zaps166** [comment]
Works properly :)

But I've got crash on Intel on `3d/platformer` demo (`2d/platformer` works). Investigating (not my notebook, so it can take some time :) ). Crashes in ` RasterizerGLES2::_process_hdr()`.

About VirtualBox: this might be only VirtualBox GLSL bug, but I've got only white screen and GLSL link error:
```
ERROR: ShaderGLES2::get_current_version: CanvasShaderGLES2: Program LINK FAILED:
Vertex info
-----------
(94) : error C5145: must write to gl_Position
```

**Comment by SuperUserNameMan** [comment]
yeah, maybe there are some other opengl extensions that are not well supported or which has some limitations :-/

**Comment by zaps166** [comment]
Yeah. Currently I've got only disassembly screenshot from QtCreator via CDB debugger (not my notebook) :smile: , it looks like `framebuffer.luminance[0]` is `nullptr`, so now just find where the array is initialized and which OpenGL feature is missing.

**Comment by zaps166** [comment]
Adding:
```c++
        if (framebuffer.luminance.empty()) {
            return;
        }
```
at the beginning of `RasterizerGLES2::_process_hdr()` (https://github.com/SuperUserNameMan/godot/blob/9d072770894ace0d4c325f47c5d1b7fc86c43d94/drivers/gles2/rasterizer_gles2.cpp#L7020) fixes the crash, but lighting is incorrect - driver doesn't support it (https://github.com/SuperUserNameMan/godot/blob/9d072770894ace0d4c325f47c5d1b7fc86c43d94/drivers/gles2/rasterizer_gles2.cpp#L10672), so the array is empty.

This condition should be enough for the patch :)

**Comment by SuperUserNameMan** [comment]
I'm wondering if it could not be depending on the ``format_luminance`` ([here](https://github.com/SuperUserNameMan/godot/blob/9d072770894ace0d4c325f47c5d1b7fc86c43d94/drivers/gles2/rasterizer_gles2.cpp#L10508)) which is set to ``_GL_RG_EXT`` by default.

GL_RG_EXT depends on the ``GL_ARB_texture_rg`` extension which is based on OpenGL 2.1 and standard in OpenGL 3.0.

It is possible to set ``format_luminance`` to ``GL_RGBA`` from the Editor Project Settings by setting ``Rasterizer / fp16_framebuffer`` to false.

Maybe could you test it again and see if ``framebuffer.luminance[0]`` is still a problem when ``format_luminance`` is set to GL_RGBA ?

**Comment by leezh** [comment]
@zaps166 The writing to `gl_Position` used to be a requirement in older GLSL versions. See this: https://github.com/mattdesl/lwjgl-basics/wiki/GLSL-Versions

**Comment by zaps166** [comment]
@leezh I've printed the shader into `cmd` and I've seen that Godot uses `gl_Position = something`, but this is not the last line in `void main()` procedure (maybe VirtualBox needs to have it at last line?). Shader works properly on old Intel, but doesn't work on VirtualBox.

@SuperUserNameMan Ok, I'll test it!

**Comment by zaps166** [comment]
@SuperUserNameMan I have already patched Godot on this device, but changing `fp16_framebuffer` to `false` doesn't fix bugs in lighting in `3d/platfomer`, so probably without the condition it will crash.

**Comment by SuperUserNameMan** [comment]
@zaps166 : well, there is no emergency if you need more time to test if it would actually crash.
Maybe the lighting bug is not related ?
I wish i had a similar device to make deeper compatibility :-/
When you'll be satisfied with the patch, feel free to submit a PR to Godot if you want :)

@zaps166 : nice finding !
We can also check the GLSL version with GLEW i think.

**Comment by zaps166** [comment]
@leezh The shader which fails on VirtualBox has declarated `#version 120` and contains `gl_Position = projection_matrix * outvec;` in `main()`, hmm...

@SuperUserNameMan 

> I wish i had a similar device to make deeper compatibility tests :-/

You can use VirtualBox :) I also don't have the old Intel, but I can use someone else's computer for testing :smile:

> Maybe the lighting bug is not related ?

Lighting bug is only when I use check for empty array https://github.com/godotengine/godot/issues/6591#issuecomment-249280869; otherwise it crashes, because code here https://github.com/SuperUserNameMan/godot/blob/9d072770894ace0d4c325f47c5d1b7fc86c43d94/drivers/gles2/rasterizer_gles2.cpp#L10672 prevents adding non-working framebuffers to Vector<> (tested on `3d/platformer`, `2d/platformer` works fine).

**Comment by zaps166** [comment]
I know why it doesn't work on VirtualBox :smile: Shader source must be passed as one big string instead of string array (probably VirtualBox can see only first string). I think I should create a separate PR which will fix it, right?

**Comment by zaps166** [comment]
![platformer3d_virtualbox](https://cloud.githubusercontent.com/assets/6239090/18802974/acc8708c-81ec-11e6-9782-06e33bb74a1c.png)

- Platformer 2D works fine on both: VirtualBox and Intel.
- Platformer 3D on VirtualBox: geometry is corrupted.
- Platformer 3D on old Intel: bad lighting, but correct geometry.

Editor also works fine (2D).

@SuperUserNameMan 

> When you'll be satisfied with the patch, feel free to submit a PR to Godot if you want :)

Ok, thanks for your help, I'll use your patch :) But is it better to create one big PR or two: for crash fix and for VirtualBox shader fix?

**Comment by zaps166** [comment]
Here is a complete patch (with still broken 3D, but I don't know how to fix - no errors in console): https://github.com/zaps166/godot/commit/88d8a94a00394cdbba73911dc70334a59ea8467d

If it works properly on modern hardware/drivers (no regressions) then I'll create a PR :)

**Comment by SuperUserNameMan** [comment]
Well, actually, I think we should make four PR :
1) one for the #include <cstdlib> and exit(1) patch 
2) one for the ARB_framebuffer_object extension fallback patch
3) one for the framebuffer.luminance.empty() patch
4) one for the shader fix for virtualbox patch

This way, the devteam would be able to revert only the patch that causes a problem if a problem is found later.

I will try test your complete patch on my Radeon R4 later today.
( and i will try to make some room on my harddrive for virtual machine too)

**Comment by SuperUserNameMan** [comment]
well, the patch for vbox shaders makes godot crash here.

**Comment by zaps166** [comment]
Could you pase a backtrace ? The `-1` value is correct according to OpenGL docs...

**Comment by SuperUserNameMan** [comment]
I recompiled it after a ``scons -c``.
It still crash but I can't get a backtrace.
When I run it from the VisualCode debugger, among the list of useless information there is a :
``Exception thrown at 0x000000005CBF90A6 (atio6axx.dll) in godot.windows.opt.tools.64.exe: 0xC0000005: Access violation reading location 0x00007FF644243000.``

**Comment by zaps166** [comment]
Hmm, I can't test it now...

You can do two things:
1. Check before every `glShaderSource()` if `lengths.size() == strings.size()`,
2. In first `for` loop replace `-1` by `strlen(strings[i])`; second `for` loop replace by a first `for` loop, but clear `lengths` array before.

Does first or second point help with crash?

**Comment by SuperUserNameMan** [comment]
Well, it took me some time because i've found an other bug that must be related to some uninitialized memory. (i will have to look at it more carefully) :
````
ERROR: ShaderGLES2::set_custom_uniform: Index p_idx out of size (version->custom_uniform_locations.size()).
   At: .\drivers/gles2/shader_gles2.h:329
ERROR: ShaderGLES2::get_custom_uniform_location: Index p_idx out of size (version->custom_uniform_locations.size()).
   At: .\drivers/gles2/shader_gles2.h:336
````

So, here is what prevents the crash on my system :
(but this trigger the uninitialized memory bug sometimes)

- replace ``-1`` by ``(int)strlen(strings[i])`` into both ``for`` loops
- and add a ``lengths.clear();`` before the second ``for`` loop

**Comment by SuperUserNameMan** [comment]
so i confirm that this modification randomly trigger the bug i mentioned. When it happen, the console is flooded with this two ERROR messages.

**Comment by zaps166** [comment]
I've tested this only on VirtualBox (and once on Wine) so far, but with 2.1-stable version.

Maybe create three PRs and the fourth for VBox can wait ? I wanted to use `-1`, because it is correct according to OpenGL docs, because it is a little faster than finding string length via `strlen()`.

**Comment by zaps166** [comment]
Three commits for three main PRs:
- https://github.com/zaps166/godot/commit/a27fafb2736a530a8a04f887dd8d6e67da3d8972
- https://github.com/zaps166/godot/commit/ca3b8deb7860eb54c2b5ef44eb686799a688febc
- https://github.com/zaps166/godot/commit/7b8fe97888dc1d9586d443498281df532ec1db3a

@SuperUserNameMan Are the three commits OK ? :)

And this is not finished yet: https://github.com/zaps166/godot/commits/virtualbox-glsl-workaround

**Comment by SuperUserNameMan** [comment]
@zaps166 : yep, they look ok to me.

And about the last unfinished PR, I don't understand me neither why ``-1`` does not work properly with my Radeon R7. Maybe it is a bug in AMD graphics driver ... It will need further investigation.

**Comment by zaps166** [comment]
@SuperUserNameMan 

So, I will do three PRs :)

I'll also check `-1` on real Windows with NVIDIA drivers when I reboot. I think that Radeon R7 is more important that VirtualBox :smile: So maybe check driver name before doing it or just use `strlen()`...

**Comment by SuperUserNameMan** [comment]
yes, thought let's keep in mind that when ``-1`` is replaced by ``strlen()``, it randomly triggers the error I mentioned on my Radeon.

So, the TODO list for further compatibility improvement is :

- [ ] investigate why ``glShaderSource()`` crashes on Radeon R7 when ``length`` parameter is an array that contain ``-1`` values.
- [ ] investigate why replacing this ``-1`` with actual string lengths randomly triggers "``ERROR: ShaderGLES2::set_custom_uniform: Index p_idx out of size``"
- [ ] check if [``GL_ARB_texture_rg``](https://www.opengl.org/registry/specs/ARB/texture_rg.txt) is supported, and create a fallback to replace ``_GL_EXT_RG`` with something compatible (like ``GL_RGBA`` maybe).
- [ ] find others opengl extensions used in Godot that go beyond opengl 2.1 minimum requirement, and implement fallbacks when possible, or at least prevent crash

**Comment by zaps166** [comment]
> yes, thought let's keep in mind that when -1 is replaced by strlen(), it randomly triggers the error I mentioned on my Radeon.

Right, I forgot :)

---

Also check (if possible) why [3D geometry and texturing](https://cloud.githubusercontent.com/assets/6239090/18802974/acc8708c-81ec-11e6-9782-06e33bb74a1c.png) is corrupted using VirtualBox.

**Comment by akien-mga** [comment]
Awesome work guys! :)

**Comment by Algrin6** [comment]
To make texturing working, you may turn off "Rasterizer / fragment_lighting".

**Comment by techtonik** [comment]
Awesome, indeed. But I guess ANGLE support would cure more bugs and pave a road to backward compatibility for Godot 3.x

**Comment by flamendless** [comment]
Is this opengl 2 compatibility fixed now in latest godot build?

**Comment by zaniar** [comment]
@flamendless OpenGL 2 planned to be back in Godot 3.1

**Comment by vnen** [comment]
@flamendless this is a place to report bugs, and this one in particular is already solved. If you have questions you can ask in one of our [community channels](https://godotengine.org/community).
