### ISSUE TITLE
Cannot export array of files or directories

### ISSUE THREAD

**Issue by DasCapschen** [godotengine/godot#65925]
### Godot version

4.0 beta 1

### System information

Linux

### Issue description

It is not possible anymore to export Arrays of files or directories.

In Godot 3, you could write:
```gdscript
export (Array, String, DIR) var my_dir_array: Array = []
export (Array, String, FILE, "*.tscn,*.scn") var my_file_array: Array = []
```

In Godot 4, you can either export a string array, or a file/dir, but not an array of files/dirs.
```gdscript
@export_file("*.tscn,*.scn") var my_file: String = ""
@export_dir var my_dir: String = ""
@export var my_dir_array: Array[String] = []   # inspector does not show file / dir selector
@export_file var my_file_array: Array[String] = []   # Error: "export_file annotation requires variable of type String"
```

### Steps to reproduce

1. Create a script
2. `@export_file var my_file_array: Array[String] = []`
3. Error: "export_file annotation requires variable of type String"
4. `@export var my_file_array: Array[String] = []`
5. Inspector does not show file picker for array elements

**Comment by theraot** [comment]
I have an `EditorPlugin` that generates scripts based on the contents of folders. The paths it will work on are an exported array `(Array, String, DIR)`.

*I open the `EditorPlugin` in the inspector by a tool menu item (`add_tool_menu_item`) which selects the `EditorPlugin`, and I save the configuration to an extra category on the `plugin.cfg` file.*

This is being a roadblock upgrading my code to Godot 4. And I consider it a regression from Godot 3.5.

**Comment by theraot** [comment]
This is the workaround. This code:

```
export(Array, String, DIR) var my_dir_array:Array
```

Becomes this code:

```
var my_dir_array:Array[String]

func _get_property_list() -> Array:
	return [
		{
			"name": "resource_folders",
			"type": TYPE_ARRAY,
			"hint": PROPERTY_HINT_TYPE_STRING,
			"hint_string": str(TYPE_STRING) + "/" + str(PROPERTY_HINT_GLOBAL_DIR) + ":",
			"usage": PROPERTY_USAGE_SCRIPT_VARIABLE | PROPERTY_USAGE_DEFAULT
		}
	]
```

*Actually for my code I use `PROPERTY_HINT_DIR` instead of `PROPERTY_HINT_GLOBAL_DIR` and I don't put `[String]` on the `Array` because of the way I serialize it.*

**Comment by electricsheap** [comment]
A way to accomplish this without requiring tool scripting would be preferable. Perhaps an @export_array with some sort of type hint? 
Regardless, _get_property_list is always an option.

**Comment by donato21** [comment]
This issue has made itself apparent to me just now. My use-case is rather simplistic, I wanted to add scene file paths to a node in the editor from which it will randomly select one to initialize. Any updates on this?

**Comment by theraot** [comment]
It could be `@export_files` and `@export_dirs`, covering the most common case of an array of files or directories, and you can still use `_get_property_list` if you need an array of arrays of files or directories.

**Comment by dalexeev** [comment]
* See also godotengine/godot-proposals#8005.
