### ISSUE TITLE
C#: Can't cast Variant to Interface

### ISSUE THREAD

**Issue by Xyotic** [godotengine/godot#65926]
### Godot version

v4.0.beta.1.mono.official[4ba934bf3]

### System information

Windows10, Vulkan, RTX2080

### Issue description

It isn't possible to cast from Variant to an Interface.

I run into this issue while converting my project from Godot3 to 4.
Im putting objects inside metadata with "SetMeta()" to get them back with "GetMeta()" while raycasting.
GetMeta() now returns Variant instead of Object, which could be casted back into an interface.
Now this isn't possible anymore...

Is there a way to fix this? Or does a workaround already exist?

### Steps to reproduce

Create a class that inherits like this:
```cs
public partial class MyClass : Node3D, IMyInterface { }
```
Try casting it like this:
```cs
Variant myVariant = new  MyClass();
ISelectable selectable = (ISelectable)myVariant; //this will throw an error
```

**Comment by antonWetzel** [comment]
`Variant` is the container for the data with extra info, it is not an instance of `MyClass`, `Resource`, ...
With `<variant>.AsGodotObject` you get the instance (`Godot.Object`), which is a base class of `MyClass` and can be casted.

**Comment by Xyotic** [comment]
Thanks! I didn't know this was an option.
I will try using your suggested method.

**Comment by Xyotic** [comment]
Just verified this. ".AsGodotObject()" works as expected.
I also noticed you can use ".Obj" as an alternative too.

Closing this issue since casting directly form variant probably wont be possible nor is it required.
