### ISSUE TITLE
GPU particles draw_pass error

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#65930]
### Godot version

4.0-beta1

### System information

Zorin OS-16, Intel hd 5500HD

### Issue description

Error thrown when using GPU particles and assigning a mesh to the draw_pass. CPU particles doesn't seem to have this issue.
`servers/rendering/renderer_rd/storage_rd/mesh_storage.cpp:1291 - Condition "!multimesh" is true.`

### Steps to reproduce

using GPU particles, assign a mesh to the draw_pass property.

**Comment by Calinou** [comment]
@vonflyhighace2 Did you find a solution to this problem? If so, please document it here by commenting :slightly_smiling_face:

**Comment by vonflyhighace2** [comment]
@Calinou  Sorry. I forgot to leave a reason for the closer. Seems that there was already a report about this and a possible fix as we. View #65833 for more.
