### ISSUE TITLE
Unable to build mono-glue on Godot 4 beta

### ISSUE THREAD

**Issue by mgrigajtis** [godotengine/godot#65936]
### Godot version

Godot Engine v4.0.beta.mono.custom_build (57bdddce02370af3d13e6edc583afdc17264147d)

### System information

Windows 11 Vulkan API 1.2.0 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3060 Ti

### Issue description

Errors are generated when attempting to build mono-glue:

ERROR: hostfxr_initialize_for_runtime_config failed with code: -2147450733
   at: (modules\mono\mono_gd\gd_mono.cpp:201)
ERROR: Parameter "load_assembly_and_get_function_pointer" is null.
   at: `anonymous-namespace'::initialize_hostfxr_and_godot_plugins (modules\mono\mono_gd\gd_mono.cpp:274)
ERROR: Parameter "godot_plugins_initialize" is null.
   at: GDMono::initialize (modules\mono\mono_gd\gd_mono.cpp:403)
Editing project: D:/Godot 4 Projects/Test Scene

Godot Engine v4.0.beta.mono.custom_build.57bdddce0 - https://godotengine.org
ERROR: Condition "!windows.has(p_window)" is true.
   at: VulkanContext::window_resize (drivers\vulkan\vulkan_context.cpp:1497)
Vulkan API 1.2.0 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3060 Ti

ERROR: hostfxr_initialize_for_runtime_config failed with code: -2147450733
   at: (modules\mono\mono_gd\gd_mono.cpp:201)
ERROR: Parameter "load_assembly_and_get_function_pointer" is null.
   at: `anonymous-namespace'::initialize_hostfxr_and_godot_plugins (modules\mono\mono_gd\gd_mono.cpp:274)
ERROR: Parameter "godot_plugins_initialize" is null.
   at: GDMono::initialize (modules\mono\mono_gd\gd_mono.cpp:403)

### Steps to reproduce

scons p=<platform> tools=yes module_mono_enabled=yes mono_glue=no
<godot_binary> --generate-mono-glue modules/mono/glue

**Comment by raulsntos** [comment]
Make sure you have installed the .NET SDK 6.0+. Can you check which SDK version and runtimes you have available by executing `dotnet --info` in a console?

**Comment by bitmammoth** [comment]
Is there documentation somewhere on building export templates with this new method? Do we use the old method minus the deprecated commands?

**Comment by raulsntos** [comment]
The commands have changed a bit recently (see more information about these changes in https://github.com/godotengine/godot/pull/66242), these would be the commands to build the editor now:

```
scons p=windows target=editor module_mono_enabled=yes
bin/godot.windows.editor.x86_64.mono --generate-mono-glue modules/mono/glue
python ./modules/mono/build_scripts/build_assemblies.py --godot-output-dir ./bin --push-nupkgs-local ~/MyLocalNugetSource
```

To build the export templates:

```
scons p=windows target=template_debug module_mono_enabled=yes
scons p=windows target=template_release module_mono_enabled=yes
```
