### ISSUE TITLE
gridmap does not hide()

### ISSUE THREAD

**Issue by jminix** [godotengine/godot#6594]
windows 10 godot 2.1 64 bit

**Issue description** (what happened, and what was expected):

when I call the hide() on a grid map, it does not disappear like it should

**Steps to reproduce:**

Add any gridmap to a scene.  Give it a script and under _ready() type hide().
upon playing the scene it is still visible.  Also in editor, if you unselect "visible" the gridmap does not go away.

**Comment by SuperUserNameMan** [comment]
unfortunately, it's a old bug #907

**Comment by jminix** [comment]
Good to know it will eventually be fixed //fingers crossed :-)

**Comment by kubecz3k** [comment]
closing as a duplicate of #907
