### ISSUE TITLE
Failing to get RPC configuration for remote function

### ISSUE THREAD

**Issue by Tompparella** [godotengine/godot#65948]
### Godot version

4.0-beta1_win64

### System information

Windows 10

### Issue description

When attempting to trigger an RPC call on a separately defined multiplayer instance remotely on a client scenetree, the console throws the following error (the rpc call also doesn't trigger the function):

E 0:00:00:0883   _OnConnectionSucceeded: Unable to get the RPC configuration for the function "test" at path: "/root/Authenticate". This happens when the method is missing or not marked for RPCs in the local script.
  <C++ Error>    Condition "rpc_id == 65535" is true. Returning: ERR_INVALID_PARAMETER
  <C++ Source>   modules/multiplayer/scene_rpc_interface.cpp:468 @ rpcp()
  <Stack Trace>  Authenticate.gd:21 @ _OnConnectionSucceeded()

The client and server scripts are both autoloaded, but I've tried them on specific Node instances as well.
The test function is specified with @rpc(any_peer), but I've also tried @rpc(call_remote, any_peer/authority).
I've been stuck on this for the whole evening and I'm fairly sure this can be attributed as a bug on the beta build.

### Steps to reproduce

1. Create a simple client multiplayer instance (ENetMultiplayerPeer.create_client) as well as a server (ENetMultiplayerPeer.create_server) and connect the client to the server (client + server: multiplayer.set_multiplayer_peer)
2. Confirm successful connection with a signal (network.connection_succeeded)
3. Trigger a test rpc call on the server from the client
 - Server: @rpc(any_peer) func test() -> void:
     print("RPC triggered")
 - Client: rpc_id(1, "test")

On the reproduction project:
1. Start server
2. Start client

Expected result:
 - Server prints "RPC triggered" to its console
Actual result:
 - Client throws the forementioned error and fails to trigger the print function

### Minimal reproduction project

[rpc_bug_reproduction.zip](https://github.com/godotengine/godot/files/9590386/rpc_bug_reproduction.zip)

**Comment by gotnospirit** [comment]
Adding the `@rpc` to `client.Test` make it works, but then there's an path error on the server-side.
Adding the `api` lines to `client` class (same as in server), solved this error

**Comment by Faless** [comment]
As explained by @gotnospirit : 
- Add `@rpc(call_remote, any_peer)` to the Test function in `client.gd`
- Add `get_tree().set_multiplayer(MultiplayerAPI.create_default_interface(), get_path())` to the client too so it works in a branch like the server.

**Comment by Tompparella** [comment]
Thank you both! This helped alot.

**Comment by Tompparella** [comment]
Unfortunately, this still doesn't work as supposed to for me. I have a gateway system set up with the client first making a login request to the gateway server, which then forwards the request for the authentication server. The problem is communication between the gateway and authentication. When the gateway sends a request to the authentication server, the following error is printed:

E 0:00:09:0713   process_confirm_path: The rpc node checksum failed. Make sure to have the same methods on both nodes. Node path: .
  <C++ Source>   modules/multiplayer/scene_cache_interface.cpp:123 @ process_confirm_path()

(So the same one gotnospirit already identified).

It's weird because for the login client and gateway the forementioned solution works, but when doing it again for gateway and authentication there seems to be a problem.

However, the authentication server receiver the request, runs the related function, and attempts to make a request back at the gateway to provide the results of authentication. This however doesn't get picked up by the gateway.

Print statements that explain communication
![kuva](https://user-images.githubusercontent.com/58560424/190857627-042f9460-4401-4ff1-954d-333303c2ff4f.png)

Error messages (upper = authentication, lower = gateway)
![kuva](https://user-images.githubusercontent.com/58560424/190857714-e8928404-d2f9-4a86-8863-a186fdc95cf8.png)

Gateway script that makes the authentication request:
![kuva](https://user-images.githubusercontent.com/58560424/190857756-4c2ebdee-2daf-4f55-a0eb-d454903623ee.png)

Authentication script that receives authentication request:
![kuva](https://user-images.githubusercontent.com/58560424/190857782-bb54400d-30e8-4bce-943d-789d70153b8d.png)

I know you already closed this ticket, but I think it still correlates to the problem at hand (or then I'm just stupid and can't figure out how the new rpc system works, lol)

**Comment by gotnospirit** [comment]
Second screenshot, there's only a `create_client` in `Authenticate.gd`, therefore in order for client to connect, I bet there is a `create_server` in `Gateway.gd` and that you also overwrite multiplayer instance (`get_tree().set_multiplayer`).

If I had to implement that kind of proxy stuff, I would start with an unique script for the gateway and split things when the whole chain is ok.

Also, pretty sure `!"test" == password` isn't the same as `"test" != password`

**Comment by Tompparella** [comment]
@gotnospirit You're right. Here's the Gateway server code:

![kuva](https://user-images.githubusercontent.com/58560424/190860769-c0a609f3-4725-4bba-9d8a-d8a3615ba9c8.png)

I'm migrating my project from godot 3.5 to 4.0, and this particular situation with a client and a server was previously handled with custom_multiplayer. I read from the docs that set_multiplayer could be utilized to achieve similar results:

![kuva](https://user-images.githubusercontent.com/58560424/190860866-4ca68b98-3779-4ae5-a559-ea820621c73f.png)

I guess I misintepreted the documentation. I thought that set_multiplayer with a different path would create a separate multiplayer instance for different Node branches, i.e. in my case there would be a server instance running on root/Gateway and a client on root/Authenticate. Any idea how this could be achieved?
