### ISSUE TITLE
Tooltip place at wrong place when embed subwindows is enabled

### ISSUE THREAD

**Issue by ncollie42** [godotengine/godot#65947]
### Godot version

4.0 beta 1

### System information

Fedora x11 NVIDIA GeForce GTX 970

### Issue description

Tooltip_text is placed at a absolute position, (roughly) center of screen when on full screen when 'embed subwindows' is enabled.
Tooltip is not visible when not fullscreen.

Enabled:
![Screenshot from 2022-09-16 15-19-10](https://user-images.githubusercontent.com/52465548/190815982-fe862db8-5038-44ff-80b5-2f28d5ef634f.png)

Enabled full screen:
![Screenshot from 2022-09-16 15-18-42](https://user-images.githubusercontent.com/52465548/190815963-da12c665-94ef-4d47-aae4-2761df6210bf.png)

Disabled:
![Screenshot from 2022-09-16 15-23-45](https://user-images.githubusercontent.com/52465548/190820299-6e642c97-bc06-4b72-bd13-a79f461f1802.png)

### Steps to reproduce

- Create controll node with tool_tip text
- run scene with and without  'embed subwindows' in project settings

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/54030.
