### ISSUE TITLE
Concave NavigationPolygon generated from code is treated as convex

### ISSUE THREAD

**Issue by lillukey** [godotengine/godot#65949]
### Godot version

4.0 beta 1

### System information

Windows 10

### Issue description

When setting a NavigationRegion2d's navpoly to a concave NavigationPolygon from code, the navpoly is treated as though it is convex, despite being displayed as correctly.

https://user-images.githubusercontent.com/42951415/190827060-e2f9d4f0-e73e-47a3-84c6-20a1416be0a1.mp4

### Steps to reproduce

Set up basic 2d navigation, and set the navpoly of the NavigationRegion2d to a new concave NavigationPolygon. 

To use the minimal reproduction project, tick the exported variable "Generate In Code" (found on the NavigationRegion2d node) on to see it not work, or off to see it work as expected. You can also change the exported variable "Target Num" to 1, 2 or 3, to see how it tries to navigate to 3 different targets.

### Minimal reproduction project

[ConcaveNavFromCode.zip](https://github.com/godotengine/godot/files/9589956/ConcaveNavFromCode.zip)

**Comment by smix8** [comment]
Your vertices array does not work to create a valid polygon for navigation mesh.
All navigation mesh polygons need to be triangulated and convex.

`NavigationMesh` resources used by the NavigationServer system require triangulated and convex 3D polygons and the `NavigationPolygon` facilitates the 2D to 3D conversions to the correct format for you if you provide it with suitable data.

What you see as "correct" is a broken debug polygon cause a working navmesh polygon in Godot 4 with the improved debug visuals will show you the polygon edges and highlight faces in different color tone similar to what you see in the Editor with a correct polygon.

![navpoly_working](https://user-images.githubusercontent.com/52464204/190855461-7b88e780-f33c-40b0-95f8-e7d60563ad2b.jpg)




Your vertices array could work for defining a NavigationPolygon `outline` that you can add with `NavigationPolygon.add_outline()` and calling `NavigationPolygon.make_polygons_from_outline()` as this will convert your outline vertices to a valid NavigationMesh for you.

If you don't want to work with outlines you can still use `NavigationPolygon.add_polygon()` but need to double-check that you add the right polygon format by adding the correct vertices first and addition polygon indicies second, e.g. triangulated, correct winding order and no intersections.

**Comment by lillukey** [comment]
Thanks for your help!
