### ISSUE TITLE
Set `TreeItem.set_icon_max_width` results in a glitch while editing a `TreeItem`.

### ISSUE THREAD

**Issue by Fran6nd** [godotengine/godot#65944]
### Godot version

4.0.dev

### System information

Vulkan API 1.1.211 - Using Vulkan Device #0: Apple - Apple M1

### Issue description

Hello everyone. I believe there is an issue with this:

There is a bug when I edit a `TreeItem` with an icon and used `set_icon_max_width` and then `set_editable`.
The text field's location appear to be discarding `set_icon_max_width`. I tried to compare the x position with and without `set_icon_max_width` and it appears to be exactly the same.
I am using the latest godot4.

Here is a picture as a proof (The tree contain only one column):
<img width="474" alt="Screenshot 2022-09-16 at 15 51 03" src="https://user-images.githubusercontent.com/14808487/190654891-2c79e52f-79c4-403f-a273-f48f1632e430.png">

And it seems to be linked directly to #42701 which is a 4.0 milestone.

### Steps to reproduce

```
var tmp = create_item(parent)
tmp.set_icon(0,myTexture2d)
tmp.set_icon_max_width(0, 40)
tmp.set_text(0, "yo")
tmp.set_selectable(0, true)
tmp.set_editable(0, false)
```

Then clic on the TreeItem titled `yo`.

**Comment by Fran6nd** [comment]
It seems there are two bugs:

* Text input displayed at the wrong location.
* Mouse event detection detecting events in at the wrong location too.

**Comment by KoBeWi** [comment]
Can you attach some minimal project that displays the issue? The code snippet you posted is not enough to test it.
