### ISSUE TITLE
GDScript 2.0: Incorrect base class when using `extends Class.Subclass`

### ISSUE THREAD

**Issue by rune-scape** [godotengine/godot#65953]
### Godot version

20d6672846

### System information

Windows 10 x64

### Issue description

When using 'extends BaseClass.Subclass' the class extended is 'BaseClass'. Kinda.
All super calls will go to A, not B, but Analyzer still knows B is the intended super class.

The `GDScriptDataType::script_type` for the identifier is set wrong in i think 'resolve_inheritance' or 'reduce_identifier_from_base' in GDScriptAnalyser. Or left unset?
Something to do with the subclass class member not getting its script type resolved.
`GDScriptDataType::script_type` is not set right by the time it gets to GDScriptCompiler when it sets the 'base' ptr in GDScript, where all super calls go.
Tested on Beta 1

### Steps to reproduce

Use the dot notation in an extends clause, like (extends A.B).
All super calls will go to A, not B, but Analyzer still knows B is the intended super class

### Minimal reproduction project

[GodotInheritanceBugProject.zip](https://github.com/godotengine/godot/files/9590571/GodotInheritanceBugProject.zip)
Running the project will print:
```
TestClass._init
BaseClass.test
```
When it should print:
```
TestClass._init
SubClass.test
```

**Comment by adamscott** [comment]
@bitbrain #65752 will not fix this issue, I just tested.

**Comment by bitbrain** [comment]
> I had to stop programming for my mental health, but if anyone wants to pick up where I left off, my WIP branch is here: https://github.com/rune-scape/godot/tree/rune-simplify-extends

@adamscott staring at you for no reason whatsoever.

**Comment by adamscott** [comment]
> I had to stop programming for my mental health

Take care, @rune-scape

**Comment by adamscott** [comment]
@rune-scape I think I fixed your issue with my new cyclic references! PR. #67714

**Comment by rune-scape** [comment]
@adamscott I found a lot of edge cases where subclasses aren't considered when I was trying to switch extends to use `resolve_datatype()` rather than trusting every use of `extends_path` to correctly find the subclasses.. There was alot of redundant code.
I almost got it to a testable state too. I'd feel much better if that was the fix to this issue. It would also fix the what @bitbrain mentioned in #66781.
its built on #67714

**Comment by adamscott** [comment]
@rune-scape You mean that it was built on #65752, I completely redid my PR from scratch.

I'll try to take a look to your PR one more time, to see what you did in resolve datatype.

**Comment by adamscott** [comment]
@rune-scape Unfortunately, there's too many changes for me, in your branch, to be confortable to integrate it in #67714, especially as it just been approved by a reviewer.

If you create a PR, I'll make sure to work with you to help you refactor `resolve_datatype()`.

**Comment by rune-scape** [comment]
> I completely redid my PR from scratch.

Ah

> there's too many changes for me, in your branch, to be comfortable to integrate it in #67714
> If you create a PR, I'll make sure to work with you to help you refactor `resolve_datatype()`.

Sounds good, ill start in a few days

**Comment by rune-scape** [comment]
So I did it Again and I have to stop programming, but @adamscott, #68086
now on you're newer pr

**Comment by adamscott** [comment]
@rune-scape Take your time. Especially for yourself. :purple_heart:

**Comment by adamscott** [comment]
Note to the Godot Maintainers: my PR (#67714) shouldn't mark this issue as resolved. That honour should go to @rune-scape 's PR #68374 as it's solution is way more deep that mine could ever be.
