### ISSUE TITLE
A code highlighting bug about ":"

### ISSUE THREAD

**Issue by upizpp** [godotengine/godot#65960]
### Godot version

3.5.stable

### System information

Windows 11

### Issue description

![QQ图片20220917111907](https://user-images.githubusercontent.com/82654854/190838657-255abe07-4775-4728-8790-0afa416b5967.png)
In the code editing part of godot, write a function. When the previous parameter is ":" as a string, the error of highlighting the following parameter as a type will occur

### Steps to reproduce

![QQ图片20220917111907](https://user-images.githubusercontent.com/82654854/190838758-b88c9697-2644-4f50-90f8-8d518c7ee718.png)

f(":", value)
Where f is a function, value is a variable.
The value will become the color of the type

**Comment by Gatada** [comment]
Just for comparison, this is on macOS. Seems like issue is fixed on 4.0b1 :-)

Using Godot 3.5
<img width="286" alt="Screenshot 2022-09-17 at 08 38 44" src="https://user-images.githubusercontent.com/326334/190846150-f91879ce-378b-4f51-9a17-e5416a191752.png">

Using Godot 4.0b1
<img width="293" alt="Screenshot 2022-09-17 at 08 38 33" src="https://user-images.githubusercontent.com/326334/190846154-d7cdf4d8-3952-4022-81f4-91d903fa7759.png">

**Comment by akien-mga** [comment]
Fixed by #65974.
