### ISSUE TITLE
Auto-start animation not starting when game played

### ISSUE THREAD

**Issue by WolfgangSenff** [godotengine/godot#65978]
### Godot version

4.0.beta1

### System information

Windows 11

### Issue description

I have an AnimationPlayer with a single animation in it that is set to autoplay on load (and repeat), and it isn't playing at all on load.

### Steps to reproduce

1. Create project
2. Create an AnimationPlayer
3. Add a sprite to the scene
4. Create an animation for the sprite
5. Set animation to autoplay and probably repeat (to ensure you see the animation happening)
6. Play the game; no animation occurs

### Minimal reproduction project

[49.2.zip](https://github.com/godotengine/godot/files/9591540/49.2.zip)

**Comment by KoBeWi** [comment]
It might be something with parallax. The animation is playing if you disable Camera2D.

**Comment by WolfgangSenff** [comment]
That is exactly what it is, thanks! Very strange. Now I'm not sure how to pull off this game idea, hm.
