### ISSUE TITLE
Add tooltips on ButtonArrays

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#6597]
Godot 2.1 official:

I want to add a tooltip to buttons of a ButtonArray, but there are no way to do it, by script or in inspector. The only method is set_tooltip, but it is intented for the whole widget, not individual buttons.

**Comment by bojidar-bg** [comment]
Um, no Vbox/Hbox of buttons anyone?

**Comment by Sslaxx** [comment]
Individual buttons as opposed to an array of them? Well, that'd work, but it doesn't solve @Zylann's issue.

**Comment by Zylann** [comment]
ButtonArray behaves differently, I would have more stuff to setup for an HBox of buttons to behave the same way.
