### ISSUE TITLE
Inspector category title becomes off-center after clicking on empty space in Scene tab

### ISSUE THREAD

**Issue by dogyx** [godotengine/godot#65972]
### Godot version

v4.0.beta1.official [20d667284]

### System information

Fedora 36

### Issue description

Inspector category title becomes off-center when clicking on a node in Scene tab after having clicked on empty space in Scene tab. This issue does not seem to happen with root nodes.

How it should look:
![expected](https://user-images.githubusercontent.com/85757201/190848165-860cb0f4-6679-4dd1-880e-48667f55ff16.png)

Bug:
![bug](https://user-images.githubusercontent.com/85757201/190848209-a3c6c1da-0c4a-42de-9d55-a043e2f97171.png)

### Steps to reproduce

1. Click on empty space in the Scene tab
2. Click on a node in Scene tab that is not root

**Comment by gotnospirit** [comment]
Reproduced on Windows 10

- New project
- Set root node (Node2D)
- Add child node (Node2D) -> text centered
- Click empty space (unselect child node)
- Click child node -> text on the right

Doesn't happen when unselecting the child node by clicking the root node

**Comment by dogyx** [comment]
I did some more testing and found out that the bug first appears in alpha 15 so it got introduced somewhere between alpha 14 and 15

**Comment by Rindbee** [comment]
https://github.com/godotengine/godot/blob/e5594c26b14e75d8b75d1f697cf2bfbd6254a50c/editor/editor_inspector.cpp#L1118

Computing `w` before and after here gives different results:

https://github.com/godotengine/godot/blob/e5594c26b14e75d8b75d1f697cf2bfbd6254a50c/editor/editor_inspector.cpp#L1131

I noticed that `get_size().width` will return `1` at the beginning. `size` doesn't seem to have been set correctly.

**Comment by Rindbee** [comment]
Related to #63398.
