### ISSUE TITLE
OpenGL: GUI rendering issues when hiding nodes

### ISSUE THREAD

**Issue by Ghashy** [godotengine/godot#65977]
### Godot version

4.0 beta 

### System information

Macbook Pro m1, Big sur 11.4

### Issue description

There are pair of gui bugs, with opacity and hiding nodes, I recorded it on video:

https://user-images.githubusercontent.com/109857267/190851810-685d1f19-b9f2-479a-94a2-189a6ff50671.mp4

### Steps to reproduce

Create an empty project, switch it to GLES3 renderer, add Control node, then Panel in it, and toggle hide/show button

**Comment by bfedie518** [comment]
I'm having the same problem when switching between scene tabs with OpenGL.  4.0 beta 1, Windows 10.
