### ISSUE TITLE
GridMap lighting issues when using imported meshes as tiles

### ISSUE THREAD

**Issue by fantaandcode** [godotengine/godot#65984]
### Godot version

4.0 beta 1

### System information

EndeavourOS 64-bit, 5.19.8-arch1-1 kernel, Ryzen 5 3600, Nvidia RTX 3090, Vulkan on driver version 515.65.01

### Issue description

When I use a GridMap with imported Blender meshes, it causes problems with the lighting/shadows as shown below. There is a distinct line where a shadow is made, regardless of location, distance from camera, and light rotation. I've tested with a flat plane MeshInstance and the lighting problem does not show. Toggling the GridMap visibility will also turn off this lighting inconsistency.

![image](https://user-images.githubusercontent.com/1066456/190856817-32930923-746e-42de-a42b-b8762e63d20d.png)

This problem actually showed up when I switched from alpha 15 to alpha 17. However, upon checking out the beta and seeing that the bug was still present, I'm making this bug report.

### Steps to reproduce

1. Make a 3D model in Blender
2. Export to GLTF
3. Import into Godot as new scene
4. Scene -> Export As... -> MeshLibrary...
5. Create GridMap
6. Add MeshLibrary created above as the Mesh Library for the GridMap
7. Paint tiles on GridMap
8. Create an OmniLight3D or Spotlight3D

### Minimal reproduction project

[Grid Map Lighting Bug.zip](https://github.com/godotengine/godot/files/9591671/Grid.Map.Lighting.Bug.zip)

I've included the .blend file of the tiles I made for this test.

**Comment by Calinou** [comment]
Try removing the `.godot/` folder while the editor is closed, then open the editor again. See https://github.com/godotengine/godot/issues/64854.

**Comment by fantaandcode** [comment]
Ah yes, this works now. Thank you!

**Comment by fantaandcode** [comment]
So, it worked for the test that I uploaded. However, it seems to still pose a problem. Would this be a problem with when I initially imported it via Blender? I see that .blend files are no longer showing up in the File Browser.

**Comment by Calinou** [comment]
> I see that .blend files are no longer showing up in the File Browser.

Double-check that Blender import is enabled in the Project Settings and that a Blender path is set in the Editor Settings.

**Comment by fantaandcode** [comment]
![image](https://user-images.githubusercontent.com/1066456/190981796-d1dc4434-d379-4bb7-bcbf-5375c64a2807.png)
So, it was initially having the same problems. Upon redoing the import process, it works now.
