### ISSUE TITLE
My godot textures are buged

### ISSUE THREAD

**Issue by faox50** [godotengine/godot#65982]
### Godot version

v3.5.stable.official [991bb6ac7]

### System information

Windows 10 GLES2 Intel(R) HD Graphics Ver.8.15.10.2372/Win10 64

### Issue description

when I opened my godot I saw that when I entered the godot editor the textures were bugged, I realize since I had opened godot on the same laptop and they were not bugged, the textures are with super low resolution...
Here it is.
![a](https://user-images.githubusercontent.com/113381143/190856903-3647eaa5-6de4-47a2-a4fa-eac8a7f313a7.png)

### Steps to reproduce

Just i opened my editor.

**Comment by faox50** [comment]
False positive, the problem was that the graphics drivers had low textures

**Comment by Calinou** [comment]
> False positive, the problem was that the graphics drivers had low textures

Can you describe this in more detail? Which graphics card model (or which integrated graphics) are you using? Knowing this would be helpful to resolve https://github.com/godotengine/godot/issues/55343.
