### ISSUE TITLE
Scancode always 0 for physical keys

### ISSUE THREAD

**Issue by stephanbogner** [godotengine/godot#65998]
### Godot version

v3.4.4.stable.official

### System information

macOS Monterey 12.1

### Issue description

I am not sure if this is the intended behaviour when working with physical keys, because I didn't find any information in the docs about this.

#### Description:
- (See example code below for easier understanding)
- When I try to access the **scancode** of a **physical button** (defined in the Input Map) it always returns `0`.
- If I retrieve the scan code for a "normal" key it works as intended (e.g. `32` for the `space`-bar)

#### Expectation:
- My assumption would have been that the scancode equals whatever the current hardware's keys represent.
- Example (as explained [in the blog post](https://godotengine.org/article/godot-3-4-is-released#input)) `WASD` equals `ZQSD` on a French keyboard:
	- That would mean that the scancode for **physical** `W`-key ([scancode](https://docs.godotengine.org/en/stable/classes/class_%40globalscope.html#enum-globalscope-keylist) `87`) would refer to the `Z`-key on a French keyboard and thus return the scancode `90`

#### Context
- I am trying to make a smooth way to handle different control schemes (a user should be able to switch between control schemes or even create a custom one). I was trying to abstract it to support local multiplayer nicely.
- Main code idea: Compare the scancode of an input key with the scancode of the (physical) keys defined in the Input Map.

#### Input map

<img width="564" alt="Screenshot 2022-09-17 at 19 21 28" src="https://user-images.githubusercontent.com/7897006/190868971-9fa5f286-f919-4845-9987-8631cc1a1377.png">

#### Code
```python
func _ready():
	print('Physical:')
	var scancode_physical = InputMap.get_action_list("debug_button")[0].scancode
	var keyname_physical = OS.get_scancode_string(scancode_physical)
	print('Scancode: ', scancode_physical, ' = ', keyname_physical)
	
	print('')
	
	print('Not physical:')
	var scancode = InputMap.get_action_list("debug_button")[1].scancode
	var keyname = OS.get_scancode_string(scancode)
	print('Scancode: ', scancode, ' = ', keyname)
```

#### Output
```
Physical:
Scancode: 0 = 

Not physical:
Scancode: 32 = Space
```

**Comment by KoBeWi** [comment]
Physical events use `physical_scancode` instead.

**Comment by stephanbogner** [comment]
@KoBeWi 
Wow that replay was fast! Thanks for the clarification! ❤️ 
(As this solves my question I am closing the issue)

I also discovered issue [3571](https://github.com/godotengine/godot-proposals/issues/3571) now which is related.

I don't really understand why there are separate ways to get the scancode, as the `physical_scancode` for non-physical keys is `0` (so it seems streamlining to `scancode` could make sense) ... but I am still learning so there probably is a good reason 🙂 

#### Code
```
func _ready():
	print('Physical:')
	var action_physical = InputMap.get_action_list("debug_button")[0]
	print('scancode_physical: ', action_physical.physical_scancode )
	print('scancode: ', action_physical.scancode )
	print('')
	print('Not physical:')
	var action = InputMap.get_action_list("debug_button")[1]
	print('scancode_physical: ', action.physical_scancode )
	print('scancode: ', action.scancode )
```

#### Output
```
Physical:
scancode_physical: 32
scancode: 0

Not physical:
scancode_physical: 0
scancode: 32
```

**Comment by lolouthefox** [comment]
Where did get_action_list go? It doesn't work anymore, anything changed?
