### ISSUE TITLE
C# generated code does not include public XML comments or disable 1591

### ISSUE THREAD

**Issue by definitelyokay** [godotengine/godot#65996]
### Godot version

4.0.0-beta1

### System information

macOS 12

### Issue description

Running `dotnet build` in C# Projects which have `<GenerateDocumentationFile>true</GenerateDocumentationFile>` specified in their `*.csproj` files results in warnings from the code produced by the Godot dotnet source generators:

```
warning CS1591: Missing XML comment for publicly visible type or member 'Main.SignalName'
warning CS1591: Missing XML comment for publicly visible type or member 'Main.RestoreGodotObjectData(GodotSerializationInfo)'
...etc
```

I currently maintain 5 packages for Godot whose public API's are fully documented and require `GenerateDocumentationFile` on those packages.

Possible solution:

The Godot source generators are already emitting `#pragma warning disable` for other rules (here's [one such example](https://github.com/godotengine/godot/blob/master/modules/mono/editor/Godot.NET.Sdk/Godot.SourceGenerators/ScriptMethodsGenerator.cs#L136)).

Since Microsoft [doesn't seem to care](https://github.com/dotnet/roslyn/issues/12702#issuecomment-285483035), I believe we should add a `#pragma warning disable 1591` to every new or modified API added by the Godot dotnet source generators.

### Steps to reproduce

Essentially, any project which contains `<GenerateDocumentationFile>true</GenerateDocumentationFile>` in the `*.csproj` file will result in build warnings about missing documentation from the Godot dotnet source generator output.

### Minimal reproduction project

I am working on updating one of my smallest packages to Godot 4. You can reference the `godot4` branch of `go_dot_collections` here as a minimum reproduction sample: https://github.com/chickensoft-games/go_dot_collections/tree/godot4

**Comment by 18swenskiq** [comment]
I will add to this rather than submitting a new issue, this causes *any* C# project to be unable to build if "Treat warnings as errors" is enabled in the csproj (`TreatWarningsAsErrors>True</TreatWarningsAsErrors>`), making the setting functionally unusable for Godot projects.
