### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by razvanc-r** [godotengine/godot#6599]
This is related to #6523, I opened a separate issue as it might be long (? or not...). Anyway, naming conventions, this is what I have:
- member variables (properties & such): only nouns
- methods: verb (present tense), verb + nous, just like the usual: `get_position` for example & the verb should go first always
- signals: verb (that describes state) / verb + nouns, for example instead of `enter_tree` have `entering_tree` (if it's fired before doing the action) and `entered_tree` if triggers after the task has finished (it has already entered), just like the methods, it should go first. For examples `script_changed` would become `changed_script`.

Also I think GDScript should only offer one of two options or both, but be complete:
- either access a member variable (or property) directly and change it, for example `transoform.origin.x = some_new_value`
- or only through `set_`, `get_` methods, like `set_pos()`, `get_pos()`

By complete I mean have all properties be directly accessible and settable through the first option and have them accessible through `set_`, `get_`. Also if then something like `transform.origin.x += 1` would be allowed (by the way, in this example `transform` would be a Godot object), then we should have the ability in GDScript to have a "magic" method to create our own `+=`, `-=` etc. compatible objects (like in Python)

**Comment by reduz** [comment]
I'm not sure if it's possible to avoid using member AND functions at the
same time due to how Godot works (which is mostly C++ API), but what we can
do is show documentation in such a way where properties are shown first and
then, even optionally, you can see functions used for setters/getters. For
Mono bindings this might be possible though.

**Comment by razvanc-r** [comment]
Having set/get methods AND accessing members directly would be fine as long as they are complete, that is these both options should be available for all properties. Then yes, in the docs there can be the "preferred" way and in any case it would leave it to the game dev. to do whatever... to have options isn't bad, but when they start mixing together it can become a mess.

I remember looking a while at node.js and they were mixing these things in the documentation and it just wasn't looking professional. Conventions are nice :)

**Comment by leezh** [comment]
For signals, while I agree that verb tense can make a big difference such as:

    enter_tree -> entered_tree
    exit_tree -> exiting_tree

The idea of a strict verb + noun doesn't make sense such as in `mouse_entered` / `entered_mouse`, because it depends on whether the noun is the subject / object of the verb.

**Comment by reduz** [comment]
this was all implemented in 3.0 as described here, so closing
