### ISSUE TITLE
Saving files in external code editors causes unnecessary dialogue popups

### ISSUE THREAD

**Issue by inputusernamehere** [godotengine/godot#65991]
### Godot version

4.0.beta1

### System information

Windows 10

### Issue description

There are two things I want to mention, the first one seems to be a bug:

The "The following files are newer on disk. What action should be taken?" dialogue popup re-appears after clicking reload. You have to click Reload twice to close it.

Secondly, I assume that this dialogue popup is important when, for example, large changes are made to the project folder via for example git commands. However for just saving code changes in a few files, it adds unnecessary friction. If it's possible to distinguish the two cases, or maybe add a setting so that I can always prefer what's on the disk/reload, that would be nice I think.

### Steps to reproduce

1. Create a new Godot 4 project.
2. Adda C# script.
3. Open the C# script in Visual Studio.
4. Save the script, whether or not you make changes does not seem to matter.
5. Tab back into Godot, see the popup.
6. Press Reload.
7. See the same popup again.

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/65912.

**Comment by FyiurAmron** [comment]
I agree that current behaviour is obnoxious. A config flag allowing to define a one selected action to happen _always_ would be the way to go IMVHO. (e.g. always reload, always ignore, always resave, always ask)

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/66644, as the issue actually got worse in 4.0.beta2.
