### ISSUE TITLE
Inferred type export vars are converted incorrectly from Godot 3 to Godot 4.

### ISSUE THREAD

**Issue by HauntedBees** [godotengine/godot#66006]
### Godot version

v4.0.beta1.official [20d667284]

### System information

Windows 8.1

### Issue description

When importing a project into the Godot 4 beta (originally written in v3.5.stable.official [991bb6ac7]), exported variables with inferred types (using `:=`) are converted incorrectly. The `export(type)` is correctly changed to `@export`, but the variable declaration itself is now incorrect.

### Steps to reproduce

1. Create a gdscript file in Godot 3.5 with `export(int) var int_export_var := 1` written in it.
2. Save the project, then import it in Godot 4, selecting **Convert Full Project** in the import prompt.
3. The converted line in Godot 4 will be `@export var int_export_var: int := 1` instead of the expected `@export var int_export_var := 1` or `@export var int_export_var: int = 1`.

### Minimal reproduction project

[VariableIssue.zip](https://github.com/godotengine/godot/files/9592627/VariableIssue.zip)

Project was created in Godot 3.5.

**Comment by rileylyman** [comment]
This seems to be fixed as of 4.3dev (2d0ee20ff30)

**Comment by Maran23** [comment]
> This seems to be fixed as of 4.3dev

Correct, I actually fixed it some months ago in Godot 4.1. Related PR: https://github.com/godotengine/godot/pull/75900
So this issue can be closed. :)
