### ISSUE TITLE
HighDPI mode is scaling too much on high resolution display (Windows)

### ISSUE THREAD

**Issue by Aculeo** [godotengine/godot#6601]
Godot 2.1 / Windows 10 on a Surface Pro 3

Not quite sure if this fits into any of the existing issues, so I'm creating a new one. I tried out Godot 2.1 on a Surface today and by default (Auto) it uses the LowDPI mode. In that mode, everything is blurry. When I turn on HighDPI, everything is far too large, it is pretty much unusable.

![godot-size](https://cloud.githubusercontent.com/assets/3977620/18810273/77bc82ba-8292-11e6-864e-bf474e1a023a.JPG)

To give some more information: I am using 150% text size on Windows, which is the default for the Surface. The resolution is 2160x1440 on a 12 inch display.

**Comment by BlenderNPR** [comment]
![tempsolution](https://cloud.githubusercontent.com/assets/11452632/18810393/5341bc9a-82c7-11e6-99a7-d5ff31243324.png)

Do this to the .exe to fix your problem.
"Disable display scaling on high DPI settings" check that.

**Comment by vnen** [comment]
This "150% text size" option is problematic. I'm not sure how this can be solved, since Windows version detection does not work without a manifest and the trial to add one resulted in issues for some Intel IGPU (see #5452).

**Comment by Qudware** [comment]
Same here, on a 2K high DPI device, the scaling is crazy. Never happened to me with any other software before. Disabling display scaling fixes this, but there must be a better way!
![image](https://cloud.githubusercontent.com/assets/3658686/20451343/cd53618a-ae43-11e6-9d1d-178bacb0fd9e.png)

**Comment by vnen** [comment]
Any suggestion is welcome. I still haven't got an idea which does not run into the issue I posted above.

**Comment by vnen** [comment]
Fixed by eb0f9651b3bb12b79db4ee4f8862a3be16a11ea5
