### ISSUE TITLE
Semicolon after Chinese string becomes smaller

### ISSUE THREAD

**Issue by xiaoliang6669** [godotengine/godot#66019]
### Godot version

4.0beta1

### System information

windows

### Issue description

Semicolon after Chinese string becomes smaller
![QQ图片20220918085659](https://user-images.githubusercontent.com/112788136/190881078-ce532237-776a-4df5-a2fd-46a0c640ea41.png)

### Steps to reproduce

Semicolon after Chinese string becomes smaller

**Comment by timothyqiu** [comment]
This can be triggered by any CJK characters, and the difference starts from the end quote character.

![ksnip_20220918-094803](https://user-images.githubusercontent.com/372476/190882169-e873469c-8883-472c-ba8e-788492bfee71.png)
