### ISSUE TITLE
[Godot4] Can't response input event sometimes when set gui_embed_subwindows = false

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#66016]
### Godot version

v4.0.beta1.official [20d667284]

### System information

Windows 10, 64bit

### Issue description

My SceneTree and Codes like this:
![image](https://user-images.githubusercontent.com/35988767/190880292-8ce61553-feb4-43f0-ba7a-ead675d395f3.png)

When `get_viewport().gui_embed_subwindows = true`, everything was OK:

https://user-images.githubusercontent.com/35988767/190880302-684b82da-32b3-4fe5-83dd-05d77f23d7ba.mp4

But when `get_viewport().gui_embed_subwindows = false`, it can't response input event sometimes:

https://user-images.githubusercontent.com/35988767/190880317-f5039a07-8a3b-412a-ac15-8ab9c3871c2b.mp4

NOTE: In this video, I was clicked the FileDialog's `OK`, `Cancel` and `[Close]` button many times!

### Steps to reproduce

Please run the reproduction project many times

### Minimal reproduction project

[PopupTest.zip](https://github.com/godotengine/godot/files/9592802/PopupTest.zip)

**Comment by Sauermann** [comment]
In my tests the problem was, that the FileDialog receives only the mouse-button-up events, but not the mouse-button-down events.
