### ISSUE TITLE
When a request times out in an HttpRequest node with multithreading enabled, the main thread is frozen

### ISSUE THREAD

**Issue by Xwdit** [godotengine/godot#66028]
### Godot version

4.0.beta1

### System information

Windows11, Nvidia RTX 2060, Vulkan

### Issue description

If I enable multithreading for a HttpRequest node, and send a request then times out, Godot will be freeze and crash

### Steps to reproduce

Enable multithreading for a HttpRequest node, and send a request which will times out, Godot will be freeze and crash

**Comment by timothyqiu** [comment]
I can't reproduce this on Arch Linux or Windows 10.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
