### ISSUE TITLE
TileSet paint properties editor dropdown does not support scrolling

### ISSUE THREAD

**Issue by xiaoliang6669** [godotengine/godot#66025]
0000000000000000

**Comment by akien-mga** [comment]
Please provide a reproduction project or clearer steps to reproduce. The code snippet you gave is not enough, what is `tuj`? We shouldn't have to reverse engineer what you did to understand and reproduce the issue.

**Comment by Calinou** [comment]
@xiaoliang6669 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.
