### ISSUE TITLE
[4.0] RayCast3D.target_position not returning correct coordinates

### ISSUE THREAD

**Issue by Flynsarmy** [godotengine/godot#66021]
### Godot version

4.0.beta1.official.20d667284

### System information

Windows 10, Vulkan 1.2.0, NVIDIA GeForce RTX 3070 Ti

### Issue description

With an identical setup, 4.0's 
```gdscript
raycast.global_transform.translated(raycast.target_position).origin
```
returns different coordinates to 3.5's
```gdscript
raycast.global_transform.translated(raycast.cast_to).origin
```

### Steps to reproduce
Here I'm using a raycast of length 10 and placing a meshinstance at its target position on `_physics_process`.

* Create a new 3D project with Spatial root, a RayCast3D, Camera3D, MeshInstance3D.
* Set camera to active, raycast rotation degrees to 90,0,0 and raycast target position to 0,-10,0
* For the mesh instance, add a new CapsuleMesh
* I also added a directional light and worldenvironment with skybox though not sure if this is a requirement.
* Add a script with the following:
```gdscript
extends Node3D


@onready var cast: RayCast3D = $RayCast3d
@onready var mesh: MeshInstance3D = $MeshInstance3d

func _physics_process(delta: float) -> void:
	mesh.global_transform.origin = cast.global_transform.translated(cast.target_position).origin
```
Hit play. The mesh won't appear at the end of the ray. With an identical setup in 3.5 and the following code, the mesh appears fine:
```gdscript
extends Spatial

onready var cast: RayCast = $RayCast
onready var mesh: MeshInstance = $MeshInstance

func _physics_process(delta: float) -> void:
	mesh.global_transform.origin = cast.global_transform.translated(cast.cast_to).origin
```

### Minimal reproduction project

Barebones 3.5 and 4.0 projects replicating the issue can be found here: https://github.com/Flynsarmy/gd-raycast-issue

**Comment by Flynsarmy** [comment]
On further inspection, Ray3D.target_position is returning the same value in both projects, however it's Ray3D.global_transform that is returning different values. 
Despite the RayCast nodes facing the same direction in both projects, here's the output of `print(cast.global_transform)` in both:
3.5:
> 1, 0, 0, 0, -0, -1, 0, 1, -0 - 0, 0, 0
4.0:
> [X: (1, 0, 0), Y: (0, -0, 1), Z: (0, -1, -0), O: (0, 0, 0)]

You can see the third Vector3 is different. -1 vs 1. What would cause this?

**Comment by timothyqiu** [comment]
`translated()` in 4.0 translates in global coordination, changing it to `translated_local()` produces the same result as in 3.5.

You may want to try `to_global()` if you don't want to change code here.

**Comment by Flynsarmy** [comment]
> `translated()` in 4.0 translates in global coordination, changing it to `translated_local()` produces the same result as in 3.5.
Ahh, gotcha. Can confirm the following works:
```gdscript
mesh.global_transform.origin = cast.global_transform.translated(cast.target_position).origin
```
We're all good here. Thanks, Timothy!
