### ISSUE TITLE
Manage editor features does not work in godot 4.0 beta

### ISSUE THREAD

**Issue by gobleboo** [godotengine/godot#66032]
### Godot version

Godot_v4.0-beta1_win64

### System information

Windows 10

### Issue description

In Godot 3.5 I can disable the 3d editor and the AssetLib, but in Godot 4.0 Beta I can't.
![editor_features](https://user-images.githubusercontent.com/18690121/190889232-7f9d7b2b-349d-432f-8fdc-276d8b1d0ae8.png)

### Steps to reproduce

Go to Editor -> Manage Editor Features... and try to disable the 3D editor.

### Minimal reproduction project

[New Game Project.zip](https://github.com/godotengine/godot/files/9593186/New.Game.Project.zip)

**Comment by timothyqiu** [comment]
You are still using the default profile in the screenshot.

Clicking the "Make Current" button activates the custom profile.

**Comment by Calinou** [comment]
We should probably make the first created profile the default automatically, so that you don't have to click **Make Current** manually.

**Comment by YeldhamDev** [comment]
@Calinou Seems to be the current behavior from what I tested.

**Comment by KoBeWi** [comment]
Yep.
