### ISSUE TITLE
Niqqud is displayed incorrectly

### ISSUE THREAD

**Issue by ababen1** [godotengine/godot#66039]
### Godot version

3.5.stable

### System information

Windows 11, GLES3, NVIDIA GeForce GTX 1650,  i5-11300H

### Issue description

Some context: [Niqqud](https://en.wikipedia.org/wiki/Niqqud) is a system of signs used to represent how to pronounce Hebrew letters. those signs are written above, below or inside the letter, depending on the sign. Here is a good example (the niqqud is in red):
![image](https://user-images.githubusercontent.com/80917990/190897027-c4b30279-76ed-47bd-84fa-adcb90f675b9.png)

So ignoring the fact that Godot displays RTL text as LTR, which I know is going to be fixed in Godot 4, it also displays niqqud as if they are separate characters. For example, I used the font [Alef ](http://alef.hagilda.com/) to write this text in Godot:
![image](https://user-images.githubusercontent.com/80917990/190898007-2052253b-d8d1-46a7-a783-b3266950352b.png)

Which is incorrect, here is an example of what I'm expecting to get:
![image](https://user-images.githubusercontent.com/80917990/190897892-f4392399-c2f4-469b-bbe7-dac649449346.png)

I didn't find anything talking about niqqud when I looked up the Godot 4 update, so I wasn't sure if it's going to be fixed or not
 

### Steps to reproduce

1. Create a new project
2. Download an Hebrew font and add it to the project. The reproduction project I added already has 2 fonts you can try
3. Create a new DynamicFont with the font you downloaded
4. Try to write Hebrew text with niqqud. Here is an example you can copy of the text I wrote:
`אָ    
בּ
וֹ `

### Minimal reproduction project

[NikudExample.zip](https://github.com/godotengine/godot/files/9593808/NikudExample.zip)

**Comment by Calinou** [comment]
> I didn't find anything talking about niqqud when I looked up the Godot 4 update, so I wasn't sure if it's going to be fixed or not

Try [4.0.beta1](https://godotengine.org/article/dev-snapshot-godot-4-0-beta-1) and see if it works :slightly_smiling_face:

**Comment by ababen1** [comment]
> This may be a limitation that can't be lifted without breaking compatibility: #54625
> 
> > I didn't find anything talking about niqqud when I looked up the Godot 4 update, so I wasn't sure if it's going to be fixed or not
> 
> Try [4.0.beta1](https://godotengine.org/article/dev-snapshot-godot-4-0-beta-1) and see if it works 🙂

oh it is actually displaying it correctly in the beta! ty
