### ISSUE TITLE
Shadows of skeleton animations stop animating if rest of the scene is static

### ISSUE THREAD

**Issue by rustwork** [godotengine/godot#66035]
### Godot version

4.0 Beta 1

### System information

Windows 10, Vulkan, Nvidia RTX 3060 Ti

### Issue description

If there is a skeleton based animation playing (for example a character walk cycle), but no other object in the scene is physically moving, then the shadows of the animated character stop animating as well. 

ShadowBug.mp4 shows the debug project that I've attached

https://user-images.githubusercontent.com/2095704/190893159-03665c0c-882c-426d-b085-0f94bdf17244.mp4

ShadowBug2.mp4 shows a different project where interestingly only one of the character's shadows stops animating (when the player stops moving the fps camera)

https://user-images.githubusercontent.com/2095704/190893161-d84eedc3-a417-4d12-aaf1-c725c3bad023.mp4

### Steps to reproduce

- import an animated model with bone animations
- set up the model's animation to autoplay and loop
- add a floor plane
- add an omni light or two, turn on their shadows
- run the game

If only the model's animation is playing, the model's animation won't animate properly in (most?) cases

### Minimal reproduction project

Please see the attached debug project. Running the game should show that even though the dummy character is leaning back and forth (via bone animation), its shadow is not animating because no transforms are changing in the scene. 
If on the other hand you turn on **autoplay** for the **AnimationPlayerSphere** node, then the sphere's position will also animate and all shadows will correctly animate as a result.

[shadow_bug_project.zip](https://github.com/godotengine/godot/files/9593373/shadow_bug_project.zip)

**Comment by Alriightyman** [comment]
I can confirm I have this issue as well.  For my scene, I have 1 animated model (player) and one static model (the level). It animates the shadows fine while running around but as soon as I stop moving, the shadow rendered is the last animation played from my character (most of the time).   This happens with OmniLight3D and SpotLight3D.  DirectionalLight3D seems to work like if should.

**Comment by TokageItLab** [comment]
I was able to confirm this at the beginning of the beta, but cannot reproduce this in recent releases. If it still occurs, I suggest to open a new issue with a more specific environment.
