### ISSUE TITLE
class_name does not work

### ISSUE THREAD

**Issue by 0x0ACB** [godotengine/godot#66042]
### Godot version

4.0

### System information

Windows 10

### Issue description

I have converted a project of mine to godot 4.0 that uses `class_name` in a few scripts. It seems that this does no longer work. All scripts that try to access these classes error out with `Parser Error: Identifier "<class name>" not delcared in current scope`. Looking at the project.godot file it seems _global_script_classes is no longer populated. `ScriptServer::save_global_classes()` seems to be getting called but `get_global_class_list(&gc);` just returns an empty list and `ScriptServer::add_global_class` seems to never be called.

The documentation for latest still claims this should work at least.

### Steps to reproduce

Create a script with `class_name` try to access said script through its class name

### Minimal reproduction project

[classname.zip](https://github.com/godotengine/godot/files/9593881/classname.zip)

**Comment by mieldepoche** [comment]
Can't reproduce on 4.0 beta 1 on linux.

**Comment by KoBeWi** [comment]
This happens when you have some error in your script and it can't be parsed correctly. Make sure you have fixed all errors.

**Comment by 0x0ACB** [comment]
The attached sample project only has a single const value exported in Foo and still produces the same error

**Comment by KoBeWi** [comment]
Can't reproduce in the attached projec.
Which version are you using exactly?

**Comment by 0x0ACB** [comment]
I tested both with a custom build of master for debugging and Godot_v4.0-beta1_win64
