### ISSUE TITLE
modules/gdscript/gdscript_analyzer.cpp:656 - Parser bug (please report): tried to assign unset node without an identifier

### ISSUE THREAD

**Issue by WideArchShark** [godotengine/godot#66041]
### Godot version

4.0 beta 1

### System information

Windows 10, AMD 2700X GTX 1660ti

### Issue description

modules/gdscript/gdscript_analyzer.cpp:656 - Parser bug (please report): tried to assign unset node without an identifier.

Don't know what to say. There's  thousands of them appearing!

### Steps to reproduce

Just loaded a project in Godot.

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
Your scripts probably have lots of errors. They should be gone once you fix the scripts

The "please report" part is unfortunate. We can't really do anything if you don't provide some sample project/code.

**Comment by WideArchShark** [comment]
It's not my script unfortunately. Looks very complicated to me, so was posting as advised by the message. I'll see if I can get it to repeat.

**Comment by Zireael07** [comment]
@KoBeWi I was seeing this from time to time while writing the script in question. Once the function/line was finished, the stupid error went away. As early as alpha 14, and is still in beta1 (I saw this while upgrading for API changes in between)

**Comment by KoBeWi** [comment]
The error looks the same as in #62092, so closing as duplicate.
