### ISSUE TITLE
Error with projects containing ] on the file path

### ISSUE THREAD

**Issue by Necco-Z** [godotengine/godot#66053]
### Godot version

v4.0.beta1.official [20d667284]

### System information

Arch Linux

### Issue description

Godot 4 can't seem to be able to save filepaths containing the `]` symbol.
I usually name some folders using square brackets to separate them from project folders. But if I create or import a project inside a folder with square brackets on its name, the next time I open the editor, the project shows as missing in the project list, and the project path only goes up to the closing square bracket.

Here's the project creation dialog
![2022-09-18_12-52](https://user-images.githubusercontent.com/41708431/190916163-1c7409d0-6fb0-4d99-b64a-ffbae5d67c1a.png)

And here's how it shows up later on the project list. Notice the project path
![2022-09-18_12-52_1](https://user-images.githubusercontent.com/41708431/190916197-51f75e05-6f70-4b46-a764-87dc61fc1d10.png)

### Steps to reproduce

- Create/import a project on a folder path containing the `]` symbol.
- Close the editor or go back to the project list.

**Comment by Calinou** [comment]
Can you reproduce this on [3.5](https://godotengine.org/article/godot-3-5-cant-stop-wont-stop)?

**Comment by Necco-Z** [comment]
The same steps work flawlessly on 3.5.
