### ISSUE TITLE
TileMap causes it to run slower

### ISSUE THREAD

**Issue by xiaoliang6669** [godotengine/godot#66055]
0000000000000000

**Comment by Calinou** [comment]
@xiaoliang6669 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

The reason for this occurring is likely that TileMap images were saved as serialized Base64 within the `.tres` file instead of external PNG images.

**Comment by xiaoliang6669** [comment]
You're right, but I usually merge images with TexturePacker, a third-party software, to reduce the size of images

**Comment by groud** [comment]
This seems expected. You are not supposed to have that many atlases in you TileSet and should use the atlas merging tool to reduce the number of atlas sources. The atlas merging tool is accessible from the menu with 3 dots at the bottom.

**Comment by xiaoliang6669** [comment]
@groud 
A tile 320*240, a total of 840 pieces make up a complete large map, I need to dynamically load and unload each tile in the script to achieve the correct display of the map. There is also a problem, how to use the script implementation to set the navigation shape for each tile, 3.0 I implemented, but 4.0 everything changed.

**Comment by groud** [comment]
> A tile 320*240, a total of 840 pieces make up a complete large map, I need to dynamically load and unload each tile in the script to achieve the correct display of the map.

How many tile you have is not a problem, you need to move them all to a single tile atlas, not use one atlas per tile, which is really inefficient.

> There is also a problem, how to use the script implementation to set the navigation shape for each tile, 3.0 I implemented, but 4.0 everything changed.

This is implemented in 4.0 too but needs to be documented I suppose.
