### ISSUE TITLE
Editor crashing when changing theme.

### ISSUE THREAD

**Issue by hypohub** [godotengine/godot#66051]
### Godot version

v4.0

### System information

Windows 10

### Issue description

The editor crashes whene changing the colors in the theme.
First time I try, it crashed instantlly. Now it not crashing everytime.
It is doing it no matter the project.

### Steps to reproduce

1. Open Editor Settings
2. Go to Interface > Theme
3. Change Base Color and Accent Color repetedly until it crashes

**Comment by Rindbee** [comment]
Probably a duplicate of #59798.
