### ISSUE TITLE
3-to-4 project converter adds extra line for move_and_slide

### ISSUE THREAD

**Issue by daveTheOldCoder** [godotengine/godot#66054]
### Godot version

4.0-beta1

### System information

Linux (Pop!_OS 20.04)

### Issue description

When the 3-to-4 project converter converts a call to KinematicBody2D.move_and_slide(), it adds a line containing only "velocity", resulting in a warning message: "Standalone expression (the line has no effect)."

This does not affect the proper execution of the code.

### Steps to reproduce

Convert and run the minimal reproduction project attached below. View the script main.gd and the Errors tab.

### Minimal reproduction project

[project_converter_3_to_4-bug1.zip](https://github.com/godotengine/godot/files/9594360/project_converter_3_to_4-bug1.zip)

**Comment by DorianSzlachcic** [comment]
This should look like 
`set_velocity(direction.normalized() * speed)`
`move_and_slide()` only without the "velocity" line, am I right?

**Comment by DorianSzlachcic** [comment]
Hi, I made [PR#66233](https://github.com/godotengine/godot/pull/66233) with the solution. Could you look at it?
