### ISSUE TITLE
Arabic Text Waving incorrectly

### ISSUE THREAD

**Issue by 3booodpro** [godotengine/godot#66058]
### Godot version

4.0.beta1

### System information

Windows 10, Vulkan, GTX 1660 Super

### Issue description

https://user-images.githubusercontent.com/78119395/190919866-00f69a1c-d89e-4172-90c7-84af9243558d.mp4

Comparing it with the Latin script
The Arabic is waving incorrectly.. it should wave letter by letter but what happens is any connected Letter are moving as a hole one letter

I think there should be a property to choose if the user want this effect or want to apply the effect on each letter individually

### Steps to reproduce

use a normal rich text label
enable the bbcode

type in the text section:
[wave freq=10 amp=100] السلام عليكم

use this font to see the letters correctly
[MarkaziText-Bold.zip](https://github.com/godotengine/godot/files/9594867/MarkaziText-Bold.zip)

now you can see the problem

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by bruvzg** [comment]
This was done intentionally, to avoid breaking connected glyphs, but I guess we can add an option for the wave effect to disable this behavior.
