### ISSUE TITLE
Resource loading autocompletion is not smart.

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#66066]
### Godot version

v3.5.1.rc1.official [293c3844b]

### System information

w10 64

### Issue description

I don't know if this is a bug or perhaps a suggestion, but could this aspect be improved?
The autocomplete simply doesn't understand that the scene I'm looking for is called "item" and offers me options that are not valid at all with what I'm writing.

In this video I simply try to load a resource, the resource is a scene called "Item.tscn" but the autocomplete offers me options that are not valid with what I write.

https://user-images.githubusercontent.com/19652075/190924086-90b6270e-9b99-4787-80a8-f77e761dc401.mp4

So what about autocomplete?
Is it bugged or just not very smart?

### Steps to reproduce

...

### Minimal reproduction project

...

**Comment by HolonProduction** [comment]
4.x has a more advanced matching algorithm for the options which fixes this.

The issue should be closed or moved to the 3.x milestone.

**Comment by HolonProduction** [comment]
Closing as fixed in 4.x.
