### ISSUE TITLE
AnimationTree can't replace one connection with another of the same type.

### ISSUE THREAD

**Issue by viksl** [godotengine/godot#66073]
### Godot version

4.0b1 mono

### System information

Windows 10, Nvidia gtx 1660Ti, latest drivers, Vulkan

### Issue description

In the animation tree if I add two animation nodes set their animations then connect one node to output, everything is ok but if I try to drag the other node's noodle to the output I get a warning as you can see in the image and here:
`Unable to connect, port may be in use or connection may be invalid.`

I'm not entirely sure if this is a bug but it does feel like one since the workaround is disconnecting the previous connection and connecting the second one which is just extra step which doesn't make much sense?

![godot-bug-AnimationTree](https://user-images.githubusercontent.com/33526847/190929423-882bc64a-0077-48cf-9549-b2898885fb16.png)

### Steps to reproduce

1. Create AnimationTree (set it up with an animation player if you need to)
2. Create two or more animation nodes and set them up with some animation
3. Connect first animation node to the Output
4. Try connecting the second animation node to the output - this gives a warning and doesn't connect.

### Minimal reproduction project

-

**Comment by TokageItLab** [comment]
Please clarify your objective. Do you mean that you want the behavior to automatically replace existing connections when trying to connect another Node?

**Comment by viksl** [comment]
> Please clarify your objective. Do you mean that you want the behavior to automatically replace existing connections when trying to connect another Node?

Yes, exactly. Right now in the image above if you try to replace the bottom animation connection by the top one you have to disconnect first then connect the new one. I would expect the warning to come when you are trying to connect a node into a spot where it doesn't work but I can't really come up with a reason why having the extra step there for regular ones.

Or was there some particualr reason why this gets triggered in AnimationTree graph edit?

For an example test flow which I believe is common:

Your drop in animations, blends, ... whatever you need and you plug it into the output to see the results then try a different one and so on, disconnecting seems like an unnecessary extra step in the workflow?

I hope this cleared it :-).

**Comment by TokageItLab** [comment]
Perhaps a "replace" option could be added to the dialog, but consensus would be needed.

**Comment by viksl** [comment]
> 

Was there a reason this was added as extra to begin with, please?
I mean I find it a bit strange because in visual shaders you can replace the connections no problem, that's why I initially filed this since it seemed more like an issue.

Well, I'll just hope it will get to it one day, manually disconnecting just feels strange unless you allow multiple connects to one point as they did in newer versions of Blender and also considering in visual shaders it alreadz works like that in godot 4 and 3. :-)

**Comment by viksl** [comment]
> AnimationTree hasn't changed behavior from before, if what you say is true, it may not be following VisualShader. In any case, I recommend that you send a proposal in https://github.com/godotengine/godot-proposals.

Oki, I've made one here:
https://github.com/godotengine/godot-proposals/issues/5460
