### ISSUE TITLE
Selecting NodePath does not work on nested exported array

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#6609]
**Operating system or device - Godot version:**
Windows 7/Ubuntu 16.04 64bit - Godot v2.2alpha.custom.build (fixnum - 09/22)

**Issue description** (what happened, and what was expected):
In the inspector, selecting a node for NodePath type array value if the array is part of another array, the selected path shows a bad value (points to EditorNode)

What was supposed to happen is getting the path to the selected node on the scene tree.

Capture of the path just selected on the second Array:

![badnodepath](https://cloud.githubusercontent.com/assets/10215987/18817047/b6d90014-832c-11e6-916b-30431dc9b961.png)

**Steps to reproduce:**
1- Make a node with a script
2- Add `export(Array) var variable_name` to the script
3- On the Inspector, edit the exported array and add an element of type Array
4- Edit the new array and add an element of type NodePath
5- Select a node and you will get a bad path value

**Link to minimal example project** (optional but very welcome):
Project with a single node and the bad path already selected on the nested array.
[badnodepath.zip](https://github.com/godotengine/godot/files/491787/badnodepath.zip)

**Comment by eon-s** [comment]
This affects master too.

Example project for Godot 3:
[badnodepathv3.zip](https://github.com/godotengine/godot/files/1465320/badnodepathv3.zip)

How to use the example:
- Select the root node.
- Edit the exported array.
- Edit the first index (another array).
- Assign a node (NodePath) to an index in that array.

**Comment by Noshyaar** [comment]
Still reproducible/relevant in 3.1 master 9ad1800

**Comment by ordigdug** [comment]
#21541

**Comment by samdze** [comment]
The bug is still there in current 3.1 8ba0d513fa0068a241a25fbb6db09315fa3309cc, and it happens even if a simple array (not nested) of NodePaths is exported.

**Comment by reduz** [comment]
I fixed this some days ago, closing.
