### ISSUE TITLE
Godot crashed: finding intersection when colliders overlap

### ISSUE THREAD

**Issue by BlenderNPR** [godotengine/godot#6610]
**Operating system or device - Godot version:**
Win10 64bit
Godot 2.1

**Issue description** (what happened, and what was expected):
When 2 collision shapes overlaps and you want to find intersection using either intersect_point/shape/ray, Godot crashed. 
Not sure why.

Error print
ERROR: Vector<struct Physics2DDirectSpaceState::ShapeResult>::operator []: Condition ' p_index<0 || p_index>=size() ' is true. returned: aux
   At: c:\projects\godot-builds\godot\core\vector.h:132

**Steps to reproduce:**
run this project
[CollidersOverlap.zip](https://github.com/godotengine/godot/files/491850/CollidersOverlap.zip)
click on the intersecting area of the sprites to crash Godot

**Comment by bojidar-bg** [comment]
Can no longer confirm on 2.1/HEAD, plus GH forgot to autoclose it again...
