### ISSUE TITLE
GDScript 2.0: Duplicating scripts works, but gives an error

### ISSUE THREAD

**Issue by radlotus** [godotengine/godot#66105]
### Godot version

4.0.beta4

### System information

--

### Issue description

Duplicating scripts gives an error. Works fine in 3.5
```
E 0:00:00:0973   _ready: Attempt to open script '' resulted in error 'File not found'.
  <C++ Error>    Condition "err" is true. Returning: err
  <C++ Source>   modules/gdscript/gdscript.cpp:1064 @ load_source_code()
  <Stack Trace>  node.tscn::GDScript_tml4s:4 @ _ready()
```

### Steps to reproduce

Duplicate any script with `duplicate()`.

**Comment by Rindbee** [comment]
When copying, `script/source` (alias of `source_code`) will be set, and it will be automatically reloaded.
https://github.com/godotengine/godot/blob/ea9bb98f26be8212245f6ff796617901a8b9f3f6/modules/gdscript/gdscript.cpp#L1024-L1027
Then it's #66593.
