### ISSUE TITLE
The lack of support for Android devices with x86 architecture

### ISSUE THREAD

**Issue by Timofffee** [godotengine/godot#6611]
Device: Orange San Diego (Android x86)
Godot 1.1stable - 2.1stable

Are the owner of a smartphone on Intel Atom (x86). Can't start any applications created in Godot engine. 

Checked on multiple devices (except your own) and not only works on x86. On arm is stable.
The application does not start, crashes.

Steps:
1. Download any app from Google Play
2. To run the application.

**Comment by vnen** [comment]
Godot does support x86 but not by default (the export templates don't have it). You can compile your own templates with x86 support. Issue is mostly of the game devs not really caring about the architecture. And since Intel stopped making such chips, the support will only get smaller.

**Comment by reduz** [comment]
You have to explicity tick x86 support when you export, This is most likely
the fault of whoever published the app for not exporting with x86 support.

**Comment by akien-mga** [comment]
> Godot does support x86 but not by default (the export templates don't have it). You can compile your own templates with x86 support. 

Actually official export templates do include the x86 library. Users just need to enable it when exporting as @reduz mentioned.
