### ISSUE TITLE
ALT + RIGHT shortcut stops working after a while of using the editor

### ISSUE THREAD

**Issue by TX256** [godotengine/godot#66111]
### Godot version

v4.0.beta1.official [20d667284]

### System information

Windows 11

### Issue description

I'm using Godot 4 beta 1, and ALT + RIGHT (Go to next edited document) stops working after using the editor for a while.

I also used alphas from about 13 to 17, and the problem was there too.

ALT + LEFT works just fine all the time..

### Steps to reproduce

I can't pinpoint the exact circumstances under which this happens, but the shortcut just stops working after a while of coding / using the editor.

### Minimal reproduction project

--

**Comment by Zireael07** [comment]
Single window mode or default? Anything else that might be stealing focus (notifications, the like)?

**Comment by TX256** [comment]
Not using single window mode (first time I hear of it).

This happens even with Godot 3.5

I noticed that as soon as I open the script editor's "File"-menu, the shortcut stops working.

Then, if I open the menu again, the shortcut starts working again.

BUT, it doesn't break every time when I open the menu... however, it really looks like opening the menu is related to this.
