### ISSUE TITLE
Garbage displayed in the top of the project manager

### ISSUE THREAD

**Issue by vinnyhorgan** [godotengine/godot#66132]
### Godot version

3.5.stable

### System information

Windows 11 GLES3 RX580

### Issue description

When I open the project manager, everytime I get this garbage:

![Screenshot (2)](https://user-images.githubusercontent.com/65792914/191097700-c0ace2f6-7a03-4813-9479-ecf2e8133690.png)

It goes away the moment I hover on the window.
It doesn't affect in any other way the engine functionality.

### Steps to reproduce

Open the project manager.

**Comment by SirQuartz** [comment]
Hmm, I can't replicate this.

Windows 11 Geforce RTX 3080

**Comment by Calinou** [comment]
Do you have any third-party Vulkan overlays installed (such as RTSS)?

**Comment by vinnyhorgan** [comment]
> 

No...

**Comment by girng** [comment]
"rendering artifact of yellow lines"

**Comment by Calinou** [comment]
@vinnyhorgan Can you (or anyone else) still reproduce this bug in Godot 4.1.2) or any later release?

**Comment by vinnyhorgan** [comment]
Sorry i have since switched operating system. Hope anyone else can give it a try!

**Comment by Calinou** [comment]
Alright, closing then. Please comment if you can still reproduce this on the latest Godot version.
