### ISSUE TITLE
Text garbling happens when the editor's language is set to Japanese

### ISSUE THREAD

**Issue by azul372** [godotengine/godot#66142]
### Godot version

4.0beta1

### System information

Windows 10, Vulkan, NVIDIA Quadro P2000

### Issue description

(see also #65180)
When the editor's language is set to Japanese, The FileDialog window looks like this in the editor view as well as when you use a FileDialog node in @tool scripts. 
![image](https://user-images.githubusercontent.com/80684394/191156972-4cf608a8-c7fe-4553-bcba-00b8046382fd.png)
It doesn't seem to happen when you actually *run* the scene containing a FileDialog node.

#65210 said it would likely fix this issue, but I can still reproduce the FIleDialog issue in 4.0beta1.

### Steps to reproduce

1. Set the editor's language to Japanese and restart the engine
2. Create a scene, add FileDialog node and see how it looks

**Comment by bruvzg** [comment]
If it is a `FileDialog` added to the project? If it is, that's expected default project font includes Latin, Greek, and Cyrillic characters only.

For the editor plugin, you should probably get theme from the `get_editor_interface().get_base_control()` and apply it to the dialog.

**Comment by akien-mga** [comment]
Closing based on the above comment.
