### ISSUE TITLE
Scene creation dialog detects some root names as invalid when it shouldn't

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#66158]
### Godot version

34e28f2

### System information

Windows 10 x64

### Issue description

![image](https://user-images.githubusercontent.com/2223172/191263372-21016e83-9f1a-4350-adac-7f93a034ff3a.png)
1 is a valid node name, but the dialog doesn't let you use it. IIRC it uses `is_valid_identifier()` function to check that, but node names have less strict rules than identifiers. A different function should be used.

### Steps to reproduce

1. Right-click in filesystem dock
2. New Scene
3. Start Root Name with number

**Comment by DorianSzlachcic** [comment]
Hi, I made [PR(#66172)](https://github.com/godotengine/godot/pull/66172) with solution to this issue. Cloud you look at it?
