### ISSUE TITLE
Unexpected long time importing blend files and other issues

### ISSUE THREAD

**Issue by lemon37564** [godotengine/godot#66169]
### Godot version

4.0 beta1

### System information

Linux, Vulkan

### Issue description

I'm trying to import a blend file in Godot 4 beta1, but Godot freezes and uses 100% CPU.
It took over 7 minutes to import while the file is only 12MB, seems abnormal.

Besides, the imported scene is missing all the textures.
The objects' translation are very different from the one I see in blender.

# In blender:
![image](https://user-images.githubusercontent.com/65079334/191302314-7e96b286-5cc5-4a2b-bc35-2431b815dfd3.png)

# In Godot4:
![image](https://user-images.githubusercontent.com/65079334/191302510-1d6aa13e-7f2d-4437-82ea-cdb28dbc3fef.png)

### Example blend file:
[cube_diorama_custom1.zip](https://github.com/godotengine/godot/files/9609164/cube_diorama_custom1.zip)

### Blender version
3.3.0

### Steps to reproduce

1. Download the attached blend file
2. Try to import with Godot 4 beta1
3. Godot freezes and take a long time to import
4. Imported scene broken (missing textures, wrong object translation)

**Comment by timshannon** [comment]
You could try exporting GLTF manually from blender, that may illuminate the issue.  I know the "Keep Original" option that Godot users on export can cause some issues.  These settings will export similarily to what Godot does in the background:

![image](https://user-images.githubusercontent.com/1330485/191309301-20ab3e88-ed22-4e8c-a14a-966785eef20b.png)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/65913.

**Comment by lemon37564** [comment]
Sorry, maybe I've wrote a improper title.
My problem is mainly on the import time, which is 7 minutes, way longer than expected.

@timshannon, after exporting .dae, .gltf and .glb format from blender itself, the results are at below:

# dae
![image](https://user-images.githubusercontent.com/65079334/191316216-bbf355a1-f2e7-48a1-af11-526b3087c981.png)
A little bit different(mostly textures) from blender but it's better.

# glb, gltf
### original
![image](https://user-images.githubusercontent.com/65079334/191316883-344c0ca1-9958-4aa1-a5c3-6cc75d7ba822.png)
### zoom in
![image](https://user-images.githubusercontent.com/65079334/191316717-82248834-e0da-4900-a0d6-5c48d031ed3f.png)
It's more like what is imported by godot editor.

**Comment by bmolyneaux** [comment]
This is not a Godot bug.

If I export your .blend to .glb and then reimport into Blender, this is what I get:
![image](https://user-images.githubusercontent.com/1959973/207757932-c0f8ebf0-c0d0-4a38-bbd1-7b5579cb59df.png)
![image](https://user-images.githubusercontent.com/1959973/207758240-297a8ee5-a42e-47bf-94f6-08e8326cd042.png)

It looks identical to what you are seeing in Godot, so this is really just an issue of Blender not being able to export your scene as a glTF. I assume this is at least partly related to Blender's Asset Browser.

**Comment by lemon37564** [comment]
Thanks! I'll issue to blender repo then.
Closing as this is not a godot issue.
