### ISSUE TITLE
Shader Editor's list of open shaders lags behind to previous selection.

### ISSUE THREAD

**Issue by Skywolf285** [godotengine/godot#66164]
### Godot version

4.0.beta1.official

### System information

Pop!_OS 22.04 LTS x86_64, NVIDIA GeForce GTX 1060 6GB, Vulkan

### Issue description

Whenever two or more shaders are loaded in the Shader Editor and the user selects another shader in the list on the left will it not correctly reflect the selected shader. It instead displays the previous state.

So lets say I have three shaders open with the first one selected. I then select the second one but the list still shows me having selected the first one. I then select the third shader which makes the list show me having selected the second shader.

The text editor portion where you do the shader writing does update correctly. Making this purely a visual bug.

### Steps to reproduce

Open the Shader Editor, create or load 2 or more shaders and try to switch between them using the list on the left of the Shader Editor.

**Comment by Chaosus** [comment]
I think it is already fixed by https://github.com/godotengine/godot/pull/65993 ? If I'm wrong, correct me.

**Comment by Skywolf285** [comment]
Yup! this is fixed in Beta2 thanks to that PR. Closing the issue.
