### ISSUE TITLE
Message pops-up says "Runtime Crash Occurred"

### ISSUE THREAD

**Issue by NeXuS4Developer** [godotengine/godot#66173]
### Godot version

3.5-stable

### System information

Arch Linux x86_64, Intel i7-67000K, GeForce GTX 960

### Issue description

Whenever i opening godot a message pops-up and says "Runtime Crash Occurred" i don't know why it is happening. But godot worked for me before.

### Steps to reproduce

1. Open godot
2. The error occurs

**Comment by lawnjelly** [comment]
If you can run a debug version:
https://github.com/Calinou/godot-debug-builds/releases

This might give more info for the crash, maybe a stack trace.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.
