### ISSUE TITLE
Quick Open dialog is impossibly slow in big projects

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#66179]
### Godot version

4.0 c44e1c4

### System information

Windows 10 x64

### Issue description

Regression from #62417

https://user-images.githubusercontent.com/2223172/191370606-8f6edfbe-13d2-4c4d-9a0c-6819059b0bc7.mp4

Opening quick open dialog in any way will completely freeze the editor for a veeeeeeery long time.

### Steps to reproduce

1. Open some *big project* (lots of scenes, resources, scripts etc., in hundreds)
2. Press Ctrl + Shift + O

**Comment by jtnicholl** [comment]
In my project it prints a bunch of the "AABB size is negative" messages from #60853 once it finally shows up. It's like it's loading and instantiating every scene in the project for some reason.

**Comment by tinmanjuggernaut** [comment]
Yep, `Quick Open`, `Quick Open Script`, and `Quick Open Scene` open and instantiate all of my scenes and assets, dumping thousands of errors to the console until the engine finally crashes. 

On windows, the quick open commands are Ctrl+Alt+O, Ctrl+Shift+O and Alt+Shift+O.

**Comment by akien-mga** [comment]
See #66215.
