### ISSUE TITLE
Godot Editor crashing when setting SurfaceOverrideMaterial

### ISSUE THREAD

**Issue by isolin** [godotengine/godot#66175]
### Godot version

4.0-beta1

### System information

Ubuntu Mate 20.04, nividia-470 driver, RTX 3060 Ti

### Issue description

The editor crashes with `8527 Segmentation fault` when I try to create a new StandardMaterial3D for SurfaceOverrrideMaterial.

### Steps to reproduce

1. Create a new `Vulcan Clustered` project
2. Add a 3D Scene
3. Add a MeshInstance3D
4. Assign it a new BoxMesh
5. Assign it a new StandardMaterial3D as `Surface Override Material`
6. Click on the new material to edit it -> **crash**

**Comment by clayjohn** [comment]
Could you please post the entire contents of the error you receive?

I can't reproduce the crash running on my device. Beta 1 PopOS 22.04 intel integrated graphics

**Comment by isolin** [comment]
When I first encountered the bug inside of my project, there was the `Segmentation Fault`. But when I go through the steps to reproduce, even with `--verbose` there is nothing. It just quits. Is there any log file or crash dump I could post?

**Comment by clayjohn** [comment]
I'm not sure perhaps @Calinou knows.

**Comment by 3p0ch-NG** [comment]
I'm also occasionally getting crashes when editing StandardMaterial3D resources in Windows. It doesn't always happen, but occasionally the editor crashes when I have the StandardMaterial3D resource open for editing and attempt to expand one of the property groups. The editor simply closes without any error messages.

Godot version: 4.0 beta 1 official
System: Windows 11 Home, version 21H2

**Comment by isolin** [comment]
I tried again with beta10 using the OpenGL compatibility renderer. Vulkan doesn't kick off at all, but that's another issue. The problem described above seems to work fine now, no more crashes, hence I am closing this issue.
