### ISSUE TITLE
"Add Feature" button in "Advanced Import Settings" window for opentype font seems not working.

### ISSUE THREAD

**Issue by slmnll** [godotengine/godot#66189]
### Godot version

4.0.beta1.official

### System information

macOS 11.5.2 / iMac (Retina 5K, 27-inch, 2017)

### Issue description

It seems the context menu which should be shown doesn't appear when the `OpenType Features > Add Feature` button in `Advanced Import Settings` window pressed. 

I can tell that the button itself is reacting to the mouse click because I can recognize a tiny 'context menu-ish something' appears below the button after the click. I think it just doesn't contain any items. (Please check the attached movie file carefully to see the empty context menu.)

### Steps to reproduce

1. create a new project file
2. import a font file
3. double click the font file and open the `Advanced Import Settings` window
4. click the `Add Feature` button under the `OpenType Features`
5. **the context menu doesn't appear**

- I tried same operation by using TTF and OTF files and the file type doesn't affect to the matter.
- The same `Add Feature` button in `FontVariations` resource inspector always works properly.

https://user-images.githubusercontent.com/52518972/191382574-5fe38f24-c982-4da8-ad22-1ff24273ea3c.mov

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by bruvzg** [comment]
OpenType features are specific to the font, seems like one you are using do not have any, which is indicated by `Features (0 of 0 set)`.

If some were supported, the menu would look like this:
<img width="1014" alt="Screenshot 2022-09-22 at 07 42 30" src="https://user-images.githubusercontent.com/7645683/191660249-4b7a3de3-546d-4177-b132-6737fbf24cfd.png">

_Note: Some features (like required ligatures, and  low-level features related to the complex text layouts) are non-user controllable and not displayed in the list._

**Comment by akien-mga** [comment]
Maybe we can hide the button if no features are supported? And maybe change the label from "Features (0 of 0 set)" to "No supported features" or similar.
