### ISSUE TITLE
Same type of node (Raycast) with exactly the same values delivers a different behaviour

### ISSUE THREAD

**Issue by OmegaEd** [godotengine/godot#66186]
### Godot version

3.4.4 - Stable

### System information

Wirdows 7 GLES2

### Issue description

First of all, sorry for any grammar mistakes in advance, its not my main lenguage, and its my first post. I have a Raycast (3D) that is meant to detect the floor for a KinematicBody. The Body CollisionShape is a Capsule. The floor hes on its a StaticBody with a Boxshape CollisionShape. The raycast is child node of the KinnematicBody and its set to exclude the parent. No other script or node interact in any way with the raycast.
The issue is that when i Enabled my Raycast, it detects the floor sometimes and sometimes it doesnt (in the course of a second, 40 times it will detect it and 20 it wont). I was for hours triying to figure out whats wrong in my code with no luck. Finally, i simply decided to use the same kind of node, with exactly the same values... and it works fine, so in theory the problem is solved. However,  my conclusion is that the problem was not the script, but this particular instance of the raycast. My question is, is this a known issue? can the node become corrupted somehow over time?.

Here we can see 2 identical pairs (all the values are the same) of 3 raycasts (3 of them work fine and 3 of them dont)
![imagen](https://user-images.githubusercontent.com/114031497/191377470-9570f5c6-643b-45dd-a396-468a61a1bb21.png)

![imagen](https://user-images.githubusercontent.com/114031497/191377400-004f3de5-4bb8-46e3-adb6-cf305aa54920.png)

![imagen](https://user-images.githubusercontent.com/114031497/191377146-2825c909-114f-4ae4-8f76-abad9b754806.png)

When i switch the names of the raycast (not switching any code or properties), it works fine:
![imagen](https://user-images.githubusercontent.com/114031497/191378135-fbbfd4f2-2a8b-4eeb-88b2-ad1ad4499222.png)
![imagen](https://user-images.githubusercontent.com/114031497/191378160-19adaf43-3384-4d15-8efd-2bbf5e8076e1.png)

### Steps to reproduce

I guess this is the biggest problem... any new raycast that i create will work fine, i cant reproduce it. Since my project actually works fine now, i dont have an issue, but i thought it would be best to report it and maybe save someone else a lot of frustrating hours triying to solve something similar.

**Comment by Calinou** [comment]
@OmegaEd Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

(It's possible that the issue is part of your game logic rather than the engine.)

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.
