### ISSUE TITLE
Scene import - specify user clips in frames, not seconds

### ISSUE THREAD

**Issue by ret80** [godotengine/godot#6618]
**Operating system or device - Godot version:**
win godot 2.1

**Issue description** (what happened, and what was expected):
I downloaded this model:
https://shop.bitgem3d.com/collections/free-3d-models/products/low-poly-zombie-commoner

Imported "fbx" it in a blender and exported in the "DAE" (using the standard export and also via "godotengine/collada-exporter")

I created a new project and tried to import the "dae" in it. just before you set up the import tab "Animation Options: Clips"
The animation is not broken up into clips. All clips appear in the player but were empty.

**Steps to reproduce:**

1 select inport
2 select dae file
3 add user clips in "Animation Options: Clips"
4 import and open
5 test user animation clips

**Link to minimal example project** (optional but very welcome):

**Comment by reduz** [comment]
This option is so you make the clips yourself

**Comment by ret80** [comment]
@reduz 
I understand that by using this option, one long animation can not be split into several smaller?

**Comment by ret80** [comment]
I figured why not work. I pointed out the frames as these were in them and had to be second. I did not notice :)
You can do as the possibility to specify in frames?

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.
