### ISSUE TITLE
Mesh AABB not preserved on ResourceSaver.save

### ISSUE THREAD

**Issue by epes** [godotengine/godot#66192]
### Godot version

v4.0.beta1.official.20d667284

### System information

MacBook Air (M2, 2022)

### Issue description

I am creating a mesh with vertex data which returns its AABB on calling `get_aabb()`. When I save that mesh into a `resource_path` using `ResourceSaver.save(mesh, resource_path)` the AABB is set to `AABB(0, 0, 0, 0, 0, 0)` rather than preserving the existing AABB.

I would expect this AABB to be preserved and saved to the resource. When loading the mesh using `ResourceLoader.load(resource_path)`, calling `get_aabb()` on the mesh returns the zeroed out AABB.

Context on use case: I am iterating over existing meshes in a CLI script and merging them as separate surfaces in a single mesh. Before saving, all of the input meshes and the merged mesh return a valid AABB. When saved, the mesh resource shows the zeroed AABB.

### Steps to reproduce

`incorrect_aabb.gd`
```gdscript
#!/usr/bin/env -S godot -s
extends SceneTree

func _init():
    # TUTORIAL CODE TO GENERATE A MESH
    # https://docs.godotengine.org/en/latest/classes/class_arraymesh.html#description
    var vertices = PackedVector3Array()
    vertices.push_back(Vector3(0, 1, 0))
    vertices.push_back(Vector3(1, 0, 0))
    vertices.push_back(Vector3(0, 0, 1))

    # Initialize the ArrayMesh.
    var arr_mesh = ArrayMesh.new()
    var arrays = []
    arrays.resize(Mesh.ARRAY_MAX)
    arrays[Mesh.ARRAY_VERTEX] = vertices

    # Create the Mesh.
    arr_mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
    # END OF TUTORIAL CODE

    var resource_path = "mesh.tres"
    ResourceSaver.save(arr_mesh, resource_path)
    print("pre-save mesh", " ", arr_mesh.get_aabb())
    ## pre-save mesh [P: (0, 0, 0), S: (1, 1.00001, 1)]
    var loaded_mesh = ResourceLoader.load(resource_path)
    print("loaded mesh", " ", loaded_mesh.get_aabb())
    ## loaded mesh [P: (0, 0, 0), S: (0, 0, 0)]
```

running the above script with 
```
 godot --headless -s incorrect_aabb.gd
```

produces this `.tres`
```
[gd_resource type="ArrayMesh" format=3]

[resource]
_surfaces = [{
"aabb": AABB(0, 0, 0, 0, 0, 0),
"format": 1,
"primitive": 3,
"vertex_count": 3,
"vertex_data": PackedByteArray(0, 0, 0, 0, 0, 0, 128, 63, 0, 0, 0, 0, 0, 0, 128, 63, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 63)
}]
```

**Comment by Calinou** [comment]
I suppose this occurs because Godot expects to always be able to recalculate the AABB on-the-fly.

**Comment by epes** [comment]
> I suppose this occurs because Godot expects to always be able to recalculate the AABB on-the-fly. However, headless mode can't do this as its RenderingServer implementation uses stub methods that don't do anything.
> 
> Out of curiosity, can you reproduce this on 3.5 with a similar setup (headless binaries)?

I can confirm it does work as expected if I remove `--headless` on 4.0. Perfect, there is a workaround then for now.

**Comment by epes** [comment]
Running this on 3.5 is showing the expected behavior (saves the mesh with the AABB preserved):

`incorrect_aabb.gd`
```gdscript
#!/usr/bin/env -S godot -s
extends SceneTree

func _init():
    # TUTORIAL CODE TO GENERATE A MESH
    # https://docs.godotengine.org/en/stable/classes/class_arraymesh.html#description
    var vertices = PoolVector3Array()
    vertices.push_back(Vector3(0, 1, 0))
    vertices.push_back(Vector3(1, 0, 0))
    vertices.push_back(Vector3(0, 0, 1))
    # Initialize the ArrayMesh.
    var arr_mesh = ArrayMesh.new()
    var arrays = []
    arrays.resize(ArrayMesh.ARRAY_MAX)
    arrays[ArrayMesh.ARRAY_VERTEX] = vertices
    # Create the Mesh.
    arr_mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
    # END OF TUTORIAL CODE

    var resource_path = "mesh.tres"
    ResourceSaver.save(resource_path, arr_mesh)
    print("pre-save mesh", " ", arr_mesh.get_aabb())
    ## pre-save mesh 0, 0, 0 - 1, 1, 1
    var loaded_mesh = ResourceLoader.load(resource_path)
    print("loaded mesh", " ", loaded_mesh.get_aabb())
    ## loaded mesh 0, 0, 0 - 1, 1.00001, 1

    quit()
```

```
godot35 --no-window -s incorrect_aabb.gd
```

produces this `.tres`
```
[gd_resource type="ArrayMesh" format=2]

[resource]
surfaces/0 = {
"aabb": AABB( 0, 0, 0, 1, 1.00001, 1 ),
"array_data": PoolByteArray( 0, 0, 0, 0, 0, 0, 128, 63, 0, 0, 0, 0, 0, 0, 128, 63, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 63 ),
"array_index_data": PoolByteArray(  ),
"blend_shape_data": [  ],
"format": 2194433,
"index_count": 0,
"primitive": 4,
"skeleton_aabb": [  ],
"vertex_count": 3
}
```

3.5 Project:
[incorrect_aabb_35.zip](https://github.com/godotengine/godot/files/9617334/incorrect_aabb_35.zip)

**Comment by epes** [comment]
> > I suppose this occurs because Godot expects to always be able to recalculate the AABB on-the-fly. However, headless mode can't do this as its RenderingServer implementation uses stub methods that don't do anything.
> > Out of curiosity, can you reproduce this on 3.5 with a similar setup (headless binaries)?
> 
> I can confirm it does work as expected if I remove `--headless` on 4.0. Perfect, there is a workaround then for now.

To add as well, printing `.get_aabb()` works correctly for the in-memory mesh in the headless script. It seems to be ok calculating the AABB in that regard just not saving it. I don't know if those utilize different rendering code.

**Comment by epes** [comment]
Re-checked the same example in v4.3dev6 and it's working correctly, it was fixed at some point! Thank you!
