### ISSUE TITLE
ItemList, text line breaking problem

### ISSUE THREAD

**Issue by xiaoliang6669** [godotengine/godot#66193]
000000000000000000

**Comment by akien-mga** [comment]
Please provide a minimal reproduction project, or detailed steps to reproduce, when you open bug reports. Contributors need to know how you're setting things up exactly to assess if there is a bug or just a misunderstanding of the API.

See the Max Text Lines property's documentation:

![image](https://user-images.githubusercontent.com/4701338/191490581-056435f4-5943-4185-986e-9a82ef869b64.png)

Configuring things accordingly makes text wrapping work:
![image](https://user-images.githubusercontent.com/4701338/191490629-38ccaf19-e291-4c7e-ab6c-0db3eebae57b.png)

Content seems to be centered, I don't know if the alignment can be configured.

Overall it does feel somewhat complex/convoluted, there might be room for improvement here @godotengine/gui-nodes. Especially when not using an icon like in my example yet I still need to set the icon mode to be able to get wrapping.
