### ISSUE TITLE
[4.0b1] Missing some bones in root motion track selection window

### ISSUE THREAD

**Issue by PoqXert** [godotengine/godot#66190]
### Godot version

4.0.beta1

### System information

Windows 10

### Issue description

Godot 4.0 does not show some bones in root motion track selection window. It does not depend on the presence of animation.
Godot 3.5 does not have this problem.

Blender:
![blender](https://user-images.githubusercontent.com/3893594/191387104-472d919b-bf92-4b07-b0b8-5230874341e4.png)

Godot 3.5:
![godot35](https://user-images.githubusercontent.com/3893594/191387826-ea7bf655-9af7-4a03-8be5-03c4ce178f60.png)

Godot 4.0b1:
![godot40b](https://user-images.githubusercontent.com/3893594/191387918-7814cb29-7fd1-49df-8b98-d7c6bc6d32f9.png)

### Steps to reproduce

1. Import test.glb
2. Create Inherited Scene.
3. Add AnimationTree (and setup AnimationPlayer for it).
4. Try add root motion track.

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/9612023/test.zip)

**Comment by TokageItLab** [comment]
I guess this is because there is no animation track for that bone. Perhaps, considering the possibility of retargeting, it might be better to candidate all bones, even if that bone does not have a track.
