### ISSUE TITLE
Captured mouse causes get_local_mouse_pos() to return crazy Y values

### ISSUE THREAD

**Issue by sketchyfun** [godotengine/godot#6620]
**Operating system or device - Godot version:**
Windows 7
Godot 2.2 compiled from source on 15/09/2016

**Issue description** (what happened, and what was expected):
When setting Input.set_mouse_mode() to MOUSE_MODE_CAPTURED, any calls to get_local_mouse_pos() or get_global_mouse_pos() returns values like the examples below:

(-160, 1068756672)
(-159.5, 534378304)
(-194.5, 534378400)

**Steps to reproduce:**
Run the project attached and see the printed output. ESC will close the example since the mouse is captured.

**Link to minimal example project** (optional but very welcome):
https://dl.dropboxusercontent.com/u/3292249/mouse_capture.zip

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by sketchyfun** [comment]
Just checked on a fairly recent build from master and the problem appears to be fixed, so I'll close this now.
