### ISSUE TITLE
Using sampler2D as global_uniform in a shader crashes engine on startup of fresh project

### ISSUE THREAD

**Issue by Piet-G** [godotengine/godot#66211]
### Godot version

4.0.beta1

### System information

Mac OS Monterey 12.6 and Windows 10

### Issue description

When opening a freshly cloned copy of a project with a shader using a global sampler2d uniform the engine crashes immediately without error messages

### Steps to reproduce

- Create a shader with a global uniform of type Sampler2D
- Create a material for that shader
- Save the material
- Apply it to a mesh
- Copy or clone the project
- Open the project

The crash does **not** occur on the copy of the project you created the shader in

### Minimal reproduction project

[GodotBetaGlobalUniformCrashReproductionProject.zip](https://github.com/godotengine/godot/files/9616863/GodotBetaGlobalUniformCrashReproductionProject.zip)

Alternatively clone this repo: [https://github.com/Piet-G/BotanicaGame.git](https://github.com/Piet-G/BotanicaGame.git)

**Comment by Piet-G** [comment]
After some more tests, it seems that it is still crashes when the sampler isn't even global. This seems like a major bug

**Comment by Chaosus** [comment]
Probably some importing bug - you can fix it by deleting the .godot folder before running the project.

**Comment by Piet-G** [comment]
It can't be that, the .godot folder isn't checked in in git and it breaks even when opening it from a fresh clone

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/62941.

**Comment by Chaosus** [comment]
I think it's fixed (running the attached project does not crash). Probably fixed by https://github.com/godotengine/godot/pull/69600.
