### ISSUE TITLE
Cannot import `.bmp` files with alpha channel support

### ISSUE THREAD

**Issue by Arecher** [godotengine/godot#66238]
### Godot version

3.5.stable

### System information

Windows 10, GLES3

### Issue description

Importing new `.bmp` files exported from Aseprite into Godot causes them to fail to import, due to being 'corrupted'.

`ERROR: Condition "line_ptr >= end_buffer" is true. Returned: ERR_FILE_CORRUPT
   at: convert_to_image (modules/bmp/image_loader_bmp.cpp:100)
ERROR: Error loading image: res://example_solid.bmp
   at: load_image (core/io/image_loader.cpp:68)
ERROR: Error importing 'res://example_solid.bmp'.
   at: _reimport_file (editor/editor_file_system.cpp:1759)`

However, the files are completely valid and can be opened using Windows, Aseprite, etc. I tracked down the difference between the old .bmp files in my project, and the newly added ones, to a change made to how Aseprite loads and exports .bmp files. (as you can read about here: https://github.com/aseprite/aseprite/pull/3486). They have expanded their support for the file type, which seems to mean it exports into a different, but completely valid, version of .bmp files. In this case one that supports Alpha channels.

However Godot doesn't seem to support this specific .bmp format, causing .bmp files to "corrupt" on import. Seems support for these bmp files needs to be added.

I tried to figure out which type of BMP i'm dealing with, but I haven't been able to determine that. 

### Steps to reproduce

[bmpfiles.zip](https://github.com/godotengine/godot/files/9621090/bmpfiles.zip)

1. Unpack the ZIP. It contains three different .bmp files.
- _old_valid_bmp_ : a simple .bmp file type with only black and white colors.
- _fail_example_transparency_ : a .bmp file type with a transparent background.
- _fail_example_solid_ : a .bmp file type with a black background, and support for alpha channels
2. Import the files into a Godot project
3. The _fail_ bmps will fail to import

### Minimal reproduction project

NA

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/pull/65717.

**Comment by Ithamar** [comment]
this is still broken in `4.0beta1`, as I was planning to look at 16-bit BMP support anyway, I'll have a look at this as well.

**Comment by Ithamar** [comment]
Okay, after some further investigation, it turns out that these files are actually broken. The fields `bmp_file_header.bmp_file_size`  and `bmp_info_header.bmp_size_image` are incorrectly set, and that breaks the Godot BMP loader.
It seems that most BMP loader implementations ignore these fields, that's why e.g. Windows itself and other programs have no problem reading these.

So, I guess this bug should be reported to the `aseprite` project so they can fix their BMP save code.

**Comment by Arecher** [comment]
> So, I guess this bug should be reported to the aseprite project so they can fix their BMP save code.

I'll report it there! Thank you for investigating!

**Comment by Ithamar** [comment]
So I think this issue can be closed, as it turned out to be a bug in 3rd party software (which, by now, is actually fixed too)

**Comment by Calinou** [comment]
Closing per @Ithamar's comment.
