### ISSUE TITLE
AnimationPlayer changes permanently position of the bones in the scene.

### ISSUE THREAD

**Issue by rarsp** [godotengine/godot#66243]
### Godot version

4.0 beta 1 mono

### System information

Windows 10

### Issue description

AnimationPlayer changes permanently position of the bones (rest positions?) in the scene.

### Steps to reproduce

1. Import model with skeleton.
2. Create AnimationPlayer
3. Create basic animation of some bone
4. Play animation
5. Delete AnimationPlayer
6. See that position of the bone is left as it was last playing in the AnimationPlayer

**Comment by TokageItLab** [comment]
This is the same for all parameters except bones. It is not a bug, it is expected behavior. You can use `Skeleton3D::reset_bone_poses()` implemented in #63486.
