### ISSUE TITLE
`File` and `Directory` aren't declared - replaced by `FileAccess` and `DirAccess` in #65271

### ISSUE THREAD

**Issue by unlessgames** [godotengine/godot#66241]
### Godot version

4.0 commit e5c5447

### System information

Linux 64bit

### Issue description

I'm getting this error with a custom build of Godot using the latest commit on master when trying to use File.new().

`SCRIPT ERROR: Parse Error: Identifier "File" not declared in the current scope.`

Tried building from the commit of the official beta as well and that runs fine.

### Steps to reproduce

* Build Godot (on Linux) from this commit e5c5447.

* Create an empty scene with a script that uses `File`

**Comment by akien-mga** [comment]
This is intended, `File` and `Directory` wrappers have been replaced by directly exposing the underlying `FileAccess` and `DirAccess`: #65271.

So you should now use it like `var file = FileAccess.open("user://save_game.dat", FileAccess.READ)` (see the `FileAccess` docs in the engine).

I'll pin this issue for others who might be similarly surprised by the change.

**Comment by unlessgames** [comment]
Thank you for the info!

**Comment by h0lley** [comment]
there's little purpose to such a wrapper class, the new usage is pretty much identical, just less code:
```swift
var file := FileAccess.open(path, FileAccess.READ)
var text := file.get_as_text()
```
