### ISSUE TITLE
No way to access the project theme through script

### ISSUE THREAD

**Issue by markdibarry** [godotengine/godot#66277]
### Godot version

4.0.dev (7da532275b)

### System information

Windows 10

### Issue description

When trying to access the theme of a `Control`, if inheriting a project custom theme, it returns `null`. The only way possible to access the current theme is to get the path to the custom theme set in the project settings, and then loading the resource, which is probably not the intended method.

### Steps to reproduce

Access the `theme` property of a `Control` when a custom theme is set for the project.

### Minimal reproduction project

[CustomTheme.zip](https://github.com/godotengine/godot/files/9629660/CustomTheme.zip)

**Comment by Calinou** [comment]
This is expected. That said, this begs the question whether the `theme` property should be renamed to `theme_override`.

**Comment by markdibarry** [comment]
My first assumption when trying to access it, was that if no theme was specified, it'd get whichever was active. i.e. I assumed "theme" meant "current theme".

If this isn't the desired behavior, maybe a globally accessible way to access the project theme would be better. In that case, the user could determine which theme is active, by checking the theme, and then checking the project theme if it returns `null`.

**Comment by KoBeWi** [comment]
Why do you want to get the theme though? You can access all of its defined theme properties via Control methods.

**Comment by markdibarry** [comment]
Oh, you're absolutely right. My (incorrect) assumption was reached for a few reasons:
1. Considering the theme didn't refer to the current theme and returned `null`, the theme properties wouldn't refer to the current theme properties either.
2. I wasn't able to confirm this until now since the `theme_name`/`theme_type` stuff is lacking in documentation currently (it is beta, after all) so it took awhile to figure out what string values it expected.
3. I actually had asked around on the Discord and no one seemed to be aware that they were accessible, so this is good information to have.
4. I assumed since `theme` is a property of all `Control`s, that it was the intended way of accessing theme properties.

My only concern when reporting this was that theme properties were mainly unreachable if project-wide. Since this isn't the case, maybe this is more of just a documentation issue? If not, feel free to close.

**Comment by markdibarry** [comment]
It's been awhile, but I think the documentation has been updated and looks good.
