### ISSUE TITLE
C# project hangs and crashes editor with blank white window after random number of launches

### ISSUE THREAD

**Issue by MBoffin** [godotengine/godot#66270]
### Godot version

v4.0.beta1.mono.official [4ba934bf3]

### System information

Vulkan (all)
SYSTEM 1: Win10/AMD Ryzen 5 5600X/RTX 2070 Super (v512.15)
SYSTEM 2: Win11/i9-12900k/RTX 3090 (v516.94)
SYSTEM 3: Win10/AMD Ryzen 5 3600/GTX 1650 Super (v516.59)

### Issue description

When I launch my project from the editor, it will often crash hard with a blank white window between the game window and the editor, and the crash takes the editor with it. It doesn't consistently crash _every_ time I launch the project, though sometimes it does crash on first launch. Sometimes I can launch the project 2 or 3 times in a row, or sometimes even 9 times, but it _will_ crash eventually. I've linked a video below of what is happening, with the editor's console window running in `--verbose` mode.

At first I thought it was something in my code, so I kept distilling the project down to less and less, and yet it would still happen. Eventually I got my project down to almost nothing, and it still crashed. Then I even built that extremely simple project from the ground up (attached below), but it still crashes.

Searching around, it _seemed_ similar to #57273 or #20566, but I tried on 3 entirely different computers with totally different peripherals (and one of them only had an extremely basic keyboard and simple $5 mouse attached, just to make sure) and it would behave consistently (read: randomly crash) as described above.

I'm using .Net SDK 6.0.401 64-bit LTS on all 3 computers.

Another piece of data: In two different Discords, I had others try to duplicate the behavior, and while they weren't getting the same crash I was, they said the editor would crash for them as soon as they opened the Project Settings. (One person said they thought it was possibly related to the `.godot` folder.)

### Steps to reproduce

1. Load attached CStest project.
2. Press the Play button (or F5)
3. If it doesn't crash, close the game window (or F8) and go to Step 2.

### Minimal reproduction project

[CStest.zip (7mb)](https://github.com/godotengine/godot/files/9627485/CStest.zip)

[Video of it crashing after 4th launch, then opening editor again and having it crash immediately after first launch (1m31s)](https://drive.google.com/file/d/1Umj4BvXyEeZ470IeAxFenCK7T8KEcFut/view)

**Comment by evvv-vvve** [comment]
Can confirm I'm experiencing this issue in Godot 4 Beta 4

**Comment by akien-mga** [comment]
Can you still reproduce this in 4.0.3 and 4.1-beta3 or later?

**Comment by KoBeWi** [comment]
Closing due to lack of response.
Comment if you can still reproduce in the newest version of Godot.
