### ISSUE TITLE
Opacity of SSR unaffected by material roughness

### ISSUE THREAD

**Issue by aaandreeew** [godotengine/godot#66285]
### Godot version

4.0 beta1

### System information

Windows 10 (x86_64), Vulkan, Intel Core i5-8265U with UHD Graphics 620 (31.0.101.2111)

### Issue description

The roughness of a material does not affect the opacity of screen space reflections seen in the material. This means that a material with a roughness of 1.0 and metallic of 0.0 will still have obvious reflections.

I expected that these parameters would produce a completely matte material, but I can't make any completely matte materials at all. However, reflections from VoxelGI nodes or SDFGI do consider roughness for reflection opacity, and a roughness of 1.0 will produce a completely matte material.

**Screen Space Reflections have equal opacity on 3 floor materials with metallic 0.0 and roughness 1.0, 0.5 and 0.0 left to right**
![TEMP6](https://user-images.githubusercontent.com/114206308/191898340-9b584353-79cc-489a-9b45-de324e788eb4.png)

**Comparison between VoxelGI reflections (left) and SSR (right).  Roughnesses are 1.0, 0.2 and 0.0 left to right.**
![TEMP7](https://user-images.githubusercontent.com/114206308/191898346-8469823a-b07a-434f-89be-430039683ed1.png)
I think SDFGI behaves correctly too, but I am experiencing a separate visual bug with SDFGI, hence I haven't shown it.

This is apparent in another sample scene with more realistic materials. The ground material has a roughness of 1.0. This issue is ruining any prospects of a realistic scene for me.

**SSR in different scene with proper PBR materials — reflections abound**
![TEMP1](https://user-images.githubusercontent.com/114206308/191901914-c6796ae2-f544-4a36-a16a-9da80250c006.png)

I believe this is the same kind of issue as [#49402](https://github.com/godotengine/godot/issues/49402), which was reported for Godot 3.2.2 and was apparently fixed in the master branch according to [#25112](https://github.com/godotengine/godot/issues/25112), the issue [#49402](https://github.com/godotengine/godot/issues/49402) was merged into. I am still posting this because Vulkan is now being implemented instead of GLES 3 and this bug may be specific to the graphical problems I've experienced with Intel inegrated graphics.

### Steps to reproduce

1. Create a Node3D containing a ground plane MeshInstance3D and box MeshInstance3D.
2. Create a material (StandardMaterial3D or ORMMaterial3D) with metallic = 0.0 and roughness = 1.0 and apply it to the ground mesh. The albedo doesn't matter.
3. Enable SSR in a WorldEnvironment node, increasing the _Max Steps_ value to improve visibility.

### Minimal reproduction project

[ssr_opacity_roughness_bug.zip](https://github.com/godotengine/godot/files/9631069/ssr_opacity_roughness_bug.zip) (for Godot 4.0 beta 1)

**Comment by aaandreeew** [comment]
Edits: Minor changes to wording and formatting. Changed an image to replace an incorrect one.

**Comment by aaandreeew** [comment]
Sorry, I pressed the wrong button :|

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/61930 (see its fix https://github.com/godotengine/godot/pull/65594).

**Comment by josefkaragoli** [comment]
> Related to https://github.com/godotengine/godot/issues/61930 (see its fix https://github.com/godotengine/godot/pull/65594).

That was about a metallic value of 0 not showing any reflections, whilst this issue is about roughness value not having an effect on ssr.

**Comment by aaandreeew** [comment]
Woohoo!
