### ISSUE TITLE
Reimporting files as a TextureAtlas freezes the editor

### ISSUE THREAD

**Issue by chrisizeful** [godotengine/godot#66287]
### Godot version

Godot_v4.0-beta1_mono

### System information

Windows 10, Vulkan Clustered, NVIDIA GeForce GTX 1660 Ti

### Issue description

Attempting to re-import assets as a TextureAtlas file causes the editor to freeze upon restarting. An in-editor window appears saying that it is (Re)Importing Assets. A separate, empty window appears as well. The .png and .import files are successfully generated. If you force close Godot and delete the generated files, the editor will start up fine and re-generate them. The editor will not start up correctly if you do not delete the generated files first. Note all TextureAtlas import settings were kept on their default values, except for specifying a path.

### Steps to reproduce

1. New project
2. Drag some image files into project folder
3. Select all image files in editor FileSystem window
4. Import -> Import As: Texture Atlas -> Choose an atlas path
5. Reimport

**Comment by akien-mga** [comment]
Please explain why you're closing it, we don't know if you found a workaround but the bug is still valid, or if you realized that the bug is not valid.
