### ISSUE TITLE
`Condition "least_cost_id == -1" is true.` Error using `NavigationAgent2D` on `TileMap` for `autotile`

### ISSUE THREAD

**Issue by MrPaiZi** [godotengine/godot#66283]
### Godot version

v3.5.stable.official [991bb6a]

### System information

Windows 10

### Issue description

When I use `NavigationAgent2D` on `autotile`, it works weird and keeps emitting a lot of error:
```
E 0:00:01.973   get_path: Condition "least_cost_id == -1" is true. Breaking.
  <C++ Source>  modules/navigation/nav_map.cpp:263 @ get_path()
  <Stack Trace> Player.gd:12 @ _physics_process()
```
![bug](https://user-images.githubusercontent.com/39019460/191887136-3a7a49d8-4b1c-45b3-bfea-82a47265926c.png)
<img src="https://user-images.githubusercontent.com/39019460/191883174-51c08353-d992-4798-84f7-1e508fa79148.png" alt="nav" width="400"/>
Sometimes the `Player` moves and sometimes it doesn't. I can't describe it simply, check minimal reproduction project for details.

### Steps to reproduce

Run MRP. It has 3 Scenes, with the same code, different type of map.
- `World_bug`: use autotile, works weird and emits error.
- `World_tile`: use single tile, works fine.
- `World_poly`: use navigation polygon, works fine.

### Minimal reproduction project

[bug.zip](https://github.com/godotengine/godot/files/9630582/bug.zip)

**Comment by MrPaiZi** [comment]
I just changed the autotile navigation polygon to concise graphics and the bug is gone.
from <img src="https://user-images.githubusercontent.com/39019460/191883174-51c08353-d992-4798-84f7-1e508fa79148.png" alt="before" width="360"/> to <img src="https://user-images.githubusercontent.com/39019460/191888943-2af5337b-71d5-4aef-aef1-ba9b7a21c356.png" alt="before" width="360"/>

**Comment by kleonc** [comment]
It's caused by a duplicated top-left vertex / zero-length edge in the navigation polygon of this tile:
![Godot_v3 5-stable_win64_ipWifzba13](https://user-images.githubusercontent.com/9283098/191949427-9cfe2b79-6697-4dd8-8c52-4dc681f0a41b.png) ![GmUFRBrfxE](https://user-images.githubusercontent.com/9283098/191949690-370e3ebd-d2c9-47d3-9766-074b704710c2.gif)
```
[sub_resource type="NavigationPolygon" id=76]
vertices = PoolVector2Array( 0, 0, 8, 0, 8, 8, 0, 8 )
polygons = [ PoolIntArray( 0, 1, 2, 3, 0 ) ]
outlines = [ PoolVector2Array( 0, 0, 0, 8, 8, 8, 8, 0, 0, 0 ) ]

0/autotile/navpoly_map = [ ... , Vector2( 5, 1 ), SubResource( 76 ), ...]
```

It results in NaNs in the calculations down the line (div by zero). Either duplicated vertices should be removed when generating the nav map or it should be taken into account in the calculations that such cases can happen.


@MrPaiZi So you can use polygons like the ones you have in MRP, just ensure there are no duplicated vertices in them (at least until it's fixed).

**Comment by zinefer** [comment]
Thanks for that explanation. Atleast for me, `v4.0.beta7.mono.official` was placing multiple duplicated points when setting my navigation polygon to the default tile shape in an isometric tileset.

**Comment by kleonc** [comment]
> Thanks for that explanation. Atleast for me, `v4.0.beta7.mono.official` was placing multiple duplicated points when setting my navigation polygon to the default tile shape in an isometric tileset.

Hmm, it could be the case as for some reason isometric tiles are generated as 6-point polygon with 2 points being duplicated:
https://github.com/godotengine/godot/blob/a7937fe54cd2c1f407a529e46e2708aea5ce7243/scene/resources/tile_set.cpp#L1439-L1475

cc @groud

@zinefer Technically that's a separate problem. If you can please open a new issue (and in such case please provide an MRP for testing).

**Comment by smix8** [comment]
The mentioned duplicates created by input in the Editor was a Godot 4 beta issue that was fixed.

The NavigationMeshGenerator pr https://github.com/godotengine/godot/pull/70724 fixes the rest of the issues as it does bake step for the NavigationPolygon that merges all created polygons first. This merge step removes duplicates and internal polygons that users might have created by accident but can't see in the TileMap Editor.

**Comment by SteveSmith16384** [comment]
If anyone else is having this problem in 3.x, I fixed it by editing the Tileset data manually in a text editor and tidying it up.  In my case, one the of the NavigationPolygon.polygons had an extra point, just like kleonc's example further above.
