### ISSUE TITLE
MenuButton's PopupMenu doesn't open correctly from script without first clicking the MenuButton

### ISSUE THREAD

**Issue by bfedie518** [godotengine/godot#66308]
### Godot version

3.5, 4.0 Beta 1

### System information

Windows 10

### Issue description

If you open a ButtonMenu's PopupMenu from a script, it should behave as if the ButtonMenu was clicked.  Instead, it pops up in the upper left corner of the screen without a theme.

If you instead click on the ButtonMenu first, then open the PopupMenu via script, it behaves as expected.

![popupMenuBug](https://user-images.githubusercontent.com/17280776/191999647-b84d0229-451e-4359-8f13-50e7a9ef015c.gif)

### Steps to reproduce

1. Call `MenuButton.get_popup().popup()` without clicking on the menu button first.
2. Click on the menu button
3. Call `MenuButton.get_popup().popup()` again.

In the attached minimal project, pressing `F1` calls `MenuButton.get_popup().popup()`.

### Minimal reproduction project

[menu_button_bug.zip](https://github.com/godotengine/godot/files/9635098/menu_button_bug.zip)

**Comment by EricEzaM** [comment]
https://github.com/godotengine/godot/blob/f74491fdee9bc2d68668137fbacd8f3a7e7e8df7/scene/gui/menu_button.cpp#L88

It appears that the menu button does some preparation of the popup before popping up. Option button has the same code, copy paste.

https://github.com/godotengine/godot/blob/f74491fdee9bc2d68668137fbacd8f3a7e7e8df7/scene/gui/option_button.cpp#L228

This likely needs to be refactored so that configuration of the popup does not depend on it being clicked.

**Comment by bfedie518** [comment]
My first thought is to move that behavior to the constructor, but then it can't respond to the menu button being changed while running.

Maybe separate it out into a `_configure_popup()` method that gets called when the button is clicked and when `get_popup()` is called?

**Comment by EricEzaM** [comment]
Maybe `MenuButton` should have a `popup` method, which does all this for you, rather than needing to call 2 methods. So
`Before: btn.get_popup().popup()`
`after: btn.popup() or maybe `btn.open()` or something similar

**Comment by bfedie518** [comment]
I'm a fan of a new `btn.popup()` or `btn.open()` method.  It would make using the docs easier as well.  I started by looking at `MenuButton` and had to follow the inheritance tree of `PopupMenu` up to `Window` to figure out how to open it.

**Comment by bfedie518** [comment]
I put together a workaround from the code @EricEzaM linked.  Calling this instead of `btn.get_popup.popup()` works.
```
func _popup(menu_button: MenuButton) -> void:
	var adjusted_size: Vector2 = menu_button.get_size() * \
			get_viewport().get_canvas_transform().get_scale()
	var popup: PopupMenu = menu_button.get_popup()
	popup.set_size(Vector2(adjusted_size.x, 0))
	var gp: Vector2 = menu_button.get_screen_position()
	gp.y += adjusted_size.y
	if (menu_button.is_layout_rtl()):
		gp.x += size.x - popup.get_size().x
	popup.set_position(gp)

	popup.popup()
```

I couldn't figure out where `set_parent_rect()` comes from so I couldn't find a replacement.  It seems to work without that line anyway.
