### ISSUE TITLE
Default QuadMesh size incorrect?

### ISSUE THREAD

**Issue by dmaz** [godotengine/godot#66305]
### Godot version

v4.0.beta.custom_build [56e847ef6]

### System information

windows 10

### Issue description

it seems the default size for QuadMesh has been switched from 1x1 to 2x2.  I didn't go look for PRs to see if that's right yet but this seems wrong on the face of it.  breaks compatibility if 2 is right because of course the scene didn't record any size and now all your default quads are twice as big. 

edit: so when it was removed and swapped to a plane on the backend I'm pretty sure the default was still seemed to be 1x1.  it seems only now (though might be wrong about this) that quads were put back in that the default is now 2x2 which is the what planes have basically always been...  having a Quad size at 2 does seem wrong for texturing and scaling though

### Steps to reproduce

create a new QuadMesh either in MeshInstance or in GPUParticles3D drawpass and check the default size

**Comment by clayjohn** [comment]
That's my bad! It's a quick fix, I'll push a PR right away
