### ISSUE TITLE
Errors when lerping integers

### ISSUE THREAD

**Issue by RedMser** [godotengine/godot#66307]
### Godot version

4.0.dev (56e847ef653ce2b818b9f2095452b6c0c0c44d54)

Worked in Godot 4.0 alpha 11 but haven't tried bisecting further yet.

### System information

Windows 10

### Issue description

Lerping two integers results in errors.

The documentation gives the example `lerp(0, 4, 0.75) # Returns 3.0` but this causes the error `Invalid call for function "lerp".` at compile-time.

Additionally, calling `lerp(-1, 1, randf())` does not cause any compile-time error, but instead at runtime you get `Invalid call. Nonexistent utility function 'lerp'.`.

---

I assume Godot used to implicitly cast int to float here, and since int isn't supported for lerp (according to the docs), it errors now.

Expected behavior would be for the method to lerp correctly and return an int value.

### Steps to reproduce

```gdscript
extends Node

func _ready():
    var x = lerp(0, 4, 0.75)
    var y = lerp(-1, 1, randf())
```

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/64332.

**Comment by KoBeWi** [comment]
You can use `lerpf()`.
