### ISSUE TITLE
Node2D.edit_set_pivot should only set pivot not position of node

### ISSUE THREAD

**Issue by razvanc-r** [godotengine/godot#6630]
**Operating system or device - Godot version:**
v2.1.official.stable

`edit_set_pivot` moves node as well (tried with `Sprite`) but as I understand from the docs it should only move the pivot.

**Comment by razvanc-r** [comment]
I looked at it but under the hood it just sets the offset and I think that's wrong, I think it should behave like the "click to change object's rotation pivot" tool.

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by razvanc-r** [comment]
`edit_set_pivot` isn't available in v3 so I'll close this
