### ISSUE TITLE
Adjustments unintentionally affect Debanding

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#66316]
### Godot version

Godot 4.0 Beta 1

### System information

Windows 11, Vulkan, Nvidia GTX 1050 Ti, 512.15

### Issue description

Debanding is causing Visual artifacts when used with Adjustments as the Debanding shader is unintentionally affected by Adjustments

### Steps to reproduce

Toggle Debanding On, Play around with Adjustments, notice a constant pattern becoming visible as the settings are changed that isn't there when Debanding is Off

### Minimal reproduction project

[Debanding.zip](https://github.com/godotengine/godot/files/9636094/Debanding.zip)

**Comment by Calinou** [comment]
@mrjustaguy Does this issue occur in 3.5 as well?
