### ISSUE TITLE
`contacts_reported` is not renamed to `max_contacts_reported` in projects ported from earlier Godot 4 alphas

### ISSUE THREAD

**Issue by dmaz** [godotengine/godot#66311]
### Godot version

v4.0.beta.custom_build [56e847ef6]

### System information

windows 10

### Issue description

I'm not sure these should be reported but since this seems like a breaking change as it stands... this https://github.com/godotengine/godot/pull/64829 pr renamed contacts_reported to max_contacts reported.  shouldn't all these go into the conversion code?   the result of this rename just removes the setting entirely from the scene file making it a potentially difficult error to find.  easy once you know what to look for of course

### Steps to reproduce

take any old rigidbody3D with contacts_reported set and the setting will be removed from the scene file when opened in the latest main branch

**Comment by Calinou** [comment]
Is this a project ported from Godot 3? The converter only runs for those projects, not projects made with earlier Godot 4 alphas.

**Comment by dmaz** [comment]
I noticed this from an alpha project.  I looked in the PR diff for the 3-4 converter as well but apparently I didn't look very hard.  I missed that it was indeed actually there. dang.

**Comment by akien-mga** [comment]
Breaking changes during alpha development are expected, it would be impossible to preserve compatibility with any arbitrary commit when the API has been in flux in a daily basis.
