### ISSUE TITLE
Godot editor spawning zombie processes 

### ISSUE THREAD

**Issue by syskrank** [godotengine/godot#6631]
**Operating system or device - Godot version:**

debian 8 x64 ( stable )
godot 2.1 stable

**Issue description** (what happened, and what was expected):
On being instructed to use external editor, Godot spawns zombie processes of that editor and itself.

**Steps to reproduce:**

1) Set external editor in the Settings -> Editor Settings -> External editor ( click "On" and write the path to executable )

2) Open up 2-3 scenes with scripts so that external text editor will fire up showing .gd files

3) close external text editor

4) see zombie processes crawling around:

ps -A | grep defunct
     or
top

Tested and confirmed with geany and gvim. 
Observed 2-3 copies of zombie "Godot_v2.1-stab" process and a dozen of gvim or geany zombie instances.

**Comment by emersonmx** [comment]
still happening in 3.2 by the way
