### ISSUE TITLE
Converting C# does NOT rename certain things

### ISSUE THREAD

**Issue by Coder2195Text** [godotengine/godot#66321]
### Godot version

Godot 4 Beta 1

### System information

Ubuntu 22.02

### Issue description

I tried Godot 4 Beta, and Im experiencing some issues. First, RectScale isnt renamed to Scale, and _PhysicsProcess(float delta), the delta needs to be changed to double. I see its beta, so most of dev is gonna bug fixes, not features, but can u fix this bug with the converter?

Not to mention net472 in csproj should be renamed to net6.0 when converting

### Steps to reproduce

Convert https://github.com/coder2195text/tile-craft

### Minimal reproduction project

https://github.com/coder2195text/tile-craft

**Comment by Calinou** [comment]
> and _PhysicsProcess(float delta), the delta needs to be changed to double

This is intended: https://github.com/godotengine/godot/issues/65313

**Comment by Coder2195Text** [comment]
> [It should indeed be renamed](https://github.com/godotengine/godot/blob/f74491fdee9bc2d68668137fbacd8f3a7e7e8df7/editor/project_converter_3_to_4.cpp#L1099=), but is the converter even run on C# code?

Some of it gets renamed, like KimenaticBody --> CharacterBody
class also is partial class now

**Comment by akien-mga** [comment]
`RectScale` is properly converted as of 4.0 RC 6.

The `float`/`double` issue is expected and should be handled manually by users.
