### ISSUE TITLE
Y Sort not working with children of a child node

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#6632]
**Operating system or device - Godot version:**
Godot_v2.1-stable_win64.exe

**Issue description** (what happened, and what was expected):
Create a tilemap, enable Y Sort.

Add child nodes to that tilemap. Y Sort works fine for all children. But when you add a child that has its own children, Y Sort doesn't work for them.  

Example:
![image](https://cloud.githubusercontent.com/assets/10387670/18893071/22d0e9ea-84c1-11e6-8cb8-3f901d704a3a.png)

**Comment by reduz** [comment]
This is totally intended, if you had a character or object that is composed
of many sub-nodes and everything would get sorted, it would be an absolute
mess.
Current approach lets you do cool things like change the sorting pivot by
using an intermediate node.

**Comment by Dillybob92** [comment]
Hmm. You are absolutely right, that would be a mess.  What exactly do you mean by intermediate node? I'm trying to get those Monsters in a group with Y Sort. Because they change positions around the characters / map

**Comment by akien-mga** [comment]
You can make your MonsterGroup node a YSort node, that should do the trick.

**Comment by Dillybob92** [comment]
@akien-mga Nice one. It does! Thanks guys!
