### ISSUE TITLE
Cannot automatically update mouse cursor shape or visibility

### ISSUE THREAD

**Issue by zaps166** [godotengine/godot#6633]
**Operating system or device - Godot version:**
Linux/X11 and Windows, Godot 2.1-stable

**Issue description** (what happened, and what was expected):
Mouse cursor shape and visibility behaves differently in X11 and Windows - cannot automatically update cursor shape or visibility without user interaction.

**Steps to reproduce:**

X11:
- download `Mousetest` project and run, assume that mouse cursor is inside the window when it starts,
- the mouse cursor has busy icon, but it should automatically switch to pointer arrow (it does it after mouse move),
- place mouse cursor inside the window and wait 2 seconds; don't move the mouse cursor,
- mouse cursor disappears - OK,
- move mouse to show the cursor - the mouse cursor automatically changes its shape from Godot theme to system theme (sometimes it happens after second cursor visibility change). And why it doesn't have system theme on X11 as default?

Windows:
- download `Mousetest` project and run,
- place mouse cursor inside the window and wait 2 seconds; don't move the mouse cursor,
- mouse cursor doesn't disappear automatically, so you must click and don't move the mouse to achieve this (normally you can also move the mouse to hide the mouse cursor, but the script will show it).

**Link to minimal example project** (optional but very welcome):
[Mousetest.zip](https://github.com/godotengine/godot/files/497656/Mousetest.zip)

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.
