### ISSUE TITLE
Can no longer use self-contained editor with projects in a sub-folder next to the editor.

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#66344]
### Godot version

v4.0.beta.custom_build [42f6532c3]

### System information

Windows 11, Vulkan, Nvidia GTX 1050 Ti, 512.15

### Issue description

Godot Fails to start when using Self contained when the Projects folder, in which there are projects is in the same directory as the Editor.

### Steps to reproduce

Try to Open the Godot Editor with `._sc_` after https://github.com/godotengine/godot/pull/66200

**Comment by akien-mga** [comment]
This is intended, this is explicitly what the link PR prevents. It's not safe to mix editor and project data on the same folder, it can break your exports.

**Comment by mrjustaguy** [comment]
the editor isn't in the projects folder, it's in the one above. Here:
![image](https://user-images.githubusercontent.com/50302479/192103566-ddd3d832-c616-405b-9980-d19f9cbb8866.png)

the Projects are inside the Projects folder

**Comment by akien-mga** [comment]
Right, I agree this use case should still be supported. That's what Steam uses for demos.
CC @aaronfranke

**Comment by aaronfranke** [comment]
This is the code:

```cpp
if (EditorPaths::get_singleton()->is_self_contained()) {
	if (ProjectSettings::get_singleton()->get_resource_path() == OS::get_singleton()->get_executable_path().get_base_dir()) {
		ERR_PRINT("You are trying to run a self-contained editor at the same location as a project. This is not allowed, since editor files will mix with project files.");
		OS::get_singleton()->set_exit_code(EXIT_FAILURE);
		return FAILED;
	}
}
```

I don't understand why this would happen. Shouldn't `ProjectSettings::get_singleton()->get_resource_path()` include the `/Projects/Whatever` at the end? Why would this not be the case? Seems like a bug with `get_resource_path()`.

@mrjustaguy Can you add these two lines in-between the two `if` statements, then compile and run Godot, so that we can double-check that this is the problem?

```cpp
print_line(ProjectSettings::get_singleton()->get_resource_path());
print_line(OS::get_singleton()->get_executable_path().get_base_dir());
```

**Comment by mrjustaguy** [comment]
Sadly I'm unable to Compile Godot on this machine as something got messed up and it keeps failing now..

However I did run another test, I made made made a New folder on another Disk, put Godot and made it run self contained, and despite there being absolutely nothing in the folder it failed.. Only things in the folder are the exe, the sc, and the editor data that got generated when I ran the exe, so there's No way it picked up a Project.

**Comment by aaronfranke** [comment]
Ah, this method does not behave as I expected in the project manager. Here's a PR to fix it https://github.com/godotengine/godot/pull/66364

**Comment by mrjustaguy** [comment]
I'll test it out when the Github Artifacts are ready and post my results with the PR there.
