### ISSUE TITLE
Can't assign Timer.new() to a type Timer

### ISSUE THREAD

**Issue by flotos** [godotengine/godot#66342]
### Godot version

4.0 beta 1

### System information

Windows 10

### Issue description

When I try to assign Timer.new() to a var of type Timer, I get the following parsing error :

Cannot assign a value of type "Timer" to a target of type "GDScriptNativeClass".

Code snippet :

```
var characterActionTimer := Timer

# Called when the node enters the scene tree for the first time.
func _ready():
	characterActionTimer = Timer.new()
	pass # Replace with function body.
```

### Steps to reproduce

Copy the provided code in a new script

**Comment by timothyqiu** [comment]
It should be `:` instead of `:=` here.

`:=` sets the type to be the same as the type of that initializer. So `var characterActionTimer := Timer` means `characterActionTimer` should be a class (`GDScriptNativeClass`) which is different from a `Timer`.
