### ISSUE TITLE
Application runs on CPU - lavapipe is not a conformant vulkan implementation

### ISSUE THREAD

**Issue by sc3sc3** [godotengine/godot#66359]
### Godot version

Godot Engine v4.0.beta1.official.20d667284

### System information

 Ubuntu 20.04 with 2 GPUs

### Issue description

I'm on Ubuntu 20.04 with 2 GPUs, first is GTX 550, second is GTX 1060 ( via xorg )
When starting Godot beta 1:
**_Godot Engine v4.0.beta1.official.20d667284 - https://godotengine.org/
Vulkan API 1.2.131 - Using Vulkan Device #0: Unknown - llvmpipe (LLVM 12.0.0, 256 bits)
WARNING: lavapipe is not a conformant vulkan implementation, testing use only_**
So Godot seems to run on CPU, and is very slow and actually unusable.
I presume Godot is picking the first GPU ( GTX 550 )
I cannot find a way in application ( Settings ) to configure a different GPU

### Steps to reproduce

Start Godot Engine v4.0.beta1.official.20d667284 on Ubuntu 20.04 with 2 GPUs

**Comment by Calinou** [comment]
Try using `--gpu-index` command line argument with parameters 0, 1 and 2.

**Comment by sc3sc3** [comment]
using --gpu-index with different indexes don't recognize GPU devices

./Godot_v4.0-beta1_linux.x86_64 --verbose
..
Vulkan devices:
  #0: Unknown llvmpipe (LLVM 12.0.0, 256 bits) - Supported, CPU
  #1: Unknown llvmpipe (LLVM 12.0.0, 256 bits) - Supported, CPU

to answer your curiosity question:
first GPU ( 550 ) handles my screens
second GPU ( 1060 ) is for dedicated GPU jobs, for example rendering with Blender

**Comment by sc3sc3** [comment]
some other info that might be relevant:
inxi -G
Graphics:  Device-1: NVIDIA GF116 [GeForce GTX 550 Ti] driver: nvidia v: 390.154 
           Device-2: NVIDIA GP106 [GeForce GTX 1060 3GB] driver: nvidia v: 390.154 
           Display: x11 server: X.Org 1.20.13 driver: modesetting,nouveau,nvidia unloaded: fbdev,vesa 
           resolution: 1920x1080~60Hz, 2560x1440~60Hz 
           OpenGL: renderer: GeForce GTX 550 Ti/PCIe/SSE2 v: 4.6.0 NVIDIA 390.154

**Comment by LHLaurini** [comment]
Try running:

    vulkaninfo --summary

What is the output?

**Comment by sc3sc3** [comment]
my version of vulkaninfo does not support _--summary_
but this is partial output of _vulkaninfo_ itself:
**$ vulkaninfo
ERROR: [Loader Message] Code 0 : /usr/lib/i386-linux-gnu/libvulkan_intel.so: wrong ELF class: ELFCLASS32
ERROR: [Loader Message] Code 0 : /usr/lib/i386-linux-gnu/libvulkan_radeon.so: wrong ELF class: ELFCLASS32
ERROR: [Loader Message] Code 0 : /usr/lib/i386-linux-gnu/libvulkan_lvp.so: wrong ELF class: ELFCLASS32
ERROR: [Loader Message] Code 0 : /usr/lib/i386-linux-gnu/libvulkan_intel.so: wrong ELF class: ELFCLASS32
ERROR: [Loader Message] Code 0 : /usr/lib/i386-linux-gnu/libvulkan_radeon.so: wrong ELF class: ELFCLASS32
ERROR: [Loader Message] Code 0 : /usr/lib/i386-linux-gnu/libvulkan_lvp.so: wrong ELF class: ELFCLASS32
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
==========
VULKANINFO
==========

Vulkan Instance Version: 1.2.131


Instance Extensions: count = 18
====================
	VK_EXT_acquire_xlib_display            : extension revision 1
	VK_EXT_debug_report                    : extension revision 10
	VK_EXT_debug_utils                     : extension revision 1
	VK_EXT_direct_mode_display             : extension revision 1
	VK_EXT_display_surface_counter         : extension revision 1
	VK_KHR_device_group_creation           : extension revision 1
	VK_KHR_display                         : extension revision 21
	VK_KHR_external_fence_capabilities     : extension revision 1
	VK_KHR_external_memory_capabilities    : extension revision 1
	VK_KHR_external_semaphore_capabilities : extension revision 1
	VK_KHR_get_display_properties2         : extension revision 1
	VK_KHR_get_physical_device_properties2 : extension revision 2
	VK_KHR_get_surface_capabilities2       : extension revision 1
	VK_KHR_surface                         : extension revision 25
	VK_KHR_surface_protected_capabilities  : extension revision 1
	VK_KHR_wayland_surface                 : extension revision 6
	VK_KHR_xcb_surface                     : extension revision 6
	VK_KHR_xlib_surface                    : extension revision 6

Layers: count = 9
=======
VK_LAYER_LUNARG_standard_validation (LunarG Standard Validation Layer) Vulkan version 1.0.131, layer version 1:
	Layer Extensions: count = 0
	Devices: count = 2
		GPU id 	: 0 (llvmpipe (LLVM 12.0.0, 256 bits))
		Layer-Device Extensions: count = 0

		GPU id 	: 1 (llvmpipe (LLVM 12.0.0, 256 bits))
		Layer-Device Extensions: count = 0

VK_LAYER_MESA_device_select (Linux device selection layer) Vulkan version 1.2.73, layer version 1:
	Layer Extensions: count = 0
	Devices: count = 2
		GPU id 	: 0 (llvmpipe (LLVM 12.0.0, 256 bits))
		Layer-Device Extensions: count = 0

		GPU id 	: 1 (llvmpipe (LLVM 12.0.0, 256 bits))
		Layer-Device Extensions: count = 0

VK_LAYER_MESA_device_select (Linux device selection layer) Vulkan version 1.2.73, layer version 1:
	Layer Extensions: count = 0
	Devices: count = 2
		GPU id 	: 0 (llvmpipe (LLVM 12.0.0, 256 bits))
		Layer-Device Extensions: count = 0

		GPU id 	: 1 (llvmpipe (LLVM 12.0.0, 256 bits))
		Layer-Device Extensions: count = 0

VK_LAYER_MESA_overlay (Mesa Overlay layer) Vulkan version 1.1.73, layer version 1:
	Layer Extensions: count = 0
	Devices: count = 2
		GPU id 	: 0 (llvmpipe (LLVM 12.0.0, 256 bits))
		Layer-Device Extensions: count = 0

		GPU id 	: 1 (llvmpipe (LLVM 12.0.0, 256 bits))
		Layer-Device Extensions: count = 0

VK_LAYER_MESA_overlay (Mesa Overlay layer) Vulkan version 1.1.73, layer version 1:
	Layer Extensions: count = 0
	Devices: count = 2
		GPU id 	: 0 (llvmpipe (LLVM 12.0.0, 256 bits))
		Layer-Device Extensions: count = 0

		GPU id 	: 1 (llvmpipe (LLVM 12.0.0, 256 bits))
		Layer-Device Extensions: count = 0

VK_LAYER_VALVE_steam_fossilize_32 (Steam Pipeline Caching Layer) Vulkan version 1.2.136, layer version 1:
	Layer Extensions: count = 0
	Devices: count = 2
		GPU id 	: 0 (llvmpipe (LLVM 12.0.0, 256 bits))
		Layer-Device Extensions: count = 0

		GPU id 	: 1 (llvmpipe (LLVM 12.0.0, 256 bits))
		Layer-Device Extensions: count = 0

VK_LAYER_VALVE_steam_fossilize_64 (Steam Pipeline Caching Layer) Vulkan version 1.2.136, layer version 1:
	Layer Extensions: count = 0
	Devices: count = 2
		GPU id 	: 0 (llvmpipe (LLVM 12.0.0, 256 bits))
		Layer-Device Extensions: count = 0

		GPU id 	: 1 (llvmpipe (LLVM 12.0.0, 256 bits))
		Layer-Device Extensions: count = 0

VK_LAYER_VALVE_steam_overlay_32 (Steam Overlay Layer) Vulkan version 1.2.136, layer version 1:
	Layer Extensions: count = 0
	Devices: count = 2
		GPU id 	: 0 (llvmpipe (LLVM 12.0.0, 256 bits))
		Layer-Device Extensions: count = 0

		GPU id 	: 1 (llvmpipe (LLVM 12.0.0, 256 bits))
		Layer-Device Extensions: count = 0

VK_LAYER_VALVE_steam_overlay_64 (Steam Overlay Layer) Vulkan version 1.2.136, layer version 1:
	Layer Extensions: count = 0
	Devices: count = 2
		GPU id 	: 0 (llvmpipe (LLVM 12.0.0, 256 bits))
		Layer-Device Extensions: count = 0

		GPU id 	: 1 (llvmpipe (LLVM 12.0.0, 256 bits))
		Layer-Device Extensions: count = 0

Presentable Surfaces:
=====================
GPU id : 0 (llvmpipe (LLVM 12.0.0, 256 bits)):
	Surface types: count = 2
		VK_KHR_xcb_surface
		VK_KHR_xlib_surface
	Formats: count = 2
		SurfaceFormat[0]:
			format = FORMAT_B8G8R8A8_SRGB
			colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
		SurfaceFormat[1]:
			format = FORMAT_B8G8R8A8_UNORM
			colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
	Present Modes: count = 4
		PRESENT_MODE_IMMEDIATE_KHR
		PRESENT_MODE_MAILBOX_KHR
		PRESENT_MODE_FIFO_KHR
		PRESENT_MODE_FIFO_RELAXED_KHR
	VkSurfaceCapabilitiesKHR:
	-------------------------
		minImageCount       = 3
		maxImageCount       = 0
		currentExtent:
			width  = 256
			height = 256
		minImageExtent:
			width  = 256
			height = 256
		maxImageExtent:
			width  = 256
			height = 256
		maxImageArrayLayers = 1
		supportedTransforms:
			SURFACE_TRANSFORM_IDENTITY_BIT_KHR
		currentTransform:
			SURFACE_TRANSFORM_IDENTITY_BIT_KHR
		supportedCompositeAlpha:
			COMPOSITE_ALPHA_OPAQUE_BIT_KHR
			COMPOSITE_ALPHA_INHERIT_BIT_KHR
		supportedUsageFlags:
			IMAGE_USAGE_TRANSFER_SRC_BIT
			IMAGE_USAGE_TRANSFER_DST_BIT
			IMAGE_USAGE_SAMPLED_BIT
			IMAGE_USAGE_STORAGE_BIT
			IMAGE_USAGE_COLOR_ATTACHMENT_BIT
	VkSurfaceCapabilities2EXT:
	--------------------------
		supportedSurfaceCounters:
			None
	VkSurfaceProtectedCapabilitiesKHR:
	----------------------------------
		supportsProtected = false


GPU id : 1 (llvmpipe (LLVM 12.0.0, 256 bits)):
	Surface types: count = 2
		VK_KHR_xcb_surface
		VK_KHR_xlib_surface
	Formats: count = 2
		SurfaceFormat[0]:
			format = FORMAT_B8G8R8A8_SRGB
			colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
		SurfaceFormat[1]:
			format = FORMAT_B8G8R8A8_UNORM
			colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
	Present Modes: count = 4
		PRESENT_MODE_IMMEDIATE_KHR
		PRESENT_MODE_MAILBOX_KHR
		PRESENT_MODE_FIFO_KHR
		PRESENT_MODE_FIFO_RELAXED_KHR
	VkSurfaceCapabilitiesKHR:
	-------------------------
		minImageCount       = 3
		maxImageCount       = 0
		currentExtent:
			width  = 256
			height = 256
		minImageExtent:
			width  = 256
			height = 256
		maxImageExtent:
			width  = 256
			height = 256
		maxImageArrayLayers = 1
		supportedTransforms:
			SURFACE_TRANSFORM_IDENTITY_BIT_KHR
		currentTransform:
			SURFACE_TRANSFORM_IDENTITY_BIT_KHR
		supportedCompositeAlpha:
			COMPOSITE_ALPHA_OPAQUE_BIT_KHR
			COMPOSITE_ALPHA_INHERIT_BIT_KHR
		supportedUsageFlags:
			IMAGE_USAGE_TRANSFER_SRC_BIT
			IMAGE_USAGE_TRANSFER_DST_BIT
			IMAGE_USAGE_SAMPLED_BIT
			IMAGE_USAGE_STORAGE_BIT
			IMAGE_USAGE_COLOR_ATTACHMENT_BIT
	VkSurfaceCapabilities2EXT:
	--------------------------
		supportedSurfaceCounters:
			None
	VkSurfaceProtectedCapabilitiesKHR:
	----------------------------------
		supportsProtected = false**

**Comment by sc3sc3** [comment]
sorry for long comment and also for the font mess

**Comment by LHLaurini** [comment]
It'd be helpful if you wrapped it between three backticks. Like this:

    ```
    The output goes here
    ```

so that it's formatted like this:
```
The output goes here
```

**Comment by LHLaurini** [comment]
Ok, so it seems like you're getting
```
Presentable Surfaces:
=====================
GPU id : 0 (llvmpipe (LLVM 12.0.0, 256 bits)):
	[...]

GPU id : 1 (llvmpipe (LLVM 12.0.0, 256 bits)):
	[...]
```
So you don't have the correct Vulkan drivers installed. Then it's not a Godot issue.

**Comment by sc3sc3** [comment]
ok, thank you for your time ( and sorry for wasting it )
I can't update this system, it's too old
I'll come back to Godot when I've got a new computer

**Comment by LHLaurini** [comment]
I don't think you need to update your system, just figure out what you have to install to get Vulkan with Nvidia GPUs working. I don't have any experience with Nvidia on Linux so I can't really help.
