### ISSUE TITLE
`&&` has wrong colors when `code_font_custom_opentype_features` are used

### ISSUE THREAD

**Issue by Lielay9** [godotengine/godot#66350]
### Godot version

v4.0.beta1.official [20d667284]

### System information

Windows 10, Vulkan, Nvidia 1050TI

### Issue description

Without features (Font: [Firacode](https://github.com/tonsky/FiraCode)):

![image](https://user-images.githubusercontent.com/40064911/192097778-4642a5f5-5a44-4ed8-846e-7472d9ac9ba5.png)
With features:

![image](https://user-images.githubusercontent.com/40064911/192097463-e8b73859-f780-41da-a3fa-3e256b24ec1c.png)

When enabling the alternative symbol for `&` (ss03), the logical and, `&&`, uses incorrect colors (StringName + Bitwise AND ?).

Not probably going to ruin anyone's project if nothing can be done about it (most use `and` anyways). 

### Steps to reproduce

1. Get a font that has a character variant for `&` (example: [Firacode](https://github.com/tonsky/FiraCode))
2. Set the font as `interface/editor/code_font` 
3. Enable and use the character variant (Firacode: `ss03`):

![image](https://user-images.githubusercontent.com/40064911/192098313-f16aa3d3-e492-42ab-8c13-484988a98c5c.png)

### Minimal reproduction project

Too lazy right now. For future reference: how would I share changes to the editor settings?

**Comment by MewPurPur** [comment]
The fix already exists: https://github.com/godotengine/godot/pull/65074
