### ISSUE TITLE
"Condition ' !texture ' is true." error in RasterizerGLES2 when using sub viewports

### ISSUE THREAD

**Issue by Wolf17777** [godotengine/godot#6635]
**Operating system or device - Godot version:**
Windows 7 64bit - Godot v2.1-stable

**Issue description** (what happened, and what was expected):
Adding a viewport as a child of control results in two errors:

> Time: 0:00:00:0538
> C Error: Condition ' !elem ' is true. returned: 0
> C Source: core\rid.h:146
> C Function: RID_Owner<struct RasterizerGLES2::Texture,0>::get

and

> Time: 0:00:00:0545
> C Error: Condition ' !texture ' is true.
> C Source: drivers\gles2\rasterizer_gles2.cpp:1280
> C Function: RasterizerGLES2::texture_set_flags 

Whatever is causing those errors, the subviewport seems to be working as intended.

**Steps to reproduce:**
1. Create new project and scene
2. Add a Control node
3. Add a Viewport node as a child of that Control node
4. Save and play the scene

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Chaosus** [comment]
I checked and its not detectable in 2.1.5 and 3.1, I used Win10 but I think its not a Win7 specific problem, eg 2.1 is pretty old and lots of changes passed since that time which may fixed this problem.. _Closed by bugsquad._
