### ISSUE TITLE
Executing `RenderingServer.create_local_rendering_device` crashes Godot

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#66372]
### Godot version

4.0.alpha.custom_build. 4b164b8e4

### System information

Ubuntu 22.04 - Nvidia GTX 970, Gnome shell 42 X11

### Issue description

When executing
```
	RenderingServer.create_local_rendering_device()
```

Godot crashes without backtrace(probably crash in graphic driver)
```
Thread 67 "[vkrt] Analysis" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffe64bea640 (LWP 94122)]
0x00007fffe02b8c0c in ?? ()
(gdb) backtrace
#0  0x00007fffe02b8c0c in ?? ()
#1  0x00007ffe64bea640 in ?? ()
#2  0x00007ffe64be9b30 in ?? ()
#3  0x00000000632f6342 in ?? ()
#4  0x000000002ee32c80 in ?? ()
#5  0x00000000632f6342 in ?? ()
#6  0x00000000000a7a30 in ?? ()
#7  0x00007fffffff89b0 in ?? ()
#8  0x000000001860f370 in ?? ()
#9  0x00007fffe02bae60 in ?? ()
#10 0x000000001860f4c0 in ?? ()
#11 0x0000000000000000 in ?? ()

```

This example was found by Godot fuzzer - [Qarminer](https://github.com/qarmin/Qarminer), so it is quite unlikelly that this code could be used in real project, but still this should be handled gracefully.

### Steps to reproduce

Above

**Comment by timothyqiu** [comment]
https://github.com/godotengine/godot/blob/632dbab226356eb4395ee2c0aa202c5fcd912e7d/servers/rendering_server.cpp#L1477-L1479

`get_singleton()` here returns null.

**Comment by qarmin** [comment]
Not sure if this is a problem here.
Usually asan/ubsan show clear error if null pointer was used, but this time I got only simple `segmentation fault`  message without debug symbols in backtrace which is quite common if external library crashes.

**Comment by dzil123** [comment]
When running with `--headless` or with the opengl3 renderer, `get_singleton()` indeed returns null and is the source of the crash.

I cannot reproduce the issue with the vulkan renderer. That might be a driver issue that can't be fixed in Godot.

**Comment by akien-mga** [comment]
That's expected, the OpenGL3 driver doesn't implement RenderingDevicr (which is the abstraction for modern APIs like Vulkan/D3D12). So this method should just null when using OpenGL3 (which can be done by checking ifthe RD singleton exists I guess). Should be documented too.
