### ISSUE TITLE
Ctrl+Click on nodes for their documentation doesn't work if using other casing styles

### ISSUE THREAD

**Issue by FHEK789** [godotengine/godot#66390]
### Godot version

4.0.beta1

### System information

Kubuntu 22.04

### Issue description

When using the default casing for nodes names (e.g Node2D) and ctrl+clicking on them opens up the documentation for that node, that doesn't work when using other casing styles like snake_case.
It would be great for the editor to make the ctrl+click thing possible on all the supported casing styles.

### Steps to reproduce

In the minimal reproduction project, there's a scene with Node2D and a Sprite2D as a child of it, the Node2D node has an attached script with this code in it `@onready var sprite := $sprite_2d`, if you ctrl+click on the "$sprite_2d" part it won't open up the documentation of the Sprite2D node.

### Minimal reproduction project

[casing.zip](https://github.com/godotengine/godot/files/9640112/casing.zip)

**Comment by Calinou** [comment]
This is expected, as the name is only clickable because it matches the class name *exactly*. There is no intelligent logic that tries to guess the node type based on the currently open scene.

**Comment by FHEK789** [comment]
That's alright, I just think it might be a bit confusing. e.g a new user could change that option to snake case, then read about the ctrl+click feature on reddit or something but that won't work because it only works for the default option.
I think it would be great to at least show a warning when changing the default casing explaining that the ctrl+click feature won't work anymore.
