### ISSUE TITLE
Cannot start Godot editor in self-contained mode on Windows since #66200 and #66364

### ISSUE THREAD

**Issue by Kemeros** [godotengine/godot#66408]
### Godot version

v4.0.beta.custom_build.1ac13e562

### System information

Windows 11 22h2

### Issue description

#66200 ~~and #66364~~ broke the CMD workaround to start Godot on Windows 10/11 since the console was disabled a while ago.

Currently, to launch Godot, you need this script:
````
@echo off
godot.windows.opt.tools.x86_64.exe
pause > nul
````

Without it, Godot just closes itself without opening the project manager.

Last working version:
v4.0.beta.custom_build [b3f7796c4]

Error:

ERROR: You are trying to run a self-contained editor at the same location as a project. This is not allowed, since editor files will mix with project files.
   at: Main::setup2 (main\main.cpp:1943)
ERROR: BUG: Unreferenced static string to 0: interface_added
   at: StringName::unref (core\string\string_name.cpp:131)

Screenshot of the error:
![image](https://user-images.githubusercontent.com/15658976/192153299-d55a8cc7-2e84-486f-be30-b3253fbca5da.png)

I have not tested on Windows 10 but i believe it will act the same. Someone else can always confirm.

### Steps to reproduce

Use any Godot version more recent than v4.0.beta.custom_build [b3f7796c4]
Open Godot's executable
Nothing happens
Use a CMD script to launch it:
````
@echo off
godot.windows.opt.tools.x86_64.exe
pause > nul
````
Error

Edit:

You can use my PowerShell script to quickly test the same way i do:

Simple put the code in a .ps1 file next to your Godot.exe or change the first variable to point to the folder where your Godot editor is.

```
$editor_path = $PSScriptRoot

$editor_settings = @"
[gd_resource type="EditorSettings" format=3]

[resource]
filesystem/directories/default_project_path = "$(($editor_path).Replace("\","/"))/Projects"
"@

$start_cmd = @"
@echo off
godot.windows.opt.tools.x86_64.exe
pause > nul
"@

if (Test-Path "$editor_path\Godot*exe" )
{
    New-Item -ItemType "File" -Path "$editor_path\._sc_" -Force
    Get-ChildItem -Directory -Path "$editor_path" -Exclude "Projects" -Force | Remove-Item -Recurse -Force -Confirm:$false
    New-Item -ItemType "Directory" -Path "$editor_path\Projects" -Force
    New-Item -ItemType "Directory" -Path "$editor_path\editor_data" -Force
    New-Item -ItemType "File" -Path "$editor_path\editor_data\editor_settings-4.tres" -Force -Value $editor_settings
    New-Item -ItemType "File" -Path "$editor_path\Start_Godot.cmd" -Force -Value $start_cmd
}
else
{
    Add-Type -AssemblyName "PresentationFramework"
    [System.Windows.MessageBox]::Show("Godot executable not found", "Reset-GodotFolders.ps1", "Ok", "Error")
} 
```

### Minimal reproduction project

No project needed

**Comment by aaronfranke** [comment]
Does the folder have a file called `_sc_` or `._sc_` in it?

**Comment by Kemeros** [comment]
> Does the folder have a file called `_sc_` or `._sc_` in it?

It has `._sc_` yes

**Comment by Kemeros** [comment]
Well now i am confused. I opened the latest artefact from today to find that the problem was gone even though i saw nothing merged to fix it.

I followed the trail a bit and realized that most PRs from #66364 and onward works fine. Sunday, i switched between, #66200, 66364 and PRs made after and it was giving me the error in the OP.

So either i did my testing wrong somehow or i'm going crazy...

Alright... Let's see if i can figure this out...

I used v4.0.beta.custom_build.1ac13e562 to declare the bug... which is #63224 ... Merged on the 25th of September at 5:29am EST... Test it now... still doesn't work in that PR artefact today.

PR 66364 was merged on the 24th of September at 4:58PM EST ... 12 hours before PR 63224... Was not working Sunday... It's working today... Which ... should not ... work.

Maybe PR 63224 was merged but needed a rebase? Which would explain the artefact without the fix present.

I don't get how PR 66364 would not work Sunday though. I must have messed up that part of the test.

I don't know if it's actually fixed or not but it works on the latest PR artefacts in any case.

**Comment by aaronfranke** [comment]
Closing as per the above. It's likely that @Kemeros was just running an old executable. Since you're on Windows, my guess is you compiled while Godot was open, and then scons wasn't able to update the executable at the end of compiling since it was in use.
