### ISSUE TITLE
can_instantiate: Cannot instance script because the associated class could not be found. Script: 'res://Player.cs'.

### ISSUE THREAD

**Issue by LenartSvetek** [godotengine/godot#66419]
### Godot version

4.0.0 beta 1

### System information

Windows 10, AMD RX 5700 XT, driver 22.8.2

### Issue description

Debugger gives me this error code:
E 0:00:00:0808   can_instantiate: Cannot instance script because the associated class could not be found. Script: 'res://Player.cs'.
  <C++ Error>    Method/function failed. Returning: false
  <C++ Source>   modules/mono/csharp_script.cpp:2288 @ can_instantiate()

### Steps to reproduce

Create new project 
Add script to CharacterBody2D and it doesn't matter if its templated or not and run and it shows me this error

### Minimal reproduction project

[UnknownOrigin.zip](https://github.com/godotengine/godot/files/9641807/UnknownOrigin.zip)

**Comment by LenartSvetek** [comment]
I just deleted everything and made new project in different folder and it seems to work fine

**Comment by wayrboy** [comment]
I have the same problem

**Comment by Haatchoum** [comment]
I have the same problem on Beta 8. (my first mono version test).

I tried resetting project, creating new project. Nothing works...

**Comment by ctafield** [comment]
Also the same issue with Beta 8. Have also tried ensuring the class matches the same case as the filename, but no joy.

**Comment by raulsntos** [comment]
Make sure the class name is the same as the filename (it's case-sensitive). So if the class is `class Player {}` the filename should be `Player.cs`.

**Comment by arkuhn** [comment]
<img width="946" alt="image" src="https://user-images.githubusercontent.com/9009111/210678827-9e75f68c-298a-4842-9375-0d6fbc28e2f2.png">

Sorry if I'm missing something obvious. The class name, filename, and scene name are all seemingly exactly the same here and yet I still get the following error:
```
E 0:00:00:0867   can_instantiate: Cannot instance script because the associated class could not be found. Script: 'res://scenes/player/MainPlayer.cs'. Make sure the script exists and contains a class definition with a name that matches the filename of the script exactly (it's case-sensitive).
  <C++ Error>    Method/function failed. Returning: false
  <C++ Source>   modules/mono/csharp_script.cpp:2295 @ can_instantiate()
```

Nothing useful in the console output that I see:
```
Godot Engine v4.0.beta9.mono.official.e780dc332 - https://godotengine.org
OpenGL Renderer: NVIDIA GeForce RTX 2060 SUPER/PCIe/SSE2

Editing project: C:/Users/ak101/projects/New C# Game
Godot Engine v4.0.beta9.mono.official.e780dc332 - https://godotengine.org
Vulkan API 1.2.186 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 2060 SUPER

WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings.     at: _editor_init (modules/gltf/register_types.cpp:61)
Copying Godot Offline Packages...
Unloading assembly load context...
Assembly load context unloaded successfully.
Copying Godot Offline Packages...
Running: C:/Users/ak101/Downloads/Godot_v4.0-beta9_mono_win64/Godot_v4.0-beta9_mono_win64/Godot_v4.0-beta9_mono_win64.enGodot Engine v4.0.beta9.mono.official.e780dc332 - https://godotengine.org
Vulkan API 1.2.186 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 2060 SUPER

ERROR: Cannot instance script because the associated class could not be found. Script: 'res://scenes/player/MainPlayer..   at: (modules/mono/csharp_script.cpp:2295)
```

**Comment by guilleatm** [comment]
I have been testing things, I thing I have found a way to reproduce the bug, at least mine.

1. Create a class and add the script to a node.

```C#
public partial class Bug : Node2D
{

}
```

2. Try making the class generic

```C#
public partial class Bug<T> : Node2D where T : class
{

}
```

3. Run the scene

> Of course this doesn't work and throws the error.

4. Change the class so it is like before

```C#
public partial class Bug : Node2D
{

}
```

5. If you try to run the scene, it will keep throwing the error


@raulsntos

**Comment by raulsntos** [comment]
@guilleatm I'm unable to reproduce the bug with those steps, please open a new issue and upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by nonunknown** [comment]
@raulsntos did you tried to reproduce on windows? seems this error only happens on windows. I'm using the betas with mono and linux, had no problem with till now, but a friend of mine, is having this problem a lot!

**Comment by guilleatm** [comment]
@raulsntos @nonunknown I tried the steps but now the error doesn't show, so I am missing something I guess.

I run a linux.
