### ISSUE TITLE
GDScript: calling static method on instance does not warn or error

### ISSUE THREAD

**Issue by RedMser** [godotengine/godot#66411]
### Godot version

4.0.dev (4ba934bf3d)

### System information

Windows 10

### Issue description

Calling a static method on an instance of the class does not cause a warning or error in the code.

This can be a potential pitfall when using the API wrongly, such as the `ImageTexture.create_from_image` API (see below).

The compiler should **warn or error** in such a situation (C# for example errors here, and suggests using the type name instead). Make the severity level configurable, like with other warnings in GDScript.

### Steps to reproduce

```gdscript
var tex = ImageTexture.new()
tex.create_from_image(img)
```
This causes nothing to happen, because `create_from_image` is a static method. You're supposed to do `var tex = ImageTexture.create_from_image(img)` instead.

**Comment by Ithamar** [comment]
This is indeed particularly hurtful, since `create_from_image` used to be non-static, but since 4.0, is static. Meaning old code will show no errors, but the `ImageTexture` that `create_from_image` was called on will be unset, and therefore will cause runtime issues later on.

**Comment by dalexeev** [comment]
A warning has been added (#67365), so I think this issue can be considered resolved.

![](https://github.com/godotengine/godot/assets/47700418/abf2af61-2490-44ac-9c76-5e2afc1f1943)

Note that there is an issue (#74397) with the type suggested in the error message. Also there is opinion (https://github.com/godotengine/godot/issues/77098#issuecomment-1559559143) that perhaps this warning is intrusive, and the benefit is only in cases like the one described here (when a static method returns an instance of the same class).
