### ISSUE TITLE
Godot 4 on Android potential memory leak

### ISSUE THREAD

**Issue by PriNova** [godotengine/godot#66415]
### Godot version

4.0-beta1 on tuxfamily

### System information

Galaxy Tab S4, Android 10 (API 29), Adreno 540, Vulkan 1.1.87, RAM 4GB

### Issue description

After creating a new Project in the Project-Manager, pressing `Edit' to go into editor.
Selecting Vulkan for Mobile.
My RAM monitor increasing fast and inbetween 5-8 seconds in the 3d view the App crashes.
Propably a memory leak.

### Steps to reproduce

See description above.
An empty starter-project works for reproducing.

**Comment by m4gr3d** [comment]
I have not be able to reproduce the issue in the latest version of the Godot Android Editor 4. 
@PriNova please reopen if the issue still occurs for you.
