### ISSUE TITLE
Godot 4.0 always maximizes window on save

### ISSUE THREAD

**Issue by darkstego** [godotengine/godot#66413]
### Godot version

4.0.beta1

### System information

Linux Manjaro Kernel 5.19.9 KDE Plasma 5.25.5

### Issue description

Whenever I save a scene in Godot 4.0 the window maximizes and takes up the entire screen. This behavior did not occur in Godot 3.5, where saving a scene did not alter the current window size. 

### Steps to reproduce

1. Create a new project in Godot 4
2. Change project window size to something other than maximized
3. Add a Node
4. Save the scene

**Comment by amoriqbal** [comment]
I can confirm this on linux mint.

**Comment by raulsntos** [comment]
This is a regression from https://github.com/godotengine/godot/pull/65107

**Comment by akien-mga** [comment]
CC @MatthewZelriche
