### ISSUE TITLE
Undo/Redo doesn't register when start or end of undo stack reached (doesn't enable or disable keyboard shortcuts)

### ISSUE THREAD

**Issue by Clonkex** [godotengine/godot#66424]
### Godot version

v4.0.beta1.mono.official [4ba934bf3]

### System information

Windows 10, Vulkan Clustered

### Issue description

This is hard to explain so bear with me. Normally, if you undo at least once and then don't make any more changes, you'll be able to redo. Or if you redo a change you previously undid, you'll be able to undo again. This isn't working for me. I have to open the Scene menu for it to work properly. At first I thought the keyboard shortcut was broken, but eventually realised opening the Scene dropdown is what fixes it (temporarily).

Essentially what I think is happening is that Godot knows when it can and can't undo or redo (in other words, when it's currently at the start or end of the undo stack), and each time it reaches a new state (at start of stack, somewhere in the middle, or at end of stack) it sets whether the keyboard shortcuts can have an effect. In my case, it doesn't seem to be unlocking the keyboard shortcuts appropriately. So if I undo all the way to the start of the stack I can't redo again, or if I redo all the way to the end of the stack I can't undo.

The only way to make it update the state is to open the Scene dropdown at the top of the window. That dropdown contains the menu items for Undo and Redo. Each time I open the Scene dropdown, the state of the keyboard shortcuts is updated to be correct. So if I undo all the way to the start of the stack, I won't be able to redo until I open the Scene dropdown. If I undo to somewhere in the middle of the undo stack and open the Scene dropdown, then I can undo and redo to my heart's content. However if I undo or redo to the start or end of the undo stack, I'll get "nothing to undo" and "nothing to redo" in the console.

### Steps to reproduce

- Create a new project and place a node in the scene
- Move it a few times
- Attempt to undo with Ctrl+Z. You shouldn't be unable to undo because the Scene dropdown hasn't updated to register that there's undoable items on the stack
- Open the Scene dropdown
- Attempt to undo with Ctrl+Z again. You should now be able to undo, but not redo, because the Scene dropdown hasn't updated to register that you've moved backwards through the undo stack

**Comment by Clonkex** [comment]
I just updated to v3.5.1.stable.mono.official [6fed1ffa3] on my laptop and discovered the issue is present there as well. I'm not sure what version I'm on at home; v3.5.0.stable.mono.official I believe, but I'm not sure of the exact commit.

It's incredibly frustrating and totally breaks normal workflow, so I hope a fix can be found quickly.

**Comment by EricEzaM** [comment]
Indeed you are correct, it only works after the file menu has been opened.

The undo/redo shortcuts are currently activated by the shortcut input being routed through the MenuBar, and then each popup menu. In the scene popup menu, the shortcut gets **rejected** because `is_item_disabled()` returns true. It is disabled because the enabled/disabled status is only updated when the file menu is opened, here:

https://github.com/godotengine/godot/blob/fcba87e696d58912838d8a4a6987b10efa28e78f/editor/editor_node.cpp#L3247-L3258

I'll take more of a look into it.
