### ISSUE TITLE
CSGBox sizing is reset to (1,1,1) when updating project from 3.5 to 4.0.beta1

### ISSUE THREAD

**Issue by GK-GreyGhost** [godotengine/godot#66420]
### Godot version

4.0.beta1

### System information

Windows 10, Vulkan, Nvidia 2070 Super

### Issue description

When import and updating a project from 3.5 to 4.0, all CSGBoxes are resized to (1,1,1)
![image](https://user-images.githubusercontent.com/1384496/192168988-60d23b3e-58ab-4ae8-aa4a-735eb9324074.png)
![image](https://user-images.githubusercontent.com/1384496/192168992-111d6595-6721-431e-a1b3-4be6f9dc192e.png)

### Steps to reproduce

1. Create a new project in Godot 3
2. add CSGBox, resize box to something other than (1,1,1)
3. Import and update project to 4.0.beta1
4. all CSGBox sizes will be reset to (1,1,1)

### Minimal reproduction project

[csg demo.zip](https://github.com/godotengine/godot/files/9641924/csg.demo.zip)

**Comment by GK-GreyGhost** [comment]
I created a new project with multiple CSG nodes, when most imported correctly, I realized that Godot 3 uses width/height/depth floats and Godot 4 uses a single Vector3

**Comment by Calinou** [comment]
This requires dedicated porting code to handle the old property names.

**Comment by GK-GreyGhost** [comment]
Thank you for the guidance! I'll start working on it, I'm excited for my first contribution :D

**Comment by Calinou** [comment]
> Thank you for the guidance! I'll start working on it, I'm excited for my first contribution :D

See an example here:

https://github.com/godotengine/godot/blob/84f2c68c84bde10026454292578e5fdcc9ab69a3/scene/resources/environment.cpp#L1134-L1151

**Comment by GK-GreyGhost** [comment]
Demo project is working, testing on my game and will then submit a pull request 👍😁

**Comment by GK-GreyGhost** [comment]
submitted https://github.com/godotengine/godot/pull/66476
