### ISSUE TITLE
The icons of run buttons are missing by default

### ISSUE THREAD

**Issue by Rindbee** [godotengine/godot#66438]
### Godot version

3472bdd6b

### System information

Linux mint 21, NVIDIA GeForce GTX 1050 Ti, Vulkan API 1.2.0

### Issue description

These buttons do not display properly after the project is first loaded unless the project is run once.

![0](https://user-images.githubusercontent.com/30386067/192270074-e2d889f4-ad43-4127-8b69-3226c0d3283d.gif)

It seems that just the icons are missing, the buttons are not being hidden. Running with the shortcut key prints the following error message.

```
ERROR: Used ED_GET_SHORTCUT with invalid shortcut: editor/stop.
   at: ED_GET_SHORTCUT (editor/editor_settings.cpp:1434)
```

### Steps to reproduce

1. Reload Current Project
2. Play with `F5`/`F6` 

See the difference in play buttons

**Comment by akien-mga** [comment]
Possible regression from #64756 @Calinou?
