### ISSUE TITLE
Getting stack from GDScript returns nothing when editor isn't present

### ISSUE THREAD

**Issue by albinaask** [godotengine/godot#66437]
### Godot version

3.5 stable

### System information

Windows 10

### Issue description

The built-in method get_stack() returns an empty array and print_stack() prints nothing when projects are exported. Even tough the project was run from the terminal in debug mode with verbose flag. 

### Steps to reproduce

1. Open a project
2. Open a script
3. Enter following code snippet: ```print(get_stack())```
4. Run from editor and observe a printout like "[Frame 0 - res://Node.tscn::1:12 in function '_ready']"
5. Export the project
6. Run from a console and observe output "[]"

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Documentation says: https://github.com/godotengine/godot/blob/92bcd3c01d5188480793c03b2b50e97363ceb624/modules/gdscript/doc_classes/@GDScript.xml#L178

> Only works with debugger turned on.

This means you need to have the running instance connect to a debugging server, not just be a debug build.
