### ISSUE TITLE
OpenGL: Environment adjustments not implemented yet

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#66457]
*Related to https://github.com/godotengine/godot/issues/66455.*

### Godot version

4.0.beta (53d2a9acd)

### System information

Fedora 36, GeForce GTX 1080 (NVIDIA 515.65.01)

### Issue description

Brightness, contrast, saturation sliders and the color correction texture have no effect on the displayed scene.

Both glow and adjustments are enabled on the example below.

### OpenGL

![2022-09-26_19 51 05](https://user-images.githubusercontent.com/180032/192346251-2647d0d3-f1cb-49a5-833a-b19fa148a9e8.png)

### Vulkan

![2022-09-26_19 51 30](https://user-images.githubusercontent.com/180032/192346264-bb384d82-db0c-4344-b508-d1bb202e74a4.png)

### Steps to reproduce

- Switch to the OpenGL driver in the Project Settings.
  - Make sure to start the editor with single-window mode enabled afterwards. This can be done by enabling **Single Window Mode** in the Editor Settings before changing the driver, or by opening the project in the editor directly with the `--single-window` [command line argument](https://docs.godotengine.org/en/latest/tutorials/editor/command_line_tutorial.html).
- Add a WorldEnvironment node, a Camera3D node and a MeshInstance3D in front of the camera.
- Enable glow. Change brightness/contrast/saturation to make a visible difference in the scene.

### Minimal reproduction project

[test_opengl_glow_adjustments_editor.zip](https://github.com/godotengine/godot/files/9648499/test_opengl_glow_adjustments_editor.zip)

**Comment by naturally-intelligent** [comment]
I'm also looking forward to this one being solved
