### ISSUE TITLE
OpenGL: Environment glow not implemented yet

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#66455]
*Related to https://github.com/godotengine/godot/issues/66457.*

### Godot version

4.0.beta (53d2a9acd)

### System information

Fedora 36, GeForce GTX 1080 (NVIDIA 515.65.01)

### Issue description

Glow has no effect on the displayed scene when enabled in OpenGL, regardless of the value of **Bloom** or **HDR Threshold**.

Both glow and adjustments are enabled on the example below.

### OpenGL

![2022-09-26_19 51 05](https://user-images.githubusercontent.com/180032/192346251-2647d0d3-f1cb-49a5-833a-b19fa148a9e8.png)

### Vulkan

![2022-09-26_19 51 30](https://user-images.githubusercontent.com/180032/192346264-bb384d82-db0c-4344-b508-d1bb202e74a4.png)

### Steps to reproduce

- Switch to the OpenGL driver in the Project Settings.
  - Make sure to start the editor with single-window mode enabled afterwards. This can be done by enabling **Single Window Mode** in the Editor Settings before changing the driver, or by opening the project in the editor directly with the `--single-window` [command line argument](https://docs.godotengine.org/en/latest/tutorials/editor/command_line_tutorial.html).
- Add a WorldEnvironment node, a Camera3D node and a MeshInstance3D in front of the camera.
- Enable glow and adjustments. Change brightness/contrast/saturation to make a visible difference in the scene.

### Minimal reproduction project

[test_opengl_glow_adjustments_editor.zip](https://github.com/godotengine/godot/files/9648499/test_opengl_glow_adjustments_editor.zip)

**Comment by naturally-intelligent** [comment]
Any word on the status of this issue?

It's the one missing piece for my 2D project. My machine just isn't fast enough to use Forward+ mode, it's painful.

(And even in that mode glow doesn't seem to have an effect). Was thinking of digging into this to see if I could help

**Comment by naturally-intelligent** [comment]
Seems like a shocking decision as I don't see how any developer would want to use a 2D game engine that can't do Glow. And Forward+ is far too slow for a 2D game, even without glow. I know this is a low-quality comment, but it really worries me that this isn't a priority

There must be a screen shader alternative? If so we should be noting that solution or link to it here

**Comment by akien-mga** [comment]
You can use 3.x if 4.0 isn't suitable for your needs.

> Seems like a shocking decision as I don't see how any developer would want to use a 2D game engine that can't do Glow. 

That's completely wrong, most 2D games don't need glow. Only very specific graphics style do. And those can use the Forward+ renderer, stay on 3.x, or wait for the 4.x release that will implement glow for the low end renderer.

Complaining here won't make it happen faster.

**Comment by naturally-intelligent** [comment]
When running 4.0-stable this message appears in console, and as a popup in editor (in rc6 too):

`WARNING: Glow is not supported when using the GL Compatibility backend yet. Support will be added in a future release.`

It is also mentioned in the GQQuest Godot 4 reveal video: https://youtu.be/chXAjMQrcZk?t=130

**Comment by naturally-intelligent** [comment]
Poking around at 3.5 branch to find the code to bring over:

https://github.com/godotengine/godot/blob/3.5/drivers/gles3/rasterizer_scene_gles3.cpp

EffectBlurShaderGLES3 effect_blur_shader;

https://github.com/godotengine/godot/blob/3.5/drivers/gles3/shaders/effect_blur.glsl

**Comment by NeonBurst** [comment]
Is there any way to activate glow on only specific objects in 2d in godot 4 though.

**Comment by clayjohn** [comment]
@naturally-intelligent Note, that the reddit discussion thread is about using the existing glow in 2D, not about supporting 3D glow in the OpenGL backend. 

This PR is planned to be implemented by the end of June. I.e. in time for 4.1 as the rendering priorities article says.

Also, to be fair, it would be done a lot sooner if someone is willing to work on it. But if no one volunteers, then I will do it as soon as I can, which could mean it will be done in a couple of months

**Comment by naturally-intelligent** [comment]
@clayjohn I thought this feature would cover both 3D and 2D glow in OpenGL? 

I'm very interested in 2D glow for sure! Also made a proposal here:
https://github.com/godotengine/godot-proposals/issues/6725

As for helping I identified primary 3.X glow code in an above comment, but I don't know what the equivalent code pathway is to get this into 4.0. Also it seems there are other features required first, as mentioned above, and particular specifications in how devs want the glow to be achieved that I don't quite grasp.

**Comment by naturally-intelligent** [comment]
Have a partially-working solution using Godot nodes:

https://github.com/naturally-intelligent/godot-4-glow-2d

Need help figuring out a way to clip glow behind other sprites.

**Comment by Joopster** [comment]
Any solution for this yet? Would really like to use this in my 2d opengl project.

**Comment by Calinou** [comment]
> Any solution for this yet? Would really like to use this in my 2d opengl project.

Glow is being implemented in https://github.com/godotengine/godot/issues/66455, although we can't guarantee it'll be merged for 4.3.

**Comment by theromis** [comment]
on MacOS with attached project getting weird artifact, is it expected?
<img width="674" alt="Screenshot 2024-03-07 at 17 50 43" src="https://github.com/godotengine/godot/assets/3720229/a6d6d68c-8088-4f2a-970d-d771fa50531d">
