### ISSUE TITLE
Shortcut text in PopupMenu of MenuButton cut off the first time menu is opened

### ISSUE THREAD

**Issue by bfedie518** [godotengine/godot#66453]
### Godot version

4.0 beta 1

### System information

Windows 10

### Issue description

If you set a shortcut on an item in a `PopupMenu`, the shortcut is shown next to the item.  The first time the menu is opened, the menu is not positioned correctly to accommodate this text.  Opening the menu a second time properly positions it.

This is a regression from 3.5.

![popup_menu_shortcut_bug](https://user-images.githubusercontent.com/17280776/192327601-0ecf53d3-1fa0-483d-8a19-c14db13903cd.gif)

### Steps to reproduce

1. Create a `MenuButton`
2. Add a `Shortcut` to one of the items
3. Run the project and click on the menu button

### Minimal reproduction project

[menu_button_shortcut_display_bug.zip](https://github.com/godotengine/godot/files/9647902/menu_button_shortcut_display_bug.zip)

**Comment by EricEzaM** [comment]
Ah, this was a cheeky one. Adding the item via `get_popup().add_shortcut()` works fine (i.e. is not affected by this bug), but calling `set_item_shortcut()` on an existing item does have thig bug, because `_shape_item()` is not called in the latter, but is in the former.
