### ISSUE TITLE
OpenGL: Font rendering quality is worse than in Vulkan

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#66463]
### Godot version

4.0.beta (53d2a9acd)

### System information

Fedora 36, GeForce GTX 1080 (NVIDIA 515.65.01)

### Issue description

Notice how text has black fringing on outlines for certain GUI elements:

*Click to view at full size, which is required for accurate comparison.*

OpenGL | Vulkan
-|-
![2022-09-26_19 42 04](https://user-images.githubusercontent.com/180032/192352465-c733ac09-ffef-436d-9683-21953ac6d936.png) | ![image](https://user-images.githubusercontent.com/180032/192353312-b7a73513-4723-4ad8-b334-df753c251f1d.png)

OpenGL | Vulkan
-|-
![2022-09-26_19 42 48](https://user-images.githubusercontent.com/180032/192352468-1939edc6-0b5c-4b06-b559-e2716ee4e49b.png) | ![image](https://user-images.githubusercontent.com/180032/192353388-d113be40-af16-473e-b751-01b2d72ccf55.png)

This is not present for *all* text though. Maybe it's caused by sub-pixel offset on certain Control nodes?

This may due to the font subpixel optimization blend mode not being updated for the OpenGL renderer. That said, the editor fonts do not use subpixel optimization (there are no settings for it, even).

**Note:** This is unrelated to font subpixel *positioning*, which only affects how the glyphs themselves are rasterized, not *how* the engine draws them. I'm referring to font LCD subpixel optimizations above.

### Steps to reproduce

- Open the editor on a project with the OpenGL renderer (`godot /path/to/project.godot --rendering-driver opengl3 --single-window`).

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
I spent some time yesterday investigating this issue. I think I have it narrowed down to an issue with the texture format in OpenGL. OpenGL appears to do something funny when blending the multiple samples taken for linear sampling.
