### ISSUE TITLE
SubViewports doesn't handle custom inputs

### ISSUE THREAD

**Issue by TandersT** [godotengine/godot#66461]
### Godot version

Godot Engine v4.0.beta1.mono.official.4ba934bf3

### System information

Windows 11, Vulkan API 1.2.0 - Using Vulkan Device #0: AMD - AMD Radeon RX 5700

### Issue description

Using the _Input method on a viewport does not work. Recreating the same situation in Godot 3.5, using .Input and a viewport, it works as intended. 

Example of code, that should as far as I know send my current event to the SubViewport

```
    public override void _Input(InputEvent @event)
    {
        if (@event is InputEventMouse _mouseEvent)
        {
            (GetNode<Viewport>("SubViewport") as Viewport)._Input(@event);
        }
    }
```

### Steps to reproduce

Create a viewport which includes any element which accept an input, and try to give the viewport an input through code.

### Minimal reproduction project

[InputExample.zip](https://github.com/godotengine/godot/files/9648710/InputExample.zip)

**Comment by Calinou** [comment]
Please create a minimal reproduction project in GDScript instead of C# for two reasons:

- Non-Mono builds of Godot are easier to set up and have less moving parts.
- This rules out C# being the cause of the bug.

**Comment by TandersT** [comment]
Converting it to GDScript I noticed the _input method was unavailable, and instead found push_input, which does send the input correctly. So it would seem that it's on my end. I'll close it if this issue.
