### ISSUE TITLE
Godot 4 b1 [C#] Possible wrong data type for param `what` in `Godot.Object.Notification`

### ISSUE THREAD

**Issue by asolux** [godotengine/godot#66460]
### Godot version

4.0 Beta 1

### System information

Windows 10

### Issue description

The current method signature in C# is as follows:
`Godot.Object.Notification(int what, [bool reversed = false])`

I think `int` should be `System.Int64` (`long`) here.
Since the triggered method `Godot.Object._Notification(System.Int64)`
already specifies `Int64` as data type and the expected constants `Godot.Object.Notification...` or `Godot.Node.Notification...`
already have `Int64` as data type.

### Steps to reproduce

example code:
```csharp
Godot.Object obj;
obj.Notification(Godot.Object.NotificationPredelete); // convert long to int issue
```

**Comment by Maclay74** [comment]
But it's long, isn't it?
![image](https://user-images.githubusercontent.com/5504685/192356267-b0d432d6-fc47-4a1f-96ce-5570a3d7ae33.png)

**Comment by asolux** [comment]
Yes. But only in method `_Notification` not in method `Notification`, as described above.

**Comment by Maclay74** [comment]
Right, my bad.

**Comment by TBleader** [comment]
This is happening in a lot of functions for C#. `ItemList.ItemSelected` sends the index as a long, but all of the `ItemList` functions that could use an index wants a long.

**Comment by avilches** [comment]
Hi, I guess the Notification constants should be changed too, right? Should I open an issue to change that?

![image](https://user-images.githubusercontent.com/194074/217905732-be1903fa-e1c5-461c-bf0e-54280158a7d0.png)

**Comment by raulsntos** [comment]
Unfortunately, signals and constants are more difficult to fix so I was unable to do so. Since we've already released RC1 and this would be a breaking change, I don't think we'll be changing it for 4.x.

The issue that tracks this for signals is https://github.com/godotengine/godot/issues/65749.
