### ISSUE TITLE
Inner class type is not highlighted in typed Array

### ISSUE THREAD

**Issue by Kubulambula** [godotengine/godot#66486]
### Godot version

4.0.beta1

### System information

Windows 10

### Issue description

Anytime you try to make a typed Array, the type is not highlighted if the type is an inner class.

### Steps to reproduce

Copy this code to any script and run it

```gdscript


class MyClass:
    func _init(num: int):
        print(num)


func _ready():
    var my_object: MyClass = MyClass.new(1)
    
    print(foo(my_object))
    print(bar(my_object))


# MyClass is highlighted
func foo(x: MyClass): -> MyClass:
    var y: MyClass = x
    return y


# MyClass is not highlighted
func bar(x: Array[MyClass]) -> Array[MyClass]:
    var y: Array[MyClass] = x
    return y

```

**Comment by MewPurPur** [comment]
> # MyClass is highlighted
Not really, you can replace "MyClass" with "Fart" in those instances and it'll still get highlighted. Highlighting there happens because a type is expected, not because it is confirmed.

But yes, a class should also be expected inside `Array[]`.

Seems like a good first issue :)

**Comment by JunoStrunk** [comment]
Hello! I would like to try and tackle this as my first issue. This will be my first time contributing to an open source project so I'll try my best!

**Comment by cgarciaromaguera** [comment]
Hi! This is my first time contributing to an open source project. I would like to try my best to give insight and possible fixes towards this issue.

**Comment by Calinou** [comment]
@JunoStrunk @cgarciaromaguera Feel free to open a pull request for this :slightly_smiling_face:

You can join the [Godot contributors chat](https://chat.godotengine.org/) to ask questions if needed.

**Comment by cgarciaromaguera** [comment]
In this case, should MyClass be highlighted specifically in blue?

**Comment by MewPurPur** [comment]
Sorry, I had a PR on topic and the naughty code was right in front of my eyes. Couldn't resist :(

**Comment by nongvantinh** [comment]
> Sorry guys! I had a PR on topic and the naughty code was right in front of my eyes, I just couldn't resist :(

You were supposed to ask @cgarciaromaguera first, he's really want to help.

**Comment by MewPurPur** [comment]
I knowww that's why I apologized.

**Comment by JunoStrunk** [comment]
No worries @MewPurPur ! I was actually pretty lost in the files. Looking at what you did to fix the bug was very helpful for my understanding :) I was in the complete wrong folder 😅
