### ISSUE TITLE
Feature Request - Ability to Bind shortcut actions to the mouse

### ISSUE THREAD

**Issue by liquidape** [godotengine/godot#6648]
Currently, you can change shortcuts only to the keyboard.  It would be nice to support binding shortcuts to the mouse as well.  (I was attempting to attach zooming in script editor to the mouse)

Additionally, support for mice with many buttons would be nice.  
![image](https://cloud.githubusercontent.com/assets/4421587/18962606/88048202-863f-11e6-9775-1b19c7898113.png)

**Comment by eska014** [comment]
See also issue #6366 for binding mouse wheel

**Comment by Noshyaar** [comment]
Still reproducible/relevant in 3.1 master 9ad1800 : afaik you can't bind mouse button as editor shortcut yet

**Comment by Calinou** [comment]
Closing in favor of #38326, which essentially covers the same issue (but with more information).
