### ISSUE TITLE
V-Sync issues after AMD driver update 22.7.1

### ISSUE THREAD

**Issue by R0Zen** [godotengine/godot#66494]
### Godot version

3.5-stable

### System information

Win10, gles3, rx6500xt (22.9.1)

### Issue description

after I updated my radeon gpu driver from 22.6.1 to 22.7.1 stutter issues started with godot 3.5 with every 3d scene that I stated (don't know if it's effecting 2d, never tested it).
using the debug menu I found that while the game thinks its running in 60fps (limited by vsync) it actually updating much slower as you can see by the  process timing. for 60 fps it should be about 17ms and not 49-50ms.
I found out that enabling "V-Sync Via Compositor" in the project menu solve this issue and now the process is running at about 17ms.
But still, maybe its placebo but 22.6.1 felt better with less micro stutters, maybe its just me.

![godot_bug](https://user-images.githubusercontent.com/13879736/192516432-baa69311-6cd5-4830-85ce-399b1e1b77b2.jpg)

**Quick edit:**
Can reproduce this issue with the TPS demo. and "V-Sync Via Compositor" fix works only in window mode as in full screen mode the issue persists.

### Steps to reproduce

- create 3d gles3 project in godot 3.5
- enable "Use V-Sync"" in project settings.
- use radeon driver 22.7.1 (also tested with 22.9.1 with same result)

**Comment by Calinou** [comment]
> I found out that enabling "V-Sync Via Compositor" in the project menu solve this issue and now the process is running at about 17ms.

The issue with this setting it behaves in an unreliable manner depending on hardware and software configurations. On some PCs, it'll cause the refresh rate to be halved for no reason.

**Comment by R0Zen** [comment]
> Can you reproduce this with V-Sync disabled? In other words, does the frametime consistently stay below 16.6 ms when V-Sync is disabled? Also try disabling V-Sync and setting **Debug > Fps > Force Fps** to `61`.
> 
> Lastly, can you reproduce this in a project that uses GLES2 instead of GLES3?
> 
> > I found out that enabling "V-Sync Via Compositor" in the project menu solve this issue and now the process is running at about 17ms.
> 
> The issue with this setting it behaves in an unreliable manner depending on hardware and software configurations. On some PCs, it'll cause the refresh rate to be halved for no reason. This is why the setting was dropped in 4.0.

Sure thing, just me to update back to the new version again and I will update this replay. 
(I just downgraded to 22.6.1)

**Comment by Calinou** [comment]
The latest AMD beta drivers do mention a related known issue: https://www.techpowerup.com/download/amd-radeon-graphics-drivers/

> When Vertical Refresh Sync is set globally to Always Off, system stuttering or driver timeout may occur during video playback using Radeon RX 6000 series GPUs.

**Comment by R0Zen** [comment]
> The latest AMD beta drivers do mention a related known issue: https://www.techpowerup.com/download/amd-radeon-graphics-drivers/
> 
> > When Vertical Refresh Sync is set globally to Always Off, system stuttering or driver timeout may occur during video playback using Radeon RX 6000 series GPUs.

for what understand the 22.7.1 driver had a lot of opengl optimization but it also broke some stuff.
I will check later if any opengl software/games effected in my system to understand if its only a driver issue or something else.

**Comment by comminux** [comment]
https://www.amd.com/ru/support/kb/release-notes/rn-rad-win-22-10-1

> When Vertical Refresh Sync is set globally to Always Off, system stuttering or driver timeout may occur during video playback using Radeon™ RX 6000 series GPUs. [**Resolution targeted for 22.10.2**]

**Comment by comminux** [comment]
I just downloaded the new driver version 22.10.2 and the problem no longer happens when normal vertical synchronization is enabled. Enabling synchronization via compositor is no longer required.

![Снимок экрана 2022-10-22 213141](https://user-images.githubusercontent.com/14937307/197357121-c4a6c059-d37c-4052-b6c3-dc6e67fd4a29.png)

**Comment by R0Zen** [comment]
@comminux I will check it tomorrow with the newest driver (22.10.3) and will update this reply.
Hope this really got fixed.
