### ISSUE TITLE
Minor issue: clicking on a scene marks it as dirty (*) and needing to be saved

### ISSUE THREAD

**Issue by juddrgledhill** [godotengine/godot#6649]
**Operating system or device - Godot version:**
windows 10, G2.1

**Issue description** (what happened, and what was expected):
I was closing out of the tools, and wanted to save everything. I noticed that clicking somewhere without making changes showed the scene as needing to be saved.

**Steps to reproduce:**
In the 2d scene editor. Make a scene.
Save the scene.
Click somewhere in the scene, but do not change anything about the scene (do not click on any objects or anything like that)
The (*) indicator shows up in the tab for that scene

--just a weird little nitpick

**Link to minimal example project** (optional but very welcome):

**Comment by Noshyaar** [comment]
Can't reproduce in 9ad1800, closing as fixed (hopefully)
