### ISSUE TITLE
LIGHT_POSITION in canvas shader Light processor does not work as expected.

### ISSUE THREAD

**Issue by Syndicist** [godotengine/godot#66508]
### Godot version

4.0.dev

### System information

Windows 10, Vulkan, NVIDIA GeForce GTX 1070

### Issue description

Given a DirectionalLight2d's light doesn't have a position like normal point lights do, I was expecting some sort of difference in how I need to handle LIGHT_POSITION. However, LIGHT_POSITION doesn't seem to return anything useful for processing directional lights at all. As far as I can tell, for DirectionalLight2d lights, LIGHT_POSITION returns the position of the top-left corner of the active camera. This appears independently true within and without the editor:
![image](https://user-images.githubusercontent.com/31106886/192596452-316889f1-36b4-47af-b967-7f20c972352a.png)

I think it'd be preferable to return the LIGHT_VEC as in the 3.x stable Light processor if possible. But, I'm no shader pro. Maybe this is actually useful in some way I don't understand.

### Steps to reproduce

I discovered this while porting over a cel shader I found on shaderfrog, but you can find this by using LIGHT_POSITION for anything you'd want to use it for I'd think. For posterity, this is my shader:
```
shader_type canvas_item;

uniform vec3 cameraPosition = vec3(0.0f);
uniform float specularAdd = 0.5f;
uniform vec4 edgeColor : source_color = vec4(0.0f);

void light() {
    vec3 worldPosition = FRAGCOORD.xyz;

    // Calculate the normal including the model rotation and scale
    vec3 worldNormal = NORMAL.xyz;
    vec3 lightVector = normalize( LIGHT_POSITION - worldPosition );
    vec3 cameraVector = normalize(LIGHT_POSITION - cameraPosition - worldPosition );
    vec4 finalColor = (texture(TEXTURE, UV) + LIGHT_COLOR) / 2.0f;
    
    // Adding the difference from the main color for the highlighted part
    vec3 specularColor = vec3(finalColor.x + specularAdd, finalColor.y + specularAdd, finalColor.z + specularAdd);
    vec3 reflectance = normalize(2.0 * dot(lightVector,worldNormal)*worldNormal-lightVector);

    
    if(dot(lightVector,worldNormal)<0.3){
        LIGHT = edgeColor;
    } else {
        if (dot(worldNormal,lightVector)>0.0){
            LIGHT = finalColor;
            if (length(cameraVector - reflectance)<0.6){
                    LIGHT = vec4(specularColor, 1.0);
            }
        }
    }
}
```

### Minimal reproduction project

[directionallight.zip](https://github.com/godotengine/godot/files/9658501/directionallight.zip)

**Comment by clayjohn** [comment]
For directional lights ``LIGHT_POSITION.xy`` is the direction but ``LIGHT_POSITION.z`` is still the lights height. The docs should be updated to reflect this. 

There is also a ``is_directional`` boolean in the shader code that needs to be exposed to users so you can have different logic for directional lights

**Comment by Syndicist** [comment]
For anyone that needs a workaround to this like myself, it's not a perfect solution, but since we know that `LIGHT_POSITION.xy` and generally an actual light position won't be, we can use that as the conditional. Floating point precision makes it a bit less simple than we want it to be, but this works for me:
```
if( ceil(abs(LIGHT_POSITION.x) + abs(LIGHT_POSITION.y)) == 2.0f || floor(abs(LIGHT_POSITION.x) + abs(LIGHT_POSITION.y)) == 0.0f) {
	// handle directional lights
}
```
