### ISSUE TITLE
Error thrown when enabling "Generate Mipmaps" on a font (only in Advanced Import Settings dialog)

### ISSUE THREAD

**Issue by j4nw** [godotengine/godot#66507]
### Godot version

v4.0.beta1.official [20d667284]

### System information

Windows 10

### Issue description

Checking the Generate Mipmaps checkbox in Advanced Import Settings for a font throws the error:

`The new image mipmaps configuration must match the texture's image mipmaps configuration`

Doesn't occur when checking the same checkbox in the regular Import tab.

### Steps to reproduce

- Drag-and-drop any font into a project (checked with a few ttf and otf files, both in an existing and an empty project)
- Double click the font to open Advanced Import Settings
- Check Generate Mipmaps

**Comment by Calinou** [comment]
cc @bruvzg
