### ISSUE TITLE
middle mouse button alternative

### ISSUE THREAD

**Issue by raould** [godotengine/godot#6651]
**Operating system or device - Godot version:**
Win 7 32bit Pro
Godot 2.1
desktop computer with mouse

**Issue description** (what happened, and what was expected):
Middle mouse button is too hard to use because it is also the scroll wheel.

This has come up in other issues
https://github.com/godotengine/godot/issues/53

If anybody can make it so that e.g. maybe I can use the spacebar to replace middle-mouse-button, that would be cool. I looked in Settings but it doesn't look like I can do that?

(thanks for a cool app)

**Comment by eska014** [comment]
In the editor settings, under "3d Editor", activate "Emulate 3 Button Mouse".
Use the "Orbit"/"Pan"/"Zoom Modifier" settings to configure the keys to use

**Comment by eska014** [comment]
Already implemented, so closing
