### ISSUE TITLE
C# : Source generator fails to recognize default exported properties that reference other things in the assembly if their name isn't fully qualified.

### ISSUE THREAD

**Issue by BerkUnver** [godotengine/godot#66523]
### Godot version

4.0 beta 1

### System information

Windows 10 Home, GLES3, Intel Core i7-6567U, Intel Iris Graphics 550 (30.0.100.9955), 16GB RAM

### Issue description

If the default value of an exported property references a function/enum value/property that doesn't have a fully qualified name, building the project fails because the source generator is unable to recognize that symbol.

### Steps to reproduce

Make a node with an exported property with a default value that references a symbol that isn't part of the same namespace as the current class that has that namespace included with a using statement. The source generator spits out an error and building the project fails.

### Minimal reproduction project

[Godot4SourceGeneratorBug.zip](https://github.com/godotengine/godot/files/9660939/Godot4SourceGeneratorBug.zip)

**Comment by raulsntos** [comment]
Related to https://github.com/godotengine/godot/issues/65938
