### ISSUE TITLE
Editor crashes when trying to snap object to floor

### ISSUE THREAD

**Issue by dolichomps** [godotengine/godot#66522]
### Godot version

v4.0.beta1.official [20d667284]

### System information

Windows 11

### Issue description

Editor crashes when trying to snap a Node3d to the floor from the `Transform->Snap Object to Floor` menu when `physics/3d/run_on_separate_thread` is enabled.

Console output:
```
ERROR: Space state is inaccessible right now, wait for iteration or physics process notification.
    at: (servers/physics_3d/godot_physics_server_3d.cpp:194)
```

### Steps to reproduce

Enable `physics/3d/run_on_separate_thread`, add any node that inherits from Node3d (example: a MeshInstance3d for a floor and a MeshInstance3d cube) , try to snap the cube to the floor.

### Minimal reproduction project

[snap_object_to_floor.zip](https://github.com/godotengine/godot/files/9660924/snap_object_to_floor.zip)

**Comment by timothyqiu** [comment]
`nullptr` is returned when this happens:

https://github.com/godotengine/godot/blob/92bcd3c01d5188480793c03b2b50e97363ceb624/servers/physics_3d/godot_physics_server_3d.cpp#L194

So the `ss` here is null:

https://github.com/godotengine/godot/blob/92bcd3c01d5188480793c03b2b50e97363ceb624/editor/plugins/node_3d_editor_plugin.cpp#L7021
