### ISSUE TITLE
GDScript - `Callable` created by lambda may be omitted when connected to signal.

### ISSUE THREAD

**Issue by ydipeepo** [godotengine/godot#66538]
### Godot version

v4.0.beta1.official [20d667284]

### System information

It's not system specific error.

### Issue description

When connecting a Callable created with lambda to a signal, it sometimes does not work.

### Steps to reproduce

It can be reproduced with the following code:

### Minimal reproduction project

```
signal S

func _make_g():
	return func(n): print(n)

func _ready():
	var f = func(n): print(n)
	S.connect(f.bind(10))
	S.connect(f.bind(20)) # This connection would be omitted.
	S.connect(_make_g().bind(30))
	S.connect(_make_g().bind(40))

	S.emit()
	# 40
	# 30
	# 10
```

**Comment by KoBeWi** [comment]
You can't connect a signal to the same method twice. This includes lambdas.
![image](https://user-images.githubusercontent.com/2223172/192777370-6206da38-be2b-4076-ae15-3c8e87c437b7.png)

`_make_g()` works because you are creating a new callable.

**Comment by ydipeepo** [comment]
Am I correct in understanding that it will be the same if bind?

**Comment by KoBeWi** [comment]
Yes, bind just adds extra arguments; internally it's still the same callable.

**Comment by ydipeepo** [comment]
@KoBeWi Okay, thanks! Take ur time.
