### ISSUE TITLE
GDScript 2.0: `assert()` containing line breaks results in an syntax error

### ISSUE THREAD

**Issue by ydipeepo** [godotengine/godot#66535]
### Godot version

v4.0.beta1.official [20d667284]

### System information

It's not system specific error.

### Issue description

Any condition containing newlines in assert's `()` will result in a syntax (grammatical?) error.

### Steps to reproduce

<strike>

```GDScript
assert(
    true or
    true) # It raises "Expected expression to assert." at edit time.
```
But. Its works with `\`:
```GDScript
assert( \
    true or \
    true)
```

</strike>

```GDScript
assert(
    true) # error
```

### Minimal reproduction project

Include line breaks in assert expression.

**Comment by TheDuriel** [comment]
This is correct? You can't do this in any other context either.

**Comment by ydipeepo** [comment]
@TheDuriel Idk but I was wondering if it was allowed cuz it was possible in 3.5.
I hitted this problem when porting my addons.

Normal calls allow line breaks like this:
```GDScript
my_func(
    "text",
    1234,
    true
)
```

**Comment by ydipeepo** [comment]
Yup, I know. Is it okay to recognize that it has become stricter?

**Comment by TheDuriel** [comment]
I'm not convinced from your example that is has.

**Comment by ydipeepo** [comment]
I checked it again.
It seems that line breaks between operands are not allowed in this version at the `or` / `and`, binary and unary operators in the function call arguments.
I don't know if it's a bug or a lang spec change, but I was able to deal with it like this:
```GDScript
assert((
    1 +
    1
)) # works
```

**Comment by ydipeepo** [comment]
Sorry, I looked further and it seems that regardless of the operator, simply cannot break a line.

https://github.com/godotengine/godot/issues/66535#issuecomment-1260907923

**Comment by hsandt** [comment]
To complete use cases, I had this issue when splitting my long assert message over multiple lines:

```gd
	assert(is_on_floor(), "_get_floor_tangent: is_on_floor() is true yet get_floor_normal() " +
		"returned Vector2.ZERO.")
```

Replacing `assert` with a condition + `push_warning` for instance, will work.

**Comment by adamscott** [comment]
I confirm this issue on master (fcba87e).

### Minimal reproduction project
[66535.zip](https://github.com/godotengine/godot/files/10369078/66535.zip)
