### ISSUE TITLE
default app gui color scheme is opposite what it should be if you ask me

### ISSUE THREAD

**Issue by raould** [godotengine/godot#6654]
**Operating system or device - Godot version:**
win 7 32bit pro
godot 2.1
desktop
(also, same thing for linux ubuntu 64 bit laptop)

**Issue description** (what happened, and what was expected):
The color scheme is darker than the default on most machines. E.g. browsers start off with a white page background with black text by default. (a) If I like white then Godot is different and that is annoying. (b) if I use a screen color inverter (which i do) to make most everything become darker, so that the browser pages are now white text on black background, then Godot is now bright which is annoying. In other words if an app has a different default color relationship of fg + bg vs. the standards (which in this day and age means whatever web browsers do by default) i think it is not good ux. (i mean same goes for lightroom or whatever else.)

note that (depending on what system was used to invert system colors) things sometimes get worse because of Godot's cross platform nature, is my guess: the I-bar text caret mouse cursor doesn't get the color changed for some reason so then i end up with a white on white mouse cursor in the text editor! but the arrow mouse cursor does get inverted properly. etc. etc. etc.

(thanks for a great fun program.)

**Comment by vnen** [comment]
Funny that you want Godot defaults to light theme so your color inverter makes it dark. It's ironic, even.

Standard here is a subjective matter. Many (if not most) programming environments use dark themes by default. Blender also does it. Godot is not that different.

Also, Godot has editor themes. My suggestion is that you get a light theme (like one from https://github.com/Geequlim/godot-themes) and then it should work for your workflow.

**Comment by raould** [comment]
agreed it is ironic whichever side you look at it from. :-) i will go get a theme, thanks!

**Comment by raould** [comment]
p.s. i went and tried to install the themes on my win7 machine and failed to understand at all how to make it work. so i think the ux there is unfortunately an impediment.
