### ISSUE TITLE
'Y' key does not work most of the time

### ISSUE THREAD

**Issue by komatar** [godotengine/godot#66562]
### Godot version

v4.0.beta1.official [20d667284]

### System information

Windows 10

### Issue description

Since Godot 4.0 Beta 1, Godot does not detect my Y key and is probably, as I've been testing it over the past few days, automatically applying CTRL without me pressing it. I use a **QWERTZ layout**.

The issue already starts at the project list, where **letter Y is not showing up** when naming/renaming/filtering projects. Same thing happens in the editor when interacting with nodes or writing code in the code editor. The key does not produce a letter. 

There are only two scenarios where it works correctly:
- if I hold down SHIFT, then it will produce _capital Y_ (or if I have caps lock enabled _lowercase y_), and
- when setting a key for input mapping

I've used all versions of Godot 4.0 Alpha and none of them had this issue. I've also tried a nightly build of 4.0 Beta and the problem persists. I have tried opening projects initialized in an Alpha version and it makes no difference, I can then reopen them in Alpha versions and the key works.

**What I've discovered so far**
By playing around in the code editor, I presume what is happening is that CTRL is always triggered when pressing the Y key. Basically I can **CTRL + Z** to undo text and if I try to redo it with the **CTRL + Y** command it does nothing. To redo text, I have to press the **Y key** only.

Here is a screen recording with visible keystrokes showing the issue.:

https://user-images.githubusercontent.com/24679910/192858784-3a9190e4-2d35-4e7e-9d1c-33cfe28e233f.mp4

**What I've already tried**
- changing layout to QWERTY -> problematic key is still Y and not Z
- reseting the editor, redownloading and replacing the exe
- pressing CTRL, ALT and SHIFT in case of a phantom key press
- restarting my PC and shutting down all background software
- two other keyboards
- windows on-screen keyboard

Here is a screen recording of rejecting the Y letter while clicking the on-screen keyboard:

https://user-images.githubusercontent.com/24679910/192861567-1af9bee5-a4fe-48da-8185-7565eb8715dc.mp4

### Steps to reproduce

Open the editor, start typing into the Filter project input and **y** key is ignored when pressed.

**Comment by Zireael07** [comment]
If I'm reading this correctly, alpha 16 (the last alpha) detects the key correctly but beta 1 does not?

This would help us narrow down when the problem started

**Comment by bruvzg** [comment]
I can't reproduce it on Windows 11, make sure you have cleaned up editor configs and project input maps, see https://docs.godotengine.org/en/latest/tutorials/io/data_paths.html for editor config locations.

**Comment by komatar** [comment]
> I can't reproduce it on Windows 11, make sure you have cleaned up editor configs and project input maps, see https://docs.godotengine.org/en/latest/tutorials/io/data_paths.html for editor config locations.

Thank you, this was it. The issue was with the _editor_settings-4.tres_ file. Redo was bound to the Y key, so I guess that explains this whole thing. But I'm almost certain I did not change editor settings since an early alpha build.

```
[sub_resource type="InputEventKey" id="InputEventKey_fuud4"]
keycode = 89
```

> If I'm reading this correctly, alpha 16 (the last alpha) detects the key correctly but beta 1 does not?
> 
> This would help us narrow down when the problem started

If it's still relevant, yes I've used alpha 16 without an issue, this issue appeared with beta.
I'm pretty sure I have not touched editor settings at all, besides binding redo to CTRL+Y on an early alpha build. Then it carried over, so I've never needed to change editor settings and I've never run into an issue until the beta.

**Comment by Calinou** [comment]
@komatar Remember that for GitHub video previews to work, you need to have a blank line before *and* after the video URL. I edited your post accordingly, but remember to do this in the future :slightly_smiling_face:

**Comment by bruvzg** [comment]
> But I'm almost certain I did not change editor settings since an early alpha build.
> I'm pretty sure I have not touched editor settings at all, besides binding redo to CTRL+Y on an early alpha build.

It's likely a result of https://github.com/godotengine/godot/pull/65241, opening beta changed `Ctrl+Y` binding to a new modifier code value first, and then opening alpha removed an incompatible modifier code, leaving only `Y`.
