### ISSUE TITLE
Project immediately shows up as missing

### ISSUE THREAD

**Issue by Swarkin** [godotengine/godot#66571]
### Godot version

4.0.beta1 apk

### System information

Android 12 on Galaxy S20 FE

### Issue description

Imported projects which haven't been created or edited with the Godot mobile version instantly show up as missing.

https://user-images.githubusercontent.com/102416174/192893165-20ef90fc-2cea-4a79-87ac-f328f12b87ec.mp4

### Steps to reproduce

Try to import a project created or edited on desktop versions of Godot.

**Comment by m4gr3d** [comment]
@Swarkin Does this issue still reproduce in the latest beta?

**Comment by Swarkin** [comment]
Seems like this was fixed! Importing a project now works normally.

**Comment by Swarkin** [comment]
Seems like this issue is back in beta11 for android.
I haven't tested it with older versions of the editor yet.

**Comment by m4gr3d** [comment]
@Swarkin Can you check if this is still an issue for the Play store version of the Godot Editor - https://play.google.com/store/apps/details?id=org.godotengine.editor.v4

**Comment by Swarkin** [comment]
For some reason I'm unable to reproduce this issue at all in neither the Playstore version nor the old betas. I've tried the exact same project and version, but it works fine this time. Something else has to be causing this issue...

If I ever manage to reproduce this again in the future I'll send that project here.

**Comment by m4gr3d** [comment]
Thanks for the update! I'll close the issue for now, but feel free to re-open if the issue occurs again.
