### ISSUE TITLE
Shader using source_color uses a more saturated color than the actual one chosen

### ISSUE THREAD

**Issue by swordcube** [godotengine/godot#66572]
### Godot version

v4.0.beta1.official [20d667284]

### System information

Arch Linux, Vulkan, Intel HD Graphics 4400

### Issue description

The shader uses a more saturated version of the color you give it
![image](https://user-images.githubusercontent.com/49110074/192893379-d84f78e7-28d5-4a27-9d49-a455c9825c15.png)

The shader parameter for `color` is lighter, and yet shows up as a more saturated color on the preview and the object itself.

This is my first time making an issue on this GitHub, So I may have done something incorrectly, If I have please let me know!

### Steps to reproduce

You can write a shader as simple as this:
```
shader_type canvas_item;

uniform vec4 color : source_color;

void fragment() {
    COLOR = color;
}
```

And use it on an object (I've only tested with a Sprite2D, i don't know if this happens on 3D objects)
Choose a lighter color for the `color` shader parameter and watch it be more saturated.

I have uploaded the ZIP file for a reproduction project. It includes an example scene with a sprite that has the shader using the code above.

### Minimal reproduction project

[Shader Issue.zip](https://github.com/godotengine/godot/files/9669091/Shader.Issue.zip)

**Comment by swordcube** [comment]
I just figured out that this code:
```
shader_type canvas_item;
uniform vec4 color : source_color;

void fragment() {
	COLOR = vec4(color.r*2.0, color.g*2.0, color.b*2.0, color.a);
}
```

fixes the issue

**Comment by swordcube** [comment]
> I just figured out that this code:
> 
> ```
> shader_type canvas_item;
> uniform vec4 color : source_color;
> 
> void fragment() {
> 	COLOR = vec4(color.r*2.0, color.g*2.0, color.b*2.0, color.a);
> }
> ```
> 
> fixes the issue

Okay this mostly fixes the issue, it's more of a weird workaround

**Comment by clayjohn** [comment]
> Okay this mostly fixes the issue, it's more of a weird workaround

I would have been very surprised if that actually fixed the issue.

I have a feeling this issue is a part of https://github.com/godotengine/godot/issues/61697, but we need to investigate a bit more to see if it actually is

**Comment by tinmanjuggernaut** [comment]
It's a lack of srgb/linear conversion issue. The color needs to be converted to SRGB to display properly. Should be built in, but this will fix it:

```
shader_type canvas_item;

uniform vec4 color : source_color;

vec4 toSRGBSlow(vec4 col) {
    bvec4 cutoff = lessThan(col, vec4(0.0031308));
    vec4 higher = vec4(vec3(1.055)*pow(col.rgb, vec3(1.0/2.4)) - vec3(0.055), col.a);
    vec4 lower = vec4(col.rgb * vec3(12.92), col.a);
    return mix(higher, lower, cutoff);
}

void fragment() {
    COLOR = toSRGBSlow(color);
}
```

![image](https://user-images.githubusercontent.com/632766/193001706-35fe8c67-8e7c-4ea1-a1ff-67d2be48e08f.png)

Alternative versions that are faster:
```
vec4 toSRGBFast(vec4 col) {
	return vec4(sqrt(col.rgb), col.a);
}
vec4 toSRGBMed(vec4 col) {
	return vec4(pow(col.rgb, vec3(.4545)), col.a);
}
```

The color looks fine on 3D shaders.

**Comment by swordcube** [comment]
it should really convert to SRGB by default, but thanks for the workaround

**Comment by Calinou** [comment]
`source_color` is formerly what was called `hint_albedo`. It should not be used in 2D, only in 3D.

**Comment by swordcube** [comment]
what should I use for 2d instead then?

**Comment by Calinou** [comment]
> what should I use for 2d instead then?

Nothing – remove the `source_color` hint entirely.

**Comment by swordcube** [comment]
> > what should I use for 2d instead then?
> 
> Nothing – remove the `source_color` hint entirely.

Well i want to be able to choose a color with 2D without having to use this
![image](https://user-images.githubusercontent.com/49110074/193334537-2c9696da-c635-4b7a-8689-65d50da14789.png)

**Comment by Zireael07** [comment]
Seconding @swordcube, I'm using hint_color for my 2D shaders to be able to pick colors in editor
