### ISSUE TITLE
Warning message for using the look_at() function on objects before they have been loaded into the scene

### ISSUE THREAD

**Issue by bepthomp** [godotengine/godot#66576]
### Godot version

4.0.beta1

### System information

Windows 10, Vulkan, Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz   2.21 GHz

### Issue description

When using the look_at() function on an instantiated object that has not been added to a scene yet, the object will spawn into the scene at position (0,0,0).
This is likely because this function uses global coordinates, which the object wouldn't have until it is added into the scene.

It would be helpful for the function to throw a warning in this situation.
It would help the user troubleshoot, especially new users who do not know the intricacies of global vs local coordinates yet.
Perhaps the warning could direct the user to look_at_from_position(), which works perfectly in this situation.

### Steps to reproduce

- Instantiate an object
- Use the look_at() function on the object, before it is added to the scene
- When the object is added to the scene, its position will be (0,0,0)

### Minimal reproduction project

[look_at() git issue.zip](https://github.com/godotengine/godot/files/9670367/look_at.git.issue.zip)

**Comment by KoBeWi** [comment]
> [look_at() git issue.zip](https://github.com/godotengine/godot/files/9670367/look_at.git.issue.zip)

Next time remove `.godot` folder when uploading MRP.
