### ISSUE TITLE
Dynamically created scenes via code share resources although being duplicated

### ISSUE THREAD

**Issue by originseekermmo** [godotengine/godot#66589]
### Godot version

4.0.beta1

### System information

MacOs 11.5.2, Intel Iris Plus Graphics 655

### Issue description

 have spent countless of hours trying to apply a texture on a MeshInstance3d within a `SubViewport` programmatically to no avail.

- I have a directory that contains two image files that serve as textures for a MeshInstance3d
- This directory is read, the image files are loaded and duplicated (so sharing does not occur)
- Each creates a Scene that contains a SubViewport with a MeshInstance3D where the texture is applied

I have two instances of the scene instantiated but both mesh instances always use the material of the latest applied texture, instead of each texture applying seperately.

Script that is reading the directory and instantiating the scenes

```gdscript
@tool
extends BoxContainer

const tiles_path = "res://addons/map_editor/tiles"
const tile_scene = preload("res://addons/map_editor/TileRenderer/TileSubview.tscn")

func _ready():
    var fs = FileSystem.new()
    
    var files = fs.read_dir(tiles_path).filter(func(f): return ".import" not in f)
    
    for file in files:
        var texture = load(file).duplicate()
        var scene = tile_scene.instantiate()
        scene.texture = texture
        add_child(scene)
```

Script for applying textures (the owner node contains the resource as export var and has a getset that calls the set_texture method)

```gdscript
@tool
extends MeshInstance3D

@export var texture: Resource

func set_texture(texture):
    
    if texture == null:
        set_surface_override_material(0, null)
        return

    var material = StandardMaterial3D.new()
    material.albedo_texture = texture
    
    var uv_mapper = UvMapper.new()
    var surface_definition = uv_mapper.map_cube_uvs(self.mesh)

    var array_mesh = ArrayMesh.new()
    array_mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, surface_definition.duplicate())
    mesh = array_mesh

    material.uv1_scale = Vector3(3, 1, 1)
    set_surface_override_material(0, material.duplicate())
```

Whichever Resource is loaded and applied last, applies it to all scenes. I tried making the resource unique with set_local_to_scene(true) to no avail.
Which leads me to thinking it might be a bug

### Steps to reproduce

- Open `ui_window.tscn` within the `addons/map_editor` directory in the editor
- Use "Play Scene" 
- Observe two MeshInstance3d that share the same resource, namely the last one applied 

### Minimal reproduction project

[godot3d.zip](https://github.com/godotengine/godot/files/9673431/godot3d.zip)

**Comment by lewiji** [comment]
In your `Viewport` node named `SubViewport` in `TileSubview.tscn`, tick the "Own World" property

What's happening is both meshes are being drawn in the same World (i.e. visual server instance) so they are being drawn one on top of the other in both viewports.

Enabling "own world" gives them different visual spaces to render in.

**Comment by originseekermmo** [comment]
Thank you so much @lewiji 
I can confirm this works flawlessly and thanks for the explanation, it makes total sense. Not a bug and can be closed.
