### ISSUE TITLE
Very bright objects does not approach/become white with filmic tonemapper

### ISSUE THREAD

**Issue by atirut-w** [godotengine/godot#66591]
### Godot version

v4.0.beta1.official [20d667284]

### System information

N/A

### Issue description

This is basically https://github.com/godotengine/godot-proposals/issues/3214 but for the Filmic tonemapper. It seems that both ACES and Filmic are supposed to have this behavior according to Blender, but only ACES got the "fitted" treatment despite Filmic being the "preferred" tonemapper in 4.0 according to the tonemapper used if you enabled tonemap in the preview world env.

This issue also applies to 3.x.
For details about Filmic, see [Color Grading and Filmic Tonemapper](https://docs.unrealengine.com/4.27/en-US/RenderingAndGraphics/PostProcessEffects/ColorGrading/)(Unreal Doc)

Blender reference:
![Screenshot_20220929_172545](https://user-images.githubusercontent.com/25323231/193007633-dd562e31-a9a6-4d27-85b1-580c20e39713.png)

**Comparison of ACES and Filmic in 4.0**
ACES:
![Screenshot_20220929_172244](https://user-images.githubusercontent.com/25323231/193007019-4c66b1c1-1777-4e08-b7a0-2e3fdbf65d98.png)
Filmic:
![Screenshot_20220929_172340](https://user-images.githubusercontent.com/25323231/193007181-7a4dc6c5-138a-4c7e-b331-021a39274a22.png)

**Same comparison in 3.x**
ACES Fitted:
![Screenshot_20220929_171928](https://user-images.githubusercontent.com/25323231/193006373-557c87e1-feed-4656-89b7-f38971286460.png)
Filmic:
![Screenshot_20220929_172002](https://user-images.githubusercontent.com/25323231/193006464-81cc33a8-13cc-4447-9450-123b0f6310b3.png)

### Steps to reproduce

1. Set up a scene with a world env, set tonemapper to Filmic
2. Place down some objects and a high energy directional light.

**Comment by clayjohn** [comment]
This isn't a bug, it is a feature proposal. Feature proposals should be made in the https://github.com/godotengine/godot-proposals repository
