### ISSUE TITLE
Show how many hours you have been working on a project

### ISSUE THREAD

**Issue by TimPlay** [godotengine/godot#6659]
I think that it would be an interesting feature to display somewhere how many hours you have been working on a project. Although non-essential, it would be cool to say, "After 2 years of working on this game, I have put in 4,000 hours into it."

Of course this wouldn't track times in other programs, but it could just track how much time you have the editor open in a project.

**Comment by SuperUserNameMan** [comment]
so if i let the editor opened while going to the toilets (which happen quite frequently), i'd be able to say "After 2 years of working on this game, I have put in 4,000 hours into it and/or over the throne playing tetris".

more seriously, it's not a bad idea. Having access to this king of stats could be interesting and fun.
Maybe we could just use an external application for that ?
http://alternativeto.net/software/apps-tracker/?license=free

**Comment by akien-mga** [comment]
It would be pretty easy to make as an editor plugin.

**Comment by rgrams** [comment]
Someone made one: https://github.com/YeOldeDM/godot-time-tracker, it's in the AssetLib. 
However it doesn't stop counting up when you alt-tab out. Does anyone know how to do that? I hoped there was some kind of signal when the window loses focus, but I haven't found anything yet.

**Comment by akien-mga** [comment]
Try to grab `NOTIFICATION_WM_*` in `Object._notification(what)`: http://docs.godotengine.org/en/latest/classes/class_mainloop.html?highlight=NOTIFICATION_WM

**Comment by rgrams** [comment]
@akien-mga  Aha! That works perfectly, thanks a lot!

**Comment by mefihl** [comment]
@rgrams very nice plugin but display time in own panel is not good. Maybe display time after toolbar with 2D, 3D, Script....

**Comment by TimPlay** [comment]
@rgrams that works great, thanks for sharing!

**Comment by rgrams** [comment]
@mefihl Yeah, I agree so I am making my own. One the top toolbar like you said, only on the other side, next to the rainbow sound bar. :) Just have one left to sort out.

**Comment by rgrams** [comment]
@mefihl Here, see how you like this: https://github.com/rgrams/ross_project_timer

**Comment by mefihl** [comment]
@rgrams Super ;). Display days and hours?

**Comment by rgrams** [comment]
@mefihl Hours, minutes, and seconds. I decided not to do days, the hours just count up to hundreds, thousands, etc.

**Comment by slapin** [comment]
Well, a fancy thing but too unrealistic.
1. It won't count hours editing scripts with vi
2. It will count idle hours.

And also, there is no value in such calculation.
Will work as fetish number though.

**Comment by akien-mga** [comment]
Closing as this feature is available through the AssetLib (and that's good enough IMO).
