### ISSUE TITLE
OpenGL: Light3D shadow rendering is not reimplemented yet 

### ISSUE THREAD

**Issue by Henrique-Henrique** [godotengine/godot#66596]
### Godot version

4.0.beta1

### System information

Windows 10/11

### Issue description

Shadow dont work when using OpenGL3 driver

In editor:
![image](https://user-images.githubusercontent.com/57235054/193031757-5820ccdc-844b-4e77-b206-48922952aa44.png)

In Game:
![image](https://user-images.githubusercontent.com/57235054/193031818-3476f91d-b31f-41fd-8b61-ec5831eaaaf7.png)

### Steps to reproduce

1. Create a Project
2. Change on **Project Settings** the _Rendering Driver_ to OpenGL3
3. Add some MeshInstance3D with Mesh
4. Add DirectionalLight3D or any light node and active Shadow on Inspector
5. Add Camera3D

### Minimal reproduction project

[shadow.zip](https://github.com/godotengine/godot/files/9674620/shadow.zip)

**Comment by Calinou** [comment]
This is because shadows haven't been implemented yet in the OpenGL renderer :slightly_smiling_face:

**Comment by Henrique-Henrique** [comment]
I imagined, thanks! 😁

**Comment by aragubas** [comment]
still waiting for the shadows to be implemented

**Comment by Calinou** [comment]
@aragubas Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.

**Comment by Zireael07** [comment]
Yikes. When I saw all the announcements of 4.0, I didn't expect it would skip right over what is pretty much a _crucial_ part of the 3D compatibility renderer!

**Comment by clayjohn** [comment]
Bumping to 4.2 as I need to do more performance analysis to ensure that the current implementation is indeed optimal from a performance perspective. :( I just ran out of time for 4.1

**Comment by joined72** [comment]
Any news about performance improvements?

**Comment by joined72** [comment]
> Bumping to 4.2 as I need to do more performance analysis to ensure that the current implementation is indeed optimal from a performance perspective. :( I just ran out of time for 4.1

Any news about performance improvements?

**Comment by Calinou** [comment]
> Any news about performance improvements?

OpenGL shadows have been merged in 4.2, following [this comment](https://github.com/godotengine/godot/pull/77496#issuecomment-1678030394) which addresses performance issues that were in the initial (unmerged) implementation.
