### ISSUE TITLE
gdscript: 3-to-4 JSON.print wasn't replaced with JSON.stringify

### ISSUE THREAD

**Issue by xarses** [godotengine/godot#66606]
### Godot version

4.0-beta1

### System information

Linux, Pop_OS

### Issue description

When converting a project 3-to-4 doesn't convert `JSON.print()` calls to (what appears to be a drop-in replacement) `JSON.stringify`

### Steps to reproduce

Convert a project with gdscript using `JSON.print`

```
	if hello.op != 0:
		logger.error("Unexpected op code from obs-websocket: %s\nAborting connection" % JSON.print(
			hello.get_as_json(), "\t"))
		return
```

re: https://github.com/you-win/obs-websocket-gd/blob/master/addons/obs-websocket-gd/obs_websocket.gd#L944-L947

### Minimal reproduction project

https://github.com/you-win/obs-websocket-gd/

**Comment by Calinou** [comment]
This is likely because the converter is unable to do so in a way that doesn't cause false positives, as it works with regexes.

**Comment by xarses** [comment]
For my understanding, your saying I shouldn't expect it replace `JSON.print` with `JSON.stringify` ? It seems to be straight forward replacement or are you saying there is a similar replacement occurring that is taking precedence?

Is there a guide somewhere of what I conversions I should expect it to make? I'd like to help identify gaps here, but I'd also like to know where the system stops so I don't spam issues with things that aren't expected to be solved.
