### ISSUE TITLE
Shader hint source_color does not transmit the correct default value to the Inspector

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#66619]
### Godot version

4.0 Beta 2

### System information

Win 10, Nvidea 765M

### Issue description

![image](https://user-images.githubusercontent.com/47016402/193135388-4008bc1b-e188-4e04-b0ff-90ae78c57a0c.png)

This is not just a visual issue, the Inspector value is indeed `vec4(0.0, 0.0, 0.0, 1.0)` aka the color Black as can be seen when mouse over.

Possibly related: https://github.com/godotengine/godot/pull/61554

### Steps to reproduce

1. Add a Sprite,
2. add a shader
3. add this line: `uniform vec4 solid_color: source_color = vec4(1.0,0.0,0.0,1.0);`

### Minimal reproduction project
This is faster tested without having to download and extract a MRP

_Bugsquad edit: removed unrelated rant_

**Comment by Calinou** [comment]
> PS: I really absolutely hate the name change of the color hint to "source_color". What was the point of this? The only thing it does is to make it [less consistent with other hints](https://docs.godotengine.org/en/latest/tutorials/shaders/shader_reference/shading_language.html#uniforms) and therefore harder to remember and less intuitive. :(

See https://github.com/godotengine/godot-proposals/issues/2323.

**Comment by opponent019** [comment]
This seems to still be an issue with Godot 4.6.3 on Linux

<img width="2873" height="584" alt="Image" src="https://github.com/user-attachments/assets/391f3a07-5904-457e-9f3a-16dcdaaa678c" />


Edit: Apparently there are hidden color values that one can see by pressing the Hexadecimal button in the color picker which changes those values to what one can input as default in the shader to replicate the color one wants. This is quite confusing 

<img width="2873" height="584" alt="Image" src="https://github.com/user-attachments/assets/c1314874-cb66-4842-9633-b4ca7aaef3c8" />
