### ISSUE TITLE
Vulkan: LightmapGI not visible in 4.0.beta2

### ISSUE THREAD

**Issue by Syntaxxor** [godotengine/godot#66618]
### Godot version

4.0.beta2

### System information

Windows 10, Vulkan renderer, Nvidia RTX 3060 ti

### Issue description

When I use a baked LightmapGI node, it seems to just render purely black lightmap textures.
![image](https://user-images.githubusercontent.com/25652538/193129679-eade7117-5016-4966-adf2-08a02d118cac.png)
However, the lightmap texture appears to be baking correctly.
![lightmap_test_scene](https://user-images.githubusercontent.com/25652538/193130049-09e0ec09-29bf-4bb0-953f-a06f9fb50974.png)
This example is with an imported .glb blender with what appear to be properly generated lightmap UVs, too.

### Steps to reproduce

- Import a model.
- Set it to import with lightmap UVs and reimport.
- Place it in a scene with a `DirectionalLight3D` and a `LightmapGI`.
- Bake the lightmaps.

### Minimal reproduction project

[lightmap_bug.zip](https://github.com/godotengine/godot/files/9678734/lightmap_bug.zip)

**Comment by akien-mga** [comment]
According to https://github.com/godotengine/godot/issues/66629 this would be a regression since 4.0 beta1.

**Comment by akien-mga** [comment]
I can confirm the bug with the MRP. For me it seems like even the DirectionalLight3D is broken, everything is pitch black.

4.0 beta 1:
![image](https://user-images.githubusercontent.com/4701338/193226633-cf5e55b4-656c-4069-968f-67e2d8529b67.png)

4.0 beta 2:
![image](https://user-images.githubusercontent.com/4701338/193226770-e900b08f-a707-434a-8784-83a09a07a13b.png)

**Comment by Syntaxxor** [comment]
If the DirectionalLight3D is set to static, then yeah, that makes sense. Though when I've tried it in dynamic, just the shadows are pure black.

**Comment by clayjohn** [comment]
In my testing the scene is sometimes black but sometimes shows the light dynamically as if the lightmap just isn't being applied at all. 

Superficially, https://github.com/godotengine/godot/pull/65807 seems like it may be the cause. But the fact that the dynamic light is still visible makes me think that it is actually a problem deeper in the rendering code.

**Comment by clayjohn** [comment]
Git bisected to https://github.com/godotengine/godot/commit/b668268772005a3cc43c6c02307c2e7f5bb97087

Fix incoming
