### ISSUE TITLE
UX: dragging outside of floating color picker causes it to close too easily

### ISSUE THREAD

**Issue by snoopdouglas** [godotengine/godot#66622]
### Godot version

4.0-beta2

### System information

Fedora 36

### Issue description

![image](https://user-images.githubusercontent.com/4892574/193141946-49c62a7b-08c2-4e68-8258-6502a00a2eba.png)

If I click and drag the lightness handle past the top of the color picker popup, it disappears. It feels more natural for it to stay open until I click on something else.

### Steps to reproduce

Open a color picker, click somewhere, drag outside of its bounds, notice it disappearing.

**Comment by Sauermann** [comment]
This problem only happens, when Single Window Mode is off.

**Comment by TchnlgPsnt** [comment]
I can't reproduce this on windows 10, might be a linux issue

**Comment by opl-** [comment]
Seems the color picker is closing due to a `NOTIFICATION_WM_CLOSE_REQUEST`, which is triggered by `WINDOW_EVENT_CLOSE_REQUEST` sent from the display server. It very well might be Linux specific.
