### ISSUE TITLE
Method-override gutter icon don't always show relevant docs when clicked

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#66630]
### Godot version

4.0 beta 2

### System information

linux

### Issue description

https://user-images.githubusercontent.com/71937306/193157661-4d415700-4d9d-4cd5-b80a-cdaf53607e7c.mp4

As you can see this depends on the type of the script (whose docs are displayed).

### Steps to reproduce

```gdscript
extends Node2D

# _ready is inherited from `Node`.
# clicking the icon will take you to the `Node2D` docs.
func _ready():
    pass
```

**Comment by Calinou** [comment]
The gutter icon was added in https://github.com/godotengine/godot/pull/65535.

cc @RedMser
