### ISSUE TITLE
Vulkan: VoxelGI not visible in 4.0.beta2

### ISSUE THREAD

**Issue by Syntaxxor** [godotengine/godot#66639]
### Godot version

4.0.beta2

### System information

Windows 10, Vulkan Forward+ Renderer, Nvidia RTX 3060 ti

### Issue description

Potentially related to https://github.com/godotengine/godot/issues/66618.
VoxelGI nodes don't appear to have any visual effect whatsoever. This is a scene with a visible, baked VoxelGI node:
![image](https://user-images.githubusercontent.com/25652538/193176416-6671e69b-57f0-461f-b88c-5b923ad51774.png)
However, in the editor, you can see that the voxels are in fact being built (albeit with some... very strange visual errors.)
![image](https://user-images.githubusercontent.com/25652538/193176554-e129eeb5-0789-4751-8279-814abe07e639.png)

### Steps to reproduce

- Add a VoxelGI node to a scene
- Bake the VoxelGI

### Minimal reproduction project

[voxel_gi_bug.zip](https://github.com/godotengine/godot/files/9680160/voxel_gi_bug.zip)

**Comment by clayjohn** [comment]
Git bisect points to b668268772005a3cc43c6c02307c2e7f5bb97087

**Comment by viktor-ferenczi** [comment]
VoxelGI does not seem to work with Godot 4 master `3a59c833`.

MRP: [VoxelGITest.zip](https://github.com/godotengine/godot/files/9795407/VoxelGITest.zip)

Screenshot:
![image](https://user-images.githubusercontent.com/1848514/196051918-3b66605f-dc90-4e72-b87d-25b9a1ebbe24.png)

There is a directional light. The VoxelGI was baked. All meshes set to Static GI mode, which includes VoxelGI. The red ball is emissive with energy of 10, it must be glowing and contribute to lighting.

Am I doing something wrong here? (Documentation is currently incomplete.)
