### ISSUE TITLE
Export texture conversion done in-place so the editor is affected

### ISSUE THREAD

**Issue by RandomShaper** [godotengine/godot#6663]
**Operating system or device - Godot version:**
Win 10 x64, last master

**Issue description** (what happened, and what was expected):
When exporting the game to `.zip`, `.pck` or `.exe` for Windows (at least), textures set to be compressed for VRAM are converted in-place. For instance, after export an uncompressed texture will be reported in the resource preview as being BC3-compressed. Loading the project again makes the original resource, with its original storage settings, to be reloaded,
I have not been able to reproduce the problem on Android export. Other platforms untested.

**Steps to reproduce:**
1. Create a project with an empty scene.
2. Add some image.
3. Set it to be compressed for VRAM on export.
4. Open the image in the resource previewer and witness its storage/compression settings.
5. Export the project for Windows.
6. Hit back and then forward on the resource preview to refresh the texture information. Now it will tell it's compressed as BC3 (or some other VRAM format).
Bonus:
7. Reload the scene or if needed quit to the project list and reopen it and check it again. Now it's back to normal.

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by RandomShaper** [comment]
No, neither in 3.0. Feel free to close it.

**Comment by RandomShaper** [comment]
By the way, it's been a long time since this.

I wasn't even tagging my issue reports.
