### ISSUE TITLE
Vulkan: strange SSAO artifacts on flat surfaces

### ISSUE THREAD

**Issue by atirut-w** [godotengine/godot#66643]
### Godot version

v4.0.beta2.official [f8745f2f7]

### System information

Arch Linux, Vulkan Clustered, Nvidia 1660(Nvidia open driver 515.76-2)

### Issue description

I initially thought this has something to do with the SSAO half size issues(https://github.com/godotengine/godot/issues/59471, https://github.com/godotengine/godot/issues/51564#issuecomment-897700747), but I found out that disabling half size only made the issue more subtle.

Personally, I think these issues have the same cause issue and the disabling of half size fixing them is due to how subtle the artifacts become after disabling half size.

https://user-images.githubusercontent.com/25323231/193185181-7dd5dd28-9de4-445e-a975-31106f1552e6.mp4

### Steps to reproduce

1. Set up a scene with a flat surface(cube, plane, etc.)
2. Enable SSAO

### Minimal reproduction project

[SSAO Issue.zip](https://github.com/godotengine/godot/files/9680537/SSAO.Issue.zip)

**Comment by Flavelius** [comment]
This is still an issue (for me atleast) in 4.0 beta15. As a kind-of workaround the negative effect can be toned down by increasing the ao radius.

**Comment by atirut-w** [comment]
@clayjohn does this issue getting moved to 4.x imply that 4.0 will be released with SSAO broken like this?

**Comment by clayjohn** [comment]
> @clayjohn does this issue getting moved to 4.x imply that 4.0 will be released with SSAO broken like this?

No. 4.x includes 4.0. if someone fixes this before we release 4.0 then it will be in the 4.0 release

**Comment by atirut-w** [comment]
Why move it then?

**Comment by Flavelius** [comment]
> Why move it then?

Because it's probably not a showstopper for the 4.0 release. It can be fixed and as said will be included if it is, but does not have to be for 4.0 to be released.

**Comment by BastiaanOlij** [comment]
This could be fixed by #72838, no guarantees though as I haven't seen this behavior before.

**Comment by mrjustaguy** [comment]
This wasn't fixed by it, this seems to have something to do with the depth, as it appears and disappears as you change your distance from the surface.
