### ISSUE TITLE
ResourceLoader not loading subresource when using properties

### ISSUE THREAD

**Issue by fravan** [godotengine/godot#66649]
### Godot version

4.0 beta 2

### System information

ubuntu

### Issue description

Hi everyone,

I am using a lot of custom Resources for a project of mine.

I noticed that sub resources were not getting loaded properly when using the new property syntax in Godot.
If I change this code :
```gdscript
@export var events: Array[Event]:
	get: return _events
	set(value):
		_events = value
		emit_changed()
```

by this one, then it works properly
```gdscript
@export var events: Array[Event]
```

I attached a zip file to demonstrate the bug.

There are no errors as-is, just that the loader returns an empty array while the saved file do have the list.

### Steps to reproduce

- Launch the attached project
- click "create resource" so a resource is saved to disk
- click "load resource" and notice the event count is set to 0 while the list has 2 in the file

Optional :
- Remove the property and use a simple var instead
- Notice the bug flies away

### Minimal reproduction project

[resource-loader-bug.zip](https://github.com/godotengine/godot/files/9681773/resource-loader-bug.zip)

**Comment by rretureau** [comment]
Same thing happens with custom Resources in an exported Array. Nothing is loaded and the Array is ultimately empty.
