### ISSUE TITLE
`Image.save_jpg()` does not write any file

### ISSUE THREAD

**Issue by dominiks** [godotengine/godot#66650]
### Godot version

v4.0.beta2.official.f8745f2f7

### System information

Windows 10

### Issue description

Calling `Image.save_png(...)` writes the image data to a png file as expected, but `Image.save_jpg(...)` does not result in any file. It returns error code 0 to indicate that no errors occured.

### Steps to reproduce

Run the example project and check the "user://" directory. There is an `icon.png` file but no `icon.jpg`.

Alternatively run this code in a fresh project:

    var icon_path := "res://icon.svg"
    
    var image = Image.load_from_file(icon_path)

    var error = image.save_jpg("user://icon.jpg")
    print("Error: %s" % error)
    print(FileAccess.file_exists("user://icon.jpg"))
    error = image.save_png("user://icon.png")
    print("Error: %s" % error)
    print(FileAccess.file_exists("user://icon.png"))

Output:

    Error: 0
    false
    Error: 0
    true

### Minimal reproduction project

[imageTest.zip](https://github.com/godotengine/godot/files/9682231/imageTest.zip)

**Comment by Robert-W-Ward** [comment]
Can confirm is reproduceable on windows 11 using the provided project and beta version specified and a custom build on commit 166df0896c.

**Comment by Calinou** [comment]
JPEG saving was implemented by https://github.com/godotengine/godot/pull/62122, but @Faless also has experience implementing the same function.
