### ISSUE TITLE
Error when not running: Could not resolve class "BattleCore", because of a parser error.

### ISSUE THREAD

**Issue by FREEDARK0** [godotengine/godot#66652]
### Godot version

4.0 beta2

### System information

Windows10, Intel Core i7-6700

### Issue description

E 0:00:01:0576   is_type_compatible: Parser bug (please report): Trying to check compatibility of unset target type
  <C++ error>       Condition "!p_target.is_set()" is true. Returning: true
  <C++ source file>      modules/gdscript/gdscript_analyzer.cpp:4075 @ is_type_compatible()

### Steps to reproduce

After one run of the scene, there was no problem before

**Comment by FREEDARK0** [comment]
After that, all custom classes are error like this:
Parse Error: Could not resolve class "BattleCore", because of a parser error.

**Comment by akien-mga** [comment]
What scene? Please provide more information so that contributors can reproduce the problem and fix it.

**Comment by FREEDARK0** [comment]
> 什么场景？请提供更多信息，以便参与者可以重现问题并修复它。

Sorry for my level of English and programming, what can I provide ? 
I remember the run before the error occurred, the program did not respond, I ended the task, and then this happened.
Reopening the editor afterwards also does not resolve it.

**Comment by Zireael07** [comment]
Can you upload the project here so that contributors can look at the problem?

**Comment by FREEDARK0** [comment]
> Can you upload the project here so that contributors can look at the problem?

I'm sorry that my project has some confidential content. 
However, I think the problem comes from the use of static types, and I just tried to remove the (: typename) items after individual variables and function arguments,and then the project works fine
Maybe I shouldn't mix dynamic and static.
I'll try to do another small example project.

**Comment by dalexeev** [comment]
Please check if the bug is still reproducible in RC 1. If so, please provide an MRP.

**Comment by FREEDARK0** [comment]
> Please check if the bug is still reproducible in RC 1. If so, please provide an MRP.

I'm sorry I haven't encountered this problem since then, but I think a bug in one of my custom classes might be causing it

**Comment by akien-mga** [comment]
Closing then. Parser errors can indeed happen if some classes in your project have errors, and prevent the project from compiling.
