### ISSUE TITLE
Thread changes, documented or undocumented between Beta 1 and Beta 2

### ISSUE THREAD

**Issue by 1xch** [godotengine/godot#66669]
### Godot version

Godot_v4.0-beta2_linux.x86_64

### System information

Linux Ubuntu 20.04

### Issue description

Any threading code I've fought with since 4.0 Alpha versions that has been working just shit itself. So as I try to work through that instead of making any other progress, I want to ask about what changes might be conflicting that I can't locate or understand right now.
I accept that my own code may in fact have been wrong, but it has been working up until I started using Beta2.

Bottom line after working on it: I don't know -- something changed with Thread outside of the scope of my project between beta1 and beta2, perhaps my code was already wrong and something finally gave me an indication, but before my threaded code was working. I've had to regress to beta1 where stuff still works and I'll need to go over again.  

### Steps to reproduce

```
func thr_func():
	while(true):
		OS.delay_usec(interval)
		step()
		if exit:
			is_done.emit()
			break
```
As an example, above never reaches exit even when exit is set....thr_func just disappears (that I can tell) without signaling or breaking. 

### Minimal reproduction project

I wish I could, I have my own private project built around Godot that is extensive to me as this repo is to Godot itself. I don't have a simple project to reproduce this yet.

**Comment by Calinou** [comment]
If you can [compile the engine from source](https://docs.godotengine.org/en/stable/development/compiling/index.html), you could look into [bisecting the regression](https://docs.godotengine.org/en/stable/community/contributing/bisecting_regressions.html) to greatly speed up troubleshooting.

**Comment by 1xch** [comment]
Thanks...I'm not sure its Thread now, something changed for me but I'm sure its likely my problem now.
