### ISSUE TITLE
GradientTexture2D preview behaves weirdly

### ISSUE THREAD

**Issue by Swarkin** [godotengine/godot#66661]
### Godot version

4.0.beta2

### System information

Windows 10

### Issue description

The preview of a GradientTexture2D behaves weirdly when the width and height values are really small:
https://streamable.com/vt8med

### Steps to reproduce

Create a GradientTexture2D and try to set the width and height of it to small numbers

**Comment by Mickeon** [comment]
What should happen at very small sizes? Because, displaying them as the strips that they are would render them difficult to even see properly. Should the gradient stretch, perhaps?

**Comment by Swarkin** [comment]
Good question... I'm not sure, but maybe it could stretch at some point, and show an indicator line representing the actual size of the texture, like this:

![image](https://user-images.githubusercontent.com/102416174/193406075-921715bf-026d-47fd-bcdb-e6ac7ae09810.png)

**Comment by MewPurPur** [comment]
Looking into it, and nah I can't do an indicator, because gradients won't necessarily be so simple as to preserve their nature when stretching.
