### ISSUE TITLE
Emulate mouse from touch and Emulate touch from mouse not working

### ISSUE THREAD

**Issue by goredhub** [godotengine/godot#66667]
### Godot version

4.0.beta2.official.f8745f2f7

### System information

Windows 10, Mobile, Intel - Intel(R) HD Graphics 620 (30.0.101.1340)

### Issue description

Testing how application will look like on touchscreen device with emulate touch from mouse and emulate mouse from touch works well on Godot 3.x but not working on Godot 4.x with the same settings.

![editor_screenshot_2022-09-30T151317](https://user-images.githubusercontent.com/114751245/193293222-90fdff60-33d5-423b-b36c-c07f5c8793bd.png)
![godot_emulate_touch_from_mouse](https://user-images.githubusercontent.com/114751245/193293237-e913dce6-7b0f-4da7-80c3-c7d0c30fbf7a.png)

### Steps to reproduce

none

### Minimal reproduction project

[Godot 4.0.2.zip](https://github.com/godotengine/godot/files/9685358/Godot.4.0.2.zip)

**Comment by finecco** [comment]
this issue seems to continue in rc2

**Comment by goredhub** [comment]
It has been rectified since Godot 4 Beta 3

**Comment by akien-mga** [comment]
Seems like @finecco still experiences something similar.
@finecco Could you open a new with a minimal reproduction project?

**Comment by finecco** [comment]
[touch_emulate.zip](https://github.com/godotengine/godot/files/10757002/touch_emulate.zip)

hello again, in the project attached, touch screen node does not fire for me with touch from mouse emulation on, Macos Ventura M1. 

on android deploy the node is working.

tbh not sure the if it is really related to this pr.
