### ISSUE TITLE
XDG Base Directory specification should be ignored on windows builds

### ISSUE THREAD

**Issue by losamyn** [godotengine/godot#66671]
### Godot version

master

### System information

Linux, running a windows build through proton

### Issue description

I have run into a bug while playing a game (Brotato on Steam), where the game was unsuccesfully trying to read/store its savefile and logs under my `XDG_CONFIG_HOME` path.

I have the environment variable set in my `~/.zprofile`, resulting in the game trying to make a folder on this path, which is not a valid path within the proton prefix.

### Steps to reproduce

- Have `XDG_CONFIG_HOME` set (I have mine set to the default `$HOME/.config`)
- Run the game

**Comment by Calinou** [comment]
I wasn't aware following the XDG specification could cause issues on Windows. But yes, for games that don't have native Linux ports, this can be a problem.

**Comment by timoleistner** [comment]
I had the same problem.
Users on [ProtonDB](https://www.protondb.com/app/1942280) recommend following launch options:
`unset XDG_CONFIG_HOME ; unset XDG_CONFIG_HOME ; %command%`
This works for me.

**Comment by sonic2kk** [comment]
> for games that don't have native Linux ports, this can be a problem.

On Steam Deck, even if a game has a native Linux port, Valve may choose to have a game run with Proton instead of the Steam Linux Runtime. So there is a chance this could have broader reaching implications for games on Steam that have been vetted by Valve for Steam Deck.
