### ISSUE TITLE
Collision not working with Animation Player and AnimatableBody3D.

### ISSUE THREAD

**Issue by fbsr** [godotengine/godot#66676]
### Godot version

v4.0.beta1.official.20d667284

### System information

Windows 11, Vulkan, NVidia Gtx 1060 6GB

### Issue description

When moving an object AnimatableBody3D against another physical object like CharacterBody3D the collision does not occur, the object overtakes the other, which is not expected according to [documentation](https://docs.godotengine.org/en/latest/classes/class_animatablebody3d.html#class-animatablebody3d)

### Steps to reproduce

Move a **AnimatableBody3D**,  with the property **sync_to_pyshics** enabled, using a **AnimationPlayer**, with the property **playback_process_mode** to **physics**, against another object pyshics 3d.
![image](https://user-images.githubusercontent.com/19686748/193338071-6efac43f-352e-432c-b5bf-4adc1c9820c2.png)

### Minimal reproduction project

[animatable_body_3d_problem.zip](https://github.com/godotengine/godot/files/9686986/animatable_body_3d_problem.zip)

**Comment by Calinou** [comment]
You're setting the `position` every frame using an AnimationPlayer node. This is expected to ignore collision checks. Set the linear velocity instead.

**Comment by fbsr** [comment]
I tried too and it didn't work.
In documentation:
"When the body is moved manually, either from code or from an [**AnimationPlayer**](https://docs.godotengine.org/en/latest/classes/class_animationplayer.html#class-animationplayer) (with [AnimationPlayer.playback_process_mode](https://docs.godotengine.org/en/latest/classes/class_animationplayer.html#class-animationplayer-property-playback-process-mode) set to physics), the physics will automatically compute an estimate of their linear and angular velocity. This makes them very useful for moving platforms or other AnimationPlayer-controlled objects (like a door, a bridge that opens, etc)."

I was just trying to use it for a door. if a  AnimatableBody3D doesn't work with AnimationPlayer what is it for?

![image](https://user-images.githubusercontent.com/19686748/193379521-f9162560-821b-48a2-89a4-1d962158ef06.png)
