### ISSUE TITLE
Cannot type @ in the editor on macOS

### ISSUE THREAD

**Issue by AarreEntertainment** [godotengine/godot#66678]
### Godot version

4.0.dev

### System information

Macbook Air 2021

### Issue description

I am unable to type @ to the editor because command + 2 is bound to switching tabs (2d, 3d, script...)

### Steps to reproduce

Try to type @ on a mac

**Comment by bruvzg** [comment]
You can remove or change the binding in the `Editor Settings` ( <kbd>⌘ + ,</kbd> ) → `Shortcuts`.

**Comment by Calinou** [comment]
> 4.0.dev

Which exact version are you using (official alpha/beta or self-compiled build)? Please include the commit hash.

**Comment by lostminds** [comment]
I think @AarreEntertainment may have mistyped? I ran into the same issue as on my Swedish keyboard @ is Alt-2, which is the default shortcut for switching to an editor tab. You can get around it by just turning the shortcut off, but it's probably not a good default. On macOS I'd say non-command shortcuts are should usually be avoided. 

There's a more general discussion on this in #63888 about how shortcut key combinations should or should not be interpreted while in an active text field editor.
