### ISSUE TITLE
v-sync not enabled not limiting fps

### ISSUE THREAD

**Issue by dmaz** [godotengine/godot#66670]
### Godot version

v4.0.beta.custom_build [61c0cb712] and Godot Engine v4.0.beta2.official.f8745f2f7

### System information

windows 10, nvidia 2080 516.94

### Issue description

I would expect that setting v-sync to Enabled should limit my fps even when Force FPS is 0 and running in release_debug.

changing v-sync doesn't seem to do anything in any window mode for me.  setting Force FPS does limit the fps correctly if set to anything but 0.  if set to 0 though the engine will always run at full fps no matter what I change v-sync to.  

tested beta 2 on mac and it didn't show this issue.

I think this hasn't worked on my windows machine for awhile now

### Steps to reproduce

turn on Debugger/Monitors/FPS
run any 3d or 2d scene 
between runs change Project Settings/Display/Window/V-Sync Mode.

**Comment by Calinou** [comment]
Is V-Sync forcibly disabled in the NVIDIA Control Panel? Do you have variable refresh rate (G-Sync) enabled?

**Comment by dmaz** [comment]
yeah checking 3.5 was the first thing I did and it had no issue switching back and forth between v-sync settings.  so I didn't even think to check the driver

but yeah, my bad, the video driver did have it set to "off".  G-Sync was set to on for full screen only.  

switching the driver to "use application" does make work correctly in 4.0.  so maybe opengl doesn't even respect the global setting in the control panel?  I don't remember setting it to off and I know other games do work correctly when changing it

**Comment by Calinou** [comment]
> so maybe opengl doesn't even respect the global setting in the control panel?

I wouldn't be surprised – NVIDIA control panel's options frequently only apply to certain graphics APIs (typically Direct3D 9/10/11).
