### ISSUE TITLE
Failed to create Windows OS window

### ISSUE THREAD

**Issue by Maclay74** [godotengine/godot#66677]
### Godot version

v4.0.beta2.mono.official [f8745f2f7]

### System information

Windows 11 Build 25206, Vulkan

### Issue description

When I start the editor, if I open any window (project settings, editor settings, etc) I get this message in console and UI gets completely blocked. Therefore, I have to kill it via Task Manager.
```
Failed to create Windows OS window.
Failed to create sub window.
scene/main/window.cpp:247 - Condition "window_id == DisplayServer::INVALID_WINDOW_ID" is true.
platform/windows/display_server_windows.cpp:858 - Condition "!windows.has(p_window)" is true. Returning: -1
platform/windows/display_server_windows.cpp:858 - Condition "!windows.has(p_window)" is true. Returning: -1
```
It's a matter of seconds before this happening, if I'm lucky I can enable in editor settings `Single Window Mode` and then it works fine.

I think it might be related with my Windows version. 

### Steps to reproduce

1. Open Godot
2. Open any window
3. Wait for a while, change something

**Comment by Calinou** [comment]
> I think it might be related with my Windows version.

For reference, [build 25206 is an Insider preview build](https://blogs.windows.com/windows-insider/2022/09/21/announcing-windows-11-insider-preview-build-25206/).

**Comment by Maclay74** [comment]
It's GeForce 3080Ti, the latest driver version (517.48)
![image](https://user-images.githubusercontent.com/5504685/193358823-c685708b-79ab-454e-a138-eef281ceea81.png)

Using a regular PC.

**Comment by Maclay74** [comment]
Today I received 25211 update and it seems to be the solution.
25206 is just corrupted it some way and it's fixed now.
