### ISSUE TITLE
StringName and NodePath are not highlighted when preceded by `self`

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#66682]
### Godot version

4.0 e69b708

### System information

Windows 10 x64

### Issue description

![godot_pYPZ6uD4yF](https://user-images.githubusercontent.com/2223172/193365571-3b24a3af-82bb-49ca-a284-0a2d14de3b66.gif)
Magic.

### Steps to reproduce

Just see above.

**Comment by MewPurPur** [comment]
On it.
