### ISSUE TITLE
AnimationPlayer node cannot call functions defined in a singleton

### ISSUE THREAD

**Issue by hetdegon** [godotengine/godot#6668]
**Operating system or device - Godot version:**
Ubuntu Linux 16.04 64b, Godot version f30602c67a86bce393c5e67551755e0a8b3f0dd4

**Issue description** (what happened, and what was expected):
Apparently it's not possible to call functions defined in a singleton from a call func track in an animation.

**Steps to reproduce:**
Add a call to a singleton in a call func track, for example "main.testfunc" with no arguments or anything. 
Nothing happens. No error is returned either. Apparently even if the singleton is removed later, nothing happens either, instead of throwing an error, meaning if you type the singleton's name wrong, there will be no warning either.

**Comment by vnen** [comment]
I feel that there are two issues here (and a bit of misunderstanding the concept of singletons and call func tracks).

If you want to call a singleton function, you have the set the track with the path to the singleton (e.g. `/root/main`). In my test this didn't work though (it shows a crossed line meaning it's invalid), so that's issue number one. If that worked, then you could set the function in the keyframe to `testfunc`.

The other issue is that if you call an invalid/non-existent function, there's no warning about it. The debugger/console should show some warning when trying to that.

**Comment by hetdegon** [comment]
Uhm, I didn't think of that, but if it doesn't work, it's basically the same problem. Should I edit the issue to reflect that?

And about the other, it could make sense to make it a separate issue, indeed. If you think it's a better idea I'll focus this one on the singleton and open a new one for the no-warning-issue.

**Comment by Sslaxx** [comment]
Sounds related to #812.

**Comment by vnen** [comment]
I imagine the problem is related to the fact that singletons aren't available in-editor. The absence of warning is indeed the same as #881.

**Comment by hetdegon** [comment]
Yeah it'd be pretty convenient to have access to them. Given they have to be explicitly declared in project settings, it should be doable, shouldn't it? (unless there's another way to dynamically load singletons that I am not aware of).

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Sslaxx** [comment]
Related to the still-open #881 so probably still an issue, though could do with a test project.

**Comment by DualMatrix** [comment]
This now works in master using the /root/ method.

**Comment by akien-mga** [comment]
Thanks for checking!
