### ISSUE TITLE
Crash on start on Windows with only Vulkan 1.1 support, tries to call Vulkan 1.2 function anyway

### ISSUE THREAD

**Issue by mahdisml** [godotengine/godot#66685]
### Godot version

4.0 beta 2

### System information

Windows 11 , Vulkan , Nvidia 940m and IntelHD 620

### Issue description

it Crash on start , without any error in console
![image](https://user-images.githubusercontent.com/1758504/193368837-29b3cc02-6e5f-4fc3-9e07-ab2e2fff0cc2.png)

### Steps to reproduce

at first

**Comment by Zireael07** [comment]
That white window looks familiar - someone else already reported it but I can't find issue #

**Comment by Chaosus** [comment]
Yeah, like Godot doesn't correctly handle multiple videocards.

**Comment by nomaton** [comment]
I encountered (maybe) the same crash on Windows 10.

It seems caused by calling vkCreateRenderPass2KHR (which requires Vulkan API 1.2)
on my old machine where only Vulkan API 1.1 is available.

Updating driver may help, but I want Godot to cover old version if possible.

```
Godot Engine v4.0.beta.custom_build.f8745f2f7 - https://godotengine.org
Vulkan API 1.1.0 - Using Vulkan Device #0: NVIDIA - GeForce GTX 950M

================================================================
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.0.beta.custom_build (f8745f2f71c79972df66f17a3da75f6e328bc55d)
Dumping the backtrace. Please include this when reporting the bug on: https://github.com/godotengine/godot/issues
[0] ???
[1] ???
[2] VulkanContext::vkCreateRenderPass2KHR (D:\Projects\godot-4.0-beta2\drivers\vulkan\vulkan_context.cpp:61)
[3] VulkanContext::_update_swap_chain (D:\Projects\godot-4.0-beta2\drivers\vulkan\vulkan_context.cpp:1863)
[4] VulkanContext::_window_create (D:\Projects\godot-4.0-beta2\drivers\vulkan\vulkan_context.cpp:1478)
[5] VulkanContextWindows::window_create (D:\Projects\godot-4.0-beta2\platform\windows\vulkan_context_win.cpp:55)
[6] DisplayServerWindows::_create_window (D:\Projects\godot-4.0-beta2\platform\windows\display_server_windows.cpp:3556)
[7] DisplayServerWindows::DisplayServerWindows (D:\Projects\godot-4.0-beta2\platform\windows\display_server_windows.cpp:3873)
[8] DisplayServerWindows::create_func (D:\Projects\godot-4.0-beta2\platform\windows\display_server_windows.cpp:3937)
[9] DisplayServer::create (D:\Projects\godot-4.0-beta2\servers\display_server.cpp:871)
[10] Main::setup2 (D:\Projects\godot-4.0-beta2\main\main.cpp:1960)
[11] Main::setup (D:\Projects\godot-4.0-beta2\main\main.cpp:1845)
[12] widechar_main (D:\Projects\godot-4.0-beta2\platform\windows\godot_windows.cpp:164)
[13] _main (D:\Projects\godot-4.0-beta2\platform\windows\godot_windows.cpp:203)
[14] main (D:\Projects\godot-4.0-beta2\platform\windows\godot_windows.cpp:217)
[15] WinMain (D:\Projects\godot-4.0-beta2\platform\windows\godot_windows.cpp:231)
[16] __scrt_common_main_seh (d:\a01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[17] BaseThreadInitThunk
-- END OF BACKTRACE --
================================================================
```

Thanks

**Comment by nomaton** [comment]
(follow-up)

In my environment, changing `vkGetInstanceProcAddr` to `vkGetDeviceProcAddr` reduced the crash to graceful error.

```
// drivers/vulkan/vulkan_context.cpp

VkResult VulkanContext::vkCreateRenderPass2KHR(VkDevice device, const VkRenderPassCreateInfo2 *pCreateInfo, const VkAllocationCallbacks *pAllocator, VkRenderPass *pRenderPass) {
	if (fpCreateRenderPass2KHR == nullptr) {
		//fpCreateRenderPass2KHR = (PFN_vkCreateRenderPass2KHR)vkGetInstanceProcAddr(inst, "vkCreateRenderPass2KHR");
		fpCreateRenderPass2KHR = (PFN_vkCreateRenderPass2KHR)vkGetDeviceProcAddr(device, "vkCreateRenderPass2KHR");
	}

	if (fpCreateRenderPass2KHR == nullptr) {
		return VK_ERROR_EXTENSION_NOT_PRESENT;
	} else {
		return (fpCreateRenderPass2KHR)(device, pCreateInfo, pAllocator, pRenderPass);
	}
}
```

messages (line numbers may differ):

```
Godot Engine v4.0.beta.custom_build.f8745f2f7 - https://godotengine.org
Vulkan API 1.1.0 - Using Vulkan Device #0: NVIDIA - GeForce GTX 950M
ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: VulkanContext::_update_swap_chain (drivers\vulkan\vulkan_context.cpp:1865) ERROR: Condition "err != OK" is true. Returning: ERR_CANT_CREATE
   at: VulkanContext::_window_create (drivers\vulkan\vulkan_context.cpp:1480)
...
```

Vulkan spec says (in the middle of [4.1. Command Function Pointers](https://registry.khronos.org/vulkan/specs/1.2/html/vkspec.html#initialization-functionpointers))

> In order to support systems with multiple Vulkan implementations, the function pointers returned by `vkGetInstanceProcAddr` **may** point to dispatch code that calls a different real implementation for different VkDevice objects or their child objects. The overhead of the internal dispatch for VkDevice objects can be avoided by obtaining device-specific function pointers for any commands that use a device or device-child object as their dispatchable object. Such function pointers **can** be obtained with the command:
>> PFN_vkVoidFunction vkGetDeviceProcAddr( ...

So testing the return of `vkGetInstanceProcAddr` is null would be insufficient to test the device functionality as it may be just a dispatch function (and calling it results in the crash.)

**Comment by akien-mga** [comment]
CC @godotengine/rendering

**Comment by clayjohn** [comment]
> (follow-up)
> 
> In my environment, changing `vkGetInstanceProcAddr` to `vkGetDeviceProcAddr` reduced the crash to graceful error.
> 
> ```
> // drivers/vulkan/vulkan_context.cpp
> 
> VkResult VulkanContext::vkCreateRenderPass2KHR(VkDevice device, const VkRenderPassCreateInfo2 *pCreateInfo, const VkAllocationCallbacks *pAllocator, VkRenderPass *pRenderPass) {
> 	if (fpCreateRenderPass2KHR == nullptr) {
> 		//fpCreateRenderPass2KHR = (PFN_vkCreateRenderPass2KHR)vkGetInstanceProcAddr(inst, "vkCreateRenderPass2KHR");
> 		fpCreateRenderPass2KHR = (PFN_vkCreateRenderPass2KHR)vkGetDeviceProcAddr(device, "vkCreateRenderPass2KHR");
> 	}
> 
> 	if (fpCreateRenderPass2KHR == nullptr) {
> 		return VK_ERROR_EXTENSION_NOT_PRESENT;
> 	} else {
> 		return (fpCreateRenderPass2KHR)(device, pCreateInfo, pAllocator, pRenderPass);
> 	}
> }
> ```
> 
> messages (line numbers may differ):
> 
> ```
> Godot Engine v4.0.beta.custom_build.f8745f2f7 - https://godotengine.org
> Vulkan API 1.1.0 - Using Vulkan Device #0: NVIDIA - GeForce GTX 950M
> ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
>    at: VulkanContext::_update_swap_chain (drivers\vulkan\vulkan_context.cpp:1865) ERROR: Condition "err != OK" is true. Returning: ERR_CANT_CREATE
>    at: VulkanContext::_window_create (drivers\vulkan\vulkan_context.cpp:1480)
> ...
> ```
> 
> Vulkan spec says (in the middle of [4.1. Command Function Pointers](https://registry.khronos.org/vulkan/specs/1.2/html/vkspec.html#initialization-functionpointers))
> 
> > In order to support systems with multiple Vulkan implementations, the function pointers returned by `vkGetInstanceProcAddr` **may** point to dispatch code that calls a different real implementation for different VkDevice objects or their child objects. The overhead of the internal dispatch for VkDevice objects can be avoided by obtaining device-specific function pointers for any commands that use a device or device-child object as their dispatchable object. Such function pointers **can** be obtained with the command:
> > > PFN_vkVoidFunction vkGetDeviceProcAddr( ...
> 
> So testing the return of `vkGetInstanceProcAddr` is null would be insufficient to test the device functionality as it may be just a dispatch function (and calling it results in the crash.)

Changing to use ``vkGetDeviceProcAddr`` seems like a good change to make in the meantime (and it seems its a necessary change to make this function behave as intended). But we do need to do better testing and validation of required extensions. As we shouldn't even be going down this codepath if the extension isn't support

cc @BastiaanOlij

**Comment by BastiaanOlij** [comment]
From my understanding, `vkCreateRenderPass2KHR` was part of the Vulkan 1.0 spec as a Khronos extension after Khronos decided to standardize all calls with `type` and `next` entries but I guess on really old Vulkan 1.0 drivers they may not have supported the extension. 

In Vulkan 1.2 the extension was made core and the function renamed to `vkCreateRenderPass2`.

Now the problem here may be that if what @nomaton says is true and we can't simply check for nullptr, that we're never getting the `vkCreateRenderPass2KHR` pointer.

Have we tried reproducing this issue while the Vulkan SDK is installed and running `--gpu-validation`? That should give much more detailed information if we're calling the wrong functions.

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/67146, which is also caused by a device not supporting the renderpass2 extension.

**Comment by mahdisml** [comment]
This problem has not been solved yet!
It's still in beta version 3!

**Comment by mahdisml** [comment]
@clayjohn @Calinou

**Comment by clayjohn** [comment]
@mahdisml Can you confirm that you are getting the same error message as above? 

And can you please confirm your device specs (Operating system, CPU, GPU, and GPU driver version)?

**Comment by mahdisml** [comment]
> @mahdisml Can you confirm that you are getting the same error message as above?
> 
> And can you please confirm your device specs (Operating system, CPU, GPU, and GPU driver version)?

i didn't debug godot , i just run godot and it Crash on start , Unlike the previous version i got error in console.
Windows 11 , Intel Core i5-6200U , Nvidia 940m (driver version : 388.57) (and IntelHD 620) 

![image](https://user-images.githubusercontent.com/1758504/196815763-cb5b49e8-f9c7-43ae-b2ca-f284252a8e31.png)

**Comment by clayjohn** [comment]
@mahdisml This is a different issue, can you please open a new bug report? The error code you are getting corresponds to the ``VK_ERROR_INVALID_SHADER_NV`` error
