### ISSUE TITLE
RichTextLabel menu popup wrong position on another screen

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#66691]
### Godot version

v4.0.beta2.official [f8745f2f7]

### System information

Windows 10, 64bit

### Issue description

LOOK:
https://user-images.githubusercontent.com/35988767/193394481-ea647666-7afd-4e39-831b-e6e18efd0a6c.mp4

### Steps to reproduce

NOTE: Need 2 screens.
Create a `RichTextLabel` and enable `Context Menu Enabled` and `Selection Enabled`.
Run separately to two screen and try popup menu.

### Minimal reproduction project

[RichTextLabelMenuTest.zip](https://github.com/godotengine/godot/files/9689642/RichTextLabelMenuTest.zip)

**Comment by KoBeWi** [comment]
Can't reproduce in RC5.
