### ISSUE TITLE
4.0 beta 2 introduces additional CharacterBody3D collision jitter

### ISSUE THREAD

**Issue by Ophiolith** [godotengine/godot#66704]
### Godot version

4.0 beta 2

### System information

Windows 10, Nvidia GTX 1070, Vulkan renderer, Ryzen 1600x

### Issue description

I am aware that there are multiple open issues regarding collision jitter in GodotPhysics, and I am sure what I am experiencing relates to these, however beta 2 specifically seems to introduce additional jitter, at least when a non-cuboid CollisionShape3D is colliding with a floor.

Opening my project in beta 1 results in (perceptibly) smooth motion, whereas in beta 2, there appears to be some kind of upward force acting erratically on the collision shape, causing it to 'judder' upwards for a single frame. Please see the below video for reference.

[jitter.webm](https://user-images.githubusercontent.com/24281932/193409192-0d3fafff-ff1b-4a5c-880e-d9a6a5baeb4d.webm)

A few additional notes:

- The jitter will manifest on an unaltered CharacterBody3D, but seems to be exacerbated by lerped movement
- It doesn't seem to be affected by the project's default gravity value, nor velocity
- Upon initially reverting to beta 1, it seemed as if the jitter carried over, however on subsequent runs I have not been able to reproduce this.

### Steps to reproduce

1. Create 3D project
2. Create 'floor' mesh with collision shape as child
3. Create CharacterBody3D with non-cuboid collision shape and Camera3D as children
5. Attach script to CharacterBody3D with default movement code
6. (optional) add code to CharacterBody3D script to lerp movement between max velocity and stop over delta

### Minimal reproduction project

[CollisionJitter_Repro.zip](https://github.com/godotengine/godot/files/9690324/CollisionJitter_Repro.zip)

**Comment by solitaryurt** [comment]
Can confirm I'm experiencing the same type of issue when I moved from beta 1 to beta 2.

**Comment by jk7c** [comment]
The size of the shape affects.

[jitter3.webm](https://user-images.githubusercontent.com/75779389/193443712-21d44c9d-29c6-48e7-9754-270408ad6664.webm)

**Comment by rburing** [comment]
Bisected to https://github.com/godotengine/godot/pull/64728.

The minimal reproduction project in the top post contains static bodies which are non-uniformly scaled, but the jitter regression can be reproduced on a static body with a 1:1:1 scale and a large thin box collision shape, as hinted by @jk7c.

I wonder why exactly this jitter occurs, since the floor is still consistently detected.

**Comment by Ophiolith** [comment]
I don't have any clue how Godot generates collisions internally, but I did notice upon further testing that jitter was most frequent / pronounced in both my project and the repro when my character was approaching the edges of the slope that intersects the floor. That could very well be a coincidence, but I realise I haven't actually tested on a completely unobstructed floor. I'll try to set up a new repro when I get time.

**Comment by mrezai** [comment]
It seems like these issues:
https://github.com/godotengine/godot/issues/49323
https://github.com/godotengine/godot/issues/58066

**Comment by jk7c** [comment]
> Bisected to #64728.
> 
> The minimal reproduction project in the top post contains static bodies which are non-uniformly scaled, but the jitter regression can be reproduced on a static body with a 1:1:1 scale and a large thin box collision shape, as hinted by @jk7c.
> 
> I wonder why exactly this jitter occurs, since the floor is still consistently detected.

Apparently the jitter disappears if you set the value of `floor_snap_length` to 0.

**Comment by Ophiolith** [comment]
> Apparently the jitter disappears if you set the value of `floor_snap_length` to 0.

Tested, confirmed same behaviour. Not an ideal workaround given this means a character can't properly walk / slide down slopes, but yeah, the `floor_snap_length` value definitely seems to affect it.

**Comment by jk7c** [comment]
There are also problems detecting the collision.
```
	var slideCollision
	for i in get_slide_collision_count():
		slideCollision = get_slide_collision(i)
	
	print(slideCollision)
```

**Comment by solitaryurt** [comment]
> There are also problems detecting the collision.

I've noticed the behavior of `is_on_wall()` has changed as well.

**Comment by fabriceci** [comment]
Could you try the above PR and confirm that the bug is fixed?

**Comment by TheBoctor** [comment]
> > There are also problems detecting the collision.
> 
> I've noticed the behavior of `is_on_wall()` has changed as well.

Ditto. Was using this passively in 4.0 beta 1 for things like wall sliding, without having to hold in the direction of the wall. Now, a character must constantly move into the wall for `is_on_wall()` to return true. Is the beta 2 behavior correct, or is this a regression? Apologies if this is a separate issue.

**Comment by fabriceci** [comment]
@TheBoctor the beta 2 behavior is the correct one  in fact, it is by correcting this behavior that this regression was introduced).

**Comment by Ophiolith** [comment]
> Could you try the above PR and confirm that the bug is fixed?

I'm still very new to anything code-related, so I'm afraid I don't currently know how to compile Godot from source, apologies. If anybody else is in a position to compile a build, I'd be happy to test though.

**Comment by solitaryurt** [comment]
> @TheBoctor the beta 2 behavior is the correct one in fact, it is by correcting this behavior that this regression was introduced).

When was that regression introduced? 

For me the `is_on_wall()` behavior was consistent from `3.x` to `4 beta 1`. Its now different in `4 beta 2`. Is there any way to toggle a flag to revert to the old behavior?

**Comment by Ophiolith** [comment]
> You should be able to test out the build from the CI pipeline here: https://github.com/godotengine/godot/actions/runs/3172501988

Thanks - I have tried this build, and jitter is still being induced in my main project, but no detectable jitter in the repro
