### ISSUE TITLE
MacOS: Unable to export - Failed to publish dotnet project

### ISSUE THREAD

**Issue by MaxFletcher** [godotengine/godot#66702]
### Godot version

4.0beta-2

### System information

MacOS 12.6, x86_64

### Issue description

I am unable to export C# based projects in Godot4.0 beta.
I am exporting using the macOS export template and selecting the .app format.

Exporting a project that only makes use of GDScript works just fine with the same steps, however as soon as a C# script is added it fails with the error message (via popup) "Failed to publish .NET project".

Interestingly the game can be played just fine by pressing cmd + b, or cmd + r and playing in the editor.

Looking in the MSBuild output window shows this error:

```
Running:  /usr/local/share/dotnet/dotnet publish /Users/maxfletcher/GodotProjects/Example/Example.sln -c ExportDebug -r osx-x86 --self-contained true -v normal "-l:GodotTools.BuildLogger.GodotBuildLogger,/Applications/Godot_mono 4.0-beta2.app/Contents/MacOS/../Resources/GodotSharp/Tools/GodotTools.BuildLogger.dll;/Users/maxfletcher/Library/Application Support/Godot/mono/build_logs/3d83d5d84e96b16a9281e565e9ef1c27_ExportDebug" -p:GodotTargetPlatform=macos -o /var/folders/76/njcgdlq537s30g3f27l4ljt00000gn/T/godot-publish-dotnet/12071-ExportDebug-osx-x86
MSBuild version 17.3.1+2badb37d1 for .NET
Build started 01/10/2022 12:39:59.
     1>Project "/Users/maxfletcher/GodotProjects/Example/Example.sln" on node 1 (Restore target(s)).
     1>ValidateSolutionConfiguration:
         Building solution configuration "ExportDebug|Any CPU".
       _GetAllRestoreProjectPathItems:
         Determining projects to restore...
     1>Project "/Users/maxfletcher/GodotProjects/Example/Example.sln" (1) is building "/Users/maxfletcher/GodotProjects/Example/Example.csproj" (2:4) on node 1 (_GenerateRestoreGraphProjectEntry target(s)).
     2>/usr/local/share/dotnet/sdk/6.0.401/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1083: The specified RuntimeIdentifier 'osx-x86' is not recognized. [/Users/maxfletcher/GodotProjects/Example/Example.csproj]
     2>Done Building Project "/Users/maxfletcher/GodotProjects/Example/Example.csproj" (_GenerateRestoreGraphProjectEntry target(s)) -- FAILED.
     1>Done Building Project "/Users/maxfletcher/GodotProjects/Example/Example.sln" (Restore target(s)) -- FAILED.

Build FAILED.

       "/Users/maxfletcher/GodotProjects/Example/Example.sln" (Restore target) (1) ->
       "/Users/maxfletcher/GodotProjects/Example/Example.csproj" (_GenerateRestoreGraphProjectEntry target) (2:4) ->
       (ProcessFrameworkReferences target) -> 
         /usr/local/share/dotnet/sdk/6.0.401/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1083: The specified RuntimeIdentifier 'osx-x86' is not recognized. [/Users/maxfletcher/GodotProjects/Example/Example.csproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.69
```

Its Interesting it mentions the platform osx-x86 is not recognised, shouldnt this be osx-x64? As far as i can tell the list of supported runtime identifiers for dotnet project does not include osx-x86 and i cant see it mentioned in the [runtime.json ](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.NETCore.Platforms/src/runtime.json) file in the dotnet repo. Also apple themselves dropped support for 32 bit apps years ago as far as I am aware.

### Steps to reproduce

- Create a new project using the mono/dotnet version of Godot4.0
- Create an empty scene
- Add a c# script to the root node of the scene
- Create an export profile for macOS using the default settings
- Select a location for the exported project
- Click export project and select the .app export option
- Export the project

### Minimal reproduction project

[Example.zip](https://github.com/godotengine/godot/files/9690204/Example.zip)

**Comment by akien-mga** [comment]
Probably caused by this? CC @godotengine/dotnet 

https://github.com/godotengine/godot/blob/9cd62741bb0e2f410b2fb861f66e2cf10fe0334d/modules/mono/editor/GodotTools/GodotTools/Export/ExportPlugin.cs#L114-L115

This likely wouldn't work for arm64 macOS, and might break if by any chance universal builds don't define `x86_64` + `arm64` but only `universal` (didn't check if that's the case).

**Comment by bruvzg** [comment]
Even with the correct `arch`, .net export for macOS is broken, it's placing files into a wrong place.

And since .net SDK are not universal, it will probably need to look for both `x86_64` and `arm64` SDK and lipo `dylibs` together (we have a built-in lipo implementation used for ad-hoc signing).

**Comment by bruvzg** [comment]
Seems like DLLs and JSON are a bit different for x86-64 and arm64 build as well. I'm not sure how important the differences are, but it's probably safer to export both into different folders and select it based on running executable arch instead of using lipo.
