### ISSUE TITLE
[4.0] "Bone2D - Bone Angle" display wrongly in polygons' uv and bone weight drawing always wrong

### ISSUE THREAD

**Issue by CheapMeow** [godotengine/godot#66708]
### Godot version

v4.0.beta4.official [e6751549c]

### System information

Ubuntu 22.04.1 LTS,GeForce RTX 2060 Mobile,TU106M,Vulkan

#### 1."Bone2D - Bone Angle" display wrongly

Property "Bone2D - Bone Angle" display wrongly in polygons' uv, but "Node2D - Transform - Rotation" display correctly.

The following two images shows that property "Bone2D - Bone Angle" display wrongly in polygons' uv

<img src="https://user-images.githubusercontent.com/88229072/193449168-859c3725-53c6-4f85-97c6-69126992707d.png" height = "400" align=center />

<img src="https://user-images.githubusercontent.com/88229072/193449279-dee8ea0a-9981-4e21-8f52-bd20b58fa929.png" height = "400" align=center />

The following two images shows that property "Node2D - Transform - Rotation" display correctly

<img src="https://user-images.githubusercontent.com/88229072/193449175-27685415-241a-41b2-a6c0-4e99ca8b0a7a.png" height = "400" align=center />

<img src="https://user-images.githubusercontent.com/88229072/193449321-d46f597a-6cfc-4ed6-96ac-3b23dee90075.png" height = "400" align=center />

#### 2.bone weight drawing always wrong

However, bone weight drawing always wrong.

The following two images shows that bone weight drawing always wrong

<img src="https://user-images.githubusercontent.com/88229072/193449469-b8d31123-458a-470a-b550-b85b19f8e0a6.png" height = "400" align=center />

In v3.5.1 everything is right

#### 1.Basic

1.Open test.tscn
2.Make sure the Polygon2D node assigned with the only Skeleton2D node
3.Every time modify Bone2D node's property, choose Skeleton2D node, click "Skeleton2D" button in top toolkit of 2D View, then click "OverWrite Rest Pose"
4.Choose Polyon2D node, click "uv" button in top toolkit of 2D View, then click "Bones" button in top toolkit of 2D UV Editor View, click "Sync Bones to Polygon", only need once

#### 2.To check property "Bone2D - Bone Angle" display wrongly in polygons' uv

1.Choose a Bone2D node, set property "Bone2D - Bone Angle" = any value, property "Node2D - Transform - Rotation" = 0
2.OverWrite Rest Pose
3.Enter 2D UV Editor View of Polyon2D node, enter "Bones" view, see the bones you modify angle, it will be wrong

#### 3.To check property "Node2D - Transform - Rotation" display correctly
1.Choose a Bone2D node, set property "Bone2D - Bone Angle" = 0, property "Node2D - Transform - Rotation" = any value
2.OverWrite Rest Pose
3.Enter 2D UV Editor View of Polyon2D node, enter "Bones" view, see the bones you modify angle, it will be right

#### 4.To check bone weight drawing always wrong

1.Choose a Bone2D node, set property "Bone2D - Bone Angle" = 0, property "Node2D - Transform - Rotation" = any value
2.OverWrite Rest Pose
3.Enter 2D UV Editor View of Polyon2D node, enter "Bones" view, click mouse and draw weight to uv island node, you will see the polygon 's displaying is flashing

It is reproducing record uploaded to youtube
[[Godot4.0] Bug of "Bone2D - Bone2d Angle" and bone weight drawing](https://youtu.be/Vc6WseltPig)

### Minimal reproduction project

[reproduction_v3.5.1.zip](https://github.com/godotengine/godot/files/9692212/reproduction_v3.5.1.zip)
[reproduction_v4.0_beta2.zip](https://github.com/godotengine/godot/files/9692213/reproduction_v4.0_beta2.zip)

**Comment by Hearsay-Law** [comment]
Skeleton2d and bone2d basically unusable with this bug unfortunately.

**Comment by Calinou** [comment]
@Hearsay-Law Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.

**Comment by CheapMeow** [comment]
Fixed by pull #68863

**Comment by maryisdead** [comment]
Is this supposed to be fixed in 4.2.1? I still see it happen there.

**Comment by akien-mga** [comment]
Please open a new issue, this was fixed in 4.0. So what you're experiencing might be a different bug, even if it has similar symptoms.
