### ISSUE TITLE
Editor enter in fullscreen when playing scene

### ISSUE THREAD

**Issue by marcosbitetti** [godotengine/godot#66701]
### Godot version

v4.0.beta.custom_build [e69b7083d]

### System information

POP OS 20.04 - nVidia GTX1650 - Vulkan

### Issue description

When I play any scene, it make editors editors enter in fullscreen mode, without my iteration!

It causes an uncomfortable break in workflow.

### Steps to reproduce

in any project (or new projects)
positioning  editor in part of screen
create any scene
play it

[edited]
The problem aways appears when SAVE any scene

**Comment by AntonioDell** [comment]
I have nearly the same specs and experience the issue quite regularly too.
POP OS 22.04 with GeForce GTX 1660 Super.
Maybe it has something to do with the distro?

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/66413 (fixed in latest `master` branch).
