### ISSUE TITLE
Window size bigger than project settings

### ISSUE THREAD

**Issue by MelimeliDev** [godotengine/godot#6671]
**Operating system or device - Godot version:**
Windows 10, Godot 2.1

**Issue description** (what happened, and what was expected):
Window size bigger than project settings' width and height
I tested this on other projects that I downloaded from github as well. Not just mine.
![error1](https://cloud.githubusercontent.com/assets/14923217/19014540/2aa9c0ec-8822-11e6-8a6e-9330b0ee0f5f.jpg)

**Comment by vnen** [comment]
Is this setting in your Windows machine greater than 100%?

![applicationframehost_2016-07-21_22-12-09](https://cloud.githubusercontent.com/assets/5599796/19015243/0d90779e-87d7-11e6-993f-b8f5c9a98bcd.png)

For the blurriness in your screenshot I imagine it is. I'm not sure if the window size should or not be scaled up when this setting is bigger, but it seems to be some Windows default.

**Comment by MelimeliDev** [comment]
That's right! I didn't even know that feature exist... Just bought a new laptop :)

I didn't suspect that because the OBS I used to record my game's video produced 800x600 window that's smaller than the game's enlarged window (seemingly unaffected by my OS settings)

Thanks a lot :)
