### ISSUE TITLE
Physical Lights in Workspace Camera Blown Out

### ISSUE THREAD

**Issue by scott-wilson** [godotengine/godot#66732]
### Godot version

v4.0.beta2.official [f8745f2f7]

### System information

Kubuntu 22.04 64 bit, NVIDIA RTX 2080 TI, Vukan

### Issue description

![image](https://user-images.githubusercontent.com/2775096/193432600-3cfc1242-7492-4f8c-9d1b-a3454d390353.png)

The viewport on the top is the "game camera" with auto exposure turned on. The viewport on the bottom is the "workspace camera" with no such exposure control. I'm experimenting with using physically based light values, so the sun/sky is set to roughly 100,000 lumens. This seems to work great when the camera's exposure can adjust, but fails when the workspace cannot adjust its exposure.

### Steps to reproduce

The scene below has a really simple scene where the lights are using physically based values, and the top viewport uses the camera in scene, but the viewport below doesn't. Loading the project should show the issue right away.

### Minimal reproduction project

[physical_light_bug.tar.gz](https://github.com/godotengine/godot/files/9691410/physical_light_bug.tar.gz)

**Comment by jtnicholl** [comment]
Your CameraAttributes is on the camera node, if you want auto exposure to effect the regular viewport too you should put it on the WorldEnvironment node instead.

**Comment by scott-wilson** [comment]
> Your CameraAttributes is on the camera node, if you want auto exposure to effect the regular viewport too you should put it on the WorldEnvironment node instead.

Yeah, that might work. But, I suspect there's going to be cases where you'd want an override. For example, being able to drop all lighting (sort of the solid mode in Blender). Or, be able to change the exposure for your workspace only without affecting the game.

**Comment by Calinou** [comment]
I suppose this can be fixed by forcing auto exposure on the editor camera if no camera effects are present.

**Comment by clayjohn** [comment]
I don't see the problem here, setting the CameraAttributes on the WorldEnvironment provides a fallback for all cameras, or you can override CameraSettings on individual Cameras by setting the CameraAttributes on the camera itself. In this case, your secondary viewport will just use the CameraAttributes set on the WorldEnvironement node.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/68052.
