### ISSUE TITLE
Can't render some characters

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#66737]
### Godot version

v4.0.beta2.official [f8745f2f7]

### System information

Windows 10, 64bit

### Issue description

![image](https://user-images.githubusercontent.com/35988767/193435470-3c5b2837-947e-41ba-b86b-e7931ba37c6e.png)
I was test many fonts but all can't render this character. I'm not sure this is a bug, or I'm not found the right font?

### Steps to reproduce

/

### Minimal reproduction project

[TextTest.zip](https://github.com/godotengine/godot/files/9691868/TextTest.zip)

**Comment by Chaosus** [comment]
cc @bruvzg

**Comment by bruvzg** [comment]
Most font (except a few pan-Unicode fonts like Unifont and Arial Unicode MS) won't have both CJK and `ǝ` at the same time, so you need to set up fallback fonts to use multiple fonts at the same time.

- Select your preferred main font in the `FileSystem` tab.
- Switch to `Import` tab.
- Add element in the `Fallbacks` property and set it the second font (you can add multiple).
- Click `Reimport`.

![Screenshot 2022-10-02 at 11 07 45](https://user-images.githubusercontent.com/7645683/193444719-4c7887a0-fffc-4fdf-96d6-c9da27c7d5a9.png)

In case you want to use the same fonts as Godot editor, it's `NotoSans_Regular` and `DroidSansJapanese`.

**Comment by CsloudX** [comment]
@bruvzg Thanks
