### ISSUE TITLE
Manjaro Linux drop down lists are broken for all nodes

### ISSUE THREAD

**Issue by FullDevMike** [godotengine/godot#66740]
### Godot version

Godot 4 Beta 2 

### System information

Manjaro Linux, Kernal 5.15.60-1-MANJARO (64 bit), KDE Plasma 5.24.6 KDE Frameworks 5.96.0 Qt 5.15.5 Graphics Platform: X11 Hardware 8x Intel Core i7-7700HQ CPU @2.8GHz 12GB Ram NVIDIA GeForce GTX 1060/PCIe/SSE2 (proprietarydrivers installed), Vulkan Instance 1.3.221

### Issue description

I have seen this issue in the last few releases from the new Godot 4 versions once I started using my Manjaro Linux laptop while traveling recently and wanted to submit 3 platforms for the recent Godot Wild Jam.

It appears the drop down menus are not working, a solid line appears and the full rect with associated items appear to not render properly. This seems to happen for all drop downs 

Here is the RGB dropdown in modulate property. (I also just now realized the color on rgb is not showing like it does on windows)

It is totally possible there is something on my linux setup that should be updated or its Godot. And will see if I can potentially contribute to fixing this if it is a true bug for Godot.  

![manjaro-linux-texture-dropdown-solid-line-no-options](https://user-images.githubusercontent.com/1005054/193435641-b890ec10-cde1-4d13-8c03-d8acc0624317.png)

This is trying to select the texture dropdown on a Sprite. 

![manjaro-linux-drop-down-solid-line-no-options](https://user-images.githubusercontent.com/1005054/193435645-f4fce9fa-e142-405a-a89a-70ee4a4dc242.png)

Here are the same drop downs on a Windows machine for what is to be expected. 

![windows-modulate-dropdown-rbg](https://user-images.githubusercontent.com/1005054/193435891-79c675b3-0b2c-4244-8b9f-51694cc3dd27.png)

![window-texture-dropdown](https://user-images.githubusercontent.com/1005054/193435894-1bc8ffea-d4f9-416a-9dc5-6d055eeee11e.png)

### Steps to reproduce

1. Open the Godot 4 Editor (visible in all the betas (1 & 2) and most recent Alphas) on Manjaro Linux (I have not tested other distributions yet) 
2. Create a new project
3. Create a new scene and add any node that has drop downs, for instance sprite 2d like my examples in the issue description. 
4. Notice a solid line instead of a drop down of options. 

### Minimal reproduction project

Any project with drop downs should show this issue on Manjaro Linux.

**Comment by Zireael07** [comment]
I have Manjaro and KDE and never had a problem. Maybe your gfx drivers?

**Comment by Calinou** [comment]
Can you reproduce this when running the editor with the `--single-window` [command line argument](https://docs.godotengine.org/en/latest/tutorials/editor/command_line_tutorial.html)? You'll have to open the project directly from the editor instead of going through the project manager for this to work as expected.

**Comment by FullDevMike** [comment]
It looks to be an issue with my setup, its related to this issue #https://github.com/godotengine/godot/issues/57708 

related to #https://github.com/KhronosGroup/Vulkan-Loader/issues/552 

Primarily the laptop was at one time ROG windows laptop, and has nvidia GTX and an intel graphics chip, that I wiped in favor of linux manjaro and instead of properly detecting the graphic card it was just failing saying there was no devices available.

closing this issue for now, and will continue to actively test manjaro linux and godot 4
