### ISSUE TITLE
signal: _body_shape_entered doesnt recognise CharacterBody2d, but works with StaticBody2d

### ISSUE THREAD

**Issue by mikelounge** [godotengine/godot#66761]
### Godot version

4.0beta2

### System information

Windows10

### Issue description

Since v4 the kinematicbody2d got replaced with characterbody2d.
I did setup an enemy with an area2d and a collissionshape2d in it. Its monitorable and correctly mask and layer set.
Created a signal -> body_shape_entered to detect if a player enters.

This event, never fires when a characterbody2d enters. So i placed a staticbody2d on the ground and set that body to the player-layer. Now the event body_shape_entered fires. its possible with staticbody, just not with the new CharacterBody2d.

In 3d it works too, but just not 2d.

### Steps to reproduce

create a player character of type: characterbody2d
create another characterbody2 as an enemy.
give the enemy an area2d with a collissionshape to detect the player.
set a signal to the area2 of the enemy that when a body_shape_enters a print("body entered") gets fired

when a player enters, it doesnt fire
when you place a staticbody2d in front of the enemy, it can detect the body (if it shares the same layer as the player)

### Minimal reproduction project

[2dPlatformer.zip](https://github.com/godotengine/godot/files/9692300/2dPlatformer.zip)

**Comment by Sauermann** [comment]
Please try connecting `area_shape_entered` instead of `body_shape_entered` for the enemy.

`body_shape_entered` does not work with the `CollisionShape2D` of the player.

**Comment by mikelounge** [comment]
did also not work.. but now of course, after hours of testing and failing, i found the issue just after posting this ^^

I did set the collission layer to Player inside the player scene... but the player instance in the level itself, didnt took over this setting and had nothing in there.

i was pretty sure, that editing the master of an instanced child, should update all childs.. maybe therefore not the collission is the bug, but the fact that it didnt update the childs?

is it possible to remove this entry here, that it's not too cluttered?

**Comment by Zireael07** [comment]
Issues cannot be removed, only closed.
