### ISSUE TITLE
Smooth geometry no longer possible with SurfaceTool

### ISSUE THREAD

**Issue by codespren** [godotengine/godot#66765]
### Godot version

4.0 Beta 1

### System information

macOS Monterey 12.6

### Issue description

Setting geometry non-smooth seems to be no longer possible.

In Godot 3.5, that was done by calling surfaceTool.add_smooth_group(bool). In Godot 4.0, the method is removed and there's a new method, set_smooth_group(int index) but it seems to set smoothgroups true but smoothgroups are true by default so it's not possible to disable them.

Also documentation lacks explanation what the parameter index should be when index arrays are not used.

### Steps to reproduce

1. Try to generate geometry with non-smooth normals.

**Comment by clayjohn** [comment]
The API has changed as you noted. You need to specify the smooth group that the vertex belongs to using the ``set_smooth_group()``. Previously the smooth group was inferred based on context, but it broke in many edge cases. 

The docs need to be updated, in particular the surface_tool tutorial needs to show how the new API is used.

**Comment by akien-mga** [comment]
Fixed by #68034.
