### ISSUE TITLE
Contents of 3D SubViewport now look blurry

### ISSUE THREAD

**Issue by lonevox** [godotengine/godot#66764]
### Godot version

4.0 beta 2

### System information

W10

### Issue description

If you have a low resolution Viewport of a 3D scene in 3.5 it looks pixelated, which could be a desired effect like in my project.

3.5:
![image](https://user-images.githubusercontent.com/38600896/193451609-52eecc65-d8ca-4ef5-9b80-72141dfb01d3.png)

4.0 beta 2:
![image](https://user-images.githubusercontent.com/38600896/193451639-3d7759ff-73ec-41fe-b89d-108e4b35b3cb.png)

This unfortunately seems to be a regression in Godot 4. This might be because of the new SubViewport Scaling 3D feature which can't be found with the old Viewport. Scaling 3D has no option for nearest-neighbor scaling as seen here:
![image](https://user-images.githubusercontent.com/38600896/193451680-cc87d441-f472-4657-b938-022a8f11ac07.png)
This might not be the reason, I'm just guessing.

### Steps to reproduce

Create a SubViewport containing a 3D scene and zoom in on it in the editor. It will look blurred.

### Minimal reproduction project

[SubViewportScaling3.5.zip](https://github.com/godotengine/godot/files/9692455/SubViewportScaling3.5.zip)
[SubViewportScaling4.0beta2.zip](https://github.com/godotengine/godot/files/9692457/SubViewportScaling4.0beta2.zip)

**Comment by clayjohn** [comment]
What is the texture filter mode set to on the Canvas item using the ViewportTexture? It looks like your CanvasItem is set to use linear filtering (the default) instead of nearest filtering. 

Note in 4.0 the texture filter mode is set on the CanvasItem not on the texture itself

**Comment by Calinou** [comment]
This is not a bug – see @clayjohn's comment above. You can change the default texture filter in the Project Settings (make sure the **Advanced** toggle is enabled).

See also https://github.com/godotengine/godot/issues/60150, https://github.com/godotengine/godot/issues/52332 and https://github.com/godotengine/godot/issues/57679.

**Comment by lonevox** [comment]
Ah apologies. I knew of the texture_filter property but didn't realize it applied to viewports too, but that makes sense. Hopefully this at least helps someone else out if they encounter this when porting.

**Comment by prominentdetail** [comment]
How do we apply this to a ViewportTexture that is used in a shader? I can't seem to disable the anti-aliasing.
