### ISSUE TITLE
ConvertTo TileSet file extension options not matching acceptable extensions during Tile Set loading

### ISSUE THREAD

**Issue by ivanskodje** [godotengine/godot#6678]
**Operating system or device - Godot version:**
Godot Engine v2.2.alpha.custom_build

**Issue description** (what happened, and what was expected):
When you click on Scene -> Convert To... -> TileSet... you get 3 options: *.tres, *.res and *.xml.
When you want to load a TileSet, it only accepts *.tres and *.xml, but not *.res.

We should be able to load .res files or it should be removed as an option when converting to TileSet :)

**Comment by vnen** [comment]
It should accept `*.res` too, it's a valid extension for binary resources.

**Comment by Hinsbart** [comment]
Ok, I found out that actually, **none** of the resource types allow loading from *.res in the inspector.
So it's not only a problem of `TileSet`.
The easy fix would be allowing *.res for all descendants of `Resource`, however I'm not sure if there's a resource type that can't be used with this format.

**Comment by vnen** [comment]
Likely all resource types can use `.res` extension (even GDScript and PackedScene files I'd say). However, it's clear that for some of them won't be the best option, so I'm not sure if it should even be allowed.

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by vnen** [comment]
This valid for 2.1.4 but it's already solved in 3.0.

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.
