### ISSUE TITLE
NavigationAgent3D crash when target not reachable

### ISSUE THREAD

**Issue by Geekotron** [godotengine/godot#66783]
### Godot version

4.0.beta2

### System information

Windows 11

### Issue description

NavigationAgent3D pathing causes a crash if target is not reachable:
`
ERROR: Index p_index = 8 is out of bounds (count = 1).
   at: operator[] (./core/templates/local_vector.h:168)
`

(I have a PR ready to fix this - will submit shortly after creating the issue)

### Steps to reproduce

1) Set navigation target a poly that's on the nav mesh but not connected to the navigation agent by any navmesh route. 
2) Trigger pathing by requesting next location or testing isTargetReachable

`
func _ready():
	navigation_agent.set_target_location(target_node.global_position);

func _physics_process(delta):
	var target_vec: Vector3 = navigation_agent.get_next_location();
`

### Minimal reproduction project

[Nav3dCrash.zip](https://github.com/godotengine/godot/files/9693323/Nav3dCrash.zip)

**Comment by Geekotron** [comment]
Related PR is #66784 
Looks like I don't have access to actually link the PR to the issue.

**Comment by Sauermann** [comment]
Just edit the opening post of the PR and insert "fix #66783" without the quotation marks in a line. That will link the PR to this issue.

**Comment by Geekotron** [comment]
@Sauermann , Thanks! I was trying the "manual linking" options from that URL and skipped right over the comment based option. My first github contribution in case you couldn't guess.

**Comment by smix8** [comment]
Regression from the recent changes in pr https://github.com/godotengine/godot/pull/66490.

I guess the underlying bug existed before but a wrong polygon pointer caused no crash while the change to index now causes this index error.
