### ISSUE TITLE
Mesh appears above another mesh after changing refraction on shader and does not revert

### ISSUE THREAD

**Issue by Mikeysax** [godotengine/godot#66790]
### Godot version

4.0-beta2

### System information

PopOS 22.04, 5.19.0-76051900-generic kernel, Ryzen 6800h, Radeon 6700m, amdgpu, Vulkan

### Issue description

Mesh appears above another mesh, even though it is below; Not sure why...

If you look at the feet, they are below the water, but then appear above the water. It's not clear as to why.

[Kooha-2022-10-02-18-54-49.webm](https://user-images.githubusercontent.com/15805689/193479962-e543cb88-1985-4a4c-89eb-b13f0401c6db.webm)

Here are the shader settings on the player:

![image](https://user-images.githubusercontent.com/15805689/193480269-80a16410-46a5-4d75-b921-810f0ec0d206.png)

![image](https://user-images.githubusercontent.com/15805689/193480068-698ef67e-f801-4d32-9ded-89223f75773e.png)

Here is the water shader code:

```
shader_type spatial;
render_mode blend_add, specular_toon;

uniform float speed : hint_range(-1,1) = 0.0;

//colors
uniform sampler2D noise1;
uniform sampler2D noise2;
uniform sampler2D normalmap : hint_normal;
uniform vec4 color : source_color;
uniform vec4 edge_color : source_color;

//foam
uniform float edge_scale = 1.0;
uniform float near = 1.5;
uniform float far = 1000.0;
uniform float displacement_amount = 1.0;
uniform float displacement_modulation = 1.0;

//waves
uniform vec2 wave_strengh = vec2(0.025, 0.025);
uniform vec2 wave_frequency = vec2(12.0, 12.0);
uniform vec2 time_factor = vec2(1.0, 2.0);

uniform float roughness = 0.1;
uniform float specular = 1.0;

float linearize(float depth){
	depth = 2.0 * depth - 1.0;
	return near * far / (far + depth * (near - far));
}


float waves(vec2 pos, float time){
	return (wave_strengh.y * sin(pos.y * wave_frequency.y + time * time_factor.y)) + (wave_strengh.x * sin(pos.x * wave_frequency.x + time * time_factor.x));
}


void vertex(){
	VERTEX.y += waves(VERTEX.xy, TIME);
}


void fragment(){
	float time = TIME * speed;
	vec3 n1 = texture(noise1, UV + time).rgb;
	vec3 n2 = texture(noise2, UV - time * 0.2).rgb;
	
	vec2 uv_movement = UV * 4.0;
	uv_movement += TIME * speed * 4.0;
	
	float z_depth = linearize(texture(DEPTH_TEXTURE, SCREEN_UV).x);
	float z_pos = linearize(FRAGCOORD.z);
	float diff = z_depth - z_pos;
	
	vec2 displacement = texture(noise1, UV - TIME / 7.0).rg; //vec2(sum * 0.05);
	displacement = ((displacement * 2.0) - 1.0) * displacement_amount;
	diff += displacement.x * displacement_modulation; //* 50.0;
	
	
	vec4 col = mix(edge_color, color, step(edge_scale, diff));
	
	vec4 alpha = vec4(1.0);
	alpha = texture(SCREEN_TEXTURE, SCREEN_UV + displacement);
	
	float sum = (n1.r + n2.r) - 1.0;
	float fin = 0.0;
	if (sum > 0.0 && sum < 0.4) fin = 0.1;
	if (sum > 0.4 && sum < 0.8) fin = 0.0;
	if (sum > 0.8) fin = 1.0;
	
	ALBEDO = vec3(fin) + mix(alpha.rgb, col.rgb, color.a);
	
	NORMAL_MAP = texture(normalmap, uv_movement).rgb;
	ROUGHNESS = roughness;
	SPECULAR = specular;
}
```

This was not happening until I added refraction on the player shader but, when I remove the setting, it doesn't revert. Not sure why?

### Steps to reproduce

As soon as I added refraction option on the shader, I noticed it started showing the player above the water in certain situations.

**Comment by Calinou** [comment]
> Mesh appears above another mesh, even though it is below; Not sure why...

This is a [transparency sorting](https://docs.godotengine.org/en/stable/tutorials/3d/3d_rendering_limitations.html#transparency-sorting) issue, which can't be resolved other than by using opaque materials or alpha scissor instead of alpha blending. Unfortunately, refraction **requires** alpha blending to work, as it needs to read what's behind the object to be able to refract anything. (Refraction will always set the material's alpha mode to alpha blend, even if set otherwise.)

Closing, as this is a 3D rendering limitation.

**Comment by Mikeysax** [comment]
Well @Calinou what is odd, is I've restarted my machine without refraction enabled, and it's a non-issue. Please see the following video:

[Kooha-2022-10-02-19-18-22.webm](https://user-images.githubusercontent.com/15805689/193480731-c2ac5760-4d4e-4384-b115-06bad7fc0164.webm)
