### ISSUE TITLE
Windows content is displayed wrong when embedded

### ISSUE THREAD

**Issue by Sauermann** [godotengine/godot#66809]
### Godot version

v4.0.beta.custom_build [d331b803b] and v4.0.beta2.official

### System information

Linux and Windows

### Issue description

For the following aspect and mode combinations of a window the content is displayed wrong when the window is embedded.
aspect: `CONTENT_SCALE_ASPECT_KEEP`, `CONTENT_SCALE_ASPECT_KEEP_WIDTH`, `CONTENT_SCALE_ASPECT_KEEP_HEIGHT`.
mode: `CONTENT_SCALE_MODE_CANVAS_ITEMS`, `CONTENT_SCALE_MODE_VIEWPORT`

When embedded & When not embedded:
![image](https://user-images.githubusercontent.com/6299227/193551263-476f47ef-df89-4762-a18f-315003f1de1f.png) ![image](https://user-images.githubusercontent.com/6299227/193551376-07bb3de6-45e6-495e-9915-ce962674edee.png)

I would expect, that the window content shows the same in both cases.

Since the non embedded version works the same in Linux and Windows and event position align with the non embedded version and the same display effect can be achieved by using `CONTENT_SCALE_ASPECT_IGNORE`, I assume, that this is a bug for embedded windows. So the embedded variant has wrong scaling and is missing the black bars at the top and bottom.

### Steps to reproduce

Have a window `w` with:
```GDScript
	w.set_size(Vector2(100, 200))
	w.set_content_scale_aspect(Window.CONTENT_SCALE_ASPECT_KEEP)
	w.set_content_scale_mode(Window.CONTENT_SCALE_MODE_VIEWPORT)
	w.set_content_scale_size(Vector2(50, 50))
```
It displays wrong when embedded.

1. Load and run the MRP
2. Click on the button to switch between embedding and not embedding mode.

### Minimal reproduction project

This is a MRP for the combination `CONTENT_SCALE_ASPECT_KEEP` and `CONTENT_SCALE_MODE_VIEWPORT`.
[BugWindowDisplayBar.zip](https://github.com/godotengine/godot/files/9696603/BugWindowDisplayBar.zip)

**Comment by YuriSizov** [comment]
Still valid as of 4.1 beta 3.

**Comment by Koyper** [comment]
This is related to [#54030](https://github.com/godotengine/godot/issues/54030#issuecomment-1631432733).
