### ISSUE TITLE
`FileAccess` produces `.tmp` file when used inside `EditorPlugin._build` callback.

### ISSUE THREAD

**Issue by RoniPerson** [godotengine/godot#66818]
### Godot version

v4.0.beta2.official [f8745f2f7]

### System information

Windows 10

### Issue description

When writing to a file in the `_build` callback of an `EditorPlugin` and afterwards printing the list of files in this directory, the file is not in the list. Instead a file with `.tmp` added is contained. The following code was used:
```swift
@tool
extends EditorPlugin


func _build() -> bool:
	var file = FileAccess.open("res://test.txt", FileAccess.WRITE)
	file.store_string("test")
	file.flush()
	print(DirAccess.get_files_at("res://"))
	return false
```
Output: `[".gitattributes", ".gitignore", "icon.svg", "icon.svg.import", "project.godot", "test.txt.tmp"]`

Using the old API's in beta1 this did not occure.
Code in beta1:
```swift
@tool
extends EditorPlugin


func _build() -> bool:
	var file = File.new()
	file.open("res://test.txt", File.WRITE)
	file.store_string("test")
	file.close()

	var dir = Directory.new()
	dir.open("res://")
	print(dir.get_files())
	return false

```
Output (beta1): `[".gitattributes", ".gitignore", "icon.svg", "icon.svg.import", "project.godot", "test.txt"]`

At first I thought it could have something to do with the removed `close` method. But the beta2 code works as expected, when used in a normal script. So this must be some edge case.

### Steps to reproduce

- Create an editor plugin with the code from above.
- Try to run in beta1 and beta2
- Observe the output

### Minimal reproduction project

[file_access_bug.zip](https://github.com/godotengine/godot/files/9697314/file_access_bug.zip)

**Comment by bitsawer** [comment]
I'm not sure if this is a bug. If you add `file = null` after `file.flush()`, it will release the reference and the file will be created in the file objects destructor. This is supposed to be the "new" way to do this, but I find removing that FileAccess.close() method to be pretty confusing to many.

When when using "res://"-paths etc. the file access does some special handling, and sometimes that special handling is writing into a .tmp file and then renaming it when everything is ready. Previously that was when close() was called, now it is when all references to it are gone and the FileAccess object is destructed.

Also, after that fix get_files_at() will list both "test.txt" and ""test.txt.tmp", althoug that .tmp is cleaned up immediately afterwards. Not sure what to make of that.
