### ISSUE TITLE
Internal script error! Opcode: 1 (please report)

### ISSUE THREAD

**Issue by ababen1** [godotengine/godot#66810]
### Godot version

v4.0.beta2.official [f8745f2f7]

### System information

Windows 11, GLES3, NVIDIA GeForce GTX 1650, i5-11300H

### Issue description

screenshots of the error:
![image](https://user-images.githubusercontent.com/80917990/193558066-0ec67017-1703-4765-ba28-4e500ecf0470.png)

![image](https://user-images.githubusercontent.com/80917990/193558247-8923df2b-9686-4954-aded-e25c7426b44f.png)

note that another bug was already present while this happened - #66429 . I'm not sure if it's related.

### Steps to reproduce

apparently this is what caused the error, but i actually never called this function.
```
var _prev_letter_chance: = 0.7
func _should_get_prev_letter_question() -> bool:
	return randf() <= _prev_letter_chance
```

**Comment by dalexeev** [comment]
Please check if the bug is still reproducible in RC 1. If so, please provide an MRP.

**Comment by ababen1** [comment]
Nope, I dont see it anymore 👍
