### ISSUE TITLE
Can't name C# variable "value" or "name"

### ISSUE THREAD

**Issue by lonevox** [godotengine/godot#66819]
### Godot version

4.0beta2

### System information

W10

### Issue description

Naming any variable in C# "value" will cause the build to fail. Here's my build log: https://pastebin.com/d3zVucAb
The important line in the build log is:

> Godot.SourceGenerators.ScriptPropertiesGenerator\new_script_ScriptProperties_Generated.cs(21,76): error CS0269: Use of unassigned out parameter 'value'

This doesn't happen in Godot 3.5.
"value" is a keyword in C#, however the use of it as a variable name is allowed and should compile.

### Steps to reproduce

Create a C# script then add a field called "value". Try to build the project and it should fail.

### Minimal reproduction project

[ValueVariableC#Bug4.0beta2.zip](https://github.com/godotengine/godot/files/9697957/ValueVariableC.Bug4.0beta2.zip)

[ValueVariableC#Bug3.5.zip](https://github.com/godotengine/godot/files/9697941/ValueVariableC.Bug3.5.zip)

Run build on both projects. You can see the 4.0beta2 project crashes and the 3.5 project doesn't.

**Comment by lonevox** [comment]
Fields called "name" also don't work.

**Comment by IXLLEGACYIXL** [comment]
C:\Godot\GD4\Godot.SourceGenerators\Godot.SourceGenerators.ScriptPropertiesGenerator\GD4.Core.Character_ScriptProperties_Generated.cs(16,13): error CS8331: Eine Zuweisung zu Variable "in godot_variant" ist nicht m”glich, weil es sich um eine schreibgeschtzte Variable handelt. [C:\Godot\GD4\Gd 4.csproj]
         C:\Godot\GD4\Godot.SourceGenerators\Godot.SourceGenerators.ScriptPropertiesGenerator\GD4.Core.Character_ScriptProperties_Generated.cs(28,76): error CS1503: Argument "1": Konvertierung von "Godot.NativeInterop.godot_variant" in "long" nicht m”glich. [C:\Godot\GD4\Gd 4.csproj]
         C:\Godot\GD4\Godot.SourceGenerators\Godot.SourceGenerators.ScriptPropertiesGenerator\GD4.Core.Character_ScriptProperties_Generated.cs(28,76): error CS0269: Verwendung des nicht zugewiesenen out-Parameters "value". [C:\Godot\GD4\Gd 4.csproj]
you write to a writing protected field which is not allowed is first error
second error is cant convert godot variant to long not possible
third is usage of unassigned out parameter value
