### ISSUE TITLE
TabBar Error

### ISSUE THREAD

**Issue by Temurumaru** [godotengine/godot#66828]
### Godot version

4.0 Beta 2

### System information

Linux 5.18 Fedora 36 AMD Vega 7

### Issue description

Godot Engine v4.0.beta2.official (c) 2007-2022 Juan Linietsky, Ariel Manzur & Godot Contributors.
  modules/gltf/register_types.cpp:75 - Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
  modules/gltf/register_types.cpp:99 - FBX file import is enabled in the project settings, but no FBX2glTF path is configured in the editor settings. FBX files will not be imported.
--- Debug adapter server started ---
--- GDScript language server started ---
  scene/gui/tab_bar.cpp:589 - Index p_current = 2 is out of bounds (get_tab_count() = 2).

### Steps to reproduce

Changed Tab Bar

**Comment by YeldhamDev** [comment]
Could you give more information? What do you mean by "Changed Tab Bar"?

**Comment by meko3** [comment]
I got this error, too.
But, when open project.
Sorry if it's different from this issue.

1. I set filesystem/import/blender/blender3_path from Project Setting(Editor) -> failed
2. I set filesystem/import/blender/blender3_path in editor_settings-3.tres(or 4) -> failed.

Where can I set Blender Path ?

OS: M1 Mac Monterey

**Comment by KoBeWi** [comment]
This error can appear when you try to increase `current_tab` in the inspector. I think this is expected behavior, because inspector's spinboxes don't have limits.
