### ISSUE TITLE
Double clicking JSON files in FileSystem tab throws errors

### ISSUE THREAD

**Issue by arotter** [godotengine/godot#66820]
### Godot version

v4.0.beta2.official [f8745f2f7]

### System information

Windows 10 21H2 (Build 19044.2075)

### Issue description

In **beta1** was able to double click a JSON file shown in the FileSystem tab to open it in the script editor view as a text file. Doing the same in **beta2** throws the following errors for the file:
```
ERROR: Failed loading resource: res://static_data/weapons/DamageBehaviors.json. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:221)
ERROR: Condition "!res.is_valid()" is true. Returning: ERR_CANT_OPEN
   at: load_resource (editor/editor_node.cpp:1248)
```
Accessing the file via `FileAccess` and parsing it via `JSON.parse()` works without problems, as does dragging the file from FileSystem into the script editor's vertical tab space.

### Steps to reproduce

1. Add JSON file to folder in `res://`
2. Double click on file
3. File doesn't open as expected, errors in console

Using the attached project:
1. Open project
2. Double click `res://static_data/weapons/DamageBehaviors.json`
3. File doesn't open as expected, errors in console

### Minimal reproduction project

[BugReproduction.zip](https://github.com/godotengine/godot/files/9698024/BugReproduction.zip)

**Comment by akien-mga** [comment]
That's due to #65295. JSON is now treated as a resource file but it's not an *imported* one, and apparently the FileSystem dock logic for double click doesn't know how to handle this.
