### ISSUE TITLE
character encoding cyrillic converter

### ISSUE THREAD

**Issue by NordeN37** [godotengine/godot#66823]
### Godot version

Godot_v4.0-beta2 linux

### System information

Ubuntu 22.04

### Issue description

Project name encoding error in taskbar "Gnome 42"
![image](https://user-images.githubusercontent.com/43890873/193613979-03cf01fd-cf06-47be-9f7c-785f333673fb.png)

### Steps to reproduce

Start projekt name "Новый игровой проект"

**Comment by akien-mga** [comment]
Duplicate of #56655
