### ISSUE TITLE
Project Manager presented random noise rather than 'Local Projects' (Image Attached)

### ISSUE THREAD

**Issue by Fracture98** [godotengine/godot#66826]
### Godot version

v4.0.beta1.official [20d667284]

### System information

Windows 10 Pro 21H2, GLES3, GTX 980 v516.94

### Issue description

On startup, the Project Manager opened, but the display area inside the border was "garbage". Screen shot attached if I figure out how. As the mouse moved across, the garbage was slightly animated across the entire field.

![godot](https://user-images.githubusercontent.com/11006705/193629057-3f477882-e6bb-4cf2-b553-9dc1a31a0b36.png)

### Steps to reproduce

Start Godot normally from the Windows Start menu. This happens about 80% of the time. It is possible to retry and have it work fine.

### Minimal reproduction project

No project required. This issue occurs on startup before a project is loaded.

**Comment by clayjohn** [comment]
What are you doing to make it start up using GLES3 if you are opening from the Windows Start menu?

**Comment by Fracture98** [comment]
Additional information. The functionality is still there, but subsequent windows will also display like this. For example, "Create New Project" window will pop-up when the button is pressed but will also be displayed as garbage.

Choosing a project and clicking "Edit" will open Godot. It's taking a very long time with "Not Responding". I'll update if it starts. When the issue doesn't happen, Godot starts normally.

**Comment by Fracture98** [comment]
> What are you doing to make it start up using GLES3 if you are opening from the Windows Start menu?

I'm not - when it does run normally, I believe I've selected GLES3. For this issue, I'm not getting that far so the GLES3 can be ignored.

**Comment by Calinou** [comment]
> I'm not - when it does run normally, I believe I've selected GLES3.

Vulkan Clustered is the default on 4.0 on desktop platforms (and Vulkan Mobile is the default on mobile platforms). The project manager never runs using OpenGL unless specified with the `--rendering-driver opengl3` command line argument.

**Comment by clayjohn** [comment]
The reason I ask is that the project manager always opens with Vulkan unless you use a command line argument to require OpenGL instead. So if you never use the command line argument, you are likely using Vulkan. 

You should instead run Godot by opening a terminal in the directory that you saved Godot in then type
``./Godot_v4.0-beta1_win64.exe --rendering-driver opengl3``

**Comment by Fracture98** [comment]
> The reason I ask is that the project manager always opens with Vulkan

I use the standard startup with no command line arguments. Ignore GLES3. I put that as the bug tool includes it in the suggestion so I included what I recalled setting the project to _when it loaded properly._ I can't see its relevant here.

**Comment by Calinou** [comment]
> I can't see its relevant here.

It's relevant because the rendering backend determines the method used for both 2D and 3D rendering. The 4.0 renderers are still in development and have many bugs, so it's important to be correct here.

**Comment by clayjohn** [comment]
Can you check that you have Vulkan support? The easiest way to do so is to download the [Vulkan SDK](https://vulkan.lunarg.com/sdk/home) and run the vkcube sample program

**Comment by Fracture98** [comment]
> Can you check that you have Vulkan support? The easiest way to do so is to download the [Vulkan SDK](https://vulkan.lunarg.com/sdk/home) and run the vkcube sample program

Not at the moment. Also, this does function occasionally. Also, V3 starts fine. This is happening on startup, before a project is even selected or loaded with no command line options.

**Comment by Fracture98** [comment]
Here is the same startup process. I repeated it enough times to get both a fail and success. Nothing else changes. I just killed and restarted half-a-dozen times. The successful start occurred even though the Project Manager was display the glitch, so the glitch between the project manager and the main editor appear to be independant.

![Screenshot 2022-10-03 105303](https://user-images.githubusercontent.com/11006705/193634622-c5eb7780-8b51-4592-aae5-a40bb546ebc8.png)
![Screenshot 2022-10-03 105356](https://user-images.githubusercontent.com/11006705/193634638-dcd0ad8b-f520-4b85-ac15-386d23b70510.png)

**Comment by Fracture98** [comment]
> This is a duplicate of another issue, but I can't find it right now.

I couldn't find one either. Closest I came was a rendering issue with Project Manager on macOS:
Vulkan: Project manager displays as black on macOS (Intel UHD Graphics 617) #66653

**Comment by Zireael07** [comment]
Godot 3.x (which is what I assume you meant when saying V3) uses OpenGL, not Vulkan.

This looks like an issue with Vulkan and/or your graphics drivers.

**Comment by Fracture98** [comment]
> Can you check that you have Vulkan support? The easiest way to do so is to download the [Vulkan SDK](https://vulkan.lunarg.com/sdk/home) and run the vkcube sample program

@clayjohn and @Zireael07 This was the correct line of reasoning. I was able to install Vulcan SDK (with no optional components selected). Vulcan cube results did show an issue:

![Screenshot 2022-10-03 115628](https://user-images.githubusercontent.com/11006705/193647485-252128b6-ee51-4b7a-a788-d5f532506977.png)

I upgraded from NVidia **516.94** to **517.48**. Vulcan cube results looked good:

![Screenshot 2022-10-03 120247](https://user-images.githubusercontent.com/11006705/193647868-0056a7da-d501-4cb1-bac7-1e8f4646a3d2.png)

Godot V4 has now started correctly 3 times. I'll call that solved.

Attaching NVidia before/after configs if anyone cares:
[NVIDIA System Information 10-03-2022 11-54-44.txt](https://github.com/godotengine/godot/files/9699889/NVIDIA.System.Information.10-03-2022.11-54-44.txt)
[NVIDIA System Information 10-03-2022 12-03-11.txt](https://github.com/godotengine/godot/files/9699892/NVIDIA.System.Information.10-03-2022.12-03-11.txt)

**Comment by clayjohn** [comment]
Glad to hear everything is working now!
