### ISSUE TITLE
notes about the baked light baker of godot 2.1

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#6682]
**Operating system or device - Godot version:**
godot 2.1

**Purpose of this post:**

As mentioned by @reduz on IRC, the Baked-Light Baker will be rewritten for 3.x.

Though, some of us might be willing to share their findings about current implementation and discuss them.
This is the purpose of this post.

Note :
On IRC @reduz said he wanted to make some changes to the baker :
1) drop geometry and only do collision against the octree
2) keep track of how much light entered from each side of the cube to avoid the current bleeding problems
3) do everything in GPU

---

My today's findings about current implementation :
( tested with a godot version 2.x win64 compiled with MSVC 2015 )

**about `rand()` and multi-thread :**

Current implementation of the baker makes use of `rand()` :
- I've found that each threads will generate the same random numbers, and thus will throw the same rays.
- It tends to create cloudy-noisy patterns that never really get smoothed.
- I read everywhere that `rand()` and `srand()` are not thread-safe.
- on some implementation `RAND_MAX` is limited to 32768. (this is the case with MSVC2015)

So,
I've replaced `rand()` with a RNG from the standard c++11 `random` library ([`#include <random>`](http://www.cplusplus.com/reference/random/mt19937/)) : 
- each thread has its own RNG which is seeded with a 100% random seed.
- noisy-cloudy patterns are smoothed faster
- the `RAND_MAX` is unsigned 2^32

(i'll publish the patch later)

Here are two screenshots to compare.
**Top** is standard `rand()`, **bottom** is thread seeded `std::mt19937` RNG.

Both are baked for 15 minutes at around 201.500 rays/s on 3 threads ( Editor Settings / Light Baker / Custom Bake Threads = 3 ), and a plot size of 2.5.

![baked_light_baker_c_rand](https://cloud.githubusercontent.com/assets/9801802/19022379/cfe8e80c-88d7-11e6-8926-6c64c1021c7d.png)

![baked_light_baker_mt_rand](https://cloud.githubusercontent.com/assets/9801802/19022380/d583a572-88d7-11e6-94c8-7365108483d5.png)

**Comment by SuperUserNameMan** [comment]
``std:mt19937`` not available on GCC 4.6. Will have to use an alternative.

Here comparison again, baked for 15 minutes with a plot size of 1.

![baked_light_baker_plotsize_1](https://cloud.githubusercontent.com/assets/9801802/19022909/c6f39afc-88e2-11e6-8cd1-90a563640250.png)

**Comment by SuperUserNameMan** [comment]
**findings of the day :**

- the ``#include <random>`` is still experimental with GCC 4.6.3 which is used by Travis.

- the Godot's ``Math::rand_from_seed()`` seems to have a too low periodicity, and gives too much patterns.

- the Mersenne Twister Pseudo Random Number Generator published on Wikipedia gives pretty good results.


With standard ``rand()``, i get around 200 000 rays/s on 3 threads.
With the RNG from Wikipedia, i get around 500 000 rays/s on 3 threads,  with peaks up to 700 000 rays/s.
Also, the periodicity is higher, and the ``RAND_MAX`` is ``0x7fFFffFF``.

Maybe Godot's ``Math::rand_from_seed()`` could be updated to use Wikipedia's RNG as well.

**Comment by SuperUserNameMan** [comment]
oh, just before going to sleep, the other finding of the night :

- according to what i've read somewhre on MSDN, MSVC's clib is thread-safe. So ``srand()`` and ``rand()`` can be used by each thread. I've made the test with MSVC 2015.
Also, the internal algorithm used by microsoft for ``rand()`` is the MT19937.
(i wish i had not lost the link to the page, but it's too late : I closed the browser :-/ )
Though, the RAND_MAX is low.

I've not tested with GCC and other compilers. But has mentionned previously, ``rand()`` should not be considered thread safe.

**Comment by SuperUserNameMan** [comment]
a paper about efficient [_"Conversion of unsigned 32-bit random integers to double pre
cision floating point"_](Conversion of unsigned 32-bit random integers to double pre
cision floating point )

**Comment by SuperUserNameMan** [comment]
Well, I've tested all of these RNG algo :
- XONOROSHI128PLUS
- XORSHIFT128
- XORSHIFTSTAR
- XORSHIFTPLUS
- MT19937
- [XKCDRANDOMNUMBER](http://imgs.xkcd.com/comics/random%5Fnumber.png)

They globally all give similar performances. 
XONOROSHI128PLUS which is said to be an improvement of all the others XORSHIFTxxx is, in theory, the fastest one.
It has a periodicity of 2^128 − 1, and a RAND_MAX of 64 bits.

Though, as none of them create a miraculous speed boost for the baker, the traditional MT19937 that has a periodicity of 2^19937 − 1 could also be selected. Though, this implementation has a RAND_MAX of 32bits.

I haven't yet tested the ziggurat method mentioned by @djrm, nor the [PGC32](PCG32 ) mentioned by @est31.

**Comment by kruglinski** [comment]
Sorry for "Flogging a dead horse" but follow this clue I'm able to make Godot 2.1 light baker even better, many thanks!

unpatched Godot 2.1:
![unpatched_lightmap](https://user-images.githubusercontent.com/2869425/61922984-ea27ac80-af94-11e9-89a2-32473e5592fe.png)
![unpatched](https://user-images.githubusercontent.com/2869425/61922989-edbb3380-af94-11e9-8334-e5bd4e8cd9cd.png)

patched Godot 2.1:
![patched_lightmap](https://user-images.githubusercontent.com/2869425/61922998-f9a6f580-af94-11e9-8044-68433dc1c33c.png)
![patched](https://user-images.githubusercontent.com/2869425/61923001-ff044000-af94-11e9-9002-c4db387ba834.png)
