### ISSUE TITLE
Camera Zoom Vector does the reverse of the expected behavior

### ISSUE THREAD

**Issue by ryash072007** [godotengine/godot#66831]
### Godot version

4.0.Beta1

### System information

Windows 10

### Issue description

Increasing the Zoom Vector of a Camera Node decreases the size seen in viewport rather than the expected behavior of the size in viewport seen to increase and vice-versa as according to the previous versions of Godot and also the Documentation.

### Steps to reproduce

1. Create a new 2D Scene
2. Add a Camera node
3. Increase the Zoom Vector and the Camera Zoom actually decreases and vice-versa.

### Minimal reproduction project

[Camera Bug.zip](https://github.com/godotengine/godot/files/9699588/Camera.Bug.zip)

**Comment by Sauermann** [comment]
related to #57392

**Comment by Zireael07** [comment]
documentation is out of date on this. Behavior was changed on purpose by the PR that Sauermann linked above

**Comment by ryash072007** [comment]
Oh! Thank you for explaining. Good day to you all.
