### ISSUE TITLE
MultiMeshInstance2D aabb not up-to-date after instances transformed

### ISSUE THREAD

**Issue by ualac** [godotengine/godot#66849]
### Godot version

4.0b2

### System information

Windows 11 Pro, Vulkan Mobile, RTX3090 (516.59)

### Issue description

When a MeshInstance2D has it's instances transformed in code the aabb of the canvas item does not appear to be updated. If they end up being outside of the original aabb this can cause them to be culled incorrectly. 

note: This is the same issue described in https://github.com/godotengine/godot/issues/54854 and fixed in https://github.com/godotengine/godot/pull/54899 

### Steps to reproduce

- Create a MultiMeshInstance2D and populate it with some instances
- Modify the instance transforms so that they now are positioned far outside of what the original aabb would be.
- Change the camera view such that the original MultiMesh2D aabb would be offscreen
- (the instances should now be incorrectly culled)

### Minimal reproduction project

In this project a set of instances are created clustered in the middle of the view. Left-click-drag to move the camera around and the instances should always be drawn.  

Press SPACE which will distribute the instances randomly in a larger area. Now moving the camera to the fringes of the instances should invariably cause them to disappear/be culled.  

Press A to recalculate the aabb (based on a workaround described in the original issue) and they should re-appear.

[godot4-bug-multimesh2d-aabb-main.zip](https://github.com/godotengine/godot/files/9701739/godot4-bug-multimesh2d-aabb-main.zip)

**Comment by Calinou** [comment]
> note: This is the same issue described in https://github.com/godotengine/godot/issues/54854 and fixed in https://github.com/godotengine/godot/pull/54899

The fix was only applied in `3.x`, not `master` (4.0 is derived from `master`).

**Comment by FalkoKotva** [comment]
Hi, can i work on this issue ?

**Comment by clayjohn** [comment]
@FalkoKotva Yes!

**Comment by mateuseap** [comment]
I worked on this issue! I checked the PR that fixed the issue #54854 and after that, I was able to solve the problem, hope that's everything ok :)

**Comment by cooperra** [comment]
Is anyone still working on this? If not, I'd like to.

**Comment by Calinou** [comment]
> Is anyone still working on this? If not, I'd like to.

There's an open pull request for this: https://github.com/godotengine/godot/pull/67116
