### ISSUE TITLE
Theme Variation with StyleBoxTexture returns wrong type

### ISSUE THREAD

**Issue by markdibarry** [godotengine/godot#66850]
### Godot version

4.0.dev (14e1f36e61)

### System information

Windows 10

### Issue description

When trying to access a theme variation using a `StyleBoxTexture`, it returns a node of type `StyleBoxFlat`
![image](https://user-images.githubusercontent.com/21325943/193705929-6a5fb5ce-5c0d-460d-a2bd-d3c9c49a3bcc.png)
![image](https://user-images.githubusercontent.com/21325943/193706007-1fc5451b-6f36-4276-b208-a8c3764a9eea.png)

### Steps to reproduce

Run the MRP. View the output.

### Minimal reproduction project

[ThemeBug.zip](https://github.com/godotengine/godot/files/9701786/ThemeBug.zip)

**Comment by KoBeWi** [comment]
You should use `get_theme_stylebox("panel", "PanelContainerAlt").`

**Comment by akien-mga** [comment]
The method should probably return an empty ref when called with invalid arguments?

**Comment by markdibarry** [comment]
Ah, you're right. The documentation is a little fuzzy on this. It just says the parameters are `StringName name, StringName theme_type=""`, but doesn't give any descriptive examples, so my assumption was that `name` was the name I gave it ("PanelContainerAlt"), when it's really the name Godot assigns it in the theme dock:
![image](https://user-images.githubusercontent.com/21325943/193827359-10f447e5-dd44-4ed5-9a53-145c60389e10.png)
and the `theme_type` is the name you give the theme variation.

I'll close this as user error, but I may make a PR to flesh out the documentation.
