### ISSUE TITLE
Mesh VisibilityInstance layers value not preserved on .duplicate() 

### ISSUE THREAD

**Issue by dynamite-ready** [godotengine/godot#6685]
I'm running Godot 2.1 on Windows 8.

After setting up a basic scene, I set the camera to only display a specific 'Visible Layer', and set the only mesh in the scene to display on a specific 'VisibilityInstance Layer'. 

After I translate the mesh, I .duplicate() it, but the duplicate does not appear on the same layer. I can only see the new duplicated mesh if I set the camera to display the default visible layer. 

I suspect that means that duplicated meshes lose VisibilityInstance layer settings...

Can this be confirmed?

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by dynamite-ready** [comment]
"We still have hundreds of issues whose relevance/reproducibility needs to be checked against the current stable version, and that's where you can help us.
Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?"

Checked again. The bug can still be reproduced, as described on commit - 59710880cd21d79ae1329f04eb35ea48e646acb3 (Godot 3.0.1/2).

**Comment by reduz** [comment]
This works perfect, tested it. I assume the problem may have been that:

1. You forgot to add the duplicate to the tree again
2. You misunderstood how layers work (common problem).

I will add a function to set layer bits independently, like physics has and then close this.
