### ISSUE TITLE
When autocompleting a function name, pre-existing parenthesis get deleted

### ISSUE THREAD

**Issue by FHEK789** [godotengine/godot#66854]
### Godot version

4.0.beta2

### System information

Kubuntu 22.04

### Issue description

This happens when you're using a function as some other function's parameter, the pre-existing parenthesis of the first function get deleted.

Video Example:

https://user-images.githubusercontent.com/52990296/193709149-30c7ff5a-90bf-4577-bcdb-825a6a06b48b.mp4

### Steps to reproduce

1. Call a function as some other function's parameter

**Comment by Mickeon** [comment]
Godot's Script Editor definitely isn't the only program I've used that does this, but it's be nice to tidily fix it, regardless of the coding language used in the Editor.
