### ISSUE TITLE
Export hint LAYERS_2D_NAVIGATION displayed as physics layers in editor

### ISSUE THREAD

**Issue by Shou** [godotengine/godot#66865]
### Godot version

v3.5.1.stable.custom_build

### System information

NixOS

### Issue description

When using the `LAYERS_2D_NAVIGATION` export hint, it is displayed as if `LAYERS_2D_PHYSICS` was used instead, with different (incorrect) layer names. It should be using the navigation layer names.

### Steps to reproduce

```gdscript
export (int, LAYERS_2D_NAVIGATION) var navigation_layers: int = 0
```

**Comment by akien-mga** [comment]
Fixed by #66868.
