### ISSUE TITLE
Directory API gone in 4.0 beta 2?

### ISSUE THREAD

**Issue by dploeger** [godotengine/godot#66866]
### Godot version

4.0 beta2

### System information

macOS ARM

### Issue description

Trying to migrate EgoVenture to Godot 4 and suddenly calls to the [Directory API](https://docs.godotengine.org/en/latest/classes/class_directory.html) result in a "Identifier Directory not declared in the current scope".

Is this an API change or a bug? I didn't find any notes about it.

### Steps to reproduce

Call

```gdscript
var dir = Directory.new()
```

**Comment by akien-mga** [comment]
> Is this an API change or a bug? I didn't find any notes about it.

Did you read the release notes? ;)
https://godotengine.org/article/dev-snapshot-godot-4-0-beta-2

![image](https://user-images.githubusercontent.com/4701338/193760970-3131ca37-5b99-40a2-9d5e-90857fb56474.png)

**Comment by dploeger** [comment]
Oh my. Missed that. Thanks! ❤️

**Comment by dploeger** [comment]
The migration tool should've read it, too, then. 😂

**Comment by Calinou** [comment]
> The migration tool should've read it, too, then. joy

The migration tool can only perform simple regex operations, so it can't do this conversion automatically.

**Comment by dploeger** [comment]
Did the API change that much? I thought a `s/Directory\./DirAccess./g` would be enough.

**Comment by zkmark** [comment]
> > Is this an API change or a bug? I didn't find any notes about it.
> 
> Did you read the release notes? ;) https://godotengine.org/article/dev-snapshot-godot-4-0-beta-2
> 
> ![image](https://user-images.githubusercontent.com/4701338/193760970-3131ca37-5b99-40a2-9d5e-90857fb56474.png)

How to delete a file? this way doesn't work for me
var file = FileAccess.remove("user://savegame.save")
