### ISSUE TITLE
Easy download and install of export templates from the editor

### ISSUE THREAD

**Issue by Duskitty** [godotengine/godot#6687]
So it's come to my attention that the way godot updates is rather....clunky in terms of needing to go onto the site and download it repeatedly for every update

is it possible to add a functionallity or something to the engine perhaps on the projects menu where it'll scan for an update, then you have the option to click if you want to update and it'll get the files and update godot to the latest version?

(just an idea for something to add to the 2.2/3.0 release)

**Comment by reduz** [comment]
We are working on this for 3.0

**Comment by reduz** [comment]
i don't think godot will self-update as there are so many ways to obtain it, many of which already self-update (steam). But templates need to be updated automatically, and this is being worked on, so leaving this open

**Comment by akien-mga** [comment]
Renamed accordingly.

**Comment by Jerome67000** [comment]
now that it is possible to download templates inside godot, we can close this one, no?

**Comment by Zireael07** [comment]
Downloading templates inside godot is buggy from what I heard on Discord, so no?

**Comment by Jerome67000** [comment]
Was buggy 2 months ago, but last time I used it, all worked. Can you give a try ?

**Comment by akien-mga** [comment]
Yep, that works fine now.
