### ISSUE TITLE
NavigationPolygon doesn't have hints for .get_vertices() in GD4.0b2

### ISSUE THREAD

**Issue by Black-Virtue** [godotengine/godot#66874]
### Godot version

4.0b2

### System information

Windows10

### Issue description

In GDScript.
As it says.
Type hints for most of the other properties and methods show fine.
Using the method works fine, just doesn't hint.
Oddly if you do type in the ".get vertices()" it does recognise that the return type is an array and provide appropriate type hints for that.

### Steps to reproduce

Create a GDscript file in the editor
Create a NavigationPolygon typed variable
Type the variable name followed by "." to receive type hints
Fail to receive type hint for get_vertices()

**Comment by smix8** [comment]
You don't see set/get methods as a GDScript hint when they are bound to a property, only the property shows up in the hint.

**Comment by Calinou** [comment]
This is not a bug – see @smix8's comment above.
