### ISSUE TITLE
NavigationAgent3d causes a crash when there is no valid path

### ISSUE THREAD

**Issue by rpiepsney** [godotengine/godot#66872]
### Godot version

4.0.beta2

### System information

Windows 10

### Issue description

When NavigationAgent3d finds no path, it causes a crash with the following error message:

> ERROR: Index p_index = 239 is out of bounds (count = 1).
>    at: operator[] (./core/templates/local_vector.h:168)

Value of p_index will vary.

### Steps to reproduce

1. With NavigationAgent3d, set up a nav mesh that isn't wholly connected.
2. If set_target_location( ) is set to somewhere that no path is available, the crash will happen at the next call of get_next_location( ).
3. get_next_location( ) is called.

**Comment by Zireael07** [comment]
dupe of #66783 fixed by #66784

you don't even need to search it's one of the most recently fixed issues so just a click on closed would've shown this

**Comment by rpiepsney** [comment]
Glad to hear it, thank you!
