### ISSUE TITLE
C#: Unable to instantiate object of type `RigidBody3D` in script of node type `CharacterBody3D`

### ISSUE THREAD

**Issue by LennDG** [godotengine/godot#66870]
### Godot version

4.0 beta 1

### System information

Windows 10, Vulkan

### Issue description

After converting my new-ish project from Godot 3 to 4 I encountered an issue where my player character is unable to instantiate projectiles.

The Character script has the following relevant code to spawn a new projectile:
```csharp
using Godot;
using System;

public partial class Character : CharacterBody3D
{
	private PackedScene bolt;

	// Called when the node enters the scene tree for the first time.
	public override void _Ready()
	{
		bolt = ResourceLoader.Load<PackedScene>("res://scenes/skills/projectiles/arcane-bolt/ArcaneBolt.tscn");

	}

	public override void _PhysicsProcess(double delta)
	{
		UseSkills();
	}

	private void UseSkills()
	{

		if (Input.IsActionJustPressed("shoot", true)) {
			ArcaneBolt newbolt = bolt.Instantiate<ArcaneBolt>();
		}
	}
}
```

With the ArcaneBolt class being:
```csharp
using Godot;
using System;

public partial class ArcaneBolt : Projectile
{

    [Export]
    public int SPEED = 10;
    
}

public abstract partial class Projectile : RigidBody3D
{
	public int Speed = 10;
	public Vector3 Direction;

	public override void _Ready()
	{
		LinearVelocity = Direction.Normalized() * Speed;
		
	}

	// Default implementation, just removes the projectile on collision
	public virtual void OnCollision(KinematicCollision3D collision)
	{
		QueueFree();
	}
}
```

When the player attempts to use the skill, the game crashes and returns the error
```Script inherits from native type 'RigidBody3D', so it can't be instantiated in object of type: 'CharacterBody3D'```

I don't understand why it matters what type of object is trying to instantiate a scene. 

### Steps to reproduce

Run the provided minimal project and click the left mousebutton.

### Minimal reproduction project

[Instance Bug.zip](https://github.com/godotengine/godot/files/9704999/Instance.Bug.zip)

**Comment by akien-mga** [comment]
This is your `ArcaneBolt.tscn` scene:
```
[gd_scene load_steps=4 format=2]

[ext_resource path="res://scenes/skills/projectiles/arcane-bolt/ArcaneBolt.cs" type="Script" id=1]
[ext_resource path="res://scenes/effects/ArcaneBolt/ArcaneBoltEffect.tscn" type="PackedScene" id=2]

[sub_resource type="SphereShape3D" id=1]
radius = 0.118939

[node name="ArcaneBolt" type="CharacterBody3D"]
script = ExtResource( 1 )

[node name="ArcaneBoltEffect" parent="." instance=ExtResource( 2 )]

[node name="CollisionShape3D" type="CollisionShape3D" parent="."]
shape = SubResource( 1 )

[node name="Timer" type="Timer" parent="."]
```

`ArcaneBolt` is a node of type `CharacterBody3D` so the class defined in `ArcaneBolt.cs` needs to inherit `CharacterBody3D` too. Or you should change the type of `ArcaneBolt` to `RigidBody3D`.

I agree that the wording of the error can be misinterpreted as referencing to the script of the node which is instantiated that other scene, I'll fix it.

**Comment by LennDG** [comment]
Thank you! I did have `ArcaneBolt` as a KinematicBody previously and missed that it changed to a `CharacterBody`.
