### ISSUE TITLE
Reordering scripts

### ISSUE THREAD

**Issue by Tybobobo** [godotengine/godot#6688]
We should be able to sort the scripts as we please.

![](http://i.imgur.com/hyEqmPp.png)

Currently, we cannot change the ordering of the scripts. 
I wish for the ability to (ctrl+up/ ctrl+down) reorder the scripts in order to organize them better, in a similar way we can with nodes in tree view.

**Comment by ret80** [comment]
It is not clear that this will ?! This is just a list of the open script editor.

**Comment by bojidar-bg** [comment]
Duplicate of #4775, sorry

**Comment by Tybobobo** [comment]
Tried to search for script reorder or list, but I could not find anything. Glad to see it already exists :)
