### ISSUE TITLE
There is no way of creating a usable Texture3D from code

### ISSUE THREAD

**Issue by rumbogs** [godotengine/godot#66881]
### Godot version

4.0.dev

### System information

MacOS, Radeon Pro 560X

### Issue description

I'm trying to create a volume texture dynamically but I can't find any recommended way to create a Texture3D to send to the shader.

This is the script attached to the mesh instance:
```
func _ready():
       var noise = FastNoiseLite.new()
	
	noise.seed = randi()
	noise.noise_type = 1
	noise.frequency = 0.1
	
	var img = noise.get_seamless_image(64, 64, false, true)
	var img_array = []
	for i in range(5):
		img_array.append(img)
	
        # If I use the RenderingServer it works, see below image
	#var tex3D = RenderingServer.texture_3d_create(img.get_format(), 64, 64, 5, false, img_array)
        # Using the ImageTexture3D resource is rendering a simple 1x1x1 Magenta texture (which I suspect is the default one)
	var tex3D = ImageTexture3D.new()
        # This create call doesn't seem to attach the newly created texture to the tex3D instance
	tex3D.create(img.get_format(), 64, 64, 5, false, img_array)
	mat.set_shader_parameter("texture3d", tex3D)
```
ImageTexture3D 👇 
<img width="571" alt="Screenshot 2022-10-04 at 17 08 58" src="https://user-images.githubusercontent.com/9051832/193843061-83be7f85-21b4-4bdf-90dd-837185015566.png">

RenderingServer 👇 
<img width="571" alt="Screenshot 2022-10-04 at 17 09 20" src="https://user-images.githubusercontent.com/9051832/193843153-72201804-5913-4d65-89b5-6f11dd73d214.png">

Shader code:
```
shader_type spatial;

uniform sampler3D texture3d: filter_nearest, repeat_enable;

void fragment() {
	ALBEDO = texture(texture3d, vec3(UV, 0.1)).rgb;
}
```

Similarly I'm not sure what the FogMaterial diffuse_texture accepts since using a dynamically created ImageTexture3D doesn't seem to do anything.

### Steps to reproduce

Create a simple scene with a Mesh to attach the script and shader material to, a default WorldEnvironment and a Camera.

**Comment by clayjohn** [comment]
This is a very odd bug, I was able to confirm it locally. But I was also able to fix the issue by adding a call to ``tex3d.get_rid()`` before creating the texture in other words, this works:
```
	var tex3D = ImageTexture3D.new()
	print(tex3D.get_rid())
	tex3D.create(img.get_format(), 64, 64, 5, false, img_array)
	mat.set_shader_parameter("texture3d", tex3D)
```
