### ISSUE TITLE
Add metadata parsing functions for audio and video streams

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#6689]
Follow-up on #3214 that implemented it for OGG Vorbis streams, but it should be done as far as possible for all audio and video stream we support that provide such metadata.

See #3214 for a reference implementation.

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the.. oh hey Akien :)

I guess this is not yet implemented?

**Comment by akien-mga** [comment]
Yep, this is still missing. For video at least, we plan to move decoding to GDNative plugins, so the metadata parsing would likely come from those too.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
