### ISSUE TITLE
Clicking on `res://` folder is very slow

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#66901]
### Godot version

0056acf

### System information

Windows 10 x64

### Issue description

When you click `res://` folder in filesystem dock, it hangs the editor for a few seconds:
![godot_96GEUSbke2](https://user-images.githubusercontent.com/2223172/193903101-d0a7d395-9a17-4642-a49c-724833f6e723.gif)
(this is release build)

### Steps to reproduce

1. Click `res://`
2. 🥶

**Comment by Mickeon** [comment]
It may be a regression of Tree itself, but I can't figure this one out. There's a lot of slow calls happening specifically when selecting the root TreeItem, and it may only be most noticeable on the FileSystem because there's a lot of... TreeItems.

**Comment by KoBeWi** [comment]
Doesn't seem to be happening anymore.

**Comment by KoBeWi** [comment]
No it's still happening, but it's not obvious. You need to click another folder first and then right-click the res://. Subsequent clicks don't cause freeze.

**Comment by radlotus** [comment]
I noticed that in Godot 4 selecting a TreeItem causes a huge spike in "Physics Time" in the Profiler unlike in Godot 3.
The Tree node is significantly slower in Godot 4 than in Godot 3.

**Comment by Maran23** [comment]
This also happens with the scene tree editor, not even a big one. 
I agree to @radlotus, the tree is significantly slower and feels more sluggish on Godot 4.
So the task would be to find and improve the performance bottlenecks of `Tree`/`TreeItem` in general.

**Comment by Zireael07** [comment]
I've been feeling that the remote tree is more sluggish in 4 than in 3.x, and kept wondering why. This looks like it might be the culprit...

**Comment by KoBeWi** [comment]
Regression from #41242
Clicking `res://` will recursively scan every file in the project.
