### ISSUE TITLE
Godot 4: missing `ProjectSettings`:`property_get_revert`

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#66900]
### Godot version

v4.0.beta2.official [f8745f2f7]

### System information

Windows10

### Issue description

I used in my plugin (Godot 3.x) the functionallity of `ProjectSettings`:property_get_revert` to get the default value to prepare my own configuration dialoge.
I start migrating to Godot 4 and miss the function of ProjectSettings to get the default value.

### Steps to reproduce

ProjectSettings.set_initial_value("foo/bar", "default")

I have no option to get back the inital set default value.

**Comment by akien-mga** [comment]
It's now `_property_get_revert` with an underscore because it's a virtual method.
