### ISSUE TITLE
Assigning Skeleton2D to Polygon2D node breaks the display of the polygon

### ISSUE THREAD

**Issue by tomglenn** [godotengine/godot#66908]
### Godot version

4.0 Beta 2

### System information

Windows 11, NVidia RTX 3070, Forward+; Mac OS X Monterey M1 Pro Max, Forward+

### Issue description

When assigning a Skeleton2D node to a Polygon2D the polygon will either disappear completely or it will visually be glitched. Resizing the editor effects how it is displayed.

![image](https://user-images.githubusercontent.com/289945/193934724-2fca14fe-f4f3-41cb-9ac7-88b7cfe141f2.png)

![image](https://user-images.githubusercontent.com/289945/193934801-e8a59ee9-6484-4135-a63b-37395d7863aa.png)

Further to this, end bones do not respect their rotation in the UV editor window. (see hand bone in image below. First image is from the editor, second is from the UV editor)

![image](https://user-images.githubusercontent.com/289945/193935079-66ee7dbc-0f8b-4849-81c8-378adeb1d0a5.png)

![image](https://user-images.githubusercontent.com/289945/193935135-6cb5664f-8a52-4e11-b5b8-6ca53eb16c01.png)

### Steps to reproduce

- Create a character with a series of polygons as children of a Node2D. 
- Create a Skeleton2D as a sibling of the Polygons container node.
- Create all of the appropriate bones
- Assign the skeleton to one of the polygons
- Notice that it disappears or glitches

### Minimal reproduction project

[Uploading godot-2d-spine-test.zip…]()

**Comment by Calinou** [comment]
The minimal reproduction project didn't upload (likely because you clicked away from the text field while it was still uploading). Try editing your post and upload it again.
