### ISSUE TITLE
Issues with lighting on manualy rendered meshes

### ISSUE THREAD

**Issue by Pszemis** [godotengine/godot#66903]
### Godot version

4.0 beta 2

### System information

Windows 10

### Issue description

Hi, I've been playing around lately with making a Minecraft-like voxel engine in the latest Godot beta. I've encountered a strange issue though while generating the meshes. 

The lighting is all broken and not rendering properly. I've tried the exact same thing before on Gotod 3.x and it worked just fine.

I'm using a `SurfaceTool` method `add_triangle_fan()` to create my voxels and get the effect visible on the pictures. I thought the problem might have been connected to using the built-in `generate_normals()` method to get the normals, but I've tried passing them manually using the `add.triangle_fan()`, or `set_normal()`, `set_uv()`, and `add_vertex()` methods, but also with no luck. The end result that I got was exactly the same.

I'm using a default `DirectionalLight3D` node for lighting the scene.

Tested it both on beta 1 and 2 and got the same results on both.

Any ideas on what the issue might be caused by? Is this just a beta issue? I have found these two, but I don't think it's the same problem: #66618, #66639

![image](https://user-images.githubusercontent.com/44278544/193906654-24595241-b57e-46e7-a818-b40fd6377800.png)

![image](https://user-images.githubusercontent.com/44278544/193906662-8c461729-ba57-4466-838b-65cce791d837.png)

![image](https://user-images.githubusercontent.com/44278544/193906620-00727a00-767b-4924-a86f-2b82f4dd412c.png)

![image](https://user-images.githubusercontent.com/44278544/193906635-fcb66f53-d670-40a3-b03c-1b8806e89090.png)

### Steps to reproduce

1. Create a project and add a DirectionalLight3D node to it
2. Using code create a mesh with the SurfaceTool method - add_triangle_fan()
3. Observe the issue

**Comment by Calinou** [comment]
@Pszemis Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by Pszemis** [comment]
> This looks like it is just confusion with the new smooth groups API. Other users have been struggling with it to. `generate_normals()` takes into account the smooth group now, so if you don't specify a unique smooth group for each vertex, it will smooth normals for you.

Yep, this seems to be the main issue that I had. After specifying the smooth groups I have this now:

![100000](https://user-images.githubusercontent.com/44278544/194113213-9050a9da-583d-4ebc-8cfd-3515122186f8.png)

Definitely better than before. The lighting is still weird, as for some reason it seems that the top of the model doesn't get almost any light at all, but at least it's consistent.

I've tried using `OmniLight3D` positioned above the model instead to see what happens and got this:

![100001](https://user-images.githubusercontent.com/44278544/194113541-ded470a9-4da4-4fa3-9438-1527a54bf1b0.png)

This is how it would look without setting the smooth groups just for reference:

![image](https://user-images.githubusercontent.com/44278544/194114147-f55cefb1-6756-4855-a002-3bf7641d51c3.png)

And after combining the two light sources it looks like this:

![image](https://user-images.githubusercontent.com/44278544/194113693-bcb01d7f-d961-49d6-b0bd-de463aab6fce.png)


I still can't figure out how to use the `DirectonalLight3D` to light the scene up properly, but hey, the main issue is gone! Thanks a lot for the help, I greatly appreciate it :D

**Comment by Calinou** [comment]
> I still can't figure out how to use the DirectonalLight3D to light the scene up properly

The default rotation when creating a new DirectionalLight3D. is purely horizontal. You need to rotate the DirectionalLight3D node so it points (mostly) downwards instead.

**Comment by Pszemis** [comment]
Oh, great to know! Checked it just now and everything works like a charm. Once again, thanks a lot for your help, both of you! I'll close the issue.

![image](https://user-images.githubusercontent.com/44278544/194118314-47984985-580a-43fc-978c-4d8069414a6c.png)


![image](https://user-images.githubusercontent.com/44278544/194118207-d4247640-e93f-419c-82e6-5ef29bdff707.png)
