### ISSUE TITLE
AnimationPlayer's curve editor breaks when focusing a selection of constant keys (or a single key)

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#66924]
### Godot version

4.0 beta 2

### System information

linux

### Issue description

https://user-images.githubusercontent.com/71937306/194051380-5ce70a38-e5bf-4fe5-9db6-45f234075c4f.mp4

As you can see focusing (by pressing `F`):
 - several keyframes equal in value,
 - or a single keyframe

breaks the view, and

 - focusing a non-constant set of points fixes the view (`Ctrl+A, F` in the video)

N.B.: Focusing a selection of temporaly-aligned keyframes does not break the zoom.

Side note: I couldn't reproduce it but when discovering this I had another probably related problem: my 2D view was broken as well (neither axes nor rulers drawn, focusing selection did nothing). Turns out a few `nan`s were introduced somehow in my project's `.godot/editor/scene.tscn-editstate-xxx.cfg` file in the 2D view offset: `"ofs": Vector2(nan, nan),`.

### Steps to reproduce

1. create 2 keys with the same value on a bezier track
2. select them on curve editor
3. press F

**Comment by TokageItLab** [comment]
I remember the broken behavior for focus was a known issue. But it should be fixed at some point.
