### ISSUE TITLE
[4.0 beta 2] C# - Resource appears to have its ref count decreased when newed from C# via GDScript or returned from GDScript to C#

### ISSUE THREAD

**Issue by massycat** [godotengine/godot#66923]
### Godot version

v4.0.beta2.mono.official [f8745f2f7]

### System information

Windows 10

### Issue description

When a Resource is newed via a GDScript from C# or returned from a GDScript function called from C# the Resource's reference count appears to be getting decremented meaning that the Resource is freed before being returned to the C# code.

Expected result is that the Resource is available and usable from C# and only freed when the C# reference to it is no longer in use.

Note: similar C# code works as expected in Godot 3.5. Also the equivalent GDScript creation code works in Godot 4.0 beta 2.

### Steps to reproduce

Given the following GDScript Resource script:

```
extends Resource

@export var width: int
@export var height: int

func _notification(what):
	if what == NOTIFICATION_PREDELETE:
		print("I am dying...")
```

The following C# code will fail to create the Resource, note TestClass is the path to the GDScript file for the GDScript Resource above:

```
    public void _on_test_create()
    {
        GDScript myGDScript = (GDScript) GD.Load(TestClass);
        Godot.Object myGDScriptInstance = (Godot.Object) myGDScript.New();

        if (myGDScriptInstance is Resource asResource)
        {
            myGDScriptInstance.Set(m_WidthProperty, 20);
            myGDScriptInstance.Set(m_HeightProperty, 100);
            
            GD.Print("Created instance, set width to ", myGDScriptInstance.Get(m_WidthProperty), ", height to ", myGDScriptInstance.Get(m_HeightProperty));
        }
        else if (myGDScriptInstance is Node asNode)
        {
            GD.Print("Node created");
            AddChild(asNode);
        }
        else
        {
            GD.Print("What was created? The type is ", myGDScriptInstance.GetType());
        }
    }
```

"I am dying..." is outputted before the prints from the C# and myGDScriptInstance is Godot.Object rather Godot.Resource.

Similarly if the Resource is created and returned from a GDScript method, the Resource is freed before being passed back to C#.
Given the following GDScript that creates and returns same GDScript Resource as above:

```
extends Resource

@export_file("*.gd") var resource_class

func get_heightmap(do_reference : bool = false) -> Resource:
	var resource_script = ResourceLoader.load(resource_class)
	var new_instance = resource_script.new()
	
	for prop in new_instance.get_property_list():
		print("factory new instance prop: ", prop)
	
	if do_reference:
		new_instance.reference()
	
	return new_instance
```

The following C# code will not get the Resource back unless "addReference" is true:

```
    private Godot.Object GetFromFactory(bool addReference)
    {
        if (ResourceFactory == null)
        {
            GD.Print("ResourceFactory is not set");
            return null;
        }

        if (!ResourceFactory.HasMethod(k_GetHeightmapFnName))
        {
            GD.Print("ResourceFactory does not have \"", k_GetHeightmapFnName, "\" method");
            return null;
        }

        var heightmapVariant = ResourceFactory.Call(k_GetHeightmapFnName, addReference);

        if (heightmapVariant.VariantType != Variant.Type.Object)
        {
            GD.Print("ResourceFactory. ", k_GetHeightmapFnName, " returned variant type ", heightmapVariant.VariantType);
            return null;
        }

        var heightmap = (Godot.Object)heightmapVariant.AsGodotObject();
        
        GD.Print("Heightmap is type ", heightmap.GetType());

        foreach (var prop in heightmap.GetPropertyList())
        {
            GD.Print(prop);
        }

        return heightmap;
    }
```

### Minimal reproduction project

[TestSharpCreateBeta2.zip](https://github.com/godotengine/godot/files/9715169/TestSharpCreateBeta2.zip)

**Comment by RedworkDE** [comment]
The MRP is no super clear about what is wrong and what should be the correct behavior, but as far as I can tell this no longer happens on master and the GDScript and C# bits now do the exact same thing, except that `Create Resource from CSharp` doesn't print the dying message immediately because of GC.

Was likely fixed by #72654
