### ISSUE TITLE
array.resize() weird behavior (Godot 3.5)

### ISSUE THREAD

**Issue by Lexazan** [godotengine/godot#66939]
### Godot version

3.5.stable

### System information

Windows 10

### Issue description

Hi, 
I am having strange issues with array.resize(), please have a look at the example below

### Steps to reproduce

```gdscript
        var a = Array()
	a.resize(3)
	print(a)
	# Output: [Null, Null, Null]

	a.fill([])
	print(a)
	# Output: [[], [], []]

	for i in a.size():
		a[i].resize(i+2)
		print(a[i])
	# Output:	
        # [Null, Null]
        # [Null, Null, Null]
        # [Null, Null, Null, Null]

	print(a)
	# Actual output:
        # [[Null, Null, Null, Null], [Null, Null, Null, Null], [Null, Null, Null, Null]]
	# Expected:
        # [[Null, Null], [Null, Null, Null], [Null, Null, Null, Null]]`
```

**Comment by Calinou** [comment]
PS: Code blocks should use triple backticks like this (with an optional language name for syntax highlighting):

\`\`\`gdscript
code here
\`\`\`

I edited your post accordingly, but remember to do this in the future :slightly_smiling_face:

**Comment by lawnjelly** [comment]
Hazard a guess it has filled the array with the same reference from `[]`. Therefore the most recent resize affects them all. You could test this by placing something in the array and see if it appears in all three.

**Comment by Lexazan** [comment]
> Hazard a guess it has filled the array with the same reference from `[]`. Therefore the most recent resize affects them all. You could test this by placing something in the array and see if it appears in all three.
> 
> This is a common gotcha in gdscript and responsible for huge amounts of bugs, it copies things by COW (kind of like by reference) by default, rather than by value.
> 
> However, I'm unsure why resizing isn't triggering the COW (copy on write). 🤔 So maybe there is more to this.

Yeap, you are right, changing 
```gdscript
a.fill([])
```

to 

```gdscript
for i in a.size():
		a[i] = []
```

did the trick, thank you!

**Comment by lawnjelly** [comment]
There still could be a bug, as calling resize on each element should be causing copy on write to kick in, afaik, so each becomes unique. Maybe there is a reason why it is not. Does need checking.

**Comment by Lexazan** [comment]
Ok, will keep open it for now, maybe someone could take a look

**Comment by lawnjelly** [comment]
A little look reveals `Array` is a thin holder for a ref counted `ArrayPrivate`, which contains the data. The data is stored as a `Vector` (which uses COW) but it looks like the `Array` itself is resistant to duplication, and probably only duplicating when you call the `duplicate()` function explicitly.

So, a bit strange and a gotcha, but not a bug.

**Comment by Lexazan** [comment]
Great, thanks for checking!
