### ISSUE TITLE
Cannot create CustomTooltip in C# SourceCode

### ISSUE THREAD

**Issue by BestMovement** [godotengine/godot#66933]
### Godot version

4.0 beta2 .NET6 Build

### System information

Windows10 GTX 1060 3GB Vulkan

### Issue description

When creating a custom Tooltip on the Editor
GDScript works fine using documentation comments

![gd_comm](https://user-images.githubusercontent.com/73213136/194086939-f53fff62-66df-4520-ad3d-d533f1c4dee6.png)

But in C# even if you write a documentation comment
Custom tooltips are not created.

![cs_comm](https://user-images.githubusercontent.com/73213136/194087600-ee69ac9a-1d4e-4544-ac0f-fa06a27e9551.png)

### Steps to reproduce

1.Create new project

2.Add one node on the scene.

3.Attach CDScript to the added node

4.If I write a script like the image tooltip works

![gd_comm](https://user-images.githubusercontent.com/73213136/194089034-822c558c-6c33-4134-96af-84252c862f40.png)

5.Next, the GDScript attached to the Node is Replace with C#Code

6.If I write the code like the image I wrote a DocumentComment Tooltips don't work.

![cs_comm](https://user-images.githubusercontent.com/73213136/194090766-a3f39a43-cdb7-40a0-b3b0-d65141078241.png)

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot-proposals/issues/5672.
