### ISSUE TITLE
`Engine.editor_hint` is always invalid

### ISSUE THREAD

**Issue by TheYellowArchitect** [godotengine/godot#66943]
### Godot version

4.0 beta2

### System information

Artix (Arch Linux without systemd), NVIDIA GTX-1050 Ti

### Issue description

`Engine._editor_hint` is a boolean value which returns true if on the editor, false if non-editor. Problem is, it doesn't work at all. It does compile without error, but whenever it checks against that logic in runtime, it gives invalid index error.

![engine-editor-hint2](https://user-images.githubusercontent.com/25630803/194126683-9fcbe7d8-f907-4d20-97b2-c0e16373d81c.png)

### Steps to reproduce

- Create a new/empty project
- Create any kind of node
- Attach a script to it
- Copy-paste this code:

```
extends Node2D

func _ready():
	if not Engine.editor_hint:
		print("This never reaches here lol")
```
- Play/Run the scene

### Minimal reproduction project

See above. Just copypaste the code into 1 script lol

**Comment by gongpha** [comment]
In 4.0, the `editor_hint` property was replaced with `is_editor_hint` method which returns boolean too.
```gdscript
print(Engine.is_editor_hint())
```

**Comment by TheYellowArchitect** [comment]
`is_editor_hint` does work. If indeed it replaced `editor_hint` why is `editor_hint` even a choice? I thank you for fixing my mini bug, but anyway, I will keep this issue open until `editor_hint` is completely removed, because the user/coder will be baited by this

**Comment by TheYellowArchitect** [comment]
@akien-mga the compilation error is on runtime. This should be caught in compiling/saving.
