### ISSUE TITLE
const dictionary results in a invalid Parse Error

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#66969]
### Godot version

v4.0.beta2.official [f8745f2f7]

### System information

all

### Issue description

Run into this issue during migrate my plugin from Godot3 to Godot4
I build a mapping between notification constants and human readable messages and run into this issue
```
const NOTIFICATION_AS_STRING_MAPPINGS := {
	TYPE_OBJECT: {
		Object.NOTIFICATION_POSTINITIALIZE : "POSTINITIALIZE",
		Object.NOTIFICATION_PREDELETE: "PREDELETE",
		MainLoop.NOTIFICATION_WM_MOUSE_ENTER: "WM_MOUSE_ENTER",
	}
}
```
res://testScene.gd:3 - Parse Error: Initializer for a constant must be a constant expression.

The problem is related to constant `MainLoop.NOTIFICATION_WM_MOUSE_ENTER`
If you replace it by there value `1002` no error occurs.
And the constant is moved in Godot4 from 
`MainLoop.NOTIFICATION_WM_MOUSE_ENTER` to `Node.NOTIFICATION_WM_MOUSE_ENTER`

**The error is missleading, it should be the constant `MainLoop.NOTIFICATION_WM_MOUSE_ENTER` not exists.**

### Steps to reproduce

create a new script and add this code

is failing
```
const NOTIFICATION_AS_STRING_MAPPINGS := {
	TYPE_OBJECT: {
		Object.NOTIFICATION_POSTINITIALIZE : "POSTINITIALIZE",
		Object.NOTIFICATION_PREDELETE: "PREDELETE",
		MainLoop.NOTIFICATION_WM_MOUSE_ENTER: "WM_MOUSE_ENTER",
	}
}
```

it works
```
const NOTIFICATION_AS_STRING_MAPPINGS := {
	TYPE_OBJECT: {
		Object.NOTIFICATION_POSTINITIALIZE : "POSTINITIALIZE",
		Object.NOTIFICATION_PREDELETE: "PREDELETE",
		Node.NOTIFICATION_WM_MOUSE_ENTER: "WM_MOUSE_ENTER",
	}
}
```

should work in both cases

**Comment by dalexeev** [comment]
> The error is missleading, it should be the constant `MainLoop.NOTIFICATION_WM_MOUSE_ENTER` not exists.

In 4.0.3 and master the error order is correct, so I think this issue can be considered resolved.

![](https://github.com/godotengine/godot/assets/47700418/6d631b16-a5aa-49df-ac2c-bd852e719b77)

See also https://github.com/godotengine/godot/issues/75052#issuecomment-1612654819. In some cases the order may be different, and this can be misleading, as the first error is the most noticeable.
