### ISSUE TITLE
Godot 4 beta Navmesh not working

### ISSUE THREAD

**Issue by CommandAlakazam** [godotengine/godot#66960]
### Godot version

4.0beta1, 4.0beta2

### System information

macOS Mojave, NVIDIA GeForce 750M 1GB, Vulkan

### Issue description

Hello all! I'm pretty new to programming, but have been learning over the past year. I'm having an issue getting a navmesh to work in 4.0 at all! I've tried three different scripts from tutorials on youtube, and can't seem to figure out what the issue is... I've tried this with a meshinstance3d, a Gridmap, and Csgboxes under the NavigationRegion3d, all with the same issue...All I'm trying to do is get the npc to follow the player. Any help would be super useful!!!

Also, I'm seeing other people's navmesh's look like one solid object, but mine is triangulated looking? not sure if that's an issue, or what that is really, and insight on that would be nice as well

this script in particular was adapted from FunctionElectrical87
https://www.reddit.com/user/FunctionElectrical87/
https://www.reddit.com/r/godot/comments/wuznk5/navigationagent3d_cannot_find_target_in_godot_40/ for the for the npc character

The output prints the "Target is no reachable :-(" message. I also posted some extra readouts from the script if that's helpful...

### Steps to reproduce

```extends CharacterBody3D


@onready var navigation_agent: NavigationAgent3D = $NavigationAgent3D


@export var movement_speed = 4
@export var player : Node3D
@export var nav : NavigationRegion3D 


var speed = 2

func _ready():
	print("get_world_3d().navigation_map ", get_world_3d().navigation_map)
	
#	NavigationServer3D.agent_set_map(navigation_agent.get_rid(), get_world_3d().navigation_map)

	print("agent RID: ", navigation_agent.get_rid())
	print("nav: ", nav)
	print("region RID: ", nav.get_region_rid())
	print("nav RID alt: ", nav.get_world_3d().navigation_map)

#	var nav_rid = nav.get_region_rid()
#	navigation_agent.set_navigation_map(nav_rid)
	navigation_agent.set_target_location(player.global_transform.origin)
	print("maps: ", NavigationServer3D.get_maps())
	print("agent map: ", navigation_agent.get_navigation_map())
	
	
	if not navigation_agent.is_target_reachable():
		print("Target is no reachable :-(")

# Called every frame. 'delta' is the elapsed time since the previous frame.
func _physics_process(delta):
	var next_path_position : Vector3 = navigation_agent.get_next_location()
	var current_agent_position : Vector3 = global_transform.origin
	var new_velocity : Vector3 = (next_path_position - current_agent_position).normalized() * movement_speed
	navigation_agent.set_velocity(new_velocity)
	
	print("global_transform.origin: ", global_transform.origin)
	print("player.global_transform.origin: ", player.global_transform.origin)
	print("next_path_position: ", next_path_position)
	print("current_agent_position: ", current_agent_position)
	print("new_velocity: ", new_velocity)

	navigation_agent.target_reached
	
	move_and_slide()

func _on_navigation_agent_3d_velocity_computed(safe_velocity):
	print("safe_velocity: ", safe_velocity)
	velocity = safe_velocity
	#move_and_slide()
```

**Comment by smix8** [comment]
@CommandAlakazam Could you solve this issue?

**Comment by smix8** [comment]
I guess this can be closed, the server sync is documented and that path queries in _ready() functions do not work cause the navigation map is still unsyned and empty.
