### ISSUE TITLE
After to open godot: application frozen and without response using jack2

### ISSUE THREAD

**Issue by ryukinix** [godotengine/godot#6696]
# Device

| OS            | GODOT | DE   | LINUX   |
|---------------|-------|------|---------|
| Manjaro Linux | 2.1   | XFCE | 4.7.5-1 |

# Description
After open the godot the windows stay unresponsive and seems nothing can be done here. The `-debug` flag just doesn't works too :(.

I use `strace` to get the stack dataflow, that is the log: http://sprunge.us/jKUB

# How to reproduce
1. Install `jack2-dbus`
2. Run `jack_control start`
3. Run `godot`
![bug](http://i.imgur.com/BfnhkiA.png)

Any thoughts?

**Comment by ryukinix** [comment]
Seems related with the jack2-dbus service whose I use for real-time (low latency) programs about audio production. I use cadence that makes a bridge with the pulseaudio service, but unfortunally the godot don't works :(

**Comment by ryukinix** [comment]
Well, this is really weird. Instead using the `godot-git` version from [AUR](https://aur.archlinux.org/packages/godot-git/) and use the release version (binaries) of official website works. Why? (?!?)

This solves the first problem, but would be great a explanation for that if someone knows... I need comment something on the AUR page too.

**Comment by freemanfromgodotengine** [comment]
I use jackd server - but it's not running all the time as a main audio system - which is pulseaudio on my xubuntu 64-bit, and I don't have any problems with Godot. Maybe you can temporary disable jack and use pusleaudio only, in times you run Godot?

**Comment by ryukinix** [comment]
Well, the problem now is another thing... the godot runs with jackd without problems, but the version of AUR has some weird problem. I don't know why, but I think this is not problem of devs or jackd, probably. After all, installing the .deb package as the official binary distribution works fine here.

**Comment by bojidar-bg** [comment]
@ryukinix Maybe you can try building godot on your own from this repo (without AUR)?

**Comment by ryukinix** [comment]
Yes, I can try. I update the progress in soon.

**Comment by ryukinix** [comment]
I compiled the source from version 2.2-alpha. I don't have any problem related on our my initial description, so the problem is affected a older version attached on the AUR godot package. Because the devs already fixed this, I'll close that issue.
