### ISSUE TITLE
CharacterBody3D and StaticBody3D do not collide when using trimesh collision shape

### ISSUE THREAD

**Issue by Dizeeee** [godotengine/godot#66963]
### Godot version

4.0 Beta 2

### System information

Arch Linux, Forward+, R9 5900X, Radeon 6700XT

### Issue description

Not sure if this is intended behavior or not, but when using a trimesh collision shape on a `CharacterBody3D`, it isn't able to collide with static bodies using trimesh collision shapes. If this is intended, it might be a good idea to provide a warning to users if possible.

### Steps to reproduce

The minimal reproduction project shows the issue when you run it. You can fix it by replacing the character collision shape with a `CapsuleShape3D`.

### Minimal reproduction project

[gdtest.zip](https://github.com/godotengine/godot/files/9721444/gdtest.zip)

**Comment by Calinou** [comment]
CharacterBody3D does not support using trimesh collision shapes. Use primitive collision shapes instead (preferably) or convex collision shapes (but beware of [performance issues](https://github.com/godotengine/godot/issues/48587)).
