### ISSUE TITLE
Document emoji not being supported by the default project font

### ISSUE THREAD

**Issue by Th-eo** [godotengine/godot#66966]
### Godot version

v4.0.beta2.official [f8745f2f7]

### System information

Fedora Linux 35 (Workstation Edition), 64-bit, GNOME 41.6

### Issue description

After browsing issues like https://github.com/godotengine/godot/issues/49145#issuecomment-849857001, I found out that Godot 4 should've fixed emoji support in engine and in labels etc, but to my surprise they don't work in Fedora yet. I've tried downloading other people's projects with them and addons that should allow their support, but to no avail. They are rendered as cubes.

![image](https://user-images.githubusercontent.com/42318572/194232641-e9215da5-cc40-411b-8646-636a56f0c6e5.png)
When pasting this emoji: 😊

### Steps to reproduce

1. Create a label
2. Paste emojis into it such as 😊
3. No emoji displayed

### Minimal reproduction project

[emoji bug.zip](https://github.com/godotengine/godot/files/9721939/emoji.bug.zip)

**Comment by timothyqiu** [comment]
This is because the default font does not contain this emoji. Changing the font to Noto Color Emoji displays it correctly.

**Comment by Th-eo** [comment]
That font won't display them as colored emojis as you can see here, and it comes with the limitation of breaking non-emoji text. 
![image](https://user-images.githubusercontent.com/42318572/194248744-2ee7e6ff-5b78-4475-adbd-755ad9f82f11.png)

**Comment by timothyqiu** [comment]
Changing the font override in the MRP works for me:

![ksnip_20221006-155452](https://user-images.githubusercontent.com/372476/194249881-82e43867-3bdb-48fc-8d9d-0d05c7e08271.png)

As you can see, the font preview is already monochrome in your screenshot. So I think there's probably something wrong with the font or font configuration.

**Comment by bruvzg** [comment]
Only bitmap emoji fonts are supported (e.g., Noto Emoji), SVG in OT fonts are not (e.g., Twitter Color Emoji, see also https://github.com/godotengine/godot/pull/64530 for implementation draft, currently unfinished due to issues with SVG rendering library).

**Comment by Zireael07** [comment]
BTW I think it's unrelated to your distro, just a matter of Godot's default font?

**Comment by bruvzg** [comment]
> I think it's unrelated to your distro, just a matter of Godot's default font?

System fonts are not used by default, as well distro FreeType (in official builds), so it's not (if Godot is installed from distro package, it might use system FreeType and have some additional limitations).

**Comment by Calinou** [comment]
Can we display a node configuration warning if the label's text contains any characters that aren't found with the current font?
