### ISSUE TITLE
RandomNumberGenerator is constructed with a fixed seed, but documentation states it is randomized

### ISSUE THREAD

**Issue by jtnicholl** [godotengine/godot#66989]
### Godot version

v4.0.beta.custom_build [0c23a2cfe]

### System information

Fedora 36

### Issue description

When constructing an RNG with `RandomNumberGenerator.new()`, the seed is always set to `-6398989897141750821`.
However, according to its classref description:

> The default values of seed and state properties are pseudo-random

Either the documentation needs to be fixed, or this is a bug that needs to be fixed, I'm not sure which. The GlobalScope random number generator is randomized implicitly now in 4.0, so I thought maybe the intention was for this to be too?

### Steps to reproduce

```gdscript
var random := RandomNumberGenerator.new()
print(random.seed)
print(random.state)
```
Prints `-6398989897141750821` and `-6332740101472756719` every time, even when constructing several generators.

**Comment by Zireael07** [comment]
IIRC you need to call random.randomize() for it to be pseudo-random. Badly written docs I guess?

**Comment by Calinou** [comment]
The global RandomNumberGenerator instance uses a random seed by default since 4.0, but I guess this wasn't done for custom RandomNumberGenerator instances (I don't know why).

**Comment by jtnicholl** [comment]
If the seed being randomized automatically isn't the intended behavior IMO it should be, I think that's the more common use case. And even when you don't want a random seed, you're going to manually set a seed anyway, not use whatever arbitrary one is the default.
I guess you could argue it's wasteful for performance to generate a random seed then overwrite it, but I doubt that's significant. If it's really an issue there could be static factory method `get_seeded` that skips the randomization.
