### ISSUE TITLE
Wrong signature for `folder_moved` signal of `FileSystemDock`

### ISSUE THREAD

**Issue by HolonProduction** [godotengine/godot#66990]
### Godot version

v4.0.beta2.official [f8745f2f7]

### System information

Windows

### Issue description

The signal `folder_moved` has the following signature:
```swift
folder_moved(String old_folder, String new_file)
```
when it should be
```swift
folder_moved(String old_folder, String new_folder)
```

(In addition #62354 points out, that the signal `files_moved` should in fact be named `file_moved`. Can be fixed together.)

### Steps to reproduce

--

**Comment by KoBeWi** [comment]
> (In addition https://github.com/godotengine/godot/issues/62354 points out, that the signal files_moved should in fact be named file_moved. Can be fixed together.)

Note that this would break compatibility (although it's minor breakage, so probably still ok)

**Comment by mateuseap** [comment]
Can you assign this issue to me and tell me more about it? Thanks :)

**Comment by akien-mga** [comment]
We don't assign issues outside of project maintainers, but you're very welcome to make a PR for this.

You'd have to rename the parameter of the `folder_moved` signal in `editor/filesystem_dock.cpp` as suggested, and possibly also rename `files_moved` (and its uses, search in all files) a suggested.

**Comment by mateuseap** [comment]
I'll work on it ASAP and open my PR! Thank you for the guidance
