### ISSUE TITLE
GDExtension: Some EditorNode3DGizmoPlugin virtual functions are not being called

### ISSUE THREAD

**Issue by alessandrofama** [godotengine/godot#66992]
### Godot version

v4.0.beta.custom_build.fc926eda1 

### System information

macOS 12.3

### Issue description

Porting an EditorNode3DGizmoPlugin to GDExtension (godot-cpp), I noticed when overriding `EditorNode3DGizmoPlugin::_get_gizmo_name` that Godot still prints:
```
WARNING: A 3D editor gizmo has no name defined (it will appear as "Unnamed Gizmo" in the "View > Gizmos" menu). To resolve this, override the `_get_gizmo_name` function to return a String in the script that extends EditorNode3DGizmoPlugin.
```

This should happen [here](https://github.com/godotengine/godot/blob/0056acf46fc88757cae9d9f6fe9805f0eec1cd09/editor/plugins/node_3d_editor_gizmos.cpp#L1014-L1021).  Haven't check in the debugger yet, and I will update the issue when I do, but I guess/intuition says the `if (get_script_instance() && get_script_instance()->has_method("_get_gizmo_name"))` check returns false. 

If this is correct this also applies to `EditorNode3DGizmoPlugin::_get_priority`. The gizmo still works fine and the other functions all seem to call `GDVIRTUAL_CALL` instead of calling the method in the script instance.

### Steps to reproduce

Create a simple EditorNode3DGizmoPlugin with godot-cpp:

```
class TestGizmo : public EditorNode3DGizmoPlugin
{
    GDCLASS(TestGizmo, EditorNode3DGizmoPlugin);

  protected:
    static void _bind_methods() {}

  public:
    virtual String _get_gizmo_name() const override
    {
        return "TestGizmo";
    }
};
```

Add it to project with `add_node_3d_gizmo_plugin` in an EditorPlugin (GDScript). Restart the editor and notice the warning produced by Godot. The gizmo will be unnamed.

**Comment by Zylann** [comment]
Can you check if `ClassDB::get_virtual_func` is called with your function name? In `godot_cpp/src/core/class_db.cpp`

**Comment by alessandrofama** [comment]
Ah, so that function basically needs to change to 
```
String EditorNode3DGizmoPlugin::get_gizmo_name() const {
    String ret;
    if (GDVIRTUAL_CALL(_get_gizmo_name, ret)) {
        return ret;
    }

[...]
```
? I will try this out and see if it works. Don't know how GDVIRTUAL works, but was wondering why all other functions but `get_gizmo_name` and `get_priority` were calling it. Good time to learn something new about the engine :-)
