### ISSUE TITLE
PopupMenus are centered in single window mode (DisplayServer regression)

### ISSUE THREAD

**Issue by Ryhon0** [godotengine/godot#66996]
### Godot version

4.0 beta 2 mono

### System information

Arch Linux

### Issue description

When PopupMenus are opened in the editor, they are positioned in the center of the window. Does not occur with single window mode disabled

### Steps to reproduce

- Open a project 
- Enable single window mode and restart
- Open a PopupMenu by pressing a MenuButton or right clicking something

**Comment by Ryhon0** [comment]
Also just noticed it prints this error when it opens: `scene/main/window.cpp:1270 - Window 0 spawned at invalid position: (63, 36).`

**Comment by Calinou** [comment]
If you can compile from source, build the latest `master` branch which includes https://github.com/godotengine/godot/pull/66712 to confirm whether it fixes the issue :slightly_smiling_face:

**Comment by Ryhon0** [comment]
Compiled the master branch and it's fixed
