### ISSUE TITLE
Vulkan: Enabling SSR or SSS with TAA and XR enabled results in all geometry appearing completely black

### ISSUE THREAD

**Issue by CheesecakeCG** [godotengine/godot#66998]
### Godot version

v4.0.beta2.official

### System information

Arch Linux, Monado(XRT) 'v21.0.0-2508-gb5b832f61', Lenovo Explorer, KDE 5.25.5, NVIDIA GeForce GTX 1060 6GB, NVIDIA Driver 515.76 Kernel 5.19.12-zen1-1-zen

### Issue description

Enabling SSR or SSS with TAA and XR enabled results in all geometry appearing completely black, including objects with SSS disabled. I suspect there may be other features that trigger this.

These errors appear in the console when this occurs:
```
ERROR: Invalid color pass flag combination 14
   at: _render_list (servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp:526)
ERROR: Invalid color pass flag combination 13
   at: _render_list (servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp:526)
```

This issue is not a duplicate of #65864, I couldn't replicate their issue and SSR, SSS, and TAA are not used in their test project.

### Steps to reproduce

1. Enable TAA.
2. Add enable SSR or subsurface surface scattering on an object in view.
3. Start the project with XR enabled with an XR device connected.

### Minimal reproduction project

[VR Test Project (1).zip](https://github.com/godotengine/godot/files/9727764/VR.Test.Project.1.zip)

**Comment by BastiaanOlij** [comment]
I'll look into it when I have some free time, a lot of these effects have not been updated for stereoscopic rendering yet which is probably the issue here.

**Comment by clayjohn** [comment]
We a missing a permutation here:
https://github.com/godotengine/godot/blob/b8ed596769d2114797015833ce86f86ee872ecfa/servers/rendering/renderer_rd/forward_clustered/scene_shader_forward_clustered.cpp#L535-L541

It should include:
```
valid_color_pass_pipelines.insert(PIPELINE_COLOR_PASS_FLAG_SEPARATE_SPECULAR | PIPELINE_COLOR_PASS_FLAG_MULTIVIEW | PIPELINE_COLOR_PASS_FLAG_MOTION_VECTORS);
```
