### ISSUE TITLE
C#: Area3D node error calling from signal "input_event" - Method not found

### ISSUE THREAD

**Issue by BrandonGillis** [godotengine/godot#67009]
### Godot version

v4.0.beta2.mono.official [f8745f2f7]

### System information

Windows 11 x64

### Issue description

I made a simple 3D Scene with an Area3D node to detect mouse movement with a CollisionShape3D. 
When registering the `input_event` signal inside a C# script and I hover my mouse over the CollisionShape it try to fire the `input_event` signal but doesn't find the method associated to it and spam this error :

```
E 0:00:00:0910   emit_signalp: Error calling from signal 'input_event' to callable: 'Area3D(Area3d.cs)::_on_area_3d_input_event': Method not found..
  <Source C++>   core/object/object.cpp:1057 @ emit_signalp()
```

### Steps to reproduce

1. Download the minimal reproduction project below
2. There's one C# script on the Area3D node with the `input_event` signal binded to it with the following code :

```c#
using Godot;
using System;

public partial class Area3d : Area3D
{
	private void _on_area_3d_input_event(object camera, object @event, Vector3 position, Vector3 normal, int shape_idx)
	{
		GD.Print("collision event");
	}
}
````

3. Run the game and move your mouse inside the game.
4. You should be spammed inside the debugger with this error :
![image](https://user-images.githubusercontent.com/27730101/194438684-eb79aa7b-6b46-48a0-8501-5c22aa902434.png)

### Minimal reproduction project

[Area3DInputEventBug.zip](https://github.com/godotengine/godot/files/9729299/Area3DInputEventBug.zip)

**Comment by akien-mga** [comment]
CC @godotengine/dotnet 

Didn't check but a potential cause of this error is if the callback parameters don't properly match what is expected by the signal. I don't know if `object` is valid here or if it should be further specified.

If this is the problem, we really need to improve the error message to point out when the method _name_ is correct but the signature isn't.

**Comment by BrandonGillis** [comment]
To add some details the signature of the current method is the one generated automatically from the Godot editor

**Comment by raulsntos** [comment]
Signals only support 64-bit types so the `int` parameter should be `long`. The `object` parameter also looks weird because we no longer support `System.Object` it likely should be `Godot.Variant`.

**Comment by BrandonGillis** [comment]
I confirm that updating the method signature to the following fix the `method not found` error :

````c#
	private void _on_area_3d_input_event(Variant camera, Variant @event, Vector3 position, Vector3 normal, long shape_idx)
	{
		GD.Print("collision event");
	}
````

Things to improve :
- Error message as @akien-mga suggested, this is not really a `method not found` but a signature issue.
- The generated signature from Godot Editor when connecting a signal 

![Animation](https://user-images.githubusercontent.com/27730101/194528532-4477d786-6dcd-4aa6-a62e-0a5e9153cd85.gif)

**Comment by raulsntos** [comment]
We used `System.Object` (now `Godot.Variant`) when we don't know or can't figure out what the type is, in this case it seems we should be able to provide more concrete types though from the core API.

For the `int` parameter, it likely works in this case because internally the signal is emitted using an `int` but in other cases it may not so we have to assume it's a `long` unless otherwise specified and the core API right now doesn't specify this for signals or virtual methods (see https://github.com/godotengine/godot-proposals/issues/5403#issuecomment-1248674837).

**Comment by BrandonGillis** [comment]
Should we split the `method not found` into another issue or is it ok to keep it in this one?

I would like to try fixing that one if it's ok, as I think it would be a nice candidate for a first contribution

**Comment by raulsntos** [comment]
There is an open issue we can use to track that: https://github.com/godotengine/godot/issues/35910
