### ISSUE TITLE
Export to telegram gaming platform

### ISSUE THREAD

**Issue by techtonik** [godotengine/godot#6700]
https://telegram.org/blog/games

For that, Godot needs three things:
1. tell if current game is exportable
2. tell what to fix if it is non-exportable 
3. export template

**Comment by punto-** [comment]
This is html5 on mobile? does it run native games too? what is a 'bot'?

**Comment by techtonik** [comment]
`bot` is a program that responds to you in chat, such as IRC channel. It is no different from normal user, except that it is programmed for responses. Bots often have names to distinguish them normal users. https://en.wikipedia.org/wiki/IRC_bot

From what I see this is safe HTML5 subset that can run on mobile, desktop and in browser.

It won't run native games, because this way it won't be crossplatform.

**Comment by vnen** [comment]
Considering the current state of Godot's HTML5 export, I doubt this is even possible. It's hard (if possible) to make a C++ engine run seamlessly in JavaScript. Also, I don't know if Telegram support WebGL, which is a mandatory requirement for at least trying.

**Comment by techtonik** [comment]
It is plain HTML5, so everything that could be run in a browser, including WebGL, should run there.

C++ engine could have modular structure, with ability to combine different modules in language independent manner, making sure that behavior is the same and communication is as fast as possible for target platform. This way people could gradually port reference modules to their own native platform. Ideally. It should be possible, because GDScript is not C++.

**Comment by punto-** [comment]
presumably they run the native browser as a component inside their app, so
if that supports webgl it should work, but until webassembly works on
phones, it'll probably not be worth it (has anybody tested something
exported to html5 on mobile?)

**Comment by akien-mga** [comment]
I tested an html5 export of Minilens on FirefoxOS, and it did not perform well (IIRC it didn't even start, just crashed after a time). But it's not the most stable testing platform either :P

**Comment by freemanfromgodotengine** [comment]
I was once trying to run my creation in the browser and at first it crashed, then it decided to run after a long loading process - can't remember maybe I switched from Firefox to Chromium in between - but it was not a great experience at all.

**Comment by akien-mga** [comment]
The current WebAssembly templates by @eska014 work pretty decently on smartphones, so I guess it's doable.

Is there anything specific to do for this platform as far as exporting goes, or does supporting it just means having working HTML5 builds? If the latter, I guess we can close this issue, we have many other issues keeping track of the work on the HTML5 platform.

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
Checking this issue again, I don't think this is going to be worked on in the near future. If some contributors have interest in this platform and can document what needs to be done to support this platform, it could be considered further.

**Comment by tavurth** [comment]
This would be interesting to try out, I guess the HTML5 export templates are really getting there (even editor in browser now).

Probably better to wait until the Vulcan release to prevent re-fixing many bugs if there are any.
