### ISSUE TITLE
PopupPanel closes when game window loses focus, even when the popup_window flag is disabled

### ISSUE THREAD

**Issue by freelancer42** [godotengine/godot#67005]
### Godot version

4.0.beta2

### System information

Windows 11

### Issue description

When showing a PopupPanel with the popup_window flag disabled, the panel remains visible even when you click outside it (but still inside the main game window). However, if the main game window loses focus (for example if you press Alt+Tab or click on the Windows task bar), the panel disappears.

The expected behavior, based on common sense and the tooltip hint for the popup_window flag, is that the panel should remain visible even when the game window loses focus. The game environment should not be altered based on the game window's focus in the operating system, unless the developer explicitly says it should.

### Steps to reproduce

Add a PopupPanel with some content and set the popup_window flag to off/disabled/false. Then show the panel, for example with get_node("PopupPanel").show() (both show() and popup() have the same result in this case). Click around anywhere inside the game window and notice that the panel remains visble. Then click outside the game window or press Alt+Tab and notice that the panel disappears.

### Minimal reproduction project

[popuppanel_test.zip](https://github.com/godotengine/godot/files/9728876/popuppanel_test.zip)

**Comment by freelancer42** [comment]
Curiously this affects the editor as well (even when the game is not running). When I'm editing a scene with a PopupPanel and the editor loses focus, the PopupPanel node gets hidden. A bit annoying when I want it to be visible by default in the scene :)

**Comment by bruvzg** [comment]
`popup_window` flag is controlling global mouse input hook for the non-embedded windows, which will close the window if you click outside the app, the rest of auto-closing behavior (focus loss, escape press etc.) is implemented in the `Popup` itself.
Auto closing is the only thing that differentiate `Popup` from the generic `Window` so it doesn't make much sense to disable it.
Probably `popup_window` should be hidden for the popup to avoid confusion.

**Comment by bruvzg** [comment]
> When I'm editing a scene with a PopupPanel and the editor loses focus, the PopupPanel node gets hidden. A bit annoying when I want it to be visible by default in the scene :)

This part is definitely a bug.

**Comment by freelancer42** [comment]
Fair enough, I'll switch to using Window instead. For some reason I had the impression that was an abstract class, not sure where I got that from. Seems to be working fine for me though.

I'm not sure the popup_window flag should be hidden from popups though, because it does still affect the behavior when clicking inside the game window. Maybe the description for the flag could be updated instead to explain this behavior?
