### ISSUE TITLE
Adding a material overlay to a mesh causes it to cast shadows from omni and spotlights regardless of cast_shadow property setting

### ISSUE THREAD

**Issue by TheWoodenTree** [godotengine/godot#67014]
### Godot version

v4.0.beta2.official

### System information

Windows 10, Vulkan, GeForce GTX 1070 driver ver. 512.15

### Issue description

When adding a material overlay to a mesh that is being lit up by an omnilight or directional light and has with cast_shadow set to off, the mesh behaves as if cast_shadow is set to on even it is set to off in the inspector.

The expected behavior is for the mesh to obey the cast_shadow property and not cast a shadow, regardless of what the material overlay is set to. Directional light behaves as expected.

![example](https://user-images.githubusercontent.com/94566175/194467150-16e3e707-b8d8-46c6-a927-5e2560291b26.png)

### Steps to reproduce

Create a new mesh as a backdrop
Create a new mesh to obscure a light and set cast_shadow to "off"
Place an omnilight or spotlight that shines on the mesh and enable shadows
Create a new StandardMaterial3D in the material overlay slot and observe as a shadow appears

### Minimal reproduction project

[Test Project.zip](https://github.com/godotengine/godot/files/9730617/Test.Project.zip)

**Comment by akien-mga** [comment]
Note that issues should be fixed only when the PR fixing them is merged. Otherwise if the PR never gets merged, the issue would never get fixed.

**Comment by TheWoodenTree** [comment]
Ah ok, my bad
