### ISSUE TITLE
Custom mono build crashing unless ran through terminal on Windows

### ISSUE THREAD

**Issue by bitmammoth** [godotengine/godot#67017]
### Godot version

v4.0.beta.custom_build.f8745f2f7 

### System information

Windows 11

### Issue description

Editor crashes when running from build executable directly but when ran from terminal with .\godot.windows.tools.x86_64.exe the build runs normally.

 Output from terminal:
Godot Engine v4.0.beta.custom_build.f8745f2f7 - https://godotengine.org
ERROR: Condition "!windows.has(p_window)" is true.
   at: VulkanContext::window_resize (drivers\vulkan\vulkan_context.cpp:1497)
Vulkan API 1.2.0 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3090 Ti

WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
     at: _editor_init (modules\gltf\register_types.cpp:75)
WARNING: FBX file import is enabled in the project settings, but no FBX2glTF path is configured in the editor settings. FBX files will not be imported.
     at: _editor_init (modules\gltf\register_types.cpp:99)
     

### Steps to reproduce

Build mono executable from source with Net 6.0 release and steps followed from #65936 solution found at the bottom.

run from clicking on the .exe it will crash but if launched from the terminal with .\godot.windows.tools.x86_64.exe it functions fine until restart.

### Minimal reproduction project

Not really possible since it's from compiled source code let me know how else I can help.

**Comment by bitmammoth** [comment]
really weird just realized this is not a mono build and I repeated those steps exactly...

**Comment by bitmammoth** [comment]
Could the build target be incorrect sometimes? 

![image](https://user-images.githubusercontent.com/21980039/194483417-e66a81db-15d2-4da0-bf81-2781990ecdef.png)

**Comment by akien-mga** [comment]
You're probably running the wrong .exe, the filenames changed recently. It should have `editor` in its name.

**Comment by bitmammoth** [comment]
> You're probably running the wrong .exe, the filenames changed recently. It should have `editor` in its name.

oh very interesting I will have a look :) Are there any recommended commands I can use to save time? The current mono process seems a bit convoluted. I would be happy to help with some form of documentation on this topic.

**Comment by bitmammoth** [comment]
the only difference in the naming convention that show up with those commands are "tools" and "opt"

 but from my recall is the opt a template? It has been a while since building in version 4.

**Comment by akien-mga** [comment]
Nevermind, I see you're on an older commit. The naming changed a week ago.

**Comment by bitmammoth** [comment]
> Nevermind, I see you're on an older commit. The naming changed a week ago.
Yes I tried to build this from the source commit/dev snapshot of beta 2

**Comment by RedworkDE** [comment]
Is this still an issue? Also see the updated docs for compiling with .NET: https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_with_dotnet.html

If yes, please post all the commands you used to build godot and the resulting binaries for investigation.

**Comment by YuriSizov** [comment]
Closing this due to the lack of response and as a likely user error. Can be reopened if there is more information provided.
