### ISSUE TITLE
Visual Studio can't open Godot 4 C# solution on Mac OSX 12.5

### ISSUE THREAD

**Issue by thomasdorone** [godotengine/godot#67029]
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

Godot 4 beta 2

### System information

Macbook pro OSX 12.5, 

### Issue description

Hi,

Visual studio on mac can't open the solution an throws this error:
<img width="353" alt="Screen Shot 2022-10-07 at 5 19 58 PM" src="https://user-images.githubusercontent.com/104303630/194576382-8299898f-b485-4a14-a259-43294e971134.png">

I have the latest version of visual studio and .net 6 framework installed

### Steps to reproduce

Create a C# file in Godot and open it either from Godot or opening the solution through visual studio.

**Comment by irmantus** [comment]
Tested on v4.0.beta3.mono.official [01ae26d31] , issue still exists.

**Comment by thomasdorone** [comment]
Same here.... same error

**Comment by MrZak-dev** [comment]
Still exist with Godot 4.0.1 stable and Visual Studio 17.5.

**Comment by FrostBird347** [comment]
Comparing and swapping lines from a godot 3.0 project has revealed that the issue is caused by this part within the .csproj file: `Sdk="Godot.NET.Sdk/4.0.2"`.

Replacing it with `Sdk="Godot.NET.Sdk/3.3.0"` worked for me, however I didn't test it beyond seeing it appear as a supported solution because doing that would undoubtably cause other issues.

**Comment by FrostBird347** [comment]
On my system, the folder `~/.nuget/packages/godot.net.sdk` contains the SDKs for 3.3.0 and 4.0.2, however I have noticed some interesting differences between visual studio's behaviour with the two versions when it's removed:

|   | Using 3.3.0 | Using 4.0.2 |
| ------------- | ------------- | ------------- |
| SDK installed  | The project loads | ![fail2](https://user-images.githubusercontent.com/39435218/236662997-6bf8a931-218f-4c6e-9d71-201dba0fe2d9.png) |
| SDK removed  | ![fail](https://user-images.githubusercontent.com/39435218/236662739-33986c75-f81a-4a44-92f6-5353f3026701.png) | ![fail2](https://user-images.githubusercontent.com/39435218/236662997-6bf8a931-218f-4c6e-9d71-201dba0fe2d9.png) |

**Comment by FrostBird347** [comment]
Removing line 6 from `~/.nuget/packages/godot.net.sdk/4.0.2/Sdk/Sdk.targets` will make the project load correctly
![1](https://user-images.githubusercontent.com/39435218/236838081-94b7a42c-5027-4ef0-9cc2-4b360c8f7148.png)

However, you then face the issue of nothing being found
![2](https://user-images.githubusercontent.com/39435218/236838647-536b5bdf-dfe8-4083-b22a-b82dab8442cb.png)

**Comment by Tuckertcs** [comment]
> Removing line 6 from `~/.nuget/packages/godot.net.sdk/4.0.2/Sdk/Sdk.targets` will make the project load ![1](https://user-images.githubusercontent.com/39435218/236838081-94b7a42c-5027-4ef0-9cc2-4b360c8f7148.png)
> 
> However, you then face the issue of nothing being found ![2](https://user-images.githubusercontent.com/39435218/236838647-536b5bdf-dfe8-4083-b22a-b82dab8442cb.png)

If by "project load" you mean that you're able to build and run your game, I removing line 6 didn't work for me. If by "project load" you mean you're able to open the project in the Godot editor, then I've been able to do that with or without removing line 6.

I have noticed that deleting my `.csproj` and `.sln` files allows me to run the game (in the editor), but it's using the last successfully built version.

**Comment by Tuckertcs** [comment]
I may have found a solution (or at least a fix that just circumvents the real problem).

Open the text file: `/home/tucker/.nuget/NuGet/NuGet.Config`. It should look like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="Package source 1" value="Sayers.SDL2.Core" />
    <add key="Package source 2" value="Sayers.SDL2.Core" />
  </packageSources>
</configuration>
```

Edit it to remove (or comment out) the two SDL2 lines:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <!--<add key="Package source 1" value="Sayers.SDL2.Core" />-->
    <!--<add key="Package source 2" value="Sayers.SDL2.Core" />-->
  </packageSources>
</configuration>
```

The project now builds and runs successfully, reflecting your latest code changes.

Not sure why this works, but it does.

**Comment by FrostBird347** [comment]
> If by "project load" you mean that you're able to build and run your game, removing line 6 didn't work for me. If by "project load" you mean you're able to open the project in the Godot editor, then I've been able to do that with or without removing line 6.

By "project load" I was meaning having the project open in visual studio without the unknown solution item type error. I can open projects in godot, use the inbuilt editor and compile it from within godot, the issue is visual studio not recognising the project.




> I may have found a solution (or at least a fix that just circumvents the real problem).
> 
> Open the text file: `/home/USERNAME/.nuget/NuGet/NuGet.Config`. It should look like this:
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <configuration>
>   <packageSources>
>     <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
>     <add key="Package source 1" value="Sayers.SDL2.Core" />
>     <add key="Package source 2" value="Sayers.SDL2.Core" />
>   </packageSources>
> </configuration>
> ```
> 
> Edit it to remove (or comment out) the two SDL2 lines:
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <configuration>
>   <packageSources>
>     <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
>     
>     
>   </packageSources>
> </configuration>
> ```
> 
> The project now builds and runs successfully, reflecting your latest code changes.
> 
> Not sure why this works, but it does.

Unfortunately my nuget config file already looks like the fixed version you provided:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
</configuration>
```
I suspect that you were experiencing another unrelated issue, caused by those lines in your nuget config file that prevented godot from building the project.

**Comment by raulsntos** [comment]
Do you have the [Godot addin](https://github.com/godotengine/godot-monodevelop-addin) installed? It seems to be required so _Visual Studio for Mac_ can recognized the Project Type Guid `{8F3E2DF0-C35C-4265-82FC-BEA011F4A7ED}` (which is the Guid for Godot projects).

**Comment by FrostBird347** [comment]
> Do you have the [Godot addin](https://github.com/godotengine/godot-monodevelop-addin) installed? It seems to be required so _Visual Studio for Mac_ can recognized the Project Type Guid `{8F3E2DF0-C35C-4265-82FC-BEA011F4A7ED}` (which is the Guid for Godot projects).

Yes, I have the addin installed. I made sure by uninstalling the addin I had already installed, downloading the latest release from the repo you linked and manually installing it, to find the issue still present.
The issue is that the addin does not support godot 4.x projects.

**Comment by caimantilla** [comment]
Well, seeing as VS Mac is being discontinued next year, I'd guess this'll never be fixed?

**Comment by caimantilla** [comment]
> Well, seeing as VS Mac is being discontinued next year, I'd guess this'll never be fixed?

well rider is expensive so im glad i was wrong. thanks @Nomad1

**Comment by sdrib** [comment]
I know this is fixed, but it's not available in any builds yet (that I could find). If you want to use VS 2022 in `4.1.1` you will have to manually apply the changes yourself. (you could also build `4.2` - that is more complicated)

Steps: 
1. Go to `~/.nuget/packages/godot.net.sdk/4.1.1/Sdk`
2. Edit `Sdk.props` and `Sdk.targets` like done in the commit that fixed this issue https://github.com/godotengine/godot/commit/d65d379d22ee24593843d28800eec1fd446d1dd3

👍
