### ISSUE TITLE
Can't post to the Godot community forum

### ISSUE THREAD

**Issue by thomasdorone** [godotengine/godot#67022]
### Godot version

3.5

### System information

Mac osx 12.5

### Issue description

Hi,
I know it's not the right place to post it.
I already asked 3 questions in the Godot community forum but they are still pending for approval for more than 72h!! So I am unable to ask questions there or create another account... Can somebody tell me what's wrong?
Thank you

### Steps to reproduce

Post a question in the Q&A section...

**Comment by clayjohn** [comment]
The Godot github issue list is for tracking engine bugs only. At the top of the Godot forums there is a [big button that says "Help/Contact"](https://godotforums.org/p/1-contact) Please use that to seek support from the forum maintainers

**Comment by Calinou** [comment]
Approvals on Q&A website are done by volunteer moderators, so it can take a few days for posts to be approved. This is a necessary measure we had to add to combat spam, which is still an unresolved problem on Question2Answer-based websites.
