### ISSUE TITLE
"Keep Screen On" not working as expected on Android

### ISSUE THREAD

**Issue by ehsanngp** [godotengine/godot#67034]
### Godot version

4.0 Beta 2

### System information

Ubuntu 16.04

### Issue description

**Keep Screen On** option in **Project Settings > Display > Window** has no effect on exported Android builds. The issue was present from the first **Alpha** release of Godot 4.0 that I tested (**4.0 Alpha 6**)

### Steps to reproduce

1. Create a mobile project, got to **Project Settings > Display > Window**. Check **Keep Screen On** option. 
2. Export and run the project on Android device. 
3. The screen turns off after default screen timeout of Android.

**Comment by Calinou** [comment]
Keep Screen On is supposed to be implemented on Android: https://github.com/godotengine/godot/issues/18683

Does it work in 3.5?

**Comment by ehsanngp** [comment]
Have not tested it on Godot 3.5 since but was working on 3.2 as I remember.
I have tested this particular bug on Android 10 & 11, both on **Xiaomi Mi A3**.

I can test on other devices too, but as far as I have searched by **grep**, I could not find any known implementation of "**Keep Screen On**" not on **XML** nor **Java** part of compiled templates, so my best guess is that there should be basically absent from generated code somehow.

**Comment by Calinou** [comment]
https://github.com/godotengine/godot/blob/2846ea1ffafddfc447036b37d255f72cb278b677/platform/android/java/lib/src/org/godotengine/godot/Godot.java#L319-L327

https://github.com/godotengine/godot/blob/2846ea1ffafddfc447036b37d255f72cb278b677/platform/android/java/lib/src/org/godotengine/godot/Godot.java#L302

I wonder why "True" has an uppercase "T" here…

**Comment by ehsanngp** [comment]
> 

That should be the root ...

**Comment by ehsanngp** [comment]
> Relevant source code:
> 
> https://github.com/godotengine/godot/blob/2846ea1ffafddfc447036b37d255f72cb278b677/platform/android/java/lib/src/org/godotengine/godot/Godot.java#L319-L327
> 
> https://github.com/godotengine/godot/blob/2846ea1ffafddfc447036b37d255f72cb278b677/platform/android/java/lib/src/org/godotengine/godot/Godot.java#L302
> 
> I wonder why "True" has an uppercase "T" here…

That should be the root ...

**Comment by akien-mga** [comment]
> https://github.com/godotengine/godot/blob/2846ea1ffafddfc447036b37d255f72cb278b677/platform/android/java/lib/src/org/godotengine/godot/Godot.java#L302
>
> I wonder why "True" has an uppercase "T" here…

Seems like `getGlobal()` in Java always returns a string and not a Variant, so it depends on the Variant to String conversion.
```
JNIEXPORT jstring JNICALL Java_org_godotengine_godot_GodotLib_getGlobal(JNIEnv *env, jclass clazz, jstring path) {
        String js = jstring_to_string(path, env);

        return env->NewStringUTF(GLOBAL_GET(js).operator String().utf8().get_data());
}
```

We used the print booleans as `True` and `False`, and this changed in Godot 4.0, so this code is now broken.

It's pretty brittle to rely on such String conversion, but I imagine it's not easy / worth the effort to reimplement a Variant equivalent in Java just for this.

**Comment by RendersJens** [comment]
> We used the print booleans as `True` and `False`, and this changed in Godot 4.0, so this code is now broken.
> 
> It's pretty brittle to rely on such String conversion, but I imagine it's not easy / worth the effort to reimplement a Variant equivalent in Java just for this.

Ah so since Godot 4.0, the string representation of bools has changed? This kind of bug could quickly be avoided by replacing the hard coded "True" with the similar conversion of the Godot bool `true` to string then, e.g. another output of getGlobal?

**Comment by akien-mga** [comment]
Yes just changing `"True"` to `"true"` in the code Calinou linked should be sufficient. If you can test it, then feel free to make a PR with that fix.

And checking the only other use of `getGlobal`, I found the reason for #68048 too, I'll make a PR to fix both.
