### ISSUE TITLE
Lights do not scale

### ISSUE THREAD

**Issue by viktor-ferenczi** [godotengine/godot#67058]
### Godot version

Godot 4 beta 2

### System information

Windows 10, Vulkan

### Issue description

The radius and size of omni and spot lights do not scale.

This limits the reusability of sub-scenes with lights in them to scenarios when they are not scaled, otherwise the lighting will change in unexpected ways.

### Steps to reproduce

Create a sub-scene. Place some meshes and an omni or spot light into it.
Instantiate the sub-scene in a top level scene multiple times and scale them differently:
<img width="1920" alt="LightsDoNotScale" src="https://user-images.githubusercontent.com/1848514/194677796-efac297f-de83-4573-942a-a227b12a883e.png">

### Minimal reproduction project

[LightsDoNotScale.zip](https://github.com/godotengine/godot/files/9737974/LightsDoNotScale.zip)

**Comment by fire** [comment]
See https://github.com/godotengine/godot/pull/65493 if this pr helps you understand how to scale.

**Comment by Calinou** [comment]
Note that we aren't certain whether scaling lights is actually desired. Only uniform scaling could be supported, and this could create issues with the light clustering almgorithm.

We may just have to document this limitation.

**Comment by viktor-ferenczi** [comment]
There should be warnings in the documentation right at the size/range fields (like `omni_range` and `light_size`) affected. Both for OmniLight3D and SpotLight3D.
