### ISSUE TITLE
Scripts stored as plain text in android export

### ISSUE THREAD

**Issue by dorjoosoft** [godotengine/godot#67069]
### Godot version

v4.0.beta2.official [f8745f2f7]

### System information

Windows 10, Vulkan

### Issue description

Exporting for android resulted "apk" package contains plain text scripts regardless of selecting "Compiled Bytecode" on GDScript export mode menu.

### Steps to reproduce

1- Create a simple project including a scene and attach a script with some line of codes.
2- In Export dialog add android export preset and from Resources tab select "Compiled Bytecode" on GDScript export mode menu.
3- Export the project to apk package.
4- Extract resulted apk to a folder and locate your script file in extracted files.
5- Your script is stored as plain text.

**Comment by Zireael07** [comment]
See https://github.com/godotengine/godot/issues/66091
