### ISSUE TITLE
3D Material .duplicate() method is not duplicating all properties/parameters

### ISSUE THREAD

**Issue by Dabnabbit** [godotengine/godot#67092]
### Godot version

4.0.dev

### System information

Windows 11, RTX 3070TI, GLES3

### Issue description

When attempting to create a duplicate material of a MeshInstance3D, the material.duplicate() method appears to work properly, however, it throws errors in the Debugger when 'queue_free()' is executed on a meshinstance with a duplicated material. This behavior does not occur if the material is not duplicated.

Error messages:

```
E 0:00:02:0561   material_casts_shadows: Condition "!material" is true. Returning: true
  <C++ Source>   servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2676 @ material_casts_shadows()
[MaterialBugProject.zip](https://github.com/godotengine/godot/files/9742003/MaterialBugProject.zip)

E 0:00:02:0561   material_is_animated: Condition "!material" is true. Returning: false
  <C++ Source>   servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2663 @ material_is_animated()
E 0:00:02:0561   material_get_instance_shader_parameters: Condition "!material" is true.
  <C++ Source>   servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2689 @ material_get_instance_shader_parameters()
E 0:00:02:0561   material_update_dependency: Condition "!material" is true.
  <C++ Source>   servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2701 @ material_update_dependency()

```

### Steps to reproduce

Instantiate a scene object that contains a mesh with a material assigned to it.
Get the meshinstance3d object of the instantiation.
Get the material of the meshinstance3d, and utilize the .duplicate() method to create a copy of the material
Reassign the duplicate material to the meshinstance3d override material
call queue_free() on the instance to remove it, which will result in errors thrown stating that parameters are missing from the duplicate material.

### Minimal reproduction project

In the main scene, there is a bool variable option to enable or disable the material duplication. It is enabled by default which will throw the errors in the debugger, disabling duplication will mean all instances share the same material, but will not throw errors.

_No response_
[MaterialBugProject.zip](https://github.com/godotengine/godot/files/9742006/MaterialBugProject.zip)

**Comment by Calinou** [comment]
@Dabnabbit Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by Dabnabbit** [comment]
> 

Working on that now, actually having some issues replicating in a smaller project; I'm running down some possibilities though, it may be related to the mesh being from a .blend file as opposed to a standard mesh3d primitive, which seems to get and duplicate the material fine... will come back to this after replicating in isolation.

**Comment by Dabnabbit** [comment]
> 
@Calinou There we go, I updated the issue/ticket to more accurately reflect exactly what is happening, created a minimal project, and updated the steps to reproduce. I made a boolean var in the main scene to toggle the error on and off by enabling or disabling the duplication of materials, but it is enabled by default, which will through debug errors.

**Comment by akien-mga** [comment]
Did you intend to close this issue? If so, why?

**Comment by Dabnabbit** [comment]
> 

@akien-mga I closed this and opened a more accurate ticket, due to misunderstanding what was generating the error originally.
New Issue Ticket: https://github.com/godotengine/godot/issues/67144
