### ISSUE TITLE
Vulkan: CanvasGroup does not work on mobile backend

### ISSUE THREAD

**Issue by Ghashy** [godotengine/godot#67096]
### Godot version

4.0 beta 2

### System information

Macbook Pro M1, Big Sur 11.7, vulkan

### Issue description

When changing the type of node to CanvasGroup, it spams in output, and causes some graphic issues:

<img width="680" alt="Screenshot 2022-10-08 at 23 47 45" src="https://user-images.githubusercontent.com/109857267/194727447-a5b6ada4-b218-4449-9bb5-d8131205aeae.png">
<img width="967" alt="Screenshot 2022-10-08 at 23 47 13" src="https://user-images.githubusercontent.com/109857267/194727448-11a41044-1e01-41a8-affa-494545c34b6a.png">

### Steps to reproduce

Open the attached project, and try to change type of "Shadow" node from Node2D to CanvasGroup.

### Minimal reproduction project

[CanvasGropupBug.zip](https://github.com/godotengine/godot/files/9740239/CanvasGropupBug.zip)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/49198.
