### ISSUE TITLE
Layout mode disappears randomly

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#67095]
### Godot version

4.0 880a017

### System information

Windows 10 x64

### Issue description

I keep getting this kind of diffs all the time:
![image](https://user-images.githubusercontent.com/2223172/194727086-6dcd94e3-775e-485c-9d9e-9aa631dcb6b0.png)
Happens randomly (might be related to project load with last opened scenes?) and re-saving the scene changes it back.

### Steps to reproduce

idk, it just happens

**Comment by akien-mga** [comment]
Reading the code, it doesn't seem to be meant to be saved at all, that's weird.
I saw several users mention that issue on Twitter (but also without steps to reproduce).

**Comment by lmurray** [comment]
The Control class contains quite a few properties that are not "authoritative" at all times due to the value of other properties but they are still always serialized. This results in undefined values being serialized only to be discarded when deserialized as they are unused. I'm not able to maintain a PR for this but I've tried the following patch on my fork and it seems to work for me, however I have custom modifications to this class so the patch may not apply cleanly and the logic will need to be reviewed.

```diff
-------------------- scene/gui/control.cpp --------------------
index d1ae37ea..03240ee4 100644
@@ -475,6 +475,7 @@ void Control::_validate_property(PropertyInfo &p_property) const {
 		// Disable force pass if the control is not stopping the event.
 		if (data.mouse_filter != MOUSE_FILTER_STOP) {
 			p_property.usage |= PROPERTY_USAGE_READ_ONLY;
+			p_property.usage &= ~PROPERTY_USAGE_STORAGE;
 		}
 	}
 
@@ -485,29 +486,40 @@ void Control::_validate_property(PropertyInfo &p_property) const {
 	// Validate which positioning properties should be displayed depending on the parent and the layout mode.
 	Node *parent_node = get_parent_control();
 	if (!parent_node) {
-		// If there is no parent, display both anchor and container options.
+		// If the parent is not a Control, display both anchor and container
+		// options. This is very important if this Control is the root of a
+		// scene as there is no way to know how the scene will be used.
 
 		// Set the layout mode to be disabled with the proper value.
 		if (p_property.name == "layout_mode") {
 			p_property.hint_string = "Position,Anchors,Container,Uncontrolled";
 			p_property.usage |= PROPERTY_USAGE_READ_ONLY;
+			p_property.usage &= ~PROPERTY_USAGE_STORAGE;
 		}
 
 		// Use the layout mode to display or hide advanced anchoring properties.
 		bool use_custom_anchors = _get_anchors_layout_preset() == -1; // Custom "preset".
-		if (!use_custom_anchors && (p_property.name.begins_with("anchor_") || p_property.name.begins_with("offset_") || p_property.name.begins_with("grow_"))) {
-			p_property.usage ^= PROPERTY_USAGE_EDITOR;
+		if (!use_custom_anchors) {
+			if (p_property.name.begins_with("anchor_") || p_property.name.begins_with("grow_")) {
+				p_property.usage &= ~(PROPERTY_USAGE_EDITOR | PROPERTY_USAGE_STORAGE);
+			} else if (p_property.name.begins_with("offset_")) {
+				// Don't remove PROPERTY_USAGE_STORAGE here as these properties
+				// are the authoritative source of layout information even if
+				// they are hidden in the editor for usability purposes.
+				p_property.usage &= ~PROPERTY_USAGE_EDITOR;
+			}
 		}
 	} else if (Object::cast_to<Container>(parent_node)) {
-		// If the parent is a container, display only container-related properties.
+		// If the parent is a Container, display only container-related properties.
 		if (p_property.name.begins_with("anchor_") || p_property.name.begins_with("offset_") || p_property.name.begins_with("grow_") || p_property.name == "anchors_preset" ||
 				p_property.name == "position" || p_property.name == "rotation" || p_property.name == "scale" || p_property.name == "size" || p_property.name == "pivot_offset") {
-			p_property.usage ^= PROPERTY_USAGE_EDITOR;
+			p_property.usage &= ~(PROPERTY_USAGE_EDITOR | PROPERTY_USAGE_STORAGE);
 
 		} else if (p_property.name == "layout_mode") {
 			// Set the layout mode to be disabled with the proper value.
 			p_property.hint_string = "Position,Anchors,Container,Uncontrolled";
 			p_property.usage |= PROPERTY_USAGE_READ_ONLY;
+			p_property.usage &= ~PROPERTY_USAGE_STORAGE;
 		} else if (p_property.name == "size_flags_horizontal" || p_property.name == "size_flags_vertical") {
 			// Filter allowed size flags based on the parent container configuration.
 			Container *parent_container = Object::cast_to<Container>(parent_node);
@@ -545,14 +557,16 @@ void Control::_validate_property(PropertyInfo &p_property) const {
 			if (hint_string.is_empty()) {
 				p_property.hint_string = "";
 				p_property.usage |= PROPERTY_USAGE_READ_ONLY;
+				p_property.usage &= ~PROPERTY_USAGE_STORAGE;
 			} else {
 				p_property.hint_string = hint_string;
 			}
 		}
 	} else {
-		// If the parent is NOT a container or not a control at all, display only anchoring-related properties.
+		// If the parent is a Control but not a Container, display only
+		// anchoring-related properties.
 		if (p_property.name.begins_with("size_flags_")) {
-			p_property.usage ^= PROPERTY_USAGE_EDITOR;
+			p_property.usage &= ~(PROPERTY_USAGE_EDITOR | PROPERTY_USAGE_STORAGE);
 
 		} else if (p_property.name == "layout_mode") {
 			// Set the layout mode to be enabled with proper options.
@@ -562,11 +576,18 @@ void Control::_validate_property(PropertyInfo &p_property) const {
 		// Use the layout mode to display or hide advanced anchoring properties.
 		bool use_anchors = _get_layout_mode() == LayoutMode::LAYOUT_MODE_ANCHORS;
 		if (!use_anchors && p_property.name == "anchors_preset") {
-			p_property.usage ^= PROPERTY_USAGE_EDITOR;
+			p_property.usage &= ~(PROPERTY_USAGE_EDITOR | PROPERTY_USAGE_STORAGE);
 		}
 		bool use_custom_anchors = use_anchors && _get_anchors_layout_preset() == -1; // Custom "preset".
-		if (!use_custom_anchors && (p_property.name.begins_with("anchor_") || p_property.name.begins_with("offset_") || p_property.name.begins_with("grow_"))) {
-			p_property.usage ^= PROPERTY_USAGE_EDITOR;
+		if (!use_custom_anchors) {
+			if (p_property.name.begins_with("anchor_") || p_property.name.begins_with("grow_")) {
+				p_property.usage &= ~(PROPERTY_USAGE_EDITOR | PROPERTY_USAGE_STORAGE);
+			} else if (p_property.name.begins_with("offset_")) {
+				// Don't remove PROPERTY_USAGE_STORAGE here as these properties
+				// are the authoritative source of layout information even if
+				// they are hidden in the editor for usability purposes.
+				p_property.usage &= ~PROPERTY_USAGE_EDITOR;
+			}
 		}
 	}
 
@@ -583,6 +604,7 @@ void Control::_validate_property(PropertyInfo &p_property) const {
 	}
 	if (property_is_managed_by_container) {
 		p_property.usage |= PROPERTY_USAGE_READ_ONLY;
+		p_property.usage &= ~PROPERTY_USAGE_STORAGE;
 	}
 }
 
```

**Comment by Cronos87** [comment]
> Reading the code, it doesn't seem to be meant to be saved at all, that's weird. I saw several users mention that issue on Twitter (but also without steps to reproduce).

I provided steps to reproduce it in my issue, but I didn't know this one exists. I paste it here.

### Steps to reproduce

1) Open the sample project and open the 2 scenes included inside `test_layout_mode` and `another_scene`.
2) Check that the property `layout_mode` exists in `test_layout_mode` for almost all nodes.
3) Go to the scene `another_scene` and run the current scene (see the image).
4) Go to the file `test_layout_mode.tscn` and you will notice that the property `layout_mode` disappear from nodes.

**Note:** If you have another scenes opened, the property will disappear as well. It seems like all scenes opened in the editor will be impacted, but not the ones closed.

![CleanShot 2022-10-09 at 14 17 07@2x](https://user-images.githubusercontent.com/1923206/194756424-8a604754-5fbf-422c-99cf-b7536a471f84.png)

Here's a video to illustrate it:

https://user-images.githubusercontent.com/1923206/194756160-4c159262-77aa-4c4b-9394-cf9483652858.mp4

**Comment by lmurray** [comment]
The above comments by @Cronos87 has reminded me that my comment above is only one part of the solution for this issue.

In addition to Control always serializing properties that contain unused values, the state of Control's layout logic depends on it being in the SceneTree which is not available for scenes opened in background tabs in the editor as only the active tab is actually attached to the SceneTree. These two things combined results in Control serializing different properties depending on whether or not it is the active tab in the editor when the scene is saved. I have not solved this second issue myself and my above patch may actually make things worse depending on the scene's contents even if it's a step in the right direction.

The above reproduction steps assume that the `run/auto_save/save_before_running` editor setting is enabled before attempting to run the scene. An alternative step is to use the "Scene -> Save All Scenes" main menu option.

**Comment by nerdbeard** [comment]
This has been vexing me for weeks and it's really helpful to have the explanation of what is happening and how to avoid it.  Thanks!

I don't know if this is helpful but I find that random changes of ``layout_mode`` are often accompanied by slight changes to ``offset_top`` and ``offset_bottom`` which also revert themselves when re-saved.

**Comment by lostminds** [comment]
I'm getting this as well, which is confusing and makes me worry something will break. In most cases it doesn't seem to change anything in the game, but I suspect it could have caused an issue where an instanced GUI scene got mangled and I had to remove it and re-instance it to fix it.

In my case there seems to be some cycle where `layout_mode` is either added, removed or changed between 1 and 3 by some process I don't know the origin of. Rarely there will also be changes to offset_* properties. This seems to affect either 2D scenes (different menus) that are open in the editor when the game is run or instanced in 3d scenes that are open (like my game overlay scene instanced in my main game scene) even though I have made no changes to the files in question, only changing scripts and running again.

In the case of the instanced scenes (I suspect this is the problem in my case) I also think it might be related to the scenes being instanced with "editable children". I have this enabled to be able to connect some signals to/from children in the UI scenes, but it seems to also add overrides to layouts even though I haven't changed any of those properties. Perhaps the editor is sometimes incorrectly adding or modifying these overrides?

**Comment by nerdbeard** [comment]
@lostminds -- I have learned a couple tips for negotiating this issue.

1) ``layout_mode`` should never be exported to a file in the first place.  Don't commit it to your version control.  I kill the hunks in magit.  Knowing this is helpful because it effectively ends the cycle, though you have to watch for it.

2) ``layout_mode`` is only exported in the scene that the Godot Editor currently has open and active.  If you have five scene tabs open in the Editor and do Save All, just the one that's currently selected will save out ``layout_mode`` lines.  By opening a different scene, you can use Save All to save the scene you were just working on without generating ``layout_mode`` entries in it.

**Comment by atirut-w** [comment]
I am using beta 7 with Git and this problem is starting to get on my nerves.

**Comment by nerdbeard** [comment]
Doesn't even look like it's on the radar for 4.0-final..!

**Comment by Calinou** [comment]
> Doesn't even look like it's on the radar for 4.0-final..!

Contributors work on a best-effort basis, so there is no ETA for fixing issues in general.

**Comment by dalexeev** [comment]
I opened PR #69860. Please test if it fixes the issue and doesn't cause any regressions.

**Comment by lmurray** [comment]
The PR does not solve this issue at all. This issue is not just that a single property changes when saved but rather the entire state of Control is invalid when it is attempted to be saved when it is not in the scene tree. See my two comments above.

**Comment by lmurray** [comment]
Thinking this issue through I think that the easiest way to solve this is to have Control cache what its parent situation is when it is added to the tree as a hidden property, and update it when its parent changes. This property is stored so that it can be remembered across reloads even if it is never attached to the scene tree (e.g. loaded directly into a background tab). There are three situations: Parented to a Container, parented to another Control, or either parented to any other node or not parented at all.

Doing this, as well as ensuring that only authoritative properties are actually stored (see my first comment above), should solve the issue completely (which affects more than just the `layout_mode` property) without requiring more in-depth changes to Godot core.

I'm not aware of any other Node that changes which properties it uses based on what other Node it is attached too.

**Comment by ashelleyPurdue** [comment]
If it's any help, I did some tests to help narrow down the issue a little bit.  You can find them in this repo:
https://github.com/ashelleyPurdue/GodotResaveTest

**Comment by YuriSizov** [comment]
@ashelleyPurdue Thanks for a thorough investigation, it's very helpful! The grow directions appearing is indeed a minor issue with the editor, for the rest I'll need to look into it more.
