### ISSUE TITLE
Godot 4 conversion tool also converts comments. Cool, but expected?

### ISSUE THREAD

**Issue by nightblade9** [godotengine/godot#67090]
### Godot version

4.0 beta 2

### System information

Linux, GLES3

### Issue description

When converting a project, the conversion tool converts things in comments. Observe the following comments:

```
# Grab the Sprite and do something.
# We can fix this with yield(tween, "tween_completed")
```

These get converted to:

```
# Grab the Sprite2D and do something.
# We can fix this with await tween.finished
```

(There are other cases, too). While this is cool in some cases (like correcting the tween syntax), it's unexpected.

### Steps to reproduce

- Create an empty project in Godot 3.5 with a scene, a node, and a GDscript file attached to it
- Add a bunch of comments using keywords that the conversion tool looks for
- Close 3.5, launch 4.0 beta 2, and import the project
- Agree to a full conversion
- Observe the comments changed

**Comment by Zireael07** [comment]
The conversion tool just runs a regex. For instance, if you have scripts or nodes named the same as renamed classes, it'll rename (mess em up) too.

**Comment by nightblade9** [comment]
That makes sense. I saw other things that fit that explanation (e.g. having custom `change_scene` methods change to `change_scene_to_file`.

I take it this is not a bug / not worth fixing, then?

**Comment by Zireael07** [comment]
IIRC there is a PR open that should improve matters slightly, but I'm not certain whether it makes the tool ignore comments

**Comment by Mickeon** [comment]
Some things are run with a regex, others are checked more laboriously, to every maintainer's dismay because it's really difficult to handle the converter's code as is now. Your case is also handled with a regex, but I've seen some more specific function conversions that do check if the function is within a comment.

**Comment by nightblade9** [comment]
I'm okay to close this as "too much effort and not worth fixing." Feel free to re-open if you think this is something that can and should be fixed in a subsequent iteration of Godot 4.

**Comment by Calinou** [comment]
https://github.com/godotengine/godot/pull/66150 will fix this issue.
