### ISSUE TITLE
Exporting a node to a subscene loses the custom values of exported variables

### ISSUE THREAD

**Issue by ippan** [godotengine/godot#671]
i am using commit: 89fa70706f9166765c3ac3f799225a467800f065

origin scene:
![2014-08-30 10 55 32](https://cloud.githubusercontent.com/assets/2070604/4097974/4b678ca0-2ff1-11e4-90a9-3cf7052c51b8.png)

convert to subscene:
![2014-08-30 10 55 57](https://cloud.githubusercontent.com/assets/2070604/4097975/5217896a-2ff1-11e4-8bcb-8f667078683e.png)
all script variables become default values

thank^^

**Comment by akien-mga** [comment]
Some work has been done on subscene editing, etc., so it would be nice to check if this issue is still valid in the current master branch.

**Comment by akien-mga** [comment]
Tested in the current master branch, the issue seems to be fixed.
