### ISSUE TITLE
Curved surfaces do not grow smoothly with StandardMaterial3D grow property

### ISSUE THREAD

**Issue by bepthomp** [godotengine/godot#67115]
### Godot version

4.beta2

### System information

Windows 10, Vulkan Forward + (and Mobile), Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz 2.21 GHz

### Issue description

The Grow property in StandardMaterial3D's do not produce smooth edges like it did in Godot 3.5. The edges are jagged and uneven
**Godot 4 Screenshot:**
![image](https://user-images.githubusercontent.com/36116447/194743393-b2c17c97-3bb2-453e-8cd8-7b7d00afcc87.png)

**Godot 3.5 Screenshot:**
![image](https://user-images.githubusercontent.com/36116447/194743438-274c9589-9185-48ee-9a31-fb04323d21ec.png)

### Steps to reproduce

**Reproduce from scratch:**
- Create a MeshInstance3D
- Select the mesh shape to be any shape with a curved surface
- Attach a StandardMaterial3D to the shape
- Change the Grow property and observe the jagged edges produced

**Reproduce from attached projects:**
- Open the GrowBugReport project in Godot 4.beta2
- Open main.tscn and observe the jagged edges produced by the material
- Open the Godot3-5Comparison project with Godot 3.5
- Open main.tcsn and observe that the Grow property is much smoother in this version

### Minimal reproduction project

[GrowBugReport.zip](https://github.com/godotengine/godot/files/9740948/GrowBugReport.zip)
[Godot3-5Comparison.zip](https://github.com/godotengine/godot/files/9740954/Godot3-5Comparison.zip)

**Comment by Calinou** [comment]
@_CHANGEME Can you reproduce this in any of the [4.0 alphas and betas](https://downloads.tuxfamily.org/godotengine/4.0/) to determine when the regression started?

**Comment by bepthomp** [comment]
@Calinou I've traced this regression back to alpha15, that seems to be when it started.

**Comment by bepthomp** [comment]
Oops I did not mean to close this.

**Comment by clayjohn** [comment]
Fixed by https://github.com/godotengine/godot/pull/68830
