### ISSUE TITLE
"Transient parent has another exclusive child." occurs when exporting build

### ISSUE THREAD

**Issue by Kacpergibas** [godotengine/godot#67122]
### Godot version

v4.0.beta2.official [f8745f2f7]

### System information

Windows 11 Insider Build (22623.730)

### Issue description

When i tried to export the build, i get "Transient parent has another exclusive child." error message,
even if we deleted the Godot settings folder.

It is unknown wherever it only caused me or everyone else

### Steps to reproduce

1. Either create an project, open an existing project supported by the engine version, or use the reproduction project below
2. Try export the build
3. Look up the "Transient parent has another exclusive child." error message

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/9741315/Test.zip)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/63770.

**Comment by Kacpergibas** [comment]
> Related to #63770.
> 
> Can you reproduce this after enabling **Single Window Mode** in the Editor Settings then restarting the editor?

I enabled it, then restarted, try to export again, and no luck, it still gives me an exact same error message.
What are the other solutions?

**Comment by Hearsay-Law** [comment]
Having the same issue.

**Comment by JMunkk** [comment]
Same issue here

**Comment by JMunkk** [comment]
@Hearsay-Law @Kacpergibas Updating from beta1 to beta2 appears to have solved the issue for me. Try that and see if that helps

**Comment by JA-Developer** [comment]
This is happening to me in Beta 3. Even after trying:

> Related to #63770.
> 
> Can you reproduce this after enabling **Single Window Mode** in the Editor Settings then restarting the editor?

**Comment by wilfregd** [comment]
Same thing here, I got this issue with beta2 and it's still happening with beta3, out of nowhere since I was able to use beta2 since it came out. In my case it happens when I create a new C# script or try to build the scripts.

**Comment by wilfregd** [comment]
Update: I managed to make it work through the building process and it doesn't stop anything anymore. No more error either.
For that, I simply updated the .NET SDK to the latest version.

**Comment by Calinou** [comment]
@Kacpergibas  Did you find a solution to this problem? If so, please document it here by commenting :slightly_smiling_face:

**Comment by Kacpergibas** [comment]
> @Kacpergibas Did you find a solution to this problem? If so, please document it here by commenting 🙂

@wilfregd managed to solve this problem by just updating .NET SDK to the latest version, does that work for you too.

**Comment by NumAniCloud** [comment]
This is still happening on my PC, even the latest .NET SDK/.NET Runtime installed. Now exact version I have is:

- .NET SDK 6.0.402
- .NET Runtime 6.0.10

My Godot version is `v4.0.beta3.mono.official` [01ae26d31].

**Comment by Kacpergibas** [comment]
Some users work, Some users don't, i don''t think i could find the solution here, This remains unfixed, unless it is fixed in future build

**Comment by Flash1232** [comment]
It happens for me on Linux with b6 on a non-Mono build. I'll re-open another issue with a sample ZIP when I get to it.

**Comment by Flash1232** [comment]
It happens even with an empty new project and independently of whether Single Window mode is enabled or not. Last tested on beta 8

```
ERROR: Transient parent has another exclusive child.
   at: set_visible (scene/main/window.cpp:473)
```

**Comment by L2750558108** [comment]
same issue here

**Comment by Ytachi1000** [comment]
same issue here

**Comment by 2BC-Jeremy** [comment]
I am also having a "Transient parent has another exclusive child" error.

I get this error with pre-compiled snap shots, and my own custom builds. Standard and Mono on Windows 10 x64. Standard on a Arch Linux Steam Deck. Done from completely blank projects. 

I also have it show up when I "Install from File" a _export_templates.tpz file, using the Export Template Manager.

Single Window Mode does not help.

Here is the Verbose output on using  v4.0.beta9.mono.official.e780dc332 on Windows 10 , when I get the error on "Install from File"
 https://pastebin.com/uDwBxTYA

Here is the Verbose output using v4.0.beta9.official.e780dc332 on Windows 10, on "Install from File"
https://pastebin.com/Zkpivg7C

**Comment by Flash1232** [comment]
@2BC-Jeremy maybe you could open a new issue with the log output as this issue is probably not being watched anymore.

**Comment by bruvzg** [comment]
`Transient parent has another exclusive child` the error is caused by the editor progress dialog. A window can have only one exclusive child, but in this case there are two: export dialog (or other dialog like "fix dependencies") and progress dialog (both are children of the main window).

The error should not cause any issues. It is an old and known issue, but there's probably no straightforward way to fix it without fully changing the behavior of editor progress dialog.

**Comment by barrrettt** [comment]
same beta11. when delete .godot folder

**Comment by ulvido** [comment]
> Related to #63770.
> 
> Can you reproduce this after enabling **Single Window Mode** in the Editor Settings then restarting the editor?

I wanted to use one click deploy and stumbled upon the same problem. `Single Window Mode` fixed it 🎉

**Godot Version:** 4.0.rc4

**Description:**
When I click "Remote Debug" button and select my phone, on my desktop screen some windows start to pop and close one after another and it never ends. I forced to close the on going error loop by cacthing a window and pressing x. After stopping the chaos, even though the errors, phone srceen shows the desired scene properly.

**This is the error log:**
![image](https://user-images.githubusercontent.com/27722274/221241566-1cc43d8d-aefd-421a-94a6-b15bf8ab6c24.png)

**machine specs:**
![image](https://user-images.githubusercontent.com/27722274/221243691-b2dc848e-b0ab-40d3-ac33-11b2b2514cc3.png)

**OS specs:**
![image](https://user-images.githubusercontent.com/27722274/221244062-1ffc0aab-3e5d-4980-a5b9-c54c6ad06fb9.png)

**phone specs:**
General Mobile GM9 Pro: an Andorid One phone
Android version: 9

**Comment by AgSmith95** [comment]
Hello, I had this issue when trying to export to Android and specifying "Export Path" to the directory, which didn't exist. I created a directory called "build" in my res:// but specified "builds/name.apk". Hope this will help someone.

Windows 10
Godot Engine v4.0.stable.official [92bee43ad]
Android (Runnable) - default build template from "Project -> Install Android Build Template..."
