### ISSUE TITLE
AnimationTree blend - initial rotation ignored when using root motion and changing the blend value in code.

### ISSUE THREAD

**Issue by ModularNucleus** [godotengine/godot#67125]
### Godot version

v4.0.beta2.official [f8745f2f7]

### System information

Windows 10, Nvidia RTX3060Ti, Studio driver 512.59, Vulkan Clustered

### Issue description

The issue is a bit puzzling, so perhaps there is something I have missed. Here is what I have observed:

When using root motion and blending in the AnimationTree - e.g., with a blend or blendspace node - between different animations that have initial rotation differences, it seems that those initial rotations are ignored when changing the blend value in code. When changing the blend value in the editor and then running the scene, those same rotation differences are taken into consideration.

In this particluar example I have three simple animations: _walk_forward_, _walk_left_ and _walk_right_. The left and right animations have a +/- 90 degrees initial rotation offset around the root bone y axis in relation to the walk_forward animation. All three animations also have smaller rotations around the root bone y axis. It is only the initial 90 degree rotation offset that is ignored - the smaller rotations are observed:

When changing the blend value in the editor, things work as expected:

https://user-images.githubusercontent.com/91982860/194754050-068c5e76-9e66-483a-ace7-940b247571cd.mp4

However, when changing the blend value in code, the initial rotation difference seems to be ignored:

https://user-images.githubusercontent.com/91982860/194754186-005b1c43-10fc-4d71-af56-b1f4e275a403.mp4

### Steps to reproduce

- Open the MRP
- Change the value of the Blend2 node in the inspector and run the project
- Observe that the CharacterBody respects the orientation of the blended animations by facing the direction of movement
- Uncomment the code line that changes the blend value, change the value and then run the scene
- Observe that the CharacterBody does not respect the orientation of the blended animations (and e.g., moves "sideways")

### Minimal reproduction project

[Root Motion Test.zip](https://github.com/godotengine/godot/files/9741408/Root.Motion.Test.zip)

**Comment by TokageItLab** [comment]
This is not a bug and it is a design issue. The root motion takes out only the difference transform value from the previous frame.

Perhaps including rotation in bones such as hips or sub_root_bone, or adding abrupt rotation in the next of first frame would be a solution to some extent, but it is not a fundamental solution.

But, when using root motion, the first frame transform of the animation is usually based on the initial transform, so the use case of mixing root motion and non-root motion deformations, as in this issue, seems to be a corner case.
