### ISSUE TITLE
Placing terrain tile clears adjacent non-terrain tiles

### ISSUE THREAD

**Issue by compmstr** [godotengine/godot#67143]
### Godot version

v4.0.beta2.official [f8745f2f7]

### System information

Linux (Pop OS), NVIDIA GeForce RTX 2060, Video Drive v 470.141.03

![TileMapBugScreenshot](https://user-images.githubusercontent.com/393652/194766931-a7973559-5d64-4564-ad5d-429a485d81fb.png)

### Issue description

If you place a terrain tile, any non-terrain tiles in the adjacent bit-checked cells get cleared out.

ex: 
  - For a 'Check sides' terrain, the N,W,S, and E tiles get cleared
  - For a 'Check sides and corners' terrain, all 8 adjacent tiles get cleared.

This happens both in the editor and in code.

I would expect that placing a terrain tile would only affect adjacent terrain tiles, and not tiles from other terrains or non-terrain tiles.

### Steps to reproduce

1) Create a terrain set in a TileSet
2) Create at least one non-terrain tile in the same TileSet
3) Place some non-terrain tiles
4) Place terrain tiles adjacent to the non-terrain tiles

### Minimal reproduction project

[TileTerrainBugRepro.zip](https://github.com/godotengine/godot/files/9741942/TileTerrainBugRepro.zip)

**Comment by amoriqbal** [comment]
Could not reproduce in Linux Mint 20.3, Vulcan, GTX 1650.

**Comment by compmstr** [comment]
I don't know of a tutorial, I've mostly just been trying to work with it.  I can still repro after rebooting and reloading the minimal repro project.

1) Open the repro project
2) Select the TileMap
3) Select 'TileMap' at the bottom of of the screen
4) Switch to the 'Terrains' tab
5) Pick 'Basic Terrain'
6) Put a terrain square adjacent to any of the green (non-terrain) tiles
    - I see all of the adjacent green tiles removed
