### ISSUE TITLE
C# Generic partial class that inherits Node crashes Godot 4.0 Beta 2 Mono

### ISSUE THREAD

**Issue by Mooncat25** [godotengine/godot#67140]
### Godot version

4.0.beta2.mono.official `[f8745f2f7]`

### System information

Windows 11 Home 64-bit (Build 22000), Intel Core i5 11400F, NVIDIA GeForce RTX 3070

### Issue description

**Issue:**
Creating a C# generic partial class that inherits `Node` and overrides `_Ready()` and then compiling the project will crash the editor the next time opening the project.
The project can actually compile and run without problem. But the editor just refuses to open it again after it is closed.
Using PowerShell to open Godot and then the project will show `System.InvalidOperationException` and `System.AccessViolationException`:
![image](https://user-images.githubusercontent.com/7956390/194764726-d4f9f100-5f79-40c5-9d31-a6b5cc9fb877.png)

**Expected Behaviour:**
Editor can open the project again without crashing.

**Current Solution:**
I have to manually delete `.godot\mono\temp\bin\Debug\(MyProject).dll` every time before I open the project in Godot.

### Steps to reproduce

1. Create a new project.
2. Create a C# class that inherits `Node`.
3. Make the C# class generic. Delete everything but `_Ready()` inside the class. So it becomes something like this:
```
using Godot;
using System;

public partial class GenericNode<T> : Node
{
	// Called when the node enters the scene tree for the first time.
	public override void _Ready()
	{
	}
}
```
4. Click the Build button in Godot. (Occasionally Godot crashes at this step)
5. Close the project. Open it again. Sometimes the editor crashes before the scene is loaded, sometimes it crashes a few seconds after the scene is loaded.

Note: if `_Ready()` is also deleted such that the class is empty, the project can be opened again after compiled.

### Minimal reproduction project

[TestCrashProject.zip](https://github.com/godotengine/godot/files/9741884/TestCrashProject.zip)

**Comment by MrZak-dev** [comment]
i am having exactly the same issue using Godot 4 Beta 6,  dotnet 6.

the editor keeps crashing when using a Node derivative class using Generics .

```pwsh

ERROR: System.InvalidOperationException: Late bound operations cannot be performed on types or methods for which ContainsGenericParameters is true.
   at System.Reflection.RuntimeMethodInfo.ThrowNoInvokeException()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Godot.Bridge.ScriptManagerBridge.GetMethodListForType(Type type) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:line 761
   at Godot.Bridge.ScriptManagerBridge.UpdateScriptClassInfo(IntPtr scriptPtr, godot_bool* outTool, godot_array* outMethodsDest, godot_dictionary* outRpcFunctionsDest, godot_dictionary* outEventSignalsDest, godot_ref* outBaseScript) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:line 593
   at: godotsharp_pusherror (modules/mono/glue/runtime_interop.cpp:1240)
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Godot.NativeInterop.NativeFuncs.godotsharp_internal_reload_registered_script(IntPtr)
   at Godot.Bridge.ScriptManagerBridge.CreateScriptBridgeForType(System.Type, Godot.NativeInterop.godot_ref*)
   at Godot.Bridge.ScriptManagerBridge.GetOrCreateScriptBridgeForType(System.Type, Godot.NativeInterop.godot_ref*)
   at Godot.Bridge.ScriptManagerBridge.GetOrCreateScriptBridgeForPath(Godot.NativeInterop.godot_string*, Godot.NativeInterop.godot_ref*)
   ```

**Comment by valkyrienyanko** [comment]
Godot 4 Beta 8 fixed this for me. Give Beta 8 a try and let me know if it fixes it for you 👍

**Comment by Mooncat25** [comment]
> Godot 4 Beta 8 fixed this for me. Give Beta 8 a try and let me know if it fixes it for you 👍
> 
> Nvm the issue came back... I didn't delete the `.Godot` folder so I was surprised to see my project work for a good while.

After a few months of working, I realized I don't really need this feature. So right now I can only test with the minimal reproduction project with Godot v4.0 beta 8:
1. Did not delete anything and open it with Godot -> Crash
2. Deleted `.godot\mono\temp\bin\Debug\(MyProject).dll`, open it, Build -> Crash
3. Deleted `.godot\mono\temp`, open it, Build, close and reopen -> No Crash
4. Deleted `.godot`, open it, Build, Error complaining about `.godot\mono\metadata\ide_messaging_meta.txt'` not found, Build again anyway, close and reopen -> No Crash

To conclude, I couldn't reproduce the issue with the minimal reproduction project after deleting `.godot\mono\temp` and build the project again with Godot v4.0 beta 8.
Not really sure if the issue is actually fixed.
