### ISSUE TITLE
Debugger throwing errors when MeshInstance3D containing a duplicate material is removed with queue_free()

### ISSUE THREAD

**Issue by Dabnabbit** [godotengine/godot#67144]
### Godot version

4.0.beta2

### System information

Windows 11, RTX 3070TI, GLES2

### Issue description

When attempting to create a duplicate material of a MeshInstance3D, the material.duplicate() method appears to work properly, however, it throws errors in the Debugger when 'queue_free()' is executed on a meshinstance with a duplicated material. This behavior does not occur if the material is not duplicated.

Error messages:

```
E 0:00:02:0561   material_casts_shadows: Condition "!material" is true. Returning: true
  <C++ Source>   servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2676 @ material_casts_shadows()
E 0:00:02:0561   material_is_animated: Condition "!material" is true. Returning: false
  <C++ Source>   servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2663 @ material_is_animated()
E 0:00:02:0561   material_get_instance_shader_parameters: Condition "!material" is true.
  <C++ Source>   servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2689 @ material_get_instance_shader_parameters()
E 0:00:02:0561   material_update_dependency: Condition "!material" is true.
  <C++ Source>   servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2701 @ material_update_dependency()

```

### Steps to reproduce

Instantiate a scene object that contains a mesh with a material assigned to it.
Get the meshinstance3d object of the instantiation.
Get the material of the meshinstance3d, and utilize the .duplicate() method to create a copy of the material
Reassign the duplicate material to the meshinstance3d override material
call queue_free() on the instance to remove it, which will result in errors thrown stating that parameters are missing from the duplicate material.

### Minimal reproduction project

[MaterialBugProject.zip](https://github.com/godotengine/godot/files/9742041/MaterialBugProject.zip)

There is a bool toggle on the main scene that will enable or disable material duplication on the spawned meshinstance3D objects. It should be enabled by default which will demonstrate the bug, disabling it shows that non duplicated materials do not behave the same way.

**Comment by Fran6nd** [comment]
I just got the same issue.

**Comment by Calinou** [comment]
> I just got the same issue.

Which *exact* Godot version are you using?

**Comment by Fran6nd** [comment]
> > I just got the same issue.
> 
> Which _exact_ Godot version are you using?

I am using Godot master branch compiled yesterday so almost the latest.
To be exact the latest commit is: 
```
commit 2bd9a6fe8d6f29fe7ab3bcf1f6378cf425e96e84
Merge: 778ffce1e3 601c42be66
Author: Rémi Verschelde <rverschelde@gmail.com>
Date:   Mon Oct 31 23:03:30 2022 +0100

    Merge pull request #68044 from ztc0611/ios-promotion
    
    Add ProMotion/High Refresh Rate Support to iOS Exports
```

**Comment by gitcatrat** [comment]
#59912 seems to be duplicate.

Seeing the same issue with C# using `RenderingServer` directly in `rc1`.
```
material_casts_shadows: Condition "!material" is true. Returning: true
servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2823 @ material_casts_shadows()
material_is_animated: Condition "!material" is true. Returning: false
servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2810 @ material_is_animated()
material_get_instance_shader_parameters: Condition "!material" is true.
servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2836 @ material_get_instance_shader_parameters()
material_update_dependency: Condition "!material" is true.
servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2848 @ material_update_dependency()
```
Seems to happen only when instances are freed in a loop, haven't noticed it with single deletions.

**Comment by gitcatrat** [comment]
#59912 probably has the same or very similar cause.

Seeing the same errors with C# using `RenderingServer` in `rc1`, so it's probably in server or material level.
```
material_casts_shadows: Condition "!material" is true. Returning: true
servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2823 @ material_casts_shadows()
material_is_animated: Condition "!material" is true. Returning: false
servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2810 @ material_is_animated()
material_get_instance_shader_parameters: Condition "!material" is true.
servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2836 @ material_get_instance_shader_parameters()
material_update_dependency: Condition "!material" is true.
servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2848 @ material_update_dependency()
```
For me it seems to happen only when instances are freed in a loop, haven't noticed it with single deletions.

**Comment by Sky84** [comment]
Same pb in godot 4 rc2

**Comment by CathodeRayBlues** [comment]
I can confirm this issue yet persists in rc3. I was wondering what caused this exactly.

**Comment by JosephHalter** [comment]
It's still the same in 4.0 final and also applies for materials where `Local to scene` is checked.

**Comment by FilipeRubin** [comment]
I've discovered a quick fix: set the material to `null` before deleting the node. For example:

```gdscript
func _exit_tree(): # When someone calls queue_free() here
    $Mesh.set("surface_material_override/0", null)
```

**Comment by Zylann** [comment]
I get this one:
```
E 0:00:02:0561   material_update_dependency: Condition "!material" is true.
  <C++ Source>   servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2701 @ material_update_dependency()
```
But I'm not using `duplicate`.

**Comment by RichardR01** [comment]
This is still going on in Godot 4.01

E 0:01:19:0782   material_casts_shadows: Condition "!material" is true. Returning: true
  <C++ Source>   servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2824 @ material_casts_shadows()
E 0:01:19:0782   material_is_animated: Condition "!material" is true. Returning: false
  <C++ Source>   servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2811 @ material_is_animated()
E 0:01:19:0782   material_get_instance_shader_parameters: Condition "!material" is true.
  <C++ Source>   servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2837 @ material_get_instance_shader_parameters()
E 0:01:19:0782   material_update_dependency: Condition "!material" is true.
  <C++ Source>   servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2849 @ material_update_dependency()

I am preloading a BaseMaterial3D resource and duplicating it, passing it to a MeshInstance3D surface override on multiple meshes. This is necessary to prevent hitching. All resources are preloaded on a singleton. Setting the surface override to null does eliminate the error, but why should we have to do this? I'd have to write code to go through each MeshInstance to remove them.

**Comment by Zylann** [comment]
Coming back from my own case... I realize it could be a hint of why this issue exists.

The `RenderingServer` basically logs those errors if a mesh instance is freed while it still holds the RID to a material that was previously freed:
I'm not using nodes, I have my own dedicated wrapper classes. I also know RenderingServer doesnt take ownership over resources, it only uses RIDs. I had this problem occur because one class was both holding the RID of a MeshInstance, and its material. But the material appeared first in the members of the class, causing it to be freed before the MeshInstance when the destructor of the class was called.
Another case was a class inheriting another, where the material was held in the child class. Because of that, this material was also freed first. 

Turns out, it is also the case in `MeshInstance3D`. The RID of the instance is in the base class, which destroys it in the destructor. But `surface_override_materials` is held in the child class, therefore can be freed first if they are the only references.
It's quite nasty to solve this kind of "dependency", so either destruction order has to be inverted somehow, or RenderingServer needs to tolerate that RIDs can go invalid, or needs to update depending instances somewhat (although that often comes with a cost when dealing with many of them, notably in destruction where it can easily become a useless callback-fest).

**Comment by Zylann** [comment]
I just added a way to set shadow casting setting for my voxel meshes, and now the mega error spam is back again for me when I close the scene... even though I already applied a workaround for the issue I described earlier.
```
ERROR: Condition "!material" is true.
   at: RendererRD::MaterialStorage::material_update_dependency (servers\rendering\renderer_rd\storage_rd\material_storage.cpp:2849)
servers\rendering\renderer_rd\storage_rd\material_storage.cpp:2849 - Condition "!material" is true.
ERROR: Condition "!material" is true. Returning: true
   at: RendererRD::MaterialStorage::material_casts_shadows (servers\rendering\renderer_rd\storage_rd\material_storage.cpp:2824)
servers\rendering\renderer_rd\storage_rd\material_storage.cpp:2824 - Condition "!material" is true. Returning: true
ERROR: Condition "!material" is true. Returning: false
   at: RendererRD::MaterialStorage::material_is_animated (servers\rendering\renderer_rd\storage_rd\material_storage.cpp:2811)
servers\rendering\renderer_rd\storage_rd\material_storage.cpp:2811 - Condition "!material" is true. Returning: false
ERROR: Condition "!material" is true.
   at: RendererRD::MaterialStorage::material_get_instance_shader_parameters (servers\rendering\renderer_rd\storage_rd\material_storage.cpp:2837)
servers\rendering\renderer_rd\storage_rd\material_storage.cpp:2837 - Condition "!material" is true.
```

**Comment by jitspoe** [comment]
I'm also getting this error spam, but I haven't been able to figure out what specifically causes it.  It seems like it happens all the time, but when I sit down and actually try to debug it, it stops. 🤔

**Comment by BastiaanOlij** [comment]
The problem seems to be that when a material gets freed as a scene is closed, mesh instances retain the RIDs for that material and try to access it. With the material no longer existing, you get the error spam mentioned in this issue.
