### ISSUE TITLE
Crash To Desktop on switching focus in GridContainer containing complex buttons.

### ISSUE THREAD

**Issue by floydnunez** [godotengine/godot#6714]
**Operating system or device - Godot version:**
Mac OSX El Capitan. Godot v2.1.stable.official

**Issue description** (what happened, and what was expected):
I am making a slightly more complex button. It has to support lighting, and animations, and thus is a complex tree including a couple of Node2D nodes. When putting a bunch of instances of them on a GridContainer, and trying to switch focus using tab produces a Crash to Desktop 

**Steps to reproduce:**
To do this I created two scenes:
-one with a container and a GridContainer.
-one that is the button. It has a Container, a Node2D and a Button.

<img width="247" alt="screen shot 2016-10-04 at 23 43 03" src="https://cloud.githubusercontent.com/assets/1719570/19099419/9a14066a-8a8c-11e6-9cb9-76f4e28456ca.png"><img width="235" alt="screen shot 2016-10-04 at 23 43 09" src="https://cloud.githubusercontent.com/assets/1719570/19099424/a5c07480-8a8c-11e6-8536-cade73e967a9.png">

I add several instances of the button to the GridContainer on its _ready method. Then launch it, click on one of the buttons and press "tab". Crash to Desktop and OSX asks to fill a report.

<img width="421" alt="screen shot 2016-10-04 at 23 43 18" src="https://cloud.githubusercontent.com/assets/1719570/19099434/c94bda8e-8a8c-11e6-96b4-2bbfb904abb4.png">
<img width="937" alt="screen shot 2016-10-04 at 23 46 51" src="https://cloud.githubusercontent.com/assets/1719570/19099442/dadaa686-8a8c-11e6-9b27-4f589ff87911.png">

Do note that moving around with the keys (reaaaally nice feature jesus christ thanks to whoever did this) does not produce a crash.

**Link to minimal example project** (optional but very welcome):
https://www.dropbox.com/s/9b1o0tnok33i479/crashDemo.zip?dl=0

The report is huge, I am posting the first lines

Process:               Godot [11438]
Path:                  /Applications/Godot.app/Contents/MacOS/Godot
Identifier:            org.godotengine.godot
Version:               2.1 (2.1)
Code Type:             X86-64 (Native)
Parent Process:        Godot [10030]
Responsible:           Godot [11438]
User ID:               502

Date/Time:             2016-10-04 23:47:21.189 -0300
OS Version:            Mac OS X 10.11.5 (15F34)
Report Version:        11
Anonymous UUID:        61065F14-7955-A5AC-554A-D9CA127CE984

Time Awake Since Boot: 7500 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000228
Exception Note:        EXC_CORPSE_NOTIFY

VM Regions Near 0x228:
--> 
    __TEXT                 00000001076b6000-0000000109c0e000 [ 37.3M] r-x/rwx SM=COW  /Applications/Godot.app/Contents/MacOS/Godot

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   org.godotengine.godot           0x00000001082ece89 Control::find_next_valid_focus() const + 617
1   org.godotengine.godot           0x00000001082945d0 Viewport::_gui_input_event(InputEvent) + 2544
2   org.godotengine.godot           0x0000000108292a89 Viewport::input(InputEvent const&) + 313
3   org.godotengine.godot           0x0000000108292943 Viewport::_vp_input(InputEvent const&) + 355
4   org.godotengine.godot           0x00000001082a3d95 MethodBind1<Viewport, InputEvent const&>::call(Object_, Variant const__, int, Variant::CallError&) + 469
5   org.godotengine.godot           0x0000000108cdc4d2 Object::call(StringName const&, Variant const_*, int, Variant::CallError&) + 642
6   org.godotengine.godot           0x0000000108cdc1aa Object::call(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) + 106
7   org.godotengine.godot           0x000000010827051b SceneTree::call_group(unsigned int, StringName const&, StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) + 1627
8   org.godotengine.godot           0x000000010827161a SceneTree::input_event(InputEvent const&) + 330
9   org.godotengine.godot           0x00000001076c07d1 InputDefault::parse_input_event(InputEvent const&) + 1201
10  org.godotengine.godot           0x00000001076b8ec0 -[GodotContentView keyDown:] + 528
11  com.apple.AppKit                0x00007fff916b1b15 -[NSWindow _reallySendEvent:isDelayedEvent:] + 2108
12  com.apple.AppKit                0x00007fff910f0539 -[NSWindow sendEvent:] + 517
13  com.apple.AppKit                0x00007fff9107116a -[NSApplication sendEvent:] + 4382
14  org.godotengine.godot           0x00000001076b7988 -[GodotApplication sendEvent:] + 136
15  org.godotengine.godot           0x00000001076bbd7b OS_OSX::run() + 235
16  org.godotengine.godot           0x00000001076be0ab main + 523
17  libdyld.dylib                   0x00007fff8a14a5ad start + 1

**Comment by Hinsbart** [comment]
I opened #6717, which at least fixes the crash.
However the issue that it doesn't find a valid "next control" in this case still remains.

**Comment by bojidar-bg** [comment]
Is this issue still valid (it's been a while)? Should we close it in favour for another one or retitle it?

**Comment by reduz** [comment]
Does this still happen?

**Comment by floydnunez** [comment]
I opened the crash demo on 2.1.3 stable and it doesn't happen anymore, so yay!
