### ISSUE TITLE
Conversion from V3.5.1 to V4Beta2 does not preserve input map

### ISSUE THREAD

**Issue by Proggle** [godotengine/godot#67156]
### Godot version

v3.5.stable.official [991bb6ac7], v4.0.beta2.official [f8745f2f7]

### System information

Window 10

### Issue description

Converting a project from 3 to 4 is does not preserve the input map.

Godot 3.5.1 version:
![image](https://user-images.githubusercontent.com/89282845/194778041-9033cabb-ce87-4195-8531-9e80eca56ba5.png)

Godot 4B2 version:
![image](https://user-images.githubusercontent.com/89282845/194777990-b279166c-e7c0-4392-a168-1cc5311526db.png)

As you can see, the keyboard inputs (including default ones, like left on the keyboard being associated with ui_left) get destroyed by the conversion process, and controller inputs get lost too.  

If nothing else, the default inputs that are automatically created with the project ought to port properly, since we know what those look like in both versions.

### Steps to reproduce

Make a godot 3 project, convert to godot 4.  Open the input map, note that information has been lost.

### Minimal reproduction project

[InputMapExample.zip](https://github.com/godotengine/godot/files/9742523/InputMapExample.zip)

**Comment by Calinou** [comment]
The key input part is already reported in https://github.com/godotengine/godot/issues/57311.

**Comment by xyproto** [comment]
Could this also be related to #67135 ?
