### ISSUE TITLE
Vulkan Mobile: `textureLod()` does not work in shaders (Can't use the compute version of the copy_to_rect shader with the mobile renderer.)

### ISSUE THREAD

**Issue by bepthomp** [godotengine/godot#67160]
### Godot version

4.alpha1 -> 4.beta2

### System information

Windows 10, Vulkan Mobile, Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz 2.21 GHz

### Issue description

When using the Vulkan Mobile renderer, textureLod() does not work.

As of Alpha 1, this error message constantly appears when running the game, and the screen will not be sampled:
![image](https://user-images.githubusercontent.com/36116447/194781277-78e5733c-f782-4182-8da3-d384490d5d55.png)

This feature works on both the GLES2 renderer in 3.5, and also on the Vulkan Forward+ renderer.

### Steps to reproduce

- Create a project in any 4.0 version with the Vulkan Mobile renderer
- Create a control node main scene with two ColorRects as children (one for reference)
- Add a shader to the second ColorRect and paste this code in the fragment:
          **COLOR = textureLod(SCREEN_TEXTURE,SCREEN_UV+vec2(sin(TIME)),0.0);**
          (sin(TIME) is added to SCREEN_UV so that it is easy to tell whether the code is working or not)
- This code will work in 3.5, and you will see the square fly across the screen, but it will not work in any 4 versions.

### Minimal reproduction project

Godot 3.5 GLES2 project included for easy comparison.

[textureLod MRP 3-5.zip](https://github.com/godotengine/godot/files/9742681/textureLod.MRP.3-5.zip)

[textureLod MRP 4-alpha1.zip](https://github.com/godotengine/godot/files/9742686/textureLod.MRP.4-alpha1.zip)

[textureLod MRP 4-beta2.zip](https://github.com/godotengine/godot/files/9742683/textureLod.MRP.4-beta2.zip)

**Comment by BastiaanOlij** [comment]
We should have an FB version of the copy_to_rect shader, I'll have a look as soon as I can to see if I can easily fix this.
