### ISSUE TITLE
keyboard navigation for autocomplete menus within text editor

### ISSUE THREAD

**Issue by doman412** [godotengine/godot#67171]
### Godot version

v3.5.1.stable.official [6fed1ffa3]

### System information

macOS 12.6 (21G115)

### Issue description

The auto-complete menus within the script editor does not accept common keyboard movement shortcuts and there is no config for it. I use `ctrl-n/p` for moving my cursor up and down the editor but this does not extend to the menus that might appear within the editor. In editors like vscode it is common for me to hit `ctrl-space` (`script_text_editor/complete_symbol` in godot) and then `ctrl-n` to highlight the auto-complete menu item I want completed. Currently this menu navigation is only `arrow-up/down` afaik.

This is just a small QoL improvement so I ask that you please make this configurable and/or allow the `ctrl-n/p` shortcut keys to move the menu selection along with the arrow keys by default.

### Steps to reproduce

- inside of a script editor
- start typing something like `Input.`
- use `ctrl-space` to bring up the menu of auto-complete options.
- You will be unable to use `ctrl-n` to move the selection down the way you would with `arrow-down`.

**Comment by EricEzaM** [comment]
Can you try 4.0? Pretty sure this is fixed there.

**Comment by doman412** [comment]
@EricEzaM yes! It does work in 4.0 after configuring it in the editor settings. I will make the switch and try it out more.

I did find a bug while setting up the shortcuts though. `command-backspace` doesn't backspace to the beginning in text inputs like the search bar in the the keyboard shortcuts editor. It also seems to not work in side dock inputs like transform values. I don't see an issue for it at the moment so let me know if you'd like me to create a separate issue for that.

Version: v4.0.beta2.official [f8745f2f7]
