### ISSUE TITLE
Script Templates not Recognized for C# Project in Godot 4

### ISSUE THREAD

**Issue by ExquisiterEmil** [godotengine/godot#67177]
### Godot version

v4.0.beta2.mono.official [f8745f2f7]

### System information

Windows 10

### Issue description

Custom Script Templates do not work on the Mono 
Build of the Godot 4.0 beta 2 version. Both Project and Editor templates do not get picked up by the Editor. 

### Steps to reproduce

Create an empty project in the Mono version of godot. 
Add the `script_templates` folder to the root of the project.
Add the `my_template.cs` file to the folder.
![image](https://user-images.githubusercontent.com/53947784/194818998-613d6db3-7393-4ae3-a6a4-57981ff59a2d.png)

Usually it should pick up the template file and show it in the editor when creating a new script but it does not.
![image](https://user-images.githubusercontent.com/53947784/194818760-1ac22d65-d6f9-48c9-bf93-d6205ea24100.png)

### Minimal reproduction project

[BrokenScriptTemplates.zip](https://github.com/godotengine/godot/files/9744063/BrokenScriptTemplates.zip)

The Project contains a `script_templates` folder with a C# Script Template and the same with a GD Script ending both are not working.

**Comment by akien-mga** [comment]
There's a specific folder structure you have to follow for script templates in 4.0, see the updated documentation: https://docs.godotengine.org/en/latest/tutorials/scripting/creating_script_templates.html
