### ISSUE TITLE
ArrayMesh surface_remove() missing in 4.0

### ISSUE THREAD

**Issue by Xyotic** [godotengine/godot#67181]
### Godot version

4.0 beta 1

### System information

Windows 10, Nvidia RTX2080

### Issue description

In 4.0, ArrayMesh is missing the 'surface_remove' method and there doenst seem to be an alternative.
Accessing the surface array directly and removing an entry also doesnt seem to work.
Currently the only way is to use 'clear_surfaces'. Which I think would have a  negative performance impact if you'd always clear all surfaces and set new ones.
In 3.x 'surface_remove' is still present.

### Steps to reproduce

Add a surface to an ArrayMesh via 'add_surface_from_arrays' and try to remove it.

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot/pull/41767.

**Comment by Xyotic** [comment]
Is there a workaround for now that doesnt include the use of 'clear_surfaces'? @Calinou

**Comment by Zireael07** [comment]
Seconding, I was using this for some very simple deformations and had to give up on those in 4.0

**Comment by Xyotic** [comment]
Removing surfaces also seems to be missing from RenderingServer3D. So this server cant be used as a workaround.

**Comment by prominentdetail** [comment]
We need this added back into 4.0
It makes it difficult to add surfaces to a mesh without it. Sure you can clear all the surfaces, but if you are relying on the previous surfaces to generate new surfaces, you don't want to clear them all when you need to add each one separately.. :(

**Comment by ze2j** [comment]
I don't know if someone started some work on it, but I started to (re)implement this function and I should be able to make a PR next week for both OpenGL and Vulkan renderers.

**Comment by nvanfleet** [comment]
I hope this gets in eventually

**Comment by EsotericDude** [comment]
Any updates? This would be a very useful function.

**Comment by Calinou** [comment]
@EsotericDude https://github.com/godotengine/godot/pull/76371 implements this feature but it needs to be rebased before I can review it.
