### ISSUE TITLE
GDScript 2.0: parameter name issue

### ISSUE THREAD

**Issue by AFE-GmdG** [godotengine/godot#67185]
### Godot version

4.0 beta 2

### System information

Windows 11 x64 professional

### Issue description

I've experienced some issues with the scope of class variables and function parameters:

For example a class containing a var file_path and a function (static or non static) has a parameter file_path:

```gdscript
class_name Example
extends RefCounted

var file_name: String

static func loadFromFile(file_name: String = "") -> Example:
    if file_name == "":
        file_name = ... #some random file name generation
        var example := new()
        example.file_name = file_name
        # more code
```

While debugging my code I get errors because the variable / parameter scope is not correct:

### Steps to reproduce

Create code like described and debug it

**Comment by Calinou** [comment]
Shadowing of this kind should be avoided whenever possible. The editor should warn you about those already. I recommend adding a `p_` prefix to function parameters so you don't have to worry about this in the future :slightly_smiling_face:
