### ISSUE TITLE
AnimationPlayer editor: Ability to copy individual keys

### ISSUE THREAD

**Issue by hetdegon** [godotengine/godot#6718]
I found myself having to move a key with a number of arguments in an func call track in the animation editor to another animation inside the same node, but it seems to not be possible to copy a single individual key. 

It'd be really convenient to allow copying/cutting selected keys to the clipboard so they can be pasted to a different animation. While this is mostly useful for func call tracks, it'd also be useful in regular node parameter ones, specially with multi-part sprites where certain positions/parameters are repeated in different animations.

**Comment by hetdegon** [comment]
As a little addendum to this, I've found myself in the situation where I need to copy a number of keys from one node to another identical node, and it's not possible as of now. As a bit of an extension to this request, it'd be nice to copy keys to another node in a similar fashion, allowing to repeat the same animation in another node.
It's *somewhat* possible to do so using the tscn format and manually copying the animation keys, but it's tedious and could easily go wrong.

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by hetdegon** [comment]
Yeah, this is still valid. I can copy the entire animation but not individual keys.

**Comment by hetdegon** [comment]
Seems the new animation editor allows copying the track, but not the key. It's a bit of a start but would be nice to be able to copy keys as well, so I'll leave this one open for now.
