### ISSUE TITLE
GDScript 2.0: Editor leaks when script checks if var is of the same class as itself

### ISSUE THREAD

**Issue by rafallus** [godotengine/godot#67199]
### Godot version

v4.0.beta.custom_build [ca25c6e0a]

### System information

Windows 10

### Issue description

When using the following code
```gdscript
class_name MyNode
extends Node


func link_node(node):
	if node is MyNode:
		pass
```
a warning message is displayed at exiting the editor
```
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: ObjectDB::cleanup (core\object\object.cpp:1956)
ERROR: Resources still in use at exit (run with --verbose for details).
   at: ResourceCache::clear (core\io\resource.cpp:473)
```

### Steps to reproduce

Add a script with the previous code. Then close the editor.

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/9746359/Test.zip)

**Comment by adamscott** [comment]
Could not reproduce the leak on master (fcba87e). I consider this issue fixed. @akien-mga
