### ISSUE TITLE
Some TODOs to resolve in editor or GUI code after Control/Window split

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#67190]
### Godot version

4.0.beta (77f4670d0)

### System information

All

### Issue description

Some `#warning`s which I'm removing in #67183 which need to be assessed by @godotengine/gui-nodes @godotengine/_editor:

Drag forwarding:

https://github.com/godotengine/godot/blob/77f4670d001b12a5c7e1f50c100301c8fb1b4d1e/editor/create_dialog.cpp#L755-L758

https://github.com/godotengine/godot/blob/77f4670d001b12a5c7e1f50c100301c8fb1b4d1e/editor/export/project_export.cpp#L1018-L1021

ColorPicker `show_modal`:

https://github.com/godotengine/godot/blob/77f4670d001b12a5c7e1f50c100301c8fb1b4d1e/scene/gui/color_picker.cpp#L1406-L1409

### Steps to reproduce

n/a

**Comment by KoBeWi** [comment]
> cannot forward drag data to a non control, must be fixed 

This is not true, see the discussion in #60558

**Comment by akien-mga** [comment]
> > cannot forward drag data to a non control, must be fixed
> 
> This is not true, see the discussion in #60558

Then I guess the `#warning` and dead code should just be removed?

**Comment by EricEzaM** [comment]
None of these appear to exist any more (ctrl + F, #warning, not results)

**Comment by akien-mga** [comment]
That's expected, I removed the `#warning`s in https://github.com/godotengine/godot/pull/67183, which is why I opened this issue instead to keep track of what they warned about.

**Comment by EricEzaM** [comment]
Oh sorry I just skimmed the op, my bad.

**Comment by KoBeWi** [comment]
Resolved by #71379 and #74962
