### ISSUE TITLE
Bounding boxes of imported GLFT2 (glb) models are displayed in wrong positions (regression).

### ISSUE THREAD

**Issue by viksl** [godotengine/godot#67209]
### Godot version

4.0 beta2 mono (C#)

### System information

Windows 10, Nvidia GTX 1660Ti, Vulkan

### Issue description

As you can see in the images bounding boxes of imported objects are shown in a wrong positions (wrong axis?), this does not happen in beta1 but in beta2.

![obrazek](https://user-images.githubusercontent.com/33526847/194929162-9a821c3f-e0bc-4e33-8ea7-95db60e14e19.png)
![obrazek](https://user-images.githubusercontent.com/33526847/194929203-edb1484f-3e99-47db-a9b7-46ceecb7fab0.png)

### Steps to reproduce

Add a gltf2 model into your scene or check the test scene, open the model scene itself (double click on Model node in the editor and press Open Anyway in the pop up) and check individual bounding boxes (click on the nodes in the Scene tab) to seethey are displayed at wrong locations.

### Minimal reproduction project

[TestNoSave.zip](https://github.com/godotengine/godot/files/9748132/TestNoSave.zip)

**Comment by fire** [comment]
Gut feeling says it might be related to https://github.com/godotengine/godot/pull/65493

**Comment by viksl** [comment]
I'm in beta 10 and it seems to be fixed. I think this can be closed unless someone else found an issues I missed now.
