### ISSUE TITLE
Conversion between V3 and V4 loses tilemap tile sizes and layer order

### ISSUE THREAD

**Issue by Proggle** [godotengine/godot#67218]
### Godot version

v3.5.stable.official [991bb6ac7], v4.0.beta2.official [f8745f2f7]

### System information

Windows 10

### Issue description

Tilesizes and layer order get changed in godot 4 when importing from godot 3

Godot 3: tilesize is (correctly) 18x18, icon is in front of tileset, covering the ! blocks.
![image](https://user-images.githubusercontent.com/89282845/194945686-38f7424e-a3f8-4882-841b-8feb68cc075d.png)

Godot 4: tile size has been changed from 18x18 to 16x16, icon is now behind tileset
![image](https://user-images.githubusercontent.com/89282845/194945622-03a7e112-c047-4699-9eed-6e94168878c4.png)

There's supposed to be some kind of legacy mode per https://github.com/godotengine/godot/issues/64006 but it doesn't seem to work out of the box.

### Steps to reproduce

Create a tile map in Godot 3.  Convert to Godot 4.  Layer order and tile sizes get changed.

### Minimal reproduction project

[tilesizeConversion.zip](https://github.com/godotengine/godot/files/9748708/tilesizeConversion.zip)

**Comment by Calinou** [comment]
I can confirm this on 4.0.beta 0c23a2cfe while porting demos: https://github.com/godotengine/godot-demo-projects/pull/782

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/70784, which contains more information about the issue at hand.
