### ISSUE TITLE
[macOS] Godot 4.0-beta frame drops when blurring (unfocusing) screen

### ISSUE THREAD

**Issue by coelhucas** [godotengine/godot#67222]
### Godot version

v4.0.beta2.official [f8745f2f7]

### System information

Macbook Pro 16,1 - Intel Core i9 8-Core; Vulkan

### Issue description

Frame drops on blur (leave focus of) Godot window.

### Steps to reproduce

- Open scene
- Unfocus screen while vertex shader is running (happens both with one of two monitors)

https://user-images.githubusercontent.com/28108272/194959595-4c494296-49b6-4c34-80c0-01384fdb2ad1.mp4

### Minimal reproduction project

Can't upload it right now, but it is an empty project, with a MeshInstance3d using the following shader:
```glsl
shader_type spatial;

void vertex() {
	VERTEX += vec3(cos(TIME)) * 10.0;
}
```

**Comment by Calinou** [comment]
The FPS when unfocused is intentionally capped to save power (and reduce the resulting heat/noise emissions). You can disable this behavior by decreasing **Unfocused Low Processor Mode Sleep Usec** in the Editor Settings.
