### ISSUE TITLE
"sync: Attempted to merge a navigation mesh triangle edge with another already-merged edge" on run-time terrain mesh

### ISSUE THREAD

**Issue by Griiimon** [godotengine/godot#67228]
### Godot version

3.5.1

### System information

Windows 10

### Issue description

I'm creating a terrain mesh at runtime via mesh surface tool plane sub-division and baking a navigation mesh for it.
Then I get this error:

"E 0:00:02.616   sync: Attempted to merge a navigation mesh triangle edge with another already-merged edge. This happens when the current `cell_size` is different from the one used to generate the navigation mesh. This will cause navigation problems.
  <C++ Source>  modules/navigation/nav_map.cpp:582 @ sync()
"

But I didn't mess with the cell_size at all.. In my project this is probably the cause for infrequent but substantial lag spikes during pathfinding calls.

### Steps to reproduce

Run the project to get the error.

### Minimal reproduction project

[nav_mesh_error.zip](https://github.com/godotengine/godot/files/9750590/nav_mesh_error.zip)

**Comment by smix8** [comment]
You need to adjust the `cell_size` and `cell_height` to your source geometry.

There is no one-size-fits-all. The default `cell_size` is designed to work well with the polygons of a default mesh resource in Godot but if you create your own meshes procedual you need to tinker more with the settings.

With too small cells too many mesh vertex can land together in the same cell creating non-working, overlapping edges in the later navmesh mergin. If you increase the cell_size and cell_height in your project the error goes away.

**Comment by Griiimon** [comment]
> If you increase the cell_size and cell_height in your project the error goes away.

Unfortunately that leads to artifacts in the navigation mesh.

I tried increasing the cell_size until the error won't occur, which lead to this

![nav mesh error](https://user-images.githubusercontent.com/25064539/195232617-2ad7e777-6922-43ba-8a8b-c3b20cb94da0.png)

Increasing the cell_height on the other hand lead to this


![nav mesh error 2](https://user-images.githubusercontent.com/25064539/195232726-6e67415f-7201-49a2-876b-faa0ee53024d.png)


So far, I haven't found an in-depth explanation of how to adjust the other parameters to mitigate this problem. This seems to be a recast implementation so there is a lot of stuff out there. It looks like it is used widely, which leaves me at least hopeful that it should be doable somehow.

**Comment by Griiimon** [comment]
I fixed the navigation artifacts by increasing the agents `max_climb`. Still not happy with the `cell_size` which I had to increase to 2 so the error would go away. It makes the navigation mesh less precise.

Originally I was hoping to eventually get a very detailed nav mesh at the cost of increased baking time. Either way it's a compromise, but I would have preferred the latter.
