### ISSUE TITLE
Shader applied colour darker than it should be

### ISSUE THREAD

**Issue by yhwhey** [godotengine/godot#67223]
### Godot version

4.0b2

### System information

macOS Monterey

### Issue description

When setting a pixel colour via shader, the colour is displayed darker than it should be.

### Steps to reproduce

Set colour of sprite via shader and same colour to a ColorRect. See difference in colour.

Please see attached project

### Minimal reproduction project

[shader_color_issue.zip](https://github.com/godotengine/godot/files/9749560/shader_color_issue.zip)

**Comment by yhwhey** [comment]
closed duplicate of #48039

**Comment by Calinou** [comment]
This may actually be a duplicate of https://github.com/godotengine/godot/issues/66619, especially if you can only reproduce the issue in 4.0.

**Comment by yhwhey** [comment]
Issue can be resolved by converting from linear to sRGB colour space
Color.linear_to_srgb()
