### ISSUE TITLE
AMD video cards fail to load game in vr (black screen)

### ISSUE THREAD

**Issue by fire** [godotengine/godot#67233]
### Godot version

https://github.com/V-Sekai/godot/commit/0e5be8fd3738460585d36aa6f59e7134d8ea1060

### System information

Windows 11, AMD, Vulkan forward+, Vulkan mobile

### Issue description

Openxr fails to load with Vulkan forward+ but works on mobile vulkan.

### Steps to reproduce

The player was using an amd gpu. Maybe an AMD 6900xt.

We play-tested with our openxr project and our project fails to load on the AMD video cards with Vulkan forward+.

When we switched our project to mobile vulkan the player was able to use openxr and it seemed to work.

1. open the game project
2. be sure to start in vr
3. the screen is black
4. If the project is forced to vulkan mobile it works

### Minimal reproduction project

We don't have a minimal project https://github.com/V-Sekai/v-sekai-game/commit/6116fd1492f9568057013426369f1b7e64e93511. There's a built version on that commit.

I would assume this would fail on @BastiaanOlij 's small openxr sample though. https://github.com/BastiaanOlij/godot4_openxr_demo

**Comment by fire** [comment]
@BastiaanOlij and @lyuma keeping you guys in the loop

**Comment by gameboycjp** [comment]
My specs are Windows 10, Ryzen 2700, 16GB RAM, RX6600XT, Index.

**Comment by Calinou** [comment]
This may be a duplicate of https://github.com/godotengine/godot/issues/66994.

**Comment by fire** [comment]
Closing because I think it's a duplicate of https://github.com/godotengine/godot/issues/66994.
