### ISSUE TITLE
SSR roughness produces strange horizontal streaks, especially visible when using Normal Maps

### ISSUE THREAD

**Issue by unfa** [godotengine/godot#67245]
### Godot version

4.0 beta 2

### System information

Windows 10 / Arch Linux; Vulkan, Clustered+, AMD Radeon RX6800XT

### Issue description

Screen-Space Reflections respond to roughness by blurring on one axis, which produces strange horizontal streaks, especially when using a normal map. For best case scenario I've set SSR to use highest quality.

Roughness = 0:
![image](https://user-images.githubusercontent.com/491704/195067122-e6aceaa8-7e9b-45db-be81-3a5b586e3a31.png)

Roughness = 0.25:
![image](https://user-images.githubusercontent.com/491704/195067278-266b7027-96a8-4127-bf0d-543b4d369564.png)

Roughness = 0 + normal map:
![image](https://user-images.githubusercontent.com/491704/195067816-7edf56a4-5a5a-4680-8536-1ae431baf610.png)

Roughness = 0.25 + normal map:
![image](https://user-images.githubusercontent.com/491704/195067698-3f99dd69-4cfa-4044-a9ff-c330457e8488.png)

Roughness = 1.0 + normal map + roughness map:
![ShareX_sOzLOPsCWT](https://user-images.githubusercontent.com/491704/195068071-9d0558cf-aaf3-4d32-8934-f159e865999a.png)

Let me tweak the floor material to make the reflection more visible:

Roughness = 1 + roughness map:
![image](https://user-images.githubusercontent.com/491704/195068479-ae34d9d9-a24a-4d16-b415-0a98b79e037d.png)

Roughness = 1 + normal map + roughness map:
![image](https://user-images.githubusercontent.com/491704/195068596-3565fc80-fffc-455a-b469-df5727b4842e.png)

These streaks are even more distracting in motion, as they flicker back and forth.

### Steps to reproduce

1. Enable SSR
2. Make your material reflective but a bit rough
3. Add a normal map to vary the surface normals
4. Observe the strange horizonal streaks

### Minimal reproduction project

[SSR Test.zip](https://github.com/godotengine/godot/files/9754346/SSR.Test.zip)

**Comment by unfa** [comment]
Accidentally I've found a really interesting talk about SSR and I think it could be of use in the effort to improve that feature in Godot:

Presentation:
https://www.youtube.com/watch?v=AzXEao-WKRc

Slides:
https://www.ea.com/frostbite/news/stochastic-screen-space-reflections

**Comment by unfa** [comment]
I wonder - does it make sense to take some code from O3DE and put them into Godot? The engine code can be used under Apache 2.0 or MIT: https://github.com/o3de/o3de

Maybe some of the rendering code could be taken from there and adapted to Godot, or at least used as a close reference.

**Comment by unfa** [comment]
This issue is still present in Beta 12:
![image](https://user-images.githubusercontent.com/491704/212425142-69e18938-fdc5-45a4-a58b-8a76c7f234a9.png)

**Comment by Calinou** [comment]
I can confirm this on 4.0.beta12 (Linux, GeForce RTX 4090 with NVIDIA 525.60.11).

Some observations:

- Enabling 16× anisotropic filtering on the texture SSR reflects on doesn't affect streaks.
- Streaks are more noticeable with heavy SSR settings (lots of steps, fade in/fade out that makes reflections more visible). At the default settings, they're not that noticeable as reflections are shorter.
- Adjusting Max Steps, Fade In, Fade Out, Depth Tolerance has no effect on the streaks.

**Comment by akien-mga** [comment]
Still reproducible in 4.0 RC 1.
