### ISSUE TITLE
Global normalmaps and shaders kill switches

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#6725]
It would be nice to have an option that's capable of turning off shaders and normalmaps on every node that has those assigned. This would allow for better graphics control in games and let people with older PCs to get a performance boost without much trouble of going through all the objects in GDscript and checking them for normalmaps/shaders by yourself.

**Comment by Noshyaar** [comment]
The issue opener deleted their account. I'll close this for now. If this feature is still desired we can open it again.
