### ISSUE TITLE
selecting new ScriptExtension for a Native Extension resource causes a crash

### ISSUE THREAD

**Issue by dark-ether** [godotengine/godot#67267]
### Godot version

4.0 beta 2 and 4.0 commit 28f642097a7986867e4fb7d697764efb4db753bf

### System information

latest archlinux

### Issue description

after creating a Native Extension resource if when selecting its script you select new ScriptExtension and click on the selection box the engine will crash

### Steps to reproduce

1. create empty project 
2. create a native script resource
3. on the RefCounted Tab click beside Script
4. on the dropdown menu select the first option New ScriptExtension
5. click the box beside the arrow it is highlighted in red on the following image
![8_002](https://user-images.githubusercontent.com/64704919/195160556-e3e7232f-8dc4-48c3-934d-0e7747e11e28.png)

**Comment by dark-ether** [comment]
i tinkered a little more with this bug and any resource seems to work, the problem can also be replicated if clicking on the edit option for a ScriptExtension and as a click on the box when it is a gdscript opens the script editor i can be fairly certain the problem is trying to edit a script extension, i tried to just edit a script extension but on the language option there is only gdscript. that may be related.

**Comment by akien-mga** [comment]
Is this still reproducible in 4.0 RC 2 or later?

**Comment by KoBeWi** [comment]
None of the mentioned options seem to be available in a vanilla project.
