### ISSUE TITLE
[4.0 beta3] My own VisualShaderNodeCustom is not recognized from VisualShader editor.

### ISSUE THREAD

**Issue by ledyba** [godotengine/godot#67268]
### Godot version

- 4.0 beta2 mono
- 4.0 beta3 mono
- 4.0 beta4 mono

### System information

Windows 10, Vulkan, RTX6800XT

### Issue description

I created my own custom visual shader node, but not recognized.

### Steps to reproduce

I saved this example plugin to `res://PerlinNoise3D.gd`.

https://docs.godotengine.org/en/latest/tutorials/plugins/editor/visual_shader_plugins.html

Exit and restart editor.
Create new shader graph (Mode: CanvasItem).

Click "Add node" and search "Perlin":

![image](https://user-images.githubusercontent.com/391964/195161099-3add9a78-cae4-4e84-92eb-849155f10c81.png)

I can't find at all!

### Minimal reproduction project

Here:

[BugReport.zip](https://github.com/godotengine/godot/files/9758500/BugReport.zip)

**Comment by clayjohn** [comment]
CC @Chaosus I'm not sure if this is an issue with GDscript, with the editor plugin system or with Visual Shaders.

**Comment by ledyba** [comment]
Not resolved in beta3.

**Comment by clayjohn** [comment]
@ledyba This issue will be closed once its resolved. If the issue is still open, you know it hasn't been resolved. Please don't comment to announce that the issue is still open.

**Comment by ledyba** [comment]
@clayjohn OK, Sorry.

**Comment by Zireael07** [comment]
Issue title has a typo - a "not" is missing. You can edit the title using the edit button up top.
