### ISSUE TITLE
Enable ANGLE for Windows 7 and below

### ISSUE THREAD

**Issue by techtonik** [godotengine/godot#6726]
Godot [compiles with ANGLE](https://github.com/godotengine/godot/commits/master/platform/winrt/include/angle_gl.h) for UWP builds (`winrt`), so #3634 is no more actual (there is choice to use Godot on Windows). However, it only works for Windows 8 and above.

It would be nice to backport support for [ANGLE](https://chromium.googlesource.com/angle/angle/+/master/README.md) backend to non-UWP platforms, such as Windows 7 and below. ANGLE may also be used to run Godot on systems with Vulkan (#3729) drivers, but without OpenGL support (which sounds kind of strange).

**Comment by reduz** [comment]
there is zero gain on running Godot on Vulkan using Angle

On Thu, Oct 6, 2016 at 12:14 PM, anatoly techtonik <notifications@github.com

**Comment by techtonik** [comment]
How about incremental porting from GLES to Vulkan? Or just reusing ANGLE optimizations for Vulkan without inventing own?

**Comment by Noshyaar** [comment]
@reduz does the change to roadmap regarding vulkan affect this request? https://godotengine.org/article/abandoning-gles3-vulkan-and-gles2

**Comment by akien-mga** [comment]
Yes, we won't start using ANGLE on desktop now (apart from UWP which needs it). ANGLE is bad enough in web browsers not to be worth investigating as a workaround for bad OpenGL support.
