### ISSUE TITLE
Renaming nodes doesn't show asterisk (scene modified) next to the scene name in the tab only in the window title.

### ISSUE THREAD

**Issue by viksl** [godotengine/godot#67276]
### Godot version

(mono) 4.0 b1, b2

### System information

Windows 10, Nvidia GTX 1660Ti, Vulkan

### Issue description

As the title says.

### Steps to reproduce

1. Create any node (at least in 3d)
2. Save the scene
3. Rename the node to anything
4. Observer * (scene modified symbol) doesn't show next to the scene name in the scene tab but only in the editor window's title bar.
5. Change any properties of the node to see that asterisk does show in this case.

**Comment by Calinou** [comment]
Can you reproduce this on 3.5.1?

**Comment by viksl** [comment]
@Calinou in 3.5.1 the asterisk appears as expected, it doesn't appear only in 4.0 as far as I checked right now.

**Comment by cooperra** [comment]
I'm investigating this.

**Comment by cooperra** [comment]
I should add that this was more than a cosmetic problem. If someone renamed a node, switched to another scene, then performed an undo, it would fail with errors. The undo code for this action requires the original scene active to work properly.

**Comment by cooperra** [comment]
For posterity, in case someone discovers similar bugs, I bisected this regression to ece3df39386af85b069cbb67ae1893b4365f1bd3. It was a big change to the undo/redo system.
