### ISSUE TITLE
Names of categories in Inspector (perhaps also other editor's parts) sometimes don't get centered until resized.

### ISSUE THREAD

**Issue by viksl** [godotengine/godot#67278]
### Godot version

(mono) 4.0 b1

### System information

Windows 10, Nvidia GTX 1660Ti, Vulkan

### Issue description

As you can see in the picture below the title CharacterBody3D is not center but if I resize the Inspector even a little bit it gets centered immediately, it happened to me on multiple occasions.

I noticed this in b1, I'm not sure if this was fixed in b2 but haven't found and issue right now so I'm reporting this just in case, I haven't had much time in b2 so far so I can't tell either especially since I don't know what exactly triggers this

I'm sorry for reporting this if it was already resolved.

![obrazek](https://user-images.githubusercontent.com/33526847/195194650-1d07b13a-a974-429d-bcbf-48d0c05aabad.png)
![obrazek](https://user-images.githubusercontent.com/33526847/195194993-92978a88-a31f-4d98-a7d0-09df69661925.png)

### Steps to reproduce

I don't know.

### Minimal reproduction project

-

**Comment by akien-mga** [comment]
This was fixed in beta 2.
