### ISSUE TITLE
Target FPS option removed - how to handle low FPS for battery saving on mobile?

### ISSUE THREAD

**Issue by florix91** [godotengine/godot#6727]
**Operating system or device - Godot version:**

**Issue description** (what happened, and what was expected):

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by reduz** [comment]
yeah, we removed this because it was misleading, you can change the phyics
FPS if you want, but the game FPS will be always fixed to your refresh rate.

**Comment by florix91** [comment]
Sorry so how can i set to 15 fps my application for example?



2016-10-06 17:40 GMT+02:00 Juan Linietsky <notifications@github.com>:

**Comment by reduz** [comment]
there is not much of a point in doing this, so this is unsupported

**Comment by reduz** [comment]
you could set the physics fps to 15 and do all your logic in
fixed_process.. but you are most likely doing something wrong

**Comment by freemanfromgodotengine** [comment]
@reduz I was using that trick - lowering from 60 to 30 fps - to lower battery consumption on android devices and as far as I was able to test, it worked, so not entirely 'not much of a point', at least for me.

**Comment by florix91** [comment]
​@reduz yes i was using that trick too for lowering battery consumption on
android devices, and using OS.set_low_processor_usage_mode(true) . And for
me was working great....To not make just game but even little app that will
not consume battery like a game....
however it was under the func _ready():
why cannot i use that?​

2016-10-06 21:26 GMT+02:00 Freeman <notifications@github.com>:

**Comment by CowThing** [comment]
What should I do if I want to have vsync off but not have the game run at several hundred FPS? Many games offer an option to set the FPS cap and set the vsync separately.

**Comment by reduz** [comment]
OS.set_low_processor_usage_mode(bool) is not working currently on Android, it should really be implemented as it' s a great way of saving battery if you are using Godot to make apps and not games.

@RandomShaper would you like to give this a try? basically it means skipping OpenGL redraw of next frame (and keep the current one) if VisualServer::get_singleton()->has_changed() returns false

**Comment by florix91** [comment]
@reduz hope you make OS.set_low_processor_usage_mode(bool) working for
Android and iOS as soon as possible. Thanks

**Comment by RandomShaper** [comment]
I'm researching it.

**Comment by RandomShaper** [comment]
I've found that the check for low CPU usage mode is perfomed at every iteration of the main loop (**main/main.cpp**). Because of that it should already work on every platform.

For instance, on the Android case the callback to re-render the GL surface calls through that code so it should already skip frames and add delays.

Any thoughts on this?

**Comment by florix91** [comment]
On Android this line of code cause a flashing Like mode of the scene Where
it is used
​ OS.set_low_processor_usage_mode(true) at least for me. And juan told us
that is not working on Android at the moment but will be implemented..(i
really hope soon to make apps and not only games).
​

**Comment by reduz** [comment]
Yes, you are already at the OpenGL frame when this callback happens, and
Android controls the swapping of buffers.
The only way this could be implemented in Android is to somehow avoid the
buffer swapping of the current frame.
Still, in GodotView.java, all you get is a callback to draw and Android
seems to swap buffers internally.

**Comment by reduz** [comment]
All I found is this:
https://developer.android.com/reference/android/opengl/GLSurfaceView.html#requestRender()
which could obviously work, but then who calls the frame callbacks? Also
you would have some delay between processing and drawing.

**Comment by RandomShaper** [comment]
Yeah, setRenderMode()/requestRender() seem to be the way to go. I'm 
looking into them…

**Comment by reduz** [comment]
the problem is the delay.. Godot can render in a thread in the worst case,
but I'm wondering if this is not kinda too much


On Sat, Oct 8, 2016 at 4:25 PM, Pedro J. Estébanez <notifications@github.com

**Comment by RandomShaper** [comment]
Not sure if that's what you mean, but GLSurfaceView already employs a 
thread for the frame callbacks. Is blocking the main thread your concern 
here?

**Comment by reduz** [comment]
Godot supports rendering in a thread, so technically it could be possible
(probably with a little work also from the engine side), to run Godot on
the main thread and do rendering in another. This was, however, never done.
If there is no other way to get the low cpu mode to work, I will make sure
threaded rendering works on Android (which is quite some work).

The easy solution would be to simply be able to abort the current frame
being drawn (do not swapbuffers or blit), is this not possible in any way?
Who does perform the swap in GLSurfaceView?

On Sat, Oct 8, 2016 at 4:45 PM, Pedro J. Estébanez <notifications@github.com

**Comment by RandomShaper** [comment]
I think there are two possible workarounds:

  * Since a helper class in GLSurfaceView is the one that performs the
    swap, we could grab a copy of the original from the Android source
    code and modify it to conditionally swap according to our needs.
    Downside: a little bit of maintenance.
  * Another one I'm going to try right now and detail (and PR) if success.

**Comment by RandomShaper** [comment]
My little experiment failed, so here are my options:

1. Grab `GLSurfaceView` from the Android SDK corresponding to the `minSdkVersion` (currently, 14). It employs some private APIs and, although they probably could be stripped out, maintining a patched copy of it is ugly.
2. Play with `EGL_SWAP_BEHAVIOR` set to `EGL_BUFFER_PRESERVED`. That would make almost irrelevant that `GLSurfaceView` swaps unconditionally because the buffer would be preserved. Downsides: 1) it should be set on EGL setup, thus potentially taking some VRAM without knowing beforehand if the low CPU usage mode was going to be used at all, 2) it seems not to be widely supported.
3. In case low CPU is enabled, render to a FBO and just blit it on subsequent render requests. This would be more or less the same as (2), but taking VRAM only if needed. Downside: blitting plus swapping is more energy demanding than just skipping the frame.
4. Decouple process and rendering on `Main::iteration()` so we can call the process part unconditionally and the render part as needed. Not sure about how easy would this be and that would still require adding some more threading to the specific code of each platform.

(3) could be a transient solution until Godot main loop is rearchitected, couldn't it?

**Comment by kubecz3k** [comment]
I was using this option as well, to lower power consumption on some mobile devices... If original function was misleading then maybe it just should be renamed to something like 'set_idle_process_fps'  or something?

**Comment by florix91** [comment]
Yeah would love to have it again for My apps...

**Comment by akien-mga** [comment]
@reduz I think The People™ wants to have this back :) If it was misleading, maybe we should readd it under a new name and/or with good documentation explaining what it can be used for or not.

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by RandomShaper** [comment]
AFAIK, _target fps_ is not coming back, so the remaining issue here is low-CPU mode not working well on Android.

I suggest to close both this and #7980 since #19304 is about the same but reported about 3.0.

**Comment by akien-mga** [comment]
Sounds good to me, thanks.
