### ISSUE TITLE
KinematicBody2D + CapsuleShape2D move problem with one way StaticBody2D

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#6728]
**Operating system or device - Godot version:**
Windows 7/Ubuntu 16.04 64bit - Godot v2.2alpha.custom.build (fixnum - 09/22)

**Issue description** (what happened, and what was expected):
What happens: With the player character of the new platformer demo that uses `move_and_slide` (and a `CapsuleShape2D`), if you jump just on the corner of a one way platform (`StaticBody2D`), the player gets stuck (on Y axis) for a moment then is pushed down.

What was expected: If the kinematic controlled character that uses a capsule shape collider jumps to the corner of a one way `StaticBody2D`, it should either be pushed up or ignore the obstacle.

It can be reproduced with the old kinematic character controller too (the one from the demo) with a shorter effect, I was unable to reproduce it with a rectangle collision shape, is possible that the `CapsuleShape2D` has issues with `move` in this case.

**Steps to reproduce:**
-Load the new platformer demo OR the attached project.
-Jump and try to reach the border of a one way platform as shown in the animation below.
-Try again with other collision shapes on the player scene.

![onesidestuck](https://cloud.githubusercontent.com/assets/10215987/19159106/98428ef2-8bc1-11e6-8af7-2ab280e3ba4e.gif)

**Link to minimal example project** :
Simplified new platformer demo with two controller scripts (Platformer demo and Kinematic Character demo).

[onesidebug.zip](https://github.com/godotengine/godot/files/514191/onesidebug.zip)

PS: Credits to my little niece for the find.

**Comment by vnen** [comment]
I've seen this too, but forgot to open the issue.

**Comment by eon-s** [comment]
This is not affecting 3 right now, can be tagged as 2.1 where still happens.

Example modified to work with 2.1:
[onesidebug.zip](https://github.com/godotengine/godot/files/1465307/onesidebug.zip)

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by eon-s** [comment]
This currently only affects 2.1, I will wait for one collision fixes that may bring back this problem on 3.

**Comment by akien-mga** [comment]
One way collisions were improved a lot in the master branch, is it still valid now? Or maybe it's superseded by one of the recent issues about such one-way collision mishaps?

**Comment by eon-s** [comment]
I have tested this on after the one side fixes on master and everything seems to be running fine.

**Comment by eon-s** [comment]
Still valid for 2.1, but maybe a wontfix there...

**Comment by akien-mga** [comment]
Yes, I don't think we should hope for a fix in 2.1 at this point. Someone adventurous could aim at backporting all physics fixes done since 2016 in the master branch, but I wouldn't even agree to merge them, so... :)
