### ISSUE TITLE
Console not showing in 3.5/4.0 in Windows

### ISSUE THREAD

**Issue by fracteed** [godotengine/godot#67293]
### Godot version

3.5.1 and 4.0 alpha 2

### System information

Windows 10 960m

### Issue description

I have just moved over to 3.5 from 3.4 and am not getting the console opening up any more. Has something changed recently? Are the official builds now built with the console option off?

This is happening in 4.0 alpha for me as well.

### Steps to reproduce

Open a project in Godot. No console is present.

**Comment by akien-mga** [comment]
This is intentional. Automatically starting a console is not compatible with Windows 11's new terminal.

Now Windows behaves like Linux and macOS builds, it prints output to the console if you run it from one. There's a .CMD script you can use that starts Godot from a console.

**Comment by fracteed** [comment]
Thanks @akien-mga  got it working now!
