### ISSUE TITLE
Black screen on Linux debug build when checking a file in "user://" folder

### ISSUE THREAD

**Issue by henriquelalves** [godotengine/godot#67292]
### Godot version

4.0 beta 2

### System information

Linux (PopOS), NVidia GeForce GTX 960M

### Issue description

Using the following code on an autoload:

```
const FILE_PATH = "user://totally_not_highscore"

func _ready() -> void:
	if not FileAccess.file_exists(FILE_PATH):
		pass
```

Makes the project show only a black screen with no errors in the console. This only happens on the Debug Build running from the editor; the project exported to Android runs normally.

### Steps to reproduce

Copy the code above on an autoload node.

**Comment by rsubtil** [comment]
Can't reproduce this on the latest 4.0 commit, can you check if it still occurs with the most [recent RC](https://godotengine.org/article/release-candidate-godot-4-0-rc-5/)?

Project created according to steps: [Tmp.zip](https://github.com/godotengine/godot/files/10830985/Tmp.zip)
