### ISSUE TITLE
Document Vector2 and Vector3 being switchable to 64-bit floats using a `float=64` build

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#67308]
### Godot version

v3.5.rc4.official [e047c5006]

### System information

Mac OS

### Issue description

When large numbers are used in a Vector2 the value is not stored correctly

### Steps to reproduce

```gdscript
	var input = 2147483647
	var output = Vector2(input, 0.0)

	assert(input == output.x)
```

**Comment by tavurth** [comment]
So I would like the values to be closer without using int if possible:

```gdscript
	var input = 1665583811
	var output = Vector2(input, 0.0)

	prints(input, output.x, input - output.x)
```
Gives:
```
1665583811 1665583872 -61
```

61 points of error here? 🤔

**Comment by tavurth** [comment]
The following has differing input, but results in the same output. I guess it's some truncation?

```gdscript
	var input = 99999999999
	var output = Vector2(input, 0.0)
	prints(input, output.x, input - output.x)

	input = 99999999000
	output = Vector2(input, 0.0)
	prints(input, output.x, input - output.x)
```

```
99999999999 99999997952 2047
99999999000 99999997952 1048
```

**Comment by Sauermann** [comment]
As mentioned by Zireael07, try instead this:
``` GDScript
	var input = 99999999999
	var output = Vector2(input, 0.0)

	print(is_equal_approx(input, output.x)) # prints true
```
Link to [documentation](https://docs.godotengine.org/en/stable/classes/class_@gdscript.html?highlight=is_equal_approx#class-gdscript-method-is-equal-approx).

**Comment by KoBeWi** [comment]
Vectors use 32-bit floats by default. If you want 64-bit floats (doubles), you need to compile a custom build with `float=64` flag.

**Comment by KoBeWi** [comment]
Well, 64-bit floats use twice as much memory and are also slower. But not sure if it's really a problem nowadays or just a legacy thing 🤔 A proper double support was added only recently AFAIK.

**Comment by tavurth** [comment]
Hmm, maybe then we should open a proposal for a `Vector2d()` which would support the 64 bit version?

**Comment by tavurth** [comment]
> As mentioned by Zireael07, try instead this:

I should mention the use case here is more about floating point errors on the edge of a user space.

**Comment by Calinou** [comment]
You can compile Godot with `float=64` to get higher precision at the cost of performance and memory usage. This makes Vector2/3 use doubles instead of floats.

**Comment by kleonc** [comment]
BTW [`Vector2i`](https://github.com/godotengine/godot/blob/15b68f760149aa71368e9aa35255690fd75427e6/core/math/vector2i.h#L40-L61)/[`Vector3i`](https://github.com/godotengine/godot/blob/15b68f760149aa71368e9aa35255690fd75427e6/core/math/vector3i.h#L40-L57)/[`Vector4i`](https://github.com/godotengine/godot/blob/15b68f760149aa71368e9aa35255690fd75427e6/core/math/vector4i.h#L40-L59) always use 32-bit integers... Meaning now there's the same problem for them as there was for their non-integer counterparts in `3.x`: there's no way to make them be 64-bit. I wonder if it was overlooked or if it is intentional.

**Comment by kleonc** [comment]
> I'd say `float=64` should make those use 64-bit integers as well, but in this case the `float` option name is misleading slightly_smiling_face

I think I agree, there's probably no need to make separate options for ints/reals. And yeah, then `float` would be misleading indeed.
 
> Maybe the option should be renamed to `precision=64` or `precision=double` (with the default being `precision=single`)? This may help avoid confusion with 32-bit/64-bit CPU architectures too.

I'd prefer `32`/`64`, more verbose to me (but `single`/`double` would be fine too). If `precision=64` is unclear then it's probably `precision` being not precise enough.:upside_down_face:

Of course these changes will introduce something like `int_t` as a counterpart to `real_t` and thus massive changes to the whole codebase but feels like it needs to be done.

**Comment by akien-mga** [comment]
`real_t` exists for a specific need for huge worlds where the distance to origin (floating point) reaches values where the precision errors are too problematic.

I don't think there's the same need for integers and so I think you're discussing a badly outlined proposal here. We don't *need* to support `Vector2/3/4i` of 64-bit int if there's no significant use case for it that warrants making the codebase significantly more complex and doing custom builds. There might be use cases for it, but they're likely not the same as the use cases for `real_t`, and may not be compelling enough to justify implementing it. Users can store 64-bit integers in Array, Dictionary, or PackedInt64Array already.

**Comment by tavurth** [comment]
So there still seems to be a bug there:

Using the latest Unix timestamp as an `x value` in a `Vector2` gives an incorrect value, even though the value should fit into an `int32`

```gdscript
	print(Vector2(1666666666, 0).x)
```

Results in `1666666624`. Is that a floating point or rounding error?

**Comment by kleonc** [comment]
> Using the latest Unix timestamp as an `x value` in a `Vector2` gives an incorrect value.
> 
> The value should fit into an `int32` (`0x7FFFFFFF`, or `2,147,483,647`)

That's true for `Vector2i`, not for `Vector2`. In case of a `Vector2` the integer you're assigning is converted to a 32/64 bit floating point number (depending on the build).

>however:
> 
> ```gdscript
> print(Vector2(1666666666, 0).x)
> ```
> 
> Results in `1666666624`.

[That's expected for 32-bit floats](https://en.wikipedia.org/wiki/Single-precision_floating-point_format#Precision_limitations_on_integer_values).
2<sup>30</sup> < 1666666666 < 2<sup>31</sup>
so it rounds to a multiple of 2<sup>30 - 23</sup> = 128 (and 1666666666 % 128 = 42).

>Is that a floating point or rounding error?

Kinda both. :smile:
