### ISSUE TITLE
RPC ID Error thrown when calling an rpc_id to client from OnPeerConnected

### ISSUE THREAD

**Issue by bitmammoth** [godotengine/godot#67305]
### Godot version

v4.0.beta.mono.custom_build [880a0177d]

### System information

Ubunutu 2021

### Issue description

When using the peer connected event to obtain the connection/player id and send a rpc_id(player_id,"RpcName") to the client I am being faced with this error:
```  _Peer_Connected: Attempt to call RPC with unknown peer ID: 398874693.
  <C++ Error>    Method/function failed.
  <C++ Source>   modules/multiplayer/scene_rpc_interface.cpp:312 @ _send_rpc()
  <Stack Trace>  Server.gd:20 @ BreakMe()
                 Server.gd:16 @ _Peer_Connected()```
```

It happens in both C# and GDScript.

### Steps to reproduce

Connect Client and Server in the minimal project

Edit: Just realized I called the Rpc directly in that example, RpcName() but it has the same result with 	

```gdscript
rpc_id(player_id,"BreakMe")
```

So I am not sure that makes a difference.

### Minimal reproduction project

[RpcIdError.zip](https://github.com/godotengine/godot/files/9765223/RpcIdError.zip)

**Comment by bitmammoth** [comment]
Just tested this on windows as well as beta 2 and it repeats the same error on all systems.

**Comment by bitmammoth** [comment]
Update I was able to solve this by adding a 1 second timer before running the rpc_id. Does the id not populate instantly?

**Comment by Faless** [comment]
You should not connect to the `ENetMultiplayerPeer` signals, but the `MultiplayerAPI` signals. I.e.:

```
	multiplayer.peer_connected.connect(_Peer_Connected)
	multiplayer.peer_disconnected.connect(_Peer_Disconnected)
```

and not:

```
	network.peer_connected.connect(_Peer_Connected)
	network.peer_disconnected.connect(_Peer_Disconnected)
```

**Comment by bitmammoth** [comment]
Tested and confirmed that was my issue on both c# and gdscript. Thank you so much! I appreciate it and am closing this issue now.
