### ISSUE TITLE
Cant play any game made with Godot

### ISSUE THREAD

**Issue by SeanTheExtraGuy** [godotengine/godot#67315]
### Godot version

N/A

### System information

Windows 10 64bit, Asus ROG b550-f MB, 32gb RAM, Ryzen 9 3900x, Nvidia Geforce RTX 3080

### Issue description

I'm not a developer, just someone who is having issues with Godot on the gaming side of things. I started a reddit thread asking for help. And was told to open up an issue here. https://www.reddit.com/r/godot/comments/y0iia6/cant_play_games_made_in_the_godot_game_engine

Basically, I can't play any game that has been made with this engine. 3 games in particular. And they all do the same thing. I can hear sound, but can't see anything. Tried all the suggestions. Even installed the actual dev tools, and funily enough that works and I can even start a tech demo up without issue.

I don't know what is causing this. I have no such issue with any other game engine like Unity or Unreal for example or any issue with opengl, direct x, or Vulkan

### Steps to reproduce

I just open a game and the game remains at either a black screen or at the Godot splash screen. Sounds in the game will play and I think gameplay is happening but I don't know.

### Minimal reproduction project

https://microtonalmatt.itch.io/beeknighted
https://warrrkus.itch.io/stargazing-64
https://warrrkus.itch.io/house-of-necrosis

**Comment by Calinou** [comment]
Do you have MSAA forced in the NVIDIA Control Panel? Set it to Application Controlled instead: https://github.com/godotengine/godot/issues/18320

**Comment by SeanTheExtraGuy** [comment]
It worked! I had it set to "enhance application setting". Never affected any other game like this but I mean hey, I can now play the games and see everything. Something so simple... thank you very much! I will let the redit thread know for anyone else needing a fix.
