### ISSUE TITLE
Physical Light Units break Default Omni/Spot Lights

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#67310]
### Godot version

4.0 Beta 2

### System information

Windows 11, Vulkan, GTX 1050 Ti 516.94

### Issue description

Left = Default,  Right = Expected

Physical Light Units
![image](https://user-images.githubusercontent.com/50302479/195375457-fda37093-5ccd-44fe-99e6-6818c793450e.png)

Non Physical Light Units
![image](https://user-images.githubusercontent.com/50302479/195375908-dc0cbd82-733a-46c9-863c-866d0f2d395e.png)

### Steps to reproduce

Toggle Physical Light Units on and off in Projects settings

### Minimal reproduction project

[Lights.zip](https://github.com/godotengine/godot/files/9766059/Lights.zip)

**Comment by clayjohn** [comment]
For other users stumbling on this issue in the meantime, there are two primary quirks that users need to be aware of when using Physical Light Units:
1. default exposure is tuned to match the default lighting (one DirectionalLight3D and ProceduralSky background). The default brightness of the DirectionalLight3D is 100,000 lux (roughly the sun's brightness at midday) and the sky is 30,000 nits (roughly the earth's sky brightness at midday). Omnilights and Spotlights are significantly dimmer than DirecrtionalLights by an order of about 500x. This means to use OmniLights and spotlights, exposure needs to be adjusted to match their range.
2. The default background brightness is 30,000 nits. So when used in a scene light this, the background dominates the scene luminance and will have the biggest impact on auto exposure. Meaning that auto-exposure won't be able to properly expose your scene for the dim omni/spot lights when the background is so bright. 

In the MRP reducing the background to 50-100 nits and increasing the exposure multiplier to 200-500 brings the scene luminance into expected levels

**Comment by clayjohn** [comment]
Fixed by https://github.com/godotengine/godot-docs/pull/6390
