### ISSUE TITLE
no code completion between function call bracket

### ISSUE THREAD

**Issue by liugangnhm** [godotengine/godot#67337]
### Godot version

v4.0.beta2.mono.official [f8745f2f7]

### System information

Windows10 

### Issue description

no code completion between function call bracket

![image](https://user-images.githubusercontent.com/743845/195495154-7e77a2e1-9f68-4dbd-896d-6cf309ff9e1e.png)

### Steps to reproduce

any where you call function

**Comment by Chaosus** [comment]
It's fixed in https://github.com/godotengine/godot/pull/66759, and will be available in next beta version.
