### ISSUE TITLE
Editor Hangs when highlighting text in output console

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#6734]
**Operating system or device - Godot version:**
Windows 10 Pro x64
Godot 2.1 Stable

**Issue description** (what happened, and what was expected):
Editor Hangs when you highlight text in the  output console that starts alongside the godot engine

**Steps to reproduce:**
In the output console highlight any string of text, then in the editor click the play button.

**Link to minimal example project** (optional but very welcome):

**Comment by vnen** [comment]
This is a Windows problem, I don't think we can do anything about it.

**Comment by vnen** [comment]
Well, maybe it's possible to disable Quick Edit mode. This will avoid people from highlighting the text directly though, it would be needed to select the option to mark text from the console window menu. It'll will still hang, just would be harder to highlight.

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by vnen** [comment]
We should probably just remove the console window as requested in #17889.

**Comment by akien-mga** [comment]
Closing as superseded by #17889 then.
