### ISSUE TITLE
Confusing syntax error when using type hint for property setter

### ISSUE THREAD

**Issue by bend-n** [godotengine/godot#67341]
### Godot version

4.0.beta2

### System information

ArchLinux x11

### Issue description

Typed variables setters values are not typed with custom classes.

```gdscript
var bug: classy:
  set(value):
    bug.bug

class classy:
  pass
```
They are also not type-able: 
"`Expected ")" after parameter name.`"
![image](https://user-images.githubusercontent.com/70787919/195530992-328ae15b-cec7-423e-a255-70c6bb324026.png)

### Steps to reproduce

```gdscript
var bug: classy:
  set(value):
    bug.bug

class classy:
  pass
```

**Comment by KoBeWi** [comment]
This applies to any class, you can't have typed setters at all.
```GDScript
var something: int:
    set(sth: int):
        pass
```
also fails.

Not sure if that's intended tbh. The type is implicit.

**Comment by akien-mga** [comment]
That's expected indeed since the type is already defined.

But maybe the UX could be improved, with either:
- Allowing the type hint anyway as long as it matches the property type
- Or at least providing a better error message

**Comment by bend-n** [comment]
> That's expected indeed since the type is already defined.

Precisely: the type is already defined.

Why is it that
```gdscript
var bug: classy:
  set(value):
    bug.bug # this does not throw a error? I would expect it to.
```

**Comment by KoBeWi** [comment]
> bug.bug # this does not throw a error? I would expect it to.

That's because you can do
```GDSCript
var bug: classy = class_with_bug.new():
  set(value):
    bug.bug # correct

class class_with_bug extends classy:
    var bug = true
```
This applies to typing in general. Non-existent members are not detected at parse time, because they can exist in derived classes. Only simple types (Vector2, Array, Basis etc.) check against that, because you can't extend them.

**Comment by djpeach** [comment]
Got my syntax from here: https://gdscript.com/articles/godot-4-gdscript/ I don't know who is running that site, but that should be fixed

**Comment by KoBeWi** [comment]
That website is not officially maintained by Godot team, so you should contact its author (there is About section at the bottom).

**Comment by dalexeev** [comment]
I think the error message is fine as is. Instead, we can clarify the [documentation](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#properties-setters-and-getters).
