### ISSUE TITLE
GDExtension restart dialog appears before asset download complete dialog when downloading GDExtension assets from AssetLib

### ISSUE THREAD

**Issue by Yagich** [godotengine/godot#67357]
### Godot version

4.0b2

### System information

Linux/Manjaro

### Issue description

When downloading an asset from AssetLib that contains a GDExtension plugin, after the download is complete, the prompt to restart the engine appears before the "download finished" dialog. This is a pretty minimal UX nitpick, but IMO the dialog informing the user that the download has finished should be shown first, or perhaps the two could get merged into one.

### Steps to reproduce

Download a GDExtension asset from AssetLib and observe the dialog order

**Comment by KoBeWi** [comment]
No restart dialog appears anymore. I think this was fixed in 4.2.
