### ISSUE TITLE
Click-drag ScrollContainer does not work 4.0beta2

### ISSUE THREAD

**Issue by shafnaz** [godotengine/godot#67352]
### Godot version

4.0Beta2

### System information

Windows 10

### Issue description

![image](https://user-images.githubusercontent.com/37254287/195635449-045461f9-254b-4af4-8a9f-f8a39ee067a9.png)

In 3.5, mouse click drag scroll worked. It seems not to be working here. Or am I missing something here?
I've tried GridContainer, FlowContainer as well.
I don't know if this is also an issue for mobile devices. Haven't tried that.

### Steps to reproduce

Create a ScrollContainer with VboxContainer as child. fill it with buttons, set everything to mouse_filter PASS
 
or 

Add the scene file from the .zip your Godot project and run it.

### Minimal reproduction project

[testscroll.zip](https://github.com/godotengine/godot/files/9778094/testscroll.zip)

**Comment by shafnaz** [comment]
![image](https://user-images.githubusercontent.com/37254287/201235302-eaf83a75-a63b-4d7d-89a0-2860fcae4aee.png)
No signals emitted when clicking on buttons that are in ScrollContainer

**Comment by shafnaz** [comment]
![image](https://user-images.githubusercontent.com/37254287/201235635-2dc3d9e7-ed36-4e5d-9640-bb0ca54eff31.png)
After enabling "expand", the buttons do work and fixes the issue, 

Still, It should work by default.

"expand" enabled
![image](https://user-images.githubusercontent.com/37254287/201235723-a000b8bd-17d6-40bb-baff-f96a3222691d.png)

"expand" disabled
![image](https://user-images.githubusercontent.com/37254287/201235844-bb5cb9a9-fbf6-4db2-987c-552ff198b1fd.png)

**Comment by KoBeWi** [comment]
Seems to work correctly in rc5.
