### ISSUE TITLE
Godot on Flatpak burns full CPU core scanning for joypads

### ISSUE THREAD

**Issue by nyanpasu64** [godotengine/godot#67355]
### Godot version

3.5.1

### System information

Void Linux, Flatpak

### Issue description

The Flatpak Godot burns a full CPU core nonstop, starting from the project picking menu, and continuing once you open a project. It also takes a long time to close the window.

This arises from a probable Godot bug rather than a Flatpak packaging error.

### Steps to reproduce

`flatpak run org.godotengine.Godot` and watch your CPU usage.

## Debugging

To debug, first I installed symbols:

```sh
flatpak install org.godotengine.Godot.Debug  # must restart gdb or something, maybe the shell entirely, for gdb to see debug symbols
flatpak run --command=sh --devel org.godotengine.Godot
```

In the Flatpak shell:

```sh
export APPDATA="$XDG_DATA_HOME"
gdb /app/bin/godot-bin
```

Normally I'd open htop, show threads, identify the thread burning CPU, then view it in gdb. But unfortunately thread IDs in the host OS differ from thread IDs in the Flatpak, and I don't know how to translate host TID/PIDs into sandbox TID/PIDs (**if anyone knows let me know!**). So I have to debug from within the sandbox. `--devel` lacks `htop` but we can use `top -H` instead to view threads. However we need to run `top` while the app is running to find which thread is burning CPU, and running a second `flatpak run --command=sh --devel org.godotengine.Godot` doesn't see the processes in the first.

My "solution" was to open a host (not Flatpak) terminal, run `kill -s SIGSTOP gdb` and `kill -s SIGCONT gdb` while the app was running, then go to the Flatpak terminal and run `top -H` and log the TID of the thread burning a CPU core. Then I'd run `fg` to activate gdb, ^C to interrupt, `info threads` and find the thread number corresponding to the TID (always 14 so far), `t 14`, then `bt`.

(An alternative approach would be to run `godot &`, then `top -H` and record the TID, then `gdb -p TID or PID`.)

```
#0  0x0000000000a4af67 in JoypadLinux::monitor_joypads (this=<optimized out>) at platform/x11/joypad_linux.cpp:214
214                             while ((current = readdir(input_directory)) != nullptr) {
(gdb) bt
#0  0x0000000000a4af67 in JoypadLinux::monitor_joypads (this=<optimized out>) at platform/x11/joypad_linux.cpp:214
#1  JoypadLinux::monitor_joypads_thread_run (this=<optimized out>) at platform/x11/joypad_linux.cpp:128
#2  JoypadLinux::monitor_joypads_thread_func (p_user=<optimized out>) at platform/x11/joypad_linux.cpp:107
#3  0x0000000002f85d00 in Thread::callback (p_self=<optimized out>, p_settings=..., p_callback=0xa4aed0 <JoypadLinux::monitor_joypads_thread_func(void*)>, p_userdata=0x599a430) at core/os/thread.cpp:78
#4  0x00000000034e23f5 in std::execute_native_thread_routine (__p=0x599a1c0) at ../../../../../libstdc++-v3/src/c++11/thread.cc:82
#5  0x00007ffff7b483ba in start_thread (arg=0x7fffcdc16640) at pthread_create.c:481
#6  0x00007ffff75da7a3 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

This pointed to https://github.com/godotengine/godot/blob/3.5.1-stable/platform/x11/joypad_linux.cpp#L206 `void JoypadLinux::monitor_joypads()` with no arguments. Perhaps `UDEV_ENABLED` is not set on Flatpak (or `udev_new` fails, but perhaps not since I don't see a `Failed getting an udev context` log), but it's set on native Void Linux? Didn't check.

## Diagnosis

This function has a likely bug (unchanged in master https://github.com/godotengine/godot/blob/master/platform/linuxbsd/joypad_linux.cpp#L202): instead of waiting 1 second between scanning `/dev/input`, it scans `/dev/input` nonstop (burning CPU) and sleeps 1 second *after* `JoypadLinux::~JoypadLinux()` sets `monitor_joypads_exit`.

I think the solution is to move the sleep into the loop. Ideally this should be backported to Godot 3 as well, unless 4 is releasing very soon (and even then, perhaps should be backported for people working on Godot 3 projects).

- Should Flatpak not be using the no-udev mode in the first place?
- Is it possible to abort the sleep early if `monitor_joypads_exit` is set?

**Comment by Calinou** [comment]
See https://github.com/flathub/org.godotengine.Godot/issues/108.
