### ISSUE TITLE
Proposal for Godot to accept Bitcoin contributions

### ISSUE THREAD

**Issue by songproducer** [godotengine/godot#6736]
Hi!

I like Godot and would like to contribute some bitcoin for helping develop more features. The Bitcoin community is quite big and I am sure there would be others who'd contribute too.

Accepting Bitcoin has pros and cons.

Pros:
- Accept donations from around the world
- Very fast and mobile (get money to developers, whichever country they're in)

Cons:
- Keeping bitcoins secure is not common knowledge
- Learning about the various wallets and signing up to exchanges is a significant barrier

Other considerations:
- Bitcoin can be volatile at times, though recently it has been less of an issue. If Godot were to accept Bitcoin contributions, would they be immediately converted to fiat (harder to set up) or converted semi-regularly?

I've been actively using bitcoins for over 5 years and am happy to help / advise if the developers, Juan Linietsky and Ariel Manzur would like to proceed.

I also have a secure hardware wallet capable of holding separate account Bitcoin funds if a custodian method is preferred.

**Comment by ret80** [comment]
A good idea!
You can go even further and create a Godot coin. Or create an assets in NXT :)

**Comment by songproducer** [comment]
Adding incentives via a Godot coin is an ambitious project and would only work if the majority of developers were on-board.

I'd like to gauge developers' interest in accepting crypto-currencies as well as a Godot coin to help with incentives, but not sure if this is the right place to do it.

**Comment by ret80** [comment]
People are trading on the stock exchange to buy and sell everything if they think they can make money on it. If the beautifully present the new coins there is a chance that it will start to trade. And the money to hire people for the support and development of the engine. At least this experiment is not so difficult. It is necessary to draw beautiful section on the site, spread the links and sell coins (I simplify things a bit but the essence does not change).

**Comment by Noshyaar** [comment]
Since we have Patreon and I don't think Free Software Conservancy allows donations in Bitcoin, this is not likely to happen. I'll close this.

**Comment by akien-mga** [comment]
Actually Conservancy supports Bitcoin donations since a few months (they needed to to receive money from the Pinapple Fund), so we could likely accept those... But I prefer not to until there is a *strong* community support for having this as an option. We already accept donations in USD and EUR, and I don't see much point adding a third currency as volatile (and hard to use in real life) as BTC.

**Comment by JosiasAurel** [comment]
its true it might not be right or even late but i am for the acceptance of bitcoin in th godot game engine. it will help alot of devs in hard regions to reach. what about making a godot plugin for that. it might be the best choice for now

**Comment by akien-mga** [comment]
Godot doesn't concern itself with monetization of Godot games - if you want to accept bitcoins for your game's monetization, it's up to you/the community to develop a module/plugin for bitcoin payment processing.

**Comment by RedFT** [comment]
Can you imagine if the Godot Foundation had accepted bitcoin donations back in 2016?.. No game developer today would have to go hungry. 🥹
