### ISSUE TITLE
Binding error for C#'s Shader create from SpirV

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#67369]
### Godot version

4.0 beta 2

### System information

manjaro linux

### Issue description

When you pass the RDShaderSPIRV ref to the RenderingDevice.ShaderCreateFromBytecode, it expects a `byte[]` but the right one is the reference as shown here:

https://github.com/godotengine/godot/blob/926429392a73a0c2261bc4ed4503c99025842d7c/servers/rendering/rendering_device.cpp#L219

thanks to @clayjohn for finding it

![image](https://user-images.githubusercontent.com/58845030/195720230-9c8628d9-e941-450b-acf7-ea51349980c7.png)

### Steps to reproduce

just follow compute shaders documentation: 

https://docs.godotengine.org/en/latest/tutorials/shaders/compute_shaders.html#create-a-local-renderingdevice

### Minimal reproduction project

N/a

**Comment by raulsntos** [comment]
In your screenshot you are using the method `ShaderCreateFromBytecode` but the method you seem to be looking for is `ShaderCreateFromSpirv`.

**Comment by nonunknown** [comment]
you're right, sorry for my lack of attention! I tested here and worked fine
