### ISSUE TITLE
In Tile Map, tile_data int array y axis increases/decreases by 65536 for 1 step while x increases by 1

### ISSUE THREAD

**Issue by roysubhra** [godotengine/godot#67377]
### Godot version

4.0 Beta 2

### System information

Windows 11

### Issue description

In Tile Map, tile_data int array y axis increases/decreases by 65536 for 1 step while x increases by 1. 
Example:
` layer_0/tile_data = PackedInt32Array(0, 0, 3, 65536, 0, 3, 1, 0, 3, -65536, 0, 3, -131072, 0, 3, 131072, 0, 3)`
it should really be 
`layer_0/tile_data = PackedInt32Array(0, 0, 3, 1, 0, 3, 1, 0, 3, -1, 0, 3, -2, 0, 3, 2, 0, 3)`
This makes it difficult to programmatically generate the TileMap data. For a single position shift the Y axis value should also increase by 1

### Steps to reproduce

Create any tilemap check the saved data

**Comment by groud** [comment]
No, I think you don't get it. Both the X and Y coordinates are stored in a single integer value. The value you get is thus something like this: `X + 65536 * Y`. Here is the packing code:
```
	for (const KeyValue<Vector2i, TileMapCell> &E : tile_map) {
		uint8_t *ptr = (uint8_t *)&w[idx];
		encode_uint16((int16_t)(E.key.x), &ptr[0]);
		encode_uint16((int16_t)(E.key.y), &ptr[2]);
		encode_uint16(E.value.source_id, &ptr[4]);
		encode_uint16(E.value.coord_x, &ptr[6]);
		encode_uint16(E.value.coord_y, &ptr[8]);
		encode_uint16(E.value.alternative_tile, &ptr[10]);
		idx += 3;
	}
```
And there no other way around it unless we double the size of each field, as we can store things only per integer (32 bits) using a PackedInt32Array, or per byte (8 bits) with a PackedByteArray. There's no Packed16BitsArray or something like that.

**Comment by Zireael07** [comment]
Heh. I thought the answer was "packing" as soon as I saw this issue, but not being familiar with Godot's internals I didn't comment.

**Comment by roysubhra** [comment]
Thanks. I get it now.

Regards,
Subhra

**Comment by groud** [comment]
I guess we won't change that for now. If anyone need a 32bit TileMap we'll see whether to change it, but that's for another proposal. Closing this issue for now then.
