### ISSUE TITLE
`OptionButton` menu blocks graphics elements above and the retrieving of mouse position information

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#67382]
### Godot version

926429392a73a0c2261bc4ed4503c99025842d7c

### System information

Windows 11

### Issue description

Using the `OptionButton` with custom animated sprite cursors is incorrect, because 

1) The popup menu clips the cursor sprite rendering
2) It blocks the information from the `get_viewport().get_mouse_position()` function which needs to be retrieved to correctly update the position of such cursors

![option_button_bug](https://user-images.githubusercontent.com/3036176/195791283-96512d05-8bb4-448a-ae4a-fb7bd0597564.gif)

### Steps to reproduce

- Create an `OptionButton`
- Create a `Sprite`, representing a cursor with a position setted in a process function
- For better visibility, disable the system cursor using (`DisplayServer.mouse_set_mode(DisplayServer.MOUSE_MODE_HIDDEN`)
- Try to interact with a `OptionButton` menu

It's better to be reproduced with a demo project

### Minimal reproduction project

[CursorBug.zip](https://github.com/godotengine/godot/files/9783705/CursorBug.zip)

**Comment by Sauermann** [comment]
I am not sure, if part 1 can be solved. You want that graphical elements within a `Viewport` appear visually above a different `Window`.
In such cases, you would have to create the mouse cursor as a new `Window`, that is placed above the other `Window`.

**Comment by Chaosus** [comment]
As far as I remember, the embedded windows are parts of the rendering of the main window so, I think there should be a way to display graphical elements above it.

**Comment by Sauermann** [comment]
Embedded viewports are placed on canvas layer `Viewport::SUBWINDOW_CANVAS_LAYER = 1024`.
I just verified, that putting the mouse cursor within a `CanvasLayer` and setting `CanvasLayer.layer = 1025` (anything bigger than 1024) will display the mouse cursor above the popup.
So it seems like part 1 can be achieved by available methods.

**Comment by Chaosus** [comment]
@Sauermann Cool, I didn't know that trick - but this can be achieved only through the script because maximum layer can be setted in the inspector is 128.

**Comment by Sauermann** [comment]
I have updated my PR to include documentation about this trick. That PR should now resolve both parts of this issue.
