### ISSUE TITLE
[Web] 2D doesn't work on Web.

### ISSUE THREAD

**Issue by zaevi** [godotengine/godot#67392]
### Godot version

master (after 367a9b8)

### System information

Win11, Edge

### Issue description

2D doesn't display on web.
We have confirmed that #67335 causes the issue. 

### Steps to reproduce

Download the reproduction project below.

PC:
![image](https://user-images.githubusercontent.com/12966814/195836491-4dd447a6-49f9-42b5-819d-0b36304a172b.png)

Web:
![image](https://user-images.githubusercontent.com/12966814/195837100-859cad1e-552c-4aff-a519-d65c92b7d205.png)

### Minimal reproduction project

[web_issue.zip](https://github.com/godotengine/godot/files/9785666/web_issue.zip)

**Comment by AntonioDell** [comment]
I am not sure if https://github.com/godotengine/godot/pull/67402 really solved this issue.
See my comment on the issue with a minimal project to reproduce: https://github.com/godotengine/godot/pull/67402#issuecomment-1287669240
