### ISSUE TITLE
Cannot Use A SpriteSheet With Pixels More Than 16384.

### ISSUE THREAD

**Issue by pegvin** [godotengine/godot#67394]
### Godot version

v3.5.1.stable.arch_linux

### System information

Manjaro Linux, GLES3

### Issue description

I am making a fps game with doom 1 (1993) styled art, so for guns i'm using a SpriteSheet For my Gun's Animation, Which Contains 93 Frames & Each Frame is 300x210 in Size, & The SpriteSheet's Size is 27900x210.

-- Image Attachment Start --
![Berrata](https://user-images.githubusercontent.com/75035219/195822737-eb298e75-e265-4520-9e24-eccac01d7a3d.png)
--  Image Attachment End  --

I Imported The SpriteSheet in my game but i cannot use it anywhere because Godot Complains Me:

```
The Image width specified (27900 pixels) cannot be greater than 16384 pixels.
Cannot generate mipmaps with width or height equal to 0.
modules/webp/image_loader_webp.cpp:79 - Condition "p_image.is_null() || p_image->empty()" is true. Returned: PoolVector<uint8_t>()
```

is there a way to adjust the maximum image size?

### Steps to reproduce

1. Create A New Godot 3d Project
2. Download The SpriteSheet I've Attached Above & Include It in the project
3. Try To Re-Import it Or Use it in a `Sprite` Node

**Comment by Zireael07** [comment]
No, because this is due to many GPU drivers not supporting such large textures.

Also your pic didn't attach

**Comment by pegvin** [comment]
Pic is Attached, it's really long and small, that's why i've added markers

**Comment by akien-mga** [comment]
As @Zireael07 mentioned, the maximum image size is a hardware constraint, it can't be raised.

**Comment by pegvin** [comment]
For People Reading The Issue Cause They Have The Same Issue, I Fixed It By Converting My Frames To Different Small SpriteSheets Which Is More Ideal & "Performant"? (not sure)

**Comment by akien-mga** [comment]
Note that you can also just use multi rows in a spritesheet. That's why there are `hframe` (horizontal frame count) and `vframe` (vertical frame count) properties in Sprite.

**Comment by Calinou** [comment]
> I am making a fps game with doom 1 (1993) styled art, so for guns i'm using a SpriteSheet For my Gun's Animation, Which Contains 93 Frames & Each Frame is 300x210 in Size, & The SpriteSheet's Size is 27900x210.

Your sprite should probably not be this large. It should only be as large as the largest required size for the animation to display (this is how animated sprites work in actual Doom to avoid wasting memory).

**Comment by pegvin** [comment]
Thanks Alot For That!

**Comment by pegvin** [comment]
Hey @Calinou Can you link some resources to animate using atlases in godot? i've created a atlas and set my texture to the newly created atlas, i found the `TextureRegion` tab in statusbar but couldn't figure out how to use that with my animation player to create animations.
