### ISSUE TITLE
Kerning issues on low resolution viewport and lower font size (oversampling)

### ISSUE THREAD

**Issue by sankto** [godotengine/godot#67401]
### Godot version

4.0 Beta 3

### System information

Windows 11 22H2, RTX 2060

### Issue description

Letter spacing (kerning) in all texts, with default or not fonts, are often horizontally incorrect, when the viewport's resolution is low (e.g. 320x240) and the stretch mode is set at "canvas_item". More apparent when the screen is slowly resized manually.

Picture as example : [Screenshot](https://imgur.com/a/QvWVL6h)
Notice the text in the sword's tooltip.

[Reddit thread](https://old.reddit.com/r/godot/comments/y3glr1/weird_kerning_issue_godot4_beta2/) (nevermind the title, it was started yesterday just before beta 3 release)

### Steps to reproduce

- in project's settings, Window tab, set viewport width & height to 320x240
- in project's settings, Window tab, set window width & height override to something like 1920x1080
- in project's settings, Window tab, set stretch mode to canvas_items
- add a node2d
- add label to node2d
- set label's font size to 8px in "Theme override - font sizes"
- not required but set autowrap to word for the label and resize label to fit the screen (so as to drop a lorem ipsum block of text in it)
- Enter some text in the label
- Start game, slowly drag the borders of the window up & down to see the kerning changing.

### Minimal reproduction project

[kerningbug_beta3.zip](https://github.com/godotengine/godot/files/9788658/kerningbug_beta3.zip)

**Comment by Calinou** [comment]
cc @bruvzg 

For reference, I haven't seen this kind of issue in `3.x`.

**Comment by sankto** [comment]
First off, thank you very much for the fix!

I wanted to add something of note, that i have no idea if it is intentional or not :
If i go in **Project Settings--Rendering--2D**, and turn ON "**Snap 2d vertices to pixel**", i get this troublesome result of weird kerning:
![image](https://user-images.githubusercontent.com/1618880/200229779-e5ea9f49-bd29-4343-9973-aa5666ef9a3d.png)

If turned OFF, i get this pretty normal result:
![image](https://user-images.githubusercontent.com/1618880/200229883-3e1da43d-e96c-4dea-9197-59f06e29df90.png)

**Comment by Calinou** [comment]
cc @bruvzg 

Should font drawing be affected by pixel snap? Not sure if we can find a way to sidestep it only for font drawing.
