### ISSUE TITLE
Using TIME constant in gdshader breaks Debugging in forward_plus renderer

### ISSUE THREAD

**Issue by WatchThemFall** [godotengine/godot#67413]
### Godot version

4.0-beta3

### System information

Windows 10, Vulkan

### Issue description

Using a breakpoint in a project with a running gdshader using the TIME constant breaks debugging. When you try to Step Into, Step Over, Continue, etc. the editor freezes and takes a very long time to move onto the next line of code, if it ever does. Turning the Rendering Method to "mobile" from "forward_plus" in the same project fixes the issue; the issue is only in forward_plus.

### Steps to reproduce

1. Open reproduction project
2. Set a breakpoint on first line of code in "DebugShaderTest.gd" script's _process function (ANY code in a project does this, just an example)
3. Run Project
4. Attempt to Step Into next line of code
5. Debugging freezes and takes a very long time to get to the next line

- Replacing both instances of "TIME" in "water_shader.gdshader" with a set float value fixes the issue.
- Using "set_shader_paremeter" to pass in a custom time variable fixes the issue
- Changing render method to "mobile" fixes the issue

### Minimal reproduction project

[Godot 4 Shader Debug.zip](https://github.com/godotengine/godot/files/9790148/Godot.4.Shader.Debug.zip)

**Comment by clayjohn** [comment]
Fixed by https://github.com/godotengine/godot/pull/72827
