### ISSUE TITLE
4.0 GLES3 renderer, CanvasItem `draw_primitive()` does not correctly handle quads

### ISSUE THREAD

**Issue by MrBlockers** [godotengine/godot#67412]
### Godot version

v4.0.beta.custom_build [39534a7ae]

### System information

Windows 10, GLES3, NVIDIA GeForce RTX 3070

### Issue description

While working on https://github.com/godotengine/godot/pull/67374 I found that draw_primitive on the GLES3 renderer is inconsistent in vertex order from Vulkan when the point count is 4. The following code:

```gdscript
extends Node2D

func _draw():
	var points = [Vector2(0, 0), Vector2(64, 0), Vector2(128, 128), Vector2(0, 64)]
	var uvs = [Vector2(0, 0), Vector2(1, 0), Vector2(1, 1), Vector2(0, 1)]
	var colors = [Color(0,0,1), Color(0,1,0), Color(1,0,0), Color(1,1,1)]
		
	draw_primitive(points, colors, uvs)
```

Results in 

(gl_compatibility):
![image](https://user-images.githubusercontent.com/1747505/195946679-528fdba9-3961-4669-9286-528ebbbb5d9b.png)

(forward_plus):
![image](https://user-images.githubusercontent.com/1747505/195946811-9b7a0de5-aa75-41e5-ac6d-c90a434f334e.png)

I did some quick looking into the GLES3 renderer code and I think this section is to blame:
https://github.com/godotengine/godot/blob/39534a7aecc4ca4215af67244b23dda09ea339f8/drivers/gles3/rasterizer_canvas_gles3.cpp#L1020-L1029

The `j+1` index into the primitives points results in the second triangle being constructed from the 2nd, 3rd, and 4th points in the primitive, which would explain the shape seen above.

### Steps to reproduce

1. Create new project with either forward+ or mobile
2. Set renderer to 'gl_compatibility'
3. Create a Node2D with above script
4. Run and compare between 'gl_compatibility' and 'forward_plus'

**Comment by clayjohn** [comment]
@MrBlockers Thanks for catching this!
