### ISSUE TITLE
Visual Shader Remap Doesn't Work with Multiple Instances

### ISSUE THREAD

**Issue by directrix1** [godotengine/godot#67429]
### Godot version

4.0 Beta 3

### System information

Linux, Radeon 6900

### Issue description

If you add multiple remap nodes to a visual shader then the shader quits working. If you open the code view, you can see it is trying to redefine the variables _input_range and _output_range for each.
![image](https://user-images.githubusercontent.com/474780/195972473-d62a0b31-11e7-439f-98f3-684981af49a1.png)

### Steps to reproduce

Create a visual shader and use two Remaps in the output.

**Comment by directrix1** [comment]
I don't think that will fix this problem, because it is still using the same internal variable names which are redeclared in the same scope with subsequent instantiations of the same object. A solution would involve unique instance prefixing the internal variable names in these shaders.

**Comment by Chaosus** [comment]
> I don't think that will fix this problem, because it is still using the same internal variable names which are redeclared in the same scope with subsequent instantiations of the same object. A solution would involve unique instance prefixing the internal variable names in these shaders.

My PR will fix this issue, because it limits the code for each connection with brackets, and these names are allocated in their own scope...

**Comment by directrix1** [comment]
> 
> My PR will fix this issue, because it limits the code for each connection with brackets, and these names are allocated in their own scope...

My apologies, I didn't notice that in the diff.
