### ISSUE TITLE
Godot logo is wrong in light mode in 'About Godot'

### ISSUE THREAD

**Issue by dom1643** [godotengine/godot#67422]
### Godot version

3.5.1.stable.official

### System information

Windows 10

### Issue description

Using light mode, the Godot logo's negative space is dark instead of light how it should be.
![image](https://user-images.githubusercontent.com/20844484/195964943-1030ed76-fed5-48be-8749-27d311f3cfb5.png)

### Steps to reproduce

Enable the Light preset in Editor > Editor Settings > Theme > Preset
Go into Help > About Godot

**Comment by Calinou** [comment]
This can be fixed by changing the editor logo SVG (not the top-level one) to use `#fefefe` instead of `#ffffff` for the logo's negative space.
