### ISSUE TITLE
Multiple Collision Shapes Causes Game to Crash Without Any Error Logs

### ISSUE THREAD

**Issue by Gamepro5** [godotengine/godot#67424]
### Godot version

4.0 beta 3

### System information

Windows 10, AMD Ryzen 7 3700X 8-Core Processor, Vulkan

### Issue description

Over the past 3 weeks, I've been overhauling move_and_slide() and re-writing it from scratch. I'm almost done, but I needed to solve a specific issue where my ground check move_and_collide test would return a collision when a character body's collision shape is touching a rectangle that is angled such that it is a simple little corner. Essentially, my snap vector in the down direction would detect a collision far above the feet of the player, so I decided to split floor checks and wall checks into different shapes. Unfortunately, no matter what orientation they were in, having more than one collision shape in the tree of a characterbody 3d node crashes the game. My workaround was to do the following:
![image](https://user-images.githubusercontent.com/23440295/195966452-8b37e1db-b1e4-4a4b-b8de-de3a2fec9b2c.png)
This isn't ideal because I need to set bother character controllers as "top level" and change the position of the root node to match the move_and_collide() new position. Would be much easier if I could just have a "current" property like for cameras so the body can know which shape to worry about when doing the next move_and_slide().

### Steps to reproduce

Run anything that has several collision bodies as children of a characterbody controller.

**Comment by rburing** [comment]
I haven't managed to reproduce this. Please attach a minimal reproduction project. Do you get any output when you run Godot via the command line?

**Comment by Gamepro5** [comment]
@rburing I didn't get an input, but I'm not able to recreate it anymore. I also was using the latest version of the godot 4 beta, so I don't really know what happened. Try having a CharacterBody3d node with two immediate collision boxes, and toggling them on and off right before a move_and_collide(). I was debating whether or not to close this because I can't consistently re-create the issue. My project just closes randomly very often, and the only thing even logged is this:
![image](https://user-images.githubusercontent.com/23440295/196013734-35ee1cbd-b2af-4eb9-8bf4-8ae485c2c338.png)

I also sent you a discord friend request because I'm encountering lots of issues with collision detection in this engine, and would like to verify that they are indeed issues that I should make an issue on or if it's my fault. Your suggestion of re-compiling the engine here is something I'd love to try with help.
https://github.com/godotengine/godot/issues/67214#issuecomment-1275342966

Feel free to close this issue.

**Comment by akien-mga** [comment]
Closing as there's no documented way to reproduce this issue.
