### ISSUE TITLE
'Save Branch as Scene' - the branch should immediately be replaced by freshly saved scn instance

### ISSUE THREAD

**Issue by Tybobobo** [godotengine/godot#6742]
When you are saving a selected branch as scene, the scene you just saved should become an instance in your scene.

![image](https://cloud.githubusercontent.com/assets/6776092/19212323/009d5b7e-8d4f-11e6-9527-c054aab0799a.png)

I am confident that majority of people using this feature would want to replace the saved scene into an instance such as this:
![image](https://cloud.githubusercontent.com/assets/6776092/19212334/2650bae6-8d4f-11e6-952c-0809299b66bb.png)

Even if the user did not want to instance the scene, it is far easier to remove an instance than it is delete node, select parent node, open new instance, navigate to saved instance, and select it.

If it is changed to an instance by default, and you dont want the instance, you can just click on the instance icon and select "Discard Instancing".

Hoping this gets changed for the better :)

**Comment by Sslaxx** [comment]
Perhaps it should ask you if you want to replace the node branch with the instanced version.

**Comment by vnen** [comment]
👍

I don't think it needs to ask. If the user don't an instance they can just discard the instancing afterward.

**Comment by eon-s** [comment]
+1 if converting to scene also keep the groups (I use to forget the groups I add to the nodes).
