### ISSUE TITLE
`append_text()` in RichTextLabel causes weird when setting visible_characters

### ISSUE THREAD

**Issue by GTM52** [godotengine/godot#67435]
### Godot version

v4.0.beta2.official [f8745f2f7]

### System information

Windows 10

### Issue description

My goal is to make typewritting animation for RichTextLabel. I played `visible_characters` and it worked well. However, when I try to append the text, it will show more text even if the property `visible_characters` is unchanged.

A workaround is to update the `visible_characters`:
```
visible_characters += 1
visible_characters -= 1
```
after appending the text.

### Steps to reproduce

1. set text to a RichTextLabel
2. set `visible_characters` to `get_total_character_count()`
3. new a timer and append text after timeout
4. the appended text is shown, while `visible_characters` is unchanged

**Comment by Sauermann** [comment]
A minimal reproduction project would help.
I am unable to replicate the described problem with the following code (The characters "ABC" never show up on the screen):

``` GDScript
func _ready():
	var r: RichTextLabel = $RichTextLabel
	r.visible_characters = r.get_total_character_count()
	var timer := Timer.new()
	add_child(timer)
	timer.wait_time = 1.0
	timer.start()
	timer.connect("timeout", Callable(self, "_timeout"))

func _timeout():
	var r: RichTextLabel = $RichTextLabel
	r.text = r.text + "ABC"
	print("appended ", r.visible_characters, " ", r.text)
```

**Comment by Sauermann** [comment]
I am trying to replicate this issue, but the following code doesn't show the described problem for me ("ABC" doesn't appear on screen)
Can you please provide a minimal reproduction project?

``` GDScript
func _ready():
	var r: RichTextLabel = $RichTextLabel
	r.text = "foobar"
	r.visible_characters = r.get_total_character_count()
	var timer := Timer.new()
	add_child(timer)
	timer.wait_time = 1.0
	timer.start()
	timer.connect("timeout", Callable(self, "_timeout"))

func _timeout():
	var r: RichTextLabel = $RichTextLabel
	r.append_text("ABC")
	print("appended ", r.visible_characters, " ", r.text)
```

**Comment by GTM52** [comment]
Sorry, I found that I can replicate the issue only if the original text is multiline. Here is a minimal reproduction project.
The state could be varied on different `visible_characters_behavior` values.
[minimal reproduction project.zip](https://github.com/godotengine/godot/files/9793571/minimal.reproduction.project.zip)
