### ISSUE TITLE
CharacterBody3D (Capsule) jittering on flat Box without velocity applied (move_and_slide)

### ISSUE THREAD

**Issue by BenjaminSchulte** [godotengine/godot#67432]
### Godot version

4.0.beta2.official.f8745f2f7

### System information

Linux 64bit, Vulkan API 1.2.0, NVIDIA GeForce GTX 1660 Ti (470.141.03)

### Issue description

A CharacterBody3D on top of a simple StaticBody3D with a flat BoxShape3D can jitter at **some** positions using `move_and_slide`, even with zero velocity.

The bug can be reproduced using physics engine *DEFAULT* and *GodotPhysics* (is it the same?).

Related Godot 3.5 bugs could be #35780 and #61616, even though they work with a GridMap and not with a plain box for collisions.

Here is how it looks like:
https://user-images.githubusercontent.com/9679864/195974997-30d2f9e5-5f24-48b9-9917-f996152f621b.mp4

The y position is switching from 1.651 to 1.695 even without applying any velocity.

### Steps to reproduce

- Add a capsule shaped CharacterBody3D containing a CollisionShape3D with a CapsuleShape3D (Example: Radius 0.3, Height 1.4)
- Add a floor using a StaticBody3D containing a CollisionShape3D with a BoxShape3D (Example above: Size 64, 1, 64, Transform y: 0.5)
- Allow the CharacterBody3D to be moved around using a simple script overriding the velocity every _physics_process() and calling move_and_slide()
- Have luck finding the correct spot where jittering happens (In the video above it was X: 1.799999, Z: 0, but this may differ on other systems)

### Minimal reproduction project

[BugTest.zip](https://github.com/godotengine/godot/files/9791453/BugTest.zip)

**Comment by rburing** [comment]
Possibly fixed by https://github.com/godotengine/godot/pull/66951. Please try 4.0 beta 3 which includes that fix.

**Comment by BenjaminSchulte** [comment]
Thanks! Seems to be fixed in latest version. Next time I'll try the latest version first...
