### ISSUE TITLE
GDScript 2.0: Debugging inner classes is broken

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#67439]
### Godot version

v4.0.beta3.official [01ae26d31]

### System information

Windows 10

### Issue description

I want to debug my inner classes, but the dubuger skips the code.
Thus, it is currently not possible to debug inner classes.

### Steps to reproduce

Put this code into a new script file.
Set breakpoint at 
`clazz.test()` or `return "foo"`

Run debug and try to step into.

```
class TestInnerClass extends RefCounted:

	func test() -> String:
		return "foo"

func _ready():
	var clazz := TestInnerClass.new()
	clazz.test()
```

**Comment by rune-scape** [comment]
[issue-67439.zip](https://github.com/godotengine/godot/files/10017804/issue-67439.zip)
with this project i got these errors when trying to step into the statements in `_ready`
```
ERROR: Condition "path.is_empty()" is true.
   at: DAP::Source::compute_checksums (C:\git\godot_bugfixes\editor\debugger\debug_adapter\debug_adapter_types.h:70)
ERROR: Resource file not found: res://.
   at: (core\io\resource_loader.cpp:219)
foo
```

**Comment by MikeSchulze** [comment]
👍
