### ISSUE TITLE
Comments field on scenes and a panel for it on editor

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#6744]
This is a feature request:

Since everything tends to be pure visual I think that could be nice to have a simple comment field as part of the scene file and the corresponding editing panel in the editor.

That way you will be able add scene description, some details or anything you need to say/remember about the scene being edited.

Something like:
![commentsection](https://cloud.githubusercontent.com/assets/10215987/19213883/9c1a7aa8-8d4c-11e6-9d13-288c8c031a1e.png)

**Comment by bojidar-bg** [comment]
Related to both https://github.com/godotengine/godot/issues/2082 and https://github.com/godotengine/godot/issues/5433

**Comment by eon-s** [comment]
@bojidar-bg I mean for the whole scene file with a main editor tab (not related to nodes).
On individual nodes seems like too bloated to me, but maybe all three issues are on the same subject of extra metadata.

**Comment by Noshyaar** [comment]
Still reproducible/relevant in 3.1 master 3ad9e47 : it's not implemented yet

**Comment by Calinou** [comment]
This was implemented in #31389, closing. (Commenting a scene is done by commenting its root node.)
