### ISSUE TITLE
C# signal callbacks don't work when callbacks are extension methods

### ISSUE THREAD

**Issue by Byteron** [godotengine/godot#67447]
### Godot version

4.0 Beta 3

### System information

Windows 11

### Issue description

In C#, signals can be used similar to how Events are used.
However, when using functions that are extension methods:
![image](https://user-images.githubusercontent.com/24433899/195989648-98c41210-904c-4689-992c-31f8242597ae.png)
![image](https://user-images.githubusercontent.com/24433899/195989681-ff80020e-6128-47f3-8572-0f7a9ccdd79d.png)
then I get an error: 
![image](https://user-images.githubusercontent.com/24433899/195989721-afff43b4-f872-4895-b5f0-0bdeb8eb3ac7.png)
It seems to assume the first argument as actual argument, rather than the method owner. With normal C# events this is possible.

### Steps to reproduce

1. create an extension method for some object
2. connect that method to a signal without parameters
3. trigger signal

### Minimal reproduction project

I think this is easy enough to reproduce in an empty project.

**Comment by NeilKleistGao** [comment]
Has this issue been solved? It seems that I can't reproduce the problem.

![image.png](https://s2.loli.net/2022/11/28/STrxiJYHtb5y4us.png)

Where
```c#
public class Button2{
}

static class Helper {
    public static void Press(this Button2 self) {
        GD.Print("Button2 Pressed.");
    }
}
```
