### ISSUE TITLE
Sky is not rendered on macOS unless renderer is gl_compatibility

### ISSUE THREAD

**Issue by OctoD** [godotengine/godot#67449]
### Godot version

4.0 beta 3

### System information

macOS

### Issue description

The sky is white unless `project-settings/general/rendering/renderer/rendering method` is set to `gl_compatibility`.

This did not happen using the 4.0-beta2

### Steps to reproduce

- Create a 3D scene
- Add environment
- Setup a sky (PhysicalSky)
- Add a camera
- Run

### Minimal reproduction project

[skybug-beta03.zip](https://github.com/godotengine/godot/files/9792312/skybug-beta03.zip)

**Comment by snougo** [comment]
got this issue too on Intel GPU Mac

**Comment by MrBBBaiXue** [comment]
Same issue here on **Apple Mac Mini M1** with **macOS 13 Ventura**:

When system is in Light Mode:
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/17956756/198920384-7d0bcaa6-52bb-4bde-8d92-d1243b5bd3b7.png">

Dark Mode:
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/17956756/198920561-e6da188b-60c9-4f9b-aa4b-b1f760f74bbb.png">
**Seems it follows the system Window's default background. And the sky rendered correctly in Mission Control**:
<img width="1849" alt="image" src="https://user-images.githubusercontent.com/17956756/198920689-71a60f00-d2e4-46dc-b095-5acccc352022.png">

**Comment by Calinou** [comment]
It looks like this is a transparency issue – see also https://github.com/godotengine/godot/issues/67101.

**Comment by MrBBBaiXue** [comment]
Update: Issue solves on Godot 4 beta 4 (Apple Mac Mini M1)
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/17956756/200026987-27a17a5e-6fea-4fd4-be63-ed2fd51e5d8c.png">

**Comment by rfsbsb** [comment]
I can confirm it was fixed on beta4 on Macbook Air m1 as well.

**Comment by clayjohn** [comment]
@b3e3e3 Can you open up a new issue? This one was solved in November, so you are likely facing a different issue.
