### ISSUE TITLE
Weird behaviour in window mode

### ISSUE THREAD

**Issue by Mine93** [godotengine/godot#67456]
### Godot version

v3.5.stable.official

### System information

Windows 11, Intel Core I7-11700k, 32GB DDR4, Nvidia GeForce GTX 1080 (driver version 522.25), GLES3

### Issue description

When set in window mode, if the window resolution matches the screen's native resolution, it appears as if it has entered some kind of borderless window mode but also having a separate window stuck on a single frame, the game is rendered in the "fullscreen" but menu items and general things that require mouse pointing require you to point in the window.

https://user-images.githubusercontent.com/46654962/196001514-39287ea4-efc9-4721-b3a3-050b17e9cbee.mp4

When I first implemented the options menu everything worked fine so it could just be Windows doing creative things after an update but I can't say for sure.

### Steps to reproduce

The setup here is quite simple, Window Settings: Fullscreen OFF, Borderless OFF, Resizable OFF, Stretch Mode viewport, Aspect keep.
I'm changing the window size with this: ```OS.set_window_size(Vector2(2560,1440))```

**Comment by ali1x** [comment]
I can confirm that this is a weird behavior.

**Comment by Calinou** [comment]
@Mine93 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

This is likely caused by the window not being resizable. Try enabling **Resizeable** in the Project Settings.
