### ISSUE TITLE
Can't be sure when file is saved with new FileAccess api [C#]

### ISSUE THREAD

**Issue by kilojool** [godotengine/godot#67450]
### Godot version

v4.0.beta3.mono.official [01ae26d31]

### System information

Windows 10

### Issue description

Since the new FileAccess closes files automatically, you're not really sure when the file is saved, at least in C#. If one wants to load the same file shortly after storing something, you only get an empty file. The unreference() method seems to work in GDscript, but not in C#. If there is a way to do this, I guess it should be made explicit.

### Steps to reproduce

Open a file using C# and store something in it, then open it again and try to read it. 

### Minimal reproduction project

[FileTest.zip](https://github.com/godotengine/godot/files/9792453/FileTest.zip)

**Comment by raulsntos** [comment]
From the [FileAccess documentation](https://docs.godotengine.org/en/latest/classes/class_fileaccess.html):

> There is no method to close a file in order to free it from use. Instead, `FileAccess` will close when it's freed, which happens when it goes out of scope or when it gets assigned with `null`. In C# the reference must be disposed after we are done using it, this can be done with the `using` statement or calling the `Dispose` method directly.

```csharp
using var file = FileAccess.Open("res://something"); // File is opened and locked for use.
// The using statement calls Dispose when going out of scope.
```

You are not disposing the file in your MRP, can you try disposing and see if it fixes the issue?

**Comment by kilojool** [comment]
Yes, that fixed it!

**Comment by kilojool** [comment]
I probably should have read the documentation first ;)
