### ISSUE TITLE
Support bilinear bars in TextureProgress

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#6746]
Supporting bilinear bars in TextureProgress (bars that extend in both directions, eg. left and right, up and down, clockwise and counter-clockwise) would be handy, so that you can make such bars using only one node (instead of two currently).

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Calinou** [comment]
This is still not implemented in both TextureProgress and ProgressBar as of https://github.com/godotengine/godot/commit/3ad9e4740c35ec20fdd6942f13047ebd53ea203e, but the workaround mentioned in OP is still valid.
