### ISSUE TITLE
Improve error message when attempting to override built-in non-virtual method

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#67461]
### Godot version

v4.0.beta3.official [01ae26d31]

### System information

Windows 10

### Issue description

I current migrating my plugin and running into this problem.
My plugin provides a mocker to mock existing classes by override functions.

When i overwrit `get_name() -> StringName` the compiler shows an error.
**The error occurs when you have an inheritance depth of three.**

### Steps to reproduce

Put this code in a new script and see the compile error
```
class CustomNode extends Node:
	
	func foo():
		pass


class TestNode extends CustomNode:
	
        # this line produces a compile error
	func get_name() -> StringName:
		return &""

```
The error is: `The function signature doesn't match the parent. Parent signature is "String get_name()".`

**Comment by KoBeWi** [comment]
You can't override built-in methods if they are not virtual, see #55024
The error is weird though. It reports the return type incorrectly and there is no parse error if you use String.

**Comment by MikeSchulze** [comment]
> You can't override built-in methods if they are not virtual, see #55024 
Thats bad news, it works in Godot3! This is a regresion this will break my mock implementations.

This code works fine in Godot3 and i see the print statement in the console, but in Godot4 the overwritten function is not called anymore.
```
class TestNode extends CustomNode:
	
	func is_inside_tree() -> bool:
		prints("is_inside_tree")
		return true


func _ready():
	var node := TestNode.new()
	node.is_inside_tree()
```

>The error is weird though. It reports the return type incorrectly and there is no parse error if you use String.
Yes the error is weired and is wrong in my eyes.
The original function signature return type is StringName and not String
`{
   "name":"get_name",
   "args":[
      
   ],
   "default_args":[
      
   ],
   "flags":5,
   "id":3172,
   "return":{
      "name":"",
      "class_name":"&""",
      "type":21,
      "hint":0,
      "hint_string":"",
      "usage":6
   }
}`
You can see the return type is 21 == TYPE_STRING_NAME
And this function is also not `virtual`
is_virtual:  false
is_static:  false
is_const:  true
is_core:  false
is_default:  true
is_vararg:  false

**Comment by dalexeev** [comment]
Attempting to override a non-virtual native method now generates the `NATIVE_METHOD_OVERRIDE` warning (which is treated as error by default), so I think this issue can be considered resolved.

![](https://github.com/godotengine/godot/assets/47700418/c2518b9b-33a5-4051-81b7-bd02f991d1f9)
