### ISSUE TITLE
Regression in mesh LOD behavior with shadows since 4.0.beta3

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#67479]
### Godot version

4.0 Beta 3

### System information

Windows 11, Vulkan, GTX 1050 Ti 516.94

### Issue description

A regression since Beta 2, Directional Shadow ALODs are acting up. They're more aggressive compared to the Camera, but also inconsistent within splits.

### Steps to reproduce

Move around Shadowed Objects with ALODs (directional shadows) and observe inconsistent LODs between View and Shadows, and even changing within splits.

### Minimal reproduction project

[LOD.zip](https://github.com/godotengine/godot/files/9793839/LOD.zip)

**Comment by clayjohn** [comment]
Could be a regression from https://github.com/godotengine/godot/pull/67307 I wonder if it's causing something funky to happen with LOD selection in the shadow pass

**Comment by TechnoPorg** [comment]
There still seem to be camera planes used in relation to LOD when rendering shadows:
https://github.com/godotengine/godot/blob/b04350828ecc2388192a5cebf662ae1afc14f5eb/servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp#L2350-L2353

**Comment by mrjustaguy** [comment]
I think maybe it's time to change up the LOD logic for Shadows (directional atleast), as they should use the same logic as orthogonal cameras do, from the perspective of the Light ofc, so that the LODs change based on splits and their resolution, regardless of distance from the camera.

**Comment by mrjustaguy** [comment]
one observation made with https://github.com/godotengine/godot/pull/82000: If you line up a series of an identical mesh, and cast directional shadows upon them, you'll notice how the LOD decision goes something like "High Lod - Mid Lod - Low Lod - Mid Lod - Low Lod" as you're going away from the casters following the line..
