### ISSUE TITLE
No way to compare dictionaries or arrays by reference

### ISSUE THREAD

**Issue by vpellen** [godotengine/godot#67474]
### Godot version

v4.0.beta3.official [01ae26d31]

### System information

Windows 10

### Issue description

Trying to test if two variables point to the same dictionary or array. Currently, Godot tests array and dictionary equality by value. An understandable decision, if mildly infuriating to somebody who grew up with C++. Alas, I seek to compare the references directly, and as far as I can tell, this is no longer possible.

I'm submitting this as a bug rather than a proposal because it _technically_ represents a loss of functionality that I don't believe was intentional.

Incidentally, my issue comes from a desire to write a deep copy function that accommodates shared references (and ideally recursion), seeing as the current `.duplicate(true)` methods do not.

### Steps to reproduce

1) Search for a method to compare arrays and dictionaries by reference
2) Repeat step 1 until sufficiently convinced that such functionality does not exist

**Comment by KoBeWi** [comment]
Related: #67153

**Comment by vpellen** [comment]
Fixed by https://github.com/godotengine/godot/pull/71758
