### ISSUE TITLE
NavigationRegion2D Bug - Godot 4 Beta

### ISSUE THREAD

**Issue by ScriptJam** [godotengine/godot#67480]
### Godot version

4 (last tested in Beta 9)

### System information

Windows 10, i7-9700, Nvidia GeForce RTX 2060 SUPER, GLES3 (gl_compatibility)

### Issue description

**Issue:** The new Navigation2D seems to sporadically choose a random path that makes no sense (see image below)

Obstacle avoidance is disabled. It's set up for just simple pathfinding.  It takes a lot of moving around to get the issue to occur, but on larger maps it happens quite a lot. 

My code along with an example project below. If anyone sees anything I did incorrectly, please let me know.  I've tried about 100 variations of this code and it always occurs. 
Additional note: I've tried several body types as well - CharacterBody2D & RigidBody2D (both kinematic and static)

![https://i.imgur.com/WiRCHLz.png](https://i.imgur.com/WiRCHLz.png)

**NPC follow script:**
```
extends RigidBody2D

var dir:Vector2 = Vector2.ZERO
@export var target:CharacterBody2D
@export var speed:float = 20.0
@onready var navAgent : NavigationAgent2D = $NavigationAgent2d

func _ready():
	call_deferred("actor_setup")
	
func _process(_delta):
	queue_redraw()
	
func actor_setup():
	await get_tree().physics_frame
	navAgent.set_target_location(target.position)
		
func _physics_process(_delta):
	#update path if target changes position
	if navAgent.get_target_location() != target.position:
		navAgent.set_target_location(target.position)
		
	if navAgent.is_navigation_finished():
		linear_velocity = Vector2.ZERO
	else:
		var navAgentPos:Vector2 = global_transform.origin
		var nextPos:Vector2 = navAgent.get_next_location()
		dir = navAgentPos.direction_to(nextPos)
		linear_velocity = dir * speed
	
func _draw():
	#draw current path
	var path:PackedVector2Array = navAgent.get_nav_path()
	var v1:Vector2 
	var v2:Vector2 
	for i in range(path.size()):
		if i != 0:
			v1 = path[i-1] - global_position
			v2 = path[i] - global_position
			draw_line(v1, v2, Color.YELLOW, 2)
			draw_circle(v1, 1.0, Color.RED)
			draw_circle(v2, 1.0, Color.RED)
``` 

### Steps to reproduce

Steps:
- Add a Navigation2DRegion with a new navigation polygon
- Add many inner polygons (holes)
- Set up basic pathfinding (obstacle avoidance not necessary)
- Move around until the issue occurs (it's sporadic)

### Minimal reproduction project

[Navigation2D_Bug.zip](https://github.com/godotengine/godot/files/9794158/Navigation2D_Bug.zip)

**Comment by smix8** [comment]
Could only reproduce by luck. It looked like the path post-processing funnel is snapping around a corner vertex pointing in the wrong direction. Maybe some of the "hole" polygons inside the navpoly data are stored in the wrong order. There are so many it is not really human-readable. After editing / recreating the navpoly with a fresh resource was not able to see this bug again.

**Comment by ScriptJam** [comment]
@smix8 
I'm able to reproduce the issue quite easily. On the attached sample project, it may be a bit more difficult for it to occur as there are few holes, but on larger-scale maps, it occurs very often. Either way, it shouldn't be happening. I first ran into the issue by cutting holes around trees and other obstacles on a top-down RPG map.

**Comment by ScriptJam** [comment]
still an issue in beta 9

**Comment by smix8** [comment]
It happens to rare and never in the exact same situation / position with the test project.

To be sure it needs a more reliable test project with a smaller layout / polygon that reproduces the bug reliably when player and npc are in the same test positions. Should also only use basic pathfinding with NavigationServer2D.map_get_path() cause the NavigationAgent has the use of path post-processing hardcoded so it is never the "real" path that we are seeing.

I assume it is those very thin and long polygon edges on top of a not triangulated polygon that breaks the post-processing corridor funnel angle calculation and makes it snap to a corner of a very long edge in rare circumstance. This corner snap is what makes it so noticeable that the path is wrong and without post-processing I assume the path would just go through the closest edge positions.

Very long and thin edges are never a good thing for pathfinding, 3D baking automatically breaks polygons down when edges are to long to avoid this. In 2D this is not automated and still something users need to be aware of when drawing polygons.

**Comment by ScriptJam** [comment]
Unable to reproduce from a new project in the latest build. The issue may be resolved.

**Comment by smix8** [comment]
It still happens in rare situations where the start / end positions are directly on one of the thin and long polygon edges.

If you look at the situation with disabled path post-processing (left path magenta with, right path yellow without) you see that the unoptimized path, while also not optimal, has the same issue as the path with post-processing. The unoptimized path has no requirement to snap to a polygon corner but even the unoptimized path still enters the last polygon with the end position at a bad place and backtracks along the edge to the end position.

![pp](https://user-images.githubusercontent.com/52464204/216846675-9b892384-a0b0-4463-a9e6-422f79f59ca0.jpg)

**Comment by ScriptJam** [comment]
yep, it still occurs. I just downloaded the "stable" version and spent a few hours setting up a new project. I added about 10 obstacles, cut holes around them, and ran into the issue immediately. It may not be common, but it's also not that rare. 

This makes the new navigation completely useless (no offense).

**Comment by smix8** [comment]
The last linked issue made the bug more reproducible.
This is fixed in an internal build scheduled for the pathfinding rework.

**Comment by smix8** [comment]
Closing in favor of the other linked issue https://github.com/godotengine/godot/issues/74696 that tracks the same issue.
