### ISSUE TITLE
Make scripts and shaders embedded in .tscn be more readable and diffable

### ISSUE THREAD

**Issue by raould** [godotengine/godot#6749]
**Operating system or device - Godot version:**
Win 7 32 bit Pro; Linux Ubuntu 16.04 64 bit.
Godot 2.1 in both cases.
My project is stored in a Git repo (hosted on Bitbucket).

**Issue description** (what happened, and what was expected):
The files are saved in a format that (1) doesn't let humans easily study them, nor (2) let automatic diff tools understand them.

Personally I think the .tscn file should be split up into a parent folder and individual files underneath it. Putting the entire scene with all the various GDScripts into one file is poor ux.

AND GOD HELP YOU WHEN THERE ARE MERGE CONFLICTS.

**Steps to reproduce:**
1) have a Godot project with GDScript files in it.
2) make changes.
Expected: to be able to see the individual diffs in a diff tool. Also to be able to ready or edit the file manually easily.
Actual: Things are not diffable because (1) too many things are stored in a single .tscn file; (2) whitespace inside GDScripts are saved as excape characters. So the diffs become entire giant chunks of entire GDScripts.

**Link to minimal example project** (optional but very welcome):
See screen shot.
![saddiff](https://cloud.githubusercontent.com/assets/77176/19215705/2a2af892-8d5a-11e6-8cf5-1dc2a7907ccc.PNG)

**Comment by akien-mga** [comment]
> Personally I think the .tscn file should be split up into a parent folder and individual files underneath it. Putting the entire scene with all the various GDScripts into one file is poor ux.

So... what are you using a built-in script instead of saving your script to a file? :)

**Comment by williamd1k0** [comment]
I think `.tscn` is actually human readable.
I can read files and diffs easily (saving scripts to a separate file).

**Comment by Zylann** [comment]
The only problem TSCN has IMO is this: https://github.com/godotengine/godot/issues/6527
Other than that, I find it human readable and easily diffable.

**Comment by raould** [comment]
@akien-mga because that is what Godot does out of the box, maybe? Are you trying to tell me that I have to learn and perform yet another customization of the system to get it to not do things that are actively breaking basic software engineering principles, tools, and habits?

Thanks for the tip, I will try to go learn about it and set it up. Although I believe it is still a bad UX.

**Comment by bojidar-bg** [comment]
Anyway, if this isn't a problem for scripts (as @akien-mga said, since embedding the script in the scene is optional and off by default), it is a also problem for shaders (which get embedded in the same ugly way).
I think I would retitle the issue though, since it currently looks as if `diff` and `cat` both crash when they open the file... :laughing:

**Comment by akien-mga** [comment]
> because that is what Godot does out of the box, maybe? Are you trying to tell me that I have to learn and perform yet another customization of the system to get it to not do things that are actively breaking basic software engineering principles, tools, and habits?

Ah?
![spectacle x24349](https://cloud.githubusercontent.com/assets/4701338/19219564/b3ad74ac-8e16-11e6-8fd1-f0804ee8564c.png)
I see "Built-In Script" as set to `OFF` by default personally.

**Comment by akien-mga** [comment]
But sure, the code embedded in tscn files could of course be made a bit more readable. But the real solution is still to write your scripts in .gd files and not in .tscn, unless it's just a two-liner shader.

**Comment by raould** [comment]
@aiken-mga there is more than one way to create a script in godot. One is as you have shown. The other is clicking on a node in the tree, going down in the list of its properties in the Inspector panel, and seeing the "New GDScript" command.

guess where that puts the new script? :-) :-(

**Comment by Zylann** [comment]
@raould in the scene, as every other resource in Godot that is created from the inspector. And every resource created this way can still be made a file if you click the right arrow on it and click "Save as". But I find myself script addition could get some improvements.

**Comment by raould** [comment]
hi,

If there is any way that by default (as in the least number of clicks, the default values for commands or menus along the way) a file is kept inside the tscn file, then that fits what I am talking about.

so i guess the changes i'd like to see are:
(1) make the tscn file *not use escapes for whitespace*. as i said (buried by now) above in the thread.
(2) there is no #2.

:-)

**Comment by akien-mga** [comment]
Right I had forgotten about the way to create a script in the inspector, I never use that. IMO all ways to create a script should default to external files, and only create embedded scripts when users actively request it.

**Comment by RandomShaper** [comment]
I also use built-in scripts a lot and diffs are useless. (For shaders too.)

I've proposed #7002 to try to improve the state of things.

**Comment by bojidar-bg** [comment]
Closing since #7002 was merged.
