### ISSUE TITLE
get_tree().change_scene_to() Doesn't seem to work anymore.

### ISSUE THREAD

**Issue by xShader1374** [godotengine/godot#67492]
### Godot version

4.0.beta3.official [01ae26d31]

### System information

Windows 11

### Issue description

``` Invalid call. Nonexistent function 'change_scene_to' in base 'SceneTree'. ```

```get_tree().change_scene_to()``` doesn't seem to work anymore in this version, idk why but i tried 2 projects and it's now broken

no workaround found.

### Steps to reproduce

just try doing a var with a preload and then try to change to another scene and you'll get the error

**Comment by timothyqiu** [comment]
`change_scene()` and `change_scene_to()` have been renamed, see #63596.

**Comment by xShader1374** [comment]
> 

Ohh so that's why, tysm!
