### ISSUE TITLE
GdScript 2.0: String as int casting is broken

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#67494]
### Godot version

v4.0.beta3.official [01ae26d31]

### System information

Windows 10

### Issue description

I want to simply cast a numeric string into a int by using the casting operator `as`

var value := "14" as int

results in 
`Invalid cast: could not convert value to 'int'.`

### Steps to reproduce

`var value := "14" as int`

### Workaround
use ` "14".to_int()` instead

**Comment by KoBeWi** [comment]
Probably the same as #44407
(i.e. different bug, but the same cause; you can check if the linked PR fixes it)

**Comment by MikeSchulze** [comment]
@KoBeWi i'm not sure is realy the same the issue you linked is about int constructor ;)

**Comment by KoBeWi** [comment]
Casting just calls the constructor I think, so if you can't construct int from String, you also can't cast it.
The workaround you mentioned is the same in both cases.

**Comment by akien-mga** [comment]
I checked and it's indeed fixed by #62814 too.
