### ISSUE TITLE
TWEEN_PAUSE_PROCESS doesn't work anymore

### ISSUE THREAD

**Issue by arcanis** [godotengine/godot#67504]
### Godot version

4.0.beta3.official

### System information

Windows 10

### Issue description

When pausing the scene tree, tweens don't process anymore even if they define `Tween.TWEEN_PAUSE_PROCESS`. This seems to be a regression from 3.5, and goes against the [documentation](https://docs.godotengine.org/en/latest/classes/class_tween.html?highlight=TWEEN_PAUSE_PROCESS#enumerations):

> TWEEN_PAUSE_PROCESS = 2 --- The Tween will process regardless of whether [SceneTree](https://docs.godotengine.org/en/latest/classes/class_scenetree.html#class-scenetree) is paused.

### Steps to reproduce

```
extends Node2D

func _ready():
	get_tree().paused = true

	var tween = create_tween()
	tween.set_process_mode(Tween.TWEEN_PAUSE_PROCESS)
	tween.tween_property($Icon, "rotation", 360, 10)
```

### Minimal reproduction project

[BugTest.zip](https://github.com/godotengine/godot/files/9795513/BugTest.zip)

**Comment by arcanis** [comment]
It seems that I used `set_process_mode` when it should have been `set_pause_mode`. Weirdly enough, it worked as expected in 3.5 ...

**Comment by KoBeWi** [comment]
> Weirdly enough, it worked as expected in 3.5 ...

That's because Tweens in 3.5 are Nodes. In 3.5 the SceneTreeTween has the same behavior as new Tweens.
