### ISSUE TITLE
`DisplayServer.window_get_current_screen` error under Linux with SubViewports

### ISSUE THREAD

**Issue by stephen-soul** [godotengine/godot#67505]
### Godot version

4.0.Beta3.mono

### System information

EndeavourOS. Vulkan. 

### Issue description

It's been observed when pushing input from an area to a subviewport that "unintended"(?) clicks cause an error to show up under:
```E 0:00:02:0357   void Godot.DelegateUtils.InvokeWithVariantArgs(IntPtr , Godot.NativeInterop.godot_variant** , UInt32 , Godot.NativeInterop.godot_variant* ): Condition "!windows.has(p_window)" is true. Returning: 0
  <C++ Source>   platform/linuxbsd/display_server_x11.cpp:1455 @ window_get_current_screen()
  <Stack Trace>  Godot.NativeInterop.NativeFuncs.generated.cs:324 @ void Godot.NativeInterop.NativeFuncs.godotsharp_method_bind_ptrcall(IntPtr , IntPtr , System.Void** , System.Void* )()
                 NativeCalls.cs:3421 @ void Godot.NativeCalls.godot_icall_2_384(IntPtr , IntPtr , IntPtr , Godot.NativeInterop.godot_bool )()
                 Viewport.cs:1379 @ void Godot.Viewport.PushInput(Godot.InputEvent , Boolean )()
```
Something to note, this only occurs if you click on things that I called "unintended" - If you click on a button or the scroll bar, no errors. If you click on a label, the error is sent. This also only happens when 2 monitors are plugged in, for some reason; if I limit my monitors to one, there is no issue. This might also be my code? Or some weird mix of everything.

### Steps to reproduce

- Load up sample project.
- Play Game.tscn (default project)
- Click around the mesh instance and observe the errors noted above (If you click on a button or a scroll container, no errors. If you click on a label or scroll on a label, error.)

### Minimal reproduction project

[Viewport-issue.zip](https://github.com/godotengine/godot/files/9795517/Viewport-issue.zip)

**Comment by Calinou** [comment]
Please create a minimal reproduction project in GDScript instead of C# for two reasons:

- Non-Mono builds of Godot are easier to set up and have less moving parts.
- This rules out C# being the cause of the bug.

**Comment by stephen-soul** [comment]
[Viewport-issue-gdscript.zip](https://github.com/godotengine/godot/files/9795812/Viewport-issue-gdscript.zip)
The y is a little backwards, but the issue remains in GDScript. Apologies for the delay!
