### ISSUE TITLE
Interacting with saturation in OKHSL color picker makes it white

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#67528]
### Godot version

v4.0.beta.custom_build [0d28820c8]

### System information

Fedora, RX 590

### Issue description

Interacting with saturation in HSV mode turns the color picker white.

### Steps to reproduce

1. make a color property
2. open the color picker
3. with the OKHSL mode, go in HSV and interact with saturation

https://user-images.githubusercontent.com/7917475/196142092-a49d6424-e2c8-4394-bfa8-87ca262831b6.mp4

**Comment by fire** [comment]
Looks the slider is reversed? The higher saturation seems to be wrongly whiter. But high saturation should be darker?
