### ISSUE TITLE
Create New Node dialog doesn't update the description field when selecting a custom class

### ISSUE THREAD

**Issue by MrPaiZi** [godotengine/godot#67535]
### Godot version

4.0beta1, 4.0beta2, 4.0beta3

### System information

Windows 10

### Issue description

In the `Create New Node` window, when we click a node, its `Description` is shown. 
The `GDScript documentation generation system` are supported after godot 4, but the `Description` of custom nodes isn't shown while we click the nodes in `Matches`: 
![2022年10月17日20时15分49秒-01](https://user-images.githubusercontent.com/39019460/196177268-0771150f-5fbb-4c1a-abfd-4e7e7da69c99.gif)

BTW, if you click the nodes in `Recent` or `Favorites`, or search the custom node, the `Description` will display properly: 
![2022年10月17日20时17分44秒-01](https://user-images.githubusercontent.com/39019460/196177875-008e0749-996d-4de2-a492-8c02cf48037a.gif)

### Steps to reproduce

omitted

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/63536.
