### ISSUE TITLE
ShapeCast2D not working with C#

### ISSUE THREAD

**Issue by ExquisiterEmil** [godotengine/godot#67530]
### Godot version

4.0-beta3

### System information

Windows10, AMD Ryzen 9 3900XT, RTX3070, Vulkan

### Issue description

`ShapeCast2D` collision does not get detected in C# while it does in GD Script, even though the code is an exact translation.

I am casting a circle with a radius of 10 from (0, -100) to (0, 100), so both rectangles should be caught in the collision. They are in fact both caught with GD Script code, while they are not caught in C#.
![image](https://user-images.githubusercontent.com/53947784/196145911-d8d3a5a7-c835-478f-bc6c-f6dcf72daccc.png)

C# Code:
```c#
  public override void _Ready()
  {
	var shape = PhysicsServer2D.CircleShapeCreate();
    	PhysicsServer2D.ShapeSetData(shape, 10);
    		
    	var param = new PhysicsShapeQueryParameters2D();
    	param.CollisionMask = 1;
    	param.ShapeRid = shape;
    	param.Motion = new Vector2(0, 100);
    	param.Transform = (new Transform2D()).Translated(new Vector2(0, -100));
    		
    	var result = GetWorld2d().DirectSpaceState.IntersectShape(param, 10);
        GD.Print(result)
  }
```

GD Code:
```python
  func _ready():
        var shape = PhysicsServer2D.circle_shape_create();
	PhysicsServer2D.shape_set_data(shape, 10);
		
	var param = PhysicsShapeQueryParameters2D.new();
	param.collision_mask = 1;
	param.shape_rid = shape;
	param.motion = Vector2(0, 100);
	param.transform = Transform2D().translated(Vector2(0, -100));
		
	var result = get_world_2d().direct_space_state.intersect_shape(param, 10);
        print(result)
```

### Steps to reproduce

- Create a Scene with 2 static body colliders and make a small gap between them
- Perform a shape cast with a C# script that runs exactly through the gap
- Print result

### Minimal reproduction project

[BrokenShapeCast2D.zip](https://github.com/godotengine/godot/files/9799163/BrokenShapeCast2D.zip)

**Comment by raulsntos** [comment]
The `Transform2D` parameterless constructor in C# is not the same as the parameterless constructor in GDScript. To get the same behavior as in GDScript you need to use `Transform2D.Identity` as described in the [documentation](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_differences.html#transform2d).

**Comment by ExquisiterEmil** [comment]
omg, thanks that fixes it. It is a bit strange that it is that way, but I guess the Shape cast works fine.
