### ISSUE TITLE
Editor Viewport Camera has DOF blur enabled, should be toggleable

### ISSUE THREAD

**Issue by tinmanjuggernaut** [godotengine/godot#67542]
### Godot version

Godot 4 Beta 3

### System information

Windows 11/64, RTX 3070, Vulkan

### Issue description

My editor viewport camera has a DOF blur which cannot be turned off unless `use_physical_light_units` is disabled in project settings. It's quite difficult to work up close with a blurry camera.

PLU disabled
![image](https://user-images.githubusercontent.com/632766/196218936-8053b93d-9292-4e9d-84aa-a504f7be9e2a.png)

PLU enabled
![image](https://user-images.githubusercontent.com/632766/196219125-6ddf126c-e01b-4b2e-9a14-0e53c74bcea6.png)

The editor viewport should be able to quickly turn blur on and off, and adjust physical camera settings (in the viewport settings), or just disable blur entirely.

Also the path `rendering/lights_and_shadows/use_physical_light_units` gives no indication it has anything to do with cameras or lenses, so it's not searchable for someone thinking about cameras & lenses. I think there should either be a new name (`use physical_lights_and_cameras`), or two settings `use_physical_lights` and `use_physical_cameras` if they need to be project settings. 

(Also, I'd like to see the camera have the option to calculate changing DOF blur without changing exposure at all, but this can be a topic for another issue. I need to separate out the blur tracker into more separate issues. It's on my list.)

@clayjohn 

### Steps to reproduce

Enable use_physical_light_units.
Zoom close to an object with details to see the blur.

**Comment by clayjohn** [comment]
Thanks for the report, it looks like I accidentally left a CameraAttributesPhysical in the editor default environment from when I was testing physical light units. DoF should definitely not be enabled with the editor Camera without the user specifically requesting it.

**Comment by seppoday** [comment]
I am pretty sure this issue is still in 4.4?
