### ISSUE TITLE
GPUParticles3D broken on float=64 builds

### ISSUE THREAD

**Issue by crynux** [godotengine/godot#67545]
### Godot version

9afc8337bd

### System information

VoidLinux Kernel 5.19.13_1,  Radeon RX 5500/5500M, Vulkan

### Issue description

GPUParticle3D doesn't seem to work properly when Godot is built with float=64. I noticed it when I opened my project (which had properly working Particles before trying a float=64 build), and they were rendering strangely.

I then tried to create a particle in a new project ... to be sure it wasn't something I've done, and they don't work there either. If you open the same project, or do the same particle creation in a non-float=64 build (custom or an official build); it works fine.

I'd put a screenshot; but on the float=64 build there's nothing to show, as the particle just doesn't render.

### Steps to reproduce

Create a GPUParticles3D node, add a ParticleProcessMaterial and a cube mesh as Draw Pass 1; or just open the uploaded project.

### Minimal reproduction project

[testing.zip](https://github.com/godotengine/godot/files/9803094/testing.zip)

**Comment by clayjohn** [comment]
I suspected that this was a regression from https://github.com/godotengine/godot/pull/66178, however, after reverting and rebuilding this issue was still present. Will have to git bisect to figure out when this broke

**Comment by Qubrick** [comment]
Not sure if this related. I got this error from add GPUPartitions3D node to the scene on editor using Godot 4 Beta 4 (e6751549c) with double precision (float=64)

![image](https://user-images.githubusercontent.com/41263042/199712318-95b64c50-64e0-4d2c-9369-d010f4c03cff.png)

**Comment by clayjohn** [comment]
Most likely broken by https://github.com/godotengine/godot/pull/51580 which adds ``real_t`` into many GPU uniforms
