### ISSUE TITLE
Editor crashes when resizing CSG boxes 3D

### ISSUE THREAD

**Issue by Gamepro5** [godotengine/godot#67548]
### Godot version

4.0 beta 3

### System information

Windows 10 ; AMD Ryzen 7 3700X 8-Core Processor

### Issue description

The editor crashes when resizing CSG boxes. I captured the issue in-action in [this video](https://youtu.be/fMYeTkOOefs?t=377), ironically reporting another bug. The only error that regularly shows up is this, and I don't know what it means but it sometimes crashes my debug instance of the project (not my entire editor).
![image](https://user-images.githubusercontent.com/23440295/196255588-c420f140-7401-4502-88d1-aec75c923c13.png)

### Steps to reproduce

1. Duplicate a CSGBox in a CSGCombiner 3D
2. Resize the duplicated box using the dots (not the inspector).

### Minimal reproduction project

https://github.com/Gamepro5/Custom_CharacterBody3D_Movement_System/tree/1be17d8578a6975d9f35d317cdff8b30553d82df

**Comment by Calinou** [comment]
I can't reproduce this on v4.0.beta.custom_build [0c23a2cfe] (Linux).

https://user-images.githubusercontent.com/180032/196277444-3d1a0af4-35e3-4c78-96b7-8a8270a1c536.mp4

**Comment by Gamepro5** [comment]
Perhaps this issue is a random side effect of something else, and it has since been fixed in the latest build. I am still using Godot 4 Beta 3 and I am on a Windows machine. I'll have to wait and see if this issue persists for me on beta 4. If it doesn't, I'll close this issue.

**Comment by Ytachi1000** [comment]
Yeah the same problem here :)  please fix godot 4.0  beta 3

**Comment by akien-mga** [comment]
We're at beta 10 already, please always test the latest version.

**Comment by clayjohn** [comment]
I tested this with both beta 11 and master, it appears that it happens sporadically and is not always reproducible. In 5 runs I was only able to reproduce it 2 times.

**Comment by TisFoolish** [comment]
Using my example build above I was able to get it to trigger within a
minute of continuously messing with the node.

It should also be stated that the crash can happen with ANY CSG node and
the more there are the more likely it might happen..

**Comment by TisFoolish** [comment]
This still happens with Beta 12. [Only took about 30 seconds](https://gfycat.com/maturenearazurevase)
