### ISSUE TITLE
4.0 beta 3: click on children selectable button prints error: "Error calling from signal 'item_group_status_changed' to callable"

### ISSUE THREAD

**Issue by rudidev08** [godotengine/godot#67557]
### Godot version

v4.0.beta3.mono.official [01ae26d31]

### System information

M1 MacBook Pro, Ventura 13.0

### Issue description

Clicking on setting children nodes as selectable or not shows 

`core/object/object.cpp:1057 - Error calling from signal 'item_group_status_changed' to callable: 'SceneTreeEditor::SceneTreeEditor::_update_tree': Method expected 1 arguments, but called with 0..`

Error. Buttons seems to work correctly - state toggles visually.

### Steps to reproduce

1. Open Mob.tscn
2. Select RigidBody2D
3. Click on Group Selected Nodes (don't make children selectable) button in toolbar
4. Error shows up in output

### Minimal reproduction project

[Learn1.zip](https://github.com/godotengine/godot/files/9804944/Learn1.zip)

**Comment by Calinou** [comment]
Can you reproduce this in previous 4.0 betas? You can download them [here](https://downloads.tuxfamily.org/godotengine/4.0/).

**Comment by rudidev08** [comment]
Beta 2 mono - same issue
Beta 1 mono - issue not happening, but also got warning that since project is mobile, it will be modified when open
