### ISSUE TITLE
Incorrect tangent generation when importing `.blend` file (works when importing `.glb`)

### ISSUE THREAD

**Issue by Dabnabbit** [godotengine/godot#67559]
### Godot version

4.0.beta3

### System information

Windows 11, RTX 3070TI, Vulcan

### Issue description

[UPDATE 2: This issue is specifically due to enabling the 'Tangents' flag (enabled by default) on the import options for .blend files, this flag does not appear to be available for other mesh formats, so I'm researching exactly what it's trying to do]

[!!!UPDATE!!! This issue is apparently exclusive to the .blend mesh format, it does not appear to be affecting meshes in .GLB format]

After trying to figure out why some models looked wrong for many days I finally figured out what was wrong. The normal maps are currently only represented in SRGB colorspace, which is inherently wrong for most modern render pipelines, which utilize 'linear colorspace' aka 'noncolor data' for vector space maps that are not meant to represent visual data, i.e. normal maps (this likely also affects other data texture maps)
Here are some images representing and reproducing the issue outside of Godot in Blender:
![image](https://user-images.githubusercontent.com/8258356/196320623-a60460ea-5379-4c79-840f-7acc4fbbf529.png)
and fixed by changing the colorspace to "non-color" data format:
![image](https://user-images.githubusercontent.com/8258356/196320745-495e2567-7a0a-4659-983e-bc35140ae8df.png)
and doing some research on the topic I stumbled on this weird 'hack' by utilizing a Gamma node in blender to convert the sRGB colorspace into 'close-enough' linear "non-color" representation of the normal maps... for whatever reason someone discovered altering the Gamma of the sRGB color space by a value of 0.454 very closely simulates the true vector linear color-space... go figure?
![image](https://user-images.githubusercontent.com/8258356/196321127-6e9cd6c0-2cda-4caa-a799-fc0fa4fe795e.png)

Finally here is the same issue displayed in Godot with the exact same assets:
![image](https://user-images.githubusercontent.com/8258356/196321284-631daf24-956d-4908-8afd-c375122a6b53.png)
![image](https://user-images.githubusercontent.com/8258356/196322772-2ed0bfea-9d4d-41ce-9032-9a47236c84b5.png)
Shouldn't have to draw lines on that one to show the issue/errors... This particular asset GREATLY exaggerates the flaw in the system due to the high number of mirrored UVW coordinates utilized across multiple axis, and normally with a diffuse texture and specular textures on a mesh you won't quite notice them as strongly as you do here where the asset is stripped to only the normal map. 
Just for added clarity, I've also attached a screenshot of the mesh with NO normal map applied to demonstrate that the mesh itself is not causing the seams, i.e. broken welds/vertices:
![image](https://user-images.githubusercontent.com/8258356/196323240-44b5d569-a4a6-4273-9496-a4196bd23d33.png)

Another more subtle but still very broken example of a different asset:
![image](https://user-images.githubusercontent.com/8258356/196321918-f6d58cf2-bc12-4c88-87c5-0aab3518b8f2.png)

This issue CAN be avoided by uniquely mapping every UVW space and avoiding any seams across flat surfaces, however, that is a huge cost to pay in the development pipeline in terms of time and also pixel real-estate.

Ultimately this is just aesthetic, but a huge factor in why high quality asset production in Godot just isn't quite matching up to other engines the way it should be.

[UPDATE] Here is a comparison of .GLB and .BLEND mesh formats using the same normal map texture, same mesh, and same material:

![Screenshot 2022-10-18 101813](https://user-images.githubusercontent.com/8258356/196457248-9faac98d-91f2-4df2-b05a-7874c33b8098.jpg)

### Steps to reproduce

Load minimal reproduction project, witness normal map errors on mesh, there are no options to correct this or change the colorspace of imported normal map textures (or any other textures).

### Minimal reproduction project
[UPDATED: Updated MRP with both .blend and .glb mesh formats side by side in main scene]
[NormalMapBug.zip](https://github.com/godotengine/godot/files/9811401/NormalMapBug.zip)

**Comment by Calinou** [comment]
Can you reproduce this in 3.5.1?

**Comment by Dabnabbit** [comment]
> 

@Calinou Hey that's a great point! I didn't isolate out a few more variables here, for clarification, that was utilizing 4.0.beta3 Vulkan rendering using the .blend file native support, I'm gonna go back and double check with .glb format as well, but that said, I can NOT currently reproduce this issue in 3.5 GLES2 or GLES3, verified checking both with the same mesh imported in glb format, the normals are behaving as expected!
![image](https://user-images.githubusercontent.com/8258356/196452747-408b9cd5-ff9b-4b9a-9676-a0bec50bb92c.png)

**Comment by Dabnabbit** [comment]
Ok, I figured out what is causing the issue on .blend mesh imports, this is specifically due to the 'Tangents' flag being set on import for the meshes. 
![image](https://user-images.githubusercontent.com/8258356/196461590-97107112-1bfd-459d-8426-b81c084a38c3.png)
Disabling the Tangents import flag seems to resolve the issue. So now I'm no longer sure this is actually a bug or not? Still seems weird that there doesn't seem to be control over the texture color-space but I might just be looking at this whole thing wrong.

**Comment by Calinou** [comment]
`.blend` import internally calls Blender's glTF export, but it may be using different options than what you're using in Blender's GUI.

**Comment by fire** [comment]
Tangents being broken in import between different pipelines is a thing. @julienduroure Any ideas how to debug this, the first guess is we imported the tangents wrong.

**Comment by julienduroure** [comment]
Maybe linked to this : https://github.com/KhronosGroup/glTF-Blender-IO/issues/920

**Comment by Dabnabbit** [comment]
@Calinou thanks for the title update/corrections, was considering making a new ticket more correctly identifying the issue, after some more diving into the issue, I think I have actually identified the issue has being a blender GLB export issue rather than a Godot issue! Attempted a re-install of a different version of blender to test the export flags (which do include the same options as Godot's import options) and found that the tangent flag was not being properly disabled or enabled in Blender, so GLB files were all being exported without tangents, and .blend files were all exporting WITH tangents.


I think it's actually safe to close this one, however, I might recommend disabling the import tangents option by default in Godot, as it doesn't seem to be beneficial in any use cases I've seen so far. (still testing)

**Comment by Calinou** [comment]
> however, I might recommend disabling the import tangents option by default in Godot, as it doesn't seem to be beneficial in any use cases I've seen so far. (still testing)

Some `.glb`s downloaded online may not include tangents in them, so the option is required for normal mapping to look correct on them.

**Comment by Dabnabbit** [comment]
> > however, I might recommend disabling the import tangents option by default in Godot, as it doesn't seem to be beneficial in any use cases I've seen so far. (still testing)
> 
> Some glTF scenes downloaded online may not include tangents in them, so the option is required for normal mapping to look correct on them. Not everyone is authoring the 3D scenes they're using in their project 🙂

Good point, guess I forget sometimes about the pre-existing assets coming in different forms.

**Comment by Eisendroid** [comment]
I have the same issue. Tried Blender 3.1 and Blender 3.3.1 and both failed. I have first encountered this bug in Godot4.0 Alpha 15 and i still have it in Godot4.0 Beta 4. Alpha 14 is working fine. Different export flags or different file format won't change anything.

Alpha 14:
![Bildschirmfoto vom 2022-11-10 15-40-34](https://user-images.githubusercontent.com/72012005/201129197-8cf4ddbe-5eba-4b8d-849e-c0e3d89ca93c.png)

Alpha 15 to Beta 4:
![Bildschirmfoto vom 2022-11-10 15-41-39](https://user-images.githubusercontent.com/72012005/201129440-dac1de92-9901-441e-b78e-c7f3908bfecf.png)

Keep in mind that it is NOT the whole Normalmap that is displayed wrong. It's always just certain parts of the mesh.

**Comment by Zireael07** [comment]
If it started with Alpha 15, it's likely related to octahedral compression. Likely will be fixed by #68428

**Comment by clayjohn** [comment]
@Eisendroid if the issue started in alpha 15, it should go away when you re-import your mesh. You can do that in two ways. One is to delete the .Godot folder in your project's folder. The other is to select the mesh in the editor, then in the import tab select re-import

**Comment by Eisendroid** [comment]
> @Eisendroid if the issue started in alpha 15, it should go away when you re-import your mesh. You can do that in two ways. One is to delete the .Godot folder in your project's folder. The other is to select the mesh in the editor, then in the import tab select re-import

Re-import in Alpha 15 fixes some graphical glitches, but the problem with tangents/normalmap stays the same.
 I hope Zireael07 is right and it's related to octahedral compression, so it's almost fixed already.
