### ISSUE TITLE
GDScript 2.0: Operations on array (find/has) after JSON.parse_string doesn't work

### ISSUE THREAD

**Issue by michaldev** [godotengine/godot#67551]
### Godot version

4.0 beta 3

### System information

MacOS

### Issue description

I have problem with basic operations on arrays. Find and has methods doesn't work.

### Steps to reproduce

```
print(GM.unlocked_achievements.get(item_package_name, []))
[1]
```

```
print(GM.unlocked_achievements.get(item_package_name, []).has(1))
false
```

```
print(GM.unlocked_achievements.get(item_package_name, []).find(1))
-1
```

```
for item in GM.unlocked_achievements.get(item_package_name, []):
		print(item == 1)
true
```

### Minimal reproduction project

```
var test = JSON.parse_string('{"test":[1]}')
print(test['test'].has(1))
```

**Comment by KoBeWi** [comment]
That's because all JSON numbers are floats. This works:
```GDScript
var test = JSON.parse_string('{"test":[1]}')
print(test['test'].has(1.0))
```

**Comment by michaldev** [comment]
Why?

**Comment by Calinou** [comment]
> Why?

The JSON specification says so :slightly_smiling_face:

**Comment by michaldev** [comment]
I understand. But its weird in use. In gdscript this is represented as an int (without X.0). In other programming languages (what i use), at the time of parsing, it is assigned to the type supported by the language.

**Comment by michaldev** [comment]
In typical use case I have to write like this:
`if GM.unlocked_achievements.get(item_package_name, []).has(float(item_photo_id)) or GM.unlocked_achievements.get(item_package_name, []).has(item_photo_id):`

Why? Because the variable with dict is operated by local and loaded from json. In typical use case after loading data in array are floats, but while game is running collected data is by int.
