### ISSUE TITLE
.NET6: Garbage collection of Variant crashes

### ISSUE THREAD

**Issue by ByteSquire** [godotengine/godot#67563]
### Godot version

v4.0.beta3.mono.official (01ae26d31)

### System information

Windows 10, .NET sdk 7.0.100-rc.2.22477.23

### Issue description

After a lot of debugging and custom building of the engine, I managed to narrow down a crash when using C# signals containing strings as parameters.
The crashes occur randomly, this is due to memory corruption occurring somewhere in the engine.
My debugger always stopped inside [Memory::free_static](https://github.com/godotengine/godot/blob/2e3662acbd8586697db38569785cc9f97dff945e/core/os/memory.cpp#L168) when cleaning up a Variant of type String whose pointer is already invalid, called from [here](https://github.com/godotengine/godot/blob/2e3662acbd8586697db38569785cc9f97dff945e/core/variant/variant.h#L302).

### Steps to reproduce

Create a C# signal with a string parameter to connect to, emit the signal somewhere and connect to it somewhere.
It seems like it doesn't matter what string you pass as long as it isn't empty and there has to be some callback connected to the signal.

### Minimal reproduction project

[Bug.zip](https://github.com/godotengine/godot/files/9808759/Bug.zip)

**Comment by ByteSquire** [comment]
related to #67460
maybe related to #66174

**Comment by Xyotic** [comment]
I'm not sure if its related but it seems using "CallDeferred()" also causes this issue. 

I think it might be related since it happens immediately or after a random amount of time after using it.

So it could be a GC issue

**Comment by nofacer** [comment]
#68329 Same as you here.

**Comment by raulsntos** [comment]
I opened PR https://github.com/godotengine/godot/pull/69194 that may fix this issue, can you try it out to confirm?

Linux users can download the artifact built by CI: https://github.com/godotengine/godot/suites/9514119809/artifacts/451640372
For other platforms, you'll have to build Godot yourself.

**Comment by lufog** [comment]
I tested #69194, and it fixed the crash caused by signals containing strings as parameters.

**Comment by ByteSquire** [comment]
Confirmed fixed in beta 8, well done!
