### ISSUE TITLE
Tilemaps inherit texture settings directly from the project settings

### ISSUE THREAD

**Issue by berarma** [godotengine/godot#67570]
### Godot version

v4.0.beta3.official.01ae26d31

### System information

Debian GNU/Linux 11.5, Nvidia RTX 2070 Super (470.141.03)

### Issue description

Tilemaps inherit texture filter from the project settings instead of inheriting from the parent node. I haven't tested what happens with the repeatable property.

### Steps to reproduce

- Create a Node2D node, and add a child Tilemap.
- Use any tileset for the tilemap and draw some tiles.
- Change the texture filter property in the parent node, the tilemap won't reflect the change.
- Change the texture filter in the project settings, the tilemap will reflect the change.

**Comment by KoBeWi** [comment]
Seems like the TileMap's tiles do not inherit the filter properly. It works if you set the filter on the TileMap node itself.
#66546 would help resolve this.

**Comment by berarma** [comment]
Thanks!
