### ISSUE TITLE
Gradle fails building on Linux

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#6758]
**Operating system or device - Godot version:**
Mageia 6 x86_64, NDK r11c, SDK last updated in July
Current master branch (616ddbd)

**Issue description** (what happened, and what was expected):
Building the Godot lib for both release and debug targets work fine, but gradle fails:
```
$ ./gradlew build
Incremental java compilation is an incubating feature.
:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:preReleaseBuild UP-TO-DATE
:prepareComAndroidSupportSupportV42340Library UP-TO-DATE
:prepareDebugDependencies
:compileDebugAidl UP-TO-DATE
:compileDebugRenderscript UP-TO-DATE
:generateDebugBuildConfig UP-TO-DATE
:mergeDebugShaders UP-TO-DATE
:compileDebugShaders UP-TO-DATE
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets UP-TO-DATE
:generateDebugResValues UP-TO-DATE
:generateDebugResources UP-TO-DATE
:mergeDebugResources UP-TO-DATE
:processDebugManifest UP-TO-DATE
:processDebugResources UP-TO-DATE
:generateDebugSources UP-TO-DATE
:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:compileDebugJavaWithJavac
:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Could not find tools.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 16.953 secs
```
```
$ find -name "*.so"
./libs/release/armeabi-v7a/libgodot_android.so
./libs/debug/armeabi-v7a/libgodot_android.so
```

CC @RandomShaper @volzhs (yeah sorry guys, you're the android experts now :p)

**Comment by RandomShaper** [comment]
Probably it's due to the JAVA_HOME env var not pointing to the JDK 
directory.

**Comment by akien-mga** [comment]
That's not documented so far: http://docs.godotengine.org/en/latest/reference/compiling_for_android.html
It used to work fine without this env var previously.

**Comment by RandomShaper** [comment]
If I unset my JAVA_HOME var Gradle works as long as is doesn't have to 
recompile any Java file.

If I remove the build dir, I get the same error.

**Comment by akien-mga** [comment]
Looks like I missed the openjdk development headers, installed `java-1.8.0-openjdk-devel` and it now works fine.

**Comment by volzhs** [comment]
@evilmu I think you should report it to the owner of that module.
