### ISSUE TITLE
Vector2i and Vector3i in core?

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#6759]
I am writing a new experimental module which needs to manipulate data indexed by integer coordinates. I also need to use spatial hash on that, so I went on creating a Vector3i structure to hold a 3D integer position that can also serve as key in dictionaries.

However it enters in conflict [with another module I made](https://github.com/Zylann/godot_voxel/blob/master/vector3i.h). I could use a different name or use a namespace, but it feels silly because I basically copy/paste the existing implementation.

Would it be better if we had a Vector2i and Vector3i structure built-in the core?

**Comment by bojidar-bg** [comment]
Related/duplicate of #3286

**Comment by bojidar-bg** [comment]
Also, note that we already have those classes, they just have to be bound (`Point2i`/`Point3i`)

**Comment by bojidar-bg** [comment]
Closing in favour of #3286, as it is older and seems to have more activity.
