### ISSUE TITLE
Godot 4.0.beta refuses to display anything but a gray screen on Intel Sandy Bridge integrated graphics

### ISSUE THREAD

**Issue by Erisfiregamer1** [godotengine/godot#67595]
### Godot version

v4.0.beta3.mono.official.01ae26d31

### System information

GLES3, Intel HD Graphics 3000 (OpenGL 3.3, Mesa (Before you say the card doesn't support it, Mesa for some reason does. Words do not describe my confusion))

### Issue description

Godot refuses to display anything other than a gray screen. No harmful errors are seen in the console when it is being run.
Godot is being run with the opengl3 rendering flag, because the fallback is broken for some reason on Beta 3. /shrug
![Screenshot from 2022-10-18 16-10-08](https://user-images.githubusercontent.com/54373833/196535888-97df4249-aaf9-4765-97d3-f4e0a3e325a3.png)

### Steps to reproduce

- Download Godot 4.0 Beta 3 (Linux x86_64 version)
- Start Godot with the OpenGL3 rendering flag
- gray screen D:

### Minimal reproduction project

How am I supposed to get a project when I can't even get past the editor? :(

**Comment by clayjohn** [comment]
Could you please post the contents of what is printed out in the console when you attempt to run Godot?

**Comment by Calinou** [comment]
> GLES3, Intel HD Graphics 3000 (OpenGL 3.3, Mesa (Before you say the card doesn't support it, Mesa for some reason does. Words do not describe my confusion))

No, there is no GLES3 support on Sandy Bridge IGPs at all. Mesa is lying here – other OpenGL 3.x-based apps/games won't work (try [Tesseract](http://tesseract.gg) or [Red Eclipse](https://redeclipse.net)) :slightly_smiling_face:

**Comment by Erisfiregamer1** [comment]
> Try using the `--single-window` command line argument.
> 
> > GLES3, Intel HD Graphics 3000 (OpenGL 3.3, Mesa (Before you say the card doesn't support it, Mesa for some reason does. Words do not describe my confusion))
> 
> No, there is no real OpenGL 3.2+ support on Sandy Bridge IGPs on any OS. Mesa is lying here – other OpenGL 3.x-based apps/games won't work (try [Tesseract](http://tesseract.gg) or [Red Eclipse](https://redeclipse.net)) 🙂
> 
> It's possible that Mesa developers tried to bridge the gap and implement missing features to claim OpenGL 3.3 support, but this kind of support is often unusable in anything else than demo projects. The same thing happend with Intel GMA having OpenGL 2.0 support on Linux, but only 1.4 on Windows. Mesa developers ended up downgrading it to OpenGL 1.4 on Linux, as OpenGL 2.0 support was so broken there was no point in having it.
> 
> The Windows driver is limited to OpenGL 3.1, which doesn't suffice to run the OpenGL renderer in Godot 4 (OpenGL 3.3 is required).

You'd be wrong. Minecraft versions above 1.17 (require 3.3) work fine on it, I checked. And the MESA team seem to be fixing bugs with this "Crocus" driver.

**Comment by Erisfiregamer1** [comment]
> Could you please post the contents of what is printed out in the console when you attempt to run Godot? Including what command you use to run Godot

Nothing out of the ordinary... Just 2 errors from the PR that set the editor to use OpenGL by default.

**Comment by clayjohn** [comment]
Just a reminder to post what command you used to run Godot here when you have a chance. Without that basic information we can't do anything

**Comment by Erisfiregamer1** [comment]
./gd.x86_64 --rendering-driver opengl3

**Comment by SonnyBonds** [comment]
I get this too, which is a problem since the project manager now starts with OpenGL.
I'm on macOS.
OpenGL Renderer: Intel Iris Pro OpenGL Engine

**Comment by Erisfiregamer1** [comment]
Okay, so it's not just my iGPU being an absolute crap sack as usual. (it tries, but it still fails.) Good to know someone else has it, that way it isn't just an isolated issue.

**Comment by Calinou** [comment]
@SonnyBonds Which macOS version and exact Intel CPU model are you using?

**Comment by SonnyBonds** [comment]
> @SonnyBonds Which macOS version and exact Intel CPU model are you using?

I'm on macOS 12.6 Monterey. This is the information about the display device available in system info:
```
Intel Iris Pro:

  Chipset Model:	Intel Iris Pro
  Type:	GPU
  Bus:	Built-In
  VRAM (Dynamic, Max):	1536 MB
  Vendor:	Intel
  Device ID:	0x0d26
  Revision ID:	0x0008
  Metal Family:	Supported, Metal GPUFamily macOS 1
  Displays:
Colour LCD:
  Display Type:	Built-In Retina LCD
  Resolution:	2880x1800 Retina
  Framebuffer Depth:	24-Bit Colour (ARGB8888)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Automatically Adjust Brightness:	No
  Connection Type:	Internal
```

Let me know if there is anything else I should look up or test. I can debug things if needed but haven't had time to find a place to start digging.

**Comment by clayjohn** [comment]
@SonnyBonds Does the project manager work fine for you when running on the Vulkan backend?

**Comment by SonnyBonds** [comment]
@clayjohn Apart from suffering from the #62322 issue, yes.

**Comment by SonnyBonds** [comment]
I should also note that it seems like the interaction works, I can click things, but itsall gray.

**Comment by qarmin** [comment]
Not sure if this is related to this issue, but after creating apitrace on Intel HD 3000 with project manager and later replaying it, then I got this error
```
Mesa: User error: GL_INVALID_OPERATION in glGetNamedBufferPointerv(non-existent buffer object 4)
31733: message: major api error 1: GL_INVALID_OPERATION in glGetNamedBufferPointerv(non-existent buffer object 4)
31733 @0 glDeleteBuffers(n = 1, buffers = &4)
31733: warning: glGetError(glDeleteBuffers) = GL_INVALID_OPERATION
Rendered 28 frames in 0.690269 secs, average of 40.5639 fps
```
Apitrace
[Pobrane.zip](https://github.com/godotengine/godot/files/10046799/Pobrane.zip)

**Comment by Erisfiregamer1** [comment]
Hmm, I'm going to try putting an issue in on the Mesa repository. It's starting to sound like this is an issue with their Crocus driver again...

**Comment by SonnyBonds** [comment]
I don't think I have anything Mesa involved at all. Just stock Macbook drivers. How do I know for sure?

**Comment by Erisfiregamer1** [comment]
You never know. I'm having the same issue on Mesa so I might as well bug-report it.

**Comment by akien-mga** [comment]
macOS drivers don't use Mesa indeed, so it wouldn't be _directly_ related. It can be however that the same issue is present in both macOS and Mesa Linux drivers for similar Intel chipsets - notably because the open source Mesa drivers are the official Intel drivers and that codebase may be partially used for the macOS drivers. But that's a wild guess, until we know we should consider both as different bugs - that may happen to have the same cause/fix, in Godot or in upstream drivers.
