### ISSUE TITLE
Can't build Godot for HTML5 (from Windows)

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#6760]
Following [this issue](https://github.com/godotengine/godot/issues/6755), I tried to compile for HTML5 using commit https://github.com/godotengine/godot/commit/9012dfb8eb7276e29d567d27b49f6fea317bd83c.

I'm using [this build script](https://gist.github.com/Calinou/f61ec28ffc1782dd6eb2dc1e3427c907) which used to work just fine. I think it broke about 2 weeks ago, but I'm not entirely sure.

```
scons: Reading SConscript files ...

scons: *** Multiple ways to build the same target were specified for: main.javascript.opt.bc  (from ['main.cpp'] and from ['input_default.javascript.opt.bc', 'main.javascript.opt.bc', 'performance.javascript.opt.bc'])
File "C:\Users\Hugo\Documents\Git\godot\main\SCsub", line 8, in <module>
```

**Comment by eska014** [comment]
Building 3.0 should work on Windows now.
I remember that error message occurring when using the Visual Studio developer command prompt, use the normal CLI for building the `javascript` platform

**Comment by Calinou** [comment]
This was fixed a long time ago, closing.
