### ISSUE TITLE
CharacterBody3D's Cylinder Collision Shape Teleports Chaotically when Colliding with a Large Slope

### ISSUE THREAD

**Issue by Gamepro5** [godotengine/godot#67616]
### Godot version

4.0 Beta 3

### System information

Windows 10 ; AMD Ryzen 7 3700X 8-Core Processor 3.60 GHz

### Issue description

I truly can't describe it. It only happens with the cylinder collision shape, and it might have something to do with the size of the slope. Other than that, I don't even know how to describe the behavior I'm seeing aside from teleporting chaotically.

### Steps to reproduce

1. Click play.
2. Observe the chaos.

### Minimal reproduction project

[CylinderBugMinimal.zip](https://github.com/godotengine/godot/files/9818270/CylinderBugMinimal.zip)

**Comment by Calinou** [comment]
> It only happens with the cylinder collision shape

Cylinder collision shapes are pretty broken. I'd use capsules or boxes instead.
