### ISSUE TITLE
Control mouse_entered and mouse_exited signals do not fire if any mouse button is pressed

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#67632]
### Godot version

3.5.1 stable

### System information

Win 10, Nvidea 765

### Issue description

The `mouse_enterd` and `mouse_exited` signals of a Control node do not fire if any mouse button is pressed over the Control Rect2 area and then moved in and out the Control Rect2 area.

This is only an issue for Godot 3.5.1, **in Godot4 beta3 this does not occur.** Signals fire normally in Godot4 beta3.

### Steps to reproduce

1. Add a Control node and connect the `mouse_entered` and `mouse_exited` signals
2. Click with any of the mouse buttons in the Control Rect2 area and then 
3. move the mouse in and out the Control Rect2 area while holding the button.
4. observe signals not firing

### Minimal reproduction project

```
func _on_ColorRect_mouse_entered():
	print("mouse_entered")

func _on_ColorRect_mouse_exited():
	print("mouse_exited")

```
I think this is faster to replicate without downloading and installing a MRP.

**Comment by Mickeon** [comment]
What about _previous_ versions. Does this occur in 3.4?

**Comment by golddotasksquestions** [comment]
@Mickeon Same issue and behavior in Godot 3.4 as in Godot 3.5.1

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/20881 (possible duplicate?).

**Comment by golddotasksquestions** [comment]
@Calinou Thanks! 
Closing as likely a duplicate of https://github.com/godotengine/godot/issues/20881
