### ISSUE TITLE
Inertia of RigidBody3D with multiple collision shapes changed after #66808

### ISSUE THREAD

**Issue by Cykyrios** [godotengine/godot#67645]
### Godot version

v4.0.beta.custom_build [5b7f62af5]

### System information

Linux Mint 21

### Issue description

The inertia calculated automatically for RigidBody3D changed after #66808 for bodies made of multiple collision shapes. This is especially noticeable when calling `get_inverse_inertia_tensor()` or `PhysicsDirectBodyState3D.inverse_inertia` for instance.
Bodies made of a single collision shape do not seem to exhibit this issue.

The expected behavior is the one from before #66808 (see MRP for details).

### Steps to reproduce

* Create a RigidBody3D, add at least 2 collision shapes (I only tested box shapes, but this should not be relevant).
* Get inverse inertia tensor.

### Minimal reproduction project

[InertiaIssue.zip](https://github.com/godotengine/godot/files/9823963/InertiaIssue.zip)

* Run the project, press space to start rotating the box (a constant torque of 1 N.m is applied).
* The inverse inertia tensor is printed to the output panel.
* The timer will stop at 12s after #66808, and 4.3s before.

You can also remove the 2 extra collision shapes to compare the results for a single shape.

The printed results for the inverse inertia tensor are the following:
* Before: [X: (6, 0, 0), Y: (0, 3, 0), Z: (0, 0, 3)]
* After: [X: (6, 0, 0), Y: (0, 1.5, 0), Z: (0, 0, 1.5)]

The correct value is the first one (mass = 1kg, box size = 1m, additional collision shapes 0.5m from origin -> inertia = 1/6 + 2 * 1/3 * 0.5^2 = 1/3, inverse inertia = 3).

**Comment by Calinou** [comment]
Can this be reproduced with RigidBody2D too?

**Comment by Cykyrios** [comment]
No, RigidBody2D is fine. I adapted the MRP and found the identical results before/after, and I also had a look at the place I fixed in my PR for RigidBody3D, and the renames in RigidBody2D look fine to me.
