### ISSUE TITLE
Cannot Paste Materials

### ISSUE THREAD

**Issue by tinmanjuggernaut** [godotengine/godot#67641]
### Godot version

Godot 4 Beta 2-3

### System information

Windows 11/64, RTX 3070, Vulkan

### Issue description

We used to be able to copy and paste material resources in Beta 1 and before. 

![image](https://user-images.githubusercontent.com/632766/196770261-04844aad-ef2f-4db2-a5e3-10f9710f1515.png)

From Beta 2, After copying the material, Paste no longer shows up. Please restore it.

![image](https://user-images.githubusercontent.com/632766/196771347-6ddd8470-3c38-44cc-bfe9-3fc21b291c21.png)

I can paste these resources: scripts, shaders, array mesh, texture, skins, shapes, and anything else I've tried. Perhaps it's limited only to materials. That's the only resource I can find so far.

### Steps to reproduce

Make a mesh instance with a sphere
Make a material in the surface override slot
Copy the material
The Paste menu option shows up in Beta 1 and prior. Not in Beta 2.

**Comment by clayjohn** [comment]
I can confirm this is reproducible on latest master a8c805be2947b211ee8b881d7a8bab7cdc86e170

**Comment by tinmanjuggernaut** [comment]
I wrote it affects beta 2 and 3. It was not an issue in beta 1.
