### ISSUE TITLE
Comment block/zone for Visual Script blocks

### ISSUE THREAD

**Issue by toby3d** [godotengine/godot#6764]
It would be very convenient to cut around some blocks and put them in a stand-out white zone, which can be signed in order to understand what is contained in this zone.

For example:
![](http://i.imgur.com/SdM8x1F.png)

**Comment by mefihl** [comment]
Comment block is alredy exists. https://pbs.twimg.com/media/CqzR2akW8AAzToF.jpg:large

**Comment by bojidar-bg** [comment]
Yeah, seems like it is already in the source (should be Data/Comment by the look of it).. So, closing
