### ISSUE TITLE
Shader function with custom defined return type raises error

### ISSUE THREAD

**Issue by esmeraldaliaj** [godotengine/godot#67658]
### Godot version

4.0.beta3

### System information

Windows 10

### Issue description

I have two files, one containing definitions, and the other some functions that look like this:

![image](https://user-images.githubusercontent.com/5569899/196846220-5345e2ac-f610-441d-b636-908b4679af67.png)

A user from the [godot public forums](https://godotforums.org/d/31571-shader-function-with-custom-defined-return-type/8) gave it a try and it was working fine for him. 

### Steps to reproduce

Create a file `definitions.gdshaderinc` containing

`#define Number float`

and another file `functions.gdshaderinc` containing

```
#include "definitions.gdshaderinc"

Number ClampCosine(Number mu) {
  return clamp(mu, Number(-1.0), Number(1.0));
}
```

**Comment by esmeraldaliaj** [comment]
I want to add some more information on this one. In a `.gdshaderinc` file I want to use *PI*, so I had to define it as such

`const float PI = 3.14159265358979323846f;`

but then when I include this in a `.gdshader` file, because *PI* is already defined there, I get:

![image](https://user-images.githubusercontent.com/5569899/196996480-2fdc2550-0b34-4444-8fbb-39fbbfebd2ef.png)

Additionally when I tried to use an `assert()` I got the following error, no matter what's inside my assertion:

![image](https://user-images.githubusercontent.com/5569899/196996741-9038e2f3-9c6b-44a9-a0ee-48bd824472cf.png)

[atmosphere_tests.zip](https://github.com/godotengine/godot/files/9831792/atmosphere_tests.zip)

**Comment by clayjohn** [comment]
> I want to add some more information on this one. In a `.gdshaderinc` file I want to use _PI_, so I had to define it as such
> 
> `const float PI = 3.14159265358979323846f;`
> 
> but then when I include this in a `.gdshader` file, because _PI_ is already defined there, I get:
> 
> ![image](https://user-images.githubusercontent.com/5569899/196996480-2fdc2550-0b34-4444-8fbb-39fbbfebd2ef.png)

You can't define PI in your shader because it is already defined as a Built-in (see the spatial shader docs for example https://docs.godotengine.org/en/latest/tutorials/shaders/shader_reference/spatial_shader.html)

> Additionally when I tried to use an `assert()` I got the following error, no matter what's inside my assertion:
> 
> ![image](https://user-images.githubusercontent.com/5569899/196996741-9038e2f3-9c6b-44a9-a0ee-48bd824472cf.png)

GLSL doesn't have an assert function, so it is expected that this will result in an error. Please see the list of builtin functions in the docs https://docs.godotengine.org/en/latest/tutorials/shaders/shader_reference/shading_language.html#built-in-functions

**Comment by esmeraldaliaj** [comment]
Thanks for the update. So then this means that if I want to use PI inside a `.gdshaderinc` file, I must define it with a different name?
Got it about the asserts, I'm scratching those from my code.

**Comment by esmeraldaliaj** [comment]
So my issue is (apart from the obvious that I mention in my original post) that it shows OK when I'm on a `.gdshader` file, but if I dont define it on a `gdshaderinc` file, then I get an undefined variable error. I'm using the latest beta3 btw.

**Comment by esmeraldaliaj** [comment]
Closing this. Two different people and my other computer worked fine. It must be something irrelevant.
Note on the fact the PI discussion above. I think that still exists as an issue.
