### ISSUE TITLE
Broken saving of @exported Array properties in @tool scripts

### ISSUE THREAD

**Issue by Iniquitatis** [godotengine/godot#67653]
### Godot version

v4.0.beta3.official [01ae26d31]

### System information

Windows 10, Vulkan, GeForce GTX 1650 (516.94)

### Issue description

Exported array properties aren't getting saved, or, more rarely, are crashing the editor when changing them through Inspector.

For example:
```
@tool
extends Node3D

@export var some_array: Array[Texture2D]:
    get:
        return some_array
    set(value):
        some_array = value
```

What works without problems:
1. Variables/properties in non-`@tool` scripts.
2. Variables without `get`/`set`. **UPDATE**: Seems like it is not always the case because variables sometimes also aren't getting saved.
3. Untyped arrays (`@export var some_array: Array`). _Though they become a bit pointless as their contents cannot be modified through the Inspector._
4. Generic `@export var some_array: Array[Resource]`.

### Steps to reproduce

1. Open the attached reproduction project.
4. Open the `array_test.tscn` scene.
5. Select `SomeNode` node.
6. Add some elements to the arrays listed in the Inspector.
7. Save the scene.
8. Close it.
9. Open the scene again.
10. Select `SomeNode` node.
11. Check contents of the arrays in the Inspector.
12. First array gets saved _(which isn't a property, but a variable)_, others do not.
13. _(Optional)_ Check the attached script for the examples.

### Minimal reproduction project

[ArrayTest.zip](https://github.com/godotengine/godot/files/9825244/ArrayTest.zip)

**Comment by Mickeon** [comment]
So it's all Array properties, even if the arrays are not typed?

**Comment by Iniquitatis** [comment]
Updated OP with more information.

**Comment by KoBeWi** [comment]
Can't reproduce with the attached project, the properties are saved:
![image](https://user-images.githubusercontent.com/2223172/197361920-703a8cc5-744c-4055-b9a2-df2eb21ac86e.png)
The crash might be related to #64979

**Comment by Iniquitatis** [comment]
@KoBeWi Yes, they are saved to the `*.tscn` file, but won't be loaded after reopening project or scene, so after that they're lost.
(I guess it might be related to the UI code, not the GDScript itself.)

**Comment by KoBeWi** [comment]
Ah, right...

**Comment by L4Vo5** [comment]
Looking at this again, I think the issue at heart is #58285. The Resource loader will interpret the array as a normal `Array`, and `set()` will be used, which will fail silently and leave the value as default.
