### ISSUE TITLE
Can't use Ctrl+D to duplicate line in script files.

### ISSUE THREAD

**Issue by prominentdetail** [godotengine/godot#67654]
### Godot version

v4.0.beta.custom_build [7fe2f25ef]

### System information

windows 10

### Issue description

I can't use Ctrl+D to duplicate line in script files. In godot 3.x I could use it, but it doesn't work in godot 4.  :(

### Steps to reproduce

Make script and type a line of code.. then press Ctrl+D.
It doesn't duplicate the line.

**Comment by Iniquitatis** [comment]
Shortcut was changed to `Ctrl+Shift+D`.

**Comment by prominentdetail** [comment]
Is there any way to change it back to ctrl+d? My other text editors use ctrl+d for duplicating lines, so it feels a bit weird.

**Comment by Anutrix** [comment]
Since we intentionally made the change in https://github.com/godotengine/godot/commit/80f4e407b231bc19d0d2ef0aaaf9e3389f9a621d, can we close this ticket?

**Comment by prominentdetail** [comment]
On that page it says "(With no selection active, the whole line will be copied.)"
Does that mean that Ctrl+D should duplicate the line if no selection is active? Because it doesn't do that- instead it just selects the current word.

**Comment by prominentdetail** [comment]
Oh ok thanks- I guess I'll close this then, since no point having it open, and there's option to rebind it.
