### ISSUE TITLE
SkeletonModificationStack3D stops working when made unique and local to scene.

### ISSUE THREAD

**Issue by Anthony-MostlyHarmless** [godotengine/godot#67669]
### Godot version

v4.0.beta3.official [01ae26d31]

### System information

Windows 10, Vulkan

### Issue description

Hi,

I am having problems with procedural IK movement and I think I have managed to pinpoint the problem to a bug on `SkeletonModificationStack3D`.

I made a Spider with 4 procedurally animated legs following the tutorial here: https://youtu.be/Ezo3YVKM8Xo

Each leg has a Unique `SkeletonModificationStack3D`. If I then add one Spider to a scene it works as intended, but when I add a Second Spider the first Spider stops working normally. Its legs now follow the `SkeletonModificationStack3D` of the second Spider.

If I make the `SkeletonModificationStack3D` on the legs Local to Scene they still work as intended for the second Spider but stop working for the first one.

Thanks for all the great work on Godot :)

### Steps to reproduce

To see this issue in the Example Project open the `test_scene.tscn` and :

- If you move the red Spider around in the editor its legs work as intended but it also moves two of the legs of the blue spider (the ones whose `SkeletonModificationStack3D` was not made local to scene)
- If you move the blue Spider around in the editor two of its legs act weirdly (the ones whose `SkeletonModificationStack3D` was not made local to scene) while the two other don't move.

### Minimal reproduction project

https://github.com/Anthony-MostlyHarmless/Test_Godot_Procedural_IK

[Test_Godot_Procedural_IK.zip](https://github.com/godotengine/godot/files/9828733/Test_Godot_Procedural_IK.zip)

**Comment by TokageItLab** [comment]
Closed by #63588.
