### ISSUE TITLE
[Bug] Zooming in Visual Script Editor

### ISSUE THREAD

**Issue by toby3d** [godotengine/godot#6766]
Godot Engine v.2.2.alpha.custom_build on Linux Mint 18 Mate x86-64

After zooming it happens:
![image](https://cloud.githubusercontent.com/assets/5412322/19224917/f4afa65e-8ea8-11e6-881d-580e2fda8776.png)
![image](https://cloud.githubusercontent.com/assets/5412322/19224945/9b4a72fa-8ea9-11e6-8b0b-97239913319d.png)
No matter approximation or distancing it - all nodes visually "torn" and move along the coordinate axes.

At a scale of 1:1, everything returns to normal.

**Comment by vnen** [comment]
Duplicate of #6342.
