### ISSUE TITLE
Only center portion of a large scene gets baked light in Godot 3.5.1

### ISSUE THREAD

**Issue by norrath-hero** [godotengine/godot#67665]
### Godot version

Godot Engine v3.5.1.stable.official.6fed1ffa3

### System information

Windows 10 x64 10.0.19044.2130, OpenGL ES 2.0 Renderer: NVIDIA GeForce GTX 960/PCIe/SSE2

### Issue description

In a large scene, only the center portion of objects gets baked light, checked the bake settings for both the BakedLightmap and meshes and light many times, it's not mistake usage, probably a bug!

![image](https://user-images.githubusercontent.com/73905273/196864266-5d2fb030-3992-46fd-bb18-c19e7d633171.png)

![image](https://user-images.githubusercontent.com/73905273/196864564-fa4e46cf-165a-411c-8a58-05d8cb5ed202.png)

![image](https://user-images.githubusercontent.com/73905273/196864668-4f8a99b1-6a1b-4db7-840b-e942c4ecd1b7.png)

![image](https://user-images.githubusercontent.com/73905273/196864797-593a3e3a-ff47-4310-aca1-3b1a6b1eade3.png)

![image](https://user-images.githubusercontent.com/73905273/196867165-a341f078-bed4-4eca-b80b-95e2c1931e6e.png)

![image](https://user-images.githubusercontent.com/73905273/196864887-275c1b6f-8ca7-46b8-aec7-17759d6ad519.png)

### Steps to reproduce

Please use the Minimal reproduction project

and please rename baking.z01.zip to baking.z01 after you download

### Minimal reproduction project

[baking.zip](https://github.com/godotengine/godot/files/9826670/baking.zip)

[baking.z01.zip](https://github.com/godotengine/godot/files/9826687/baking.z01.zip)

**Comment by Calinou** [comment]
The extents of your BakedLightmap node are too small (check the inspector). You need to resize them to encompass the entire scene.
