### ISSUE TITLE
[4.0] New ColorPicker UX lacks customization options

### ISSUE THREAD

**Issue by cridenour** [godotengine/godot#67663]
### Godot version

v4.0.beta3.official [01ae26d31]

### System information

Windows 10

### Issue description

The old color picker gave you the option to hide some of the editor features like Presets which allowed the control to be helpful for simple inputs in-game. The recent UX sprint left us without similar options.

### Steps to reproduce

Add ColorPicker to in-game UI, attempt to remove Recent Colors, Swatches, the new color mode tab bar.

**Comment by Calinou** [comment]
cc @Vitika9 @KoBeWi

**Comment by KoBeWi** [comment]
The behavior is unchanged, the `presets_enabled` property only disables the `+` button like it did before. We could make the ColorPicker more "modular", it's just a matter of hiding some parts.

**Comment by akien-mga** [comment]
Fixed by #67741.
