### ISSUE TITLE
Physical shift key is ignored in input search field of project settings

### ISSUE THREAD

**Issue by honeycuttGitHub** [godotengine/godot#67675]
### Godot version

3.5.1 - Android ARM64

### System information

Samsung Galaxy Tab S7+, Android 12, OneUI 4.1.1, WiFi

### Issue description

In the project settings, when entering to the search field on the input page, the special characters cannot be entered since the shift key is not considered. No special characters or uppercase can be entered, underscore in particular is valuable in this context. The shift key can be used to enter capital and special characters in other fields in the editor such as scripts, file names, new project directories, etc.. I have yet to notice any other place where this issue occurs. I can enter special characters using the on screen IME. 

### Steps to reproduce

0. Own Samsung Galaxy Tab S7+ with Samsung Bookcover Keyboard - I have no other device to confirm that the issue is not unique to this configuration.

1. Download the APK from the official godoteditor.org page
2. Install APK
3. Open or create a project
4. Open project settings
5. Navigate to input pane
6. Select search field
7. Observe that shift cannot be used to enter special characters

**Comment by honeycuttGitHub** [comment]
I wish to label as follows: 
label:platform:android label:topic:editor

but I do not see the option to modify labels.

**Comment by Calinou** [comment]
> I wish to label as follows: label:platform:android label:topic:editor
> 
> but I do not see the option to modify labels.

On GitHub, labels can only be assigned by people with triage permissions on a repository.

**Comment by honeycuttGitHub** [comment]
I have come to find that the issue is intermittent and can be worked around by clicking on one of the list elements of the input pane, for example the "ui_up" element, then returning to the text field. In that case the shift key will be regarded again. 

There are other small issues with input, for example the backspace key was only erasing the last 5 characters of a file I was renaming. I had to select the entire field and then start typing to overwrite the existing text. In that case the shift key did work since that was how I was highlighting the text. 

If it happens elsewhere I will update with specific details and I will include if selecting a different element will cause normal behavior to resume.

**Comment by honeycuttGitHub** [comment]
I connected my bluetooth keyboard, Logitech G613, and have issues that are the same as with the bookcover keyboard, in addition to issues not previously mentioned. Both of the following issues occur with both input devices.

Whenever a key is being assigned in the input map settings, some keys cannot be assigned and only say "Unknown(Physical)" when auto-detected or "Unknown" alone if not using physical keys, such as the Escape key or the tilde key.

I also notice that the Android navigation tries to take over sometimes, causing the entire activity to be selected, resulting in a highlight around the edge of the screen. This happens upredictably when using Tab to switch between input fields.

**Comment by Gromph** [comment]
I ran across this issue typing with a bluetooth keyboard on Amazon Fire TV. Shift and Caps lock didn't work, so couldn't type upper case.

We tracked down the issue to:
godot/platform/android/java/lib/src/org/godotengine/godot/input/GodotInputHandler.java
In onKeyDown and onKeyUp. the line:
final int chr = event.getUnicodeChar(0);

Should be:
final int chr = event.getUnicodeChar(event.getMetaState());

**Comment by Calinou** [comment]
@Gromph Feel free to open a pull request for this :slightly_smiling_face:

**Comment by Gromph** [comment]
Turns out this was already fixed in commit https://github.com/godotengine/godot/commit/2f7de4c8ed691cf0a11f0359ef2db48d390ff13c

It'd be nice to get that in the next 3.5.x update

**Comment by akien-mga** [comment]
Fixed by #62886.
