### ISSUE TITLE
Gaps in Gridmap when moving camera

### ISSUE THREAD

**Issue by DoctorVaan** [godotengine/godot#67673]
### Godot version

3.5

### System information

Windows 10

### Issue description

Lines between gridmap cells. theyre are not always there but flicker when moving.

![gridmap](https://user-images.githubusercontent.com/71151157/196943512-e949a84c-6b83-477c-90f0-d4c0f2b01678.png)

-The window display properties are 1920x1080, viewport, keep.
-The camera is orthogonal, 45 angle, the mesh is a 1x1x1 cube, the texture used in the albedo has no filter, gridmap cellsize is 1x1x1.

-This is the box texture (66x44).
![FL0](https://user-images.githubusercontent.com/71151157/196943760-495e699d-260f-4cdc-9181-c8b198374582.png)
-I noted the lines are the same color as the surrounding pixels of the top square, so making the white square 1 pixel wider and taller kinda fixes the problem.

I've tried changing the gridmap cell scale property to something like 1.002, maybe helps a bit but the lines are still very obvious.
I tried pixel snap in the project settings, does not help.
I tried all viewport stretch settings, different resolutions, lines wont go away!

Is there a way around this?

### Steps to reproduce

Spatial.
Gridmap.
Meshlib, 1 box with a texture (top different than walls) so lines are different color and visible, and no filter.
Orthogonal Camera (but it happens aswell in perspective, just less obvious).
Move the camera, and there they are!

### Minimal reproduction project

[GridmapTest.zip](https://github.com/godotengine/godot/files/9830074/GridmapTest.zip)

**Comment by Calinou** [comment]
> I've tried changing the gridmap cell scale property to something like 1.002, maybe helps a bit but the lines are still very obvious.
I tried pixel snap in the project settings, does not help.

You need to *decrease* the cell size or make meshes larger instead.

**Comment by DoctorVaan** [comment]
> Related to https://github.com/godotengine/godot/issues/16337 (possible duplicate?).

MSAA and FSAA are both disabled.

> You need to decrease the cell size or make meshes larger instead. Otherwise, you're actually increasing the gap's size.

I dont mean the cell size, there is a property in Gridmap that scales the cells, I think its called cell scale.

**Comment by golddotasksquestions** [comment]
I can confirm this issue.

I spend more than two hours, going through everything in OPs project. Checking all transforms, checking all project settings, checking the meshlibrary and camera ...

I also made new Gridmaps and new Meshlibrary from scratch with 1x1x1 cubes, 1.01 x 1.01 x 1.01 cubes and 1.1 x 1.1 x 1.1 cubes.

These visual horizontal and vertical lines keep appearing no matter what I do. I am convinced at this point the issue is not with the project, but with with Godot. 

**It only seems to appear with Gridmaps and Cameras in Orthographic mode.**

**Comment by DoctorVaan** [comment]
> It only seems to appear with Gridmaps and Cameras in Orthogonal mode.

In the minimal reproduction project that I uploaded here (and in my project too, at least on my end), perspective camera show lines aswell.

**Comment by DoctorVaan** [comment]
I noticed it even happens on the editor, just preview the camera and move it around with the inspector.
Im assuming ppl know about this but its very hard to fix or even unsolvable right now, cuz this is a very obvious problem and not hard at all to come across (most of the properties of the few nodes used to replicate it are left at default).
Hopefully 4.0 fixes this.

**Comment by Calinou** [comment]
> Then I created yet another MeshLibrary, again with the same 1x1x1 cube, but with OPs texture:
> 
> And the issue appears!

This is a mipmap/linear filtering bleeding issue. You need to pad your texture with *at least* 1 pixel (if you have mipmaps disabled), or more pixels if you have mipmaps enabled. How much padding you need depends on the texture's size and the maximum mipmap level you expect to be viewed in practice.

**Comment by elvisish** [comment]
> > Then I created yet another MeshLibrary, again with the same 1x1x1 cube, but with OPs texture:
> > And the issue appears!
> 
> This is a mipmap/linear filtering bleeding issue. You need to pad your texture with _at least_ 1 pixel of the same color (if you have mipmaps disabled), or more pixels if you have mipmaps enabled. How much padding you need depends on the texture's size and the maximum mipmap level you expect to be viewed in practice.
> 
> Duplicate of #27837.

Is this a duplicate? I'm having the same issue when the camera moves:
![image](https://github.com/godotengine/godot/assets/16231628/ec24306b-ed75-472d-8847-84dd289a631f)

**Comment by elamaunt** [comment]
I figured out that the issue is actual only for .gltf format exported from Blender.
I switched to dae and the gaps has dissapeared. But dae has other blending issues. 
![image](https://github.com/godotengine/godot/assets/804384/db57ee14-0702-4bdd-8648-8617f259e199)
