### ISSUE TITLE
Navigation 3D Max Slope Variable Limit Too Low

### ISSUE THREAD

**Issue by 1Lethn1** [godotengine/godot#67670]
### Godot version

3.5.1 Stable

### System information

Windows 11

### Issue description

On the advice of user @rburing in chat I've opened up a potential usability issue with regards to how the 3D navmesh bakes on sloped surfaces in 3.5.1 and I've detailed the problem in this thread on the Godot forums.

https://godotforums.org/d/31289-investigating-the-floating-navmesh-agent-behaviour-and-fixing-it-for-good/14

Initially thought when I was first investigating the behaviour it was some kind of issue with the navmesh agent itself and experimented a lot to find out what was going on but after a lot of fiddling I realised that was just the navmesh agent reacting to the way the navmesh agent getting either trapped within the navmesh itself because I increased the height to make the slopes bake correctly with an offset or they would be too many gaps baked into the mesh that I was baking on because the slopes were too high for the current 90 degrees max slope variable to deal with.

I don't know if this necessarily counts as a 'bug' but I seem to have accidentally stumbled on a small limitation with the engine itself that could be solved with some tweaking. Would appreciate some comments on this, there are use cases like with my game where I would like the nav mesh agents to be able to walk up slopes beyond the limits currently in place. Due to how many problems it causes it definitely has caused confusion on whether or not the navmesh is simply broken in how it behaves currently or something else and needs addressing.

### Steps to reproduce

https://godotforums.org/d/31289-investigating-the-floating-navmesh-agent-behaviour-and-fixing-it-for-good/14

**Comment by smix8** [comment]
As mentioned in chat max slope has nothing to do with this. A right angle equals 90 , and therefore a slope is always measured between 0 (horizontal) and 90 (vertical) which is the limit. As also mentioned need an MRP for this, just by looking at the images I doubt there is a bug, this kind of landscape should have no issues so I assume it is just a setup problem.

**Comment by smix8** [comment]
Well, in this case the problem is not the physics or the navigation but the extreme scaling values that scale 3D nodes up and down in your project. While some scaling may be o.k. (better avoid node scaling all together) such large values (x50) with multiple nodes in the nodetree are asking for problems.

Your source geometry mesh for the navmesh baking is basically miniature tiny. The navmesh baking still manages to bake it somehow but has to scale the result up a lot with the scaled node. If you go back to original scale that matches the values in the NavigationMesh bake properties you can immediatly see why things go wrong while voxelizing this 3D source mesh and why with certain settings the baking goes so wrong and creates gaps on all slopes. Due to the tiny scale a single cell basically needs to flatten so much surface area to create the minimum cell size that the slope turns into a single cell that has a large height difference which is threaded like it is a wall creating the gaps.

There are bugs in the actor movement logic in this project. The scripts are convoluted so I did not attempt to find the bug and created a new basic navigation actor for testing that had no issues with pathfinding or movement on this navmesh.

**Comment by 1Lethn1** [comment]
Thanks a lot for all this detail! It's needed, that's fascinating, I didn't know scale could affect it so much, I had mixed and matched the scale quite a bit to try and understand what was going on with the baking but I've been initially thinking that it was the slope. Would you mind explaining which values in the navmesh the scale of the land mesh it's baking to need to be the same? That's something I simply haven't seen discussed in tutorials or even the documentation.

**Comment by Zireael07** [comment]
Why would you even need to scale things up x50???

**Comment by 1Lethn1** [comment]
@Zireael07 I was rage experimenting

**Comment by 1Lethn1** [comment]
Okay, now I have some time again, I've been messing with the scale and everything and put it back to the default settings, it is now baking over the slopes correctly. I haven't yet experimented with steeper slopes and I will be doing but when I reduce the cell height to the minimum the gaps appear again. Ideally I think I want to have the navmesh hugging the island mesh for the sake of accuracy and minimal tweaking. 

I take it when it comes to the scale if I want to change that I should be changing it within Blender and then re-importing it? That's something important I hadn't understood so I'll be doing that from now on. Also, I feel like a massive idiot for not realising this but it's obvious now I had it pointed out to me, the reason the navmesh was scaled differently was because I was creating a child of the mesh itself and because I had initially switched up the scale it was automatically copying that LOL. Yeah I was raging hard at this problem and not paying attention.

![1](https://user-images.githubusercontent.com/116270409/197386787-d4cb040f-d7f1-47b1-9472-629c59b53805.png)

![2](https://user-images.githubusercontent.com/116270409/197386788-2b87d2bd-fe1a-4908-b7ef-2f91eb801958.png)

Just posting up screenshots as well to show I've got the scales normal now.

![3](https://user-images.githubusercontent.com/116270409/197386800-d76ae0a9-b400-47b4-9698-8f7726169aba.png)

![4](https://user-images.githubusercontent.com/116270409/197386802-e6fbf5d7-05cc-4b1e-b606-7ba7a809b218.png)

**Comment by smix8** [comment]
The cell_height is used for the baking voxels and this value is also used for the navmesh height offset from the "ground". Low height values cost a lot of baking  performance as it needs to create multiple additional voxel grid layers to cover the same geometry height. If the height cells are too small the geometry angle might not be conderised a walkable slope but a vertical wall and that is way additional gaps appear with too small cell heights. You should never count on the navmesh offset being accurate towards the collision to e.g. place actors on the ground, as it is an aproximation, especially on slopes the offset can vary greatly.

**Comment by 1Lethn1** [comment]
Thanks again for all that detail it really is helping, I'll get to experimenting again and see what I can do with all of this. I think one thing is clear if there are no bugs and this is just a bit of a fiddly job to get through. There needs to be a proper write up done on exactly what you can do to make everything work correctly once I'm done I'll be happy to do a write up on the forum. 

However I would also recommend this be done for the documentation because otherwise you'll have a lot of frustrated complainers like me not understanding what's going on with tall these variables and any topic I make is potentially going to get buried after awhile. I mean if it's approved by everyone else, I have no problem doing a write up for the documentation as well to specifically deal with slopes.

It's kind of funny now I think about it because I suspect that even the tutorial makers weren't posting up any information on this significant issue they seemed to cheat really and use completely flat floors whenever they made their tutorials which makes me wonder how much they had really tinkered with the navmesh.

One thing I might recommend debug wise is to prevent any annoyance with the scaling is maybe have a check run when the navmesh is baked or a mesh is made a child of the navmesh to see if the scales are equal and if they're not flag up a yellow warning. This will be another way you can reduce any potential spam about these settings.

**Comment by shazzsamed** [comment]
Hi i am completely new to open source can someone navigate me or assign me this issue

**Comment by Zireael07** [comment]
@shazzsamed This turned out to be user error, not a real issue. Plus Godot doesn't practice assigning people issues

**Comment by smix8** [comment]
@1Lethn1 
If you think something should be added to the existing navigation documentation please look at the Godot 4 doc [here](https://docs.godotengine.org/en/latest/tutorials/navigation) and go from there as Godot 3.5 has no backport of this navigation doc rightnow. Also for baking take into account the NavigationMesh class-doc [here](https://docs.godotengine.org/en/latest/classes/class_navigationmesh.html#class-navigationmesh) as it was decided to not repeat class-doc info, e.g. baking property descriptions, inside the godot-doc navigation pages.

**Comment by 1Lethn1** [comment]
@smix8 Will do! Thanks, I'll even throw in a basic wondering script as I've got that working properly now as well to get people started, basic movement from point A to point B is easy to look up.

**Comment by 1Lethn1** [comment]
![1](https://user-images.githubusercontent.com/116270409/197794520-68dfef9d-706c-47bd-8aef-c2ef21cdbcb4.png)

Hurray! Ultra steep slopes are now baking correctly with a bit of height offset, I've still got experiments to do now with the agent movement and making sure that's relatively glitch free but I'm quite happy I think this can be counted as a solved issue. When I've got the time I'll do a more organised and coherent write up on the topic to help out anyone else who stumbles on this navmesh weirdness and doesn't know what to do.

**Comment by smix8** [comment]
> I think this can be counted as a solved issue

I guess this issue can be closed then.
