### ISSUE TITLE
Node names reject a single "1" at the end of their name.

### ISSUE THREAD

**Issue by hetdegon** [godotengine/godot#6768]
**Operating system or device - Godot version:**
Ubuntu 16.10, 64b
Godot fea1fb0925142c3279fd3afaf27e80e78cd2e1e8

**Issue description** (what happened, and what was expected):
I had a scene with its parent node named "BattleChoice1" which was instanced into another scene along with a "BattleChoice2" node. But suddenly and without any interaction it was renamed "BattleChoice" and any attempts to change it back proved futile. From renaming it in the editor to altering the tscn scene.
![](http://i.imgur.com/r9kAkJD.gif)

Those 2 scenes are the only ones with "BattleChoice" names, and there's no possible way to change it back to "BattleChoice1". I changed the nodepaths appropriately to suit the change, but it's still weird and I never touched the scene itself (I was editing a different scene at the time and when running a reference turned out null for no apparent reason).

**Steps to reproduce:**
Given the strange circumstances I can't provide reproduction steps, and since it's a component in a relatively large project I can't quite link to the entire project (I got the source on github but it's one day old, at https://github.com/hetdegon/VaultCityRaiders ,so it might not be suitable to reproduce).

_Alternately, the editor got possessed by a ghost, but we are people of science here._

**Comment by hetdegon** [comment]
Apparently, it seems the editor isn't letting me name things "anything1" such as "LV1" or "q1". The 1 at the end is rejected. "11" however is not. I renamed the issue name to accommodate for that fact.

**Comment by akien-mga** [comment]
CC @RandomShaper

**Comment by RandomShaper** [comment]
@hetdegon, I like to use Godot on the cutting edge too, but things can break. I hope your project hasn't got too messed up.

Have you found any other misbehavior related to this change (especially after the fix)?

**Comment by hetdegon** [comment]
@RandomShaper Oh yeah a bit of breakage is expected. I am used to that kind of thing, I just report, debug and soldier on.

Other than a few node templates in this fashion doing this:
![snapshot14](https://cloud.githubusercontent.com/assets/323651/19247974/b6b23396-8f2d-11e6-8c87-54b560bb2ac2.png)
all other numbers seem to work properly, it's just the lone "1" misbehaving as far as I can tell.

**Comment by RandomShaper** [comment]
That happens before or after merging the new PR?

**Comment by hetdegon** [comment]
Doesn't seem to be in master yet.

**Comment by hetdegon** [comment]
Alright, seems it's fixed now, thanks!

**Comment by RandomShaper** [comment]
I'm glad. Good luck with your project!
