### ISSUE TITLE
Severe Collision Precision Errors Increase Proportionally to the Distance from the Origin of the Map

### ISSUE THREAD

**Issue by Gamepro5** [godotengine/godot#67687]
### Godot version

4.0 Beta 3

### System information

Windows 10; AMD Ryzen 7 3700X 8-Core Processor 3.60 GHz

### Issue description

It is known that scaling collision shapes messes with the physics engine. This is not that. The collision shape is not scaled, but its size is increased (as recommended by @rburing).

For some reason, it looks as if the precision of collision reported on large objects like this one are not great even if they are "scaled" properly. Drastically increasing the magnitude of the snap vector can help somewhat, but that would not be ideal because it would mean we snap to the ground from much higher than usual. I even enabled "recovery_as_collision" on all the significant move_and_collides() that report information, but this didn't help.

### Steps to reproduce

Attached is a simple character controller that shows the normal vector as a raycast and displays whether or not the floor check returns true.

1. Download and open project
2. Enable visible collision shapes
3. Click run
4. Walk up the slope
5. Watch as the collision reporting gets very inaccurate the higher up you go

### Minimal reproduction project
Demonstration video: https://www.youtube.com/watch?v=PGOHiI-5beM

UPDATED REPRODUCTION PROJECT:
[CharactedControllerBug.zip](https://github.com/godotengine/godot/files/9874544/CharactedControllerBug.zip)

**Comment by Calinou** [comment]
How large is the collision shape? When using a single-precision build (the default), precision issues are expected to happen as soon as one of the positions exceeds 8192 units or so.

**Comment by Gamepro5** [comment]
Not that large. You only reach about y=200

**Comment by Zireael07** [comment]
There's an open issue where things jitter with values around 100 on a single axis, may be related. Although IIRC that one was for Bullet and you seem to be... on Godot physics? Please confirm which engine you're using

**Comment by Gamepro5** [comment]
I'm using Godot physics. Bullet isn't an option on the Godot 4 beta it seems.

**Comment by Gamepro5** [comment]
I changed the name before after more testing I discovered that it has nothing to do with the size of the collision shape but rather how far away from (0,0,0) you are. If you make a small slope in the air around y=560, you will have the same precision errors as if your slope was 500 units high. I attached an example project where even simple move_and_collide() in the direction Vector3.DOWN (serving as a floor check) fails quite frequently as you get in the triple digits in terms of position.

**Comment by Gamepro5** [comment]
I solved countless physics issues including this one by compiling the engine with 64 bit floats. This led me to ask the question "why are 32 bit floats not enough for godot collisions to work, but fine for 32 bit engines like the source engine?". I theorized that perhaps this is because the source engine deals in hammer units which are ~52 times godot's units (meters), so it doesn't need to deal with decimals that much and can handle collisions at a much more comfortable scale for 32 bit floats.

[Here](https://youtu.be/UZQPBNdbSdI) is a video explaining my findings. This issue can be closed because it can be worked around by making the engine use 64 bit floats, but I think the engine should try to imitate how the source engine handles units for physics. That way, you could still make 32 bit apps in Godot.

**Comment by Zireael07** [comment]
@Gamepro5: Counter argument: many engines work fine in 32 bit and have the same scale as Godot (meters). 500 units is very much within the realm of 32 bit, so while 64 bit may be a workaround, it's wasting RAM for no real reason

**Comment by Gamepro5** [comment]
These precision errors happen at all Y levels. Triple digits should still be fine, but they are not.

**Comment by Gamepro5** [comment]
As of Godot Beta 14 (presumably because of https://github.com/godotengine/godot/pull/71447), this bug has been fixed! 🎉
