### ISSUE TITLE
Tilemap displacement

### ISSUE THREAD

**Issue by Cheville** [godotengine/godot#67683]
### Godot version

3.5 stable

### System information

Windows 10, GLE3

### Issue description

When porting my tilemap from 3.5 to 4.0, the tile hitboxes were displaced down and right by seemingly either half their tile size or half their hitbox side, causing my entire scene to be displaced by essentially half a tile.

### Steps to reproduce

- Create tilemap in Godot 3.5
- Make it 16x16
- Scale by 4
- Add hitboxes to tiles
- Save project
- Scan for project in 4.0 Beta 3
- Convert to 4.0
- Check tilemap
- All hitboxes displaced

**Comment by Sauermann** [comment]
sounds similar to #67601
