### ISSUE TITLE
Text editor overlaps dialogs if function hints are being displayed

### ISSUE THREAD

**Issue by hetdegon** [godotengine/godot#6769]
**Operating system or device - Godot version:**
Ubuntu 16.04 64b, Godot fea1fb0925142c3279fd3afaf27e80e78cd2e1e8

**Issue description** (what happened, and what was expected):
One image speaks a thousand words:
![snapshot14](https://cloud.githubusercontent.com/assets/323651/19226106/f1be2ada-8ea6-11e6-8efd-bd67069f7333.png)
It might be related to commit 9eb54e5b6e89b51fb3287de3b89f009109242bad ?

**Steps to reproduce:**
Only seems to happen in the scenario shown in the screenshot, where some function hint is being displayed and a dialog is opened.

**Comment by Hinsbart** [comment]
It's indeed caused by #6716. I was worried that something like this might happen, but couldn't find a case where it does.
So we need to find a better solution.

**Comment by akien-mga** [comment]
Damn, how come I missed this commit for 2.1? :/
