### ISSUE TITLE
Sprite3D not rendering in the gl_compatibility renderer.

### ISSUE THREAD

**Issue by shared67** [godotengine/godot#67700]
### Godot version

4.0 beta 3

### System information

Windows 10, gl_compatibility renderer

### Issue description

Sprite3Ds do not seem to render using the gl_compatibility renderer, in both editor and exported games.

Here is one test scene in the forward_plus renderer:
![unknown1](https://user-images.githubusercontent.com/87948590/197120113-33ac0b80-29f2-4065-802d-2f6199aa8e2d.png)

And here is the same scene in the gl_compatibility renderer:
![unknown](https://user-images.githubusercontent.com/87948590/197120226-e237e49f-cdde-4cdf-96b5-4143baea63e1.png)

### Steps to reproduce

Add a Sprite3D node and add a texture to it.
Change the rendering method in the project settings to gl_compatibility

**Comment by clayjohn** [comment]
The root cause of this is that ``mesh_surface_update_vertex_region()`` and ``mesh_surface_update_attribute_region()`` haven't been implemented yet. It should be quick to add

```
void MeshStorage::mesh_surface_update_vertex_region(RID p_mesh, int p_surface, int p_offset, const Vector<uint8_t> &p_data) {
}

void MeshStorage::mesh_surface_update_attribute_region(RID p_mesh, int p_surface, int p_offset, const Vector<uint8_t> &p_data) {
}
```
