### ISSUE TITLE
Sprite2D repeat broken

### ISSUE THREAD

**Issue by dmaz** [godotengine/godot#67721]
### Godot version

v4.0.beta.custom_build [28a4eec9a]

### System information

windows 10

### Issue description

Texture/Repeat seems to be broken for Sprite2D.   TextureRect too except that Stretch Mode can be set to Tile and that works.

### Steps to reproduce

drag a png to the canvas and resize the sprite to larger than image.  set Texture/Repeat to Enabled and see that nothing changes in the editor or on run

**Comment by KoBeWi** [comment]
Repeat affect the Sprite's region. If you resize it in the editor, you are scaling it.

**Comment by dmaz** [comment]
dang... my bad.   setting region makes it work perfectly!
