### ISSUE TITLE
Setting initial window mode to "Minimized" or "Maximized" produces errors

### ISSUE THREAD

**Issue by vpellen** [godotengine/godot#67724]
### Godot version

v4.0.beta3.official [01ae26d31]

### System information

Windows 10, Vulkan

### Issue description

Setting the project variable `display/window/size/mode` to `minimized` or `maximized` spits out errors on run.

For maximized, you get a single error:
```
E 0:00:00:0162   window_resize: Condition "!windows.has(p_window)" is true.
  <C++ Source>   drivers/vulkan/vulkan_context.cpp:1601 @ window_resize()
```
For minimized, you get several:
```
E 0:00:00:0687   draw_list_bind_render_pipeline: Condition "!dl" is true.
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:7564 @ draw_list_bind_render_pipeline()
E 0:00:00:0688   draw_list_bind_index_array: Condition "!dl" is true.
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:7711 @ draw_list_bind_index_array()
E 0:00:00:0688   draw_list_bind_uniform_set: Condition "!dl" is true.
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:7638 @ draw_list_bind_uniform_set()
E 0:00:00:0688   draw_list_set_push_constant: Condition "!dl" is true.
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:7745 @ draw_list_set_push_constant()
E 0:00:00:0688   draw_list_draw: Condition "!dl" is true.
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:7763 @ draw_list_draw()
E 0:00:00:0688   draw_list_end: Immediate draw list is already inactive.
  <C++ Error>    Condition "!draw_list" is true.
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:8066 @ draw_list_end()
```

These errors don't seem to have any immediate negative impact, and the window even loads in the correct state, but it's still mildly irritating. Doesn't seem to affect the other window modes. May cause other issues on the OpenGL implementations, not sure, didn't test. Also unsure if it causes issues with an exported project. Setting the mode manually after launch doesn't seem to produce any errors.

Probably just some fairly innocuous initialization order issue.

### Steps to reproduce

Create a new vulkan project, set the starting window size mode to minimized or maximized, run.

**Comment by lmurray** [comment]
Maximized error should be fixed by #67539. Minimized will need further investigation but might be similar in nature.

**Comment by vpellen** [comment]
Maximized error is fixed, minimized errors persist as of Beta 17.

**Comment by Delocop** [comment]
Had the same issue on 4.0.3-stable

OS : windows 10
GPU : Nvidia GTX 1650

**Comment by vpellen** [comment]
Got fixed at some point, couldn't say when.
