### ISSUE TITLE
GDScript 2.0: ProjectSettings `_property_can_revert` and `_property_get_revert`

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#67720]
### Godot version

v4.0.beta3.official [01ae26d31]

### System information

Windows 10

### Issue description

I want to use `_property_can_revert` and `_property_get_revert` from ProjectSettings to restore default values.

The functions throw an error at runtime.

`Invalid call. Nonexistent function '_property_can_revert' in base 'ProjectSettings'.`

### Steps to reproduce

Run this code:

```

func _ready():
	ProjectSettings._property_can_revert("abc")
	ProjectSettings._property_get_revert("abc")
```

**Comment by KoBeWi** [comment]
These methods are virtual. You shouldn't be calling them.

**Comment by MikeSchulze** [comment]
but `property_get_revert` is removed and was proposed in https://github.com/godotengine/godot/issues/66900
So than https://github.com/godotengine/godot/issues/66900 should be reopend

**Comment by KoBeWi** [comment]
> use _property_can_revert was proposed

Well, you still can't call it directly. So I think we might need a new method that returns a default value.
(by can't I mean you shouldn't; not sure why the method can't be called)

**Comment by MikeSchulze** [comment]
hi @KoBeWi so please bring back the removed functions ;)

**Comment by atngames** [comment]
What I did was:
In the class that has the property "abc", I implemented:
`func _property_can_revert(property):
	if property == "abc":
		return true
	return false`

As a side note, those functions seem to call the parent functions without the need to call super() (Which I personnally find a bit annoying)

**Comment by MikeSchulze** [comment]
@atngames that not help, you just implement your own default function.
I have a lot of properties with default values, i don't want to rebuild existing code from Godot3!

You can just set default values of a property by `ProjectSettings.set_initial_value(name, default)`
So i want back to have `ProjectSettings.property_get_revert(name)` (Godot3)
To be consistent with the naming it should be named `ProjectSettings.get_initial_value(name)`

**Comment by atngames** [comment]
Ok i did not get it. I use it to change there behaviors of properties through overriding _get_property_list()
Good luck

**Comment by MikeSchulze** [comment]
Close, is now located in Objects
`Variant property_get_revert(property: StringName) const`
`bool property_can_revert(property: StringName) const`
