### ISSUE TITLE
Undoing a change in a texture region won't reflect in the region editor.

### ISSUE THREAD

**Issue by hetdegon** [godotengine/godot#6772]
**Operating system or device - Godot version:**
Ubuntu Linux 16.04, Godot version fea1fb0925142c3279fd3afaf27e80e78cd2e1e8

**Issue description** (what happened, and what was expected):
Changing a texture region and then undoing it won't change the selection rectangle. Closing and opening the region editor again or changing to other tools in the bottom dock (animation editor/debugger/output) won't reflect the change as well. Only changing to another scene and back will show the change.
This could be misleading as it makes it seem like region changes aren't being undone unless one is aware of this bug.

**Steps to reproduce:**
Open a texture region editor and click somewhere to change the current region, then undo. Change to other tools in the bottom dock and back and it will still show the changes before undo. Change to another scene and return to the one with the undone region, now it refreshes properly.

**Comment by hetdegon** [comment]
@Hinsbart Looks like it's still happening after updating. 
![snapshot14](https://cloud.githubusercontent.com/assets/323651/19289405/ed162252-900a-11e6-9b48-6bd53e2cd910.png)

I include a video as demonstration (which also showcases a strange issue where apparently scene changes count towards undo buffer, I'll open a separate issue for it).
[http://kuuv.io/i/EXxge2s.mp4](http://kuuv.io/i/EXxge2s.mp4)

**Comment by Hinsbart** [comment]
@hetdegon mhh, I can't reproduce this anymore.
And it looks like I'm doing the same as in your video: make changes to the region then press ctrl+z..
Will investigate this further.

**Comment by hetdegon** [comment]
Strange. If there's anything I can do to help, please let me know.
