### ISSUE TITLE
[4.0, Mono] Disabling CollisionShape2D not working

### ISSUE THREAD

**Issue by josiahdbarbieri** [godotengine/godot#67731]
### Godot version

4.0.beta3.mono

### System information

Arch Linux

### Issue description

I am having issues disabling a collision shape. Whenever I run `GetNode<CollisionShape2D>("CollisionShape2D").Disabled = true;`, which should disable the collision, I get the following error.

```
E 0:00:06:0920   Godot.NativeInterop.godot_bool Godot.Bridge.CSharpInstanceBridge.Call(IntPtr , Godot.NativeInterop.godot_string_name* , Godot.NativeInterop.godot_variant** , Int32 , Godot.NativeInterop.godot_variant_call_error* , Godot.NativeInterop.godot_variant* ): Can't change this state while flushing queries. Use call_deferred() or set_deferred() to change monitoring state instead.
  <C++ Error>    Condition "body->get_space() && flushing_queries" is true.
  <C++ Source>   servers/physics_2d/godot_physics_server_2d.cpp:654 @ body_set_shape_disabled()
  <Stack Trace>  Godot.NativeInterop.NativeFuncs.generated.cs:324 @ void Godot.NativeInterop.NativeFuncs.godotsharp_method_bind_ptrcall(IntPtr , IntPtr , System.Void** , System.Void* )()
                 NativeCalls.cs:308 @ void Godot.NativeCalls.godot_icall_1_34(IntPtr , IntPtr , Godot.NativeInterop.godot_bool )()
                 CollisionShape2D.cs:155 @ void Godot.CollisionShape2D.SetDisabled(Boolean )()
                 CollisionShape2D.cs:50 @ void Godot.CollisionShape2D.set_Disabled(Boolean )()
                 Enemy.cs:30 @ void Enemy.kill()()
                 Enemy.cs:37 @ void Enemy._on_head_body_entered(Godot.Node2D )()
                 Enemy_ScriptMethods_Generated.cs:41 @ Boolean Enemy.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name& , Godot.NativeInterop.NativeVariantPtrArgs , Int32 , Godot.NativeInterop.godot_variant& )()
                 CSharpInstanceBridge.cs:24 @ Godot.NativeInterop.godot_bool Godot.Bridge.CSharpInstanceBridge.Call(IntPtr , Godot.NativeInterop.godot_string_name* , Godot.NativeInterop.godot_variant** , Int32 , Godot.NativeInterop.godot_variant_call_error* , Godot.NativeInterop.godot_variant* )()
```

### Steps to reproduce

[I found a video posted 2 years ago that explains my issue well.](https://youtu.be/pUc6AVgBkzQ)

The Code I Used:
![image](https://user-images.githubusercontent.com/51347472/197297046-1b682284-d714-4723-9798-4149c04752e6.png)

The Code In The Minimal Example:
![image](https://user-images.githubusercontent.com/51347472/197299919-1080f0cd-b873-4198-aa1e-c159f84eca9c.png)

### Minimal reproduction project

In [this example](https://github.com/godotengine/godot/files/9842899/GodotIssue.zip), the godot icon should fall off the screen.

**Comment by Calinou** [comment]
As the error message says: 

> Can't change this state while flushing queries. Use call_deferred() or set_deferred() to change monitoring state instead.
  <C++ Error>    Condition "body->get_space() && flushing_queries" is true.


You need to use the equivalent of `set_deferred("disabled", true)` in C# instead of setting the `disabled` property directly.

**Comment by josiahdbarbieri** [comment]
what does it mean? and why do I have to do it that way?

**Comment by Calinou** [comment]
> what does it mean? and why do I have to do it that way?

`set_deferred()` sets the variable's value with a 1-frame delay. This is required due to internal physics engine limitations.
