### ISSUE TITLE
NoiseTexture2D Image Data Size Doesn't Match Image Size

### ISSUE THREAD

**Issue by iiMidknightii** [godotengine/godot#67734]
### Godot version

4.0.dev

### System information

Windows 10, Vulkan, GTX 1080ti

### Issue description

After creating a NoiseTexture2D and converting to an Image using get_image(), when calling get_data() the returned PackedFloat32Array size doesn't correspond with the original image size.  For instance, if the original image was 128x128, I would expect the returned data array to be 16384 bytes on its own, or 65536 bytes if the image is converted to FORMAT_RF.  Instead, I'm getting a weird number like 21845 or 87380 in RF format.

This directly interferes with using HeightmapShape2D, as the resource wants a plain PackedFloat32Array to determine vertex heights.  If I set the width and depth of the shape to match the image (and thus match the size of my terrain as well), then the returned data from the image is too large for the shape's data and it silently fails, leaving all the heights at 0.

### Steps to reproduce

Open the included project and run the ConvertImageToRaw scene.  It will print the image size, an unconverted byte count, then convert it to FORMAT_RF and print that pixel count.  None of the byte counts match the number of pixels in the image when factoring for type conversions.

### Minimal reproduction project

[Uploading Image_Data_Size_Test.zip…]()

**Comment by iiMidknightii** [comment]
A followup after doing some digging.  It appears to be tied to generating mipmaps.  If an image is imported (or noise generated) with "generate mipmaps" enabled, the Image object data includes the mipmap data as well.  At least I think.  This is very opaque to end users like me so it's really confusing when the Image I imported has different sized data than expected without any warning.

**Comment by clayjohn** [comment]
This is expected, the ``get_data()`` function returns the image's data which includes mipmaps if you have generated mipmaps (NoiseTexture generates mipmaps by default. you can turn that off by unchecking "generate mipmaps").

The [Image docs](https://docs.godotengine.org/en/latest/classes/class_image.html#properties) have a good explanation of what ``get_data()`` returns.

Closing as solved by user.
