### ISSUE TITLE
Could not create folder. File with that name already exist

### ISSUE THREAD

**Issue by nongvantinh** [godotengine/godot#67738]
### Godot version

4.0 dev (72b845b)

### System information

Windows 10

### Issue description

Can not create a folder with a name slightly different from the existing one.
`core` --> `Core` ==> `Could not create folder. File with that name already exist`
![Capture](https://user-images.githubusercontent.com/53887662/197309601-4d48ea48-8e45-4784-9bd0-b038320f4920.PNG)
![1Capture](https://user-images.githubusercontent.com/53887662/197309603-6acc589d-7e34-447b-889a-ae61eeb183cb.PNG)

### Steps to reproduce

1. Create empty project
2. Create a folder named `core`
3. Create a folder named `Core`
4. Warning/Prevent: `Could not create folder. File with that name already exist`

**Comment by reynarzz** [comment]
Hi, this is a windows thing, if you try to do the same outside Godot you will get a message like this one below.
![image](https://user-images.githubusercontent.com/56844500/197310141-f24c0929-d7aa-40a6-9bf1-d49f1a1d8d49.png)

**Comment by KoBeWi** [comment]
Yeah this is a problem with case-insensitive filesystems (mostly Windows). It's not something that can be fixed.
