### ISSUE TITLE
[4.0] Crash on .blend import with bone map (CowData)

### ISSUE THREAD

**Issue by Flynsarmy** [godotengine/godot#67733]
### Godot version

v4.0.beta3.official

### System information

Windows 10, NVIDIA - NVIDIA GeForce RTX 3070 Ti, Blender 3.3.1

### Issue description

When importing specific blend, FBX or GLTF files with a custom bone map, Godot crashes.

### Steps to reproduce

1. Download Quaternius Ultimate Modular Men Pack from https://quaternius.com/packs/ultimatemodularcharacters.html
2. Drop *All together\Blends\Humans_Master.blend* or *Individual Characters\glTF\Adventurer.gltf* into your project
3. Double click it int he FileSystem tree
4. Click 'Skeleton3D' on the left, then on the right create a new BoneMap, click on it, under Profile create a new SkeletonProfileHumanoid
5. Hit Reimport

Godot will crash. I have Blender 3 Path set up correctly in *FileSystem - Import* and I can successfully import other models complete with bone maps using the above steps. It's just this particular blend file causing crashes.

### Minimal reproduction project

Empty Godot project with just the .blend and .fbx files inside:
[BoneMapTest-2.zip](https://github.com/godotengine/godot/files/9843083/BoneMapTest-2.zip)

UPDATE: It also crashes with this GLTF file of a single character:
[Adventurer.zip](https://github.com/godotengine/godot/files/9843669/Adventurer.zip)

**Comment by Flynsarmy** [comment]
The crash actually also happens importing FBX (I have fbx2GLTF set up correctly). Perhaps this isn't an issue with the .blend file, but an issue with Godot trying to import multiple outfits at once? I've updated the zip file linked in the issue above.

**Comment by Flynsarmy** [comment]
I ran Godot from terminal to see if I could see any errors before the crash. Here's what was logged:
![image](https://user-images.githubusercontent.com/334808/197323826-2b306e0b-6e01-4469-919b-df63fed0e38f.png)

**Comment by fire** [comment]
The p_index is not between 0 and 62. That's a significant clue.

**Comment by Flynsarmy** [comment]
@Calinou WRT your title change, the crash also happens on FBX and GLTF imports, not just blend files. I've included one of all 3 file types in my issue description that can replicate the problem.

**Comment by fire** [comment]
I can confirm that the skeleton doesn't seem to rig the mesh for at least the GLTF and the blend imports.

**Comment by TokageItLab** [comment]
Closed by #68725
