### ISSUE TITLE
GDScript 2.0: Autocomplete doesn't work for function until restarting the editor

### ISSUE THREAD

**Issue by nofacer** [godotengine/godot#67740]
### Godot version

4.0 beta3

### System information

macos 12.6

### Issue description

I've a custom class in addon folder. It has a func named with fetch_class_name. The auto-complete for this func not show up. After I close the IDE and reopen then it works as expected.

### Steps to reproduce

Create gd script in `res://addons/fsm/state.gd`
```gdscript
extends Node
class_name State
@icon("res://addons/fsm/state_logo.svg")

var state_machine: StateMachine
var target

static func fetch_class_name() -> String:
	return "State"
	

func enter() -> void:
	print(666)


func update():
	pass


func exit():
	pass

```

In another script `res://addons/fsm/state_machine.gd`

```gdscript
extends Node
class_name StateMachine
@icon("res://addons/fsm/state_machine_logo.svg")

@export var init_state = NodePath()
@onready var _target_node: Node = get_parent() as Node
@onready var _states: Array[State] = []


var cur_state: State 
var _states_map: Dictionary = {}

func _ready():
	for child in get_children():
		if child.get_class() == State.fetch_class_name():
			_states.append(child)
	for state in _states:
		state.target = get_parent()
		state.state_machine = self
		_states_map[state.name] = state
	cur_state = get_node(init_state) as State
	cur_state.enter()


func _process(delta):
	pass

```
The auto completion doesn't work for `State.fetch_class_name()` and `cur_state.enter()`

Then close the IDE and reopen it.

It will work as expected

**Comment by Calinou** [comment]
> Then close the IDE and reopen it.

To clarify, are you using the built-in script editor or an external editor?

**Comment by nofacer** [comment]
> 

I'm using built-in script editor.

**Comment by Nickelvad** [comment]
Happens on v4.2.beta5 as well, using built-in editor.

**Comment by Jules5** [comment]
Still happening on v4.2, this is a bit annoying.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/78074, as this is due to the same cause (cyclic reference).
