### ISSUE TITLE
Debanding not working for framebuffer allocation = 2D

### ISSUE THREAD

**Issue by belzecue** [godotengine/godot#67748]
### Godot version

3.5.1-stable.official

### System information

Linux, GLES3, Intel Integrated GPU

### Issue description

The Project Settings "framebuffer allocation" property hint says:

![Clipboard 1](https://user-images.githubusercontent.com/1931303/197334761-403fc241-fb85-4e82-b268-009eb1a0ec31.png)

So, as I undestand it, DEBANDING should work for either a value here of 3D or 2D.  I can confirm that debanding is active when I set Framebuffer Allocation to '3D', but when I switch it to '2D' it is not active, as demonstrated in the video below, where you can see a smooth fade-up on the moon when set to 3D but banding appear when Framebuffer Allocation is set to 2D.  Watch the bottom of the moon in both examples.

https://user-images.githubusercontent.com/1931303/197334677-a7ec6482-7f7a-4e89-8a5c-613a895ee28d.mp4

### Steps to reproduce

Grab any greyscale texture with a wide grey range (dark to light), such as an high quality texture of the moon, slap it on a quad and add a tween to fade up from black.

First try it with the framebuffer property set to "3D" to confirm you get a smooth fade up with no banding.
Next switch over to framebuffer allocation = "2D" and run the scene again, watching for any banding.

### Minimal reproduction project

Once I get confirmation that debanding _should_ be active when framebuffer allocation = 2D then I'll upload a simple MRP.

**Comment by Calinou** [comment]
Debanding only affects 3D rendering, not 2D rendering.

**Comment by belzecue** [comment]
Thank for the info.  I suspected that might be the case.  Yes, I'm using a custom shader and have debanding code ready to use in the alternative.  And yes, I'm using Canvas environment background, which is providing glow but not the debanding when framebuffer allocation is set to 2D.  No problem leaving allocation set to 3D, other than losing a couple frames of performance.

I feel the documentation needs to make this much clearer and I'll look into submitting a doco patch to do so -- unless a deeper dive shows that it is actually mentioned somewhere.
