### ISSUE TITLE
Generated C# code is not annotated as such.

### ISSUE THREAD

**Issue by RobTF** [godotengine/godot#67758]
### Godot version

4.0 beta 3

### System information

Windows 11, Visual Studio 2022

### Issue description

On our team we use StyleCop to enforce code styles. The generated C# code is picked up by StyleCop resulting in errors;

![image](https://user-images.githubusercontent.com/4292237/197352235-25f041d9-fa9b-4777-bb3e-24ad68cc8332.png)

The code should have an appropriate marker indicating it is generated code and will therefore be skipped by code analysis tools, e.g. by adding `// <auto-generated />` to the top of each generated source file.

### Steps to reproduce

- Create a new GoDot project using C#.
- Install the `StyleCop.Analyzers` package.
- Note errors reported in files ending with `_Generated.cs`.

**Comment by raulsntos** [comment]
A file is considered generated by .NET if it has a `// <auto-generated />` comment as the first line of the file, or if the file name ends with one of these suffixes: `.designer`, `.generated`, `.g` or `.g.i`. I don't know why we are using the `_Generated` suffix, I feel like the `.generated` suffix is equally descriptive and should work for letting .NET know it's a generated file.

As a workaround in the meantime, you might be able to disable the analyzers for the generated files by adding this configuration to your `.editorconfig`:

```toml
[*_Generated.cs]
generated_code = true
```

**Comment by RobTF** [comment]
Fantastic response, thanks guys!
