### ISSUE TITLE
GDScript 2.0: Extending an inner class results in invalid constructor resolution at runtime

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#67753]
### Godot version

v4.0.beta3.official [01ae26d31]

### System information

Windows 10

### Issue description

I run into this issue during my plugin migration form Godot3 to Godot4
My mocker implementation allows to mock inner classes and used default arguemts to construct it.

With Godot 4 it is broken and the construction fails by an error:
**`Invalid call to function '_init'. Expected 0 arguments.`**
But the construcor is correct called with all needed arguments

### Steps to reproduce

create a simple scene and add this code

```
class_name TestScene
extends Node

class SmokyAtmosphereData extends ExampleClass.AtmosphereData:
	
	func _init():
		super._init(SMOKY, 1.1)

func _ready():
	ExampleClass.AtmosphereData.new()
	SmokyAtmosphereData.new()
``` 

The `ExampleClass` code
```
class_name ExampleClass
extends Resource

class AtmosphereData:
	enum {
		WATER,
		AIR,
		SMOKY,
	}
	
	func _init(type := AIR, toxigen := 0.0):
		prints("AtmosphereData", type, toxigen)

func _init():
	pass
```

Run it
![image](https://user-images.githubusercontent.com/347037/197343506-b1f66072-7c99-4cd6-9e27-3c8767a9d529.png)

**Apparently the constructor of the 'ExampleClass' class is used instead of the constructor of the inner class.**
If you comment the construcor of the 'ExampleClass' out, the code is running

This is a critical bug in my eyes.

**Comment by rune-scape** [comment]
@akien-mga i just tested that this is fixed as of https://github.com/godotengine/godot/pull/68374
