### ISSUE TITLE
Floor not detected and movement is glitchy

### ISSUE THREAD

**Issue by Coder2195Text** [godotengine/godot#67757]
### Godot version

Godot 4 Beta 3

### System information

Ubuntu 22.04 Running on Vulkan Mesa Intel® UHD Graphics 620 (WHL GT2)

### Issue description

So back in Godot 3, I also had a similar issue. All I did was to add Vector2.UP to the 2nd param of MoveAndSlide()

Now in Godot 4, there is no parameters for MoveAndSlide()

Jump doesn't work as an result of this. 

Also, the movement just stops after you try to move around for a bit; I think its when u change direction of movement on the ground

### Steps to reproduce

Clone https://github.com/coder2195text/tile-craft

Set a breakpoint at Scripts/GameScene/Player.cs at line 31.

Play the game.

When you press jump, something like this should appear
![image](https://user-images.githubusercontent.com/63069499/197348176-503a3579-9c2e-4213-92a2-1ea414dca557.png)

For the movement testing, let the player touch the ground, move left then move right.

**Comment by Calinou** [comment]
The project linked is not a minimal reproduction project.

Please create a minimal reproduction project in GDScript instead of C# for two reasons:

- Non-Mono builds of Godot are easier to set up and have less moving parts.
- This rules out C# being the cause of the bug.

**Comment by Coder2195Text** [comment]
> The project linked is not a minimal reproduction project.
> 
> Please create a minimal reproduction project in GDScript instead of C# for two reasons:
> 
> * Non-Mono builds of Godot are easier to set up and have less moving parts.
> * This rules out C# being the cause of the bug.

While doing this, I found something else
Creating a new project gives me these attrs for CharacterBody2d
![image](https://user-images.githubusercontent.com/63069499/197366728-6bd78fc1-340d-4126-b776-414734da3459.png)
Transfering one apparently glitches it out cuz up direction doesnt exist
![image](https://user-images.githubusercontent.com/63069499/197366741-47ca53eb-cfcc-4b72-b740-dd826c5d4139.png)

Moving left stops the sprite like touching wall, but moving right doesn't do that
Reproduction project
[sadssdad.zip](https://github.com/godotengine/godot/files/9845478/sadssdad.zip)

**Comment by Coder2195Text** [comment]
Apparently everything works now because I changed floating mode to grounded mode
