### ISSUE TITLE
get_tree().change_scene problem

### ISSUE THREAD

**Issue by demmixes** [godotengine/godot#67761]
### Godot version

3.5.stable

### System information

Windows 10

### Issue description

every time i input the change_scene signal in my script and i play the game, my game will always crash and fizzle. How do i fix it?

### Steps to reproduce

get_tree(). change scene in a godot script

### Minimal reproduction project

i dont understand please help

**Comment by KoBeWi** [comment]
> i dont understand please help

Minimal reproduction project is a Godot project with enough files to reproduce the bug. E.g. if a bug in your project is caused by specific script, MRP will contain only this script and some empty `project.godot` (although attaching only script is ok too).

The issue does not have enough details.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
