### ISSUE TITLE
MultiplayerSynchronizer only synchronizes the earliest client connected when the Replication Interval is set to anything above 0

### ISSUE THREAD

**Issue by Yohnny** [godotengine/godot#67765]
### Godot version

4.0.beta3.official

### System information

Windows 10 x64 Intel

### Issue description

When using a MultiplayerSynchronizer it will only synchronize the earliest connected client if the Replication Interval is set to anything above 0.

### Steps to reproduce

Run the included minimal reproduction project. In one of the instances click the "host" button, on the other instances click the "join" button. The number in the top left signifies the order of connection, the host is 0, the first connected client is 1, and so on. The counter above the center of the screen will only synchronize for the host and the first connected client. Click the "change replication interval" button, now the counter will synchronize for the host all clients. Click the "change replication interval" button again, the counter will only synchronize for the host and the first connected client. Close the first connected client, the counter will synchronize for the host and the second connected client. Close the second connected client, the counter will synchronize for the host and the third connected client.

### Minimal reproduction project

[minimal example.zip](https://github.com/godotengine/godot/files/9845227/minimal.example.zip)

**Comment by MrBlockers** [comment]
I ran into this issue as well in a personal project recently, it's very strange.

Minimal example reproduces the issue on master [56fa8f1d58efd62f941e9fd94f6c3e156a8b7a6b]

**Comment by kdada** [comment]
Actually it's a bug. I found the reason of it.

`SceneReplicationInterface::on_network_process` calls `SceneReplicationInterface::_send_sync` for every peer. Then `SceneReplicationInterface::_send_sync` calls `MultiplayerSynchronizer::update_outbound_sync_time` for every synchronizer.

`MultiplayerSynchronizer::update_outbound_sync_time`` update `MultiplayerSynchronizer::last_sync_msec`. It returns true at first time and returns false otherwize. So only the first peer can receive the message.

I'll create an PR for this problem.

for testing, you can change the `update_outbound_sync_time` method to:
```c++
bool MultiplayerSynchronizer::update_outbound_sync_time(uint64_t p_msec) {
	if (last_sync_msec == p_msec || p_msec >= last_sync_msec + interval_msec) {
		last_sync_msec = p_msec;
		return true;
	}
	return false;
}
```

**Comment by Faless** [comment]
Confirmed regression from #66794.
