### ISSUE TITLE
Tile pick button sometimes unavailable in TileSet painting mode

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#67769]
### Godot version

4.0 0b627c4

### System information

Windows 10 x64

### Issue description

![godot_K7xoRqRy9R](https://user-images.githubusercontent.com/2223172/197365175-6b670ec4-6b03-49d8-8489-4a0605b2e921.gif)
Notice how the pick button (on the right) disappears when changing between atlas setup and painting. Changing to a different atlas source fixes the issue.

### Steps to reproduce

1. Have a TileSet
2. Go to tile property painting mode (e.g. for collision shapes)
3. The pick button is not there sometimes

**Comment by groud** [comment]
Can't reproduce the bug on latest master. Can you confirm it is fixed ?

**Comment by KoBeWi** [comment]
Seems fixed.
