### ISSUE TITLE
[v4.0 Beta 2] - Gamepad Controllers Do Not Work On HTML5 Builds?

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#67778]
### Godot version

v4.0.beta2.official [f8745f2f7]

### System information

Windows 11 Pro 64Bit / Linux Mint 21 Cinnamon / Windows 10 Pro 64Bit

### Issue description

Hi,

HTML5 does support gamepad controllers on at least Mozilla Firefox and Google Chrome Internet browsers.
Can you please add gamepad controller support to HTML5 builds?

Thanks!

Jesse

### Steps to reproduce

You can download our project below on GitHub:
https://github.com/BetaMaxHero/GDScript_Godot_4_T-Story

**Comment by FarbrorMartin** [comment]
In 3.x you needed to click a key or the mouse in the HTML5 window to get controller events to work. I believe it's something related to how the browser handles the running assembly.
Is this the same problem, or something else that has appeared in 4.0?

**Comment by akien-mga** [comment]
Can you test again in 4.0 RC 6 or later, and confirm whether it works or not after following @FarbrorMartin's advice? Last I checked my Xbox controller worked fine in both Firefox and Chromium on Linux.

**Comment by YuriSizov** [comment]
Closing due to the lack of response and additional confirmations.
