### ISSUE TITLE
Animations do not import correctly into Godot 4.0 'cyclic dependency'

### ISSUE THREAD

**Issue by prominentdetail** [godotengine/godot#67773]
### Godot version

v4.0.beta.custom_build [7fe2f25ef]

### System information

Windows 10

### Issue description

I am running into a bug with the gltf importer in Godot 4.0.
It isn't properly importing the models. I've attached two example .gltf files:

godotTest01.gltf
godotTest01_b.gltf

Download: [godotTest01.zip](https://github.com/godotengine/godot/files/9845479/godotTest01.zip)

These files have been run through the Gltf Validator: https://github.khronos.org/glTF-Validator/ and they are both valid files.

When adding godotTest01.gltf to project, these errors appear in console:
```
  Can't add child 'part2' to 'Skeleton3D' as it would result in a cyclic dependency since 'part2' is already a parent of 'Skeleton3D'.
  scene\main\node.cpp:1609 - Condition "!owner_valid" is true.
```

This is how it should look (viewed in Window's 3d viewer):

![screenshot01](https://user-images.githubusercontent.com/10412778/197366695-8b1f0ec1-e584-4587-932b-4c84d3a243c0.png)

This is how it looks in Godot 4.0 ( it is missing part2, which should be a child of part1 ):

![godot_screenshot01](https://user-images.githubusercontent.com/10412778/197366722-694f08e9-3fd9-49cd-a67e-7ace445d738a.png)

When adding godotTest01_b.gltf to project, these errors appear in console:
```
  Can't add child 'part2' to 'Skeleton3D' as it would result in a cyclic dependency since 'part2' is already a parent of 'Skeleton3D'.
  scene\main\node.cpp:1609 - Condition "!owner_valid" is true.
  scene\main\node.cpp:1677 - Condition "!common_parent" is true. Returning: NodePath()
  scene\main\node.cpp:1677 - Condition "!common_parent" is true. Returning: NodePath()
  scene\main\node.cpp:1677 - Condition "!common_parent" is true. Returning: NodePath()
  scene\main\node.cpp:1677 - Condition "!common_parent" is true. Returning: NodePath()
  scene\main\node.cpp:1677 - Condition "!common_parent" is true. Returning: NodePath()
  scene\main\node.cpp:1677 - Condition "!common_parent" is true. Returning: NodePath()
```

This is how it should look & animate (viewed in Window's 3d viewer):

![screenshot_b](https://user-images.githubusercontent.com/10412778/197366544-39bd1eb3-5633-42b0-b693-dc56323680b7.gif)

This is how it looks in Godot 4.0 ( it is missing part2, which should be a child of part1 ):

![godot_screenshot_b](https://user-images.githubusercontent.com/10412778/197366653-f3fdb87e-735c-4b9b-9efb-648b9b006bff.gif)

Notes:

godotTest01.gltf consists of a mesh that has a child that is a skinned mesh. The skinned mesh has no animation.
godotTest01_b.gltf consists of a mesh that has a child that is a skinned mesh. The skinned mesh has bones that are animated.

### Steps to reproduce

Download example files and try importing them.

**Comment by fire** [comment]
I can confirm that this bug exists.

**Comment by fire** [comment]
MRP: [gltf skeleton multi-parent.zip](https://github.com/godotengine/godot/files/10366665/gltf.skeleton.multi-parent.zip)

**Comment by fire** [comment]
We fixed this in https://github.com/godotengine/godot/pull/72158. Please check.

**Comment by prominentdetail** [comment]
> We fixed this in #72158. Please check in beta 16.

I just compiled from the latest, and it looks like it messes up the material texture.. Any idea why it looks different (it's importing the same gltf file as before)?
![image](https://user-images.githubusercontent.com/10412778/215147053-f250f859-13ac-4c2e-a0b5-50085c5fa59d.png)

**Comment by prominentdetail** [comment]
Seems like the gltf importer doesn't properly use the project import settings anymore. I guess it's a separate bug.

**Comment by lyuma** [comment]
yeah the texture is a separate issue. Thanks for filing that.

I'm going to close this issue as fixed. Please follow up further if you encounter more skeleton related issues (not visual /texture)
