### ISSUE TITLE
[v4.0 Beta 2] - HTML5 Builds - macOS Safari Internet Browser - Not Running?

### ISSUE THREAD

**Issue by BetaMaxHero** [godotengine/godot#67809]
### Godot version

v4.0.beta2.official [f8745f2f7]

### System information

Apple macOS Monterey v12.0.1 

### Issue description

Hi,

The HTML5 version of our Godot v4.0 Beta 2 game is not working on Apple macOS Safari Internet browser?
Running Apple macOS Monterey version 12.0.1

See screenshot below:

Any ideas?
Thanks!

Jesse

![Godot4_Beta2-HTML5_Safari_macOS_Not_Working-01](https://user-images.githubusercontent.com/109624581/197403211-de352985-d97f-4184-bb6c-058c55754fa0.png)

### Steps to reproduce

(1) Run HTML5 version of our Godot 4 game in Apple Safari Internet browser.

**Comment by Calinou** [comment]
As stated by the error message, the [web server needs to be configured accordingly to support WebAssembly threads](https://docs.godotengine.org/en/latest/tutorials/export/exporting_for_web.html#threads). Newgrounds doesn't seem to offer support for this (to my knowledge), so you'll have to use another host such as itch.io (which must be manually configured to do this).

**Comment by BetaMaxHero** [comment]
Hi,

We tried Itch.io first over a week ago - it does not work on any OS platform.

v4.0 Beta 2 HTML5 status:
- Windows 10/11 - Itch.io not working, NewGrounds.com working
- Linux - Itch.io not working, NewGrounds.com working
- macOS - Itch.io not working, NewGrounds.com not working

Hope this can be fixed...

Jesse
