### ISSUE TITLE
RigidBody3d going into or through CollisionShape3d

### ISSUE THREAD

**Issue by ThowV** [godotengine/godot#67817]
### Godot version

v4.0.beta2.mono.official

### System information

Windows 11, AMD Ryzen 5 3600 X, NVIDIA GeForce RTX 2060

### Issue description

So I have a RigidBody3d cube that moves using the `ApplyCentralForce` method inside the `_PhysicsProcess` function.

When the cube has a high enough velocity, or when the cube stands next to a wall it manages to go into the wall or sometimes even pass through it. I've looked up ways to potentially fix this issue, such as setting `Continuous Collision Detection` to enabled, but nothing has worked.

The cube obviously should not pass through the wall.

### Steps to reproduce

I have a small scene with a few CollisionShape3d nodes that have their shape set to BoxShape3d.
Next I've added a cube with a script that applies forces using the `ApplyCentralForce` method in the `_PhysicsProcess` function:

```csharp
public override void _PhysicsProcess(double delta)
{
    float input = Input.GetAxis("turn_left", "turn_right");
    ApplyTorque(Vector3.Up * input);

    // Apply movement force.
    Vector2 inputDir = Input.GetVector("move_left", "move_right", "move_forward", "move_back");
    Vector3 forceDirection = (Transform.basis * new Vector3(inputDir.x, 0, inputDir.y)).Normalized();

    ApplyCentralForce(forceDirection * THRUSTER_FORCE);
}
```

In the project settings I have under Physics - 3D I changed the following settings:

- Run On Seperate thread: On
- Default Linear Damp: 0

### Minimal reproduction project

You can find the project here: [collision-bug.zip](https://github.com/godotengine/godot/files/9847267/collision-bug.zip)
When running the game you can move around using `wasd` and rotate the cube using `q` or `e`

**Comment by Zireael07** [comment]
CCD not working is a longstanding issue.

What you are experiencing is known as tunneling

**Comment by rburing** [comment]
Can you please try it again in 4.0 RC 3? There have been fixes to CCD in the meantime. Also make sure to replace the `10 x 1 x 1` scale on the static bodies by `1 x 1 x 1` and set the `size` of the `BoxShape3D` resource (in the `shape` property of the `CollisionShape3D`) to `10 x 1 x 1` instead (as indicated by the warning which has also been added in the meantime).

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
