### ISSUE TITLE
Relative paths for shader include in 4.0 beta3 are not working

### ISSUE THREAD

**Issue by autofool** [godotengine/godot#67811]
### Godot version

4.0 beta 3

### System information

Arch Linux, Vulkan, NVidia gtx 1650ti

### Issue description

Relative paths for shader includes are not working. It only works for top level dir. (first dir after "res://" ) e.g. "res://top_dir". Then `#include top_dir/..` works. But let's say we have another dir inside top_level. e.g. `res://top_dir/second_dir/`. Then any includes with relative paths wont work, like: `#include second_dir/..`

### Steps to reproduce

Use shader include inside multi level directories.

### Minimal reproduction project

Open shader.gdshader for quick example.
[ShaderInc.zip](https://github.com/godotengine/godot/files/9847006/ShaderInc.zip)

**Comment by Calinou** [comment]
To my knowledge, support for relative paths in shader includes wasn't implemented yet.

**Comment by autofool** [comment]
I had my doubts that maybe it only works with absolute paths but since "top_dir/.." worked so I figured its a bug.
