### ISSUE TITLE
SubViewports are not rendering 3D scenes

### ISSUE THREAD

**Issue by RedNicStone** [godotengine/godot#67813]
### Godot version

v4.0.beta3.offical [01ae26d31]

### System information

Fedoar Linux [36] using the mesa [0x5801007] Vulkan [1.3.204] implementation

### Issue description

SubViewports are not able to render 3D scenes even if configured to do so while 2D scene render just fine.
It may appear to work fine in the editor while the built project does not.
This might relate to #16067 and others.

Here is a example scene of how this might look in the editor:
![Screenshot from 2022-10-23 17-42-44](https://user-images.githubusercontent.com/36967667/197404544-c83b2e2a-6273-408d-9204-a310da66bb59.png)
And in the build application:
![Screenshot from 2022-10-23 17-43-21](https://user-images.githubusercontent.com/36967667/197404572-7363eb92-935b-4ee4-b53b-77194ecd7ed2.png)

I've tried multiple workarounds such as using TextureRects and setting the texture at runtime with no success.

### Steps to reproduce

Create a SubViewport, a SubViewportContainer and a 3D scene to render. Configure the SubViewport to be able to render the scene.
The scene graph should look similar to this now:
![image](https://user-images.githubusercontent.com/36967667/197404225-c094ab66-c900-4d0a-a0e8-64c598aeca71.png)
Build the application and the SubViewportContainer object should have the default color.

### Minimal reproduction project

To big to upload here, download an MRE as [LZMA here](https://nextcloud.struktur.de/s/DtHAznimX4BKipY) or as [DEFLATE here](https://nextcloud.struktur.de/s/TXoBw4tBJ4qkbAJ).

**Comment by Calinou** [comment]
Is the viewport's update mode set to **Always**? See https://github.com/godotengine/godot/issues/55471.

**Comment by RedNicStone** [comment]
> Is the viewport's update mode set to **Always**? See #55471.

Yes it is. Replacing the 3D scene with a 2D seems to work so the configuration must be correct. The `disable_3d_rendering` option is disabled.

**Comment by Sauermann** [comment]
I was able to get the 3D-items displayed in the MRP by adding a `DirectionalLight3D` light source:

![image](https://user-images.githubusercontent.com/6299227/197407031-635a4ba9-b07e-4499-8b8f-ab9bdc801f9c.png)

**Comment by RedNicStone** [comment]
Oh that would be a tad silly if that was the issue, ill do some testing...

**Comment by RedNicStone** [comment]
I can confirm, setting viewport's `debug_draw` to `DEBUG_DRAW_UNSHADED` "fixes" the issue.
I dident expect this to be the reason since I was using a custom environment in my project (removed in the MRP) which should have been drawing but that was related to something different.

Thanks for your quick response!
Im sorry to have opened a issue for this mistake on my side.

**Comment by Sauermann** [comment]
I think, that the problem is, that the viewport shows different things in the editor and in the app. I would consider this either a usability problem or a rendering bug.

**Comment by RedNicStone** [comment]
Thats a good point. Since the editor view can be brought up by selecting the Node3D/Node2D displaying that same editor view outside of the viewport is confusing if anything.

**Comment by DriftWare07** [comment]
I'm having this same issue, but changing debug drawing or adding a light isn't fixing it. The viewport preview in the editor shows my viewmodel just fine, but it stops working when the game runs
