### ISSUE TITLE
[4.0 beta3] Can't choose a proper locale code in the project name localization setting

### ISSUE THREAD

**Issue by Rustyard** [godotengine/godot#67829]
### Godot version

4.0-beta3

### System information

Windows 10

### Issue description

In the project settings, this property `application/config/name_localized` seems to not work properly for some languages.

For example, when I choose the language for Chinese[zh]-China[CN], the locale code should be "zh_CN" but godot always give me "zh_Hans_CN" which doesn't work on the Android export (the application title won't be translated). This problem happens with Chinese[zh]-Taiwan[TW] too.

I tried to manually edit the `project.godot` file and changed "zh_Hans_CN" to "zh_CN" and then export again, and that actually worked. But I hope I can do that in the godot editor.

### Steps to reproduce

1. Create a new project
2. Open "Project -> project settings..." and choose "Application/Config"
3. Click "Name Localized" then click "Add Translation", "Select a Locale" window will show up
4. Choose language Chinese[zh] and country China[CN], then click "Select"
5. The added property will be "zh_Hans_CN" when it should be "zh_CN"

**Comment by Rindbee** [comment]
I think the option for the script field should be _[Default]_ by default. Although the option list for this field is not displayed by default, this field still seems to take effect.

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by jitspoe** [comment]
This is broken in 3.6 as well.  Broke between 3.5 and 3.6.  "zh" and "zh_HK" in csv files import as "zh_Hans_CN" and "zh_Hant_HK".  Probably need to backport https://github.com/godotengine/godot/pull/67931

**Comment by jitspoe** [comment]
Did a backport of the fix here: https://github.com/godotengine/godot/pull/98109

Had to re-implement it since the files were moved around and a simple cherry-pick didn't work.
