### ISSUE TITLE
FreeBSD build failure: HAVE_SECURE_GETENV erroneously set for openxr dependency

### ISSUE THREAD

**Issue by phryk** [godotengine/godot#67838]
### Godot version

4.0.dev (040f49ed6e71a6e7f23d763c4b56095cbf319ef7)

### System information

FreeBSD 13.1-RELEASE, GENERIC kernel, amd64

### Issue description

When specifying the `linuxbsd` platform for scons during build, `modules/openxr/SCsub`
defines `HAVE_SECURE_GETENV` for the `openxr` third-party dependency. This define
implies the existence of the function `secure_getenv` – which FreeBSD doesn't have.

That in turn leads to the build currently failing on FreeBSD when it encounters [this](https://github.com/godotengine/godot/blob/040f49ed6e71a6e7f23d763c4b56095cbf319ef7/thirdparty/openxr/src/common/platform_utils.hpp#L53):
```cpp
#ifdef HAVE_SECURE_GETENV
    return secure_getenv(name);
```

I can confirm that commenting out the define of `HAVE_SECURE_GETENV` in
[modules/openxr/SCsub](https://github.com/godotengine/godot/blob/040f49ed6e71a6e7f23d763c4b56095cbf319ef7/modules/openxr/SCsub#L37) fixes said build failure *on FreeBSD*, but am not too
sure how to fix this without finally introducing BSD as its own platform.

I also can't speak on whether the other BSDs provide `secure_getenv`,
but a cursory check for corresponding man pages on [man.openbsd.org](https://man.openbsd.org/secure_getenv)
and [man.netbsd.org](https://man.netbsd.org/secure_getenv) yields no results.

### Steps to reproduce

* Run `scons platform=linuxbsd` on FreeBSD

**Comment by kdiduk** [comment]
The same issue is present when building on OpenBSD (apart from several others, mentioned in this ticket: #92130)
