### ISSUE TITLE
3D Physics RigidBody: distance on elevator not equal

### ISSUE THREAD

**Issue by MikeFrom** [godotengine/godot#67846]
### Godot version

3.5.1.stable

### System information

Windows 10

### Issue description

I have an elevator (KinematicBody -> Box) going down and up, where my Rigidbody ball lies on it.

The 3D Physics engine (Godot and Bullet) calculates very different distances from my RigidBody to the KinematicBody when its going down or up. I would expect an equal distance.

Is this a bug?

<img width="342" alt="elevator_down" src="https://user-images.githubusercontent.com/50963378/197588419-2b61e6a9-57d5-47ad-b399-b00e4901f90e.png">

<img width="342" alt="elevator_up" src="https://user-images.githubusercontent.com/50963378/197588506-085527d0-7ddb-44ac-94e1-520a4d4169f2.png">

### Steps to reproduce

test project bellow

### Minimal reproduction project

[godot221024_3d_physics_elevator_test.zip](https://github.com/godotengine/godot/files/9853884/godot221024_3d_physics_elevator_test.zip)

**Comment by Calinou** [comment]
Try adjusting the collision safe margin: https://github.com/godotengine/godot/blob/2b1544b4f47bfeec71c552ce57ff8322ec3e3cfb/doc/classes/KinematicBody.xml#L157-L162

**Comment by MikeFrom** [comment]
Hi Calinou, `sync_to_physics=true` fixed it, thank you
