### ISSUE TITLE
White screen on opening Godot 4 and each time we launch a scene in the editor

### ISSUE THREAD

**Issue by JeanMakesGames** [godotengine/godot#67862]
### Godot version

Godot 4 Beta 3 

### System information

windows 11, i5, surface pro 8

### Issue description

Every time I launch godot 4 (whatever it was the alpha version or the beta) I have a blank screen that appears for around 15seconds and every time I play a scene I have that white screen again. It has always been on, even on my macbook.

### Steps to reproduce

In my case, just by opening Godot 4 and trying to launch a scene

### Minimal reproduction project

same as above

**Comment by Calinou** [comment]
Does the editor and project run normally after that white screen?

[The Godot 4 editor and projects takes more time to start compared to 3.x](https://github.com/godotengine/godot/issues/43351). This is likely what you're seeing, [especially on macOS](https://github.com/godotengine/godot/issues/62322).

**Comment by JeanMakesGames** [comment]
Yes, between 15 to 20 seconds things run normal, but everytime I want to launch a scene, it start back again. And I'm not on mac anymore, I'm on windows 11 with the surface pro 8 but when i was on MacOs it was the same, but ive noticed that bug in EVERY alpha and beta, which makes it super hard to deal with. It's similar to the bug that was on the alpha of godot 3 back in the day.

**Comment by clayjohn** [comment]
Yes, we need to ensure that the splash screen properly displays during engine initialization, right now it looks pretty bad to just show a blank window

**Comment by JeanMakesGames** [comment]
I agree, plus also reducing the initialization time, because 15 to 20 seconds is way too much and off putting. If every time you make a small change in your game and you want to test it, it takes 20 seconds to run, people won't use it I believe.

**Comment by Calinou** [comment]
> I agree, plus also reducing the initialization time, because 15 to 20 seconds is way too much and off putting. If every time you make a small change in your game and you want to test it, it takes 20 seconds to run, people won't use it I believe.

This could be due to https://github.com/godotengine/godot/issues/20566.
