### ISSUE TITLE
Singletons inaccessible when an exported group has the same name

### ISSUE THREAD

**Issue by SleepyTonia** [godotengine/godot#67865]
### Godot version

4.0 beta3

### System information

Linux Manjaro, AMD Ryzen 2500U, Radeon Vega 8

### Issue description

Trying to access the Time singleton after naming a group "Time" using `@export_group("Time", "time")` produced the following error message: 
> Invalid call. Nonexistent function 'get_unix_time_from_system' in base 'Nil'

Commenting out the `@export_group("Time", "time")` line was what it took to fix this issue, so did changing "Time" to "Time ".

### Steps to reproduce

Write a script with an `@export_group` call, giving it the name of a singleton, such as "Time" or "RenderingServer", then try to access that singleton in any way.

### Minimal reproduction project

[SingletonNil.zip](https://github.com/godotengine/godot/files/9858998/SingletonNil.zip)

**Comment by Sslaxx** [comment]
Might not be a bug per se, if it's shadowing an existing name. Might do with a more descriptive warning/error though.

**Comment by SleepyTonia** [comment]
I agree. Took me a good while to figure out what was causing this. Though I guess a note could be added to the documentation instead. It probably won't be a very common issue.
