### ISSUE TITLE
Invalid locale: en_TW (locales not in core/translation.cpp)

### ISSUE THREAD

**Issue by songproducer** [godotengine/godot#6787]
**Operating system or device - Godot version:**
Mac OS 10.12

**Issue description** (what happened, and what was expected):
Invalid Locale: en-TW

**Steps to reproduce:**
Run a project

**Comment by akien-mga** [comment]
Does it really mention `en-TW`, or `en_TW` (underscore)?

**Comment by akien-mga** [comment]
There are two possible solutions to this issue:
- the easiest one: add `"en_TW", //  English (Taiwan)` after https://github.com/godotengine/godot/blob/54e97e5/core/translation.cpp#L134 and `"English (Taiwan)",` after https://github.com/godotengine/godot/blob/54e97e5/core/translation.cpp#L492
- the more complex, but future proof one: add a fallback mechanism in `is_valid_locale` https://github.com/godotengine/godot/blob/54e97e5/core/translation.cpp#L782 to strip the country code when the locale is unrecognized, and thus default to the global language (`en_TW` -> `en`).

**Comment by songproducer** [comment]
It really shows en-TW

**Comment by songproducer** [comment]
>If you can give the output of the locale command, that could be useful too.

How can I do this please?

**Comment by akien-mga** [comment]
Type `locale` in a terminal, and copy paste the result.

**Comment by songproducer** [comment]
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"

**Comment by akien-mga** [comment]
Hm, then I have no clue where this error comes from. Just to make sure, you do live in a Taiwanese timezone? Maybe OSX is a bit messy on its locale recognition, that would need some investigating.

**Comment by damon-myers** [comment]
@akien-mga, would you still like someone to work on falling back to a default language when the locale code is unrecognized?

**Comment by akien-mga** [comment]
@damon-myers That would be great yes. :)

**Comment by damon-myers** [comment]
Cool, I will get started on that shortly!

**Comment by damon-myers** [comment]
@akien-mga Is there a documentation page for contributing/testing guidelines? I can't seem to find it on http://docs.godotengine.org/

**Comment by songproducer** [comment]
@akien-mga Sorry, I thought I replied before - yes, I live in Taiwan.

**Comment by akien-mga** [comment]
I had partly misinterpreted this issue, which exhibited two problems:
- Missing locale `en_TW` -> Now fixed thanks to #6910 which would make such locales fallback to the non-country-specific language (here `en`).
- MacOS Sierra new locale formatting `en-TW` (with a dash) not supported by Godot, now tracked in #6942 which is a bit clearer.

So let's close this one and continue working on the second issue in #6942.
