### ISSUE TITLE
Crash the Editor [Whole system]

### ISSUE THREAD

**Issue by vishal-ahirwar** [godotengine/godot#67872]
### Godot version

3.5.1

### System information

Fedora Linux 36 [Workstation Edition]

### Issue description

When I play the game in editor my whole system stopped responding

### Steps to reproduce

This happens Accidentally I don't know which script is causing this error because when I put breakpoint in main script and debug I found nothing there 

### Minimal reproduction project

[Project Repo](https://github.com/vishal-ahirwar/Dash-Coin)

**Comment by KoBeWi** [comment]
Can't reproduce on Windows 10.
Also the project does not start correctly due to missing files.

**Comment by vishal-ahirwar** [comment]
yeah may be its working on windows OS but on fedora Workstation it crashed so many times:(

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/18871. We can't do anything without *detailed* system logs and hardware information.
