### ISSUE TITLE
Unable to view sub objects in debugger

### ISSUE THREAD

**Issue by joe-lawton** [godotengine/godot#67870]
### Godot version

4.0 beta 3

### System information

Windows 10

### Issue description

The debugger inspector will not follow sub objects

### Steps to reproduce

-Break after object creation
-Double click on "main object"s member, "sub object"

The debugger will not follow the sub object

### Minimal reproduction project

[DebuggerViewingSubobjects.zip](https://github.com/godotengine/godot/files/9860703/DebuggerViewingSubobjects.zip)
![DebuggerViewingSubobjects](https://user-images.githubusercontent.com/105455193/197786256-845cf084-49fe-4bbf-aa3d-88d06c02db74.png)

**Comment by akien-mga** [comment]
Thanks!
