### ISSUE TITLE
Text rendering in front of Sprite2D differs and has artifacts compared to a panel with the same opaque color

### ISSUE THREAD

**Issue by roookeee** [godotengine/godot#67883]
### Godot version

Godot_v4.0-beta1_mono_win64

### System information

Windows 11, Nvidia 1060

### Issue description

Rendering text (e.g. via a `Label`) in front of a `Sprite2D` with a flat color differs compared to rendering the same label in front of a `Panel` with the same flat color. Here is an example with a `Panel` on the left and the same text in front of a `Sprite2D` on the right (you have to zoom in pretty deeply to see the issue):
![image](https://user-images.githubusercontent.com/1199562/197871473-74fa28ef-2850-4583-a7ea-45be33659805.png)

Here is a direct side-by-side (`Sprite2D` is on the right):
![image](https://user-images.githubusercontent.com/1199562/197872617-6845b5c4-eae0-4070-b32c-81fdfb747e28.png)
Notice the "ghosting" at the top of the x.

At first I thought it was an issue with subpixel positioning but the given example image highlights the issue at any screen position. I am not that knowledgeable about rendering and can't give any more insights here. The issue becomes more apparent when scaling is used on the parent container.

### Steps to reproduce

1. Add a solid-colored panel and label to your scene containing some text
2. Add a Sprite2D to your scene that has the same color and add another label in front of it
3. Notice the artifacts in front of the Sprite2D

### Minimal reproduction project

[sample.zip](https://github.com/godotengine/godot/files/9863732/sample.zip)

**Comment by roookeee** [comment]
I just noticed that my example does not reflect my actual issue as the "ghosting" is present in front of the `Panel` as well, just at the bottom. Will open another issue that reproduces my issue (if I can reproduce it properly).

**Comment by roookeee** [comment]
I actually found the issue after wondering for weeks what was going on with my rendering on one of my screens: it was actually a broken display port on my graphics card. Switching to another one resolved all the issues. Heres an image of the issue:
![image](https://user-images.githubusercontent.com/1199562/201525554-ac8f7286-6af1-492a-8d5c-c2782d5f264d.png)
The brown/orange aliasing around the second occurence of "The quick brown" on the left side were actually present for me and not caused by photo capturing. I hope noone else ever runs into this issue :D

**Comment by Calinou** [comment]
It looks like 4:2:0 chroma subsampling was being forced on the display due to your cable lacking the required bandwidth for full 4:4:4 color. Alternatively, this may be caused by poor configuration in the graphics driver.

**Comment by roookeee** [comment]
Thats a bit too technical but probably true as I couldn't run my monitor with 165hz (it was not available in Windows) and instead was forced to 120hz at most (which is more than enough but was peculiar). Thank you for looking into this false report, the next time I run into this I will check all cables / ports first as I double checked and its really the port that's broken, the cable works fine - d'oh!
