### ISSUE TITLE
Layout not properly display on Android

### ISSUE THREAD

**Issue by pixelguy106** [godotengine/godot#67899]
### Godot version

3.5

### System information

Infinix smart 6 HD

### Issue description

The game engine layout unclickable in some part I think because of the size of my screen the layout are unable to correct the position. I think the best way too fix it is to add layout resizeable 

### Steps to reproduce

None

### Minimal reproduction project

None

**Comment by Zireael07** [comment]
IS this the Android build? What is the DPI of your device and the size in inches?

**Comment by pixelguy106** [comment]
I already fix it by  dragging the layout until I see the button and also change the layout size.
