### ISSUE TITLE
Class method (function) does not return expected values 

### ISSUE THREAD

**Issue by funabab** [godotengine/godot#6789]
**Operating system or device - Godot version:**

Godot 2.1 stable

**Issue description** (what happened, and what was expected):

this seem kind of weird to me cause i can't really tell if am the one doing something wrong, so i made a little project to illustrate the problem. 

**Steps to reproduce:**

(Example project below) 

**Link to minimal example project** (optional but very welcome):
https://drive.google.com/file/d/0Bz6wAnc_xKblajk2X1JYNzNaczA/view?usp=drivesdk

**Comment by funabab** [comment]
The problem is that CalculatorRuntime.calculate() returns the same result, so am getting the same result in the returned dictionary (Problems.solve() )

**Comment by Hinsbart** [comment]
This happens because dictionaries are passed by reference.
So when this function runs:
```Python
func solve():
		return {
		"first_solution": cal_runtime.calculate(params["first"]),
		"second_solution": cal_runtime.calculate(params["second"]),
		};
```
It stores a **reference** to the `buffer` object used in the `calculate` method as the value for the "first_solution" key. Then the second call to `calculate` overwrites the buffer, thus also changing the reference stored before.

**Comment by volzhs** [comment]
@Hinsbart made so fast answer.
@funabab You should make another `Dictionary` instead of `buffer.clear()`
```gdscript
func clear_buffer():
	buffer = {}  # instead of buffer.clear()
```

**Comment by funabab** [comment]
@Hinsbart that totally make sense... 

@volzhs taught Dictionary was built in... 
@volzhs i use breakpoint alot don't know why i didn't use it in testing it (maybe cause i was so sure that dictionary were built in :)
Thanks guys..  Please close
