### ISSUE TITLE
Cannot add different materials to two CSG meshes in the same scene

### ISSUE THREAD

**Issue by Skaruts** [godotengine/godot#67893]
### Godot version

4.0.beta3.official.01ae26d31

### System information

Windows 7, Vulkan, GeForce GTX 960

### Issue description

Not being able to set two separate materials to two separate CSG objects in the same scene.

### Steps to reproduce

I made two materials, using two textures, then created two `CSGBox3D`s in a scene and tried to place the two materials on both objects, but then when I reload the scene or run the project, both of the objects will show up using the same material.

This seems to happen regardless of how I assign the material. I tried dragging the material onto the objects in the 3D view, as well as dragging to any of the material slots in the inspector. 

### Minimal reproduction project

This is my actual project, but it's mostly bare bones at this point. It as only two scenes and the materials. This happens in the `test_scene.tscn`.
[mat_bug_proj.zip](https://github.com/godotengine/godot/files/9866761/mat_bug_proj.zip)

**Comment by alazifk** [comment]
Tested this on Win10, I did not encounter any error.
[mat_bug_proj_fixed.zip](https://github.com/godotengine/godot/files/9867344/mat_bug_proj_fixed.zip)

**Comment by Skaruts** [comment]
Just to better illustrate my problem: 
https://i.imgur.com/hAPvmAO.mp4

**Comment by Skaruts** [comment]
Actually, I think I found the issue: I just noticed they both have the same uid. 

Might this be because I created the second material by duplicating the first one in the FileSystem tab?

I created a new green material from scratch and now I'm able to place both the materials on the meshes without a problem.

**Comment by alazifk** [comment]
Ah, okay, I also get the error. The uids should indeed be unique. Duplication should not be the issue.

**Comment by alazifk** [comment]
Update: I just managed to reproduce the error using the `.material` ending.

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/60849 (possible duplicate, likely the same cause).
