### ISSUE TITLE
NODE_POSITION_WORLD and NODE_POSITION_VIEW shader built-ins do not yield the expected results ('model_matrix' : undeclared identifier)

### ISSUE THREAD

**Issue by alfredbaudisch** [godotengine/godot#67894]
### Godot version

Godot4-beta3

### System information

Windows 10

### Issue description

The `NODE_*` built-ins implemented in https://github.com/godotengine/godot/pull/63597 are currently null/0.

**UPDATE:** By pulling Godot from the master branch, there's now a related crash when using the `NODE_*` built-ins (either in a Shader and VS):

```
ERROR: 0:2121: 'model_matrix' : undeclared identifier 
ERROR: 0:2121: 'model_matrix' :  left of '[' is not of type array, matrix, or vector  
ERROR: 0:2121: 'assign' :  cannot convert from ' const float' to ' temp highp 3-component vector of float'
ERROR: 0:2121: '' : compilation terminated 
ERROR: 4 compilation errors.  No code generated.
```

To make it easy to visualize for this Issue, I set them both to the Albedo channel, so it would be possible to visualize the RGB colors changing, but no matter where in the world, there are no changes:

![image](https://user-images.githubusercontent.com/248383/197957533-07a58e97-c1f0-4dc4-b1c1-6a4a86d1880d.png)

![image](https://user-images.githubusercontent.com/248383/197958066-ab35775b-b83d-45ce-aa1f-d80fc74c2c31.png)

### Expected - NODE_POSITION_WORLD / World Position
Unity:
![image](https://user-images.githubusercontent.com/248383/197957704-99631c9a-13df-42c9-ad1b-4f3e349c4913.png)

UE:
![image](https://user-images.githubusercontent.com/248383/197957781-0806a827-1750-458c-bb0c-889994a02f8c.png)

### Expected - NODE_POSITION_VIEW / Object Position
Unity:
![image](https://user-images.githubusercontent.com/248383/197957847-5ce20244-3f90-4ed9-afae-5a58575a0da5.png)

UE:
![image](https://user-images.githubusercontent.com/248383/197957984-bc121914-2597-4c5e-b650-245b2f7f5ed7.png)

### Steps to reproduce

Use `NODE_POSITION_WORLD` and/or `NODE_POSITION_VIEW` in any shader (VS or GDShader), the result is always `0`.

```c
void fragment() {
ALBEDO = NODE_POSITION_VIEW;
}
```

### Minimal reproduction project

[NodePositionSample.zip](https://github.com/godotengine/godot/files/9867026/NodePositionSample.zip)

**Comment by clayjohn** [comment]
Cc @paddy-exe

**Comment by paddy-exe** [comment]
@clayjohn From testing I can say that there must be a regression between `beta 2` and `beta 3`

This is how it looks like when it's working in beta 2:

https://user-images.githubusercontent.com/38077837/198077975-6da09944-deba-4787-976f-a35fdf5d3094.mp4

**Comment by clayjohn** [comment]
@paddy-exe the issue must be from my double precision changes, I will take a look

**Comment by alekseym88** [comment]
@akien-mga  @clayjohn  Hello! Seems this problem is still exist, I have same problem for last godot build on MacOS Monterey, graphics: Intel Iris Graphics 550 1536 MB.

`
shader_type spatial;
render_mode unshaded;

void fragment() {

	vec4 view = VIEW_MATRIX * vec4(NODE_POSITION_WORLD, 1.0);
	vec3 view_n = view.xyz/view.w;
	
	if (view_n == NODE_POSITION_VIEW){
		ALBEDO = vec3(1.0, 0.0, 0.0);
	}
}
`

and 

`
shader_type spatial;
render_mode unshaded;

void fragment() {

	vec4 world = INV_VIEW_MATRIX * vec4(NODE_POSITION_VIEW, 1.0);
	vec3 world_n = world.xyz/world.w;
		
	if (world_n == NODE_POSITION_WORLD){
		ALBEDO = vec3(1.0, 0.0, 0.0);
	}
}
`

gives a white screen instead red (as should be on IF condition)

**Comment by clayjohn** [comment]
@alekseym88 this bug report was reporting a shader compilation error that came from using those builtins. The fact that your shader compiles means you are not facing the same issue. 

Your issue comes from floating point precision. By doing multiple operations, you are losing precision such that the equality operator fails. Take a look at [this site](https://floating-point-gui.de/) for a deeper explanation about how floating point numbers work and why avoiding == between two floats is important

**Comment by Lunarexxy** [comment]
It appears that model_matrix being undefined is still an issue in web exports. Godot 4 beta 5, tested on Firefox.

![image](https://user-images.githubusercontent.com/8879206/203102140-bd240a4e-cda1-4b8d-8e9e-a6863456bd28.png)

Using only this in my visual shader. (node_position_view has a similar "model_matrix undefined" error)

![image](https://user-images.githubusercontent.com/8879206/203102278-5ede1330-6d7a-4044-a995-8c598abad1ef.png)
