### ISSUE TITLE
EditorPlugin - "Error: set_persisting" when deactivated. 

### ISSUE THREAD

**Issue by rgrams** [godotengine/godot#6792]
**Operating system or device - Godot version:** Windows 7, build from Sept 12th

**Issue description** (what happened, and what was expected):
When you set an editor plugin to be "inactive" in Project Settings, it gives a the following error in the console: 

> ERROR: set_persisting: Condition '  !props.has(p_name) ' is true. 
>     At: core/globals.cpp:100

I thought it was something I messed up with my own plugin, but it happens for every plugin I've tried, including all three of the official ones (custom dock, import plugin, and node). I tested them in a new, empty project. 

It doesn't crash the editor or cause any noticeable issues though, should I just ignore this?

**Comment by bojidar-bg** [comment]
Can someone confirm this on 3.0 or 2.1.3?

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.
