### ISSUE TITLE
Godot4.0-Beta3，I can‘t get any properties of Class InputEventMouseButton

### ISSUE THREAD

**Issue by DJRockTime** [godotengine/godot#67930]
### Godot version

GODOT4.0-beta3

### System information

Window10 

### Issue description

The class InputEventMouseButton's properties it looks like didn't work and throw new error: Invalid get index "button_index" ( on base : 'Nil' ) .

### Steps to reproduce

![editor_screenshot_2022-10-27T130915](https://user-images.githubusercontent.com/38347978/198197500-651719b0-f168-43b6-becc-abefbd01f906.png)

**Comment by zCubed3** [comment]
Input events should be handled in _input(), you're handling them in _physics_process(). Also button is never assigned to, therefore it is implicitly nil, you must create / assign an event to the variable before you access it.

**Comment by zCubed3** [comment]
Refer to the documentation for input for further info, https://docs.godotengine.org/en/stable/tutorials/inputs/input_examples.html
This might be akin to what you were intending to do originally.
```gd
func _input(event):
	if event is InputEventMouseButton:
		if event.button_index == 1:
			print("BUTTON_LEFT")
```

**Comment by timothyqiu** [comment]
Closing as per @zCubed3's comment.

**Comment by DJRockTime** [comment]
thank you~
