### ISSUE TITLE
Enabling shadows causes additional 3D draw calls in empty viewport

### ISSUE THREAD

**Issue by 74boar** [godotengine/godot#67935]
### Godot version

3.5.1

### System information

Windows 10, GLES3, Nvidia GTX 1080 Ti

### Issue description

When enabling shadows in a 3D scene, draw calls increase when a Viewport with a Camera child is in the scene tree, regardless of what the Camera is rendering. Disabling every layer of the Camera’s cull mask does not reduce the added draw calls.

### Steps to reproduce

![tree](https://user-images.githubusercontent.com/73418509/198238577-d72804a8-e7bb-47f6-8bb2-d0817e4102bf.PNG)

1.	Disable shadows in the directional light.
2.	Run the scene
3.	Toggle visibility on the viewport container off/on. (Draw calls stay the same)
4.	Enable shadows in the directional light. (Draw calls increase substantially)
5.	Disable visibility on the viewport container. (Draw calls decrease, unexpected behavior)

### Minimal reproduction project

[Viewport_Draw_Calls_MRP.zip](https://github.com/godotengine/godot/files/9877500/Viewport_Draw_Calls_MRP.zip)

**Comment by TheDuriel** [comment]
I would expect this, as it is performing a draw for shadows as long as shadows _could_ exist. There just don't happen to be any shadows. It still has to do all the work to find that out, and effectively, not draw them.

**Comment by TheDuriel** [comment]
Not seeing anything out of the ordinary here.

You're getting a static number of calls, per object, per shadow, **per viewport**.

8 calls, viewport off, shadows off
12 calls, viewport off, shadows on
16 calls, viewport on, shadows on
8 calls, viewport on, shadows off

1 Call per object visible in any viewport + 1 call for its shadow.

Regardless of what is visible on screen, objects and their shadows create a draw call in the performance monitor. You will however note that "objects drawn" correctly reflects the number of visible meshes displayed on the screen. (Unless of course you are hiding them behind something else, in which case you can't see them, but they are there behind the obstruction.)

**Comment by 74boar** [comment]
Thank you for the clear explanation. I think I misunderstood what exactly a draw call is.
