### ISSUE TITLE
GDScript 2.0: `Array.append` results in an invalid await runtime error 

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#67943]
### Godot version

v4.0.beta3.official [01ae26d31]

### System information

Windows 10

### Issue description

I run in this issue during testing my test API.
When using an `array.append()` after an await it will be results into a runtime error
`Trying to call an async function without "await".`

### Steps to reproduce

Run this code:

```
class_name TestScene
extends Node

func _ready():
	pass

func _process(_delta):
	set_process(false)
	
	await execute()
	#var value = ""
	#value += "foo"
	
	var list := Array()
	list.append("foo")
	
	set_process(true)

func execute():
	await get_tree().process_frame
```

# Error
`Trying to call an async function without "await".`

![image](https://user-images.githubusercontent.com/347037/198297556-57776355-a976-4ea4-8c1a-5276ee5d6b3c.png)

And also very strange when you enable the commented out lines again, the error is gone.

**Comment by vnen** [comment]
I have a hunch about this and might have already been fixed. I'll test it later when I have some more time.

**Comment by vnen** [comment]
I forgot about this one. I tried now and cannot reproduce it so I do believe it has already been fixed.
