### ISSUE TITLE
GltfDocument `append_from_file` cause to show `SCRIPT ERROR: ` which should be used only with GDScript/C#

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#67951]
### Godot version

4.0.beta.custom_build. 39534a7ae

### System information

Ubuntu 22.04 - Nvidia GTX 970, Gnome shell 42 X11

### Issue description

```
	var temp_variable182 = GLTFDocument.new()
	temp_variable182.append_from_file("5555", null, -81, -56, "")
```
shows 
```
SCRIPT ERROR: 
          at:  (:0)
ERROR: Condition "err != OK" is true. Returning: ERR_PARSE_ERROR
   at: _parse (modules/gltf/gltf_document.cpp:6570)
ERROR: Condition "err != OK" is true. Returning: err
   at: append_from_file (modules/gltf/gltf_document.cpp:7032)
```
if I undestand correctly, `SCRIPT ERROR` should only be visible when using/loading broken GDScript/C# files, not GltfDocuments.

### Steps to reproduce

Above

**Comment by lyuma** [comment]
This issue is missing an MRP and references a GDScript issue during 4.0 dev cycle which was likely fixed.

The issue is that too many arguments are passed into `append_from_file` which accepts only 4 arguments, not 5.
