### ISSUE TITLE
AnimationNodeStateMachine don't play synced animations

### ISSUE THREAD

**Issue by dannygaray60** [godotengine/godot#67953]
### Godot version

3.5.1 stable

### System information

Windows 10

### Issue description

In this example there are two attack animations for the character (when attacking on the ground and in the air). When you play the attack animation in the air and immediately call the attack animation on the ground the "sync" trip of animationtreeplayer works fine. But this does not always work, mainly from time 0.6 onwards.

![GIF 27 - octubre - 2022 11-47-54 a  m](https://user-images.githubusercontent.com/30391210/198363712-43a53551-f9f2-42a3-acbc-98c5ccddef75.gif)

### Steps to reproduce

Make an `AnimationTree` with a `AnimationNodeStateMachine` and connect two animations with `sync` switch mode. Like this:

![Captura de pantalla (172)](https://user-images.githubusercontent.com/30391210/198364065-ede150b9-c6a9-40f9-844a-0fe72837322b.png)
![Captura de pantalla 2022-10-27 115902](https://user-images.githubusercontent.com/30391210/198364301-f417de71-345f-4d5d-b6c1-b8651c2fb1e2.png)

### Minimal reproduction project

I added a simple example project. Press "Left" to play "air attack" and "Right" for "floor attack".

[Test Syn AnimTree.zip](https://github.com/godotengine/godot/files/9882052/Test.Syn.AnimTree.zip)

**Comment by rakkarage** [comment]
only seems to happen in second half... where dest sync anim is light on frames? 0.6 - 0.9?
adding some constant frames to that part of dest sync anim seems to fix it, as a workaround.

![Screenshot from 2023-10-20 13-11-39](https://github.com/godotengine/godot/assets/962340/e6edaa6b-13e7-458d-a7e9-77ac0d143f72)

https://github.com/godotengine/godot/issues/79505
this issue maybe gives some hints as to why sync not working?

**Comment by dannygaray60** [comment]
Uhhh... I reported the issue for godot 3.X so... No updates for godot3? 😅😭
