### ISSUE TITLE
Default clear color not applied on some projects.

### ISSUE THREAD

**Issue by DriNeo** [godotengine/godot#6795]
**Operating system or device - Godot version:**
Godot 2.1 stable, Windows 8.1, Intel HD4600.

**Issue description** (what happened, and what was expected):
In some projects the new clear color is applied only in editor.

In the other projects the new clear color is applied only in the running game. After a restart the color is applied in the editor too, as expected.

**Steps to reproduce:**
In the "SAT collision test" demo set another default clear color.

**Link to minimal example project** (optional but very welcome):
The "SAT collision test" official demo  ;)

**Comment by kubecz3k** [comment]
I think we will need to check if this bug will be still present after renderer rewrite in Godot 3.0

**Comment by bojidar-bg** [comment]
Bump, I think I saw it fixed in some gif, was it?

**Comment by reduz** [comment]
I tested this and does not seem to be happening any longer
