### ISSUE TITLE
Forward Plus: 3D rendering fails and/or freezes Godot, spams errors

### ISSUE THREAD

**Issue by jtnicholl** [godotengine/godot#67958]
### Godot version

v4.0.beta.custom_build [4dc2c8ae6]

### System information

Linux (Fedora 36), AMD R9 390x w/ amdgpu

### Issue description

3D rendering using the Forward Plus renderer fails and sometimes freezes Godot, printing a multitude of errors every frame, including:

- The entire contents of `scene_forward_clustered.glsl`
- `Condition "!shader" is true. Returning: RID()`
- `Condition "rid.is_null()" is true. Returning: rid`
- `Condition "!uniform_set" is true.`
- `Uniforms were never supplied for set (0) at the time of drawing, which are required by the pipeline`

They are also printed once upon opening the project manager.
This is appears to be a regression caused by #66107, reverting it fixes the errors.

### Steps to reproduce

Open any project using Forward Plus. Mobile seems unaffected.

**Comment by Calinou** [comment]
cc @clayjohn

**Comment by clayjohn** [comment]
Looks to be a merge conflict not caught by git. I'll have a PR ready as soon as my compile finishes
