### ISSUE TITLE
Script Editor Ctrl+D no longer works (regression)

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#67962]
### Godot version

4.0 beta3

### System information

Win 10, Nvidea 765M

### Issue description

Pressing Ctrl+D to duplicate in the Script editor does not work in Godot 4 beta3 compared to Godot 3.5.1.

Godot 3.5.1 stable:

https://user-images.githubusercontent.com/47016402/198418255-c06ddd25-c898-4e37-acd2-ec0a6be0e393.mp4

Godot 4.0 beta3:

https://user-images.githubusercontent.com/47016402/198418202-fe4a5179-3ec7-48fd-acb0-ca5227b0a7b9.mp4

### Steps to reproduce

1. write some code
2. select it
3. press Ctrl+D

### Minimal reproduction project

does not require MRP

**Comment by clayjohn** [comment]
Do you know if this issue was present in earlier betas? https://github.com/godotengine/godot/pull/65241 looks like it might be the culprit, but it was merged before beta 1

**Comment by golddotasksquestions** [comment]
Hey, so I have now tested all the beta Godot4 version, a lot of alpha versions and even some very old prealpha versions and all of them have the same issue with Ctrl+D in the script editor.

The oldest Godot4 prealpha version I tested was v4.0.dev.20211015.official [f113dc986]

**Comment by Cykyrios** [comment]
The default shortcut was changed to Ctrl + Shift + D, Ctrl + D now just selects/unselects the word under the cursor.

**Comment by alfredbaudisch** [comment]
Also notice that with https://github.com/godotengine/godot/pull/67644, `CTRL+D` is changed again:

- If there's no selection, `select_word_under_caret` is performed
- If there's a selection, the next occurrence of the selection is selected. Check the PR for details.

**Comment by golddotasksquestions** [comment]
> Ctrl + D now just selects/unselects the word under the cursor.

Who in their right mind would approve this change? This has to be a mistake!

**Comment by clayjohn** [comment]
> > Ctrl + D now just selects/unselects the word under the cursor.
> 
> Who in their right mind would approve this change? This has to be a mistake that slipped through the cracks!

Please try to be more respectful.

**Comment by bruvzg** [comment]
> Who in their right mind would approve this change?

All shortcuts are configurable in the `Editor Settings`, so if you do not like default shortcuts, you can set it to whatever you want.

**Comment by golddotasksquestions** [comment]
@clayjohn 

> Please try to be more respectful.

This has nothing to do with respect. I have the utmost respect for anyone contributing to Godot in any way shape of form. I meant it as I said it: I can literally not imagine anyone would approve of this change when they are actually aware of making this decision (-> colloquially "in their right mind")

So my only logical conclusion is this decision was made by accident and has to be a mistake.

I mean noone in their right mind would change Ctrl+C to Shift+Ctrl+C either for the same behaviour, right? Especially since Ctrl+D has already been in use for it's commonly known behavior of duplicating stuff for years in this software.

@bruvzg 
This **_is_** about default shortcuts. I'm well aware about customizing shortcuts. The ability to customize shortcuts is not a good argument to change incredibly common and well known exiting shortcuts and behaviour to something much less common and therefore much less discoverable.

**Comment by clayjohn** [comment]
@golddotasksquestions Questioning a person's sanity because they made a decision you disagree with is disrespectful. I don't need to teach you that. 

Importantly, there was no reason to question a person's sanity to get your point across, you could have easily said that you think a mistake has been made, or that you disagree with the decision. 

I am closing this thread now as it is abundantly clear that there is no underlying bug and you have been given a helpful workaround. Its fair enough if you want to open a discussion on what the default shortcuts _should_ be. I understand how annoying it is to have shortcuts changed on you. But the appropriate place to have that discussion is in the [discussion forum in the godot-proposals reposity](https://github.com/godotengine/godot-proposals/discussions). Feel free to open a discussion there.

**Comment by golddotasksquestions** [comment]
@clayjohn 

I'm not questioning anyone's sanity. If that's the impression I'm sorry, this was definitely not my intent. Maybe it's lost in translation, My understanding of "in their right mind" is equal to "not present" or "not focused on the thing they are doing". It's not derogatory. At least from my understanding. If it is to someone else I sincerely apologize.

**Comment by Zireael07** [comment]
@golddotasksquestions "in their right mind" means "sane", so NOT in their right mind means, well... the opposite

**Comment by GDami** [comment]
Ctrl + D is the duplication shortcut all across the engine except in the text editor, the new functionality should use the new shortcut instead of the existing one
