### ISSUE TITLE
C# RpcId randomly crashing with no error

### ISSUE THREAD

**Issue by Kody06** [godotengine/godot#67966]
### Godot version

4.0 Beta 3

### System information

Windows 10

### Issue description

I'm calling a RpcId at Server.cs Line 219 60 times a second and it randomly crashes with no error after 3-10 seconds.

### Steps to reproduce

Start Server
Start Client
Press Connect To Server Button
Press Spawn Button
Wait 3-10 Seconds

### Minimal reproduction project

https://github.com/Kody06/MovementStuff

**Comment by zCubed3** [comment]
I downloaded the project and am experiencing the same crashes, the exit code is 3221226356 (0xC0000374). Meaning RpcId or some other code within this project is causing heap corruption

**Comment by zCubed3** [comment]
I was not able to replicate this issue on Linux, I left the server to run in the background with the client in the foreground for about 1 minute and there was no crash, could this be limited to just windows? (If it matters, I am using Arch Linux with the latest packages installed, on kernel version 6.0.2-arch1-1)

**Comment by ozqf** [comment]
I am unable to reproduce it reliably at the moment but I wanted to add I too are getting crash events with code 0xc0000374. Godot 4 beta 6 C#. I am not doing anything related to networking, it just happens as you play. Attempting to narrow it down.

**Comment by RedworkDE** [comment]
Does this issue still exist with a 4.0-stable release? This issue sounds like a duplicate of a whole bunch of other issues that got fixed by https://github.com/godotengine/godot/pull/69194.
