### ISSUE TITLE
Preload function would have to accept a  constant string parameter as input.

### ISSUE THREAD

**Issue by Rocket-Buddha** [godotengine/godot#6798]
**Preload function would have to accept a  constant string parameter as input.**

```
const WARM_UP_STATE = "res://scenes/states/warm_up/warm_up.tscn"

func _go():
    current_state = preload(WARM_UP_STATE).instance()
    level.add_child(current_state)

```

> res://scenes/levels/level_01/src/node2d_state_manager.gd:23  - Parse Error: expected string constant as 'preload' argument.

**Comment by vonflyhighace2** [comment]
Not understanding what you mean.

you could just do:

WARM_UP_STATE = preload("res://scenes/states/warm_up/warm_up.tscn")

then just call it in your function

```
func _go():
current_state = WARM_UP_STATE.instance()
level.add_child(current_state)
```

**Comment by Rocket-Buddha** [comment]
That's right! But IMO it doesn't change the fact that the function should accept a constant string and WARM_UP_STATE is a constant string.

**Comment by kubecz3k** [comment]
I also think it should accept constants even if it's defined in external file (lets say I have singleton with constants)

**Comment by hetdegon** [comment]
This is amusing. I was going to say something because I am loading an "empty scene" from a string constant in my project. Turns out I was using load() (which works) instead of preload() (which doesn't), making them inconsistent.

**Comment by akien-mga** [comment]
Well it's normal that `load()` works as it does not expect a constant. But `preload()` does, and apparently fails to see a const String as such.

**Comment by hetdegon** [comment]
Ah I see, I figured load() would also expect a constant.

**Comment by Rocket-Buddha** [comment]
As i see it, preload function loads the resource when the scene is constructed, for that reason needs a constant input, on the other hand load function loads the resource when it is called.

**Comment by sabbir28** [comment]
Thanks i use this as my final code.. texture = ResourceLoader.load(image_path) and it work properly
