### ISSUE TITLE
No relative anchor positions anymore?

### ISSUE THREAD

**Issue by LuFlo** [godotengine/godot#67989]
### Godot version

4.0 beta3

### System information

PopOS 22.04

### Issue description

I'm trying to dynamically size the HUD / UI to the window size of the game. Unfortunately the HUD stays the same size because I'm not able to define relative anchor sizes. See the screenshots of 3.5 and 4.0 respectively:

3.5:

![Screenshot from 2022-10-28 22-58-23](https://user-images.githubusercontent.com/10896164/198733110-508b2b62-09b5-40c4-aadd-7516dc9856fa.png)

4.0 beta3:

![Screenshot from 2022-10-28 22-59-13](https://user-images.githubusercontent.com/10896164/198733114-8cbe552f-06e0-49f7-8b22-731cd4e3bf04.png)

I've found this issue: https://github.com/godotengine/godot-proposals/issues/4994
Is it possible that this feature is only partly implemented it will be completed in a later beta? Because I can't find the FullScreen Containers :( 

### Steps to reproduce

Add a main HUD with a HBox with three sub containers. The center one should shrink and the outer ones should stay "sticked" to the screen borders.

### Minimal reproduction project

[UI_3.5.zip](https://github.com/godotengine/godot/files/9891880/UI_3.5.zip)
[UI_4.0.zip](https://github.com/godotengine/godot/files/9891882/UI_4.0.zip)

**Comment by LuFlo** [comment]
When I set the anchor preset to custom, I can set the anchor points, but they have no effect...

![Screenshot from 2022-10-28 23-28-05](https://user-images.githubusercontent.com/10896164/198735872-3e3af3bf-d642-434e-960d-872566f76d5a.png)

**Comment by KoBeWi** [comment]
I think the anchors have no effect because you didn't put your node under Control node. What type is its parent?

**Comment by LuFlo** [comment]
> I think the anchors have no effect because you didn't put your node under Control node. What type is its parent?

The MainHUD sits normally in a Node2D (the parent of all 2D nodes in my world). Even if I put it in a Control Node, nothing changes. Also it never was necessary in 3.5

**Comment by LuFlo** [comment]
I think now I got you, so I need to put the whole Node2D-Scene also inside a Control node? This time it seems to be working :D But is this really working as intended? It seems a bit weird to me...

**Comment by timothyqiu** [comment]
Anchor Offsets are the equivalent of Margins in 3.x. These anchor properties are only available when using custom preset.

![ksnip_20221029-143038](https://user-images.githubusercontent.com/372476/198817459-d493476c-163d-44b9-8b91-724d5a6cf1c6.png)

These will bring you the same positioning as in 3.5.1.

**Comment by LuFlo** [comment]
> 

Yea I know, the issue was that I didn't put the WHOLE scene (including the 2D game content itself) inside a control parent. My question is why this is necessary in 2D but not in 3D

**Comment by timothyqiu** [comment]
I'm not sure what's the problem you described, but anchors are relative to the node's parent rect.

If the parent is a ...

* `Control`: This is simple as the parent rect is the control's rect.
* `Node2D`: The rect's position is the same as the node's position. But the size depends on the node's type and defaults to zero. For example, the rect size of a `Sprite2D` depends on the texture.
* Other type of nodes: Uses the viewport rect, i.e. fullscreen.

So in a 3D scene, the parent rect is fullscreen. In a 2D (Node2D) scene, the parent rect is usually `(0, 0, 0, 0)` and it's usually recommended to use a `CanvasLayer` as the parent.

This is not changed between 3.x and 4.0 I think.
