### ISSUE TITLE
Disabling script template is not remembered after editor restart

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#67988]
### Godot version

4.0 11e1bac

### System information

Windows 10 x64

### Issue description

When you disable script template to have an empty script, it will only be remembered until you exit the editor. Next time you will have to disable it again. Pretty sure it wasn't like that when the feature was implemented for the first time.

### Steps to reproduce

1. Add script to node
2. Uncheck this
![image](https://user-images.githubusercontent.com/2223172/198733073-bb56a6f2-d7be-4ee6-8fff-9b1e777ab18d.png)
3. Restart the editor
4. It's enabled again

**Comment by dalexeev** [comment]
It looks like this is not a regression, but an initially unimplemented behavior.

**Comment by KoBeWi** [comment]
I reviewed and approved the original implementation (#53957) and according to the comments it was implemented at some point.

**Comment by dalexeev** [comment]
Indeed, this was originally implemented, but then was accidentally removed in #59603.

**Comment by dalexeev** [comment]
I'm not entirely sure what `templates_dictionary` is for, but it looks like that logic has been removed as well.

https://github.com/godotengine/godot/pull/59603/files#diff-265788e1751b9ed8b0ec9dad4e96ecbfd7a85457b078e13bfaccd053eb2cf858L600-L603

**Comment by KoBeWi** [comment]
I left a comment in https://github.com/godotengine/godot/pull/59603. That PR was wrong.
