### ISSUE TITLE
Bug when using `backspace` when using multiple carets

### ISSUE THREAD

**Issue by BeayemX** [godotengine/godot#67992]
### Godot version

v4.0.beta.custom_build [11e1bac76]

### System information

Linux Fedora - Godot Engine v4.0.beta.custom_build.11e1bac76 - https://godotengine.org Vulkan API 1.2.0 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1080

### Issue description

When having a selection with multiple carets and pressing backspace, one additional character is wrongly deleted for all but the latest created caret.

### Steps to reproduce

Given this text snippet:

```
	car.test()
	car.test()
	car.test()
	car.test()
```

1. place the cursor in one of the `test` strings
2. press `ctrl+d` until all occurrences are selected
it should look like this:
![image](https://user-images.githubusercontent.com/3453076/198749388-4d5adde6-ec0b-4f27-a78c-d098472223e0.png)

4. press `backspace`
this is the result:
![image](https://user-images.githubusercontent.com/3453076/198749420-1df8e68a-4d83-4b80-93cb-e8fb592a0884.png)

**Comment by B-Scoots** [comment]
I tried this on Windows 11, and it has the same issue

**Comment by alfredbaudisch** [comment]
It also happens when adding multiple carets and selections manually with ALT+Double Click the words.

I thought it would be part of #67644, but it's part of the base multi-carets implementation.

**Comment by alfredbaudisch** [comment]
@Paulb23 I found where the issue happens:

When backspacing with multiple carets, `CodeEdit::_backspace_internal(int p_caret)` is called https://github.com/godotengine/godot/blob/master/scene/gui/code_edit.cpp#L684, the selection is processed:
```
	if (has_selection()) {
		delete_selection();
```

But then for every caret before the last one, this line is also called, removing one additional character to the left: https://github.com/godotengine/godot/blob/master/scene/gui/code_edit.cpp#L739

Only for the last caret that that L739 is not called.
