### ISSUE TITLE
`ESC` should cancel multi-carets in the script editor

### ISSUE THREAD

**Issue by BeayemX** [godotengine/godot#67991]
### Godot version

v4.0.beta.custom_build [11e1bac76]

### System information

Linux Fedora - Godot Engine v4.0.beta.custom_build.11e1bac76 - https://godotengine.org Vulkan API 1.2.0 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1080

### Issue description

Currently there is no way to return to a single caret after using multiple carets by only using the keyboard.

In VSCode this is done by pressing `esc`.

### Steps to reproduce

1. Open a script file in the text editor
2. Use `shift + d` to select multiple text occurrences and create multiple carets (or hold `alt` while clicking at different positions)
3. Press `Esc` 
4. See that there are still more than one caret

**Comment by Calinou** [comment]
cc @alfredbaudisch – would you be interested in taking a look at this? :slightly_smiling_face:

**Comment by alfredbaudisch** [comment]
@Calinou I'll take a look 🙂
