### ISSUE TITLE
Weird behavior with multi-carets in script editor

### ISSUE THREAD

**Issue by BeayemX** [godotengine/godot#67993]
### Godot version

v4.0.beta.custom_build [11e1bac76]

### System information

Linux Fedora - Godot Engine v4.0.beta.custom_build.11e1bac76 - https://godotengine.org Vulkan API 1.2.0 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1080

### Issue description

Multi carets are cancelled if clicking outside of selection.
Multi carets are placed at the end of the selection if clicking inside of the selection.

### Steps to reproduce

Given a multi-selection like this:
![image](https://user-images.githubusercontent.com/3453076/198749632-70fb0077-eea5-405b-9e79-5ee6164b37ab.png)

**Expected**
When using a mouse click (without holding any modifier-key) outside of the selection, the multi-selection is cancelled.

**Unexpected**
When using a click inside of any of the selected texts, all carets persist but are placed at the end of the selected area.

**Comment by alfredbaudisch** [comment]
This started annoying recently alongside #67992. If I saw this earlier I would've pushed together with the fix in #68282. But I'll investigate and start a new PR to fix this one then.

**Comment by alfredbaudisch** [comment]
I want to ammed this issue. For a selection with a single caret, after clicking to deselect the cursor should go to the clicked position, but it either goes to the beginning or end of the selection, which is not consistent with other text editors.


https://user-images.githubusercontent.com/248383/200185086-7989cf71-1444-4bfd-ba12-ea616664db8f.mp4
