### ISSUE TITLE
Can we have an option to pull in androidmanifest chunk from project folder

### ISSUE THREAD

**Issue by vinod8990** [godotengine/godot#6800]
I found that the manifest is populated here

https://github.com/godotengine/godot/blob/master/platform/android/SCsub

But I am not that experienced to do this.

Because many android modules like googleplay services require custom properties in manifest file, this should ease the process I think.

**Comment by volzhs** [comment]
You can put `AndroidManifestChunk.xml` file in your module.
It will be merged when making templates.
Here is an example module for Google Play Service module for godot.

https://github.com/ranmaru90/Play-Game-Services-Android-Module-for-Godot

**Comment by vinod8990** [comment]
Yes, I know that. But the problem is that the project specific ids and such things are bound to the module. So every project require different export templates to be created. I was looking for simplifying things here.

For eg: If our most projects require only google iap, admod, gpg. Then we can create one export template and we can use that for all projects. We only need to change the app id in the manifest, which resides in the project folder.

**Comment by vinod8990** [comment]
I think that the above file is for creating export templates but the real export is done in this file
https://github.com/godotengine/godot/blob/master/platform/android/export/export.cpp

I am thinking like this.
The module already has a chunk xml but inside the module creator can have a $$CUSTOM_XML_CHUNK$$ string and the export should replace this string with the string that is defined in a file in the project folder.

Anyway the export.cpp file is too complicated for me.

**Comment by Noshyaar** [comment]
I'm not familiar with android export process. Can anyone confirm about the absence of feature?

**Comment by Calinou** [comment]
Is this covered by the new Android export system? See [Custom builds for Android](https://docs.godotengine.org/en/latest/getting_started/workflow/export/android_custom_build.html) in the documentation.

**Comment by akien-mga** [comment]
Yes, you can customize any part of the AndroidManifest from your project folder now.
