### ISSUE TITLE
[4.0] Can't use existing class function with a custom return type for property getter

### ISSUE THREAD

**Issue by ClarkThyLord** [godotengine/godot#68001]
### Godot version

Godot 4.0 beta 3

### System information

Windows 10

### Issue description

GDScript marks an error when using existing class function with a custom Object return type for property getter, this is despite both the property and the function return type being the same custom type. The error marked is along the lines of:
`Function with return type "GDScript" cannot be used as getter for a property of type "{NameOfCustomTypeHere}".`

As seen below:
![image](https://user-images.githubusercontent.com/17155529/198812570-7ba2a631-2688-4f5b-843a-c7b2546cf992.png)

### Steps to reproduce

1. Open example project
2. Open example.gd
3. Errors at each variable declaration using existing class function with a custom return type for property getter:
```
Line 3: Function with return type "GDScript" cannot be used as getter for a property of type "CustomObject".
Line 8: Function with return type "GDScript" cannot be used as getter for a property of type "CustomNode".
```

### Minimal reproduction project

[example.zip](https://github.com/godotengine/godot/files/9892910/example.zip)

**Comment by adamscott** [comment]
I confirm this issue. I also submitted a PR to fix it.
