### ISSUE TITLE
icon problem in android, app icon get croped

### ISSUE THREAD

**Issue by hani09876** [godotengine/godot#68011]
### Godot version

godot 4 beta 3 

### System information

android

### Issue description

i am exporting my game on android . There i am getting this error ... 
![image](https://user-images.githubusercontent.com/92350126/198822575-8b88a47e-4846-48c3-b3ff-d7359819ac24.png)

 another error is i my app icon size is 192*192 .when i export my app on android the app icon get cropped and bigger..

### Steps to reproduce

i dont know..

**Comment by Akylzhan** [comment]
@hani09876 I think the error is related to your code in `sceneCode/autoload.gd`'s `store_var` function. Are you trying to write something to a file? If so, try enabling "Write External Storage" permissions in Export->Options window of android.

![image](https://user-images.githubusercontent.com/28390596/201480350-c3a43424-a5be-4ef1-82c8-fdf7da6878d4.png)

**Comment by hani09876** [comment]
> @hani09876 I think the error is related to your code in `sceneCode/autoload.gd`'s `store_var` function. Are you trying to write something to a file? If so, try enabling "Write External Storage" permission in Export->Options window of android.
> 
> ![image](https://user-images.githubusercontent.com/28390596/201480350-c3a43424-a5be-4ef1-82c8-fdf7da6878d4.png)
> 

No that isn't the solution.. i have another project that doesn't use any data saving system has the same error

**Comment by Calinou** [comment]
This is how [Android adaptive icons](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive) work by design. You need to have margin added to the icon image itself, as Android will crop it automatically.

The warning message you see in adb has nothing to do with the Android app icon and can be ignored.

**Comment by hani09876** [comment]
> This is how [Android adaptive icons](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive) work by design. You need to have margin added to the icon image itself, as Android will crop it automatically.
> 
> The warning message you see in adb has nothing to do with the Android app icon and can be ignored.

Then this problem can be solved by this way.
1. Create a background of 192*192
2. Make your icon size 100*100. Then place the icon on the middle of the background..
