### ISSUE TITLE
[4.0 beta3] Attach script does not detect custom Node type

### ISSUE THREAD

**Issue by atngames** [godotengine/godot#68014]
### Godot version

4.0 beta3

### System information

linux

### Issue description

Whenever one attaches a script to a Node, godot should detect the type of the Node automatically.
It works for built-in Nodes, but not for custom nodes defined with class_name.

### Steps to reproduce

See minimal project included below

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/9893481/test.zip)

**Comment by timothyqiu** [comment]
Templates are searched along the inheritance chain. i.e. it searches templates for `Node2D`, `CanvasItem`, `Node`, and `Object` when you're attaching a script for `Node2D`.

In the MRP, the node named `MyClass` is a `Node`, so the script inherits from `Node` by default. Thus only templates for `Node` and `Object` are shown.

If you change "Inherits" from `Node` to `MyClass`, your template is shown in the list:

![ksnip_20221029-205040](https://user-images.githubusercontent.com/372476/198832466-381a5752-3843-4a18-9f0f-132e3c20fcc9.png)

**Comment by atngames** [comment]
Thanks for your answer.

I noticed that if I changed inherits, it works as expected.

But this is not the expected behaviour.
The node "MyClass" is of type Myclass (if I let my mouse over the node, it says type: Myclass, not type: Node). The expected behaviour would be that inherits is filled with MyClass, not Node.

**Comment by timothyqiu** [comment]
In this case, I think the "Extend Script" in the context menu is for you.

The node is still a plain `Node`, it's a `MyClass` because the attached script. Choosing "Attach Script" will change the script attached, so the editor could no longer assume it's a `MyClass`.

**Comment by atngames** [comment]
Oh, I get it now.

It still feels... incorrect ?
I mean, the whole process is to have me create a new global class. I did not attach a script to the MyClass node, therefore, it felt natural to attach a new script and not extend the current one.
I use it for a plugin. I expect the users of the plugin to think of their Nodes as regular nodes and therefore to attach a script, not extend the current script. I'll deal with that anyway and document it in the plugin.

Thank you for your time !
What would be the best way to have a discussion on this problem ? Or has this discussion already happened ?
