### ISSUE TITLE
GDScript 2.0: When assigning a function to a variable before function results in a lot of errors when pressing "Ctrl".

### ISSUE THREAD

**Issue by SleepingPhoenix1** [godotengine/godot#68017]
### Godot version

4.0.beta3

### System information

Windows 10, Forward+, RX Vega 56

### Issue description

In any script when assigning a function to a variable before the function results in an error when pressing the key "Ctrl" in the script editor or when starting the project: "modules/gdscript/gdscript_analyzer.cpp:668 - Parser bug (please report): tried to assign unset node without an identifier.". Works in latest version of Godot 3. 

### Steps to reproduce

1.Create a project
2.Create a script for any node
3.Create a variable and a function below it, assign the function to a variable
4.press "Ctrl" in the editor or start the project

### Minimal reproduction project

[Editor_bug.zip](https://github.com/godotengine/godot/files/9893770/Editor_bug.zip)

**Comment by adamscott** [comment]
Here's the two scripts included in the MRP:
```gdscript
# Normal script
extends Node2D

func bar():
	return "bar"

var foo = bar()

func _ready():
	print(foo)
```
```gdscript
# Error script
extends Node2D

var foo = bar()

func bar():
	return "bar"

func _ready():
	print(foo)
```

These two scripts are not valid GDScript scripts per se. `bar()` cannot be called like this, neither be assigned to a variable, as it's not a static function. Hence the error.
