### ISSUE TITLE
local:// totally broken in load()

### ISSUE THREAD

**Issue by gau-veldt** [godotengine/godot#6801]
**Operating system or device - Godot version:**
linux x11 HEAD (12843167cacf3bacca32c29b7ea8b4426392bad0)

**Issue description** (what happened, and what was expected):
load fails on any local:// path
since some recent update load no longer works on absolute paths without prepending local:// however the big problem is that local:// doesn't seem to work either.  My server just lost its only way to access external enduser-supplied resources (which is not part of the project nor its hidden 'savegame' directory which is already broken due to #6047 if any symlinks occur along user://'s real directory path [I was also using absolute paths to work around #6047 via OS.get_data_dir()]).  Now all means of loading external files are gone!!!

**Steps to reproduce:**
![screenshot](https://cloud.githubusercontent.com/assets/1862162/19324122/deb61c98-9074-11e6-92fd-b3946dc1a462.png)

**Link to minimal example project** (optional but very welcome):
see _ready() in the screenshot (it's two lines and a sample dir sturcture to test with is shown)
duplicate with:

`sudo mkdir /test`
`sudo ln -s /test /symtest`
`sudo chown me:me /test`
`sudo chown -h me:me /symtest`
(where me is the user you run godot apps with)
`echo -e "extends Node\n\nfunc _ready():\n\tpass\n" >/test/test1.gd`
`cp /test/test1.gd /test/test2.gd`

in Godot:

```
func _ready():
    var a=load("local://test/test1.gd")
    var b=load("local://symtest/test2.gd")
```

**Comment by Faless** [comment]
You are right, "local://" is broken, a fix is under way, hold tight :)

**Comment by Faless** [comment]
Turns out "local://" was not supposed to be there at all. I'll try to re-enable absolute paths, I'll take extra care to ensure that they works as intended to avoid confusion like in #3106 and #4280 and I'll remove all reference to "local://".

**Comment by gau-veldt** [comment]
@Faless you'll also have to revert #6702 to allow /absolute/path/to/file.txt work again without crashing the game on an error
