### ISSUE TITLE
Emoji is not displayed in Output (console)

### ISSUE THREAD

**Issue by pohy** [godotengine/godot#68026]
### Godot version

4.0.beta.3

### System information

Windows 10 Pro 21H2

### Issue description

If I try to `print_debug(...)` a message containing emojis they are not rendered.  
Instead a box (with the character code?) is displayed.  

![image](https://user-images.githubusercontent.com/2036806/198843174-178d1284-f341-4c0e-9fae-3b18dbbdd04b.png)

### Steps to reproduce

In GDScript:
`print_debug("😁👍❓🎉")`

**Comment by PhoenixFlame101** [comment]
Looks like it's being discussed at https://github.com/godotengine/godot-proposals/issues/916, and right now the only issue (for emoji in strings and comments) seems to be a lack of a monospace font with a suitable license and coloured emoji support.

As a workaround, you can use a font that fits your needs by changing the code editor font manually. Feel free to mention any fonts that may have a fitting license, as my short search didn't yield anything promising.

**Comment by Calinou** [comment]
Now that [system fonts can be loaded](https://github.com/godotengine/godot/pull/62973) (4.0 only), it should be possible to add the system's emoji font as a fallback font throughout the editor (in the main font, code font and output font).

**Comment by bruvzg** [comment]
> it should be possible to add the system's emoji font as a fallback font throughout the editor (in the main font, code font and output font).

For some system fonts (Noto Color / Twemoji) it might need https://github.com/godotengine/godot/pull/64530, but at least default Apple and Windows 10 emoji fonts are bitmap, so it's should be easy to do.
