### ISSUE TITLE
Massive discrepancy in memory usage between systems, with the same scene unplayable dependent on system

### ISSUE THREAD

**Issue by LakshayaG73** [godotengine/godot#68021]
### Godot version

4.0 beta 3, 4.0 beta 2

### System information

Windows 10 home

### Issue description

We are a small 2-person team working on an indie project. 

There is a scene, with some 2D assets, and few static bodies + a characterbody. 

When I try to play the scene, this is what I see on my memory monitor:
<img width="387" alt="image" src="https://user-images.githubusercontent.com/1243371/198838868-dcfb1fd3-b4c2-4c1d-aa88-e47d0961a797.png">

When my colleague tries to play the same scene, the memory usage increases until he has to force quit godot:
![image](https://user-images.githubusercontent.com/1243371/198838901-9be88b8a-d0c1-4ead-907b-3939a4c56c94.png)

If there is a memory leak, why is it only affecting his system? 

My system, without memory issues -:
Windows 11, 64GB RAM, intel 12th gen, RTX 3090

His system, with issues -: 
Windows 10, 32GB RAM, Ryzen 5 3600, RTX 3060

Sometimes, starting the same scene can cause some initial lag, where the game starts at 55 fps. Sometimes it starts at 60. This is a simple 2D game. No way it should ever be at 55 fps on a high end machine. What is going on? 

### Steps to reproduce

Memory usage and performance inconsistencies in godot 4

**Comment by Calinou** [comment]
@LakshayaG73 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by LakshayaG73** [comment]
@Calinou after some debugging, it seems that the issue is that Godot is using GPU - Copy, which is odd. We have set it to use the advanced processor in Windows Graphics settings, for all the beta versions. However, all of the beta versions continue to use GPU - Copy. Is there any other way to force Godot to use the right card?

**Comment by Calinou** [comment]
> However, all of the beta versions continue to use GPU - Copy. Is there any other way to force Godot to use the right card?

"GPU - Copy" is an operation, not the name of a graphics adapter.

Godot already prefers to use the dedicated GPU when available out of the box, but you can override the selected GPU using the `--gpu-index` [command line argument](https://docs.godotengine.org/en/latest/tutorials/editor/command_line_tutorial.html).

**Comment by LakshayaG73** [comment]
https://devblogs.microsoft.com/directx/gpus-in-the-task-manager/

Actually, it refers to the 'engine' being used by the operating system on the GPU. 

The message we saw was GPU 0 - Copy, which indicates that it was using the Copy Engine, that too on the integrated graphics card. This is even though all the settings point to Godot using GPU 1 -> The 3060.

**Comment by LakshayaG73** [comment]
My apologies, it is using the right GPU, but it seems to be using the 'Copy' engine. Not sure...

**Comment by LakshayaG73** [comment]
Ok. So this is quite arbitrary. Sometimes the memory issues also occur on my machine. They seem to be tied to a specific commit where we introduced an AI character, but the character is not doing anything special. 

They are performing a few operations per second, but sometimes this causes small dips in fps for me, and sometimes it does not.

Is there a way to do some in depth performance profiling?

**Comment by LakshayaG73** [comment]
So. I did this, and I can't seem to pinpoint any issue. The reason is that the CPU usage is not the issue at all. It stays < 5% in both systems. 

Now i'm thinking this has to do with rendering canvas items. 

I'm seeing 12GB of VRAM usage on an exported template of the game. Which is basically one room, with one character and an enemy. 

What I really need is the 'VRAM usage by resource" tab working. Any idea when that will be up and running? : ) 

I will do some more tests.

**Comment by Calinou** [comment]
> I'm seeing 12GB of VRAM usage on an exported template of the game. Which is basically one room, with one character and an enemy.

How large are your textures? I recommend sticking to 2048×2048 textures or lower. The benefit of 4K textures is often debatable in practice (with rare exceptions).

> What is texture streaming and is the lack of the same the issue?

Texture streaming is only needed in projects that have thousands of large textures. It's unlikely you need it at your scale.

**Comment by LakshayaG73** [comment]
Ok. So the VRAM is definitely the issue, and it is bleeding into the RAM somehow. 

To reduce the VRAM, I am creating AtlasTextures. https://godotengine.org/article/atlas-support-returns-godot-3-2

This should help for now, until we decide on a size for the textures.

**Comment by LakshayaG73** [comment]
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/1243371/199984312-63cefe4d-17f2-4329-ae66-9f1ce41ec01e.png">

I'm seeing this crop up a lot, and the engine is behaving a little slower since I started adding atlas textures.

Any idea how I could fix this?

**Comment by akien-mga** [comment]
Did you mean to close this?

**Comment by LakshayaG73** [comment]
I've created a new issue to discuss the above: https://github.com/godotengine/godot/issues/68256
Not sure if that is proper, or it should be discussed here. 

I'm hopeful that adding atlas textures will resolve this issue, but until I have proof I will keep it open. Thanks.

**Comment by Calinou** [comment]
> I'm hopeful that adding atlas textures will resolve this issue, but until I have proof I will keep it open. Thanks.

Atlas textures are useful for 2D games where you have animated spritesheets with wildly varying sprite sizes. They are not useful in 3D projects.

**Comment by LakshayaG73** [comment]
My project is 2D. Apologies if that wasn't clear. 

Using atlas textures has gotten my VRAM usage to ~30%, but now there is another issue. Which is linked above. 

Closing this.

**Comment by SteveSmith16384** [comment]
Was the cause found as to why the same program used different amounts of memory on different PC's?
