### ISSUE TITLE
Setting direction of Particles2D through GDscript uses degrees and not radians

### ISSUE THREAD

**Issue by lukaskotik** [godotengine/godot#6803]
**Operating system or device - Godot version:**
Godot v2.1

**Issue description** (what happened, and what was expected):

`Particles2D.set_param(Particles2D.PARAM_GRAVITY_DIRECTION, angle)`
requires `angle` to be in degrees and not in radians (as stated in help)
The same holds for `PARAM_DIRECTION`.

**Comment by WalasPrime** [comment]
I wonder if PARAM_INITIAL_ANGLE is also degrees and not radians...
