### ISSUE TITLE
Using fill() in an Array[Array] will fill the Array with reference to a single Array

### ISSUE THREAD

**Issue by Pizza-Script** [godotengine/godot#68032]
### Godot version

v4.0.beta3.official [01ae26d31]

### System information

Windows 10

### Issue description

When using fill() on an Array[Array], it will fill the Array with reference to a single Array.

Thus when changing a single item, it will change all of the other items.

### Steps to reproduce

See code and minimal project included below

### Minimal reproduction project

```
extends Node

var my_array: Array[Array]

func _ready() -> void:
    my_array.resize(4)
    my_array.fill([0, 1, 2, 3])
	
    my_array[0][0] = 5 
    print(my_array)
```
Result
will change all 1st item of all arrays
[[**5**, 1, 2, 3], [**5**, 1, 2, 3], [**5**, 1, 2, 3], [**5**, 1, 2, 3]]
             
Expected
change the 1st item of the 1st array only
[[**5**, 1, 2, 3], [**0**, 1, 2, 3], [**0**, 1, 2, 3], [**0**, 1, 2, 3]]

	
[Array[Array].zip](https://github.com/godotengine/godot/files/9894461/Array.Array.zip)

**Comment by Pizza-Script** [comment]
As a current workaround, I use duplicate() to ensure that a new array is passed - 

extends Node

var my_array: Array[Array]

func _ready() -> void:
    my_array.resize(8)
    for a in range(my_array.size())
        my_array[a] = [0, 1, 2, 3].duplicate()

**Comment by alexamy** [comment]
It isn't a bug. `Array` is passed by reference, according to [docs](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_basics.html#built-in-types):
```
Arrays and Dictionaries, which are passed by reference so they are shared.
```

Btw you dont need to call `duplicate()` in second example, you are creating a new array on every loop cycle.

**Comment by Pizza-Script** [comment]
I see, thank you, was able to confirm that `duplicate()` was not needed.
But the fill() behavior is still feels a bit weird to me.

`my_array.fill([0, 1, 2, 3])`

should be a shorthand for - 

```
for a in range(my_array.size()):
        my_array[a] = [0, 1, 2, 3]
```

or should it not?

**Comment by thehatless** [comment]
fill() is equivalent to

```
var b = [0, 1, 2, 3]
for a in range(my_array.size()):
        my_array[a] = b
```

Almost, but not quite, the same. :)

**Comment by kleonc** [comment]
I agree that's expected behavior. I guess adding a note in the `Array.fill`'s docs about how it behaves when a reference type is passed in might be a good idea.

**Comment by Pizza-Script** [comment]
Thank you !
