### ISSUE TITLE
InputEventKey unicode wrong value on windows

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#68031]
### Godot version

v4.0.beta3.official [01ae26d31]

### System information

Windows 10, i9900KF, RTX 2070S

### Issue description

On windows, when a Key is released, the unicode from InputEventKey.unicode reads 0.

While on Linux and Mac the unicode character remains the same as on the key being depressed.

### Steps to reproduce

```
func _unhandled_input(event: InputEvent) -> void:
	
	if event is InputEventKey and event.pressed:
		printt("key down: ", event.unicode)
	
	if event is InputEventKey and not event.pressed:
		printt("key up: ", event.unicode)

```
**Windows Output:**
```
key down: 	100
key up: 	0
key down: 	115
key up: 	0
key down: 	119
key up: 	0
```
**Ubuntu 22.04 Output:**
```
key down: 	100
key up: 	100
key down: 	115
key up: 	115
key down: 	119
key up: 	119
```

**Comment by Sauermann** [comment]
Have a look here: #56544

**Comment by TheDuriel** [comment]
Duplicate of #56544
