### ISSUE TITLE
Godot on WSL: libasound.so.2: undefined symbol: snd_dlpath

### ISSUE THREAD

**Issue by XsongyangX** [godotengine/godot#68043]
### Godot version

v3.5.1-stable_mono_x11.64

### System information

Windows 11 with WSL 2

### Issue description

When I launch the Godot executable in WSL, the program launches with an error message about an undefined symbol. The error does not crash the program. It however makes a segmentation fault when exiting Godot.

```
[21:32:39] song@DESKTOP-CBDKVRK:~/installations/Godot_v3.5.1-stable_mono_x11_64$ ./Godot_v3.5.1-stable_mono_x11.64
Godot Engine v3.5.1.stable.mono.official.6fed1ffa3 - https://godotengine.org

================================================================

================================================================
OpenGL ES 3.0 Renderer: D3D12 (NVIDIA GeForce RTX 3070 Laptop GPU)
Async. shader compilation: OFF
/lib/x86_64-linux-gnu/libasound.so.2: undefined symbol: snd_dlpath

Mono: Log file is: '/home/song/.local/share/godot/mono/mono_logs/2022-10-29_21.32.41_4577.log'
Segmentation fault
```

### Steps to reproduce

1. Download the 64-bit Mono version of Godot for Linux.
2. Extract and copy the files on WSL.
3. Add permissions to the executable.
4. Run it.
5. Close the program.

**Comment by Calinou** [comment]
Does using the `--audio-driver ALSA` or `--audio-driver Dummy` command line arguments prevent this? (`Dummy` will disable audio output entirely.)

**Comment by akien-mga** [comment]
What makes you think that the segmentation fault is related to this message?

This message is harmless and can be ignored, it shouldn't impact anything.

**Comment by Calinou** [comment]
> What makes you think that the segmentation fault is related to this message?

It's worth [compiling a debug build](https://docs.godotengine.org/en/stable/development/compiling/index.html) and running a debugger on it to check the source of the crash.

**Comment by XsongyangX** [comment]
Sound is not supported on WSL 2 for now.
https://github.com/microsoft/WSL/issues/5816

**Comment by XsongyangX** [comment]
I'll close this issue, until the problem replicates when WSL supports sound output.

**Comment by bruvzg** [comment]
> snd_dlpath

Godot do not use this symbol (and it is not loading it in the current version), so it almost certainly not related to the crash (ALSA in general might be).
