### ISSUE TITLE
RegEx.search misbehaves for start anchor when offset given

### ISSUE THREAD

**Issue by svn133** [godotengine/godot#68058]
### Godot version

4.0.beta3

### System information

macOS 12.5.1 (21G83), MacBook Pro (2020, intel)

### Issue description

I've used the RegEx class for expressing scanners as part of a small tokenizer utility. For those, I configured the expressions by using a start-anchor (i.e. `^` at beginning of regex pattern). As part of the scanning behaviour I have a potentially longer input text string (source) and a "current position" index value, indicating the start position of the next token to be scanned in the source.

I used the function `RegEx.search(source, position)` to test if one of the scanner patterns matches the source on the specified position. Unexpectedly the function returned null as soon as position was larger than 0.

Did I misunderstood the semantic of the offset argument on that function? From reading the documentation, it seems to indicate, that using an offset should basically limit the scope of the input text, against which the regex is fired.

<img width="659" alt="RegEx_search_documentation" src="https://user-images.githubusercontent.com/114500633/198891391-4e4dfe1c-d31d-4fff-98ad-336b15962cc9.png">

The following isolated code should highlight the problem, I would expect both cases to resolve to the same output, but the one with offset 3 is resolving to null instead. Removing the "start-anchor" resolves in a non-null output, albeit not the one I'm looking for in the general case.

<img width="286" alt="RegEx_search_offset_misbehaving" src="https://user-images.githubusercontent.com/114500633/198891526-04a6d32f-6a72-4d3e-9a3d-eac926b867da.png">

Is the "start-anchor" not handled correctly for offset > 0?

### Steps to reproduce

```
var input = "xxxfooyyy"
var regex = RegEx.new()
regex.compile("^foo")
var res1 = regex.search(input, 3)
print(res1) # null (!)
var res2 = regex.search(input.substr(3))
print(res2) # the expected match
```

**Comment by timothyqiu** [comment]
This is expected behavior according to the underlying [PCRE documentation](https://www.pcre.org/current/doc/html/pcre2api.html).

> A non-zero starting offset is useful when searching for another match in the same subject by calling `pcre2_match()` again after a previous success. Setting `startoffset` differs from passing over a shortened string...

The `offset` parameter behavior should be documented.

**Comment by svn133** [comment]
Thanks for the quick clarification.

After re-reading the documentation again, with the intentional behaviour: I think it can even be understood in the desired way... but my initial reading of it totally pushed me into the other interpretation. The part about "without modifying where the start and end anchor would be" can be understood in both directions, so maybe replacing that with a more precise phrasing would help here.
