### ISSUE TITLE
Vulkan: Rendering pixel art adds more colors between pixels

### ISSUE THREAD

**Issue by RoniPerson** [godotengine/godot#68053]
### Godot version

4.0.beta3

### System information

Windows 10, Vulkan, AMD Ryzen 3 with Radeon Vega 8 Graphics

### Issue description

I tried to port an pixel tileset from Godot 3 to 4. When I run the project the diffrent colored region of the tile set seemed somewhat elevated this did not happen in Godot 3. I took a screenshot of my computer screen and opend it in an image viewing programm to find out what was going on.
When zoomed in I found the following:
![grafik](https://user-images.githubusercontent.com/67514656/198881328-bafaf905-14a2-44cb-be3f-1e19b40c4e65.png)
Between the diffrent colored regions there are colors, that are not in the original image.

This is due to the Vulcan renderer. When switching to the opengl renderer on 4.0 it looks like this:
![grafik](https://user-images.githubusercontent.com/67514656/198881424-96225f8c-6c5f-4484-8426-6efeba95895b.png)
Crisp pixel art as expected.

Maybe I am just missing some settings. But it feels wrong, that it works with one renderer and not with the other one.

### Steps to reproduce

- add an pixel image into a scene
- run the project
- take a screenshot
- open the screenshot with an image viewing programm that has no filtering
- zoom in and look at the transition between diffrent colors

- switch the renderer to opengl and try again

### Minimal reproduction project
[pixel_bug.zip](https://github.com/godotengine/godot/files/9896737/pixel_bug.zip)
This project contains a setup with which I can reproduce the bug. The screenshot is taken with an external program (I am using Snipping Tool). The effect can not be observed when using `get_viewport().get_texture().get_image()` and saving it to disk.

**Comment by RoniPerson** [comment]
> have you tried disabling mipmaps?

In the import settings `Mipmaps>Generate` is turned off. Is this what you mean? Or is there another option to disable it?

**Comment by clayjohn** [comment]
Could you please upload an MRP so other contributors can assist by reproducing the issue?

**Comment by RoniPerson** [comment]
> This is likely caused by your graphics driver applying a sharpening filter. AMD on Windows has a tendency have this feature enabled; check your AMD Adrenalin control panel.

This was infact the issue. Thanks for the hint.
