### ISSUE TITLE
Use Physical Light Units completely break the lighting

### ISSUE THREAD

**Issue by krupitskas** [godotengine/godot#68052]
### Godot version

v4.0.beta3.official

### System information

Windows 11, Vulkan, Nvidia 3060M, 526.47 driver

### Issue description

When I enable "Physical Light Units" in the project settings and adding world environment node, I receive complete white scene and I dont know how to get rid of it
Before node beign added:
![image](https://user-images.githubusercontent.com/5683877/198880261-9fa45126-8825-4a98-81ed-9f9430ac7d5b.png)
After addition:
![image](https://user-images.githubusercontent.com/5683877/198880260-67c28560-500c-4258-9778-dc5a92acb5fe.png)
After configuring physical based sky for background:
![image](https://user-images.githubusercontent.com/5683877/198880290-3fc3aea6-eed9-4246-b9b2-1114030dcf21.png)

### Steps to reproduce

Load any object on scene
Enable Physical Light Units in the project settings
Add world environment node

**Comment by Calinou** [comment]
cc @clayjohn

**Comment by clayjohn** [comment]
What are your exposure settings? Note that the default DirectionalLight3D brightness matches the sun, so you need to properly expose the scene or it will appear over bright

**Comment by krupitskas** [comment]
> What are your exposure settings? Note that the default DirectionalLight3D brightness matches the sun, so you need to properly expose the scene or it will appear over bright

So DirectionalLight3D itself works good, I can control lux'es and kelvins and scene looks nice. Problem appear only after WorldEnvironment node addition.
Exposure is Linear and 1
Any tonemap modes give the same result and changing exposure value doesnt help.

**Comment by clayjohn** [comment]
@krupitskas Exposure settings are set in the CameraAttributes in the WorldEnvironment. 

You need to add a CameraAttributes resource to your WorldEnvironement when using PhysicalLightUnits. Otherwise the default settings will appear way too bright

**Comment by krupitskas** [comment]
Ah yeah. It's fixed that. Thank you. I actually didnt see it at all under the all environment parameters.

![image](https://user-images.githubusercontent.com/5683877/199068457-e7fd6d6d-6cbd-4d97-93b0-7a8e7211aa5e.png)

I think its quite undesired behaviour when you switch to physical light units and receive complete white scene. Maybe we can add alert triangle to the Camera Attributes field to ask user not to forget to set this up?

**Comment by clayjohn** [comment]
> I think its quite undesired behaviour when you switch to physical light units and receive complete white scene. Maybe we can add alert triangle to the Camera Attributes field to ask user not to forget to set this up?

That could work. The only challenge will be that you can also set the CameraAttributes on the Camera3D itself, in which case the error would be wrong to show.

**Comment by krupitskas** [comment]
I would like to contribute here actually to get into godot development!
Can we have something like default CameraAttribute parameters if nothing set nowhere?
If we can't then if there a WorldEnvironment node with Environment set but no Camera Attributes set - everything white
If we add Camera3D, set same environment - camera3d also white. But if we add CameraAttributes to the Camera3D, then viewport will be white but Camera3D Preview will be fixed.

I fill like there can be this two solution or default CameraAttributes or alert triangle

**Comment by clayjohn** [comment]
Fixed by https://github.com/godotengine/godot-docs/pull/6390
