### ISSUE TITLE
apply_torque on RigidBody2D does not work if bodys CollisionShape2D is disabled

### ISSUE THREAD

**Issue by compmstr** [godotengine/godot#68068]
### Godot version

v4.0.beta3.official [01ae26d31]

### System information

Linux (Pop OS), NVIDIA GeForce RTX 2060, Video Drive v 470.141.03

### Issue description

If the CollisionShape2D under a RigidBody2D is disabled, using `apply_torque` in `_integrate_forces` or `_physics_process` does not appear to work.  

`apply_force` still works fine, which is what leads me to think this is a bug.

### Steps to reproduce

- Have` a `RigidBody2D` with a `CollisionShape2D`
- Have the ability to move straight (via `apply_force`), and rotate (via `apply_torque`)
- Disable the `CollisionShape2D`
- Notice that the `apply_force` call still works, but `apply_torque` does not.

In the example repro project:
- `w` thrusts
- `a` turns left
- `d` turns right
- `c` disables collision

I set it up to show debug collision shapes to better see what state the RigidBody2D is in.

### Minimal reproduction project

[RigidBodyRotateBugRepro.zip](https://github.com/godotengine/godot/files/9897214/RigidBodyRotateBugRepro.zip)

**Comment by rburing** [comment]
Here is why: https://github.com/godotengine/godot/blob/b6cbea5e58d88c2b554fc0429ab44abec3f174ae/servers/physics_2d/godot_body_2d.cpp#L590-L591

The change in linear velocity uses the (inverse) mass, but the change in angular velocity requires the (inverse) inertia. The mass is always defined via a property, but the (inverse) inertia is by default computed based on the shapes. It becomes zero when there are no shapes, which explains why applying torque does not work.

You can override the inertia by setting the `RigidBody2D`'s [`inertia` property](https://docs.godotengine.org/en/latest/classes/class_rigidbody2d.html#class-rigidbody2d-property-inertia) above zero, e.g. in the minimal reproduction project set it to `1830` to make it work as if the collision shape was still there.

**Comment by compmstr** [comment]
Thank you so much, that makes sense.

Putting some code examples in for if anyone else has this same issue.

To set it up with disabled shapes, it looks like I can do:
```
var orig_inertia = inertia
collision_shape.disabled = disable_collision
if inertia == 0:
	inertia = orig_inertia
```

For now, I'll just update to enabling/disabling the collision masks instead of disabling the `CollisionShape2D`, which also works as I need it to, and seems cleaner.

```
set_collision_layer_value(1, !disable_collision)
set_collision_mask_value(1, !disable_collision)
```
