### ISSUE TITLE
GDScript cannot infer the type of a variable initialized with a typed method call

### ISSUE THREAD

**Issue by rblopes** [godotengine/godot#68069]
### Godot version

v4.0.beta3.official [01ae26d31]

### System information

KDE neon 22.04

### Issue description

(_Sorry in advance if the following bug was reported before, or is already fixed. I couldn't find anything related._)

(_Edit: Added the MRP._)

It seems that the GDScript parser cannot infer the type of a _typed_ user method ahead of its definition.

```gdscript
extends Node

var some_var := some_func()

# NOTE: It doesn't matter if you qualify the method as `static` or not.
static func some_func() -> int:
	return 42
```

The code above will trigger a parser error notification on both the script editor and the debug console, as follows:

```
  modules/gdscript/gdscript_analyzer.cpp:668 - Parser bug (please report): tried to assign unset node without an identifier.
  res://bug_2.gd:3 - Parse Error: Cannot infer the type of "some_var" variable because the initial value doesn't have a set type.
  modules/gdscript/gdscript_analyzer.cpp:668 - Parser bug (please report): tried to assign unset node without an identifier.
  modules/gdscript/gdscript_analyzer.cpp:668 - Parser bug (please report): tried to assign unset node without an identifier.
```

![editor_screenshot_2022-10-30T221805](https://user-images.githubusercontent.com/61425/198912783-540a0d57-bef6-4c86-aac7-0b41831c62fc.png)

For comparison: that same code works on Godot 3.5.

Either declaring the variable after the method or replacing the type inferred assignment (`:=`) works fine.

### Steps to reproduce

Creating a script with the following content on any project triggers the error:

```gdscript
extends Node

var some_var := some_func()

static func some_func() -> int:
	return 42

# func some_func() -> int:
#	return 42
```

### Minimal reproduction project

[68069.zip](https://github.com/godotengine/godot/files/9910850/68069.zip)

**Comment by adamscott** [comment]
I confirm the issue for Godot 4.0.

**Comment by rblopes** [comment]
Still getting the same error messages in Godot 4 beta 7.

**Comment by adamscott** [comment]
CC @rune-scape @anvilfolk

**Comment by anvilfolk** [comment]
I'd be pretty excited to take a look at this one. Recently did a little bit on initializers so it's a part of the code I'm not completely clueless on :)

**Comment by rune-scape** [comment]
i'm sorry to do this to you again @anvilfolk, but my out of order member resolution branch fixes this

**Comment by anvilfolk** [comment]
For a moment I thought this was for a PR that I had already submitted! I started looking into it a little bit but didn't get super far. It makes a ton of sense that PR would fix it!

Curious how you did it! I'm guessing something like parsing non-inferred types or functions first, and inferred types later?

**Comment by rune-scape** [comment]
@anvilfolk i typed up an explanation and thought i sent it, but now its eaten by my browser, ill flesh out the explanation in my PR description

**Comment by anvilfolk** [comment]
Sweet, thank you. It is mostly curiosity, and I'm trying to review the PR now so it gets more upvotes to get merged sooner rather than later! :)

**Comment by Angular-Angel** [comment]
So I had this problem show up again for me, using the Godot_v4.0.2-stable_linux.x86_64 build. I loaded the FPS engine template and tried to run it, and got: `var texture_folder := _devblock_color_to_foldername[block_color_group]`. I was able to fix this easily enough by just changing it to `var texture_folder : String = _devblock_color_to_foldername[block_color_group]`, but it still shows that this bug isn't entirely solved.

**Comment by adamscott** [comment]
> So I had this problem show up again for me, using the Godot_v4.0.2-stable_linux.x86_64 build. I loaded the FPS engine template and tried to run it, and got: `var texture_folder := _devblock_color_to_foldername[block_color_group]`. I was able to fix this easily enough by just changing it to `var texture_folder : String = _devblock_color_to_foldername[block_color_group]`, but it still shows that this bug isn't entirely solved.

What is the type of `_devblock_color_to_foldername`?
