### ISSUE TITLE
Nested loop variables in for loops do not increment properly

### ISSUE THREAD

**Issue by altinaaaaaaa** [godotengine/godot#68071]
### Godot version

3.5stable

### System information

Windows 10

### Issue description

If there are two `for` loops nested, then the second loop variable does not reset when going back up a loop. The loop variable still keeps the old value it ended on from the previous loop. I found this going through the debugger and looking at the stack variables.

### Steps to reproduce

Here is the example function I found it in.

```
func get_indiv_dict(sub):
    var indiv_dict = {}
    var holding_sub_arr = []
    var looking = true
    for h in master_dictionary:
        holding_sub_arr = h["Sub"]
        for i in holding_sub_arr:
            if sub == i and looking:
                looking = false
                indiv_dict = h.duplicate()
                indiv_dict["Sub"].clear()
                indiv_dict["Sub"].append(sub)
                return indiv_dict
```
Here, the variable `sub` is a string that gets passed in to the function. The variable `master_dictionary` is an array holding multiple dictionaries. Each of those dictionaries has a key `"Sub"` which has a value of an array of strings.

The purpose of this function is to take a string, find which dictionary also has that string within its `"Sub"` array, and then return a copy of that dictionary with the value of `"Sub"` replaced with the passed in string.

When the loop reaches the last entry of `holding_sub_arr` and then goes back up to increment `h`, the value of `i` is still whatever string was before. `i` does not get set back to the value of the first index of the new `holding_sub_arr` that is now filled with a different `h["Sub"]`. This causes errors as it cannot correctly compare values in the array `holding_sub_arr` with the passed in string `sub`.

**Comment by TurtleKwitty** [comment]
Trying to replicate but it seems to be working fine for me on 3.5.1-stable Linux

Boiled it down to something that would actively show the error but following the same structure as yours

```
var master_dictionary = [{"Sub": ["test1_1", "test1_2"]}, {"Sub": ["test2_1", "test2_2"]}]
var indiv_dict = {}
var holding_sub_arr = []
for h in master_dictionary:
	print(h)
	holding_sub_arr = h["Sub"]
	for i in holding_sub_arr:
		print(i)
```

seems to give the right values in the expected order

```{Sub:[test1_1, test1_2]}
test1_1
test1_2
{Sub:[test2_1, test2_2]}
test2_1
test2_2
```

**Comment by adamscott** [comment]
@altinaaaaaaa Please join a MRP when submitting issues. Example code is good, but an actual project is way easier to test and debug.

**Comment by altinaaaaaaa** [comment]
After resetting Godot which has been open for 30+ hours and only adding print statements in a few places, I no longer see the issue in the debugger stack variables or encounter the error when the game is running. This seems like an odd one-time bug.
