### ISSUE TITLE
TouchScreenButton does not register short taps on iOS

### ISSUE THREAD

**Issue by BimDav** [godotengine/godot#68078]
### Godot version

3.5.1-stable

### System information

iOS-15.6.1

### Issue description

TouchScreenButtons with an "Action" to press or release in InputDefault don't work with short taps on iOS.

I believe this is because of the touch_delay added for iOs. With touch_delay, short taps are still registered but if I understand correctly presses are sent to InputDefault on the same frame as releases. So downstream calls to Input.is_action_pressed() return false.

### Steps to reproduce

Use a TouchScreenButton connected to an InputDefault action.

Check Input.is_action_pressed() and do short taps on the button.

**Comment by tbveralrud** [comment]
This is fixed testing against https://github.com/godotengine/godot/pull/69200.

**Comment by tbveralrud** [comment]
This bug is fixed with the #69200 merge.
