### ISSUE TITLE
2D End bone deforms uncontrollably

### ISSUE THREAD

**Issue by inabird** [godotengine/godot#68076]
### Godot version

3.4.5 stable fedora

### System information

Fedora Linux 36 (Workstation Edition)

### Issue description

Hello I've been learning how to animate 2D pictures using skeleton,
but found the end bones that are the child of another child do not deform properly.

In my project, the texture **bat 1 wing top** is assigned to two bones: **wing top** and **wing top2**

![Screenshot from 2022-10-31 16-42-44](https://user-images.githubusercontent.com/117072051/198967327-9e059210-dd55-4156-8ad9-4c0eb3d9dcfc.png)

Weights are assigned

![Screenshot from 2022-10-31 15-36-43](https://user-images.githubusercontent.com/117072051/198967388-62426bbc-ee57-4498-bea7-01a29ce8572f.png)
![Screenshot from 2022-10-31 15-36-46](https://user-images.githubusercontent.com/117072051/198967410-e2dd050b-7bbe-4b98-b91f-d0cf85aa9b80.png)

After clicking OK and tried to rotate **wing top 2**, it deforms dramatically, like from 0 and 100 and there is no other options in between

![Screenshot from 2022-10-31 16-45-50](https://user-images.githubusercontent.com/117072051/198967846-18e26159-a6e0-47c2-b9dc-359cdfd14674.png)

Moving or scaling **wing bone 2** is relatively normal though. Rotating **wing top** alone is also fine

![Screenshot from 2022-10-31 16-46-43](https://user-images.githubusercontent.com/117072051/198968328-171282e3-3731-44c7-8ff9-b66cfb646fa2.png)

**wing bottom 2** is also the child of another child but it seems to be doing okay. Neither moving, rotating nor scaling has issue

Here are the values of both bones so I'm confused what caused them like that.

![Screenshot from 2022-10-31 16-57-28](https://user-images.githubusercontent.com/117072051/198970364-3c002be1-3d3c-481a-bc94-76ae0b7d7ed1.png) ![Screenshot from 2022-10-31 16-57-39](https://user-images.githubusercontent.com/117072051/198970384-973da20a-9065-422e-8bb6-28336ad80764.png)

Can someone tell me what I can do to fix **wing top 2**?

### Steps to reproduce

Here are the steps I created **wing top 2** and **wing bottom 2**:

1. Select **bat1** (skeleton2D) node
2. Scene tab > + > Node2D > Bone2D
3. Rename and move them to the right position
4. Parent to the **torso** bone
5. Select **bat1** > Skeleton2D > Rewrite rest pose
6. Select wing top/wing bottom texture > UV editor > draw weights > OK

### Minimal reproduction project

The file size is too big to upload so uploaded to Google drive instead >> https://drive.google.com/file/d/1dQ4HqwKTZwpAs6ulxtOkteUzPgv0DNJR/view?usp=sharing

**Comment by Zireael07** [comment]
Minimal reproduction project should be, well, minimal. Try trimming other scenes until you only have the bat, this should bring it under the limit.

**Comment by inabird** [comment]
> Minimal reproduction project should be, well, minimal. Try trimming other scenes until you only have the bat, this should bring it under the limit.

May I ask how to do that? Sorry I'm super new to Godot and I can't seem to find it in the documents

**Comment by Zireael07** [comment]
Literally make a copy of your project and delete any other scenes that are not the bat. Because I really doubt the bat only is big enough to bring it over the upload limit.

**Comment by inabird** [comment]
Ah I see. I have removed the background image from the folder. Now it is reduced to 12mb from 30mb.
The bone deformation issue is still there though even I removed all the other images.

[bat.zip](https://github.com/godotengine/godot/files/9978658/bat.zip)

**Comment by clayjohn** [comment]
The problem here is that you have incorrectly set up your bones. 

Running the example scene I can see that your "Wing top" bone is totally misconfigured

![Screenshot from 2023-01-27 15-09-34](https://user-images.githubusercontent.com/16521339/215222959-8bdd6ada-67d1-4e7b-a684-4ae42fdf823d.png)

All the values are way out of normal ranges, for example note how the scale on the y-axis is 14,000 while the scale on the x-axis is 4. 

I reset the transforms for "wing top" and "wing top 2" and then dragged them in the editor to where they should go and the wing deformed fine after that.
