### ISSUE TITLE
Mousing over Editor MenuButton causes incorrect selection

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#68084]
### Godot version

v4.0.beta.custom_build [11d74d606]

### System information

Windows 10, Vulkan, i9900KF, RTX 2070S

### Issue description

When interacting with the Editor MenuButtons, Scene, Project, Debug, Editor, Help, the mouse position is incorrectly detected. Menu items are selected while the mouse is visibly on top of other options, or while it is not within the menu whatsoever. Nested dropdowns open on the wrong side as well.

This also affects other uses of Option and MenuButton, like in the File Dock.

This does not happen in a game.

### Steps to reproduce

https://user-images.githubusercontent.com/44248915/199045201-67e15a56-1708-4069-9601-6f6ae722ebb3.mp4

My editor Theme settings are as follows:

![image](https://user-images.githubusercontent.com/44248915/199045358-16660377-0631-4d77-b243-e862402cc9e6.png)

**Comment by Sauermann** [comment]
Possibly introduced in #67903.
Do I assume correctly, that you have `Single Window Mode` Off?

**Comment by TheDuriel** [comment]
> Possibly introduced in #67903. Do I assume correctly, that you have `Single Window Mode` Off?

All settings are at default, so yes that is off.
