### ISSUE TITLE
range value over any builtin type property is broken

### ISSUE THREAD

**Issue by mintyleaf** [godotengine/godot#68093]
### Godot version

4.0.beta3

### System information

Windows 11 22H2, Vulkan, intel hd 520

### Issue description

if you try to get range over builtin type variable (or constant) property, like vector2.x or rect2.size.x and try to do some operations over it - it goes into something like uint value, i guess
![image](https://user-images.githubusercontent.com/17470408/199081241-4634d1c7-cb33-4cef-bd80-2701e0d8c078.png)
![image](https://user-images.githubusercontent.com/17470408/199081257-9c35ac28-593b-42f2-bf97-6b35112c4eef.png)
![image](https://user-images.githubusercontent.com/17470408/199081316-7e1a6822-09f7-406e-a8d6-b26a5d24e81e.png)
![image](https://user-images.githubusercontent.com/17470408/199081337-7d1362df-6316-4984-8b43-8572967ca0ee.png)

however, specified start value fixes that issue
![image](https://user-images.githubusercontent.com/17470408/199087864-f36b03ac-88d1-4258-87ab-68692f31c7e1.png)

### Steps to reproduce

```
extends Node

func _ready() -> void:
	for x in range(Vector2(10, 10).x):
		print(x + x)
	for x in range(Rect2(10, 10, 10, 10).size.x):
		print(x + 10)
```

**Comment by kzerot** [comment]
Confirmed, have that issue too. It can be simpler:
```
	for x in range(10.2):
		print(x)  # prints valid 
		print(x+1) # prints some garbarge
```
Or any other float.

**Comment by kzerot** [comment]
Also, int(x), float(x) also return some random garbarge number:
```
	for x in range(10.2):
		print("int(x)", int(x))
		print("float(x)", float(x))
		print("===")
```
![image](https://user-images.githubusercontent.com/4415061/199102186-00607f12-2b4a-4f5e-8225-ca4137e3a6e3.png)

**Comment by kleonc** [comment]
These are not "some random garbarge number". Each of these is a result of using an integer encoded as a `double` (64-bit float) but decoded as an `int64_t` (64-bit signed integer) when the given operation (here addition) is performed.

```gdscript
for x in range(5.2):
	assert(typeof(x) == TYPE_FLOAT) # Bug, should be `TYPE_INT`.
	var a := PackedByteArray()
	a.resize(8)
	a.encode_double(0, x)
	assert(a.decode_s64(0) + 1 == x + 1)
	prints(x, a.hex_encode(), a.decode_s64(0), x + 1)
```
```
0 0000000000000000 0 1
1 000000000000f03f 4607182418800017408 4607182418800017409
2 0000000000000040 4611686018427387904 4611686018427387905
3 0000000000000840 4613937818241073152 4613937818241073153
4 0000000000001040 4616189618054758400 4616189618054758401
5 0000000000001440 4617315517961601024 4617315517961601025
```
Likely the same / similar cause as #62650.

**Comment by kzerot** [comment]
Not sure it's a right way to fix it, but I played a little and it is working properly:
![image](https://user-images.githubusercontent.com/4415061/199248069-06f1068f-df42-472f-9e51-aebeb9315831.png)
