### ISSUE TITLE
Game crashes when used remote filesystem for resources.

### ISSUE THREAD

**Issue by kboxsoft** [godotengine/godot#681]
When I load remote resources, the game crashes on loading time.
I narrow down and found when net response is data type in FileAccessNetworkClient::_thread_func(), and its FileAccessNetwork fa memory is corrupt, such as fa->page_size is 0, or fa pointer is incorrect.

		FileAccessNetwork *fa=NULL;

		if (response!=FileAccessNetwork::RESPONSE_DATA) {
			ERR_FAIL_COND(!accesses.has(id));
		}

		if (accesses.has(id))
			fa=accesses[id];  //Get FA

...
fa->_set_block(offset,block);  // APP crashed in this function.

**Comment by akien-mga** [comment]
No answer, so archiving as there isn't much that can be done here if it can't be reproduced.
