### ISSUE TITLE
ImmediateMesh ignores specified color

### ISSUE THREAD

**Issue by Cykyrios** [godotengine/godot#68108]
### Godot version

4.0.beta.custom_build [c29fe310f]

### System information

Linux Mint 21, Vulkan, NVidia GTX 1060

### Issue description

When drawing with an ImmediateMesh, the colors passed with `surface_set_color()` are ignored, and all vertices are drawn with the same color. This happens for triangles as well as lines.
In the MRP below, adding an unshaded material in `surface_begin()` results in every vertex being white, otherwise they appear grey. In another project where I use ImmediateMesh, the color changes somewhat randomly from one run to another, but all vertices are the same color anyway.

### Steps to reproduce

Create a MeshInstance3D, add an ImmediateMesh to it, draw some triangles and give them colors with `surface_set_color()`.

### Minimal reproduction project

[ImmediateMeshColor.zip](https://github.com/godotengine/godot/files/9907989/ImmediateMeshColor.zip)

This project draws a single triangle which moves around every frame. The color of each vertex is also supposed to change every frame, but the entire triangle appears pure white.
The desired color of one of the vertices is printed to the output every frame.

**Comment by dzil123** [comment]
You have to set `mat.vertex_color_use_as_albedo = true`

**Comment by Cykyrios** [comment]
Oh no, I can't believe I forgot to set this flag... now I'm not sure whether I was using it at all with ImmediateGeometry in Godot 3.x either.
Anyway, thanks for reminding me about this! I'm closing this issue.
