### ISSUE TITLE
Something seems to have changed in the shaders, causing some old ones to break.

### ISSUE THREAD

**Issue by esmeraldaliaj** [godotengine/godot#68121]
### Godot version

3.5.1

### System information

Windows 10

### Issue description

I used to have a bunch of random shaders I had created by reading books, tutorials etc. I recently tried to open a project of mine containing many of those shaders and they seem to not function correctly any longer. The same thing has happened with some random open source projects I had gotten from github.

An example is this shader below:

![image](https://user-images.githubusercontent.com/5569899/199268706-75aac93a-c8d8-43d4-ac9f-5f955aa6ed0c.png)

I've attached a minimal reproducible example. 

[shaders.zip](https://github.com/godotengine/godot/files/9911643/shaders.zip)

As well as a more complex example of a game I got on itchio made with if I recall v3.2 that on v3.5.1 just displays white all over the screen uploaded [here ](https://drive.google.com/file/d/1xdStTu_6J7MAT2kTITqbLE5Fx5JXiFzQ/view?usp=share_link)due to size. 

### Steps to reproduce

I am not sure how to reproduce it as I am not sure what causes it. Some shaders work some don't. Please have a look at the attached projects.

**Comment by tinmanjuggernaut** [comment]
![image](https://user-images.githubusercontent.com/632766/199465821-6965ed50-d57c-4dc5-a594-4008aa90c9f7.png)

I opened up the project in 3.5 and 3.5.1.  Looks fine to me. It is bouncing the image around like it's a flag. RTX3070, Win11/64.

Try upgrading (or downgrading) your graphics drivers, ensuring you're on GLES3, or upgrading your projects to Godot 4 w/ Vulkan.

Also, for the future, this is not a good report. This is not a `minimal` example, it's a complex shader. You need to do some work to narrow down what part of the shader code isn't working and describe how the code is supposed to work. You also need to show w/ pictures or video what should happen (from the older version) and what is happening. As well as list your graphics card. 

Aside from opening the project, if it was displaying white, I wouldn't put out any more effort as I have no idea what it's supposed to do, and I'm not going to troubleshoot 100 lines of your shader code if you aren't willing to either.
