### ISSUE TITLE
Global built-in constants are not available in shader include files.

### ISSUE THREAD

**Issue by Uxeron** [godotengine/godot#68124]
### Godot version

v4.0.beta3.official [01ae26d31]

### System information

Windows 10

### Issue description

Shader global built-in constants (PI, TAU, E) are not available in shader include files.

### Steps to reproduce

Create a .gdshaderinc file.
Create a function.
Try referencing any of the global constants (PI, TAU, E).

### Minimal reproduction project

[ShaderincMissingGlobals.zip](https://github.com/godotengine/godot/files/9912132/ShaderincMissingGlobals.zip)

**Comment by Calinou** [comment]
cc @Chaosus
