### ISSUE TITLE
GPUParticles3D gets culled for unknown reason

### ISSUE THREAD

**Issue by Mikeysax** [godotengine/godot#68145]
### Godot version

4.0beta3

### System information

PopOS 22.04, 5.19.0-76051900-generic kernel, Ryzen 6800h, Radeon 6700m, amdgpu, Vulkan

### Issue description

GPUParticles3D keeps getting culled unless I increase the cull margin, but this causes other issues.

Without cull margin:

![image](https://user-images.githubusercontent.com/15805689/199367025-6b8f6bbd-a3c4-424f-9d02-407b1e95be20.png)

![image](https://user-images.githubusercontent.com/15805689/199367035-c6f5bc1a-bf19-4ff8-9e0c-c67eeea58957.png)

![image](https://user-images.githubusercontent.com/15805689/199367045-1d4f62c4-3010-4e9a-9823-9679db4d58f1.png)

With cull margin:

![image](https://user-images.githubusercontent.com/15805689/199367109-697d909b-89a2-40ca-b9f5-8cd898590021.png)

![image](https://user-images.githubusercontent.com/15805689/199367096-9c3770f9-9460-4652-9bb4-6b683a8a85f3.png)

![image](https://user-images.githubusercontent.com/15805689/199367076-74fe02b1-ce12-4837-959b-71c2e5b414e1.png)

### Steps to reproduce

Place a plane on the ground and gpu particles above it.

This project can likely reproduce if gpu particles are added:

https://github.com/Mikeysax/example-project-for-godot-bug-67807

**Comment by Calinou** [comment]
You need to generaate an emission AABB using the menu at the top of the 3D editor viewport after selecting the GPUParticles3D node.
