### ISSUE TITLE
Shadow is not re-computed when vertex is moved from shader.

### ISSUE THREAD

**Issue by AllenDang** [godotengine/godot#68158]
### Godot version

4.0 Beta4

### System information

Macbook Pro M1, macOS 12.6

### Issue description

I created a rotating shader by rotate vertex in "vertex" function in shader, I noticed the shadow is not re-computed.

![cell_shading](https://user-images.githubusercontent.com/18550/199429537-38c11229-5ac0-49da-bc72-0f6da35fda8b.gif)

Here is the scene setup.

![image](https://user-images.githubusercontent.com/18550/199429965-567416c9-e84b-49f3-ae7f-f50b1fc35e91.png)

Do I miss something or what should I do to make the shadow work?

And here is the shader.

```glsl
shader_type spatial;

uniform float vertical_range = 1.0;
uniform float floating_speed = 3.0;
uniform float rotation_speed = 3.0;
uniform float directoin : hint_range(-1, 1, 2) = 1.0;

mat4 rotationMatrix(vec3 axis, float angle)
{
    axis = normalize(axis);
    float s = sin(angle) * directoin;
    float c = cos(angle);
    float oc = 1.0 - c;
    
    return mat4(vec4(oc * axis.x * axis.x + c,           oc * axis.x * axis.y - axis.z * s,  oc * axis.z * axis.x + axis.y * s,  0.0),
                vec4(oc * axis.x * axis.y + axis.z * s,  oc * axis.y * axis.y + c,           oc * axis.y * axis.z - axis.x * s,  0.0),
                vec4(oc * axis.z * axis.x - axis.y * s,  oc * axis.y * axis.z + axis.x * s,  oc * axis.z * axis.z + c,           0.0),
                vec4(0.0,                                0.0,                                0.0,                                1.0));
}

void vertex() {
	float v_range = vertical_range * sin(TIME * floating_speed);
	vec3 up = vec3(VERTEX.x, VERTEX.y + v_range, VERTEX.z);
	VERTEX = (rotationMatrix(vec3(0.0, 1.0, 0.0), TIME * rotation_speed) * vec4(up, 1.0)).xyz;
}

```

### Steps to reproduce

1. Create a shader which rotates the vertex.
2. Assign this shader to any object.
3. Create a simple scene with Directional Light 3D.

### Minimal reproduction project

[GodotFirstPersonController.zip](https://github.com/godotengine/godot/files/9917711/GodotFirstPersonController.zip)

**Comment by SleepyTonia** [comment]
It seems this happens when you use the TIME built-in variable. Using your own uniform floating variable seems like a viable workaround to me:
```
@tool
extends MeshInstance3D

var time := 0.0

func _process(delta):
	time += delta
	material_override.set_shader_parameter("time", time)
```
This is all you really need along with a slight tweak to your shader.
```
shader_type spatial;

uniform float vertical_range = 1.0;
uniform float floating_speed = 3.0;
uniform float rotation_speed = 3.0;
uniform float direction : hint_range(-1, 1, 2) = 1.0;

uniform float time = 0.0;

mat4 rotationMatrix(vec3 axis, float angle) {
    axis = normalize(axis);
    float s = sin(angle) * direction;
    float c = cos(angle);
    float oc = 1.0 - c;
    
    return mat4(vec4(oc * axis.x * axis.x + c,           oc * axis.x * axis.y - axis.z * s,  oc * axis.z * axis.x + axis.y * s,  0.0),
                vec4(oc * axis.x * axis.y + axis.z * s,  oc * axis.y * axis.y + c,           oc * axis.y * axis.z - axis.x * s,  0.0),
                vec4(oc * axis.z * axis.x - axis.y * s,  oc * axis.y * axis.z + axis.x * s,  oc * axis.z * axis.z + c,           0.0),
                vec4(0.0,                                0.0,                                0.0,                                1.0));
}

void vertex() {
	float v_range = vertical_range * sin(time * floating_speed);
	vec3 up = vec3(VERTEX.x, VERTEX.y + v_range, VERTEX.z);
	mat4 rotation = rotationMatrix(vec3(0.0, 1.0, 0.0), time * rotation_speed);
	VERTEX = (rotation * vec4(up, 1.0)).xyz;
	NORMAL = (rotation * vec4(NORMAL, 1.0)).xyz;
	BINORMAL = (rotation * vec4(BINORMAL, 1.0)).xyz;
	TANGENT = (rotation * vec4(TANGENT, 1.0)).xyz;
}
```

You can also use a global uniform instead:
`RenderingServer.global_shader_parameter_set("time", time)` with `global uniform float time;` in your shader.

**Comment by AllenDang** [comment]
@SleepyTonia Thanks for the work around.

**Comment by tinmanjuggernaut** [comment]
Good find on the TIME variable. Related to #51957 and #53972. 

I just discovered this when creating a wind shader for my trees. Having CPU driven animation for vertex shaders isn't a good solution. Every 3D game with animated foliage and trees is going to do use a vertex shader. I just noticed my trees moving around in direct sunlight all of a sudden sway into their own shadows! Why is this listed as "postpone" on the roadmap?

@clayjohn What do you think? 
Here, shadows are not recalculated after the shader moves the vertices in the vertex shader, when adjusted by TIME.

In #67471 zylann found shadows are not recalculated based on adjusting the scissoring in the fragment shader, when adjusted by TIME.

#53972 now makes the redraw request. I did some debugging and found in `render_forward_clustered.cpp::_render_list_template()` it does run `RenderingServerDefault::redraw_request()` for both opaque and shadow passes. Those and `RenderingServerDefault::_draw()` run many times per second, even when the camera is stationary. There are plenty of opportunities for both passes to update, but it seems like the shadow pass is calculating based on old data, not considering any changes from the shader. 

It won't update the shadow, even when you move the camera or transform objects. I have a tree that dips into its own shadow, then I rotate it, so the shaded side faces the direct sun and it's still in shadow.

Looking through render_forward_clustered.cpp, I tried marking the surfaces as dirty to no avail.

```
--- a/servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp
+++ b/servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp
@@ -361,6 +363,7 @@ void RenderForwardClustered::_render_list_template(RenderingDevice::DrawListID p
                //request a redraw if one of the shaders uses TIME
                if (shader->uses_time) {
                        should_request_redraw = true;
+                       surf->owner->_mark_dirty();
                }

                //find cull variant
```

I even marked every surface every time, and it does nothing. Any ideas? Where is this shadow calculated?

**Comment by clayjohn** [comment]
I think this is caused by the object using the default shadow material by mistake. The default shadow material is essentially a Godot shader with an empty ``vertex()`` and ``fragment()`` processor function.

**Comment by tinmanjuggernaut** [comment]
Hmm, I could see that being an issue if we can't edit the material on the shadow mesh. But on my trees, they have artist created lods. Upon import, I disabled lod and shadow mesh creation. 

My trees are calculating shadows based off of lod0. No shadow mesh. Other lods are disabled for now.

**Comment by clayjohn** [comment]
> Hmm, I could see that being an issue if we can't edit the material on the shadow mesh. But on my trees, they have artist created lods. Upon import, I disabled lod and shadow mesh creation.
> 
> My trees are calculating shadows based off of lod0. No shadow mesh. Other lods are disabled for now.

Shadow material is different than shadow mesh. But at any rate, I just tested out my theory and I was wrong, the logic checks for any write to ``VERTEX`` so it was appropriately not using the shadow mesh already. I'll dig in a bit further

**Comment by tinmanjuggernaut** [comment]
Thanks to @clayjohn for the PR fix. Should make it into master soon and beta5.
