### ISSUE TITLE
Add C# support for Android in Godot 4.x

### ISSUE THREAD

**Issue by tjacobhi** [godotengine/godot#68153]
### Godot version

4.0.beta1

### System information

Windows 11

### Issue description

In Godot 4.0.beta1 mono version, I am unable to export projects to android due to a missing export template for android. On all download sources, it shows windows and linux templates, but no android templates.

When I compare this to the non-mono version, I see android templates.

I have looked at all iterations of godot 4.0 beta [here](https://github.com/GodotBuilder/godot-builds/releases/tag/4.0-prerelease-templates) and see later beta versions also don't have android templates for the mono build.

I searched for an issue tracking this, but I was only able to find a closed issue for when godot originally added C# support for android https://github.com/godotengine/godot/issues/20267.

Is C# support for android planned for godot 4.0? If so, is there a different issue I should reference for this issue?

### Steps to reproduce

1. Open Godot 4.0.beta1
2. Select Project -> Install Android Build Template
3. Select Manage Templates
4. Select Download and Install
5. Close Template Manager
6. Select Project -> Export
7. Select Add -> Android
8. Observe error message `No export template found at the expected path:`

### Minimal reproduction project

Not including minimal reproduction project as this should be reproducible in an empty project. Let me know if you need one anyways.

**Comment by akien-mga** [comment]
C# support for Android, iOS and Web is not planned for 4.0, it will be worked later on for 4.x releases (as soon as possible, but for 4.0 we focus on the desktop platform and the overall feature set and UX).

**Comment by redthing1** [comment]
What are the blockers for mono on Android? I would be interested in trying

**Comment by tagcode** [comment]
> What are the blockers for net6 on Android? I would be interested in trying

I have no idea what I am talking about here, but my guess is that Xamarin won't work with .NET 5+. So Android export would have to be based on [MAUI](https://github.com/dotnet/maui), which needs to get Vulcan support, which might take a long time.

**Comment by Zireael07** [comment]
What's the status of this after the upgrade to NET 7.0?

**Comment by Jonak-Adipta-Kalita** [comment]
Its 4.0 Stabls and the support is not there...

**Comment by AThousandShips** [comment]
@Jonak-Adipta-Kalita yes, as was expected

> C# support for Android, iOS and Web is not planned for 4.0, it will be worked later on for 4.x releases

**Comment by Jonak-Adipta-Kalita** [comment]
> @Jonak-Adipta-Kalita yes, as was expected
> 
> > C# support for Android, iOS and Web is not planned for 4.0, it will be worked later on for 4.x releases

Yeah, I saw on there blog post.

**Comment by LutherShaw8888** [comment]
Waiting for Android export template of Godot 4 mono version!

**Comment by MusinxFate** [comment]
Still waiting the android export for C#

**Comment by akien-mga** [comment]
Please don't comment if you don't have meaningful information to add. We know that C# support for Android is missing, we don't need reminders.

If you want to show your support of the issue, add a :+1: reaction to the first post.

**Comment by Racso** [comment]
Hi. Regarding this: is there an estimate of when will Godot 4.x support C# for Android and iOS? Even a rough estimate would be appreciated. Are we talking about ~2 months? ~6 months? ~1 year?

Thanks!

**Comment by redthing1** [comment]
I wouldn't expect any less than 6 months to a year.

**Comment by behroozbc** [comment]
Hi, I want to know this issue is possible for a new contributor? if yes, please tell me how I should fix it?

**Comment by Zireael07** [comment]
@behroozbc Adding C# support in Android is a VERY complex task - not a first issue definitely.

Look for things tagged good first issue

**Comment by SelfMadeSystem** [comment]
> > @behroozbc Adding C# support in Android is a VERY complex task - not a first issue definitely.
> > Look for things tagged good first issue
> 
> Is it gonna happen or not

I know I'm not a contributor, but

> Please don't comment if you don't have meaningful information to add. We know that C# support for Android is missing, we don't need reminders.
> 
> If you want to show your support of the issue, add a +1 reaction to the first post.

**Comment by azimuthdeveloper** [comment]
Just a heads up, the Godot site is currently wrong until this issue is resolved. It shows you can use C# for your Godot games. While you can, this lacks an important asterix advising of this problem, and should possibly be updated until this issue is resolved.

![image](https://github.com/godotengine/godot/assets/9065229/ed27c19a-593e-4aed-98ec-e6934d3b8568)

The square below it advertises cross-platform ability, which is not possible when using C# in 4.0. The website should probably be updated.

![image](https://github.com/godotengine/godot/assets/9065229/a4d7af1a-5420-44cd-839c-571d375f5110)

**Comment by Calinou** [comment]
> Just a heads up, the Godot site is currently wrong until this issue is resolved. It shows you can use C# for your Godot games. While you can, this lacks an important asterix advising of this problem, and should possibly be updated until this issue is resolved.

This is being addressed by https://github.com/godotengine/godot-website/pull/671.

**Comment by Goldman13** [comment]
For 4.0.* works. Download the templates for non-mono, go to the downloaded template folder and copy all the android files to the mono templates folder

**Comment by akien-mga** [comment]
> For 4.0.* works. Download the templates for non-mono, go to the downloaded template folder and copy all the android files to the mono templates folder

That's not going to work, unless you're not using any C# code, in which case there's no reason to use the Mono version.

**Comment by Zamir7** [comment]
> Download the templates for non-mono
where can i download this template?

**Comment by Goldman13** [comment]
People, I'm sorry. I was wrong, it won't work.

> > For 4.0.* works. Download the templates for non-mono, go to the downloaded template folder and copy all the android files to the mono templates folder
> 
> That's not going to work, unless you're not using any C# code, in which case there's no reason to use the Mono version.

People, I'm sorry. I was wrong, it won't work.

**Comment by akien-mga** [comment]
C# support for Android was implemented by https://github.com/godotengine/godot/pull/73257 and will be available in Godot 4.2, due for release in November 2023.

You can already test it in the latest dev snapshots (the current one, and first one with the Android export template, is [4.2 dev 4](https://godotengine.org/article/dev-snapshot-godot-4-2-dev-4/)).

There might still be bugs with the implementation, so if you run into any issue when testing, please open a dedicated bug report, so we can make sure to iron out problems before the 4.2 release.

No ETA yet for iOS and Web support, but this is a top priority, we're currently assessing what it will take to get those.

**Comment by gtk2k** [comment]
4.2 Do I need to configure anything to be able to select C# in dev 4?
C# cannot be select.
![image](https://github.com/godotengine/godot/assets/309829/ff66fdda-34d6-4c80-8590-b07734e691eb)

**Comment by saierXP** [comment]
@gtk2k
https://godotengine.org/article/dev-snapshot-godot-4-2-dev-4/#downloads
You need to download the mono version (it's not renamed yet, it's actually .net)
![msedge_u1OoVr6H72](https://github.com/godotengine/godot/assets/45038185/eefe1dab-093d-4731-aa9e-e129d2daad9e)
Yours is the standard version.
You can ask questions on [other platforms](https://godotengine.org/community/) first next time, and if it might be a bug then report it on GitHub.
![msedge_l1WOA5yjAH](https://github.com/godotengine/godot/assets/45038185/3ace3fc1-748b-477d-a3dd-57e3b31435fc)

**Comment by gtk2k** [comment]
Thanks

**Comment by Jonak-Adipta-Kalita** [comment]
Amazing stuff guys! Thanks!!

**Comment by geekley** [comment]
> No ETA yet for iOS and Web support, but this is a top priority, we're currently assessing what it will take to get those.

Is there an open issue that we can follow just so we can get notified whenever these are available on Godot 4? I couldn't find any. If not, is it okay to open one just for tracking that?

**Comment by akien-mga** [comment]
iOS support was implemented already in #82729.
