### ISSUE TITLE
Is there a command to set these two records in 4.0?

### ISSUE THREAD

**Issue by xiaoliang6669** [godotengine/godot#68152]
### Godot version

4.0-beta3

### System information

win10

### Issue description

Is there a command to set these two records in 4.0? I can't find it

### Steps to reproduce

![999](https://user-images.githubusercontent.com/112788136/199414093-fcceeedb-3222-4f95-aa86-a570d88a3e81.png)

**Comment by Calinou** [comment]
@xiaoliang6669  Did you find a solution to this problem? If so, please document it here by commenting :slightly_smiling_face:
