### ISSUE TITLE
Rotation matrix multiplication order should be ZYX

### ISSUE THREAD

**Issue by zzz125** [godotengine/godot#6816]
i tried godot to verify some 3d transformations and found out that they were 'incorrect'.
it seems like godot uses XYZ order for rot. matrix multiplication but the correct order is ZYX (like in blender, and glm's quaternions)

im not an expert in 3d math but i read articles in internet that the correct order for euler angles is ZYX (like in quaternions) but many apps use XYZ (incorrect)

**Steps to reproduce:**
1. create an entity in blender, translate by 2,3,4 then rotate by 45,45,45 deg 
   compare the position with godot, try switch rotation order in blender (XYZ, YXZ - will give different position)
2. use this code with glm

```

#include <iostream>
#include <glm/vec3.hpp> // glm::vec3
#include <glm/vec4.hpp> // glm::vec4
#include <glm/mat4x4.hpp> // glm::mat4
#include <glm/gtc/matrix_transform.hpp> // glm::translate, glm::rotate, glm::scale, glm::perspective
#include <glm/gtc/matrix_inverse.hpp>
#include <glm/gtc/constants.hpp> // glm::pi
#include <glm/gtc/quaternion.hpp>
#include <glm/ext.hpp>
#include <glm/gtx/string_cast.hpp>
#include <glm/gtx/matrix_decompose.hpp>
#include <glm/gtx/quaternion.hpp>

using namespace std;
using namespace glm;

int main()
{
         mat4 rm = mat4(); // identity matrix
    // ZYX order (yaw, pitch, roll); "XYZ" in blender.
    rm = rotate(rm, radians(45.0f), vec3(0.0, 0.0, 1.0)); /// change values here to have "XYZ" order (wrong)
    rm = rotate(rm, radians(45.0f), vec3(0.0, 1.0, 0.0));
    rm = rotate(rm, radians(45.0f), vec3(1.0, 0.0, 0.0));
    //mat4 tm = mat4();
    mat4 tm = translate(vec3(2., 3., 4.));
    mat4 sm = mat4();

    mat4 modelMatrix = tm * rm * sm;
        mat4 m = modelMatrix;

    cout << "model matrix:" << endl;
    cout << to_string(m) << endl << endl;



        // Verifing it with quaternion rotation

    // quaternion rm test

    vec3 EulerAngles = radians(vec3(45, 45, 45)); // radians
    quat q1 = quat(EulerAngles);

    rm = mat4();
    rm = toMat4(q1); // quat to Rm
    m = tm * rm * sm;

    cout << "model matrix from quat:" << endl;
    cout << to_string(m) << endl << endl;

    cout << "quat:" << endl;
    cout << to_string(q1) << endl << endl;

        return 0;

}

```

hope it compiles

**Link to minimal example project** (optional but very welcome):

**Comment by BastiaanOlij** [comment]
It's actually common to support all combinations of rotations so this may be something that needs to be added as a setting. Look for instance and BVH for animation structures where the rotation order is specified on each joint for animations. Something to keep in mind if this gets changed.

**Comment by gau-veldt** [comment]
Does the orientation affect the definition of 'correct' rotation matrix?  The OP mentioned a comparison to Blender and Godot has a different orientation than Blender (Z is 'up' axis and Y is 'eye poker' axis in Blender but in Godot Z is the 'eye poker' axis and Y is 'up' axis).

**Comment by zzz125** [comment]
@gau-veldt

yes, im aware about Z/Y-up difference, but its not related

personally im using blender and glm only to verify my own 3d math 'library'

**Comment by reduz** [comment]
Yeah I know this is broken, it's noted in the list of things that need to
be fixed for 3.0. If you know a good implementation for reference in how to
deconstruct and construct the euler angles that is compatible with Blender,
Unity and others let me know.

**Comment by zzz125** [comment]
@reduz 

>If you know a good implementation for reference in how to deconstruct and construct the euler angles that is compatible with Blender
as i said, im not an expert but its in the example code that i posted

```
    // ZYX order (yaw, pitch, roll); "XYZ" in blender.
    rm = rotate(rm, radians(45.0f), vec3(0.0, 0.0, 1.0)); /// change values here to have "XYZ" order (wrong)
    rm = rotate(rm, radians(45.0f), vec3(0.0, 1.0, 0.0));
    rm = rotate(rm, radians(45.0f), vec3(1.0, 0.0, 0.0));
```

this code is compatible with both blender and glm's quaternions (i used it later to 'verify' the order')
it will will create a 45,45,45 deg rotation matrix in ZYX multiplication order (first multiply (rotate) by Z axis, then Y, then X). and in blender this order is called "XYZ" in the gui, it is a default order, you can choose "ZYX" in order in blender, but in glm it will be an "XYZ" order...

the verification part is quaternion-based transforms (blender uses them internally too AFAIK)
```
    // quaternion rm test

    vec3 EulerAngles = radians(vec3(45, 45, 45)); // radians
    quat q1 = quat(EulerAngles);

    rm = mat4();
    rm = toMat4(q1); // quat to Rm
```

here the same rotation was performed. first quaternion from euler angles was created, later it was converted to rotation matrix, and it gives the same matrix as ZYX multiplications.

if you want to test it againts XYZ matrix change these lines

```
    // ZYX order (yaw, pitch, roll); "XYZ" in blender.
    rm = rotate(rm, radians(45.0f), vec3(0.0, 0.0, 1.0)); /// change values here to have "XYZ" order (wrong)
    rm = rotate(rm, radians(45.0f), vec3(0.0, 1.0, 0.0));
    rm = rotate(rm, radians(45.0f), vec3(1.0, 0.0, 0.0));
```
to these:

```
    // XXX warn: XYZ order (will be called ZYX in blender)
    rm = rotate(rm, radians(45.0f), vec3(1.0, 0.0, 0.0)); // first X
    rm = rotate(rm, radians(45.0f), vec3(0.0, 1.0, 0.0)); // then Y
    rm = rotate(rm, radians(45.0f), vec3(0.0, 0.0, 1.0)); // then Z
```
the result will be different and incompatible with quaternion's version.

maybe it will help, it helped me to solve this in my engine

**Comment by tagcup** [comment]
> If you know a good implementation for reference in how to deconstruct and construct the euler angles that is compatible with Blender, Unity and others let me know.

I'm not sure about the deconstruction part, but the construction of the full matrix can be found here: https://en.wikipedia.org/wiki/Euler_angles#Rotation_matrix

**Comment by tagcup** [comment]
If the only issue is converting from XYZ to ZYX, I think it can be done with minimal change, using the following relation between XYZ and ZYX rotations.

An XYZ rotation matrix is R_z(γ) R_y(β) R_x(α), where R_i(θ) denotes rotation along i-axis by θ. In quaternion representation, this corresponds to a rotation by ψ along some u axis. The transpose (=inverse) of the original rotation matrix is R_x(-α) R_y(-β) R_z(-γ), which can be interpreted as a ZYX rotation, and in angle-axis representation, it is a rotation by -ψ along the same u axis.

**Comment by tagcup** [comment]
Found it [here](https://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/19770024290.pdf)! The current Quat constructor is the one on page A-11 (which is X-first, Z-last) up to sign conventions (flipping the signs of θ2 and θ3 does it); the one on page A-2 is the opposite order (Z-first, X-last).

The relation I mentioned in my previous post is also there, Eq. (13).

**Comment by tagcup** [comment]
@zzz125 A few corrections:

* The correct terminology is XYZ means Z-first, Y-next, X-last, it's not read from left-to-right, it's read from right-to-left. The reason is, each letter represents a rotation matrix along the indicated axis. The matrix on the right acts first. So the blender terminology is correct, and the title of this issue should be "Rotation matrix multiplication order should be XYZ".
* There is no "correct order" for Euler anglers or quaternions. You can expand a rotation matrix in infinitely many different ways. It's a matter of convention. However, the mapping between axis-angle representation (used when constructing a quaternion) and Euler angles depends on the axes you choose for your Euler angles. This is obvious I guess, because (Euler) angles are measured from some axis; if you use different axes, the angles will be different.

**Comment by tagcup** [comment]
@zzz125 Could you try the PR #6865?

**Comment by tagcup** [comment]
@zzz125 Can you post the gdscript code you found problematic?

One confusing and undocumented bit about godot's convention is rotations are [passive](https://en.wikipedia.org/wiki/Active_and_passive_transformation#Passive_transformation) (the angle in [godot](https://github.com/godotengine/godot/blob/master/core/math/matrix3.cpp#L459) is flipped in comparison to the ["normal" rotation matrix](https://en.wikipedia.org/wiki/Rotation_matrix#Rotation_matrix_from_axis_and_angle)). For example, `Matrix3(Vector3(0,0,1), PI/2)*Vector3(1,0,0)` will give you `(0,-1,0)`, not `(0,1,0)` because `Matrix3(u, phi)` gives a rotation matrix that rotates around `u` by `-phi` when applied to a vector as an active transform.

This is unlike glm or Unity or anything I've ever used, and I'm not sure whether this was intentional or not, I hope reduz can answer this, but for now, you'll need to flip the signs of your angles.

Can you please check whether this is the thing that causes your problem?

**Comment by tagcup** [comment]
Same thing is for quaternions, [godot flips the sign of the rotation angle](https://github.com/godotengine/godot/blob/master/core/math/quat.cpp#L258), so `Quat(u, phi)` gives you a rotation matrix that rotates by `-phi` around `u` axis, when you use it as a normal (active) rotation matrix.

**Comment by tagcup** [comment]
Correcting the angles broke some rotations in the 3D editor (spatial editor plugin). At first glance, the problem seems to be the fact that active transforms (matrices and quaternions that modify vectors are active by definition) were used for passive transformations that rotate basis vectors. I believe this is the reason why the angles were wrong in the first place.

**Comment by tagcup** [comment]
Also I think `Matrix3::rotate` and `Matrix3::rotated` could be renamed and hidden in GDScript. Ordinarily, rotating a matrix implies `R.M.Rᵀ` whereas these functions are intermediate tools for constructing the model transform matrix in a particular way (which can be achieved by constructing ordinary rotation matrices in GDScript using the angle-axis constructor).

**Comment by tagcup** [comment]
I just realized that the [docs](http://docs.godotengine.org/en/latest/tutorials/matrices_and_transforms.html#transform) are also confusing:

> Transform is the act of switching between coordinate systems. To convert a position (either 2D or 3D) from “designer” coordinate system to the OCS, the “xform” method is used.

This is a [passive transformation](https://en.wikipedia.org/wiki/Active_and_passive_transformation#Passive_transformation) which is not the first thing game programmers think of by default (all transformations are active on Unity and Love2D, and I'm guessing it's the same in Unreal Engine and others too). Strictly speaking, a passive transformation rotates the basis vectors of the world, and the vectors (such as position vector) are left unchanged.

I don't know how you can actually do real passive transformations in OpenGL (that is, changing the definition of basis vectors), but either case, a passive rotation leaves the vectors intact, so a passive rotation can't act on vectors.

To add more to the confusion, rotation and are like passive whereas scaling is active.

I'd be happy to submit a PR for the docs (and maybe explain more about the rotation group SO(3) and Spin(3) for those not familiar with them) if & after this PR is merged.
