### ISSUE TITLE
Collision is inaccurate when navigating

### ISSUE THREAD

**Issue by krazyjakee** [godotengine/godot#68175]
### Godot version

4.0 beta 4

### System information

Windows 11, Geforce 3090

### Issue description

Attached is a project containing a scene with a CharacterBody3D and a Skeleton3D that uses navigation to move towards the player. Inside the Skeleton3D there is a BoneAttachment3D with a RigidBody3D and a CollisionShape3D inside it.

![image](https://user-images.githubusercontent.com/623463/199573609-3fac278a-560f-4bf5-8b30-db09d768cc35.png)

The navigation seems to work but does not take the CollisionShape3D boundary into consideration and the Character clips through the wall.

![image](https://user-images.githubusercontent.com/623463/199574011-4e651e1d-8fcd-46fd-9ccb-c27927b3490e.png)

### Steps to reproduce

Add a character with skeleton and add a boneattachment to a bone with a collision box.
Have the character navigate to the player avoiding obstacles.

### Minimal reproduction project

[godot-collision-bug.zip](https://github.com/godotengine/godot/files/9923154/godot-collision-bug.zip)

**Comment by krazyjakee** [comment]
Damn, even without it being attached to a bone it clips through while pathfinding.

**Comment by Zireael07** [comment]
IIRC Smix has said that navigation is distinct from collision.

**Comment by krazyjakee** [comment]
@Zireael07 thanks. I've been thinking about it. Supporting Collision in navigation would mean a complete rework of the navigation as you could no longer guarantee that the character was in the bounds of the path at all. If it was pushed off-track, the events would need to be retriggered and it just adds a boat-load of entropy and wouldn't be a nice feature to work with at all.
