### ISSUE TITLE
Editor scene tree icons shift (and take up more space) when the pane is small.

### ISSUE THREAD

**Issue by JayCee-101** [godotengine/godot#68171]
### Godot version

4.0.beta4

### System information

Windows 10

### Issue description

When reducing the Scene Tree pane width the icons take up more space than normal, compounding the issue of the icons already covering names of nodes.

![godot4_scenetree_1](https://user-images.githubusercontent.com/79587945/199553120-26abd66c-0d5c-475d-b279-1c21557c68fb.png)
![godot4_scenetree_2](https://user-images.githubusercontent.com/79587945/199553117-7f60fd78-3b57-49d1-b081-bd966f7f18d1.png)

### Steps to reproduce

1. Add scenes with long names
2. Adjust pane width

### Minimal reproduction project

[minimal.zip](https://github.com/godotengine/godot/files/9922633/minimal.zip)

**Comment by Calinou** [comment]
Can you reproduce this in 3.5.1?

**Comment by JayCee-101** [comment]
No, I cannot reproduce in 3.5.1. There doesn't appear to be a horizontal
scrollbar in 3.5.1 when reducing the width of the pane, and the icons do
not move no matter how small I make a pane with a long node name or deep
nesting of nodes. This seems to be something added in 4.0.

**Comment by JayCee-101** [comment]
After a bit of testing it appears that when the horizontal scrollbar
appears the icons shift to the left as if a vertical scrollbar was shown,
but it is not. Icon distance from the right-side edge of the pane doesn't
change between a horizontal scrollbar and vertical scrollbar being visible,
and doesn't change when both scrollbars are visible.

**Comment by Calinou** [comment]
cc @KoBeWi

**Comment by KoBeWi** [comment]
The issue is in Tree. I suspect some condition is wrongly checking for scrollbar visibility. Good luck finding it though.
