### ISSUE TITLE
Godot export from terminal does not copy library files from gdnative (.DLL, .so, .dylib)

### ISSUE THREAD

**Issue by hirohido** [godotengine/godot#68172]
### Godot version

3.5.1 rc2

### System information

Macos Monterey

### Issue description

The export command does not copy the necessary dynamically linked libraries on both mac and linux when exporting from the terminal. Even after copying the library files into the same directory as the build project, it still does not work, like the files don't exist.

### Steps to reproduce

godot --export "Linux/X11"

**Comment by hirohido** [comment]
This was an error on my end

**Comment by Calinou** [comment]
@hirohido Did you find a solution to this problem? If so, please document it here by commenting :slightly_smiling_face:

**Comment by hirohido** [comment]
The issue was that i ran `godot --export "Linux/X11"` inside a sub-folder instead of the root folder containing project.godot.
