### ISSUE TITLE
Dictionary is always empty when defined as a member variable.

### ISSUE THREAD

**Issue by SassyJammy** [godotengine/godot#68183]
### Godot version

v4.0.beta4.mono.official [e6751549c]

### System information

Fedora Linux 37 (Workstation Edition)(beta) 64 bit

### Expected behaviour
The variable `dict` contains a dictionary containing the specified keys and values.

### Actual behaviour
The variable `dict` is an empty dictionary.
        `print(dict)` prints `"{ }"`

Note: This is not an issue of `print()`, `dict` doesn't contain anything when accessing a key.
This is fixed when adding the `@onready` annotation to the definition like so `@onready var dict = {"hello": 1}`

### Steps to reproduce

1. Create a script which extends Control
2. Define a member variable and store a Dictionary containing some values
        `var dict = {"hello": 1}`

4. Check the value of the variable
        `print(dict)`

**Comment by Calinou** [comment]
@SassyJammy Can you reproduce this in any of the previous [4.0 betas](https://downloads.tuxfamily.org/godotengine/4.0/) to determine when the regression started?

**Comment by SassyJammy** [comment]
@Calinou just tested all **non**-mono versions. Looks like the issue started in beta 4.

**Comment by SassyJammy** [comment]
Hmm that's weird. I've rewritten my code just the way it was and now it suddenly does work.

**Comment by KoBeWi** [comment]
If it's fixed then close it. Can always be reopened if you encounter it again (hopefully with more details).
