### ISSUE TITLE
Some suggestions for Label and RichTextLabel

### ISSUE THREAD

**Issue by Keyaku** [godotengine/godot#6818]
I'm in a fork in the road with my project which is rather bothersome.

There's dialogue in my game. Standard stuff. For that, I use a Label so that I can add shadows, custom colors, etc… However, there are pieces of dialogue that would have a greater impact on the player if we could add italic and bold font styles in some words, so I consider switching to RichTextLabel.

That's the thing: I have to juggle between one another just to find out which one of them would suit me best. That's a problem.

So, I have a few suggestions.

These are about **Label**:
- "Shadow as outline" has an integer slider setting that does _nothing_ but add or remove the outline (that's because [the code in Label grabs a boolean instead of an integer](https://github.com/godotengine/godot/blob/master/scene/gui/label.cpp#L88)). An improvement to this would be to use an integer and have a thickness level of the outline
- Export `visible_characters` since we only have `percent_visible` in the editor.

Here are other suggestions; these are optional but highly appreciated: having shared features so that when switching from one another, there would be less broken code. Features like:
- `add_text()` for Label
- `set_scroll_active()`for Label
- `set_text()` for RichTextLabel. Either swap `set_bbcode()`'s name or have a method that just adds raw text without checking if BBCode is on.
- `percent_visible` attributes for RichTextLabel

I hope this isn't asking for too much. I may make a Pull Request, but I'm not sure if I have the time.

**Comment by tagcup** [comment]
Relevant issue: #3854 (number of visible lines for RichTextLabel)

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Keyaku** [comment]
Thanks to Godot's 3.0 novelties, this is the current state of things:
* [ ] "Shadow as outline" works as a boolean even though has an `int` slider: This still acts as a boolean with an `int` slider.
* [x] Export `visible_characters` since we only have percent_visible in the editor: 

As for my suggestions:
* [x] `add_text()` for Label: now unnecessary.
* [x] `set_scroll_active()` for Label: ultimately unnecessary.
* [x] `set_text()` for Label: both Label and RichTextLabel have `text` (and therefore also have `set_text()`).
* [x] `percent_visible` for RichTextLabel: added in 3.0.

**Comment by akien-mga** [comment]
Given that almost everything has been addressed, closing as fixed.

It would be good to open a new issue for this part:
>  "Shadow as outline" works as a boolean even though has an int slider: This still acts as a boolean with an int slider.
