### ISSUE TITLE
GDScript 2.0: Property getters can easily `OPCODE_BREAK` when containing reference is freed

### ISSUE THREAD

**Issue by MarianoGnu** [godotengine/godot#68184]
### Godot version

v4.0.beta.custom_build [48925d60c]

### System information

Linux (Fedora36) - AMD Rayzen 9 5950X 16-Core Processor - Vulkan API 1.2.0 - Using Vulkan Device #0: AMD - AMD RADV NAVI14

### Issue description

The following source code emulates a situation where some code is deleting a node stored in a variable.
**In my particular case, the child nodes was being destroyed from _input, but code running on _draw was still trying to check the value stored in a variable**
When the variable was used, i got the following error
```
Got a freed object as a result of the call.
```
This error seems to be cryptic, because the blaiming line was `if !is_instance_valid(_selection):`
At first glance i was puzzled since the call in here is_instance_valid does not return an object, but the actual failing function actually was "@_selection_getter"

### Steps to reproduce

The following example can reproduce the issue:

```
extends Node

var node: Node:
	get:
		return node
	set(n):
		node = n


func _ready():
	node = Node.new()
	add_child(node)
	node.queue_free()
	
	get_tree().create_timer(1).timeout.connect(async_call)

func async_call():
	if !is_instance_valid(node):
		print("This should print right?")
```

### Found workaround
By using the following getter the OPCODE_BREAK and error can be avoided:
```
var node: Node:
	get:
		return null if !is_instance_valid(node) else node
	set(n):
		node = n

```

### Minimal reproduction project

[bug-reproduction-project.zip](https://github.com/godotengine/godot/files/9924011/bug-reproduction-project.zip)

**Comment by adamscott** [comment]
I don't really understand the point of your issue. Is this a Godot bug or is this a workaround you want to share to others?

**Comment by vnen** [comment]
The bug here is the difference between having a getter and not. The inconsistency is certainly odd but you're technically getting some extra protection here (and no one should be dealing with freed objects anyway).

**Comment by MarianoGnu** [comment]
the point is is this code should work:
```
func async_call():
	if !is_instance_valid(node):
		print("This should print right?")
```
but instead of printing the message, the debugger is stopping with an error

**Comment by MarianoGnu** [comment]
Yup, still reproduces
![image](https://user-images.githubusercontent.com/1776044/224155117-15b8ff8e-300f-43f4-a0ce-2e6043b135da.png)
