### ISSUE TITLE
Godot 4.0 beta 3 and beta4 stuck when clicking browse

### ISSUE THREAD

**Issue by 10ve** [godotengine/godot#68198]
### Godot version

v4.0.beta4.official [e6751549c]

### System information

macOS 12.6.1

### Issue description

stuck when clicking browse
macos's screencapture can't capture the mouse pointer of the stuck application

### Steps to reproduce

1. open godot 4.0beta3/4
2. click `New project->Browse` or `Scan` or `Import->Browse`
3. stuck

**Comment by 10ve** [comment]
<img width="868" alt="screencupture" src="https://user-images.githubusercontent.com/11514850/199640714-b3a058a5-4bd1-496a-9cd0-25bdff7b9237.png">

**Comment by Calinou** [comment]
How many folders and files do you have in the top-level of the home folder (`/Users/yang`)? Having a huge amount of files and folders (more than a few thousands or so) may be problematic here.

**Comment by 10ve** [comment]
> 您在主文件夹 ( ) 的**顶层**有多少个文件夹和文件`/Users/yang`？拥有大量文件和文件夹（超过几千个左右）在这里可能会出现问题。

No more than 10

**Comment by 10ve** [comment]
> How many folders and files do you have in the **top-level** of the home folder (`/Users/yang`)? Having a huge amount of files and folders (more than a few thousands or so) may be problematic here.

No more than 10 and It gets stuck even if I switch to another directory(change "/Users/yang" to "/User/yang/Desktop/" or other)

**Comment by 10ve** [comment]
In beta9,it's okay
