### ISSUE TITLE
Editor Inspector can not edit exported int64 value correctly

### ISSUE THREAD

**Issue by xiaowangxu** [godotengine/godot#68199]
### Godot version

v4.0.beta3.mono.official [01ae26d31]

### System information

Windows 11

### Issue description

when exporting a int64 value ('int' in gdscript, 'Int64' in c#)
editing them with large number through the inspector will cause visual and data incorrectness

### Steps to reproduce

create a script with @export var int_64 : int = 0 or c# equivalent
edit the 'int_64' property in the editor inspector (for example: 72057581049326836 and -9223372036854775808, which are all valid int64 value)
in gui 72057581049326836 will become 72057581049326832, -9223372036854775808 will become -9223372036854775800
in the .tscn file they will be saved as int_64 = 72057581049326832, int_64 = -9223372036854775808

![int64](https://user-images.githubusercontent.com/45325000/199641628-c9bf8224-3d0e-44f8-8a12-216213c06753.png)

this may be caused by using double as an intermedia data type

**Comment by kleonc** [comment]
Duplicate of #33095.
