### ISSUE TITLE
ColorPicker can be made horizontal and broken

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#68194]
### Godot version

4.0 08d56ac

### System information

Windows 10 x64

### Issue description

Unintended consequence of BoxContainer rework.
![](https://chat.godotengine.org/file-upload/jHndWtouPFR3aFSn9/godot.windows.editor.dev.x86_64_2ecFLD4rpP.gif)
`vertical` should be hidden with `_validate_property()`, like in other subclasses of BoxContainer.

### Steps to reproduce

1. Add ColorPicker
2. Change `vertical` to `false`
3. Funny

**Comment by jbcolli2** [comment]
If no one else is working on this, I'll take a crack at it.
