### ISSUE TITLE
Typo in method name: `VisualInstance3D::set_transparecy`

### ISSUE THREAD

**Issue by peppemas** [godotengine/godot#68205]
### Godot version

4.0 beta

### System information

Windows 11

### Issue description

Please correct typo: 

https://github.com/godotengine/godot/blob/a8c805be2947b211ee8b881d7a8bab7cdc86e170/scene/3d/visual_instance_3d.h#L143

it should be void set_transparency(float p_transparency); 

### Steps to reproduce

just look at the code :)

**Comment by pasi1991** [comment]
Hey! I will fix this typo as my first contribution. So I can get familiar with the workflow.
