### ISSUE TITLE
Godot_v4.0-beta4_mono_win64.exe crashes when trying to open a project for the 1st time

### ISSUE THREAD

**Issue by hoihoi8** [godotengine/godot#68206]
Godot Engine v4.0.beta4.mono.official.e6751549c - https://godotengine.org
Vulkan API 1.2.0 - Using Vulkan Device #0: AMD - Radeon RX 590 Series

ERROR: hostfxr_initialize_for_runtime_config failed with code: -2147450730
   at: (modules/mono/mono_gd/gd_mono.cpp:201)
ERROR: Parameter "load_assembly_and_get_function_pointer" is null.
   at: initialize_hostfxr_and_godot_plugins (modules/mono/mono_gd/gd_mono.cpp:274)
ERROR: Parameter "godot_plugins_initialize" is null.
   at: initialize (modules/mono/mono_gd/gd_mono.cpp:403)
Editing project: C:/Users/hoihoi8/Documents/Kraken_game

Godot Engine v4.0.beta4.mono.official.e6751549c - https://godotengine.org
Vulkan API 1.2.0 - Using Vulkan Device #0: AMD - Radeon RX 590 Series

ERROR: hostfxr_initialize_for_runtime_config failed with code: -2147450730
   at: (modules/mono/mono_gd/gd_mono.cpp:201)
ERROR: Parameter "load_assembly_and_get_function_pointer" is null.
   at: initialize_hostfxr_and_godot_plugins (modules/mono/mono_gd/gd_mono.cpp:274)
ERROR: Parameter "godot_plugins_initialize" is null.
   at: initialize (modules/mono/mono_gd/gd_mono.cpp:403)
WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:76)
WARNING: FBX file import is enabled in the project settings, but no FBX2glTF path is configured in the editor settings. FBX files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:100)

**Comment by raulsntos** [comment]
You are using the mono version of the editor which requires the .NET SDK (version 6.0 or greater) in a standard location.

If you do have the .NET SDK installed, can you execute `dotnet --info` in a console to give us more information about your installation?

**Comment by hoihoi8** [comment]
Didn't have 6 Net installed

**Comment by hoihoi8** [comment]
resolved
