### ISSUE TITLE
Tooltips cut off at edge of screen in-game

### ISSUE THREAD

**Issue by Wyxaldir** [godotengine/godot#68219]
### Godot version

v4.0.beta3.official [01ae26d31]

### System information

Windows 10

### Issue description

Tooltips clip past the screen rather than being offset like in the editor.

![image](https://user-images.githubusercontent.com/36777181/199789465-10e51294-7470-4d2e-9cad-a03d35af3a54.png)

### Steps to reproduce

Add a UI element with a tooltip, place it on the edge of the scene and make sure mouse filter is set to pass or stop. The tooltip should clip offscreen.

**Comment by Calinou** [comment]
Disable **Embed Subwindows** in the project settings to make tooltips spawn in actual OS windows.

**Comment by KoBeWi** [comment]
I think this was fixed in beta4. Embedded tooltips should be clamped to window.

**Comment by Wyxaldir** [comment]
The tooltips work as intended in fullscreen mode as well, thanks for the insight!
