### ISSUE TITLE
The default dock width is too small

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#68218]
### Godot version

4.0 beta4

### System information

Windows 10 x64

### Issue description

After the SplitContainer changes some time ago, the default dock width is too small:
![image](https://user-images.githubusercontent.com/2223172/199782714-7ba2916e-1433-4a19-a2d7-f31f9ae4fa80.png)
It's smaller than before, because the size is calculated differently, so we just need some new default.

### Steps to reproduce

1. Create new project
2. Open it
3. Look at the docks

**Comment by kleonc** [comment]
Related: https://github.com/godotengine/godot-proposals/issues/5685.

**Comment by akien-mga** [comment]
Another egregious example where having multiple icons on a given node makes things really cramped, and adds a scrollbar that behaves in a wonky way:

![image](https://user-images.githubusercontent.com/4701338/213168465-3e656802-708f-4163-9f00-5cf3f04da590.png)

https://user-images.githubusercontent.com/4701338/213168542-76513f2c-5df9-40a7-b9f7-b22548db2c7d.mp4

IMO we should aim to solve this for 4.0, it's not a terrible issue but it's a bad first impression.

**Comment by wlwl2** [comment]
@akien-mga I'm fine with any changes you or other users suggest, however, the way docks are in v3.5.stable right now seems to be perfect for me. You can even set the min size for each of the docks when you create one using EditorPlugin:

```py
func _enter_tree():
	dock = preload("res://path/to/your_scene.tscn").instance()
	add_control_to_dock(DOCK_SLOT_RIGHT_UL, dock)
	var d = dock as Control
	d.rect_min_size = Vector2(600,600)
```

I suspect that adding scrollbars takes up space on the screen for users (that they can use for other things) and takes time away from Godot engine developers. You can remove this from the milestone as well. Note that these are only my thoughts on the issue.

**Comment by wlwl2** [comment]
@akien-mga Adding scrollbars to docks take away space. The way they are right now is fine (at least for me).
