### ISSUE TITLE
Can't preload a scene in autoload if that scene uses the autoload

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#68211]
### Godot version

4.0 beta4

### System information

Windows 10 x64

### Issue description

When you have an Autoload and do `preload("scene.tscn")`, it will fail *at runtime* if that scene refers to Autoload in a script. This wasn't happening in beta3.

### Steps to reproduce

Just run MRP

### Minimal reproduction project

[PreloadBug.zip](https://github.com/godotengine/godot/files/9929400/PreloadBug.zip)

**Comment by adamscott** [comment]
I confirm the issue.

I tried to revert https://github.com/godotengine/godot/pull/68040 (26f0afdce25c00abc3f847b596cccafa9ccc0bc8), to see if it was the cause, and it is not.

**Comment by adamscott** [comment]
I mentioned in #67714 that it fixes this PR, but ideally, we should find what caused this issue.

**Comment by KoBeWi** [comment]
Bisect says #67849 :<

tbh that fix was fishy to me from the beginning. But the issue it fixed was more important, so we need a proper fix for both issues rather than simple revert.
