### ISSUE TITLE
[C#] Cannot convert type 'Godot.Variant' to 'AnimationNodeStateMachinePlayback'

### ISSUE THREAD

**Issue by FrostMiKu** [godotengine/godot#68226]
### Godot version

v4.0.beta3.mono.official [01ae26d31]

### System information

Windows 11

### Issue description

The return type of `Get` function is Variant.
But AnimationNodeStateMachinePlayback inherits from Resource...
Cannot convert type 'Godot.Variant' to 'AnimationNodeStateMachinePlayback'

### Steps to reproduce

code in official document:
```csharp
var stateMachine = GetNode<AnimationTree>("AnimationTree").Get("parameters/playback") as AnimationNodeStateMachinePlayback; 
stateMachine.Travel("some_state");
```
The above code will throw an error
Cannot convert type 'Godot.Variant' to 'AnimationNodeStateMachinePlayback' via a built-in conversion

**Comment by raulsntos** [comment]
You should be able to use the `Variant.Obj` property, so it should probably be something like this:

```csharp
var stateMachine = GetNode<AnimationTree>("AnimationTree").Get("parameters/playback").Obj as AnimationNodeStateMachinePlayback;
stateMachine.Travel("some_state");
```

Keep in mind the documentation hasn't been updated for 4.0 yet so there are probably many other outdated pages.

**Comment by FrostMiKu** [comment]
Hey raulsntos, thanks for your reply. I got the code from the documentation comments and I thought it was up to date. Should I close this issue?

**Comment by raulsntos** [comment]
No, we can keep it open to track that this part of the documentation needs to be updated. It's a valid issue, thank you for reporting it because otherwise we could have missed it.
