### ISSUE TITLE
Ability to name root node of imported asset scene after its filename

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#6822]
**Operating system or device - Godot version:**
Any

**Issue description** (what happened, and what was expected):
having to rename the root node of a imported scene can get tedious when dealing with lots of scenes or scenes that get updated over time. This can lead to issues if you have code/nodes that depend on some form of naming convention. I think that having a check box in the import settings to rename the root node to the same as the source file name should help alleviate some of the headache. We usually name the source file in a manner that represents what it contains anyway.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by kubecz3k** [comment]
@vonflyhighace2 the intended work-flow of dealing with external 3d assets (scenes) involves using scene inheritance. You should import asset, create scene that's extending the asset. You can change name here and make other edits that wont be lost while reimporting. 
I think this might be a documentation issue in fact.

**Comment by reduz** [comment]
I suppose it will still not kill us to add an option to specify the root
node name, I guess
