### ISSUE TITLE
Debug stepping becomes really slow when the scene contains a shader material wich uses the TIME uniform.

### ISSUE THREAD

**Issue by Gnumaru** [godotengine/godot#68232]
### Godot version

4.0beta15

### System information

windows 10 x64, vulkan and opengl

### Issue description

While trying to step trough lines in the debugger in a scene that contains a shader material that uses the TIME built-in uniform, the debug steps become really slow.

### Steps to reproduce

Open attached project, play "main.tscn" and try to step through the breakpoints with F10 or F12

### Minimal reproduction project

[NewGameProjectG4B.zip](https://github.com/godotengine/godot/files/9932630/NewGameProjectG4B.zip)

**Comment by Gnumaru** [comment]
Another slow debug stepping related bug was reported here:
https://github.com/godotengine/godot/issues/67696

**Comment by Zireael07** [comment]
Same on Linux (my sky shader uses TIME)

**Comment by flotos** [comment]
Same, it was slow to the point I thougt it was freezing. Removing my shader from the label I used totally fixed it.

**Comment by Gnumaru** [comment]
still reproducible on beta 5

**Comment by clayjohn** [comment]
Closing as duplicate of https://github.com/godotengine/godot/issues/68232

**Comment by Zireael07** [comment]
Yy, you closed this as duplicate of... itself?

**Comment by clayjohn** [comment]
Whoops, I had both issues open at once. Should be https://github.com/godotengine/godot/issues/67696
