### ISSUE TITLE
Allow even more freedom for line breaks in GDScript

### ISSUE THREAD

**Issue by RandomShaper** [godotengine/godot#6823]
GDScript already allows newlines inside arrays and maps, now also inside function calls among other new places thanks to #6694.

It would be nice to allow them in more places like at either side of binary operators (arithmetic, assignment, boolean).

I'm calling on @bojidar-bg here since he has this stuff fresh on his mind. ;)

EDIT: Before/after dot (method/property access) would be nice too.

**Comment by bojidar-bg** [comment]
Note that pythong doesn't support the following:
```py
a=
3
# --
b
=3
# --
c = 2 +
1
# --
if d
and c:
# --
if e and
f:
#...
```
(All of the are supported when inside parenthesis, except the `=` operator, which needs `\` instead)

**Comment by RandomShaper** [comment]
My opinion could be biased, being not a Python developer myself, but I
believe that making GDScript more flexible is a good thing.

Of course, provided GDScript doesn't mutate as far as rejecting familiar
Python syntax.

That way, one can write GDScript according to his preferred style. Line
breaks are part of it exactly as usage of spaces, alignment of similar
sentences, names of symbols, etc.

That said, I strive to write one-line sentences for readability, but
sometimes there is no good alternative and all those syntactic slashes add
a lot of clutter.

**Comment by akien-mga** [comment]
I think we should stick as close as possible to the design of Python (3). The Python community is huge and already put a lot of thought in their syntax, I don't think it would be wise of us to consider we can do better based on the feedback of a handful of developers.

It's fine to decide to part with the Python syntax if there is a strong technical justification for one variant being superior to the pythonesque one, but it shouldn't be just for the sake of flexibility. Too much flexibility means that people don't know what is the proper syntax anymore, and the language becomes much harder to master (see e.g. C#...).

**Comment by SuperUserNameMan** [comment]
beginners would just stick to the syntax they've learned into the tutorials, and could be oriented to the python syntax for further dogmatic reference.

on the other hand, advanced users could benefit from the extra flexibility that could be documented into the "Advanced" category of the doc for instance.

Though, since it is already possible to write multi-line statements thanks to the parenthesis effect mentioned by @bojidar-bg, i'm wondering why we'd need more than that ?

````
if ( hair_style == "banana"
and hair_color == "orangish"
and iq < IQ_5_YEAR_OLD_BONOBO
and width >= XL
and country = "USA"  
) : #{
    print("You have a trump.");
#}
````

**Comment by RandomShaper** [comment]
@SuperUserNameMan, nice example! :)

Well, after some consideration I think that the way to go is not to diverge too much from Python. Especially, when parentheses cover my line-breaking needs.

So enough for this issue.
