### ISSUE TITLE
No error logged when setting a property with no setter

### ISSUE THREAD

**Issue by adamscoble** [godotengine/godot#68240]
### Godot version

4.0.beta3.official

### System information

Windows 10

### Issue description

GDScript 2.0 allows you to set a property without a setter. I believe this should show a linting error.

### Steps to reproduce

Create a property with a get only and set it:
```
var my_property: int = 0:
    get:
        return my_property
		

func _init() -> void:
    my_property = 1
    print(my_property) # 1 
```

**Comment by TheDuriel** [comment]
This is entirely intentional. There is no mandate to define either a setter nor a getter if they do nothing special.

**Comment by Calinou** [comment]
This is intended. In 3.x, you could define only a getter using the `var my_property setget ,get_my_property` syntax (notice the leading comma). This didn't cause a warning to be emitted.

**Comment by TheDuriel** [comment]
@Calinou I figure the expectation was that, not defining a setter makes the property read only. Though this is actually achieved by defined a setter that does nothing.

Might be worth reiterating that fact in the docs. "If you don not define a setter, the value will be set without modification. If you instead wish for your property to be read-only in effect, instead define a setter that does not set the value and immediately returns."

**Comment by adamscoble** [comment]
Thanks for the comments gang! 

Yep @TheDuriel that's exactly what my expectation was. I clearly misunderstood "It may also be desired to encapsulate [the property's] access in some way." from the Properties section on the [GDScript Reference](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_basics.html) page! (Just noticed a typo in the preceding sentence, "change" instead of "changes",) 

Coming from C# I'm altering my mindset as I go, and this kind of pairs with GDScript not having a private concept! The only "issue" I have with it is how to indicate externally that a property shouldn't be set, in the way GDScript recommends using an underscore to indicate privacy. But maybe that's as simple as a setter that throws an error.

Thanks!

**Comment by TheDuriel** [comment]
Error throwing setter is my GoTo. Sadly with the new syntax it's not possible to just redirect all properties you want readonly to a single setter, so you'll get a lot of redundant lines.
