### ISSUE TITLE
Hex value field does not accept transparency

### ISSUE THREAD

**Issue by RPicster** [godotengine/godot#68248]
### Godot version

4.0.beta3

### System information

Win 10

### Issue description

The Color Picker in Godot 4 has a Hex field, similar to Godot 3.
While Godot 3 correctly included transparency (alpha) in the hex code, Godot 4 does not accept or display alpha in the hex code.

This is not just incorrect but it also makes it impossible to paste values from Godot 3 to 4.

### Steps to reproduce

Open the Color Picker, paste `c5143761` (slightly transparent blue). The result is another color.

**Comment by KoBeWi** [comment]
It works, at least in beta4. The field is RGBA, so you expect wrong color.

**Comment by akien-mga** [comment]
In 3.x the HTML color code was ARGB, for no good reason:
![image](https://user-images.githubusercontent.com/4701338/199998400-64a7169b-3484-485b-8628-1b70b5392a45.png)

This was changed for 4.0 in #40868 to follow the Web standard: https://developer.mozilla.org/en-US/docs/Web/CSS/hex-color

Colors should still be stored as `(R, G, B, A)` internally both in 3.x and 4.0 so they should stay compatible when converted. But yes, for copy pasting hex values from 3.x to 4.0, that won't work, you'll need to move the first two digits to the end.
