### ISSUE TITLE
GDScript doesn't throw errors for assigning to unassignable expressions

### ISSUE THREAD

**Issue by Schranz0r** [godotengine/godot#6824]
**Operating system or device - Godot version:**
Win10 Home 64Bit - Godot v.2.2.custom_build

**Issue description** (what happened, and what was expected):
No Errorhandling for "bad" Syntax for (in editor and cmd.exe window):

  get_node("MyArray") = add_child(myMap[x][y],false)
  add_child(myMap[x][y],false)

**Steps to reproduce:**
see my codessnippet : http://pastebin.com/E7ApcFxj

**Link to minimal example project** (optional but very welcome):
see above 🎃

**Comment by vnen** [comment]
I guess the problem here is that `get_node("MyArray") = add_child(myMap[x][y],false)` is trying to assign to a function call and no error is shown. Did I understand it right?

**Comment by gau-veldt** [comment]
@vnen If I'm reading that right line 1 would reduce to:
`<Node_id>=<null>`

The void func renders <null> when used as an expression and get_node() returns a <Node_id>.

Conclusion: Shouldn't be allowed since Node_id's are not vars.

**Comment by gau-veldt** [comment]
**PS:** Line 2 is _not_ an error since it means same as `self.add_child(myMap[x][y],false)`
