### ISSUE TITLE
OSX export fullscreen mode inconsistent due to missing info.plist entries

### ISSUE THREAD

**Issue by lekoder** [godotengine/godot#68254]
### Godot version

3.5.1-stable

### System information

OSX

### Issue description

Games exported with Godot Engine, when running in the full-screen mode on OSX, will show the title bar and menu docks as soon as the user puts the mouse pointer near the edge of the screen. While this is an expected behaviour for a full-screen application, it is not the case for the games, which require exclusive input without OS interruptions.

This behaviour can be controlled by `info.plist` file entry:
```
	<key>LSUIPresentationMode</key>
	<integer>3</integer>
```

I classified this report as a bug based on the fact that it makes Godot Engine unsuitable to create games to run fullscreen on OSX. Once the "trick" is known it can be easily worked around by the game developer, either manually or in the build script, but I'd argue that the default behaviour for the game engine should be to treat its projects as games, not a "generic full-screen apps".

### Steps to reproduce

- Export any fullscreen project on OSX.
- Move the mouse cursor to the lower edge of the screen.

**Comment by akien-mga** [comment]
CC @bruvzg 

Quality docs from Apple...
![image](https://user-images.githubusercontent.com/4701338/199996753-91ee8247-60a6-4186-ab39-0f7453df8837.png)

https://developer.apple.com/documentation/bundleresources/information_property_list/lsuipresentationmode

**Comment by bruvzg** [comment]
> Quality docs from Apple...

Indeed, we can set presentation mode from the code - actual option are documented at - https://developer.apple.com/documentation/appkit/nsapplicationpresentationoptions?language=objc

I guess in case of 4.0 it's probably should be `WINDOW_MODE_EXCLUSIVE_FULLSCREEN`. I'll open PR in a few moments (found unrelated bug while testing it).
