### ISSUE TITLE
Crash opening any project (even new one) on Silicon M1 Mac

### ISSUE THREAD

**Issue by alex-dearden** [godotengine/godot#68258]
### Godot version

4.0 beta 3

### System information

Mac OS Monterey 12.6 M1 chip

### Issue description

Trying to open any project, even a newly created one crashes Godot with this error:

VM Region Info: 0 is not in any region.  Bytes before following region: 4303699968
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      100854000-106630000    [ 93.9M] r-x/r-x SM=COW  ...s/MacOS/Godot

### Steps to reproduce

1. Open godot 4
2. create new project
3. open project
4. app crashes

Partial report:

VM Region Info: 0 is not in any region.  Bytes before following region: 4303699968
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      100854000-106630000    [ 93.9M] r-x/r-x SM=COW  ...s/MacOS/Godot

**Comment by Calinou** [comment]
Does it work if you open the project with the `--rendering-driver opengl3 --single-window` command line arguments? See [Command line tutorial](https://docs.godotengine.org/en/latest/tutorials/editor/command_line_tutorial.html) for instructions. Note that you need to open the project directly by specifying the path to its `project.godot` file, instead of going through the project manager.

**Comment by StevenH34** [comment]
Try installing [.NET 6.0 SDK - macOS Arm64 Installer](https://dotnet.microsoft.com/en-us/download/dotnet/6.0). That fixed the crash for me.

**Comment by dglwilkins** [comment]
> Try installing [.NET 6.0 SDK - macOS Arm64 Installer](https://dotnet.microsoft.com/en-us/download/dotnet/6.0). That fixed the crash for me.

I've been having a similar error and this fixed it for me, thank you.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
