### ISSUE TITLE
C# tutorial script not working with KinematicBody2D

### ISSUE THREAD

**Issue by aakov** [godotengine/godot#68250]
### Godot version

v3.5.1-stable_mono_win64

### System information

Windows 10, GLES3, Intel Core i7 6820HQ

### Issue description

![image](https://user-images.githubusercontent.com/73497471/199961245-40028acc-362d-4e57-bf7e-9ac6cc682871.png)

When using a C# script from the 2D movement overview tutorial (link below)
https://docs.godotengine.org/en/stable/tutorials/2d/2d_movement.html I always get the following error
 E 0:00:00.884   can_instance: Cannot instance script because the class 'new_script' could not be found. Script: 'res://Player/new_script.cs'.
  <C++ Error>   Method failed. Returning: __null
  <C++ Source>  modules/mono/csharp_script.cpp:2897 @ can_instance()

This error occurs when using any C# script with KinematicBody2D
However attaching a C# to a sprite works fine 

### Steps to reproduce

Just follow this tutorial using C# https://docs.godotengine.org/en/stable/tutorials/2d/2d_movement.html
or simply attach a C# script to a KinematicBody2D

### Minimal reproduction project

[2D Movement C#.zip](https://github.com/godotengine/godot/files/9937823/2D.Movement.C.zip)

**Comment by raulsntos** [comment]
In C# the name of the file must match the name of the class and it's case-sensitive. From reading the documentation page you linked, it seems the name of the file should be `Movement.cs`. The documentation should include this about naming the script, currently it doesn't say anything about how to name it.

**Comment by aakov** [comment]
Thank you!

**Comment by Sslaxx** [comment]
If you've closed this, it may be worth opening an issue about the C# documentation not mentioning filename/classname issues on https://github.com/godotengine/godot-docs/issues
