### ISSUE TITLE
Creating AtlasTextures in Godot 4.0 beta 4 causes re-imports every time we reload, and engine runs slower

### ISSUE THREAD

**Issue by LakshayaG73** [godotengine/godot#68256]
### Godot version

4.0 beta 4

### System information

Windows 11

### Issue description

I've started using AtlasTextures on all my sprites for the massive VRAM savings. 

There are three issues -: 
1) Everytime I open the project now, I see errors like this that eventually go away: 
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/1243371/199990562-81ab853f-2fdf-47ae-894d-dcc31efae6e1.png">

2) There are reimports every time I open the project

3) The engine seems to be running on a different setting now. It is generally slower, and specially if I alt tab, it takes it a few seconds to wake up. This happens any time I change the window, and otherwise when navigating the filesystem. 

The VRAM savings are good, but slowed development is bad. Thanks for your help. 

### Steps to reproduce

1) Use atlastextures in project

**Comment by LakshayaG73** [comment]
Every time I alt tab and come back, CPU usage shoots up to 30%.

**Comment by Calinou** [comment]
@LakshayaG73 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

We can't do anything here without a MRP, so the issue will have to be closed in 7 days otherwise.

**Comment by LakshayaG73** [comment]
To create a MRP for this, I will need to a lot of textures, and create atlases. I will do that if needed. 

The issue is very evident. Every time I alt-tab, or minimize the godot window, or even play the scene, I am reloading all the textures that point to sprite atlases:

<img width="637" alt="image" src="https://user-images.githubusercontent.com/1243371/200062374-e1e6f327-0f92-45fe-b627-1fde2673023b.png">

This is happening every time I alt tab! This cannot be normal behavior.

**Comment by LakshayaG73** [comment]
[MRP.zip](https://github.com/godotengine/godot/files/9941670/MRP.zip)

The project above is small but experiences all the issues as described above even with a single atlas texture. Seems like the feature is broken.

You will experience huge delays when alt tabbing and opening the project.

**Comment by LakshayaG73** [comment]
I can see that this is coming from:

<img width="910" alt="image" src="https://user-images.githubusercontent.com/1243371/200075080-237380f1-63be-47e6-af1f-b322e67e1c68.png">

Could it be because this cache mode has been set incorrectly? Shouldn't these resources be cached somewhere?

**Comment by LakshayaG73** [comment]
<img width="374" alt="image" src="https://user-images.githubusercontent.com/1243371/200076742-00acff5a-21ed-4473-9d2b-6002f079faab.png">

The cache mode could be set this way due to 'load from file' being called, because the image is not being loaded 'OK'. 

Please let me know if this is the right path?

**Comment by AThousandShips** [comment]
Doing some digging it looks like the hash for TextureAtlas is broken, not sure exactly what's going on but on reload the md5 hash for the atlas file is changed, this would naturally cause the editor to reimport it, and thus force the target file to be reimported, on each entering of the editor, will see if I can find where this occurs and what is going on exactly with that

**Comment by AThousandShips** [comment]
Ignore all that, it turns out it was way simpler:
Files included from a group are not given a UUID on import, possibly an oversight from past versions I don't know, however import files without one are always queued for import, therefore these atlas files are always reimported, should be straight forward to solve will take a look

**Comment by LakshayaG73** [comment]
Thank you for your efforts, much appreciated

**Comment by AThousandShips** [comment]
There seems to have been a second issue as well where under some condition (like opening the editor) the target file would be reimported on its own, and then the group would be reimported, which would more or less double the import time under those conditions, so adding a tentative check to prevent files that are groups from being imported twice

**Comment by AThousandShips** [comment]
Also, for the future I recommend you not include the .godot folder in your MRPs, it can contain information about your computer that could be a security risk, not a big deal in this case but a good practice to keep in mind

**Comment by Calinou** [comment]
> Also, for the future I recommend you not include the .godot folder in your MRPs, it can contain information about your computer that could be a security risk, not a big deal in this case but a good practice to keep in mind

Is that actually the case? Please don't spread this kind of information without verifying it beforehand (and reporting it in a dedicated issue if it turns out to be the case).

**Comment by AThousandShips** [comment]
Oh I'm sorry I thought I had seen that being pointed out before! And considering the issues with files in git repositories

**Comment by AThousandShips** [comment]
I had understood that file paths external to the res:// filespace was an issue, and there is the reference to the executable in there somewhere

**Comment by kleonc** [comment]
> Is that actually the case?

@Calinou I've briefly checked the files from the MRP and this can be found in the `.godot\editor\project_metadata.cfg`:
```cfg
[editor_metadata]

executable_path="C:/Users/User/Downloads/Godot_v4.0-beta4_win64.exe/Godot_v4.0-beta4_win64.exe"
```

**Comment by Calinou** [comment]
The metadata storage in question was added by https://github.com/godotengine/godot/commit/2f151068b5333c133d1a9dffe124bb532ba0a25b, likely for use by the Godot Rider plugin.

**Comment by van800** [comment]
I am under the impression that .godot content including project_metadata.cfg is not supposed to be added to the vcs. If so, then what is the issue with the username?

**Comment by Calinou** [comment]
> I am under the impression that .godot content including project_metadata.cfg is not supposed to be added to the vcs. If so, then what is the issue with the username?

It's not supposed to be committed to version control, but some people still include it in ZIP archives they create to upload as minimal reproduction projects here (or on other places).

Including the username is problematic for people who use their real name as their OS username and wish to keep their online identity private. Not everyone can change their OS username (e.g. on corporate-owned machines). Even when it's possible, it requires recreating a new and moving everything, which is a time-consuming process.

**Comment by Zireael07** [comment]
We discussed it in https://github.com/godotengine/godot/issues/29674 (I managed to find it by searching for "privacy")

**Comment by LakshayaG73** [comment]
Sorry to derail this conversation a bit... 

Regarding this issue. The PR from @AThousandShips works great.

There is one more thing that I've noticed. Which may be by design, but I'm not sure. I've noticed that the width of the atlastexture doesn't go below 2048: 

<img width="553" alt="image" src="https://user-images.githubusercontent.com/1243371/200192585-bc89eb3a-dd2e-4055-a815-d96ae3e0c901.png">

Can't help but wonder about the extra dead space here as well. Is this done on purpose?

**Comment by kleonc** [comment]
> There is one more thing that I've noticed. Which may be by design, but I'm not sure. I've noticed that the width of the atlastexture doesn't go below 2048:

@LakshayaG73 You mean it doesn't go above 2048? That's indeed the default value which is currently used for the max width by the atlas packer:
https://github.com/godotengine/godot/blob/256069eaf00be2340259f896695014d92b1e22ed/editor/editor_atlas_packer.h#L71



> Can't help but wonder about the extra dead space here as well. Is this done on purpose?

Is there an extra dead space though? Looking at the preview you've shown it seems like it's just zoomed out and the preview's transparent background is rendered way bigger then it should (not just behind the actual image) as this rectangle has approximately 2048 / 18556 aspect ratio:
![JhDzc1O](https://user-images.githubusercontent.com/9283098/200193454-72f67562-304b-454d-b7a1-146ce446abf0.png)

**Comment by LakshayaG73** [comment]
whoops. you're right. thanks for the clarification!

**Comment by LakshayaG73** [comment]
There is one more issue here it seems. 

If I use a Mesh to pack these textures together, like I've done in the image above, and try to add the frames to a spriteframes, some frames show up as empty. The reason is that some frames are simply not added to the mesh. This does not occur if you select 'region' when creating the AtlasTexture. 

Mesh2D, created with the same frames:
<img width="242" alt="image" src="https://user-images.githubusercontent.com/1243371/200195022-cd377dfd-a81e-438c-a7bd-91f9b34a06e4.png">

Region, created with the same frames:
<img width="245" alt="image" src="https://user-images.githubusercontent.com/1243371/200195057-4e95b7b6-ee12-4515-bf66-6035159def59.png">

**Comment by LakshayaG73** [comment]
The same frames are being skipped every time. Perhaps they are being considered duplicates?

**Comment by kleonc** [comment]
>The same frames are being skipped every time. Perhaps they are being considered duplicates?

@LakshayaG73 No idea. But for sure it seems like a seperate problem. So please open a new issue and provide all needed details in there (and an MRP so it could be investigated properly).

**Comment by LakshayaG73** [comment]
https://github.com/godotengine/godot/issues/68350

**Comment by LakshayaG73** [comment]
Could you please remove the "needs testing" label from this @Calinou as there is a PR out. Thank you.
