### ISSUE TITLE
Android app crashes at startup due to IllegalArgumentException for PendingIntent

### ISSUE THREAD

**Issue by coner** [godotengine/godot#68264]
### Godot version

3.5.stable

### System information

Android 12

### Issue description

The following exception is thrown at startup on Android 12 for a project with Android plugins installed and enabled:

java.lang.IllegalArgumentException: ...: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.

### Steps to reproduce

Clone the following project https://github.com/coner/godot-pendingintent-issue and run on an Android 12 device with plugins enabled.

Use adb logcat to trace logs.

### Minimal reproduction project

https://github.com/coner/godot-pendingintent-issue

**Comment by Calinou** [comment]
cc @m4gr3d

**Comment by avnerh1** [comment]
> Fixed by upgrading tooling and dependency versions on all plugins. Also had to upgrade the gradle version of the android build template that comes with 3.5.1

I also have this error (using 3.5.2), but I couldn't understand from your answer what I need to do to solve it. Please advise.

**Comment by cengiz-pz** [comment]
> I also have this error (using 3.5.2), but I couldn't understand from your answer what I need to do to solve it. Please advise.

@avnerh1, make sure your app's target android SDK version is 32 and if you're using any android plugins, then you'll need to make sure that the gradle, gradle plugin, and SDK versions used in the plugins match that used by Godot 3.5.2.
