### ISSUE TITLE
Editor crashes when duplicating nodes with scene dock on the right side

### ISSUE THREAD

**Issue by souplamp** [godotengine/godot#68265]
### Godot version

Godot 4.0 beta3

### System information

Windows 10

### Issue description

Arranging your editor dock to have the scene dock on the right hand side, selecting a node and hitting (Control + D) more than once will crash the engine.
This is related to #67886, which apparently was fixed in #67926. In my case, however, this bug appears to still be present.

![editor-layout](https://user-images.githubusercontent.com/89402588/200048419-73550782-e95b-481c-8122-2bc837acdf1d.png)
The above is my current dock positioning, placing all elements on the right hand side of the screen. I ran into this issue whenever I attempted to select the child AnimatedSprite2D node and duplicating it using the duplicate shortcut.

This appears to happen with any kind of node, but this crash happened reliable with an AnimatedSprite2D child node in case that information is relevant. See the attached MRP.

### Steps to reproduce

1. Open the MRP in Godot 4 beta3.
2. For the scene panel, click the dropdown to move it to the top or bottom right portion of the editor screen (to recreate my exact set-up, see the attached image in the issue description).
3. Open the scene "node.tscn" and go to the scene panel.
4. Select the AnimatedSprite2D child node and press Control+D until you encounter a crash.

### Minimal reproduction project

[control+d mrp.zip](https://github.com/godotengine/godot/files/9941138/control%2Bd.mrp.zip)

**Comment by souplamp** [comment]
Just realized this fix would be in master if it does work, whoops. I don't know how to pull from master to test this, so I'll close this for now.

**Comment by akien-mga** [comment]
You can use beta 4, which includes this fix.

**Comment by souplamp** [comment]
> You can use beta 4, which includes this fix.

Thank you for the heads up. I just tested and it works as expected :)
