### ISSUE TITLE
Can't not catch event from Button under BottomDock(plugin)/GraphEdit/GraphNode

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#6828]
**Operating system or device - Godot version:**
Godot 2.2 alpha (6c0be2c017e605c2106823e80e5aaa78fc68aba5)

**Issue description** (what happened, and what was expected):
Can't not catch event from Button under BottomDock(plugin)/GraphEdit/GraphNode

**Steps to reproduce:**
* from running scene, Button pressed event can be catched.
* from dock, never catch.
![image](https://cloud.githubusercontent.com/assets/8281454/19395282/d3e94f6a-9277-11e6-8154-86b6d650d094.png)

**graphedit_test.gd**
```gdscript
tool
extends EditorPlugin

var dock

func _enter_tree():
	dock = preload("res://addons/addon_graphedit_test/GraphEdit.tscn").instance()
	add_control_to_bottom_panel(dock, "GraphEdit Test")

func _exit_tree():
	remove_control_from_bottom_panel(dock)
	dock.free()
```

**graphedit_test_scn.gd**
```gdscript
extends GraphEdit

func _ready():
	get_node("GraphNode/Button").connect("pressed", self, "on_button")

func on_button():
	get_node("GraphNode/Button").set_text("clicked!!!")
```

**Link to minimal example project** (optional but very welcome):
[godot_plugin_graphedit.zip](https://github.com/godotengine/godot/files/529983/godot_plugin_graphedit.zip)

**Comment by bojidar-bg** [comment]
@volzhs Is the `graphedit_test_scn.gd` script tool as well? Otherwise it won't ever run in the editor..

**Comment by volzhs** [comment]
@bojidar-bg Oh.. totally my bad. closing it...
