### ISSUE TITLE
Could not parse global class... But do not have sense

### ISSUE THREAD

**Issue by seeergi7** [godotengine/godot#68284]
### Godot version

Godot 4.0 Beta 4

### System information

Windows 10, Intel(R) Core(TM) i5-10600K CPU @ 4.10GHz  4.10 GHz

### Issue description

Hello gentlemen!

I am developing a project in Godot 4 Beta 1 and I have tried to move to Godot 4 Beta 4 because Beta 1 when compiling the app gave me this error "Transient parent has another exclusive child". The problem is that when opening the same project in Beta 4 I get the errors shown in the image.

![image](https://user-images.githubusercontent.com/25349508/200113729-75bb954d-35ed-421b-92d8-a81a553ff46e.png)

The problem and the madness is that I am trying to solve the
` Parse Error: Could not parse global class "NakamaSocket" from "res://addons/NakamaNetwork/socket/NakamaSocket.gd".`

And when I go to Autoload, the NakamaSocket singelton does not appear and when I try to add it it appears that it already exists. And as you can see, there is nothing. is it a bug? or is there something I am missing?
![image](https://user-images.githubusercontent.com/25349508/200113745-046ef6ac-d4f5-4b88-9d71-5830c7f057a1.png)
![image](https://user-images.githubusercontent.com/25349508/200113800-d5ac6819-5553-441c-a5dd-530bdc410e24.png)

### Steps to reproduce

To test this you can go here [https://github.com/heroiclabs/nakama-godot](url) to download the addons folder that contains all the information on client sockets and others, which is the one I am using. And open project.

**Comment by KoBeWi** [comment]
The error clearly tell you that the scripts are broken, hence the class is not available. As for autoload problem, a plugin can add an autoload that doesn't appear on the project's list.

Please attach a MRP with ready to test setup.

**Comment by seeergi7** [comment]
> The error clearly tell you that the scripts are broken, hence the class is not available. As for autoload problem, a plugin can add an autoload that doesn't appear on the project's list.
> 
> 
> 
> Please attach a MRP with ready to test setup.

How can my files be broken if they work perfectly in Godot 4 Beta 1? On the other hand. What do you mean by "attach to MRP"? I don't understand this.

**Comment by KoBeWi** [comment]
https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project

**Comment by Calinou** [comment]
@seeergi7 Bump :slightly_smiling_face: 

> Please attach a MRP with ready to test setup.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.

PS: Since no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.

**Comment by TheYellowArchitect** [comment]
I have gotten this error just now. The equivalent script of OP was attached to a resource in my case, with a class_name. The sneaky part about this is that from beta14 up to 4.0.1, it appears only on exported builds, never on editors. Will request re-opening once I get an MRP

**Comment by TheYellowArchitect** [comment]
I stripped down the project I'm working on, so it's essentially an MRP. I would strip it down to oblivion, but some errors won't happen.

**MRP**: [MRP.tar.gz](https://github.com/godotengine/godot/files/11130187/MRP.tar.gz)

**Error Log**: [error-log.txt](https://github.com/godotengine/godot/files/11130189/error-log.txt)

**Build (made for X11 linux)**: 
[ConflictResourceConflictExecutable.tar.gz](https://github.com/godotengine/godot/files/11130191/ConflictResourceConflictExecutable.tar.gz)

------------------

Reproduction Scenario:
1. Open the MRP
2. Export the project (Server Template, basically default choice with all resources/scenes loaded lol)
3. Open the project (./Server.x86_64)
4. Quit (Super+Q in my case)
5. The errors of the error log uploaded above display. That's a lot of script errors which I cannot fix in any way. They do not appear in the editor (if they do, its on opening so they are ignored), only on exported builds.

I am available for any kind of clarification or guidance, as this issue has halted my project (multiplayer game, cant test unless testers install godot and run the game from editor)

@Calinou @KoBeWi

**Comment by Calinou** [comment]
@TheYellowArchitect Please open a new issue, as the exact cause most likely differs.

**Comment by TheYellowArchitect** [comment]
You are right. I opened https://github.com/godotengine/godot/issues/75582
