### ISSUE TITLE
Editor ColorPicker color wheel preview incorrect in OKHSL / HSV mode

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot#68286]
### Godot version

4.0.beta4

### System information

macOS 12.6.1

### Issue description

It seems the color picker panel color wheel previews are rendering incorrectly if you modify the color in HSV mode. Possibly it's interpreting the values as something other than HSV? It works correctly as long as you use the RGB sliders, but if you switch to HSV mode the selected color is still correct, but the preview color wheel and gradient thing are incorrect. Possibly color wheel and gradient above is rendering the values as HSL (where lightness L=1 is white) instead of the intended HSV (where V=1 is a bright color). For difference see https://en.wikipedia.org/wiki/HSL_and_HSV 

See the attached screen capture.

https://user-images.githubusercontent.com/17763524/200117422-aec4de9d-7187-4124-880d-869e4cdc5632.mov

### Steps to reproduce

- Click a color parameter in the editor (for example a material Albedo color) to bring up the color picker
- Switch to HSV sliders by clicking the HSV tab
- Change the HSV sliders and observe the color wheel/gradient above to see the indicated location doesn't match the selected color

### Minimal reproduction project

This should be a general editor issue, rather than project specific

**Comment by lostminds** [comment]
Still the same in 4.0b13, the issue more specifically seems to be the "OKHSL" circle picker (that was the default, I only recently found there were others that work fine) that is should represent the points in the circle and bar as HSL values somehow confuses the input HSV bar values as if they were HSL instead of first converting them from HSV if they're changed. 

![Screenshot 2023-01-18 at 21 52 08](https://user-images.githubusercontent.com/17763524/213292253-ec1849ce-635f-4ebf-a1bf-c7cab24bba9f.jpg)

**Comment by hsandt** [comment]
It also surprised me, then I found these older issue https://github.com/godotengine/godot/issues/62120 and its PR https://github.com/godotengine/godot/pull/67534 which show that the 3rd slider was L (lightness) at some point, which would explain the pure white at 255.

Either
a. the wanted decision was to edit L and display it as V is a bug (a regression since it was L for a moment)
or
b. the wanted design was to edit V and the fact that the 3rd slider changes lightness is a bug (this would mean design changed since the time we were displaying L)

In case a. though, I'd expect the tab to change its name from HSV to HSL. We could also just have both tabs HSV and HSL always visible.

**Comment by lostminds** [comment]
Fixed when testing in 4.2.beta1

**Comment by Norrox** [comment]
this is still a thing in master - fresh compile 7529c0bec597d70bc61975a82063bb5112ac8879
![image](https://github.com/godotengine/godot/assets/13393087/aaae7de9-eabb-4ea3-bbf2-36156400c71c)

**Comment by lostminds** [comment]
Seeing the same issue, so re-opening. Might be that I was mistaken when not seeing the issue in 4.2b1 not checking the OKHSL mode properly. 

Still seems to be the issue that in the OKHSL mode color circle it's using the HSV V value as the L value for the HSL color, resulting in full white L=1 when V=1, which is not correct.

**Comment by lostminds** [comment]
Still present in 4.3beta2. And more specifically it looks like the issue is that when you set the V value (for example using the slider) in the OKHSL mode of the picker this is interpreted as a HSL L value, which results in incorrect color preview. However, if you just switch to the OKHSL mode and use the color areas to change the color the values are correctly interpreted.

https://github.com/godotengine/godot/assets/17763524/05e630d7-8619-483c-8fbb-ba797dd5ed71

**Comment by kerstop** [comment]
I think this is actually behaving as intended. in the original video the color wheel is in the OKHSL mode which uses the Oklab color space. The vertical bar on the right is not being passed into an hsv function but the L parameter of oklab. On [this](https://oklch.com/) site if you change the L parameter you can see that it can effect the available hues.

While I couldn't find a color picker that demonstrated the same wiggling, if you compare the difference between `oklab(10%,50%,50%)` and `oklab(5%,50%,50%)` on [this converter website](https://products.eptimize.app/color-convert/oklab-to-hsv) you can see that changing the L parameter also changes the hue there too.

**Comment by kerstop** [comment]
I am currently looking at solving this issue but do not know how to proceed. I could attempt to make the sliders work as expected, however after looking at the code it doesn't seem like that will be trivial to pull off. A simpler solution would be to change the OKHSL circle and color mode to OKHSV. This would make it consistent with the other color selector modes.

If I should leave it as HSL should I add regular sRGB HSL as well?

**Comment by lostminds** [comment]
[Converting](https://en.wikipedia.org/wiki/HSL_and_HSV#Interconversion) the HSV slider values to the correct HSL values for the HSL preview component sounds like it would be easier than rebuilding the graphical picker preview to show/pick HSV? And it would make it work as currently intended making the change just a bug fix, instead of a feature change removing HSL color picking. 

What issues have you run into that would make this difficult enough to propose chaning the preview to HSV instead?

**Comment by kerstop** [comment]
changing the circle should be a one line change on line 230 here. 
https://github.com/godotengine/godot/blob/e63c40e59c6650bdba02c2ceff3390ee9273ac46/scene/gui/color_picker.cpp#L220-L241
`okhsv_to_srgb` already exists in `OK_COLOR_SHADER` and v is already passed into the shader. Then there are a few similar changes to turn the OKHSL sliders into OKHSV.
Keeping it as hsl would require more changes to the code and I don't know if it would be better to keep the ui the same but add to the code base, or to change the ui to make the code (and ui) more consistent.  So I wanted to get some other opinions. I am a fairly new contributor and don't have any experience working on a project of this scale.

**Comment by lostminds** [comment]
> changing the circle should be a one line change on line 230 here.

Looking a little at the code I think you found the line that causes the issue. It looks like that line is assuming that h, s and v are actually hsl values, which is what they might be set to when clicking in the circle. So it works as expected when clicking, but when you use the sliders the h s v values will actually be set to the slider h s v values, and the display will be wrong. 

So a way to fix this could be to replace `okhsl_to_srgb` with `okhsv_to_srgb` as you suggest on line 230. But then instead look at the mouse tracking code and ensure the values this gets in `_uv_input` is converted from the hsl values the mouse input calculation is resulting in the OKHSL circle case to the hsv values the shader and color picking in general seems to expect.
