### ISSUE TITLE
RenderingDevice uses index offsets incorrectly

### ISSUE THREAD

**Issue by pkdawson** [godotengine/godot#68293]
### Godot version

v4.0.beta.mono.custom_build [8245e052c]

### System information

Windows 11, GTX 1060 (526.47)

### Issue description

`RenderingDevice::index_array_create` takes a `p_index_offset` and checks it as if it’s a number of indices, but `draw_list_bind_index_array` passes this value to `vkCmdBindIndexBuffer` which expects an offset in bytes.

https://github.com/godotengine/godot/blob/6882890a34528e056f13020798f4a473046990bb/drivers/vulkan/rendering_device_vulkan.cpp#L7754

https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdBindIndexBuffer.html

However, this same value is also passed (correctly) to `vkCmdDrawIndexed` by `draw_list_draw`.

https://github.com/godotengine/godot/blob/6882890a34528e056f13020798f4a473046990bb/drivers/vulkan/rendering_device_vulkan.cpp#L7860

So Godot effectively has two conflicting implementations of the index offset, and one of those implementations is broken. My suggested solution is to set the buffer offset to 0 for `vkCmdBindIndexBuffer`.

That fixes it for me, with draw commands from Dear ImGui. Here’s the before and after:
![index_offsets](https://user-images.githubusercontent.com/132955/200126223-2cd50857-24bb-493f-8059-62319591b340.png)

### Steps to reproduce

Try drawing anything with a non-zero index offset

**Comment by clayjohn** [comment]
This certainly looks like a problem that comes from always using an offset of 0. 

I agree with your proposed solution, do you mind turning it into a PR?
