### ISSUE TITLE
Image.Create() creates an image with size 0

### ISSUE THREAD

**Issue by Pantastic80** [godotengine/godot#68294]
### Godot version

4.0.beta4.official.e6751549c

### System information

Windows 10, NVIDIA GeForce RTX 3060

### Issue description

I create an image and use it as texture. In v4.0.beta3.official.01ae26d31 it worked perfect, and in the latest Beta it produces a image with 0/0 dimension.

These are the results of the code:
--- Debugging process started ---
Godot Engine v4.0.beta3.official.01ae26d31 - https://godotengine.org
Vulkan API 1.2.0 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3060
 
Hight: 1080 Width: 1920
--- Debugging process stopped ---

--- Debugging process started ---
Godot Engine v4.0.beta4.official.e6751549c - https://godotengine.org
Vulkan API 1.2.0 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3060
 
Hight: 0 Width: 0
--- Debugging process stopped ---

### Steps to reproduce

func _ready():
    var w = 1920
    var h = 1080
    var img = Image.new()
    img.create(w, h, false, Image.FORMAT_RGBA8)
    print("Hight: ", img.get_height(), " Width: ", img.get_width())

**Comment by raulsntos** [comment]
`Image.create()` is static in 4.0:

```gdscript
var img = Image.create(w, h, false, Image.FORMAT_RGBA8)
```

**Comment by KoBeWi** [comment]
Closing per above comment.
