### ISSUE TITLE
Importing .png doesn't respect Project Settings > Import Defaults.

### ISSUE THREAD

**Issue by prominentdetail** [godotengine/godot#68298]
### Godot version

4.0

### System information

windows 10

### Issue description

When importing new .png files to Godot, the settings in the Project Settings > Import Defaults > Texture 2D, does not get applied to the images.

### Steps to reproduce

Set Lossless mode to lossless in Project Settings, for Texture 2D.
Import a .png file.. Check the file's import settings, and you will see that it isn't set to Lossless.
Same happens if you set mipmaps off in the settings, it will import with that on. I assume it is broken for all properties.

**Comment by Calinou** [comment]
Are you using the texture in a 3D context? If so, **Detect 3D** will kick in and will override the compression mode, sRGB and mipmaps.

**Comment by prominentdetail** [comment]
Thanks for the info!
