### ISSUE TITLE
Very high CPU usage when installing a plugin

### ISSUE THREAD

**Issue by BobTheDeleter** [godotengine/godot#68290]
### Godot version

v3.5.1.stable.official [6fed1ffa3]

### System information

Windows 10, GTX 960, Ryzen 5 3600, 16gb RAM, GLES3

### Issue description

When installing a plugin through the asset lib, or simply by adding the files to the addons directory, the editor freezes and spends up to 30 seconds using 100% of my CPU to "re-import assets". Eventually, it does finish, but I don't think such high usage is intended.

### Steps to reproduce

Install a plugin via the asset library or by dragging the files into res://addons

### Minimal reproduction project

Had the same issue on a brand new project

**Comment by Calinou** [comment]
This is expected. Importing resources is expected to use 100% CPU, ideally from multiple threads (in 4.0 only).

**Comment by BobTheDeleter** [comment]
If importing

**Comment by BobTheDeleter** [comment]
I was installing Qodot, but if using all threads to import is intended, then I'll just close this issue. Thanks!
