### ISSUE TITLE
TouchScreenButton's touch area not scaling when zooming with Camera2D

### ISSUE THREAD

**Issue by adsn** [godotengine/godot#683]
By setting camera's zoom to 2,2 the graphic of the button is scaled down according to the scale factor.
The touch area remains at the size and position as if camera's zoom still was at 1,1.

http://www.mediafire.com/download/btwcf9m9kwl67t2/touch_button_fail.zip

**Comment by mshka** [comment]
did u find a solution for this problem cz its giving me a major setback in my game:/

**Comment by mshka** [comment]
@reduz is this a bug or is there something we can do about it?

**Comment by akien-mga** [comment]
Can somebody reproduce this issue in a recent build of the current master branch (2.0 alpha)?

**Comment by akien-mga** [comment]
Tested on the current master branch (thanks for the test project!) which should behave similarly to 2.0.2. It seems to work just fine there, regardless of the zooming factor, the touch area is well recognized (tested on Linux with emulate_touchscreen and on android).
