### ISSUE TITLE
`ShapeCast3D` Debug Shape is not updating when changing `Shape` property

### ISSUE THREAD

**Issue by Jasuse** [godotengine/godot#68304]
### Godot version

4.0 beta4 (but also present at master ``Nov 8``)

### System information

Windows 10

### Issue description

ShapeCast3D should be updated when changing Shape property
![anim](https://user-images.githubusercontent.com/61157367/200139424-00e5b878-362d-4a2c-976e-f0ec76f95dc3.gif)

### Steps to reproduce

Add ```ShapeCast3D``` to ```Spatial``` node
Change ```Shape``` 
Debug shape is only changed if changing ```ShapeCast3D``` `s properties 

### Minimal reproduction project

at prefabs/player.tscn
[RPGSample.zip](https://github.com/godotengine/godot/files/9944660/RPGSample.zip)

**Comment by snougo** [comment]
got the same issue recently, it's really annoying, I have to switch Tab to update Shape itself everytime when I changged the property.

**Comment by kleonc** [comment]
Regression from #65292. cc @AlmightyLaxz
