### ISSUE TITLE
Import 3d model view lags when physics is ticked in Generate section.

### ISSUE THREAD

**Issue by viksl** [godotengine/godot#68301]
### Godot version

4.0 b3 c#

### System information

Windows 10, Nvidia GTX 1660Ti, Vulkan

### Issue description

The 3d view of a model in the import window lags when you try to generate a collision mesh, depending on which method you use it seriously lags or just not so much (lots of frames dropped vs not many), if you view the model in the editor as part of a scene it doesn't cause any issues.

Trimesh works for me better (still dropping some frames), Decompose convex, Simple Convex work the worst so far.

### Steps to reproduce

Open the import window of a 3d model (use a model with more complex geometry if possible to make sure you get the issue in case a simpler model doesn't do the trick for you - I have no idea if it matters, for me I just have very low frame rates; or the test.glb in KayKit directory in the test project. don't try to run the project it might not work, just open it in godot and double click the test.glb file to open the import window), tick physics Generate section of a MeshInstance3D node you selected in the scene view, try to rotate around.

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/9944620/test.zip)

**Comment by viksl** [comment]
In beta10 I'm pretty sure the only method that drops frames (seriously) is the decompose convex.
Depending on precision it almost completely freezes the 3d viewport of the import window, at lower precision it's bearable - still stutterring.

**Comment by Calinou** [comment]
If you can compile from source, try using a [C++ profiler](https://docs.godotengine.org/en/latest/development/cpp/using_cpp_profilers.html) on a debug build to see what's taking the most time.

**Comment by viksl** [comment]
Well, no promises, I'll try to figure out if I can build godot or not at least :). I hope there's a stupid people proof tutorial for this hehe.
