### ISSUE TITLE
Issue With WorldEnvironment Node

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#6831]
**Operating system or device - Godot version:**
Windows 10 Pro x64
Godot 2.1 x64 Stable
**Issue description** (what happened, and what was expected):
Get this error while loading another scene with a world Environment node.
`WARNING: WorldEnvironment::_notification: World already has an environment (Another WorldEnvironment?), overriding`
**Steps to reproduce:**
Have 2 different non-inherited scenes, both with a World Environment Node. load scene 2 while in scene 1. 
**Link to minimal example project** (optional but very welcome):
Is the WorldEnvironment node a Persistent Object?

**Comment by reduz** [comment]
this is kind of expected, you should make sure scene1 is freed before
adding scene2 to the tree

**Comment by vonflyhighace2** [comment]
I see. I'll check my scene loading method to see if I'm adding the new loaded scene to the tree before deleting the old one.
