### ISSUE TITLE
Groups are lost when using them in TileMaps

### ISSUE THREAD

**Issue by robbertstevens** [godotengine/godot#68314]
### Godot version

v4.0.beta4.official [e6751549c]

### System information

Windows 10

### Issue description

When you have a scene that has a group, and you add this scene to the tileset. the group is lost when in a scene above it you call `get_tree().get_nodes_in_group("group-name")` both group set in the editor as in code.

I've included a test project.

### Steps to reproduce

- Create a tilemap/tileset.
- Create a scene that will be used in the tilemap/tileset and add that scene to a group
- Add the scene to the tileset
- Use the scene in your tilemap
- call `get_tree().get_nodes_in_group("group-name")`  in your code.

### Minimal reproduction project

[TileMapGroupSceneBug.zip](https://github.com/godotengine/godot/files/9945333/TileMapGroupSceneBug.zip)

**Comment by KoBeWi** [comment]
Adding the nodes seems to be deferred. They are in group, but you just need to wait 1 frame.
```GDScript
func _ready() -> void:
	await get_tree().process_frame
	print(get_tree().get_nodes_in_group("test-editor"))
	print(get_tree().get_nodes_in_group("test-code"))
```
