### ISSUE TITLE
XRCamera3D and VR Playspace do not spawn relative to the XROrigin3D

### ISSUE THREAD

**Issue by Kotzwinkle** [godotengine/godot#68312]
### Godot version

v4.0.beta4.mono.official [e6751549c]

### System information

Windows 10 & Pop OS 22.04, RTX3060 ti,  Steam Index

### Issue description

The XRCamera3D and VR Playspace do not spawn relative to the XROrigin3D.
The camera and playspace spawn relative the the world origin.
Although somehow, the controllers still spawn relative to the XROrigin3D.

### Steps to reproduce

1. Create an XR project.
2. Place all the necessary components (XROrigin3D, XRCamer3D, XRController3D)
3. Initialize and script all components
4. Move the XROrigin3D anywhere outside of the world origin
5. Launch game and notice that you(Camera) are positioned relative to the world origin

### Minimal reproduction project

[get-is-active-demo.zip](https://github.com/godotengine/godot/files/9945190/get-is-active-demo.zip)

**Comment by BastiaanOlij** [comment]
I think the issue lies with

> 4. Move the XROrigin3D anywhere outside of the world origin

We're only reacting to changes in the transform of XROrigin3D, we're not updating the starting transform. This is why only the camera is really in the wrong place.

See #68321 for a fix if I'm right.

**Comment by Kotzwinkle** [comment]
This appears to be correct. I threw a 1 second timer on the XROrigin3D,  translated it by 1, and the camera/playspace repositioned to the correct spot.
