### ISSUE TITLE
Symbols are not displayed in labels

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#6834]
Godot 2.2 alpha linux x32

@Zylann checked it QA https://godotengine.org/qa/8893/special-characters-in-labels

Godot doesn't display special characters from fonts for some reason.

**Comment by eon-s** [comment]
I don't see the emojis in Noto Sans, I see no text with Noto Sans Emoji/Color Emoji but can see the pencil.
![pencilnoto](https://cloud.githubusercontent.com/assets/10215987/19413390/eec02ee6-9301-11e6-8806-1af68ee275b8.png)
_this is with the Noto Sans Color Emoji_ 

Here, Noto does not show the pencil character if you edit the text:
[https://fonts.google.com/?query=noto+sans](https://fonts.google.com/?query=noto+sans)

Are you sure the font you had used includes the character?

**Comment by Zylann** [comment]
How did you get that pencil? Do you mean it's only included in a specific version of Noto?

**Comment by eon-s** [comment]
@Zylann you import only a single "specimen", the pencil is in the Noto Sans Emoji (imported in Unicode mode)

I don't know how to import many specimens in one set to allow characters and emojis in one font, maybe the custom mode is for that.

ps: in the PNG files created as resources, with regular noto I don't see any emoji

**Comment by ArcFutahito** [comment]
@eon-s On QA follow the link with charmap detailing the origin of the character. It is included in Noto Sans/Common and the main problem is it being inaccessible from a ttf file already included in project. So character is there, font is there, godot doesn't display it. 
Not sure about Noto Emoji, never saw that one.

**Comment by eon-s** [comment]
@ArcFutahito the screenshot suggest you are using Noto Sans Regular, I have tried downloading even extended versions and all show squares, checked the font with KfontView and it does not show any emoji-like symbol.

Can you share a link to the font that is supposed to have the emoji symbols and letters in the same file?

**Comment by ArcFutahito** [comment]
@eon-s I think noto regular should have it? 
https://www.google.com/get/noto/

**Comment by eon-s** [comment]
I was looking at other fonts, like Open Sans Emoji and Emoji One and realized something, looks like the fonts sometimes have missing parts and when that happens, some kind of fall back to a default font...

So, I have tried something and got this:
![fonthell](https://cloud.githubusercontent.com/assets/10215987/19437973/138cd43e-944e-11e6-878a-3d3bf9f23ec1.png)

That is the result of Noto Emoji Regular (a small set of symbols [https://www.google.com/get/noto/#emoji-zsye](https://www.google.com/get/noto/#emoji-zsye) ) and Noto Regular as fallback (which does not have any emoji).

I don't know if is the intended way to work with fonts on Godot but works.

ps: Noto Color Emoji does not works (I was confused, it seems), also other colored fonts, but may not be a Godot issue.

**Comment by ArcFutahito** [comment]
Huh. I need to try it with dynamic fonts. Also, can you tell me how exactly you added symbols to labels? I've tried a lot of stuff, nothing seems to work

**Comment by eon-s** [comment]
@ArcFutahito Import a font specimen with emoji
![symbolfonts1](https://cloud.githubusercontent.com/assets/10215987/19621165/44514ede-9862-11e6-9e6e-16477f81b530.png)
Mode Unicode, works on Bitmap and Distance Field

Then import a regular font, not sure if matters the mode
![symbolfonts2](https://cloud.githubusercontent.com/assets/10215987/19621174/6d45c52c-9862-11e6-8c71-2e1156fa5b15.png)

Create a lablel with emoji font and add the regular as fallback
![symbolfonts3](https://cloud.githubusercontent.com/assets/10215987/19621181/8d1f56e2-9862-11e6-96c2-99f82a85900e.png)

Modify the text on the label to update the display of the contents if already has something on it.

------------
Here comes the Strange Things(TM), you will see many symbols on the png's of the emoji fonts but some or many of those symbols won't appear in your font browser (like charmap for windows) if installed, and you can use only what you see there, not copypasting from a web browser (some work, many don't).

I think that maybe there is a different specification on the new fonts making it broken on systems or completelly unusable (like emojione on OSX or the colored fonts almost everywhere)

Made a project with the noto fonts included and used with the fallback and emojione imported too

[symbolfont.zip](https://github.com/godotengine/godot/files/545912/symbolfont.zip)

**Comment by ArcFutahito** [comment]
Hm. So I guess Dynamic Font isn't going to be a thing in my project. That sucks =\

**Comment by eon-s** [comment]
@ArcFutahito that mysterious custom mode may have something, because images are there but Unicode can't see them

**Comment by eon-s** [comment]
This feature can be considered added and working now on Godot 3
