### ISSUE TITLE
Scene tile not setting current camera

### ISSUE THREAD

**Issue by compmstr** [godotengine/godot#68347]
### Godot version

v4.0.beta4.official [e6751549c]

### System information

Linux (Pop OS), NVIDIA GeForce RTX 2060, Video Drive v 470.141.03

### Issue description

If you create a scene that contains a current Camera2D node, the camera does not get activated unless you re-set current on the camera in the node's _ready function.

If you add the same scene as a sibling of the tilemap instead of as a tile, it does properly set the camera without having to re-set it in _ready.

In the example project, the player.gd script has a commented out _ready function that sets the camera to current.

### Steps to reproduce

* Create a player scene with a camera attached
* Make sure that the camera has 'current' enabled
* Add the player scene to a Tilemap with a Scene Collection tile
* Notice that the camera is still the default camera when the scene starts.

### Minimal reproduction project

[SceneTileBugRepro.zip](https://github.com/godotengine/godot/files/9946853/SceneTileBugRepro.zip)

**Comment by KoBeWi** [comment]
I don't know what happens exactly, but if you look at remote tree, the camera has `current` set to false for some reason. Might be related to the scene being instantiated twice.
