### ISSUE TITLE
It is possible to define a `script` variable, overloading the Node's main script

### ISSUE THREAD

**Issue by anvilfolk** [godotengine/godot#68355]
### Godot version

f814e15c7f 

### System information

Windows 10

### Issue description

It is possible to define and/or export the `script` variable that exists in node.

In Godot 3.5.1, attempting to declare (or export) this variable would result in the following error:
`Parse Error: The member "script" already exists in a parent class`

So this is a regression in 4.0.

### Steps to reproduce

1. Create a `buggy_script.gd` script with `@export var script : Resource`
2. Assign `buggy_script.gd` to a node
3. Select that node (and check that a new variable `script` appears as part of `buggy_script.gd`)
4. Assign some other script to `buggy_script.gd`'s `script` variable

Watch mayhem ensue :)

**Comment by Zireael07** [comment]
Why does it even allow you to name an exported variable script in the first place? This should be forbidden.

**Comment by anvilfolk** [comment]
I think that's a much better description of the issue :)

**Comment by anvilfolk** [comment]
Updated issue to more represent the core problem rather than the effect :)

**Comment by KoBeWi** [comment]
There's actually a proposal that suggested this behavior (somewhat): https://github.com/godotengine/godot-proposals/issues/338
It was never intended though, it's a buggy coincidence.
