### ISSUE TITLE
3 to 4 converter: raise -> move_to_front

### ISSUE THREAD

**Issue by wdv4758h** [godotengine/godot#68357]
### Godot version

4.0.beta4

### System information

Linux

### Issue description

Didn't see raise() -> move_to_front() convert entry in [project_converter_3_to_4.cpp](https://github.com/godotengine/godot/blob/master/editor/project_converter_3_to_4.cpp), probably need one?

Ref: [Rename raise() to move_to_front() #60108](https://github.com/godotengine/godot/pull/60108)

### Steps to reproduce

As description, just wanna check if it's a missing.

**Comment by vincentmoreschi** [comment]
We would have to do more then just function rename since the function got moved to from node to canvas item, or is adding it to just the list of rename enough?

**Comment by akien-mga** [comment]
Just adding to the renames should be sufficient for most cases. While it's technically possible for users to have been using it on a Node that doesn't inherit CanvasItem, it's unlikely. If they do, they'll get an error, but they would anyway without performing the rename.
