### ISSUE TITLE
Gizmos don't clear on screen when environment background set to "keep"

### ISSUE THREAD

**Issue by thomasdorone** [godotengine/godot#68359]
### Godot version

Godot 4 beta 4

### System information

Mac os 13 2.3 GHz Dual-Core Intel Core i5 Intel Iris Plus Graphics 640 1536 MB

### Issue description

Gizmos freak out in Beta 4 when environment background is set to keep in Mac OS, mobile and froward +.
<img width="955" alt="Screenshot 2022-11-07 at 10 19 15" src="https://user-images.githubusercontent.com/104303630/200261254-14f7b2ac-328c-408e-9228-35cc71c19c79.png">

### Steps to reproduce

1. Add a new WorldEnvironment to the scene
2. Create a new environment
3. Set the Background mode to "Keep"
4. Rotate view in the editor

**Comment by Calinou** [comment]
This is expected. As mentioned in the [class reference](https://github.com/Calinou/godot/blob/ab7a807f2bfffa270ad0438eb646139db860537b/doc/classes/Environment.xml#L352), the mode *keeps* the previous framebuffer data. This allows slightly improving performance in fully indoor scenes, but it will look broken in scene that have their sky exposed in any way.
