### ISSUE TITLE
depth_draw_mode = 1 does not work with alpha or invisible objects.

### ISSUE THREAD

**Issue by prominentdetail** [godotengine/godot#68356]
### Godot version

v4.0.beta.custom_build [0b958971f]

### System information

windows 10

### Issue description

The following images show the box's material having depth_draw_mode = 1, which should draw the depth always.
"DEPTH_DRAW_ALWAYS = 1 --- Depth draw is calculated for both opaque and transparent objects."

The following pictures illustrate the depth being drawn on a quad.
picture one shows transparency set to Disabled:
![image](https://user-images.githubusercontent.com/10412778/200235382-07155f35-3b7c-4446-8ffa-f6762cba72b3.png)

picture two shows transparency set to Alpha:
![image](https://user-images.githubusercontent.com/10412778/200235433-b2d60843-4175-4154-93c2-f8d06ec2b2d7.png)

picture three shows transparency set to Opaque but the mesh instance's visibility is set to false:
![image](https://user-images.githubusercontent.com/10412778/200235470-156e5920-f793-4891-93e4-7f12b2a4bcd5.png)

In all situations, the depth should be drawn, but it isn't. 
:(

### Steps to reproduce

Set the material properties of the box, and see the results.

### Minimal reproduction project

[depthModeBug.zip](https://github.com/godotengine/godot/files/9948459/depthModeBug.zip)

**Comment by clayjohn** [comment]
Well, when visibility is false depth should not be written. But when transparency is true depth should still be written when the depth draw mode is set to always.

**Comment by prominentdetail** [comment]
> Well, when visibility is false depth should not be written. But when transparency is true depth should still be written when the depth draw mode is set to always.

How would I get it to draw the depth even when invisible? Because I need it to do that! :(

**Comment by prominentdetail** [comment]
> Does this occur when using the OpenGL renderer?

I switched the "render compatibility" to "gl_compatibility".. I assume that is what you are referring to?
However, it breaks my shader, because DEPTH_TEXTURE and INV_PROJECTION_MATRIX cause errors. I'm not sure how to fix that in order to test it, and I can't find any info on the godot docs.

**Comment by clayjohn** [comment]
Taking a closer look at this issue. I think this is a misunderstanding how the depth draw modes work. 

First, the depth texture shows you the results of the depth prepass. By default, only opaque objects are included in the depth prepass. To include transparent objects in the depth prepass, their transparency mode must be set to "alpha depth prepass". 

Second, the depth draw modes specify if depth is written during the main render passes (the regular opaque and transparent passes). An object with transparency set to "alpha" will write to the depth buffer during the transparent pass if its depth draw mode is set to "DEPTH_DRAW_ALWAYS". But this writing to depth won't be reflected in the depth buffer which is captured after the opaque prepass.

**Comment by prominentdetail** [comment]
> Taking a closer look at this issue. I think this is a misunderstanding how the depth draw modes work.
> 
> First, the depth texture shows you the results of the depth prepass. By default, only opaque objects are included in the depth prepass. To include transparent objects in the depth prepass, their transparency mode must be set to "alpha depth prepass".
> 
> Second, the depth draw modes specify if depth is written during the main render passes (the regular opaque and transparent passes). An object with transparency set to "alpha" will write to the depth buffer during the transparent pass if its depth draw mode is set to "DEPTH_DRAW_ALWAYS". But this writing to depth won't be reflected in the depth buffer which is captured after the opaque prepass.

Is there a way to get the depth data in a shader from the transparent pass?

**Comment by clayjohn** [comment]
> Is there a way to get the depth data in a shader from the transparent pass?

Not right now no. The depth data from the transparent pass only affects other objects that are drawn later in the transparent pass.
