### ISSUE TITLE
Incorrect caret placement for Line Edit when text is not left aligned.

### ISSUE THREAD

**Issue by tex111** [godotengine/godot#68360]
### Godot version

4.0 beta 4

### System information

Windows 10

### Issue description

The carat current aligns itself to the left of placeholder text which is the correct behavior for the left aligned use case. It does not change its relative position or behavior when alignment is changed however.

For center the expected behavior is to have the carat appear in the exact center of the field.
For right the carat should be to the right of the placeholder text and then appear the the left of subsequent text.

As it is now, the carat jumps when the placeholder text disappears and new text is entered.

### Steps to reproduce

![ex1](https://user-images.githubusercontent.com/55551426/200280104-96592c49-3f24-46a1-85dd-0e4826c7b7c4.PNG)
![ex2](https://user-images.githubusercontent.com/55551426/200280100-90f29099-7c57-4588-a98b-93bf0c3ae441.PNG)

**Comment by bruvzg** [comment]
> For center the expected behavior is to have the carat appear in the exact center of the field.

Not sure if I agree with this, this might place caret in the middle of the character and make it almost invisible. GTK+ and Qt seems to hide placeholder when input control is focused, probably we should do the same.

**Comment by tex111** [comment]
> > For center the expected behavior is to have the carat appear in the exact center of the field.
> 
> Not sure if I agree with this, this might place caret in the middle of the character and make it almost invisible.
> 
> GTK+ and Qt seems to hide placeholder when input control is focused, maybe we should do the same. On the other hand, Firefox and macOS seems to place caret in the center on top of text.

Hiding placeholder text does seem like the best solution. Thanks for creating a pull request.
