### ISSUE TITLE
It seems that you can only modify VERTEX in a vertex fragment

### ISSUE THREAD

**Issue by Redwarx008** [godotengine/godot#68378]
### Godot version

4.0B4

### System information

WIN10 VULKAN GTX1660TiMaxQ

### Issue description

When I modified VERTEX by passing it as an inout argument to a function outside the vertex fragment, it didn't look right.
![1](https://user-images.githubusercontent.com/50837890/200347485-123b5029-d4d4-4b73-b403-8d42e5963e02.PNG)
``` c
shader_type spatial;

void test(inout vec3 vertex)
{
	vertex.y = 10.0;
}
void vertex()
{
	test(VERTEX);
}
```

### Steps to reproduce

see mini project

### Minimal reproduction project

[vertex.zip](https://github.com/godotengine/godot/files/9953052/vertex.zip)

**Comment by Chaosus** [comment]
Interesting, look like a bug.

**Comment by clayjohn** [comment]
Interestingly, this code works:
```
void test(inout vec3 vertex)
{
	vertex.y = 1.0;
}
void vertex()
{
	vec3 vert = VERTEX;
	test(vert);
	VERTEX = vert;
}
```
