### ISSUE TITLE
Android exported app crash at launch

### ISSUE THREAD

**Issue by Barina** [godotengine/godot#6837]
**Operating system or device - Godot version:**
Windows 7 64 - Godot 2.1 stable / Godot 2.2 alpha

**Issue description** (what happened, and what was expected):
when exporting to Android app crash on launch living this big ugly output in logcat.

**Steps to reproduce:**
1. export to android platform
2. install and run
OR
1. run on android  device from editor

**Link to minimal example project** (optional but very welcome):
[log.txt](https://github.com/godotengine/godot/files/531512/log.txt)

**Comment by Barina** [comment]
After hours of testing I found that the problem was calling "Directory.new().dir_exists("res://some/folder")"

**Comment by vnen** [comment]
Mandatory question: are you sure your export template matches the editor version?

**Comment by Barina** [comment]
Of course I tried remove the godot folder in AppData and install the correct one several times keep jumping from 2.1 to 2.2 back and forth

**Comment by Barina** [comment]
This is the code which cause the crash:
![capture](https://cloud.githubusercontent.com/assets/370379/19414573/cda4e87a-9359-11e6-9047-7a76a34052ac.PNG)
(STAGES_PATH = "res://stages/a" for instance)
When I remove the whole if statement the game runs flawlessly

**Comment by volzhs** [comment]
and you don't have `res://stages/a` or have it?

**Comment by Barina** [comment]
I do have 
There's also an issue with File.new().file_exists()
It always return false

**Comment by volzhs** [comment]
I made a PR for crashing when using `Directory.dir_exists`
I'll investigate about `File.file_exists`

**Comment by Barina** [comment]
I'll test File.file_exists too (on 2.2) as I wasn't test it properly

**Comment by volzhs** [comment]
At least, Directory.file_exists("path") seems to return always false, which I'm investigating now.

**Comment by Barina** [comment]
Alright I didn't have much time but I did setup a project to test that issue
checking file gives false althou there's a file
directory check still crash
[log.txt](https://github.com/godotengine/godot/files/532078/log.txt)
I'll upload the project next time

**Comment by volzhs** [comment]
My test was wrong about `Directory.file_exists("path")`. I didn't include file on export.
I confirmed `Directory.file_exists("path")` works fine.
@Barina Did you include all files on export? try **Export Mode** to **Export all files in the project directory** at Project Export Settings > Resources.

**Comment by Barina** [comment]
Ok I'm home.. yes I did include everything and I didn't change anything in the export or settings (only basic stuff like custom resolution and main scene)
I'va uploaded the project to my drive folder here:
https://drive.google.com/open?id=0B54uADD0Gcm9ZmlsZk1rejhNTHc
I tried that on Godot's version 2.2 alpha from October 16 at 08:08 which I didn't compile myself..
I downloaded the build and the templates from here:
http://fixnum.org/godot/

**Comment by volzhs** [comment]
There was a similar issue for checking resources with `file_exists`
Actually, `res://scenes/another_scene.tscn` will be converted to `res://scenes/another_scene.scn` by option at Project Export Settings > Resources > Conver text scenes to binary on export when exporting.
So, checking by `file_exists("res://scenes/another_scene.tscn")` will return false because the file is not there anymore.
but `load()` or `preload()` works magically with internal resource mapping file.

There would be several options for this case.
* check with `.tscn` and with `.scn` also
* listing all files under the directory
* using `load()` function

**Comment by volzhs** [comment]
And app won't crash with latest compiled android templates.

**Comment by vnen** [comment]
BTW, you can also use the [`PathRemap` singleton](http://docs.godotengine.org/en/latest/classes/class_pathremap.html) to check if a given remap exists or not.

**Comment by Barina** [comment]
Ok so File.file_exists is working as expected (my bad of curse :D) 
But why Directory.dir_exists result in a crash? it doesn't matter if there is a directory or not it should return true\false
I really didn't know about PathRemap singleton! that could help me with another project.. good to know
I'll compile again maybe tomorrow (doesn't have much time these days) or maybe use one of those here:
http://fixnum.org/godot/

**Comment by volzhs** [comment]
@Barina That was a bug and fixed recently. so you need the latest compiled templates.

**Comment by Barina** [comment]
Yes I was just wondering lol.. I didn't see the source code :)

**Comment by volzhs** [comment]
scroll up, you can see a PR for this.

**Comment by Barina** [comment]
I didn't test it for a while but from last commit (20dd5a6) there's problems with Directory.dir_exists() on Android
I made this function to test it on Desktop (Windows) and Android:
```
	var path = "res://scenes/"
	var i = 0
	var dir = Directory.new()
	var file = File.new()
	while true:
		var target_dir = path + str(i) + "/"
		if not dir.dir_exists(target_dir): # <- causing problems again *
			#print(target_dir, " exist.")
			break
		print(target_dir, " exist.")
		var f = 0
		while true:
			var target_file = target_dir + str(f) + ".scn" # working with .scn for simplicity. 
			if not file.file_exists(target_file):
				print(target_file, " doesn't exist.")
				break
			print(target_file, " exist.")
			f += 1
		i += 1
```
On Windows it works great.
On Android the line with dir_exists function cause an infinite loop:
http://textuploader.com/d5h03
The content of the apk is valid and the hierarchy is:
- scenes
    - 0
        - 0.scn
        - 1.scn
        - 2.scn
        - 3.scn

Looks like its still return true even when there isn't any directory in that path causing infinite loop in that code
Another example:
```
	var dir = Directory.new()
	var path = get_node("LineEdit").get_text() # writing 'res://scenes/X' where X is some number
	if dir.dir_exists(path):
		print(path, " exist")
	else:
		print(path, " not exist")
```
In Windows everything works well..
While on android the path always exists. even if I put an empty string as a path.
That code will always print "X exist"

**Comment by vnen** [comment]
@Barina better open a new issue, otherwise your problem might be forgotten under this one since it's already closed.

**Comment by Barina** [comment]
Sure thing :)
