### ISSUE TITLE
is_button_pressed(JOY_VR_TRIGGER) not working

### ISSUE THREAD

**Issue by gbach** [godotengine/godot#68376]
### Godot version

3.5 stable

### System information

Ubuntu Jammy // Oculus Quest 2

### Issue description

I am developing a game for Oculus/Meta Quest 2, using GLES3, OpenXR 1.3.0.
The method "is_button_pressed" and also it's signal version "button_pressed" are not working properly:

Pressing the "middle-finger button" on the controler (aka "Hand Trigger") quickly fires "button_pressed" two times - button being 2, then 6.
The "Index Trigger", the button on the front of the controller does not fire anything.
"X" fires 8 and occasionally 11 after that.
"Y" fires 1 and some times 11 after that.
The mini-joystick is also not sending a button-press.

Same for the right hand-controller, for "A", "B" respectively.

### Steps to reproduce

Start a OpenXR-Project and bind the "button_press" signal of ARVR-Controller.

### Minimal reproduction project

[button_test.zip](https://github.com/godotengine/godot/files/9952357/button_test.zip)

I removed "android" and "plugin"-folders so save space. Hope that's ok.

**Comment by BastiaanOlij** [comment]
Not sure what is going on seeing XR tools uses all these inputs without issue and Malcolm exclusively works on his Quest. Will see if I can find some time to try the project and see if anything is setup incorrectly.

**Comment by gbach** [comment]
Thank you for having a look at it. I also tried a fresh project on 3.5 with the same results. My quest is at the newest firmware. If there is something I can help, you will let me know. Unfortunately the Quest is not working yet with 4 - hopefully the new bootloader will be done by Meta soon...
Keep up the great work!!!

**Comment by gbach** [comment]
It's working now in 4.1 using the predefined signals!

**Comment by akien-mga** [comment]
Thanks, closing then :)
