### ISSUE TITLE
Unicode parsing error when custom enum is declared in script with high value

### ISSUE THREAD

**Issue by Swarkin** [godotengine/godot#68383]
### Godot version

v4.0.beta4.official [e6751549c]

### System information

Windows 10 21H2

### Issue description

When declaring a custom enum in a script, the output constantly shows parsing errors like
`Unicode parsing error, some characters were replaced with spaces: NUL character`, or
`Unicode parsing error: Invalid unicode codepoint (12820000)`.

### Steps to reproduce

Declare an enum with a value over 1114111.
This is fine:
```
enum {
    foo = 1114111
}
```
however, this or higher numbers show `Unicode parsing error: Invalid unicode codepoint` in the output
```
enum {
    foo = 1114112
}
```

**Comment by dalexeev** [comment]
Couldn't reproduce this bug in beta 4 (on Linux). However, I noticed the following:

```gdscript
@tool
extends EditorScript

const T1 = 1114111
const T2 = 1114112
const T3 = (1 << 31) - 1
const T4 = 1 << 31
const T5 = (1 << 63) - 1

enum {
    E_T1 = 1114111,
    E_T2 = 1114112,
    E_T3 = (1 << 31) - 1,
    E_T4 = 1 << 31,
    E_T5 = (1 << 63) - 1,
}

enum Test {
    T1 = 1114111,
    T2 = 1114112,
    T3 = (1 << 31) - 1,
    T4 = 1 << 31,
    T5 = (1 << 63) - 1,
}

func _run() -> void:
    print(T1)      # 1114111
    print(E_T1)    # 1114111
    print(Test.T1) # 1114111
    print("---")   # ---
    print(T2)      # 1114112
    print(E_T2)    # 1114112
    print(Test.T2) # 1114112
    print("---")   # ---
    print(T3)      # 2147483647
    print(E_T3)    # 2147483647
    print(Test.T3) # 2147483647
    print("---")   # ---
    print(T4)      # 2147483648
    print(E_T4)    # 2147483648
    print(Test.T4) # -2147483648
    print("---")   # ---
    print(T5)      # 9223372036854775807
    print(E_T5)    # 9223372036854775807
    print(Test.T5) # -1
```

Named enums are limited to int32 for some reason.

**Comment by Chaosus** [comment]
@Swarkin Are you using a custom font in the editor?

**Comment by Swarkin** [comment]
I do, [JetBrains Mono](https://www.jetbrains.com/lp/mono/)

**Comment by vnen** [comment]
Can't reproduce this. If it was really a bug it might have been fixed already.
