### ISSUE TITLE
Have "Create" and "Add" options instead of "Add script" on node right click menu

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#6839]
Adding a script on a node can be done in two ways:
- Creating one
- Adding an existing one

But there is only one option in the right-click menu of a node in the hierarchy. Could we have the same options as in the inspector?

**Comment by eon-s** [comment]
I like this, the script section on the inspector is too far sometimes.

Or the "create script" dialog could be used add an existing script (as the menu name suggest), not sure how could be the UI in that case.

**Comment by Zylann** [comment]
@eon-s in that case the UI would not even be the one we have now, it would simply be a file dialog.

**Comment by volzhs** [comment]
I was trying to find simple easy way to do it. but I didn't find yet.
I like this way as you suggest.

**Comment by Zylann** [comment]
There is one case a file dialog would not cover though... scripts embedded in the scene. No idea how to make them available here. But at the same time, they don't even have a name, willing to do that would be unpractical anyways.

**Comment by eon-s** [comment]
@Zylann for the "Add" proper dialog you propose yes (should be easy to add too). 

If want to keep menu small with the current dialog with an Add and Create button (and to use with the script button on the tree), all the ways I'm thinking for it are confusing.
