### ISSUE TITLE
 Why is this tile_origin setting option missing?

### ISSUE THREAD

**Issue by xiaoliang6669** [godotengine/godot#68401]
0000000000000000000

**Comment by KoBeWi** [comment]
Can't you do the same with tile offset?

**Comment by KoBeWi** [comment]
In TileSet mode, open tile properties and it's under rendering tab:
![image](https://user-images.githubusercontent.com/2223172/200564721-ef02999d-7746-4293-b46d-8308cd44777d.png)
You set it per-tile, but you can draw this property in painting mode (third tab) to quickly set it for multiple tiles.

**Comment by xiaoliang6669** [comment]
> In TileSet mode, open tile properties and it's under rendering tab: ![image](https://user-images.githubusercontent.com/2223172/200564721-ef02999d-7746-4293-b46d-8308cd44777d.png) You set it per-tile, but you can draw this property in painting mode (third tab) to quickly set it for multiple tiles.


As expected, there is no unified setting. I have more than 800 pictures, and it seems that I can only set them with scripts
