### ISSUE TITLE
ScrollContainer overflow its parent-container when scrolling

### ISSUE THREAD

**Issue by jinyangcruise** [godotengine/godot#68405]
### Godot version

v4.0.beta4.official [e6751549c]

### System information

Windows 11, Vulkan API 1.2.0 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3060 Ti

### Issue description

when resize window, items in ScrollContainer/VBoxContainer in wrong position.
<img width="471" alt="right" src="https://user-images.githubusercontent.com/42859362/200527532-f3fe7996-8309-4ad4-b6a1-f0991817344a.png">
![bug](https://user-images.githubusercontent.com/42859362/200529792-195d154a-1691-42f1-a233-6ddf163c3658.png)

### Steps to reproduce

Run the provided project. 
Resize window to a smaller window. 
Scroll the left container.

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/9959671/test.zip)

**Comment by Chaosus** [comment]
This can be easily fixed by toggling `Clip contents` on ScrollContainer (Chapter).

**Comment by jinyangcruise** [comment]
> 

You are right. Thank You!
