### ISSUE TITLE
Spatial shader doesn't update continuously. Godot 4 beta 4 mac os 13

### ISSUE THREAD

**Issue by thomasdorone** [godotengine/godot#68419]
### Godot version

Godot 4 beta 4

### System information

Mac os 13 2.3 GHz Dual-Core Intel Core i5 Intel Iris Plus Graphics 640 1536 MB

### Issue description

When creating a spatial shader that uses TIME, the editor redraws only once every two seconds. If I switch to "Update continuously" It works, but then I get the popup that says it is considered a bug...

https://user-images.githubusercontent.com/104303630/200647012-5eb8a00b-c99c-4283-ab3c-5cc887aefd2c.mp4

### Steps to reproduce

Create a moving spatial shader attached to a Mesh3D and see if it updates continuously.

**Comment by Zireael07** [comment]
This is for performance reasons.

**Comment by clayjohn** [comment]
Have you changed any other editor settings? Like sleep_usec or anything like that?

I can't reproduce this bug on my machine using default settings. I tested with both the RD renderer and the OpenGL3 renderer.

**Comment by thomasdorone** [comment]
No I haven't, but I see that the renderer was set to "mobile" in all sections. When switching to forward+ it works correctly

**Comment by clayjohn** [comment]
Oh! I didn't test with the mobile renderer, that's a good clue. 

I can reproduce on the mobile renderer, PR incoming.
