### ISSUE TITLE
Godot 4 Beta 4 crashes on Save & Exit, Mac OS 13

### ISSUE THREAD

**Issue by thomasdorone** [godotengine/godot#68417]
### Godot version

Godot 4 beta 4

### System information

Mac os 13 2.3 GHz Dual-Core Intel Core i5 Intel Iris Plus Graphics 640 1536 MB

### Issue description

Godot 4 beta 4 crashes everytime I close godot and then choose save & exit on mac OS 13.

Process:               Godot [19573]
Path:                  /Applications/Godot_mono4.app/Contents/MacOS/Godot
Identifier:            org.godotengine.godot
Version:               4.0 (4.0)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-11-08 20:02:16.0168 +0200
OS Version:            macOS 13.0 (22A380)
Report Version:        12
Anonymous UUID:        5E7A494C-77E9-4103-225B-ED1CA5FEC6C1

Sleep/Wake UUID:       44AC89FF-5FF4-4B40-888A-5E500DAAD0CD

Time Awake Since Boot: 63000 seconds
Time Since Wake:       304 seconds

System Integrity Protection: enabled

Crashed Thread:        29

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Application Specific Information:
abort() called

### Steps to reproduce

1. On Mac Os 13, create a new scene in a project.
2. Click the window's quit red button.
3. Choose save and exit

**Comment by lostminds** [comment]
Tried this now on macOS 13.0.1 on 4.0.beta10 and didn't get a crash. @thomasdorone have you tried it in the latest beta to see if this bug still exists?
