### ISSUE TITLE
Random error CS0246 when build game in Godot 4 mono

### ISSUE THREAD

**Issue by avilches** [godotengine/godot#68411]
### Godot version

v4.0.beta4.mono.official.e6751549c

### System information

macOS Monterey 12.6

### Issue description

When a solution with different projects and using external libraries with `PackageReference include` is built, godot (or dotnet) shows a CS0246 error ` The type or namespace name 'xxxx' could not be found (are you missing a using directive or an assembly reference?)`, where xxx is not always the same library (and the dlls are present). The error appears randomly, sometimes the build works properly.

```
CSC : warning CS8785: Generator 'ScriptPathAttributeGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'InvalidOperationException' with message 'Property 'GodotProjectDir' is null or empty.' [/Users/avilches/Godot/Betauer4/Betauer.TestRunner/Betauer.TestRunner.csproj]
/Users/avilches/Godot/Betauer4/Betauer.TestRunner/TestRunner.cs(9,7): error CS0246: The type or namespace name 'NUnit' could not be found (are you missing a using directive or an assembly reference?) [/Users/avilches/Godot/Betauer4/Betauer.TestRunner/Betauer.TestRunner.csproj]
```
The warning with the `Property 'GodotProjectDir' is null or empty` message maybe is the cause, not sure about this of course.

The error happens when build from the editor or the command line with `dotnet build`.
`dotnet clean` or removing the `.godot/mono` doesn't fix the error. The dlls are present in the .godot/mono folders, available for msbuild.
![Screen Recording 2022-11-08 at 13 22 02 (1)](https://user-images.githubusercontent.com/194074/200574296-bec933b0-89fe-4227-9373-818bc3e0869d.gif)

dotnet --info
```
.NET SDK (reflecting any global.json):
 Version:   6.0.402
 Commit:    6862418796

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.6
 OS Platform: Darwin
 RID:         osx.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.402/

global.json file:
  Not found

Host:
  Version:      6.0.10
  Architecture: x64
  Commit:       5a400c212a

.NET SDKs installed:
  3.1.405 [/usr/local/share/dotnet/sdk]
  5.0.102 [/usr/local/share/dotnet/sdk]
  6.0.402 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```

### Steps to reproduce

Use the minimal reproduction project.
Just type `dotnet build` from the command line and after some tries, the error will start to appear, then will work. 
Using the editor, just click on the "Build" button.

### Minimal reproduction project

[error-CS0246-in-mono.zip](https://github.com/godotengine/godot/files/9961424/error-CS0246-in-mono.zip)

**Comment by avilches** [comment]
I'm still migrating more modules into my project (that means, adding more csproj to my solution), and now I got this error, which can be visible only through Rider with debug because the ExceptionUtils.LogException dump a native stacktrace only, instead the csharp stacktrace:

![image](https://user-images.githubusercontent.com/194074/200593000-58624881-4230-4707-8cce-c28fd63849f4.png)

The missing dll is present in the .godot/mono folder and before the error appears, there is some code using classes from this dll.

Not sure if it's related, if it isn't, I can create a new issue.

**Comment by raulsntos** [comment]
You seem to be using the **Godot.NET.Sdk** for your library projects, I don't think that's supported.

If you need to reference the Godot API you should be able to reference the [GodotSharp package](https://www.nuget.org/packages/GodotSharp) (make sure the version you use matches the version used by your game project because currently I don't think we can guarantee there won't be binary compatibility breakage).

I suspect the issue is caused by how the **Godot.NET.Sdk** sets the output path to be relative to the game project directory which means every C# project is using the same path which likely conflicts.

https://github.com/godotengine/godot/blob/60e25835a5d19dee9382052549d7f7a6523a6b97/modules/mono/editor/Godot.NET.Sdk/Godot.NET.Sdk/Sdk/Sdk.props#L19-L21

**Comment by raulsntos** [comment]
I think you might have misunderstood. What I meant was the game project should be the only one with `<Project Sdk="Godot.NET.Sdk/4.0.0-beta.4">` and the library projects should be using `<Project Sdk="Microsoft.NET.Sdk">` and then reference the GodotSharp package with `<PackageReference Include="GodotSharp" Version="4.0.0-beta.4" />`

**Comment by avilches** [comment]
Amazing, everything works right now. No warning, always finishes the build ok. Thank you very much, I close the issue.

**Comment by mattgangwer** [comment]
In version 4.0.1, I'm still seeing the complier warning for my Unit Test csproj:
`CSC : warning CS8785: Generator 'ScriptPathAttributeGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'InvalidOperationException' with message 'Property 'GodotProjectDir' is null or empty.'`

My project configuration has <Project Sdk="Microsoft.NET.Sdk"> and a <PackageReference Include="Godot.NET.Sdk" Version="4.0.1"/>

My project setup has the SLN file in the top folder, with the Godot game/ and test/ as sub folders:

RootFolder/
  GodotProj/
  TestProj/
