### ISSUE TITLE
Kinematic2d (Collision Layer/Mask)

### ISSUE THREAD

**Issue by RameshRavone** [godotengine/godot#6841]
Ubuntu 16.04, Godot (git clone)

Hi, as the title I seems docs are missing when comes to collision Layer and Mask
but as for as I can understand the mask scans for collision in layer something like 

OBJ1Mask == OBJ2Layer

so, this is my current condition

const BULLET_COLLISION_LAYER = 5
const FIGHTER_COLLISION_LAYER = 6
const ENEMY_COLLISION_LAYER  = 7

const BULLET_COLLISION_MASK  = ENEMY_COLLISION_LAYER
const FIGHTER_COLLISION_MASK  = ENEMY_COLLISION_LAYER
const ENEMY_COLLISION_MASK = FIGHTER_COLLISION_LAYER

hmmm, now as per the condition Bullet should not collide with the FIGHTER, But it does

**Comment by bojidar-bg** [comment]
Well, masks and layers are _bitwise_ masks, not just numbers. This means that you setupped the following layers/masks:
```
101 (5) - BULLET_COLLISION_LAYER
110 (6) - FIGHTER_COLLISION_LAYER
111 (7) - ENEMY_COLLISION_LAYER
```

And, it isn't `Mask==Layer`, but `Mask (bitwise and) Layer`, which means that layer 1 (...0001) would collide with mask 3 (...0011) but not with mask 2 (...0010). This allows for much more flexibility and uses of the mask/layer system.
If you still want to use layers as numbers, use `set_layer_mask_bit()` and `set_collision_mask_bit()`.

**Comment by akien-mga** [comment]
Archiving as not an engine issue.
