### ISSUE TITLE
MultiMeshInstance3D: Changes in the transform of instances stay after game is closed

### ISSUE THREAD

**Issue by OvercookedRoach** [godotengine/godot#68421]
### Godot version

v4.0.beta4.official [e6751549c]

### System information

OpenSUSE Tumbleweed 20221102, Vulkan

### Issue description

Changes made in a `MultiMesh` instances by code stay after the game is exited. When the game is started again, it maintains the changes made in the previous run (when referencing the instances last position).

### Steps to reproduce

1. Create a `MultiMeshInstance3D` node and populate a surface.

2. Add a script to the `MultiMeshInstance3D` node and alter its instances transform.

Example:

```gdscript
func _ready():
    for index in range(multimesh.get_instance_count()):
        # Get the position
        var pos: Vector3 = multimesh.get_instance_transform(index).origin
        # Elevate it by 1 based on instance's own position
        pos.y += 1.0
        # Set the position
        multimesh.set_instance_transform(index, Transform3D(Basis(), pos))
```

4. After each run, the instances position get higher and higher.

### Minimal reproduction project

[multimesh_bug.zip](https://github.com/godotengine/godot/files/9964576/multimesh_bug.zip)

**Comment by Zireael07** [comment]
Why do you expect the transform to reset? The equivalent code for any other Node, be it 2D or 3D, would have the same result.

**Comment by OvercookedRoach** [comment]
It looks like the runtime code is changing the `MultiMesh` data. I just tried the equivalent code with `Node3D` and `Node2D` and it worked as expected.

In the case of `MultiMesh`, the alterations are kept even after restarting the engine.

**Comment by clayjohn** [comment]
I can't reproduce this issue on Beta13 the instances are in the same place every time I run the scene.
