### ISSUE TITLE
Input.get_vector returns incorrect values when action set to All Devices

### ISSUE THREAD

**Issue by adamscoble** [godotengine/godot#68433]
### Godot version

4.0.beta4

### System information

Windows 10

### Issue description

Hi all,

If I create four axis actions (up, down, left and right) all set to "All Devices" and then use `Input.get_vector()` to get a circular value, I receive unpredictable results when I use the joystick on an Xbox One controller. (In particular, full-up or -down return zero.)

Changing "All Devices" to "Device 0" fixes the issue, but I want the user to be able to hot swap any controller.

### Steps to reproduce

- Create four input actions: `look_up`, `look_down`, `look_left`, `look_right`
- Assign them to Right Stick <direction>, All Devices
- Use the following to see odd returned values:
```
var input: Vector2 = Input.get_vector("look_left", "look_right", "look_down", "look_up")
print(input)
```

**Comment by tttttm-gh** [comment]
I can still reproduce this issue in the latest beta.

However in my case setting mappings to `Device 0` does not result in correct input values.

### Godot version
`4.0.beta17`

### System information
- Arch linux
- Xbox One X|S wireless controller

### Minimal reproduction project
[controller-input.zip](https://github.com/godotengine/godot/files/10661579/controller-input.zip)

**Comment by felaugmar** [comment]
@adamscoble and @tttttm-gh if possible, could you please bring more data about your controllers?

The following piece of GDScript code will list the device's **guid** and **name** recognized by the Godot:

```gdscript
for device in Input.get_connected_joypads():
  print('guid: "%s"' % Input.get_joy_guid(device))
  print('name: "%s"' % Input.get_joy_name(device))
  print()
```

**Comment by tttttm-gh** [comment]
@felaugmar I ran your snippet, here's the output:
```
guid: "050000005e0400008e02000030110000"
name: "Xbox Wireless Controller"
```

**Comment by felaugmar** [comment]
@tttttm-gh looks like your controller isn't mapped in the database.

If the issue is really about the missing mapping, new mappings can be added and tested in runtime.
I don't have the controller and unfortunatelly can't test myself, but I'll show a little guide below.

You can register "custom mappings" and test them with this function: [`Input.add_joy_mapping`](https://docs.godotengine.org/en/stable/classes/class_input.html#class-input-method-add-joy-mapping).
The mapping accepted by this function is in a common format used by SDL2.

For reference, this repository explains about the format and instructs at creating new mappings: https://github.com/gabomdq/SDL_GameControllerDB.

**Comment by adamscoble** [comment]
@felaugmar Sorry for the delay! Here's my output, in case it's relevant, the controller is an Xbox Elite Series 2 connected via Bluetooth:

```
guid: "__XINPUT_DEVICE__"
name: "XInput Gamepad"
```

**Comment by felaugmar** [comment]
@adamscoble The code below constains the equivalent of `Input.get_vector`, implemented in GDScript.

Just attach it to an empty node, run and you can debug to find more details about the problem.
Sorry for not being of more help, but I can't reproduce the issue as the `Input.get_vector` works fine with my controller.

```gdscript
extends Node

const _LL := &'look_left'
const _LR := &'look_right'
const _LU := &'look_up'
const _LD := &'look_down'

@onready var _look_avg_deadzone := 0.25 * (
  InputMap.action_get_deadzone(_LL) +
  InputMap.action_get_deadzone(_LR) +
  InputMap.action_get_deadzone(_LD) +
  InputMap.action_get_deadzone(_LU)
)


func _process(delta: float) -> void:
  var input := InputUtils.get_vector_from_raw_strengths(
    Input.get_action_raw_strength(_LL), Input.get_action_raw_strength(_LR),
    Input.get_action_raw_strength(_LU), Input.get_action_raw_strength(_LD),
    _look_avg_deadzone
  )
  print(input)


# based from `Input.get_vector`'s cpp implementation
func get_vector_from_raw_strengths(
  negative_x : float,
  positive_x : float,
  negative_y : float,
  positive_y : float,
  deadzone := 0.5
) -> Vector2:
  var vector := Vector2(
    positive_x - negative_x,
    positive_y - negative_y
  )

  # Circular length limiting and deadzone.
  var length := vector.length()

  if length <= deadzone:
    return Vector2.ZERO
  elif length > 1.0:
    return vector.normalized()
  else:
    # Inverse lerp length to map (p_deadzone, 1) to (0, 1).
    return vector * inverse_lerp(deadzone, 1.0, length) / length

```

**Comment by adamscoble** [comment]
@felaugmar Thanks for that! Just to clarify, I was receiving correct results when I specify a device (e.g. `Device0`). It was only when set to `All Devices` that the values were incorrect. I can double check it's still happening in 4.1 soon, but just to confirm: you receive correct values with `All Devices`?

**Comment by adamscoble** [comment]
@felaugmar Sorry for the delay, I just tried this again in 4.1.beta2.official and am seeing an issue though I'm not sure if it's exactly the same, or just related. It seems to be the same issue to me (adding unused controller values to the output value).

1. Follow the same steps as the original issue.
2. Connect your controller.
3. Hold a keyboard button and look at the output `input` value. 

One axis _should_ be `1`, the other `0` if you press a single key, however I get values such as `(0.998444, 0.055762)` if either:
- the application has just started, or 
- for a short while after using the controller.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating with https://github.com/godotengine/godot/issues/45628, as this is the same underlying issue.
