### ISSUE TITLE
[Godot 4 Beta 4 C#] Godot Editor Crashes to Desktop when Loading Project with "System Error - Exception Processing Message 0xc0000005 - Unexpected parameters"

### ISSUE THREAD

**Issue by valkyrienyanko** [godotengine/godot#68443]
### Godot version

4.0.beta4.mono

### System information

Windows 10, AMD RX 6600 GPU, Intel 10400 CPU

### Issue description

Godot editor crashes when loading the project. Sometimes the editor loads in the background, sometimes I just see the error message box. When the editor does load in the background, I can click on buttons in the editor but nothing works and clicking on buttons freezes the editor. Closing the error message closes Godot.

![image](https://user-images.githubusercontent.com/6277739/200774609-373bc328-b739-4290-a9cb-30a0d12a7cae.png)

![image](https://user-images.githubusercontent.com/6277739/200774419-c4781e37-8af2-4655-bfe0-af095d2ea947.png)

I suspect this is happening because of Godots source generators not regenerating code properly and it might have something to do with the generics I added in [this commit](https://github.com/Valks-Games/sankari/commit/5adb79653ce121f9edbb2a45841b210e1a6cb453). **Note that if this commit is reverted, this issue no longer happens.**

Deleting the `.godot` folder fixes this, but the issue comes back again when modifying the `MovingEntity.cs` script with enough significant changes to trigger Godot source generators.
 
This issue was discussed in the Godot discord in the #csharp channel. The first message that started the discussion can be found [here](https://discord.com/channels/212250894228652034/389794884585914368/1039787759268802560).

### Steps to reproduce

1. Clone the [fix-225](https://github.com/Valks-Games/sankari/tree/fix-225) Sankari branch
2. Make enough changes to the [MovingEntity.cs](https://github.com/Valks-Games/sankari/blob/fix-225/Scripts/Entities/MovingEntity.cs) script to trigger Godot source generators (**It is important that you modify the [MovingEntity.cs](https://github.com/Valks-Games/sankari/blob/fix-225/Scripts/Entities/MovingEntity.cs) script, modifying any other script will not trigger this error after relaunching Godot again**)

This is the code I added to trigger Godot source generators (sometimes a simple `//` comment change to the script won't be enough). The green marked lines are the new lines of code I added.

![image](https://user-images.githubusercontent.com/6277739/200775640-7a8f1ca4-ef90-4cf5-8ca5-468375b313e8.png)

3. Launch Sankari project through Godot
4. Notice the error message and you will be forced to close Godot
5. Delete `.godot` folder in the project directory
6. Launch Sankari project through Godot
7. Notice how everything works fine now
8. Repeat steps 2 to 4 to get the error again

### Minimal reproduction project

I was not able to reproduce this issue in a blank Godot project.

**Comment by valkyrienyanko** [comment]
[This commit](https://github.com/Valks-Games/sankari/commit/18f53425ad4f6cc06649413e4bad39b6c6c96388) resolves this issue. The reason I was making `MovingEntity<T>` a generic in the first place was to avoid the hassle of adding a new property every time I create a new animation type class. (see the changes in the commit I linked to see what I'm talking about)

I will keep this issue open because it took a good chunk out of my day (4 hours). As of writing this it is 3:19 AM, I am just glad I was able to narrow down the issue to the point where I can live without it if I wanted to.

By keeping this issue open I hope that someone will look into the Godot source generators and find any weird things going on revolving around generics so maybe in the future I will be able to bring these changes back that this latest commit reverted for my project.

**Comment by raulsntos** [comment]
I don't see how this could be related to source generators. If it's related to generics it's more likely an issue with reflection where the type is unbound.

It might be helpful to see the output in the console when the error happens, try opening Godot in verbose mode:

```bash
godot4.exe --verbose --path [Path to Godot project]
```

**Comment by valkyrienyanko** [comment]
I ran Godot with `--verbose` flag and I spotted an error that happened right during the crash / popup error message. Full logs attached below as a gist.

![image](https://user-images.githubusercontent.com/6277739/201406011-b586a4c6-74d2-41a2-847d-abdeaed3a721.png)

Full logs: <https://gist.github.com/valkyrienyanko/0094d7639d1804dac8b60adf35deeb71>

**Comment by raulsntos** [comment]
Sounds like https://github.com/godotengine/godot/issues/67537

**Comment by imogenlay** [comment]
I had a different problem but with the exact same crash log as @valkyrienyanko 
The editor would crash upon trying to open the project. My fix was to delete the mono Debug folder:
projectname\.godot\mono\temp\bin\Debug

**Comment by MrZak-dev** [comment]
similar console log error in #67140.

**Comment by valkyrienyanko** [comment]
Closing as Godot 4 Beta 8 seems to have fixed this. I hope this issue never comes back fingers crossed!

**Comment by valkyrienyanko** [comment]
Nvm the issue came back after these 2 commits. Exact same popup / error in --verbose console. 😭 

https://github.com/Valks-Games/sankari/commit/190aac79cfc4587fffcf21499538da95fc4e60d4
https://github.com/Valks-Games/sankari/commit/cb2897896535f3e27fcb82d33ae714efff8448e1

**Comment by imogenlay** [comment]
This bug has returned for me as well, I was free of it for a month 😢
Now it is caused by some conflict between building the project and plugins. I try and build the project, it fails because of an ExportPlugin (I only have one plugin and it is an inspector plugin). Then a bunch of errors appear in the MSBuild console, sometimes when I try and open these errors, it gives me the old 'Attempted to read or write protected memory'.


![picture](https://user-images.githubusercontent.com/70460604/208288874-37c49706-0c52-4e48-b4ee-ce1cce9a6570.png)

**Comment by valkyrienyanko** [comment]
Linking this issue as has similar error to mine https://github.com/godotengine/godot/issues/67140
