### ISSUE TITLE
[4.0] Rendering of bitmap fonts ignores color of associated image

### ISSUE THREAD

**Issue by Zorochase** [godotengine/godot#68458]
### Godot version

4.0.beta4.mono

### System information

Windows 11, Vulkan (forward_plus), NVIDIA GTX 1060

### Issue description

Here's how my bitmap font renders in Godot 3:

![FontInGodot3](https://user-images.githubusercontent.com/101901701/200899842-77a9fc8f-7356-4260-8c65-296e30155f7c.png)

This is how I expect the font to look.
However, this is what it looks like in Godot 4:

![FontInGodot4](https://user-images.githubusercontent.com/101901701/200899913-99350ad4-2a24-48d8-b787-70941d812c55.png)

### Steps to reproduce

Create a bitmap font with, for example, white characters with a black shadow. Import the .fnt file and the associated image into Godot. Then, either create a Theme resource and apply the font, or create a Control scene with a Label and/or RichTextLabel and apply the font to the theme override.

### Minimal reproduction project

[BitmapFontColorIssueMRP.zip](https://github.com/godotengine/godot/files/9973709/BitmapFontColorIssueMRP.zip)

**Comment by Calinou** [comment]
The issue might be specific to BMFont, as I've been able to use colored fonts using monospace image imports (see https://github.com/godotengine/godot-docs/pull/6373).

**Comment by bruvzg** [comment]
What app was used to generate this font? Your `fnt` file channel data (`alphaChnl=0 redChnl=4 greenChnl=4 blueChnl=4`) is set to only alpha channel contains glyphs data, and the color channels are filled with sold white (so rendering seems to be correct).

If you have edited the image, you should also change `fnt` file to reflect it - `alphaChnl=0 redChnl=0 greenChnl=0 blueChnl=0`

**Comment by Zorochase** [comment]
> What app was used to generate this font? Your `fnt` file channel data (`alphaChnl=0 redChnl=4 greenChnl=4 blueChnl=4`) is set to indicate that only alpha channel contains glyphs data, and the color channels are filled with sold white (so rendering seems to be correct).
> 
> If you have edited the image, you should also change `fnt` file to reflect it - `alphaChnl=0 redChnl=0 greenChnl=0 blueChnl=0`

I used [this .fnt generator](https://github.com/burakyucel07/angelcode-fnt-generator) by @burakyucel07. There were no fields to edit the color channels in the app and I didn't set those values myself. Changing the channel values in the `fnt` file the way you said did seem to fix the issue, but I'm curious as to why the font seemed to render fine in Godot 3 despite having incorrect values.

**Comment by bruvzg** [comment]
> but I'm curious as to why the font seemed to render fine in Godot 3 despite having incorrect values.

Godot 3.x is not checking the channel values (and most of the other `.fnt` config), and always loading image as is. So it doesn't support bitmap fonts with outlines in the separate channel, bitmap fonts with different glyphs packed in the different channels, 4-bit color glyph + outline and other types, only RGBA8 images.

Since there's software that is generating fonts with this kind of channel config, we probably should add a special case to handle it (it should not conflict with any other valid config).

**Comment by elvisish** [comment]
My font shows like this in 3.x:
![image](https://user-images.githubusercontent.com/16231628/235375510-291f2db2-1611-4fb8-b89a-ad0c4cc85959.png)

But like this in 4.0:
![image](https://user-images.githubusercontent.com/16231628/235375525-7b54417d-14b1-4183-9984-8af7a1d52cf1.png)

So this still seems to be broken?
