### ISSUE TITLE
Godot 4 crashes when typing anything into the docs search bar

### ISSUE THREAD

**Issue by Swarkin** [godotengine/godot#68452]
### Godot version

v4.0.beta4.official [e6751549c]

### System information

Windows 10 21H2

### Issue description

The Godot editor crashes without any errors in the console when opening the docs and trying to search for anything.
The last thing I did before this started happening was adding the smoothing addon in one of my projects..
I've tried removing it and using the docs search in another project without this addon, but it also crashes.

https://user-images.githubusercontent.com/102416174/200843197-e572da7b-443d-4ee7-9709-37b98511d442.mp4

Are there any other logs I can provide? 

### Steps to reproduce

Install the smoothing addon in any project and reload the editor (Not sure if this is related to this issue)
Press F1
Try to type anything.

### Minimal reproduction project

any

**Comment by clayjohn** [comment]
I can't reproduce this issue. I have tested on Windows 10 21H2 and on PopOS 22.04. In both cases I am able to search the editor help without crashing. 

It seems like the smoothing addon must be related. Are you referring to lawnjelly's smoothing addon (https://github.com/lawnjelly/smoothing-addon)? If so, can you confirm that you are using the 4.x version and not the 3.x version?

**Comment by Swarkin** [comment]
Yup I am, downloaded from the 4.x branch.

**Comment by Swarkin** [comment]
Still happening on Godot beta5.

**Comment by Swarkin** [comment]
I can definitely confirm that this is related to the smoothing addon.
This time, it worked fine after removing it, and broke again when adding it back.
This is how I can reproduce it every time:
https://user-images.githubusercontent.com/102416174/202294635-ff7f2f57-cb37-4f4c-994f-8342e017fb17.mp4

**Comment by Calinou** [comment]
@Swarkin Remember that for GitHub video previews to work, you need to have a blank line before *and* after the video URL. I edited your post accordingly, but remember to do this in the future :slightly_smiling_face:

**Comment by akien-mga** [comment]
CC @lawnjelly
