### ISSUE TITLE
Visual Shader - UVFunc -  Parameter pivot value not loaded correctly

### ISSUE THREAD

**Issue by thoced** [godotengine/godot#68463]
### Godot version

4.0 beta 04

### System information

Linux Ubuntu

### Issue description

When using a **UVFunc** node in the visual Shader. **The Pivot** parameter is not reloaded correctly. Although it is correctly saved in the *.tres file. The parameter pivot is always in the default value 0.5,0.5

### Steps to reproduce

1) Create a VisualShader resource
2) Add Node UVFunc
3) Add Node Texture2d 
4) Link UvFunc and Texture2d 
5) Link Texture2d and Output Node
6) Modify the pivot parameter
7) Write All

![image](https://user-images.githubusercontent.com/10273261/200942169-ba818d07-2a67-414b-bb08-39b3589fa87a.png)

In the file *.tres of the VisualShader File, the parameter pivot is correctly writing but when the file is loaded, the parametre pivot in the node is always 0.5,0.5

**Comment by Calinou** [comment]
cc @paddy-exe
