### ISSUE TITLE
only two digits displayed in color picker when changing editor display scale

### ISSUE THREAD

**Issue by mokalux** [godotengine/godot#68466]
### Godot version

4.0 beta 4

### System information

windows 10, nvidia geforce 1650, vulkan 1.2.0

### Issue description

Only 2 digits are shown in any color picker when changing editor display scale.

![color_panel_wrong_number_of_digits](https://user-images.githubusercontent.com/26754505/200977607-aa5ad42c-c17e-49d9-abe9-779cd72bae07.png)

### Steps to reproduce

Change godot editor display scale to 1.04 for example. Open any color picker, 255 will only show 25.

**Comment by Calinou** [comment]
This is likely caused by coordinate rounding causing the last digit to not be displayed.. The bug is likely in SpinBox code, rather than ColorPicker.

**Comment by fracteed** [comment]
Ouch, yes I just ran into this one as well, and was wondering why rgb was in a 0-25 range!
