### ISSUE TITLE
XR: materials rendering in wrong order

### ISSUE THREAD

**Issue by shocktail39** [godotengine/godot#68469]
### Godot version

commit dca5cb8e40fd2a348a59ea73c597eb742c14c980
edit: tested again in commit f3e6750a7e4702918e05f42b1376e30e652f2f90 , still happens

### System information

Linux Zen 6.0.7, RX 6600 XT, forward_plus and mobile backends

### Issue description

when running a project with xr enabled, things appear to draw in the wrong order.  here's how my scene looks in the editor.  this is correct, and it's also how it looks while running if xr doesn't initialize.

![image](https://user-images.githubusercontent.com/6035079/201015922-27169942-5b4d-432c-b652-1d2fedfc1df1.png)

and here is how it looks when running with xr.  note that the pale bricks are showing up in front of the grey bricks, and the tower on the left is getting completely drawn on top of aside from a small sliver on the bottom with no bricks behind it.

![image](https://user-images.githubusercontent.com/6035079/201015942-d54d8823-caac-4d25-9fe8-42d0b111c5ec.png)

### Steps to reproduce

just run a project with xr enabled.

### Minimal reproduction project

~~[ErrorReproduction.zip](https://github.com/godotengine/godot/files/9977917/ErrorReproduction.zip)~~

edit: more minimal reproduction [ErrorReproduction.zip](https://github.com/godotengine/godot/files/10061151/ErrorReproduction.zip)

**Comment by Calinou** [comment]
Are your materials set to be opaque (i.e. their transparency mode is **Disabled** and the mesh's **Transparency** property is `0.0`)?

**Comment by shocktail39** [comment]
yes, all materials have disabled transparency, and the mesh's transparency is 0.

**Comment by shocktail39** [comment]
hello.  this is still an issue, but strangely, https://github.com/BastiaanOlij/godot4_openxr_demo/ seems to render just fine.  i'm unsure what exactly i'm doing differently.

**Comment by BastiaanOlij** [comment]
The suspicion at the moment is that something is broken with the depth buffer override that OpenXR has, so the issue is actually the depth buffer not doing its job.

A workaround is enabling 2x MSAA as it will use the MSAA depth buffer.

I am looking into the issue.

**Comment by shocktail39** [comment]
this workaround worked for me.  thank you for mentioning it.

**Comment by luzader** [comment]
@shocktail39 I have just tried your MRP in beta 16 it looked fine in both eyes to me. I think this has been fixed.
Are you still seeing this?

```
Godot Engine v4.0.beta16.official.518b9e580 - https://godotengine.org
OpenXR: Running on OpenXR runtime:  SteamVR/OpenXR   0.1.0
OpenXR: XrGraphicsRequirementsVulkan2KHR:
 - minApiVersionSupported:  1.0.0
 - maxApiVersionSupported:  1.2.0
Vulkan API 1.3.205 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3080
```

**Comment by shocktail39** [comment]
ah sorry i'm late.  this is fixed as of the current RC.  thank you.
