### ISSUE TITLE
What is the command for tilemap to set multiple navigation

### ISSUE THREAD

**Issue by xiaoliang6669** [godotengine/godot#68467]
### Godot version

4.0-beta3

### System information

win10

### Issue description

![ppp1](https://user-images.githubusercontent.com/112788136/201003417-4f212846-499f-44c2-8b6e-d646be01c274.png)
![ppp2](https://user-images.githubusercontent.com/112788136/201003448-e56c4e74-cc13-4aa0-96e1-87fa7c809f7b.png)

### Steps to reproduce

Only one navigation can be set
![3](https://user-images.githubusercontent.com/112788136/201003505-5330b1d2-b1c1-45d5-ac26-d1033f226c63.png)

**Comment by Zireael07** [comment]
I think this is a better fit for the Q&A site.

**Comment by xiaoliang6669** [comment]
> I think this is a better fit for the Q&A site.

I think no one except the godot developer can understand some new features of 4.0, so I ask here

**Comment by Zireael07** [comment]
This is not the place to "ask", this is a place to report **bugs.**

**Comment by xiaoliang6669** [comment]
This is also a BUG

**Comment by xiaoliang6669** [comment]
The developer forgot to publish this command

**Comment by KoBeWi** [comment]
For some reason navigation polygon functions are missing `polygon_index` argument, unlike collision polygons.

**Comment by xiaoliang6669** [comment]
> For some reason navigation polygon functions are missing argument, unlike collision polygons.`polygon_index`

Can it be realized? Can you be more specific

**Comment by KoBeWi** [comment]
Seems like they take `NavigationPolygon` object as an argument. The polygons are inside that object.
I guess the description of the method can be improved.

**Comment by xiaoliang6669** [comment]
> Seems like they take `NavigationPolygon` object as an argument. The polygons are inside that object, so one NavigationPolygon may have multiple internal polygons defined. I guess the description of the method can be improved.

You mean I use NavigationPolygon to create the same navigation effect?

**Comment by xiaoliang6669** [comment]
![wwwww](https://user-images.githubusercontent.com/112788136/201082860-96abb131-dfa5-4be7-9404-634076eda352.png)
I have implemented this. A total of 1500 NavigationPolygons have been created

**Comment by KoBeWi** [comment]
```GDScript
var polygon= NavigationPolygon.new()
polygon.add_outline(outline1)
polygon.add_outline(outline2)
polygon.add_outline(outline3)
polygon.add_outline(outline4)
...
polygon.make_polygons_from_outlines()
```
Something like this probably.

**Comment by xiaoliang6669** [comment]
Not this function. Only one navigation shape can be set for each tile
![yyyyyyyy](https://user-images.githubusercontent.com/112788136/201091404-cf809b18-8653-4fd3-a9ca-f94f6f8be471.png)

**Comment by KoBeWi** [comment]
When you add multiple outlines, it will create multiple shapes.

**Comment by xiaoliang6669** [comment]
> When you add multiple outlines, it will create multiple shapes.

![bbbbb](https://user-images.githubusercontent.com/112788136/201092953-766e6f2a-9a0a-4775-8d01-0fbfe8a39dd3.png)

This is the command to set a navigation shape. How to add it will not increase

**Comment by KoBeWi** [comment]
The function adds NavigationPolygon resource, which can have multiple shapes. So you add shapes to NavigationPolygon and set it for the tile and then tile has multiple shapes from the polygon.

**Comment by xiaoliang6669** [comment]
> The function adds NavigationPolygon resource, which can have multiple shapes. So you add shapes to NavigationPolygon and set it for the tile and then tile has multiple shapes from the polygon.

Can you be more specific? How to write the command

**Comment by KoBeWi** [comment]
Just like the code you posted above. Does it not add multiple shapes?

**Comment by xiaoliang6669** [comment]
> Just like the code you posted above. Does it not add multiple shapes?
No, this command can only create one navigation shape

**Comment by xiaoliang6669** [comment]
> Can you attach some minimal project?
The map is too big. More than 800 320 * 240 maps can't be uploaded,

**Comment by KoBeWi** [comment]
Well by minimal I mean a simple scene with the script you use and some placeholder tileset.

**Comment by xiaoliang6669** [comment]
> Well by minimal I mean a simple scene with the script you use and some placeholder tileset.

[1.zip](https://github.com/godotengine/godot/files/9981079/1.zip)

**Comment by KoBeWi** [comment]
![image](https://user-images.githubusercontent.com/2223172/201115771-6861cc38-6204-4902-9691-85d5abc31068.png)
As you can see, there are multiple shapes. In the project you attached, there was a decomposition error. But even after fixing it, the shapes were so close next to each other that they looked like one shape.

Here's the code I used for the above image:
```GDScript
extends TileMap

func _ready():
	var bxy=Vector2()#Vector2(-160,-120)
	#bxy=Vector2(0,0)
	var shs=[]
	
	for a in 2:
		for b in 2:
			var fh = []
			fh.append(Vector2(a*40, b*40))
			fh.append(Vector2(a*40 + 20, b*40))
			fh.append(Vector2(a*40 + 20, b*40 + 20))
			fh.append(Vector2(a*40, b*40 + 20))
			shs.append(fh)
	
	var ps = get_tileset().get_source(0).get_tile_data(Vector2i(0,0),0)
	var polygon = NavigationPolygon.new()
	
	for a in shs.size():
		print(shs[a])
		polygon.add_outline(shs[a])
	polygon.make_polygons_from_outlines()
	ps.set_navigation_polygon(0,polygon)
```

**Comment by xiaoliang6669** [comment]
It's normal to use this command
polygon.vertices = PackedVector2Array(shs)

**Comment by smix8** [comment]
Your test project prints error `NavigationPolygon: Convex partition failed!` all over the place hence why the 2D navmeshes are not working.

This error means the NavigationPolygon outline arrays are wrong and / or they overlap / intersect with other outlines in the same NavigationPolygon resource so the NavigationMesh conversion fails.

NavigationPolygon outlines can not overlap in the same resource. They are outlines, not polygons! You need to first create the largest, outer outline followed by any inner, smaller outlines if needed in opposite winding order (to cut holes in the larger outline / later polygon).

Please see NavigationPolygon class doc [here](https://docs.godotengine.org/en/latest/classes/class_navigationpolygon.html) and navmesh usage doc [here](https://docs.godotengine.org/en/latest/tutorials/navigation/navigation_using_navigationmeshes.html).

**Comment by xiaoliang6669** [comment]
> Your test project prints error all over the place hence why the 2D navmeshes are not working.`NavigationPolygon: Convex partition failed!`
> 
> This error means the NavigationPolygon outline arrays are wrong and / or they overlap / intersect with other outlines in the same NavigationPolygon resource so the NavigationMesh conversion fails.
> 
> NavigationPolygon outlines can not overlap in the same resource. They are outlines, not polygons! You need to first create the largest, outer outline followed by any inner, smaller outlines if needed in opposite winding order (to cut holes in the larger outline / later polygon).
> 
> Please see NavigationPolygon class doc [here](https://docs.godotengine.org/en/latest/classes/class_navigationpolygon.html) and navmesh usage doc [here](https://docs.godotengine.org/en/latest/tutorials/navigation/navigation_using_navigationmeshes.html).

There is a problem with this function. The creation of this group of shapes in the collision body and navigation node is normal, and it is also normal to add them with polygon.vertices

**Comment by smix8** [comment]
No, the error message is very clear what is the problem, which is the invalid created outline Arrays which is a user error.

Look at your code and notice that many of the outlines that you add have at least one identical vertex position with one of the previous outlines and this overlap alone creates the error.

**Comment by xiaoliang6669** [comment]
> No, the error message is very clear what is the problem, which is the invalid created outline Arrays which is a user error.
> 
> Look at your code and notice that many of the outlines that you add have at least one identical vertex position with one of the previous outlines and this overlap alone creates the error.

It's irresponsible for you to say this. If you really want to say it, please provide the solution code, because I sometimes have no effect when I operate many shapes without overlapping vertices. For example, I subtract coordinates every time

**Comment by xiaoliang6669** [comment]
extends TileMap


# Called when the node enters the scene tree for the first time.
func _ready():
	var bxy=Vector2(-160,-120)
	#bxy=Vector2(0,0)
	var shs=[]
	for a in 12:
		for b in 8:
			var fh=[]
			fh.append(Vector2(b*20,a*20)+bxy)
			fh.append(Vector2(b*20+20,a*20)+bxy)
			fh.append(Vector2(b*20+20,a*20+20)+bxy)
			fh.append(Vector2(b*20,a*20+20)+bxy)
			bxy=bxy+Vector2(1,1)
			shs.append(fh)
	
	var ps = get_tileset().get_source(0).get_tile_data(Vector2i(0,0),0)
	var polygon = NavigationPolygon.new()
	
	for a in shs.size():
		print(shs[a])
		polygon.add_outline(shs[a])
	polygon.make_polygons_from_outlines()
	ps.set_navigation_polygon(0,polygon)
	
	pass # Replace with function body.

**Comment by xiaoliang6669** [comment]
```
extends TileMap

# Called when the node enters the scene tree for the first time.
func _ready():
	var bxy=Vector2(-160,-120)
	#bxy=Vector2(0,0)
	var shs=[]
	for a in 12:
		for b in 8:
			var fh=[]
			fh.append(Vector2(b*20,a*20)+bxy)
			fh.append(Vector2(b*20+20,a*20)+bxy)
			fh.append(Vector2(b*20+20,a*20+20)+bxy)
			fh.append(Vector2(b*20,a*20+20)+bxy)
			bxy=bxy+Vector2(1,1)
			shs.append(fh)
	
	var ps = get_tileset().get_source(0).get_tile_data(Vector2i(0,0),0)
	var polygon = NavigationPolygon.new()
	
	for a in shs.size():
		print(shs[a])
		polygon.add_outline(shs[a])
	polygon.make_polygons_from_outlines()
	ps.set_navigation_polygon(0,polygon)
	
	pass # Replace with function body.

```

**Comment by smix8** [comment]
You can use the [Geometry2D](https://docs.godotengine.org/en/latest/classes/class_geometry2d.html) class merge_polygons() function to preprocess and combine you individual, square shaped polygons to a valid outline array with no overlap / intersection.

**Comment by xiaoliang6669** [comment]
> You can use the [Geometry2D](https://docs.godotengine.org/en/latest/classes/class_geometry2d.html) class merge_polygons() function to preprocess and combine you individual, square shaped polygons to a valid outline array with no overlap / intersection.

I have handled it, but there are still missing polygons. You can see that when I add 1 to the above code coordinates, it is impossible to overlap. When 7 can still display 8, it will not be displayed. However, when I change to use the "add_polygon" function, it is completely normal, indicating that there is a problem with the "add_outline" function
