### ISSUE TITLE
Vulkan Clustered: Omni3D and SpotLight3D lights are not visible on macOS + AMD

### ISSUE THREAD

**Issue by BjarkePedersen** [godotengine/godot#68476]
### Godot version

v4.0.beta4.official

### System information

MacOS 12.5.1, Vulkan, Radeon Pro 560

### Issue description
🚨🚨🚨
Lighting from Omni3D and SpotLight3D is not visible when using rendering method 'forward_plus' on MacOS (Vulkan). The effects of the lights are visible when using SDFGI, but the the light itself is not visible. Directional lights work as expected.
<img width="1792" alt="Screenshot" src="https://user-images.githubusercontent.com/29751977/201060539-1c70c7de-f54f-4c0a-80c5-e005cbfae88d.png">

### Steps to reproduce

1. Create a OmniLight3D or SpotLight3D node.
2. No light is visible.

### Minimal reproduction project

[testo.zip](https://github.com/godotengine/godot/files/9979509/testo.zip)

**Comment by Intervel** [comment]
This happens on me today too, but im on windows 11, godot 4, beta 4

Im using one directional light plus spotlight, 

Result = directional light works, spotlight didn't.

Also directional light went through my tunnel scene, even though it has roof at the top? No idea what happens

**Comment by Zireael07** [comment]
@Intervel Unless your directional light is pointed straight down, it's expected when it comes to the tunnel

**Comment by Intervel** [comment]
It is pointed straight down. Im not on my PC rn. I can't show it

**Comment by lostminds** [comment]
Getting the same bug here on macOS 12.6.1 with an AMD Radeon Pro 560:
On the forward_plus renderer no 3d spotlights or omnilights seem to have any visible effect, directional lights work.
If I change to the mobil renderer they appear as expected.
If I run the same project on a Windows 11 machine it also works as expected.

**Comment by clayjohn** [comment]
Can anyone facing this issue confirm if the issue was present in beta 3 as well?

**Comment by lostminds** [comment]
> Can anyone facing this issue confirm if the issue was present in beta 3 as well?

Yes. I just re-downloaded beta 3 and tried the same project and no SpotLight3Ds visible on forward_plus renderer and macOS

**Comment by BjarkePedersen** [comment]
> Can anyone facing this issue confirm if the issue was present in beta 3 as well?

The problem appears to go as far back as the first alpha of Godot 4.

**Comment by BjarkePedersen** [comment]
> This happens on me today too, but im on windows 11, godot 4, beta 4
> 
> Im using one directional light plus spotlight,
> 
> Result = directional light works, spotlight didn't.
> 
> Also directional light went through my tunnel scene, even though it has roof at the top? No idea what happens

Which graphics card do you use?

**Comment by Intervel** [comment]
Rtx 3090

**Comment by Calinou** [comment]
> Also directional light went through my tunnel scene, even though it has roof at the top? No idea what happens

If you have a large unsubdivided mesh, you need to increase **Pancake Size** on the DirectionalLight3D for shadow casting to work.

**Comment by Intervel** [comment]
> > Also directional light went through my tunnel scene, even though it has roof at the top? No idea what happens
> 
> [If you have a large unsubdivided mesh, you need to increase **Pancake Size** on the DirectionalLight3D for shadow casting to work.](https://github.com/godotengine/godot/issues/60391)

sorry for the late reply, i was busy. 
i tried this, no luck. 

im using beta 5 currently, 

1. spotlight did not working on game play
2. directional3d went through tunnels even though it has roof on top.

here is my settings, check out my videos

https://streamable.com/71nyv0
https://streamable.com/y09mxh

**Comment by Intervel** [comment]
i was able to fixed my issues! thanks to clayjohn! 

just change the world enviroment camera setting aperture to 2 instead of 16

:)

**Comment by clayjohn** [comment]
Whoops should not have closed. I didn't realize the last comment was not from OP and was not actually facing this issue. re-opened and tags restored

**Comment by lostminds** [comment]
Just tried the forward_plus renderer on my project in 4.0.beta7 on macOS 13.0.1 and both 3d OmniLight and Spotlight seem to be working for me there now, which they did not previously. I've been working in the mobile renderer since beta4 so I don't know when this was fixed.  Maybe @BjarkePedersen  can see if it's fixed for them as well so you can close it for real this time @clayjohn

**Comment by BjarkePedersen** [comment]
Yes! It appears to be fixed since beta 5! Closing issue :)
