### ISSUE TITLE
Lost all animation data of a glb file and lights after reopening the project

### ISSUE THREAD

**Issue by inabird** [godotengine/godot#68474]
### Godot version

v3.4.5.stable.fedora [f9ac000d5]

### System information

Fedora Linux 36 (Workstation Edition)

### Issue description

I animated a PNG using armature in Blender and then exported it as a glb file since Godot did not allow me to import fbx files.

It was all good in the beginning. All keyframes were there, animation was just like how it behaved in Blender.
2 more spot lights and a plane of animated texture are further added to the scene.

Problem is, every time when I save the scene, a pop-up window will appear saying the glb file format is not recognised.
And after closing the project and reopening it, the animation are all gone

which includes

1. Mesh animation
2. Light animation

Only the texture animation is still running fine.

![Screenshot from 2022-11-10 15-48-00](https://user-images.githubusercontent.com/117072051/201032894-ec34c062-5f78-47ae-a8dc-dda31043a0ec.png)

(The animation was reduced to two frames and the light animation is gone)

Is there any way I can get my animation back?

### Steps to reproduce

1. Import glb to 2D scene
2. Added two spotlights and animated them
3. Save scene but got warnings
4. Close project
5. Reopen and lost all animation data

### Minimal reproduction project

[Uploading seahorse.zip…]()

**Comment by Zireael07** [comment]
Not a bug. Godot can't save glb. 

In Godot 4, IIRC you will be prevented from making changes that can't be saved.

Make an inherited scene and make the changes in it.

**Comment by inabird** [comment]
So is there anyway I can import Blender file with animation to Godot?
Wouldn't have worked with a glb file if I saw it failed to import...

**Comment by Zireael07** [comment]
Reexport the glb and just make an inherited scene if you want to change things in Godot itself.

Alternately use gltf as the format (but the same caveat about Godot not being able to save the format applies)

The popup on opening should be clear enough about this. It tells you to make an inherited scene if you want to make any changes...

**Comment by inabird** [comment]
Thank you! Will be more attentive about this next time
