### ISSUE TITLE
Automatic mesh LOD selection isn't affected by 3D resolution scaling

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#68484]
### Godot version

4.0 Beta 4

### System information

Windows 11, Vulkan, GTX 1050 Ti 516.94

### Issue description

Changing Project Setting Resolution Scale doesn't affect Automatic LOD

### Steps to reproduce

Load a Mesh with ALOD
Get to a distance where it is about to switch LODs
View Information (see primitive count)
Play with Resolution Scale
Observe no Change with LODs

### Minimal reproduction project

[ALOD.zip](https://github.com/godotengine/godot/files/9989122/ALOD.zip)

**Comment by Calinou** [comment]
@mrjustaguy Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by mrjustaguy** [comment]
updated. For some reason Half Resolution setting in the editor works as expected, just not Resolution Scale.
