### ISSUE TITLE
`StreamPeerTCP` doesn't connect to TCP servers

### ISSUE THREAD

**Issue by Hunam6** [godotengine/godot#68493]
### Godot version

4.0.beta4.official

### System information

MacOS Ventura 13.0 or Windows 11 21H2

### Issue description

Using the `StreamPeerTCP` class to connect to a TCP server/listener doesn't work. Well, it works from the server side, but the `StreamPeerTCP` class do not.

Using the exact same minimal reproduction project in latest stable Godot 3.x works.

### Steps to reproduce

- Start a basic TCP server/listener on any port (5005 in this example)
	-	<details>
		<summary>Click me</summary>
		This is an example code in NodeJS:

		```js
		const net = require('net');
		
		let server = net.createServer((socket) => {
		    console.log("Accepted connection.");
		}).listen(5005, () => console.log("Listening on 5005."));
		```
		Run it using `node file.js`.
		</details>
- Try to connect by running the very minimal reproduction project
- `Accepted connection.` will get printed on the server side ✅ 
- `TCP Connected.` will not get printed on Godot/client side ❌

### Minimal reproduction project

[minimal.zip](https://github.com/godotengine/godot/files/9984958/minimal.zip)

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot/issues/64699 and https://github.com/godotengine/godot/issues/62001.

**Comment by Hunam6** [comment]
I just looked at the issues you linked. The first one looks similar to the issue I have as it's stuck in the connecting phase too, otherwise they seem to be using some more hight level Class.

Can you expend on why being stuck on `STATUS_CONNECTING` makes sense in this scenario? I don't get how it could have to do with a compatibility breakage.

**Comment by timothyqiu** [comment]
Calling `tcp.poll()` before checking the status works for me.

**Comment by Hunam6** [comment]
> Calling `tcp.poll()` before checking the status works for me.

Thank you, I wasn't aware of this function, this fixed my issue.
