### ISSUE TITLE
Sprite2D with AnimatedTexture not displayed in Web export

### ISSUE THREAD

**Issue by AntonioDell** [godotengine/godot#68506]
### Godot version

4.0.beta4

### System information

Pop!_OS 22.04, Firefox and Chrome

### Issue description

When creating an AnimatedTexutre with 2 alternating frames and setting it inside a Sprite2D node, the Sprite is shown as pink rectangle in the browser.
Running the scene normally (not in browser) shows the desired effect. 

Pink rectangle in browser:
![Pink rectangle in browser](https://user-images.githubusercontent.com/29783330/201277030-d13a9c59-6e1c-48ef-99d7-541f3f169746.png)

Frame showing without browser:
![Frame showing without browser](https://user-images.githubusercontent.com/29783330/201277112-2248c696-228f-4569-91a9-7ed8f3bc0580.png)

### Steps to reproduce

1. Create a Sprite2D
2. Select AnimatedTexture in the Sprite2D
3. Add second frame to AnimatedTexture
4. Add any images to the 2 frames of the AnimatedTexture
5. Run project in browser (needs Web export template)

### Minimal reproduction project

[animated_texture_bug.zip](https://github.com/godotengine/godot/files/9987038/animated_texture_bug.zip)

**Comment by akien-mga** [comment]
Confirmed that AnimatedTexture doesn't seem to be working in the web editor either as of 140f0395470975f1c20648ffd8807be113a9e373.
