### ISSUE TITLE
add_child can no longer be shadowed

### ISSUE THREAD

**Issue by lonevox** [godotengine/godot#68500]
### Godot version

4.0beta4

### System information

W10

### Issue description

In Godot 3.5.1 you can shadow add_child to add your own logic. This is useful for detecting when a child is added to a node. I expected this to work in Godot 4.0beta4 but it doesn't.

### Steps to reproduce

3.5.1 code:
```gdscript
func add_child(node: Node, legible_unique_name := false):
	.add_child(node, legible_unique_name)
	print("I just fathered ", node.get_name())
```
Showing that a child has been added with add_child:
![image](https://user-images.githubusercontent.com/38600896/201239286-7ebc02a0-7a9e-4cd6-81e2-ed254c302598.png)

Showing that the above print statement is successful:
![image](https://user-images.githubusercontent.com/38600896/201239307-af2583f1-a9a9-4ca1-b551-1e9459d6547c.png)

4.0beta4 code:
```gdscript
func add_child(node: Node, force_readable_name := false, internal := 0):
	super.add_child(node, force_readable_name, internal)
	print("I just fathered ", node.get_name())
```

Showing that a child has been added with add_child:
![image](https://user-images.githubusercontent.com/38600896/201239754-f3dcca37-1223-4437-8877-bf25de6e6080.png)

Showing that the above print statement isn't ran:
![image](https://user-images.githubusercontent.com/38600896/201239813-ec0cc381-d664-4427-a7a3-cbd7ad33d3ca.png)

The code shown is within the minimal reproduction projects.

### Minimal reproduction project

[AddChildBug3.5.1.zip](https://github.com/godotengine/godot/files/9985679/AddChildBug3.5.1.zip)
[AddChildBug4.0beta4.zip](https://github.com/godotengine/godot/files/9985684/AddChildBug4.0beta4.zip)

**Comment by TheDuriel** [comment]
This is unfortunately intentional under the guise of "never having been intended, because the engine never called your override in the first place."

You will now have to fall back to a "custom_add_child()" function of your own making.

**Comment by lonevox** [comment]
I've found that there are child_entered_tree and child_exiting_tree signals, so this isn't needed.
