### ISSUE TITLE
Problem with inheritance

### ISSUE THREAD

**Issue by Begah** [godotengine/godot#68517]
### Godot version

4.0 dev

### System information

Linux mint, vulkan

### Issue description

My issue comes from the following piece of code :
```GDscript
var test : TestClass = $TestOverride as TestClass
print('--------------First invoke through base class')
test.test_function()
print('--------------Second invoke through call')
test.call("test_function")
print('--------------Third invoke through $Node')
$TestOverride.test_function()
print('--------------End')
```
`TestOverride` node is an instance of the TestOverride class defined below:

```GDscript
extends TestClass
	
func test_function():
	print("Test function inherited")
	super()
```

and TestClass is defined like so :
```Cpp
class TestClass : public Node {
    GDCLASS(TestClass, Node);

protected:
    static void _bind_methods();
public:

    void test_function();
};
-----
void TestClass::_bind_methods() {
    ClassDB::bind_method(D_METHOD("test_function"), &TestClass::test_function);
}

void TestClass::test_function() {
    print_line("TestFunction");
}
-----
GDREGISTER_CLASS(TestClass);
```

Therefore the output of this code should be:
```
--------------First invoke through base class
Test function inherited
TestFunction
--------------Second invoke through call
Test function inherited
TestFunction
--------------Third invoke through $Node
Test function inherited
TestFunction
--------------End
```

but instead what i get is:
```
--------------First invoke through base class
TestFunction
--------------Second invoke through call
Test function inherited
TestFunction
--------------Third invoke through $Node
Test function inherited
TestFunction
--------------End
```

### Steps to reproduce

Download the test project, put the custom folder in the modules folder of godot, compile and launch the project

### Minimal reproduction project

[TestProj.zip](https://github.com/godotengine/godot/files/9989975/TestProj.zip)

**Comment by RedMser** [comment]
I believe you aren't overriding any method, but merely shadowing it.

You'd need to declare the method as virtual (using `GDVIRTUAL_BIND` and `GDVIRTUAL*` macros) and add `GDVIRTUAL_CALL` to C++.

**Comment by Begah** [comment]
You may be right, but either way it still doesn't make much sense :
1) If the gdscript properly inherites, then the call to test.test_function() should work like the others
2) If the gdscript doesn't properly inherites, then why can i call super() in the shadowed function'

Either way, if it should work or not, the problem is that it partially work instead of completely working or not at all.
Not a huge priority anyway i would say.

**Comment by dalexeev** [comment]
> I believe you aren't overriding any method, but merely shadowing it.

Yes it is. Now there is a warning (which is treated as an error), so I think this issue can be considered resolved.

> Either way, if it should work or not, the problem is that it partially work instead of completely working or not at all.

See #55024 and #72608 for details on why this sometimes works and sometimes doesn't.
