### ISSUE TITLE
Clear the block error and always report the error

### ISSUE THREAD

**Issue by xiaoliang6669** [godotengine/godot#68522]
### Godot version

4.0-beta4

### System information

win10

### Issue description

![QQ图片20221111215023](https://user-images.githubusercontent.com/112788136/201354326-62df1436-174b-4f0f-9301-a17f7fe1a966.png)

### Steps to reproduce

![QQ图片20221111215051](https://user-images.githubusercontent.com/112788136/201354347-e0cc9e59-a4f6-4a94-a69c-550f36fa5568.png)

**Comment by clayjohn** [comment]
This isn't a bug. This is a valid warning that you are receiving. Please do as the warning suggests if you do not want the warning to be printed.
