### ISSUE TITLE
Documentation for group methods needed

### ISSUE THREAD

**Issue by rgrams** [godotengine/godot#6852]
**Operating system or device - Godot version:** All (docs)

**Issue description** (what happened, and what was expected):
Some important details about methods pertaining to groups are missing from the docs. There are no descriptions for _any_ SceneTree methods, including several pertaining to groups, and there's no info about add_to_group()'s second argument. There have been a couple questions on the Q&A about them, but they have gone unanswered. I'm particularly interested in:

SceneTree.call_group() - "int flags". There's a list of flags, but what do they do?

Node.add_to_group() - "persistent". It defaults to "false" which is confusing by itself, since nodes seem to "persist" in groups until removed.

**Comment by vnen** [comment]
> Node.add_to_group() - "persistent"

This is only used if you pack and save the node as PackedScene. Only persistent groups are saved into the file. Now it just needs someone to updated the docs.

**Comment by Noshyaar** [comment]
Still reproducible/relevant in 3.1 master 3ad9e47 : most methods in SceneTree, including group-related, aren't yet documented

**Comment by KoBeWi** [comment]
Seems like the issue is no longer relevant. Everything in SceneTree except `get_frame()` is documented.
