### ISSUE TITLE
Tooltip no longer works properly when selecting multiple nodes

### ISSUE THREAD

**Issue by CrayolaEater** [godotengine/godot#68533]
**Operating system, Browser, Browser Version:**
Windows 10 64 bit
**Issue description:**
When selecting multiple nodes of the same type and hovering on a property in the inspector the tooltip no longer works.

**Screenshots (greatly appreciated if it’s a style issue)**
I select only one node:
![image](https://user-images.githubusercontent.com/38570835/201397629-17bd70b6-a020-4cc0-b61c-9236c9411583.png)
hovering works (the cursor its not visible but I'm pointing on the gravity scale property)
![image](https://user-images.githubusercontent.com/38570835/201397844-07610c28-f541-46af-9b26-f4419296be90.png)
when I select multiple nodes:
![image](https://user-images.githubusercontent.com/38570835/201397884-f329ee36-1ccf-4f53-ad31-4d98a4a2092d.png)
the tooltip is empty:
![image](https://user-images.githubusercontent.com/38570835/201397926-633305ed-094e-4587-943b-ef2812504029.png)

*Bugsquad edit (keywords for easier searching): MultiNodeEdit*

**Comment by Calinou** [comment]
@CrayolaEater Which Godot version are you using?

**Comment by CrayolaEater** [comment]
> @CrayolaEater Which Godot version are you using?

3.5.1
