### ISSUE TITLE
Can't use GetTransformedAabb() with Godot 4.0 beta 4

### ISSUE THREAD

**Issue by ZachAR3** [godotengine/godot#68539]
### Godot version

4.0.beta4.mono

### System information

Arch linux kernel 6.0.2-arch1-1 KDE DE.

### Issue description

When I try and use "GetTransformedAabb()" on a MeshInstance3D in the new beta 4.0 update I get the following error: "`/home/zach/Godot Projects/Procederul Dungeon Crawler Godot 4/Scripts/AStarPF.cs(55,25): 'MeshInstance3D' does not contain a definition for 'GetTransformedAabb' and no accessible extension method 'GetTransformedAabb' accepting a first argument of type 'MeshInstance3D' could be found (are you missing a using directive or an assembly reference?)"`. It seems that in beta 4 something changed with the MeshInstance3D class and broke AABB support.

### Steps to reproduce

In C# use "AABB aabb = YourMeshInstance3D.GetTransformedAabb();" the error only happens in godot 4 beta 4 and not any of the previous beta.

**Comment by ZachAR3** [comment]
Also appears to be an issue in GD Script using get_transformed_aabb()

**Comment by raulsntos** [comment]
The method was removed in https://github.com/godotengine/godot/pull/66940
