### ISSUE TITLE
Alterable playback speed for StreamPlayer

### ISSUE THREAD

**Issue by MutantOctopus** [godotengine/godot#6854]
Hi all-
I don't know if this is a big request on the programming level (although from what little I know of sound playback it _seems_ like it would just be a matter of increasing the playhead increment step), but I'd like to request the ability to put in a speed modifier to the StreamPlayer node. In many games, a subtle change of speed in the music can change the feel of the game. For example, someone making a Tetris game might want to speed up the music slightly when the block fall speed increases, or a platformer may want to increase speed when time starts running low, or a boss battle might want its music sped up when its health is down. Currently these effects can be emulated by actually creating different audio streams at different speeds, but this seems like a somewhat less than optimal solution (it takes time and adds more files to the project).

I wasn't sure if this was planned already, but I hadn't seen anything saying it was. So I figured I may as well put the request out there. Thanks!

**Comment by Noshyaar** [comment]
Closing as implemented. (pitch_scale in AudioStreamPlayer)

**Comment by daniyyelfelipe** [comment]
> Closing as implemented. (pitch_scale in AudioStreamPlayer) #15254

As a audio engineer and musician, I just wanna say that pitch scale and playback speed are two completely different things! One is about note key and key signatures, other is about tempo!  Sometimes people do it together in audio editors but they are two different sound properties.

**Comment by MutantOctopus** [comment]
Yeah, I kind of have to agree with @daniyyelfelipe -- When I originally made the feature request, the hope was for a property that would adjust the tempo without changing the pitch -- The same effect you'd find in the original Super Mario Bros. when the timer hit 100 seconds, for example. I think that when I originally made the request it was because I was programming a Tetris game and wanted the music to speed up when you were at risk of losing.

The pitch_scale thing _does_ allow for some degree of modification, and it's pretty functional for SFX, but I think everyone (except maybe for vaporwave or nightcore buffs, haha) pretty universally agrees that the basic implementation of fluctuating the pitch doesn't sound good for most music tracks.

I understand that a more complex solution, where both the "speed scale" and the pitch are separate properties, _would_ be a lot more complicated to program, but fundamentally speaking I'm not sure if the pitch_scale property solves the original feature request the way I'd intended the request.

**Comment by Calinou** [comment]
Feature proposals should be discussed on the [Godot proposals](https://github.com/godotengine/godot-proposals) repository, but note that changing playback speed requires an expensive algorithm compared to simply changing the pitch.
