### ISSUE TITLE
Problem with "tilemap" navigation

### ISSUE THREAD

**Issue by xiaoliang6669** [godotengine/godot#68547]
### Godot version

4.0-beta4

### System information

win10

### Issue description

```
func _physics_process(delta):

	if not nav_agent.is_navigation_finished():
		var next_location = nav_agent.get_next_location()
		var direction = global_position.direction_to(next_location)
		velocity = direction * speed
		#nav_agent.set_velocity(direction * speed)
		move_and_slide()
```

![9999](https://user-images.githubusercontent.com/112788136/201450395-b32909b4-40fb-4bde-b6e8-0b9a0fa5235e.png)

### Steps to reproduce

![screenshots](https://user-images.githubusercontent.com/112788136/201450247-51094599-25e0-4a56-8fdf-c4165e61797b.gif)

### Minimal reproduction project

![screenshots](https://user-images.githubusercontent.com/112788136/201450301-ad70bf83-68f4-49e0-b6f7-960e1385cf2b.gif)

**Comment by xiaoliang6669** [comment]
> Please provide a minimal reproduction project. Such navigation bugs can not be debugged from visuals.

The map is too big to upload, so people who understand it can see it. The navigation is set with the command "ps.set_navigation_polygon (0, polygon)"
![pppppp](https://user-images.githubusercontent.com/112788136/201457174-3cc8e044-4878-47e4-ba3e-597cc5559ae7.png)

**Comment by xiaoliang6669** [comment]
To add, map blocks are dynamically loaded and unloaded according to the camera range

**Comment by smix8** [comment]
Please look at the 437 Editor error / warning messages and report if you have a navigation edge merge error or a navpoly convex error among them.

**Comment by xiaoliang6669** [comment]
> Please look at the 437 Editor error / warning messages and report if you have a navigation edge merge error or a navpoly convex error among them.

Without the mistake you said
![QQ图片20221112140155](https://user-images.githubusercontent.com/112788136/201459927-836345a1-2526-43bd-aa7c-f90240f22532.png)

**Comment by xiaoliang6669** [comment]
> Please look at the 437 Editor error / warning messages and report if you have a navigation edge merge error or a navpoly convex error among them.

The reason has been found. The 20 * 20 navigation that has not been merged is normal, but the merged navigation is abnormal

![222](https://user-images.githubusercontent.com/112788136/201473868-d803d093-8a4c-47dd-80b3-fb39fce277dc.png)
![1111](https://user-images.githubusercontent.com/112788136/201473873-e19aed8b-c2e7-49da-b0a2-4a65ce9001b2.png)
