### ISSUE TITLE
Bugs found

### ISSUE THREAD

**Issue by xiaoliang6669** [godotengine/godot#68550]
### Godot version

4.0-beta4

### System information

win10

### Issue description

It has no effect after setting. I hope you can batch set this attribute for tiles in the editor
```
	ps.texture_offset=Vector2(-160,-120)
	var xys= tilemap.map_to_local(Vector2i(xx,yy))
	if le==0:
		print(xys)


```

### Steps to reproduce

![lll](https://user-images.githubusercontent.com/112788136/201456743-10ed1046-15ce-4859-9e5c-be5b0fba7c8f.png)

**Comment by MewPurPur** [comment]
Please read https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#reporting-bugs

Write a descriptive title. Minimal reproduction project is not 100% necessary, but we still need AT LEAST a self-contained way to reproduce the bug.

**Comment by xiaoliang6669** [comment]
> Please read https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#reporting-bugs
> 
> Write a descriptive title. Minimal reproduction project is not 100% necessary, but we still need AT LEAST a self-contained way to reproduce your bug.

Look at the code. It means that the command of setting offset has no effect after setting

**Comment by adamscott** [comment]
> Look at the code. It means that the command of setting offset has no effect after setting

Please follow @MewPurPur instructions, no matter how "evident" the issue seems to be. And the title definitely needs to be descriptive.

**Comment by groud** [comment]
The map_to_local returns the center of the cell on the map, this is completely unrelated to the rendering of the tile itself. Maybe the documentation could be improved but I don't think anyone else assumed this function would depend on the tile rendering.

Also, please seek help on the other [community platforms](https://godotengine.org/community) before posting here. This seems like a question that could have been solved by asking other users before reporting a bug.
