### ISSUE TITLE
Bug in the godot 12801

### ISSUE THREAD

**Issue by radlotus** [godotengine/godot#68555]
s

**Comment by adamscott** [comment]
Could not replicate in 3.5.1 on Linux.

**Comment by radlotus** [comment]
> Could not replicate in 3.5.1 on Linux.

Forgot to mention that it's happening on all Buttons.

**Comment by adamscott** [comment]
Could replicate on 3.5.1 on Linux, but not on 4.0 (master c17f17e).

Though, @radlotus, please add a minimal reproduction project with a base button set to `FOCUS_NONE`. It would help a lot to reproduce easily the issue.

https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#reporting-bugs

**Comment by timothyqiu** [comment]
This is related to `enabled_focus_mode`:

https://github.com/godotengine/godot/blob/28afd32d29df78283d0433680812c70edfb14c65/doc/classes/BaseButton.xml#L57-L59

> This property no longer has any effect when set.

This is not true, setting it will also sync the focus mode when the button is not disabled.

https://github.com/godotengine/godot/blob/28afd32d29df78283d0433680812c70edfb14c65/scene/gui/base_button.cpp#L324-L329

So the NONE focus mode is correctly copied, but set to ALL when copying `enabled_focus_mode`.

**Comment by Calinou** [comment]
Superseded by https://github.com/godotengine/godot/issues/72968.
