### ISSUE TITLE
test 129

### ISSUE THREAD

**Issue by radlotus** [godotengine/godot#68565]
minimal reproductible project, as it is way easier for devs to test your code than themselves create a new project and copy-paste the code

1.,.a

**Comment by adamscott** [comment]
Please create a MRP, a minimal reproductible project, as it is way easier for devs to test your code than themselves create a new project and copy-paste the code.

**Comment by radlotus** [comment]
> Please create a MRP, a minimal reproductible project, as it is way easier for devs to test your code than themselves create a new project and copy-paste the code.

This is all the code.

**Comment by TheDuriel** [comment]
Related: 61184, maybe: 31098

**Comment by adamscott** [comment]
@radlotus Thanks for the MRP!

**Comment by adamscott** [comment]
Could not reproduce on 3.5.1 (on Linux). Everything seems normal:

![Capture d’écran du 2022-11-12 12-09-16](https://user-images.githubusercontent.com/270928/201486054-5c5ea3fe-2b00-4d58-be1e-42adec276a60.png)

**Comment by radlotus** [comment]
Seems to be an issue tied to the Sway tiling window manager. It's fine if I turn on floating window mode. I'll check if issue is reproducible with a newer version of Sway.

**Comment by radlotus** [comment]
Can reproduce the issue on Windows 10 if the window isn't floating - it's fullscreened or tiled.
![Screenshot_1](https://user-images.githubusercontent.com/95962222/201492810-e112a035-eb6b-440b-b43c-5f675ebb4c72.png)

**Comment by nedafij100** [comment]
Can confirm this on Windows 11. Fullscreen or tiled causes 'Off "position" value of simulated InputEventMouse'.
This is a very obscure bug. 
I've encountered this while trying to program a TextEdit that you can pan on touch devices using regular swiping. I find it annoying having to use the scrollbars for panning.

**Comment by Calinou** [comment]
Superseded by https://github.com/godotengine/godot/issues/72969
