### ISSUE TITLE
Better path follow

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#6856]
This is a breaking change idea/suggestion/request:

PathFollow is a great tool but it requires to cut branches and reparenting poor children just to follow a path for awhile.

I was messing around in GDScript and nodes trying some approaches to see how could it be more flexible and got 2 ideas:
- One is that PathFollow can have a list of follower nodes from the scene and each member assigned an offset too.

![pathfollowers](https://cloud.githubusercontent.com/assets/10215987/19450001/1cf1090c-947e-11e6-90e7-c1f6917de8ea.gif)

That way, a single pathfollow can move N nodes without altering the scene tree, allowing add and remove easily from following a path, even push nodes in a trail.
- The other idea that was thinking is make the PathFollow a parasite.

![brainslug](https://cloud.githubusercontent.com/assets/10215987/19450172/c131be58-947e-11e6-804e-390a0c2a9f38.png)

If a pathfollow is added as child of a node and assigned to a path in the scene (like a ParticleAttractor to an Emitter), it will move the parent along the path, this way could be more flexible than the other but harder to make a trail of nodes.
- Another not so breaking option could be that depending on who is the parent of PathFollow it could behave as now ( _or as the first idea which is a breaking one_ ) or with the second mode (if parent is not a path).

ps: I'm still bad with plugins so don't know if can be just done with that while keeping a simple/transparent way to use (the second idea sounds possible).

**Comment by jtaart** [comment]
Cool ideas. If someone does change how PathFollow works, please keep it backwards compatible also. I would have to rewrite so much code in my game, and I'm sure I wouldn't be the only one who would have to do this.

**Comment by eon-s** [comment]
@jtaart could be a new type of pathfollow but don't know if worth a new node for this.
Everything may depend on how many people find the idea useful but also the current system I guess.

**Comment by bojidar-bg** [comment]
@eon-s I don't understand. Why did you close this issue?

**Comment by eon-s** [comment]
@bojidar-bg I was looking to my old requests to see if some are still valid and now I think the plugin system may be enough to cover this one without touching the main components :)
