### ISSUE TITLE
In-editor documentation resets scroll when resized in any way

### ISSUE THREAD

**Issue by Yagich** [godotengine/godot#68567]
### Godot version

4.0b4

### System information

Linux/Manjaro

### Issue description

While browsing in-editor docs, if you resize the container it's in in any way, e.g. by opening/closing the bottom docks or turning on/off distraction free mode, the scroll of the doc view will be reset to the top.

### Steps to reproduce

1. Open documentation for any class in the editor
2. Open/close any bottom dock

**Comment by adamscott** [comment]
I confirm the issue on Godot 4.0 beta 4 on Linux.

[Capture vidéo du 2022-11-12 11:18:42.webm](https://user-images.githubusercontent.com/270928/201483773-6791fe03-4f4d-4855-b368-5616431e878d.webm)

**Comment by Calinou** [comment]
I remember seeing this reported in another issue, but I can't find it right now.

cc @bruvzg

**Comment by adamscott** [comment]
The issue still exists on `master` as of now (c17f17e).
