### ISSUE TITLE
[C#] `_ExitTree` is not called at the main scene node after `QueueFree`

### ISSUE THREAD

**Issue by asolux** [godotengine/godot#68578]
### Godot version

4.0.beta4

### System information

Windows 10, 64bit

### Issue description

After changing a scene with the following code, the `_ExitTree` method is not called under C#. In GD-Script, on the other hand, it is. However, Dispose is called in C#.<br>
`_ExitTree` is called on all nodes contained in the scene except on the root node. (_I don't mean the tree node "/root"_)

C#:
```csharp
public static void SwitchScene(string newScenePath)
{
    var tree = (SceneTree)Engine.GetMainLoop();
    Viewport root = tree.Root;
    using Node CurrentScene = root.GetChild(root.GetChildCount() - 1);

    CurrentScene.QueueFree();

    Node newCurrentScene;
    using (var nextScene = GD.Load(newScenePath) as PackedScene)
    {
        newCurrentScene = nextScene?.Instantiate();
    }

    if (!IsInstanceValid(newCurrentScene))
    {
        GD.PushError("[SceneManager] Scene instance not valid.");
        return;
    }

    tree.Root.AddChild(newCurrentScene);
    tree.CurrentScene = newCurrentScene;
}
```
GD-Script:
```gdscript
func switch_scene(new_scene_path : String) -> void:
	var tree : SceneTree = Engine.get_main_loop()
	var root : Viewport = tree.root
	var current_scene : Node = root.get_child(root.get_child_count() - 1)

	current_scene.queue_free()

	var new_scene : Node = load(new_scene_path).instantiate()

	if !is_instance_valid(new_scene):
		push_error("[SceneManager] Scene instance not valid.")

	tree.root.add_child(new_scene)
	tree.current_scene = new_scene
```

_Edit:_ Works with the code normally using for changing the scene:
```csharp
var tree = (SceneTree)Engine.GetMainLoop();
tree.ChangeSceneToFile(newScenePath);
```
And works on 3.5: Here `_ExitTree` is called as expected.

### Steps to reproduce

After starting the test scene, click once on the "Switch scene to scene 2" button and then on the "Switch scene to scene 1" button. Then the following output is generated:

under C#:
```
[Scene1] : _EnterTree
[Scene1] : _Ready
[Scene2] : _EnterTree
[Scene2] : _Ready
[Scene1] : Dispose
[Scene1] : _EnterTree
[Scene1] : _Ready
[Scene2] : Dispose
```

under gd-script:
```
[Scene1] _enter_tree
[Scene1] _ready
[Scene2] _enter_tree
[Scene2] _ready
[Scene1] _exit_tree
[Scene1] _enter_tree
[Scene1] _ready
[Scene2] _exit_tree
```

### Minimal reproduction project

[Godot4B4_GD_Test_ExitTree.zip](https://github.com/godotengine/godot/files/9995890/Godot4B4_GD_Test_ExitTree.zip)
[Godot4B4_CS_Test_ExitTree.zip](https://github.com/godotengine/godot/files/9995891/Godot4B4_CS_Test_ExitTree.zip)

**Comment by zaevi** [comment]
```csharp
using Node CurrentScene = root.GetChild(root.GetChildCount() - 1);
```
You are using `using` statement so the csharp instance had been disposed before the node exited tree (QueueFree will defer deletion to the end of MessageQueue). 

You can remove `using` statement, or remove child manually:
```csharp
using Node CurrentScene = root.GetChild(root.GetChildCount() - 1);

root.RemoveChild(CurrentScene); // will call _ExitTree
CurrentScene.QueueFree();
```

**Comment by asolux** [comment]
Thank you for your explanation. I had a misconception here.
Of course it works great without the `using`.
Can be closed, sorry.
