### ISSUE TITLE
Changing parent node for FileDialog when it's visible will block any input in the editor

### ISSUE THREAD

**Issue by marzecdawid** [godotengine/godot#68575]
### Godot version

4.0.beta4

### System information

Windows 10 21H2, Vulkan, AMD Radeon RX 6750 XT (31.0.12029.1042)

### Issue description

Changing the type of the parent node for the FileDialog when the FileDialog is set to be visible in the Editor will block any input for the Editor (mouse, keyboard inputs as well as close button).

[Video showing the problem](https://www.youtube.com/watch?v=SXR0uSBrj7I)

This also happens for other nodes, for example AcceptDialog

It does not happen in Godot 3.5.1

### Steps to reproduce

1. Create a scene with Node2D
2. Add a FileDialog node as a child to Node2D
3. Change the visibility of the FileDialog node so it is visible in the editor:
![obraz](https://user-images.githubusercontent.com/23726629/201493434-75af9668-b1f0-4958-a88a-0b74c3bbc388.png)
4. Change the type of the Node2D to Control

**Comment by Sauermann** [comment]
Can confirm this on Linux.
If the changed node (`Node2D`) is _not_ the root-element, the bug doesn't happen.

**Comment by Rindbee** [comment]
https://github.com/godotengine/godot/blob/c17f17eb98188a7134c85bdbdf0123127c462046/scene/main/window.cpp#L515-L517
https://github.com/godotengine/godot/blob/c17f17eb98188a7134c85bdbdf0123127c462046/scene/main/window.cpp#L227-L233

When replacing the scene root node, here `get_tree()->get_edited_scene_root()` should be the new node, but actually still get the old one.
