### ISSUE TITLE
Unhelpful RETURN_VALUE_DISCARDED warning on tweening functions

### ISSUE THREAD

**Issue by m-r-hunt** [godotengine/godot#68585]
### Godot version

4.0 beta 4

### System information

Windows 10

### Issue description

When using tweening functions, you get a GDScript RETURN_VALUE_DISCARDED warning which is pretty useless. For example I have some code like this:

```
text_tween = create_tween()
text_tween.tween_property(dialog_text, ^":visible_characters", chars, chars/CHARS_PER_SECOND)
```

I get a warning on the second line here because `tween_property` returns a `PropertyTweener` object that I can use to customise the tween further. However in this case I don't need to do so, and this warning is very useless. There's no hidden bug or issue that could arise from ignoring this return value.

To silence it I have a few options, all of which are kind of clunky:
* Declare and assign an `_unused` variable
* Disable the warning locally with an annotation
* Disable the warning globally in settings

I think there should be some way to have a return value that is marked as "OK to ignore", and these methods should be marked as such so this problem doesn't arise.

### Steps to reproduce

Use tweening methods with warnings turned on.

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot-proposals/issues/613.

> I think there should be some way to have a return value that is marked as "OK to ignore", and these methods should be marked as such so this problem doesn't arise.

This is [feature proposal](https://github.com/godotengine/godot-proposals) territory :slightly_smiling_face:
