### ISSUE TITLE
Instancing MultiMesh with local to scene flag set throws Vulkan buffer argument error

### ISSUE THREAD

**Issue by SdgGames** [godotengine/godot#68592]
### Godot version

v4.0.beta4.official [e6751549c]

### System information

Windows Server 2022, Nvidia 4080 Ti, Vulkan

### Issue description

I made Minecraft using chunks made of of MultiMeshInstance3Ds. Each time a new chunk is instanced, there are errors thrown. It turns out, the "Local To Scene" flag in the MultiMesh resource was causing the error. This project was a convert from Godot 3.5.1. The issue was not present in that version, it appeared after upgrading.

Error output from reproduction project below.
```
E 0:00:00:0780   _ready: Buffer argument is not a valid buffer of any type.
  <C++ Error>    Method/function failed. Returning: ERR_INVALID_PARAMETER
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:6311 @ buffer_update()
  <Stack Trace>  Game.gd:7 @ _ready()
```

Despite printing an error, everything does seem to be working, I can use the multimesh that is created.

### Steps to reproduce

Create a `MultiMeshInstance3D `with a `MultiMesh` and `Mesh` resource. Set the `Local To Scene` flag as shown below:

![multi](https://user-images.githubusercontent.com/83036002/201504771-7735805b-4ae4-40cc-b5fb-02c5855463a6.PNG)

Save the scene. Load the scene resource from another scene, then call `multiMeshScene.instantiate()`

A rendering error will be thrown.

### Minimal reproduction project

[Multimesh.zip](https://github.com/godotengine/godot/files/9996456/Multimesh.zip)

**Comment by Lippanon** [comment]
Still present in v4.0.beta.custom_build [2a04b18d3]
```
E 0:00:01:0175   _ready: Buffer argument is not a valid buffer of any type.
  <C++ Error>    Method/function failed. Returning: ERR_INVALID_PARAMETER
  <C++ Source>   drivers\vulkan\rendering_device_vulkan.cpp:5856 @ RenderingDeviceVulkan::buffer_update()
  <Stack Trace>  Game.gd:7 @ _ready()
```

**Comment by Swarkin** [comment]
Still present in v4.0.rc5.official [6296b4600]
```
E 0:00:01:0109   Load.gd:36 @ _process(): Buffer argument is not a valid buffer of any type.
  <C++ Error>    Method/function failed. Returning: ERR_INVALID_PARAMETER
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:5857 @ buffer_update()
  <Stack Trace>  Load.gd:36 @ _process()
```

**Comment by rmvermeulen** [comment]
v4.0.stable.mono.official [92bee43ad]
I see the same issue, and it doesn't seem to matter if it's created from a saved tscn/tres file and/or duplicated afterwards. Even if I create the MultiMesh resource and node 'manually' from code this error pops up whenever it's added to the scene.

**Comment by ironstrasza** [comment]
In my case, I need to instance hundreds of local to scene MultiMeshes and this really slows down the engine (150+ instances, and I have to wait up to 15-20 seconds for the engine to throw an error for each of them). After that, everything works fine.

If you can raise an issue for them, it would be much appreciated @SamsPepper1

**Comment by fracteed** [comment]
I am just running into error this in 4.1.1. My multimeshes are working correctly but each one gets this error on creation.

I am setting the instance count with gdscript and in general there is a lot of weirdness with using a multimesh from an instanced scene. But they do render correctly so far. Every time I change something in the scene with the multimesh, I have to add in back to the master scene, otherwise the changes don't update.

**Comment by fracteed** [comment]
@SamsPepper1 I had also tried this tactic, but had even more issues with it. I have it on a value above 0 and then in the ready method try to change the instance count and get the error "Condition instance_count > 0 is true". It also doesn't increase the instance count correctly, so the buffer size is incorrect. 

I seem to only be able to dynamically change the instance count in ready if it is on zero to start with. Note, that 3.x didn't exhibit these issues.

**Comment by NatGazer** [comment]
**Still present in 4.2 rc2 official** 

![image](https://github.com/godotengine/godot/assets/67602607/e763a574-5cc1-41ee-be5a-b0d6ba5009a3)

And yes, the project silently crashes when it's in compatibility mode. This issue should be given more attention than what it's getting
