### ISSUE TITLE
Failed to unload assemblies when loading an Array of Resource

### ISSUE THREAD

**Issue by geowarin** [godotengine/godot#68590]
### Godot version

v4.0.beta.mono.custom_build [f814e15c7]

### System information

Arch Linux

### Issue description

My C# plugin is loading an array of Resources.
It prevents assemblies from reloading when I recompile.

```
Unloading assembly load context...
Assembly unloading is taking longer than expected...
Failed to unload assemblies. Possible causes: Strong GC handles, running threads, etc.
ERROR: .NET: Failed to unload assemblies.
   at: reload_project_assemblies (modules/mono/mono_gd/gd_mono.cpp:504)
ERROR: Condition "delegate_handle.value == nullptr" is true.
   at: call (modules/mono/managed_callable.cpp:92)
ERROR: Can't get method on CallableCustom "Delegate::Invoke".
   at: get_method (core/variant/callable.cpp:333)
ERROR: Error calling from signal 'timeout' to callable: 'Node::': Method not found..
   at: emit_signalp (core/object/object.cpp:1057)
```

The console is then flooded with infinite messages of the nullptr exception.

In the provided repro, I use a Texture2D to trigger the bug but any kind of Resource seems to have the same behavior (Gradient, etc).
The most specific repro I could find is: `CustomResource` -> `Array<CustomResource2>` -> `Texture2D`

### Steps to reproduce

```CSharp
#if TOOLS
using Godot;

[Tool]
public partial class myplugin : EditorPlugin
{
    public override void _EnterTree()
    {
        var libResource = ResourceLoader.Load<LibResource>("res://myResource.res");
    }
}
#endif
```

```CSharp
[Tool]
public partial class LibResource : Resource
{
    [Export] public Array<LibEntry> Entries { get; set; }
}
```

```CSharp
[Tool]
public partial class LibEntry : Resource
{
    [Export] public Texture2D Preview { get; set; }
}
```

### Minimal reproduction project

https://github.com/geowarin/ReloadBug

[ReloadBug-main.zip](https://github.com/godotengine/godot/files/9996345/ReloadBug-main.zip)

**Comment by SavoVuksan** [comment]
I have the same issue on a Windows machine with following version: v4.0.beta4.mono.official [e6751549c]
