### ISSUE TITLE
[4.0] GDScript no syntax error on trailing comma(",") in function parameters / arguments

### ISSUE THREAD

**Issue by ClarkThyLord** [godotengine/godot#68595]
### Godot version

Godot 4.0 beta 4

### System information

Windows 10

### Issue description

GDScript gives no syntax error on trailing comma(",") in function parameters. Below, is an example script with a trailing comma in the example function parameters, you'll note no syntax errors:
![image](https://user-images.githubusercontent.com/17155529/201507138-e06c7528-6a4c-467c-8208-c2a3279c46d1.png)

The above is not inline with Godot 3 behavior, as seen below:
![image](https://user-images.githubusercontent.com/17155529/201507135-2e5d325d-267a-4ffb-85a0-6b965bcc89d8.png)

### Steps to reproduce

1. Open example project
2. Open example.gd
3. No syntax errors

### Minimal reproduction project

[example.zip](https://github.com/godotengine/godot/files/9996547/example.zip)

**Comment by ClarkThyLord** [comment]
Just tested it, this also happens in function parameters:
![image](https://user-images.githubusercontent.com/17155529/201507485-d2c42980-c415-43dc-990a-9aace52496e1.png)

**Comment by tinmanjuggernaut** [comment]
Lists like in arrays and dictionaries allow a trailing comma. This is a convenient feature so you can have each entry on it's own line, and rearrange them without having to add/remove the last comma.
```
var arr := [
   1,
   2,
   3,
   4,
]
```

Perhaps it is intentional, as one could do the same thing with functions:
```
res = myfunc(
   arg1,
   arg2,
   arg3,
)
```

Or perhaps it is intentional and related to not variadic function proposals.
https://github.com/godotengine/godot-proposals/issues/1034
https://github.com/godotengine/godot/issues/16565

**Comment by akien-mga** [comment]
I think this is intentional indeed, it does allow a syntax like @tinmanjuggernaut showed:
```
res = myfunc(
   arg1,
   arg2,
   arg3,
)
```

It behaves similarly in Python 3:
```
>>> def somefun(
...   a1,
...   a2,
...   a3,
... ):
...     print(a1)
... 
>>> somefun("hi", None, None)
hi
>>> def somefun2(a1, a2, a3,): print(a1)
... 
>>> somefun2("hi", None, None)
hi
>>> somefun2("hi", None, None, )
hi
>>> somefun2("hi", None, None, ,)
  File "<stdin>", line 1
    somefun2("hi", None, None, ,)
                               ^
SyntaxError: invalid syntax
```

**Comment by Chaosus** [comment]
@akien-mga Okay, so I guess this issue should be closed?

**Comment by MewPurPur** [comment]
Agreed, no need to disallow it, I can imagine using it in a monolithic function with a lot of arguments with each one being on a new row.

**Comment by akien-mga** [comment]
@Calinou also confirms this was a "heavily requested feature": https://github.com/godotengine/godot/pull/68691#issuecomment-1315588139
