### ISSUE TITLE
Editor defaults to full monitor instead of full screen (DisplayServer regression)

### ISSUE THREAD

**Issue by SdgGames** [godotengine/godot#68591]
### Godot version

v4.0.beta4.official [e6751549c]

### System information

Windows Server 2022 (Win X kernel), Rtx 3080 Ti, 5120X1440 display

### Issue description

I'm using a ultrawide monitor. Windows still doesn't have great support for these, so I use an external program ([Display Fusion](https://www.displayfusion.com/)) to manage my desktops. Most programs, including Godot 3.5.X will default to Fullscreen within a single virtual monitor. Godot 4 defaults to maximized Fullscreen instead. Reloading the active project will also change the window size instead of sticking to the monitor I was working on. I did try overriding the default window layout under `Editor->Editor Layout->Save Layout`, but it appears that this only affects the position of elements within the editor window, not the position of the editor window itself.

Here's a screenshot of my desktop with no programs opened (virtual desktops are numbered)
![1](https://user-images.githubusercontent.com/83036002/201498558-73aacf00-f6ba-45d1-aa64-31c93e7714d0.png)

Here is what Godot 3 looks like after opening a project. This is how I would expect Godot 4 to behave:
![2](https://user-images.githubusercontent.com/83036002/201498562-538461ac-0afe-40b5-a5b1-9521908e6e17.png)

Here's Godot 4 opening a new project (notice how it crosses boundaries into all 3 virtual desktops):
![3](https://user-images.githubusercontent.com/83036002/201498685-4365ffe1-ebbd-41b3-b35e-4dae7653295f.png)

Programs like DisplayFusion piggyback on the Windows APIs, which is why I'm opening a bug here. I'm assuming that the full screen mode of the program was changed between Godot 3 and 4

### Steps to reproduce

This issue does unfortunately require a third-party program to be installed. DisplayFusion may not be the only one, and the issue might also be present on Windows 11 with the new monitor modes. I haven't tested these though, so here are the steps I used.

1. Install the DisplayFusion demo (it is free). Set up a monitor split, so your physical monitor is composed of two or more virtual monitors.
2. Open any project in Godot 3. It will fill your primary virtual monitor.
3. Open any project in Godot 4. It will ignore the monitor boundaries and fill the whole screen.

**Comment by Calinou** [comment]
This is likely because a proper, separate exclusive fullscreen was implemented in 4.0. It may be used by the editor even though it probably should be using borderless fullscreen instead.

**Comment by bruvzg** [comment]
> This is likely because a proper, separate exclusive fullscreen was implemented in 4.0. It may be used by the editor even though it probably should be using borderless fullscreen instead.

It's the opposite, 4.0 editor is using new non-exclusive mode to allow multiple windows. But it's likely not related, on both screenshots Godot is in maximized window mode, not in full-screen. This is definitely not happening with multiple physical monitors, so probably related to the way DisplayFusion works (I guess it's using window move API to manipulate window positions, not actually creating virtual devices on kernel level).

**Comment by akien-mga** [comment]
Is this still reproducible in 4.0 RC 3 or later?

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
