### ISSUE TITLE
Invisible text in the editor with old AMD GPU on Windows 7

### ISSUE THREAD

**Issue by Shockblast** [godotengine/godot#686]
(Sorry my english)
Hi, I come to report a bug godot in "Windows 7", the problem is that when you start godot text is not displayed or is "invisible", and and tried several ways to try to solve the problem (basic solutions) to update "Windows", compile godot (the latest github, gives the same problem), update directx,drivers, compatibility mode and some other (problem not solved).

(original text)
Hola, vengo a reportar un bug con godot in"Windows 7", el problema consiste que al iniciar godot el texto no aparece en pantalla o es "invisible", ya e intentado varias formas de intentar solucionar el problema (soluciones básicas) como actualizar "Windows", compilar godot (la ultima versión de github, da el mismo problema), actualizar directx, drivers, modo de compatibilidad y algunas otras (el problema no se soluciona).

PC specifications: (not think it necessary, but...)
OS: Windows 7 Professional X32
Processor: AMD Phenom II X3 2.6 GHZ
MB: ECS A790GXM-AD3
Ram: 2 GB
Graphics: ATI Radeon HD 3300 (integrated)
HDD: 150 GB WD

Screenshots:
![ss1](https://cloud.githubusercontent.com/assets/5357217/4219191/e3079be0-38f7-11e4-9eb9-7bca4bc16622.png)
![ss2](https://cloud.githubusercontent.com/assets/5357217/4219192/e30b4aa6-38f7-11e4-8032-13099daac50a.png)
![ss3](https://cloud.githubusercontent.com/assets/5357217/4219193/e30f358a-38f7-11e4-8117-bc8e60bfbb84.png)

**Comment by GodotofHanoi** [comment]
I've got the same Error. 
With both Godot Engine Versions: December 15, 2014 (1.0stable): 
godot_win32.exe and
godot_win64.exe 

Error Text:
<pre><code>
ERROR: _update_framebuffer:  Condition ' status != 0x8CD5 ' is true. Continuing.
.:
At:  drivers/gles2/rasterizer_gles2.cpp:8963
ERROR: _update_framebuffer:  Condition ' status != 0x8CD5 ' is true. Continuing.
.:
At:  drivers/gles2/rasterizer_gles2.cpp:8963
ERROR: _update_framebuffer:  Condition ' status != 0x8CD5 ' is true. Continuing.
.:
At:  drivers/gles2/rasterizer_gles2.cpp:8963
ERROR: _update_framebuffer:  Condition ' status != 0x8CD5 ' is true. Continuing.
.:
At:  drivers/gles2/rasterizer_gles2.cpp:8963
ERROR: _update_framebuffer:  Condition ' status != 0x8CD5 ' is true. Continuing.
.:
At:  drivers/gles2/rasterizer_gles2.cpp:8963
WARNING: viewport_data_create:  Can't create framebuffer for vd
At:  drivers/gles2/rasterizer_gles2.cpp:3920
</code></pre>
System:
AMD Turion 64 Mobile Tech.
ATI Readon Xpress 1100

**Comment by okamstudio** [comment]
I have a feeling this has to do with GPUs with Directx9b, which do not
support something specific

On Wed, Jan 21, 2015 at 9:55 AM, GodotofHanoi <notifications@github.com>
wrote:

> I've got the same Error.
> With both Godot Engine Versions: December 15, 2014 (1.0stable):
> godot_win32.exe and
> godot_win64.exe
>
> Error Text:
>
>
> ERROR: _update_framebuffer:  Condition ' status != 0x8CD5 ' is true. Continuing.
> .:
> At:  drivers/gles2/rasterizer_gles2.cpp:8963
> ERROR: _update_framebuffer:  Condition ' status != 0x8CD5 ' is true. Continuing.
> .:
> At:  drivers/gles2/rasterizer_gles2.cpp:8963
> ERROR: _update_framebuffer:  Condition ' status != 0x8CD5 ' is true. Continuing.
> .:
> At:  drivers/gles2/rasterizer_gles2.cpp:8963
> ERROR: _update_framebuffer:  Condition ' status != 0x8CD5 ' is true. Continuing.
> .:
> At:  drivers/gles2/rasterizer_gles2.cpp:8963
> ERROR: _update_framebuffer:  Condition ' status != 0x8CD5 ' is true. Continuing.
> .:
> At:  drivers/gles2/rasterizer_gles2.cpp:8963
> WARNING: viewport_data_create:  Can't create framebuffer for vd
> At:  drivers/gles2/rasterizer_gles2.cpp:3920
>
> System:
> AMD Turion 64 Mobile Tech.
> ATI Readon Xpress 1100
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/686#issuecomment-70831764>.
>



-- 

*OkamStudio*

**Comment by GodotofHanoi** [comment]
> I have a feeling this has to do with GPUs with Directx9b, which do not support something specific

My Directx is 11.
1280x800
driver 02.11.2010

**Comment by the-mech** [comment]
since godot uses framebuffer, i think you need at least opengl 3.0 to run it..

**Comment by okamstudio** [comment]
2.1 generally works as pretty much all 2.1 hardware supports FBOs, I think
the problem with the fonts is related to the texture format, but i'm not
sure

On Wed, Jan 21, 2015 at 10:40 AM, Roman Nekrassow <notifications@github.com>
wrote:

> since godot uses framebuffer, i think you need at least opengl 3.0 to run
> it..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/686#issuecomment-70837896>.
>



-- 

*OkamStudio*

**Comment by GodotofHanoi** [comment]
Thanks for your support. I want to get Godot run on my Laptop.
Is there a work around? 

Engine is not running with -vd GLES1 either.

how did you hide the text with "... Button"?

>C:\Godot>godot_win32-1.0stable.exe -vd GLES1
EXEC PATHP: C:\Godot\godot_win32-1.0stable.exe
EXEC PATHP: C:\Godot\godot_win32-1.0stable.exe
opening pack C:\Godot\godot_win32-1.0stable.exe, -1, -1
opening pack C:/Godot/data.pck, -1, -1
ERROR: _update_framebuffer:  Condition ' status != 0x8CD5 ' is true. Continuing.
.:
At:  drivers/gles2/rasterizer_gles2.cpp:8963
ERROR: _update_framebuffer:  Condition ' status != 0x8CD5 ' is true. Continuing.
.:
At:  drivers/gles2/rasterizer_gles2.cpp:8963
ERROR: _update_framebuffer:  Condition ' status != 0x8CD5 ' is true. Continuing.
.:
At:  drivers/gles2/rasterizer_gles2.cpp:8963
ERROR: _update_framebuffer:  Condition ' status != 0x8CD5 ' is true. Continuing.
.:
At:  drivers/gles2/rasterizer_gles2.cpp:8963
ERROR: _update_framebuffer:  Condition ' status != 0x8CD5 ' is true. Continuing.
.:
At:  drivers/gles2/rasterizer_gles2.cpp:8963
WARNING: viewport_data_create:  Can't create framebuffer for vd
At:  drivers/gles2/rasterizer_gles2.cpp:3920

**Comment by reduz** [comment]
gles 1 is gone forever, but there might be a way. Can you compile it
yourself? this way I can help you try different approaches until it works

**Comment by GodotofHanoi** [comment]
How long would this take?

**Comment by bushig** [comment]
Same problem, but godot of the same version with the same hardware worked in ubuntu 14.10 and windows 8.1. Problem is in windows 7. I have not an english version of windows (and probably everyone else in this thread), but saving godot in root directory doesn't help.

**Comment by Shockblast** [comment]
so... problem "solved"?

**Comment by gnat** [comment]
This issue happens because the drivers available for these older GPUs on Windows do not support GLES 2. I can replicate this issue on my laptop sporting an ATI X1300... the final driver update was from 2010.

One solution would be to use a backend better supported by these old drivers (straight OpenGL 2, D3D 9, GLES 1, etc.). This is how Unity 3D solves the issue.

**Comment by eVoLuTiVeMEDIA** [comment]
Wish I could test this promising game engine, seems really great
but I'm having the same problem (hidden text and 0x8CD5 status)
Tested in Windows 7 + Core 2 Duo with an ATI Radeon 1550

**Comment by rojohound** [comment]
I've got godot compiling on my machine so I can do some digging.

It seems that some glTexImage2D() calls were causing INVALID_VALUE errors.  My guess was that _GL_RG_EXT isn't actually supported by my card as all the other parameters seemed valid.

I made use_fp16_fb to be false in RasterizerGLES2's constructor so that GL_RGBA is used instead.  The good news is that resolved the logged errors and gDebugger doesn't show any opengl errors.  The bad news is the text is still invisible.

**Comment by rojohound** [comment]
Eureka!
It's a known mipmapping issue with ati drivers prior to 2011, where the mipmap isn't generated.
https://www.opengl.org/wiki/Common_Mistakes#Automatic_mipmap_generation.
This is useful for legacy integrated ati cards where the newest drivers you can get are from 2010.

The fix is to proceed all calls to
glGenerateMipmap(GL_TEXTURE_2D)
with
glEnable(GL_TEXTURE_2D)

And the text is then visible in godot.

**Comment by WinnerEX** [comment]
So this is a user-end only fix with adding calls for compiling? This topic was addressed 11 months ago and godot 2.0/2.0.1 still fail to render text.

**Comment by Shockblast** [comment]
(sorry my english)
sorry, but I can not test with the current version, now I have another hardware.

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by akien-mga** [comment]
Might get fixed when the GLES2 renderer will be reworked in 3.0.

**Comment by akien-mga** [comment]
Godot's rendering changed a lot since this issue was initially reported. Godot 3.0 now requires OpenGL 3.3 (so such GPU would likely not be able to run it), and Godot 3.1 will add back support for OpenGL 2.1, but fully rewritten, so there would likely be new bugs and maybe not the old ones.

As such, closing this issue. If you still experience something similar in a recent Godot version, feel free to comment here or open a new issue.
