### ISSUE TITLE
Signal error when instancing a node through a plugin

### ISSUE THREAD

**Issue by psichma** [godotengine/godot#68600]
### Godot version

v3.5.1.stable.official [6fed1ffa3]

### System information

Windows 10

### Issue description

When playing around with creating a plugin I noticed an issue with signaling on instanced nodes loaded from a scene file.
The signals I used are 'mouse_entered' and 'mouse_exited'

The Editor complains about "already connected" signals:
![image](https://user-images.githubusercontent.com/17086753/201509755-c75a0e63-d16e-4131-97e4-24b211134a45.png)

When dragging the scene node into the tree, no errors occur.
When instancing the node via code inside the scene, no errors occur.
When I use the same code inside a plugin, the error finally occurs and game still runs and signals work

Important to note:
When removing the signals on the node created with the plugin, the node still has the signals, but no errors occur.

Code in the scene itself:
```
extends Node2D

var hover_node_tscn = preload("res://HoverNode.tscn")

func _ready():
	var inst = hover_node_tscn.instance()
	inst.name = "via_scene_code"
	inst.position.x += 50
	add_child(inst)
	pass
```
Code in the plugin
```
tool
extends VBoxContainer

var hover_node_tscn = preload("res://HoverNode.tscn")

func _on_TestButton_pressed():
	var inst = hover_node_tscn.instance()
	inst.name = "via_addon"
	inst.position.x += 100
	
	var st = get_tree().get_edited_scene_root()
	st.add_child(inst)
	inst.owner = st
```

On the attached minimal reproduction code there should be a dock on the left with a button to add the node

### Steps to reproduce

- Create Area2D node with collider
- Attach a script and connect mouse signals
- Save node as scene
- Instance node via a plugin

### Minimal reproduction project

[SignalBug.zip](https://github.com/godotengine/godot/files/9996645/SignalBug.zip)

**Comment by tinmanjuggernaut** [comment]
Try using code to connect to the signal. I never use the editor for signal connections. And if it still is a problem after that, check with `is_connected()` before you connect.

On your report, I'm not clear at all how to reproduce the error. I loaded the scene, clicked the button under signal test, hovered over and dragged the added nodes in the viewport. It seemed to work and no errors.

**Comment by clayjohn** [comment]
@psichma Do you have an update after tinmanjuggernaut's comments? Or can this be closed?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.
