### ISSUE TITLE
GDNative C++ library.so: "Attempt to connect nonexistent signal"

### ISSUE THREAD

**Issue by br3eze** [godotengine/godot#68601]
### Godot version

v3.5.1.stable.arch_linux

### System information

Linux Arch (amd64)

### Issue description
```
E 0:00:00.645   connect: In Object of type 'Control': Attempt to connect nonexistent signal 'Game.co' to method 'Control._on_connect'.
  <C++ Error>   Condition "!signal_is_valid" is true. Returned: ERR_INVALID_PARAMETER
  <C++ Source>  core/object.cpp:1468 @ connect()
  <Stack Trace> Login.gd:84 @ _ready()
                Root.gd:5 @ start()
```

### Steps to reproduce

DynLib (*.so) works well, I can uncomment the rest of a code and it connects (by ASIO) to a server and talks to it. But signal doesn't work in any variant.

**game.hpp** // New empty class
```
class game: public godot::Node
{
    GODOT_CLASS(game, godot::Node)
    ...
    void game::_register_methods ()
    { 
        godot::register_signal<game>("ok");
    }

    start()
    {
        emit_signal("ok");
    }
};
```
**menu.gd**
```
extends Control
....
func _on_lib():  // never runs
    print("ok")

func _start():
    connect("Game.ok",  self, "_on_lib") // lib.gdns exports it as "Game"
    Game.start()

func _ready():
    call_deferred("_start")
```
This prints that is the signal is there:
```
"{args:[], default_args:[], flags:1, id:0, name:ok, return:{class_name:, hint:0, hint_string:, name:, type:0, usage:7}}"
```
But this presents in Debugger too:
```
"connect: In Object of type 'Control': Attempt to connect nonexistent signal 'Game.ok' to method 'Control._on_lib'."
```

**Comment by Akylzhan** [comment]
`connect("Game."` why the signal has `.` in it's name? I would not declare signals with `.` in their names

**Comment by br3eze** [comment]
![image](https://user-images.githubusercontent.com/5236855/201537712-8adf2bc8-fe29-45be-887a-7fee4d460464.png)
This worked well, but why should it not in C++?

**Comment by Zireael07** [comment]
Does it work with some other naming scheme, eg. with a "-" or a "@" in the name?

**Comment by br3eze** [comment]
If You are talking about the screenshot, can't check it anymore.
What is the proper way to name it in C++: ```connect("Game.ok",  self, "_on_lib")``` ?

**Comment by akien-mga** [comment]
`Game.connect("ok", self, "_on_lib")`

**Comment by br3eze** [comment]
> `Game.connect("ok", self, "_on_lib")`

At last! Thank You!
