### ISSUE TITLE
Incorrect positioning of fields on Mac Retina

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#6860]
**Operating system or device - Godot version:**
Mac OS X 11.6, Retina Mac Book Pro running at highest scale setting (though other scale settings have same behaviour)
Godot 2.1 and 2.1.1 RC

**Issue description** (what happened, and what was expected):
Object seem wrongly positioned or too large, for instance the preview button for the selected camera:
![Preview camera](http://i95.photobucket.com/albums/l136/Mux213/th_Preview%20hidden.png)
http://s95.photobucket.com/user/Mux213/media/Preview%20hidden.png.html

Popup for entering coordinates/rotations has text overlapping:
![Popup](http://i95.photobucket.com/albums/l136/Mux213/th_Coordinate%20popups.png)
http://s95.photobucket.com/user/Mux213/media/Coordinate%20popups.png.html

Saw some more in other places but most likely all the same cause. It must be getting sizing info wrong from somewhere. 

**Steps to reproduce:**
Just open the interface :)

**Link to minimal example project** (optional but very welcome):

**Comment by bojidar-bg** [comment]
Still valid?

**Comment by BastiaanOlij** [comment]
Just did a fresh build from Master, yup still valid

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
I'm pretty sure this has been fixed a long time ago.
