### ISSUE TITLE
WorldEnvironment Ambient light renderers incorrectly on Mobile renderer

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot#68618]
### Godot version

4.0.beta4

### System information

macOS 12.6.1

### Issue description

On my macOS 12.6.1 AMD Radeon Radeon Pro 560 system using the mobile renderer scenes with a WorldEnvironment that uses a Sky for Ambient Light (directly or indirectly via Background) get a strange banded appearance, as if the sky is being projected weirdly as you can see below. 

![Screen Shot 2022-11-13 at 17 13 46](https://user-images.githubusercontent.com/17763524/201532507-feef616f-3dcd-475e-8c65-63fa55c61016.jpg)

At first I though these were incorrect environment reflections, but it turned out that even the default material with full roughness got them, using the default preview environment in the 3d view. Investigating a little more I found out that the problem seems to be the Ambient Light source in the WorldEnvironment. If you change this to disabled or a static color instead of the default Background or Sky the strange lines go away.

### Steps to reproduce

- Make a new project
- Set it to use the mobile renderer
- Add a MeshInstance3D, set the mesh to be a SphereMesh
- Observe strange lines

### Minimal reproduction project

(I just get an error "Something went really wrong, we can't process that file" trying to upload my 5kb minimal reproduction project. But it should be relatively easy to reproduce as described above. I'm guessing it will affect all mobile renderer projects on macOS or AMD cards)

**Comment by clayjohn** [comment]
This bug has already been reported and fixed. The fix is available if you compile from master. It will also be available in beta 5

https://github.com/godotengine/godot/pull/68511
