### ISSUE TITLE
ZIPReader with HTTPRequest doesn't work consistently in seemingly equivalent code

### ISSUE THREAD

**Issue by oganm** [godotengine/godot#68614]
### Godot version

4.0 beta 4

### System information

Windows 10

### Issue description

I am working on some code to download a zip file using HTTPRequest then reading it with the new ZIPReader. In the example issue attached, I have 3 scripts attached to 3 buttons that, as far as I understand should work in an equivalent fashion. However only one of them appears to successfully read the zip file.

Button 1, the one that works just tucks everything into the function connected to request_completed signal, here we succesfully reach the "I'm good" message

```gdscript
extends Button

var download_path = 'down/zip.zip'
var download_link = 'https://github.com/oganm/ZIPReader_issue/archive/refs/heads/main.zip'

func _ready():
    pressed.connect(self._on_pressed)

func _on_pressed():
    DirAccess.remove_absolute(download_path)
    var http_request = HTTPRequest.new()
    add_child(http_request)
    http_request.request_completed.connect(self._download_completed)
    http_request.request(download_link)

func _download_completed(result, response_code, headers, body):
    var install_directory = download_path.get_base_dir()
    DirAccess.make_dir_recursive_absolute(install_directory)

    var f:FileAccess = FileAccess.open(download_path,FileAccess.WRITE)
    f.store_buffer(body)
    f = null

    var reader = ZIPReader.new()
    var err = reader.open(download_path)
    print(err)
    if err != OK:
        push_error('An error occured reading the zip file')
        return err
    else:
        print("I'm good")
```
The only difference of Button 2 is that the code for reading the zip is moved to a different function but this fails.
```gdscript
extends Button

var download_path = 'down/zip.zip'
var download_link = 'https://github.com/oganm/ZIPReader_issue/archive/refs/heads/main.zip'

func _ready():
    pressed.connect(self._on_pressed)

func _on_pressed():
    DirAccess.remove_absolute(download_path)

    var http_request = HTTPRequest.new()
    add_child(http_request)
    http_request.request_completed.connect(self._download_completed)
    http_request.request(download_link)

func _download_completed(result, response_code, headers, body):
    var install_directory = download_path.get_base_dir()
    DirAccess.make_dir_recursive_absolute(install_directory)

    var f:FileAccess = FileAccess.open(download_path,FileAccess.WRITE)
    f.store_buffer(body)
    f = null
    unzip()

func unzip():
    var reader = ZIPReader.new()
    var err = reader.open(download_path)
    print(err)
    if err != OK:
        push_error('An error occured reading the zip file')
        return err
    else:
        print("I'm good")
```
Button 3 moves the ZIPReader part back to _on_pressed by using await and a signal, emitted after the file is written
```gdscript
extends Button

var download_path = 'down/zip.zip'
var download_link = 'https://github.com/oganm/ZIPReader_issue/archive/refs/heads/main.zip'
signal zip_written

func _ready():
    pressed.connect(self._on_pressed)

func _on_pressed():
    DirAccess.remove_absolute(download_path)

    var http_request = HTTPRequest.new()
    add_child(http_request)
    http_request.request_completed.connect(self._download_completed)
    http_request.request(download_link)
    await self.zip_written

    var reader = ZIPReader.new()
    var err = reader.open(download_path)
    print(err)
    if err != OK:
        push_error('An error occured reading the zip file')
        return err
    else:
        print("I'm good")

func _download_completed(result, response_code, headers, body):
    var install_directory = download_path.get_base_dir()
    DirAccess.make_dir_recursive_absolute(install_directory)

    var f:FileAccess = FileAccess.open(download_path,FileAccess.WRITE)
    f.store_buffer(body)
    f = null
    emit_signal('zip_written')
```

### Steps to reproduce

Running the project attached, only pressing button 1 works to successfully read the downloaded zip file.

### Minimal reproduction project

https://github.com/oganm/ZIPReader_issue/archive/refs/heads/main.zip
https://github.com/oganm/ZIPReader_issue

**Comment by Calinou** [comment]
cc @MisterMX

**Comment by TechnicalSoup** [comment]
I get the same result as you when running your example project on Windows 11. However if I modify the button 3 code to just read the file using ZIPReader (i.e. remove the HTTPRequest code), and I have already downloaded the file using button 1 or button 2 then the ZIPReader code in button 3 is successful and I get an "I'm good" output.

Perhaps it has something to do with the FileAccess handle going out of scope between setting it to null and the ZIPReader attempting to open it? The FileAccess docs indicate that setting the handle to null or having the handle go out of scope should close the file.

**Comment by oganm** [comment]
`f.flush()` does work as a fix as a quick way to patch the issue. however this fix doesn't seem to work if the project is loaded as an addon.
