### ISSUE TITLE
PS4 controller vibration not working.

### ISSUE THREAD

**Issue by hakuhan** [godotengine/godot#68638]
### Godot version

4.0 beta4

### System information

lastest windows11

### Issue description

I'm using`Input.start_joy_vibration(0, 1, 1, 1)` and it is not working. I tested PS4 controller and third-part xbox controller. And also I tried change controller ID.

### Steps to reproduce

Just run editor and do `Input.start_joy_vibration(0, 1, 1, 1)`

**Comment by Chaosus** [comment]
Pretty much the same as https://github.com/godotengine/godot/issues/14634 (only more examples (including PS4) are available in that topic).
