### ISSUE TITLE
Vulkan Mobile: Screen texture is slightly dark when writing onto the albedo of a mesh

### ISSUE THREAD

**Issue by bepthomp** [godotengine/godot#68636]
### Godot version

4.alpha16 -> current

### System information

Windows 10, Vulkan Mobile, Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz 2.21 GHz

### Issue description

When doing a screen texture lookup on a shader then writing it onto the albedo of a plane mesh, it does not reflect the screen texture, it is darker.
![image](https://user-images.githubusercontent.com/36116447/201570849-de268e79-d658-4395-a977-e0019b9e1b56.png)

This is what it should look like (this snapshot was taken on alpha15, Vulkan Mobile):
![image](https://user-images.githubusercontent.com/36116447/201571050-6253ecc0-0583-4fbc-b486-ed395fa969d4.png)

### Steps to reproduce

- Create a Quad Mesh MeshInstance3D
- Assign a shader material to it
- Use the following shader code, the mesh will show up as darker in the newer versions:
```
shader_type spatial;
render_mode unshaded;

void fragment() {
	vec4 tex = texture(SCREEN_TEXTURE,SCREEN_UV);
	ALBEDO = tex.rgb;
}
```

### Minimal reproduction project

[Screen Texture MRP.zip](https://github.com/godotengine/godot/files/9999300/Screen.Texture.MRP.zip)

**Comment by Calinou** [comment]
If you can [compile the engine from source](https://docs.godotengine.org/en/stable/development/compiling/index.html), you could look into [bisecting the regression](https://docs.godotengine.org/en/stable/community/contributing/bisecting_regressions.html) to greatly speed up troubleshooting.

**Comment by bepthomp** [comment]
I haven't done this before but I'll try to learn how and look for where the regression was.

**Comment by bruce965** [comment]
As a workaround in the meantime: multiplying the final `ALBEDO` by `4` produces the correct result.

```
shader_type spatial;
render_mode unshaded;

void fragment() {
	vec4 tex = texture(SCREEN_TEXTURE,SCREEN_UV);
	ALBEDO = tex.rgb;
	
	ALBEDO *= 4.;
}
```

**Comment by bruce965** [comment]
I ran a bisect, the first bad commit is 4a1c7de57c53af429a3523bdcbef65c8c791f09f.

**Comment by Calinou** [comment]
cc @clayjohn

**Comment by akien-mga** [comment]
> I ran a bisect, the first bad commit is [4a1c7de](https://github.com/godotengine/godot/commit/4a1c7de57c53af429a3523bdcbef65c8c791f09f).

That's unlikely to be the culprit. This commit just changed the project setting used to select the rendering method so for earlier commits you were likely testing the Vulkan Forward+ renderer.

**Comment by bruce965** [comment]
Ah, makes sense, sorry... I'll look into it again as soon as I have time.

**Comment by bruce965** [comment]
Okay, the first commit with this issue seems to be 385ee5c70b110fc4e6a47c847428bfe3da89e18e.
cc @clayjohn

**Comment by clayjohn** [comment]
@bruce965 Yes, that line should be changed back to a multiplication. I think I had inverted the logic at some point while writing https://github.com/godotengine/godot/commit/385ee5c70b110fc4e6a47c847428bfe3da89e18e and then forgot to undo it. 

Taking a look at other places in the engine to verify I can confirm that we should be multiplying by ``sc_luminance_multiplier`` when reading from a texture and dividing by ``sc_luminance_multiplier`` just before writing to a texture. 

@bruce965 Would you like to make a PR with the fix?

**Comment by bruce965** [comment]
Sure thing, I was testing this change against master before opening a PR.
