### ISSUE TITLE
Godot editor start up loading time is much slower / faster depending on how singletons are used

### ISSUE THREAD

**Issue by takaturre** [godotengine/godot#68634]
### Godot version

4.0.beta4

### System information

Win 11

### Issue description (tl;dr)

The issue is that starting up Godot editor might take 10s or almost a minute depending on a seemingly unrelated tiny detail in the project (related to singletons). Below is a conceptualization of the situation and the two key findings:
  1. _Using a singleton is much faster (when editor starts up) than using preloads from multiple scripts_.
    - To be clear, let's say the moment starting up is finished is when the FileSystem tab refreshes to show all your resources.
  2. Introducing a _cyclical reference from one singleton to another_ made Godot start up time drop from near a minute to a blazing 10 seconds (all functioning correctly). But it'll cause a crash on the game side.

#### The setup
We have two singletons: 1. `Editor`, and 2. `Tools`. They are editor side only (will be removed from final game).

#### The singleton no 1: Editor
In this setup, the Editor has some features as an instanced node, but mostly it provides a global static interface:
- It has many "tool modules" that are written as static, eg. `Editor.Services`, `Editor.Nodes`, `Editor.Folders`, ...
  * They are (or were) loaded on the `Editor` singleton as: `const Services := preload("HeavyStuff/Services.gd")` etc.
  * These modules build on each other (in clean inheritance). They could use preloads to earlier loaded modules (as if were "importing modules"), but it makes Godot editor start up slower.
  * So instead, using finding 1 above we can refactor them to use the `Editor` keyword to access the other modules (instead of multiple preloads), so that startup is much faster.
- However, using the `Editor` keyword within scripts that are part of the same `Editor` singleton is cyclical:
  * To do it we must change our `const preload`s to `var load`s, so that we can get away with it on the editor side.
  * However, pressing `F6` causes a crash on game side (maybe fixed by #67714). Luckily we can solve it by using conditional loading (as it's not a preload anymore), so now our lines look like this:
    * `var Services = load("res://HeavyStuff/Services.gd") if Engine.is_editor_hint() else null`
- It works, but unfortunately we of course lose all the typing for these modules (with `var load`s).
  * But wait a minute, we could make another script (say, "Tools") that has everything loaded as constants and just preload it. So that even though our tool modules can't enjoy typing (without extra inner preloads), the rest of our script world can. It should be fine as long as none of the modules preloads Tools (which they don't).
  * This does work, but now Godot starts up slower. (In the ref. project, it should be a bit over 10 secs, but now it's 20-25s.)

#### The singleton no 2: Tools
- But wait, we can use the same principle again: loading a singleton is faster than preloads from multiples scripts.
- So let's consume another singleton, say, `Tools` and refer to that instead and Godot should open up very quickly:
  * No, now it actually takes almost a minute (45-50 seconds) before the FileSystem tab is refreshed.
- However, if we now add the `Tools` keyword to our `Editor` singleton (eg. to load the modules from it), the start up time drops down to 10 seconds..!
  * However, the enthusiasm drops when pressing `F6` and seeing a parser error saying it cannot load one of the tool modules (= most often the first one using an `Editor` keyword).
  * Well, of course, it's the same thing again: a cyclical ref causes a parser error on the game side. (This can actually be worked around, see below - but it's beside the point.)

#### Hacky solution (extra info):
- In that reference project, I actually ended up changing the `Editor` singleton node and path dynamically:
  * First, when Godot editor starts up, it swaps the `Editor` singleton to another that is "game safe".
     * The editor starts up with `EditorStartUp.gd` which extends `Editor.gd` with simply having the `Tools` keyword in it.
  * Secondly,  when Godot editor closes (detected by notification), the `ProjectSettings` are re-written (using `File`) to correct the path back. So that opening up the project again is fast again.
- This actually works: Godot now opens up super fast, while pressing F6 still works.
  * However, it's quite a surprise. And given the fact that 10 sec load up _can_ function 100% correctly, optimally Godot would take care of the situation internally and/or provide clear documentation as to how not mess it up. (Maybe this issue report can be considered to contribute to that documentation.)
  * As a side note. A general feature to say whether a script is &1: game side, &2: tool side could also solve this indirectly (and be useful otherwise). Or even better if the autoload system allowed to define separate tool and game side scripts to the same singleton..! (Then could preload stuff with typing on editor side, while having near empty game side script with no errors about a missing singleton.)

### Minimal reproduction project

I'll try to make a min. project, but it'll mostly be a lot of jargon code to represent the "tool modules" and other scripts that use them, so that the loading will start to take longer. (I considered these findings to be of more importance.)

**Comment by adamscott** [comment]
If all goes well, https://github.com/godotengine/godot/pull/67714 is planned to be merged as soon as possible as the underlying issue is well known from the Godot maintainers.

**Comment by takaturre** [comment]
Just an update on the ref. project loading times after Godot v4.0.beta6:
- In the scenario where loading time was 45-50s, it's now 30-35s.
- With the EditorStartUp's cyclical hack, the loading time drops to about 10 seconds like did before (maybe 1-2 seconds faster than in beta4 or beta5).

**Comment by adamscott** [comment]
Can you test with a build of master? #69079 has been merged since beta 6 and that fixes issues with singletons. Build artifacts are available, you don't have to build it from scratch.

**Comment by takaturre** [comment]
Sorry, I haven't once compiled Godot from source - trying to stay on the GDScript side of things. :) ... Probably it's not super difficult, so I could look into it and test later (but currently a bit busy with other things).

**Comment by adamscott** [comment]
You can download a build based on the master branch on [Hugo Locurio's website](https://hugo.pro/projects/godot-builds/). He's a Godot maintainer.

**Comment by takaturre** [comment]
Thanks for the info! I tried the nightly build from the link you sent (both win 64 bit versions), but it seems I can't open the project with them at all: theres' just an enormous amount of flickering errors of various messages, eg.
![image](https://user-images.githubusercontent.com/16601926/204109329-c6a93a2e-17ce-4405-9323-22757438dc14.png)

**Comment by Calinou** [comment]
> You can download a build based on the master branch from [Hugo Locurio's website](https://hugo.pro/projects/godot-builds/). He's a Godot maintainer.

These builds are currently outdated, as I didn't update the scripts to take buildsystem changes into account yet.

**Comment by takaturre** [comment]
Somehow I found myself compiling the source code (following [this tutorial](https://www.youtube.com/watch?v=zu3j89GkDwE)), and Godit working. :) However, the results are very much the same as in beta6 - or if something, then possibly a couple of seconds slower when not using the cyclical reference (about 32-37s.) compared to my beta6 tests (30-35s).

**Comment by takaturre** [comment]
I'm happy to inform that at least in Godot v4.0.beta11 I no longer need to use the "EditorStartUp.gd" - it opens up in about 10seconds in both cases..! Didn't check beta7-10 versions, and didn't yet test if I can now drop the second singleton, but will report back more later.
