### ISSUE TITLE
The navigation polygon set by "tilemap" has a pathfinding bug

### ISSUE THREAD

**Issue by xiaoliang6669** [godotengine/godot#68633]
000000000000000000

**Comment by xiaoliang6669** [comment]
#68547

**Comment by clayjohn** [comment]
I can't see anything obviously wrong in the image. Can you please upload an MRP so that other contributors can test this out and see if they can reproduce the issue?

**Comment by xiaoliang6669** [comment]
> I can't see anything obviously wrong in the image. Can you please upload an MRP so that other contributors can test this out and see if they can reproduce the issue?

I have studied for several days, and I have basically determined that this is a bug. It seems that there will be a problem of path finding between polygons of different colors. Because small polygons should be merged into large polygons, and then the "add_polygon" function is used to add navigation. If the polygons are all the same size, there is no problem, because this function sets the order of vertices, and I don't know how to implement it internally, but it will cause various problems. Using "polygon. add_outline()" will not cause such problems
