### ISSUE TITLE
Modifying a RigidBody2D's rotational inertia changes its free fall speed

### ISSUE THREAD

**Issue by BimDav** [godotengine/godot#68655]
### Godot version

3.5.1-stable

### System information

OSx 12.5.1

### Issue description

When a RigidBody2D is set up for a free fall (no forces but gravity), and has a user-defined mass, its free fall acceleration and speed are radically different whether its "inertia" property (weirdly named but representing rotational inertia) is set to 0 or != 0.

### Steps to reproduce

Create a scene with a RigidBody2D, set its mass to 5, and visualize its free fall with inertia set to 0 or 1000.

### Minimal reproduction project

[inertia.zip](https://github.com/godotengine/godot/files/10005227/inertia.zip)

**Comment by BimDav** [comment]
So, it's not really free fall since there is damping by default. Inverse mass is not correctly computed when inertia is defined by the user.

**Comment by akien-mga** [comment]
Fixed by #68659.
