### ISSUE TITLE
[macOS Godot 4.0 beta 4 ] stops responding at launch 

### ISSUE THREAD

**Issue by westleyaaj** [godotengine/godot#68670]
### Godot version

Godot 4.0 beta 4

### System information

macOS 10.14.6 2012 MacBook Air

### Issue description

Immediately after godot opens It stops responding

### Steps to reproduce

Open godot

**Comment by Calinou** [comment]
Do you see a black screen like in https://github.com/godotengine/godot/issues/57285?

**Comment by westleyaaj** [comment]
No GUI at all i just saw a icon in the dock

**Comment by westleyaaj** [comment]
Oh I just saw it opened lol

**Comment by westleyaaj** [comment]
It's just takes a while

**Comment by clayjohn** [comment]
Looks like a duplicate of https://github.com/godotengine/godot/issues/62322 which was fixed by https://github.com/godotengine/godot/pull/67746 fix will be available in beta 5
