### ISSUE TITLE
Animation not playing when passing through AnimationNodeTransition (AnimationTree)

### ISSUE THREAD

**Issue by Jaku-San** [godotengine/godot#68676]
### Godot version

3.5.1 Stable

### System information

Windows 11

### Issue description

Here is a part of the character AnimationTree :
![Screenshot (10)](https://user-images.githubusercontent.com/118238187/201820744-0f59a313-f9ee-43ea-9cfa-661e933aab95.png)
When the main character is dashing, it call a OneShot node in his AnimationTree. (fullbody_oneshot in this case) It sets the fullbody_transition to "dash", and adjust correctly the dash_blendspace.
It's not working. It doesnt play the animation.

However, if i remove "fullbody_transition" and pass "dash_blendspace" directly to fullbody_oneshot, then it works fine.
I tried added a Seek node but without success.
Is it a bug or am i missing something?
Thanks a lot.

### Steps to reproduce

Didn't have time to try if it is reproducible yet.

**Comment by Chaosus** [comment]
Please attach the minimal reproduction project.

**Comment by Jaku-San** [comment]
Sorry i solved the issue.
Actually i was setting the transition like so:
Animations["parameters/" + node_name + "_transition/current"] = input_name
input_name as string. Turns out i need an int.
It was a dumb mistake from me, however i didn't really find it intuitive, setting string in AnimationTree but having to use int from script.
