### ISSUE TITLE
Mac crashes with EXC_I386_DIV when too many of a certain scene

### ISSUE THREAD

**Issue by josephValentine** [godotengine/godot#68675]
### Godot version

4.0-beta4

### System information

Mac OS, 2 GHz Quad-Core Intel Core i5

### Issue description

In beta 4.0-beta4, I have a scene with instanced child scenes . When i instance about 30 or less of one particular scene, everything runs just fine. but if i make more than that, the debugger always crashes with `EXC_I386_DIV (divide by zero)` before it starts. As far as i can understand these scenes shouldn't require too much processing and even if they did i would expect it to crash with out of memory or something like that.

Im trying out Godot for the first time, thanks for all the work that has gone into this. Its been fun for me.

### Steps to reproduce

Let me know if this isn't enough information:
[Crash Report](https://gist.github.com/josephValentine/3a7c9a02864370eb143a109bed7d0ed4)
[Child Scene](https://gist.github.com/josephValentine/0f04f683360cbbd14477a3b3ad1694ef)

**Comment by Calinou** [comment]
> Let me know if this isn't enough information:

Indeed, we need a *complete* minimal reproduction project here.

**Comment by josephValentine** [comment]
This no longer happens as of Godot 4.0-beta6
