### ISSUE TITLE
Godot puts error in logs about C# method not found, but debugger proves otherwise

### ISSUE THREAD

**Issue by Coder2195Text** [godotengine/godot#68698]
### Godot version

Godot 4 Beta 4

### System information

Ubuntu 22.04 Running on Vulkan Mesa Intel® UHD Graphics 620 (WHL GT2)

### Issue description

This is my gamescene code

https://github.com/Coder2195Text/tile-craft/blob/master/Scripts/GameScene/GameScene.cs

All you really need to know, is that _Ready calls SetupGameScene()

I get this error in godot logs, but doesn't crash my app.

```
E 0:00:03:0514   emit_signalp: Error calling from signal 'ready' to callable: 'Control(GameScene.cs)::SetupGameScene': Method not found..
  <C++ Source>   core/object/object.cpp:1057 @ emit_signalp()
```
Obviously, this error states that SetupGameScene isnt found.

But the below provides that something is wrong with the system, because obviously you cant call a method if it doesn't exist.

First I set an breakpoint in the function that supposedly isnt found.

![image](https://user-images.githubusercontent.com/63069499/202028725-69934bf6-eefe-4b34-97cf-3b65ac86ac26.png)

Next, I run it.

![image](https://user-images.githubusercontent.com/63069499/202029009-306ba7c9-69e4-4cd0-8258-3e3e3604e9eb.png)
 
Voila, how does an supposedly non existant function recieve the breakpoint?

### Steps to reproduce

Follow the above stuff

**Comment by raulsntos** [comment]
You connected the method `SetupGameScene` to the `ready` signal of `World/CollisionLayer`. The `ready` signal has no parameters but the `SetupGameScene` takes one parameter of type `GameScene`, this parameter mismatch is what the error is complaining about.

Methods connected to signals must match the signature of the signal, this means they must have the same number of parameters and those parameters must be the right type which can only be a compatible Variant type.

The error message is confusing but there's already an issue open about it:
- https://github.com/godotengine/godot/issues/35910

Closing as duplicate.
