### ISSUE TITLE
[4.0B4]RenderingServer does not work in C# scripts

### ISSUE THREAD

**Issue by Redwarx008** [godotengine/godot#68692]
### Godot version

4.0B4 3.5

### System information

WIN10 VULKAN GTX1660TiMaxQ

### Issue description

Here is almost the same as two pieces of code, but the c # version does not work.
```c#
[Tool]
public partial class Block
{
    private Mesh _mesh;
    private RID _meshInstance;
    public Block(Node3D parent)
    {
        _meshInstance = RenderingServer.InstanceCreate();
        var world = parent.GetWorld3d();
        RenderingServer.InstanceSetScenario(_meshInstance, world.Scenario);
        BoxMesh mesh = new BoxMesh()
        {
            Size = new Vector3(20, 20, 20),
            Material = new StandardMaterial3D()
        };
        _mesh = mesh;
        RenderingServer.InstanceSetBase(_meshInstance, _mesh.GetRid());
        var xform = new Transform3D(new Basis(), new Vector3(20, 0, 20));
        RenderingServer.InstanceSetTransform(_meshInstance, xform);
        RenderingServer.InstanceSetVisible(_meshInstance, true);
    }
}
```
```python
@tool
var _mesh : Mesh = null
var _mesh_instance : RID

func _init(parent : Node3D):
	var rs = RenderingServer
	_mesh_instance = rs.instance_create()
	var world = parent.get_world_3d()
	rs.instance_set_scenario(_mesh_instance, world.scenario)
	var mesh = BoxMesh.new()
	mesh.size = Vector3(20,20,20)
	mesh.material = StandardMaterial3D.new()
	_mesh = mesh
	rs.instance_set_base(_mesh_instance, _mesh.get_rid())
	var xform = Transform3D(Basis(), Vector3(20, 100, 0))
	RenderingServer.instance_set_transform(_mesh_instance, xform)
	RenderingServer.instance_set_visible(_mesh_instance, true)
```
GDscript version works well.
![20221116001013](https://user-images.githubusercontent.com/50837890/201969159-2088cd4d-4050-47dc-800a-02c69de5df5a.png)

### Steps to reproduce

see miniproject
Attach the World.cs or world.gd script to a node

### Minimal reproduction project

[ViusalTest.zip](https://github.com/godotengine/godot/files/10014316/ViusalTest.zip)

**Comment by Redwarx008** [comment]
> I am not very familiar with C#, but where are `_mesh` and `mesh_instance` coming from? Is it possible they are going out of scope and getting freed? If they get freed then the rendering resources will get freed as well.

I'm holding them outside of the constructor, so that's not the reason

**Comment by raulsntos** [comment]
You are using `new Basis()` in the C# code which is equivalent to a zero Basis since it's a struct (every struct in C# has a parameterless constructor that zero initializes it). The GDScript `Basis()` constructor creates an identity Basis which would be the equivalent to `Basis.Identity` in C#.
