### ISSUE TITLE
fragment shader : DISCARD does not work as expected

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#6870]
**Operating system or device - Godot version:**
2.1, win 64
Windows 8.1
GPU : AMD Radeon R4

**Issue description** (what happened, and what was expected):

In theory, fragment shader's `DISCARD;` should not write any pixel.
In practice, it writes pixels using default material.

**Steps to reproduce:**

Apply this fragment shader to the TestCube.

```
float test = sin( SCREEN_UV.x * 100.0);


if ( test < 0.5 ) {
    DISCARD;
}
else {
    DIFFUSE = color(1,0,0,1).rgb;
};
```

**Link to minimal example project** (optional but very welcome):

**Comment by reduz** [comment]
this is not a bug, you have to use it as 
DISCARD=true
I will change this so it works like in GLSL anyway before 3.0 goes stable, so leaving it open

**Comment by SuperUserNameMan** [comment]
damn ... i wish i asked you directly instead of just opening this issue ... 

maybe it is not too late to update the docs btw.

**Comment by reduz** [comment]
docs where not written for a reason! i just changed the shader language to use discard GLSL command properly.
