### ISSUE TITLE
Input event order for Viewports, Areas doesn't match documentation

### ISSUE THREAD

**Issue by paulmiller** [godotengine/godot#68703]
### Godot version

3.5.1.stable, 4.0.beta

### System information

Arch Linux

### Issue description

I think this is a bug, but it's also possible I'm misunderstanding the documentation.

The [Using InputEvent](https://docs.godotengine.org/en/stable/tutorials/inputs/inputevent.html) tutorial describes this sequence:

1. Call `Node._input()` on every Node in reverse order.
2. Call `Control._gui_input()`.
3. Call `Node._unhandled_input()` on every Node in reverse order.
4. If object picking is on, call `Area._input_event()` on any picked object.
5. Repeat for the next Viewport in the tree.

If I understand that correctly, then when clicking the CollisionShape in this scene tree:

* Spatial1
    * Spatial2
    * ViewportContainer
        * Viewport
            * Spatial3
    * Area
        * CollisionShape

The order of `Spatial._input()` and `Area._input_event()` calls should be:

1. `Spatial2._input()`
2. `Spatial1._input()`
3. `Area._input_event()`
4. `Spatial3._input()`

But It seems like Viewports receive input events in order with every other Node in the tree, rather than at the end. So the order is actually:

1. `Spatial3._input()`
2. `Spatial2._input()`
4. `Spatial1._input()`
3. `Area._input_event()`

I use Godot 3 node names here but the same happens in Godot 4.

The relevant Godot 4 code seems to be `SceneTree::_call_input_pause()`; it loops over the Nodes, and if a given node happens to be a SubViewportContainer, then `Node::_call_input()` > `SubViewportContainer::input()` > `Viewport::push_input()` > `SceneTree::_call_input_pause()`, which then loops over the Nodes under the SubViewportContainer.

### Steps to reproduce

The attached Godot 3 project has the scene tree I described. Click the sphere and see the order logged in the console.

### Minimal reproduction project

[input-test.zip](https://github.com/godotengine/godot/files/10017222/input-test.zip)

**Comment by Sauermann** [comment]
Yes, the "Using InputEvent tutorial" is outdated. I intend to update it, however there are a few bugfix pull-requests waiting for review (e.g. #58334), that will have an impact on that tutorial, so I would like to update the tutorial after they get merged.

**Comment by Sauermann** [comment]
I had a look at this issue and have updated the parts of the tutorial, that will be unaffected by the outstanding PRs.
