### ISSUE TITLE
Finding a function that traverses and merges adjacent polygons

### ISSUE THREAD

**Issue by xiaoliang6669** [godotengine/godot#68705]
### Godot version

4.0-beta4

### System information

win10

### Issue description

Find a function to traverse and merge adjacent polygons. If you write it with "Geometry2D", you will lose polygons. I wonder if there is a bug

### Steps to reproduce

Find a function to traverse and merge adjacent polygons. If you write it with "Geometry2D", you will lose polygons. I wonder if there is a bug

**Comment by clayjohn** [comment]
Feature requests should be made in the [Godot Proposals](https://github.com/godotengine/godot-proposals) repository. Specifically, you should open a [discussion](https://github.com/godotengine/godot-proposals/discussions) in the proposals repository. 

This space is for bug reports only.

**Comment by Calinou** [comment]
@xiaoliang6669 Please don't ask support questions here, as this issue tracker is meant to be used for bug reports only. Use one of the other [community channels](https://godotengine.org/community) instead.
