### ISSUE TITLE
The problem of "tilemap" occupying memory

### ISSUE THREAD

**Issue by xiaoliang6669** [godotengine/godot#68712]
00000000000000000

**Comment by clayjohn** [comment]
Could you please provide more information about what the bug is? Based on the images I can't tell what the problem is. 

It is okay to type it out in your native language and then use Google translate to translate. 

Also, can you please add an MRP to your report? An MRP is the smallest possible project that can be used by a contributor to reproduce the bug you are facing. Including an MRP really helps us find and fix the bug. If you do no include one, it is unlikely we can fix the issue you are experiencing.

**Comment by xiaoliang6669** [comment]
> Could you please provide more information about what the bug is? Based on the images I can't tell what the problem is.
> 
> It is okay to type it out in your native language and then use Google translate to translate.
> 
> Also, can you please add an MRP to your report? An MRP is the smallest possible project that can be used by a contributor to reproduce the bug you are facing. Including an MRP really helps us find and fix the bug. If you do no include one, it is unlikely we can fix the issue you are experiencing.

I use a big picture to make a atlas, which is more than 800 MB after running. I divide the big picture into more than 800 pieces, which is more than 80 MB after running the atlas. I want to know why

**Comment by timothyqiu** [comment]
To hold a larger image, a larger chunk of memory is needed.

"Static Max" is, as how its named, the max chunk of static memory ever allocated. It's different from the total amount of memory that is in use.

Although `5 * 20 = 100`, the max memory chunk it needs to load a 100MB image and to load five 20MB images are different: `max(100) = 100`, `max(20, 20, 20, 20, 20) = 20`.

**Comment by xiaoliang6669** [comment]
> To hold a larger image, a larger chunk of memory is needed.
> 
> "Static Max" is, as how its named, the max chunk of static memory ever allocated. It's different from the total amount of memory that is in use.
> 
> Although , the max memory chunk it needs to load a 100MB image and to load five 20MB images are different: , .`5 * 20 = 100``max(100) = 100``max(20, 20, 20, 20, 20) = 20`
It is better to use a large image or a small image. It takes up memory

**Comment by xiaoliang6669** [comment]
> To hold a larger image, a larger chunk of memory is needed.
> 
> "Static Max" is, as how its named, the max chunk of static memory ever allocated. It's different from the total amount of memory that is in use.
> 
> Although `5 * 20 = 100`, the max memory chunk it needs to load a 100MB image and to load five 20MB images are different: `max(100) = 100`, `max(20, 20, 20, 20, 20) = 20`.

Which way should I use
