### ISSUE TITLE
Module By Zero crash the game without explanation

### ISSUE THREAD

**Issue by Alikae** [godotengine/godot#68713]
### Godot version

4.0-beta4

### System information

Windows 10

### Issue description

While executing a modulo by zero, if the zero come from Array.size(), the application crash without any error message.

### Steps to reproduce

Simply open the minimal project, then Launch it.
It will crash without explanation.

Comment the line 7 in A.gd, uncomment line 6:
The project now crash with the proper error message.

### Minimal reproduction project

[Test4beta4.zip](https://github.com/godotengine/godot/files/10017967/Test4beta4.zip)

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/67317.
