### ISSUE TITLE
Add more scripts and features for audio

### ISSUE THREAD

**Issue by toby3d** [godotengine/godot#6871]
Unfortunately, in the current state of Godot Engine are very few tools to work with audio via scripts. Why not add a function like the following:
- **retrieve_bpm_from_music** - automatic analysis of the audio to give the approximate value of BPM.
- **get_volume** - getting the audio volume in the current frame.
- **get_rms** - getting more "soft" audio volume value in the current frame
- **and other...**
## What is this for?

For example, I need to animate the mouth of the character based on a sample of his voice. The RMS value would help me to do this automatically through scripts. Or make a graphic equalizer which would have demonstrated the noise level around the character. In an extreme case, it opens up at least some space for creation of rhythm games and games based on music files.

I know that usually respond to such requests, "write your own plug-in", but:
- I do not know how to write plug-ins;
- My friend, who understands the C language, says that writing such a plugin is problematic;
- Such basic things should be in engine by default, such as a Construct Classic or Unity (which paid, non-optimized and hard-to-learn, meh!);

**Comment by vnen** [comment]
> My friend, who understands the C language, says that writing such a plugin is problematic

Why is it problematic? If this is true, then adding to the core is also problematic. *Someone* will have to write it either way.

**Comment by berserk82** [comment]
Actually, I have a similar idea I summarized in this google docs file: https://drive.google.com/open?id=1gUIwN55NA1xFu1NXDpKV7sbau_oR38TbQnpD7vd1V90
It popped in my mind to describe this when I saw a blog post about an audio API which *could* be developed for 3.x
My idea is mainly for scripting audio, but a simple editing framework could be fine.

**Comment by berserk82** [comment]
Nevermind, I saw this is already being implemented in 3.0.
I'll delete the Google Docs file, so consider the link broken.

**Comment by KoBeWi** [comment]
Is this still needed with [the new audio features](https://godotengine.org/article/godot-32-will-get-new-audio-features)?
Seems very specific to me and now it should be easier to make a plugin (probably).

**Comment by toby3d** [comment]
I think current state of the audio features in engine is ok. Last thing what can be great to implement is mp3 support #27236

**Comment by KoBeWi** [comment]
Given that's in another issue, this one can be closed then.
