### ISSUE TITLE
Font oversampling conflicts with line_spacing 0 when scaling window

### ISSUE THREAD

**Issue by rainlizard** [godotengine/godot#68721]
### Godot version

v4.0.beta4.official [e6751549c]

### System information

Windows 10, GTX 970

### Issue description

My fonts are becoming invisible (flashing in and out) as I scale the window. This is apparently because I set `line_spacing` to 0 on my labels in the inspector, I did this because it slightly shrank the size of the label. To my surprise it revealed this bug.

- Setting `Project Settings -> GUI -> Fonts -> Use Oversampling` to false will fix the issue.
- Changing the Import Settings of a font and setting `Oversampling` to 1 will also fix the issue.

Side note but I find it rather confusing that there's two oversampling settings like this, and by default they have opposing values (Project Settings Use Oversampling is enabled, Import Settings Oversampling is 0). Does this mean that no fonts have oversampling unless you set it in the font's Import Settings? If so, a tooltip for the Project Settings one that states this might be a good idea.

### Steps to reproduce

1. Set stretch mode to `canvas_items`
2. Create a label with some text and set `Line Spacing` to 0 in the inspector
3. Slowly drag resize the window and the font will disappear and reappear a lot

Different font sizes can make the issue more or less apparent and so can specific positions the labels are placed in the scene.

### Minimal reproduction project

[line_spacing_oversampling_bug.zip](https://github.com/godotengine/godot/files/10018423/line_spacing_oversampling_bug.zip)

**Comment by bruvzg** [comment]
If import setting `oversampling` is `0` it's suing viewport scale, if it's `> 0` it will override and force oversampling factor for the specific font (in this case `Project Settings -> GUI -> Fonts -> Use Oversampling` should not have any effect).
