### ISSUE TITLE
Unicode project names  not compatible with iOS export

### ISSUE THREAD

**Issue by biblical-text** [godotengine/godot#68723]
### Godot version

3.5.1

### System information

iOS 16.1, mac, xcode 

### Issue description

If you create a new hello world project, with the name `λογικός` and export it as an iOS Xcode project, and attempt to run the newly created project inside Xcode, the application will crash on startup, and report that it cannot find the .pck file.

### Steps to reproduce

Create a new hello world project, with the name λογικός and export it as an iOS Xcode project, and attempt to run the newly created project inside Xcode, the application will crash on startup, and report that it cannot find the .pck file.

### Minimal reproduction project

a blank project is fine to reproduce this problem

**Comment by akien-mga** [comment]
CC @bruvzg
