### ISSUE TITLE
Scene Tree and Node Editor Windows Not Updating Grouping Set Through Tool Script

### ISSUE THREAD

**Issue by Kalcen** [godotengine/godot#68739]
### Godot version

v4.0.beta4.official [e6751549c]

### System information

Windows 10

### Issue description

I'm making an addon that adds itself to a group on `_enter_tree()`, it seems like this is working fine despite the group not appearing in the Groups window nor is the group icon appearing next to the node's name in the Scene Tree window. I re-enabled the plugin, disabled/enabled the custom node, and removed/added the custom node in the scene tree.

![scrn1](https://user-images.githubusercontent.com/38251868/202235507-50658f24-4a0e-41b1-8043-ca703976dde1.png)

### Steps to reproduce

Install the custom plugin, enable it and place its custom node SpawnerNode into a 3D scene. The script containing `add_to_group()` is spawner.gd.

### Minimal reproduction project

[spawner_node_group_issue.zip](https://github.com/godotengine/godot/files/10023796/spawner_node_group_issue.zip)

**Comment by KoBeWi** [comment]
try `add_to_group("player_spawn", true)`

**Comment by Kalcen** [comment]
That was the issue, I totally missed that thank you!

**Comment by KoBeWi** [comment]
Ok closing.
#68560 will improve the docs, so will be more clear.
