### ISSUE TITLE
Jumping to bookmark doesn't clear selection

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#68737]
### Godot version

4.0 2846ea1 / 3.5

### System information

Windows 10 x64

### Issue description

![godot windows editor dev x86_64_dGWGEAKT4I](https://user-images.githubusercontent.com/2223172/202222655-477c1640-6b36-4da4-b987-b38f6ef7d0a4.gif)

### Steps to reproduce

1. Add a bookmark
2. Select some text elsewhere
3. Jump to bookmark
4. Type something
5. Instead of typing at bookmark, the selected text is replaced

**Comment by MewPurPur** [comment]
On it.
