### ISSUE TITLE
Any way to set the background of a 2D viewport?

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#6875]
I am trying to use a Viewport in 2D, but I failed so far at setting its background to a solid color.

I tried this so far:

``` gdscript
    var world = World.new()
    var env = Environment.new()
    env.set_background(Environment.BG_COLOR)
    env.set_background_param(Environment.BG_PARAM_COLOR, Color(0,0,0))
    world.set_environment(env)
    viewport.set_world(world)
    viewport.set_use_own_world(true)
```

But it has no effect in 2D. It just uses the default background color...

Is this feature available in Godot? Or not exposed? Or a bug?

Edit: quick note, my use case involves rendering to a texture, in case detail matters

**Comment by eon-s** [comment]
World is for Spatial, World2D is for Node2D

**Comment by Zylann** [comment]
But... I don't see a set_world_2d(). There is only find_world_2d(). How is it supposed to work?

**Comment by eon-s** [comment]
@Zylann I think what you are looking for may be on CanvasItem.

What do you don't want to do to set a background, just avoid the use of textures?

**Comment by bojidar-bg** [comment]
The thing is, the example from the OP should work.... (try it with a normal WorldEnvironment node at home).

**Comment by eon-s** [comment]
@bojidar-bg WorldEnvironment affects 2D too? I thought were only Spatial (used with environment for general skyboxes, glow, etc.).

**Comment by Zylann** [comment]
@bojidar-bg I tried to use WorldEnvironment but this is for 3D. Also it still doesn't works, and prints an error:
```
ERROR: RID_Owner<struct RasterizerGLES2::Texture,0>::get: Condition ' !elem ' is true. returned: 0
   At: core\rid.h:146
ERROR: RasterizerGLES2::texture_set_flags: Condition ' !texture ' is true.
   At: drivers\gles2\rasterizer_gles2.cpp:1280
```
I tried to add a camera under the viewport with current set to true, with no luck.

**Comment by bojidar-bg** [comment]
@Zylann can you try doing it from the editor (with a Viewport inside a Control node), since this should actually work? (I might do a sample project if it really doesn't, lol)

**Comment by Zylann** [comment]
I tried this from the editor too but it didn't seem to work. Also, why should I use a Control?
I can try again when I get back home since I'm not sure I tested exactly what you said.

**Comment by Zylann** [comment]
I am stumbling into this again today in 2.1.4, I can't for the life of me figure out how to change this background color. This time, it's nothing fancy (no render to texture or anything), I just want to change the background color using an auto-load with the same code as written above, but nothing works.

I even tried this:

```gdscript
extends Node

func _ready():
	var world_environment = WorldEnvironment.new()
	var env = preload("default_environment.tres")
	world_environment.set_environment(env)
	add_child(world_environment)
```

And it doesn't work.

**Comment by icnikerazah** [comment]
@Zylann this doesn't work for me.
```
extends Node

func _ready():
	VisualServer.set_default_clear_color(Color(0,0,0))

```
I want change clear color in run-time by script. How can i do it?

**Comment by Zylann** [comment]
@icnikerazah it worked for me in 2.1.4, do you mean it's broken/changed in 3.0?

**Comment by icnikerazah** [comment]
@Zylann yes in 3.0 on MacOs

**Comment by eon-s** [comment]
I can confirm (on Ubuntu) that does not change the clear color on 2D, also environment options do not work (color on canvas mode).

**Comment by TheTokenMaster** [comment]
I think there should be an easy and clear way to set the clear colour of an individual 2D viewport/camera because having a viewport clear itself just to have a 2D ploy/frame re-clear it to the desired colour is wasteful of render time, not very wasteful, but render time costs.

**Comment by FeralBytes** [comment]
This is a needed feature so that the project default render color does not effect every 2D viewport.

**Comment by KoBeWi** [comment]
As of Godot 4.1, there are at least 3 ways (workarounds) to set viewport's background color:
1. `RenderingServer.set_default_clear_color()`. It's global, so not ideal
2. Add Environment and Camera3D. The camera will render the background and 2D elements will overlay it
3. If the viewport is meant to be displayed, enable transparent background and put e.g. ColorRect under the viewport container

If these workarounds are not sufficient and you want to set background per-viewport, [open a proposal](https://github.com/godotengine/godot-proposals).

**Comment by Calinou** [comment]
> If these workarounds are not sufficient and you want to set background per-viewport, [open a proposal](https://github.com/godotengine/godot-proposals).

There's already a proposal: https://github.com/godotengine/godot-proposals/issues/252
