### ISSUE TITLE
The InputMap event configuration dialog fails to setup analog axes when the input strength is too low

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#68765]
### Godot version

4.0.beta5

### System information

linux

### Issue description

The even configuration dialog allows to press a key or move a joystick to automatically configure the action.
The dialog does detect the input but the actual action is not selected if the joystick/analog trigger strength is too low (it seems that "too low" is "<1.0", but I'm not sure).

https://user-images.githubusercontent.com/71937306/202348201-e20b69ab-9d4d-4e16-8c29-8262fcd849e2.mp4

Such low values happens on the controllers I own even when pressed at max strength, making it impossible for me to configure these actions automatically (my xbox 360 controller's joystick value are usually around .95).

A fix should be to add a very low deadzone.

### Steps to reproduce

Try associating an analog event to an action and notice how the correct event isn't select by the dialog unless the action strength is close to 1.

**Comment by EricEzaM** [comment]
Thank you for the report. I noticed this when testing #68617 and both this issue and that one were resolved in #68821
