### ISSUE TITLE
Too laggy frame loss in pathfinding

### ISSUE THREAD

**Issue by xiaoliang6669** [godotengine/godot#68763]
00000000000000000000

**Comment by clayjohn** [comment]
CC @smix8

**Comment by Calinou** [comment]
@xiaoliang6669 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by smix8** [comment]
Using "set_cell" makes the entire TileMap quadrant dirty.
The dirty quadrant refreshes all cell navregions on the NavigationServer.
The change to the navregions triggers a update of the navigation map.
From the other issues I remember user has a lot of tile cells in use, hence why it lags when all of them need to update in both TileMap quadrant and navigation map.

**Comment by xiaoliang6669** [comment]
> Using "set_cell" makes the entire TileMap quadrant dirty.
> 
> The dirty quadrant refreshes all quadrant cell navregions on the NavigationServer.
> 
> The change to the navregions triggers a update of the navigation map (e.g. recalculation all the edge connections between the tiles).
> 
> From the other issues of the same user I remember user has a lot of tile cells in use, hence why it lags when all of them need to update in both TileMap quadrant and navigation map.
> 
> I think adding a function to only set for each cell would help with this as changing the navigation_layers bitmask does not trigger update to the TileMap quadrant or the navigation map and only affects the next path query for the NavigationAgents.`navigation_layers`

Set different layers for each tile? What is the impact of using "set_cell" to load and unload tiles on game performance and memory? I won't use it if the impact is small, because I don't know much about the operating principle of "tilemap"

**Comment by smix8** [comment]
> What is the impact of using "set_cell" to load and unload tiles on game performance and memory? I won't use it if the impact is small, because I don't know much about the operating principle of "tilemap"

Can not tell performance details around TileMap as I am involved with navigation and less with 2D or TileMap, maybe @groud can answer that.

> Set different layers for each tile?

The current Godot 4 TileMap creates a navigation `region` on the NavigationServer for each cell that uses TileSet tiles with baked navigation.

Each of navigation `region` uses the `navigation_layers` set on the TileMap. This is a limitation of the current TileMap not of the navigation `region`. You can can set different `navigation_layers` per navigation `region` in general using the NavigationServer.

If you make a navigation path query the `navigation_layers` control if this `region` is considered in the path query. This avoids all the performance costly updates that changing the entire cells directly would require and that could be the cause of the performance problems you are facing in your project.

You can receive all the created `region` RIDs for the default navigation `map` with `NavigationServer2D.map_get_regions(get_world_2d().get_navigation_map())` but there is currently no way to know which region maps to which TileMap cell. If you know which region is which cell you could use those `region` RID's with `NavigationServer2D.region.set_navigation_layers(layers)` where `layers` is the int bitmask to control the navigation.

E.g.
layers = 0 --> no one can use the cell / region in a navigation path query.
layers = 1 --> all (default) agents can use the cell / region
layers = 2 --> only agents that have the second bit enabled can use the cell / region.
layers = 4 --> only agents that have the third bit enabled can use the cell / region.

**Comment by xiaoliang6669** [comment]
> > What is the impact of using "set_cell" to load and unload tiles on game performance and memory? I won't use it if the impact is small, because I don't know much about the operating principle of "tilemap"
> 
> Can not tell performance details around TileMap as I am involved with navigation and less with 2D or TileMap, maybe @groud can answer that.
> 
> > Set different layers for each tile?
> 
> The current Godot 4 TileMap creates a navigation on the NavigationServer for each cell that uses TileSet tiles with baked navigation.`region`
> 
> Each of navigation uses the set on the TileMap. This is a limitation of the current TileMap not of the navigation . You can can set different per navigation in general using the NavigationServer.`region``navigation_layers``region``navigation_layers``region`
> 
> If you make a navigation path query the control if this is considered in the path query. This avoids all the performance costly updates that changing the entire cells directly would require and that could be the cause of the performance problems you are facing in your project.`navigation_layers``region`
> 
> You can receive all the created RIDs for the default navigation with but there is currently no way to know which region maps to which TileMap cell. If you know which region is which cell you could use those RID's with where is the int bitmask to control the navigation.`region``map``NavigationServer2D.map_get_regions(get_world_2d().get_navigation_map())``region``NavigationServer2D.region.set_navigation_layers(region_rid, layers)``layers`
> 
> E.g. layers = 0 --> no one can use the cell / region in a navigation path query. layers = 1 --> all (default) agents can use the cell / region layers = 2 --> only agents that have the second bit enabled can use the cell / region. layers = 4 --> only agents that have the third bit enabled can use the cell / region.

It's too much trouble. We should wait for the official to handle it

**Comment by groud** [comment]
> It's too much trouble. We should wait for the official to handle it

Sorry that's not really how it works, we can't optimize every system to everyone's special case. The TileMap node is optimized to render fast, and changing a few tiles from time to time should have a low enough impact on performances.

However, here are the things you should not do at runtime:
- Edit the TileSet or one of its atlas properties. This ALWAYS triggers a full update of the full TileMap.
- Replace tiles too often, for any reason (animation, change of state, etc... ). If you do it anyway, you should make sure to set the quandrant_size to 1, so that a quadrant is very small. This will have an impact on general performance and memory footprint, but updates should be less problematic.

For very dynamic object, or, in general, objects with change that would cause issues, please consider using a SceneCollectionTileSetSource and thus use scene tiles. Those are a lot more efficient to handle dynamic behaviors.

**Comment by xiaoliang6669** [comment]
> > It's too much trouble. We should wait for the official to handle it
> 
> Sorry that's not really how it works, we can't optimize every system to everyone's special case. The TileMap node is optimized to render fast, and changing a few tiles from time to time should have a low enough impact on performances.
> 
> However, here are the things you should not do at runtime:
> 
> * Edit the TileSet or one of its atlas properties. This ALWAYS triggers a full update of the full TileMap.
> * Replace tiles too often, for any reason (animation, change of state, etc... ). If you do it anyway, you should make sure to set the quandrant_size to 1, so that a quadrant is very small. This will have an impact on general performance and memory footprint, but updates should be less problematic.
> 
> For very dynamic object, or, in general, objects with change that would cause issues, please consider using a SceneCollectionTileSetSource and thus use scene tiles. Those are a lot more efficient to handle dynamic behaviors.

I don't know how "tilemap" works and optimizes internally. I'm worried that the large map will affect the memory performance, so dividing a 11200 * 5760 resolution map image into more than 800 copies of dynamic loading and unloading leads to these problems in navigation. If I only use a 11200 * 5760 map to directly display it on my mobile phone, will it affect the performance?

**Comment by groud** [comment]
I don't think any mobile game would be able to display such a big texture. You should probably split your map manually into chunks and implement a dynamic loading system.
TileMap aren't really made for being used that way and will not provide any kind of performance improvement compared to a normal scene, as they will load the whole texture anyway. They are meant so that you can easily reuse small components, not to be a grid-based editor on a big texture.

**Comment by xiaoliang6669** [comment]
> I don't think any mobile game would be able to display such a big texture. You should probably split your map manually into chunks and implement a dynamic loading system. TileMap aren't really made for being used that way and will not provide any kind of performance improvement compared to a normal scene, as they will load the whole texture anyway. They are meant so that you can easily reuse small components, not to be a grid-based editor on a big texture.

I see. Thank you
