### ISSUE TITLE
Xcode complains `English.lproj` should be named `en.lproj`

### ISSUE THREAD

**Issue by biblical-text** [godotengine/godot#68762]
### Godot version

3.5.1

### System information

MacOS Ventura 13.0.1, Xcode 14.1

### Issue description

The latest version of Xcode doesn't like how godot exports some files. It generates the following warning. I believe it doesn't integer with deployment (it's only a warning), but it might be best to fix this now so users aren't presented with warnings by Xcode??

`Migrating the “English, deprecated” localization to “English” is recommended for all projects. This will ensure localized resources are placed in “en.lproj” directories instead of deprecated “English.lproj” directories.`

### Steps to reproduce

Export a generic hello world project for XCode

### Minimal reproduction project

Export a generic hello world project for XCode

**Comment by bruvzg** [comment]
ISO codes for locales should be supported starting from Xcode 9, so it should be safe to update it.
