### ISSUE TITLE
SurfaceTool isn't applying textures to certain primitives when generating a mesh.

### ISSUE THREAD

**Issue by Sindern** [godotengine/godot#6876]
**Operating system or device - Godot version:**
MacOSX : Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64 x86_64

Also confirmed not working on my Linux box; Debian 7.

Godot 2.1  ( Downloaded via Steam ) 

**Issue description** 
It seems that when using SurfaceTool to generate a mesh, textures can't be applied to TRIANGLE_STRIP or TRIANGLE_FAN (possibly others).  It does apply to TRIANGLES though.

**Steps to reproduce:**
1.  Create a scene laid out like so: 

```
[Node]
  \- Camera
  \- Light Source
  \- MeshInstance
```

Add a script to the MeshInstance for generating a mesh via surface tool.  Try applying a texture to a triangle strip or fan. 

**Link to minimal example project** (optional but very welcome):

PRIMIVIVE_TRIANGLES script below is based on this: http://www.gamefromscratch.com/post/2015/09/25/Godot-Engine-Tutorial-Part-15-Static-and-Programmatic-3D-Meshes.aspx

```
extends MeshInstance

func _ready():
  var surfTool = SurfaceTool.new()
  var mesh = Mesh.new()
  var material = FixedMaterial.new()
  material.set_parameter(material.PARAM_DIFFUSE,Color(1,0,0,1))

  surfTool.set_material(material)
  surfTool.begin(VS.PRIMITIVE_TRIANGLES)

  surfTool.add_uv(Vector2(0,0))
  surfTool.add_vertex(Vector3(0,0,0))

  surfTool.add_uv(Vector2(0,1))
  surfTool.add_vertex(Vector3(0,5,0))

  surfTool.add_uv(Vector2(1,1))
  surfTool.add_vertex(Vector3(5,5,0))

  surfTool.generate_normals()
  surfTool.index()
  surfTool.commit(mesh)

  self.set_mesh(mesh)
```

The texture is properly applied to the triangle, but if you try to generate other primitives, such as triangle strips, you just get a pure black mesh.

PRIMITIVE_TRIANGLE_STRIPS : 

```
extends MeshInstance

func _ready():
  var surfTool = SurfaceTool.new()
  var mesh = Mesh.new()
  var material = FixedMaterial.new()
  material.set_parameter(material.PARAM_DIFFUSE,Color(1,0,0,1))

  surfTool.set_material(material)
  surfTool.begin(VS.PRIMITIVE_TRIANGLE_STRIP)

  surfTool.add_uv(Vector2(0,0))
  surfTool.add_vertex(Vector3(0,0,0))

  surfTool.add_uv(Vector2(0,1))
  surfTool.add_vertex(Vector3(0,5,0))

  surfTool.add_uv(Vector2(1,0))
  surfTool.add_vertex(Vector3(5,0,0))

  surfTool.add_uv(Vector2(1,1))
  surfTool.add_vertex(Vector3(5,5,0))

  surfTool.generate_normals()
  surfTool.index()

  surfTool.commit(mesh)

  self.set_mesh(mesh)
```

**Comment by bojidar-bg** [comment]
Have seen this as well

**Comment by Sindern** [comment]
If anyone else comes across this before it's fixed, there's a workaround you can use with SurfaceTool.add_triangle_fan()  http://docs.godotengine.org/en/latest/classes/class_surfacetool.html#class-surfacetool-add-triangle-fan

Sample: 

```
extends MeshInstance

func _ready():
  
  var surfTool = SurfaceTool.new()
  var mesh = Mesh.new()
  var material = FixedMaterial.new()
  material.set_parameter(material.PARAM_DIFFUSE,Color(1,0,0,1))
  
  surfTool.set_material(material)
  surfTool.begin(VS.PRIMITIVE_TRIANGLES)
  
  var uv1 = Vector2(0,0)
  var v1 = Vector3(0,0,0)
  
  var uv2 = Vector2(0,1)
  var v2 = Vector3(0,5,0)

  var uv3 = Vector2(1,1)
  var v3 = Vector3(5,5,0)

  var uv4 = Vector2(1,0)
  var v4 = Vector3(5,0,0)

  var uvarray = [ uv1, uv2, uv3, uv4]
  var varray = [ v1, v2, v3, v4 ]
  
  surfTool.add_triangle_fan(varray,uvarray)
  
  surfTool.generate_normals()
  surfTool.index()
  
  surfTool.commit(mesh)
  
  self.set_mesh(mesh)
```

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.
