### ISSUE TITLE
Some icon's are not filled when exporting iOS app

### ISSUE THREAD

**Issue by biblical-text** [godotengine/godot#68764]
### Godot version

3.5.1

### System information

MacOS 13.0.1, Xcode 14.1

### Issue description

If you fill out each icon size in the iOS export dialogue box, not every icon is filled in the resulting project export.  

Here is an image showing what it looks like after opening with Xcode 14.1

<img width="629" alt="Screenshot 2022-11-17 at 11 20 19 AM" src="https://user-images.githubusercontent.com/88878602/202346822-cd8b58a6-ea8b-4047-aa8d-edd86e25737d.png">

### Steps to reproduce

Create a generic placeholder project. Fill every icon in the iOS export project settings panel. Export the project, then open the project in Xcode 14.1

### Minimal reproduction project

Create a generic placeholder project. Fill every icon in the iOS export project settings panel. Export the project, then open the project in Xcode 14.1

**Comment by bruvzg** [comment]
These icons are optional, we can add it to the export list to set manually (generating it from the same `icon.png` won't give any benefits), but not having it set should not cause any issues.

**Comment by zaddok** [comment]
If we can’t specify the smaller icons in the Godoy export panel, we I’ll have to manually set all of these icons inside Xcode every time we do a project export.  It would definitely save time if the export process allows including images for the smaller icons.

Right now, the workaround is to manually create a checklist document of “post export activities” that includes dragging the small icons from the project folder across into Xcode. 

Or are we missing something? How do people normally set custom small icons for iOS projects?
