### ISSUE TITLE
The `load()` function does not return the resource font if loaded from an absolute path

### ISSUE THREAD

**Issue by shinspiegel** [godotengine/godot#68772]
### Godot version

4.0 Beta 4

### System information

Macbook Pro (M1)

### Issue description

I'm trying to use the `load()` function to pick a font in the fonts folder. But this returns a `null` object instead of the `resource`. The font does exist, but I could not find a way to load it from the absolute path.

### Steps to reproduce

1. Create a new project, add a new node, and add a script, on the `_ready` function use the following
2. `load("/absolute/path/to/font/file.tff")`
3. This will return a `null` object

**Comment by dalexeev** [comment]
Not a bug, `load` only works with `res://`. Use [FontFile.load_dynamic_font](https://docs.godotengine.org/en/latest/classes/class_fontfile.html#class-fontfile-method-load-dynamic-font) instead.

**Comment by shinspiegel** [comment]
Maybe I update the `load()` description on the docs to add a small note on this use case?  
Or this is not needed?

**Comment by KoBeWi** [comment]
I think load does work with absolute paths, but you can't load imported resources (and Font is imported since recently).

**Comment by shinspiegel** [comment]
I was using the Beta4 and I could not read any file outside the `res://` or `user://`. Would you mind giving some extra details @KoBeWi ?

**Comment by KoBeWi** [comment]
This works:
```GDScript
load("C:/Any/Folder/Anywhere/SomeScene.tscn")
```
Loading with absolute paths is possible if the file is not imported, i.e. you can load tscn, gd, tres files etc., but not png, wav, glb.

**Comment by shinspiegel** [comment]
> This works:
> 
> ```gdscript
> load("C:/Any/Folder/Anywhere/SomeScene.tscn")
> ```
> 
> Loading with absolute paths is possible if the file is not imported, i.e. you can load tscn, gd, tres files etc., but not png, wav, glb.

Looks like the real issue is with loading anything that could not be parsed as a resource. 
And because the font used to be parsed as a resource, and does not parse like a resource now, it's needed to use a different method to solve this.

Thanks for the information.
