### ISSUE TITLE
Hitting [shift] + [tab] in the code editor doesn't work in 4.0 when no text is selected

### ISSUE THREAD

**Issue by robbertzzz** [godotengine/godot#68783]
### Godot version

4.0 beta 5

### System information

Windows 11

### Issue description

In Godot 3.x, [shift] + [tab] will remove one tab from the start of the line even when no text is selected. In Godot 4.x, text needs to be selected for this to work. Godot's 3.x behaviour is in line with most IDEs and code editors, so reporting this as a bug.

### Steps to reproduce

1. Create a script (the default script will do) and open it in the code editor.
2. Place the cursor/caret on an indented line.
3. Press [shift] + [tab].
4. Observe that nothing happens when no text is selected.

**Comment by MewPurPur** [comment]
Or when the caret sits on tabs.

This has been annoying me for a good while, I'll look into it. BTW it's older than multi-carets, I'm fairly sure.

**Comment by MewPurPur** [comment]
https://github.com/godotengine/godot/issues/50279 This is a duplicate apparently
