### ISSUE TITLE
Scoop installation fails in beta 5 due to file name collision introduced in #67434

### ISSUE THREAD

**Issue by cedriclevarlet** [godotengine/godot#68782]
### Godot version

4.0-beta5

### System information

Windows 11

### Issue description

The godot beta 5 has introduced a new executable in #67434.

Scoop's `pre_install` command attempts to match the executable using this pattern:
`"Get-ChildItem \"$dir\\Godot_*.exe\" | Rename-Item -NewName 'godot-mono.exe'",`

Since the new file `Godot_v4.0-beta5_mono_win64_console.exe` also matches this pattern, it fails to copy the files over correctly and the installation returns the following error:
```bash
Running pre_install script...
Rename-Item: Cannot create a file when that file already exists.
```

The installation seems to complete after this but when opening godot, it would appear that the executable that is renamed is the new console file and godot is therefore unable to open correctly.

### Steps to reproduce

1. In your terminal type: `scoop install godot-mono-beta`
2. Output should be similar to this:
```bash
Installing 'godot-mono-beta' (4.0-beta5) [64bit] from versions bucket
Loading Godot_v4.0-beta5_mono_win64.zip from cache
Checking hash of Godot_v4.0-beta5_mono_win64.zip ... ok.
Extracting Godot_v4.0-beta5_mono_win64.zip ... done.
Running pre_install script...
Rename-Item: Cannot create a file when that file already exists.
Linking ~\scoop\apps\godot-mono-beta\current => ~\scoop\apps\godot-mono-beta\4.0-beta5
Creating shim for 'godot-mono'.
Creating shortcut for Godot Engine (Mono) (godot-mono.exe)
'godot-mono-beta' (4.0-beta5) was installed successfully!
```
3. Go to the installation directory
4. You should now see that the console executable is now being incorrectly renamed to godot-mono.exe. The created shortcuts to start godot now point to the console executable instead of the godot executable.
![image](https://user-images.githubusercontent.com/7115312/202441379-f4e35683-d151-4ceb-85f5-fe141adfdf84.png)
![image](https://user-images.githubusercontent.com/7115312/202441575-5a55ff69-8bea-4e4f-9446-73a2c0902a4d.png)

**Comment by akien-mga** [comment]
This is an intentional change, so it's not a Godot bug.

The scoop scripts should be fixed by scoop maintainers, so it should be reported here:
https://github.com/ScoopInstaller/Versions

They need to fix `godot-beta` and `godot-mono-beta`, and should likely also change `godot`, `godot-mono`, and `godot-alpha` in prevision for future updates.
