### ISSUE TITLE
Window nodes lock/group children, making it impossible to edit using the 2D editor.

### ISSUE THREAD

**Issue by Rodeo-McCabe** [godotengine/godot#68793]
### Godot version

4 beta 5

### System information

Linux

### Issue description

Nodes that derive from Viewport lock and group their children automatically and this can't be undone. This is apparently intentional: https://github.com/godotengine/godot/issues/51539

However, it makes editing scenes like popup windows very difficult, since you cannot adjust positions, margins, or anchors using the 2D editor. In fact, there is not even an outline displayed on the node, so even editing it using the inspector is practically impossible because you can't see what you're doing.

### Steps to reproduce

1. Make a scene with a popup or dialog of some kind as the root node.
2. Add some child controls.
3. Attempt to move, resize, or anchor the child controls.
4. Experience frustration.

**Comment by SpicerXD** [comment]
Is there any recommended workaround for this? The issue makes working with windows at all very troublesome.

**Comment by koteyur** [comment]
Also got stuck with this problem when updating my app (map editor) from 3.5 to 4.1. The only workaround which I found is to temporary move child nodes outside of dialog nodes, edit them and move back. This is far from convenient, but at least I can see what I do. AFAIK Godot's editor is made using Godot, so I'm curious how Godot developers work with editor's dialogs.

**Comment by kitbdev** [comment]
- fixed by #99401
