### ISSUE TITLE
Splash screen minimum display time does not work properly on macOS

### ISSUE THREAD

**Issue by bmercury** [godotengine/godot#68798]
### Godot version

4.0 beta 5

### System information

MacOS Monterey M1

### Issue description

Setting the "minimum display time" parameter in project settings under Application>Boot splash does not show the custom image (nor the default one) for that amount of time. Instead when the app is run either from an editor or the project manager, it waits until that time is over and then splashes for a very short time (as if no custom time was set)

This happens when run from the editor.
This happens when run from the project manager.

### Steps to reproduce

1. Create a new project
2. Set a custom image for splash screen (or leave default)
3. Set minimum display time to some notable duration (e.g 4 seconds / 4000ms )
4. Run the project
5. The game window is not visible (although shown in the doc)
6. After the time is over (4s in this case) the window is finally shown with the custom splash image(visible for less than a second) and then loads the main scene

**Comment by Calinou** [comment]
If you have access to Windows or Linux machines, can you reproduce the issue there? Splash screen drawing is OS-specific.

**Comment by bmercury** [comment]
> If you have access to Windows or Linux machines, can you reproduce the issue there? Splash screen drawing is OS-specific.

Unfortunately I do not have other operating systems available at the moment.

**Comment by RumblingTurtle** [comment]
> If you have access to Windows or Linux machines, can you reproduce the issue there? Splash screen drawing is OS-specific.

Not reproducible on Ubuntu 20.04.4 LTS

**Comment by souplamp** [comment]
> If you have access to Windows or Linux machines, can you reproduce the issue there? Splash screen drawing is OS-specific.

Couldn't reproduce on Windows 10.

**Comment by lostminds** [comment]
I get the same issue on macOS 13, Godot 4.0.beta7. I set the minimum_display_time to try out and see how a custom boot splash image would appear, but at least on macOS it seems that the wait time that property controls happens before the game window is displayed on screen like @bmercury described.

It seems that this delay is happening in https://github.com/godotengine/godot/blob/829d49b0110edc7bf283c7cca30cddb967bccb70/main/main.cpp#L3062-L3068 which is after the window has been created. But perhaps on macOS the system window server has not yet had time to move the window on screen when the delay happens so it's not visible?

**Comment by Calinou** [comment]
For reference, this feature was implemented in https://github.com/godotengine/godot/pull/41833.

cc @dalexeev

**Comment by dalexeev** [comment]
I don't have access to macOS and don't know Godot core, but here's what I found.

The boot splash delay occurs at the end of `Main::start`.

https://github.com/godotengine/godot/blob/a7937fe54cd2c1f407a529e46e2708aea5ce7243/main/main.cpp#L3062-L3068

This function is called in the corresponding `main` for different platforms.

<details>
<summary>Details</summary>

https://github.com/godotengine/godot/blob/a7937fe54cd2c1f407a529e46e2708aea5ce7243/platform/macos/godot_main_macos.mm#L77-L89

https://github.com/godotengine/godot/blob/a7937fe54cd2c1f407a529e46e2708aea5ce7243/platform/linuxbsd/godot_linuxbsd.cpp#L61-L75

https://github.com/godotengine/godot/blob/a7937fe54cd2c1f407a529e46e2708aea5ce7243/platform/windows/godot_windows.cpp#L164-L181

</details>

Inside which the `MainLoop` functions are called.

<details>
<summary>Details</summary>

https://github.com/godotengine/godot/blob/a7937fe54cd2c1f407a529e46e2708aea5ce7243/platform/macos/os_macos.mm#L665-L689

https://github.com/godotengine/godot/blob/a7937fe54cd2c1f407a529e46e2708aea5ce7243/platform/linuxbsd/os_linuxbsd.cpp#L861-L884

https://github.com/godotengine/godot/blob/a7937fe54cd2c1f407a529e46e2708aea5ce7243/platform/windows/os_windows.cpp#L1265-L1280

</details>

`MainLoop::initialize()` is the same for all platforms.

https://github.com/godotengine/godot/blob/a7937fe54cd2c1f407a529e46e2708aea5ce7243/core/os/main_loop.cpp#L59-L65

I guess there is some difference between platforms in

```cpp
if (Main::start()) { 
    os.run();
} 
```

That is, on MacOS something is called in `os.run()`, and on other platforms in `Main::start()` or earlier. But comparing these files, I did not notice any clues.
