### ISSUE TITLE
GPUParticles3D amount parameter emits wrong number of particles when using scale curve

### ISSUE THREAD

**Issue by Mikeysax** [godotengine/godot#68809]
### Godot version

4.0beta4

### System information

PopOS 22.04, 6.0.3-76060003-generic kernel, Ryzen 6800h, Radeon 6700m, amdgpu, Vulkan

### Issue description

When setting the GPUParticles amount to 1, 3, 6, and maybe other, the particles emitted are the same as setting amount to 1 if a scale curve is applied

### Steps to reproduce

Setup a GPUParticles3D with a ParticalProcessMaterial and change the amount with a scale curve applied to the ParticalProcessMaterial:

https://user-images.githubusercontent.com/15805689/202588137-ebdeb652-4cf4-4900-a585-7ef0acee6d92.mp4

https://user-images.githubusercontent.com/15805689/202586281-4a848458-54a2-4e93-a68f-85016cf6a2be.mp4

### Minimal reproduction project

https://github.com/Mikeysax/example-project-godot-bug-gpu-particle-amount-bug-

**Comment by Calinou** [comment]
@Mikeysax Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by Mikeysax** [comment]
https://github.com/Mikeysax/example-project-godot-bug-gpu-particle-amount-bug-

**Comment by clayjohn** [comment]
I can't reproduce this issue on PopOS 22.04 I attempted with beta 4 and beta 9

**Comment by EzraT** [comment]
I can confirm this still happens in RC1 in one of my personal projects, one of my particle systems almost stops emitting altogether after a few seconds when a scale curve is used. As soon as I take away the curve it starts working correctly again.

https://user-images.githubusercontent.com/781121/219049175-0992e36e-41ed-47d9-8e71-83ca7201c50f.mp4

As can be seen in the video, it doesn't seem to stop emitting entirely, for whatever reason it's just way less then it should be with a scale curve applied.

**Comment by Calinou** [comment]
This can be worked around by ensuring the beginning and end points of the curve are not exactly 0.0 (e.g. `0.01`) works. It looks *mostly* the same, but the particle amount will not decrease over time.

**Comment by clayjohn** [comment]
I wonder if this is the same underlying problem as https://github.com/godotengine/godot/issues/55396. If it is, https://github.com/godotengine/godot/pull/55397 may help

**Comment by QbieShay** [comment]
@clayjohn I believe there's NaN' ing issues in those scales. I think it's possible that sometimes scales goes close to zero, then float point precision, then it's actually zeros, and there's a bunch of NaN going being fed every frame into the transform. In my own project i set the scale to never be exactly zero to work around this issue.

**Comment by QbieShay** [comment]
I also suspect that scale curves have repeat on when they're sampled, causing scale to wrap around

**Comment by Calinou** [comment]
> I also suspect that scale curves have repeat on when they're sampled, causing scale to wrap around

Repeat is already disabled on the scale texture: https://github.com/Calinou/godot/blob/91c0b62451ecff469d4857c7bb7977d3f15f7fd4/scene/resources/particle_process_material.cpp#L282
