### ISSUE TITLE
When I run my game, it boots to a white screen with a button.

### ISSUE THREAD

**Issue by tt2806** [godotengine/godot#68807]
### Godot version

3.2.3.stable.custom_build

### System information

Chrome OS, GLES2 (won't let me change to gles3), arm64 processor

### Issue description

When I run the game (with just pixel art loaded on to it), instead of booting to the actual game, it boots to a white screen with a button. Clicking on the button closes the window. I've seen this before actually, didn't find out what happened but it was the same exact screen.

Here's some more information:
When I start Godot 3 in the terminal, it throws these errors:

X Error of failed request:  GLXBadFBConfig
  Major opcode of failed request:  150 (GLX)
  Minor opcode of failed request:  34 ()
  Serial number of failed request:  25
  Current serial number in output stream:  22
X Error of failed request:  GLXBadFBConfig
  Major opcode of failed request:  150 (GLX)
  Minor opcode of failed request:  34 ()
  Serial number of failed request:  25
  Current serial number in output stream:  22
ERROR: initialize: Condition "ctxErrorOccurred || !p->glx_context" is true. Returned: ERR_UNCONFIGURED
   At: platform/x11/context_gl_x11.cpp:190.
ERROR: is_viable: Error initializing GLAD
   At: drivers/gles3/rasterizer_gles3.cpp:141.

[White screen](https://i.imgur.com/uIAbJUK.png)

### Steps to reproduce

I don't know how to reproduce this issue.

**Comment by Calinou** [comment]
[Godot 3.2.x is not supported for bug fixes anymore](https://docs.godotengine.org/en/stable/about/release_policy.html#release-support-timeline), so please upgrade to [3.5.1](https://godotengine.org/article/maintenance-release-godot-3-5-1) and check if the issue still occurs there.
