### ISSUE TITLE
There is no explanation in the documentation of how 3D Gizmo works in local mode with multiple selecting

### ISSUE THREAD

**Issue by fire** [godotengine/godot#68804]
### Godot version

https://github.com/godotengine/godot/commit/7d9923b2e0b970602c3c6c17b94fae5badf60764

### System information

Windows 11, Nvidia 3000, firefox

### Issue description

Various 3d gizmo odd things with grouping and snapping.

### Steps to reproduce

https://user-images.githubusercontent.com/32321/202546898-7e93949d-638c-4d25-8a8e-dab422c860b5.mp4

https://user-images.githubusercontent.com/32321/202546926-c3b7f688-3dfc-4cc4-9c2c-2271ea2d5a72.mp4

Need to spend some time writing the steps from the video.

**Comment by TokageItLab** [comment]
I discuss with @fire and confirmed that this is not a bug.

This is a change made in #53684. It makes multiple-local-position and multiple-local-scale follow the behavior of the original multiple-local-rotation to make it consistent. This is the same behavior as Blender's multiple-local-individual-origins.

If this is an issue, then it could be a documentation issue.

**Comment by fire** [comment]
This is a documentation issue, but the original issue is resolved.
