### ISSUE TITLE
Thread silently fails on Parse Error

### ISSUE THREAD

**Issue by pseidemann** [godotengine/godot#68811]
### Godot version

v3.5.1.stable.official [6fed1ffa3]

### System information

macOS 12.6.1 (21G217)

### Issue description

when a thread function runs via Thread.new() + start(), an error like "Parse Error" will block the thread and give no error message whatsoever.

one way to trigger this behavior is via giving callv() not an array:
`self.callv("some_method", 42)`
(`42` should be `[42]`)

when this code runs in the main thread, an error message is displayed. when this code runs inside another thread, the thread will block and no error message is given, leaving the user in the unknown why a thread is blocking.

I suspect this might happen with other errors as well, but I'm not sure what class of errors exist which should be tested.

### Steps to reproduce

run `self.callv("some_method", 42)` in a thread other than the main thread

### Minimal reproduction project

`self.callv("some_method", 42)`

**Comment by timothyqiu** [comment]
Probably the same as #18330

**Comment by akien-mga** [comment]
Indeed, consolidating this in #18330.
