### ISSUE TITLE
Godot 4.0 beta 5 breaks exported node references from C#

### ISSUE THREAD

**Issue by simon-peregrine** [godotengine/godot#68840]
### Godot version

4.0.beta5.mono

### System information

Windows 11

### Issue description

I've been using C# in Godot 4.0 and exporting Node references directly to the inspector as opposed to using untyped NodePaths and the associated boilerplate (despite the latest documentation [saying](https://docs.godotengine.org/en/latest/tutorials/scripting/c_sharp/c_sharp_exports.html#nodes) that this isn't supported, [this proposal](https://github.com/godotengine/godot-proposals/issues/1048) and [subsequent C# implementation](https://github.com/godotengine/godot/pull/62789) indicate otherwise).

Until beta5 this worked very well:

![Correct](https://user-images.githubusercontent.com/21371262/202759287-80b8b9cd-5aaf-40ec-a83e-de1f754cab1c.png)

Upon loading my project in beta5, I found that all of the node references in my project have been broken and the node chooser inspector widget replaced by resource chooser widgets:

![Incorrect](https://user-images.githubusercontent.com/21371262/202759485-c06792d1-2415-4bfc-943f-7be73c61d09d.png)

This was a destructive change to my project and required a full Git revert, as the references had been completely removed from the scene files and remained broken even when reopening in beta4. This seems to only affect C#, as I made a simple test project with both languages and the equivalent Node reference was retained when exported from GDscript.

### Steps to reproduce

Using Godot 4.0 beta4 or earlier, create the following C# script:
```csharp
using Godot;
using System;

public partial class Referencer : Node
{
    [Export]
    public Node Referencee { get; set; }
}
```

Assign it to a node in the scene and assign the Referencee to another node in the scene. Then open the same project in beta5 and observe that the reference has been broken and the inspector no longer shows the node chooser, but rather the resource chooser.

### Minimal reproduction project

[NodeReferenceIssue.zip](https://github.com/godotengine/godot/files/10043280/NodeReferenceIssue.zip)

Open the project in beta4 to see the intended behaviour, then open it in beta5 to see the incorrect behaviour.

**Comment by akien-mga** [comment]
CC @godotengine/dotnet

**Comment by raulsntos** [comment]
Looks like the property is now being exported as a Resource instead of a Node, probably due to changes in the hints that weren't synchronized with .NET's source generators so we're now generating the wrong property hints.

**Comment by Kelin2025** [comment]
The same thing happens with gdscript, updated to beta6 and all nodes that export `NodePath` got broken

**Comment by Zireael07** [comment]
cc @vnen

**Comment by akien-mga** [comment]
Please open a new bug report, this was a C# specific bug and was fixed.
