### ISSUE TITLE
Creating a new Editor Features profile disables one or more default docks

### ISSUE THREAD

**Issue by souplamp** [godotengine/godot#68844]
### Godot version

4.0.beta5

### System information

Windows 10

### Issue description

Creating a new Editor Features profile will, seemingly randomly, disable Docks by default. The Docks that are disabled on creating a new profile can change each time a new profile is created.

![random disabled](https://user-images.githubusercontent.com/89402588/202771823-1b94cb35-c309-4ec4-948d-b3e462de2335.gif)
Ex. creating an Editor Features profile typically disables the Node Dock, but it can also disable the 3D Editor at random.

![example of disabled script](https://user-images.githubusercontent.com/89402588/202772226-ceb28b9a-d717-4da8-b691-4e65da851132.png)
Ex. creating a new profile disabled only the Script Editor, so the issue is not only linked to the Node Dock and/or 3D Editor.

At time of writing, it is unknown if this affects the "Nodes and Classes" category; it is only shown to affect "Main Features" in testing.

### Steps to reproduce

1. Editor -> Manage Editor Features
2. Create a new profile (with any name)
3. One or more Docks will sometimes get disabled; other times, all are enabled as expected.

It is difficult to reproduce this issue reliably, as it randomly disables certain Docks, or will sometimes not disable any at all.

### Minimal reproduction project

N/A

**Comment by souplamp** [comment]
Note: in testing, this also does not seem related to the profile name. I created identical profile names as shown in the two examples, and everything in "Main Features" was left enabled as expected.

**Comment by Calinou** [comment]
This is likely the result of uninitialized data, which manifests itself as "random" behavior (previous values in memory are used instead).

**Comment by kitbdev** [comment]
- fixed by https://github.com/godotengine/godot/pull/66194
