### ISSUE TITLE
Docks do not clear from editor layout when disabled in Editor Features

### ISSUE THREAD

**Issue by souplamp** [godotengine/godot#68843]
### Godot version

4.0.beta5

### System information

Windows 10

### Issue description

Editor Docks do not fully disable in editor when disabled in Editor Features.

This is more obvious when the user defines a custom Editor Layout. 
For example, when all docks are placed on the right-side of the editor, disabling the History Dock (see below) and reloading the project leaves a gap where the History Dock used to be.

![editor features doesn't fully disable history dock](https://user-images.githubusercontent.com/89402588/202762949-c62c3235-4c40-4b75-adb4-41351f212258.gif)
Ex. of the gap left in the editor; this appears to only happen with a custom Editor Layout.

![phantom history dock](https://user-images.githubusercontent.com/89402588/202763599-015859b8-26e8-40be-81e3-ef6b57796388.png)
With a custom Editor Layout (eg. docks on right-side), disabling the History Dock in the Editor Features and reloading the project leads to this graphical issue. If the non-custom Editor Layout is used, the History Dock will appear as normal.
In either case, a disabled History Dock still appears in the Editor Layout.

This issue appears to affect all Dock options in the Editor Features window.

### Steps to reproduce

Optional: Change the layout of the Editor such that all Docks are in some portion of the right-side of the screen (the original issue will occur regardless; this just introduces more related graphical bugs that might make testing easier).

1. Create an Editor Features profile.
2. Disable an Editor Dock.
3. Project -> Reload Current Project.
4. The disabled dock will be present again.

If the optional step is followed, the disabled dock will appear again with some out of place elements, and enabling and re-disabling it causes a gap to be left in its place.

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
CC @KoBeWi

**Comment by KoBeWi** [comment]
Seems like all docks have this problem, not only History. (the code that disables them is the same so it makes sense...)

**Comment by kitbdev** [comment]
This should be fixed as of https://github.com/godotengine/godot/pull/84122
