### ISSUE TITLE
For AMD Cpu, Nvidia graphics card laptop, can't set vsync in godot

### ISSUE THREAD

**Issue by Redwarx008** [godotengine/godot#68845]
### Godot version

4.0B5

### System information

win10, vulkan, AMD Radeon, Nvidia gtx 1660ti

### Issue description

As the question, but I can set it up in the NVIDIA Control Panel and it works
edit:Enabling vsync in the project settings or setting it in the code via `window_set_vsync_mode ` is not valid. 
When I disable the Nvidia graphics card only using AMD Radeon is effective.

### Steps to reproduce

-

### Minimal reproduction project

-

**Comment by clayjohn** [comment]
Could you please provide more detail? For example, how are you turning Vsync on through Godot? What metrics are you looking at to verify that VSync is enabled?

**Comment by Redwarx008** [comment]
> The description has been updated and the frame rate is viewed by `get_frames_per_second` in the code.
。。

**Comment by Redwarx008** [comment]
> Could you please provide more detail? For example, how are you turning Vsync on through Godot? What metrics are you looking at to verify that VSync is enabled?

The description has been updated and the frame rate is viewed by get_frames_per_second in the code.

**Comment by clayjohn** [comment]
In the NVidia graphics panel, have you set VSync to something like "use application settings"? Or is it set to "disabled"?

**Comment by Redwarx008** [comment]
> In the NVidia graphics panel, have you set VSync to something like "use application settings"? Or is it set to "disabled"?

It works, thank you！:D
