### ISSUE TITLE
Can't type in Project Settings with onscreen keyboard

### ISSUE THREAD

**Issue by JeroenNieuwenhuis** [godotengine/godot#68857]
### Godot version

3.3.2 stable

### System information

Windows 10

### Issue description

The Project Settings window closes when typing with onscreen keyboard.

### Steps to reproduce

Open Windows on screen keyboard (%windir%\system32\osk.exe)
Open a godot project and a gd script
Open the project settings
Position the OSK so it's not over the project settings
Use the OSK to type in any field
The project settings close

### Minimal reproduction project

N/A

**Comment by DmitriySalnikov** [comment]
> 3.3.2 stable

hmm, maybe I didn't understand something, but at the moment the current version is 3.5.1

Windows 11, v3.5.1.stable.official [6fed1ffa3]
![Godot_v3 5 1-stable_win64_iwW8TU4FJW](https://user-images.githubusercontent.com/7782218/202827102-c5f379b0-fbbe-435f-b21a-2b1fb2762d9a.gif)

however, I don't have this bug even in 3.3.2 and 3.3.4
![Godot_v3 3 2-stable_win64_aWBs2N1bLa](https://user-images.githubusercontent.com/7782218/202827028-cb6b43f7-ae91-4f12-8723-21e2e863374e.gif)

**Comment by JeroenNieuwenhuis** [comment]
I just tried it and can't reproduce it anymore.
