### ISSUE TITLE
Unsaved duplicate scripts seemingly get randomly created

### ISSUE THREAD

**Issue by SaracenOne** [godotengine/godot#68867]
### Godot version

84c404f6bcce9ba112118d77afd6bd70a92774d1

### System information

Windows 10, Vulkan, Intel® Core™ i7-8700K, Nvidia GTX 1080 (471.11)

### Issue description

When working with GDScript files, sometimes they will randomly spawn unsaved broken duplicates upon saving:

![godot windows editor dev x86_64_PJPWf1ma5u](https://user-images.githubusercontent.com/12756047/202829268-0ef7f254-c6b5-4223-9154-67ce42d7580b.png)

Regression caused since merging of #67714

### Steps to reproduce

Unknown as of yet, but occurs frequently and may be triggered by having errors in your scripts

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
CC @adamscott

**Comment by adamscott** [comment]
Maybe fixed by #68872. Can you see if it happens still?

**Comment by dalexeev** [comment]
> Regression caused since merging of #67714

I noticed the bug before merging #67714, for example when renaming/moving a script.

**Comment by dmaz** [comment]
I see this sometime when I click a script icon from an instanced scene in the Scene tree

**Comment by SaracenOne** [comment]
From my subsequent tests after the updates, I haven't noticed the particular initial issue anymore. It sounds like this problem may be deeper from other people's comments, but I'm going to close this for now. I'll reopen or create a new issue if I encounter anything similar
