### ISSUE TITLE
CameraAttributes not available in 2D

### ISSUE THREAD

**Issue by h0lley** [godotengine/godot#68864]
### Godot version

v4.0.beta.custom_build [84c404f6b]

### System information

Ubuntu, Vulkan, Nvidia

### Issue description

In Godot 3, effects such as DOF near blur and auto exposure have been very useful in 2D. Since these effects have now been moved to CameraAttributes, they no longer apply to 2D.

Examples:

I've been using auto exposure to get a better handle on calibrating glow. Without it, it was difficult not to get extremely exaggerated glow in situations such as where your game cycles through day and night.

![overexposureflow](https://user-images.githubusercontent.com/23386940/202822872-3eac9d3f-5342-4a91-9b6b-bba103827f03.png)

I've been using DOF near blur to do things like blurring the game world during on the pause screen:

![dofnearblur](https://user-images.githubusercontent.com/23386940/202822937-20f37118-2852-44c3-9633-3c26daaeade8.png)

while this should be achievable with a shader, too, it was really nice to be able to do this with a simple WorldEnvironment setting.

Related: https://github.com/godotengine/godot-proposals/issues/4564

### Steps to reproduce

1. Add a WorldEnvironment node to your 2D scene
2. Attempt to apply any effect to your scene using CameraAttributes
3. Sad

### Minimal reproduction project

please let me know if desirable

**Comment by h0lley** [comment]
I toyed some more around with environment settings and mostly achieved what I had in 3.x with 4.0.
Got an almost identical blur effect with `glow_blend_mode` set to `RenderingServer.ENV_GLOW_BLEND_MODE_REPLACE`
and the exposure issue is mitigated by adjusting `tonemap_exposure`.

It still looks quite different from how it did in 3.x, but I think I can work with it.

**Comment by clayjohn** [comment]
You just need to add a Camera3D to your scene for DoF and auto-exposure to work in a 2D scene (and set background to "Canvas" of course). I'm really surprised that they worked without a Camera3D in 3.x. 

Also, as a note, you really should not be using DoF and auto-exposure in 3D. You are sacrificing a lot of performance for effects that would look better and run way faster if done natively in 2D.

**Comment by zaevi** [comment]
This should be documented, at least marked in official `HDR for 2D` demo.

**Comment by clayjohn** [comment]
@zaevi There is already a draft PR! https://github.com/godotengine/godot-docs/pull/6273 It should be finished and merged soon

**Comment by h0lley** [comment]
Closing, as all these effects are achievable in other (better) ways in 4.x as explained by clayjohn.

**Comment by KerekesDavid** [comment]
Sorry for posting on a closed issue, but I'm in the same situation where I want to use auto-exposure in my 2D game. You closed this issue saying the new workaround is better, but didn't clayjohn explicitly warn against using these effects with the 3D camera?

> Also, as a note, you really should not be using DoF and auto-exposure in 3D. You are sacrificing a lot of performance for effects that would look better and run way faster if done natively in 2D.

Wouldn't it be reasonable for the camera attributes to work natively in the 2D camera as well? It might not be a regression _per se_, since it sounds like these worked by accident on the 2D camera before, but it's still a regression from a usability standpoint.

**Comment by h0lley** [comment]
@KerekesDavid I am not using Camera3D.

I am using `WolrdEnvironment` in canvas mode - nothing plugged into `camera_attributes` - and am achieved the desired effect in my case with the `tonemap_exposure` property.

for the blur, I am using `glow_blend_mode` set to `Environment.GLOW_BLEND_MODE_REPLACE`.

**Comment by KerekesDavid** [comment]
Thanks for the reply, I somehow missed your other comment above! I would have never thought about glow bend mode. How do you determine the correct exposure to set in the tonemap? I guess I'd have to do the screen histogram calculation myself somewhere.

**Comment by h0lley** [comment]
Oh I can't help you there since in my case I don't need it top be dynamic. I've just toyed around with the environment settings until I got something I am satisfied with (for tonemap, it's Filmic with exposure of 0.6 in my case).
