### ISSUE TITLE
Broken scripts appear blank in the editor after saving and restart

### ISSUE THREAD

**Issue by tinmanjuggernaut** [godotengine/godot#68862]
### Godot version

Godot 4 Beta 5 & master 895428c8058ce97abb02a6a3500e463f72a4f9c9

### System information

Windows 11/64, RTX 3070, Vulkan

### Issue description

Since beta 5, broken scripts cannot be opened _at all_. The editor window is blank. This file is not empty. The contents are shown further below.

![image](https://user-images.githubusercontent.com/632766/202821677-0c4ba73b-de1f-4c80-ad2a-3b0b9c247e52.png)

I took the default script, and removed `pass` from ready. Then saved the file and got this console error:
`SCRIPT ERROR: Parse Error: Mixed use of tabs and spaces for indentation.`

Then I restarted Godot and now this script cannot be opened in the editor.

```
extends Node3D


# Called when the node enters the scene tree for the first time.
func _ready():
	 # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	pass
```

Upon reopening, there are no further error messages on the console from this broken script. Of course all of my other scripts that reference this one complain that the class is missing.

I've had this happen on multiple files. I am able to edit the file externally, grab the contents and paste it in to Godot and resave the file once the syntax checker is satisfied with it.

**Caused by** bce6f1792ebce5de31700e72f57830e5d87b419a
**GDScript compiler subclass bugfixes**
@rune-scape

**Comment by Calinou** [comment]
If you can [compile the engine from source](https://docs.godotengine.org/en/stable/development/compiling/index.html), you could look into [bisecting the regression](https://docs.godotengine.org/en/stable/community/contributing/bisecting_regressions.html) to greatly speed up troubleshooting.

- 4.0.beta4's commit hash (`good`) is `e6751549cf7247965d1744b8c464f5e901006f21`.
- 4.0.beta5's commit hash (`bad`) is `89a33d28f00fec579184fb7193790d40aa09b45b`.

**Comment by dalexeev** [comment]
I assume the problem is that the editor does not use the actual contents of the file on disk, but `GDScript.source_code`, which is maybe empty for an non-parsed/non-resolved script. In addition, I have noticed that sometimes the contents of a file on disk and in the Godot editor may differ, but the dialog about this may not appear.

**Comment by tinmanjuggernaut** [comment]
> git bisect

Wow I didn't know this existed! Cool.

And the winner is.... bce6f1792ebce5de31700e72f57830e5d87b419a

@rune-scape
