### ISSUE TITLE
Geometry below Viewport using a custom world is not visible in editor

### ISSUE THREAD

**Issue by fractilegames** [godotengine/godot#68883]
### Godot version

3.5.1

### System information

Xubuntu 22.04 x86_64, Intel UHD 620, GLES3

### Issue description

Any geometry inside a Viewport in scene tree disappears in editor when setting the viewport to use a custom world. Everything works as intended run-time and shows up in the viewport in editor too.

![image](https://user-images.githubusercontent.com/2310335/202847142-85c5ecf1-cd1f-4c45-9b78-7de4fd7df903.png)

### Steps to reproduce

Set a Viewport in scene tree to use a custom world.

### Minimal reproduction project

[OwnWorldViewportTest.zip](https://github.com/godotengine/godot/files/10046780/OwnWorldViewportTest.zip)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/57334 (possible duplicate?).

**Comment by fractilegames** [comment]
Yes, that's a duplicate. I didn't find the other issue, sorry.

So this is more like a missing feature that can be worked around when you know it.

**Comment by Calinou** [comment]
Duplicate of #57334.
