### ISSUE TITLE
"Invalid break insert count" error when using a ligature font and a symbol that requires a hyphen.

### ISSUE THREAD

**Issue by gamedevbram** [godotengine/godot#68888]
### Godot version

v4.0.beta5.official [89a33d28f]

### System information

Windows 10, NVIDIA Geforce GTX 1660 SUPER

### Issue description

I'm using the FontAwesome ligature font in my project. Ever since Godot 4 Beta 4 I started getting the following error: "Invalid break insert count!"
This error happens when I load a scene that has the following:
- A Label using the FontAwesome font.
- That Label has some text that is transformed into an icon with the ligatures
- This text includes a hyphen

For example a label with the text "eye-dropper".
The error only occurs when the text including the hyphen gets transformed. For example "eye-droppe" would not cause an error, as this is not a ligature in the font.

When running the game, I also get the following error in the debugger:
E 0:00:01:0458   _shaped_text_update_breaks: Invalid break insert count!
  <C++ Error>    Condition "sd_shift != sd->break_inserts" is true. Returning: false
  <C++ Source>   modules/text_server_adv/text_server_adv.cpp:4753 @ _shaped_text_update_breaks()

This error was not present in Godot 4 Beta 3. However in both Godot 4 Beta 4 and Beta 5 I get the error.

### Steps to reproduce

1. Create new project.
2. Add a font using ligatures.
3. Create a scene with a Label.
4. Use the font in that label.
5. Type some text that includes a hyphen and will get transformed using ligatures.
6. Observe the error in the output.

### Minimal reproduction project

[FontBugMinimalProject.zip](https://github.com/godotengine/godot/files/10047366/FontBugMinimalProject.zip)

**Comment by Calinou** [comment]
If you can [compile the engine from source](https://docs.godotengine.org/en/stable/development/compiling/index.html), you could look into [bisecting the regression](https://docs.godotengine.org/en/stable/community/contributing/bisecting_regressions.html) to greatly speed up troubleshooting.

- 4.0.beta3's commit hash (`good`) is `01ae26d31befb6679ecd92cd3c73aa5a76162e95`.
- 4.0.beta4's commit hash (`bad`) is `e6751549cf7247965d1744b8c464f5e901006f21`.

**Comment by souplamp** [comment]
Bisecting now:
- 4.0beta3 (?) commit hash (`good`) is `f0b7ff324cc246a59e6adbcb6d50f2443990e4a9`.

**Comment by souplamp** [comment]
Bisect: `f0b7ff324cc246a59e6adbcb6d50f2443990e4a9`, or #67821
