### ISSUE TITLE
Improve error messages for incorrect collision exception setups

### ISSUE THREAD

**Issue by Mikeysax** [godotengine/godot#68889]
### Godot version

4.0beta4

### System information

PopOS 22.04, 6.0.3-76060003-generic kernel, Ryzen 6800h, Radeon 6700m, amdgpu, Vulkan

### Issue description

I'm seeing the following:

```
E 0:00:00:0324   add_collision_exception_with: Collision exception only works between two CollisionObject3Ds.
  <C++ Error>    Condition "!collision_object" is true.
  <C++ Source>   scene/3d/soft_body_3d.cpp:610 @ add_collision_exception_with()
```

When looking for CollisionObject3D, the only thing that shows is CollisionShape3D

![image](https://user-images.githubusercontent.com/15805689/202860290-0855642b-2fe3-432f-b46d-9f48d6589052.png)

![image](https://user-images.githubusercontent.com/15805689/202860309-7099741b-f604-4ada-b13d-1bd90c3b6365.png)

![image](https://user-images.githubusercontent.com/15805689/202860497-c96a6f7f-ce08-495d-93b1-b6e2cf86fce3.png)

Is this just a miss and it's checking for a node type that doesn't exist? Is this the parent node type? Am I misunderstanding what's going on here?

### Steps to reproduce

Add a CollisionShape3D to the parent ignore param of a SoftBody3D node

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
CollisionObject3D is an abstract node that's inherited by Area3D and PhysicsBody3D. You cannot instance it directly.
