### ISSUE TITLE
History dock take the first place by default in the control tab bar

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#68882]
### Godot version

beta 5

### System information

Windows 11

### Issue description

I think it's incorrect and distracting, because inspector is more important and should appear first:

![image](https://user-images.githubusercontent.com/3036176/202844458-2c3f39b4-0f39-4124-b1e5-d4d2b4c8963d.png)

It seems to be intended to place after the Node tab in the code, but somehow appears first:

https://github.com/godotengine/godot/blob/895428c8058ce97abb02a6a3500e463f72a4f9c9/editor/editor_node.cpp#L7006-L7016

### Steps to reproduce

Run the editor

### Minimal reproduction project

No need

**Comment by Sauermann** [comment]
Can confirm this behavior on linuxbsd.

**Comment by KoBeWi** [comment]
This only happens when you open an existing project that has a layout saved. On new projects, all docks are on correct position.

This is a temporary issue that will fix itself once people transition to the new version.

**Comment by Chaosus** [comment]
Ah, true.

**Comment by Yagich** [comment]
> This only happens when you open an existing project that has a layout saved. On new projects, all docks are on correct position.
> 
> This is a temporary issue that will fix itself once people transition to the new version.

That doesn't appear to be the case. I started a new project, and the History dock still showed up first.

**Comment by KoBeWi** [comment]
Can't reproduce. History dock appears correctly for me.

**Comment by Yagich** [comment]
I forgot I use a different dock layout than the default one. However, it opening by default every time a new project is opened with custom layouts is still annoying.
![image](https://user-images.githubusercontent.com/24468819/203429997-32f2e389-2001-4579-8895-73fec0d25bd1.png)

**Comment by dalexeev** [comment]
> I forgot I use a different dock layout than the default one.

I assume you need to re-save the layout.

**Comment by Sauermann** [comment]
> This is a temporary issue that will fix itself once people transition to the new version.

While this is a temporary issue, we will have to deal with this for a long time, because all previous MRPs will show the History-dock first. Is there a way to make it, so that unknown new docks are shown last?

**Comment by Yagich** [comment]
> I assume you need to re-save the layout.

I did resave it, and making a new project still opens the History dock first. 😕

**Comment by KoBeWi** [comment]
#69072 might fix it.

**Comment by Sauermann** [comment]
@Yagich I don't have any experience with different layouts, so I didn't test #69147 with your use-case. It would be great, if you could give feedback, if that PR solves your problem.

**Comment by Yagich** [comment]
That seems to have fixed it, thanks!
