### ISSUE TITLE
Improve clarity of "Return Value Discarded" GDScript warning

### ISSUE THREAD

**Issue by unfa** [godotengine/godot#68896]
### Godot version

4.0 dev Beta 5

### System information

Arch Linux

### Issue description

I get a flood of this:
![image](https://user-images.githubusercontent.com/491704/202868607-bce0a366-8e27-4700-bef4-c58d9d50803e.png)

Despite having set this:
![image](https://user-images.githubusercontent.com/491704/202868625-4fe64e70-79c1-4955-8a42-cbdf60e018c9.png)

### Steps to reproduce

1. Use a function that returns a value that you discard.
2. Run the project and see a warning (default)
3. Go to Project > Settings (Advanced Settings must be enabled) > Debug > GDScript > Unused Variable and change the value to Ignore
4. Rerun your project and see that it had no effect
5. Change it to Error
6. Try again and see that this has an effect

### Minimal reproduction project

[Beta 5 Warnings.zip](https://github.com/godotengine/godot/files/10047841/Beta.5.Warnings.zip)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/56592.

**Comment by souplamp** [comment]
There should definitely be a change to clarify the difference.

Two ideas:
1. Change Debug: Return Value Discarded -> Unused Return Value
2. Change the Error: "The function ... returns a value, but the return value was discarded."

**Comment by unfa** [comment]
Yes. I have searched the list of options fro "Unused" keyword but found nothing that seemed matching.
Also the error states "xyz returns a value but this value is never used" so I thought it's logical to seek fro "unused variable" in settings.

I think renaming for consistency would help here a lot.
