### ISSUE TITLE
Godot displaying empty script when script exists

### ISSUE THREAD

**Issue by calvinjanes** [godotengine/godot#68890]
### Godot version

Godot_v4.0-beta5_win64

### System information

windows 10

### Issue description

I've got a small project where I saved a gd script and later when I reopened the script (after closing and reopening godot editor) the editor pane was empty.  So I checked the actual file in a different text editor and the file still has contents in it.  There was a warning in the godot when I opened the file:

[Ignore]Line 1 (EMPTY_FILE):Empty script file.

### Steps to reproduce

I don't know how to reproduce other than with this sample project.  If I create a minimal project with the same file copied to a new location the issue persists.

1. unzip my sample project folder
2. create a godot project targetting the folder
3. open the file  /gd/Player.gd

### Minimal reproduction project

[blankgd.zip](https://github.com/godotengine/godot/files/10047422/blankgd.zip)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/68795.
