### ISSUE TITLE
Curve3D::sample_baked_up_vector() returns value perpendicular to its previous value after merge

### ISSUE THREAD

**Issue by Ademan** [godotengine/godot#68893]
### Godot version

8ab3e73a799bbfa862403747a5de9fc96ba83149

### System information

Ubuntu 22.04

### Issue description

Prior to 8ab3e73a799bbfa862403747a5de9fc96ba83149, `Curve3D::sample_baked_up_vector()` returned a somewhat plausible up vector for some curves, however since 8ab3e73a799bbfa862403747a5de9fc96ba83149 it returns a vector perpendicular to the old value. Original PR #64212

The simple attached project displays the angle between the first curve point up vector, and the global up vector

8ab3e73a799bbfa862403747a5de9fc96ba83149

![2022-11-19-102053_1916x1033_scrot](https://user-images.githubusercontent.com/18740/202861009-b4a0f887-f355-4bc6-9d04-2b9690a524fa.png)

8ab3e73a799bbfa862403747a5de9fc96ba83149^

![2022-11-19-103036_1916x1033_scrot](https://user-images.githubusercontent.com/18740/202861365-66b2968f-c756-44a9-b195-10ea60153a90.png)

Additional screenshots here: https://github.com/godotengine/godot/pull/64212#issuecomment-1320811390 (more difficult to reproduce because it requires rebasing another change)

### Steps to reproduce

1. Create a Node3D
2. Assign it a Curve3D
3. call `Curve3D::sample_baked_up_vector()`
4. Observe the value with Godot after 8ab3e73a799bbfa862403747a5de9fc96ba83149
5. Observe the value with Godot 8ab3e73a799bbfa862403747a5de9fc96ba83149^

Run the attached project to accomplish the same

### Minimal reproduction project

Run the example scene in this project to show this behavior [Curve3D Up Vector Test.zip](https://github.com/godotengine/godot/files/10047493/Curve3D.Up.Vector.Test.zip)

**Comment by Calinou** [comment]
cc @xiongyaohua

**Comment by Ademan** [comment]
I thought I'd also note in the original PR there was quite a bit of discussion about whether or not the up vector is naturally a property of Curve3D or if it belongs elsewhere. I'm not sure any conclusions were reached but it obviously has a bearing on whether `Curve3D::sample_baked_up_vector()` should exist at all.

The `sample_baked_with_rotation()` method which @xiongyaohua added in that PR is more useful than `sample_baked_up_vector()` anyway, every use of `sample_baked_up_vector()` that I can think of is ultimately trying to establish a basis for some transform anyway. Perhaps the real fix is to simply drop the `sample_baked_up_vector()` method entirely.

**Comment by xiongyaohua** [comment]
Sorry for the late reply, as I am occupied by other things recently. I will investigate.
