### ISSUE TITLE
Can't access node `Signal`s in lambda

### ISSUE THREAD

**Issue by dkaste** [godotengine/godot#68907]
### Godot version

v4.0.beta5.official [89a33d28f]

### System information

Fedora 37

### Issue description

Lambda functions cannot access the `Signal` objects declared in the current object script.

It is possible that this is intended behavior but it seems surprising to me, so I am assuming it is a bug.

### Steps to reproduce

```gdscript
extends Control

signal my_signal

func _ready():
	my_signal.connect(func(): print("Hello!"))
	
	# Works
	var test1 = func(): emit_signal("my_signal")
	test1.call()
	
	# Doesn't work
	var test2 = func(): my_signal.emit()
	test2.call()
```

Prints "Hello!" once and crashes on `my_signal.emit()` with "Invalid get index 'my_signal' (on base: 'Nil')."

### Minimal reproduction project

N/A

**Comment by MrBlockers** [comment]
I ran into this also when accessing any members of the object from within a lambda in general. A workaround I've been using is writing it out in full with `self`, e.g. `self.my_signal.emit`. I feel like lambdas should inherit/close over the class scope though.
