### ISSUE TITLE
" core/image.cpp:2063 - Loaded resource as image file, this will not work on export:"

### ISSUE THREAD

**Issue by zaddok** [godotengine/godot#68915]
### Godot version

3.5.1

### System information

macOS 13.0.1, iOS 16.1

### Issue description

When exporting a project to iOS with the _use storyboard_ splash screen option is ticked, the following error appears in Godot as a yellow message:

" core/image.cpp:2063 - Loaded resource as image file, this will not work on export:"

If we untick the storyboard option, the export does not include this message, but instead Xcode warns that you are supposed to use a storyboard.

### Steps to reproduce

It is not clear to me if this is a warning or an error, and it it should be fixed. Perhaps the error message should be clearer. I did not do anything but go into the export settings panel and set the splash screens.  But I do know after the splash screen the app does go black/blank (the app still runs though, you just cant see it).

### Minimal reproduction project

Just ass a storyboard splash screen.  The same error occurs in my current project, and a separate test project I created to try to diagnose some problems.

**Comment by zaddok** [comment]
Here is the error in context. Is it meant to be ignored? Perhaps a note could go into the logs to say it can be ignored, or alternatively how to fix it?

```
READ: libgodot.iphone.release.xcframework/
READ: libgodot.iphone.release.xcframework/ios-arm64_x86_64-simulator/
READ: libgodot.iphone.release.xcframework/ios-arm64_x86_64-simulator/empty
READ: libgodot.iphone.release.xcframework/ios-arm64_x86_64-simulator/libgodot.a
READ: libgodot.iphone.release.xcframework/Info.plist
READ: libgodot.iphone.release.xcframework/ios-arm64/
READ: libgodot.iphone.release.xcframework/ios-arm64/empty
READ: libgodot.iphone.release.xcframework/ios-arm64/libgodot.a
Using Launch Storyboard
 core/image.cpp:2063 - Loaded resource as image file, this will not work on export: 'res://splash-1536x2048.png'. Instead, import the image file as an Image resource and load it normally as a resource.
Exporting additional assets
xcodebuild (.xcarchive):
Command line invocation:
```

**Comment by akien-mga** [comment]
This is a warning that you can ignore, it's emitted by the export code which doesn't seem to use the proper API to load the source image and convert it to/export it in the required formats for the storyboard. CC @bruvzg

**Comment by bruvzg** [comment]
Same for icons and other platforms, it should be possible to suppress it by using `ImageLoader` directly, instead of `load`.
