### ISSUE TITLE
Godot 4 StringName not found in Array

### ISSUE THREAD

**Issue by mrimvo** [godotengine/godot#68918]
### Godot version

4.0 Beta 4

### System information

Ubuntu 20.04

### Issue description

**StringName** objects won't be found **in** **Arrays** (but it _does_ work for Dictionaries):

	if StringName("test") == "test":
		print("works")

	if StringName("test") == in {test=true}:
		print("works")

	# BUG
	if StringName("test") in ["test"]:
		print("doesn't work")

	# BUG
	if node.name in ["A", "B"]:
		print("never printed, even is node is named A or B")

### Steps to reproduce

Write and run the simple script I presented above.

### Minimal reproduction project

See above.

**Comment by souplamp** [comment]
Related PR: #68747

**Comment by Mickeon** [comment]
Unfortunately this is as much of a bug as an `int` and a `float` in an Array being two completely different **Variant** types. Same goes for **Vector2** and **Vector2i**. If finding Variants in Arrays were to be loose, it'd be much, much slower. 

One solution would be to at least make it opt-in. Maybe an optional parameter in `Array.has()`?

~Don't worry I hate StringNames' practical implementation too~
