### ISSUE TITLE
[4.0] GDScript inconsistent error highlighting within scoped context

### ISSUE THREAD

**Issue by ClarkThyLord** [godotengine/godot#68913]
### Godot version

Godot 4.0 beta 5

### System information

Windows 10

### Issue description

GDScript has inconsistent error highlighting with scoped context.

As seen below, we're given a variable naming error within the scope of the `_ready()` function, but it isn't being highlighted:
![image](https://user-images.githubusercontent.com/17155529/202891260-ec19a1ce-ae3f-4888-aca4-943d50e9dc6e.png)
Seen in the error console we see the error is being marked on line 7, which isn't correct since the error is at line 5; nor is it possible since the script only consist of 6 lines.

As seen below, a variable naming error at the class level is being highlighted, but still not at the scoped function:
![image](https://user-images.githubusercontent.com/17155529/202891732-11eba76d-0283-4e08-877d-6716d035b354.png)
Again, seen in the error console we see a second error is being marked on line 10, which isn't correct since the error is at line 9; nor is it possible since the script only consist of 9 lines.

### Steps to reproduce

1. Open example project
2. Open `example_a.gd`
3. Error marked at line 7, no highlighting.
4. Open `example_b.gd`
5. Second error marked at line 10, no highlighting.

### Minimal reproduction project

[example.zip](https://github.com/godotengine/godot/files/10049109/example.zip)

**Comment by Ayush-singla27** [comment]
I would like to work on this issue. I have reproduced the issue but m unable to understand where to start looking. A pointer to where i should begin would be much appreciated.

**Comment by Calinou** [comment]
> I would like to work on this issue. I have reproduced the issue but m unable to understand where to start looking. A pointer to where i should begin would be much appreciated.

Searching for the error string in the codebase usually gives you a good idea of where to look at first: https://github.com/godotengine/godot/blob/895428c8058ce97abb02a6a3500e463f72a4f9c9/modules/gdscript/gdscript_parser.cpp#L805-L807

**Comment by Ayush-singla27** [comment]
![2](https://user-images.githubusercontent.com/77923967/203420872-596e7cd9-c259-4aa5-b2f7-f234de9afe68.png)
i tried working on this issue. i think the error should be at ( 7 , 5 ) instead of ( 6 , 5) .Am I correct? or is this fine?

**Comment by ClarkThyLord** [comment]
Closing issue, as no longer seen in latest Godot 4.0 beta 17
