### ISSUE TITLE
Crash in editor when using PlaneMesh

### ISSUE THREAD

**Issue by ueshita** [godotengine/godot#68923]
### Godot version

4.0.beta5

### System information

Windows 11

### Issue description

The editor crashes when the following settings are made in PlaneMesh.
- Subdivide Width: 254
- Subdivide Depth: 254

Perhaps, it seems to crash when the number of vertices in the mesh is just 65536.

### Steps to reproduce

1. Open reproduction project
2. Select "MeshInstance3D" node
3. In inspector, extend "Mesh" property
4. Set "Subdivide Depth" to 254

### Minimal reproduction project

[PlaneMeshBug.zip](https://github.com/godotengine/godot/files/10050044/PlaneMeshBug.zip)

**Comment by Redwarx008** [comment]
I have encountered this bug before. When I generate a mesh with 255*255 vertices(Same as subdividing into 254 * 254), the editor crashes, but as long as it is not this value, this will not happen

**Comment by clayjohn** [comment]
I can't reproduce this on my device. Windows 10, 16 GBRAM, Radeon dedicated GPU with 16 GBVRAM.

Could someone who can reproduce the issue please try running the engine from console, reproduce the crash, and then copy the backtrace here?

**Comment by Redwarx008** [comment]
> I can't reproduce this on my device. Windows 10, 16 GBRAM, Radeon dedicated GPU with 16 GBVRAM.
> 
> Could someone who can reproduce the issue please try running the engine from console, reproduce the crash, and then copy the backtrace here?

![catch](https://user-images.githubusercontent.com/50837890/202977259-9fcd5b4f-a670-4d90-8acc-594f63e695e5.PNG)

**Comment by ueshita** [comment]
> > I can't reproduce this on my device. Windows 10, 16 GBRAM, Radeon dedicated GPU with 16 GBVRAM.
> > Could someone who can reproduce the issue please try running the engine from console, reproduce the crash, and then copy the backtrace here?
> 
> ![catch](https://user-images.githubusercontent.com/50837890/202977259-9fcd5b4f-a670-4d90-8acc-594f63e695e5.PNG)

**Comment by BharatSahlot** [comment]
I was able to reproduce this on my machine and fix it by changing `<=` to `<` line 369 in mesh_storage.cpp

**Comment by clayjohn** [comment]
> I was able to reproduce this on my machine and fix it by changing `<=` to `<` line 369 in mesh_storage.cpp

Great find! That line determines whether we use 16 bit ints of 32 bit ints for the index array. That explains why the error message is reporting receiving an array that is 2 times too big. 

Feel free to open a PR with your fix!

**Comment by BharatSahlot** [comment]
Okay I will open a PR, but I don't understand why it didn't crash on your machine? This sort of error should make it crash for everyone.

**Comment by ueshita** [comment]
A different approach than above, but changing some parts of rendering_server.cpp improved the issue.
https://github.com/ueshita/godot/commit/454116716e7934f6bd80d7040a2c06a7c18d4c64
