### ISSUE TITLE
HTML5 export audio issue: "Cannot read property 'disconnect' of undefined"

### ISSUE THREAD

**Issue by radicaled** [godotengine/godot#6892]
**Operating system or device - Godot version:**

Ubuntu, Godot 2.1

**Issue description** (what happened, and what was expected):

I have a generic "explosion" scene that I add to the main scene to represent an explosion. The explosion scene has a `SamplePlayer` attached. I call a "boom" function on it, which starts a 2s timer and immediately plays a 1.5s sound effect. When the timer is triggered, it removes the scene afterward. This works fine in desktop exports and in the editor, but in the HTML5 export I occasionally see the following stacktrace.

Stacktrace:

```
index.js:1 Uncaught TypeError: Cannot read property 'disconnect' of undefined
  _as_voices.(anonymous function).onended @ index.js:1
```

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.
