### ISSUE TITLE
get_var returns null

### ISSUE THREAD

**Issue by ugothmeex** [godotengine/godot#68920]
### Godot version

v4.0.beta5.official [89a33d28f]

### System information

Win 11, UHD Graphics 730

### Issue description

was trying to do a simple save/load with godot4

### Steps to reproduce

![image](https://user-images.githubusercontent.com/68721236/202908306-574f3e5a-6bb0-4fa1-ad7c-a61f5a7ea865.png)

```
extends Node2D


#var A = "123123"
var A = {"ads":1,"qwe":"test2"}

func _ready():
	_save(A)

func _save(x):
	var file = FileAccess.open("user://save_game.txt", FileAccess.WRITE)
	file.store_var(x)
	print(x)
	print(_load())

func _load():
	var file = FileAccess.open("user://save_game.txt", FileAccess.READ)
	print("file",file)
	return file.get_var()
```

### Minimal reproduction project

n/a

**Comment by akien-mga** [comment]
You can't read back what you just wrote to a file right away - you either need to close the file (by letting the `file` handle go out of scope), or force flushing it by calling `file.flush()`.

So either of those:
```gdscript
func _ready():
	_save(A)
	# file contents get written to disk on close, i.e. when `_save`'s `file` handle goes out of scope
	print(_load())
```
or:
```gdscript
func _ready():
	_save(A)

func _save(x):
	var file = FileAccess.open("user://save_game.txt", FileAccess.WRITE)
	file.store_var(x)
	print(x)
	file.flush()
	print(_load())
```
