### ISSUE TITLE
OptionButton's minimum size does not update after changing `expand_icon`

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#68930]
### Godot version

4.0 98da707

### System information

Windows 10 x64

### Issue description

When you change `expand_icon` property in OptionButton, the minimum size does not update correctly until you reload the scene.
![godot_ABRUWQWiYA](https://user-images.githubusercontent.com/2223172/202924641-f9b4fc77-02b8-43b3-808e-6b76c707c86a.gif)
Most likely the cause is that OptionButton caches size and has a method called `_queue_refresh_cache()` that should be called when `expand_icon` is changed. But the method is in Button so it's unavailable. Maybe it should be virtual or something.

### Steps to reproduce

1. Add OptionButton
2. Add item with icon
3. Enable expand icon
4. Try to shrink the button
5. Nope

### Minimal reproduction project

N/A

**Comment by Rindbee** [comment]
I made a try in #75958.
