### ISSUE TITLE
PROPERTY_USAGE_READ_ONLY is editable in the Editor

### ISSUE THREAD

**Issue by FeralBytes** [godotengine/godot#68939]
### Godot version

4.0-beta5

### System information

Linux Mint 20.3; Kernel: 5.4.0-131; CPU: AMD Ryzen 9 3900X; GPU: AMD 5700XT, Vulkan

### Issue description

PROPERTY_USAGE_READ_ONLY does not prevent editing of the property in the editor.

### Steps to reproduce

```gdscript
var debug_squares: int = 0
var debug_triangles: int = 0

func _get_property_list():
    var props = []
    props.append({
        name = "Debug Tools",
        type = TYPE_NIL,
        hint_string = "debug_",
        usage = PROPERTY_USAGE_GROUP | PROPERTY_USAGE_SCRIPT_VARIABLE
    })
    props.append({name="debug_squares", type=TYPE_INT, useage=PROPERTY_USAGE_READ_ONLY})
    props.append({name="debug_triangles", type=TYPE_INT, useage=PROPERTY_USAGE_READ_ONLY})
    return props
```

### Minimal reproduction project

[PROPERTY_USAGE_READ_ONLY.zip](https://github.com/godotengine/godot/files/10053343/PROPERTY_USAGE_READ_ONLY.zip)

**Comment by akien-mga** [comment]
It's `usage`, not `useage`.

**Comment by KoBeWi** [comment]
Yep, it works when you fix the typo.

**Comment by Mickeon** [comment]
The mere existence of this issue admittedly does make a strong case for typed Dictionaries or more specialised data *struct*ures, and better documentation, so that simple issues like these can be prevented.

**Comment by FeralBytes** [comment]
LOL... oh wow. Thanks @akien-mga  and @KoBeWi . Spelling obviously was never my strong point.
