### ISSUE TITLE
Godot 4.0 beta5&beta6,Strange behavior using BlendNodes in AnimationTree

### ISSUE THREAD

**Issue by dszhblx** [godotengine/godot#68940]
### Godot version

4.0 beta5, beta6

### System information

Windows 10

### Issue description

when I blend two animations, the position of left hand is very strange.

![0](https://user-images.githubusercontent.com/8831593/202970749-540f6c7e-25fd-44d4-9f1b-d51fa6c21b57.png)
![1](https://user-images.githubusercontent.com/8831593/202970758-89a31c9a-4f5a-4c6a-b5b9-92571b3d316a.png)
![0 5](https://user-images.githubusercontent.com/8831593/202970769-1486a3ec-c9e7-46cd-bc2f-cead891dce60.png)

### Steps to reproduce

Open the godot project with Godot 4.0 Beta5 or Beta6
Blend between animations in AnimationTree

### Minimal reproduction project

[animation_blend_test.zip](https://github.com/godotengine/godot/files/10053606/animation_blend_test.zip)

**Comment by TokageItLab** [comment]
The animation seems to have already been broken at the point of imported it, not in the AnimationTree blending, do you understand correctly about the BoneRest?

If you are didn't create the animation on the same model, I would recommend to use retargeting https://docs.godotengine.org/en/latest/tutorials/assets_pipeline/retargeting_3d_skeletons.html. If you are animating the same model, then the "import settings" in Blender may be incorrect https://github.com/KhronosGroup/glTF-Blender-IO/issues/1662.

**Comment by dszhblx** [comment]
I used retargeting, BoneMap was set correctly，see animation_blend_test.zip above.
The Animations are from Mixamo(same pack，I guess they are made on same model)，in FBX format。I convet the animations into glTF format using Blender 3.3. So, I  used Blender glTF exporter, not importer.

I will check settings of glTF exporter.
Thanks a lot!

**Comment by dszhblx** [comment]
@TokageItLab 
Maybe the gotdot 4 blend result is correct.But this result is different from godot 3.5.
Because in godot 3.5 animation track, there is a transform hold the position of the bone, so position is blended too?
Thanks!

**Comment by TokageItLab** [comment]
@dszhblx The godot3.x blending system had several problems and has been significantly reworked in godot4.0. See also https://docs.godotengine.org/en/latest/tutorials/animation/animation_tree.html#for-better-blending.
