### ISSUE TITLE
The problem of clicking "tilemap" node

### ISSUE THREAD

**Issue by xiaoliang6669** [godotengine/godot#68947]
00000000000000000000000

**Comment by Calinou** [comment]
@xiaoliang6669 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by xiaoliang6669** [comment]
> @xiaoliang6669 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

[1.zip](https://github.com/godotengine/godot/files/10056020/1.zip)

**Comment by smix8** [comment]
Change your used resource format from text-based (.tres) to binary (.res) to speed up IO in the Editor.

Other than that your file alone must contain 150+ unique navigation polygons which turn into unique navigation meshes which turn into navigation regions which is an excessive amount. All of them need to be (re)drawn and (re)calculcated (for edge connections) everytime you make changes or (re)select nodes in the Editor. The inspector also needs to be updated with the resource data. Depending on available hardware all this is expected to lag with such a large resource. While it may not have rendering lag in the exported game it certainly will have crippled pathfinding performance / quality so this lag is also a fair warning.

The MRP contains just an image which is not very useful to help with this issue.

**Comment by xiaoliang6669** [comment]
> Change your used resource format from text-based (.tres) to binary (.res) to speed up IO in the Editor.
> 
> Other than that your file alone must contain 150+ unique navigation polygons which turn into unique navigation meshes which turn into navigation regions which is an excessive amount. All of them need to be (re)drawn and (re)calculcated (for edge connections) everytime you make changes or (re)select nodes in the Editor. The inspector also needs to be updated with the resource data. Depending on available hardware all this is expected to lag with such a large resource. While it may not have rendering lag in the exported game it certainly will have crippled pathfinding performance / quality so this lag is also a fair warning.
> 
> The MRP contains just an image which is not very useful to help with this issue.

The key point is not this. The map is large, but there are many navigation coordinates, which do not affect the operation of the game. The key point is that there is an option on the editor to load coordinates without clicking every time, which will cause the editor to change.

**Comment by xiaoliang6669** [comment]
It makes no sense to load navigation coordinates every time you click on the editor

**Comment by smix8** [comment]
The NavigationRegion2D is only (re)drawing the debug when a queue_redraw() is triggered. This happens when ...

a) The region gets enabled / disabled cause it needs to switch from enabled visuals to disabled visuals
b) The Polygon is changed cause it needs to draw the new polygon
c) The Navigation map is changed cause the edge connections between regions need to be recalculated and redrawn

> The key point is that there is an option on the editor to load coordinates without clicking every time, which will cause the editor to change.

Maybe this is lost in translation but I don't understand fully what you mean. What kind of option? An option to disable the navigation debug in the editor?

**Comment by xiaoliang6669** [comment]
> The NavigationRegion2D is only (re)drawing the debug when a queue_redraw() is triggered. This happens when ...
> 
> a) The region gets enabled / disabled cause it needs to switch from enabled visuals to disabled visuals b) The Polygon is changed cause it needs to draw the new polygon c) The Navigation map is changed cause the edge connections between regions need to be recalculated and redrawn
> 
> > The key point is that there is an option on the editor to load coordinates without clicking every time, which will cause the editor to change.
> 
> Maybe this is lost in translation but I don't understand fully what you mean. What kind of option? An option to disable the navigation debug in the editor?

Everything has not changed. I use code to control these things after the game runs. I hope it will not be updated frequently in the editor, because I will not operate and modify it in the editor

**Comment by xiaoliang6669** [comment]
As long as the map of "tilemap" is drawn on the editor, it will change. Because each map block records a large number of navigation coordinates, it will not get stuck if it does not record the navigation coordinates. Of course, it will not get stuck if it does not draw the map on the editor. The reason is that as long as the map is drawn on the editor, each time you click this node, it will read the navigation coordinates and cause the card to change, regardless of whether you change it or not

**Comment by xiaoliang6669** [comment]
This leads to a problem. When I record a lot of navigation information in each map block, I will not dare to draw the map on the editor, because it will drag down the entire editor
