### ISSUE TITLE
Node icon is too big in Inspector

### ISSUE THREAD

**Issue by ygingras** [godotengine/godot#68962]
### Godot version

4.0 beta5

### System information

Ubuntu 22.04.1 LTS

### Issue description

I have a node with the following definition: 
```extends Node
class_name Weapon
@icon("res://assets/opencliparts/sword_01.svg") 
```

The icon showed up fine in the scene tree, but in the Node Inspector, it takes the whole width of the inspector pane and obscures some of the fields.

![Screenshot from 2022-11-21 09-13-58](https://user-images.githubusercontent.com/169930/203105094-10630dca-c5a3-4c7c-be94-f70f585076d0.png)

![Screenshot from 2022-11-21 09-12-59](https://user-images.githubusercontent.com/169930/203105126-3186b4f6-3a00-49b3-96ff-651016c5668e.png)

Here is the file that I'm using as the node icon:
![sword_01](https://user-images.githubusercontent.com/169930/203105240-f744788b-92d5-4ca0-a18d-fd8546810a42.svg)
CC0 openclipart.org 

### Steps to reproduce

Create a node with `@icon("res://sword_01.svg")` using the attached file. Inspect the node.

### Minimal reproduction project

N/A

**Comment by TamerSoup625** [comment]
This happens because it renders the sword with the original texture size in the inspector. It is scaled appropiatly in the scene tree, but on the inspector it renders at the original size (533x533 in this case).

You can fix this by importing the texture with a 16x16 size (common size of all icons) by either modifying the .svg file or using the import dock in the editor.

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/36981.

**Comment by ygingras** [comment]
Oh yeah, setting size-limit to 16 in the import dock after double clicking on the file then clicking the "re-import" button solves the problem. Setting the size-limit to 32 makes the image overflow just a little bit in the inspector, which looks rather good so that's what I went for.

We can close this if the import settings are the right solution for this. Mentioning the 16x16 size recommendation in the  `@icon()` documentation would be a good idea in any case.

**Comment by Calinou** [comment]
> Mentioning the 16x16 size recommendation in the @icon() documentation would be a good idea in any case.

32×32 is recommended, so that the icon looks good on hiDPI displays.

**Comment by KoBeWi** [comment]
Related to #57286, except this one is about `class_name`.
