### ISSUE TITLE
Model importing results in weird models

### ISSUE THREAD

**Issue by JCodeFox** [godotengine/godot#68974]
### Godot version

4.0.beta5

### System information

Void Linux, Intel Celeron integrated graphics, Vulkan

### Issue description

When importing models the indices appear to be mixed up. This doesn't happen on the import preview window. Disabling LOD doesn't seem to effect it. It happens with gltf, glb, obj, and escn files from blender.

### Steps to reproduce

1. Create a 3d model in blender.
2. Export to gltf, glb, obj, or escn.
3. Import the model into Godot.

### Minimal reproduction project

[ImportTest.zip](https://github.com/godotengine/godot/files/10063703/ImportTest.zip)

**Comment by Calinou** [comment]
@JCodeFox Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by JCodeFox** [comment]
I will when I can (in a few hours)

**Comment by JCodeFox** [comment]
I have been able to reproduce it in beta 3, haven't tried it in the other betas

**Comment by JCodeFox** [comment]
Minimal project uploaded.

**Comment by fire** [comment]
Can you post a photo / video of what the corruption looks like? I suspect it may be related to integrated graphics and or mesa linux.

**Comment by JCodeFox** [comment]
Still happens in Godot 4.0, however I'm now getting an error with it.
`scene/resources/mesh.cpp:192 - Condition "index >= vc" is true. Returning: Ref<TriangleMesh>()
 scene/resources/mesh.cpp:192 - Condition "index >= vc" is true. Returning: Ref<TriangleMesh>()`

**Comment by JCodeFox** [comment]
Also, the triangles change each time I reimport.

**Comment by A840w** [comment]
> ### Godot version
> 
> 4.0.beta5
> 
> ### System information
> 
> Void Linux, Intel Celeron integrated graphics, Vulkan
> 
> ### Issue description
> 
> When importing models the indices appear to be mixed up. This doesn't happen on the import preview window. Disabling LOD doesn't seem to effect it. It happens with gltf, glb, obj, and escn files from blender.
> 
> ### Steps to reproduce
> 
> 1. Create a 3d model in blender.
> 2. Export to gltf, glb, obj, or escn.
> 3. Import the model into Godot.
> 
> ### Minimal reproduction project
> 
> [ImportTest.zip](https://github.com/godotengine/godot/files/10063703/ImportTest.zip)
> 

I also have same problem😭

**Comment by Calinou** [comment]
I can't reproduce this on 4.0.2 (Linux, GeForce RTX 4090 with NVIDIA 530.41.03) with the MRP:

![image](https://user-images.githubusercontent.com/180032/236949625-c88524f8-d98e-4b96-9f2b-e3f44e2cc700.png)

**Comment by fire** [comment]
May be fixed. 
![image](https://github.com/godotengine/godot/assets/32321/09f54c21-7416-40bc-b5de-e9125fc2d2a8)
