### ISSUE TITLE
GDScript 2.0: Argument of a function marked as constant if it is of a custom type

### ISSUE THREAD

**Issue by vonagam** [godotengine/godot#68977]
### Godot version

4.0.beta5 and currently last build of 11e1c83

### System information

MacOS 10.15.7

### Issue description

Last line of code in **Steps to reproduce** produces a parser error on last line with "Cannot assign a new value to a constant."

Maybe that is some intended behavior, but if `baz` is of type `Object` the restriction is lifted and no error is produced.

### Steps to reproduce

```gd
class Foo extends Object:
  pass

func bar( baz: Foo ) -> void:
  baz = Foo.new()
```

### Minimal reproduction project

N/A

**Comment by adamscott** [comment]
Even if the steps to reproduce are quite short, it's very appreciated when a MRP is joined. This facilitates a lot the developers job to debug and test the following PRs.

I enjoin you to create a MRP. Thanks!

**Comment by vonagam** [comment]
Ok, here is the MRP - [68977.zip](https://github.com/godotengine/godot/files/10061331/68977.zip)

**Comment by adamscott** [comment]
Oops. Mentioned unintentionally this issue in #68982.
