### ISSUE TITLE
HTML5 exports fail to run on macOS (CanvasShaderGLES3: Program linking failed)

### ISSUE THREAD

**Issue by Luzzotica** [godotengine/godot#68980]
### Godot version

4.0.beta5

### System information

MacOS Monterey 12.2.1

### Issue description

Building any godot application for web fails to load with the following error:
```
USER ERROR: CanvasShaderGLES3: Program linking failed
at: _display_error_with_code (drivers/gles3/shader_gles3.cpp:237)
USER ERROR: Method/function failed.
at: _compile_specialization (drivers/gles3/shader_gles3.cpp:397)
```

### Steps to reproduce

Create any project using Godot 4.0 beta 5 official.

Add a button and link it to a print just to test things.

Run the project once to assign a root.

Build for html.

Deploy using some server. Itch.io is the easiest, just be sure to enable the SharedBufferArray.

Try to run the game. It will block after loading, and then crash with lots of errors, the above being the first.

### Minimal reproduction project

[Godot4WebExportFail.zip](https://github.com/godotengine/godot/files/10061237/Godot4WebExportFail.zip)

**Comment by Calinou** [comment]
Which browser(s) did you test?

**Comment by Luzzotica** [comment]
I tested on Brave, Safari, and Chrome. Each had the same error.

**Comment by Luzzotica** [comment]
As a side note, I tried building using my friend's windows laptop and got the same error from the site.
If you want a live example of my game failing (Not a simple project), you can go here:
https://melodious-granita-9bfb98.netlify.app/

The game with load and then stall for a good 30 seconds to a minute before throwing the error.

**Comment by clayjohn** [comment]
> As a side note, I tried building using my friend's windows laptop and got the same error from the site. That was built with Godot 4.0.beta3 however, not beta 5. Both seem to have the same issue.
> 
> If you want a live example of my game failing (Not a simple project), you can go here: https://melodious-granita-9bfb98.netlify.app/
> 
> The game with load and then stall for a good 30 seconds to a minute before throwing the error.

The only related errors I get running this sample scene are due to it using GPUParticles which weren't implemented yet in Beta3 but they are in Beta 5. 

The fact that the error message you pointed to above is an error only with linking the Shader makes me think that the issue is also related to GPUParticles. Can you please check an example scene without GPUParticles and confirm whether you get the same error message? Apologies in advance, I don't have a macOS devices with which to test this

**Comment by Luzzotica** [comment]
@clayjohn Alright, just tested with my test project above.
Built it, and deployed it here:
Same error. I'm building from my macOS here. I will try later using my friends laptop (After updating to Godot 4.0 beta 5) on windows to see if that resolves the issue with the GPUParticles.

If that does resolve the GPUParticles, then this is a macOS build issue.

**Comment by Luzzotica** [comment]
Some additional feedback for this:
If I build my game on windows, I can run my game on a windows machine, but not on macOS.
I haven't tested if I can build the game on macOS and run it on windows.

This seems to simply be an issue with macOS not being able to run my html5 game. 

Any thoughts?

I hope my added details are helpful.

**Comment by Calinou** [comment]
> This seems to simply be an issue with macOS not being able to run my html5 game.

macOS has different graphics drivers compared to Windows, and there is no native OpenGL support. Apple still provides OpenGL support by translating OpenGL to Metal, but this comes with its own bugs and limitations.

**Comment by Luzzotica** [comment]
That sounds like an inconclusive “We have now way to fix this”.

But that can’t be right. What are our options?

**Comment by clayjohn** [comment]
> macOS has different graphics drivers compared to Windows, and there is no native OpenGL support (WebGL uses OpenGL behind the scenes). Apple still provides OpenGL 4.1 support by translating OpenGL to Metal, but this comes with its own bugs and limitations.

AFAIK this only happens on M1 and M2 systems. The older intel based Macs still attempt to run over ordinary OpenGL and the drivers are indeed very buggy. 

> That sounds like an inconclusive “We have no way to fix this”.
> 
> But that can’t be right. What are our options?

For starters, someone who can reproduce the bug needs to investigate further and determine what shader is failing to link (e.g. by process of elimination), then we need to identify what exactly is causing that shader to fail to link and figure out a workaround.

**Comment by Luzzotica** [comment]
I have an intel based Mac and it is still crashing. Guess those are the buggy drivers?

I know that the particles cause it to fail as mentioned above, but building the basic game in my first post also causes macOS to crash with tons of stuff printed out.

Here are the logs for one set of errors, if they are helpful.
[Errors.zip](https://github.com/godotengine/godot/files/10143931/Errors.zip)

I can also take a video if you'd like.

**Comment by davidlanderos-digital** [comment]
I'm also facing this issue on Godot 3.5-stable. (Safari/Brave with M1), What I find mind-bending is that if I test the game from within the editor using the HTML5 button on the top-left. it works, It only crashes when I export it.

Sounds fixable given the fact that I have at least one scenario that works with the same hardware.

**Comment by Luzzotica** [comment]
Godot 4.0 beta 7 doesn't work on Macbook pro Intel. 
Not sure if godot 4.0 has the Shader Compl. Mode. I was unable to find it.

**Comment by ztc0611** [comment]
Still occurring on Beta 8. This issue crashes Firefox and Chrome, and freezes Safari. I have an M1 MacBook Pro (Late 2020).
