### ISSUE TITLE
If parent StateMachine has Xfade, SubStateMachine is not properly initialized after end

### ISSUE THREAD

**Issue by David-Ochoa** [godotengine/godot#68986]
### Godot version

4.0 beta 5

### System information

Windows 11 Ryzen 3

### Issue description

I have a main state machine with two states: OnAir and OnLand. OnAir is another state machine, it does a loop for a falling animation, when an OnAir flag changes it will take one of two paths (normal landing or hard landing) based on how much time it was on the air.
![state_machine1](https://user-images.githubusercontent.com/13645633/203209433-efe12405-ea29-4853-a15f-8934dd6c2650.png)
![state_machine2](https://user-images.githubusercontent.com/13645633/203209452-eca9d5b9-3d45-4350-9762-a44b6c5eef26.png)
If in the transition from OnAir to OnLand the Xfade time is set to something siginificant (0.05 or more) the OnAir state machine is not left in the END state and entering again will resume the state and then start from the begining:

https://user-images.githubusercontent.com/13645633/203209975-4cd6d294-4b94-48ea-ac76-b49471e25d09.mp4

### Steps to reproduce

Create a state machine with an end state as a node for another state machine, in the transition from this state machine to another node set the cross fade to some value (0.05 or greater).

### Minimal reproduction project

Minimal reproduction project:
[TreeTest.zip](https://github.com/godotengine/godot/files/10063118/TreeTest.zip)

**Comment by TokageItLab** [comment]
I guess there is a problem with the StateMachine end process and it seems to be unwillingly looping a bit after the SubAnimation finishes to process it. I will see if we can do something about it.

**Comment by thiolliere** [comment]
it seems related to https://github.com/godotengine/godot/issues/74752 : transitionning with xfade from a state machine then first frame can be wrong.
