### ISSUE TITLE
Main screen added by plugin is displayed in all main screens

### ISSUE THREAD

**Issue by StraToN** [godotengine/godot#6899]
**Operating system or device - Godot version:**
Mageia 6
Godot master

**Issue description** (what happened, and what was expected):
The screen should only be displayed under its context, not under 2D, 3D, Asset lib and Script.

First screen: plugin disabled
![plugin-disabled](https://cloud.githubusercontent.com/assets/1289207/19620854/bb911cb8-9885-11e6-82de-9e8d4b3d530e.png)

Second screen: plugin enabled, 2D context
![plugin-enabled](https://cloud.githubusercontent.com/assets/1289207/19620855/bb915156-9885-11e6-87aa-b4cfc8d5ed1f.png)

Third screen: plugin enabled, Tree-tools context
![plugin-treetools-tab](https://cloud.githubusercontent.com/assets/1289207/19620856/bb956eda-9885-11e6-8673-7067d9ee6f94.png)

**Steps to reproduce:**
0. If you use Windows, you should copy the ``addons`` folder in the ``godot-dialogtreetools/addons/``. The idea is to set the plugin as a plugin for itself.
1. Download project : https://github.com/StraToN/godot-dialogtreetools
2. Import it in Godot launcher and click "Edit" to run the editor.
3. Go to Project settings, "Plugins" tab and enable the plugin
4. The content of the new Tree-tools context is displayed under all contexts.

**Link to minimal example project** (optional but very welcome):
https://github.com/StraToN/godot-dialogtreetools

**Comment by vnen** [comment]
You to override the `make_visible()` function to show/hide your plugin when needed.

**Comment by StraToN** [comment]
@vnen Thanks for the information. I think it puts under the light a miss in documentation. I'll look into it ;)
I'll close thing this issue as soon as I succeeded in making it work.

**Comment by vnen** [comment]
Yeah, I thought about doing a "Main Screen Plugin" tutorial, but haven't got the time.

**Comment by StraToN** [comment]
Ok I created an issue in the docs for this one. https://github.com/godotengine/godot-docs/issues/279
I may give it a try since I now know it much better.
Closing this issue then.
