### ISSUE TITLE
Text selection disappears when replacing text forwards

### ISSUE THREAD

**Issue by duianto** [godotengine/godot#69007]
### Godot version

v4.0.beta5.official [89a33d28f]

### System information

Windows 10 22H2, OpenGL3, Geforce GTX 550 Ti

### Issue description

The text selection disappears when replacing text forwards `enter`

https://user-images.githubusercontent.com/13420573/203341280-bb7df474-18bb-4924-ac7a-1359fe3ecd06.mp4

But the selection remains visible when replacing text backwards `shift enter`

https://user-images.githubusercontent.com/13420573/203341302-67f760be-91aa-4da9-92e1-c9f9cd9d1960.mp4

### Steps to reproduce

- Open the included project: `issue, text selection disappears, replace text forwards.zip`
- In the bottom left panel: `FileSystem`
- Double click on the script: `new_script.gd`
- In the script editor, on line `3`, double click on `123` to select the number
- Press `ctrl r` to open the find and replace input boxes at the bottom of the script editor
- With the replace input box focused, type `456`
- Press `enter`
The instance of `123` on line 3 was replaced with `456` as expected, but...

### Expected
The next occurrence should be selected, so that it's visible what will be replaced when `enter` is pressed again.

The expected behavior is observed when replacing backwards: `shift enter`
Now the next occurrence to be replaced is selected.

### Observed
The text selection disappeared. This makes it difficult to see which occurrence will be replaced when `enter` is pressed again.

In this example it's easy to see the next occurrence, but it becomes difficult when the occurrences are on multiple columns and lines.

### Minimal reproduction project

[issue, text selection disappears, replace text forwards.zip](https://github.com/godotengine/godot/files/10075999/issue.text.selection.disappears.replace.text.forwards.zip)

It's not project specific, it's reproducible in a new project with a new script file, the project doesn't even have to be saved.

It can also be reproduced with the default script template, it has four instances of the word "the".

I had already recorded the videos above when I noticed that simpler reproduction step.

**Comment by KoBeWi** [comment]
Still valid in 4.3 dev6
