### ISSUE TITLE
PARSE ERROR? Expected end of statement after variable declaration, found "Identifier" instead.

### ISSUE THREAD

**Issue by chaosgamng** [godotengine/godot#69010]
### Godot version

4.0 Beta 5 Win64

### System information

Windows 11, Vulkan, gtx mx450

### Issue description

After switching to Godot 4 Beta 5,

I came into a problem while coding

```gdscript
var viewport := get_viewport()
var viewport_center = viewport.size / 2.0
var direction := viewport.get_mouse_position() - viewport_center
var percent := (direction / viewport.size * 2.0).length()
```

these lines would give me the error "Expected end of statement after variable declaration, found "Identifier" instead."
and what's weird is this didn't happen until Godot Crashed while I was using the Anchor feature for UI.

thank you,

Chaos

### Steps to reproduce
```gdscript
var viewport := get_viewport()
var viewport_center = viewport.size / 2.0
var direction := viewport.get_mouse_position() - viewport_center
var percent := (direction / viewport.size * 2.0).length()
```
Whenever the above code is used I get this error now, no matter what script or node is used.

### Minimal reproduction project

N/A

**Comment by adamscott** [comment]
To cite [CONTRIBUTING.md](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md)

> On the contributors' end, recreating a test project from scratch takes valuable time that can be saved by uploading a minimal project.

> To speed up our work, please upload a minimal project that isolates and reproduces the issue. This is always the best way for us to fix it. We recommend attaching a ZIP file with the minimal project directly to the bug report, by drag and dropping the file in the GitHub edition field. This ensures the file can remain available for a long period of time. Only use third-party file hosts if your ZIP file isn't accepted by GitHub because it's too large.
> 
> We recommend always attaching a minimal reproduction project, even if the issue may seem simple to reproduce manually.

Please upload a MRP to the issue's description.

**Comment by Calinou** [comment]
PS: Code blocks should use triple backticks like this (with an optional language name for syntax highlighting):

\`\`\`gdscript
code here
\`\`\`

I edited your post accordingly, but remember to do this in the future :slightly_smiling_face:

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
