### ISSUE TITLE
4.0, mouse click below code without an empty last line, error: Index p_column = 6 is out of bounds

### ISSUE THREAD

**Issue by duianto** [godotengine/godot#69011]
### Godot version

v4.0.beta5.official [89a33d2]

### System information

 Windows 10 22H2, OpenGL3, Geforce GTX 550 Ti

### Issue description

The `Output` panel shows an error message like this:
```
scene/gui/text_edit.cpp:4911 - Index p_column = 6 is out of bounds (text[carets[p_caret].selection.selecting_line].length() + 1 = 6).
```

When left mouse button clicking below code, without an empty last line.

For example, if one want to select from the last line, upwards, by mouse dragging upwards.

An empty line is added automatically at the end when a script file is saved.
But this error can be encountered if one, for example, copies code from a website, 
and it didn't have an ending empty line, or it wasn't included in the selection when the code was copied.

### Steps to reproduce

- Open the included project: `error, mouse click below non-empty last line.zip`
- On the bottom panel, open the `Output` panel
- In the bottom left `FileSystem` panel
- Double-click on the script: `new_script.gd`
- In the script editor, erase the last empty line (line 12), leaving `pass` as the last line
- Mouse left click below the last line (line 11)

### Expected
Nothing should happen.

### Observed
The Output panel shows the error message:
```
  scene/gui/text_edit.cpp:4911 - Index p_column = 6 is out of bounds (text[carets[p_caret].selection.selecting_line].length() + 1 = 6).
```

### Minimal reproduction project

[error, mouse click below non-empty last line.zip](https://github.com/godotengine/godot/files/10075842/error.mouse.click.below.non-empty.last.line.zip)

~A MRP is probably not needed, since it happens in any script without an empty last line, even with the default script template.~

**Comment by adamscott** [comment]
To cite [CONTRIBUTING.md](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md)

> On the contributors' end, recreating a test project from scratch takes valuable time that can be saved by uploading a _minimal_ project.

> To speed up our work, **please upload a minimal project** that isolates and reproduces the issue. This is always the **best way for us to fix it.** We recommend attaching a ZIP file with the minimal project directly to the bug report, by drag and dropping the file in the GitHub edition field. This ensures the file can remain available for a long period of time. Only use third-party file hosts if your ZIP file isn't accepted by GitHub because it's too large.
> 
> We recommend always attaching a minimal reproduction project, even if the issue may seem simple to reproduce manually.

> **If you've been asked by a maintainer to upload a minimal reproduction project, you _must_ do so within 7 days.** Otherwise, your bug report will be closed as it'll be considered too difficult to diagnose.

Please upload a MRP to the issue's description.

(I know that you say that it happens to any script, but it really helps having a prepared project to test, Thank you!)

**Comment by duianto** [comment]
Sorry about that, I added a MRP, and updated the reproduction steps.

**Comment by adamscott** [comment]
I confirm the issue.
