### ISSUE TITLE
TileMap improvements

### ISSUE THREAD

**Issue by UnwarySage** [godotengine/godot#6902]
I would like to request a few simple-ish functions for the tilemap class, based on my dabbling with procedural levels.

get_extents():
Returns a rect2 or similar structure that contains the space occupied by non-empty cells. This should be fairly easy to do at at base level, and spares having to write something to loop through all of get_used_cells.

flood_cellsv( vector2 position, tile ID to flood fill, optional array of tile ids which block the flood fill):
flood fills an area from code with the tile id, starting at the vector2 position, the optional array when not present would default to anything other than -1

find_connected( Vector2 position, array of blocking tile IDs):
Breadth-first-Searches the tilemap, starting at the vector position provided, and constrained by the array of tile IDs. Returns an array of reachable positions.

overlay_tilemap(Vector2 position, node)
Takes the node, which should be a tilemap with the same tileset and copies it into the calling tilemap, not adding or deleting anything under empty cells in the copied map.

A chunk of these are maybe a little too specific, but I want to open up some thought about what a few underlying tools could be used for.

**Comment by Zylann** [comment]
Note: almost all of these methods are grid algorithms. They can be implemented in GDScript, but also for any kind of grid, be it for Tilemap edition, level generation or ahead-of-time AI simulation (the same goes for pathfinding).
Having them on Tilemap could be handy for performance, but having them only here would be a bit of a waste, isn't it? I worked on grids too in a totally different area not involving tilemap, but I needed the same functions as described above, and the way I implemented them could work on anything having get(x,y), set(x,y) and optionally a 2D size.
Anyways it's fine if we get these functions in Tilemap, just felt this should be mentionned.

**Comment by Norrolith** [comment]
Hmm, I had no idea Godot had grid datastructures. I agree they would be handy in there as well.

**Comment by Zylann** [comment]
Godot has no "grid" data structure, only specified classes having grid access (Image, Tilemap, Gridmap...). Grids I worked on were pure GDScript.

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.
