### ISSUE TITLE
Override gutter icon does not show for inner classes

### ISSUE THREAD

**Issue by RedMser** [godotengine/godot#69023]
### Godot version

4.0.dev (e3a51e53ef055a1fe94351b68173c6dfcd2cb371)

### System information

Windows 10

### Issue description

The script editor does not show the override gutter icon when overriding a method of an inner class:

![image](https://user-images.githubusercontent.com/5117197/203413395-c09554f0-fd58-4200-b156-cff716c5f2b8.png)

### Steps to reproduce

```gdscript
extends Node2D

func _draw() -> void:   # override icon :)
	pass

class Inner extends Node2D:
	func _draw() -> void:   # no icon :(
		pass
```

### Minimal reproduction project

See above code snippet.

**Comment by MewPurPur** [comment]
It's fine, the code snippet can be copied in any script.

**Comment by RedMser** [comment]
I quickly looked into it, to give anyone interested a starting point.
The code just takes the base class of the script, not taking the inner classes into account: https://github.com/godotengine/godot/blob/a9b394d5bcd551d7ccb16cf19d6e40f675c9d07b/editor/plugins/script_text_editor.cpp#L1047

The `name` variable contains the inner class nesting hierarchy like `Inner._draw`, so you probably need to query the script for the inner class info first.

I'm not 100% sure if GDScript supports multiple layers of nested classes, but if it does then this should be taken into account as well.
