### ISSUE TITLE
Editor crashed when I was uploading 3d landscape

### ISSUE THREAD

**Issue by zevertaix** [godotengine/godot#69029]
### Godot version

4.0 (Beta 4)

### System information

Windows 11, Vulkan API 1.2.182, NVIDIA GeForce GTX 1650 SUPER

### Issue description

I tried to make 3d landscape in Blender. Then I exported 3d model with .glb format. Then I wanted to import this object in godot, and after 2 minutes godot crashed. I tried to do this a few times, but without results...

You can dowload my 3d landscape from following link.

Download landscape 3d model: https://drive.google.com/file/d/13DSo2lu9vfhohlp9-c6gzt9ua0El2Xlg/view?usp=share_link

![Снимок экрана 2022-11-22 230725](https://user-images.githubusercontent.com/53122904/203421742-7ab5c66d-563d-45e3-92cb-3fdd2420240d.png)

### Steps to reproduce

1. Download my 3d landscape.
2. Create empty 3d project in Godot.
3. Move 3d object in a project folder
4. Open a project and wait...
5. BOOM... in this step I've got a crash

### Minimal reproduction project

Minimal project (with 3d model): https://drive.google.com/file/d/1wsIfzuF6pFbC6nNWRObt6zF0_EYp_Uxg/view?usp=share_link

**Comment by clayjohn** [comment]
Could you run the project from the command line and then let us know if anything prints when the crash happens?

**Comment by zevertaix** [comment]
Ok, I will try in the evening (+2 GMT)

**Comment by adamscott** [comment]
@zevertaix You need to run the console executable instead of the Godot executable (there's two files in the downloaded Godot zip)

I suggest you test with [Godot 4.0 beta 5](https://godotengine.org/article/dev-snapshot-godot-4-0-beta-5) too, as a fix could have been found between beta 4 and 5.

**Comment by zevertaix** [comment]
I tried to run it in Godot 4.0 beta 5.
And also I tried run with console. Error before a crash:

![error_console_godot](https://user-images.githubusercontent.com/53122904/203598371-aba2d3e9-cbac-4229-b77b-ef26b47028dc.png)

**Comment by zevertaix** [comment]
up⬆️

**Comment by clayjohn** [comment]
Can you take a look at your RAM usage in the task manager as you reproduce the bug? That error message seems to be saying you are running out of RAM

**Comment by zevertaix** [comment]
Memory was changing from ~1100 to ~2100 Mb. Yes, this problem with RAM, but for exmple, I can import this landscape to unity in ~10 sec. So, it's a reason why I created this issue. Maybe you can create some threads for import big models. I think it's important. What do you think?

![image](https://user-images.githubusercontent.com/53122904/205451048-349d4afc-b019-4f1c-ad0c-6b50d8accaa8.png)
