### ISSUE TITLE
Godot fails to compile nested recursive namespace names with cryptic error messages

### ISSUE THREAD

**Issue by LouisIngenthron** [godotengine/godot#69038]
### Godot version

v4.0.beta5.mono.official [89a33d28f]

### System information

Windows 10 x64

### Issue description

If you add a C# script with nesting namespace lines that use the same name as a higher namespace name, Godot fails to compile, but gives an odd error about Godot.SourceGenerators temporary files instead of the problem file in question.

### Steps to reproduce

To reproduce the error, just add the below class to a C# script in a Godot 4 project and then reference that class in any other script and click build:

```
using Godot;

namespace SpaceA.SpaceB
{
    namespace SpaceA
    {
        public partial class Foo : Node {}
    }
}
```

### Minimal reproduction project

[BugReport.zip](https://github.com/godotengine/godot/files/10079379/BugReport.zip)

**Comment by adamscott** [comment]
To cite [CONTRIBUTING.md](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md)

> On the contributors' end, recreating a test project from scratch takes valuable time that can be saved by uploading a minimal project.

> To speed up our work, please upload a minimal project that isolates and reproduces the issue. This is always the best way for us to fix it. We recommend attaching a ZIP file with the minimal project directly to the bug report, by drag and dropping the file in the GitHub edition field. This ensures the file can remain available for a long period of time. Only use third-party file hosts if your ZIP file isn't accepted by GitHub because it's too large.
> 
> We recommend always attaching a minimal reproduction project, even if the issue may seem simple to reproduce manually.

Please upload a MRP to the issue's description.

**Comment by LouisIngenthron** [comment]
Updated original post per request.
