### ISSUE TITLE
c#_project_directory setting causes C# project feature to be stripped from project.godot

### ISSUE THREAD

**Issue by alexdlm** [godotengine/godot#69045]
### Godot version

4.0 beta5

### System information

Windows 11

### Issue description

I discovered the `dotnet/project/c#_project_directory` setting, which is wonderful because I like to keep source separate from the rest of the godot project assets.

I've been using this successfully for a week or two. Unfortunately after settings this, the `project.godot` file has `C#` stripped from `application/config/features` on save, so I've been manually restoring this a lot.

### Steps to reproduce

0. In a project with C# set up already, confirm project.godothas "C#", in the setting `config/features=PackedStringArray("4.0", "Forward Plus", "C#")`
1. Edit project settings, turn on advanced, go to DotNet and enter a directory name for `c#_project_directory`, call it `Source` for this example
2. Make `Source` directory
3. Move the .csproj into `Source` directory
4. Edit .sln file so .csproj is located in the `Source` dir. Or do this all in your IDE of choice...
5. Go back to Godot, edit a random setting to trigger project save. 
6. Check project.godot and see C# is removed from the `config/features`

### Minimal reproduction project

[SourceDirTest.zip](https://github.com/godotengine/godot/files/10074058/SourceDirTest.zip)

**Comment by raulsntos** [comment]
The `dotnet/project/c#_project_directory` no longer exists, so this is no longer an issue.
