### ISSUE TITLE
2D Skeleton polygon mapping results in error "drivers/vulkan/rendering_device_vulkan.cpp:7717 - Condition "!vertex_array" is true."

### ISSUE THREAD

**Issue by ttexpie** [godotengine/godot#69040]
### Godot version

4.0.beta5

### System information

Windows 10 64 bit, RTX 2080 SUPER, foward plus

### Issue description

Skeleton 2D seems to have multiple issues when mapping 2D polygons to bones. I am following the steps from the [docs](https://docs.godotengine.org/en/latest/tutorials/animation/2d_skeletons.html) to create the 2D skeleton. 

![image](https://user-images.githubusercontent.com/49420152/203474477-f1257f5d-b635-4e7e-b3ed-c1e57a1199db.png)
Seems to happen when assigning skeleton to polygon when no vertices have been painted for bones. However, the polygon texture completely disappears.

![image](https://user-images.githubusercontent.com/49420152/203475015-b223375a-8715-4678-961b-469e5996f6c7.png)
Assigning vertex weights fixes console errors, but doesn't fix missing textures. seems to be related to pivot point?

![image](https://user-images.githubusercontent.com/49420152/203475420-3143503b-2a74-411e-9147-e260b4798a6b.png)
Centering pivot point doesn't fix either. I thought pivot point was unrelated to skeleton mapping, unless I am wrong? 

### Steps to reproduce

Follow steps from docs until you have to assign the skeleton to the polygons. Opening UV tab and assigning bone weights stops console spam, but doesn't fix missing textures. 

### Minimal reproduction project

[godotskeletonissue.zip](https://github.com/godotengine/godot/files/10073046/godotskeletonissue.zip)

**Comment by clayjohn** [comment]
This was just fixed a few days ago in https://github.com/godotengine/godot/pull/68863

The fix will be in beta 6
