### ISSUE TITLE
AnimationTree cannot play animation in inherited scene

### ISSUE THREAD

**Issue by magian1127** [godotengine/godot#69044]
### Godot version

4.0 dev (7f8ecffa) 2022/11/23

### System information

win11

### Issue description

![image](https://user-images.githubusercontent.com/14800320/203503428-42f932f8-8fce-4a9b-93bb-f828861190e4.png)
The AnimationTree of the inherited node is invalid.

### Steps to reproduce

see demo project

### Minimal reproduction project

[bugDemo.zip](https://github.com/godotengine/godot/files/10073858/bugDemo.zip)

**Comment by akien-mga** [comment]
CC @godotengine/animation

**Comment by magian1127** [comment]
Normal after restore #68593

**Comment by TokageItLab** [comment]
Can you check #68993?

**Comment by magian1127** [comment]
> Can you check #68993?

#68993 is OK
