### ISSUE TITLE
rigidbody not detecting collision with kinematicbody

### ISSUE THREAD

**Issue by plucian** [godotengine/godot#6905]
**Operating system or device - Godot version:**
Windows 8 - Godot 2.2 alpha

**Issue description** (what happened, and what was expected):
the rigidbody (player) is not detecting the collision with a kinematicbody instantiated through code (bullet). Function used is based on the signal body_enter (Object body).

**Steps to reproduce:**
see attached example
[rigid-Kinematic.zip](https://github.com/godotengine/godot/files/546248/rigid-Kinematic.zip)

**Link to minimal example project** (optional but very welcome):

**Comment by eon-s** [comment]
You need to set the "bullet" shape to trigger mode, it will work like an area that way and will <enter> the rigid.

**Comment by plucian** [comment]
I believe that is should have worked they way is set up in the example. There are many work arounds, I just changed the bullet to a rigidbody object + two other lines in the code and works just fine. to me this is still a bug though.

**Comment by bojidar-bg** [comment]
I would agree with @eon-s, since `move` would prevent the bullet from moving _through_ the rigidbody, and if the rigidbody isn't moving in the opposite direction, it would probably never collide with the kinematicbody (especially if the former has CCD on).

**Comment by plucian** [comment]
the same set up works on a rigidbody, if both bullet and player are rigidbodies the collision is detected. Anyway, if you guys say that this works as intended then is not an issue, just a misuse .. so close the issue.
