### ISSUE TITLE
Camera outline got bugged

### ISSUE THREAD

**Issue by Perndoe** [godotengine/godot#69057]
### Godot version

4.0 beta 5

### System information

Windows 11

### Issue description

When I click on camera the outlines got bugged out and some parts disappear
![image](https://user-images.githubusercontent.com/81963564/203591046-ad3f61cc-bbe1-45db-a330-c9b75b948b4b.png)
![image](https://user-images.githubusercontent.com/81963564/203591061-057b0d05-0bea-4b88-940f-85524e14d3e5.png)

### Steps to reproduce

Create camera node attached to a sprite node or something

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/10077128/Test.zip)

**Comment by Calinou** [comment]
This is likely because the camera outline is thicker than other outlines, which makes it drawn as a polygon and is affected by zoom in the 2D editor. At zoom levels below 100%, it becomes too thin to be drawn consistently.

**Comment by PandoCyclone** [comment]
> This is likely because the camera outline is thicker than other outlines, which makes it drawn as a polygon and is affected by zoom in the 2D editor. At zoom levels below 100%, it becomes too thin to be drawn consistently.

No fix yet?

**Comment by Calinou** [comment]
> No fix yet?

There is no ETA for fixing issues, as contributors work on a best-effort basis.

**Comment by Perndoe** [comment]
> > No fix yet?
> 
> There is no ETA for fixing issues, as contributors work on a best-effort basis.

Umm it is dumb that Godot 4 already got the camera enabled which is why it bugged out
