### ISSUE TITLE
Unable to get vertex count from the RenderingServer, viewportrenderinfo missing

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#69059]
### Godot version

3.5.1 stable, 4.0 beta5

### System information

Win 10, Nvidea 765M

### Issue description

I'm trying to get the viewport vertex count like it was possible in Godot 3 using the VisualServer:

`$Label.text = str(VisualServer.viewport_get_render_info(get_viewport().get_viewport_rid(), VisualServer.VIEWPORT_RENDER_INFO_VERTICES_IN_FRAME))`

The problem seems to be in Godot4 Beta5, the now called RenderingServer does not have this ViewportRenderInfo constant `VIEWPORT_RENDER_INFO_VERTICES_IN_FRAME` any more: https://docs.godotengine.org/en/latest/classes/class_renderingserver.html#enum-renderingserver-viewportrenderinfo

For a comparison, here is the constant in Godot3: https://docs.godotengine.org/en/stable/classes/class_visualserver.html#enum-visualserver-viewportrenderinfo

### Steps to reproduce

`print( str(RenderingServer.viewport_get_render_info(%SubViewport.get_viewport_rid(), RenderingServer.VIEWPORT_RENDER_INFO_TYPE_VISIBLE, RenderingServer.VIEWPORT_RENDER_INFO_VERTICES_IN_FRAME)) )`

### Minimal reproduction project

[vertex_count.zip](https://github.com/godotengine/godot/files/10077785/vertex_count.zip)

**Comment by fire** [comment]
See https://github.com/AllenDang/model_explorer_godot4/issues/2

**Comment by clayjohn** [comment]
The new name is ``VIEWPORT_RENDER_INFO_PRIMITIVES_IN_FRAME`` before it was a bit confusing because it wasn't actually returning the number of vertices it was reporting the the total of vertices or indices depending on if a given mesh used an index buffer or not.

**Comment by golddotasksquestions** [comment]
@clayjohn  @fire 
Thank you both for the info!

I would have never guessed this is the total vertex count int the viewport, since the name PRIMITIVES makes it sound as if it has something to do with primitive meshes. As someone who does not know that much about rendering and programming compared to you guys, I find this name much more confusing.
