### ISSUE TITLE
Cannot override functions with narrowing return type.

### ISSUE THREAD

**Issue by RoniPerson** [godotengine/godot#69075]
### Godot version

4.0.beta6

### System information

Windows 10

### Issue description

When overriding a method of a class it is not possible to change the return type even if the new return type is a valid subtype of the original.

### Steps to reproduce

a.gd
```swift
extends Object

func foo() -> Node:
    return Node.new()
```
b.gd
```swift
extends "a.gd"

func foo() -> Node2D: # The function signature doesn't match the parent. Parent signature is "Node foo()".
    return Node2D.new()
```

### Minimal reproduction project

[override_bug.zip](https://github.com/godotengine/godot/files/10079268/override_bug.zip)

**Comment by Mickeon** [comment]
I wonder, how does this work in other languages?

**Comment by RoniPerson** [comment]
It works in [Dart](https://dartpad.dev/5a30443b5103c07fc1196383b9b09b86).

I also tested it in Python and TypeScript and it works in both but they would also allow me to return a not compatible type (e.g. String) from the overriden method which seems questionable to me.

**Comment by RoniPerson** [comment]
Completed per #82477
