### ISSUE TITLE
Client sends a packet, the server does not receive the PackedByteArray - only a 0 in its place. ENetConnection/low-level ENet.

### ISSUE THREAD

**Issue by YukenK** [godotengine/godot#69078]
### Godot version

4.0 Beta 5

### System information

Linux (PopOS & Gentoo).

### Issue description

When I attempt to send data to the server from my client, the server does not seem to receive the PackedByteArray. Instead, my event looks like this: [EVENT_TYPE, PACKET_PEER, 0, 1] (where 1 is my reliable channel). That 0 _should_ be the data the client sent, but it is not.

### Steps to reproduce

Create an ENet server and client.
Connect the client to the server.
Send a packet from the client to the server.
The server event will print out as [EVENT_RECEIVE, PACKET_PEER, 0, 1]. 0 should be the PackedByteArray from the client.

### Minimal reproduction project

[enet_test.zip](https://github.com/godotengine/godot/files/10079495/enet_test.zip)

**Comment by YukenK** [comment]
Issue was PEBKAC - you're supposed to use get_packet on the peer!

**Comment by GrauBlitz** [comment]
I had the same issue, I totally overlooked the last sentence of the Docs to the `Service()` function:

```text
If the generated event is Godot.ENetConnection.EventType.Receive, the received
packet will be queued to the associated Godot.ENetPacketPeer.
```

Maybe a added sentence at the end like `"...and needs to be retrieved by the GetPacket() function of the corresponding ENetPacketPeer."` would benefit the documentation. (I am using C#)
