### ISSUE TITLE
Moving Node from scene makes children rename in a weird way

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#69071]
### Godot version

4.0 beta 5

### System information

manjaro linux

### Issue description

Lets suppose you have 2 Scenes:

* Player
* Level

level layout:

- Level
  L subNode
  L Player (marked as editable)
      L playersubNode
           L Camera3D (this is from level not from player)
           
 if you go to edit player in its own scene tab and move `playerSubNode` looks in the video below what happens

### Steps to reproduce

https://user-images.githubusercontent.com/58845030/203645045-22f04030-6ce9-4f76-9203-80c709043c1e.mp4

### Minimal reproduction project

N/a

**Comment by KoBeWi** [comment]
This is intended. The child node you added in the other scene no longer has a valid parent. Previously it would be deleted, but after #60893 the editor will attempt to rescue such nodes and will put their original path as a name.
