### ISSUE TITLE
Editor deletes Autoloaded node's children

### ISSUE THREAD

**Issue by jeffgamedev** [godotengine/godot#69073]
### Godot version

v4.0.beta6.official [7f8ecffa5]

### System information

Windows 10

### Issue description

When using a global auto-loaded node, the editor will delete the children of the node if they are referenced via a script.

This occurred in my project that is stable in Godot 4 beta 4 and I noticed right away that my one global node had most of the children deleted when I opened the project in Godot 4 beta 6.

I was able to recreate a minimum project with ease by setting up an auto-loaded node that has children and scripts that reference the global name.

I build the autoloaded node like this with two children:
![](https://jeffgamedev.com/img/dev/singleton-issue.png?raw=true)

Here is the raw text of the node:
![](https://jeffgamedev.com/img/dev/singleton-issue-raw.png?raw=true)

After reloading the project, the editor has deleted my child nodes:
![](https://jeffgamedev.com/img/dev/empty-global-raw.png)

This is a major regression from Godot 4 beta 1, 2, 3, and 4.

### Steps to reproduce

1. Create a scene with a corresponding script and add it to as an auto-loaded global.
2. Create two child nodes with corresponding scripts and add them as children to the auto-loaded node. Create onready references to them in the auto-loaded node's script.
    ![](https://jeffgamedev.com/img/dev/singleton-issue.png?raw=true)
3. In one of the child node scripts, reference the other child of the auto-loaded node from the global reference.
    ![](https://jeffgamedev.com/img/dev/singleton-issue-child-b.png?raw=true)
5. Click Project > Reload Current Project
6. Open the auto-loaded node and observe that the editor has deleted it's child nodes.
    ![](https://jeffgamedev.com/img/dev/singleton-deleted-children.png?raw=true)

### Minimal reproduction project

[editor-deletes-nodes.zip](https://github.com/godotengine/godot/files/10079156/editor-deletes-nodes.zip)

Attached is my minimum reproduction project. When you open the project, the editor will delete the child nodes before you can observe in the scene hierarchy. To prove that it is opening, I recommend opening the `singleton.tscn` node in an external editor, then opening in editor to observe that the nodes have been deleted. You can also re-add the child nodes, `map.tscn` and `ui.tscn`, and all appears well until you do the step I describe above to Reload the project, and you can observe that once again the children have been deleted.

**Comment by adamscott** [comment]
Found the issue, found a way to fix it. I'm investigating a way to cleanly fix this, though.

The problem is the cyclic loading of `singleton.tscn`. It is loaded first by the autoload, then it's loaded back in `map.gd`. But it loads a new instance of the scene, not the first one loaded.

When the first one loaded is reused, there's no issue and no nodes disappear.

**Comment by adamscott** [comment]
My PR #69079 fixes the issue and the MRP. 

But don't panic if the MRP returns "null" and "null". You print in the child nodes `Singleton.child`, but `child` is set when the parent is ready, which is after the `child`'s `_ready()` function.

**Comment by jeffgamedev** [comment]
Confirmed that PR https://github.com/godotengine/godot/pull/69079 fixes the issue.
