### ISSUE TITLE
Godot 4.0 b 4-6 crashes when connecting to LSP in external editor

### ISSUE THREAD

**Issue by strash** [godotengine/godot#69080]
### Godot version

4.0b4-6

### System information

MacOS 13.0.1

### Issue description

Editor crashes silently when I open a script in external editor (neovim in my case). I think it is because of the special keywords with `@`.

### Steps to reproduce

1. open Godot
2. open script in external editor

### Minimal reproduction project

[mrp.zip](https://github.com/godotengine/godot/files/10079730/mrp.zip)

**Comment by strash** [comment]
Specifically the `@export_color_no_alpha` keyword. Just `@export` or `@tool` works fine.

**Comment by YuriSizov** [comment]
Can't reproduce the crash with VS Code in either beta 5 or current master. Can be some different condition or can be related to neovim's handling of LSP specifically.

We do spam `Cannot get class '@GDScript'.` quite a lot when you type an annotation. Seems like we get it once per character, so probably from an attempt to do autocompletion. But it doesn't crash for me either way.

**Comment by strash** [comment]
Tested on latest stable version 4.0 and it doesn't crash anymore. And `@export_color_no_alpha` works as expected.

Seems like the bug was fixed at some point. Thanks!
