### ISSUE TITLE
Updating a sound file makes the FileExplorer ignore display mode

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#6908]
Tested on Godot 2.1, Windows 10 64 bits

![filesystem_display_bug](https://cloud.githubusercontent.com/assets/1311555/19628548/9097122a-9960-11e6-8145-312433489396.png)

Repro steps:
1) Make sure the FileExplorer is in icons mode
2) Import a sound, see it in the FileSystem
3) Set the FileSystem display mode to "list"
4) Modify the sound and overwrite its file
5) Go back to Godot, see it auto-re-imports the updated sound
6) Notice the FileExplorer now shows an icon for the sound, making its line a lot bigger than others. It should not show an icon here because the selected mode is still "list".

Note: this issue probably affect other resource types.

Note 2: I noticed that hitting the "Play game" button, the UI refreshes and the FileExplorer shows the list correctly.

**Comment by Zylann** [comment]
I reproduced this with script files too. Hit Ctrl+S while having the list display mode, and poof
![filesystem_display_bug2](https://cloud.githubusercontent.com/assets/1311555/19988536/eefd5162-a220-11e6-8777-c81deddc6f7f.png)

**Comment by reduz** [comment]
all this code is gone, so closing this
