### ISSUE TITLE
Help Font Size and Help Source Font Size EditorSettings don't do anything

### ISSUE THREAD

**Issue by Yagich** [godotengine/godot#69097]
### Godot version

4.0b6

### System information

Linux/Manjaro

### Issue description

The EditorSettings properties `text_editor/help/help_font_size` and `text_editor/help/help_source_font_size` have no effect in the editor docs. Confusingly, the property `text_editor/help/help_title_font_size` does work, after an editor restart.

### Steps to reproduce

1. Change EditorSettings `text_editor/help/help_font_size` or `text_editor/help/help_source_font_size` to any value.
2. Observe that no change has taken place, even after an editor restart.

### Minimal reproduction project

N/A

**Comment by brunosxs** [comment]
I kinda identified the problem.
Value is correctly saved to the editor theme, but when the editor refreshes itself, it grabs data from the cache of the resource, which is not correctly invalidated, thos having the old value.
There is a second issue, which is: EditorHelp does not have variables and does not change fonts of the help documentation based on those values. The only variable present is `doc_title_font_size`.
The latter issue is easier to solve, but I dunno why the first one happens tho. I would like to grab this task but I'll have to ask for some guidance from some of the other devs.

**Comment by pedrogabe** [comment]
Hi there,
I just wanted to let you know that I'm looking into it. I'm knew to this so it might take a while, but I seem to be getting to where the font size should be specified (so far it does look like it just takes a generic theme font size)
