### ISSUE TITLE
Crash when using Skeleton2D "deleting mesh with active instances"

### ISSUE THREAD

**Issue by h0lley** [godotengine/godot#69092]
### Godot version

v4.0.beta.custom_build [fa270c245]

### System information

Ubuntu, Vulkan, Nvidia

### Issue description

When freeing a scene that contains a Polygon2D with a skeleton set, Godot crashes with this error message:
```
ERROR: deleting mesh with active instances
   at: mesh_free (servers/rendering/renderer_rd/storage_rd/mesh_storage.cpp:236)
```
#68863 made Skeleton2D usable again but perhaps introduced this issue.

### Steps to reproduce

1. Create new Node2D scene
2. Add Polygon2D, plug a texture in (e.g. icon.svg), and add some points (polygon data)
3. Add Skeleton2D and plug it into the skeleton property of your polygon
4. Add at least two Bone2D as children to the Skeleton2D node
5. Open the UV editor on the Polygon2D and click Sync Bones to Polygon to on the Bones tab
6. a) Save the scene and close the tab - see Godot crash
6. b) alternatively add a second scene and have the first one change to the second scene via `change_scene_to_file()` in `_ready()`, hit F5 and see the game crash

### Minimal reproduction project

[godot_4_free_skel2d_bug.zip](https://github.com/godotengine/godot/files/10080817/godot_4_free_skel2d_bug.zip)

**Comment by clayjohn** [comment]
#68863 doesn't really do anything with allocating or freeing the skeletons, so it's more likely that the bug existed already and #68863 just exposed it by making Skeleton2D actually usable.

**Comment by clayjohn** [comment]
I can reproduce the error message, but not the crash. 

Are there any additional steps needed to make Godot crash in addition to the error message?

**Comment by h0lley** [comment]
ah, please also add at least two Bone2D as children to the Skeleton2D node, open the UV editor on the Polygon2D, and click Sync Bones to Polygon to on the Bones tab. then, save the scene and try to close it.

even after deleting the Bone2D nodes this will persist (which is why I missed that it was needed for reproduction).

**Comment by clayjohn** [comment]
Thanks!

I built from 5fd382c2ab3a117c0d98690f9f1f84fbf9d27234 and tested again with your updated instructions and still can't reproduce the crash (I do consistently get the error though). I'm on Windows 10 and using Radeon graphics, so this could come down to a difference in device setup.

I'll start by fixing the error message and then we'll see if that resolves the crash.
