### ISSUE TITLE
CanvasEditor's zoom widget has janky click areas

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#69093]
### Godot version

4.0.beta6

### System information

Ubuntu 22

### Issue description

![Clipboard - November 22, 2022 6_07 PM](https://user-images.githubusercontent.com/85438892/203695334-6adbfd58-92bd-461b-9da0-e019bd39544f.png)

This cursor position here should get the Zoom Minus' focus, not the Zoom Reset's.

The bug is caused by the HBoxContainer using a negative amount of separation. So Zoom Plus overlaps a bit of Zoom Reset, and Zoom Reset overlaps a little bit of Zoom Minus.

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by YuriSizov** [comment]
> The bug is caused by the HBoxContainer using a negative amount of separation.

That doesn't seem like a bug. If the separation is negative, then the right-hand items will start to overlap the left-hand items.

**Comment by MewPurPur** [comment]
Yeah I meant that the "janky click areas" is caused by this behavior, didn't mean that the behavior itself is a bug.
