### ISSUE TITLE
Shader param won't reset after reloading scene with background loader

### ISSUE THREAD

**Issue by Barina** [godotengine/godot#6909]
**Operating system or device - Godot version:**
Version compiled at 23-10-2016_00:44 (GMT+3) using Windows 7 (last commit as of now)
Operating system is Windows 7 64bit

**Issue description** (what happened, and what was expected):
Description: 
Some animation made with shaders and Tween applied to a Sprite2D.
Creating a new instance from that scene and add it as a child to the root with a background loader (inside global.gd).
The parameter "material/material:shader_param/modulate" hangs from previous scene.

Expected:
Scene reload successfully with all parameters reset to the initial state.

Result:
Sprite2D loaded with previous scene params (material/material:shader_param/modulate)

**Steps to reproduce:**
With the provided project below:
1. Click on the play button.
2. Click on the button on the right [Animate].
3. Click on the button [Reload Scene].
4. Watch the animation "get stuck" on red color (do above steps several times)

When I free the scene before recreating it' it works ok.

**Link to minimal example project** (optional but very welcome):
https://drive.google.com/open?id=0B54uADD0Gcm9QmswZ0VJb05raXc

**Comment by Barina** [comment]
PS. That didn't work either when "make unique" on both the CanvasItemMaterial and CanvasItemShader.

**Comment by bojidar-bg** [comment]
1. Resources are cached... This means that reloading a scene would load it from cache.
2. Subresources are resources as well... Thus materials are going to be cached as well

Maybe you can use `set_material(get_material().duplicate())`?

**Comment by Barina** [comment]
Doesn't "make unique" doing that for me?

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.
