### ISSUE TITLE
GLTFDocument cannot load texture from gltf file.

### ISSUE THREAD

**Issue by AllenDang** [godotengine/godot#69090]
### Godot version

4.0 Beta5

### System information

macOS v13.0

### Issue description

GLTFDocument cannot load texture from gltf file. Error message is
```
E 0:01:02:0964   _load: No loader found for resource: /Users/allen/Downloads/bevy/assets/models/FlightHelmet/FlightHelmet_Materials_RubberWoodMat_Normal.png.
  <C++ Error>    Method/function failed. Returning: Ref<Resource>()
  <C++ Source>   core/io/resource_loader.cpp:222 @ _load()
```

### Steps to reproduce

```
var file = "...some.gltf"
var gltf_doc = GLTFDocument.new()
var gltf_state = GLTFState.new()
var err = gltf_doc.append_from_file(file, gltf_state)
```

### Minimal reproduction project

N/A

**Comment by fire** [comment]
See https://github.com/AllenDang/model_explorer_godot4/issues/1 for more context.

**Comment by akien-mga** [comment]
Please be more explicit about what the bug is.

The linked issue just has screenshots and a bunch of downloads, that's not a bug report.

**Comment by akien-mga** [comment]
I can't reproduce the issue. I download the `untitled.glb` from https://github.com/AllenDang/model_explorer_godot4/files/10078226/untitled.glb.zip

I imported it in Blender, re-exported as:
- glTF Binary: `donuts-binary.glb`
- glTF Embedded: `donuts-embedded.gltf`
- glTF Separate: `donuts-separate.gltf` (+ `.bin` + textures)

All three import fine in Godot:
![image](https://user-images.githubusercontent.com/4701338/204052130-fd022dcd-3875-4df2-8b5b-465c5fbc3323.png)

**Comment by fire** [comment]
I'll create a reproduction project.

**Comment by fire** [comment]
[Uploading VSK_model_explorer.zip…]()

Drag a .gltf vs a .glb to where the label is.

Will do some tests.

**Comment by fire** [comment]
Downloaded https://github.com/godotengine/godot/commit/c7ceb94e372216b1b033d7c2ac26d5b7545c4dac and ran the game.

```powershell
.\godot.windows.editor.x86_64.console.exe --path .\VSK_model_explorer\  -e
.\godot.windows.editor.x86_64.console.exe --path .\VSK_model_explorer\ 
```

Drag a gltf to the exe.

[glTF.zip](https://github.com/godotengine/godot/files/10095000/glTF.zip)


![image](https://user-images.githubusercontent.com/32321/204053259-fec7a0c3-0b7c-4fbd-86e0-735ad24eae5c.png)

**Comment by fire** [comment]
<details>
  <summary>Patched in the pr</summary>

![image](https://user-images.githubusercontent.com/32321/204053507-1aafa791-f269-4231-8a14-5a7170bc9c92.png)
</details>

**Comment by fire** [comment]
For further detail:

Aside from the ui, the code that causes the bug is here:

```C++
func _load_gltf(file:String):
	var gltf_doc = GLTFDocument.new()
	var gltf_state = GLTFState.new()
	var err = gltf_doc.append_from_file(file, gltf_state, 1, 30)
	
	var success = false
	var gltf:Node = null
	
	if err == OK:
		success = true
		gltf = gltf_doc.generate_scene(gltf_state)
		gltf.add_to_group(GlobalSignal.GLTF_GROUP)
		call_deferred("add_child", gltf)
		
	gltf_is_loaded.emit(success, gltf)
```

The usage of GLTFDocument triggers the bug.
