### ISSUE TITLE
"HScrollBar", pull insensitive

### ISSUE THREAD

**Issue by xiaoliang6669** [godotengine/godot#69102]
000000000000000000000000000000000

**Comment by Calinou** [comment]
> not by the focus

Are you referring to keyboard navigation after focusing on the scrollbar?

**Comment by xiaoliang6669** [comment]
> > not by the focus
> 
> Are you referring to keyboard navigation after focusing on the scrollbar?
> 
> Can you reproduce this on 3.5.1?

3.0 Didn't find this problem. Please try
