### ISSUE TITLE
closing file that has been deleted crashes

### ISSUE THREAD

**Issue by androbytes** [godotengine/godot#69113]
### Godot version

4.0 beta 6

### System information

Windows 11

### Issue description

I created a file, didn't need it anymore so i deleted it and closed it in the scripts tab and godot crashed

### Steps to reproduce

Create .gd file,
Open .gd file, 
Delete .gd file,
Close it in the scripts tab

### Minimal reproduction project

N/A

Edit: this script was part of an addon

**Comment by Whimfoome** [comment]
Can't reproduce, can you give minimal reproduction project

**Comment by AnnoyingB** [comment]
i don't know how it happened though, it just randomly did when I had an addon and deleted it with a file from it still open and it crashed. Try making a folder with a gd script and delete the folder?

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
