### ISSUE TITLE
VehicleWheels default direction is inconsistent with Vector3.FORWARD

### ISSUE THREAD

**Issue by Skaruts** [godotengine/godot#69112]
### Godot version

Both Godot 3 and Godot 4

### Issue description

VehicleWheels, by default, point (and move) toward positive Z, while Godot's conception of the forward direction is toward negative Z.

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/47650.

**Comment by Skaruts** [comment]
From the title I thought that was a separate issue.
