### ISSUE TITLE
On OSX, DisplayServer.window_set_size() does not resize if `display/window/size/resizable` is false

### ISSUE THREAD

**Issue by eviltrout** [godotengine/godot#69116]
### Godot version

v4.0.beta6.official [7f8ecffa5]

### System information

Mac OSX Ventura 13.0.1

### Issue description

According to the documentation, under `WindowFlags`:

> WINDOW_FLAG_RESIZE_DISABLED = 0 --- The window can't be resizing by dragging its resize grip. It's still possible to resize the window using [window_set_size](https://docs.godotengine.org/en/latest/classes/class_displayserver.html#class-displayserver-method-window-set-size). This flag is ignored for full screen windows.

However, on OSX calling `window.set_size` does not resize the window if that flag is not set.

On Windows the resize works even if that flag is false.

### Steps to reproduce

1. Set the display/window/size/resizable to false in project settings
2. Call `DisplayServer.window_set_size`
3. The window stays the same size

A workaround which I've confirmed works it to temporarily enable the flag, change the size, then disable it:

```
	DisplayServer.window_set_flag(DisplayServer.WINDOW_FLAG_RESIZE_DISABLED, false)
	DisplayServer.window_set_size(res)
	DisplayServer.window_set_flag(DisplayServer.WINDOW_FLAG_RESIZE_DISABLED, true)
```

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by eviltrout** [comment]
`DisplayServer` doesn't exist in 3.5.1. However, I can confirm that the equivalent API of `OS.set_window_size` works correctly in Godot 3.5.1

**Comment by eviltrout** [comment]
Thanks @bruvzg - I can confirm in the latest Godot 4.0 Beta it works as expected.
