### ISSUE TITLE
Scene tree drag & drop node ends up as child

### ISSUE THREAD

**Issue by Keetz** [godotengine/godot#6912]
This is a issue that have been brought up a few times before, and has supposedly been fixed, but i am still experiencing this problem. I am running Godot 2.1 stable on Ubuntu 16.04/Windows 8.

Trying to place a node under a node already with children, it ends up as a child instead of just being moved beneath.

This doesn't happen when moving a node next to a node without children.

Example from previous issue (#4628)
https://cloud.githubusercontent.com/assets/6987027/15219243/06b74f30-1831-11e6-8e2a-f5db6e3542c4.gif

Previous issues stating this problem as reference:
#5341
#4628

**Comment by MatiasFito** [comment]
I had this issue too good to know there is a PR to fix it, awesome!.
