### ISSUE TITLE
Theme editor regression in 2.1.1 rc

### ISSUE THREAD

**Issue by pkowal1982** [godotengine/godot#6913]
**Operating system or device - Godot version:**
Ubuntu 16.04 / Windows 7 64b

**Issue description** (what happened, and what was expected):
Dialogs for adding / removing properties to / from theme have misplaced buttons.
It's working properly on 2.1 stable.

**Steps to reproduce:**
Open theme editor and then one of dialogs.

**Link to minimal example project** (optional but very welcome):
![theme_bug](https://cloud.githubusercontent.com/assets/19764492/19656032/79402080-9a1e-11e6-9b1f-86303728f9a0.png)

**Comment by akien-mga** [comment]
Fixed by #6986.
