### ISSUE TITLE
cannot receive UDP packets in Godot 4 Beta 5

### ISSUE THREAD

**Issue by GK-GreyGhost** [godotengine/godot#69136]
### Godot version

Godot 4 Beta 5

### System information

Windows 10

### Issue description

packet message is not received, no errors in Godot 4
packet message is printed in Godot 3.5

### Steps to reproduce

1. send UDP packet to port
2. Godot 3.5 prints message, Godot 4 doesn't

### Minimal reproduction project

[udp_demo_godot3_working.zip](https://github.com/godotengine/godot/files/10087390/udp_demo_godot3_working.zip)

[udp_demo_4_broken.zip](https://github.com/godotengine/godot/files/10087401/udp_demo_4_broken.zip)

**Comment by Calinou** [comment]
As per https://github.com/godotengine/godot-docs/pull/6393:

- `is_connected_to_host()` was removed from StreamPeerTCP and PacketPeerUDP as per GH-59582.
  - `get_status()` can be used in StreamPeerTCP instead.
  - `is_socket_connected()` can be used in PacketPeerUDP instead.

**Comment by GK-GreyGhost** [comment]
Thank you, I'm sorry, I don't think I understand, the linked documentation only references PacketPeerUDP and not UDPServer, should I only be using PacketPeerUDP even though I don't intend to send packets, only receive?

based on that I tried https://docs.godotengine.org/en/latest/classes/class_packetpeerudp.html#class-packetpeerudp-method-wait 

``` extends Node

var socket = PacketPeerUDP.new()

func _ready():
	
	if socket.bind(4592,"*") != OK:
		print("Failed to bind to port 4592")
		return
	else:
		print('started on port 4592')
		
	while socket.wait() == OK:
		var data = socket.get_packet().get_string_from_ascii()
		print(data)
		if data == "end":
			return
```

and can't receive any packets

**Comment by GK-GreyGhost** [comment]
documentation has been updated and everything works now, closing, thanks!
