### ISSUE TITLE
Expose curve2D data on the inspector

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#6914]
I think it could be nice to have Curve2D data exposed on the inspector to fine tune points (position, in and out) values from there, that could allow to visually animate curves too.

**Comment by Zylann** [comment]
Or have a notion of "selected point", so you could edit its properties (here, position) by typing numbers in a small text box overlaid on the main view? Have the data in the inspector would be tedious to edit if your curve is very long.

**Comment by eon-s** [comment]
@Zylann that is a must for Path, but general Curve resource can't use the visual scene editor panels(I think), I mean like ConcavePolygonShape which gives access to the segments array.

**Comment by avencherus** [comment]
Yes, it would be a useful feature.  I would like to be able to keyframe the curves of Path2D nodes in AnimationPlayers.

**Comment by Zylann** [comment]
Keyframing this is a different issue, because that would actually mean keyframing array items.

**Comment by eon-s** [comment]
@Zylann I see, I wonder if will be possible to at least keyframe special arrays like Vector2Array, but is a different issue/request, indeed.

**Comment by eon-s** [comment]
Keyframing arrays may be possible now (tested with Polygon2D), but we still have no access to Curve2D data from the inspector.

**Comment by Noshyaar** [comment]
Still relevant in latest master 3ad9e47 I think. There's no way to set point's position in the inspector.

**Comment by Zylann** [comment]
Keyframing arrays looks nice but I think it's a bit too overkill compared to the alternative of skinned 2D meshes.

**Comment by eon-s** [comment]
@Zylann probably, but it can be done currently (but manually), the point is to expose curve data to be able to edit and not having to save the curve resource and edit with a text editor it its horrible formatting.

**Comment by sketchyfun** [comment]
I've just looked into this and it seems a bit tricky currently. I exposed the curve point data to the inspector, but it's stored as a dictionary, which isn't the nicest thing to edit via the inspector, and also you can only keyframe the dictionary itself, not the contents (even doing this, the values wouldn't interpolate between frames when I tested it). I think the curve data would need to be stored as an array, although it would have to be an array for point positions and also an array for both curve in and curve out data. Obviously this is less than ideal, so a better solution would be needed. In addition to all this, I believe updating the curve in real-time can be a little slow at the moment as it attempts to bake the data (not sure if it does this every time it changes, but it wouldn't surprise me)

**Comment by eon-s** [comment]
@sketchyfun more than to animate the curve, the need to see the data is to edit it, editing the resource is too complex because has a terrible formatting and that is why we have an Inspector anyway...

**Comment by sketchyfun** [comment]
Yeah I agree that being able to edit the data via the inspector would be nice as well

**Comment by Xrayez** [comment]
The data is a sequence of `in-out-vertex-in-out-vertex...`. I think we just need to get rid of the dictionary representation of the data and use a simple `PoolVector2Array` for that as exposed `data` property... This means breaking compatibility, but it's 4.0 time!

**Comment by panorb** [comment]
Are there any updates on this? Is something in the works?

**Comment by Calinou** [comment]
@panorb As far as I know, nobody is currently working on this.

Either way, I'll close this issue as it has been superseded by https://github.com/godotengine/godot-proposals/issues/48. (Feature proposals are now tracked in the Godot proposals repository.)
