### ISSUE TITLE
Double-click project file to open it in Godot

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#6915]
One of the usability problems that still remain is that it's a bit hard to open a project directly from the file explorer with Godot. You can open through command line or create a custom shortcut for each project, but it's cumbersome.

Since for 3.0 the project file will change name, might be a good opportunity to change this behavior.

**My proposal:**
- Change the `engine.cfg` to a file with custom extension, like `project.gdp` (`.gdp` for Godot Project, open to suggestions of course).
- Change the command line to accept a `.gdp` directly, without `-path` specifier (currently the expected argument is the starting scene path).
- Run the editor by default if it's a `tools=yes` binary.

This will allow the file to be associated with Godot and even be dragged & dropped over the Godot executable to open it. Also, it'll be possible to use a custom icon for Godot projects. It'll enable the recent file list on Windows, like my idea in #5653 and some other OS-specific possibilities.

**Comment by funabab** [comment]
I will also like this to be implemented, but at the same time keeping engine.cfg for backwards compatibility (for sometime)

**Comment by vnen** [comment]
@funabab `engine.cfg` will be removed anyway (it's already in the plans). We don't want Godot 3 opening projects from Godot 2. Instead, we will add a one-way project converter in a Godot 2.x version.

**Comment by williamd1k0** [comment]
While this is not implemented (+1 for this feature) I'm using a very very simple tool that I wrote in python (binary for windows only).

I hope this can be implemented soon (I don't have any C++ skills to help 😞  ).

Download and usage info: https://github.com/williamd1k0/godot-sandbox/tree/master/gdproj

**Comment by vnen** [comment]
Reactions does not give notifications, only now I noticed that this is quite a wanted feature. I hope I can lobby @reduz for this when we start breaking stuff.

**Comment by williamd1k0** [comment]
Yup, reactions does not give notifications but at least you can filter using reactions:

![image](https://cloud.githubusercontent.com/assets/10428035/20947324/c882aa7a-bbf5-11e6-8177-9ae285e41d79.png)

**Comment by vnen** [comment]
Reopening since #8375 was reverted by #8579.
