### ISSUE TITLE
Random `InputEventJoypadMotions` created when joypad not connected

### ISSUE THREAD

**Issue by bend-n** [godotengine/godot#69153]
### Godot version

4.0b6

### System information

ArchLinux x11 AwesomeWM xinput

### Issue description

`InputEventJoypadMotion` and `InputEventJoypadButton`s spammed when no joypad connected.
`Input.get_connected_joypads()` returns `[0]`.
The device name is `HTIX5288:00 0911:5288 Touchpad` even when im using a mouse 🤔 

Video attached: <sup>(during which time I only move the mouse around, although I do press a few keys at times.)</sup>

https://user-images.githubusercontent.com/70787919/203897692-41bd323d-f389-442a-92f6-36215bc6d97a.mp4

I first noticed this problem when trying to assign InputMap binds, when I clicked the thing to filter by `InputEvent` it kept trying to make it a left joystick motion.
This could be a hardware issue, but I can play other games fine, and I dont move involuntarily.
Also, it recieves this input even when the window is not focused.

### Steps to reproduce

- make script
- `func _input(e): print(e)`
- observe

### Minimal reproduction project

[mrp](https://github.com/godotengine/godot/files/10088478/bug.zip)

**Comment by snougo** [comment]
can't reproduce issue on Mac with Xbox one controller (bluetooth mode)

**Comment by bend-n** [comment]
No like, it happens *without* a controller.

**Comment by bend-n** [comment]
duplicate of #59250 i think
