### ISSUE TITLE
[4.0]Pressing Enter to ensure the changging of Inspector property will suddenly change the interface focus from Inspector to Node

### ISSUE THREAD

**Issue by snougo** [godotengine/godot#69160]
### Godot version

4.0 beta4/beta5/beta6

### System information

macOS 11.7.1 Intel-iris-GPU Forward+  and Mobile 

### Issue description

when pressing Enter to ensure the changging of Inspector will suddenly change the interface focus from Inspector to Node, it's really annoying.

https://user-images.githubusercontent.com/64188282/203937756-fb0e6132-a5a6-4f29-a803-6ba3c186f6c2.mov

### Steps to reproduce

pick up a node
change inspector property
press enter

### Minimal reproduction project

[Uploading Godot4Beta5Mobile.zip…]()

**Comment by felixkriechbaum** [comment]
This is really annoying, every time I change a value and want to save it I have an S in the name of the node because the focus changes over. I've had this since I started with Godot (I think it was Godot 3.1). That's one of the reasons why I mostly work with it on Windows.

**Comment by Sauermann** [comment]
Bisecting this bug shows that it got introduced in #67397.

**Comment by PabloNeirotti** [comment]
Also have this issue in macOS Ventura 13.0.1.

I believe I didn't experience this on beta2 but now one beta6 I do.

A temporary workaround is to build the muscle memory of hitting `return` twice to confirm a change.

**Comment by snougo** [comment]
Not be fixed in beta8

**Comment by Sauermann** [comment]
As mentioned in https://github.com/godotengine/godot/pull/69234#issuecomment-1329539434, I was not certain, if that PR would solve this issue on macOS.

**Comment by snougo** [comment]
> Thanks for the feedback. As mentioned in https://github.com/godotengine/godot/pull/69234#issuecomment-1329539434, I was not certain, if that PR would solve this issue on macOS.

Let me create a new empty project  to see if it has been fixed in beta8

**Comment by snougo** [comment]
I created a new empty project in beta 8, but the issue is still there, not be fixed.

**Comment by sfaletti** [comment]
Not sure if this helps, but I have the same issue on MacOS with an M1 Max processor and have noticed weird behavior when tabbing through property fields. I'm using beta8. 

If I click on a field right after I've opened or created a scene, it will highlight as normal and I can edit it. Pressing `return` focuses on the Node per @snougo's comment. Pressing `tab` initially does nothing, but `shift+tab` will focus on the previous field in the list. After I've gone back using `shift+tab` I can go forward using `tab` but only 1 field, then `tab` has no effect again. If I back up from this point with `shift+tab` I can go forward again. Once I've done this back-and-forth dance with tab through the first section of the inspector panel it seems to work normally.

This video might explain it better. It shows me tabbing through the properties of a new `Node2D`. 

https://user-images.githubusercontent.com/2781296/208309349-df58e94c-3098-481f-9580-f9d9d717e697.mp4
