### ISSUE TITLE
PopupMenu throws errors when `radio_unchecked` is set to empty in theme

### ISSUE THREAD

**Issue by justofisker** [godotengine/godot#69161]
### Godot version

4.0.beta.6

### System information

Windows 11, Vulkan, RTX 2080 Super (516.94)

### Issue description

When overriding `PopupMenu`'s theme value `radio_unchecked`  to \<empty\> and then opening an `OptionButton` you get this error. It only occurs once.

![image](https://user-images.githubusercontent.com/37525404/203957137-ce4aa7db-1f1e-4d34-866e-1b6fe48c9952.png)

```
E 0:00:01:0004   _gdvirtual__get_width_call: Required virtual method Texture2D::_get_width must be overridden before calling.
  <C++ Source>   scene/resources/texture.h:60 @ _gdvirtual__get_width_call()
E 0:00:01:0004   _gdvirtual__get_height_call: Required virtual method Texture2D::_get_height must be overridden before calling.
  <C++ Source>   scene/resources/texture.h:61 @ _gdvirtual__get_height_call()
```

### Steps to reproduce

Override `radio_unchecked` for `PopupMenu`'s theme to \<empty\> by clicking the + icon to the left of the default value.

![image](https://user-images.githubusercontent.com/37525404/203946466-f7437b72-39ea-4077-9aa3-9cba34bfaafe.png)

Open on an `OptionButton` in a running scene.

### Minimal reproduction project

[PopupMenuIconErrorMinRepoduction.zip](https://github.com/godotengine/godot/files/10090431/PopupMenuIconErrorMinRepoduction.zip)

**Comment by KoBeWi** [comment]
The error happens here
https://github.com/godotengine/godot/blob/a9fbf3718d4f8455dee1ebad05374d7baf714370/scene/gui/popup_menu.cpp#L555-L556
I tried guarding it with `check[i].is_valid()` check, but the problem is that the texture is actually valid, but it's a plain Texture2D for some reason.

**Comment by justofisker** [comment]
From looking into this it seems that when loading the theme resource it loads a valid Texture2D here

https://github.com/godotengine/godot/blob/c7ceb94e372216b1b033d7c2ac26d5b7545c4dac/core/io/resource_format_binary.cpp#L820

**Comment by justofisker** [comment]
Manually forcing it not to load the Texture2D from the theme resource with this code in the same function as the above comment

```cpp
if (set_valid) {
	String sname = name;
	if (sname != "PopupMenu/icons/radio_unchecked")
		res->set(name, value);
}
```

Gets rid of the error. So it is definitely to do with theme resource saving/loading

**Comment by justofisker** [comment]
After even further looking into this it seems like somehow the theme resource has a sub-resource of a plain Texture2D for the value of `PopupMenu/icons/radio_unchecked` and I cannot reproduce the error anymore.

```
[gd_resource type="Theme" load_steps=2 format=3 uid="uid://iht1l1bgm18h"]

[sub_resource type="Texture2D" id="Texture2D_5tucc"]
resource_local_to_scene = false
resource_name = ""

[resource]
PopupMenu/font_sizes/font_separator_size = 16
PopupMenu/font_sizes/font_size = 16
PopupMenu/icons/radio_unchecked = SubResource("Texture2D_5tucc")
```

This might've been an error of a previous version of Godot 4 as I'm often new versions as they come out and build some myself inbetween betas. So with this I'm closing this issue.
