### ISSUE TITLE
Godot editor prevents screen from going to sleep

### ISSUE THREAD

**Issue by Uxeron** [godotengine/godot#69167]
### Godot version

v4.0.beta6.official [7f8ecffa5]

### System information

Windows 10

### Issue description

While the Godot editor is open, the screen will never go to sleep and will always remain ON. 
This seems to be caused by the setting `display/window/energy_saving/keep_screen_on` being enabled by default. This makes sense for a game, however, it's enabled for the editor too, with no way to disable it.

### Steps to reproduce

Check your screen sleep delay (on Windows 10: Settings -> System -> Power & sleep)
Open the Godot editor and leave the computer idle for a while.
Notice how the screen remains awake, even after enough time has passed.

Alternatively

Run `powercfg /requests` in Windows command prompt.
Notice that it mentions "Godot Engine running with display/window/energy_saving/keep_screen_on = true" under [DISPLAY], while referencing the editor executable by path.

![image](https://user-images.githubusercontent.com/31929029/203995737-c8a58f28-d8f1-4c7f-b210-28a3cfed23ec.png)

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Can you reproduce this on 3.5.1?

**Comment by Uxeron** [comment]
I cannot reproduce this on 3.5.1, the screen turns off properly and `powercfg` does not report any locking.

**Comment by RedMser** [comment]
There is an `editor` feature override for this setting, but it is not handled by the editor. See #64100

**Comment by Calinou** [comment]
I can confirm this on 4.0.beta8 (Linux).

**Comment by vancura** [comment]
The same issue is on macOS (`v4.0.beta10.mono.official [d0398f62f]` on macOS `13.2`). It prevents monitor sleep when the screensaver runs; even LoginWindow can't get the screen to sleep.

**Comment by Calinou** [comment]
> There is an `editor` feature override for this setting, but it is not handled by the editor. See #64100

This can be fixed by disregarding the setting within the editor, and removing the `.editor` override. In general, I think running the project from the editor is expected to prevent sleeping. What shouldn't prevent sleeping is the editor itself.

**Comment by Uxeron** [comment]
Fixed by #71325.
