### ISSUE TITLE
_gdvirtual__get_height_call: Required virtual method Texture2D::_get_height must be overridden before calling

### ISSUE THREAD

**Issue by Intervel** [godotengine/godot#69162]
### Godot version

beta 6

### System information

Windows 11

### Issue description

whenever i call  TranslationServer or DisplayServer. godot will throws this error:

### Steps to reproduce

E 0:00:02:0199   _gdvirtual__get_height_call: Required virtual method Texture2D::_get_height must be overridden before calling.
  <C++ Source>   scene/resources/texture.h:61 @ _gdvirtual__get_height_call()

E 0:00:02:0199   _gdvirtual__get_width_call: Required virtual method Texture2D::_get_width must be overridden before calling.
  <C++ Source>   scene/resources/texture.h:60 @ _gdvirtual__get_width_call()

is this a bug or im doing something wrong. here is my code :

DisplayServer.window_set_mode()

E 0:00:02:0043   _ready: Required virtual method Texture2D::_get_height must be overridden before calling.
  <C++ Source>   scene/resources/texture.h:61 @ _gdvirtual__get_height_call()
  <Stack Trace>  config.gd:202 @ init_screen_mode()
                 config.gd:400 @ init_config()
                 config.gd:415 @ _ready()

E 0:00:02:0043   _ready: Required virtual method Texture2D::_get_width must be overridden before calling.
  <C++ Source>   scene/resources/texture.h:60 @ _gdvirtual__get_width_call()
  <Stack Trace>  config.gd:202 @ init_screen_mode()
                 config.gd:400 @ init_config()
                 config.gd:415 @ _ready()

### Minimal reproduction project

nothing

**Comment by akien-mga** [comment]
Related to #69161.

**Comment by Calinou** [comment]
@Intervel Can you reproduce this in an empty project? If not, please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by Intervel** [comment]
@Calinou just opened it yesterday on beta 7, somehow the errors did not occured. i think i will close this ones. so you guys can focus on the other.
