### ISSUE TITLE
O app fecha quase toda hora

### ISSUE THREAD

**Issue by Joelph860** [godotengine/godot#69175]
### Godot version

3.5.1

### System information

SnapDragon 860 - 6gb Ram - Android 11 , MIUI 12.5

### Issue description

[Watch this video the guy says everything he needs to improve ](https://youtu.be/oFBZlyiMVrQ) 

### Steps to reproduce

.

### Minimal reproduction project

.

**Comment by akien-mga** [comment]
This tracker is for reproducible and actionable bug reports. A video in Portuguese (which most of our contributors can't understand) with no further explanations is not a bug report.

If this video outlines some bugs, someone needs to do the effort and write them down with reproduction steps / a reproduction project, so our contributors can understand the issue, reproduce it, and fix it.
