### ISSUE TITLE
Add more file format for saving/loading data ?

### ISSUE THREAD

**Issue by linkpy** [godotengine/godot#6917]
Currently we got the `File` class allowing [encrypted] binary saving and the `Dictionary` JSON methods. But why don't add more human friendly data format ? Like YAML ? Or add more used format like XML ?

The YAML can be very useful with game allowing simple modding. The YAML and the XML can also be used for debugging purpose.

It's just a proposal, and I know there are already an XMLParser, but not documented and doesn't allow writing XML data. Maybe also add an option for pretty-printing JSON ?

**Comment by vnen** [comment]
There's a request for YAML already (#4354). A XMLWriter could be useful (though JSON is much more easy to handle). I don't like adding qny other method beyond that, it makes things too complex.

**Comment by linkpy** [comment]
I think just adding and option for pretty printing JSON will be great. After this, having binary, JSON, YAML and XML will be quiet enough yes. I don't like the current JSON because `Array` should have `to_json` method and another object `JSON` may be added with a `parse` function.

**Comment by Sslaxx** [comment]
Supporting Godot's version of ToML would be nice at the least.

**Comment by linkpy** [comment]
TOML seems cool yes

**Comment by Sslaxx** [comment]
It's also the file format used for scenes and .tres files.

**Comment by hetdegon** [comment]
Human-formatted JSON and ToML would be pretty interesting to have, personally.

**Comment by naturally-intelligent** [comment]
How are so many developers getting by with a file format that doesn't support integer array indexes?

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Sslaxx** [comment]
Adding ToML support to 3.1 would be nice.

**Comment by keito940** [comment]
> Adding ToML support to 3.1 would be nice.
Since. .tscn is also TOML based, is not it possible to go?

**Comment by Calinou** [comment]
@keito940 `.tscn` is *inspired* by TOML, but it does not follow [the TOML specification](https://github.com/toml-lang/toml).

**Comment by Sslaxx** [comment]
To be more accurate, then, support for being able to read/write `.tscn` files from within a Godot-made application.

**Comment by akien-mga** [comment]
We already have support for `ConfigFile` (INI-style, similar to TOML), and JSON. There's a popular feature proposal for YAML support (#4354). I don't think we need to keep a generic feature proposal regarding adding unspecified file formats, we only add features when they have a clear scope and use case.
