### ISSUE TITLE
Write to `DEPTH` built-in breaks depth testing when assignment is not executed

### ISSUE THREAD

**Issue by Flarkk** [godotengine/godot#69184]
### Godot version

3.5.2

### System information

Ubuntu 22.04

### Issue description

Writing to `DEPTH` in a fragment shader breaks depth testing even though the assignment is not actually executed.
Objects the shader operates onto flicker back and forth as if their depth was randomly shuffled from one frame to another.

```glsl
shader_type spatial;
render_mode unshaded;

uniform bool flag = false;
uniform vec4 albedo : hint_color;

void fragment() {
	if(flag) DEPTH = 1.0; // Never executed
		
	ALBEDO = albedo.rgb;
}
```

### Steps to reproduce

See MRP

### Minimal reproduction project

[DEPTH_unreachable_branch.zip](https://github.com/godotengine/godot/files/10095114/DEPTH_unreachable_branch.zip)

**Comment by clayjohn** [comment]
That is expected, if you write to ``DEPTH`` in any branch in your shader, you become responsible for setting ``DEPTH`` in _all_ branches. If you don't, OpenGL leaves ``DEPTH`` with uninitialized memory which is what you are seeing. 

This is a limitation placed on us by the OpenGL specification. So there is nothing we can do other than document this behaviour in our documentation.

**Comment by Flarkk** [comment]
Thanks @clayjohn.
Let's then assume I want to set `DEPTH` in the other branch, as if it was natively provided by OpenGL.

I assume I can't just do `FRAGCOORD.z / FRAGCOORD.w` because according to the documentation, `FRAGCOORD.z` will be neither initialized precisely because I set `DEPTH` in the other branch.

Would something like `VERTEX.z / FRAGCOORD.w` be valid instead ?

Thank you for your help, it's very much appreciated !

**Comment by Flarkk** [comment]
I've figured it out.
The right way to do it is :

```glsl
vec4 ndc = PROJECTION_MATRIX * vec4(VERTEX, 1.0);
DEPTH = (ndc.z / ndc.w) * 0.5 + 0.5;
```

**Comment by Calinou** [comment]
Does Vulkan also behave this way?

**Comment by htw6174** [comment]
Trying to do the same thing with godot 4.0.3 with forward+ I've found that `ndc.z / ndc.w` is in the (0..1) range already, so @Flarkk 's solution should be simplified to:
```glsl
vec4 ndc = PROJECTION_MATRIX * vec4(VERTEX, 1.0);
DEPTH = ndc.z / ndc.w;
```

**Comment by celyk** [comment]
> I assume I can't just do `DEPTH = FRAGCOORD.z` because according to the documentation, `FRAGCOORD.z` will be neither initialized precisely because I set `DEPTH` in the other branch.

The spec says you can.
https://registry.khronos.org/OpenGL/specs/es/3.0/GLSL_ES_Specification_3.00.pdf#page=89
> The z component is the depth value
> that would be used for the fragment’s depth if no shader contained any writes to gl_FragDepth. This is
> useful for invariance if a shader conditionally computes gl_FragDepth but otherwise wants the fixed
> functionality fragment depth.

Example:
```glsl
if(flag) DEPTH = 1.0;
else DEPTH = FRAGCOORD.z;
```

**Comment by Flarkk** [comment]
@MJacred I think the description of `FRAGCOORD` is still confusing reagrding @celyk 's last comment :
https://github.com/godotengine/godot-docs/blob/2e93680fe50655d5d5474b1bbf3b2a8b39c742a3/tutorials/shaders/shader_reference/spatial_shader.rst?plain=1#L246C1-L249C142

I would suggest to change it to something like :

> Coordinate of pixel center in screen space. ``xy`` specifies position in window, ``z`` specifies fragment depth. Origin is lower-left. **``z`` is used as the output value for the fragment depth unless ``DEPTH`` is written to**.
