### ISSUE TITLE
Linux with Intel HD Graphics - Godot 4 beta 6 project manager and confirmation dialog using OpenGL3 is empty 

### ISSUE THREAD

**Issue by MetalMaxMX** [godotengine/godot#69192]
### Godot version

4.0 beta 6

### System information

Debian 11, GLES3, Intel HD Graphics 2000 (SNB GT1)

### Issue description

Hi! I'm having a similar issue to https://github.com/godotengine/godot/issues/68760 with the difference that I am using Linux and running an OpenGL3 instance of the project. 

I would like to mention that both OpenGLES2 and 3 work on my machine when using Godot 3 so I can safely confirm that prior to Godot 4 it can reproduce this. I have the exact same blank window and confirmation dialog in Godot 4 as the issue described there. I was unsure if making a github issue about this since it already exists was worthy but since that one dealt specifically with macOS machines, I wanted to make this one for Linux-based computers. 

### Steps to reproduce

Open the project as normal and the issue appears.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
>  Intel HD Graphics 2000 (SNB GT1)

These integrated graphics don't have *any* OpenGL 3.3 support on Windows, and their OpenGL 3.3 support on Linux is known to be poor. I'm afraid we can't support those reliably.
