### ISSUE TITLE
Parser Error: When trying to run (F5) a project

### ISSUE THREAD

**Issue by produno** [godotengine/godot#69213]
### Godot version

4.0 Beta 6

### System information

Windows 11

### Issue description

When trying to run my project with F5 it halts with Parse Error:
The only information shown is in the console as follows. 

> E 0:00:02:0469   GDScriptCompiler::_populate_class_members: Condition "!base->is_valid()" is true. Returning: ERR_BUG
  <C++ Source>   modules\gdscript\gdscript_compiler.cpp:2287 @ GDScriptCompiler::_populate_class_members()

My project is fairly large and runs fine in Beta 5.

in case it helps heres the log when loading up the project:

> Godot Engine v4.0.beta6.official.7f8ecffa5 - https://godotengine.org
OpenGL Renderer: NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2
Editing project: C:/SpaceSlog Game/SpaceSlog
Godot Engine v4.0.beta6.official.7f8ecffa5 - https://godotengine.org
Vulkan API 1.2.0 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1080 Ti
ERROR: Non-existent native base class.
   at: (modules/gdscript/gdscript_analyzer.cpp:4052)
ERROR: Non-existent native base class.
   at: (modules/gdscript/gdscript_analyzer.cpp:4052)
ERROR: Non-existent native base class.
   at: (modules/gdscript/gdscript_analyzer.cpp:4052)
ERROR: Non-existent native base class.
   at: (modules/gdscript/gdscript_analyzer.cpp:4052)
ERROR: Non-existent native base class.
   at: (modules/gdscript/gdscript_analyzer.cpp:4052)
ERROR: Non-existent native base class.
   at: (modules/gdscript/gdscript_analyzer.cpp:4052)
ERROR: Non-existent native base class.
   at: (modules/gdscript/gdscript_analyzer.cpp:4052)
ERROR: Non-existent native base class.
   at: (modules/gdscript/gdscript_analyzer.cpp:4052)
ERROR: Non-existent native base class.
   at: (modules/gdscript/gdscript_analyzer.cpp:4052)
ERROR: Non-existent native base class.
   at: (modules/gdscript/gdscript_analyzer.cpp:4052)
ERROR: Non-existent native base class.
   at: (modules/gdscript/gdscript_analyzer.cpp:4052)
ERROR: Non-existent native base class.
   at: (modules/gdscript/gdscript_analyzer.cpp:4052)
ERROR: Non-existent native base class.
   at: (modules/gdscript/gdscript_analyzer.cpp:4052)
ERROR: Non-existent native base class.
   at: (modules/gdscript/gdscript_analyzer.cpp:4052)
ERROR: Non-existent native base class.
   at: (modules/gdscript/gdscript_analyzer.cpp:4052)
ERROR: Non-existent native base class.
   at: (modules/gdscript/gdscript_analyzer.cpp:4052)
ERROR: Condition "!base->is_valid()" is true. Returning: ERR_BUG
   at: _populate_class_members (modules/gdscript/gdscript_compiler.cpp:2287)
ERROR: Non-existent native base class.
   at: (modules/gdscript/gdscript_analyzer.cpp:4052)
ERROR: Condition "!base->is_valid()" is true. Returning: ERR_BUG
   at: _populate_class_members (modules/gdscript/gdscript_compiler.cpp:2287)
ERROR: Condition "!base->is_valid()" is true. Returning: ERR_BUG
   at: _populate_class_members (modules/gdscript/gdscript_compiler.cpp:2287)
ERROR: Condition "!base->is_valid()" is true. Returning: ERR_BUG
   at: _populate_class_members (modules/gdscript/gdscript_compiler.cpp:2287)
ERROR: Condition "!base->is_valid()" is true. Returning: ERR_BUG
   at: _populate_class_members (modules/gdscript/gdscript_compiler.cpp:2287)
ERROR: Condition "!base->is_valid()" is true. Returning: ERR_BUG
   at: _populate_class_members (modules/gdscript/gdscript_compiler.cpp:2287)
ERROR: Condition "!preset.is_valid()" is true. Continuing.
   at: load_config (editor/export/editor_export.cpp:206)
ERROR: Condition "!d.has("handle_modes")" is true. Returning: false
   at: _set (scene/resources/animation.cpp:319)

### Steps to reproduce

Unfortunately i cannot help much as my project is fairly large. I have tried to narrow the issue down but cannot.  Any help with this would be appreciated.

### Minimal reproduction project

Please see above.

**Comment by tinmanjuggernaut** [comment]
You might have a cyclic reference in your code, which used to produce CRC errors and now presents `Condition "!base->is_valid()" is true` for me. The error is not locatable in GDScript, so perhaps you can think about where you are introducing cyclic references and untype the variables. See https://github.com/godotengine/godot/pull/67714#issuecomment-1328076248

**Comment by adamscott** [comment]
CC @rune-scape

**Comment by produno** [comment]
> You might have a cyclic reference in your code, which used to produce CRC errors and now presents `Condition "!base->is_valid()" is true` for me. The error is not locatable in GDScript, so perhaps you can think about where you are introducing cyclic references and untype the variables. See [#67714 (comment)](https://github.com/godotengine/godot/pull/67714#issuecomment-1328076248)

Your issue seems very similar to mine, though i have no idea where the cyclic reference is, unless it also refers to places where i check class types with `x is class`.

There are currently no cyclic reference errors whilst using Beta 5.

**Comment by issork** [comment]
@adamscott Just ran into the same issue and managed to create a MRP, hope it helps!

[MRPCyclicRef.zip](https://github.com/godotengine/godot/files/10098268/MRPCyclicRef.zip)

**Comment by issork** [comment]
I ran into the issue as well and managed to create a MRP.

[MRPCyclicRef.zip](https://github.com/godotengine/godot/files/10098287/MRPCyclicRef.zip)

**Comment by adamscott** [comment]
@issork Thanks for the MRP! It really helped pinning down the issue.

If you could test my PR, it would be great. When the Github action will finish, you will be able to download the artifacts to test, if you don't feel to build from source.

**Comment by issork** [comment]
The PR seems to fix the issue for me, I can run my project again. Thanks!

**Comment by rune-scape** [comment]
it seems like something may be going wrong in the analyzer? `ERROR: Condition "!base->is_valid()" is true. Returning: ERR_BUG` may be caused by the `"Non-existent native base class."` error

**Comment by rune-scape** [comment]
@adamscott had it right (nice job)
the other error in the analyzer is also a side effect of allowing cyclic references
