### ISSUE TITLE
Godot suggest to drop sprite as sibling to root node

### ISSUE THREAD

**Issue by seppoday** [godotengine/godot#69219]
### Godot version

Godot 4.0 Beta 6

### System information

Windows 10

### Issue description

Godot suggest to drop sprite as sibling to root node, while it is impossible to make it as a sibling. In that case when I hold SHIFT, Godot just ignores it. It probably should not show that suggestion when root node is selected?
![image](https://user-images.githubusercontent.com/62170071/204100502-9439e467-b3f1-4dda-9ee9-ba53a52bab83.png)

### Steps to reproduce

-

### Minimal reproduction project

-

**Comment by dkleitsas** [comment]
Hi, I don't believe anyone is working on this so I'd love to give it a crack! First time contributing to anything open source and this seems like a good place to start.

**Comment by AThousandShips** [comment]
It's controlled from here for anyone wanting to solve: https://github.com/godotengine/godot/blob/860884bde7/editor/plugins/canvas_item_editor_plugin.cpp#L5498
