### ISSUE TITLE
PAUSE_MODE_PROCESS Doesn't Inherit when Set From Code in Certain Situations

### ISSUE THREAD

**Issue by Gastronok** [godotengine/godot#6921]
**Operating system or device - Godot version:**
Godot 2.1 Stable, Win64

**Issue description** (what happened, and what was expected):
I've got menus whose pause mode are adjusted in code. I have a Panel which has PAUSE_MODE_INHERIT by default, but is set to PAUSE_MODE_PROCESS in _ready(). It has an ItemList child which has PAUSE_MODE_INHERIT. Even though the code reports get_pause_mode() of then Panel as PAUSE_MODE_PROCESS from within the code, the ItemList acts as though paused. If I set the Panel to PAUSE_MODE_PROCESS in the editor, it behaves as it should.

The expectation is that any nodes with PAUSE_MODE_INHERIT that are immediate children of nodes with PAUSE_MODE_PROCESS should not behave as though they're paused.

**Steps to reproduce:**
Create a Panel, set it to PAUSE_MODE_INHERIT. Have its _ready() function call set_pause_mode(PAUSE_MODE_PROCESS). Give it an ItemList child with PAUSE_MODE_INHERIT, and add_item("Anything") to the ItemList.

Run the application and have it pause (possibly via a _ready() function). You will not be able to click on the ItemList item, even though it has PAUSE_MODE_INHERIT and its parent has PAUSE_MODE_PROCESS.

**Link to minimal example project**:
Here's an example demonstrating the difference between a parent with PAUSE_MODE_PROCESS set in the editor and PAUSE_MODE_PROCESS set in code.

![example](https://cloud.githubusercontent.com/assets/10686700/19708168/7df38474-9ad1-11e6-828b-260d84dd64b8.png)

Both panels report a get_pause_mode() of 2 at runtime, but only the ItemList whose parent was set to PAUSE_MODE_PROCESS in the editor is selectable.

Here's the project example: 
[Example.zip](https://github.com/godotengine/godot/files/552010/Example.zip)

**Comment by akien-mga** [comment]
Fixed by #8663.
