### ISSUE TITLE
Impossible to limit frames, neither with v-sync, nor with max fps nor Nvidia limits, in Godot 4.0

### ISSUE THREAD

**Issue by Bucham** [godotengine/godot#69218]
### Godot version

4.0 

### System information

Windows 11.CPU AMD Rizen 9 5950 ,GPU Nvidia RTX 3060 , 32g RAM

### Issue description

Godot 4.0 does not limit the frames, neither by activating v-sync nor max fps. I have tried it in the last 4.0 beta versions, and none does it in my case. Unlike the 3.x versions that do limit them correctly. I have tried managing the nvidia settings and it does limit or not limit the fps in all other programs, but not in Godot 4.0. Godot 4.0, in my case, does not limit the fps with any of the commented options, my fps are allways over 300.

### Steps to reproduce

Open a new godot 3d project. Activate the frame limiting option or the v-sync option or both at the same time. Press the option to see frame time of the 3d view button.

### Minimal reproduction project

Open a new godot 3d project. Activate the frame limiting option or the v-sync option or both at the same time. Press the option to see frame time of the 3d view button.

**Comment by clayjohn** [comment]
The frame time option in the 3D view prints how long it takes to get from the first render command to the last. It does not necessarily include the time waiting for Vsync (although on some systems it does depending on how the drivers implement vsync). Therefore, the FPS label is misleading, as you are not necessarily actually rendering that many frames, it's more like you _could_ render that many frames in the absence of vsync. 

I believe the "print FPS" option in the project settings does a better job at accurately reporting FPS. If that doesn't work, see if you have NVidia tools that will do a screen overlay with FPS and other frame stats. This will be the most accurate measurement you can get.

**Comment by Bucham** [comment]
Ah, I understand, I had not found anything about that. I haven't said anything then. Thank you very much for your answer and best regards.
