### ISSUE TITLE
Unable to add a custom icon to a GDExtension's custom node

### ISSUE THREAD

**Issue by 98teg** [godotengine/godot#69212]
### Godot version

Godot_v4.0-beta6

### System information

Any OS

### Issue description

I was wondering if this should be a proposal instead, but I consider it a regression since you were able to do it in Godot 3.x, for example:
```
[gd_resource type="NativeScript" load_steps=2 format=2]

[ext_resource path="res://addons/native_dialogs/bin/native_dialogs.gdnlib" type="GDNativeLibrary" id=1]

[resource]
resource_name = "native_dialog_message"
class_name = "NativeDialogMessage"
library = ExtResource( 1 )
script_class_icon_path = "res://addons/native_dialogs/icons/native_dialog_message.png"
```
I've been looking into open PRs and a bit through the code, but this doesn't seem to be implemented. If it is, it would be nice to add it [here](https://github.com/godotengine/godot-docs/pull/6212). If it needs to be added, I think taking an approach similar to [that of modules](https://docs.godotengine.org/en/latest/development/cpp/custom_modules_in_cpp.html#adding-custom-editor-icons) would be nice.

### Steps to reproduce

Any GDExtension project.

### Minimal reproduction project

Any GDExtension project.

**Comment by narren96c** [comment]
Perhaps, it could be done similarly as it is done in engine module development.  An "icons/" folder would hold svg files for the class icons. Each file named after the class it represents. And those assets would be embedded into the compiled lib. Is this possible?
