### ISSUE TITLE
`ColorPicker`'s pick color from editor tool isn't working

### ISSUE THREAD

**Issue by hani09876** [godotengine/godot#69211]
### Godot version

Godot 4 beta 5 ,d

### System information

windows11

### Issue description

the color picker tool isnt working

_(busquad edit)_ This one:
![Godot_v4 0-beta6_win64_MHpVcocUlQ](https://user-images.githubusercontent.com/9283098/204111397-273f38d7-3843-48db-a909-85c7f175f828.png)

### Steps to reproduce

dont have idea

### Minimal reproduction project

you can check it by trying to use the color picker tool to pick a color

**Comment by Castro1709** [comment]
yeap seems to not be working in beta 6 either, when you click in any part of the editor to pick the color, the color dosen't get updated

**Comment by kleonc** [comment]
Works in v4.0.beta3.official [01ae26d31].
Doesn't work in v4.0.beta4.official [e6751549c] and later (`master` as of [68e3f49157b10b87504a88fc31d15c4d1c691ead]).

**Comment by KoBeWi** [comment]
Duplicate of #68979
