### ISSUE TITLE
reload_current_scene crashes the game

### ISSUE THREAD

**Issue by AndreaTerenz** [godotengine/godot#69227]
### Godot version

4.0beta6

### System information

Windows 11 22H2, Vulkan API 1.2.0, NVIDIA GeForce MX110

### Issue description

When reloading (aka restarting) the current scene with `get_tree().reload_current_scene()` the game just crashes. Using the code below, it seems that the "restart" action registers as just-pressed over and over instead of just once before restarting. 

### Steps to reproduce

Create an empty project and, for the sake of this example, add an InputAction "restart" (I used the R key to trigger it but that's not the point, clearly).
Then use this code to handle such action when it is just pressed:

```gdscript
func _input(event):
	if Input.is_action_just_pressed("restart"):
		print("restarting") # This will be printed over and over
		get_tree().reload_current_scene()
```

### Minimal reproduction project

[CrashTest.zip](https://github.com/godotengine/godot/files/10096923/CrashTest.zip)

**Comment by Sauermann** [comment]
As a workaround use:
``` gdscript
func _input(event):
	if event is InputEventKey:
		var e: InputEventKey = event as InputEventKey
		if e.is_action_pressed("quit"):
			print("quitting")
			get_tree().quit()
		if e.is_action_pressed("restart"):
			print("restarting")
			get_tree().reload_current_scene()
```

**Comment by AndreaTerenz** [comment]
I can confirm that this is actually an input issue: I tried triggering the reload with an Area node and it reloaded just fine (in beta7)

**Comment by KoBeWi** [comment]
Using `Input.is_action_just_pressed()` inside `_input()` is wrong, because you are ignoring the event and assume that the action you are checking is the event that arrived. Multiple events can happen in a single frame, which breaks this logic. Sauermann's comment is not a workaround, it's a correct usage of actions inside `_input()` (although you only need `event.is_action_pressed()`).
