### ISSUE TITLE
GDScript 2.0: Typed Arrays raise @implicit_new error with preloaded classes

### ISSUE THREAD

**Issue by RoniPerson** [godotengine/godot#69233]
### Godot version

v4.0.beta6.official [7f8ecffa5]

### System information

Windows

### Issue description

Not a duplicate of #58203

When using a preloaded class as type hint for a typed Array godot gives the following error:
```
@implicit_new: Script class can only be set together with base class name
```

### Steps to reproduce

- add a script `a.gd` without content to your project
- add a script `b.gd` with the following content
```swift
extends Node

const A := preload("res://a.gd")

var list: Array[A] = []
```
- attach `b.gd` to your main scene
- run the project

### Minimal reproduction project

[typed_array_bug.zip](https://github.com/godotengine/godot/files/10097091/typed_array_bug.zip)

**Comment by dalexeev** [comment]
The bug is not reproduced in 4.0.3.

![](https://github.com/godotengine/godot/assets/47700418/25e2e022-d8e6-4b17-9512-812aa5ffce78)

This should probably be added to the tests to avoid regressions in the future.
