### ISSUE TITLE
Camera rotation using Node3D does not wrap 0 and 360 to same camera view

### ISSUE THREAD

**Issue by StoreBoughtRocketGames** [godotengine/godot#69231]
### Godot version

4.0 dev Beta 6

### System information

Windows 10, Vulkin

### Issue description

When adding a wrapf from 0.0 to 360.0 to the rotation ( you can see this in the Camera.gd script attached to the CameraRoot node in the LowpolyPlayerRigged scene) the camera is rotated to a different position when the rotation wraps to 0.0 versus 360.0

### Steps to reproduce

To reproduce this issue, rotate the camera from 0 to 360 back and forth slowly. There's a print statement attached, so it should be easy to see where the rotation angle is at to reproduce this. This doesn't occur if I remove the wrapf function, but it's probably unrelated to wrapf because I can produce the same behavior by writing an if elif statement to wrap the angle myself. I've done this exact thing in Godot 3 before and the rotation is not discontinuous.

### Minimal reproduction project

[TestProject.zip](https://github.com/godotengine/godot/files/10097043/TestProject.zip)

**Comment by kleonc** [comment]
`Node3D.rotation` is in radians, not degrees. Docs:
https://github.com/godotengine/godot/blob/e29b982dbf06fb7bb32257642687df5093d7327c/doc/classes/Node3D.xml#L286-L289

So you'd need to `wrapf` between `0` and `TAU` (which is equivalent to `deg_to_rad(360)`).
https://github.com/godotengine/godot/blob/e29b982dbf06fb7bb32257642687df5093d7327c/modules/gdscript/doc_classes/%40GDScript.xml#L257-L259

No bug in here, closing.

**Comment by StoreBoughtRocketGames** [comment]
Why did rotation get changed to radians from degrees? That's so unintuitive.

**Comment by kleonc** [comment]
> Why did rotation get changed to radians from degrees?

In 3.x `Spatial.rotation` is also in radians so this hasn't changed. However, in 3.x there's also `Spatial.rotation_degrees` which can be used instead. But it was removed from `Node3D` in #50009, not sure about the reasoning. Check also #63390.
