### ISSUE TITLE
[Godot 4] Editing property in inspector triggers node rename

### ISSUE THREAD

**Issue by italodirenzo93** [godotengine/godot#69241]
### Godot version

4.0.beta6.official (7f8ecffa5)

### System information

macOS 12.6, Apple M1 Max

### Issue description

In the latest beta version of Godot 4, I've noticed that once you edit any text/number field in the inspector pane and press <kbd>RETURN</kbd>, it automatically goes to rename the node in the scene pane that the property belongs to. This usually results in accidentally renaming nodes with gibberish since it isn't immediately obvious that the text field has focus. Using keyboard shortcuts after changing properties in the inspector often leads to messing up the user's scene tree.

### Steps to reproduce

1. Create a scene
2. Place any node in the scene
3. Find a property in the inspector and type in a new value
4. Press enter
5. The node in the scene pane will have its name highlighted and the caret placed in the text field

### Minimal reproduction project

N/A

**Comment by Sauermann** [comment]
Could be a duplicate of #69160

**Comment by italodirenzo93** [comment]
Ah, yes it is a duplicate. Oops 😁

**Comment by italodirenzo93** [comment]
Confirmed duplicate of #69160
