### ISSUE TITLE
[Godot 4.0] GDScript properties break in release mode only, when combining type hints and match getters

### ISSUE THREAD

**Issue by gelvinp** [godotengine/godot#69245]
### Godot version

4.0 beta 6 official

### System information

Windows 10, also noticed on M1 MBP Mac OS 13

### Issue description

I noticed my game broke on export, but only with release builds, debug builds worked fine. The errors I get from the console are:

```
SCRIPT ERROR: Parse Error: Not all code paths return a value.
          at: GDScript::reload (res://script.gd:26)
SCRIPT ERROR: Parse Error: Not all code paths return a value.
          at: GDScript::reload (res://script.gd:40)
SCRIPT ERROR: Parse Error: Not all code paths return a value.
          at: GDScript::reload (res://script.gd:54)
ERROR: Script does not inherit from Node: res://script.gd
   at: (main/main.cpp:2755)
```

The errors show that the script does not inherit from Node (even though it `extends Node`), and that not all code paths return a value on lines 26, 40, and 54. These lines are property getters that return a `match`, all with a default `_:` block, so they all do return a value. Sample starting at line 25 below:

```
var Interact: String:
	get:
		match ActiveDevice:
			DEVICE.KEYBOARD_MOUSE:
				return "Left Mouse"
			DEVICE.SONY:
				return "X"
			DEVICE.NINTENDO:
				return "B"
			DEVICE.MICROSOFT:
				return "A"
			_:
				return ""
```

As a consequence of these errors, most of my scripts stop working and the game completely breaks. This happens when using the official release export templates, or when compiling my own release templates, and does *not* happen when running from the editor or using any debug template. In debug builds, everything works exactly as expected.

I've narrowed down the script to the minimal that breaks. The following *is* broken:

```
extends Node

var Foo: String:
	get:
		match 1:
			0:
				return "Zero"
			1:
				return "One"
			_:
				return "Something Else"
```

and by only removing the type hint, the following works fine in release mode

```
extends Node

var Foo:
	get:
		match 1:
			0:
				return "Zero"
			1:
				return "One"
			_:
				return "Something Else"
```

All of the above involves the script being an autoload, however attaching the script (with the type hint) to a node in a scene still breaks, showing a parse error (but *not* showing a "does not inherit from Node" error), and failing to execute any further, e.g. a _ready() function that prints Foo will not run.

### Steps to reproduce

1. Create a script with property that has a type hint, and a getter that uses a `match` statement to return a value.
2. Ideally, add a `_ready()` function that prints the value of the property.
3. Either add this script to a node in the scene, or set it to be an autoload.
4. Export with any release template, ideally with a console script to notice the errors, and the lack of a printed value from step 2.
5. Export with any debug template and notice the opposite behavior.

Console output should look like this (release on top, debug on bottom)
![image](https://user-images.githubusercontent.com/61520531/204121770-e018cd4e-ef5b-49a2-aaa4-9255450cfa93.png)

### Minimal reproduction project

[PropertyRelease.zip](https://github.com/godotengine/godot/files/10097646/PropertyRelease.zip)

**Comment by gelvinp** [comment]
For some additional context, I went back and recompiled a release template for 4.0 alpha 1, and this was occurring then as well. This bug isn't specific to beta 6.

**Comment by cridenour** [comment]
This looks to be the same as #55045.
