### ISSUE TITLE
GDScript 2.0 setget doesn't work

### ISSUE THREAD

**Issue by SoapSpangledGames** [godotengine/godot#69255]
### Godot version

4.0 beta 6

### System information

Kubuntu 18.04 NVidia GTX 1060

### Issue description

Setters and getters don't get called in the editor when changing the value of the exported variable.

### Steps to reproduce

@export var m_vecSize:Vector3 = Vector3(1,1,1) : set = setSize, get = getSize

func getSize():
print("Return size")
return m_vecSize

func setSize(a):
print("Change size")
m_vecSize = a

### Minimal reproduction project

github won't accept my zip file.

**Comment by MrBlockers** [comment]
Is your script a tool script? If not, I don't think setget methods will trigger. IIRC this is how it works in the old gdscript, too

**Comment by SoapSpangledGames** [comment]
I could have sworn that 3.x fired off the setget regardless of the tool keyword, but I may very well be wrong.

I made my script a tool, and the set and get work. Thank you! I'm going to close this, since it's a false alarm.
