### ISSUE TITLE
Fog breaks rendering of unshaded materials.

### ISSUE THREAD

**Issue by EzraT** [godotengine/godot#69268]
### Godot version

4.0.beta6

### System information

Windows 10, Vulkan/OpenGL3, NVIDIA GTX1060

### Issue description

Demonstration Videos:

https://user-images.githubusercontent.com/781121/204161343-fd0eb68f-654b-47bc-b4bd-e3de70012c20.mp4

https://user-images.githubusercontent.com/781121/204161348-71be76aa-03c5-4e54-9a9e-5db95de26053.mp4

https://user-images.githubusercontent.com/781121/204161354-57bd289c-f02c-4aed-9848-28446820130b.mp4

As the title says, unshaded material rendering breaks when any form of fog is enabled, this issue is especially noticeable if the material also uses the add blend mode. Fog does not affect unshaded materials in Godot 3, so unless I'm missing something this should not be happening in Godot 4 either.
Happens in forward_plus, mobile and opengl3 renderers.

### Steps to reproduce

1. Download and open the reproduction project below.
2. Select the WorldEnvironment node and toggle fog on and off.

### Minimal reproduction project

[srp_fogbug.zip](https://github.com/godotengine/godot/files/10099259/srp_fogbug.zip)

**Comment by Calinou** [comment]
@EzraT Remember that for GitHub video previews to work, you need to have a blank line before *and* after the video URL. I edited your post accordingly, but remember to do this in the future :slightly_smiling_face:
