### ISSUE TITLE
continuous collision detection method cast ray leads to incorrect results

### ISSUE THREAD

**Issue by Warlaan** [godotengine/godot#6926]
**Operating system or device - Godot version:**
Godot 2.1, Windows 10 64bit

**Issue description** (what happened, and what was expected):
Switching between different ccd modes changes the results of the solver. A collision is correctly reported, but the resulting speed of the involved rigid body is completely wrong.
In the project I linked a ball moves towards a vertical rectangle in a diagonal direction. After the collision the horizontal movement is reflected (correct), but the vertical is also reflected, resulting in the ball going back in the direction it came from.

**Steps to reproduce:**
Create a RigidBody and put it on a path that collides with a StaticBody in an angle. 
Set a speed that is large enough for ccd to be applied.
Set friction and gravity scale to 0 and bounce to 1 on both bodies.
Set Continuous CD to Cast Ray.

**Link to minimal example project** (optional but very welcome):
[issue_cast_ray.zip](https://github.com/godotengine/godot/files/552709/issue_cast_ray.zip)

**Comment by Warlaan** [comment]
The android build behaves the same.

**Comment by bojidar-bg** [comment]
@Warlaan Would you like to test this with 1.0/1.1, since I have a feeling that I used to work before just fine...

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.
