### ISSUE TITLE
Hints comments

### ISSUE THREAD

**Issue by BBric** [godotengine/godot#6927]
A specific character (? by example) could be used just after # in a declaration for identify a hint comment.
It would contain a type information and could be used for the completion and the preventive error detection (and probably more).

``` python
func f(a, b, c, d): #? int, String, *, SomeClass.gd : Rect2
    return Rect2()

func g(): #? void : null
    var a #? int # a meaningful integer
    return true # no error but a warning 'return type mismatch'

func h():
    # f() returns a Rect2, it can be completed
    var a = f().|

    # warning 'found Rect2, String expected'
    var b = f() #? String
```

**Comment by Noshyaar** [comment]
This feature request is quite old but I think typed GDScript will be implemented in later versions?

**Comment by BBric** [comment]
Yes the optional typing should be better.

**Comment by bojidar-bg** [comment]
Optional typing in GDScript is now implemented, going to close this issue as such.
