### ISSUE TITLE
A proporção do app está pequena

### ISSUE THREAD

**Issue by Moabesilva004** [godotengine/godot#69280]
### Godot version

3.5.1

### System information

Android

### Issue description

Ola, hoje eu vim relatar uma dificuldade que estou tendo com o Godot para Android, ele está com a proporção pequena, e fica sem conseguir aparecer uma parte do editor, já testei em outros celulares, e o problema persiste, já tentei arrumar nas configurações, mas não conseguir.
por favor arrumem, ficaria muito grato, amo a Godot ❤️

### Steps to reproduce

Apenas crio um projeto, então quando abro o editor, o problema aparece

![Screenshot_20221128-005635](https://user-images.githubusercontent.com/110205286/204190939-b74903c3-9673-4f99-8b0b-31eeb267293c.png)

### Minimal reproduction project

N/A

**Comment by Zireael07** [comment]
Duplicate of already reported issue (the editor wrongly detects your DPI)

PS. Please make bug reports in English, few contributors know Portuguese (I don't but I know Spanish so I was able to get the gist)

**Comment by akien-mga** [comment]
Duplicate of #64165.
