### ISSUE TITLE
Mouse Cursor lag

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#6929]
**Operating system or device - Godot version:**
2.1

I've searched this repo but cannot find anything related to the cursor lag

However, I found this:
https://godotengine.org/qa/6572/is-it-possible-to-run-custom-mouse-cursor-in-seperate-thread

> Custom mouse cursors are emulated by Godot as a sprite on top of the scene, that's why they are affected by lag. According to this issue, custom mouse pointers will be rewritten in 3.0 so they use the system's API instead, then I guess they won't be affected by lag anymore.

Real life example:
![](https://i.gyazo.com/334d7c3fc523cbf51452d2edaccac16c.gif)

And that's changing the position of the sprite using `_input`, inside a `CanvasLayer`.  Is there maybe an alternative method we can use before waiting for 3.0? (If it's even noted :P) This is essential for Hotline Miami / top down shooters. The lag really makes a difference in fluidity / combat

**Comment by timoschwarzer** [comment]
I think the only thing you can currently do is changing the source and hard coding a OS-level cursor. (If it's easily possible using the current source)

**Comment by vnen** [comment]
@timoschwarzer likely not so easy, except maybe for someone already acquainted with the APIs of all platforms.

**Comment by akien-mga** [comment]
*Bug triage note:* The original issue reporter closed all their issues before deleting their account. If you are affected by a similar issue/want a similar feature, please file a new ticket (referencing this one if it contains useful information) so that it can be further looked at and eventually resolved.
