### ISSUE TITLE
having crash on android. 

### ISSUE THREAD

**Issue by hani09876** [godotengine/godot#69297]
### Godot version

godot 4 beta 4, beta5, beta6

### System information

android

### Issue description

when ever i use a plugin i see this error . No matter what the plugin is. 
split_config.armeabi_v7a.apk!libgodot_android.so

![image](https://user-images.githubusercontent.com/92350126/204275550-98d22dc6-9be0-4166-9e38-c132f50ec144.png)

### Steps to reproduce

don't have any idea.

### Minimal reproduction project

[puzzle.zip](https://github.com/godotengine/godot/files/10103633/puzzle.zip)
there is a plugin folder .. add these plugin on the android folder . then build .aab file to see the issue

**Comment by Calinou** [comment]
> when ever i use a plugin i see this error . 

Can you link to the plugin's source code repository?

**Comment by hani09876** [comment]
> > when ever i use a plugin i see this error . 
> 
> Can you link to the plugin's source code repository?

https://github.com/MrZak-dev/Godot-4-Android-Ads


https://github.com/ha0986/Godot-android-InAppReview
