### ISSUE TITLE
Compile Mono version from source, exported template crashes

### ISSUE THREAD

**Issue by Redwarx008** [godotengine/godot#69309]
### Godot version

4.0 master

### System information

WIN10 VULKAN GTX1660TiMaxQ

### Issue description

I followed the approach of this article <https://docs.godotengine.org/en/latest/development/compiling/compiling_with_mono.html>
```
# Build temporary binary
scons p=windows tools=yes module_mono_enabled=yes mono_glue=no
# Generate glue sources
bin\godot.windows.tools.64.mono --generate-mono-glue modules/mono/glue
# Export templates
scons p=windows target=template_debug module_mono_enabled=yes
```
When I compile the exported template, the progress is done at 71%.
![图片](https://user-images.githubusercontent.com/50837890/204358414-1ad120ee-12f6-424b-a589-162b98f33ffe.png)
When I run the exported project, I receive the following error.
![图片](https://user-images.githubusercontent.com/50837890/204358653-766e948f-9da3-4b75-bd9f-b74c43795a58.png)
In addition, the size of the compiled template(53.4m) is smaller than the official Beta6 release(64.3m).

### Steps to reproduce

1.
Installing mono
2.
Installing net6 sdk
3.
 If using PowerShell, replace `curl` with `curl.exe` below.
curl -LO https://curl.haxx.se/ca/cacert.pem
cert-sync --user cacert.pem
4.
Build temporary binary
scons p=windows tools=yes module_mono_enabled=yes mono_glue=no
 Generate glue sources
bin\godot.windows.tools.64.mono --generate-mono-glue modules/mono/glue
Export templates
scons p=windows target=template_debug  module_mono_enabled=yes

### Minimal reproduction project

-

**Comment by raulsntos** [comment]
The documentation hasn't been updated for 4.0 yet, take a look at the instructions in the .NET module's [README.md](https://github.com/godotengine/godot/blob/55dae301777ba609c3255026f9a9852a0dbfd43b/modules/mono/README.md). Also, installing Mono is no longer required.

These would be the commands to build the editor and the assemblies now:

```
scons p=windows target=editor module_mono_enabled=yes
bin/godot.windows.editor.x86_64.mono --generate-mono-glue modules/mono/glue
python ./modules/mono/build_scripts/build_assemblies.py --godot-output-dir ./bin --push-nupkgs-local ~/MyLocalNugetSource
```

To build the export templates:

```
scons p=windows target=template_debug module_mono_enabled=yes
scons p=windows target=template_release module_mono_enabled=yes
```

**Comment by Redwarx008** [comment]
I tried and found that the log is only printed in godot's terminal if dev_build=yes. but at this time godot.windows.editor.dev.x86_64.mono.exe has 200m, generally speaking the official release of godot is only about 110m, what is wrong with this?

**Comment by Zireael07** [comment]
Template_debug will always be bigger than the official release, which is optimized.

**Comment by akien-mga** [comment]
> I tried and found that the log is only printed in godot's terminal if dev_build=yes. but at this time godot.windows.editor.dev.x86_64.mono.exe has 200m, generally speaking the official release of godot is only about 110m, what is wrong with this?

What log do you mean? Official releases are not made with `dev_build=yes`.
See https://github.com/godotengine/godot-build-scripts/blob/main/build-windows/build.sh for build options we use.

> Template_debug will always be bigger than the official release, which is optimized.

Not really, official builds also include `template_debug` (that's the Debug template). But here Redwarx008 built a dev binary, which is a separate option which includes more code and debug symbols, so it's bigger for sure.

**Comment by Redwarx008** [comment]
So, with what options is the official release built? I used `scons p=windows target= editormodule_mono_enabled =yes` but there is no printed log in the terminal(godot.windows.editor.x86_64.mono.console.exe)

**Comment by akien-mga** [comment]
> So, with what options is the official release built?

It's built with MinGW-GCC on Fedora 36: https://github.com/godotengine/build-containers#toolchains

The Mono glue is generated in a separate process from a Linux build, and then copied, but it shouldn't make a difference.
https://github.com/godotengine/godot-build-scripts/blob/main/build-mono-glue/build.sh#L35
https://github.com/godotengine/godot-build-scripts/blob/main/build-windows/build.sh#L50-L51

Then the editor binary is built with:
https://github.com/godotengine/godot-build-scripts/blob/main/build-windows/build.sh#L53-L54

Which expands to (check top of the script):
```
scons -j64 verbose=yes warnings=no progress=no platform=windows arch=x86_64 production=yes module_mono_enabled=yes target=editor
./modules/mono/build_scripts/build_assemblies.py --godot-output-dir=./bin --godot-platform=windows
```
(`verbose=yes warnings=no progress=no` shouldn't make any difference here)

> I used `scons p=windows target= editormodule_mono_enabled =yes` but there is no printed log in the terminal(godot.windows.editor.x86_64.mono.console.exe)

Note that the spaces are wrong in the above command (spaces after `=` and no space between `editor` and `module_mono_enabled`) but I assume it's a typo when copying it in the issue?

Your screenshot in the OP shows console output so I don't understand why you wouldn't get console output anymore? You do need to run the `.console.exe` binary on Windows to get the console redirection working properly.

**Comment by akien-mga** [comment]
Could you tell us what was the resolution for your issue?

[![xkcd "Wisdom of the Ancients"](https://user-images.githubusercontent.com/4701338/204603511-1327646a-9647-4994-9b47-6ae1c39b534d.png)](https://xkcd.com/979/)

**Comment by Redwarx008** [comment]
> Could you tell us what was the resolution for your issue?
> 
> [![xkcd "Wisdom of the Ancients"](https://user-images.githubusercontent.com/4701338/204603511-1327646a-9647-4994-9b47-6ae1c39b534d.png)](https://xkcd.com/979/)

I don't know either, but when I went home and tried `scons p=windows target= editormodule_mono_enabled =yes`again, the console had log output. :D
