### ISSUE TITLE
StyleBox texture for PopupPanel missing

### ISSUE THREAD

**Issue by WolfgangSenff** [godotengine/godot#69308]
### Godot version

4.0.beta6

### System information

Windows 11

### Issue description

Was attempting to use a PopupPanel and found I could not find the actual panel style to define how the panel is supposed to look. Are you supposed to define this in the theme? Seems like a long, circuitous route for something that used to be explicitly defined on the control in the past. The documentation even seems to imply the panel property should be there so you can apply the style like rather than having to figure out the new theming system and potentially having to replace a theme that you already made.

### Steps to reproduce

Start a project, add a PopupPanel to a scene, note the panel is missing.

### Minimal reproduction project

Don't have one because this isn't project specific.

**Comment by Calinou** [comment]
Can you reproduce this in 3.5.1?

**Comment by WolfgangSenff** [comment]
No. See the picture for more:
![image](https://user-images.githubusercontent.com/148612/204356778-565ba61c-0b13-486c-8615-0366751193f3.png)

**Comment by WolfgangSenff** [comment]
Just noticed PanelContainer *does* have the theme override like the above, which leads me to believe it might be either an issue of a missing inheritance chain, or because the engine is not interpreting it as a control but rather as a window, it isn't listing the theme overrides, even though you can define the theme on it. Purely guesswork, of course.

**Comment by kleonc** [comment]
Indeed `PopupPanel` inheriting from `Window` seems to be the cause. The code adding "Theme Overrides" is present in `Control`:
https://github.com/godotengine/godot/blob/55dae301777ba609c3255026f9a9852a0dbfd43b/scene/gui/control.cpp#L349-L424
but not in `Window`.

cc @YuriSizov

**Comment by YuriSizov** [comment]
Yep, I don't think this was ever implemented when popups were split into their own thing, which is not a `Control`. This should probably be solved by moving local overrides to the new ThemeOwner class.

>  having to figure out the new theming system and potentially having to replace a theme that you already made.

Not sure what you mean, Kyle. Theming works pretty much as before, though some names changed for clarity and consistency. Most of the improvements were made to the usability, and even that was backported to 3.x. Also fonts are not compatible between 3.x and 4.x, but that's not strictly theming related 🙃

**Comment by WolfgangSenff** [comment]
Oh, I just mean creating a theme specifically using the new theming system to go and find the panel and target it and applying it. I'm not even sure if it's possible, was just a thought! I wasn't sure how to get one theme to inherit the other if you already had a theme applied, if I had to do such a thing at all.

**Comment by YuriSizov** [comment]
There is no "new" theming system though 🙃 Themes inherit each other from the tree order, i.e. parents provide styling for their children with the theme resource they have assigned. Any new theme further down a branch of nodes adds/overwrites properties, they combine, and that combination is applied to the following children. And so on, and so forth.

For the time being you can just assign a theme resource to your panel with appropriate theme properties defined. Not exactly the same as local overrides, but would work in a pinch.

**Comment by WolfgangSenff** [comment]
@YuriSizov - okay, that's what I was asking about. :P Appreciate it!
