### ISSUE TITLE
Disabling splash screen Show Image project setting has no effect on Android

### ISSUE THREAD

**Issue by MecoCL** [godotengine/godot#69316]
### Godot version

3.5.1 stable

### System information

Android 11 (GLES2)

### Issue description

![image](https://user-images.githubusercontent.com/103614257/204392929-97a4f99d-7658-4a79-ad6b-71079ab212f1.png)

Hey guys, I caught a bug in Godot 3.5.1

When you unselect "Show Image", it won't show image on PC versions but on Android, it completely ignores that and keep showing the image normally

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
@MecoCL Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by MecoCL** [comment]
I'm sorry, but where do I get that?

**Comment by radlotus** [comment]
Can confirm on Android 10.

**Comment by Zireael07** [comment]
@MecoCL: Minimal reproduction project is the smallest project YOU can make that shows the problem. In this case, likely a new godot project + image you wanted to show in splash screen

**Comment by MecoCL** [comment]
@Zireael07 [Splash Screen.zip](https://github.com/godotengine/godot/files/10124023/Splash.Screen.zip)
