### ISSUE TITLE
[Godot 4] Polygon 2d texture messing up

### ISSUE THREAD

**Issue by tomaskallup** [godotengine/godot#69311]
### Godot version

v4.0.beta5.official [89a33d28f]

### System information

Manjaro Linux Xfce, GLES3, AMD RX 580

### Issue description

Creating 2d polygons with texture assigned ([following the 2d skeleton tutorial](https://docs.godotengine.org/en/stable/tutorials/animation/2d_skeletons.html)) in the 4.0 beta renders some of the polygons incorrectly:
![image](https://user-images.githubusercontent.com/26621166/204364141-dd516f05-a729-4a0a-b330-cb1efb9a2498.png)
There are no bones, simply a couple of polygon 2ds with texture and UV points setup. Some polygons become messed up, some seem to be fine.
A way to 100% break a polygon, is by assigning a 2d skeleton (event empty one, without any bones and without assigning any weights).
![image](https://user-images.githubusercontent.com/26621166/204364504-3060844f-944f-4c67-a619-de906597b99c.png)

### Steps to reproduce

The project is very very simple, just a 2d scene with a couple of polygon 2ds.
Simply opening it should break the polygons, if not, assigning a skeleton to them should do the trick.

I have been able to reproduce this on two different computers, one running Manjaro Xfce on full AMD, one running custom Manjaro with tilling window manager running on intel GPU.

### Minimal reproduction project

[example.zip](https://github.com/godotengine/godot/files/10106883/example.zip)

**Comment by tomaskallup** [comment]
When I was looking through possibly related issues, I got to this one https://github.com/godotengine/godot/issues/59451, which seems like the same bug, but it was closed in March and also related to Vulkan + mobile.

**Comment by clayjohn** [comment]
This was fixed in beta 6: see the release post here: https://godotengine.org/article/dev-snapshot-godot-4-0-beta-6

**Comment by tomaskallup** [comment]
Ah my bad, completely missed the release, sorry!
