### ISSUE TITLE
Add Scots (lang code "sco") as a supported language in Godot

### ISSUE THREAD

**Issue by Cobradabest** [godotengine/godot#6931]
**Operating system or device - Godot version:**
Windows 10 - Godot 2.1 Stable

**Issue description** (what happened, and what was expected):
I tried to add my Scots translation of a game into my project, and it didn't recognize it, nor does it officially support.

Can this language be added to the list in 2.1.1. or whatever next version comes out?

**Comment by bojidar-bg** [comment]
@akien-mga You want help on the issue? (i.e. pretty bump)
