### ISSUE TITLE
BaseMaterial3D: wrong tooltip/documentation for roughness texture channel 

### ISSUE THREAD

**Issue by novemberist** [godotengine/godot#69328]
**Your Godot version:**

4.0 dev, 55dae301777ba609c3255026f9a9852a0dbfd43b

**Issue description:**

The tooltip and documentation for the property roughness_texture_channel in the editor actually show the description for the ao_texture_channel

![grafik](https://user-images.githubusercontent.com/7927471/204448720-63d0dbc5-7161-4a27-8fba-3d87bc2d7040.png)

**URL to the documentation page:**

https://github.com/godotengine/godot-docs/blob/master/classes/class_basematerial3d.rst

**Comment by clayjohn** [comment]
Transferring to the main godot repository as that is where we manage the class reference. 

The line that needs to be updated can be found here: https://github.com/godotengine/godot/blob/55dae301777ba609c3255026f9a9852a0dbfd43b/doc/classes/BaseMaterial3D.xml#L322

**Comment by akien-mga** [comment]
Fixed by #69515.
