### ISSUE TITLE
Enabling Proximity Fade/Distance Fade in shader will make the light went through

### ISSUE THREAD

**Issue by Intervel** [godotengine/godot#69329]
### Godot version

4.0 beta 6

### System information

Windows 11

### Issue description

is this supposed to happen or is this a bug?
i set the tunnel to cull_disabled.

also, spotlight not working at all

check this videos for better explanation :

https://streamable.com/4ygq1c
https://streamable.com/ou6w8p
https://streamable.com/4ur3i2

### Steps to reproduce

check the videos

### Minimal reproduction project

none

**Comment by Calinou** [comment]
This is expected, as enabling Proximity Fade or Distance Fade will make the object go through the transparent pipeline, which disables shadow casting for the object.

**Comment by Intervel** [comment]
@Calinou hello my friend, sorry for not including the project. here is my project. im using the new physical light units not the vanilla ones.

https://www.dropbox.com/scl/fo/4i2vmoywoqas264z2pn27/h?dl=0&rlkey=itabgvtkti5v5oc0s5gihqyd1
