### ISSUE TITLE
Unable to export to macOS with Notarization Xcode altool

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot#69345]
### Godot version

4.0.beta6

### System information

macOS 13.0.1

### Issue description

I'm trying out exporting to macOS and wanted to try the Godot notarization export process. But I've been unable to do so, since when I fill in my AppleID credentials this disables the "Export Project..." button.

If I disable Notarization (the default) I can export the project fine, but there's a warning in the Export dialogue that it will be blocked by gatekeeper as expected. If I enable Notarization with XCode altool but don't fill in my Apple ID Name, Apple ID Password and Apple Team ID I get red error messages below. If I fill these in the error messages disappear, but the "Export Project..." button remains disabled.

### Steps to reproduce

- Create a macOS export preset in a project
- Enable XCode altool notarization
- See warning messages about needing to fill in credentials
- Enter your Apple ID Name, Password and Team ID (for testing these can probably be anything)
- Warning messages should now have disappeared, but the Export Project button is still disabled so you can't export.

### Minimal reproduction project

see above

**Comment by Calinou** [comment]
cc @bruvzg
