### ISSUE TITLE
Cannot disconnect signal with context menu once created

### ISSUE THREAD

**Issue by adamscott** [godotengine/godot#69348]
### Godot version

4.0.dev (55dae301)

### System information

Linux (Ubuntu 22.04), Vulkan, Radeon RX Vega 64 (eGPU)

### Issue description

When creating signals successfully, the signal can be shown yellow. If the signal is yellow, it's impossible to disconnect it from the context menu.

![Capture d’écran du 2022-11-29 12-04-54](https://user-images.githubusercontent.com/270928/204595961-842f6826-16f1-4da6-91a5-76a858c5ace1.png)

It's still possible to disconnect the signal using the Disconnect button at the bottom.

### Steps to reproduce

1. Create a scene
2. Attatch a script to the scene
3. Click on the root node of that scene
4. Attach a signal

Sometimes, the signal is yellow. If it's yellow, it's not possible to disconnect it using the context menu.

### Minimal reproduction project

Unfortunately, this happens only when creating a new signal. But if needed, here's a kind of MRP:
[cannot_disconnect_signal.zip](https://github.com/godotengine/godot/files/10115408/cannot_disconnect_signal.zip)

From testing, when loading a project, the yellow signals will become white and will work as usual.

**Comment by KoBeWi** [comment]
This was implemented in #66665 and it's supposed to block signal disconnections from foreign nodes, but I noticed that it sometimes blocks a signal when it shouldn't. I don't know what triggers wrong behavior though.

**Comment by Sauermann** [comment]
I just tested it and can confirm this issue. After connecting a Signal, I can't disconnect it via the right-button-menu.

After saving the scene, the right-button-menu works for me again.

It looks like in `SceneState::has_connection` after the first signal-connection, `ss->connections.size() == 0` until storing the value is triggered somehow.

**Comment by kleonc** [comment]
> I don't know what triggers wrong behavior though.

Whether the connection is inherited is deduced based on the scene state of a `PackedScene` obtained from the `ResourceLoader`:
https://github.com/godotengine/godot/blob/d930b308836af09ea3e3bf4b689ac436977db940/editor/connections_dialog.cpp#L790-L808

Meaning all connections not yet saved within the scene file are considered as inherited and thus as non-disconnectable.

Not yet saved connections should be somehow taken into account.
cc @Mickeon

**Comment by KoBeWi** [comment]
Right... I tested on a new scene and if the scene is [unsaved] the issue does not happen.

**Comment by kleonc** [comment]
> Right... I tested on a new scene and if the scene is [unsaved] the issue does not happen.

Because when it fails to load the scene it deduces it's not inherited:
https://github.com/godotengine/godot/blob/d930b308836af09ea3e3bf4b689ac436977db940/editor/connections_dialog.cpp#L790-L793

**Comment by Sauermann** [comment]
It looks like the info, that a new connection is made, is somehow buried between the undo-redo-mechanic and `ResourceLoaderText::load`.

A solution would likely have to do one of the following things:
- maintain a cache of connections in `ConnectionsDock::_connect`, `ConnectionsDock::_disconnect` and other related functions
- let `ConnectionsDock::_is_connection_inherited` access the connections stored in the undo-redo-mechanic
- enforce saving the state after connecting a signal

**Comment by Mickeon** [comment]
I had a more "advanced" check stashed in the branch implementing this check that fixes this, but it is so convoluted that it makes me think that either the SceneState should know about this in advance (by storing whether or not a signal is inherited for example), or by at least caching it more nicely.
