### ISSUE TITLE
detach/clear script context menu option

### ISSUE THREAD

**Issue by razvanc-r** [godotengine/godot#6934]
I got reminded a few minutes ago that for people starting out in Godot is really difficult to figure out how to detach/clear scripts from nodes. It's intuitive to attach, but not to detach, myself included. When I first looked at Godot I just couldn't figure out how the heck to do it cause it isn't specified anywhere that attaching scripts basically just sets the `Script` property in `Inspector`.

I propose that a `Detach Script` near `Add Script` in the context menu :).

**Comment by volzhs** [comment]
Then we need context menu for "Create", "Load", "Detach" for script.
I think I saw an issue for loading existing script with context menu, but I can't find now.
