### ISSUE TITLE
"Create new node" search field gets slow the more node types are displayed

### ISSUE THREAD

**Issue by Kelin2025** [godotengine/godot#69359]
### Godot version

4.0.beta5

### System information

Win 10, Ryzen 2600x

### Issue description

For now, the more node types exist in the project, the slower the search 
Adding a debounce to search can solve this problem

### Steps to reproduce

1. Create ~50-100 node types with same-ish names
2. Press "Add child node" on any scene
3. Type something in search input
4. It's very slow and speeds up when more nodes get filtered out

### Minimal reproduction project

Not needed

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/27333.
