### ISSUE TITLE
Erroneous input events when hovering non-focused native window

### ISSUE THREAD

**Issue by pkdawson** [godotengine/godot#69368]
### Godot version

v4.0.beta6.mono.official [7f8ecffa5]

### System information

Windows 11 22H2

### Issue description

This is a platform-specific bug, because it behaves correctly on macOS 13. No idea about Linux.

In a project with multiple native windows:

1. Have one window focused, and hover your mouse over another window.

2. The focused window will receive `InputEventMouseMotion` events in `_input`, but with mouse coordinates from the non-focused window.

Or to look at it another way, the events are correct but the wrong window is receiving them.

### Steps to reproduce

Run the MRP, observe output as you focus one window and hover over the other.

### Minimal reproduction project

[native_windows_hover.zip](https://github.com/godotengine/godot/files/10119459/native_windows_hover.zip)

**Comment by pkdawson** [comment]
This was apparently caused by an intentional change ("Send mouse move events to focused window instead of hovered window."), but I don't understand the intent. The result is just bad data: input events that say the mouse cursor is somewhere it isn't.

* https://github.com/godotengine/godot/pull/67903

@Sauermann If you could explain the intended behavior, maybe I can fix this.

**Comment by Sauermann** [comment]
Thank you for bringing this issue to my attention: _The focused window will receive InputEventMouseMotion events in \_input, but with mouse coordinates from the non-focused window._
I can confirm this bug. Apparently I missed this corner case during my implementation. The behavior differs from linuxbsd, where the mouse-coordinates are relative to the focused window.
I believe, that the correct solution is to adjust the mouse position in the event and not adjust the window, that receives the input. I will investigate a solution for this.
