### ISSUE TITLE
naming project with file name with 2 or more prohibited characters causes user:// directory to not exist

### ISSUE THREAD

**Issue by Broskibble** [godotengine/godot#69366]
### Godot version

3.5.1

### System information

Windows 10

### Issue description

I named my project something, and later renamed it with a colon and a period(not knowing of the problems). I later was adding saves and was using "user://save_game.save" like most people but it wasn't working. after a while we figured out that the problem was the colon in the project title made "user://" not functional (print(save_file.open("user://save_game.save", File.WRITE)) returned 7) i changed the name and now it works fine but the bug is still there.

### Steps to reproduce

On windows 10 (windows 11 doesnt work) Make a new project with two special characters in the project name (two colons, two periods, one colon one period, etc). Try to access "user://" one way is to do

var save_file = File.new();
print(save_file.open("user://save_game.save", File.WRITE));
save_file.close();

it should return 7 which is wrong, if you rename the project without a colon and try the code again it will return 0

### Minimal reproduction project

[project.zip](https://github.com/godotengine/godot/files/10119154/project.zip)

**Comment by ShatReal** [comment]
Additionally, naming your project "." makes the `user://` directory the `app_userdata` folder and naming your project ".." makes the `user://` directory the `Godot` folder (parent of the `app_userdata` folder).

**Comment by volokh0x** [comment]
Tested on Linux with 4.0 `beta7`

>Additionally, naming your project "." makes the user:// directory the app_userdata folder and naming your project ".." makes the user:// directory the Godot folder (parent of the app_userdata folder).

I can confirm this behavior.

In other cases `user://` folder is created inside `app_userdata` in a predictable way:
- project's name starting with period is a hidden folder
- each `:` character gets replaced with `-`

In all cases no error occurs when accessing user files
