### ISSUE TITLE
Rename TileMap.get_surrounding_tiles() to get_surrounding_cells()

### ISSUE THREAD

**Issue by Rubrickus** [godotengine/godot#69373]
### Godot version

4.0 beta6 (and earlier)

### System information

N/A

### Issue description

Just a naming consistency issue. Within TileMap, "cell" refers to a location in map coordinates, represented as a Vector2i. This method returns an array of such locations, not of "tiles". Surely this should be consistent with get_neighbor_cell() etc.

Obviously this would be a breaking change (though one with a trivial fix for users), but there are enough of those in Godot 4 that maybe it would be an opportune time.

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by groud** [comment]
Yeah, that's a good idea!

**Comment by Rubrickus** [comment]
Awesome, thanks!
