### ISSUE TITLE
Can't change Anisotropic Filtering at run time

### ISSUE THREAD

**Issue by TokisanGames** [godotengine/godot#69379]
### Godot version

Godot 4 Beta 6

### System information

Windows 11/64, RTX 3070, Vulkan

### 1. Runtime Anisotropic Filtering
I can turn on anisotropic filtering on my terrain in the shader. However, I cannot give the player the option to turn it off or change the level. In godot 3, I could turn on or off filtering on the fly, not only in the project settings, but also on all of the textures.

I'm using texture arrays, importing with Mipmaps generation, and in my shader material, I've added filtering. Project settings default to 4x. That worked as soon as I enabled it in the shader.

![image](https://user-images.githubusercontent.com/632766/204751666-dee65afd-4016-44f3-985d-3aea5baf1849.png)

However changing the project settings, and confirming with Godot that the setting has changed, does not change anything on screen. The only difference happens when the shader is changed to remove the filtering as shown here:

![image](https://user-images.githubusercontent.com/632766/204755916-4c11926b-c20e-4652-adc7-bc72de726031.png)

I can manually change the project setting to different levels and restart the editor and see the change in the editor. But that is unreasonable that a player should have to restart the game for a setting that updated on the fly in GD3. And how do I as the developer even change the project settings and restart on an exported game anyway?

~~### 2. There is no difference beyond 4x.~~

~~I see a difference between off, 2x, and 4x. After that there is absolutely no difference between 4x and 16x. The color you see at the top is from animated trees. The terrain difference is all black.~~

![image](https://user-images.githubusercontent.com/632766/204760345-2aed8227-c33e-419e-971d-ffd6237aeea0.png)

### Steps to reproduce

n/a

### Minimal reproduction project

n/a

**Comment by nonunknown** [comment]
please provide at least Minimal Reproduction project, where you can change AF at runtime, to make devs life easier!

**Comment by tinmanjuggernaut** [comment]
> You can still toggle anisotropic filtering on a per-material basis in the BaseMaterial3D properties, 

We're using shaders, which does not inherit that. Does this toggle generate a new shader? It appears that moving af to the shader texture uniform instead of the texture file removes the option to toggle it without creating all new shaders on the fly. 

> but the anisotropic filtering level can't be changed at run-time just like in 3.x.

You mean "unlike in 3.x". We had runtime anisotropic filtering toggle. Enabled in the project settings, then we went through every loaded texture and enabled af on it. 

Leaving it on always will be our next best option. But it's courteous to provide lower end options.

I'll look at a basematerial mrp. I've also discovered that anisotropic filtering is noisy, whereas it was stable in 3. Not mipmap noise. Bands of noise.

**Comment by Calinou** [comment]
> You mean "unlike in 3.x". We had runtime anisotropic filtering toggle. Enabled in the project settings, then we went through every loaded texture and enabled af on it.

Indeed, you could toggle anisotropic filtering on a per-*texture* basis in 3.x. You can still toggle anisotropic filtering at run-time in 4.0, but it's done on a per-*material* basis. What you can't do is *change* the global anisotropic filtering *level* at run-time.

**Comment by tinmanjuggernaut** [comment]
Sure, except now I can't change af on textures, nor on shaders, nor globally. And base materials are inadequate for terrain, so there's no feasible way to change it at runtime, when there was in 3. Hence the ticket.

**Comment by clayjohn** [comment]
I think we can improve the project setting so filtering level is switchable at runtime. To me, that makes the most sense as the use-case here is a performance switch anyway. 

I definitely see how annoying it is to have to manage multiple versions of a shader just to enable/disable anisotropy. In the StandardMaterial we make it easy to change and we maintain a hashmap of shader versions so you can just switch back and forth easily. But it would be unfair to users to force them to build their own material system like StandardMaterial just to enable/disable anisotropy. 

On the more technical side, we already have code to hot swap the texture samplers so we can adjust the mipmap bias on the fly. We just need to hook that up better with the anisotropy project setting so it can be used to change anisotropy on the fly

**Comment by tinmanjuggernaut** [comment]
After further testing, I do see a difference between all levels 0 through 16x, and the noise is not from AF. It's from low quality DOF.

So the only thing remaining is the means to toggle AF on/off via project settings, textures, or shaders. If you guys want to close this in favor of https://github.com/godotengine/godot-proposals/issues/4673 or leave it open, either is fine.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/4673.
