### ISSUE TITLE
Godot tries switching monitor resolution after splash screen

### ISSUE THREAD

**Issue by udit** [godotengine/godot#69389]
### Godot version

v3.5.1.stable.official [6fed1ffa3]

### System information

Windows 10, GLES3, Nvidia GTX 1070

### Issue description

When running Godot projects in fullscreen on an external monitor with 4k native resolution, there is a brief black screen after the splash screen, as if the program was attempting to change resolution. Same black screen can be observed when Alt-Tabbing in and out when the project is running. However, the project itself runs on 4k.

The problem only occurs on 4k. The problem goes away if I change the monitor's display resolution to 1080p in Windows settings or run it on my laptop's internal 1080p screen.

https://user-images.githubusercontent.com/6249061/204794807-99e4711c-2fbb-4af2-9485-d7c85ce950be.mp4

### Steps to reproduce

Run an empty project with stretch mode disabled.

### Minimal reproduction project

[ResolutionTest.zip](https://github.com/godotengine/godot/files/10122961/ResolutionTest.zip)

**Comment by Calinou** [comment]
Godot 3.x uses exclusive fullscreen if the window resolution matches the screen resolution. Can you reproduce this if you disable **Fullscreen**, enable **Borderless** and set the window height to be 1 pixel smaller than the screen height?

**Comment by udit** [comment]
> [Godot 3.x uses exclusive fullscreen if the window resolution matches the screen resolution.](https://github.com/godotengine/godot/issues/60665) Can you reproduce this if you disable **Fullscreen**, enable **Borderless** and set the window height to be 1 pixel smaller than the screen height?

Unable to reproduce the issue with mentioned settings, it occurs only when fullscreen is enabled.

**Comment by udit** [comment]
Since I started using Godot 4 and Windows 11 preview, this problem has stopped happening. I even tried v3.5.1.stable and there was no resolution switching issue.

Since I no longer have a  Windows 10 device I don't know whether the issue was with Windows or drivers or something else. I think this can be closed since the issue is not happening even with Godot 3 on Win 11.

**Comment by Calinou** [comment]
Closing per the above comment. Thanks for the follow-up :slightly_smiling_face:
