### ISSUE TITLE
ResourceFormatLoader and ResourceFormatSaver throwing errors on focus

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#69386]
### Godot version

4.0 beta 6

### System information

manjaro linux

### Issue description

When you load a plugin, that uses `ResourceFormatLoader` and/or `ResourceFormatSaver` engine throws error:

```
Script does not inherit a CustomResourceLoader: res://addons/dialogic/addons/dialogic/Resources/CharacterResourceLoader.gd.
```

### Steps to reproduce

* Just open a project which contains script using the mentioned classes

### Minimal reproduction project

just download dialogic and place it on your project

https://github.com/coppolaemilio/dialogic

**Comment by Calinou** [comment]
Please try to reproduce this in a minimal project, as a full add-on makes it difficult to know what's the exact cause of the issue.

**Comment by paskausks** [comment]
I've encountered this issue with my minimal custom loaders and savers as well, but it seems to happen occasionally and I can't pinpoint the issue (yet).

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
