### ISSUE TITLE
[Godt 4.0] Sometime expression which should be a boolean value that return a `GDScriptFunctionState` 

### ISSUE THREAD

**Issue by Daylily-Zeleen** [godotengine/godot#69381]
### Godot version

4.0 beta 6

### System information

Windows 10, Vulkan, GTX1060

### Issue description

The issue is quite complicated, and I can't descripte it exactlty, it is very hard to reproduce，so I try my best to seperate it from my projecct. Please download the attached zip file for mroe detail.

I sure it is relate to type and async mechanism.

Here have 3 ways to "solve" this problem.
```
	## Case1: ↓↓↓↓↓↓↓↓↓↓ the issue will disappear if use 
	## `var adaptor = load("res://addons/bool_err_test/scenes/adaptor.gd").new()` 
	## to replace this line. ↓↓↓↓↓↓↓↓↓↓↓↓
	var adaptor = _instantiate_adaptor()
	## ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
	
	add_child(adaptor)
	
	## Case2: ↓↓↓↓↓↓↓↓↓↓ the issue will disappear if remove this 4 lines. ↓↓↓↓↓↓↓↓↓↓
	var valid = await adaptor._is_configuration_valid_async()
	if not valid:
		adaptor.queue_free()
		return
	## ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
	
	var check_version_res := await adaptor._check_package_version_exists_async() as int
	var force_override :bool = false
	## Case3: ↓↓↓↓↓↓↓↓↓↓ the issue will disappear if remove all type info in this line. ↓↓↓↓↓↓↓↓↓↓
	var packed_path:String = await adaptor._pack_package_async() as String
	## ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
	
	print(packed_path)
	# will print as a `GDScriptFunctionState`.
	print(packed_path.is_empty())
```

The reson why I specify the problem is relate to  boolean expression is I had encountered this situation:
```
func foo(bool_value: bool ) -> void:
    ## some operate, and `bool_value` is `true`
    if not bool_value:
        # will print a `GDScriptFunctionState`, too.
        print(not bool_value)
    else:
        # will not be executed.
        print("will not be execute")
    
```
Unfortunately, I can't reproduce this example and lost the origin code.

### Steps to reproduce

1. Open my attached project.
2. Ensure my test plugin `Bool Error Test Window` is enabled.
3. `Project `->`Tool`->`Bool Error Test Window`, to open a test window.
4.  Press `Print` button and check the `Output` panel.

### Minimal reproduction project

Here is the reproduction project
[bool_error_test_project.zip](https://github.com/godotengine/godot/files/10121782/bool_error_test_project.zip)

**Comment by dalexeev** [comment]
Probably duplicate of #70637. Please test this and see if the bug still reproduces.

**Comment by Daylily-Zeleen** [comment]
I'm not sure this issue is occured by the same reason of [#70637](https://github.com/godotengine/godot/issues/70637).
I test this again, it seems that this issue is already fixed.
So, I close this issue.
