### ISSUE TITLE
AnimationStateMachine doesn't run consistently when animation entrance was spammed

### ISSUE THREAD

**Issue by mrbaggins** [godotengine/godot#69382]
### Godot version

Official 4.0 beta 5 and 6

### System information

Windows 10

### Issue description

Using AnimationTree and AnimationPlayer, using `Input.is_action_just_pressed` to then call `state_machine.travel("Roll")` which then plays the animation from a BlendTree2D with no issue if there is space between each call.

The Roll animations then have a Call Method track that calls a function. This also gets called consistently when there is space between the inputs.

But if you spam the input key, this function is sporadically not called. Same issue with Attack, which is set up the exact same way.

Perhaps related, perhaps not, but the `AnimationPlayer - animation_finished(string)` signal ALSO never seems to be called. I've specifically checked as per docs that none of the animations are set to loop, which would disable this signal.

Tested in b5 and b6 (6 has no animations playing due to known `RESET` bug, but the call method track still fails on input spam.)

Issue persists when changing `Method Call Mode` to any setting.

### Steps to reproduce

Open project, Run. Mopve around with WASD to set animation directions. Attempt to roll by pressing `F` Wait until roll is complete then `F` again to roll again. No issues.

Instead, spam the `F` key. Eventually it will not stop moving when it should (sliding to the edge) and other controls are unresponsive because you are in ROLL state. 

Check console during above, you will see "Start roll" from ENTERING the animation, but no "End Roll" from the Animation player's call method function on the spammed issue.

Same issue without console outputs if you use `Space` to do ATTACK animations instead.

### Minimal reproduction project

[HeartBeast ARPG - Copy.zip](https://github.com/godotengine/godot/files/10121854/HeartBeast.ARPG.-.Copy.zip)

**Comment by nonunknown** [comment]
this is likely an error from your part than the engine, try this:

in the function that calls the animationplayer.play() change to this:

```gd
func play_animation():
  if !anim_player.is_playing("roll"):
      anim_player.play("roll")
```

**Comment by mrbaggins** [comment]
I'm not using `.play`, I'm using a state machine and `.travel`

**Comment by lufog** [comment]
I tried to make mrp, but I was unable to replicate the behavior. So I also tend to think that the problem is in the game logic, but I have no concrete evidence. BTW, if you move animation transitions from

```gdscript
if (Input.is_action_just_pressed("Attack")):
		state = ATTACK
		# state_machine.travel("Attack")
		
	if (Input.is_action_just_pressed("Roll")):
		if (state != ROLL):
			print("Roll start")
			state = ROLL
			# state_machine.travel("Roll")
```

to begin of each state:

```gdscript
func roll_state(delta):
	state_machine.travel("Roll") # <-- here
	velocity = roll_vector * ROLL_SPEED
	move_and_slide()
	if (Input.is_action_just_pressed("Attack")):
		state = ATTACK
		#state_machine.travel("Attack")

func attack_state(delta):
	state_machine.travel("Attack") # <-- here
	velocity *= 0.75
	move_and_slide()
```

the problem disappears.

**Comment by mrbaggins** [comment]
Moving the `state.travel` made no difference to my project or uploaded project.

Running your upload project gets stuck in spin state EVERY time for me. (Running in official beta 5 though)

**Comment by lufog** [comment]
> Running your upload project gets stuck in spin state EVERY time for me. (Running in official beta 5 though)

As I mentioned, for tests, I used build from #69336 to separate your problem from this one #69415. So use build from [actions](https://github.com/godotengine/godot/actions/runs/3592876308) or move method call away from the end of the animation.

> Is that likely to cause issues, telling my state_machine to travel 15+ times because it's called every physics frame?

I didn't suggest this as the correct fix. I just voiced it in the hope that it will help you, or another person who decides to dive into this issue, find its cause.

> Edit-edit, I don't believe the move fixes it, it masks it, as it fails to run call method track, and simply rolls again, and the next time works. It's mostly hidden by spamming the keys, but it is actually still failing.

Perhaps.

**Comment by mrbaggins** [comment]
All of the following using the original problem project:

>As I mentioned, for tests, I used build from https://github.com/godotengine/godot/pull/69336 to separate your problem from this one https://github.com/godotengine/godot/issues/69415. So if you want to test it, use build from [actions](https://github.com/godotengine/godot/actions/runs/3592876308) or move method call away from the end of the animation.

I downloaded the linked build, using my original code the problem persists for me 

>After some additional testing, I was able to reproduce the issue in my MRP. The error occurs if the method call time on the timeline is less than ≈0.4.

I adjusted mine to a 1 second animation, with the method call at 0.8, and it still fails.

**Comment by lufog** [comment]
Are you sure that you test adjusted animation? You have 4 for each side. Test this:
[HeartBeast ARPG - Copy.zip](https://github.com/godotengine/godot/files/10137084/HeartBeast.ARPG.-.Copy.zip)

By the way, this is not a suggestion how to fix the problem. Just additional information that may be useful (or not) to those who undertake to fix it.

**Comment by mrbaggins** [comment]
That project breaks for me in official beta 5 (it never ever calls the Call Method Track), and the animations are 0.4 long (Mine are normally 0.3)

In the custom build, you're right, `Call_Method` track works at 0.4 but does NOT work at 0.25

I tested back in 0.01 increments. 0.39 works, 0.38 does not.

**Comment by lufog** [comment]
This time varies slightly, for example, depending on whether _process or _physics_process is used.  Also, depending on which node the transition occurs, Animation or BlendSpace2D, etc.

**Comment by TokageItLab** [comment]
Maybe the problem is related to this issue #68986, but I don't know since I have not much knowledge about StateMachine.

I remember there is a plan to rework StateMachine, but I don't know detail. cc @SaracenOne

**Comment by TokageItLab** [comment]
This issue is caused by the state on the GDScript and the StateMachine state being out of sync, and the StateMachine Node is trying to transition (restart) to itself, which is not yet supported. The following code would solve this problem.

```gdscript
	if (Input.is_action_just_pressed("Roll")):
		if (state_machine != ROLL):
			print("Roll start")
			state = ROLL
			state_machine.travel("Roll")
```
↓
```gdscript
	if (Input.is_action_just_pressed("Roll")):
		if (state_machine.get_current_node() != "Roll"):
			print("Roll start")
			state = ROLL
			state_machine.travel("Roll")
```

**Comment by mrbaggins** [comment]
That's very close to my current work around, better in terms of running too (just a minor reorganise of code, but mine runs the check more often currently).
