### ISSUE TITLE
`queue_free()` (or maybe something else) in animation breaks game if run in editor 

### ISSUE THREAD

**Issue by SephReed** [godotengine/godot#69410]
### Godot version

3.5.1

### System information

Fedora

### Issue description

Perhaps this is expected behavior, I'm new to this.  But I tried running an enemy animation in a demo project which calls `queue_free()` at the end, and -- once I do that a single time -- all of the enemies RayTracers stop interacting.

It seems like running an animation shouldn't substantially affect the project.

### Steps to reproduce

1. Open the "Platformer 2D (Raytrace)" Demo project
2. Go to the enemy entity
3. Run the "destroy" animation
4. Everything is borked in game now

### Minimal reproduction project

N/A

**Comment by SephReed** [comment]
This is the animation.  And it turns out it doesn't break the ray tracing, but instead it's collision stuff?  It's really weird and hard to explain as this is my first day.

![Screenshot from 2022-11-30 11 59 32](https://user-images.githubusercontent.com/14002040/204885486-25b46c84-067d-4c74-8b2b-f0d1803288cd.png)

**Comment by Calinou** [comment]
Call method tracks in the editor are supposted to be ineffective.

**Comment by SephReed** [comment]
Oh, yeah.  Thanks.  I'm really having a hard time figuring this out.  If I close the project and reopen, it's still broken.  If I close godot and reopen, it's still broken.  The only thing I can do to get it working again is delete the entire project and re-download it.

**Comment by SephReed** [comment]
Oooh!  It might be that it changes the collision layer.  But still, why would playing an animation change anything about what goes on inside the game?

**Comment by Calinou** [comment]
> Oooh! It might be that it changes the collision layer. But still, why would playing an animation change anything about what goes on inside the game?

This is likely an issue with the demo itself. The AnimationPlayer lacks a suitable RESET track with tracks for all properties that need to be reset when opening the scene in the editor. This is common in projects made before Godot 3.4 and ported over.

**Comment by SephReed** [comment]
Thanks, I just found the answer here too: https://github.com/godotengine/godot-proposals/issues/3829

It's an older project, as you said.
