### ISSUE TITLE
AnimationTree; AnimationNodeBlendTree graph creates new nodes far away from parent node connections

### ISSUE THREAD

**Issue by wokeraccoon** [godotengine/godot#69413]
### Godot version

v4.0.beta6.official [7f8ecffa5]

### System information

Fedora Linux 37, AMD RX 6600, AMD Ryzen 7 3700x

### Issue description

When editing blend nodes in the AnimationNodeBlendTree graoh, right clicking anywhere on the graph and making a new node creates it where it was originally clicked. But when dragging a connection from a preexisting node, even when is close to the original node, creates it far away from the original node instead of where the mouse was located. See video below to see it the bug in action.

[Screencast from 2022-11-30 15-25-25.webm](https://user-images.githubusercontent.com/13603525/204901707-aa83c613-24e1-4a97-86c1-8395b20fae32.webm)

### Steps to reproduce

1. Create or add an AnimationTree node in the scene
2. Set AnimationNodeBlendTree as Tree Root
3. Create a new node (i.e Animation node) by right clicking anywhere on the AnimationTree graph
4. Drag a connection (The white dots alongside the nodes) from the node anywhere in the screen (either close or far away from the node) and select any type of node (i.e. Blend2 node)
5. Observe how the new node is created unnecessarily far away from the original, parent node 

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
The issue is likely in GraphEdit and how it handles new node position depending on zoom level.
