### ISSUE TITLE
`AnimationTree` state machine, the end of animation cuts off despite the use of `At End` transition

### ISSUE THREAD

**Issue by lufog** [godotengine/godot#69415]
### Godot version

v4.0.beta.custom_build (0bb1e89fb)

### System information

Windows 11, Forward, Geforce 1660 (526.98)

### Issue description

Sometimes when using the `AnimationTree` state machine, the end of animation cuts off despite the use of `At End` transition.

https://user-images.githubusercontent.com/10379487/204909849-fae80e93-29a9-4192-8a09-39d36eed01d3.mp4

### Steps to reproduce

- open project;
- select `AnimationTree` and play `Modulate` animation.

### Minimal reproduction project

[animation_transition_test.zip](https://github.com/godotengine/godot/files/10127389/animation_transition_test.zip)

**Comment by mrbaggins** [comment]
In wonder if this is related to my bug #69382 however I've tried moving my call method function earlier and not succeeded in resolving my problem.

**Comment by TokageItLab** [comment]
This issue may be fixed by #69415, please check it.

**Comment by TokageItLab** [comment]
This issue may be fixed by #69336, please check it.

**Comment by lufog** [comment]
@TokageItLab, yes, #69336 fixes this issue.
