### ISSUE TITLE
Unable to set `progress_ratio` on `PathFollow2D`.

### ISSUE THREAD

**Issue by bend-n** [godotengine/godot#69421]
### Godot version

4.0b6 / 860884bde

### System information

Archlinux x11

### Issue description

setting `progress_ratio` on PathFollow2D has no effect on position.

### Steps to reproduce

- make path
- make pathfollow
- make script
- set pathfollow progress ratio

### Minimal reproduction project

[bug.zip](https://github.com/godotengine/godot/files/10128093/bug.zip)

**Comment by TokageItLab** [comment]
cc @xiongyaohua

**Comment by bend-n** [comment]
> cc @xiongyaohua

It's the 2d curve though?

**Comment by KoBeWi** [comment]
You set the progress ratio to `1.0` and then assert that position is different than (0, 0), which is your last point. The test project is wrong, try ratio 0.5.

**Comment by bend-n** [comment]
Im sorry, i had the points reversed. I do think i had a legitimate issue with being unable to tween them though, ill see if i can make a new mrp.

**Comment by KoBeWi** [comment]
Note that you also have `loop` enabled, which might make the object loop back to the beginning.

**Comment by GyandwipDas** [comment]
This is still there in 4.3. It randomly comes up then I end up restarting godot and trying some variation to make it work. It seems to come up once you add more points and curves. This not only stops progress ratio (changing value goes back to default value) but also basically everything stops working (can't delete, add nodes or anything for that matter).

**Comment by KoBeWi** [comment]
@GyandwipDas Is this #96081?
