### ISSUE TITLE
EditorScenePostImport scripts can't add additional nodes to the imported scene

### ISSUE THREAD

**Issue by Flynsarmy** [godotengine/godot#69429]
### Godot version

4.0.beta6.official

### System information

Windows 11, Forward+, NVidia GeForce RTX 3070 TI

### Issue description

I have an Import Script set for a model on the Advanced Import Settings screen:
![image](https://user-images.githubusercontent.com/334808/204959002-de51e322-d74e-46c2-9960-a10bdd6da9f2.png)
The script prefixes the imported scene name with 'foo' and adds an `AnimationTimer` node. When reimporting the model and creating an inherited scene, I see the 'foo' prefix, but the `AnimationTimer` node was never added:
![image](https://user-images.githubusercontent.com/334808/204959178-99d4e0de-d1d6-440e-8211-f2ff747564e5.png)

### Steps to reproduce

* Create a `post_import.gd` script in your root directory with the following code:
```gdscript
@tool

extends EditorScenePostImport

func _post_import(scene: Node):
	var player: AnimationPlayer = AnimationPlayer.new()

	scene.add_child(player)

	scene.name = 'foo' + str(scene.name)

	return scene
```
* Have any file importable as a scene (for example a mesh in a GLB file).
* Double click it and in the 'Advanced Import Settings' window set the `import_script/path` setting to *res://post_import.gd*
* Click reimport and then right click on the GLB and click 'Create Inherited Scene'.

The scene will have the 'foo' prefix, but no `AnimationTimer`.

### Minimal reproduction project

Barebones repo available here: https://github.com/Flynsarmy/gd-editorscenepostimport-issue

**Comment by Calinou** [comment]
You probably need to define an `owner` for the node, so that the node is persisted to the scene file.

**Comment by Flynsarmy** [comment]
This was exactly what I was missing. Thank you so much!
