### ISSUE TITLE
Dynamically loading "tileset" resources and dropping frames, the interface will get stuck

### ISSUE THREAD

**Issue by xiaoliang6669** [godotengine/godot#69437]
000000000000000000000000000000000000000

**Comment by Calinou** [comment]
@xiaoliang6669 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by xiaoliang6669** [comment]
> @xiaoliang6669 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

#1801


[mrjustaguy](https://github.com/mrjustaguy) commented [on May 17](https://github.com/godotengine/godot-proposals/issues/1801#issuecomment-1128807920)
One thing to consider with this, it is quite possible that this is actually a PCIe Bottleneck.. I've found that with sufficiently gigantic assets, when they're instanced for the first time, the loading goes smoothly, but stutters when it's moving from RAM to VRAM, and which also explains why further instances don't cause the stutters, only the 1st one.

Similar result can be gotten by just using to load an asset on a thread, which will automatically move any Video Assets into VRAM once it is done loading into RAM (causing the stutter at that point)
Instancing the Asset at that point has no stuttering, as if it were instanced once.ResoruceLoader

hence the stutter from first time instancing, noise generation and the like are actually caused by PCIe Bottleneck, as it just overwhelms the PCIe bus with the transfer, preventing normal CPU<->GPU communication required for telling the GPU what to render which means the GPU is left idle during transfer, even if the GPU Doesn't need any of the data from the offending resources.

The only solution to this that I see is finding a way to limit how much bandwidth is used for moving assets to VRAM

**Comment by xiaoliang6669** [comment]
> @xiaoliang6669请上传[一个最小的复制项目](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project)，以便于故障排除。



> @xiaoliang6669 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.



Why don't you submit such a problem? It will lead to the collapse of the project of dynamic map loading game
