### ISSUE TITLE
WorldEnvironment canvas world not working

### ISSUE THREAD

**Issue by ha0986** [godotengine/godot#69432]
### Godot version

godot 4 beta 5

### System information

windows 11

### Issue description

i was trying to glow a line2d. then i notice, when i am selecting canvas option of the worldenvironment node this happen to my scene
![image](https://user-images.githubusercontent.com/118948165/204964210-369bc669-8609-43ba-b801-135df3811e3a.png)

on actual my scene looks like this.
![Uploading image.png…]()

### Steps to reproduce

don't have any idea.

### Minimal reproduction project

i think screenshots are enough to confirm this bug.

**Comment by clayjohn** [comment]
This bug was already reported and fixed. You need to download beta 6 as the fix was merged after beta 5 was released
