### ISSUE TITLE
editor in veryLoDPI mode shows crappy icons

### ISSUE THREAD

**Issue by curly-brace** [godotengine/godot#6944]
godot v2.2

**Issue description** (what happened, and what was expected):
upon switching the editor to veryLoDPI mode, it scales the UI icons down with very low quality filter
<details> 
  <summary>

Screenshot </summary>

   ![screenshot](http://s10.postimg.org/a3yeva23d/Screenshot_at_2016_10_27_15_32_14.png)
</details>

would be great to have it resize the UI images using bilinear filter :+1:

**Comment by akien-mga** [comment]
At this scale I don't think filtering would improve anything (if it's not used already).

**Comment by curly-brace** [comment]
here i've scaled a screenshot of the normal editor to the same size using gimp and qubic filter
<details> 
  <summary>Screenshot </summary>
   ![screenshot](http://s10.postimg.org/ddbthowc9/Screenshot_at_2016_10_27_15_44_08.png)
</details>

**Comment by akien-mga** [comment]
Ok, that's definitely better :)

**Comment by bojidar-bg** [comment]
Uhh, is it just me, or I just can't see the screenshots at all?

**Comment by curly-brace** [comment]
just click it. btw i came to a temp solution:
- get the source
- goto /tools/editor/icons
- run mogrify -resize 75% *.png
- compile!

**Comment by reduz** [comment]
we need to implement icon conversion directly from SVG in real time at some point

**Comment by djrm** [comment]
even with an svg renderer the icons will not look good on a sizes lower than 16x16, they are designed to match pixels at that scale, so if they are rendered at lower resolution, information will be lost. as far as i can tell this problem will never be fixed, until a different set designed to be pixel perfect at a lower resoultion is created (and i really struggled creating one with 16x16). of course a better result can be expected but not a perfect one.

**Comment by curly-brace** [comment]
my screenshots are gone, but they were fine even with 10x10 resolution, while using bicubic downscaling in gimp

**Comment by djrm** [comment]
This is now fixed, but dont expect super crisp icons at that resoultion.
ping @akien-mga

**Comment by akien-mga** [comment]
Awesome :) Fixed by #10433.
