### ISSUE TITLE
vscode Code synchronization issues

### ISSUE THREAD

**Issue by wayrboy** [godotengine/godot#69453]
### Godot version

4.0 beta 7

### System information

windows 10

### Issue description

When I set up the correct lsp server,vscode changes the code and godot cannot update it

text_editor/behavior/files/auto_reload_and_parse_scripts_on_save it's open

I'm sure I can refresh it when I don't set it correctly

### Steps to reproduce

vscode 1.73.1

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Can you reproduce this issue with other external editors?

**Comment by wayrboy** [comment]
> Can you reproduce this issue with other external editors?

Although the code is not refreshed, it runs as modified code

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/69485, which provides more information about the issue at hand.
