### ISSUE TITLE
Memory leak when opening a project in the editor

### ISSUE THREAD

**Issue by ec-j** [godotengine/godot#69450]
### Godot version

v4.0.beta6.official

### System information

Windows 10, Vulkan, AMD Radeon(TM) R7 Graphics (19.12.1)

### Issue description

When opening a project in the editor, RAM usage skyrockets in a few seconds, from somewhere around 70-90 mb to 3-4 GB, (I only have 8 GB of memory, it could go up even further)

### Steps to reproduce

Steps to reproduce:

- Open Godot_v4.0-beta6_win64.exe from the official download
- Create a new project (both forward+ and mobile have this issue)
- Open it

![image](https://user-images.githubusercontent.com/119608617/205092360-c46700f9-95f0-4249-b7f5-4aef1193d9d0.png)

![image](https://user-images.githubusercontent.com/119608617/205092598-2895d4e4-cb75-4c51-8911-f924846b7c82.png)

(CPU usage is normal, I have a old cpu)

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
I can't reproduce this issue on Windows 10 with an AMD ryzen CPU and AMD Radeon GPU

**Comment by Calinou** [comment]
@ec-j Do you have a laptop with hybrid AMD/NVIDIA graphics by any chance?

**Comment by ec-j** [comment]
Not really, i'm using a desktop with the A10 7890K APU, from 2016 i think

**Comment by Calinou** [comment]
Can you update to more recent graphics drivers, or is 19.12 all you can get?

**Comment by ec-j** [comment]
This APU has moved in 22.6.1 to legacy support, but newer versions of the graphic driver just suck, reason why i was using a old version.

Updating the drivers works, and the project loads up perfectly. 

I'm now using 20.10, and it works, it's most probably some Vulkan bug in the driver, as in 3.5.1 this didn't happen.

**Comment by ec-j** [comment]
__
