### ISSUE TITLE
Godot games keep freezing

### ISSUE THREAD

**Issue by comblock** [godotengine/godot#69464]
### Godot version

3.4.2.stable

### System information

OS: openSUSE tumbleweed KDE desktop environment

### Issue description

Turing Complete (written in godot) and Virtual Circuit Board (also written in godot) both freeze after a small amount after launching them. Tabbing out and in again results in my entire desktop environment freezing and my computer becoming unusable until I use ctrl+alt+delete to log out and in again which closes the game for me. 

(I did verify other games not written in godot work)

### Steps to reproduce

Run a godot game with opensuse tumbleweed KDE edition.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Which graphics card model and driver are you using? Are you using X11 or Wayland?

Can you reproduce this issue with the Godot editor itself, or an empty Godot project?

**Comment by akien-mga** [comment]
Probably a duplicate of https://github.com/godotengine/godot/issues/69352, OpenSUSE broke X11 in its last update.

**Comment by comblock** [comment]
> Which graphics card model and driver are you using? Are you using X11 or Wayland? If using Wayland, try switching to X11 which is generally more stable (especially on NVIDIA). Godot doesn't support Wayland yet and doesn't use SDL, so your desktop has to use XWayland to support it.

I'm running a radeon 6700xt 


> Can you reproduce this issue with the Godot editor itself, or an empty Godot project?

I will try that later

**Comment by comblock** [comment]
Duplicate of #69352
