### ISSUE TITLE
CharFXTransform has no "relative_index" equivalent in Godot 4

### ISSUE THREAD

**Issue by vmedea** [godotengine/godot#69461]
### Godot version

4.0beta6

### System information

Linux (but applies to every OS)

### Issue description

There used to be a [relative_index](https://docs.godotengine.org/en/stable/classes/class_charfxtransform.html?highlight=relative_index#class-charfxtransform-property-relative-index) property on `CharFXTransform`. It was removed in Godot 4, seemingly with no replacement.

It appears that `absolute_index` was replaced by `range`. However, it can be useful for some kinds of effect (in my case, a fade-in effect) to know the text position of the character in the tag content instead, of the global index. I don't think there is a way to get this right now?

### Steps to reproduce

No special steps required to reproduce.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
cc @bruvzg
