### ISSUE TITLE
Invalid Tile origin when set as Bottom Left

### ISSUE THREAD

**Issue by jejoivanic** [godotengine/godot#6946]
**Operating system or device - Godot version:** 2.1

**Issue description**:

I'm not sure if I'm misunderstanding the property, but when I set the _Tile Origin_ to _Bottom Left_ the tile is set like _Top Left_ but the origin is even higher and the texture is lower.

As _Top Left_ to compare
![godot bug tile origin 2](https://cloud.githubusercontent.com/assets/13970212/19788293/cb4322ea-9c7d-11e6-8700-187c18daca67.png)

As _Bottom Left_ with error
![godot bug tile origin](https://cloud.githubusercontent.com/assets/13970212/19788292/cb316eba-9c7d-11e6-9769-2af5921e3cbe.png)

**Comment by vnen** [comment]
This seems right to me, the tile image is placed at the bottom left of the tile.

**Comment by jejoivanic** [comment]
My bad, I was thinking in something  like this.

![godot tile](https://cloud.githubusercontent.com/assets/13970212/19789186/16a69d4c-9c84-11e6-842c-bd4935921507.png)

**Comment by eska014** [comment]
Til origin "Bottom Left" is specifically made for y-sorted TileMaps. In the TileSet, you manually set the origin/pivot for each tile (which is easy to do by pointing and pressing the `V` key). That origin is then anchored to the bottom-left (or whatever tile origin mode is selected) in the TileMap.

What this mode doesn't do is inverting Godot's y-axis. Godot has y0 on the top, so sprites and tiles are drawn below the origin. This makes Godot's coordinate system highly impractical for y-sorting, but the "Bottom Left" mode helps work around this.

This issue also has some explanation why this mode is useful #3892

**Comment by Noshyaar** [comment]
I'll close this as working as expected. If you want, you can open a new issue/request to implement new origin mode that accounts for tile size.
