### ISSUE TITLE
The editor is too laggy

### ISSUE THREAD

**Issue by xiaoliang6669** [godotengine/godot#69468]
000000000000000000000000000000

**Comment by xiaoliang6669** [comment]
> ### Godot version
> 4.0-beta7
> 
> ### System information
> win10
> 
> ### Issue description
> Editing these commands is slow
> 
> ### Steps to reproduce
> ![(PW7X H1E5$EFOHV@}%EY](https://user-images.githubusercontent.com/112788136/205189247-f6b2f692-99c1-46a6-ab2f-77eee971dd20.png)
> 
> ### Minimal reproduction project
> Editing these commands is slow

**Comment by Chaosus** [comment]
@xiaoliang6669 Use the edit button next time and attach the minimal reproduction project
