### ISSUE TITLE
Assigning a ViewportTexture to a 2D sprite results in error spamming

### ISSUE THREAD

**Issue by FritzK-Hub** [godotengine/godot#69469]
### Godot version

4.0.beta6

### System information

OS: Windows 10,  GPU: AMD R9 290,  Driver: 21.4.1,  Backend: Vulkan 

### Issue description

Whenever I have a ViewportTexture assigned to a 2D sprite the following error is being spammed:

Texture (binding: 0) should provide one ID referencing a texture (IDs provided: 0).
drivers/vulkan/rendering_device_vulkan.cpp:7675 - Condition "!uniform_set" is true.
Uniforms were never supplied for set (3) at the time of drawing, which are required by the pipeline

But it only happens if I switch to the 3DScene that I use for the viewport, save it, and go back to the main 2D scene. If I then remove the viewport texture from the sprite the errors stop. After reassigning the texture the error doesn't come back until I open and save the 3D scene again.

Funnily enough this also happens if I have another SubViewport in the main 2D scene which contains a 2D scene. Assigning the texture from that "2D" viewport to a 2D sprite, and then opening/saving the 3D scene, makes the error appear again.

Doing the same opening/saving progress but with an "unrelated" 3D scene nothing bad happens.

### Steps to reproduce

In the minimal reproduction project:
- Open all the scenes
- Assign one of the viewports as a texture for one of the 2D sprites in the 'Main' scene
- Switch to the '3DScene' scene
- Save it and go back to the 'Main' scene
- The error should appear

### Minimal reproduction project

[ViewportBug.zip](https://github.com/godotengine/godot/files/10137282/ViewportBug.zip)

**Comment by Shadetheartist** [comment]
I get this as well. It could have something to do with the following error, which i get when trying to save the 2D scene.

`Can't save resource to empty path. Provide non-empty path or a Resource with non-empty resource_path`

**Comment by Anixias** [comment]
I not only get this error, mine also complains that the Viewport at the given path simply does not exist, despite looking at Remote in the Debugger to see that it really does.

**Comment by Luke9389** [comment]
I also get this. 

Interestingly, the error does not appear when running the [3d in 2d demo](https://github.com/godotengine/godot-demo-projects/tree/master/viewport/3d_in_2d), which leads me to believe we're configuring something incorrectly.

**Comment by mattdiener** [comment]
(Info, C#) I ran into this while working on an EditorPlugin. In `_Forward3DDrawOverViewport`, I made a call to `viewportControl.DrawTexture` with a texture that I got from a `Viewport _viewport` via `Viewport.GetTexture()`.

Once `_viewport` exited the tree, this started spamming. I believe it was due to the [cached draw command](https://github.com/godotengine/godot-docs/blob/708aea71ab918bdb6cb42a9210a4391c720447ef/tutorials/2d/custom_drawing_in_2d.rst#updating) continuing to draw a `ViewportTexture` from a disposed `Viewport`. I resolved this with an added call to `QueueRedraw` when my Viewport exits the tree.

**Comment by olympian-mods** [comment]
> I also get this.
> 
> Interestingly, the error does not appear when running the [3d in 2d demo](https://github.com/godotengine/godot-demo-projects/tree/master/viewport/3d_in_2d), which leads me to believe we're configuring something incorrectly.

For me this error also happens in the [3d in 2d demo](https://github.com/godotengine/godot-demo-projects/tree/master/viewport/3d_in_2d) demo in Godot 4.0.2. So this seems to be a general problem and not an incorrect config on our part.

**Comment by olympian-mods** [comment]
> something that seems to have fixed it for me is setting the viewport texture as **not** local to scene

Thanks for the hint. Unfortunately for me this makes it even worse. I now get the error _"get_height: Viewport Texture must be set to use it"_ when starting the scene. And the editor log is still overflown with _"should provide one ID referencing a texture"_.

(Godot 4.0.3)

**Comment by MASTRIO** [comment]
I'm also having this exact issue (except it is happening with a TextureRect and not a Sprite2D)

**Comment by CLMagnus** [comment]
seems to be a general viewporttexture issue rather than an issue with sprite2d/texturerect i would imagine

**Comment by Rindbee** [comment]
It seems that saving the sub scene causes the `Viewport` in the main scene to be replaced with a new instance.

**Comment by CrashCanHero** [comment]
Not much more here I can say other than I am having the same problem as originally described on Godot 4.1.1, also bump I guess

**Comment by YuriSizov** [comment]
@CrashCanHero This issue was addressed by a PR included in Godot 4.2 and 4.1.3, please try one of those versions.

**Comment by CrashCanHero** [comment]
@YuriSizov Yeah looks like it, guess I should have checked. Was confused because at first it didn't seem like it, but after a restart (and making a test project) I can no longer reproduce the issue

**Comment by disukomusic** [comment]
Godot Engine v4.3.stable.mono.official.77dcf97d8 - https://godotengine.org
Vulkan 1.3.280 - Forward+ - Using Device #0: NVIDIA - NVIDIA GeForce GTX 1660


Having this error occur still! Assigning both a New Viewport Texture or using a saved one and then switching scenes back and forth results in the error spam. 
![image](https://github.com/user-attachments/assets/0c541a6f-0bb1-4450-b9b0-72a6a480196c)

![image](https://github.com/user-attachments/assets/4f1633c0-243b-4377-85bc-8afbcea0fc22)
