### ISSUE TITLE
Setting @onready var variable value by calling a function inside the same class causes a parser bug.

### ISSUE THREAD

**Issue by dewareva** [godotengine/godot#69479]
### Godot version

v4.0.beta4.official [e6751549c].

### System information

Windows 11.

### Issue description

> What doesn't work…

I have a variable called `_state_list` with the `@onready` annotation whose value is set by calling the method `_fetch_state_list()`:
```gdscript
# This is a custom state machine class that extends node.
@export var state_machine: StateMachine

@onready var _state_list: Array[StringName] = _fetch_state_list()

func _fetch_state_list() -> Array[StringName]:
	_state_list.clear()
	
	for child in state_machine.get_children():
		if child is State:
			_state_list.append(child.name)
	
	return _state_list
```

The value assignment itself works with no issues, but the editor keeps displaying this pair of error messages in the output panel:
```
  modules/gdscript/gdscript_analyzer.cpp:668 - Parser bug (please report): tried to assign unset node without an identifier.
  Parser bug (please report): Trying to check compatibility of unset value type
```

This pair of error messages appear when I opened the project; each time I opened, or in any way interacted with, the `.gd` file that contains the code in the topmost code block; and when I run the project. They also appear five-six times for every keystroke I made editing the script, and simply writing a few lines could easily flood the output panel with hundreds of error messages.

This pair of error messages also appear in the debugger panel each time I run the project:

```
E 0:00:00:0677   resolve_class_interface: Parser bug (please report): tried to assign unset node without an identifier.
  <C++ Source>   modules/gdscript/gdscript_analyzer.cpp:668 @ resolve_class_interface()
E 0:00:00:0677   is_type_compatible: Parser bug (please report): Trying to check compatibility of unset value type
  <C++ Error>    Condition "!p_source.is_set()" is true. Returning: true
  <C++ Source>   modules/gdscript/gdscript_analyzer.cpp:4098 @ is_type_compatible()

```

> […] and how do you expect it to work instead?

I expect it not to output error messages, especially because the variable value assignment actually works. I have also tried using the latest official version (v4.0.beta7.official [0bb1e89fb]), but it still happens.

Is this a bug or am I just doing things wrong?

### Steps to reproduce

Attach a script onto any node that contains this code block:
```gdscript
@onready var test_variable: int = fetch_test_variable()


func fetch_test_variable() -> int:
	return 10
```

It happens every time there is a variable with the `@onready` annotation whose value is assigned by calling a method that is inside the same class. The variable and return type and value do not seem to matter, I just happened to use an `int` value.

It does not happen if the method comes from outside the class; I have tried assigning a value to the variable by calling a method from a singleton (autoload) and from a child node, and no error messages appeared. It also does not happen if I set `test_variable` on the `_ready()` function, which I thought was what `@onready` was supposed to emulate.

### Minimal reproduction project

I think it is pretty trivial to reproduce this error, but I uploaded a reproduction project anyway.

[Onready Error.zip](https://github.com/godotengine/godot/files/10139334/Onready.Error.zip)

**Comment by adamscott** [comment]
Quick note. You can highlight code using the typing of a block of code in Github for better readability.

\`\`\`gdscript
[your code here]
\`\`\`

**Comment by adamscott** [comment]
I confirm the issue on master ([6f1d4fd](https://github.com/godotengine/godot/commit/6f1d4fd8871155efcb29d115a7168879948e1cf3)).

Just tested the MRP with the work of @rune-scape (PR #69471) and it fixes this issue.

**Comment by dewareva** [comment]
> Quick note. You can highlight code using the typing of a block of code in Github for better readability.

Thanks for the info, I've never done anything on GitHub before. I just edited the post, and it's much more readable!


> I confirm the issue on master ([6f1d4fd](https://github.com/godotengine/godot/commit/6f1d4fd8871155efcb29d115a7168879948e1cf3)).
> 
> Just tested the MRP with the work of @rune-scape (PR #69471) and it fixes this issue.

Hopefully the PR will be approved soon!
