### ISSUE TITLE
Godot 4 beta 7 cannot export/build on Windows11

### ISSUE THREAD

**Issue by Intervel** [godotengine/godot#69472]
### Godot version

4.0 beta 7

### System information

Windows 11,  Rtx 3090

### Issue description

just download the export templates and install it.

make simple scene like this :

![control tscn - test - Godot Engine 12_2_2022 12_28_36 PM](https://user-images.githubusercontent.com/86478025/205221488-8852d8b0-3ab5-48b6-b6eb-1bb08088d798.png)

now, go try export it. 

it will throw this error :

![1](https://user-images.githubusercontent.com/86478025/205221341-3bf802af-5a68-41eb-bc05-4e84d0109262.png)

possible crylic recursion or whatever that is

### Steps to reproduce

as above

### Minimal reproduction project

as above

**Comment by Intervel** [comment]
in my main build the game will export with this error, then i open the .exe file.

it will close immediatly.

i check everything in editor , 0 error

**Comment by bruvzg** [comment]
> it will throw this error :

What exactly is not working? There are no export errors in the log, and two `rceedit` messages suggests export was successful. `Transient parent` error is not related to export process and can be safely ignored.

**Comment by Intervel** [comment]
![2](https://user-images.githubusercontent.com/86478025/205226077-b08fca44-73ef-4525-8778-a52d39db74d2.png)

here is it

**Comment by Intervel** [comment]
https://user-images.githubusercontent.com/86478025/205226235-b52223fc-8c58-487c-b076-a12e2a2c05cc.mp4

**Comment by bruvzg** [comment]
Please provide minimal reproduction project, export of the simple scenes seems to work fine. And `cyclic resource inclusion` errors are related to something in your project (and likely not Windows specific).

**Comment by vmikhav** [comment]
I had similar output on beta 6 on the next scene, but export was successful. If I remember correctly error notifications strarted to appear after I moved this scene to another folder.

```
[ext_resource type="Texture2D" uid="uid://bmnac0sq8kbk6" path="res://assets/sprites/MiniDwarfDemolitionist.png" id="1_vj30r"]

[sub_resource type="AtlasTexture" id="AtlasTexture_8yhgh"]
atlas = ExtResource("1_vj30r")
region = Rect2(0, 160, 32, 32)

[sub_resource type="AtlasTexture" id="AtlasTexture_aibj8"]
atlas = ExtResource("1_vj30r")
region = Rect2(32, 160, 32, 32)

[sub_resource type="SpriteFrames" id="SpriteFrames_4ybha"]
animations = [{
"frames": [SubResource("AtlasTexture_8yhgh"), SubResource("AtlasTexture_aibj8")],
"loop": false,
"name": &"hit",
"speed": 10.0 
}]
```

**Comment by Intervel** [comment]
i just got it working!

apparently u need to close all your editor tabs. then try to export it. it will not throw errors anymore!

hopefully this will helps other!
