### ISSUE TITLE
Godot crashes when a certain gdscript file is in the project folder

### ISSUE THREAD

**Issue by beamer159** [godotengine/godot#6947]
Issue experienced on Windows 7 and Windows 10 - Godot version 2.1

Description: When Godot has a certain gdscript somewhere within "res://", it crashes when this file is either previewed in the file browser, opened, or saved within Godot. This problematic .gd file is attached to this issue. A way to prevent the crash is to mess with lines 30 and 31:

```
var x = 200 * cos(2 * PI / (0))
var y = 200 * sin(2 * PI / (0))
```

If either of these lines are deleted, Godot won't crash. If either of these lines are changed enough, Godot won't crash. It makes no sense to me why the editor seems to crash only in the case that these lines are present in a file.

Steps to reproduce:
1. Download the attached file
2. Change the file extension from .txt to .gd
3. Create a new Godot project
4. Put the downloaded .gd file in the Godot project's root directory
5. Open the project
6. Open the .gd file within Godot
7. Try to save the .gd file a number of times

Godot should crash at some point during this process.

[Game.txt](https://github.com/godotengine/godot/files/557495/Game.txt)

**Comment by henriquelalves** [comment]
I'm not sure what is happening, but I couldn't confirm this with the steps you described and the Game.gd file. Could you provide the project itself that is crashing?

**Comment by beamer159** [comment]
Attached is a project showing the problem. To get it to crash, you have to open the .gd file in Godot and go to File > Save to save the .gd file.
[Test.zip](https://github.com/godotengine/godot/files/560191/Test.zip)

**Comment by henriquelalves** [comment]
On LinuxMint it won't crash, but running the latest Godot build on terminal, every time I save I'm given this: 
`ERROR: next: Condition ' !e ' is true. returned: __null
   At: core/hash_map.h:530.`
Not sure if this is related to the project crashing on Windows, but it sure looks like a bug.

**Comment by beamer159** [comment]
Just an update, this bug is still present in Godot 2.1.2.

**Comment by bojidar-bg** [comment]
Looking at the issue, it should be a bug in the gdscript parser's constant expression optimization (as it doesn't really guard for errors there).

**Comment by akien-mga** [comment]
Reopening as #7807 was reverted (better fix incoming, @hpvb and @tagcup are on it :D).
