### ISSUE TITLE
Godot 4 beta 7 HTML5 export fails to render (missing unpackUnorm4x8)

### ISSUE THREAD

**Issue by vmikhav** [godotengine/godot#69489]
### Godot version

4.0 beta 7

### System information

Windows 10, GLES3

### Issue description

HTML5 exported project fails to start in browser with next error:
```
USER ERROR: CanvasShaderGLES3: Fragment shader compilation failed:
ERROR: 0:378: 'unpackUnorm4x8' : no matching overloaded function found
ERROR: 0:378: '=' : dimension mismatch
ERROR: 0:378: '=' : cannot convert from 'const mediump float' to 'highp 4-component vector of float'
```
```
USER ERROR: CanvasShaderGLES3: Fragment shader compilation failed:
ERROR: 0:546: 'unpackUnorm4x8' : no matching overloaded function found
at: _display_error_with_code (drivers/gles3/shader_gles3.cpp:237)
USER ERROR: Method/function failed.
at: _compile_specialization (drivers/gles3/shader_gles3.cpp:337)
```
Issue is not presented in beta 6.

### Steps to reproduce

Run project in local browser

### Minimal reproduction project

N/A

**Comment by Chaosus** [comment]
Note that these functions are not supported by the older GLES versions (https://registry.khronos.org/OpenGL-Refpages/gl4/html/unpackUnorm.xhtml), maybe the wrappers for them could be written thought it's not trivial.

**Comment by clayjohn** [comment]
This is a regression from https://github.com/godotengine/godot/pull/69355
