### ISSUE TITLE
[Godot 4] In gl_compatibility mode, shader cannot access two or more textures

### ISSUE THREAD

**Issue by MikhailMartianov** [godotengine/godot#69481]
### Godot version

Godot_v4.0-beta7_win64

### System information

Windows 10, GLES3, AMD5900, RTX3080, GLES3/Vulkan

### Issue description

The shader cannot receive more than one texture. If you pass a texture and a light map to the shader (using uv1, uv2 respectively), only one of the textures will be displayed. The example below uses Sample2D from a colored texture where there should be a light map, this should not be the case.
In rendering mode forward_plus or mobile everything works fine.

I have been experiencing this problem since version beta 5. Prior to that, this problem probably also occurred.

I used the VusualShader tool to build the shader.
![2](https://user-images.githubusercontent.com/83165702/205265847-0c8c135c-a575-4d45-9872-b2fa16eddc23.png)
![1](https://user-images.githubusercontent.com/83165702/205265841-77f60ef6-0e13-4bce-8293-679334873824.png)

Mode forward_plus / gl_compatibility 
![5](https://user-images.githubusercontent.com/83165702/205266153-5df354c1-377e-4608-856c-baa06cd1d84c.png)
![3](https://user-images.githubusercontent.com/83165702/205266142-f228e032-b135-43d6-bccc-926895a75e06.png)

### Steps to reproduce

You can minimally reproduce the problem by trying to pass two different textures into the shader to blend them in gl_compatibility mode.

### Minimal reproduction project

For convenience, I put together a special scene to demonstrate this problem. 
[example.zip](https://github.com/godotengine/godot/files/10139991/example.zip)

**Comment by Chaosus** [comment]
As far as I know, the OpenGL renderer is not completely ready for production. cc @clayjohn

**Comment by clayjohn** [comment]
I noticed this issue recently as well. I looked into it a bit but didn't find an obvious culprit. I will take another look soon
