### ISSUE TITLE
GDScript 2.0: Lambda function seemingly not being called when static method of class with inferred type is called inside

### ISSUE THREAD

**Issue by detomon** [godotengine/godot#69491]
### Godot version

v4.0.beta7.official [0bb1e89fb]

### System information

macOS Monterey 12.6.1

### Issue description

When assigning a class (local to script or global) to a local variable with inferred typing, then calls to static methods of that class using the variable inside a lambda function which is called by the static method will not call the lambda function. Using an instance of the class works. Also when the parameter of the method being called has not type `Callable`, the editor crashes.

### Steps to reproduce

The script below only prints

```
1
3
4
```

`2` is missing.

Can be run inside editor:

```gdscript
@tool
extends EditorScript


func _run() -> void:
	# inferring variable type with :=
	var inferred_type := TestClass

	# works
	inferred_type.call_fn(func () -> void:
		print(1)
	)

	# this crashes the editor
	#inferred_type.call_fn_no_type(func () -> void:
	#	print("crash")
	#	inferred_type.test()
	#)

	# does not get called for variable with inferred type and static method call to class
	inferred_type.call_fn(func () -> void:
		print(2)
		# works when removing this line
		inferred_type.test()
	)

	# no explicit type set
	var no_type = TestClass

	# works for variable without type
	no_type.call_fn(func () -> void:
		print(3)
		no_type.test()
	)

	# instance with inferred type
	var instance := TestClass.new()

	# works for instances
	instance.call_fn(func () -> void:
		print(4)
		instance.test()
	)


class TestClass:

	# parameter with type
	static func call_fn(fn: Callable) -> void:
		fn.call()

	# parameter without type
	static func call_fn_no_type(fn) -> void:
		fn.call()

	static func test() -> void:
		pass
```

### Minimal reproduction project

[issue.zip](https://github.com/godotengine/godot/files/10145978/issue.zip)

**Comment by adamscott** [comment]
Citing [CONTRIBUTING.md](https://github.com/godotengine/godot/blob/e032152494646da7933fbef13d2914c67b09ce9a/CONTRIBUTING.md#reporting-bugs)

> On the contributors' end, recreating a test project from scratch takes valuable time that can be saved by uploading a _minimal_ project.

> To speed up our work, **please upload a minimal project** that isolates and reproduces the issue. This is always the **best way for us to fix it**. We recommend attaching a ZIP file with the minimal project directly to the bug report, by drag and dropping the file in the GitHub edition field. This ensures the file can remain available for a long period of time. Only use third-party file hosts if your ZIP file isn't accepted by GitHub because it's too large.

> We recommend always attaching a minimal reproduction project, even if the issue may seem simple to reproduce manually.

Please join a MRP. (even if the script seems quite simple, thank you!)

**Comment by detomon** [comment]
@adamscott Done! See `editor_script.gd` in root directory.

**Comment by adamscott** [comment]
From what I tested so far, it seems that this code works:

```gdscript
inferred_type.call_fn_no_type(func () -> void:
	print("do not crash")
)
```

It's related to the number of captured arguments for the lambda. It captures the scope when it refers to other variables inside the lambda, I think, but tries to pass each of the captured variables as an argument for the lambda, which fails because the lambda doesn't have any parameters, hence the crash.

https://github.com/godotengine/godot/blob/daf168f4c821980a6a06fde67057f6a14d9e20c6/modules/gdscript/gdscript_lambda_callable.cpp#L69-L87

**Comment by IceflowRE** [comment]
Not sure if this is the right issue, i cant follow completely, but does this issue covers this case?
```gdscript
static func foo() -> void:
    print("foo")

static func use_foo() -> void:
    var foo_func: Callable = foo  # <- this does not work: Invalid get index 'foo' (on base: 'Nil')
```
