### ISSUE TITLE
Node rename triggered after changing value in Inspector

### ISSUE THREAD

**Issue by yedpodtrzitko** [godotengine/godot#69497]
### Godot version

4.0.beta7.official

### System information

MacOS 13, MB Air M1

### Issue description

When a value of property in Inspector is changed, node rename is triggered. See attached video

https://user-images.githubusercontent.com/162526/205329703-012e327b-6ebb-4746-acff-121fcabc4479.mov

### Steps to reproduce

- select a property in inspector (eg. size)
- change the value
- submit the change with Enter
- rename of selected node in Scene panel is initiated

### Minimal reproduction project

- not a project specific issue

**Comment by Calinou** [comment]
Can you reproduce this on 3.5.1?

**Comment by Sauermann** [comment]
Plesse habe a look at #69160

**Comment by yedpodtrzitko** [comment]
Seems like the same issue, so I'll close it in favour of that one.

**Comment by yedpodtrzitko** [comment]
> Can you reproduce this on 3.5.1?

does not happen on 3.5.1
