### ISSUE TITLE
ButtonMask return middle when setting both left and right

### ISSUE THREAD

**Issue by eraffaelli** [godotengine/godot#69500]
### Godot version

4.0 beta 6/7

### System information

Windows 10

### Issue description

When setting the **button_mask** of a button to both left and right (as per the documentation) so we can use both clicks, getting said **button_mask** return **middle** instead of returning either **left** or **right** depending on which mouse button has been used.

### Steps to reproduce

Add a Node, create a button then set its mask and add it to the node.

```csharp
Button btn = new Button();
btn.ButtonMask = MouseButton.Left | MouseButton.Right;
GD.Print("btn.ButtonMask value ", btn.ButtonMask);//return middle

btn.Pressed += () => 
{
	GD.Print("btn.ButtonMask : ", btn.ButtonMask);//return middle
};
btn.SetSize(new Vector2(100, 100));
AddChild(btn);
```

Then click it using either the left or right click of the mouse. The print return middle but should return which mouse button has been used.

### Minimal reproduction project

N/A

**Comment by adamscott** [comment]
Citing [CONTRIBUTING.md](https://github.com/godotengine/godot/blob/e032152494646da7933fbef13d2914c67b09ce9a/CONTRIBUTING.md#reporting-bugs)

> On the contributors' end, recreating a test project from scratch takes valuable time that can be saved by uploading a _minimal_ project.

> To speed up our work, **please upload a minimal project** that isolates and reproduces the issue. This is always the **best way for us to fix it**. We recommend attaching a ZIP file with the minimal project directly to the bug report, by drag and dropping the file in the GitHub edition field. This ensures the file can remain available for a long period of time. Only use third-party file hosts if your ZIP file isn't accepted by GitHub because it's too large.

> We recommend always attaching a minimal reproduction project, even if the issue may seem simple to reproduce manually.

And especially for your issue, to know if it's a Godot issue or a dotnet issue:

> **Note for C# users:** If your issue is _not_ .NET-specific, please upload a minimal reproduction project written in GDScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a .NET setup available.

Please join a MRP.

**Comment by eraffaelli** [comment]
> On some hardware or OSes (such as laptop trackpads), clicking both the left and right mouse button at the same time will produce a middle click. Please try to reproduce this with an external mouse.

I may have been a little unclear but I'm not trying to click both at the same time, just that using either left click or right click (only one of the two at a time) in that setting return middle.
Unless I misunderstood that setting?

> Please join a MRP.

Yes but it was also said than if the code was small enough it wasn't needed.
But anyway here's a csharp one.
I didn't found a way to get the button from the clicked function in the on_pressed in gdscript yet so I couldn't check in GDscript.

[buttontest_csharp.tar.gz](https://github.com/godotengine/godot/files/10149509/buttontest_csharp.tar.gz)

**Comment by adamscott** [comment]
> Required, unless the reproduction steps are trivial **and don't require any project files to be followed.** In this case, write "N/A" in the field.

In that case, having to add a C# file (considering that not all builds have dotnet enabled), it renders the contributors life much more easier just to unzip a project and run Godot with the extracted path.

**Comment by DissonantVoid** [comment]
can confirm both with and without C# oddly enough.. I made a minimum example for Gdscript based on original code:
[input_issue.zip](https://github.com/godotengine/godot/files/10281823/input_issue.zip)

**Comment by eraffaelli** [comment]
> one last edit, if you want to retrieve a specific button index from the mask instead of checking for the value of `btn.button_mask` you can do `btn.button_mask & MOUSE_BUTTON_MASK_LEFT`

I'm not sure if I understand correctly your sentence about this part, this only return Left all the time (or right if I check MASK_RIGHT).

**Comment by DissonantVoid** [comment]
open this project in Godot 4 and checkout how the code works: 
[input_issue.zip](https://github.com/godotengine/godot/files/10290168/input_issue.zip)

**Comment by eraffaelli** [comment]
Ok I see what you did but that doesn't concern the problem at all.
I don't have a problem checking what kind of click the button can have, I'm interested of knowing which click has been done when the button has been clicked, which I thought ButtonMask was returning in the clicked signal.

**Comment by DissonantVoid** [comment]
exactly! the mask is not meant to be used to check for input, but for the engine to know which button to count and which to ignore. you can use the `gui_input` to check for clicks and it would look something like this:
``` gdscript
   func _on_gui_input(event):
	if event is InputEventMouseButton and event.pressed and event.button_index == MOUSE_BUTTON_LEFT:
		print("Left Button Pressed")
```

**Comment by eraffaelli** [comment]
Yeah I knew about that function but I wanted to get the information directly from the clicked button signal.
Anyway, thanks for the answers.
