### ISSUE TITLE
Editor Code Completion using $Node reference does not work.

### ISSUE THREAD

**Issue by jcarlosrc** [godotengine/godot#69501]
### Godot version

4.0 Beta 7

### System information

Windows 10

### Issue description

Autompletion does not show proper hints when referencing a child node with the $ChildNode. $ChildNode has a very clear known type in the editor so that it should hint the appropiate methods of the class. In the video, there is a character body 3D in the tree. However, if we reference it with the $CharacterBody3D the editor does not show the methods of a CharacterBody3D class like move_and_slide().

https://user-images.githubusercontent.com/8985409/205352607-f01ecdae-da7e-4282-a1f3-633420684a73.mp4

### Steps to reproduce

Create a scene and add a $MyChildNode3D child to it. Then add a script to the scene and type $MyChildNode3D. The editor should show the methods a Node3D has. However it does not.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
`$` does not use type hints, so this is expected. If you use `($Node as NodeType).something` (where `NodeType` is a class type), it'll work

**Comment by Deozaan** [comment]
I agree that it seems strange to have to specify the class type when referencing a node for code completion hints to die up.

What I do in the meantime is `onready var my_var := $MyNode as NodeType` and then I get proper code hints whenever I use `my_var` anywhere in my script.
