### ISSUE TITLE
"Create Version Control Metadata" pop up window is glitching

### ISSUE THREAD

**Issue by Wasabi-Cheetah** [godotengine/godot#69509]
### Godot version

Godot 4.0 Beta 7

### System information

Ubuntu 22.04 LTS, AMD RX570 8GB

### Issue description

When pressing "Create Version Control Metadata" a glitching window pops up, tested on both Standard and .NET 6.0 versions of Godot. 
![Godot Create VC Metadata](https://user-images.githubusercontent.com/45925149/205366607-508ccfd3-ab1f-4a53-b182-3a48602c926d.png)

### Steps to reproduce

At the top left menu, click on Project > Version Control > Create Version Control Metadata

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Which rendering backend are you using in the project?

Does resizing the window fix its appearance?

Can you reproduce this after enabling **Single Window Mode** then restarting the editor?

**Comment by Wasabi-Cheetah** [comment]
Oh, I didn't take 2 of those points into consideration, but after noting them:
- I am using Forward+, tested on Mobile and same issue, GL Compatibility though just shows a black screen
- Resizing does NOT fix it in any of them
- Single Window Mode DOES fix it in all 3

**Comment by dogyx** [comment]
Can reproduce in alpha 17.
Can reproduce in alpha 16 and 15 but in addition to the window being glitched out it's also constantly flickering/flashing.
Can not reproduce in alpha 14.

**Comment by TomSpalango** [comment]
Confirming Wasabi-Cheetah's results in beta7.  Also adding that if you minimize/restore or maximize the window, the contents remain black (no change).

In Single Window Mode, behavior is as expected.

**Comment by Calinou** [comment]
@dogyx @TomSpalango Which operating system and graphics card model are you using?

**Comment by TomSpalango** [comment]
OS: Windows 11 Home, Version 21H2, OS build 22000.1219
GPU: GTX 3080

Two monitor setup: 
A: Acer Predator XB271HU - 27" - 1440p, 144Hz
B: VX248H - 24"- 1080p, 60Hz

Issue remains when Single Window Mode is OFF, regardless of which display I drag the main window to.

**Comment by Zireael07** [comment]
@TomSpalango What happens if you disconnect one of the monitors? I have a feeling the two monitor setup might be at fault, as it's somewhat of a rarity among Godot users

**Comment by TomSpalango** [comment]
I also just tested the opposite.  Unplugged the 27" and kept the 24" plugged in, to eliminate possibly some refresh rate or other setting of the physical monitor hardware.  Same behavior existed.

**Comment by dogyx** [comment]
OS: Fedora 37 (KDE)
GPU: RX 6600
Monitor: 1440p@144hz

**Comment by AndreiSchapov** [comment]
Same here, 4 Beta 7, Create Version Control Metadata window is purple, as if a texture was missing. Macbook Air M1, external 24" monitor.
