### ISSUE TITLE
Touch emulates mouse: improper button passed for taps

### ISSUE THREAD

**Issue by dave2** [godotengine/godot#69517]
### Godot version

v4.0.beta7.official [0bb1e89fb]

### System information

Android 9, Moto G6, gl_compatability

### Issue description

Probing the GUI events while running on Android gives me the following event passed to ``_gui_input()``:

```
InputEventMouseButton: button_index=0, mods=none, pressed=true, position=((106, 124)), button_mask=0, double_click=false
InputEventMouseButton: button_index=0, mods=none, pressed=false, position=((106, 124)), button_mask=0, double_click=false
```

This is emulated from touch, but contains ``button_index`` equal to 0. It should be 1. When running on a desktop, it correctly reports the button index as 1:

```
InputEventMouseButton: button_index=1, mods=none, pressed=true, position=((124, 87)), button_mask=1, double_click=false
InputEventMouseButton: button_index=1, mods=none, pressed=false, position=((124, 87)), button_mask=0, double_click=false
```

I looked at the emulation code and I can't see why ``MouseButton::LEFT`` being set would result in 0, but the log above doesn't lie.

Note: using ``gl_compatibilty`` on this project because the Android device is failing to start using Vulkan due to ``R8_Uint`` error on startup.

### Steps to reproduce

Run MRP. Tap or click button

### Minimal reproduction project

[example.zip](https://github.com/godotengine/godot/files/10145313/example.zip)

**Comment by akien-mga** [comment]
CC @m4gr3d

**Comment by exoticorn** [comment]
@dave2 I have implemented an experimental fix for #69536 in https://github.com/exoticorn/godot/tree/fix-android-touch-input and uploaded export templates with this fix to https://share.exoticorn.de/godot4-git-input-fix-android_export_templates.zip

It is indeed likely that both these issues are actually the same bug, so it might be helpful to try out this fix on your device if possible. (Either by compiling your own export templates from my branch, or by using my pre-built ones (as long as you are comfortable running "random" export templates from the internet)).

**Comment by spatker** [comment]
I tried this commit and touch input is now fixed on android for me.

**Comment by exoticorn** [comment]
@spatker So you had the same issue on your device and my commit fixed it? That's great to hear.

In order to gather information about this issue: Can you write on which device / Android version you ecnountered this issue?

**Comment by spatker** [comment]
@exoticorn Yes, before this  touch input was not working, but now it is fixed with this commit.

I'm using Android emulator on Linux, the emulated phone is a Pixel 3A with API version 33, x86_64.
