### ISSUE TITLE
[4.0 Beta 7] TweenCallback does not find methods with parameters

### ISSUE THREAD

**Issue by valkyrienyanko** [godotengine/godot#69519]
### Godot version

v4.0.beta7.mono.official [0bb1e89fb]

### System information

Windows 10, RX 6600, 10400

### Issue description

`TweenCallback` can not find methods with parameters, although it can find methods without parameters just fine.

### Steps to reproduce

The following code will reproduce the error.

```cs
public partial class Node3D : Godot.Node3D
{
    public override void _Ready()
    {
        var tween = GetTree().CreateTween();
        tween.TweenCallback(new Callable(this, nameof(Foo)));
    }

    public void Foo(int x)
    {
        GD.Print("Foo!");
    }
}
```

Error shown in console
```
E 0:00:01:0468   step: Error calling method from CallbackTweener: 'Node3D(Node3D.cs)::Foo': Method not found
  <C++ Error>    Method/function failed. Returning: false
  <C++ Source>   scene/animation/tween.cpp:624 @ step()
```

### Minimal reproduction project

[Test2.zip](https://github.com/godotengine/godot/files/10145444/Test2.zip)

**Comment by raulsntos** [comment]
I believe that's expected, tween callbacks need to be parameterless. Unfortunately, Godot doesn't support typed Callables so the compiler can't help you here, but it would be the equivalent of `Action` in C#.

When porting your MRP to GDScript I get this error:

```
ERROR: Error calling method from CallbackTweener: 'Node3D(Node3D.gd)::foo': Method expected 1 arguments, but called with 0
```

The error in C# is not incorrect, `Foo(int)` and `Foo()` have different signatures so they are technically different methods and C# can't find `Foo()`, but the error could be more user-friendly, there's an issue about this already: https://github.com/godotengine/godot/issues/35910.

In GDScript, if the method you are using has parameters you can pass them using `bind` as explained in the [documentation](https://docs.godotengine.org/en/latest/classes/class_tween.html#class-tween-method-tween-callback):

```gdscript
tween.tween_callback($Sprite.set_modulate.bind(Color.red))
```

In C#, Callables don't have a `Bind` method, but you can use lambdas. The example in the documentation is outdated, it would be something like this:

```csharp
tween.TweenCallback(Callable.From(() => sprite.Modulate = Colors.Red));
```

**Comment by valkyrienyanko** [comment]
Thanks
