### ISSUE TITLE
Area2D  After adding input_event to the script - the function is blocked, and there is no way to edit it until a complete restart of the engine

### ISSUE THREAD

**Issue by InkRobert** [godotengine/godot#69510]
### Godot version

4.0 beta 7

### System information

Windows 11

### Issue description

Once the Area2D input_event is connected to the script, it can no longer be edited, the only way is to restart the engine completely!
![bind](https://user-images.githubusercontent.com/91805483/205372806-d9b1ff3a-bee3-4f8d-8ed7-30d5b1c7e7d5.png)

### Steps to reproduce

Connect Area2D input_event to script

### Minimal reproduction project

After restarting the engine - the problem is eliminated, so I do not know how to send it...

**Comment by adamscott** [comment]
Duplicate of #69348
