### ISSUE TITLE
[4.0 Beta 7] Editor crashes when parent and child class declare duplicate variable names

### ISSUE THREAD

**Issue by traceExcalibur** [godotengine/godot#69512]
### Godot version

4.0 beta7

### System information

Windows 10 (OS build 19044.2251)

### Issue description

I encountered an issue where a project abruptly closed on me, and the editor crashed whenever I tried to re-open it.

After some trial-and-error, I discovered that I'd accidentally tried to declare a variable in a parent class when that variable name was already being used by another class inheriting it. Normally, that would give you a parser error of `The member "[name]" already exists in a parent class.` But instead, it was just crashing my editor outright.

I first noticed this issue while working in 4.0 beta 6, tried downloading the newer version, and found it still exists in beta 7. I also have a copy of the 4.0 beta 2 editor, and the error does _not_ appear there.

The minimal reproduction I've attached should crash the editor if you try to open it. You can edit either "new_script.gd" or "new_script2.gd" and remove the offending variable declaration, and the project will be able to open. You can then try to put the variable declaration back in and the project should crash once it parses the code.

### Steps to reproduce

1. Create a .gd script named new_script containing:
```
extends Node
var test
```
2. Create a second script containing:
```
extends "res://new_script.gd"
var test
```
3. Crash should occur around the time the editor would normally display a parser error.

### Minimal reproduction project

[TestProjectBug.zip](https://github.com/godotengine/godot/files/10144941/TestProjectBug.zip)

**Comment by adamscott** [comment]
Hi! Thanks for the submitting the issue/finding the bug, I found the bug in master (6f1d4fd) and created a PR. #69520 
The issue should be resolved in the next beta.
