### ISSUE TITLE
Selecting node in editor does not scroll to correct node in scene tree

### ISSUE THREAD

**Issue by tobeks** [godotengine/godot#69513]
### Godot version

4.0 beta 7

### System information

Windows 10

### Issue description

In case when we have a lot of nodes in the editor, scene tree is not scrolled correctly to a newly selected node.
Selecting any node in the editor scrolls scene tree to node which was selected previously.

I have found that method ``tree->ensure_cursor_is_visible();`` in ``SceneTreeEditor::set_selected`` is called before the newly selected node is assigned to the tree.

![godot](https://user-images.githubusercontent.com/13313981/205410472-2bc97723-63b8-4e59-b119-0cd28edf2f08.gif)

### Steps to reproduce

1. Add about 25 sprites to editor and make sure that scene tree cannot show them all.
2. Select first node manually in the scene tree,
3. Select last node in the scene editor.

Result: Node is selected but tree is not properly scrolled to show selected node.

4. Deselect everything in the scene editor,
5. Once again select last node in scene editor.

Result: Node is selected and the tree is scrolled correctly to the last item.

I have also noticed that when option ``docks/scene_tree/auto_expand_to_selected`` is set to ``false`` there is no scroll to element even if it is expanded.

### Minimal reproduction project

[Demo.zip](https://github.com/godotengine/godot/files/10145038/Demo.zip)

**Comment by Calinou** [comment]
Can you reproduce this issue in 3.5.1?

**Comment by tobeks** [comment]
In version 3.5.1 it works fine.

**Comment by AThousandShips** [comment]
Regression from #59226 it looks like
