### ISSUE TITLE
Vulkan: Camera jitter when TAA is enabled on float=64 build

### ISSUE THREAD

**Issue by Qubrick** [godotengine/godot#69528]
### Godot version

v4.0.beta.custom_build [0ff874291] equivalent to beta 7

### System information

Windows 11, RTX2060 Super Desktop, Vulkan

### Issue description

Camera jitter when TAA is enabled on float=64 build. 

I tested on normal build (custom build without float=64) and official pre-build of Godot 4 beta 7 as well. 
There is no jittering on those builds. This only happens on float=64 build.

This also happens on previous version. For now, I only tested with beta 4 [e6751549c] and beta 7 [0ff874291].

In the video, you can see viewport before TAA is enabled, viewport after TAA is enabled and game window in respective order.

https://user-images.githubusercontent.com/41263042/205432231-effff425-8653-424c-992a-04b7ae754f91.mp4

### Steps to reproduce

Enable TAA in float = 64 build. 

I added mesh, directional light, and camera so you can see that jittering happens on game window too. 
But you can remove it all and look at jittering wireframe in editor viewport.

### Minimal reproduction project

Just open the project with float=64 build.
[camera_jitter_taa_float64.zip](https://github.com/godotengine/godot/files/10145976/camera_jitter_taa_float64.zip)

**Comment by Calinou** [comment]
For reference, TAA jitter is expected (as it's required to improve quality in still scenes), but it shouldn't be this strong.

**Comment by clayjohn** [comment]
This looks like the TAA pass isn't happening at all and instead the raw internal buffer is being used.

**Comment by DavidBradbury** [comment]
I have the same thing, but for now, it only seems to be affecting gizmos, not my imported meshes. For now I just turn it off while working, but it would be nice to turn off rendering settings while in the editor, but turn them back on when running. Maybe similar to Environment / Camera Attributes? (Which is a great change by the way)

**Comment by Calinou** [comment]
> but it would be nice to turn off rendering settings while in the editor, but turn them back on when running. 

This can be achieved with by enabling TAA in a Node3D script's `_ready()` function while leaving the project setting disabled:

```gdscript
extends Node3D

func _ready():
   get_viewport().use_taa = true
```

**Comment by Qubrick** [comment]
Seems like it's not just TAA. 
Enable **"Depth of Field Use Jitter"** option in Project Settings alone cause this too on [16a6bdd423aa85272837d0bc6b9e709febdb4ec0]

Maybe it's about Double Precision cause strong jittering on everything that use jitter?
