### ISSUE TITLE
Polygon2D not displaying in web build (Godot 4 beta)

### ISSUE THREAD

**Issue by d-bucur** [godotengine/godot#69533]
### Godot version

4.0.beta6

### System information

Windows 11, rendering: mobile, GPU: Intel Iris Xe (Integrated i7 11th Gen)

### Issue description

Noticed that if using a Polygon2D in a web export it won't display at all, while it does display correctly in the desktop version.

This happens when viewed both in Chrome for Windows and Chrome on Android on an actual mobile device.

I tried this in 3.5 and Polygon2D displayed correctly in the web build.

Here is the exported web build not displaying correctly: https://sirdorius.itch.io/godot-test

### Steps to reproduce

- Create a Polygon2D node
- Create some points and add a color
- Export to web build

### Minimal reproduction project

Attaching a small project that reproduces this
[polygon_web.zip](https://github.com/godotengine/godot/files/10146261/polygon_web.zip)

**Comment by adamscott** [comment]
Your exported build doesn't run correctly:

![image](https://user-images.githubusercontent.com/270928/205453699-2c48cea8-efe9-4a28-913c-e6f48349738c.png)

Please check your itch.io settings.

**Comment by d-bucur** [comment]
@adamscott what browser are you using? Currently Itch only supports Chrome because of some changes in Godot 4 as described [here](https://www.rafa.ee/articles/deploying-godot-4-html-exports/) and [here](https://github.com/godotengine/godot/issues/68180)

**Comment by adamscott** [comment]
Oh! I was using Firefox. I'm sorry!
