### ISSUE TITLE
Godot 4.0 Beta 7 doesn't work on Android

### ISSUE THREAD

**Issue by MecoCL** [godotengine/godot#69540]
### Godot version

4.0 Beta 7

### System information

Android 11 (GLES 3)

### Issue description

When I ever wanna launch the editor on my phone, it only gives me this screen. nothing works, the last beta update wasn't like this tbh...

![image](https://user-images.githubusercontent.com/103614257/205459096-6ed532b3-d8cc-4b36-b080-6c6c0b53e860.png)

https://user-images.githubusercontent.com/103614257/205459100-d92ac2d0-c204-4ef8-acd7-cb6b76062358.mp4

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
Beta 6 didn't support GLES3 on Android. Perhaps you were running the Vulkan renderer and didn't realize it. 

Could you check the output from adb logcat and see if you are getting errors? 

Also could you post more information about your scene and settings?

**Comment by MecoCL** [comment]
how to check that output? Also There's no scene and settings, there's no even a project... I can't create one because of this

**Comment by aveeryy** [comment]
I can recreate this issue in my Samsung Galaxy Note 9 (Android 13, Mali-G72), here's the logcat: 
[godot_logcat.log](https://github.com/godotengine/godot/files/10147424/godot_logcat.log)

The same problem happens in any exported project with Beta 7 if the Android renderer is set to gl_compatibility

**Comment by MecoCL** [comment]
.......For the million time, I didn't export any projects, This is Godot itself

**Comment by clayjohn** [comment]
> I can recreate this issue in my Samsung Galaxy Note 9 (Android 13, Mali-G72), here's the logcat: [godot_logcat.log](https://github.com/godotengine/godot/files/10147424/godot_logcat.log)
> 
> The same problem happens in any exported project with Beta 7 if the Android renderer is set to gl_compatibility

Thanks for the logcat printout. I can see that the shaders are failing to compile. I have a feeling this is related to https://github.com/godotengine/godot/pull/69521
We added a workaround when exposing OpenGL on Android that we thought worked around an Android bug, but it appears my fears have been confirmed and it is an Adreno bug. 

Will fix this soon.

**Comment by MecoCL** [comment]
Thank you for your concern! <3

**Comment by clayjohn** [comment]
Fixed by https://github.com/godotengine/godot/pull/69521
