### ISSUE TITLE
Huge lags every few seconds. FPS drops to almost 0 with very simple scene.

### ISSUE THREAD

**Issue by seppoday** [godotengine/godot#69542]
### Godot version

4.0 beta6

### System information

Windows 10

### Issue description

I was trying 3D in Godot and made a very simple scene with controller and simple plane. Added WorldEnvironment node and for test I started to try to enable most of stuff. When I try to run that projects it is just unplayable. FPS drops every 1 sec.

Edit: After few minutes it started to work fine at 60 FPS. I will try to reproduce it and screen capture it.

### Steps to reproduce

Check project below.

### Minimal reproduction project

[3D_test.zip](https://github.com/godotengine/godot/files/10147295/3D_test.zip)

**Comment by Zireael07** [comment]
What is your gfx card? What is "most of the stuff" you enabled in WorldEnvironment? Things such as SDFGI, Glow are perf killers...

**Comment by Slluxx** [comment]
I have the same issue. It depends on what i turn on or off but right now i have the issue with SDFGI.

While it may be performance intense, the scene is almost empty, just one character and csg box to stand on. Its running (if uncapped) at over 200 fps.

I feel like a lagspike at pretty much constant intervals while the rest of the time the game runs just fine, means that there is something else wrong than just slow hardware.

**Comment by AThousandShips** [comment]
Please open a new issue and add details, including a minimum project as per the instructions in the report form 🙂
