### ISSUE TITLE
Cannot use negative numbers in `@export_range`

### ISSUE THREAD

**Issue by Kubulambula** [godotengine/godot#69544]
### Godot version

4.0.beta7

### System information

Irelevant

### Issue description

When using `@export_range()` it does not accept any negative ints and floats as both first and second argument.

### Steps to reproduce

`@export_range(-1, 1) var x`
copy-paste this code into any script and get:
`Parse Error: Expected float as argument 1 of annotation "@export_range".`

### Minimal reproduction project

see above

**Comment by MewPurPur** [comment]
Duplicate of #41183
