### ISSUE TITLE
Assertion failed: <null>

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#69549]
### Godot version

4.0 015dc49

### System information

Windows 10 x64

### Issue description

When `assert()` fails and it has no message, it says null.
```GDscript
@tool
extends EditorScript

func _run() -> void:
	assert(false)
```
```
gd:5 - Assertion failed: <null>
```
The message should say simply "Assertion failed.", but for some reason it stringifies null and passes it as message. Might be related to #62695

### Steps to reproduce

1. Run the code above

### Minimal reproduction project

N/A

**Comment by Mickeon** [comment]
Remember when it was argued that it accepting any Variant was fine in principle? Well, `null` is a Variant type too...
