### ISSUE TITLE
TileMap “set_cell” default parameters error

### ISSUE THREAD

**Issue by BeyondXinXin** [godotengine/godot#69554]
### Godot version

4.0.beat7

### System information

windos

### Issue description

I want to make a function of following the mouse to highlight.
I want to clear the previously highlighted cells by `set_cell(highlight_lay,hover_pos)`, But a lot of warnings.
Has to be changed to `set_cell(highlight_lay,hover_pos,-1,Vector2i(-1, -1),-1)`.

![tmp](https://user-images.githubusercontent.com/78600221/205475338-f99e219c-0747-4b0c-b5a9-a835fa3bf5a8.gif)

### Steps to reproduce

Use `set_cell(highlight_lay,hover_pos)` empty TileMap

### Minimal reproduction project

```gdscript
func draw_hover_tile(new_hover) -> void:
	var new_hover_pos = local_to_map(new_hover)
	if hover_pos == new_hover_pos:
		return
	set_cell(highlight_lay,hover_pos)
	# set_cell(highlight_lay,hover_pos,-1,Vector2i(-1, -1),-1)
	hover_pos = local_to_map(new_hover)
	set_cell(highlight_lay,hover_pos,highlight_tile_id,hover_atlas_coords)
	if select_pos != Vector2i() && hover_pos != select_pos :
		set_cell(highlight_lay,select_pos,highlight_tile_id,select_atlas_coords)
```

**Comment by BeyondXinXin** [comment]
https://github.com/godotengine/godot/pull/69555

**Comment by Zireael07** [comment]
So was this fixed or not?

**Comment by akien-mga** [comment]
No because it's not a bug, see the PR.
