### ISSUE TITLE
CanvasLayer hide() or show() can only run once per frame

### ISSUE THREAD

**Issue by IndustrialDonut** [godotengine/godot#69556]
### Godot version

3.5.1

### System information

Windows 10

### Issue description

The CanvasLayer, if you try to hide() it and then show() it on the same frame, stays hidden. However, the same thing works for a Control node just fine.

### Steps to reproduce

Add a CanvasLayer and put some item under it so you can see it in the editor, then run the following and watch that there is nothing visible.

```
func _ready() -> void:
	
	$CanvasLayer.hide()
	$CanvasLayer.show()
	
```

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
Fixed by #69558.
