### ISSUE TITLE
Wierd shadow using directional light

### ISSUE THREAD

**Issue by TandersT** [godotengine/godot#69566]
### Godot version

Godot Engine v4.0.beta7.mono.official.01ae26d31

### System information

AMD Radeon RX 5700

### Issue description

When updating from  v4.0.beta3 to v4.0.beta7 the shadows produced by the directional light looks very funky. This was not the case before, hence something I believe to have been introduced in recent betas. I believe any use of shadow with directional light seem to cause this issue.

![WierdShadow](https://user-images.githubusercontent.com/45199982/205489233-a094e02e-04a5-4ae3-bd7a-53c7c4d44bfc.gif)

### Steps to reproduce

Create a directional light, enable shadow and have a mesh produce shadow on another mesh.

### Minimal reproduction project

[RenderIssues.zip](https://github.com/godotengine/godot/files/10148445/RenderIssues.zip)

**Comment by Calinou** [comment]
This is expected, as a result of https://github.com/godotengine/godot/pull/68339. You need to tweak your directional shadow bias values accordingly. You'll need to increase Shadow Bias and/or Shadow Normal Bias, and find a value that resolves shadow acne without introducing too much peter-panning.
