### ISSUE TITLE
v4.0 Beta 7 - HTML5 Build - "SharedArrayBuffer" / "Cross Origin Isolation" Fail On My New Website?

### ISSUE THREAD

**Issue by BetaMaxHero** [godotengine/godot#69564]
### Godot version

v4.0.beta7.official [0bb1e89fb]

### System information

4.0 Beta 7 HTML5 Build On Website

### Issue description

Hi,

I bought a website.

I enabled "Cross-Origin Resource Sharing (CORS)"
https://support.hostinger.com/en/articles/6320787-do-you-support-cors

But when I run the Godot 4 HTML5 game on the new website:
https://betamaxheroes.org/games/TS3-Godot_4/index.html
I still get errors about "SharedArrayBuffer" and "Cross Origin Isolation"?

Any ideas?

Test on website below passes for "CORS" support:
https://cors-test.codehappy.dev/?url=https%3A%2F%2Fbetamaxheroes.org%2Fgames%2FTS3-Godot_4%2Findex.html&method=get

Jesse

### Steps to reproduce

Visit:  https://betamaxheroes.org/games/TS3-Godot_4/index.html

### Minimal reproduction project

NA

**Comment by Calinou** [comment]
This is a web server configuration issue, as I can't see the required headers in the response (Firefox devtools):

![image](https://user-images.githubusercontent.com/180032/205511363-93d9351c-251b-4dbb-a915-3fc70d5910bd.png)
