### ISSUE TITLE
Animation save file in external editor causes problems

### ISSUE THREAD

**Issue by Gramps** [godotengine/godot#6956]
**Windows 10 64-bit: Godot 2.1**

**Issue description**:
I save my animations as .tres files in a folder for editing in a separate editor.  However, if I have Godot open while editing these files, it causes some weird results.  Often times the line directly above a Call Func Track will turn into a Call Func Track and have it's key frames erased.  Sometimes no changes carry over at all when saved, but most times they will immediately change.  Also, for whatever, reason, a lot of the times the 6th track will also turn into a Call Func Track and have it's key frames erased.

**Steps to reproduce:**
Create an animation with about seven tracks (might happen with less); Call Func Track as last track.  Save animation as whatever.tres and open in an external editor (using Sublime Text) with Godot running.  Modify and it should make the last track a before the Call Func Track into one and erase it's key frames.

UPDATE:  Noticed this seems to happen if tracks above the one above the Call Func Track are deleted in the external editor or Godot.

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.
