### ISSUE TITLE
RichTextLabel's `scroll_to_line()` doesn't account for text wrapping

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#69577]
### Godot version

4.0 beta 7

### System information

Ubuntu 22.04.1 LTS

### Issue description

RichTextLabel's `scroll_to_line()` method doesn't seem to account for lines that wrap to multiple rows.
For example, if you have a line that wraps to 3 rows, the results start being displayed 2 rows lower down than they are supposed to. After a lot of such lines in a documentation page, the results may scroll entirely of view (which appears to be the cause of #58108)

### Steps to reproduce

Add RichTextLabel, give it text with some wrapping lines. Test `scroll_to_line(p_line)` on it.

### Minimal reproduction project

[RTL_bug.zip](https://github.com/godotengine/godot/files/10149214/RTL_bug.zip)

**Comment by bruvzg** [comment]
Not a bug, this is intentional, you should use `scroll_to_paragraph` instead to scroll to the source line (ignoring breaks), `_to_line` scroll to visible lines (including breaks). Same with the `get_line_offset`, `get_line_count`, and `get_visible_line_count`.

**Comment by MewPurPur** [comment]
This clears it up.
