### ISSUE TITLE
sprite.set_region_rect() and bleeding pixels

### ISSUE THREAD

**Issue by mishapsi** [godotengine/godot#6957]
Hi I'm not sure if this is intended behavior.  But I'm creating a pixel art editor in godot, one of actions I can perform is moving a layer (a sprite) by x and y, at first I was setting the position, but wanted to figure out how to crop it to the document bounds.  I started experimenting with set_region_rect(), and was able to get pretty close to the result I wanted.

The issue is that on the borders of the ImageTexture, if there is a pixel, and I shift layer using set_region_rect(), it will bleed infinitely on that border.  Here are some examples:

https://dl.dropboxusercontent.com/u/46434785/normal.PNG
https://dl.dropboxusercontent.com/u/46434785/fucked.PNG

Again not sure if this is intended.  I solved the issue by just making the imagetexture a few pixels larger, and accounting for that in all my put_pixel operations, but would be nice to not have to.

**Comment by Zylann** [comment]
Looks like the texture coordinates of the geometry representing your sprite are off, they are below 0 or above 1, which creates this repetition.
I think this will happen if you are setting a region that overlaps the border of the actual ImageTexture. You need to clamp the rectangle if you don't want to see that, or set REPEAT mode so the image will repeat instead of blocking on the last pixels.

**Comment by YeOldeDM** [comment]
A fix for this would be to have at least one pixel of transparency along all the borders of your image.  

Here's a recreation of your issue using the godot icon (its pixels go all the way to the edge so you get the bleeding):
![image](https://cloud.githubusercontent.com/assets/14256106/19826492/1cd9ba94-9d49-11e6-87e8-13cfaadf4021.png)

Here is the exact same setup, but using a texture that has transparent edges:
![image](https://cloud.githubusercontent.com/assets/14256106/19826497/41b64026-9d49-11e6-9255-082bcd0f010d.png)
I assume the bleeding is still going on, but it's bleeding transparent pixels ;)

**Comment by bojidar-bg** [comment]
You might want to use sprite offset instead.

**Comment by mishapsi** [comment]
@Zylann Makes sense, forgot godot uses a 3d engine and a fixed camera for 2d and sprites are just quads
@YeOldeDM Ended up doing just that, and it works well
@bojidar-bg Sprite Offset won't crop image outside of the desired bounds

**Comment by akien-mga** [comment]
> Makes sense, forgot godot uses a 3d engine and a fixed camera for 2d and sprites are just quads

I'd be interested in the source of this statement :)

**Comment by volzhs** [comment]
I'm interesting too. AFAIK, Godot has completely different rendering system for 2D and 3D.

**Comment by Zylann** [comment]
You are mixing what a 3D engine and a graphic card is. A graphic card uses polygons to represent anything to be drawn anyways. A 3D engine makes these polygon look like 3D objects. The 2D engine is not using the 3D engine, but uses the graphic card too, so it draws a quad with texture coordinates too.

**Comment by fguillen** [comment]
This is still happening in Godot 3.5 and it is preventing me to use my pixelart sprites and some specific shaders: 

- https://stackoverflow.com/questions/75472945/godot-2d-outline-shader-is-duplicating-edge-pixels
