### ISSUE TITLE
AnimationTree animation string values are superseded by RESET animation values when using Continuous update mode

### ISSUE THREAD

**Issue by valedict0** [godotengine/godot#69591]
### Godot version

4.0.beta7

### System information

Windows 10

### Issue description

https://user-images.githubusercontent.com/46985106/205547748-77292dd3-2679-4c43-8baf-299c153d60b0.mp4

AnimationPlayer has two animations: 'RESET' and 'animation'.
'RESET' sets the Label's text to "RESET", and the Label's modulate to Color.RED.
'animation' sets the Label's text to "animation", and the Label's modulate to Color.GREEN.
Both tracks are using the Continuous update mode.
The AnimationTree is set up to play 'animation' only.

What's expected when activating AnimationTree: Label is green with text "animation".
What actually happens: Label is green with text "RESET".

Changing update mode to Discrete or Trigger works as expected. Capture mode is, uh, also broken but in another way beyond my comprehension.

### Steps to reproduce

1. Open MRP.
2. Observe animations.
3. Set AnimationTree to active.
4. Observe unexpected results.

### Minimal reproduction project

[animation_tree_issue_587213874635874.zip](https://github.com/godotengine/godot/files/10150641/animation_tree_issue_587213874635874.zip)

**Comment by TokageItLab** [comment]
The problem with this is that `blend_variant()` does not support String types in the first place.

Although `interpolate_variant()` supports String type, we need to consider whether it can be defined for `blend_variant()` as well.

**Comment by TokageItLab** [comment]
I feel it is an interesting problem, but not an easy one.

For example, when there are three Strings "abcde" "fgh" "ij" and three blend input 0.2, 0.5, 0.3, I have no idea on how to blend it consistently neatly. It is difficult to mix strings, so even if one of the strings is prioritized, there will probably be inconsistencies that depend on the iterated order.

**Comment by akien-mga** [comment]
I don't think it makes s

**Comment by lufog** [comment]
I also encountered a situation where an animation not used in an AnimationTree is still applied to some extent. Is this the same problem, or should I open a new issue?

https://user-images.githubusercontent.com/10379487/228355166-b0b204b0-6a0b-49e8-80c5-de670b0e1b32.mp4

[AnimTreeModulate_Test.zip](https://github.com/godotengine/godot/files/11093863/AnimTreeModulate_Test.zip)

**Comment by TokageItLab** [comment]
@lufog It seems that your problem is just AnimationPlayer and AnimationTree applying at the same time.
