### ISSUE TITLE
Signal connection issues when opening a project using BoneAttachment3D but it isn't the last scene tab

### ISSUE THREAD

**Issue by cridenour** [godotengine/godot#69614]
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

v4.0.beta6.official [7f8ecffa5]

### System information

Windows 10

### Issue description

When using a BoneAttachment3D (with or without external skeleton), the following error is given if the scene with the BoneAttachment isn't the last open scene tab:

`Attempt to disconnect a nonexistent connection from 'GeneralSkeleton:<Skeleton3D#1995700239022>'. Signal: 'bone_pose_changed', callable: 'BoneAttachment3D::on_bone_pose_update'.`

When returning to the tab:
`Signal 'bone_pose_changed' is already connected to given callable 'BoneAttachment3D::on_bone_pose_update' in that object.`

### Steps to reproduce

1) Create a scene with a BoneAttchement3D
2) Open another scene after it
3) Reload current project

### Minimal reproduction project

N/A

**Comment by barrrettt** [comment]
same in beta9 mono. 

in my case, whenever I open the scene I get the error:

Signal 'bone_pose_changed' is already connected to given callable 'BoneAttachment3D::on_bone_pose_update' in that object.

But even so, I haven't seen any strange behaviour, everything works fine for me.

![image](https://user-images.githubusercontent.com/47840319/208973158-f9087102-e2ff-4e13-92c3-2fd80c621be8.png)

**Comment by BtheDestroyer** [comment]
Also a problem in Beta 10. Especially annoying when there are models with tons of bones (eg: fully rigged hands)

![image](https://user-images.githubusercontent.com/6555773/211116529-15f1ef48-1a24-4f0e-9d78-e11ac4c96aed.png)

**Comment by JohnPandich** [comment]
Confirmed to exist in Beta 17

**Comment by 18swenskiq** [comment]
Getting this in RC1 as well, however it no longer appears in the output console as it did in beta 16 (for me). It now from what I can see only appears if attempting to export from the linux build on the command line

**Comment by sigrudds1** [comment]
Still exists in 4.0.stable, output in either  console Windows 10 build.

**Comment by enxas** [comment]
Still exists in 4.0.3 stable on project launch.
![image](https://github.com/godotengine/godot/assets/8630984/6dc6b005-776f-4ed5-b231-19cac918e001)

**Comment by enxas** [comment]
Problem still exist in v4.1.beta1.mono.official [828ec2c5d] and I can provide [MRP.zip](https://github.com/godotengine/godot/files/11704039/MRP.zip) since no one did. Just open the project and console will be filled with errors.

**Comment by AThousandShips** [comment]
This is probably the same cause as #34752, along with many other signal related errors like this

**Comment by tung-nt-niteco** [comment]
I have the same problem. I am using Godot 4.0.3

**Comment by BliznyukNM** [comment]
Still an issue in 4.1.1.stable

**Comment by theraot** [comment]
v4.2.dev3.official [013e8e3af] - Windows 10

> Attempt to disconnect a nonexistent connection from 'Skeleton3D:<Skeleton3D#...>'. Signal: 'bone_pose_changed', callable: 'BoneAttachment3D::on_bone_pose_update'.

![image](https://github.com/godotengine/godot/assets/1212509/68530361-d80d-4b88-846a-8d70aab30248)

**Comment by cridenour** [comment]
That's interesting since the new IK system was reverted later in the 4.0 development cycle but the bug stayed around ha.

**Comment by comminux** [comment]
Please merge this change for the branch 4.1

**Comment by Ladnopoka** [comment]
I have this problem on 4.1. Please meger this change for 4.1

**Comment by theraot** [comment]
@Ladnopoka The fix for this will be in Godot 4.1.3 see https://github.com/godotengine/godot/pull/81695#issuecomment-1777663184
