### ISSUE TITLE
Can't write '@' on editor

### ISSUE THREAD

**Issue by rbarongr** [godotengine/godot#69612]
### Godot version

4 Beta

### System information

macOS (Intel and Apple Silicon)

### Issue description

In macOS you can switch between 2D, 3D, Script and AssetLibrary tabs on the top of the editor by pressing `option` + `number`. This works fine.

The problem is when you are writing code in the Script tab: when you try to write the `@` symbol you change to the second tab one because you use `option` + `2`, so you can't write the `@` symbol.

### Steps to reproduce

Open any script in the in-engine editor.
Try to write the `@` symbol.

Then you switch to the second tab, but there's no `@` written in the code.

### Minimal reproduction project

Any script opened in Godot's in-engine editor running on macOS will do.

**Comment by Chaosus** [comment]
I guess you can change these hotkeys in the editor's shortcuts, as a temporary solution, but definitely this doesn't sound good and need to be fixed.

**Comment by pseidemann** [comment]
hi,
just curious, which keyboard layout are you using?
for me @ is at shift+2 (english or us)

**Comment by rbarongr** [comment]
@pseidemann I'm using a Spanish keyboard

I didn't think about it when I posted the issue, thank you for pointing that out.

> hi,
> just curious, which keyboard layout are you using?
> for me @ is at shift+2 (english or us)

**Comment by Calinou** [comment]
Which exact 4.0.beta version are you using? This should have been fixed a few months ago, see https://github.com/godotengine/godot/issues/61468.

**Comment by rbarongr** [comment]
v4.0.beta7.official [0bb1e89fb]

I'm using ES keyboard layout from Spain: [https://en.wikipedia.org/wiki/List_of_QWERTY_keyboard_language_variants#Spain](url)
