### ISSUE TITLE
Game runs in Godot but crashes when built. How can I debug the problem of the built version?

### ISSUE THREAD

**Issue by therealrobster** [godotengine/godot#6961]
**Operating system or device - Godot version:**
OSX 10.11.6 - Godot Stable 2.1 OS X

**Issue description** (what happened, and what was expected):
I am running the latest 2.1 stable on OS X.
I am building for OSX.

When I run the built game via the finder it loads to my menu fine. Things are there, options buttons work, but when I hit PLAY and the scene goes to change to the game scene it locks up and I have to shut down the app.

I exported again with the Debugging Enabled set to True and when the problem happened again I couldn't see any debug info.

I right clicked the app file generated and chose show package contents.

I entered and looked about, there were no log files there.

I went to the folder /Users/USERNAME/Desktop/Hangman.app/Contents/MacOS/ and ran the executable there.

This brought up a terminal window and when the crash occurred the attached image is what was looping at a rapid rate.

Image: http://imgur.com/a/uaFmB

So that's SOMETHING but what do I make of it. It's not really got anything that I feel I can go on. I hope someone can make sense of that stuff :-) as I sure can't!

Anyway, hopefully that extra info can help. Not sure if it's a Godot build bug or my issue but either way I have NO idea how to resolve it.

I have installed the latest 2.1 export templates.

**Link to minimal example project** (optional but very welcome):
http://salonswift.com/tmp/HangMan.zip

**Comment by Zylann** [comment]
Tip: you can drag and drop images and small files to Github comments, they will be hosted here automatically, no need for an external link ;)

Are you loading a file when you play the game at some point?

**Comment by therealrobster** [comment]
Thanks for the tip. I'm loading .txt files that contain the word databases
for the hangman game.  They are all there in the zip file attached.  Am I
doing it incorrectly?

Rob

**Comment by bojidar-bg** [comment]
@therealrobster I'd say, you maybe forgot to add it to the export? By default it would ignore all non-resources, such as your txt file.

**Comment by Zylann** [comment]
Yeah, that must be it. The file could not open.
![hangman_file_error](https://cloud.githubusercontent.com/assets/1311555/19829234/c7f5982a-9ddb-11e6-9037-1b0b9fdeaa7f.png)

**Comment by therealrobster** [comment]
You are a god amung us... and I must confess I'm very new to all of this. 
I really want to thank you.  As soon as I turned on export for all files in project dir it just worked perfectly.  Thank you so much.  Again and again. :-)

**Comment by Zylann** [comment]
Note that if you do that, I guess Source Files and Unused Files will be included too.

**Comment by bojidar-bg** [comment]
Closing as non-issue then :smile:

**Comment by therealrobster** [comment]
Thanks you lot.  Very appreciative here. There was an issue, but it wasn't Godot.  👍

**Comment by Sslaxx** [comment]
Yeah, got bit by this myself trying something vaguely similar.

**Comment by bojidar-bg** [comment]
Maybe you would like to open an issue on godotengine/godot-docs?

**Comment by Sslaxx** [comment]
http://docs.godotengine.org/en/stable/tutorials/asset_pipeline/exporting_projects.html you mean? Honestly, the only issue I have with this page right now is that the screengrabs are from Godot 1.x.
