### ISSUE TITLE
Audio import of high frequency 48KHz sample resolution 16-bit audio files results in artifacts in sounds.

### ISSUE THREAD

**Issue by freemanfromgodotengine** [godotengine/godot#6964]
**Operating system or device - Godot version:**
Godot 2.1-stable on Xubuntu 14.10 64-bit. Project also tested on Android 4 to 6.

**Issue description** (what happened, and what was expected):
Listen to the both sounds. First one is obviously not converted correctly.

**Steps to reproduce:**
Project explaining audio problems attached - it's problem nr 2
Originaly 16-bit, 48000 Hz sample converted with Import/AudioSample menu settings:
Max Rate ON and Max Rate Hz = 48000 does not sound incorrectly. You can hear strange artefacts/ clicking. Because it's audible in higher frequency sounds, I think it's aliasing. Godot could use better quality sample rate conversion.
![godot_audio_problem_2](https://cloud.githubusercontent.com/assets/11817561/19830970/bcf2f5c0-9dff-11e6-9cf2-56699cf0c933.jpg)

Original samples are attached in the sample project's /Snd folder: E5-44100.wav and E5-48000.wav
Converting E5-48000 should result in sounds with artefacts.

**Link to minimal example project** (optional but very welcome):
[Audio_problems.zip](https://github.com/godotengine/godot/files/560001/Audio_problems.zip)

**Comment by Dillybob92** [comment]
Audio rewrite engine after 3.0 maybe?

**Comment by Noshyaar** [comment]
Is this still an issue in latest master? Audio system has been rewritten for the most part in the meantime.

**Comment by freemanfromgodotengine** [comment]
I know, audio engine is completely new, but it will take me some time before I will be able to test those things again.

**Comment by freemanfromgodotengine** [comment]
In latest master the problem is gone. :)
