### ISSUE TITLE
Characterbody 3d cant interact with Rigidbody 3d

### ISSUE THREAD

**Issue by samangol** [godotengine/godot#69640]
### Godot version

v4.0.beta7.official [0bb1e89fb]

### System information

Linux mint cynnimon, vulkan, intel hd graphics family 4400, core i5 4th

### Issue description

Characterbod3d wont push rigidbody 3d

### Steps to reproduce

like if there is a gun on the ground which is rigid body character cant push it like its static, this is the same for sphere also as provided in the sample project

### Minimal reproduction project

[new bug report characterbod3d-rigidbody3d.zip](https://github.com/godotengine/godot/files/10163839/new.bug.report.characterbod3d-rigidbody3d.zip)

**Comment by Zireael07** [comment]
Are you sure your layers are properly set?

This is likely due to the fact that 4.0 doesn't have infinite inertia that 3.x had

**Comment by timothyqiu** [comment]
Clearing the collision layer of the RigidBody3D node does what you want.

AFAIK, this is intended. Collision layers/masks in `4.0` are not bidirectional. Clearing the collision layer of the RigidBody3D node makes the CharacterBody3D ignore that ball when moving, so it can go "inside" the ball. But for the ball, it can still collide with the player, thus it is moved to resolve the overlapping.

In `3.x` the collision layers/masks are bidirectional. There was no way to make A collide with B, but B does not collide with A. So Godot uses a hack internally to achieve something like this.

**Comment by samangol** [comment]
> Clearing the collision layer of the RigidBody3D node does what you want.
> 
> AFAIK, this is intended. Collision layers/masks in `4.0` are not bidirectional. Clearing the collision layer of the RigidBody3D node makes the CharacterBody3D ignore that ball when moving, so it can go "inside" the ball. But for the ball, it can still collide with the player, thus it is moved to resolve the overlapping.
> 
> In `3.x` the collision layers/masks are bidirectional. There was no way to make A collide with B, but B does not collide with A. So Godot uses a hack internally to achieve something like this.

no
