### ISSUE TITLE
【Not bugs】Can Particles's Textures support region?

### ISSUE THREAD

**Issue by Atem1995** [godotengine/godot#69650]
### Godot version

3.5.1

### System information

win10

### Issue description

【Not bugs】Can Particles's Textures support region?

### Steps to reproduce

【Not bugs】Can Particles's Textures support region?

### Minimal reproduction project

【Not bugs】Can Particles's Textures support region?

**Comment by Zireael07** [comment]
Ask questions on forum or Q&A, not here

**Comment by Atem1995** [comment]
> Ask questions on forum or Q&A, not here

@Zireael07 Oh,sorry. I mean, add a bit of a texture feature to the particles so that they support region selection.

**Comment by Atem1995** [comment]
> The short answer is no.
> 
> The long answer is that Particles support AtlasTexture properly in Godot 4.0, if I recall correctly. Because AtlasTexture is very exceptional, most Nodes require custom implementations to support that type of Texture, specifically.
> 
> Please do not bypass the bug report form to ask a very, very simple question next time. I do not have the "authority" to say it, but I know it would be appreciated a lot.

OK!
