### ISSUE TITLE
Crash related to tilemaps: malloc(): mismatching next->prev_size (unsorted) / corrupted size vs. prev_size in fastbins

### ISSUE THREAD

**Issue by furrykef** [godotengine/godot#69659]
### Godot version

4.0.beta7; 4.0.dev (43e9ca40f)

### System information

Linux Mint 20.3, GeForce RTX 3060; mobile renderer

### Issue description

Sometimes Godot crashes when switching scenes using `get_tree().change_scene_to_file()`. The crash does not happen inside this function call; it gets a little further before crashing. The bug **appears** to be related to TileMap or TileSet, since the game where this issue first appeared for me used TileMaps, and the bug disappeared when I removed the TileMaps from my game.

When the crash occurs, no message is printed to the in-editor console, but this does appear in the terminal window if the game is running from when running the editor from the terminal in Godot 4.0.beta7:

> malloc(): mismatching next->prev_size (unsorted)

When trying in build 43e9ca40f, I got a different message:

> corrupted size vs. prev_size in fastbins

I'm not sure whether using a different build is responsible for the different message, or if it's just crashing in two different places and it's a coincidence that this happened in different builds.

For the test case project, I have two scenes, 1 and 2. Scene 1 uses a tilemap and Scene 2 does not. (This seemed to reproduce the bug more reliably on my system than using two scenes with tilemaps, though the project where I first ran into the bug did use tilemaps in both scenes.) Pressing the 1 key switches to scene 1 (even if it's already loaded), and pressing the 2 key switches to scene 2 (ditto).

### Steps to reproduce

1. Open the project in the editor and run it.
2. Alternate between the 1 and 2 keys rapidly until the engine crashes, **or** rapidly press the 1 key a bunch of times and then press the 2 key.

If the bug does not manifest, stop execution and launch again. It seems to happen pretty reliably for me with this project, though.

### Minimal reproduction project

[scene-switch.zip](https://github.com/godotengine/godot/files/10166495/scene-switch.zip)

**Comment by vmedea** [comment]
This sounds kind of similar to the issue I had. It might be fixed with #69922.

**Comment by furrykef** [comment]
I can't reproduce the crash in the master build anymore, so I assume it has indeed been fixed.

**Comment by naturally-intelligent** [comment]
@qarmin 
How do you get a stack trace like that? I'm having `corrupted size vs. prev_size in fastbins` crashes in Godot 4 stable but don't get any error messages like that.
