### ISSUE TITLE
TSCN not saving CSGBoxes correctly on material change, Godot 4.0 Beta 6 Mono

### ISSUE THREAD

**Issue by hudmarc** [godotengine/godot#69682]
### Godot version

4.0-beta6_mono

### System information

Windows 10

### Issue description

Changing file location of shared Standard Material 3D used by multiple CSGBox3D's under a CSGCombiner3D causes the .tscn to corrupt itself and all the CSGBox3D's to disappear.

### Steps to reproduce

Create a CSGCombiner3D node under a Node3D. Add a few CSGBoxes (with Union and Intersect). Apply a new Standard Material 3D to all the CSGBoxes and save the .tscn. Move the Standard Material to a subfolder in the project, many errors should print out. Close Godot (without saving) and reload the scene. The CSGBoxes will not reload correctly and when looking at the .tscn file you should see they are not listed in its node tree.
![image](https://user-images.githubusercontent.com/44267994/206012669-19c33155-7d13-429e-b80f-0fb30322a9b3.png)

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
I can reproduce the error messages on 4.0.beta7 (Linux):

```
  Cannot open file 'res://new_standard_material.tres'.
  Failed loading resource: res://new_standard_material.tres. Make sure resources have been imported by opening the project in the editor at least once.
  scene/resources/resource_format_text.cpp:178 - res://node_3d.tscn:10 - Parse Error: [ext_resource] referenced non-loaded resource at: res://new_standard_material.tres
  scene/resources/resource_format_text.cpp:178 - res://node_3d.tscn:13 - Parse Error: [ext_resource] referenced non-loaded resource at: res://new_standard_material.tres
  scene/resources/resource_format_text.cpp:178 - res://node_3d.tscn:16 - Parse Error: [ext_resource] referenced non-loaded resource at: res://new_standard_material.tres
  scene/resources/resource_format_text.cpp:178 - res://node_3d.tscn:21 - Parse Error: [ext_resource] referenced non-loaded resource at: res://new_standard_material.tres
```

However, the scene is able to be reloaded successfully after closing and reopening the editor.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/69794, which has more information about the issue at hand.
