### ISSUE TITLE
AnimationPlayer's method track to change oneself with method call mode `IMMEDIATE` is strange

### ISSUE THREAD

**Issue by LakshayaG73** [godotengine/godot#69681]
### Godot version

4.0 dev

### System information

Windows 11

### Issue description

AnimationPlayer is ignoring function call tracks, especially when they are used to change the animation. 

The behavior is inconsistent, with certain keys and their functions being called. Keys at the end of the animation are usually not being called, or called sometimes. 

I did a git bisect and the offending commit is this:
https://github.com/godotengine/godot/commit/1fc38336171b775c9cd9a6a33277829fd920d7a2?diff=split

I have uploaded an MRP that at least highlights one such scenario. 

### Steps to reproduce

1. Play the player scene.
2. You should see "reached middle" and "reached end"
3. You only see "reached middle"
4. Try pulling the key back in the "jump_post" animation, you will see "reached end" at certain values

### Minimal reproduction project

[Energy_MRP.zip](https://github.com/godotengine/godot/files/10170080/Energy_MRP.zip)

**Comment by lufog** [comment]
I see the following:
```
["library/jump_end", "library/jump_post", "library/jump_pre"]
reached middle
reached end
Project FPS: 60 (16.66 mspf)
Project FPS: 60 (16.66 mspf)
Project FPS: 60 (16.66 mspf)
Project FPS: 60 (16.66 mspf)
```

I didn't make any changes, just downloaded and ran on:
v4.0.beta7.official [0bb1e89fb] and v4.0.beta.custom_build [deb760fb1]

**Comment by TokageItLab** [comment]
I think that when the method call mode is `Immediate`, the method track updates AnimationPlayer itself, causing a conflict with its own updates. I will investigate whether this can be resolved, but for now setting the method call mode to `Deferred` might work.

**Comment by adamscott** [comment]
@LakshayaG73 Thank you for have taken the time to create a MRP! :raised_hands:
