### ISSUE TITLE
Cannot modify Scattering value when Place Random Tile is deselected

### ISSUE THREAD

**Issue by TomSpalango** [godotengine/godot#69697]
### Godot version

4.0.beta7.official [0bb1e89fb]

### System information

Windows 11 Home, Version 21H2, OS build 22000.1219

### Issue description

Within the TileMap window you cannot change the Scattering value if "Place Random Tile" is not selected, but you can still select the field and highlight it, hinting that it can be changed.

Is this expected behavior?

![Scattering](https://user-images.githubusercontent.com/4755780/206081520-e7fc5794-2c8b-4d15-9653-5c693bf79d46.png)

### Steps to reproduce

Create TileMap Node
Assign a TileSet
Ensure "TileMap" is selected at the bottom within the TileMap editor window
Attempt to change Scattering value by clicking arrows or selecting field and entering a number. **[DOES NOT WORK]**

Enable "Place Random Tile" to the left of Scattering
Attempt to change Scattering value.  **[WORKS]**

### Minimal reproduction project

N/A

**Comment by TomSpalango** [comment]
MRP attached, if needed.
[Scattering.zip](https://github.com/godotengine/godot/files/10172690/Scattering.zip)

**Comment by TomSpalango** [comment]
MRP attached, if needed.
[Scattering.zip](https://github.com/godotengine/godot/files/10172731/Scattering.zip)

**Comment by KoBeWi** [comment]
The scattering becomes disabled when random is disabled. You can click and select it, but not edit it. I think the confusion comes from the focus style, which makes the SpinBox look like it can be interacted with. I think we could just hide the scattering instead of disabling.
