### ISSUE TITLE
Navigation of contour array generated with "opencv" is not normal in godot generation

### ISSUE THREAD

**Issue by xiaoliang6669** [godotengine/godot#69705]
### Godot version

4.0-beta7

### System information

win10

### Issue description

![77777](https://user-images.githubusercontent.com/112788136/206108497-c78ae4c2-983d-4007-8e43-ff52f0586349.png)

### Steps to reproduce

The 11,200 * 5760 image generates a contour shape array. The navigation of the godot generation is too slow. I can only split it into two parts, but many shapes are not cut.

In fact, the structure is very clear. There is a big outline outside and many small outlines inside

I occasionally adjust the size of the contour. Sometimes it is normal, but in most cases, many shapes cannot be cut

### Minimal reproduction project

![8888](https://user-images.githubusercontent.com/112788136/206109527-8d5cb774-deb5-4f41-a6c0-709dfd2e3912.png)

**Comment by akien-mga** [comment]
It's pretty evident why such a badly optimized shape would be demanding for navigation. You need to simplify it.

Without a minimal reproduction project we can't profile anything to see if some improvements could be made to the algorithm to increase performance. But even then it won't change that the input data is bad.

**Comment by xiaoliang6669** [comment]
It's just that the map is big enough. You can see that the points are not optimized, but they have been optimized. Moreover, the coordinates of the "opencv" basic contour command are very clear and neat

**Comment by xiaoliang6669** [comment]
![4OWGE1DCJA $Z9$JHNIRZ`C](https://user-images.githubusercontent.com/112788136/206193312-d9be74aa-1664-4cee-a2d2-ad413048673d.png)

**Comment by akien-mga** [comment]
"Optimized" means using simple shapes such as rectangles and ellipses.

Unless you're doing a sand simulation game, you don't need to be able to go in all the tiniest details of the relief.

Also, you don't need to process the whole game pad at once. Or if you do, you need to come up with clever optimizations on your own, this is not what the navigation API is designed for.

**Comment by xiaoliang6669** [comment]
Why is it that this emphasis is always so strong that it is not appropriate to move around? What is the engine suitable for? It is only suitable for platform jumping games?

**Comment by Zireael07** [comment]
Looking at the pictures, I am thinking your units should only be able to move on the roads themselves, not in "courtyards" of buildings. That's a major optimization here, reducing your problem to just some rectangles.

**Comment by smix8** [comment]
If only a single polygon hole in the bool operation order is winded in the wrong order all following polygons will fail their bool operations. Also the Clipper lib that does the bool operations for polygons converts all polygon vertex to integers and upscales them for the operation to avoid precision issues and the result gets downscaled again before returned to user. Such a very large polygon map might simply run into the limit. Even if the operation would succeed such a detailed polygon map is basically completely useless for pathfinding performance.

**Comment by xiaoliang6669** [comment]
![A4A QTI3U%)_X P $4$82VN](https://user-images.githubusercontent.com/112788136/206335082-f460593f-d781-4590-8208-d8589c958456.png)
