### ISSUE TITLE
mouse_entered/mouse_exited not emitting when camera moves

### ISSUE THREAD

**Issue by OgGhostJelly** [godotengine/godot#69708]
### Godot version

v4.0.beta7.official [0bb1e89fb]

### System information

Linux T430 Thinkpad, Mobile renderer, Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz

### Issue description

the mouse_entered and mouse_exited signals only update when the mouse has moved, which means if the players camera moves looking away from an object. godot does not detect that the mouse has exited the object.

### Steps to reproduce

1. create a area3d with a collider
2. connect the mouse_entered and mouse_exited to a script to print the results
4. without moving your mouse move your in-game camera around
5. the mouse_entered and mouse_exited signal do not emit even though your mouse is exiting and or entering the area3d

### Minimal reproduction project

hover your mouse over the square
and see that "mouse_entered" is printed into the console

move your camera away from the square with 'a' or 'd' without moving your mouse
and see that "mouse_exited" is not printed until you move your mouse again
[mouseenterbugfix.zip](https://github.com/godotengine/godot/files/10173908/mouseenterbugfix.zip)

example video to better show what I mean

https://user-images.githubusercontent.com/94768729/206123583-ac7b89f7-4001-4944-bdbb-4cdb2cd6b717.mp4

**Comment by Chaosus** [comment]
I think it's intended behaviour (but may be undocumented), you can fix it by calling the following code in your camera class (if its position or rotation have changed):

```
	var mouse_event = InputEventMouseMotion.new()
	mouse_event.position = get_viewport().get_mouse_position()
	Input.parse_input_event(mouse_event)
```

**Comment by Calinou** [comment]
Does this behavior occur with Camera2D as well?

**Comment by OgGhostJelly** [comment]
> 

yes, it does.

**Comment by Sauermann** [comment]
The Camera2D-variant of this bug is reported in #75711
