### ISSUE TITLE
PNGs glitched after importing from Blender

### ISSUE THREAD

**Issue by inabird** [godotengine/godot#69710]
### Godot version

v3.4.5.stable.fedora [f9ac000d5]

### System information

Fedora Linux 37 (Workstation Edition)

### Issue description

I have animated a picture in Blender using armature and PNGs.
The PNGs are imported to Blender as mesh.

After exporting as dae or gib to Godot, the PNGs all got glitched backgrounds.
The bones are of different rotation as well.

In Blender:
![Screenshot from 2022-12-07 17-06-39](https://user-images.githubusercontent.com/117072051/206136050-ecc623ec-7c5f-4a66-b72c-7740978e1965.png)

After importing to Godot:
![Screenshot from 2022-12-07 16-57-32](https://user-images.githubusercontent.com/117072051/206135499-d353600f-a26f-47f7-9779-476e5445a2e2.png)

The PNGs on their own:
![Screenshot from 2022-12-07 17-06-14](https://user-images.githubusercontent.com/117072051/206136083-4e8edee9-3e74-4ac1-9bfd-f1ef581713fc.png)

Another strange thing is that one more armature is created automatically in Godot while I only have one in the Blender file.
![Screenshot from 2022-12-07 17-16-43](https://user-images.githubusercontent.com/117072051/206138596-23a6ecba-1bee-4d0d-a0bb-162b6197fcbd.png)  ![Screenshot from 2022-12-07 17-18-26](https://user-images.githubusercontent.com/117072051/206138622-f333c1ff-5cec-46ee-8c72-31c2c9436ed2.png)

It didn't happen in the last 10 animation I've done and I have been exporting the PNGs in the same manner.
Is this a bug or did I do something wrong?

### Steps to reproduce

1. Create a new Godot project
2. Move all PNGs and dae/gib to the Godot folder
3. Double click the dae/gib (New inherited)

### Minimal reproduction project

N/A

**Comment by fire** [comment]
@julienduroure Do you think this is a Godot Engine import or a Blender export issue?

**Comment by julienduroure** [comment]
Hello,
Can you please share a simple .blend file to be able to reproduce the issue?

**Comment by inabird** [comment]
Yes. Here it is

[tree_blender.zip](https://github.com/godotengine/godot/files/10183677/tree_blender.zip)

**Comment by julienduroure** [comment]
Can't see any problem using an online glb viewer (three.js or babyloon.js), so I may think problem comes from Godot 

![image](https://user-images.githubusercontent.com/1696020/206850832-0e0d15a6-79a6-44ab-9fa3-8120ba6d6991.png)

**Comment by fire** [comment]
The project appears to import as expected.

https://user-images.githubusercontent.com/32321/220498013-d12acb87-9878-4853-ad6a-48156b5630f5.mp4
