### ISSUE TITLE
`CanvasLayer.layer` draws higher value first, but description describes the other way around.

### ISSUE THREAD

**Issue by SysError99** [godotengine/godot#69716]
### Godot version

all

### System information

Linux 5.19.17-2-MANJARO

### Issue description

Behaviour of `CanvasLayer.layer` will draw layer that has higher value first, then lower value last, which means`-128` will be the minimum value and gets drawn last. But its description, on both editor and docs, describes the other way around. 
![image](https://user-images.githubusercontent.com/17522480/206166120-fa888b2e-8e06-4ece-b174-cf59fe4b7448.png)
If lower value gets drawn first, that means `-128` will be drawn first. I got baffled for awhile of why my loading layer gets covered by background despite had tried to make it as lowest value as possible, but later I had looked up the docs and finally found the culprit.
![image](https://user-images.githubusercontent.com/17522480/206167307-33fce52e-91e4-47f5-bbb3-dafd9f64288d.png)

### Steps to reproduce

1) Lookup on description of `CanvasLayer.layer` on the editor.
2) Making a mistake following its description.
3) Getting baffled of what's going on

### Minimal reproduction project

-

**Comment by timothyqiu** [comment]
You may have gotten the meaning the other way around. By "drawn first", it means the layer will be covered by layers drawn later.

Like regular painting process, if you draw a red rect on a paper _first_ and then draw a black circle on it, the black circle covers the red rect.

**Comment by KoBeWi** [comment]
The description seems misleading.

**Comment by hackenshaw** [comment]
Can I pick this one up? I would change the text to "drawn behind" instead of "drawn first" in `CanvasLayer.xml` and all untranslated po files.

**Comment by KoBeWi** [comment]
Sure, but the change should be done only in the xml file.

**Comment by hackenshaw** [comment]
Are the other ones generated?

**Comment by SysError99** [comment]
Please consider cherry-pick this to 3.x.

Thank you!
