### ISSUE TITLE
Sliders scale weirdly in the current theme

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#6972]
**Operating system or device - Godot version:**
Mageia 6 x86_64, Godot 33766a4

**Issue description** (what happened, and what was expected):
![spectacle egz949](https://cloud.githubusercontent.com/assets/4701338/19835938/2cc4eece-9e93-11e6-84a5-c70e349e5720.png)

**Steps to reproduce:**
- Insert HSlider or VSlider in a scene and scale it

Both the bar and the pin could use some rework btw, especially the VSlider bar with its bulging belly :)

**Comment by reduz** [comment]
current theme no longer exists, so closing

**Comment by akien-mga** [comment]
It still exists for games (the new theme is only for the editor), so it needs checked.

**Comment by djrm** [comment]
@akien-mga im pretty sure i fixed this, #9688

**Comment by akien-mga** [comment]
Nice, closing then.
