### ISSUE TITLE
Travis: Those ever timing-out Android builds

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#6973]
Android builds on Travis are often timing out for no good reason - mainly it seems like the download of the SDK/NDK takes too long and Travis kills the build.

@bojidar-bg tried a workaround in #6738 but it did not work out.

We need to find a fix, or disable the android target, as it's getting tiring that half the PRs are shown as not passing CI because of a timeout on a single job (and I've checked, there's no option in GitHub to not show erroring jobs as broken, contrarily to Travis itself which makes a distinction between errors (!) and failures (x)).

We could also try moving the android builds to the container-based Linux infra instead of the more limited OSX nodes - then the main question is whether we can get the SDK and NDK easily.

**Comment by est31** [comment]
Some links which might be useful

https://github.com/travis-ci/travis-cookbooks/pull/393
https://github.com/travis-ci/travis-cookbooks/tree/master/community-cookbooks/android-sdk
https://docs.travis-ci.com/user/languages/android (only SDK atm, no NDK support yet)

**Comment by akien-mga** [comment]
Fixed by 7f3ecd42.
