### ISSUE TITLE
`TileSet` default tile shape creates broken navigation polygons for isometric tiles

### ISSUE THREAD

**Issue by zinefer** [godotengine/godot#69745]
### Godot version

v4.0.beta7.mono.official

### System information

Windows 10

### Issue description

The autogenerated navigation polygon has two extra points for isometric TileSets that throws an exception and prevents navigation.

[Related Issue #66283](https://github.com/godotengine/godot/issues/66283)

### Steps to reproduce

In the included project there is a main scene with a TileMap with a TileSet that has not yet had any navigation polygons painted on the walkable tile.

- Navigate to the walkable tile in the TileSet
- Activate Paint properties
- Clear the input
- Reset the input to the default tile shape
- Select the walkable tile to apply the properties
- Run the game

The result is no navigation and a repeated error:
```
_physics_process: Condition "least_cost_id == -1" is true. Breaking.
  <C++ Source>   modules/navigation/nav_map.cpp:261 @ get_path()
  <Stack Trace>  CharacterBody2D.gd:11 @ _physics_process()
```

To get the game running, edit the navigation polygon and remove the bonus points on the east and west sides of the polygon.

![image](https://user-images.githubusercontent.com/466002/206335675-6fafe8f9-c9b8-4694-a6c8-e6dbd0de7609.png)

### Minimal reproduction project

[godot-iso-nav-bug.zip](https://github.com/godotengine/godot/files/10181437/godot-iso-nav-bug.zip)

**Comment by smix8** [comment]
The "Reset to default tile shape" Button calls the shared `TileSet::get_tile_shape_polygon()` function to create the new polygon.

For the basic `SQUARE` shaped tiles this function creates an outline polygon with 4 vertices, something that also works for a NavigationPolygon as an outline, later converted to a NavigationMesh when the TileSet calls `make_polygons_from_outlines()`.

For any other shape `ISOMETRIC / HEXAGON / HALF_OFFSET_SQUARE` the TileSet creates a triangulated polygon.

A triangulated polygon can work for visuals or physics but not as an outline of a NavigationPolygon cause outlines can not overlap or intersect. It is not just that there are duplicated vertices, if there are only 4 vertices and you move one vertex into a position that creates intersections the Editor will already spam the well known "NavigationPolygon: Convex partition failed!" error msg when the TileSet tries to save this invalid NavigationPolygon resource.
