### ISSUE TITLE
Tracker Added / Removed / Updated signals not firing 

### ISSUE THREAD

**Issue by Kimau** [godotengine/godot#69756]
### Godot version

4.0.beta7

### System information

Windows, SteamVR / Index / Vive Pucks 2.0

### Issue description

The tracking and pose valid states work if the tracker is connected and registered by SteamVR at application boot.

Though if you turn on any tracking pucks post launch they don't seem to be detected and the XRController3d get_is_active() && get_has_tracking_data() never change.

Looking into binding to XRServer tracker_x signals and they don't seem to emit either.

Which means all tracking devices need to be turned on and registed by steam before boot which is rare for body trackers

### Steps to reproduce

Steps
1. Turn off tracking puck
2. Boot application
3. Turn on tracking puck

Connect some debug functions to
	XRServer.connect("tracker_added", trackerAdded)
	XRServer.connect("tracker_removed", trackerRemoved)
	XRServer.connect("tracker_updated", trackerUpdate)

Also have an update script on XRController3D checking
	var isValid : bool = get_is_active() && get_has_tracking_data()
	self.visible = isValid

### Minimal reproduction project

[VRLab.zip](https://github.com/godotengine/godot/files/10184600/VRLab.zip)

**Comment by akien-mga** [comment]
Can you still reproduce this in 4.0.3 and 4.1-beta3 or later?

**Comment by KoBeWi** [comment]
Closing due to no response.
Comment if you can still reproduce in the newest version of Godot.
