### ISSUE TITLE
Spotlight with shadow not working on GLES 2 when shadows filter mode is disabled

### ISSUE THREAD

**Issue by norrath-hero-cn** [godotengine/godot#69759]
### Godot version

Godot Engine v3.5.1.stable.official.6fed1ffa3

### System information

Windows 10 x64, OpenGL ES 2.0 Renderer: NVIDIA GeForce GTX 960/PCIe/SSE2

### Issue description

Spotlight with shadow not working on GLES 2 when shadows filter mode is disabled, related to https://github.com/godotengine/godot/issues/54343

shadows filter mode disabled
![image](https://user-images.githubusercontent.com/73905273/206441156-a845a7d1-c0c8-4082-8388-1eee72838575.png)

shadows filter mode set to pcf5
![image](https://user-images.githubusercontent.com/73905273/206441240-22634116-071a-44ba-8b52-b46d88fb3531.png)

shadows filter mode set to pcf13
![image](https://user-images.githubusercontent.com/73905273/206441338-64cff598-1603-48fb-8d4d-77cd4c32bd85.png)

### Steps to reproduce

please use the minimal reproduce project

### Minimal reproduction project

[shadow.zip](https://github.com/godotengine/godot/files/10185090/shadow.zip)

**Comment by akien-mga** [comment]
Fixed by #69826.
