### ISSUE TITLE
Scene name can be saved as extension only: ".tscn"

### ISSUE THREAD

**Issue by duianto** [godotengine/godot#69768]
### Godot version

v4.0.beta7.official [0bb1e89fb] and v3.5.1.stable.official [6fed1ffa3]

### System information

Windows 10 22H2, OpenGL3, Geforce GTX 550 Ti

### Issue description

A scene can be saved without a pre file extension name, leaving only ".tscn".

### Steps to reproduce

- create a new project
- add a `2D scene`
- save the scene `ctrl s`
the `Save Scene As...` window opens, with the pre file extension name selected: `[node_2d].tscn`
- erase the selected text before the dot and extension: `backspace`
leaving the name as: `.tscn`
- accept the scene name: `enter`

### Expected
If it's by design, then this can be closed.

If the name should have at least one character, then a message should appear, stating the requirement.

### v4.0.beta7.official [0bb1e89fb]
Started with: `Godot_v4.0-beta7_win64.exe --rendering-driver opengl3`

![Godot_v4 0-beta7_win64_mpt1qa7lLg](https://user-images.githubusercontent.com/13420573/206493911-db53d845-a8f4-4340-9e90-400da1d32642.png)

![Godot_v4 0-beta7_win64_ctlNHmvkDZ](https://user-images.githubusercontent.com/13420573/206493957-b327048f-2f72-4d9d-8de2-15f3e16d50ce.png)

### v3.5.1.stable.official [6fed1ffa3]

![Godot_v3 5 1-stable_win64_KE6md9ivd4](https://user-images.githubusercontent.com/13420573/206493991-7045230a-8ae7-4f26-ae86-0780d4a1fc18.png)

![Godot_v3 5 1-stable_win64_GWZuCcZEuS](https://user-images.githubusercontent.com/13420573/206495216-842649d1-5b14-4d5b-a51a-209d30b1f0a7.png)

### Minimal reproduction project

[issue, scene name, extension only, v4.0.beta7.zip](https://github.com/godotengine/godot/files/10187508/issue.scene.name.extension.only.v4.0.beta7.zip)

[issue, scene name, extension only, v3.5.1.stable.zip](https://github.com/godotengine/godot/files/10187507/issue.scene.name.extension.only.v3.5.1.stable.zip)

**Comment by KoBeWi** [comment]
The scene saves and loads correctly, so I think it's not really a problem. Although there is inconsistency with New Scene dialog.
![image](https://user-images.githubusercontent.com/2223172/206513135-95c79a06-4001-46ff-a9af-35b2a5bc0640.png)
