### ISSUE TITLE
Expose built-in types default constructors

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#6977]
- Vector2
- Vector3
- Matrix32
- Matrix3
- Quaternion
- Color
- Transform
- ...

Primitive math types often have multiple constructors, but the default one is not listed. Also, some people read the docs first before writing code (especially with a scripting API), it can be misleading to hint there is no default constructor, leading them to not even try.

These constructors exist, they can be used. But if they are not found by doctool... then we have another problem, because not a single default constructor is ever documented, not just math primitives. Which leads me to think they are bound automatically, and unavailable to doctool.

Original request: https://github.com/godotengine/godot/pull/6752#issuecomment-257141732

**Comment by bojidar-bg** [comment]
[`core/variant_call.cpp:1743`](https://github.com/godotengine/godot/blob/master/core/variant_call.cpp#L1743) is responsible for registering most of them.

**Comment by vnen** [comment]
@bojidar-bg it doesn't seem to register default constructors. Considering the comment in [`get_constuctor_list`](https://github.com/godotengine/godot/blob/master/core/variant_call.cpp#L1285), they might be implied to exist. The change may need to be done in the doctool side.

**Comment by reduz** [comment]
kicking to 3.1 unless someone adds it

**Comment by Zylann** [comment]
Found another confused post, PoolVectors default constructors aren't listed either https://godotengine.org/qa/17117/how-to-construct-a-poolbytearray?show=17118#a17118

**Comment by akien-mga** [comment]
@vnen @bojidar-bg Any idea on how to do this for 4.0? Worst case we could register them manually I guess.
