### ISSUE TITLE
Editor documentation appears left-aligned when first opened

### ISSUE THREAD

**Issue by Lippanon** [godotengine/godot#69773]
### Godot version

v4.0.beta.custom_build [204715ae9]

### System information

Windows 10

### Issue description

When opening the in-editor documentation for seemingly any resource/object/page, it will be shown left-aligned as shown in pic, until the code editor is resized.

First shown:
![image](https://user-images.githubusercontent.com/115422160/206539109-c3ac1857-2463-4e24-a6f2-d5700818d0fa.png)

Upon resizing it's fixed:
![image](https://user-images.githubusercontent.com/115422160/206539231-d7ece89b-c1b2-4c65-b046-af0ffc3ccc68.png)

If after resizing the page is closed, it will be left-aligned again when re-opened.

### Steps to reproduce

Open any page (I think) in the editor docs, if this doesn't happen to everyone, let me know what I should add for more info, might be some setting I have toggled.

### Minimal reproduction project

Leaving the one I used for the pics here but for me it happens in any project.
[SpringArm3D clipping.zip](https://github.com/godotengine/godot/files/10188446/SpringArm3D.clipping.zip)

**Comment by Calinou** [comment]
I can confirm this on 4.0.beta 55dae3017 (Linux, 100% editor scale).

@Lippanon Can you reproduce this in any of the earlier [4.0 betas](https://downloads.tuxfamily.org/godotengine/3.5/) to determine when the regression started?

**Comment by Lippanon** [comment]
> @Lippanon Can you reproduce this in any of the earlier [4.0 betas](https://downloads.tuxfamily.org/godotengine/4.0/) to determine when the regression started?

Official builds, win64:

It's present in: beta6, beta5
NOT present in: beta2, beta3, beta4

So it was something between beta 4 and 5. Sorry, I don't have time to bisect it by builing from source.

**Comment by nongvantinh** [comment]
I'll bisect it.

**Comment by 16amattice** [comment]
@nongvantinh I already did.

**Comment by 16amattice** [comment]
@Calinou After bisecting, looks like this issue arrised in PR [#68132](https://github.com/godotengine/godot/pull/68132)
I don't have enough time to test around for a fix at this exact moment, but I believe it is coming from one of the first four theme overrides that were added. If more testing isn't done by tomorrow afternoon, I'll do some tests and throw out a fix.

**Comment by akien-mga** [comment]
CC @Mickeon @bruvzg

**Comment by Mickeon** [comment]
Thank you for mentioning me. I still have no clue myself as to why this would be the case. I could investigate it now since my PR is known to be the cause, but for now I can only speculate that this is the culprit behind it, since it was required to have the background of the EditorHelp RichTextLabel be darker:
https://github.com/godotengine/godot/blob/45cac42c0b511672240c1fcccecfd3cc0580edcb/editor/editor_themes.cpp#L1546-L1549

**Comment by 16amattice** [comment]
> Thank you for mentioning me. I still have no clue myself as to why this would be the case. I could investigate it now since my PR is known to be the cause, but for now I can only speculate that this is the culprit behind it, since it was somewhat required to have the background of the EditorHelp RichTextLabel be ever so slightly darker.
> 
> https://github.com/godotengine/godot/blob/45cac42c0b511672240c1fcccecfd3cc0580edcb/editor/editor_themes.cpp#L1546-L1549

Probably wasn't the best way to go about it, but removing those four lines don't affect the outcome.

**Comment by 16amattice** [comment]
Sorry that I keep breaking these up, I'm just posted as I go. This override seems to interfere with the forced theme update inside of _class_desc_resized

https://github.com/godotengine/godot/blob/45cac42c0b511672240c1fcccecfd3cc0580edcb/editor/editor_help.cpp#L189-L204
