### ISSUE TITLE
'xform_inv' present in code but missing from GDScript and Docs

### ISSUE THREAD

**Issue by redthing1** [godotengine/godot#69777]
### Godot version

4.0-beta7

### System information

Arch Linux

### Issue description

Godot 3 has `xform_inv` in 3D transform: https://docs.godotengine.org/en/stable/classes/class_transform.html

Godot 4 has it in the source code: https://github.com/godotengine/godot/blob/e413d1c9c35bec80f7244772bd63a3269f56c5a2/core/math/transform_3d.h#L89-L92

However it is not available to GDScript.

But is missing in docs:
https://docs.godotengine.org/en/latest/classes/class_transform3d.html
https://godotengine.org/qa/114844/godot-4-equivelent-to-basis-xform_inv

### Steps to reproduce

Try calling `Transform3D::xform_inv`

### Minimal reproduction project

N/A

**Comment by raulsntos** [comment]
It's exposed as the `*` operator:

https://github.com/godotengine/godot/blob/f692b476869c14023b342c12efc21cb5cd6002b7/core/variant/variant_op.cpp#L338-L345

I think `ProjectConverter3To4` has a conversion that handles this case.

```gdscript
# 3.x
my_transform.xform(Vector3(1, 2, 3))
my_transform.xform_inv(Vector3(1, 2, 3))

# 4.0
my_transform * Vector3(1, 2, 3)
Vector3(1, 2, 3) * my_transform
```

**Comment by redthing1** [comment]
Thanks
