### ISSUE TITLE
Midi note off event interpreted as `MIDI_MESSAGE_NOTE_ON`

### ISSUE THREAD

**Issue by atirut-w** [godotengine/godot#69770]
### Godot version

v4.0.beta7.official [0bb1e89fb]

### System information

Arch Linux

### Issue description

As described in the title, both note on and off events are interpreted as `MIDI_MESSAGE_NOTE_ON`. The only difference is that the velocity is 0 when you are lifting a key.

### Steps to reproduce

I am not sure if this is an isolated case, but this happens with my Yamaha PSR-E373.

```gdscript
# Do `OS.open_midi_inputs()` first to initialize MIDI
func _input(event: InputEvent) -> void:
	if event is InputEventMIDI:
		if event.message == MIDI_MESSAGE_NOTE_ON:
			breakpoint
		elif event.message == MIDI_MESSAGE_NOTE_OFF:
			breakpoint # Not triggered
```

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
See https://github.com/godotengine/godot/pull/66003 - cc @voidshine.

Your device is likely actually sending note on with velocity 0.

**Comment by atirut-w** [comment]
> Your device is likely actually sending note on with velocity 0. It usually means note off, but now you have to handle this convention yourself.

I guess this can be closed as a non-issue then.
