### ISSUE TITLE
Cannot create Callable object by constructor in GDScript

### ISSUE THREAD

**Issue by layton7362** [godotengine/godot#69782]
### Godot version

v4.0.beta7.official

### System information

Windows 11

### Issue description

I cannot create a Callable object in GDscript

![grafik](https://user-images.githubusercontent.com/43618510/206585513-1030e0e8-d2ef-4aee-8860-0b5620a4212a.png)

### Steps to reproduce

Scene Setup:
![grafik](https://user-images.githubusercontent.com/43618510/206584966-2416b8e7-ee0a-46f8-ab3c-c5c73f9be170.png)

Just attach the script to the Node

### Minimal reproduction project

[minimal_project.zip](https://github.com/godotengine/godot/files/10190467/minimal_project.zip)

**Comment by KoBeWi** [comment]
But the project runs without any problem and you can even call the Callable. So what's the issue?

**Comment by layton7362** [comment]
oh you are right. It's possible to create a Callable. My mistake. I misinterpret the problem. I was confused, because the text is "null:null".

**Comment by KoBeWi** [comment]
Ah I noticed the tooltip now. The debugger is not always reliable when displaying variable contents and this particular case might be releated to #55414
