### ISSUE TITLE
UI text size does not match theme 

### ISSUE THREAD

**Issue by Barugon** [godotengine/godot#69781]
### Godot version

v4.0.beta7.official [0bb1e89fb]

### System information

Fedora 37, AMD Radeon RX 6700 XT, Vulkan

### Issue description

UI text size doesn't match the theme text size.

### Steps to reproduce

- Create a new project
- Crete "User Interface" root node
- Create a new theme for the root node (default theme)
- Add a button with the text "Button"
- Select the root node and click on the theme in order to show a preview

The button text in the preview is smaller than the button text in the project.

Screenshot:
![Screenshot from 2022-12-08 14-30-09](https://user-images.githubusercontent.com/16503728/206580931-4dcc4196-a673-47a2-9456-fca510bef169.png)

### Minimal reproduction project

[New Game Project.zip](https://github.com/godotengine/godot/files/10190250/New.Game.Project.zip)

**Comment by Calinou** [comment]
This is because the editor preview uses the default editor font, not the default project font.

**Comment by Barugon** [comment]
> This is because the editor preview uses the default editor font, not the default project font which is slightly larger (16 instead of 14).

Is this intended?

**Comment by Calinou** [comment]
> Is this intended?

No, I'm just making the observation here to note that it's not just the font size that is incorrect. The reference to the default project font isn't used at all by the editor.

**Comment by Ayush-singla27** [comment]
I would like to work on this issue but i guess changing default editor font size or changing default project font size doesn't seems to be good idea. right?

**Comment by Barugon** [comment]
I personally would like the default font to be the same as the editor font.

**Comment by Calinou** [comment]
> It looks slightly bolder in the project.

The default project font is expected to look bolder, as it uses OpenSans SemiBold while the editor uses Noto Sans regular.

**Comment by Ayush-singla27** [comment]
I don't think heavy font will look good in the editor. Also, its better to use heavy font in game cause it is more visible, as mention [here](https://github.com/godotengine/godot/pull/39603#issuecomment-778370520).

**Comment by Calinou** [comment]
Either way, this is not the issue. The default font size is also not respected (it's 16 in the project, 14 in the editor).

**Comment by Barugon** [comment]
The biggest is that the theme preview doesn't match what I get in my project (font weight and size).

**Comment by Ayush-singla27** [comment]
i dug a bit deeper into this issue and have changed the default project font size to 14 and it matches with the editor font size.
As for the font should i make the default theme font to be the same as the project font?

**Comment by Calinou** [comment]
@Ayush-singla27 This is not how the issue should be removed. The default font size and weight should not be modified.

**Comment by Ayush-singla27** [comment]
@Calinou  actually i changed the default theme's default font size. which is defined [here](https://github.com/godotengine/godot/blob/master/scene/resources/default_theme/default_theme.cpp) ( line 46). Sorry about that previous comment. i hope this is correct.

**Comment by Calinou** [comment]
> i hope this is correct.

No, the default project font size should be left at 16. It's larger than the editor default font size because games generally use larger text compared to the editor.

**Comment by Ayush-singla27** [comment]
umm i am a bit confused right now. Isn't this issue saying that both actual UI and the preview should have same font size? but according to you the preview should be smaller than the project UI in order to fully utilize the screen space. right?

> > actually i changed the default theme's default font size. which is defined [here](https://github.com/godotengine/godot/blob/master/scene/resources/default_theme/default_theme.cpp?rgh-link-date=2022-12-16T21%3A35%3A45Z) ( line 46). Sorry about that previous comment. i hope this is correct.
> 
> No, the default project font size should be left at 16. It's larger than the editor default font size because games generally use larger text compared to the editor (which is a non-game application, and needs to make the best possible use of the available screen real estate).

**Comment by Barugon** [comment]
My project should match the preview. That's the issue. It doesn't necessarily need to be the same as the editor.

**Comment by Ayush-singla27** [comment]
ah , so i should change the font size of the theme preview to be 16? Also, the font of the preview is the same as the rest of the editor so i will have to create certain new variables in order to change the preview font to OpenSans SemiBold and assign it to default theme font. Right?

**Comment by Ayush-singla27** [comment]
Correct me if i am wrong. Theme preview takes it's font from default editor font and every component that could be could be shown in theme preview ( example - buttons, checkbox , lables etc) have its own `get_theme_font` (which return default editor font), so i have to manually change this function with another one which set the font to our desired output in every component file. ryt?
