### ISSUE TITLE
Text input in the "Name" and "Description" fields ... 

### ISSUE THREAD

**Issue by jorgerosa** [godotengine/godot#69792]
### Godot version

Godot 4.0.beta6.official [7f8ecffa5]

### System information

Windows 10

### Issue description

Depending on the input text, in the "_Name_" and "_Description_" fields all works fine  - OR - lags a lot and throws errors.

### Steps to reproduce

1) If I input "_ENCYCLOPEDIA AR - Portugal 1922_"  <-- everything works fine
2) If I input "_ENCYCLOPEDIA AR - Portugal 1922 - © Copyrights Reserved to Jorge Rosa_" <-- it lags a lot and throws erros

### Minimal reproduction project

![Godot_4_001](https://user-images.githubusercontent.com/5511928/206628859-e689ca71-49dc-4a73-8873-eb7702103e93.jpg)

![Godot_4_002](https://user-images.githubusercontent.com/5511928/206628851-c2c8221d-d289-443e-8e67-bf57c5d288a9.jpg)

![Godot_4_003](https://user-images.githubusercontent.com/5511928/206628827-3da138cf-0abc-4516-83aa-4db76d2b8fcf.jpg)

----------------------------------------------------------------------------------------------------------
**BIG THANKYOU to all the GODOT team for your hard work to develop this so brilliant piece of software!**
----------------------------------------------------------------------------------------------------------

.

**Comment by Zireael07** [comment]
At a guess, the copyright symbol might be to blame?

**Comment by Calinou** [comment]
Does this occur when you change *only* the name to contain special characters, or *only* the description?

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
