### ISSUE TITLE
Moving/renaming resources cause unopened/unused tscn/res files to become corrupted

### ISSUE THREAD

**Issue by Rindbee** [godotengine/godot#69794]
### Godot version

f692b4768

### System information

Linux mint 21, forward_plus ,NVIDIA GeForce GTX 1050 Ti

### Issue description

You can open the scene to view, but if you want to reproduce this issue, make sure to close the scene before moving.

The result obtained at step 2.
```node_2d.tscn before
[gd_scene load_steps=2 format=3 uid="uid://cxgwh3ypon3mj"]

[ext_resource type="Texture2D" uid="uid://xdf2u634fcd1" path="res://icon.svg" id="1_l3rl2"]

[node name="Node2D" type="Node2D"]

[node name="Icon" type="Sprite2D" parent="."]
position = Vector2(49, 62)
texture = ExtResource("1_l3rl2")
```
The result obtained at step 5.
```node_2d.tscn after
[gd_scene load_steps=2 format=3]

[ext_resource type="Texture2D" uid="uid://xdf2u634fcd1" path="res://test/icon.svg" id="1_l3rl2"]
```

### Steps to reproduce

1. Open the MRP project in the editor;
2. Use an external editor or the `cat` command to view the text in node_2d.tscn;
3. Make sure node_2d.tscn is not open;
4. Move the icon.svg file to a different folder.
5. Repeat step 2;

### Minimal reproduction project

[MRP.zip](https://github.com/godotengine/godot/files/10191899/MRP.zip)

**Comment by akien-mga** [comment]
Please mention when a bug is a regression, and from which version - this was made obvious by #69953 but wasn't clear from this issue.

**Comment by lawnjelly** [comment]
This will be a regression from #69119 , sorry my bad, I didn't see it linked as it had not been bisected.

As @Rindbee correctly noticed, the code in `ResourceLoaderText::rename_dependencies` is relying on the file pointer being in sync with `VariantParser::StreamFile`, which cannot be relied on any longer, the file position must be retrieved from `VariantParser::StreamFile` directly.

**Comment by akien-mga** [comment]
I can confirm that the bug happens in `3.x` too (#69963 will fix it).

**Comment by lesleyrs** [comment]
Does this fix 
-[sub_resource type="Image" id="Image_och0y"]
+[sub_resource type="Image" id="Image_5rs4i"]

**Comment by lesleyrs** [comment]
Does this fix:
```
-[sub_resource type="Image" id="Image_och0y"]
+[sub_resource type="Image" id="Image_5rs4i"]
```

.tres file changing id every time I press f5 to run game?

**Comment by tinmanjuggernaut** [comment]
@lesleyrs No. See https://github.com/godotengine/godot/issues/62258

**Comment by Rindbee** [comment]
I can confirm that the issue is only partially fixed.

```
A ---> B ---> C
```
For example, the C file is used in the B file, and the B is used in the A file. 
If C is renamed/moved without opening/using A and B, the uid of B will still be lost, which will cause a new uid to be generated when B is opened and saved again, and A will not be updated during this period.
