### ISSUE TITLE
Coding standards: Python files

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#6980]
As a monolithic issue (#3916) does not make it easy to discuss specific points, let's split some topics in their own issue (always referencing the main one) so that we can progress forwards.

---

We have various Python files in the source, mostly related to the buildsystem or some helper scripts.

I'd propose to follow the Python standard for those, PEP 8: https://www.python.org/dev/peps/pep-0008/
The main disruptive change of PEP 8 for us would be that it enforces space indentation (:innocent:), while we currently have a stronger tendency to use tabs (though it's not done consistently and we have a lot of mixed situations).

Since most auto-formatting tools enforce spaces, I'd propose to use that convention too for our Python files (not C++ of course, where we should stick to our _de facto_ tabs standard).

Alternatively, we can decide to use PEP 8 and tabs for indentation, we just need to tweak the PEP 8 checking tools to disable some warnings and errors related to indentation. One advantage of keeping tabs is that we're consistent with the C++ code, so we don't have issues with conflicting IDE configs.

**Comment by neikeq** [comment]
IMHO the convention, which is spaces for PEP8.

**Comment by vnen** [comment]
Since PEP 8 defines indentation with spaces, it's better to use spaces. Users used to Python will likely use spaces when contributing and having a different settings and tooling for Godot should not be necessary.

**Comment by Zylann** [comment]
I prefer to use spaces in general. Some text editors make it a bit tedious (backspace removing one space at a time instead of 1 indent) but that's the only problem I would have with it.

**Comment by akien-mga** [comment]
Let's go with spaces then.

One thing not covered by pep8 (or at least not touched by `autopep8`) is the use of parenthesis around conditionals:
```
if (cond):
    do_stuff()
```
vs
```
if cond:
    do_stuff()
```

Which one do we want to enforce? I think the 2nd one is more idiomatic python, but the former one is currently used more often as the buildsystem was written by C++ guys :)

**Comment by neikeq** [comment]
I prefer the second one (no parenthesis) both in Python and GDScript.

**Comment by Zylann** [comment]
I prefer the second one too, also I don't understand why the first one would be useful?

**Comment by akien-mga** [comment]
> I don't understand why the first one would be useful?

It has no use, but it's what C/C++ programmers are used to use, so they might find it more aesthetic (at least judging by its extensive usage in all our python files :)).

**Comment by timoschwarzer** [comment]
Personally I prefer the first one (with parenthesis) because it clearly separates the if keyword from the whole condition. (Might be that I'm used to C syntax though... :-))

**Comment by Dillybob92** [comment]
First one is useful if multiple conditions and/or in one if statement. I think GDScript lets us use both styles anyways? I use the first one for complex conditions and the no parenthesis one for more simpler ones

**Comment by RandomShaper** [comment]
Now I'm trying to embrace the Python culture I also feel no parentheses is the best.

And although I like tabs for Python and GDScript I think that folliwing a well-defined set of rules like PEP8 is a good thing, so ident with spaces is good for me.

**Comment by akien-mga** [comment]
Alright, so the consensus so far seems to be:
- We follow PEP8, including 4-space indent.
- We use the pythonic `if cond:` instead of the C-style `if (cond):`. Parenthesis can still be used when relevant, especially for multiline line conds.

Two other points that come to mind and not (fully) covered by the above:

**Line wrapping**

PEP8 advises to wrap lines at 79 chars, and 72 chars for docstrings. They allow going over 80 chars and up to 99 chars on lines that make more sense when long than when arbitrarily wrapped, if there is an agreement in the team about it:

> Some teams strongly prefer a longer line length. For code maintained exclusively or primarily by a team that can reach agreement on this issue, it is okay to increase the nominal line length from 80 to 100 characters (effectively increasing the maximum length to 99 characters), provided that comments and docstrings are still wrapped at 72 characters.

I must say that arbitrarily cropping lines at 79 chars often produces weird code, so we need to stay clever and try to ensure that we keep short lines while keeping readability. So I think allowing the "up to 99 chars when relevant" clauses would be good for us, with a strong encouragement to keep below 79 when possible. WDYT?

**Single vs double quotes for string literals**

I don't think there is an official Python recommendation for this, but the use case I've seen so far is to use single quote (`'hello'`) for "functional" strings/tokens/identifiers (e.g. keys to a dict, etc.), while using double quotes (`"Hello world."`) for real "text" strings, like sentences meant to be printed (and maybe paths too?).

I've tried using that in my last PR, thus producing code like:
`opts.Add('tools', "Build the tools a.k.a. the Godot editor (yes/no)", 'yes')`

Feedback welcome on this one, especially if you know of more formal conventions we could follow, which would be better than just following one's gut feeling about the "purpose" of a given string literal.

**Comment by Zylann** [comment]
I usually always write double quotes because I got used to it from C, C++, Java, C# and GDScript. Also because my azerty keyboard requires only one keypress to get one (though qwerty requires shift).

I like the idea of using them for visible text VS functional, although localization would make these transform into single-quoted identifiers anyways, so in the end only non-translated, dev messages would end up like that (but considering the scope of this issue I don't think they will ever be localized :p).

**Comment by hubbyist** [comment]
Python console seems to  prefer single quotes:

	# ~ $ python
	>>> "text"
	'text'
	>>> 'text'
	'text'

Tested on Python 2.7.12 and Python 3.5.2.
This may be considered pythonic way.

**Comment by hubbyist** [comment]
Also can an prettifier tool understand the distinction between "functional" and "printable" text if it will be used for enforcing standards?

**Comment by paper-pauper** [comment]
+1 for PEP8 compliance - it was done for BCE and now the code is much easier to maintain since there is some static checking (`flake8`). I honestly think that with all the debates on coding style on the web, PEP8 is the one thing that everybody can settle on.

Also, I would also go with single quotes.

**Comment by Anutrix** [comment]
What about multi-line comments?
Any plans to support them anytime soon?
Testing groups of logic is harder without them.

**Comment by Calinou** [comment]
Is this considered resolved by #37421?

**Comment by akien-mga** [comment]
Yes. We still have to document this in godot-docs but this should be tracked there.
