### ISSUE TITLE
Textures parented by SubViewport nodes have incorrect visuals

### ISSUE THREAD

**Issue by Giftfox** [godotengine/godot#69812]
### Godot version

4.0.beta7

### System information

Windows 10

### Issue description

When converting my project to Godot 4 beta 7, I realized that some of my textures looked differently from how they did in 3.4.2, and differently from how they're supposed to look.

![image](https://user-images.githubusercontent.com/45781747/206743727-16381aa8-a62e-4f89-9177-22cb535e8f1f.png)

A lot of the rectangular boxes on the screen look like their texture has been...shifted? By a pixel or so? I discovered that this happens when these textures are parented by a SubViewport node. I've set the project settings filter default to "nearest", and did the same for relevant SubViewport nodes, but the effect still happens. In fact, with default filter settings, this is how it looks:

![image](https://user-images.githubusercontent.com/45781747/206744180-3e87c9a5-266c-4795-8918-093b10ed83c1.png)

The texture looks slightly different between the version within the SubViewport and the version without. It seems to have a similar displacement issue. My first thought was that the extra viewport was filtering the texture a second time, and causing such issues regardless of the filter type. This kind of thing is out of my depth, though, so that's all I can offer. Curiously, only some textures in my game are shifted in this way, not all of them. I rely on SubViewport nodes for my scene structure and I would like to continue using them, though for now I can make do.

### Steps to reproduce

Create a SubViewportContainer node, and add a SubViewport node to it. Add a Sprite2D node to the viewport and give it a texture. Add another Sprite2D node outside of the SubViewportContainer and give it the same texture. It will look different from the other one.

### Minimal reproduction project

[new.zip](https://github.com/godotengine/godot/files/10196278/new.zip)

**Comment by BraqueDown** [comment]
Your Sprite2D nodes are using the Centered property, but your texture has an uneven height (23px). This is means the texture doesn't line up with the viewport's pixel grid.

Either change your texture to use even dimensions, or change the Sprite2D's Y offset by 0.5px.

**No Offset**
![image](https://user-images.githubusercontent.com/43602802/206889731-884b043f-a1ea-40f4-b9d4-f0012a253edf.png)

**0.5px Offset on Y-axis**
![image](https://user-images.githubusercontent.com/43602802/206889753-1df5745f-9faf-4d07-85f5-b6023511f187.png)

**Comment by Giftfox** [comment]
Oh! Thank you for that, that was never an issue for me in 3 so I never even considered. I'm very glad it's something I can fix on my end.

**Comment by BraqueDown** [comment]
You might have been using the **Use GPU Pixel Snap** setting in 3.x, which has a different name in 4.x, and it wasn't re-enabled.
