### ISSUE TITLE
TileMap 2D renders error around the y-axis

### ISSUE THREAD

**Issue by clapik** [godotengine/godot#69818]
### Godot version

4.0 beta 7

### System information

Windows 11, Ubuntu

### Issue description

When using 2D TileMap, the edges are rendered incorrectly around the y-axis.
![image](https://user-images.githubusercontent.com/3974885/206764817-619552f2-af78-45b5-b6da-9b9c5f5bf681.png)

### Steps to reproduce

Create a 2D TileMap with according TileSet

Paint the tile.

### Minimal reproduction project

[TileMapBug.zip](https://github.com/godotengine/godot/files/10197057/TileMapBug.zip)

**Comment by groud** [comment]
Duplicate of https://github.com/godotengine/godot/issues/69818. See my answer there.

**Comment by clapik** [comment]
@groud May you re-link the issue? I think #69818 is _this_ issue. Thanks!

**Comment by groud** [comment]
Ah sorry, I edited the link.
