### ISSUE TITLE
Exporting c# Resources broken in Godot 4 Beta 8:  "The type is not supported for conversion to/from Variant"

### ISSUE THREAD

**Issue by dogboydog** [godotengine/godot#69822]
### Godot version

v4.0.beta8.mono.official [45cac42c0]

### System information

Windows 10

### Issue description

I am developing an add-on for Godot version 4.  
In beta 7, I was able to export arrays or single instances of custom Resources that I defined in c#. 
As soon as I updated to beta 8, all instances of exported custom resources started throwing errors, with the message 'The type is not supported for conversion to/from Variant'.  I have to downgrade back to beta 7 for now. 

### Steps to reproduce

Open the project
You will  see the error described above in the Output pane, and you will not be able to add any new resources to the array on  the inspector for SerializedResource.tres

### Minimal reproduction project

[VariantResourceRepro.zip](https://github.com/godotengine/godot/files/10197612/VariantResourceRepro.zip)

**Comment by Calinou** [comment]
This may be a regression from https://github.com/godotengine/godot/pull/69428.

cc @neikeq @raulsntos

**Comment by neikeq** [comment]
Indeed, this is a regression from #69428. The source generators were changed to use the `VariantUtils` generic conversion method, but it looks like I never added support for GodotObject (or derived) arrays to that. I'll work on a fix tomorrow.
