### ISSUE TITLE
Editor crash when adding a new position key in AnimationPlayer

### ISSUE THREAD

**Issue by Levrault** [godotengine/godot#69829]
### Godot version

4.0-beta7 and 4.0-beta8

### System information

Windows 10 with 3070gtx && KDE plasma intel 620

### Issue description

Hi,

When I'm adding a new key to an existing track (picture 1) though the inspector (picture 2) the editor can crash at random interval

![image](https://user-images.githubusercontent.com/1162446/206797835-193709aa-d019-45e5-82b7-fd4a4a1f1c63.png)
![image](https://user-images.githubusercontent.com/1162446/206797773-b903d427-1bae-4e3f-82bf-4850d32ef766.png)

Is there a way to check the editor crash log files? I only saw about the game and the editor itself so I could provide more data.

### Steps to reproduce

1 - Create a new AnimationPlayer
2 - Add a new animation
3 - Move some meshes
4 - Should crash at some point (can be after 2-3 operations or 20)

### Minimal reproduction project

Clone https://github.com/Levrault/mr-mister-and-the-winter
Open Player.tscn
Use the AnimationPlayer node
Select an animation (doesn't matter)
Edit some animations by moving the associated player meshes
You should get a crash

Sorry I'm not able to create a better minimal projet but it should be quite easy to reproduce with this one

**Comment by Eoin-ONeill-Yokai** [comment]
I can confirm this bug. Spamming the key button is the easiest way to get it to happen quickly, though the users MRP also works. 

### Backtrace
```
>	godot.windows.editor.x86_64.exe!EditorProperty::gui_input(const Ref<InputEvent> & p_event) Line 666	C++
 	godot.windows.editor.x86_64.exe!Control::_call_gui_input(const Ref<InputEvent> & p_event) Line 1714	C++
 	godot.windows.editor.x86_64.exe!Viewport::_gui_call_input(Control * p_control, const Ref<InputEvent> & p_input) Line 1329	C++
 	godot.windows.editor.x86_64.exe!Viewport::_gui_input_event(Ref<InputEvent> p_event) Line 1559	C++
 	godot.windows.editor.x86_64.exe!Viewport::push_input(const Ref<InputEvent> & p_event, bool p_local_coords) Line 2797	C++
 	godot.windows.editor.x86_64.exe!Window::_window_input(const Ref<InputEvent> & p_ev) Line 1309	C++
 	[Inline Frame] godot.windows.editor.x86_64.exe!call_with_variant_args_helper(Window *) Line 262	C++
 	[Inline Frame] godot.windows.editor.x86_64.exe!call_with_variant_args(Window * p_instance, void(Window::*)(const Ref<InputEvent> &) p_method, const Variant * *) Line 376	C++
 	godot.windows.editor.x86_64.exe!CallableCustomMethodPointer<Window,Ref<InputEvent> const &>::call(const Variant * * p_arguments, int p_argcount, Variant & r_return_value, Callable::CallError & r_call_error) Line 104	C++
 	godot.windows.editor.x86_64.exe!Callable::callp(const Variant * * p_arguments, int p_argcount, Variant & r_return_value, Callable::CallError & r_call_error) Line 51	C++
 	godot.windows.editor.x86_64.exe!DisplayServerWindows::_dispatch_input_event(const Ref<InputEvent> & p_event) Line 2170	C++
 	godot.windows.editor.x86_64.exe!Input::_parse_input_event_impl(const Ref<InputEvent> & p_event, bool p_is_emulated) Line 663	C++
 	godot.windows.editor.x86_64.exe!Input::flush_buffered_events() Line 886	C++
 	godot.windows.editor.x86_64.exe!DisplayServerWindows::process_events() Line 1864	C++
 	godot.windows.editor.x86_64.exe!OS_Windows::run() Line 1274	C++
 	godot.windows.editor.x86_64.exe!widechar_main(int argc, wchar_t * * argv) Line 181	C++
 	godot.windows.editor.x86_64.exe!_main() Line 205	C++
 	godot.windows.editor.x86_64.exe!main(int argc, char * * argv) Line 217	C++
 	[External Code]	

```

### Other Points of Interest

Output has the following before crash:

```
core\object\object.cpp:1800 - Object <Object#3703369167943> was freed or unreferenced while a signal is being emitted from it. Try connecting to the signal using 'CONNECT_DEFERRED' flag, or use queue_free() to free the object (if this object is a Node) to avoid this error and potential crashes.
Exception thrown at 0x00007FF676BE64CB in godot.windows.editor.x86_64.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.
```

Likely need to revisit our connections to make sure that we keep them sanitary.

**Comment by Eoin-ONeill-Yokai** [comment]
Hi @Levrault ,

I've gone ahead and made a fix for this. Do you have the means to build that branch for testing to see if this fully resolves this issue on your end?

Thanks,
Eoin.

**Comment by Levrault** [comment]
I pull and build your branch and spawned the key button, seems to works fine now!
