### ISSUE TITLE
rich text label: [center] und [right] don't work correct

### ISSUE THREAD

**Issue by Lebostein** [godotengine/godot#6982]
**Operating system or device - Godot version:**
Mac OS 10.10.5, Godot 2.1

**Issue description** (what happened, and what was expected):

Only the first line is correct aligned. All other lines are left-aligned to the first line:
What I get: https://dl.dropboxusercontent.com/u/13472834/Foren/godot_rich.png
What I expect: https://dl.dropboxusercontent.com/u/13472834/Foren/godot_rich2.png

**Steps to reproduce:**

Add a rich text label and add text:

Godot provides a huge set of common tools, so you can just focus on making your game without reinventing the wheel.

[right]Godot provides a huge set of common tools, so you can just focus on making your game without reinventing the wheel.[/right]

[center]Godot provides a huge set of common tools, so you can just focus on making your game without reinventing the wheel.[/center]

**Link to minimal example project** (optional but very welcome):

**Comment by Lebostein** [comment]
Where I can find (in documentation?) which tags are supported in Godot? In the official manual there is a hint to [color] only.

**Comment by volzhs** [comment]
https://github.com/godotengine/godot-demo-projects/tree/master/gui/rich_text_bbcode
I think this demo uses all support tags.

**Comment by Lebostein** [comment]
The [fill] [/fill] tag is also full of bugs:
- Sometimes text disappears on the right side
- there seems a big problem with punctuation marks. Sometimes space was added between a word and a following comma for example "setup, which" --> "setup   ,   which"
- Seems to come into conflict with other tags

**Comment by volzhs** [comment]
what you are trying to do can be achieved with just `Label` and some other `Control` nodes, easily.

**Comment by volzhs** [comment]
[center], [right] tag works as expected.
The [fill] tag bug is different issue.

test result from another site http://www.tytyweb.net/projects/smf/bbcode/
![image](https://cloud.githubusercontent.com/assets/8281454/19904630/bc87207a-a0b6-11e6-8425-6f00c1d0d26e.png)

seems you have never heard of bbcode

**Comment by volzhs** [comment]
sorry I deleted my last comment. I miss-read it. :(

**Comment by volzhs** [comment]
I read `rich_text_label.cpp`, it seems not easy to fix it. :(

**Comment by GammaGames** [comment]
After poking around in /scene/gui/rich_text_label.cpp, it looks like it's not getting the width for each line. I'm not sure how much it would have to change, but the script would essentially have to:

1.  Store the longest line for each tag
2. Get the number of characters for that line
3. Do one of the following for each line to get the offset
    * For center:
        3.1 Subtract the max length from the current line count
        3.2 Divide the difference by 2
        3.3 Either add that amount of spaces to the beginning of the line or make the line's margin the result * character width
    * For right:
        3.1 Subtract the max length from the current line count
        3.2 Either add that amount of spaces to the beginning of the line or make the line's margin the result * character width
4. ???
5. Profit

I'm not sure how the class is currently structured, but I see that currently https://github.com/godotengine/godot/blob/5f0ea4ddcfb8de5d0f1c3080a36d6291c26086ce/scene/gui/rich_text_label.cpp#L174 has a part where they add the spaces in commented out, so maybe it was worked on previously? I'm not sure what the flow of the file is and if it'd need any reorganization. You could also do the spaces as you parse each line, it might only be a little more complicated and one less loop through the text (negligible optimizations are the best!)

**Comment by kubecz3k** [comment]
It so happen I encouraged `[center]` problem today in 0b7df80eb1b1f6415b397f0ac115da5014b7b8a8, so it's still viable.

**Comment by eligt** [comment]
The images above on dropbox give a 404 but I think I've fixed this issue in my branch:
![Selection_121](https://user-images.githubusercontent.com/2043211/59531387-b78e8c80-8edd-11e9-8009-b58c077bc2ac.png)

Right now I have a pull request pending (https://github.com/godotengine/godot/pull/29762) once that's merged in I can commit this fix too.

**Comment by lfkdev** [comment]
aaaand .. its still broken.

**Comment by Calinou** [comment]
@lfkdev This was already reported in #34308.
