### ISSUE TITLE
The height field is not exposed in GPUParticlesCollisionHeightField3D

### ISSUE THREAD

**Issue by yosh3333** [godotengine/godot#69824]
### Godot version

4.x

### System information

All

### Issue description

The height field in GPUParticlesCollisionHeightField3D should be exposed as a texture accessible to the user, similarly to how GPUParticlesCollisionSDF3D exposes the SDF as a texture. 

This is important for users that need to manually place particles in a shader according to the height field (e.g. populating surfaces with grass GPU particles in a forest scene composed of multiple terrain meshes). 

### Steps to reproduce

NA

### Minimal reproduction project

NA

**Comment by Calinou** [comment]
The heightfield is generated in real-time. If you need baked collision, use GPUParticlesCollisionSDF3D instead.
