### ISSUE TITLE
Crash on project load when set to gl_compatibility

### ISSUE THREAD

**Issue by Malcolmnixon** [godotengine/godot#69836]
### Godot version

4.0 beta 8

### System information

Windows 11, gl_compatibility, NVidia RTX 3070 TI

### Issue description

Godot crashes when opening a project set with gl_compatibility. I compiled a custom version and found the problem occurs in rasterizer_scene_gles3.cpp line 2334:
https://github.com/godotengine/godot/blob/ae86d907e75c3de9b039e7cc77e521bc9739e6dc/drivers/gles3/rasterizer_scene_gles3.cpp#L2332-L2335

This code assumes it can pass a null in for the fourth indices argument because an array has already been bound to the GL context previously at line 2219:
https://github.com/godotengine/godot/blob/ae86d907e75c3de9b039e7cc77e521bc9739e6dc/drivers/gles3/rasterizer_scene_gles3.cpp#L2215-L2222

It turns out the glBindBuffer call can be skipped, and when its skipped the crash occurs. If I modify the code as follows it works:
```cpp
		bool use_index_buffer = index_array_gl != 0;
		//if (prev_index_array_gl != index_array_gl || prev_vertex_array_gl != vertex_array_gl) {
			if (index_array_gl != 0) {
				// Bind index each time so we can use LODs
				glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, index_array_gl);
			}
			prev_index_array_gl = index_array_gl;
		//}
```

The glDrawElements call on 2334 was changed by https://github.com/godotengine/godot/commit/5f52936350c9d1fea3f7c93d7d33b815e06d813d on Jun 15.
The condition on 2219 around the glBindBuffer call was changed by https://github.com/godotengine/godot/commit/9ce57050a5d12776deedd44fcb82dd5841a56686 on Nov 15.

### Steps to reproduce

I reproduced this using the Godot XR Tools project - https://github.com/GodotVR/godot-xr-tools/tree/4.0-dev:
 1. Open the godot-xr-tools project (4.0-dev branch) in Godot 4 beta 8
 2. Switch the project renderers to gl_compatibility
 3. Save and re-load the project

### Minimal reproduction project

I haven't been able to recreate it by constructing a simple demo project and adding a few simple objects. As the code is dealing with rendering meshes, it may be related to the meshes loaded by the godot-xr-tools proejct.

**Comment by Malcolmnixon** [comment]
I think I've identified the problem - its in the rasterizer_scene_gles3.cpp in the following block of code starting at 2206:
```cpp
		index_array_gl = mesh_storage->mesh_surface_get_index_buffer(mesh_surface, surf->lod_index);

		if (prev_vertex_array_gl != vertex_array_gl) {
			if (vertex_array_gl != 0) {
				glBindVertexArray(vertex_array_gl);
			}
			prev_vertex_array_gl = vertex_array_gl;
		}

		bool use_index_buffer = index_array_gl != 0;
		if (prev_index_array_gl != index_array_gl || prev_vertex_array_gl != vertex_array_gl) {
			if (index_array_gl != 0) {
				// Bind index each time so we can use LODs
				glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, index_array_gl);
			}
			prev_index_array_gl = index_array_gl;
		}
```

The first if condition tests whether the vertex array needs to be updated, and if so:
1. Binds the vertex array
2. Updates the previous vertex array

The second if condition tests whether either the index or vertex array have changed, and if so:
1. Binds the index array
2. Updates the previous index array

The problem is that the second if condition ```prev_vertex_array_gl != vertex_array_gl``` happens *after* the previous vertex array is updated; and so the test doesn't work.

**Comment by Malcolmnixon** [comment]
It took a bit of tracking down in the documentation and stackoverflow (https://stackoverflow.com/questions/10000776/opengl-3-glbindvertexarray-invalidates-gl-element-array-buffer), but yes, the glBindVertexArray call clears any bound GL_ELEMENT_ARRAY_BUFFER. As such the bug in the code can make call glBindVertexArray which clears the index array, but then skip calling glBindBuffer to bind the index array. Then it tries to draw the elements without a buffer and using null for the indices causing the crash.

A fix that works for me is to invalidate prev_index_array_gl if the vertex array changes:
```cpp
		if (prev_vertex_array_gl != vertex_array_gl) {
			if (vertex_array_gl != 0) {
				glBindVertexArray(vertex_array_gl);
			}
			prev_vertex_array_gl = vertex_array_gl;

			// Invalidate the previous index array
			prev_index_array_gl = 0;
		}

		bool use_index_buffer = index_array_gl != 0;
		if (prev_index_array_gl != index_array_gl || prev_vertex_array_gl != vertex_array_gl) {
			if (index_array_gl != 0) {
				// Bind index each time so we can use LODs
				glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, index_array_gl);
			}
			prev_index_array_gl = index_array_gl;
		}
```

**Comment by clayjohn** [comment]
Nice catch, I guess you can also remove the second check for ``prev_vertex_array_gl != vertex_array_gl`` now that you are invalidating the ``prev_index_array``. 

Feel free to make a PR with this fix!

**Comment by pseidemann** [comment]
hi,
does this bug also exist in 3.x?

**Comment by Zireael07** [comment]
@pseidemann No, this is 4.x specific bug
