### ISSUE TITLE
Functions that return Variant ignore type hints and break autocomplete

### ISSUE THREAD

**Issue by Haydoggo** [godotengine/godot#69837]
### Godot version

v4.0.beta8.official [45cac42c0]

### System information

Windows 10

### Issue description

Some functions that return `Variant` seem to break autocomplete, even when the method has a return type hint.

Interestingly, a function with `return dict.get("key")` will break autocomplete, but `return dict["key"]` will not.
See below for more examples.

### Steps to reproduce

example script that demonstrates some cases that break autocomplete:
```gdscript
@tool
extends EditorScript

var dict := {"key": Node2D.new()}

func _run():
	method_1().position # Autocomplete works as expected
	method_2().position # Autocomplete works as expected
	method_3().position # No autocomplete popup at all
	method_4().position # No autocomplete popup at all
	

func method_1() -> Node2D:
	return dict["key"]

func method_2() -> Node2D:
	return dict.get("key") as Node2D

func method_3() -> Node2D:
	return dict.get("key")

func method_4() -> Node2D:
	return Marshalls.base64_to_variant("")
```

### Minimal reproduction project

N/A

**Comment by kleonc** [comment]
The same for non-`@tool` script.
