### ISSUE TITLE
InputEventKey.get_keycode_with_modifiers() returns wrong values (German keyboard)

### ISSUE THREAD

**Issue by ascripter** [godotengine/godot#69830]
### Godot version

4.0 beta8

### System information

Windows 10

### Issue description

`InputEventKey.get_keycode_with_modifiers()` returns wrong values on German Keyboard.

In case it matters: This happens for my notebook's keyboard (Lenovo T470p) as well as my external Microsoft Ergonomic keyboard. The keyboards' drivers in the Device Manager are named "HID keyboard device" and "Standard PS/2 Keyboard"

### Steps to reproduce

1. Set Windows to [German keyboard layout](https://en.wikipedia.org/wiki/German_keyboard_layout) and language.
2. Make a node with the code below and run it (or use Minimal reproduction project)
3. When pressing for example the Umlaut-Keys ö, ü or ä, I get 96 (QuoteLeft), 59 (Semicolon) and 39 (Apostrophe) respectively (they are not equal to the physical keycodes though). I would expect keycodes 214 (Ö), 220 (Ü) and 196 (Ä). The locale is returned correctly however.

```
extends Control

func _ready():
	print(OS.get_locale())
	print(OS.get_locale_language())

func _input(event):
	if event is InputEventKey:
		var key: int = event.get_keycode_with_modifiers()
		var key_phys: int = event.get_physical_keycode_with_modifiers()
		print("keycode  %s (%s), physical %s (%s)" %
			[key, OS.get_keycode_string(key), 
			key_phys, OS.get_keycode_string(key_phys)])
```

### Minimal reproduction project

[get_keycode_demo.zip](https://github.com/godotengine/godot/files/10198319/get_keycode_demo.zip)

**Comment by bruvzg** [comment]
These are correct values, there are no dedicated keycodes / scancodes for `ö`, `ü` or `ä`, see https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes and http://download.microsoft.com/download/1/6/1/161ba512-40e2-4cc9-843a-923143f3456c/scancode.doc

You can use `unicode` property to get layout specific character value.

I have no idea why there's `ODIAERESIS` and other similar codes in the Godot key list (maybe it is/was supported on some OS, definitely not on Windows, but it seems to be unused).

**Comment by bruvzg** [comment]
Since currently getting any of these Latin-1 keycodes in only possible on by lossy conversion from Unicode on iOS and a specific X11 config, we probably should allow using `unicode` values in the actions and restrict keycode list to the least common values (equivalent of PS/2 scancodes) to avoid confusion.

**Comment by ascripter** [comment]
Without understanding all the technical details, I think it's relevant that there's some process with which we know what key on their keyboard the user has pressed, and also showing it to them (my main use case is to offer customizable controls.)

I didn't realise that [`InputEventKey.unicode`](https://docs.godotengine.org/en/stable/classes/class_inputeventkey.html#class-inputeventkey-property-unicode) is what I need, so `OS.get_keycode_string(event.unicode)` returns what I actually expected - well, at least when not pressing for example `Shift+ü`, otherwise I get `Udiaeresis` when I was expecting either `Ü` or `Shift+ü`. Seems I'm still missing something...

**Comment by bruvzg** [comment]
> I didn't realise that [InputEventKey.unicode](https://docs.godotengine.org/en/stable/classes/class_inputeventkey.html#class-inputeventkey-property-unicode) is what I need, so OS.get_keycode_string(event.unicode) returns what I actually expected - well, at least when not pressing for example Shift+ü, otherwise I get Udiaeresis when I was expecting either Ü or Shift+ü. Seems I'm still missing something...

Right now, there's no convenient way to get is as text, but you can do something like this:

```gdscript
if event is InputEventKey:
	var name = ""
	if event.is_ctrl_pressed():
		name += OS.get_keycode_string(KEY_CTRL) + "+";
	if event.is_shift_pressed():
		name += OS.get_keycode_string(KEY_SHIFT) + "+";
	if event.is_alt_pressed():
		name += OS.get_keycode_string(KEY_ALT) + "+";
	if event.is_meta_pressed():
		name += OS.get_keycode_string(KEY_META) + "+";
	name += String.chr(event.unicode).to_upper()

	print(name)
```

**Comment by bruvzg** [comment]
> Right now, there's no convenient way to get is as text, but you can do something like this

Actually, do not use this, it might work in German keyboard layout, but not in general. There are plenty of layouts which have completely different character bound to Key and Shift+Key, also `unicode` won't be set when using `Ctrl` / `Alt` modifiers.

**Comment by bruvzg** [comment]
Currently, key events have:
- `physical_keycode` - which is position on a keyboard (should work fine, useful for stuff like `WASD`, when you do not care what character is on the key).
- `keycode` - which is basic Latin in the current keyboard layout (if it's available), so something like `Ctlr+S` will always be triggered by the key with `S` on it. For non-Latin layouts, it's usually replaced with `physical_keycode`.
- `unicode` - which is used for input, `Ü` will have `unicode=ü` and `Shift+Ü` will have `unicode=Ü`, but in other layout the same key can be for example `Key -> unicode=ش` and `Shift+SameKey -> unicode=»`, Alt and Ctrl combinations can have some other Unicode values or none.

So maybe we should add another "unshifted" Unicode value to always give the primary character (like it was pressed without any modifiers) + list of modifiers, and allow using it as an option for action mappings.
