### ISSUE TITLE
GUI: No scrolling while drag and drop

### ISSUE THREAD

**Issue by Lebostein** [godotengine/godot#6983]
**Operating system or device - Godot version:**
Mac OS 10.10.5, Godot 2.1

**Issue description** (what happened, and what was expected):
If you move nodes from up to down or down to up the node list don't scroll. So you can move nodes inside the visible entries of the list only.

If you move s sprite from the ressource browser to the sprite definition with drag and drop, then the sprite slot have to be visible. Also here no automatic scrolling with an object "in the hand".

**Comment by volzhs** [comment]
is this resolved by #6529?

**Comment by pkowal1982** [comment]
#6529 should fix the issue for the first part - node editor, it was merged to 2.1.1.
@Lebostein can you check it with 2.1.1 rc2?

**Comment by volzhs** [comment]
I can confirm this is fixed on current master head. cdc4664226cdc397d054b7390d0f75028d40412c
