### ISSUE TITLE
OpenXR: SSAO is distorted for the right eye

### ISSUE THREAD

**Issue by jtnicholl** [godotengine/godot#69843]
### Godot version

v4.0.beta.custom_build [ae86d907e]

### System information

Fedora 36

### Issue description

When enabling screen-space ambient occlusion in a VR project, the effect appears normal in the left eye, but is offset to the right in the right eye.

I _think_ it's rendering to the left eye only and just copying it over to the right, but I'm not 100% sure.

![openxr_ssao](https://user-images.githubusercontent.com/44414418/206831497-876930d5-9b13-49e3-923f-a984f76e2525.jpg)

### Steps to reproduce

Enable SSAO on a VR application.

### Minimal reproduction project

[openxr_ssao.zip](https://github.com/godotengine/godot/files/10199286/openxr_ssao.zip)

**Comment by jtnicholl** [comment]
Related: #69000

**Comment by BastiaanOlij** [comment]
Should be fixed in #72838
