### ISSUE TITLE
`SCREEN_TEXTURE` is blank when `Use Physical Light Units` is enabled

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot#69847]
### Godot version

4.0.beta8

### System information

Windows 10, GTX 980 Ti, Vulkan Forward+

### Issue description

Before enabling Physical Light Units:
![image](https://user-images.githubusercontent.com/4955051/206844845-78ce11c0-5564-4e52-ad50-1e3a0527817c.png)

After enabling Physical Light Units:
![image](https://user-images.githubusercontent.com/4955051/206845082-36c51875-536f-4421-88f8-fd5118e4143b.png)

### Steps to reproduce

Create a mesh and assign a Standard Material to it and set transparency to alpha, set Albedo's alpha to 0 and enable refraction.
Then enable `Use Physical Light Units` in the project settings.

### Minimal reproduction project

[refraction_real_light_units_bug.zip](https://github.com/godotengine/godot/files/10199691/refraction_real_light_units_bug.zip)

**Comment by atirut-w** [comment]
Still happening on alpha 10

**Comment by Calinou** [comment]
This is likely because the screen texture is being generated, but it's way too dark as a result of not accounting for physical light units.
