### ISSUE TITLE
C# Jagged arrays cause Godot 4's ScriptPropertiesGenerator and ScriptSerializationGenerator to fail with NullPointerException

### ISSUE THREAD

**Issue by mewore** [godotengine/godot#69862]
### Godot version

4.0.0-beta1

### System information

Linux Mint 20.3 x86_64

### Issue description

This line, for example:
```cs
    private int[][] thisDoesNotWork;
```

causes the following errors:
```
CSC(0,0): Generator 'ScriptPropertiesGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'NullReferenceException' with message 'Object reference not set to an instance of an object.'
CSC(0,0): Generator 'ScriptSerializationGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'NullReferenceException' with message 'Object reference not set to an instance of an object.'
```

I don't know where I can find any logs to see more info on this.

-----

These lines are OK:
```cs
    private int[] thisWorks;

    private List<List<int>> thisAlsoWorks;
```
Since nested lists work, I'll just use them instead of jagged arrays in the meantime.

### Steps to reproduce

In any class:
```cs
    private int[][] thisDoesNotWork;
```

It can also be `public`:
```cs
    public int[][] ThisDoesNotWork;
```

### Minimal reproduction project

[godot-breaker.zip](https://github.com/godotengine/godot/files/10200545/godot-breaker.zip)

**Comment by raulsntos** [comment]
Likely fixed by https://github.com/godotengine/godot/pull/65946. Can you still reproduce in Godot 4.0 beta 8?

**Comment by mewore** [comment]
Sorry, I've also just noticed there's beta 8, which is much more recent than beta 1. I'm checking if it's fixed there...

**Comment by mewore** [comment]
Yeah, it does work with beta 8. Nevermind.
