### ISSUE TITLE
[4.0 beta] Empty tab container throws `tabs.is_empty` error on mouse hover

### ISSUE THREAD

**Issue by asolux** [godotengine/godot#69863]
### Godot version

4.0.beta7

### System information

Windows 10, 64bit

### Issue description

Creating an empty tab container will trigger an error when the mouse pointer moves over it.
```
E 0:00:03:0084   _update_hover: Condition "tabs.is_empty()" is true.
  <C++ Source>   scene/gui/tab_bar.cpp:785 @ _update_hover()
```
On the other hand, if you fill up the container tab bit by bit, it becomes more and more difficult to trigger the error. However, the error is triggered when there are objects in it.

### Steps to reproduce

Create a tab container and add one or more tabbars. Start the project and move the mouse pointer over it.

### Minimal reproduction project

[GD4_MinTab_GDS.zip](https://github.com/godotengine/godot/files/10200579/GD4_MinTab_GDS.zip)

**Comment by YeldhamDev** [comment]
The issue is not on `TabContainer`, but on `TabBar`, I will take a look at it. By the way, you don't need to add `TabBar`s to add tabs to it, just add the `Control` nodes directly.

**Comment by BeyondXinXin** [comment]
您好！您的邮件已收到！我查阅后，尽快回复您！

**Comment by tinmanjuggernaut** [comment]
Beta 10, Win11/64.

I have this issue on tabs with content.

![image](https://user-images.githubusercontent.com/632766/210167610-b7be941e-4829-4034-8b30-e1d09527e06d.png)

On mouse hover over various contents I get this error.
* Labels - error
* texture - error
* empty space - error
* Button - no error

It's not just "an error" It is error spam, dumping an error for every mouse update while hovering over the tabs.

```
ERROR: Condition "tabs.is_empty()" is true.
   at: _update_hover (scene/gui/tab_bar.cpp:785)
```
I use tabars so I can define the tab text.


Thanks for the pending PR fix.
