### ISSUE TITLE
export(Object) doesn't let me assign any object to the variable in the inspector

### ISSUE THREAD

**Issue by dawkot** [godotengine/godot#6987]
Windows 10 - Godot 2.1 and 2.2

When used, the variable is showed in the inspector, but upon clicking it there are no options to assign or clear the value. It works if I use NodePath type instead of Object.

**Comment by vnen** [comment]
`export(Object)` should not even work. Only builtin and resource types can be used with `export`.

**Comment by volzhs** [comment]
so, the bug tag means, godot script editor prevents to write `export(Object)` -shows error or somethig-, right?

**Comment by vnen** [comment]
> so, the bug tag means, godot script editor prevents to write export(Object) -shows error or somethig-, right?

It *should* show an error in this case, like it shows when you try `export(Node2D)`.

**Comment by JarLowrey** [comment]
Why can't objects such as Node2D or Texture be exported? It'd make it really easy to assign them from the game editor

**Comment by Zireael07** [comment]
Instead of exporting a Texture, export a material.

**Comment by bojidar-bg** [comment]
@JarLowrey You can (and should) export a NodePath instead of Node, and Texture should work fine (since it is a Resource).
