### ISSUE TITLE
could i get the gridmap in modules from godot version 3.3.3 and put it in this version 3.2.2 and compile?

### ISSUE THREAD

**Issue by MiqueiasDevGames** [godotengine/godot#69876]
### Godot version

3.2.2 and 3.3.

### System information

Linux Debian 11 i686

### Issue description

I'm here on my computer i686 pentium 4 I compiled godot 3.2.2 it took a few hours, but as bakedlight was crashing in the compiled version, I decided to do that and it worked, but I still have problems when I use it with gridmap and Bake in All in directionlight, oh I thought, could I get the gridmap in modules from godot version 3.3.3 and put it in this version 3.2.2 and compile?

### Steps to reproduce

could i get the gridmap in modules from godot version 3.3.3 and put it in this version 3.2.2 and compile?

### Minimal reproduction project

could i get the gridmap in modules from godot version 3.3.3 and put it in this version 3.2.2 and compile?

**Comment by MiqueiasDevGames** [comment]
answer me @Calinou

**Comment by MiqueiasDevGames** [comment]
Or I could take bakelight from godot 3.2.2 and put it in godot 3.3.3, since as of 3.3 it no longer works on x32 systems 
answer me @Calinou

**Comment by Calinou** [comment]
Modules between engine versions are not compatible with each other. The old CPU lightmapper (the one used before 3.3) is not supported anymore either.

> since as of 3.3 it no longer works on x32 systems

Embree only supports 64-bit systems indeed: https://github.com/godotengine/godot/blob/9983df9210b2ba4e9161c9fc52eefef9d1d3c07b/modules/lightmapper_cpu/config.py#L15-L16

I'm afraid you'll have to do without lightmaps if you want to use a supported Godot version.

**Comment by MiqueiasDevGames** [comment]
@Calinou 

Get it, BackLight from version 3.2.2 is a plugin, not a module after I saw it, so I put the one from version 3.2.2 in version 3.3.3
I modified them:

scene/3D/baked_light.cpp
scene/3D/baked_light.h
and
editor/plugins/baked_lightmap_editor_plugin.cpp
editor/plugins/baked_lightmap_editor_plugin.h

In godot 3.3.3 by godot 3.2.2

In

scene/3D/baked_light.cpp

I modified the calls to the instance_set_use method to take 5 arguments instead of 3
adding these variables
that I saw that were used in VisualServer

Rect2 uv_rect = Rect2(0, 0, 1, 1);
int slice_index = -1;

Oh, it was like this:

instance_set_use_lightmap(instance, get_instance(), lightmap->get_rid(), slice_index, uv_rect);


I also put the scene/3D/voxel_light_baker.cpp
and
scene/3D/voxel_light_baker.h

from godot 3.2.2 to 3.3.3
I just changed the name to voxel_light_bakerM
then I changed their references within themselves and in the scene/3D/baked_light

and it worked, much better than in 3.2.2 alias, it even looked great on the computer, even on android it worked and I didn't even need to do the export templates, but on android it was kind of weird, I'll need the export templates, but then the NDK is only 64bit

**Comment by MiqueiasDevGames** [comment]
@Calinou 
I'm going to upload here to github, do you export models to android for me, on your machine?

**Comment by MiqueiasDevGames** [comment]
@Calinou 

if you can generate a godot executable also one of those fast and small, here it is not possible.

Create a repository with this modification of Godot so that others can also use it and even make improvements with the old bakedlight, who knows in the future it will become something better.

Oh, you put everything there

**Comment by MiqueiasDevGames** [comment]
everything is working here on my machine.
Now I just need to create export models for android, but NDK is only 64bits, help me there @akien-mga 

> @akien-mga  I'm going to upload here to github, do you export models to android for me, on your machine?
> 
> Here could you generate the export templates for me, I just need it for android
> 
> You will only need NDK 21.4.7075529
> 
> Download source code Godot 3.3.3
> 
> clone the repository below, paste in the root of godot, to overwrite https://github.com/MiqueiasDevGames/Godot-3.3.3_LightMapGodot3.2.2
> 
> and generate the models for android: armv7 arm64v8 x86 x86_64
> 
> and go up and put the link here.
> 
> Please,Please,Please,Please,Please,Please,

**Comment by MiqueiasDevGames** [comment]
@Calinou and @akien-mga  no longer need not build the export models, I asked because on android here the gridmaps were leaking, there were some black lines between the blocks, but then I created it when creating the meshlib I unchecked the mask collision of the blocks, to they don't collide with themselves, and also on the gridmap itself, then it worked, there are still some small leaks, but nothing that a few tweaks here and there can't fix.
Thanks!!!
