### ISSUE TITLE
OpenGL: Project crashes when there's an OmniLight3D in the scene

### ISSUE THREAD

**Issue by Henrique-Henrique** [godotengine/godot#69886]
### Godot version

4.0.beta8

### System information

Windows 11 / Web

### Issue description

EDIT - Using `GLES3`

Project break when has OmniLight3D in Scene

```
E 0:00:00:0667   _display_error_with_code: SceneShaderGLES3: Fragment shader compilation failed:
ERROR: 0:659: 'omni_lights' : undeclared identifier 
ERROR: 0:659: 'omni_lights' :  left of '[' is not of type array, matrix, or vector  
ERROR: 0:659: '' : missing #endif 
ERROR: 0:659: '=' :  cannot convert from ' const float' to ' temp 3-component vector of float'
ERROR: 0:659: '' : compilation terminated 
ERROR: 5 compilation errors.  No code generated.
<C++ Source>   drivers/gles3/shader_gles3.cpp:242 @ _display_error_with_code()
```

### Steps to reproduce

Just Add OmniLight3D to Scene

### Minimal reproduction project

Create New Project or add to an existent one.

**Comment by Henrique-Henrique** [comment]
The same occurs with `SpotLight3D`

```
E 0:00:00:0957   _display_error_with_code: SceneShaderGLES3: Fragment shader compilation failed:
ERROR: 0:706: 'spot_lights' : undeclared identifier 
ERROR: 0:706: 'spot_lights' :  left of '[' is not of type array, matrix, or vector  
ERROR: 0:706: '' : missing #endif 
ERROR: 0:706: '=' :  cannot convert from ' const float' to ' temp 3-component vector of float'
ERROR: 0:706: '' : compilation terminated 
ERROR: 5 compilation errors.  No code generated.

<C++ Source>   drivers/gles3/shader_gles3.cpp:242 @ _display_error_with_code()
```

**Comment by clayjohn** [comment]
I thought I already fixed this bug in https://github.com/godotengine/godot/pull/69634. But it's in beta 8 so clearly there is something else going on. Do you happen to have an MRP that reproduces the issue?

**Comment by Henrique-Henrique** [comment]
Well, I created a new project, changed to GLES3 renderer, and added `OmniLamp3D` or `SpotLight3D` , and the editor immediately showed the error. But here an MRP

[TestingOmniLamp.zip](https://github.com/godotengine/godot/files/10201491/TestingOmniLamp.zip)
