### ISSUE TITLE
UI Label Uppercase  

### ISSUE THREAD

**Issue by evan-gordon** [godotengine/godot#69888]
### Godot version

4.0 beta 8

### System information

Linux PopOS

### Issue description

When working with a UI Label Node if uppercase is enabled but the text field is empty U_STRING_NOT_TERMINATED_WARNING is thrown.

Expected behavior would be that uppercase would not do anything if the text field were empty.

### Steps to reproduce

Create a Node, enable the uppercase option and run the scene.

Alternatively via code one can do:
```
extends Control


func _ready():
	var new_label = Label.new()
	new_label.uppercase = true
	new_label.text = ""
	self.add_child(new_label)
```

### Minimal reproduction project

N/A

**Comment by Zireael07** [comment]
Ooo. I've been having this for a couple of betas but could never figure it out - thanks!

**Comment by evan-gordon** [comment]
Thanks! It's definitely quite the annoyance.
