### ISSUE TITLE
Bugs in obtaining control location

### ISSUE THREAD

**Issue by xiaoliang6669** [godotengine/godot#69899]
### Godot version

4.0-beta8

### System information

win10

### Issue description

The obtained position is displayed incorrectly

![11111](https://user-images.githubusercontent.com/112788136/206894494-814c75cc-2cbf-42c7-b2c0-3148bc90a035.png)

### Steps to reproduce

![222222](https://user-images.githubusercontent.com/112788136/206894510-53691a25-539c-4768-aa01-3c2621d68a69.png)

### Minimal reproduction project

Not applicable

**Comment by Zireael07** [comment]
HBoxContainer controls the button's positioning. And IIRC some functions need a one frame delay before they work - this is probably a combination of both these things.

Also you were asked to provide MRPs, so don't be surprised if this is closed with zero action.

**Comment by xiaoliang6669** [comment]
But I don't use beta 8. There has never been such a problem before. The beta 8 has just been launched

**Comment by Zireael07** [comment]
If you say this worked with beta 7, you should have said so in the OP. My point about MRP still stands, though

**Comment by xiaoliang6669** [comment]
> 如果你说这适用于beta 7，你应该在OP中这么说。不过，我对MRP的观点仍然成立。

To be exact, projects that should be started from 5 have never encountered such problems. Since 8, such problems have occurred. According to your ideas, the delay has been added. I found that the variable initialization variable behind the delay statement is not available in the upper node. Alas, it has to be modified again
