### ISSUE TITLE
Extending CharacterBody3D script crash

### ISSUE THREAD

**Issue by HalfAsleepSam** [godotengine/godot#69904]
### Godot version

4.0 beta 7

### System information

Windows 10, 8 GB RAM

### Issue description

Extending a CharacterBody3D crashes the editor

### Steps to reproduce

1. make a characterbody2d script
2. extend it in another scene
3. crash

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
I can't reproduce this on 4.0.beta10.

**Comment by akien-mga** [comment]
Closing due to lack of details.
