### ISSUE TITLE
Editor crashing when searching for material properties after assigning PBR textures on a material that is currently applied to a visible mesh

### ISSUE THREAD

**Issue by Kronos328** [godotengine/godot#69909]
### Godot version

4.0.beta8.official (45cac42c0b511672240c1fcccecfd3cc0580edcb)

### System information

OS Arch Linux x86_64; kernel 6.0.12-arch1-1; CPU AMD Ryzen 5 3400G (8) @ 3.700GHz; GPU AMD ATI Radeon RX 6600/6600 XT/6600M 

### Issue description

Hello! 

I've experienced crashing on the editor when trying to search for a material property after assigning a PBR texture on a material that is currently being displayed on a mesh. 

This bug does not seem to be 100% consistent though. I don't know if it could be a difference in the order of actions that i took when testing this, but I'd estimate about 30% of the times I tried to reproduce the bug it didn't happen.

After experiencing the bug once, I tried to reproduce it again while logging the output to the terminal, here is the back-trace from when the crash happened:

```
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.beta8.official (45cac42c0b511672240c1fcccecfd3cc0580edcb)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /usr/lib/libc.so.6(+0x38a00) [0x7f2ec66e8a00] (??:0)
[2] /usr/bin/godot4() [0x4af062e] (??:0)
[3] /usr/bin/godot4() [0x2268521] (??:0)
[4] /usr/bin/godot4() [0x1c854c9] (??:0)
[5] /usr/bin/godot4() [0x434c128] (??:0)
[6] /usr/bin/godot4() [0x41c8d84] (??:0)
[7] /usr/bin/godot4() [0x492b535] (??:0)
[8] /usr/bin/godot4() [0x43e18f7] (??:0)
[9] /usr/bin/godot4() [0x2a22228] (??:0)
[10] /usr/bin/godot4() [0xe6d496] (??:0)
[11] /usr/bin/godot4() [0xd9f143] (??:0)
[12] /usr/lib/libc.so.6(+0x23290) [0x7f2ec66d3290] (??:0)
[13] /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7f2ec66d334a] (??:0)
[14] /usr/bin/godot4() [0xdc095e] (??:0)
-- END OF BACKTRACE --
================================================================
```
Thank you in advance for your time.

### Steps to reproduce

After opening the reproduction project, do the following:

1. Open the main scene
2. Click on the "MeshInstance3D" node
3. Go to the "Material Override" property and create a new StandardMaterial3D, clicking on the <empty> dropdown menu
4. Right-click on the newly created material and click "Save"
5. Save it in the "blade01" folder, with the name "blade01.material"
6. Double-click on the "blade01.material" file that you just saved, to open it on the Inspector
7. Search for a pbr property (For example: Metallic)
8. Assign the corresponding texture to the property's texture slot (Following the example above, assign the blade01_metallic.png to the Metallic texture slot)
9. Attempt to search for another property name on the material property search bar (For example: Roughness)
10. The editor will crash

I also recorded a demonstration of the crash, to be as thorough as possible: 

https://user-images.githubusercontent.com/37886706/206911216-4371bb8e-c0cf-44ff-82ad-43efdca008fd.mp4

### Minimal reproduction project

[crash_reprod_project.zip](https://github.com/godotengine/godot/files/10202470/crash_reprod_project.zip)

**Comment by reduz** [comment]
I tried but I can't reproduce this, anyone else can give it a try?

**Comment by KoBeWi** [comment]
Also can't reproduce.
