### ISSUE TITLE
LSP significantly slows down when browsing code completion suggestions

### ISSUE THREAD

**Issue by JoannesJ** [godotengine/godot#69914]
### Godot version

v4.0.beta7.official [0bb1e89fb]

### System information

Ubuntu 22.10

### Issue description

Browsing LSP code completions almost grinds LSP to a halt.

### Steps to reproduce

Open any script where a good amount of completion suggestions are available.
Trigger code completion and browse the items by holding down the down key on your keyboard for maybe 5 seconds.
Remove any code you just produced returning the script to a valid state.
Notice how there are still errors/warnings given as if the code you used for completion is still in the document.
Try to trigger code completions again and notice there is no reaction, LSP seems to be busy.

Tested with nvim's LSP and vscode.

Testing with my nvim setup it sometimes seems like the LSP is parsing every selected suggestion as if they where inserted into the document. As I will see the the errors flash by one by one for the suggestions. This might be because of a ghost text feature I have enabled. Not sure yet, because I've not been able to replicate this specific aspect.

### Minimal reproduction project

N/A

**Comment by DragonAxe** [comment]
I can reproduce in Godot: v4.0.2.stable.official [7a0977ce2].

I did some packet analysis using Wireshark and found that every time a new item is selected in the auto-complete box, a `completionItem/resolve` request is sent to LSP to fetch documentation/parameter info for that object. When holding the down arrow in the auto-complete box for 5 seconds, hundreds of `completionItem/resolve` requests are sent to LSP for each item briefly selected. `completionItem/resolve` requests must take a non-trivial amount of time thus LSP gets bogged down resolving all the requests.

Here is an excerpt of the JSON RPC messages between Godot and VSCode for the following actions:
- `ctrl+space` on a new line in any script's `_ready()` function.
```json
{
    "jsonrpc": "2.0",
    "id": 288,
    "method": "textDocument/completion",
    "params": {
        "textDocument": {
            "uri": "file:///{...}/godot_project/client_world.gd"
        },
        "position": {
            "line": 5,
            "character": 4
        },
        "context": {
            "triggerKind": 1
        }
    }
}
```
- Auto complete appears with the suggestions.
```json
{
    "id": 288,
    "jsonrpc": "2.0",
    "result": [
        {
            "data": "AESContext::MODE_ECB_ENCRYPT",
            "insertText": "",
            "kind": 21,
            "label": "MODE_ECB_ENCRYPT"
        },
        {...}
    ]
}
```
- First item in auto-complete box is selected by default.
```json
{
    "jsonrpc": "2.0",
    "id": 289,
    "method": "completionItem/resolve",
    "params": {
        "label": "__data__",
        "insertTextFormat": 1,
        "kind": 10,
        "data": "PackedDataContainer::__data__"
    }
}
```
- Documentation appears for first item.
```json
{
    "id": 289,
    "jsonrpc": "2.0",
    "result": {
        "command": {
            "command": "",
            "title": ""
        },
        "data": "PackedDataContainer::__data__",
        "deprecated": false,
        "detail": "",
        "documentation": {
            "kind": "markdown",
            "value": "\tvar PackedDataContainer.__data__: PackedByteArray\n\n\n\n"
        },
        "filterText": "",
        "insertText": "",
        "kind": 10,
        "label": "__data__",
        "preselect": false,
        "sortText": ""
    }
}
```
- `Down` key pressed to select next item.
```json
{
    "jsonrpc": "2.0",
    "id": 290,
    "method": "completionItem/resolve",
    "params": {
        "label": "_add_constant_central_force",
        "insertTextFormat": 1,
        "kind": 2,
        "data": "PhysicsDirectBodyState2DExtension::_add_constant_central_force"
    }
}
```
- Documentation appears for second item.
```json
{
    "id": 290,
    "jsonrpc": "2.0",
    "result": {
        "command": {
            "command": "",
            "title": ""
        },
        "data": "PhysicsDirectBodyState2DExtension::_add_constant_central_force",
        "deprecated": false,
        "detail": "",
        "documentation": {
            "kind": "markdown",
            "value": "\tfunc PhysicsDirectBodyState2DExtension._add_constant_central_force(force: Vector2) -> void\n\n\n\n"
        },
        "filterText": "",
        "insertText": "",
        "kind": 2,
        "label": "_add_constant_central_force",
        "preselect": false,
        "sortText": ""
    }
}
```
- Repeat `Down` key pressed and LSP will bog down...

**Comment by DragonAxe** [comment]
Turning on "Use Threads" in:
- Editor Settings
- Network
- Language Server
- Use Threads :heavy_check_mark: 
...seems to speed up auto-complete processing which helps, but it's still noticeable.

**Comment by akien-mga** [comment]
#89284 might fix this, could one of you test it to confirm?

**Comment by akien-mga** [comment]
Assuming fixed by #89284. Please let us know if it isn't the case.

**Comment by JoannesJ** [comment]
Yeah, confirmed fixed!

**Comment by Arrow-x** [comment]
on Godot 4.3 rc 2 arch-linux (from the offical builds)
It is still very slow on big projects though, on small scripts it works well, but on my main projects it takes a minut to get going when it does it chugs so much that I have to reastart the whole project
