### ISSUE TITLE
GDScript 2.0: Cannot assign external inner class as a constant

### ISSUE THREAD

**Issue by adamscott** [godotengine/godot#69917]
### Godot version

4.0.dev (05097de)

### System information

Linux (Ubuntu 22.04), Vulkan, Radeon RX Vega 64 (eGPU)

### Issue description

It's a regression that was introduced very recently. Using `git bisect`, it seems that the regression comes from #69907.

We cannot assign inner classes as constants.

```gdscript
# test.gd
extends Node

const Lambda: = preload("res://lambda.gd")
const InnerClass: = Lambda.InnerClass  # the script error is thrown here

func _ready() -> void:
	var inst: InnerClass = InnerClass.new()
```

```
SCRIPT ERROR: Parse Error: Initializer for a constant must be a constant expression.
          at: GDScript::reload (res://test.gd:4)
```
Inner classes should be assignable to constants.

### Steps to reproduce

1. Open the MRP
2. Open `test.gd`
3. Note the error

### Minimal reproduction project

[innerclass_constant.zip](https://github.com/godotengine/godot/files/10202773/innerclass_constant.zip)

**Comment by adamscott** [comment]
CC @rune-scape

**Comment by rune-scape** [comment]
this is related to https://github.com/godotengine/godot/issues/61636
https://github.com/godotengine/godot/pull/69907 uses the analyzer to fetch values from preloaded scripts, which will not make a constant class, and then tries to initialize the const with that
but my attempt to just make classes constant broke the compiler :/

**Comment by anvilfolk** [comment]
It's probably something to do with `is_meta_type` alongside `is_constant`, right? Presumably, a class _type_ will be both a meta type as well as const. A variable of a class instance will be neither?

**Comment by adamscott** [comment]
I wonder how `Lambda` is a constant, but not `Lambda.InnerClass`. I'm not at my computer right now, but I think it may be interesting to compare both values. I'll try to work on this later.

**Comment by rune-scape** [comment]
there's actually 2 different `is_constant`s 1. on DataType and 1 on ExpressionNode, 😵 
the ExpressionNode one is the problem (in `reduce_identifier` and `reduce_identifier_from_base`)
Lambda is const because `preload` actually calls `reduced_value = get_shallow_script()`, which needs to be set if `ExpressionNode::is_constant` is true

**Comment by adamscott** [comment]
@rune-scape If we could make `get_shallow_script()` work with inner classes, could it work? Like, create a shallow script of a inner class that could be used afterwards?

**Comment by rune-scape** [comment]
i was working on exactly that a couple weeks ago, i even [got it passing](https://github.com/rune-scape/godot/tree/rune-inner-class-resource-path), so i might try with that and see if the dependencies work out :), but my focus is on out of order resolution and stringname dict keys right now
