### ISSUE TITLE
Opening a project containing compute shaders, or adding them while open, can freeze Godot

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#69919]
### Godot version

Godot 4 beta8 (and some preceding betas I dont recall)

### System information

Windows 10 64 bits NVIDIA GeForce GTX 1060

### Issue description

The editor opens, a GLSL file starts importing, then immediately a popup shows up, either completely black or white, blocking the editor. The popup stays that way, meaning the whole editor is stuck and I have to kill it.
It happened to me 3 times at this point in various beta versions.
The shaders likely have errors in them, but that should not make Godot freeze like that.

EDIT: happened again as I was trying to workaround it. I removed shaders from the project, the project opened, then I moved the files back in the project, but Godot went stuck the same way while importing them.

I also tried commenting out the code in the `main` function, which this time did not show a popup, but Godot still froze anyways.

![image](https://user-images.githubusercontent.com/1311555/206919593-32260d6a-a9b2-431f-8e70-87543f8a6bad.png)

I eventually found out a workaround that SEEMS to work:
I commented out the contents of every shader, except `#[compute]` and `#version 450`, and added a placeholder `void main() {}` just so it doesnt complain. Finally Godot opened fine, then I removed the placeholder and uncommented the rest of the code, and only then, Godot properly opened the error popup without freezing.

### Steps to reproduce

Unfortunately I tried reproducing this a few times but it's not happening 100% of the time. But every time it happened, the following conditions were met:

- I was opening the project, it wasn't already open. Although I also had the same thing happen with an open project, if I add shader files to the project and focus back Godot.
- The project had GLSL compute shader(s) that had errors in them. Syntax, or other.
- Those GLSL shaders were either brand new since the last time the project opened, or were imported before but have been modified while the project was closed.
- This one might not matter, but my environment is such that Godot's internal shader cache gets recompiled often, since I'm often switching between versions (although I always opened my project with increasing beta versions).

### Minimal reproduction project

Last time it happened, I started my computer and opened this project for the first time in the day, and the faulty shaders were brand new files. The project itself had been opened in the past and already had valid imported shaders, but the new ones were added while the project was not open.

[shaders_copy.zip](https://github.com/godotengine/godot/files/10202822/shaders_copy.zip)

It might not reproduce for you though, as I mentionned it's not 100%.

**Comment by clayjohn** [comment]
I have a feeling this is connected to the freeze we get when the built-in shaders contain compile errors.

**Comment by akien-mga** [comment]
> I have a feeling this is connected to the freeze we get when the built-in shaders contain compile errors.

For the record, these seem to happen on Windows but not on Linux, where it happily spams errors. Not sure if the Windows freeze (some report a crash) comes from spamming I/O too much, or actual GPU drivers giving up.

**Comment by Zylann** [comment]
Got once again a similar problem in beta10, except a lot earlier, during splash screen:
![image](https://user-images.githubusercontent.com/1311555/209866835-a571052b-08c0-4650-b680-08464eed0a3e.png)

I dont recall adding compute shaders this time, only a `.gdshader`.

**Comment by capnm** [comment]
Just tried Linux with single window disabled ...
![grafik](https://user-images.githubusercontent.com/4047289/231241994-38227277-cef4-4e74-a591-1fd1b933832b.png)
