### ISSUE TITLE
Autocomplete incorrectly suggests non-static members for custom classes

### ISSUE THREAD

**Issue by Haydoggo** [godotengine/godot#69928]
### Godot version

v4.0.beta8.official [45cac42c0]

### System information

Windows 10

### Issue description

Autocomplete will suggest non-static members that belong to a custom class. Selecting one of these will result in invalid code.

Expected:
![image](https://user-images.githubusercontent.com/14885846/206926179-e15b5663-11f1-4939-93e7-75ffa9954de2.png)

Observed:
![image](https://user-images.githubusercontent.com/14885846/206925858-b648fb0a-9c99-40f5-af22-a92b37818f31.png)

### Steps to reproduce

1. Add script `custom_class.gd`
```gdscript
class_name CustomClass extends Node
```
2. Add script `main.gd`
```gdscript
extends Node

func _ready():
	CustomClass.
```
3. Non static members are suggested by autocomplete

### Minimal reproduction project

N/A

**Comment by adamscott** [comment]
CC @poohcom1

**Comment by Haydoggo** [comment]
Also something I just noticed (Also visible in the "Expected" screenshot) is that signals (which are not static) are suggested for both native and custom classes.
![image](https://user-images.githubusercontent.com/14885846/207158740-ddfc3069-404e-4351-abc1-8495979fb8eb.png)
![image](https://user-images.githubusercontent.com/14885846/207158785-8286dee3-c0c6-44b8-965a-98044a0bdf49.png)

Notice the editor does not recognise the following snippet as incorrect:
![image](https://user-images.githubusercontent.com/14885846/207158966-f6dced08-70c8-4c91-8802-f0c7db646c11.png)
