### ISSUE TITLE
No export template found at the expected path

### ISSUE THREAD

**Issue by barrrettt** [godotengine/godot#69921]
### Godot version

4.0 beta (mono) 

### System information

win11 x64

### Issue description

When update proyect from beta7. 

![image](https://user-images.githubusercontent.com/47840319/206920878-e3429b98-11fe-4cf8-b085-e960abef7984.png)

verything seems fine

![image](https://user-images.githubusercontent.com/47840319/206921232-f9fe9c11-868a-4d9c-9ef4-2ec2a5f7de34.png)

I tried to download the templates again but it keeps giving errors.

### Steps to reproduce

create new proyect. add windows template (for example) and errors appear. 

### Minimal reproduction project

null

**Comment by KoBeWi** [comment]
> I tried to download the templates again but it keeps giving errors.

Did you downloading the *editor* again? AFAIK beta8 had a bug at first, which was later fixed.

**Comment by barrrettt** [comment]
confirmed. working well. good job
