### ISSUE TITLE
Crash when reparenting an Animation Tree

### ISSUE THREAD

**Issue by All-StarsPixel** [godotengine/godot#69935]
### Godot version

4.0-beta6_win64

### System information

Windows 10

### Issue description

I was making animations when I realised that the tree and player should be children of the characterbody2D and not the sprite node. Reparenting the player was fine but when I try to reparent the tree Godot crashes.

### Steps to reproduce

Make a quick characerbody2D and attach a sprite node. make a child animation player and animation tree. make some animations then reparent the characterbody2D with the animation tree. Godot will load for 1 second, then crash.

### Minimal reproduction project

![icon](https://user-images.githubusercontent.com/116387385/206930766-61cba22d-5e05-48b6-bc25-d317c51b295c.svg)

yes i'm trying to make Undertale.

**Comment by jcarlosrc** [comment]
I can confirm. First click on the AnimationTree node to open it, then try to reparent. It leads to crashes in some cases.
