### ISSUE TITLE
Vulkan: SpotLight3D affects lighting outside of the cone

### ISSUE THREAD

**Issue by Syntaxxor** [godotengine/godot#69936]
### Godot version

4.0.beta8

### System information

Windows 10, Vulkan, Nvidia RTX 3060 ti, driver version 527.56

### Issue description

Spot lights have a strange ring around them, which seems to vary depending on distance and angle. It can be light or dark as well, seemingly at random.
![image](https://user-images.githubusercontent.com/25652538/206939376-73cea6ce-fd2c-472f-8e94-d06f4a1be5f4.png)

This is in the Mobile renderer. The Forward+ renderer has a similar issue, but it's localized only to the clusters that contain the spot light cone.
When trying to reproduce in the OpenGL renderer, I just got errors.

### Steps to reproduce

Add a spot light to a dark scene (set ambient light to low, but not black.)
Set size to somewhere around 35 degrees for best results.
Full ring is more visible in mobile renderer.

### Minimal reproduction project

[SpotLightError.zip](https://github.com/godotengine/godot/files/10203733/SpotLightError.zip)

**Comment by Calinou** [comment]
> When trying to reproduce in the OpenGL renderer, I just got errors.

See https://github.com/godotengine/godot/issues/69886.

**Comment by clayjohn** [comment]
I can't reproduce this issue on PopOS with intel integrated graphics. I will try the MRP on an NVidia device to see if I can reproduce it there
