### ISSUE TITLE
Material Shader Parameters displayed in forced alphabetical order in Inspector

### ISSUE THREAD

**Issue by fracteed** [godotengine/godot#69949]
### Godot version

4.0 beta 8

### System information

Windows 10 960m

### Issue description

I have noticed when porting a project from 3.5 to 4.0 that shader parameters are now displayed in forced alphabetical order in the inspector. This was not the case in 3.5, where the inspector lists them in the order that they are in the shader script.

When you have a long list of parameters in a custom shader it is normal to want to group them in a logical order for material editing. This is an example of one of my shaders that has 50 or so parameters. As can be see, they are in forced alphabetical order which makes it very hard to edit as they are not grouped in a logical manner. I would tend to put all my maps first, for instance. This forces me to scroll constantly to find what I need to edit.  I do not want to have to rename parameters just to get them in a certain listed order!

![parameter_order](https://user-images.githubusercontent.com/7741669/207014662-866ee139-d5b4-4d42-a7ff-a793567aef91.jpg)

For the example attached project file this is what it looks like in 4.0 beta 8:

![parameter_order_g4](https://user-images.githubusercontent.com/7741669/207015217-76336377-f60d-4850-ab28-624035e6022d.jpg)

and the same shader file in 3.5, which shows it in the correct order:

![parameter_order_g3](https://user-images.githubusercontent.com/7741669/207015400-ccef1e96-f9db-4631-9988-d5cbb7b24f09.jpg)

### Steps to reproduce

- Create a new shader material
- Add some uniform parameters
- Look at the inspector to see they have been displayed in alphabetical order

### Minimal reproduction project

[shader_parameter_oder.zip](https://github.com/godotengine/godot/files/10206756/shader_parameter_oder.zip)

**Comment by clayjohn** [comment]
Looks like the alphabetical sorting was added in https://github.com/godotengine/godot/pull/62972 at the same time as uniform groups/subgroups. For shaders with a large number of uniforms I think the intended usage is to organize them into groups as appropriate This gives you control over the organization and lets you fold sections as needed. 

Perhaps @Chaosus can chime in as I am unsure why the alphabetical sorting was added within groups

**Comment by fracteed** [comment]
@clayjohn thanks for looking at this issue. I did not know about the grouping feature, which does look useful, but the forced order is still a bad idea.

I could see in that commit that @akien-mga says the same thing:
>  I noticed that within a group the uniforms are listed alphabetically, is that intended? In GDScript exports are listed in the order they're defined in the script, which allows to give them a meaningful order 

I can't understand the technical reason that chaosus gave for this though.

@Chaosus can we please have this as an option rather than as default?

**Comment by Chaosus** [comment]
I need to remember, that part of code I have edited a while ago. I will try to fix it, of course.

**Comment by fracteed** [comment]
@Chaosus  I appreciate you looking into this. Btw, you have done some amazing work on some of the new shader features!
