### ISSUE TITLE
Autocomplete does not suggest custom class names

### ISSUE THREAD

**Issue by Haydoggo** [godotengine/godot#69941]
### Godot version

v4.0.beta8.official [45cac42c0]

### System information

Windows 10

### Issue description

Autocomplete will no longer complete custom class names defined with `class_name`.

Godot 3.5.1
![image](https://user-images.githubusercontent.com/14885846/206967061-a00bce29-52e3-4d5f-9c92-4f318051e833.png)

Godot 4.0 beta8
![image](https://user-images.githubusercontent.com/14885846/206967345-c5b3ea59-4c06-4af0-a46d-7edf7e4e52e8.png)

### Steps to reproduce

1. Create `custom_class.gd`
```gdscript
class_name CustomClass extends Node
```

2. Create `main.gd`
```gdscript
extends Node

func _ready():
	Custo
```

### Minimal reproduction project

N/A

**Comment by adamscott** [comment]
CC @poohcom1

**Comment by atirut-w** [comment]
This seems to also be happening in Beta 12. Do I open a new issue or...?

**Comment by adamscott** [comment]
@atirut-w No. The issue is known. A pull request already exists that may fix this issue.

**Comment by atirut-w** [comment]
Sorry I misread the version.

**Comment by adamscott** [comment]
@atirut-w You can comment to say that the issue still occurs. But you don't have to open a new issue, as this one is already open.
