### ISSUE TITLE
Half of the screen can't be seen while debugging in 4K (3840 x 2160) resolution

### ISSUE THREAD

**Issue by buniart** [godotengine/godot#69967]
### Godot version

v3.5.1.stable.official [6fed1ffa3]

### System information

Windows 7

### Issue description

Context: 

I posted on reddit here about my artwork looking terrible in my game, looking for a better way to import them so they wouldn't look so pixelated (my art wasn't pixel art). I was instructed that my art style was prone to looking bad when resized, and a suggestion was to use a style with much thicker lines as well as increasing the resolution of the game (from 1920 by 1080 to 3840 by 2160).

The problem itself:

So I tried that, and it turns out I really like how my new artwork looks like. The problem is, like I stated in the title, when I test the game in the higher resolution, half the screen is black. I tried testing on different screens, one 1080p, the other 720p and the problem happens in both.

I have tried a lot of things to make this worse. I played with Stretch (Mode, Aspect - but not Shrink), I tried different test widths and heights, I tried toggling resizable, borderless, full screen all on and off.

Another thing I did was play with the Window Placement options in the Editor Settings, but even starting a new project with no modifications, the problem still persisted. I am sharing screenshots of the Editor Settings in the main project, anyways.

Lastly, I use a texture in a TextureRect as the background of my levels. I figured maybe that was the problem, so I changed the margin and rect sizes there, too, but it didn't help. I tried making a brand new level, not inheriting from the LevelMother scene, too - Nothing, I still have half of the screen black.

I was instructed to report a bug here, so that is what I am doing. 

### Steps to reproduce

Settings screenshots:

https://ibb.co/4sX2SWs
https://ibb.co/yVtgXk1
https://ibb.co/CBMg33f
https://ibb.co/VLytqf2
https://ibb.co/6HQ79hv

Code screenshots:

https://ibb.co/7JbhqY7
https://ibb.co/9sZtVHM
https://ibb.co/PsySBVS
https://ibb.co/gDxZX5T
https://ibb.co/tMmpPMc
https://ibb.co/nPQVkhc
https://ibb.co/v1JZFTY
https://ibb.co/1XNxS0g
https://ibb.co/bPKJgmF

### Minimal reproduction project

I don't know how.

**Comment by Calinou** [comment]
The issue is likely the Test Width and Test Height not playing along with the Fullscreen setting. Try enabling one or the other, not both at the same time.

**Comment by Calinou** [comment]
@buniart Bump :slightly_smiling_face: 

> Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot. (You can remove the art assets, but the project must be able to run on its own and exhibit the bug.)

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.

PS: Since no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
