### ISSUE TITLE
Crash when checking options in Project Settings

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#6996]
**Operating system or device - Godot version:** Ubuntu 16.10, Clang 3.8.1 - Godot Git, compiled from commit https://github.com/godotengine/godot/commit/681575fa7123592897090c6cce44402c4e45baeb

**Issue description** (what happened, and what was expected):

Godot will crash when checking options in the Project Settings. It occasionally happens, not 100% of the time.

**Steps to reproduce:** Check some options in the Project Settings, eventually it will crash. GDB reports this as "exiting normally" though, so it doesn't seem to be possible to get a backtrace.

**Comment by timoschwarzer** [comment]
It happens for specific keys when this key is not present in engine.cfg and you change it's value.
The value *is not* being saved to engine.cfg.

One example I found is Rasterizer.android > fp16_framebuffer:

When clicking "On", it...
```
[ ] fp16_framebuffer [ ] On > crashes
[X] fp16_framebuffer [ ] On > doesn't crash
[X] fp16_framebuffer [X] On > doesn't crash
```

And it only occurs on checkboxes, which are not yet stored in the engine.cfg.

**Comment by vnen** [comment]
Cannot reproduce this on Windows.

**Comment by Calinou** [comment]
Seems to be fixed for now, closing. Reopen if this happens again in the Git master branch.
