### ISSUE TITLE
TabsConainer scroll buttons are drawn outside of control

### ISSUE THREAD

**Issue by TeddyDD** [godotengine/godot#6997]
**Operating system or device - Godot version:**
2.1 stable official from Steam - Linux Arch 64bit

**Issue description** (what happened, and what was expected):
Godot editor draws two little buttons with arrows so you can scroll tabs when you open too much scenes 
![1][1]

I tried to create similar setup but it seems that buttons are drawn outside of the TabsConainer.
![2][2]
![3][3]

**Steps to reproduce:**
My scene setup looks like this:

![4][4]

**Link to minimal example project** (optional but very welcome):
There is my [scene](https://gist.github.com/TeddyDD/ef03edbc64c103c98935a1e5c7b30b8c)

  [1]: https://i.imgur.com/420Cb0c.png
  [2]: http://i.imgur.com/zXRQrM5.png
  [3]: http://i.imgur.com/ntADtum.png
  [4]: http://i.imgur.com/DgMGwQB.png

**Comment by Qualitymix** [comment]
This affects me as well.

**Comment by RayKoopa** [comment]
I fixed it in https://github.com/godotengine/godot/pull/7600 but nobody wants to merge :D
