### ISSUE TITLE
Changing the size of panels (such as scene, file system, inspector, or output/debugger) crashes the engine.

### ISSUE THREAD

**Issue by LeonStansfield** [godotengine/godot#69984]
### Godot version

4.0 beta 8

### System information

Windows 11, foreward+ renderer, Dell XPS 13 Plus (integrated graphics), 12th Gen Intel(R) Core(TM) i7-1280P, 1800 Mhz, 14 Core(s), 20 Logical Processor(s)

### Issue description

Changing the size of the panels (such as scene, file system, inspector or output/debugger) causes the engine to not respond, eventually crashing the engine.
This happens around 50% of the time I adjust the size of these panels.
I have no other devices to test this on.

### Steps to reproduce

Open the project, and adjust the side panels a few times. Usually, between the 1st and 4th time adjusting them, the engine will stop responding.

### Minimal reproduction project

[Bug report.zip](https://github.com/godotengine/godot/files/10212017/Bug.report.zip)

**Comment by KoBeWi** [comment]
@LeonStansfield Can you still reproduce this in rc3?

**Comment by KoBeWi** [comment]
Closing. Comment if you can still reproduce.
