### ISSUE TITLE
Access to cumulative processing time and fixed processing time from GDScript

### ISSUE THREAD

**Issue by FeldrinH** [godotengine/godot#6999]
Would it be possible to add functions that return "processing" time and "fixed processing" time, which would return the value you would get (in principle, ignoring precision issues) if you added processing or fixed processing deltas to some accumulator every frame. A sort of "engine" time, affected by things like pausing, as opposed to "real" time.  
This would be useful for instance to keep track of cooldowns without active processing, by simply storing the time the cooldown would end in a variable and then comparing that to the current processing time.  
I would guess the engine keeps track of it anyway, so it shouldn't be too hard to simply expose it to GDScript.

**Comment by Zylann** [comment]
It's obvious that a singleton with process() could solve that easily. It's ok if the engine can provide it already, but the pause mode makes it a bit more difficult than it sounds because it implies that the nodes being pausable are always the same ones.

**Comment by eon-s** [comment]
Or fixed frame counter, I can see it useful for syncing.
Then if want to pause, the pause method can register frame number of pause and un-pause if needed.

**Comment by RodeoMcCabe** [comment]
You could just use OS.get_ticks_msec() and a couple of variables in a "Pause" singleton for that.

**Comment by bojidar-bg** [comment]
@RodeoMcCabe That's more complex than what @Zylann proposed, compare:

```gdscript
# Singleton that increments time
var time = 0
func _ready():
    set_process(true)
func _process(delta):
    time += delta
```
```gdscript
# Singleton that works with get_ticks_msec
var paused_time = 0
func _ready():
    set_process(true)
func _process(delta):
    if get_tree().is_paused():
        paused_time += delta
func get_time():
    return OS.get_ticks_msec() / 1000.0 - paused_time
```

**Comment by reduz** [comment]
Just call get_process_time() and get_process_fixed_time()

**Comment by bojidar-bg** [comment]
@reduz This PR asks for people to be able to use some function to get **cumulative** process/fixed_process time, and not **delta** time. So, just like you add up all `_fixed_process` deltas so far.

(PS. They are actually called `get_process_delta_time`  and `get_process_fixed_delta_time`)

**Comment by RodeoMcCabe** [comment]
@bojidar-bg Sorry, I was responding to eon-s. Something like this (actually you don't need get_ticks_msec if you're just looking for a frame counter):

    # Singleton with pause mode set to process (so this singleton is never paused)
    var paused_frame = 0
    var unpaused_frame = 0
    var total_frames = 0
    var run_time = 0

    func _ready():
        set_process(true)

    func _process(delta):
        total_frames += 1
        if not get_tree().is_paused():
            run_time += delta

    func pause():
        get_tree().set_paused(true) # can't remember exactly how to pause the tree
        paused_frame = total_frames

    func unpause():
        get_tree().set_paused(false)
        unpaused_frame = total frames

**Comment by groud** [comment]
Reopening as reverted by https://github.com/godotengine/godot/pull/51979

**Comment by aaronfranke** [comment]
Shouldn't this just be closed? @reduz already rejected the feature, and I agree with him - it's very easy to just do this in a script.

**Comment by eon-s** [comment]
Apart of syncing this may be probably useful for some deterministic systems (some core ones), but is a (very old) feature request and will need a proper proposal with use cases now, I guess...

**Comment by Calinou** [comment]
Closing per @aaronfranke's comment.
