### ISSUE TITLE
mouse_entered() stop working when in a full rect parent and fullscreen

### ISSUE THREAD

**Issue by Kotzwinkle** [godotengine/godot#69997]
### Godot version

v4.0.beta8.official [45cac42c0]

### System information

Windows 10, RTX 3060TI

### Issue description

This one is a bit odd, but I found that under certain conditions, the mouse_entered() event stop triggering and hover theme styles no long apply.

Basically, with a project set to full screen, if you launch a form scene with a button in a full rect control container, then mouse_entered() event will stop triggering if you "leave" the screen left, right, bottom, left.

I've attached a sample project, but can provide a screen recording as well.

### Steps to reproduce

1. Create a new project
2. Set the Project Setting viewport to 960x540
3. Set Stretch Mode to "viewport"
4. Set Aspect to "keep"
5. Create a new User Interface scene
6. Set the root Control node to Full Rect
7. Add a VBox Container
8. Add a Button to vBox
9. Launch the application
10. As long as the mouse does not leave the window, the button mouse_entered() event and hover styles work normally
11. **Touch any or all 4 sides of the screen with the cursor: up, down(offscreen), left(offscreen), right
12. Move the mouse over the buttons: mouse entered does not fire and hover styles are not applied

**This step can be somewhat inconsistent, but I'm generally able to reproduce it with enough effort

### Minimal reproduction project

[hover_test.zip](https://github.com/godotengine/godot/files/10213968/hover_test.zip)

**Comment by piyushmulatkar** [comment]
Unable to recreate on windows 11.  Can you provide more details about step 11?

**Comment by Kotzwinkle** [comment]
Yeah, here's a link to a demo: [demo](https://imgur.com/a/yo6spM7) 
I apologize for the phone recording, but I couldn't get regular screen cap sofware to work.

**Comment by Kotzwinkle** [comment]
Sorry, I also noticed that it only occurs with a two monitor setup. 
I never click off the window or do anything that would make it lose focus.
Also, click events seem to work just fine.

**Comment by takhimi** [comment]
Hi. For my prototype game, Godot 4 Mono Beta 17, also have this problem. Mouse entered sometimes will not get triggered however my clicked event is working just fine.

**Comment by KoBeWi** [comment]
Can't reproduce in rc5.
@Kotzwinkle Is this still an issue?

**Comment by Kotzwinkle** [comment]
@KoBeWi 

I can't speak for @takhimi, but for myself, as of 4.0.rc3, it appears to no longer be an issue
