### ISSUE TITLE
Recording with a mic stops working after changing scenes

### ISSUE THREAD

**Issue by ababen1** [godotengine/godot#70008]
### Godot version

v4.0.beta.custom_build [f692b4768]

### System information

Linux (specifically linux mint 21)

### Issue description

Recording with a microphone using AudioEffectRecord stops working after changing scenes

### Steps to reproduce

Download the reproduction project, it's identical to the audio recording demo from the godot repository, but I added an option to change scene when pressing Home. Recording works as expected at first, but after you press Home, the resulting audio is silence. 

1. Download the audio recording demo from here https://github.com/godotengine/godot-demo-projects/tree/4.0-dev/audio/mic_record
2. Add this code:
```
func _unhandled_input(event):
	if event.is_action_pressed("ui_home"):
		get_tree().change_scene_to_file("res://MicRecord.tscn")
		print("Scene changed")
```
3. Run the project. You might get errors on `_on_FormatOptionButton_item_selected`, You need to change `AudioStreamSample` to `AudioStream` in that function

4. Press "record
5.  Say something
6.   Press "Stop"
7. Press "Play" to listen to what you just recorded
8. Press Home to reload the scene
9. Repeat steps 4-7. The new recording is silent 

### Minimal reproduction project

[mic_record.zip](https://github.com/godotengine/godot/files/10215805/mic_record.zip)

**Comment by timothyqiu** [comment]
I can't reproduce this issue.

After reloading the scene, the default "Record" button is effectively the "Stop" button. Clicking "Record" stops the recording. And "Save WAV to" / "Play" buttons works fine for me.

BTW, your minimal reproduction project failed to upload. So I just followed your steps and modified the original demo.

**Comment by ababen1** [comment]
> I can't reproduce this issue.
> 
> After reloading the scene, the default "Record" button is effectively the "Stop" button. Clicking "Record" stops the recording. And "Save WAV to" / "Play" buttons works fine for me.
> 
> BTW, your minimal reproduction project failed to upload. So I just followed your steps and modified the original demo.

Hmm, the button doesn't change to "Stop" for me. I didn't mean you should try changing scenes while recording, but after you finished. alternatively you can just change scene right at the start and see that it returns silence.  
I tried attaching the project to this comment, hopefully it will upload 
[mic_record.zip](https://github.com/godotengine/godot/files/10215805/mic_record.zip)

**Comment by ababen1** [comment]
Yeah that's what I meant except you don't have to save it to wav, you can just press "listen" to hear it
And i'm not sure I understand what's wrong here? I'm not trying to access the previous recording after changing scenes, I'm trying to make a new recording and playing it back, which returns silence

**Comment by timothyqiu** [comment]
The problem is that the demo is not designed to be used / changed like that. It's not an engine error.

In the doc for [AudioEffectRecord.set_recording_active()](https://docs.godotengine.org/en/latest/classes/class_audioeffectrecord.html#class-audioeffectrecord-method-set-recording-active)

> If true, the sound will be recorded. Note that restarting the recording will remove the previously recorded sample.

Since pressing Play calls `set_recording_active(true)`, it means that the previous recording will be removed by AudioEffectRecord.

You should change the demo further if you want it to work after changing scene. For example, in `_ready()`, you can obtain the recoding with `get_recording()` and enable the Listen button.

**Comment by ababen1** [comment]
> The problem is that the demo is not designed to be used / changed like that. It's not an engine error.
> 
> In the doc for [AudioEffectRecord.set_recording_active()](https://docs.godotengine.org/en/latest/classes/class_audioeffectrecord.html#class-audioeffectrecord-method-set-recording-active)
> 
> > If true, the sound will be recorded. Note that restarting the recording will remove the previously recorded sample.
> 
> Since pressing Play calls `set_recording_active(true)`, it means that the previous recording will be removed by AudioEffectRecord.
> 
> You should change the demo further if you want it to work after changing scene. For example, in `_ready()`, you can obtain the recoding with `get_recording()` and enable the Listen button.

But again, I don't want the previous recording. I want to record something new after changing scene and then listen to my new recording. So I don't understand why wouldn't it work?

**Comment by timothyqiu** [comment]
Ah, sorry for my misunderstanding.

However, I can obtain the new recoding after pressing Home with your MRP. So probably still needs testing.

**Comment by ababen1** [comment]
I updated the issue, hopefully it is more clear now. also fixed the download link

**Comment by ababen1** [comment]
> Ah, sorry for my misunderstanding.
> 
> However, I can obtain the new recoding after pressing Home with your MRP. So probably still needs testing.

What OS are you using? I just tried it on my windows computer and it works. But the bug persists on my linux computer

**Comment by ababen1** [comment]
seems to be working now
