### ISSUE TITLE
Editor crash when click mesh instance 3d with shader material in 3D view.

### ISSUE THREAD

**Issue by AllenDang** [godotengine/godot#70001]
### Godot version

4.0 Beta 8

### System information

macOS v13.0

### Issue description

Editor crash when click mesh instance 3d with shader material in 3D view.

### Steps to reproduce

1. Create a mesh instance 3d, choose "Box" shape.
2. Create a ShaderMaterial with a new empty shader.
3. Click empty space to remove focus for the mesh instance 3d.
4. Click mesh instance 3d again.

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
I think this was fixed in the last couple of months. Can you still reproduce in RC3?

**Comment by AllenDang** [comment]
Yes, it is fixed.
