### ISSUE TITLE
Vulkan: Environment Fog: Severe sky shader-related instability when PanoramaSky is used

### ISSUE THREAD

**Issue by RandomCatDude** [godotengine/godot#70015]
### Godot version

v4.0.beta8.official [45cac42c0]

### System information

Manjaro Linux, Vulkan, RX 570 (Mesa 22.2.4)

### Issue description

Preface: This is a very strange problem, and I haven't been able to entirely pin down what causes it, I'm largely speculating and guessing from experimentation.

This all mainly occurs upon startup of the project -- once the scene is loaded, it settles into some state, until the next time the project is started.
The simple (non-volumetric) environment fog seems to exhibit severe problems when it is used in conjunction with PanoramaSky (or a shader that is very similar to it), and with visible ReflectionProbes in the scene upon startup.

I have experienced issues of varying severity,:
- Sections of sky being pitch black (probably NaN because they cause glow to be extremely bright)
   - This in turn affects ReflectionProbes, causing anything within them to become black/NaN too
- Severe performance hit when any fragment of the sky is visible (not obscured by the world)
- OS' compositor crashing and rendering the system unusable, forcing a reboot.

The last one is the worst by far, and is the main reason I've struggled to learn much about  

The pattern of occurrences of these bugs seems to be entirely random.
I have made attempts to tinker and try to pin down the exact conditions for causing the bug(s), but it is inconsistent and I haven't been really able to find much. It _seems_ like other sky materials besides PanoramaSky don't have any of these problems, but I'm not really sure.

I apologize for this issue's relatively poor quality and lack of sufficient info. I mainly just want to alert others to this issue, to see if others have experienced this too, or can replicate this on their systems. So that we can get more potential info on this.

### Steps to reproduce

1. Download MRP. Ensure you won't gonna lose anything important if your system crashes from running it
2. Run it. It has a simple FPS player controller for moving around the scene. WASD controls with mouselook. It is fullscreen so press ESC to pause and regain mouse control, Alt+F4 to exit at any moment
3. Observe the sky and see if anything is erroneously black-coloured, if having the sky in-view severely damages performance, and/or if your system's compositor/graphics crash.
4. Rerun the project if nothing happened, this is an inconsistent bug and may take multiple tries to get.

### Minimal reproduction project

I was unable to replicate it in a fresh project, so I trimmed down my FPS project (in which I ran into the issue) to the bare minimum needed to replicate it.
[Environment Fog+Sky Test.zip](https://github.com/godotengine/godot/files/10217296/Environment.Fog%2BSky.Test.zip)

**Comment by GTcreyon** [comment]
Process of reproduction:

First attempt, no adverse effects.

Second attempt, got stuck on a grey screen. Couldn't alt-f4. Mouse vanished completely, and was rendered unusable, even when alt-tabbing or switching workspaces. Had to restart PC.

Third attempt, project did not open in the editor at all. Just a grey screen. Godot log for that attempt is as follows:
```
ERROR: Condition "gvtype == RenderingServer::GLOBAL_VAR_TYPE_MAX" is true. Continuing.
   at: global_shader_parameters_load_settings (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2163)
WARNING: FBX file import is enabled in the project settings, but no FBX2glTF path is configured in the editor settings. FBX files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:99)
SCRIPT ERROR: Parse Error: Identifier "Directory" not declared in the current scope.
          at: GDScript::reload (res://common/AnimatedDecal.gd:11)
ERROR: Condition "gvtype == RenderingServer::GLOBAL_VAR_TYPE_MAX" is true. Continuing.
   at: global_shader_parameters_load_settings (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2163)
ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: swap_buffers (drivers/vulkan/vulkan_context.cpp:2299)
ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: swap_buffers (drivers/vulkan/vulkan_context.cpp:2299)
```
Godot would not close. Running `kill godot4` after this caused a system freeze for around 5 seconds, before the editor closed and system returned to normal.

Subsequent attempts were the same. Deleting the shader cache in the `.godot` folder allowed the project to open again.

Fourth attempt yielded the same results as the second attempt, although I realised that I could kill Godot from the terminal as described earlier using only the keyboard, so I didn't have to restart the PC.

Fifth yielded the same results as the third attempt. From this point onwards, I started deleting the shader cache after every run.

Sixth attempt, I disabled fog. The project ran perfectly with it disabled.

Seventh, I re-enabled fog, and it broke again. Same as attempt 2.

GPU: NVIDIA GTX 1060
CPU: AMD Ryzen 7 1800X
On Manjaro Linux with KDE

**Comment by marcinn** [comment]
I have similar issues with Volumetric Fog (v4.0.beta.custom_build [3c9bf4bc2]). From a time to time the fog is very bright and glowing or completely dark. This has happened before (on alpha or before alpha).

![Screenshot_20230114_142120](https://user-images.githubusercontent.com/139032/212502521-b7c07cd9-43a2-4080-85ba-e8ca02f3d724.png)

Expected result:
![Screenshot_20230114_142143](https://user-images.githubusercontent.com/139032/212502522-7fdd95bd-31f2-46aa-8b95-9f68cd6c2622.png)

----

Next thing is, that starting from Godot 4 Beta 12 I'm noticing frequent performance drops. A restart of the project is required, but also sometimes changing the window size (i.e. go to toggle fullscreen) is enough to bring back the performance. The editor remains open, but I'm always activating empty tab or script editor.

----

On this scene I'm getting 30-40fps typically. But today I've added a 4k exr panorama sky, and Godot almost freezed together with whole operating system. The stdout contains:

```
ERROR: 1 shaders of type VolumetricFogShaderRD were never freed
   at: ~ShaderRD (servers/rendering/renderer_rd/shader_rd.cpp:708)
ERROR: 1 RID allocations of type 'N10RendererRD15MaterialStorage6ShaderE' were leaked at exit.
```

Are these issues related to volumetric fog? Do you know these issues, or should I create new tickets and try to reproduce these issues with MRPs?

Thanks.

**Comment by clayjohn** [comment]
Running the MRP, this appears to be an issue with the ``sun_scatter`` property. Changing it to 0 makes the issue go away
