### ISSUE TITLE
It's still an old problem. There is a problem with the editor. It's very slow when there is more code

### ISSUE THREAD

**Issue by xiaoliang6669** [godotengine/godot#70017]
### Godot version

4.0-beta8

### System information

win10

### Issue description

![77777](https://user-images.githubusercontent.com/112788136/207357618-8798732a-3058-4e20-9374-9d426820e424.png)

### Steps to reproduce

![MWZX0DF~9FLS8VSZ5)FD6@H](https://user-images.githubusercontent.com/112788136/207357882-55b0a68a-3bae-4f7b-8e18-10a48381bbad.png)
This is also slow when there are many resource files

### Minimal reproduction project

The performance of this editor is terrible. That's just a lot of code. The card will no longer work

**Comment by Calinou** [comment]
@xiaoliang6669 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

As noted in other issues you've opened in the past, this issue will be kept closed until you upload a minimal reproduction project.
