### ISSUE TITLE
Unexpected light behavior (light gets cut off) affecting shaded Sprite3D

### ISSUE THREAD

**Issue by dark-elf1** [godotengine/godot#70018]
### Godot version

4.0 Beta 8

### System information

openSUSE Tumbleweed, AMD Radeon RX 550, Vulkan 1.3.224, Mesa 22.2.4

### Issue description

https://user-images.githubusercontent.com/110809639/207380252-9892ceb2-53cb-4142-94ef-29f63b26b551.mp4

As you can see in the video the light gets cut off and the sprite is not shaded correctly. Both of the lights (omni light and spot light) are set to a distance of 0.1 on Z axis from sprites. Tried with both forward_plus and mobile renderer, same result.

### Steps to reproduce

Put 2 Sprite3D on the scene and turn on shading for them. Also put omni light on one sprite and spot light on the other (rotate spot light). Set the distance of both lights to be 0.1 on Z axis from sprites.

### Minimal reproduction project

[reproduction_project.zip](https://github.com/godotengine/godot/files/10219998/reproduction_project.zip)

**Comment by Calinou** [comment]
Sprite3D normals are likely broken when the mesh is generated.
