### ISSUE TITLE
OpenGL: Screen tearing on some Android devices

### ISSUE THREAD

**Issue by Snowy-Fox** [godotengine/godot#70031]
### Godot version

4.0beta8 - 4.0RC2

### System information

Android 9, OpenGL 3, PowerVR GE8300

### Issue description

On certain Android devices, there is a persistent, obvious screen tearing issue. This tearing is unaffected by v-sync or scaling settings. The top third of the screen lags several frames behind the bottom two thirds.

At present, I've only observed the issue on a Retroid Pocket 2+ handheld (Android 9, PowerVR GE8300 GPU). I've also tested the same projects on a Huawei P10 Lite phone (Android 8, Mali-T830 GPU) but observed no issues there.

![photo_2022-12-13_15-45-20_detail](https://user-images.githubusercontent.com/6191653/207446565-970e997c-f7c3-49ae-a27a-7dd15be8cb57.jpg)

https://user-images.githubusercontent.com/6191653/207448582-a6df595f-2104-4275-804c-9b63ca51af4b.mp4

I will also note that I had this issue with 3.x, as well. In that case, I observed the screen tearing on both the Pocket 2+ and the P10 Lite, and I eventually resolved it by switching the graphics driver from GLES3 to GLES2.

### Steps to reproduce

- Create any project with moving graphics using gl_compatibility renderer
- Export Android APK with debug
- Install and run on affected device

Note that the issue only affects certain Android devices, and may require testing on multiple devices in order to narrow down the cause.

### Minimal reproduction project

Any project exported using OpenGL 3 will do, but here's the one I made to test it.
[Android Test 4.0b8.zip](https://github.com/godotengine/godot/files/10222314/Android.Test.4.0b8.zip)

**Comment by Snowy-Fox** [comment]
Just tested export from Godot 4.0beta9 - issue persists

**Comment by Snowy-Fox** [comment]
I just tested an export from Godot 4.0 RC 3, and as of this version, the screen tearing is no longer occurring on the Retroid Pocket 2+!

I re-tested on the Huawei P10 Lite, too, and the screen tearing is still no longer occurring on that, either.

This exhausts the Android devices I'm able to test on. Hopefully nobody else is still having the issue on their devices, either.

**Comment by aerze** [comment]
I'm still having this exact issue with the Retroid Pocket 2+ on v4.0.stable.official [92bee43ad]
I tried downloading and installing the zipped project above and I'm getting the same results as the video above as well.
I'm really new to this so it could very likely be a configuration setting somewhere for the project/android export I'm missing.
Any notes/links/ideas would be great!
Last thing I'm checking tonight is to try to update the Retroid Pocket 2+ to it's latest OTA update.

**Comment by Snowy-Fox** [comment]
> I'm still having this exact issue with the Retroid Pocket 2+ on v4.0.stable.official [[92bee43](https://github.com/godotengine/godot/commit/92bee43adba8d2401ef40e2480e53087bcb1eaf1)]

In Godot, which renderer are you using? For exporting for older Android devices, like the RP2+, you should be using Compatibility (gl_compatibility) for best results.

**Comment by aerze** [comment]
Yeah I was using the Compatibility version, ironically I found that switching to Mobile somehow helped and isn't showing the glitching anymore 🤷‍♀️ . I'm ok with using that for now but I can also keep testing the other mode if needed.

**Comment by Snowy-Fox** [comment]
> Yeah I was using the Compatibility version, ironically I found that switching to Mobile somehow helped and isn't showing the glitching anymore 🤷‍♀️ . I'm ok with using that for now but I can also keep testing the other mode if needed.

How odd! I didn't think the Mobile renderer was compatible with the RP2+. I'll have to test it myself at some point.

**Comment by aerze** [comment]
I checked online, and supposedly the GPU in the RP2+ should support vulkan 1 which _I think_ is why it's working, but again I'm very new to this

**Comment by aerze** [comment]
[RetroDodo Review/Specs](https://retrododo.com/retroid-pocket-2-plus/)
[PowerVR GE8300 Specs](https://www.notebookcheck.net/PowerVR-GE8300-GPU-Benchmarks-and-Specs.420311.0.html)
![image](https://user-images.githubusercontent.com/4723083/227768646-af5e34ce-58ca-4c5e-8b66-92530bedc865.png)

**Comment by DavidJayIndie** [comment]
There's still screen tearing on the RP2+ as of 4.2.2 rc2 unfortunately. I'd reopen a ticket about this, but I don't know if it's worth it for such a niche device.
