### ISSUE TITLE
Crash when changing glTF import settings

### ISSUE THREAD

**Issue by bmolyneaux** [godotengine/godot#70041]
### Godot version

4.0.beta7

### System information

Windows 10

### Issue description

Godot crashes when I try to change the import settings for a binary glTF file.

### Steps to reproduce

Double-click the .glb file in the file system.

### Minimal reproduction project

[GltfCrash.zip](https://github.com/godotengine/godot/files/10223634/GltfCrash.zip)

**Comment by aaronfranke** [comment]
I can't reproduce with either beta 7 or the latest master on a macOS computer. The import settings open fine.

**Comment by akien-mga** [comment]
Likely duplicate of https://github.com/godotengine/godot/issues/69604, fixed in beta 8 already.

**Comment by bmolyneaux** [comment]
This is not fixed in beta 8. It crashes as well.

**Comment by akien-mga** [comment]
I don't seem to be able to reproduce the bug either with the provided project, on Linux with beta 7, beta 8 or master.

Could you give more details on the Steps to reproduce?

You mention that it crashes when changing import settings, but then the steps to reproduce are only to double click the file. Does it crash when double clicking? When changing some specific settings? Which ones? When pressing Reimport?

**Comment by bmolyneaux** [comment]
In detail:

- Open the project
- Expand the animations folder
- Double-click the fall_animation.glb file

The pre-importing progress dialog is shown briefly and then Godot crashes. This is 100% reproducible on my Windows machine on either beta 7 or beta 8. I could try it on another OS and get back to you.

https://github.com/godotengine/godot/issues/69625 is fixed in beta 8 for me.

**Comment by bmolyneaux** [comment]
If I delete the `fall_animation.glb.import` file, it no longer crashes. That at least gives me a workaround.

I suppose if this is just an issue with incompatible import settings from a previous beta build, it's probably not worth fixing.

**Comment by bmolyneaux** [comment]
I was unable to reproduce the issue on Mac, so this seems to be Windows-specific.

Given that deleting the .import file (which was created by beta7) resolved the problem, I think that closing this issue makes sense.
