### ISSUE TITLE
Baked Light from godot 3.2.2 on godot 3.3.3 works

### ISSUE THREAD

**Issue by MiqueiasDevGames** [godotengine/godot#70051]
### Godot version

3.3.3

### System information

Linux Debian 11 i686

### Issue description

I managed to adapt godot to use the old Baked Light from version 3.2.2 in version 3.3.3, since the new lightmap doesn't support 32bit systems, see here:

[https://github.com/godotengine/godot/issues/69876](
https://github.com/godotengine/godot/issues/69876)

Well that Calinou could help me and generate the export templates for android

Help me with my campaign to buy a better computer, I only need $200
$200 is more than enough to buy a computer that can use godot for 3D
share or
give me some help here in my game on itch, any value already helps, below:
People from Godot put it on twitter for people to help me, please.

[https://miqueiasdevgames.itch.io/shanty-town-ball](https://miqueiasdevgames.itch.io/shanty-town-ball)

### Steps to reproduce

I managed to adapt godot to use the old Baked Light from version 3.2.2 in version 3.3.3, since the new lightmap doesn't support 32bit systems, see here:

[https://github.com/godotengine/godot/issues/69876](
https://github.com/godotengine/godot/issues/69876)

Well that Calinou could help me and generate the export templates for android

### Minimal reproduction project

I managed to adapt godot to use the old Baked Light from version 3.2.2 in version 3.3.3, since the new lightmap doesn't support 32bit systems, see here:

[https://github.com/godotengine/godot/issues/69876](
https://github.com/godotengine/godot/issues/69876)

Well that Calinou could help me and generate the export templates for android

**Comment by akien-mga** [comment]
This is a tracker for bug reports, it's not the place to ask for financial support or for help building custom versions of the engine.

**Comment by MiqueiasDevGames** [comment]
Don't forget people from godot to put it in the community, twitter reddit or other:

Help our friend to collect $200 to use all the good that Godot 3D can offer, help with any amount in the itch, below:
[https://miqueiasdevgames.itch.io/shanty-town-ball]( https://miqueiasdevgames.itch.io/shanty-town-ball)

**Comment by akien-mga** [comment]
I just told you this is not the place for this. This is a final warning, next time is a ban.

**Comment by MiqueiasDevGames** [comment]
@akien-mga 
Ok, I'm sorry, I already went to reddit, help me there, just fized for a few hours, here:
[https://www.reddit.com/r/godot/comments/zlofdx/the_game_i_made_in_godot_on_my_computer_i686_ram/](https://www.reddit.com/r/godot/comments/zlofdx/the_game_i_made_in_godot_on_my_computer_i686_ram/)
