### ISSUE TITLE
GDScript 2.0: Can't use Variant type for argument when override virtual method

### ISSUE THREAD

**Issue by DarkMessiah** [godotengine/godot#70054]
### Godot version

v4.0.beta8

### System information

Windows 10

### Issue description

Can't use Variant type for argument when override virtual method.

### Steps to reproduce

```
extends Node

func _set(property: StringName, value: Variant) -> bool:
	return true
```

Error: `The function signature doesn't match the parent. Parent signature is "_set(StringName, Variant) -> bool".`

### Minimal reproduction project

[override_bug.zip](https://github.com/godotengine/godot/files/10228241/override_bug.zip)

**Comment by Chaosus** [comment]
Also confirmed in 3.x with slightly different error:
```
SCRIPT ERROR: Parse Error: The identifier "Variant" isn't a valid type (not a script or class), or couldn't be found on base "self".
```

**Comment by Mickeon** [comment]
@Chaosus In 3.x you just can't statistically type "Variant", period.
