### ISSUE TITLE
[Proposal] Option for discarding draws outside of a `Control` rectangle

### ISSUE THREAD

**Issue by linkpy** [godotengine/godot#7005]
This can be use full in some case. Example :

In my game I've got a `GridContainer` which holds a list of `Control`s. Each of these `Control`s have a `Sprite`. I scale each sprite to fill all the `Control` space. But, if the texture does not have the exact aspect ratio of the `Control`, the `Sprite` will draw outside of the `Control`. What I done is to compute the texture region rectangle to have the exact aspect ratio. Even if the logic and the math behind this isn't really hard, it can be a problem to beginners in games development. 

Thanks.

**Comment by volzhs** [comment]
how about using `TextureFrame` instead of `Sprite`?

**Comment by linkpy** [comment]
For my case yes it will works, but for other case it may not works.

But thanks I didn't know about TextureFrame ^^

**Comment by Zylann** [comment]
Are you talking about using a clipping rectangle? (glScissor?) That functionnality expands beyond Controls IMO.

**Comment by linkpy** [comment]
I saw that `ScrollContainer` clip its content. So yes I'm talking about clipping rectangle.

**Comment by volzhs** [comment]
This would help.
https://godotengine.org/qa/675/how-to-clip-child-controls-to-parent-controls-rect-bounds

**Comment by vnen** [comment]
I think @reduz has plans to add a `clip` property for controls in 3.0.

**Comment by Zireael07** [comment]
What happened to those plans to add a clip property? I'm making a minimap out of controls and have to somehow work in clipping...

**Comment by Noshyaar** [comment]
Closing as fixed by `Control.rect_clip_content`.
