### ISSUE TITLE
Build and play buttons to run multiple instances at once

### ISSUE THREAD

**Issue by dawkot** [godotengine/godot#7008]
It would be helpful for developing multiplayer games if it was possible to instantly build and run a number of instances of the game at once to see if networking works correctly.

**Comment by bojidar-bg** [comment]
Partly related: https://github.com/godotengine/godot/issues/6642#issuecomment-256655555
> @bojidar-bg
> Note that you can make ... (drumroll) ... another SceneTree! For example, I've done something similar here: https://github.com/KOBUGE-Incubator/multiball/tree/615e0f07c6f30ab7e1d337b512dac1c6761957de/game/menu

**Comment by Noshyaar** [comment]
Still reproducible/relevant in 3.1 master 3ad9e47 : can't run multiple instances of a project

**Comment by bukkits-** [comment]
This is quickly becoming an annoyance here as well. The best workaround I can dream up right now is an editor plugin that calls a shell script that handles starting the server and client instances - but this is clunky

A feature that I would like is some configuration options for a one-click multiplayer project run. Many of these options exist in other engine editors such as Unreal.
This would include:

-Setting the number of clients to start on project run
-Arguments to pass the server instance and optionally set headless
-Arguments to pass client instances

**Comment by Zylann** [comment]
Just had some quick thoughts about it:
for example if you debug 2 instances (or even two threads!), and both fail at different scripts, which one should the editor open? Should it popup in foreground? If they fail in the same function, from which instance variable values will be shown? Which instance is the Stop button going to close? How do you know which is which? (and so on etc). Many assumptions of what was thought to be "One" (one instance) may become "Many". I think we may get multiple debuggers as processes first before we get them inside one single editor.

**Comment by Bombfuse** [comment]
Has work on this started or is there an ETA on it? I'm also developing a net game and having to relaunce godot over and over is very tedious and annoying

**Comment by Calinou** [comment]
@Bombfuse As far as I know, nobody is currently working on this.

**Comment by Bombfuse** [comment]
Yah I guess I can write a script, would still be an S+ feature imo tho

**Comment by asheraryam** [comment]
@Bombfuse Not really a fix, but what I do is that I keep the Project Manager open and from there I can run the server and as many clients as I need.
