### ISSUE TITLE
Shader editor autocomplete box clips off screen if too small

### ISSUE THREAD

**Issue by Haydoggo** [godotengine/godot#70088]
### Godot version

v4.0.beta8.official [45cac42c0]

### System information

Windows 10

### Issue description

When writing lines close to the top of the shader editor, the autocomplete popup list goes upwards, clipping off the top (often most relevant) suggestions.

I understand the editor is trying to stop the autocomplete popup from clipping off of the bottom of the screen for the case of editing close the bottom of the editor, but clipping off of the top is worse in this case.

Shader editor too small, cutting off top suggestions:
![image](https://user-images.githubusercontent.com/14885846/207758193-b9aef5a1-2574-497a-861f-511534bd7098.png)

Shader editor after resizing:
![image](https://user-images.githubusercontent.com/14885846/207759507-669c38ce-dbb3-4813-8a4b-a01ec076ecae.png)

### Steps to reproduce

1. Open shader in shader editor
2. Move cursor near top of screen and bring up autocomplete with something like
```c
shader_type canvas_item;

void fragment() {
	texture(TEX)
}
```
4. Shrink vertical size of shader editor until issue appears.

Produced on 1080p monitor, maximised editor window, with default editor scale.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Can you reproduce this on 3.5.1?

**Comment by Haydoggo** [comment]
Can't reproduce in 3.5.1. Autocomplete box only goes upwards if there is enough room for it to do so.
![image](https://user-images.githubusercontent.com/14885846/207965338-525121d6-187d-4200-8e15-5ab2b74eaaf4.png)
![image](https://user-images.githubusercontent.com/14885846/207965409-7838ae88-5cee-48d3-8e98-2e2c7c68abdc.png)

**Comment by Haydoggo** [comment]
> Can you reproduce this on 3.5.1? This is most likely caused by #32996.
 
In 3.5.1:
![image](https://user-images.githubusercontent.com/14885846/207967814-29d50383-bbaa-4840-9e17-112c238d09a7.png)

The autocomplete box still clips off the edges in 3.5.1, (which I agree, is likely caused by the issue you mentioned), but the logic for choosing the position of the autocomplete box is better in 3.5.1 such that the top of the autocomplete box is never off screen (It will never place the autocomplete box above the edited line unless there is room for it to fully fit there).

Fixing the `TextEdit` clipping issue would resolve this issue, but in the meantime, I think it would suitable to restore the autocomplete placement logic from 3.5.1.

**Comment by Haydoggo** [comment]
I'll make a PR to fix this when I get a chance
