### ISSUE TITLE
"Save Branch as Scene" does not work as expected.

### ISSUE THREAD

**Issue by al0fdf** [godotengine/godot#70095]
### Godot version

3.5 stable official(991bb6ac7)

### System information

Linux Debian Bullseye

### Issue description

After accessing the Remote Scene tree in the Scene tab and selecting "Save Branch as Scene", typing a file name, then pressing "save", the node is not saved. I would expect the scene to be saved under the specified filename with the selected node as its root.

### Steps to reproduce

1. Run project from editor
2. Select "Remote" in Scene tab
3. Right click on a node and select "Save Branch as Scene"
4. Provide filename, then press save.

### Minimal reproduction project

N/A

**Comment by stmSi** [comment]
but FileSystem Dock will not update the new file scene. I have to double Alt-Tab.. to update the FileSystem Dock.. i think that is another issue. both 3.x and 4.0 suffer this issue.

**Comment by akien-mga** [comment]
>  but FileSystem Dock will not update the newly created file. I have to double Alt-Tab.. to update the FileSystem Dock.. i think that is another issue. both 3.x and 4.0 suffer this issue.

Could you open an issue about this so we keep track of it?

**Comment by stmSi** [comment]
Will do.

**Comment by akien-mga** [comment]
Fixed by #70584.
