### ISSUE TITLE
Noise texture shader not repeating

### ISSUE THREAD

**Issue by AdeptusCat** [godotengine/godot#70105]
### Godot version

4.0-beta8

### System information

Windows10, Foward+/mobile, GTX3080

### Issue description

The noise texture inside a Sprite2D is not repeating and glitches out on 4.0-beta8. Works fine in 3.5.1 as seen in the following images:

Result in godot 4.0-beta8
![4 0](https://user-images.githubusercontent.com/33057629/207846594-a33f1d74-b6cc-4908-98d6-4eff8fb2570f.png)

Result in godot 3.5.1
![3 5 1](https://user-images.githubusercontent.com/33057629/207846664-14794a9a-581a-4ccc-9855-3169a2f2102c.png)

### Steps to reproduce

Create Sprite2D
Add Noise Texture2D as Texture
Use FastNoiseLite as Noise
Otherwise default config
Add ShaderMaterial as Material
Add shader script with the following code

```
shader_type canvas_item;

void fragment() {
	float textureColor = texture(TEXTURE, UV + vec2(0.1, 0.1) * TIME).r;
	COLOR = vec4(textureColor); 
}
```

![config](https://user-images.githubusercontent.com/33057629/207847832-abdf417b-6b2c-45b5-9157-b6809b36567a.png)

### Minimal reproduction project

[shader_test.zip](https://github.com/godotengine/godot/files/10236569/shader_test.zip)

**Comment by tinmanjuggernaut** [comment]
Attach the texture directly to the shader parameters. Then enable repeating on the texture uniform.

```
shader_type canvas_item;

uniform sampler2D noise_tex : repeat_enable;
uniform float uv_scale = 1.0;

void fragment() {
	float textureColor = texture(noise_tex, uv_scale * UV + vec2(0.1, 0.1) * TIME).r;
	COLOR = vec4(textureColor); 
}
```
