### ISSUE TITLE
`@tool` annotation requires project reopen to start working

### ISSUE THREAD

**Issue by anvilfolk** [godotengine/godot#70128]
### Godot version

4.0 master

### System information

Windows 11

### Issue description

The `@tool` annotation doesn't appear to take effect until the project is reopened.

### Steps to reproduce

```GDScript
func _process(_delta):
  print("@tool working")
```

1. Create a Node
2. Attach above script
3. Add `@tool` annotation to script and save
4. Notice nothing happens
5. Close and reopen project
6. Notice flood of `@tool working` messages in output

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
You don't need to reopen project, reloading the scene should be enough.
Also the reason why this happens is that `set_process()` is called when node is ready, which happens only once. Hence reloading is needed. You could try with something that doesn't need enabling, e.g. NOTIFICATION_VISIBILITY_CHANGED.
