### ISSUE TITLE
Autoloads broken: cannot find members

### ISSUE THREAD

**Issue by lufog** [godotengine/godot#70127]
### Godot version

v4.0.beta.custom_build [15631e24f]

### System information

Windows 11, Forward+, Geforce 1660 (526.98)

### Issue description

When I try to get a variable from autoload, I get:
```Parser Error: Cannot find member "audio_player" in base "".```

I think the regression was introduced in 6debf86d5, because on the previous commit (ec4de82ab) MRP works.

### Steps to reproduce

open and run project

### Minimal reproduction project

[var_from_autoload_test.zip](https://github.com/godotengine/godot/files/10240605/var_from_autoload_test.zip)

**Comment by joaopedrosgs** [comment]
same issue here

**Comment by akien-mga** [comment]
CC @rune-scape

**Comment by dmaz** [comment]
this might be related.  I get the following after op mentioned commit
```
SCRIPT ERROR: Invalid get index 'data' (on base: 'Node3D ()').
          at: Health._init (res://scripts/Health.gd:21)
```
 
autoload Game.gd 
```
var data:Resource
```

Health.gd
```
	match group:
		PLAYER: maxValue = Game.data.playerBuff.getHealth(maxHealth)
		ENEMY: maxValue = Game.data.enemyBuff.getHealth(maxHealth)
		ENVIRONMENT: maxValue = maxHealth
```

**Comment by Lippanon** [comment]
Trying to access a var or const, from an autoload, as an autoload, also doesn't work anymore. Functions don't throw this error. Leaving a different MRP here with those 3 cases, if needed to test.

![image](https://user-images.githubusercontent.com/115422160/208321299-46f17d41-87a9-44ac-b5da-10808d560ce3.png)

MRP: [autoload bug.zip](https://github.com/godotengine/godot/files/10254705/autoload.bug.zip)
