### ISSUE TITLE
Changing type of node removes it from all groups

### ISSUE THREAD

**Issue by RebelliousX** [godotengine/godot#7013]
Tested on Godot 2.1, but pretty positive the issue is there in 2.2+

**Issue description** (what happened, and what was expected):
If a scene was added to a group in the Node viewer (Node is next to Inspector. Group is next to Signals)
and then we try to change the type of the scene (say, static 2d to area2d), the added "Group" is gone! 

Looking for issues in the wrong place, this can lead to headaches if overlooked, barking up the wrong tree is not nice!

**Steps to reproduce:**
Create a scene lets say StaticBody2D
Add it to a group, lets say "Walls"
Change the type of the Scene/Node to Area2D
Grouping is gone.

**Comment by volzhs** [comment]
It would be better to change title to describe more specific, like "Changing node type loses Group info"
