### ISSUE TITLE
Can't set meta by get_instance_id()

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#70141]
### Godot version

v4.0.beta8.official [45cac42c0]

### System information

Windows 10, 64bit

### Issue description
Can't set meta by `get_instance_id()`
![image](https://user-images.githubusercontent.com/35988767/208062138-3259c2f7-9729-47bf-afaa-503b8c9b5870.png)

### Steps to reproduce

/

### Minimal reproduction project

[MetaTest.zip](https://github.com/godotengine/godot/files/10244219/MetaTest.zip)

**Comment by timothyqiu** [comment]
Meta data's name should be a valid identifier. A valid identifier can't start with a number, thus the error.

**Comment by rburing** [comment]
The error message can be improved to be more human-readable then.

**Comment by CsloudX** [comment]
OK, thanks, should I close this issue? @timothyqiu

**Comment by timothyqiu** [comment]
@CsloudX I think this requirement can be documented, and the error message can be improved just like @rburing said.
