### ISSUE TITLE
OpenGL: 3D resolution scaling does not scale the image to the full viewport size

### ISSUE THREAD

**Issue by zaevi** [godotengine/godot#70142]
### Godot version

4.0.beta8

### System information

Win11, gl_compatibility

### Issue description

Scaling 3D doesn't work on `gl_compatibility` renderer.

**renderer=forward+, scale=0.5:** 
![image](https://user-images.githubusercontent.com/12966814/208063267-f1774fbe-6193-4072-b278-85e825586c28.png)

**renderer=gl_compatibility, scale=0.5:**
![image](https://user-images.githubusercontent.com/12966814/208063056-308022dd-cfa0-4a67-9d98-1d82f1653cc7.png)

**renderer=gl_compatibility, scale=0.5, running on web:**
![image](https://user-images.githubusercontent.com/12966814/208063956-c2c53fed-e1d2-4777-a41d-e30d88ab462c.png)

### Steps to reproduce

see reproduction project below

### Minimal reproduction project

[web_3d_scaling.zip](https://github.com/godotengine/godot/files/10244336/web_3d_scaling.zip)

**Comment by Calinou** [comment]
For reference, 3D resolution scaling was added to Vulkan backend in https://github.com/godotengine/godot/pull/51870.

**Comment by clayjohn** [comment]
Fixed by https://github.com/godotengine/godot/pull/83976
