### ISSUE TITLE
Directory.dir_exists() always return True on Android

### ISSUE THREAD

**Issue by Barina** [godotengine/godot#7014]
**Operating system or device - Godot version:**
Android Galaxy S4 Galaxy S6
Godot tools and export templates from 20dd5a6 compiled on Windows 7 x64

**Issue description** (what happened, and what was expected):
Calling Directory.dir_exists(some_path) on Android always return True even if there isn't any directory in that path
Related to [6837](https://github.com/godotengine/godot/issues/6837)

**Steps to reproduce:**
A project with assets:
- scenes
    - 0
        - 0.scn
        - 1.scn
        - 2.scn
        - 3.scn

And the following code
```
1. var dir = Directory.new()
2. var path = "res://scenes/non_valid/dir"
3. if dir.dir_exists(path):
4. 	print(path, " exist")
5. else:
6. 	print(path, " not exist")
```
After running this on Android device it will print "res://scenes/non_valid/dir exist" even if it isn't.

**Comment by volzhs** [comment]
It's odd. at last time I checked when fixing crash #6837, I got expected result.

**Comment by Barina** [comment]
Yes me too.. and it's also the same project

**Comment by volzhs** [comment]
`core/os/dir_access.cpp` has not been changed since 5 months ago...

**Comment by vnen** [comment]
`core/os/dir_access.cpp` is the base file, this is a platform-specific problem, so either in `drivers/unix` or `platform/android`.

**Comment by volzhs** [comment]
hm, `dir_access*` files under those directory seem not to changed at least 3 months also...

**Comment by Barina** [comment]
I tested it on two separated projects
I'll make a new clean and fresh project and test it again, this time I'll try numbers, letters and other characters as folder name and for files too, maybe it has something to do with it..

**Comment by Barina** [comment]
I did some testing with a new project but the results are the same. Directory.dir_exists(path) always return TRUE even if 'path' is empty
Link to the project [Directory Text](https://drive.google.com/open?id=0B54uADD0Gcm9aG1EQTB0anB4VGc)

**Comment by volzhs** [comment]
when run on desktop with this code
```gdscript
func dir_contents(path):
	var text = ""
	var dir = Directory.new()
	if dir.open(path) == OK:
		dir.list_dir_begin()
		var file_name = dir.get_next()
		while file_name != "":
			if dir.current_is_dir() and file_name != "." and file_name != "..":
				var content = dir_contents(file_name)
				text += str(dir.get_current_dir(), "/", file_name, "\n", content)
			file_name = dir.get_next()
	else:
		print("An error occurred when trying to access ",path)
	return text
```
debugger shows error messages.
```
An error occurred when trying to access 0
An error occurred when trying to access @
An error occurred when trying to access _
An error occurred when trying to access 0
An error occurred when trying to access a
An error occurred when trying to access 1b
```
this should be changed like this
```gdscript
...
			if dir.current_is_dir() and file_name != "." and file_name != "..": 
				var content = dir_contents(dir.get_current_dir()+"/"+file_name) # this
...
```

**Comment by volzhs** [comment]
Here is my test codes.
```gdscript
func dir_contents(path):
	var text = ""
	var dir = Directory.new() 
	if dir.open(path) == OK: 
		dir.list_dir_begin() 
		var file_name = dir.get_next() 
		while file_name != "" and file_name != null:
			if dir.current_is_dir() and file_name != "." and file_name != "..": 
				var path = dir.get_current_dir().plus_file(file_name)
				print("Found directory: " + path)
				var content = dir_contents(path)
				text += str(path, "\n", content)
			else: 
				print("Found file: " + file_name) 
			file_name = dir.get_next() 
		dir.list_dir_end() 
	else: 
		print("An error occurred when trying to access ",path)
	return text
```

**Note that empty directory is not included when packaging APK.**
Even if there is an empty directory in APK, `dir.dir_exist()` will return `false`.
can't determine if empty directory is actually directory or file on Android.

**Comment by Barina** [comment]
Yes of course that's why I put some scenes in there ;)

**Comment by volzhs** [comment]
I tested with my Nexus 6P (Android 7.0) and works well.

**Comment by Barina** [comment]
I compiled to 6993214 tools and export templates for Windows and Android, and placed them in appdata
But still same results.. here's updated project with the exported apk
[Directory Test.zip](https://drive.google.com/open?id=0B54uADD0Gcm9dTV6QWdpNFVKSDQ)

**Comment by volzhs** [comment]
hey... that's not the one for fixing this issue.
It's not merged yet.
if it's merged, this issue will be closed.

**Comment by Barina** [comment]
Oops I guess I see things LoL..
