### ISSUE TITLE
_GetPropertyList() in CSharp has different behavior with _get_property_list() in GDScript

### ISSUE THREAD

**Issue by Parallel-Paradox** [godotengine/godot#70146]
### Godot version

4.0.beta8

### System information

Windows 11

### Issue description

According to the document: https://docs.godotengine.org/en/latest/classes/class_object.html#method-descriptions - _get_property_list(), I create a dynamic property list in both GDScript and CSharp.

In CSharp:

<img width="294" alt="image" src="https://user-images.githubusercontent.com/81791934/208093231-fb4e5c88-1f6f-4b95-9440-9d3da26dbf19.png">

In GDScript:

<img width="294" alt="image" src="https://user-images.githubusercontent.com/81791934/208093274-a086eb63-a63a-49fd-82a6-e5cba16eb656.png">

The HammerType property can't be set to the catagory.

By the way, the document of _get_property_list() miss the `partial` key word:

```C#
[Tool]
public class MyNode2D : Node2D
...
```

### Steps to reproduce

Open the node_2d.tscn in the MRP given below, then check out the CSharp node and GDScript node.

### Minimal reproduction project

[MRP.zip](https://github.com/godotengine/godot/files/10245579/MRP.zip)

**Comment by Calinou** [comment]
Can you reproduce this on 3.5.1?

**Comment by MikeSchulze** [comment]
Hi i run into same issue on Godot 4.1


```csharp
    public partial class MyClass : Node
    {
        private int _value = 0;

        private RefCounted? _nullable = new RefCounted();


        [Export]
        public RefCounted? _bar = new RefCounted();


        public void Foo()
        {
            Bar();
        }
        public virtual void Bar()
        {
            _value = 1;
        }
    }
```
```csharp
            var t = new MyClass();

            System.Console.WriteLine($"value: {t.Get("_value")}");
            System.Console.WriteLine($"value: {t.Get("_foo")}");
            System.Console.WriteLine($"value: {t.Get("_bar")}");
            System.Console.WriteLine($"property `_foo` exists: {t.GetPropertyList().Any(p => p["name"].Equals("_foo"))}");
            System.Console.WriteLine($"property `_bar` exists: {t.GetPropertyList().Any(p => p["name"].Equals("_bar"))}");
            System.Console.WriteLine($"property `_foo` exists: {t.GetPropertyList().Any(p => p["name"].ToString().Equals("_foo"))}");
            System.Console.WriteLine($"property `_bar` exists: {t.GetPropertyList().Any(p => p["name"].ToString().Equals("_bar"))}");
            foreach (var dict in t.GetPropertyList())
            {
                var name = dict["name"];
                System.Console.WriteLine($"property: {name}");
            }
            t.Free();
```

```shell
value: 0
value: 
value: <RefCounted#-9223372006588676904>
property `_foo` exists: False
property `_bar` exists: False
property `_foo` exists: False
property `_bar` exists: True
property: Node
property: _import_path
property: name
property: unique_name_in_owner
property: scene_file_path
property: owner
property: multiplayer
property: Process
property: process_mode
property: process_priority
property: process_physics_priority
property: Thread Group
property: process_thread_group
property: process_thread_group_order
property: process_thread_messages
property: Editor Description                                                          PASSED 096ms
property: editor_description
property: script
property: MyClass
property: _bar
```

I see multiple issues here.
The `GetPropertyList` only contains the custom variables annotated by `[Export]`
The dictionary contains Variant objects of String and is not able to compare to a string.

For me is still unclear why the Variant type is exposed to C# this makes thinks more complex as it need.
When expose Variants to C# than please add full suport of Comparable to standard c# objects to avoid extra code to handle variants.

**Comment by hayahane** [comment]
I've looked into the engine code.
It seems that `CSharpScriptInstance` and `GDScriptInstance` deals with `get_property_list()` differently.
GDScript adds default propertyinfos in the front.
C# simply appends the default propertyinfos behind the data that overriden function returns.
I guess that's the problem.
