### ISSUE TITLE
Centered sprites are off in odd sizes

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#7015]
**Operating system or device - Godot version:**
Godot Windows x64 v2.2

**Issue description** (what happened, and what was expected):
When using the centered option in a sprite, it'll be half a pixel off if it's an odd sized image, e.g: 11x9. I think that's fixable since you can unmark the centered option and mess with the offset to properly center it, but it's a pain in the ass to do so when you have hundreds of images.

**Steps to reproduce:**
Create an odd sized image, put it in a sprite node and mark "centered".

**Comment by volzhs** [comment]
you mean odd size (11x9)?

**Comment by mateusak** [comment]
I don't speak english, forgot what was what. 😢

**Comment by volzhs** [comment]
I don't speak English either :) just want to make it sure.

**Comment by Zylann** [comment]
Centered sprites with odd size are not very common. You could make it even, then.
If Godot were to support integer centering... I see one case where it would be annoying, and that is when you don't care about centered pixels, especially when the sprite is supposed to rotate. Could it be an option?

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by mateusak** [comment]
@Noshyaar Still an issue.

**Comment by akien-mga** [comment]
The main question is whether we want to support this use case, and allow the centering option to set an internal half-pixel offset. IMO that could be quite confusing, especially if doing pixel art, but that's worth discussing.

**Comment by KoBeWi** [comment]
That sounds similar to my old issue: #20622

**Comment by Ramh5** [comment]
This issue is quite limiting for me at the moment trying to set the position of a train wagon centered on a line. It would be useful to be able to set the center to the track, the corner is useless for my case. I don't see what use case would benefit from the current off-centered "centered".

**Comment by Regoso** [comment]
Ya for working on Low pixel count games (Gameboy, Atari) a 1 pixel wide char just doesnt work

**Comment by KoBeWi** [comment]
It works if you disable centering (and enable pixel snap).

**Comment by Maran23** [comment]
> The main question is whether we want to support this use case, and allow the centering option to set an internal half-pixel offset. IMO that could be quite confusing, especially if doing pixel art, but that's worth discussing.

I agree.
Currently, one has two options:
- Center it and enable pixel snap (will affect the whole game)
- Do the centering work manually in a script (which will affect other objects you add as child)

I think what we need is a third option: Center a sprite and snap it.
This is most likely a proposal at this point though.

**Comment by Calinou** [comment]
Out of curiosity, can this be reproduced with Sprite3D

**Comment by YuriSizov** [comment]
I agree with the assessment, that if an improvement is needed, it should be requested with a proposal and a specific solution should be described for that.
