### ISSUE TITLE
Continuous Collision Detection no longer works with high speed body

### ISSUE THREAD

**Issue by fabriceci** [godotengine/godot#70154]
### Godot version

4.0 (2e657e51)

### System information

macOS 12.6

### Issue description

Seems that #69934 introduce a regression.

The CCD test (in my physical test project) fails after this commit. In both 2D/3D :

Before:

![Screenshot 2022-12-16 at 17 56 26](https://user-images.githubusercontent.com/6397893/208149568-8a5f4dbd-d08c-49b9-b7f0-e784d216ef65.jpg)

After:

![Screenshot 2022-12-16 at 17 44 47](https://user-images.githubusercontent.com/6397893/208148532-db7dbc2d-a50b-42c5-8a27-74ba9cea8b72.jpg)

@Geekotron could you take a look?

I am not familiar with this algorithm, it seems to be related to `from -= motion * 0.1;`. (note, in 2D, if we lower 0.1 to 0.01, seems to help)

### Steps to reproduce

Open the physics test project: https://github.com/fabriceci/Godot-Physics-Tests

Open the scene:

- in 2D: `tests/nodes/RigidBody/tests/2d/conntinuous_detection.tscn`
- in 3D: `tests/nodes/RigidBody/tests/3d/conntinuous_detection.tscn`

And run the scene.

### Minimal reproduction project

/

**Comment by Geekotron** [comment]
Checking it out now.
