### ISSUE TITLE
2 script icons on Scene dock

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#7016]
**Operating system or device - Godot version:**
compiled 681575fa7123592897090c6cce44402c4e45baeb

**Issue description** (what happened, and what was expected):
![image](https://cloud.githubusercontent.com/assets/8281454/19940207/31178250-a16f-11e6-852e-45c6ec747a56.png)
One for "create script" and the other one for "load script"
These 2 icons are not recognizable and take too much space.

It would be nice make it 1 icon in somehow.

**Comment by eon-s** [comment]
+1 for a single icon, with a dropdown menu is possible.

I was also thinking if the "create" screen could turn into "load" if "file exists" (the file exists check is already in create).

**Comment by puppetmaster-** [comment]
I got yesterday the problem, not showing any script icons after selecting top scene node. (last build)

**Comment by vnen** [comment]
This was auto-closed, but I still think two icons there is too much.

**Comment by RebelliousX** [comment]
@vnen It is too much, there should have been a drop down menu on the spot asking to choose between add or create.

**Comment by TheoXD** [comment]
@RebelliousX, finally someone with good ideas, nowadays anything can get merged without a second thought or considering alternatives. Selecting already existing script in creation dialog makes more sense. Was very frustrating to pull newest changes and see... well whatever it was...

**Comment by akien-mga** [comment]
> nowadays anything can get merged without a second thought or considering alternatives,

Well if we would get users to actually review PRs that could help. Looks like getting things merged is the only way to get them reviewed..
