### ISSUE TITLE
Godot 4: Creating a project on hardware without Vulkan support generates a project that can't be opened

### ISSUE THREAD

**Issue by aragubas** [godotengine/godot#70162]
### Godot version

v4.0.beta8.mono.official.45cac42c0

### System information

Windows 10 22H2 (19045.2364); GPU: Nvidia GT 430 (GLES3); CPU: Intel Core i5 2400; Ram Size: 14GB

### Issue description

When creating a project on hardware that doesn't support vulkan the project can't be opened.
The Main Window does open but the generated project doesn't.
```
Editing project: C:/Users/Ceira/Documents/Development
Godot Engine v4.0.beta8.mono.official.45cac42c0 - https://godotengine.org
ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: _create_physical_device (drivers/vulkan/vulkan_context.cpp:1094)
ERROR: Condition "err != OK" is true. Returning: ERR_CANT_CREATE
   at: _window_create (drivers/vulkan/vulkan_context.cpp:1624)
ERROR: Failed to create Vulkan Window.
   at: (platform/windows/display_server_windows.cpp:3620)
ERROR: Failed to create main window.
   at: (platform/windows/display_server_windows.cpp:3937)
``` 

My suggestion is to change the renderer of the generated project to OpenGL3 if the hardware doesn't support vulkan, so that the generated project can be opened.

A workaround is to add the the ``--rendering-driver opengl3`` command line argument

### Steps to reproduce

Open Godot on hardware that doesn't support Vulkan, Create a New Project, Try to open the project (it won't open)

### Minimal reproduction project

[DefaultProject.zip](https://github.com/godotengine/godot/files/10248316/DefaultProject.zip)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/58927. This needs the OpenGL fallback to be implemented first.

**Comment by clayjohn** [comment]
This will be substantially alleviated in Beta 9 because you will be able to create an [OpenGL project from the project creation menu](https://github.com/godotengine/godot/pull/70028)

**Comment by akien-mga** [comment]
Yes, I think we can consider that #70028 solves this, and the remaining part (having a fallback when opening a project intentionally using Vulkan) is covered by #58927.
