### ISSUE TITLE
Enum values are inconsistent

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#70179]
### Godot version

4.0 ab354b8

### System information

Windows 10 x64

### Issue description

I have enum like this:
```GDScript
enum {SOUND_ENTER, SOUND_EXIT, SOUND_MOVE, SOUND_ACCEPT, SOUND_CANCEL, SOUND_FAIL, SOUND_TAB, SOUND_CONSUME, SOUND_EQUIP,
		SOUND_SHOP_ENTER, SOUND_SHOP_EXIT, SOUND_SHOP_BUY, SOUND_SHOP_SELL, SOUND_START, SOUND_SWAP}
```
It's inside a `class_name` script. I access them from outside the script, like this for example:
```GDScript
prints("SOUND_MOVE", Enum.SOUND_MOVE)
```
The result is...
```
SOUND_MOVE 1
```
But if I do
```GDScript
prints("SOUND_ENTER", Enum.SOUND_ENTER, "SOUND_EXIT", Enum.SOUND_EXIT, "SOUND_MOVE", Enum.SOUND_MOVE)
```
I get
```
SOUND_ENTER 0 SOUND_EXIT 1 SOUND_MOVE 2
```

The returned value of `SOUND_MOVE ` depends on values I used before it.

Bonus:
The second example in my project gives
```
SOUND_ENTER 0 SOUND_EXIT 1 SOUND_MOVE 1
```
I can't reproduce this result in a minimal project.

### Steps to reproduce

1. Add an enum in a class_name script
2. Print a single value of that enum in another script

### Minimal reproduction project

[EnumBug.zip](https://github.com/godotengine/godot/files/10250530/EnumBug.zip)

**Comment by anvilfolk** [comment]
Out of curiosity, is this a totally new regression or was it working fine some time before?

**Comment by rune-scape** [comment]
ah it's a regression introduced in https://github.com/godotengine/godot/pull/69471

**Comment by anvilfolk** [comment]
I'm trying something to see if I can fix it :) but if you are as well we can compare solutions later!

**Comment by rune-scape** [comment]
oh, yea, i just remembered where it was. a tiny fix
