### ISSUE TITLE
2D rendering optimizations for 2.x

### ISSUE THREAD

**Issue by RandomShaper** [godotengine/godot#7017]
I'm optimizing the 2D rendering. I was aware that my work would probably never get merged due to Godot 2.2 skipped and the new renderer for 3.0 will probably be already better optimized than the current.

At least it would be of use in my currently developed game until the Godot 3.0 version compatible with GL ES 2.0 were released.

But now I know Godot 2.1.1 will see the light of the day, tomorrow probably. So there is still a chance for my work to become official and get merged in an official Godot release. Probably I'm too late for 2.1.1, but is there any hope of a 2.1.2 or 2.2 release?

Of course, first I have to complete the task (one or two days I expect) and check it the performance gain worths it (provided there is actually some gain; you never know).

Also I would like to know if people are interested in this being released.

**Comment by punto-** [comment]
What are these optimizations exactly? Somebody is working on a 3ds port at
the moment, they'll probably benefit from this

**Comment by volzhs** [comment]
As you know, Godot 3.0 is based on GLES 3.0 and about 45% android devices are still use GLES 2.0.
So, I would use 2.x version for production until 3.x released which support GLES 2.0 also.

**Comment by RandomShaper** [comment]
What a quick feedback! Knowing some people is interested encourages me.

I'm attempting thsee optimizations:
1) Use VBOs for primitives like lines and, the most relevant, rects. That with a cache. I hope the cache code is faster than submitting vertices and UVs on every draw.
2) Front-to-back rendering with depth buffering.

I don't want to give false hopes, but I think at least these deserve a try.

**Comment by akien-mga** [comment]
As I mentioned, there will be 2.1.x releases until we decide not to support it anymore (i.e. until 3.x is ripe enough to take over for 99% of use cases). There won't be a 2.2.

**Comment by JustDevs** [comment]
Is this optimization will fix jittering/stuttering bug that occurs in 2.1? That would be really nice if you can get it fixed.

**Comment by RandomShaper** [comment]
Jittering can be due to a number of different things. I can't tell you 
what I will be able to achieve.

**Comment by oliver-ruehl** [comment]
I'm having a stuttering and jittering animated sprite as well.
Not sure though if this is caused by the engine or by code.
https://www.dropbox.com/s/inm16am0tjfsrex/jittering_animated-sprite.m4v?dl=0

**Comment by RandomShaper** [comment]
I'd say its related to your own code, but it's difficult to know without
knowing more about your scene.

**Comment by oliver-ruehl** [comment]
I was able to fix my sprite jittering by following this rule of thumb:

- physics = _fixed_process
- everything else = _process

**Comment by RandomShaper** [comment]
I think I have bad news. After more than a month of work, I re-implemented de 2D drawing applying a number of techiques.

I tried different approaches measuring on PC and mobile to try to find the fastest way of doing things and I researched a lot.

Anyway, my final implementation has ended up being a bit slower than the original. It does a lot of book-keeping, probably adding too much work for the CPU. It also adds some RAM overhead. It would worth it if it would have taken us to an overall faster rendering, but it hasn't.

So this has been a big waste of time. At least, I learned a couple of things about how GL driver and hardware works.

Anyway, if anybody wants to try it for himself, you can find by branch here: [https://github.com/RandomShaper/godot/tree/exp-optimize-2d-render](https://github.com/RandomShaper/godot/tree/exp-optimize-2d-render)

It's based on _master_, though I think the relevant commits could be cherry-picked for the _2.1_ branch.

**Comment by bojidar-bg** [comment]
Uhm, given the above comment and the fact that this issue is getting a bit stale, should it be closed?

**Comment by RandomShaper** [comment]
For me closing this is OK.

I expected some feedback about how my code performed for other people, but yes, this is not getting anywhere.

**Comment by mhilbrunner** [comment]
@akien-mga This can be closed.
