### ISSUE TITLE
Regex module requires runtime type information

### ISSUE THREAD

**Issue by eska014** [godotengine/godot#7018]
Since #6887, the Regex module included in the repository uses `dynamic_cast` in [regex.cpp](https://github.com/godotengine/godot/blob/20dd5a62cf4b639987c62c38447ff39fe1d692c8/modules/regex/regex.cpp). This requires RTTI, which is disabled in JavaScript builds to keep the file size low.

**Comment by eska014** [comment]
Just saw #6958 where this is fixed, so should be fixed after merging

**Comment by akien-mga** [comment]
Fixed by f935d7a.
