### ISSUE TITLE
Setting raycast parameters to exclude self causes Godot runtime window to crash without error

### ISSUE THREAD

**Issue by LouisIngenthron** [godotengine/godot#70183]
### Godot version

v4.0.beta5.mono.official [89a33d28f]

### System information

Windows 10 x64

### Issue description

The following code (in a class derived from Node) causes Godot's runtime window to crash.  The editor reports no errors.

```
var rayParam = new PhysicsRayQueryParameters3D();
rayParam.Exclude.Add(Variant.CreateFrom(this));
```

### Steps to reproduce

Just run the repro project.

### Minimal reproduction project

[MinReproProject.zip](https://github.com/godotengine/godot/files/10250944/MinReproProject.zip)

**Comment by rburing** [comment]
Can you test again with the latest 4.0 beta 8? Note the [`exclude`](https://docs.godotengine.org/en/latest/classes/class_physicsrayqueryparameters3d.html#class-physicsrayqueryparameters3d-property-exclude) array has changed to be strongly typed, accepting only `RID`s, which can be obtained from collision objects (such as areas and physics bodies) using the [`get_rid()`](https://docs.godotengine.org/en/latest/classes/class_collisionobject3d.html#class-collisionobject3d-method-get-rid) method.

**Comment by LouisIngenthron** [comment]
Yes, that appears to fix the problem.  However, the code is now more cumbersome:

`rayParam.Exclude.Add(GetNode<CollisionShape3D>("Collider").Shape.GetRid());`

It would be nice to have a helper method that adds all CollisionShapes on a given node or its children to the list.

**Comment by rburing** [comment]
You may have misread the terminology; probably we should say

> [CollisionObject3D](https://docs.godotengine.org/en/latest/classes/class_collisionobject3d.html#class-collisionobject3d)-derived node (such as an [Area3D](https://docs.godotengine.org/en/latest/classes/class_area3d.html) node or a [PhysicsBody3D](https://docs.godotengine.org/en/latest/classes/class_physicsbody3d.html)-derived node).

 in the documentation of the `exclude` parameter.

So you can just call `get_rid()` on a physics body; then all its collision shapes will be excluded.

Does what you wrote actually work? (It will compile, but I don't think it works.)

**Comment by LouisIngenthron** [comment]
I don't know if it worked or not.  It was my first attempt to use the exclude function, so I don't have great use cases to test that in my current setup, unfortunately. 

I think I can close this issue, though, since it's no longer relevant in the latest beta.
