### ISSUE TITLE
Incorrect file filter for icon in Windows export preset

### ISSUE THREAD

**Issue by localwhale20** [godotengine/godot#70188]
### Godot version

4.0beta8

### System information

Windows 10, Vulkan, NVIDIA Geforce 920MX

### Issue description

I accidently find that Select Console Wrapper Icon dialog uses incorrect filter, instead of `*.ico, *.png ...` it uses `*.ico.*.png ...`
![image](https://user-images.githubusercontent.com/61111955/208237839-2b544e6d-12f8-4302-9db6-1396b38279de.png)

### Steps to reproduce

Open Project>Export
Create Windows Export template
Scroll down on right side to Console Wrapper Icon
Try to select Console Wrapper Icon

### Minimal reproduction project

N/A

**Comment by vmedea** [comment]
Wrong line is here: https://github.com/godotengine/godot/blob/master/platform/windows/export/export_plugin.cpp#L229
