### ISSUE TITLE
Editor asset lib cannot display svg icons.

### ISSUE THREAD

**Issue by HolonProduction** [godotengine/godot#70195]
### Godot version

4.0.beta8

### System information

Windows 10

### Issue description

When viewing assets which have a svg icon in the editor the icon is not displayed.

I consider this a bug as the webinterface accepts and displays svg icons correctly. The project manager can also display svg project icons correctly.

### Steps to reproduce

Have a look at this asset in the AssetLib tab:
https://godotengine.org/asset-library/asset/1474

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
This is likely not feasible to implement in 3.5 due to the lack of run-time SVG loading, but it should be feasible in 4.0.

cc @fire

**Comment by fire** [comment]
It should be possible to do runtime svg and even animated vector graphics via thorvg. Rive does this with thorvg.

However it is a feature enhancement, so if I wanted to work on this, I'd need to delay 4.0, do a kludge or reduce work on something else.

**Comment by EsdrasCaleb** [comment]
Godot does not open SVG that do not have height and weight properties inside it yet. And the way it opens is different from the way the godot 3.0 open. There are plans to solve this?
