### ISSUE TITLE
move_and_collide: kinematicCollision returning null

### ISSUE THREAD

**Issue by derickfelix** [godotengine/godot#70194]
### Godot version

3.5.stable.official [991bb6ac7]

### System information

Windows 10

### Issue description

I don't know if this is correct, I am opening the issue for the case it isn't.
These two rockets are a `KinematicBody`, one has the x rotation at `-30dg`, and the other at `-29dg`. They are about to collide with a `trimesh static body`.

![image](https://user-images.githubusercontent.com/20743967/208246071-312b8b30-4f5e-4817-a423-de498f5f3216.png)

Using the `move_and_collide` function, the return of the first instance is working normally, but the second returns `null` when touching the ground, it keeps going forward forever.

![image](https://user-images.githubusercontent.com/20743967/208246445-27e6947e-c38c-4106-989b-f11604c589d5.png)

Also, there is another issue that is related with particles:

![image](https://user-images.githubusercontent.com/20743967/208246501-e0b6d757-248a-4e35-9948-9c3e4c13e37a.png)

A particle from the rocket appears where it isn't supposed to as soon as the scene loads.

### Steps to reproduce

Just run the project.

### Minimal reproduction project

[CollisionNotWorking.zip](https://github.com/godotengine/godot/files/10251923/CollisionNotWorking.zip)

**Comment by derickfelix** [comment]
I just tested on godot 4, none of the two issues happened.
[CollisionWorkingGodot4.zip](https://github.com/godotengine/godot/files/10251951/CollisionWorkingGodot4.zip)

**Comment by Calinou** [comment]
Can you reproduce the issue in 3.5.1 after switching the 3D physics engine to **GodotPhysics** in the project settings?
