### ISSUE TITLE
Clicking textured CSG mesh in viewport crashes Godot

### ISSUE THREAD

**Issue by jotson** [godotengine/godot#70203]
### Godot version

4.0 beta 8

### System information

Ubuntu Linux 22.04, Nvidia

### Issue description

Godot crashes when I click a textured CSG node

### Steps to reproduce

1. Open main.tscn
2. Click the textured CSG mesh in the viewport

### Minimal reproduction project

[CSGCrash.zip](https://github.com/godotengine/godot/files/10252314/CSGCrash.zip)

**Comment by Sslaxx** [comment]
Unable to replicate using v4.0.beta.calinou.015dc492d.

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/69859.
