### ISSUE TITLE
Implement trackpad gesture panning in the TileSet editor

### ISSUE THREAD

**Issue by iamjoeysox** [godotengine/godot#70201]
### Godot version

4.0.beta8 [45cac42c0]

### System information

macOS 13.0.1 (22A400)

### Issue description

I had similar issues on Godot 3.5, etc but I am hoping we can get the Mac trackpad to work properly within the editor. Some things work okay, but the areas I notice it the most is inside the tileset editor where on a normal mouse you can move around with MMB and zoom in with the scroll wheel. I am hoping we can allow the obvious gestures to work on the track page (pinch to zoom, swipe to pan). I have also noticed similar issues within the Animation editors.

If none of the development team has a MacBook or trackpad available, I would be willing to provide any testing, etc required or possibly even send out a trackpad for them to use. I would also be interested in helping out with a PR myself if someone could point me in the right direction as I have never worked within the Godot 4 core.

Thanks!

### Steps to reproduce

Go to a tiletset on a Mac computer or laptop with an Apple trackpad. Try to pan or zoom inside the tile editor pane.

### Minimal reproduction project

Should work inside any project.

**Comment by Calinou** [comment]
The animation editor part is already being tracked in https://github.com/godotengine/godot/issues/38237. See also https://github.com/godotengine/godot/issues/28149 and https://github.com/godotengine/godot/issues/42747.

**Comment by KoBeWi** [comment]
Related to #58014 I think.
It has a linked PR that you could try.

**Comment by iamjoeysox** [comment]
Thank you everyone! This is a great place for me to start on contributing back to the community. I'll get on those as I get time. Thanks again for all your amazing and hard work on the project.

**Comment by Calinou** [comment]
@iamjoeysox Bump :slightly_smiling_face: Can you [test](https://docs.godotengine.org/en/latest/community/contributing/testing_pull_requests.html) https://github.com/godotengine/godot/pull/62272?
