### ISSUE TITLE
MSDF font outlines are limited to 2 pixels and look worse at 2 pixels than 1

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#70211]
### Godot version

4.0.beta8

### System information

Fedora 36, Vulkan Forward Plus (or Forward Mobile), AMD Radeon RX 6900 XT

### Issue description

Multichannel signed distance field font outlines are limited to 2 pixels and look worse at 2 pixels than 1, with visible artifacts on the edges. This can be seen in the videos below where I'm adjusting the outline size at run-time:

### Rasterized DynamicFont

*Make sure to view videos in fullscreen to notice artifacts more easily.*

https://user-images.githubusercontent.com/180032/208261772-43075e1e-c45b-4431-b297-cf3fc8a2c23e.mp4

### MSDF font

https://user-images.githubusercontent.com/180032/208261744-fd750f87-cfe1-4fd2-8738-25c69100d62d.mp4

If this is a limitation of the rendering algorithm, this should be documented.

cc @bruvzg 

### Steps to reproduce

- Import a font file in the project (TTF/OTF/WOFF/WOFF2; make sure it doesn't have self-intersecting outlines for correct MSDF rendering).
- Create a Label node, assign it a custom font and set the Outline Size custom constant to a value like `12`. Also set an outline color that can be distinguished from the text itself.
- Select the font file in the FileSystem dock, then enable **Multichannel Signed Distance Field** in the Import dock. Click **Reimport**.
- Notice how the outline appears thinner. If you adjust the outline size, its appearance won't change with values greater than or equal to `3`. The outline also has a worse appearance at outline size `2` compared to outline size `1`.

### Minimal reproduction project

[msdf_font.zip](https://github.com/godotengine/godot/files/10252513/msdf_font.zip)

**Comment by bruvzg** [comment]
MSDF `pixel range` in the import settings should be about `2x` of used outline size for it to work correctly, but there's also a scaling error, so it's not using correct outline size (should be fixed by https://github.com/godotengine/godot/pull/70219).
