### ISSUE TITLE
GDScript 2.0: Cannot assign external enum as a constant

### ISSUE THREAD

**Issue by adamscott** [godotengine/godot#70213]
### Godot version

4.0.dev (10bc1d8)

### System information

Linux (Ubuntu 22.04), Vulkan, Radeon RX Vega 64 (eGPU)

### Issue description

Given the following GDScript file:
```gdscript
extends Node

const External: = preload("res://external.gd")
const MyEnum: = External.MyEnum
```

Godot will return this error:
```
SCRIPT ERROR: Parse Error: Initializer for a constant must be a constant expression.
          at: GDScript::reload **(res://main.gd:4)**
```

It should be possible to assign external enums as constants.

Seems to be a regression caused by https://github.com/godotengine/godot/pull/69907. The issue doesn't exhibit in beta 8.

Similar to #69917, which is about external inner classes.

### Steps to reproduce

1. Open minimal project
2. Open `main.gd`
3. See that Godot returns the previously mentioned error

### Minimal reproduction project

[external_enum_constant.zip](https://github.com/godotengine/godot/files/10252654/external_enum_constant.zip)

**Comment by akien-mga** [comment]
CC @rune-scape

**Comment by rune-scape** [comment]
same reason as https://github.com/godotengine/godot/issues/69917, the analyzer doesn't see enums as constants, (just their values)

**Comment by adamscott** [comment]
I'm working on a PR.
