### ISSUE TITLE
GDScript 2.0: Wrong lookup for outer things

### ISSUE THREAD

**Issue by vonagam** [godotengine/godot#70216]
### Godot version

master

### System information

MacOS 10.15.7

### Issue description

#69587 introduced regression because of [this line](https://github.com/godotengine/godot/blob/10bc1d8710e8d6a3f58f2c4f5cc09604ef3ec51f/modules/gdscript/gdscript_analyzer.cpp#L3170) in `reduce_identifier_from_base`.

First argument here is `parser->current_class`, which ignores the fact that typing can happen in a different class, even in a different file. So lookup happens not form `base` perspective, but from perspective of a place of typing.

Example:
```gdscript
class A:
  class B:
    pass

class C:
  class D:
    func hello() -> void:
      print( A.B.D ) # no warning or error from analyzer here
```

Also `get_class_node_current_scope_classes` should not be used here as it collects both class, its base classes and outer classes together in one list, but `reduce_identifier_from_base` have different logic for base classes and outer classes. So outer logic is applied now to all base classes except first direct one.

### Steps to reproduce

Copy paste code from the example and see that there is no warning in the editor.

### Minimal reproduction project

[70216.zip](https://github.com/godotengine/godot/files/10252763/70216.zip)

**Comment by akien-mga** [comment]
CC @adam-scott

**Comment by adamscott** [comment]
Can you set this MRP in your description? I usually ask for users to join a MRP even if it's a simple copy and paste because it's way easier to know if an issue is fixed or not. Hence I asked you to open this issue, I created a MRP for you.

[70216.zip](https://github.com/godotengine/godot/files/10252758/70216.zip)

**Comment by vonagam** [comment]
I mean, if it was that easy I would not have opened the issue.

Second part is important one.

Example:
```gdscript
class A:
  const Q := 'right one'

class X:
  const Q := 'wrong one'

class Y extends X:
  class B extends A:
    static func check() -> void:
      print(Q)

func _ready() -> void:
  Y.B.check()
```

Obviously, that `Q` from base class should have a priority over `Q` from base class of outer class, but it does not because of the wrong usage of `get_class_node_current_scope_classes` every class connected in any way to outer class gets checked even before first base class of the type in question is looked at. (So this is an easy example, you can come up with base class of outer class of base class of outer class and it will beat simple base class.)

**Comment by adamscott** [comment]
@akien-mga Could you reopen the issue? The issue is not fixed, finally.

**Comment by vonagam** [comment]
Another issue because of [this line](https://github.com/godotengine/godot/blob/62a50827601c479d078053b1b4c83d3b2da13236/modules/gdscript/gdscript_analyzer.cpp#L3119):
```gdscript
class Hide: # Hide is needed just to separate from other issue
  class A: pass

class B extends Hide.A:
  static func check() -> void:
    print(B.A) # no warning. runtime error.
    print(B.B) # no warning. runtime error.

func _ready() -> void:
  B.check()
```

This logic should apply only if `p_base` is null (so on implicit instance).
