### ISSUE TITLE
Godot 4b8 crashes on startup with custom shader

### ISSUE THREAD

**Issue by rcjsuen** [godotengine/godot#70224]
### Godot version

4.0b8

### System information

macOS Monterey 12.6.1 / MacBook Pro 2019 / Intel UHD Graphics 630 1536 MB

### Issue description

After assigning a Sprite2D with some shader material, my project would no longer start. Unfortunately, macOS did not generate any logs for me.

May be related to #69438 and/or #70137.

### Steps to reproduce

1. Create a new project.
2. Select the mobile low-end renderer. Set version control metadata to "None".
3. Create a new Sprite2D node.
4. Save it.
5. Drag the generated `icon.svg` as the sprite's texture.
6. Canvas Item > Material > New ShaderMaterial
7. Click the white ball.
8. Shader > New Shader
9. Save it as some file.
```
shader_type canvas_item;

uniform bool active = false;

void fragment() {
}
```
10. Shader Parameters > Active
11. Close Godot.
12. Restart it and point it at the project. It will not start.

### Minimal reproduction project

[shader-macos12-crash.zip](https://github.com/godotengine/godot/files/10252817/shader-macos12-crash.zip)

**Comment by Calinou** [comment]
> 10. Shader Parameters > Active

Do you mean the Active property should be enabled?

**Comment by rcjsuen** [comment]
> > 10. Shader Parameters > Active
> 
> Do you mean the Active property should be enabled?

@Calinou Thanks for taking a look at this. Yes, that is what I meant. We should tick the checkbox so that the property is enabled.

**Comment by bitsawer** [comment]
@rcjsuen Is this still reproducible on Mac (or any other platform)? After following the steps, everything seems to work on Windows. If anyone can still reproduce this problem, pasting any relevant console log output or errors here would help. This is a somewhat old issue, so it is possible that this has been fixed at some point.

**Comment by bitsawer** [comment]
Closing due to lack of response, I would assume that a simple bug like this has been fixed at some point similar to the two other linked issues unless it's a hardware/driver issue. Still, if anyone can reproduce this feel free to comment or reopen this issue.
