### ISSUE TITLE
property name inconsistency - surface_material_override

### ISSUE THREAD

**Issue by dmaz** [godotengine/godot#70233]
### Godot version

v4.0.beta.custom_build [d44d0cc0f]

### System information

windows 10

### Issue description

I didn't see anything mentioned about this anywhere and maybe this should just be closed but I thought it should be brought up

MeshInstance has a property called 
`surface_material_override`
but all the functions refer to it with material and override swapped like..
`get_surface_override_material()`

a bunch of the code in mesh_instance_3d is just there to deal with the issue.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/203130/208270875-a3528115-b059-4ab4-b759-46a1c36afdd7.png)

![image](https://user-images.githubusercontent.com/203130/208270890-8570dfd1-0b9d-44ce-a8c6-caa6d92d5499.png)

### Minimal reproduction project

NA

**Comment by akien-mga** [comment]
We won't resolve this for 4.0 in the end, as discussed in https://github.com/godotengine/godot/pull/70308#issuecomment-1402178378.
