### ISSUE TITLE
Ogg files missing options in advanced import menu

### ISSUE THREAD

**Issue by skyace65** [godotengine/godot#70245]
### Godot version

4.0.beta8

### System information

Windows 10

### Issue description

Despite being able to adjust the Beat Count and Bar Beats setting in the import panel of the inspector, there is no option to adjust these properties for .ogg files in the advanced importer, despite mp3 files having this option.

Here is how the advanced importer looks for an .ogg file.
![oggissue](https://user-images.githubusercontent.com/6080368/208280828-a90839fb-da3a-4153-ae8b-c99490132f3c.PNG)

And here is how it looks for an mp3 file.
![NamingIssue](https://user-images.githubusercontent.com/6080368/208280835-8521d0bb-7c9f-4a74-be1e-a6a0a88a6634.PNG)

There is a naming inconsistency between the import tab and the advanced importer. I've opened issue #70242 for that.

### Steps to reproduce

Go to the advanced importer for a .ogg audio file.

### Minimal reproduction project

N/A

**Comment by MarcusElg** [comment]
This is not true:
![image](https://user-images.githubusercontent.com/19669673/208478567-94e25d80-d808-4a7b-9fd5-6beb15b17519.png)

Those two properties are simply hidden when BPM is false.

**Comment by akien-mga** [comment]
Maybe the options could be disabled / greyed out instead of hidden, to make this clearer.
