### ISSUE TITLE
Instanced scene with `Control` root node doesn't inherent correct size property

### ISSUE THREAD

**Issue by wesley800** [godotengine/godot#70247]
### Godot version

4.0 beta8 mono on Windows 10 Vulkan;
4.0.beta.custom_build non-mono https://github.com/godotengine/godot/commit/0bb94df247a0a0c22333e2e99744fc3fd184601a on Linux X11

### Issue description

Instanced scene with `Control` (or its derivitives) as root node will get a `(0,0)` default size, if not manually overrided per instance.
~~If the `Control` node is moved to that undering a new `Node2D` root, the signal works as normal.~~

### Steps to reproduce

See the next post by @Sauermann . `$test` should also gets a non-zero default size, to properly capture `gui_events`.
~~See the attached project for details. Clicking on lower-half of either godot logo should trigger print to debug output window. But only the lower one actually reacts to mouse click, while the upper one remains silent.~~

### Minimal reproduction project

[control-guievent-test.zip](https://github.com/godotengine/godot/files/10253312/control-guievent-test.zip)

**Comment by Sauermann** [comment]
The Control node `$"/root/main/test"` doesn't receive any mouse-events, because it has a size of `(0, 0)`:
![image](https://user-images.githubusercontent.com/6299227/208289631-7a9e017f-cffc-42fc-bb6c-ac09d0d05b30.png)

Please change the size to something larger and it will receive the mouse events within the specified area.

**Comment by wesley800** [comment]
@Sauermann Any hint on why `$test` doesn't inherent size from it's template scene while `$test2` don't?

**Comment by Sauermann** [comment]
I believe, that this is a bug.
Can you please update title and description of this issue?

**Comment by wesley800** [comment]
> I believe, that this is a bug. Can you please update title and description of this issue?

Done. Thanks for your clarification.

**Comment by Sauermann** [comment]
I can confirm that the size is not inherited on non-mono-build v4.0.beta.custom_build [0bb94df24] on Linux X11.

**Comment by TheDuriel** [comment]
Note that you can, and should, use the minimum_size property to set the size of a Control node.

**Comment by Calinou** [comment]
Can you reproduce this on 3.5.1?

**Comment by KoBeWi** [comment]
This is not a bug. Your control has anchors set to "Full Rect", so it will fit inside its parent's rectangle. Node2D has no size and the control adjusts accordingly.
