### ISSUE TITLE
GPU particle flickering while the game is paused

### ISSUE THREAD

**Issue by Intervel** [godotengine/godot#70248]
### Godot version

4.0 beta 8

### System information

Windows 11,  Rtx 3090

### Issue description

GPU particle flickering while the game is paused

https://streamable.com/8r4gnk

### Steps to reproduce

look at video

### Minimal reproduction project

look at video

**Comment by AndreSacilotto** [comment]
Disabling `interpolation` or increasing the `fixed FPS` seems to solve the problem.
So it can be very well not being a bug, but a some kind of limitation.

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/65390.
