### ISSUE TITLE
Godot 4.0b8 can't open a project created with Godot 4.0b7

### ISSUE THREAD

**Issue by terraquad** [godotengine/godot#70259]
### Godot version

4.0.beta8.official

### System information

Windows 11; GPU: NVIDIA GeForce RTX 3060; Driver Version: 527.56; Rendering Backend: Vulkan

### Issue description

I tried to open my new game in Godot 4.0b8 (which I created in Godot 4.0b7) but the engine crashed.
I haven't figured the issue out yet.
Here are the logs:
![Godot 4.0b8 logs](https://user-images.githubusercontent.com/65852537/208304928-4158ac72-8abe-45d0-992b-4ab31642aaa0.png)

### Steps to reproduce

1. Open Godot 4.0b7
2. Create a new project
3. Open Godot 4.0b8
4. Try to open the project

### Minimal reproduction project

[project.zip](https://github.com/godotengine/godot/files/10258352/project.zip)

**Comment by adamscott** [comment]
Please add your Godot 4.0b7 project as the minimal reproduction project, please.

**Comment by Zireael07** [comment]
Project is unlikely to be a factor here @adamscott - it;s vkEnumeratePhysicalDevices failing.

**Comment by KoBeWi** [comment]
Can't reproduce using the given steps.
I think the project **is** relevant.

**Comment by KoBeWi** [comment]
Well, the project opens for me.
Did you update your drivers recently? Maybe you have corrupted driver?

**Comment by clayjohn** [comment]
This certainly sounds like a GPU driver update may have broken something internally. The fact that Vulkan isn't detecting any viable drivers is very suspicious.

**Comment by gemmattSD** [comment]
@KoBeWi I updated my drivers a few weeks ago, although in other applications (like Minecraft) it works perfectly fine, so it might only affect Godot.

**Comment by adamscott** [comment]
@gemmattSD Can you try projects that use Vulkan? If you have recent games with that uses a Vulkan renderer, can you try to start them?

Otherwise, you can try (Super Tux Kart)[https://supertuxkart.net] that added Vulkan support recently.

If you cannot run Vulkan games, maybe it's something with your graphic card or your drivers.

**Comment by gemmattSD** [comment]
@adamscott I tried to run Super Tux Cart and it works perfectly fine.

**Comment by adamscott** [comment]
@gemmattSD Did you run Super Tux Kart with the `--render-driver=vulkan` command line parameter?

**Comment by gemmattSD** [comment]
@adamscott I tried running it with --render-driver=vulkan and I got this: 
![supertuxkart-render-crash](https://user-images.githubusercontent.com/65852537/209714366-1a735ee6-0b0e-42d0-9d37-793ea9fa60e0.png)

**Comment by KoBeWi** [comment]
Which means it's not a Godot problem. Try beta 10, it has better OpenGL fallback.

**Comment by Calinou** [comment]
Try fully uninstalling and reinstalling your NVIDIA drivers.

**Comment by terraquad** [comment]
I tried setting DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1 to 1 (#57708 ), it works now, although I think that cannot be a permanent solution.

**Comment by terraquad** [comment]
I reinstalled Windows and now it works out of the box.
