### ISSUE TITLE
CanvasGroup affected by CanvasModulate darkens texture and increases saturation

### ISSUE THREAD

**Issue by bitbrain** [godotengine/godot#70252]
### Godot version

4.0beta (0bb94df247a0a0c22333e2e99744fc3fd184601a)

### System information

MacOS, Vulkan Forward, Metal GPUFamily Apple 7

### Issue description

Given the following scene:

<img width="238" alt="Screenshot 2022-12-18 at 11 28 53" src="https://user-images.githubusercontent.com/822035/208295886-d99ab843-6364-4888-9699-fa91f33f6741.png">

It appears that sprites rendered inside a `CanvasGroup` are rendered much darker when affected by a `CanvasModulate`. Additionally, I noticed that the saturation of sprites inside a `CanvasGroup` is increased compared to sprites outside of `CanvasGroup`:

<img width="972" alt="Screenshot 2022-12-18 at 11 25 54" src="https://user-images.githubusercontent.com/822035/208295858-a2a940ad-1a68-46e6-a1b9-c5f6b9225c80.png">

### Steps to reproduce

1. Create a Sprite
2. Create a CanvasGroup
3. Setup CanvasModulate
4. Move Sprite into CanvasGroup as a child

### Minimal reproduction project

[lighting-issue.zip](https://github.com/godotengine/godot/files/10253690/lighting-issue.zip)

**Comment by adamscott** [comment]
I confirm the issue on master (0bb94df) on my Linux laptop (Ubuntu 22.04, Radeon RX Vega 64 (eGPU))

**Comment by Calinou** [comment]
This is likely because the modulation is applied twice. The saturation issue may be caused by linear/sRGB conversion being done twice as well.

**Comment by zounw7** [comment]
I noticed that this issue is still present when using a Polygon2D. When a Polygon2D is the child of a CanvasGroup it gets modulated twice. Should I make a new bug report or can this one be reopened?
