### ISSUE TITLE
Enabling and disabling "Cinematic Preview" view option in a 3D scene leaves touchscreen controls visible, even when they were hidden previously

### ISSUE THREAD

**Issue by grizeldi** [godotengine/godot#70269]
### Godot version

v4.0.beta8.official [45cac42c0]

### System information

Ubuntu 22.04 LTS, 64bit

### Issue description

When enabling and then disabling the "Cinematic Preview" option in the editor's 3D scene viewer options...
![image](https://user-images.githubusercontent.com/13003371/208315231-210c0f23-a3c8-4b16-ae8e-3ef90f770642.png)
... I am left with the touchscreen movement controls in the bottom left and right corners:
![image](https://user-images.githubusercontent.com/13003371/208315259-b5e19027-a1ca-4a16-a5f9-56f3961d5ddf.png)

It happens no matter which scene I have open and I can't seem to find a way to get rid of the touchscreen controls afterwards.

### Steps to reproduce

1. Open any 3D scene or create a new one
2. Enable the Cinematic Preview, as shown in the issue description
3. Disable the Cinematic Preview

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
This is likely fixed by https://github.com/godotengine/godot/pull/70040

It would be great if you could test on master branch. If not, beta 9 will contain the fix and you can test again then!

**Comment by grizeldi** [comment]
I'll wait for beta 9, as I don't have a local environment set up to build from source.

**Comment by Calinou** [comment]
You can download precompiled builds of any recent pull request: https://docs.godotengine.org/en/latest/community/contributing/testing_pull_requests.html

**Comment by tinmanjuggernaut** [comment]
I've confirmed this issue is present in 4828ac6b9, and just built 36fa6fc8f. It has been fixed in the latest master.
