### ISSUE TITLE
.gitignore ignoring a bunch of code under godot/thirdparty directory

### ISSUE THREAD

**Issue by ipforums** [godotengine/godot#70276]
### Godot version

latest

### System information

X11 Manjaro

### Issue description

There's a bug .gitignore which causes a bunch of code under godot/thirdparty to be ignored.  Inserting below around line 250 fixes the issue.

```
# don't ignore x86 third party library code
!thirdparty/libtheora/x86/
!thirdparty/libtheora/x86/
!thirdparty/libvpx/vp8/common/x86
!thirdparty/libvpx/vpx_dsp/x86
!thirdparty/libtheora/x86
!thirdparty/libvpx/vp9/common/x86
!thirdparty/opus/celt/x86
!thirdparty/opus/silk/fixed/x86
!thirdparty/opus/silk/x86  

```

### Steps to reproduce

1) Cloned godot latest from github
2) Checked into local git source control
3) Pulled from local source control on Manjaro VM

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
This should have been fixed already by https://github.com/godotengine/godot/pull/69730. Is there something not done correctly in that PR?

**Comment by ipforums** [comment]
Commit ffb9f2b53f3f2fe0ad600d131ce4463610e77988 that's attached to #69730 only appears to safelist libtheora/x86
`!thirdparty/libtheora/x86/`

There's also libvpx, opus. 

```
!thirdparty/libvpx/vp8/common/x86
!thirdparty/libvpx/vpx_dsp/x86
!thirdparty/libvpx/vp9/common/x86
!thirdparty/opus/celt/x86
!thirdparty/opus/silk/fixed/x86
!thirdparty/opus/silk/x86
```

I think `!thirdparty/**/x86/` would work better since we want infinite depth not just thirdparty/[library]/x86

**Comment by Calinou** [comment]
Feel free to open a pull request for this :slightly_smiling_face:
