### ISSUE TITLE
load and parse order 

### ISSUE THREAD

**Issue by dmaz** [godotengine/godot#70274]
### Godot version

v4.0.beta.custom_build [0bb94df24]

### System information

windows 10

### Issue description

https://github.com/godotengine/godot/pull/69471 seems to have introduced a few issues in my lazy code and wondering if I need to split this into another autoload.   this has worked fine up until now.

I have a few autoloads and custom classes define by class_name.

one of the autoloads (Game.gd) has an _init function (no change if in _ready instead) that scans a directory for custom resources and then does ResourceLoader.load on what it finds.  the custom resource has a property for a PackedScene that may or may not be blank.  that PackedScene is usually extended off "ItemBase".  after 69471 I get 
`Parser Error: Could not resolve class "ItemBase"`

if I add 
`var ib:ItemBase` 
right before the loop I find the real issue which is 
`Parser Error: Cannot find member "tick" in base ""` from this line in ItemBase.gd

`nextAction = Game.tick + cooldown`

note; the item isn't instanced, it's just loaded so that code isn't run so I wouldn't expect this behavior in a dynamic language

### Steps to reproduce

I'm having a little difficulty reducing this from my main project.  working on that now

### Minimal reproduction project

NA

**Comment by akien-mga** [comment]
CC @rune-scape 

Possibly the same as #70127.

**Comment by rune-scape** [comment]
could you test it on the latest master? it does look similar to https://github.com/godotengine/godot/issues/70127, and might be fixed by https://github.com/godotengine/godot/pull/70275

**Comment by dmaz** [comment]
the latest commit is giving me errors
```
[ 96%] Linking Program bin\godot.windows.editor.x86_64.exe ...
[ 98%] e'4.ex6ta
[100%] progress_finish(["progress_finish"], [])
[100%] scons: *** [bin\godot.windows.editor.x86_64.exe] Error 1104
scons: building terminated because of errors.
```

**Comment by dmaz** [comment]
looks fixed!  
thanks!

**Comment by dmaz** [comment]
I no longer getting the error but I'm now have odd issues that I have to track down

**Comment by dmaz** [comment]
found it.
this issue is fixed!  Sweet!  Thanks

my other issue is a change with dictionaries and vector2 keys that I have to sort out.
