### ISSUE TITLE
max_light_per_object default value is set to 8 in Godot4

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#70282]
### Godot version

3.5.1 stable, 4.0 Beta8

### System information

Win10, Nvidea765M

### Issue description

Almost two years ago, this PR https://github.com/godotengine/godot/pull/43606 made the `max_lights_per_object` configurable in the Project Settings and changed the default to 32 lights because users often reported issues with the low limit of 8 lights. I remember Juan tweeting about it saying something along the lines of there was no good reason for having this hard-coded limit.

In Godot3.X ever since, [the soft limit is now 32](https://docs.godotengine.org/en/stable/classes/class_projectsettings.html#class-projectsettings-property-rendering-limits-rendering-max-lights-per-object), but in Godot4.0 [the soft limit default value is again 8](https://docs.godotengine.org/en/latest/classes/class_projectsettings.html#class-projectsettings-property-rendering-limits-opengl-max-lights-per-object), which again [seems to cause issues and confusion](https://www.reddit.com/r/godot/comments/zpfw9x/models_surfaces_randomly_stop_rendering_if_too/).

Similarly, the `max_renderable_lights` default value is also drastically reduced: [Godot3: 4096](https://docs.godotengine.org/en/stable/classes/class_projectsettings.html#class-projectsettings-property-rendering-limits-rendering-max-renderable-lights), [Godot4: 32](https://docs.godotengine.org/en/latest/classes/class_projectsettings.html#class-projectsettings-property-rendering-limits-opengl-max-renderable-lights)

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
Yes, this is intentional. The OpenGL renderer in Godot 4 is aimed for low end and mobile devices. The GLES3 renderer in Godot 3.x is aimed at modern desktop devices. To keep acceptable performance on low end and mobile devices we have kept the default soft limit low. 

The reddit post you link to isn't even using the OpenGL renderer so this project setting is totally unrelated to their issue.
