### ISSUE TITLE
Using a singleton for dictionary presets is causing unexpected interconnectivity

### ISSUE THREAD

**Issue by pisumdev** [godotengine/godot#70288]
### Godot version

4.0.beta8

### System information

OS: Arch Linux x86_64, Kernel: 6.0.12-zen1-1-zen

### Issue description

I'm trying to use a dictionary in a singleton to set preset data on a universal character scene.
I expect after initially setting the preset the characters data is not linked, but if I change the data of one character it changes in the other too.

Here is my code, but I have also attached a project file below.

**preset_singleton.gd**
```
extends Node

var equipment_preset = {
	"hat": "crown"
}
```
**character.gd**
```
extends Node

@export var current: bool
var helmet_equipped = false

var equipment

func _ready():
	equipment = PresetSingleton.equipment_preset
	if (current):
		equipment["hat"] = "helmet"
		helmet_equipped = true
```

### Steps to reproduce

Download my project below and hit run, check the Equipment dictionary on the two CharacterBody3D instances under "Remote". Both will have a "helmet" equipped, but the helmet equip code only ran under "CurrentCharacter".

Alternatively here are the steps to create the project:

Create **preset_singleton.gd**, and set it to autoload in project settings.
Create a CharacterBody3D scene with **character.gd** attached.
Create a new Node3D scene and instantiate two instances of the CharacterBody3D scene.
On one of the CharacterBody3D instances enable the exposed bool called "Current".

### Minimal reproduction project

[CharacterPresetBug.zip](https://github.com/godotengine/godot/files/10256519/CharacterPresetBug.zip)

**Comment by Chaosus** [comment]
Dictionaries are always passed by reference.
To get a copy of a dictionary which can be modified independently of the original dictionary, use [duplicate](https://docs.godotengine.org/en/latest/classes/class_dictionary.html#class-dictionary-method-duplicate).
