### ISSUE TITLE
set_server_relay_enabled(false) has chicken/egg error which may be a bug

### ISSUE THREAD

**Issue by gau-veldt** [godotengine/godot#70301]
### Godot version

4.0.beta7

### System information

Windows 7 "Radeon RX560 Series" forward_plus/mobile/gl_compatibility

### Issue description

We seem to have a chicken/egg problem with not being able to shut off automatic client relaying.
I would like to avoid the O(n squared) bandwidth complexity (each client of n clients relays to (n-1) others)

The chicken side of the problem:
```
# A scene with a simple Node root set to the following script
extends Node
func _ready():
	multiplayer.set_server_relay_enabled(false)
```

this raises error: _ready: Cannot change the server relay option while the multiplayer peer is active.
  <C++ Error>    Condition "multiplayer_peer.is_valid() && multiplayer_peer->get_connection_status() != MultiplayerPeer::CONNECTION_DISCONNECTED" is true.
  <C++ Source>   modules/multiplayer/scene_multiplayer.cpp:613 @ set_server_relay_enabled()
this is "error: no longer an egg"

Any sooner (like trying to set in _init) and the egg side of the problem occurs (access thru nullPtr, in other words: "error: not yet a chicken")

### Steps to reproduce

# A scene with a simple Node root set to the following script
```
extends Node
func _ready():
	multiplayer.set_server_relay_enabled(false)
```

### Minimal reproduction project

n/a

**Comment by Calinou** [comment]
cc @Faless
