### ISSUE TITLE
GridMap (3D) collision settings missing collision_priority property

### ISSUE THREAD

**Issue by vermeeren** [godotengine/godot#70302]
### Godot version

4.0.dev (e780dc332a0a3f642a6daf8548cb211d79a2cc45)

### System information

Linux

### Issue description

(Originate from https://github.com/godotengine/godot/pull/64343#issuecomment-1343598929)

Since #64343 physics bodies have a `collision_priority` property, which can be used to for example prevent bodies being pushed through walls. However `GridMap` is lacking this property, meaning it's not possible to set `collision_priority` for level geometry made using it.

I'm not sure if 2D TileMap has a similar issue as I have not checked it and have no experience with it.

### Steps to reproduce

Create a `GridMap` node and observe the lack of `collision_priority` property.

![Screenshot_20221219_162929](https://user-images.githubusercontent.com/5957454/208461643-bff3ea60-d465-4861-9969-765dd5d3f625.png)

Compared to, for example, a `RigidBody3D`, which does have the property.

![Screenshot_20221219_163150](https://user-images.githubusercontent.com/5957454/208461822-e973e058-e626-44d6-a438-c9385242efac.png)

### Minimal reproduction project

N/A

**Comment by smix8** [comment]
GridMap adds multiple collision shapes for the cells inside an octant (default 8 cells) to a single collision body using the PhysicsServer directly so there is no individual `collision_priority` for each cell available as priority can only be set per body and not per shape.

Those properties in the GridMap inspector are for the entire GridMap and GridMap is not inheriting CollisionObject3D or GeometryInstance3D where a lot of those individual properties like `collision_priority` or `material_override` would come from.

Individual cell item properties would need to be added in the MeshLibrary but not sure how possible that is for collision_priority as it requires a larger rework of the current physics part of GridMap.

**Comment by vermeeren** [comment]
@smix8 I'm not sure about the internals but from a user point of view I think it would be sufficient to implement `collision_priority` inside the GridMap properties in a "global" fashion for that entire GridMap, just like is already the case with collision layers and masks.

I believe the way GridMap works is already on the basis that "a single GridMap has the same collision settings for everything created with it", and that is perfectly fine for most use cases.

For example: If you create level geometry (walls, ceilings, etc) with GridMap, having all of those in some high `collision_priority` is perfectly fine.

**Comment by smix8** [comment]
A global priority for the entire GridMap would be no problem to add.

**Comment by vermeeren** [comment]
@smix8 That would be fantastic, thanks for your quick replies!

I read that somewhere down the line GridMap does likely need some major reworking, like what happened to 2D TileMap already, but I definitely consider it very usable already and a nice tool to work with if you take its current limitations into account. Finer-grained and/or per-block-type properties seem like something interesting for a rework, but definitely a massive amount of work.

Cheers
