### ISSUE TITLE
AnimationNodeStateMachinePlayback won't restart non-looping animations when using travel()

### ISSUE THREAD

**Issue by stickzman** [godotengine/godot#70318]
### Godot version

4.0beta8

### System information

Windows 10

### Issue description

When using an AnimationTree with AnimationNodeStateMachinePlayback and using the travel() function, the docs say it will teleport to a state that does not have a transition.  When traveling/teleporting to the node using a non-looping animation, this works as intended the first time.  After the animation is complete, calling is_playing() still returns true and attempting to travel to the node again does not reset/play the animation again.  You need to manually call start() on the animation to play it again.

I would expect travel to play the animation from the start when traveling to it again.

### Steps to reproduce

Create an AnimationPlayer and added 2 animations to it (idle and attack, etc).  Set attack to non-looping.
Create an AnimationTree and add an AnimationNodeStateMachine as the Tree Root.
Add the previously created AnimationPlayer to the AnimationTree.
Inside the AnimationTree panel, add both animations as nodes in the state machine.
Set idle as the starting node.  Do not set any transitions to the attack animation.
With the Play Mode set to "Travel", play the attack animation, then idle, then attempt to play attack again.  Notice how the attack animation remains stuck at the final frame.

### Minimal reproduction project

Follow the above steps to create a MRP.  Let me know if you think this post needs an uploaded project.

**Comment by TokageItLab** [comment]
I think this is expected behavior, not a bug. Currently, StateMachine and NodeTransition do not allow restarts in the same State. Yeah, I agree it is inconvenient, but I think we need a proposal to improve the convenience in https://github.com/godotengine/godot-proposals.
