### ISSUE TITLE
Cannot get constructor of inner class

### ISSUE THREAD

**Issue by IceflowRE** [godotengine/godot#70319]
### Godot version

v4.0.beta9.official [e780dc332]

### System information

Windows 10

### Issue description

```gdscript
extends RefCounted

class InnerClass:
    extends RefCounted

# does not work
var foo: Callable = InnerClass.new
```

Getting the constructor of an inner class is not longer possible, this was possible in beta8.

### Steps to reproduce

See above.

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
CC @adamscott @rune-scape
