### ISSUE TITLE
enum typed variable do not throw warning when assigning string

### ISSUE THREAD

**Issue by ajreckof** [godotengine/godot#70323]
### Godot version

4.0.beta8 

### System information

MacOS Monterey 12.4 puce M1 Pro

### Issue description

Enum typed variables accept at runtime string while it is giving an error in the editor and when assigned at runtime it does not assign the value associated with the key contained in the string.

### Steps to reproduce

create an enum with two values
create a variable typep by this enum
create a variable with a string with the name of the second value
assign the string variable to the enum typed variable
when running there is no error but the enum is assigned the value 0

### Minimal reproduction project

[Archive.zip](https://github.com/godotengine/godot/files/10263384/Archive.zip)

**Comment by TokageItLab** [comment]
Same issue with #69570

**Comment by anvilfolk** [comment]
Could no longer reproduce on master `2a04b18d37` :)

![image](https://user-images.githubusercontent.com/1133892/208757255-f8b36bd4-982d-4119-9890-7dc1be60551c.png)

So looks like some PR since beta 8 fixed it :)

Also just checked this out with beta 9 and it appears fixed there also!
