### ISSUE TITLE
Resizing the game window dramatically drops the FPS on Linux on a very simple project

### ISSUE THREAD

**Issue by hakro** [godotengine/godot#70320]
### Godot version

v4.0.beta9.official.e780dc332

### System information

PopOs 22.04, NVIDIA Corporation GP107GLM [Quadro P1000 Mobile] (P1000 [Zbook Studio x360 G5 mobile workstation]), Nvidia drivers version 525.60.11, Vulkan Forward+ renderer

### Issue description

I created a very simple new 3D project using the Forward+ renderer.
It only contains a floor and 3 rigid body boxes, and the default light and world environment.

When running the project, the FPS count takes a bit of time to get to 60, but it gets there.

![2022-12-19_23-04](https://user-images.githubusercontent.com/3624853/208534911-4261eb41-14e1-40fe-9dcd-daeb0bfc5934.png)

However, when resizing the game window, the FPS progressively starts to drop, the bigger the window gets.
When the window is maximized, it can drop to 30-40 FPS, even if nothing is moving in the scene anymore.

![2022-12-19_23-05_1](https://user-images.githubusercontent.com/3624853/208535569-a5003224-9f57-4765-b0df-fc23eca211a8.png)

Performance drop is less noticeable on the other renderers (mobile and OpenGL).

### Steps to reproduce

Just run a simple 3D project on Linux, and resize the game window, then try to maximize it

### Minimal reproduction project

[godot4-test.zip](https://github.com/godotengine/godot/files/10263145/godot4-test.zip)

**Comment by Sauermann** [comment]
Looks like Vulkan has also other performance related issues with resizing windows: https://github.com/godotengine/godot/issues/68313#issuecomment-1304889675.

**Comment by hakro** [comment]
Changing the project setting display/window/size/mode to fullscreen gives even worse performance.

Sadly this would make the Vulkan renderer pretty much unusable on linux without incurring some kind of performance hit.
Resizing is always needed, it won't be possible to have one specific window size fit everyone's screen.
Are there any known work arounds? Other than waiting for OpenGL to be fully implemented :)
Currently it lacks at least shadow rendering.

Cheers !

**Comment by Zireael07** [comment]
You are on a mobile graphics card. The FPS drop with a bigger screen is indicative of the card having a bad fill rate. I don't think a move to OpenGL will help with that

**Comment by akien-mga** [comment]
> You are on a mobile graphics card. The FPS drop with a bigger screen is indicative of the card having a bad fill rate. I don't think a move to OpenGL will help with that

It would, just like using the Vulkan *mobile* renderer would help on a mobile graphics card :) That's what it's made for.
This card simply confirms that the high end Forward+ renderer is not meant for use on low-end/mobile chipsets.

There might be ways to optimize further and gain some FPS but this chipset shouldn't be expected to deliver high end graphics at a stable 60 FPS.

**Comment by Calinou** [comment]
You can decrease 3D resolution scaling in the project settings to gain some performance, but if you want the best possible performance at a scaled resolution, nothing will beat actually decreasing the screen resolution (as scaling is an expensive operation on low-end GPUs).

**Comment by Calinou** [comment]
Closing per the above comment.
