### ISSUE TITLE
Button font is rendered incorrectly when using pixel art TTF font

### ISSUE THREAD

**Issue by boruok** [godotengine/godot#70327]
### Godot version

v4.0.beta.custom_build [dcb3754db]

### System information

Ubuntu 22.10, GTX1060, Vulkan

### Issue description

tried to use pixel-art `.ttf font` on my project. Looks like `Button` font renders incorrectly compared to other buttons (checkbutton, link...)

below is how it looks, from top to bottom `Button`, `CheckButton`, `LinkButton`, `MenuButton`. All have same font with same size. Only `Button` glitched

![Screenshot from 2022-12-20 11-27-46](https://user-images.githubusercontent.com/36783322/208567772-97245a2a-94a6-4667-bb16-e3c5dc0a0ce2.png)

### Steps to reproduce

1. open attachment
2. try to change button text

### Minimal reproduction project

[New Game Project.zip](https://github.com/godotengine/godot/files/10264223/New.Game.Project.zip)

**Comment by Calinou** [comment]
I can confirm this on v4.0.beta.custom_build [b6e06038f] (Linux).

![image](https://user-images.githubusercontent.com/180032/210014286-bc4fdc10-e297-450c-8252-f46874a571b9.png)

**Comment by bruvzg** [comment]
Button style box or/and text alignment is likely resulting in a non integer horizontal offset, which is in general fine.

Disable `subpixel positioning` in the font import settings, it's not suitable for pixel art fonts (but can improve rendering of the small sizes of the usual vector fonts).

**Comment by bruvzg** [comment]
Since the particular font in the MRP is a vector font, but with all vertices aligned to the pixel grid and only line segments, it's not possible to detect if it's a pixel art font automatically. But we probably should auto disable subpixel positioning for true fixed size bitmap TTFs.

**Comment by boruok** [comment]
@bruvzg thanks! solved.

**Comment by Calinou** [comment]
Reopening, as this needs to be documented on [Using fonts](https://docs.godotengine.org/en/latest/tutorials/ui/gui_using_fonts.html).
