### ISSUE TITLE
Impossible to only override materials without overriding material 0.

### ISSUE THREAD

**Issue by cridenour** [godotengine/godot#70330]
### Godot version

v4.0.beta9.official [e780dc332]

### System information

Windows 10

### Issue description

After #70176 any scene with a surface override in a slot greater than 0 that doesn't have an override in 0, will have all of their overrides put in the first few slots. 

This isn't a one time break that can be fixed, it will be overwritten every time - even if the editor never touches the file.

Only known workaround is to fill the overrides with the base material.

### Steps to reproduce

Create a MeshInstance3D with more than one material.
Override material in slot 1. (Usually breaks immediately)
Save scene.
Load scene (or run project).

### Minimal reproduction project

[mesh-override.zip](https://github.com/godotengine/godot/files/10265184/mesh-override.zip)

**Comment by clayjohn** [comment]
Are you saying for example that if you had a surface override like the following:
Surface override 0 - empty
Surface override 1 - mat1
Surface override 2 - mat2

You would end up with the following:

Surface override 0 - mat1
Surface override 1 - mat2
Surface override 2 - empty

**Comment by cridenour** [comment]
@clayjohn Yes, that is correct. I countered it locally by commenting out lines 59-65 of `mesh_instance_3d.cpp` but I have no idea of the impact of that.

**Comment by fracteed** [comment]
I ran into a similar issue where I have a mesh with 4 material slots. By default they are all empty and in game the 4th slot has a material added by gdscript, but it was nowhere to be seen when playing. If I went back and had the first 3 slots filled with a material, the 4th one would show up in game when added by script.

**Comment by clayjohn** [comment]
Taking a look now, the compatibility code is indeed to blame. Here it is for reference:
https://github.com/godotengine/godot/blob/98d871b6f9c97485ff01eae5e01c8a0177563554/scene/3d/mesh_instance_3d.cpp#L56-L65

As you can see in the comment we are assuming that the ``_set()`` method is only called when the scene is loaded, however, it appears for the material overrides it is used any time they are set from the editor as well. So the code completely breaks. I will look into a fix. Worst case scenario we will have to remove the compatibility code. It is there to ensure compatibility with projects created in master during a brief window between beta 8 and beta 9 so breaking compatibility may be acceptable
