### ISSUE TITLE
WebGL: Basis Universal textures are rendered as black

### ISSUE THREAD

**Issue by TyounanMOTI** [godotengine/godot#70341]
### Godot version

4.0.dev (dcb3754)

### System information

Windows 11, Chrome 108.0.5359.125 (Official Build), GeForce RTX3080 (driver 527.56)

### Issue description

When exporting WebGL build, the materials using Basis Universal textures are rendered as black.
May be same issue as #67558.

Intended (VRAM Compressed texture):
![image](https://user-images.githubusercontent.com/173001/208637739-50557b5a-8026-4d54-bf7c-23268c0268bd.png)
![image](https://user-images.githubusercontent.com/173001/208637942-06e3c5e7-dd7b-4443-a2ed-7cf6cc6a05e4.png)

Reproduced (Basis Universal texture):
![image](https://user-images.githubusercontent.com/173001/208637832-e65ef1bc-0717-4516-ac96-377ee2dbd2b5.png)
![image](https://user-images.githubusercontent.com/173001/208638000-625dd414-8a3f-4fcf-a042-d4df2794c354.png)

### Steps to reproduce

1. Open attached minimal reproduction project.
2. Export for Web.
3. Run in Chrome.

### Minimal reproduction project

[basis_universal_rendered_as_black.zip](https://github.com/godotengine/godot/files/10267320/basis_universal_rendered_as_black.zip)

**Comment by Calinou** [comment]
One of the output formats supported by Basis Universal is ETC2, which is supported in WebGL 2.0. Therefore, it should be feasible to make it work in theory.

**Comment by TyounanMOTI** [comment]
It shows error message `failed! on level 0` in console of chrome developer tools.
Also, when I call `basis_universal_unpacker_ptr` with a PackedByteArray of .basis file prefixed with BASIS_DECOMPRESS_RGB as following, it shows same error `failed! on level 0`.

```C++
// image.h
	Error load_basis_from_buffer(const Vector<uint8_t> &p_array);

// image.cpp
Error Image::load_basis_from_buffer(const Vector<uint8_t> &p_array) {
	ERR_FAIL_NULL_V_MSG(
			basis_universal_unpacker_ptr,
			ERR_UNAVAILABLE,
			"The Basis module isn't enabled. Recompile the Godot editor or export template binary with the `module_basis_universal_enabled=yes` SCons option.");
	return _load_from_buffer(p_array, basis_universal_unpacker_ptr);
}

void Image::_bind_methods() {
...
	ClassDB::bind_method(D_METHOD("load_basis_from_buffer", "buffer"), &Image::load_basis_from_buffer);
...
}
```

```gdscript
func _on_http_request_request_completed(result: int, response_code: int, _headers: PackedStringArray, body: PackedByteArray):
	if result != HTTPRequest.RESULT_SUCCESS:
		push_error("HTTP request failure: ", response_code)
		return
	
	# push BASIS_DECOMPRESS_RGB to front
	for _i in range(4):
		body.insert(0, 0)
	body.encode_u32(0, 1)
	
	var image := Image.create(256, 256, true, Image.FORMAT_DXT5)
	image.load_basis_from_buffer(body)
	$MeshInstance3D.mesh.surface_get_material(0).albedo_texture = ImageTexture.create_from_image(image)
```

**Comment by Yasei-no-otoko** [comment]
> One of the output formats supported by Basis Universal is ETC2, which is supported in WebGL 2.0. Therefore, it should be feasible to make it work in theory.

ETC/PVRTC/ASTC on WebGL is not supported by Chromium and Firefox on Windows. (Sadly, regardless of GPU driver's support)

https://toji.github.io/texture-tester/

(If the current implement is ETC2 premise) The smarter decoding process is to change the transcoding format to match the capability of the browser. (regardless of the OS)

**Comment by TyounanMOTI** [comment]
On Windows Chrome, requested format to transcode is `basist::transcoder_texture_format::cTFBC7_M6_OPAQUE_ONLY`.
That worked fine with my PR on Chrome, but we should check for other browsers and OS.

**Comment by Calinou** [comment]
> ETC/PVRTC/ATC on WebGL is not supported by Chromium and Firefox on Windows. (Sadly, regardless of GPU driver's support)

That test only tests for ETC*1*, not ETC2.
