### ISSUE TITLE
Canvas Group not merging sprites has in viewPort

### ISSUE THREAD

**Issue by jonSP12** [godotengine/godot#70348]
### Godot version

4.0 beta9

### System information

windows10 vulkan

### Issue description

When selecting texture Linear in Canvas Group, the effect is applied to all childern sprites individually, and not has an entire image, has in viewPort... In viewPort seems to work fine

Canvas Group
**Linear**
![canvasLinear](https://user-images.githubusercontent.com/77213594/208682591-66f9877e-69e9-4f21-9b58-bfe41fab0a96.png)

**Nearest**
![canvasNear](https://user-images.githubusercontent.com/77213594/208682673-ad5263c5-4410-404a-9acb-a6a34f3a6c1d.png)

---------------//-------//--------
viewPort
**Linear**
![viewPortLinear](https://user-images.githubusercontent.com/77213594/208682790-2a94ab78-9306-4516-85d1-074dff98d898.png)

**Nearest**
![viewPortNear](https://user-images.githubusercontent.com/77213594/208682850-5845cda0-1878-4925-9308-93854a774680.png)

### Steps to reproduce

create canvas Group add 2 childern pixel Sprites connect the 2, set texture to linear... Ive added an outline shader. 
(SCREEN_TEXTURE) ,  (SCREEN_UV ) for the canvas group
(TEXTURE) ,  (UV ) for the viewPort

### Minimal reproduction project

canvasGroupTest
[canvasGroupTest.zip](https://github.com/godotengine/godot/files/10268995/canvasGroupTest.zip)

**Comment by akien-mga** [comment]
For the record, I closed this on behalf of the Code of Conduct team, as the OP was banned due to harassing contributors. They're restricted from further interacting so this issue cannot progress. If someone confirms that the issue is still reproducible, you can open a new issue.
