### ISSUE TITLE
Const arrays are not read-only, despite the description in the docs

### ISSUE THREAD

**Issue by dalexeev** [godotengine/godot#70349]
### Godot version

v4.0.beta9.official [e780dc332]

### System information

Kubuntu 22.10

### Issue description

The docs says:

> bool is_read_only() const
>
> Returns true if the array is read-only. See set_read_only(). Arrays are automatically read-only if declared with const keyword.

But

```gdscript
@tool
extends EditorScript

const A = [1, 2, 3]

func _run() -> void:
    const B = [4, 5, 6]
    print(A.is_read_only()) # false
    print(B.is_read_only()) # false
```

I'm not sure if this is a bug in the documentation or in the implementation.

### Steps to reproduce

See above.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/30212.
