### ISSUE TITLE
Changing the editor's theme does not affect the scrollable property headers in the inspector immediately

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#70356]
### Godot version

2a04b18d37de6c6e621db5a9dfd1cd0da5ccb015

### System information

Windows 11

### Issue description

Just a minor editor bug, which is nicely to be fixed.

![bug](https://user-images.githubusercontent.com/3036176/208732309-8cd47b21-60fc-4eb2-bdc8-8bde451628b4.gif)

### Steps to reproduce

^^

### Minimal reproduction project

Too easy to reproduce

**Comment by akien-mga** [comment]
Just FYI, I removed it from the 4.0 roadmap as this is not critical at this stage to release 4.0-stable. But if someone wants to fix it before the stable release, that's welcome of course.

**Comment by akien-mga** [comment]
Reopening as #70381 was reverted.

**Comment by rcorre** [comment]
Is this still expected to be fixed in 4.3? I'm using "follow system theme" on `hyprland`, and I see this for a few seconds after switching the system theme with godot 4.3:

![Image](https://github.com/user-attachments/assets/26305fac-b4c4-4deb-b242-fc6d0d95f95f)
