### ISSUE TITLE
blend mode mask is missing in Light2D node

### ISSUE THREAD

**Issue by arabgamedev** [godotengine/godot#70358]
### Godot version

4.0 beta 9

### System information

windows 8.1 GLES3

### Issue description

why mask mode is removed or missing in Light2D nodes
![image](https://user-images.githubusercontent.com/66444993/208734480-b406006b-5384-45fb-b35b-9010fa21258d.png)

### Steps to reproduce

add Light2D node
select blend mode

### Minimal reproduction project

_

**Comment by Calinou** [comment]
This is expected. The Mask Light2D mode is replaced by the CanvasItem Clip Children property, which makes clipping more convenient to perform.

**Comment by arabgamedev** [comment]
> This is expected. The Mask Light2D mode is replaced by the CanvasItem **Clip Children** property, which makes clipping more convenient to perform. (The CanvasGroup node may also be relevant to your needs, depending on what you need to achieve.)

but if i want mask like 2d shadows i can't do it using just clip children
what i need is the shadows as mask like in 3.x

**Comment by arabgamedev** [comment]
> This is expected. The Mask Light2D mode is replaced by the CanvasItem **Clip Children** property, which makes clipping more convenient to perform. (The CanvasGroup node may also be relevant to your needs, depending on what you need to achieve.)

did you see the effect in among us when you can't see player behind the wall
you can do this effect in godot 3 using mask light2D

**Comment by Calinou** [comment]
> did you see the effect in among us when you can't see player behind the wall

This should be done server-side to prevent cheats from revealing player positions.

**Comment by arabgamedev** [comment]
> > did you see the effect in among us when you can't see player behind the wall
> 
> This kind of culling should be done server-side to prevent cheats from revealing player positions.

what is the harm of bring back this blend mode?

**Comment by PhilWun** [comment]
@arabgamedev I also miss this feature, because I wanted to the same thing. To get the same effect you can write a shader to calculate the shadows with the new SDF functions and make the texture transparent in the shadow. These are the resources I used:
- https://docs.godotengine.org/en/latest/tutorials/shaders/shader_reference/canvas_item_shader.html#sdf-functions 
- https://www.ronja-tutorials.com/post/037-2d-shadows/

**Comment by Wllwl2** [comment]
> @arabgamedev Я тоже скучаю по этой функции, потому что я хотел того же самого. Чтобы получить тот же эффект, вы можете написать шейдер для вычисления теней с помощью новых функций SDF и сделать текстуру прозрачной в тени. Это те ресурсы, которые я использовал:
> 
> * https://docs.godotengine.org/en/latest/tutorials/shaders/shader_reference/canvas_item_shader.html#sdf-functions
> * https://www.ronja-tutorials.com/post/037-2d-shadows/

Hi. I am another person with this problem. Can you please post how you worked it out here?
