### ISSUE TITLE
Pressing Escape closes project settings window when listening for input

### ISSUE THREAD

**Issue by kristin-meshka** [godotengine/godot#70379]
### Godot version

Godot Engine v4.0.beta9.official

### System information

Windows 10 

### Issue description

In the input map setting page on "Filter by event . . .", when you press Escape, it will both register and close the window.
The key stock will be there when you open the input map settings page again, but i don't think it should close the window when listening for input.

### Steps to reproduce

Open project settings
Click input map tab
Click "Filter by event . . ."
Press Esc

The window will close, but when you open the settings tab again it will be there.

### Minimal reproduction project

N/A

**Comment by kristin-meshka** [comment]
I just tested it a little further and found that when this window is used it is not blocking things like Caps lock from also registering to the computer.
Example : pressing caps lock when in the input listening field will both capture the key and let the caps lock on your keyboard enable/disable.

**Comment by Sauermann** [comment]
> I just tested it a little further and found that when this window is used it is not blocking things like Caps lock from also registering to the computer.

Feel free to create a separate bug-report for this issue, so that it doesn't get forgotten. Usually it is best to make a single bug-report for a single problem.
