### ISSUE TITLE
Image to ImageTexture toTextureRect.texture not working.

### ISSUE THREAD

**Issue by ndee85** [godotengine/godot#70393]
### Godot version

4.0 Beta 9

### System information

Windows 10, Windows 11

### Issue description

Hi,
I am creating an Image object. From there I generate an ImageTexture and try to feed it into a TextureRect via:
tex_rect.texture = img_tex

This is working perfectly fine in godot 3.5.x but Godot 4 Beta 9 and below I get an error which tells me **Invalid Image**.

I have prepared a very simple project with 3 sections which can be commented in and out. Would be great if you can have a look.

### Steps to reproduce

Load the attached project and press F5. Typically a red square of size 100x100 should appear. But it doesn't.

### Minimal reproduction project

Load the attached project and press F5. Typically a red square of size 100x100 should appear. But it doesn't.
[ImageBug.zip](https://github.com/godotengine/godot/files/10276939/ImageBug.zip)

**Comment by KoBeWi** [comment]
Check the warnings. Both `create()` and `create_from_image()` are static and return a new instance.
