### ISSUE TITLE
using custom mouse cursor will make my PC goes brrrrrrrrrrrrrrr when closing

### ISSUE THREAD

**Issue by Intervel** [godotengine/godot#70390]
### Godot version

4.0 beta 9

### System information

Windows 11,  Rtx 3090

### Issue description

changing this settings will make my PC goes brrrrrrrrrrrrrrr when closing the game

![1](https://user-images.githubusercontent.com/86478025/208845829-a43691c3-c039-4a4a-973c-daaece4049c8.png)

i feel like its going to exploded! 

what happens?

### Steps to reproduce

try to change the mouse cursor

### Minimal reproduction project

try to change the mouse cursor

**Comment by lawnjelly** [comment]
> changing this settings will make my PC goes brrrrrrrrrrrrrrr

Can you be more specific? Is this a sound? (I have visions of this being a dance move) :smile:

**Comment by Calinou** [comment]
@Intervel Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by Intervel** [comment]
mybad, i will add it now.

**Comment by Intervel** [comment]
ok apparently, after closing the game, my cursor will appear loading like this :

![1](https://user-images.githubusercontent.com/86478025/209094077-c8436e83-6535-420f-919a-54e8dce8fd5f.png)

and it lagged for 1 to 2 seconds.

**Comment by Zireael07** [comment]
You said you will add the MRP, but haven't.

The "loading" cursor in Windows can have many causes... most likely is unloading stuff from memory as Godot closes

**Comment by Intervel** [comment]
@Zireael07 my bad,  i think you are right about unloading memory. i just noticed that.

im sorry
