### ISSUE TITLE
Changing renderer doesn't show restart editor prompt from Settings

### ISSUE THREAD

**Issue by Skyvastern** [godotengine/godot#70401]
### Godot version

3.5.1

### System information

Windows 10, Nvidia GTX 1650

### Issue description

Changing renderer from GLES3 to GLES2 or vice-versa can be done in two ways as of now -
1. Going to `Project Settings -> Quality -> Driver -> Driver Name`, and setting relevant option.
2. Selecting renderer from top-right corner of the Godot editor.

If we change renderer from Project Settings then no prompt is shown to restart Godot editor. Whereas, if we change renderer via method 2, then the prompt shows up where it asks us to restart Godot editor.

So one way should be standardized. I think restart should be made compulsory, as its hard to tell whether new renderer is in effect or not if we change through method 1.

### 1. Change renderer through Project Settings
![3](https://user-images.githubusercontent.com/52847458/208930233-b054828f-8e2c-433b-97f2-298614eb4db9.png)

### 2. Change renderer through top-right corner of the Godot editor.
![1](https://user-images.githubusercontent.com/52847458/208930370-efcec6d9-5f48-4492-a2fc-2bd918438792.png)
![2](https://user-images.githubusercontent.com/52847458/208930393-f6093de9-3b2c-43fa-aaea-84593a70775f.png)

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
Fixed by #70412.
