### ISSUE TITLE
GPU particle only working first time

### ISSUE THREAD

**Issue by Intervel** [godotengine/godot#70400]
### Godot version

4.0 beta 9

### System information

Windows 11,  Rtx 3090

### Issue description

i dont know what happens here

it just freezed

https://streamable.com/6iauq9

load a scene for 2nd time will make the particle freezing.

![1](https://user-images.githubusercontent.com/86478025/208916198-40ece272-f9cb-4f36-834a-5af7f2afcf47.png)

i set the proccess to always, when pause

### Steps to reproduce

above

### Minimal reproduction project

above

**Comment by DissonantVoid** [comment]
I want to take a look at this issue but I don't quite understand, the video you linked doesn't exactly tell us much, what is the issue? are the particles pausing when they shouldn't? and what do you mean by 2nd time?
also can you please provide a Minimal reproduction project

**Comment by Calinou** [comment]
I've noticed GPUParticles sometimes emit less frequency or even stop emitting altogether after some time. This is more common with particles that have Explosiveness increased above 0.

**Comment by Intervel** [comment]
i was unable to reproduce this issues in new project. i think something wrong in my code. 

mybad
