### ISSUE TITLE
Beta 8 breaks PhysicsShapeQueryParameters3D set_exclude

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot#70425]
### Godot version

4.0 beta 8

### System information

Windows 10

### Issue description

An old function that worked fine in beta 6:
```
var space: PhysicsDirectSpaceState3D = get_world_3d().direct_space_state as PhysicsDirectSpaceState3D
	
	var params: = PhysicsShapeQueryParameters3D.new()
	params.set_shape(col_stand.shape)
	params.set_transform(global_transform)
	params.set_exclude([self])
	params.collision_mask = collision_mask
```
But since upgrading to beta 8, I get an error:
`Parser Error: Invalid argument for "set_exclude()" function: argument 1 should be Array[RID] but is Array[res://og_player/player.gd].`

This is fixed when changing `params.set_exclude([self])` to `params.set_exclude([self.get_id()])` but it seems like a regression.

### Steps to reproduce

As above.

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
I noticed this too and thought that #65170 was a cause, but I didn't investigate. The PR was merged way before beta6 though, so if it was working correctly as you claim, fault lies somewhere else probably.

**Comment by rburing** [comment]
This is the result of https://github.com/godotengine/godot/pull/69017 and https://github.com/godotengine/godot/pull/69060 (follow-ups to the PR mentioned above) making the physics API more strongly typed. With the latter PR the usage is now also documented: see [`exclude`](https://docs.godotengine.org/en/latest/classes/class_physicsshapequeryparameters3d.html#class-physicsshapequeryparameters3d-property-exclude).

I guess we can also add this information to the blog post of the first beta that included this change.

**Comment by elvisish** [comment]
> making the physics API more strongly typed

Doesn't this change make things needlessly complicated? Since the only part that's going to be required in `params.set_exclude([])` would be nodes, it's much more convenient for Godot to "smartly" get the RIDs from the node references, otherwise the user has to write `get_id()` a bunch of times for every node which seems to go against the whole point of GDScript being a simpler language.

**Comment by KoBeWi** [comment]
Yeah I don't really like it either. The method should take nodes or auto-convert, because users are always dealing with nodes, not RIDs in their code. If changing the type is a problem, we could add an intermediate method and bind it instead.

**Comment by Zireael07** [comment]
> or auto-convert,

Pleeease

**Comment by akien-mga** [comment]
The 4.0 release is imminent and this is now too late to do further compat breaking changes, so closing.
