### ISSUE TITLE
Input Map(joypad): both axis starts with -0.707107 when the joystick is connected.

### ISSUE THREAD

**Issue by derickfelix** [godotengine/godot#70427]
### Godot version

4.0.beta8.official [45cac42c0]

### System information

Windows 10

### Issue description

I defined `move_forward` as `Joypad Axis 1 -` and `move_left` as `Joypad Axis 0 -`.

When I run the project both keys starts and keep with the value `-0.707107`  until these keys are pressed:
![image](https://user-images.githubusercontent.com/20743967/209020076-cf25d69e-01ec-41b7-b9dc-b2f2e35b57fb.png)

### Steps to reproduce

Just run the project, with a joystick connected.

### Minimal reproduction project

[JoystickProblem.zip](https://github.com/godotengine/godot/files/10282354/JoystickProblem.zip)

**Comment by KoBeWi** [comment]
Can't reproduce
![image](https://user-images.githubusercontent.com/2223172/209030506-bb286aa1-d2be-4fca-b13c-e9d65fe330fe.png)
likely a hardware issue. Try increasing deadzones.

**Comment by derickfelix** [comment]
Maybe, I changed the deadzone to `0.1` and `1`. Still having the problem. The `Input.getActionStrength("move_forward")` and `Input.getActionStrength("move_left")` starts with `1`. When I move forward (axis 1) this problem stops, but `move_left` keeps with `1`, so I have to move both axis at least one time to stop this behavior.

Well, since it couldn't be reproduced by another person, I'll close this issue, until it happens to someone else.
