### ISSUE TITLE
glb import: automatic "-col" suffix collision, not sliding when using character move_and_slide()

### ISSUE THREAD

**Issue by derickfelix** [godotengine/godot#70426]
### Godot version

4.0.beta8.official [45cac42c0]

### System information

Windows 10

### Issue description

I created a mesh on blender named the object with the "-col" suffix for automatic collision, and exported as .glb into godot. The player gets stuck on the wall, there is no sliding.

### Steps to reproduce

The wall on the front, the player slides normally:
![image](https://user-images.githubusercontent.com/20743967/209017817-5e02f97f-09e5-4134-b444-e466bb5ccdfe.png)

But the walls from the glb, the player gets stuck:
![image](https://user-images.githubusercontent.com/20743967/209018051-7b83a2b7-9a2b-4c6d-9671-d2f4970dd973.png)

### Minimal reproduction project

[AutomaticColNotWorking.zip](https://github.com/godotengine/godot/files/10282287/AutomaticColNotWorking.zip)

**Comment by timothyqiu** [comment]
The place you'll stuck seems to be using the wrong normal (red in the screen shot).

![ksnip_20221222-201354](https://user-images.githubusercontent.com/372476/209132351-ba532d59-e6e5-4cdb-8887-2acef56586a7.png)

**Comment by derickfelix** [comment]
Flipping the normals solved it

**Comment by and-rad** [comment]
Since the problem was with the flipped normals, can this issue be closed then?
