### ISSUE TITLE
Selecting methods in script editor methods list does not position them consistently when scrolling, if Word Wrap option is enabled.

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#70438]
### Godot version

v3.5.2.rc1.official [f5f0543ae]

### System information

w10 64

### Issue description

You can see it in the video.
I select a function and the editor places it at the bottom of the screen, other times it places it at the top, and other times it places it in the center.

https://youtu.be/4yqvRaNwZes

### Steps to reproduce
Thanks to user Tetane we know that the problem happens when:
The setting "text_editor/appearance/word_wrap" is set to true.
See the video.

### Minimal reproduction project

...

**Comment by akien-mga** [comment]
I can't seem to reproduce the issue with 3.5.2.rc1 on Linux. For me it's consistently scrolling to have the selected function as the first line:
![image](https://user-images.githubusercontent.com/4701338/209111493-f87cac87-1fbf-4c74-a8de-a44227cced55.png)

The only exception is when the functions are towards the end of the file, if scrolling past end of file is disabled.

Do you have any custom editor settings values set that could affect this?

**Comment by Torguen** [comment]
I'm not sure I understand.
The editor misplaces the function even though there is plenty of room at the bottom of the script to position the function correctly in the center.

In the video I show this when I scroll down showing that there is enough space.

Can you give me more information about that option? I have to translate everything we write into my language and that makes it a bit difficult to understand.

**Comment by akien-mga** [comment]
Yes I see the bug in your video, I'm just unable to reproduce it. So there must be a configuration difference between your Godot version and mine, or something in your script/project which triggers the bug.

What I'm suggesting is that your review your Editor Settings in the "Text Editor" category, to see if there's any setting that you configured to a value which is not the default one (so it shows with a revert arrow). One of these settings may cause the issue.

![image](https://user-images.githubusercontent.com/4701338/209116241-6d91b5d9-a98d-4ca9-bbf9-e7b84c8ab9c3.png)

It could also be a general theme setting (font size, line spacing, etc.), or editor scale (mine is 100%, maybe you have a hidpi display with 150% or 200% scaling which is not properly handled for scrolling).

Alternatively, you could share your `%APPDATA%/Godot/editor_settings-3.tres` file to see if others can reproduce the issue with the same configuration.

**Comment by Torguen** [comment]
Well, my configuration is this but I think that none of those options should be involved in the problem we are dealing with.

![Captura1](https://user-images.githubusercontent.com/19652075/209117869-f613bb8f-5a33-4363-9e49-4051efd0e309.PNG)

**Comment by akien-mga** [comment]
I just showed one screen of potential options that could be related, but it's really everything which could impact this. If you can share your `editor_settings-3.tres` I can see if it triggers the issue for me.

**Comment by Torguen** [comment]
Could it be something related to the script?.

[editor_settings-3.zip](https://github.com/godotengine/godot/files/10286430/editor_settings-3.zip)

**Comment by Torguen** [comment]
Could it be something related to the script?

I can share the editor_settings file but won't I expose compromised information about android, you know, the keys or passwords for debug, release, etc...

**Comment by Tetane** [comment]
I was able to reproduce the issue in v3.5.1 by changing the setting "text_editor/appearance/word_wrap" to true.

**Comment by akien-mga** [comment]
> I can share the editor_settings file but won't I expose compromised information about android?, you know, the keys or passwords for debug, release, etc...

The Android release key/password should be in the `export_presets.cfg` in theory, so it should be fine. The editor settings have the default debug user/password names, if yours are different from the default `androiddebugkey` and `android` you might want to remove them from the file. You can copy the file, open it in a text editor and remove lines which you don't want to share.

**Comment by Torguen** [comment]
> I was able to reproduce the issue in v3.5.1 by changing the setting "text_editor/appearance/word_wrap" to true.

Yes, I have that option activated, so it could be due to the activation of that option.


Ok so this is the file.
[editor_settings-3.zip](https://github.com/godotengine/godot/files/10286526/editor_settings-3.zip)

**Comment by akien-mga** [comment]
The issue also seems reproducible in latest `3.x` and `master`.

**Comment by Torguen** [comment]
Why did you label this as "enhancement"?
I consider this to be a problem (bug) because the script editor does not correctly position the function declaration as it does when you don't have the "word_wrap" option enabled.

I honestly don't think this is an improvement, this is a solution to a real problem.

**Comment by Torguen** [comment]
This is very annoying, it also happens when you switch between the script editor and the 2D editor, as you can see in this video.

https://user-images.githubusercontent.com/19652075/225869788-b136be26-d74c-4d5c-9358-a0f2c526a38a.mp4

**Comment by Torguen** [comment]
Still in 3.6 beta 3
