### ISSUE TITLE
changing navigation really fast will make it out of bound/list

### ISSUE THREAD

**Issue by Intervel** [godotengine/godot#70436]
### Godot version

4.0 beta 9

### System information

Windows 11,  Rtx 3090

### Issue description

https://streamable.com/a949eh

no idea what happens here

why does it went out of list?

### Steps to reproduce

https://streamable.com/a949eh

### Minimal reproduction project

https://streamable.com/a949eh

**Comment by timothyqiu** [comment]
Please upload a Minimal Reproduction Project so it's easier to troubleshoot (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug).
