### ISSUE TITLE
C# crash: Condition "!match" is true

### ISSUE THREAD

**Issue by firebelley** [godotengine/godot#70449]
### Godot version

v4.0.beta10.mono.official [d0398f62f]

### System information

Windows 11

### Issue description

I am experiencing a runtime crash in my game which logs the following error:

```
ERROR: FATAL: Condition "!match" is true.
   at: ~CSharpInstance (modules/mono/csharp_script.cpp:2015)
Fatal error. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Godot.NativeInterop.NativeFuncs.godotsharp_internal_refcounted_disposed(IntPtr, IntPtr, Godot.NativeInterop.godot)
   at Godot.Object.Dispose(Boolean)
   at Godot.Object.Finalize()
```
There is no other output alongside this error.

I am using several `RefCounted` objects throughout my game and the error seems to be related. I'm using `RefCounted` 
 primarily as a way to pass my own C# objects as signal arguments.

~~My project is fairly complex so I'm having a hard time isolating the issue. The crash doesn't happen immediately, but rather it usually happens after a minute or so of playing the game. It also seems quite inconsistent - sometimes I can play for several minutes before the crash. There's probably a very specific combination of events I need to identify in order to reproduce the issue consistently.~~

~~I know this report isn't super helpful but I've been trying to isolate the issue for the past several hours with no luck. I figured I'd log it for now and update with an MRP if/when I find out how to reproduce.~~

I've now uploaded an MRP below. I still haven't been able to identify the exact cause but I am hoping the MRP is stripped down enough to make debugging easier.

I have confirmed the crash happens in betas 8 and 9 as well.

### Steps to reproduce

Unknown

### Minimal reproduction project

[Crash MRP.zip](https://github.com/godotengine/godot/files/10304593/Crash.MRP.zip)

Run the MRP for ~30 seconds and observe the crash. Also, you can remove `WanderTravelDefinition` from the `EnemyFlyingOrbBullet` to observe that the crash no longer happens.

**Comment by firebelley** [comment]
I just tested the project in Beta 8, and experienced the same crash.

**Comment by firebelley** [comment]
@raulsntos I have updated the issue with an MRP which is a stripped down version of my project. You can run the project for ~30 seconds to observe the crash.

In the `EnemyFlyingOrbBullet`, you can remove the `WanderTravelDefinition` node and run again, and observe that the crash no longer happens. Let me know if I can be of any assistance to further identify the issue.

**Comment by raulsntos** [comment]
I have tested the MRP, as reported it crashes in this line:

https://github.com/godotengine/godot/blob/e780dc332a0a3f642a6daf8548cb211d79a2cc45/modules/mono/csharp_script.cpp#L2015

And the responsible seems to be the freeing of an instance of `GunStats`.

This is my backtrace:

```
[1] /usr/share/dotnet/shared/Microsoft.NETCore.App/6.0.12/libcoreclr.so(+0x4dccfe) [0x7fffd4cdccfe] (??:0)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7ffff7c42520] (??:0)
[3] CSharpInstance::~CSharpInstance() (??:0)
[4] void memdelete<ScriptInstance>(ScriptInstance*) (??:0)
[5] Object::~Object() (??:0)
[6] RefCounted::~RefCounted() (??:0)
[7] void memdelete<RefCounted>(RefCounted*) (??:0)
[8] /media/raulsntos/Data/Godot/src/godot/bin/godot.linuxbsd.editor.dev.x86_64.llvm.mono(godotsharp_internal_refcounted_disposed+0x143) [0x55555a9a1ea3] (??:0)
[9] [0x7fff5bdbd55d] (??:0)
```

Maybe we are forgetting to add the instance to the `script->instances` HashSet. However, I checked the `GunStats` constructor, it should be using `CSharpLanguage::tie_native_managed_to_unmanaged` or `CSharpLanguage::tie_user_managed_to_unmanaged` and both of them add the instance to the script as far as I'm concerned.

I don't think the object would be freed before the constructor finishes executing. There's also locks around insert and remove so I don't think it's an issue with multi-threaded execution.

**Comment by Voidheart** [comment]
I just came across this thread, was curious have tried to Pool/reuse the new created objects? You can implement method to return the reference of the pooled object and apply any changes incase lets say you got a power-up and the GunStats changed you can modify
