### ISSUE TITLE
depth_draw_opaque not working in Shader when ALPHA is used

### ISSUE THREAD

**Issue by norrath-hero-cn** [godotengine/godot#70445]
### Godot version

Godot Engine v3.5.1.stable.official.6fed1ffa3

### System information

Windows 10 x64
OpenGL ES 3.0 Renderer: NVIDIA GeForce GTX 960/PCIe/SSE2
OpenGL ES 2.0 Renderer: NVIDIA GeForce GTX 960/PCIe/SSE2

### Issue description

Incorrect depth when camera near parallel to plane mesh instance in Godot 3.5.1, both gles 3 and gles 2

gles 3

https://user-images.githubusercontent.com/73905273/209146857-7a30601e-a8c5-4dfe-b69d-bdd63809b8ca.mp4

gles 2

https://user-images.githubusercontent.com/73905273/209147241-c37b4e7b-a0fe-457f-a129-97595027f48c.mp4

and we can see when camera touch the plane mesh, the object depth suddenly disordered

https://user-images.githubusercontent.com/73905273/209150662-f7b53981-8e90-46e0-8e02-03487c09ff09.mp4

### Steps to reproduce

Please use the minimal reproduction project

### Minimal reproduction project

[demo.zip](https://github.com/godotengine/godot/files/10287360/demo.zip)

**Comment by Seubmarine** [comment]
Your texture alpha is plugged in the alpha channel of your brick material, I don't know enough about shaders if it's the good things to do but disconnecting the alpha channel remove the problem.

**Comment by Zireael07** [comment]
Transparent object sorting has various issues. If you used alpha anywhere in the material, that mesh is now going through the transparent pipeline and subject to said issues.

**Comment by norrath-hero-cn** [comment]
> Transparent object sorting has various issues. If you used alpha anywhere in the material, that mesh is now going through the transparent pipeline and subject to said issues.

Just confirmed this by capture some frame in intel gpa

visual shader use alpha output socket cause depth mask disabled when rendering
![image](https://user-images.githubusercontent.com/73905273/209217795-66d06069-ec33-4136-ad59-6c3c2da1e9d3.png)
![image](https://user-images.githubusercontent.com/73905273/209217839-73ca0f38-f11c-473c-be92-88fc47c82497.png)
![image](https://user-images.githubusercontent.com/73905273/209218002-63e21ed1-413f-4c5c-a219-e689f641d1a2.png)

when not using alpha output socket, depth mask is enabled
![image](https://user-images.githubusercontent.com/73905273/209218154-849f71cc-8780-4793-adee-318b52e74209.png)
![image](https://user-images.githubusercontent.com/73905273/209218260-1030c5e5-3397-4e79-9177-2235e7457012.png)

is this some sort of bug or deliberately design? the depth mask can be enabled by force when set depth draw to always
![image](https://user-images.githubusercontent.com/73905273/209219845-7a61cca3-c9c9-4127-b204-a8ed1b0c7910.png)
![image](https://user-images.githubusercontent.com/73905273/209218985-7cac21a8-bd3a-4e27-8871-6ee88a43489a.png)

if this is the way visual shader works I will close this issue, and please documenting this in the [visual shader document](https://docs.godotengine.org/en/stable/tutorials/shaders/visual_shaders.html), or user will search anwsers everytime when miss the point

**Comment by norrath-hero-cn** [comment]
Just confirmed depth_draw_opaque is not working in Shader when ALPHA is used by convert visual shader to shader then manually add the flag

![image](https://user-images.githubusercontent.com/73905273/209224175-af9825b4-3f96-4bdb-ab54-3a3e6a6eee0c.png)

**Comment by clayjohn** [comment]
This isn't a bug. You are just seeing an edge case that highlights the limitations of alpha sorting. You should be using the ``depth_draw_alpha_prepass`` mode. 

Also, with respect to the last comment, you don't need to specify ``depth_draw_opaque`` as it is the default mode if nothing is specified in the shader
