### ISSUE TITLE
`popup_centered_ratio` is based on the screen and not the window when subwindows are not embeded.

### ISSUE THREAD

**Issue by HolonProduction** [godotengine/godot#70451]
### Godot version

4.0.beta9

### System information

Windows 10

### Issue description

When using `Window.popup_centered_ratio` without embeded subwindows the popup is placed at the screen center and not the center of the parent window. Also the size is calculated based on screen size and not window size.

### Steps to reproduce

- open the mrp
- run it
- move the window to the side of the screen
- the popup will apear at the center

### Minimal reproduction project

[popup_tests.zip](https://github.com/godotengine/godot/files/10288572/popup_tests.zip)

**Comment by YuriSizov** [comment]
I think that might be by design.
