### ISSUE TITLE
C#: Init-only properties causes illegal code to be generated

### ISSUE THREAD

**Issue by Fabien2S** [godotengine/godot#70479]
### Godot version

v4.0.beta9.mono.official [e780dc332]

### System information

Windows 11

### Issue description

Using the `init` property keyword in a `Node` causes illegal code to be generated by the `ScriptPropertiesGenerator` generator

```csharp
public partial class TestNode : Node
{
    public Node SomeNode { get; init; }
}
```

![image](https://user-images.githubusercontent.com/18100602/209359537-a6b0ab89-c351-4f56-b11a-0e31c819bf83.png)

The causes of this problem is probably [this if statement](https://github.com/godotengine/godot/blob/d0398f62f08ce0cfba80990b21c6af4181f93fe9/modules/mono/editor/Godot.NET.Sdk/Godot.SourceGenerators/ScriptPropertiesGenerator.cs#L171) which checks if the property is not read-only, but does not check for init-only.

### Steps to reproduce

1. Create a project
2. Create a C# Script
3. Add `public Node SomeNode { get; init; }`
4. Build the project
5. Check the error

### Minimal reproduction project

N/A

**Comment by raulsntos** [comment]
We only support writable properties, the source generator checks if the property is readonly (`IPropertySymbol.IsReadOnly`) and should report diagnostic `GD0103`. This only checks that there's no set accessor but `init` is a set accessor so we have to also check that the set accessor is `init` (`IMethodSymbol.IsInitOnly`).
