### ISSUE TITLE
Context menu not showing on right mouse click

### ISSUE THREAD

**Issue by AlaynCuervoRavelo** [godotengine/godot#70484]
### Godot version

v3.5.1.stable.official --6fed1ffa3-- para Android

### System information

Redmi 9A, Android 10, MIUI 12.0.20, Mediatek Helio G25, 4G RAM, 64G internal

### Issue description

When I use a mouse to work with the Godot Engine, right-clicking to open a context menu doesn't show anything.

Best regards

### Steps to reproduce

Nothing else, apart from what is mentioned

### Minimal reproduction project

Nothing else, apart from what is mentioned

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/60031.

cc @m4gr3d

**Comment by m4gr3d** [comment]
This is addressed in the Godot 3.6 upcoming beta.
The 3.6 beta builds will be made available fairly soon.
