### ISSUE TITLE
Editor crashes when SubViewport size is set to zero by sliding the values

### ISSUE THREAD

**Issue by rbarongr** [godotengine/godot#70481]
### Godot version

v4.0.beta9.official [e780dc332]

### System information

macOS Ventura 13.0.1 (Intel), Radeon Pro 580 8 GB

### Issue description

When setting the size of a SubViewport (that is inside the corresponding SubViewportContainer) to zero, the editor crashes instantly.

**But it only happens when I set the size of the SubViewport by sliding the values.**

You can see what happens in this video:

https://user-images.githubusercontent.com/91340577/209363880-503d3dff-80e1-4e9e-bb57-d059fdbfeed0.mp4

At the end of the video you can see the crash message of macOS reading: _Godot quit unexpectedly._

If I write the number zero (or any negative) to the values of the SubViewport size, the crash doesn't happens.

### Steps to reproduce

1. Add a SubViewportContainer
2. Add a SubViewport as a child of the SubViewportContainer
3. Set the size of the SubViewport to zero **by sliding** the X or the Y value.

### Minimal reproduction project

1. Open the project
2. Go to the Control.tscn scene
3. Select the SubViewport node
4. Slide the X or Y values of the size to zero

[SubViewportCrash.zip](https://github.com/godotengine/godot/files/10296101/SubViewportCrash.zip)

**Comment by rbarongr** [comment]
I tried to slide the values of the SubViewport size in v4.0.beta17.official [c40020513] and I can't slide it, so... it doesn't crash.

I think is because of #67331.

So yeah, this issue could be closed, but I'm not sure. Not being able to slide the values should be another issue?

**Comment by rbarongr** [comment]
False alarm, I was trying to set a SubViewport size with a SubViewportContainer parent set to 'stretch', so I couldn't modify the size values. 😅

**The crash still happens.**

**Comment by Sauermann** [comment]
> Not being able to slide the values should be another issue?

I agree: #72556
