### ISSUE TITLE
C# version of Vector2.AngleToPoint is off by PI

### ISSUE THREAD

**Issue by irwiss** [godotengine/godot#70499]
### Godot version

4.0.beta10.mono.official (d0398f62f)

### System information

Windows 10

### Issue description

It appears C# version of `AngleToPoint` wasn't updated when #43072 was applied to GDScript's `angle_to_point`

https://github.com/godotengine/godot/blob/5784bf1be0cdf409a115556bf6c54f78f3d454ef/modules/mono/glue/GodotSharp/GodotSharp/Core/Vector2.cs#L140-L143

For reference GDScript version appears to be 

https://github.com/godotengine/godot/blob/5784bf1be0cdf409a115556bf6c54f78f3d454ef/core/math/vector2.cpp#L84-L86

### Steps to reproduce

Run the included repro project, it has a scene with 2 scripts attached to nodes;
One node has GDScript attached, with `print(Vector2.ZERO.angle_to_point(Vector2(1, 0)))`
The other node has C# script attached with `GD.Print($"{Vector2.Zero.AngleToPoint(new Vector2(1f, 0f))}");`

You'll see two lines in the log, the one coming from C# script will be off by PI
```
0
3.1415927
```

### Minimal reproduction project

[AngleToPoint_bug.zip](https://github.com/godotengine/godot/files/10297409/AngleToPoint_bug.zip)

**Comment by Calinou** [comment]
cc @raulsntos

**Comment by raulsntos** [comment]
OP is right that https://github.com/godotengine/godot/pull/43072 changed the method in Core and the C# implementation is now outdated. Should be trivial to update if anyone wants to open a PR; otherwise, I can take care of it. Just want to make sure it's fixed for 4.0 since this breaks compatibility.
