### ISSUE TITLE
SSR doesn't do anything on 4.0 beta 6

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot#70507]
### Godot version

4.0 beta 6

### System information

Windows 10, Vulkan, RTX 3060 (466.81)

### Issue description

Enabling SSR on WorldEnviroment does nothing when used with a texture with the material's metallic settings on high.

### Steps to reproduce

- Add a material with metallic set to full and roughness set to low.
- Turn on SSR in the WorldEnviroment.
- Nothing happens to the texture.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Can you reproduce this in 4.0.beta10 on a new project?

**Comment by elvisish** [comment]
It seems to work on 10 actually:
[ssr test.zip](https://github.com/godotengine/godot/files/10297705/ssr.test.zip)
