### ISSUE TITLE
MultiplayerSynchronizer and RPCs lead to errors on the server when a client disconnects

### ISSUE THREAD

**Issue by Zorbn** [godotengine/godot#70505]
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

4.0-beta9

### System information

Windows 11

### Issue description

Using the MultiplayerSynchronizer node, or sending RPCs every frame, leads to errors in the server's console when there are multiple clients and one of them disconnects. It seems that increasing the Replication Interval of the MultiplayerSynchronizer or sending RPCs less frequently makes the problem less likely to occur, but it still will happen occasionally.

I wasn't able to find an existing open issue for this, which is strange given how easy the issue is to encounter (at least in my testing). So, I may have been searching with the wrong keywords.

Here is an example of the type of errors produced:
```
ERROR: Condition "peer > 0 && !connected_peers.has(peer)" is true.
   at: _process_sys (modules/multiplayer/scene_multiplayer.cpp:317)
ERROR: Node not found: "World/Players/70163785" (relative to "/root").
   at: (scene/main/node.cpp:1359)
ERROR: Failed to get cached path: World/Players/70163785.
   at: get_cached_object (modules/multiplayer/scene_cache_interface.cpp:246)
ERROR: Invalid packet received. Requested node was not found.
   at: (modules/multiplayer/scene_rpc_interface.cpp:228)
ERROR: Condition "peer > 0 && !connected_peers.has(peer)" is true.
   at: _process_sys (modules/multiplayer/scene_multiplayer.cpp:317)
```

### Steps to reproduce

The problem generally seems to occur under the following scenario:
1. Use a MultiplayerSynchronizer node to synchronize a variable that the client has authority over. Alternatively, send a consistent stream of RPCs from one of the clients. (Both of these happen in the example). 
2. Start a server, connect multiple clients.
3. Close one of the clients.
4. Errors will appear in the console of the server.

Repeating these steps multiple times may lead to slightly different output, but the general errors are the same.

### Minimal reproduction project

[Networking.zip](https://github.com/godotengine/godot/files/10297623/Networking.zip)

Start one instance of the game with the "--server" flag.
Start two or more other instances without the server flag, these are the clients.
Close one of the clients.
Errors are then printed in the server's console.

**Comment by Zorbn** [comment]
This also occurs in 4.0-beta10

**Comment by Zorbn** [comment]
In my opinion these cases (at least for my use case) shouldn't be considered errors, so I made the following changes locally.

<details>
  <summary>Code diff</summary>

```
diff --git a/modules/multiplayer/scene_cache_interface.cpp b/modules/multiplayer/scene_cache_interface.cpp
index f0da4f9dfc..40b2c59d70 100644
--- a/modules/multiplayer/scene_cache_interface.cpp
+++ b/modules/multiplayer/scene_cache_interface.cpp
@@ -241,10 +241,7 @@ Object *SceneCacheInterface::get_cached_object(int p_from, uint32_t p_cache_id)
 	ERR_FAIL_COND_V_MSG(!F, nullptr, vformat("ID %d not found in cache of peer %d.", p_cache_id, p_from));
 
 	PathGetCache::NodeInfo *ni = &F->value;
-	Node *node = root_node->get_node(ni->path);
-	if (!node) {
-		ERR_PRINT("Failed to get cached path: " + String(ni->path) + ".");
-	}
+	Node *node = root_node->get_node_or_null(ni->path);
 	return node;
 }
 
diff --git a/modules/multiplayer/scene_multiplayer.cpp b/modules/multiplayer/scene_multiplayer.cpp
index 5042a0502d..2824fa418f 100644
--- a/modules/multiplayer/scene_multiplayer.cpp
+++ b/modules/multiplayer/scene_multiplayer.cpp
@@ -314,7 +314,10 @@ void SceneMultiplayer::_process_sys(int p_from, const uint8_t *p_packet, int p_p
 			bool should_process = false;
 			if (get_unique_id() == 1) { // I am the server.
 				// Direct messages to server should not go through relay.
-				ERR_FAIL_COND(peer > 0 && !connected_peers.has(peer));
+				// Don't continue if the peer is no longer connected.
+				if (peer > 0 && !connected_peers.has(peer)) {
+					return;
+				}
 				// Send relay packet.
 				relay_buffer->seek(0);
 				relay_buffer->put_u8(NETWORK_COMMAND_SYS);
diff --git a/modules/multiplayer/scene_rpc_interface.cpp b/modules/multiplayer/scene_rpc_interface.cpp
index a7e29dfcc7..d9f67adbcd 100644
--- a/modules/multiplayer/scene_rpc_interface.cpp
+++ b/modules/multiplayer/scene_rpc_interface.cpp
@@ -159,11 +159,7 @@ Node *SceneRPCInterface::_process_get_node(int p_from, const uint8_t *p_packet,
 
 		NodePath np = paths;
 
-		node = root_node->get_node(np);
-
-		if (!node) {
-			ERR_PRINT("Failed to get path from RPC: " + String(np) + ".");
-		}
+		node = root_node->get_node_or_null(np);
 		return node;
 	} else {
 		// Use cached path.
@@ -225,7 +221,9 @@ void SceneRPCInterface::process_rpc(int p_from, const uint8_t *p_packet, int p_p
 	}
 
 	Node *node = _process_get_node(p_from, p_packet, node_target, p_packet_len);
-	ERR_FAIL_COND_MSG(node == nullptr, "Invalid packet received. Requested node was not found.");
+	if (node == nullptr) {
+		return;
+	}
 
 	uint16_t name_id = 0;
 	switch (name_id_compression) {

```

</details>

Personally, I don't think there should be errors logged due to using NetworkSynchronizer in what I believe is the intended way. RPCs sent to nodes that have just been destroyed by a client disconnecting should also be simply ignored in my opinion. However, I don't have enough context on the networking system as a whole to be sure that the changes I made here don't cause Godot to ignore actual errors. There might also be a very good reason to have errors in these situations that I'm not aware of.

**Comment by SantiagoSastre** [comment]
This still happens in 4.0.2, and I agree with @Zorbn that there shouldn't be errors logged in the console.

**Comment by SantiagoSastre** [comment]
I'm not really experienced in networking or the inner workings of godot, but would it be possible to keep track of recently freed nodes until the other peers realize the node doesn't exist any longer?

**Comment by jtnicholl** [comment]
I can confirm this is still present in latest master (68193bee9 as of writing).

**Comment by OrlanRod** [comment]
I get this error on 4.1.1.

**Comment by ana-rchy** [comment]
can also confirm on 4.1.1

**Comment by HGCollier** [comment]
Any update on this?

**Comment by Calinou** [comment]
> Any update on this?

To my knowledge, nobody has found a solution for this yet as we don't know why this is occurring.

**Comment by mhilbrunner** [comment]
The error log in the OP can be paraphrased as `"SceneMultiplayer has received an update for node World/Players/70163785 by a player that is not connected (anymore); update discarded"`.

Most of the time, these logs are normal for networking. Sometimes, you are going to send an update, not knowing that either the pertaining player has already left, or the last updates by that leaving player are going to arrive after they alread left, and so on. Things have latency after all, and order of updates isn't always guaruanteed.

So most of the time, these are harmless (if you do not encounter any actual breakage). But sometimes, they can be indicative of a larger problem. If you get a lot of these suddenly after a change where you didn't before, it is likely you got some ordering wrong somewhere, or some node paths are not matching up between clients, and so on.

So while it is noisy, sometimes it is useful. We may be able to trim them a bit, and may want to consider adding a way to silence them (optionally or by default).

**Comment by tjulioh** [comment]
Same problem here, I'm creating an inventory system in the online game and when I collect an object the same is queue_free(), but the error persists almost every time I collect/throw away the object.

**Comment by Braxtogoo** [comment]
Can confirm this problem exists in v4.2.1.stable.official [b09f793f5] as well.

**Comment by homhomhomhomhom** [comment]
I don't know if this will work for player synchronization, but for my bullets I currently bypassed it by setting the rootnode of the multiplayersynchronizer in the ready function to the parent where I know it would be.

func _ready():
	$MultiplayerSynchronizer.set_root_path("../BulletSpawn")

so far haven't had the issues anymore (altho, limited testing)
However, the error spam when despawning the bullets went away after I added it like that

**Comment by Suero152** [comment]
Can confirm this problem still exists in v4.2.1.stable.arch_linux , Happens when I disconnect a player and queue_free the scene where those MultiSync are.

**Comment by makeryangcom** [comment]
Can confirm this problem still exists in Godot Engine v4.3.rc1.official.e343dbbcc 

![1722511842492](https://github.com/user-attachments/assets/74bdc6a0-3d5d-4bc2-9608-fc936200c48a)

**Comment by makeryangcom** [comment]
Should I continue to provide feedback and the MRP here?

**Comment by makeryangcom** [comment]
[BugTest.zip](https://github.com/user-attachments/files/16478185/BugTest.zip)

I have prepared a minimal error example. The usage is as follows:

1、Export server.exe and run the server with "server.exe --headless".
2、Run two client windows in the editor, ensuring both clients join the game.
3、Close any one of the client windows, and you will see the related error information on the server.

This error occurs in multiplayer scenarios. As the number of clients increases, more error messages will appear.

**Comment by PiCode9560** [comment]
> The error log in the OP can be paraphrased as `"SceneMultiplayer has received an update for node World/Players/70163785 that does not exist (anymore) by a player that is not connected (anymore); update discarded"`.
> 
> Most of the time, these logs are normal for networking. Sometimes, you are going to send an update, not knowing that either the pertaining player has already left, or the last updates by that leaving player are going to arrive after they alread left, and so on. Things have latency after all, and order of updates isn't always guaranteed.
> 
> So most of the time, these are harmless (if you do not encounter any actual breakage). But sometimes, they can be indicative of a larger problem. If you get a lot of these suddenly after a change where you didn't before, it is likely you got some ordering wrong somewhere, or some node paths are not matching up between clients, and so on.


To reduce the chance of getting the error. Maybe add a way for the client to tell the server that they are disconnecting, so that the server don't have to print the error when they disconnected without a problem.

**Comment by makeryangcom** [comment]
> > The error log in the OP can be paraphrased as `"SceneMultiplayer has received an update for node World/Players/70163785 that does not exist (anymore) by a player that is not connected (anymore); update discarded"`.
> > Most of the time, these logs are normal for networking. Sometimes, you are going to send an update, not knowing that either the pertaining player has already left, or the last updates by that leaving player are going to arrive after they alread left, and so on. Things have latency after all, and order of updates isn't always guaranteed.
> > So most of the time, these are harmless (if you do not encounter any actual breakage). But sometimes, they can be indicative of a larger problem. If you get a lot of these suddenly after a change where you didn't before, it is likely you got some ordering wrong somewhere, or some node paths are not matching up between clients, and so on.
> 
> To reduce the chance of getting the error. Maybe add a way for the client to tell the server that they are disconnecting, so that the server don't have to print the error when they disconnected without a problem.

I think many methods have been exhaustively explored for this error, but at least for now, I haven't found a good way to prevent it. If I have 1,000, 10,000, or 100,000 players, these errors will be serious issues, even disasters, for the server logs. I have already spent three days searching for solutions to this error, and it has been very frustrating.

his issue has actually existed for several years, which is quite surprising to me. It seems that this problem is not so easy to solve.

**Comment by makeryangcom** [comment]
> > The error log in the OP can be paraphrased as `"SceneMultiplayer has received an update for node World/Players/70163785 that does not exist (anymore) by a player that is not connected (anymore); update discarded"`.
> > Most of the time, these logs are normal for networking. Sometimes, you are going to send an update, not knowing that either the pertaining player has already left, or the last updates by that leaving player are going to arrive after they alread left, and so on. Things have latency after all, and order of updates isn't always guaranteed.
> > So most of the time, these are harmless (if you do not encounter any actual breakage). But sometimes, they can be indicative of a larger problem. If you get a lot of these suddenly after a change where you didn't before, it is likely you got some ordering wrong somewhere, or some node paths are not matching up between clients, and so on.
> 
> To reduce the chance of getting the error. Maybe add a way for the client to tell the server that they are disconnecting, so that the server don't have to print the error when they disconnected without a problem.

Since it's a normal log, why mark it as 'ERROR'? This makes us think it's a mistake!

**Comment by makeryangcom** [comment]
> > The error log in the OP can be paraphrased as `"SceneMultiplayer has received an update for node World/Players/70163785 that does not exist (anymore) by a player that is not connected (anymore); update discarded"`.
> > Most of the time, these logs are normal for networking. Sometimes, you are going to send an update, not knowing that either the pertaining player has already left, or the last updates by that leaving player are going to arrive after they alread left, and so on. Things have latency after all, and order of updates isn't always guaranteed.
> > So most of the time, these are harmless (if you do not encounter any actual breakage). But sometimes, they can be indicative of a larger problem. If you get a lot of these suddenly after a change where you didn't before, it is likely you got some ordering wrong somewhere, or some node paths are not matching up between clients, and so on.
> 
> To reduce the chance of getting the error. Maybe add a way for the client to tell the server that they are disconnecting, so that the server don't have to print the error when they disconnected without a problem.

Could you guide or remind us how to avoid their occurrence?

**Comment by makeryangcom** [comment]
> > The error log in the OP can be paraphrased as `"SceneMultiplayer has received an update for node World/Players/70163785 that does not exist (anymore) by a player that is not connected (anymore); update discarded"`.
> > Most of the time, these logs are normal for networking. Sometimes, you are going to send an update, not knowing that either the pertaining player has already left, or the last updates by that leaving player are going to arrive after they alread left, and so on. Things have latency after all, and order of updates isn't always guaranteed.
> > So most of the time, these are harmless (if you do not encounter any actual breakage). But sometimes, they can be indicative of a larger problem. If you get a lot of these suddenly after a change where you didn't before, it is likely you got some ordering wrong somewhere, or some node paths are not matching up between clients, and so on.
> 
> To reduce the chance of getting the error. Maybe add a way for the client to tell the server that they are disconnecting, so that the server don't have to print the error when they disconnected without a problem.

I always thought this error would affect normal operation, and I spent several days trying to find a solution!!!

**Comment by makeryangcom** [comment]
I will provide a relevant minimal example, and you guide me on where to handle it to avoid this error!!!

**Comment by PiCode9560** [comment]
> I will provide a relevant minimal example, and you guide me on where to handle it to avoid this error!!!

Are you talking to me or @mhilbrunner? Don't ask me, I don't know these things. I'm just here giving suggestions.

**Comment by makeryangcom** [comment]
> > I will provide a relevant minimal example, and you guide me on where to handle it to avoid this error!!!
> 
> Are you talking to me or @mhilbrunner? Don't ask me, I don't know these things. I'm just here giving suggestions.

Haha, sorry, and thank you for your help!

**Comment by makeryangcom** [comment]
Has there been any progress on this bug? If you won't be focusing on fixing it in the short term, I won't wait any longer!

**Comment by PiCode9560** [comment]
Whoops, sorry for making you wait, I didn't even work on it. I guess I could try figuring it out now. I just need more info.

**Comment by makeryangcom** [comment]
> Whoops, sorry for making you wait, I didn't even work on it. I guess I could try figuring it out now. I just need more info.

Thank you very much. I have provided my minimal program and the steps to reproduce it in the previous reply, hoping it can help you.

**Comment by PiCode9560** [comment]
Is there even a time when the error occurs as an actual mistake instead of by disconnecting?

**Comment by makeryangcom** [comment]
This error only occurs when multiple players are connected to the server and one player exits; no such errors or other issues are observed at other times.

**Comment by PiCode9560** [comment]
Really? If so, why would that error exist?

**Comment by makeryangcom** [comment]
> Really? If so, why would that error exist?

I'm not very sure either; this might require your help to resolve.

**Comment by makeryangcom** [comment]
I believe that if the line ERR_FAIL_COND(peer > 0 && !connected_peers.has(peer)); is not removed or commented out, the ERROR log will still exist. This is because I encountered a similar issue when I tried to recompile Godot. I must use the program below to avoid the ERROR.

```
if (get_unique_id() == 1) { // I am the server.
    // Direct messages to server should not go through relay.
    // ERR_FAIL_COND(peer > 0 && !connected_peers.has(peer));
    if(peer > 0 && !connected_peers.has(peer)){
	    return;
    }
```
