### ISSUE TITLE
GDScript.reload() for GDScript which only sets the [source code that contains inner classes] no longer works after 4.0.Beta9

### ISSUE THREAD

**Issue by Xwdit** [godotengine/godot#70518]
### Godot version

4.0.beta10

### System information

Windows 11

### Issue description
UPDATE: This problem only occurs when the source code contains inner classes

Before 4.0.Beta9, I could get a GDScript instance by `GDScript.new()` and then set the `source_code` property and then `reload()`, but now it throws an error 
```
USER SCRIPT ERROR: Parse Error: Could not find script "".
   at: GDScript::reload (built-in:1644)
```
In my software, I use the above method when the user modifies the code text, and then read the godot log to implement real-time error checking of the custom user script editor. But now this functionality is completely broken

### Steps to reproduce

1. Create a GDScript instance by `GDScript.new()`
2. set the `source_code` property and then `reload()`

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
CC @adamscott @rune-scape

**Comment by adamscott** [comment]
Could not reproduce on master ([f382a2b](https://github.com/godotengine/godot/commit/f382a2b59bb9606f958ccaf7be7ac98f45607c9f))

@Xwdit Please add a minimal reproduction project to the issue.

**Comment by Xwdit** [comment]
UPDATE: This problem only occurs when the source code contains inner classes

**Comment by adamscott** [comment]
This is a regression coming from #69471. The analyzer tries to resolve the script using it's path, but as it's a runtime script, it has no script path.
