### ISSUE TITLE
Normal Map doesn't flip properly with flip_h and flip_v in Sprite2D

### ISSUE THREAD

**Issue by IntangibleMatter** [godotengine/godot#70517]
### Godot version

4.0 beta 10

### System information

Windows 10, Vulkan Renderer

### Issue description

In 2D scenes with sprites, when the sprite's `flip_h` and/or `flip_v` property is enabled, the normal map is flipped with the image, causing lighting to be reversed. While this does technically make sense, in a game where You have a bunch of sprites that flip and use normal maps, the only solution is to generate normal maps for both facing directions.
![image](https://user-images.githubusercontent.com/47702559/209426338-6257d66c-a965-4793-a7bb-5a635a136267.png)

Ultimately the fix is simple: Invert the red channel in normal maps on horizontally flipped sprites, and invert the green channel on vertically flipped sprites.

### Steps to reproduce

1) Create a Sprite2D
2) Add a Diffuse Texture and Normal Map 
3) Add a 2D Light to the scene
4) Enable `flip_h` and/or `flip_v` on the Sprite2D

### Minimal reproduction project

[Normal not flipped.zip](https://github.com/godotengine/godot/files/10298203/Normal.not.flipped.zip)

**Comment by jainl28patel** [comment]
Hi, I would Like to work on this issue. 
I am quite new to contribute in Godot, but I have basic knowledge of OpenGL graphics and also Normal maps.
@Chaosus Can you please provide me with some tips on where to start for this issue ?

**Comment by Chaosus** [comment]
I guess you could look at scene/2d/sprite_2d.cpp first. Then it would lead you to canvas_item stuff. I'm not sure if it's an easy issue to fix.

**Comment by jainl28patel** [comment]
Okay thanks for guiding. I will try and notify in 2-3 days if I will be able to do it or not.
