### ISSUE TITLE
GDExtensions not working with beta 10

### ISSUE THREAD

**Issue by MatSox** [godotengine/godot#70524]
### Godot version

4.0 beta 10

### System information

Windows 11

### Issue description

The classes bonded with GDExtension are not recognized. When you open the editor with some GDExtension plugin it fails to load the classes in the plugin.

### Steps to reproduce

Compile the godot-cpp, compile the test (included in godot cpp) voth with scons target=template_debug, open the editor and load the test.

### Minimal reproduction project

"N/A"

**Comment by Chaosus** [comment]
Did you not forget, update it to https://github.com/godotengine/godot-cpp/commit/3da6db4fe41b8f3d3aaeb0dc80f1556f83fd7fe6 ?

**Comment by MatSox** [comment]
No, I update it, in fact, everything compiles correctly. If I don't update I have the error due to the renaming of the GDNative in GDExtension.

**Comment by MatSox** [comment]
Any news about this? tried with Godot 11 and still not working, even the test inside the godot-cpp.
Am I missing something or it does not work for you too?
Thanks

**Comment by akien-mga** [comment]
Possibly a duplicate of https://github.com/godotengine/godot/issues/71090.

Is there any error in the console? Can you share your gdextension config file?

**Comment by MatSox** [comment]
these are the errors I have in the console:
`SCRIPT ERROR: Parse Error: Identifier "Example" not declared in the current scope.
          at: GDScript::reload (res://main.gd:17)
SCRIPT ERROR: Parse Error: Identifier "Example" not declared in the current scope.
          at: GDScript::reload (res://main.gd:18)
SCRIPT ERROR: Parse Error: "Example" was not found in the current scope.
          at: GDScript::reload (res://main.gd:28)
SCRIPT ERROR: Parse Error: Identifier "ExampleRef" not declared in the current scope.
          at: GDScript::reload (res://main.gd:39)
ERROR: Cannot get class 'Example'.
   at: (core/object/class_db.cpp:326)
ERROR: Cannot get class 'ExampleMin'.
   at: (core/object/class_db.cpp:326)
ERROR: In Object of type 'MissingNode': Attempt to connect nonexistent signal 'custom_signal' to callable 'Node(main.gd.
   at: (core/object/object.cpp:1256)`

I'm using the standard gdextension file contained in the godot-cpp repos.
`[configuration]

entry_symbol = "example_library_init"

[libraries]

macos.debug = "res://bin/libgdexample.macos.template_debug.framework"
macos.release = "res://bin/libgdexample.macos.template_release.framework"
windows.debug.x86_32 = "res://bin/libgdexample.windows.template_debug.x86_32.dll"
windows.release.x86_32 = "res://bin/libgdexample.windows.template_release.x86_32.dll"
windows.debug.x86_64 = "res://bin/libgdexample.windows.template_debug.x86_64.dll"
windows.release.x86_64 = "res://bin/libgdexample.windows.template_release.x86_64.dll"
linux.debug.x86_64 = "res://bin/libgdexample.linux.template_debug.x86_64.so"
linux.release.x86_64 = "res://bin/libgdexample.linux.template_release.x86_64.so"
linux.debug.arm64 = "res://bin/libgdexample.linux.template_debug.arm64.so"
linux.release.arm64 = "res://bin/libgdexample.linux.template_release.arm64.so"
linux.debug.rv64 = "res://bin/libgdexample.linux.template_debug.rv64.so"
linux.release.rv64 = "res://bin/libgdexample.linux.template_release.rv64.so"
android.debug.x86_64 = "res://bin/libgdexample.android.template_debug.x86_64.so"
android.release.x86_64 = "res://bin/libgdexample.android.template_release.x86_64.so"
android.debug.arm64 = "res://bin/libgdexample.android.template_debug.arm64.so"
android.release.arm64 = "res://bin/libgdexample.android.template_release.arm64.so"`

**Comment by akien-mga** [comment]
I tested on Linux, compiling current godot-cpp https://github.com/godotengine/godot-cpp/commit/512ec5b236fc550526d0a9cc37c9e9681459af52 with `scons target=template_debug`.

When I open the demo project with 4.0 beta 11, I do get the "SCRIPT ERROR" in the console the first time (that's a known issue the first time Godot loads a new extension), but then it works fine when running the project, or on subsequent editor runs.

**Comment by MatSox** [comment]
Thank you, I deleted everything and downloaded it from scratch and it seems to work now. It seems that something was compiled wrong even if I manually deleted all the dlls and the .obj files.
