### ISSUE TITLE
"Cannot Use Subscript Operator on a Base Type of 'null'" Error Not Allowing for Other Types when 'null' is Only Default Value

### ISSUE THREAD

**Issue by Snowy-Fox** [godotengine/godot#70523]
### Godot version

4.0beta10

### System information

Windows 10

### Issue description

GDScript error occurs in Godot 4.0 beta 10 (worked as expected in beta 9) when unreachable code is given a variable of the wrong type. In the function in the below example, some variables are set by according to a dictionary in an array, provided in the argument `val`. If no argument is provided (defaulting to `null`), those variables are reset to their defaults, and the function returns.

![error](https://user-images.githubusercontent.com/6191653/209433096-e02205c0-d745-46a8-9558-8386340be429.png)

The error occurs at the four lines where the variables are set according to the given array/dictionary, as `null` would indeed not be compatible. But, this code is unreachable if `val` is `null`.

This error can be worked around by using `[null]` instead, of course, and the error makes sense in theory, but it doesn't make sense for it to be raised before runtime.

### Steps to reproduce

Create any function with a default argument with a base type that includes no subscript operators, then attempt to use a subscript operator from that argument in code within the function which should be unreachable by that type

### Minimal reproduction project

[Variable Type Error.zip](https://github.com/godotengine/godot/files/10298445/Variable.Type.Error.zip)

**Comment by anvilfolk** [comment]
Interestingly I just tested in Beta 8 and it didn't work there either, so it might've been a "bug" in Beta 9 that made it work. Software is lovely ;)

**Comment by Snowy-Fox** [comment]
> Interestingly I just tested in Beta 8 and it didn't work there either, so it might've been a "bug" in Beta 9 that made it work. Software is lovely ;)

That is indeed interesting. I started working on the transition system on Beta 9, so go figure.

**Comment by anvilfolk** [comment]
Ok, so this came from the changes in #70440.

@rune-scape, would there be any issue in re-adding these lines? I think that would solve the problem.
```
if (p_value.get_type() == Variant::NIL) {
		// A null value is a variant, not void.
		result.kind = GDScriptParser::DataType::VARIANT;
```

**Comment by anvilfolk** [comment]
Actually, I don't think that was necessarily the right solution. Should have a PR that I think makes more sense than re-adding those lines coming in a minute.
