### ISSUE TITLE
Scenes with both sky panoramas and ReflectionProbes print "test" 100+ times alongside thousands of errors

### ISSUE THREAD

**Issue by jtnicholl** [godotengine/godot#70532]
### Godot version

v4.0.beta.custom_build [9f1fe0895]

### System information

Fedora 36

### Issue description

Opening scenes with a sky panorama and any ReflectionProbes print "test" over a hundred times, as well as a few hundred varied error messages for each probe in the scene. Toggling visibility of the probes off and on again prints the errors again.
Everything seems to still render correctly, as far as I can tell.
Regression from #70253.

### Steps to reproduce

Open a scene with a sky panorama and a reflection probe.

### Minimal reproduction project

https://github.com/godotengine/godot-demo-projects/tree/4.0-dev/3d/platformer

**Comment by Calinou** [comment]
cc @BastiaanOlij

**Comment by BastiaanOlij** [comment]
Oops on leaving the test in :)
Going to have a look at where the error spam is coming from
