### ISSUE TITLE
Cannot import FBX animation containing animation only as animation library

### ISSUE THREAD

**Issue by trommlbomml** [godotengine/godot#70538]
### Godot version

4.0 beta 10

### System information

macOS Monterey, Apple MacBook Pro M1

### Issue description

I wanted to try out the very cool new animation retargeting feature on [Kenneys Characters Assets](https://kenney.itch.io/kenney-character-assets) for my little game. 

I was able to import the fbx files for the model itself properly with enabling animation retargeting but not the animations, which are separate fbx files. The fbx animation files during import have no skeleton node but only a node3D hierarchy and an animation player, so I cannot enable the option for being an animation library. The animation fbx seems to only contain the animation, no 3d geometry.

The main question is: is it really a Godot problem, with the asset or the importer?

### Steps to reproduce

- Use Kenney Character Assets
- Copy models from folder to Godot project
- open characterMedium.fbx with animation retargeting for humanoids enabled -> everything is fine
- open e.g. animation run.fbx -> only node3d and animationplayer, no option for being an animation library

### Minimal reproduction project

I cannot add the original assets as I had to buy them.

**Comment by Donn-Eddy** [comment]
I have had this issue with the Blink assets from [this humble bundle.](https://www.humblebundle.com/software/unity-unreal-rpg-essentials-blink-software)

**Comment by fire** [comment]
See https://github.com/godotengine/FBX2glTF/issues/19 **FbxSkeleton should create empty skins with all of the bones**

**Comment by lyuma** [comment]
May be fixed in FBX2glTF by https://github.com/godotengine/FBX2glTF/pull/41

**Comment by lyuma** [comment]
Since there is no comment and no easily accessible MRP, I believe this is the issue we have fixed with the import as skeleton option as well as detecting unused skins.

Closing as fixed in FBX2glTF and 4.3 native FBX

If you're still having this issue, please test again on the latest 4.3 dev build and let us know what steps you tried.
