### ISSUE TITLE
OBJ files imported as Scene crashes when selecting the mesh in import settings.

### ISSUE THREAD

**Issue by Donn-Eddy** [godotengine/godot#70539]
### Godot version

4.0 Beta10

### System information

Ubuntu 22.04 (Tuxedo OS)

### Issue description

After importing an *.obj file as a scene, if you click on the mesh in the import settings Godot crashes.

![Screenshot from 2022-12-24 14-38-23](https://user-images.githubusercontent.com/25522325/209452619-3c0ed61b-deaa-4fb6-8ff5-5aa11ff4ed33.png)

I the above screenshot, clicking in the circled area will crash Godot.

### Steps to reproduce

Import .obj file into a project.
Select the file.
Go to import setting.
Change OBJ As Mesh to Scene.
Click Reimport.
Click Save Scenes, Re-Import, and Restart.
Once restarted, open the advanced import settings on the object.
Click the are circled in the description, or in the meshes tab.

### Minimal reproduction project

N/A

Specifically, I lack the distribution rights of the .obj files I am using.  Any .obj file should do, this happened to me on at least 4 different .obj files.

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/64970.
