### ISSUE TITLE
lambda can not change local variables' value

### ISSUE THREAD

**Issue by matrixant** [godotengine/godot#70549]
### Godot version

4.0 beta 9

### System information

Windows 11

### Issue description

When chage a local variable in lambda, it will not get change out of the lamda scope.

### Steps to reproduce

```gdscript
func test1():
	var inc1 := 0
	var c := func():
		inc1 += 1
		print_debug(inc1)
	
	for i in 10:
		c.call()
```
when call `test1`, the editor will print `1` 10 times.

```gdscript
var inc2 := 0
func test2():
	var c := func():
		inc2 += 1
		print_debug(inc2)
	
	for i in 10:
		c.call()
```
when call `test2`, the editor will print `1` to `10`.

<img width="219" alt="Snipaste_20221225_170706" src="https://user-images.githubusercontent.com/9391827/209462717-b032ee3e-bba3-44e0-9ecd-a507d8106110.png">
<img width="270" alt="Snipaste_20221225_170731" src="https://user-images.githubusercontent.com/9391827/209462726-4137d63b-d40d-416d-9a2d-dcedf75caeeb.png">

### Minimal reproduction project

[bug_report.zip](https://github.com/godotengine/godot/files/10299670/bug_report.zip)

**Comment by KoBeWi** [comment]
That's how lambdas work, see #69014
