### ISSUE TITLE
"indirect call to null" \ "null function or function signature mismatch" error only on web exports

### ISSUE THREAD

**Issue by ababen1** [godotengine/godot#70558]
### Godot version

v4.0.beta.custom_build [f692b4768]

### System information

Linux

### Issue description

I get these error only on the web export (both on localhost and in production). 
Here is what I get on Firefox:
![image](https://user-images.githubusercontent.com/80917990/209471779-2a60e611-69d5-46e5-9d53-ddc9d98a6245.png)

and on Chrome: 
![image](https://user-images.githubusercontent.com/80917990/209472079-9c0303f3-c08d-4b1d-8100-361f1973ca96.png)

The errors appeared with the recent update, had no problem beforehand. And they only appear on the web export.

### Steps to reproduce

I'm not sure exactly what caused this error,  'LetterSquaresGenerator.gd' is a class that inherits Node, so this line shouldn't throw an error:
`@onready var _generator: LetterSquaresGenerator = $LetterSquaresGenerator`
And even if didn't inherit from Node, and this line really is an error, why would the error only appear on web? 

### Minimal reproduction project

don't have one, sorry :(

**Comment by akien-mga** [comment]
Can you still reproduce this issue in the latest 4.0 beta?

**Comment by ababen1** [comment]
Oh I posted this quite awhile ago and the problem is gone in the latest version, web export working fine again :) I will close the issue
