### ISSUE TITLE
"Save Branch as Scene" FileDialog in Debugger Remote Tree doesn't suggest the filename

### ISSUE THREAD

**Issue by stmSi** [godotengine/godot#70553]
### Godot version

Both 4.0 and 3.x

### System information

Linux

### Issue description

This issue is only for Remote Tree... Local Tree works fine.
![image](https://user-images.githubusercontent.com/32661049/209468212-57e3a63d-c3cd-4814-b114-327b2dbfdc12.png)

![image](https://user-images.githubusercontent.com/32661049/209468332-785ae838-18d3-478a-b899-89b3218f53ee.png)

### Steps to reproduce

1. Add Node2D
2. Save and Run then Pause
3. Click the `Remote` (as shown in screenshot)
4. Right click and click "Save Branch as Scene"
5. See that File input box is empty.

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
The popup menu could also use a `reset_size()`, because it's too big.

**Comment by Beweeted** [comment]
This is as far as I got, poking around tonight. In case it helps someone else, or for me to maybe come back to.

Here is where it grabs the parent node to copy:
https://github.com/godotengine/godot/blob/0bb94df247a0a0c22333e2e99744fc3fd184601a/editor/scene_tree_dock.cpp#L892

Which is used here to generate the name. But I think it's just the folder path?
https://github.com/godotengine/godot/blob/0bb94df247a0a0c22333e2e99744fc3fd184601a/editor/scene_tree_dock.cpp#L928-L937

This is where the field of the popup is defined, but I don't see anything in here to suspect:
https://github.com/godotengine/godot/blob/2ca972ad01e8000aff639c691abce325f1ac01cf/scene/gui/file_dialog.cpp#L1092-L1097

**Comment by stmSi** [comment]
@Beweeted  I already have pr... #70554 .. thanks for analysis anyway 😇😇

**Comment by Beweeted** [comment]
Oh, so you do. And it wasn't in any of the files I mentioned. Well at least it was fun to poke around! Sorry for the bother.
