### ISSUE TITLE
Label Valign - Center is worked as Top and Top as Center

### ISSUE THREAD

**Issue by ealataur** [godotengine/godot#7055]
**Operating system or device - Godot version:**
master
commit - 79e8c7fc0d15ab432f017e9b40b2122e89610d40

**Issue description** (what happened, and what was expected):
Label Valign worked wrong

**Steps to reproduce:**
Add Label to Node
add text to Label
set Valign to Center
set Valign to Top
Look differences

**Link to minimal example project** (optional but very welcome):
![2016-11-06 18 50 55](https://cloud.githubusercontent.com/assets/7677575/20039325/5755d9dc-a45b-11e6-9bd2-ba14ed9888d8.png)
![2016-11-06 18 51 08](https://cloud.githubusercontent.com/assets/7677575/20039334/638bf39e-a45b-11e6-8f42-1ebb70b00444.png)

**Comment by vnen** [comment]
Note that this happens only if the Label is child of a Container. It's not that the values are swapped, it's something related to how the container and label interfere with each other, so I'm not sure if this is a junior job.

**Comment by bojidar-bg** [comment]
@vnen Sadly, we have no <kbd>paranormal</kbd> tag for you. :wink:

**Comment by volzhs** [comment]
It can be reproduced whatever parent node is. (Node2D or Control)

**Comment by puppetmaster-** [comment]
LOL! I never thought it was a bug!
