### ISSUE TITLE
Can not rename the folder

### ISSUE THREAD

**Issue by L2750558108** [godotengine/godot#70551]
### Godot version

3.5.1mono

### System information

windows10

### Issue description

When I tried to rename a folder,I failed and got this
![image](https://user-images.githubusercontent.com/119792950/209467405-8819842b-93ce-4fd6-80dc-eb37b0ddc500.png)

### Steps to reproduce

no

### Minimal reproduction project

no

**Comment by akien-mga** [comment]
With no steps to reproduce, we can't do anything.
