### ISSUE TITLE
bbcode repeat twice when used the tag [color]

### ISSUE THREAD

**Issue by ryugold777** [godotengine/godot#70562]
### Godot version

3.5.1

### System information

Linux/openSUSE

### Issue description

I don't know if this is a bug, but the text when used bbcode [color] repeat twice. See the pictures please! I would like from any answers. Thanks in advance.
![Script Image](https://user-images.githubusercontent.com/76182721/209473617-f9f9d6fe-f757-457f-94a7-4fabe0bc2a1e.png)
![Run Project with bbcode](https://user-images.githubusercontent.com/76182721/209473619-2c989bcb-636e-4215-ac27-4ce8749ae7b9.png)

### Steps to reproduce

When I use tag bbcode color

### Minimal reproduction project

[Bug.zip](https://github.com/godotengine/godot/files/10300214/Bug.zip)

**Comment by KoBeWi** [comment]
Why do you have both `set_bbcode()` and `append_bbcode()` with the same text?

**Comment by ryugold777** [comment]
If I remove "set_bbcode()" it enabled scroll, I don't know why. Download the project and see yourself.

**Comment by KoBeWi** [comment]
That's because you do `append_bbcode()` inside a method that's called per frame. Obviously the text will repeat.

Make sure `show_message()` is only called once and use only either `set_bbcode()` or `add_bbcode()`.

**Comment by ryugold777** [comment]
please see this project:
[Bug.zip](https://github.com/godotengine/godot/files/10300442/Bug.zip)

the bug persist.

**Comment by KoBeWi** [comment]
That's a bug in your code.
You are checking for the whole message length, which includes bbcode. Try
```GDScript
while (Message.visible_characters) <= ($Message.text.length()):
```

**Comment by ryugold777** [comment]
Thanks! sorry for disturb you!
