### ISSUE TITLE
 Incorrect C++ source stack trace file:line format (please report).

### ISSUE THREAD

**Issue by L2750558108** [godotengine/godot#70561]
### Godot version

3.5.1mono

### System information

windows10

### Issue description

I clicked this:
![image](https://user-images.githubusercontent.com/119792950/209473077-a3a0a4b6-9e64-4d36-b3e3-954237309d20.png)
and got a message:
 Incorrect C++ source stack trace file:line format (please report).
It says "please report"

### Steps to reproduce

no

### Minimal reproduction project

no

**Comment by timothyqiu** [comment]
Please upload a minimal reproduction project so it's easier to troubleshoot.

If it's not easy to make one, you can also post the complete error message instead (with information in the expanded branch).

**Comment by L2750558108** [comment]
![image](https://user-images.githubusercontent.com/119792950/209502995-4b79fd6a-9994-4ddb-a2e1-c14d008c97f9.png)

**Comment by timothyqiu** [comment]
@L2750558108 Seems the same as #66974 which was fixed by #66977.

Please try the latest [3.5.2.rc1](https://godotengine.org/article/release-candidate-godot-3-5-2-rc-1).
