### ISSUE TITLE
Create new Image failed

### ISSUE THREAD

**Issue by creative-brainiac** [godotengine/godot#70567]
### Godot version

4.0 beta 10

### System information

Linux (pop-os) / NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2

### Issue description

The Image class does not contain any data after the create() method call and is of size (0, 0).

### Steps to reproduce

```
var img = Image.new()
img.create(600,400,false,Image.FORMAT_RGBA8)
img.fill(Color.WHITE)
print(img.get_size())
print(img.get_data())
img.save_png("res://test_output.png")

```
The console output:
(0, 0)
[]
* drivers/png/png_driver_common.cpp:56 - png_image_write_to_memory: invalid argument
* drivers/png/png_driver_common.cpp:187 - Condition "compressed_size <= png_size_estimate" is true. Returning: FAILED
* Can't convert image to PNG.

### Minimal reproduction project

[space-toolkit.zip](https://github.com/godotengine/godot/files/10300553/space-toolkit.zip)

**Comment by stmSi** [comment]
This will solve your problem.
```
var img = Image.create(600,400,false,Image.FORMAT_RGBA8)
img.fill(Color.WHITE)
img.save_png("res://test_output.png")
```

**Comment by KoBeWi** [comment]
See above.

**Comment by creative-brainiac** [comment]
This line causes Godot to freeze:
`var img = Image.create(600,400,false,Image.FORMAT_RGBA8)`

**Comment by KoBeWi** [comment]
Can't reproduce with this code. How are you setting the property?

**Comment by creative-brainiac** [comment]
I can't reproduce the problem any more. After the restart of the computer it no longer freezes. Full code of the issue looked like this:

```
@tool
extends Node
 
@export var test := false:
	set(value):
		var img = Image.create(600,400,false,Image.FORMAT_RGBA8)
		img.fill(Color.WHITE)
		img.save_png("res://test_output.png")
```

The scene was simple 3d scene with a single Node3D in it and the script was attached to it. Once I clicked on the "test" button in the editor, the Godot freezed and couldn't recover. Maybe the problem was with the previous code:

```
var img = Image.new()
img.create()
```

vs

`var img = Image.create()`

But I couldn't reproduce the error this way either.
