### ISSUE TITLE
Using SSR in Godot4, no combination of Material settings makes can produce no reflections

### ISSUE THREAD

**Issue by jamesdkay** [godotengine/godot#70574]
### Godot version

v4.0.beta5.mono.official [89a33d28f]

### System information

Windows 10, GeForce GTS 1660Ti

### Issue description

There appears to be no way to not have SSR reflections appear on a, opaque material. In Godot 3 there were combinations of Metallic, Specular and Roughness that would result in the material not having SSR reflections (eg. I think turning metallic down to zero accomplishes this). In Godot 4 at least some amount of SSR reflection remains regardless of how these are set, and I can find no way of having no reflections appear on an object short of having it render in a transparent pass.

### Steps to reproduce

Add two MeshInstance3D spheres to an empty scene. Move them so they re just touching. Add a WorldEnvironment and enable SSR. Make one sphere Red albedo and the other white. Play with Metallic/Specular/Roughness settings on the white one and you will find you are unable to make at least a hint of the red one appear reflected in the white one. For example, the white sphere below has zero metallic and specular and roughness 1.

![image](https://user-images.githubusercontent.com/59898064/209487680-457282f2-6910-4b76-82c0-15c24dacb9ae.png)

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
This was fixed already in an earlier beta. Latest is now beta 10. I suggest using that for the best experience.
