### ISSUE TITLE
Tool Export Variable Evaluation Order Incorrect

### ISSUE THREAD

**Issue by SoapSpangledGames** [godotengine/godot#70573]
### Godot version

4.0 beta 10

### System information

Kubuntu 18.04 NVIDIA GeForce GTX 1660

### Issue description

When creating a @tool-enabled file with get and set directives, the set directive gets called before the scene is added to the scene tree. When using this mechanism to initialize file-level object state, this causes the game to halt with an error accessing scene objects.

If I start with this:

![image](https://user-images.githubusercontent.com/55257920/209485083-80481561-5285-4a80-88e3-e9541942bbbc.png)

It results in:

![image](https://user-images.githubusercontent.com/55257920/209485102-576e8afa-630a-48ac-8af0-cb2cc918423b.png)

So far, so good.

But if I uncomment line 15, the script stops with an access error:

![image](https://user-images.githubusercontent.com/55257920/209485174-87cdd826-b9a6-47fe-9156-ec5be0b7cabc.png)

![image](https://user-images.githubusercontent.com/55257920/209485202-59477947-62fa-45e8-a659-c5d4034d0b63.png)

I would expect the object's resources to be loaded (and _ready() called) prior to the set and get directives being called.

### Steps to reproduce

1) Create an @export var that specifies get and set directives.
2) Implement set and/or get functions that access file-level resources.
3) Run the project (or relevant file), and watch the program die at the file-level resource access.

### Minimal reproduction project

Github won't let me upload my minimum reproduceable project, for some reason.

**Comment by KoBeWi** [comment]
`@export` variables are initialized very early, right after `_init()` (or even before, I always forget xd). You'd need `@onready @export` variable in your case, but it's not supported yet, see this proposal: https://github.com/godotengine/godot-proposals/issues/325
As a workaround, you can `await ready` in the setter if the node can't be found yet.
