### ISSUE TITLE
pressing "Convert to ShaderMaterial" on a .glb model's Surface 1 converts Surface 0 to a shader material instead

### ISSUE THREAD

**Issue by the1chocolatte** [godotengine/godot#70579]
### Godot version

4.0.beta9 [e780dc332]

### System information

Windows 10
AMD Ryzen 5 3600
AMD Radeon RX 580

### Issue description

https://user-images.githubusercontent.com/95674438/209506480-be37f1c6-2060-4a98-831d-d5fa495b3e7c.mp4

I brought in my .glb model (a tree) from blender which has two different models in it (one for the bark and one for the pine needles) and wanted to make the pine needles sway a bit. I inherit a new scene with the model and make the mesh unique (recursive) go to surface 1's material and try to convert it to a shadermaterial and it instead converts surface 0's material and on top of that it makes surface 0's material into surface 1's material. 

I decided to go back to godot 4 beta 8 [45cac42c0] and this issue is not present with my model so it is a specific godot bug (there is also a name change between the 2 versions? In beta9 it's surface 0 and surface 1 while in beta8 it's surface 1 and surface 2? just a side note).

https://user-images.githubusercontent.com/95674438/209506818-b4ed3556-ac1f-4aa9-84a9-c2f5113394cd.mp4

### Steps to reproduce

Using the minimal reproduction product:

1) Right-Click the tree.glb in the project files and make a new inherited scene

2) click tree2 in the scenetree and go to the mesh dropdown and click "make unique (recursive)"

3) click on the mesh and go down til you see surface 0 and surface 1

4) right click surface 1's material and press "convert to ShaderMaterial" what happens is surface 1's material stays the same while surface 0's material is the one that changes

### Minimal reproduction project

[tree.zip](https://github.com/godotengine/godot/files/10301635/tree.zip)

**Comment by the1chocolatte** [comment]
I could've named the videos better, the 1st video is me showing off the bug in 4.0.beta9 and the 2nd video is me doing the same thing in 4.0.beta8 and the problem not appearing.

**Comment by the1chocolatte** [comment]
another note that I realized after is the the "weird magical fix" isn't a fix at all and instead makes it so that both surface's materials are not the same (the trunk of my tree turn into the pine_needles material lol)

**Comment by devloglogan** [comment]
Thanks for creating this issue! Was about to create it myself. This issue is still present in Beta 10.

Here is a workaround until the problem is addressed:

1. Make the tree2 mesh property unique
2. Make the Surface 0 (the bark) material unique
3. Make the Surface 1 (the pine needles) material unique
4. Convert the pine needles material to a ShaderMaterial

If you try to make Surface 1 unique before 0, the issue arises, but if you do them in order it seems to work fine.

**Comment by Calinou** [comment]
> I decided to go back to godot 4 beta 8 [https://github.com/godotengine/godot/commit/45cac42c0b511672240c1fcccecfd3cc0580edcb] and this issue is not present with my model so it is a specific godot bug (there is also a name change between the 2 versions? In beta9 it's surface 0 and surface 1 while in beta8 it's surface 1 and surface 2? just a side note).

This is an intentional change: https://github.com/godotengine/godot/pull/70176

cc @clayjohn

**Comment by clayjohn** [comment]
Sounds like the conversion code may make some assumptions about surface indices that need to change
