### ISSUE TITLE
No results appear in project manager asset library if using the Open Asset Library button

### ISSUE THREAD

**Issue by TechComet** [godotengine/godot#70598]
### Godot version

v4.0.beta10.official.d0398f62f

### System information

Windows 10, NVIDIA GeForce GTX 750 Ti/PCIe/SSE2

### Issue description

Hi,

when run Godot_v4.0-beta10_win64
it's show dialog question if "Open Asset Library" or "Cancel"
if I click "Open Asset Library" it's not shwing any thing
but if click cancel and click "Open Asset Library" from tab its show demos

preview problem in video
https://drive.google.com/file/d/1hZTgMiJLLk8Cz1B_voX25CdNHKeuCXyH/view?usp=sharing

### Steps to reproduce

https://user-images.githubusercontent.com/5288136/209568828-c8824202-5b9c-4df3-a6a2-e838c3b88ac6.mp4

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Can you reproduce this on 3.5.1?

**Comment by TechComet** [comment]
No
3.5.1 **Standard** and **mono** version not have this problem
but 3.5.1 have many demo projects

**Comment by Maran23** [comment]
This is not a bug. The `Support` filter is just different. And there is no `Official` Godot 4.0 project yet.
Filter set by the `Open Asset Library` button:
![image](https://user-images.githubusercontent.com/66004280/210125101-cd6b9dc2-9b0e-47d1-863a-8229ba0d2bfb.png)

Default filter:
![image](https://user-images.githubusercontent.com/66004280/210125114-2836d917-160f-4908-a9b7-c66027ee8be8.png)
