### ISSUE TITLE
`mono/editor/external_editor` editor parameter UI only accepts integers as input

### ISSUE THREAD

**Issue by adamscott** [godotengine/godot#70599]
### Godot version

4.0.dev (b6e0603)

### System information

Linux (Ubuntu 22.04), Vulkan, Intel(R) UHD Graphics 620 (WHL GT2)

### Issue description

The `mono/editor/external_editor` editor parameter UI only accepts integers as input, as shown:

![image](https://user-images.githubusercontent.com/270928/209569927-e743cd8a-4fdb-4739-a850-7e8538947849.png)

The UI should let the user set the external editor path, as a integer value for this setting doesn't make any sense at all.

### Steps to reproduce

1. Open Godot;
2. Open Editor settings;
3. Open the `mono/editor` settings from the side bar;
4. See that the `mono/editor/external_editor` field only accepts integers.

### Minimal reproduction project

N/A

**Comment by raulsntos** [comment]
You seem to be using the non-mono version of the editor.

**Comment by Calinou** [comment]
This is likely caused by the old editor setting lingering as you changed it with a Mono-build, then you used a non-Mono build.
