### ISSUE TITLE
Tools from plugins show up for a split second and dissapear again.

### ISSUE THREAD

**Issue by MRMaasbaas** [godotengine/godot#70597]
### Godot version

3.5.1.stable.official

### System information

Windows 11

### Issue description

I am just starting with godot (I installed it yesterday) so this can question can have a obvious solution.
But essentially what happend was that I followed this tutorial: youtube.com/watch?v=nPX9MrnvNLo and everything went fine until I installed the plugin she mentions at 14:16, at 15:57 she says that you need to deselect the node and select it again to see the tools on the toolbar, I did this, and also restarted godot and my computer, but it only showed up for me for like 0.1 seconds, I tried clicking on it but I couldn't do it. The video is just to show you what's happening
Can anyone help me?

https://user-images.githubusercontent.com/121450028/209568440-75ffbbdf-12a1-4277-93fa-f738c6e75a28.mp4

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by Hiiamwilliam** [comment]
This is probably an issue with the plugin itself and not Godot.
There were people reporting a similar thing on [this thread](https://github.com/SirRamEsq/SmartShape2D/issues/97). Maybe try those workarounds, and if nothing works, report a new bug on the [plugin's Issues page](https://github.com/SirRamEsq/SmartShape2D/issues).

**Comment by AThousandShips** [comment]
Closing as per above
