### ISSUE TITLE
Unnecessary suggestion on autocomplete

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#7061]
**Operating system or device - Godot version:**
master head cdc4664226cdc397d054b7390d0f75028d40412c

**Issue description** (what happened, and what was expected):
![image](https://cloud.githubusercontent.com/assets/8281454/20061269/8aa7a602-a542-11e6-97f6-153202d30a70.png)

EDIT:
I'm not sure it's intended.
I don't know why it's in here.
https://github.com/godotengine/godot/blob/c05ff0577fd9cc39a6968e65743f7d7da711bfe2/modules/gdscript/gd_editor.cpp#L2318-L2328

**Comment by akien-mga** [comment]
Those are meant to ease the readability of the autocompleted InputEvent methods AFAIK, but they should not be shown when no methods of their type is being displayed.

**Comment by Noshyaar** [comment]
This is no longer the case with latest master.

**Comment by akien-mga** [comment]
Fixed by 5b3709d30 in 3.0.
