### ISSUE TITLE
`Generate POT` generates incorrect multiline message.

### ISSUE THREAD

**Issue by zaevi** [godotengine/godot#70617]
### Godot version

master

### System information

Win11

### Issue description

When use `Generate POT` for multiline texts, it drops `\n` and generates single line message.

- **Label text in Main.tscn:**
![image](https://user-images.githubusercontent.com/12966814/209623668-19fd1d76-038a-4c19-938e-7559eb7652a3.png)

- **tr() text in Main.gd:**
```gdscript
func _ready():
	print(tr("MULTILINE text\nfrom\nMain.gd"))
```

- **Generated .pot:**
```pot
#: Main.tscn
#: Main.gd
msgid "MULTILINE text"
"from"
"Main.gd"
msgstr ""

#: Main.tscn
msgid "This is"
"MULTILINE text"
"from Main.tscn"
msgstr ""
```
This is actually single line like `This isMULTILINE textfrom Main.tscn`

- **Expected:**

```pot
#: Main.tscn Main.gd
msgid ""
"MULTILINE text\n"
"from\n"
"Main.gd"
msgstr ""

#: Main.tscn
msgid ""
"This is\n"
"MULTILINE text\n"
"from Main.tscn"
msgstr ""
```

### Steps to reproduce

Generate pot file for multiline texts.

### Minimal reproduction project

[generate_pot_newline.zip](https://github.com/godotengine/godot/files/10306460/generate_pot_newline.zip)

**Comment by ZangEldor** [comment]
Hi,
Started to look about this bug.
Hopefully will be solved tomorrow (europe time).
