### ISSUE TITLE
gd script files are not getting updated reads after modifying them in external editor

### ISSUE THREAD

**Issue by claychinasky** [godotengine/godot#70614]
### Godot version

4.0 beta 10

### System information

windows 10

### Issue description

I'm using neovim with LSP support,  but I think its irrelevant to this issue what editor it is.
I don't know how to reproduce it, sometimes it refreshes sometimes not. 
Reloading project forces the refresh, making big changes to file forces a refresh.
It looks like it reads it from the cache and ignore the actual file.

### Steps to reproduce

I don't know how to reproduce it, sometimes it refreshes sometimes not. 

### Minimal reproduction project

if its not known issue, then I may try to experiment with a fresh project.

**Comment by Rindbee** [comment]
Possibly a duplicate of #69485.

**Comment by claychinasky** [comment]
> The way to get this updated to close the script with <Ctrl-w> and reopen it
This doesn't work in my case. Even after closing reopening, it still reads from the cache.
Other difference is, it was started happening in beta 10. I didn't have this issue in beta 9 or any previous beta or alphas. I have used all of the godot 4 releases at least 5+ hours regularly.

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/69485.
