### ISSUE TITLE
Physics 3D SAT solver produces incorrect collision normals between large sphere and capsule

### ISSUE THREAD

**Issue by Malcolmnixon** [godotengine/godot#70615]
### Godot version

4.0 beta 10

### System information

Windows 10, NVidia 2070, Vulkan Mobile

### Issue description

A human-sized (0.4 x 1.8 x 0.4) CapsuleShape3D on top of a large (50 x 50 x 50) SphereShape3D produces unstable normals when performing a move_and_collide down.

In discussions on the physics channel of the Godot Contributors Chat, the SAT solver isn't a good choice when the exact collision information can be solved analytically.

The problem with the SAT solver is that it ends up producing two collision points A and B on the two colliding shapes, and then the vector between them is used to build the normal. The problem is that A and B end up being extremely close (1e-4 distance), so normalizing the vector results in a large amplification of any numeric errors.

The current API for the ```_collision_<shape1>_<shape2>()``` functions can only report their findings via the ```_CollectorCallback``` API, and that only allows for providing the A and B points. Instead the collision functions should also have a means of providing exact analytic collision information if available.

### Steps to reproduce

Construct a scene consisting of a large 50m sphere with a capsule shape resting on top of it. Then perform a move_and_collide down and print the collision normal vector. 

### Minimal reproduction project

[SphereCapsuleCollision.zip](https://github.com/godotengine/godot/files/10306031/SphereCapsuleCollision.zip)

This demo walks a capsule around the top of a large sphere drawing the normal vector. The vector flickers between the correct normal and weird unstable normals:
![image](https://user-images.githubusercontent.com/1863707/209614550-5d631bb3-de05-463b-baf7-3c51b00b36e4.png)

**Comment by Malcolmnixon** [comment]
I suspect this video also contains the same sort of normal problems - https://www.youtube.com/watch?v=PGOHiI-5beM

**Comment by Malcolmnixon** [comment]
In order to debug the physics problems further, I created a test project that rolls different CharacterBody3D shapes over different StaticBody shapes. I've attached a zip - [PhysicsCollisionTest.zip](https://github.com/godotengine/godot/files/10310452/PhysicsCollisionTest.zip), but the project can also be accessed at https://github.com/Malcolmnixon/PhysicsCollisionTest.

Roughly 43% (18 out of 42) collision tests show failures.

![image](https://user-images.githubusercontent.com/1863707/209718066-3a4e8398-8234-40dd-ad3b-35ccfdad54f2.png)
![image](https://user-images.githubusercontent.com/1863707/209718155-f6ffde1a-ce92-47d4-8f34-c238aaf36a78.png)
![image](https://user-images.githubusercontent.com/1863707/209718255-7a08be18-4c19-4e0f-b95e-84867dd05a5e.png)
![image](https://user-images.githubusercontent.com/1863707/209718384-149779ec-8589-4213-8ff1-e82f759e5c11.png)

The exact results are as follows:
 - Sphere moving on Sphere - good
 - Capsule moving on Sphere - unstable normals
 - Cylinder moving on Sphere - good
 - Box moving on Sphere - good
 - Convex moving on Sphere - unstable normals
 - Concave moving on Sphere - no collisions
 - Sphere moving on Capsule - good
 - Capsule moving on Capsule - unstable normals
 - Cylinder moving on Capsule - periodic collision misses
 - Box moving on Capsule - periodic collision misses
 - Convex moving on Capsule - wildly incorrect normals and collision points
 - Concave moving on Capsule - no collisions
 - Sphere moving on Cylinder - good
 - Capsule moving on Cylinder - unstable normals
 - Cylinder moving on Cylinder - periodic collision misses
 - Box moving on Cylinder - periodic collision misses
 - Convex moving on Cylinder - unstable normals
 - Concave moving on Cylinder - no collisions
 - Sphere moving on Box - good
 - Capsule moving on Box - good
 - Cylinder moving on Box - good
 - Box moving on Box - good
 - Convex moving on Box - good
 - Concave moving on Box - no collisions
 - Sphere moving on Convex - good
 - Capsule moving on Convex - good
 - Cylinder moving on Convex - periodic collision misses and unstable normals
 - Box moving on Convex - good
 - Convex moving on Convex - good
 - Concave moving on Convex - no collisions
 - Sphere moving on Concave - good
 - Capsule moving on Concave - good
 - Cylinder moving on Concave - good
 - Box moving on Concave - good
 - Convex moving on Concave - good
 - Concave moving on Concave - no collisions
 - Sphere moving on World Boundary - good
 - Capsule moving on World Boundary - good
 - Cylinder moving on World Boundary - good
 - Box moving on World Boundary - good
 - Convex moving on World Boundary - good
 - Concave moving on World Boundary - no collision

**Comment by peastman** [comment]
I've been debugging the cylinder-cylinder case.  It seems to just be numerical precision.  I compared two successive steps, one on which it successfully finds the collision and one on which it doesn't.  Between the two steps, the moving cylinder's z coordinate changes by a tiny amount, from 1.096738 to 1.109235.  That leads to a tiny change in the axis direction, from (0, 0.999941, 0.01086) to (0, 0.999983, 0.005893).

That axis gets passed to the large cylinder's `get_supports()` function.  It returns an edge that will get passed to `_generate_contacts_edge_circle()`.  The tiny change in axis leads to a large change in the edge's z coordinate, from 1.085994 to 0.589262.  That edge is outside the moving cylinder and no contacts get generated.

**Comment by Malcolmnixon** [comment]
It seems that SAT is good for collision "detection" but sucks for contact "determination". Using SAT requires numeric expressions which involve the size of the objects and the margin between them; and IEEE 32-bit floats don't have the significant digits for it.

I can't currently conceive of a solution to SAT contact determination., The best you can do is calculate the most accurate axis possible, but you're still relying on the get_supports() to produce points on each object that are close enough to make sense, and that just doesn't seem to be a dependable operation.

All I can think of doing at this point is replacing the SAT collision detection/determination code with analytic solutions in as many places as possible.

**Comment by peastman** [comment]
Analytic cylinder-cylinder intersections are really painful.  I've been going through papers on various methods.  All of them are really complicated, and a lot of them look like they might have similar precision problems.  This paper is one of the most recent ones, and it has references to lots of others: https://ieeexplore.ieee.org/document/6697131.

Box-capsule intersections seem like they ought to be easy to do analytically, but I haven't found any published methods.

For the capsule-cylinder case, a simple approach would be to view the cylinder as a capsule with the ends cut off.  Start by pretending it's a capsule and use the analytic capsule-capsule test.  It's fast and accurate.  There are three possible results.

1. No collision.  In that case, there's no collision with the cylinder either.
2. A collision with the curved side of the capsule.  Since it coincides with the side of the cylinder, that's the correct intersection.
3. A collision with the rounded end of the capsule.  That isn't present in the cylinder, but it's possible there's an intersection with the flat end of the cylinder.  Fall back to the existing SAT code.  Since the end is flat, precision issues will hopefully be less serious there.

**Comment by Malcolmnixon** [comment]
Which analytic solutions do we have at the moment? Either way it's probably best to:
 1. Get the base infrastructure in place, for example expanding the callback to include the optional normal
 2. Update the simple cases (sphere-sphere, sphere-capsule, and capsule-capsule)
 3. Get that PR pulled in
 4. Start working through the remaining cases individually and knock off the low-hanging fruit

**Comment by peastman** [comment]
Agreed.  Up to you whether you want to include the optional normal in the current PR, or get it merged first then do it in a separate PR.  I can add it if you want or leave it to you, whatever you prefer.

Sphere-box is also an easy one to do analytically.  And I think that box-capsule can be done by checking against each of the twelve edges of the box (each one is a capsule-capsule test), plus testing the ends of the capsule against the full box (each is a sphere-box test).

**Comment by Malcolmnixon** [comment]
Adding the optional normal to all the callbacks should probably be its own pull request. It's going to touch a bunch of areas:
 - CallbackResult
 - _CollectorCallback::call
 - SeparatorAxisTest::test_contact_points
 - GodotPhysicsServer3D::_shape_col_cbk
 - _rest_cbk_result
 - GodotCollisionSolver3D::soft_body_contact_callback
 - GodotBodyPair3D::_contact_added_callback
 - GodotBodyPair3D::contact_added_callback
 - GodotPhysicsServer3D::CollCbkData

Given the scope of these changes I think it's best to keep them as separate PRs.

**Comment by peastman** [comment]
Sounds good to me.

**Comment by Dabnabbit** [comment]
@peastman @Malcolmnixon Awesome work troubleshooting this guys! This has been a major major hard-stoppage point for me and several others I know attempting open-world projects in Godot, was definitely a bit of a demotivator, but seeing your efforts here gives me some optimism we may see some results soon!

**Comment by peastman** [comment]
I figured out a much better way of doing capsule-cylinder than what I described above.  It's in #70787, along with sphere-box and sphere-cylinder.

**Comment by reduz** [comment]
For analytical solutions, remember that in most cases they need to include margins (which are needed for depenetration in stuff like the kinematic controller). In general this is fine since the axis will probably not change so just computing the axis analytically is enough, but this something that still needs to be considered.

**Comment by peastman** [comment]
Does the way margins are handled in #70660 look correct?  It effectively inflates each object by the margin.  For example,

```c++
if (withMargin) {
    p_radius_a += p_margin_a;
    p_radius_b += p_margin_b;
}
```

**Comment by Malcolmnixon** [comment]
For the box/sphere case (and possibly for some of the others) you may want to change how the margin math is performed:
![image](https://user-images.githubusercontent.com/1863707/210159810-ea76646d-0c42-42de-8f1c-469274680402.png)

The current math for the box expands each dimension of the box by the margin, but that ends up moving the corners out by sqrt(3) * margin. The ideal case would be to keep the margin thickness constant, but that's challenging to apply to the box; however at least for the box-sphere case, you can just add the boxes margin to the sphere.

**Comment by peastman** [comment]
I think that adding the margin to the sphere isn't quite equivalent.  It produces the same amount of padding, but it puts the contact points in different places.  I don't know which is preferable?  Or possibly it makes no difference, and all three end up being equally effective?

**Comment by Malcolmnixon** [comment]
I agree you'd have to correct the contact points - it's more the collision approach that would round off the box. It's only 3-4  lines of difference as compared to your current cube PR code:
 - Don't expand the box by p_margin_b
 - Add p_margin_b to the inside test expression
 - Offset the b_point from nearest by p_margin_b towards the sphere
 
 It should then replicate the intended results of the SAT-axis shadow expansion.

**Comment by peastman** [comment]
I've updated it to handle the corners correctly.  Likewise for the cylinder, which has a similar issue at the edges.

**Comment by reduz** [comment]
@peastman yes that is intended, its just the easiest way
