### ISSUE TITLE
OS X (El Capitan) delayed UI responsiveness to mouse interactions

### ISSUE THREAD

**Issue by fogelfish** [godotengine/godot#7062]
In an empty project, newly installed Godot, trying to follow the "Hello World" tutorial.  The user interface's responsiveness to mouse interactions is very poor.  Sometimes I have to click on a menu item or button 3 or 4 times before the UI responds.

Responsiveness is subjective but no other software on this computer exhibits anything like this behavior. I need advice on how to crack this open. I could screen capture a video.

I will remove all startup items to see if that reveals a hidden conflict. I'll post the results.

I first referred to this in [https://godotengine.org/qa/9630/godot-editor-interface-performance-bottleneck-on-mac-os-x?show=9697#c9697](url)

Godot v2.1.stable.official
Mac Pro (early 2009)
OS X El Capitan
2 x 2.66 GHz Quad Core Intel Xeon
16 GB 1066 MHz DDR3 ECC
nVidia GeForce GT 120 512 MB.

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by fogelfish** [comment]
I've switched my daily work to a newer computer running High Sierra and on that system I've had no problems with the responsiveness of Godot's UI.  Back on my El Capitan system I installed Godot 3.0.2 and there is still a problem with the UI's responsiveness.  I have to click or double-click interface elements (depending on what kind it is) more than once.  With the UI feedback delayed like that it makes my use of it unpredictable.  Sometimes I end up activating another element "inside" the first one I intended to interact with.  The behavior doesn't appear to be project-specific.

One thing that may be unique about that system is I'm using an Nvidia GeForce GTX 980 and the Nvidia Web Driver (which I keep up-to-date, along with OS X system updates).  It is not the stock card that came with the machine.  According to the OpenGL Extensions Viewer application I'm using OpenGL version "4.1 NVIDIA-10.11.14 346.03.15f13", but the Terminal command glxinfo | grep "OpenGL version" returns "version string 2.1 NVIDIA-10.11.14 346.03.15f13".  Would you like to see debug output from Godot?

**Comment by akien-mga** [comment]
Thanks for testing again. Given that El Capitan is no longer supported by Apple, and no other user has reported a similar issue, I assume that it must be system-specific (and maybe related to Apple OpenGL drivers, which are notoriously bad). Closing as I doubt we'll ever get to fixing this sadly.
