### ISSUE TITLE
VisualShader GPU particle index is type `uint` but is trying to assign as `int`

### ISSUE THREAD

**Issue by cphillips83** [godotengine/godot#70634]
### Godot version

4.0.dev-10

### System information

Windows 11

### Issue description

It seems like the `index` type for a gpu particle is `uint` but when you are trying to use it in the visual shader system it is always trying to assign it to an `int` aka `int n_out10p0 = INDEX` and this causes a shader compilation error.

As a work around I've created a custom shader node with the following code and named it `GPUIndex`

```
func _get_code(input_vars, output_vars, mode, type):
	return "%s = int(INDEX);" % output_vars[0]
```

### Steps to reproduce

1. Create GPUParticle3D node
2. Add a Shader and then a VisualShader
3. Add node `index` from `input`
4. Try to assign the output to any inputs will produce a shader compilation error.

### Minimal reproduction project

Not needed

**Comment by Calinou** [comment]
cc @Chaosus

**Comment by Chaosus** [comment]
Because visual shaders currently do not support `uint` type, you must convert it to an integer first.

**Comment by cphillips83** [comment]
@Chaosus Going through the options, I couldn't find any visual nodes that would convert from uint to int, everything I selected would always assign it to an `int` without a `int(INDEX)` on the right. 

Is there a node I'm missing?

**Comment by Chaosus** [comment]
> Is there a node I'm missing?

No, its a complex thing, including nodes, return type, menu support etc
