### ISSUE TITLE
[Godot 4.0 beta10] return null after call tween.tween_property(...)

### ISSUE THREAD

**Issue by HackLinjiuyue** [godotengine/godot#70647]
### Godot version

v4.0.beta10.official.d0398f62f

### System information

Vulkan API 1.2.194 - Using Vulkan Device #0: Intel - Intel(R) Iris(R) Xe Graphics

### Issue description

unexpected return value after calling tween_property(...) from object created by get_tree().create_tween() at any point

### Steps to reproduce

var tween=get_tree().create_tween()
print(tween.tween_property($self,"position",position,1))

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/10311100/test.zip)

**Comment by KoBeWi** [comment]
Check the errors in Debugger tab. Tween methods return null when they fail.
