### ISSUE TITLE
Transparency with refraction is too dark with mobile renderer

### ISSUE THREAD

**Issue by Sekuta82** [godotengine/godot#70645]
### Godot version

v4.0.beta8.official [45cac42c0]

### System information

Windows 10, GTX 1060

### Issue description

When switching from forward+ to the mobile renderer, all transparent shaders with refraction turned on are too dark.
The blend mode is set to 'mix'.
With albedo set to white, alpha 0, the objects seen through the transparent shaders are noticeibly darker.
The effect increases with increasing transparency, which leads me to believe, that it is a blending issue.

forward+
![gd4_refraction_fw+](https://user-images.githubusercontent.com/47293702/209731534-16d1e49c-a42c-4187-9173-18b4839467c4.PNG)
mobile
![gd4_refraction_mobile](https://user-images.githubusercontent.com/47293702/209731537-6e3922bd-8829-407d-9e80-11bb153f62b5.PNG)

### Steps to reproduce

Set the renderer to mobile in the project settings.
Create a material with alpha 0, blend mode 'mix' and refraction 'on'
Assign the tranparent material to an object in front of another object

### Minimal reproduction project

[refraction_mobile.zip](https://github.com/godotengine/godot/files/10311040/refraction_mobile.zip)

**Comment by Calinou** [comment]
This should be fixed in 4.0.beta9 and later: https://github.com/godotengine/godot/issues/68636

**Comment by Sekuta82** [comment]
Yep, it works now.

Thanks!
