### ISSUE TITLE
Method to play sound in SamplePlayer at a given voice

### ISSUE THREAD

**Issue by joelgomes1994** [godotengine/godot#7065]
Hello!

I would like to ask for a method to allow the SamplePlayer node to play sounds at a given voice, just like in SamplePlayer2D and SpatialSamplePlayer nodes.

`SamplePlayer2D.play(sample, voice)`
`SpatialSamplePlayer.play(sample, voice)`

In canse of SamplePlayer, it is:
`SamplePlayer.play(sample, unique)`

And could be:
`SamplePlayer.play(sample, voice, unique)`

I'm in need of this for my musical instruments project in Godot. I don't need the SamplePlayer2D positional capabilities (there's the reason I'm not using it in place, not telling its max polyphony), and the code is getting much larger than it could be if this simple parameter in SamplePlayer existed.

Thanks, and I hope you consider my request! :smile:

**Comment by Noshyaar** [comment]
The audio system is rewritten in 3.0. Can you test if the functionality is achievable with it?

**Comment by joelgomes1994** [comment]
Unfortunately  I'm not using Godot anymore, 3.0 doesn't work on my hardware (OpenGL issues), so I can't test it. I will close issue. Thanks.

**Comment by Noshyaar** [comment]
Thanks for responding. Sorry to hear that. Would you mind opening an issue about that? It'd helpful to those having similar hardware.
