### ISSUE TITLE
Exported Array of Resources becomes empty if any item is empty in the inspector

### ISSUE THREAD

**Issue by Yagich** [godotengine/godot#70657]
### Godot version

4.0b10

### System information

Linux/Manjaro

### Issue description

An exported Array of Resources becomes empty unless all the items in that Array are filled with Resources, despite Resource being nullable like all other Objects. This seems to be an inspector-only issue, therefore I imagine it's the same cause as #62916.

The provided MRP has a scene with an exported Array with two items, one empty and one a generic Resource, and prints the Array in `_ready()`, printing an empty Array.

### Steps to reproduce

1. Add an `@export` variable and type it to `Array[Resource]`
2. In the inspector, resize the array to 2
3. Set one of the items to any Resource, and leave one item empty
4. Run the scene and look at the array in the remote tree, observe how it's empty

### Minimal reproduction project

[export-array-resource.zip](https://github.com/godotengine/godot/files/10312401/export-array-resource.zip)

**Comment by vnen** [comment]
I can't reproduce, it seems to have already been fixed.
