### ISSUE TITLE
Plugin tool scripts need to be updated by force

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#70667]
### Godot version

4.0 5674fa0

### System information

Windows 10 x64

### Issue description

This is an extension of #68615

When you start a project with a plugin that preloads a resource and `.godot` does not exist, you get the typical "Unable to load addon script from path:" warning and the plugin is disabled. Before it wasn't a big deal, just go to addons tab and enable the plugin manually, because the filesystem has been scanned by then.

But no, this does not work anymore. The script will never become valid, you need to force it. Either by project reload or... opening and saving the script.

https://user-images.githubusercontent.com/2223172/209811540-1a44edc7-92f7-4166-9e5c-5982b6176ba2.mp4

EDIT:
I tried bisecting this and beta8 and beta9 have a weird issue where failed plugins don't show the warning dialog and just fail silently.

### Steps to reproduce

1. Open the MRP
2. Error
3. Go to Project Settings -> Plugins
4. Enable the plugin
5. Still error
6. Open the problematic script
7. Save the script without doing literally anything else
8. Try enable the addon again
9. Success

### Minimal reproduction project

[global_class_issue.zip](https://github.com/godotengine/godot/files/10314187/global_class_issue.zip)

**Comment by KoBeWi** [comment]
A similar issue exists with any custom class. Like, I have a script inheriting a `class_name` and then add a method to the parent class, the script won't see it.

**Comment by akien-mga** [comment]
Could it be related to the GDScript cache? @adamscott

**Comment by adamscott** [comment]
I'll investigate!

**Comment by adamscott** [comment]
I'm wondering if it could be fixed by #71171.

**Comment by KoBeWi** [comment]
No, it doesn't fix this.

**Comment by WolfgangSenff** [comment]
Still present in 4.0beta17 - just ran into it myself with my Firebase plugin upgrade.
