### ISSUE TITLE
viewport's position incorrect when it inside a control

### ISSUE THREAD

**Issue by ippan** [godotengine/godot#7066]
**Operating system or device - Godot version:**
Windows 64bit, Godot 2.1 and still happan in master (cdc4664)

**Issue description** (what happened, and what was expected):
viewport inside a control always at the top left of screen in playmode, but it is correct in editor

**Steps to reproduce:**
- add a control
- drag the control to center of screen
- add a viewport to the control
- add a camera to viewport
- add a cube to viewport

![editor](https://cloud.githubusercontent.com/assets/2070604/20084119/626b2d90-a59b-11e6-845f-6890f9448c20.JPG)
![run](https://cloud.githubusercontent.com/assets/2070604/20084118/62641a78-a59b-11e6-8a17-b40183bcc71c.jpg)

**Comment by henriiquecampos** [comment]
It's working as expected for me (Windows 10, Godot 2.1 on Steam)
![printscreen](https://cloud.githubusercontent.com/assets/10171059/20084651/fcb6fc5e-a54a-11e6-9087-0155bbb4a379.png)

**Comment by ippan** [comment]
I create a new project -> it work correctly!
but I found the other step
in project setting
stretch mode set to viewport
and the viewport position -> incorrect

**Comment by mprasil** [comment]
I can confirm the position is working correctly when the stretch mode is set to 2D, but it appears to be broken when using viewport stretch mode. (tested with 2.1.4)

Note, that the 2D stretch mode is not really a working workaround as the contents of the viewport won't stretch with the rest of the window.

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by ippan** [comment]
in 3.0, place Viewport under ViewportContainer, set stretch mode to viewport. It's work correctly~

I think this issue has fixed!

thank you^^

**Comment by Noshyaar** [comment]
Thanks for letting us know. Closing as fixed. :)
