### ISSUE TITLE
PackedVector2Array.reverse() does nothing on Line2D `points` property

### ISSUE THREAD

**Issue by lapspider45** [godotengine/godot#70666]
### Godot version

v4.0.beta10.official [d0398f62f]

### System information

Linux

### Issue description

[PackedVector2Array.reverse()](https://docs.godotengine.org/en/latest/classes/class_packedvector2array.html#class-packedvector2array-method-reverse) does nothing on the `points` property of `Line2D`. This might be because `points` is built-in?

### Steps to reproduce

``` gdscript
extends Line2D

func _ready():
	points = PackedVector2Array([Vector2(0,0), Vector2(1,1)])
	print(points) # should print [(0, 0), (1, 1)]
	points.reverse()
	print(points) # should print [(1, 1), (0, 0)]
		
#	var points2 = points
#	points2.reverse()
#	print(points2) # correctly prints [(1, 1), (0, 0)]
```

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
Same issue as in #62857 (most likely)
