### ISSUE TITLE
Text color wrong on project manager due to LCD subpixel font rendering not working on OpenGL

### ISSUE THREAD

**Issue by johnhattan** [godotengine/godot#70679]
### Godot version

4.0 beta 10

### System information

Mac M1, MacOS Ventura 13.0.1

### Issue description

This has been happening with all the 4.0 betas, and it's only happening on the Mac. When I start Godot and am presented with the Project Manager, the UI text is always black. Even on the "about" box.

![Screenshot 2022-12-28 at 2 49 46 PM](https://user-images.githubusercontent.com/786744/209870865-222a47c6-c19d-4be5-bee5-6a3b5191d9c9.png)

If I open a project, the text color is shown correctly. Note that the "about" box text is also fixed.

![Screenshot 2022-12-28 at 2 50 24 PM](https://user-images.githubusercontent.com/786744/209871082-5a48c7d6-2396-42f1-b509-2077ec3be617.png)

If, at this point, I tell Godot to return to the Project Manager, the black text reappears.

### Steps to reproduce

It's just doing this from a cold start, so there aren't any steps.

### Minimal reproduction project

N/A

**Comment by spindlebink** [comment]
I have this issue as well on Manjaro Linux with Gnome.

**Comment by Calinou** [comment]
Are you using a custom editor theme? If so, please remove it in the Editor Settings. These resources are not expected to be compatible across Godot versions, and have been changed in backwards-incompatible way since 3.x.

**Comment by spindlebink** [comment]
I wasn't using a custom theme, but deleting `editor_settings-4.tres` fixed it for me.

**Comment by johnhattan** [comment]
Same here. Deleting the file fixed it, but I was just using the default dark theme.

**Comment by Calinou** [comment]
This likely occurs because Godot thinks you are using a light theme, so the icon and font preset is set to "light" instead of "dark" when it's set to Auto. I have no idea why this occurs though.

**Comment by dmaz** [comment]
removing the line
```
interface/editor/font_antialiasing = 2
```
from `editor_settings-4.tres`
fixed it for me

**Comment by UgisBrekis** [comment]
Can confirm- setting "interface/editor/font_antialiasing" to "LCD Subpixel" causes Project Manager to have dark text

**Comment by Calinou** [comment]
This likely occurs because the OpenGL renderer doesn't support rendering fonts with LCD subpixel optimization, and the project manager always runs with the OpenGL renderer.

cc @bruvzg

**Comment by clayjohn** [comment]
> This likely occurs because the OpenGL renderer doesn't support rendering fonts with LCD subpixel optimization, and the project manager always runs with the OpenGL renderer.

The OpenGL renderer does support rendering fonts with the LCD subpixel optimization, there must be a bug somewhere as this is only happening on macOS, and only on some devices at that
