### ISSUE TITLE
Shader color_hint not recognized

### ISSUE THREAD

**Issue by bozoVuksan** [godotengine/godot#70674]
### Godot version

v4.0.beta10.mono.official [d0398f62f]

### System information

Windows 10 Home, Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz   2.90 GHz, 

### Issue description

![image](https://user-images.githubusercontent.com/11051231/209837172-817181a7-45ff-4d27-bebf-29a655861ac4.png)

hint_color is not recognized. Did the hint change?

### Steps to reproduce

Create a shader. create a uniform and add a color_hint. Results into error message: 
![image](https://user-images.githubusercontent.com/11051231/209837402-9586778f-944c-4113-81c6-f5f2ee7103d7.png)

### Minimal reproduction project

-

**Comment by Zireael07** [comment]
It's hint_albedo now IIRC and has been changed a couple betas ago

**Comment by Chaosus** [comment]
It was replaced by `source_color`.

**Comment by bozoVuksan** [comment]
Is this documented somewhere? Because my google search always got me to hint_color.

**Comment by Chaosus** [comment]
You need to look at latest documentation (https://docs.godotengine.org/en/latest/tutorials/shaders/shader_reference/shading_language.html)
