### ISSUE TITLE
Minimum window size not effective from 4.0 beta 9 onwards on Linux

### ISSUE THREAD

**Issue by snoopdouglas** [godotengine/godot#70680]
### Godot version

4.0-beta9

### System information

Fedora Workstation 36

### Issue description

There's been a regression between betas 8 and 9 where setting a minimum size via `DisplayServer.window_set_min_size` doesn't seem to have any effect.

Additionally, I seem to be able to shrink the window down past the normal minimum size of 64x64.

### Steps to reproduce

Call `DisplayServer.window_set_min_size`; note that the window can be resized down past the given size.

### Minimal reproduction project

Trivial.

**Comment by snoopdouglas** [comment]
nb. this still affects beta 10.

**Comment by Sauermann** [comment]
Please have a look at  #70347

**Comment by snoopdouglas** [comment]
@Sauermann Ah yes, looks to be the same thing.
