### ISSUE TITLE
Path3D: Point handles invisible in editor

### ISSUE THREAD

**Issue by Kalamster** [godotengine/godot#70688]
### Godot version

4.0 beta 10

### System information

Windows 10, Vulkan

### Issue description

While the fishbone pattern is visible, the points are not. (Invisible) points can be added to a path and deleted from it, but they can't be moved in the editor viewport, only via inspector properties.
I haven't used 4.9b, but I confirmed the point handles are visible in 4.8b on my system (same file).

### Steps to reproduce

Make a Path3d. Add points via Inspector. Fail to see point handles in the viewport.

### Minimal reproduction project

n/a

**Comment by Calinou** [comment]
cc @xiongyaohua

**Comment by Kalamster** [comment]
This seems to be an issue with updating the data. Points are only visible after the Curve3d settings panel is closed and another node is clicked. They become invisble again if clicking on the Path3d Curve3d settings panel, is this expected behavior after all?
In 4.8b this seems to be not happening.

**Comment by xiongyaohua** [comment]
https://github.com/godotengine/godot/pull/70907

I tracked down the cause of the problem, but I am not sure the fix is appropriate, as I am not familiar enough with the editor code. Need help from more experienced developers.

**Comment by TokageItLab** [comment]
Maybe related by #68498, it maybe affects the collision polygon editor, etc. #70907 seems like a not a very good way to do it because there are too many objects affected, at least if there is no other way to do it, we should merge it very carefully.

I think we will need a fix similar to #70696. @Rindbee thoughts?

**Comment by Rindbee** [comment]
I'm investigating this issue and the plugin for Path2D seems to be working fine.

**Comment by Kalamster** [comment]
I think this issue might also concern SoftBody3d pinned point selection.
