### ISSUE TITLE
Project Camera Overide can't detect project instance.

### ISSUE THREAD

**Issue by MagmaGuy** [godotengine/godot#70697]
### Godot version

4.0 beta 10, mono edition

### System information

Windows 11

### Issue description

No matter what I do Project Camera Override can never detect a game instance.

![image](https://user-images.githubusercontent.com/13719743/209912444-541f642a-42d3-4860-a4e0-54a17dbbab0b.png)

Of relevance: I can see remote nodes. I can see the output in the console. I can see the output in my IDE of choice (Rider). I can toggle debug mode.

It's just the camera that is unable to detect the game instance.

### Steps to reproduce

This happens everywhere, including on a brand new projects where the only nodes are a 2d camera and the Godot svg icon for testing. This also seems to happen when not using Rider as a third party editor.

### Minimal reproduction project

N/A

**Comment by MagmaGuy** [comment]
Addendum: I forgot to mention this, but this report is specifically for my 2d project. I have not tested this for 3d.

**Comment by MagmaGuy** [comment]
Addendum 2: I tested with the 3.5.1 mono edition, the camera override works correctly there so I don't think it's an issue specific to my setup.

Also maybe not the right place to mention this but I don't think there's any documentation for the Project Camera Override, which does sound like it should be in the debug tools section of the official docs.

**Comment by Calinou** [comment]
cc @rxlecky, who implemented this feature in https://github.com/godotengine/godot/pull/27742.
