### ISSUE TITLE
Vulkan Clustered: SpotLight3D clustering artifacts with no fog or other effects

### ISSUE THREAD

**Issue by PieKing1215** [godotengine/godot#70698]
### Godot version

4.0.beta10.official [d0398f62f]

### System information

Windows 10, Vulkan, NVIDIA GeForce RTX 2060m (31.0.15.2698)

### Issue description

I'm getting some kind of clustering/blocky artifact when using spotlights, with no fog or any fancy rendering stuff whatsoever.
I've looked through a bunch of similar issues, but the only ones I could find were related to volumetric fog or other environment effects that I am not using.
Not sure if I'm just missing something, but I think I've played with every option in the spotlight and every option in a WorldEnvironment and nothing makes it go away.

The only lead I have is that the intensity of the artifact seems to be affected by the spot angle. It cycles in a sawtooth pattern every ~0.07 degrees.

![image](https://user-images.githubusercontent.com/13819558/209914720-77a637ea-8cc7-4cff-8216-363f9150885a.png)

Lmk if you need more info or need me to try anything.

### Steps to reproduce

1. New Project (Forward+)
2. Put down some MeshInstance3Ds as a backdrop
3. Put a SpotLight3D
4. Raise spotlight intensity, lower spot angle, and increase range to see it better
5. Slowly increase spot angle to see cycling effect

### Minimal reproduction project

[testspotlight.zip](https://github.com/godotengine/godot/files/10318069/testspotlight.zip)

**Comment by solek1312** [comment]
![Screenshot from 2022-12-31 09-42-56](https://user-images.githubusercontent.com/65317076/210130808-9d56185f-8f98-49e2-b5e2-0cb1ac15f5bd.png)
Haven't confirmed it, looks normal to me.


But I do see a similar effect when I look along a spotlight on this particular omnilight attached to a navigation agent. Doesn't happen with the other ones, might investigate.

![3](https://user-images.githubusercontent.com/65317076/210130925-1d35995e-4618-4e7b-9520-1701afc40e4f.png)

**Comment by Calinou** [comment]
@solek1312 Which operating system and graphics card model are you using?

**Comment by solek1312** [comment]
> Related to #59262 and #45469.
> 
> @solek1312 Which operating system and graphics card model are you using?

Intel i5-1135g7 integrated card, Linux Mint 21

**Comment by Calinou** [comment]
I can confirm this on 4.0.beta 621e32971 (Linux, GeForce RTX 4090 with NVIDIA 525.60.11).

![image](https://user-images.githubusercontent.com/180032/213833640-d30a6010-da20-4699-ada6-99af91a470d1.png)
