### ISSUE TITLE
Godot 4.0 GLTFDocument.generate_scene is not importing nested meshes

### ISSUE THREAD

**Issue by EibrielInv** [godotengine/godot#70709]
### Godot version

v4.0.beta10.official [d0398f62f]

### System information

Xubuntu 22.04

### Issue description

When a glTF file includes a mesh nested under another mesh (for example linking one object to another in Blender), only the meshes on the root level are properly imported to the generated scene.

![imagen](https://user-images.githubusercontent.com/172656/209988973-f4963ef7-aa57-4774-a495-8623a446f32e.png)

In the image you can see the same `.glb` file imported using drag and drop (on the left) vs using `GLTFDocument.generate_scene` (on the right)

### Steps to reproduce

- On Blender create a Cube and a Sphere. Link the Sphere to the Cube and export both objects as a single `.glb` file.
- On Godot 4 setup a 3D scene to load the `.glb` file using the `GLTFDocument.generate_scene` function.
- Setup a camera to run the project.

The expected result is to see a Cube and a Sphere, but only the Cube is visible.

### Minimal reproduction project

Scene ready to test, and `.blend` file

[GLTFBug_v2.zip](https://github.com/godotengine/godot/files/10320776/GLTFBug_v2.zip)

**Comment by Calinou** [comment]
Can you reproduce this on 3.5.1?

**Comment by EibrielInv** [comment]
> Can you reproduce this on 3.5.1?

I think Godot 3.x doesn't have a function equivalent to `GLTFDocument.generate_scene` available at run time. Only Godot 4 allows loading glTF at run time.

**Comment by jamesmintram** [comment]
Can repro with the example scene locally, looking into the root cause
