### ISSUE TITLE
Custom Node Export not working on new scripts

### ISSUE THREAD

**Issue by WesleyElliott** [godotengine/godot#70718]
### Godot version

4.0.beta10.official

### System information

MacOS 12.6

### Issue description

The custom node exporting introduced in #67055 seems to have regressed in beta9 and beta10, but only for newly created scripts. The selection dialog for the export does not allow selecting a node with the script attached unless the engine is restarted (or the project is reloaded).
While looking around, it seems the node isn't being recognised as the custom class. If I hover over the node to show the tooltip, the type is listed as `Node`, not the custom class. After a project reload, the tooltip correctly shows the custom class as the type.

If I change the export type to `Node`, select the node and then change the type back to the custom class, the selection persists, so that seems to be the workaround for now.
This also doesn't seem to be a problem in beta7.

### Steps to reproduce

1. Create a script with a custom `class_name`:
```gdscript
class_name TestClass extends Node
```
2. Create another script with an export of the type declared in step 1:
```gdscript
class_name Main extends Node

@export var testClass: TestClass
```
3. Create a node with the `Main` script assigned
4. Create a node with the `TestClass` script assigned
5. Try set the `testClass` export for the `Main` node to the `TestClass` node

Reloading the project will allowing selecting the `TestClass` node

### Minimal reproduction project

N/A - opening the project will not reproduce the issues. Its best to test on a new project with newly created scripts

**Comment by KoBeWi** [comment]
Sounds related to #70667
The issue is about plugins, but it might apply to any class.

**Comment by WesleyElliott** [comment]
I tried looking into it myself, and seems the wrong path is used to update the class name in `EditorData::_script_class_file_to_path` when the scripts are updated from `EditorFileSystem::_update_script_classes()`:

```c++
EditorNode::get_editor_data().script_class_set_name(efd->files[index]->file, efd->files[index]->script_class_name);
```
The `efd->files[index]->file` doesn't include the `res://` prefex (only the file name). When the project is reloaded, the actual path is used (including the `res://`prefix) - which is why the bug fixes itself when opening or reloading a project.

It seems using `path` instead of the `efd->files[index]->file` fixes the issue.
