### ISSUE TITLE
InputMap action can overflow without scrolling being enabled

### ISSUE THREAD

**Issue by HubbleCommand** [godotengine/godot#70711]
### Godot version

4.0 beta 10

### System information

Windows 11 Vulkan

### Issue description

Looked through the issues list, but couldn't find something like this, sorry in advance if this has already been reported.

There is a few cases (in the pictures below) where list of Actions in Input Map may not always show a scrollbar even if the actions list overflows (I imagine this could also happen for the widget that Input Map uses).

![image](https://user-images.githubusercontent.com/39958198/210003566-cf60dbaf-921f-485b-b0a9-51ffc28d0244.png)

![New Bitmap image](https://user-images.githubusercontent.com/39958198/210004079-8eb2e6a1-0cf5-4a7c-8905-a4e3cfd0ec5d.png)

![image](https://user-images.githubusercontent.com/39958198/210004165-a6b6790b-248a-4f68-b4d0-b44b25afdf4f.png)

![image](https://user-images.githubusercontent.com/39958198/210004537-aca52194-a464-48b9-b818-24782706de45.png)

### Steps to reproduce

The pictures are clearer than anything I could write here: "a picture is worth 1000 words"

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
cc @KoBeWi
