### ISSUE TITLE
OpenGL: Text corruption when interacting with the editor's UI

### ISSUE THREAD

**Issue by RagingRoosevelt** [godotengine/godot#70722]
### Godot version

4.0.beta10.official

### System information

Windows 11 22000.1335, Intel HD Graphics 630, vulcan(?)

### Issue description

Unknown triggers cause sometimes code, sometimes output to look like this:
![image](https://user-images.githubusercontent.com/6985440/210017180-aab1aa83-15f6-40e4-bb70-38f9e62a2f5a.png)

Sometimes previews of imported textures get corrupted, too.

### Steps to reproduce

It seems to crop up just by having Godot open for a while.  Seems to start when changing a setting, going from the code editor to the 2D viewport, etc.  Can work on more detailed troubleshooting with suggestions on what to focus on.

Project Settings / Rendering / Renderer has
* method: gl_compatibility
* method.mobile: mobile
* method.web: gl_compatibility

### Minimal reproduction project

Trying to put one together, seems to be not related to my particular project.

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/68814.

**Comment by RagingRoosevelt** [comment]
> or when using the Vulkan renderer in 4.0.beta10 

How do I set that up?  I had thought I was already using vulkan.  Or do you mean switching from `gl_compatibility` to `forward_plus` or `mobile`?


I'll try to see if I can reproduce on 3.5.1

**Comment by Zireael07** [comment]
@RagingRoosevelt Yes, switch to forward_plus to use Vulkan renderer (or mobile to use a mobile Vulkan renderer)

**Comment by celticintuition** [comment]
I have seen this a few times now (on this beta 10 build, later builds I have been unable to use for different reasons). 

- It can appear in the font preview when working with font overrides and also in the debug window. 
- It is not consistently reproducible with specific steps (for me at the moment). 
- I have an RTX 2080Ti and I am running on Windows 10 as below
- On this occasion I'd opened a project with a scene of about 200MB size and adjusted some of the world environment custom colour settings. I then noticed the corruption. This is all I'm able to report at the moment.

**System**
Device name	WINDOWS-XXXXX
Processor	Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz   3.60 GHz
Installed RAM	48.0 GB
Device ID	XXXXX-XXXXX-XXXXX
Product ID	XXXXX-XXXXX-XXXXX
System type	64-bit operating system, x64-based processor
Pen and touch	Pen support

![image](https://user-images.githubusercontent.com/25031050/216521164-08636e16-35cf-48e8-8bbc-be6c26147417.png)

**Comment by RagingRoosevelt** [comment]
I've had similar experience having difficulty reproducing

**Comment by clayjohn** [comment]
I think this is fixed as of Beta 17

**Comment by clayjohn** [comment]
This may have been fixed by https://github.com/godotengine/godot/pull/72474

It would be very helpful if people who can reproduce this issue could check again using RC1 or later

**Comment by clayjohn** [comment]
Closing as fixed by #72474, please comment if you can reproduce in RC6 or later and I can reopen.
