### ISSUE TITLE
inst_to_dict doesn't create dictionaries for custom classes in the instance

### ISSUE THREAD

**Issue by aqt** [godotengine/godot#70720]
### Godot version

Godot 4.0 beta 10

### System information

Windows 10

### Issue description

I have created a class which may hold other of my classes. Calling `inst_to_dict` on such an instance doesn't convert those members into dictionaries, it will keep the reference to the respective instance.

### Steps to reproduce

Attached project shows the problem.

Actual output:
```JSON
{
  "@path": "res://my_object.gd",
  "@subpath": "",
  "child": "<Node#26508001707>",
  "message": "Parent",
  "my_children": [
    "<Node#26508001707>"
  ]
}
```

Expected output:
```JSON
{
  "@path": "res://my_object.gd",
  "@subpath": "",
  "child": {
    "@path": "res://my_object.gd",
    "@subpath": "",
    "child": null,
    "message": "Child",
    "my_children": [

    ]
  },
  "message": "Parent",
  "my_children": [
    {
      "@path": "res://my_object.gd",
      "@subpath": "",
      "child": null,
      "message": "Child",
      "my_children": [

      ]
    }
  ]
}
```

### Minimal reproduction project

[inst_to_dict.zip](https://github.com/godotengine/godot/files/10322217/inst_to_dict.zip)

**Comment by aqt** [comment]
In the meantime I created this function to work around the problem, which seems to work fine so far.

```GDScript
func recursively_serialize_object(instance: Object) -> Dictionary:
	var dict := inst_to_dict(instance)

	for key in dict:
		var field = dict[key]
		
		if field is Object:
			dict[key] = _recursively_serialize_object(instance)
		elif field is Array:
			var new_array := []
			for entry in field:
				new_array.append(_recursively_serialize_object(entry))
			dict[key] = new_array
			pass
		# else keep value

	return dict
```

**Comment by Calinou** [comment]
Can you reproduce this in 3.5.1?

**Comment by unfa** [comment]
> In the meantime I created this function to work around the problem, which seems to work fine so far.
> 
> ```gdscript
> func recursively_serialize_object(instance: Object) -> Dictionary:
> 	var dict := inst_to_dict(instance)
> 
> 	for key in dict:
> 		var field = dict[key]
> 		
> 		if field is Object:
> 			dict[key] = recursively_serialize_object(field)
> 		elif field is Array:
> 			var new_array := []
> 			for entry in field:
> 				new_array.append(recursively_serialize_object(entry))
> 			dict[key] = new_array
> 			pass
> 		# else keep value
> 
> 	return dict
> ```

This works, but... how to deserialize it afterwards?

**Comment by aqt** [comment]
> > In the meantime I created this function to work around the problem, which seems to work fine so far.
> > 
> > ```gdscript
> > func recursively_serialize_object(instance: Object) -> Dictionary:
> > 	var dict := inst_to_dict(instance)
> > 
> > 	for key in dict:
> > 		var field = dict[key]
> > 		
> > 		if field is Object:
> > 			dict[key] = recursively_serialize_object(field)
> > 		elif field is Array:
> > 			var new_array := []
> > 			for entry in field:
> > 				new_array.append(recursively_serialize_object(entry))
> > 			dict[key] = new_array
> > 			pass
> > 		# else keep value
> > 
> > 	return dict
> > ```
> 
> This works, but... how to deserialize it afterwards?

I don't have access to my computer for a few days, so I'll just post what I am using rather than trying to reduce it to the necessities.

For background I'm using this to deserialize network messages in an online game. I have not had performance in mind but I also haven't ran into such problems yet with my low amount of messages. I want to look into GDExtensions, eventually... There's also assumptions about the data actually being valid since the messages are sent from a server in my control.

I pass a json string like `{"type":"0","payload":{"thing":true}}` to the deserialize function. Payload is the object to deserialize. Type is for knowing the type of the payload instead of just guessing from the data. The types of the payload's fields are inferred from an instance of the class referenced by the type field.

```gdscript
# All the different payload classes
var s2c_payloads := { 
         PayloadType.S2C_CHAT: ChatPayload,
         ...
}

func deserialize(message: String): 
         var packet: Dictionary = JSON.parse_string(message) 
  
         var type: String = packet.get("type") 
         var payload_dict: Dictionary = packet.get("payload") 
  
         var payload_script = s2c_payloads.get(type) 
  
         assert(payload_script != null, "Payload type %s is not defined, run exporter" % type) 
  
         var payload = payload_script.new() 
         _assign_object_values(payload, payload_dict) 
  
         return payload 
  
  
 # object is filled with values from the dictionary 
 func _assign_object_values(object, dict: Dictionary) -> void: 
         for dict_key in dict: 
                 # We get the field from the object to know its type/script 
                 var object_field = object.get(dict_key) 
  
                 if object_field is Array: 
                         var script = object_field.get_typed_script() 
  
                         if script == null: 
                                 # Array is untyped or of a built-in type. Assuming the array 
                                 # items don't need to be deserialized
                                 object.set(dict_key, dict.get(dict_key)) 
                         else: 
                                 # Construct a new entry and add it to the object's existing array 
                                 for array_entry in dict.get(dict_key): 
                                         var instance = script.new() 
                                         _assign_object_values(instance, array_entry) 
                                         object.get(dict_key).append(instance) 
                 elif object_field is Object: 
                         # TODO: I don't have a payload designed like this right now to check 
                         @warning_ignore(assert_always_false) 
                         assert(false, "Does this code work") 
                         var instance = object_field.new() 
                         _assign_object_values(instance, dict.get(dict_key)) 
                         object.set(dict_key, instance) 
                 else: 
                         # Should be a built-in type, so set what we got from parsing json 
                         object.set(dict_key, dict.get(dict_key))
```

If you need this code to be licensed then just consider it MIT licensed.

**Comment by aqt** [comment]
> Thank you! I will analyze this and probably use in my game (a multiplayer shooter).

No worries. Exciting!

> I assume the code above works in conjuction with the serializing method you've pasted before?

Yes, roughly. With the addition of the type field and stringifying. Using it like this:

```gdscript
func serialize(payload) -> String: 
         var type = c2s_payloads.get(payload.get_script()) 
  
         assert(type != null, "No type defined for payload %s, run exporter" % payload.get_script().get_path()) 
  
         var payload_dict: Dictionary = _recursively_serialize_object(payload) # Function I had pasted previously 
  
         var packet_dict := { 
                 "type": type, 
                 "payload": payload_dict 
         } 
  
         return JSON.stringify(packet_dict) 
```
