### ISSUE TITLE
MultiplayerSpawner doesn't replicate spawn properties once the node's authority has changed (on _enter_tree)

### ISSUE THREAD

**Issue by lethiandev** [godotengine/godot#70739]
### Godot version

v4.0.beta10.official [d0398f62f]

### System information

Windows 10, Vulkan mobile, AMD Radeon RX 6600 XT

### Issue description

Hello, I'm playing around with the new high-level multiplayer and I've encountered an issue, it seems like the MultiplayerSpawner ignores initial properties for the spawned nodes (or resets it idk), after changing the node's authority on `_enter_tree` - to let remote players control their hero in a coop game.

There's what I'm getting when switching node's authority on `_enter_tree` callback:
[net-set-authority.webm](https://user-images.githubusercontent.com/5323129/210075747-d4701c6d-5371-4b94-a7e1-2086eadbadbb.webm)
Notice the player's starting position from (0,0) (which should have been random) and the colour isn't matching with the remote.

And there's what I'd expect - I solved the issue using `_spawn_custom`, but it doesn't seem right, that it isn't supported out of the box nevertheless:
[net-expected.webm](https://user-images.githubusercontent.com/5323129/210075957-d7c20ca6-0fcb-4d9c-9ac8-263e31c45ec0.webm)

#### Expected
I should be able to replicate the node's authority on initialization, such as `_enter_tree`, or when setting up the authority on scene instantiating, before the node's getting appended into the scene tree, like:
```
# Players.gd (Node type, as spawn target of the MultiplayerSpawner)
func spawn_player(id):
	var player = PlayerScene.instantiate()
	player.set_multiplayer_authority(id)
	# ... some additional parameters
	add_child(player)
```

### Steps to reproduce

1. Create a new project.
2. Add an initial networking code, like Host/Join buttons with ENet/SceneMultiplayer initialization etc.
3. Place a MultiplayerSpawner in the tree somewhere and setup their target node.
4. Create a player scene, with basic controller script like:
```
func _enter_tree():
	# Switch authority to the remote/local player
	set_multiplayer_authority(name.to_int())

func _ready():
	# To disable the inputs handling
	if not is_multiplayer_authority():
		set_physics_process(false)

func _physics_process(delta):
	var direction = Input.get_vector("ui_left", "ui_right", "ui_up", "ui_down")
	velocity = direction * SPEED
	move_and_slide()
```
5. Add MultiplayerSynchronizer to sync some spawn properties like modulation
6. Add spawning code for the Players node, like:
```
func spawn_player(id):
	var player = PlayerScene.instantiate()
	player.transform.origin = Vector2(randf(), randf()) * 300 + Vector2(64, 64)
	player.modulate = [Color.RED, Color.TEAL, Color.YELLOW][randi()%3]
	player.set_name("Player_%d" % id)
	add_child(player)
```
7. Spawn the players upon host and peer joined to instantiate the player. 

### Minimal reproduction project

There's small demo - to change the spawn approach, please remove the extra `_` from `__spawn_custom` in `spawner.gd` script. And change target node responsible for spawning in the `prison_stage.gd` script - to use `_spawn_custom` instead of the default behaviour.

[platformer-prototype.zip](https://github.com/godotengine/godot/files/10324927/platformer-prototype.zip)

**Comment by cridenour** [comment]
I feel this is by design. It seems to me if you want the object to inherit properties, the server should remain the authority. 

It's common with these nodes to have child Node that the client gets authority over (usually called PlayerInput or PlayerNetworking that I've seen) while the rest of the player scene is still controlled by the server.

I'm also doing a co-op game so client input checking isn't important, so I just sync over position/rotation/etc from the PlayerNetworking node to the other players, where more competitive games will just stream Input commands and update the game state as usual. But what is the same is the player itself is under the authority of the server, which as you're seeing here is a requirement of being spawned by a MultiplayerSpawner.

**Comment by lethiandev** [comment]
Thanks for the clarification! Yeah sounds about right, it's still achievable through `_spawn_custom` if needed. I tried to compensate input lags for other players by giving them full authority over their nodes. This might be a naive approach, but I also think since it's a co-op game, checking inputs isn't that important.
