### ISSUE TITLE
Create a Plugin dialog's text fields do not expand to fit the whole dialog window

### ISSUE THREAD

**Issue by Yagich** [godotengine/godot#70746]
### Godot version

4.0b10

### System information

Linux/Manjaro

### Issue description

Most dialogs in the editor scale their text field Controls to fit the whole window when it's resized, but the plugin creation dialog does not: 
![image](https://user-images.githubusercontent.com/24468819/210095286-e53bc450-dcdc-472c-acc7-f8b3532a0ca2.png)

### Steps to reproduce

1. Go to Project Settings -> Plugins -> Create New Plugin
2. Resize the new dialog

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Can you reproduce this in 3.5.1?

**Comment by Yagich** [comment]
No. The dialog is not resizable in 3.5.1.

**Comment by jamesmintram** [comment]
Happy to look at this

**Comment by mastermarkus** [comment]
Quick glance, It seems horizontal sizing flags are not set for the GridContainer where the LineEdit boxes are in `https://github.com/godotengine/godot/blob/8a98110e3e353a9a3b86b4a0bd56adf405bd6d93/editor/plugin_config_dialog.cpp#L211-L344`
Adding these 2 lines to the GridContainer should do the trick
```cpp
grid->set_h_size_flags(Control::SIZE_EXPAND_FILL);
grid->set_v_size_flags(Control::SIZE_EXPAND_FILL);
``` I'm unable to test this myself cause the latest raw 4.0 crashes on start, but maybe somebody confirm this works?

**Comment by jamesmintram** [comment]
> 

I tried that and it didn't fix the issue. 

I have added `set_h_size_flags(Control::SIZE_EXPAND_FILL);` to each of the line edits (as done in other similar UI code) and it resolves the problem.
