### ISSUE TITLE
GoDot VPL for scripts and shaders

### ISSUE THREAD

**Issue by berserk82** [godotengine/godot#7074]
**Windows 10 Pro x64 - Godot version: 2.1**

**Issue description** I would like to code with GoDot using something like BluePrints for Unreal:

**Steps to reproduce:** None

**Link to minimal example project** (optional but very welcome): None

Hello everyone.
I like GoDot very much, but I would like it more if it had a visual scripting language for scripts and shaders.
Something like BluePrints for Unreal Engine, or something like Korduene (http://www.korduene.com/).

Thanks in advance for any help.

Bye, Ivano.

**Comment by volzhs** [comment]
Godot has Visual script on current master.

Download latest unofficial version and try it.
http://fixnum.org/godot/
https://archive.hugo.pro/godot/

And there is youtube video for this.
https://www.youtube.com/watch?v=FFuzNOGJr14

**Comment by vnen** [comment]
Note that visual scripting for shaders exists in 2.1.

Closing since this is already done.

**Comment by vnen** [comment]
Also, it's *not* "GoDot". It's **Godot**, with lowercase `d`.

**Comment by berserk82** [comment]
But this doesn't exist for scripting. Apologizes for the lowercase d.

**Comment by vnen** [comment]
It does exist in the current code. It was made after 2.1 stable though, so to use it you have to download and compile (or get an unofficial version). Or wait for the next major version.

**Comment by vnen** [comment]
Here's a sample from the [Platformer demo](https://github.com/godotengine/godot-demo-projects/tree/master/visual_script/platformer):

![godot windows opt tools 64_2016-11-09_01-09-19](https://cloud.githubusercontent.com/assets/5599796/20126059/4dae50f2-a619-11e6-8ca2-028d96f36a3d.png)
