### ISSUE TITLE
4.0: GPUParticles2D particle jittering in global coordinates if attached to moving node

### ISSUE THREAD

**Issue by birdbrainzzg** [godotengine/godot#70748]
### Godot version

4.0 beta 10

### System information

Windows 10, Vulkan, GeForce 1070

### Issue description

In Godot 4 beta 10 there is a visible issue with gpuparticles2d, which I noticed by attaching one to a characterbody2d. The particles exhibit noticeable jitter as the parent node moves around. The jitter stops if the node stops moving and particles will then continue to elapse normally even if they jittered previously.

![particlejitter](https://user-images.githubusercontent.com/121687184/210098540-3151f87c-0b00-4000-a190-0b332971e81a.gif)

I notice the issue on Vulkan or Mobile but not on gl_compatibility.

By limiting max FPS I discovered that the issue is somewhat affected by FPS. If I have unlimited max fps it is very noticeable, and it's also quite noticeable down to 30 FPS, upon which it switches to sudden subtle jerks rather than constant jitter - below that it vanishes. At 12 FPS, it is no longer noticeable at all. I have no idea why.

It is the same if it is attached to a CharacterBody2D moving around with move_and_slide() or a Node2D moving around by an animation player changing its position with a track. it takes a certain amount of speed to notice the jitter as at low speeds it seems more like a blur if it is noticeable at all

The issue is NOT affected by the following things that I've tried:
- Interpolation on/off on the gpuparticles2d node
- Resolution of project or stretch mode used or gpu snapping options used

### Steps to reproduce

From a blank Godot project, 
- add a CharacterBody2D that can move around, using the default movement template is fine
- add a default gpuparticles2d to it that emits visible particles in global coordinates
- Observe particles as you move the character around. 

- Alternatively just attach particles to and change the position and/or rotation of a node2d with an AnimationPlayer and have it move back and forth on the screen from one side to another quite quickly and it should display the same issue.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/51318 and https://github.com/godotengine/godot/issues/50824.

**Comment by clayjohn** [comment]
Fixed by https://github.com/godotengine/godot/pull/71520
