### ISSUE TITLE
Large objects are displayed in the "Stack Variable" list as <null>

### ISSUE THREAD

**Issue by tebz** [godotengine/godot#70756]
### Godot version

v4.0.beta10.official [d0398f62f]

### System information

Windows 10, 32GB ram

### Issue description

Large arrays/images (and probably other objects) are displayed in the "Stack Variable" list as "null"
It would be nicer if they were displayed as "to large to display", if it's not possible to display them in the "Stack Variable" list 
The limit seems to maybe be 0xffff bytes.

### Steps to reproduce

	var nnn := []
	var rnd = RandomNumberGenerator.new()
	for i in 262142:
		nnn.append(rnd.randi)
	# put breakpoint here

### Minimal reproduction project

N/A

**Comment by L4Vo5** [comment]
This affects any Object as long as the sum of its _exported_ variables is big enough.
The limit seems to be 2^20 bytes.
Annoyingly, it propagates infinitely. I encountered this bug when I had a Resource storing another Resource into an exported array, and the second Resource happened to have a big enough exported variable inside.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/39465.
