### ISSUE TITLE
Auto completion gets blocked by helper in strings

### ISSUE THREAD

**Issue by mateusak** [godotengine/godot#7075]
When writing NodePaths or other kind of strings, the helper shows up to demonstrate the use of the current function. And it's **very** annoying. I've lost count on how many times I couldn't use the auto completion feature because it switched to the helper. Just try to get_node by script, it's way harder than it should.

**Comment by bojidar-bg** [comment]
I'm unable to fully understand the issue, can you provide a screenshot?

**Comment by mateusak** [comment]
![untitled-2](https://cloud.githubusercontent.com/assets/18586380/20111761/9c1abaee-a5d0-11e6-8d38-04ece30902ee.png)

It should show up "Main menu", "Main menu/something", etc. It does show up at times, but doesn't at others. Very strange. A simple way to fix it would be that no helper is shown after the ".

**Comment by volzhs** [comment]
I think this shows problem.

![helper](https://cloud.githubusercontent.com/assets/8281454/20114887/7e422a84-a639-11e6-8615-64d165e9a2ce.gif)

**Comment by volzhs** [comment]
I tested for `get_node("Main ` with current master.
It shows helper (with white box) but changed to node path suggestion list within a second.
but anyway, my demo gif is related in somehow, I guess.

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by DualMatrix** [comment]
This doesn't appear anymore in 3.1 master and 2.1.5

**Comment by Chaosus** [comment]
Cool, thanks !
