### ISSUE TITLE
Missing / non-functional editor bindings

### ISSUE THREAD

**Issue by ReturnMinusOne** [godotengine/godot#70750]
### Godot version

v3.5.1.stable.arch_linux

### System information

Manjaro Linux (kernel 6.1.1-1); system language: French

### Issue description

Some keyboard mappings are either not functional, or missing:

- The "Numbersign" (#) key is not detected when the Alt key is held down, so setting an action to `Alt + #` is not possible. (The key is just under Esc on my keyboard, where the Tilde key is on US keyboards.)

- The "Uppercase" binding is missing.

- The "Lowercase" binding is missing.

### Steps to reproduce

Attempt setting a shortcut with the "Alt + #" combination, or setting the "Uppercase" or "Lowercase shortcuts.

### Minimal reproduction project

N/A

**Comment by ZangEldor** [comment]
Tested with Linux Mint, French (Canda) layout and it seems to work in the latest devlopment version.
However, for this to work I was needed to disable the deafult ALT+# (or ` in US layout) shortcut binding which was for switching group windows (if you don`t want to disable this key binding you can always press # and then tick the alt box in the key-binding window).
For the upper and lower case binding, can you please explain what do you mean? As far as I know, there isn't specific buttons for upper and lower cases other than the regular capslock button which exists in godot.

**Comment by ReturnMinusOne** [comment]
I can't find this "switch group windows" binding; is it a 4.0 feature? I'm using 3.5.1 stable.

Regarding the "uppercase" and "lowercase" shortcuts, I was referring to shortcuts for converting previously written characters to uppercase or lowercase. However, I can't see these shortcuts in any of the recent Godot versions, so I suppose I must have conflated it with another program...

Clearly it's my mistake; apologies. That said, it is a useful feature that I wish were supported by the script editor.

**Comment by ZangEldor** [comment]
switch group windows is a built in linux key bindning for changing the current open window of the current open application (rather than switching applications, as alt+TAB do), nothing to do with godot

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/66678.

**Comment by ReturnMinusOne** [comment]
> switch group windows is a built in linux key bindning for changing the current open window of the current open application (rather than switching applications, as alt+TAB do), nothing to do with godot

Well, there it is; removing that shortcut in the system settings worked, and it's now possible to use the Alt+# combo in Godot. Thank you.

Oddly, the OS shortcut doesn't seem to work in any applications (web browsers, file browser, etc.), but it was still blocking the combination in Godot.

> @ReturnMinusOne Can you reproduce the issue with the hash symbol (`#`) in 4.0beta10?

Apologies, I see now that this was an OS shortcut conflict. Hopefully this thread will be useful to others with the same problem in the future.
