### ISSUE TITLE
The custom Mainloop inherited from SceneTree does not work properly

### ISSUE THREAD

**Issue by Hapenia-Lans** [godotengine/godot#70764]
### Godot version

4.0 beta 10, also 3.5.1

### System information

Windows 11

### Issue description

Creating a Mainloop inherited from SceneTree makes sense when you want to add a few features to SceneTree instead of starting from scratch. Unfortunately, this doesn't work as well, as if its type is erased.

But inheriting from Mainloop directly (in the example) can work properly.

### Steps to reproduce

1. Create a mainloop extends SceneTree. In this case, I call it `MyGDScriptMainLoop`.

```gdscript
class_name MyGDScriptMainLoop extends SceneTree

func say_hello():
    print("hello")
```

2. Go to project settings, set `application/run/main_loop_type` to `MyGDScriptMainLoop`.
3. Create a test scene and try to call `Engine.get_main_loop().say_hello()`.

```gdscript
extends Node2D


# Called when the node enters the scene tree for the first time.
func _ready() -> void:
    Engine.get_main_loop().say_hello()
    pass # Replace with function body.
```

Then you will see:

![image](https://user-images.githubusercontent.com/93276898/210129049-0250a15f-2f87-49a1-b066-16ef5e695302.png)

And also I found that `Engine.get_main_loop() is MyGDScriptMainLoop` is `false`.

Using GDExtension to do this also failed. But since I'm using godot-rust, I'm not sure if this problem exists with godot-cpp.

### Minimal reproduction project

[bug.zip](https://github.com/godotengine/godot/files/10327002/bug.zip)

**Comment by KoBeWi** [comment]
Seems like custom main loop does not take script classes into account. It instantiates the base type, but does not attach the script.
Not sure why it would fail with GDExtension though.

**Comment by Hapenia-Lans** [comment]
> Seems like custom main loop does not take script classes into account. It instantiates the base type, but does not attach the script. Not sure why it would fail with GDExtension though.

I thought so at first, but I found that the examples in the document worked as well.

![image](https://user-images.githubusercontent.com/93276898/210135577-5c72466d-92bd-4747-817b-b83f25ada4a9.png)

**Comment by KoBeWi** [comment]
Ah right, I forgot about the part where MainLoop works...
No idea then.

**Comment by kleonc** [comment]
The main loop is being set correctly, just too late. I've opened PR with a fix. Before that as a workaround you could e.g. await for a single frame like:
```gdscript
extends Node2D

func _ready() -> void:
	#Engine.get_main_loop().say_hello() # Fails.
	await get_tree().process_frame
	Engine.get_main_loop().say_hello() # Works.
```

**Comment by Hapenia-Lans** [comment]
I also found this issue in 3.5.1. @kleonc

**Comment by kleonc** [comment]
> I also found this issue in 3.5.1. @kleonc

I've already marked #70771 for cherry-picking to 3.x/3.5 (meaning when it will be merged it should be backported) so I guess I've checked that as well back then (now I don't remember:smile:).
