### ISSUE TITLE
Modulate for UI nodes

### ISSUE THREAD

**Issue by mateusak** [godotengine/godot#7076]
Some of the nodes which should have modulate doesn't even offer you an option to the change color or if it does it's a lengthy process. Nodes like panel, button, labels, etc. Having to create a new StyleBoxFlat and edit it's color (and update it by moving or something, you should look into that too, it's strange) every time you create a panel is very time consuming and makes the tedious job of making an UI into an ocean of boredom.

**Comment by vnen** [comment]
AFAIK this is already changed in the gles3 branch. Now every node has a modulate option that can also apply to the children nodes.

UI usually uses a single theme everywhere, rarely one want to do a rainbow and change each control individually. Themes also make easier the job of changing the UI look.

Now the StyleBox not updating when editing, it's probably some missing `emit_signal` to update the view.

**Comment by hubbyist** [comment]
I had similar issues about especially with autoarranging of subnodes under container type nodes so I opened #4951 as a semi workaround for this matter. So if this is solved my proposal can be closed as well. :smile:

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by vnen** [comment]
As I said back then, it was available in the dev branch which is now in the stable release, so this is already available. If the update is still a problem, just open a new issue.
