### ISSUE TITLE
Shortcut for Reparent to New Node not working

### ISSUE THREAD

**Issue by aXu-AP** [godotengine/godot#70768]
### Godot version

3.5.1, 4.0 beta 10

### System information

Windows 10

### Issue description

I tried to set a shortcut for `Reparent to New Node`, but the shortcut doesn't trigger. As it's closest neighbour, I tried setting the same shortcut for `Reparent` without problems.

### Steps to reproduce

* Set editor shortcut for `Reparent to New Node` (I set it as Ctrl+G as to group nodes together, but anything is fine - it's not about conflicting shortcut)
* Select a node and press your chosen hotkey

### Minimal reproduction project

N/A (any project is fine, requires modifying editor settings anyway)

**Comment by KoBeWi** [comment]
Missing case in `shortcut_input()` method.

**Comment by jamesmintram** [comment]
Gonna take a look

**Comment by TrueSgtMonkey** [comment]
Thank you for this! Just applied https://github.com/godotengine/godot/pull/70779 to my fork and it works.
