### ISSUE TITLE
vkCreateComputePipelines failed with error -1000012000

### ISSUE THREAD

**Issue by cchute** [godotengine/godot#70772]
### Godot version

4.0 beta 10 mono

### System information

Apple macbook m1 pro 14" OSX 13.0.1 

### Issue description

When trying to create a compute shader as per the tutorial: https://docs.godotengine.org/en/latest/tutorials/shaders/compute_shaders.html

Fails to create the compute pipeline.

E 0:00:01:0727   Godot.NativeInterop.godot_bool Godot.Bridge.CSharpInstanceBridge.Call(IntPtr , Godot.NativeInterop.godot_string_name* , Godot.NativeInterop.godot_variant** , Int32 , Godot.NativeInterop.godot_variant_call_error* , Godot.NativeInterop.godot_variant* ): vkCreateComputePipelines failed with error -1000012000.
  <C++ Error>    Condition "err" is true. Returning: RID()
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:6508 @ compute_pipeline_create()
  <Stack Trace>  Godot.NativeInterop.NativeFuncs.generated.cs:332 @ void Godot.NativeInterop.NativeFuncs.godotsharp_method_bind_ptrcall(IntPtr , IntPtr , System.Void** , System.Void* )()
                 NativeCalls.cs:7296 @ Godot.RID Godot.NativeCalls.godot_icall_2_799(IntPtr , IntPtr , Godot.RID , Godot.NativeInterop.godot_array )()
                 RenderingDevice.cs:985 @ Godot.RID Godot.RenderingDevice.ComputePipelineCreate(Godot.RID , Godot.Collections.Array`1[Godot.RDPipelineSpecializationConstant] )()
                 ComputePixel.cs:46 @ void ComputePixel.compute()()
                 ComputePixel.cs:11 @ void ComputePixel._Ready()()
                 Node.cs:1815 @ Boolean Godot.Node.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name& , Godot.NativeInterop.NativeVariantPtrArgs , Godot.NativeInterop.godot_variant& )()
                 ComputePixel_ScriptMethods.generated.cs:38 @ Boolean ComputePixel.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name& , Godot.NativeInterop.NativeVariantPtrArgs , Godot.NativeInterop.godot_variant& )()
                 CSharpInstanceBridge.cs:24 @ Godot.NativeInterop.godot_bool Godot.Bridge.CSharpInstanceBridge.Call(IntPtr , Godot.NativeInterop.godot_string_name* , Godot.NativeInterop.godot_variant** , Int32 , Godot.NativeInterop.godot_variant_call_error* , Godot.NativeInterop.godot_variant* )()

### Steps to reproduce

Follow the c# tutorial and hit run: https://docs.godotengine.org/en/latest/tutorials/shaders/compute_shaders.html . You can see this in my example project under ComputePixel.cs

### Minimal reproduction project

[Pixel1.zip](https://github.com/godotengine/godot/files/10327520/Pixel1.zip)

**Comment by clayjohn** [comment]
This is a macOS specific issue. The tutorial uses doubles, but Metal (and thus macOS devices) doesn't support doubles in shaders. The tutorial should be using floats instead which is exactly what https://github.com/godotengine/godot-docs/pull/6468 does

**Comment by cchute** [comment]
Out of curiosity is there any way we can include some better error messages for this? I've heard from others that they can't use compute shaders either in V4.0. I think some proper error messages would be extremely useful

**Comment by clayjohn** [comment]
> Out of curiosity is there any way we can include some better error messages for this? I've heard from others that they can't use compute shaders either in V4.0. I think some proper error messages would be extremely useful

For some errors it is possible. I'm not sure about this specific case as the only information we have to go off of is the fact that the Shader is invalid (thats what the ``-1000012000`` code means). I just happened to quickly identify the issue was with doubles because the shader is very short. 

In general the errors you get from shaders should be pretty good, but some (like this) arise because of a mismatch between Vulkan and Metal. As an Apple user you end up suffering because Apple refuses to implement open standards and we are kinda stuck until we find someone willing to implement a Metal backend.

**Comment by cchute** [comment]
I hear you.

Also just wanna say you guys rock for what you're doing, I am so excited to fully get away from Unity once Godot 4.0 is finished :)

**Comment by MKB-dragon** [comment]
Hi, I was about to use Godot 4.0, but then when I try to open a project it gives me the same error....and I'm on Windows(10) on a Wacompro16......I can open the program, but when I launch any (new) project it crashes and this error appears.

thanks in advance

**Comment by q8f13** [comment]
Same issue here.  Creating empty project
Windows10 22H2 19045.2728

> Godot Engine v4.0.2.stable.official.7a0977ce2 - https://godotengine.org
> OpenGL API 3.3.0 NVIDIA 385.54 - Compatibility - Using Device: NVIDIA Corporation - Quadro M6000
> 
> Editing project: e:/GodotProjects/HelloV4
> Godot Engine v4.0.2.stable.official.7a0977ce2 - https://godotengine.org
> vkEnumerateInstanceVersion not available, assuming Vulkan 1.0.
> Vulkan API 1.0.49 - Forward+ - Using Vulkan Device #0: NVIDIA - Quadro M6000
> ERROR: vkCreateComputePipelines failed with error -1000012000.
>    at: (drivers/vulkan/rendering_device_vulkan.cpp:6517)

**Comment by sbond75** [comment]
Found a workaround using command line arguments when starting Godot: `--rendering-driver opengl3` followed by the path to the project to open

**Comment by Zireael07** [comment]
Kinda obvious as vkCreateComputePipelines is a Vulkan error and OpenGL 3 is ... not Vulkan

**Comment by Wolf-SO** [comment]
I still observed this issue on Win 10 Pro 22H2 19045.3208, updating my Nvidia driver made it finally disappear. Before that, the workaround `--rendering-driver opengl3` mentioned by @sbond75 helped.

Is there a way to specify that the “best” available rendering engine should be used (something like `--rendering-driver auto` or `--rendering-driver default`), or can/should I script/implement the detection myself?

**Comment by Calinou** [comment]
> Is there a way to specify that the “best” available rendering engine should be used (something like --rendering-driver auto or --rendering-driver default), or can/should I script/implement the detection myself?

This is not implemented yet, and you can't do it without modifying the engine source: https://github.com/godotengine/godot/issues/58927
