### ISSUE TITLE
Godot 4 script editor throws errror when hover on minimap

### ISSUE THREAD

**Issue by littlexfish** [godotengine/godot#70775]
### Godot version

4.0 beta 10

### System information

Windos 10, Vulkan, NVIDIA GeForce GTX 1050 (31.0.15.2647)

### Issue description

When opened file is 196 or 197 lines, script editor throws error when hover on minimap.
I also found that only happen on "Output" is opened.
The error shows attach below.

`scene/gui/text_edit.cpp:3602 - Index p_line_from = -1 is out of bounds (text.size() = 196).`
`scene/gui/text_edit.cpp:3602 - Index p_line_from = -1 is out of bounds (text.size() = 197).`

https://user-images.githubusercontent.com/50160052/210150255-08ce5875-aa82-47f4-8d34-d151ade24c01.mp4

### Steps to reproduce

Open a file and input any text to 196 or 197 lines.
Mouse hover on script editor minimap.
Throws error.

### Minimal reproduction project

N/A

**Comment by littlexfish** [comment]
I wish to supply some additional information about this, it just happen when Output is opened.

**Comment by jamesmintram** [comment]
Taking a look
