### ISSUE TITLE
ResourceLoader fails to load nested resources saved in .tres files when a value is passed through the _init of such nested resource.

### ISSUE THREAD

**Issue by Sirosky** [godotengine/godot#70783]
### Godot version

Godot_v4.0-beta10_win64

### System information

Windows 11, Vulkan, Intel integrated graphics

### Issue description

I've been using resources to serve as a savegame, and resources nested within the `Save` resource to represent data from the game (e.g., player stats, inventory). However, it appears that when there are variables passed through the `_init()` function of the nested resources, `SubResource`, Godot doesn't deserialize the nested resource properly.

For example, you won't be able to access the `hp` value of the nested resource here.

![image](https://user-images.githubusercontent.com/2752448/210156422-90895e0c-d1b7-4fdb-91f5-34aa9e2fdee7.png)

### Steps to reproduce

**Minimal Reproduction Project**

1. Run project, click save button.
2. Save button will create a new .tres save resource, and pass a variable through `_init()` of the nested subresource.
3. Click load button.
4. Load button will attempt to read the subresource's `hp` value, at which point Godot throws an error.

### Minimal reproduction project

[ResourceFormatLoaderText Bug.zip](https://github.com/godotengine/godot/files/10328023/ResourceFormatLoaderText.Bug.zip)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/15866 and https://github.com/godotengine/godot/issues/30572 (likely the same cause).
