### ISSUE TITLE
unshaded mesh is brighter than albedo set in fragment shader with vulkan renderer

### ISSUE THREAD

**Issue by jmdejong** [godotengine/godot#70797]
### Godot version

v4.0.beta10.official.d0398f62f

### System information

archlinux; vulkan on dedicated `NVIDIA GeForce RTX 3060 Laptop GPU`; opengl3 on integrated `AMD Radeon Graphics (renoir, LLVM 14.0.6, DRM 3.49, 6.1.1-arch1-1)`

### Issue description

When using the fragment shader to set an albedo then the color that is rendered much too bright, even when the mesh is unshaded.
This happens with the vulkan renderer, but it does not seem to happen with the opengl3 renderer.

With vulkan renderer :
![too bright texture from vulkan renderer](https://user-images.githubusercontent.com/7968950/210169368-53a394da-2332-41fe-b6ba-5416c7f2f991.png)

With the opengl3 renderer this does not occur:
![texture with correct brightness but missing interpolation from opengl3 renderer](https://user-images.githubusercontent.com/7968950/210169441-bc727a75-570b-451e-a9e0-d7c3cdac2b45.png)
(The lack of interpolation seems to be [a different problem](https://github.com/godotengine/godot/issues/70799))

Used texture: ![original grass texture](https://user-images.githubusercontent.com/7968950/210169393-469c0b2f-fa94-4ceb-a454-65e7114a64e2.png)

Shader:
```shader_type spatial;
render_mode world_vertex_coords, unshaded;

uniform sampler2D tex;

void fragment() {
	ALBEDO = texture(tex, UV).xyz;
}
```
This example uses the render mode `unshaded` for simplicity, but when lightning calculations do occur then this shader still shows a brighter color than expected

### Steps to reproduce

View a mesh that uses the shader above and is given a texture as parameter in a project with the vulkan renderer

### Minimal reproduction project

[texturebrightness.zip](https://github.com/godotengine/godot/files/10328684/texturebrightness.zip)

**Comment by jmdejong** [comment]
I just found out that this does not seem to be related to textures: setting the albedo to `vec3(0.0, 0.5, 0.0)` will result in the mesh having color `#00bc00` in the vulkan renderer. With the opengl3 renderer it is `#008000`, which I would expect.

**Comment by Calinou** [comment]
This is likely a sRGB ↔ linear conversion issue.

**Comment by jmdejong** [comment]
Yes, adding that fixed the difference in color

**Comment by jmdejong** [comment]
When setting the albedo without a texture there is still a difference in color.

![albedo_squares](https://user-images.githubusercontent.com/7968950/210182142-d7360b2a-452e-4344-b64f-dbbdeec93318.png)
The left square is a standardmaterial that is unshaded and has albedo `#008000` while the right square is from a shader that sets the albedo to `vec3(0.0, 0.5, 0.0)`. On the opengl3 backend both squares are the same color, but on vulkan the right one is brighter.

used shader:
```shader_type spatial;
render_mode unshaded;

void fragment() {
	ALBEDO = vec3(0.0, 0.5, 0.0);
}
```
Minimal reproduction project:
[albedobrightness.zip](https://github.com/godotengine/godot/files/10329318/albedobrightness.zip)

**Comment by clayjohn** [comment]
This isn't a bug, you are just forgetting the ``source_color`` hint when you set your uniform sampler2D See the docs for uniforms here:
https://docs.godotengine.org/en/latest/tutorials/shaders/shader_reference/shading_language.html#uniforms

In the second MRP you are setting the quads to two different colors. The quad on the left is in sRGB space while the quad on the right is in linear space.

**Comment by kb173** [comment]
I hope it's okay to add something here because this issue was a top search result while debugging a similar problem I had:

Even with `source_color` or no custom shader (just a standard material with an Albedo texture), my texture appeared too bright in the editor. I set the material to `unshaded` and compared screenshots with the original texture to confirm that it was quite a bit too bright.

The reason was that Godot's viewport is set to the _Filmic_ tonemap by default. It can be changed to _Linear_ here:

![image](https://github.com/godotengine/godot/assets/18697097/d2ce8b7e-8a94-4844-906e-5db6f4bb92af)

I know this is intended, but I figured adding a comment here might help people with the same problem in the future.

**Comment by souplamp** [comment]
> I know this is intended, but I figured adding a comment here might help people with the same problem in the future.

I am from the future. Thank you.

PS. If anyone is trying to use source_color (as mentioned above) in the VisualShader editor, make sure to go to your Texture2D node dropdown where it says "Data" and change it to "Color".
