### ISSUE TITLE
Shaders in opengl3 renderer do not interpolate texture

### ISSUE THREAD

**Issue by jmdejong** [godotengine/godot#70799]
### Godot version

v4.0.beta10.official.d0398f62f

### System information

archlinux; vulkan on dedicated NVIDIA GeForce RTX 3060 Laptop GPU; opengl3 on integrated AMD Radeon Graphics (renoir, LLVM 14.0.6, DRM 3.49, 6.1.1-arch1-1)

### Issue description

Setting the albedo in the fragment shader based on a sampled texture does not do any interpolation between the pixels of the texture with the opengl3 renderer.

Example of viewing a quadmesh with a green texture in opengl3:
![opengl_texture](https://user-images.githubusercontent.com/7968950/210169814-24442ce3-3f96-47a4-963c-ec74db7c191a.png)

Same view with the vulkan renderer:
![vulkan_texture](https://user-images.githubusercontent.com/7968950/210169826-63baf073-30a2-4f93-b293-e47d1fddfa4a.png)
(the brightness seems to be [a different problem](https://github.com/godotengine/godot/issues/70797))

used texture: 
![ground_grass](https://user-images.githubusercontent.com/7968950/210169858-01a7d75a-c503-48ca-b1a1-5e74bf047e95.png)

Shader:
```shader_type spatial;
render_mode world_vertex_coords, unshaded;

uniform sampler2D tex;

void fragment() {
	ALBEDO = texture(tex, UV).xyz;
}
```

### Steps to reproduce

- Create a mesh with the shader mentioned above
- View that mesh from up close with the opengl3 renderer

### Minimal reproduction project

[texturebrightness.zip](https://github.com/godotengine/godot/files/10328697/texturebrightness.zip)

**Comment by Calinou** [comment]
Does it work if you use `uniform sampler2D tex : filter_linear;`?

**Comment by clayjohn** [comment]
Indeed it sounds like the OpenGL renderer isn't using the same defaults as the Vulkan renderer. It should.

**Comment by jmdejong** [comment]
Yes, using `filter_linear` fixed it.

In my full project I had to use `filter_linear_mipmap` to get the correct results. It seems like the mipmap was not included in the opengl defaults either

**Comment by HolonProduction** [comment]
Another default mismatch exists with `repeat_enable`. The opengl render will default to `repeat_enable` but vulcan uses `repeat_disable` by default.

**Comment by clayjohn** [comment]
This was fixed yesterday in https://github.com/godotengine/godot/pull/71011 the defaults should be good now.
