### ISSUE TITLE
Infinite autoload error spam preventing project from being opened

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#70798]
### Godot version

4.0 8a98110

### System information

Windows 10 x64

### Issue description

I have a method call in my script that has changed in some newer version. Whenever I want to open the project in the new version, the autoload script will spam argument error. Forever.

https://user-images.githubusercontent.com/2223172/210169561-1938b0f9-684e-4a8f-bebd-4900ff48b98a.mp4

The project never loads. It works fine after I fix the method in external editor.

### Steps to reproduce

1. Be me
2. Try to open the project :<

### Minimal reproduction project

I wasn't able to reproduce it in a minimal project. I suspect some dependency being at fault.

**Comment by adamscott** [comment]
I confirm the same error using your project, @KoBeWi. I'm investigating.

**Comment by adamscott** [comment]
I'd close the issue. It seems that `AudioStreamRandomizer` `add_stream` API changed, a new parameter has been added and [the stream parameter is now mandatory](https://github.com/godotengine/godot/pull/67922#issuecomment-1360550099). That would explain GDScript complaining for missing a parameter.

> Okay! Rebased, added the optional weight parameter & made the stream parameter mandatory. Adding/removing streams and undo/redo in the inspector plugin work, and as far as I can tell the API is working as intended with gdscript. Thanks for the inputs :)

**Comment by KoBeWi** [comment]
The issue isn't about the error though. I know what caused it and I already said that fixing the error will make my project openable.

The problem is that unless I fix the error, I will get infinite spam at startup preventing the project from being opened. I have to fix the error externally to make the project usable again.
