### ISSUE TITLE
cmd+backspace does not work in editor text inputs

### ISSUE THREAD

**Issue by doman412** [godotengine/godot#70793]
### Godot version

v4.0.beta10.official [d0398f62f]

### System information

macOS 13.1 (22C65)

### Issue description

`cmd+backspace` does not actually backspace all to the left as it does elsewhere in macOS and other applications. `option+backspace` works and backspaces a word as intended.

### Steps to reproduce

backspace all to the left:

- open `Editor Settings`
- type `hello` into the `Filter Settings` input field
- hit `cmd+backspace` - nothing happens

another strange sequence:

- open `Editor Settings`
- type `hello` into the `Filter Settings` input field
- hit `ctrl+b` to move the cursor left one place (`hell|o`)
- hit `cmd+backspace` - nothing happens
- hit `backspace` - the last two characters are removed (`hel`)

### Minimal reproduction project

should be reproducible with any Godot project on macOS

**Comment by EricEzaM** [comment]
Here are Apples official shortcuts: https://support.apple.com/en-au/HT201236#:~:text=Option%2DDelete%3A%20Delete%20the%20word%20to%20the%20left%20of%20the%20insertion%20point.

Excerpt:
```
Option-Delete: Delete the word to the left of the insertion point.
```

There is no entry for `command-delete`. Are you using a non-mac keyboard on a Mac? Not sure how those keys map.

**Comment by doman412** [comment]
Its a standard macbook keyboard, so yes I do mean 'delete' but colloquially its backspace as normally the `delete` key has a different connotation. Seems as if under the hood Godot treats `backspace` and `delete` as the same thing on macs as when I hit those keys in the shortcuts key listener I get whats in screenshot 1. 

<img width="656" alt="Screenshot 2023-01-29 at 12 33 05 PM" src="https://user-images.githubusercontent.com/3157204/215354342-656efeb8-7377-4065-a0c4-56b7f9beaa14.png">

In the second screenshot, the command `ui_text_backspace_all_to_left` works as intended within the scripts editor but any input field within the Godot editor as a whole, it does not work. If i were to focus that input in screenshot 2 that has the value `backspace` with the cursor at the end and hit `command+backspace` it does nothing when it should clear the whole input left of the cursor.

<img width="453" alt="Screenshot 2023-01-29 at 12 24 32 PM" src="https://user-images.githubusercontent.com/3157204/215354192-32547d09-f65c-44b5-8950-55eb863cb4fc.png">

**Comment by passivestar** [comment]
Can confirm everything, `command+backspace` works in the script editor but not in any of the `LineEdit`s, which is really annoying when searching for things in the FileSystem search, quick open, command palette, etc, because I'm used to `command+backspace` in every other application, but in godot I can only `alt+backspace`

using v4.2.1.stable.official [b09f793f5]
