### ISSUE TITLE
GDScript Integer division Error - Silent error with floats

### ISSUE THREAD

**Issue by TheYellowArchitect** [godotengine/godot#70807]
### Godot version

4.0 beta10 (downloaded from official website)

### System information

Arch Linux, NVIDIA GTX-1050 Ti

### Issue description

I wanted to make a simple math script (tl;dr: displays all possible single-multiplication combinations to form a number), and decided to use Godot. The problem is that on pressing play, it instantly closes without any kind of errors, so the user doesn't instantly know where to look

### Steps to reproduce

Make an empty scene with just 1 node, and attach this script on it:
```gdscript
extends Node

var targetNumber : int
var dividedNumber : float
var regeneratedNumber : float
var finalNumberArray = [1]

# Called when the node enters the scene tree for the first time.
func _ready() -> void:	
	targetNumber = 120
	
	for i in range(targetNumber/2):
		dividedNumber = targetNumber / i
		regeneratedNumber = dividedNumber * i
		
		#integer removes fractions
		if (dividedNumber == regeneratedNumber):
			finalNumberArray.append(i)
			
	print(finalNumberArray)
```

It crashes silently on the 1st line after forloop.
`dividedNumber = targetNumber / i` is essentially `float = int / int` so it should work. Even if I do explicit casting `float = (float)(int / int)` it still doesn't work and straight up crashes.

If you change `targetNumber` from `:int` to `:float` it won't throw any error but ofc it won't work logically (since I need that lazy fraction detection)
It does throw 'GDScript Integer Division' warnings, but they are just that, warnings. It doesn't make sense to close the scene entirely.

### Minimal reproduction project

See above, it's just a script

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/59556 (you're performing a division by zero on the first iteration, as `range()` starts at 0).

**Comment by TheYellowArchitect** [comment]
You are correct, silly me. I even did a test by injecting below the forloop `if i == 0: i = 1` to ensure it wasn't a division by zero, but it seems i didn't save or sth? Anyway, I apologize for taking your time, thank you for looking into this silent error
