### ISSUE TITLE
Metadata is not saved when added via tool

### ISSUE THREAD

**Issue by IceflowRE** [godotengine/godot#70806]
### Godot version

v4.0.beta10.official [d0398f62f]

### System information

Windows 11

### Issue description

When adding metadata via a tool script it is not saved.
`notify_property_list_changed` wont change this also.

### Steps to reproduce

Edited: With the example below.
Just open `metadata.tscn`. The metadata change is not recognized by the editor via an asteriks at the scene name above nor saved when closing the scene.

---

Add this script to a node.
```gdscript
@tool
extends Control

func _ready() -> void:
    self.set_meta("foo", 42)
    self.notify_property_list_changed()
```
This change is not recognized and not saved.

### Minimal reproduction project

[metadata.zip](https://github.com/godotengine/godot/files/10329365/metadata.zip)

**Comment by KoBeWi** [comment]
Can't reproduce
![image](https://user-images.githubusercontent.com/2223172/210179926-e323e35e-8d76-4ae4-bfa8-9a502dd09131.png)
You set meta in ready, so make sure you reload the scene after adding the script.

**Comment by IceflowRE** [comment]
Added an example to the issue.

**Comment by KoBeWi** [comment]
And it's working as I said
![image](https://user-images.githubusercontent.com/2223172/210183087-62e5f5e4-faa8-40bf-bfba-8571ee3deffc.png)

**Comment by IceflowRE** [comment]
> 

Which OS? Which editor?
Cause it does not for me with that example.

**Comment by KoBeWi** [comment]
Beta 10
Windows 10 (it can't be system-specific)

How do you test if it does work?

**Comment by IceflowRE** [comment]
1. Open the project.
2. Open `metadata.tscn`.
3. Close the scene.
4. Check via an text editor the `metadata.tscn` file.

**Comment by KoBeWi** [comment]
You need to save the scene...

**Comment by IceflowRE** [comment]
> You need to save the scene...

Well right then it does indeed works.
But i would still expect that the editor tells me that the scene was changed. Which it does not.

So the issue is that the editor does not mark a metadata change as a change?

**Comment by KoBeWi** [comment]
The editor doesn't know that the scene has changed. You need to notify it explicitly, by making an editor plugin and using the editor's UndoRedo system.

**Comment by IceflowRE** [comment]
> The editor doesn't know that the scene has changed. You need to notify it explicitly, by making an editor plugin and using the editor's UndoRedo system.

I would expect that changing build in things would be supported by the editor itseld.

**Comment by KoBeWi** [comment]
Whether scene is changed or not is determined solely by the undo history. Changes can't be detected automatically, because that would require scanning every property in every node, which would kill performance. Tool scripts don't interact with the editor (at least not in legitimate way). `@tool` just means that the methods can be executed in the editor, but for advanced editor uses you need EditorPlugin.

That said, this issue is clearly not a bug. If you expect a different behavior, open a [proposal/discussion](https://github.com/godotengine/godot-proposals).

**Comment by IceflowRE** [comment]
Ah right got it!
Clearly did not got the concept of `@tool`. Makes more sense now.
Thanks for the discussion!
