### ISSUE TITLE
Material grow: faces unconnected for flat shading and connected for smooth shading

### ISSUE THREAD

**Issue by SmartySmart702** [godotengine/godot#70819]
### Godot version

4.0 Beta 10

### System information

Win 10, GTX 1070, forward_plus, mobile, gl_compatibility

### Issue description

The grow property behaves differently on flat and smooth shaded meshes.
Should be either documented or fixed if this is not intended.

### Steps to reproduce

Import two cubes with rounded edges, one with flat shading and the other one with smooth shading.
Add a material and use the grow feature.

### Minimal reproduction project

[grow_test.zip](https://github.com/godotengine/godot/files/10329544/grow_test.zip)

left is smooth, right is flat
![grow_test](https://user-images.githubusercontent.com/42713365/210186036-56c2ff5c-9736-43e8-8673-d1e344e63ae2.PNG)

**Comment by Calinou** [comment]
This is an expected limitation of grow in a fragment shader, as it cannot create new verticeS.

**Comment by MGilleronFJ** [comment]
If the mesh is smooth, there is no reason for this to happen though, since vertices are supposed to be shared.
