### ISSUE TITLE
Popup window not recognized as popup on X11

### ISSUE THREAD

**Issue by locriacyber** [godotengine/godot#70814]
### Godot version

4.0 beta10

### System information

Linux

### Issue description

This is a problem of the Godot editor.

`_NET_WM_WINDOW_TYPE` of all windows is `_NET_WM_WINDOW_TYPE_NORMAL`. When using a tiling window manager, the WM tries to tile every popup as well.

It should be `_NET_WM_WINDOW_TYPE_DIALOG`.

### Steps to reproduce

- Open any Godot popup, like "Save or Discard"
- use `xprop` and click on the popup
- check `_NET_WM_WINDOW_TYPE(ATOM)` in xprop's output

### Minimal reproduction project

N/A

**Comment by rsubtil** [comment]
Duplicate of https://github.com/godotengine/godot/issues/55415?

**Comment by locriacyber** [comment]
duplicate
