### ISSUE TITLE
Window size is bigger when "display/window/size/resizable" = false

### ISSUE THREAD

**Issue by LDev-IX** [godotengine/godot#70815]
### Godot version

4.0 beta-10

### System information

Windows 10, API Vulkan, GTX 1050Ti, 1920x1080

### Issue description

I noticed that when the property "display/window/size/resizable" is false, then the window is bigger by 10 pixels.

### Steps to reproduce

Project settings:
Viewport Width/Height = 600/300
Resizable = false

Code:
```
public override void _Ready()
	{
		GD.Print(GetViewportRect().Size);
	}
```

Expected message in console:
(600, 300)

Actual message in console:
(610, 310)

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/37288.
