### ISSUE TITLE
C# scripts cannot be hot-reloaded automatically

### ISSUE THREAD

**Issue by L2750558108** [godotengine/godot#70827]
### Godot version

3.5.1mono

### System information

windows10

### Issue description

C# scripts cannot be hot-reloaded automatically.You need to manually click the Build button after the change, which GDScript does not.

### Steps to reproduce

No

### Minimal reproduction project

No

**Comment by markdibarry** [comment]
This is documented in the [C# Basics section of the docs.](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_basics.html#general-differences-between-c-and-gdscript)

**Comment by YuriSizov** [comment]
Indeed, this is a documented limitation. If you know how to implement this as a feature, feel free to open a new proposal for it https://github.com/godotengine/godot-proposals. There may even already be one.
