### ISSUE TITLE
Apk signer returned with error #1

### ISSUE THREAD

**Issue by sopdevv** [godotengine/godot#70831]
### Godot version

3.5 stable, 4.0 beta 10

### System information

Windows 10, i5-7200, 940MX

### Issue description

hi,

I am having an issue when i try to export my game for android, the error calld ( **Apk signer returned with error #1** ), I follow the documentation step by step, I traid to delete android studio and godot and reinstall everything but still getting the same problem.

I was using unity and exporting for andriod and it was working very will and i don't know why this is facing me in godot.

Even if i want to make a debug build or release one it gives me the same error.

![image](https://user-images.githubusercontent.com/96385910/210217157-1dbaaea2-5d91-42e5-9127-c0bc870e30f9.png)

### Steps to reproduce

I don't know how it's only happening to me, My friends can build for android so I hope that you can help me to fix this issue.

### Minimal reproduction project

it doesn't mattre what project i traid to build even if it was empty.

**Comment by akien-mga** [comment]
How did you solve it?

**Comment by sopdevv** [comment]
I deleted all of android studio packages and sdk's, deleting android studio is not enough

Open android studio > More Actions > SDK maneger > Uncheck everything in SDK platforms and SDK Tools > click Apply

Then follow the documentation normally : https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_android.html

**Comment by Kirx9** [comment]
I Tried everything looked at a lot of posts but it still doesn't work
