### ISSUE TITLE
Better Collada Exporter from Blender to support Blender's Cycles Render engine

### ISSUE THREAD

**Issue by briangular** [godotengine/godot#7083]
Currently using Ubuntu 16.04, with Godot 2.1 and the current Better Collada exporter for Blender - and Blender 2.78.

**Background**
The Blender **Cycles** Engine has long been the standard render engine for Blender. The Blender [Internal Engine has been discontinued (per Blender devs)](https://twitter.com/dingto/status/268655993020350464) as of 2010, and is only included for backward compatibility - for now.

### Main issue:
The Better Collada exporter for Blender does not export textures or even basic colors when using **Blender Cycles**.  _Blender Internal engine support and development has ended._

**Issue description** When exporting from Blender, using Cycles, all textures, colors, etc. are lost and must be manually copied to Godot, and manually set on each mesh. This becomes overwhelming to support for the Godot user when dozens (or more) textures and colors are needed in a game.

**Proposed solution:**  Cycles, a node and tree based system like Godot, needs be supported - at minimum, Cycles' textures should be supported/exported.

**Attached** is a very tiny and very simple blender file containing a cube with one texture that is packed in the the Blender file. Using the Better Collada exporter, and checking the "copy textures" flag in the exporter results in a Godot Scene import with no texture at all.

[Blender_Cycles_to Collada_test.blend.zip](https://github.com/godotengine/godot/files/581367/Blender_Cycles_to.Collada_test.blend.zip)

**Comment by bojidar-bg** [comment]
Please, reopen at https://github.com/godotengine/collada-exporter/issues
