### ISSUE TITLE
Godot seam to be confused with surface material overrides assignations

### ISSUE THREAD

**Issue by PKNzeta** [godotengine/godot#70835]
### Godot version

v4.0.beta.custom_build [2a04b18d3]

### System information

5.15.85-1-MANJARO x86_64 GNU/Linux OpenGL NVIDIA GeForce RTX 2060/PCIe/SSE2 4.6.0 NVIDIA 525.60.11

### Issue description

Hi,
I am using the latest development version of Godot. When I try to modify the "surface_material_override/1" attribute in the editor, it changes "surface_material_override/0" instead. I have isolated the code in a separate project and tested it in the stable version, and the bug does not appear.

### Steps to reproduce

- open the project
- open the main.tscn scene
- select the node "stone"
- change the "surface_material_override/1" by a new one.
- save or run main.tscn

### Minimal reproduction project

[godot-bugreport.zip](https://github.com/godotengine/godot/files/10331960/godot-bugreport.zip)

**Comment by clayjohn** [comment]
This should be fixed by https://github.com/godotengine/godot/pull/70466

Can you try again with latest master? 

In the future I recommend checking master and/or the latest beta before opening bug reports as the bug may have been fixed in a PR merged after you made your custom build

**Comment by PKNzeta** [comment]
Thank you for your assistance with my issue. I followed your suggestion. This has successfully resolved the bug that I was experiencing, so I am very grateful for your help. I apologize for wasting your time by reporting a bug that had already been fixed. In the future, I will make sure to check the latest development build before reporting a bug

**Comment by Calinou** [comment]
Closing per the above comment.
