### ISSUE TITLE
Godot crashes when reloading tilemaps with external tilesets

### ISSUE THREAD

**Issue by Skrapion** [godotengine/godot#70846]
### Godot version

4.0 beta 10

### System information

Windows 11

### Issue description

I'm working on a [Godot 4 exporter for Tiled](https://github.com/mapeditor/tiled/pull/3550), and discovered that under mysterious circumstances, Godot 4 crashes when reloading changed tilemap files.

As far as I can tell, it only ever happens when you have the tileset saved as a separate .tres file, and never when the tileset is embedded in the .tscn file with the tilemap. Having multiple maps, tilesets, and physics layers, also seems to contribute to this crashing consistently.

### Steps to reproduce

1. Open the reproduction project
2. Touch Levels/example-tileset.tres and Levels/example.tscn, in that order. (If you have WSL, `touch example-tileset.tres example.tscn` will work, otherwise, open them with an editor and resave without making changes. Touching them in this order seems to make a difference.)
3. Re-focus Godot. It should detect the changes, and crash immediately.

### Minimal reproduction project

[tilemapcrash.zip](https://github.com/godotengine/godot/files/10333178/tilemapcrash.zip)

**Comment by Skrapion** [comment]
The crash is here: 

https://github.com/godotengine/godot/blob/0160fea1ced6697d5b72ad2f41332e8768080be4/editor/plugins/tiles/tile_set_atlas_source_editor.cpp#L132-L135

`tile_set_atlas_source->signal_map.hashes` is null. (Uninitialized, or double-freed?)

**Comment by KoBeWi** [comment]
Can't reproduce in rc3.
@Skrapion Does this still happen for you?

**Comment by KoBeWi** [comment]
Comment if it still happens.
