### ISSUE TITLE
build android template under windows 7 32bit fails

### ISSUE THREAD

**Issue by avril-gh** [godotengine/godot#7084]
**OS : windows 7 32bit**
**Cannot build android template under windows 7 32bit**
uses [scipt by @Calinou](https://gist.github.com/Calinou/44edbd5d9c4a2ac0dbc8f165b8b7f0ce) (with modified ENVVARS)
```
C:\Windows\system32>cd c:\godot

c:\godot>set threads=1
c:\godot>set PATH=C:\mingw\mingw32\bin
c:\godot>set JAVA_HOME=C:\Program Files\java\jre1.8.0_111
c:\godot>set ANDROID_HOME=C:\Program Files\Android\android-sdk
c:\godot>set ANDROID_NDK_ROOT=C:\android-ndk-r13b
c:\godot>set NDK_TARGET=arm-linux-androideabi-4.9

c:\godot>call "C:\Python27\Scripts\scons.bat" p=android -j1 verbose=yes tools=no
 target=release_debug
scons: Reading SConscript files ...

MSVC not detected, attempting Mingw.
- gcc detected.
Godot Android!!!!! (armv7) (with neon)
scons: done reading SConscript files.
scons: Building targets ...
C:\android-ndk-r13b/toolchains/llvm/prebuilt/windows-x86/bin/clang++ -o platform
\android\os_android.os -c -fno-rtti -fno-exceptions -DNO_SAFE_CAST -DFREETYPE_EN
ABLED -DENABLE_DEPRECATED -isystem C:\android-ndk-r13b/platforms/android-14/arch
-arm/usr/include -Wno-invalid-command-line-argument -Wno-unused-command-line-arg
ument -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -fvisib
ility=hidden -fno-strict-aliasing -Wa,--noexecstack -DANDROID -DNO_STATVFS -DGLE
S2_ENABLED -D__ARM_ARCH_7__ -D__ARM_ARCH_7A__ -march=armv7-a -mfloat-abi=softfp
-mfpu=neon -D__ARM_NEON__ -target armv7-none-linux-androideabi -fno-integrated-a
s -gcc-toolchain C:\android-ndk-r13b/toolchains/arm-linux-androideabi-4.9/prebui
lt/windows-x86 -O2 -DNDEBUG -ffast-math -funsafe-math-optimizations -fomit-frame
-pointer -ftree-vectorize -DDEBUG_ENABLED -DANDROID_ENABLED -DUNIX_ENABLED -DNO_
FCNTL -DMPC_FIXED_POINT -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DXML_ENABLED -Icor
e -Icore\math -Itools -Idrivers -I. -Iplatform\android -Ithirdparty\zlib -Ithird
party\freetype -Ithirdparty\freetype\include -Ithirdparty\libpng platform\androi
d\os_android.cpp
=====
In file included from platform\android\os_android.cpp:29:
In file included from platform\android/os_android.h:32:
In file included from core\os/input.h:32:
core\object.h:522:8: warning: 'this' pointer cannot be null in well-defined C++
code; pointer may be assumed to always convert to true [-Wundefined-bool-convers
ion]
                if (!this)
                    ~^~~~
core\object.h:537:8: warning: 'this' pointer cannot be null in well-defined C++
code; pointer may be assumed to always convert to true [-Wundefined-bool-convers
ion]
                if (!this)
                    ~^~~~
2 warnings generated.
C:\mingw\mingw32\bin\as.exe: unknown option -- mfpu=neon
clang++.exe: error: assembler command failed with exit code 1 (use -v to see inv
ocation)

=====
scons: *** [platform\android\os_android.os] Error 1
scons: building terminated because of errors.
```

**Comment by vnen** [comment]
@RandomShaper do you have any clue about this?

**Comment by RandomShaper** [comment]
It's the classic problem of Clang invoking the wrong assembler.

I'd like to see an env dump (by adding
print env.Dump()
at the end of platform\android\detect.py).

**Comment by vnen** [comment]
I can't reproduce this.

**Comment by volzhs** [comment]
I'm not sure, but when I got this similar error message,
`scons: *** [platform\android\os_android.os] Error 1`
I solved it by running terminal as admin permission, don't know why.

**Comment by avril-gh** [comment]
> I'd like to see an env dump (by adding print env.Dump() at the end of platform\android\detect.py).

@RandomShaper 
env.Dump() at the end of godot\SConstruct [envdump.txt](https://github.com/godotengine/godot/files/583816/envdump.txt)
env.Dump() at the end of platform\android\detect.py [detect_py.txt](https://github.com/godotengine/godot/files/583865/detect_py.txt)

> (...) running terminal as admin permission (...)

@volzhs 
I run it as admin, also UAC is completly disabled on this computer through registry.
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\EnableLUA = 0`

**Comment by avril-gh** [comment]
I know its hard to tell much without enought information,
therefore i can give full direct access to this computer through [TeamViewer](https://www.teamviewer.com) so you can see, tryout, change or fix anything you want by yourself.
If some of you would like to check it by yourself, please tell it here and i will give you access ID and pass on IRC #godotengine

_TeamViewer is a remote desktop software for remote support - works on all platforms, not require installation._

**Comment by RandomShaper** [comment]
@volzhs, sometimes NTFS permissions get messed up. You could try resetting
the ACL for your repo folder in Explorer by (maybe not exact, right now not
in front of my PC):
1) disabling inheritance on it and choosing to keep a copy of the current
permissions, and accepting;
2) then re-enabling inheritance on that folder and allowing propagation to
children elements.

@Avril, thank you for your data. I can't find anything wrong there, though.
As soon as I get my PC repaired I'm willing to have a look with TeamViewer.
I'm curious about that issue. I'll let you know when I'm ready.

**Comment by RandomShaper** [comment]
@Avril, I've found the problem. I've downloaded the 32-bit NDK and noticed
the host subpath (as I call it) is "windows" and not "windows-x86".

Please do the replace in android/detect.py and retry your build.

If it succees I'll submit the relevant PR.

**Comment by avril-gh** [comment]
> "windows" and not "windows-x86" (...) replace in android/detect.py and retry your build.
If it succees I'll submit the relevant PR.

@RandomShaper 
Worked very well :star2: compiler finished fine, (so proved that replace to "windows" is ok),
but then linker stoped with `unrecognized option --threads`
I removed `-Wl,--threads` and everything went forward, finished build 100%

So good to know - you may like to also take closer look at LINKFLAGS

**Thank you everyone for your time,**
**With your help, we have found that theres potentially 2 problems when compiling under 32bit windows.**
In file `android/detect.py`
- `windows-x86` should be `windows` (`windows-x86` folder does not exists in 32bit NDK)
- `-Wl,--threads` may be removed (this flag seems to stop linker under 32bit windows)

**Since issue seems to be solved i will close thread.**

**Comment by akien-mga** [comment]
A workaround is not a fix.

**Comment by akien-mga** [comment]
Possible regression from #6723.

**Comment by avril-gh** [comment]
tested #7110  under windows 7 32bit - works ok
