### ISSUE TITLE
ReShade popup on every component of the editor

### ISSUE THREAD

**Issue by dotnetdummy** [godotengine/godot#70849]
### Godot version

4.0-beta10

### System information

Windows 11, NVidia RTX 3080

### Issue description

![godot4-editor](https://user-images.githubusercontent.com/2156200/210270548-bbba505a-fc12-476e-acc6-8c9352b3523c.png)

As soon as I start the editor and choose a project with the Forward+ or Mobile renderer I get various ReShade information/warnings (see appended screenshot). I do not have ReShade installed for all users on the system, just injected in in an emulator (CEMU). 

It works fine when creating a project using the "Compability" renderer. 

Also when opening the editor as Admin, the error in the appended screenshot is just replaced with the yellow text "An update is available! .....". Pressing the home-key does nothing, no ReShade configuration is opened.

### Steps to reproduce

I just need to open the provided project and it pops up on every menu, sub-menu, dialog, etc in the editor.

### Minimal reproduction project

[gd4test.zip](https://github.com/godotengine/godot/files/10333218/gd4test.zip)

**Comment by dotnetdummy** [comment]
Just realized it pops up in every game if using Vulkan. So it is some systemwide config that hooks into the driver somehow, no issue with the Godot 4 engine...

**Comment by Calinou** [comment]
Is there a way to hint ReShade that it shouldn't affect a specific window? This would be good to do on the Godot editor, as there's no reason to ever use ReShade on the Godot editor (though you may want to do so on a running project).

**Comment by Calinou** [comment]
Reopening, as I can still reproducible this as of 4.3.dev3 after installing ReShade on the Godot editor executable.
