### ISSUE TITLE
Syntax highlighting highlights `$` syntax on node names starting with a number, despite not being valid identifiers

### ISSUE THREAD

**Issue by pattlebass** [godotengine/godot#70843]
### Godot version

Godot Engine v4.0.beta10.official.d0398f62f

### System information

Windows 10

### Issue description

Even though the syntax highlighting is correct, the following errors are raised, unless quotes are used.

`Expected node path as string or identifier after "$".`
`Invalid numeric notation.`
`Expected statement, found "Literal" instead.`

### Steps to reproduce

1. Add a node named "2D" to the scene
2. In a script, use `$2D`
3. The errors above are shown, even though the highlighting works fine

### Minimal reproduction project

[node-starts-with-number.zip](https://github.com/godotengine/godot/files/10332763/node-starts-with-number.zip)

**Comment by Sslaxx** [comment]
Didn't think nodes starting with numbers were permitted?

**Comment by Calinou** [comment]
This is expected, as valid identifiers must not start with a number. The syntax highlighting should be fixed as to not highlight these as valid node paths though.

**Comment by pattlebass** [comment]
It's the same on 3.5.1.

```gdscript
func _ready() -> void:
  print($2D.name) # error
  print($"2D".name) # 2D
  print(get_node("2D").name) # 2D
  print(get_node(@"2D").name) # 2D
  
  var a = Node2D.new()
  a.name = "123456"
  add_child(a)
  print(a.name) # 123456
```

Using "2D" and "123456" as node paths seems to work correctly (both on 3.x and 4), so if we want to disallow them starting with a number we should probably throw an error

> Can you reproduce this on 3.5.1?
> 
> This is expected, as valid identifiers must not start with a number. The syntax highlighting should be fixed as to not highlight these as valid node paths though.

**Comment by MewPurPur** [comment]
Hmm... okay.
