### ISSUE TITLE
GDScript 2.0: Unable to do type checking on variables typed with `const X = preload("script.gd")` 

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#70844]
### Godot version

Godot 4 beta10

### System information

Windows 10 64 bits NVIDIA GeForce GTX 1060

### Issue description

In Godot 3 it was possible to type-hint a variable using constant preloaded script. But in Godot 4 it seems GDScript treats those variables as if they were variants with no known type, even though all the information is available.
Lines will not be highlighted as "safe", and attempting to use `:` to auto-hint variables assigned from properties or methods of the object will cause errors.

### Steps to reproduce

`body.gd`
```gdscript
extends RigidBody3D
```

`main.gd`
```gdscript
const MyBody = preload("./body.gd")

func _ready():
	var body := MyBody.new()
	print(body.name)

	# This causes an error
	#var pos := body.position

	body.freeze = true # This is supposed to be safe
	body.queue_free() # This is supposed to be safe
```

### Minimal reproduction project

[GDScriptSafeLineConstType.zip](https://github.com/godotengine/godot/files/10333076/GDScriptSafeLineConstType.zip)

**Comment by adamscott** [comment]
CC @vonagam

**Comment by adamscott** [comment]
I confirm this issue on master. (b29bb11)

This is weird because the editor suggests the right types.

**Comment by adamscott** [comment]
This is a regression. Could not reproduce in beta 8, but could in beta 9.

I'm currently trying to find the culprit commit.

**Comment by adamscott** [comment]
@rune-scape I suspect #69471 have something with this.
