### ISSUE TITLE
Object allocation is slower since 4.0.beta9

### ISSUE THREAD

**Issue by maldrasen** [godotengine/godot#70853]
### Godot version

v4.0 beta9

### System information

Windows 11, 64bit

### Issue description

Since migrating from Beta 8 to Beta 10, I've noticed a serious performance hit. I've tracked the problem down to a place where I'm creating a couple thousand objects. The object allocation used to take a couple microseconds, but ever since Beta 9 it takes hundreds of microseconds to construct a new object.

### Steps to reproduce

Create a plain Godot class that extends Object. Create a few thousand of them. It takes a while. 

### Minimal reproduction project

[AllocationExample.zip](https://github.com/godotengine/godot/files/10333611/AllocationExample.zip)

**Comment by Calinou** [comment]
If you can [compile the engine from source](https://docs.godotengine.org/en/stable/development/compiling/index.html), you could look into [bisecting the regression](https://docs.godotengine.org/en/stable/community/contributing/bisecting_regressions.html) to greatly speed up troubleshooting.

**Comment by maldrasen** [comment]
OK, I'll see what I can find.

**Comment by KoBeWi** [comment]
I didn't test much, but I remember having this problem and that it might be fixed on newest master.

**Comment by maldrasen** [comment]
That would be awesome if so. I haven't been able to build from source yet, so I've yet to test it on master.

**Comment by KoBeWi** [comment]
Beta 11 might be released soon, so you will be able to test easily.

**Comment by clayjohn** [comment]
Can you still reproduce this issue using Beta 14?
