### ISSUE TITLE
Build failure against system OpenSSL 1.1.x.

### ISSUE THREAD

**Issue by Ovnuniarchos** [godotengine/godot#7085]
**Operating system or device - Godot version:**
Debian SID - Commit 7d1230a266f4eab3262ebfcbf4a89148dfcb3c48

**Issue description** (what happened, and what was expected):
Build fails with the following dump:
[build.txt](https://github.com/godotengine/godot/files/581748/build.txt)

**Comment by akien-mga** [comment]
I guess our `stream_peer_openssl.cpp` is not compatible with OpenSSL 1.1.0 yet.

**Comment by Elinvention** [comment]
I solved this issue by installing `libssl1.0-dev` that removed `libssl-dev`, but I don't know why...

**Comment by akien-mga** [comment]
That means you replaced OpenSSL 1.1.0 by OpenSSL 1.0.x, which is the one currently supported by Godot.

**Comment by akien-mga** [comment]
Superseded by #8624.
