### ISSUE TITLE
Can select children on instanced scenes even when child selection is turned off

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#7086]
Tested on Godot 2.1, Windows 10 64 bits,
also tested on cdc4664226cdc397d054b7390d0f75028d40412c

This has been annoying me a lot today when designing a level with very small elements. I unwillingly messed up scene instances, so I investigated further.

![selection_box_children_bug](https://cloud.githubusercontent.com/assets/1311555/20158782/db3eacbe-a6dc-11e6-8901-ada004f727e3.png)

Repro:
1) Create a thing.tscn with a Node2D as parent and a child sprite that is a lot smaller than 32x32, say 8x8
2) Create another scene and instance one thing.tscn
3) Try to select it with a rectangle selection: start with a corner very far away, and end with a corner that is very close to the thing
4) Notice the thing seems to be visually selected, but... the node won't be selected in the tree dock. That's actually because the child got selected.
5) Notice Ctrl+D won't work and display an error "Can't operate on nodes from a foreign scene!"
6) Disable selection of child nodes using the scene view toolbar
7) Try 3) again, notice the same problems occur.

Here is a test project:
[SelectionAreaChildren.zip](https://github.com/godotengine/godot/files/582194/SelectionAreaChildren.zip)

A few things are wrong here:
- Child nodes can be selected even when the option is turned off
- It can happen on a scene where child nodes are not in editable mode
- The selection area of the instances is way too big

**Comment by eon-s** [comment]
That happens on normal nodes too, the rectangle selection seems to ignore the children lock
