### ISSUE TITLE
Scrollbar grabber click is not detected at bottom edge

### ISSUE THREAD

**Issue by Maran23** [godotengine/godot#70866]
### Godot version

4.x (beta 5, 6, 7, 8, 9, 10) didn't tested versions before beta 5
Also reproducable in current master: c5bfe13
  
### System information

Windows 10

### Issue description

When clicking around the bottom edge of the scrollbar grabber, it is not detected as such and instead jumps to a lower position, as if you click on the free area of the scrollbar.

The red marked area is not detected as grabber click. Everything is fine on the top edge.
![image](https://user-images.githubusercontent.com/66004280/210325316-6718b793-b3ec-4c3a-b2b3-0df0f431a222.png)

### Steps to reproduce

Just use a `ScrollContainer` with e.g. a `VBox` and many `Button`s.

See the video:

https://user-images.githubusercontent.com/66004280/210325006-718e0f57-49b3-4aa1-ad35-653b9c66d9fa.mp4

### Minimal reproduction project

N/A

**Comment by YuriSizov** [comment]
> Godot version
> 
> 4.x

In future, please be more specific. This covers everything under the sun and doesn't help to reproduce or bisect the issue.
