### ISSUE TITLE
Expose path 2d points array in editor

### ISSUE THREAD

**Issue by HeartoLazor** [godotengine/godot#7087]
I would like to edit the points from a path 2d manually without using code, for that could be useful to expose the non-baked Vector2Array. This is similar to polygon or collision polygon points behavior, the user could access to array directly from editor and edit values manually.

As a reference could be like this when the user try to edit the generated Curve2D Resource in path 2d:
![3em3w38 1](https://cloud.githubusercontent.com/assets/12376042/20160583/da2a02da-a6c6-11e6-8a71-1f38f83c2a89.png)

**Comment by eon-s** [comment]
Related (or duplicated) #6914

**Comment by bojidar-bg** [comment]
Right, dupe of #6914... @vnen - better luck next time :wink:
