### ISSUE TITLE
Expression objects can't use the "await" keyboard

### ISSUE THREAD

**Issue by jon-heard** [godotengine/godot#70888]
### Godot version

v4.0.beta10.official [d0398f62f]

### System information

Windows 10

### Issue description

Expression objects are Godot types that allow storing code statements, including function and method calls.  In Godot 3.5 this included calling functions and methods that used the "yield" keyword.  In Godot 4.0, "yield" has been replaced with "await", which is apparently incompatible with Expression objects.  When an Expression object contains a call that uses the "await" keyword, the execution of that Expression fails with the error message

```
Invalid named index 'await' for base type Object
```

This introduces a limitation to Expressions that was not present prior to Godot 4.0.  It also doesn't seem to fit the intended usage of Expressions, so I'm filing it as this bug.

### Steps to reproduce

1) Create an Expression object containing code to call a function or method using the "await" keyword.
2) Execute the Expression
3) Call the Expression's has_execute_failed() method and note that returns true
4) Call the Expression's get_error_text() method and see that it returns an error message pointing to the "await" keyword.

### Minimal reproduction project

N/A

**Comment by jon-heard** [comment]
I closed this as I realized that the issue only occurred when the Expression execution is the right-side of an assignment.

**Comment by Zireael07** [comment]
Nit: key*word* not keyboard

**Comment by jon-heard** [comment]
@Zireael07: fixed, thanks
