### ISSUE TITLE
Depth pre-pass is broken

### ISSUE THREAD

**Issue by TokisanGames** [godotengine/godot#70881]
### Godot version

v4.0.beta.custom_build [96f12040c]

### System information

Windows 11/64, RTX 3070, Vulkan

### Issue description

From beta10 to the current master, depth prepass is broken. 

Alpha
![image](https://user-images.githubusercontent.com/632766/210395481-1eb4a6be-da4e-423f-a169-65a4b08b9411.png)

Depth Prepass
![image](https://user-images.githubusercontent.com/632766/210395511-7bb2058c-0784-46de-a582-c4d911fc8d88.png)

Alpha
![image](https://user-images.githubusercontent.com/632766/210395568-d168d393-6681-488f-b7d7-b1d58e7728ed.png)

Depth Prepass `depth_prepass_alpha`
![image](https://user-images.githubusercontent.com/632766/210395630-c9a11673-52c1-45c2-890d-29d4330f1cda.png)

Depth Prepass Beta 10
![image](https://user-images.githubusercontent.com/632766/210395836-e1c2be64-378c-4bb0-ac81-a3e9b7e7685a.png)

Note that the shadows render fine, as does vertex animation.

I also get a lot of vulkan errors that I don't get in b10. Many repeats of these on load, but not continuous:

```
ERROR: Condition "!named_textures.has(key)" is true. Returning: RID()
   at: get_texture_slice (servers/rendering/renderer_rd/storage_rd/render_scene_buffers_rd.cpp:357)
ERROR: Texture (binding: 0, index 0) is not a valid texture.
   at: (drivers/vulkan/rendering_device_vulkan.cpp:5465)
ERROR: Condition "rid.is_null()" is true. Returning: rid
   at: _allocate_from_uniforms (./servers/rendering/renderer_rd/uniform_set_cache_rd.h:129)
ERROR: Condition "!uniform_set" is true.
   at: compute_list_bind_uniform_set (drivers/vulkan/rendering_device_vulkan.cpp:7807)
ERROR: Uniforms were never supplied for set (0) at the time of drawing, which are required by the pipeline
   at: (drivers/vulkan/rendering_device_vulkan.cpp:8006)
ERROR: Condition "!rt" is true. Returning: RID()
   at: render_target_get_override_depth_slice (servers/rendering/renderer_rd/storage_rd/texture_storage.cpp:2688)

```

I'm bisecting now....

### Steps to reproduce

See MRP. Change alpha on the tree.

### Minimal reproduction project

You can use my demo from #63675
https://github.com/godotengine/godot/files/10256553/test_zorder.zip

**Comment by TokisanGames** [comment]
Bisecting reveals the winner is....
[d44a91c2f78809365020a67647a2c94ccab418ad] use depth prepass to increase performance
https://github.com/godotengine/godot/pull/70214
@Ansraer

**Comment by clayjohn** [comment]
Looks like we should disable that option when depth prepass is used as the user doesn't have control over the depth threshold.
