### ISSUE TITLE
`InputEventAction` is never emitted.

### ISSUE THREAD

**Issue by ItsAleph** [godotengine/godot#70889]
### Godot version

4.0.beta10

### System information

Linux 5.15.85-1 x86_64 (Manjaro XFCE)

### Issue description

The event object passed to `Node._input()` is *never* `InputEventAction`.

### Steps to reproduce

- Create a project.
- Create Node2D scene and add the following script to it:
```gdscript
extends Node2D


func _input(event):
	print(event is InputEventAction)
```
- Go to the **Project > Project Settings > Input Map** and add an action which is triggered by a key, **`F`** for example.
- Run the scene and try to push the key you just set for the action.
- Look at the **Output** tab in the editor and see that all the `event`s emitted are `InputEventKey`s and not `InputEventAction`s.

### Minimal reproduction project

[IEANeverEmitBug.tar.gz](https://github.com/godotengine/godot/files/10339149/IEANeverEmitBug.tar.gz)

**Comment by timothyqiu** [comment]
This is intended.

Events won't be converted to `InputEventAction` upon calling input functions. Instead, you can check if that event matches an action by `event.is_action_pressed(action_name)`.

**Comment by ItsAleph** [comment]
Oh, sad. My possible use case would be like this:
```gdscript
# If `Node._input()` emitted `InputEventAction`s, i could've written this..
func _input(event: InputEvent):
    if event is InputEventAction and event.pressed and event.action in [&"up", &"down", &"left", &"right"]:
        $AnimatedSprite.play(event.action) # `AnimatedSprite` has animation with the same names as actions

# ..instead of this (this is what i currently use)..
func _input(event: InputEvent):
    if event.is_action_pressed(&"down"):
        $AnimatedSprite.play(&"down")
    
    if event.is_action_pressed(&"up"):
        $AnimatedSprite.play(&"up")
    
    if event.is_action_pressed(&"left"):
        $AnimatedSprite.play(&"left")
    
    if event.is_action_pressed(&"right"):
        $AnimatedSprite.play(&"right")

# ..reducing code duplication and increasing maintainability a bit.
```
But i guess this case falls under the "can-be-worked-around-with-a-few-lines-of-code" category. I wonder if something like `InputEvent.get_action(exact_match: bool = false)` can be implemented instead.

**Comment by KoBeWi** [comment]
```GDScript
func _input(event: InputEvent):
    for action in [&"up", &"down", &"left", &"right"]
        if event.is_action_pressed(action):
            $AnimatedSprite.play(action)
```

**Comment by RedwanFox** [comment]
>This is intended.
This is bad because it locks user to using synchronous input handling. You mostly want to deal with actions that hide physical input. Especially in cases when player can change controls in-game.  Sending InputEventAction events at least should be flag in engine (IMHO enabled by default). 

Right now it can be worked around with singleton (set in tree as early as possible) with code like this

```
extends Node

func _input(event:InputEvent):
	if (event is InputEventAction or event is InputEventMouseMotion):
		return

	var actions = InputMap.get_actions()
  
	for action in actions:
		if event.is_action(action):
			get_viewport().set_input_as_handled()
			var ev = InputEventAction.new()
			ev.action = action
			ev.pressed = event.is_pressed()
			Input.parse_input_event(ev)

```

**Comment by timothyqiu** [comment]
@RedwanFox As pointed out above, you can use `event.is_action_pressed("up")`  instead of iterating through the input map.

**Comment by ItsAleph** [comment]
> ```gdscript
> func _input(event: InputEvent):
>     for action in [&"up", &"down", &"left", &"right"]
>         if event.is_action_pressed(action):
>             $AnimatedSprite.play(action)
> ```

@KoBeWi thanks much! I believe this solution pretty much eliminates the issue, though i think documentation should be a bit more clear on the matter of `InputEventAction`, because usually subclasses of `InputEvent` *are* emitted in `_input()`.  I've opened a PR: #71060

**Comment by SephReed** [comment]
These are my actions:

```
P1.Note1, P1.Note2, P1.Note3, P1.Note4, P1.Note5,
P2.Note1, P2.Note2, P2.Note3, P2.Note4, P2.Note5,
P3.Note1, P3.Note2, P3.Note3, P3.Note4, P5.Note5,
P4.Note1, P4.Note2, P4.Note3, P4.Note4, P5.Note5,
```

I'd rather not iterate over every one of them for every input.  Is there really not any way to listen for action events?  I find this really, really confusing.  What's the point of an event if you can't listen for it?

**Comment by KoBeWi** [comment]
Check `is_action_pressed()` method of *InputEvent*.
