### ISSUE TITLE
Weird movement behavior with paths

### ISSUE THREAD

**Issue by HeartoLazor** [godotengine/godot#7088]
**Operating system or device - Godot version:**
Windows 10
Godot 2.1
One of latest Godot Builds from GitHub https://github.com/godotengine/godot/commit/611a94e3a673a61b51746366366c698c66ef0195

**Issue description** (what happened, and what was expected):
Weird movement in a path with Cubic Interp off and baking at default value
I was expecting LINEAR movement
This is fixed with big baking values (example 512)

Here is a video of the issue:
https://gfycat.com/TinyTotalBarbet
Top Sprite is moving with Linear movement on x axis without using paths (`pos.x += speed * delta`)
Bot Sprite is a path using a line in the Curve2D moving the offset with the same formula from top, bot sprites should move at the same speed 

**Steps to reproduce:**
Create a path and make a long line in the Curve 2d with two points (more than 512 pixel long)
Set the baking at default value (5) and disable Cubic Interp
Move the PathFollow2D with this formula:
```
func _fixed_process(delta):
	if(_follower != null && speed != 0.0):
		_follower.set_offset(_follower.get_offset() + speed * delta)
```

**Link to minimal example project** (optional but very welcome):
Here is a demo showcasing the issue:
https://dl.dropboxusercontent.com/s/7pkt2rv9cgt3g73/path2d_speed_test.zip
With baking at default value (5) or < 512 produces the bug, baking at 512 fixes the issue
If the two sprites moves at same speed without taking account the baking value, the issue is fixed
Top Sprite is moving without path, Bot is moving using path.

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by HeartoLazor** [comment]
Same behavior in 3.0.2.stable and 2.1.5 rc1.
Here is the updated 3.0 project.
[path2d_speed_test_3.0.zip](https://github.com/godotengine/godot/files/1889933/path2d_speed_test_3.0.zip)

**Comment by akien-mga** [comment]
Still reproducible in the current master branch (631cf67) with above project.

**Comment by Wolfe2x7** [comment]
I can confirm this issue still exists with PathFollow nodes in 3D on Godot 3.2.3 stable. I have two PathFollow nodes as guides to lead CPU cars, and one of them is intended to follow a fixed offset ahead of the car, but it drifts closer and further ahead throughout the path.
