### ISSUE TITLE
Image Generated from Viewport (in the form of a ImageTexture) won't render in SpatialMaterial when set as the albedo_texture

### ISSUE THREAD

**Issue by LunaticWyrm467** [godotengine/godot#70894]
### Godot version

3.5.stable mono

### System information

Windows 11, Nvidia RTX 3050

### Issue description

When saving an ImageTexture that is generated from the image data from a viewport capture, that image will not render in a spatial material when set as that material's albedo_texture.

### Steps to reproduce

1. Capture the viewport (has to be set to 2D)
2. Grab the image data and create an ImageTexture
3. Set the ImageTexture as the albedo_texture in the spatial material

The sample project does exactly that - and saves the results of each step in a folder in the project directory.

### Minimal reproduction project

[Sample Project.zip](https://github.com/godotengine/godot/files/10339430/Sample.Project.zip)

**Comment by clayjohn** [comment]
In your MRP you are never calling ``_on_tree_created()`` so the Viewport is never captured. It works if you move ``self.capture()`` into ``_ready()``.

**Comment by LunaticWyrm467** [comment]
I am, it's set externally as a signal in the editor. Does that not show up in the MRP?

**Comment by clayjohn** [comment]
If you add a print statement to ``_on_tree_created()`` you will see that it is never called

**Comment by LunaticWyrm467** [comment]
Ah alright, sorry about that! I managed to get it to work on my end.
Thanks a bunch.

**Comment by LunaticWyrm467** [comment]
Leaving this here for anyone who needs it:
I think it might have been an error with the cache or something, because it wasn't working beforehand (I initially had the logic in the `_on_tree_created()` method run in the `_ready()` method, which caused me to try that.
Closing and reopening the project fixed it.
