### ISSUE TITLE
Path2D should generate AT LEAST a baked point for each original array point

### ISSUE THREAD

**Issue by HeartoLazor** [godotengine/godot#7089]
**Operating system or device - Godot version:**
Windows 10
Godot 2.1
One of latest Godot Builds from GitHub https://github.com/godotengine/godot/commit/611a94e3a673a61b51746366366c698c66ef0195

**Issue description** (what happened, and what was expected):
Path2D should generate AT LEAST a baked point for each original array point
Examples:
Using baking value at 50.
In orange there is the generated baked curve, in blue is the original array of points created in the editor:
**In Godot:**
![t2dcbby 1](https://cloud.githubusercontent.com/assets/12376042/20165029/76f01d72-a6e8-11e6-8b3c-4276566ebd06.png)
Should generate instead something like this:
**Drawing of how the baked curves should be in Photoshop**
![eokjo0d 1](https://cloud.githubusercontent.com/assets/12376042/20165173/cfb6551a-a6e9-11e6-9f60-62f0dd034203.png)

Now using a baking value longer than the whole path (example this path is +- 100 length so lets use 512)
**In Godot:**
![iofyjfy 1](https://cloud.githubusercontent.com/assets/12376042/20165234/33ea3dc6-a6ea-11e6-998e-c3d8693f45aa.png)
Nothing is baked with values longer than path length
Instead should generate in this case:
**Drawing of how the baked curves should be in Photoshop**
![er3uote 1](https://cloud.githubusercontent.com/assets/12376042/20165277/99d108b8-a6ea-11e6-9008-35778fe850e3.png)

Both issues are fixed with an algorithm baking always a point for each original point.
Some things to take in consideration or discuss with this change:

- Should the baking length for next baked point be reset at an original point?, Maybe make a Flag for this behavior, something like reset_baked_value_at_original_point?
Graphical example of reset vs don't reset in Photoshop:
![mh4qfdn 1](https://cloud.githubusercontent.com/assets/12376042/20165551/0f125f8a-a6ed-11e6-9d6f-3bb7fdd62516.png)

- Add a flag to bake only the original points?. Aka disable baking and ignore curves 

**Steps to reproduce:**
Create a Path2D
Add a curve and set the baking to a high value

**Link to minimal example project** (optional but very welcome):
A project drawing the baked curve in editor
https://dl.dropboxusercontent.com/s/poknngxj7z4yo37/path2d_tesselation.zip

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by HeartoLazor** [comment]
Same behavior in 3.0.2.stable.
Here is the updated project.
[https://dl.dropboxusercontent.com/s/760n1r69kcml02f/path2d_tesselation_3.0.zip](https://dl.dropboxusercontent.com/s/760n1r69kcml02f/path2d_tesselation_3.0.zip)

**Comment by Noshyaar** [comment]
Would you mind uploading the project to Github by drag and drop to the reply box so that it can be used as reference later? Thanks!

**Comment by HeartoLazor** [comment]
Ok, Here is:
[path2d_tesselation_3.0.zip](https://github.com/godotengine/godot/files/1889644/path2d_tesselation_3.0.zip)

**Comment by akien-mga** [comment]
Still valid in the current master branch (631cf676).

**Comment by akien-mga** [comment]
Still valid in 3.3.

**Comment by smix8** [comment]
No longer valid for Godot 4.0 as one of the more recent Curve Resource changes must have fixed it "by accident".
https://github.com/godotengine/godot/commits/master/scene/resources/curve.cpp
