### ISSUE TITLE
Display only light - mode

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#709]
for wishlist

There is new mode for viewport to Display Shadeless (which is awesome, thanks!)
Would be cool to have also possibility to display raw light, where all objects are displayed with the same simple white or mid-grey material (maybe option to setup your own test material?). Useful feature for light artists.

**Comment by akien-mga** [comment]
Is this still a wanted feature in the current stable versions?

**Comment by n-pigeon** [comment]
@akien-mga 
Sorry for delay.

Yes, it's important feature for Light Artists and Enviro Artists. It's besically opposite of Unshaded mode :)

**Comment by nunodonato** [comment]
is this the same mentioned in #11392 ?

**Comment by nunodonato** [comment]
here's a simple test of a "clay render mode", in the material tester demo.
the only issue is that the gizmos also get affected :)

![clay](https://user-images.githubusercontent.com/1642015/42718083-ab4aa85c-86fd-11e8-84a0-4f9c2d734078.png)

**Comment by aaronfranke** [comment]
@nunodonato Are you working on this issue?

**Comment by Anutrix** [comment]
Any updates?

**Comment by Calinou** [comment]
@Anutrix This mode is available in the `vulkan` branch, so I guess this is now implemented :slightly_smiling_face:
