### ISSUE TITLE
Incomplete input functions

### ISSUE THREAD

**Issue by L2750558108** [godotengine/godot#70908]
### Godot version

3.5.1mono

### System information

windows10

### Issue description

Missing is_key_button_just_pressed in the Input class,
is_key_button_just_released,
is_joy_button_just_pressed,
is_joy_button_just_released,
is_mouse_button_just_pressed,
is_mouse_button_ just_released,
is_physical_key_just_pressed,
is_physical_key_just_released
 Method. This makes it inconvenient when trying to check keyboard input directly without mapping.

### Steps to reproduce

no

### Minimal reproduction project

no

**Comment by AThousandShips** [comment]
I think this is because of how input is handled, it looks at a glance like it only tracks when actions were pressed, and so only for them can it track the time and if it was just pressed or not

**Comment by L2750558108** [comment]
The echo property in the InputEvent class can be used to achieve the same effect as is_key_just_pressed or is_key_just_released. This shows that more input functions are possible. However, there is no such function in the Input class.

**Comment by AThousandShips** [comment]
No I understand that, it's possible to handle this, but it's not just a simple fact of having a function do that, it would require adding tracking for when keys were pressed, which would be much larger, though some ways to do it are possible, I am assuming the reason this isn't done because it's not worth it.

The added storage and processing to handle a random key state other than if it is at all pressed or not, when you can just create an event for the specific keys you want to track, or, as you pointed out, you can just listen for the events and handle this behavior. Being able to detect if a random key was just pressed or released isn't a normal use case for games.

**Comment by L2750558108** [comment]
But almost all other game engines do this (such as Unity, GameMaker), so I think it's necessary

**Comment by AThousandShips** [comment]
There is a proposal for this so better move discussion [there](https://github.com/godotengine/godot-proposals/issues/2016)

**Comment by Maran23** [comment]
The reason why there are only "is_action_xxx" methods is that this allows you (and then the user) to easily reassign the actions to other keys.
For example, if you assign a "forward" action to the "W" key, you can easily program that "forward" is remapped to the "ARROW_UP" key.

**Comment by L2750558108** [comment]
I don't think this is handy and flexible solution in most cases.I want the user to set the value and then use the corresponding key based on the value. Instead of setting up a mapping for each key on the keyboard.

**Comment by AThousandShips** [comment]
This isn't a very requested feature, the proposal hasn't gotten much attention, and it's not the recommended way to handle input. What is the reason that you can't use actions for input?

**Comment by L2750558108** [comment]
I'm working on a full-keyboard music game where the player needs to press the keys displayed on the decision block when the note coincides with the judge blocks. For ease of serialization, keys are stored as integer values. In order to check if the player pressed the corresponding key, I need to use is_key_just_pressed function instead of a map

**Comment by AThousandShips** [comment]
But why can't you use echo then? This is an extreme edge case, most games don't need this functionality, and you can implement it just by using echo, or even by tracking which key is supposed to be pressed and the first time its pressed remove that key.

**Comment by L2750558108** [comment]
Yes. But echo needs to write a separate _Input function to receive the InputEvent in order to use it. I want to use the Input class to put the output receiving function in the _Process, so that it can be better combined with other code.I thought it wouldn't be too hard.

**Comment by L2750558108** [comment]
I can to use echo instead. Just wanted to see if there was a better solution

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/2016.

**Comment by L2750558108** [comment]
> Closing in favor of [godotengine/godot-proposals#2016](https://github.com/godotengine/godot-proposals/issues/2016).
I also mentioned other functions (such as is_mouse_just_pressed) besides is_key_just_pressed, which are not exactly the same as this issue, and I don't think my issue should be closed


> I'm sorry but it isn't easy to do, or more it isn't for free, so as it would, and should, almost never be used, it's not a good idea.
> 
> Is it impossible for you to use echo? Can you work out some method to accomplish this? You could for example track input yourself, having two dictionaries for keys that were pressed and keys that were released, and then clear that every time you process.
But I've found that almost all major engines include this feature, such as GameMaker, Cocos, Unity and Unreal. This proves that this feature really needs to be used frequently, so I think it should be added.
