### ISSUE TITLE
Project Manager - it does not trim entered path

### ISSUE THREAD

**Issue by fpv999** [godotengine/godot#7090]
Win8.1 / Godot v2.1 stable

in the Project Manager. If you put import path with 'space' character at the end, it does not import the path. It could be trimmed, right?

reproduce:

Try to import project from path like: "d:\DevGodot\Herbi-master "  (notice the space at the end)

effect:
nothing happens.

**Comment by volzhs** [comment]
![image](https://cloud.githubusercontent.com/assets/8281454/20179810/2b3b2e72-a79b-11e6-96d4-161fda19e55c.png)

I'm using 2.2 alpha with current master head.
**Create** button is disabled and I can see error message if add a space at the end of project path.

**Comment by fpv999** [comment]
ok then, but why just not trim it internally?

**Comment by volzhs** [comment]
I can make a directory with space like "folder_name    "
I think it's more like user fault, it's not good just trimming it.

**Comment by fpv999** [comment]
you can do it only on Linux. On Windows names are trimmed by default.
