### ISSUE TITLE
Editor and project manager always start to run on the first monitor

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#70917]
### Godot version

26bed8aa85fc2f98e38552a82929e1deb5b29d8a

### System information

Windows 11

### Issue description

Regardless of settings, the project manager (and the editor itself) has always started to run on the first monitor (I have two), as well as the debugged instance window. This does not happen on 4.0 beta 10.

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
From #70624 looks like, enforces first screen

**Comment by bruvzg** [comment]
> Regardless of settings, the project manager

Which settings? `Editor Settings` → `Run` → `Window Placement` seems to work fine.

> This does not happen on 4.0 beta 10.

What was the behavior in the beta 10? And what's your display placement, https://github.com/godotengine/godot/pull/70624 should force it to the first screen if it's trying to open a window with invalid position (outside any screen).

**Comment by Chaosus** [comment]
For some reason, the project manager window always opens on the first monitor. Even if I place the project manager to the second, the editor window again opens at the first. And `Editor Settings` → `Run` → `Window Placement` settings does not have effect on the debug window...

**Comment by Chaosus** [comment]
> Which settings? Editor Settings → Run → Window Placement seems to work fine.

Ah, yes it does affect but, firstly the window opened at first monitor and after about a half of second placed to the second. If its turned to be full screen, it does not even happen.

**Comment by bruvzg** [comment]
> For some reason, the project manager window always opens on the first monitor. Even if I place the project manager to the second, the editor window again opens at the first.

Why would project manager position have any effect on editor position? For me, it was always opening on a firs screen, so nothing changed.

It's always trying to open the main window in the middle of the first screen: https://github.com/godotengine/godot/blob/dc3175e4cdb4e54e1c6200b6c4d07646eea95284/platform/windows/display_server_windows.cpp#L3944-L3946
But it's doing in it a wrong way assuming first screen coordinates starts at `(0,0)`, so might explain why it was different for you.

Not sure what would be the best behavior, maybe open main window on a screen where the mouse cursor is?

**Comment by Chaosus** [comment]
> Why would project manager position have any effect on editor position? For me, it was always opening on a firs screen, so nothing changed.

Ah, never mind, this does not affect it either in 4.0 beta 10, my bad. 
But still it running on the first display, which is not a main display!

Confirmed that reverting f7955633de42d660a24efafdf32b3bd3b72f6251 will fix this issue.

**Comment by bruvzg** [comment]
> Firstly the window appears at first monitor and after about a quarter of second placed to the second. If it's turned to be full screen in the project settings, it does not even happen (so it is placed always on the first monitor in Fullscreen or Exclusive Fullscreen modes).

Seems like `Editor Settings → Run → Window Placement` is trying to set window position (not screen number) after the window is opened, which is causing issues with fullscreen windows.

> Not sure what would be the best behavior, maybe open main window on a screen where the mouse cursor is?

I guess there probably should be a dedicate setting for this.

**Comment by TokisanGames** [comment]
Yes, this is an annoying change from b10. For me the editor and manager start on my secondary external monitor and I have to move it every time to my main laptop monitor. The game is set to start on the editor monitor, but even when the editor is moved, the game starts on the secondary, then moves itself after a second.

**Comment by Chaosus** [comment]
Nope, I don't see the effect from https://github.com/godotengine/godot/pull/70939 on the project manager and the editor. I see the new settings, and by default it's setted as primary but don't run on the actual primary monitor,
