### ISSUE TITLE
Typed Arrays do not accept newly-created subclasses in the editor until the editor is restarted

### ISSUE THREAD

**Issue by SekoiaTree** [godotengine/godot#70918]
### Godot version

4.0.beta9

### System information

Pop!_OS 22.04

### Issue description

A typed array will not suggest a subclass of its assigned type once the subclass is created until the editor is restarted.

Once restarted, everything works correctly. However, if you make the subclass no longer a subclass of the assigned type, it will still suggest it, but errors get thrown or generally strange behavior happens.

![A screenshot of the bug](https://user-images.githubusercontent.com/51149447/210580991-f00fbf40-dce7-4eaa-bc2d-2dcfe1f882cd.png)

### Steps to reproduce

- Create a script that exports an array of some type
- Create a subclass of that type
- Observe that the editor does not suggest the subclass for creation 
- Restart the editor
- Observe that the editor does suggest the subclass

### Minimal reproduction project
[TypedArrayExport.zip](https://github.com/godotengine/godot/files/10354856/TypedArrayExport.zip)

In this project there are the following files:
- `Mineral.gd`, a custom resource extending `Resource` or `Object`, depending on a comment
- `Bismuth.tres`, a custom Mineral
- `Main.tscn` a scene containing nothing but a Node2D
- `Main.gd` a script exporting a `Array[Resource]`

**Comment by SekoiaTree** [comment]
Update: I just realized that this probably does the same for any typed array with new subclasses. Gonna simplify my minimal reproduction project and update the issue accordingly in a minute.

**Comment by KoBeWi** [comment]
Looks fixed on master.
