### ISSUE TITLE
Possible candidates for HTML5 performance improvement

### ISSUE THREAD

**Issue by curly-brace** [godotengine/godot#7091]
I've tested the performance of a game exported to html5 and see a very bad performance even on very simple content and it seems like bottleneck is in drawing, rather then gdscript itself.
forget to mention: it is 2.2 build
[![profiling results](https://s18.postimg.org/b8b8nh4m1/Screenshot_at_2016_11_10_18_06_51.png)](https://postimg.org/image/erx6da7bp/)

**Comment by reduz** [comment]
This should hopefully work a lot better in the new GLES3/WebGL2 branch, as
Godot 2.0 currently suffers from too many API calls.

**Comment by curly-brace** [comment]
@reduz hey! i was struggling with compilation of javascript export templates on gles3 branch and it seems to be completely broken. lots of headers are missing :thinking: i was trying to add them, according to compiler messages, but then it appeared that source files are missing too (together with headers tho) in different engine parts. but editor itself seems to compile without any huge issues. could you help here?

**Comment by reduz** [comment]
gles3 branch is still super experimental and havent bothered to get it to
work on anything other than linux

**Comment by reduz** [comment]
should be ready for porting in a month or so

**Comment by curly-brace** [comment]
oh now i understood. those files are missing because they are not ported yet. thank you. waiting eagerly for godot 3.0 :smiley:

**Comment by punto-** [comment]
Can you show the reverse call stack?

**Comment by curly-brace** [comment]
@punto- what callstack? i didn't get you. it was not an exception, i did simple profiling in chrome while game was just running still for a few seconds

**Comment by mhilbrunner** [comment]
@bojidar-bg Close this?

**Comment by akien-mga** [comment]
Yep, this is obsolete by now. Let's see in new issues how the performance goes for 3.0.
