### ISSUE TITLE
Add Fullscreen for the editor! Please.

### ISSUE THREAD

**Issue by RealAquilus** [godotengine/godot#7092]
Ok this isn't an issue but it would be a really nice add for the editor. Please take this in consideration.
Thanks <3

**Comment by scovelme** [comment]
I dunno if you're using an outdated version or something, but there's always been a fullscreen option for me, it opens that way by default

**Comment by bojidar-bg** [comment]
@scovelme "Fullscreen" is not "maximised".

Anyway, should be simple to do, even if via a plugin.

**Comment by bojidar-bg** [comment]
@RealAquilus It is a "Feature Request" issue :wink: . I hope you aren't talking about no-distraction or main-screen-only modes, since we already have them.

**Comment by BBric** [comment]
Another interesting mode could be a "super maximized" window, with always the task bar but without the title bar.

**Comment by RealAquilus** [comment]
I talk about to hide the title bar of windows and the task board, a real full screen for the full editor, the unreal engine 4 have this feature. I hope you guys understand me, my english is not really good i'm sorry...

**Comment by punto-** [comment]
Try it on a plugin, you just need to call OS.set_window_fullscreen

**Comment by ISylvox** [comment]
Godot 2.2 or master branch has Fullscreen mode for Editor.

![fullscreen_godot-2 2](https://cloud.githubusercontent.com/assets/20697655/20203647/8af1af52-a7fb-11e6-9241-a98fe15b0f9b.png)

**Comment by volzhs** [comment]
yes. actually there has been 2 months. f10d2bd

**Comment by bojidar-bg** [comment]
Ouch, my bad... I assumed it was related to the no-distraction mode (just harder).

Closing as done then.

**Comment by RealAquilus** [comment]
Aaaahhh, i'm sorry i didn't compile the code and i haven't see that the 2.2 already have it, my fault. i'm sorry, thanks to all anyway.

**Comment by bojidar-bg** [comment]
@RealAquilus Well, don't worry -- some people (e.g. me) that are always on master version don't even notice it :wink:
