### ISSUE TITLE
save to file option dont work when generate physics is ticked on when importing gltf files

### ISSUE THREAD

**Issue by loafbrr** [godotengine/godot#70937]
### Godot version

4.0 beta 10

### System information

windows 10,vulkan, amd radeon graphics

### Issue description

Mesh data of objects is not saved when the physics is ticked on under generate on the import window of the gltf file
![image](https://user-images.githubusercontent.com/31808683/210714900-65378cf9-8759-47da-8b47-d75bdd314664.png)
![image](https://user-images.githubusercontent.com/31808683/210714941-00415846-d7e1-43e6-b813-5044c114a56f.png)

### Steps to reproduce

open the gltf file to access the import window;
tick on physics under generate on the scene tab
go to meshes tab and enable save to file and choose a destination
then press reimport

### Minimal reproduction project

N/A

**Comment by dame-ng** [comment]
This also happens if -col suffix is added to the mesh to generate collisions. Without physics checkbox ticked on.
