### ISSUE TITLE
The game never recovers after paused from debugger

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#70932]
### Godot version

4.0 beta9

### System information

Windows 10 x64

### Issue description

When I pause a game using debugger, either manually or using breakpoint or via an error break, the game can't be continued anymore. Resume button does nothing and the window is frozen. *Sometimes* it does continue (but rarely) and a few times I managed to trigger a crash

Another, probably related issue, is that remote tree can't be used while the game is paused. Selecting nodes does not switch inspector properly and after a few selects the inspector will randomly switch between nodes on its own.

Here's a video displaying the issue(s):

https://user-images.githubusercontent.com/2223172/210675180-d4c9fa6a-00ca-4279-95b1-df9c0b9a560f.mp4

Unfortunately I can't reproduce it in a minimal project, so this might be only happening in big projects™.

### Steps to reproduce

1. Be me
2. Try to use breakpoints :<

### Minimal reproduction project

N/A

**Comment by DmitriySalnikov** [comment]
Probably a duplicate of #68232 or #67696

**Comment by Zireael07** [comment]
I have the same problem (long before beta 9) and it's not happening in a minimal project either

**Comment by KoBeWi** [comment]
Doesn't seem related to #68232, although I have so many nodes that I can't say if I managed to remove all shaders 🙃
#67696 is also unrelated, because I don't use CPU particles.

**Comment by DmitriySalnikov** [comment]
As far as I know GPUParticles also use TIME.
![Godot_v4 0-beta10_win64_0vqZ2DdHdt](https://user-images.githubusercontent.com/7782218/211103914-4b9e98ab-0956-4bba-8f21-065465828335.gif)
[TIME.zip](https://github.com/godotengine/godot/files/10363285/TIME.zip)
If you hide all the particles in this example, there will be no freeze. Have you tried hiding particles?

**Comment by KoBeWi** [comment]
> Have you tried hiding particles?

If deleting all process materials from particle nodes counts, yes.

**Comment by Gnumaru** [comment]
@KoBeWi Could you test if setting "editor settings > interface > editor > update continuously" to true works around your issue?

**Comment by KoBeWi** [comment]
I checked in beta 16 and the issue doesn't seem to be happening at all 🤔
It doesn't mean it's fixed, maybe there is some trigger I don't know (although it doesn't occur in the circumstances it did before).

**Comment by KoBeWi** [comment]
Status update: in beta 17 trying to continue from debugger break (error, assert ect) ends in crash 🤪

**Comment by KoBeWi** [comment]
Ok I'm pretty sure this does not happen anymore.

**Comment by Zireael07** [comment]
Confirming that my game now pauses/unpauses properly too in rc1
