### ISSUE TITLE
Window size increases by 10px

### ISSUE THREAD

**Issue by fangameXPmaster** [godotengine/godot#70938]
### Godot version

4.0beta10

### System information

Windows11

### Issue description

Project→Project Settings→Desplay→Resizable
When I turn off Resizable, the Window size increases by 10px. Why is this?
It doesn't seem to be a problem on Ubuntu, not sure on Mac, but probably a Windows-specific issue.
The same problem also occurs with 3.5.1

### Steps to reproduce

Create new project(renderer can be anything, but just in case, Mobile)→choose to settings(Project→Project Settings→Desplay→Resizable)→turn off Resizable
※In the sample project, a screenshot is generated at startup to make it easier to see the window size.

### Minimal reproduction project

[Test2.zip](https://github.com/godotengine/godot/files/10349907/Test2.zip)

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/62869.
