### ISSUE TITLE
The tileset keeps moving when I try to edit it

### ISSUE THREAD

**Issue by ShatReal** [godotengine/godot#70935]
### Godot version

4 beta 10

### System information

win 11

### Issue description

So I have a very skinny tileset image. When I try to make a tile at the top of the image, it jumps down to some where in the middle. Why does it do this?

### Steps to reproduce

make a tileset with a skinny image

### Minimal reproduction project

none

**Comment by KoBeWi** [comment]
Bug in action.

https://user-images.githubusercontent.com/2223172/210833302-b10d42ee-99a8-4f8d-a288-2b73d5baf9a9.mp4

I think it happens after you change the zoom level. When you edit without changing zoom the view is stable.
