### ISSUE TITLE
Autofill failure in GDScript

### ISSUE THREAD

**Issue by MAX-71** [godotengine/godot#70941]
### Godot version

4.0 beta10

### System information

Fedora Linux 37 (W.E) GNOME 43.2

### Issue description

if Input.is_action_pressed("move_left"")  
 Adds extra quotes when auto-selecting
If you put quotes there is no error

### Steps to reproduce

![Снимок экрана от 2023-01-05 12-20-48](https://user-images.githubusercontent.com/58471294/210746493-88dccc53-f63f-4881-b443-24ed4deb13a9.png)
![Снимок экрана от 2023-01-05 12-21-50](https://user-images.githubusercontent.com/58471294/210746747-8cccb3bb-508c-41de-ae05-6c8586444930.png)
![Снимок экрана от 2023-01-05 12-08-14](https://user-images.githubusercontent.com/58471294/210747214-134b43e6-383a-43c8-83c6-31c4945f043b.png)

### Minimal reproduction project

"N / A"

**Comment by arkology** [comment]
If I'm not mistaken, this has already been reported and fixed in master.
