### ISSUE TITLE
Godot Script editor: tabs positions restored after every opened script or editor restart

### ISSUE THREAD

**Issue by PabloNeirotti** [godotengine/godot#70943]
### Godot version

v4.0.beta10.official [d0398f6]

### System information

Apple M1 Max - macOS Ventura 13.1 (22C65)

### Issue description

The positions of the scripts on the sidebar tabs are restored to some initial position they first had when:
- Restarting the editor
- Opening a script file

The **expected behavior** is that a tab should be opened next to the current tab. No tab reordering should occur. It is otherwise very hard to know where everything opens on a large project if positions keep changing all the time.

https://user-images.githubusercontent.com/905216/210768531-a34c17a5-b8a1-4430-ba6f-6a6b3a58fb88.mov

### Steps to reproduce

Shown on the video above.

### Minimal reproduction project

Can be reproduced in any project as far as I can tell.

**Comment by PabloNeirotti** [comment]
I just noticed that the editor by default sorts automatically by name. While that is seen as true on this small example, on a larger project I'm working on this isn't true. While the order-by-name setting was on, not all tabs where ordered correctly by name after every restart, so there is still something not working quite right. Probably why I didn't think it was ordered alphabetically to begin with.

That said, turning off the order sort seems to prevent the order to randomly change after a restart. Not sure if the alphabetical order still needs to be addressed though, but it isn't a pain point for me anymore.

**Comment by PabloNeirotti** [comment]
P.S: Since I cannot provide reproduction steps for the issue of alphabetical order, I guess we can close this.

**Comment by stmSi** [comment]
I was debugging for this issue.. Okie.. 🙂
