### ISSUE TITLE
Tres fonts way too large...

### ISSUE THREAD

**Issue by horseyhorsey** [godotengine/godot#70949]
### Godot version

4 beta 10

### System information

Windows 10

### Issue description

I think this font is being incremented to, I will keep an eye on it as to where, but the file size seems incorrect for what this is. Which is now at 60mb. 

I ignore the file when committing because I know I haven't touched the font since the start of the project.

![image](https://user-images.githubusercontent.com/5377332/210808228-fdd8023e-c25a-4f11-bf33-6d16969e9602.png)

### Steps to reproduce

Could be that the original tres file came from Godot 3.4 but hadn't noticed any issues up until the file size.

### Minimal reproduction project

Normal tres font
![image](https://user-images.githubusercontent.com/5377332/210809638-aea53e0c-6ae5-40bf-9548-ff79d07ee2d2.png)

Borked
![image](https://user-images.githubusercontent.com/5377332/210809513-5ec2c6b4-4aed-4591-a212-03fd9eb23ee1.png)

**Comment by Calinou** [comment]
This is because you saved a binary resource in a text file, which causes all the data to be included in text form, making it much larger.

In Godot 4.0, you generally don't need to save the font to a Godot resource file, as antialiasing and hinting properties are set in the Import dock.

**Comment by horseyhorsey** [comment]
I see, thanks for the extra info. This was a project I had been working on which was in Godot 3.4 and I only set the font after I first loaded it, then left it. 

Coming from using 3, creating a `tres` font was a standard thing to do and was unaware you could use the .ttf directly.

If I had looked at the [Upgrade: Removed or replaced nodes/resources](https://docs.godotengine.org/en/latest/tutorials/editor/upgrading_to_godot_4.html) then I wouldn't have figured it out.
