### ISSUE TITLE
The actual font size is different from the fill

### ISSUE THREAD

**Issue by L2750558108** [godotengine/godot#70958]
### Godot version

3.5.1mono

### System information

windows10

### Issue description

The actual font size is different from the fill.I set the size to 14 pixels, but it was only 8 pixels
![image](https://user-images.githubusercontent.com/119792950/210832492-a0eb86cb-1439-4da1-beec-b218741a0517.png)

### Steps to reproduce

Use this ([bahnschrift.zip](https://github.com/godotengine/godot/files/10353902/bahnschrift.zip)) font
Test like the picture
![image](https://user-images.githubusercontent.com/119792950/210832492-a0eb86cb-1439-4da1-beec-b218741a0517.png)

### Minimal reproduction project

No

**Comment by AThousandShips** [comment]
Font size doesn't necessarily mean the size of a letter, usually it doesn't, I'd recommend reading up on font sizing and relevant details.
