### ISSUE TITLE
Window focus doesn't refocus window after clicking in the editor.

### ISSUE THREAD

**Issue by viksl** [godotengine/godot#70955]
### Godot version

4.0 Beta 10 mono

### System information

Windows 10, Nvidia GTX 1660Ti, Vulkan

### Issue description

When I open the import window by clicking on a gltt scene and then press back in the editor if I try to go for example close the import window or anything I can't. The window focus stays on the editor in the background so I have to click elsewhere in windows and then I can focus the import window back again. It happens all the time.

### Steps to reproduce

1. Open a 3d scene in the import window (double click on a 3d asset, in my case I have an export from blender through gltf exporter)
2. Click on the godot editor in the background.
3. Try to click on anything in the import window again - you shouldn't be able to, check window title bars and observer the active window is the editor in background all the time.
4. Minimaze godot or click on your desktop or some other window outside godot
5. You can now focus back on the import window.

### Minimal reproduction project

-

**Comment by akien-mga** [comment]
Is this still reproducible in 4.0 RC 3 or later?

**Comment by viksl** [comment]
@akien-mga I'm in RC3 dotnet and it seems to be fine or at least after a quick test it didn't give me any problems.
I reported some other problems with focus in a different report couple days/weeks ago or so which were at least in rc1 and rc2 still issues I believe.

This one seems to be ok for me now on WIndows 10.
