### ISSUE TITLE
Godot Built in code editor

### ISSUE THREAD

**Issue by Dairoe** [godotengine/godot#70959]
### Godot version

3.5 stable

### System information

Linux

### Issue description

I been playing around with gds , I have some code for example _on_gui_input(event) in the body i try to do some stuff with event and sometimes the linter/helper complete doesn't work....the work around i do  is do some event on a different special
 godot event func nd copy paste the code inside original 

### Steps to reproduce

explained above

### Minimal reproduction project

None

edit:
see here

https://user-images.githubusercontent.com/121760097/210875506-252360a6-1b2f-4cec-9694-87f5e924010b.mp4

**Comment by adamscott** [comment]
@Dairoe Please make your issue title more descriptive. The current one doesn't describe what's the issue in one line.

**Comment by Calinou** [comment]
Autocompletion isn't expected to work reliably when you have errors in the script, especially in 3.x.

**Comment by Calinou** [comment]
@Dairoe Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.
