### ISSUE TITLE
Popups are positioned with an offset on Windows with a vertical taskbar

### ISSUE THREAD

**Issue by YuriSizov** [godotengine/godot#70966]
### Godot version

4.0 (#b2a5b55)

### System information

Windows 10 22H2

### Issue description

Seems to be a regression from https://github.com/godotengine/godot/pull/70624. All popups in the editor are placed with an offset to their expected position. The issue is reproduceable on a display with a vertical taskbar (pinned on the left side), but not in the taskbar is horizontal (pinned at the bottom).

https://user-images.githubusercontent.com/11782833/210861314-9af49c05-24b9-49eb-98a5-e64327a565f7.mp4

### Steps to reproduce

Make sure you have a vertical taskbar, and open the editor with any project. Try to access items of the top menu.

### Minimal reproduction project

n/a

**Comment by stephannv** [comment]
I'm having a related problem on M1 Max Mac OS (12.6) on TileSet panel. The X coordinate always seems to be zero.

https://user-images.githubusercontent.com/3025661/210902687-0e4d6c59-ff3a-47ec-80d6-9ba839868316.mov

**Comment by YuriSizov** [comment]
@stephannv Which version is that?

**Comment by stephannv** [comment]
> @stephannv Which version is that?

@YuriSizov 4.0.beta10. The animations panel has the same problem too:

https://user-images.githubusercontent.com/3025661/211163418-b7fae014-b503-4d03-bb63-30b21473689a.mov

**Comment by YuriSizov** [comment]
@stephannv Then this is unrelated, please file a new bug for this issue. It is possible, though, that this is fixed now, but it is still worth filing a dedicated bug report.

**Comment by stephannv** [comment]
Thanks @YuriSizov . I filled a issue (https://github.com/godotengine/godot/issues/71067). I noticed that problem is occurring with other popups/popovers too, and solves itself on godot restart.
