### ISSUE TITLE
Vulkan Clustered: Large GPU cost for rendering nothing

### ISSUE THREAD

**Issue by TheJazMaster** [godotengine/godot#70971]
### Godot version

4.0 beta 10

### System information

Manjaro 6.0.15-1. GPU: AMD Lucienne. Driver: amdgpu. Renderer: forward-plus

### Issue description

I'm not sure how this is supposed to work, so forgive any silly observations.

I've been having performance issues with my game. The tonemapping part of the GPU frame time was always large, so I decided to create a completely empty project save for a camera and see the visual profiler.

The small bump on the left is the GPU time with the default game window size. The much larger part on the right is what it looks like after I maximise the window (1920x1080 monitor).

This seems like way too high of a cost for rendering a gray screen, and an absurd jump in GPU usage for resizing the window. I assume it's what's causing performance issues for my game. What is going on?

![image](https://user-images.githubusercontent.com/47794482/210893129-dca2731d-3063-4ef0-9b1b-8e0a12ea517c.png)

### Steps to reproduce

Create an empty project, add a scene with a Node3D and a Camera3D child. Play and start the visual profiler.

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
Can you try the same thing on the mobile renderer?

The forward-plus renderer is written with Desktop class GPUs in mind. Mobile and integrated GPUs work quite a bit differently and, in particular, have a lot of trouble processing a lot of pixels. So things that require every pixel be processed (like the tonemapping pass) can take a significant amount of time. 

What sort of post processing effects do you have enabled? Have you turned off glow and tonemapping?

**Comment by TheJazMaster** [comment]
I have nothing enabled as it is an empty project with no environment and default settings.
As far as I know, tonemapping can not be turned off, not even in an environment. Can it? And where.

The mobile renderer is indeed a lot more reasonable (regular window and then maximised)
![image](https://user-images.githubusercontent.com/47794482/210897465-fe57756c-2bb7-4bb7-b3c3-3d30cc07a083.png)

**Comment by clayjohn** [comment]
I think most likely this is just a limitation of your iGPU. If you are interested, you can investigate further by running Godot through the [Radeon GPU Profiler](https://gpuopen.com/rgp/) (I think your GPU should support it). This would tell you a little bit more about what exactly is making the tonemapper run so slow and may give us some hints on what could be improved.

**Comment by Calinou** [comment]
It may be worth considering a project setting to fall back to the mobile backend when integrated graphics are detected. This will have to be enabled explicitly though, as the mobile backend has limitations that may make your project look broken if you don't account for it.

**Comment by Calinou** [comment]
Closing, as this is a limitation of the Forward+ rendering method.
