### ISSUE TITLE
Subviewport Window PopupPanel doesn't allow movement of child nodes via editor

### ISSUE THREAD

**Issue by ShatReal** [godotengine/godot#70976]
### Godot version

4.0 beta 10

### System information

win 11

### Issue description

sorry if this is a repeat

There is no cross icon that shows where the node is located. When I click on it nothing (the popup, child node) moves.

### Steps to reproduce

make one of the nodes listed and add a child with a position

### Minimal reproduction project

none

**Comment by timothyqiu** [comment]
A related proposal: https://github.com/godotengine/godot-proposals/issues/5422

**Comment by KoBeWi** [comment]
Technically duplicate of #20619
