### ISSUE TITLE
Crash at starting project manager or editor

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#7097]
**Operating system or device - Godot version:**
Ubuntu 16.04, complied with 7751a93

**Issue description** (what happened, and what was expected):
I complied tool with **target=release_debug** on Ubuntu and run `./bin/godot.x11.opt.tools.64`
```
$ ./bin/godot.x11.opt.tools.64
WARNING: initialize: Error setting locale modifiers
   At: platform/x11/os_x11.cpp:120.
Segmentation fault (core dumped)
```
if **target=debug**, no crash

**Steps to reproduce:**
with PR #6802, crash at start
```
$ git checkout 7751a93
$ scons -j 4 platform=x11 bits=64 verbose=no target=release_debug
$ ./bin/godot.x11.opt.tools.64
```

with before PR #6802, no crash
```
$ git checkout d0d81a2
$ scons -j 4 platform=x11 bits=64 verbose=no target=release_debug
$ ./bin/godot.x11.opt.tools.64
```

**Link to minimal example project** (optional but very welcome):

**Comment by Calinou** [comment]
I can reproduce this on Windows 10 64-bit, with Godot Git commit 7751a93 (64-bit tools in release_debug mode).
