### ISSUE TITLE
Circular dependencies of scenes (by preload) cause a script can not be loaded

### ISSUE THREAD

**Issue by jinyangcruise** [godotengine/godot#70985]
### Godot version

v4.0.beta10.official [d0398f62f]

### System information

Vulkan API 1.3.205 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3060 Ti

### Issue description

My project contains two scenes "cell.tscn"（attached with a script "cell.gd") and "swap_pad.tscn" (attached with a script "swap_pad.gd"). Everytime I open this project, the "cell.tscn" always lose its script "cell.gd" with an error log : 
```
ERROR: res://src/swapPad/cell.tscn:9 - Parse Error: [ext_resource] referenced non-loaded resource at: res://src/swapPad/cell.gd
   at: _parse_ext_resource (scene/resources/resource_format_text.cpp:178)
```
I need to re-attach this script to the scene to fix it temporarily but next time this problem happen again.
I finally figured out this problem happens if two scripts have circular dependencies. I don't know if this problem is or not a bug of Godot. If not, why can I fix it temporarily by re-attach the script to the scene. 

Content of "cell.gd":
```
extends CenterContainer

var _swapPad : SwapPad = null
```

Content of "swap_pad.gd"
```
extends Control
class_name SwapPad

func _ready():
	var cellClass := preload("res://src/swapPad/cell.tscn")
```

### Steps to reproduce

0.download minimal reproduction project below
1. open project
2. open cell.tscn（src/swapPad）in godot and you will find this scene have no script
3. attach cell.gd to cell.tscn
4. save and close project
5. open project again
6. open cell.tscn（src/swapPad）in godot and you will find this scene still have no script

### Minimal reproduction project

[test1.zip](https://github.com/godotengine/godot/files/10358858/test1.zip)

**Comment by Chaosus** [comment]
cc @adamscott

**Comment by adamscott** [comment]
I confirm this issue. This does not seem to be a regression. I'm investigating.

**Comment by dalexeev** [comment]
See also:

* #74253
* #77436

**Comment by adamscott** [comment]
For more info on this issue and why it's currently difficult to fix it, see the comments of my closed PR https://github.com/godotengine/godot/pull/71004.

**Comment by keir** [comment]
I put up https://github.com/godotengine/godot/pull/80854 to help make the user experience of this engine limitation easier to debug/deal with.

**Comment by Muhammad-Fiqri** [comment]
![image](https://github.com/godotengine/godot/assets/60091975/15057072-abe8-48f2-b51d-7b703f8332ce)
I got the same problem. 
The scene that get added to the scene with the error script lose its script and unable to be functional
