### ISSUE TITLE
Autocomplete suggestion for GDScript's `$'MyNode'` can suggest wrong syntax

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#70986]
### Godot version

4.0 beta 10

### System information

Ubuntu 22.04.1 LTS

### Issue description

If your node has `'` in its name, autocomplete might still suggest single quotes which results in an error.

![image](https://user-images.githubusercontent.com/85438892/210971332-81c13316-e7de-4d7d-9b08-f5676bf4c598.png)

![image](https://user-images.githubusercontent.com/85438892/210973393-ba999b6f-650c-461e-8d2d-b6a1a21adb76.png)

### Steps to reproduce

1. Add a child and name it `Juan's pancakes`
2. Add a script and type `$'`

### Minimal reproduction project

N/A

**Comment by MAX-71** [comment]
This error is repeated where there is autocomplete in () with quotes. An extra quotation mark appears. I didn't have single quotes in the node name.

**Comment by akien-mga** [comment]
Thanks!
