### ISSUE TITLE
Initial window size is below minimum size on i3 window manager (DisplayServer regression)

### ISSUE THREAD

**Issue by ttencate** [godotengine/godot#70984]
### Godot version

4.0beta10

### System information

Arch Linux, X.org, i3 window manager

### Issue description

The size of windows showing the Godot logo is initially very small, too small to show even the logo. They don't get bigger after their content is loaded, either.

This happens in the i3 window manager, which otherwise is pretty good at following standards like freedesktop. And the issue didn't occur in Godot 3, so I think something in the new version is to blame.

### Steps to reproduce

Have this in `~/.config/i3/config` to make Godot windows floating by default:

```
for_window [instance="^Godot_Engine$"] floating enable
```

Launch Godot 4:

![2023-01-06T08:24:17_3440x1440](https://user-images.githubusercontent.com/90930/210951751-700f2608-25c9-44b0-b8d9-9b745c39134f.png)

Wait until the project manager becomes "visible":

![2023-01-06T08:24:22_3440x1440](https://user-images.githubusercontent.com/90930/210951987-f4d2bf6a-3aa6-41ca-a959-51a52b8b7bb1.png)

Resize the window; it immediately snaps to its minimum size and can't be made smaller anymore:

![2023-01-06T08:24:28_3440x1440](https://user-images.githubusercontent.com/90930/210952756-34820f34-c0a1-4144-8547-79f7bac2aa0e.png)

(Black rectangle added afterwards, it does actually show my projects :))

### Minimal reproduction project

n/a

**Comment by bruvzg** [comment]
Incorrect min. size should be fixed by https://github.com/godotengine/godot/pull/70863, not sure why initial size is not set, probably i3 specific issue.

**Comment by schme** [comment]
Can confirm with i3, Ubuntu. Splash screens are tiny. Project Manager and Editor are resized when loaded to fill the content, but under the minimum. Editor is also not centered, but resizes on the spot towards bottom right.

**Comment by ttencate** [comment]
The behaviour with 4.0beta11 is better than in 4.0beta10, probably thanks to #70863: when the tiny splash screen turns into the project manager, the window is now automatically resized (towards the bottom right) to its new minimum size.

The splash screen still starts out tiny though.

**Comment by cptchuckles** [comment]
I continue to have this problem on RC 1.  Using `xprop` to see the window details of the running project, `program specified size` is set to 0x0 unless `display/window/size/resiable` is disabled, whereupon `program specified size` is correct, but *also* `program specified minimum/maximum size` are set (hence unresizable).  I have a hunch the whole thing would just work as expected if the `program minimum size` property would just get set when `resizable` is enabled, but for some reason it isn't.
```bash
#window resiable = false
$ xprop
_NET_WM_ICON(CARDINAL) = 	Icon (128 x 128):
	(not shown)

_NET_WM_NAME(UTF8_STRING) = "PokingAround (DEBUG)"
_NET_WM_DESKTOP(CARDINAL) = 2
_NET_WM_STATE(ATOM) =
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
I3_FLOATING_WINDOW(CARDINAL) = 1
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 384, 216
		program specified size: 1152 by 648
		program specified minimum size: 1152 by 648
		program specified maximum size: 1152 by 648
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
WM_CLASS(STRING) = "Godot_Engine", "PokingAround"
XdndAware(ATOM) = BITMAP
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW
WM_NAME(STRING) = "PokingAround (DEBUG)"
_NET_WM_PID(CARDINAL) = 17368
```
```bash
#window resiable = true
 $ xprop
_NET_WM_ICON(CARDINAL) = 	Icon (128 x 128):
	(not shown)

_NET_WM_NAME(UTF8_STRING) = "PokingAround (DEBUG)"
_NET_WM_DESKTOP(CARDINAL) = 2
_NET_WM_STATE(ATOM) =
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
I3_FLOATING_WINDOW(CARDINAL) = 1
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 0, 0
		program specified size: 0 by 0
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
WM_CLASS(STRING) = "Godot_Engine", "PokingAround"
XdndAware(ATOM) = BITMAP
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW
WM_NAME(STRING) = "PokingAround (DEBUG)"
_NET_WM_PID(CARDINAL) = 17867
```

**Comment by ttencate** [comment]
@cptchuckles Thank you, that's great info! Based on that, I did some more debugging. Here's the code responsible:

https://github.com/godotengine/godot/blob/4848877b802b17f4ab1aecfde42c81a7cc9b6f08/platform/linuxbsd/x11/display_server_x11.cpp#L1640-L1645

It was added in a31b164071dd7af790d4b62057d9f9222285e59d, almost three years ago. Before this commit, setting the position and size hints was conditional on `id != MAIN_WINDOW_ID`. That check disappeared. If I put it back, the problem is solved for me. However, I don't think that's the correct fix.

This is called once, in `_create_window`:

https://github.com/godotengine/godot/blob/4848877b802b17f4ab1aecfde42c81a7cc9b6f08/platform/linuxbsd/x11/display_server_x11.cpp#L5109

It's worth noting that none of `window_set_size`, `window_set_min_size` and `window_max_size` get called at project manager startup. So i3 does the right thing here: it tries to honour Godot's silly request of a 0x0 window. The issue description "window size is below minimum size" is misleading since there is no minimum size.

Related: the settings `display/window/size/viewport_width` and `display/window/size/viewport_height` have no effect on the initial window size. It seems like `window_set_size` is never called when running the game from the editor either.

These sizes should normally be set from `Window::_update_window_size`:

https://github.com/godotengine/godot/blob/master/scene/main/window.cpp#L914-L916

The root window is automatically created by `DisplayServer`, so it's a special case. It turns out that `window_id == -1` on the root `Window` object throughout startup, so the check `window_id != DisplayServer::INVALID_WINDOW_ID` fails, even if the window is long visible already.

`Window::window_id` is set to `DisplayServer::MAIN_WINDOW_ID` when receiving `NOTIFICATION_ENTER_TREE`, which is very late in the startup process:

https://github.com/godotengine/godot/blob/master/scene/main/window.cpp#L1116

Even then, `_update_window_size` is not called.

I'll send a PR to fix both these issues.
