### ISSUE TITLE
[Editor] Mouse cursor locks up when right-clicking while using a scrolling number input field

### ISSUE THREAD

**Issue by jmf** [godotengine/godot#7098]
**Operating system or device - Godot version:**
Crux Linux, Kernel 4.9.0rc2
Godot 12843167cacf3bacca32c29b7ea8b4426392bad0

**Issue description** (what happened, and what was expected):
When holding the left mouse button pressed to scroll through numbers in a scrolling number field and then clicking right, the mouse cursor locks up and disappears. Expected behavior would be the mouse cursor not locking up and re-appearing.

**Steps to reproduce:**
1: You need a scrolling number input field. You can create a Sprite3D which has input fields like that, for example the ones for Vframes and Hframes.
2: Left-click the field and hold the button while moving your cursor to change the number.
While still holding the left mouse button, perform a right-click.
3: The cursor stays invisible and is locked up. Keyboard input still works though.

**Comment by Zylann** [comment]
Also got this behaviour with Godot 2.1 on Windows 10 64 bits.

**Comment by bojidar-bg** [comment]
BTW, mouse is locked on [`tree.cpp:2312`](https://github.com/godotengine/godot/blob/master/scene/gui/tree.cpp#L2312) and unlocked on [`tree.cpp:2363`](https://github.com/godotengine/godot/blob/master/scene/gui/tree.cpp#L2363) and then again on [`tree.cpp:2949`](https://github.com/godotengine/godot/blob/master/scene/gui/tree.cpp#L2949) (but the second time doesn't matter much).
Also, it is done for spinbox controls seperately in [`spin_box.cpp:173`](https://github.com/godotengine/godot/blob/master/scene/gui/spin_box.cpp#L173)/[`spin_box.cpp:152`](https://github.com/godotengine/godot/blob/master/scene/gui/spin_box.cpp#L152), but this implementation doesn't suffer from the bug.

**Comment by jmf** [comment]
For me, #7385 fixes the bug.
