### ISSUE TITLE
[GUI SIGNAL BUG] Bug about "_gui_input ()" function and its signal "gui_input ()"

### ISSUE THREAD

**Issue by Atem1995** [godotengine/godot#70992]
### Godot version

4.0 Beta 10

### System information

Window10

### Issue description

![捕获](https://user-images.githubusercontent.com/52338846/211019345-b07e5de0-248a-430d-b090-c88ac09bec6f.PNG)
As shown in the figure, when you click the node signal trigger area with the "left mouse button", it will be triggered twice; However, if it is the "middle button" or "right button" and "additional key position" of the mouse, it will only be triggered once.

### Steps to reproduce

略

### Minimal reproduction project

略

**Comment by timothyqiu** [comment]
I guess you're using `input_devices/pointing/emulate_touch_from_mouse`. Enabling this setting will generate both an `InputEventScreenTouch` and an `InputEventMouseButton` for left mouse click.
