### ISSUE TITLE
The "editable children" behaviour sticks even after a scene instance is deleted and placed again

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#7099]
Tested on Godot 2.1, Windows 10 64 bits

Repro steps:
1) Create a scene with child nodes
2) Instance it in another scene
3) Enable "Editable children"
4) Delete the whole instance
5) Instance it again: notice it still has editable children, even though it should be a new instance.
Instancing scenes resulting in different root name doesn't make their children editable. It doesn't happen if the editor is restarted between 4) and 5).

It's probably related to https://github.com/godotengine/godot/issues/6455, my guess is the "editable" nodes is not a state of the nodes themselves, but a separate list, and this list is not updated when the node is deleted from the tree.

**Comment by Noshyaar** [comment]
I'll close this as it's the same issue as #6455. Still reproducible 9e7cee2.
