### ISSUE TITLE
There may be an incorrect reaction to user actions in the interface

### ISSUE THREAD

**Issue by MAX-71** [godotengine/godot#70990]
### Godot version

4.0 beta10

### System information

Fedora Linux 37 (W.E.) GNOME 43.2

### Issue description

CollisionObject2D click the Mask property and uncheck the first checkbox. This ensures that mobs will not collide with each other. This is recommended in the documentation for action
![Снимок экрана от 2023-01-06 13-56-39](https://user-images.githubusercontent.com/58471294/211005421-05fda86d-1d59-414a-962c-15ddc56cbe7c.png)
![Снимок экрана от 2023-01-06 14-42-11](https://user-images.githubusercontent.com/58471294/211006663-c93bd853-c25f-43b8-9cab-1350513198b7.png)
After it did not occur to edit the CollisionObject2D mask correctly, it is not visible

### Steps to reproduce

The documentation and documentation actions are described above

### Minimal reproduction project

"N / A"

**Comment by Zireael07** [comment]
This is visibility layer, not physics layer

**Comment by kleonc** [comment]
Closing per @Zireael07's comment.
