### ISSUE TITLE
4.0.beta10, Code completion adds an extra double quote

### ISSUE THREAD

**Issue by duianto** [godotengine/godot#70997]
### Godot version

This is an issue in:
v4.0.beta10.official [d0398f62f]

It works as expected in:
v3.5.1.stable.official [6fed1ffa3]

### System information

Windows 22H2, Compatibility, GeForce GTX 550 Ti

### Issue description

Code completion adds an extra double quote.
(| = cursor)
Before
```
$AnimationPlayer.play|
```

After typing an open parenthesis and accepting (`enter`) the code completion suggestion to add the animation: `"New Anim"`
```
$AnimationPlayer.play("New Anim"|")
```
An extra double quote was added.

### Expected
```
$AnimationPlayer.play("New Anim"|)
```

### Steps to reproduce

- start godot
- open the attached project
- open the script: `Node2D.gd`
(either from the Scene panel, by clicking the script icon to the right of `Node2D`
or from the FileSystem panel, by double-clicking on: `Node2D.gd`
or by selecting `Script` above the viewport)
- on line 7, (under `def _ready():`), replace the line `pass # Replace with function body.` with:
```
$AnimationPlayer.play
```
- type an open parenthesis: `(`
a code completion list appears with one choice: `"New Anim"`
- press `enter` to accept the selected choice

### Expected
The choice should be inserted between the parentheses:
```
$AnimationPlayer.play("New Anim"|)
```

### Observed
An extra double quote was added.
```
$AnimationPlayer.play("New Anim"|")
```
The status bar shows the message:
>Error at (7, 37): Unterminated string.

![Godot_v4 0-beta10_win64_RN0r27Oxle](https://user-images.githubusercontent.com/13420573/211033166-973482b4-49d9-43f0-a2e5-318a7fa51761.png)

### Minimal reproduction project

[issue, code completion, extra double quote.zip](https://github.com/godotengine/godot/files/10360798/issue.code.completion.extra.double.quote.zip)

**Comment by jpcerrone** [comment]
this issue also appears in 4.0.beta10

**Comment by duianto** [comment]
If I was unclear.
This is an issue in: v4.0.beta10.official [d0398f62f]
It works as expected in: v3.5.1.stable.official [6fed1ffa3]

**Comment by AThousandShips** [comment]
Duplicate of #70535

**Comment by duianto** [comment]
Your right, it's a known issue, I missed them when I tried to search for existing issues.
This might be the PR that fixes it:
Fix autocompletion inserts an extra quotation by heppocogne https://github.com/godotengine/godot/pull/70699
