### ISSUE TITLE
JSON parses as wrong number for a big integer

### ISSUE THREAD

**Issue by luxmargos** [godotengine/godot#71019]
### Godot version

4.0-beta10

### System information

Windows 11, Vulkan, RX560

### Issue description

The parsed object thru JSON has wrong value for an integer which has large amount. A small value have no problem. For now, I'm using tricky way that converting string to int .

### Steps to reproduce

CODE : 
```GDScript
var json_obj = JSON.parse_string("{\"num1\":11111111111111111, \"str1\":\"11111111111111111\"}")
print("num1 : ", json_obj.num1)
print("str1 : ", json_obj.str1)
print("str1 to num : ", int(json_obj.str1))
```

OUTPUT :
```text
num1 : 11111111111111112
str1 : 11111111111111111
str1 to num : 11111111111111111
```

### Minimal reproduction project

[GODOT_JSON_PARSE_ERROR.zip](https://github.com/godotengine/godot/files/10365911/GODOT_JSON_PARSE_ERROR.zip)

**Comment by timothyqiu** [comment]
It's the float precision problem when you use `float("11111111111111111")`.

Decimal 11111111111111111 has 54 digits in binary. But IEEE-754 double can only have 53 significant binary digits.

**Comment by luxmargos** [comment]
> It's the float precision problem when you use `float("11111111111111111")`.
> 
> Decimal 11111111111111111 has 54 digits in binary. But IEEE-754 double can only have 53 significant binary digits.

Thank you for your explanation. Eventually, it is not a bug.
