### ISSUE TITLE
OpenGL: TextureArrays and Texture3D samplers not implemented yet

### ISSUE THREAD

**Issue by jmdejong** [godotengine/godot#71029]
### Godot version

Godot Engine v4.0.beta10

### System information

archlinux; vulkan on dedicated `NVIDIA GeForce RTX 3060 Laptop GPU`; opengl3 on integrated `AMD Radeon Graphics (renoir, LLVM 14.0.6, DRM 3.49, 6.1.1-arch1-1)`

### Issue description

With the opengl3 backend a shader will read a Samper2dArray uniform as being completely black.

opengl3:
![texturearray_opengl3](https://user-images.githubusercontent.com/7968950/211161142-48379a1b-ea3c-4529-bbda-ad837f56bbfb.png)

vulkan:
![texturearray_vulkan](https://user-images.githubusercontent.com/7968950/211161147-d84389cb-737f-4229-9984-36d9dd12a0ce.png)

used shader:
```
shader_type spatial;

uniform sampler2DArray textures : source_color, filter_linear_mipmap;

void fragment() {
	ALBEDO = texture(textures, vec3(UV, 1.0)).xyz;
}
```

### Steps to reproduce

Create a scene with a meshinstance3d with the shader above as a material.
Give that shader a Texture2DArray as parameter.
With the vulkan renderer this will run fine, but with opengl3 the texture is read as being completely black.

### Minimal reproduction project

[sampler2darray.zip](https://github.com/godotengine/godot/files/10366728/sampler2darray.zip)

**Comment by clayjohn** [comment]
Looks like this hasn't been implemented yet in the gl_compatibility nor have 3D textures. It should not be a lot of work to implement.

**Comment by Wolfe2x7** [comment]
Good news: as of Godot 4.1 RC1, TextureArrays are now functional in the OpenGL Compatibility renderer. 👍  Texture3Ds are still not implemented yet.

The cube should be a bright color, not black:

![Image3](https://github.com/godotengine/godot/assets/72348938/486c5fd7-2716-4ebd-a1e5-52c56c455e96)

**Comment by alula** [comment]
and here are Texture3Ds :eyes: 

![image](https://github.com/godotengine/godot/assets/6276139/c3314f06-45b4-4f20-9d57-8fdded314350)

**Comment by quinoazephyr** [comment]
hi! i'm using v4.1.stable.official.970459615 and sampler2DArray is not working correctly in the Mobile mode (it ignores frame number parameter). is it expected or a bug?
