### ISSUE TITLE
Changed NavMesh import settings on GLTF/GLB files not propogated to inheriting scenes

### ISSUE THREAD

**Issue by corjohnson** [godotengine/godot#71039]
### Godot version

v4.0.beta.custom_build [fcba87e69]

### System information

Windows 11, Vulkan

### Issue description

When trying to change a setting in the imported GLTF file; the changes are not applied to the scene(s) that inherit the GLTF scene. In my specific case, I had a mesh that I imported and in the settings selected "NavMesh: Mesh + NavMesh" under the `MeshInstance3D` import settings. I created a new scene which inherited from the GLTF one, and added some other nodes to it. Later I decided to change the NavMesh setting to Disabled on the import, and then clicked "reimport". The generated nav mesh node persisted in my inherited scene until after I reloaded the project using Project > Reload Current Project

### Steps to reproduce

1) Open an imported GLTF/GLB file
2) Click the MeshInstance3D
3) Select dropdown for `NavMesh` under `Generate` section, and select `Mesh + NavMesh`
4) Click re-import
5) Open GLTF/GLB to verify the read-only scene has a navigation region
6) Save as a new inherited scene with a name
7)  Open the import settings for GLTF/GLB file again
8) Change the NavMesh option
9) Click re-import
10) Observe the navigation region still present in inherited scene
11) Reload the project
12) Open the inherited scene, observe the navigation region is now gone

### Minimal reproduction project

[minimal_repro.zip](https://github.com/godotengine/godot/files/10367092/minimal_repro.zip)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/70255.
