### ISSUE TITLE
Vector2 operator * (Transform2D right) is using Transform2D.inverse() instead of Transform2D.affinity_inverse()

### ISSUE THREAD

**Issue by LuisCarli** [godotengine/godot#71035]
### Godot version

4.0 beta10

### System information

MacOS 12.6

### Issue description

The [Vector2 operator * (Transform2D right)](https://docs.godotengine.org/en/latest/classes/class_vector2.html#class-vector2-operator-mul-transform2d) gives a similar (but not the same) result to `Transform2D.inverse() * Vector2` instead of `Transform2D.affinity_inverse() * Vector2`. As a result doing `Vector2 * Transform2D` is not the inverse of doing `Transform2D * Vector2`.

`Transform2D.inverse()` does not take in consideration the scale of the transform, `Transform2D.affinity_inverse()` takes into consideration the scale. The confusion between those two functions is also mentioned [here](https://github.com/godotengine/godot/issues/39433).

### Steps to reproduce

Self contained code bellow.

### Minimal reproduction project

```GDScript
var xform = Transform2D(PI/2, Vector2(2, 2), 0, Vector2(16, 16))
var from = Vector2(1, 1)

var to = xform * from
var inverse = to * xform
prints(from, inverse) # (1, 1) (4, 4)

to = xform * from
inverse = xform.inverse() * to
prints(from, inverse) # (1, 1) (4.000002, 3.999998)

to = xform * from
inverse = xform.affine_inverse() * to
prints(from, inverse) # (1, 1) (1, 1)
```

**Comment by Calinou** [comment]
This may be done by design for performance reasons.

**Comment by LuisCarli** [comment]
The docs say that [`Vector2 operator * (Transform2D right)`](https://docs.godotengine.org/en/latest/classes/class_vector2.html#class-vector2-operator-mul-transform2d) "Inversely transforms (multiplies) the Vector2 by the given Transform2D transformation matrix". But it's doing that without considering scaling. 

If this is by design, why doing the transformation without considering scaling is a more relevant use case than with scaling?

**Comment by AThousandShips** [comment]
Since the documentation has been updated to make it clear it uses `inverse` this can be said to be complete:
> `vector * transform` is equivalent to `transform.inverse() * vector`. See Transform2D.inverse.
>
> For transforming by inverse of an affine transformation (e.g. with scaling) `transform.affine_inverse() * vector` can be used instead. See Transform2D.affine_inverse.
