### ISSUE TITLE
Color from String ARGB or RGBA?

### ISSUE THREAD

**Issue by Nickneim** [godotengine/godot#7104]
**Operating system or device - Godot version:**
Windows 10 64bit - Godot 2.1-stable_win64

**Issue description** (what happened, and what was expected):
Creating a Color from a String reads the string as Alpha, Red, Green, Blue. While the Docs say it should be read as RGBA which, as I understand, means Alpha is the last two characters.
This may be on purpose, since Color Picker also writes colors this way. Nevertheless it's weird that Color(0x000000FF) and Color("000000FF") create two different colors.

**Steps to reproduce:**
Just create a Color("000000FF") and a Color(0x000000FF) and check their Blue and Alpha values.

**Comment by Noshyaar** [comment]
Still reproducible/relevant in 3.1 master 9e7cee2 but the documentation now covers the component ordering and contains code snippets. I think it's safe to close this as fixed.
