### ISSUE TITLE
margin_top/tween_property type mixup and failure to implicitly convert between types

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#71043]
### Godot version

3.5.1

### System information

linux

### Issue description

Hello, I didn't know if there are multiple issues or one, but they are all related. I imagine they will all be seen as as designed, but it seems wrong and not as expected.

1. margin_top is defined as a float (if you drill down far enough in the docs to the Control node) however the UI/property inspector only allows integer values, everything is clamped. So if you enter 5.5 as a margin_top it is clamped to 6

2. In the Tween node you can do something like this:
$Tween.interpolate_property($ViewportContainer,"margin_top",10,100,10.5)

and it works.

but if you use new Scene Tree Tween
tw.tween_property($ViewportContainer,"margin_top",100,0.5)

you get a null return and an error in the debugger stating cannot convert from int to float. I guess three things from this too:

1. GDScript normally performs an implicit int to float cast, but not in this case
2. you would expect tween_property to work same as interpolate_property, but it doesn't
3. When you look at margin_top in the UI/property inspector you are led to believe (as point 1 at the very top) is an int

### Steps to reproduce

As above, I can provide example but I presume it's not needed.

### Minimal reproduction project

Happy to provide sample if required, but it seems it should be understandable without a sample

**Comment by Calinou** [comment]
@chucklepie Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by chucklepie** [comment]
@Calinou  I will delete this and create a new one with code as i've narrowed it down to a bug not a discussion point and my summary was a bit vague.
