### ISSUE TITLE
Removing a project from the project list also removes all projects in the same root folder

### ISSUE THREAD

**Issue by EddyAlleman** [godotengine/godot#71053]
### Godot version

4 beta 10 mono

### System information

windows 10

### Issue description

Hi Godot devs,

For testing purposes I made a specific test folder:
F:\GODOT4-tests

In there I create my test projects like:
F:\GODOT4-tests\test01-player
F:\GODOT4-tests\test02-FPS
F:\GODOT4-tests\test03-CS

When I select "test01-player" from the list above and press the "Remove" project button, I get a dialog asking if I really want to delete the project? (no undo)
![image](https://user-images.githubusercontent.com/979361/211185836-4482adc2-4c72-4c53-8b49-927b3104b8eb.png)

I was expecting by selecting the  option to remove content , Godot would only delete the content of the "test01-player" subfolder, but all files in F:\GODOT4-tests are deleted and the folder F:\GODOT4-tests itself also.

Please change this so only the subfolder with the project you want to delete is removed.

Thanks,

Eddy

### Steps to reproduce

Create a specific test folder:
fi. F:\GODOT4-tests

In there create several test projects like:
F:\GODOT4-tests\test01-player
F:\GODOT4-tests\test02-FPS
F:\GODOT4-tests\test03-CS

Go to project list
Select "test01-player" from the list above and press the "Remove" project button, you will get a dialog asking if I really want to delete the project? (no undo)
![image](https://user-images.githubusercontent.com/979361/211185836-4482adc2-4c72-4c53-8b49-927b3104b8eb.png)

All files in F:\GODOT4-tests are deleted and the folder F:\GODOT4-tests itself also.

### Minimal reproduction project

N/A

**Comment by EddyAlleman** [comment]
It seems safer to me to remove the option
"also delete project contents (no undo)"
and give a short hint to delete it using a file explorer if you want to tidy up things.

**Comment by MarioLiebisch** [comment]
Huh, you scared me for a tiny moment. I used the very same function just an hour ago with a fresh build from scratch (`master` on `fcba87e696d58912838d8a4a6987b10efa28e78f`); in my case all other projects are still there, though.

Didn't test further, but in case it makes a difference: I launched Godot from the build folder with Godot's source folder being the working directory.

**Comment by gotnospirit** [comment]
Wasn't able to reproduce on Windows 10 with Godot_v4.0-beta10_win64 (Local drive D: NTFS)

**Comment by EddyAlleman** [comment]
I forgot to mention it was the mono version I used.

**Comment by Zireael07** [comment]
I am not well versed in the mono version. Copying the godot project file shouldn't have an effect but I wonder why you'd even need to, the file is auto-generated when you create a project...

**Comment by gotnospirit** [comment]
Just tested with your method (folder copy) and still wasn't able to reproduce (even when the copy is not imported yet).
If I don't edit the `project.godot` file of the copy, I just end with two projects with the same name, but when I delete one, the other is still there.

It's either a problem with the mono version or the filesystem of your F: drive

**Comment by EddyAlleman** [comment]
My F: drive is an extra disk (NTFS)
Thanks all for testing!

**Comment by gotnospirit** [comment]
I use a partitioned physical drive but I don't think an extra one would be a problem in this case.
Can you try with the standard build (Godot_v4.0-beta10_win64) and, if it still happens, with the latest stable (3.5.1)?

**Comment by MarioLiebisch** [comment]
Partitions etc. shouldn't have any impact as that's abstracted away from regular programs.

Any chance you used soft-/hardlinks when setting up the whole structure and that's something that screwed you over some odd way?

Did you just open the editor to remove the projects or did you go back to the menu first?

And any chance you accidentally had the deleted project right inside `F:\GODOT4-tests` without a sub folder, so it removed everything?

**Comment by EddyAlleman** [comment]
I did another test and I cannot reproduce the above described problem myself. I don't know what happened, but I will never touch that option "also delete project content" in the future ;-)

Project with a player (C#), 3Denvironment and imported glb file
Projects in F:\GODOT4-tests :
     test-CS

copy using windows explorer in F:\GODOT4-tests:
test-CS-Copy
	Edit project.godot file and rename in the line :
	config/name="test-CS" to "test-CS-Copy"

Open test-CS in godot
	Edit player script -> opens Visual studio 2022 (the cs file is in the correct subfolder)
	Add debug.print + rebuild
	Test the scene : player code works fine
	Close the project and go back to project manager

Open test-CS-Copy in godot
	Edit player script -> opens Visual studio 2022  (the cs file is in the correct subfolder)
	Add debug.print + rebuild
	Test the scene : player code works fine
	Close the project and go back to project manager

In project manager : delete the test-CS-Copy project

In windows explorer: the test-CS-Copy is deleted, but test-CS is still there.

**Comment by EddyAlleman** [comment]
@MarioLiebisch
Any chance you used soft-/hardlinks when setting up the whole structure and that's something that screwed you over some odd way?
No I didn't use links

Did you just open the editor to remove the projects or did you go back to the menu first?
I used "Quit to project list" and deleted there

And any chance you accidentally had the deleted project right inside F:\GODOT4-tests without a sub folder, so it removed everything?
No, I'm sure about that: every project had it's own subfolder in F:\GODOT4-tests. I'm keen on separating things as much as possible.

**Comment by EddyAlleman** [comment]
I tested again several times and cannot reproduce it. Therefore I will close this
