### ISSUE TITLE
YSort not working with polygon2D

### ISSUE THREAD

**Issue by puppetmaster-** [godotengine/godot#7105]
**Operating system or device - Godot version:**
Windows 7 64bit
Godot Version 2.1

**Issue description** (what happened, and what was expected):
YSort don't sort polygon2D.

**Steps to reproduce:**
Add a YSort node
Add two polygon2d node
change Y position

![ysort_bug](https://cloud.githubusercontent.com/assets/10463138/20240853/906a38cc-a923-11e6-8851-8bb128275269.gif)

**Link to minimal example project** (optional but very welcome):

**Comment by volzhs** [comment]
I think it's because of pivot point.
move pivot point to center of polygon2d.
![poly2d](https://cloud.githubusercontent.com/assets/8281454/20243701/7acae4f2-a9a6-11e6-8b6d-61ea989ec23c.gif)

**Comment by puppetmaster-** [comment]
Thx @volzhs ,  yes it was the pivot point. :)
