### ISSUE TITLE
SceneTreeTween fails to perform implicit parameter conversion on Variant parameters

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#71058]
### Godot version

3.5.1 stable

### System information

Linux

### Issue description

Refer to my code example, but details below:

the signature for Tween node interpolate_property  is:
`interpolate_property(object: Object, property: NodePath, initial_val: Variant, final_val: Variant, duration: float)`
	
the signature for SceneTreeNode tween_property is:
`tween_property(object: Object, property: NodePath, final_val: Variant, duration: float)`

so passing in the same value to both final_val should work, however if you have a property that takes a float but pass in an int, then scene tree tween version fails with the following whereas Tween node works:

> E 0:00:00.428   tween_property: Type mismatch between property and final value: float and int
>   <C++ Error>   Condition "property_type != p_to.get_type()" is true. Returned: Ref<PropertyTweener>()
>   <C++ Source>  scene/animation/scene_tree_tween.cpp:70 @ tween_property()
>   <Stack Trace> RichTextLabel2.gd:22 @ _ready()

You would expect the same behaviour, that the final_var/variant should be performing implicit int>float conversion (or if GDScript does not do this then the code behind tween_property is not doing something that Tween node does to compensate.

This is exaggerated when as per my code margin_top appears to be an integer value in the ui (floats are not allowed to be set for the slider) and margin_top accepts integers in code except via SceneTreeNode

In fact I don't think it is a int>float issue at all because the parameter is a Variant and in the below code you can see it is performing a int>float cast for the duration

### Steps to reproduce

Use the sample project included below. But here is the code:

```
extends Node2D

func _ready() -> void:
	var my_margin_defo_an_int:int = 50
	
	#setting margin_top with an int
	#the UI suggests it's an int because you cannot enter float values
	$ButtonTween.margin_top = my_margin_defo_an_int
	$ButtonObjOK.margin_top = my_margin_defo_an_int
	$ButtonObjErr.margin_top = my_margin_defo_an_int
	
	#all parameters very happy with integers and doing presumably implicit int > float conversion
	$Tween.interpolate_property($ButtonTween, "margin_top", 50, 100, 3, Tween.TRANS_LINEAR, Tween.EASE_IN_OUT)
	$Tween.start()
	
	#this produces an error despite passing the same value to what you believe is an int as above
	var tw2 = create_tween()
	tw2.tween_property($ButtonObjErr, "margin_top", 100, 3)
	
	#tween requires you to force a float cast to work
	var tw1 = create_tween()
	tw1.tween_property($ButtonObjOK, "margin_top", float(100), 3)
	
	
	#the signature for interpolate is:
	#	bool interpolate_property(object: Object, property: NodePath, initial_val: Variant, final_val: Variant, duration: float, trans_type: TransitionType = 0, ease_type: EaseType = 2, delay: float = 0)
	
	#the signature for tween is:
	#	tween_property(object: Object, property: NodePath, final_val: Variant, duration: float)

	#so both should work as they take a Variant for final value

```

### Minimal reproduction project

[tween_error.zip](https://github.com/godotengine/godot/files/10368364/tween_error.zip)

**Comment by timothyqiu** [comment]
Fixed by #65072

**Comment by chucklepie** [comment]
Thanks @timothyqiu  :)

Can I be cheeky and ask this, I keep getting this error, there is no context given, no mention of where it came from, what started it. I've literally had breakpoints on every creation and every tween works, but this just pops up randomly. Is it a variant of the infamous yield error where something goes out of scope but the yield has just returned and it doesn't exist anymore? 

E 0:02:13.824   step: SceneTreeTween started, but has no Tweeners.
  <C++ Error>   Condition "tweeners.empty()" is true. Returned: false
  <C++ Source>  scene/animation/scene_tree_tween.cpp:263 @ step()


I've seen other people mention it too with no answers. i.e. is it a benign thing that shouldn't really be an error?

**Comment by timothyqiu** [comment]
It means that you created a SceneTreeTween, but did not call its `tween_*` methods in the same frame.

**Comment by chucklepie** [comment]
Thanks. In the code below I originally had the create_tween before the first if so if it never went in it never ran. So you get an error just for that, it's just an object that was never used? Does this also mean that you cannot create a persistent class level scene tree tween (I use one in my audio manager to stop a fade tween when required)....

```
	if enable_flag and !immediate:
			$ViewportContainer.margin_top=viewport_top/2.0
			var tw = create_tween()
			var pt = tw.tween_property($ViewportContainer,"margin_top",100.0,0.5)
	elif !immediate:
			$ViewportContainer.margin_top=viewport_top
			var tw = create_tween()
			tw.tween_property($ViewportContainer,"margin_top",viewport_top/2.0,0.5)

```
