### ISSUE TITLE
Autocomplete works only from the beginning of the property/method name

### ISSUE THREAD

**Issue by DarkMessiah** [godotengine/godot#71059]
### Godot version

v4.0.beta10

### System information

Windows 10

### Issue description

Autocomplete doesn't work if you type anything other than the first word.

For example, in GraphNode, if you type `close` you see only `close_request` (autocomplete doesn't show `show_close`)

https://user-images.githubusercontent.com/1756388/211195095-1bdec9c7-d6c3-4847-840f-ec5444d57ea6.mp4

### Steps to reproduce

1) Create `GraphNode` class
2) Type `close`
3) Try to find the `show_close` property

### Minimal reproduction project

[autocompletion_bug.zip](https://github.com/godotengine/godot/files/10368367/autocompletion_bug.zip)

**Comment by akien-mga** [comment]
Might be worth checking against #65655 (cc @Mickeon).

**Comment by HolonProduction** [comment]
Seems fixed on `master`

![Image](https://github.com/godotengine/godot/assets/99511741/c41ebe4d-8369-4e51-9c3c-b47b120fd73c)


![Image](https://github.com/godotengine/godot/assets/99511741/3fd7b566-8388-48ea-be96-4928a324c643)
