### ISSUE TITLE
Can not change IME on Ubuntu 16.04

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#7106]
**Operating system or device - Godot version:**
Ubuntu 16.04, master head (c93c2a6be8ad0abbfd5cae4831ff2ce2200ae6f6)

**Issue description** (what happened, and what was expected):
I got error when run editor or game.
```
Error setting locale modifiers
```
comes from https://github.com/godotengine/godot/blob/master/platform/x11/os_x11.cpp#L118-L121

**Comment by reduz** [comment]
I've seen this before, but don' t have the slightest clue why it happens
for some people

**Comment by volzhs** [comment]
I just read #5158, and I tried to run with `sudo ./godot.tool.64`.
I got no error, though can't change locale.

**Comment by bojidar-bg** [comment]
@volzhs What about running it with an absolute path to the binary?

**Comment by volzhs** [comment]
@bojidar-bg it's same. I have this problem with Krita(.appimage) too.
and blender(steam version) shows square.

**Comment by bojidar-bg** [comment]
@volzhs Hm, that's strange, I can't confirm it on my arch linux when running it from `$PATH`... Maybe some installation weirdness?

**Comment by volzhs** [comment]
maybe. I've tried several ways to configure IME, but not good so far. :(

**Comment by akien-mga** [comment]
As discussed on IRC with @hpvb, the issue might be due to some locales that do not allow *not* to have an input method defined, so our call to `XSetLocaleModifiers ("@im=none");` fails. That would explain #5158 which we worked around by printing the error @volzhs mentioned above.
See https://www.x.org/archive/X11R6.8.0/doc/XSetLocaleModifiers.3.html for the X11 documentation about `XSetLocaleModifiers`.

So a potential solution would be to find the X11 calls that can list the valid `im` modifier values, and define the proper one instead of forcing `none`.

**Comment by Tugsav** [comment]
I seem to get this issue as well on Ubuntu 16.04. (godot 2.1.2-stable)
After some tinkering i have found that setting the XMODIFIERS environment var to an empty string using
export XMODIFIERS=""
in the terminal before starting godot solves it for me.

**Comment by akien-mga** [comment]
What's your usual XMODIFIERS env var when not overridden?

**Comment by Tugsav** [comment]
"@im"

**Comment by Tugsav** [comment]
[update]
It seems that XMODIFIERS can also be set to
"@im="
or any string of the form "@im=[something]" such as
"@im=ibus" or even "@im=blabla123"
and godot will not get the warning

**Comment by volzhs** [comment]
in my test, `export XMODIFIERS=""` or `"@im="` makes no warning but still can't change IME.

**Comment by akien-mga** [comment]
I think having proper IME support will likely be more complex than just fixing the parsing of XMODIFIERS. But that's a first step.

**Comment by volzhs** [comment]
it's fixed by 41029eb.
now I can type Korean in script editor. :+1:

**Comment by volzhs** [comment]
I wish 2.1.x has this fix too. :smile:
