### ISSUE TITLE
Multiple editor crashes on fedora 37 / godot 4 beta 10 - mono build

### ISSUE THREAD

**Issue by ZwieBit** [godotengine/godot#71063]
### Godot version

4.0 Beta 10 Mono

### System information

Fedora 37, Intel i5-11300h, IGPU

### Issue description

While running a project from within the editor, the editor crashes quit often without any output to console (5/6 times a day).

### Steps to reproduce

Just open the editor and after 10-20 starts it just closes but the game keeps running. Example coredmp is provided.

[coredmp.txt](https://github.com/godotengine/godot/files/10368439/coredmp.txt)

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Can you reproduce this with a non-Mono build, or on a blank project?

**Comment by ZwieBit** [comment]
@Calinou Well, after lots of days of crashing i don't experience them anymore. Maybe because i upgraded to Beta 11? Guess the ticket can be closed for now.
