### ISSUE TITLE
Godot4 Array find() method works incorrectly with PackedVector2Arrays

### ISSUE THREAD

**Issue by jarmush** [godotengine/godot#71073]
### Godot version

v4.0.beta10.official [d0398f62f]

### System information

OS independent

### Issue description

It doesn't care about vectors in PackedVector2Array, it counts only array size.
Code example below is self-explaining. Any PackedVector2Array may be given as argument to Array.find() method, it will return an index of any PackedVector2Array with same PackedVector2Array.size()

### Steps to reproduce

Minimal reproduction example of code:
```
	var testarray := []
	testarray.append(PackedVector2Array([Vector2(10,10), Vector2(10,20), Vector2(20,20), Vector2(20,10)]))
	print(testarray.find(PackedVector2Array([Vector2(1,1), Vector2(1,2), Vector2(2,2), Vector2(2,1)])))
#outputs 0 (expected output -1)

```

```
	var testarray2 := []
	testarray2.append(PackedVector2Array([Vector2(10,20), Vector2(20,20), Vector2(20,10)]))
	testarray2.append(PackedVector2Array([Vector2(10,10), Vector2(10,20), Vector2(20,20), Vector2(20,10)]))
	print(testarray2.find(PackedVector2Array([Vector2(100,1), Vector2(1,200), Vector2(2,2), Vector2(2,111)])))
#outputs 1 (expected output -1)
```

### Minimal reproduction project

[array find test.zip](https://github.com/godotengine/godot/files/10368857/array.find.test.zip)

**Comment by AThousandShips** [comment]
Seems to possibly be due to a parentheses issue in Variant, will test when I can
