### ISSUE TITLE
[Shading] There seems to be a rounding issue with uniform colors picked from wheel when comparing them

### ISSUE THREAD

**Issue by thornySoap** [godotengine/godot#71079]
### Godot version

4.0 beta 10

### System information

Debian GNU/Linux 11

### Issue description

After restarting the editor the comparison between a uniform color and a color from `(in my case) texture(SCREEN_TEXTURE, SCREEN_UV)` doesn't work. 
This doesn't occur if the color is something like 00ff00, only if it's something like a3ea86 (Rounding issue?). And, it gets fixed when clicking the color in shader parameters in the inspector.

#### (Reproduction project)
`TextureModifier` is supposed to replace the color of `Texture` with pure red, but when opening up the project this isn't the case first. You have to open up the shader parameters of the material of `TextureModifier` and click on the color once and escape. Only then you will see the color changed to red. Without doing this it won't even work when running the project.

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/10368990/test.zip)

**Comment by Calinou** [comment]
This is likely floating-point precision error. You need to use approximate comparisons using an epsilon value: `if (x < value - 0.001 && x < value + 0.001)`.

**Comment by thornySoap** [comment]
> You need to use approximate comparisons using an epsilon value: if (x > value - 0.001 && x < value + 0.001).

But isn't it still weird behaviour to be forced to do something like that even though I am just comparing two colors with the same hex-value?

**Comment by thornySoap** [comment]
That would be absolutely possible to do indeed, but instead of
```glsl
colorA == colorB  // a3ea86 == a3ea86
```

it would be
```glsl
colorA.r > colorB.r - 0.001 && colorA.r < colorB.r + 0.001
&& colorA.g > colorB.g - 0.001 && colorA.g < colorB.g + 0.001
&& colorA.b > colorB.b - 0.001 && colorA.b < colorB.b + 0.001
&& colorA.a > colorB.a - 0.001 && colorA.a < colorB.a + 0.001
```

which seems a little bit weird to me

**Comment by thornySoap** [comment]
But why does this even happen at all? This is the scene file of the test project: the colors are defined the same, aren't they?

```
[gd_scene load_steps=3 format=3 uid="uid://tybcxgtxjc31"]

[ext_resource type="Shader" path="res://test.gdshader" id="1_ayupo"]

[sub_resource type="ShaderMaterial" id="ShaderMaterial_o4ahs"]
shader = ExtResource("1_ayupo")
shader_parameter/replaceColor = Color(0.639216, 0.917647, 0.52549, 1)

[node name="Node2D" type="Node"]

[node name="Texture" type="ColorRect" parent="."]
editor_description = "Just a simple Rect doing nothing"
offset_right = 440.0
offset_bottom = 163.0
color = Color(0.639216, 0.917647, 0.52549, 1)

[node name="TextureModifier" type="ColorRect" parent="."]
material = SubResource("ShaderMaterial_o4ahs")
anchors_preset = 15
anchor_right = 1.0
anchor_bottom = 1.0
grow_horizontal = 2
grow_vertical = 2

```

**Comment by Zireael07** [comment]
As @Calinou said there is such a thing as float precision error. The value you see saved has 6 digits of precision - iirc the IEEE floating point number has 13, which means they can differ in the 7th digit...

**Comment by thornySoap** [comment]
> But why does this even happen at all? This is the scene file of the test project: the colors are defined the same, aren't they?

I am just a bit confused because I am not doing calculations, but simply compare two numbers. Shouldn't it be trivial then for comparing, if either numbers' binary value get chopped off at the end?

**Comment by Zireael07** [comment]
No, because computers do not "chop off at the end", they compare the whole floating point number value regardless of what you see in the tscn file

**Comment by thornySoap** [comment]
> No, because computers do not "chop off at the end"

I'm very sorry for my cluelessness, but still: floating point precision errors only occur with calculations (if not I really have to apologize), don't they? So this cannot really be the problem. Maybe it is because of what value `texture(SCREEN_TEXTURE, SCREEN_UV)` gives? But why does it work then if I click and escape on the color in shader params without modifying anything?

**Comment by Zireael07** [comment]
No, they occur with comparisons too

**Comment by Proggle** [comment]
If you want a function that takes discrete values from 0-255 for each channel, you should try using Color8 instead of Color.  The int->float conversion should then have the same inputs and outputs.

It is a little odd that using a Color converts precise int8 values into 64-bit floats

**Comment by clayjohn** [comment]
@thornySoap the floating point guide has an entire section on the pitfalls of floating point comparison https://floating-point-gui.de/errors/comparison/ you may find it helpful

**Comment by thornySoap** [comment]
> pitfalls of floating point comparison https://floating-point-gui.de/errors/comparison/ you may find it helpful

Thank you, but still, floating point precision error doesn't occure when doing zero calculations:

> it also means that numbers expected to be equal (e.g. when calculating the same result through different correct methods) often differ slightly

But nevermind. Seems like everyone agrees that this 
> instead of
>
> colorA == colorB  // a3ea86 == a3ea86
>
> it would be
>
> colorA.r > colorB.r - 0.001 && colorA.r < colorB.r + 0.001
&& colorA.g > colorB.g - 0.001 && colorA.g < colorB.g + 0.001
&& colorA.b > colorB.b - 0.001 && colorA.b < colorB.b + 0.001
&& colorA.a > colorB.a - 0.001 && colorA.a < colorB.a + 0.001

and this 
> And, it gets fixed when clicking the color in shader parameters in the inspector.

is the right behavior and for everyone else absolutely not confusing.

**Comment by thornySoap** [comment]
> Try using Color8 (which goes 0-255 for each channel as integers instead of 0-1) instead of Color.
> 
> It is a little odd that the Color class converts precise int8 values into approximate 64-bit floats.

Sorry, didn't see your comment first. Thank you for the tip, but this is about the Godot Shading Language, so it doesn't really help right now.
