### ISSUE TITLE
Big tilesets with skewed ratio don't load correctly

### ISSUE THREAD

**Issue by rhardouin** [godotengine/godot#71086]
### Godot version

4.0.beta10.mono.official.d0398f62f

### System information

Ubuntu 22.04.1 LTS

### Issue description

It seems there is a limit in tileset size that causes a display problem or the root cause might be the unusual ratio (here 256x17024)

![Screenshot from 2023-01-08 19-56-19](https://user-images.githubusercontent.com/20056/211214358-266f8a56-0f51-4494-aacf-262fb9719240.png)

### Steps to reproduce

Choose a big tileset and/or with huge Y size compared to X

### Minimal reproduction project

I can't share the spritesheet (I bought it)

**Comment by Calinou** [comment]
The texture is larger than 16384 on one of the axes, which is bound to cause various issues (especially on low-end hardware and mobile devices once you export the project). I suggest you rearrange the spritesheet to make it wider but less tall.

**Comment by rhardouin** [comment]
Thanks @Calinou, I was about to link [a reddit comment](https://www.reddit.com/r/godot/comments/ckr7zc/maximum_texture_sprite_size/) where you mentioned the 16384 limit (and even 4096 for some devices!).

It would be useful to show a warning or even an error. It would avoid useless bug report to review ^^

**Comment by Calinou** [comment]
> Thanks @Calinou, I was about to link [a reddit comment](https://www.reddit.com/r/godot/comments/ckr7zc/maximum_texture_sprite_size/) where you mentioned the 16384 limit (and even 4096 for some devices!).

Did this fix the issue for you?

**Comment by rhardouin** [comment]
Yes it worked but based on your reddit comment I'll use even smaller spritesheets, split by theme, to cap X and Y size at 4096.
