### ISSUE TITLE
(binding: 0, index 0) is not a valid texture

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#71089]
### Godot version

v4.0.dev.20220118.official [bc5ba38ff]

### System information

linux

### Issue description

Hello, I presume Godot 4 issues are being looked at :)

I've just tried to open a 3.5.1 project (after I deleted all the cache files, fixed all OS. functions, converted Tweens, etc) and it spent 5 minutes repeating this error before it calmed down and let me in, which I presume is for every image. Is this a 'benign' error or something new/known that needs a fix?

If it helps, all my images are png wiht 2D Pixel preset with filter turned off.

neil@pop-os:/usr/share/applications$ /opt/godot/Godot_v4.0-dev.20220118_linux.64 
Godot Engine v4.0.dev.20220118.official.bc5ba38ff - https://godotengine.org
Vulkan API 1.2.0 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 950
 
Editing project: /home/neil/godot/rex/game/Rex_Godot4/game (::home::neil::godot::rex::game::Rex_Godot4::game)
Godot Engine v4.0.dev.20220118.official.bc5ba38ff - https://godotengine.org
Vulkan API 1.2.0 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 950
 

ERROR: Texture (binding: 0, index 0) is not a valid texture.
   at: uniform_set_create (drivers/vulkan/rendering_device_vulkan.cpp:5547)
ERROR: Condition "!uniform_set" is true.
   at: compute_list_bind_uniform_set (drivers/vulkan/rendering_device_vulkan.cpp:7831)
ERROR: Image (binding: 0, index 0) is not a valid texture.
   at: uniform_set_create (drivers/vulkan/rendering_device_vulkan.cpp:5654)
ERROR: Condition "!uniform_set" is true.
   at: compute_list_bind_uniform_set (drivers/vulkan/rendering_device_vulkan.cpp:7831)
ERROR: Uniforms were never supplied for set (3) at the time of drawing, which are required by the pipeline
   at: compute_list_dispatch (drivers/vulkan/rendering_device_vulkan.cpp:8030)
ERROR: Texture (binding: 0, index 0) is not a valid texture.
   at: uniform_set_create (drivers/vulkan/rendering_device_vulkan.cpp:5547)
ERROR: Condition "!uniform_set" is true.
   at: compute_list_bind_uniform_set (drivers/vulkan/rendering_device_vulkan.cpp:7831)
ERROR: Image (binding: 0, index 0) is not a valid texture.
   at: uniform_set_create (drivers/vulkan/rendering_device_vulkan.cpp:5654)
ERROR: Condition "!uniform_set" is true.
   at: compute_list_bind_uniform_set (drivers/vulkan/rendering_device_vulkan.cpp:7831)
ERROR: Uniforms were never supplied for set (3) at the time of drawing, which are required by the pipeline
   at: compute_list_dispatch (drivers/vulkan/rendering_device_vulkan.cpp:8030)
ERROR: Texture (binding: 0, index 0) is not a valid texture.
   at: uniform_set_create (drivers/vulkan/rendering_device_vulkan.cpp:5547)
ERROR: Condition "!uniform_set" is true.
   at: compute_list_bind_uniform_set (drivers/vulkan/rendering_device_vulkan.cpp:7831)

### Steps to reproduce

open and wait

### Minimal reproduction project

n/a

**Comment by chucklepie** [comment]
btw, I dunno if this helps, but on starting godot 4 all I got was the option to convert my .project file and nothing in the project was converted. All the videos I've seen show you are prompted by Godot to convert just your project or convert everything?

**Comment by chucklepie** [comment]
I also got not image errors as above in beta 9, so only in this pre-alpha. I presumed prealpha was later and more stable than beta 9?

**Comment by akien-mga** [comment]
"pre" means "before". So pre-alpha predates alpha1, and then date in the binary name confirms it. You were testing a one year old dev build (2022, Jan 18).

**Comment by chucklepie** [comment]
Yeah, it was pointed out to me, hence I closed the ticket going nobody
noticed 😉

In my defence all the other items were chronological and I just saw the
word  'jan' 😁
