### ISSUE TITLE
Unicode error in about editor page

### ISSUE THREAD

**Issue by fire** [godotengine/godot#71094]
### Godot version

4.0 near master https://github.com/godotengine/godot/commit/bb08997b8725780670be30afa96354e7c38586fd

### System information

Windows 11, Nvidia 3000

### Issue description

Unicode error near the copyright.

![image](https://user-images.githubusercontent.com/32321/211232651-34733ac2-3013-4516-92d8-3aece604c607.png)

### Steps to reproduce

Go to the about godot screen.

### Minimal reproduction project

Create a new godot engine project from the project manager.

**Comment by raulsntos** [comment]
Fixed by https://github.com/godotengine/godot/pull/71068
