### ISSUE TITLE
GDExtensions are not exported correctly: No suitable library found for GDExtension: res://webrtc/webrtc.gdextension

### ISSUE THREAD

**Issue by JonathanPicques** [godotengine/godot#71090]
### Godot version

4.0.beta10 mono and standard

### System information

Windows 10 64bits

### Issue description

When exporting a project, Godot fails to bundle the required DLLs from the GDExtension to the export folder:

```
editor/export/editor_export_plugin.h:123 - Required virtual method EditorExportPlugin::_get_name must be overridden before calling.
  No suitable library found for GDExtension: res://webrtc/webrtc.gdextension. Possible feature flags for your platform: pc, s3tc, windows, x86_64, template, template_debug
```

### Steps to reproduce

Export for Windows with the existing configuration: WebRTC DLLs won't be copied in the export folder

### Minimal reproduction project

[Repro.zip](https://github.com/godotengine/godot/files/10368987/Repro.zip)

**Comment by hakuhan** [comment]
I got this bug once. And I deleted all dll's and build again. Seems fixed.:)

**Comment by Faless** [comment]
> `Possible feature flags for your platform: pc, s3tc, windows, x86_64, template, template_debug`

I don't see the generic `debug` flag, was it removed from the default features? (CC @groud I remember this was discussed at some point for the "auto" prefix PR)

**Comment by groud** [comment]
I believe it was fixed in: https://github.com/godotengine/godot/pull/69805
