### ISSUE TITLE
CanvasLayer textures are different in editor and in game.

### ISSUE THREAD

**Issue by danskiyq** [godotengine/godot#71100]
### Godot version

4.0 dev Beta 10

### System information

MacBook Pro M1 Max

### Issue description

Textures placed insde the new CanvasLayer are mismatched with their actual placement on the screen.
Here are some pictures of how it looks https://imgur.com/a/YTvrmRO.

### Steps to reproduce

1. Create new 2D Scene.
2. Create objects that are tracked with Camera2D for scrolling
3. Create new CanvasLayer as a child of a scene
4. add objects to the CanvasLayer
5. run the game and compare difference.

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
CanvasLayer layout is based on absolute coordinates, not camera's. You probably confused camera's rectangle with the viewport one.
![image](https://user-images.githubusercontent.com/2223172/211329703-acbde7cc-d9f5-46e4-afc5-5b6f2e72420f.png)
Put your nodes in relation to the blue lines and it will appear correctly.

**Comment by danskiyq** [comment]
@KoBeWi yes, you are right but it isn't really intuitive, why I can't resize the CanvasLayer then? or can I?

**Comment by danskiyq** [comment]
and it also acts weirdly on screen resize, I thought that CanvasLayer always stays in the same position, isn't it? here's an example https://imgur.com/a/JJkjGH3

**Comment by KoBeWi** [comment]
You can't resize it, but it will automatically adjust to camera's zoom, i.e. your camera zoom will not affect the size of elements in CanvasLayer.

**Comment by danskiyq** [comment]
Closing as it's not a bug but I misunderstood the worklfow, as a note I'd say that CanvasLayer isn't really intuitive.
