### ISSUE TITLE
UI is not rendered on Intel UHD 630. Latest driver.

### ISSUE THREAD

**Issue by kragil** [godotengine/godot#71104]
### Godot version

4.0 dev beta 10

### System information

Windows 10, Vulkan (I guess) UHD 630 23.20.16.4974

### Issue description

I can't use Godot 4 at all. The UI is all black.

### Steps to reproduce

Start Godot.

### Minimal reproduction project

Any project will do.

**Comment by kragil** [comment]
Godot Engine v4.0.beta10.official.d0398f62f - https://godotengine.org
vkEnumerateInstanceVersion not available, assuming Vulkan 1.0.
Vulkan API 1.0.66 - Using Vulkan Device #0: Intel - Intel(R) UHD Graphics 630

WARNING: Nodes with non-equal opposite anchors will have their size overridden after _ready().
If you want to set size, change the anchors or consider using set_deferred().
     at: _set_size (scene/gui/control.cpp:1379)
WARNING: Nodes with non-equal opposite anchors will have their size overridden after _ready().
If you want to set size, change the anchors or consider using set_deferred().
     at: _set_size (scene/gui/control.cpp:1379)
WARNING: Nodes with non-equal opposite anchors will have their size overridden after _ready().
If you want to set size, change the anchors or consider using set_deferred().
     at: _set_size (scene/gui/control.cpp:1379)
WARNING: Nodes with non-equal opposite anchors will have their size overridden after _ready().
If you want to set size, change the anchors or consider using set_deferred().
     at: _set_size (scene/gui/control.cpp:1379)
WARNING: Nodes with non-equal opposite anchors will have their size overridden after _ready().
If you want to set size, change the anchors or consider using set_deferred().
     at: _set_size (scene/gui/control.cpp:1379)
WARNING: Nodes with non-equal opposite anchors will have their size overridden after _ready().
If you want to set size, change the anchors or consider using set_deferred().
     at: _set_size (scene/gui/control.cpp:1379)
WARNING: Nodes with non-equal opposite anchors will have their size overridden after _ready().
If you want to set size, change the anchors or consider using set_deferred().
     at: _set_size (scene/gui/control.cpp:1379)
WARNING: Nodes with non-equal opposite anchors will have their size overridden after _ready().
If you want to set size, change the anchors or consider using set_deferred().
     at: _set_size (scene/gui/control.cpp:1379)
WARNING: Nodes with non-equal opposite anchors will have their size overridden after _ready().
If you want to set size, change the anchors or consider using set_deferred().
     at: _set_size (scene/gui/control.cpp:1379)
WARNING: Nodes with non-equal opposite anchors will have their size overridden after _ready().
If you want to set size, change the anchors or consider using set_deferred().
     at: _set_size (scene/gui/control.cpp:1379)
WARNING: Nodes with non-equal opposite anchors will have their size overridden after _ready().
If you want to set size, change the anchors or consider using set_deferred().
     at: _set_size (scene/gui/control.cpp:1379)

**Comment by clayjohn** [comment]
It looks like your device only supports Vulkan 1.0. @BastiaanOlij has a PR in the works that should help on Vulkan 1.0 devices (or at least print an instructive error on devices that don't support Vulkan well enough) https://github.com/godotengine/godot/pull/70429 It should be ready in the coming days

**Comment by kragil** [comment]
Cool, thanks for the great work everybody is doing. Godot will be a big success like Blender or the Linux Kernel.

**Comment by kragil** [comment]
Hmm, I just checked and the UHD 630 can do Vulkan 1.2. I did a Windows driver update dance, and it now works with Beta10 and Beta11, but it wasn't working in this Acer machine with all automatic updates from Intel, Acer, and Microsoft....

**Comment by Zireael07** [comment]
Sometimes OEM updates are not actually up to date, and the automatic updates function can also be faulty.

**Comment by Calinou** [comment]
Closing, as this is resolved by a graphics driver update.
