### ISSUE TITLE
Cancelling node selection with Escape breaks shape editing undo

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#71113]
### Godot version

4.0 964fc6e

### System information

Windows 10 x64

### Issue description

Tested with CollisionShape nodes. When you start dragging a shape, but press Escape without releasing the mouse button, the node gets deselected and the new size gets applied. You can't undo this action:
![godot windows editor dev x86_64_iWtSiN8yMa](https://user-images.githubusercontent.com/2223172/211327911-8391173d-b5eb-4e82-bb8f-378a0bd2b695.gif)
In case of 2D shapes it's worse, because when you click the node afterwards, it will stick to cursor until you click again:
![godot windows editor dev x86_64_NMzIledZwf](https://user-images.githubusercontent.com/2223172/211328055-1a5f8abe-ba0d-448a-8cda-edd0e3f09fa9.gif)

### Steps to reproduce

1. Add a CollisionShape (2D or 3D)
2. Add any editable shape
3. Drag shape's handle to change it size
4. Without releasing mouse button, press Escape

### Minimal reproduction project

N/A

**Comment by EricEzaM** [comment]
I assume this is the desired behaviour?
* Escape Pressed
* Revert to previous value, no commit made to undo/redo.

Interestingly moving nodes in the editor does not work like this. Pressing escape while drag-moving a node does nothing.

https://user-images.githubusercontent.com/41730826/211537227-b2fce170-2e9e-4c4c-a8c9-38130a095d48.mp4
