### ISSUE TITLE
"Make Floating" option is missing

### ISSUE THREAD

**Issue by iconberg** [godotengine/godot#71126]
### Godot version

v4.0.beta10.official [d0398f62f]

### System information

linux mint Vulkan API 1.3.194 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1660 Ti, Vulkan API 1.3.194 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1660 Ti

### Issue description

"Make Floating" option is not shown/available:
![grafik](https://user-images.githubusercontent.com/8441455/211378689-fe68bd95-fd3f-4a8b-8a1e-3e3114978f8d.png)

Should be:
![grafik](https://user-images.githubusercontent.com/8441455/211378601-05f3cce3-6a46-4caf-b6a0-7b2e386e2d07.png)

### Steps to reproduce

Have no other monitors to test if its an old 17" issue,
here are the specs from system info:

Graphics:  Device-1: NVIDIA TU116 [GeForce GTX 1660 Ti] driver: nvidia v: 510.108.03 
           bus ID: 01:00.0 chip ID: 10de:2182 
           Display: x11 server: X.Org 1.20.13 driver: nvidia 
           unloaded: fbdev,modesetting,nouveau,vesa resolution: **1280x1024~60Hz**, **1920x1080~60Hz** 
           OpenGL: renderer: NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2 v: 4.6.0 NVIDIA 510.108.03 
           direct render: Yes 

### Minimal reproduction project

happens for all projects

**Comment by DmitriySalnikov** [comment]
Do you mean the button from this PR #62378? It turns out that this is not yet included to the master branch.

**Comment by iconberg** [comment]
I saw this video where shows it in 4.0beta so i guessed it should be in the v4.0.beta10.official, it is not?

https://www.youtube.com/watch?v=hwB8BHPGnGM

**Comment by DmitriySalnikov** [comment]
No, these changes have not yet been merged at the moment.
I do not know when these changes will be accepted and merged.

**Comment by clayjohn** [comment]
Beta releases only include changes from merged PRs. Since https://github.com/godotengine/godot/pull/62378 hasn't been merged yet, the changes in it won't be in any betas yet. 

In the video you linked the creator has a big disclaimer saying they are using a custom build of the engine. If you want to test https://github.com/godotengine/godot/pull/62378 you will also have to make a custom build

**Comment by akien-mga** [comment]
For the record, this feature will be merged, but for 4.1. We're not adding any big new feature to 4.0 at this stage.

**Comment by bdcrisco** [comment]
Any news on this? I'm using Godot v4.2.1 and the "Make Floating" button is still missing
