### ISSUE TITLE
Properties/setget do not offer clickable links

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#71125]
### Godot version

4.0 beta 10

### System information

Linux

### Issue description

When you set a property to point to a function it should offer a clickable link to the function. I know you can create anonymous/inline methods but distinguishing the two should be easy enough...

![image](https://user-images.githubusercontent.com/12863685/211377897-95048c3c-c582-4bb9-aa1b-1540fe717412.png)

### Steps to reproduce

Create a setter/getter and try to use it to get there

### Minimal reproduction project

n/a

**Comment by bluematt** [comment]
This appears to work as expected (Godot 4.2.stable, MacOS 13.6.1 [Ventura]).

**Comment by akien-mga** [comment]
Tested too, I can reproduce the bug in 4.0-stable, it was fixed in 4.1-stable.
