### ISSUE TITLE
Various Keyboard Shortcuts from Godot 3 are not present in Godot 4

### ISSUE THREAD

**Issue by Braveo** [godotengine/godot#71135]
### Godot version

4.0.beta10.mono

### System information

Windows 10, Forward+, RTX 3060 TI

### Issue description

Various shortcuts used in Godot 3.5 do not work. Overall, the UI does feel a bit inconsistent, but here's a few I'll list:

1. Alt+Left (or Alt+Collapsing) a node doesn't collapse all nodes inside the selected node
2. Alt+Right (or Alt+Expanding) a node doesn't expand all nodes inside the selected node

https://user-images.githubusercontent.com/23423003/211430344-cb480bfb-661b-4376-ae52-fcefb02abb43.mp4

3. Selections while moving up and down are inconsistent. 

https://user-images.githubusercontent.com/23423003/211430671-0e9d1ae3-6634-4b83-8b96-ba7b95d97182.mp4

https://user-images.githubusercontent.com/23423003/211430908-9f293bac-207c-4807-a483-d6c2a7b8cdf3.mp4

4. Pressing Enter on inconsistently selected nodes return an inconsistent rename prompt.

https://user-images.githubusercontent.com/23423003/211431773-0fcc5354-7ab7-4e7d-adb6-48d09a9a1eea.mp4

5. Using backspace and hitting enter to return zero values in inspector don't work. Not sure if intentional or not.

https://user-images.githubusercontent.com/23423003/211431021-148d4c1a-1cbf-4f99-a792-06ce3e3d4bca.mp4

6. Hitting tab while going through fields works, but sometimes, fields end up being locked, preventing me from moving to the next field. (I'm spamming tab as soon as I hit the scale Z value):

https://user-images.githubusercontent.com/23423003/211431276-b853cee3-fa3a-43d8-9ef8-aee5ec51c33f.mp4

7. Hitting ESC while having a field selected doesn't stop exiting the field edit.

https://user-images.githubusercontent.com/23423003/211431337-a906cd4a-c4d0-4a4d-a433-777b513742c6.mp4

These are just a few. Let me know if some of these are existing pull requests / issues. 

### Steps to reproduce

N/A (shown above)

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/70673.

> Hitting tab while going through fields works, but sometimes, fields end up being locked, preventing me from moving to the next field. (I'm spamming tab as soon as I hit the scale Z value):

This is already being tracked in https://github.com/godotengine/godot/issues/37723.

**Comment by KoBeWi** [comment]
> Alt+Left (or Alt+Collapsing) a node doesn't collapse all nodes inside the selected node
Alt+Right (or Alt+Expanding) a node doesn't expand all nodes inside the selected node

Alt+Collapsing/Expanding was changed to Shift+Collapsing/Expanding. Last PR modifying this part that I recall was #62666; maybe arrow shortcuts were omitted.

> Selections while moving up and down are inconsistent.

I don't see any different from 3.5 behavior.

> Pressing Enter on inconsistently selected nodes return an inconsistent rename prompt.

Can't reproduce.

![godot windows editor dev x86_64_5zeUUb9hcZ](https://user-images.githubusercontent.com/2223172/212078933-8842d3d9-c4ba-4d64-a68a-71f9c46267bc.gif)

> Using backspace and hitting enter to return zero values in inspector don't work. Not sure if intentional or not.

Same as 3.5.

> Hitting ESC while having a field selected doesn't stop exiting the field edit.

Might've been caused by #67397
