### ISSUE TITLE
Godot 4 converter adding Callable and bindings where methods, signals, etc have 'start' anywhere in their name, even comments!

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#71134]
### Godot version

4.0 beta 10

### System information

Linux

### Issue description
Godot 4 on finding the word 'start' in any part of a function, signal, even in commented out code,  is completely breaking all code by trying to wrap a callable and then switching parameters to bindings. It doesn't even have to be the function 'start()', literally anything with a sub-string of 'start'. The problem is some (but most are) are not generating errors, so you have to comb through code looking for 'callable' and replacing everything.

I have this function:
```
func start(start_text,colour, scale_index,speed:=1.0,_end_y:=96):
	pass
```

Godot 4 Changed:
```
score.start(str(shot_count*SCORE_ACCUMULATOR),GlobalMethods.get_as_colour(score_colours[i]),i)
```

to: 
```
score.start(Callable(str(shot_count*SCORE_ACCUMULATOR),GlobalMethods.get_as_colour(score_colours[i])).bind(i))
```
---

In another example:
```_set_death_start(weapon,on_floor)```

Is changed to:
```_set_death_start(Callable(weapon,on_floor))```

---
It has even gone to lengths to convert comments!
```#shake.start(Callable(main_camera,priority).bind(total_shake_time),shakes_per_second,shake_half_height)```

---
It even does signals :)
```
signal scroll_start(Callable(tl,br))
```

---
For a fuller example, I have the following declared at the top of my function:
```
var release_pattern_ships=[
	[0,			UFO,	PATTERN_G,		0,LEFTRIGHT],
	[0,			SHIP,	PATTERN_D,		0,LEFTRIGHT],
]

```

I have the following Godot 3 function:

```
func _start(release_patterns, killscreen:=false):
    pass #code commented out as irrelevant
```

It is called like this:
```

	_start(release_pattern_ships,true)
	_start(release_pattern_bouncy,true)

```

On migrating to Godot 4 it has left everything as is except it has done this to all calls, causing compile errors:

```_start(Callable(release_pattern_bouncy,true))```

---

### Steps to reproduce

As description

### Minimal reproduction project

As description

**Comment by KoBeWi** [comment]
Likely this comes from `Thread.start()` taking callable now, but the converter does not know the type.

**Comment by chucklepie** [comment]
Makes sense, but I think the regex needs a tweak before final release is
all I'm saying 😉

func MystartingFunction() is clearly not a candidate, neither are signals.

**Comment by Maran23** [comment]
This should be much better now with https://github.com/godotengine/godot/pull/75002 and https://github.com/godotengine/godot/pull/74193 merged.
Inline comments may still be converted (e.g. `func _process(delta) # start`). Otherwise this should not happen.
