### ISSUE TITLE
Baking 3D navmesh results in an empty navmesh (4.0 beta 10)

### ISSUE THREAD

**Issue by Rattel** [godotengine/godot#71158]
### Godot version

4.0 beta 10

### System information

Ubuntu 20.04

### Issue description

I tried to bake a simple planar navmesh (works before baking) to later bake it with static obstacles, but whenever I bake it either in the editor or in the game, either with obstacles or in an empty scene, it visually disappears and agents stop navigating

### Steps to reproduce

1. Create a mesh
2. Create the navmesh 
3. Bake the navmesh

### Minimal reproduction project

N/A

**Comment by Zireael07** [comment]
MRP!

Is the planar mesh an obj import? A cube mesh from editor? a CSG converted to mesh? So many variables....

**Comment by smix8** [comment]
You need to provide more detail what you are doing and what you are using or an MRP.

The baking works just fine in all recent Godot versions so it is probably either your NavigationMesh properties or your chosen source geometry mesh(es) that is causing problems.

**Comment by Rattel** [comment]
> MRP!
> 
> Is the planar mesh an obj import? A cube mesh from editor? a CSG converted to mesh? So many variables....

My original mesh was a subdivided triangulated quad which was .obj import, but I can't make the editor meshes to work either, I tried changing the size as well (my mesh was 360x360 godot units), but none work. I made a reproduction of the problem in a fresh project, but it was just a cube with its navmesh so I thought it was excessive to include.

**Comment by smix8** [comment]
I don't understand why you did not add you images from Discord to the git issue to help debug this.

![image](https://user-images.githubusercontent.com/52464204/211623442-5d9ec688-8da2-4fa9-9a77-32d26c2d00fb.png)

As said on Discord, you need to place navigation mesh source geometry nodes by default below the NavigationRegion3D as children not on top as parent node. The parsing starts at the defined root node which is the NavigationRegion3D by default. If you did not change the NavigationMesh properties there is no way your node setup can work for baking. If for whatever reason you can not add your source geometry as children below the NavigationRegion3D you can change the parsing on the NavigationMesh by switching from root node children to groupname and add the groupname to whatever SceneTree node you want to parse when baking.

**Comment by Rattel** [comment]
> I don't understand why you did not add your images from Discord to the git issue to help debug this.
> 
> ![image](https://user-images.githubusercontent.com/52464204/211623442-5d9ec688-8da2-4fa9-9a77-32d26c2d00fb.png)
> 
> As said on Discord, you need to place navigation mesh source geometry nodes by default below the NavigationRegion3D as children not on top as parent node. The parsing starts at the defined root node which is the NavigationRegion3D by default. If you did not change the NavigationMesh properties there is no way your node setup can work for baking.
> 
> If for whatever reason you can not add your source geometry as children below the NavigationRegion3D you can change the parsing on the NavigationMesh by switching from root node children to groupname and add the groupname to whatever SceneTree node you want to parse when baking.

Changing the geometry settings and assigning the group to the plane mesh worked, thank you!
