### ISSUE TITLE
GDScript 2.0: Cannot use void functions as a return value

### ISSUE THREAD

**Issue by anthonyec** [godotengine/godot#71169]
### Godot version

v4.0.beta11.official [91713ced8]

### System information

macOS 13.1

### Issue description

When using a function with a return type of `void` as the return value of another function with a return type of `void`, the following error occurs: 
> Cannot get return value of call to "foo()" because it returns "void"

This wasn't a problem in Godot 3.x and Godot 4.x until now. Seems it's related to https://github.com/godotengine/godot/pull/70702. 

I understand why this is happening, but I'd expect to be able to use functions like this that return `void` because they both use the matching return type. It seems overly strict.

In a real world example I use this to return early when switching states in a FSM:

```gdscript
func _process(_delta: float) -> void:
  if player.is_grounded():
    return state_machine.transition_to("ground") # returns void

  if player.is_on_wall():
    return state_machine.transition_to("wall") # returns void
```

### Steps to reproduce

```gdscript
extends Node

func foo() -> void:
	print("hello")

func _ready() -> void:
	return foo()
```

### Minimal reproduction project

[godot_4_return_value_regression.zip](https://github.com/godotengine/godot/files/10385377/godot_4_return_value_regression.zip)

**Comment by adamscott** [comment]
`void` just means it returns nothing. It's not an actual value. So no, `state_machine.transition_to()` doesn't _actually_ returns a `void` value, they return nothing.

I suggest you to fix your code to remove the `return` statements.

**Comment by anthonyec** [comment]
> `void` just means it returns nothing. It's not an actual value. So no, `state_machine.transition_to()` doesn't _actually_ returns a `void` value, it returns nothing.
> 
> I suggest you to edit your code to return after the `transition_to()` calls.

I get that bit. It just seems a bit strict that returning nothing should fail to compile.

**Comment by adamscott** [comment]
There was a discussion on the developers' chat about the strictness of return values. It would be quite hard to ensure that the function effectively don't return anything. There's no quick way to make syntactic sugar so that `return void_func()` would mean `void_func(); return`.

Before the #70702 merge, `void` functions would return `null`. So, it was always returning a value, hence `return transition_to()` working previously.

No decision has been made to _not_ create in any way syntactic sugar to fix this issue, but it is not considered as a high-priority issue neither.

**Comment by anthonyec** [comment]
Fair enough, that makes sense about it technically being syntactical sugar. Thanks for explaining!

**Comment by dalexeev** [comment]
IMO, `return void_func()` worsens readability, `return something` looks like the function returns some value, and this is confusing, since nothing is actually returned. I would prefer two lines instead of one.

**Comment by anthonyec** [comment]
@dalexeev for me it's an aesthetic choice and what I'm used to. But yeah, I can see how the intention might be less explicit, so I'll update my opinions (and my code) ;--)

**Comment by okla** [comment]
Void functions shouldn't use `return` since they don't return anything, they should use `exit` instead :)

**Comment by vonagam** [comment]
It is quite common in typed languages to allow `return void_func()` from void functions. Like in C++ for example. So it will be a little bit unexpected for users that it is forbidden. Though I am not saying that it is definitely should be allowed.
