### ISSUE TITLE
Resource variable value with `set()` is always set as the default value

### ISSUE THREAD

**Issue by rbarongr** [godotengine/godot#71165]
### Godot version

v4.0.beta10.official [d0398f62f]

### System information

macOS 13.0.1

### Issue description

When I **create a custom Resource** with a script to (for example) store some variables values and I **write default values** with the `@export` to set the final values later for every scene that uses this custom Resource, **if the value has a set()** function to _do something_ when the value is set, **the default value first given is always the value that the variable is set to**.

For example, in the Minimum Reproduction Project:

I have created a custom Resource to store two values, one with a set() and the other without it:
```GDScript
class_name MyResource extends Resource

@export var value_a = 1
@export var value_b = 2:
	set(value):
		print("Setting a new value_b as: ", value)
```
Then I changed these values in the UI of the editor on the main scene `node_2d.tscn` with the values:
- `value_a` = 100
- `value_b` = 200

<img width="367" alt="NewValuesInEditor" src="https://user-images.githubusercontent.com/91340577/211622058-35f5ac00-52e9-488c-a13f-12525a1598d5.png">

And by printing the values in the main scene `node_2d.tscn` like this:
```GDScript
extends Node2D

@export var my_resource: MyResource

func _ready():
	print(my_resource.value_a)
	print(my_resource.value_b)
	
	my_resource.value_b = 9
	print(my_resource.value_b)
```
I get the following output:
```
--- Debugging process started ---
Godot Engine v4.0.beta10.official.d0398f62f - https://godotengine.org
Vulkan API 1.2.231 - Using Vulkan Device #0: AMD - AMD Radeon Pro 580
 
Setting a new value_b as: 200
100
2
Setting a new value_b as: 9
2
--- Debugging process stopped ---
```

So the setter gets called, but does not update the value. The `value_a` has changed, but the `value_b` has not.

### Steps to reproduce

On any project:
1. Write a custom Resource
2. Store some values in variables with a set() function
3. Try to change these values
4. The values don't change

**In the minimal reproduction project**:
1. Open the main scene `node_2d.tscn`
2. Select the root node
3. Change the values of MyResource in the UI of the editor
4. Run the main scene
5. Read the terminal to see the values

### Minimal reproduction project

[ResourceValueIssue.zip](https://github.com/godotengine/godot/files/10385177/ResourceValueIssue.zip)

**Comment by rbarongr** [comment]
Still happens in v4.0.beta11.official [91713ced8].

**Comment by Gnumaru** [comment]
I think you may have misunderstood the currently expected behavior for setters. You must set the value inside the setter

```gdscript
@export var value_b = 2:
    set(value):
        value_b = value
        print("Setting a new value_b as: ", value)
```

**Comment by rbarongr** [comment]
Thank you, @Gnumaru.

I couldn't find proper info about the new setter syntax of GDScript 2.0, so your answer helps a lot.

I assumed that the value was supposed to be automatically assigned, but you are right, maybe sometimes you need to choose if the value is assigned or not.
