### ISSUE TITLE
Godot 4: Godot.Collections.Array memory leak

### ISSUE THREAD

**Issue by cphillips83** [godotengine/godot#71163]
### Godot version

4.0.0-beta-10

### System information

Windows 11

### Issue description

Out of Memory Exception when assigning a GD Array index data.

### Steps to reproduce

1. Create blank project.
2. Add Node3D
3. Add script to node3d and use the following code
4. Watch the memory climb in your favorite process manager.

```
using Godot;
using System;

[Tool]
public partial class MemLeak : Node3D
{

    private Godot.Collections.Array _array;

    public override void _Process(double delta)
    {
        base._Process(delta);

        if (_array == null)
        {
            _array = new();
            _array.Resize((int)Mesh.ArrayType.Max);
        }

        _array[(int)Mesh.ArrayType.Vertex] = new Vector3[100000];
    }

}

```

### Minimal reproduction project

.

**Comment by stephannv** [comment]
This can be related to https://github.com/godotengine/godot/issues/71172

**Comment by raulsntos** [comment]
Likely fixed by https://github.com/godotengine/godot/pull/70494, can you try [beta11](https://godotengine.org/article/dev-snapshot-godot-4-0-beta-11)?

**Comment by cphillips83** [comment]
@raulsntos Fixed in beta11! Thanks
