### ISSUE TITLE
Dragging and dropping an audio stream to the audio player fails without any hint

### ISSUE THREAD

**Issue by L2750558108** [godotengine/godot#71161]
### Godot version

3.5.1mono

### System information

windows10

### Issue description

See this example video
[2023-01-11 00-19-26.zip](https://github.com/godotengine/godot/files/10384711/2023-01-11.00-19-26.zip)

Dragging and dropping an audio stream to the audio player fails without any hint
I understand that the drag and drop and create failure may be due to this audio resource not containing any data, but I think a hint should be given to tell the user why

### Steps to reproduce

See "Issue Description"

### Minimal reproduction project

No

**Comment by KoBeWi** [comment]
Pretty sure there's an error in the output tab.
