### ISSUE TITLE
Anchor presets not working

### ISSUE THREAD

**Issue by venilark** [godotengine/godot#71178]
### Godot version

4.0 beta 11

### System information

Windows 10

### Issue description

Anchors presets are ignored, sometimes they work if you manually modify the size of the node using the handles.

### Steps to reproduce

Simple test, open new scene, base node is Control, try to set the full rect preset, nothing happens. then just try out different stuff with different nodes and hierarchies, it barely works.

### Minimal reproduction project

.

**Comment by YuriSizov** [comment]
> Simple test, open new scene, base node is Control, try to set the full rect preset, nothing happens.

I can confirm this.

> then just try out different stuff with different nodes and hierarchies, it barely works.

I cannot confirm this.

**Comment by venilark** [comment]
Anchors of the children of the "fixed" Control don't work, but they do if the nodes are put inside of a CanvasLayer, always after modifying the size beforehand.

**Comment by YuriSizov** [comment]
What's a fixed control? Can you provide a reproduction project or at least a video?

**Comment by venilark** [comment]
[anchors.zip](https://github.com/godotengine/godot/files/10386394/anchors.zip)
by "fixed" control I meant after resizing it manually, so the anchor presets start working
this is the test project, on the control.tscn scene, if you try to set full rect for all children, nothing happens, if you do the same with the canvas_layer scene, it works, but only after resizing them at least once. 
If the project has been closed, you have to resize them again for the anchor presets to work

**Comment by YuriSizov** [comment]
@venilark When you say it doesn't work, you mean using this panel?

![image](https://user-images.githubusercontent.com/11782833/211652002-b3458840-f6be-45e3-ae38-b558e1b06d9d.png)

**Comment by venilark** [comment]
yes

**Comment by YuriSizov** [comment]
Thanks, I understand the problem now!
