### ISSUE TITLE
No index.html created with `make html` in godot/doc

### ISSUE THREAD

**Issue by romeojulietthotel** [godotengine/godot#7117]
**Operating system or device - Godot version:**
Linux 
X86_64 
github master branch
godot mainline

**Issue description** (what happened, and what was expected):
No index.html created when building html documentation
An index.html should exist according to all the links to it in the other html pages.

**Steps to reproduce:**

`cd godot/doc`
`make html`
`ls -l _build/html/index.html`
`/bin/ls: cannot access '_build/html/index.html': No such file or directory`

**Link to minimal example project** (optional but very welcome):
See above command line steps.

**Comment by akien-mga** [comment]
This is a legacy script that is not really meant to be used. If you want to build the class reference in html, it's best to use https://github.com/godotengine/godot-docs (and `make rst` in `godot/doc/` to generate the rst files that should be put in `godot-docs/classes/`).

**Comment by romeojulietthotel** [comment]
That makes sense. I was really wondering about makehtml.py and that it doesn't really work correctly. For example single_page feature also.

**Comment by romeojulietthotel** [comment]
Is it worth my time to submit a PR to remove this or will that happen as part of 3.0 anyway? Looks like base/ is still needed but not the others.

**Comment by akien-mga** [comment]
At least `doc_status.py` and `makerst.py` are still used. The ones were used for previous documentation platforms (especially when we used GitHub Wiki in Markdown). They don't hurt and still produce an output that can be of use, so no need to remove them IMO.
