### ISSUE TITLE
Parser Error: Could not resolve member "<scene>": Cyclic reference

### ISSUE THREAD

**Issue by lbowers** [godotengine/godot#71187]
### Godot version

4.0 Beta 11

### System information

Windows 11, NVidia RTX 3050

### Issue description

When attempting to reference a preloaded scene in a (nested) element, I encounter the following compiler error:

**Parser Error: could not resolve member "projectile_blaster": Cyclic reference**

(see code below)

### Steps to reproduce

_See minimal reproduction project block for code._

The PreloadedScenes.weapon_blaster line works just fine, but the PreloadedScenes.projectile_blaster line fails, even though both are preloaded scene constants. If I change this line of code:

`const projectile_blaster : PackedScene = preload("res://scenes/weapons/projectiles/blaster_bullet.tscn")`

to this:

`var projectile_blaster : PackedScene = load("res://scenes/weapons/projectiles/blaster_bullet.tscn")`

It then compiles and works as expected.

### Minimal reproduction project

```
const weapon_blaster : PackedScene = preload("res://scenes/weapons/blaster.tscn")
const projectile_blaster : PackedScene = preload("res://scenes/weapons/projectiles/blaster_bullet.tscn")

var Weapons : Array = [
	{
		"name" : "Laser",										# Weapon name
		"levels" : [
			{
				"name" : "Single Laser",						# Weapon name at level
				"reload" : 0.5,									# Reload speed (in seconds)
				"scene" : weapon_blaster,			# Weapon scene
				"projectile" : {
					"count" : 1,								# Number of projectiles spawned for a single fire of the weapon)
					"speed" : 1.0,								# Projectile speed
					"range" : 6.0,								# Projectile range (in seconds)
					"spread" : 0,								# The amount of spread between projectiles (see count)
					"damage" : 10,								# Damage inflicted on enemies
					"bloom" : 0,								# Weapon bloom (0 = 100% accurate, 100 = very innacurate)
					"homing" : false,							# Projectile homes in on the target
					"locking" : false,							# Projectile locks onto targets in range
					"scene" : projectile_blaster	# Projectile scene
				}
			}
		]
	}
```

**Comment by AThousandShips** [comment]
Can you please provide some information on what goes into the two loaded scenes, so that we can make some sense of this, and please upload a MRP, this is not an MRP

**Comment by lbowers** [comment]
Feel free to remove this issue, and I'll raise a proper ticket after a little more investigation. I think I've made some progress myself. The following code in the blaster_bulltet scene script seems to cause the issue (but only when preloaded):

	area2d.set_collision_layer_value(Constants.LAYER_PLAYER_BULLETS, true)
	area2d.set_collision_mask_value(Constants.LAYER_ENEMIES, true)
	range_area2d.set_collision_layer_value(Constants.LAYER_PLAYER_BULLETS, true)
	range_area2d.set_collision_mask_value(Constants.LAYER_ENEMIES, true)

**Comment by lbowers** [comment]
It's the use of the Constants class that's the problem. If I replace those references with integer literals, no issues.

Constants.gd is simply a autoloaded script:

```
extends Node

const LAYER_PLAYER : int = 1
const LAYER_PLAYER_BULLETS : int = 2
const LAYER_ENEMIES : int = 9

```

**Comment by lbowers** [comment]
Please feel free to close this ticket. I believe this is due to the way autoloading scripts works, and is likely not an bug. Apologies.
