### ISSUE TITLE
Camera clipping doesn't update as camera moves (ortho)

### ISSUE THREAD

**Issue by icanfathom** [godotengine/godot#71186]
### Godot version

3.5.1.stable

### System information

Windows 10, GLES3

### Issue description

I added a Spatial node as my "Pivot," then added a Camera child.

I'm using Orthogonal projection.

When I use code to move the Spatial pivot node in order to pan across the map, the Camera starts clipping things nearer than the original position. BUT when I move the camera in the editor, I don't see any clipping.

My guess: Near and Far are being calculated once on init, and never recalculated as the camera moves?

I verified that Near and Far affect the clipping I'm seeing.

Is there a better way to pan than moving the camera? Or a way to ask it to update which objects get culled by Near and Far on the fly?

In game (broken)
![image](https://user-images.githubusercontent.com/14110970/211669553-28c17bd5-ccb1-4a43-996b-4e10c332d3d2.png)

In editor (working)
![image](https://user-images.githubusercontent.com/14110970/211669593-19b3b23e-472f-4af1-af70-938acf09a3e7.png)

### Steps to reproduce

See reproduction project.

### Minimal reproduction project

[ortho camera clip.zip](https://github.com/godotengine/godot/files/10387116/ortho.camera.clip.zip)

**Comment by lawnjelly** [comment]
This seems to be some kind of misunderstanding of how cameras work, might be better to ask on discord or community channels. I'm not sure there is a bug here.
