### ISSUE TITLE
Graphics bug with GLES3 double buffered viewport when reading from UV coordinates outside of texture

### ISSUE THREAD

**Issue by SimonImming** [godotengine/godot#71184]
### Godot version

v3.5.1.stable.flathub [6fed1ffa3], v3.5.1.stable.official [6fed1ffa3]

### System information

Ubuntu 22.10 Wayland, Intel HD 620 / AMD 530

### Issue description

While following [this](https://www.youtube.com/watch?v=VSwVwIYEypY) water shader tutorial, I could only get the shader to work on GLES2. The GLES3 render always produced graphics glitches. I think the problem comes down to the shader reading values from invalid UV coordinates (see example project).

This is what it looks like: (ViewportTexture should actually be completely black)
![grafik](https://user-images.githubusercontent.com/73028447/211661916-cea5f3cd-5154-4cc4-b241-0339df97c1fd.png)

### Steps to reproduce

- Create new project with GLES3 renderer
- Add Spatial Node
- Add Viewport Node and set it to Clear Mode "Next Frame" to use double buffer
- Fill Viewport with ColorRect
- Add shader to ColorRect that reads the ViewportTexture and reads from UV coordinates outside of ViewportTexture, e.g.:
```
shader_type canvas_item;

uniform sampler2D viewport_texture;

void fragment() {
    vec3 c = texture(viewport_texture, UV).rgb;
	vec3 d = c - texture(viewport_texture, UV - vec2(1.0, 1.0)).rgb;
	COLOR = vec4(d, 1.0);
}
```
- Click on the Viewport Node to see Viewport preview
- See graphic bug (sometimes seems to require mouse movement to appear)
- Switch to GLES2 renderer
- Graphic bug should disappear

### Minimal reproduction project

[viewport_bug_gles3.zip](https://github.com/godotengine/godot/files/10386832/viewport_bug_gles3.zip)

**Comment by clayjohn** [comment]
This isn't a bug. If you want to double buffer you need two viewports. This is single buffering, you are reading from and writing to the same viewport each frame. That is not intended to work. GLES2 works by chance because the ``SCREEN_TEXTURE`` has to store a separate copy of the screen in order to work.

Since you are reading from and writing to the same texture, any particular result cannot be guaranteed. 

To do multi pass effects you should do something like what is recommended by the [custom post processing tutorial](https://docs.godotengine.org/en/stable/tutorials/shaders/custom_postprocessing.html)

**Comment by SimonImming** [comment]
Thanks a lot for the explanation! However what I intended to do / what is done in the tutorial is not processing the same frame multiple times but rather reading from the previous frame as input for the current frame (to have a basic simulation), so maybe double buffer is the wrong term for it? So in the shader I read the frame (fragment colors) to a local variable before setting the fragment color. My understanding was that by setting Clear Mode to "Next Frame", the content of the previous frame would still be available for me in the current frame, or is it not?

**Comment by clayjohn** [comment]
[CLEAR_MODE_ONLY_NEXT_FRAME](https://docs.godotengine.org/en/stable/classes/class_viewport.html#enum-viewport-clearmode) clears the viewport on the next frame and then switches to CLEAR_MODE_NEVER. It does not create a copy of the viewport for you to read on the next frame.

**Comment by SimonImming** [comment]
Ok I see… Now after reading a bit further it seems that using the SCREEN_TEXTURE would probably be the appropriate way to do such things.

**Comment by SimonImming** [comment]
I’m now just wondering, if the viewport preview is showing this glitch and is flickering when I move my mouse over other parts of the UI, could it be that the shader was able to read something from parts of the memory where it is not supposed to read? Could that be a memory safety issue that needs to be fixed on the engine side or is it my responsibility to prevent that by coding proper shaders?

**Comment by clayjohn** [comment]
> I’m now just wondering, if the viewport preview is showing this glitch and is flickering when I move my mouse over other parts of the UI, could it be that the shader was able to read something from parts of the memory where it is not supposed to read? Could that be a memory safety issue that needs to be fixed on the engine side or is it my responsibility to prevent that by coding proper shaders?

That's a good intuition. Its reading from uninitialized memory. Which means that the chunk of memory was previously used for something else, but was then marked as freed, then allocated to this texture. That means that it isn't reading from another part of the memory, so there isn't really a big security concern. However, it is your responsibility to ensure that the texture gets cleared before reading from it. Uninitialized memory can easily propogate NaN errors throughout your shader if you are reading from the texture without clearing it first.

**Comment by SimonImming** [comment]
Alright thank you very much @clayjohn for the clarification! I’ll close this issue then.
