### ISSUE TITLE
AnimationTree Oneshot animation cannot be interrupted

### ISSUE THREAD

**Issue by krazyjakee** [godotengine/godot#71195]
### Godot version

4.0 beta 11

### System information

Windows 11

### Issue description

I am trying to implement a oneshot animation that can be triggered (and retriggered) on user action. See [this issue](https://godotengine.org/qa/134456/how-to-immediately-reset-oneshot-in-animationtree) as an example. The godot 4 solution posted in that question no longer works, in fact, the oneshot animation appears to be unstoppable by any means.

### Steps to reproduce

Add an animationtree with a oneshot animation. Trigger the animation with code. Attempt to interrupt the oneshot animation in code.

I've tried...

```
animation_tree.set("parameters/FireOneshot/active", false)
animation_tree.set("parameters/FireAnimation/seek_position", 0.0)
animation_tree.set("parameters/FireOneshot/active", true)
```

```
animation_tree.set("parameters/Fire/active", false)
await get_tree().process_frame
animation_tree.set("parameters/Fire/active", true)
```

The animation continues as if no code is running at all.

### Minimal reproduction project

N/A

**Comment by adamscott** [comment]
@krazyjakee As it involves animation and needs more code than the lines shared (as we need to log the state of the animation), please join a minimal reproduction project.

**Comment by TokageItLab** [comment]
I'm working on this now as https://github.com/godotengine/godot-proposals/issues/5965.

**Comment by krazyjakee** [comment]
@TokageItLab perfect, that is it exactly, thank you.
