### ISSUE TITLE
Editor reports recursion in theme resource when setting a font twice

### ISSUE THREAD

**Issue by tanukibouwer** [godotengine/godot#71194]
### Godot version

v4.0.beta11.mono.official [91713ced8]

### System information

Arch Linux, Vulkan, GTX 1060 6GB (525.60.11)

### Issue description

If you set a font property on a theme resource to a certain font resource in the inspector, then set it to another font resource, then set it back to that first font resource again, Godot will refuse to set any font-type property in the theme to that first font.
It will report `Recursion detected, unable to assign resource to property.`. Any attempt to set a font-type property in that theme to that font resource again will fail until you restart the editor. (As far as I've seen.) 
When doing the same thing in code, this does not happen.

### Steps to reproduce

1. Open up a theme resource.
2. Set one of the theme resource's font-type properties to a certain font resource.
3. Set it to another font.
4. Set it to that first font again.
5. Godot refuses! Same thing also happens if you now try to set it to that second font again.

The MRP contains:
* A theme resource.
* Two font resources.
* A scene and script that perform these reproduction steps in code without any issue.
* A text file containing the reproduction steps.

### Minimal reproduction project

[ThemeFontBug-MRP.zip](https://github.com/godotengine/godot/files/10387530/ThemeFontBug-MRP.zip)

**Comment by akien-mga** [comment]
Likely caused by https://github.com/godotengine/godot/pull/70994 @reduz.

**Comment by reduz** [comment]
Ah yes this is my fault, will fix ASAP
