### ISSUE TITLE
iPhone Gyro and Magnetometer support

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#7119]
The current iPhone implementation only has accelerometer support and uses an approach marked as deprecated in iOS 7 if I read things correctly on the apple website.

I've made changes to the source code in my own fork and changed the code over to use CMMotionManager and also read out the gyro and magnetometer values. 

So far it just passes them on to Godot as they are with just the z flipped (the original code did so, its just a starting point). I have not yet gotten a chance to see what further adjustments are needed to make the output compatible with Android on which this already works.

I'd change this into a pull request but pretty new to contributing with GIT and I'm not sure how to isolate just these changes from other changes I've made yet. 

Anyway, could use some help finalising these changes and submitting them for further evaluation.

Fix #7127

**Comment by BastiaanOlij** [comment]
Closing this, see:
https://github.com/godotengine/godot/pull/7127
For pull requests with core motion enhancements

**Comment by vnen** [comment]
Reopening since the PR is not merged yet.

**Comment by volzhs** [comment]
@BastiaanOlij If you add "Fix #7127" or "Close #7127" in first comment, this issue will closed automatically when PR is merged.

**Comment by BastiaanOlij** [comment]
Done, learn something new every day:)

**Comment by reduz** [comment]
guys, you forgot to close it..
