### ISSUE TITLE
HTML5 export no longer loads custom cursor images in 3.5.1

### ISSUE THREAD

**Issue by Sharkalien** [godotengine/godot#71201]
### Godot version

v3.5.1.stable.official [6fed1ffa3]

### System information

Windows 10, Google Chrome Version 108.0.5359.125, GLES2, Intel HD Graphics 4600

### Issue description

After updating from Godot 3.4 to 3.5.1, the Input.set_custom_mouse_cursor() method no longer works when exported to HTML5. It loads in images fine when played in the editor, however. No errors are logged in the browser console, either.

### Steps to reproduce

Just load a texture into Input.set_custom_mouse_cursor() and export to HTML5. The minimal reproduction project is about as minimal as it gets.

### Minimal reproduction project

[HTML5 not loading cursor images.zip](https://github.com/godotengine/godot/files/10388767/HTML5.not.loading.cursor.images.zip)

**Comment by Calinou** [comment]
@Sharkalien Can you reproduce this in any of the [3.5 betas and RCs](https://downloads.tuxfamily.org/godotengine/3.5/) to determine when the regression started?

**Comment by Sharkalien** [comment]
I've been doing some additional testing and found that not even setting a custom image for the mouse cursor in the project settings worked, but I think I found a [relevant commit](https://github.com/godotengine/godot/commit/e1447ec823ea9dc024fc82dd140838061e735251) that might have caused the regression, at least. 

When the HTML5 project first runs, the canvas element's style rule doesn't include a declaration for the cursor property. After setting a Control node's default cursor shape property to anything else and hovering over it, the declaration is added and the custom mouse cursor finally works.
![gif1](https://user-images.githubusercontent.com/22488483/211973363-55926311-f05d-4806-a0b9-f4b2f9d1bd44.gif)

**Comment by akien-mga** [comment]
Can you test 3.5.2 RC 1? This might have been fixed by https://github.com/godotengine/godot/commit/602ef82e890439232327d1e886ded63f082e5cb7 

https://godotengine.org/en/article/release-candidate-godot-3-5-2-rc-1

**Comment by Sharkalien** [comment]
Yep, it's been fixed!

**Comment by Calinou** [comment]
Closing per the above comment.
