### ISSUE TITLE
Sub-Dictionaries cannot be modified in Beta 11.

### ISSUE THREAD

**Issue by cliftonpatty** [godotengine/godot#71200]
### Godot version

4.0.beta11

### System information

Windows 10,i7 4700k,1080ti

### Issue description

A weird issue that I can only confirm broken in one instance - I have a Dictionary, and one of the keys in that Dictionary is another Dictionary. When iterating over the Dictionary, I can modify the values of top-level keys (e.g. adding a number, multiplying, etc) but on the sub-level Dictionary I cannot. 

I moved back to Beta 10 and the issue is gone, with no modification to the code. 

Thanks for y'alls amazing work <3

### Steps to reproduce

```gdscript
extends Node2D

var testDic = {
	"armoured_chub" : {
		"ref" : "res://scenes/drillables/fish/armoured_swimmers/armoured_chub.tscn",
		"value" : 300,
		"depthTier" : 3,
		"rarity" : 30,
		"swimSpeed" : 150,
		"lootMeat" : 
			{
				"knight" : 2,
				"line" : 1
			},
		"lootGems" : 
			{
				"blue" : {
					"amount" : 1
				}
			}
		}
		}

var newDic : Dictionary

func _ready() -> void:
	for x in 5:
		for item in testDic:
			if item:
				if newDic.has(item):
					var dicItem = newDic[item]
					dicItem.total += 1
					var subDict = dicItem.loot
					for loot in subDict:
						print(subDict[loot].amount)
						print(subDict[loot].amount + 90)
						subDict[loot].amount += 90
						print(subDict[loot].amount)
				else:
					var dict = FishingDB.fishDB[item].lootMeat
					newDic[item] = {
						"total" : 1,
						"loot" : dict
					}
			
	print(newDic)
```

Just "Run Current" this code in both Beta 10 and Beta 11. 

### Minimal reproduction project

[test_dic.zip](https://github.com/godotengine/godot/files/10388372/test_dic.zip)

This is just the same code as "steps to reproduce" in zip form.

**Comment by adamscott** [comment]
@cliftonpatty Please wrap your code in code tags:

\`\`\`gdscript
YOUR CODE
\`\`\`

And when joining a minimal reproduction project, please create a project from scratch in Godot, then zip that directory (removing beforehand the `.godot` directory). Don't just share loose files.

**Comment by cliftonpatty** [comment]
@adamscott Just learned a valuable lesson in deep dictionary duplication
