### ISSUE TITLE
Error when using navigation

### ISSUE THREAD

**Issue by huangjiaminhhh** [godotengine/godot#71202]
### Godot version

Godot Engine v3.5.stable.official.991bb6ac7

### System information

Macos Monterey

### Issue description

Run project with navmesh and get error.

![image](https://user-images.githubusercontent.com/14999486/211722749-1fc1f677-9dd8-4b75-b762-e94e67cb97df.png)

E 0:00:00.266   sync: Attempted to merge a navigation mesh triangle edge with another already-merged edge. This happens when the current `cell_size` is different from the one used to generate the navigation mesh. This will cause navigation problems.

### Steps to reproduce

Run the uploaded project

### Minimal reproduction project

[navigation.zip](https://github.com/godotengine/godot/files/10389133/navigation.zip)

**Comment by smix8** [comment]
Increase the cell_size when you use SAMPLE_PARTITION_MONOTONE or use other NavigationMesh partition types for such a layout.

With 0.25 cell size only SAMPLE_PARTITION_WATERSHED (uses distance field and optimization passes) or SAMPLE_PARTITION_LAYERS (simplest possible) will work cause the default NavigationServer navmap cell_size is also 0.25 and SAMPLE_PARTITION_MONOTONE creates the navigation mesh in such a rough way that the vertex can not be mapped to the cells correctly creating overlap / intersections and this error msg.

**Comment by huangjiaminhhh** [comment]
It works for me. Thanks a lot. @smix8
