### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by cjmxp** [godotengine/godot#7120]
**Operating system or device - Godot version:**
github branch master code

**Issue description** (what happened, and what was expected):
c:\godot\thirdparty\libvpx\vpx_dsp/vpx_dsp_common.h(39) : error C2054: 在“inlin
e”之后应输入“(”
c:\godot\thirdparty\libvpx\vpx_dsp/vpx_dsp_common.h(39) : error C2085: “clip_pi
xel”: 不在形参表中
c:\godot\thirdparty\libvpx\vpx_dsp/vpx_dsp_common.h(39) : error C2143: 语法错误
: 缺少“;”(在“{”的前面)
c:\godot\thirdparty\libvpx\vpx_dsp/vpx_dsp_common.h(43) : error C2054: 在“inlin
e”之后应输入“(”
c:\godot\thirdparty\libvpx\vpx_dsp/vpx_dsp_common.h(43) : error C2085: “clamp”
: 不在形参表中

**Steps to reproduce:**
scons p=windows

**Link to minimal example project** (optional but very welcome):

**Comment by akien-mga** [comment]
Please run with `LC_ALL=C scons p=windows` to get errors in English.

We also need more information: what compiler are you using, in what version? What is your OS, in what version? etc.

**Comment by cjmxp** [comment]
My OS     Windows 7       Use Visual Studio 2013 to compile

**Comment by akien-mga** [comment]
CC @zaps166.

**Comment by akien-mga** [comment]
Error code translations (thanks google):
```
error C2054: expected '(' to follow 'inline'
error C2085: 'clip_pixel' : not in formal parameter list
error C2143: syntax error : missing 'token1' before 'token2'
error C2054: expected '(' to follow 'inline'
error C2085: 'clamp' : not in formal parameter list
```
(provided the error codes from MSVC 2015 are the same as in 2013)

**Comment by zaps166** [comment]
Can't compile on both: MSVC 2013 and 2015 ?

**Comment by cjmxp** [comment]
Yes Compilation failure Syntax error

**Comment by akien-mga** [comment]
@zaps166 The report is only about MSVC 2013. I mentioned 2015 only because I was looking at its docs to translate the error codes.

**Comment by zaps166** [comment]
Probably MSVC 2013 doesn't support `inline` in C code... 
`INLINE` is defined as `inline` in `vpx_config.h`, line 12. Probably MSVC 2013 needs to define as `__inline` or `__forceinline`.

@cjmxp Could you replace `#define INLINE inline` by `#define INLINE __inline` (`thirdparty/libvpx/vpx_config.h` line 12) and try again?

**Comment by cjmxp** [comment]
Modify the code to `#define INLINE __inline`
Compile through

**Comment by zaps166** [comment]
#7122 Please test :)
