### ISSUE TITLE
Out of bounds error on `ctrl+d` with some multi line selections

### ISSUE THREAD

**Issue by duianto** [godotengine/godot#71217]
### Godot version

v4.0.beta11.official [91713ced8]

### System information

Windows 10 22H2, Compatibility, GeForce GTX 550 Ti

### Issue description

In the `Script Editor`.
Sometimes when a selection spans multiple lines.
Pressing: `ctrl d` (which calls: `ui_text_add_selection_for_next_occurrence`)
Shows an error message in the `Output` panel:
>scene/gui/text_edit.cpp:4057 - Index p_from_column = 15 is out of bounds (text[p_from_line].length() + 1 = 1).

### Steps to reproduce

- start Godot
- open the attached project (it just has a new unmodified script with the default template)
- open the script `Node2D.gd`
- open the `Output` panel, near the bottom left of Godot
- in the `Script Editor`, select from the end of the first line to the second line,
either with the keyboard (`shift down`), or with the mouse
- press `ctrl d`

### Expected
A second cursor should be added on line 3,
and second selection should span from the end of line 2 to line 3.
| = a cursor,
[ = a selection start
] = a selection end

### Before `Ctrl d`
```
extends Node2D[
|]
```
### After `Ctrl d`
```
extends Node2D[
|][
|]
```

The expected behavior is observed in `Visual Studio Code`, 
with the same code example, and shortcut: `ctrl d`

### Before `Ctrl d`
![before](https://user-images.githubusercontent.com/13420573/211800737-096d0cf6-4499-4a8c-8bb7-9b9a020f9e5a.png)

### After `Ctrl d`
![after](https://user-images.githubusercontent.com/13420573/211800753-cbd16a87-1308-4de2-b2b7-ae886d06b759.png)

### Observed
The Output panel shows the error message:
>scene/gui/text_edit.cpp:4057 - Index p_from_column = 15 is out of bounds (text[p_from_line].length() + 1 = 1).

Selecting upwards from the second line to the end of the first, and pressing `ctrl d`,
shows the error message:
>scene/gui/text_edit.cpp:4057 - Index p_from_column = 15 is out of bounds (text[p_from_line].length() + 1 = 15).

### No errors when selecting in one direction
At first, it seemed like it might be happening when a new line is included in the selection.

But there is no error when selecting upwards:
- from the second line to the first line, including the first line's last character:
```
extends Node2[|D
]
```
- or downwards from the third line to the beginning, middle, or end of the fourth line:
```
extends Node2D

[
# Called|] when the node enters the scene tree for the first time.
```

### But there are errors when selecting in the other direction
Downwards:
```
extends Node2[D
|]
```
>  scene/gui/text_edit.cpp:4057 - Index p_from_column = 14 is out of bounds (text[p_from_line].length() + 1 = 1).

Upwards:
```
extends Node2D

[|
# Called] when the node enters the scene tree for the first time.
```
>  scene/gui/text_edit.cpp:4057 - Index p_from_column = 1 is out of bounds (text[p_from_line].length() + 1 = 1).

### Minimal reproduction project

[issue, ctrl d, next occurrence.zip](https://github.com/godotengine/godot/files/10392045/issue.ctrl.d.next.occurrence.zip)

**Comment by YuriSizov** [comment]
cc @aXu-AP perhaps this is something that you've fixed (or are interested in fixing)

**Comment by aXu-AP** [comment]
Thanks for the heads up, I might look at it some point, but I'm gonna be busy for some time now. But I tested this and can confirm this happens.
I didn't actually know this operation existed (it's called `ui_text_add_selection_for_next_occurrence` in shortcut settings), since I've remapped duplicate selection to `ctrl+D` long ago in my setup. Got me confused for a second 😅

**Comment by MewPurPur** [comment]
I'm on it.

**Comment by YuriSizov** [comment]
Still happens in 4.3 with the current master, by the way.
