### ISSUE TITLE
4.0 beta 10/11 - Export fails if any file is selected and or open in editor, even if files have been closed.

### ISSUE THREAD

**Issue by MarkoKrsic** [godotengine/godot#71238]
### Godot version

4.0 beta 10 (d0398f62f) and beta 11 (91713ced8)

### System information

Windows 10

### Issue description

I know that https://github.com/godotengine/godot/issues/69472#issue-1472337911 raises the fix, but the issue is more prevelent than reported there. 

I had errors with missing TSCN files and cyclical error warnings on export. After going through the above linked issue report I closed all windows and the export worked. 

The next go around on export the errors came back with a different set of files but without the cyclical warnings , this time a missing .gltf resource that isn't even included as a resource in the project, without any owners, only sitting in a mesh folder AND a script that was merely selected in the script editor. 

If the file is selected in the Editor's file browser or the script is selected in the script editor the build fails WITHOUT any warning in the editor. Unlike the issue where cyclical warnings appear in the editor, this just leads to the game crashing at start, without it progressing to the point where the resource is called. The console closes as well requiring a timed press of the Pause/Break key on the keyboard to catch the errors. 

In my case I had an NPC script that I worked on last, open in the editor, closing all scripts so none were selected removed the script related error but the gltf dependency would only go away after removing the file from the project folder. It was the last file worked on and was the last file selected, deselcting it or selecting a different file but not opening it did not remove the issue.

I only narrowed it down due to the issue noted above and paying attention to my last steps taken to see where I might have been introducing typos, figured out the newest errors were always regarding the last file worked on, finally noticed it happens on selection only not just open files.

### Steps to reproduce

a)Open one or multiple scripts in editor window, close all scene files and have an empty scene file waiting for input. Export project as debug or release, if there is a blue highlight on a script file in the script browser panel the build will fail with or without warnings in editor.

or

b) Select file in file browser with all scenes and scripts closed. Experience errors in console on launch of debug or release build without any warnings in editor. 

or

c) Exclude .gltf files in the export window, open/reimport a gltf file and close it. Something is cached in the editor telling it to include a reference to the last .gltf file opened in the build regardless of gltf exclusion rule.

### Minimal reproduction project

N/A

**Comment by YuriSizov** [comment]
Is this still reproduceable as of RC1 or RC2 (should be up soon)?

**Comment by MarkoKrsic** [comment]
I will check over the weekend, hopefully within the next 24 hours and report back.

**Comment by MarkoKrsic** [comment]
Sorry for the delay in getting back to you on this Yuri, I have gone through my project and exported it and don't see the issue still so this can be closed as far as I can tell.
