### ISSUE TITLE
[4.0 Beta 11 x64 Linux] - Parser Error: Could not resolve member "Icons": Cyclic reference. ?

### ISSUE THREAD

**Issue by BetaMaxHero** [godotengine/godot#71230]
### Godot version

Godot 4.0 Beta 11 x64 Linux Official

### System information

Linux Mint 21.1 Cinnamon 64Bit Linux OS

### Issue description

Hi,

On Godot 4.0 Beta 10 everything was OK.
On new Godot 4.0 Beta 11, our game does not run?

Getting strange errors like below:
```
for index in range(0, 4):
	InterfaceCore.Icons.IconAnimationTimer[index] = -1
# Parser Error: Could not resolve member "Icons": Cyclic reference.
```

Any ideas?

### Steps to reproduce

Reproducible when running game on Godot 4.0 Beta 11 x64 Linux version.

### Minimal reproduction project

https://github.com/BetaMaxHero/GDScript_Godot_4_T-Story

**Comment by akien-mga** [comment]
CC @adamscott @anvilfolk

**Comment by BetaMaxHero** [comment]
Hi,

Is there something I can do on my side to fix above errors on Beta 11 x64 Linux version?
Or I should go back to Beta 10 and wait for Beta 12 ?

Jesse

**Comment by adamscott** [comment]
CC @rune-scape

**Comment by adamscott** [comment]
@BetaMaxHero You could help by submitting a minimal reproduction project. Minimal in miminal reproduction project means to isolate to the strict minimum what goes wrong. It makes debugging and fixing the issue much easier. :)

Even if your source code is available and public.

**Comment by BetaMaxHero** [comment]
Hi,

Still an issue in Beta 12.

Jesse

**Comment by adamscott** [comment]
@BetaMaxHero Can you join a MRP, as asked?

**Comment by BetaMaxHero** [comment]
Hi,

i tried to make a MRP, but the error on running does not occur?
What does "Cyclic Reference" mean?
(perhaps it is an error in my source code)

Jesse

**Comment by adamscott** [comment]
I'm investigating. I downloaded your project and reproduced the issue. I'm currently trying to create a MRP.

**Comment by BetaMaxHero** [comment]
Ok, thank you for your help...

**Comment by BetaMaxHero** [comment]
Sorry, will above issue be fixed in next Beta of 4.0 ?

**Comment by adamscott** [comment]
@BetaMaxHero It will be fixed when it will be merged, unfortunately. There's no guarantee that it will make it to the next beta.

**Comment by BetaMaxHero** [comment]
Ok, many thanks!

**Comment by adamscott** [comment]
@BetaMaxHero It's in beta 13! https://godotengine.org/article/dev-snapshot-godot-4-0-beta-13/
