### ISSUE TITLE
Android Beta 11 Scaling 

### ISSUE THREAD

**Issue by imximxi** [godotengine/godot#71246]
### Godot version

4.0 beta 11

### System information

Android Pixel 4 android 13

### Issue description

Scaling for android beta 11

Beta 10 scaling is fine 
![Screenshot_20230111-214349](https://user-images.githubusercontent.com/122491128/211925181-504e7c50-f235-4292-b4a4-cdd6ee74f67e.png)

Beta 11 scaling is off
![Screenshot_20230111-214253](https://user-images.githubusercontent.com/122491128/211925334-3d0e03b5-5b77-42e8-a6ae-49cf5d7ab179.png)

### Steps to reproduce

install 

create project 

edit project

### Minimal reproduction project

none needed

**Comment by Calinou** [comment]
This is not actually a GUI scaling issue, but one of the controls may now be forcing a minimum size that's too high to work on mobile.
