### ISSUE TITLE
[4.0 Beta 14] C#  Changing/Packing the Scene "forgets" set values in the new scene

### ISSUE THREAD

**Issue by codewing** [godotengine/godot#71244]
### Godot version

4.0.beta14

### System information

Linux

### Issue description

Changing a level and setting a variable inside the tree of the upcoming scene used to work like this in 3.5:

```
var sceneLoaderScene = (PackedScene) GD.Load("res://scenes/other_scene.tscn");
var sceneInstance = sceneLoaderScene.Instantiate<PrintInNewLevel>();
sceneInstance.PrintMe = "Greetings from the other script!";
			
var packedScene = new PackedScene();
var result = packedScene.Pack(sceneInstance);
if (result == Error.Ok)
{
	GetTree().ChangeSceneToPacked(packedScene);
}
```
With `PrintInNewLevel` inheriting from Node2D

I came across the`GetTree().CurrentScene = sceneInstance` during this research but this seems to crash even harder.

---

Is this intended behavior and if yes how does this work in 4.0?

### Steps to reproduce

- Create two scenes SceneA and SceneB.
- Switch from SceneA to SceneB
- Before switching set a variable in the newly instanced SceneB
- Try to access the newly set variable from the loaded SceneB

Expected: Variable is set
Actual: Variable is not set.

### Minimal reproduction project

[minimal_repro.zip](https://github.com/godotengine/godot/files/10395833/minimal_repro.zip)

---
Updates:
1. Tested with beta 14 again - still persists

**Comment by KoBeWi** [comment]
Is your variable exported? Packed scene stores only exported (serializable) variables.

**Comment by codewing** [comment]
Interesting, this seemed to work in 3.5 though.
Anyway I've also tried it with and it didn't work. This should avoid the packing of the scene and does basically the same..

```
var sceneLoaderScene = (PackedScene) GD.Load("res://scenes/other_scene.tscn");
var sceneInstance = sceneLoaderScene.Instantiate<PrintInNewLevel>();
sceneInstance.PrintMe = "Greetings from the other script!";
			
GetTree().CurrentScene = sceneInstance;
```

**Comment by raulsntos** [comment]
> Interesting, this seemed to work in 3.5 though.

I've ported and tested your MRP in 3.5.1, as expected it doesn't work without `[Export]`. With `[Export]` your MRP works in both 3.5.1 and 4.0-beta.17.

> This should avoid the packing of the scene and does basically the same

Yes, but don't forget to also add the node instance to the scene. In your code excerpt you are not adding the node to the scene which would result in the error `Condition "p_scene && p_scene->get_parent() != root" is true`.

If you want to know exactly how `ChangeSceneToPacked` does this, here's the implementation:

https://github.com/godotengine/godot/blob/13f0158e49676fc5ec8694a40261685596faa3d1/scene/main/scene_tree.cpp#L1133-L1141
https://github.com/godotengine/godot/blob/13f0158e49676fc5ec8694a40261685596faa3d1/scene/main/scene_tree.cpp#L1103-L1122
