### ISSUE TITLE
[4.0 beta11] GeometryInstance3D transparency parameter hide mesh with value over 0.0

### ISSUE THREAD

**Issue by jmb462** [godotengine/godot#71249]
### Godot version

4.0 beta 11

### System information

Windows10

### Issue description

When setting GeometryInstance3D transparency parameter to a value higher than zero, mesh do not appear anymore if material transparency is not enabled.

 Worked fine in beta10 even if material was not set to transparent.

Not sure if it's a regression or a bug fix...

### Steps to reproduce

1. Add a MeshInstance3D with a Box shape
2. Change the transparency setting in GeometryInstance3D

Mesh disappears.

Beta 11 : 

![transp_bug](https://user-images.githubusercontent.com/3649998/211932790-15d92330-83dd-46f3-b975-6ecdcdb15984.gif)

Beta 10 : 

![transp_bugb10](https://user-images.githubusercontent.com/3649998/211932880-f94ad790-b982-4202-9514-abbdee3a2be0.gif)

### Minimal reproduction project

[transparency_bug.zip](https://github.com/godotengine/godot/files/10396445/transparency_bug.zip)

**Comment by jmb462** [comment]
Just realized that it works if Transparency is enabled in material.
Before, it was working even if material transparency was disabled.

So don't know if it's a regression or a bug fix...

**Comment by clayjohn** [comment]
I noticed this as well. There is already a PR fixing it that just needs to be merged https://github.com/godotengine/godot/pull/71124

**Comment by fracteed** [comment]
@clayjohn I am not sure if this feature is intended to work on the mobile and opengl renderers or not? Can be hard to find this sort of info, and I didn't want to open up a new issue if it is a known limitation.

**Comment by clayjohn** [comment]
@fracteed it should work on all rendering backends

**Comment by fracteed** [comment]
@clayjohn I have tried it on a few pc's and it only works in 4.0.2 on the forward+ renderer. Do you want me to open up another issue?

**Comment by clayjohn** [comment]
> @clayjohn I have tried it on a few pc's and it only works in 4.0.2 on the forward+ renderer. Do you want me to open up another issue?

Yes please. I took a quick look and it looks like it just hasn't been implemented. It would be nice to have an issue to track it. It should not be a lot of work to implement as the implementation can be copied directly from the clustered renderer. 

_Code for reference_
https://github.com/godotengine/godot/blob/8c729f0f34a92b92a1a8204e1d56b6ad05cfd27b/servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp#L845-L860
