### ISSUE TITLE
SceneTreeTween hangs running game on reuse

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#71245]
### Godot version

3.5.1 stable

### System information

Linux

### Issue description

If you try to use a SceneTreeTween again after it has finished in the same function, the tween object exists and is valid, you can call all the tween methods and everything appears to work, but nothing actually runs and you never get any signals. 

If it is as designed to not allow this, then the tween should either null itself or all methods should raise an exception so code knows something has gone wrong. Also, the documentation needs to address this too?

```
	var tw:SceneTreeTween=create_tween()
	tw.tween_property(rect,"color:a", 1.0, duration/2.0).set_delay(duration/2.0).set_ease(Tween.EASE_IN).set_trans(Tween.TRANS_LINEAR).from(0.0)
	yield(tw,"finished")
	
       #some code
	_camera_controller.set_position(newpos+camera_offset)
	
	tw.tween_property(rect,"color:a", 0.0, duration/2.0).set_delay(duration/2.0).set_ease(Tween.EASE_IN).set_trans(Tween.TRANS_LINEAR).from(1.0)
	yield(tw,"finished")
```

I did this the first time I used tweens and the only fault is the second yield never yields and the code hangs forever.

In addition, where it says 'some code' if you put a: stop()

It gives the error 'tween still running you need to call stop()' (or words to that effect), even though it has obviously stopped.

### Steps to reproduce

1. create a tween and start it
2. yield until finished
3. try to start again

### Minimal reproduction project

n/a

**Comment by KoBeWi** [comment]
The error says
```
Can't append to a Tween that has started. Use stop() first.
```
It doesn't say anything about Tween running. You need to call `stop()` to reset the "started" state.
Also be sure to read `finished` signal description.

On a last note, SceneTreeTweens aren't supposed to be reused. You can somewhat force it with `stop()`, because users requested it for whatever reason, but normally you should create a new tween for each new animation.

Closing, as the behavior is documented and you get clear errors.

**Comment by chucklepie** [comment]
Ok, but it's a bit of a crap behaviour isn't it?

No indication is invalid to use, no errors generated, literally nothing.

The object is still valid and pointing at something but it doesn't work
afterwards.

No documentation to state this either

**Comment by astrale-sharp** [comment]
Indeed there is no documentation. I had the same issue

**Comment by YuriSizov** [comment]
@chucklepie Can you provide an example of there being no errors or other indication? As KoBeWi mentions, the code you provided does raise an error.

**Comment by Sslaxx** [comment]
See https://github.com/godotengine/godot/pull/74258
