### ISSUE TITLE
Crash and weird behavior when using const packed arrays

### ISSUE THREAD

**Issue by TheSecondReal0** [godotengine/godot#71255]
### Godot version

4.0b11, 0abd60b9530d574fc8fc466e6a3f0c5b9814f697

### System information

Windows 10, RTX 2060, Vulkan

### Issue description

Trying to iterate over a const PackedStringArray in an _init() function causes silent crash. PackedInt32 + PackedInt64Arrays don't have the correct values.

Not fixed by #71228

### Steps to reproduce

Try to run this code (note: same issues exist using _ready() as well):
``` swift
extends Node

const array: Array = ["hello", 1234, 1.234]
const packed32: PackedInt64Array = [5034, 4343, 10101]
const packed64: PackedInt64Array = [5034, 4343, 10101]
const packed_string: PackedStringArray = ["hello", "goodbye", "testing"]

func _init():
	print_debug("about to iterate over array")
	for thing in array:
		print(thing)
	print_debug("about to iterate over packed32")
	for thing in packed32:
		print(thing)
	print_debug("about to iterate over packed64")
	for thing in packed64:
		print(thing)
	print_debug("about to iterate over packed_string")
	for thing in packed_string:
		print(thing)
```
which gives this output:
```
Godot Engine v4.0.beta.custom_build.0abd60b95 - https://godotengine.org
Vulkan API 1.3.224 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 2060 with Max-Q Design

about to iterate over array
   At: res://main.gd:9:_init()
hello
1234
1.234
about to iterate over packed32
   At: res://main.gd:12:_init()
249108103170
10101
0
about to iterate over packed64
   At: res://main.gd:15:_init()
249108103170
10101
0
about to iterate over packed_string
   At: res://main.gd:18:_init()

================================================================
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.0.beta.custom_build (0abd60b9530d574fc8fc466e6a3f0c5b9814f697)
```

### Minimal reproduction project

[static-packed.zip](https://github.com/godotengine/godot/files/10397193/static-packed.zip)

**Comment by vonagam** [comment]
I assume it will be fixed by #70873. There is an implicit conversion involved for `packed32: PackedInt64Array = [5034, 4343, 10101]`, from usual array to `PackedInt64Array`, which currently does not happen because it is `const`.

**Comment by dalexeev** [comment]
Yes, I tested, with #70873 the output looks correct:

```
about to iterate over array
hello
1234
1.234
about to iterate over packed32
5034
4343
10101
about to iterate over packed64
5034
4343
10101
about to iterate over packed_string
hello
goodbye
testing
```

I'm not sure how #70873 works with typed arrays, but I think it's either already fixed in #69248 or can be fixed quickly.

**Comment by vonagam** [comment]
It works because there exist a conversion for a usual array to packed one and back. Which before I read this issue I was not aware of. The fact that it exists makes my array PR more consistent with current state.

When it comes to literals, like in shown example, I do agree that it is handy, but I'm not sure about implicit copying existing array - `var packed: PackedStringArray = my_array`.

**Comment by TheRealSlander** [comment]
I encountered the same kind of crash behavior in Godot 4.0 beta 11 while iterating in an array using this:
`const ARRAY : PackedStringArray = ["a", "b", "c", "d", "e"]`

While, using this works perfectly:
`var ARRAY : PackedStringArray = ["a", "b", "c", "d", "e"]`

If it can help...
