### ISSUE TITLE
Multi Tiled Sprite Y Sort Order not working correctly

### ISSUE THREAD

**Issue by KHawk63** [godotengine/godot#71257]
### Godot version

4.0 Beta 11 & 10

### System information

Windows 10 64-bit, NVIDIA GeForce GTX 980, DirectX 12, version 31.0.15.1694

### Issue description

When using a tile created from multiple tiles like a wall that is size 64x64 out of a 16x16.  The wall will overlap with the next wall placed.  But when you enable/disable y sort (or hold the enable y sort shortcut) they will show-up as expected briefly then go back to not working.

![Y Sort issue](https://user-images.githubusercontent.com/11861688/211966865-c249758d-3c33-4953-a4cf-6cb4f89589ae.gif)

### Steps to reproduce

1. Create a new tilemap
2. add a tilemap that has something like a wall in the issue description
3. setup the wall so it's made out of multiple tiles 2x2
4. place on the tilemap next to another
5. View walls overlap unexpectedly
6. enable y-sort on tilemap and layer
7. view they still overlap
8. Enable/Disable y-sort to see it fix itself, and go back to not working.

### Minimal reproduction project

[Y Sort issue.zip](https://github.com/godotengine/godot/files/10397872/Y.Sort.issue.zip)

**Comment by groud** [comment]
Sadly, there's not really a fix for that, unless we implement a way to "X-sort" the nodes one way or another.
This requires significant changes to the rendering server.

See https://github.com/godotengine/godot-proposals/issues/2838

**Comment by groud** [comment]
I found a workaround. It's not optimal but well, better than nothing: 
- Set the TileMap as Y-Sorting
- Rotate the TileMap by `0.1`
- Set the Node2D parent's of the TileMap as Y-sorting
- Rotate the Node2D parent by `-0.1`

**Comment by FeldonDragon** [comment]
Not sure if this solves your problem, but analysing your case, I managed to fix this problem in my project...

Solution: Select TileMapLayer -> check Y Sort Enabled -> open Rendering tab -> check/uncheck "X Draw Order Revers"

That worked for me and I'm creating in very similar style (tibia-like assets) to you :) 
Hope that will help someone!
