### ISSUE TITLE
Godot 4.0 Beta 11 - MultiplayerSpawner error on new node name

### ISSUE THREAD

**Issue by DeadlyEssence01** [godotengine/godot#71252]
### Godot version

4.0 beta 11

### System information

Linux Ubuntu

### Issue description

After creating a server connection, if you 'spawn'  more than one version of the node (add child nodes) to the designated MultiplayerSpawner's (MS) node, with a valid scene saved to the MS, you receive this error:

```
E 0:00:50:0683   _on_spawn_pressed: Unable to auto-spawn node with reserved name: @Sprite2D@2. Make sure to add your replicated scenes via 'add_child(node, true)' to produce valid names.
  <C++ Error>    Condition "name.validate_node_name() != name" is true.
  <C++ Source>   modules/multiplayer/multiplayer_spawner.cpp:229 @ _node_added()
  <Stack Trace>  main.gd:22 @ _on_spawn_pressed()

```
"@Sprite2D@2" changes with the number spawned. 

The nodes usually still show, but can have issues with being deleted as they don't seem to have been appropriately made initially (not sure entirely)

Clients can spawn the same scene seemingly with no problem.
Though they sometimes get this error: 
```
E 0:00:48:0833   on_spawn_receive: Condition "parent->has_node(name)" is true. Returning: ERR_INVALID_DATA
  <C++ Source>   modules/multiplayer/scene_replication_interface.cpp:556 @ on_spawn_receive()
```

### Steps to reproduce

Create a network as a server, have a mutliplayer spawner with its node path set to a node. Add a scene to the MS to spawn. Add_child the scene to the same node the MS is set for. Then add_child again to receive the error.

### Minimal reproduction project

While this has a server and client, the problem can be reproduced with just a server connection.
[test.zip](https://github.com/godotengine/godot/files/10396596/test.zip)

**Comment by DeadlyEssence01** [comment]
To resolve this error, the `add_child()` func should have the second parameter set to true... which was not the case. This issue can be closed.

**Comment by TheYellowArchitect** [comment]
Adding "true" to 2nd parameter solved the bug for me, on Godot Beta14, on my own project (not the above MRP)

Someone should test the above MRP in Godot beta17+ to confirm this is really a bug

**Comment by AngCosmin** [comment]
I'm having the exact same problem with Godot 4.0 beta 17 (latest)

**Comment by YuriSizov** [comment]
@AngCosmin Actually, RC1 is latest :) Though I don't think there was a fix in the meantime.

**Comment by AngCosmin** [comment]
Oh, it was released yesterday. I didn't know about it :)

In the meantime looks like the error is gone if I am doing something like this:
```
item.name = "Pickup_{0}".format([randf_range(0, 1000000)])
```

**Comment by theromis** [comment]
@AngCosmin facing same issues in my multiplayer test, but with your example project been able to get rid of errors
```
var Child = preload("res://sprite_2d.tscn")

func _on_spawn_pressed():
	var child = Child.instantiate()
	child.name = str(children_spawned)
	add_child(child)
	children_spawned += 1
	print("spawn x", children_spawned)
```

**Comment by theromis** [comment]
@AngCosmin btw: can't find, how you setup running 2 app instances per clicking `Run project` button

**Comment by AngCosmin** [comment]
@theromis You can do it from the `Debug` menu

<img width="491" alt="image" src="https://user-images.githubusercontent.com/8146514/218982228-6cb9b1bc-0cf4-4ae9-859e-cf7f99c9750e.png">

**Comment by theromis** [comment]
just found it, thank you
but you example tells me that I have some naming problems in my project

**Comment by Faless** [comment]
As the error in the OP states:
`Make sure to add your replicated scenes via 'add_child(node, true)' to produce valid names.`

So to anyone testing the original project, the issue is that `add_child(child)` should be `add_child(child, true)`.

Additionally, make sure to disable the spawn button on the client to avoid spawning nodes only on the client (and potentially end up with colliding name).

Fix:

```
func _on_spawn_pressed():
	if not multiplayer.is_server():
		return
	var child = load("res://sprite_2d.tscn").instantiate()
	add_child(child, true)
	children_spawned += 1
	print("spawn x", children_spawned)
```

**Comment by PPillau** [comment]
Just for anybody in the future who stumbles upon this error and the second parameter for `add_child` doesn't solve the issue, here was my problem:

The spawn node/spawn path for my MultiplayerSpawner pointed to a node of the general type "Node", which does not have a "name" attribute. When I switched the type of my spawning-node to Node3D instead, the error went away, because Node3D now does have a name attribute.

Hope that may help someone else in the future :) Maybe we could write this in the docs as well somehow as a hint or something...

**Comment by tjulioh** [comment]
Godot 4.1.1 here, i change to Node3D but properties name dont exists and give same error. I pointed MultiplayerSpawner to himself, MultiplayerSpawner and solved.

**Comment by isaaccp** [comment]
FWIW, regarding the previous comment, I have my MultiplayerSpawners pointing at a plain Node and don't have this issue. 

Moreover, the check is for "does the parent already have a node with this name?" so it doesn't seem like whether the parent is a Node vs Node3D would matter?

**Comment by Archytas79** [comment]
Still have this issue with `add_child` second parameter being true.
```
func add_player(peer_id, player_info):
	var _new = PlayerScene.instantiate();
	_new.set_multiplayer_authority(peer_id, true);
	PlayerObjects.add_child(PlayerScene.instantiate(), true);
	return;
```
this gets called by the server when a player successfully connects - it should spawn it, then set the multiplayer authority to the client yet it errors out with the above: 'on_spawn_receive: Condition "parent->has_node(name)" is true. Returning: ERR_INVALID_DATA'

**Comment by kawht** [comment]
Having same issues as well, does nobody know anything still? I've been battling it for days.

**Comment by fermion87** [comment]
I was able to solve this problem in my case. 

I was trying to replicate a Node3D scene called `Physics Objects`. When inspecting the remote scene tree, each instance was named `@Node3D@2`,`@Node3D@3`... etc. These were spawning in the server, but not being replicated by the MultiplayerSpawner across the connected clients.
![image](https://github.com/godotengine/godot/assets/74116015/2df99a89-32a8-4bfd-9668-953bda34b46f)

I was able to fix this error by adding the second argument `true` to `add_child(instance, true)` as in this function that instantiates a new scene that contains RigidBody3Ds.
![image](https://github.com/godotengine/godot/assets/74116015/19deb7e9-c265-49c7-885a-22897a49a3a5)

After adding the `true` argument, each node is now named properly. In my case, `Physics Object2`, `Physics Object3`... etc. This was also the fix that finally correctly spawned the objects across all peers.
![image](https://github.com/godotengine/godot/assets/74116015/a0a1efe6-cf3d-4976-a293-268286000856)

**Comment by CrispyMD** [comment]
I'm still having some issues... Made these modification to the project, such that when the server spawns a node, it will update for all clients (using MultiplayerSynchronizer on the sprite that replicates position). Although, when the client clicks spawn the sprite appears only on that client, but not on the server side. Any fixes?
![image](https://github.com/user-attachments/assets/c456c69f-edaa-4472-a88b-e9640b7332af)
![image](https://github.com/user-attachments/assets/be015c2d-38fb-4904-b053-abd56d7cb6ff)

**Comment by RpxdYTX** [comment]
@CrispyMD shouldn't `spawn_child` be called with `.rpc[_id]`?
