### ISSUE TITLE
`OS.kill()` doesn't kill the process that it's not spawned by the game

### ISSUE THREAD

**Issue by eskandrej** [godotengine/godot#71268]
### Godot version

v3.5.1.stable.official [6fed1ffa3]

### System information

Windows 10, NVIDIA GeForce GTX 760

### Issue description

OS.kill() will not terminate process that it's not spawned by game although it is noted in the documentation that it can also be used to kill processes that were not spawned by the game.

### Steps to reproduce

Use PID when calling OS.kill() that it isn't spawned by the game.

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
It seems to work fine on Linux.
Might be specific to Windows and/or macOS. @bruvzg

**Comment by bruvzg** [comment]
> Might be specific to Windows and/or macOS.

macOS uses the same generic Unix `kill` as Linux, and Windows uses a map of child processes to kill, fix - https://github.com/godotengine/godot/pull/71269
