### ISSUE TITLE
Invalid type inference when returning from a branch

### ISSUE THREAD

**Issue by vr-voyage** [godotengine/godot#71277]
### Godot version

4.0.beta10

### System information

Windows 10, Vulkan, Nvidia RTX 3080

### Issue description

When using the following code :

```gdscript

extends Node

var dayta = {"impressive_field": Vector3.ONE}

func this_returns_any_kind_of_object(data:Dictionary):
	var invalid_value:Dictionary = {}

	if data.has("impressive_field"):
		return data["impressive_field"]

	return invalid_value

# Called when the node enters the scene tree for the first time.
func _ready():
	var output:Vector3 = this_returns_any_kind_of_object(dayta)

```

The compiler will output the following error :
```
Error at (15, 26): Value of type "Dictionary" cannot be assigned to a variable of type "Vector3".
```

This inference is wrong, the type of the value is actually unknown here, the "if" branch returns a value based on some Dictionary field which can be anything.

However, this is not all, if you write `this_returns_any_kind_of_object` like this :

```gdscript
func this_returns_any_kind_of_object(data:Dictionary):
	var invalid_value:Dictionary = {}

	if data.has("impressive_field"):
		return data["impressive_field"]

	return invalid_value
	return Quaternion.IDENTITY
```

The compiler will then complain about :

```
Error at (16, 26): Value of type "Quaternion" cannot be assigned to a variable of type "Vector3".
```

The GDScript interpreter seems to infer the return type of the method based on type of the value of the latest "return" value found, it seems.
This can be resolved by having only one value to all the "return" clauses, but this does not accommodate every programming style.

```
# This will work fine
func this_returns_any_kind_of_object(data:Dictionary):
	var invalid_value:Dictionary = {}
	var returned_value = invalid_value

	if data.has("impressive_field"):
		returned_value = data["impressive_field"]

	return returned_value
```

### Steps to reproduce

* Create a Scene, add a script to the main node and use the following code :

```gdscript
extends Node

var dayta = {"impressive_field": Vector3.ONE}

func this_returns_any_kind_of_object(data:Dictionary):
	var invalid_value:Dictionary = {}

	if data.has("impressive_field"):
		return data["impressive_field"]

	return invalid_value

# Called when the node enters the scene tree for the first time.
func _ready():
	var output:Vector3 = this_returns_any_kind_of_object(dayta)
	print(output)
```

* The compiler will deny the ability to play this scene, even though the code is correct, due to invalid type inferences.

### Minimal reproduction project

[BugTester.zip](https://github.com/godotengine/godot/files/10404528/BugTester.zip)

**Comment by akien-mga** [comment]
Confirmed in 4.0 beta 10, but this is already fixed in 4.0 beta 11.
