### ISSUE TITLE
[Godot 4.0] Window bugs

### ISSUE THREAD

**Issue by HackLinjiuyue** [godotengine/godot#71288]
### Godot version

v4.0.beta11.official.91713ced8

### System information

Window 10,Vulkan API 1.2.194 - Using Vulkan Device #0: Intel - Intel(R) Iris(R) Xe Graphics

### Issue description

Nothing happened after set window.initial_position to screen center and set window.title to something else.

### Steps to reproduce

Create a FileDialog Node and set its Initial Position to Screen Center | set its Title to anything instead of default text.

### Minimal reproduction project

N/A

**Comment by bruvzg** [comment]
> Nothing happened after set window.initial_position to screen center and set window.title to something else.

`title` seems to be working fine (note, FileDialog can rest title when you change other properties, to avoid it unset `mode_overrides_title`)

`initial_position` is for the native windows only (unset "embed sub-windows in the project settings), it will take effect when the window is first opened, but not in the editor (and not for embedded windows).

**Comment by HackLinjiuyue** [comment]
> > Nothing happened after set window.initial_position to screen center and set window.title to something else.
> 
> `title` seems to be working fine (note, FileDialog can rest title when you change other properties, to avoid it unset `mode_overrides_title`)
> 
> `initial_position` is for the native windows only (unset "embed sub-windows in the project settings), it will take effect when the window is first opened, but not in the editor (and not for embedded windows).

Maybe we can add embedded windows support for `initial_position` too?

**Comment by akien-mga** [comment]
Closing as those are not bugs.
