### ISSUE TITLE
Change datatype from int to float with no reason

### ISSUE THREAD

**Issue by alberto-mco** [godotengine/godot#71283]
### Godot version

4.0 beta 11

### System information

Windows 11

### Issue description

I notice a bug using godot 4 beta 11, because godot change the data type from int to float. It's a problem because i can't compare 2 values with an if sentence.
Note: This doesn't occurs in godot 4 beta 10.

Using my example and my player_inventory.dat, you can see 2 different outputs using godot 4 beta 11 and beta 10.

**Output with beta 11:**
```
typeof 'count' before: 2
typeof 'count' after: 3
[1 != 1] typeof['a'=3, '1'=2]
```

**Output with beta 10:**
```
typeof 'count' before: 2
typeof 'count' after: 2
[1 == 1] typeof['a'=2, '1'=2]
```

### Steps to reproduce

It's easy, just put the player_inventory.dat in the user://, and play the scene

### Minimal reproduction project

[report_conversion.zip](https://github.com/godotengine/godot/files/10405276/report_conversion.zip)

**Comment by akien-mga** [comment]
This appears to be fixed in the current `master` branch, likely by #71228.
