### ISSUE TITLE
HTML5 custom cursor reverts to default in bottom and right margin

### ISSUE THREAD

**Issue by Sharkalien** [godotengine/godot#71291]
### Godot version

v3.5.2.rc2.official [1a2bf3eb4]

### System information

Windows 10, Google Chrome Version 109.0.5414.75, GLES2, Intel HD Graphics 4600

### Issue description

After exporting to HTML5, there's this weird approximately 60px margin on the bottom and right side of the canvas that causes a custom mouse cursor to revert back to the default cursor, although the cursor property doesn't change at all, strangely enough.

Here it is happening with a ColorRect strictly being used to show the cutoff point.

https://user-images.githubusercontent.com/22488483/212182601-fa6fa7de-9963-4715-a11a-04808eceafdc.mp4

https://user-images.githubusercontent.com/22488483/212182656-a0311561-0d99-4730-bea1-5d30536d2084.mp4

I've tested as far back as 3.2 and this occurs in every version.

### Steps to reproduce

Set a custom image for the mouse cursor in the project settings and export to HTML5.

### Minimal reproduction project

[HTML5 custom cursor reverting.zip](https://github.com/godotengine/godot/files/10406088/HTML5.custom.cursor.reverting.zip)

**Comment by Calinou** [comment]
This may be done by design, as you're not pointing within the game window in this situation.

**Comment by Sharkalien** [comment]
But the whole canvas is the game window, unless I'm misunderstanding. The ColorRect in the above example videos wasn't taking up the full window only to show where the cursor was only visible. This still occurs even after changing the resize policy, window size project settings, stretch mode and aspect.

https://user-images.githubusercontent.com/22488483/212194946-61e5f243-4190-4bf6-a551-509321c6acf8.mp4

**Comment by Sharkalien** [comment]
Oh you know what, it just occurred to me that it might be because of the size of the cursor, and when it extends outside of the browser, it can't render itself for some reason. That's lame.

**Comment by Sharkalien** [comment]
Closing this issue since [using](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor#icon_size_limits) a custom cursor larger than 32x32 pixels will cause the behavior exhibited above, and this is [implemented into browsers](https://chromestatus.com/feature/5825971391299584) as a security feature against spoofing, so this is outside of Godot's control.

If you really need a larger cursor than that AND have the game take up the whole window, a hacky workaround would be to implement a fake custom cursor yourself inside of the engine using something like a Sprite that constantly has its position updated to wherever the cursor is. I don't see this being a very common problem that people will run into, though.

**Comment by Zireael07** [comment]
Probably worth documenting in the web export page, though?
