### ISSUE TITLE
IPv6 for Godot 2.1.x

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#7129]
The recently-implemented IPv6 support in the master branch seems to behave, at least @punto- reports that some guys were able to publish their iOS game without any trouble (so Apple did not complain about missing support - and I suppose the game worked too :)).

There have been quite a few commits about this, so instead of trying to cherry-pick them myself, I'd like someone who understands this stuff to do it :)

@Faless Would you mind preparing a pull request to the 2.1 branch to add all the IPv6-related commits?

You can cherry-pick with `git cherry-pick -x <commit-hash>` - the `-x` part adds the hash of the original commit to the description of the cherry-picked commit, I'm using this as a convention for better traceability.

**Comment by Faless** [comment]
> @Faless Would you mind preparing a pull request to the 2.1 branch to add all the IPv6-related commits?

Sure, no problem, I'll start cherry picking and let you know ASAP @akien-mga

**Comment by bojidar-bg** [comment]
Closing as the PR was merged
