### ISSUE TITLE
AnimatedSprite2D add frames from sprite sheet picture display problem

### ISSUE THREAD

**Issue by absolve** [godotengine/godot#71310]
### Godot version

3.5.1-stable_win64

### System information

win10,gles3, AMD Radeon R7 M260

### Issue description

When I add animations using AnimatedSprite2D, I find that images loaded from the Sprite sheet display incorrectly
like this

![E}RD2VUVXOUF3U_((}XU2OC](https://user-images.githubusercontent.com/6998235/212219424-1f3dc379-fc11-4171-b9fd-e0c98952216f.png)

But when I used aseprite to view images, the ratio was just right.

![8LRTQH0M 4)1_Q)E3~SI$K1](https://user-images.githubusercontent.com/6998235/212220145-891d7b5f-907a-47cc-9286-2cc8c5246f74.png)

 The image size of each Sprite is 64x64

![bowser](https://user-images.githubusercontent.com/6998235/212220654-2dd7aa47-6535-48e3-95fe-f3a7df256253.png)

### Steps to reproduce

![ZSKFN%2BJ13MF}OL(8ACRYK](https://user-images.githubusercontent.com/6998235/212221339-7f2c33dd-0abb-4619-8096-0246969ae31f.png)

![{}IRTM3_O U JEPLSA832Q0](https://user-images.githubusercontent.com/6998235/212221511-4287f439-b135-4c0e-b0df-8ce481b20c98.png)

![$ UGXR1$5GRNF5 ML@JSY4](https://user-images.githubusercontent.com/6998235/212221648-4a7f0dd3-4687-4ae3-9009-973226f12b93.png)

### Minimal reproduction project

[godotTest1.zip](https://github.com/godotengine/godot/files/10407575/godotTest1.zip)

**Comment by Calinou** [comment]
This is caused by bilinear filtering when sprites don't have any padding on the edges.

To resolve this, select the texture in the FileSystem dock, disable **Filter** in the Import dock, then click **Reimport**.
