### ISSUE TITLE
Wrong Chinese encoding for MSBuild errors in the editor

### ISSUE THREAD

**Issue by L2750558108** [godotengine/godot#71326]
### Godot version

4.0(beta 11) mono

### System information

windows10

### Issue description

![image](https://user-images.githubusercontent.com/119792950/212323573-8c6ef2aa-7dc8-463a-94a1-7e97eabf13b0.png)

### Steps to reproduce

Set the editor language to chinese
Create a C# project
Create a scene
Create a C# script
Build it
Go to MSBuild Window
See the chinese display error

### Minimal reproduction project

An empty project

**Comment by akien-mga** [comment]
Can you translate the error, or is it invalid Chinese? I see some characters are mangled (e.g. "Debug" lacks the "D").

Could you confirm which is the bug / unexpected behavior you are experiencing?
- There is an error (in Chinese) when using the editor in Chinese. There is no error when using the editor in English.
- There is an error both when using the editor in English and in Chinese, but you do not expect the error message to be presented in Chinese and would prefer it to be always in English?

**Comment by L2750558108** [comment]
Whether I'm using a Chinese or English editor, some strange characters that look like Chinese decoding errors appear. I think maybe it's because my computer language is Chinese so the compilation information returned by MSBuild is also Chinese, then the Godot editor decodes it incorrectly and then shows the wrong characters.

**Comment by L2750558108** [comment]
Sorry, I was just wondering if this is in the plan to be solved , without rushing to resolve it as soon as possible.

**Comment by timothyqiu** [comment]
Probably related: #64276

@L2750558108 Can reproduce this error when starting from the `_console.exe` version?

**Comment by L2750558108** [comment]
![image](https://user-images.githubusercontent.com/119792950/212371810-8d64361f-8e49-43e2-80ed-67526f47333a.png)

**Comment by MrBBBaiXue** [comment]
试试复制这些出错的文字，用这个网址[http://www.mytju.com/classCode/tools/messyCodeRecover.asp](http://www.mytju.com/classCode/tools/messyCodeRecover.asp) 看看来源的编码方式和造成错误的编码？

Try copy this corrupt words and using this website, to determine what your computer default encoding (codepage) is, and what encoding methods cause this error?

**Comment by L2750558108** [comment]
![image](https://user-images.githubusercontent.com/119792950/212467111-1b4d933d-096f-40fe-b803-0a1b647b449d.png)

**Comment by MrBBBaiXue** [comment]
<details>
<summary>Reproduce on Godot 4 beta 12 mono:</summary>

![image](https://user-images.githubusercontent.com/17956756/212471253-41feb539-070e-4fc7-b944-9810acabe978.png)

</details>


**Seems Godot decodes UTF-8 strings using GBK:**
![image](https://user-images.githubusercontent.com/17956756/212471451-f65b4218-e534-42c0-ad82-5237b93dd43e.png)


The console output seems follow Windows system display language (or **default CodePage of the shell**), **when using godot in english**, the error still happens:
![image](https://user-images.githubusercontent.com/17956756/212471562-04e96b1a-8399-438c-910d-7790dbd398ba.png)
Running `chcp 65001` before using `console.exe` is not working.

If you select default Windows Display language on the initial setup (OOBE) of Windows to Simplified Chinese, the default codepage will be set to `936 (GBK)`, but in most case of software dev, we uses `65001 (UTF-8)`, **that's the problem that cause the issue**.
Japan `932`, Korea `949`, Chinese Taiwan `950` also uses their specific codepages, that might also cause issue similar to this.

**Comment by paulloz** [comment]
We could consider forcing MSBuild into the same language as the editor.

**Comment by nagilson** [comment]
FYI I am working on a change for MSBuild to use UTF 8 if it's running in the context where `DOTNET_CLI_UI_LANGUAGE` is set. Might fix this for you. https://github.com/dotnet/msbuild/pull/8503
