### ISSUE TITLE
HTTPClient get_status doc description is contradictory.

### ISSUE THREAD

**Issue by romeojulietthotel** [godotengine/godot#7132]
**Operating system or device - Godot version:**
All platforms

**Issue description** (what happened, and what was expected):
The description for HTTPClient.get_status is contradictory. It currently returns an int.
So either this is a doc fix or a code fix. I would rather see a code fix so that get_status() returns a string.

**Steps to reproduce:**

>  **int get_status ( ) const**
> 
> Returns a status string like STATUS_REQUESTING. Need to call poll in order to get status updates.

**Link to minimal example project** (optional but very welcome):

**Comment by vnen** [comment]
`STATUS_REQUESTING` is an integer constant. The problem is in the documentation.
