### ISSUE TITLE
TileSet editor cell's context menu position is incorrect

### ISSUE THREAD

**Issue by nezvers** [godotengine/godot#71327]
### Godot version

Godot 4.0 beta 11

### System information

Windows 10, all renderers, Nvidia GTX1060

### Issue description

The position of the right mouse context menu is correct ONLY on my first display and the Godot editor is fullscreen, in other scenarios the context menu position is off.
Both my displays are 4K.
![image](https://user-images.githubusercontent.com/26794315/212324622-70549e31-372d-4e5d-8723-312414d5a872.png)

### Steps to reproduce

Editing a tileset and clicking with the right mouse clicking on the tileset cell for context menu to appear (Create a tile/ Create alternate tile or delete cell).

### Minimal reproduction project

[TileSet reproduction.zip](https://github.com/godotengine/godot/files/10411935/TileSet.reproduction.zip)

**Comment by KoBeWi** [comment]
Probably related to #37320
