### ISSUE TITLE
The embed mode set for a single window does not work

### ISSUE THREAD

**Issue by L2750558108** [godotengine/godot#71324]
### Godot version

4.0(beta 11) mono

### System information

windows10

### Issue description

The embed mode set for a single window does not work
See this video
[2023-01-13 20-15-02.zip](https://github.com/godotengine/godot/files/10411385/2023-01-13.20-15-02.zip)

### Steps to reproduce

See "Issue Description" for detail

### Minimal reproduction project

An empty project

**Comment by YuriSizov** [comment]
I'm not exactly sure what you're trying to demonstrate here. The "Embed subwindows" property affects subwindows of that window. Your window has no subwindows.

If you want this window to not be embedded into the main window, then you need to change that. Use the `display/window/subwindows/embed_subwindows` project setting.

**Comment by L2750558108** [comment]
I got it wrong. I thought this option meant to set whether the current window is embedded in the parent window or not. Is there any way to make one child of one window embedded in the parent window and the other not?

**Comment by YuriSizov** [comment]
I don't think so, but there is a proposal https://github.com/godotengine/godot-proposals/issues/4741
