### ISSUE TITLE
Sub-windows cannot be dragged in editor and the marquee is not visible

### ISSUE THREAD

**Issue by L2750558108** [godotengine/godot#71323]
### Godot version

4.0(beta 11) mono

### System information

windows10

### Issue description

Sub-windows cannot be dragged in editor and the marquee is not visible.
See this video
[2023-01-13 20-06-39.zip](https://github.com/godotengine/godot/files/10411332/2023-01-13.20-06-39.zip)

This is the check box of the popup node in version 3.x, which disappeared in 4.0 (beta 11). These issues lead to inconvenient development
![image](https://user-images.githubusercontent.com/119792950/212320589-a0b07ef6-7981-40d6-9dfd-923404539e20.png)

### Steps to reproduce

Create a project
Create a Window
Try dragging the window in editor and failed

### Minimal reproduction project

An empty project

**Comment by KoBeWi** [comment]
Duplicate of #56872
