### ISSUE TITLE
Setting transparency on a mesh makes it invisible.

### ISSUE THREAD

**Issue by m4rr5** [godotengine/godot#71333]
### Godot version

4.0 beta 11

### System information

Windows 10

### Issue description

When I create a MeshInstance3D and set the transparency property to anything but 0.0, the mesh disappears completely instead of becoming (partially) transparent. This worked fine up to and including beta 10, and stopped working in beta 11.

In beta 10:
![image](https://user-images.githubusercontent.com/446570/212356065-b47dd6fd-62e7-4bdc-a9c3-11d07a640ce9.png)

In beta 11:
![image](https://user-images.githubusercontent.com/446570/212356105-e2b37703-2f1e-462d-99c9-3f964caf8ac9.png)

### Steps to reproduce

Create a 3D project with a MeshInstance3D and set its transparency property to (for example) `0.5` and then add a world environment, directional light and camera (or simply open the example project and compare it in beta 10 vs 11).

### Minimal reproduction project

Minimal project:
[godot-4-transparency-bug.zip](https://github.com/godotengine/godot/files/10412831/godot-4-transparency-bug.zip)

Or clone:
https://github.com/m4rr5/godot-4-transparency-bug

**Comment by Sslaxx** [comment]
Note that the cube appears using Mobility and Compatibility settings, albeit not transparent.

**Comment by m4rr5** [comment]
As I just saw beta 12 builds showing up on the server (although not announced yet) I tried it there and that does seem to work, so that means this issue is probably fixed already:
![image](https://user-images.githubusercontent.com/446570/212362178-7d243ddd-2941-4d95-b4ae-37decb8aba1d.png)

**Comment by Sslaxx** [comment]
Fixed in Beta 12.

**Comment by Sslaxx** [comment]
In the few minutes since this: https://godotengine.org/article/dev-snapshot-godot-4-0-beta-12

**Comment by Sslaxx** [comment]
Fixed by https://github.com/godotengine/godot/pull/71124
