### ISSUE TITLE
Add custom path option for export template

### ISSUE THREAD

**Issue by HackLinjiuyue** [godotengine/godot#71338]
### Godot version

4.0beta12 offical

### System information

Windows10

### Issue description

I am struggling with keeping my C disk clean, so I think it is a good idea to provide an option for developers and players(maybe?) to choose where they want to store their userdata.

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by YuriSizov** [comment]
Please open a proposal discussion: https://github.com/godotengine/godot-proposals/discussions.

You can make your game write anywhere. The `user://` path is following the specifications of platform vendors and is ensured to be writable. For your custom path you would need to do that yourself.
