### ISSUE TITLE
Don't default the FileSystem pane to expanding every folder

### ISSUE THREAD

**Issue by chanon** [godotengine/godot#7134]
This is a UI/Usability improvement request

In most file explorers (such as Windows Explorer, Mac OS Finder) that have a tree style representation of the directory structure of a file system, they do not default to having every folder expanded.

However godot's FileSystem pane defaults to having every single folder in the file system expanded every time a project is opened. For large projects with complex directory structures, this makes finding a specific folder tedious.

Some people (those with less complex directory structures) may prefer having them all expanded though. Advanced IDEs actually remember the expand/collapse state of their project explorers - which is something that would be a nice improvement to Godot.

**Comment by volzhs** [comment]
Duplicated #796

**Comment by bojidar-bg** [comment]
I would rather edit #796, as it is a "mega-issue", and not as focused as this one...

**Comment by bojidar-bg** [comment]
Actually, thinking about it, it might be an actual dupe. So, closing...
