### ISSUE TITLE
RayCast3D set_target_position does not work as expected

### ISSUE THREAD

**Issue by ViktorEvil** [godotengine/godot#71341]
### Godot version

4.0.beta11

### System information

MacOS Ventura 13.1, M1 MacBook Pro 

### Issue description

Im slowly changing a project from 3.5.1 to 4.0 and the RayCast3D does not set the target position of the ray cast correctly. 

On the 3.5.1 project using ```RayCast3D.cast_to = Vector3()``` the ray is correctly pointing in the direction the player is about to face but using the new ```RayCast3D.target_position = Vector3()``` or ```RayCast3D.set_target_position(Vector3())``` on Godot 4 the ray never points forward or backward. The ray only points left or right

### Steps to reproduce

assign a direction Vector3 to the RayCast3D target_position property and the RayCast does not point the correct way even though the RayCast3D get_target_position says it is.

### Minimal reproduction project

[RayCast3D.zip](https://github.com/godotengine/godot/files/10413742/RayCast3D.zip)
Enabled debug visible collision shapes and use arrow keys to control player

**Comment by ViktorEvil** [comment]
<img width="417" alt="Screenshot 2023-01-13 at 15 54 46" src="https://user-images.githubusercontent.com/4403212/212377820-26bc4324-eb6c-4759-9724-8301fd303052.png">

<img width="417" alt="Screenshot 2023-01-13 at 15 55 18" src="https://user-images.githubusercontent.com/4403212/212377846-b2d74fc2-6d5d-42ac-9457-0a3fb3b0f244.png">

**Comment by Marthog** [comment]
The target position is local to the ray. Since the ray is a child of the player it automatically rotates with the player.

Everything should werk if you set the `target_position` to `Vector3(1, 0, 0)` once in the editor and never update it in code.

**Comment by ViktorEvil** [comment]
That doesn’t work for my usecase as I need the ray cast to check for collision just before the player turns and moves into the next square. 

In 3.5.1 casting the ray to a direction before moving has the desired effect but in 4.0 setting the target position of the ray does not

**Comment by Zireael07** [comment]
Take your 3.5 position vector, which is global, and just do player.to_local(vec) where vec is your original vector.

**Comment by ViktorEvil** [comment]
> Take your 3.5 position vector, which is global, and just do player.to_local(vec) where vec is your original vector.

I tried that but it moves the target position all over the place. 

I thought the change for RayCast3D “cast_to” to “target_position” was just a change of name for 4.0 but it works very different in very basic identical projects

**Comment by ViktorEvil** [comment]
same issue on beta 12

**Comment by Zireael07** [comment]
Why close? Did you find a solution?

**Comment by ViktorEvil** [comment]
It was my own stupid mistake as in the process of moving from 3.5.2 to 4.0 I rewrote the tween nodes from the old system to the new way but I accidentally had the root node rotate instead of the mesh node .I must have rewritten the tween node in 4.0 a dozen times to try and fix it but this morning I decided to recreate the issue in 3.5.2 with a stripped down project and realised what I had done. I could kick myself as this wasted a few days.
