### ISSUE TITLE
Godot 4 beta12: "Building project" window is using a separate theme from the rest of the editor.

### ISSUE THREAD

**Issue by Marigem** [godotengine/godot#71351]
### Godot version

Godot 4 beta 12

### System information

Windows 10

### Issue description

![tttttt](https://user-images.githubusercontent.com/43501741/212407759-2e3cfa93-c9c1-4224-a118-2d236b0c5318.png)

### Steps to reproduce

Run a project in Godot 4 beta 12

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
Saw this too with import dialogs, I suspect #71209 caused it. @bruvzg

**Comment by YuriSizov** [comment]
That's a good suspicion. The window that holds the editor node doesn't have the editor theme, children of the editor node do. This is annoying and will be properly fixed later, but I guess we could also assign the current theme to the window for now.

**Comment by bruvzg** [comment]
> I suspect https://github.com/godotengine/godot/pull/71209 caused it.

I can reproduce it (and it makes sense that it won't get theme updates), but it was working with a correct theme somehow (at least on macOS and for export process), so something else might have changed as well.
