### ISSUE TITLE
Suggest project reloading after the changes in settings that require it

### ISSUE THREAD

**Issue by etareduction** [godotengine/godot#71355]
### Describe the project you are working on

I think it is a general feature and is applicable to any project.

### Describe the problem or limitation you are having in your project

I've been stuck for a while trying to grasp why editing C# Project Directory (project/c#_project_directory) setting has no effect. Later on just through trial and error I've figured out that it only applies after re-opening the project.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a popup window that appears when you change such a setting that suggests reloading the project.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When the user changes a setting in menu that requires project reload to take effect (such as C# Project Directory), show modal window that asks if he wants to reload the project and describes why it is necessary.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, i don't think so. The problem is mostly due to the lack of knowledge about which setting does require project reload to take effect.

### Is there a reason why this should be core and not an add-on in the asset library?

I think it is vital to the core user experience of the editor.

**Comment by YuriSizov** [comment]
Transferred to issues because this feature already exists in the form of the `PROPERTY_USAGE_RESTART_IF_CHANGED` hint and `ProjectSettings::set_restart_if_changed`. It just doesn't seem to be used for that particular setting.

The setting was removed or renamed in 4.0, btw, but this can still be fixed in 3.x.

**Comment by akien-mga** [comment]
Fixed by #71358.

**Comment by etareduction** [comment]
Thanks!
