### ISSUE TITLE
Center of mass offset for RigidBody and RigidBody2D.

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#7136]
Currently the center of mass is always at the origin point of the RigidBody. There is no way to change the center of mass without moving all of the collision shapes and visual nodes so that the origin is offset.

I would like to have a function to offset the center of mass away from the origin without having to move everything around.

**Comment by reduz** [comment]
This was planned for 3.0

**Comment by reduz** [comment]
this was added in 3.0

**Comment by Xrayez** [comment]
This was potentially fixed for 3D case in #7426 but not for RigidBody2D.

@m4nu3lf Can this be done for 2D case as well? I've tried to translate your code to 2D but my knowledge of physics is pretty much basic. I've successfully recomputed the center of mass based on shapes' origin and other stuff but I can't figure out how to integrate it all. Any pointers?

**Comment by SteveSmith16384** [comment]
I'm on 3.4.2 and I can't see the option?  The docs at https://docs.godotengine.org/en/stable/classes/class_rigidbody2d.html still say "The center of mass is always located at the node's origin without taking into account the CollisionShape2D centroid offsets."

**Comment by Calinou** [comment]
Custom center of mass was added in both 2D and 3D in 4.0 by https://github.com/godotengine/godot/pull/49610, but it won't be backported to `3.x` as it involves backwards-incompatible changes.
