### ISSUE TITLE
GDScript: properties setter and getter not working with @onready annotation

### ISSUE THREAD

**Issue by nullMolotov** [godotengine/godot#71372]
### Godot version

v4.0.beta12.official

### System information

Windows 8.1, Forward+, NVIDIA GTX 650

### Issue description

setter and getter functions of a property dont work on Node's _ready execution even using @onready annotation

i don't know if this is intended but @onready annotation is intended to do that

```
# Doesn't work in this way
@onready var value : int = 0:
    set(new):
        value = new
        print("value changed")
```

```
# With this way it does work, so it executes value's setter
 var value : int:
    set(new):
        value = new
        print("value changed")

func _ready():
    value = 0 
```

### Steps to reproduce

@onready var value : int = 0:
    set(new):
        value = new
        print("value changed")

### Minimal reproduction project

N/A

**Comment by Sslaxx** [comment]
Are you saying that the first code snippet doesn't print "value changed", which is what I think it should do? Being initialised with a setter means the setter being called in initialisation.

**Comment by nullMolotov** [comment]
what im trying to say is that assigning value inside the _ready function executes the property's setter, but assigning it with the @onready annotation doesn't do that, and @onready is intended to assign values on Node's _ready call

**Comment by KoBeWi** [comment]
Setters are never called with default value.
Also onready setters aren't really supported, see https://github.com/godotengine/godot-proposals/issues/325
`@onready @export` var will call the setter before node enters tree.

Poor @onready btw. Unfortunate name.

**Comment by YuriSizov** [comment]
Closing in favor of the linked proposal.
