### ISSUE TITLE
Can't update Android editor without uninstalling previous version since 3.5.2rc2 due to modified signature

### ISSUE THREAD

**Issue by Raffa064** [godotengine/godot#71378]
### Godot version

3.5.2 rc2

### System information

Android 10, 64bits

### Issue description

Due to the new keystore used in the godot, I can't install godot 3.5.2 rc2 without lost my old data... please reupload with the old keystore

### Steps to reproduce

Install the godot 3.5.2 rc1, and after it, try to install the 3.5.2 rc2.

### Minimal reproduction project

The problem is not on a project.

**Comment by clayjohn** [comment]
CC @m4gr3d

**Comment by m4gr3d** [comment]
The Godot Editor was published to the Play store, so you should be able to get that version. By installing from the Play store, it'll ensure you automatically get updates without any loss of data.

https://play.google.com/store/apps/details?id=org.godotengine.editor.v3

Unfortunately, you may have to uninstall the current version to download the Play store version.
