### ISSUE TITLE
Possible tilemap problem when loading in chunks with threads

### ISSUE THREAD

**Issue by alberto-mco** [godotengine/godot#71388]
### Godot version

Godot 4.0 - [all betas i tried since beta 1]

### System information

Windows 11

### Issue description

I'm making a survival 2d rpg game (open world like minecraft) and when loading a tilemap in chunks, to make an open world, i found that sometimes tiles are not painted, but it detects his collision layers correctly.

I made an example that generate a map in chunks, from a noise (using the same seed for this example), and sometimes, tiles are not fully painted. Notice that i made all grass connection possiblities.

I don't know if it's a truly bug or i'm making something that makes this behavior. In my game, the player can detect the tile grass when it's not painted, that's the reason i think that it's a bug, because it's not painted but it's there.
![Missing tiles](https://user-images.githubusercontent.com/70795945/212468349-1592670b-8296-48dd-bf52-eedc9a56d4da.png)
![OK tiles](https://user-images.githubusercontent.com/70795945/212468350-a58738c7-bfc2-4eb8-9886-6f0b8397cd67.png)

### Steps to reproduce

Just play the main_scene.tscn, and sometimes, the tiles are not painted in the border between Sea and Grass.

### Minimal reproduction project

[report_tilemap_chunks.zip](https://github.com/godotengine/godot/files/10417170/report_tilemap_chunks.zip)

**Comment by furroy** [comment]
I have same issue with TileMap terrains randomly not painting all the tiles. Plus it was so slow causing massive lag spikes, I split the chunk/tilemap updates into their own threads, and now it will randomly crash and close the game with no errors shown.
[Godot4Crash.zip](https://github.com/godotengine/godot/files/10702669/Godot4Crash.zip)

**Comment by furroy** [comment]
I made some progress on this, it would seem that TileMaps are just straight up not thread safe in any fashion. Not that any of the docs any where mention this pitfall. You can't interact with them from multiple threads without it locking up/crashing eventually.  I made a double buffered TileMap in Godot3 to get around this, and it works fine. I briefly tried this same approach in Godot4 and it is still laggy/crashes.  I'll stick with Godot3 for the time being.

**Comment by alberto-mco** [comment]
I think the same, it's not thread safe, and that's a problem to make open world games. In my example, i just have one thread to load the chunks one by one, and sometimes they also crash, missed to draw some tiles (but not its collision layers), or just determine other tile. In my case, i converted my game from godot 3 to godot 4 at beta 1, and this works right with the update_bitmask_region in godot 3. In my case i can't make a come back to use godot 3 in this project, because my project is almost finished in godot 4.

**Comment by AThousandShips** [comment]
This is not a bug but a thread safety issue, see [#75317 (comment)](https://github.com/godotengine/godot/issues/75317#issuecomment-1483819778) for some details and a solution to make this work

**Comment by AThousandShips** [comment]
Are you loading them in outside the tree? Because you can't manipulate them from a thread when they're in the tree.

**Comment by alberto-mco** [comment]
> Are you loading them in outside the tree? Because you can't manipulate them from a thread when they're in the tree.

In my game i only have 1 tilemap, and chunks calculate the terrain with a noise and use set_cell_terrain_connect (in the example is without call_deferred, but also i tried with call_deferred and the performace decrease... making the player movement to stop until the chunk is loaded). I use only 1 tilemap because the grass need to be correctly connected, because the grass has a border when it's near to the water for example, and maybe the neirbor chunk has grass and the other chunk has the grass also. Using 2 tilemaps i have a grass border, and that's not correct... I understand what you say, to use 2 or more tilemaps, but i think that its a problem to match the grass border. I don't know if i explained correctly, sorry

**Comment by alberto-mco** [comment]
a great solution maybe is a mix of your suggestion and my idea to have only one tilempa. The chunk load the tilemap portion, as you said, and when it's ready, i'll try to joing and call_deferred (set_cell_terrain_connect) only with the coordenates of the chunk border, the other cells i'll set exacly has the chunk said. That's will force the main tilemap to only refresh these borders... I think that this will work

**Comment by AThousandShips** [comment]
I'm not saying to use `set_cell_terrain_connect` on deferred though, I'm saying to have the chunk of the map not in the tree, that is not as a child in the game tree, and call the function directly on it, and then add it to the scene

**Comment by alberto-mco** [comment]
> I'm not saying to use `set_cell_terrain_connect` on deferred though, I'm saying to have the chunk of the map not in the tree, that is not as a child in the game tree, and call the function directly on it, and then add it to the scene

Yeah i know what you mean, you said to have N tilemaps, but when i add the tilemap to the container, it will not match the grass terrain with the other tilemaps, for example:

1. Create a tilemap and add it to the scene
2. Fill a grass square of 9x9 in this tilemap, then you will have 1 normal grass and 8 grass borders (the image is different)
3. Add a second tilemap to the scene
4. Repeat the step 2, but the grid of 9x9 to be near of the first
5. Then you'll have 16 borders and not 14.

Your solutions will work if i don't have an image of the grass border, just a grass tile

**Comment by alberto-mco** [comment]
Ok thanks, sorry for the missunderstood

**Comment by AThousandShips** [comment]
I would suggest turning to the [community channels](https://godotengine.org/community) for this, as it is not a bug, and this isn't a support forum but a bug reporting tool, if you have any issues with the referenced documentation please comment on the other issue

**Comment by furroy** [comment]
what i ended up doing was this: do all your changes in a tilemap not in the tree. whenever you deem it's a good time to update, duplicate that tilemap and swap out the live tilemap in the tree with the duplicate.
