### ISSUE TITLE
The scene root node cannot be set to a unique name

### ISSUE THREAD

**Issue by L2750558108** [godotengine/godot#71387]
### Godot version

3.5.1mono

### System information

windows10

### Issue description

The scene root node cannot be set to a unique name
This is the right-click menu of the node that is not root node
![image](https://user-images.githubusercontent.com/119792950/212468076-8d3df11e-8962-4f39-8b44-0d95b7c04c19.png)
This is the right-click menu of the root node
![image](https://user-images.githubusercontent.com/119792950/212468100-62aba4e7-ef90-4dd9-af12-523c7c81aef6.png)

### Steps to reproduce

See "Issue Description"

### Minimal reproduction project

An empty project

**Comment by akien-mga** [comment]
That's not a bug. Unique name is unique *in the scene*. In the scene, the root node isn't referenced by name, it's the root (start of the path).

**Comment by L2750558108** [comment]
But when it is instantiated to other scenes, it is applied by name

**Comment by akien-mga** [comment]
You should be able to give the instantiated scene a unique name in its parent scene.

**Comment by L2750558108** [comment]
I need to make any child node in the instantiated scene quickly get the root node of the instantiated scene, so I want to set the root node to a unique name before instantiation. If this is the wrong idea, is there any other way to achieve this? GetTree(). GetRoot() gets the root node of the entire application

**Comment by akien-mga** [comment]
Use the `owner` property for this.
