### ISSUE TITLE
Feature: Realtime Collaboration 

### ISSUE THREAD

**Issue by RobotUnderscore** [godotengine/godot#7139]
It's a huge task to build, but it would be amazing if you could have multiple users edit a single Godot project at once as opposed to using Git.

It would be similar to Google Docs, where any changes made in a project would update instantly across all connected users.

To avoid having to invest in servers for this, the host user could port forward their IP and share it with other users to connect and collaborate.

This can be seen in an engine called Superpowers HTML5.

**Comment by reduz** [comment]
Godot is designed with the total opposite mindset. It lets you split your
game in scenes, so each part of the team does what they do best, and each
owns their owns scenes (game designer, programmer, artist, etc). This makes
real time collaboration pointless by design.

**Comment by RobotUnderscore** [comment]
Alright, that clears things up.

**Comment by iniyanijoseph** [comment]
> Alright, that clears things up.

I guess, but it would still be nice to have that functionality. It would make it more accesible for all people

**Comment by Calinou** [comment]
@iniyanijoseph Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.
