### ISSUE TITLE
GDExtension: Global enum are not marked as bitfield in extension_api.json

### ISSUE THREAD

**Issue by touilleMan** [godotengine/godot#71397]
### Godot version

4.0beta12

### System information

all

### Issue description

In `extension_api.json` we have some function that uses parameter typed after a global enum and display it as a bitfield:
```js
{
	"name": "set_button_mask",
	"is_const": false,
	"is_vararg": false,
	"is_static": false,
	"is_virtual": false,
	"hash": 3950145251,
	"arguments": [
		{
			"name": "mask",
			"type": "bitfield::MouseButtonMask" // bitfield prefix here !
		}
	]
},
```

However the global enum's own definition doesn't mention it is a bitfield:
```js
{
	"name": "MouseButtonMask",
	// No "bitfield" field here !
	"values": [
		{
			"name": "MOUSE_BUTTON_MASK_LEFT",
			"value": 1
		},
		{
			"name": "MOUSE_BUTTON_MASK_RIGHT",
			"value": 2
		},
		{
			"name": "MOUSE_BUTTON_MASK_MIDDLE",
			"value": 4
		},
		{
			"name": "MOUSE_BUTTON_MASK_MB_XBUTTON1",
			"value": 128
		},
		{
			"name": "MOUSE_BUTTON_MASK_MB_XBUTTON2",
			"value": 256
		}
	]
},
```

On the other hand, the non-global enums (i.e. the ones defined as part of a class) have this `is_bitfield` field.
So I guess we should add it to global enum too.

### Steps to reproduce

n/a

### Minimal reproduction project

n/a

**Comment by touilleMan** [comment]
Correcting this is a bit annoying though: the bitfield information is not connected to the type but to the callsite (if `Foo` is a global enum bitfield, it is declared as a regular struct, then used as `Bitfield<Foo>`)
https://github.com/godotengine/godot/blob/60d031777b2a922cba03210181c9ba7ad3a6f3ab/core/input/input.cpp#L746-L748

**Comment by raulsntos** [comment]
You should be able to check if the enum is bitfield with `CoreConstants::is_global_constant_bitfield(i)`.

**Comment by touilleMan** [comment]
@raulsntos thanks for the tip ! I've submitted PR #71400 then ;-)
