### ISSUE TITLE
Debug visuals of Node3d descendants created in tool script don't work

### ISSUE THREAD

**Issue by RedwanFox** [godotengine/godot#71408]
### Godot version

4.0.dev (60d031777b2a922cba03210181c9ba7ad3a6f3ab)

### System information

Windows 11

### Issue description

Nodes that have debug visuals that should be visible in 3d scene display them only if added via editor. If node is added to tree via code of tool script it won't show any debug visuals.

![bug_report](https://user-images.githubusercontent.com/1223739/212483327-8257e90b-e323-49dc-9ad3-f6a6bf872922.png)

### Steps to reproduce

1. Create scene with Area3D with collisionshape3d and sphereshape3D,
2. Create tool script extending Area3D with collisionshape3d and sphereshape3D added through core on `_ready`. 
3. Place tool script node in the same scene beside original hierarchy.
4. Witness no debug visuals in 3d scene for tool script node

### Minimal reproduction project

[reproduce_no_debug_visuals_bug.zip](https://github.com/godotengine/godot/files/10418201/reproduce_no_debug_visuals_bug.zip)

**Comment by Zireael07** [comment]
What happens if you set the owner of the newly added nodes to root?

**Comment by RedwanFox** [comment]
I have forgot to add ownership to code collisionshape3d in demo project. 

>What happens if you set the owner of the newly added nodes to root?

It goes like this:
1. If CollisionShape3D owner is tool script **no debug visuals**
2. If CollisionShape3D owner is scene root **debug visuals appear**. But there are problems.

Problems:
1. Setting owner to external object is strange. My custom script is already in tree and serialized with scene. 
1. CollisionShape3D appears as node in scene tree even if it is marked as Internal.
2. It exposes internal api and can be deleted by user from editor. This can break behavior. I wanted my type as script to expose only needed configuration. 
3. Thus it is saved to serialized scene and on every project reload will duplicate. It must be handled manually by user.

**Comment by Zireael07** [comment]
Yeah, I wasn't saying it was a solution, I was just wondering whether it has an effect.

**Comment by RedwanFox** [comment]
Sorry, I didn't mean to sound harsh:( I have merely described consequences. 
After shuffling some code around after testing your proposal somehow everything started working even after setting owner to self. I think the issue should be closed.
