### ISSUE TITLE
Error: Node3DEditorViewport::_get_drag_data_fw: Method not found.

### ISSUE THREAD

**Issue by TokisanGames** [godotengine/godot#71412]
### Godot version

Godot 4 Beta12

### System information

Windows 11/64, RTX 3070, Vulkan

### Issue description

Clicking and dragging in the viewport produces errors:

`ERROR: Error calling forwarded method from 'get_drag_data': 'Node3DEditorViewport::_get_drag_data_fw': Method not found.
   at: (scene/gui/control.cpp:1851)`

### Steps to reproduce

* Open an empty 3d scene
* Draw a selection box in the viewport

### Minimal reproduction project

n/a

**Comment by mohsenph69** [comment]
I have the same problem in linux Manjaro

**Comment by mohsenph69** [comment]
This issue still exist even in godot beta 13
Can someone do something because this problem preventing me to develop my plugin, and it is not working anymore

**Comment by TokisanGames** [comment]
Kobewi did do something by providing a fix. You can build the engine off of his PR to continue development until it gets merged into the master branch.

https://stackoverflow.com/questions/27567846/how-can-i-check-out-a-github-pull-request-with-git

**Comment by KoBeWi** [comment]
You can download build artifacts to use the PR without compiling it: https://docs.godotengine.org/en/stable/community/contributing/testing_pull_requests.html#downloading-a-compiled-build
Although it's not the latest Godot version, but from the time the PR was opened.

**Comment by mohsenph69** [comment]
Thanks
It is working now
