### ISSUE TITLE
Cannot change existing value in a constant dictionary

### ISSUE THREAD

**Issue by b0z1** [godotengine/godot#71413]
### Godot version

4.0-beta12_win64

### System information

Windows 10, 64 Bit

### Issue description

The following code throws an error "Cannot assign a new value to a constant."

```
const _static = { initialized=false, config={} }

static func _initialize():
	_static.initialized = true
```

In Godot 3 this worked and i used it mainly for singletons. So i depend on it.
According to the documentation this should work.

Link: https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_basics.html
Statement: 
```
Since objects, arrays and dictionaries are passed by reference, constants are "flat". This means that if you declare a constant array or dictionary, it can still be modified afterwards. They can't be reassigned with another value though.
```

### Steps to reproduce

1. Create an gd script
2. Define a const dictionary with some initial values
3. Try to change those values
4. Error

### Minimal reproduction project

See reproduction steps

**Comment by b0z1** [comment]
My guess is this MR broke it: https://github.com/godotengine/godot/commit/e6c443a353cb3923b80f4fa112667a08159ee971

**Comment by b0z1** [comment]
Okay after debugging the issue further, this MR broke it: https://github.com/godotengine/godot/commit/5e2ac1a31ee34842438a3a76c54f6a15df77bb95

**Comment by akien-mga** [comment]
This was changed on purpose, see #71051.

The documentation needs to be updated.

We plan to add support for proper static variables in the future.
