### ISSUE TITLE
Null SceneTree root before and after calling SceneTree::init

### ISSUE THREAD

**Issue by FinleyPan** [godotengine/godot#71415]
### Godot version

3.5.stable

### System information

Android 12, GLES 3.0, Adreno (TM) 650

### Issue description

I am new to Godot and want to integrate it into our system on Android, key code lines are as follows:
```cpp
// foo.cpp
if(Main::start()){
  SceneTree *st = Object::cast_to<SceneTree>(m_MainLoop);
  LOGI("scene tree: %p, root: %p", st, st->get_root());
  m_MainLoop->init() //calling SceneTree::init
  LOGI("scene tree: %p, root: %p", st, st->get_root());
...
}

// scene_tree.cpp
void SceneTree::init(){
  ERR_FAIL_COND(!root);
  LOGI("this scenetree: %p, get_root: %p, root: %p", this, get_root(), root); //print these to check it is the same scenetree
  initialized = true;
  root->_set_tree(true);
  MainLoop::init();
}
```
what printed astonished me a lot:
<img width="937" alt="企业微信截图_05d40140-cb37-40f3-898e-8a9c165073b3" src="https://user-images.githubusercontent.com/26212839/212485897-2dca482b-dde3-469b-b320-662a442ad332.png">
**`root` of scenetree is null before calling `SceneTree::init` but owns a valid address immediately entering the method**. It seems there are no any codes to assign a value to root. Besides, `SceneTree::get_root` stills return null after calling `SceneTree::init`. Who can help me out?

### Steps to reproduce

Described as above

### Minimal reproduction project

[RvMaterial.zip](https://github.com/godotengine/godot/files/10418377/RvMaterial.zip)

**Comment by akien-mga** [comment]
Did you find a solution?
