### ISSUE TITLE
ScrollContainer or GraphEdit.get_children() returns internal child nodes, unexpected by the user

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#7142]
**Operating system or device - Godot version:**
Godot 2.2 alpha with current master

**Issue description** (what happened, and what was expected):
ScrollContainer.get_children() returns also it's sub component like HScrollBar and VScrollBar.
I expected just it's children shown as in nodes Scene tree of editor.
This can cause crash if remove all children of ScrollContainer.

```gdscript
for node in scroll_container.get_children():
    node.queue_free()
```

```gdscript
for node in graph_edit.get_children():
    node.queue_free()
```

**Comment by leezh** [comment]
Looking at `scene/gui/scroll_container.cpp` it seems like it was set up as such to handle ScrollBar input and rendering.

A workaround would be:

    for node in scroll_container.get_children():
        if node extends HScrollBar:
            continue
        if node extends VScrollBar:
            continue
        node.queue_free()

**Comment by volzhs** [comment]
I know how to workaround, and I found it by my mistake.
But game was crashed silently and I should run Godot editor with Qt debug to find it.

**Comment by neikeq** [comment]
Perhaps Container should have a method that derived classes can override to return the expected children.

**Comment by bojidar-bg** [comment]
Perhaps we might make some nodes "hidden" and not shown in `get_children`, unless one uses `get_children(include_hidden = true)`?

**Comment by volzhs** [comment]
I like what @neikeq suggested.
if we really need to expose hidden nodes, we can do it by `get_scrollbar_vertical` or something.

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by DualMatrix** [comment]
Still relevant in 3.1 master

**Comment by Anutrix** [comment]
Any updates?
