### ISSUE TITLE
Lock icons are not affected by CanvasLayer

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#7143]
Tested on Godot 2.1 and 2.1.1, Windows 10, 64 bits

Repro:
1) Create a CanvasLayer and set its scale to (3, 3)
2) Create a Sprite as child of CanvasLayer, with a texture on it
3) Move the sprite off the origin, then lock it
4) Observe the lock icon is off, as if it was not affected by the scale.

I expected the lock icon to be shown on the sprite as usual, but its size and rotation should not be affected (just like the rectangular handles of the sprite).

Example project:
[LocksAndCanvasLayers.zip](https://github.com/godotengine/godot/files/598933/LocksAndCanvasLayers.zip)

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Zylann** [comment]
Still happens in Godot 2.1.5 rc1.
Happens too in Godot 3.0.2.

I also noticed that even when not locked, moving sprites in a scaled CanvasLayer makes them move faster than intented.

**Comment by DualMatrix** [comment]
Tested in master. The lock now behaves as expected.

**Comment by akien-mga** [comment]
Thanks, closing as fixed.
