### ISSUE TITLE
【Godot 4.0 beta.10】How to hide Tab symbols and line breaks in Bbcode text？

### ISSUE THREAD

**Issue by Atem1995** [godotengine/godot#71448]
### Godot version

4.0 Beta 10

### System information

Window10

### Issue description

How to hide Tab symbols and line breaks in Bbcode text？I didn't find the relevant settings, even in the theme settings; I think this is a rendering bug, so I submit it.
![捕获](https://user-images.githubusercontent.com/52338846/212522701-8aefb1d7-7e36-4b31-a147-34fa7cf38bd9.PNG)

### Steps to reproduce

略

### Minimal reproduction project

略

**Comment by akien-mga** [comment]
Please provide a minimal reproduction project as asked, or at least detailed steps to reproduce the example in the screenshot.

**Comment by Atem1995** [comment]
Oh, I think it's my problem. The font I used caused this situation. Unifont.
