### ISSUE TITLE
'Vulkan: Did not create swapchain successfully' causing OS lock-up

### ISSUE THREAD

**Issue by satscape** [godotengine/godot#71453]
### Godot version

4.0 beta 12 Mono

### System information

Linux Mint 21.1

### Issue description

In the _process() I'm altering the Camera3D's Fov and it mostly works (see code below), but then freezes the game and locks up the OS,
Examining the log there are millions of these lines:
`USER ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: swap_buffers (drivers/vulkan/vulkan_context.cpp:2299)
USER ERROR: Vulkan: Did not create swapchain successfully.`

Here's the beginning of the log:
Godot Engine v4.0.beta12.mono.official.3c9bf4bc2 - https://godotengine.org
Vulkan API 1.3.224 - Using Vulkan Device #0: NVIDIA - Quadro K2200
[Lots of the error above here]

If you need anything else, let me know.

### Steps to reproduce

In the _process()...Attached to a Camera3D  "zoom_in" is mouse wheel input
`if (Input.IsActionJustReleased("zoom_in") && Fov > 10f) {
      Fov -= (float)delta * 200;
    }`
**UPDATE**: I changed the code to translate the camera instead of zooming the lens and it's still having this issue.
Also: Changing the renderer from 'Forward+' to 'compatibility' or 'mobile' is a workaround fix.

### Minimal reproduction project

Please run the attached project, use A and D to move left and right and mouse wheel to zoom in and out.
When I was creating this project it seems to need the environment rendering effects on the Camera3D to cause the lockup, turning those off seems to be stable. Also not using the Forward+ renderer fixes things too.
[Bug71453.zip](https://github.com/godotengine/godot/files/10425976/Bug71453.zip)
You might have to stop and re-run a few times,I just re-tested it after a reboot and it took three attempts before locking up.

**Comment by Calinou** [comment]
@satscape Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by satscape** [comment]
Now on 4.0.3 stable using Minimal reproduction project
When SDFGI is enabled I get intermittant lock up with lots of these errors,maybe the same issue?
`E 0:00:23:0672   swap_buffers: Vulkan: Cannot submit graphics queue. Error code: VK_ERROR_DEVICE_LOST
  <C++ Error>    Condition "err" is true. Returning: ERR_CANT_CREATE
  <C++ Source>   drivers/vulkan/vulkan_context.cpp:2357 @ swap_buffers()
`
It could be a faulty card, I only have one game that uses Vulkan and that can be a bit flaky. Will try to test on another machine, but thought I'd drop this here. Hope it helps.

**Comment by Calinou** [comment]
Consolidating in https://github.com/godotengine/godot/issues/71929.
