### ISSUE TITLE
Recursion detected, unable to assign resource to property.

### ISSUE THREAD

**Issue by gnenux** [godotengine/godot#71451]
### Godot version

4.0-beta12

### System information

Windows11 Vulkan API 1.2.0 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1080

### Issue description

Can not assign "SpriteFrames" resource file to SpriteFrames attribute in custom resource file, it alert "Recursion detected, unable to assign resource to property."

### Steps to reproduce

Please look uploaded project. try assign new_sprite_frames.tres to frames in custom_res.tres.

### Minimal reproduction project

[GodotCustomRes.zip](https://github.com/godotengine/godot/files/10419770/GodotCustomRes.zip)

**Comment by akien-mga** [comment]
Might be fixed by https://github.com/godotengine/godot/pull/71229, needs testing.

**Comment by akien-mga** [comment]
Tested, and confirmed fixed by #71229.
