### ISSUE TITLE
Methods get_children() and get_child_count() does not work on TileMap with scenes in it

### ISSUE THREAD

**Issue by seppoday** [godotengine/godot#71469]
### Godot version

4.0 beta 12

### System information

Windows 10

### Issue description

Using get_children() on tilemap that has scenes in it (that are even visible in remote view) returns empty array. Similar for get_children_count() that returns 0.
![image](https://user-images.githubusercontent.com/62170071/212553920-99651167-ed52-435e-a8cd-bcbf46502a7d.png)

### Steps to reproduce

-

### Minimal reproduction project

-

**Comment by KoBeWi** [comment]
You need to wait 1 frame before printing the nodes.
