### ISSUE TITLE
Making a resource Local to Scene seems to be ignored for Next Pass materials

### ISSUE THREAD

**Issue by blackears** [godotengine/godot#71467]
### Godot version

v4.0.beta12.official [3c9bf4bc2]

### System information

Windows 10, GLES 3, 

### Issue description

I'm trying to create a two pass material where the depth buffer is drawn first and then a material with translucency is drawn on top of it (this is to avoid drawing some of the mesh's internal faces). The shader itself works fine, but I run into trouble when I try to instance my scene with the shader inside another scene. I'd like to be able to control the material attributes for each instance independently, but this not happening. The attributes I set on any one instance are immediately replicated on all other instances. 

The recommended way to handle this is to set the material resource to be Local To Scene, and that works for me if I only set the root material. However, I need to set the attributes of the second material in the Next Pass slot and Godot seems to be ignoring the Local To Scene flag in this case. How can I get my instances to display different opacity values in their materials?

The test case is for Godot 4.0.beta12, but I am having the same trouble in Godot 3.5.

### Steps to reproduce

Probably faster to just open the attached project.  In a nutshell:

Create a new scene.  
Add a MeshInstance3D to it.
Create a new VisualShader material in the material's Surface Material Override slot.  Set it to be Local To Scene.
Create a StandardMaterial3D in the Next Pass slot of the first material you created.  Set it to be Local To Scene.
Edit the properties of the second material to be sure you can see the effect of changes in the viewport.
Save this scene with the name Pillar.
Create a GDScript on the root node that exports a float variable.  Have the script update the second material in the _process() loop to copy the exported value into a property of the second material.

Create a new scene.
Create two instances of the Pillar scene in the new scene.
Set the exported parameter to different values for the two different Pillars.
Run the game.

I would expect the two instances to draw their materials independently, but I am seeing the second material being drawn using the properties I set for the second.

### Minimal reproduction project

[MaterialsInstanceTest.zip](https://github.com/godotengine/godot/files/10420511/MaterialsInstanceTest.zip)

**Comment by RedMser** [comment]
In your MRP, the local to scene checkbox was not set for the next pass material:
![image](https://user-images.githubusercontent.com/5117197/212979691-e42f269a-f7ee-4b69-b4b9-0a511062c2d0.png)

Enabling it makes the MRP work as expected: 
![image](https://user-images.githubusercontent.com/5117197/212979340-4c8b18ad-cbc7-4c83-b3d4-a878fa70b821.png)

Local to scene only works if all resources have it enabled, recursively in the chain (so the mesh's own material, and the next pass material).
