### ISSUE TITLE
This is a feedback/report bugs for Godot 4.x Android version, Running on Android 12 Tablet

### ISSUE THREAD

**Issue by johnaderson** [godotengine/godot#71476]
### Godot version

4.0 beta 12 Godot 4 Android Version App

### System information

Android 12, Vulkan Api 1.1.177, GPU: Mali-G72, CPU: Exynos 9611 10nm,  Device: Samsung Galaxy Tab S6 Lite 10.4"

### Issue description

1: Godot 4 on Android version Must be fixed and improvement, I know is an Experimental application but...

Have a lot pontetional to make a games for Android Device, I have made alot games for my phone using Godot 3 "beta 3.apk" only on my android tablet.

2: This feedback, I will post it through four images only. I made it is simple as i could for better explanation with a little funny way.

![1673767677-456652-01-feedback-bug-report](https://user-images.githubusercontent.com/122747505/212562222-0f0e5cd2-3bd2-4cf1-ab36-30b9df6ebaba.png)
![1673767678-894679-02-feedback-bug-report](https://user-images.githubusercontent.com/122747505/212562251-9b0b768a-9ed0-43e5-9fa0-bcbb105365a5.png)
![1673767680-672427-03-feedback-bug-report](https://user-images.githubusercontent.com/122747505/212562277-cd27c5a4-ddb8-49a7-a970-7729fd212f15.png)
![1673767683-15423-04-feedback-bug-report](https://user-images.githubusercontent.com/122747505/212562339-b6b78922-4027-4d32-a67e-07fc072e3486.png)

I love to use godot 4 on my android tablet, I don't have a PC or Laptop, But I know how I can export my project into apk or abb bundle. Soon I will make a image tutorial on how you can export your project on godot editor from android tablet. So yes godot 4  have a lot potential. 🙂👍

### Steps to reproduce

1: When I'm import 3d model rigged gbl the mesh of model splited like spiked see above 2nd image.

2: When I trying to open "Show in File manager" godot 4 on android is crashing. see above my 3rd image for explanation I give.

4: When I'm closing the running project inside the godot editor, the godot is crashing. See above my 4th image for explanation I give. 

This bugs I exclusive mentioned for godot 4  editor on android version. Not for Desktop version. Thanks. Need to be fixed.😔

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Regarding the model rendering issue, please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by johnaderson** [comment]
The "crash on quitting project" issue is already reported in #61611.
> 
> > But I know how I can export my project into apk or abb bundle.
> 
> Exporting projects isn't posible on Android, as you can't run the Android SDK tools on Android itself (when targeting up-to-date Android versions at least).

For the "crash on quitting project" if remember well in Godot 3 Beta 3.apk they haved fixed this problem when i was using it. why not? same for godot 4 editor also?

Yes on this Beta 12 you can't export a apk or aab app 

but in godot 4 beta 4.apk or beta 6.apk i could it, 

 I just download only "build tools" and "platforms tools" of linux version 
then I set up sdk in godot 4 beta 4 or beta 6 i don't remember which one of version i used 

and i was able to expoted into apk but sadly the apksinger of linux it was not reconized on Godot 4 beta 6 or in Godot 3 Beta 3 which i used also. 

expoted as unsigned version then i signed with apk tool for android .

Too bad for Beta 12 it has alot pontetional. 

ok nevermind i will consider to buy Desktop Pc only for Godot 4. bc i love it, godot it's so good game engine. thanks for the info you provide to me
