### ISSUE TITLE
Apk file not generated  (Compiling for android)

### ISSUE THREAD

**Issue by EdwardAngeles** [godotengine/godot#7148]
**Operating system - Godot version:**
Ubuntu 15.10 / Godot 2.1

**Issue description**
I'm compiling for Android and everything since to go well, I don't get any major error. Even though, I don't get .apk file in the bin directory as the [docs](http://docs.godotengine.org/en/stable/reference/compiling_for_android.html) says.

I'm really clueless about what to do here... :/

Edit: I've notice that compiling it again generates the file bin / libgodot.android.opt.armv7.neon.so. Which shouldn't happen with this new way of compiling...

**Comment by volzhs** [comment]
There is https://godotengine.org/qa/ for question.

**Comment by EdwardAngeles** [comment]
I'm reporting an issue.

**Comment by akien-mga** [comment]
The APK goes in `bin/`, so if it's not there you probably missed a step or it failed.

**Comment by akien-mga** [comment]
Please give the exact commands you used and the log output, otherwise we can only assume you made a mistake.

**Comment by EdwardAngeles** [comment]
The documentation used to say `./gradlew` for building, I checked just now and it now says `./gradlew build`.

It was fixed by this commit [commit](https://github.com/godotengine/godot-docs/commit/7400cce692f614cb856434dbdfcbfc8f9597c2c4).

I got the .apk thanks! :D
