### ISSUE TITLE
2D GPU Particles appear to ignore the Local Coords setting in regard to the parent node's rotation

### ISSUE THREAD

**Issue by floere** [godotengine/godot#71480]
### Godot version

4.0.beta12.official

### System information

macOS 12.3.1 (21E258), Metal GPUFamily Apple 7, Vulkan

### Issue description

I expected particles emitted by a `GPUParticles2D` with `Drawing > Local Coords` set to `not On` to move independently of the rotation of the parent node of the `GPUParticles2D`.

However, this does not appear to be the case and the particles appear to rotate together with the parent node of the emitting `GPUParticles2D`.

https://user-images.githubusercontent.com/3022/212566997-b972cf05-3a74-4eb2-a5bc-d4d4e7c5b14a.mp4

### Steps to reproduce

1. Open the attached project.
2. Check that `Drawing > Local Coords` is set to `Off` on the `GPUParticles2D`.
3. Run the main scene.
4. The particles should not rotate with the parent node. (But they do)

### Minimal reproduction project

[GPUParticle2DRotationalJitter.zip](https://github.com/godotengine/godot/files/10421202/GPUParticle2DRotationalJitter.zip)

**Comment by Calinou** [comment]
Can you reproduce this with CPUParticles2D, or with GPUParticles3D?

**Comment by conradhappeliv** [comment]
I can repro this in my project.

@Calinou I don't think this is a problem in 3.5.1 - I believe this particular regression was introduced in beta11. And no, CPUParticles2D aren't affected.

**Comment by floere** [comment]
> Can you reproduce this with CPUParticles2D […]?

I can't. I can locate the regression between beta9 and beta10.

With 4.0.beta12.official:

https://user-images.githubusercontent.com/3022/212638174-c6f456b6-4ba7-47b2-99bb-f284ed9600a4.mp4

With v4.0.beta10.official [d0398f62f]:

https://user-images.githubusercontent.com/3022/212642883-190f31e8-6e44-4372-a0bb-27b39b93ea73.mp4

With v4.0.beta9.official [e780dc332]:

https://user-images.githubusercontent.com/3022/212644314-2ea6215f-a29a-4f53-95b9-e069b6fd55cc.mp4

Repro project for the above:
[GPUParticle2DRotationalJitterWithCPU.zip](https://github.com/godotengine/godot/files/10424077/GPUParticle2DRotationalJitterWithCPU.zip)

**Comment by akien-mga** [comment]
CC @clayjohn, you had a bunch of 2D particles PRs between beta 9 and 10, e.g. #70418 and #70422.

**Comment by floere** [comment]
That was fast! Thank you all 💖

**Comment by chrisheld2** [comment]
I am using 4.1.1 and I am still seeing this behavior. I am attempting to have a particle emit and continue in the direction while the emitter moves. I do not want to particles to appear as they are still attached, but move independent. The particles seem to ignore rotation.

Anything I might be doing wrong?

**Comment by Calinou** [comment]
@chrisheld2 If you want particles to inherit velocity while using global coordinates, you'll need https://github.com/godotengine/godot/pull/79527.
