### ISSUE TITLE
Vulkan Mobile: TAA camera jitter is still applied even though temporal antialiasing isn't supported

### ISSUE THREAD

**Issue by Akira1San** [godotengine/godot#71488]
### Godot version

v4.0.beta12.official [3c9bf4bc2]

### System information

Windows 10, AMD Radeon RX 480 4 GB RAM, 16 gb ram, Intel CPU 4 cores.

### Issue description

When switching to mobile render from forward + The alpha texture on the tree mesh starts to flicker.
Made a video: https://www.youtube.com/watch?v=WdGVi1hdRHo

### Steps to reproduce

Switching to mobile render from forward +

### Minimal reproduction project

Uploaded the project in google link: https://drive.google.com/file/d/1efEV914CWkyWoGzkv3RBMnw9t-4BVTeQ/view?usp=sharing
(only deleted the .godot - i guess its not needed.)

**Comment by Calinou** [comment]
You have temporal antialiasing enabled, but it's not implemented in the Forward Mobile backend (by design). However, the camera jitter is still being applied, which causes the issue.

As a workaround, disable TAA in the advanced Project Settings.

**Comment by Akira1San** [comment]
Thx, that works, closing.

**Comment by akien-mga** [comment]
Reopening as this should be done automatically as pointed out by @Calinou.
