### ISSUE TITLE
Export Android Apk，The program stops running repeatedly

### ISSUE THREAD

**Issue by BeyondXinXin** [godotengine/godot#71494]
### Godot version

4.0.beta.12  android7

### System information

windos10 

### Issue description

Create a blank project and export the Android program.
Install the apk file on the virtual machine, and the software exits.

When I use the same settings and package with `4.0.beta.10`, I will be prompted `Unable to initialize video drive`
When I use the same settings and package with `3.5.1`, it works normally

Android SDK
![image](https://user-images.githubusercontent.com/78600221/212588116-0842f94d-fd47-400b-b023-b98b1985ef34.png)
![image](https://user-images.githubusercontent.com/78600221/212588135-017678e3-5206-47b0-96e4-344fdce33dec.png)

Simulator information
![image](https://user-images.githubusercontent.com/78600221/212588746-8e585d25-b384-44ee-8609-610d5ac2f8cb.png)

#### 1）Use the same settings to export APK separately and install it
![screenshot-20230116-103735](https://user-images.githubusercontent.com/78600221/212588200-54dcea38-8507-47ad-9c05-3192bbc1f4ca.png)

#### 2）3.5 normal
![screenshot-20230116-103325](https://user-images.githubusercontent.com/78600221/212588191-6d21b462-cea4-4b88-89c3-7517af8fc229.png)

#### 3）4.0.b10 `Unable to initialize video drive`
![screenshot-20230116-103304](https://user-images.githubusercontent.com/78600221/212588185-39589c28-abd7-44fe-9bb7-f69ec45686ff.png)
![screenshot-20230116-103312](https://user-images.githubusercontent.com/78600221/212588189-41fff3c1-35c4-4214-bbff-5671c5c83d01.png)

#### 4）4.0.b12 The program stops running repeatedly
![screenshot-20230116-103610](https://user-images.githubusercontent.com/78600221/212588194-bfa0958f-2564-4092-a044-e3a13ec9bf62.png)

### Minimal reproduction project

[export_android_demo_src.zip](https://github.com/godotengine/godot/files/10422082/export_android_demo.zip)
[v_3.15.apk.zip](https://github.com/godotengine/godot/files/10422088/v_3.15.apk.zip)
[v_4.0.b_10.apk.zip](https://github.com/godotengine/godot/files/10422089/v_4.0.b_10.apk.zip)
[V_4.0.b_12.apk.zip](https://github.com/godotengine/godot/files/10422090/V_4.0.b_12.apk.zip)

**Comment by Calinou** [comment]
Last time I checked, Android emulators don't have Vulkan hardware acceleration or software emulation.

**Comment by BeyondXinXin** [comment]
> Last time I checked, Android emulators don't have Vulkan hardware acceleration or software emulation. Therefore, you need to use the Compatibility rendering method which uses OpenGL ES 3.0 (like Godot 3.x's GLES3 renderer).

> Have you tried exporting using the gl_compatibility renderer? The error message is telling you that your device (or emulated device) doesn't support Vulkan

Yes, use`gl_compatibility `No problem after. Sorry, I am not set correctly.
