### ISSUE TITLE
NVIDIA display driver regularly freezes when using Godot 4.

### ISSUE THREAD

**Issue by HauntedBees** [godotengine/godot#71501]
### Godot version

v4.0.beta10.official [d0398f62f]

### System information

Windows 8.1, 32GB RAM, Intel Core i5-6600K @3.50GHz, NVIDIA GeForce GTX 1070 (NVIDIA Windows Kernel Mode Driver, Version 474.11), Forward Plus renderer, Vulkan API 1.2.175 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1070.

### Issue description

After performing any random action in Godot, my computer will freeze for a moment, then I will receive a notification from my computer: **Display driver stopped responding and has recovered.** Display driver NVIDIA Windows Kernel Mode Driver, Version 474.11 stopped responding and has successfully recovered.

After this error happens, Godot 4.0 is largely unusable until it is closed and restarted. If I hadn't saved changes recently and try to save first, the usual "save before quitting?" popup appears but with no text or buttons in it. When the save popup appears, the only way to close Godot is through the Task Manager, but if there's no save prompt I can close Godot with the x button without any issue.

### Steps to reproduce

Recently triggers of this error have been: 
 - Trying to bring up the LabelSettings outline color picker
 - Trying to switch from the Script Editor to the 2D view
 - Leaving Godot open, putting the computer into Hibernate mode, then turning the computer back on

But the issue seems to be caused by any action in the 2D view, 3D view, or inspector in less than 30 minutes after opening Godot and a project. I don't think it has happened while I was using the Script editor. 

This is happening in 4.0 beta 10, but has occurred previously in betas 1 and 9 as well. This issue did not occur in Godot 3.5 on the same computer. Actions that cause the error will work without issue immediately after closing and reopening Godot, so there is no clear action that I've been able to identify that will always trigger the issue.

### Minimal reproduction project

N/A. Error occurs regardless of project contents. Occurs in 2D, 3D, and User Interface scenes.

**Comment by Calinou** [comment]
Can you reproduce this after switching to the Forward Mobile rendering method in the advanced Project Settings? Also try the Compatibility method.

**Comment by TokisanGames** [comment]
This is likley a driver or OS issue. Godot 3 is OpenGL only. Do you have any games that support Vulkan and you've configured for Vulkan mode so you can test your system?

NVidia v474.11 is from December. I'm on the latest, 528.02 (1/5/2023). If you upgrade your OS, you'll be able to upgrade your video driver, and replace the whole OS graphics subsystem and kernel (which are likely the problem). 

Windows 8.1 reached end of life Jan 10th, 2023 and won't be getting any more fixes. Both Windows 10 and 11 are far superior to 8.1 and Microsoft offers free upgrades to either one.

Windows 10
https://answers.microsoft.com/en-us/windows/forum/all/free-upgrade-to-windows-10/a1906d5c-2183-4064-af8e-e6650c15d96d

From 10 to 11 (see faq)
https://www.microsoft.com/en-us/windows/get-windows-11

**Comment by smix8** [comment]
A GTX 1070 by now is 5-6+ years old so apart from obvious driver / OS issues this also could just be card hardware wear and tear. You could try a low framerate cap and downclocking your card. If the issue goes away yours is no longer able to run stable at full spec. This error is very common even with modern cards when there is insufficient cooling or the fans are so badly configured that the sudden heatspike generated by e.g. Godot Vulkan Editor update rendering can cause a card and driver collapse.

**Comment by HauntedBees** [comment]
After trying out the Compatibility and Forward Renderers, the driver has only crashed once in a couple hours of Godot usage, so I guess the problem really is just "my hardware/drivers are old." Thank you for your help, everyone!

**Comment by TokisanGames** [comment]
Shouldn't be anything wrong with a 1070 or December drivers. But yes with win8.1. Do try one of the windows upgrades and test other vulkan games like I suggested, and run a temperature monitor as another suggested. Using the compatability modes is just a bandaid, not a permanent solution.

**Comment by PancheteG3D** [comment]
Hello. I downloaded Godot4 when it was released, a couple of days ago. I had been using the Godot3.5 and it worked very well. Never crashed. But Godot4 is crashing at the start (exactly about 18 seconds after starting). I thought it was due to the FBX2glTF importer window, because I don't have any reason to use this importer, but it appears automatically. If I select Cancel, it freezes. So I downloaded the FBX2glTF importer and selected the path to it, and it freezes anyways. But not really sure now if it has something to do with that. I've been reading issues like this, and it seems that Godot has some problems with Nvidia. I have a Nvidia RTX3050 with the drivers updated, and using Windows10. I don't know if there is a good fix for this issue, but I would like to know it, because I like Godot a lot, and I would like to use this new version. Thanks!

**Comment by TokisanGames** [comment]
Define crash or freeze. You said it does both, but they are different. Does it crash (Godot goes away) or freeze (Godot stays there). Does your mouse move? Does windows continue to work? Can you force Godot to close? Does all of windows freeze or crash? 

Is it exactly 18 seconds (same every time) or about 18 seconds (changes)? You said both. Does it do it on the project manager screen, or only when loading the editor? Does it do it on the 2d screen, or 3d screen, or script? So loading a new, empty project and switching to the script screen then waiting, 18 seconds later Godot hangs?

How about loading a Godot project with the other renderers on the project screen, forward, compatibility gles or vulkan mobile, etc? 

Is this a laptop or desktop? What brand and model? What does a temperature monitor report for your CPU and GPU? Are you overclocking anything? 

What version is your Nvidia driver? Studio or game driver?

What other games or 3D engines have you tested with a vulkan renderer on your system? You most likely would have had to configure them to use vulkan. 

Attach your Godot log file.

Finally, you should answer all of these questions in a new ticket as this one was specific to Ops hardware and considered resolved. You can reference this issue and tag me. 

My RTX3070, Win 11 has worked fine.

**Comment by PancheteG3D** [comment]
@TokisanGames Hello, TokisanGames! I've created a new ticket with the problem (and some new info, which can be interesting).
Here the new Ticket:
https://github.com/godotengine/godot/issues/74450
Thanks, mate! I've answered most of your questions. Let me know if I can give more info, or if a screenshot/video would help. Stay great!
