### ISSUE TITLE
GLB file fails to import with cycling dependency error

### ISSUE THREAD

**Issue by Flynsarmy** [godotengine/godot#71511]
### Godot version

4.0.beta12.official

### System information

Windows 11, Forward+, NVidia Geforce 3070 TI

### Issue description

I exported a character as GLB from unreal engine 5.1 and tried to import it into Godot. The import fails with the following error:
> Can't add child 'Mesh2' to 'Skeleton3D' as it would result in a cyclic dependency since 'Mesh2' is already a parent of 'Skeleton3D'.
> scene/main/node.cpp:1641 - Condition "!owner_valid" is true.

I can load the GLB file file in [Microsoft 3D Viewer](https://apps.microsoft.com/store/detail/9NBLGGH42THS?hl=en-au&gl=AU&rtc=1).

### Steps to reproduce

Download the below GLB and drop it in a blank projects root directory. As Godot attempts to import you'll see the error.

### Minimal reproduction project

Download this GLB and drop it in a blank projects root directory. As Godot attempts to import you'll see the error.
[SK_Character_Female_Druid.zip](https://github.com/godotengine/godot/files/10425615/SK_Character_Female_Druid.zip)

**Comment by fire** [comment]
@lyuma Nudge, there's two issues that seem to be in the same area. https://github.com/godotengine/godot/issues/68994

**Comment by Flynsarmy** [comment]
No longer an issue in Beta 17!
