### ISSUE TITLE
Undo in Animation editor does not work after changing script

### ISSUE THREAD

**Issue by lukaskotik** [godotengine/godot#7152]
**Operating system or device - Godot version:**
Godot 2.1, Linux 64bit

**Issue description** (what happened, and what was expected):
Undo in Animation editor does not work correctly after changing script. It undo script changes not animation changes.

**Steps to reproduce:**
Make a change in script. Then make a change in animation (tested on: `remove selected track`, `duplicate animation`, `remove animation`). Then Undo. It will undo script changes not animation changes.

**Comment by bojidar-bg** [comment]
Code itself looks legit to me: https://github.com/godotengine/godot/blob/master/tools/editor/animation_editor.cpp#L838.

Does the "Output" console show the `"Remove Anim Track"` text?

**Comment by lukaskotik** [comment]
Yes. The console shows `"Remove Anim Track"`, but undo is done script.

I can reproduce it with:

1. make a scene with a script and an animation
2. make a change in the script
3. run the scene
4. remove a track
5. make undo

Undo reverse script change. Removed track is not reversed.

**Comment by StraToN** [comment]
Confirmed.

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.
