### ISSUE TITLE
Sprite disappears when transitioning from an Animation that modifies the Scale property in the AnimationTree

### ISSUE THREAD

**Issue by taylordevereaux** [godotengine/godot#71532]
### Godot version

v4.0.beta12.mono.official [3c9bf4bc2]

### System information

Windows 10, Vulkan, NVIDIA GeForce GTX 1050 Ti with Max-Q Design

### Issue description

![Godot_AuosiMHd14](https://user-images.githubusercontent.com/880207/212780361-630c91c6-af15-4c8f-9316-b94cfc18a8a8.gif)

A Sprite will disappear when it's scale property is animated and the animation transitions to another animation using the AnimationTree.

### Steps to reproduce

1. Create an empty node.
2. Add a Sprite with any texture
3. Create an AnimationPlayer
4. Create a new animation
5. Add a Bezier Track for the sprites Scale Property
6. Set the key values for the first frame to 1 for both x and y 
7. Set the key values for the second frame to 1 for x and 0.9375 for y
8. Set the key values for the third frame to 1 for both x and y
9. Create a second animation (named anything). This animation can remain empty.
10. Create an AnimationTree, Assign the AnimationPlayer and set the Root to StateMachine
11. Add the First animation and set it to autoplay on start.
12. Add the second animation and add a transition from Animation1 to 2 then a second transition back to Animation1 that transitions at the End.
13. Set the AnimationTree to Active 
14. Idle animation will be running, the sprite will be scaling up and down.
15. Press Play on Animation2 in the AnimationTree

### Minimal reproduction project

[GodotAnimationBug.zip](https://github.com/godotengine/godot/files/10430004/GodotAnimationBug.zip)

**Comment by Chaosus** [comment]
Can you reproduce it on 3.x? Then it will be a regression and we can correctly assign a milestone.

**Comment by taylordevereaux** [comment]
I did and it’s not reproducible in 3.5

**Comment by TokageItLab** [comment]
The main reason for the scale being 0 is the lack of RESET animation (https://docs.godotengine.org/en/latest/tutorials/animation/animation_tree.html#for-better-blending), but apart from that, the acquisition of the BezierTrack for the RESET animation was broken.

The following project should work after #71823 is merged.

[GodotAnimationBug.zip](https://github.com/godotengine/godot/files/10473156/GodotAnimationBug.zip)
