### ISSUE TITLE
Cannot debug C++ code on Android Studio

### ISSUE THREAD

**Issue by FinleyPan** [godotengine/godot#71537]
### Godot version

3.5.stable

### System information

Android12(device), MacOS(host)

### Issue description

I want to debug the template project in Android Studio, but found the debugger only worked on java codes, it cannot step into native c++ codes. My Build Variant is as follows:
![image](https://user-images.githubusercontent.com/26212839/212810164-fa49a984-e6a9-4e8e-b446-0ceb2f3f0a1a.png)
I'm assured the debug symbol are kept on the library:
```
(lldb) file /Users/user/Projects/godot/platform/android/java/app/build/outputs/apk/dev/android_dev/lib/arm64-v8a/libgodot_android.so
(lldb) image lookup -vrn SceneTree::init
...
CompileUnit: id = {0x000002b9}, file = "/Users/user/Projects/godot/scene/main/scene_tree.cpp", language = "c++14"
...
```
The source file is correctly located. Whether are there any additional configurations on Android Studio for debugger working on c++ codes?

### Steps to reproduce

Described  as above

### Minimal reproduction project

None

**Comment by akien-mga** [comment]
CC @m4gr3d

**Comment by m4gr3d** [comment]
@FinleyPan The build variants are correct. You also need to update the build configuration to enable native debugging:
- Click on the `Run Configurations` drop-down and select  `Edit Configurations...`. 
![Screenshot 2023-01-17 at 2 02 55 AM](https://user-images.githubusercontent.com/914968/212868783-30bd23f3-3037-46c4-988a-5d5ab70fc321.png)

- In the `Run/Debug Configurations` window, select the project and on the `Debugger` pane, select `Dual (Java + Native)`.
![Screenshot 2023-01-17 at 2 04 36 AM](https://user-images.githubusercontent.com/914968/212869108-852fbb26-57b9-41e0-8e55-7c683294f5d9.png)

**Comment by FinleyPan** [comment]
@m4gr3d awesome! it works for me

**Comment by akien-mga** [comment]
Is there somewhere we could document this better?

**Comment by m4gr3d** [comment]
> Is there somewhere we could document this better?

Updating the documentation in https://github.com/godotengine/godot-docs/pull/6901
