### ISSUE TITLE
Unable to save the config file on android, using the _exit_tree() function

### ISSUE THREAD

**Issue by Vilcrow** [godotengine/godot#71536]
### Godot version

3.5.1.stable

### System information

Ubuntu 22.04.1, Android 10

### Issue description

Unable to save the config file on android, using the _exit_tree() function (see [scripts/hud.gd](https://github.com/Vilcrow/2048/blob/master/scripts/hud.gd)). For Linux and Windows it works.
If move the save_config_all() function to the _on_PauseButton_pressed() function, for example, it works for Android too.
The [exported app](https://vilcrow.itch.io/2048).

UPD: in the project the bug fixed. Use  [f07781c](https://github.com/Vilcrow/2048/commit/f07781cfcbba79548c7b2947ac868e7478897c61) for the bug reproducing.

### Steps to reproduce

1. Export the project for Android.
2. Open the application in Android.
3. Close the application.
4. Open the application again.
5. Check if the data has been saved.

### Minimal reproduction project

[Project](https://github.com/Vilcrow/2048). See [f07781c](https://github.com/Vilcrow/2048/commit/f07781cfcbba79548c7b2947ac868e7478897c61)

**Comment by Vilcrow** [comment]
Android feature.

**Comment by Zireael07** [comment]
Can you explain what you mean?

**Comment by Vilcrow** [comment]
@Zireael07 If I understand correctly, on android we cannot control the behavior of the application when it is closed. The data is destroyed before we have time to do anything. Maybe I'm wrong.

**Comment by Zireael07** [comment]
cc @m4gr3d - is this the case? if yes, should be clarified in the Android docs...
