### ISSUE TITLE
Invalid unicode codepoint (7fffff) on AZERTY keyboard

### ISSUE THREAD

**Issue by Badaxis** [godotengine/godot#71554]
### Godot version

v4.0.beta11.official [91713ced8]

### System information

Windows 10, AZERTY (french) keyboard

### Issue description

I have remap shortcuts for folding lines with the "><" key, but while I could assign the shortcut and it is working as intended, I'm now having error messages in the output:

>  Unicode parsing error, some characters were replaced with spaces: Invalid unicode codepoint (7fffff), cannot represent as UTF-16
>  U_ILLEGAL_ARGUMENT_ERROR

When I did this in v.3.5 the binding text was printing "unknown" without errors in the output dialog and was working just fine.
Same problem with the "§!" key.

An image for reference:
![AZERTY_keyboard](https://user-images.githubusercontent.com/29995442/212904489-1f06a0dc-b674-4705-9ea3-b09cc81cea2c.jpg)

### Steps to reproduce

1) Have an AZERTY keyboard (physical or virtual)
2) Assign a shortcut with the "><" or the "§!" key

### Minimal reproduction project

Can't really provide a project since it's a problem within the editor settings.

**Comment by akien-mga** [comment]
CC @bruvzg. Maybe fixed by #70052?

**Comment by bruvzg** [comment]
> Maybe fixed by https://github.com/godotengine/godot/pull/70052?

Yes, missing keys (including `§!`) should be fixed by #70052.
