### ISSUE TITLE
<"App name" may slow down your iPhone > warning message on iOS 10.1

### ISSUE THREAD

**Issue by KenHuang0917** [godotengine/godot#7155]
**Operating system or device - Godot version:**
macOS Sierra 10.12.1, Godot 2.1 stable, Xcode 8.1, iOS 10.1.1, Simulator 10.0

**Issue description** (what happened, and what was expected):
My new app, when first deployed and run on iOS 10.1 device or Simulator, will present the alert message which reads: " 'App name' may slow down you iPhone. The developer of this app needs to update it to improve its compatibility".  After some googling work, I found that it could be the 32 bits issue. But it proves to be of no use even I recompile Godot with 64 bits and export data.pck only 64 bits (not fat mode).

**Steps to reproduce:**
Compile Godot with: "Scons platform=iphone tools=no bits=64 target=release ios_sim=yes" for Simulator and with "Scons platform=iphone tools=no bits=64 target=release" for iDevice. Export data.pck from editor with 64 bits mode.

Thanks for helping!

**Comment by punto-** [comment]
Do other games get this message as well?

**Comment by KenHuang0917** [comment]
Sorry for my wording and I have reedited it. I am working  on one app only.

**Comment by KenHuang0917** [comment]
Yes. I tried another test chip and get the same result.

**Comment by punto-** [comment]
no, I mean other games made with other engines.. I wonder if this is cause
by the fact that games swap buffers constantly, much more often than apps

**Comment by KenHuang0917** [comment]
Because I've never used other game engine so I can't answer your question... :)  Isn't it because Apple forces developers update 32 bits apps to 64 bits?

**Comment by KenHuang0917** [comment]
I did some google work and found that other game engine seemed to have the same issue.
---Xamarin: https://forums.xamarin.com/discussion/81425/ios-10-1-message-app-may-slow-down-your-iphone
---Unity: https://forum.unity3d.com/threads/xxxxx-may-slow-down-your-iphone.438177/
---Apple developer forum: https://forums.developer.apple.com/thread/66972 , https://forums.developer.apple.com/thread/68081

Hope it helps to find some clue.

**Comment by punto-** [comment]
Just get a game from the app store, there's a ton of free ones :p

**Comment by vnen** [comment]
I think the problem is that the docs are outdated and iOS build arguments are not consistent with the other platforms. `bits=64` won't do anything, you need to use `arch=arm64` to build an actual 64-bit binary.

**Comment by KenHuang0917** [comment]
Ok I'll try. How about Simulator? How to compile an actual 64-bit binary for Simulator? "Scons platform=iphone tools=no bits=64 target=release ios_sim=yes" failed and I don't know how to make arch=x86 and arm64 at the same time. I tried arch=x64 but it seemed do no compiling at all?

**Comment by vnen** [comment]
Looking at the [build file](https://github.com/godotengine/godot/blob/master/platform/iphone/detect.py) it seems not to be possible to build for x86 64-bits.

To me this is a bug, so I'll label as such.

**Comment by KenHuang0917** [comment]
Got it. This warning message only pops up at the first deploy run and after that it won't appear again. So it's difficult to tell if any change works to clear this issue. On simulator it is easier to debug because I can reset the simulator and redeploy the app to see if the warning message gone. On iDevice it seems that I need to set up new apps to debug. I'll keep you posted if any results. Thank you for your prompt reply!!

**Comment by KenHuang0917** [comment]
Great! I start 2 new apps from demo files and prove it works! So the conclusion goes:
Set arch=arm64 instead of bits=64, ex.:  "Scons platform=iphone tools=no bits=64 target=release arch=arm64" to make an actual 64-bit binary to solve this problem. Thank you for your great help, Guys! Godot rocks!!
p.s. Please keep me posted if you have fixed to build for x86 64 bits binary. Since it really make my life much easier. XD

**Comment by bojidar-bg** [comment]
Bump, can this be closed, or is it still waiting for an IOS pro?

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
Thanks!
