### ISSUE TITLE
Rooms and portals not working with VR

### ISSUE THREAD

**Issue by sanyi12** [godotengine/godot#71556]
### Godot version

3.5.1

### System information

Windows 10

### Issue description

I tested it on two versions (1 project without the r&p and the same project with r&p) and they use same amount of resources thus the r&p makes no difference. 

### Steps to reproduce

using Olij's addons: godot oculus, openvr and xr tools
simple scene like in the snip
![sdfsdfsf](https://user-images.githubusercontent.com/79376841/212903972-0ec27d0e-346e-4f47-b3e9-6c53333977ca.PNG)

nothing changed, all properties remained by default, each room contains at least 10 objects and 1 portal
no errors or issues when running
actually works in the editor with a normal camera and the XRCamera -  tested them with the "preview camera" in Debug

### Minimal reproduction project

I cannot make the project public. Would sent it to only 1 person if someone is interested. Please do not share the files. Leave an email address.

**Comment by Calinou** [comment]
Do geometric occluders (OccluderShapeSphere/Quad) work?

> I cannot make the project public. Would sent it to only 1 person if someone is interested. Please do not share the files. Leave an email address.

This makes troubleshooting a lot more difficult, so I recommend you create a minimal project specifically for this bug report. Otherwise, it'll take a lot more time to find a solution to this issue.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
