### ISSUE TITLE
Scale is ignored when aligning 2D node to screen

### ISSUE THREAD

**Issue by Klaider** [godotengine/godot#71550]
### Godot version

4.0dev beta9

### System information

Windows 11, gl_compatibility

### Issue description

Node doesn't align correctly to screen.

NOTE: the first picture uses a `Control`. I put the control at the right position manually. I tried aligning the abstract `Control` itself and it didn't work as well.

![image](https://user-images.githubusercontent.com/110610266/212894424-0908cd86-bd58-41a8-bad3-0b2dfe964be2.png)
![image](https://user-images.githubusercontent.com/110610266/212894443-eda27130-ae10-4a09-b6a5-06c17db262d0.png)

### Steps to reproduce

- 1. Create a 2D scene.
- 2. Add a node to the scene.
- 3. Align the node to the right-side center of the screen at the scene.

### Minimal reproduction project

N/A

**Comment by Zireael07** [comment]
Anchors/alignment only work for controls. The difference between your 1st and 2nd picture is that the parent is a Node2D, not a Control, which means it wont work.

**Comment by Klaider** [comment]
@Zireael07 Actually it didn't work too when I used control. The first one too doesn't work.

**Comment by KoBeWi** [comment]
Node 2D has no size, so your alignment works around point 0,0. You need a Control **root node** and set it to full rect. The easiest way is to pick User Interface option in empty scene.

**Comment by Klaider** [comment]
@KoBeWi Is creating a "User Interface" scene equivalent to a Node2D one? I mean, will it create a Node2D with, like, a full rect control?

And, alternatively, is there an easy way to set a abstract control as full rect?

**Comment by KoBeWi** [comment]
This option sets the Control as full rect:
![image](https://user-images.githubusercontent.com/2223172/212901032-77da14a6-3484-4741-a04c-a53f68d44e83.png)
But full rect means it will take the parent's size. If the parent is CanvasItem, it will use size of that node. For Control parents, it's their rect size, for Node2D parents, it depends on node. Sprite2D takes the size of its texture, but Node2D has no size, thus full rect has size of 0.

If you want fullscreen Control, the parent has to be non-CanvasItem node, e.g Node, CanvasLayer or Viewport. If your Control is the scene's root, full rect will cover the screen too.

**Comment by Klaider** [comment]
@KoBeWi Thanks! At first I thought it was a bug because the alignment worked at first with an abstract `Node2D` scene. Anyway, using a `CanvasLayer` worked!

**Comment by Klaider** [comment]
I've a little issue: scale seems to be ignored. I'm trying to change the scale of a node and it doesn't align correctly with the new scale. Any idea?

**Comment by KoBeWi** [comment]
See #19068
