### ISSUE TITLE
`empty()` method missing in `Array`

### ISSUE THREAD

**Issue by Scony** [godotengine/godot#71568]
### Godot version

master latest

### System information

Linux Manjaro

### Issue description

In Godot 3.x there was: `empty()` method exposed on `Array` objects: https://docs.godotengine.org/en/stable/classes/class_array.html#class-array-method-empty
In Godot 4 it's missing thus forcing the user to use a less readable counterpart like `arr.size() == 0`

### Steps to reproduce

Try this code:
```
var r = []
print(r.empty())
```

### Minimal reproduction project

N/A

**Comment by raulsntos** [comment]
It was renamed to [`is_empty()`](https://docs.godotengine.org/en/latest/classes/class_array.html#class-array-method-is-empty).

**Comment by KoBeWi** [comment]
^
