### ISSUE TITLE
[godot v2.1.1] editor's text area overlaps windows when code completion popup is on

### ISSUE THREAD

**Issue by avril-gh** [godotengine/godot#7156]
godot v2.1.1-stable is affected by this bug
master branch is NOT affected by this bug

example image of godot v2.1.1-stable
![overlap_bug](https://cloud.githubusercontent.com/assets/3224132/20454328/af57d3d8-ae3d-11e6-9555-7ff5cca289c0.gif)

**Comment by akien-mga** [comment]
Duplicate of #6769.

**Comment by akien-mga** [comment]
Will be fixed in next release relatively soon (2.1.1.1 or 2.1.2, not sure yet).

**Comment by bojidar-bg** [comment]
@akien-mga Relatively is a flexible term :wink:
