### ISSUE TITLE
Meshes drawn incorrectly when too far from camera due to automatic mesh LOD

### ISSUE THREAD

**Issue by blackears** [godotengine/godot#71567]
### Godot version

v4.0.beta12.official [3c9bf4bc2]

### System information

Windows 10, GLES 3,

### Issue description

A character mesh that I've imported from blender draws with obviously incorrect polygons when its too far from the camera.  This is happening both in the viewport and in running programs.  I suspect this is some sort of LOD issue.

### Steps to reproduce

Create a new scene and add the attached model to it.  Move the camera away from the model and view the result.  When the model is only about 1/8 as tall as the viewport, geometry is drawn incorrectly.

### Minimal reproduction project

[MeshLODDrawing.zip](https://github.com/godotengine/godot/files/10437635/MeshLODDrawing.zip)

You might need to adjust the window size of this project when you play it.  On my machine it shows the problem when run at the default window size, but goes away if I maximize the window.

![image](https://user-images.githubusercontent.com/6724608/212967346-1202e950-8451-48e8-80d3-8d8bf0a44d6c.png)

**Comment by clayjohn** [comment]
Indeed, it looks like the auto LOD system is having a lot of trouble with that mesh

**Comment by Calinou** [comment]
As a workaround, disable **Generate Lods** in the mesh's import options, then click **Reimport**.

**Comment by blackears** [comment]
Unchecking Generate LODs and reimporting does not seem to do anything.  However, making the children editable and tweaking the MeshInstance3D's LOD BIAS does seem to help.

**Comment by clayjohn** [comment]
This was fixed at some point. I didn't track exactly when, but I tested on 4.0.3 and 4.3 stable and I can't reproduce the issue. 

I also tested:
1. With the model being animated
2. With a small window size (400x300)
3. With a heavy LOD bias (0.1)
