### ISSUE TITLE
Miscellaneous problems parsing GDScript in the scan thread

### ISSUE THREAD

**Issue by reduz** [godotengine/godot#71570]
### Godot version

4.0-dev

### System information

all

### Issue description

There are a couple of problems in the scan thread when parsing script files (specifically GDScript).

The first one is relatively minimal:

https://github.com/godotengine/godot/blob/master/modules/gdscript/gdscript.cpp#L2468
This should be more tolerant to parse errors, so even if parse is not ok, this information will almost certainly still be there in the parse tree.

The second one is a design problem of the feature:
https://github.com/godotengine/godot/blob/master/editor/editor_file_system.cpp#L925
this has the following problems:
* This is way too early to load a script, most clases in the filesystem have not been scanned and it is highly likely the parsing will fail. this should be done later on in the scan scripts phase.
* The function to get documentation should still *not* load the script resource in a thread. This is dangerous as the script could have init logic not meant to run on a thread. This should be a dedicated function that uses the parser on the file on disk without opening the resource.

### Steps to reproduce

Here is a script that lets you generate a lot of Godot classes, you can see the second problem appear easily if you use this (I have no idea where this cache goes, but it seems the error only happens on the first time:
![image](https://user-images.githubusercontent.com/6265307/212972737-4aa74f21-b357-4b74-a4f9-add54bbc2f63.png)

Python script: 
```Python
import random

class_count = 500

class_inherit_from = ["Sprite2D","ImageTexture","Control","ArrayMesh"]

for i in range(class_count):
    cname = "Class"+str(i)
    inh = ""
    if (i > 0 and i % 5 == 0):
        inh = "Class"+str(int(random.randrange(i)))
    else:
        inh = class_inherit_from[random.randrange(len(class_inherit_from))]
            
    cstr = "class_name "+cname+" extends "+inh    
    f = open(cname+".gd","w")
    f.write(cstr+"\n\nfunc _init():\n\tpass\n")
```

### Minimal reproduction project

Use script above in an empty project.

**Comment by adamscott** [comment]
Here's a generated version of the MRP, for those too lazy to run Python:
[71570.zip](https://github.com/godotengine/godot/files/10438036/71570.zip)

I could reproduce the issue when deleting the `.godot` root repository and reloading the project.

**Comment by akien-mga** [comment]
Is this fixed by https://github.com/godotengine/godot/pull/71628?

**Comment by adamscott** [comment]
@akien-mga I think so. The issue with classes is gone in master (eaf306e).
