### ISSUE TITLE
strange normal map behaviour on some meshes

### ISSUE THREAD

**Issue by djmaesen** [godotengine/godot#71571]
### Godot version

4.0 beta 12

### System information

windows 10

### Issue description

im getting artifacts on some meshes. the normal map isnt applied correctly.
![189929140-9ea8b81f-4727-4c92-9e0c-93c0b6d4834c](https://user-images.githubusercontent.com/95492794/212972998-891916b2-dfb5-480a-a974-94b5459cdf09.jpg)
![212738089-7ecb8db8-8829-4f03-a9e4-6467d37dc2b7](https://user-images.githubusercontent.com/95492794/212973020-e4cde95f-46e4-40b1-a531-a3f785b347ba.jpg)

### Steps to reproduce

ive attached the barrel model to reproduce the issue.

import the model and apply a standard material with the maps provided. 

### Minimal reproduction project

[exploBarrel.zip](https://github.com/godotengine/godot/files/10437960/exploBarrel.zip)

**Comment by Calinou** [comment]
Is the mesh triangulated on export, either by using a Triangulate modifier in Blender and ensuring **Apply Modifiers** is enabled in the export dialog, or by checking an appropriate triangulate option in the exporter?

**Comment by djmaesen** [comment]
> Is the mesh triangulated on export, either by using a Triangulate modifier in Blender and ensuring **Apply Modifiers** is enabled in the export dialog, or by checking an appropriate triangulate option in the exporter?
> 
> This is more reliable than letting the game engine do it. (This advice is not specific to Godot; it applies to any 3D application you'd export a mesh to.)

the barrel isnt
but the weapon and arms are triangulated

**Comment by djmaesen** [comment]
> Is the mesh triangulated on export, either by using a Triangulate modifier in Blender and ensuring **Apply Modifiers** is enabled in the export dialog, or by checking an appropriate triangulate option in the exporter?
> 
> This is more reliable than letting the game engine do it. (This advice is not specific to Godot; it applies to any 3D application you'd export a mesh to.)

i just tried the barrel with triangulation applied before import, same result.

**Comment by Flavelius** [comment]
i had a look at the file and it actually seems to be a godot issue (i also tried exporting with different modifications (like merged verts, non-sharp, non/autosmooth, normal edit modifier etc) and export options. Blender's mesh analysis tools also confirm that there are no normal issues or overlaps etc. And when importing the barrel in a different orientation, those artifacts even occur in different locations in godot.

**Comment by tagcode** [comment]
On Godot 4.0.2, I'm having issue with normal mapped materials and normals that point at (0, 0, -1).

![normalmap-bug](https://user-images.githubusercontent.com/5236113/231960572-7d6b72c8-21a7-4f30-ac32-014df4f0013a.png)

When I adjust normals a bit near Z=-1, the normalmap issues goes away:
`
float dot = normal.Dot(Vector3.Forward);
if (dot > 0.99f) normal = new Vector3(0.1f, 0.1f, -0.9f).Normalized();
`

![normalmap-bug-With-workaround](https://user-images.githubusercontent.com/5236113/231960581-957587f3-31a5-4cf8-8710-35a07fc96a06.png)
