### ISSUE TITLE
Imported glTF at runtime not visible on Android

### ISSUE THREAD

**Issue by EibrielInv** [godotengine/godot#71586]
### Godot version

v4.0.beta13.official [caacade56]

### System information

Xubuntu 22.04

### Issue description

A glTF 3D model loaded at runtime is visible when running the project, but not when exporting to Android.

This is how it looks when running on the editor:
![imagen](https://user-images.githubusercontent.com/172656/213036321-56793bd5-4999-4476-9691-041579d07f1a.png)

And this on the Android emulator:
![imagen](https://user-images.githubusercontent.com/172656/213036239-36f6a952-e18d-44ad-b1d4-a2285cd9d0e4.png)

### Steps to reproduce

Download the reproduction project, export to Android, open the `.apk` on an Android device (with Vulkan support)

### Minimal reproduction project

[GLTFBug.zip](https://github.com/godotengine/godot/files/10440511/GLTFBug.zip)

**Comment by EibrielInv** [comment]
Was an error on export configuration.

**Comment by Calinou** [comment]
> Was an error on export configuration.

Can you describe the exact error to help future users who may stumble upon this issue from a web search? Thanks in advance :slightly_smiling_face:

**Comment by EibrielInv** [comment]
Sure, the issue was that Godot was not including the `glTF` files on the export. To fix that:
- Set the `glTF` files import method to "Keep file (do not import)"
- And include `*.glb,*.gltf,*.bin` to the file export filter section on the Resources tab on Export settings
