### ISSUE TITLE
File browser "up to folder" duplicate icons

### ISSUE THREAD

**Issue by UgisBrekis** [godotengine/godot#7158]
**Operating system or device - Godot version:**
Windows 10, 4965ddfaa1536fb179d4b156d1ecb8a72a3c565f

**Issue description** (what happened, and what was expected):
There are duplicate "up to folder" icons in file browser and only the one with two dots work. Previously there was just one option to go one folder up.

![duplicate_up_to_folder](https://cloud.githubusercontent.com/assets/9309589/20456386/9b615c0c-ae6d-11e6-9758-db955a5829b9.jpg)

**Steps to reproduce:**
It just happens from the whole start when Godot is launched. This happens when I want to create a new project, add existing one or basically anytime file browser is being showed.

**Link to minimal example project** (optional but very welcome):

**Comment by akien-mga** [comment]
That's not a duplicate, `./` is the current directory, `../` is its parent.

**Comment by UgisBrekis** [comment]
But why is it there? It does nothing, feels even misleading. Is there any particular reason why it was added?

**Comment by Calinou** [comment]
> But why is it there? It does nothing, feels even misleading. Is there any particular reason why it was added?

It is here so that you can target the "current directory", this is especially relevant when you have to choose a directory and not a file.

**Comment by akien-mga** [comment]
See #5989.

**Comment by UgisBrekis** [comment]
Ok, I get the idea guys, but this really doesn't feel intuitive, it looks more like an error happened and some names are missing or it did the folder scan twice... I'll try to figure out better solution for this.

**Comment by volzhs** [comment]
aren't `.` and `..` directory names pretty general for all OS?

**Comment by puppetmaster-** [comment]
Can this be only available when file browser window wants you select a folder and not in all file browser windows?

**Comment by bojidar-bg** [comment]
Bump. This issue is getting stale :wink:

To me it looks perfectly intuitive, but that is probably due to my computer/linux background anyway.

Maybe we can rename `../` to  "Parent folder" text and appropriate icon, and `./` to "Current folder" and appropriate icon?

**Comment by volzhs** [comment]
@bojidar-bg I like that one.

**Comment by Noshyaar** [comment]
Closing as fixed. The ../ and ./ are no longer present in the list.
