### ISSUE TITLE
Calling `AnimationPlayer.seek()` when there is no current animation causes an undescriptive error in the debugger

### ISSUE THREAD

**Issue by MiloThatch4** [godotengine/godot#71593]
### Godot version

4.0.beta13

### System information

Windows 10

### Issue description

When you call the `seek()` function without a current animation it outputs `Condition "!playback.current.from" is true.` to the debugger.

I was getting the error above whenever I would call `stop()` on an AnimationPlayer when it didn't have a playing animation. I realized that `stop()` also calls the `seek()` function.

I would expect the `seek()` and `stop()` functions to just do nothing, instead of throwing errors, if there isn't a current animation, or at least show an error that says that there is no animation to seek/stop.

This is the same issue that was described here: [#6122](https://github.com/godotengine/godot/issues/6122)

### Steps to reproduce

- Create an AnimationPlayer node.
- Don't have it play any animations.
- Call the `seek()` function.

### Minimal reproduction project

[seek_issue.zip](https://github.com/godotengine/godot/files/10442071/seek_issue.zip)

**Comment by devduckgames** [comment]
I don't have a minimal reproduction project to share, but I think I'm seeing something similar in my project.  I have just over 100 of these errors in the console when starting my game, and each one traces back to an `instantiate` call on a scene.  The details reference the `seek()` function as mentioned above.

**Comment by TokageItLab** [comment]
This error is necessary to detect that the animation does not exist, i.e., there is no timeline to seek.

The error in the editor when creating an empty animation is due to a change in the behavior of stop(), which is corrected in https://github.com/godotengine/godot/pull/71907#issuecomment-1404199141.
