### ISSUE TITLE
Project setting 'Initial Screen' has too many monitor options

### ISSUE THREAD

**Issue by jwmcgettigan** [godotengine/godot#71591]
### Godot version

v4.0.beta12.mono.official [3c9bf4bc2]

### System information

Windows 10, Forward+ (Vulkan), NVIDIA GeForce RTX 3070 (526.98)

### Issue description

The `Initial Screen` select dropdown provides 64 options for monitors when it should only provide options for what is available.  In my case, I'm only using two monitors so there should only be two monitors to choose from (excluding the Primary Monitor option of course).  Screenshot below.

![image](https://user-images.githubusercontent.com/1691061/213066149-b97d3220-9b23-4685-a155-ad2f48f96de3.png)

### Steps to reproduce

The issue appears to occur whether I'm using two monitors or one monitor.

---
1. Open `Project Settings`
2. Go to `Display` > `Window` > `Size`
3. Select the `Initial Screen` dropdown.
4. You will see the `Primary Monitor` option and 64 other monitor options as seen in the screenshot.

### Minimal reproduction project

N/A

**Comment by jwmcgettigan** [comment]
The following code seems to be responsible.

https://github.com/godotengine/godot/blob/04a39ecd846f40ac1049b699291f28b2f08e2185/core/config/project_settings.cpp#L1278-L1284

**Comment by jwmcgettigan** [comment]
I think it would be good to mimic the options available in `Editor Settings` > `Run` -> `Window Placement` -> `Screen`.

![image](https://user-images.githubusercontent.com/1691061/213073930-6c36c943-f041-4bb7-9999-b905ccdbb4cc.png)

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by bruvzg** [comment]
> I'm only using two monitors so there should only be two monitors to choose from

It's deliberately not using current monitor count. The editor run options are only used on the machine you are currently using, and using the current monitor number. Initial project settings are preserved when you export the app, you can use it on the other machines with the different number of monitors, so there's no reason to limit to the current config.

**Comment by Calinou** [comment]
> It's deliberately not using current monitor count. The editor run options are only used on the machine you are currently using, and using the current monitor number. Initial project settings are preserved when you export the app, you can use it on the other machines with the different number of monitors, so there's no reason to limit to the current config.

That makes sense, but in terms of usability, we should probably only list 8 monitors. It's already very unlikely to be using more than 6 monitors on a single system.

**Comment by jwmcgettigan** [comment]
> It's deliberately not using current monitor count. The editor run options are only used on the machine you are currently using, and using the current monitor number. Initial project settings are preserved when you export the app, you can use it on the other machines with the different number of monitors, so there's no reason to limit to the current config.

Ahh, I see now - that makes sense.  I agree with @Calinou that 64 monitors seems excessive.  Here are some other considerations.

1. Perhaps the `Previous Monitor` and `Next Monitor` options could be useful additions to the `Initial Screen` options?
2. The documentation for the `Initial Screen` property could be improved.

## Current Documentation
### Initial Screen (Project)
> Main window initial screen.

### Screen (Editor)
> The monitor to display the project on when starting the project from the editor.

## Suggested Documentation
### Initial Screen (Project)
> The monitor to display the main window on when starting the exported project.

**Comment by akien-mga** [comment]
This should maybe be two separate project settings:
- Enum with only the common options which make sense (primary, secondary?) + custom
- If custom, a new setting is shown with a SpinBox in range 1,64.

Realistically though, who would be able to ship a project with say "Monitor 41" selected as the initial screen?

The only situation I can think of would be for a productivity app that would be deployed on one's own controlled hardware configuration... seems pretty niche.
