### ISSUE TITLE
Vulkan: Ambient light rendering within ReflectionProbe breaks if SSAO or SSIL are enabled

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#71595]
### Godot version

4.0.beta13

### System information

Fedora 37, GeForce RTX 4090 (NVIDIA 525.60.11), Forward Plus

### Issue description

Ambient light rendering within ReflectionProbe breaks if SSAO or SSIL are enabled (or both):

No SSAO/SSIL | SSAO enabled
-|-
![Screenshot_20230118_075221](https://user-images.githubusercontent.com/180032/213104809-23c880b3-fb72-4742-9010-ed8d4797639c.png) | ![Screenshot_20230118_075227](https://user-images.githubusercontent.com/180032/213104816-3c76f052-dd86-40f1-a7d3-0aa44ab9d1da.png)

SSIL enabled | SSAO + SSIL enabled
-|-
![Screenshot_20230118_075231](https://user-images.githubusercontent.com/180032/213104824-43260c5c-4a77-418e-b05b-10fad5f4f21b.png) | ![Screenshot_20230118_075236](https://user-images.githubusercontent.com/180032/213104830-460926d6-722c-43ce-9919-31ab24421253.png)

If you increase both **Light Affect** and **AO Channel Affect** in the Environment SSAO properties, the entire reflection becomes black (except the background sky):

![Screenshot_20230118_075421](https://user-images.githubusercontent.com/180032/213104722-10564cdf-00f7-43bf-b9d9-b09f07015a9c.png)

This hints at the SSAO buffer being fully black within the reflection rendering.

The easiest fix is likely to disable SSAO and SSIL rendering within the ReflectionProbe. Its results will be hardly visible, and this would bring a handy performance benefit in scenes where the ReflectionProbe has to be re-rendered continuously (moving ReflectionProbes, or ReflectionProbes with the update mode set to **Always**).

This regression started in 4.0.beta11, as it works in 4.0.beta10. I bisected the exact commit that caused the regression to e886a7af818be3287deefab9b18f87014ee60182. cc @BastiaanOlij 

### Steps to reproduce

- Create a scene with visible DirectionalLight and and shadows.
- Add a MeshInstance3D with a SphereMesh, and a fully reflective material to display the reflection (roughness = 0.0, metallic = 1.0).
- Add a ReflectionProbe node, then increase its extents to work around https://github.com/godotengine/godot/issues/54449. Enable **Enable Shadows** in the ReflectionProbe.
- Enable SSAO in WorldEnvironment.
- Notice how the shadow becomes fully black in the reflection.

### Minimal reproduction project

[test_reflection_probe_ssao_ambient.zip](https://github.com/godotengine/godot/files/10443013/test_reflection_probe_ssao_ambient.zip)
Use the arrow keys to move the sphere, <kbd>O</kbd> to toggle SSAO, <kbd>I</kbd> to toggle SSIL.

**Comment by BastiaanOlij** [comment]
Thats likely a regression caused by the render buffers change I did a while ago, I'll have a look at it tomorrow

**Comment by BastiaanOlij** [comment]
This is caused by the recent changes in render buffers and some of the SSAO/SSIL logic being run when it shouldn't when rendering reflection probes.

I plan to fix this this week as I was already planning other fixes around screen space effects but working through some other things first.
