### ISSUE TITLE
Vulkan Mobile: DirectionalLight3D shadow opacity not working

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot#71606]
### Godot version

4.0b13

### System information

macOS 13.0.1

### Issue description

The shadow opacity parameter on DirectionalLight3d does not seem to work as intended on the Mobile renderer. Using the Forward+ renderer it works as expected, but on the Mobile renderer it has no effect unless set to 0 where the shadow disappears completely.

https://user-images.githubusercontent.com/17763524/213153694-24029838-e6e0-4836-8eb5-53a6259ce151.mov

### Steps to reproduce

- Set your project to use the Mobile Renderer
- Set up a scene with some meshes and a default directionalLight3D to cast shadows
- Enable shadows on the light and change the Shadow Opacity parameter

### Minimal reproduction project

[shadow_opacity_test.zip](https://www.lostminds.com/godot/shadow_opacity_test.zip)

**Comment by Calinou** [comment]
For reference, per-light shadow opacity was added in https://github.com/godotengine/godot/pull/61893.

**Comment by lostminds** [comment]
> For reference, per-light shadow opacity was added in #61893. Both clustered and mobile shaders were modified by that PR, so it's not due to a missing implementation.

In that PR it's mentioned that the same opacity is used by shadow distance fade, and that still works as expected on the mobile renderer. So it's just the specific shadow opacity parameter that doesn't seem to be applied as intended.

**Comment by lostminds** [comment]
I'll admit this is a little beyond me, but looking at the code in the PR above I notice that in servers/rendering/renderer_rd/shaders/scene_forward_clustered.glsl the shadows are multiplied with `directional_lights.data[i].shadow_opacity` while in what I think is the mobile version servers/rendering/renderer_rd/shaders/scene_forward_mobile.glsl `directional_lights.data[i].shadow_opacity` only seem to be used for checks > 0.001 to enable shadows and not used for any multiplication? Instead I only found 
`shadow = mix(shadow, 1.0, smoothstep(directional_lights.data[i].fade_from, directional_lights.data[i].fade_to, vertex.z)); //done with negative values for performance`
Which I guess could explain why shadow distance fade would still work on mobile while the `shadow_opacity` parameter is still not used.

**Comment by Calinou** [comment]
@lostminds Good catch, this turned out to be the exact issue! Thanks :slightly_smiling_face:
