### ISSUE TITLE
Incorrect window and taskbar icon on Windows export

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot#71602]
### Godot version

4.0.beta13

### System information

Windows 11

### Issue description

When exporting to windows the exported exe (with embedded pck) file gets the assigned icon shown on the desktop and in explorer when using the RCEdit tool. However, the icon is not correctly used on the window or in the taskbar. Instead it gets a default icon. When right-clicking the item in the task bar this then strangely shows the correct icon, however it shows "Godot Engine" instead of the set game name (or File Description as it's strangely named in the export dialogue). If the game is run from the editor the icon is properly set in the window and taskbar, but I assume this uses the project settings icon. When exported I guess it's trying to get the icon from the assigned export icon resource instead and this is failing on windows in this case.

![Screenshot_20230118_103339](https://user-images.githubusercontent.com/17763524/213139949-1eed1380-2831-4b7c-8124-9883d184e470.png)

![Screenshot_20230118_103534](https://user-images.githubusercontent.com/17763524/213139966-f99e40c8-06fa-4dd2-941f-5c15d4711752.png)

![Screenshot_20230118_103640](https://user-images.githubusercontent.com/17763524/213139993-9bdadc35-3a17-4d9c-b4a4-bf51029a773a.png)

In other words, more or less the same bugs as described in https://github.com/godotengine/godot/issues/54713 however, possibly with other sources as the causes of those issues are listed as fixed.

The issue with "Godot Engine" being shown is also covered in https://github.com/godotengine/godot/issues/36629 but there the proposed fix is to just fill in File Description, which doesn't seem to work now. So either this is a new 4.0 bug, or just the same, and it didn't work back in 3.2 either.

I've double checked that the ico file has members of all possible sizes. When investigating this I noticed that the resolution members of an icon file can be either png or bmp (at least at some sizes). Could this be an issue? I also noticed that there's an icon interpolation setting in the export settings, which would indicate that something would be scaling icons, but as I understand it this should not be the case as the ico file already contains the icon at different resolutions? Overall some descriptive tool tips on these export settings would be very helpful.

### Steps to reproduce

- Install and set the path to RCEdit in the editor settings 
- Set up a windows export preset (with embedded pck) with an icon (see below for sample) and application info (name, version etc)
- Export and observe the icon not being properly used

### Minimal reproduction project

You can download the ico file I used to test with here [VlobsIcon.ico.zip](https://www.lostminds.com/godot/VlobsIcon.ico.zip)

**Comment by akien-mga** [comment]
CC @bruvzg

**Comment by bruvzg** [comment]
Can't reproduce.

Note: Icon of the window title bar and taskbar is determined by `Project Settings -> Application -> Config -> Icon`, not by export settings, export icon is an icon of the executable only.

**Comment by bruvzg** [comment]
Seems reproducible only when exporting using editor executable (with `TOOLS_ENABLED`).

**Comment by lostminds** [comment]
> Seems reproducible only when exporting using editor executable (with `TOOLS_ENABLED`).

@bruvzg Well, maybe you found another bug then. Your comment about it using the project settings icons rather than the export icons made me figure out and find the issue I was having. Turns out my problem was caused by me having added a .gdignore file to the directory with all the app icon files (I didn't want Godot to generate .import files and process all the icon size image files for all platforms). This wasn't an issue while running in the editor since you can still use files in .gdignored folders in the editor. However, not surprisingly these files aren't included in exports and therefore the .ico file was not working in export. I guess the issue in my case was more that there wasn't a warning that the project was referencing resources in an ignored folder that would not be included in exports.

So, my original issue is now resolved, but as you've linked a pullrequest I'll leave this open for now instead of closing it.
