### ISSUE TITLE
Broken Documentation

### ISSUE THREAD

**Issue by FIXTHISPLEASE** [godotengine/godot#7160]
Much of the example code is outside of many of the `<pre>` elements at [this link](http://docs.godotengine.org/en/latest/tutorials/step_by_step/simple_2d_game.html#script) ; this makes the learning curve even worse.

I'm using a temporary email so don't bother.

**Comment by avril-gh** [comment]
this issue is reported in wrong repository - should be in https://github.com/godotengine/godot-docs

Anyway i pushed fix there https://github.com/godotengine/godot-docs/pull/307
