### ISSUE TITLE
Error when exporting .NET project

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#71608]
### Godot version

4.0.beta13

### System information

Mageia 9, Linux

### Issue description

When exporting a trivial .NET project with 4.0.beta13, I get the following error:

```
ERROR: Required virtual method EditorExportPlugin::_get_name must be overridden before calling.
   at: _gdvirtual__get_name_call (editor/export/editor_export_plugin.h:123)
```

It doesn't seem to prevent exporting, but should be fixed anyway.

On the first export attempt (not be reproducible in my MRP, needs to be redone from scratch), it also shows this warning:
```
WARNING: Property not found: dotnet/project/assembly_name
     at: get_setting_with_override (core/config/project_settings.cpp:364)
```
Which likely means that we're using `GLOBAL_GET` before we defined the property with `GLOBAL_DEF`.

### Steps to reproduce

- Create a simple project with a hello world C# script
- Export it from Linux to Linux or Windows (didn't test other combinations, would likely have the same issue)
- Check Output dock / console

### Minimal reproduction project

[TestMono.zip](https://github.com/godotengine/godot/files/10445350/TestMono.zip)

**Comment by raulsntos** [comment]
The method `EditorExportPlugin::_get_name` was added in https://github.com/godotengine/godot/pull/65135 and uses `GDVIRTUAL_REQUIRED_CALL` (I wish it was an abstract method), I guess we need to override it in C#'s ExportPlugin.
