### ISSUE TITLE
[4.0beta13] Editor freezes with custom editor display scale

### ISSUE THREAD

**Issue by Flavelius** [godotengine/godot#71611]
### Godot version

v4.0.beta13.mono.official

### System information

Windows 10, nvidia gtx 1060, forward+

### Issue description

When selecting 'Custom' in the 'Display Scale' setting of the editor, it won't start anymore, freezing indefinitely. No errors printed to the console.

### Steps to reproduce

Just apply the described editor settings and restart the editor.

### Minimal reproduction project

not applicable

**Comment by YuriSizov** [comment]
I can't reproduce this. Do you still experience the issue with the 4.0 stable?

**Comment by Flavelius** [comment]
I'm now on linux and there i can't reproduce it with 4.0 stable. I'll reopen an issue in case i'll ever switch to windows and encounter it again.
