### ISSUE TITLE
MenuBar with submenus will raise errors when submenu item is clicked.

### ISSUE THREAD

**Issue by Ark2000** [godotengine/godot#71612]
### Godot version

v4.0.beta13

### System information

Windows 11, Forward+

### Issue description

Click the items in sub PopupMenu nested in MenuBar will raise an error, but everything works fine.

![image](https://user-images.githubusercontent.com/21126555/213169715-26b174b2-c3c0-4ef5-a750-2c6bb2d1819e.png)

Correct me if this is not the intended usage of MenuBar node.

### Steps to reproduce

1. Create a scene like this below.

![image](https://user-images.githubusercontent.com/21126555/213169715-26b174b2-c3c0-4ef5-a750-2c6bb2d1819e.png)

2. Add some items and set submenu via code

```gdscript
extends MenuBar

func _ready():
	$Menu1.add_item("item 1")
	$Menu1.add_item("item 2")
	$Menu1/Submenu1.add_item("item 11")
	$Menu1/Submenu1.add_item("item 12")
	$Menu1.set_item_submenu(1, "Submenu1")
```

3. Click submenu items.

![image](https://user-images.githubusercontent.com/21126555/213169292-c3b992a6-6043-4c8b-b54b-783ad10c6e68.png)

4. An error is raised, but nothing breaks.

![image](https://user-images.githubusercontent.com/21126555/213170175-30243452-1874-43ef-8eb0-ec151f2d1da4.png)

```
E 0:00:03:0700   window_get_popup_safe_rect: Condition "!windows.has(p_window)" is true. Returning: Rect2i()
  <C++ Source>   platform/windows/display_server_windows.cpp:2322 @ window_get_popup_safe_rect()
```

Github source: https://github.com/godotengine/godot/blob/caacade569eb7a541aaa7a8cdc3eedffca1422d9/platform/windows/display_server_windows.cpp#L2322

### Minimal reproduction project

[bug_minimal_project.zip](https://github.com/godotengine/godot/files/10446154/bug_minimal_project.zip)

**Comment by nezvers** [comment]
Where is some information on WHY PopupMenu is inheriting the Window?

**Comment by ze2j** [comment]
Same error on Linux, Godot 4.0.1.rc1 with just a PopupMenu in a GraphEdit derivated class reacting to the signal popup_request (so no OptionButton or Menubar and I don't have any submenu).

```
E 0:01:32:0819   window_get_popup_safe_rect: Condition "!windows.has(p_window)" is true. Returning: Rect2i()
  <C++ Source>   platform/linuxbsd/x11/display_server_x11.cpp:3691 @ window_get_popup_safe_rect()
```

**Comment by KoBeWi** [comment]
Can't reproduce in 4.2 dev. Can someone test in the newest version and confirm?

**Comment by ze2j** [comment]
@KoBeWi I can't reproduce as well with the current 4.2 master [c495eb5102278a110c14bbffbf833ed436d1594d](https://github.com/godotengine/godot/tree/c495eb5102278a110c14bbffbf833ed436d1594d)

I reproduce with 4.1.1-stable though.
