### ISSUE TITLE
InputMap does not list custom actions when running in Editor

### ISSUE THREAD

**Issue by AndreaTerenz** [godotengine/godot#71613]
### Godot version

4.0 beta 13 (existed since at least beta 10)

### System information

Manjaro Linux, kernel 6.1.1-1-MANJARO, AMD Ryzen 5 3600, AMD RX 580

### Issue description

When running a `@tool` script, `InputMap` will ignore any custom defined input actions and list only the predefined ones. However, it behaves correctly when actually running the game. If this is (somehow) expected behaviour, it should at least be specified in the `InputMap` docs

### Steps to reproduce

- New project
- Define any input action
- Create a tool script
- In the script:
```gdscript
func _ready():
	print(InputMap.get_actions())
```
The custom action you've defined will not be in the printed array _while in editor_ but it will be _while running_
In the reproduction project, I have added `my_custom_action` to the input map and a tool script with the above code. In editor, the script prints:

```
[&"ui_accept", &"ui_select", &"ui_cancel", &"ui_focus_next", &"ui_focus_prev", &"ui_left", &"ui_right", &"ui_up", &"ui_down", &"ui_page_up", &"ui_page_down", &"ui_home", &"ui_end", &"ui_cut", &"ui_copy", &"ui_paste", &"ui_undo", &"ui_redo", &"ui_text_completion_query", &"ui_text_completion_accept", [...]]
```
and when running solo it prints:
```
[&"ui_accept", &"ui_select", &"ui_cancel", &"ui_focus_next", &"ui_focus_prev", &"ui_left", &"ui_right", &"ui_up", &"ui_down", &"ui_page_up", &"ui_page_down", &"ui_home", &"ui_end", &"ui_cut", &"ui_copy", &"ui_paste", &"ui_undo", &"ui_redo", &"ui_text_completion_query", &"ui_text_completion_accept", [...], &"my_custom_action"]
```

### Minimal reproduction project

[InputBugTest.zip](https://github.com/godotengine/godot/files/10446218/InputBugTest.zip)

**Comment by akien-mga** [comment]
That's normal, a `@tool` script runs in the editor, and so it uses the editor's InputMap, not your project's.

You'd get similar results if you tried to inspector the nodes of the SceneTree (the root is `EditorNode`, not your project's), or the theme, etc.
