### ISSUE TITLE
Key Scene "Forgets" Its Script on Project Reload

### ISSUE THREAD

**Issue by CornflakeWoof** [godotengine/godot#71610]
### Godot version

4.0 Beta 13 - Also occurred on 4.0 Beta 10

### System information

Windows 11, RTX 3070, AMD Ryzen 7 2700X

### Issue description

Hi everyone!

I've recently started experiencing a _very_ frustrating issue where one of my key scenes (Player Actor) seems to "forget" it has a script on it every time the project is reloaded. 

No matter how many times I save this scene, as soon as I reload the project the script is no longer attached and I need to set everything up again just for that session before it's all forgotten again on next load. The problem briefly went away when I saved the scene again under a new name, but it has just reoccurred, and I suspect this will only become more aggravating should the project get any bigger.

I have made absolutely sure the project and its contents are not read-only - I appreciate this could be my hardware's fault, but as it's this particular scene that keeps malfunctioning under numerous different names, I wonder if the issue is coming from elsewhere.

![2023-01-18 11_32_41-Actor_PlayerN tscn - SoulslikeEngine - Godot Engine](https://user-images.githubusercontent.com/106239192/213164024-dd86f6d2-ce0b-47ac-b8e4-cc054b3e2bb5.jpg)

(Before reload)

![2023-01-18 11_33_11-(_) Actor_PlayerN tscn - SoulslikeEngine - Godot Engine](https://user-images.githubusercontent.com/106239192/213165310-bb69988b-ff29-478d-b79e-78f11e6e671d.jpg)

(After reload)

No errors or relevant warnings are provided as to why this might be occuring and from what I can tell the Actor_Player.gd script has no issues the GDScript parser can detect.

### Steps to reproduce

In the attached project:

1. Open "Scenes\Actors\Actor_PlayerN.tscn" in Editor.
2. Drag and drop "Scripts\Actors\Actor_Player.gd" onto the topmost node in this scene, then save it.
3. Reload the project.

### Minimal reproduction project

Unfortunately as I cannot guarantee this will occur on any other project, I have opted to include my full project here. Only freely available Mixamo assets are used.

[SoulslikeEngine.zip](https://github.com/godotengine/godot/files/10445770/SoulslikeEngine.zip)

**Comment by adamscott** [comment]
The issue seems to be related by it's symptom to #70985.

**Comment by CornflakeWoof** [comment]
> The issue seems to be related by it's symptom to #70985.

Interesting! I did recently try getting some multiplayer stuff in motion which involved preloading the player scene, I'm not sure where the circular dependency would be coming from in this case though.

**Comment by adamscott** [comment]
When reporting an issue, try always to run Godot with the verbose flag: `--verbose`

Here's an interesting log that links it to #70985:
```
ERROR: res://Scenes/Actors/Actor_PlayerN.tscn:17 - Parse Error: [ext_resource] referenced non-loaded resource at: res://Scripts/Actors/Actor_Player.gd
   at: _parse_ext_resource (scene/resources/resource_format_text.cpp:178)
```

I confirm that my PR #71478 fixes this issue too.

**Comment by CornflakeWoof** [comment]
> 

Ah, I wasn't aware about the verbose flag!

Not sure if it's correlation or causation, but since I removed the line in the Multiplayer script that preloads the player scene it _seems_ to have stopped, if it starts happening again I'll get the verbose flag going!

**Comment by adamscott** [comment]
There's clearly a cyclic component to your script. `Actor_Player.gd` loads `res://Scenes/Networking/MultiplayerHandler.tscn` and `MultiplayerHandler.gd` loads `res://Scenes/Actors/Actor_PlayerN.tscn`.

@akien-mga You can close this issue as a duplicate #70985.
