### ISSUE TITLE
Why do the attached scripts run _process even though it is disabled? This is when _ready() is used in the scripts. Is it a bug?

### ISSUE THREAD

**Issue by MatiasVME** [godotengine/godot#71621]
### Godot version

Godot 4-beta13

### System information

Linux, KDE Neon, OpenGL3, Mesa Intel(R) UHD Graphics (CML GT2)

### Issue description

Why do the attached scripts run _process even though it is disabled? This is when _ready() is used in the scripts. Is it a bug?

I would like to disable the _process completely even though _ready() has been used.

I have created a minimal example in which the problem is shown, if it is...

### Steps to reproduce

I have made a short example of this... in the MRP

### Minimal reproduction project

[InheritedWithReady.zip](https://github.com/godotengine/godot/files/10446910/InheritedWithReady.zip)

**Comment by TheDuriel** [comment]
You are overriding _ready, so your base ready will no longer be called.

Use _init instead and don't override it.

**Comment by MatiasVME** [comment]
> 

Ohh thanks, I am going to try that

**Comment by TheDuriel** [comment]
There is no need to await ready.

**Comment by KoBeWi** [comment]
The process **must** be set inside ready, you are doing it correctly. Just call the base method in your inheriting class:
```GDScript
func _ready():
	super()
	print(name)
```

**Comment by TheDuriel** [comment]
@KoBeWi According to the documentation, that only applies to the input related toggles.

**Comment by KoBeWi** [comment]
Which documentation?
![image](https://user-images.githubusercontent.com/2223172/213198116-0d283eba-b41e-4049-a3bc-84b4e0c43b82.png)

**Comment by TheDuriel** [comment]
NVM, I was looking at set_process_internal
