### ISSUE TITLE
const PackedArrays iteration issue

### ISSUE THREAD

**Issue by AdamAvramov** [godotengine/godot#71635]
### Godot version

4 beta 13 & 12

### System information

Windows 10

### Issue description

can't properly iterate over const packed arrays, you can see the output will be a default initialized value and the last element of the array in beta13 and in 12 it will be similar with but with the other elements represented as what seem to be uninitialized memory (random numbers)

### Steps to reproduce

Start a new Project
Add any node and a script to it
add something like this to see it:

```
const array : PackedVector2Array = [Vector2(0,0),Vector2(1,1),Vector2(2,2),Vector2(3,3)]

func _ready() -> void:
	for i in array:
		print(i)
```

### Minimal reproduction project

"N/A" would be faster for you to check in your own projects

**Comment by vonagam** [comment]
I assume that #70873 fixes the issue.

**Comment by dalexeev** [comment]
> I assume that #70873 fixes the issue.

Yes, I have tested.
