### ISSUE TITLE
StreamPeerOpenSSL::initialize_ssl loads cert twice

### ISSUE THREAD

**Issue by romeojulietthotel** [godotengine/godot#7163]
**Operating system or device - Godot version:**
x86_64 linux master

**Issue description** (what happened, and what was expected):
The ssl .cert file was loaded twice but only needs to be loaded once.

**Steps to reproduce:**
Set the ssl cert and conf setting under project settings.

**Link to minimal example project** (optional but very welcome):
Use the HTTPClient to request an https website url.
Set ssl=true,verify=false.

The code is clear enough why it loads twice.  Should the conf setting and cert settings be mutually exclusive? Or should StreamPeerOpenSSL::initialize_ssl use 
```
if(cert) 
    load cert
else
    load cert specified by conf
```

**Comment by bojidar-bg** [comment]
Looking at the code right now, it looks like this might have been changed, and/or resolved now. Can you confirm, @romeojulietthotel?

**Comment by romeojulietthotel** [comment]
I tried to rebuild from git master but the build fails.  I will test as soon as I can get a build.

**Comment by romeojulietthotel** [comment]
The build fails in core/reference.h   with a call to a function that does not exist.  reference->unreference()
I also now remember that the push is on to make a 3.0 version. Should I file a separate issue against the build failure or are things moving too fast now for that to be helpful to the team?

**Comment by romeojulietthotel** [comment]
...time walks...

I still need to test this, been out of the loop. And I need to see where Godot's at, as I have not been following News or Releases.

**Comment by romeojulietthotel** [comment]
No longer seeing this in 3.x.
