### ISSUE TITLE
Clicking on Shader resource no longer opens the shader editor

### ISSUE THREAD

**Issue by clayjohn** [godotengine/godot#71639]
### Godot version

b5f3ac522e16b2d899604e2d0788a86c66476e78

### System information

PopOS 22.04 

### Issue description

This is a regression since Beta 13. In Beta 13 if you click on a node and the shader is open in the inspector, the shader editor will open up and load the shader. 

In master, even if you click on a shader resource in the inspector the shader editor will not pop up and the shader will not load. You have to manually open up the shader editor and then manually load the shader (i.e. "File > Load Shader").

Inspector showing an open material and I have just clicked on the Shader resource
![Screenshot from 2023-01-18 10-50-52](https://user-images.githubusercontent.com/16521339/213269650-836c19ed-f92c-4c04-bc1e-c3624ddc68dc.png)

This is what the shader editor looks like once opened
![Screenshot from 2023-01-18 10-51-01](https://user-images.githubusercontent.com/16521339/213269648-9cabeb6c-c66f-4053-92c4-f276ebbab838.png)

### Steps to reproduce

1. On an existing node with a ShaderMaterial, click on the material to unfold it in the inspector
2. click on the material's Shader resource

### Minimal reproduction project

Not a project specific issue

**Comment by clayjohn** [comment]
Bisected to https://github.com/godotengine/godot/commit/81b1ebddefc5e3775331b70ea09dfb7d23a4ee1e 

So this will be fixed by https://github.com/godotengine/godot/pull/71636

**Comment by akien-mga** [comment]
Fixed by #71636.
