### ISSUE TITLE
[4.0beta13] Physics: Scaled Area3D fails to produce signal _on_body_entered when entered by RigidBody

### ISSUE THREAD

**Issue by substract** [godotengine/godot#71633]
### Godot version

4.0 beta 13 (official)

### System information

Windows 10, NVIDIA GeForce 1060 GTX 3GB, Vulkan

### Issue description

 Area3D fails to produce signal _on_body_entered when scaled and entered by RigidBody. This worked in previous versions.

### Steps to reproduce

Set up scene with Area3d and RigidBody3d so that the RigidBody will fall into the Area3D.
Connect a script with the _on_body_entered signal.

Compare outcome when Area3D is unscaled and scaled. The Area should be a lot bigger than the RigidBody.
I used a Sphere Collision for the RigidBody and Box for the Area.

(see minimal reproduction project)

### Minimal reproduction project

[area3d_test.zip](https://github.com/godotengine/godot/files/10448954/area3d_test.zip)

**Comment by rburing** [comment]
This is a regression introduced by https://github.com/godotengine/godot/pull/70787.
