### ISSUE TITLE
[Android] Implicit conversion of the package name when exporting for Android with using "$genname" for project name starting with invalid characters.

### ISSUE THREAD

**Issue by Vilcrow** [godotengine/godot#71645]
### Godot version

3.5.1.stable, v4.0.beta.custom_build [0a87ead64]

### System information

Ubuntu 22.04.1

### Issue description

For example, if project has name "300spartans", we can't enter the "org.godotengine.300spartans" to "Unique Name" field. We get the error "Invalid package name: A digit cannot be the first character in a package segment". But , if we enter "org.godotengine.$genname", there will be no error message. When exporting, the name will be set as "org.godotengine.spartans" without "300" in beginning, but user will not be informed about it. I think, it is not very good. It may not be worth making changes to the source code, but mention it in the documentation.

### Steps to reproduce

See issue description.

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
It should be easy to add a warning if using $genname but the generated name would be invalid.

**Comment by Vilcrow** [comment]
@akien-mga theoretically, the project name can start with other invalid characters, not just numbers.
