### ISSUE TITLE
Transparent Flag Not Initially Working With Non-embedded Subwindows

### ISSUE THREAD

**Issue by ChildLearningClub** [godotengine/godot#71642]
### Godot version

4.0.beta12

### System information

Windows 11, RTX 3080

### Issue description

When a Window Node is created with it's Transparent flag set to true and Project Settings --> Display --> Window --> Subwindows --> Embed Subwindows is false, the Window has a black background. By cycling the transparent flag from false and back to true again, during runtime, the window's background then becomes transparent. 

### Steps to reproduce

Attempt to create a Non-embedded Subwindow with a transparent background using the appropriate flags. 

### Minimal reproduction project

Note: this project is from Reddit user [gongpha](https://www.reddit.com/user/gongpha/) and his Reddit post [Learning a Godot 4.0 Window node](https://www.reddit.com/r/godot/comments/xr8yxn/learning_a_godot_40_window_node/)

https://github.com/gongpha/godot4-window-test

**Comment by akien-mga** [comment]
CC @bruvzg

**Comment by ChildLearningClub** [comment]
May be duplicate or just related to #70627

**Comment by ChildLearningClub** [comment]
This bug seems to extend to the always_on_top property flag as well, with funny things happening when toggling the flag during runtime or setting always_on_top = true in the _ready function. I read at least one post of someone who was trying to achieve this effect as it allows for you to have an overlay and pass all inputs to the operating system below. Maybe it should be kept in :)

**Comment by ChildLearningClub** [comment]
Hi @bruvzg,  The transparency flag works now, but the "Always on Top" flag does not function unless turned off and back on again during runtime in 4.0.beta14.
