### ISSUE TITLE
Mipmap bug when using imported textures

### ISSUE THREAD

**Issue by danielpcs** [godotengine/godot#7164]
**Windows 10 Home 64-Bits** - Godot Version: **2.1.1-Stable 32-bits** _&_ **2.1-Stable 32-bit**

When using imported textures with the **"no mipmap"** option turned off and specific compression options, I get a black shadow a bit far from camera as seen [**HERE**](https://i.gyazo.com/72c551219ba3aa0025d82d2d786970c7.png).

It doesn't happen when seen from the top, but grows the more aligned the face/polygon is to the camera.

It only happens if you import the textures with the compression option set to Uncrompressed or Compressed(Vram) and with mipmap.

Using the image file directly or importing using the other compression options work as it should, both with mipmaps on.
Deactivating the mipmaps flag after it was imported with vram or uncrompressed also gets rid of the problem but you lose the mipmap effect.

**Steps to reproduce:**
1-Import the texture provided with only **repeat**, **anisotropy**,**fix border** and **filter** flags set to on and compression set to **Vram** or **Uncompressed**.
2-Apply to terrain as diffuse.
3-Run the scene for a FPS view or move camera close to the ground and align to it.

[**Link to minimal example project**](https://dl.dropboxusercontent.com/u/11827298/MipmapBug.rar)

**Comment by bojidar-bg** [comment]
Does this occur with recent master/gles3?

**Comment by Zireael07** [comment]
I think it does, see #10221

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.
