### ISSUE TITLE
Some 3D nodes will incorrectly force 3D editor when switching scene tab

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#71655]
### Godot version

4.0 d93b66a

### System information

Windows 10 x64

### Issue description

I have a 2D scene with some 3D nodes. The root is node 2D, most nodes are 2D, I have 2D node selected. When I switch scene tab and back, the editor switches to 3D view, even though the 2D node is still selected.

I managed to strip the scene to bare minimum. You need a Node3D with Camera3D and DirectionalLight3D children.

https://user-images.githubusercontent.com/2223172/213327465-ba07760e-6dab-43c0-96e8-5109fcc0a576.mp4

### Steps to reproduce

1. Make 2D scene
2. Add some 3D
3. This bug has a chance to happen
4. Check the repro for setup that reproduces the issue

### Minimal reproduction project

[3DBug.tscn.txt](https://github.com/godotengine/godot/files/10452297/3DBug.tscn.txt)

**Comment by PrecisionRender** [comment]
What is the expected behavior here? Should we open whatever editor the root node resides in?

**Comment by KoBeWi** [comment]
We should open the editor of whatever node is currently selected. In this case I have 2D node selected, but I see 3D editor. This also leads to some bugs like not being able to lock a node while in this state.

**Comment by PrecisionRender** [comment]
I'd like to see if I can fix this.

**Comment by PrecisionRender** [comment]
https://github.com/godotengine/godot/blob/c3539b4561f9b4d7dc4ba1c5859217e7fbf9c6fe/editor/editor_node.cpp#L3630-L3636

Ah, so right now, it's selecting the editor tab based on how many nodes of each type there are in the scene. So, if there are more 3D nodes than 2D, it will select the 3D editor, which is what is happening to you. Your scene has 3 3D nodes and 2D nodes.

**Comment by KoBeWi** [comment]
So I guess it should prioritize the currently selected node (whether it's 2D or 3D) and fallback to counter if there is no selected node or it's not 2D/3D.

**Comment by PrecisionRender** [comment]
I suggest as a fallback it should check the node type of the root node.
