### ISSUE TITLE
Editor redraws continuously after running scene with F5 / F6

### ISSUE THREAD

**Issue by maiself** [godotengine/godot#71652]
### Godot version

d93b66ad4d6b1dae42cc318c16224d03bd1a1472

### System information

arch linux

### Issue description

The editor redraws continuously after running a scene with F5 / F6, but this does not happen when running a scene with the buttons in the upper right of the editor. Redrawing does not stop until the editor is closed. This can cause the system to run hot and drain battery quickly.

### Steps to reproduce

Enable update spinner if not enabled in editor settings.
Press F5 or F6 to run a scene.
Notice the spinner going even after the scene is closed.

### Minimal reproduction project

none

**Comment by Calinou** [comment]
> latest master

Can you point the exact commit you compiled? Which rendering backend are you using in the project? Can you reproduce this in a brand new project, or only in a specific project? If you can only reproduce this in a specific project, please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

Also, can you reproduce this in any of the [3.5 betas and RCs](https://downloads.tuxfamily.org/godotengine/3.5/) to determine when the regression started?

**Comment by maiself** [comment]
Bisected to dd3a1b08a938181c67c2fc573431a63904600184.
