### ISSUE TITLE
[godot 4.0 beta.13] RichTextLabel's meta_underlined did not work.

### ISSUE THREAD

**Issue by Atem1995** [godotengine/godot#71666]
### Godot version

4.0 Beta 13

### System information

Window10

### Issue description

[godot 4.0 beta.13] RichTextLabel's meta_underlined did not work.But it works in beta.10 version.

### Steps to reproduce

略

### Minimal reproduction project

略

**Comment by akien-mga** [comment]
Please explain what the bug is. "did not work", with no steps to reproduce is not a bug report.

Most likely you're seeing an intended behavior introduced by #69753, but I shouldn't have to guess it.

**Comment by Atem1995** [comment]
> 请解释错误是什么。“不起作用”，没有步骤重现不是错误报告。
> 
> 您很可能看到#69753 引入的预期行为，但我不必猜测它。
No matter how you set the meta_underlined attribute, the underline will not be displayed.

**Comment by akien-mga** [comment]
I can't reproduce, please provide a minimal reproduction project.

![image](https://user-images.githubusercontent.com/4701338/213430611-6b556af4-51f3-499a-9966-d245fda70126.png)
