### ISSUE TITLE
Scale manipulator does not scale rotated objects uniformly

### ISSUE THREAD

**Issue by ExquisiterEmil** [godotengine/godot#71675]
### Godot version

4.0beta13

### System information

Windows10, AMD Ryzen 9 3900XT, RTX3070, Vulkan

### Issue description

I would expect when using the scale tool on an object with a scale of (1,1,1) without touching any of the handles to result in a uniform scale again (i.e. 0.1, 0.1, 0.1) and not one, where all components are different.
However, when the object has been rotated, this is the case no matter if using local or global transform.

![RotateAndScaleBroken](https://user-images.githubusercontent.com/53947784/213452728-d03427dd-be89-4bba-8dba-fbade6627555.gif)

This behavior was working properly in 3.x

### Steps to reproduce

- Create an object (e.g. a CSGBox3D)
- Rotate it a little on different axes
- Scale it with the scale tool, without using any handle (uniform scale)
- Observe how the object is now slightly squashed or stretched, i.e. the scale components are not equal anymore

### Minimal reproduction project

[BrokenScale.zip](https://github.com/godotengine/godot/files/10457086/BrokenScale.zip)

Observe how the cube turns into a pillar when using the Scale Manipulator.

**Comment by ExquisiterEmil** [comment]
still valid in beta15
![badScaling](https://user-images.githubusercontent.com/53947784/214710633-53297697-b41f-45c9-929d-bca4e573f9ee.gif)

**Comment by ExquisiterEmil** [comment]
Started bisecting the issue. 
Issue did not appear in 4.0-dev.20211210, started appearing in 4.0-dev.20220105/.

**Comment by ExquisiterEmil** [comment]
After bisecting up until 11 revisions, I am confident, that https://github.com/godotengine/godot/commit/6af77c7b090f9e49aa5176783bf7350f8f6ec2e2 introduced the bug.

**Comment by clayjohn** [comment]
CC @TokageItLab

**Comment by TokageItLab** [comment]
Due to #53684. I'll take a look later。

**Comment by TokageItLab** [comment]
@ExquisiterEmil Okay, I sent #72362. Please test it if you can.

**Comment by ExquisiterEmil** [comment]
@TokageItLab Works! Thank you! 👍
