### ISSUE TITLE
Changing directional shadow map size or blur filter quality at runtime does nothing

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot#71681]
### Godot version

4.0b13

### System information

macOS 13.0.1

### Issue description

I'm experimenting with a graphics quality settings in a project and try to change shadow quality settings during runtime from code. More specifically the settings `rendering/lights_and_shadows/directional_shadow/size` and `rendering/lights_and_shadows/directional_shadow/soft_shadow_filter_quality`. If I understand this pull request https://github.com/godotengine/godot/pull/54165/ correctly this should be possible and changes should be applied instantly when the setting is changed (at least the size, but I assume the same should go for the filter quality). 

While the pull request is for 3.5 it is mentioned that this will be possible in 4.0 as well (or?). However, when trying to change these settings at runtime they seem to do nothing at all, so I'm opening this issue in case this is a bug or oversight.

https://user-images.githubusercontent.com/17763524/213479796-b23b73e0-4b57-4141-8c64-b627abe41d43.mov

This is the same on both Mobile and Forward+ renderer

### Steps to reproduce

- Set up a scene with a directional light with shadows turned on some meshes and a camera
- Observe your shadow quality
- Change the shadow map size using `ProjectSettings.set("rendering/lights_and_shadows/directional_shadow/size",shadowMapSize)`
- Observe your shadow quality

### Minimal reproduction project

[shadow_quality_test.zip](https://www.lostminds.com/godot/shadow_quality_test.zip)

**Comment by mrjustaguy** [comment]
This is expected, this is only read at runtime.
Use `RenderingServer.directional_shadow_atlas_set_size(resolution,16bit)`

**Comment by lostminds** [comment]
> This is expected, this is only read at startup.
> Use `RenderingServer.directional_shadow_atlas_set_size(resolution,16bit)`

Ah, thank you! I guess I was tricked by finding the PR above and thinking this new 3.5 feature would be the same in 4.0.
