### ISSUE TITLE
[platform:web] Cannot download project source in v4

### ISSUE THREAD

**Issue by PoolloverNathan** [godotengine/godot#71702]
### Godot version

v4.0.beta9.official [e780dc332]

### System information

* Chrome 107.0.5304.110 (Official Build) (64-bit) on ChromeOS 15117.111.0 (Official Build) stable-channel octopus

### Issue description

When attempting to download your project from the web app using the Download Project Source button, nothing happens. This makes it impossible to download your project, which means that you must start over if you need to switch platforms.

### Steps to reproduce

1. Create or open any project in the web editor
2. Click `Download Project Source`
3. Notice a lack of download

### Minimal reproduction project

N/A, freshly created project works

**Comment by clayjohn** [comment]
Confirmed on Beta13

Clicking "Download Project Source" gives the following error:
```
editor/editor_node.cpp:3113 - Error calling function from tool menu: 'WebToolsEditorPlugin::WebToolsEditorPlugin::_download_zip': Method expected 1 arguments, but called with 0
```

**Comment by PoolloverNathan** [comment]
Thank you!
