### ISSUE TITLE
Parallax Layers don't seem to respect camera's anchor mode

### ISSUE THREAD

**Issue by Leather128** [godotengine/godot#71701]
### Godot version

4.0.beta.13.official

### System information

EndeavourOS

### Issue description

When using parallax layers it seems they don't respect the anchor mode of the currently active camera. This means that if you for example, have a camera set to "Drag Center" as it's anchor mode, and then zoom in the camera, the parallax layers, instead of zooming in and moving as if the camera was centered will instead act as if the camera is using the "Fixed TopLeft" anchor mode.

![image](https://user-images.githubusercontent.com/81660872/213571507-228ccf9a-0589-4088-a8e8-6647726dc267.png)

This image is from the example project I provided in the issue.

### Steps to reproduce

1. Get a Camera2D set as current that uses the "Drag Center" anchor mode.
2. Add a new parallax background and parallax layer (parallax layer having a motion scale other than `1,1`) to the scene.
3. Put a sprite in the parallax layer.
4. Set the camera's zoom to anything other than `1,1`.

### Minimal reproduction project

Here is a [Minimal reproduction project](https://github.com/godotengine/godot/files/10461498/example.zip) that demonstrates the bug.

**Comment by tlobig** [comment]
Have you tried setting the offset of the ParallaxBackgound to half the screen size? i.e.
background.offset = DisplayServer.window_get_size() / 2
It seems the behaviour has changed or it is exactly a bug

**Comment by Leather128** [comment]
I just tried it and I don't see much of a change in behaviour, rather changing the offset just seems to have made it harder to see the behaviour properly.

**Comment by akien-mga** [comment]
Seems fixed when converting to the new Parallax2D implemented in #87391 (will be available in 4.3-dev5 and later), at least if I understood the desired outcome correctly:

[Screencast_20240304_142210.webm](https://github.com/godotengine/godot/assets/4701338/f6f779b2-c56e-4815-adb4-2abaffc16a33)
