### ISSUE TITLE
Ignore Texture Size is not kept when using github and working on Windows 10 vs Windows 11

### ISSUE THREAD

**Issue by TrevorHarron** [godotengine/godot#71714]
### Godot version

4.12.dev

### System information

Windows 10 and Windows 11

### Issue description

Textures using a .png for the texture of a Texture Nodes don't keep the Ignore size bool. Keeps being reset to false.

### Steps to reproduce

Have a project using Git source control with a texture node with a .png file.  
On Windows 10
set flag for ignore size for texture node to true.
commit changes and push to origin
On the Windows 11 machine
pull project
Look at the texture node 
see the flag for ignore size set to true

### Minimal reproduction project

[texture-bug.zip](https://github.com/godotengine/godot/files/10463887/texture-bug.zip)

**Comment by lostminds** [comment]
Could this be this bug: https://github.com/godotengine/godot/issues/71340 where the new TextureRect node would not correctly translate the old Ignore Size property to the new Expand mode setting? If so it should be fixed in 4.0b13 and you can test it there

**Comment by TrevorHarron** [comment]
It looks possible that it is the same bug, I will test in 4.0b13. Thanks!

**Comment by TrevorHarron** [comment]
Confirmed that in 4.0b13 (and 4.0b14) this bug is resolved. Thank you!
