### ISSUE TITLE
OpenGL: multiple omni lights render incorrectly

### ISSUE THREAD

**Issue by fracteed** [godotengine/godot#71710]
### Godot version

4.0 beta 13

### System information

Windows 10 960m

### Issue description

I have noticed that more 3 omni lights will render meshes incorrectly. Initially I thought it might have been a light limit over 8 issue, but increasing it to 16 made no difference.

This is an example of the issue:

![omni_8_opengl](https://user-images.githubusercontent.com/7741669/213618701-1f67202e-8e1f-4715-a1b7-c9900292d025.jpg)

This has 8 overlapping omni lights, but it seems like any more than 3 has this kind of incorrect lighting issue. If you toggle on and off random selections of lights in the sample file, there can be seen that some combinations work and some don't.

@clayjohn I am guessing that this is related to the light fix you did for Vulkan recently? I don't usually use opengl in 4.0 but I was trying to use the light limit option to increase it for the vulkan mobile render. Is the opengl light limit render option meant to also work for vulkan mobile?

### Steps to reproduce

- add several plane meshes that butt up against each other
- add 3 or more omni lights and move them around to see the lighting overlap

### Minimal reproduction project

[omni_opengl.zip](https://github.com/godotengine/godot/files/10463259/omni_opengl.zip)

**Comment by Calinou** [comment]
> I don't usually use opengl in 4.0 but I was trying to use the light limit option to increase it for the vulkan mobile render. Is the opengl light limit render option meant to also work for vulkan mobile?

No, it only works for OpenGL.

**Comment by fracteed** [comment]
@Calinou does that mean an option to increase the limit is not even possiblein the future? It seems odd that opengl would have it and not Vulkan mobile, since it is the "higher end" of the 2 renderers.

Or at least some flexibility such as choosing the omni to spotlight ratio. Instead of 8 omnis/8 spots...in my case I only have one spot but lots of omnis. I think you guys are going to find that many people are going to want to use the "mobile" renderer for desktop as well when 4.0 is unleashed. It may very well end up being the most used of the 3 renderers as it has the best performance to feature ratio. I am getting massive gains in the mobile renderer for my game and moving to forward+ just for a few extra few lights is not worth it.

Even if there was a way to have more lights just for specific meshes, like the ground would be useful, since that is where I notice dropouts the most.

**Comment by Calinou** [comment]
> does that mean an option to increase the limit is not even possible in the future? It seems odd that opengl would have it and not Vulkan mobile, since it is the "higher end" of the 2 renderers.

Real-time light rendering is expensive on mobile platforms. Also, you should split your level into several meshes for culling efficiency reasons anyway.

> Or at least some flexibility such as choosing the omni to spotlight ratio. Instead of 8 omnis/8 spots...in my case I only have one spot but lots of omnis.

You can use SpotLights with very wide angles to mimic OmniLights, but only if they don't have shadows.

**Comment by fracteed** [comment]
I think it would be a mistake to think that most indie devs that use Godot 4 will be wanting the overhead of using the forward+ render. I am getting about 60-70% greater performance between the mobile and forward (with no loss of quality), and most likely many other devs will come to the same conclusion.

I do really hope that features and optimisations are also added to the "mobile" renderer in 4.x as it is very suitable for desktop games that want to target gtx1060 and below performance targets. Unless you really need TAA, GI or some of the screenspace effects it can be hard to justify the performance cost, but hopefully we do see serious performance improvements in the forward + in the future.

**Comment by ztc0611** [comment]
> does that mean an option to increase the limit is not even possible in the future? It seems odd that opengl would have it and not Vulkan mobile, since it is the "higher end" of the 2 renderers.
Or at least some flexibility such as choosing the omni to spotlight ratio. Instead of 8 omnis/8 spots...in my case I only have one spot but lots of omnis.

Putting a +1 on this for what it's worth, I think it is a bad choice to decide for the developer what is best for them. The iPhone 15 can process raytracing and run late-PS4 games. (and Android will not lag far behind) I think they could handle 16 omnilights at once with proper consideration (30fps cap, or only target newest devices). I also think this choice will only age worse with time as mobile devices get more and more powerful. Regardless, in my use case I could live with 16 omnilights and 0 spotlights far easier than a fixed 8 of each.
