### ISSUE TITLE
Pressing Return after changing value in the Inspector causes a node to enter Rename mode. macOS

### ISSUE THREAD

**Issue by Paladin-Caffeine** [godotengine/godot#71724]
### Godot version

4.0 beta 12 and 13

### System information

macOS 13 Ventura, Macbook Pro 2019, 16-inch

### Issue description

When I press the return key after making changes in the Inspector panel, it causes the current note in the Scene tree to enter Rename mode.

### Steps to reproduce

Select the node and in the Inspector panel change any value, such as scale or size, and press return. 

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
I can't seem to reproduce the issue on Linux, might be macOS specific. CC @bruvzg

**Comment by Sauermann** [comment]
Duplicates:  #71605 #69160
For Linux the problematic behavior was a bit different and got fixed in #69234

**Comment by Sauermann** [comment]
@JohnCWakley since this was closed as a duplicate, it is very likely, that your comment will be forgotten. May I suggest, that you create a new issue for the problem, that you have identified.
