### ISSUE TITLE
Godot 4 minimizing when you double-click any button in the title bar area, if the "Expand to Header" option is enabled. macOS

### ISSUE THREAD

**Issue by Paladin-Caffeine** [godotengine/godot#71721]
### Godot version

4.0 beta 13

### System information

macOS 13 Ventura, Macbook Pro 2019, 16-inch

### Issue description

In Godot 4, if a editor is expanded to a title bar, double clicking on any button in a title bar such as "Run Project" or "Stop Running Project" will result in minimizing or shrinking a Godot window. It is a small but quite annoying bug and it works in all Godot 4 betas I'v seen. 

### Steps to reproduce

Turn on "Expand to Title" in the Editor Settings/Interface/Editor, than double click on any button in the title area.

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
CC @bruvzg
