### ISSUE TITLE
RemoteTransform2D doesn't support Control nodes

### ISSUE THREAD

**Issue by eskandrej** [godotengine/godot#71723]
### Godot version

v4.0.beta.custom_build [3cc926bf7]

### System information

Windows 10, NVIDIA GeForce GTX 760

### Issue description

RemoteTransform2D description says that "RemoteTransform2D pushes its own Transform2D to another CanvasItem derived Node in the scene." but it doesn't accept Control which is a derived CanvasItem node.

### Steps to reproduce

Add RemoteTransform2D to scene and try add path of Control to remote path.

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
The docs are incorrect, it only works with Node2D.

**Comment by aXu-AP** [comment]
As a side note, you can get it to work if you make your control a child of Node2D, and remote transform that.
