### ISSUE TITLE
filter_linear_mipmaps is not a valid shader type hint on beta 14

### ISSUE THREAD

**Issue by Gnumaru** [godotengine/godot#71736]
### Godot version

4.0.beta14

### System information

windows 10, gles 3, nvidia graphics

### Issue description

SCREEN_TEXTURE  was dropped in beta 14. The suggested replacement is to use ```uniform sampler2D SCREEN_TEXTURE : hint_screen_texture, filter_linear_mipmaps;```, but filter_linear_mipmaps is not recognized as a valid shader type hint and a shader using it fails to compile.

### Steps to reproduce

Create a canvas item shader and use the filter_linear_mipmaps type hint with a sampler2D uniform.

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
That seems to be a typo in the error message, it should be `filter_linear_mipmap`.

**Comment by Gnumaru** [comment]
Indeed, its just a typo in the error message. Using ```filter_linear_mipmap``` without the 's' in the end works as expected.
