### ISSUE TITLE
cannot drag a node from the scene tree view inside the script editor to copy/paste the nodepath on beta 14

### ISSUE THREAD

**Issue by Gnumaru** [godotengine/godot#71737]
### Godot version

4.0beta14

### System information

windows 10, gles 3, nvidia graphics

### Issue description

on beta 14, you cannot drag anymore a node from the scene tree to the script editor to get the node path or the ```@onready``` var snippet

### Steps to reproduce

Using beta 14, try to drag a node from the tree inside the script editor and see the arrow cursor turn into a circular white and red stop sign icon.

Note that this happens even if the script belongs to the currently opened scene.

### Minimal reproduction project

N/A

**Comment by 01010100010100100100100101000111** [comment]
Just to add this was working in Beta 13

**Comment by KoBeWi** [comment]
I can confirm this. Same issue with files.
