### ISSUE TITLE
Marked as Win32/Heim.C when steam is updating GODOT

### ISSUE THREAD

**Issue by splite** [godotengine/godot#7173]
**Operating system or device - Godot version:** Windows7, Steam, AVG

**Issue description** (what happened, and what was expected): When Steam is downloading new GODOT patch, AVG is marking files

godot.windows.opt.tools.32.exe
windows_32_debug.exe
windows_32_release.exe
windows_64_debug.exe
windows_64_release.exe

as infected with [Win32/Heim.C](http://www.avgthreatlabs.com/us-en/virus-and-malware-information/info/win-heim)

Probably false positive, just letting you know. [You can submit false-positive report here](https://secure.avg.com/submit-sample)

![godot_heimc](https://cloud.githubusercontent.com/assets/4945875/20516801/87a85ae4-b098-11e6-9868-dca983627920.png)

(screenshot is in czech language but i think it is self explanatory)

**Steps to reproduce:**
Steam auto update.

Posibly related with #3665

**Comment by akien-mga** [comment]
Could you submit to `godot.windows.opt.tools.32.exe` binary as false positive with the link given above? I don't have AVG myself, so it's best if it's reported by an actual user.

I'm pretty sure we did not put a virus in those binaries :P

**Comment by splite** [comment]
Ok, i tried when you ask. I tried it twice. But no, the submit server is broken. They say "max 20 mb" (opt.tools.32.exe is 24 mb), so i tried windows_64_release.exe, which is in limit - but without luck, i only see "std-full" error.

**Comment by vnen** [comment]
AVG is a bit paranoid (it even [tagged Windows apps as viruses](http://answers.microsoft.com/en-us/windows/forum/windows_10-security/recent-update-to-microsoft-photoviewer-flagged-as/9da8f3cd-7734-4188-a796-a15e462a92d1)). Though I agree that is better to mistag a valid application than to let pass a virus. But unless Steam is changing the binaries, there is no virus in Godot (you could also test the one downloaded from the [website](https://godotengine.org/download) for comparison).

Anyway, will try to whitelist Godot in the AVG database.

**Comment by vnen** [comment]
AVG site is bailing on me too...

**Comment by splite** [comment]
Downloaded version is marked as "infected" too. I just hope your build server is not compromised :) But becouse avg is the only one flagging godot binaries as a virus, i am pretty sure it is false positive.

**Comment by vnen** [comment]
I'm talking to the AVG support to see if there's anything that can be done.

**Comment by SuperUserNameMan** [comment]
> Downloaded version is marked as "infected" too. I just hope your build server is not compromised :)

It'd be intereesting to test with a self compiled version maybe too ?

If you have some time, here is a version i compiled last month with MSVC2015 (it's 17MB) :

https://drive.google.com/file/d/0BwPrOdeAV28fOC1aM25qejVTQ2c/view

(it is not zipped, so Google should have scanned it for virus already)

**Comment by splite** [comment]
> If you have some time, here is a version i compiled last month with MSVC2015 (it's 17MB) :

Tested, AVG says its clean.

**Comment by SuperUserNameMan** [comment]
@splite : thanks for testing.

@vnen, @Calinou, @akien-mga : isn't the official Windows release compiled with MSVC2015 too ?

**Comment by akien-mga** [comment]
> isn't the official Windows release compiled with MSVC2015 too ?

Yes: https://github.com/GodotBuilder/godot-builds/blob/master/appveyor.yml#L1

**Comment by techtonik** [comment]
Closing?

**Comment by akien-mga** [comment]
Assuming fixed by now, no new reports since one year.

**Comment by splite** [comment]
Cant test again, we didnt even use AVG anymore... :)
