### ISSUE TITLE
Editor sets a limit of 0 on dof_blur_near_transition and dof_blur_far_transition camera attributes, even though they can be negative

### ISSUE THREAD

**Issue by timshannon** [godotengine/godot#71743]
### Godot version

v4.0.beta13.mono.official [caacade56]

### System information

Ubuntu 22.10

### Issue description

Small issue, but according to the documentation you can set the `dof_blur_near_transition` and `dof_blur_far_transition` practical camera attributes to [negative values](https://docs.godotengine.org/en/latest/classes/class_cameraattributespractical.html#class-cameraattributespractical-property-dof-blur-far-distance), but the editor / property hints only lets you set it to 0.01 and no lower, so you have to set the value in code.

![image](https://user-images.githubusercontent.com/1330485/213751772-e423ca8a-ad24-4c4a-9ac9-fb386e10de5a.png)

### Steps to reproduce

1. Add a camera
2. Add practical camera attributes
3. Enable Near or Far DOF
4. Try to set the Transition to a negative value

### Minimal reproduction project

N/A

**Comment by vortexofdoom** [comment]
Was gonna claim this, what should the minimum value be?

**Comment by timshannon** [comment]
I'm pretty sure it just needs to be any negative value, so you could set it -1 I suppose.
