### ISSUE TITLE
Viewport Gizmos don't show in new Projects

### ISSUE THREAD

**Issue by VenomousInc** [godotengine/godot#71755]
### Godot version

4.0.beta14

### System information

Windows 10

### Issue description

Viewport Gizmos do not show when starting a new Project until you reload your Project or Godot, even when toggling the Gizmos inside of the Editor Settings.

### Steps to reproduce

1. Open Godot to the Project List Manager
2. Create a new Project
3. Switch to a Viewport and notice the Gizmos

I have located gizmos and checked it is turned on:
1. Editor > Editor Settings
2. editors/3d/navigation/show_viewport_rotation_gizmo

editors/3d/navigation/show_viewport_rotation_gizmo is by default turned on, but not displaying anything in the viewport.
Toggling it does not produce the Gizmo to the viewport, the only way I found to fix it:
- [x] Project > Reload Current Project
- [x] Project > Quit to Project List > Open the new Project

### Minimal reproduction project

N/A - Must be a freshly created project

**Comment by Calinou** [comment]
Can you reproduce this in any of the [4.0 betas](https://downloads.tuxfamily.org/godotengine/4.0/) to determine when the regression started?

**Comment by VenomousInc** [comment]
I don't know when it started, and I will take some time to go back and see but I do know it was happening in 4.0 Beta 12, as I updated to 14 before posting this just to check it wasn't already fixed.

**Comment by VenomousInc** [comment]
I have tested the following versions and they're fine:

- [x] 4.0.alpha.1
- [x] 4.0.beta.1
- [x] 4.0.beta.5
- [x] 4.0.beta.8 
- [x] 4.0.beta.15 - Seems to be fixed in this latest one!

Regression found in:
-  **`4.0.beta.9`** through to **`4.0.beta.14`**

While testing I tried the latest version, which is **`4.0.beta.15`** at the time of writing this.
It does seem to be fixed now, so that is great.

**Comment by Calinou** [comment]
@ti5jrur-ok Please open a new issue *with a minimal reproduction project attached*.
