### ISSUE TITLE
Godot 4.0 crashes on Mac when creating new project

### ISSUE THREAD

**Issue by bandaloo** [godotengine/godot#71751]
### Godot version

4.0-beta-10

### System information

macOS Ventura 13.1

### Issue description

On the Standard and mono versions of the universal Mac binary, Godot crashes when I create a new empty project. I wish I had more details but if a contributor wants me to check anything specific so I can add more detail, just ask; I'll be responsive and try to be as helpful as possible. (If there is a crash log I can dig up, for example.)

These are the specs of my machine:

MacBook Pro: 13-inch, 2017, Four Thunderbolt 3 Ports
3.5 GHz Dual-Core Intel Core i7
Intel Iris Plus Graphics 650 1536 MB
16 GB 2133 MHz LPDDR3
Ventura 13.1

### Steps to reproduce

Install Godot 4.0 beta 10, create a new project from the dialog box.

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
Could you test on Beta 14 which is the latest beta right now?

**Comment by bandaloo** [comment]
@clayjohn yep, it works! accidentally downloaded beta 10 since it was the first search result; my bad. i'll just close the issue

**Comment by clayjohn** [comment]
> @clayjohn yep, it works! accidentally downloaded beta 10 since it was the first search result; my bad. i'll just close the issue

Glad to hear that its working for you now!
