### ISSUE TITLE
Advanced Importer `Actions...` button looks weird in some themes

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#71762]
### Godot version

4.0.beta13
`
### System information

Windows 10, Nvidia Vulkan

### Issue description

The advanced importer has a button in the top left called Actions... but it is not themed like a normal clickable button.
before:
![old image](https://user-images.githubusercontent.com/39946030/213795860-db5aa537-aa4c-42f1-92c1-97b5d46f2958.png)
after beta14:
![new image](https://user-images.githubusercontent.com/39946030/213848392-68f178db-7a1d-4c3d-8baa-9339702ef7c5.png)

Users who import models will see greyed out read-only materials. The obvious, but wrong/bad solution is to use "Make Local" on the imported scene nodes which will duplicate all mesh data into the current scene.

To make imported materials editable, the correct workflow involves going to the Advanced importer, and either going to the Materials tab and selecting Save to File one-by-one, or using the "Actions..." button on the top left to bulk-extract all materials which is the menu which is hardest to find.

In short, "Extract Materials" is the most efficient and preferred workflow for customizing materials of imported files. This feature was on by default in 3.x, but as of 4.0, new users are likely going to want to find this.

Source: https://chat.godotengine.org/channel/devel?msg=LdhDzZG4MhvFzpZSm - this user was not able to find the Extract Materials button without my help.

I see two fixes:
1. Make the Actions... menu/button more obvious: add a button border, or an icon in addition, or put an arrow saying click here.
2. Make the top bar into a toolbar and migrate the three buttons currently in the "Actions..." menu into top-level buttons on the toolbar, for example
`Extract Materials    |    Set Animation Save Paths    Set Mesh Save Paths`

(side note, I'm not sure why materials get "Extracted" but animations and meshes "Set Save Paths". I'm pretty sure the functionality is the same for all three resource types. In that case, I would expect:
`Extract Materials     Extract Animations     Extract Meshes`

### Steps to reproduce

1. Import a model
2. Fail to find any editable materials
3. Go to the Advanced Importer
4. Look for the button to "extract materials"

### Minimal reproduction project

UI looks the same for all imported .glb or .fbx models.

**Comment by Maran23** [comment]
Related to https://github.com/godotengine/godot-proposals/issues/6115

**Comment by m4rr5** [comment]
@lyuma kindly explained this to me after I embarked on a workflow involving "Make Local" with the only goal to redefine a bunch of materials in an imported (big) mesh. I had totally overlooked that button!

**Comment by MewPurPur** [comment]
I thought it was fixed in https://github.com/godotengine/godot/pull/71582?

**Comment by lyuma** [comment]
I do see the change on beta 14!

I was on my build which was halfway between beta 13 and beta 14 but I guess it just dodged that commit. What luck that I finally decided to file this issue and it happened to be 3 days after the bugfix was merged.

On my system, the theme makes the button hard to read, but at least it's more visible now.

![image](https://user-images.githubusercontent.com/39946030/213848392-68f178db-7a1d-4c3d-8baa-9339702ef7c5.png)

**Comment by MewPurPur** [comment]
So this was fixed then?

**Comment by Calinou** [comment]
This seems to be resolved. This is how it looks as of 4.0.2:

### Dark theme

![image](https://user-images.githubusercontent.com/180032/232637798-91567ab7-d247-4bd4-9fde-900b958d03bb.png)

### Light theme

![image](https://user-images.githubusercontent.com/180032/232637857-a5e91986-b865-4d86-ba4f-53e7312c6444.png)
