### ISSUE TITLE
Graphical glitches with spotight3d and low angle

### ISSUE THREAD

**Issue by Euphoreka7** [godotengine/godot#71765]
### Godot version

v4.0.beta13

### System information

Windows11. rtx 3080 (lates drivers), vulkan

### Issue description

<img width="305" alt="image" src="https://user-images.githubusercontent.com/10160367/213803065-d09efa28-f1e2-437e-bc43-c0a248e83db5.png">

this bug exists at least from beta2

it works better in compatibility mode. but adds unneeded effect:
<img width="749" alt="image" src="https://user-images.githubusercontent.com/10160367/213803719-235672ce-355d-49a0-b6c3-d698dd4ad77f.png">

### Steps to reproduce

- add mesh instance
- add spotlight3d
- rotate spotlight3d to mesh and decrease angle to 1-3

### Minimal reproduction project

[tmp.zip](https://github.com/godotengine/godot/files/10470169/tmp.zip)

**Comment by clayjohn** [comment]
I think this might be the same as https://github.com/godotengine/godot/issues/70698
