### ISSUE TITLE
Merge From Scene option is missing from Scene right click menu

### ISSUE THREAD

**Issue by blackears** [godotengine/godot#71773]
### Godot version

v4.0.beta13.official [caacade56]

### System information

Windows 10, GLES 3,

### Issue description

The Merge From Scene option in the right click Scene menu that is present in Godot 3.5 does not appear in Godot 4.0beta13.  I find this option to be very useful to quickly copy nodes and think it would be a good idea to include it in Godot 4.

### Steps to reproduce

Right click in the Scene area and examine the menu options.  Merge From Scene does not appear, and there does not seem to be any similar option.

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
It was replaced fully by the ability to copy-paste nodes directly across scenes.

**Comment by Calinou** [comment]
For reference, Merge from Scene was removed by https://github.com/godotengine/godot/pull/45943.
