### ISSUE TITLE
@tool broken

### ISSUE THREAD

**Issue by rainlizard** [godotengine/godot#71782]
### Godot version

Godot_v4.0-beta14_win64

### System information

Windows 10

### Issue description

Simple bug report, it's just busted.

### Steps to reproduce

Write it and the error at the bottom says `Annotation "@tool" is not allowed in this level.`

### Minimal reproduction project

N/A

**Comment by dalexeev** [comment]
`@tool` and `@icon` must be placed at the very beginning of the script, above `class_name` and `extends`. See #67774.

**Comment by rainlizard** [comment]
Thank you, error could be more informative.
