### ISSUE TITLE
Directory.get_current_dir() only returning relative path

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot#7179]
**Windows 10 - Godot 2.1.1**

**Issue description** (what happened, and what was expected):
What happened: Directory.get_current_dir() returning only relative path
What was expected: Directory.get_current_dir() returning also (or only) absolute path

**Steps to reproduce:**

1. Create any script
2. inside the _ready() function put a print(Directory.new().get_current_dir())
3. look at the output

**Comment by vnen** [comment]
`Directory.new().get_current_dir()` returns `res://` for me, which is the expected result.

**Comment by volzhs** [comment]
I guess @henriiquecampos already get idea to get absolute path of `res://` now.
```gdscript
Globals.globalize_path(Directory.new().get_current_dir())
```

**Comment by bojidar-bg** [comment]
@volzhs Slight nitpick, this would be simpler and faster (assuming this is a non-bug):
```gdscript
Globals.globalize_path("res://")
```

**Comment by henriiquecampos** [comment]
It's because the doccumentation tells this:

"String get_current_dir()
Return the absolute path to the currently opened directory (e.g. res://folder or C:\tmp\folder)."

**Comment by bojidar-bg** [comment]
Ok, labeling as a documentation issue then.

**Comment by vnen** [comment]
I don't see what's wrong with the documentation. Maybe just needs to state that by default `res://` is the current open folder, if you didn't call `open()`.

**Comment by bojidar-bg** [comment]
@vnen Emphasis:
> Return the **absolute** path to the currently opened directory (e.g. __res://folder__ or C:\tmp\folder).
Then, it is either not really absolute, or `res://folder` is absolute.

**Comment by akien-mga** [comment]
I'm the one who wrote this, and I considered that `res://folder` is absolute, as opposed to `../folder` which would be relative, if you were in `res://otherfolder`. That's the same semantics I used for the whole Directory doc.

**Comment by akien-mga** [comment]
See `open()` and `change_dir()` descriptions for more details: http://docs.godotengine.org/en/latest/classes/class_directory.html

**Comment by vnen** [comment]
Yes, in my point of view, `res://folder` is an absolute path inside the resources filesystem.

**Comment by bojidar-bg** [comment]
Ok, since doc mentions that res://folder is returnable by the function, I guess, I agree too.

Therefore, I'm closing this as invalid documentation issue -- though, if you really feel it is unclear, it might be reopened (or maybe open another one, if you read this in the far future..).

**Comment by henriiquecampos** [comment]
To be honest, for other people that is not aligned with how Godot handles filesystem, "absolute" means the path in which the project is, i.e ("C:/Users/Henrique/Desktop/Game Development/Project Folder"), "res://" is basically a relative path, since it does not actually exists in the computer, I can't actually place "res://" in my file explorer. I would really recommend to change the docs to "absolute path of the current opened dir in internal filesystem" or to erase "absolute" path.
