### ISSUE TITLE
Unindenting a line without selection in CodeEdit happens after a noticeable delay

### ISSUE THREAD

**Issue by Yagich** [godotengine/godot#71794]
### Godot version

4.0b14

### System information

Linux/Manjaro

### Issue description

After #60904 added back unindenting lines without a selection, hitting shift+tab without a selection unindents the line after a noticeable delay.

### Steps to reproduce

1. Put the cursor on an indented line;
2. Hit Shift+Tab.

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
CC @Paulb23 @KoBeWi
