### ISSUE TITLE
Array.map generates "STANDALONE_EXPRESSION" warning

### ISSUE THREAD

**Issue by adamscoble** [godotengine/godot#71791]
### Godot version

4.0.beta13.official

### System information

Windows 10

### Issue description

When using `Array.map` on a line I receive the following warning:

`Line ## (STANDALONE_EXPRESSION): Standalone expression (the line has no effect).`

### Steps to reproduce

Create a class with the below function, create an instance of it somewhere and run the application:
```
func _init() -> void:
	var storage: Dictionary = { &"first": 1, &"second": 2, &"third": 3 }
	var names: Array[StringName] = [&"first", &"second", &"third"]
	var values = names.map(func(name: StringName): storage[name])
```
You should receive a warning for the `var values` line.

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
Your lambda does not have `return`.

**Comment by adamscoble** [comment]
@KoBeWi Oh man betrayed by C#. Apologies!

**Comment by nightblade9** [comment]
> Your lambda does not have `return`.

This finally solved my problem, thank you! In my case, it was `var something = get_children().all(func(h): h.health <= 0`. Setting the lambda to `return h.health <= 0` solved it.

Would be great if the warning would be clearer in this case (as opposed to the case when you use `==` instead of `=`)
