### ISSUE TITLE
OpenGL: Window stretch mode `canvas_items` or `viewport` leaves uncleared section if using `keep`, `keep_width` or `keep_height` stretch aspect

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#71799]
### Godot version

v4.0.beta13.official [caacade56]

### System information

Debian 11

### Issue description

I noticed this rendering issue. 
It not happen in "Forward" or "Mobile" mode.
It happen when I set project settings->display->windows->stretch->mode as canvas_item or viewport.

I do not use NVIDIA card 
![DeepinScreenshot_select-area_20230121111325](https://user-images.githubusercontent.com/13235119/213862518-d48a6b2e-e6ef-45b0-b389-4f8392a9a1c4.png)

this is a screen shoot
![DeepinScreenshot_select-area_20230121143842](https://user-images.githubusercontent.com/13235119/213869396-f425f38a-3d61-4fa6-a2e0-b57d5bb5dc2e.png)

EDIT: I tried it in another computer
v4.0.beta12.official [3c9bf4bc2]
Debian 10
```

Godot Engine v4.0.beta12.official.3c9bf4bc2 - https://godotengine.org
OpenGL Renderer: Mesa DRI Intel(R) Ivybridge Mobile
```

![DeepinScreenshot_select-area_20230121132211](https://user-images.githubusercontent.com/13235119/213869067-c56e1afa-6e3b-4ea8-9363-afaf90cc5934.png)

### Steps to reproduce

run the MRP and resize the window

### Minimal reproduction project

[test_resolution.zip](https://github.com/godotengine/godot/files/10471955/test_resolution.zip)

**Comment by acedogblast** [comment]
Can confirm that this bug still exists with Godot 4.0 RC1. The bug only effects the OpenGL renderer. Using Linux/Wayland with AMD GPU.

**Comment by clayjohn** [comment]
Looks like we have reports for this issue from all desktop OSes now, so it definitely isn't an X11 windowing issue. I will take a look

**Comment by git2013vb** [comment]
It seems very similar to this issue #48091 
Not sure if its related, maybe at that time this issue came out just in that particular case... We will see.

**Comment by clayjohn** [comment]
@git2013vb I don't think this is related to #48091. This issue was caused by 4.0-specific changes that are not in 3.x
