### ISSUE TITLE
Deleting autoloaded enum that's being referenced causes editor crash until manually removed from autoload

### ISSUE THREAD

**Issue by the-quick-red-fox** [godotengine/godot#71793]
### Godot version

v4.0.beta12.official [3c9bf4bc2]

### System information

Fedora36.x86_64, AMD Ryzen R7 5800X3D, 6800XT, Vulkan

### Issue description

Removing a certain autoloaded file crashes the editor and will keep it crashing until project.godot file is manually edited to remove the autoload reference.

### Steps to reproduce

1. Create new project on forward+
2. Create new script that extends Node
3. Create a named enum in script, e.g.: `enum Example { ONE = 1, TWO = 2}`
4. Open project settings and autoload the script
5. Create a new Node in the default scene and attach a new script to it
6. Reference the enum in the global script in an exported variable, e.g.: `@export var example: Global.Example`
7. Save scripts and scene
8. Use the editor's filebrowser to delete the global script

Alternatively:
1. Unpack Example.zip
2. Import the project
3. Open in editor
4. Use the editor's filebrowser to delete global.gd

To stop the editor from crashing while loading the project:
1. open project.godot in system filebrowser
5. remove the script reference in the `[autoload]` section

### Minimal reproduction project

[Example.zip](https://github.com/godotengine/godot/files/10471679/Example.zip)

**Comment by YuriSizov** [comment]
Can't reproduce with the current version, RC2.

**Comment by YuriSizov** [comment]
Okay, I didn't get the initial crash, but it does indeed fail to load the project after that.

![image](https://user-images.githubusercontent.com/11782833/218868507-4614a543-b1b0-4aaf-b3f4-707bda9cb32e.png)
