### ISSUE TITLE
[GDExtension] Crash at "ready" function.

### ISSUE THREAD

**Issue by hakuhan** [godotengine/godot#71796]
### Godot version

4.0 beta 14

### System information

Windows 11, MacOS also

### Issue description

Callstack:

```
> CrashHandlerException: Program crashed
> Engine version: Godot Engine v4.0.beta.custom_build (4db3716d8d9bbc95c031818b190002602558b0f2)
> Dumping the backtrace. Please include this when reporting the bug to the project developer.
> [0] <couldn't map PC to fn name>
> [1] <couldn't map PC to fn name>
> [2] GDScriptFunction::call (C:\Users\xx\Documents\godot\modules\gdscript\gdscript_vm.cpp:2000)
> [3] GDScriptInstance::callp (C:\Users\xx\Documents\godot\modules\gdscript\gdscript.cpp:1838)
> [4] Node::_notification (C:\Users\xx\Documents\godot\scene\main\node.cpp:155)
> [5] Object::notification (C:\Users\xx\Documents\godot\core\object\object.cpp:792)
> [6] Node::_propagate_ready (C:\Users\xx\Documents\godot\scene\main\node.cpp:189)
> [7] Node::_propagate_ready (C:\Users\xx\Documents\godot\scene\main\node.cpp:179)
> [8] Node::_propagate_ready (C:\Users\xx\Documents\godot\scene\main\node.cpp:179)
> [9] Node::_propagate_ready (C:\Users\xx\Documents\godot\scene\main\node.cpp:179)
> [10] Node::_set_tree (C:\Users\xx\Documents\godot\scene\main\node.cpp:2595)
> [11] SceneTree::initialize (C:\Users\xx\Documents\godot\scene\main\scene_tree.cpp:411)
> [12] OS_Windows::run (C:\Users\xx\Documents\godot\platform\windows\os_windows.cpp:1288)
> [13] widechar_main (C:\Users\xx\Documents\godot\platform\windows\godot_windows.cpp:181)
> [14] _main (C:\Users\xx\Documents\godot\platform\windows\godot_windows.cpp:205)
> [15] main (C:\Users\xx\Documents\godot\platform\windows\godot_windows.cpp:217)
> [16] __scrt_common_main_seh (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
> [17] <couldn't map PC to fn name>
> -- END OF BACKTRACE --
> ================================================================

```

<img width="1195" alt="image" src="https://user-images.githubusercontent.com/18411187/213860152-6ef7ec40-c069-4724-9286-4a5f98376a55.png">

These crashes are not caused by GDExtension codes from my test.

### Steps to reproduce

Just launch game.

### Minimal reproduction project

[mini_project.zip](https://github.com/godotengine/godot/files/10471840/mini_project.zip)

**Comment by RicardRC** [comment]
Related? https://github.com/godotengine/godot/issues/71483

**Comment by hakuhan** [comment]
> Related? #71483

I'm not sure. When I comment "_ready" function in my original project. It will crash for similar reason.

**Comment by hakuhan** [comment]
@RicardRC  I can still reproduce it at beta 16. Maybe it is not same issue with #71483 
<img width="991" alt="image" src="https://user-images.githubusercontent.com/18411187/215512491-fc14d0d3-9860-4bb9-9160-044246775f2b.png">
 I was working at beta 12. Because my project has alot of tasks. So I have little time to fix it sorry.

**Comment by hakuhan** [comment]
From my test. First crash happened when I call a method from gdtextension. And this method has a parameter which type is "Object*", I modify it:
<img width="310" alt="image" src="https://user-images.githubusercontent.com/18411187/218254196-350f8fd1-421b-4efb-84fe-e82040d30e2f.png">
Crash passed. And Then I meat another crash which is very simular with first crash. In gdscript I called a method:
<img width="439" alt="image" src="https://user-images.githubusercontent.com/18411187/218254249-c3491074-6df2-43d1-ac9b-9d960982b0c6.png">
which parameter is a custom "Resource" data. I'm a little confused. 
@Chaosus @RicardRC  Is it caused by by my wrong parameter type?

**Comment by hakuhan** [comment]
From my test. This issue appears after godot: "7502e1dc0da15334f88911a802fa6ba919b6c83c" and godot-cpp: "992d85e6f845d798ab26237fe52d1aa6461452c5" submitions. Mutex in object is not initailized maybe. I haven't figer out why does  Ref reference sent back a object with wrong mutex.

**Comment by hakuhan** [comment]
> From my test. This issue appears after godot: "7502e1dc0da15334f88911a802fa6ba919b6c83c" and godot-cpp: "992d85e6f845d798ab26237fe52d1aa6461452c5" submitions. Mutex in object is not initailized maybe. I haven't figer out why does Ref reference sent back a object with wrong mutex. @BastiaanOlij Would you please help me for this issue if you have time?

I reset these changes back. But crash still there.

**Comment by hakuhan** [comment]
When I change all parameters type of C++ functions which will be called at gdscript "lifetime functions" (_ready, _process and so on) from Object*, Ref<Resource> to Variant. Crashes are gone.:>. But I think there has something wrong  with passing parameters from gdscript to C++ function.

**Comment by akien-mga** [comment]
Can you still reproduce this in 4.0.3 and 4.1-beta3 or later?

**Comment by hakuhan** [comment]
Sorry to replay later. It was fixed at godot-cpp repor
