### ISSUE TITLE
4.0 beta 10 cannot run Android applications correctly when exporting apk and obb files using apk expansion.

### ISSUE THREAD

**Issue by Atem1995** [godotengine/godot#71808]
### Godot version

4.0 Beta 10

### System information

Android

### Issue description

4.0 beta 10 cannot run Android applications correctly when exporting apk and obb files using apk expansion. There is another question. How to configure apk expansion? There is no corresponding document.I have configured obb's unique package path folder, but it is still unresponsive. Sometimes it will flash back directly, and the obb file will be deleted automatically.
![94429fc0bad8537801afbf2dab5cabd](https://user-images.githubusercontent.com/52338846/213869914-8a1ea2ad-aa1d-44f1-80ac-f8179e38337d.jpg)
![96afb63542a1f2da592583367eb463f](https://user-images.githubusercontent.com/52338846/213869917-b849a579-9253-44e8-9c1d-fd0cf4a1398c.jpg)

### Steps to reproduce

略

### Minimal reproduction project

略

**Comment by Atem1995** [comment]
![捕获](https://user-images.githubusercontent.com/52338846/213872261-21621757-3f25-4aab-98c8-f760223c448c.PNG)
On window10, a similar situation will occur after exporting using a custom template.

**Comment by akien-mga** [comment]
Again, please include steps to reproduce the issue, or a minimal reproduction project.

Without this information, we can't reproduce the issue to see if it's a bug or a mistake on your end.

**Comment by Atem1995** [comment]
> Again, please include steps to reproduce the issue, or a minimal reproduction project.
> 
> Without this information, we can't reproduce the issue to see if it's a bug or a mistake on your end.

Excuse me, can you tell me how to configure APK expansion? I think it may be caused by my configuration error. There is no relevant document to tell us how to operate it.

**Comment by YuriSizov** [comment]
We can't tell you what to change in the configuration if you don't explain exactly what you are doing, I'm sorry.
