### ISSUE TITLE
[4 Beta 13] OptionButton crashes on Android

### ISSUE THREAD

**Issue by DerKusti** [godotengine/godot#71802]
### Godot version

4.0 Beta 13

### System information

Android 10, Samsung Galaxy S9

### Issue description

Opening an option button crashes the app on Android, after showing the menu with the various options for a split-second.
This only affects one of 3 option buttons (which I created with copy-paste, only the contained options are different, so maybe there is the problem), and it only occurs when compiling with Beta 13. Compiling the same project with Beta 9 results in the OptionButton working as expected.

Running the app from the editor on Windows rather than deploying to the device, the bug does not occur. Only on the Android device.

(Development is done on Windows 10, in case it matters; I have tried both apk export with adb install and installing & running directly from Godot Editor, makes no difference)

Logcat output (filtered by com.godot) after crash:

01-21 12:08:32.354  1006 21012 W ActivityTaskManager:   Force finishing activity org.godotengine.cncchargen/com.godot.game.GodotApp
01-21 12:08:32.357  1006 21012 V WindowManager: Changing focus from Window{3fadef4 u0 org.godotengine.cncchargen/com.godot.game.GodotApp} to null displayId=0 Callers=com.android.server.wm.RootWindowContainer.updateFocusedWindowLocked:204 com.android.server.wm.WindowManagerService.updateFocusedWindowLocked:6458 com.android.server.wm.ActivityDisplay.setFocusedApp:1686 com.android.server.wm.ActivityTaskManagerService.setResumedActivityUncheckLocked:6980 com.android.server.wm.ActivityRecord.moveFocusableActivityToTop:1947 com.android.server.wm.ActivityDisplay.moveHomeActivityToTop:1778
01-21 12:08:32.404  1006  1056 I WindowManager: Focus moving from Window{3fadef4 u0 org.godotengine.cncchargen/com.godot.game.GodotApp} to null displayId=0
01-21 12:08:32.404  1006  1056 I WindowManager: Losing focus: Window{3fadef4 u0 org.godotengine.cncchargen/com.godot.game.GodotApp}
01-21 12:08:32.406  1006  1219 W InputDispatcher: channel '3fadef4 org.godotengine.cncchargen/com.godot.game.GodotApp (server)' ~ Consumer closed input channel or an error occurred.  events=0x9, fd=464
01-21 12:08:32.406  1006  1219 E InputDispatcher: channel '3fadef4 org.godotengine.cncchargen/com.godot.game.GodotApp (server)' ~ Channel is unrecoverably broken and will be disposed!
01-21 12:08:32.406  1006  1056 E WindowManager: RemoteException occurs on reporting focusChanged, w=Window{3fadef4 u0 org.godotengine.cncchargen/com.godot.game.GodotApp}
01-21 12:08:32.422   523  1215 I SurfaceFlinger: id=108 Removed Bounds for - org.godotengine.cncchargen/com.godot.game.GodotApp@0#0 (47)
01-21 12:08:32.423   523  1849 I SurfaceFlinger: id=109 Removed SurfaceView - org.godotengine.cncchargen/com.godot.game.GodotApp@beb64d9@0#0 (47)
01-21 12:08:32.424   523  1849 I SurfaceFlinger: id=110 Removed Background for -SurfaceView - org.godotengine.cncchargen/com.godot.game.GodotApp@beb64d9@0#0 (47)
01-21 12:08:32.424  1006  2891 I WindowManager: WIN DEATH: Window{3fadef4 u0 org.godotengine.cncchargen/com.godot.game.GodotApp}
01-21 12:08:32.424  1006  2891 W InputDispatcher: Attempted to unregister already unregistered input channel '3fadef4 org.godotengine.cncchargen/com.godot.game.GodotApp (server)'
01-21 12:08:32.444  1006  2759 V WindowManager: Setting visibility of Window{3fadef4 u0 org.godotengine.cncchargen/com.godot.game.GodotApp EXITING}: false, caller=com.android.server.wm.WindowContainer.sendAppVisibilityToClients:644 com.android.server.wm.AppWindowToken.setClientHidden:632 com.android.server.wm.AppWindowToken.onAnimationFinished:3913 com.android.server.wm.AppWindowToken.commitVisibility:914 com.android.server.wm.AppWindowToken.onRemovedFromDisplay:1146
01-21 12:08:32.444  1006  2759 E WindowManager: win=Window{3fadef4 u0 org.godotengine.cncchargen/com.godot.game.GodotApp EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0 caller=com.android.server.wm.AppWindowToken.destroySurfaces:1249 com.android.server.wm.AppWindowToken.destroySurfaces:1230 com.android.server.wm.WindowState.onExitAnimationDone:5189 com.android.server.wm.-$$Lambda$01bPtngJg5AqEoOWfW3rWfV7MH4.accept:2 java.util.ArrayList.forEach:1262 com.android.server.wm.AppWindowToken.onAnimationFinished:3941 com.android.server.wm.AppWindowToken.commitVisibility:914
01-21 12:08:32.445  1006  2759 I WindowManager: Destroying surface Surface(name=org.godotengine.cncchargen/com.godot.game.GodotApp$_1364)/@0xbfbf299 called by com.android.server.wm.WindowStateAnimator.destroySurface:1834 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:733 com.android.server.wm.WindowState.destroySurfaceUnchecked:3649 com.android.server.wm.WindowState.destroySurface:3623 com.android.server.wm.AppWindowToken.destroySurfaces:1249 com.android.server.wm.AppWindowToken.destroySurfaces:1230 com.android.server.wm.WindowState.onExitAnimationDone:5189 com.android.server.wm.-$$Lambda$01bPtngJg5AqEoOWfW3rWfV7MH4.accept:2
01-21 12:08:32.445   523  1849 I Layer   : id=108 removeFromCurrentState Bounds for - org.godotengine.cncchargen/com.godot.game.GodotApp@0#0 (47)
01-21 12:08:32.445   523  1849 I Layer   : id=110 removeFromCurrentState Background for -SurfaceView - org.godotengine.cncchargen/com.godot.game.GodotApp@beb64d9@0#0 (47)
01-21 12:08:32.445   523  1849 I Layer   : id=109 removeFromCurrentState SurfaceView - org.godotengine.cncchargen/com.godot.game.GodotApp@beb64d9@0#0 (47)
01-21 12:08:32.445   523  1849 I Layer   : id=107 removeFromCurrentState org.godotengine.cncchargen/com.godot.game.GodotApp$_1364#0 (47)
01-21 12:08:32.447   523  1849 I Layer   : id=106 removeFromCurrentState 3fadef4 org.godotengine.cncchargen/com.godot.game.GodotApp#0 (47)
01-21 12:08:32.449   523  1849 I SurfaceFlinger: id=106 Removed 3fadef4 org.godotengine.cncchargen/com.godot.game.GodotApp#0 (47)
01-21 12:08:32.449   523  1849 I SurfaceFlinger: id=107 Removed org.godotengine.cncchargen/com.godot.game.GodotApp$_1364#0 (47)
01-21 12:08:32.451   523  2155 I Layer   : id=99 removeFromCurrentState AppWindowToken{2482a1a token=Token{a6020c5 ActivityRecord{6d66b3c u0 org.godotengine.cncchargen/com.godot.game.GodotApp t41}}}#0 (47)
01-21 12:08:32.451   523  2155 I Layer   : id=99 removeFromCurrentState AppWindowToken{2482a1a token=Token{a6020c5 ActivityRecord{6d66b3c u0 org.godotengine.cncchargen/com.godot.game.GodotApp t41}}}#0 (47)
01-21 12:08:32.451   523  2155 I SurfaceFlinger: id=99 Removed AppWindowToken{2482a1a token=Token{a6020c5 ActivityRecord{6d66b3c u0 org.godotengine.cncchargen/com.godot.game.GodotApp t41}}}#0 (47)
01-21 12:08:32.455   523   523 I Layer   : id=106[1] Destroyed 3fadef4 org.godotengine.cncchargen/com.godot.game.GodotApp#0
01-21 12:08:32.455   523   523 I Layer   : id=99[1] Destroyed AppWindowToken{2482a1a token=Token{a6020c5 ActivityRecord{6d66b3c u0 org.godotengine.cncchargen/com.godot.game.GodotApp t41}}}#0
01-21 12:08:32.457   523   523 I Layer   : id=107[1] Destroyed org.godotengine.cncchargen/com.godot.game.GodotApp$_1364#0
01-21 12:08:32.457   523   523 I Layer   : id=108[1] Destroyed Bounds for - org.godotengine.cncchargen/com.godot.game.GodotApp@0#0
01-21 12:08:32.457   523   523 I Layer   : id=109[1] Destroyed SurfaceView - org.godotengine.cncchargen/com.godot.game.GodotApp@beb64d9@0#0
01-21 12:08:32.457   523   523 I Layer   : id=110[1] Destroyed Background for -SurfaceView - org.godotengine.cncchargen/com.godot.game.GodotApp@beb64d9@0#0

### Steps to reproduce

I added a stripped-down version of my app with everything but the relevant interaction removed.

- Start the app on an Android device (I only have one for testing right now, see above, might not occur on every device)
- Use the Create Random Character button
- Tap the third OptionButton from the top (labeled Background)

The scene is RandomMenu/RandomMenu.tscn

### Minimal reproduction project

[BugReproduction.zip](https://github.com/godotengine/godot/files/10472074/BugReproduction.zip)

**Comment by akien-mga** [comment]
This might have been a touch input related crash that got fixed in beta 14, could you test and confirm?

**Comment by DerKusti** [comment]
Just tested with Beta 14, the bug no longer seems to occur.
