### ISSUE TITLE
EditorInterface.new().get_current_directory() Doesn't work after godot4-beta14

### ISSUE THREAD

**Issue by maktoobgar** [godotengine/godot#71805]
### Godot version

godot4-beta14

### System information

Ubuntu 22.04.1 LTS

### Issue description

In godot4-beta14 `EditorInterface.new().get_current_directory()` does not work and this error message gets generated:
```
Native class "EditorInterface" cannot be constructed as it is abstract.
Static function "new()" not found in base "EditorInterface".
```

If I try to use it like `EditorInterface.get_current_directory()`, this error message gets generated:
```
Cannot call non-static function "get_current_directory()" on the class "EditorInterface" directly. Make an instance instead.
```

This is a loop and makes `get_current_directory()` method unusable.

### Steps to reproduce

1. Just make a Scene and add a node.
2. Attach a script to it.
3. Paste current content into it:
```
func _ready() -> void:
	EditorInterface.new().get_current_directory()
```
4. Run the scene.

### Minimal reproduction project

It doesn't really need any reproduction project, the case is obvious.

**Comment by akien-mga** [comment]
Please check the documentation for EditorInterface: https://docs.godotengine.org/en/latest/classes/class_editorinterface.html

> Note: This class shouldn't be instantiated directly. Instead, access the singleton using [EditorPlugin.get_editor_interface](https://docs.godotengine.org/en/latest/classes/class_editorplugin.html#class-editorplugin-method-get-editor-interface).

**Comment by maktoobgar** [comment]
That does not work too.
```gdscript
EditorPlugin.get_editor_interface().get_current_directory()
```
Returns this error:
```
Cannot call non-static function "get_editor_interface()" on the class "EditorPlugin" directly. Make an instance instead.
```

**Comment by akien-mga** [comment]
You should have a script that extends EditorPlugin (i.e. an instance of EditorPlugin), and from it you call `get_editor_interface()` to have the singleton instance.

It's like any non static methods, you can't call `Node.get_node()` directly but if your script extends Node, you can use `get_node()`.

**Comment by maktoobgar** [comment]
Thanks. 🙏
