### ISSUE TITLE
Deleted node does not completly removed from Inspector Tab

### ISSUE THREAD

**Issue by avril-gh** [godotengine/godot#7180]
Godot Version
both 2.1.1 and master branch

Description
Node name persists in inspector after node has been deleted.

Example animation of bug
![del_node](https://cloud.githubusercontent.com/assets/3224132/20589783/efe72752-b21e-11e6-9ee5-fded4ad06236.gif)

**Comment by Noshyaar** [comment]
Can't reproduce in 3.1 master 9e7cee2 : the node name still persists (until redrawn) but it's removed from the history.

**Comment by avril-gh** [comment]
this is still present in master 397b01d
node name persist in inspector tab after node has been deleted.
