### ISSUE TITLE
Project Settings / Localization allows to add non-translation resource files

### ISSUE THREAD

**Issue by viktor-ferenczi** [godotengine/godot#71816]
### Godot version

master 360b6108

### System information

Windows 10, Compatibility, 2D

### Issue description

Problem is that `Project Settings / Localization` allows adding CSV translation file directly:
![image](https://user-images.githubusercontent.com/1848514/213877114-62b5626a-0685-4245-a941-e50bebe59de6.png)

**The CSV file is accepted in the settings, despite it will not work for the translation in practice.**

On running the project the translation does not work and the following error is produced:
```
E 0:00:02:0513   ResourceLoader::_load: Failed loading resource: res://translations.csv. Make sure resources have been imported by opening the project in the editor at least once.
  <C++ Error>    Condition "found" is true. Returning: Ref<Resource>()
  <C++ Source>   core\io\resource_loader.cpp:215 @ ResourceLoader::_load()
```

This error message is useless and confusing. It does not help to debug the issue at all.

What actually need to be added in `Project Settings / Localization` are the `*.translation` files produced by importing the CSV:
![image](https://user-images.githubusercontent.com/1848514/213877291-3ce93035-ed02-445e-95ec-dab2b09ddf8d.png)

While a [screenshot exists in the documentation](https://docs.godotengine.org/en/latest/tutorials/i18n/internationalizing_games.html#configuring-the-imported-translation) the error message above does not point the user into the right direction.

**The `Localization` list should only accept resource files which will actually work with the translation.** It would prevent this issue from happening in the first place.

### Steps to reproduce

1. Create an new 2D project with an empty scene.
2. Add a `Label` node with text: `CARD1`.
4. Copy this CSV file into the project: [translations.csv](https://github.com/godotengine/godot/files/10472503/translations.csv)
5. Notice that the CSV file gets imported and the `*.translation` files for the `en` and `hu` languages are produced.
6. Add the CSV file (not the .translation files) in `Project Settings / Localization`, notice that it is accepted.
7. Run the project. Translation of `CARD1` to `Guard` will not happen. Notice the confusing and useless error message in the output.
8. In `Project Settings / Localization` remove the CSV file and add the two `.translation` files instead.
9. Run the project. The `Label` will be translated as expected and there will be no error message.

### Minimal reproduction project

- To reproduce the issue: [Issue71816-Repro.zip](https://github.com/godotengine/godot/files/10472577/Issue71816-Repro.zip)
- Works once the right translation files are selected: [Issue71816-Works.zip](https://github.com/godotengine/godot/files/10472578/Issue71816-Works.zip)

Diff them, you will see that the only difference is in the project settings.

**Comment by timothyqiu** [comment]
Fixed by #97222

See that PR for information about why CSV was allowed.
