### ISSUE TITLE
[4.0] AnimationPlayer keeps playing audio after stopping

### ISSUE THREAD

**Issue by kuhnchris** [godotengine/godot#71810]
### Godot version

4.0-dev (master)

### System information

Win 11

### Issue description

Reported by @ExquisiterEmil on Discord

I analyzed an issue regarding the animation player - it keeps behaving weirdly when using an AudioStreamPlayer and using the AnimationPlayer. After adding a couple of debug messages and following various weird calls (up to 5 calls to animation process during _stop_internal) I narrowed the issue down to the following use-case:
- You have an AnimationPlayer
- You have an AudioStreamPlayer within the AnimationPlayer
- You position yourself somewhere "non position 0" in the timeline of the animation player (i.e. 'seek')
- You try to stop the animation player by pressing the "Stop" symbol (+ it shouldnt be playing in the first place because you haven't pressed 'Play' yet)
- The audio keeps playing but the bar resets to 0
- You press "Stop" again and it stops the audio.

From what I was able to analyze, the following process happens:
- When you click within the animation player, you trigger a _timeline_changed signal, this is being consumed by the AnimationPlayerEditor's "Seek Value changed" function, which in turn "stops" the player, seeks the position, and "starts" the player again. (See animation_player_editor_plugin.cpp:1169 -> animation_player.cpp:1984) -> Assumtion Nr. 1
![image](https://user-images.githubusercontent.com/761911/213870376-dd12d973-4e1e-483e-a24a-09e19c01a390.png)
- During the press of "Stop" you basically setting the seek value back to "0", and since this is another change of the seek valuje, it triggers another round-trip of seeking and pausing and unpausing the audioplayer.
![image](https://user-images.githubusercontent.com/761911/213870551-95d79a05-5bc3-4597-886a-ada6cca3c0c8.png)
- If you press once again, since the seek position is now "0", the round trip isn't triggered, and the animation processing isn't started, hence the audio doesn't start playing again. -> Assumtion Nr. 2

Assumtion Nr. 1:
- animation_player.cpp _stop_internal doesn't reset "is_stopping" to the proper previous state and just overrides it with "false" upon finish seeking (albeit setting "playing" to false)

Assumtion Nr. 2:
- I assume this behaviour like this, due to observing the stack trace of the calls, which only tripped my breakpoint once, here over at _stop_internal
![image](https://user-images.githubusercontent.com/761911/213870612-dfcfbe2c-c64d-41d4-ad4f-fe1e5ef6e927.png)
This, in turn, means that `frame->set_value(0);` does not trigger a seek again, which makes the audio player shut up.

Sadly, I have no idea how we could fix this, maybe instead of checking against the `if (!nc->node || is_stopping) {` block, we may also add a `|| !playing`? But maybe we are too early for this to trigger - someone with more experience in the animationplayer may be able to help out here.

If I should add anything to my analysis, let me know and I'll try to give more insight!

### Steps to reproduce

Listed above, download example project, open, click AnimationPlayer, seek somewhere, try to stop, ...

### Minimal reproduction project

[AudioPlaybackTrackIssue.zip](https://github.com/godotengine/godot/files/10472323/AudioPlaybackTrackIssue.zip)

**Comment by TokageItLab** [comment]
I remember changing the editor to preview the audio during seek, but indeed if there is a long audio such as bgm placed, it causes a problem where it keeps playing. There are two possible solutions:

1. Do not play audio when seeking in the editor in the first place. This should be the same as the previous behavior
2. Stop the playback by pressing the "stop" button

**Comment by kuhnchris** [comment]
1.) would be great for consistency, 2.) should work regardless, without having to press it twice. :-)

**Comment by kuhnchris** [comment]
Alternatively, do you think it would make sense to add a "autoplay" button in the AnimationEditorPlugin? Then anyone could toggle that playback whenever they'd want it or not.

**Comment by TokageItLab** [comment]
Do you mean the audio preview button? I think it's technically possible, but I'll have to give it some thought to see if it would be clean from an architectural design standpoint.

**Comment by kuhnchris** [comment]
No, I mean the regular Animation Player. I attached a video, maybe this makes it a bit more clear.
[godotaudio.webm](https://user-images.githubusercontent.com/761911/213874763-5d06979f-a6b9-4d82-b95b-e90e4d68be0d.webm)

**Comment by KoBeWi** [comment]
> Do not play audio when seeking in the editor in the first place. This should be the same as the previous behavior

Pretty sure previously it would play the audio too. Or at least I remember there was a similar issue with audio tracks.

**Comment by ExquisiterEmil** [comment]
Thank you @kuhnchris for creating the issue. I'd like to point out, there is a bunch of other concerning things with the Animation player and audio. At first, when positioning somewhere within the range of an Audio key and having LMB pressed, it keeps repeatedly restarting the sound, resulting in very ear-blasting sounds. You can see the issue in this video (don't watch with very high volume!):
https://user-images.githubusercontent.com/53947784/214711467-8b8f1758-9ebd-4380-919e-539346282b11.mp4

I hope this can also be fixed, as to protect the ears of the users 👂

**Comment by ExquisiterEmil** [comment]
I mentioned a bunch of other usability problems in a new issue because they go far beyond the scope of this thread.
