### ISSUE TITLE
[4.0] Default scons build option doesn't build debug symbols albeit written in --help

### ISSUE THREAD

**Issue by kuhnchris** [godotengine/godot#71812]
### Godot version

master

### System information

Win 11

### Issue description

If you check `scons --help` it reads:
```
debug_symbols: Build with debugging symbols (yes|no)
    default: True
    actual: True
```

The resulting binary does *not* have debug symbols available for gdb tho! (I renamed the file to say 'no.debug.symbols.exe', it's just a default `scons`)
```
Reading symbols from .\bin\godot.windows.editor.x86_64.no.debug.symbols.exe...
(No debugging symbols found in .\bin\godot.windows.editor.x86_64.no.debug.symbols.exe)
``` 

After compiling it with `scons debug_symbols=yes`:
```
Reading symbols from .\bin\godot.windows.editor.x86_64.exe...
(gdb) 
```
(and debugging works now!)

### Steps to reproduce

- Compile with `scons` (Windows 11, MinGW, Python from `scoop` package manager, `pip install scons`)
- Check resulting executable with `gdb`

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
Yes the help is wrong, it actually default to false (or true if `dev_build` is enabled).
