### ISSUE TITLE
Background energy changes not only the intensity of light, but also the brightness of the background itself

### ISSUE THREAD

**Issue by mishkarch** [godotengine/godot#71813]
### Godot version

3.5.1, 3.5.2rc2

### System information

Windows (I think it's not matter)

### Issue description

Background energy in Environment changes not only the intensity of light, as stated in the description, but also the brightness of the background itself, in particular, the procedural or panoramic sky.

This was noted in passing in the original post #47785, but was not taken into account as the discussion progressed.

This is a problem, because if I want to completely get rid of the sky light and completely control the color of the ambient light, there is no way to do it without getting a completely black sky panorama.

For example, I want to suppress the cold skylight and end up with a completely black panorama.
![Sprite-0001](https://user-images.githubusercontent.com/48409271/213870784-0633701e-b633-455b-905d-db3b01d1ad1b.png)

![Sprite-0002](https://user-images.githubusercontent.com/48409271/213870794-5d4ea26f-2ae9-4cf4-bbeb-1a40461e0088.png)

The minimum reproduction project shows that even with the ambient light turned off completely, we do not get a completely black shadow if we do not reduce background energy.

![Sprite-0003](https://user-images.githubusercontent.com/48409271/213870973-af0148b0-d749-41de-a200-9f52284265b6.png)
![Sprite-0004](https://user-images.githubusercontent.com/48409271/213870977-6a5771cc-efaf-496d-9881-19c05b0f1099.png)

Interestingly, even in 4.0, despite the ability to select ambient_light_source, no combination of settings can still completely suppress the lighting from the sky, without using the background energy multiplayer slider, which, again, changes the brightness of the sky itself.

### Steps to reproduce

Open the representation project, change the background energy in the inspector.

### Minimal reproduction project

[background_energy.zip](https://github.com/godotengine/godot/files/10472314/background_energy.zip)

**Comment by Calinou** [comment]
This is done by design. Background energy is exactly that – it multiplies the intensity (brightness) of the background. This in turn affects its ambient and specular light.

To decrease ambient light generated by the sky only, decrease **Sky Contribution** and nothing else. This works in both 3.x and 4.0.

> The minimum reproduction project shows that even with the ambient light turned off completely, we do not get a completely black shadow if we do not reduce background energy.

This is because there's still some reflected light visible. Godot 3.x doesn't offer separate control for ambient light and reflected light, but 4.0 does (and allows you to turn off reflected light from the sky without disabling ambient light).

**Comment by clayjohn** [comment]
As Calinou says, part of the improvements made in 4.0 were to improve the control you have over background lighting. In Godot 3.x you are limited to controlling ambient light (AKA indirect diffuse) and the brightness of the sky (background_energy). You do not have a multiplier to control the brightness of indirect specular reflections. In 4.0 you now have that control you just have to set the reflection source to disabled as well.

**Comment by mishkarch** [comment]
Thanks for the clarification, I seem to understand how it works and the difference between 3.x and 4.0. Due to an absurd oversight, the roughness was indeed set to less than 1, after increasing to 1 the desired effect was achieved. I think after finishing the documentation everything will be in order.
