### ISSUE TITLE
Detected GDExtension class but not allowing it to be extended.

### ISSUE THREAD

**Issue by Coder2195Text** [godotengine/godot#71821]
### Godot version

v4.0beta10 offical

### System information

Ubuntu 22.04 Running on Vulkan Mesa Intel® UHD Graphics 620 (WHL GT2)

### Issue description

Disclaimer: I don't know if this is a rust gdextension issue, or godot issue, so Ill post it on both

In [this repo](https://github.com/Coder2195Text/tile-craft-rust), the [ArtistCredit script](https://github.com/Coder2195Text/tile-craft-rust/blob/master/src/artist_credit.rs) along with other scripts have compiled successfully.

The thing is, I cannot extend the node off like this, because it doesn't exist.
![image](https://user-images.githubusercontent.com/63069499/213879273-a76a1b92-94d4-4aa7-be6e-628f14386949.png)

So I decided to see if I can extend it via a script. They are detected in Godot as valid classes to extend off of.
![image](https://user-images.githubusercontent.com/63069499/213879237-5bb736de-f2ce-40c7-88af-d36949416ad7.png)

But then hell breaks loose, because it now says its invalid. 
![image](https://user-images.githubusercontent.com/63069499/213879319-ead4f624-f560-4d01-83d4-f7531624ca2b.png)

### Steps to reproduce

Clone the project, and just compile via `cargo build`

The scripts are fine, because the class is detected by Godot (look at above images)

Then try to extend or change type of the root node of `res://Scenes/ArtistCredit.tscn` from Control to ArtistCredit

### Minimal reproduction project

[n-a.txt](https://github.com/godotengine/godot/files/10472680/n-a.txt)

**Comment by Sslaxx** [comment]
https://github.com/godot-rust/gdextension/issues/79 is the issue on the Godot Rust tracker.

**Comment by Coder2195Text** [comment]
Nevermind, I forgot the last chunk of code which was to `impl GodotExt`
