### ISSUE TITLE
beta14 AnimationTree add animation node failure

### ISSUE THREAD

**Issue by danielbill** [godotengine/godot#71833]
### Godot version

4.0 beta14

### System information

win10 Gles3 

### Issue description

great, my anim-tree code works fine from 3.5 to beta13 , untill beta14.
the issue is when i use a animation node , the anim-tree just dont add it into nodeStatmentMachine.
so statMachine cannot from walk travel back to idle .

--
![image](https://user-images.githubusercontent.com/6269655/213901098-acd37f72-92e9-40a8-a567-ddb6089d3c27.png)
![image](https://user-images.githubusercontent.com/6269655/213901122-6816d7d3-4a8a-463c-85d2-193167029b24.png)

### Steps to reproduce

	if direction:
		velocity.x = lerp(velocity.x,direction.x * SPEED,_lerp_val)
		velocity.z = lerp(velocity.z,direction.z * SPEED,_lerp_val)
		anim_tree.set("parameters/walk/blend_position",direction)
		animationStat.travel("walk")
	else:
		velocity.x = lerp(velocity.x,0.0,_lerp_val)
		velocity.z = lerp(velocity.z,0.0,_lerp_val)
		animationStat.travel("idle")        <----  wont work!!!

### Minimal reproduction project

sorry

**Comment by TokageItLab** [comment]
> the issue is when i use a animation node , the anim-tree just dont add it into nodeStatmentMachine.

Please clarify what is not being added.

Perhaps there is an error somewhere other than StateMachine, but we cannot investigate since there are not enough details in the description. Also, MRP is lacking.

**Comment by danielbill** [comment]
>
> > the issue is when i use a animation node , the anim-tree just dont add it into nodeStatmentMachine.
> 
> Please clarify what is not being added.
> 
> Perhaps there is an error somewhere other than StateMachine, but we cannot investigate since there are not enough details in the description. Also, MRP is lacking.

i guess the animation node “idle”  didnt add into the statment list， so cannot be travelled to。
i tested the code on 3.5  4.0.10  4.0.13 ， just fine， but beta14 failed
