### ISSUE TITLE
Godot 4 beta 14 won't launch

### ISSUE THREAD

**Issue by rpenaand** [godotengine/godot#71835]
### Godot version

4.0 beta 14

### System information

Windows 10, Nvidia Gtx 1080 Driver version 528.02, Amd Ryzen 7 1800x, 

### Issue description

I am experiencing an issue where the Godot 4.0 beta 14 executable won't launch no matter what I try. I saw that someone else was also running into the same issue with beta 8 and that they were able to fix it by re-installing windows which is not something I can do in my case. I have already tried launching the beta in admin mode, using the cmd, but nothing works and nothing is printed in the console. It is important to note that I could launch beta 1 - 7 just fine on my machine but anything after beta 7 so 8-14 won't launch. Also the web version of beta 13 did actually load and work just fine on my machine but neither mano nor standard builds for windows 64 worked. 

### Steps to reproduce

I downloaded the beta from the official site and extracted the files. Afterwards I double clicked the exe file and waited for it to launch to no avail. When double clicking the exe file the loading circular status bar does appear momentarily then disappears and nothing happens. In the task manager Godot does appear as a process but no memory, CPU, disk, GPU usage is being allocated to it from what it seems.
![godot task manager](https://user-images.githubusercontent.com/118253326/213903176-ec2ba561-b444-4068-930c-a10a39a1c583.PNG)

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
If you go back and try to run beta 7 now does it still launch?

**Comment by rpenaand** [comment]
yes it launches just fine

**Comment by gotnospirit** [comment]
Did you try "Godot_v4.0-beta14_win64_console.exe"?

**Comment by rpenaand** [comment]
Yes as mentioned beta 8 - 14 do not work where as 1 - 7 work just fine in regards to the windows 64 executables. And then I was able to try beta 13 and beta 14 web versions and that did appear to work fine on my machine as shown in the screen shots attached.
![Godot beta 14 v1](https://user-images.githubusercontent.com/118253326/213975923-5d59984b-e75a-4173-a754-16d5af29e925.PNG)
![Godot beta 14 v2](https://user-images.githubusercontent.com/118253326/213975934-aa421754-1391-4df2-b553-361c2c68a8f6.PNG)
![Godot beta 14 v3](https://user-images.githubusercontent.com/118253326/213975940-a1ef6d84-edf1-42f2-906e-cd39ca2bbbc5.PNG)

**Comment by coppolaemilio** [comment]
@rpenaand have you tried with any of the release candidates yet?

**Comment by rpenaand** [comment]
I did get it to work but I did have to do a windows reinstall to get it working. So not entirely sure what the issue was.
