### ISSUE TITLE
TextEdit Signal does not exist or is implemented, yet ingame docs say it does exist

### ISSUE THREAD

**Issue by TheYellowArchitect** [godotengine/godot#71852]
### Godot version

4.0 beta14

### System information

Artix Linux

### Issue description

I was trying to make a signal which detects "enter" and pressing "search help" and typing "text_submitted" it shows that signal. In reality, it doesn't exist (and ofc no auto-complete)

What is strange is that the signals themselves have no parameters, instead of having `new_text : String` as mentioned in the docs. Currently I can just capture text field before and after, no problem, but it should give you the convenience of giving the user the diff of the text field.

pic-related
![deprecated-docs](https://user-images.githubusercontent.com/25630803/213913731-a7bf64a8-3754-40a1-b2e2-f30d9425a148.png)

### Steps to reproduce

Written above.

**Comment by Sauermann** [comment]
Be aware that the Signal `text_changed` has no argument for the node `TextEdit` while it has the argument `new_text` for the node `LineEdit`.
It looks like you are viewing the docs for `LineEdit` while you want to use `TextEdit`.

**Comment by KoBeWi** [comment]
Yep, you are looking at wrong docs.

**Comment by TheYellowArchitect** [comment]
I just checked again and you are correct, sorry!
