### ISSUE TITLE
Resources on .tscn files gets new IDs for no reason

### ISSUE THREAD

**Issue by stephannv** [godotengine/godot#71854]
### Godot version

v4.0.beta14.official.28a24639c

### System information

Vulkan API 1.2.231 - Apple - Apple M1 Max

### Issue description

While using Godot as usual (changing properties values, updating scripts) , the sub-resources on `.tscn` files get new IDs even when they are not modified. This pollutes the commits with unnecessary changes  and makes it harder to track what was actually changed.
<img width="1416" alt="Screen Shot 2023-01-22 at 08 58 14" src="https://user-images.githubusercontent.com/3025661/213915045-742a996d-9d48-470a-81a2-cbd1b3fe9570.png">

### Steps to reproduce

I don't know how to reproduce this. It is happening after some time using godot, and when I go to prepare the commit, I notice these changes. I tried to do many things to detect what is triggering this behavior but I couldn't. 
This problem is occurring on older Godot 4 beta versions too (beta 10, 11, 12, 13).

### Minimal reproduction project

All projects, N/A

**Comment by stephannv** [comment]
I tried to do this with another scenes but the bug doesn't happen.

https://user-images.githubusercontent.com/3025661/213915692-26663c7f-0194-4b7d-ab00-a8b2b495786a.mov

**Comment by Sauermann** [comment]
Please have a look at #62258

**Comment by stephannv** [comment]
Thanks, @Sauermann . I searched on issues but I didn't find it. I'm closing it since it's a duplicate.
