### ISSUE TITLE
Beta 14 Animation Tree no longer playing 2d animations.

### ISSUE THREAD

**Issue by OddlifeDev** [godotengine/godot#71873]
### Godot version

4.0 Beta 14

### System information

Mac OS X 11.6.7

### Issue description

My player animations are no longer working in beta 14 (migrating from 12 skipped 13 so not sure if it worked then)

More specifically, Animation tree is still switching the animations (I am seeing the first frame of each animation) But the animation itself will not play.

The set up i have is Three blend tree nodes which in turn have blendspace 2D nodes in them.

<img width="488" alt="Screenshot 2023-01-22 at 17 42 06" src="https://user-images.githubusercontent.com/119736831/213931282-db436d1d-ef95-42c2-b976-2177009bbbfe.png">

This still appears to be working in the editor.
![2023-01-22 17-37-48](https://user-images.githubusercontent.com/119736831/213931411-843e8926-06fb-4cb4-b585-d758ac3e67a0.gif)

This is the code i'm using to switch animations

func update_animation(move_input : Vector2):
	if move_input != Vector2.ZERO:
		facing_direction = move_input
		animation_tree.set("parameters/Run/Run/blend_position", move_input)
		animation_tree.set("parameters/Idle/Idle/blend_position", move_input)

But again this seems to be working, when i build and run the project you can see just no animation playing

![2023-01-22 17-37-48 2](https://user-images.githubusercontent.com/119736831/213931663-4d71dde9-7940-433f-83c7-956359cc1af1.gif)

Where as the result i was getting in 12 was this

![2023-01-22 17-52-37](https://user-images.githubusercontent.com/119736831/213931819-2f3e47bb-68cf-4920-a6d6-46af3bb40275.gif)

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by OddlifeDev** [comment]
confirmed it was still working in beta 13. So Beta 14 was the breaking update.

**Comment by TokageItLab** [comment]
MRP is needed

**Comment by TokageItLab** [comment]
Is it caused by the Dodge animation not being loaded as a parameter, same with #71833? But there is no way to find out because there is no MRP in either issue.
