### ISSUE TITLE
GDScript 2.0: Internal script error (opcode 3)

### ISSUE THREAD

**Issue by weckr** [godotengine/godot#71879]
### Godot version

4beta14

### System information

fedora 37, intel i5 6600

### Issue description

> E 0:00:29:0774   _gui_input: Condition ' (ip + 4) > _code_size ' is true. Breaking..:
>   <C++ Source>   modules/gdscript/gdscript_vm.cpp:787 @ call()
>   <Stack Trace>  Canvas.gd:37 @ _gui_input()

toy drawing thing, i collect non accumulated inputs and then process them in a thread after each frame, got the error after i saved a png file in other script, might be because i dont really sync the thread with the input and they touch the same strokes array, it does suprisingly well otherwise... but error said pls report so... error happens at await

### Steps to reproduce

```
#in ready
var paint_thread = Thread.new()
paint_thread.start(painter)

func painter() -> void:
	var brect := Rect2i(Vector2i.ZERO,brush.get_size())
	while true:
		for s in strokes:
			canvas.blit_rect(brush,brect,s - brush.get_size() / 2)
		strokes.clear()
		tex.update(canvas)
		await get_tree().process_frame
	
func _gui_input(event : InputEvent) -> void:
	if event is InputEventMouseButton and event.button_index == MOUSE_BUTTON_LEFT:
		brushing = event.pressed
	
	
	elif event is InputEventMouseMotion and brushing:	
		strokes.append(Vector2i(event.position))
		

```

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
@weckr Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot. (The code sample won't run on its own.)

**Comment by weckr** [comment]
cant really reproduce it myself anymore, if it comes up again ill try to post the minimal project

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
