### ISSUE TITLE
Export for HTML does not work when viewed on Firefox

### ISSUE THREAD

**Issue by blackears** [godotengine/godot#71882]
### Godot version

v4.0.beta13.official [caacade56]

### System information

Windows 10, GLES 3,

### Issue description

I'm trying to run a 3D game I exported from Godot on Firefox.  I'm getting errors when I try to run.  These errors to not occur if I try running using Chrome.  These errors occur even if I check the SharedBufferArray support flag in the itch.io game configuration page.

You can see this on the page I'm trying to run on (password: submarine)
https://blackears.itch.io/submarine-shooter

![image](https://user-images.githubusercontent.com/6724608/213940586-e5d30785-8fa0-421d-ae75-5b2b01451723.png)

### Steps to reproduce

Create a 3D project
export as HTML5
Upload to itch.io
Try to run on Firefox web browser.

### Minimal reproduction project

N/A

**Comment by blackears** [comment]
This also happens when I try to run from my local file system using either Firefox or Chrome.

**Comment by Calinou** [comment]
> These errors to not occur if I try running using Chrome. These errors occur even if I check the SharedBufferArray support flag in the itch.io game configuration page.

itch.io's flag only works for Chromium-based browsers. This is a limitation on their end.
