### ISSUE TITLE
Only cam in scene tree needs to be made current, but only sometimes

### ISSUE THREAD

**Issue by ScyDev** [godotengine/godot#7188]
**Operating system or device - Godot version:**
Windows 7 64bit
Godot 2.1.1 stable and 2.1 stable

**Issue description** (what happened, and what was expected):
All my levels are separate scenes. Every level scene contains a camera. When switching levels (queue_free old scene, add new scene), something goes wrong with detecting the only camera and making it the current cam.
This works almost always on Linux, but on Windows 7 64bit it fails almost every time, especially when running an exported game.

**Steps to reproduce:**
Setup as described above.

**Link to minimal example project** (optional but very welcome):

**Comment by vnen** [comment]
AFAIK (though I might be wrong) there's no function to detect the only camera all the time. It does work if you call `SceneTree.change_scene()` but not really if you just free the Camera node (or its parent) and add another.

My hunch is that if you `queue_free` one and `add_child` another at the same time, sometimes the old will still be in the tree while you're adding the new one, so it won't be marked as current.

**Comment by ScyDev** [comment]
There must be, because I have been doing that for months, without ever setting a cam to current manually or by code. 
And it fails much harder on Windows than on Linux. So that is probably why I didn't notice the problem for so long.

**Comment by vnen** [comment]
I mean it doesn't look *all the time*, but when you free the current camera it'll likely look for another to replace it (or that check happens when you add one, not sure). I think you got lucky for it to work. Might be related to how memory management happens in different OSs.

**Comment by bojidar-bg** [comment]
Can we confirm that this is still the case in 3.0? (I'd assume yes, but still)

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.
