### ISSUE TITLE
Godot 4.0 Beta 14 Mono Cannot Emulate Touch From Mouse

### ISSUE THREAD

**Issue by trudeaua-vividream-software** [godotengine/godot#71899]
### Godot version

v4.0.beta14.mono.official [28a2463]

### System information

Windows 10

### Issue description

The [docs page for Touch Events](https://docs.godotengine.org/en/latest/tutorials/inputs/input_examples.html#touch-events) states the following:

> To test your touch events on a non-touchscreen device, open Project Settings and go to the "Input Devices/Pointing" section. Enable "Emulate Touch From Mouse" and your project will interpret mouse clicks and motion as touch events.

However, in Godot 4.0beta14, these Project Settings are no longer present in the Project Settings menu (I also looked at each of the sections to see if the `Emulate Touch From Mouse` setting was moved, and couldn't find it):

![image](https://user-images.githubusercontent.com/120415438/213981474-a745810e-8561-446f-a464-c25c8c02b3bd.png)

I've looked elsewhere too, and cannot find them.

If the emulation is supposed to happen automatically now, then the issue for me is that it's not working for `TouchScreenButton` (see the attached reproduction project for an example of this).

### Steps to reproduce

1. Install the attached reproduction project.
2. Run the game in a Desktop environment.
3. Observe that clicking the TouchScreenButton does not seem to perform a touch, as the TouchScreenButton does not change color, and the `pressed` signal is not fired.

### Minimal reproduction project

[ReproduceEmulateTouchFromMouseIssue.zip](https://github.com/godotengine/godot/files/10477381/ReproduceEmulateTouchFromMouseIssue.zip)

**Comment by Sauermann** [comment]
If I recall correctly, these are advanced settings.
Please enable the "Advanced Settings" button in the top-right corner of your screenshot.

**Comment by trudeaua-vividream-software** [comment]
Gah, that was it. Thanks for the help!
