### ISSUE TITLE
4.0 C# `Signal.Connect` Doesn't Work as Documented in `Object.Connect` Documentation

### ISSUE THREAD

**Issue by trudeaua-vividream-software** [godotengine/godot#71895]
### Godot version

v4.0.beta14.mono.official [28a24639c]

### System information

Windows 10, .Net SDK 6.0.405

### Issue description

The [4.0 docs for `Object.Connect`](https://docs.godotengine.org/en/latest/classes/class_object.html#class-object-method-connect) suggest that [`Signal.Connect`](https://docs.godotengine.org/en/latest/classes/class_signal.html#class-signal-method-connect) (the docs for which are lacking any C# entry) or `object.event += Signal` are the preferred ways to hook up signals in C# via code. However, trying to make use of these commands result in errors which prevent building the project. 

Here is the code for the class containing the statements which are erroring (you can view my Player implementation in the attached reproduction project):
```
using Godot;
using System;

public partial class Example : Node2D
{
    public override void _Ready()
    {
        var button = new Button();
        // C# supports passing signals as events, so we can use this idiomatic construct:
        button.ButtonDown += OnButtonDown;

        // This assumes that a `Player` class exists, which defines a `Hit` signal.
        var player = new Player();
        // Errors with the message:
        // The event 'Player.Hit' can only appear on the left side of += -=
        player.Hit.Connect(OnPlayerHit, new Godot.Collections.Array { "sword", 100 });

        // Errors with the message:
        // 'Example.OnPlayerHit(string, int)' is a method, which is not valid in the given context
        player.Hit += OnPlayerHit.Bind("sword", 100);

        // NOTE: this statement isn't in the docs, but I used to check whether an explicit `Callable` could use the `Bind` method
        // Errors with the message:
        // 'Callable' does not contain a definition for 'Bind' and no accessible extension method 'Bind' accepting a first argument of type 'Callable' could be found (are you missing a using directive or an assembly reference?)
        player.Hit += new Callable(this, nameof(OnPlayerHit)).Bind("sword", 100);

    }

    private void OnButtonDown()
    {
        GD.Print("Button down!");
    }

    private void OnPlayerHit(string weaponType, int damage)
    {
        GD.Print(String.Format("Hit with weapon {0} for {1} damage.", weaponType, damage));
    }
}
```

### Steps to reproduce

To reproduce, simply open the attached reproduction project and attempt to either open the `Example.cs` script in Visual Studio, or press the `Build` button in the top right of the Editor, which should result in the errors which I documented in the Issue Description.

### Minimal reproduction project

[ReproduceSignalConnectIssue.zip](https://github.com/godotengine/godot/files/10476718/ReproduceSignalConnectIssue.zip)

**Comment by raulsntos** [comment]
Yes, the documentation is incorrect. It should be fixed by https://github.com/godotengine/godot/pull/64930.

The valid ways to connect to a signal in C# are:

```csharp
// Option 1: In C#, we can use signals as events and connect with this idiomatic syntax:
button.ButtonDown += OnButtonDown;
// Option 2: Object.Connect() with a constructed Callable from a method group.
button.Connect(Button.SignalName.ButtonDown, Callable.From(OnButtonDown));
// Option 3: Object.Connect() with a constructed Callable using a target object and method name.
button.Connect(Button.SignalName.ButtonDown, new Callable(this, MethodName.OnButtonDown));
```

`Bind` is not implemented so if you need to bind values, use lambdas:

```csharp
player.Hit += (hitBy, level) => OnPlayerHit(hitBy, level, "sword", 100);
```

**Comment by trudeaua-vividream-software** [comment]
Thank you so much for the clarification! I really appreciate it - I'm a bit newer to the features of C# being used here, so I missed the possibility of adding Lambdas to bind arguments.

Just one more quick question on your example for binding values:

> `player.Hit += (hitBy, level) => OnPlayerHit(hitBy, level, "sword", 100);`

Isn't that too many arguments passed to `OnPlayerHit`? In this context, wouldn't we either want  `player.Hit += (hitBy, level) => OnPlayerHit(hitBy, level);` if we wanted to pass arguments through to `OnPlayerHit` from the signal itself, or `player.Hit += (hitBy, level) => OnPlayerHit("sword", 100);` if we wanted to hardcode those values in `OnPlayerHit` for any emission of the `player.Hit` signal (though, in this case, it may be preferable to remove the arguments from `player.Hit`)?

**Comment by raulsntos** [comment]
Oh, sorry, I copied the example from the documentation that has a `OnPlayerHit` method with this signature:

```csharp
void OnPlayerHit(string hitBy, int level, string weaponType, int damage);
```

The idea was to show you can use methods with a different signature than the one required by the signal delegate type if you "bind" the missing parameters with a lambda.

For the method signature in your MRP:

```csharp
void OnPlayerHit(string weaponType, int damage);
```

You are correct:

```csharp
// Works because the method signature matches the signal delegate type:
player.Hit += OnPlayerHit;
// Using the values emitted by the signal:
player.Hit += (hitBy, level) => OnPlayerHit(hitBy, level); 
// Ignore the values emitted by the signal and "bind" different values:
player.Hit += (hitBy, level) => OnPlayerHit("sword", 100);
```
