### ISSUE TITLE
Occluder polyshape set_hole_point() not working in 3.5 stable

### ISSUE THREAD

**Issue by webnetweaver** [godotengine/godot#71908]
### Godot version

3.5 stable

### System information

Windows 8

### Issue description

set_hole_point() method of OccluderShapePolygon doesnt seem to work for 3.5 stable.  I am attempting to create a hole in an occluder at runtime but the point array for holes is not being updated.  Creating occluder holes using the editor seems to work fine.  But any effort to create or modify holes at runtime bring about no result.

### Steps to reproduce

MRP has two identical scenes which can each be run.  Both scenes include a cube meshInstance node,  and an occluder node using a polygon shape.  The occluder node is between the cube mesh and the camera, potentially culling the cube mesh from the camera. 

For one scene, the occluder node has a hole created in the editor.  When viewing the scene through the camera. the cube mesh is now visible through the hole defined in the OccluderShapePolygon node.  Running the scene confirms the cube mesh is visible through the hole in the occuluder.

The second scene has an identical cube mesh, camera node, and occluder node in between the two.  The difference is that there is no hole defined in the OccluderShapePolygon node.  The cube mesh is occluded by the occluder node.  A script on the occluder node attempts to create a hole identical to the hole from the first scene using set_hole_point().  Running the project shows the cube is still being culled indicating that the hole was never created.  Inspection of the running scene, and switching to the "Remote" tab, confirms that the hole is not being created.

The cube should be visible in the second scene as well.  Let me know if I am missing a step or if you notice a problem with the script.

### Minimal reproduction project

[HoleBug.zip](https://github.com/godotengine/godot/files/10478835/HoleBug.zip)

**Comment by Calinou** [comment]
cc @lawnjelly

**Comment by lawnjelly** [comment]
Try this instead:
```
	var pts = PoolVector2Array()
	pts.push_back(Vector2(1, -1))
	pts.push_back(Vector2(1, 1))
	pts.push_back(Vector2(-1, 1))
	pts.push_back(Vector2(-1, -1))
	oshape.set_hole_points(pts)
```
It is my fault though I forgot to add an error message, I'll change this. The idea is that `set_hole_point()` is primarily for the editor, and it will only change a point if the hole id is within the existing array of points.

Just a good error message is probably better than trying to deal with the possible situations (what if e.g. you call `set_hole_point(1000, Vector2(1, 1))`? Should it create all the missing hole points etc?).

**Comment by webnetweaver** [comment]
Ok I will try this.  Also understand that set_hole_points() is not in the docs so I didnt even know this function exists.

**Comment by lawnjelly** [comment]
I thought the same at first, but it is in the docs - rather confusingly lower down on the page (godot docs does this for getters / setters of properties). So I'll try and draw attention to this.

**Comment by webnetweaver** [comment]
@lawnjelly Is it on this page?  https://docs.godotengine.org/en/stable/classes/class_occludershapepolygon.html  I dont see it anywhere on this page.  Am I looking on the wrong page?

**Comment by lawnjelly** [comment]
Under `Property Descriptions` `PoolVector2Array - hole points`.

**Comment by webnetweaver** [comment]
Ok gotcha.  I do see set_polygon_points in the class description.  I didnt notice the extra "s" at the end differentiating it from the one in the method list.

**Comment by webnetweaver** [comment]
Using set_hole_points() works fine.  Thanks for the help @lawnjelly  Closing this issue.
