### ISSUE TITLE
Godot 4.0 Gridmap change floor hotkeys broken

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot#71916]
### Godot version

4.0 beta 14

### System information

Windows 10

### Issue description

The hotkeys to change floor in gridmap don't work as they are also used by the select mode and rotate mode tools. Temporary fix: clear the editor hotkeys for Select and Rotate mode and it works in gridmap.

### Steps to reproduce

Add a gridmap, attempt to use Q and E to change floors, Select and Rotate hotkeys will supersede the floor change in Gridmap.

### Minimal reproduction project

N/A

**Comment by jkulawik** [comment]
Cursor Clear Rotation (W) does not work too

**Comment by akien-mga** [comment]
> Duplicate of #71916?

You linked this very issue.

**Comment by tavurth** [comment]
Sorry was shuffling many tabs:

https://github.com/godotengine/godot/issues/67497

**Comment by akien-mga** [comment]
Duplicate of #67497
