### ISSUE TITLE
How to disable and enable vsync from code Godot 4 beta 13

### ISSUE THREAD

**Issue by Ogre44** [godotengine/godot#71926]
### Godot version

v4.0.beta.arch_linux [23e10d1df]

### System information

Artix Linux 6.1.1-zen1-1-zen Plasma 5.26.4

### Issue description

```
if option_vsync:
		ProjectSettings.set('display/window/vsync/vsync_mode', DisplayServer.VSYNC_ENABLED)
	else:
		ProjectSettings.set('display/window/vsync/vsync_mode', DisplayServer.VSYNC_DISABLED)
```

I couldn't find another way but this doesn't work

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Project settings are only applied when the project starts. You need to call the appropriate DisplayServer method instead.

**Comment by clayjohn** [comment]
This is not a support channel. This space is for bug reports only. Please respect that. 

In the future if you have support questions, please ask them on one of the various [community channels](https://docs.godotengine.org/en/latest/community/channels.html)

To answer your question vsync is set with the method [DisplayServer.window_set_vsync_mode](https://docs.godotengine.org/en/latest/classes/class_displayserver.html#class-displayserver-method-window-set-vsync-mode) This can be found by using the search bar in the docs
