### ISSUE TITLE
Mouse scroll acts like a click when cursor is over Color picker

### ISSUE THREAD

**Issue by TeddyDD** [godotengine/godot#7192]
**Operating system or device - Godot version:**
Godot 2.1 stable from Steam on 64 bit Arch Linux

**Issue description** (what happened, and what was expected):
When you scroll mouse wheel over Color Picker it changes currently selected color. This should happen only when left mouse button is pressed.

**Comment by Hinsbart** [comment]
Slightly related: How about "scrolling" the hue using the mouse wheel?

**Comment by volzhs** [comment]
Color is selected in hue also with mouse wheel...

**Comment by volzhs** [comment]
updated PR to prevent selecting color with mouse wheel scroll in hue panel too.
