### ISSUE TITLE
Tree signal "item_custom_button_pressed" doesn't work

### ISSUE THREAD

**Issue by eskandrej** [godotengine/godot#71928]
### Godot version

v4.0.beta.custom_build [7b1747d36]

### System information

Windows 10, NVIDIA GeForce GTX 760

### Issue description

Signal is never emitted. I've searched in the code and it seems that the signal is only defined but not emitted anywhere.

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot/issues/37604.

**Comment by akien-mga** [comment]
Duplicate of #37604
