### ISSUE TITLE
2d not working in 32 bit windows

### ISSUE THREAD

**Issue by gibberingmouther** [godotengine/godot#7193]
**Operating system or device - Godot version:**
windows 10 - 2.1.1 Godot

**Issue description** (what happened, and what was expected):
here is the thread where i described it: https://godotdevelopers.org/forum/discussion/18040/cant-see-label-or-viewport-lines-in-2d-scene-editor
look at all 4 of the posts i made.

**Steps to reproduce:**
not sure.  maybe download a 32 bit Godot version for windows 7?

**Link to minimal example project** (optional but very welcome):
the problem was in the editor.  it didn't matter what project i created, the problem appeared for all of them.

**Comment by vnen** [comment]
Might be some OpenGL issue. What is the graphics card?

**Comment by volzhs** [comment]
I guess there were some messages on `cmd` window. what it said?

**Comment by gibberingmouther** [comment]
My dad said Norton might be the issue but Godot works on my 64 bit Windows
10 laptop that also has Norton installed.
  On my 32 bit Windows 7 machine I get a bunch of warnings and errors about
RasterizerGLES2 (a driver, I think).  The cmd windows also mentions the
framebuffer and viewport.  Here's a screen shot:
https://postimg.org/image/9pafdiupl/

**Comment by vnen** [comment]
Looks indeed like the problem is in the GPU that does not properly support OpenGL. Likely the same as #1260.

**Comment by SuperUserNameMan** [comment]
( that make me think that it could be handy that godot displays the gpu/driver name into the console to ease bug report from peoples who don't know how and to find this information )

**Comment by gibberingmouther** [comment]
okay, thanks!  at least i know what the problem is.

On Tue, Nov 29, 2016 at 10:10 AM, SuperUserNameMan <notifications@github.com

**Comment by vnen** [comment]
Closing as duplicate of #1260.
