### ISSUE TITLE
@icon broken in 4.0 beta 14

### ISSUE THREAD

**Issue by anatolbogun** [godotengine/godot#71947]
### Godot version

v4.0.beta14.official [28a24639c]

### System information

MacOS 12.6.2

### Issue description

Beta 14 throws an error for custom `@icon`, e.g.
```
class_name StateMachine extends Node

@icon("res://assets/icons/state_machine.svg")
```
> Annotation "`@icon`" is not allowed in this level.

In beta 13 and before that worked fine.

### Steps to reproduce

1. Add a custom `@icon` in a custom node script.
2. Error message: Annotation "`@icon`" is not allowed in this level.

There are possibly other errors because a `class_name` node is now not recognized if extended by other classes, but they should resolve if `@icon` is removed.

### Minimal reproduction project

N/A

**Comment by poohcom1** [comment]
This is an expected breaking change: `@icon` has been changed in #67774 to be placed before `class_name`.

**Comment by clayjohn** [comment]
Tagging this as a documentation topic as this should be made more explicit in the [GDScript docs](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_basics.html)

**Comment by aXu-AP** [comment]
I don't know how to make this more explicit:

> Annotations can be specified one per line or all in the same line. They affect the next statement that isn't an annotation.

However, in [class reference](https://docs.godotengine.org/en/latest/classes/class_%40gdscript.html#class-gdscript-annotation-icon) the code snippet could have `class_name` declaration after `@icon` to make the point.
I think this is the kind of a problem, which affects only in transition phase, but new users will pick up the correct way simply by looking at examples.

**Comment by akien-mga** [comment]
I think the error message `Annotation "@icon" is not allowed in this level.` could be made more explicit. It's not obvious to users what "in this level" means, and that they just need to move it to the top.

**Comment by aXu-AP** [comment]
How about: `Annotation "@icon" must be before "class_name".`

**Comment by akien-mga** [comment]
Sounds good.

**Comment by dalexeev** [comment]
This also applies to `@tool` and potential other script-level annotations (for which `class_name` is not required, but should still be above `extends`). I think we need text like `"%s" annotation must be at the top of the script, before "extends" and "class_name".`.

**Comment by anatolbogun** [comment]
Thanks, good to know that it's not broken after all. It makes sense to have `@icon` at the beginning of a script.
I didn't notice that change when I reported the issue.

Changing the error message as suggested above would help. Thank you all for your contributions 🙇 .
