### ISSUE TITLE
Strange error with GDScriptCompiler at `_is_class_member_property`. Maybe cyclic dependency?

### ISSUE THREAD

**Issue by stephannv** [godotengine/godot#71944]
### Godot version

v4.0.beta15.official.4fa6edc88

### System information

Vulkan API 1.2.231 - Apple M1 Max

### Issue description

I'm getting this error: `Parse Error: Identifier not found: some_info` when running my project.
```
E 0:00:00:0201   _is_class_member_property: Condition "!nc" is true. Returning: false
  <C++ Source>   modules/gdscript/gdscript_compiler.cpp:63 @ _is_class_member_property()
```
![Sem título-2023-01-26-1935](https://user-images.githubusercontent.com/3025661/214967794-89702685-7b33-4342-829a-47a8fd8bac7f.png)

Error happens on Enemy script on line: `print(some_info)`.

The error is gone if:
-  I replace `enemy: Enemy` by `enemy` on `_on_enemy_collision` function from Entity script.
- or add `var x = preload("res://entity.gd")` on main scene script.

Looks like a circular dependency problem.

### Steps to reproduce

Download the project, comment the line 4 `var x = preload("res://entity.gd")` on `sandbox.gd` and run the main scene `sandbox.tscn`.

### Minimal reproduction project
[preload 3.zip](https://github.com/godotengine/godot/files/10514061/preload.3.zip)

**Comment by stephannv** [comment]
I managed to create a MRP. And cleanup the problem. Looks like a cyclic dependency.

**Comment by stephannv** [comment]
@akien-mga this is the issue I mentioned on mastodon.

**Comment by akien-mga** [comment]
CC @adamscott

**Comment by vnen** [comment]
Can you try again with the latest RC? I cannot reproduce with the attached project, I don't get any kind of error.

**Comment by stephannv** [comment]
@vnen I'm downloading the RC3 (It is super slow because tuxfamily servers) to test again. But I noticed I uploaded the project with an uncommented line, and the uncommented line is a workaround to solve the issue.
This way the error doesn't happen:
`sandbox.gd`:
<img width="421" alt="Screen Shot 2023-02-22 at 15 37 16" src="https://user-images.githubusercontent.com/3025661/220725386-2ccbac86-e85d-4bda-9977-ef34f5168e76.png">

This way the error happens:
`sandbox.gd`:
<img width="458" alt="Screen Shot 2023-02-22 at 15 37 53" src="https://user-images.githubusercontent.com/3025661/220725681-2ea7ba6d-f879-4a4c-b37b-b69889d114f7.png">

**Comment by vnen** [comment]
@stephannv thanks for checking. Indeed, if I comment the line I do get the error.

**Comment by vnen** [comment]
This is definitely because of circular dependency. The base scripts are accepted but since they might not have fully compiled yet it fails to find the member variable.

One solution to this is to rely on data from previous compilation steps instead of searching again for the identifier, which is actually something I wanted to do for a while but never got the chance. Unfortunately that would be a big change so it won't be done before 4.0 stable.

**Comment by adamscott** [comment]
@vnen Do you think it you can fix it for 4.1? Don't hesitate to poke me if you want to work together on this.

**Comment by Zireael07** [comment]
4.1. is right around the corner (beta 2 today), so I'm doubtful...

**Comment by stephannv** [comment]
When 4.1 comes out I will upload a MRP using the newer version.

**Comment by GreenCrowDev** [comment]
I tried to reproduce this on Windows 11, Godot 4.4.dev7.
I commented line 4 as said in the steps to reproduce.
I don't see the error.
Has this been fixed?

**Comment by stephannv** [comment]
> I tried to reproduce this on Windows 11, Godot 4.4.dev7. I commented line 4 as said in the steps to reproduce. I don't see the error. Has this been fixed?

I will try to reproduce it with latest Godot 4.4 in the next days.

**Comment by stephannv** [comment]
@vnen @GreenCrowDev @adamscott this problem doesn't happen anymore on Godot 4.4.dev7. Thanks. I'm closing this issue.
