### ISSUE TITLE
`collision_base_size` unit is px when it shouldn't have unit (`GPUParticles2D`)

### ISSUE THREAD

**Issue by aXu-AP** [godotengine/godot#71942]
### Godot version

v4.0.beta14.official [28a24639c]

### System information

Windows 10

### Issue description

`GPUParticles2D.collision_base_size` show units to be in pixels in editor. This is misleading, since the value doesn't change collider size in pixels, but multiplies it with the texture size.

Here's the exact logic how the size is calculated from `collision_base_size`:
https://github.com/godotengine/godot/blob/1dfd236f15d8553e0ad0c976eab93b70665c3b78/scene/2d/gpu_particles_2d.cpp#L188-L196

### Steps to reproduce

Add `GPUParticles2D` node. Look at property `collision_base_size` under Collision category.
![collision](https://user-images.githubusercontent.com/1621768/214155560-ea5c1ed2-6bc4-4776-bd7a-01b2900159c9.png)

### Minimal reproduction project

N/A

**Comment by Kabiirk** [comment]
Hi,

I am a beginner to open source. As per my understanding, this seems to be a UI change right (perhaps somwhere in ```scene/GUI```) ? I'll have to edit the file rendering this UI component. If so, can I work on this ?

**Comment by Kabiirk** [comment]
Ah, I see. Thanks for the tip ! I'll reach out in case I have few more queries.

As a rule of thumb, I try to get a good understanding about the scope of the issue (even if it is small/easy) as some issues can turn out to be deceptively more complex than they initially appear (previous experience lol).

**Comment by purviporwal0** [comment]
Could you please assign me this issue so I can work on it?

**Comment by Zireael07** [comment]
@purviporwal0 Godot Engine does not practice assigning people issues. Just start working on whichever issue you want to fix.

**Comment by Kabiirk** [comment]
Hi,

Based @aXu-AP's explanation about ```collision_base_size```, I have changed the unit from ```px``` to ```TextureSize``` which sounds more appropriate IMO. Please refer screenshot below :
![image](https://user-images.githubusercontent.com/16386226/214912302-1809b01c-4336-4d90-a3e1-efb4d4385d37.png)

For larger numbers, the 'unit text' overflows (refer screenshot below). Is this fine or should I change the 'unit text' to something else (I would be grateful for some suggestions, if possible) ?
![image](https://user-images.githubusercontent.com/16386226/214913135-eb611fd7-c7d5-404b-b548-3e46b7bb809e.png)

Thanks.

**Comment by aXu-AP** [comment]
I think removing unit text makes the most sense.

**Comment by Kabiirk** [comment]
Something like this ?
![image](https://user-images.githubusercontent.com/16386226/214931918-e951899a-ef9b-4965-a407-e1ca0e81ea90.png)

Let me make the PR, I'll see if any other changes maybe required.

**Comment by aXu-AP** [comment]
Yes, I think that is good, let's see how the pr review goes :)
