### ISSUE TITLE
Multi-Carets in the editor will forcibly unselect after the first character if Find / Find+Replace is open

### ISSUE THREAD

**Issue by TheRandomDog** [godotengine/godot#71955]
### Godot version

v4.0.beta14.official

### System information

Windows 11 22H2

### Issue description

There's not much to it, simply noticed that if you have Find or Find+Replace opened in the Script Editor, the Multi-Caret functionality seems to stop working -- forcibly removing all other carets after the first character is typed. I'd expect the Multi-Caret to remain until unselected by clicking elsewhere.

The content of what's in "Find" doesn't matter, it happens regardless.

https://user-images.githubusercontent.com/8159582/214234069-cbcc1681-3f09-4b10-9a90-857cc91d41a7.mp4

### Steps to reproduce

1. Open the Find or Find+Replace tool in the Script Editor _(nothing has to be inputted)_
2. Add multiple mouse cursors with Ctrl+Alt+Click **OR** highlight something and then highlight additional duplicates with Ctrl+D _(or synonymous keyboard shortcuts depending on OS)_.
3. Start typing as if going to add or replace in all locations where the multi-caret is

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
I can confirm this on 4.0.beta 4fa6edc88 (Linux).
