### ISSUE TITLE
AnimationPlayer timeline scrollbar not functioning properly.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#7196]
I'm using Windows 64 version of v2.1.1

In the AnimationPlayer, whenever I drag on the timeline's slider, it will only jump from end to end.  It also does some strange jumps when just clicking on the empty areas of the bar.  Is there some sort of option that I mistakenly set, or is this a bug?

Here is what it looks like when I drag from side to side.

![animation_player](https://cloud.githubusercontent.com/assets/13004169/20646052/2e3df586-b47b-11e6-8598-fc25d66719b3.gif)

**Comment by bojidar-bg** [comment]
Looks weird -- is it also present in 2.1(.0)?

**Comment by avencherus** [comment]
No it works fine in 2.1.0

![animation2 1](https://cloud.githubusercontent.com/assets/13004169/20649948/a566e214-b4d3-11e6-8f1b-515e433f1f74.gif)

**Comment by volzhs** [comment]
I confirmed it happens with current master head.

**Comment by akien-mga** [comment]
Might be related to the PR that changed step usage for sliders?

**Comment by volzhs** [comment]
@akien-mga probably yeah...
