### ISSUE TITLE
Posing Polygon2D by Skeleon2D is not affected by bones transformation

### ISSUE THREAD

**Issue by elmordo** [godotengine/godot#71962]
### Godot version

v4.0.beta.custom_build [3ef8d3e4e]

### System information

Pop_OS! Linux, NVIDIA GeForce GTX 1050 Ti 4GB GDDR5

### Issue description

When using `Skeleton2D` and `Nonde2D` with `Polygon2D` and rotating a bone, rotation pivot of `Polygon2D` seems not to be affected by its transformation.

### Steps to reproduce

Create a project with `Skeleton2D`, `Bone2D` and assign them to some `Polygon2D` and rotate some bones

### Minimal reproduction project

Here is project in Godot 4:

https://github.com/elmordo/SkeletonProblem_v4
https://youtu.be/BHGpk0PJ6s0

In Godot 3 works all fine:

https://github.com/elmordo/SkeletonProblem_v3
https://youtu.be/irPcaZ0ETEY

**Comment by clayjohn** [comment]
Seems like a duplicate of https://github.com/godotengine/godot/issues/71108

**Comment by elmordo** [comment]
@clayjohn  I read the #71108 and yes, it is the same. And read your comment there

> Right now to have rotations work correctly you need to set the polygon's pivot to be the origin (i.e. 0,0). This was not the case in 3.x, but due to how bones work in 4.0, it may be necessary.

so it is not bug and in Godot 4 we will have to set origin to [0, 0] and move texture around with `Polygon2D.offset` property?

**Comment by clayjohn** [comment]
> so it is not bug and in Godot 4 we will have to set origin to [0, 0] and move texture around with `Polygon2D.offset` property?

I hesitate to say that as the new behaviour is really annoying and I would like for us to find a way to get back to the old behaviour if we can. 

There is a button in the editor to place the root which sets the origin and ``Polygon2D.offset`` automatically, but it still feels like an unnecessary manual step

**Comment by elmordo** [comment]
> I hesitate to say that as the new behaviour is really annoying and I would like for us to find a way to get back to the old behaviour if we can.

Yep, it is really annoying, but it is still beta.

>There is a button in the editor to place the root which sets the origin and Polygon2D.offset automatically, but it still feels like an unnecessary manual step
 
Where is this button? I can't see it (I have build from yesterday's evening - 3ef8d3e4e80887d21009abc84def627e8a1c031f ). This button can save my sanity :-D

**Comment by clayjohn** [comment]
![Screenshot from 2023-01-24 11-08-29](https://user-images.githubusercontent.com/16521339/214385982-014c6c30-4512-46cd-9531-79cef60339a9.png)

**Comment by elmordo** [comment]
Oh, sorry, my bad. I didn't thing of this. Thank you very much :-)

(also closing this issue as duplicate)
