### ISSUE TITLE
TileMap editor shortcuts conflict with Scene shortcuts, context is only recognized when focusing TileMap window

### ISSUE THREAD

**Issue by hsandt** [godotengine/godot#71977]
### Godot version

v4.0.beta.custom_build [fcba87e69]

### System information

Linux Ubuntu 20.04 with Unity desktop

### Issue description

After painting some tiles with the v4 TileMap window in Paint mode, when I want to switch to Eraser mode with E, it switches to Scene Rotate mode instead (as it uses the same shortcut) and I accidentally rotate my whole tilemap...

If I make sure to click on the TileMap window first, the context is recognized and conflict is solved in favor of TileMap shortcuts. But this extra click defeats the purpose of the shortcut.

The same applies to all conflicting shortcuts.

I expected the TileMap shortcuts to be active when using the TileMap (selecting a TileMap with TileMap window opened).

Workaround: set TileMap shortcuts to other keys like Ctrl+E for Eraser, or M for Rect (this one was default in Godot 3 I think).

### Steps to reproduce

1. Create a TileMap with a dummy TileSet
2. Start painting tiles on the Scene
3. Without clicking anywhere else, press E (default shortcut for Eraser vs Rotate). Same for R (Rect vs Ruler Mode), S (Selection vs Scale)
Expected: switch TileMap mode
Actual: switch Scene tool

### Minimal reproduction project

N/A

**Comment by Rindbee** [comment]
TileMap editor shortcuts are global. Conflicting shortcuts have context, so they are handled first.

**Comment by hsandt** [comment]
So the solution would be to give "TileMap window open (but not necessarily focused)" context to TileMap editor shortcuts?

**Comment by Rindbee** [comment]
It's best not to conflict here, since both may be used. Or toggle the edit mode explicitly like in Blender.

**Comment by bkerz** [comment]
I'm also seeing this issue, tested in Ubuntu 22.04.3 LTS, Godot v4.1.2.stable.official [399c9dc39]

**Comment by bkerz** [comment]
Well, I tested on v4.2.dev6.official [57a6813bb] and it seems to be fixed now

**Comment by hsandt** [comment]
Indeed, verified on v4.2.beta4.official [93cdacbb0], as long as Select mode is active, shortcut will toggle Tilemap tools while editing tilemap as expected.

I'm closing this, although I would have really liked to know which commit actually did that (if it was a structural commit that improved shortcut context it would be nice, as it would also help with other parts of the editor).
