### ISSUE TITLE
GDScript2.0: `is_instance_valid` returns true on class type

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#71978]
### Godot version

v4.0.beta14.official [28a24639c]

### System information

All

### Issue description

I working on my plugin GdUnit4 a unit testing framework.

To decide if an argument is allowed to mock, I need to check if it is an instance or a type of a class.

like `func is_mockable(clazz :Variant) -> bool:`
it should return false if the given value a instance.
I use `is_instance_valid(instance)` to check if is an already created instance

But it says true for a class type
`is_instance_valid(RefCounted)`

### Steps to reproduce

Open the attached example project and run the test scene.

### Minimal reproduction project

[is_instance_valid.zip](https://github.com/godotengine/godot/files/10491156/is_instance_valid.zip)

**Comment by dalexeev** [comment]
I think this is... expected? At least for GDScript classes that are instances of the `GDScript` class. Native classes, if I'm not mistaken, are represented as `GDScriptNativeClass` wrappers, which are also objects.

**Comment by MikeSchulze** [comment]
If there a other way to detect is a variable a pure GDScriptNativeClass i'm also ok

**Comment by dalexeev** [comment]
```gdscript
func my_is_instance_valid(object: Object) -> bool:
    if not is_instance_valid(object):
        return false
    return not (object is Script) and object.get_class() != "GDScriptNativeClass"

func _run() -> void:
    print(my_is_instance_valid(RefCounted)) # false
    print(my_is_instance_valid(MyClass)) # # false
    print(my_is_instance_valid(MyClass.InnerClass)) # false
    
    print(my_is_instance_valid(RefCounted.new())) # true
    print(my_is_instance_valid(MyClass.new())) # true
    print(my_is_instance_valid(MyClass.InnerClass.new())) # true
```

**Comment by MikeSchulze** [comment]
Thank you, thats helps me. you my hero ;)

**Comment by dalexeev** [comment]
I'm not sure if this is a bug or a planned change.

```gdscript
@tool
extends EditorScript

func test(object: Object) -> void:
    pass

func _run() -> void:
    var node := Node.new()
    node.free()

    # Runtime error: Invalid type in function 'test' in base 'EditorScript ()'.
    # The Object-derived class of argument 1 (previously freed) is not
    # a subclass of the expected argument class.
    test(node)
```

**Comment by vnen** [comment]
> I'm not sure if this is a bug or a planned change.
> 
> ```gdscript
> @tool
> extends EditorScript
> 
> func test(object: Object) -> void:
>     pass
> 
> func _run() -> void:
>     var node := Node.new()
>     node.free()
> 
>     # Runtime error: Invalid type in function 'test' in base 'EditorScript ()'.
>     # The Object-derived class of argument 1 (previously freed) is not
>     # a subclass of the expected argument class.
>     test(node)
> ```
> 
> Crash is obviously a bug.

It could have a better error message for the case of freed objects, but it's expected that you cannot accept freed objects as arguments. While there could be an exception for `Object` type since everything inherits it anyway, I'm not sure if accepting those are fine.

For `Variant` type, it does not do any check so it's expected it accepts anything.

**Comment by vnen** [comment]
In any case, the original post is not a bug. `is_instance_valid()` is meant to check if the object is freed or not, it does not mean to check if it's an "instance" as opposed to a "class".

**Comment by MikeSchulze** [comment]
Thank you for the detailed explanations 👍.
