### ISSUE TITLE
Move tool in 2D editor does not suppress navigation

### ISSUE THREAD

**Issue by EchoingLogos** [godotengine/godot#71980]
### Godot version

4.0 beta 10

### System information

Windows 11

### Issue description

Using the default selection tool in the Scene editor allows the user to use arrow keys to move the selected node pixel per pixel.

This behavior is maintained when a different tool is selected, but the ability to navigate the editor is restored, making keyboard movement unusable.

### Steps to reproduce

Open the 2D editor.

Select the move tool.

With the mouse cursor hovering the editor body, press an arrow key.

### Minimal reproduction project

N/A

**Comment by Sauermann** [comment]
Can you please check a more recent built than beta 10?
In current master I can't replicate this behavior, but beta 6 has this problem.

**Comment by EchoingLogos** [comment]
Checked beta15. Behavior is fixed. Did not check because this had been an issue for a few months, apologies.
