### ISSUE TITLE
Base functions such as _process and _ready not functioning inside of classes (Godot 4)

### ISSUE THREAD

**Issue by ZachAR3** [godotengine/godot#71981]
### Godot version

4.0.beta14.mono

### System information

Endeavour OS Zen Kernel 6.1.7 Ryzen 5900x Nvidia RTX 2080TI 11GB (proprietary drivers)

### Issue description

When using a custom class made with `class_name example` and inheriting it into a script via `extends example` all of the base processes of Godot don't function inside of the base class. E.g:`_process` and `_ready`.

### Steps to reproduce

Create a scene and attach a script to it which we will call script A. Make another script and make it a class via `class_name example` which will be called script B. Have script A inherit from script B via `extends <script B>` and attempt to use any standard class functions inside of script B. None will work ,

### Minimal reproduction project

[BrokenClasses.zip](https://github.com/godotengine/godot/files/10491914/BrokenClasses.zip)

**Comment by DarkMessiah** [comment]
You need to call `super()`. Check this: https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_basics.html#inheritance
```
HelperScript.gd
extends BaseScript

# Function isn't called from inherited scripts as it should be making it useless in a class
func _ready():
        super()
	print("Helper ready")

func _process(_delta):
	super(_delta)
	#Runs process script in class
	_helper_run_process(_delta)```

**Comment by ZachAR3** [comment]
> You need to call `super()`. Check this: https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_basics.html#inheritance
> 
> ```
> HelperScript.gd
> extends BaseScript
> 
> # Function isn't called from inherited scripts as it should be making it useless in a class
> func _ready():
>         super()
> 	print("Helper ready")
> 
> func _process(_delta):
> 	super(_delta)
> 	#Runs process script in class
> 	_helper_run_process(_delta)```
> ```

That fixed it, thank you!
