### ISSUE TITLE
CharacterBody3D move_and_slide use an hardcoded delta time

### ISSUE THREAD

**Issue by Fabien2S** [godotengine/godot#71999]
### Godot version

v4.0.beta14.mono.official [28a24639c]

### System information

Win11

### Issue description

`move_and_slide()` in `CharacterBody3D ` uses [an hardcoded delta time](https://github.com/godotengine/godot/blob/9937915ad77059b63582ffd4e324afb26f467b76/scene/3d/physics_body_3d.cpp#L1161) which make it impossible to apply multiple inputs in the same frame.

I'm developing a fast-paced multiplayer game in which I want to implement client prediction and lag compensation. I need a way to apply a list of inputs (or velocity) multiple times in the same frame with each of them responding to collisions. Each of theses inputs should be executed 0.05 seconds apart (delta time), but as the delta time is hardcoded this make it quiet challenging.

I may be doing something wrong here, perhaps something not supported, in that case please let me know.
The documentation says nothing about calling `move_and_slide` only once per frame or something like that.

### Steps to reproduce

1. See https://github.com/godotengine/godot/blob/9937915ad77059b63582ffd4e324afb26f467b76/scene/3d/physics_body_3d.cpp#L1159-L1161

### Minimal reproduction project

N/A

**Comment by RemyCampanals** [comment]
I don't know why we don't have delta as an argument for move_and_slide() method, it could help if we want to create some slowmotion feature for our CharacterBody3D.

I think it could resolve many problems at once or i'm mistaken ?

**Comment by aXu-AP** [comment]
Calling `move_and_slide` multiple times in a frame seems to work. But you need to handle the velocity yourself in some custom manner. Something along these lines (untested):

```
velocity = velocity / delta # Counteract default delta value
velocity = velocity * custom_delta # Add your own delta
move_and_slide()
velocity = velocity * delta / custom_delta # Get modified velocity
```

**Comment by Fabien2S** [comment]
You're right, I should have posted this in godotengine/godot-proposals, my bad. I was quite tired when I post this.

Thanks you for the workaround, I tried to do the same thing but used a for loop which called move_and_slide multiple times based on the difference of the two delta times, which was really not working (obviously)

Do you think I should close this and create a proposal instead?

**Comment by aXu-AP** [comment]
Well, I'm not moderator or anything, so take that as a disclaimer. But that's what I'd do. Less headache for project management when everybody goes by the book.

**Comment by viksl** [comment]
Is that what move_and_collide is for? You utilize delta there for the vector input. Although you need to handle the custom behaviour on your own then.

**Comment by Calinou** [comment]
> I'm developing a fast-paced multiplayer game in which I want to implement client prediction and lag compensation.

You probably want support for manual physics simulation instead, which isn't implemented yet: https://github.com/godotengine/godot-proposals/issues/2821
