### ISSUE TITLE
Godot 4 move_and_slide with floor_snap_length doesn't snap and lets character leave ground at the top of an ascending slope 

### ISSUE THREAD

**Issue by hsandt** [godotengine/godot#71993]
### Godot version

v4.0.beta.custom_build [fcba87e69]

### System information

Linux Ubuntu 20.04 with Unity desktop

### Issue description

In Godot 4, move_and_slide_with_snap has been replaced with move_and_slide + setting floor_snap_length. However, even if floor_snap_length at the max value (32px), my character still leaves the ground instead of snapping to the floor when it reaches the top of an ascending slope. The issue occurs both ways:
1. when running up the slope and reaching flat ground, it leaves the floor for a short time due to momentum, then falls back on ground
2. when running on the flat ground toward the same slope (a descending slope from the character's PoV), it will take off due to momentum, then fall on the slope

![2023-01-24 move_and_slide takes off even with snap parameter](https://user-images.githubusercontent.com/1067772/214369333-a408af1b-1409-4223-b940-eb8c18a89b4c.gif)

(the GIF play slowly, this was not intended but since this can help seeing things I didn't reformat them)

The issue occurred with a slope of 45 degrees.

When testing in my minimal project, I tried again with different slopes, with the same issue. In addition, on low-angle ascending slopes, the character keeps falling and landing again as if it intermittently stopped detecting ground, similarly to this old Godot 3 bug: https://github.com/godotengine/godot/issues/16268 (but this is not the topic of this issue and will deserve another ticket for Godot 4).

![2023-01-24 move_and_slide takes off even with snap parameter (debug polygons)](https://user-images.githubusercontent.com/1067772/214383600-e09f9f8b-895e-438d-847b-dd3bea0ec531.gif)

A look at the [documentation](https://docs.godotengine.org/en/latest/classes/class_characterbody2d.html#class-characterbody2d-property-floor-snap-length) suggests that move_and_slide will only snap if "the body moves against up_direction", but "against" is not clearly defined (dot product of velocity with up_direction is negative? in this case, it only works when character is moving downward, which means it only snaps to escape being inside the ground; which is useful, but also the easy part of most physics engine; the hard part is to prevent the character from leaving the ground when it goes up, or enters a descending slope from flat ground).

A look at the current [code](https://github.com/godotengine/godot/blob/398e73c689e8506933a066c6a8045a50f58d0c04/scene/2d/physics_body_2d.cpp#L1408) suggests that move_and_slide will only snap if the character collides with the next floor, which is slightly different (it basically means that motion is against the outside floor normal direction, which is only equal to the up direction on flat ground; and only covers other cases where the character happens to enter some ground colliders). Again, this does not cover the important case where the character is reaching new ground with a slope relatively more "descending" than the previous ground and must avoid take off.

### Steps to reproduce

1. Open attached project and open the demo scene if needed
2. Play it and move around (keyboard left/right and Space to jump; you can even use the gamepad), esp. around the slope change area of the 3 debug colliders (if you don't see the colliders, make sure that Debug > Visible Collision Shapes is checked)
Expected: player character is always on ground. This can be seen as all grounded sprites are yellow (with an arrow indicating move direction).
Actual: player character leaves ground and falls back. This can be seen as all airborne sprites are red (with an arrow indicating move direction).

Note: do not worry about the purple line appearing at the top of the sprite, this is a known issue (https://github.com/godotengine/godot/issues/67164)

### Minimal reproduction project

[v4.0.beta.custom_build [9de0c73e4] - Character takes off ground even with snap parameter (no git).zip](https://github.com/godotengine/godot/files/10776906/v4.0.beta.custom_build.9de0c73e4.-.Character.takes.off.ground.even.with.snap.parameter.no.git.zip)

UPDATE: removed git history which was containing copyrighted assets. If you downloaded the old version, just delete the .git folder inside and it will be like this one.

Note that there are extra scripts like the add-on AS2P (which helped me generate the animations) and AppManager.gd, I kept them for convenience although they are not "minimal".

**Comment by hsandt** [comment]
If this is by design, then I suppose this proposal I've just found: https://github.com/godotengine/godot-proposals/issues/4259 may be what I need. One idea is to set a threshold to recognize a "true" jump and snap for any other small upward velocity (such as running off an ascending slope).

**Comment by hsandt** [comment]
OK, I managed to work around this and manually snap my character down to the ground with the following trick (adapted from my other projects in Unity and PICO-8):

1. call move_and_slide() with the true velocity set
2. check if character left ground, but is still close enough to it, using either a custom Raycast2D (or even 2, one on the left and one on the right of the character collision box, for maximum precision) or some move_and_collide with test_only = true
3. if close ground is detected, set velocity = (travel vector + margin) / delta time and move_and_slide() again using this adjusted velocity. The margin ensures we actually hit the ground with this extra motion, so is_on_floor() returns true afterward. I found margin = 0.5 to 1 * Vector2.DOWN to be good enough in my case.

After that, the velocity will be equal to the adjustment velocity, so if you need to check the velocity for other things like animation, I'd recommend you storing the true velocity somewhere.

The reason I use move_and_slide although I don't really want sliding in step 3 is because it's the only one that updates on_floor, see https://github.com/godotengine/godot-proposals/issues/6170

By the way, I tested 2D Platformer Demo (KinematicBody) (https://godotengine.org/asset-library/asset/120) in Godot 3 and the character snaps down properly when using `move_and_slide_with_snap` on this slope:

![image](https://user-images.githubusercontent.com/1067772/214679922-ab58c346-ed4e-45d9-90e1-5428952c9457.png)

so it may actually be a regression in Godot 4. This also means that finishing porting this demo project will be a good way to spot such issues.

**Comment by fabriceci** [comment]
In v4, `move_and_slide` no longer modifies the velocity to handle slopes, so it can uses `velocity` to understand the movement. So if there is a Y in the velocity, it means that the player is jumping or being pushed upwards by a force, and in this case the snap should not be applied.  Y velocity caused many issues (check here for info: https://github.com/godotengine/godot/pull/51645)

You seem to want code a custom mouvement but still use move and slide for `on_floor`. It's strange to want to manage slopes manually, and at the same time, using a function that manages slopes. Why do you need `on_floor` (I would like to understand your need)?

I think it would be useful to add a way to force the snap even if there is Y velocity. There is a proposal on how best to provide this: https://github.com/godotengine/godot-proposals/issues/4259

We can continue the discussion in the proposals (or in the chat) since the behaviour is the expected one.

**Comment by hsandt** [comment]
Yes, I already found that proposal (second post). It's good enough to me, esp. if the intention is to split the API into more parts (move_and_slide + snap), which I think is good to provide more control. I'll be testing the PR locally so I can go on with the 2D platformer demo.

I still have a question on the other part of the problem, snap up, as my character moves much more slowly that in Godot 3. I'll open a discussion for this.

**Comment by M7med-BRQ** [comment]
hi try use this code . 
	#slope fix-----------------------
	if is_on_floor():
		set_floor_snap_length(5)
		set_floor_max_angle(1.5)
	elif !is_on_floor(): 
		set_floor_snap_length(1)
		set_floor_max_angle(0.785398)
	apply_floor_snap() 
        move_and_slide()

**Comment by hsandt** [comment]
The issue is fixed now thx to new method `apply_floor_snap`, but I realized I never replied properly to the last question nor given my final solution so I'll do it now.

> You seem to want code a custom movement but still use move and slide for on_floor. It's strange to want to manage slopes manually, and at the same time, using a function that manages slopes. Why do you need on_floor (I would like to understand your need)?

- My character generally walks on the ground, but can also jump and move/execute actions differently in the air, so I need to check `is_on_floor()`
- I use `move_and_slide` for most of the motion
- ... then I need an extra custom move just for the snapping (before `apply_floor_snap` was added)
- Custom movement is indeed done better with `move_and_collide(Vector2)`...
- ... but `move_and_collide` doesn't update the result of `is_on_floor()`, so I decided to set `velocity` and call `move_and_slide` a 2nd time anyway. However, this approach caused the issue of giving an irrelevant velocity for next frame (only giving the vertical snap motion instead of the main horizontal/diagonal move), so I dropped it in favor of `move_and_collide`, since waiting 1 frame to get an updated `is_on_floor()` is not such a big deal.

But in the meantime, as seen in the PR above, `apply_floor_snap()` has been added it's now much more effective. It also checks for `is_on_floor()` on its own.

So in the end, after my main movement by setting `velocity` and calling `move_and_slide()`, I only needed to call `apply_floor_snap()`. In the case of a jump, I do not call it for 1 frame to avoid unwanted snap back (only needed if jump_speed * delta <= floor_snap_length).

Compared to @M7med-BRQ 's solution note that I must call `move_and_slide()` _before_ `apply_floor_snap()` or the character will still do a small bump when reaching slope angle change.

**Final solution chosen**

```gdscript
# ... code that calculates wanted_velocity and checks input to know if character should_jump
velocity = wanted_velocity
move_and_slide()
if not should_jump:
	apply_floor_snap()
```
