### ISSUE TITLE
ShaderMaterial params change all scenes that use it. Local to Scene not working

### ISSUE THREAD

**Issue by venilark** [godotengine/godot#71990]
### Godot version

4.0 beta 13

### System information

Windows 10

### Issue description

Two different meshes with two different materials, each one has a next pass ShaderMaterial. If you modify the values of the ShaderMaterial of one mesh, the others receive those changes too and I already set Local to Scene to true and tried different combinations, same exact result.

### Steps to reproduce

Press play, the script will change the params of cube1 but cube2 will be changed too.

### Minimal reproduction project

[shader-params.zip](https://github.com/godotengine/godot/files/10493004/shader-params.zip)

**Comment by clayjohn** [comment]
Did you make the ShaderMaterial unique? local to scene just means that it will not share with other instances of the _scene_, it does not mean that the resource will not be shared between instances within the same scene

**Comment by venilark** [comment]
I made it unique then the blue cube didn't turn white, but if I add another yellow cube this happens
![imagen](https://user-images.githubusercontent.com/98270528/214384980-5bbd21cb-77cb-499f-99df-99043102b927.png)

**Comment by clayjohn** [comment]
I ran the MRP. I can see that you are indeed using the materials within scenes, so local_to_scene is the correct approach. 

However, what you were missing was actually setting local to scene on the first material. You need to set local_to_scene on the parent resources as well. 

Here is the heirarchy that you have in the MRP
```
Mesh (local to scene)
  |->  Material (not local to scene)
         |-> Next pass (local to scene)
```
Setting the material to local_to_scene makes it work as expected

**Comment by clayjohn** [comment]
> Is this the correct way to achieve this if there are multiple instances, considering performance?

Yes
