### ISSUE TITLE
wiki doesn't has enough information about extending engine code

### ISSUE THREAD

**Issue by strobe** [godotengine/godot#72]
Please update wiki about advanced topics like:
- what is general architecture of engine?
- how to start writing c++ extension?
- what is the export template from developer perspective and how it possible to 
tune template code or write new from scratch?
- what is development environment you would like to recommend to working on engine code?

In other words please also provide documentation for quick starting contribution for engine itself.

**Comment by akien-mga** [comment]
Keeping this one open for the reference for now, but it will have to be moved to OpenProject once it is confirmed for documentation project management.

**Comment by akien-mga** [comment]
Actually closing this one as duplicate of #73, since the latter has more participants.
