### ISSUE TITLE
enable keypad navigation in text editor

### ISSUE THREAD

**Issue by adolson** [godotengine/godot#720]
With NumLock disabled, the keypad should allow the secondary functions in the text editor. For some laptops, this is the only way to use functions such as Home/End/PgUp/PgDn, for example.

**Comment by jfbilodeau** [comment]
Any development on that?

**Comment by hurikhan** [comment]
Does it concern all platforms?

**Comment by adolson** [comment]
No idea, I only have Linux.

**Comment by jfbilodeau** [comment]
Ditto.

**Comment by the-mech** [comment]
works fine on windows 7

**Comment by erbridge** [comment]
Also experiencing this on Linux.

**Comment by akien-mga** [comment]
I can confirm this with the current bd736e5.

**Comment by akien-mga** [comment]
Tested in the current master branch, it seems to work just fine.

**Comment by neikeq** [comment]
This was fixed by #3269
