### ISSUE TITLE
Crashes when deleting a .gd file

### ISSUE THREAD

**Issue by VsE-Gautier** [godotengine/godot#72005]
### Godot version

4.0 Beta 14

### System information

Windows 10, CPU : Intel Core I7-4790K, GPU : GTX 1060 6GB, RAM : 16GB

### Issue description

Hello,
My Godot (Forward+) crashes when I try to delete a .gd file.
It happens when I try to do it in the FileSystem in Godot but also in the Windows' file explorer.
I can delete .tscn file without any problem.
I opened godot with the PowerShell but no error showed up even with the --verbose parameter.

Same happened to a friend on Ubuntu. 
His config : 
-CPU : Ryzen 7 5800x
-GPU : RTX 3070 TI
-RAM : 16GB

### Steps to reproduce

Delete a script file

### Minimal reproduction project

[Godot4Test.zip](https://github.com/godotengine/godot/files/10494490/Godot4Test.zip)

**Comment by Icelogist** [comment]
Having the same problem, this also happens when you try to move the scripts to a different file, once reopening Godot the scripts have moved to the file I dragged them to. This also happens no matter what renderer you are using, I am currently using the "Compatibility" option.

**Comment by MewPurPur** [comment]
Should be fixed already: #71713

**Comment by akien-mga** [comment]
Duplicate of #71713
