### ISSUE TITLE
`Image.set_pixel()` not working properly on Mac

### ISSUE THREAD

**Issue by menimato** [godotengine/godot#72002]
### Godot version

v4.0.beta15.official [4fa6edc88]

### System information

macOS ventura 13.1, M1 Pro

### Issue description

`Image.set_pixel()` is not working properly when creating a new image in GDScript.

### Steps to reproduce

I am trying to create an `Image` with code and then use it to create an `ImageTexture` to set in a `Sprite2D`.

The code I'm using is:
```
func _ready():
	# creates image
	var img = Image.new()
	img.create(10, 10, false, Image.FORMAT_RGB8)
	
	# setting values pixel by pixel
	for i in range(10):
		for j in range(10):
			img.set_pixel(j,i, Color.RED)
	
	# creates and sets texture
	var tex = ImageTexture.new()
	tex.create_from_image(img)
	$Sprite2D.set_texture(tex)
```

Although I'm following the example code available in the documentation [available here](https://docs.godotengine.org/en/latest/classes/class_image.html#class-image-method-set-pixel), an error message appears for every `img.set_pixel()` like the following:
```
E 0:00:01:0571   _ready: Index p_x = 8 is out of bounds (width = 0).
  <C++ Source>   core/io/image.cpp:3274 @ set_pixel()
  <Stack Trace>  node_2d.gd:10 @ _ready()
```

I thought that maybe it was because I wasn't using `Image.lock()`, but it was removed in v4.0.

Because of this error, later when I do `$Sprite2D.set_texture(tex)`, another error appears like:
```
E 0:00:01:0572   _ready: Invalid image
  <C++ Error>    Condition "p_image.is_null() || p_image->is_empty()" is true. Returning: Ref<ImageTexture>()
  <C++ Source>   scene/resources/texture.cpp:171 @ create_from_image()
  <Stack Trace>  node_2d.gd:14 @ _ready()

```

It looks like a bug to me, can anyone else reproduce it on their machines?

### Minimal reproduction project

[Test_Texture.zip](https://github.com/godotengine/godot/files/10494324/Test_Texture.zip)

**Comment by AThousandShips** [comment]
Create returns an image, not updating the original
