### ISSUE TITLE
Script editor doesn't type some characters with a custom keyboard layout

### ISSUE THREAD

**Issue by Necronomicron** [godotengine/godot#72006]
### Godot version

v4.0.beta15.official [4fa6edc88]

### System information

Windows 10

### Issue description

I use a custom keyboard layout (I made it myself), and it has «dead keys» (just like International keyboard layouts have). For example, if I press `'`, nothing happens, but if I press `a` after that, I'll get `á`. If I press `'` and `Space`, I'll get just `'`. And with my layout:
If I press `Shift + .` and then `a`, I will get `ᵄ`.
If I press `Shift + .` and then `Space`, I will get `>`.
If I press `Shift + [` and then `5`, I will get `₅`.
If I press `Shift + [` and then `Space`, I will get `{`.
In beta 14 and before, everything worked fine, but in beta 15 when I press `Shift + .` and `Space`, just nothing happens, I don't get `>`. Same for `Shift + [` and `Space`, I don't get `>`. It seems the problem is with `Shift`, because I still can type `á` (`'` and `a`) or `'` (`'` and `Space`), but not `ä` (`Shift + '` and `a`) or `"` (`Shift + '` and `Space`). In the latter cases I get `á` and `'` as if `Shift` were never pressed.

### Steps to reproduce

Install/add US International keyboard layout or [Extended Latin keyboard layout](https://github.com/godotengine/godot/files/10494466/Layouts.zip) (just run `Extended Latin\ExtLat6\setup.exe`).
Open script editor.
Press `Shift + '`.
Then press `a`.

### Minimal reproduction project

N/A

**Comment by bruvzg** [comment]
Your layout is not functional at all (neither setup in the archive, nor new setup generated from `klc` file using Microsoft Keyboard Layout Creator), it's crashing explorer if you try to switch layout. But I was able to reproduce it with another layout.

**Comment by Necronomicron** [comment]
> Your layout is not functional at all (neither setup in the archive, nor new setup generated from `klc` file using Microsoft Keyboard Layout Creator), it's crashing explorer if you try to switch layout. But I was able to reproduce it with another layout.

Well, that's weird, cause I use this layout every day without any crashes. And the layout was generated by MSKLC itself, so I guess nothing I can do about it. 🤷‍♂️
