### ISSUE TITLE
`File` operations have disappeared in Godot 4.x?

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#72014]
### Godot version

v4.0.beta14.official [28a24639c]

### System information

Mac

### Issue description

I use `File` often for saving and loading of data.

I was trying to port a 3.5.1 project over to 4.x and the entire `File` access system is missing with [empty docs pages](https://docs.godotengine.org/en/latest/classes/class_file.html).

Has this been replaced with something or is Godot 4.x still missing a saving and loading feature?

If so it seems like it should be in the first stable version.

### Steps to reproduce

`File.new()`

### Minimal reproduction project

N/A

**Comment by arkology** [comment]
https://github.com/godotengine/godot/issues/66241

**Comment by tavurth** [comment]
@arkology Thank you!

**Comment by tavurth** [comment]
Perhaps the docs on this could be linked to the new page `File` could redirect to `FileAccess`?
