### ISSUE TITLE
Shader Globals in Compatability Mode Causes Shaders to Fail

### ISSUE THREAD

**Issue by MTareqAzim** [godotengine/godot#72016]
### Godot version

4.0dev_beta15

### System information

Windows10, GLES3, RX6600XT

### Issue description

Using Shader Globals (global uniforms) in Rendering Method gl_compatability (OpenGL3.3) causes shader compilation to fail.

### Steps to reproduce

Create a Shader Global of any type. This case I am using one named GLOBAL_BOOL of type bool.

Use the global in a gdshader:
```
shader_type spatial;

global uniform bool GLOBAL_BOOL;

void vertex() {
	GLOBAL_BOOL;
}
```

Attach shader to any material and get the following error:
```
  drivers/gles3/shader_gles3.cpp:242 - SceneShaderGLES3: Vertex shader compilation failed:
  ERROR: 0:386: '' :  syntax error, unexpected LEFT_BRACKET, expecting RIGHT_PAREN
  ERROR: 1 compilation errors.  No code generated.
```
The offending piece of generated glsl shader code:
```
385: 	{
386: 		bool(floatBitsToUint([m_GLOBAL_BOOL].x));
387: 	}
```

Basically it's trying to access the `global_shader_uniforms` array and retrieve the `m_GLOBAL_BOOL`th element, but it is forgetting to prepend the array name. It should look like this:
```
385: 	{
386: 		bool(floatBitsToUint(global_shader_uniforms[m_GLOBAL_BOOL].x));
387: 	}
```

Rummaging through the code, the `Shader::DefaultIdentifierActions` for GLES3 side of things found in `\drivers\gles3\storage\material_storage.cpp` forgets to set the value for `global_buffer_array_variable`. The fix would be to add the line
```actions.global_buffer_array_variable = "global_shader_uniforms";```
before initializing the `ShaderCompiler`s. There are four `ShaderCompiler`s so you would need to add that line before each of their initializations if you want all of them to have access to Shader Globals. Attached is the laziest updated code to `material_storage.cpp` that fixes this issue.
[material_storage_fix.zip](https://github.com/godotengine/godot/files/10497086/material_storage_fix.zip)

### Minimal reproduction project

[GlobalShaderUniformsBug.zip](https://github.com/godotengine/godot/files/10497094/GlobalShaderUniformsBug.zip)

**Comment by akien-mga** [comment]
I believe shader globals are not supported in the compatibility renderer, but if so we need to improve the UX so that it reports a proper error about lack of support, instead of syntax errors. CC @godotengine/shaders

**Comment by clayjohn** [comment]
They should be supported. The fix provided by OP looks correct

**Comment by lostminds** [comment]
There seems to be a similar issue with compatibility mode shader compilation for the new instance uniforms as well. In that case I'm not sure they're meant to be supported in the compatibility renderer, but currently they have the same issue as above that they're added in the shader code as just brackets (for example `float m_n_out6p0=([(+0)].x);`) without the proper array variable name before the brackets, resulting in a syntax error and failed shader compilation.
