### ISSUE TITLE
Carets on an empty line in the code editor have a missing pixel

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#72013]
### Godot version

 Latest 4.0.dev (a3a42159e31db27f8ae7c1ecad6a9ed417cb05de)

### System information

Ubuntu 22.04.1 LTS

### Issue description

![image](https://user-images.githubusercontent.com/85438892/214476911-0ce83a43-b959-4b13-88fd-d6b9af0cd63a.png)

### Steps to reproduce

Open any script

### Minimal reproduction project

N/A

**Comment by timothyqiu** [comment]
It seems that it's not missing a pixel, but an extra black pixel on top of the caret.

On a non-empty line, that black pixel is at the bottom of the caret.

![ksnip_20230125-134337](https://user-images.githubusercontent.com/372476/214489550-bb51ea24-f129-4d43-af15-e5c443023898.png)

Whenever I take a screenshot, this black pixel disappears right after. When I close the script editor and switch back on, it appears again.
