### ISSUE TITLE
Releasing a Control's focus will unfocus the entire window on Linux/GNOME

### ISSUE THREAD

**Issue by nyairobi** [godotengine/godot#72023]
### Godot version

v4.0.beta15.mono.official [4fa6edc88]

### System information

Linux, Xorg

### Issue description

The entire window loses focus if you ungrab focus from a Control. 
This doesn't seem to happen in Beta 14 and older betas.

### Steps to reproduce

1. Create a Control that can grab focus (tested with LineEdit and TextEdit)
2. Grab focus
3. Release focus via release_focus() or hiding the node

### Minimal reproduction project

[FocusMinimal.zip](https://github.com/godotengine/godot/files/10498175/FocusMinimal.zip)

**Comment by akien-mga** [comment]
I can't reproduce the issue on 4.0.beta15.official on Linux (Mageia 9, KDE Plasma, KWin/X11). Both beta 14 and beta 15 behave the same, the TextEdit loses focus but the window is still the main one in focus.

I confirmed it by adding this to the script:
```gdscript
func _input(event):
	if event.is_action_pressed("ui_accept"):
		print("hey")
```

Pressing "Enter" properly prints "hey" even after releasing focus from the TextEdit.

Which Linux system and window manager are you using?

**Comment by Sauermann** [comment]
I can't replicate this problem on Windows with v4.0.beta.custom_build [4368191a9].
The Window keeps its focus for me.

**Comment by nyairobi** [comment]
It's also an issue on Wayland Gnome, with extra steps:
1. Focus and unfocus the Control, then don't click anything
2. Move the cursor away from the window's bounds
3. The window will immediately lose focus, and it will behave like on Xorg from now on

And, again, it doesn't happen in Beta 14.

The desktop is Gnome 43.1-1 (Arch, up to date), all extensions disabled, the kernel is 6.1.7.arch1-1, and I can't replicate it on Openbox so it has to be related to Gnome.

**Comment by boruok** [comment]
do you noticed popup autoclosing in that version?
1. open any script (script editor must be active)
2. right click in file browser (autoclose)
3. any click in top right menu items, where sceme, project, debug (autoclose)

**Comment by Calinou** [comment]
If you can [compile the engine from source](https://docs.godotengine.org/en/stable/development/compiling/index.html), you could look into [bisecting the regression](https://docs.godotengine.org/en/stable/community/contributing/bisecting_regressions.html) to greatly speed up troubleshooting.

**Comment by boruok** [comment]
```console
git bisect start
# status: waiting for both good and bad commits
# bad: [10d22a4b35b33ad89f626c261ef7f1aeae81daf3] Merge pull request #72067 from dsnopek/webxr-tutorial-godot-4
git bisect bad 10d22a4b35b33ad89f626c261ef7f1aeae81daf3
# status: waiting for good commit(s), bad commit known
# good: [28a24639c3c6a95b5b9828f5f02bf0dc2f5ce54b] Merge pull request #48570 from Calinou/animation-editors-new-name
git bisect good 28a24639c3c6a95b5b9828f5f02bf0dc2f5ce54b
# good: [35c37ce4ce5d1559ae4548ebb2c0c7286cb90a3d] Merge pull request #67847 from rburing/warn_non-uniformists
git bisect good 35c37ce4ce5d1559ae4548ebb2c0c7286cb90a3d
# bad: [ffb7c6e2fcdb5133de5a7941dc2314f6139a525a] Merge pull request #71957 from aXu-AP/remotetransform2d-doc
git bisect bad ffb7c6e2fcdb5133de5a7941dc2314f6139a525a
# bad: [738e96529eeb623e20fdda15c57e11ebe087b16a] Merge pull request #71925 from clayjohn/RD-particles-view
git bisect bad 738e96529eeb623e20fdda15c57e11ebe087b16a
# good: [9ae7a2554cb90418af517c91e0b7f8e8d5d4fe4a] Merge pull request #71912 from KoBeWi/another_regression_DEAD
git bisect good 9ae7a2554cb90418af517c91e0b7f8e8d5d4fe4a
# bad: [5c4fe6339bcb4d5539e39cc84f075461b9156ddc] [Linux/BSD] Include headers for dynamically loaded libraries to simplify build dependencies.
git bisect bad 5c4fe6339bcb4d5539e39cc84f075461b9156ddc
# good: [11e227884458e1f5661dcd27e846b6996271467e] Merge pull request #57606 from SaracenOne/update_on_reimport
git bisect good 11e227884458e1f5661dcd27e846b6996271467e
# good: [81fe3715b825dfc2b02adced8c08f8bc88220cb7] Merge pull request #71914 from vnen/gdscript-no-continue-match
git bisect good 81fe3715b825dfc2b02adced8c08f8bc88220cb7
```

i can't bisect further:
```console
scons: Reading SConscript files ...
Automatically detected platform: linuxbsd
Package xkbcommon was not found in the pkg-config search path.
Perhaps you should add the directory containing `xkbcommon.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xkbcommon' found
OSError: 'pkg-config xkbcommon --cflags' exited 1:
  File "/home/boruok/Documents/GitHub/godot/SConstruct", line 538:
    detect.configure(env)
  File "/home/boruok/Documents/GitHub/godot/./platform/linuxbsd/detect.py", line 195:
    env.ParseConfig("pkg-config xkbcommon --cflags")
  File "/usr/lib/python3/dist-packages/SCons/Environment.py", line 1612:
    return function(self, self.backtick(command))
  File "/usr/lib/python3/dist-packages/SCons/Environment.py", line 599:
    raise OSError("'%s' exited %d" % (command, status))

```

**Comment by akien-mga** [comment]
You need to install xkbcommon-devel or similar to build further, it was required for a few commits before 5c4fe6339.
