### ISSUE TITLE
shader_params in tween_property() returns null unless that param was previously set

### ISSUE THREAD

**Issue by venilark** [godotengine/godot#72021]
### Godot version

4.0 beta 14

### System information

Windows 10

### Issue description

Tried to use a tween to change the value of a shader_param using "shader_param/flash_modifier" in the tween_property() method, but it returns null.
However, if it is previously set using 
	shader_material.set_shader_parameter("flash_modifier", 1)
then the Tween works just fine

### Steps to reproduce

Press play, it works, then comment out the first line in _ready() to make the tween return the error.

### Minimal reproduction project

[shader-params.zip](https://github.com/godotengine/godot/files/10497741/shader-params.zip)

**Comment by Zireael07** [comment]
dupe of https://github.com/godotengine/godot/issues/44454 ?

**Comment by akien-mga** [comment]
Looks like it indeed.
