### ISSUE TITLE
`Array.slice` has an off-by-one error

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#72027]
### Godot version

v4.0.beta14.official [28a24639c]

### System information

Mac

### Issue description

```gdscript
print([1,2,3,4,5,6,7,8,9].slice(0, -1))
```

The above should include nine, but instead prints:

`[1, 2, 3, 4, 5, 6, 7, 8]`

### Steps to reproduce

```gdscript
print([1,2,3,4,5,6,7,8,9].slice(0, -1))
```

### Minimal reproduction project

N/a

**Comment by tavurth** [comment]
```gdscript
var a = [1,2,3,4,5,6,7,8,9]
print(a.slice(0, len(a)-1))
```

Also prints `[1, 2, 3, 4, 5, 6, 7, 8]`

**Comment by tavurth** [comment]
To get the correct result you have to now do:

```gdscript
var a = [1,2,3,4,5,6,7,8,9]
print(a.slice(0, len(a)))
```

However, negative slices are not working as expected.

**Comment by aXu-AP** [comment]
I think this is how it should work? As noted by class reference:

> Returns the slice of the Array, from begin (inclusive) to _end (exclusive)_, as a new Array.

So the ending index is not included in resulting array. As you noted, these are the same:

```
print(a.slice(0, -1))
print(a.slice(0, len(a)-1))
```
Which return whole array except for the last element (index of which is `len(a)-1`).

**Comment by STUDIOEMBYR** [comment]
This is the intended behaviour I believe.

**Comment by akien-mga** [comment]
Yes this is intentional. See #56661.

**Comment by tavurth** [comment]
Perhaps we should note in the docs somewhere that this has been updated. It took a while to track down this change when upgrading to 4.x

**Comment by aXu-AP** [comment]
I too have pondered on how to know all the changes in Godot 4.
With endless amount of small changes a full upgrade guide would be quite big and hard to make.
If class reference would have a note on each method that has been changed, that would too have it's own cons. Adding extra information, which would become unnecessary in a few years (after most have moved on from 3.x). In this case especially, since old behaviour was the stranger one (see issues akien linked).

**Comment by tavurth** [comment]
> I too have pondered on how to know all the changes in Godot 4.
> With endless amount of small changes a full upgrade guide would be quite big and hard to make.

This is the fourth (fifth?) time I've tried to upgrade my main project to Godot 4.x and I can see the amount of hard work that has gone into it.

There are a few niggling issues but in general I was excited and impressed to see that it took less than two hours to get it to render again.

Perhaps however a migration guide, which contains such things in an easy to read format could be helpful for users who will upgrade.

**Comment by tavurth** [comment]
Perhaps the migration tool could add a `TODO` to each `array.slice` call.

I usually calculate indexes and so I doubt the tool could resolve it correctly unless using ChatGPT 😂 

However a small TODO note would be very much appreciated and it would only apply to older projects as the upgrade tool would be working on them anyway.
