### ISSUE TITLE
Keeping a project on a mounted `.dmg` file on Mac causes issues with Project list

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#72038]
### Godot version

v4.0.beta14.official [28a24639c]

### System information

Mac Monterey 12.2.1 (21D62)

### Issue description

I have some projects that are only ever run from a `.dmg` file for portability.

In Godot 3.x the project appears in the project list when the `.dmg` is mounted.

When the `.dmg` is unmounted, the project will not appear in the list.

In Godot 4.x the project is never saved to the project list, which means I have to type out the path each time I open Godot.

### Steps to reproduce

1. Unzip the file below
2. Mount the `dmg_test.dmg`

[dmg_test.dmg.zip](https://github.com/godotengine/godot/files/10499851/dmg_test.dmg.zip)

Alternately:

1. Create a new folder
2. Add a project inside that folder
3. Open DiskUtility (Mac)
4. Choose File -> New -> Disk from folder
5. Select your project folder

## Then

Mount the `dmg` file
Try to import the project in Godot project editor

In Godot 3.x this will work, and when you quit Godot and restart the project will remain
In Godot 4.x this will not work, and when you restart Godot the project will not appear in the project list

### Minimal reproduction project

[dmg_test.dmg.zip](https://github.com/godotengine/godot/files/10499851/dmg_test.dmg.zip)

Please note: The same issue will probably appear with projects stored on USB flash drives

**Comment by Calinou** [comment]
> Please note: The same issue will probably appear with projects stored on USB flash drives

Can you test this to make sure?

**Comment by tavurth** [comment]
> Can you test this to make sure?

I just tested

1. Add a USB drive
2. Create a project on the USB drive
3. Quit to project list

The project is not listed

**Comment by tavurth** [comment]
> Can you test this to make sure?

I just tested

1. Add a USB drive
2. Create a project on the USB drive
3. Quit to project list

The project is not listed

**Comment by bruvzg** [comment]
Can't reproduce on macOS 13.1, projects on USB drive are listed correctly, same with DMG.

**Comment by tavurth** [comment]
It's a human bug 🤦 

Default sorting is by path instead of by recently edited.
