### ISSUE TITLE
Editor nodes not filtered on the 'Create CanvasItem' window

### ISSUE THREAD

**Issue by EXSPIRAVIT1104OFFICIAL** [godotengine/godot#72033]
### Godot version

v4.0.beta15.official [4fa6edc88]

### System information

Windows10, Forward+, AMD Ryzen 5 5600H with Radeon Graphics

### Issue description

Users can only add Control and Node2D nodes on the Create CanvasItem window, but there are Editor nodes not filtered out. 

### Steps to reproduce

Right-clicking on the 2D viewport. Select the add node feature. A Create CanvasItem window shows. Users can only add Control and Node2D nodes, but there are Editor nodes not filtered out.
![图片](https://user-images.githubusercontent.com/80319225/214565483-98717565-c2e5-41d8-83a0-a985a96fc595.png)

### Minimal reproduction project

No project is needed.

**Comment by KoBeWi** [comment]
This is not a regression, the issue also exists in 3.5

**Comment by Calinou** [comment]
I think EditorSpinSlider is here by design, because it's an exposed node that is also available in exported projects if I'm not mistaken.
