### ISSUE TITLE
Importer with `apply_root_scale`, scale not applied to custom shape for collider

### ISSUE THREAD

**Issue by JonqsGames** [godotengine/godot#72049]
### Godot version

4.0 beta 15

### System information

Windows 10

### Issue description

When ticking `apply_root_scale` the scale is not applied to custom collision shape set in importer.
This apply for `shape_type`  Box, Sphere, Cylinder and Capsule

_I tried to fix it myself but i'm a bit confused on how to have acces to the `apply_root_scale` and `root_scale` at the moment where the shape is generated_

### Steps to reproduce

- Add a 3d model.
- Generate physics for the mesh
- Select a `shape_type` for example Box
- Add `root_scale` != 1 and tick `apply_root_scale`

### Minimal reproduction project

[BoxColliderImport.zip](https://github.com/godotengine/godot/files/10500751/BoxColliderImport.zip)

**Comment by Zireael07** [comment]
Note that collision shapes should NEVER be scaled.

**Comment by Calinou** [comment]
cc @SaracenOne

**Comment by JonqsGames** [comment]
@Zireael07  agree and without the `apply_root_scale` the scale is left to the root node so it may be dangerous too. At least the scale is always uniform so i think it's not that bad.


I think the scale should be applied to the shape parameters before generating it. From what i understand the `apply_root_scale` modify the import parameters accordingly before importing for other nodes. I think this should also apply to the shape parameters. I'll look more into it.
