### ISSUE TITLE
Adding a ProximityFade node in the shader editor reports an error

### ISSUE THREAD

**Issue by 1419427247** [godotengine/godot#72042]
### Godot version

v4.0.beta14.mono.official [28a24639c]

### System information

Win10

### Issue description

![image](https://user-images.githubusercontent.com/33598732/214590159-f3f3705e-cdd1-4abc-81d1-de1d4b0cf0ee.png)

### Steps to reproduce

As shown in the figure

### Minimal reproduction project

N/A

**Comment by Chaosus** [comment]
Fixed by https://github.com/godotengine/godot/pull/71760. Please download the beta 15.
