### ISSUE TITLE
Clicking away from certain popups compromises the editor

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#72055]
### Godot version

Latest 4.0.dev (41e5f5b0930343ef548a56d553ba20fafd672147)

### System information

Ubuntu 22.04.1 LTS

### Issue description

The editor becomes prohibitively slow when clicking away from certain in-editor popups. So far, I have found this with the color picker button's popup (interestingly, the one in the gradient editor doesn't do that) and with the node rename popup. It only happens when you click away and not if you press <kbd>Esc</kbd>. It also compromises more than just the editor's performance, blocking the scrollbars for example and many more things.

https://user-images.githubusercontent.com/85438892/214590591-2aa51a1d-d62f-4a42-b639-e6f184be224f.mp4

(this video uses a tool script to demonstrate the loss of performance too)

### Steps to reproduce

Click on a node twice to rename it. Then click away from the popup. Try to move scrollbars and see that they are locked in place.

### Minimal reproduction project

N/A

**Comment by barbaros83** [comment]
i think i have the same problem, with the latest beta (15), i couldn't pinpoint what the reason is, but it completely freezes my pc, i have to reset it

**Comment by Zireael07** [comment]
@barbaros83 your issue is a dupe of the pinned #72012

OP's issue reminds me of another one, where it's the compositor/system deciding to drop unfocused windows to 1 fps

**Comment by MewPurPur** [comment]
I found nothing specific, this happened even in an empty project. But I can no longer reproduce this in the latest dev build. Can anyone confirm that it has been fixed?

**Comment by MewPurPur** [comment]
Indeed, it's fixed on my system with my setup.
