### ISSUE TITLE
Editor gets stuck when saving gdscript or opening editor settings after attaching script

### ISSUE THREAD

**Issue by beicause** [godotengine/godot#72052]
### Godot version

4.0 beta15

### System information

Ubuntu 22.04, GLES3

### Issue description

 The new windows and editor are stuck and flashing.

![Screenshot_20230125_235453](https://user-images.githubusercontent.com/75941842/214613938-8953719e-c424-4777-a6ab-14233b7a5e52.png)

The outputs:

❯ ./Desktop/Godot_v4.0-beta15_linux.x86_64 -v
Godot Engine v4.0.beta15.official.4fa6edc88 - https://godotengine.org
TextServer: Added interface "Dummy"
TextServer: Added interface "ICU / HarfBuzz / Graphite (Built-in)"
XInput: Refreshing devices.
XInput: Absolute pointing device: xwayland-pointer:10
XInput: Using touch device: xwayland-touch:10
XInput: Absolute pointing device: xwayland-touch:10
Detecting GPUs, set DRI_PRIME in the environment to override GPU detection logic.
Text-to-Speech: Speech Dispatcher initialized.
Only one GPU found, using default.
Using "default" pen tablet driver...
OpenGL Renderer: AMD RENOIR (LLVM 13.0.1, DRM 3.42, 5.15.0-58-generic)
JoypadLinux: udev enabled and loaded successfully.
PulseAudio: context other
PulseAudio: context other
PulseAudio: context other
PulseAudio: context ready
PulseAudio: Detecting channels for device: alsa_output.pci-0000_03_00.6.analog-stereo
PulseAudio: detected 2 output channels
PulseAudio: audio buffer frames: 512 calculated output latency: 11ms

TextServer: Primary interface set to: "ICU / HarfBuzz / Graphite (Built-in)".
CORE API HASH: 2707759663
EDITOR API HASH: 601774097
EditorSettings: Load OK!
Loaded builtin certs
EditorSettings: Save OK!
Editing project: /d/luo/godot-demo-projects/my-demo
EditorSettings: Save OK!
XR: Clearing primary interface
XR: Removed interfaceNative mobile
XR: Removed interfaceOpenXR
PulseAudio: context terminated
Godot Engine v4.0.beta15.official.4fa6edc88 - https://godotengine.org
Vulkan API 1.3.204 - Using Vulkan Device #0: AMD - AMD RADV RENOIR
Orphan StringName: SceneMultiplayer
StringName: 1 unclaimed string names at exit.

~ ❯ WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:61)

### Steps to reproduce

Create a empty project, add a node and attach a gdscript to it, then press ctrl+s or open editor settings.

### Minimal reproduction project

 It seems to happen in any projects.

**Comment by akien-mga** [comment]
Likely duplicate of https://github.com/godotengine/godot/issues/72012

**Comment by beicause** [comment]
Fixed in the latest master branch
