### ISSUE TITLE
[Beta 15 C#] Clicking on `AnimationPlayer` node closes project

### ISSUE THREAD

**Issue by valkyrienyanko** [godotengine/godot#72065]
### Godot version

v4.0.beta15.mono.official [4fa6edc88]

### System information

Windows 10, RX 6600, 10400

### Issue description

Clicking on a `AnimationPlayer` node closes the project. Nothing is logged in Godot editor console using `--verbose` when this happens.

### Steps to reproduce

1. Clone the GitHub repo [zombies](https://github.com/Valks-Games/zombies) *(Note that this was tested on the repo commit `58d81a1` called "update to beta 15")*
2. Open the project, you will see something like this below

![Preview](https://user-images.githubusercontent.com/6277739/214654484-264abc72-933e-49bf-acb4-8b5f2c4ad091.PNG)

3. Open up a scene for any of the `Zed`'s
4. Click on their `AnimationPlayer` node
5. Notice how the project closes

### Minimal reproduction project

[Zombies.zip](https://github.com/godotengine/godot/files/10502571/Zombies.zip)

**Comment by lyuma** [comment]
Can you test this on beta16 (released on friday/saturday) and see if it's still happening?

**Comment by valkyrienyanko** [comment]
Wow looks like it got fixed 👍
