### ISSUE TITLE
Pile of stacked RigidBodies is wobbly

### ISSUE THREAD

**Issue by GorEldeen** [godotengine/godot#72063]
### Godot version

4.0

### System information

Linux mint, GLES3, Nvidia quadro 2000m

### Issue description

So i was trying to test 2d physics using 'Rigidbody 2d' nodes in godot, I made 'static body' nodes to make kind of a box to run the simulation, using 'marker 2d' as a position detector and making it spawn the rigidbodies, and a 'timer' node to give breaks between spawn times

### Steps to reproduce

https://user-images.githubusercontent.com/112822849/214648604-dbfb91b4-b8d1-4d33-b678-0d38ddb4811d.mp4

### Minimal reproduction project

[Test 2 godot 4.zip](https://github.com/godotengine/godot/files/10502377/Test.2.godot.4.zip)

**Comment by MewPurPur** [comment]
Looks like #2092 is back?

**Comment by Calinou** [comment]
Increasing physics FPS can help mitigate the issue at the cost of increased CPU usage.

**Comment by GorEldeen** [comment]
Well yeah but it should probably get fixed so it won't affect low end devices

**Comment by pwab** [comment]
> Looks like https://github.com/godotengine/godot/issues/2092 is back?

In fact, #2092 was not completely solved by #55602, which can be seen in @fabriceci's [comment](https://github.com/godotengine/godot/pull/55602#pullrequestreview-823436480).

For a better reproduction project the `rectangle_stack` and `rectangle_pyramid` test in [Godot-Physics-Tests](https://github.com/fabriceci/Godot-Physics-Tests/tree/master/tests/nodes/RigidBody/tests/2d) could be used. I only needed to increase the `height` property from 10 to 11 or 12 in both tests to get collapsing piles and this shaking behavior when there is not enough room for the boxes to move to the side.

**Comment by fabriceci** [comment]
I don't think it's a bug but the stability limit of the current engine, all engines break down at some point.

The engine tries to balance the simulation (by applying impulses between the bodies) and at some point the instability builds up and the simulation breaks.

**Comment by Seubmarine** [comment]
> 

It's normal for an engine to break at some point but this should be stable when there is only this amount of simple 2D rectangle shape.
