### ISSUE TITLE
AnimationTree AnimationNodeStateMachinePlayback does not play at runtime

### ISSUE THREAD

**Issue by mgrigajtis** [godotengine/godot#72070]
### Godot version

4.0.dev

### System information

Windows 11, NVIDIA 3060, Vulkan Mobile

### Issue description

When using an AnimationTree with AnimationNodeStateMachinePlayback, animations do not start during the game.  They also can't seem to be manually started from Code.  The .is_playing() method always returns false.  The animations have worked previously about a week ago.

### Steps to reproduce

Create an AnimationTree node using AnimationNodeStateMachinePlayback.  Run game.

### Minimal reproduction project

N/A

**Comment by eviltrout** [comment]
You might be encountering a recent API change outlined here:

https://github.com/godotengine/godot/pull/71418

In my code, I had to update a line from this:

```
anim_tree.set("parameters/Action/current", 1)   # Where 1 was the index of the `Entering` state
```

To this:

```
anim_tree.set("parameters/Action/transition_request", "Entering")
```

Then it worked as expected.

**Comment by TokageItLab** [comment]
Too little explanation. Moreover, the Minimal reproduction project is lacking. StateMachine is currently working properly.
