### ISSUE TITLE
clip_children has no effect on PointLight2D

### ISSUE THREAD

**Issue by PhilWun** [godotengine/godot#72073]
### Godot version

4.0-beta14

### System information

Fedora 37

### Issue description

When the `clip_children` property of a PointLight2D node is set to `Clip Only` or `Clip + Draw` it has no effect on child nodes. Example scene:
![image](https://user-images.githubusercontent.com/2245391/214673750-4e550ab3-1722-4c23-97c0-b6ba9e68a675.png)
The selected node is a PointLight2D with a white circle as texture and `clip_children` set to `Clip Only`. The dark grey rectangle has a LightOccluder2D to block some of the light. The purple rectangle is a child node of the PointLight2D and I would expect it to be clipped to the light of the PointLight2D and the light texture to be invisible. But that is not the case. In Godot 3.5 I can get the expected effect with the mask mode that was removed in Godot 4.0:
![image](https://user-images.githubusercontent.com/2245391/214678431-760acabd-29b4-498b-8d46-d7a2dcbb257e.png)
I know that `clip_children` works with other CanvasItems, but they don't react to light occluders, so I can't use them to create the same effect that the mask mode in 3.5 could.

### Steps to reproduce

- create a PointLight2D node and set a texture
- add a child node with a texture
- set `clip_children` of the PointLight2D to `Clip Only`

### Minimal reproduction project

The example scene for Godot 4.0: [PointLight2DBug_4_0.zip](https://github.com/godotengine/godot/files/10503343/PointLight2DBug_4_0.zip)
a similar scene for Godot 3.5 with mask mode that shows how it should look like: [Light2DMaskMode_3_5.zip](https://github.com/godotengine/godot/files/10503348/Light2DMaskMode_3_5.zip)

**Comment by clayjohn** [comment]
The ``clip_children`` property should be removed from PointLight2D and other CanvasItem derived nodes that are not rendered as draw commands

**Comment by AThousandShips** [comment]
I'll take a stab at this today

**Comment by AThousandShips** [comment]
Opened a PR for this
