### ISSUE TITLE
Buttons do not send signals if they are not inside the bounds of a panel.

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#7208]
**Operating system or device - Godot version:**
Windows 10 Pro x64. 
Godot 2.1.1 stable

**Issue description** (what happened, and what was expected):
For some reason if a button is not inside the bounds of a panel or a button container, they do not send any signals even if they are the child of another object.

**Steps to reproduce:**
create a button not inside the bounds of a panel or a button container. Attach a script that sends a signal when pressed. Proceed to test clicking said button.

**Link to minimal example project** (optional but very welcome):

**Comment by puppetmaster-** [comment]
There is a parameter in the texture button "click on press" can you look if it is set.
I have had the same problem on my old 2.0 projects.

```
node2d
 - textureButton
```

I used this for animating a button (rotating and scaling).

**Comment by vonflyhighace2** [comment]
Tied using the recommended settings but still don't work. Strange since I have a texture button inside the same control that does.

**Comment by Keetz** [comment]
Could it be that you have a Control node above that blocks mouse clicks.
If anything is in front of your button and Focus mode "Stop Mouse" is on, the buttons wont work.

I haven't had this problem at least,  i have texture buttons just as a child of a Control node, and  their signals get triggered just fine.

**Comment by bojidar-bg** [comment]
Can we get a sample project? :smiley:

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by DualMatrix** [comment]
Tested in both 2.15 and 3.1alpha, worked in both.

**Comment by Chaosus** [comment]
Thanks !
