### ISSUE TITLE
Can't use calculated constant as array size in shader

### ISSUE THREAD

**Issue by winston-yallow** [godotengine/godot#72087]
### Godot version

v4.0.beta15.official [4fa6edc88]

### System information

Windows 10 (10.0.19045 Build 19045) | Forward+ | Vulkan API 1.3.206 | AMD Radeon RX 6800 XT

### Issue description

Using a calculation in a constant (like `1 + 2`) will prevent that constant from being used as an array size. The error is `Expected a positive integer constant.` despite the constant being positive.

### Steps to reproduce

Create a text shader and add the following code:
```glsl
shader_type canvas_item;

const int SIZE = 1 + 2;
uniform int array[SIZE];
```

### Minimal reproduction project

N/A

**Comment by RicardRC** [comment]
I used to have a
```
const float nu= 0.739513;
const float normalizer = 1.0 / sqrt(1.0 + nu*nu);
```
And now it tells me that `E 0:00:01:0241   Expected constant expression.
  <C++ Source>   :46
`

**Comment by asujela** [comment]
If no one has tried to tackle this issue, I would like to see if I can do this.

**Comment by winston-yallow** [comment]
@asujela since there are no linked PRs, it's likely that no one is working on this. You can also ask on rocket chat: https://chat.godotengine.org/

It has a few channels, including one for new contributors in case you have any additional questions :sparkles:

**Comment by jsjtxietian** [comment]
The shader parser will parse it as a ConstantNode expression, but the const lookup didn't calculate the expression. Looks that we have to do some constant propagation.
