### ISSUE TITLE
F1 (Search help) in script editor freezes godot

### ISSUE THREAD

**Issue by bend-n** [godotengine/godot#72089]
### Godot version

a3a42159e

### System information

ArchLinux x11

### Issue description

f1 in script editor freezes
expect no freeze

### Steps to reproduce

- open script editor
- <kbd>fn</kbd>+<kbd>1</kbd>

### Minimal reproduction project

‮

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/72012 (fixed in the latest `master` branch).
