### ISSUE TITLE
InputEvents associated with actions in InputMap do not have actions property/getter

### ISSUE THREAD

**Issue by RKelln** [godotengine/godot#72093]
### Godot version

4.0dev beta 14

### System information

N/A (Ubuntu 22.04)

### Issue description

When writing UI code the pattern often looks quite a bit like this:

```gdscript
if event.is_action_pressed("action1"):
   do_thing()
elif event.is_action_pressed("action2"):
   do_thing2()
```
It would be nice to be able to use the `match` syntax, but there is no good way to get the associated action of an event. Something like this would be nice:
```gdscript
if event.is_action_type():
   match event.get_action():
      "action1":
         do_thing1()
      "action2":
         do_thing2()
```
`match` allows for cleaner code and once pattern guards are in place could be a nice syntax for complex input.

There is `event.action` for `InputEventAction` but all `InputEvents` associated with an action should have that property.

There also exists `InputEvent.is_action(action: StringName, exact_match: bool = false) ` but given an event you generally want to find out which action it represents.

Beyond the use with match, this feels like a general problem that InputEvents that are associated with an action cannot be queried for that action.

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by RKelln** [comment]
Thanks @dalexeev, the multiple action issue definitely makes this tricky. I would say then that the problem is lack of access to the associated actions, as you suggest something like `InputEvent.triggered_actions`.

I have a use case (VJ-like software) where there are 10+ actions (from keyboard and midi), essentially anything that has instrument-like qualities may have a large number of actions. Getting an array of actions would be quite helpful in that case, even if it had to be manually filtered (i.e. naming all the actions `instrument_*`) that applied to the node that cared about them. 

Will add feedback to existing proposals, thanks.

**Comment by YuriSizov** [comment]
As mentioned above, this should be a proposal.
