### ISSUE TITLE
SeparationRayShape3D buggy or behave erratically

### ISSUE THREAD

**Issue by takhimi** [godotengine/godot#72090]
### Godot version

Godot 4 Beta 15 and Beta14

### System information

Windows 11, RTX3070, Vulkan

### Issue description

Hi. I notices that snap feature or SeparationRayShape3D is broken since Beta 14. FYI Beta 13 is working just fine. 
Since beta 14 , the character will slowly pushed into the ground and bounces back up and continuously will do so. Beta 13 does not have this behavior.

### Steps to reproduce

1)Create empty scene
2)Create ground (StaticBody3D with collision)
3)Create player(CharacterBody3D, with two CollisionShape3Ds . (1- CollisionShape3D with capsule collision, 2-CollisionShape3D with SeparationRayShape3D below collision no1 and pointing to the ground or pointing below the character)
4) Add the template script to the player (the characterbody3d)
5)Add camera3d ortho view for better seeing the problem
6)Run

### Minimal reproduction project

[TestSnapBug.zip](https://github.com/godotengine/godot/files/10505186/TestSnapBug.zip)

**Comment by Calinou** [comment]
cc @rburing
