### ISSUE TITLE
Code editor: crash when trying to auto-complete code with mouse click then Enter/Tab

### ISSUE THREAD

**Issue by hsandt** [godotengine/godot#72114]
### Godot version

v4.0.beta.custom_build [9de0c73e4]

### System information

Linux Ubuntu 20.04 with Unity desktop

### Issue description

The editor craches when you try to auto-complete a string by clicking on the auto-complete popup, then press Enter/Tab.

More exactly, clicking on the auto-complete popup will not apply auto-completion as expected, but extend the selection to the next line (you may need to hold the mouse a bit). You can repeat this a certain number of times (undetermined) until the popup closes. If however, the popup is still open at this point (you may need to hold the last click) and you press Enter/Tab to fill with the selected autocompletion, the editor may crash.

Debugging shows that we are in fact trying to access the original line selection with a bad index, due to index being incorrectly offset when the selection is extended.

**Crash location**

```cpp
	_FORCE_INLINE_ const T &get(int p_index) const {
		CRASH_BAD_INDEX(p_index, size());  // HERE

		return _ptr[p_index];
	}
```

Crash log output

> ERROR: Index p_to_column = 22 is out of bounds (text[p_to_line].length() + 1 = 18).
   at: _base_get_text (scene/gui/text_edit.cpp:7673)
ERROR: Index p_to_column = 22 is out of bounds (text[p_to_line].length() + 1 = 18).
   at: _base_remove_text (scene/gui/text_edit.cpp:7696)
ERROR: FATAL: Index p_index = 29 is out of bounds (size() = 18).
   at: get (./core/templates/cowdata.h:155)

**Crash callstack**

```
CowData<char32_t>::get(int) const (/home/leyn/Developer/Godot/godot-repo/core/templates/cowdata.h:155)
String::operator[](int) const (/home/leyn/Developer/Godot/godot-repo/core/string/ustring.h:224)
CodeEdit::confirm_code_completion(bool) (/home/leyn/Developer/Godot/godot-repo/scene/gui/code_edit.cpp:2033)
CodeEdit::gui_input(Ref<InputEvent> const&) (/home/leyn/Developer/Godot/godot-repo/scene/gui/code_edit.cpp:506)
Control::_call_gui_input(Ref<InputEvent> const&) (/home/leyn/Developer/Godot/godot-repo/scene/gui/control.cpp:1748)
Viewport::_gui_input_event(Ref<InputEvent>) (/home/leyn/Developer/Godot/godot-repo/scene/main/viewport.cpp:1987)
Viewport::push_input(Ref<InputEvent> const&, bool) (/home/leyn/Developer/Godot/godot-repo/scene/main/viewport.cpp:2781)
Window::_window_input(Ref<InputEvent> const&) (/home/leyn/Developer/Godot/godot-repo/scene/main/window.cpp:1347)
void call_with_variant_args_helper<Window, Ref<InputEvent> const&, 0ul>(Window*, void (Window::*)(Ref<InputEvent> const&), Variant const**, Callable::CallError&, IndexSequence<0ul>) (/home/leyn/Developer/Godot/godot-repo/core/variant/binder_common.h:293)
void call_with_variant_args<Window, Ref<InputEvent> const&>(Window*, void (Window::*)(Ref<InputEvent> const&), Variant const**, int, Callable::CallError&) (/home/leyn/Developer/Godot/godot-repo/core/variant/binder_common.h:407)
CallableCustomMethodPointer<Window, Ref<InputEvent> const&>::call(Variant const**, int, Variant&, Callable::CallError&) const (/home/leyn/Developer/Godot/godot-repo/core/object/callable_method_pointer.h:104)
Callable::callp(Variant const**, int, Variant&, Callable::CallError&) const (/home/leyn/Developer/Godot/godot-repo/core/variant/callable.cpp:50)
DisplayServerX11::_dispatch_input_event(Ref<InputEvent> const&) (/home/leyn/Developer/Godot/godot-repo/platform/linuxbsd/x11/display_server_x11.cpp:3478)
DisplayServerX11::_dispatch_input_events(Ref<InputEvent> const&) (/home/leyn/Developer/Godot/godot-repo/platform/linuxbsd/x11/display_server_x11.cpp:3449)
Input::_parse_input_event_impl(Ref<InputEvent> const&, bool) (/home/leyn/Developer/Godot/godot-repo/core/input/input.cpp:685)
Input::flush_buffered_events() (/home/leyn/Developer/Godot/godot-repo/core/input/input.cpp:909)
DisplayServerX11::process_events() (/home/leyn/Developer/Godot/godot-repo/platform/linuxbsd/x11/display_server_x11.cpp:4532)
OS_LinuxBSD::run() (/home/leyn/Developer/Godot/godot-repo/platform/linuxbsd/os_linuxbsd.cpp:874)
main (/home/leyn/Developer/Godot/godot-repo/platform/linuxbsd/godot_linuxbsd.cpp:73)
```

**Demo gif**

With simple click or minimal drag (doesn't always work):

![Godot v4 0 beta custom_build  9de0c73e4  - Code editor: crash when trying to auto-complete code with mouse click then Enter](https://user-images.githubusercontent.com/1067772/214831865-4b9c2176-8ee5-48e7-8875-6841ddfc43fa.gif)

With long drag, but make sure to press Enter/Tab while dragging:

![Godot v4 0 beta custom_build  9de0c73e4  - Code editor: crash when trying to auto-complete code with mouse click then Tab (holding variant)](https://user-images.githubusercontent.com/1067772/214834105-6050b024-404d-4b1c-a328-7f682cff552c.gif)

(when you see the code editor, it means Godot crashed, more exactly it hit the CRASH_BAD_INDEX breakpoint in debug, but if not debugging it would just close)

### Steps to reproduce

1. Start typing some method name
2. Ctrl+Space to show auto-complete popup
3. Click on the auto-complete suggestion => instead of applying auto-completion, the selection is extended to the line below. If the popup closes, drag the mouse a little to the left to make sure you extend selection to the next line. In this case, I recommend keeping dragging (mouse button held) to make sure the popup remains open.
4. Press Enter or Tab to apply the auto-completion (while popup is still open) => no auto-completion, the editor crashes instead

### Minimal reproduction project

N/A

**Comment by YuriSizov** [comment]
This is related to https://github.com/godotengine/godot/issues/63726.

The crash is new, and it happens because code completion doesn't expect a bunch of lines to disappear in the process (which is fair). This can be patched somewhat to avoid the crash, but it shouldn't happen in the first place, code completion should not remove any lines in the process, because you should not be able to do mouse selection in the process.

From my testing, the PR linked to the aforementioned issue, https://github.com/godotengine/godot/pull/63876, does address some of the conditions, but not all of them. I no longer get random selection while the cursor stays within the completion box. But I can still start dragging from inside of it and over to the code area, and reach the same state as reported before. And then pressing Enter like you suggest crashes again.
