### ISSUE TITLE
Godot throws "[...] hides a global script class" when deep copying a Resource with a "classname" script

### ISSUE THREAD

**Issue by henriquelalves** [godotengine/godot#72119]
### Godot version

4.0 (beta 14 and 15)

### System information

Pop_OS

### Issue description

When using `[...].duplicate(true)` on a Resource with a script with `classname TestResource`, Godot throws the following error:

`Parse Error: Class "TestResource" hides a global script class.`

I was expecting to get a new `TestResource` object with its SubResources copied as new objects.

### Steps to reproduce

Using `.duplicate(true)` on a Resource with a `classname` script should throw this error.

### Minimal reproduction project

[DuplicateBug.zip](https://github.com/godotengine/godot/files/10510043/DuplicateBug.zip)

**Comment by bitsawer** [comment]
Possibly related: https://github.com/godotengine/godot/issues/68666? Likely fixed by https://github.com/godotengine/godot/pull/71142.

**Comment by henriquelalves** [comment]
I can confirm the `DuplicateBug` reproduction project no more throws an error on master, so this issue may be closed!
