### ISSUE TITLE
Tool Scripts cause editor crash and project corruption

### ISSUE THREAD

**Issue by dannflor** [godotengine/godot#72123]
### Godot version

Godot 4.0.beta15.mono

### System information

macOS

### Issue description

When I modify a script to make it a [Tool] script that sets its sprite frame when an exported field is updated, I can't use this object without godot crashing. If I have multiple instances, it becomes impossible to open until I delete `.godot`.

### Steps to reproduce

Create a Node2D with a reference to its child node Sprite2D. Attach a sprite sheet with animation frames. Attach a script to the parent Node2D. Export two fields: `FrameX` and `FrameY`. Use their setter method to update the sprite's frame number. Everything should be working fine. Now add `[Tool]` to the top of the script so the sprite's frame number is updated live in the editor. Crashes and headaches follow.

### Minimal reproduction project

[ToolCrashMinimal.zip](https://github.com/godotengine/godot/files/10510955/ToolCrashMinimal.zip)

**Comment by dannflor** [comment]
This is still occurring on 4.0 stable

**Comment by Calinou** [comment]
Can you reproduce this with GDScript?

**Comment by dannflor** [comment]
No I can't. However in GDScript it doesn't work at all unless I put the tool script on the Sprite node itself. I can't use it to modify the frame of children (I suspect because of some way with how `onready` works.) I'm going to see if putting the tool on the sprite node in c# is a workaround

**Comment by dannflor** [comment]
Ok if I put the tool script on a Sprite2D node I get *slightly* different behavior. I can't launch the project without crashing until I delete `.godot/mono`. After I do, I can drag the PackedScenes into another scene. After I build the project and generate a new `mono`, the exports show up in the sidebar, I can modify them and the changes are reflected in the editor. However, the moment I try to drag a new packedScene with the tool script in, the moment it crosses the threshold into the editor viewport the project crashes and won't reboot until I delete mono.

**Comment by silenuz** [comment]
It looks like you simply forgot to refrence the node you wanted to change, as well as trying to change the values on the property changed.  Along with having the property values on changed fire while in the editor.   Below is modified original code that should work.
```
[Tool]
public partial class ToolSprite : Node2D
{
	
	public Sprite2D sprite;
	[Export]
	public int FrameX {
		get => frameX;
		set {
			frameX = value;
			if (!Engine.IsEditorHint())
			{
				sprite.Frame = frameX + frameY * 16;
			}
		}
	}
	private int frameX;

	[Export]
	public int FrameY {
		get => frameY;
		set {
			frameY = value;
			if (!Engine.IsEditorHint())
			{
				sprite.Frame = frameX + frameY * 16;
			}
		}
	}
	private int frameY;
	// Called when the node enters the scene tree for the first time.
	public override void _Ready()
	{
		sprite = (Sprite2D) GetNode("Sprite2D");
		
		if (!Engine.IsEditorHint())
		{
			sprite.Frame = frameX + frameY * 16;
		}
	}

	// Called every frame. 'delta' is the elapsed time since the previous frame.
	public override void _Process(double delta)
	{
		if (Engine.IsEditorHint())
		{
			sprite.Frame = frameX + frameY * 16;
		}
	}
}
```

**Comment by dannflor** [comment]
@silenuz Sometimes my project exports don’t export with the node’s correctly set. I’m confident that’s not the problem though because I was able to get a crash without using child nodes at all. Put the Tool script on a Sprite2D, export an int called `MyFrame` and have the getter and setter change the `Frame` property of the sprite. The tricky thing with these tool scripts is they work just fine in the scene that has the script on the root, the crash happens when you drag it into another scene. For some reason I’m having a hard time getting the minimal reproduction crashing now but I definitely was in the past and it’s still crashing in my bigger project if I use Tool + exported + getter/setter

**Comment by silenuz** [comment]
I just added a screenshot and the original project with the updated code.  Hopefully that will get you started.

There was no need for the exported Sprite2D, if you were trying to set the value on the child Sprite2D node, what you do is get a reference to the node, and then when the frames change you set the frame on the child node.

One thing to remember is that the Editor engine and the game engine are two different assemblies, and when you can change values varies between the two.
