### ISSUE TITLE
AnimationTree doesn't work right anymore godot 4 beta 14,15

### ISSUE THREAD

**Issue by VP-GAMES** [godotengine/godot#72122]
### Godot version

4.0 beta 14,15

### System information

Ubuntu 22.04 1 LTS

### Issue description

After update from godot4 beta 13 to beta 14 AnimationTree doesn't work right anymore.
`_animation_tree.set["parameters/move_state/current"] = 1 #<= NOT WORKING`
ERROR:  Invalid set index 'parameters/move_state/current' (on base: 'Callable') with value of type 'int'

Change code to: 
`_animation_tree.set("parameters/move_state/current", 1) #<= IT WORKS BUT NOT RIGHT`

Control of AnimationTree is corrupt. See appended project.

### Steps to reproduce

Please download and start "Minimal reproduction project"

### Minimal reproduction project

[game_character_test.zip](https://github.com/godotengine/godot/files/10510721/game_character_test.zip)

**Comment by TokageItLab** [comment]
It's not a bug. The parameter control has changed a lot, but unfortunately the documentation has not been updated, sorry. See also https://github.com/godotengine/godot/pull/71418.

**Comment by VP-GAMES** [comment]
Thank you, for your comment. Works perfect!

**Comment by metanoia83** [comment]
I tried the minimal reproduction project above and already updated the code to the latest implementation. 
I think the reset is only working in the editor but not on runtime. It doesn't reset the animation on runtime, instead, it is stuck at the last frame. But if you turn off the reset on the AnimationNodeTransition, then the animation works on runtime. 
Not sure if this is how it is supposed to behave.
![Screenshot 2023-01-28 163157](https://user-images.githubusercontent.com/39092464/215297488-9279d74b-5f72-4566-ae5a-9cbae568cfa7.png)

You can test the attached sample project.
[game_character_test (new).zip](https://github.com/godotengine/godot/files/10528671/game_character_test.new.zip)

**Comment by TokageItLab** [comment]
@metanoia83 The request should not be spammed. So it should be:
```gdscript
if _animation_tree.get("parameters/move_state/current_state") != "jump":
	_animation_tree.set("parameters/move_state/transition_request", "jump")
```

**Comment by metanoia83** [comment]
> @metanoia83 The request should not be spammed. So it should be:
> 
> ```gdscript
> if _animation_tree.get("parameters/move_state/current_state") != "jump":
> 	_animation_tree.set("parameters/move_state/transition_request", "jump")
> ```

Do you mean like this?
![image](https://user-images.githubusercontent.com/39092464/215300028-2fd30efa-1159-4790-ab34-b64571a2b79e.png)

Below is the output for the code above.

https://user-images.githubusercontent.com/39092464/215300117-e1d938e5-a5ac-437f-ae6f-aa2b3aa4ef8c.mp4

**Comment by TokageItLab** [comment]
```gdscript
func handle(is_on_floor: bool, _motion: Vector2) -> void:
	if not is_on_floor:
		if _animation_tree.get("parameters/move_state/current_state") != "jump":
			_animation_tree.set("parameters/move_state/transition_request", "jump")
	else:
		if _animation_tree.get("parameters/move_state/current_state") != "move":
			_animation_tree.set("parameters/move_state/transition_request", "move")
	# Blend position for walk speed based on motion.
	_animation_tree.set("parameters/move/blend_position", _motion.length())
```
https://user-images.githubusercontent.com/61938263/215300871-73ba1c9b-8b51-419f-9f7d-cd02be5c5a7a.mp4

**Comment by metanoia83** [comment]
@TokageItLab Thanks for the help.
