### ISSUE TITLE
Not allways correct return variable in doc when return variable is set as variant

### ISSUE THREAD

**Issue by puppetmaster-** [godotengine/godot#7212]
I saw there are not correct return variable (void) in the doc.

**Example: get metadata**
![image](https://cloud.githubusercontent.com/assets/10463138/20796222/7b2ba156-b7d5-11e6-8e81-baf33ceff11b.png)
[https://github.com/godotengine/godot-docs/search?utf8=%E2%9C%93&q=get_item_metadata](https://github.com/godotengine/godot-docs/search?utf8=%E2%9C%93&q=get_item_metadata)

**Example: optionButton**
[Variant OptionButton::get_item_metadata(int p_idx) const ....](https://github.com/godotengine/godot/blob/c05ff0577fd9cc39a6968e65743f7d7da711bfe2/scene/gui/option_button.cpp#L152)

but in **doc_dump.cpp** is [missing OptionButton Variant](https://github.com/godotengine/godot/blob/c05ff0577fd9cc39a6968e65743f7d7da711bfe2/tools/doc/doc_dump.cpp#L157).

I don't know if there are more missing or not correct set variant classes.

**Comment by ducdetronquito** [comment]
Hi @bojidar-bg !

I made a PR to solve this issue, but as said in my PR comment I might have missed some missing return values...

I was wondering if it could be useful to develop a script to list methods that:
- have no description
- have incorrect/missing arguments
- have incorrect/missing return value
- does not exists in the documentation

Do you it worth putting time in this ? If it is, I can try something :)

**Comment by akien-mga** [comment]
You mean like https://github.com/godotengine/godot/blob/master/doc/tools/doc_status.py ? :)

**Comment by ducdetronquito** [comment]
Exactly :D

Well, cool to see that this script already exists !

**Comment by bojidar-bg** [comment]
Close?
