### ISSUE TITLE
TextureRect's "Tile" Stretch mode does not work with an AtlasTexture

### ISSUE THREAD

**Issue by KittyMcTophat** [godotengine/godot#72132]
### Godot version

4.0.beta15

### System information

Windows 10, RTX 3050 Ti Laptop GPU, Game Ready Driver version 527.56, Using Vulkan Renderer

### Issue description

When setting up a TextureRect with an AtlasTexture for the texture, the tile stretch mode behaves like the scale stretch mode

I've attached a picture that shows the bug (Both are configured the same way besides the texture)
![showing](https://user-images.githubusercontent.com/82963444/214918354-b5e8d882-455f-4f01-9729-658020c094c5.PNG)

### Steps to reproduce

Create a TextureRect

Set its texture to an AtlasTexture

Set the stretch mode to tile

### Minimal reproduction project

[Minimal Reproduction.zip](https://github.com/godotengine/godot/files/10512300/Minimal.Reproduction.zip)

**Comment by Procymbopteryx** [comment]
Godot Docs State:
"AtlasTexture ... may not tile properly in nodes such as TextureRect"
[https://docs.godotengine.org/en/latest/classes/class_atlastexture.html](url)

**Comment by KoBeWi** [comment]
Duplicate of #20472

**Comment by hunterloftis** [comment]
Is this truly "not planned?" It seems like a pretty clear bug.

If "tile" mode is known to be incompatible with AtlasTexture textures, *and* that isn't considered a bug / something to be fixed, then at the very least the UI should prevent you from selecting that combination that's known to not work.

**Comment by KoBeWi** [comment]
> Is this truly "not planned?"

No, it's just GitHub's weird way of calling invalid issues. It was closed as duplicate.
