### ISSUE TITLE
Drawing a Polygon or Curve results in duplicate vertices

### ISSUE THREAD

**Issue by snw-0** [godotengine/godot#72133]
### Godot version

v4.0.beta15.official [4fa6edc88]

### System information

Windows 11

### Issue description

When drawing a polygon in the editor, several duplicate vertices are added to the polygon array for each click.  In the image below, I clicked three times to draw the triangle, but got 10 entries.  The number you get varies, though I don't know why; I've seen hundreds of points from drawing a hexagon.  I tested it with a Polygon2D, a CollisionPolygon2D, and a CollisionPolygon3D; the issues occurs with all of them.  It later occurred to me that this might happen with a Curve2D as well, and it does.

![image](https://user-images.githubusercontent.com/2808851/214926182-b8609b87-85a1-4a08-8017-be4eeec912c6.png)

### Steps to reproduce

Add a node that has a Polygon or Curve resource, such as a Polygon2D, draw some points, then check the PackedVector2Array resource.

### Minimal reproduction project

N/A

**Comment by bitsawer** [comment]
Can confirm. It looks like the editors are sometimes getting more input events than they should, like they accumulate somewhere and suddenly one mouse left clicks sends up to similar 4 click events. For example, putting this code snipped in Polygon3DEditor::forward_3d_gui_input() shows input spam when adding points to CollisionPolygon3D. You can try editing, then removing all points and repeating and the input issue should soon become clear.

```
@@ -126,6 +126,11 @@ EditorPlugin::AfterGUIInput Polygon3DEditor::forward_3d_gui_input(Camera3D *p_ca
 	Ref<InputEventMouseButton> mb = p_event;
 
 	if (mb.is_valid()) {
+
+		if (mb->get_button_index() == MouseButton::LEFT) {
+			print_line("PRESS " + p_event->as_text() + " " + String::num_int64(mb->is_pressed()));
+		}
+
 		Vector2 gpoint = mb->get_position();
 		Vector3 ray_from = p_camera->project_ray_origin(gpoint);
 		Vector3 ray_dir = p_camera->project_ray_normal(gpoint);
```

This patch (adding `return true`) seems to "fix" the 2D editing, but I think the fundamental problem is the input event spam.

```
@@ -323,6 +324,7 @@ bool AbstractPolygon2DEditor::forward_gui_input(const Ref<InputEvent> &p_event)
 							return true;
 						} else {
 							selected_point = Vertex();
+							return true;
 						}
 					}
 				} else {
```

**Comment by clayjohn** [comment]
Cc @godotengine/input

**Comment by smix8** [comment]
While the duplicated Input spam makes it now obvious there is also the issue that the abstract polygon draw tools in general allow these kinds of duplicates / invalid arrays to be created. While the visual rendering does not mind and physics collision runs at very degraded performance the navigation polygons actuall bugs out with duplicated vertices like seen here https://github.com/godotengine/godot/issues/66283.

**Comment by akien-mga** [comment]
CC @Sauermann

**Comment by Sauermann** [comment]
Bisecting this was a bit complicated.
Last time it worked, was in c3539b4561f9b4d7dc4ba1c5859217e7fbf9c6fe

Creating Entries of the Polygon got broken in bda87300e8d846987c1a6c4216c201c5ce16b8fe #71770 (Node gets deselected when clicking in the Scene-Viewport)
This behavior persists and stays the same until 9937915ad77059b63582ffd4e324afb26f467b76.

That bug got fixed and works again since 9ae7a2554cb90418af517c91e0b7f8e8d5d4fe4a #71912 with the problem mentioned in this issue-report.

**Comment by clayjohn** [comment]
CC @KoBeWi

**Comment by Sauermann** [comment]
In `EditorPluginList::forward_gui_input` each event is forwarded twice to `AbstractPolygon2DEditor::forward_gui_input`.
So it looks like `AbstractPolygon2DEditor` got added twice to `EditorPluginList.plugins_list`.
