### ISSUE TITLE
[Regression] Double quote marks don't work on US international keyboard, Windows

### ISSUE THREAD

**Issue by robbertzzz** [godotengine/godot#72142]
### Godot version

4.0 beta 15

### System information

Windows 11

### Issue description

Double quote marks (") don't work on US international keyboard layout in the latest beta. They worked fine in beta 14 and I've confirmed that it's limited to Godot. On US international the double quotation mark is typed by typing shift + [ ' ] (single quote, next to enter key) followed by a space bar. Other key combinations that rely on double quotes (like ä, ë, ö, typed by shift + [ ' ] followed by the letter) are also broken and instead show the single quote version (á, é, ó).

### Steps to reproduce

- Open a project in Godot 4.0 beta 15 on Windows (I'm on 11)
- Change the keyboard layout to US international
- Type a double quotation mark (shift + [ ' ] followed by space bar, single quotation is usually in between ; and enter keys)
- Observe instead of a double quotation mark, a single one is inserted
- Alternatively, try typing a vowel with umlaut: ö, ä, ü, ï, ë, ÿ, which are typed as shift + [ ' ] followed by a vowel. Observe that vowels end up with an accent: ó, á, ú, í, é, ý.

### Minimal reproduction project

N/A

**Comment by robbertzzz** [comment]
I forgot to mention, if I change to UK layout (where no space bar is needed) everything works as it should.

**Comment by Werninator** [comment]
Can confirm that behavior on my machine as well (win11 beta15). thanks for fixing

**Comment by akien-mga** [comment]
Should be fixed in 4.0 beta 16: https://godotengine.org/article/dev-snapshot-godot-4-0-beta-16/
