### ISSUE TITLE
GODOT 2.1.1 don't work with Mac OS X 10.10.5

### ISSUE THREAD

**Issue by Lebostein** [godotengine/godot#7214]
**Operating system or device - Godot version:**
Mac OS X 10.10.5

**Issue description** (what happened, and what was expected):
App shows error: App needs Mac OS 10.11 or newer
Godot 2.1 runs with 10.10.
If Godot 2.1 runs with Mac OS 10.10, Godot 2.1.1. should run too.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by volzhs** [comment]
I guess it's fixed with #7181

**Comment by bojidar-bg** [comment]
Can someone confirm this was fixed in 2.1.2/2.1.3? If not, can we cherrypick the commit?

**Comment by volzhs** [comment]
2.1 branch already has it ef009a8

**Comment by akien-mga** [comment]
Indeed, fixed.
