### ISSUE TITLE
Regression in editor theme for popup menus

### ISSUE THREAD

**Issue by clayjohn** [godotengine/godot#72145]
### Godot version

Beta15 and 63b5adf8a85f6f2f222d048bd4975490b6afd9a8

### System information

PopOS 22.04 

### Issue description

The theme for popup elements broke again

_Beta 14_
![Screenshot from 2023-01-26 14-48-56](https://user-images.githubusercontent.com/16521339/214968350-0f9dc31c-f30b-4376-982c-1e60effd703c.png)

_Beta 15 and 63b5adf8a85f6f2f222d048bd4975490b6afd9a8_
![Screenshot from 2023-01-26 14-47-55](https://user-images.githubusercontent.com/16521339/214968353-ade4556b-9e1b-41e4-b5de-3045db7acc7b.png)

Happens on import and when saving the project

### Steps to reproduce

Launch the editor and import any resource or save any scene

### Minimal reproduction project

N/A

**Comment by bend-n** [comment]
Is the tall progress bar a problem? I kind of like it.

**Comment by clayjohn** [comment]
> Is the tall progress bar a problem? I kind of like it.

I guess it is personal preference. I prefer the thinner bar, but I'm fine with the wider bar if that's what others prefer

**Comment by clayjohn** [comment]
I wonder if this is a result of the style box changes in https://github.com/godotengine/godot/pull/72124

CC @YuriSizov

**Comment by YuriSizov** [comment]
Yes, sorry, I forgot to mention it, but the progress bar is now slightly larger in the editor. It should be fixable with some margin adjustments, it's just so slow to rebuild every time on my laptop to test and tweak, I thought it'd be okay for now.

**Comment by YuriSizov** [comment]
> edit: or maybe not looks like #72124 would have been merged after beta 15

It's likely related to one of my stylebox changes, including one from the last beta. The fix is still in the margins, if anyone wants to play around with them.

**Comment by winston-yallow** [comment]
This isn't a bug, it's a feature!

More seriously though, I think the taller progress bar has some advantages:
- looks cleaner due to the spacing (doesn't feel so crowded)
- text readability is increased
- easier to spot the progress (especially on my small notebook screen in sunlight it was always a hassle)

I personally am in favor of having these tall progress bars in the editor.

**Comment by YuriSizov** [comment]
Based on my entirely unscientific research on Twitter and Mastodon, thick progress bars seem to be loved overwhelmingly. 👀

**Comment by clayjohn** [comment]
> Based on my entirely unscientific research on Twitter and Mastodon, thick progress bars seem to be loved overwhelmingly. eyes
> 
> https://twitter.com/YuriSizov/status/1619100461935783936
> 
> https://mastodon.gamedev.place/@yurisizov/109763544579475128

Haha the change seems pretty universally liked. So no point in "fixing" it
