### ISSUE TITLE
Sliders textures are squeezed

### ISSUE THREAD

**Issue by boruok** [godotengine/godot#72147]
### Godot version

v4.0.beta.custom_build [d1e5903c6]

### System information

Ubuntu 22.10, GTX1060, Vulkan

### Issue description

Sliders no longer can draw correct texture, who squeezed them? )

Godot_v4.0-beta14_linux.x86_64
![Screenshot from 2023-01-27 09-30-36](https://user-images.githubusercontent.com/36783322/214980875-0afc048b-2fb6-4463-8003-7efaa19b8912.png)
v4.0.beta.custom_build [d1e5903c6]
![Screenshot from 2023-01-27 12-49-37](https://user-images.githubusercontent.com/36783322/215005864-f2574ee8-2bc1-4bff-b144-2d7207d302a2.png)

### Steps to reproduce

1. run attachment
2. assign StyleBoxTexture to Slider
3. change margins

### Minimal reproduction project

[New Game Project.zip](https://github.com/godotengine/godot/files/10515308/New.Game.Project.zip)

**Comment by boruok** [comment]
strange, if you tune `Content Margins` to 4,4,4,4 (texture size 8x8px) it draws correctly.

**Comment by clayjohn** [comment]
Likely caused by https://github.com/godotengine/godot/pull/72124 which says existing scenes my need to be changed

**Comment by YuriSizov** [comment]
Yes, please use margins to ensure a minimum size of your styleboxes from now on. StyleBoxTexture used to ignore margins and used the texture size instead, which limited what you could do with it. Now you can properly control the size and the offsets with margins, just like any other stylebox.
