### ISSUE TITLE
 GPUParticle size causes crash

### ISSUE THREAD

**Issue by westmentodog** [godotengine/godot#72150]
### Godot version

beta4 v4.0

### System information

Win 11, Intel Graphics

### Issue description

new 3d gpu particle node, set to quad then set it's yscale to 0.1m causes program to close.

### Steps to reproduce

new 3d gpu particle node, set to quad then set it's yscale to 0.1m causes program to close.

### Minimal reproduction project

-

**Comment by clayjohn** [comment]
Duplicate of https://github.com/godotengine/godot/issues/69454

Fixed by https://github.com/godotengine/godot/pull/72064
