### ISSUE TITLE
`@export_group` does nothing

### ISSUE THREAD

**Issue by bend-n** [godotengine/godot#72151]
### Godot version

3b086aa06

### System information

ArchLinux x11

### Issue description

```gdscript
extends Node

@export_group("My Properties")
@export var number = 3
@export var string = ""

@export_group("Prefixed Properties", "prefix_")
@export var prefix_number = 3
@export var prefix_string = ""

@export_group("", "")
@export var ungrouped_number = 3
```

![image](https://user-images.githubusercontent.com/70787919/214983963-528c415b-745b-47fc-9777-36ebe31a3060.png)

### Steps to reproduce

- create script
- @export_group
- go inspector

### Minimal reproduction project

‮

**Comment by bend-n** [comment]
I might just be misunderstanding what @export_group does though.

**Comment by dalexeev** [comment]
This is probably a regression after #71634. I'll see.
