### ISSUE TITLE
Move cards from Trello to GitHub projects?

### ISSUE THREAD

**Issue by toby3d** [godotengine/godot#7216]
[Why not?](/godotengine/godot/projects) ¯\\\_(ツ)_/¯

**Comment by bojidar-bg** [comment]
Sounds good, though I'm not sure how much those cards are actually valid nowdays...

**Comment by toby3d** [comment]
Any news? Only today I just found out that there is a special text document listing the features planned in the full version 3.0. A very inconvenient way.

**Comment by toger5** [comment]
Really great proposal.

 - the cards are there it cost nothing to use them.
 - it will be much much easier to find for ppl who don't know about the other docs + roadmap files.
 - Nothing supports better integration with issues.
 - things like trakers can be listed...
 - in general it is a great way to structure issues. (label are also good but don't provide the same amount of flexibility and overview)
 - It is always better to have one central place for the whole project than spreading it all over the place. less redudant information.
 - I really like the github website. so having to leave it less often is great (really week point ;) but still)

**Comment by Noshyaar** [comment]
@reduz @akien-mga Any interests?

**Comment by akien-mga** [comment]
Not for now, maybe later, but we don't need an issue as a reminder :)
