### ISSUE TITLE
Editor load times increased a lot with beta 15

### ISSUE THREAD

**Issue by elenakrittik** [godotengine/godot#72185]
### Godot version

Godot 4 beta 15 (**UPD**: the issue persists on beta 16 too)

### System information

Linux 5.15.89-1 x86_64 (Manjaro XFCE)

### Issue description

When opening a godot project, the window name is changed every frame-two and shows a scene name in it, which indicates that godot for some reason reopens every scene present in the current tabs, then every instanced scene (if any). First time i tried opening project (just after the system booted) it freezed and didn't load (i Ctrl-C'ed it after a minute of *nothing*), second time thing described above happened. Before beta 15 everything worked fine and godot loaded just the current scene in ~15 seconds, but now it takes a lot more, even though my project is not even small, it's *tiny* (less than 400 lines of code including website template). My best guess for this issue is #57606 

https://user-images.githubusercontent.com/77104725/215151296-5cf11a7e-9791-4731-9d58-6915949a1dfd.mp4

![UTDGpjct](https://user-images.githubusercontent.com/77104725/215151331-ae58d13b-ffe0-4f31-9b97-b9fd564a9114.svg)

### Steps to reproduce

Create a new project, add a few basic scenes like Player, Level etc., keep the scene tabs open, and reopen the project.

### Minimal reproduction project

[Beta15Lags.zip](https://github.com/godotengine/godot/files/10521525/Beta15Lags.zip)

**Comment by MackyK** [comment]
I noticed performance issues with beta 14 as well.

**Comment by Calinou** [comment]
> I noticed performance issues with beta 14, 15 and 16 as well on Windows 10 22H2

This is an unrelated issue, as you can also reproduce it in betas prior to https://github.com/godotengine/godot/pull/57606's merge.

**Comment by akien-mga** [comment]
@elenakrittik Can you still reproduce this issue in 4.0.3-stable and 4.1-beta3?

I tested on Mageia 9 (Linux) on KDE / X11 and I can't reproduce the issue with the MRP, 4.0-beta14, beta15 and beta16 all open the project in ~6 s for me.

**Comment by elenakrittik** [comment]
No

> @elenakrittik Can you still reproduce this issue in 4.0.3-stable and 4.1-beta3?
> 
> I tested on Mageia 9 (Linux) on KDE / X11 and I can't reproduce the issue with the MRP, 4.0-beta14, beta15 and beta16 all open the project in ~6 s for me.

No, not anymore, 4.0.3 behaves as expected. Also i no longer use Manjaro, but EndeavourOS instead (linux 6.3.7-arch1-1 x86_64, Gnome/X11), *maybe* it affected the result.
