### ISSUE TITLE
OpenGL: Editor right panel tabs disappear when loading a tileset with an atlas with dimensions greather than 799x799

### ISSUE THREAD

**Issue by Gnumaru** [godotengine/godot#72181]
### Godot version

4.0.beta15

### System information

windows 10, nvidia graphics, opengl backend

### Issue description

When using a TileSetAtlasSource on a TileSet with dimensions greater than 799x799 and selecting the Tiles tab in the TileSet editor, all tabs in the right editor panel disappear.

This is likely a regression of https://github.com/godotengine/godot/issues/67942

### Steps to reproduce

see attached video:

https://user-images.githubusercontent.com/5783414/215139823-f78e94c5-5199-452e-b601-76ec0f680748.mp4

### Minimal reproduction project

[LikelyRegressionOf67942.zip](https://github.com/godotengine/godot/files/10520933/LikelyRegressionOf67942.zip)

**Comment by clayjohn** [comment]
Looks like the bug was introduced between beta 12 and 13. Very likely a regression from https://github.com/godotengine/godot/pull/71335
