### ISSUE TITLE
Unexpected Error when using Navigation Mesh with Grid Map

### ISSUE THREAD

**Issue by wkirby** [godotengine/godot#72188]
### Godot version

v4.0.beta16.mono.official [518b9e580]

### System information

macOS Ventura 13.1, M1 Max

### Issue description

Attempting to integrate Navigation Mesh and Grid map results in the following error:

```
E 0:00:02:0329   sync: Attempted to merge a navigation mesh triangle edge with another already-merged edge. This happens when the current `cell_size` is different from the one used to generate the navigation mesh. This will cause navigation problems.
  <C++ Source>   modules/navigation/nav_map.cpp:691 @ sync()
```

This results in nav agents being unable to navigate the resulting nav region.

### Steps to reproduce

# Creating the Mesh Library

* Create a new scene
* Add a mesh instance with a cube mesh
* Using the mesh menu, create a Navigation Mesh
* Export scene as a mesh library

# Using the Mesh Library

* Create a new scene
* Add a grid map
* Select the mesh library from the previous steps
* Set the cell size to 1x1x1 (this is so that the meshes touch each other when added to the grid map)
* Add two or more consecutive meshes
* Ensure `bake_navigation` is set to `true`
* Run the current scene
* Observe the error above

### Minimal reproduction project

[Navigation Test.zip](https://github.com/godotengine/godot/files/10521754/Navigation.Test.zip)

**Comment by wkirby** [comment]
For added context, I _may_ be misunderstanding the expected interactions between the 3D navigation system and grid maps. My _desired_ functionality is to make _some_ meshes in my gridmap navigable, and _some_ non-navigable. My understanding from the existing documentation is that if I add a nav mesh to _some_ mesh instances, and tick the `bake_navigation` setting in the Grid Map, that the Grid Map will produce a navigation region from the nav meshes.

Relevant documentation from `GridMap`:

> If true, this GridMap creates a navigation region for each cell that uses a mesh_library item with a navigation mesh. The created navigation region will use the navigation layers bitmask assigned to the MeshLibrary's item.

**Comment by wkirby** [comment]
Still happening on v4.0.beta17.mono.official [c40020513]

**Comment by smix8** [comment]
The reason why this does not work for you is cause you don't use a valid NavigationMesh.

![box_navmesh](https://user-images.githubusercontent.com/52464204/216622929-43fc5977-153f-4aff-bdf3-3d52006b70cc.jpg)

If you enable navigation debug in Editor->Debug->Visible Navigation you will see quickly what is wrong. Seems like you just copied over your visual mesh to the navigation mesh slot. This does not work as a navigation mesh can not have a volume, it needs to have flat surfaces.

What you can do is use a NavigatioRegion3D, add a NavigationMesh resource and set the agent_radius to zero, add a child MeshInstance3D and add you visual mesh inside. Then bake your NavigationMesh, store it on disk and load it in your MeshLibrary as the cell navigation mesh.
