### ISSUE TITLE
@export_node_path doesn't accept class name constants

### ISSUE THREAD

**Issue by stephannv** [godotengine/godot#72192]
### Godot version

v4.0.beta16.official.518b9e580

### System information

Vulkan API 1.2.231 - Apple M1 Max

### Issue description

I don't know if this is by design, but after upgrading to 4.0.beta16, `@export_node_path` with class name constant doesn't work, it requires a class name as string.
```gdscript
@export_node_path(Sprite2D) var main_sprite_node_path: NodePath
```
> Parse Error: Argument 1 of annotation "@export_node_path" isn't a constant expression

But if I do `@export_node_path("Sprite2D")` it works.

The [4.0 docs](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_exports.html#nodes) shows:
<img width="853" alt="Screen Shot 2023-01-27 at 15 13 20" src="https://user-images.githubusercontent.com/3025661/215165110-e4e80fbe-f2a9-41a3-a1ce-8d0a119dd548.png">

If this is a intended behavior, I can open a PR to Godot Docs to update the example. 

### Steps to reproduce

Download the project and open `main.gd` script

### Minimal reproduction project

[export_node_path.zip](https://github.com/godotengine/godot/files/10521948/export_node_path.zip)

**Comment by akien-mga** [comment]
Probably a regression from https://github.com/godotengine/godot/pull/71634.

**Comment by dalexeev** [comment]
The quotes are now required. See #71634.

**Comment by stephannv** [comment]
@dalexeev I will close this and submit a change to docs. Thanks.
