### ISSUE TITLE
GLTF Importer doesn't use the Project's Import settings when extracting its embedded textures.

### ISSUE THREAD

**Issue by prominentdetail** [godotengine/godot#72191]
### Godot version

v4.0.beta.custom_build [705273140]

### System information

windows 10

### Issue description

When importing a gltf file with embedded textures, godot will extract these textures, however it won't use the Project's Import settings, resulting in the textures looking compressed and messed up.
Also it creates a image file in the project- I don't remember it doing this before(it would just keep it embedded I think).

### Steps to reproduce

open project, check the included gltf file. See how it doesn't adhere to the project's import settings for texture2d. Instead it is all compressed and messed up.

### Minimal reproduction project

[gltf import bug.zip](https://github.com/godotengine/godot/files/10521850/gltf.import.bug.zip)

**Comment by lyuma** [comment]
Hey, so I understand the issue here is that the extracted `.png.import` files are using some hardcoded defaults rather than the project import defaults for imported `Texture2D`.

modules/gltf/gltf_document.cpp
```cpp
				Ref<ConfigFile> config;
				config.instantiate();
				if (FileAccess::exists(file_path + ".import")) {
					config->load(file_path + ".import");
				}
				config->set_value("remap", "importer", "texture");
				config->set_value("remap", "type", "Texture2D");
				if (!config->has_section_key("params", "compress/mode")) {
					config->set_value("remap", "compress/mode", 2); //user may want another compression, so leave it bes
				}
				if (!config->has_section_key("params", "mipmaps/generate")) {
					config->set_value("params", "mipmaps/generate", true);
				}
				Error err = OK;
				err = config->save(file_path + ".import");
```

In #72440, we will be adding an option to allow embedding textures losslessly, which could serve as a workaround, but this is still technically a bug.

**Comment by prominentdetail** [comment]
Understood- thanks for looking into it! :)
