### ISSUE TITLE
Cylinder gets stuck on seams of static body while sliding against it.

### ISSUE THREAD

**Issue by prominentdetail** [godotengine/godot#72198]
### Godot version

v4.0.beta.custom_build [705273140]

### System information

windows 10

### Issue description

Sliding a cylinder shape against a static body will cause it to get stuck against the seams in the mesh.
![stuck](https://user-images.githubusercontent.com/10412778/215172771-1cf7c08f-1d48-4446-a4c9-4fe5d319aefb.gif)

### Steps to reproduce

run project and move cylinder against the static body

### Minimal reproduction project

[moveSlideStuck_beta16.zip](https://github.com/godotengine/godot/files/10522271/moveSlideStuck_beta16.zip)

**Comment by hunterloftis** [comment]
I'm seeing similar behavior with capsules against the edges of a boxshaped rigidbody3d.

**Comment by hunterloftis** [comment]
Here's an example (sorry, this is intermittent for me so I captured it when I noticed the scene geometry triggering the issue, so there's not even visible collision shapes).

https://user-images.githubusercontent.com/364501/228639708-e00d27ab-eb44-4c5f-a963-5c15355c09b5.mp4

If the original minimal repro isn't sufficient, I'll try to repro this with a capsule & box.
