### ISSUE TITLE
MenuButton doesn't render as a button (invisible except for text)

### ISSUE THREAD

**Issue by TheSecondReal0** [godotengine/godot#72190]
### Godot version

4.0b15

### System information

Windows 10, RTX 2060, Vulkan

### Issue description

MenuButtons don't render at all like normal buttons, only text is displayed (no panels or other theme elements).

They look like this:
![image](https://user-images.githubusercontent.com/66881186/215162178-135e1427-aeed-4b57-9b7f-7ea7b234ade9.png)

When I would expect them to look more like this:
![image](https://user-images.githubusercontent.com/66881186/215162461-5eab78a6-0ed0-4a05-a5a1-b9bdd14a1214.png)

Maybe this is intended behavior, but it's not documented to work like this and it seems like it's meant to display like other buttons.

### Steps to reproduce

Add a MenuButton node to any scene

### Minimal reproduction project

N/A

**Comment by dalexeev** [comment]
I guess `MenuButton` is for menu/toolbar items. In this case, the button does not need a background.

**Comment by bruvzg** [comment]
Uncheck `flat` in the properties, it's set for `MenuButton` by default.

**Comment by TheSecondReal0** [comment]
Thanks, unchecking `flat` worked. Why is that the default when `MenuPopup` already exists for when you don't want a full button?

**Comment by TheSecondReal0** [comment]
Just realized this is a duplicate of #30768
