### ISSUE TITLE
GPUParticles3D. Wrapper class not found. 4.0.beta16 mono

### ISSUE THREAD

**Issue by barrrettt** [godotengine/godot#72203]
### Godot version

4.0 beta 16 mono

### System information

win11

### Issue description

 Wrapper class not found for type: GPUParticles3D

CONSOLE SAY:

E 0:00:01:0387   ScriptManagerBridge.cs:101 @ IntPtr Godot.Bridge.ScriptManagerBridge.CreateManagedForGodotObjectBinding(Godot.NativeInterop.godot_string_name* , IntPtr ): System.InvalidOperationException: Wrapper class not found for type: GPUParticles3D
  <C# Error>     System.InvalidOperationException
  <C# Source>    /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:101 @ IntPtr Godot.Bridge.ScriptManagerBridge.CreateManagedForGodotObjectBinding(Godot.NativeInterop.godot_string_name* , IntPtr )
  <Stack Trace>  ScriptManagerBridge.cs:101 @ IntPtr Godot.Bridge.ScriptManagerBridge.CreateManagedForGodotObjectBinding(Godot.NativeInterop.godot_string_name* , IntPtr )

### Steps to reproduce

Call this in C#
```
 private GpuParticles3D emitter1;
	
    public override void _Ready() {
        emitter1 = GetNode("emitter1") as GpuParticles3D;
}
```

### Minimal reproduction project

1 scene with: 

```
- Node3D
   - GpuParticles3D
```

Add c# script to rood node.
GetNode gpu particle

**Comment by MysteriousMilk** [comment]
Same issue for me, but with GPU Particles 2D. I know there were a lot of renames and breaking changes in this beta. What's interesting is that in the editor, the node type shows up as GPUParticles2D, but in code it is now GpuParticles2D. Not sure if that makes a difference. Usually, the node name and the class name are the same.

`
ScriptManagerBridge.cs:101 @ IntPtr Godot.Bridge.ScriptManagerBridge.CreateManagedForGodotObjectBinding(Godot.NativeInterop.godot_string_name* , IntPtr ): System.InvalidOperationException: Wrapper class not found for type: GPUParticles2D
  <C# Error>     System.InvalidOperationException
  <C# Source>    /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:101 @ IntPtr Godot.Bridge.ScriptManagerBridge.CreateManagedForGodotObjectBinding(Godot.NativeInterop.godot_string_name* , IntPtr )
  <Stack Trace>  ScriptManagerBridge.cs:101 @ IntPtr Godot.Bridge.ScriptManagerBridge.CreateManagedForGodotObjectBinding(Godot.NativeInterop.godot_string_name* , IntPtr )
`
