### ISSUE TITLE
Adding parameters to @rpc gives errors in Godot 4 beta 16.

### ISSUE THREAD

**Issue by CrankyCranton** [godotengine/godot#72218]
### Godot version

4.0.dev

### System information

Garuda Linux (rolling release)

### Issue description

When adding the tag @rpc to a function in the 16th beta, there are no errors (besides in the reproduction project, where every peer calls the rpc function send_mesage(), and with the default @rpc flags, only the multiplayer authority may call it), but when adding flags such as @rpc(call_remote, any_peer), it will give the following errors:

Identifier "call_remote" not declared in the current scope.
Argument 1 of annotation "@rpc" isn't a constant expression.

The errors don't pop up in the 15th beta as far as I know.

### Steps to reproduce

Go to main.gd, and the debuger should show the error before the script runs (in beta 16).

### Minimal reproduction project

[RPC Test.zip](https://github.com/godotengine/godot/files/10524173/RPC.Test.zip)

**Comment by orange4glace** [comment]
same here.

**Comment by daviirodrig** [comment]
Quotes are now required on the flags. See #71634
