### ISSUE TITLE
Rendering goes bad in script editor

### ISSUE THREAD

**Issue by voylin** [godotengine/godot#72224]
### Godot version

4.0.beta_16

### System information

Arch linux, i3 wm

### Issue description

As can be seen in the image, I don't know what exactly goes wrong, but it only happens in the script editor. It happens at irregular moments and the only solution is close and restart the editor. Not certain what triggers this.

![Screenshot from 2023-01-28 11-45-44](https://user-images.githubusercontent.com/56970759/215238183-bc445606-620e-431a-b4cf-9bbc8673533f.png)

Inside of a normal textfile (a csv file) it looks like this:

![Screenshot from 2023-01-28 11-49-18](https://user-images.githubusercontent.com/56970759/215238283-f6194c4e-8841-43e9-9bb2-414a1a4d3e84.png)

### Steps to reproduce

No idea, sometimes happens, sometimes doesn't.

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
This looks like it could be the same issue reported here https://github.com/godotengine/godot/issues/71951#issuecomment-1407227022 

Are you also using an Nvidia GPU?

**Comment by voylin** [comment]
> This looks like it could be the same issue reported here [#71951 (comment)](https://github.com/godotengine/godot/issues/71951#issuecomment-1407227022)
> 
> Are you also using an Nvidia GPU?

Also using an Nvidia GPU.  I guess this is probably related as I'm also using compatibility mode.

**Comment by voylin** [comment]
What I just noticed is, everything renders wrongly, except for the Japanese text.

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/68814, although that issue affects the entire editor, not just the script editor.

**Comment by clayjohn** [comment]
Could you test again in Beta 17? This may have been fixed

**Comment by voylin** [comment]
> Could you test again in Beta 17? This may have been fixed

I can not recreate it in 17, so probably fixed. I'll close this issue for now and re-open if it happens again, I'll be using beta 17 from now on anyway so it'll be quick to notice if this happens again. Thanks!
