### ISSUE TITLE
Lots of crashes

### ISSUE THREAD

**Issue by Palka606** [godotengine/godot#72229]
### Godot version

4.0 beta15

### System information

Android 10, OpenGL ES 3.2, Snapdragon 625, Adreno

### Issue description

I have reinstalled the latest beta several times, wanted to use beta15 but later when creating a project ( In any of the modes ) the editor just crashes. Now I can't use beta15. Beta16 doesn't work for me at all. What should I do?It turns out that I can only install a certain version once and that's it

### Steps to reproduce

1. Installed beta 15
2. Delete 15, install 16
3. Delete 16, install again 15
4. The editor began to fly out without even loading

### Minimal reproduction project

i got no

**Comment by auratheenby** [comment]
For me, beta15 is fine, but beta16 crashes when trying to open any of my previously existing projects. Creating a new one (in either version!) works fine, both on creation and on subsequent loads. I don't know if it counts as a minimal reproduction project, since it's actually not very minimal at all, but it does it with my [addon](https://gitlab.com/addons-by-aura/simple-state) if you want to test it.

**Comment by Calinou** [comment]
@auratheenby Which operating system are you using? Which rendering method are you using in the project (Forward+/Mobile/Compatibility)?

**Comment by auratheenby** [comment]
I am on Manjaro 22. In the projects for my addons, I use the compatibility renderer so I can make brower-playable demos, and in my games I use the forward++ one.

**Comment by auratheenby** [comment]
I just tried creating a new project in beta16 like before, then adding the addon from the aaset library. It crashed as soon as I pressed “Install”, then continued crashing like before. If I remove the addon files, it loads fine.

**Comment by auratheenby** [comment]
It’s actually letting me install any addon except my own, from what I can tell.

**Comment by Zireael07** [comment]
This suggests the issue is somewhere in your addon, can you share the addon here?

**Comment by auratheenby** [comment]
@Zireael07 it's mentioned in my first comment here:

> my [addon](https://gitlab.com/addons-by-aura/simple-state)

**Comment by auratheenby** [comment]
It's no longer crashing for me in the release candidate.

**Comment by YuriSizov** [comment]
Alright then. Let us know if it resurface.
