### ISSUE TITLE
Textures using Basis Universal compression no longer generate mipmaps

### ISSUE THREAD

**Issue by BraqueDown** [godotengine/godot#72237]
### Godot version

v4.0.beta.custom_build [a43db5afa]

### System information

Windows 10, Forward+, NVidia RTX 3070 (516.94)

### Issue description

After recompiling the engine, a grid texture using Basis Universal compression in a test project became extremely noisy, having lost its mipmaps.

Opening a Basis Universal texture in the inspector shows that there are no mips, even if Generate Mipmaps is enabled:
![image](https://user-images.githubusercontent.com/43602802/215256078-ed1a203b-5455-413c-bb31-559acee1b812.png)
![editor_screenshot_2023-01-28T184045](https://user-images.githubusercontent.com/43602802/215256370-9b1278cf-c8f3-4356-94ea-b98d509ad895.png)

### Steps to reproduce

1. Import a texture to a project (The noisier the better).
2. Open texture in the inspector, enable mipmaps, change the compression mode to Basis Universal, and re-import.

### Minimal reproduction project

[Basis Universal MipMapping.zip](https://github.com/godotengine/godot/files/10526818/Basis.Universal.MipMapping.zip)

**Comment by fire** [comment]
We wanted to use the basisu generated mipmaps rather than 5-12 images with each a basisu mipmap, but clearly it is bugged.

**Comment by fire** [comment]
I am looking into this.

**Comment by fire** [comment]
Here's some commentary about fix for this pr. https://github.com/godotengine/godot/pull/73857#issuecomment-1445120102

We wish to cherrypick the fix from 4.1.
