### ISSUE TITLE
[4.0 Beta 14] TabBar signal pressed not working

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#72239]
### Godot version

v4.0.beta14.official [28a24639c]

### System information

Debian 11

### Issue description

The signal `tab_button_pressed` is not working

### Steps to reproduce

Use the MRP to click the tabs icon

### Minimal reproduction project

[TestTab01.zip](https://github.com/godotengine/godot/files/10526971/TestTab01.zip)

**Comment by Sauermann** [comment]
That is because your TabBar doesn't have a Tab Button Icon.

Please test the following in your MRP:
``` gdscript
func _ready() -> void:
	var texture = NoiseTexture2D.new()
	texture.noise = FastNoiseLite.new()
	texture.width = 100
	texture.height = 100
	$TabBar.set_tab_button_icon(0, texture)
	print("ready")

```
If you click now on the newly added NoiseTexture-Button-Icon, the `tab_button_pressed`-signal gets emitted.

**Comment by git2013vb** [comment]
Was not one of those (icon)? 
![image](https://user-images.githubusercontent.com/13235119/215272475-8c967f26-6308-4c98-8c8b-f583808a0b46.png)

**Comment by YuriSizov** [comment]
Those are icons for the tab itself. Button needs its own icon (and it seems we don't expose it in the inspector UI, so you have to use code).
