### ISSUE TITLE
[Godot 4 beta 16] Scrolling using the trackpad is really slow on macOS

### ISSUE THREAD

**Issue by Cronos87** [godotengine/godot#72242]
### Godot version

4.0.beta16

### System information

macOS Monterey 12.3.1

### Issue description

Since Godot 4 beta 16, scrolling in a scene is very slow; it looks me a long time to reach the point I want.

Here is an example in Godot 4 beta 15:

https://user-images.githubusercontent.com/1923206/215263090-0996323f-fad5-46bf-9473-19c7754b9d69.mp4

Using Godot 4 beta 16:

https://user-images.githubusercontent.com/1923206/215263131-937e2a3c-a2c6-4d40-9a4f-c1404fb503fd.mp4

Sometimes I can scroll not too badly, but sometimes it looks like it is almost not moving.

I only have macOS to try this; I can't tell on Windows or Linux.

### Steps to reproduce

Open a scene and start to scroll.

### Minimal reproduction project

Any projects will have this issue.

**Comment by akien-mga** [comment]
CC @bruvzg @Sauermann

**Comment by Sauermann** [comment]
I can't seem to scroll with the touchpad on a Windows-Laptop, but only zoom. Not sure how to replicate this.

**Comment by stephannv** [comment]
This is happening with me too: v4.0.beta16.official.518b9e580 | Vulkan API 1.2.231 - Apple M1 Max | MacOS 12.6.
This issue doesn't happen on v4.0.beta15.

**Comment by Cronos87** [comment]
By the way, this is not happening in the GDScript editor.

**Comment by Cronos87** [comment]
Is it possible that it's related to this PR https://github.com/godotengine/godot/pull/71685?

**Comment by Zireael07** [comment]
I seem to remember another mouse/trackpad speed related PR recently? But I can't find it on the list.

**Comment by DoctorWhoof** [comment]
I’m experiencing the same but more extreme than on those video examples - what should be a single swipe now needs at least 5 swipes to cover the same distance. Mac OS Ventura 13.2. Pinch to zoom is fine, and non-pan related scrolling with two fingers is also fine.

**Comment by francescarpi** [comment]
Hi. Same here.
The trackpad works very bad. It goes very slow. And also I can't do zoom in/out using Ctrl+Two fingers.

I've got Godot 4 beta 17.
OS: Ventura 13.2 on MBA M1

Let me know if you need more details or I can help.

Thank you so much for this amaizing project.

**Comment by johnfn** [comment]
Trackpad is essentially unusable on macos - which is unfortunate because mac users effectively use their trackpad nonstop. 

A workaround I've found is to press "G" to get into pan mode and then click and drag around. Another one is to plug in a mouse and use the middle mouse button, but that might not work for everyone.

**Comment by bruvzg** [comment]
For the reference, normal panning on the Mac touchpad produce events with deltas in the `0.5 - 1.5` range, a quick movement produces deltas at most `6 - 7`.

**Comment by groud** [comment]
I'll investigate that today. @bruvzg might have the right fix.

**Comment by Cronos87** [comment]
> Trackpad is essentially unusable on macos - which is unfortunate because mac users effectively use their trackpad nonstop.

Indeed. I haven't used a mouse for 10 years, only my Macbook trackpad or the external one. This means this issue is a bit disturbing for me. But regressions are part of a software lifetime; it allows it to evolve.

Thank you, guys, for the immediate investigation.

**Comment by Cronos87** [comment]
Thank you, everyone, to have fixed this issue! I can't wait for RC2 now 😁
