### ISSUE TITLE
AnimationTree AnimationNodeStatemachine stoped working as intended after godot 4 beta 14

### ISSUE THREAD

**Issue by Shidoengie** [godotengine/godot#72244]
### Godot version

Godot 4 beta 14/15/16

### System information

Windows 10

### Issue description

Prior to beta 14 my player animations worked but when moving to beta 14 and onward they stopped working as intended 
heres a video showing its effects
https://youtu.be/yMos8KdybIM

### Steps to reproduce

Im not aware of how to reproduce it.

### Minimal reproduction project

I have here my project that is affected by this bug
https://github.com/Shidoengie/unnamed-soldiertf2-game

**Comment by Zireael07** [comment]
dupe/related to #71870 ?

**Comment by MenchenFive** [comment]
Similar issue on KDE archlinux. For me, just adding the animationtree node into the scene, and attempting to link some animation nodes in the statemachine editor, makes the whole editor CRASH

**Comment by Shidoengie** [comment]
> dupe/related to #71870 ?

just checked on it and yeah pretty much

**Comment by Shidoengie** [comment]
i managed to fix it by storing the previous animation state and only traveling if the current animation state is not equal to the previous.
