### ISSUE TITLE
Godot 4.Beta15 - "standalone" feature tag not working in exported builds

### ISSUE THREAD

**Issue by Crystal-Spiral** [godotengine/godot#72253]
### Godot version

4.0.Beta15

### System information

Windows 10 x86_64, Forward and Mobile Rendering

### Issue description

I've been testing separately exporting project folders into PCK files for dynamic asset loading at runtime.
Feature tag documentation says _OS.has_feature("standalone")_ can be used to check for a non-editor build, however it appears to return false even after export. 
I am able to use "editor" tag instead as a workaround.

### Steps to reproduce

- Create a new GD Script and attach it to the main / starting scene
- In the script, have it print the return value of OS.has_feature("standalone")
- Export the project using the default values for the Windows Desktop export template
- Open the created exe with attached console
- Observe it will print a false value for the feature tag
- Also occurs on exports without debug tools checked

### Minimal reproduction project

[bug-repro_standalone-flag.zip](https://github.com/godotengine/godot/files/10527388/bug-repro_standalone-flag.zip)

**Comment by akien-mga** [comment]
It's replaced by `template`, the documentation should be updated.
