### ISSUE TITLE
Editor freeze when writing "invalid gdscript"

### ISSUE THREAD

**Issue by Frontrider** [godotengine/godot#72252]
### Godot version

Godot 4 beta16

### System information

Manjaro Linux

### Issue description

I'm getting constant freezes with an error message spam like this in the terminal where I started to run Godot from:

```
Debugger Break, Reason: 'Parser Error: Could not resolve script "res://addons/frontrider.statecharts/async_executor.gd".'
*Frame 0 - res://addons/frontrider.statecharts/script_loader.gd:4 in function ''
Enter "help" for assistance.
debug> 
```

```
Debugger Break, Reason: 'Parser Error: Cannot find property "plus_file" on base "String".'
*Frame 0 - res://addons/frontrider.statecharts/file_reader.gd:11 in function ''
Enter "help" for assistance.
debug> 
```
This one was take from godot 3, namely [here](https://gist.github.com/hiulit/772b8784436898fd7f942750ad99e33e), made an attempt at updating it. Also causes the project to be unloadable, god help anyone who has anything similar in an embedded script.

```
*Frame 0 - res://addons/frontrider.statecharts/script_loader.gd:9 in function ''
Enter "help" for assistance.
debug> 
Debugger Break, Reason: 'Parser Error: Function "println()" not found in base self.'
```
Last log I'm adding, it can happen on any typo like situations.

This only happens when I edit into a code segment and then it becomes "not valid" before saving. Editor needs to be killed and restarted. After a restart it is fine until I don't type in "invalid code" again, and even in that case it may or may not trigger.
Yes, for this specific version, the preloaded script it complains about exists, and is valid.

It looks like some kind of debugger is enabled, and it enters an infinite loop if it triggers. This has been happening quite frequently with the last betas.

### Steps to reproduce

Edit the script, and get an error while doping so.

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
How are you running Godot? It sounds like you're using the `-d`/`--debug` switch which enables the command line debugger.

**Comment by Frontrider** [comment]
Closing, it yes I indeed had a debug flag in the startup script for some reason. Thank you!
