### ISSUE TITLE
Tileset: Clicking anything when there is shader attached to tile prompt shader editor

### ISSUE THREAD

**Issue by seppoday** [godotengine/godot#72262]
### Godot version

4.0 beta 16

### System information

Windows 11

### Issue description

There are shaders on alternative tiles. Clicking anything or trying to paint stuff on tile (in this example modulate) ends with the opening shader editor. 

PS: Reloading project helps.

![Godot_v4 0-beta16_win64_1hkaEriocx](https://user-images.githubusercontent.com/62170071/215277448-b65b5ddc-2306-4405-a7eb-2e1ee41a6de5.gif)

### Steps to reproduce

Add shader to tile and try using paint tool on that tile.

### Minimal reproduction project

-

**Comment by akien-mga** [comment]
CC @KoBeWi @groud

**Comment by KoBeWi** [comment]
Somewhat similar to #70705
Clicking the tile brings up the inspector for that tile and switches to shader editor. It will stop doing that once you fold the property.

Maybe a solution to both these issues could be automatically folding the resources when inspector is updated? This would mean that you'd have to manually unfold the resource every time you want to edit it; it would no longer happen on node switch etc. idk what else can be done 🤔
