### ISSUE TITLE
Crash on drag-n-drop to new project dialog

### ISSUE THREAD

**Issue by wydgit** [godotengine/godot#7226]
**Operating system or device - Godot version:**
Windows 10 Core i5 - 2.1.1.stable.official (64-bit)

**Issue description** (what happened, and what was expected):
Crash on folder drag-n-drop to new project dialog

**Steps to reproduce:**
From project manager: click "New Project"
click "Browse"
Drag a folder from Explorer to anywhere in the "Open a Directory" dialog
Crash

Note: a crash will also occur if a folder is dragged into the "New Project" dialog without clicking "Browse"

My motivation was to make browsing to the new folder easier, since the previous project path is not remembered between program runs.  I already had the path open in explorer, so dragging seemed natural.  Copy and paste does work, but is more cumbersome.

**Comment by bojidar-bg** [comment]
Related #5993 (@profelis), #6050 (@Hinsbart) :smiley:
