### ISSUE TITLE
OpenXR action map export regression

### ISSUE THREAD

**Issue by rsjtdrjgfuzkfg** [godotengine/godot#72263]
### Godot version

any version after 74458b6

### System information

Linux x64, but likely irrelevant

### Issue description

OpenXR action maps are not properly exported in recent builds of Godot 4: the `.res` file is small and does no longer seem to contain anything of use. In-game, no actions are passed on to OpenXR (obviously).

I bisected the issue down to https://github.com/godotengine/godot/commit/74458b6e9bed0f28db3374c7406eacbcf4b09b9d, which was merged in #70377.

### Steps to reproduce

1. Delete any previous export files (`.godot/exported/*/*.pkg`)
2. Perform an export (I did one for Android, but it likely works with anything)
3. Observe OpenXR actions not working in the export (error spam 'sync_action_sets: Condition "active_sets.size() == 0"'), and the exported action map file being very small (`.godot/exported/*/*.pkg`, from a few tens of kilobytes down to 296 bytes)

### Minimal reproduction project

Any OpenXR project can be used, such as https://github.com/BastiaanOlij/godot4_openxr_demo

**Comment by dsnopek** [comment]
Thanks for the report! I'll look into it

**Comment by dsnopek** [comment]
Here's a PR that fixes this issue in my testing: https://github.com/godotengine/godot/pull/72402

@rsjtdrjgfuzkfg Can you test and see if this fixes it for you too? Thanks!
