### ISSUE TITLE
Godot 4 beta. area_entered signal not working when collided object has a script.

### ISSUE THREAD

**Issue by sonicjason255** [godotengine/godot#72279]
### Godot version

4.0 beta 16, mono

### System information

Windows 10

### Issue description

the area_entered signal in godot 4 beta gives an error if the collided object has a script on it, but works perfectly fine if there's no script. I thought this might have been a thing with the version of the beta I had as I was on beta 2 when I discovered it, but it's still a problem after upgrading to beta 16.

### Steps to reproduce

set up an area 3d node made to detect other area 3d nodes
![image](https://user-images.githubusercontent.com/53952059/215293366-b0b9dd76-6ed0-4d1c-89d2-b85cce4c8140.png)
this is the script it has connected to the signal
![image](https://user-images.githubusercontent.com/53952059/215293396-fb84da7d-a926-4e2d-8f1e-68ea276fce7b.png)

have 2 area3d nodes, one that has a script on it and one that doesn't
![image](https://user-images.githubusercontent.com/53952059/215293345-e773e438-98e3-4ffc-8704-ad9944b63397.png)
![image](https://user-images.githubusercontent.com/53952059/215293352-a7183655-e795-4181-9241-f6f991df05c2.png)

set a scene up where both are accessible by the player
![image](https://user-images.githubusercontent.com/53952059/215293456-4c93cf41-e866-4fde-9937-0b61ff10a39f.png)

run the scene and hit the one without a script
you can see here that the signal works and the console displays the message correctly
![image](https://user-images.githubusercontent.com/53952059/215293497-46ea12f7-dc8b-48c4-b10d-27ce47fa72b9.png)

now hit the one with the script on it
you can see here that the console doesn't print anything and the debugger throws an error
![image](https://user-images.githubusercontent.com/53952059/215293553-09417302-ed4e-4c0f-87fa-ba374e8d5f0f.png)

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

Please create a minimal reproduction project in GDScript instead of C# for two reasons:

- Non-Mono builds of Godot are easier to set up and have less moving parts.
- This rules out C# being the cause of the bug.

**Comment by sonicjason255** [comment]
once again, an issue I have ends up being solved by changing one thing in code...


seriously though, thank you so much, I can't believe I didn't think about that yet.
the project works fine now.
