### ISSUE TITLE
custom theme for godot interface base_color not load

### ISSUE THREAD

**Issue by konquerprojekt** [godotengine/godot#72275]
### Godot version

4 beta16

### System information

win10

### Issue description

setting base_color from a custom_theme.tres don't work,
only work setting base_color direct in editor_settings > interface > theme > base_color

### Steps to reproduce

create a new_theme.tres resource
edit new_theme.tres > manage_items > import_items > editor_theme > editor > base_color
add the custom theme in editor_settings > interface > theme > custom_theme
 
 
![image](https://user-images.githubusercontent.com/28818773/215291193-fed81414-6b7a-4e45-898a-899a1005ce13.png)
![image](https://user-images.githubusercontent.com/28818773/215291101-1d9fc0f7-a0f3-4e6d-a0af-e687f41752c3.png)

### Minimal reproduction project

[new_theme.zip](https://github.com/godotengine/godot/files/10528333/new_theme.zip)

**Comment by YuriSizov** [comment]
`base_color` is a name of an editor setting. Theme resources doesn't have such property. Instead the editor setting is used to generate many different properties in the editor. If you want to make a fully custom theme, you have to do this yourself/manually. If you simply want to change the base color for the entire editor, you don't have to create a theme, you just change the editor setting.
