### ISSUE TITLE
Kinematic body (3d) not using layer/mask correctly

### ISSUE THREAD

**Issue by sketchyfun** [godotengine/godot#7227]
**Operating system or device - Godot version:**
Windows 7, custom build from November

**Issue description** (what happened, and what was expected):

My understanding is that a physics object that has it's layer set to 1, and it's mask set to 2 will only collide with an object that has it's own layer set to 2

In the demo project I've attached, both kinematic bodies have their layers set to 1 and their masks set to 2. As far as I'm aware, this should mean that the two bodies shouldn't collide, yet they both stop when they reach each other.

Conversely, if you set the first objects layer to 1 and it's mask to 2, and the other objects layer to 2 and mask to 1, they should technically collide with each other, but instead they pass straight through.

Wondering if it was related to this issue? https://github.com/godotengine/godot/issues/872

**Steps to reproduce:**

Download and run the attached project. The first scenario I've described is already set up to run, but you'll have to manually edit the two bodies to test the second scenario I mentioned.

**Link to minimal example project** (optional but very welcome):

https://dl.dropboxusercontent.com/u/3292249/kinematic3d_bug.zip

**Comment by bojidar-bg** [comment]
Can you confirm that the same thing works fine for KinematicBody2D? (if it is, the I introduced this bug... ops)

**Comment by sketchyfun** [comment]
Just tested it with KinematicBody2D and it works correctly

**Comment by eon-s** [comment]
The issue is on 2.1.1 too (KinematicBody against kinematic or rigid on any mode), happens when using move against anything on the same layer.

Maybe move or the server is checking layer instead of mask because it also pushes rigids on other layers.

**Comment by bojidar-bg** [comment]
Wait, you mean that Rigid-Rigid works fine, right? :smiley: 

If so, that would limit the bug to the move function...

**Comment by eon-s** [comment]
@bojidar-bg Rigid moving (impulse) against kinematic or rigid works fine, Kinematic moving (move) against rigid collides (same layer, any mode) or pushes it (different layer, rigid mode).

So, yes, probably move is the first place to look (but all the KinematicBody code looks old compared to the 2D one).

**Comment by sketchyfun** [comment]
I'm wondering if this ever worked for KinematicBody 3d? Looking at the code, I can't see it making any use of the collision mask in the move function, just the body's layer

**Comment by Muzz** [comment]
Ah this explains some behaviour i saw, this is a thing that would be really good to have fixed!

**Comment by eon-s** [comment]
Move is broken on KinematicBody on Godot 3 too, but now it seems to be inverted the layer-mask check (the moving body checks for masks on its layers instead of other layers on its mask).

**Comment by kubecz3k** [comment]
This should be fixed now, would be nice if someone could check

**Comment by eon-s** [comment]
Issue persist with Bullet cc @AndreaCatania

**Comment by eon-s** [comment]
To resume, using bullet:
Kinematic on layer 2, mask 1, using move and slide:
 - Collides with anything on layer 2 (should ignore)
 - Collides with anything on mask 1 (should ignore)

**Comment by kubecz3k** [comment]
I can see dropbox link with reproduction is not working anymore. @sketchyfun could you reupload?
Also tip for the future, you can upload directly on github by drag and dropping zip to the browser.

**Comment by sketchyfun** [comment]
I haven't checked if it still works but here's the link https://www.dropbox.com/s/dwp6qx1d64x8t7t/kinematic3d_bug.zip?dl=0

**Comment by AndreaCatania** [comment]
@sketchyfun this project is not for godot 3

**Comment by AndreaCatania** [comment]
I've checked it with either Godot and Bullet physics and it works correctly

**Comment by sketchyfun** [comment]
Okay, so I just recreated the project in 3.0 and I can't reproduce my original issues, so it looks like this is 
no longer a problem.

I've uploaded the project just in case anyone else wants to try it, but it seems to be working now.

[kinematic_bug.zip](https://github.com/godotengine/godot/files/1493433/kinematic_bug.zip)

**Comment by sketchyfun** [comment]
I'm going to close this as it seems to be fixed, thanks @AndreaCatania !
