### ISSUE TITLE
Name Textbox for Atlas resets caret position to start after every key press

### ISSUE THREAD

**Issue by Anixias** [godotengine/godot#72289]
### Godot version

v4.0.beta16.mono.official [518b9e580]

### System information

Windows 10

### Issue description

Typing into the textbox for Atlas's Name property resets its caret position to the start after every key press, causing you to type in reverse:

![image](https://user-images.githubusercontent.com/22286697/215301479-bb42831b-907d-4bb7-b18c-468647ac426e.png)

### Steps to reproduce

1. Add a TileMap node to a scene
2. Create a new TileSet for it in-place in the Inspector
3. In the "Tiles" tab, press the plus button to create a new Atlas
4. Start typing in the textbox for its name

### Minimal reproduction project

N/A

**Comment by aXu-AP** [comment]
I'll try bisecting this. Haven't done it before, but I think I can get it done.

**Comment by aXu-AP** [comment]
I found  #65419 to be the culprit. Didn't yet understand the exact cause, but I'll take a second look at it tomorrow.

**Comment by akien-mga** [comment]
This typically happens when `notify_property_list_changed` ends up called on each change to the label, forcing a redraw of the UI which sends the caret back to the first column.

CC @SaracenOne

**Comment by aXu-AP** [comment]
Removing this line seems to fix the problem:
https://github.com/godotengine/godot/blob/0810ecaafdbee3ea747219e6ab3a8de5d2216a09/editor/plugins/tiles/tile_set_atlas_source_editor.cpp#L2393
But I'm not sure what side effects would be 😅 
That's a starting point at least.

**Comment by aXu-AP** [comment]
Would it be bad solution to simply save the cursor position before the line I mentioned and reset it afterwards? It feels a bit hacky, but if there's no other problems in this process it's a direct cure for the issue at hand.

**Comment by YuriSizov** [comment]
We could save the caret alongside the focused element in the inspector itself, but it wouldn't solve the underlying problem. There shouldn't be calls to redraw the entire tree when you simply type something in a text field.

**Comment by TheNormandyProject** [comment]
Happens on the MacOS Universal Mono RC-1 as well.
Glad this is being fixed :)
