### ISSUE TITLE
Rust GDExtension fails to register class that extends `HttpRequest`

### ISSUE THREAD

**Issue by justofisker** [godotengine/godot#72280]
### Godot version

4.0.dev beta16

### System information

Windows 11 & PopOS

### Issue description

Using https://github.com/godot-rust/gdextension and creating a simple class that extends `HttpRequest` fails when attempting to register it.

Outputted when project ran from the editor.
```
E 0:00:00:0400   _register_extension_class: Attempt to register an extension class 'TestHTTP' using non-existing parent class 'HttpRequest'
  <C++ Error>    Method/function failed.
  <C++ Source>   core/extension/gdextension.cpp:263 @ _register_extension_class()
```

I first reported it there (godot-rust/gdextension#88), but I was suggested that I report it here.

I suspect that this issue to do with class name's being case-sensitive (godot-rust/gdextension is requesting "HttpRequest" while the class name is officially "HTTPRequest") and is a matter of whether Godot allows for case-insensitive class inheritance for extensions or godot-rust/gdextension updates the name to match godot.

### Steps to reproduce

1. Set `GODOT4_BIN` environment variable to the path to the Godot binary.
2. Build the rust project in `MinRepoRustGodotHTTPRequest\rust`.
3. Open the project in `MinRepoRustGodotHTTPRequest\godot` and run it.

### Minimal reproduction project

[MinRepoRustGodotHTTPRequest.zip](https://github.com/godotengine/godot/files/10528404/MinRepoRustGodotHTTPRequest.zip)

**Comment by Bromeon** [comment]
This was a bug in godot-rust, not in Godot.
The class name was passed wrong. It's totally reasonable for Godot class names to be case-sensitive 👌 

As such, this issue can be closed.
