### ISSUE TITLE
Panning Issue After Renaming

### ISSUE THREAD

**Issue by SolDroid** [godotengine/godot#72296]
### Godot version

4.0dev (4fa6edc88)

### System information

Ubuntu 20.04.2 LTS

### Issue description

Panning of the 2D view does not work after attempting to rename node

### Steps to reproduce

1. Open the a scene in the 2D viewing tab
2. Double click to rename any node under the scene tab
3. click into the 2D view directly
4. attempt to pan the view through middle-clicking or using the pan tool

Refocusing the editor window will fix it temporarily

### Minimal reproduction project

[Panning Issue.zip](https://github.com/godotengine/godot/files/10529131/Panning.Issue.zip)

**Comment by KoBeWi** [comment]
Can't reproduce on Windows 10.
When the name is being edited, middle click will close the edition, but after releasing and pressing the MMB again the panning will happen normally.

**Comment by akien-mga** [comment]
Possibly related to #72074.

**Comment by QbieShay** [comment]
Reproduced on Fedora, Gnome on XORG.

I reproduced with number fields in visual shaders, and renaming nodes too.

**Comment by akien-mga** [comment]
Please try the latest `master` if you haven't, this may be related to what #72370 fixed.

**Comment by QbieShay** [comment]
Fixed for me :partying_face:

**Comment by QbieShay** [comment]
I tried it yesterday and it seemed to work, but I'm experiencing the same issue again now

**Comment by timothyqiu** [comment]
I've got a similar issue on Linux.

If I exit renaming _by clicking outside the LineEdit_:

* I can't interact with scrollbars.
* LineEdits and TextEdits can be focused and edited, but the carets in these controls won't be shown.

It works fine if I exit renaming by hitting enter or ESC.

It's also intreseting that I can only reproduce this with a custom build. The offical beta16 works fine, while custom built 518b9e5801a19229805fe837d7d0cf92920ad413 has this problem. (`target=editor tests=yes module_text_server_fb_enabled=yes dev_build=yes use_asan=yes use_lsan=yes linker=mold`)
