### ISSUE TITLE
Strange errors when running a mostly UI based project

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#72299]
### Godot version

v4.0.beta14.official [28a24639c]

### System information

Mac

### Issue description

I have a UI project I've recently converted from 3.5.1 to 4.beta.14, and I find these errors popping up whenever I start the project.

<img width="869" alt="Screenshot 2023-01-29 at 14 54 05" src="https://user-images.githubusercontent.com/100964/215313054-364be27f-9604-4b9c-94a0-e8ec5d03a4cc.png">

`visibility_changed`
`size_flags_changed`
`minimum_size_changed`

The error pointed out is:
https://github.com/godotengine/godot/blob/master/core/object/object.cpp#L1270

Yet no callstack is given.

### Steps to reproduce

I'm not exactly how to reproduce this as it's not present in another project. 
I'm interested in trying to figure out why the error appears, but I guess I will have to recompile the engine to get deeper debugging on that?

### Minimal reproduction project

I won't upload my full project here, but interested in solutions to debug these three errors.

I would assume it's something to do with an old node that I ported over from 3.5.1, but without deleting and re-adding all nodes in the project, might there be some easier way to test for where this is coming from?

**Comment by tavurth** [comment]
Please note that I do not use any of these signals in my project, this is some Godot core node using such I guess.

**Comment by tavurth** [comment]
Could be related?

https://github.com/godotengine/godot/issues/51543

**Comment by coppolaemilio** [comment]
@tavurth have you tried with the latest version?

**Comment by tavurth** [comment]
@akien-mga unfortunately I'm blocked from using the latest update for my projects until we can resolve this issue:

https://github.com/godotengine/godot/issues/73824

Unfortunately I don't have enough time to test sources outside my project scope at the moment.

**Comment by tavurth** [comment]
<img width="969" alt="Screenshot 2023-02-24 at 23 23 38" src="https://user-images.githubusercontent.com/100964/221232011-f6825467-b755-4bba-aeb3-88d38518414e.png">

Still present `v4.0.rc3.official [7e79aead9]` except now I have a new one about blender.

**Comment by rainlizard** [comment]
I'm not sure but if the error is "signal is already connected", then maybe it means the error occurs because you're trying to connect a signal twice?

**Comment by tavurth** [comment]
@coppolaemilio I've narrowed this down to the `TabContainer` component.

I had a node tree like this:

```gdscript
TabContainer
  Tab(Control)
  Tab(Control)
```

I deleted the `TabContainer` and created a new one with the same attributes. The errors are now gone.

I would assume this is a migration script bug, but I will close this issue. If you feel it should still be open please let me know.

**Comment by tavurth** [comment]
I now have no errors at all somehow! 🥳
