### ISSUE TITLE
Why don't work?

### ISSUE THREAD

**Issue by ko-dokun** [godotengine/godot#72303]
### Godot version

Godot 3.2.3

### System information

windows10

### Issue description

extends KinematicBody
export(NodePath) var animationtree
onready var _anim_tree = get_node(animationtree)
var gravity = Vector3.ZERO
func _physics_process(_delta):
var root_motion : Transform = _anim_tree.get_root_motion_transform()
var v = root_motion.origin/_delta
if is_on_floor():
gravity=Vector3.ZERO
else:
gravity=Vector3(0,-9.83,0)
v += gravity
if Input.is_action_pressed("up"):
_anim_tree["parameters/playback"].travel("Running")
else:
_anim_tree["parameters/playback"].travel("Idle")
move_and_slide(v,Vector3.UP)

I tried this cord. But it is not work.
Debugger said "The function 'move_and_slide()' returns a value, but this value is never used."
Please tell me help.

### Steps to reproduce

Debugger what said?

### Minimal reproduction project

none

**Comment by KoBeWi** [comment]
This is a place to report *engine bugs*, not get help with your projects. Use other community channels instead: https://godotengine.org/community/

btw your engine version is outdated.
