### ISSUE TITLE
Possible Bug: mouse_enter signal gets emitted twice

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#7231]
**Operating system or device - Godot version:** 2.1.1 stable x64 bitz

**Issue description** (what happened, and what was expected):
Hover your mouse over the control area towards the middle button. The `mouse_enter` signal gets emitted.

Keep your mouse on that button.  Now slowly move your mouse away from that button, and the `mouse_enter` signal gets emitted again.

However, **we are already hovering over the control node**.  

I know we can just do `button.set("focus/ignore_mouse", true)`, however if we do that, we lose functionality of the button :-1: 

This happens under any child node of a `mouse_enter` signal, not just buttons.

I'm not sure if this is intended or there is a setting I'm missing. I do believe that the `mouse_enter` signal should only be emitted once though. Having it being emitted twice doesn't seem right since your mouse is already over the control?

**Link to minimal example project** (optional but very welcome):
[mouse_enter_possible_bug.zip](https://github.com/godotengine/godot/files/626402/mouse_enter_possible_bug.zip)

**Comment by bojidar-bg** [comment]
Can we confirm it wasn't accidentally fixed on master?

**Comment by akien-mga** [comment]
*Bug triage note:* The original issue reporter closed all their issues before deleting their account. If you are affected by a similar issue/want a similar feature, please file a new ticket (referencing this one if it contains useful information) so that it can be further looked at and eventually resolved.
