### ISSUE TITLE
Tab bars scroll buttons, double-click creates new empty tab

### ISSUE THREAD

**Issue by duianto** [godotengine/godot#72313]
### Godot version

v4.0.beta16.official [518b9e580]

### System information

Windows 10 22H2, Compatibility, Geforce GTX 550 Ti

### Issue description

When the tab bars scroll buttons are double-clicked, then they create a new empty tab.
Expected: Scroll the tab bar twice.

### Steps to reproduce

- open the attached project: [issue, next or prev tab buttons, double click adds empty scene.zip](https://github.com/godotengine/godot/files/10529987/issue.next.or.prev.tab.buttons.double.click.adds.empty.scene.zip)

The right side of the tab bar shows two buttons: scroll tabs left and scroll tabs right
when there are more tabs than fit on the tab bar.

When Godot is maximized on a display with a resolution of `1920x1080`,
then the tab bar shows the tabs, from: `scene_name - Copy (10)` to: `scene_name - Copy (15)`

The project has 16 tabs, hopefully, that's enough to fill the tab bar on larger resolutions.
But if the person that tests this has a large enough resolution to show all tabs,
then the tester needs to either:
unmaximize Godot and possibly shrink Godot's width, until the tabs don't fit
or create and save additional scenes to overfill the tab bar

- to the right of the last scene tab: `scene_name - Copy (15)`,
click on the button to scroll the tab bar to the left

![Godot_v4 0-beta16_win64_CDrkLktPB3](https://user-images.githubusercontent.com/13420573/215332992-2232c121-441e-4b0c-a170-3cbbc68c60a1.png)

now the tab bar shows the tabs from: `9` to: `14`
- click the scroll tab bar left button twice within 1 second

### Expected
The tab bar should scroll to the left twice, and show the tabs from: `7` to `12`

### Observed

![Godot_v4 0-beta16_win64_MeC6aij5kd](https://user-images.githubusercontent.com/13420573/215333667-345e83b6-a655-4253-9337-469e2734020b.png)

A new `[empty]` scene tab was added to the right of scene `15`,
the tab bar scrolled to the rightmost position, 
and it now shows the tabs from `11` to `15` followed by an `[empty]` tab.

The same thing happens when the button: scroll tab bar to the right, is pressed twice within 1 second.

This means that it isn't possible to scroll the tab bar quickly, by pressing the scroll tab bar buttons quickly.

### A possible cause
Double-clicking on an empty area of the tab bar, to the right of the rightmost tab, creates a new `[empty]` tab.

If the scroll tab bar buttons don't have a specific double-click action,
then maybe the double-click event is picked up by the tab bar, behind the scroll tab bar buttons.

This is possibly confirmed by the fact that the double-click action,
also happens when the scroll tab bar buttons are disabled.

The scroll tab bar right button is disabled when the rightmost tab is focused.
The scroll tab bar left button is disabled when the leftmost tab is focused.

### Minimal reproduction project

[issue, next or prev tab buttons, double click adds empty scene.zip](https://github.com/godotengine/godot/files/10529987/issue.next.or.prev.tab.buttons.double.click.adds.empty.scene.zip)

**Comment by Calinou** [comment]
> double-click creates new empty tab

This is intentional behavior, but it was discussed to remove it as it's obscure and rarely used.

**Comment by gelvinp** [comment]
To add my two cents, I "use" this feature all the time, but always accidentally when I'm just trying to navigate through tabs, which has caused me to compile my own version of the editor with this feature specifically removed. Especially since the "add new" tab button is right next to the arrow buttons anyways, I'd love to see this removed officially.

**Comment by djrain** [comment]
Ah, so _that's_ what I've been experiencing all this time. I was wondering where all those new tabs were coming from. I also thought it was just incredibly buggy.  

The whole scrolling arrows thing is terrible UX in the first place, and personally I'm making a plugin to replace the scene tabs entirely. But yeah this should be removed asap.

**Comment by Calinou** [comment]
The ability to change scenes by scrolling the mouse wheel on the list of tabs was removed in 4.1 by https://github.com/godotengine/godot/pull/70800.

**Comment by gelvinp** [comment]
I am honestly completely confused by removing the ability to change scenes by scrolling and not even making it an option. If I have to use the two arrow buttons to scroll but I also have to take my time and carefully make sure I don’t click either of them too quickly to count as a double press so I don’t unintentionally make a new scene instead, I’m going to completely stop using the official builds and patch that back in myself. I consider that a usability nightmare.

**Comment by Calinou** [comment]
> I am honestly completely confused by removing the ability to change scenes by scrolling and not even making it an option. If I have to use the two arrow buttons to scroll but I also have to take my time and carefully make sure I don’t click either of them too quickly to count as a double press so I don’t unintentionally make a new scene instead, I’m going to completely stop using the official builds and patch that back in myself. I consider that a usability nightmare.

Unfortunately, options that are disabled by default suffer from poor discoverability. They often end up being dead weight in terms of maintenance, as we have to maintain something that will not be used often (and may be buggy for several months if not years).

**Comment by kitbdev** [comment]
Fixed by #79852
