### ISSUE TITLE
PhysicsDirectSpaceState3D.intersect_ray lowers precision the farther away from world origin you go

### ISSUE THREAD

**Issue by Ifhay** [godotengine/godot#72338]
### Godot version

4.0 beta 14

### System information

Windows 10

### Issue description

I was following the official [docs on Ray-Casting](https://docs.godotengine.org/en/latest/tutorials/physics/ray-casting.html) from the screen to the object and discovered that if you go far enough from the origin (~130 units in the attached video), then the recommended way of ray-casting through space state starts to become inaccurate, while casting `RayCast3D` keeps being accurate.

You may see that I switch between using space state and the collision position of `RayCast3D` in the top left corner and the marker either is placed off to the side or in the correct place.

https://user-images.githubusercontent.com/18574763/215352736-8daa2a51-a832-42df-8ce9-fffbe95bc807.mp4

### Steps to reproduce

1. create a `CollisionShape` >130 units from the origin in any direction;
2. build the project, move the camera to the location of the `CollisionShape`;
3. try to ray-cast from the screen using `PhysicsDirectSpaceState3D.intersect_ray`;
4. place a simple small `CubeMesh` at the collision position by `marker.global_transform.origin = result["position"]`;
5. see that the mesh does not have the correct position;
6. try the same but with `RayCast3D.get_collision_point()` to see the mesh in the correct spot.

### Minimal reproduction project

```GDScript
extends Node3D

@onready var marker: MeshInstance3D = MeshInstance3D.new()
@onready var ray_cast = RayCast3D.new()

var new_click_location: Vector2 = Vector2.INF
var _use_space_state: bool = true

func _ready() -> void:
	ray_cast.hide()
	ray_cast.set_collision_mask_value(2, true)
	add_child(ray_cast)

	marker.mesh = BoxMesh.new()
	marker.scale = Vector3(0.2, 0.2, 0.2)
	marker.hide()
	add_child(marker)
	

func _physics_process(delta):
	if new_click_location != Vector2.INF:
		var camera: Camera3D = get_viewport().get_camera_3d()
		var from: Vector3 = camera.project_ray_origin(new_click_location)
		var to: Vector3 = camera.project_ray_normal(new_click_location) * 1000
		
		var result_position: Vector3 = Vector3.INF
		
		if _use_space_state:
			var space_state: PhysicsDirectSpaceState3D = get_world_3d().direct_space_state
		
			var result: Dictionary = space_state.intersect_ray(
				PhysicsRayQueryParameters3D.create(from, to)
			)
		
			if result != null and not result.is_empty():
				result_position = result["position"]
				player.update_path(a_star_custom.find_path(player.global_transform.origin, result_position))
		else:
			ray_cast.global_position = from
			ray_cast.target_position = to
			ray_cast.force_raycast_update()
			
			if not ray_cast.visible:
				ray_cast.show()
				
			result_position = ray_cast.get_collision_point() 
		
		if result_position == Vector3.INF:
			marker.hide()
		else:
			marker.show()
			marker.global_transform.origin = result_position
			
		new_click_location = Vector2.INF
	

func _unhandled_input(event: InputEvent) -> void:
	if event.is_action_pressed("switch_ray_cast"):
		_use_space_state= not _use_space_state
		
	if event is InputEventMouseButton and event.is_action_pressed("click"):
		new_click_location = (event as InputEventMouseButton).position
```

**Comment by Ifhay** [comment]
It looks similar to [61174](https://github.com/godotengine/godot/issues/61174) but this instance has nothing to do with frustum offset.

**Comment by rburing** [comment]
Note the `RayCast3D` node's `target_position` is given in local coordinates whereas the `to` member of `PhysicsRayQueryParameters3D` is given in global coordinates, so your code is incorrect.
