### ISSUE TITLE
Volumetric fog is shifted in screenspace when XR is enabled on the viewport.

### ISSUE THREAD

**Issue by luzader** [godotengine/godot#72331]
### Godot version

4.0beta16

### System information

Windows 10, Vulkan API 1.3.205, NVIDIA - NVIDIA GeForce RTX 3080, Valve Index, Steam VR

### Issue description

When XR is enabled FogVolumes (and probably all volumetric fog but it is not obvious for large homogenous volumes) are rendered to the wrong location in both eyes once XR is enabled on the viewport. Here's a unit-cube dense fog volume stacked between two mesh cubes.

Here it is correctly positioned in the editor:
<img width="687" alt="Screenshot 2023-01-29 122055" src="https://user-images.githubusercontent.com/617962/215351015-db22759f-2687-4791-bf1d-86266a630415.png">
But once XR is enabled on the viewport, the volume is shifted to the left in the left eye and to the right in the right eye:
![Screenshot_Sun_Jan_29_12-19-34_2023_VR](https://user-images.githubusercontent.com/617962/215351058-907ed3c9-ea98-412c-b792-4edfacff9f57.png)

It is also shifted to the left in the main game window (presumably because the game window is rendering the left eye).

The shift is in screenspace as you can see if I rotate my head:
![Screenshot_Sun_Jan_29_12-19-41_2023_VR](https://user-images.githubusercontent.com/617962/215351286-d9dd656a-bc90-4c00-8834-674d294e8a70.png)

### Steps to reproduce

Create a small fog volume and enable XR on the viewport.
I have also observed this on large fog volumes if using a fog shader which creates small clumps of fog, the clumps are shifted wrongly which breaks stereopsis .

### Minimal reproduction project

[FogVolume.zip](https://github.com/godotengine/godot/files/10530642/FogVolume.zip)

**Comment by jakes1403** [comment]
Having this exact issue. Hopefully it can get fixed.

**Comment by BastiaanOlij** [comment]
Fog is indeed still on the list of effects to add stereo support for

**Comment by jakes1403** [comment]
Would this be fixed by the time 4.0.0 is fully released?

**Comment by Calinou** [comment]
> Would this be fixed by the time 4.0.0 is fully released?

No, as this is technically a missing feature for XR.
