### ISSUE TITLE
[4.0 Beta 16] Number of visible lines of word-wrapped label calculated wrong

### ISSUE THREAD

**Issue by DerKusti** [godotengine/godot#72339]
### Godot version

4.0 Beta 16

### System information

Windows 10 and Android

### Issue description

Labels in my program behave weirdly on Godot 4.0 Beta 14-16. The same project works correctly on Beta 9.

When I create labels with word auto-wrap-mode and add text, they correctly increase in height to accomodate multiple lines... up to a certain point (4 lines), then they suddenly produce no more lines (no 5th) and just cut off the remaining text.
The Max Lines Visible property is set to -1. Even if I manually set it to a higher value than the amount of lines after which it cuts off, this changes nothing (a lower value works as expected).
When I copy the same text I added to the label to the clipboard, the text is complete. It's just the label that is too short.

This bug appears on both Windows run-from-editor and on Android devices (for which I intended my program).

I then wrote a new test project from scratch to try and reproduce the issue, in which everything worked fine.

I then created a copy of my project, stripped out everything except the relevant UI structure, and the bug occurred again, even more weirdly than before:
The first time the labels get their text set, they cut off after the first line. When their text is set anew, they cut off after 2 lines. Set it a third time, 3 lines are visible and the fourth cut off...

This stripped project was added for reproduction. I couldn't figure out in which way it differs from my from-scratch-test to introduce this bug.

### Steps to reproduce

- Start the BugReproduction program in Beta 16 (bug also occurs on Beta 14 and 15, doesn't on Beta 9, didn't test with versions in-between).
- Observe that all labels only show one line.
- Use the Clipboard button to copy the whole thing to the clipboard, then paste in a text editor to see the text should be longer on most of the labels.
- Use the Recalculate button to create new text. Suddenly, up to 2 lines are visible per label, but no more than that.
- Use the Recalculate button again, up to 3 lines are visible per label.
- Using the Clipboard button again will reveal that there should be 4 lines on the bottommost labels.

(There are 2 seperate BoxLayouts with seperate Clipboard and Recalculate buttons to show that the increase of visible lines in one layout does not affact the labels in the other layout)

### Minimal reproduction project

[BugReproduction.zip](https://github.com/godotengine/godot/files/10530811/BugReproduction.zip)

**Comment by DerKusti** [comment]
Just noticed upon re-testing my BugReproduction program that the initially-set text only has a single line visible on Beta 9 as well, but on the first recalculate everything gets the correct size on Beta 9.

(In my actual program, I only set the line texts once, and they have the correct length on Beta 9. But a lot more is going on there, and somehow this apparently leads to 4 lines being the cutoff point. Unlike the simple reproduction program, which increases in line length with each time a new text is set.)

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by aXu-AP** [comment]
I can confirm. Also when resizing font or changing some other parameters, shown lines change. They revert upon reloading the scene.

[imagine a screen capture here, which didn't upload for some reason]

**Comment by aXu-AP** [comment]
Regression from #71553
There's a reimplementation #72387, but it doesn't seem to fix this problem.

**Comment by akien-mga** [comment]
Fixed by #72387.
