### ISSUE TITLE
signal with unbinds doesnt work on export

### ISSUE THREAD

**Issue by bend-n** [godotengine/godot#72348]
### Godot version

d01ac9c73

### System information

ArchLinux x11

### Issue description

Signal with unbinds[^1] fails to emit in exported project.

[^1]: ![image](https://user-images.githubusercontent.com/70787919/215381688-1df57b26-2ed5-4473-a9dd-54d9c2228567.png)

### Steps to reproduce

- open mrp
- run in editor
- `it worked!` is printed
- export project
- run executable
-  
```c++
ERROR: Error calling from signal 'sig' to callable: 'Node::_on_sig': Method expected 0 arguments, but called with 1.
   at: emit_signalp (core/object/object.cpp:1058)
```

### Minimal reproduction project

[bug.zip](https://github.com/godotengine/godot/files/10531944/bug.zip)

**Comment by akien-mga** [comment]
Confirmed in 4.0 beta 16.

Interestingly, it works fine when running from source with an export template binary (both release and debug).

Exporting the MRP shows:
```
Can't open file from path 'res://.godot/global_script_class_cache.cfg'.
```
And running shows:
```
ERROR: Couldn't find the given section "" and key "list", and no default was given.
   at: get_value (core/io/config_file.cpp:86)
```
But these might be unrelated issues (there are no global script classes so the file isn't generated).

**Comment by bend-n** [comment]
Sorry, what do you mean by running form source with an export template binary?
Is that different from exporting a binary?

**Comment by akien-mga** [comment]
I mean this:
```
$ cd project/path
$ ~/.local/share/godot/export_templates/4.0.beta16/linux_debug.x86_64
```
This will find `project.godot` and run it.

**Comment by bend-n** [comment]
Oh, interesting. very strange...

**Comment by KoBeWi** [comment]
The scene inside PCK is converted to `scn`. Unbinds are not implemented in the binary format 🙃
