### ISSUE TITLE
Dropdown menus are clicking through to whatever is behind them in v4 beta11 on windows 11

### ISSUE THREAD

**Issue by shanempope** [godotengine/godot#72345]
### Godot version

v4.0.beta11.mono.official [91713ced8]

### System information

Windows 11, GLES3

### Issue description

Dropdown menus are broken and then all clicks click the element behind the dropdown menu.

### Steps to reproduce

Happens on all file dropdowns as well as Inspector dropdowns. Just adding a CollisionShape2D and trying to select a shape clicks whatever is behind it.

https://user-images.githubusercontent.com/9895648/215371333-40a08df0-2f19-4c5c-ade0-47ed273ce640.mp4

In this example video I try to click the shape, and it clicks the scene and deselects the collision shape in inspector.

### Minimal reproduction project

Just make a new project.

**Comment by clayjohn** [comment]
A lot of work has happened in this area since beta 11. Could you try again in beta 16?

**Comment by shanempope** [comment]
Doh, I don't know how I ended up on 11. I thought I downloaded the latest since I just started this today. It is working correctly.

**Comment by shanempope** [comment]
Unfortunately it still seems to be happening in `v4.0.beta16.mono.official [518b9e580]` but as soon as I tried to reproduce it it stopped happening. I'll try to repro and post details.
