### ISSUE TITLE
Godot worked once, but now will not open again

### ISSUE THREAD

**Issue by xyroclast** [godotengine/godot#7234]
Windows 10, Godot 2.1.1

I downloaded Godot, ran it, installed one of the template games (forget what it was called, it had a white icon), realized I'd installed it in the wrong directory, moved the game folders into a new folder, tried to run it from inside Godot, got an error saying one of the resources was not found, deleted the game template, and tried to run Godot again (intending to reinstall the template game).

Now the Godot window will open for only a moment, then the console in the background spits out a bunch of errors, and then the app closes.

I've tried reinstalling Godot, and I've tried deleting the Godot folder in AppData/Roaming, but the problem persists.

I managed to get a look at the console errors by running Godot from the command line, and here's what it says:

`EXEC PATHP??: C:\Users\owner\Downloads\Godot_v2.1.1-stable_win64.exe\Godot_v2.1.1-stable_win64.exe
DETECTED MONITORS: 1
Boot splash path: res://KOBUGE_Splash.png
ERROR: GDScript::load_source_code: Condition ' err ' is true. returned: err
   At: modules\gdscript\gd_script.cpp:750
ERROR: ResourceFormatLoaderGDScript::load: Condition ' err!=OK ' is true. returned: RES()
   At: modules\gdscript\gd_script.cpp:1867
ERROR: Failed loading resource: res://shared/config.gd
   At: core\io\resource_loader.cpp:218
ERROR: Can't autoload: res://shared/config.gd
   At: main\main.cpp:1419
ERROR: GDScript::load_source_code: Condition ' err ' is true. returned: err
   At: modules\gdscript\gd_script.cpp:750
ERROR: ResourceFormatLoaderGDScript::load: Condition ' err!=OK ' is true. returned: RES()
   At: modules\gdscript\gd_script.cpp:1867
ERROR: Failed loading resource: res://shared/save_manager.gd
   At: core\io\resource_loader.cpp:218
ERROR: Can't autoload: res://shared/save_manager.gd
   At: main\main.cpp:1419
ERROR: GDScript::load_source_code: Condition ' err ' is true. returned: err
   At: modules\gdscript\gd_script.cpp:750
ERROR: ResourceFormatLoaderGDScript::load: Condition ' err!=OK ' is true. returned: RES()
   At: modules\gdscript\gd_script.cpp:1867
ERROR: Failed loading resource: res://shared/screen_manager.gd
   At: core\io\resource_loader.cpp:218
ERROR: Can't autoload: res://shared/screen_manager.gd
   At: main\main.cpp:1419
ERROR: GDScript::load_source_code: Condition ' err ' is true. returned: err
   At: modules\gdscript\gd_script.cpp:750
ERROR: ResourceFormatLoaderGDScript::load: Condition ' err!=OK ' is true. returned: RES()
   At: modules\gdscript\gd_script.cpp:1867
ERROR: Failed loading resource: res://shared/scenes_manager.gd
   At: core\io\resource_loader.cpp:218
ERROR: Can't autoload: res://shared/scenes_manager.gd
   At: main\main.cpp:1419
ERROR: GDScript::load_source_code: Condition ' err ' is true. returned: err
   At: modules\gdscript\gd_script.cpp:750
ERROR: ResourceFormatLoaderGDScript::load: Condition ' err!=OK ' is true. returned: RES()
   At: modules\gdscript\gd_script.cpp:1867
ERROR: Failed loading resource: res://shared/settings_manager.gd
   At: core\io\resource_loader.cpp:218
ERROR: Can't autoload: res://shared/settings_manager.gd
   At: main\main.cpp:1419
ERROR: GDScript::load_source_code: Condition ' err ' is true. returned: err
   At: modules\gdscript\gd_script.cpp:750
ERROR: ResourceFormatLoaderGDScript::load: Condition ' err!=OK ' is true. returned: RES()
   At: modules\gdscript\gd_script.cpp:1867
ERROR: Failed loading resource: res://shared/file_manager.gd
   At: core\io\resource_loader.cpp:218
ERROR: Can't autoload: res://shared/file_manager.gd
   At: main\main.cpp:1419
ERROR: GDScript::load_source_code: Condition ' err ' is true. returned: err
   At: modules\gdscript\gd_script.cpp:750
ERROR: ResourceFormatLoaderGDScript::load: Condition ' err!=OK ' is true. returned: RES()
   At: modules\gdscript\gd_script.cpp:1867
ERROR: Failed loading resource: res://shared/SUTjoystick.gd
   At: core\io\resource_loader.cpp:218
ERROR: Can't autoload: res://shared/SUTjoystick.gd
   At: main\main.cpp:1419
ERROR: ResourceFormatLoaderText::load_interactive: Condition ' err!=OK ' is true. returned: Ref<ResourceInteractiveLoader>()
   At: scene\resources\scene_format_text.cpp:947
ERROR: Failed loading resource: res://menu/menu.tscn
   At: core\io\resource_loader.cpp:218
ERROR: Failed loading scene: res://menu/menu.tscn
   At: main\main.cpp:1471
ERROR: SpatialSoundServerSW::free: Attempt to free invalid ID
   At: servers\spatial_sound\spatial_sound_server_sw.cpp:615
ERROR: SpatialSound2DServerSW::free: Attempt to free invalid ID
   At: servers\spatial_sound_2d\spatial_sound_2d_server_sw.cpp:612
WARNING: ObjectDB::cleanup: ObjectDB Instances still exist!
     At: core\object.cpp:1953`

**Comment by Hinsbart** [comment]
@xyroclast It seems that the engine is trying to execute the game direclty. This happens when you run godot from a directory that contains an `engine.cfg` file.
So I guess you accidentally moved some of the project files to the same folder where godot is located, but some files are missing so it fails loading.
(Re)moving those files, mainly `engine.cfg` should allow godot to start again. (Alternatively, move the godot executable somewhere else)

**Comment by xyroclast** [comment]
@Hinsbart Oddly, the folder containing Godot is empty other than the app (I have hidden files enabled) and I've just tried making a fresh new folder and moving the .exe into it to no avail. I've also tried both the 64 and 32 bit versions, with the same result. Thoughts?
Thank you

**Comment by vnen** [comment]
@xyroclast the folders above it also can't contain an `engine.cfg` file, otherwise it'll try to open the project.

**Comment by xyroclast** [comment]
@vnen That fixed it, thank you!!
I never would have thought to consider enclosing folders.

**Comment by cassio-raposa** [comment]
What about cases when there is no engine.cfg in the entire hdd apart from the one present in the project's directory?
Running my project using godot 2.0x goes fine, but if I try to edit it I get the following errors:

ERROR: load: No loader found for resource: res://$exec
   At: core/io/resource_loader.cpp:210.
ERROR: start: Failed loading scene: res://$exec
   At: main/main.cpp:1401.
ERROR: ~List: Condition ' _first != __null ' is true.
   At: core/self_list.h:80.
ERROR: ~List: Condition ' _first != __null ' is true.
   At: core/self_list.h:80.
ERROR: free: Attempt to free invalid ID
   At: servers/spatial_sound/spatial_sound_server_sw.cpp:598.
ERROR: free: Attempt to free invalid ID
   At: servers/spatial_sound_2d/spatial_sound_2d_server_sw.cpp:595.

**Comment by akien-mga** [comment]
@cassio-raposa Did you define `main_scene=res://$exec`? If so that's bogus, you can just remove that line from your `engine.cfg` and it should work.

**Comment by cassio-raposa** [comment]
@akien-mga Hi, thanks for replying so promptly. But my scene is defined as follows in the cfg:

main_scene="res://scenes/intro.tscn"
