### ISSUE TITLE
No way to give an existing variable type hint.

### ISSUE THREAD

**Issue by rambda** [godotengine/godot#72354]
### Godot version

4.0.beta.16

### System information

N/A

### Issue description

```gdscript
func get_variant():
	return call("get_scene") # which is Node


# Called when the script is executed (using File -> Run in Script Editor).
func _run() -> void:
	var a = get_variant()
	if a is Node:
		assert(a is Node)
		a = a as Node
		var must_be_node := a # Error
```

I know assert won't work in exported version. I read somewhere a few years ago that someone said this worked, so I tried it

### Steps to reproduce

N/A

### Minimal reproduction project

[godot.4.0.beta15.bugs.0.zip](https://github.com/godotengine/godot/files/10532057/godot.4.0.beta15.bugs.0.zip)

**Comment by dalexeev** [comment]
```gdscript
var t = get_variant()
var a := t as Node if t is Object else null # `as` works with objects only.
assert(a)
if a:
    var must_be_node := a # OK

var b := get_object() as Node
assert(b)
if b:
    var must_be_node := b # OK
```

**Comment by rambda** [comment]
> ```gdscript
> var t = get_variant()
> var a := t as Node if t is Object else null # `as` works with objects only.
> assert(a)
> if a:
>     var must_be_node := a # OK
> 
> var b := get_object() as Node
> assert(b)
> if b:
>     var must_be_node := b # OK
> ```

`var a := t as Node if t is Object else null` defines a new variable and giving it a type hint with `as`,
it's internally the same as `var a: Node = t`, right?
Also since Object in GDScript is "nullable", can't I just do `var a := t as Node` ?

If I did't give `a` a type hint upon defining, but want to give it later...
I know type hint is "static" by definition, but from a practical perspectives, there are such cases, for example:
```
for key in {a=1,b=2}:
	var cant_infer_type := key
```
Is it possible to give `key` a type hint, without defining a new variable?
related to https://github.com/godotengine/godot-proposals/issues/632#issue-587836828

**Comment by rambda** [comment]
I checked. This used to be possible:
https://github.com/godotengine/godot-proposals/issues/632#issuecomment-869000807
```
for button in buttons:
    if button is Button:
        button.align = ALIGN_CENTER
```
```
for button in buttons:
    assert(button is Button)
    button.align = ALIGN_CENTER
```
```
for button in buttons:
    button = button as Button
    button.align = ALIGN_CENTER
```
According to comments, these codes used to work, but I tried them all in 3.5.1 and they all errors.

**Comment by dalexeev** [comment]
> Is it possible to give `key` a type hint, without defining a new variable?

You can use `as` in expressions, for example:

```gdscript
var name := (get_object() as Node).name
```

But I wouldn't recommend doing that, since `get_object() as Node` will be `null` if `get_object()` returns a non-`Node`.

> If I did't give `a` a type hint upon defining, but want to give it later...
> I know type hint is "static" by definition

You cannot change the static type of a variable at runtime.

**Comment by rambda** [comment]
No that I think about it, shouldn't be able to change the static type.
