### ISSUE TITLE
self.function syntax won't trigger Ctirl+Click -> jump to definition.

### ISSUE THREAD

**Issue by rambda** [godotengine/godot#72353]
### Godot version

4.0.beta.16

### System information

N/A

### Issue description

```gdscript
func _run() -> void:
	click_this_function_doesnt_jump_to_its_line() # this works
	self.click_this_function_doesnt_jump_to_its_line() # add self breaks click-jump























































func click_this_function_doesnt_jump_to_its_line():
	pass
```

Ctrl + Click on self.click_this_function_doesnt_jump_to_its_line(), it won't jump to its definition.

### Steps to reproduce

N/A

### Minimal reproduction project

[godot.4.0.beta15.bugs.0.zip](https://github.com/godotengine/godot/files/10532051/godot.4.0.beta15.bugs.0.zip)

**Comment by Calinou** [comment]
Does it work in 3.5.1?

**Comment by rambda** [comment]
> Does it work in 3.5.1?

Doesn't work in 3.5.1 either.

**Comment by akien-mga** [comment]
Reopening as #73196 was reverted.
