### ISSUE TITLE
Method overriding works differently depending if the variable is declared as typed or untyped

### ISSUE THREAD

**Issue by Gnumaru** [godotengine/godot#72363]
### Godot version

4.0.beta16

### System information

windows 10

### Issue description

When calling a method override from a script, if the bound object was stored in a typed variable, the method override wont be called at all. But if the variable was untyped, the override will be called. In other words, method overrides will only be called depending on details of the call site.

For example, if you create a script that extends Timer and override the stop method, none of the three calls bellow will call the override implementation
```gdscript
extends Node
func _ready() -> void:
	# TYPED AS SCRIPT
	var timer3:ExtendsTimer = ExtendsTimer.new()
	add_child(timer3)
	timer3.stop() # WONT CALL OVERRIDE

	# TYPED AS BASE CLASS
	var timer4:Timer = ExtendsTimer.new()
	add_child(timer4)
	timer4.stop() # WONT CALL OVERRIDE

	var timer5:Timer = Timer.new()
	timer5.script = ExtendsTimer
	add_child(timer5)
	timer5.stop() # WONT CALL OVERRIDE
```

### Steps to reproduce

see the attached video:

https://user-images.githubusercontent.com/5783414/215427136-da0fb71f-3e80-48d8-b6ce-b3ebd4e681ea.mp4

### Minimal reproduction project

[NativeClassOverrideFromScriptWontWorkForTypedVars.zip](https://github.com/godotengine/godot/files/10533861/NativeClassOverrideFromScriptWontWorkForTypedVars.zip)

### Work Around

The user can work around this issue by either using untyped variables OR by erasing the type with a caster function or a temp variable OR by using call
```gdscript
extends Node
func cast(p): return p
func _ready() -> void:
	var timer3:ExtendsTimer = ExtendsTimer.new()
	add_child(timer3)
	timer3.stop() # WONT CALL OVERRIDE

	cast(timer3).stop() # WILL CALL OVERRIDE SUCCESSFULLY
	timer3.stop.call() # WILL CALL OVERRIDE SUCCESSFULLY
	timer3.call('stop') # WILL CALL OVERRIDE SUCCESSFULLY
	var v = timer3
	v.stop() # WILL CALL OVERRIDE SUCCESSFULLY
```

**Comment by dalexeev** [comment]
See #55024.

**Comment by Gnumaru** [comment]
I've read the discussion at https://github.com/godotengine/godot/issues/55024

I agree with akien that:

> we can start with a warning and let people who still want to play with fire mark the warning as ignored and accept they're using an unsupported feature.

and with you that we could

> 2. Allow non-virtual methods to be "overridden" (as in 3.x), but generate a warning about it. And also we can change the method override indicator (blue arrow) for this case.

I'll close this as a duplicate of https://github.com/godotengine/godot/issues/55024

**Comment by dalexeev** [comment]
It seems to me that in #55024 the emphasis is shifted towards "cannot override C++ methods" (which is actually not a bug). In this issue and in my comment, the emphasis is shifted towards "different behavior is bad". And if we decide to make it a warning (not an error), then this bug still needs to be fixed.

Plus, you also noticed that the error occurs when accessing the object externally.

**Comment by Gnumaru** [comment]
Indeed, the focus of this issue is in the inconsistent call behavior on gdscript (involving shadowed native functions) whereas the other issue focus on the undocumented and unintentional behavior that in some scenarios a script can implement a function what will (sometimes) shadow a native implementation of a non-virtual method.

Having a script implementation being called when the current reference is untyped or when you use object::call, but not when you call directly and the reference is typed (specially when the type is the actual one where the implementation you whish to use resides) is really confusing.

But since the other issue is older and could cover this, and that this issue has already been archived, if it needs to be reopened, I would prefer that a core dev reopen it instead of myself.
