### ISSUE TITLE
Can't type @ symbol on mac with Swiss keyboard

### ISSUE THREAD

**Issue by PeterAlfonsLoch** [godotengine/godot#72369]
### Godot version

4.0 dev beta 16

### System information

Macosx M1 macbookpro swiss keyboard

### Issue description

I am unable to type the @ symbol with "option + G" in the editor. Nothing happens when doing so.

### Steps to reproduce

Trying to type @ with "option + G"

### Minimal reproduction project

It is not a project issue it is an editor issue

**Comment by bruvzg** [comment]
By default, `Option+G` is bound to the `ui_text_select_word_under_caret` action, remove in the `Editor Settings` → `Shortcuts` and it will work.

**Comment by PeterAlfonsLoch** [comment]
> By default, `Option+G` is bound to the `ui_text_select_word_under_caret` action, remove in the `Editor Settings` → `Shortcuts` and it will work.

Thank you, that works.

I hope that this issue will help others who encounter that issue.
