### ISSUE TITLE
Mouse wheel zoom on TextureRegion Editor is too fast

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#7236]
On Godot 2.1.1, Windows 10, 64 bits

When I use the mouse wheel on the Texture Region Editor, one tick multiplies the zoom by 4. It's way too fast, and should at least match the + and - buttons, which modify the zoom by a factor of 2.

That repro is a bit chaotic though, the zoom speed doesn't seem consistent.

**Comment by williamd1k0** [comment]
+1
![texture-zoom](https://t.gyazo.com/teams/thetimetunnel/759c52ed632cf60bb48eb148c8a6b60e.gif)
