### ISSUE TITLE
Frequent crashes when using animationTree node

### ISSUE THREAD

**Issue by LeonStansfield** [godotengine/godot#72384]
### Godot version

4.0 beta 16 (also 15, 14, 13, 12)

### System information

Dell XPS 13 plus 2022, 12th Gen Intel(R) Core(TM) i7-1280P, 1800 Mhz, 14 Core(s), 20 Logical Processor(s), intergrated graphics, vulkan

### Issue description

Frequent crashing while using the editor window for the animation tree node. 
This happens randomly usually after a few minutes of using the node and leads to the editor not responding and then crashing a few minutes later.
This is happening on all versions of the beta form beta 10 and on multiple devices.

### Steps to reproduce

Open MRP, edit the animation tree and experience the crash!

### Minimal reproduction project

[animation tree crash.zip](https://github.com/godotengine/godot/files/10536971/animation.tree.crash.zip)

**Comment by TokageItLab** [comment]
@LeonStansfield What operating system do you use? Also, if you can get a crash log, that may be helpful.

**Comment by TokageItLab** [comment]
No reply and cannot confirm, so closing this.
