### ISSUE TITLE
The 2D editor for Android cannot drag content

### ISSUE THREAD

**Issue by Vasilyevski** [godotengine/godot#72385]
### Godot version

4.0rc1

### System information

Android10 MT6765 Mobile

### Issue description

When the 2D editor view is movable, manipulate the content in the editor and the editor view moves with the movement of your finger

https://user-images.githubusercontent.com/120901575/217091720-d111a90e-3476-4365-886e-f0d2140b4d54.mp4

When the editor view is pinned, the operation is normal

https://user-images.githubusercontent.com/120901575/217091804-9ca0c594-483b-40c5-9c61-cac779e61a97.mp4

### Steps to reproduce

Drag content in the scene

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
cc @m4gr3d
