### ISSUE TITLE
Godot "go to documentation" eats 100% ram and dies

### ISSUE THREAD

**Issue by essial** [godotengine/godot#72392]
### Godot version

v4.0.beta16.official [518b9e580]

### System information

M1 Macbook Air (2020)

### Issue description

When ctrl+clicking something in the code editor, it should pop up the documentation in another tab. On godot 3.x it works just fine, but on 4.x 95% of the time it locks up, and allocates as much ram as fast as possible before dying. Every great once in a while I'll see it work but usually it's a hard crash. This has always been an issue in 4.x for at least the last few months since I started using it so I'm reporting it now.

<img width="817" alt="Screenshot 2023-01-30 at 11 55 34 AM" src="https://user-images.githubusercontent.com/242652/215543948-060379b3-40cb-4e23-b3da-6f4d2041890c.png">

### Steps to reproduce

Create/open a project in Godot 4.x on an M1 Macbook Air.
Type some code.
Ctrl+click on a type to pop up documentation.
Wait for your OS to run out of ram while the editor is locked up.

### Minimal reproduction project

No project needed, this happens in any project with any code.

**Comment by akien-mga** [comment]
CC @bruvzg, might be related to RTL threading?

**Comment by bruvzg** [comment]
Can't reproduce. Might be related to https://github.com/godotengine/godot/issues/72183 / https://github.com/godotengine/godot/pull/72208.

**Comment by essial** [comment]
I will say this does not seem to happen on Windows.

**Comment by essial** [comment]
Still happening as of RC2. Sometimes now it just completely crashes out the editor immediately. Doesn't happen on all links, just random ones.

**Comment by YuriSizov** [comment]
Is the result repeatable for the same class, or is it completely random?

**Comment by essial** [comment]
OK tested repeated clicks for each of the below words in the editor and yes it's consistent. I will say with this version the crash seems to happen immediately instead of freezing and filling up RAM.

When Ctrl+clicking...

Camera2D: Works
int: works
remove_at (Array): works
rpc (Node): works
clear (LineEdit): works

AStarGrid2D: instant crash
Node2D: instant crash
set_point_solid: instant crash
PackedVectorArray2D: instant crash

I can try other specific keywords if you have a list you'd like me to try.

**Comment by essial** [comment]
Also note I'm a dev as well, so I'm going to see if I can get clion to build/debug and see if I can also trace the issue.

**Comment by akien-mga** [comment]
When building from source, note that we don't generate debug symbols out of the box, so you have to enable pass `debug_symbols=yes` to SCons manually. Alternatively, pass `dev_build=yes` which implies debug symbols + no optimization and some dev-only code, which can provide more details on the crash.

**Comment by essial** [comment]
Found it!
It crashes on vector.h on:
CRASH_BAD_INDEX(p_index, ((Vector<T> *)(this))->_cowdata.size());

Callstack is:
```
VectorWriteProxy::operator[](int) vector.h:52
CanvasItem::draw_dashed_line(const Vector2 &, const Vector2 &, const Color &, float, float, bool) canvas_item.cpp:537
RichTextLabel::_draw_line(RichTextLabel::ItemFrame *, int, const Vector2 &, int, const Color &, int, const Color &, const Color &, int, const Vector2 &, int &) rich_text_label.cpp:1182
RichTextLabel::_draw_line(RichTextLabel::ItemFrame *, int, const Vector2 &, int, const Color &, int, const Color &, const Color &, int, const Vector2 &, int &) rich_text_label.cpp:951
RichTextLabel::_notification(int) rich_text_label.cpp:1861
RichTextLabel::_notificationv(int, bool) rich_text_label.h:41
Object::notification(int, bool) object.cpp:790
CanvasItem::_redraw_callback() canvas_item.cpp:135
call_with_variant_args_helper<…>(CanvasItem *, void (CanvasItem::*)(), const Variant **, Callable::CallError &, IndexSequence<…>) binder_common.h:293
call_with_variant_args<…>(CanvasItem *, void (CanvasItem::*)(), const Variant **, int, Callable::CallError &) binder_common.h:407
CallableCustomMethodPointer::call(const Variant **, int, Variant &, Callable::CallError &) const callable_method_pointer.h:104
Callable::callp(const Variant **, int, Variant &, Callable::CallError &) const callable.cpp:50
MessageQueue::_call_function(const Callable &, const Variant *, int, bool) message_queue.cpp:229
MessageQueue::flush() message_queue.cpp:275
SceneTree::physics_process(double) scene_tree.cpp:430
Main::iteration() main.cpp:3120
OS_MacOS::run() os_macos.mm:668
main godot_main_macos.mm:86
```

**Comment by essial** [comment]
on CanvasItem::draw_dashed_line there is a bug:

It calculates step (Vector2) by multiplying p_dash by the normalized distance from p_to to p_from. In the case where the value is 0, the condition (steps % 2 == 0) is true which causes steps-- to underflow to the max value of 2147483647.

At this point, when points is constructed and resized, it does points.resize(steps + 1), which _overflows_ back to 0.

Then at the for loop just under that, it's going to loop from 0 to max value (2147483647) and immediately crash because the points.write[i] index is always going to be invalid due to it being a 0-length array.

**Comment by akien-mga** [comment]
CC @dalexeev @bruvzg

**Comment by essial** [comment]
Furthermore... in this scenario:

float length = (p_to - p_from).length(); sets length to 84
Vector2 step = p_dash * (p_to - p_from).normalized(); sets step to (0, 0)

p_to is:
[0] = {real_t} 1139
[1] = {real_t} 1259

p_from is:
[0] = {real_t} 1055
[1] = {real_t} 1259

**Comment by bruvzg** [comment]
> It calculates step (Vector2) by multiplying p_dash by the normalized distance from p_to to p_from. In the case where the value is 0, the condition (steps % 2 == 0) is true which causes steps-- to underflow to the max value of 2147483647.

OK, checking dash size and step makes sense, but there might be another bug as well, since it should not be called with dash size == 0 in a first place.

**Comment by essial** [comment]
Yup I'm evaluating that now. Sorry, haven't worked on godot before so fresh eyes and all.

**Comment by essial** [comment]
Though I would say this function needs more defensive code so you don't try to write to invalid memory locations regardless of the originating bug. Maybe a debug assert to at least show there's a problem without actually nuking the user's machine. But that's technically a separate issue.

**Comment by essial** [comment]
Aaand you've already created a PR for that one, haha

**Comment by bruvzg** [comment]
> AStarGrid2D: instant crash
> Node2D: instant crash
> set_point_solid: instant crash
> PackedVectorArray2D: instant crash

I have tried it with theses, and still can't reproduce it. I guess it might be sensitive to the help window size.

**Comment by essial** [comment]
I'm going to track down why the size is wrong in the first place. I got you fam.

**Comment by essial** [comment]
I'm slammed at work so may be later in the day before I have a full understanding, but at the high level:

float underline_width = TS->shaped_text_get_underline_thickness(rid) * theme_cache.base_scale;

is setting underline_width to 0 in rich_text_label:1181

It calls into text_server_adv:5855

The sd object's uthk (underline thickness?) has a value of 0.

**Comment by essial** [comment]
So this may be a bit more abstract and beyond direct tracing.

Ultimately the issue is that the text has an underline hint, but the underline width is set to 0 somewhere else.

This specific issue I believe is dealing with certain hyperlinks in the help document. But could crash anywhere that uses a rich text label, and sets underline hints with a 0 underline size.

The patch you posted above will stop the drawing from blowing up in this condition, and that may be 'good enough'. I guess technically we could break the attempt at the start by checking underline size, but not sure if it's even really worth it to be that pedantic with no real gain.

**Comment by bruvzg** [comment]
> The sd object's uthk (underline thickness?) has a value of 0.

For line thickness, values ≤ 0 are fine (it's gonna use 2 point primitive to draw it, instead of 4-point).
