### ISSUE TITLE
interface/editors/default_signal_callback_name not working

### ISSUE THREAD

**Issue by Badaxis** [godotengine/godot#72391]
### Godot version

v4.0.beta16.official [518b9e580]

### System information

Windows 10

### Issue description

I changed the default value of default_signal_callback_name weeks ago from ```_on_{node_name}_{signal_name}``` to ```_on_{NodeName}_{signal_name}``` in order to match the behavior in v3.5
I'm pretty sure it was still working in v4.0.beta13 (didn't try in later versions until now).
But now it does not seems to work at all even if I type ```_on_Narnia_{signal_name}``` I only get the default:
![image](https://user-images.githubusercontent.com/29995442/215540537-1c00249d-abde-4c6b-b364-da01f36a7fd2.png)
![image](https://user-images.githubusercontent.com/29995442/215540734-81acd743-d3f1-4701-a0fe-3de7937cf2f7.png)
![image](https://user-images.githubusercontent.com/29995442/215540976-83451fab-0821-4727-8777-10a2b3ec72ce.png)

### Steps to reproduce

Change interface/editors/default_signal_callback_name in the Editor Settings to whatever value.
Connect a children node's signal to its parent's script.

### Minimal reproduction project

n/a: Editor settings issue

**Comment by RedMser** [comment]
This is not a bug  You're connecting a signal to the node the signal is coming from. So the "self node" editor setting, below the highlighted setting in your screenshot, is used instead.

**Comment by Badaxis** [comment]
As you can see in the second screenshot, the signal is connecting from the Timer node to the EnemySpawner (Node2D) node. So it's node "self node" as I wouldn't even have the node name in the signal callback.

**Comment by RedMser** [comment]
Oops I didn't look at the screenshot thoroughly enough, you're right!

**Comment by dalexeev** [comment]
Now this is a project setting.

![](https://user-images.githubusercontent.com/47700418/215762721-02a6d796-28ae-4a7d-91f9-3144ab4a4746.png)

**Comment by Badaxis** [comment]
Oh OK thanks for the info, didn't know the settings were moved.
So it's back like in v3.5 where I have to edit my naming preferences every time I create a new project…
I was so happy to finally have it global, damn.

**Comment by dalexeev** [comment]
Different projects may have different naming styles. See also:

* #69012
