### ISSUE TITLE
BSOD when game is left open for a few minutes

### ISSUE THREAD

**Issue by ElectricVersion** [godotengine/godot#7240]
**Operating system or device - Godot version:** Windows 10 - Godot Version 2.1

**Issue description**:  When leaving my game open for a few minutes, the computer freezes and then gets a Blue Screen of Death. (I am fairly confident that it's not an issue with my computer, because I don't have this issue in any other situation or with any other program). I'm also fairly certain it's not a memory issue, because even if it's just an empty scene, the BSOD happens.

**Steps to reproduce:** Press F5/the "play" button, then wait a minute or so.

**Comment by Alex-doc** [comment]
Some more details would actually be useful...
Video card?
CPU?
RAM?

Does it do BSOD ( the sad smile thing ) or just crashes?
Godot's console shows any warning or message?

**Comment by eon-s** [comment]
BSOD (sometimes) gives useful information about what caused the crash, that info can be found on the dump file too.

Could be the video drivers, gpu temperature, a dying hard drive/ram/power supply.

**Comment by Spark01** [comment]
@Alex-doc It first crashes, but the console stays open and is impossible to close. The BSOD happens about 30 seconds later, every time. Video card is NVidia Geforce GTX. CPU is Intel Core i7-6700HQ. 8 GB ram. 

@eon-s I will keep an eye out for what the BSOD says if it happens again, though I try to avoid causing the BSOD in order to prevent potentially damaging my computer.

**Comment by eon-s** [comment]
@Spark01 there are tools to read the dump files.
Official ones:
[https://developer.microsoft.com/en-us/windows/hardware/windows-driver-kit](https://developer.microsoft.com/en-us/windows/hardware/windows-driver-kit)
A simplified program:
[http://www.nirsoft.net/utils/blue_screen_view.html](http://www.nirsoft.net/utils/blue_screen_view.html)

You can also look at the event logs if you remember the time when the crash happened.

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Chaosus** [comment]
@ElectricVersion I decided to close this issue - We are unable to help you if you are not provide crash dump + This issue from 2016 and its very obsolete - I suggest to try to use 3.0.6, 3.1 or 2.1.5 and recreate this issue if this is still relevant
