### ISSUE TITLE
Clicking on color selector exits out in single window mode

### ISSUE THREAD

**Issue by Coder2195Text** [godotengine/godot#72409]
### Godot version

Godot 4 Beta 16

### System information

Ubuntu 22.04 Running on Vulkan Mesa Intel® UHD Graphics 620 (WHL GT2)

### Issue description

https://user-images.githubusercontent.com/63069499/215583979-e525a1fd-930f-4650-8e9f-3752100cdb72.mp4

Godot keeps clicking out of the color editor

EDIT: I did a test it seems to be single window mode

### Steps to reproduce

Go in editor settings and search for single window mode 

Enable it

Try using the color editor on any color field with single window mode

### Minimal reproduction project

N/A

**Comment by Sauermann** [comment]
I tracked this problem to `DisplayServerX11::process_events` which receives a `FocusOut` message.
Immediately afterwards a `FocusIn` message is received, which causes the `ColorPicker` to close.
