### ISSUE TITLE
Various issues when multiple carets are on the same row

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#72410]
### Godot version

4.0 beta16

### System information

Ubuntu 22.04.1 LTS

### Issue description

When I use multi-carets and I have two on the same line, various functionalities misbehave by being run twice on the same line:

* Toggling breakpoints (F9)
* Toggling bookmarks (Ctrl+Alt+B)
* Toggling comments (Ctrl+K)
* Toggling folding (Alt+F)
* Duplicating lines (Ctrl+Shift+D)
* Deleting lines (Ctrl+Shift+K). There must also be a selection.
* Indent/Unindent (might be by design but I doubt it)

Move line up/down (Alt+Up/Down) works correctly though, so maybe its implementation can be used as a baseline.

### Steps to reproduce

Test the above in the script editor

### Minimal reproduction project

N/A

**Comment by aXu-AP** [comment]
I've been working with some of these functions lately, so I think I can tackle this too.

**Comment by aXu-AP** [comment]
I've completed most of these now and made pull requests for each. Some PRs fix various other issues found in these operations and make their behavior more consistent with each other.

Status:
✔️ Toggling breakpoints
✔️ Toggling bookmarks
✔️ Toggling comments
⚪ Duplicating lines (this one is a bit more complex and has another problem to fix as well)
✔️ Deleting lines 
⚪ Indent/Unindent

**Comment by YuriSizov** [comment]
This is only partially addressed

**Comment by akien-mga** [comment]
I would suggest opening new issues for the remaining points, to keep things focused.

**Comment by aXu-AP** [comment]
@MewPurPur will you open issues for the remaining ones, I think you found some more also?

**Comment by MewPurPur** [comment]
Sure sure, I'll stress-test this soon
