### ISSUE TITLE
Can't move AnimatableBody3D in the editor

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#72416]
### Godot version

4.0.beta 44c0bfc94

### System information

Fedora 37, GeForce RTX 4090 (NVIDIA 525.78.01), Forward Plus

### Issue description

It's impossible to move AnimatableBody3D in the editor – nothing happens, even though you can see the transform message at the bottom-left corner of the 3D editor.

This problem occurs regardless of whether the AnimatableBody3D contains a valid CollisionShape3D child node.

This problem does not occur with AnimatableBody2D, StaticBody3D or CharacterBody3D.

https://user-images.githubusercontent.com/180032/215598547-afab7150-eaf4-4fbb-8589-0856c9beff9d.mp4

### Steps to reproduce

- Add an AnimatableBody3D node in the editor.
- Try to move it using the gizmos or the inspector's **Position** property.

### Minimal reproduction project

N/A

**Comment by aXu-AP** [comment]
I can confirm that you also cannot rotate or resize AnimatableBody3D.

Just as I wanted to test if my old issue #58269 happens on AnimatableBody3D as well and make a new test project for it 😅

**Comment by aXu-AP** [comment]
I ran into some problems with compiling builds, but I believe #67847 is when the regression happened.
