### ISSUE TITLE
SeparationRayShape3D collision shape doesn't affect is_on_floor() on CharacterBody3D

### ISSUE THREAD

**Issue by Ivanfs8** [godotengine/godot#72429]
### Godot version

v4.0.beta16.official.518b9e580

### System information

Windows 10

### Issue description

I'm making a 3D game where I use the SeparationRayShape3D on a CharacterBody3D to move on stairs and obstacles. Since it's the ray collider that's touching the ground, It's the only one that can detect is_on_floor(). 
I updated from 4.0 beta 13 to 4.0 beta 16 and noticed I could not detect is_on_floor() with the ray collision anymore, but it still collides correctly. I have confirmed it also doesn't work in beta 14 and 15

### Steps to reproduce

1. Make a CharacterBody3D for a player and a StaticBody3D with box collider for the ground
2. On the CharacterBody3D, add a capsule collider on top and a short SeparationRayShape3D on the bottom (rotated to face the ground)
3. Add a script that implements gravity if not is_on_floor(), and prints is_on_floor() at the end

In beta 13 the character will work properly and stop at the end of the ray, in beta 16 it will jump up and down and clip because it can only detect is_on_floor() with the capsule

### Minimal reproduction project

[RayBugTest.zip](https://github.com/godotengine/godot/files/10541935/RayBugTest.zip)

**Comment by rburing** [comment]
Probably a duplicate of https://github.com/godotengine/godot/issues/72090, please [test](https://docs.godotengine.org/en/latest/contributing/workflow/testing_pull_requests.html) whether the PR https://github.com/godotengine/godot/pull/72107 fixes your issue (and leave a comment on the PR if so).

**Comment by Ivanfs8** [comment]
Damn I searched for issues with "floor" or "ground", It is a duplicate. I tried your PR and now it works perfectly fine, thanks for the fix!
