### ISSUE TITLE
Weird alpha cutting in 3D

### ISSUE THREAD

**Issue by timoschwarzer** [godotengine/godot#7243]
**Operating system or device - Godot version:**
Linux, latest master

**Issue description** (what happened, and what was expected):
I'm experiencing some weird alpha cutting on Sprite3D nodes.

If there are Sprites overlapping on the right side of the viewport, it works like I expect it to work:
![image](https://cloud.githubusercontent.com/assets/8849554/20867513/f9183016-ba46-11e6-9d3b-d1e17714cdf9.png)

If I move the camera so that the Sprites are on the left half of the viewport, it cuts down every pixel which has Alpha < 1. **I don't know if that's intended behavior, but it makes creating a sprite based 2.5D game literally impossible**. But maybe this is changing with the new renderer... :-)
![image](https://cloud.githubusercontent.com/assets/8849554/20867527/53788bb4-ba47-11e6-83d5-8cc82a21552c.png)

All Sprites use this shader:
![image](https://cloud.githubusercontent.com/assets/8849554/20867531/7e57fb58-ba47-11e6-839a-fd284a1e8b17.png)

For example, look at the lower half of the pipe: https://youtu.be/QvAQIWnsLyk

**Steps to reproduce:**
Put some blurred sprites (with alpha) behind each other and look at them from different perspectives.

**Comment by SuperUserNameMan** [comment]
it must be related to the z-sorting of the transparent polygons.

it affects also other platforms and other types of 3D nodes that draw transparent polygons.

**Comment by SuperUserNameMan** [comment]
I feel like my previous reply was short ...

3D transparent polygons are z-sorted by godot renderer, and AFAIK, there is no mean to manually choose the order in which they are drawn.
Though, in some cases, setting the "Fixedmaterial / Material / Flags / On Top" flag might help with the frontmost layer.

The only workaround that i know is to split the large polygons into smaller tiles.

**Comment by timoschwarzer** [comment]
I want to try if it's "fixed" in 3.0, but we need working Sprite3Ds for that.

**Comment by reduz** [comment]
The problem in this case is pre pass alpha I think, which is just masking a
problem. Withuot prepass alpha, your geometry should be z-sorted and
display properly, you don't want to draw depth on objects with alpha unless
they can't be sorted

**Comment by timoschwarzer** [comment]
Will it be possible to disable pre pass alpha in 3.0 (and do z-sorting respectively)? This would make sprite-based perspective 2.5D games possible.

**Comment by reduz** [comment]
You can already in the material settings

**Comment by timoschwarzer** [comment]
@reduz Great! Was there an option for this in 2.1 already or is it new in 3.0?

**Comment by reduz** [comment]
it's an option both in 2.1 and 3.0

**Comment by timoschwarzer** [comment]
So, would it be easy to implement custom z-sorting of my nodes? Because currently they are sorted by the distance from the camera, right? But I want to sort them by their z coordinate, because we will never change the look angle in a 2.5D game.
@reduz Can you give me a small hint where I have to investigate here? Thanks :smile:

**Comment by reduz** [comment]
For 2.1 or 3.0?

**Comment by timoschwarzer** [comment]
Preferably 3.0, but if it's possible in 2.1, too, I could experiment there until 3.0 is ready.

**Comment by timoschwarzer** [comment]
So, I got it to work in 2.1! :smile: 
Unless this is 100% different in 3.0 I should get it there, too.

For those who are curious:
The only thing that I needed to do was changing one line in `drivers/gles2/rasterizer_gles2.cpp`:
Line 4561: `e->depth = camera_transform.origin.distance_to(p_instance->transform.origin);`
to `e->depth = p_instance->transform.origin.z;`

This causes the renderer to sort everything by its z coordinate. This simple implementation has it's limitations (e.g. you can't look from the backside or everything is sorted wrong) but this is a perfect start for a 2D game with perspective 3D graphics.

Now there are other things to do like getting 2D physics to work in the 3D environment as using 3D physics here is not needed and will only cause other problems. But this does not belong to this issue.
Thanks @reduz! :smile:

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by timoschwarzer** [comment]
2D in 3D is still not easy/possible in Godot as it needs changing the engine's z-sorting. It would be nice to have an additional Z-Value for Sprite3Ds and 2D meshes (on roadmap) in 3D, too. The use case for example is a 2.5D platformer.

**Comment by Calinou** [comment]
@timoschwarzer Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by timoschwarzer** [comment]
I cannot reproduce this bug right now in GLES3. I cannot test GLES2 right now because of https://github.com/godotengine/godot/issues/35401

**Comment by clayjohn** [comment]
The rendering engine for 2.x and 3.x is so different. I am not sure this issue is even worth tracking anymore.

**Comment by timoschwarzer** [comment]
I, too, think that this issue can be closed.

**Comment by clayjohn** [comment]
Closing. If you notice anything like this, feel free to ping me and I'll re-open.
