### ISSUE TITLE
Animations in Animation Trees state machine are not looping

### ISSUE THREAD

**Issue by LeonStansfield** [godotengine/godot#72446]
### Godot version

4.0 beta 16 (also 15, 14)

### System information

Windows 11, foreward+ renderer, Dell XPS 13 Plus (integrated graphics), 12th Gen Intel(R) Core(TM) i7-1280P, 1800 Mhz, 14 Core(s), 20 Logical Processor(s)

### Issue description

Animations are not looping when running the project while using the AnimationTree and skeletal animations. The animations will loop as expected in the editor, but when running do not loop.
The works as expected from beta 13 and earlier. This does not seem to affect non-skeletal animations. As seen in the video.

https://user-images.githubusercontent.com/23266792/215739665-13099107-59c7-4652-9182-22f14d8680ba.mp4

### Steps to reproduce

Open MRP, and play main scene, observe how animations do not loop in the game, but do in the editor.

### Minimal reproduction project

[bug.zip](https://github.com/godotengine/godot/files/10545605/bug.zip)

**Comment by TokageItLab** [comment]
Should not spamming `travel()`. See also #71418.

```gdscript
if state_machine.get_current_node() != "On_floor":
	state_machine.travel("On_floor")
```

[bug_fixed.zip](https://github.com/godotengine/godot/files/10545798/bug_fixed.zip)

**Comment by LeonStansfield** [comment]
I haven't had time to sit down and find a work around to spamming travel()
yet. But out of curiosity, doy yo know, why this work fine in Godot 3.x and
Godot 4.0 beta 13 and before?
Thanks for the help.

**Comment by Zireael07** [comment]
@LeonStansfield The answer to the why question is, because animation tree was reworked in the PR #71418, as to why the PR was necessary, go to it to find out in details

**Comment by TokageItLab** [comment]
I have received so many similar inquiries so I sent #72450 PR.
