### ISSUE TITLE
Godot 4 tilemap - the bigger the map the lower the fps

### ISSUE THREAD

**Issue by grusad** [godotengine/godot#72458]
### Godot version

4.0 beta 16

### System information

Linux mint 

### Issue description

By increasing the tiles of the tilemap the fps reduces. Starting off with a map approxiate 12k x 12k i got around 1,5k fps. decresing the tiles in the map with 200x200 tiles the fps increased to around 1.7k.

Isnt there a "built in" batching/chunking logic within the tilemaps? To create a large open world map right now you have to split up one Tilemap into different Tilemaps as chunks and load them dynamically dependent where the camera is in the world.

Best regards
/G

### Steps to reproduce

Compare fps of a large tilemap with a not so large tilemap

### Minimal reproduction project

[minimal.zip](https://github.com/godotengine/godot/files/10548148/minimal.zip)

**Comment by Zireael07** [comment]
1500 fps is 0,6666666666666666 ms per frame. 1700 is 0,5882352941176471 ms so a difference of around 0.1 ms per frame. 
IMHO you shouldn't be worrying about performance at those numbers.

**Comment by grusad** [comment]
Understandable when speaking in those number of frames. Though my laptop is not as beefy as my pc, so the difference is bigger over there. The question is still there, why does the map size affect the performance? I suppose the whole tile map isnt being rendered or processed?

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/72405.

**Comment by grusad** [comment]
Thanks @Calinou for the reply. 

> Is this causing a noticeable performance issue in a real world project? If not, I would just continue developing the project as usual.
There is #72405 can edit the map anymore. 

Ill get going with chunking up the tiles aswell.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/72405.

**Comment by grusad** [comment]
I have to correct myself: It was not 12k x 12k tiles. Rather 700-800 tiles in both direction.

**Comment by Calinou** [comment]
> I have to correct myself: It was not 12k x 12k tiles. Rather 700-800 tiles in both direction.

This still seems to be in line with what I'd expect.

By the way, which graphics card model do you have? Which resolution are you running the project at?

**Comment by Calinou** [comment]
> running the game in fullscreen on my 27' preditor monitor. :)

Which resolution does it have? There are 27" monitors with 1080p resolution, others with 1440p and others with 4K.

**Comment by grusad** [comment]
> If you run into performance issues on target hardware, yes. Otherwise, no.

Probobly wont run in to any issues. Chunking entities, just curious :)


> Which resolution does it have? There are 27" monitors with 1080p resolution, others with 1440p and others with 4K.
Oh sorry, 1440p!
