### ISSUE TITLE
Make the 3D grid in the editor infinite

### ISSUE THREAD

**Issue by vybr** [godotengine/godot#7245]
With 3.0 having a heavy focus on 3D, it will result in a surge of users coming to create 3d games. The 3D grid in the editor is quite small and should be made infinite. I don't know how hard this is to implement but it improves the overall usability of the engine in my opinion.

Thanks.

**Comment by Zylann** [comment]
That could be done with a grid that follows the camera (so it looks like it's always there but still matching correct spatial units), and if the camera zooms out or moves further, it will multiply its size by 10, and so on. For a reference, Unity's grid does that, as well as 3DSMax.

**Comment by Einlander** [comment]
Also the grid should have user adjustable measurements.

**Comment by Noshyaar** [comment]
Still reproducible/relevant in 3.1 master 9e7cee2 : grid is not infinite

**Comment by aaronfranke** [comment]
Related: https://github.com/godotengine/godot/issues/12324

I was looking through the code for this, and I noticed that it generates grids for each of the three axial planes. So, not only the flat XZ plane, but also the XY and YZ planes. However, these are hidden and never shown, as there doesn't seem to be any setting inside Godot to enable them. As-is, it seems strange that essentially the same piece of code is ran two extra times for no purpose.

If this would be implemented, does anybody care about having grids on the XY and YZ planes? If these extra grids are never exposed to Godot users then I don't see why the code should generate them internally. Though admittedly, it does look really trippy:

![1](https://user-images.githubusercontent.com/1646875/56468682-9e95bd80-63fd-11e9-823e-49dc7cb5793c.png)

**Comment by Zireael07** [comment]
If grids were larger, having them (toggleable) for the other two axes would make sense. At the size they are now, not so much.

**Comment by aaronfranke** [comment]
If anyone would like to try out infinite grids, I recently updated #28289 to be mostly functional.
