### ISSUE TITLE
Enhanced 3d Navigation Mesh Feature Suggestions.

### ISSUE THREAD

**Issue by Einlander** [godotengine/godot#7246]
Currently the 3d navigation mesh does not interact with other navigation meshes or collision meshes in any  meaningful way. In coming versions of the engine this may be fixed, but I would like to make sure the concern is at least written down somewhere.

---

Issue:
- All navigation meshes are treated separately. This causes AI to get stuck in a navigation segment.
**How it should be:**
 ![How it should be](http://i.imgur.com/zVEB222.jpg "How it should be")
**[Simulated] How Godot Does It:**
![[Simulated]How Godot Does It](http://i.imgur.com/kg4NKnj.jpg "How Godot Does It")

Example:
- One can get a 3d road asset and connect them end to end. If an AI is placed at the end of the road and tell it to navigate to the other end, it would be unable to. 

Suggestion:
- To solve this I would suggest merging all the navigation meshes, unless it is possible to make pathing cross multiple adjacent or overlapping navigation meshes without connecting them.

---
Issue:
- The navigation mesh generator does not handle obstacles at all. This causes AI to get stuck on objects it should route around.
**How it should Be**
![How it should Be](http://i.imgur.com/2jGD1gk.jpg "How it should Be" )
**[Simulated] How Godot does it.**
![[Simulated]How Godot does it.](http://i.imgur.com/ZqiMLIy.jpg "Simulated]How Godot does it." ) Simulated]

Example:
- If one were to place a a box or chair on the floor and have the navigation mesh generator would not react to the fact that there is an obstacle in contact with the navigation mesh. 

Suggestion:
- My suggestion is that all collision node types should have an option for 'Things that affect the nav mesh' eg: Sofas/cars/buildings and 'Things that do not affect the nav mesh' eg: litter/debris/boxes. The result should be a hole in the nav mesh surrounding the obstacle.

**Comment by volzhs** [comment]
I hope something like this.
http://xenko.com/blog/new-version-1-9-0/#navigation-meshes

**Comment by Muzz** [comment]
Further extensions to nav mesh would be a great feature to shoot for. Highly support it here.

**Comment by Zireael07** [comment]
Don't navmeshes merge automatically now?

**Comment by Zireael07** [comment]
Shouldn't this be closed? I believe navmeshes merge automatically now.

**Comment by akien-mga** [comment]
Assuming so. Feel free to comment/reopen if it's not fixed yet in the master branch.

**Comment by Einlander** [comment]
Reopening, Reason: cant make obstacles.

**Comment by Jackain** [comment]
I will have to try but i think the navmesh you want to merge need to share vertices

**Comment by Einlander** [comment]
They do but, that;s not really feasible when you are dealing with 3d assets from different sources. How exactly are you supposed to share vertices for a bridge with the terrain? How do you prevent the ai from walking into the water if you can't mark the water itself as a navigation obstacle? All meshes with navigable navigation nodes should be merged and the navigable area calculated from the merged mesh.

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by atllllll** [comment]
Just wanted to bring in @SaracenOne on this since they added basic Recast integration last year (92e77d5). If you're able to find the time, SaracenOne, could you write a brief write-up on the plugin's current functionality and a plan for how it could be developed further and perhaps how others could contribute, please? That would be great! You said you'd need a moment to collect your thoughts and refresh your memory, so no rush. Thanks.

**Comment by chrisb123** [comment]
How feasible would it be to have a negative navigation system, meaning the character is free to go anywhere except certain spots

**Comment by akien-mga** [comment]
Navigation issues will be reevaluated for Godot 3.2, moving to that milestone.

**Comment by akien-mga** [comment]
I assume that at least part of these suggestions are handled by the new NavigationServer in Godot 4.0.

If any points are still relevant in the `master` branch, please open new dedicated proposals on [godot-proposals](https://github.com/godotengine/godot-proposals).
