### ISSUE TITLE
AT_LIGHT_PASS always false

### ISSUE THREAD

**Issue by CalcoDev** [godotengine/godot#72477]
### Godot version

4.0 beta 16 win64

### System information

Windows 11, Intel i7-11700, NVIDIA GeForce RTX 3060 driver 527.56

### Issue description

I was trying to show a sprite only when it was overlapping a light. Looking around in the CanvasItem Shader documentation I found the `AT_LIGHT_PASS` fragment built-in. Trying to use it in the project, however, the sprite would never show up. I tried setting the renderer to Compatibility, as the documentation said, but still, nothing happened.
Trying out the same code in Godot 3.5.1 it resulted in the expected output.

Sample code for the shader:
```gdshader
shader_type canvas_item;

void fragment() {
	COLOR = vec4(1.0, 1.0, 1.0, 0.0);
	
	if (AT_LIGHT_PASS)
		COLOR.a = 1.0;
}
```

### Steps to reproduce

In order to reproduce this in a brand new project:
1. Set the Render to Compatibility.
2. Create a new 2D node, with a Sprite2D and PointLight2D as children.
3. Assign a texture to each of them.
4. Set the light's Blend Mode to Mix.
4-a. Set the sprite's material to a new CanvasItemMaterial, and set its Light Mode to Light Only
4-b. Set the sprite's material to a new ShaderMaterial, and add the following code to the shader:
```gdshader
shader_type canvas_item;

void fragment() {
	COLOR = vec4(1.0, 1.0, 1.0, 0.0);
	
	if (AT_LIGHT_PASS)
		COLOR.a = 1.0;
}
```
5. Overlap the sprite and the light.

In Godot 3.5.1 this would lead to only the lit portion of the sprite being visible. In Godot 4, however, the sprite cannot be seen.

For the provided project, the aforementioned steps have already been carried out.

### Minimal reproduction project

[ReproductionProject.zip](https://github.com/godotengine/godot/files/10551523/ReproductionProject.zip)

**Comment by clayjohn** [comment]
``AT_LIGHT_PASS`` should be removed. Godot 3.x worked by rendering objects in multiple passes, one for the base sprite and then once for each light that intersects the object. In Godot 4 there is no light pass and all lights are drawn in a single pass. Since there is no light pass ``AT_LIGHT_PASS`` is always false.

**Comment by olivatooo** [comment]
And now there is no way anymore to make a object disappear on light pass

**Comment by ren-lv** [comment]
for @olivatooo and anyone else it may concern

uniform sampler2D SCREEN_TEXTURE : hint_screen_texture;
void light(){
    vec4 test = texture(SCREEN_TEXTURE, SCREEN_UV);
    LIGHT.a = 1.0;
    LIGHT.rgb = -COLOR.rgb + test.rgb;
}

it is still possible to make an object disappear on light pass. If you have a canvasmodulate active, multiply its value with -COLOR.rgb.
