### ISSUE TITLE
Physics behaving differently across platforms depending on FPS

### ISSUE THREAD

**Issue by bayleak** [godotengine/godot#7247]
OS: X11 & Android
Godot-Version: 2.1.1 official build

If a RigidBody gets tossed up in the air by another RigidBody (in 3D) the linear velocity in y-direction seems to be depending on the FPS the device reaches.
In my example the desktop version is running at a constant 60 FPS while the Android version was tested on a (sort of) low-end device, which is capable of playing the scene at ~40 FPS.
The Desktop version behaves as expected and the object which gets tossed up makes a (little) jump, while in the same scene on Android the object (most of the time) gets tossed up that high, that it leaves the game-platform (3-4 times higher).

If i limit the FPS to 40 with OS.set_target_fps AND limit the physics engine to 40 via fixed_fps in the physics section of the settings, the scene behaves equally on desktop and android.

In my opinion that shouldn't be the case, because (obviously) as a developer i don't know which device a gamer will run the game on. And droppings in the framerate can occur on any device depending on the scene-complexity.

Not shure if this is some sort of bug, but it is not the behaviour i'm expecting.

**Comment by tamkcr** [comment]
how are you tossing the bodies?

**Comment by bayleak** [comment]
The body gets tossed via an animation that gets played of the object the ball hits.
I can provide you with a demoscene as soon as i am back this evening.

**Comment by bojidar-bg** [comment]
Try setting the animationPlayer's mode to "fixed"

**Comment by bayleak** [comment]
Ok. That "fixed" fixed the problem. :)
Never mind. Can't believe i didn't notice that one.......... *facepalm*

**Comment by bojidar-bg** [comment]
Closing as archived, though we might as well have some warning about this (somehow...)

**Comment by Sslaxx** [comment]
This needs to be a documentation issue, then?

**Comment by bojidar-bg** [comment]
@Sslaxx You have an idea under which part of the docs it can be placed?
