### ISSUE TITLE
Typed arrays break resource deserialization when some elements are `null`

### ISSUE THREAD

**Issue by karljs** [godotengine/godot#72489]
### Godot version

v4.0.beta16.official [518b9e580]

### System information

MacOS 13.1

### Issue description

I have two custom resources (called `Collection` and `Item`) and `Collection` contains an exported property with the type `items: Array[Item]`.  My serialized `Collection.items` is length 2, the 0th element is an `Item` and the 1st is `null`. When I deserialize this resource, it will silently fail.

If I change the type annotation from `Array[Item]` to just `Array` and literally nothing else, it will start working. It seems like unless there's a way to specify a `Maybe` or `Optional` type, we have to allow `null`.

### Steps to reproduce

- Create two custom resources, `Collection` and `Item`.  `Collection` should have a property `@export items: Array[Item]`.
- Create an actual resource of type `Collection` and, using the inspector, add two elements to its `items` array
- Instantiate the 0th item with a new `Item`
- Do not instantiate the element at index 1
- Try to iterate over the array after a `load` and see that it will never deserialize that first element.
- Notice that if you literally _only_ change the type annotation of `items to be simply `Array`, you can now iterate over the items whether null or not.

### Minimal reproduction project

[repro.zip](https://github.com/godotengine/godot/files/10552957/repro.zip)

**Comment by AThousandShips** [comment]
Is this fixed by #72492

**Comment by vonagam** [comment]
Relevant #70657.

**Comment by karljs** [comment]
This appears to have been fixed by the recent typed array update.  Closing.
