### ISSUE TITLE
Groups not showing at editor when created using add_to_group()

### ISSUE THREAD

**Issue by Firemanarg** [godotengine/godot#72486]
### Godot version

4.0-beta16

### System information

Windows 10

### Issue description

When I try to add a node to a group, by calling function add_to_group() in a @tool script, the group is assigned but is not showing at the editor.

![image](https://user-images.githubusercontent.com/35619327/215923458-d620b8ca-26db-43e7-b982-9e099488aeb8.png)

```py
@tool
extends Node


func _enter_tree():
	print("Adding to group test")
	add_to_group("test")
	notify_property_list_changed()
	print("Groups: ", get_groups())


func _ready():
	add_to_group("test2")
	print("Groups: ", get_groups())
	pass
```
![image](https://user-images.githubusercontent.com/35619327/215923575-df31b218-59be-4b3c-93f5-6d208ce63be7.png)

![image](https://user-images.githubusercontent.com/35619327/215923602-b9e57586-91bd-4c9a-b109-d1b55f8d38f9.png)

**Note: If I try to add manually, it works fine.**

![image](https://user-images.githubusercontent.com/35619327/215923727-b5c23f11-4d02-4466-8fdb-d55374329687.png)
![image](https://user-images.githubusercontent.com/35619327/215923743-6c490cce-6a6b-416e-a2c3-eca8b2938952.png)

### Steps to reproduce

1. Create a new node
2. Create a new script to the node
3. Add @tool to the script
4. Call function add_to_group() inside _enter_tree() or _ready()

### Minimal reproduction project

N/A

**Comment by Zireael07** [comment]
Always been like that IIRC - same in 3.x

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/68739. This is done by design and will be documented by https://github.com/godotengine/godot/pull/68560.

**Comment by bikemurt** [comment]
Any update on this one? Trying to call add_to_group in the editor for use within a tool script and appears to not work

**Comment by AThousandShips** [comment]
See the comment right above 🙂

**Comment by bikemurt** [comment]
Sorry... Didn't see #68739. I will give that a shot

**Comment by AThousandShips** [comment]
It's nothing wrong, this is by design, the documentation just needs to be updated

**Comment by bikemurt** [comment]
It's working now for me - thanks for getting me to double check!
