### ISSUE TITLE
[Godot 4 beta 16] Viewport freezes after opening color picker dialog

### ISSUE THREAD

**Issue by MrDixioner** [godotengine/godot#72506]
### Godot version

4.0 beta 16 official

### System information

Linux Mint 21.1 Vera, GeForce GT 1030

### Issue description

After opening the color selection dialog (works on any node, 2D, 3D, UI, etc.), the viewport is frozen: moving when pressing the middle mouse button in the 2D window does not work, as well as all moving in the 3D window. Remain workable pressing the right mouse button and left. The selection of objects is possible, but this happens with a big delay. Freeze disappears after deleting the object on which the color was selected.

### Steps to reproduce

- Create a new project.
- Create any node (doesn't matter if it's 2D, 3D, etc.) where color selection is possible.
- Click on the color picker box and close this panel.
- Try moving the viewport with the middle mouse button.

### Minimal reproduction project

The project is not required.

**Comment by MrDixioner** [comment]
After the viewport is frozen, I close Godot and get errors in the terminal:

`ERROR: Attempted to free invalid ID: 0
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8382)
ERROR: Attempted to free invalid ID: 0
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8382)
ERROR: Attempted to free invalid ID: 0
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8382)
ERROR: Attempted to free invalid ID: 0
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8382)
ERROR: Attempted to free invalid ID: 0
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8382)
ERROR: Condition "!shader" is true.
   at: shader_free (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2453)
ERROR: Condition "!material" is true.
   at: material_free (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2686)
WARNING: 1 RID of type "Framebuffer" was leaked.
     at: _free_rids (drivers/vulkan/rendering_device_vulkan.cpp:8954)
WARNING: 4 RIDs of type "Texture" were leaked.
     at: finalize (drivers/vulkan/rendering_device_vulkan.cpp:9286)
`

**Comment by MrDixioner** [comment]
> Can you reproduce this after enabling **Single Window Mode** in the Editor Settings then restarting the editor?
When you turn on Single Window Mode, the viewport is not frozen, but it becomes difficult to select a color, because. when you click anywhere in the color picker, it closes immediately (you can enter a hexadecimal color value). After exiting Godot, the same errors that I posted above appear in the terminal.
> Also, are you using an X11 or Wayland session?
Session x11.

**Comment by Coder2195Text** [comment]
> When you turn on Single Window Mode, the viewport is not frozen, but it becomes difficult to select a color, because. when you click anywhere in the color picker, it closes immediately (you can enter a hexadecimal color value). After exiting Godot, the same errors that I posted above appear in the terminal.

https://github.com/godotengine/godot/issues/72409

**Comment by MrDixioner** [comment]
The error is gone and everything works great!
