### ISSUE TITLE
Really High Sprite contrast/Saturation 

### ISSUE THREAD

**Issue by CereEnder** [godotengine/godot#7250]
**Android 5.1 - Godot 2.1**

I am developing an android game, and I don't know why my sprites show in really high contrast in my device, but show well on my pc

I draw the sprites in Aseprite and saved them in png. I loaded them as ImageTexture (are TextureButton).

~~Here some screenshots: ~~

I don't know why, but my device screen show in high contrast, but the screenshots show well....

**Comment by volzhs** [comment]
can't see screenshots for me.

**Comment by Alex-doc** [comment]
Look your gamma/sRGB might be that.

**Comment by CereEnder** [comment]
On my phone or in the engine? 
I didnt post any screen shot because in there the sprites show well, but my device show a very high contrast. Only using Godot.

**Comment by Alex-doc** [comment]
On the image files. 
Try changing their colour space and/or the import/export mode

**Comment by CereEnder** [comment]
nevermind, I'll change output colors of the images and desire they work. Thank you very much.
