### ISSUE TITLE
GDScript being broken in many places after #72487

### ISSUE THREAD

**Issue by maiself** [godotengine/godot#72501]
### Godot version

394bb0ee2bcd863aed75e1c6799c4c8138dbf269

### System information

arch linux

### Issue description

#72487 broke my project in quite a few ways. I haven't yet had time to look into everything. Including here one example with assigning enum values.

```
SCRIPT ERROR: Parse Error: Invalid operands "Input::MouseMode" and "Input::MouseMode" for "==" operator.
SCRIPT ERROR: Parse Error: Cannot assign a new value to a constant.
```

Here is the full log output: https://pastebin.com/raw/TbdyfMSX

### Steps to reproduce

Add the following code to a new project:
```gdscript
Input.mouse_mode = Input.MOUSE_MODE_VISIBLE
```

### Minimal reproduction project

None yet

**Comment by maiself** [comment]
#72500 contains same bug.

**Comment by Chaosus** [comment]
cc @vnen

**Comment by HungryProton** [comment]
This PR also breaks anything using `get_node` or `$`, whether `@onready` is used or not.

```
@onready var my_node = $Button
```

Displays this error message despite using `@onready`
```
Parse Error: The default value is using "$" which won't return nodes in the scene tree before "_ready()" is called. Use the "@onready" annotation to solve this. (Warning treated as error.)
```

**Comment by vnen** [comment]
Thanks for finding this so quickly. I didn't have the time to test very thoroughly before sending the PR. I'll try to add these to the test cases when submitting a new version.
