### ISSUE TITLE
Mouse Middle Button Inconsistency

### ISSUE THREAD

**Issue by michael-nischt** [godotengine/godot#72507]
### Godot version

v4.0.beta16.official [518b9e580]

### System information

Linux + Windows

### Issue description

I would expect the `MOUSE_BUTTON_MIDDLE` react to same input in both cases:

**Event: reacts to the mouse-wheel being pressed**

```gdscript
var event_pressed : bool = false

func _input(event : InputEvent) -> void:
	if event is InputEventMouseButton:
		var mouse_button_event : InputEventMouseButton = event
		if mouse_button_event.button_index == MOUSE_BUTTON_MIDDLE:
			self.event_pressed = mouse_button_event.pressed
```

**Polling: Reacts to the left and right mouse buttons pressed simultaneously**

```gdscript
var poll_pressed : bool = false

func _process(delta : float) -> void:
	self.poll_pressed = (Input.get_mouse_button_mask() & MOUSE_BUTTON_MIDDLE) == MOUSE_BUTTON_MIDDLE	
```

I recommend both cases to react to the mouse-wheel.

### Steps to reproduce

1. Launch the sample project.
2. Press (and hold) the middle mouse button and observe the event captures it but input polling fails to.
3. Press (and hold) the left and right mouse buttons simultaneously and observe the polling captures it but input event fails to.

### Minimal reproduction project

[mouse-middle-button-inconsistency.zip](https://github.com/godotengine/godot/files/10556321/mouse-middle-button-inconsistency.zip)

**Comment by Sauermann** [comment]
Please use `MOUSE_BUTTON_MASK_MIDDLE` instead of `MOUSE_BUTTON_MIDDLE` in `func _process`.
You are comparing the mask with the button index, which are two distinct things.

**Comment by michael-nischt** [comment]
Thanks for spotting my mistake @Sauermann . Everything behaves as expected when using `MOUSE_BUTTON_MASK_MIDDLE`.
