### ISSUE TITLE
Animationtree set function no longer working

### ISSUE THREAD

**Issue by oxixxixo** [godotengine/godot#72526]
### Godot version

Godot 4.0 beta 14 and up

### System information

Windows 10 education 21H2, mobile renderer

### Issue description

Starting in beta 14 the term used for setting which state a transition node in an animationtreenodeblendtree is set to was changed from current to current_state. In beta 14 and up using neither current nor current_state seems to work. In beta 13 using current would work but beta 14 and up return the error:
_"Invalid set index 'parameters/Transition/current_state' (on base: 'AnimationTree') with value of type 'float'_
using typoeof() shows it's of type string though using '1' 'state 1' 'state_1' or changing the states name to something like 'hi' (doing so will also break the transition request in the inspector) and using that makes no difference (though doesn't return an error).

![image](https://user-images.githubusercontent.com/61514710/216112952-8c836992-957e-4f08-9494-36cc5eb820e5.png)
image taken from: https://docs.godotengine.org/en/latest/tutorials/animation/animation_tree.html#blend-tree

### Steps to reproduce

create a project with an animationtree and animation player as children of the root node. Add an animationtreenodeblendtree to the animationtree and set up a transition like shown below. Then try to transition between animations in gdscript.

![image](https://user-images.githubusercontent.com/61514710/216118639-3ff23764-4b34-469f-a055-75376fb85f16.png)

### Minimal reproduction project

[animationtree bugtest 2-1-23.zip](https://github.com/godotengine/godot/files/10559629/animationtree.bugtest.2-1-23.zip)

**Comment by TokageItLab** [comment]
It is changed to `transition/request` in #71418 to restart same state, the current documentation is out of sync.
