### ISSUE TITLE
SceneTreeTween that were set on loop crashes the game after freeing an entire scene

### ISSUE THREAD

**Issue by rockgem** [godotengine/godot#72523]
### Godot version

3.5.1

### System information

Windows 11

### Issue description

I have an object that creates a scenetreetween and it is set on loop but as soon as the parent scene of the object it crashes the app

### Steps to reproduce

1. Create a node
2. attach a script and create a SceneTreeTween object
3. set the tween on loop by using set_loop()
4. free the parent scene or the entire scene

### Minimal reproduction project

![1](https://user-images.githubusercontent.com/63050183/216105160-a594d7b5-817a-4046-9779-4eca0102da4e.png)
![2](https://user-images.githubusercontent.com/63050183/216105169-332452ee-c9a4-4614-afba-9b798eb073dc.png)

**Comment by Zireael07** [comment]
Why close?

**Comment by rockgem** [comment]
> 

i read the documentation that says it will crash the game when it is not explicitly called via kill(). so i thought this wasn't a bug at all.
