### ISSUE TITLE
Camera2D stays active after its node has been freed; can lead to crashes

### ISSUE THREAD

**Issue by h0lley** [godotengine/godot#72529]
### Godot version

v4.0.beta.custom_build [0a9e6e478]

### System information

Ubuntu, Nvidia, Vulkan

### Issue description

When a Camera2D is freed - either explicitly or by being a child of a scene that is being switched away from via a method like `get_tree().change_scene_to_file()` - then this camera somehow stays active instead of Godot properly switching to no-camera-mode.

`get_viewport().get_camera_2d()` then returns all sorts of funny things from `<Freed Object>`  (it's supposed to return `null`) to arbitrary nodes of the current scene (not cameras).

This can lead to crashes.

### Steps to reproduce

checkout the MRP.

note that the "Go to scene 2" button switches places after pressing it.
that is because a camera is still active that does not exist in the current tree.

restart it a couple of times and spam the "Go to scene 2" button.
notice the garbage output.

### Minimal reproduction project

[godot_4_camera_bug.zip](https://github.com/godotengine/godot/files/10560455/godot_4_camera_bug.zip)

**Comment by Cronos87** [comment]
I can complete this issue by saying that I'm developing a shmup game where a camera is moving from left to right; if I leave my scene with the moving camera, the next scenes won't show up, and I will have a black screen because the content is on the left 😅

**Comment by KoBeWi** [comment]
Can't reproduce
![image](https://user-images.githubusercontent.com/2223172/216172777-2e2cfd10-4bfe-4dbc-b55a-fcbe5e7c7786.png)
This code ensures that the camera is cleared when it leaves tree (including when freed):
https://github.com/godotengine/godot/blob/0a9e6e478e3183d7bf3c5cb895c706bc6275d3ea/scene/2d/camera_2d.cpp#L262-L265

**Comment by MewPurPur** [comment]
> to arbitrary nodes of the current scene (not cameras)

Not just nodes, Godot just thought that my camera was an AudioStreamPlaybackOggVorbis

**Comment by KoBeWi** [comment]
If anyone wants a workaround until beta 18, attach this to your camera:
```GDScript
extends Camera2D
func _exit_tree() -> void:
	for g in get_groups():
		remove_from_group(g)
```
