### ISSUE TITLE
No way to start Profiler before starting game

### ISSUE THREAD

**Issue by cosmoddd** [godotengine/godot#72524]
### Godot version

4.0 Beta 16

### System information

Windows 11  Vulkan

### Issue description

In the online manual, it states:

> To begin profiling, click on the Start button in the top-left. Run your game and data will start appearing. You can also start profiling at any time before or during gameplay, depending on if you want.

I want to be able to profile my game's startup time to suss out any bottlenecks during startup.  
However, the option to start profiling before the game as it starts is not possible in the current 4.0 build.  In 3.x, this option is available.

![2023-02-01 11_20_50-(_) Test - Godot Engine](https://user-images.githubusercontent.com/9627628/216101680-3c1fb6b8-62ea-4a19-95d7-ed2b334d7719.png)

### Steps to reproduce

Click on the Debugger tab at the bottom of the screen.
Click on the Profiler tab in the Debugger window.
Notice that you cannot press "Start".
Start any scene.
Notice that you can now press "Start"
Stop the scene.
Notice that you can no longer press "Start" on the profiler.

### Minimal reproduction project

This issue is apparent regardless of the project.

**Comment by Zireael07** [comment]
Related to #71111 (profiler button being grayed out)

**Comment by cosmoddd** [comment]
As this is the 4.0 build (# 71111 is still on 3.x) and the Profiler _does_ work once the game is running, I'm not sure the two issues are related.

**Comment by Zireael07** [comment]
Whoops, didn't notice THAT. Right.

**Comment by Calinou** [comment]
The documentation is incorrect and should be reworded.

The lack of autostart functionality is being tracked in https://github.com/godotengine/godot-proposals/issues/6017.

**Comment by lostminds** [comment]
I think this was changed in https://github.com/godotengine/godot/pull/70151 which fixed some other inconsistencies with the profiler Start/Stop buttons. 
Personally I think implementing an autostart feature would be a better solution, but I'm guessing just allowing it to be started again ahead of launch would be an easier temporary fix as this is how it used to work.

**Comment by stmSi** [comment]
@lostminds  There is a  [PR](https://github.com/godotengine/godot/pull/70766) for this feature. I am waiting for review.

**Comment by Calinou** [comment]
This could technically be implemented by the Start button enabling [autostart](https://github.com/godotengine/godot/pull/96759) if it's pressed while the project isn't running (only for the current editor session).
