### ISSUE TITLE
Godot Linux version 15/16 open then crashes shorly after

### ISSUE THREAD

**Issue by Kiwi-the-Cat** [godotengine/godot#72527]
### Godot version

4.0 dev beta 15/16

### System information

fedora linux, gnome de, Nvidia gtx 1650 mobile, Intel i5 9300H, 16Gb dram

### Issue description

Shortly after opening godot, the app closes itself. There is no error.

### Steps to reproduce

Open the Linux x86_64 version, wait approximately a half second, and watch it close.

### Minimal reproduction project

It's just the executable

**Comment by Yagich** [comment]
Can't reproduce on Manjaro/KDE. Are you on X11 or Wayland? Can you try running the binary with `--verbose`?

**Comment by Kiwi-the-Cat** [comment]
I was on Gnome on Xorg, I downgraded my Libx11 and it's working properly now

**Comment by akien-mga** [comment]
Duplicate of #69352
