### ISSUE TITLE
[Godot4] How to rotate tile in tilemap? Alternative Tile can't replace rotation.

### ISSUE THREAD

**Issue by CheapMeow** [godotengine/godot#72525]
### Godot version

v4.0.beta16.official [518b9e580]

### System information

Windows11, GLES3, RTX 2060

### Issue description

Usually, atlas is a collection of tiles, each of which doesn't have a rotation alternatives. So it is convenient to rotate tile in game editor.

In Godot 3, you can press "S" key to rotate the tile for 90 degrees, but in Godot 4, pressing "S" will link to scale tool.

If you want to rotate the tile in Godot4, you have two choices.

1. Use Alternative Tile. But you can only use filp H and filp V. Sometimes filp H and filp V doesn't work the same as rotation, see image that a cube is on the top of a tile. You can never get a tile that cube is on the right or left. And it is a burden to make 3 rotation Alternative Tiles for each tiles in atlas
2. Modify atlas. Manually rotate each tiles in image editor and make a big atlas that contains one original atlas and 3 rotation copies. It seems stupid.

So is there a way to rotate tile easily in Godot4?

![image](https://user-images.githubusercontent.com/88229072/216113641-2db45c8d-6084-446b-9d06-37828968db2c.png)

### Steps to reproduce

None

### Minimal reproduction project

None

**Comment by KoBeWi** [comment]
Yeah you need to use transpose.
btw there are plans to make alternative tiles easier to use.
There's also this proposal: https://github.com/godotengine/godot-proposals/issues/5158

Closing, as there is no bug here.

**Comment by CheapMeow** [comment]
Transpose can equal to rotate 90 degrees? I can't make it, what's wrong...

![input](https://user-images.githubusercontent.com/88229072/216231572-778b7af5-613e-4ef6-a93b-0d836d94f906.gif)

**Comment by Gnumaru** [comment]
You're perfectly right, it doesn't work at all. I've opened an issue: https://github.com/godotengine/godot/issues/72574
