### ISSUE TITLE
MenuBar breaks if the windows content_scale_mode != disabled and the window is resized

### ISSUE THREAD

**Issue by whiteshampoo** [godotengine/godot#72532]
### Godot version

4.0 beta 16

### System information

Windows 11 (does not seem to matter)

### Issue description

MenuBar reacts to mouseclicks strange, if content_scale_mode is not disabled and the window is resized/in fullscreen.
It looks like the problem is worse on  the upper-half of the menu-button.

![menubar_1](https://user-images.githubusercontent.com/2029198/216148196-2d711015-ed39-4e48-973f-9b76a849cefe.gif)

![menubar_2](https://user-images.githubusercontent.com/2029198/216148979-e6336895-43af-45ec-b5dd-39ea0a23eb32.gif)

### Steps to reproduce

Use a MenuBar, set the content_scale_mode (stretch mode) to cansvas_items or viewport and resize/fullscreen the window.

### Minimal reproduction project

[MenuTest.zip](https://github.com/godotengine/godot/files/10561138/MenuTest.zip)

**Comment by whiteshampoo** [comment]
(does also happen in beta 17)

**Comment by Sauermann** [comment]
Can confirm this on Linux. Beta 1 also had this problem.

**Comment by zjf0123** [comment]
I also encountered this problem. 
System: win10
Version: godot4,0

**Comment by zjf0123** [comment]
Through some attempts, I found that this bug can be triggered stably: 
1.Set the display/window/stretch/mode to canvas_items in the project settings.
2. Set display/window/size/viewport_ Width and display/window/size/window_width_override to different values.
3. If the window size is adjusted when running a scene containing menubar, this bug will be triggered.
