### ISSUE TITLE
Godot 4 Beta 17: Shader doesn't compute after project reload

### ISSUE THREAD

**Issue by ShortsKing** [godotengine/godot#72538]
### Godot version

4.0 Beta 17

### System information

Windows 10 Pro w/ AMD Radeon R7 Graphics, using Forward+

### Issue description

A shader I wrote works perfectly until I reload the editor

### Steps to reproduce

1. Make a Mesh
2. Within the Mesh, create a StandardMaterial with an albedo texture
3. convert the StandardMaterial to a ShaderMaterial
4. Observe that the shader works correctly
5. Save and Reload the project
6. Observe that the shader no longer works correctly

### Minimal reproduction project

Open and follow the steps. A mesh and albedo texture are provided.

[project.zip](https://github.com/godotengine/godot/files/10561816/project.zip)

**Comment by clayjohn** [comment]
Traced this back to Beta 15. So it is most likely a regression from https://github.com/godotengine/godot/pull/71797

**Comment by QbieShay** [comment]
What happens is that converting any material to shader still sends the right uniforms to the GPU but the parameters don't get the previous values. So if you save the scene and reopen it, all will have default values and not work anymore.

**Comment by Zireael07** [comment]
Yes
