### ISSUE TITLE
Top Menu Bar doesn't work on single window mode while on the Script tab

### ISSUE THREAD

**Issue by wokeraccoon** [godotengine/godot#72535]
### Godot version

v4.0.beta17.official [c40020513]

### System information

Fedora Linux 37 Wayland, AMD RX 6600, AMD Ryzen 7 3700x

### Issue description

When using Godot 4 in single window mode, the top menu bar seems to not detect clicks on the drop down menus while on the "Script" tab. Switching to any other tab or to multi window mode fixes the issue.
[Screencast from 2023-02-01 16-06-10.webm](https://user-images.githubusercontent.com/13603525/216163861-cde10e93-f039-42ca-a5a3-72f767d19a5d.webm)

### Steps to reproduce

1. Open any project and switch Godot to single window mode on Editor settings > Interface > Editor. Restart Godot.
2. On either the 2D/3D tab, click on the top menu bar and try to open any window such as `Project Settings` or toggling  an option in `Debug`. The drop down menus should work as usual
3. Switch to the `Script` tab in the editor and try the same actions as in step 2.

### Minimal reproduction project

N/A

**Comment by YuriSizov** [comment]
Can't confirm on Windows with RC2. Does it still happen for you?

**Comment by wokeraccoon** [comment]
Nope, it no longer happens on rc2 on Fedora
