### ISSUE TITLE
Godot can't find scene when lauching editor from KDE application menu

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#72543]
### Godot version

4.0 beta 17

### System information

Debain 11 KDE Plasma 5.20.5

### Issue description

Launching the recently released godot 4.0 beta 17 from kde plasma menu on debain 11 fails with this...
![image](https://user-images.githubusercontent.com/2453707/216174704-feb06a70-f46a-472b-9566-937ee8aa6aa5.png)

It runs fine launching it directly by clicking on the executable.

### Steps to reproduce

- Move your...
`/home/username/Downloads/Godot_v4.0-beta17_linux.x86_64` 
to 
`/home/username/.local/bin/Godot_x4.0/Godot_v4.0.x86_64`

- Add it to your KDE plasma 5 applications menu...
![image](https://user-images.githubusercontent.com/2453707/216174345-48412aff-1db5-4be1-a0d5-5832ef2234be.png)

- Try to run it from menu.

### Minimal reproduction project

There is none

**Comment by dalexeev** [comment]
Can you show the `.desktop` file? The following minimal `godot4.desktop` works fine for me:

```desktop
#!/usr/bin/env xdg-open
[Desktop Entry]
Type=Application
Name=Godot 4
Exec=godot4
Icon=godot4
Terminal=false
```

```
~/.local/bin/godot4
~/.local/share/icons/godot4.png
~/.local/share/applications/godot4.desktop
```

**Comment by Shadowblitz16** [comment]
> Can you show the `.desktop` file? The following minimal `godot4.desktop` works fine for me:
> 
> ```desktop
> #!/usr/bin/env xdg-open
> [Desktop Entry]
> Type=Application
> Name=Godot 4
> Exec=godot4
> Icon=godot4
> Terminal=false
> ```
> 
> ```
> ~/.local/bin/godot4
> ~/.local/share/icons/godot4.png
> ~/.local/share/applications/godot4.desktop
> ```

```
[Desktop Entry]
Comment=
Exec=/home/shadowblitz16/.local/bin/Godot_x4.0/Godot_v4.0.x86_64
GenericName=FOSS 2D and 3D Game Engine
Icon=/home/shadowblitz16/.local/bin/Godot_x4.0/Godot_x4.0.png
Name=Godot
NoDisplay=false
Path[$e]=
StartupNotify=true
Terminal=0
TerminalOptions=
Type=Application
X-KDE-SubstituteUID=false
X-KDE-Username=
```

I just use the kde application gui to add it and it worked fine for godot 4.0 beta 15

**Comment by Shadowblitz16** [comment]
I just tried and deleting the menu item and re adding it from scratch doesn't change anything

**Comment by akien-mga** [comment]
Sounds like you have a `project.godot` file in your `$HOME`, or wherever the Godot process is started from

**Comment by Shadowblitz16** [comment]
really odd I don't remember saving a godot project to my home folder.

anyways ty.
