### ISSUE TITLE
Typed variables can't be assigned to a null value

### ISSUE THREAD

**Issue by prominentdetail** [godotengine/godot#72545]
### Godot version

v4.0.beta.custom_build [1b131ac49]

### System information

Windows 10

### Issue description

In previous versions you could assign a null value to a typed variable, but in beta17 now I get this error.

Line 7:Cannot assign a value of type "null" as "Dictionary".
Line 7:Value of type "null" cannot be assigned to a variable of type "Dictionary".

![image](https://user-images.githubusercontent.com/10412778/216177366-4ead8c6b-856b-4aee-86d3-10bc626dcb7f.png)

### Steps to reproduce

open the project and try to assign null to a typed variable.

### Minimal reproduction project

[dictionaryNullBug.zip](https://github.com/godotengine/godot/files/10562258/dictionaryNullBug.zip)

**Comment by Shadowblitz16** [comment]
lets hope this means we have nullables/optionals

**Comment by KoBeWi** [comment]
If it worked before it was a bug. Dictionary is not nullable. You can assign a `null` only to Object-derived variables.
There's a proposal for nullables: https://github.com/godotengine/godot-proposals/issues/162
