### ISSUE TITLE
Broken LightmapGI gizmo icon

### ISSUE THREAD

**Issue by msiedlarek** [godotengine/godot#72568]
### Godot version

v4.0.beta17.mono.official [c40020513]

### System information

macOS 13

### Issue description

After adding LightmapGI to a 3D scene instead of its gizmo it shows a broken resource (?) icon. Effectively, it cannot be used. This can be easily reproduced in new empty projects.

![screenshot](https://user-images.githubusercontent.com/133448/216259276-d7fe1075-ef42-4306-9a1e-f6e05753780a.png)

### Steps to reproduce

Create a new project with a 3D scene, add a LightmapGI node

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
I can confirm this on 4.0.beta 44c0bfc94.

However, this does not prevent using LightmapGI – the issue is purely visual and is only visible in the editor.
