### ISSUE TITLE
Re-import option for Audio Sample disappears from context-menu

### ISSUE THREAD

**Issue by williamd1k0** [godotengine/godot#7256]
**Operating system or device - Godot version:**

Windows 10 x64
Godot 2.1.1 and master 959683c3d8f7aaa7469d5758c7698e0da108b406

**Issue description** (what happened, and what was expected):

It happens sometimes after a re-import, the re-import option disappears from context-menu for no apparent reason.

**Steps to reproduce:**
1. Import a audio sample.
2. Try to re-import sample changing some options (max rate, compress etc).

>Removing .smp file and importing again solves it (until it happens again).

**Comment by bojidar-bg** [comment]
Can someone try to confirm (maybe on master)?

**Comment by bojidar-bg** [comment]
Buuump.

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by williamd1k0** [comment]
Oh, I had already forgotten about this issue ><
Godot 3 has a different import system so I think this one is not applicable to the current stable.
I will try to reproduce this anyway (I've not tried it on v2.1.5 yet).

**Comment by williamd1k0** [comment]
Yep, it still happens in 2.1.5, but not applicable to the current stable.

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.
