### ISSUE TITLE
Autocomplete gets in the way when writing numbers

### ISSUE THREAD

**Issue by wokeraccoon** [godotengine/godot#72565]
### Godot version

v4.0.beta17.official [c40020513]

### System information

Fedora Linux 37 Wayland, AMD RX 6600, AMD Ryzen 7 3700x

### Issue description

When writing numbers, Godot's autocomplete gets on the way suggesting keyboard enums (i.e. KEY_0). Here's a video explaining better the issue: 
[Screencast from 2023-02-01 23-29-34.webm](https://user-images.githubusercontent.com/13603525/216232512-76a3b8b2-045e-44fc-bbe3-d5a27933eb09.webm)

### Steps to reproduce

Open a script and type any number from 0 to 10. Godot will try to suggest immediately anything that has that number. A work around is to accept the suggestion then CTRL - Z to revert to the original number

### Minimal reproduction project

N/A

*Bugsquad edit:* Keywords for search: code completion, autocompletion, intellisense, numerical.

**Comment by Calinou** [comment]
An easy fix is likely to make autocomplete never pop up if your cursor is on a numerical value.
