### ISSUE TITLE
Godot 4 beta 16, 17 external C# editor not working

### ISSUE THREAD

**Issue by pomoshnik** [godotengine/godot#72569]
### Godot version

4.0 beta 16

### System information

Windows 10, GLES3

### Issue description

Godot 4 beta 16, 17 external C# editor not working. With any settings, the internal editor opens. Back to beta 15 everything is fine there.

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by Flavelius** [comment]
It works for me in 16 and 17 with jetbrains rider

**Comment by jmpichardo** [comment]
In Godot > Editor > Editor settings > Mono > Editor > External Editor reset the value and select the desired editor again.
Then, close the project, remove the .godot folder from the project, then open again and try again.

**Comment by pomoshnik** [comment]
> В Godot > Редактор > Настройки редактора > Моно > Редактор > Внешний редактор сбросил значение и снова выбрал нужный редактор. Затем закройте проект, удалите папку .godot из проекта, затем снова откройте и повторите попытку.

Thank you very much. This helped me.
