### ISSUE TITLE
Tiny Android "one-click deploy" icon on HiDPI display

### ISSUE THREAD

**Issue by igorskuhar** [godotengine/godot#7257]
**Operating system or device - Godot version:**
Mac OS X 10.11.4 (MBP 2015 Retina) - Godot v2.1.1.stable

**Issue description** (what happened, and what was expected):
When Godot Editor is launched on HiDPI display (MBP's retina in my case) all icons scale well except for Android's "one-click deploy" icon which remains very small.

<img width="400" alt="tiny_android_icon" src="https://cloud.githubusercontent.com/assets/5592468/20947836/55415298-bc11-11e6-8fa6-d33a359f8deb.png">

**Steps to reproduce:**
1. Launch the Godot Editor on HiDPI display with Android "one-click deploy" set up.

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Calinou** [comment]
I can still reproduce this issue as of commit https://github.com/godotengine/godot/commit/59cdc5eb9d8c41bffe30a9cd02a2c58e2cdbd973.

**Editor scaling set to 200% (hiDPI):**

![android_button_hidpi](https://user-images.githubusercontent.com/180032/38471905-0a8dd90a-3b78-11e8-92c7-b365235860c3.png)

**Editor scaling set to 100% (loDPI):**

![android_button_lodpi](https://user-images.githubusercontent.com/180032/38471904-091433b2-3b78-11e8-88a7-3ae3f33f893c.png)

**Comment by djrm** [comment]
those icons are not svgs, they are rasters included in each platform folder, so im not sure if we should include them in the icons workflow.

**Comment by Calinou** [comment]
I guess we should find or create SVG versions of those then.
