### ISSUE TITLE
OpenGL: Transposing a tile in the tileset has no effect

### ISSUE THREAD

**Issue by Gnumaru** [godotengine/godot#72574]
### Godot version

4.0.beta17

### System information

windows 10, nvidia graphics, gl compatibility renderer

### Issue description

Checking or unchecking the 'transpose' checkbox in a tile alternative in the tileset editor has absolutely no visual effect. This was found by another user here https://github.com/godotengine/godot/issues/72525
This only happens in the compatibility renderer. I've tested with the vulkan (mobile and forward) and both worked fine.

### Steps to reproduce

See attached video:

https://user-images.githubusercontent.com/5783414/216274035-0acbe609-52b0-4dd8-90c1-b8970f248231.mp4

### Minimal reproduction project

[TileMapTransposeWontWork.zip](https://github.com/godotengine/godot/files/10566912/TileMapTransposeWontWork.zip)

### Work Around

User vulkan instead of opengl. Or, The user could create a specific tilemap node for rotated tiles and rotate the entire node by 90 or -90 degrees to achieve the desired result.

**Comment by AThousandShips** [comment]
Caused by incorrect mirroring applied in the code, will look into shortly

**Comment by AThousandShips** [comment]
I cannot replicate this on master

**Comment by KoBeWi** [comment]
Same as this issue #56390
But it was about Vulkan, so indeed might be renderer-related.
