### ISSUE TITLE
Undo is incomplete for TileMap paint & bucket actions, when TileSet is/has been opened in inspector

### ISSUE THREAD

**Issue by cagibi-dev** [godotengine/godot#72598]
### Godot version

4.0-beta16 & beta17

### System information

Linux Mint 20.3 x86_64 xfce

### Issue description

When painting tiles with the Paint (D) action, then pressing Ctrl-Z to undo, the first painted tile is still here.

![Peek 02-02-2023 14-28](https://user-images.githubusercontent.com/45714685/216338106-20e5d0cc-7f13-4893-95d8-f805e7516a37.gif)

Interestingly, this only happens if the TileSet resource has been unfolded at least once in the inspector. If I reload the current project and re-select the TileMap node, I don't encounter the bug until I unfold its TileSet resource in the inspector. I can still reproduce the bug when re-closing the resource.

The unfolded TileSet doesn't need to belong to *this TileMap* (or even any TileMap) to enable the bug. But it has to be *a TileSet*, not another resource.
I thought this has to do with the TileSet drawer (in the editor's bottom bar) being opened, but manually opening it does not enable the bug either.

Also happens in Eraser mode. Does not happen when drawing/erasing a Line or Rect.
More importantly, this also happens for the Bucket tool. This time, the whole region escapes undoing instead of just one tile.

### Steps to reproduce

- Create a TileMap node
- Create a TileSet for it; the TileSet resource starts unfolded in the inspector
- Add any tiles by dropping an image (such as icon.svg) in the TileSet drawer
- Select the "TileMap" drawer
- Select the "Paint" (pencil) tool
- Paint tiles
- Press Ctrl+Z
- Notice that the first painted tile is still there

### Minimal reproduction project

[undotest.zip](https://github.com/godotengine/godot/files/10569342/undotest.zip)

**Comment by zurasuta** [comment]
I'm using v4.0.rc2.official [d2699dc7a] and this happens even when the TileSet has not been unfolded. When I press Ctrl+Z sometimes it doesn't do nothing and sometimes it undoes a lot of stuff and sometimes it undoes things on the inspector instead like changing Tilemap layers properties.

https://user-images.githubusercontent.com/25066388/219517222-13da7c67-4ded-4412-bdb8-3ba671a88946.mp4

**Comment by cagibi-dev** [comment]
This bug was fixed in RC3, for me.

@zurasuta Do you still encounter it?

**Comment by zurasuta** [comment]
@cagibi-dev I just played around with it for a while and it seems to be working properly!

**Comment by Calinou** [comment]
Closing per the above comments.
