### ISSUE TITLE
Deleting Shader file in FileSystem panel leaves shader file open for editing in Shader Editor tab

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot#72595]
### Godot version

4.0b17

### System information

macOS 13.2

### Issue description

If you have a shader resource open in the Shader Editor (Visual shader like below or regular code-based Shader) and then delete this shader file from the FileSystem panel, the Shader editor is not updated. I would expect the shader editor to close the file (perhaps with a warning) and update the file list. 

If you then save the project the name of the file in the Shader Editor changes to [unsaved]. However, it does not prompt you if you wish to save this open unsaved file if you close it or the project, so it feels like a ghost file of sorts instead of reverting the file to an unsaved new file state (as perhaps intended?). 
If you try to save again you instead get an error in the output `Can't save resource to empty path. Provide non-empty path or a Resource with non-empty resource_path.`

https://user-images.githubusercontent.com/17763524/216334632-84fd19da-cd13-442f-98a8-d96a07386f30.mov

There also seems to be a similar issue with the Theme editor tab. Where it will stay open even if the resource you're editing has been deleted. 

### Steps to reproduce

- Open a shader resource in the Shader Editor tab
- Delete the Shader file from the FileSystem panel
- Observe that nothings seems to have happened in the Shader Editor
- Save the project and see the Shader editor filename change to [unsaved] but not prompting to be saved on close

### Minimal reproduction project

This is an editor UI issue so I think any project will be the same.

**Comment by jsjtxietian** [comment]
Looks like when the file itself is deleted, godot will clear the path cache and so shader editor plugin will see a shader with empty path cache as a built-in shader.
