### ISSUE TITLE
"phantom viewport" when launching maximized interferes with mouse input

### ISSUE THREAD

**Issue by SpaceAttorney** [godotengine/godot#72596]
### Godot version

4.0.beta17

### System information

Windows 10/11

### Issue description

When project settings are set to "Maximized", "Fullscreen", or "Exclusive Fullscreen", and the base viewport size is smaller than the resulting window size, the following occurs:
Moving the mouse into the top left of the window (into a region the size of the base viewport size) causes mouse enter/exit behavior (including both Controls and Node2D object picking) to stop working outside of that region. Clicking on Controls still works. Resizing the window fixes the error until the project is closed.

### Steps to reproduce

- Make new project
- Set base viewport size in Project Settings to something smaller than your monitor resolution
- Set the window's launch mode to Maximized, Fullscreen, or Exclusive Fullscreen
- Add a few Controls to the scene
- Run the project
- Hover over the top left portion of the screen
- Hover outside of the top left portion of the screen

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/10569454/Test.zip)

**Comment by Calinou** [comment]
cc @Sauermann
