### ISSUE TITLE
HiDPI Mode issue with multiple monitors

### ISSUE THREAD

**Issue by igorskuhar** [godotengine/godot#7259]
**Operating system or device - Godot version:**
Mac OS X 10.11.4 (MBP 2015 Retina) - Godot v2.1.1.stable

**Issue description** (what happened, and what was expected):

I would like to move the Editor to my external 27" display (2560x1440).
When I click the Godot's dock icon, the Project Manager is launched first.
Then, no matter which display is Project Manager on, after launching the project, Editor will always open on my internal MBP's display.
Editor looks good on retina with HiDPI Mode set to both Auto and HiDPI.
But when I move the Editor's window to external display, it becomes unusable:

![doubled_editor](https://cloud.githubusercontent.com/assets/5592468/20948945/01c54074-bc17-11e6-8a23-2d0ab2ccadc4.png)

If I move the Editor's window back to retina it becomes fine again.
Setting HiDPI Mode to LoDPI doesn't fix the issue, everything just looks super tiny on retina and still broken on LoDPI display.
Is there a way to launch Editor directly on external display?
I expected the "Auto" mode to handle displays automatically.
 
**Steps to reproduce:**
1. Launch Godot project via Godot Project Manager.
2. Move the Editor from HiDPI display (for example retina) to any other LoDPI display.
3. Editor will become scaled and unusable.

**Comment by jcs224** [comment]
Yep, experiencing this as well 😬

**Comment by Zireael07** [comment]
@jcs224 You might want to try 2.1.4 rc?

**Comment by jcs224** [comment]
@Zireael07 that seems to work! Thanks!

It's still a little weird, but if I move or resize the window after I move it to the LoDPI screen, it fixes it in 2.1.4 but not 2.1.3. I think it's good enough. You might want to give it a try, @igorskuhar

**Comment by jcs224** [comment]
Evidence of fix
![godot_fix](https://user-images.githubusercontent.com/6226188/29803736-2b15d052-8c3b-11e7-9d63-b96ff875be8e.gif)

**Comment by akien-mga** [comment]
Fixed by #9953.
