### ISSUE TITLE
godot crashes with no console output 

### ISSUE THREAD

**Issue by qwe3121** [godotengine/godot#72597]
### Godot version

Godot 4 beta 17

### System information

Windows 11, Vulcan, GTX 1050 TI (driver geforce game ready 528.24)

### Issue description

godot crashes with no console output when trying to open any scene from FileSystem window or from my main scene using "Open in Editor" button
![image](https://user-images.githubusercontent.com/95754732/216338273-527df1c0-44eb-4b37-8332-7d5911851c56.png)
first it crashes even when I just trying to open the project
then I delete .godot folder and it launched
but with issue which is im describing
then I remade project to create new project.godot file and it launched with no issue
then I do my project settings, save godot and then reopen my project
and here it is the same issue

### Steps to reproduce

idk for sure

### Minimal reproduction project

honestly dont want to past my entire project here, ill past only project.godot file here and your requests while conversation
[file.zip](https://github.com/godotengine/godot/files/10569502/file.zip)

**Comment by qwe3121** [comment]
Also project was created at beta 1-2-3 maybe, and this is first time I see problems like this (i was using all betas)

**Comment by qwe3121** [comment]
logs file:

Godot Engine v4.0.beta17.official.c40020513 - https://godotengine.org
Vulkan API 1.3.224 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1050 Ti
 
USER ERROR: Disabling a CollisionObject node during a physics callback is not allowed and will cause undesired behavior. Disable with call_deferred() instead.
   at: _apply_disabled (scene/2d/collision_object_2d.cpp:233)
USER ERROR: Disabling a CollisionObject node during a physics callback is not allowed and will cause undesired behavior. Disable with call_deferred() instead.
   at: _apply_disabled (scene/2d/collision_object_2d.cpp:233)
USER ERROR: Disabling a CollisionObject node during a physics callback is not allowed and will cause undesired behavior. Disable with call_deferred() instead.
   at: _apply_disabled (scene/2d/collision_object_2d.cpp:233)
USER ERROR: Disabling a CollisionObject node during a physics callback is not allowed and will cause undesired behavior. Disable with call_deferred() instead.
   at: _apply_disabled (scene/2d/collision_object_2d.cpp:233)
USER ERROR: Disabling a CollisionObject node during a physics callback is not allowed and will cause undesired behavior. Disable with call_deferred() instead.
   at: _apply_disabled (scene/2d/collision_object_2d.cpp:233)
USER ERROR: Timer was not added to the SceneTree. Either add it or set autostart to true.
   at: start (scene/main/timer.cpp:109)
USER ERROR: Disabling a CollisionObject node during a physics callback is not allowed and will cause undesired behavior. Disable with call_deferred() instead.
   at: _apply_disabled (scene/2d/collision_object_2d.cpp:233)
USER ERROR: Disabling a CollisionObject node during a physics callback is not allowed and will cause undesired behavior. Disable with call_deferred() instead.
   at: _apply_disabled (scene/2d/collision_object_2d.cpp:233)
USER ERROR: Disabling a CollisionObject node during a physics callback is not allowed and will cause undesired behavior. Disable with call_deferred() instead.
   at: _apply_disabled (scene/2d/collision_object_2d.cpp:233)
USER ERROR: Disabling a CollisionObject node during a physics callback is not allowed and will cause undesired behavior. Disable with call_deferred() instead.
   at: _apply_disabled (scene/2d/collision_object_2d.cpp:233)
USER ERROR: Disabling a CollisionObject node during a physics callback is not allowed and will cause undesired behavior. Disable with call_deferred() instead.
   at: _apply_disabled (scene/2d/collision_object_2d.cpp:233)
USER ERROR: Timer was not added to the SceneTree. Either add it or set autostart to true.
   at: start (scene/main/timer.cpp:109)
USER ERROR: Disabling a CollisionObject node during a physics callback is not allowed and will cause undesired behavior. Disable with call_deferred() instead.
   at: _apply_disabled (scene/2d/collision_object_2d.cpp:233)
USER ERROR: Disabling a CollisionObject node during a physics callback is not allowed and will cause undesired behavior. Disable with call_deferred() instead.
   at: _apply_disabled (scene/2d/collision_object_2d.cpp:233)
USER ERROR: Disabling a CollisionObject node during a physics callback is not allowed and will cause undesired behavior. Disable with call_deferred() instead.
   at: _apply_disabled (scene/2d/collision_object_2d.cpp:233)
USER ERROR: Timer was not added to the SceneTree. Either add it or set autostart to true.
   at: start (scene/main/timer.cpp:109)
USER ERROR: Disabling a CollisionObject node during a physics callback is not allowed and will cause undesired behavior. Disable with call_deferred() instead.
   at: _apply_disabled (scene/2d/collision_object_2d.cpp:233)
USER ERROR: Disabling a CollisionObject node during a physics callback is not allowed and will cause undesired behavior. Disable with call_deferred() instead.
   at: _apply_disabled (scene/2d/collision_object_2d.cpp:233)

**Comment by qwe3121** [comment]
just got a new logs with errors:
Godot Engine v4.0.beta17.official.c40020513 - https://godotengine.org
Vulkan API 1.3.224 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1050 Ti
 
USER ERROR: Cannot open file 'res://fonts/molot_font.tres'.
   at: load (scene/resources/resource_format_text.cpp:1647)
USER ERROR: Failed loading resource: res://fonts/molot_font.tres. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:221)
USER ERROR: Error loading custom font 'res://fonts/molot_font.tres'
   at: initialize_theme (scene/theme/theme_db.cpp:69)
USER ERROR: Attempt to open script 'res://src/autoloads/snl.gd' resulted in error 'File not found'.
   at: load_source_code (modules/gdscript/gdscript.cpp:1043)
USER ERROR: Script does not inherit from Node: res://src/autoloads/snl.gd.
   at: start (main/main.cpp:2724)
USER ERROR: Attempt to open script 'res://src/autoloads/events.gd' resulted in error 'File not found'.
   at: load_source_code (modules/gdscript/gdscript.cpp:1043)
USER ERROR: Script does not inherit from Node: res://src/autoloads/events.gd.
   at: start (main/main.cpp:2724)
USER ERROR: Attempt to open script 'res://src/autoloads/cfg.gd' resulted in error 'File not found'.
   at: load_source_code (modules/gdscript/gdscript.cpp:1043)
USER ERROR: Script does not inherit from Node: res://src/autoloads/cfg.gd.
   at: start (main/main.cpp:2724)
USER ERROR: Cannot open file 'res://src/autoloads/music_test_autoload.tscn'.
   at: load (scene/resources/resource_format_text.cpp:1647)
USER ERROR: Failed loading resource: res://src/autoloads/music_test_autoload.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:221)
USER ERROR: Condition "nc == 0" is true. Returning: nullptr
   at: instantiate (scene/resources/packed_scene.cpp:88)
USER ERROR: Path in autoload not a node or script: res://src/autoloads/music_test_autoload.tscn.
   at: start (main/main.cpp:2735)
USER ERROR: Attempt to open script 'res://src/autoloads/global_settings.gd' resulted in error 'File not found'.
   at: load_source_code (modules/gdscript/gdscript.cpp:1043)
USER ERROR: Script does not inherit from Node: res://src/autoloads/global_settings.gd.
   at: start (main/main.cpp:2724)
USER ERROR: Cannot open file 'res://src/autoloads/transition.tscn'.
   at: load (scene/resources/resource_format_text.cpp:1647)
USER ERROR: Failed loading resource: res://src/autoloads/transition.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:221)
USER ERROR: Condition "nc == 0" is true. Returning: nullptr
   at: instantiate (scene/resources/packed_scene.cpp:88)
USER ERROR: Path in autoload not a node or script: res://src/autoloads/transition.tscn.
   at: start (main/main.cpp:2735)
USER ERROR: Cannot open file 'res://src/autoloads/notification.tscn'.
   at: load (scene/resources/resource_format_text.cpp:1647)
USER ERROR: Failed loading resource: res://src/autoloads/notification.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:221)
USER ERROR: Condition "nc == 0" is true. Returning: nullptr
   at: instantiate (scene/resources/packed_scene.cpp:88)
USER ERROR: Path in autoload not a node or script: res://src/autoloads/notification.tscn.
   at: start (main/main.cpp:2735)
USER ERROR: Attempt to open script 'res://src/autoloads/global.gd' resulted in error 'File not found'.
   at: load_source_code (modules/gdscript/gdscript.cpp:1043)
USER ERROR: Script does not inherit from Node: res://src/autoloads/global.gd.
   at: start (main/main.cpp:2724)
USER ERROR: Cannot open file 'res://src/world.tscn'.
   at: load (scene/resources/resource_format_text.cpp:1647)
USER ERROR: Failed loading resource: res://src/world.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:221)
USER ERROR: Failed loading scene: res://src/world.tscn
   at: start (main/main.cpp:2921)
ERROR: 2 RID allocations of type 'N10RendererRD12LightStorage11ShadowAtlasE' were leaked at exit.
ERROR: 1 RID allocations of type 'N10RendererRD12LightStorage15ReflectionAtlasE' were leaked at exit.
ERROR: 1 RID allocations of type 'N10RendererRD14TextureStorage12RenderTargetE' were leaked at exit.
ERROR: 2 RID allocations of type 'N10RendererRD14TextureStorage7TextureE' were leaked at exit.
ERROR: 1 RID allocations of type 'N18RendererCanvasCull6CanvasE' were leaked at exit.
ERROR: 1 RID allocations of type 'N16RendererViewport8ViewportE' were leaked at exit.
ERROR: 1 RID allocations of type 'N17RendererSceneCull8ScenarioE' were leaked at exit.
USER WARNING: 4 RIDs of type "Texture" were leaked.
   at: finalize (drivers/vulkan/rendering_device_vulkan.cpp:9286)
USER WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
   at: cleanup (core/object/object.cpp:1982)

**Comment by qwe3121** [comment]
Now godot cant even launch project manager

**Comment by Calinou** [comment]
Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot. The `project.godot` file is not enough to reproduce the issue locally.

**Comment by Calinou** [comment]
>  Now even 16 beta cant launch project manager, Ill continue testing and will upload any information

What happens when you try to run the project manager? Did you place the Godot editor executable in the same location as the project folder? Did you place the project folder within your user's home directory?

**Comment by qwe3121** [comment]
> > Now even 16 beta cant launch project manager, Ill continue testing and will upload any information
> 
> What happens when you try to run the project manager? Did you place the Godot editor executable in the same location as the project folder? Did you place the project folder _directly_ within your user's home directory (`C:\Users\[username]`)? This will make the project run directly instead of opening the project manager, unless you pass the `--project-manager` command line argument to the editor executable.

nvm, I got editor crashes because project.godot and godot.exe was in the same folder.
so, lets back to the issue theme
maybe I can give you my project in private message or something?
cause there is no logs about crash, there is no problems when I create project in old betas in open in 17

**Comment by ababen1** [comment]
I'm also getting crashes when I try to change to certain scenes.  Both when I change into them in the game and when I open them in the editor.
I don't see any error messages when it crashes the game,
but when it crashes the editor, there's this:
```
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.beta17.official (c40020513ac8201a449b5ae2eeb58fef0ce0a2a4)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7ff5e4842520] (??:0)
[2] /home/ben/Desktop/Godot4/Godot_v4.0-beta17_linux.x86_64() [0x30d6515] (??:0)
[3] /home/ben/Desktop/Godot4/Godot_v4.0-beta17_linux.x86_64() [0x30d6708] (??:0)
[4] /home/ben/Desktop/Godot4/Godot_v4.0-beta17_linux.x86_64() [0x30d7389] (??:0)
[5] /home/ben/Desktop/Godot4/Godot_v4.0-beta17_linux.x86_64() [0x44ef5c4] (??:0)
[6] /home/ben/Desktop/Godot4/Godot_v4.0-beta17_linux.x86_64() [0x2b00a35] (??:0)
[7] /home/ben/Desktop/Godot4/Godot_v4.0-beta17_linux.x86_64() [0x2b00907] (??:0)
[8] /home/ben/Desktop/Godot4/Godot_v4.0-beta17_linux.x86_64() [0x2b00907] (??:0)
[9] /home/ben/Desktop/Godot4/Godot_v4.0-beta17_linux.x86_64() [0x2b00907] (??:0)
[10] /home/ben/Desktop/Godot4/Godot_v4.0-beta17_linux.x86_64() [0x2b00907] (??:0)
[11] /home/ben/Desktop/Godot4/Godot_v4.0-beta17_linux.x86_64() [0x2b016e3] (??:0)
[12] /home/ben/Desktop/Godot4/Godot_v4.0-beta17_linux.x86_64() [0x2b02c54] (??:0)
[13] /home/ben/Desktop/Godot4/Godot_v4.0-beta17_linux.x86_64() [0x2b03424] (??:0)
[14] /home/ben/Desktop/Godot4/Godot_v4.0-beta17_linux.x86_64() [0x44ef5c4] (??:0)
[15] /home/ben/Desktop/Godot4/Godot_v4.0-beta17_linux.x86_64() [0xeb02ca] (??:0)
[16] /home/ben/Desktop/Godot4/Godot_v4.0-beta17_linux.x86_64() [0x2b40a79] (??:0)
[17] /home/ben/Desktop/Godot4/Godot_v4.0-beta17_linux.x86_64() [0x2b9394c] (??:0)
[18] /home/ben/Desktop/Godot4/Godot_v4.0-beta17_linux.x86_64() [0xeab0cb] (??:0)
[19] /home/ben/Desktop/Godot4/Godot_v4.0-beta17_linux.x86_64() [0xde8ed3] (??:0)
[20] /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7ff5e4829d90] (??:0)
[21] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7ff5e4829e40] (??:0)
[22] /home/ben/Desktop/Godot4/Godot_v4.0-beta17_linux.x86_64() [0xe0908e] (??:0)
-- END OF BACKTRACE --
================================================================
```

I tried doing the same thing on windows, this time the game kept crashing but the editor was fine. 
Again, no error messages after the game crashes

**Comment by qwe3121** [comment]
Fixed in rc1
