### ISSUE TITLE
Font import doesn't allow dynamic fonts

### ISSUE THREAD

**Issue by igorskuhar** [godotengine/godot#7260]
**Operating system or device - Godot version:**
Mac OS X 10.11.4 (MBP 2015 Retina) - Godot v2.1.1.stable

**Issue description** (what happened, and what was expected):

When I drag and drop a .ttf font file onto Editor's "FileSystem" pane, the window titled "Font Import" shows up.
The only import modes it has are Bitmap and Distance Field.
But I just want to add .ttf font file to the resources, to use it as a newly supported dynamic font.
I managed to add the .ttf font file to the resources using Finder, but it would be easier to just drag and drop onto Editor.

**Steps to reproduce:**
1. Drag and drop .ttf font file from Finder to Editor's FileSystem pane.

**Comment by bojidar-bg** [comment]
Just load the .ttf directly, without any import

**Comment by igorskuhar** [comment]
@bojidar-bg 
What do you mean by loading the font directly?

**Comment by bojidar-bg** [comment]
Don't import it, but, select load in the "font" property's menu, then select the ttf...

**Comment by igorskuhar** [comment]
@bojidar-bg 
Thanks for your help 👍 

What worked for me:
1. Add the .otf/.ttf font file to the project resources using Finder (Mac) / Explorer (Windows).
2. Select your Label node. 
3. Inside Inspector scroll down to Control > Custom fonts > Font and select "New DynamicFont".

<img width="245" alt="new_dynamic_font" src="https://cloud.githubusercontent.com/assets/5592468/20970468/11b079fa-bc8e-11e6-96bf-706d556819aa.png">

4. Click the arrow on the right to open DynamicFont properties.
5. Click the Font dropdown menu (it says "<null>") and select "Load".

<img width="240" alt="load_font" src="https://cloud.githubusercontent.com/assets/5592468/20970615/b500086e-bc8e-11e6-9e2f-a17131aa5d55.png">

6. In "Open a File" popup, select your font file from the project resources (the rest of the filesystem is not available at this point).
7. Voila! Your .otf/.ttf font renders in the scene.

Hope it will help newcomers like me! ;)

**Comment by bojidar-bg** [comment]
Note that you can directly drag the ttf from the filesystem _dock_ into the font property of the _control_ (or theme)
