### ISSUE TITLE
Interfaces implemented in C# classes derived from CSharpScript Resources are not accessible

### ISSUE THREAD

**Issue by tobiasleissner** [godotengine/godot#72607]
### Godot version

4.0 Beta 17

### System information

Windows 10

### Issue description

Using Godot Mono 4.0 Beta 17

I have a Node with an exporting Resource of type CSharpScript
`[Export] public CSharpScript OtherScript;`

This way I can use different Scripts with a predefined interface to process events differently, depending on which Script I assign to this resource.

This is an example for the "OtherScript" implementation:
```cs
public partial class DefaultTriggerOtherScript : CSharpScript, ITriggerScript
{
    public void ProcessTrigger()
    {
        // do something here
    }
}
```

I cannot use the `DefaultTriggerOtherScript` directly in my `[Export]` tag, as this is not supported by the Godot Editor (cannot cast `CSharpScript` to `DefaultTriggerOtherScript`).

To call the methods defined in my `ITriggerScript` interface, I want to check whether this interface is implemented:
```cs
if (Trigger?.OtherScript is ITriggerScript ts)
{
           // do something with ts
}
```

However, the `OtherScript` is not an instance of my class, but a wrapper around my class, which is **not** implementing my interface. This way I cannot access my method `ProcessTrigger`, which **is** implemented in my interface.

Do you have a solution for this?
- make it possible to use OtherScript instead of CSharpScript when exporting as a Resource
- make it possible to check for implemented interfaces of CSharpScript if the solution before is not possible

Thanks for considering!

### Steps to reproduce

See description

### Minimal reproduction project

N/A

**Comment by tobiasleissner** [comment]
[SampleCSharpScript.zip](https://github.com/godotengine/godot/files/10571113/SampleCSharpScript.zip)
<img width="1917" alt="ERROR_MESSAGE" src="https://user-images.githubusercontent.com/64648122/216383856-22b2f269-822d-4f6d-817c-3ba5b633d6b1.png">

Check the sample main node.
SampleScript is a CSharpScript
SampleCSharp is a SampleCSharp object
SamplePlain is a C# class

Run the project and you will find some cast errors in the debugger view (see attached screenshot).

**Comment by Flavelius** [comment]
Aren't CSharpScripts indirectly created resources _only_ to link to actual managed classes? The way i understand it is that these CSharpScript inheriting types aren't even usable in way that actually makes use of their CSharpScript type. Wouldn't it be more useful to inherit from Resource instead? The examples look like usages of mere resources with an unnecessary inheritor inbetween.

**Comment by tobiasleissner** [comment]
> Wouldn't it be more useful to inherit from Resource instead? The examples look like usages of mere resources with an unnecessary inheritor inbetween.

Haven't thought about this solution yet.

BUT: It still doesn't work, with the same effect.

I change the superclass to `Resource` instead of `CSharpScript`, and `[Export]` the `Resource` instead. Again, I cannot check for implemented interfaces.

When exporting the `SampleCSharp` class directly, I get the same _casting_ error message as before.

**Comment by raulsntos** [comment]
I think I understand the issue now. When you use `[Export]` in a property/field, this means you can assign an instance of the same type through the inspector. For example, if your exported property is of type `Stats`, you need to assign an instance of the type `Stats`.

When you export a property of type `Script`, you can assign an instance of `Script`. Every `.cs` file in a Godot project is imported as a Resource of type `CSharpScript`. This means they are instances of `CSharpScript` and therefore can be assigned to exported properties of type `Resource`, `Script`, or `CSharpScript`.

When you export a property of type `MyCustomScript`, you need to assign an instance of that type of resource, of which there is none, unless you implement a custom `ResourceImporter`.

A file `MyCustomScript.cs` which contains a definition for the `MyCustomScript` type is not an instance of `MyCustomScript`, it's still an instance of `CSharpScript`.

I think @Flavelius is right, it seems what you intended was to create a `Resource` type and export that. The section [_Creating your own resources_](https://docs.godotengine.org/en/latest/tutorials/scripting/resources.html#creating-your-own-resources) in the documentation might help.

**Comment by tobiasleissner** [comment]
> A file `MyCustomScript.cs` which contains a definition for the `MyCustomScript` type is not an instance of `MyCustomScript`, it's still an instance of `CSharpScript`.


That's true. My requirement is to _assign a custom script to a property and use its methods via C#_.

> I think @Flavelius is right, it seems what you intended was to create a `Resource` type and export that. The section [_Creating your own resources_](https://docs.gdotengine.org/en/latest/tutorials/scripting/resources.html#creating-your-own-resources) in the documentation might help.

That would be nice, but this doesn't work either. I can create custom resources, export those as custom resources or as regular resources. As soon as I drag&drop a` .cs` file in editor to it, the `.cs` file will be imported as `CSharpScript`.

I can create a custom resource _instance_ in editor (a `TRES` file), attach my C# script to it, and use that as a resource. That works, but then I can use it as a regular `Resource` only, not as my custom resource. I have to use the `GodotObject.Call` method to call my public functions. However, this only works when using Godot classes as method parameters. As I have complex native C# objects, this doesn't work for me.

If it's not possible at all, to assign a custom script to a property, then this is fine. I will find a workaround in some way. I just want to make sure that I don't run into a bug or an unintended behavior.

**Comment by Flavelius** [comment]
Maybe i'm misunderstanding the intention, but custom resources work just fine for me in 4.0 beta 17:
[SampleProject.zip](https://github.com/godotengine/godot/files/10577017/SampleProject.zip)

**Comment by tobiasleissner** [comment]
Thanks @Flavelius, you were right. It was confusing to me on how to use the `.cs` file right.

I just tried your sample, even added a custom method to it, and I was able to call it.

So the solution is to create a **custom resource** (`TRES file`), add the `.cs` file as script for this `TRES file`.
Exporting the **custom resource type** is the way to go, but you cannot use the `.cs` file directly, but you have to create the `TRES file wrapper` around it to use it.

Thanks for your help to get this misunderstanding right.

This issue can be closed then.
