### ISSUE TITLE
[Godot 4 beta 17] Zoom with magic mouse in 2D editor does not work

### ISSUE THREAD

**Issue by UgisBrekis** [godotengine/godot#72609]
### Godot version

v4.0.beta17.official [c40020513]

### System information

macOS

### Issue description

Zoom in/out is not being triggered while holding "control" and scrolling via magic mouse on macOS. I also attempted to press command/shift/option just in case shortcut has changed, but still wasn't able to zoom in/out. Pressing +/- buttons in the top-left corner works, so does the pinch gesture on trackpad, so the issue appears to be with magic mouse input events.

(There is also an issue with panning- it is extremely slow on both magic mouse and trackpad)

### Steps to reproduce

Hold "control" and "scroll" the magic mouse either horizontally or vertically

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
> (There is also an issue with panning- it is extremely slow on both magic mouse and trackpad)

This is already being tracked in https://github.com/godotengine/godot/issues/72242.

**Comment by UgisBrekis** [comment]
Just to avoid confusion about the state of this one:
* the linked issue is about input slowness and that one is fixed
* **this issue** is about zoom in/out not working with magic mouse in 2D editor and it is still present in Godot 4 stable; the only way to zoom in/out is to use the widget or CMD +/- . At this point I'm even questioning if this is even implemented at all? How one zooms in/out in Godot 4 in 2D editor with a mouse?

**Comment by rndevfx** [comment]
Same issue for me with 4.0.2 stable. Have to use another mouse with a scroll wheel, the magic mouse is just scrolling the 2D editor around and isn't zooming.

**Comment by aitorciki** [comment]
This also affects trackpads in MacOS (both built-in and Magic Trackpad).

Testing multiple betas, the regression started in beta 16, so I guess it's likely related to https://github.com/godotengine/godot/pull/71685 (merged just a couple days before beta 16 was released)?

**Comment by oxeron** [comment]
Any news on this subject ?
