### ISSUE TITLE
Debug options are unchecked on every launch

### ISSUE THREAD

**Issue by igorskuhar** [godotengine/godot#7261]
**Operating system or device - Godot version:**
Mac OS X 10.11.4 (MBP 2015 Retina) - Godot v2.1.1.stable

**Issue description** (what happened, and what was expected):

Every time I open the Editor, all Debug options are unchecked and I need to check them all again.
It would be useful if their state was saved along with the project.   

<img width="450" alt="debug_options_unchecked" src="https://cloud.githubusercontent.com/assets/5592468/20950244/e225bc64-bc1e-11e6-9187-e8b939d58ee2.png">

**Steps to reproduce:**
1. Open editor.
2. Check few Debug options.
3. Close editor.
4. Open editor again.
5. Debug options will be unchecked.

**Comment by ppfeiler** [comment]
Should the state of the options saved in the `engine.cfg` file?

**Comment by bojidar-bg** [comment]
No, there was some per-project file for such data, check the PR about saving the last selected script language.

**Comment by ppfeiler** [comment]
Thank you for the hint! I will give it a try
