### ISSUE TITLE
Again beta17 breaks my project. `Trying to assign an array of type "Array" to a variable of type "Array[GdUnitReport]".`

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#72620]
### Godot version

v4.0.beta17.official [c40020513]

### System information

Windows 10

### Issue description

I get a lot of compile issues after upgrade to beta17
Simple code parts are broken!

`var reports :Array[GdUnitReport] = Array()`
results now in a error
`Trying to assign an array of type "Array" to a variable of type "Array[GdUnitReport]".`

needs to be changed to `var reports :Array[GdUnitReport] = []` but it should work to with `= Array()` as before

### Steps to reproduce

Add this simple line to a script and run it

```
func _ready:
   var reports :Array[RefCounted] = Array()
```
This kind of simple code is also broken:
```
func add_elements(value :Array[RefCounted]):
	pass

func test():
	var elements := [
		RefCounted.new(),
		RefCounted.new(),
	]
	add_elements(elements)
```
`Invalid type in function 'add_elements' in base 'Node (GdUnitIntAssertImplTest)'. The array of argument 1 (Array) does not have the same element type as the expected typed array argument.`
   
   

### Minimal reproduction project

N/A

**Comment by MikeSchulze** [comment]
> See #72566.
> 
> ```gdscript
> var reports: Array[RefCounted]
> reports.assign(Array())
> ```
> 
> `Array()` is not a constant expression, unlike `[]`.

Sorry what the hell? 
Why is should use this code noise to achive it?
`var values:Array[int] = []` is at least the same as `var values:Array[int] = Array()`
Both assigns are untyped, and the first one works.

**Comment by AThousandShips** [comment]
The codebase on 4.0 is in progress, it's going through a lot of change and various bugs involving Array has been fixed recently, and some other things haven't been implemented yet

**Comment by MikeSchulze** [comment]
> The codebase on 4.0 is in progress, it's going through a lot of change and various bugs involving Array has been fixed recently, and some other things haven't been implemented yet

I know this is a beta version, but this way of breaking the code makes me nervous. ;)

**Comment by h0lley** [comment]
I was also surprised to see that something like
```
var arr: Array[MyType]
arr = [MyType.new()]
```
would no longer be accepted.
I solved this particular case by changing the code to
```
var arr: Array[MyType]
arr.append(MyType.new())
```
but I imagine if this is intended, it's going to be quite a pain.

**Comment by dalexeev** [comment]
Constant expressions are automatically converted on assignment for convenience. But in general, assigning an array of a different type is now considered an error. You have to convert the array with `assign()`. See #69248 for details.

`Array()` is not the same as `[]`, you can see this:

```gdscript
const A = [] # OK
const B = Array() # Error
```

**Comment by MikeSchulze** [comment]
`Array()` is an untyped construtor yes, in the end it is the same as `[]` it is just a different notation.
Why should I please use an extra `assign()` ? 
This is primarily about the initial creation of an array.
And why should it not be autotyped in the initial assignment?
What speaks against it, it went also before problem-free.

**Comment by dalexeev** [comment]
Arrays are passed by reference. This means that variables and the objects in memory they point to are not the same thing for you. Multiple variables can point to the same array. Both variables and arrays (objects in memory) have types.

![](https://user-images.githubusercontent.com/47700418/216437809-e14890c6-6c23-423c-b953-fe223f932cf3.png)

When you assign an array to a variable with the `=` operator, you are not creating a new array with the same contents, you are saying "now this variable points to this array". The type of a variable limits what arrays the variable can point to. A variable of type `Array[int]` cannot point to an array of some other type. And if you want _to create a new array_ from another, you must use the `assign()` method.

Some bugs and inconsistencies still remained, but in general it was a deliberate change and fixing old incorrect behavior.

**Comment by KoBeWi** [comment]
> needs to be changed to var reports :Array[GdUnitReport] = []

You can just do `var reports :Array[GdUnitReport]`
All variables are automatically initialized to default value.

AFAIK there are plans to add a constructor for typed array, so `assign()` is a temporary workaround.

**Comment by vonagam** [comment]
There is a PR for typed constructor so it will be:
```gdscript
var reports := Array[GdUnitReport]()
```
So a single line and no noise. I assume that would be good enough, right?

Why `[]` and `Array()` have different behavior? Well those are two different types of expressions. `Array()` has arguments for typing the array, so if they were not specified it means that array is without an element type. `[]` has no arguments and its meaning can be treated as more open to interpretation.

Note about constant expressions: both `Array()` and `[]` can be supported for use in constants, but currently constructor call for array (and packed arrays) is not. This is just a flaw in implementation, can be fixed.

@h0lley your case (with `arr = [MyType.new()]`) as you wrote it should be supported, if it does not work (I tried and it works on master for me) - please open an issue and mention me there.

**Comment by MikeSchulze** [comment]
> There is a PR for typed constructor, it will be:
> 
> ```gdscript
> var reports := Array[GdUnitReport]()
> ```
> 

Thats good news ;) I had missing that.
I had fixed my issues yesterday so my project is working.

Thanks for all the effort and time.
Mike

**Comment by MikeSchulze** [comment]
this ticket can be closed, all questions are clarified
