### ISSUE TITLE
`AnimationNodeTransition`'s `current_state` is unset after #72450

### ISSUE THREAD

**Issue by maiself** [godotengine/godot#72637]
### Godot version

afe3b94ab28a28d562fd96f3daf41a22cb26757a

### System information

arch linux

### Issue description

`AnimationNodeTransition`'s `current_state` is unset after #72450

The line here https://github.com/godotengine/godot/pull/72450/files#diff-5f60b407f682f667ff4662bba3f1540fbe42dd854480db702ae445b5d56a281aL831 was moved up into the block above, and is now not called.

This is happening in my project when the first transition is to the first state.

### Steps to reproduce

Try to retrieve `AnimationNodeTransition`'s `current_state` after transitioning to the first state, `current_state` is unset.

### Minimal reproduction project

None

**Comment by TokageItLab** [comment]
The `current_state` is now read-only. You can only `transition_request` can be set.

**Comment by maiself** [comment]
Right, this is about not being able to read `current_state` after setting `transition_request` because `current_state` wasn't set internally.

**Comment by TokageItLab** [comment]
The current_state is set in the _process() after the transition_request is set. If you need to retrieve the animation immediately after setting (during the time it takes to _process()), read the transition_request directly.

**Comment by maiself** [comment]
> The `current_state` is set in the `_process()` after the `transition_request` is set.

Currently that statement doesn't hold if `current_index == 0` when `transition_request` is set to the state in position 0. Many `_process()` may have happened and `current_state` will still not be set.

**Comment by TokageItLab** [comment]
Are you trying to transition to the same state? Caused by the side-effects of #72450?

**Comment by maiself** [comment]
Yes and no... my code is checking `current_state` to know what state to request next, but `current_state` isn't valid and so it tries to transition to what it should be. I hope that sentience made any sense...

I think the problem is that `current_state` is not set initially. `current_index` starts out at `0`, but `current_state` starts as nothing at all, when it should be the name of the initial state.

**Comment by TokageItLab** [comment]
Maybe the initial value should be -1 or something, but I don't know if it can be done, because I remember that not blending was not allowed. I'll look at it later.
