### ISSUE TITLE
No display when export for Android and running on Samsung SM-A037W

### ISSUE THREAD

**Issue by blackears** [godotengine/godot#72630]
### Godot version

v4.0.beta17.official [c40020513]

### System information

Windows 10, both Compatability + Mobile

### Issue description

I'm having trouble getting an app I compile for Android to run on my cell phone. I have a Samsung Galaxy SM-A037W which is one of the cheaper and more modern phones.  When I have the Godot editor deploy the app for debugging, it seems to deploy something but the screen is completely black.  

The scene in the demo file I've provided has a simple scene with a MeshInstance3D, a light and a camera.  When I deploy it for debugging, the screen is completely black.  I've tried doing this in both compatibility mode and mobile mode.

### Steps to reproduce

Open the project and click the 'run remote' button in the toolbar.  The app seems to be loaded and run, but the screen display is entirely black.

### Minimal reproduction project

[ShaderTest.zip](https://github.com/godotengine/godot/files/10573986/ShaderTest.zip)

**Comment by clayjohn** [comment]
Could you update the post to include the logs from running ``adb logcat``?

**Comment by blackears** [comment]
How do I get the log from my session?  I tried running adb from the command line, but I'm just getting a flood of messages.

**Comment by blackears** [comment]
I captured this from Android Studio
[log.txt](https://github.com/godotengine/godot/files/10575180/log.txt)

**Comment by clayjohn** [comment]
It looks like it is attempting to setup Vulkan and failing. Have you double checked that ``rendering_method`` and ``rendering_method.mobile`` are both set to ``gl_compatibility``?

I don't think your device supports Vulkan. So if it is trying to use Vulkan it will fail.

**Comment by blackears** [comment]
It looks like setting those to gl_compatability fixed the problem.
