### ISSUE TITLE
Main screen view buttons can immediately lose focus when navigating (causes the focus style to quickly flicker)

### ISSUE THREAD

**Issue by forecaster-cyber** [godotengine/godot#72647]
### Godot version

v4.0.beta17.official [c40020513]

### System information

MacOS 13.1

### I know it's a nitpick but I pretty weird and I think it's a bug...

https://user-images.githubusercontent.com/75746148/216531884-06e4e543-859c-41cc-8535-766af99a204b.mov

As you can see in the video, when I switch between the tabs sometimes they show like they're selected and sometimes they don't and it's a little weird in my opinion. 
### Steps to reproduce

Just switch between the 3D, 2D, Script or AssetLib tabs...

### Minimal reproduction project

N/A

**Comment by forecaster-cyber** [comment]
I would just remove the rectangles that surround the tabs and I the ink it would look better...

**Comment by Flavelius** [comment]
It's the focus indicator that gets automatically moved to the viewport, as it seems it receives focus by merely hovering it. It's the same when you click the SceneTree or the FileSystem. But yes, i think it should be removed too, as it's unnecessary (i cannot imagine someone navigating the center toolbar buttons with a keyboard, not that it's easy to focus it that way to begin with)

**Comment by Zireael07** [comment]
@Flavelius That focus indicator was introduced for keyboard only users such as visual impaired developers (note that VI does not mean someone is COMPLETELY blind)

**Comment by YuriSizov** [comment]
To me it's not the "flicker" that's annoying, it's that entering the scene or the asset lib view the focus is immediately stolen by another GUI element. This makes keyboard navigation support useless, as you are removed from the top bar the moment you land on one of those tabs, with no direct way to continue moving through them.

**Comment by forecaster-cyber** [comment]
@YuriSizov Said it perfectly! In my opinion, at least make some sort of a setting to enable/disable it in settings...

**Comment by forecaster-cyber** [comment]
Can you change the milestone to 4.0, or is it too late?

**Comment by YuriSizov** [comment]
@forecaster-cyber 4.0 is in its final days of development, we only focus on critical issues and important bugs. This is a usability issue, but it's not critical and can be solved in a future release.

**Comment by Zireael07** [comment]
Why was this closed as "not planned" if you admit there EXISTS an "underlying problem" :confused:

**Comment by YuriSizov** [comment]
@Zireael07 It was closed by the author 4 days ago, which is within their right. I just reclassified it so it doesn't appear as if it was fixed.
