### ISSUE TITLE
[Godot 4 beta 14] (C#) Problem with loading assembly with dependencies in editor/build

### ISSUE THREAD

**Issue by wilfregd** [godotengine/godot#72645]
### Godot version

v4.0.beta14.official [28a2463]

### System information

Windows 10

### Issue description

Hello,
I noticed some problems with dynamic loading of assemblies in C#.
I am using version 4.0 (Beta 14)

Here is the context:
I would like to load a custom .dll into my game. It is sharing a reference to another .dll with core features shared between my game itself. 
My game has a reference to the core assembly in the .csproj file, the .dll I try to load has a reference to the core .dll on it's own.

To load the file, I use the Assembly.LoadFrom() method as should be:
`Assembly coreAssembly = Assembly.LoadFrom(@"..\Game.Core.dll");`
From there, I do what I have to, I try to get an attribute from it to check a specific class for my own implementation. But here is where it gets strange...
In the editor, everything works perfectly. I find my attribute, the class, I work with it as usual. But in build, it doesn't work and I get an error:
```
[A]Game.Core.MyAttribute  cannot be cast to [B]Game.Core.MyAttribute.
 
Type A originates from 'Game.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' in the context 'Default' at location 'C:\Users\Wilfre\Desktop\game\exports\1\data_Voxel_x86_64\Game.Core.dll'.
 
Type B originates from 'Game.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' in the context 'Default' at location 'C:\Users\Wilfre\Desktop\game\exports\1\data_Voxel_x86_64\Game.Core.dll'.
```
As you can see, only in a build, it loaded twice the assembly yet it is the exact same. I tested this out on a simple c# project without using Godot and it works as expected just like in the editor. Which means something in the build happens to assemblies and I can't find what it is. 
I tried to test this further but this is all I could find. I event tried using the "AssemblyResolve" event but, in the build, it is not even called.

Is there something I am missing about how Godot works with Assemblies? Again, this strange behavior happens in the Godot builds ONLY. And not even in simple c# apps.

### Steps to reproduce

The steps require at least 3 projects. I uploaded everything in the minimal reproduction so it can be tested easily.
- Project A: Core components
- Project B: The Godot project, referencing Assembly A
- Project C: A library to load into Godot, referencing Assembly A

In Godot, dynamically load Assembly C (called "Addon.dll") and compare their types (in this case, an attribute).
Make sure to trigger the "AssemblyResolve" event if the dependencies are not loaded into the Addon assembly.
If everything goes right, the editor will log that the two types are equal. The build should display an error saying that the two types are different.

I added a build of the project just to try it out easily.
The required .dll have been compiled already for you to test it. If needed, the projects for them are found in the ".dll projects" folder if you want to take a look.

### Minimal reproduction project

On my [Google Drive](https://drive.google.com/file/d/1d5Uu-qbw8Sw5JWNT0fikDVZWTcfgkGhC/view?usp=share_link) since the file is 55Mb.

Everything you need to test this should be included and commented.

**Comment by Flavelius** [comment]
I was interested in why this doesn't work and that led me to discovering the new AssemblyLoadContexts in .net.
The reason it doesn't work is that both assemblies are in a different one, so the types are 'separate'.
This is the quick-fix:
var addonAssembly = AssemblyLoadContext.GetLoadContext(typeof(MyAttribute).Assembly).LoadFromAssemblyPath(path);

**Comment by wilfregd** [comment]
Thank  you very much, this solution works perfectly! I somehow completely missed the new AssemblyLoadContext.

I made it cleaner by getting the game assembly itself without using the attribute if someone needs it for another use case:
`AssemblyLoadContext.GetLoadContext(Assembly.GetExecutingAssembly())`
