### ISSUE TITLE
[C#] Signals Throw "Method not found" From Inherited Scenes with Extended Scripts

### ISSUE THREAD

**Issue by Anixias** [godotengine/godot#72641]
### Godot version

v4.0.beta16.mono.official [518b9e580]

### System information

Windows 10

### Issue description

Scenes that are inherited from a base scene always throw "Method not found" for inherited signals if the child scene extends the parent's script without explicitly implementing the signal methods themselves.

### Steps to reproduce

1. Create a parent scene, give it a new script.
2. Connect some signal to the root node.
3. Create a child scene that inherits from the parent scene.
4. Extend the inherited script, do not explicitly implement the signal method.
5. Run the game, trigger the signal for the child scene, observe the error.

### Minimal reproduction project

[InheritedSignalIssueMRP.zip](https://github.com/godotengine/godot/files/10574455/InheritedSignalIssueMRP.zip)

Run the "ChildButton" scene. Clicking the button should inherit the signal handler method "OnPressed", which changes the button text to "Pressed!", but it fails (check the errors in the debugger).

**Comment by Anixias** [comment]
Okay, it seems to be deeper than just signals. No methods are being called unless they are also overridden/implemented in the child! This includes all built-in functions, such as _Process or _PhysicsProcess.

**Comment by Flavelius** [comment]
In the example there's an inherited scene that replaces the script of the parentbutton scene with another that is not even related to the parentbutton script. This is working as intended and expected. 
I think what you assume would be possible is that the script of the inherited scene is implicitly extended/inherited aswell. Not sure if this works in gdscript but in c# this is not possible without the engine doing strange magic that goes against expectations. If you want to re-use methods, event handlers etc. from a base class, inherit your class from it. 
```public partial class ChildButton : ParentButton```
It will not **be** the same instance as the parent, but it'll work the same way and as you expect.

**Comment by Anixias** [comment]
I managed to fix the problem in my game (somehow the editor cleared the script property from my instance of the child scene), but in my example MRP, did I really forget to use ChildButton : ParentButton? If so, I was in a hurry and it was a silly mistake. This can be closed if it's confirmed that I just forgot to do so.

**Comment by Anixias** [comment]
Yep, I was just in a hurry to make a MRP and forgot to actually inherit the ParentButton... Sorry about that!
