### ISSUE TITLE
GPUParticles3D flickers frozen particle at world origin (0, 0, 0) when shader material has y-billboard set

### ISSUE THREAD

**Issue by kraybit** [godotengine/godot#72650]
### Godot version

v4.0.beta17.mono.official [c40020513]

### System information

Windows 10

### Issue description

With certain settings, GPUParticles3D intermittently shows a particle at world origin with zero velocity.

These settings in GPUParticles3D caused this behavior:
- Lifetime 1 s
- Material Override / StandardMaterial3D / Billboard / Mode : Y-Billboard
- Mesh: Quad

**Quirks**
- Turning Y-Billboard on and off toggles the bug
- Setting Lifetime for particles to 10 s makes the bug disappear "for ever", even if setting back Lifetime to 1 s (?)

![gpu_particles_ybillboard_bug](https://user-images.githubusercontent.com/2845401/216540590-f7f96836-1b62-430f-bddd-e5be6c8ff6b8.gif)

### Steps to reproduce

- Create new Godot project
- Create new scene with Node3D
- Add GPUParticles3D node
- Under Process Material, select New ParticleProcessMaterial
- Click ParticleProcessMaterial for settings, there set Emisssion Shape to Box
- Under Draw Passes / Pass 1, select New QuadMesh
- Click the QuadMesh for settings, there set size to 0.1 , 0.1
- Under Geomeetry / Material Override, select New StandardMaterial3D
- Click StandardMaterial3D for settings, there set Billboard / Mode to Y-Billboard
- Set Transform y-position to 1

At world origin (0, 0, 0) there's intermittently a particle with zero velocity.

### Minimal reproduction project

[gpu_particles_ybillboard_bug.zip](https://github.com/godotengine/godot/files/10576653/gpu_particles_ybillboard_bug.zip)

**Comment by QbieShay** [comment]
Could you re-test with apply_scale flag enabled?

**Comment by Calinou** [comment]
I could reproduce a	similar issue with the Particle Billboard mode here: https://github.com/godotengine/godot/issues/49767#issuecomment-1440500413

**Comment by QbieShay** [comment]
oop sorry @kraybit . Yes, it was keep scale not apply scale :D 

@Calinou particles use scale 0 to try and make particles invisible, but if keep scale is off then a new matrix is generated based on the camera matrix and the instance_custom.x as a rotation value, so the particles that should be "dead" are instead displayed at the origin

**Comment by Calinou** [comment]
> @Calinou particles use scale 0 to try and make particles invisible, but if keep scale is off then a new matrix is generated based on the camera matrix and the instance_custom.x as a rotation value, so the particles that should be "dead" are instead displayed at the origin (at least this is how it worked in 3.x)

Interesting, I thought their position would be changed to `-INF, -INF, -INF` (this is what the "Hide On Contact" collision mode does).

**Comment by QbieShay** [comment]
I think that's what happens already, but if you don't enable scale in billboards you still see them. The inf solution sounds better

**Comment by ecmjohnson** [comment]
The inf solution is much cleaner (2 line change vs. 12) and doesn't have a performance impact on the billboarded materials since they don't need to even check anything
