### ISSUE TITLE
Viewport.push_input's second parameter: in_local_coords not working

### ISSUE THREAD

**Issue by jinyangcruise** [godotengine/godot#72657]
### Godot version

v4.0.beta17.official.c40020513

### System information

Windows 10, Forward+, NVIDIA GeForce GTX 860M

### Issue description

![image](https://user-images.githubusercontent.com/42859362/216591208-28935ade-e63c-480e-8545-b344b50f13a1.png)

I use a SubViewport as the Sprite3D's texture to render a 2D-scene in this 3D scene.

In order to trigger mouse event into the 2D scene, I use this script:
```gdscript
extends Node3D

func _input(event: InputEvent):
	$SubViewport.push_input(event, false) 
```
The second parameter of `push_input` behaves like having no effect whether it's `true`or `false`.

![screenshot](https://user-images.githubusercontent.com/42859362/216593606-1920401b-6fa6-425b-a546-fa1f5d286016.gif)

this function's information in GODOT API DOC:
https://docs.godotengine.org/en/latest/classes/class_viewport.html#class-viewport-method-push-input

### Steps to reproduce

1. open minimal reproduction project below
2. run this project and check if you can click the buttons (by moving some left-offsets)
3. modify `$SubViewport.push_input(event, false) `  second parameter to true or false 
4. re-run and check

### Minimal reproduction project

[test for viewport.zip](https://github.com/godotengine/godot/files/10578523/test.for.viewport.zip)

**Comment by Calinou** [comment]
cc @Sauermann

**Comment by jinyangcruise** [comment]
when running this project, also see an error (not sure whether related to this bug or anther bug):

![image](https://user-images.githubusercontent.com/42859362/216605726-cdf4d29f-86c2-41c3-a9ce-005cdb2b5c16.png)

```
E 0:00:01:0341   setup_local_to_scene: Condition "proxy.is_valid()" is true.
  <C++ Source>   scene/main/viewport.cpp:88 @ setup_local_to_scene()
```

and when I put the SubViewport node below the Sprite3D node, more errors occur:
![image](https://user-images.githubusercontent.com/42859362/216606533-5a4856f5-4208-461f-b10f-681ddbba8e96.png)
![image](https://user-images.githubusercontent.com/42859362/216606461-c2c9ff00-896c-4983-8708-237d2641e1f3.png)

**Comment by Zireael07** [comment]
Why close?

**Comment by jinyangcruise** [comment]
> Why close?

my bad, reopened

**Comment by jinyangcruise** [comment]
I see. Thank you very much.

Do you have any plan to make an out-of-the-box method to deal with such cases?

And I'm curious about the exception of embedded Windows and SubViewports in InputEvent process.
In this artical: https://docs.godotengine.org/en/latest/tutorials/inputs/inputevent.html

`When sending events to its child and descencand nodes, the viewport will do so, as depicted in the following graphic, in a reverse depth-first order, starting with the node at the bottom of the scene tree, and ending at the root node. Excluded from this process are embedded Windows and SubViewports.`

and

```
Since Viewports don't send events to other SubViewports, one of the following methods has to be used:
- Use a SubViewportContainer, which automatically sends events to its child SubViewports during 
Node._input() and Node._unhandled_input().
- Implement event propagation based on the indivitual requirements.
```
btw, I notice there isn't a 3D version SubViewportContainer.

Any problem prevents Viewports to send events to its SubViewports? (complex, no need and no time for this at the moment, maybe?)

I ask this because it's kind of counter-intuitive and it might break the simplicity and coherence of Godot's node-based design concept.

**Comment by Sauermann** [comment]
It was a design decision, that `SubViewports` by default don't receive events, because there are use-cases for Viewports, which don't need events.
In order to send events to `SubViewports` it is necessary, to provide a coordinate system-conversion (for mouse-clicks and other events with positions). `SubViewportContainer` does exactly this for the 2D-use-case (`SubViewports` don't have a position).

Embedded Windows only receive input events, if they are focused, so there is a different mechanism for them and the above mentioned restriction is actually a necessity. (See step 2 in the cited InputEvent tutorial)

I believe, that a 3D-variant of `SubViewportContainer` could be an interesting idea.
Feel free to create a proposal for this on https://github.com/godotengine/godot-proposals

**Comment by Sauermann** [comment]
I have created a small project file that shows the general idea of how to implement event propagation for 3D.

[SubViewportEventPropagationTutorial.zip](https://github.com/godotengine/godot/files/10581163/SubViewportEventPropagationTutorial.zip)

Advanced features like Drag and Drop would probably need more work.

![image](https://user-images.githubusercontent.com/6299227/216667273-890cd051-5ea4-4e5e-bd64-9f53d705a660.png)

This function does the heavy lifting of the coordinate-transforms.
``` gdscript
func _on_input_event(_camera: Camera3D, event: InputEvent, pos: Vector3, _normal: Vector3, _shape_idx: int):
	# Position of the event in Sprite3D local coordinates.
	var texture_3d_position = s.get_global_transform().affine_inverse() * pos
	if !is_zero_approx(texture_3d_position.z):
		# Discard event because event didn't happen on the side of the Sprite3D.
		return
	# Position of the event relative to the texture.
	var texture_position: Vector2 = Vector2(texture_3d_position.x, -texture_3d_position.y) / s.pixel_size - s.get_item_rect().position
	# Send mouse event.
	if event is InputEventMouse:
		var e: InputEvent = event.duplicate()
		e.set_position(texture_position)
		e.set_global_position(texture_position)
		v.push_input(e)
```

**Comment by jinyangcruise** [comment]
Thx again! A lot to learn from your turorial.
I will consider to create a proposal for a 3D-variant of SubViewportContainer after doing some research on the current 2D SubViewportContainer : )

**Comment by Sauermann** [comment]
I did a quick search and you might find https://github.com/godotengine/godot-proposals/discussions/4093 interesting.

**Comment by jinyangcruise** [comment]
hope there wil be more progresses made to break totally the wall of 2D world and 3D world : P

**Comment by olmswagballs** [comment]
does any one knowany way in which this could be accomplished whilst in mouse mode captured with a first person moving camera?
