### ISSUE TITLE
LightmapGI is slow to import due to OpenEXR VRAM compression being enabled by default

### ISSUE THREAD

**Issue by eviltrout** [godotengine/godot#72666]
### Godot version

4.0 beta 17

### System information

Windows 11, Forward+, RTX 4090

### Issue description

In the latest beta, baking LightmapGI has taken a big performance hit. The baking itself might not be the problem, it's the (Re)Importing Assets step for the `.exr` that seems to take all the time.

### Steps to reproduce

I've included a repro project to demonstrate it. Click the `LightmapGI` node and then the `Bake Lightmaps` button.

Before Beta 17:
`Done baking lightmaps in 00:00:01.`

With Beta 17 (and the latest Master branch, just in case):
`Done baking lightmaps in 00:00:08.`

### Minimal reproduction project

[lightmap-regression-repro.zip](https://github.com/godotengine/godot/files/10579835/lightmap-regression-repro.zip)

**Comment by akien-mga** [comment]
Probably related to #72031.

**Comment by cosmoddd** [comment]
this came up in my tests as well.  Any exr file takes a very long time to reimport, to the point where Windows gives the "This Program Has Stopped Responding" dialog.

**Comment by Calinou** [comment]
VRAM compression should probably not be used on lightmaps themselves by default, as it tends to have a big impact on quality.

**Comment by clayjohn** [comment]
I've been investigating this a little bit. It seems like the difference is that we are now using BPTC compression for lightmaps instead of using the textures uncompressed. I don't know why https://github.com/godotengine/godot/pull/72031 changed the behaviour in that regard, so I will continue investigating

**Comment by WrobotGames** [comment]
This makes baking lightmaps almost impossible for me, since it freezes the editor for like 10 minutes. (The baking itself took only 1 minute) Other exr files import just fine, even when using the texture2darray importer.

**Comment by Calinou** [comment]
> Edit: Okay, so the difference is actually that textureArrays didn't have BPTC implemented so it always used S3TC, but now BPTC is supported so it is used as the image is HDR. IMO the current behaviour is actually more correct and really just serves to highlight that we desperately need a faster BPTC compressor

I would be surprised if a fast BPTC compressor can compress a lightmap in less than 5-10 seconds, which still takes its toll on iteration times. This is why I'd prefer lightmap VRAM compression to be something you have to explicitly enable after you're done with initial iteration.

**Comment by Zireael07** [comment]
> This is why I'd prefer lightmap VRAM compression to be something you have to explicitly enable after you're done with initial iteration.

Can this (no VRAM compression by default on lightmap) be squeezed in before 4.0 as this is quite a bad performance regression?

**Comment by eviltrout** [comment]
Just confirming that my issue is fixed in the latest master branch of Godot. As noted in #73136 I had to delete my `.exr.import` files from previous bakes to get back to the previous speed.

Thanks to all who helped and got this fixed.
