### ISSUE TITLE
Running scenes process won't close

### ISSUE THREAD

**Issue by carlinitos** [godotengine/godot#727]
When hitting run in the editor, a new process appears and the preview window shows up. but when than window is closed, or the stop button is hit in the editor, the process remains
![area de trabajo 1_038](https://cloud.githubusercontent.com/assets/8909965/4400059/639e7a3a-4479-11e4-9a55-d111cda56dbf.png) I'm using xubuntu 14.04 and everything else in the OS seems fine

**Comment by akien-mga** [comment]
Is this issue still valid in the current master branch?

**Comment by akien-mga** [comment]
I can't seem to reproduce it here on Linux by monitoring the processes in ktop. I do get a zombie when quickly switch from an opened project to the project list and then into a different project, but it quickly gets cleaned up and in the end I still have only one process.

**Comment by carlinitos** [comment]
It's already fixed
