### ISSUE TITLE
[4.0] GDScript underscored variables in custom classes appears in generated documentation

### ISSUE THREAD

**Issue by ClarkThyLord** [godotengine/godot#72705]
### Godot version

Godot 4.0 beta 17

### System information

Windows 10

### Issue description

As mentioned in Godot's latest documentation, [here](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_documentation_comments.html#documenting-script-members).

> The script documentation will update in the editor help window every time the script is updated. If any member variable or function name starts with an underscore it will be treated as private. It will not appear in the documentation and will be ignored in the help window.

However, when working with custom classes that have underscored variables they still appear in the classes generated documentation, as seen below:

![image](https://user-images.githubusercontent.com/17155529/216753460-e4b86280-f575-40fd-ad00-c86174d273c2.png)

![image](https://user-images.githubusercontent.com/17155529/216753476-27938e16-1c0c-4dcd-bf23-175aa7810319.png)

This is obviously unwanted behavior as it exposes "private" variables that are supposed to be abstracted away from an end user.

### Steps to reproduce

1. Open example project
2. Open Example class documentation
3. Private variable "_private_variable_a" can be seen
3. Private variable "_private_variable_b" can be seen

### Minimal reproduction project

[example.zip](https://github.com/godotengine/godot/files/10607907/example.zip)

**Comment by ClarkThyLord** [comment]
Relevant to  [@68639](https://github.com/godotengine/godot/issues/68639)

**Comment by Cykyrios** [comment]
I have a PR that should fix this #67707, but it hasn't been approved yet.
