### ISSUE TITLE
the gdextension project cannot be opened in godot4.0beta14

### ISSUE THREAD

**Issue by dream727** [godotengine/godot#72715]
### Godot version

4.0 beta14

### System information

windows10

### Issue description

I download gdextension,built it and built test project.When it done,I try to open test/demo/project.godot,then the editor is turned on.Fast,the editor is turned off.I try to open it over 10 times,but the results is common.

### Steps to reproduce

1.I download gdextension,built it and built test project.(scons .    cd test    scons .)
2.When it done,I try to use godot to open test/demo/project.godot,then the editor is turned on.Fast,the editor is turned off.
3.I try to open it over 10 times,but the results is common.

### Minimal reproduction project

sorry,I don't have project now,but i will put it after about 10 hours.(if you need it now,you can repeat my step,sorry very much)

**Comment by aXu-AP** [comment]
Have you tried using the latest beta ([17](https://godotengine.org/article/dev-snapshot-godot-4-0-beta-17/))?

**Comment by dream727** [comment]
> 您是否尝试过使用最新的测试版 （[17](https://godotengine.org/article/dev-snapshot-godot-4-0-beta-17/)）？

Sorry, I didn't follow the new version of godot, it opened successfully in beta17
