### ISSUE TITLE
Running project does not go fullscreen if the editor is currently fullscreen on macOS

### ISSUE THREAD

**Issue by RandomWalrus13** [godotengine/godot#72710]
### Godot version

4.0.beta17

### System information

MacOS Ventura 13.2

### Issue description

Fullscreen mode only works when the Godot app isn't in full screen mode. If the app is not in full screen mode, it appears to be a very small window (shown below). Otherwise, the window is fullscreen.
<img width="638" alt="Screenshot 2023-02-04 at 8 09 40 AM" src="https://user-images.githubusercontent.com/111152655/216772137-42a578ea-7d2b-4007-b45b-91eebdb1a88b.png">

### Steps to reproduce

<img width="673" alt="Screenshot 2023-02-04 at 8 10 17 AM" src="https://user-images.githubusercontent.com/111152655/216772155-0f8d16b2-2fe1-4404-bf6c-0d8b788e4bfa.png">
Use these window settings to reproduce.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
I think this is expected, as you can't have multiple apps in fullscreen at the same time on macOS.

This could be worked around by disabling fullscreen on the editor before running the project, then enabling fullscreen again when the running project stops for any reason (including on a crash).

cc @bruvzg

**Comment by bruvzg** [comment]
I can't reproduce on the current master (on macOS 13.2), running full-screen app from a full-screen editor is working fine. Check `Editor Settings -> Run -> Window Placement` it overrides project settings if set.

> I think this is expected, as you can't have multiple apps in fullscreen at the same time on macOS.

You can have any number of full-screen apps on macOS at the same time, each one will occupy its own virtual desktop and should not cause any conflicts.
