### ISSUE TITLE
Godot crash when disconnecting audio source

### ISSUE THREAD

**Issue by pikmeir** [godotengine/godot#7272]
**Operating system or device - Godot version:**
Windows 8.1 64bit Godot 2.1.1 (Steam)

**Issue description** (what happened, and what was expected):
The program will completely crash when disconnecting the current audio device (such as Bluetooth).

**Steps to reproduce:**
Turn on Bluetooth headset/speaker that is connected to the computer. Open Godot. Turn off Bluetooth headset/speaker. Godot crashes.

**Link to minimal example project** (optional but very welcome):

**Comment by xxDeathskillxx** [comment]
Same with normal Audio-Jack. After unplugging Godot crashes.

**Comment by bojidar-bg** [comment]
Related #1684 and even more to #5211. (and probably duplicate of the latter)

**Comment by timoschwarzer** [comment]
Seems like it affects all OSes

**Comment by timoschwarzer** [comment]
@bojidar-bg I tried this with 2.1.3-stable and Godot does no longer crash.
So this issue and #5211 can be closed.

**Comment by bojidar-bg** [comment]
Assuming fixed then 👍
