### ISSUE TITLE
Godot glitches out and becomes unusable after being left in the background for a long time

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#72728]
### Godot version

4.0 beta 17 (but I've encountered it since early alphas)

### System information

Ubuntu 22.04.1 LTS

### Issue description

Sorry for the jank, I just went to record this as soon as I could catch it on camera. The task bar is on the left and I'm clicking the Godot icon. It auto-minimizes when I try to open it most of the time.

https://user-images.githubusercontent.com/85438892/216784828-403b01d2-8818-44fe-b7a8-3d749091c011.mp4

I'm pressing F5 here to play the project normally, but it closes immediately:

https://user-images.githubusercontent.com/85438892/216784819-9a4120a1-d751-4ba4-837d-9272f3fc7caa.mp4

### Steps to reproduce

I have been unable to reproduce it, but leaving Godot in the background for a few hours often leads to it happening. For all I know, it seems random. Happens even on a tiny project.

However, one reliable way to trigger this behavior seems to be suspending my machine.

the "About" of my laptop:

![image](https://user-images.githubusercontent.com/85438892/223223383-1f5d6c20-72cf-4ed2-a69e-3d14b5e95d55.png)

### Minimal reproduction project

N/A

**Comment by JulianHeuser** [comment]
I've noticed this too (both behaviors). Somtimes the 3d viewport also gets really laggy, as if it's framerate limited.

**Comment by MewPurPur** [comment]
A reliable way to trigger this behavior is to suspend my machine.

**Comment by naturally-intelligent** [comment]
For myself this is immediate if I minimize Godot, whether after 1 second of use or 2 hours, it will not unminimize, and must be closed

**Comment by vvvvvvitor** [comment]
Same is happening here in Fedora, allegedly it affects both Wayland and X11 and can also happen in any DE.

**Comment by vvvvvvitor** [comment]
Still happens on 4.0.3, it can happen randomly after you focus on editable text.
[Gravação de tela de 2023-05-19 17-29-38.webm](https://github.com/godotengine/godot/assets/119557151/6b32b9aa-71cc-4262-a4f6-c8eea974fa88)

**Comment by thebigtoona** [comment]
can confirm this is happening for me as well on 4.0.3.  I'm running Pop!_OS 22.04 LTS. 
commenting here as https://github.com/godotengine/godot/issues/74336 was closed as a duplicate.

**Comment by chfoo** [comment]
Issues dealing with popup windows on Linux might be a different bug specifically with text input boxes: #60073 and #77333.

**Comment by MewPurPur** [comment]
Well, I've been using 4.1 betas and I've not encountered the issue in the first video. But I still encounter the issue in the second video. I'll open a new issue.
