### ISSUE TITLE
Beta 17 crashes when trying to parse .tscn files of previous beta

### ISSUE THREAD

**Issue by ababen1** [godotengine/godot#72724]
### Godot version

v4.0.beta17.official [c40020513]

### System information

tried on win 10, and on linux, same result

### Issue description

Because beta 17 added improvements to typed arrays, it changes how .tscn file is written
for exmaple - in beta 16, it would save an array of custom resources like this:
`chapters = [ExtResource("2_jvml2"), ExtResource("3_kl787"), ExtResource("4_7m46j"), ExtResource("5_81xj8"), ExtResource("4_j6y8m")]
`
but in beta 17 it saves it like this:
`chapters = Array[Resource("res://src/Resources/Lessons/LessonGroupData.gd")]([ExtResource("2_jvml2"), ExtResource("3_kl787"), ExtResource("4_7m46j"), ExtResource("5_81xj8"), ExtResource("4_j6y8m")])
`

If you try to open \ play a .tscn file that is formatted like the first example inside beta 17, the editor will crash.
it does change it to the correct formatting if you change something in the scene and save again, but my project is pretty large by now and going into every scene to do this quite tedious and sometimes even impossible, because it will crash as soon as you open the file

### Steps to reproduce

- have a scene that contains custom resources and was made in godot  4 beta 16 or earlier
- run it in beta 17

### Minimal reproduction project

n\a

**Comment by vonagam** [comment]
Previous syntax `chapters = [...]` is still valid and used one (for untyped arrays). There is also a special handling of properties in packed scenes and resource files that converts untyped arrays into typed arrays of expected type when they are being set. So this should not happen.

Is it possible to get some minimal project for reproduction? Maybe there is some specific combination of setter/getter involved.

**Comment by ababen1** [comment]
> Previous syntax `chapters = [...]` is still valid and used one (for untyped arrays). There is also a special handling of properties in packed scenes and resource files that converts untyped arrays into typed arrays of expected type when they are being set. So this should not happen.
> 
> Is it possible to get some minimal project for reproduction? Maybe there is some specific combination of setter/getter involved.

this is a typed array. it always was, even in godot 16 and earlier. but it only started saving it with the `Array[type]` syntex in beta 17. is the previous syntex still valid with typed arrays as well?

**Comment by vonagam** [comment]
Yes, should be. At least in scene and resource files. So when it is saved with new syntax, but loading should work with old one too.

**Comment by ababen1** [comment]
I took another look at my files, I see that some of them were changed to the new syntax, but some didn't. So currently my project is mixed with new syntax in some files and old in others. I dont know why it only changed some of them. 
I have a lot of resources and some of them are pretty large, could this be a problem?

**Comment by vonagam** [comment]
I guess only those that we touched after upgrade were saved with new syntax. Size should not matter. There are reports to crashes related to other reasons. So without an example hard to say that it is related to arrays at all or if it is then to why.

**Comment by qwe3121** [comment]
I can confirm this happens

**Comment by vonagam** [comment]
Any stacktrace? What makes you think it is array related specifically?

**Comment by qwe3121** [comment]
> Any stacktrace? What makes you think it is array related specifically?

I confirm trying to open .tscn files from previous beta crashing beta 17, but the main scene (which is open by default in projects) running fine. Also if you run the project, it will be processing fine.

**Comment by vnen** [comment]
Seems like a transient bug and last report mentions it being solved.
