### ISSUE TITLE
_edit function in EditorPlugin is only called when dock status changes.

### ISSUE THREAD

**Issue by JulianHeuser** [godotengine/godot#72733]
### Godot version

v4.0.beta17.official [c40020513]

### System information

Linux Mint 21 Cinnamon

### Issue description

I'm using a custom editor plugin that updates whenever a node is selected. The _edit function should be called every time a new node is selected. However, after beta 17, the _edit function is only called if the dock updates. In general, if selecting the node causes the dock button to change visibility, _edit will run.

This means switching between nodes that don't change the return value of _handles won't cause _edit to run, even though it should.

I didn't have this issue in beta 16 so this is new since then. PR #72482 seems likely to have caused this, maybe #72420 but it's unlikely.  

### Steps to reproduce

1. Create a new plugin
3. Override the _edit and _handles functions.
4. _edit will only be called when the return value of _handles changes, or when you deselect everything - it should be called whenever a new node is selected.

### Minimal reproduction project

[BugReport.zip](https://github.com/godotengine/godot/files/10609652/BugReport.zip)

**Comment by TokageItLab** [comment]
There is a similar issue #72382.

**Comment by YuriSizov** [comment]
cc @KoBeWi

**Comment by KoBeWi** [comment]
Fixed by #72796
