### ISSUE TITLE
[v4.0beta17-mono] Windows Release Builds Frozen on Launch

### ISSUE THREAD

**Issue by QueenOfSquiggles** [godotengine/godot#72739]
### Godot version

4.0.dev (c40020513) (4.0 beta 17 Mono Version)

### System information

Windows 10/11 Nvidia GPU (varied)

### Issue description

Several of my players that are windows users are reporting that the game does not launch on their system. It reaches to the splash screen then does nothing.

I have had several reports of it working and several of it not working. One user [opened an issue](https://github.com/QueenOfSquiggles/DumbJumpscareGame/issues/1) on the project repository noting they got an error of having run out of RAM. Both of us verified that it seems to cap out around 700 Mb of memory usage. But since I'm on Linux I can't test much myself.

Another user was helping me to do some debugging and was able to generate this verbose log file. But I'm having trouble making heads or tails of it. It seems to imply one of the autoload scenes is loaded, and then everything stops
[WhereTheDeadLie_WindowsTrace.txt](https://github.com/godotengine/godot/files/10609796/WhereTheDeadLie_WindowsTrace.txt)

I haven't had any reports from Linux or Mac users, and from the analytics on the project page I know several users on each system have downloaded the project. So I believe this is a strictly windows issue?

I'm actually really hoping that this is an issue with the engine of some sort, because I'm at a complete loss what it could be. Thanks for any help that can be provided!

### Steps to reproduce

Run the game on a windows machine (Unsure if Nvidia GPU is related). Launch should stop before fully loading the main menu.

### Minimal reproduction project

N/A (I don't know what's causing this.)

**Comment by QueenOfSquiggles** [comment]
I forgot some important links:

- Project Repository: [https://github.com/QueenOfSquiggles/DumbJumpscareGame](https://github.com/QueenOfSquiggles/DumbJumpscareGame)
- Project Download Page: [https://queenofsquiggles.itch.io/where-the-dead-lie](https://queenofsquiggles.itch.io/where-the-dead-lie)
For the download page, I've been uploading "Windows DEBUG" versions as demos so they are free to download. I've been incrementing the version number for those with each iteration. I'm not sure how to link a direct download otherwise I would

**Comment by pkdawson** [comment]
I think the crash happens because none of your theme's SystemFont options are available on Windows. So to get readable text on Windows, you'd have to add the appropriate font(s) to the list.

**Comment by Calinou** [comment]
Consider adding `Segoe UI` as a last option to your system font.
