### ISSUE TITLE
@export node is Nil on _ready() Call

### ISSUE THREAD

**Issue by Syndicist** [godotengine/godot#72731]
### Godot version

v4.0.beta16.official [518b9e580]

### System information

Windows10, NVIDIA GeForce RTX 3060 Ti (31.0.15.2225), Vulkan

### Issue description

When using @export to export a node type and setting the appropriate node in the inspector, and then trying to operate on it in the _ready() function, the var is Nil.

When using the Godot 3.x method of doing a get_node() call on an exported path, this works as you'd expect.

I expect there to be no difference between the two methods when it comes to getting a node reference.

### Steps to reproduce

1. Add two nodes to the scene
2. Add script with @export var nodeRef : Node to one of them
4. Attach other node via inspector
5. Operate on the node in the _ready() function of the created script
6. Play scene
7. Godot crashes with Nil reference

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
Can't reproduce.

**Comment by Syndicist** [comment]
Uprevved to RC1 and prpblem no longer persists
