### ISSUE TITLE
Scons build issue on BSD "KeyError: CCVER"

### ISSUE THREAD

**Issue by sunnystormy** [godotengine/godot#7274]
**Operating system or device - Godot version:**
*BSD Godot version 2.1.1.

**Issue description** (what happened, and what was expected):
Unable to build because environment variables are missing? I've tried echoing the variables on my Linux machine, but they're undefined there and Scons works without any problems...

Here's the log:

```
File "usr/local/bin/scons", line 190, in <module>
  import SCons.Script
File "usr/local/lib/scons-2.5.0/SCons/Script/__init__.py", line 77, in <module>
  import SCons.Environment
File "usr/local/lib/scons-2.5.0/SCons/Environment.py", line 48, in <module>
  import SCons.Defaults
File "usr/local/lib/scons-2.5.0/SCons/Defaults.py", line 559, in <module>
  'ENV'       : { 'CCVER' : os.environ['CCVER'] },
File "usr/local/lib/python2.7/UserDict.py", line 40, in __getitem__
  raise KeyError(key)
KeyError: 'CCVER'
```

**Steps to reproduce:**
Try building the source with Scons on a BSD-based OS.

**Link to minimal example project** (optional but very welcome):

**Comment by eska014** [comment]
What BSD and what SCons options are you using? Is gcc installed? Otherwise you can compile with LLVM by using use_llvm=yes

**Comment by sunnystormy** [comment]
DragonFly BSD 4.6.1 stable. I've tried both using GCC and LLVM, but keep getting the same error.

I run scons with:

`scons platform=x11`

With LLVM, I add the llvm option.

**Comment by bojidar-bg** [comment]
@sunnystormy Does building any other scons-using c++ project even work?

**Comment by sunnystormy** [comment]
@bojidar-bg Unfortunately, my system got wiped, so I can't even test this anymore! :( If somebody else uses Dragonfly, please follow up on this.

**Comment by akien-mga** [comment]
Closing as without way to reproduce, we can't fix it. If some *BSD users can reproduce it, please comment so that we reopen the issue.
