### ISSUE TITLE
High memory usage when using `draw_dashed_line()`

### ISSUE THREAD

**Issue by danielbill** [godotengine/godot#72755]
### Godot version

4.0 beta17

### System information

win10 Gles3 

### Issue description

i am using tilemap to setup RTS game.
use draw_dashed_line function drew 192 v-dashlines  , 192 h-dashlines, 
the _draw function run only once , 
than run my scene , 2G memory has been consumed.
The following is the comparison data （before and drew）：
before：
![%HLAHK A3ULQD8}4DTW0254](https://user-images.githubusercontent.com/6269655/216816409-d62398c1-2cf8-4a95-ad72-0cee5702700e.png)
after
![2 Z(P162O 7LRXR6{C@}VEW](https://user-images.githubusercontent.com/6269655/216816415-1034ee58-43c2-45a9-a3dc-e3c315a16101.png)
---
the code 
---
func _draw():
	if world:
		draw_pave_grid()
	print("drawn")

func draw_pave_grid():
	var k =0
	for i in world.tmapSize.y:
		draw_dashed_line(Vector2(world.worldStart.x,world.worldStart.y+i*world.cellSize.y),
			Vector2(world.worldEnd.x,world.worldStart.y+i*world.cellSize.y),_line_color,_line_width)
		k+=1			
	
	for i in world.tmapSize.x:
		draw_dashed_line(Vector2(world.worldStart.x+i*world.cellSize.x,world.worldStart.y),
			Vector2(world.worldStart.x+i*world.cellSize.x,world.worldEnd.y),_line_color,_line_width)
		k+=1

and the world size is :  wsize (8032, 4256) 
the cell size is  32X32
...
wstart (-1504, -800) wend (6528, 3456) wsize (8032, 4256) whsize (4016, 2128) center (2512, 1328) 
384 lines drew

### Steps to reproduce

setup a big tilemap with 32X32 tile , map size is about 8K X 4K,
then darw dash line(about 200X200) grid  once 
the memory will be eat up

### Minimal reproduction project

sorry

**Comment by danielbill** [comment]
bty  draw_line  is ok !

**Comment by dalexeev** [comment]
I think this can be optimized with `canvas_item_add_multiline()` but not sure if that will solve this issue.

https://github.com/godotengine/godot/blob/00302860541e9cccc59abd93b930af2a6e6ec360/scene/main/canvas_item.cpp#L522-L525

**Comment by danielbill** [comment]
> I think this can be optimized with `canvas_item_add_multiline()` but not sure if that will solve this issue.
> 
> https://github.com/godotengine/godot/blob/00302860541e9cccc59abd93b930af2a6e6ec360/scene/main/canvas_item.cpp#L522-L525

thank u , i just replaced it with draw_line , and it is fine
