### ISSUE TITLE
Port in shader editor partially overlaps the eye when zoomed out.

### ISSUE THREAD

**Issue by viksl** [godotengine/godot#72757]
### Godot version

4.0 Beta 17 mono

### System information

Windows 10, Nvidia GTX 1660Ti, Vulkan

### Issue description

When you try to click on the eye icon it won't work in about half of the icon's area when you zoom out, instead you can drag a noodle from the port next to the icon.

https://youtu.be/zpWVsGoy9oU

### Steps to reproduce

Check the video and description above.

### Minimal reproduction project

-

**Comment by QbieShay** [comment]
Most likely re-introduced in https://github.com/godotengine/godot/pull/78556
