### ISSUE TITLE
Undoing TextEdit complex operation doesn't revert all selections

### ISSUE THREAD

**Issue by aXu-AP** [godotengine/godot#72769]
### Godot version

v4.0.beta.custom_build [13f0158]

### System information

Windows 10

### Issue description

When doing operations (`begin_complex_operation` and `end_complex_operation`) with multiple selections in TextEdit, some of these selections don't revert upon undo. This behavior is affects some of script editor's operations, like duplicate selection and delete lines.

### Steps to reproduce

Open script editor, make multiple selections. Keep in mind what you have selected. Do duplicate selection (ctrl+shift+D). Undo (ctrl+Z). Compare the result to what you remember.

### Minimal reproduction project

N/A

**Comment by TheSofox** [comment]
Did you fix this? The linked PR seems to have been merged and I can't repo on my end. Great work by the way!

**Comment by TheSofox** [comment]
Tracked down the problem and submitted a PR to fix it.
