### ISSUE TITLE
4096+px wide results in image looping artifact

### ISSUE THREAD

**Issue by StraToN** [godotengine/godot#7276]
**Operating system or device - Godot version:**
Godot 2.2alpha (current master)
Mageia 5

**Issue description** (what happened, and what was expected):
The image set on a TextureFrame or a Sprite is displayed weird if it is larger than 4096px.
![image](http://i.imgur.com/RAoVjGZ.png)

**Steps to reproduce:**
Start a project.
Create a Sprite node or a TextureFrame node (same behaviour)
Apply this image (from OpenGameArt) : http://opengameart.org/sites/default/files/sci-fi-level%5Bbackground_layer%5D.png

**Link to minimal example project** (optional but very welcome):
Not needed.

**Comment by StraToN** [comment]
After some tests, it seems the bug occurs on images wider than 4096px, and seems then to loop every 2048px.

You can use this image for testing :
![5000redyellow](https://cloud.githubusercontent.com/assets/1289207/21074265/f627e6e6-bef4-11e6-9448-476bfc140720.png)

**Comment by Alex-doc** [comment]
Actually, that might be the expected behaviour.
I've gave a quick look and I couldn't find any protection over too big textures.
AFAIK, making textures larger than 4096 is not a good idea still these days, especially if you are targeting mobile.
I'd rather add [this line]
(https://github.com/godotengine/godot/blob/c05ff0577fd9cc39a6968e65743f7d7da711bfe2/scene/resources/dynamic_font.cpp#L529)
In the texture loading code (with console warning) if not present already.

**Comment by Einlander** [comment]
I'd rather have the option to control the texture size myself. I have 12gb ram and 8gb vram. I might want to have a high graphics mode for those who can handle it.

**Comment by Alex-doc** [comment]
Sure, I think it could be put in the global project configuration.

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by StraToN** [comment]
@Noshyaar The bug seems fixed thanks to the new OpenGL 3 renderer.
![image](https://user-images.githubusercontent.com/1289207/38719279-56bfb40c-3ef1-11e8-9494-8ac028dcb790.png)
Closing the issue. I'll reopen it if needed after testeing @karroffel 's new renderer.
