### ISSUE TITLE
Godot 4.0 beta 17 crashes, does not open project

### ISSUE THREAD

**Issue by shafnaz** [godotengine/godot#72768]
### Godot version

4.0 beta 17

### System information

Windows 10

### Issue description

When I open my project, it crashes.
Does not happen in previous versions

Godot Engine v4.0.beta17.official.c40020513 - https://godotengine.org/
OpenGL Renderer: NVIDIA GeForce GTX 1080/PCIe/SSE2

Editing project: F:/project mzd/godot/mzd
ERROR: Condition "!method" is true. Returning: 0
at: get_builtin_method_hash (core/variant/variant_call.cpp:1348)
ERROR: Error getting method typed_assign, hash mismatch.
at: gdextension_variant_get_ptr_builtin_method (core/extension/gdextension_interface.cpp:480)
ERROR: Condition "!method" is true. Returning: 0
at: get_builtin_method_hash (core/variant/variant_call.cpp:1348)
ERROR: Condition "!method" is true. Returning: 0
at: get_builtin_method_hash (core/variant/variant_call.cpp:1348)
Godot Engine v4.0.beta17.official.c40020513 - https://godotengine.org/
Vulkan API 1.3.205 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1080

### Steps to reproduce

My Project is too large.

### Minimal reproduction project

My Project is too large.

**Comment by YuriSizov** [comment]
> My Project is too large.

Which is why we ask for a minimal reproduction project, and not your entire project. We are unlikely to help you if we can't reproduce the issue, and this seems to be at least partially specific to your setup.

You can start by bisecting your project, removing parts and seeing if the issue is still reproduceable. Then when you can pinpoint it to a particular set of scenes, scripts, resources, etc, it should be easy to submit an MRP. Or you may discover it's an issue on your side.

**Comment by shafnaz** [comment]
il check it out

**Comment by 404Fox** [comment]
Try opening the project without addons/plugins if you have any.

**Comment by akien-mga** [comment]
The errors refer to GDExtension. Are you using it? This kind of information is primordial to include in a bug report.

If you do use GDExtension, did you recompile your extensions with the correct godot-cpp commit (assuming you're using it)?

**Comment by shafnaz** [comment]
Totally the addons,  it's open now. And now have to find a way to put them back. Now I don't know which one...
![image](https://user-images.githubusercontent.com/37254287/216973994-4450eee0-893e-49d2-982f-19752dee653e.png)

**Comment by SidusAtra** [comment]
I have a similar issue without addons.

**Comment by shafnaz** [comment]
git plugin was causing my crash to happen, I just disabled it,

![image](https://user-images.githubusercontent.com/37254287/217501358-c1f7d8a3-57fd-4bab-a076-438416e25e21.png)

**Comment by iamjoeysox** [comment]
> I have a similar issue without addons.

Me too, have you figured your issue out yet?

**Comment by IvanMatev** [comment]
I had to completely delete git plugin, just disabling it didnt seem to work. It's fine now though

**Comment by iamjoeysox** [comment]
> I had to completely delete git plugin, just disabling it didnt seem to work. It's fine now though

Hmm that's odd, I am not using any kind of plugins or addons in my project that is not working. Maybe some specific project setting?

**Comment by Zireael07** [comment]
@iamjoeysox Git plugin is a weird one as it comes with Godot by default and IIRC is on by default. It's sorta plugin but core, if you catch my drift

**Comment by akien-mga** [comment]
> @iamjoeysox Git plugin is a weird one as it comes with Godot by default and IIRC is on by default. It's sorta plugin but core, if you catch my drift

That's not true, the Git plugin isn't installed by default.

**Comment by Zireael07** [comment]
My mistake then
