### ISSUE TITLE
Impossible to position the cursor using mouse click when renaming nodes in tree

### ISSUE THREAD

**Issue by TheRealSlander** [godotengine/godot#72765]
### Godot version

4.0 beta 17

### System information

Manjaro Linux (DE: Cinnamon v5.6.7) 64 bits

### Issue description

First, I apologize if this is a duplicate, but I haven't found anything in the reported bugs corresponding to what I encounter.

When trying to rename a node from the tree using the mouse, it is not possible to position the caret (cursor) with the mouse as it cancels the editing. The video is more explicit about the problem: all I do in this video is clicking once on the node to access the editing of the node name. Then I try to click to position the caret somewhere but the edition is then closed.

In the video, no keyboard is involved, only using the mouse normally (but renaming using F2 leads to the same result).

Once again, this only occurs when Single Window Mode is **enabled**.

https://user-images.githubusercontent.com/102065761/216832755-5126ba6e-1523-4aa0-ba15-d37e65a329d9.mp4

### Steps to reproduce

- Activate the Single Window Mode
- Create a node in the tree view and begin to rename it (F2 or mouse click)
- Using mouse only, place the caret anywhere in the edit

### Minimal reproduction project

N/A

**Comment by YuriSizov** [comment]
cc @Sauermann perhaps this is in your neighborhood?

**Comment by TheRealSlander** [comment]
I forget to say I tested a previous version of Godot 4.0 (the beta 14) to be sure and the bug does not exist there...

**Comment by Sauermann** [comment]
Can't reproduce this on Windows, but can confirm on Linux X11 Xfce.
Bisecting shows, that this got introduced in #70052.
So this is very likely an IME-issue which I know almost nothing about.

**Comment by YuriSizov** [comment]
cc @bruvzg then :)
