### ISSUE TITLE
Spatial.look_at and Translate result in rotation seemingly being interpolated 

### ISSUE THREAD

**Issue by iboshkov** [godotengine/godot#7277]
**Operating system or device - Godot version:**
Manjaro, Godot 2.1

**Issue description** (what happened, and what was expected):
Translating the node in the same frame as calling `look_at` in results in the object (maybe ?) being interpolated.

**Steps to reproduce:**
Call `look_at` and either manually translate by calculating the offset and calling `set_translation` or `global_translate` in the same `_process` call.

**[Video](https://www.youtube.com/watch?v=wy1nhFdu7uc)**

**Link to minimal example project** (optional but very welcome):
You can find a simple reproducible project with the same code as in the video in this small repo here:

https://github.com/iboshkov/GodotLookatDemo

**Comment by iboshkov** [comment]
Okay so I seem to have misread the documentation. I thought look_at takes a directional vector as a parameter, but it's a position.

**Comment by bojidar-bg** [comment]
Yeah, was thinking to mention it, but assumed you know what you are doing :smiley:

**Comment by iboshkov** [comment]
My mistake to assume a bug in Godot's code instead of my own ignorance and overlooking something as trivial as that. Live and learn I guess.
