### ISSUE TITLE
EditorPlugin input forwarding unexpected behavior

### ISSUE THREAD

**Issue by Nevur** [godotengine/godot#72773]
### Godot version

v4.0.beta17.official [c40020513]

### System information

Windows 10

### Issue description

GDScript-based `EditorPlugin` addons end up forwarding their input in unexpected ways as different nodes are selected. The plugin's input handling remains active despite `_handles()` no longer returning true. Furthermore, duplicate `EditorPlugin._forward_3d_gui_input()` calls (and similar methods) occur when the bug is triggered, piling up each time it happens, and persisting until Godot is rebooted.

Switching the selection between node types handled by different plugins each seems to trigger this issue consistently, and a minimal reproduction project to accomplish this is provided.

### Steps to reproduce

1. Create a new project.
2. Create 2 `EditorPlugin` GDScript addons, and filter their `_handles()` with different node types.
3. Create a few nodes, 2 of which match the aforementioned `_handles()`.
4. Repeatedly switch the selection on the node tree, and measure their input forwarding (For example, by using `_forward_3d_gui_input()`).

### Minimal reproduction project

[EditorPlugin Input Forwarding Bug.zip](https://github.com/godotengine/godot/files/10613798/EditorPlugin.Input.Forwarding.Bug.zip)

Scroll the mousewheel while having a `Marker3D` or a `Path3D` node selected to debug-print, and then switch to the other one and also scroll the mousewheel. Keep switching selections forth and back to keep triggering the bug.

**Comment by Nevur** [comment]
I just checked that this bug does not occur in v4.0.beta14.official [28a24639c], but it does in v4.0.beta15.official [4fa6edc88].

**Comment by Sauermann** [comment]
Can confirm the bug also on Linux in v4.0.beta.custom_build [81fe3715b] (between beta 14 and 15).

**Comment by smix8** [comment]
Probably related issues all with shared EditorPlugin Input problems.
https://github.com/godotengine/godot/issues/72738
https://github.com/godotengine/godot/issues/72761
