### ISSUE TITLE
Cannot procedurally generate a mesh for MeshInstance3D using SurfaceTool in Godot 4

### ISSUE THREAD

**Issue by blackears** [godotengine/godot#72778]
### Godot version

v4.0.beta17.official [c40020513]

### System information

Windows 10, Compatability

### Issue description

I'm trying to port a program from Godot 3.5 that generates a mesh to Godot 4.  I'm running into problems because the mesh I generate with using SurfaceTool does not seem to be producing a mesh (or at least not one that is visible).  I'm attaching a project which should generate a plane.  I've tried reversing the winding on the mesh, but that does not render anything to screen either.  This code is adapted from code that works on 3.5.

### Steps to reproduce

Use SurfaceTool to generate a mesh, write that to a Mesh and then assign that to a MeshInstance3D.mesh.

### Minimal reproduction project

[MeshCreateProblem.zip](https://github.com/godotengine/godot/files/10629434/MeshCreateProblem.zip)

**Comment by clayjohn** [comment]
I ran the MRP locally in beta 17. The issue is that the face of the quad you create is facing down instead of up. To make the quad appear, you can either swap the order of the second and third vertex, or you can enable front face culling.
