### ISSUE TITLE
Godot 4 project upgrading tool improperly renames `System.IO.Path` to `System.IO.Path3D`

### ISSUE THREAD

**Issue by 84634E1A607A** [godotengine/godot#72788]
### Godot version

4.0 beta 17

### System information

Linux Mint 20.3

### Issue description

For example, it renames `System.IO.Path` to `System.IO.Path3D`

### Steps to reproduce

Upgrade the project below (Full upgrade)

and you'll get

```C#
using Path3D = System.IO.Path3D;
using Godot;

public partial class Main : Label
{
    public override void _Ready()
    {
        base._Ready();

        Text = Path3D.GetRandomFileName();
    }
}
```

### Minimal reproduction project

[Test-3.5.1.zip](https://github.com/godotengine/godot/files/10661962/Test-3.5.1.zip)

**Comment by Calinou** [comment]
This is expected for GDScript, but there is no way to know in C# that `Path` is used as part of `System.IO.Path`. The project upgrade tool performs simple text-based replacement; it is not actually aware of the underlying language syntax.

**Comment by YuriSizov** [comment]
Indeed, the project converter operates on the best-effort principle and can miss things, as well as it can have false positives. We warn about it before you use the tool, and that's unfortunately how it's going to remain. Some hand polishing is expected from the developer converting the project.

**Comment by 84634E1A607A** [comment]
I can understand that, but I wonder if there is any approach that I can know of all methods and peoperty changes. Also is it possible that Godot can have a conversion mode that handles project files except csharp files? This approach may even be clearer for us to upgrade a project, than make Godot do the cs conversion with many false positives and many things missed.

**Comment by YuriSizov** [comment]
> Also is it possible that Godot can have a conversion mode that handles project files except csharp files?

No, but you can easily achieve this with your version control system.

**Comment by akien-mga** [comment]
We can disable specific renames if they do more harm than good, it's on a case by case basis. Maybe `Path` is not a good rename to do unconditionally (it actually has a comment that suggests the same):
```
        { "Path", "Path3D" }, // Be careful, this will be used everywhere
```

Alternatively, there could be exceptions for specific class renames in scripts for C# scripts.

**Comment by 84634E1A607A** [comment]
> No, but you can easily achieve this with your version control system.

Ah, brilliant!
