### ISSUE TITLE
*.TSCN extension filter not present when loading Resource exports in editor

### ISSUE THREAD

**Issue by schraf** [godotengine/godot#7278]
**Operating system or device - Godot version:**
Ubuntu Linux x86_64

**Issue description** (what happened, and what was expected):
When using export(Resource) in a GDScript file and then trying to load a tscn file into the property in the editor, the file dialog does not have a filter for *.tscn file extensions. If I select to show all files and select a tscn file it works as expected. A filter to tscn files should be added to that file dialog.

**Steps to reproduce:**
1) Open the linked example project (ResourceFileSceneBug)
2) Load the Main.tscn file
3) Click on the Node in the Scene view window
4) In the inspector, click the drop down for the "Set To Instance Scene" property and scroll down and click load
5) Notice that there is a filter for *.scn files but not one for *tscn files
6) If you use the filter "All Files (*)", you will see the InstanceScene.tscn file that you can select and it works

**Link to minimal example project** (optional but very welcome):
[ResourceFileSceneBug.zip](https://github.com/godotengine/godot/files/644142/ResourceFileSceneBug.zip)

**Comment by bojidar-bg** [comment]
Can someone confirm on 3.0 with import system changes?

**Comment by jmf** [comment]
I checked it out a few months ago, in the early 3.0 releases, when I hit the right entry by using arrow keys and randomly hitting ENTER, the problem still existed, so it might still exist.
I am unable to confirm that though, since the list is too long and doesn't scroll and I can't find the entry for loading. I'll open a bug for that issue.

**Comment by saltares** [comment]
In current master, following the repro steps results into the following UI message: *Error loading file: Not a resource!"

There is no resource loader that can load `.tscn` with a `"Resource"` hint.

**Comment by saltares** [comment]
A fix would be to edit `scene_format_text.cpp` and have the following:

```cpp
void ResourceFormatLoaderText::get_recognized_extensions_for_type(const String &p_type, List<String> *p_extensions) const {

	if (p_type == "") {
		get_recognized_extensions(p_extensions);
		return;
	}

	if (p_type == "PackedScene" || p_type == "Resource")
		p_extensions->push_back("tscn");
	else
		p_extensions->push_back("tres");
}
```

However, it feels like the engine doesn't want to play around with generic `"Resource"` types and prefers to be explicit on the types of resources that want to be loaded.

I think the way you're supposed to do this now is the following:

1. Edit bug.gd and have `export(PackedScene) var SetToInstanceScene`. That is, type your exported variable adequately.
2. Now use the property inspector to load the resource. You'll be able to select your tscn file.

**Comment by saltares** [comment]
I believe this is working as designed.

**Comment by AlexHolly** [comment]
Godot Master
Just to make things a bit simpler.

`export(Resource) var SetToInstanceScene`

Shows no .tscn

![image](https://user-images.githubusercontent.com/4741886/31854062-9ead7452-b693-11e7-885b-b2bbf8ee8048.png)

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by DualMatrix** [comment]
The .tscn filter is still missing in master.

**Comment by Andre12Lazaro** [comment]
I will fix these issue w/ @antoniocarreiro

**Comment by 2shady4u** [comment]
Has this now been fixed? @Andre12Lazaro @antoniocarreiro

Or are there still missing functionalities?

**Comment by KoBeWi** [comment]
Sooo the status is this: you can assign .tscn file to Resource, because Godot treats it as PackedScene. When you export PackedScene, you get more extensions available than just .tscn. So we should probably add all these extensions to the filters, because they are valid PackedScene.

However, I failed to pinpoint where all these extensions are defined.

**Comment by akien-mga** [comment]
This depends on the output of `ResourceLoader.get_recognized_extensions_for_type("Resource")` which indeed does not include `.tscn`:
```
[tres, anim, atlastex, cubemap, curvetex, font, largetex, lmbake, material, mesh, meshlib, meshtex, mp3str, multimesh, oggstr, phymat, res, sample, scn, shape, stylebox, tex, theme, translation, vs, world]
```

I'm not sure this is really worth fixing though, see discussion in #24212.

What's the use case for exporting a generic `Resource` to select a `PackedScene`, as opposed to exporting with `PackedScene` hint directly?
