### ISSUE TITLE
Game closes immediately

### ISSUE THREAD

**Issue by Sandvich** [godotengine/godot#7279]
**Operating system or device - Godot version:**
Linux, running via steam.

**Issue description** (what happened, and what was expected):
When trying to run my game, the process quits immediately with no debug output. Running from the console gives the following:

[ssharma@static-awesums Godot Engine]$ SAVING: res://menu.scn
running: /opt/steamapps/common/Godot Engine/godot.x11.opt.tools.64 -path /home/ssharma/PhysSim -rdebug localhost:6007 -epid 20105 -p 0x0 res://menu.scn
ERROR: canvas_light_shadow_buffer_create: Condition ' status != 0x8CD5 ' is true. returned: RID()
   At: drivers/gles2/rasterizer_gles2.cpp:8846.
ERROR: init: Condition ' status != 0x8CD5 ' is true. returned: false
   At: drivers/gles2/rasterizer_gles2.cpp:10337.
ERROR: init: Condition ' status != 0x8CD5 ' is true. returned: false
   At: drivers/gles2/rasterizer_gles2.cpp:10337.
ERROR: init: Condition ' status != 0x8CD5 ' is true. returned: false
   At: drivers/gles2/rasterizer_gles2.cpp:10337.
ERROR: init: Condition ' status != 0x8CD5 ' is true. returned: false
   At: drivers/gles2/rasterizer_gles2.cpp:10337.
ERROR: init: Condition ' status != 0x8CD5 ' is true. returned: false
   At: drivers/gles2/rasterizer_gles2.cpp:10337.
ERROR: init: Condition ' status != 0x8CD5 ' is true. returned: false
   At: drivers/gles2/rasterizer_gles2.cpp:10337.
ERROR: init: Condition ' status != 0x8CD5 ' is true. returned: false
   At: drivers/gles2/rasterizer_gles2.cpp:10337.
ERROR: init: Condition ' status != 0x8CD5 ' is true. returned: false
   At: drivers/gles2/rasterizer_gles2.cpp:10337.
WARNING: _update_framebuffer: Could not create framebuffer!!, code: 36061
   At: drivers/gles2/rasterizer_gles2.cpp:10529.
WARNING: _update_framebuffer: Could not create framebuffer!!
   At: drivers/gles2/rasterizer_gles2.cpp:10565.
ERROR: _update_framebuffer: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles2/rasterizer_gles2.cpp:10607.
ERROR: _update_framebuffer: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles2/rasterizer_gles2.cpp:10607.
ERROR: _update_framebuffer: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles2/rasterizer_gles2.cpp:10607.
ERROR: _update_framebuffer: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles2/rasterizer_gles2.cpp:10659.
ERROR: _update_framebuffer: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles2/rasterizer_gles2.cpp:10659.
ERROR: _update_framebuffer: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles2/rasterizer_gles2.cpp:10659.
ERROR: _update_framebuffer: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles2/rasterizer_gles2.cpp:10659.
ERROR: _update_framebuffer: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles2/rasterizer_gles2.cpp:10659.
WARNING: _update_framebuffer: Could not create framebuffer!!, code: 36061
   At: drivers/gles2/rasterizer_gles2.cpp:10529.
WARNING: _update_framebuffer: Could not create framebuffer!!
   At: drivers/gles2/rasterizer_gles2.cpp:10565.
ERROR: _update_framebuffer: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles2/rasterizer_gles2.cpp:10659.
ERROR: _update_framebuffer: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles2/rasterizer_gles2.cpp:10659.
ERROR: _update_framebuffer: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles2/rasterizer_gles2.cpp:10659.
ERROR: _update_framebuffer: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles2/rasterizer_gles2.cpp:10659.
ERROR: _update_framebuffer: Condition ' status != 0x8CD5 ' is true. Continuing..:
   At: drivers/gles2/rasterizer_gles2.cpp:10659.
shit?: Connection reset by peer
ERROR: read: Server disconnected!

   At: drivers/unix/stream_peer_tcp_posix.cpp:276.

I've been working on this game for a few days now and even if I revert all the changes I made today the issue persists, so I'm fairly sure it's not to do with my code.

**Steps to reproduce:**
Unknown

**Comment by Calinou** [comment]
Does this happen if you [compile Godot yourself](http://docs.godotengine.org/en/stable/reference/compiling_for_x11.html), or use a Git build like [this one](https://archive.hugo.pro/godot/)?

**Comment by Sandvich** [comment]
So I just uninstalled via steam and reinstalled, and it now refuses to open any project...
I previously had a compiled version which I haven't removed, and I'm seeing the exact same issue on there.

**Comment by eon-s** [comment]
Try to run it in self contained mode (create a file named `._sc_` where the executable is located) and see what happens.

**Comment by Sandvich** [comment]
That seems to have fixed it! Any ideas on a more permanent fix?

**Comment by eon-s** [comment]
@Sandvich one of your compiled Godot versions maybe corrupted the configuration files in some way, you may have to delete the config files on your ~/.godot directory to recreate new ones.

I always run custom or older versions on the SC mode to avoid those (not common) issues, at least to keep the stable safe.

**Comment by Sandvich** [comment]
Will do. Thanks for the help!

**Comment by Sandvich** [comment]
Sorry, have to reopen because I tried this morning and I'm getting the same issue again. Deleted ~/.godot, ran things with ._sc_, and still no luck :/

**Comment by akien-mga** [comment]
The steam binary already runs in self contained mode with a `._sc_` file. Maybe your editor settings in the Godot Steam folder are corrupted?

**Comment by Sandvich** [comment]
Tried deleting editor_data/config and editor_data/editor_settings.tres and no luck.

**Comment by Sandvich** [comment]
(from the directory where the steam binary is stored)

**Comment by akien-mga** [comment]
Does the issue only happen when you try to load your game, or with any project?
The error with the framebuffer status could also be related to a bad graphics driver upgrade that left you without OpenGL 2.1 support.

**Comment by Sandvich** [comment]
It randomly started working again. I think previously it was an issue with all projects, not just mine.
It could be, as I know that I've had driver issues on this computer.
Going to leave this open as it's not really fixed, it just happens to be working right now.

**Comment by bojidar-bg** [comment]
What's the status on this one? Is it somehow resolved in 2.1/2.2/master?

**Comment by Sandvich** [comment]
I'm fairly sure it was a driver issue - it can be closed.
