### ISSUE TITLE
Visual Particles Shader: setting "Angle in Radians" overwrites entire `TRANSFORM`

### ISSUE THREAD

**Issue by hmans** [godotengine/godot#72798]
### Godot version

v4.0.beta17-official

### System information

macOS 13.1 (Silicon/M1)

### Issue description

In a `GPUParticles3D` node that uses a Visual Shader for processing particles, writing into the processing root node's "Angle in Radians" input generates shader code that overwrites the entire `TRANSFORM`.

### Steps to reproduce

What I'm doing exactly:

**Step 1:** In the "Start" graph, I'm setting a random rotation axis and angle using per-particle randomness.

![image](https://user-images.githubusercontent.com/1061/217018192-a8a554f9-eb9a-420c-bb17-414d8ef3440e.png)

What the scene is rendering now looks like the following:

![image](https://user-images.githubusercontent.com/1061/217018500-aed3480b-cc63-43fb-9a12-a9ee071ea177.png)

**Step 2:** In the "Process" graph, I'm plugging a "Time" node into the "Angle in Radians" input.

![image](https://user-images.githubusercontent.com/1061/217018341-68e875e0-b518-4f28-955f-aed886ef5cde.png)

I would have expected this to continuously rotate the individual particles, but it unfortunately resets all particles' transforms, displaying them in the same position (but at least it's rotating them as expected :b):

![image](https://user-images.githubusercontent.com/1061/217018777-4234b9df-6c87-42d4-8ee4-44e6638bce61.png)

This is the generated shader code:

```glsl
void process() {
  uint __seed = __hash(NUMBER + uint(1) + RANDOM_SEED);

  {
    // Input:2
    float n_out2p0 = TIME;

    // ProcessOutput:0
    TRANSFORM = __build_rotation_mat4(vec3(0, 1, 0), n_out2p0);
  }
}
```

### Minimal reproduction project

[MRP-Visual-Particle-Shader-Rotation-Issue.zip](https://github.com/godotengine/godot/files/10664814/MRP-Visual-Particle-Shader-Rotation-Issue.zip)

### Addendum

This doesn't seem to affect the Process graph's root node only, a similar behavior can also be observed when plugging something into the Start graph's "Angle in Radians" input.

**Comment by hmans** [comment]
I'm sort of suspecting [these lines](https://github.com/godotengine/godot/blob/2fdaf2919c03ab50f971f2d51616d4ee329d29af/scene/resources/visual_shader_particle_nodes.cpp#L1414-L1419) to be related to this issue.

Was it correct to plug `time` into the "Angle in Radians" input in the Process graph, or should this be a per-step value that gets accumulated via transform feedback? If it's supposed to be the latter, I _think_ setting `op` to `*=` in both cases of the branch fixes things for me. But I'm looking at the Visual Shader source code for the first time in my life, so I'd appreciate feedback from someone more familiar with it.

**Comment by clayjohn** [comment]
Incremental makes sense to me. Otherwise you would always overwrite "Scale" and "RotationAxis"

cc @Chaosus

**Comment by hmans** [comment]
> Incremental makes sense to me. Otherwise you would always overwrite "Scale" and "RotationAxis"

I think there's a case to be made for both approaches. Some animations are actually a lot simpler to implement if they're just built from absolute values derived from `time`. Would it be feasible to let the user control this?

**Comment by Chaosus** [comment]
As far as I remember these ports in process (scale, angle) are intended to be work with Curve Texture's, Initially I made them incrementally (like this issue propose), but @QbieShay is convinced me to make it like that.

The only thing seems like incorrect here is position in Transform which being resettled (and that should be fixed by using Custom override ?). I don't remember that part, really.

**Comment by hmans** [comment]
Alright, it's good to know that I'm not just holding this wrongly. :-)

As a newcomer to Godot's visual particle shaders (with some experience in node-based shader authoring tools, including Unity's Visual Effect Graph), the current separation between "Process" and "Custom Process" confuses me. If I create both graphs, will both of them be active? Or just the one I'm currently selecting as active (a choice that also seems to apply to all three graph categories at once: Start, Process, and Collide)?

I think the difficulty here is that even though Godot's GPU particles implement a stateful system where you'll ideally control particles through velocity alone, you'll sometimes want to directly affect individual components of each particle's transform matrix (for example for rotating particles, like I'm doing in the attached MRP.) In code, this typically happens by taking the current state (ie. the `TRANSFORM`) and mutating it (eg. by applying a rotation matrix to it), but for some animations you'll also want to start with an identity transform and apply a rotation to it that is a function of particle age (or absolute time.)

I think Visual Particle Shaders should ideally enable both of these. I'd be happy to get involved, but it's hard for me to understand where Visual Particle Shaders are currently at — they seem to be in a state of flux at the moment, but set to ship with 4.0? Would a rework of these in 4.x not carry the risk of breaking a lot of projects that use them?

Happy to get some pointers here if you have any. \o/

**Comment by fracteed** [comment]
This sounds like the same issue that I created with https://github.com/godotengine/godot/issues/67524
After discussing it with @Chaosus it was closed as it was related to https://github.com/godotengine/godot/issues/56358

Would be really good to get this resolved, as you can't really do any time based transform manipulation in the process method for visual particles otherwise.

**Comment by hmans** [comment]
> This sounds like the same issue that I created with #67524 After discussing it with @Chaosus it was closed as it was related to #56358
> 
> Would be really good to get this resolved, as you can't really do any time based transform manipulation in the process method for visual particles otherwise.

Thanks for the heads-up, I didn't find these when I was searching for similar issues, but I might have searched for the wrong things. :(

Closing this in favor of #56358.

Side note: I've been working around this issue by creating an expression node where I just mutate `TRANSFORM` and plug the result into the custom process graph's transform socket. It's a bit finicky, but it's a start. I've already seen how you can create custom visual shader nodes in userland, so I think that's what I'll eventually do.

![image](https://user-images.githubusercontent.com/1061/217191884-80c06dea-2a00-4d61-b2d5-4339373f6de7.png)

**Comment by fracteed** [comment]
@hmans Maybe it would have been good to leave this open, as I think there are a few broken issues with the visual particles.

I attempted to get color over life happening but it seems like the particle lifetime node doesn't work. Maybe I have this setup incorrectly? It is not clear if the lifetime variable has a 0-1 range or is in seconds.

![particles1](https://user-images.githubusercontent.com/7741669/217231679-4c115640-14aa-41d2-9e00-cc0f220ba996.jpg)

If put a random 0-1 value into the mix socket it does work as expected though it is static or course. I was also able to use the standard time node through sine and into the mix. However anything with lifetime seems broken.

![particles2](https://user-images.githubusercontent.com/7741669/217232213-f1e8760c-dfa8-428a-b803-81e383baa101.jpg)

@Chaosus @QbieShay  what is the correct way of getting color or scale over life within the process method?

**Comment by QbieShay** [comment]
@fracteed i'm assuming lifetime needs to be assigned ..? may be a separate issue

**Comment by fracteed** [comment]
@QbieShay I would be interested to know if you are able to get any of the parameters to work over particle life in the process method. I do remember it working at one point, but it is hard to know what is actually broken now. Could be animated transforms as well as the lifetime node as separate issues?

**Comment by QbieShay** [comment]
@fracteed lifetime seems to be the total lifetime, not the current one

**Comment by hmans** [comment]
> @QbieShay I would be interested to know if you are able to get any of the parameters to work over particle life in the process method. I do remember it working at one point, but it is hard to know what is actually broken now. Could be animated transforms as well as the lifetime node as separate issues?

I'm currently doing this myself by doing a variation of this:

```glsl
void start() {
	CUSTOM.x = TIME;
}

void process() {
	float age = TIME - CUSTOM.x;
	// ...
}
```

**Comment by fracteed** [comment]
@QbieShay oh, that would explain why it doesn't work! Can the current age be gotten without using using an expression node?

@hmans thanks. I am not sure if you are doing this with expression nodes inside visual particles or have you written the whole particle shader?

**Comment by hmans** [comment]
> @hmans thanks. I am not sure if you are doing this with expression nodes inside visual particles or have you written the whole particle shader?

This is from a text-based shader — I'm trying to get comfy with how all of this works in the hopes that I can maybe contribute a custom node or two by way of a plugin or similar.

**Comment by fracteed** [comment]
Ok, so I managed to work out particle age with just nodes. It can be confusing that know when to use the custom or standard output mode/node. It took me a while to realise both can be used at once!

For anyone interested here is the start and process graphs:

![particles3](https://user-images.githubusercontent.com/7741669/217263748-8ee6b9de-916a-49cb-be33-258324df70d0.jpg)

![particles4](https://user-images.githubusercontent.com/7741669/217263777-ef8f0568-657d-4bac-ad98-43e6a7711108.jpg)

I can use this age to drive color mix and alpha but I still get any joy with driving scale or rotation, so this definitely needs to be fixed! As well as a native age parameter node

**Comment by fracteed** [comment]
@hmans sounds good! Any developers helping to get it closer to Unity FX graph would be great :)

**Comment by QbieShay** [comment]
I have a mega discussion thread for visual shaders, but I do not have one specifically for particle features. The ideal thing would be if there was an issue per-issue (oh really :D ) and we can link to them in the megathread

**Comment by fracteed** [comment]
@QbieShay yeah I think there is a need for one for visual particles. Maybe it should be a separate thread though?

**Comment by fracteed** [comment]
@hmans I am curious where you found the method __build_rotation_mat4 ? I can't find this anywhere in the documentation.

**Comment by hmans** [comment]
> @hmans I am curious where you found the method __build_rotation_mat4 ? I can't find this anywhere in the documentation.

These are automatically added to the shader code generated by Visual Shader in Particles mode (you can see it when you click the button that shows the generated code.)

> @QbieShay yeah I think there is a need for one for visual particles. Maybe it should be a separate thread though?

Yes please!
