### ISSUE TITLE
C#: Integer vectors are missing .PosMod

### ISSUE THREAD

**Issue by wihrl** [godotengine/godot#72793]
### Godot version

4.0 beta 17

### System information

Win 11

### Issue description

After upgrading a C# project from beta 10 to beta 17, integer vectors no longer have .PosMod(). Float vectors still have it.

### Steps to reproduce

-

### Minimal reproduction project

-

**Comment by YuriSizov** [comment]
Yes, it was removed on purpose to make the API consistent with the engine, see https://github.com/godotengine/godot/pull/71569.
