### ISSUE TITLE
Adding theme type in the Theme editor causes a crash

### ISSUE THREAD

**Issue by cryptonosaurus** [godotengine/godot#72799]
### Godot version

v4.0.beta17.mono.official [c40020513]

### System information

Window 11, Forward+, GTX 1060

### Issue description

Adding two theme variations in a row result to a  crash.

https://user-images.githubusercontent.com/93253123/217037249-1ce1d56d-beb6-4435-83ad-9f8a07fe0e96.mp4

### Steps to reproduce

1. Create a project.
2. Create a theme.
3. Double click to go in the theme editor.
4. Click on manage items buttons.
5. In the add type field type a name to add a type.
6. type another name to add a second type.
7. Crash.

### Minimal reproduction project

[ThemeVariationCrash.zip](https://github.com/godotengine/godot/files/10665863/ThemeVariationCrash.zip)

**Comment by YuriSizov** [comment]
For the record, those are not variations. Just types.

**Comment by YuriSizov** [comment]
See https://github.com/godotengine/godot/issues/72271, though that shouldn't happen with non-resource properties. Huh.

**Comment by cryptonosaurus** [comment]
Oh, by the way, being kicked out from the editor is more annoying, than the crash.

**Comment by cryptonosaurus** [comment]
Then crash!
