### ISSUE TITLE
Missing theme options for slider controls

### ISSUE THREAD

**Issue by GalanCM** [godotengine/godot#728]
I've been working on making a theme, but I've discovered that Icon → Grabber Hilite is availible when editing an individual slider control but is not available when editing a theme, for both HSliders and VSliders. This makes it difficult to theme sliders, since they'd need to be individually themed for consistency.

In addition, while Styles → Focus is available for HSliders (in both locations), it's not availible for VSliders. I'm not sure if this is intentional, though.

**Comment by akien-mga** [comment]
Is this still valid in the current master branch?

**Comment by Krosh** [comment]
VSlider still hasn't focus style in last build

**Comment by akien-mga** [comment]
See also from #5719:
![image](http://savepic.net/8271136.png)
