### ISSUE TITLE
Node2D inside a SubViewport returning (0, 0) from get_mouse_position()

### ISSUE THREAD

**Issue by rbarongr** [godotengine/godot#72807]
### Godot version

v4.0.beta17.official [c40020513]

### System information

macOS 13.0.1

### Issue description

When a `Control` node is over a `SubViewportContainer` (with a `SubViewport` as a child), both in Full Rect anchors, asking for the get_viewport().get_mouse_position() from a scene inside the `SubViewport` returns (0, 0) as the position of the mouse.

This wasn't happening in at least Beta 15. I was getting the mouse position without any problems before Beta 17. I didn't try Beta 16.

### Steps to reproduce

1. Create a `Control` node
2. Add two children: A `SubViewportContainer` and a `Control` node
3. Put both in Full Rect anchors so the `Control` node (child) is covering the `SubViewportContainer`
4. Ask for the get_viewport().get_mouse_position() from inside a scene of the `SubViewport`

As you can see in this screenshot: asking for the mouse position from inside the `Node2D` script always returns (0, 0).

<img width="1533" alt="SubViewportContainerIssue" src="https://user-images.githubusercontent.com/91340577/217051768-d9c2e8ad-40ca-4c6d-bb98-f6a7c9c6081f.png">

Only If the `Control` (child) mouse filtering is set to _Ignore_ you can get the mouse position. But with that you are losing the mouse inputs from that `Control` node.

You can find the setup of these nodes in the MRP.

### Minimal reproduction project

Run the main scene (control.tscn) and move the mouse around the screen. Look for the print in the Output tab.

[SubViewportMousePositionIssue.zip](https://github.com/godotengine/godot/files/10667894/SubViewportMousePositionIssue.zip)

**Comment by Sauermann** [comment]
Sounds similar to #60390 which happened long before beta 15, so this isn't a duplicate.
Can confirm the bug on Linux since v4.0.beta16.official [518b9e580].

**Comment by rbarongr** [comment]
I tried Betas 15 and 16, and this is happening after 15.

Beta 15 getting the correct mouse position:
<img width="1996" alt="Beta15" src="https://user-images.githubusercontent.com/91340577/217061513-0eec568d-6978-4c76-b46c-025772720f0c.png">


Beta 16 always returning (0, 0):
<img width="1996" alt="Beta16" src="https://user-images.githubusercontent.com/91340577/217061564-3b4869be-7597-4f28-8983-0333aa5c1be9.png">
