### ISSUE TITLE
Modifying parent scene hierarchy breaks inheriting scenes

### ISSUE THREAD

**Issue by Anixias** [godotengine/godot#72803]
### Godot version

v4.0.beta17.mono.official [c40020513]

### System information

Windows 10

### Issue description

Modifying the node hierarchy in a scene while there are scenes who inherit from it will break the child scenes' custom nodes that were modified.

I created a scene called Creature, set it up as needed, then made a scene called Human that inherits from Creature. Later on, I needed to add a new node to Creature and move an existing node to be a child of that. Doing so caused every child of the moved node to be deleted in the child scene. Inspecting the *.tscn file, the custom nodes were not actually deleted but instead had the wrong parent, and were therefore broken in the editor. I was able to hand-modify the scene file to restore the broken nodes.

### Steps to reproduce

1. Create a scene root Node2D, name it ParentNode.
2. Add a child Node named "TestNode" to it.
3. Save it, create a new inheriting scene named ChildNode.
4. Add any node as a child to the "TestNode"
5. Save it, return to the ParentNode
6. Add a new Node, move "TestNode" to be a child of the new Node. Save it.
7. Return to the ChildNode and notice the broken hierarchy.

### Minimal reproduction project

[BrokenSceneInheritanceMRP.zip](https://github.com/godotengine/godot/files/10667706/BrokenSceneInheritanceMRP.zip)

**Comment by Zireael07** [comment]
IIRC this was already reported.

**Comment by KoBeWi** [comment]
This is same issue as #24817
Editor doesn't know how the hierarchy was changed. The parent can be moved, renamed or deleted and and the child nodes you added will be in invalid state. There is no way to detect the changes and move the nodes to the correct parent.

And no, your nodes are not gone. They are moved under root node, with their old path stored in their name.
![image](https://user-images.githubusercontent.com/2223172/217065144-385abd83-73ff-44af-9ff5-1d660b1850fb.png)
