### ISSUE TITLE
Tween method with different numerical types (int X float) for initial and final value parameters fails without warning

### ISSUE THREAD

**Issue by Gnumaru** [godotengine/godot#72808]
### Godot version

4.0.beta17

### System information

windows 10

### Issue description

When using tween_method and providing different numerical types for the initial and final values, like int for initial and float for final or vice versa, the tweening doesn't happen at all. The initial value will be used for every call except the last one, where the final value will be used.

I get it that all tween methods are generic and that receive plain variants as values, regardless of the type of the property or the type of the parameter of the function being tweened, and that it could be undesired to spam error messages for each unsuccessful tween iteration, but at least in the special case of method tweening different numeric types for the initial and final value, maybe it would be better to convert both values to float to prevent the user being confused not knowing why the tween doesn't work only to, later, notice that the initial and final value have different types and that the method tweener should use the same numerical type for both initial and final value.

Please note that in fact it seems that all tween attempts with an incorrect type fails without warning, but the least obvious of them is certainly when converting int>float or float>int, where most users would expect to work.

### Steps to reproduce

Try to use a method tweener where the initial value is an int and the final value is a float or the other way around. The screenshot bellow showcases this on line 8:
```gdscript
tween.tween_method(asdf, 0, 10.0, time) # will print 'typecode:2;value:0' in every call, except the last one which will be 'typecode:3;value:10'
```

![Screenshot (279)](https://user-images.githubusercontent.com/5783414/217057604-8505ca79-0626-4287-875c-3d5f30aa1316.png)

### Minimal reproduction project

[TweenMethodWithDifferentInitialAndFinalValueTypes.zip](https://github.com/godotengine/godot/files/10668135/TweenMethodWithDifferentInitialAndFinalValueTypes.zip)

**Comment by Darenn** [comment]
Hi! I am using Godot 3.5.2stable.
The cast is now fixed and the tween works in the editor. 
But it does not work in the editor and throws a cast error in exports in the logs.
It's obviously not that big of a deal and proper casting in code fixes everything but I just wanted to let you know!
![image](https://github.com/godotengine/godot/assets/11272715/befe6753-297f-44d8-81fb-94e100a3350f)

**Comment by Gnumaru** [comment]
> But it does not work in the editor and throws a cast error in exports in the logs

You said "it does not work in the editor" but you probably meant "it doesnt work in the exported build". Please notice that this bug was originally opened for godot 4 and you are experiencing a godot 3 bug. Tween implementation is different in godot 4 and 3. The fix did KoBeWi did on https://github.com/godotengine/godot/pull/73178 needs to be backported to godot 3 to solve the problem.

**Comment by Darenn** [comment]
Oh sorry you're right I meant "it doesn't work in the exported build". Thanks!
