### ISSUE TITLE
Shape2D added to CollisionObject2D do not appear with Visual Collision enabled.

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#7281]
Running Windows 7 SP1 x64, Godot 2.1.1 stable

If I use GDScript to add a Shape2D to, for example, an Area2D, it does trigger collisions but it's "hitbox" is not shown when Visual Collision is enabled.

Having to work around by adding a CollisionShape2D feels kinda dirty. 
Please look into it. Thanks.

`shape = CircleShape2D.new()`
`shape.set_radius(400)`
`self.add_shape(shape)`
Works fine, but not visible.

`shape = CircleShape2D.new()`
`shape.set_radius(400)`
`collision = CollisionShape2D.new()`
`collision = set_shape(shape)`
`self.add_child(collision)`
Works and is visible, but feels weird to use an "editor helper" class for something done in code.

**Comment by bojidar-bg** [comment]
This would probably be fixed when the physics is fixed (and broken) for 3.0.

**Comment by reduz** [comment]
this is fixed now, given debug is in CollisionObject itself.

**Comment by reduz** [comment]
errrrr CollisionShape I meant
