### ISSUE TITLE
Tween not working with shader params (previously worked on beta10)

### ISSUE THREAD

**Issue by CaelRowley** [godotengine/godot#72813]
### Godot version

v4.0.beta17

### System information

macOS Ventura 13.0

### Issue description

I was using v4.0.beta10 previously, and was using tween.tween_property to modify shader params directly on a material. This was working fine on beta10, but since upgrading to beta17 the tweens are no longer working on shader params. Although they are working to modify other params.

### Steps to reproduce

Create a Sprite2D, and give it a ShaderMaterial with a custom shader (see attachment for my .gdshader code)

[player_sprite copy.txt](https://github.com/godotengine/godot/files/10669327/player_sprite.copy.txt)

Then create a function on the sprite to create the tween and modify the shader param

```
func deform(in_deformation: Vector2, time_in: float):
        var tween := create_tween()
        tween.tween_property(player_sprite.material, "shader_param/deformation", in_deformation, time_in)
```

Then call the function at any point in runtime, with any valid values

```
func ready():
   deform(Vector2.ONE, 1.0)
```
### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
The full property name of shader parameters is "shader_parameter/parameter_name" not "shader_param/parameter_name"

It changed recently as it should have been "shader_parameter" all along. The fact that "shader_param" worked in earlier betas was a bug.

**Comment by CaelRowley** [comment]
You are right, shader_param -> shader_parameter did the trick
