### ISSUE TITLE
[Godot 4 Mono B17] VR game nearly instant crashes when debbuger is active

### ISSUE THREAD

**Issue by Lakasabasz** [godotengine/godot#72835]
### Godot version

4.0 beta 17 Mono

### System information

Windows 10, RTX 2070, Game Ready 528.24, Vulkan, HTC Vive

### Issue description

Game crashes without any logs nearly instant when started from editor. Only what I see is:
```
--- Debugging process started ---
--- Debugging process stopped ---
```
After some tries I found that it happens when:
- I use VR (HTC Vive)
- Project uses Mono
- Game starts with remote debbuger and debugging server is online
After that I compiled engine from source and I got what caused instant shutdown - SIGSEGV. I built engine with debugging symbols and I saw that:
\modules\mono\csharp_script.cpp:585
```cpp
Vector<ScriptLanguage::StackInfo> CSharpLanguage::debug_get_current_stack_info() {
#ifdef DEBUG_ENABLED
	// Printing an error here will result in endless recursion, so we must be careful
	static thread_local bool _recursion_flag_ = false;
	if (_recursion_flag_) {
		return Vector<StackInfo>();
	}
	_recursion_flag_ = true;
	SCOPE_EXIT {
		_recursion_flag_ = false;
	};

	if (!gdmono->is_runtime_initialized()) { // Here crashes. gdmono is null
		return Vector<StackInfo>();
	}

	Vector<StackInfo> si;

	if (GDMonoCache::godot_api_cache_updated) {
		GDMonoCache::managed_callbacks.DebuggingUtils_GetCurrentStackInfo(&si);
	}

	return si;
#else
	return Vector<StackInfo>();
#endif
}
```
Temporary/my fix is to add condition `gdmono == nullptr` before access to `gdmono->is_runtime_initialized()`.

### Steps to reproduce

1. Load minimal project
2. Try to start it from editor (It should crash)
-----
3. Export project
4. Enable debugging server
5. Try to execute game from cmd using remote debugger param (It should crash too)
-----
6. Try to execute game without param (It should work normal - you cannot do anything, because there are nothing in scene)

### Minimal reproduction project

[MinimalVR.zip](https://github.com/godotengine/godot/files/10675840/MinimalVR.zip)

**Comment by BastiaanOlij** [comment]
I think checking whether `gdmono` is set is a valid way to determine whether we need to skip over this logic seeing mono isn't setup yet.

**Comment by Beliar83** [comment]
FYI: This persists with RC3
