### ISSUE TITLE
Animation BlendTree blend2 node unexpected behaviour

### ISSUE THREAD

**Issue by shuvit-game** [godotengine/godot#72837]
### Godot version

v4.0.beta17.official [c40020513]

### System information

Windows 10

### Issue description

When blending between 2 animations, there is unexpected movement. I suspect the reset pose is affecting the positioning. The extremes are correct and blending between the same animation seems to work correctly.
![blend_bug](https://user-images.githubusercontent.com/38700738/217272297-ab9167fa-12fe-4013-9e6a-2b721c032b2c.gif)

### Steps to reproduce

Use a blend2 node to blend 2 Skeleton3D animations in an Animation Tree.

### Minimal reproduction project

[b17_blend_bug.zip](https://github.com/godotengine/godot/files/10675890/b17_blend_bug.zip)

**Comment by TokageItLab** [comment]
I don't know what is wrong. Having trouble getting your feet into the ground? The calculation is done correctly, and I think that blending on Blender will give the same result.

In such cases, I think it's common practice to add a transition animation from standing to sitting as a StateMachine or Transition in between.

**Comment by shuvit-game** [comment]
You are correct, I was mistaken and will close. Your suggested 'common practice' is not suitable for my purposes as this is just part of a much larger setup.
