### ISSUE TITLE
Can't change a texture on a in scene

### ISSUE THREAD

**Issue by TanguyCogrel** [godotengine/godot#72834]
### Godot version

4.0 beta17

### System information

Windows 10

### Issue description

Hello,

I want to change a texture of a inherit scene but I can't. The sprite node is yellow. I made the  texture unique and local to scene but its changes nothing. I can change the texture but there is no change when I instanciate the scene.

### Steps to reproduce

    Make a scene (parent) with a sprite2D with texture and make unique
   Inherit the scene
  The sprite node is yellow, change the texture
 Instantiate the scene with the old texture
   

### Minimal reproduction project

 "N/A"

**Comment by clayjohn** [comment]
This space is for bug reports only. We do not provide user support through here. I suggest you reach out on one of the community channels intended for community support like the forum, or the Discord
