### ISSUE TITLE
Opening a currently preloaded scene will remove paths from sub-resources

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#72854]
### Godot version

4.0 a05670c

### System information

Windows 10 x64

### Issue description

Follow-up to #72257
The PR fixed only half of the issue. Sub-resource IDs are no longer lost, but paths still are. When a scene is preloaded in a currently opened script, opening that scene will result in all sub-resources having empty paths until you save it. While it's harmless in most cases, it's a major pain for built-in scripts, because they appear as `[unsaved]` in the script editor (which leads to further issues, like not being closed on scene close or not being able to open multiple scripts).

https://user-images.githubusercontent.com/2223172/217350742-d3b204d9-c30b-4b01-b8dd-d84f9e39e954.mp4

As identified in https://github.com/godotengine/godot/pull/72257#issuecomment-1412393593, the issue is caused by `preload()` using resource cache in a wrong way. This needs a GDScript fix (and #72257 can be then reverted).

### Steps to reproduce

1. Create a scene
2. Close it
3. Preload it in a script
4. Open again

### Minimal reproduction project

[PreloadBug.zip](https://github.com/godotengine/godot/files/10678899/PreloadBug.zip)

**Comment by KoBeWi** [comment]
Further issues with affected built-in scripts include not being able to use breakpoints and not being able to pin-point errors (their source shows as something like `GDScript:-143434353`, which is the default Object string that displays id). Which means the issue also exists at runtime and is even worse.

**Comment by dalexeev** [comment]
* Possibly related: #80131.
