### ISSUE TITLE
GD.PrintStack missing in Godot 4 mono beta 17

### ISSUE THREAD

**Issue by firebelley** [godotengine/godot#72861]
### Godot version

v4.0.beta17.mono.official [c40020513]

### System information

Windows 11

### Issue description

In the mono version of Godot 4 beta 17, `PrintStack` appears not to exist in the `GD` static class anymore. The docs for GDScript state that `print_stack` still exists in the global scope.

![image](https://user-images.githubusercontent.com/4622925/217381133-37179808-a598-4ee1-a901-93d58e1f8104.png)

### Steps to reproduce

1. Create a script
2. Attempt to call `GD.PrintStack()`

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
`print_stack` is a `@GDScript` scope method, which seemed to exist in C# `GD` before, but was removed in 47ca2f2e092b985e6c56a70781ac1a18972245a1. See #71946 for the rationale.

**Comment by firebelley** [comment]
I see, that seems sensible. Thanks!
