### ISSUE TITLE
Vector2#angle_to returns zero when the left side is zero

### ISSUE THREAD

**Issue by ctrlraul** [godotengine/godot#72875]
### Godot version

4.0 beta 17

### System information

Windows 10

### Issue description

`Vector2#angle_to` always returns zero when the vector in which the method is being called from is zero.

The angle from vector a to vector b can be found with `atan2(b.y - a.y, b.x - a.x)`, and naturally, if vector a is the origin (0, 0) the angle is just the angle of vector b, this is not the case with Godot's `angle_to` implementation:

```cpp
real_t Vector2::angle_to(const Vector2 &p_vector2) const {
	return Math::atan2(cross(p_vector2), dot(p_vector2));
}
```

The following piece of code should print `0.78539816339745` (45 in degrees), but the output is zero.
```py
print(Vector2.ZERO.angle_to(Vector2(1, 1)))
```

### Steps to reproduce

Just run `print(Vector2.ZERO.angle_to(Vector2(1, 1)))`

### Minimal reproduction project

-

**Comment by lawnjelly** [comment]
Is this just the difference between `angle_to` and `angle_to_point()`?

https://docs.godotengine.org/en/3.6/classes/class_vector2.html#class-vector2-method-angle-to

`angle_to_point()` is indeed as you describe:
```
real_t Vector2::angle_to_point(const Vector2 &p_vector2) const {
	return Math::atan2(y - p_vector2.y, x - p_vector2.x);
}
```

**Comment by akien-mga** [comment]
Yes that's a misunderstanding, `Vector2.ZERO` is the origin, it doesn't have an angle to any other vector. An angle requires two directions and the origin is not a direction, so the result is as expected.

What you seem to want is `Vector2(1, 0).angle_to(Vector2(1, 1))` (which is indeed equivalent to `angle_to_point()`). It's the vector (1, 0) which marks the angle 0 on the trigonometric circle, not the origin point.
