### ISSUE TITLE
Switching Polygon2D nodes in the scene tree does not affect points editing in the 2D editor

### ISSUE THREAD

**Issue by DeanNevan** [godotengine/godot#72879]
### Godot version

4.0 Beta 17

### System information

Windows 10

### Issue description

I was trying to place **multiple** Polygon2D in a scene, and when I switched to a Polygon2D in the scene tree and edited the point in the 2D editor, I found that I actually changed the Polygon2D data from **the last selected** node (**if the last selected node was also Polygon2D**).

### Steps to reproduce

1.Add multiple (say two) Polygon2D nodes to the scene, called **A** and **B**
2.Deselect any Polygon2D node (such as clicking a blank area in the 2D editor, or clicking a non-Polygon2D node)
3.Select **A** in SceneTree
4.Select **B** in SceneTree
5.Use “Create points” tool in the 2D editor to create some points, then press Enter to confirm
6.You will find the points data of **A** has been changed

### Minimal reproduction project

[BugReport1.zip](https://github.com/godotengine/godot/files/10683256/BugReport1.zip)

**Comment by smix8** [comment]
This is properly already fixed by https://github.com/godotengine/godot/pull/72796

**Comment by timothyqiu** [comment]
I can confirm this is fixed on the current master. Fixed by #72796

**Comment by DeanNevan** [comment]
Yes, it has been fixed, thank you :)
