### ISSUE TITLE
OpenGL: GPUParticles2D with Color alpha set to 0 are not transparent

### ISSUE THREAD

**Issue by JonqsGames** [godotengine/godot#72882]
### Godot version

4.0.dev (8843d9ad347e5c3be5130153aeecdf48e4fe5a14)

### System information

Windows 10

### Issue description

#72853 fixed #72847
But with the same setup and setting the alpha to 0, particles are still visible.

### Steps to reproduce

Reproduce #72847
Set alpha to 0

### Minimal reproduction project

MRP from #72847

**Comment by Calinou** [comment]
Can you reproduce this when using the Forward+ or Mobile rendering methods, or only Compatibility?

**Comment by JonqsGames** [comment]
@Calinou only in Compatibility
Works normally with other renderer.

**Comment by JonqsGames** [comment]
Did some more test around this and i think the issue is with 0 value in any channel, i suspect the issue is in `unpackHalf2x16`

**Comment by JonqsGames** [comment]
I'm working on a refactor of `float2half` and `half2float` the solution used currenty is not working for some value (exposant == 0, truncated mantissa...) @clayjohn
