### ISSUE TITLE
RtAudio output underflow!

### ISSUE THREAD

**Issue by TX256** [godotengine/godot#7288]
**Operating system or device - Godot version:**
Windows 10. Godot 2.0 -2.2 Alpha.

**Issue description** (what happened, and what was expected):
Ever since I started using Godot (2.0 I think), I've received audio buffer underflows.

The debugger window simply gets (occasionally) spammed with this message:
`RtAudio output underflow!`

I'm not sure if it's caused by sound effects or music, but I get a "crack" in sounds / music whenever it happens.

I've got some integrated sound card (it's Acer Aspire E 13 laptop)

**Comment by TX256** [comment]
If it's of any help... I can confirm that there is a direct correlation with CPU load and these underflows. If I happen to use a graphics software (while my game is running) which uses an enormous amount of CPU, I get these underflows constantly.

**Comment by ackens** [comment]
I receive these warnings too, even in projects without any audio. I get no crack in sound, however, just the message.
![default](https://cloud.githubusercontent.com/assets/20978421/22174380/18e6474c-dfff-11e6-8075-5a26159ccc3e.PNG)

**Comment by Zireael07** [comment]
I am getting this warning in both 2.1.4 alpha and in 3.0 alpha1.

**Comment by DjPale** [comment]
Can also confirm that I get this in latest builds as well

**Comment by eon-s** [comment]
Got these since 2.0, I believe, but are not constant, is like something in the system triggers the error because sometimes never appear.
I have never seen it in 3 yet but I have not used it much on windows.

Try disabling most programs on windows startup (like skype) and others like cortana and check if the warning appears.

**Comment by plucian** [comment]
I get the constant warning on 2.1.4 RC, but not on beta. (continuous spamming of the message)

**Comment by akien-mga** [comment]
> I get the constant warning on 2.1.4 RC, but not on beta. (continuous spamming of the message)

That should be fixed in 2.1.4-stable.

The main issue should also be fixed in the master branch by #10683.

**Comment by DjPale** [comment]
Looks good in the latest 3.0 builds I've tested 👍
