### ISSUE TITLE
Custom Build with Mono crashes with ERROR: hostfxr_initialize_for_runtime_config failed with code: -2147450733

### ISSUE THREAD

**Issue by berkselvi** [godotengine/godot#72891]
### Godot version

4.0.dev (28a24639c)

### System information

Windows 10, tried multiple devices

### Issue description

My custom builds with Mono for Windows crash with following errors:

```
ERROR: hostfxr_initialize_for_runtime_config failed with code: -2147450733
   at: (modules/mono/mono_gd/gd_mono.cpp:201)
ERROR: Parameter "load_assembly_and_get_function_pointer" is null.
   at: initialize_hostfxr_and_godot_plugins (modules/mono/mono_gd/gd_mono.cpp:274)
ERROR: Parameter "godot_plugins_initialize" is null.
   at: initialize (modules/mono/mono_gd/gd_mono.cpp:403)
```

I tried compiling it both from Windows 10 and latest Ubuntu on multiple devices. The result is the same. Any ideas what may be causing this?

### Steps to reproduce

(Cross-)Compile Godot 4.0 from commit beta 14 commit (28a24639c) for windows.

### Minimal reproduction project

-

**Comment by raulsntos** [comment]
> ERROR: hostfxr_initialize_for_runtime_config failed with code: -2147450733

Acording to the error code (see https://github.com/dotnet/runtime/blob/main/docs/design/features/host-error-codes.md), the error received was `InvalidConfigFile` with description:

> The `.runtimeconfig.json` file is invalid. The reasons for this failure can be among these:
>
> - Failure to read from the file
> - Invalid JSON
> - Invalid value for a property (for example number for property which requires a string)
> - Missing required property
> - Other inconsistencies (for example `rollForward` and `applyPatches` are not allowed to be specified in the same config file)
> - Any of the above failures reading the `.runtimecofig.dev.json` file
> - Self-contained `.runtimeconfig.json` used in `hostfxr_initialize_for_runtime_config`. Note that missing `.runtimconfig.json` is not an error (means self-contained app). This error code is also used when there is a problem reading the CLSID map file in `comhost`. 

---

> (Cross-)Compile Godot 4.0 from commit beta 14 commit (https://github.com/godotengine/godot/commit/28a24639c3c6a95b5b9828f5f02bf0dc2f5ce54b) for windows.

Try using beta 17 or RC1, there were some changes that may have fixed this already. If it doesn't fix it, let us know what's the output of executing `dotnet --info` in a console (should inform us of which version(s) of the .NET SDK/runtime you have installed).

**Comment by tagcode** [comment]
Have you checked build log?

I got hostfxr issue too, but then noticed that the solution had not built properly. Could be same underlying [issue](https://github.com/godotengine/godot/issues/72915).

**Comment by berkselvi** [comment]
I was able to take a deeper look today and found out that the modules/mono/glue/mono_glue.gen.cpp doesn't get created. So it should be realted to the build environment, although I tried a fresh install of the environment as well. Quite interestingly the build was completed without any errors, also no errors in the build log @tagcode. 

Here  is the .NET version: 

.NET SDK (reflecting any global.json):
 Version:   6.0.405
 Commit:    27ab36058b

**Comment by raulsntos** [comment]
We stopped generating `mono_glue.gen.cpp` a long time ago. You may be using outdated build commands, take a look at the instructions in the .NET module's [README.md](https://github.com/godotengine/godot/blob/5c1295dc20323ee1596369b5bcf91ba6a9383336/modules/mono/README.md).

For your convenience, here are the build commands that should work:

```
scons p=windows target=editor module_mono_enabled=yes
bin/godot.windows.editor.x86_64.mono --generate-mono-glue modules/mono/glue
python ./modules/mono/build_scripts/build_assemblies.py --godot-output-dir ./bin --push-nupkgs-local ~/MyLocalNugetSource
```

Also, make sure to clear the GodotNuGetFallbackFolder directory to ensure the latest assemblies are used.

**Comment by berkselvi** [comment]
Thanks a lot for the help! I used the commands, you gave and build seemed again to be completed without any errors. However now it crashes with the following error: 

```
`ERROR: vkCreateComputePipelines failed with error -1000012000.
   at: (drivers\vulkan\rendering_device_vulkan.cpp:6509)`
```

Btw GodotNuGetFallbackFolder does not exist if it says anything meaningful.

**Comment by berkselvi** [comment]
Yes, someone issued it for MacOS but it also helped me solve the issue: Just needed to update the graphic driver. Thanks for all the help and keep up the great work you're doing here!

**Comment by raulsntos** [comment]
The GodotNuGetFallbackFolder should exist, maybe you didn't check the right path? In Windows the full path should be `%APPDATA%\godot\mono\GodotNuGetFallbackFolder`.

**Comment by raulsntos** [comment]
The folder is created and gets added to your NuGet configuration on opening a Godot 4 build compiled with the .NET module. When building a C# project, Godot copies the Godot C# assemblies to this folder (unless they already exist).

If Godot is working as expected, the folder should have been created. Maybe you could check if there are any errors printed to the console. I think, in order to get the console open in Windows, you need to use the binary named something like `godot.windows.editor.dev.x86_64.mono.console.exe`.

But if everything is working and the original issue has been resolved, feel free to close the issue.
