### ISSUE TITLE
[rc1] Image creation doesn't work

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot#72904]
### Godot version

4.0 rc1

### System information

Linux Manjaro, Intel Kaby Lake

### Issue description

```
var img = Image.new()
img.create(1000, 1000, false, Image.FORMAT_RGBA8)
	
print("Img size: ", img.get_size())
```

size is (0,0) and obviously set_pixel spams errors. Looked at docs both in editor and on website, no indication of any changes.

### Steps to reproduce

See above

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Create is a static function, you need to write:
```gdscipt
var img = Image.create(...)
```

**Comment by Zireael07** [comment]
In that case, docs need to be updated ASAP, they don't mention this yet!

**Comment by akien-mga** [comment]
Which docs? Please always give links, we can't update them without knowing which ones you're reading.

**Comment by Zireael07** [comment]
This is the docs within rc1 
![image](https://user-images.githubusercontent.com/4525388/217610116-4e2bc7fb-7d1c-4183-a8b4-0debab01a71a.png)

This is the link: https://docs.godotengine.org/en/latest/classes/class_image.html if you scroll down it's the same as the rc1 docs
