### ISSUE TITLE
black screen bug

### ISSUE THREAD

**Issue by JLGGX1000** [godotengine/godot#72910]
### Godot version

4.0

### System information

android 6 j2 prime

### Issue description

when i create a project and enter godot my J2 PRIME phone has a black screen and closes by itself please if you solve this bug i will donate it to your team and i thank you

### Steps to reproduce

when i create a project and enter godot my J2 PRIME phone has a black screen and closes by itself please if you solve this bug i will donate it to your team and i thank you

### Minimal reproduction project

when i create a project and enter godot my J2 PRIME phone has a black screen and closes by itself please if you solve this bug i will donate it to your team and i thank you

**Comment by YuriSizov** [comment]
Duplicate of https://github.com/godotengine/godot/issues/72888.
