### ISSUE TITLE
opengl: Using CanvasItemMaterial with BLEND_MODE_SUB makes the editor disappear.

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#72918]
### Godot version

4.0rc1 gl_compatibility only.

### System information

Windows 10, Nvidia 527.56 RTX3090, gl_compatibility
OpenGL API 3.3.0 NVIDIA 527.56 - Compatibility

### Issue description

Assigning a `CanvasItemMatrial` with `blend_mode = BLEND_MODE_SUB` in opengl causes the entire editor to turn black and break, even if later unassigned.

In case it matters, I'm using Single Window Mode in the editor.

### Steps to reproduce

1. Open the attached Project. Make sure it is using **Compatibility** on the top right.
2. On the root "Level" node, click the `Use Standard` checkbox which runs the tool script (it actually sets a CanvasItemMaterial, not standard. the checkbox was badly named). The editor turns black.
3. Without moving the mouse, click again to toggle this material off and return to a ShaderMaterial. The editor is still black / broken.
4. Press Ctrl-S to save the scene so you aren't bombarded with an invisible save dialog.
5. Close the editor.

If you edit the script and try other blend_mode values, this issue does not happen.

### Minimal reproduction project

[black_screen_test.zip](https://github.com/godotengine/godot/files/10689627/black_screen_test.zip)

**Comment by lyuma** [comment]
Apparently the test project I was basing this on was using `gl_compatibility`. This bug does not occur in vulkan **Forward+** or **Mobile**

**Comment by clayjohn** [comment]
Related to https://github.com/godotengine/godot/issues/72488 Although that issue is with 3D
