### ISSUE TITLE
OS-specific extensions are not default for exporting

### ISSUE THREAD

**Issue by IBwWG** [godotengine/godot#7291]
**Operating system or device - Godot version:**
win7x64, godot 2.1.1

**Issue description** (what happened, and what was expected):
Export to win/mac/linux, and the filename is always whatever the previous export was, even for a different OS.  It should be no extension for linux, .zip for Mac (I think), and .exe for Windows.

**Steps to reproduce:**
Export to the above with the standard templates installed.

**Link to minimal example project** (optional but very welcome):

**Comment by unbu** [comment]
This was causing problems for me, and for some other people that opened reddit posts for them. Since they were confused why they had .html extensions for linux binaries!
This can be very confusing for first-time exporters
