### ISSUE TITLE
[4.0 RC1] C# won't recognise static methods as class members.

### ISSUE THREAD

**Issue by dunyakilavuz** [godotengine/godot#72927]
### Godot version

Godot 4 RC 1 .Net Build

### System information

Windows 11, .Net version 7.0

### Issue description

While converting an 3.x project to 4, I tried connecting few buttons to respective scripts using `button_down` and `button_up` actions. However I found out that Godot 4 won't recognise static methods as class members now. 

In the code given below `ButtonDown()` method is registered and runs alright but when it comes to run `ButtonUp()` method the editor says it can not find method.

```cs
public static void ButtonUp()
{
    GD.Print("Button up");
}

public void ButtonDown()
{
    GD.Print("Button down");
}
```

### Steps to reproduce

-Open up the Test.zip file I provided. 
-Run the project.
-Click on the button.

You should see that `ButtonDown()` method is being called and prints fine while calling the static `ButtonUp()` method, editor throws the below error.

```
E 0:00:01:0209   emit_signalp: Error calling from signal 'button_up' to callable: 'Control(Test.cs)::ButtonUp': Method not found.
  <C++ Source>   core/object/object.cpp:1058 @ emit_signalp()
```

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/10690462/Test.zip)

**Comment by silenuz** [comment]
It's just the way C# works.  Preface the name of the static method with the object name.  For example if you had a class called Button and it has a static method called ButtonUp() to call button up you would use Button.ButtonUp().  Or you add a using statement for the static method at the top of the class and you'll be able to call it with just the method name.

[static](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/static)

**Comment by raulsntos** [comment]
As a workaround, I think connecting to signals from code works with static methods when using C# events or a Callable created from a delegate:

```csharp
button.ButtonDown += ButtonDown;
// -or-
button.Connect(Button.SignalName.ButtonDown, Callable.From(ButtonDown));
```

**Comment by dunyakilavuz** [comment]
I think it used to recognise static members in Godot 3.x but @raulsntos's answer is a nice workaround. Thanks a lot the replies. No need to keep this open now i guess.
