### ISSUE TITLE
[4.0 RC 1] Can't switch to packed scene that was started in using change_scene_to_packed

### ISSUE THREAD

**Issue by KittenAqua** [godotengine/godot#72921]
### Godot version

4.0 RC 1

### System information

Windows 10

### Issue description

I cannot switch back to the packed scene that I start in. Hard to describe, so see the minimal reproduction project if my description is difficult to follow.

I have two scenes, SceneA and SceneB, that just switch between eachother repeatedly by preloading and using `change_scene_to_packed`.
- SceneA has a button that switches to SceneB with `get_tree().change_scene_to_packed(scene_b)`
- SceneB has a button that switches to SceneA with `get_tree().change_scene_to_packed(scene_a)`

But I can't seem to switch back to whatever scene I start in.
- If I start in SceneA and switch to SceneB, I can't switch back to SceneA (`ERR_CANT_CREATE`)
- If I start in SceneB and switch to SceneA, I can't switch back to SceneB.

I tried adding a third scene, SceneC, that switches to SceneA.
- If I start in SceneC, I can switch back and forth between SceneA and SceneB endlessly, so the conclusion is that I can't switch back to whatever scene I start in.

This error is specific to packed scenes, but it doesn't require `change_scene_to_packed` specifically. If I use `change_scene_to_file` instead, there are no errors. However, if I use `change_scene_to_file` AND preload the packed scenes (even if I'm not using them), it will error.

### Steps to reproduce

Open the minimal reproduction project.

SCENE A FAILURE:
- Run SceneA.
- Click the button. It should switch to SceneB.
- Now click the button in SceneB. It will fail to switch to SceneA and print the error code to the console (error code 20 - ERR_CANT_CREATE).

SCENE B FAILURE:
- Run SceneB.
- Click the button. It should switch to SceneA.
- Now click the button in SceneA. It will fail to switch to SceneB and print the error code to the console (error code 20 - ERR_CANT_CREATE).

SCENE C SUCCESS:
- Run SceneC.
- Click the button. It should switch to SceneA.
- Now click the button in SceneA. It should take you to SceneB.
- Now click the button in SceneB. It should take you back to SceneA. Since we never return to the scene we started in, there are no errors.

### Minimal reproduction project

[SceneswitchTest.zip](https://github.com/godotengine/godot/files/10689710/SceneswitchTest.zip)

**Comment by KoBeWi** [comment]
![image](https://user-images.githubusercontent.com/2223172/221867925-8ac046cc-f6a8-4483-be84-4293258ee4c4.png)
Closing as WONTFIX.

You can also use `load()` or preload the scenes in another file.
