### ISSUE TITLE
beta15: `set_shader_parameter` fail to be serialized if shader assigned in the same frame.

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#72923]
### Godot version

Regressed in 4.0.beta15. Still broken in rc1. Worked fine in beta14

### System information

Windows 10, Nvidia

### Issue description

I'm writing a custom importer that needs to assign a ShaderMaterial to some materials.

When creating a new ShaderMaterial and assigning a shader, it seems that parameters assigned in the same frame are not serialized properly. One workaround is to use `set_deferred("shader_parameter/color", ...)` or `call_deferred("set_shader_parameter", "color", ...)` but this doesn't work for my application (an editor importer).

This issue was previously opened as #72143 but there was some confusion due to an error in the original MRP, so I'm opening a new report.

The reproduction project does:
```
			var new_mat = ShaderMaterial.new()
			new_mat.shader = load("res://shaders/color_stripes.gdshader")
			new_mat.set_shader_parameter("color", color)
```
If left alone, this will appear to work fine because it's not being serialized.

Therefore I also run this code in the reproduction project to force it to be serialized and then reloaded from disk ignoring cache:
```
			new_mat.take_over_path("res://saved_material.tres")
			ResourceSaver.save(new_mat, "res://saved_material.tres")
			new_mat.take_over_path("res://junk_material.tres")
			new_mat = ResourceLoader.load("res://saved_material.tres", "", ResourceLoader.CACHE_MODE_REPLACE)
```

On `beta15`, `saved_material.tres` contains:
```
$ cat saved_material.tres
[gd_resource type="ShaderMaterial" load_steps=2 format=3 uid="uid://b3j8rq3rbwteh"]

[ext_resource type="Shader" path="res://shaders/color_stripes.gdshader" id="1_mfh7u"]

[resource]
shader = ExtResource("1_mfh7u")
shader_parameter/color = null
```
The null value is the bug.

On `beta14`, it contains:
```
[gd_resource type="ShaderMaterial" load_steps=2 format=3 uid="uid://b3j8rq3rbwteh"]

[ext_resource type="Shader" path="res://shaders/color_stripes.gdshader" id="1_mfh7u"]

[resource]
shader = ExtResource("1_mfh7u")
shader_parameter/color = Color(0.564706, 0.4, 1, 1)
```

### Steps to reproduce

1. Open the attached project.
2. It should run the property setter on load, which will autosave and already show the incorrect material.
3. Click the checkbox Use Standard on and off. This serializes a new material and then loads it from disk.
4. Starting from beta15, the serialized material has no shader_parameter assigned, so when using CACHE_MODE_REPLACE, they are loaded.

The correct behavior is it should have stripes with the selected color (purple in the MRP). if the color is not serialized correctly, it will use the default color in the shader which is greyish.

### Minimal reproduction project

[set_shader_parameter_test.zip](https://github.com/godotengine/godot/files/10690011/set_shader_parameter_test.zip)

**Comment by clayjohn** [comment]
I wonder if this has the same root cause as https://github.com/godotengine/godot/issues/72538
