### ISSUE TITLE
CameraMatrix::set_frustum does not work

### ISSUE THREAD

**Issue by 1000h** [godotengine/godot#7292]
**Operating system or device - Godot version:**
Godot 2.1, recent clone as of the december 11, core CameraMatrix.cpp

**Issue description** (what happened, and what was expected):
This is a TODO in the CameraMatrix.cpp but I can't find any issues about open it so I figure I'd just post that it was there incase anyone knows how to fiddle with the camera.

**Steps to reproduce:**
Search .set_frustum in CameraMatrix.cpp

**Link to minimal example project** (optional but very welcome):

**Comment by 1000h** [comment]
In order to try and mess with the coordinates of the viewing plane, since set_frustum wouldn't effect them, I replaced the code in set_orthogonal inside CameraMatrix.cpp, both of the set_orthogonal functions, so that one would have the set_frustum code in it and the other wouldn't divide the input coordinates by 2 anymore, and I set the translation of the camera to a moving 3D object.  Nothing is seen in the scene, as in when I switch to orthogonal mode nothing is viewed no matter how I change the properties, but I was printing get_frustum and as the character moved the coordinates for the planes were changing.

**Comment by 1000h** [comment]
Messing with Orthogonal didn't work, but I put the set_frustum code and referenced a bit from this guys code

http://gamedev.stackexchange.com/questions/83191/offset-a-camera-render-without-changing-perspective

And I replaced how 'set_perspective' works in CameraMatrix.cpp and I think it is working so that the vanishing point changes.  The reason I think it's working is because when I translate, the perspective doesn't change!!!

**Comment by 1000h** [comment]
So I think in order to offset the vanishing point now, all I need to do is learn how to reference the Camera that this CameraMatrix is of, and then use the v_offset h_offset to shift the vanishing point...

**Comment by 1000h** [comment]
What I am doing now is adding 2 more arguments to set_perspective which are h and v offset

**Comment by 1000h** [comment]
Turns out I was wrong the whole time... Apparently it switched to orthogonal like, cause perspective was broken so I guess it just switched to it when I started it up, or maybe I had forgotten to change it the last time I saved, and anyway what I thought worked didn't work.

I was in orthogonal when I thought it was perspective, so yeah.  My bad

**Comment by akien-mga** [comment]
> Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

As there was no update since the previous post, we close this issue.

If it is still relevant in the way it was described and discussed above, please comment to ask for it to be reevaluated. If it is only partly relevant, or if the original issue has changed, it would be better to open a new issue (potentially referring to this one) focused on the current state.
