### ISSUE TITLE
More DPI scaling options should be available

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#7293]
More DPI scales should be available to cater to the growing amount of hi-DPI displays.

Currently, we have:

- 75% (VeryLoDPI)
- 100% (LoDPI)
- 150% (MiDPI)
- 200% (HiDPI)

Following the Windows 10 scaling options, I suggest adding:

- 125%
- 175%
- 225%
- 250%

This way, users with poor vision, medium-resolution displays or very high-resolution displays can enjoy a more natively-integrated Godot (compared to their OS scaling settings).

Additionally, the scaling percentage should probably be shown when selecting a DPI option (such as 150%), instead of just a named value. A "(recommended)" text could also show next to the automatically-detected DPI setting.

Lastly, it is probably worth it to regenerate all icons and editor graphics for each of those sizes, for optimal display on each of those sizes. With optimized PNGs, the size should hopefully not be too much of an issue.

**Comment by toger5** [comment]
What abot allowing the user to choose any number btween 50 and 200% ?

**Comment by Calinou** [comment]
> What abot allowing the user to choose any number btween 50 and 200% ?

Unfortunately, this is not really possible without making the icons look horrible, *unless* they are generated at run-time from vector assets.

**Comment by toger5** [comment]
yea I'm thinking about generating them at runtime.
I made some test with a tiny svgs parsing (license works with godot) library.
I mentioned that in another issue I don't find at the moment

**Comment by djrm** [comment]
no that we can do this, how should we handle it, simply adding more options, or a slider?

**Comment by Calinou** [comment]
If possible, arbitrary scaling by a floating-point number should be allowed (but some presets should be available).

**Comment by djrm** [comment]
@Calinou i think it has to be just one of them (i dont know if we have a widget that manges both).

**Comment by Calinou** [comment]
> i think it has to be just one of them (i dont know if we have a widget that manges both).

There could be a dropdown with DPI presets, the last option of the dropdown being "Custom". If this setting is chosen, then a custom DPI scale is used, which can be set by the user just below the dropdown (kind of like the editor theme colors).

**Comment by toger5** [comment]
@Calinou. That sounds like a good approach.
I wonder if the property editor gets a rewrite,if those options cpuld fold in /out dependant on what is choosen.

**Comment by reduz** [comment]
Was this not added already? I would close or push to next version

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by Calinou** [comment]
This was fixed a while ago by https://github.com/godotengine/godot/pull/17706, closing.
