### ISSUE TITLE
TileSet name types backwards

### ISSUE THREAD

**Issue by Blockyheadman** [godotengine/godot#72937]
### Godot version

v4.0.rc1.official [8843d9ad3]

### System information

Windows 10 Pro

### Issue description

When typing in the name for my TileSet, it sets the cursor position to the very beginning of the name each character you type.

### Steps to reproduce

Make an Atlas TileSet, type a name, see issue.

https://user-images.githubusercontent.com/80011716/217703931-875b128a-d4b0-4efa-9130-756e06115086.mov

### Minimal reproduction project

All projects.

**Comment by Zireael07** [comment]
This sort of error has been reported earlier for another inspector field. The whole inspector is unnecessarily refreshed, which puts the caret at the beginning

**Comment by AThousandShips** [comment]
Possibly related to #69244

**Comment by akien-mga** [comment]
Duplicate of #72289
