### ISSUE TITLE
[4.0-rc1] Visual Shader "Show Generated Code" button broken

### ISSUE THREAD

**Issue by hmans** [godotengine/godot#72949]
### Godot version

4.0.rc1

### System information

macOS 13.1, Apple M1

### Issue description

The "Show Generated Code" button in Visual Shader no longer works (it was working in 4.0.beta17.) It merely changes color when clicked, but the window with the shader code no longer opens.

![Screenshot 2023-02-09 at 09 26 38](https://user-images.githubusercontent.com/1061/217757845-22063e28-d94e-4ddb-8337-43f2797677ae.png)

### Steps to reproduce

1) Create any project with a visual shader (or use the attached MRP)
2) Click the "Show Generated Shader Code" button

### Minimal reproduction project

[MRP-Visual-Shader-Show-Generated-Code.zip](https://github.com/godotengine/godot/files/10694943/MRP-Visual-Shader-Show-Generated-Code.zip)

**Comment by Chaosus** [comment]
It's showing, but in minimized state...

![vs_preview](https://user-images.githubusercontent.com/3036176/217774997-756e7e58-e510-4ef6-9aa2-5ee9445913de.gif)

**Comment by hmans** [comment]
> It's showing, but in minimized state...

On macOS, you don't even get the small window (and I couldn't find any other way to switch to it.)

**Comment by Chaosus** [comment]
Then I'm not sure that my fix is correct for macOS users. Since I don't have mac, then somebody else should fix it properly. cc @clayjohn - I know you bought a mac recently, can you check if my PR is correct?

**Comment by hmans** [comment]
I've built your PR on my Mac and I can confirm that it fixes the issue.

![image](https://user-images.githubusercontent.com/1061/217791929-8c1984d2-cce1-4ea1-b455-d649f7d8b2a5.png)

Thank you!
