### ISSUE TITLE
GDScript in `@tool` mode ignores errors in the call stack

### ISSUE THREAD

**Issue by dalexeev** [godotengine/godot#72966]
### Godot version

v4.0.rc1.official [8843d9ad3]

### System information

Kubuntu 22.10

### Issue description

This code is executed as you would expect:

```gdscript
@tool
extends EditorScript

func _run():
    var x
    x.lalala()
    print("This should not be printed.") # Will not be printed.
```

But if you move the error code to a function, then the execution will continue:

```gdscript
@tool
extends EditorScript

func test():
    var x
    x.lalala()

func _run():
    test()
    print("This should not be printed.") # Will be printed.
```

Without `@tool` mode, in both cases the code will stop at the error until you press Continue in the debugger. I think it's a bug that `@tool` mode "automatically presses" Continue. Especially in just one of the cases. This may result in data corruption.

### Steps to reproduce

See above.

### Minimal reproduction project

[gds-tool-exec-inconsistency.zip](https://github.com/godotengine/godot/files/10696998/gds-tool-exec-inconsistency.zip)

**Comment by KoBeWi** [comment]
`@tool` does not "automatically press continue". It's the debugger that's stopping the execution and the editor runs without debugger.

**Comment by dalexeev** [comment]
Yes, but I still feel like this is not the behavior that users expect.

I can't reproduce it now, but I'm pretty sure I've seen the error being ignored within a function in `@tool` mode.

**Comment by KoBeWi** [comment]
And what do you expect exactly? Pausing editor by debugger would freeze it, unless your tool scripts execute in a thread.

**Comment by dalexeev** [comment]
I expect the script to abort after an error, without freezing the editor.

**Comment by KoBeWi** [comment]
Well, then you expect wrong xd
When you run from editor and continue after encountering this error, the message will be printed.
When you run without editor, the message will be printed.
When you export the project and run, the message will be printed.

Godot is literally designed in a way that makes it able to continue when it encounters error, so your app does not crash and can run even if something goes wrong. If you are worried about data corruption just safeguard your code.
