### ISSUE TITLE
Add float Curve

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#7296]
Godot has Curve3D, Curve2D, ColorRamp but no Curve for just floats. This would be handy for defining values changing over time in a determined and smooth way, or defining a custom interpolation.
For comparison, the Unity equivalent is AnimationCurve, and is used in a lot of places in the engine.

I currently need it so i can define the width of a line along its length (rather than having to set every single 50 points for example).

**Comment by bojidar-bg** [comment]
How should it be called? `Curve1D`? just `Curve`? `FloatRamp`? just `Ramp` (:smile:)?

**Comment by reduz** [comment]
Bezier curves will be added to animation editor eventually

**Comment by bojidar-bg** [comment]
@reduz You are mistaking the issue a bit -- this isn't about AnimationPlayer or AnimationTreePlayer, it is about a Resource which contains a Curve of floats (i.e. a 1D Curve), which can allow for more possibilities than `@GDScript.ease()` :smiley:

**Comment by Zylann** [comment]
Yeah I meant having a Resource holding that. It can still be useful in other places such as AnimationPlayer though :)

**Comment by Zylann** [comment]
I would call it Curve since there are Curve2D and Curve3D doing the same things (with control points and all). ColorRamp does too in the concept but its implementation differs.

**Comment by eon-s** [comment]
I think that a 1 dimension curve called "Curve" will be a bit confusing... "Ramp" sounds better.

**Comment by bojidar-bg** [comment]
Ramp is probably confusing as well -- FloatRamp/RealRamp might be better.. (but, not sure about this actually)

**Comment by LeonardMeagher2** [comment]
I would enjoy something like this if I could put in x, ranging from 0-1, and it'd return what y was (from 0-1)

**Comment by Gibbz** [comment]
a curve editor dialog to adjust a curve in a similar way to the UE4 would be great!

**Comment by Zylann** [comment]
I now have a work in progress based on cubic bezier curves. I found it allows access in the form y(x) instead of (x,y)(t), which is nice :)

![image](https://cloud.githubusercontent.com/assets/1311555/25412824/f33696f2-2a25-11e7-8f1c-4a4107ab17c4.png)

@reduz at the same time, I'm thinking about the CurveTextureEditor, which could use the same algorithm, but what I did so far relies on the fact that the baking is done in the resource rather than the editor plugin (so it can change at runtime).

**Comment by Noshyaar** [comment]
Fixed by #8591
