### ISSUE TITLE
`_parse_property` in `EditorInspectorPlugin` is asking for `::Type` instead of `int` in `type` parameter.

### ISSUE THREAD

**Issue by eh-jogos** [godotengine/godot#72963]
### Godot version

4.0 rc1

### System information

Manjaro Linux using i3, Foward+

### Issue description

All of my `EditorInspectorPlugin`s are broken with the following error:
```
Line 34:The function signature doesn't match the parent. Parent signature is "_parse_property(Object, ::Type, String, int, String, int, bool) -> bool".
```

I tried to change it from `int` to `Type` like it shows in the documentation and it also doesn't work:
![image](https://user-images.githubusercontent.com/13070158/217805607-de1bc8f2-3c36-4f1c-9a6d-02b8e2bbee2d.png)
![image](https://user-images.githubusercontent.com/13070158/217805682-d43b3ccf-0fb7-4e7a-a9c3-92fd7e63be94.png)

And keeping it as an `int` just gives me the function signature mismatch error above.

### Steps to reproduce

Create a new `EditorInspectorPlugin` script and try to override the virtual method `_parse_property`

### Minimal reproduction project

See Steps to reproduce above.

**Comment by raulsntos** [comment]
It looks like this was my fault (see https://github.com/godotengine/godot/pull/71479).

**Comment by raulsntos** [comment]
The type is actually `Variant.Type`, it's a nested type. The [online documentation](https://docs.godotengine.org/en/latest/classes/class_editorinspectorplugin.html#class-editorinspectorplugin-method-parse-property) seems to be able to handle it properly, not sure why the editor documentation shows just `Type`.

However, it seems using `Variant.Type` is not usable as a type hint in GDScript, I get error `Variant doesn't contain nested types.`

I wonder why `int` is working for the other enums though.
