### ISSUE TITLE
Renaming nodes with physical keyboard

### ISSUE THREAD

**Issue by pc9098** [godotengine/godot#72965]
### Godot version

4 rc1, android

### System information

Android

### Issue description

-You can't rename a node with F2.
-Another is bug is that you cannot accept the name of the node clicking enter.
-Another is that Control+S does not save the scene.

Those 3 bugs happen with a physical keyboard

I think those 3 bugs are related so I posted them together.

I know it is not my keyboard's fault since Alt+Tab works perfectly fine. Enter also works in scripts to write code

### Steps to reproduce

Create a Scene with a node and try to rename it with a physical keyboard.

### Minimal reproduction project

N/A

**Comment by m4gr3d** [comment]
These issues are no longer reproducible in the latest version of the Android editor (tested using a Galaxy tab tablet with attached external keyboard).
