### ISSUE TITLE
Input actions don't update pressed states after OS window adjustment

### ISSUE THREAD

**Issue by jtaart** [godotengine/godot#7297]
Operating system: Windows 8.1(64)
Godot version: Godot_v2.1.1-stable_win64
Issue description: 
Input actions don't update pressed states after OS window adjustment. This may create an input saying its pressed even though you released it outside of the game.

Steps to reproduce:
1.) press and hold an action
2.) adjust OS window and release action 

Video of me doing it:
[https://youtu.be/3bZuJVrmGJw](https://youtu.be/3bZuJVrmGJw)

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by jtaart** [comment]
I just tested it again with Godot_v3.0.2-stable_win64. Now both _input(event) and Input.is_action_pressed does it. 
-If you have your game in window mode (not full-screen)
-then click out of the game, while holding down an input. 
-then release input with the game window deselected.

the game wont get the button release. I guess Godot need to automatically set all input stated to false when it loses the ability to capture input.
