### ISSUE TITLE
"Treat Warning as Errors" has no effect and annotation warnings are generating fatal errors

### ISSUE THREAD

**Issue by alfredbaudisch** [godotengine/godot#72982]
### Godot version

4.0-rc1

### System information

Windows 10

### Issue description

The code: `@export @onready var camera_system : Node3D`

Is throwing: `Line 5:The "@onready" annotation will make the default value to be set after the "@export" takes effect and will override it. (Warning treated as error.)` and is crashing the game.

Unchecking "Treat Warning as Errors" seems to have no effect:

![imagen](https://user-images.githubusercontent.com/248383/217900756-8e214c40-68fb-4fb2-8509-a1e689725930.png)

![imagen](https://user-images.githubusercontent.com/248383/217901253-3b758ebc-48e9-40fe-8d77-16fce7cbae88.png)

### Steps to reproduce

- Write `@export @onready var some_var : Node3D`
- In Project Settings, uncheck `Treat Warning as Errors`
- Try to run the project, a `Parser Error` will be thrown.

### Minimal reproduction project

It's as simple as adding one line of code, so I'm not sure a MRP is needed.

**Comment by dalexeev** [comment]
This checkbox means "Treat **all** warnings as errors". If you want to change the behavior for the `@export @onready` warning, you need this:

![](https://user-images.githubusercontent.com/47700418/217913943-45be62a7-b4ef-412b-8c40-94dd9a7a6d3a.png)

**Comment by alfredbaudisch** [comment]
> This checkbox means "Treat **all** warnings as errors". If you want to change the behavior for the `@export @onready` warning, you need this:
> 
> ![](https://user-images.githubusercontent.com/47700418/217913943-45be62a7-b4ef-412b-8c40-94dd9a7a6d3a.png)
> 
> If it's not too late, I suggest renaming or deleting this setting.

But that's the thing: if "Treat all warnings as errors" is checked, warnings should be errors.
If unchecked, no warning should be an error - but in this case I was getting errors.

Or am I missing something?

**Comment by dalexeev** [comment]
If this checkbox is disabled, then it does not affect warnings. Otherwise, we would have only two states: all warnings on or all warnings off. It doesn't make sense. :smile:

**Comment by akien-mga** [comment]
This option indeed means "Force an error on any warning, regardless of the fine grained configuration". It's the equivalent of the `-Werror` and `/WX` compiler flags for GCC/Clang and MSVC respectively.

But yes the current name isn't obvious, and maybe the functionality isn't useful either.
