### ISSUE TITLE
Unresizable window's resolution is incorrect

### ISSUE THREAD

**Issue by TheEternalShine** [godotengine/godot#72985]
### Godot version

v4.0.rc1.official [8843d9ad3]

### System information

Windows 10

### Issue description

The size of the main window seems to be 10 pixels larger in both width and height whenever the window is set to be not resizable. the window should remain the same size, whether it is resizable or not.

### Steps to reproduce

1. Uncheck Project Settings > Display > Window > Resizable
2. Run Project

### Minimal reproduction project

[Bug Report.zip](https://github.com/godotengine/godot/files/10700522/Bug.Report.zip)

**Comment by akien-mga** [comment]
CC @bruvzg
