### ISSUE TITLE
Unexpected behavior when using PROPERTY_HINT_PASSWORD in inspector

### ISSUE THREAD

**Issue by meloonics** [godotengine/godot#72992]
### Godot version

v4.0.rc1.official [8843d9ad3]

### System information

Windows 10

### Issue description

When I export a String-property in the inspector with the hint-flag set to PROPERTY_HINT_PASSWORD, overriding _set(), _get() and the _get_property_list() functions, it behaves very weirdly, when trying to type. The caret seems to be jumping to position one all the time, so when entering a password that's supposed to be "12345" I have to enter it backwards "54321".

### Steps to reproduce

add a dictionary with a String-Property and the property hint PROPERTY_HINT_PASSWORD into the property_list by overriding _get_property_list.
Create a resource from that and try modifying the string property in the inspector.

### Minimal reproduction project

[password_bug.zip](https://github.com/godotengine/godot/files/10701522/password_bug.zip)

**Comment by YuriSizov** [comment]
You are calling `notify_property_list_changed()` for no good reason, which causes the entire inspector to be updated, which resets the caret. You only need to call `notify_property_list_changed()` when the property _list_ changes (i.e. new properties are added or existing properties are hidden), not when you change values.

**Comment by meloonics** [comment]
> You are calling `notify_property_list_changed()` for no good reason, which causes the entire inspector to be updated, which resets the caret. You only need to call `notify_property_list_changed()` when the property _list_ changes (i.e. new properties are added or existing properties are hidden), not when you change values.

oh, good to know, however this behavior doesn't occur with Multiline Strings as far as I can tell. 
Just out of curiosity: What am I supposed to use instead of `notify_property_list_changed()` when I want vars to appear in the inspector under certain circumstances (such as a String matching a password)?

**Comment by meloonics** [comment]
did some experimenting, and it works better when i check for that password match right after the variable declaration, when i override the set function. however, i still have to check for the very same value inside the `_get_property_list()` function, which doesn't really help keeping the code DRY. I still feel like the caret shouldn't jump to pos1, once the inspector updates.

**Comment by YuriSizov** [comment]
It doesn't just update, it is completely rebuild. Your old controls are gone, and the news ones are created. Your element is refocused, but it's not possible to preserve the focus. It happens with every text input, and the hint has nothing to do with it.

What exactly do you mean by making a variable to appear in the inspector?

**Comment by YuriSizov** [comment]
The inspector is not designed for such behavior, and indeed it would require a complete rebuild of the property list for a new property to appear like that (though you still call the notify method excessively).

You can try making an inspector plugin for your boolean property, to hide or disable it when not needed this way. Then the property can be always on the list, and you will control its appearance with your own code.
