### ISSUE TITLE
Create docs for engine hackers

### ISSUE THREAD

**Issue by Ed-von-Schleck** [godotengine/godot#73]
Hey everyone,

I've started hacking on the engine (because I'm stuck at home with a bad cold), and for starters I began converting the code to c++11 (https://github.com/Ed-von-Schleck/godot/tree/c++11). Don't expect anything big soon, though. Skimming through the code there a lot of questions piling up in the vain of: Why re-invent the standard library (I started to tackle that, as you can see)? Why so much code duplication (and is there a goal to properly factor out copy&pasted code)? Why so little comments? Is there a possibility that the documentation system (I haven't really spent time with it) might be converted to something more standard (e.g. doxygen)? What's with the slightly odd coding style? What's with the tests (e.g. 'bin/godot -test gui' just opens a window, but I don't see automated tests running)? Where's the git (or whatever you used previously) history?

The forum seems to aim primarily at game devs, and not so much engine hackers. That's fine, but it leaves the impression that the engine is still something of an in-house, throw-over-the-wall-kind-of project.

I'd *love* to see documentation outlining answers to these kinds of questions (and more) and guidelines for hacking the engine. Also, I think a mailing list would be great.

Thanks for the open-sourcing of the engine! I believe it opens up great possibilities to improve the code quality of the engine.

**Comment by akien-mga** [comment]
Regarding the communication channel we have #godotengine-devel on Freenode.

**Comment by akien-mga** [comment]
See also https://github.com/godotengine/godot/issues/72#issuecomment-35148560 for some more input.

**Comment by akien-mga** [comment]
Moving to https://github.com/godotengine/godot-docs/issues/129 so that we can focus on the engine itself in this repo.
