### ISSUE TITLE
Mac (Fat format) export from Windows crashes (error -10825) on startup in Mac

### ISSUE THREAD

**Issue by IBwWG** [godotengine/godot#7300]
**Operating system or device - Godot version:**
exported from win7x64 godot 2.1.1
trying to launch via itch.io app on Mac OS X 10.10.5

**Issue description** (what happened, and what was expected):
On launch, an error popup says exit code 1.  In a log file this is the error detail the user gets:
![mac-probs2](https://cloud.githubusercontent.com/assets/16719964/21179983/f94794e8-c1f6-11e6-8fbd-f123efb8f74f.png)

Now, I'm aware the execute bit is still not set properly by godot ( #527 ), but [the itch.io app's documentation says that it is supposed to set this automatically when uploading with butler](https://itch.io/docs/itch/integrating/platforms/macos.html), which is what I used.  As you can see from the debug output it found the .app within the .zip OK.

**Steps to reproduce:**

Use the itch.io app (you can download from http://itch.io/app ) on Mac and try to install and launch the game https://ibwwg.itch.io/52cp2k from within the itch app.  You should get an error like this:

![mac-probs1](https://cloud.githubusercontent.com/assets/16719964/21180090/a7664628-c1f7-11e6-9879-a0dd1f7f5fc3.png)

I'm assuming this is a Godot problem, since the same procedure on Linux and Windows results in a running game.

**Link to minimal example project** (optional but very welcome):

https://github.com/IBwWG/52cp2k

**Comment by IBwWG** [comment]
Actually this can be closed!  While Godot should still mark it per the other issue, itch.io was recently patched to do the same thing.  So actually itch is now a great way to get around this current Godot limitation for those wanting to publish for Mac but from a Win box.  :)

**Comment by punto-** [comment]
So when you upload to itch.io, do you unzip the .app and send the files
individually? Maybe that's where it loses its executable bit? a "crash"
doesn't sound like it's related to the binary being executable anyway..

**Comment by IBwWG** [comment]
It doesn't lose it.  On Windows it can't have it in the first place.  But it was failing to add it (as was Godot) within the zip.  Now, it adds it.  It will add it whether you upload the .app itself, or the .zip that Godot makes, which contains the .app.  It may not have seemed like it was related, but, upgrading itch.io's butler to the latest and then re-uploading did seem to fix it in both cases.
