### ISSUE TITLE
subtract blend mode makes everything black

### ISSUE THREAD

**Issue by constantitus** [godotengine/godot#73022]
### Godot version

v4.0.beta.mono.custom_build.a05670c61

### System information

Gentoo Linux - 6.0.12 Zen Kernel

### Issue description

Selecting the "Subtract" blend mode for CanvasItemMaterial turns everything black.

![image](https://user-images.githubusercontent.com/118078873/217993641-80a3c27f-c018-480c-8f13-1c3a6c12f2c0.png)

https://user-images.githubusercontent.com/118078873/217993481-d2864c04-a4cc-4acb-af69-173e29e834e0.mp4

### Steps to reproduce

Create a Sprite2D, Select CanvasItemMaterial in the CanvasItem > Material section and choose the "Subtract" Blend Mode.

### Minimal reproduction project

[project.zip](https://github.com/godotengine/godot/files/10703485/project.zip)

**Comment by clayjohn** [comment]
Duplicate of https://github.com/godotengine/godot/issues/72488 and https://github.com/godotengine/godot/issues/72918

Will be fixed by https://github.com/godotengine/godot/pull/73006

Please remember to do a search of existing issues before opening a new bug report.
