### ISSUE TITLE
GDScript dictates my scene name(s): P1

### ISSUE THREAD

**Issue by clemens-tolboom** [godotengine/godot#73038]
### Godot version

v4.0.rc1.official [8843d9ad3]

### System information

MacOS

### Issue description

My scene has a Node named `P1`, `P2`, etc which results in

> Identifier "P1" is visually similar to the GDScript keyword "PI" and this not allowed.

Only the latter in the code snippet below works

```
#@onready var P1 = $P1
#@onready var P_1 = $P1
#@onready var P_1 = %P1
@onready var p_1 = get_node("P1")
```

I expected `$P1` to work (and another issue?: be able to suppress the warning `var P1`)

### Steps to reproduce

- Add a node named `P1` to a scene
- From code try to get it using $P1

### Minimal reproduction project

[p1_vs_pi.zip](https://github.com/godotengine/godot/files/10706898/p1_vs_pi.zip)

**Comment by Zireael07** [comment]
Duplicate of  #72978 already fixed by https://github.com/godotengine/godot/pull/72975

**Comment by clemens-tolboom** [comment]
Thanks
