### ISSUE TITLE
RC1: Using engine `GlobalScript` enum  as return type ends up in a compile error

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#73046]
### Godot version

v4.0.rc1.official [8843d9ad3]

### System information

ALL

### Issue description

I build a mock/spy and double all engine functions.
To double successfully i have to "shadow" the core function with the same function signature.

Since Godot RC1 it needs to using the correct enum as return type otherwise it will end up in a error.
`The function signature doesn't match the parent. Parent signature is "get_texture_filter() -> CanvasItem::TextureFilter".`

Godot RC1
```gdscript
@warning_ignore("native_method_override")
func get_texture_filter() -> TextureFilter:
  ...
```

Godot betaXX worked with an int 
```gdscript
@warning_ignore("native_method_override")
func get_texture_filter() -> int:
```

---
So i addapt the doubler to use the right enum when the method descriptor has defined a enum as return.
But it fails for the enum`@GlobalScope:Error` 

```gdscript
@warning_ignore("native_method_override")
func connect(signal_, callable_, flags_=0) -> Error:
```
`Parser Error: "Error" was not found in the current scope.`

### Steps to reproduce

Use this simple part to reproduce

```gdscript
extends RefCounted


# using an existing engine enum -- WORKS
func foo() -> CanvasItem.TextureFilter:
	return CanvasItem.TEXTURE_FILTER_PARENT_NODE


# using GlobalScript enum fails -- FAILS
func bar() -> Error:
	return OK

```

### Minimal reproduction project

N/A

**Comment by MikeSchulze** [comment]
In addition I found an invalid method description at ColorRect -> enum `Control.LayoutMode`
**The function not exist!**
'''
func test_foo():
	var c := ColorRect.new()
	for m in c.get_method_list():
		if m["name"] == "_get_layout_mode":
			prints(m)
```
`{ "name": "_get_layout_mode", "args": [], "default_args": [], "flags": 5, "id": 3820, "return": { "name": "", "class_name": &"Control.LayoutMode", "type": 2, "hint": 0, "hint_string": "", "usage": 65542 } }`

**Comment by YuriSizov** [comment]
> **Invalid method description for many classes, e.g. ColorRect -> enum `Control.LayoutMode`**
> 
> The function `_get_layout_mode` not exist.
> 
> ```
> func test_foo():
> 	var c := ColorRect.new()
> 	for m in c.get_method_list():
> 		if m["name"] == "_get_layout_mode":
> 			prints(m)
> ```
> 
> `{ "name": "_get_layout_mode", "args": [], "default_args": [], "flags": 5, "id": 3820, "return": { "name": "", "class_name": &"Control.LayoutMode", "type": 2, "hint": 0, "hint_string": "", "usage": 65542 } }`

Layout mode is an internal property, and you are not supposed to use it, nor its hidden setter and getter, nor the enum.

**Comment by MikeSchulze** [comment]
> > **Invalid method description for many classes, e.g. ColorRect -> enum `Control.LayoutMode`**
> > The function `_get_layout_mode` not exist.
> > ```
> > func test_foo():
> > 	var c := ColorRect.new()
> > 	for m in c.get_method_list():
> > 		if m["name"] == "_get_layout_mode":
> > 			prints(m)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `{ "name": "_get_layout_mode", "args": [], "default_args": [], "flags": 5, "id": 3820, "return": { "name": "", "class_name": &"Control.LayoutMode", "type": 2, "hint": 0, "hint_string": "", "usage": 65542 } }`
> 
> Layout mode is an internal property, and you are not supposed to use it in scripting, nor its hidden setter and getter, nor the enum.

_get_layout_mode is listed at `ClassDB.class_get_method_list(clazz_name)`

**Comment by YuriSizov** [comment]
Of course it is, it's registered as a setter for a property. But it's a private method and it's not available through documentation and code completion. You can filter it (and other such methods) out by checking that it starts with an underscore and it is not `METHOD_FLAG_VIRTUAL`.

**Comment by MikeSchulze** [comment]
Thats wrong e.g. function `_ready` begins also with an underscore and is virtual
`{ "name": "_ready", "args": [], "default_args": [], "flags": 8, "id": 0, "return": { "name": "", "class_name": &"", "type": 0, "hint": 0, "hint_string": "", "usage": 6 } }`

**Comment by YuriSizov** [comment]
> begins also with an underscore and is virtual

Exactly, it is virtual. And `_get_layout_mode` is not.

**Comment by MikeSchulze** [comment]
> > begins also with an underscore and is virtual
> 
> Exactly, it is virtual. And `_get_layout_mode` is not.

ah you wrote and it is **not** METHOD_FLAG_VIRTUAL. my fould :)

**Comment by MikeSchulze** [comment]
But the invalid method descriptors is a problem.
You can detect it by this small code
```gdscript
static func is_invalid_method_descriptior(clazz :String, method :Dictionary) -> bool:
	var return_info = method["return"]
	var type :int = return_info["type"]
	var usage :int = return_info["usage"]
	var clazz_name :String = return_info["class_name"]
	# is method returning a type int with a given 'class_name' we have an enum
	# and the PROPERTY_USAGE_CLASS_IS_ENUM must be set
	if type == TYPE_INT and not clazz_name.is_empty() and not (usage & PROPERTY_USAGE_CLASS_IS_ENUM):
		prints("'%s': invalid method descriptor found! %s" % [clazz, method])
		return true
	return true

func test_foo():
	
	var count := 0
	for clazz_name in ClassDB.get_class_list():
		for method in ClassDB.class_get_method_list(clazz_name):
			if is_invalid_method_descriptior(clazz_name, method):
				count +=1
	
	prints("-----------------------------------")
	prints("%d invalid method descriptors found" % count)
```

-----------------------------------
128033 invalid method descriptors found

**Comment by YuriSizov** [comment]
The issue with enums in general seems to be the same as in https://github.com/godotengine/godot/issues/72963.

**Comment by MikeSchulze** [comment]
Thank you for your quick help
