### ISSUE TITLE
[4.0] deep_equal is missing

### ISSUE THREAD

**Issue by Protowalker** [godotengine/godot#73049]
### Godot version

4.0.dev

### System information

Windows 10

### Issue description

`deep_equal` was initially implemented by #42625. The code still exists and is still used internally, but has been renamed `recursive_equal`. Since it's used internally, my assumption is that it is working, and just hasn't been re-exposed. https://github.com/godotengine/godot/blob/master/core/variant/array.cpp#LL121C22-L121C22

### Steps to reproduce

1. Enter a gdscript file.  
2. Call `deep_equal({}, {})`  
3. A "not defined" error will appear.
4. Call `recursive_equal({}, {})`
5. A "not defined" error will appear.

### Minimal reproduction project

N/A

**Comment by YuriSizov** [comment]
In Godot 4 arrays and dictionaries are compared by value, and that comparison is performed internally by `recursive_equal`. This means you can simply use `==` and `!=` to compare.
