### ISSUE TITLE
Duplicate files on Import

### ISSUE THREAD

**Issue by Jordancjb** [godotengine/godot#73053]
### Godot version

4.0.rc1

### System information

Windows 11, AMD Ryzen 5 5600x, AMD Radeon RX 6750XT, Vulkan

### Issue description

Files(.glb tested) appear to be duplicated upon import into a new project. When removed both files appear to be removed, but an empty file icon is left behind.

![image](https://user-images.githubusercontent.com/33920543/218169496-1ba7dee9-963c-4201-8ab8-b3ad94d2f9b2.png)

### Steps to reproduce

Import .glb file into new project in godot 4.0.rc1

### Minimal reproduction project

N/A

**Comment by Jordancjb** [comment]
Update: It appears reloading current project after this happens crashes Godot. You have to open it manually.

**Comment by Zireael07** [comment]
How did you import the file? Did you drag and drop into Godot?

**Comment by Jordancjb** [comment]
> How did you import the file? Did you drag and drop into Godot?

Yes, from the file explorer.

**Comment by Zireael07** [comment]
I know the multiple entries in filesystem dock (ghost entries) was reported previously but I can't find the other issue atm.

**Comment by Saul2022** [comment]
It happened the same to me with blend files, and when i deleted one it suddenly crashed.

**Comment by gotharcade** [comment]
I have this same issue. In addition, the texture on the .glb model is displayed incorrectly. 
Interestingly, when I opened the project created in RC1 in beta17, I was able to delete the "ghost entries" without crashing. However, when I then re-imported the same .glb model in beta17, there were 3 ghost entries instead of the usual 2, and deleting those ones did result in a crash. 
All .glb files were created in the same version of Blender 3.4

**Comment by gotharcade** [comment]
Ah, this issue appears to be related to #53871

**Comment by YuriSizov** [comment]
https://github.com/godotengine/godot/pull/73159 may address a ghosting issue, if it is accepted (at least I noticed _a_ ghosting issue with drag'n'dropping images from the issue linked above, and I fixed that).

**Comment by YuriSizov** [comment]
We merged https://github.com/godotengine/godot/pull/73214 instead. Would be nice to re-test this issue with that fix applied.

**Comment by Saul2022** [comment]
Yea, waiting for rc2

**Comment by gotharcade** [comment]
Just tested this in RC2 with a few different .glb files, the issue seems to be resolved on my end. Was able to import files via drag-and-drop without any duplicate entries, and was also able to delete them without any errors or issues.

**Comment by YuriSizov** [comment]
Superb!
