### ISSUE TITLE
"Face Corner" color attributes from Blender are not recognized

### ISSUE THREAD

**Issue by Zorochase** [godotengine/godot#73056]
### Godot version

3.5.1.stable, 4.0.rc1

### System information

Windows 11, GLES3/Vulkan, NVIDIA GTX 1060

### Issue description

In Blender 3.2+, the vertex paint tool works differently in the "Vertex" domain than it does in the "Face Corner" domain. In order to paint individual faces, I have to (afaik) create a color attribute set to use the "Face Corner" domain. However, Godot doesn't recognize this domain, and colors aren't recognized/rendered when exported from Blender and imported into Godot, even with a material applied.

For example, I have a cube model I made in Blender, with a color attribute using the "Face Corner" domain. I painted its front face black, and the rest of the faces white. Importing this into Godot, either by saving the .blend file - or exporting a (for example) .glb file - to the project directory, I would expect to see the following:

![Expected](https://user-images.githubusercontent.com/101901701/218185669-0322bef6-7301-4473-a8e6-ed8454bcdf89.png)

However, this is not the case. Instead, the colors are simply not present, and there doesn't seem to be any way to get them to render.

This is a problem because it means I now have to revert to an older version of Blender just to be able to achieve this sort of effect and have it work in Godot.

As a side note, though I feel like this may need to be reported separately, vertex colors on models from .blend files imported directly are _never_ visible, no matter the domain or data type of the color attribute.

### Steps to reproduce

Download the attached MRP and unzip it. You'll find two folders, one with a project for 3.x, and another for 4.x. Open either one and try to create an inherited scene of any of the included .glb files. You'll notice that vertex colors only render for the models in the "vertex" folder (with the exception of the "old" folder, which includes a model made in an older Blender version).

To touch on the side note from earlier, the 4.x version contains the original .blend files, but in trying to create inherited scenes for any of those, you'll notice the vertex colors never show up, no matter the domain. Again, I'm not sure if that needs an issue of its own, or is due to the same problem causing the main issue at hand. I've tried adding a material to them, both in Blender and Godot, but that doesn't do anything.

### Minimal reproduction project

[Face Corner Color Issue MRP.zip](https://github.com/godotengine/godot/files/10710822/Face.Corner.Color.Issue.MRP.zip)

**Comment by clayjohn** [comment]
I think this is actually an issue with Blender's exporter. If you import the GLB file into Blender it looks the same as it does in Godot. In both cases the vertex colors are lost and the cube appears totally white

**Comment by Zorochase** [comment]
> I think this is actually an issue with Blender's exporter. If you import the FaceCornerColor.glb file into Blender it looks the same as it does in Godot. In both cases the vertex colors are lost and the cube appears totally white

You're right. I should've thought to try that before opening the issue, my bad. In that case, should this be closed? I'm not sure there's anything that can be done on Godot's end to solve this.

**Comment by clayjohn** [comment]
> @Zorochase
> 
> > I'm not sure there's anything that can be done on Godot's end to solve this.
> 
> Unless there's some weird extra metadata that could be somehow hackishly parsed, no, but even then it wouldn't certainly be appropriate.
> 
> If the file's exported wrong, it's Blender's problem.
> 
> I've been thinking, though, does gltf even support face corner attributes? I fear that it might be some blenderism not supported by the format itself.

GLTF really just understands arrays of vertex info. So Blender should be baking the face corner attributes into the vertex data. Likely it needs to duplicate vertices per face corner so each can carry their own data. I'm not sure how complex that is as I am not familiar with Blender's face corner paradigm.

**Comment by Calinou** [comment]
Reopening, as this should be documented in [Importing 3D scenes](https://docs.godotengine.org/en/latest/tutorials/assets_pipeline/importing_scenes.html).

**Comment by warcanin** [comment]
Don't bother i reported the issue on blender.org and they have fixed it, it is already fixed on the 3.5+ version of blender.
