### ISSUE TITLE
Can't jump to autoload members using Lookup Symbol

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#73058]
### Godot version

4.0 RC1

### System information

Windows 10 x64

### Issue description

When you have any autload with any method, the method completes correctly, but you can't Ctrl+Click to go to its definition.

https://user-images.githubusercontent.com/2223172/218195754-f71e94fc-2041-4507-af34-1960ec623a68.mp4

### Steps to reproduce

1. Have autoload script
2. Add any method
3. Call this method in some script
4. Try to go to definition

### Minimal reproduction project

N/A

**Comment by Vilcrow** [comment]
Does it work in 3.5.1?

**Comment by Vilcrow** [comment]
Yeah, the reason of this bug is #72789. The PR #73196 must fix it.
