### ISSUE TITLE
The purple tooltip does not follow the rotation when Camera2D rotates within the editor

### ISSUE THREAD

**Issue by L2750558108** [godotengine/godot#73079]
### Godot version

4.0(rc 1) mono

### System information

windows10

### Issue description

The purple rect of camera does not follow the rotation when Camera2D rotates within the editor.
![image](https://user-images.githubusercontent.com/119792950/218244292-5bb39e8d-8596-4c27-975f-d5f2bab5f256.png)

### Steps to reproduce

1.Create a Camera2D Node
2.Go to the inspector
3.Change the value of rotation
4.See the purple rect of camera does not rotate

### Minimal reproduction project

An empty project

**Comment by KoBeWi** [comment]
You have `ignore_rotation` enabled.
