### ISSUE TITLE
Can't assign variable to script property

### ISSUE THREAD

**Issue by jheng-jie** [godotengine/godot#73072]
### Godot version

4.0.rc.1

### System information

mac m1

### Issue description

- error

```
@onready var role = $role # RigidBody2D Mounted a script

func _ready():
  role.bodyScale = 1.0 # Invalid set index 'bodyScale' (on base: 'RigidBody2D') with value of type 'float'.
```

- RigidBody2D script content

```
var bodyScale: float = 3.0
```

---

beta.11 is working. but it can't be used after upgrading rc

### Steps to reproduce

#

### Minimal reproduction project

#

**Comment by Seubmarine** [comment]
Specs:
    AMD Ryzen 5 5600X 6-Core Processor
    16gb ram
    NVIDIA Geforce RTX 3070

Can't reproduce in 4.0.rc1
Everything works normally, are you sure you did not forget to `extends RigidBody2D` inside your RigidBody2D script
And to extends whatever type is the parent script ?

**Comment by jheng-jie** [comment]
i can reproduce. [test project](https://github.com/jheng-jie/godot4.rc.1-script-property)

**Comment by Seubmarine** [comment]
You have a typo in player.gd where you try to access bodySacle instead of bodyScale

**Comment by jheng-jie** [comment]
oh... my bad. But my main project is not typo. I am moving some content to try

**Comment by jheng-jie** [comment]
is my problem

i am correcting

```
Invalid set index 'playback_speed' (on base: 'AnimationPlayer') with value of type 'float'.
```

accidentally broke the script. resulting in no binding script

sorry
