### ISSUE TITLE
Dragging in the editor filesystem both drags the file and scrolls the view

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#73087]
### Godot version

godot 4 RC1

### System information

Android 13, Samsung Galaxy 7 FE

### Issue description

Dragging on top of the filesystem tab both moves the file and scrolls the view. I'm not 100% sure this is an issue, perhaps its just some sort of muscle memory from other softwares. Ithink it  would be easier for me if the filesystem tab had a "lock file movement" mode or something similar, that i can enable and disable depending on wheter im moving files or not.

### Steps to reproduce

Create a project with Godot 4 on android, create enough files to make a scroll bar appear, try to scroll the filesystem dock by just dragging with your big thumb on top of all files instead of using the scroll bar. Perhpas i just have big thumbs.

### Minimal reproduction project

See above

**Comment by m4gr3d** [comment]
This is as intended at the moment; scrolling the filesystem dock (or other editor docks) in only supported via the scrollbar, or using a mouse.
Using a finger is interpreted as a drag intent (e.g: re-arranging nodes).
