### ISSUE TITLE
Renaming popup for script does not auto-focus the text field

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#73099]
### Godot version

4 RC1

### System information

Android 13, Samsung Galaxy 7 FE

### Issue description

The rename popup doesnt auto focus on the text field. note i'm using a samsung keyboard with the editor

### Steps to reproduce

open a project, rename a file, try to type with the attached keyboard (not virtual keyboard), doesn't change the textbox

### Minimal reproduction project

see above

**Comment by m4gr3d** [comment]
Fixed by https://github.com/godotengine/godot/pull/76794
