### ISSUE TITLE
Changing focused app on android quits the editor to project settings

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#73093]
### Godot version

4 RC1

### System information

Android 13, Samsung Galaxy 7 FE

### Issue description

When i tab to another app (for example the browser etc.) and go back to the godot editor, i am prompted again with the project setting. it's not an issue for now because my project is almost empty, but  it will likely be an issue later on when the project starts having more resources.

### Steps to reproduce

open godot editor on android, open a project, change to another app (web browser), observe you're brought back to project selection

### Minimal reproduction project

see above

**Comment by m4gr3d** [comment]
Please check you haven't configured your device to kill backgrounded apps, or limit the number of activities they can run.
