### ISSUE TITLE
Custom modules somehow break script class cache

### ISSUE THREAD

**Issue by karljs** [godotengine/godot#73104]
### Godot version

4.0 rc 1

### System information

MacOS 13.1 

### Issue description

I use Godot with custom C++ modules for the [Spine runtime](https://github.com/EsotericSoftware/spine-runtimes). All those builds, both those provided by the Spine folks and ones I've built myself, fail to update `.godot/global_script_class_cache.cfg`.

These builds do not modify any part of the core Godot code and only adds additional functionality.  Even if, hypothetically, there were some error in the added module code, it seems like it shouldn't prevent Godot from performing basic functionality.

### Steps to reproduce

- Visit [the Spine Godot page](http://en.esotericsoftware.com/spine-godot)
- Download the version built from the latest 4.0 code
- Create a new project and add a single scene/script with `class_name Junk` at the top of the file
- Note that `.godot/global_script_class_cache.cfg` still reads `list=[]`
- Repeat steps in the vanilla RC1 and note that the file is updated correctly.

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
This should probably be debugged first with the Spine runtime's maintainers (CC @badlogic) to determine whether this is indeed a Godot bug, or a bug in that module specifically.

Godot itself comes with a lot of builtin modules and does not suffer from this issue, so it seems the Spine module is doing something specific which triggers the issue.

**Comment by badlogic** [comment]
As we are up-to-date with master and this doesn't happen in vanilla Godot,
I'm pretty sure the error is on our end. I'll investigate. I think this can
be closed.

**Comment by YuriSizov** [comment]
Closing per the comment above.
