### ISSUE TITLE
Wrong input mapping for modifier keys in html5 export

### ISSUE THREAD

**Issue by baconsaur** [godotengine/godot#73105]
### Godot version

4.0-beta17

### System information

Ubuntu 20.04

### Issue description

HTML5 exports handle input events for modifier keys differently from running the project in the editor. For example: if shift is mapped to an event named "shift" and S is mapped to an event named "down", they trigger the correct events in the editor, but in HTML5, pressing shift triggers "down" instead of "shift". I also exported the project for linux and it worked the same way as the editor. I haven't tested windows/macOS.

When I made the minimal reproduction project to investigate, I also noticed a difference in the input events: `event.as_text()` in the editor shows "Shift", "Alt", and "Ctrl", as expected, but after exporting to HTML5 they become "Shift+Shift", "Ctrl+Ctrl", and "Alt+Alt". That doesn't necessarily explain why shift is getting mixed up with S and may be an unrelated issue, but I would expect them to match.

### Steps to reproduce

Run the reproduction project in the editor. When you press a key, a label should show the key pressed and the action name, if applicable. WASD keys map to "up", "left", "down", "right" respectively. Shift maps to "shift".

Run [the html5 export](https://tetrapteryx.itch.io/test-godot-bug?secret=Nymj68e0XaYmGMfhvHwi4lLOxo) of the project and do the same thing. The WASD keys should all work the same as in the editor, but pressing modifier keys shows "Shift+Shift", "Ctrl+Ctrl", and "Alt+Alt", and shift maps to "down" instead of "shift".

### Minimal reproduction project

Project: [test-input-bug.zip](https://github.com/godotengine/godot/files/10714016/test-input-bug.zip)

[HTML5 export](https://tetrapteryx.itch.io/test-godot-bug?secret=Nymj68e0XaYmGMfhvHwi4lLOxo)

**Comment by akien-mga** [comment]
CC @Faless @bruvzg
