### ISSUE TITLE
Quick Edit of Input Mapping

### ISSUE THREAD

**Issue by Tybobobo** [godotengine/godot#7312]
~~Inside Project Settings -> Input Map, you are unable to edit added action names. You would have to remove it and re-add it along with all the input mapping that was previously set to do so.~~

You should be able to double click input mapping in order to edit it, instead of having to delete it and readd it. It is a minor change, but would make it more user-friendly to a small degree :)

![](http://i.imgur.com/csqmRdL.png)

~~I believe it would be an improvement to allow users to edit those without having to remake the entire action.~~

_(Searched for this issue, but failed to find any opened issues)_

**Comment by neikeq** [comment]
You mean input presets, right? Then it's related to #4315

IIRC, last time we didn't get to any consensus on whether or not allow modifying input presets.

**Comment by Tybobobo** [comment]
Oh my god, you are right. Did not realize I could not edit the presets - thought it was any and every action. Apparently you can only edit custom actions. Editing this to reflect editing input mapping only, without the need to remove and re-add :)
