### ISSUE TITLE
LightmapGI: Lightmaps for direct lighting not displaying correctly at runtime or when re-opening the project

### ISSUE THREAD

**Issue by BlockyDK** [godotengine/godot#73122]
### Godot version

Godot 4 RC1

### System information

Windows 10, GeForce 3070

### Issue description

When baking lighting from a directional light with everything set to static, the lightmaps for the direct lighting don't display correctly when running the scene, even when they look correct in the editor viewport. Additionally, when closing and re-opening the project, the lightmaps no longer look correct in the editor viewport either. In the included screenshot, the left shows the scene in editor, and the right is at runtime in the gameplay window. You can see the edges of the shadows are splotchy.

I've played around with a bunch of settings, such as the Quality and the Lightmap resolution, none seem to have any effect.

![Godot_RC1_LightmapRuntime](https://user-images.githubusercontent.com/42628327/218278830-5661414f-6b8d-45ff-a18c-2660bbec19e2.jpg)
![image](https://user-images.githubusercontent.com/42628327/218279002-9abf1c04-cb74-49c8-b266-72e9db51ddf0.png)
![image](https://user-images.githubusercontent.com/42628327/218279012-0f189c6f-d0b4-40ba-a1e0-d53d9f55c1c1.png)
![image](https://user-images.githubusercontent.com/42628327/218279028-a930326d-98eb-44c8-bfb5-65ecb3781e5b.png)

### Steps to reproduce

1. Create a scene where all the static meshes are imported with Light Baking set to Static Lightmaps and there Global Illumination mode is set to Static.
2. Place a directional light in that scene with shadows enabled and the Bake Mode set to Static.
3. Add a LightmapGI and Bake the Lightmaps for the scene.
4. Run the game.

### Minimal reproduction project

[RC1_LightmapGI_RuntimeTest.zip](https://github.com/godotengine/godot/files/10714625/RC1_LightmapGI_RuntimeTest.zip)

**Comment by Calinou** [comment]
If lightmaps disappear depending on camera position/rotation (in both editor and running project), this is already being tracked in https://github.com/godotengine/godot/issues/71585.

**Comment by BlockyDK** [comment]
So far in none of my testing has the camera position/rotation had any effect on the lightmaps, they just end up looking really noisy at runtime or when restarting the editor. But just to add some additional clarity

Editor:
![image](https://user-images.githubusercontent.com/42628327/218282963-c1101d4c-f0cd-4cff-b20d-4bff46a7f24f.png)

Runtime or in Editor after restart:
![image](https://user-images.githubusercontent.com/42628327/218282974-3486ac20-d936-4bca-9b61-09d06b892ad4.png)

**Comment by Calinou** [comment]
This is likely due to https://github.com/godotengine/godot/issues/72666. Can you reproduce this if you change the compression mode to **Lossless** on the EXR image in the Import dock?

**Comment by BlockyDK** [comment]
Switching to Lossless for the EXR import fixed this issue, looks like you are right :)
