### ISSUE TITLE
Godot 4.0 RC1 `ImageTexture.CreateFromImage` does not render transparent pixels in PNG

### ISSUE THREAD

**Issue by pcen** [godotengine/godot#73128]
### Godot version

4.0.rc1.mono

### System information

macOS Ventura 13.1, M1, Vulkan 1.2.231

### Issue description

Textures created from `ImageTexture.CreateFromImage` (C#) render transparent pixels as magenta, but are rendered as transparent when the texture is set in the editor.
Texture loaded from c# onto a TextureRect node:
<img width="332" alt="Screenshot 2023-02-11 at 4 57 45 PM" src="https://user-images.githubusercontent.com/43939602/218282810-8edca6e5-29b1-460d-a6e3-a726d12974e0.png">
Same texture opened in editor: 
<img width="332" alt="Screenshot 2023-02-11 at 4 58 56 PM" src="https://user-images.githubusercontent.com/43939602/218282863-d26f338e-2920-4027-b174-bb6833c5b176.png">

- texture is loaded correctly in a Godot script using `load`
- texture does not load at all in C# script using `GD.Load<ImageTexture>`

### Steps to reproduce

load and set an `ImageTexture` in c# script for a `TextureRect` from a png with an alpha channel and transparent pixels:
```
Image img = Image.LoadFromFile("res://foo.png");
ImageTexture tex = ImageTexture.CreateFromImage(img);
this.Texture = tex;
```

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
Pretty sure it's a problem with that specific texture not C#.

**Comment by pcen** [comment]
In this case, the magenta is due to the texture, however I believe the behaviour is still not as expected. The magenta pixels being rendered all have an alpha value of 0, but whereas in Godot 3.x they were not being rendered, there's some kind of blending happening when the texture is created as described in the issue

**Comment by KoBeWi** [comment]
Please attach the textures to make it easier to test.

**Comment by pcen** [comment]
here's an example texture

![img_11](https://user-images.githubusercontent.com/43939602/218295053-c82f0c5f-af7d-48c3-901b-ddf315104bcf.png)

**Comment by Mickeon** [comment]
In the texture provided, I do not see any magenta with alpha set to 0, so I can't even imagine where the magenta comes from.

**Comment by KoBeWi** [comment]
Well, can't reproduce.
![image](https://user-images.githubusercontent.com/2223172/218322322-64712a82-baeb-438d-8872-80528abd0a73.png)

**Comment by pcen** [comment]
thanks for testing. closing for now since it doesn't seem reproducible
