### ISSUE TITLE
Can't export projects from the Android editor due to the export dialog having a fixed size, making the button unreachable

### ISSUE THREAD

**Issue by ItzFafa** [godotengine/godot#73130]
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

4.0.0.beta.17

### System information

Android 12 Mediatik helio g95

### Issue description

There are no export button to export our projects to apk on google play godot app

### Steps to reproduce

Click export then add and click on Android there is no export button

### Minimal reproduction project

Any project 3d or 2d can't be exported

**Comment by Calinou** [comment]
In theory, exporting apps to desktop platforms could be supported (even though you'd have no way to run those apps on the device itself).

However, exporting apps from the Android editor is impossible to support, as you can't install the necessary tooling on an Android device (Android SDK tools).

**Comment by YuriSizov** [comment]
That's a known limitation described in the announcement article.

**Comment by Raffa064** [comment]
> That's a known limitation described in the [announcement article](https://godotengine.org/article/android_godot_editor_play_store_beta_release/).

As I said before in my issue, it was possible to export apk before! I made a video showing this: https://youtu.be/qwz-KZzAxoM

**Comment by jiangqiuming** [comment]
我认为开发团队不应当隐藏这个按钮，这对我们一些特定的开发群体来说是个可选项，而不是“死路”

**Comment by Booklight12** [comment]
I don't think the development team should hide this button, it should be an option for some of us as a developer community, not a dead end. In the meantime, since the above has proven that exporting on Android is feasible, I think we can return the button to its original position (of course, if the dev team has other considerations such as adaptation, hopefully that will be expressed, rather than making us jealous of each other here).

**Comment by longPtrCall** [comment]
The export button could exists and available, but the export dialog has fixed size and button is located out of screen.
To fix this issue export dialog must have an adaptive size.

**Comment by Booklight12** [comment]
> The export button could exists and available, but the export dialog has fixed size and button is located out of screen. To fix this issue export dialog must have an adaptive size.

As far as I know, it was deliberate.

**Comment by Calinou** [comment]
> As far as I know, it was deliberate.

This was indeed an intentional change, but there's no point in exposing the option if it looks broken on most displays.

**Comment by Booklight12** [comment]
> > As far as I know, it was deliberate.
> 
> This was indeed an intentional change, but there's no point in exposing the option if it looks broken on most displays. As per the [Code of Conduct](https://godotengine.org/code-of-conduct), always assume positive intent 🙂

so.Are there any plans to add support for exporting on Android in a future release?

**Comment by Booklight12** [comment]
This is not my personal appeal by any means. Since it is not working properly at this stage, are there any official plans to make it work properly in the future? As far as I know, some Android engines already support this

**Comment by Calinou** [comment]
> This is not my personal appeal by any means. Since it is not working properly at this stage, are there any official plans to make it work properly in the future? As far as I know, some Android engines already support this

There is no ETA for fixing this issue, as contributors work on a best-effort basis.

**Comment by longPtrCall** [comment]
> > This is not my personal appeal by any means. Since it is not working properly at this stage, are there any official plans to make it work properly in the future? As far as I know, some Android engines already support this
> 
> There is no ETA for fixing this issue, as contributors work on a best-effort basis. Most core contributors don't use the Android editor as a daily driver, so this will likely take a while to be resolved.

Maybe you're right, but I don't think that changing window layout is a really challenging task, as godot's framework already has all necessary utilities to create an adaptive layout.

Sure, there is no reason to prioritise this issue, but it still exists and needs to be solved. 

:]

**Comment by a-f-larionov** [comment]
Godot editor 4.2.1 bug still exists. I can not export project from android. Export dialog super height.
![Screenshot_20240114_011417_Godot Editor 4](https://github.com/godotengine/godot/assets/7540279/5d6a293e-b630-4e7b-ae0b-5687a34daccd)

**Comment by nacho00112** [comment]
I think this should have more priority not in the project in general but in the android editor itself,
what I'm trying to say is that this would be good to have it solved before the next update of the android editor, because it already has been updated multiple times but this issue still occurs, and without this there's no point on developing the games in the android editor if you can't export to at least zip or pck that is what the documentation tells you to do in the android editor.
