### ISSUE TITLE
Scrollbar overlaps text in Godot 4 RC1 "About" Dialog box

### ISSUE THREAD

**Issue by knadoor** [godotengine/godot#73139]
### Godot version

Godot 4 RC1

### System information

MacOS Ventura 13.2

### Issue description

The scrollbars overlap text in the Godot "About" dialog box.

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/8476589/218290294-8bad2151-9f83-45b6-a024-f518e1f966a6.png">

### Steps to reproduce

1.  Open the Godot Help
2. Go to the "Third-party licenses" tab
3. Observe text overlap as per screenshot.

### Minimal reproduction project

N/A

**Comment by YuriSizov** [comment]
I don't think this is an issue?

**Comment by knadoor** [comment]
Okay agreed.

One other thing, the UX would look better imo if the spaces between the container and the scrollbars were closer (if possible) to match with the other scrollbar on screen. As below:

![image](https://user-images.githubusercontent.com/8476589/220216802-ddff7096-e792-4d9a-abdd-59fd2a2318d9.png)

**Comment by YuriSizov** [comment]
That is actually a bug and there is a PR that addresses it: https://github.com/godotengine/godot/pull/70901.
