### ISSUE TITLE
3-to-4 conversion renames all "remove" functions

### ISSUE THREAD

**Issue by Pennycook** [godotengine/godot#73143]
### Godot version

v4.0.rc1.official [8843d9ad3]

### System information

Steam OS Holo, Steam Deck

### Issue description

The conversion rule renaming `remove` to `remove_at` for `Array` objects is applied to all functions named `remove`.

### Steps to reproduce

Create a 3.0 project with a function called "remove" in any script:
```gdscript
extends Node

func remove():
	pass
```

After converting to 4.0, the function will be called "remove_at":
```gdscript
extends Node

func remove_at():
	pass
```

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
Could be commented out as a too risky rename.
