### ISSUE TITLE
[GDextension]I found a bug but implemented hot reload by this bug

### ISSUE THREAD

**Issue by cosmos-in-h2o** [godotengine/godot#73148]
### Godot version

4.0 rc1

### System information

windows 10

### Issue description

I first changed the original xx.dll file to xxa.dll when the godot editor is beening opened, and the name was not changed in gdextension. Then compile to generate xx.dll. when I modify the code and recompile,
compilation succeeded,editor is still open,godot runs the content of xx.dll.If this is a bug,please don't repair it. : )

### Steps to reproduce

As above

### Minimal reproduction project

Because I don't remember how to do it at that time, so the description may be wrong, but the effect is the same as video

https://user-images.githubusercontent.com/69554835/218303178-e85694ca-b68e-4fc1-844a-a847d1f7e44d.mp4

**Comment by dsnopek** [comment]
Thanks!

I don't think this is a bug, but now that we support hot reload in Godot 4.2+, there is an easier way to accomplish what you're doing here. So, I'm going to close this one.
