### ISSUE TITLE
I have to press enter to change the value, even though the editor shows the value I entered at all times

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#7314]
**Operating system or device - Godot version:**
current master branch commit id: afbe013ba12d68f20ef1dfe2d7a895105a440bd9

**Issue description** (what happened, and what was expected):
I was trying to change the FPS of an animated script and when I typed in 10 instead of 5 and hit play it didn't change anything. I later understood it's because I never pressed Enter after changing the value. Now I believe if there is no save button some where that I can press then I expect my setting to be applied right after I type in the value. Having to press Enter wasn't really obvious to me, I thought it was a bug and kept trying to fix it. especially that the value I entered **does not change back** when I leave the screen or click away or play the game or whatever.

So what do you guys think?
**Steps to reproduce:**
Try to change the value of any property without pressing enter.

**Link to minimal example project** (optional but very welcome):

**Comment by jesperkondrup** [comment]
I agree. 
Strangely enough, some values can actually be changed without pressing Enter while others can't.

Example: Rotation and Opacity can be changed without pressing Enter, while Position and Scale needs the Enter button pressed in order to change.

**Comment by bojidar-bg** [comment]
@jesperkondrup Not strange at all, this just shows it affects only Vector2 and similar types of properties.

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by jesperkondrup** [comment]
This issue is still relevant in 3.1

**Comment by KoBeWi** [comment]
Tested in 3.1.1 stable. When you press outside the box, the value is stored, which means the issue is fixed.
