### ISSUE TITLE
BlendTree: NodeOneShot blending mode broken on master (still worked in RC1)

### ISSUE THREAD

**Issue by LemiSt24** [godotengine/godot#73155]
### Godot version

v4.0.rc.custom_build.a4c2d8dc7

### System information

Manjaro Linux

### Issue description

One-Shot Nodes in BlendTrees used to correctly blend and filter the selected animation tracks.
However, some change between the RC1 release and current master broke this functionality.
Now, all animation tracks from the one-shot animation are always applied and the other animation is paused, no filtering happens. However, it works when using the "add"-mode instead of "blend".

https://user-images.githubusercontent.com/4104810/218312448-fbb044a5-edd1-4d39-ac4b-c8caa4d2bf19.mp4

### Steps to reproduce

Create an animation blend tree, add two animation nodes, connect them via a one-shot node (and filter some of the animation tracks). Trigger the one-shot node.

### Minimal reproduction project

[oneshot_broken_minimal_repro.zip](https://github.com/godotengine/godot/files/10716098/oneshot_broken_minimal_repro.zip)

**Comment by TokageItLab** [comment]
I think it conflicts with the #73024 resolution. I will look into whether that is something that can co-exist....
