### ISSUE TITLE
add the ability to change FPS of animated sprite from GDScript

### ISSUE THREAD

**Issue by lordadamson** [godotengine/godot#7315]

**Comment by Zylann** [comment]
I think that's what you are looking for: http://docs.godotengine.org/en/latest/classes/class_spriteframes.html#class-spriteframes-set-animation-speed

**Comment by lordadamson** [comment]
hmmm so I was indeed able to set the FPS by calling `get_sprite_frames().set_animation_speed("walk", 24.0)`

Thank you sir.
