### ISSUE TITLE
Lookup Symbol does not always work (regression in 4.0 RC 1)

### ISSUE THREAD

**Issue by BetaMaxHero** [godotengine/godot#73167]
### Godot version

v4.0.rc1.official [8843d9ad3]

### System information

Windows 11 Pro 64Bit

### Issue description

Hi,

Found a rather annoying bug in 4.0 RC1 official on Windows 11:
When right clicking on a function in code and selecting "Lookup Symbol" - it does not always work?
Sometimes it works, sometimes it does not work?

Any ideas?

Jesse

### Steps to reproduce

Right click on a function in code and select "Lookup Symbol".
(it does not work always?)

### Minimal reproduction project

N.A.

**Comment by KoBeWi** [comment]
Yeah symbol lookup seems to be spotty.
For me it fails for autoloads: #73058
Might be same issue.

**Comment by Calinou** [comment]
@BetaMaxHero Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by BetaMaxHero** [comment]
Hi,

Was using 3.x before using 4.0, and this was never an issue.
I went back to 4.0 Beta 17 and it works 100%.

"Lookup Symbol" is an IDE feature I use ALOT.
Definitely something wrong with 4.0 RC1

Jesse

**Comment by akien-mga** [comment]
Might be a regression from #72789 then, CC @Vilcrow @vnen.

**Comment by Vilcrow** [comment]
I tested this in 3.5.1.stable on Ubuntu, there was a similar problem: the `Lookup Symbol` button not always work. I think the reason isn't #72789, but this fix doesn't work correctly: `Ctrl+Click` will always lead to a function in the current script, even if it is a method of another class. I will deal with this issue.
@KoBeWi I couldn't reproduce #73058 on Ubuntu.

**Comment by Vilcrow** [comment]
I think i fix mistake in #72789 by #73196. I will think about fixing  #73167. It may be possible to include a solution to this bug in the same PR.
