### ISSUE TITLE
Automplete breaks when using @onready paired with get_node()

### ISSUE THREAD

**Issue by BlackDragonBE** [godotengine/godot#73164]
### Godot version

4.0 rc1

### System information

Windows 11, GTX 1080Ti, Vulkan

### Issue description

Automplete can't find any variables and methods on custom classes when the nodes are loaded with `@onready`:

simple_rotate.gd:
```gdscript
extends Node2D
class_name SimpleRotate

@export var shouldRotate : bool = true
```

machine.gd:
```gdscript
@onready var wheel1 : SimpleRotate = $Wheel

func start_motor():
	wheel1.sho... # Doesn't autocomplete, it can't find shouldRotate 
```

If I add another cast like below, autocomplete does work:
machine.gd:
```gdscript
@onready var wheel1 : SimpleRotate = $Wheel as SimpleRotate

func start_motor():
	wheel1.shouldRotate = true # Autocomplete works
```

To make things even weirder, it does work if I make Wheel into a unique name and access it using %:
machine.gd:
```gdscript
@onready var wheel1 : SimpleRotate = $"%Wheel"

func start_motor():
	wheel1.shouldRotate = true # Autocomplete works
```

### Steps to reproduce

- Create a script with a class_name
- Add that script to a node
- Create another script referencing the node with the type of the script
- Try to let automcomplete find any methods or variables on the script with the class_name
- Notice that it fails

### Minimal reproduction project

N/A

**Comment by BlackDragonBE** [comment]
This is still an issue in rc4. It might seem like a tiny problem, but it's very confusing for GDScript beginners. It's even referenced in the very video that motivated me to switch from Unity to Godot: https://youtu.be/YVjT0OeE4P0?list=PLRTDZBJAg1Np16EGdovtdqAbYd1eh8BN2&t=668

**Comment by notKamui** [comment]
While it is a "tiny" problem, it is still quite frustrating, especially when you work in a team, and you make an effort of documenting your neatly typed API, and you end up with none of its benefits.

As of now, the workaround with the cast still works with the walrus operator (no need to specify the type twice)

```gdscript
@onready var wheel1 := $Wheel as SimpleRotate
```

Maybe this is a hint towards the origin of the bug

**Comment by saierXP** [comment]
Maybe we can close this and discuss it in this [issue](https://github.com/godotengine/godot/issues/73638)

**Comment by lamdevhs** [comment]
I have the same issue, but unique names ('%') don't solve the problem in my case:
```@onready var foo: ButtonSubClass = %Foo```
The autocompletion does not complete anything from ButtonSubClass, only from Button. The walrus trick from @notKamui does provide a temporary fix to the issue though, so that's nice!

My version: v4.1.1.stable.arch_linux
