### ISSUE TITLE
get_global_mouse_position() is shifted in the viewport's transform

### ISSUE THREAD

**Issue by JohnEmhoff** [godotengine/godot#73160]
### Godot version

4.0rc1

### System information

Linux

### Issue description

This is a copy of https://github.com/godotengine/godot/issues/30215, as it seems it was incorrectly closed (or there's a regression).

When I use the get_global_mouse_position() in a normal scene, the coordinates are right, but when I use in a scene that uses a viewport container to render pixelated the scene, the coordinates are incorrect.

### Steps to reproduce

Add a viewport node with a non-1:1 scale. Note that `get_global_mouse_position` returns the wrong coordinates.

### Minimal reproduction project

[scale-bug-4rc1.zip](https://github.com/godotengine/godot/files/10716275/scale-bug-4rc1.zip)

**Comment by Sauermann** [comment]
> `# mouse = to_local(mouse)  # no effect?`

In your MRP, it is correct, that `to_local` has no effect in this case, because `TileMap` has a default transform.
`to_local` is not affected by the viewport.

The `SubViewport`-setup in your MRP looks complicated. Doesn't look like a trivial issue to investigate.

**Comment by Sauermann** [comment]
Somehow you managed to bring the SubViewport into an inconsistent state in the editor.

`SubViewportConteiner.stretch == true` implies that `SubViewport.size` is set automatically by the `SubViewportContainer`.
However in your MRP you have
- `SubViewportConteiner.size == (2560x1440)`
- `SubViewportConteiner.stretch == true`
- `SubViewport.size == (640x360)`

This will cause problems, as described in #66906, which fixed a different way to create an inconsistent state.

The following topics might also be interesting for you.

related to #61301
related to godotengine/godot-proposals#6221
related to godotengine/godot-proposals#1666

Currently the method that brings you as close as possible to your wanted functionality is to set in your MRP `SubViewportContainer.stretch_shrink = 4`
![image](https://user-images.githubusercontent.com/6299227/218338741-e68c8e86-6cf1-44a4-aef0-4ed1ca6caabf.png)
This will automatically scale the `SubViewport` to the size of 1/4 of the `SubViewportContainer`.

If this doesn't fill your requirements, I would like to suggest, that you describe your needed functionality in the form of a proposal in https://github.com/godotengine/godot-proposals

**Comment by JohnEmhoff** [comment]
Thanks, I'll mess around and see if that fixes the mouse coordinates. This particular project was created in version 3.something then migrated to 4 which might explain how it got into such a weird state.
