### ISSUE TITLE
The AnimatedSprite node could have the signal finished ( ) 

### ISSUE THREAD

**Issue by samuale** [godotengine/godot#7316]
It would be possible for the AnimatedSprite node to have the signal finished ( )

And so it would be easier to handle certain actions from From the code

**Comment by Geequlim** [comment]
How about animations with loop?

**Comment by bojidar-bg** [comment]
@Geequlim I guess it should work the same as AnimationPlayer (i.e. `finished` on each completed iteration AFAIK)
