### ISSUE TITLE
@export_range "radians" does not work as documentation suggests

### ISSUE THREAD

**Issue by quinnyo** [godotengine/godot#73170]
### Godot version

v4.0.rc1, 4.1

### System information

Arch Linux

### Issue description

When using the `@export_range` annotation with the `"radians"` hint, the editor converts the property's value to and from degrees but it uses the range extents (and increment) without any conversion.

To illustrate this, consider the example from the docs: `@export_range(-3.14, 3.14, 0.001, "radians") var angle_radians`. The editor will clamp the value to `[-3.14..3.14] degrees`.

I don't think this behaviour is incorrect, strictly speaking. But it is in conflict with the documentation.

### Steps to reproduce

Add the example properties to a script:
```
extends Node
@export_range(-3.14, 3.14, 0.001, "radians") var angle_radians = PI
@export_range(-180, 180, 0.1, "radians") var angle_radians_but_range_degrees = PI
```
Edit the properties in the inspector and note that the values are clamped to the range extents as written, but the value is converted to degrees.

### Minimal reproduction project

N/A

**Comment by YuriSizov** [comment]
This is not an issue with documentation, docs and your assumptions are correct.

**Comment by YuriSizov** [comment]
Through a discussion on RocketChat, there is a suggestion to rename the hint from `radians` to `radians_as_degrees` to make it clearer in code that the property is going to be represented as degrees and that the hinted range is also in degrees. Then the documentation fix proposed twice already would be possible.

We can keep support for `radians`, just avoid using it and advertising it in the documentation. So it won't be compatibility breaking.

**Comment by aaronfranke** [comment]
I prefer the current name. Marking a property as "radians" means "this property uses radians as its unit", which is an independent thing from how the editor decides to convert the unit. For example, if we ever add an editor setting to display radians as radians, the property hint "radians_as_degrees" makes no sense.

**Comment by AThousandShips** [comment]
The current wording makes no sense either *without* a setting to control it, is there any actual work or interest in that?

I don't see the value in having radians edited in the inspector, it's not a convenient unit to use for editing like this, degrees works much better

**Comment by aaronfranke** [comment]
I think the proper solution is to have `@export_range(-3.14, 3.14, 0.001, "radians")` treat 3.14 as also in radians (so about 179.9 degrees on the UI). That way the code only works with radians, independent from the UI.

**Comment by AThousandShips** [comment]
That's not convenient, and breaks compatibility

**Comment by AThousandShips** [comment]
Changing the current behaviour isn't an option here for many reasons IMO

**Comment by quinnyo** [comment]
I finally ~~didn't ADHD too hard or too soft~~ collected my thoughts on this -- my reasoning for why the current behaviour is correct.

An export hint is (logically, semantically, conceptually) concerned with *the way the property is exported* -- it's for telling the editor how you would like the property presented and how it should be interacted with.
I'm stating the obvious to point out what the export hint is not:
An export hint is not a constraint on a variable.

Specifying user-facing values in user-facing units makes sense, regardless of *which units* are in use at either end. The `"radians[ to degrees]"` unit conversion is irrelevant.


> I think the proper solution is to have `@export_range(-3.14, 3.14, 0.001, "radians")` treat 3.14 as also in radians (so about 179.9 degrees on the UI). That way the code only works with radians, independent from the UI.

The code *does* work independently of the UI. The export range is for the editor/user, not your code. Then the `"radians"` fairy dust frees your code from the shackles of degrees -- that allows your code to be independent from the UI.

**Comment by aaronfranke** [comment]
Ok, as long as the min/max/step values are in degrees, then I agree `radians_as_degrees` makes more sense. Also I agree with `as` being better than `to`, since the conversion happens in both directions (converting rad to deg when displaying to the UI, converting deg to rad when saving back in the export var).

@quinnyo The point I was making is that the code giving a hint to the UI to display in degrees means that the code itself has some parts knowing about degrees. The range hint's values being in degrees means that the code is in fact not independent from the UI, the `@export_range` code gives instructions on how to convert for the UI. But if we are fine with the code knowing about degrees, then this is fine.

**Comment by quinnyo** [comment]
@aaronfranke I understand. I just think that:
- export hints are for configuring the editor (the boundary has already been violated)
- using the editor's units is a further violation of the boundary, but a reasonable one
- you can view export hints as separate to your code, the violation is entirely contained within the brackets

And I thought that explaining that might be of use.
