### ISSUE TITLE
unable to initialize vulkan video driver 

### ISSUE THREAD

**Issue by raoufowo** [godotengine/godot#73185]
### Godot version

v4.0.rc1.official [8843d9ad3]

### System information

windows 7 ,vulkan

### Issue description

when I tried open softeware i get this error :
Your video card driver seem not to support required vulkan version .
if possible consider updating your video card driver or using the opengl3 driver 
you can enable the opengl3 driver by.............................ETC
I tried put the command --rendering opengl3 it work but when I tried run the scene get the same error 
PS:
when i convert my project from 3.x to 4.x i find my scene have alot of error and sometimes i can't open it for no reason 

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
> I tried put the command --rendering opengl3 it work but when I tried run the scene get the same error

The command line argument is not passed from the editor to the running project, so you need to change the rendering method to **Compatibility** using the drop-down in the top-right corner of the editor.

**Comment by akien-mga** [comment]
You should create a project using the Compatibility renderer:

![image](https://user-images.githubusercontent.com/4701338/218343121-b7df12b2-58a4-49e2-a8c0-91a9b1c008ec.png)

**Comment by raoufowo** [comment]
@akien-mga 
i moved project from godot 3.x that's why didn't know about that but still have problme with opening scene have a big mess inside nothing in the correct place
