### ISSUE TITLE
YSort: Godot 3.5 based on root node vs Godot 4.0 based on Sprite2D

### ISSUE THREAD

**Issue by rnbwsncron** [godotengine/godot#73183]
### Godot version

4.0rc1

### System information

Windows 11, Forward+

### Issue description

![YSortComparison](https://user-images.githubusercontent.com/125223093/218340877-60d93230-27fe-4ab8-aa21-5a4761e4b28f.gif)

In 3.5 the YSorting happens at the origin point of the root node. Whereas in 4.0 the YSorting happens at  the origin of the Sprite regardless of the root node. If there are two sprites (as is the case here, stone fence + blue door), the YSorting will happen at different points for the individual sprites.

### Steps to reproduce

1. Create a StaticBody2D
2. Attach a sprite
3. Create another set as above
4. Put them both in the same Tree (World, Main, ...)
5. Set the Tree to YSort and also both newly created StaticBody
6. Move them around to see where the YSorting happens
7. Repeat in 3.5 to compare

### Minimal reproduction project

[ysort_issue.zip](https://github.com/godotengine/godot/files/10717559/ysort_issue.zip)

**Comment by YuriSizov** [comment]
Please provide an MRP.

**Comment by akien-mga** [comment]
Did you mean to close the issue?

**Comment by rnbwsncron** [comment]
It seems like a non-issue. YSort needs to be enabled on the main tree only and not on individual scenes that are instanced in the tree. Which makes sense if you don't want every individual part of a scene to YSort independently.
