### ISSUE TITLE
Minimizing / Maximizing godot after saving crashes godot

### ISSUE THREAD

**Issue by kicknbrit** [godotengine/godot#73181]
### Godot version

4.0 rc1

### System information

Windows 10

### Issue description

Using the taskbar to min/max the godot window will crash godot if you have saved your game (I use ctrl+s to save my game)

### Steps to reproduce

Create an 3D project. Save it, minimize and maximize the window using the taskbar.

### Minimal reproduction project

N/A

**Comment by kicknbrit** [comment]
I have also testing the window buttons at the top right, using these cause godot to freeze and then crash for me as well

**Comment by kicknbrit** [comment]
Ok so after restarting my computer the problem went away. Should I leave this up?

**Comment by akien-mga** [comment]
This might have been unstable graphics drivers after an update and before a reboot then. (Or drivers got in a failed state for some reason and started misbehaving for the rest of the session.)

**Comment by kicknbrit** [comment]
I see. Thanks for your attention to this problem :)
