### ISSUE TITLE
Option to change the default PascalCase/CamelCase into snake_case when adding Nodes

### ISSUE THREAD

**Issue by Tybobobo** [godotengine/godot#7319]
I am blown away that I can't find an existing issue about this. 
Most people that I know, uses snake_case in all their Godot projects. 
I don't see why we couldn't implement an option to change the PascalCase into snake_case when adding them to the scene :)

**Comment by bojidar-bg** [comment]
Better yet, enforce it as default :wink: https://github.com/KOBUGE-Games/resources/blob/master/STYLE-GUIDE.md#nodes (not to be taken seriously)

**Comment by RayKoopa** [comment]
I guess this can be closed then as with https://github.com/godotengine/godot/pull/7509 being merged?

**Comment by akien-mga** [comment]
Yes :)

You can use "Fixes #7319." in the description of your commit or PR next time, and it will autoclose the mentioned issue once merged :)

**Comment by RayKoopa** [comment]
Good to know... guess I never used GitHub as it should be used :P

**Comment by akien-mga** [comment]
For the reference, fixed in master by a971186c266de2df818a7f3dc063a49b0ad51bd8.
