### ISSUE TITLE
4.0.rc1, inc-decrement buttons missing from process priority input box

### ISSUE THREAD

**Issue by duianto** [godotengine/godot#73192]
### Godot version

v4.0.rc1.official [8843d9ad3]

### System information

Windows 10 22H2, Compatibility, Geforce GTX 550 Ti

### Issue description

The inc-decrement buttons are missing from the Process Priority input box.

The issue is observed in: v4.0.rc1.official [8843d9ad3]

![Godot_v4 0-rc1_win64_vzNcfx2YGm](https://user-images.githubusercontent.com/13420573/218346770-cca6f609-48a6-4637-9731-cf631398e2f5.png)

The expected behavior is observed in: v3.5.2.rc2.official [1a2bf3eb4] and v3.5.1.stable.official [6fed1ffa3]

![Godot_v3 5 2-rc2_win64_LYSNq0gjW1](https://user-images.githubusercontent.com/13420573/218346766-c68f1a21-307d-4ddd-b33a-9765a6a46988.png)

### Steps to reproduce

- open the attached project: [issue, inc-decrement buttons missing from process priority input box.zip](https://github.com/godotengine/godot/files/10717722/issue.inc-decrement.buttons.missing.from.process.priority.input.box.zip)

- in the `Inspector` panel, left-click on the `Process` property group to unfold it's properties.
Look at the `Priority` input box.

### Expected
There should be increment and decrement buttons on the right side of the input box.

### Observed
There are no increment and decrement buttons on the right side of the input box.

### v4.0.rc1.official [8843d9ad3]

[issue, inc-decrement buttons missing from process priority input box.zip](https://github.com/godotengine/godot/files/10717722/issue.inc-decrement.buttons.missing.from.process.priority.input.box.zip)

### v3.5.2.rc2.official [1a2bf3eb4] and v3.5.1.stable.official [6fed1ffa3]

[inc-decrement buttons in process priority input box.zip](https://github.com/godotengine/godot/files/10717723/inc-decrement.buttons.in.process.priority.input.box.zip)

**Comment by Zireael07** [comment]
I think priority is no longer an int, so that's why?

**Comment by Rindbee** [comment]
> I think priority is no longer an int, so that's why?

Probably not, this issue first occurred in beta10, there are multiple similar properties affected, such as `AnimatedSprite2D:frame`.

**Comment by Calinou** [comment]
The setting lacks a property hint range: https://github.com/godotengine/godot/blob/8c7b98d4526c6ba66d7f1636abb71ccbe54727c6/scene/main/node.cpp#L3016

**Comment by akien-mga** [comment]
Well the problem is the default value:
```
	bool hide_slider = true;
```

`hide_slider` in `EditorSpinSlider` controls both the actual horizontal slider, and the up/down buttons.

IMO the up/down buttons should always be shown.

**Comment by akien-mga** [comment]
It's a regression from #69797, in `3.x` `EditorPropertyInteger::setup` doesn't set `hide_slider` on the spinbox. CC @TokageItLab

**Comment by TokageItLab** [comment]
I remember that this was done intentionally because it was necessary to hide the button if the slider was not present, since the grabs could not be determined.
