### ISSUE TITLE
Crashes when replace surface material

### ISSUE THREAD

**Issue by marcosbitetti** [godotengine/godot#732]
When I try replace a material for a surface the editor replace it normally.
But after run the the window and debugger crashes! And I have same crashes when i try to reload the scene!

**Comment by akien-mga** [comment]
Since there hasn't been much activity on this issue I'll assume it has been fixed somehow or was an issue with the material used, so archiving. Feel free to reopen if you can still reproduce the issue, and if so please provide an example project that triggers the bug.
