### ISSUE TITLE
VBoxContainer / HBoxContainer / FlowContainer default separation is 1px, but inspector says 0px

### ISSUE THREAD

**Issue by tufduckhotmailcom** [godotengine/godot#73207]
### Godot version

Both 4.0 RC1 and 3.5.1 stable.

### System information

Windows 10

### Issue description

I've noticed that when adding a VBox/HBox/Flow container there is a default 1px separation between the children. But the value under Theme Overrides -> Constants -> Separation in the inspector says 0px. 

![VBox sep](https://user-images.githubusercontent.com/99537319/218407888-fe68462f-d31f-4c04-aee3-41a49748789b.png)

If I change the value in the inspector up to 1, and then back down to 0, then the children moves next to each other, i.e. 0px separation. 

![VBox sep workaround](https://user-images.githubusercontent.com/99537319/218407931-1360c864-f5a8-449f-a081-858b960c6758.png)

At first I thought this was specific to 4.0, but it exists in 3.5 stable as well.

I've also tested this with HBoxContainer and FlowContainers and the issue is there as well.

### Steps to reproduce

1. Make a new scene
2. Add CanvasLayer
3. Add a VBoxContainer as child to CanvasLayer, set some min size value to this VBox
4. Add two PanelContainers as children to VBox. Set min size to these as well, and set different StyleBoxFlat texture colors to them so you can distinct them from each other.
5. Notice the 1px gap between them. There should be no gap, since the inspector value says 0.
6. Adjust the VBoxContainer separation value up to 1 and back to zero and notice the behavior.

### Minimal reproduction project

Not needed. It's really simple to reproduce

**Comment by YuriSizov** [comment]
This field doesn't show you the current value. It's either empty and shows you the default value for this type of property, or it's overridden and it shows your override. There is a proposal for that https://github.com/godotengine/godot-proposals/issues/4439.
