### ISSUE TITLE
Directory - A way to get_next() without getting . or ..

### ISSUE THREAD

**Issue by Tybobobo** [godotengine/godot#7320]
Every single time I work with directory, I never want to use . or .. that appears during get_next(). 
If there was a way to disable it all-together, we would save time and work. :)

Would anyone mind adding a Directory function that allows us to enable/disable . .. from appearing during get_next()?

Ex.:
```
var dir = Directory.new()
dir.ignore_dots(true)
```

**Comment by bojidar-bg** [comment]
Should this method also disable unix-hidden files and directories? (e.g. `.fscache`, `.git/`...)

**Comment by Tybobobo** [comment]
Good question. 
Perhaps we could use `dir.ignore_hidden(true)` that would cover those as well. :)

**Comment by puppetmaster-** [comment]
Does this https://github.com/godotengine/godot/issues/7158 (File browser "up to folder" duplicate icons) also belong together?

**Comment by bojidar-bg** [comment]
@puppetmaster- No.

The other issue is for the FileDialog/EditorFileDialog node, while this is for the Directory class.

**Comment by RayKoopa** [comment]
I'd rather prefer to extend `dir.list_dir_begin()` with optional parameters.
Like `dir.list_dir_begin(ignore_internal, ignore_hidden)`
I'm not a UNIX expert. Are dotted file system entries the only way to "hide" them? For a Windows user, this would be really confusing.

**Comment by bojidar-bg** [comment]
@RayKoopa Sounds cool, though `ignore_internal` sounds really confusing to me (and I'm a linux user even).
Also, `ignore_hidden` should ignore `.<stuff>` as well as `<stuff>~` on linux, mind it. On windows, I don't remember how hidden files were made, so can't really help there :smiley:.

**Comment by RayKoopa** [comment]
I was about to name them `skip_hidden` and `skip_navigational` now... is that better? I wonder if . and .. have a real term to describe them both...

**Comment by akien-mga** [comment]
Fixed by #7563.
