### ISSUE TITLE
Object.new() can't be used (but it works on any Object-derived class like Node or RefCounted)

### ISSUE THREAD

**Issue by jinyangcruise** [godotengine/godot#73213]
### Godot version

v4.0.rc1.official.8843d9ad3

### System information

Windows 10, Forward+, NVIDIA GeForce GTX 860M

### Issue description

cannot use Object.new()

![image](https://user-images.githubusercontent.com/42859362/218438759-d7a593a5-5265-4501-8528-82f5a5de6bdc.png)

### Steps to reproduce

NA

### Minimal reproduction project

NA

**Comment by akien-mga** [comment]
This was supposed to be fixed by #41516 but indeed I still see this error.

**Comment by JMidd91** [comment]
Hi, as this is still a bug, what would be a good workaround for now? would Node.new() be suitable? just because I am in the middle of converting my project to 4.0 and have got stuck on this bug! many thanks.

**Comment by jinyangcruise** [comment]
workaround: use a subclass which extends Object, like RefCounted, or an empty class which extends Object:

MyObject.gd:
```
extends Object
class_name MyObject
```

it depends whether you should use Node:
https://docs.godotengine.org/en/latest/tutorials/best_practices/node_alternatives.html

**Comment by JMidd91** [comment]
Sweet that works for me, thanks!

**Comment by santouits** [comment]
I' m not sure what is the correct fix here. We can fix it here by not adding the "Object" as a builtin type:
https://github.com/godotengine/godot/blob/db5113de36aa59b3b3ffcd3399d06f4b76476df8/modules/gdscript/gdscript_parser.cpp#L52-L57

But then I saw that this code uses the above function:
https://github.com/godotengine/godot/blob/db5113de36aa59b3b3ffcd3399d06f4b76476df8/modules/gdscript/gdscript_analyzer.cpp#L2779-L2782

Do we want to use ``Object()`` as a constructor which I don't think works correct anyway, it returns an object that prints ``<Object#null>``. I can remove that code too.

We can also fix it in other ways but it seems more clean this way.

**Comment by adamscott** [comment]
@dalexeev's PR didn't make it to 4.1's release window, but it will certainly be cherrypicked for 4.1.x versions.
