### ISSUE TITLE
Godot marks `property_can_revert` and `property_get_revert` as error

### ISSUE THREAD

**Issue by theraot** [godotengine/godot#73210]
### Godot version

v4.0.rc1.official [8843d9ad3]

### System information

Windows 10

### Issue description

Declaring `property_can_revert` or `property_get_revert` results in the error:

> Parse Error: The method "property_get_revert" overrides a method from native class "Object". This won't be called by the engine and may not work as expected. (Warning treated as error.)

Although these methods worked in prior versions and should work given that Godot calls them dynamically:

https://github.com/godotengine/godot/blob/8f0208af6509b26d6eaccd68f1d7fb03b8413ef4/editor/editor_inspector.cpp#L452-L454

### Steps to reproduce

Create a script and declare either the function `property_can_revert` or `property_get_revert`.

### Minimal reproduction project

[proprevert.zip](https://github.com/godotengine/godot/files/10720980/proprevert.zip)

**Comment by theraot** [comment]
Nope, Godot does not call then dynamically anymore, unfortunately. That means the change is by design. We need an alternative.

**Comment by akien-mga** [comment]
It's `_property_can_revert` and `_property_get_revert` with an underscore prefix in 4.0, like all virtual methods. See the `Object` docs.

**Comment by YuriSizov** [comment]
The code you linked is also not from the `master` branch. Methods are no longer called this way, they are proper multilevel calls, and your implementation should be through virtual counterparts, as mentioned above.
