### ISSUE TITLE
Blend importer doesn't import "empty" as collision shape

### ISSUE THREAD

**Issue by walikour** [godotengine/godot#73221]
### Godot version

4.0 Release candidate 1

### System information

Windows 10 i5 4570 gtx 1050 ti

### Issue description

![image](https://user-images.githubusercontent.com/57159438/218466524-dbbc0a00-2c2c-4c3b-a70e-4cc5bd6c05b0.png)
When importing blend file to godot with the native importer empty are not imported as collision shape while object with a mesh and  -col / -colonly are imported
![image](https://user-images.githubusercontent.com/57159438/218467046-01b21881-aace-4567-99c4-fcf56f5e408f.png)
![image](https://user-images.githubusercontent.com/57159438/218467103-e5d7b96c-c468-4bfc-bddd-8619c36217b8.png)

### Steps to reproduce

Create an object in blender 
parent an sphere empty with -colonly added at the end of the name
save the blend file into your godot project

### Minimal reproduction project

n/a

**Comment by lyuma** [comment]
I don't know if empty objects can be assumed to have a shape, but perhaps it should still create a StaticBody without a child,

**Comment by lyuma** [comment]
I would also keep your eye on this PR: https://github.com/godotengine/godot/pull/69266
If #69266 is merged, it means that Godot could run Blender with an addon to export that GLTF extension and preserve blender physics objects exactly.
