### ISSUE TITLE
Some tooltips in the editor don't show their text content

### ISSUE THREAD

**Issue by Sauermann** [godotengine/godot#73230]
### Godot version

v4.0.rc.custom_build [4a2c2170b]

### System information

Linux X11 Xfce

### Issue description

Some tooltips in the editor appear black without content.

![image](https://user-images.githubusercontent.com/6299227/218492857-7a681cc7-5843-4c14-aa70-33268a0ad86a.png)

Apparently not all tooltips have this problem.
![image](https://user-images.githubusercontent.com/6299227/218493075-22aa9e24-53ae-4106-a38d-ec946cc350df.png)

I would expect, that all tooltips show their content.

Bisecting lead to #72387

### Steps to reproduce

Hover the mouse over CanvasItem-Editor Icons.

### Minimal reproduction project

Happens in the editor

**Comment by RandomShaper** [comment]
Will look into it right now.
