### ISSUE TITLE
[HELP] Godot on Termux

### ISSUE THREAD

**Issue by Maxython** [godotengine/godot#73233]
### Godot version

3.5.1.stable

### System information

Termux (Android 13, aarch64)

### Issue description

Hello, I recently compiled `Godot` on `termux`, but every time I run it I get the following error:
![IMG_20230213_151342_508](https://user-images.githubusercontent.com/60917834/218523079-0def3d89-c4e9-4cb4-bf73-2b7a6af26dc6.jpg)
I tried to fix it myself, but nothing worked for me.

### Steps to reproduce

Compiling godot from this [source](https://github.com/archlinux/svntogit-community/blob/packages/godot/trunk/PKGBUILD).

### Minimal reproduction project

None

**Comment by Maxython** [comment]
> You can't run Godot in non-headless mode on Termux, as Termux does not support 3D acceleration (and support for GUI apps in general is spotty). Godot requires 3D acceleration to run.

Can you explain in detail about "3D Acceleration" in Godot? And also do not underestimate the functionality and capabilities of Termux, I assume that Godot on Termux will have the same features as Godot on regular linux arm distributions (for example: [godot aarch64 in archlinuxarm](https://archlinuxarm.org/packages/aarch64/godot)).

> Out of curiosity, why not use the native Android editor port?

Firstly, what do you mean by "the native Android editor port"? And secondly, why not, I think that Godot will be relevant for users in Termux.

**Comment by Calinou** [comment]
> Can you explain in detail about "3D Acceleration" in Godot? 

Godot is rendered by its own rendering engine, which uses OpenGL ES 3.0 or 2.0 depending on project configuration (in Godot 3.x).


> Firstly, what do you mean by "the native Android editor port"? And secondly, why not, I think that Godot will be relevant for users in Termux.

https://godotengine.org/article/android_godot_editor_play_store_beta_release/

**Comment by Maxython** [comment]
>It may be possible to work around the run-time crash by compiling with the udev=no SCons option, which disables linking against udev (which is used to support controller hotplugging on Linux).

Thanks for the help after that and a few extra tweaks with the fonts, I got it to run in Termux. Here are the screenshots:
![Screenshot_20230214-104628_VNC Viewer](https://user-images.githubusercontent.com/60917834/218685163-2d15d08e-d7c7-4ded-98bb-e8f67be0bd6a.jpg)
![Screenshot_20230214-104810_VNC Viewer](https://user-images.githubusercontent.com/60917834/218685187-5af586fb-6cf7-4a16-ac38-7110414d1202.jpg)
![Screenshot_20230214-104852_VNC Viewer](https://user-images.githubusercontent.com/60917834/218685204-425024a3-162b-4609-ae4b-165595f60246.jpg)
![Screenshot_20230214-110501_VNC Viewer](https://user-images.githubusercontent.com/60917834/218685230-1664bd5b-131e-45be-8697-2f7e0d626dee.jpg)
![Screenshot_20230214-110516_VNC Viewer](https://user-images.githubusercontent.com/60917834/218685244-2a796b95-afcd-41bd-8f02-c7dcfc2ecd0a.jpg)
But to be honest, the loading time of some processes (like loading a project or launching it) leaves much to be desired, but it's still cool. Now I'll probably try to optimize it.

PS: apparently "3D acceleration" works in Termux, since I no longer see any other reason why my tablet gets quite hot /j

**Comment by Calinou** [comment]
> Thanks for the help after that and a few extra tweaks with the fonts, I got it to run in Termux. Here are the screenshots:

What tweaks did you perform to fonts?

**Comment by Maxython** [comment]
> What tweaks did you perform to fonts?

There was an error that the font format was not defined (https://github.com/godotengine/godot/blob/3.5-stable/scene/resources/dynamic_font.cpp#L178), the problem was solved in the same way as with `udev` but this time with `freetype`.

Also, I recently tested `exporting` godot projects for linux and for android. **Bottom line:** for linux, the export was successful, but I was unable to run the program because it is configured for `glibc-x86_64` (ideal combination for `bionic-aarch64`); for android, I had to configure the sdk, but in the end, the export was successful and the program starts.
**Export result for Android:**
![IMG_20230214_234124_535](https://user-images.githubusercontent.com/60917834/218862604-256b2dff-6c16-457b-93db-a55c4e0c121f.jpg)
![IMG_20230214_234124_096](https://user-images.githubusercontent.com/60917834/218862610-ef0d25dc-a1a2-4c8e-83af-0c2899936704.jpg)
![IMG_20230214_234124_629](https://user-images.githubusercontent.com/60917834/218862613-f7bc8662-f5df-4e42-989f-fd0454210e5d.jpg)

**Comment by Maxython** [comment]
One question: what is the difference between `x11` platform and `server` platform?

**Comment by Calinou** [comment]
> One question: what is the difference between `x11` platform and `server` platform?

`x11` is graphical, server is a headless platform which doesn't require `x11` to run. In 4.0, this distinction was removed (`x11` is now `linuxbsd`) and any binary can be run in headless mode by passing the `--headless` command line argument.

**Comment by Maxython** [comment]
That is, godot with `headless` is godot in a web browser (something similar to [code-server](https://github.com/coder/code-server))?

**Comment by Zireael07** [comment]
@Maxython: No, headless has nothing to do with web browsers.

**Comment by Maxython** [comment]
> @Maxython: No, headless has nothing to do with web browsers.

Got it, thanks for the explanation.

PS: I asked because I saw the [godot web editor](https://editor.godotengine.org/releases/latest/) and thought that godot supports a local web editor. And my guess is that godot via local web editor might be faster than godot via vnc (x11).

**Comment by Zireael07** [comment]
@Maxython No clue what you mean by 'local web editor'

**Comment by Maxython** [comment]
> @Maxython No clue what you mean by 'local web editor'

By **local web editor** I mean **godot web editor** but which is running on a local (your) device and which needs a browser to work with but with a link like `localhost:0`.

**Comment by Zireael07** [comment]
cc @Faless then

**Comment by akien-mga** [comment]
Let's try to keep things focused here. This is an issue tracker for bug reports, not a forum for user support.

Just to be clear, on an Android or AOSP-based phone, you can use:
- Native Android editor https://play.google.com/store/apps/details?id=org.godotengine.editor.v3
- Web editor: https://editor.godotengine.org/
- And apparently through Termux a native Linux build, with caveats, but this is not a supported platform. The crashes in libudev on Termux show that there are compatibility issues with the expected behavior for Linux binaries on desktop Linux or embedded devices like Raspberry Pi. Improvements to increase compatibility are welcome but this is not a priority, nor considered a bug.

**Comment by Maxython** [comment]
> Let's try to keep things focused here. This is an issue tracker for bug reports, not a forum for user support.
> 
> Just to be clear, on an Android or AOSP-based devices, you can use:
> 
> * Native Android editor https://play.google.com/store/apps/details?id=org.godotengine.editor.v3
> * Web editor: https://editor.godotengine.org/
> * And apparently through Termux a native Linux build, with caveats, but this is not a supported platform. The crashes in libudev on Termux show that there are compatibility issues with the expected behavior for Linux binaries on desktop Linux or embedded devices like Raspberry Pi. Improvements to increase compatibility are welcome but this is not a priority, nor considered a bug.

Ok, I understand you.  Further support for the godot package in Termux is up to us (Termux developers).

Thanks again for your help.

**Comment by Maxython** [comment]
Godot is now available on termux.
