### ISSUE TITLE
File System panel hierarchy displays incorrectly after rename/move.

### ISSUE THREAD

**Issue by tmathews** [godotengine/godot#7323]
**Operating system or device - Godot version:**

Windows 10
Godot 2.1.1

**Issue description** (what happened, and what was expected):
I rename/move a script to a folder and afterwards the file system panel is displaying the wrong hierarchy. I noticed this also happens after importing a scene. There is probably the same problem going on in many places.

I expect the hierarchy to be displayed correctly. I'd also expect there to be a refresh button for the panel if resources are added externally.

**Steps to reproduce:**
Rename/move an object in the file system to a sub folder.

**Comment by bojidar-bg** [comment]
Duplicate of #3662?

**Comment by tmathews** [comment]
Looks like the same issue and I have been able to reproduce it using different methods.
