### ISSUE TITLE
Random out-of-bounds rects in keep-optimal-aspect-ratio in GL Compatibility

### ISSUE THREAD

**Issue by hydroper** [godotengine/godot#73246]
### Godot version

4.0.rc2

### System information

Windows 11, gl_compatibility

### Issue description

![image](https://user-images.githubusercontent.com/110610266/218567361-580c4728-4911-464e-8d38-3f6752a3acd2.png)

I've confirmed this bug does not happen in `forward_plus` renderer.

### Steps to reproduce

I did this in my project:

- Display > Window > Stretch > Mode = viewport
- Display > Window > Stretch > Aspect = keep
- Display > Window > Stretch > Scale = 1
- Main Scene: A `Node2D`

However, when I create a new project I don't reproduce the problem, so please look at the minimal reproduction project, which is my project still in development (pretty short).

### Minimal reproduction project

[godot_optimal_ratio_demo](https://github.com/hydroper/godot_optimal_ratio_demo)

**Comment by hydroper** [comment]
It works perfectly in `forward_plus` renderer. The out-of-bounds area is rendered as black.

![image](https://user-images.githubusercontent.com/110610266/218761814-ae036976-8b7f-459f-90be-69c5dbadc508.png)

**Comment by hydroper** [comment]
Tried in 4.0.rc2 now and same issue.

**Comment by clayjohn** [comment]
Duplicate of https://github.com/godotengine/godot/issues/71799 closing this so we can track the issue in one place
