### ISSUE TITLE
Comment section for official Godot api, tutorial and other part website?

### ISSUE THREAD

**Issue by Qws** [godotengine/godot#7324]
I don't know if this is the right place but... I find the comment section beneath PHP api/documentation very useful. Can there be something equal for Godot documentation where people can make comments, reply, upvote, downvote comments about specific api, tutorials that's on the official website.

Sorry if this is not the right place, but I think this is the only way to get attention of Godoy developers.

**Comment by ClikCode** [comment]
Like a discussions tab in wikipedia for the documents
