### ISSUE TITLE
Random angle in particle seems to be re-randomized somewhere in particle life

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#73245]
### Godot version

b7723a01d957e6492a3f20bce8a47d3559afe5c5 <- after RC1

### System information

Fedora, RX 590

### Issue description

Particles random angles seem to flicker, sometimes.

https://user-images.githubusercontent.com/7917475/218566882-60e552ec-5284-46bd-ac6c-45e6e1dc3d98.mp4

### Steps to reproduce

I didn't find yet a way to repro reliably. But definitely random angle is the first step

### Minimal reproduction project

See above

**Comment by clayjohn** [comment]
Closing as duplicate of https://github.com/godotengine/godot/issues/49767
