### ISSUE TITLE
.ogg sample support

### ISSUE THREAD

**Issue by Duskitty** [godotengine/godot#7325]
So the game im working on i have most of the sounds as .ogg files, and they arent too too long, but i'd like to keep the smaller file size when using them, would it be possible to add support in sample players for .ogg files?

**Comment by bojidar-bg** [comment]
If they are going to be converted to `.smp` anyway, why bother? The idea behind using `.wav` is that wavs are not lossily compressed, and therefore have no artefacts in them.

**Comment by reduz** [comment]
Godot uses IMA-ADPCM compression for sound effects, using .ogg files in
sample players means a very inefficient use of CPU. Best you can do is to
either use .wav files, or import the audio as .smp

**Comment by freemanfromgodotengine** [comment]
@Duskitty I would convert sounds to mono, 16-bit, 44100 Hz sample resolution wav files (if they are sound effects and your game is a 2d game). And if you really need more space, I would even go with 22050 Hz sample rate. 
With music I would stay with ogg format and use the streamplayer.

**Comment by akien-mga** [comment]
As per the above I guess this is a wontfix.
