### ISSUE TITLE
Editor won't reload scripts on external change

### ISSUE THREAD

**Issue by fisheye36** [godotengine/godot#73260]
### Godot version

v4.0.rc1.official [8843d9ad3]

### System information

Windows 10

### Issue description

I have the following option selected: `text_editor/behavior/files/auto_reload_scripts_on_external_change`, but when editing and saving the script file in VSCode, the internal Editor doesn't seem to pick up the change.

### Steps to reproduce

Create a script, open it in internal editor, then modify it in external editor (I only tested VSCode), and the internal editor won't reload the new script.

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
Duplicate of #72825
