### ISSUE TITLE
Set Y Sort Enabled On brake Highlight Selected TileMap Layer

### ISSUE THREAD

**Issue by sgervais333** [godotengine/godot#73266]
### Godot version

4.0rc1

### System information

Windows 11, Vulkan API 1.3.224 - Vulkan NVIDIA GeForce RTX 3080 Ti

### Issue description

When I change de Y Sort Enabled On/Off. The Highlight seems to brake:

![Screencapture](https://user-images.githubusercontent.com/6784639/218634052-3b6181dc-d24d-494a-97be-88918b738809.gif)

### Steps to reproduce

1. Make a simple TileMap with a TileSet
2. Set 2 Layers
3. Set the CanvasItem -> Ordering Y Sort Enabled -> On
4. On/Off Y Sort Enabled

### Minimal reproduction project

[Minimal.zip](https://github.com/godotengine/godot/files/10728595/Minimal.zip)

**Comment by Proggle** [comment]
I suspect this is related to this more-general bug
https://github.com/godotengine/godot/issues/63994

**Comment by Loufe** [comment]
I can confirm this issue is occurring with my editor, 4.0.2. Follows enabling Y-sort.
