### ISSUE TITLE
Line disappears when you open the color picker from the context menu in the code editor

### ISSUE THREAD

**Issue by el-falso** [godotengine/godot#73279]
### Godot version

4.0.rc1

### System information

Windows 11, Forward+

### Issue description

When you right click the Color class in the code editor you can bring up the color picker to easily select the color you want, eg. when tweening a color. When you define a color in tween_property with Color("red") it works as intended, but when you use Color.RED for example and open the color picker from the context menu, it deletes the whole line, after choosing a color.

![bug](https://user-images.githubusercontent.com/5958083/218727556-40c6c957-0445-4550-83a5-3d3fdf8a018b.gif)

This is the same in Godot 3.5

### Steps to reproduce

``` python
extends Node2D

@onready var sprite_2d: Sprite2D = $Sprite2D


func _ready() -> void:
	var color := Color.RED # You can't select the color picker from the context menu
	var color1 := Color("red") #You can select the color picker from the context menu


func _process(delta: float) -> void:
	
	# Doesn't work, line get's deleted
	# You can select the color picker from the context menu
	var tween := get_tree().create_tween()
	tween.tween_property(sprite_2d, "modulate", Color.RED, 1)
	
	
	# Works
	# You can select the color picker from the context menu
	var tween1 := get_tree().create_tween()
	tween1.tween_property(sprite_2d, "modulate", Color("red"), 1)
```

### Minimal reproduction project

[ColorPickerBug.zip](https://github.com/godotengine/godot/files/10731968/ColorPickerBug.zip)

**Comment by YuriSizov** [comment]
Probably something to do with detecting identifier boundaries?
cc @Paulb23 @aXu-AP

**Comment by el-falso** [comment]
Just tested Godot 4 RC2, there #63907 fixed the issue it seems.
