### ISSUE TITLE
Android "Don't keep activities" freezes editor after exiting running project

### ISSUE THREAD

**Issue by lawnjelly** [godotengine/godot#73272]
### Godot version

3.6 beta (current version from play store) 42083f3a6

### System information

Galaxy Tab S6 Lite, Android version 12, One UI version 4.1

### Issue description

As I have _developer options_ enabled on my tablet, by chance I had the "Don't keep activities - destroy every activity as soon as the user leaves it" option switched on.

The editor would run, and I could press play to debug the app, but when I press the back button, I get a black screen and nothing seems to be happening (until I close the editor using the OS).

If I turn off the "Don't keep activities" it correctly exits back to the editor after pressing back on the running project.

### Steps to reproduce

As above, load e.g. Dodge the creeps, run it, press back.

### Minimal reproduction project

N/A.

**Comment by m4gr3d** [comment]
This is expected behavior given the Android editor uses multiple activities to replicate the experience on Android devices; preventing those activities from running in the background breaks the functionality.

I'm updating the Android editor documentation to reflect this issue.
