### ISSUE TITLE
Parser error with lambda assignment after if statement

### ISSUE THREAD

**Issue by Gnumaru** [godotengine/godot#73273]
### Godot version

4.0.rc1

### System information

windows 10

### Issue description

When assigning a lambda to a variable right after an if statement, the parser seems to understand that a ternary expression is happening when in fact it is not.

![image](https://user-images.githubusercontent.com/5783414/218691792-a27619cd-f17c-4d1e-9121-197c22aeec09.png)

### Steps to reproduce

Put the code bellow on a script on an empty project
```gdscript
func test():
	var v
	if true: v = (func(): test())
	if true: v = (func(): test())
	if true: v = (func(): test())

	if true: v = func(): test()
	if true: v = func(): test()
```

### Minimal reproduction project

N/A

**Comment by kinami-imai** [comment]
I managed to reproduce the issue with the following code:
```
var v
v=func():v=1
if true: v=1
```
It appears this gets parsed as the incomplete ternary `v=func:v=1 if true` rather than the correct `v=func():v=1` and `if true: v=1`. I suspect this is because ternary expressions have higher priority, and lambdas get special treatment, but I have not yet been able to find the cause, but I think I'm getting somewhere.

**Comment by kinami-imai** [comment]
Okay, I think I found the issue. Normally, when parsing an assignment, the parser will properly separate the next expression on a new line.

When a lambda expression is passed, it consumes all the new lines before they can be passed to the parent expression, which means the assignment misses any new lines after the line, so the line becomes `v=func():v=1 if true: v=1`, which is then identified as an invalid ternary.

I'll see if I can fix the issue in code.

**Comment by WolfgangSenff** [comment]
Just adding support for this - ran into it just now as well. Very strange trying to debug what's happening from the editor itself. :P

**Comment by kinami-imai** [comment]
Interesting. It appears any token with a higher precedence than `NONE` triggers this issue. For example:
```
v=func():v=1
in v
```
Compiles, when it should not.

Also notable, is some programs appear to be valid even when there is no new line. For example `v=func():v=1 print(1)` compiles and prints 1 (without the lambda being called)! So assigning lambdas has always worked sort of by accident.

Also, multi-line lambdas break too, this produces an error:
```
v=func():
  v=1
if true: v=1
```

**Comment by WolfgangSenff** [comment]
Verifying above: the latter case is exactly what I ran into, with of course slightly more code for my usecases. :)
