### ISSUE TITLE
Trying to invoke un-existing static methods does not yield a parser error

### ISSUE THREAD

**Issue by Gnumaru** [godotengine/godot#73283]
### Godot version

4.0.rc1

### System information

windows 10

### Issue description

Trying to invoke un-existing static methods does not yield a parser error. Only trying to access other static members (consts and enums) does.

![image](https://user-images.githubusercontent.com/5783414/218737374-2eff3a6f-f4a7-4249-9d4e-de8b90e2734b.png)

### Steps to reproduce

In any project, put the code bellow on any script. It will yield a parser error only at ```var a = MyClass.qwer``` but not at ```MyClass.myUnexistingMethod()```

```gdscript
class MyClass: pass
func test():
	MyClass.myUnexistingMethod()
	var a = MyClass.qwer

```

### Minimal reproduction project

N/A

**Comment by adamscott** [comment]
@dalexeev's PR didn't make it to 4.1's release window, but it will certainly be cherrypicked for 4.1.x versions.
