### ISSUE TITLE
High refresh rate monitors jitter problem

### ISSUE THREAD

**Issue by Cube-Logic** [godotengine/godot#73288]
### Godot version

4.0 rc1

### System information

Windows 11, RTX 4070 Ti, Forward+

### Issue description

I'm using a 144 Hz Ultrawide monitor and when moving the camera there's a blurry trail behind the player
I investigated the issue and found the problem, **Engine.physics_ticks_per_second** was 60 while my **Engine.get_frames_per_second()** was 144
Is there a way to sync these two without the need to set them individually or use the process method instead of physics_process?

### Steps to reproduce

Any godot game shown on a 144 hz monitor
![Godot_4 0_OurcYSIr4X](https://user-images.githubusercontent.com/85768334/218775086-00233f08-873c-4d6e-bb2b-6e162cb9b5e6.png)

### Minimal reproduction project

Any godot game shown on a 144 hz monitor

**Comment by YuriSizov** [comment]
Those two are not supposed to be in sync (and your framerate will not match your refresh rate if you disable VSync). Your framerate is typically larger, but it fluctuates, while the physics rate is slower, but fixed to a constant pace. Change it can negatively affect users with different setups, so should be done with caution.

In any case, physics rate shouldn't have anything to do with ghosting,

**Comment by Calinou** [comment]
This is expected behavior as Godot currently lacks physics interpolation in 4.0. [Physics interpolation](https://docs.godotengine.org/en/stable/tutorials/physics/interpolation/index.html) is the best way to fix this issue, but it's only available in 3.x and in 3D currently. In 4.0, you can use the [`4.x` branch of smoothing-addon](https://github.com/lawnjelly/smoothing-addon/tree/4.x) as an alternative (which also works in 2D). The `3.x` branch of that add-on also supports 2D.

**Comment by Cube-Logic** [comment]
Thanks for your code snippet and the extension, really helped!
But also, are you planning on integrating the plugin with godot?
I'm asking that because I thought my monitor or my graphics card caused the problem, spent half a week debugging this to understand the root of the problem, I don't want others to feel the same frustration as I felt :)

**Comment by Calinou** [comment]
>  But also, are you planning on integrating the plugin with godot?

Physics interpolation will be added in core in a future 4.x release, but it will use a different approach.
