### ISSUE TITLE
'View', 'Share', and 'Menu' Xbox Wireless Controller buttons do not work on iOS

### ISSUE THREAD

**Issue by BZ1234567890** [godotengine/godot#73305]
### Godot version

3.5.1 stable

### System information

iOS 15.6.1, iPad Mini, Xbox Wireless Controller

### Issue description

When pressing the 'View', 'Share', or 'Menu' button on the Xbox Wireless Controller, the following error is displayed in the Xcode debug output when running a Godot project on iOS:

`2023-02-14 20:35:59.159876+0100 insync[13177:908420] [EventDispatcher] Found no UIEvent for backing event of type: 3; contextId: 0x86A42F3; Event will not be dispatched`

No input events are fired in Godot.

'View', 'Share', and 'Menu' are buttons no. 3, 5, and 6 from the following article: https://support.xbox.com/en-US/help/hardware-network/controller/get-to-know-your-xbox-series-x-s-controller (see "The face of the controller" section).

The 'Share' button is not that problematic, as it is handled by the iOS to take a screenshot. Having support for the 'Menu' button (which works as expected on macOS) would be nice, though.

### Steps to reproduce

1. Create a new Godot project.
2. Export Xcode project.
3. Open the project in Xcode.
4. Add "Game Controllers" capability to the project, and check the "Extended gamepad" option.
5. Run on an iOS 15.6.1 device and press 'View', 'Share', or 'Menu' button on the Xbox controller.

### Minimal reproduction project

N/A

**Comment by BZ1234567890** [comment]
I think I have figured out how to fix this for the 3.5 branch.

It seems that there are no handlers for the **gamepad.buttonOptions** (the 'View' Xbox button) and the **gamepad.buttonMenu** (the 'Menu' Xbox button) gamepad buttons in the `- (void)setControllerInputHandler:(GCController *)controller` function in **platform/iphone/joypad_iphone.mm**.

The behaviour of the 'View' and 'Menu' buttons in iOS becomes consistent with the macOS behaviour when adding the following piece of code at the end of the said function:

```
			if (@available(iOS 13, *)) {
				if (element == gamepad.buttonOptions) {
					OSIPhone::get_singleton()->joy_button(joy_id, JOY_BUTTON_10,
							gamepad.buttonOptions.isPressed);
				} else if (element == gamepad.buttonMenu) {
					OSIPhone::get_singleton()->joy_button(joy_id, JOY_BUTTON_11,
							gamepad.buttonMenu.isPressed);
				}
			}
```

Since these two buttons were introduced in iOS 13, the code is enclosed in `if (@available(iOS 13, *)) {` block.

The master branch seems to have different constants (cannot find an equivalent for JOY_BUTTON_10 and 11), also there are other joy buttons already mapped to 10 and 11. So, this fix likely isn't appropriate for the master branch.

Should I do a pull request and push my "fix" for the 3.5 branch for now, and maybe someone more knowledgeable than me can port this to the master branch?

**Comment by Calinou** [comment]
> Should I do a pull request and push my "fix" for the 3.5 branch for now, and maybe someone more knowledgeable than me can port this to the master branch?

Pull requests should be opened against the `master` branch instead of `3.x` or `3.5`. This is because feature development occurs in the `master` branch. We can then cherry-pick specific PRs to the `3.x` branch then `3.5` if they don't break backwards compatibility.

**Comment by BZ1234567890** [comment]
@akien-mga: Would you like me to do the PR for the 3.X and 3.5 branches too?

**Comment by akien-mga** [comment]
Feel free to make one for 3.x. For the 3.5 branch well just cherrypick the 3.x commit.
