### ISSUE TITLE
FBX2glTF dialog appears in a loop after clicking Cancel

### ISSUE THREAD

**Issue by gfnekro** [godotengine/godot#73319]
### Godot version

v4.0.rc2.official [d2699dc7a]

### System information

Linux Mint 20.3

### Issue description

I'm trying to import some Assets.
I receive the message that I need "FBX2glTF" to import FBX files (fig. 1).

![fig1](https://user-images.githubusercontent.com/125417462/218897167-11a98609-96e9-4d16-8028-8885ac06957a.jpg)

I don't have FBX2glTF, so I click "Cancel".
It then proceeds to (Re)Import the assets (fig. 2)

![fig2](https://user-images.githubusercontent.com/125417462/218897228-d0d3fcc2-6802-4402-9eaa-f953582d147c.jpg)

and at the end I receive the same message (fig. 1). The process continues and can not be canceled. If I try to shut down Godot, next time I open the project, the first thing it does is to (Re)Import the assets and continue with the same loop.

I suppose that if I don't have the program needed to import the assets, clicking "Cancel" would cancel the import process and return to the project.

### Steps to reproduce

Trying to import an Asset that contains assets that need to be converted by a third party program.

### Minimal reproduction project

N/A

**Comment by PQINT** [comment]
the stable version has the same problem
