### ISSUE TITLE
Z Drive won't show in drive selection dropdown

### ISSUE THREAD

**Issue by balloonpopper** [godotengine/godot#7331]
Windows 10 - Godot 2.1 stable

In windows explorer I have multiple drives, one of which is Z:
Trying to import a project, the "Z" drive is not listed in the "Open a File" dialog's drive pulldown.
Mapping different paths to "Z" drive doesn't help. If I map the same path to a different drive letter I can access it under that drive letter. 
The dialog won't show a "Z" drive in the listing, no matter what's mapped to it but appears to show any other drive letter (ie. "A" to "Y")

**Comment by bojidar-bg** [comment]
Seems like the error comes from here: https://github.com/godotengine/godot/blob/master/drivers/windows/dir_access_windows.h#L47

**Comment by RebelliousX** [comment]
@bojidar-bg Yes, changed it to 26 as the number of english letters and it showed Z drive
Before:
![z_before](https://cloud.githubusercontent.com/assets/1888186/21412073/033688a8-c7b3-11e6-8fe9-eb49d4961cf2.png)
After:
![z_after](https://cloud.githubusercontent.com/assets/1888186/21412079/0c7b2248-c7b3-11e6-831c-7324800d0bdf.png)

**Comment by bojidar-bg** [comment]
@RebelliousX Good, then you can make a PR! :laughing:

**Comment by akien-mga** [comment]
Fixed by #7351.
