### ISSUE TITLE
Theme update problems caused by using SNAME

### ISSUE THREAD

**Issue by vmjcv** [godotengine/godot#73314]
### Godot version

4.0 rc1

### System information

windows11

### Issue description

Expected: theme.set_font_size can adjust the text size of controls that use the same theme throughout the project
Actual：theme.set_font_size cannot resize any controls

Reason: Use SNAME() as the key in the engine script, but use String as the key in the gdscript script

For example: Change a button‘s theme_font_size
In gdscript, the code is 
```
func _ready():
	theme.set_font_size("font_szie", "Button", 80)
	printt("get_theme_font_size",get_theme_font_size("font_szie", "Button"))
	notification(NOTIFICATION_THEME_CHANGED)
```
it will print 80, but the button's font size don't change.
Because calling [theme.set_font_size](https://github.com/godotengine/godot/blob/master/scene/resources/theme.cpp#:~:text=void%20Theme%3A%3Aset_font_size(const%20StringName%20%26p_name%2C%20const%20StringName%20%26p_theme_type%2C%20int%20p_font_size)%20%7B)
from gdscript. the p_name's type is String. so you will storage "font_size"(String key) in  font_size_map[p_theme_type].
but in [Button._update_theme_item_cache()](https://github.com/godotengine/godot/blob/master/scene/gui/button.cpp#:~:text=theme_cache.font_size%20%3D%20get_theme_font_size(SNAME(%22font_size%22))%3B). the key is SNAME("font_size"). because hash(SNAME("font_size"))!=hash("font_size"). So you cannot get the expected value, and the control will not be updated.

The possible repair method is to do a type conversion in the incoming function of gdscript, like "font_size"->SNAME（"font_size"）

Note: Similar problems should exist in other controls

### Steps to reproduce

1. open project and run it 
2. you can see two node, test_80's font_size is 20,  test_20's font_size is 20. But in code, test_80's font_size is 80
![image](https://user-images.githubusercontent.com/25278695/218882558-7aff19a7-3bf6-4cee-90f7-b9e065194961.png)

### Minimal reproduction project

[test_theme_font_size.zip](https://github.com/godotengine/godot/files/10737622/test_theme_font_size.zip)

**Comment by YuriSizov** [comment]
You have a typo in your code.

> "font_szie"

**Comment by vmjcv** [comment]
thanks your help. I'm sorry I didn't review my code carefully @YuriSizov

**Comment by vmjcv** [comment]
thanks your help. I'm sorry I didn't review my code carefully @YuriSizov
