### ISSUE TITLE
Some texts are translated into empty strings.

### ISSUE THREAD

**Issue by minazukitouka** [godotengine/godot#73317]
### Godot version

4.0.rc1, 4.0.rc2

### System information

Windows 11

### Issue description

![no-translated-text](https://user-images.githubusercontent.com/118855397/218890352-d47fe605-23cd-4c9f-90de-915683174267.gif)

The editor shows an "incomplete format" error when this happens.

### Steps to reproduce

1. Change editor language to zh_TW, then restart the editor.
2. Add an animation tree, set tree root to a new AnimationNodeStateMachine.
3. Right click on the AnimationTree editor.

### Minimal reproduction project

[EmptyTranslation.zip](https://github.com/godotengine/godot/files/10737823/EmptyTranslation.zip)

**Comment by timothyqiu** [comment]
Thanks for reporting this. I've fixed the translation, it should be included after the next translation sync.

**Comment by akien-mga** [comment]
Closing as it will be fixed tomorrow when I update the translations in Git.
