### ISSUE TITLE
Godot 4 RC 2 completely gets rid of viewport lines on OpenGL.

### ISSUE THREAD

**Issue by BlueGameStudios** [godotengine/godot#73320]
### Godot version

4.0 RC 2

### System information

Windows 11, AMD Radeon RX 6700 XT, OpenGL

### Issue description

OpenGL:
![image](https://user-images.githubusercontent.com/120224184/218899408-1faff448-ffe6-4954-a7cb-5593374af2a0.png)
Vulkan:
![image](https://user-images.githubusercontent.com/120224184/218899456-cebc8b03-d73d-4df4-9a37-1ef748bb542a.png)

Note:
All I did was switch from forward+ to compatibility at the top right.

### Steps to reproduce

1: New project, rendering device = compatibility
2. See the problem?

### Minimal reproduction project

[rc2test.zip](https://github.com/godotengine/godot/files/10738273/rc2test.zip)

**Comment by clayjohn** [comment]
I can't reproduce on my device. PopOS 22.04 intel iGPU.

This is how the MRP looks for me using the gl_compatibility renderer:
![image](https://user-images.githubusercontent.com/16521339/218913777-0574d9e4-68c2-4573-afb5-922971dce497.png)

I can test on another computer as well to see if maybe this is a Windows or Radeon GPU issue

**Comment by clayjohn** [comment]
I can reproduce this on Windows 10 with an RX 6900 XT. 

This appears to be a regression from https://github.com/godotengine/godot/pull/72914. Line drawing relies on ``unpackHalf2x16`` which appears to return a totally wrong color on Radeon GPUs now
