### ISSUE TITLE
Editor won't start on Android (regression in 4.0 beta 16)

### ISSUE THREAD

**Issue by Palka606** [godotengine/godot#73323]
### Godot version

4.0beta15 - 4.0rc2

### System information

Android 10, OpenGL ES 3.2, Snapdragon 625, Adreno, aarch64

### Issue description

Hello! I am writing for the second time for the same reason.
Once I installed beta15 and everything worked well. But after I wanted to upgrade to beta16, godot stopped opening/creating projects in the editor. After that, no version 4.0 was able to open the project. Please try to fix this. Attached screenshots below GPU Z.
![Screenshot_2023-02-15-10-41-41-072_com cpuid cpu_z](https://user-images.githubusercontent.com/95614918/218906770-28b9c988-e22c-49e1-9c46-cdc82962ab7b.jpg)
![Screenshot_2023-02-15-10-40-08-181_com cpuid cpu_z](https://user-images.githubusercontent.com/95614918/218906779-08583eaf-1a6c-45f0-9abb-9bd3d3a2f63c.jpg)
![Screenshot_2023-02-15-10-40-12-004_com cpuid cpu_z](https://user-images.githubusercontent.com/95614918/218906782-de7a621c-862f-4b87-a5ec-324306e7b091.jpg)

### Steps to reproduce

1. installed 4.0beta15
2. Deleted 4.0beta15
3. installed 4.0beta16 (editor's first error)
4. All of the following 4.0 versions were installed and none were able to open/create the project

### Minimal reproduction project

empty.

**Comment by akien-mga** [comment]
Can you fetch logs with `adb logcat` or the Android Studio after trying to open Godot?

**Comment by Palka606** [comment]
> Can you fetch logs with `adb logcat` or the Android Studio after trying to open Godot?

I'll try

**Comment by Palka606** [comment]
> Can you fetch logs with `adb logcat` or the Android Studio after trying to open Godot?

I'll try

**Comment by m4gr3d** [comment]
@Palka606 Can you try installing the version from the Play store - https://play.google.com/store/apps/details?id=org.godotengine.editor.v4

**Comment by Palka606** [comment]
> @Palka606 Can you try installing the version from the Play store - https://play.google.com/store/apps/details?id=org.godotengine.editor.v4

Nothing changes

**Comment by m4gr3d** [comment]
@Palka606 We need more information for this issue to be actionable. Can you fully describe what happens when you use the editor. Even better would be if you could record the issue and post the recording.

In addition, the system information you provided don't match with the screenshots.

**Comment by m4gr3d** [comment]
Closing this issue due to lack of responses.
