### ISSUE TITLE
Bug get_node('area').set_scale(Vector3(0.0, 0.0, 0.0))

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#7332]
**Operating system or device - Godot version:**
Ubuntu 16.04 - Godot 2.1.1

**Issue description** (what happened, and what was expected):
![2016-12-19 14-26-33](https://cloud.githubusercontent.com/assets/11325733/21304559/f76fa788-c600-11e6-9e2a-90e835542544.png)

**Steps to reproduce:**
Bug get_node('area').set_scale(Vector3(0.0, 0.0, 0.0))

**Link to minimal example project** (optional but very welcome):
[Bug set scale.zip](https://github.com/godotengine/godot/files/660373/Bug.set.scale.zip)

**Comment by Alex-doc** [comment]
Why would you want to set scale to 0.0?
If you try to set scale to 0, it should give error.
Did you meant to set scale to 0.01 or similar?

**Comment by bojidar-bg** [comment]
The question is, should we try to either a) improve the error text, or b) fix the scale, so that it is at least `±EPS` on each axis, or c) both?

**Comment by eon-s** [comment]
@bojidar-bg I prefer a clear error message, this could happen with a variable scale where 0 should be a special case (like, turn off monitor or remove the area).

**Comment by DimaKiva** [comment]
> If you try to set scale to 0, it should give error.

Ok. I'll try to remember. But there are different situations addition or subtraction, which may be zero.

> The question is, should we try to either a) improve the error text, or b) fix the scale, so that it is at least ±EPS on each axis, or c) both?

I just do not understand why it is considered an error.

**Comment by Sslaxx** [comment]
Wouldn't setting a scale of 0.0.0 make the object non-visible?

**Comment by DimaKiva** [comment]
> Wouldn't setting a scale of 0.0.0 make the object non-visible?
There will be a black holee :)

**Comment by eon-s** [comment]
@bojidar-bg well, in 2D, it does not allow scale of 0 on the inspector and does not give a warning for trying on code, just leaves it at 0.00001 in both cases.

**Comment by Zylann** [comment]
That probably boils down to how physics are implemented. Unlike rendering, a value of 0 in a scale field can lead to broken results or divides-by-zero.

**Comment by eon-s** [comment]
@DimaKiva any axis on 0 will be a projection, not a scale, and I guess it uses some transformation techniques that does not allow 0.

**Comment by eon-s** [comment]
@Zylann @bojidar-bg is not limited to Area, many Spatial nodes are affected allowing set to 0 but throwing error on the console.

The curious thing is you can set a Spatial node to 0 and that works fine for the children 😕

**Comment by Noshyaar** [comment]
Still reproducible/relevant in 3.1 master 48890b1 : #18087 (Control node)

**Comment by KoBeWi** [comment]
This does not produce errors since 3.1 stable.
