### ISSUE TITLE
Typing Chinese characters in TextEdit gives a lot of error messages

### ISSUE THREAD

**Issue by Rindbee** [godotengine/godot#73321]
### Godot version

v4.0.rc.custom_build [4848877b8], rc1, rc2

### System information

Linux mint 21, NVIDIA GeForce GTX 1050 Ti, Vulkan API 1.3.205, ibus-libpinyin
Win10 

### Issue description

Typing Chinese characters (maybe also include typing of other non-English characters.) in TextEdit may result in the following error message:
```
ERROR: Condition "undo_stack.size() == 0" is true.
   at: end_complex_operation (scene/gui/text_edit.cpp:3907)
ERROR: Condition "!sd" is true. Returning: TextServer::ORIENTATION_HORIZONTAL
   at: _shaped_text_get_orientation (modules/text_server_adv/text_server_adv.cpp:3829)
ERROR: Condition "!sd" is true. Returning: Vector2i()
   at: _shaped_text_get_range (modules/text_server_adv/text_server_adv.cpp:5763)
ERROR: Condition "!sd" is true. Returning: 0.0
   at: _shaped_text_get_ascent (modules/text_server_adv/text_server_adv.cpp:5811)
ERROR: Condition "!sd" is true. Returning: 0.0
   at: _shaped_text_get_descent (modules/text_server_adv/text_server_adv.cpp:5822)
ERROR: Condition "!sd" is true. Returning: 0
   at: _shaped_text_get_glyph_count (modules/text_server_adv/text_server_adv.cpp:5734)
ERROR: Condition "!sd" is true. Returning: nullptr
   at: _shaped_text_get_glyphs (modules/text_server_adv/text_server_adv.cpp:5723)
```
The output is similar to the one in #71902.

https://user-images.githubusercontent.com/30386067/218899329-503553d6-e480-4f4d-aac3-2c77eb22a69f.mp4

### Steps to reproduce

1. New a scene;
2. Add a TextEdit with a  large enough size;
3. Run the scene and type Chinese characters into the TextEdit.

### Minimal reproduction project

N/A

**Comment by bruvzg** [comment]
Is it reproducible with `LineEdit`? Also, which IME method and framework (ibus, fctix) are you using?

**Comment by Rindbee** [comment]
> Is it reproducible with `LineEdit`? Also, which IME method and framework (ibus, fctix) are you using?

`LineEdit` doesn't seem to have this problem. Here ibus-libpinyin is used. This issue can also be reproduced by using the pinyin input method that comes with the system on win10.

**Comment by Rindbee** [comment]
The first error message has been fixed.

The remaining error messages need to meet the following two conditions at the same time.
1. Enable "Embed preedit text in application window" in Ibus Preferences;
 ![0](https://user-images.githubusercontent.com/30386067/225815855-3517d40e-996b-4810-b5f3-5918a0df840d.png)
2. Run the ibus daemon but not the ibus XIM server. Some additional configuration may be required for the ibus xim service to run by default.
