### ISSUE TITLE
Inspector panel dropdown/section collapsing bars stay highlighted/visibly hovered when slowly moving the mouse upward over them

### ISSUE THREAD

**Issue by AlnisS** [godotengine/godot#73327]
### Godot version

4.0 RC 2

### System information

macOS Monterey 12.6.3 (21G419), MacBook Pro (16-inch, 2019), 2.3 GHz 8-Core Intel Core i9, 32 GB 2667 MHz DDR4, AMD Radeon Pro 5500M 4 GB

### Issue description

Dropdowns in the Inspector panel stay highlighted if the mouse moves upwards over them slowly.

While this doesn't affect functionality, it's distracting and looks broken.

I couldn't find a matching issue, but it's possible my search terms weren't good enough!

### Steps to reproduce

1. Open any Godot project.
2. Open any resource that has dropdowns (e.g. default_env.tres)
3. **Slowly move the mouse upward over dropdowns** in the Inspector and they **stay highlighted**.
4. **Quickly** moving the mouse does not cause this issue, **nor does slowly moving it downward**. Affects things like default_env.tres.

See gif:
![ezgif-3-c40aabd3b8](https://user-images.githubusercontent.com/19418610/218909439-eb6552e8-7ceb-4931-a5b7-7af6547bc238.gif)

### Minimal reproduction project

N/A

**Comment by Cronos87** [comment]
I can't reproduce this issue in the `Godot 4.2.dev4`. Can someone else confirm it?

**Comment by AlnisS** [comment]
@Cronos87 I can't reproduce it either (tried in Godot 4.2.dev5). I think we can close it!
