### ISSUE TITLE
Improve discoverability of creating physics, navigation and custom data layers in the TileSet editor

### ISSUE THREAD

**Issue by raoufowo** [godotengine/godot#73331]
### Godot version

v4.0.rc2.official [d2699dc7a]

### System information

.

### Issue description

when I tried look new about tilemap some buttons not working , when i press each one of "physics,navigation,custom data" that's happen(look screen shot)
EDIT2: where s autotile ?
EDIT:  i think this doc need update  [https://docs.godotengine.org/en/latest/tutorials/2d/using_tilemaps.html]([https://docs.godotengine.org/en/latest/tutorials/2d/using_tilemaps.html](https://github.com/godotengine/godot/issues/url))

### Steps to reproduce

.

### Minimal reproduction project

![image](https://user-images.githubusercontent.com/86517257/218929153-66f0532b-7b60-44bf-a958-8531ad57174f.png)

**Comment by akien-mga** [comment]
It's not clear to me what this bug report is about.

Is the bug only the blue outlines at the wrong place in the Paint Properties?

**Comment by leogott** [comment]
Rendering, Physics, Transform and Custom are all Categories of layers, not actual data layers you would be able to paint on.

**Comment by Calinou** [comment]
There should be a clearer hint in the inspector that you need to add physics/navigation/custom data layers to be able to add anything there.

**Comment by raoufowo** [comment]
> 

@akien-mga akien-mga 
i think it should be when you click one of "physics,navigation,custom data" you'll get some button for click like when click "rendering" shows texture origin ,modulate , z-index ......
