### ISSUE TITLE
Shader project settings not showing until shader editor is open

### ISSUE THREAD

**Issue by dalexeev** [godotengine/godot#73336]
### Godot version

v4.0.rc2.official [d2699dc7a]

### System information

Kubuntu 22.10

### Issue description

Shader project settings (`debug/shader_language/*`) only appear after the shader editor is opened for the first time.

Before:
![](https://user-images.githubusercontent.com/47700418/218946992-1ca11c75-59d4-46a7-b547-0c79a16b9807.png)

After:
![](https://user-images.githubusercontent.com/47700418/218947088-9ae36890-49b1-47de-ae5f-9fa8e8d54d2e.png)

Related:

* #55730

### Steps to reproduce

1. Open the Godot editor.
2. Open the Project Settings, enable Advanced Settings and make sure the section is not visible.
3. Create a new shader resource in the Inspector so that the shader editor appears in the bottom panel.
4. Open the Project Settings and you will see that the section has appeared.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
This is likely fixed by moving setting default declarations to `editor_settings.cpp`.
