### ISSUE TITLE
Camera2D  jitter

### ISSUE THREAD

**Issue by dream-young-soul** [godotengine/godot#73347]
### Godot version

4.0 mono rc2

### System information

windows11. rtx 3050 .vulkan

### Issue description

The camera shakes during movement, but this problem does not occur with 3.5x

### Steps to reproduce

Press the arrow keys to observe the scene while moving

### Minimal reproduction project

[camera2d_test.zip](https://github.com/godotengine/godot/files/10741698/camera2d_test.zip)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/71074 (possible duplicate)?

**Comment by WhalesState** [comment]
please confirm if setting `snap 2d transforms to pixel` and `snap 2d vertices to pixel` enabled still produce this issue.

![image](https://github.com/godotengine/godot/assets/53877170/e4f79817-318f-4395-a69b-86e4d5d660f8)

**Comment by dream-young-soul** [comment]
see [The protagonist of the 2d camera experiences severe shaking](https://github.com/godotengine/godot/issues/83135)
