### ISSUE TITLE
GraphEdit signal _on_connect_to_empty gives wrong position

### ISSUE THREAD

**Issue by bruno-ortiz** [godotengine/godot#7334]
**Operating system or device - Godot version:**
Windows 10 - Master branch

**Issue description** (what happened, and what was expected):
 When using a GraphEdit as a plugin, the release_position of the signal "_on_connect_to_empty", gives the wrong position.

https://www.youtube.com/watch?v=2Th9_l0413g

**Steps to reproduce:**
Shown in the videos above.

**Link to minimal example project** (optional but very welcome):

**Comment by volzhs** [comment]
I not sure this is a bug.
All position information of GraphEdit are relative to GraphEdit node in my experience, and I think it should be.
I don't know how @bruno-ortiz made this.
But I guess should add some positions, like global position, scroll offset, zoom level of GraphEdit node to fix this.

**Comment by bruno-ortiz** [comment]
@volzhs i tried that already.

I uploaded the project, it's in an very early stage(a.k.a nothing works), but you can try for yourself.

https://github.com/bruno-ortiz/Behave

The Two scenes that you need to look at are BehaviorTreeEditor.tscn and Teste.tscn.

**Comment by volzhs** [comment]
@bruno-ortiz can't run Teste.tscn because of error on line 20 `child.on_enter()` in `behavior_tree.gd`

**Comment by bruno-ortiz** [comment]
**missclick

@volzhs  You dont need to run Teste.tscn. Just click on the behavior tree node on it, this will add the Behave panel to the bottom panel.

**Comment by bruno-ortiz** [comment]
Fixed the problem, you were right @volzhs, adding the global_pos() of the GraphEdit, did the trick. I thought i did it before, but i didn't.

I understand now, the "release_position" was relative to the GraphEdit.

Sorry :/

And thanks :D
