### ISSUE TITLE
Mono external editor broken, Godot 4 rc1 & 2 / Mac OS

### ISSUE THREAD

**Issue by tburt** [godotengine/godot#73348]
### Godot version

4.0.dev / mono

### System information

Mac OS 12.5.1 Intel

### Issue description

Starting in 4.0 rc1,  Editor Settings/Mono/Editor/External Editor shows an int value instead of enum. Double clicking a .cs file in the file explorer opens the file in the internal editor, whatever the value of the int.

Editor Settings/Mono/Builds/Build Tool also shows an int value instead of enum, though this has been the behavior for several dev releases (not sure when it started).

### Steps to reproduce

1. Go to  Editor Settings/Mono
2. Attempt to set value of Editor/External Editor or Builds/Build Tool
3. Double click any .cs source file from the file explorer.

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
The setting was renamed, it's now in the "Dotnet" folder.

Obsolete settings saved in your config are still shown, this might change in the future (https://github.com/godotengine/godot-proposals/issues/4444) but for now you can ignore/reset them.

**Comment by tburt** [comment]
Ah makes perfect sense, thanks very much for explaining
