### ISSUE TITLE
[4.0] GDScript "Go to definition" doesn't work with member from a different class

### ISSUE THREAD

**Issue by hsandt** [godotengine/godot#73354]
### Godot version

v4.0.rc1.official [8843d9ad3]

### System information

Linux Ubuntu 20.04 with Unity desktop

### Issue description

Ctrl+click to go to definition does not work when targeting a member (property or method) of an object of another type, even when this type is properly hinted (static type).

Holding ctrl and hovering the member will not underline the member in red, and clicking will do nothing. This applies to both custom classes and built-in types.

Holding ctrl and hovering other class member:

![image](https://user-images.githubusercontent.com/1067772/219036604-18ebf823-7134-4401-b9d2-1a5e189bb735.png)

In comparison, holding ctrl and hovering member of same class as current file, or a global built-in will work:

![image](https://user-images.githubusercontent.com/1067772/219036648-afe30d98-e0a1-4da8-8dbb-59d09960ddf9.png)

### Steps to reproduce

1. Open B.gd in script editor
2. Hold Ctrl and hover various members, and try to click on them
Expected: all members and built-in symbols should be recognized to go to definition
Actual: members of A and Animation are not recognized

### Minimal reproduction project

[v4.0.rc1 - Go to definition doesnt work on third object member.zip](https://github.com/godotengine/godot/files/10743301/v4.0.rc1.-.Go.to.definition.doesnt.work.on.third.object.member.zip)

**Comment by akien-mga** [comment]
Thanks for the detailed report. This was a regression in RC 1 and already fixed in RC 2 by d405392847149e1620324ac9217952bc51884baf.
