### ISSUE TITLE
Show warning or error when lambda does not return a value

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#73357]
### Godot version

v4.0.beta14.official [28a24639c]

### System information

Mac

### Issue description

When I use lambdas:

```gdscript
var my_func = func(x): some_func(x)
```

Or even worse

```gdscript
self.do_something(func(x): do_something_else(x, a, b, c))
```

It's quite easy to miss that there is no `return`, and so the lamda returns `null`.

Perhaps we can make the default return value the left operand of whatever is inside the lambda?

Perhaps alternately we can add a warning? 

I would prefer the left operand because it allows side effects (i.e. no effect) in a lamda.

### Steps to reproduce

It's a dev flow issue

### Minimal reproduction project

Please see above

**Comment by tavurth** [comment]
@Calinou I'm not sure if this should be a proposal?

**Comment by YuriSizov** [comment]
Please don't arbitrary tag contributors, we have teams that can take a look at your report at their convenience.

And yes, there is already a related proposal, where this can be discussed: https://github.com/godotengine/godot-proposals/issues/5925
