### ISSUE TITLE
Timer wait time 0.01 is not enough small

### ISSUE THREAD

**Issue by Rocket-Buddha** [godotengine/godot#7335]
Timer wait time 0.01 is not enough small.

**Comment by Dillybob92** [comment]
Pretty sure you can do it less than 0.01...?

**Comment by bojidar-bg** [comment]
What about just doing a `call_deferred` and/or adding `_fixed_process` deltas instead?

**Comment by Rocket-Buddha** [comment]
I don't understand how call_deferred works.

**Comment by Zylann** [comment]
0.01 seconds is less than a frame (aka more than 60 fps), how do you expect it to work?

**Comment by Rocket-Buddha** [comment]
I' am writing a scoreboard discount. As I see it, if I could setup the timer wait time in less than 0.01 I will allowed modifying the label text 2 times between frames. I don't care if one this update is never seen. Your code is similar to Timer internal code; I don't want to reinvent the wheel. But your comment let me think, that I need more efficient solution, thanks.

**Comment by akien-mga** [comment]
I don't see anything that can be implemented in Godot here, if you need to make operations faster than the game loop, you need to find some tricks which would be game specific (like setting the FPS to 120 and slowing down everything else..). But it mostly sounds like you're trying to implement bad design, if you need to change a label twice per frame, just skip the 1st change and do the 2nd one...
