### ISSUE TITLE
Saving a builtin gdscript of an unsaved scene crashes the engine

### ISSUE THREAD

**Issue by blueloveTH** [godotengine/godot#73366]
### Godot version

4.0 Beta RC2

### System information

Windows 11, Nvidia GTX 3070, Vulkan

### Issue description

When saving a builtin gdscript of an unsaved scene, the engine gets no respond and then crashes.

https://user-images.githubusercontent.com/28104173/219067204-5c651fa2-cf54-42b8-ad7a-1b3522408dd8.mp4

### Steps to reproduce

1. Create a new project
2. Create a 2D scene as root (DON'T SAVE IT)
3. Select root node and click "+"
4. Add a builtin GDScript
5. Press CTRL+S to save (CRASH!!)

### Minimal reproduction project

You need to create a new project.

**Comment by akien-mga** [comment]
Tested on Linux with RC 2, I couldn't reproduce the issue with Ctrl+S (it prompts me to save the scene, which works fine), but I can reproduce it with Shift+Alt+S, which is "Save All" in the script editor.

It spams
```
ERROR: Can't save resource to empty path. Provide non-empty path or a Resource with non-empty resource_path.
   at: save (core/io/resource_saver.cpp:105)
ERROR: Can't save resource to empty path. Provide non-empty path or a Resource with non-empty resource_path.
   at: save (core/io/resource_saver.cpp:105)
```
and freezes the editor (which might lead to a crash eventually once running out of stack)
