### ISSUE TITLE
Game window is frozen during debugging when a code error occurs

### ISSUE THREAD

**Issue by stesproject** [godotengine/godot#73374]
### Godot version

4.0 rc1/rc2

### System information

Windows 11

### Issue description

When an error occours in the code (any error in any script), the debug window freeze (not responding)
![image](https://user-images.githubusercontent.com/32966173/219080275-ce1aca6b-c7b8-4e9d-b4f3-e8ddddd47483.png)

### Steps to reproduce

1. Run the game (F5 to enter play mode)
2. Try to close the DEBUG window (F8 to exit play mode or just press the 'X' to close the window)

I purposely set
`remoteTransform.remote_path = null`
on line 6 of the player.gd script to let an error occour

### Minimal reproduction project

[crash.zip](https://github.com/godotengine/godot/files/10744805/crash.zip)

**Comment by akien-mga** [comment]
I can't reproduce on Mageia 9 Linux running KDE Plasma on X11.

But this might be OS specific, on my system I can't actually close the game window when the debugger breaks on an error. The game window is frozen, the editor is working fine with the debugger raised:
![image](https://user-images.githubusercontent.com/4701338/219100335-27ab80a0-7c78-4e7c-bb85-514e26d6362b.png)
To close the game window, I need to hit the Stop button in the editor. (Or kill the game process from the OS, but that doesn't trigger a crash).

**Comment by jamie-pate** [comment]
This is an issue on windows only.
Still happens on godot 4.2.2

On linux the window will update and changes made in the remote tree will immediately be reflected in the window.

As of godot 4 On windows the game window will be frozen and will not be updated.

Likely there is some event handler in windows that is not handling events anymore while the debugger has it paused.

This used to work in godot3

**Comment by jamie-pate** [comment]
In the debugger loop it calls 

`OS::get_singleton()->process_and_drop_events();`
				
but this function is no longer implemented on windows/osx
