### ISSUE TITLE
Error parsing .po file from poeditor.com (internationalization, localization)

### ISSUE THREAD

**Issue by chanon** [godotengine/godot#7337]
After adding .po file exported from poeditor.com to translations in project settings, this is output on console:

```
ERROR: :1 Unexpected 'msgstr', was expecting 'msgid' while parsing:
   At: core\io\translation_loader_po.cpp:107
ERROR: Failed loading resource: res://localization/A_Project_English.po
   At: core\io\resource_loader.cpp:218
```

contents of A_Project_English.po:
```
msgid ""
msgstr ""
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: POEditor.com\n"
"Project-Id-Version: A Project\n"
"Language: en\n"

#: 
msgid "key_hello"
msgstr "Hello there!"

#: 
msgid "key_bye"
msgstr "Bye!!!"

```

This file is successfully loaded by Poedit po editor.

**Comment by chanon** [comment]
As a workaround .. can someone provide an example po file that is sucessfully loaded so I can hand edit my own to match?

I've tried editing the po file by hand in various ways and I come up with different errors instead. Looking at the translation_loader_po.cpp file, I can't figure what's wrong either.

**Comment by bojidar-bg** [comment]
Does adding a newline before the first `msgid ""` line fix it? (no idea, just blind-testing...)

**Comment by bojidar-bg** [comment]
Also, which version of godot and OS are you on?

**Comment by chanon** [comment]
> Does adding a newline before the first msgid "" line fix it? (no idea, just blind-testing...)

Wow, that did it! Absolutely didn't expect it to.
I'm on master branch (self built), Windows 10.

**Comment by chanon** [comment]
One other thing from the code here:

https://github.com/godotengine/godot/blob/c05ff0577fd9cc39a6968e65743f7d7da711bfe2/core/io/translation_loader_po.cpp#L173-L175

it looks like the code is looking for an "X-Language" config, but in my .po above it is using "Language".

**Comment by bojidar-bg** [comment]
@chanon No, that's unrelated, since the error is raised before it is looking at the configs.

**Comment by bojidar-bg** [comment]
The problem is that [line 106](https://github.com/godotengine/godot/blob/master/core/io/translation_loader_po.cpp#L106), which raises the error, can occur only if the if on [line 101](https://github.com/godotengine/godot/blob/master/core/io/translation_loader_po.cpp#L101) (`if (l.begins_with("msgstr"))`) passes. Since the error message prints `:1` in the beginning, we can be sure that it errors out during the first iteration, or that it somehow doesn't pass through any `line++` instruction..

**Comment by chanon** [comment]
Thanks!

> @chanon No, that's unrelated, since the error is raised before it is looking at the configs.

Yes, it is unrelated, but I believe it means it won't be able to detect the language from the po file correctly. Maybe it should be a separate issue?

**Comment by bojidar-bg** [comment]
@chanon Exactly, a seperate issue might be better (though, you should also research if such parameters are widespread)
