### ISSUE TITLE
Resizing Ninepatchrect horizontaly does not draw child label text.

### ISSUE THREAD

**Issue by Bargeral** [godotengine/godot#73385]
### Godot version

v4.0.rc2.official [d2699dc7a]

### System information

Windows 10

### Issue description

Resizing a ninepatchrect horizontally causes child label text to not show.  
Vertical resizing is fine.  
If you resize it enough that label has to re-do the text wrap then text shows up.
Toggle the visibility and text will show up.
Resize the 9patch Vertically and text will show up.  

I would think a comparison between the Vertical and Horizontal handling in the code would show the issue. 

https://user-images.githubusercontent.com/3193592/219109730-d19edde5-6049-4460-9cab-f15ec2a3ea4a.mp4

### Steps to reproduce

In attached project, resize the 9pathc node and observe the label text behavior. Also, see attached video 

### Minimal reproduction project

[ninepatch_bug.zip](https://github.com/godotengine/godot/files/10745926/ninepatch_bug.zip)

**Comment by YuriSizov** [comment]
This is similar to https://github.com/godotengine/godot/issues/73296 and fixed by https://github.com/godotengine/godot/pull/73343.
