### ISSUE TITLE
Improved "remapping" for localized resources - remap folders instead of individual resource files

### ISSUE THREAD

**Issue by chanon** [godotengine/godot#7338]
This suggestion comes from a feature that I've implemented in my previous game engine and is very convenient.

## The Problem

Godot has a "remapping" functionality for localization where you can remap paths for specific resources for each locale.

This is nice, but the problem is when there are lots of resources that need remapping and there are lots of locales that need to be supported then it becomes extremely time consuming to setup the mappings because you have to set them up one by one.

## A Solution

Instead of mapping each resource file one by one, I suggest mapping paths.
This could be by convention with configurable 'locales' path.

For example, consider this project structure:

```
res/
	images/
		titleScreen.png
		enemySprite.png
		playerSprite.png
	fonts/
		mainText.tres (a font resource)
	audio/
		...
```

When localizing, maybe we need to support de and es locales. Maybe we need to localize just the titleScreen and the mainText font.

We might then have this project structure:

```
res/
	images/
		titleScreen.png
		enemySprite.png
		playerSprite.png
	fonts/
		mainText.tres (a font resource)
	audio/
		...
	locales/
		de/
			images/
				titleScreen.png
			fonts/
				mainText.tres
		es/
			images/
				titleScreen.png
			fonts/
				mainText.tres
```

The idea is that, whatever needs to be changed in a locale, we add the changed version inside the correct subfolder inside the locales folder. Then the engine will use it to **_"override"_** the default file.

This way there is no need to manually setup mappings one by one. Instead you just copy the files into place and you're ready to go.

## Implementation

Godot already runs every resource file access through ```PathRemap``` singleton defined in ```path_remap.cpp```, specifically the ```get_remap``` method. This is actually very powerful as even script files (.gd) and scene files (.tscn) and everything else goes through this method.

What is needed is to only add additional functionality to ```get_remap``` to detect whether a corresponding resource file exists in the corresponding localization folder and return the path if it does.

EDIT: Upon further thought, this can actually be implemented by using PathRemap itself. What is needed is to just scan the locales path at startup to see what files are in there and setup remappings for them using PathRemap.add_remap which already has a p_locale parameter.

## Folder location

If this is to be implemented, one thing that might need to be discussed is where should the 'locales' folder be / should it be named 'locales' and should it be configurable?

Note: In my old engine, the engine supported mounting folders virtually, so what I did was just mount the correct locale folder on top of the resources folder so that the localized resources would override the other ones.

**Comment by bojidar-bg** [comment]
Note that we already support "virtual" mounting of res:// folders from resource packs.

**Comment by insomniacUNDERSCORElemon** [comment]
Not sure if I'm reading too much into this, but does this (either suggested or what is possible) for user-added resourcepacks (partial replacement of textures, sounds, models, etc. Best if it's stackable, like have one pack that replaces 50 textures and under that one with 20 textures some of which might be the same destination but aren't used) or is it internal only and something that would need a tedious setup to be possible?

**Comment by bojidar-bg** [comment]
@insomniacUNDERSCORElemon You are asking for something that is probably already somewhat possible with resource packs. So, no, this issue is probably for something else :smiley:

**Comment by chanon** [comment]
Upon further thought, this can actually be implemented in a custom module by using ```PathRemap``` itself. What is needed is to just scan the locales path at startup to see what files are in there and setup remappings for them using ```PathRemap.add_remap``` which already has a ```p_locale``` parameter.

BTW (unrelated, but curious) @bojidar-bg is there any documentation regarding resource packs? I wasn't able to find any.

**Comment by bojidar-bg** [comment]
@chanon There is [`OS::load_resource_pack(path)`](http://docs.godotengine.org/en/latest/classes/class_globals.html#class-globals-load-resource-pack), and not much else -- I guess that's worth reporting on the -docs repo.

**Comment by chanon** [comment]
I have been able to implement this in a custom module. Since there is no need to modify the core engine to support this, I'm closing the issue. If someone likes this idea just see my above comment for an idea of how to implement it.
