### ISSUE TITLE
Hidden rich text box can not be made visible

### ISSUE THREAD

**Issue by Dunkhan** [godotengine/godot#73394]
### Godot version

v4.0.rc2.mono.official [d2699dc7a]

### System information

Linux Mint 20.3 Cinnamon, NVIDIA Corporation TU106 [GeForce RTX 2070]

### Issue description

After upgrading to rc2 project is broken in multiple ways with no clear explanation as to what might have changed to cause the issues.

XX Resolved 1. The project can no longer find the root component in the main scene when started from the editor
2. If the project is run from the editor the code of the file ItemControl.tscn automatically has the line at 103 removed: fit_content_height = true
3. If exported (linux debug) and run it finds the main.tscn file, but the component described at lines 97-103 or ItemControl.tscn does not show when it is made visible. Even if the line in 2. above is still present.
XX Hard to confirm 4. Reverting and running the application with beta 12 seems to have persistent instabilities that were not present before even after deleting .config/godot (hard to confirm)

### Steps to reproduce

1. I made a beta17 branch here https://gitlab.com/gametheatre/poriferareader/Porifera/-/tree/beta17 simply check out, open in the rc2 editor, press play
2. Same as 1. then check git for changes
3. revert changes caused by 2. export, run exported project, subscribe to a feed e.g. https://www.reddit.com/r/godot/ , click on an item to expand the description/content field
XX 4. after trying step 1 above, check out https://gitlab.com/gametheatre/poriferareader/Porifera/-/tree/beta12 branch and open in godot beta 12 editor

### Minimal reproduction project

https://gitlab.com/gametheatre/poriferareader/Porifera/-/tree/beta17
https://gitlab.com/gametheatre/poriferareader/Porifera/-/tree/beta12

I know it is not minimal, but there are issue that only affect complex projects. I am open to the possibility that the correct fix for me to change my code but even if that is the case, issues like this are going to strand people on Godot 3 and make updating projects to the new version when it is released impossible.

**Comment by Dunkhan** [comment]
Possibly connected to https://github.com/godotengine/godot/issues/70910, based on the fact that both issues occur on the same project and appear to be rare.

**Comment by Dunkhan** [comment]
Ah, just noticed RC 2 was released, let me check that before anyone spends time on this

**Comment by Dunkhan** [comment]
In rc2 problem 3. is worse for the beta12 branch but I can open the beta17 branch in the editor ok. I guess that makes problem 3. only relevant for upgrading projects. Hopefully that is being tested for upgrading from Godot 3.0, not many people will be dealing with the 12 -> release issue so it might not be a big deal. 4. is still impossible to be sure about. 1. is resolved

I will update the report

**Comment by YuriSizov** [comment]
> fit_content_height = true

This property no longer exists, there is now `fit_content` and works universally, see https://github.com/godotengine/godot/pull/71330.
