### ISSUE TITLE
Godot 4 rc2: Inspector - name of selected scene is not output correctly

### ISSUE THREAD

**Issue by Juuliuus** [godotengine/godot#73395]
### Godot version

4.0 rc2

### System information

Linux Ubuntu

### Issue description

Select a node from the scene tab, and then in the inspector the name (first field in the inspector) is either chopped off by a few characters or it has unnecessary ellipses added.
![characters_chopped_off](https://user-images.githubusercontent.com/7746371/219134123-218bb529-c328-4aa2-9f0d-3b346ae520da.png)
![unneccesary_ellipses](https://user-images.githubusercontent.com/7746371/219134130-0c81ee1c-7ae2-423f-91d2-5b8b709dcc72.png)

### Steps to reproduce

Click on a node in the scene tree and see that the inspector is not reflecting the entire node name.

### Minimal reproduction project

<no script>

**Comment by YuriSizov** [comment]
This is probably fixed https://github.com/godotengine/godot/pull/73343, if I had to guess.

**Comment by RandomShaper** [comment]
> This is probably fixed #73343, if I had to guess.

Maybe, but seeing the screenshots in the PR when it had a bug that has been eventually fixed, it seems it was making the icon misalignment worse, but it was already in RC2. So, it may be that it fixed it luckily, or that it just stopped making it even worse with that final fixup.

I'll check it after dinner.

**Comment by bend-n** [comment]
@YuriSizov issue persists on f2aae8fa5
