### ISSUE TITLE
TabContainer does not support focusing tabs for keyboard navigation

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#73406]
### Godot version

v4.0.rc2.official [d2699dc7a]

### System information

Debain 11 KDE Plasma 5.20.5

### Issue description

Some controls don't support focusing their own parts..
for example tab container doesn't allow focusing between it's own tabs with left and right

### Steps to reproduce

- Add a tab container
- Add some tabs
- Make sure it's focus mode is set to all
- Run the project
- Click on a tab
- Try switching with left and right

### Minimal reproduction project

[TabContainerBugs.zip](https://github.com/godotengine/godot/files/10751011/TabContainerBugs.zip)

**Comment by Shadowblitz16** [comment]
https://github.com/godotengine/godot/issues/73405

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/25877.

**Comment by Shadowblitz16** [comment]
https://github.com/godotengine/godot-proposals/issues/6297
