### ISSUE TITLE
Positional shadow artifacting in VR

### ISSUE THREAD

**Issue by firescaleVR** [godotengine/godot#73407]
### Godot version

4.0 rc2

### System information

Windows 10, Vulkan, GTX 1070

### Issue description

Positional shadows from omni lights have severe artifacting around the edges of their volumes in VR and the artifacting each eye sees is different, left eye sees artifacting on the left edge while right sees artifacting on the right edge.

### Steps to reproduce

See attached project

### Minimal reproduction project

[VR test scene2.zip](https://github.com/godotengine/godot/files/10751052/VR.test.scene2.zip)

**Comment by BastiaanOlij** [comment]
Please check if this is resolved by: https://github.com/godotengine/godot/pull/78499

**Comment by firescaleVR** [comment]
Thanks, issue is resolved in 4.1.1.0 stable.
