### ISSUE TITLE
Godot 4 RC2 - Tileset Paint Texture Offset does not apply any texture offset to tile

### ISSUE THREAD

**Issue by tlobig** [godotengine/godot#73416]
### Godot version

4.0.RC2

### System information

Windows 10, Vulkan, NVIDIA RTX 3080 Laptop (NVIDIA 516.94)

### Issue description

In the Tileset Editor the Paint mode works for things like modulate color and z index, but Texture Offset paint mode does not do anything

![tilset_paint_texture_offset_not_working](https://user-images.githubusercontent.com/10432347/219294764-3cf3553d-2461-44e9-bc01-fe3f9d950091.jpg)

### Steps to reproduce

create tileset
load tile suitable texture
change to paint mode
select texture offset
change offset values
try to paint those values on a tile

### Minimal reproduction project

[tileset_paint_draw_offset.zip](https://github.com/godotengine/godot/files/10753184/tileset_paint_draw_offset.zip)

**Comment by AThousandShips** [comment]
Texture Offset is no longer a property of tile maps, it's now texture origin, sounds like it's incorrectly handling this as a custom property instead

**Comment by tlobig** [comment]
Indeed, this seems to be fixed since a while. I may have been mixing up versions on my end. Sorry for the inconvenience
