### ISSUE TITLE
StyleBox "hover_pressed" missing from Button but used by CheckBox

### ISSUE THREAD

**Issue by Anixias** [godotengine/godot#73439]
### Godot version

v4.0.rc2.mono.official [d2699dc7a]

### System information

Windows 10

### Issue description

Button does not have a "hover_pressed" StyleBox (which I've wanted for a while), but CheckBox does, and will try to use the parent Button's hover_pressed state, making the Button become invisible when hovering over a pressed CheckBox.

Hover:
![image](https://user-images.githubusercontent.com/22286697/219385388-c382933f-64b2-4a71-8746-0ea01ba96d87.png)

Hover while Pressed:
![image](https://user-images.githubusercontent.com/22286697/219385455-be28548f-3c60-4f6e-a932-eb2a178e3439.png)

### Steps to reproduce

1. Create a CheckBox
2. Toggle it on
3. Hover your mouse over it

### Minimal reproduction project

[VanishingCheckBoxMRP.zip](https://github.com/godotengine/godot/files/10778102/VanishingCheckBoxMRP.zip)

**Comment by YuriSizov** [comment]
I don't understand the problem you describe, and the steps are not enough to demonstrate any incorrect behavior. Please provide an actual MRP with a scene and a theme that demonstrate the issue clearly.

**Comment by Anixias** [comment]
The issue is that when you hover over a CheckBox while it is toggled, the underlying Button becomes invisible because Button does not have a "hover_pressed" StyleBox state.

**Comment by YuriSizov** [comment]
There is no underlying Button. CheckBox _is_ a Button.

**Comment by Anixias** [comment]
Either way, the StyleBox for it vanishes when you hover it while it is pressed.

**Comment by YuriSizov** [comment]
Can you provide an MRP? Nothing vanishes with the default theme, or your repro steps are incomplete.

**Comment by Anixias** [comment]
Added. Toggle the CheckBox on, then hovering at all causes the underlying Button to become invisible. The custom theme only modifies Button, not CheckBox.

**Comment by YuriSizov** [comment]
Okay, I see what you mean. Theme properties are inherited alongside the class hierarchy. Since CheckBox is a Button, it takes custom styles for the Button from your theme over its default look from the default theme. However, since your theme does not define any styles for the hover_pressed state, and indeed normal Buttons don't have it, the default theme is used. You need to add a hover_pressed definition for the CheckBox, or for even the Button in your theme.
