### ISSUE TITLE
Cannot set default environment to .res

### ISSUE THREAD

**Issue by scrapp08** [godotengine/godot#73451]
### Godot version

v4.0.rc2.official [d2699dc7a]

### System information

MacOS 13.2.1

### Issue description

When trying to set the default environment to a scene saves as a .res, it allows input of an environment however immediately deletes it after entering.

https://user-images.githubusercontent.com/105889363/219458059-41ac9475-1e69-4c09-859c-73b6d16f30cc.mov

### Steps to reproduce

1. Create scene with world environment node
2. Change some paramenters (For me i added a procedural sky, changed the colour of the ground as that was what i wanted to change for all of my other scenes; to something other than the default brown colour)
3. Save scene as `.res`
4. Change default environment file

### Minimal reproduction project

[Archive.zip](https://github.com/godotengine/godot/files/10759425/Archive.zip)

**Comment by Calinou** [comment]
Does it work with a `.tres` scene?

**Comment by scrapp08** [comment]
I can't seem to save as a `.tres` , and no it doesnt work as a `.tscn`

**Comment by YuriSizov** [comment]
Default environment is not supposed to be a scene. It's a `Environment` resource.

**Comment by scrapp08** [comment]
Is there any way I can change the brown ground colour globally then?

**Comment by Calinou** [comment]
Nevermind, I was confused and thought you were talking about the default scene project setting.

**Comment by YuriSizov** [comment]
> Is there any way I can change the brown ground colour globally then?

Yes, this is defined in an `Environment` resource. The node that you create is called `WorldEnvironment`, but it doesn't do anything without an `Environment` resource. That same resource can be added as a project setting that you're looking at.

**Comment by scrapp08** [comment]
Ok, got it working now, i had to save the environment instead of a scene. Yeah i understand the design choice completely, I'm just stubborn and prefer the old colours. :p

Thanks for the help. :)
