### ISSUE TITLE
Display safe area is bigger than viewport size

### ISSUE THREAD

**Issue by vagnerGT** [godotengine/godot#73455]
### Godot version

4.0.rc2

### System information

Windows 10

### Issue description

Size obtained from `DisplayServer.get_display_safe_area().size` is bigger than window size. Also does not change when resizing the window.

![2023-02-16 16 02 46](https://user-images.githubusercontent.com/70494781/219464915-93e4ef67-dea2-4e08-b621-ede983bd3497.png)

### Steps to reproduce

In an empty project, run a Control node with the following code:

```GDscript
class_name PrintSize
extends Control


func _process(_delta) -> void:
	print("")
	print("Safe area: ", DisplayServer.get_display_safe_area().size)
	print("screen size: ", DisplayServer.screen_get_size())
	print("usable rect: ", DisplayServer.screen_get_usable_rect().size)
	print("Root size: ", get_tree().get_root().size)
	print("Viewport size: ", get_viewport().size)
	print("viewport rect size: ", get_viewport_rect().size)
```

### Minimal reproduction project

[SafeArea.zip](https://github.com/godotengine/godot/files/10759742/SafeArea.zip)

**Comment by Zireael07** [comment]
Display safe area is device specific, it doesn't care about your window size itself
