### ISSUE TITLE
GLTF Import >Settings > Root Type does not change

### ISSUE THREAD

**Issue by AntohaRDNS** [godotengine/godot#73452]
### Godot version

v4.0.rc2.official [d2699dc7a]

### System information

Windows 10, GLES3, Nvidia RTX 3070

### Issue description

In GLTF file Import Settings, when I try to change Root Node type from "Node" to "Node3d" nothing happened

### Steps to reproduce

1. Create Cube in blender
2. Export as *.glb file to godot
3. Try to change RootType from Node3d -> Node -> ..(similar or parent types?) And press Reimport button
4. Conversion does not happen every time.

### Minimal reproduction project

[importIssue.zip](https://github.com/godotengine/godot/files/10759440/importIssue.zip)

**Comment by Calinou** [comment]
By the way, Root Type should not be allowed to select classes that don't inherit from Node (this is allowed right now).

**Comment by hakro** [comment]
I also stumbled upon this issue as well

I made a video showing that in another issue.
Changing from Node3D to MeshInstance3D works. But it doesn't work the other way around.

https://user-images.githubusercontent.com/3624853/221559924-b2c01be4-ac53-4344-a431-57306888032e.mp4

**Comment by aaronfranke** [comment]
Can't reproduce in Godot 4.3-stable. Probably a duplicate of #78140, fixed by #79907. Closing as fixed and adding archived because it's a duplicate.
