### ISSUE TITLE
Selecting and Moving a group of Tiles erases the Selection both in the origin and the destination

### ISSUE THREAD

**Issue by zurasuta** [godotengine/godot#73469]
### Godot version

v4.0.rc2.official [d2699dc7a]

### System information

Windows 10

### Issue description

Instead of moving a selection of tiles, both the tiles in the destination (When you release the selection while moving it) and the tiles you had selected dissapear, making it look like it's an erasing selection despite not having the Eraser enabled. 

https://user-images.githubusercontent.com/25066388/219513252-9a255bf2-f8a4-4eb0-aac7-f8416201355c.mp4

What I expect it to do is to place the original selection of tiles in the destination.

### Steps to reproduce

- Create a Tilemap Node.
- Add a new Tileset in its Inspector.
- Drop a Tileset on the TileSet tab.
- Go back to the TileMap tab.
- Paint some tiles.
- Select some tiles.
- Move the Selection over other tiles. 
- Both the selection and the other tiles are gone.

https://user-images.githubusercontent.com/25066388/219514953-eb841048-25f6-4456-952a-c42bef4745e0.mp4

### Minimal reproduction project

I'm attaching it with a free tileset since the one shown in the videos is licensed but the behavior is the same. 
[tile_map.zip](https://github.com/godotengine/godot/files/10761961/tile_map.zip)

**Comment by Zamakeur** [comment]
I'm having exactly the same issue.
I want to add that trying to create a Pattern by Drag/Drop this way also crashes Godot. No log is created.
