### ISSUE TITLE
AnimatedSprite3d doesn't cast shadows.

### ISSUE THREAD

**Issue by endritdev1** [godotengine/godot#73463]
### Godot version

4.0 rc2

### System information

windows 10

### Issue description

AnimatedSprite3d doesn't cast shadows. I tried it with Sprite3d and it cast shadows. 
It's very inconvenient to not have such a powerful node available to make projects like Octopath traveler.

![image](https://user-images.githubusercontent.com/26037455/219493853-20f340dc-d0d3-45da-a6d7-b12a3075e243.png)

The nodes have both the same settings. 
![image](https://user-images.githubusercontent.com/26037455/219494372-5224dee0-61e6-463c-9b49-13aca6bd7a69.png)

Hopefully this will be fixed soon, in godot 3 it works just fine

### Steps to reproduce

Just use an animatedsprite3d with this settings , it doesn't cast shadows
![image](https://user-images.githubusercontent.com/26037455/219494537-429d5b48-50ce-47a1-8f53-e894a9767b9e.png)

### Minimal reproduction project

[testFebbraio.zip](https://github.com/godotengine/godot/files/10761192/testFebbraio.zip)

**Comment by Calinou** [comment]
You have **Cast Shadow** set to off on the AnimatedSprite3D:

![image](https://user-images.githubusercontent.com/180032/219496840-2442a0c4-4498-41b8-bb88-be4209098cb2.png)
