### ISSUE TITLE
Can't launch scene with custom arguments

### ISSUE THREAD

**Issue by bebae** [godotengine/godot#7346]
1. It is impossible to set arguments

2. Game with custom arguments crashes, because EditorRun::run adds then on the wrong place
(custom arg is "-s")
`running: godot.x11.tools.64 -path path/to/godot-project -rdebug localhost:6007 -epid 8564 -s -p 2368x240 res://root.tscn`
should be:
`running: godot.x11.tools.64 -path path/to/godot-project -rdebug localhost:6007 -epid 8564  -p 2368x240 res://root.tscn -s`

The second issue is easy to solve, but I don't know how you want to handle custom args. Currently the custom arguments gets set to "" by this function:
https://github.com/godotengine/godot/blob/2c8a1729152f5bcb1cb81d24b1e642634bff7174/tools/editor/editor_node.cpp#L1851

because `run_settings_dialog->set_custom_arguments();` is never called in the whole code.
And no idea where I would/should do it. My suggestion would be to add a property to EditorSettings for custom arguments.

I would do the pull request for this issue, just need to know from where we actually want to get the custom arguments.

**Comment by bojidar-bg** [comment]
Note that you can also put extra contiguration options in `engine.cfg` (for just your game).

**Comment by bebae** [comment]
i just used `editor/main_run_args` for now, which was already there, but unused, hope thats fine.

**Comment by bojidar-bg** [comment]
@bebae Indeed it looks unused -- maybe someone added it and forgot to implement it :laughing:
