### ISSUE TITLE
Shift-clicking "Add Sun to Scene" or "Add Environment to Scene" no longer adds both sun and environment at the same time

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#73467]
### Godot version

4.0.rc2

### System information

Fedora 37, GeForce RTX 4090 (NVIDIA 525.85.05)

### Issue description

Prior to 4.0.beta17, you could hold <kbd>Shift</kbd> to add both the current preview sun and environment to the scene when clicking either **Add Sun to Scene** or **Add Environment to Scene** in the 3D editor's preview sky/environment editor:

![image](https://user-images.githubusercontent.com/180032/219509859-7b0cddff-ae04-43f7-b2a2-4c22e1484271.png)

This feature no longer works since 4.0.beta17. If I hold <kbd>Shift</kbd> while clicking, it acts as if it wasn't holding <kbd>Shift</kbd> and will only add the sun or environment (which matches whichever button I clicked).

This feature is useful to add both sun and environment with a single click, speeding up the setup of simple test projects (useful for MRPs and prototyping).

I bisected the regression to 9f426498231816ccb9d686b3944373f61312aa24. cc @bruvzg

### Steps to reproduce

- Ensure the preview sun and sky are enabled, so you can edit them and add them to the current scene. Also make sure there is neither a WorldEnvironment nor a DirectionalLight3D node in the current scene.
- Click the 3 vertical dots icon at the top of the 3D editor viewport, next to the globe.
- Hold <kbd>Shift</kbd> and click **Add Sun to Scene** or **Add Environment to Scene**.
- Notice it only adds one node, while it's supposed to add both. Test this in previous 4.0 betas for comparison.

### Minimal reproduction project

N/A

**Comment by vike2000** [comment]
I came by this issue as just clicking the buttons didn't work at all for me in Godot 4.1.1 on macOS 10.13.
Getting desperate I finally double clicked.
Then I found double clicking with shift worked as expected for me.

**Comment by ryevdokimov** [comment]
Can't replicate in v4.3dev2

**Comment by ryevdokimov** [comment]
That's odd, I quickly glanced at the code and didn't see anything wrong or specific to an OS. I'm on Windows 11 Build 10.0.22631. I can check again.

**Comment by Mickeon** [comment]
What if we replace it outright with a button right in the middle to add both? More accessible?

**Comment by Calinou** [comment]
> What if we replace it outright with a button right in the middle to add both? More accessible?

That could work too, as long as we can fit all 3 buttons without making the UI too large.

**Comment by Mickeon** [comment]
Then it could be called "Add Both" instead of showing the symbol?

**Comment by Calinou** [comment]
> Then it could be called "Add Both" instead of showing the symbol?

Sounds good :slightly_smiling_face:

**Comment by Giganzo** [comment]
It adds both if I first press and hold Left MB, then hold down shift and release mouse button. 

On Windows I can hold down shift and then click on button.
