### ISSUE TITLE
drag gesture scrolls the visual shader editor and drags nodes at the same time

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#73466]
### Godot version

4.0 RC2

### System information

Android 13, Samsung Galaxy 7 FE

### Issue description

I tried to use visual shaders on tablet but when i try to move a block it also scrolls the view. I believe that the 2D editor has the same issue, but i couldn't find it.

### Steps to reproduce

create a visual shader, add a node, drag that node around. Even without any node, if you pan with a single finger it will select and drag the view

### Minimal reproduction project

see above.

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/72385 (same cause, but the fix needed is different).
