### ISSUE TITLE
List selection does not work in 3D editor

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#73473]
### Godot version

4.0 rc2

### System information

Windows 10 x64

### Issue description

https://user-images.githubusercontent.com/2223172/219531151-6d10e5f3-7a35-4457-91f9-68b733b00c3a.mp4

### Steps to reproduce

1. Have 2+ 3D nodes on the scene, overlapping
2. Alt + Right Click them
3. Select a node from the list
4. Does not get selected

### Minimal reproduction project

N/A

**Comment by YuriSizov** [comment]
While testing this, I noticed that if you hover over an option long enough for a tooltip to appear, then that tooltip kind of steals the focus and hover style is no longer updating.
