### ISSUE TITLE
The 'Ctrl+Z' don't cancel the 'Breakpoint' and 'Toggle Bookmark' operations.

### ISSUE THREAD

**Issue by Vilcrow** [godotengine/godot#73481]
### Godot version

4.0 dev_build

### System information

Ubuntu 22.04.1

### Issue description

Possible to cancel the `Indent`, `Unindent`, `Toggle Comment` and other operations with the `Ctrl+Z` or `Redo` help, but it don't works for the `Breakpoint` and `Toggle Bookmark` operations. Should there be such a possibility?

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by MewPurPur** [comment]
It's different because those operations are on the text and these are on the script. But it can be argued that breakpoints and bookmarks should also be in the UndoRedo. No opinion, personally, this never occurs in my workflow.

**Comment by Mickeon** [comment]
Debatable if they should even count, indeed. They do not modify the file in any way. If these should be "undo-able", other operations in the engine (such as expanding/collapsing items) would need to be, as well.

**Comment by Vilcrow** [comment]
There's no need for that. It's different because those operations are on the text and these are on the script.
