### ISSUE TITLE
OpenGL: Crash when changing a LightOccluder2D in an instanced scene

### ISSUE THREAD

**Issue by braem** [godotengine/godot#73487]
### Godot version

4.0 rc1

### System information

Windows 11

### Issue description

Modifying a `LightOccluder2D` in scene 2 that is instanced in scene 1 causes a crash when switching back to scene 1.

### Steps to reproduce

For the minimal reproduction project, simply open `test.tscn` in editor.

For full repro from black project:
1. Create blank scene `test1.tscn`
2. Add a `DirectionalLight2D` and enable shadows on it
3. Create another blank scene `test2.tscn`
4. Instance `test2.tscn` into `test1.tscn`
5. Add a `LightOccluder2D` to `test2.tscn` & draw any occluder polygon
6. Switch back to `test1.tscn`
7. If this doesn't crash, switch back to `test2.tscn` and modify the the occluder polygon a tad
8. Switch back to `test1.tscn`. This should crash.

### Minimal reproduction project

[TestCrash.zip](https://github.com/godotengine/godot/files/10764470/TestCrash.zip)

**Comment by braem** [comment]
Now seeing this within a single scene. I believe the issue is really that modifying an OccluderPolygon in a scene with a light casting shadows results in a crash 100% of the time.
So, modifying one in an isolated scene is fine, but once it's instanced into a scene with lights with shadows, the editor crashes.

**Comment by akien-mga** [comment]
Confirmed on Linux, the GLES3 renderer crashes, possibly from passing invalid elements to draw to the driver?
```
Thread 1 "godot-git" received signal SIGSEGV, Segmentation fault.
(gdb) bt
#0  0x00007ffff7e2a749 in __memmove_avx_unaligned_erms () from /lib64/libc.so.6
#1  0x00007fffea62ea2e in tc_draw_vbo () from /usr/lib64/dri/radeonsi_dri.so
#2  0x00007fffea2daa6b in _mesa_validated_drawrangeelements () from /usr/lib64/dri/radeonsi_dri.so
#3  0x00007fffea2dc192 in _mesa_DrawElements () from /usr/lib64/dri/radeonsi_dri.so
#4  0x0000000006fe5cc9 in RasterizerCanvasGLES3::light_update_directional_shadow (this=0x7fffdc7b7020, p_rid=..., p_shadow_index=0, p_light_xform=..., p_light_mask=1, p_cull_distance=10000, p_clip_rect=..., 
    p_occluders=0xe628cb0) at drivers/gles3/rasterizer_canvas_gles3.cpp:1722
#5  0x0000000009771e5f in RendererViewport::_draw_viewport (this=0xc5193f0, p_viewport=0xde4d960) at servers/rendering/renderer_viewport.cpp:500
#6  0x0000000009773111 in RendererViewport::draw_viewports (this=0xc5193f0) at servers/rendering/renderer_viewport.cpp:727
#7  0x00000000097e36ae in RenderingServerDefault::_draw (this=0xc4e83e0, p_swap_buffers=true, frame_step=0.23047533333333475) at servers/rendering/rendering_server_default.cpp:91
#8  0x00000000097e4f1e in RenderingServerDefault::draw (this=0xc4e83e0, p_swap_buffers=true, frame_step=0.23047533333333475) at servers/rendering/rendering_server_default.cpp:395
#9  0x00000000052a2f67 in Main::iteration () at main/main.cpp:3169
#10 0x00000000052259c6 in OS_LinuxBSD::run (this=0x7fffffffd190) at platform/linuxbsd/os_linuxbsd.cpp:880
#11 0x000000000521ce80 in main (argc=2, argv=0x7fffffffd6f8) at platform/linuxbsd/godot_linuxbsd.cpp:73
```

**Comment by akien-mga** [comment]
This happens with the GL Compatibility renderer (configured in the MRP), but not with Forward+ in my quick testing.
