### ISSUE TITLE
TileSet Alternative transposed tile incorrectly offsets collision shape (and representative tile orange box)

### ISSUE THREAD

**Issue by hsandt** [godotengine/godot#73517]
### Godot version

v4.0.rc2.official [d2699dc7a]

### System information

Linux Ubuntu 20.04 with Unity desktop

### Issue description

While working on Demo Platformer 2D, I noticed that the collision shapes for slope ceiling tiles, which are transposed variants, were completely offset from their definition in red. Below, the blue collision shapes are not matching the red ones at all.

![image](https://user-images.githubusercontent.com/1067772/219743359-35989ea8-de63-4fe4-8956-596ce1baed71.png)

Either the preview for red shape editing is wrong, or the blue collision shape is wrong. When testing in game, the physics seems to correspond to the blue shape, so it's possible that the preview for red shape editing is incorrectly offset.

In addition, the orange box, representing the place in the tilemap where the tile is actually set (only meaningful for tile collection whose Texture Region Size does not match TileMap Tile Size, generally bigger), is also offset from the actual box used for placement.

In the alternative tile view, the representative box (in blue this time) is also oddly represented:
- when moved by at least 1 px horizontally, it disappears (I suspect transposed tiles think it's moving vertically and therefore leaving the expected area, as the bad orange box in the red shape editing area). We can still see the center blue cross though
- when moved to the right edge, it's coonsidered completely out of area so the coords (16, 0) are shown instead (again due to transpose thinking we are moving on Y)

![image](https://user-images.githubusercontent.com/1067772/219744460-3925f8a7-dcb5-44bc-ae0e-4d2fd6a28a47.png)

Compare with a non-transposed tile correctly showing the blue box:

![image](https://user-images.githubusercontent.com/1067772/219745452-9f64b1ad-6825-4b99-90ef-26771f3815ad.png)

### Steps to reproduce

1. Open a tileset with transposed tiles (the demo Platformer 2D is good)
2. Click on Select tab and click on some of the variants, esp. transposed ones (ceiling slopes)
3. Check the Transpose flag, the Texture Origin, and most importantly Physics > Physics Layer 0 > Red collision shape editing area
4. Observe discrepancy between red area and blue area in the preview on the right
5. Repeat with Texture Origin, testing different values to move the orange/blue box near the edges of the big tile
6. Observe discrepancy between orange box and blue box in the preview on the right

### Minimal reproduction project

The Demo Platformer 2D is good, but I can provide minimal project extracting just the tileset if required

**Comment by SingleShot** [comment]
I'm seeing this on 4.0.3.

**Comment by kleonc** [comment]
I'm not sure what's the exact issue being reported in here. Please elaborate. Is it:
1. Incorrect tiles setup specifically in the Platformer 2D demo?
2. Incorrect conversion of the transposed etc. collision shapes when converting from 3.x to 4.0?

Or something else?

And yes, a minimal reproduction project is welcomed (with the steps which led to the specific incorrect setup of the collision shapes).

**Comment by SingleShot** [comment]
Sorry. I'll post a sample today or tomorrow.

**Comment by SingleShot** [comment]
I've attached a sample project. Basically the alternate tile is not centered in the physics layer drawing window. If you draw the physics layer over the tile image, the layer ends up in the wrong location in game. As a workaround, if you instead ignore the actual position of the tile image and draw the layer where it should be (centered in the drawing window) you can sorta of eyeball the correct position. I suspect it's due to using a tile that is not squared.
[sample.zip](https://github.com/godotengine/godot/files/11779513/sample.zip)

![image](https://github.com/godotengine/godot/assets/9001/22de6895-356d-4cc8-a053-d85e51aa25b6)

**Comment by kleonc** [comment]
@SingleShot Thanks! So indeed that's an issue not just about converting from 3.x TileSets, hence reopening.
