### ISSUE TITLE
TileMap button does not appear when TileMap is first clicked, if a custom plugin handles it

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#73533]
### Godot version

4.0 rc2

### System information

Windows 10 x64

### Issue description

Likely caused by #71770 and follow-ups

https://user-images.githubusercontent.com/2223172/219813543-9de517c1-221d-4c11-9624-a4732d14c6d0.mp4

I have a plugin that handles TileMaps. When I first click a TileMap, the TileMap editor does not appear (likely due to my plugin). Subsequent clicks show the editor properly.

It did not happen before. Might apply to other plugins.
It's a minor regression though and I'm opening it mostly to keep track.

### Steps to reproduce

1. Have a plugin that `_handles()` TileMap
2. Click TileMap
3. No TileMaps appear at the bottom
4. Deselect TileMap
5. Click it again

### Minimal reproduction project

[TileMapPluginBug.zip](https://github.com/godotengine/godot/files/10772345/TileMapPluginBug.zip)

**Comment by akien-mga** [comment]
Fixed by #74039.
