### ISSUE TITLE
store_var/get_var not compatible between Godot 3 and Godot 4

### ISSUE THREAD

**Issue by daveTheOldCoder** [godotengine/godot#73530]
### Godot version

4.0.rc2

### System information

n/a

### Issue description

Due to new Variant.Type enums inserted into existing Variant.Type enums, a file containing data written with File.store_var() in Godot 3 may not be read properly with FileAccess.get_var() in Godot 4.

This was reported in the earlier issue 69114. Since that issue contains replies that may cause confusion, I'm creating this new issue to clarify the problem.

In Godot 3, if File.store_var() is used to write a Dictionary, the Variant.Type written to the file is 18 (Variant.Type.TYPE_DICTIONARY).

In Godot 4, if FileAccess.get_var() is used to read the Dictionary, it will fail, since in Godot 4, 18 is Variant.Type.TYPE_TRANSFORM3D, not Variant.Type.TYPE_DICTIONARY.

This can affect data types other than Dictionary. That's only one example.

Godot 3 Variant.Type enums documentation:
https://docs.godotengine.org/en/stable/classes/class_%40globalscope.html#enum-globalscope-variant-type

Godot 4 Variant.Type enums documentation:
https://docs.godotengine.org/en/latest/classes/class_@globalscope.html#enum-globalscope-variant-type

My suggested fix is to move the Variant.Type enums added in Godot 4 to the end, so that the values of the Godot 3 Variant.Type enums are unchanged.

Alternatively, the declaration order of the enums could be kept, but the enums could be assigned numerical values. But I think this would be more error-prone.  

This is a list of the files that require changing. I don't know if this list is complete.
https://github.com/godotengine/godot/blob/master/core/extension/gdextension_interface.h
https://github.com/godotengine/godot/blob/master/doc/classes/%40GlobalScope.xml
https://github.com/godotengine/godot-docs/blob/master/classes/class_%40globalscope.rst

### Steps to reproduce

n/a

### Minimal reproduction project

n/a

**Comment by akien-mga** [comment]
This is not going to change, Godot 4.0 is expected to break compatibility, and does on pretty much all accounts. Opening binary files saved in 3.x with Godot 4.0 is not supported.

Reordering the Variant types now would break compatibility for all Godot 4.0 users, which is not an option.

If you need to load Godot 3.x data, I can think of two options:
- Make an intermediate tool with Godot 3.x that can load your data and convert it to a different format (e.g. JSON).
- Write a custom binary loader for Godot 4.x that can remap the 3.x enum values to 4.x Variants.

**Comment by daveTheOldCoder** [comment]
> * Write a custom binary loader for Godot 4.x that can remap the 3.x enum values to 4.x Variants.

My new addon uses this method to solve this issue.
[Godot3To4FileConversion](https://godotengine.org/asset-library/asset/2307)

**Comment by AThousandShips** [comment]
You can't transfer RIDs, they shouldn't be stored in the first place, so that's not a limitation, they aren't persistent across runs
