### ISSUE TITLE
Crash when using export keyword incorrectly

### ISSUE THREAD

**Issue by ferreiradaselva** [godotengine/godot#7353]
OS: Linux, 64-bit
Godot: 2.1 stable

Using the following code will result in a crash (but only when the Inspector tab is visible for that specific node):
```
export var My_Var = Area2D
```
The expected result would be an error message, explaining that you can't assign a node type as value.

My bet: the error must be in somewhere in the code of the Inspector, because it only occurs when the Inspector is visible. The inspector will try to add the exported variable in the Script Variables and will fail there.

**Comment by bojidar-bg** [comment]
Note that `Area2D` is of type `GDNativeClass` -> `Object` (-> `Variant`), so, it shouldn't be exportable __at all__

**Comment by bojidar-bg** [comment]
Somewhat related to #6987

**Comment by felipefs** [comment]
Yup, I know. I was learning how to use export when I detected the bug. In anyway, it's a better behavior to just report an error. The same goes to other unexportable types.

**Comment by xyroclast** [comment]
A crash should never be the result for anything, no matter how illogical :)

**Comment by hpvb** [comment]
I believe this is fixed now. Can you try again?
