### ISSUE TITLE
Vector2 division breaks the editor

### ISSUE THREAD

**Issue by jeff-s-zhou** [godotengine/godot#7354]
**Operating system or device - Godot version:**
2.2.1

**Issue description** (what happened, and what was expected):
Typing out Vector2 division immediately crashes the editor, and opening the project afterwards causes the editor to immediately crash again until you remove the line using some other method.

**Steps to reproduce:**
I wrote this line in the _ready call of an otherwise empty script in an empty scene.

Vector2(5, 0)/Vector2(1, 0)

**Comment by RebelliousX** [comment]
It is supposed to crash! In fact, I crashed trying to think about it, lol. There is no such thing as vector division. Vectors have sum, subtraction and 2 types of multiplication scalar (result is not a vector, just a number, a.k.a dot product) and cross product (result is a vector, which has many useful applications, determining if a vector is perpendicular to another is one of them).


This is not a bug, although, it should give a big fat error, not crashing the whole editor. Adding some exception for such expression would do it.

**Comment by jeff-s-zhou** [comment]
I'm not sure I was clear here. I didn't RUN the script, and in fact the specific line was actually just an in between step as I was rewriting the code. 

Just writing the line at all causes the editor to crash and to crash every time the project is opened.

**Comment by Zylann** [comment]
Vector division is fine, it's just the same logic as member-wise operation as with add, multiply and subtract.
And as such, it also implies handling divide-by-zero cases.

**Comment by Zylann** [comment]
I found that if you have a constant that is NaN, the GDScript parser will silently put it as key of `constants_map`. However, `NaN == NaN` returns `false`, which probably makes dictionary lookup to fail all the times (because the key is compared for equality once found through the hash) and return null anyways. It probably messes up earlier because of this :s

**Comment by Zylann** [comment]
Hmmm that fix isn't what I expected, and it makes comparisons slower (and I'm sure you can still inject NaNs :p)... but if @reduz thinks it's better... :)

**Comment by reduz** [comment]
So far it's just for gdscript, so should be hopefully ok

**Comment by akien-mga** [comment]
Reopening as #7807 was reverted (better fix incoming, @hpvb and @tagcup are on it :D).
