### ISSUE TITLE
Create Script Dialog is bigger then my screen

### ISSUE THREAD

**Issue by mio991** [godotengine/godot#73549]
### Godot version

v4.0.rc2.mono.official [d2699dc7a]

### System information

Windows 10

### Issue description

I created a new Project an the wanted to create a script. 
The create dialog extends above and Below my screen.
![grafik](https://user-images.githubusercontent.com/6023976/219855184-6a70fc21-539a-4f21-a558-5c4aa7e9a5ae.png)

I have an 2560x1440 Screen.

### Steps to reproduce

1. Create a new Project
2. Create a new Scene with a spatial node for example
3. add a new script to the node

### Minimal reproduction project

N/A

**Comment by YuriSizov** [comment]
This is probably fixed in master after the label sizing or popup center changes. Should retest after RC3.

**Comment by KoBeWi** [comment]
@mio991 rc3 is out, please re-check if the issue still happens.

**Comment by mio991** [comment]
Seems fine now.
