### ISSUE TITLE
In-editor help page for Vector2 does no longer underline some outgoing links

### ISSUE THREAD

**Issue by HerrSersch** [godotengine/godot#73551]
### Godot version

4.0 RC2, was working in 4.0 RC1

### System information

Windows 10

### Issue description

Since Godot 4.0 RC2, there's an outgoing link inside the Vector2's help page that is no longer underlined (but still clickable).

![vector2_rc1_vs_rc2](https://user-images.githubusercontent.com/35151158/219856316-8b5328ca-cd5f-470b-b39b-69569dd8abc9.png)

Other outgoing links, like the ones at the very beginning of the page, are underlined. There's a link on the Vector3 page inside the explanation for bezier_interpolate() which is underlined as well. The class_vector2.rst file hasn't changed since RC1.

Maybe this has something to do with the link's target, which is a .png file? Could this problem be a result of the recent font and theming changes in #73106?

EDIT: The problem was indeed introduced in this commit 0eb3b49c3997dd27781428fa9925b25aec5ea046

### Steps to reproduce

1. Open the in-editor help page for Vector2
2. Search for "Illustration" and observe that the linked text is clickable but not underlined

### Minimal reproduction project

N/A

**Comment by HerrSersch** [comment]
I've narrowed the problem down a bit, it was caused by this commit: 0eb3b49c3997dd27781428fa9925b25aec5ea046

**Comment by HerrSersch** [comment]
The problem seems to be caused by the Display Scale. The underline reappears when I set the Display Scale to any other preset than 100% or use a custom value like 0.99 or 1.05.

**Comment by YuriSizov** [comment]
Thanks for your thorough research. It's not directly caused by the linked commit, but it did expose the problem. If you change the font size to a different value, you can also see the underline reappear, for example. So a naive and most straight-forward solution would be to round the underline size to be at least 1 pixel thick.
