### ISSUE TITLE
Visibility Notifier: "Timer was not added to the SeneTree [...]"

### ISSUE THREAD

**Issue by Eerywax** [godotengine/godot#73567]
### Godot version

3.5.1 stable

### System information

Windows 10

### Issue description

related to:
[33929](url=https://github.com/godotengine/godot/issues/33929)
[32366](url=https://github.com/godotengine/godot/issues/32366)

I am using VisibilityNotifiers to destroy projectiles that go off-screen. However, I want there to be a grace period where, if the player "catches up" somehow, the bullet isn't gone as soon as it's off-screen. I added a timer that starts when off-screen, and then finalizes the object freeing on timeout.

Everything works at runtime, but upon closing the game, errors pop up - one per projectile.
"E 0:00:05.528   start: Timer was not added to the SceneTree. Either add it or set autostart to true.
  <C++ Error>   Condition "!is_inside_tree()" is true.
  <C++ Source>  scene/main/timer.cpp:108 @ start()
  <Stack Trace> OffScreenCleanup.gd:14 @ on_screen_exited()"
  
This us a use-case where I do not want autostart to true, I want the timer to start when it exits the screen, so the message does not address this.

Insofar as, watching the Remote tree, everything is working and being freed as intended, it's either not a real error, or not one I understand. I'm not sure what's going on behind the scenes enough to suggest an alternative, other than to account for this type of case somehow.

### Steps to reproduce

In the project below, press Space to fire. Everything goes fine, until you close the project - then the errors pop up.

### Minimal reproduction project

[VisibilityNotifierMinimal.zip](https://github.com/godotengine/godot/files/10775117/VisibilityNotifierMinimal.zip)

**Comment by KoBeWi** [comment]
I don't see any error in the MRP.

**Comment by KoBeWi** [comment]
The error is correct. When you close the project, the bullet exits scene tree, so the notifier exits the screen. But the signal is emitted while it's already outside scene tree and it tries to start the timer.

The error does not happen if you use `CONNECT_DEFERRED` for your "screen_exited".

**Comment by Eerywax** [comment]
That makes sense, thanks for explaining where it's coming from! I'll keep the CONNECT_DEFERRED in mind as well.

**Comment by Eerywax** [comment]
Giving this a nudge just because, as far as I could find, this is the correct implementation of CONNECT_DEFERRED:
```timer.connect("timeout", self, "on_timer_timeout", [], CONNECT_DEFERRED)```
...but the errors still crop up when closing the project. For reference, ```on_timer_timeout``` refers to this:
```func on_timer_timeout() -> void:
	get_parent().queue_free()```
I've tried adding ```| CONNECT_ONESHOT``` to no avail, as well as call-deferred-ing the queue_free(), and the errors persist.

**Comment by KoBeWi** [comment]
I tested this in Godot 4 and there is no error (even without `CONNECT_DEFERRED`).

In Godot 3 there are errors even with `CONNECT_DEFERRED` (I don't know how I was testing before, but it doesn't seem to help 🙃). You can add this to your `on_screen_exited()`:
```GDScript
if not is_inside_tree():
    return
```

**Comment by Eerywax** [comment]
I'll add that, thanks!
