### ISSUE TITLE
4.0 rc 2.0 project setting tools C sharp freezes program.

### ISSUE THREAD

**Issue by Devilsclaw-sudo** [godotengine/godot#73568]
### Godot version

4.0 rc 2.0 

### System information

Windows 11

### Issue description

If you open the setting make Csharp solution in the project menu and press it, the menu item dissapears and becomes really small

### Steps to reproduce

1. Work with the engine like normal
2. Open the project settings menu from the top menu bar, and go to create C sharp solution
3. Menu item dissapears and you get a very small empty window
### Minimal reproduction project

Program unpredictably freezes sometimes with second monitor plugged in when going to the menu, but without second monitor it doesn't freeze if I go to this setting.

NA

**Comment by arisvaldez** [comment]
hi @Devilsclaw-sudo , 
Can you put a ScreenShot?
do you use a Dedicate Graphics Video Card?, Which one,?
is updated you graphics video card driver?
Laptop or Desktop?
do you use a secondary Monitor?
Do you know which render the engine uses? forward+ or compatibility?

Sorry for the many questions, but it's to find the problem faster .

**Comment by Devilsclaw-sudo** [comment]
![Screenshot 2023-02-20 163248](https://user-images.githubusercontent.com/123577338/220148621-188f2882-3b0c-47c5-9fa3-09e87b788d3c.jpg)


I use a desktop with AMD 5700XT with a 3600X CPU on a B450 motherboard
This program freeze seems to be caused by a second monitor, but the build tool button disappears regardless if a second monitor is plugged in. I use the forward+ engine (default).

**Comment by akien-mga** [comment]
CC @godotengine/dotnet

**Comment by raulsntos** [comment]
These seem like 2 separate issues:

> If you open the setting make Csharp solution in the project menu and press it, the menu item dissapears and becomes really small

This should be only a visual issue, the menu only has one option (to generate the C# solution) so when a solution already exists it disappears which leaves the menu empty. It's already reported in https://github.com/godotengine/godot/issues/60940.

> Program unpredictably freezes sometimes with second monitor plugged in when going to the menu, but without second monitor it doesn't freeze if I go to this setting.

This doesn't seem related to .NET, more likely a rendering issue. Maybe it's an issue with your GPU drivers? I can't really help with this.

**Comment by Devilsclaw-sudo** [comment]
OK I didnt saw that it was reported in another topic, I will close it.
