### ISSUE TITLE
FastNoiseLite does not work in 3d

### ISSUE THREAD

**Issue by Cheesy-Brik** [godotengine/godot#73574]
### Godot version

4,0 dev

### System information

Windows 10

### Issue description

When trying to use FastNoiseLite it is just returning 0's

### Steps to reproduce

Code:
```
func _ready():
	noise.seed = randi()
	noise.noise_type = FastNoiseLite.TYPE_PERLIN
	print(noise.get_noise_2d(position.x, position.z))
```

### Minimal reproduction project

[proj.zip](https://github.com/godotengine/godot/files/10775682/proj.zip)

**Comment by Calinou** [comment]
@Cheesy-Brik Did you find a solution to this problem? If so, please document it here by commenting :slightly_smiling_face:
