### ISSUE TITLE
[FIXED in master] [Godot 4 RC2] Directional shadow twitches when the camera moves

### ISSUE THREAD

**Issue by unfa** [godotengine/godot#73572]
### Godot version

4.0 RC2

### System information

Arch Linux + X11+ KDE Plasma + Radeon RX6800XT

### Issue description

I've tested and it does not happen in RC1 - this is clearly a regression in RC2.

Demonstration in RC2:
https://youtu.be/7RK0D4woyMI

In RC1 there is no such issue:
https://youtu.be/Jl5q6M_i2Ao

### Steps to reproduce

Probably just use a directional light I guess?

### Minimal reproduction project
[Twitching Shadows.zip](https://github.com/godotengine/godot/files/10788214/Twitching.Shadows.zip)

**Comment by akien-mga** [comment]
What do you mean by "FIXED in master"?

**Comment by Calinou** [comment]
@unfa Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

Also, check if this only occurs when the light's angular distance is greater than 0 (PCSS-style shadows).

**Comment by unfa** [comment]
@akien-mga That means me building Godot from git after the RC2 release doesn't show this problem. I assume it was a mistake that was noticed and promptly fixed after the RC2 release. I decided to still post the issue in case it's not that simple.

@Calinou Ok, I'll try to do that.

**Comment by unfa** [comment]
Here's an MRP:
[Twitching Shadows.zip](https://github.com/godotengine/godot/files/10788214/Twitching.Shadows.zip)

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/59232.

**Comment by unfa** [comment]
Thanks!

**Comment by akien-mga** [comment]
What about the comment that it's fixed in master? Is #59232 too?

**Comment by unfa** [comment]
I didn't test that one.

**Comment by akien-mga** [comment]
I tested and the MRP from https://github.com/godotengine/godot/issues/73572#issuecomment-1437643757 does reproduce the bug, so it doesn't appear to be fixed (and thus can indeed be a duplicate of #59232).
