### ISSUE TITLE
[.NET] [VSCode] VSCode is not reporting specific errors which are likely added in Godot4

### ISSUE THREAD

**Issue by Hamster5295** [godotengine/godot#73575]
### Godot version

4.0-rc2

### System information

Windows 11, NVIDIA GeForce RTX 2050

### Issue description

I'm using C# with Godot 4.0-rc2.
I've written code as below: 
![image](https://user-images.githubusercontent.com/37259613/219920391-294f6369-68cd-4d9f-a000-cccfdca05c47.png)
And there's no error shown in the VSCode editor.
I'm quite sure the environment is correctly set as it worked fluently when I was using Godot 3.x. Here are my extensions: 
![image](https://user-images.githubusercontent.com/37259613/219920839-dc1ea60a-4520-41f1-b097-cea80cc285de.png)  

But in Godot 4, I get errors when building the code above. Here is the log: 
![image](https://user-images.githubusercontent.com/37259613/219921016-0475f02a-5dac-4e9d-b8a0-bba39228db4f.png)
It seems that these errors are not captured in the VSCode. Maybe it's related to the "C# Tools for Godot" extension, which is in need of update. 🍰 

### Steps to reproduce

1. Create a Godot 4 project.
2. Create a C# script.
3. Use Vscode to edit it, inputing the content below:
```C#
using Godot;
using Godot.Collections;

public class Example<K, V> : Node
{
    public Dictionary<K, V> dict;
}
```
4. Build the project.

If the problem exists, you'll find there's no error hints in VSCode, but the building process in Godot fails.

### Minimal reproduction project

[Report.zip](https://github.com/godotengine/godot/files/10775921/Report.zip)

**Comment by YuriSizov** [comment]
Well, the errors are correct as far as I can tell. As for not showing in the external editor, that is probably not related to this repository, but pinging @godotengine/dotnet to be sure.

**Comment by raulsntos** [comment]
We are aware that some IDEs may not show diagnostics reported from source generators, reporting from analyzers seems to work fine though.

There's not much we can do here, as far as I know IDEs already have all the information necessary to show the diagnostics inline and I think Visual Studio 2022 already does. So I would open an issue on the [VSCode omnisharp](https://github.com/OmniSharp/omnisharp-vscode) repository.
