### ISSUE TITLE
`--display-driver opengl3` does not work as described in `--help`

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#73581]
### Godot version

v4.0.rc2.official [d2699dc7a]

### System information

ALL

### Issue description

I try to get my CI WF running with opengl3 support but it fails when using the option `--display-driver` as described in the `--help`

` --display-driver <driver>         Display driver (and rendering driver) ['windows' ('vulkan', 'opengl3'), 'headless' ('dummy')]`

maybe i understand it wrong and it means use `windows` is supports 'vulkan' or 'opengl3

when using `opengl3` it fails with an error
%GODOT_BIN% --display-driver opengl3

```
Unknown display driver 'opengl3', aborting.
Valid options are 'windows' and 'headless'.
```

### Steps to reproduce

open a console and see the error

`%GODOT_BIN% --display-driver opengl3`

Windows:
`Valid options are 'windows' and 'headless'.`
Unix:
`Valid options are 'x11' and 'headless'.`

### Minimal reproduction project

N/A

**Comment by bruvzg** [comment]
It's `--rendering-driver opengl3`, display driver is for selecting window manager backend.

**Comment by MikeSchulze** [comment]
you can close as clarified ;)
