### ISSUE TITLE
Getting a triangle based collision shape to go around a mesh

### ISSUE THREAD

**Issue by ComradeKeys** [godotengine/godot#7359]
**Operating system or device - Godot version:**
Fedora 25 using Godot 2.1.1

**Issue description** (what happened, and what was expected):
I am trying to get some triangle based collision shapes to go around my mesh, and I cannot seem to find a documented way to do this or fabricate it myself. Is this a current or planned feature in Godot? Triangle based collision shapes should be a must for the vast majority of 3D games. 

**Steps to reproduce:**
Should be simple as adding
>Rigid Body
>>Collision Shape
>>MeshInstance

**Link to minimal example project** (optional but very welcome):
https://notabug.org/bkeys/Godot_Test

**Comment by Jerome67000** [comment]
Hi,

I think that's what you're looking for, this button is a little bit lost :

![image](https://cloud.githubusercontent.com/assets/7358899/21459894/fc31925a-c942-11e6-8809-35685329f1f0.png)

How to use :
* Select a MeshInstance
* Mesh > Create trimesh static body

note: the trimesh CollisionShape dont appear in the editor (maybe it's a bug for now), but you can see it when you run the game with the **Visible collision shapes** debug option :
![image](https://cloud.githubusercontent.com/assets/7358899/21459969/a4725ea4-c943-11e6-9236-9366e1a38c21.png)

**Comment by ComradeKeys** [comment]
Alright thank you, this solved the problem I was trying to solve.
