### ISSUE TITLE
Godot4.0rc2 editor node rename can not use input method

### ISSUE THREAD

**Issue by HackLinjiuyue** [godotengine/godot#73591]
### Godot version

4.0rc2

### System information

Windows10 Vulkan API 1.2.194 - Forward Mobile - Using Vulkan Device #0: Intel - Intel(R) Iris(R) Xe Graphics

### Issue description

Same as title.

### Steps to reproduce

just normal rename steps and activate input method (from my situation is microsoft Pinyin for Chinese input).

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
What is the problem? What are the steps to reproduce it? This tells us nothing

**Comment by HackLinjiuyue** [comment]
> What is the problem? What are the steps to reproduce it? This tells us nothing

The problem is the same as title, just normal rename steps and activate input method (from my situation is microsoft Pinyin for Chinese input).

**Comment by Zireael07** [comment]
@HackLinjiuyue Put the contents of your comment above in "steps to reproduce", thanks

**Comment by HackLinjiuyue** [comment]
> @HackLinjiuyue Put the contents of your comment above in "steps to reproduce", thanks

I already done that now.

**Comment by pepsiandmilk** [comment]
Works for me on Linux with `ibus-libpinyin`
![demo](https://imgur.com/CD1Dwgg.gif)

**Comment by erasin** [comment]
The same error occurs on macos systems. When renaming nodes, they cannot be entered using the default system input method or any other input method. The `filter nodes` above works fine.

https://user-images.githubusercontent.com/716514/221741404-8a96aaa0-227a-4cfd-a8ca-cca4c44deab7.mov

**Comment by 011eh** [comment]
It is highly possible that there is an error occurring in the interaction between Godot and Microsoft Pinyin

**Comment by AThousandShips** [comment]
Is this still reproducible in 4.0.1?

**Comment by erasin** [comment]
> Is this still reproducible in 4.0.1?

Yes, it still in godot v4.0.1.rc2.official [6970257cf] (macos)
