### ISSUE TITLE
Running a game crashes godot

### ISSUE THREAD

**Issue by cube-logic** [godotengine/godot#73596]
### Godot version

4.0 rc2

### System information

Windows 11, RTX 4070 Ti, Forward+

### Issue description

This is a really weird issue that I couldn't figure out it's cause
Sometimes when I run the project (any project) 2 windows appear, one is the game and the other is a blank window
![image](https://user-images.githubusercontent.com/85768334/219972223-55076f7d-19b2-42be-8a37-c5f9da1e19f5.png)
If you click any of the windows godot stops responding and crashes
Since the release of rc2 it happened to me at least 3 times
I'm sorry that I open a vague issue without really much explanation of how it happens, I'm trying to figure it out myself and it doesn't have any repeating pattern that causes it.

### Steps to reproduce

Any game (I made a platformer one) with just the movement and camera

### Minimal reproduction project

Any game (I made a platformer one) with just the movement and camera

**Comment by YuriSizov** [comment]
> Any game (I made a platformer one) with just the movement and camera

Please, provide an actual MRP.

**Comment by cube-logic** [comment]
Forgot to close the issue, fixed in later versions of godot
