### ISSUE TITLE
Possible bug when accessing child node during get and set on "tool" script

### ISSUE THREAD

**Issue by telmotrooper** [godotengine/godot#73599]
### Godot version

4.0.rc2.official [d2699dc]

### System information

Arch Linux

### Issue description

When writing a `tool` script in Godot 4 and accessing a child node in `get` or `set`, if I don't check whether the child node is a valid instance, I get a null instance error:
```
Invalid get index 'text' (on base: 'null instance').
```

Relevant example in Godot 4:

![image](https://user-images.githubusercontent.com/9438853/219973636-12ef5f6d-f744-486a-b8f9-ed6a7169bc70.png)

```
@tool
extends Button

@export var button_text : String : get = get_button_text, set = set_button_text

func get_button_text() -> String:
  return $Label.text

func set_button_text(new_text) -> void:
  $Label.text = new_text
```

This behavior did not happen in Godot 3, which leads me to think it might be a bug (please correct me if this is now intended behavior).

Working code in Godot 3:
```
tool
extends Button

var button_text setget set_button_text, get_button_text

func get_button_text() -> String:
  return $Label.text

func set_button_text(value: String) -> void:
  $Label.text = value
```

I've attached a file with two minimal examples, one in Godot 3 and one in Godot 4 to illustrate.

### Steps to reproduce

Just run the provided minimal projects.

### Minimal reproduction project

[new_projects.zip](https://github.com/godotengine/godot/files/10777889/new_projects.zip)

**Comment by KoBeWi** [comment]
Your Godot 3 project is different.
The variable is missing `export` and a value. There is the same error when you change that. Setters are called before node is inside tree, so the hierarchy is not initialized yet.

**Comment by telmotrooper** [comment]
@KoBeWi If you may, if the hierarchy is not initialized yet when calling setters, what is considered good practice when we want to export children properties?

**Comment by KoBeWi** [comment]
There isn't one AFAIK. There is a proposal to support it properly: https://github.com/godotengine/godot-proposals/issues/325

For now you can use this workaround:
```GDScript
func set_button_text(new_text) -> void:
    if not is_inside_tree():
        await ready
    $Label.text = new_text
```

**Comment by telmotrooper** [comment]
Thank you.
