### ISSUE TITLE
Unique Name fails on duplicated node

### ISSUE THREAD

**Issue by 20milliliter** [godotengine/godot#73609]
### Godot version

4.0.rc2

### System information

Windows 10

### Issue description

A duplicated node fails to access uniquely named nodes, instead returning `null`.

Possible duplicate (haha) of #70531 ?

### To reproduce:

1. Open the included project
2. Run SCENE.tscn

### What happens:

1. CHILD's `ready()` function prints PARENT, obtained via `%PARENT`
2. PARENT's `ready()` function creates a new child as a copy of the existing CHILD
3. *that* CHILD's `ready()` function executes, but now fails to obtain the PARENT, printing `null`

### Minimal reproduction project

[Bug.zip](https://github.com/godotengine/godot/files/10778855/Bug.zip)

**Comment by dalexeev** [comment]
This is expected. When creating a node at runtime in general, and when duplicating in particular, the new node does not automatically set the `owner` property. And Scene Unique Names is for the same `owner`.

Scene Unique Names are not intended to be used with nodes or in nodes added at runtime.

**Comment by 20milliliter** [comment]
The Unique Name's [documentation page](https://docs.godotengine.org/en/latest/tutorials/scripting/scene_unique_nodes.html) should be changed to make that clear, then.

**Comment by dalexeev** [comment]
> The Unique Name's [documentation page](https://docs.godotengine.org/en/latest/tutorials/scripting/scene_unique_nodes.html) should be changed to make that clear, then.

See godotengine/godot-docs#6670.

**Comment by YuriSizov** [comment]
Resolved by https://github.com/godotengine/godot-docs/pull/6670.
