### ISSUE TITLE
Node Name cut-off in Inspector View

### ISSUE THREAD

**Issue by rm-code** [godotengine/godot#73600]
### Godot version

4.0.rc2.mono

### System information

macOS 12.0.1

### Issue description

The node name is cut-off in the inspector view currently:

<img width="347" alt="Bildschirmfoto 2023-02-19 um 22 18 40" src="https://user-images.githubusercontent.com/11627131/219975803-2c6eb253-eb0c-4855-8fc8-10dde539f54a.png">
<img width="341" alt="Bildschirmfoto 2023-02-19 um 22 18 00" src="https://user-images.githubusercontent.com/11627131/219975767-410555f9-2599-43b0-9143-4bb5481711fd.png">

This happens for all nodes as far as I can tell.

### Steps to reproduce

1. Create new project
2. Add Node2d
3. Check Inspector view
<img width="281" alt="Bildschirmfoto 2023-02-19 um 22 21 18" src="https://user-images.githubusercontent.com/11627131/219975942-dbc7d71c-2377-4ca0-9f29-bebc755987e7.png">

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
This may be fixed in the master branch already, need testing to confirm.

**Comment by rm-code** [comment]
Additional information: This seems to be an issue with shorter names. Long names are abbreviated correctly with ellipses:
<img width="284" alt="Bildschirmfoto 2023-02-19 um 22 39 10" src="https://user-images.githubusercontent.com/11627131/219976844-710cb809-0de8-4e3e-b0f4-351fcd08c4c4.png">

**Comment by KoBeWi** [comment]
Fixed on master.
