### ISSUE TITLE
SceneTreeTimer time_left property goes into negative values

### ISSUE THREAD

**Issue by Wichamir** [godotengine/godot#73607]
### Godot version

4.0.rc1

### System information

Linux Mint 21.1

### Issue description

When `SceneTreeTimer` is created using get_tree().create_timer(), it doesn't stop at `time_left = 0.0`, but goes into negative values. Normal `Timer` stops at exactly `0.0`, so I expected `SceneTreeTimer` to be the same.

### Steps to reproduce

1. Create an empty scene with one node.
2. Attach this script:
```gdscript
extends Node


var timer: SceneTreeTimer


func _ready() -> void:
	timer = get_tree().create_timer(1.0)


func _process(delta: float) -> void:
	assert(
		timer.time_left >= .0,
		"time_left: %f" % [timer.time_left] # time_left is negative
	)
```
3. Run.

### Minimal reproduction project

N/A

**Comment by chutchinson** [comment]
I can't speak to the intended behavior, but my opinion would be that as a user I would also expect this timer to behave similarly to the **Timer** node in one-shot mode, which is to say that **time_left** is 0.0 when the timer has triggered and there is no time remaining. 

Clamping to 0.0 can be useful for animation / drawing, in the sense that you can be assured the timer will not become negative and say, make it potentially frustrating to animate / scale / etc. a progress bar or similar element.
