### ISSUE TITLE
tts_stop freezes Godot under Godot 4 on Linux

### ISSUE THREAD

**Issue by nightblade9** [godotengine/godot#73605]
### Godot version

- 4.0 RC2 (.NET) x64 official binaries 
- 4.0 RC1 (.NET) x64 official binaries

### System information

Manjaro (Arch) with KDE Plasma.

### Issue description

Calling `DisplayServer.tts_stop` freezes Godot. None of the subsequent actions (e.g. `print` or `tts_speak`) execute.

TTS works. I have installed `spd-say`, `festival`, and `espeakup`. Running `spd-say Hello, world!` on the console speaks the intended output.

It doesn't look like a regression per-se; RC1 and RC2 both behave the same.

On the other hand, it seems to work on Windows 10. I suspect that it's system-specific; perhaps I'm missing some pre-requisites or other libraries related to TTS?

### Steps to reproduce

- Get a voice for TTS
- Call `DisplayServer.tts_speak(long_ramble, _voice["id")`
- Call `DisplayServer.tts_stop()` while the speech is still in progress

Expected: speech stops and the game continues
Actual: speech stops and the game freezes

### Minimal reproduction project

[tts-stop-bug.zip](https://github.com/godotengine/godot/files/10778085/tts-stop-bug.zip)

- Click the first button
- Click the second button

**Comment by akien-mga** [comment]
Yes, this one will be in RC3.

**Comment by nightblade9** [comment]
Verified on my end. Thank you @bruvzg and @akien-mga !
