### ISSUE TITLE
History mismatch when editing tile source properties

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#73603]
### Godot version

4.0 9f68d06

### System information

Windows 10 x64

### Issue description

When changing any property of tile source, e.g. name:
![image](https://user-images.githubusercontent.com/2223172/219977766-9babbd6c-cd75-41a0-a167-fe6da039d05e.png)
This error appears in the output:
```
UndoRedo history mismatch: expected 0, got 2.
Set name
```
It means that there is an undo action that starts with a global object and continues with a scene one.

Only happens when the TileSet is built-in and it makes the changes to the tileset being registered as global, i.e. not related to its scene (which results in history inconsistency after closing the scene).

I did some debugging and the action comes from inspector, which edits TileSetAtlasSourceEditor and then TileSetAtlasSource. I don't know what exactly triggers it; the properties should be only set on TileSetAtlasSource.

### Steps to reproduce

1. Add scene
2. Add tilemap
3. Add tileset (don't save it to a file)
4. Edit tileset
5. Add atlas source (e.g. drop icon.svg)
6. Change atlas name
7. Observe output

### Minimal reproduction project

N/A

**Comment by groud** [comment]
Related to https://github.com/godotengine/godot/issues/74594

**Comment by Rindbee** [comment]
At present, it seems that the operations on objects of node and resource types are regarded as scenes (case 1), and the operations on other types of objects are regarded as global (case 2).

https://github.com/godotengine/godot/blob/c83f912bcb33d441b90afe36bad38880acbe5f15/editor/editor_undo_redo_manager.cpp#L96-L102

For the example in this issue (for action "Set ..."), the operation is from an object of `TileSetAtlasSourceProxyObject` (case 2) to an object of type `TileSetAtlasSource` (case 1).

https://github.com/godotengine/godot/blob/c83f912bcb33d441b90afe36bad38880acbe5f15/editor/editor_inspector.cpp#L3662-L3663
https://github.com/godotengine/godot/blob/c83f912bcb33d441b90afe36bad38880acbe5f15/editor/plugins/tiles/tile_set_atlas_source_editor.cpp#L2159
https://github.com/godotengine/godot/blob/c83f912bcb33d441b90afe36bad38880acbe5f15/editor/plugins/tiles/tile_set_atlas_source_editor.cpp#L2183

For action "Add atlas source", it is also possible to get this error message here:

If you add `TileMap` and `TileSet` to a new scene, save the scene, and then execute the Add atlas source operation, you will also get this error message.


https://github.com/godotengine/godot/blob/c83f912bcb33d441b90afe36bad38880acbe5f15/editor/plugins/tiles/tile_set_editor.cpp#L287

https://github.com/godotengine/godot/blob/c83f912bcb33d441b90afe36bad38880acbe5f15/editor/editor_undo_redo_manager.cpp#L88


https://github.com/godotengine/godot/blob/c83f912bcb33d441b90afe36bad38880acbe5f15/editor/editor_data.cpp#L424-L431

It seems that the path of `EditedScene` is not updated when saving the scene.

**Comment by Rindbee** [comment]
Steps to reproduce the case of action "Add atlas source":
1. Create a new scene;
2. Add a TileMap;
3. Add a TileSet;
4. Open the TileSet editor, add an Atlas, no error.
5. Save the scene;
6. Add a new Atlas again.


https://github.com/godotengine/godot/assets/30386067/08c63e3f-c4ca-4134-8ef1-f4816e2e1e07
