### ISSUE TITLE
Windows 11 shader artifacts

### ISSUE THREAD

**Issue by theromis** [godotengine/godot#73619]
### Godot version

4.0.rc2

### System information

Windows 11

### Issue description

Getting artifacts on test scene in Windows 11 (MacOS works fine)
![Screenshot 2023-02-20 090401](https://user-images.githubusercontent.com/3720229/220060971-c4470cdc-ba69-4687-adae-c9c55375bda8.jpg)
in shell can see some errors
![Screenshot 2023-02-20 085401](https://user-images.githubusercontent.com/3720229/220061132-5bcd67b9-fb86-4603-a0ea-f5c4676144c6.jpg)
Attaching example project.

### Steps to reproduce

Just open test project on windows 11

Shader code:
```
shader_type spatial;
render_mode unshaded;

uniform float size: hint_range(0.001, 0.1) = 0.01;
uniform float line_thickness: hint_range(0.001, 0.1) = 0.01;
uniform vec4 color : source_color = vec4(1, 1, 1, 1);

float grid(vec2 r) {
    float result;

    for (float i = 0.0; i <= 1.0; i += size) {
        for (int j = 0; j < 2; j++) {
            result += 1.0 - smoothstep(0.0, line_thickness, abs(r[j] - i));
        }
    }

    return result;
}

void fragment() {
    vec4 gridColour = color * grid(UV);
	ALBEDO = gridColour.rgb;
}
```

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/10782535/Test.zip)

**Comment by JonqsGames** [comment]
This seems to fix the issue :
```
    float result = 0.0;
````
I think declaring `float` without initliazing is dangerous not sure if the behaviour should be to have 0.0 by default

**Comment by theromis** [comment]
@JonqsGames thanks, it fixed an issue, my bad, thought some horrible glitch in godot :)
btw: same "feature" on iOS

**Comment by Calinou** [comment]
Declaring a variable without initializing it is undefined behavior in GLSL (like in C/C++), so that's expected.
