### ISSUE TITLE
Input.warp_mouse(Vector2.ZERO) moves to (0,-1) on Mac

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#73618]
### Godot version

v4.0.rc2.official [d2699dc7a]

### System information

MacOS Big Sure 11.3

### Issue description

I do testing my scene runner implementation with GdUnit4.
The scene runner moves the mouse pos initial to (0,0) by using `Input.warp_mouse(Vector2.ZERO)`
It works on linux and windows but fails on MacOS.

### Steps to reproduce

create a new script and put into.

```gdscript
func _ready():
	# we need to set inital a valid window otherwise the warp_mouse() is not handled
	DisplayServer.window_set_mode(DisplayServer.WINDOW_MODE_WINDOWED)
	# set inital mouse pos to 0,0
	var max_iteration_to_wait = 0
	while get_global_mouse_position() != Vector2.ZERO and max_iteration_to_wait < 100:
		prints(get_global_mouse_position())
		Input.warp_mouse(Vector2.ZERO)
		max_iteration_to_wait += 1

```
Results into
```
(-487, -209)
(0, -1)
(0, -1)
(0, -1)
(0, -1)
(0, -1)
(0, -1)
(0, -1)
(0, -1)
(0, -1)
(0, -1)
...
```

### Minimal reproduction project

N/A

**Comment by bruvzg** [comment]
`-1` is clearly added deliberately, but I do not remember why it was done exactly. I'll test if it's necessary.

**Comment by MikeSchulze** [comment]
Thanks 👍
