### ISSUE TITLE
Web-Export not possible on macOS and Godot 4 RC2

### ISSUE THREAD

**Issue by divin** [godotengine/godot#73637]
### Godot version

4.0-rc2 mono

### System information

macOS Ventura (13.2.1) with M1 Max

### Issue description

When I try to export my project for web it can't find the web export templates.

![Screenshot 2023-02-20 at 18 36 43](https://user-images.githubusercontent.com/71128266/220171186-9d977985-ad86-4355-ba6e-44d85622eadd.png)

I manually downloaded the export files and double checked the `export_template` folder but the `web_debug.zip` as well as the `web_release.zip` are missing in both cases.

![Screenshot 2023-02-20 at 18 36 54](https://user-images.githubusercontent.com/71128266/220171192-ed4b9e00-1fe5-4689-bdf7-f70ac6a78c39.png)

According to the approved answer in this [post](https://godotengine.org/qa/129054/godot-4-html5-webassembly-export) Godot 4 should have a web export.

Any idea why the web export templates are missing?

### Steps to reproduce

1. Create a project
2. Try to export it for web

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/10786798/Test.zip)

**Comment by Calinou** [comment]
There are no HTML5 export templates for C# yet, because upstream support is missing. (It will only be restored in 4.1 at the earliest.)
