### ISSUE TITLE
Missing enum `MOUSE_BUTTON_MASK_WHEEL_UP` and `MOUSE_BUTTON_MASK_WHEEL_DOWN` in GlobalScope

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#73632]
### Godot version

v4.0.rc2.official [d2699dc7a]

### System information

ALL

### Issue description

I map mouse buttons against mask and find out there are missing enums.
* `MOUSE_BUTTON_MASK_WHEEL_UP`
* `MOUSE_BUTTON_MASK_WHEEL_DOWN` 

```gdscript
# mapping of mouse buttons and his masks
const MAP_MOUSE_BUTTON_MASKS := {
	MOUSE_BUTTON_LEFT : MOUSE_BUTTON_MASK_LEFT,
	MOUSE_BUTTON_RIGHT : MOUSE_BUTTON_MASK_RIGHT,
	MOUSE_BUTTON_MIDDLE : MOUSE_BUTTON_MASK_MIDDLE,
	MOUSE_BUTTON_WHEEL_UP : 8,
	MOUSE_BUTTON_WHEEL_DOWN : 16,
	MOUSE_BUTTON_XBUTTON1 : MOUSE_BUTTON_MASK_MB_XBUTTON1,
	MOUSE_BUTTON_XBUTTON2 : MOUSE_BUTTON_MASK_MB_XBUTTON2,
}
````
From documentaiton
```
flags  MouseButtonMask:

● MOUSE_BUTTON_MASK_LEFT = 1
Primary mouse button mask, usually for the left button.
● MOUSE_BUTTON_MASK_RIGHT = 2
Secondary mouse button mask, usually for the right button.
● MOUSE_BUTTON_MASK_MIDDLE = 4
Middle mouse button mask.
● MOUSE_BUTTON_MASK_MB_XBUTTON1 = 128
Extra mouse button 1 mask.
● MOUSE_BUTTON_MASK_MB_XBUTTON2 = 256
Extra mouse button 2 mask.
````

https://github.com/godotengine/godot/blob/c4fb119f03477ad9a494ba6cdad211b35a8efcce/core/input/input_enums.h
```
enum class MouseButtonMask {
	NONE = 0,
	LEFT = (1 << (int(MouseButton::LEFT) - 1)),
	RIGHT = (1 << (int(MouseButton::RIGHT) - 1)),
	MIDDLE = (1 << (int(MouseButton::MIDDLE) - 1)),
	MB_XBUTTON1 = (1 << (int(MouseButton::MB_XBUTTON1) - 1)),
	MB_XBUTTON2 = (1 << (int(MouseButton::MB_XBUTTON2) - 1)),
};
```

### Steps to reproduce

```gdscript
const MAP_MOUSE_BUTTON_MASKS := {
	MOUSE_BUTTON_LEFT : MOUSE_BUTTON_MASK_LEFT,
	MOUSE_BUTTON_RIGHT : MOUSE_BUTTON_MASK_RIGHT,
	MOUSE_BUTTON_MIDDLE : MOUSE_BUTTON_MASK_MIDDLE,
	MOUSE_BUTTON_WHEEL_UP : MOUSE_BUTTON_MASK_WHEEL_UP,
	MOUSE_BUTTON_WHEEL_DOWN : MOUSE_BUTTON_MASK_WHEEL_DOWN,
	MOUSE_BUTTON_XBUTTON1 : MOUSE_BUTTON_MASK_MB_XBUTTON1,
	MOUSE_BUTTON_XBUTTON2 : MOUSE_BUTTON_MASK_MB_XBUTTON2,
}
```
```
Identifier "MOUSE_BUTTON_MASK_WHEEL_UP" not declared in the current scope.Zeile 
Identifier "MOUSE_BUTTON_MASK_WHEEL_DOWN" not declared in the current scope.Zeile 
Assigned value for constant "MAP_MOUSE_BUTTON_MASKS" isn't a constant expression.
```

### Minimal reproduction project

N/A

**Comment by Sauermann** [comment]
Not sure if I remember correctly.
The reason why these masks are not useful was, that WHEEL-buttons emit events always as button-down-button-up combination, so there is never a state, where these buttons are in pressed down state.

Can you please provide a use-case, where these missing MASK-constants are a problem?

**Comment by MikeSchulze** [comment]
I added this mapping and mask handling on my scene runner input event handling just for completness.
A usecase are:
oben a browser, press wheel down and hold than move the mouse it will scroll the page.

**Comment by Sauermann** [comment]
I believe, that you are talking about `MOUSE_BUTTON_MIDDLE`.

**Comment by MikeSchulze** [comment]
you are right ;) it is `MOUSE_BUTTON_MIDDLE` but is the wheel, 
So i have to use the mask `MOUSE_BUTTON_MASK_MIDDLE` instead?

**Comment by Sauermann** [comment]
Indeed.

**Comment by MikeSchulze** [comment]
Ok thank you, so i'm wrong you can close this issue.
Thanks for your time

**Comment by Sauermann** [comment]
Do you know, that you can close the issue yourself? There is a button for that at the bottom of the page.

**Comment by MikeSchulze** [comment]
yes i now ;)
