### ISSUE TITLE
Crash when Label's text exceeds height inside ScrollContainer when autowrap set to 'arbitrary'.

### ISSUE THREAD

**Issue by bhottovy** [godotengine/godot#73635]
### Godot version

4.0-rc2 mono

### System information

Windows 11

### Issue description

Trying to set up an in-game chat with Labels contained inside of a VBoxContainer within a ScrollContainer. Things work as expected when autowrap is set to 'Off' (Scrollcontainer has a scrollbar when label(s) exceed the height).

However, when the label(s) have autowrap set to 'arbitrary' Godot immediately crashes when the text exceeds the height of the ScrollContainer. This is the minimal example I used to reproduce this problem:

![image](https://user-images.githubusercontent.com/17091612/220164821-240b98eb-fb19-45d2-9920-ee0006791689.png)
If another line is added to the text Godot crashes and the following errors are displayed in the console:
```
ERROR: Failed method: Label::_shape. Message queue out of memory. Try increasing 'memory/limits/message_queue/max_size_kb' in project settings.
   at: push_callablep (core/object/message_queue.cpp:120)
ERROR: Failed method: CanvasItem::_redraw_callback. Message queue out of memory. Try increasing 'memory/limits/message_queue/max_size_kb' in project settings.
   at: push_callablep (core/object/message_queue.cpp:120)
ERROR: Failed method: CanvasItem::_redraw_callback. Message queue out of memory. Try increasing 'memory/limits/message_queue/max_size_kb' in project settings.
   at: push_callablep (core/object/message_queue.cpp:120)
ERROR: Failed method: CanvasItem::_redraw_callback. Message queue out of memory. Try increasing 'memory/limits/message_queue/max_size_kb' in project settings.
   at: push_callablep (core/object/message_queue.cpp:120)
```

### Steps to reproduce

- Create a ScrollContainer that contains a VBoxContainer and a Label. 
- Set the Label's autowrap to 'arbitrary'.
- Append lines to the Label's text until the text exceeds the ScrollContainer's height.
- When a character is typed into the last line Godot will crash.

### Minimal reproduction project

[ScrollContainerCrash.zip](https://github.com/godotengine/godot/files/10786641/ScrollContainerCrash.zip)

In the project go to the Label node and add another line to the Text field and type any character. If autowrap is set to 'off' then everything works fine.

**Comment by akien-mga** [comment]
I can reproduce the issue in 4.0 RC 2, and it seems fixed in `master` (likely by #73426).
