### ISSUE TITLE
Crashing on project open

### ISSUE THREAD

**Issue by Robert-W-Ward** [godotengine/godot#73653]
### Godot version

4.0 release candidate 1

### System information

Windows 10 21H2, RTX 2070, Driver 517.48

### Issue description

Opening any project will stall for a second like its about to load then immediately crash and close the window. I believe it has something to do with the ultrawide monitor, as this did not happen when I was using a regular 16:9 monitor.

### Steps to reproduce

Use an ultrawide monitor as you only display.
Try and open any 4.0 release candidate project 
Editor fails to load and crash.

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
Can you run the engine from the command line and then post what is printed to the command line when the engine crashes?

**Comment by Calinou** [comment]
> Use an ultrawide monitor as you only display.

This seems unlikely as a cause, but if you want to make sure, switch to a 16:9 resolution in the NVIDIA Control Panel.

**Comment by WalruswareGames** [comment]
I don't have an ultrawide monitor, just tried to create new project twice on 4.0 Rc2 and both times it go at far as saying "importing" and then crashed.

**Comment by Robert-W-Ward** [comment]
``` 
ERROR: hostfxr_initialize_for_runtime_config failed with code: -2147450733
   at: (modules/mono/mono_gd/gd_mono.cpp:201)
ERROR: Parameter "load_assembly_and_get_function_pointer" is null.
   at: initialize_hostfxr_and_godot_plugins (modules/mono/mono_gd/gd_mono.cpp:274)
ERROR: Parameter "godot_plugins_initialize" is null.
   at: initialize (modules/mono/mono_gd/gd_mono.cpp:403)
WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:70)
```
These are the errors I get when trying to run from the console. I thought maybe it was something to do with .Net not being found, but the thing is the beta version 14 still opens as does 12 and 13. All of them are mono builds so it can't be .Net. Also I tried what @Calinou  suggested and can confirm that its nothing to do with the ultrawide, but I'm at a loss for why mono isn't being initialized.

**Comment by Robert-W-Ward** [comment]
Well apparently its been fixed with rc3.
