### ISSUE TITLE
`is` statement cant read scope

### ISSUE THREAD

**Issue by bend-n** [godotengine/godot#73663]
### Godot version

9c960a8c2

### System information

Archlinux x11

### Issue description

![image](https://user-images.githubusercontent.com/70787919/220256306-f93c19ba-99eb-4bb6-97f1-96b02a008ed0.png)

### Steps to reproduce

```gdscript
var c := 4
var b := 2
var a := c is b
```

### Minimal reproduction project

na

**Comment by dalexeev** [comment]
`is` is not a comparison operator, it is a type checking operator.

**Comment by bend-n** [comment]
i know that

**Comment by akien-mga** [comment]
This is an expected compat breaking change from https://github.com/godotengine/godot/pull/73489.

What's your use case for `a is b`? It doesn't make sense. It used to work, but it's not what the `is` operator is for.

@vonagam I feel the error message could maybe be improved though, it could say that it expects a type name instead of saying it doesn't see `b`.

**Comment by dalexeev** [comment]
The right operand of the `is` operator must be a type. `2` is not a type. If you want to compare values or references, there is the `==` operator, `is_same()`, `is_equal_approx()`, etc.

**Comment by bend-n** [comment]
I use it to check if a `InputEvent` is a `InputEventMouseMotion` or other event (https://github.com/bend-n/remap/blob/main/addons/remap/private/RemapUtilities.gd#L17-L22)

**Comment by dalexeev** [comment]
See #73489:

> Since right side now needs to be compile time known type to support previously available functionality, where a type was intended to be variable, add `is_instance_of` utility function to GDScript.
> 
> ```gdscript
> is_instance_of(a, TYPE_INT)
> is_instance_of(a, RefCounted)
> is_instance_of(a, A)
> ```

**Comment by bend-n** [comment]
@dalexeev I see, thanks for explaining.
