### ISSUE TITLE
Screen Space Ambient Occlusion function (ssao) has no effect on the iPad

### ISSUE THREAD

**Issue by jl1872002** [godotengine/godot#73670]
### Godot version

3.5

### System information

13.0.1 (22A400)

### Issue description

Screen Space Ambient Occlusion function (ssao) has no effect on the iPad

Effect on PC:
![149E7196-2321-4CD0-80C1-F4ADE5023735](https://user-images.githubusercontent.com/5889641/220281273-70249d0e-a760-4309-8bab-16cddcff7998.png)

Effect on iPad:
![IMG_0001](https://user-images.githubusercontent.com/5889641/220281323-2835652f-d3c6-4893-b88a-965e8c6f4991.PNG)

### Steps to reproduce

Open the ssao function and export the project to the ipad.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
I know there are separate settings for these things in 4.0 for mobile, is there a setting like that for this?

**Comment by jl1872002** [comment]
Android pad and iPad have the same problem.

**Comment by AThousandShips** [comment]
Which backend do you use? GLES3 or GLES2?

**Comment by clayjohn** [comment]
This is likely because [``rendering/quality/depth_prepass/disable_for_vendors``](https://docs.godotengine.org/en/stable/classes/class_projectsettings.html#class-projectsettings-property-rendering-quality-depth-prepass-disable-for-vendors) disables the depth prepass for Apple phones (among other mobile devices). depth prepass is needed for SSAO

**Comment by jl1872002** [comment]
![image](https://user-images.githubusercontent.com/5889641/220503908-0b541357-5ced-4a4a-8960-bb413fd2987d.png)

I use GLES3

I set these attributes of the image, but there is no effect of ssao on mobile devices

**Comment by clayjohn** [comment]
> ![image](https://user-images.githubusercontent.com/5889641/220503908-0b541357-5ced-4a4a-8960-bb413fd2987d.png)
> 
> I use GLES3
> 
> I set these attributes of the image, but there is no effect of ssao on mobile devices

In the screenshot you are still disabling the depth prepass

**Comment by Zireael07** [comment]
The git diff above shows depth prepass as off  - are you sure you saved after making the setting change?

**Comment by Calinou** [comment]
The default framebuffer allocation mode for mobile is **3D Without Effects** for performance reasons. You need to change the `.mobile` override to **3D** to allow using effects in 3D.

**Comment by jl1872002** [comment]
> framebuffer

This setting can take effect on mobile devices. Thank you all
