### ISSUE TITLE
Crashing on project open with Forward+ 

### ISSUE THREAD

**Issue by cling1988** [godotengine/godot#73676]
### Godot version

Godot_v4.0-rc2_win64

### System information

Windows 10 Home, NVIDIA - GeForce GTX 860M

### Issue description

Open project with Forward+ will close the window immediately.
Try opening with console and displaying the error message like below
`ERROR: vkCreateComputePipelines failed with error -1000012000.
   at: (drivers/vulkan/rendering_device_vulkan.cpp:6517)`

### Steps to reproduce

With create new project
1. Open Godot 
2. Create new project with Forward+
3. Editor fails to load

With existing project
1. Open Godot with any project not using Forward+
2. Switch it to Forward+ and restart
3. Editor fails to load

### Minimal reproduction project

n/a

**Comment by clayjohn** [comment]
That error maps onto the ``VK_ERROR_INVALID_SHADER_NV`` and it is failing to create a compute pipeline. These indicate that one of the compute shaders are failing to compile. 

Can you please do two things:
1. Confirm that you have up-to-date GPU drivers (if you don't, then update your driver)
2. Run the engine from the command line and then post the output here (I am hoping there will be a shader compilation failure log printed to the command line before it crashes)

**Comment by cling1988** [comment]
After updated the GPU drivers, it works now.
