### ISSUE TITLE
Distance Directional Shadows Pixelize as you get further away

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#73677]
### Godot version

4.0 rc 1

### System information

Windows 11, Vulkan, GTX 1050 Ti 528.24

### Issue description

Expected Results: Large Distance Directional Shadows start to shrink-fade as you get further from them due to the lower resolution of distant Shadow Splits. This is common Practice in Many Games, Even AAA games such as Shadow of the Tomb Raider for Directional Shadows

Wrong Results: Large Distance Directional Shadows Pixelize as you get further away from them as the shadow blur reduces ultimately resulting in hard shadows in distant splits that look significantly worse compared to simply slowly shrink-fading the shadows as they get less resolution.

This Issue prevents Longer distance Shadows from being usable unless you are intentionally going with Hard shadows which don't have Shadow blur by definition.

While this Issue is also present with Blending Splits off, it is intended behavior there, as with No blending you get Massive seams between two splits of non matching shadow blur radiuses that look significantly worse compared to a little pixelization, especially considering the fact that blending splits is not very useful for smaller distance directional shadows which benefit the most from the change as they are now cheaper to get at good quality

As such https://github.com/godotengine/godot/pull/48776 Should be modified to not work for Blending Splits on, as the usage for it is typically for larger more demanding scenes where a little cost from blending doesn't matter and where the pr causes issues, whereas Blending Splits off should keep current behavior as it provides good quality for smaller scenes where there's no point in forcing a more expensive approach

Expected Results in Alpha 1:

https://user-images.githubusercontent.com/50302479/220336549-df423292-c977-46bb-9d1c-ecd66d5c222a.mp4

Wrong Results in RC 1:

https://user-images.githubusercontent.com/50302479/220336724-045e99ef-c005-4be0-855d-33579fc22aec.mp4

### Steps to reproduce

Enable Blending, and set the Split settings to similar values as in the videos (Higher distance shadows, with significantly lower resolution in the distance compared to close up)

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
We should really change blend splitting to work over a smaller distance of the split (e.g. 50% of the split instead of its entire distance). This will make the transition a bit less smooth, but it'll improve effective resolution and also performance (as the area over which you need to sample two splits will be smaller, and fewer objects will need to be drawn in each split).

**Comment by mrjustaguy** [comment]
> That said, we should really change blend splitting to work over a smaller distance of the split (e.g. 50% of the split instead of its entire distance). This will make the transition a bit less smooth, but it'll improve effective resolution and also performance (as the area over which you need to sample two splits will be smaller, and fewer objects will need to be drawn in each split).
> 
> A lot of the issues with blend splitting currently come from the fact that the _entire_ split has to overlap with the previous one, which decreases the effective shadow resolution more than needed.



Actually, when the blending is off with these settings the distant splits ALSO have the pixelization issue very obviously at the same settings, so smaller blending distance wouldn't do much at all as it's more or less all about split values as shown below.

![image](https://user-images.githubusercontent.com/50302479/220400570-9a5290e8-e87d-4cef-b649-85dfe04d2bcf.png)

While the PR caters to games that have sufficient shadow resolution for their needs on the default split values, but those games have to go one of 2 routes:
1) High Resolution but Low Distance
2) Low Resolution but High Distance

Anything in between just doesn't exist now, as changing up the split values more significantly just causes problems, and the only mitigation to those problems is to up the Shadow Map Resolution, which is both very memory intensive and slower but also doesn't even mitigate it much.

As such what should be done is:

1) PR stays for Blending Splits disabled as is, as it works for the more or less default setup scenarios and does have a performance advantage that smaller games aiming more limited devices would be most impacted by
2) When Blending Splits use Old logic, as that is way easier to work with and is more flexible not to mention that it works significantly better for larger environments where you still need to have detailed shadows up close, but also decent shadows very far away, and for those types of games the performance penalty from Blending Splits is small anyway compared to everything else that's typically going on.

**Comment by clayjohn** [comment]
As Calinou pointed out, this is kind of expected behaviour. The previous behaviour resulted in distant splits having a much wider penumbra then closer splits which lead to an ugly seam between individual splits. 

In the end we decided it was worthwhile to have the blur amount reduce for distance splits to hide the transition, but this of course leads to the pixelation artifacts that you describe (unless your base blur is very high). 


> As such what should be done is:
> 
> 1. PR stays for Blending Splits disabled as is, as it works for the more or less default setup scenarios and does have a performance advantage that smaller games aiming more limited devices would be most impacted by
> 2. When Blending Splits use Old logic, as that is way easier to work with and is more flexible not to mention that it works significantly better for larger environments where you still need to have detailed shadows up close, but also decent shadows very far away, and for those types of games the performance penalty from Blending Splits is small anyway compared to everything else that's typically going on.

This sounds like a good idea. As Calinou mentioned above, we likely need to rework the split blending anyway, so that would be a good time to make the adjustment.

**Comment by mrjustaguy** [comment]
Regarding Reworking blending to have it start at an arbitrary distance the shader code that needs to be changed is this (linking for Forward+)

https://github.com/godotengine/godot/blob/4c3dc26367518e006f8555c12f5d2df0b8a28192/servers/rendering/renderer_rd/shaders/forward_clustered/scene_forward_clustered.glsl#L1778 to `pssm_blend = smoothstep(directional_lights.data[i].shadow_split_offsets.x-directional_lights.data[i].shadow_split_offsets.x*Blending_Start, directional_lights.data[i].shadow_split_offsets.x, depth_z);`
https://github.com/godotengine/godot/blob/4c3dc26367518e006f8555c12f5d2df0b8a28192/servers/rendering/renderer_rd/shaders/forward_clustered/scene_forward_clustered.glsl#L1785 to `pssm_blend = smoothstep(directional_lights.data[i].shadow_split_offsets.y-directional_lights.data[i].shadow_split_offsets.y*Blending_Start, directional_lights.data[i].shadow_split_offsets.y, depth_z);`
https://github.com/godotengine/godot/blob/4c3dc26367518e006f8555c12f5d2df0b8a28192/servers/rendering/renderer_rd/shaders/forward_clustered/scene_forward_clustered.glsl#L1792 to `pssm_blend = smoothstep(directional_lights.data[i].shadow_split_offsets.z-directional_lights.data[i].shadow_split_offsets.z*Blending_Start, directional_lights.data[i].shadow_split_offsets.z, depth_z);`

with the Blending_Start being a float passed to the shaders, much like things like softness is passed, however I have no ideas how to do anything past this, and in my tests I've just hardcoded Blending into the shader. I've also removed the Blur factor multiplication in https://github.com/godotengine/godot/blob/4c3dc26367518e006f8555c12f5d2df0b8a28192/servers/rendering/renderer_rd/shaders/forward_clustered/scene_forward_clustered.glsl#L1802
and
https://github.com/godotengine/godot/blob/4c3dc26367518e006f8555c12f5d2df0b8a28192/servers/rendering/renderer_rd/shaders/forward_clustered/scene_forward_clustered.glsl#L1768
to in effect restore the old behavior for better Blending quality..

Though there are some things that Need to be discussed:
1) How to expose Blending start (IMO we need to give an option per split, as there's no good solution here, too many variables)
2) Potentially reworking the Blur mechanism, as both the current automatic adjustment per split and no adjustment are suboptimal in their own ways, having an option of changing blur factors per split with blending enabled would be beneficial for enabling users to get the best quality with Blending.
With Blending Disabled the Automatic adjustments should be kept, so this is just a rework for when blending is used
