### ISSUE TITLE
str function error when extracting HTML5 or Linux binary version

### ISSUE THREAD

**Issue by borcun** [godotengine/godot#7368]
Hi,

I started to develop a small project with Godot Engine v2.0.3.stable.official version in Arch Linux ( 4.8.11.1 x64_86 ). 

I used a label and a button. When the button is triggered, any numeric value as **string** will be written in label via setText. When i use str function to convert the numeric value to string, it works on Godot Editor. After the project is exported, it does not work in browser (HTML5) and as Linux binary file, str function gives 'you can not convert bool to string' weird error when it runs. Then, i use String constructor instead of str function, at this time it does not work on Godot Editor, but works on browser ( HTML5 ) and as Linux binary, there is no error. 

[This](https://github.com/borcun/godot-sample/blob/master/GoCalculator/calculator.gd) is my GDScript link.
The related issue is in 73 and 74 lines.

Thank you so much.

**Comment by borcun** [comment]
is it related to [5593](https://github.com/godotengine/godot/issues/5593)

**Comment by volzhs** [comment]
what happen for this issue?

**Comment by bojidar-bg** [comment]
Guess he fixed it himself, or a misclick.

**Comment by borcun** [comment]
i am sorry, it was already opened. i solved it.
