### ISSUE TITLE
Exports fail to codesign

### ISSUE THREAD

**Issue by Anixias** [godotengine/godot#73681]
### Godot version

v4.0.rc2.mono.official [d2699dc7a]

### System information

Windows 10

### Issue description

I've just set up code signing but am being given a large number of the same error:

![image](https://user-images.githubusercontent.com/22286697/220371190-810f6d14-c805-4470-95b5-73996937b1af.png)

### Steps to reproduce

Unsure, attempting to codesign using Identity Type = Certificate Store with a personal code signing certificate.

### Minimal reproduction project

N/A

**Comment by Anixias** [comment]
Changing Identity Type to PKCS12 file successfully signs the export with the following warnings:

![image](https://user-images.githubusercontent.com/22286697/220372066-8101cd60-8112-42bd-a052-11041a7089d8.png)

**Comment by bruvzg** [comment]
> Type = Certificate Store with a personal code signing certificate.

Have you entered a SHA1 hash in the `codesign/identity` field? Or are you using file + password.

There are two options for signing:
- `Auto`: `identity` and `password` are ignored.
- `Certificate Store`: `identity` should be SHA1 hash, `password` is ignored.
- `PKCS12`: `identity` should be certificate file path and `password` should be set if certificate is encrypted.

> Changing Identity Type to PKCS12 file successfully signs the export with the following warnings:

Check the log, this warning indicate that signing was not successful.

**Comment by Anixias** [comment]
I tried both methods, only file + password works successfully.
