### ISSUE TITLE
cannot change visibility of child node if parent node is hidden

### ISSUE THREAD

**Issue by Warlaan** [godotengine/godot#7369]
**Operating system or device - Godot version:**
Godot 2.1.1

**Issue description** (what happened, and what was expected):
When you are trying to use the eye icon in the hierarchy to change the visibility of a node that is a child of an invisible node you get an error message saying "This item cannot be made visible because the parent is hidden. Unhide the parent first.".
It's fine that there is a warning for people who would wonder why there are no visible changes, but it should be possible to change the value nevertheless. E.g. I might have a complex scene with two states in it of which one is always hidden. It should be possible to switch those states without having to unhide the root node first.

Apart from that changing the Visible-Flag in the CanvasItem section of the inspector works, but doesn't update the eye-symbol in the hierarchy.

**Steps to reproduce:**
Create a new scene.
Create a root node of type Node2D.
Create a child node of type Node2D.
Hide the root node.
a) Try to hide the child node.
b) Unset the Visible-flag in the inspector.

**Comment by bojidar-bg** [comment]
@volzhs This looks great!

**Comment by volzhs** [comment]
![visibility_color](https://cloud.githubusercontent.com/assets/8281454/21522127/5276f04a-cd46-11e6-99f3-fa6263065e0b.gif)

This is another version. (not done yet)
@bojidar-bg WDYT on this?

**Comment by bojidar-bg** [comment]
@volzhs Well, I think the first one is better, since the gray color is nicer than the red.

**Comment by volzhs** [comment]
@bojidar-bg agreed with colors. I'll make another commit with first one for now. :)

**Comment by Warlaan** [comment]
Great solution! I agree about the colors. Grey suggests inactive, red invalid.

**Comment by volzhs** [comment]
I was trying to show grouping colors but it was not easy :(
