### ISSUE TITLE
[Android Editor] Several controls don't respond to touch gestures

### ISSUE THREAD

**Issue by leogott** [godotengine/godot#73707]
### Godot version

Version v4.0.rc.custom_build [8c7b98d45]

### System information

Galaxy Tab S6 Lite running Android 12 with keyboard case

### Issue description

For the fun of it, I followed the [2D Tutorial](https://docs.godotengine.org/en/latest/getting_started/first_2d_game/index.html) on my Android tablet.
I noticed several steps that were impossible to repeat without a connected mouse, because interface elements simply didn't respond to touch taps.
I was unable to:
* [x] Close a Scene
* [x] Resize a CollisionShape2D
* [x] Modify a Mask property
* [x] Move Path2D Nodes

### Steps to reproduce

**Close a Scene**
In any Workspace, while several scenes are open: Press the X to close the Scene. (Image for clarity)
![grafik](https://user-images.githubusercontent.com/61663141/220451195-22a7f817-621b-4ce9-b0ea-3766ca129f6f.png)
**Expected result**
The Scene is closed after tapping the X

**Resize a CollisionShape2D**
Try to grab and move the Gizmos to resize the Shape. I can't do it at all.
**Expected result**
The gizmos could be a smidge larger. Mostly though, they should move when I try to drag them. The viewport shouldn't.

**Modify a Mask property**
Tapping the property has no effect. Long-press can sometimes select a layer, after which it can be toggled. Very fiddly and not repeatable.
![grafik](https://user-images.githubusercontent.com/61663141/220451776-b111b10f-8dcb-452f-9c0a-d95b7094df03.png)
**Expected result**
The mask property should behave like a bunch of tiny toggle buttons. Alternatively tapping should enlarge the button field.

**Move Path2D Nodes**
It's not completely impossible. I can move the Node by a few pixels.
With longer movements I'll instead drag the viewport.
**Expected result**
Dragging a node should move the node and not the viewport. The node icons could be a bit larger on mobile.

What if you could only 2-finger-drag the viewport while a Node with Gizmos is selected? That could make things easier!

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/72385.

**Comment by QbieShay** [comment]
Related: https://github.com/godotengine/godot/issues/75144

**Comment by m4gr3d** [comment]
Fixed by https://github.com/godotengine/godot/pull/75718 and https://github.com/godotengine/godot/pull/75703
