### ISSUE TITLE
Can't change rendering method in the Android editor using the dropdown in the top-right corner / Exported mobile project doesn't use specified rendering method

### ISSUE THREAD

**Issue by leogott** [godotengine/godot#73712]
### Godot version

Version v4.0.rc.custom_build [8c7b98d]

### System information

Galaxy Tab S6 Lite running Android 12

### Issue description

After creating a project on android, attempting to change the renderer from Mobile to Compatibility or the other way around just results in the Godot Splash screen appearing for a few seconds, without the change being applied.

### Steps to reproduce

On Android, create a new Project.
Afterwards attempt to change the renderer.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
I remember seeing an issue for this already, but I can't find it right now.

**Comment by Calinou** [comment]
I can confirm this on 4.0.rc3. This is caused by the rendering dropdown not changing the `.mobile` override, so https://github.com/godotengine/godot/pull/72461 fixes this.

**Comment by astrale-sharp** [comment]
How would one change "Rendering Method.mobile" ? :)

**Comment by clayjohn** [comment]
> How would one change "Rendering Method.mobile" ? :)

In the project settings [rendering/renderer/rendering_method.mobile](https://docs.godotengine.org/en/latest/classes/class_projectsettings.html#class-projectsettings-property-rendering-renderer-rendering-method-mobile)

**Comment by astrale-sharp** [comment]
With what value, mobile?

**Comment by Calinou** [comment]
> With what value, mobile?

If you want to switch to the Compatibility rendering method, use `gl_compatibility` on the `mobile` override but make sure you also change it for the non-overridden setting (so visuals on your PC will match the mobile device).
