### ISSUE TITLE
Keyword 'is' no longer works with variables or dynamic references.

### ISSUE THREAD

**Issue by LunaticWyrm467** [godotengine/godot#73722]
### Godot version

4.0 Release Candidate 3

### System information

Windows 11, Nvidia RTX 3050

### Issue description

Prior to 4.0's release candidate 3.0, I was able to set up a variable that contains a reference to a class, and compare that variable with the 'is' keyword; like so:
```
var class_reference = CLASS_NAME_HERE
var object: CLASS_NAME_HERE = class_instance_here
if object is class_reference:
    run_logic_here()
```
Now, I am no longer able to do this, as the editor throws the following error:
`"class_reference " was not found in the current scope.`

### Steps to reproduce

1) Declare a variable that will hold a class reference.
2) Use that as a direct comparison with an object with the keyword 'is'.
3) Error pops up.

### Minimal reproduction project

N/A

**Comment by vonagam** [comment]
Use `is_instance_of(object, class_reference)`, that's the intended consequence from changing how type check operates - #73489.

**Comment by LunaticWyrm467** [comment]
Oh thank you, glad to know this functionality still exists!
