### ISSUE TITLE
Debugger errors thrown when ReflectionProbe sees a ShaderMaterial that reads from the depth texture (both in game and in editor)

### ISSUE THREAD

**Issue by tessarakkt** [godotengine/godot#73727]
### Godot version

4.0.rc3

### System information

Windows 10 & Arch Linux, both Vulkan backend with AMD RX 6700

### Issue description

When an object with a ShaderMaterial that accesses the depth texture is visible to a ReflectionProbe, errors will be thrown each time the ReflectionProbe redraws. This happens both in the editor and in game. There does not appear to be any obvious effects of this aside from the error, but I might not have found them yet.

In the editor this message will be displayed to the Output:
```
servers/rendering/renderer_rd/storage_rd/texture_storage.cpp:2697 - Condition "!rt" is true. Returning: RID()
```

In game this error will be displayed to Debugger/Errors:
```
E 0:00:00:0881   render_target_get_override_depth: Condition "!rt" is true. Returning: RID()
  <C++ Source>   servers/rendering/renderer_rd/storage_rd/texture_storage.cpp:2697 @ render_target_get_override_depth()
```

### Steps to reproduce

1. Create a 3D scene containing a ReflectionProbe, a MeshInstance3D, and a Camera3D.
2. Attach a ShaderMaterial to the mesh which access the depth texture:
```
shader_type spatial;

uniform sampler2D depth_texture : hint_depth_texture;

void fragment() {
	float depth = texture(depth_texture, SCREEN_UV).r;
}
```
3. Move the ReflectionProbe around the scene, note the errors in the Output tab.
4. Run the scene, note the errors in the Debugger/Errors tab.

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/10799590/Test.zip)

**Comment by clayjohn** [comment]
Will be fixed by https://github.com/godotengine/godot/pull/73733
