### ISSUE TITLE
Godot 4 rc3 Android has wrong Manifest version

### ISSUE THREAD

**Issue by leoossa** [godotengine/godot#73735]
Hi,
because of the wrong version in the Manifest (rc0) you can't upgrade rc2 to rc3 without reinstallation.
![](https://i.imgur.com/Q4vnfCm.jpg) 

Version downloaded from:
https://downloads.tuxfamily.org/godotengine/4.0/rc3/

**Comment by m4gr3d** [comment]
@leoossa You should be able to grab the version from the Play Store, it has the correct manifest version 

https://play.google.com/store/apps/details?id=org.godotengine.editor.v4

**Comment by leoossa** [comment]
@m4gr3d play version has no rc3 just rc2. So that's not a solution.

![](https://i.imgur.com/UVIHMOU.png)

**Comment by m4gr3d** [comment]
> @m4gr3d play version has no rc3 just rc2. So that's not a solution.
> 
> ![](https://i.imgur.com/UVIHMOU.png) 

The rc3 build was recently pushed, so it will be available shortly.

**Comment by leoossa** [comment]
@m4gr3d  how long it takes the release cycle to publish to the store? There's rc5 available on website but rc3 on Play Store

**Comment by akien-mga** [comment]
It's not automated yet, and we've had very frequent builds. @m4gr3d will likely get to it in coming days (if anything, with 4.0-stable which is imminent).
