### ISSUE TITLE
Front view looks opposite side

### ISSUE THREAD

**Issue by ulvido** [godotengine/godot#73742]
### Godot version

4.0.rc3

### System information

Windows 10

### Issue description

If user pressed `Front View` (Numpad 1) camera should look Vector3.FORWARD . current settings not match with blender or godots internal semantic.

### Steps to reproduce

switch to 3d tab and press numpad 1

### Minimal reproduction project

N/A

**Comment by kleonc** [comment]
> If user pressed `Front View` (Numpad 1) camera should look Vector3.FORWARD . current settings not match with blender or godots internal semantic.

In front view the camera looks at the front so from front (-Z) to back (+Z). Just like e.g. in right view the camera looks from right (+X) to left (-X) so the right side is seen, etc.
So AFAICT everything works as expected (as in Godot `Vector3.FORWARD` is -Z).

[Blender uses different coordinate system](https://www.techarthub.com/wp-content/uploads/coordinate-comparison-chart-full.jpg) so of course these two don't match.

See also:
- https://github.com/godotengine/godot-proposals/issues/6198.
