### ISSUE TITLE
EditorFileDialog doesn't support filters

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#73745]
### Godot version

4.0 RC2

### System information

Fedora, RX 590

### Issue description

Can't assign filters for file types to EditorFileDialog. Furthermore, it seems odd that it's a sibling class of FileDialog rather than being a child?

### Steps to reproduce

https://docs.godotengine.org/en/latest/classes/class_filedialog.html
https://docs.godotengine.org/en/latest/classes/class_editorfiledialog.html

Note the lack of filters option for editorfiledialog
![Screenshot from 2023-02-22 09-57-27](https://user-images.githubusercontent.com/7917475/220571101-f8d60340-a910-4e90-be38-b46fdb628e03.png)
![Screenshot from 2023-02-22 09-57-20](https://user-images.githubusercontent.com/7917475/220571105-a14ac77d-641d-4ed3-8494-700bad05d10f.png)

### Minimal reproduction project

see above

**Comment by bruvzg** [comment]
`clear_filters` and `add_filter` methods are supported by both, not sure why property is not (probably editor dialog was missed when it was added in https://github.com/godotengine/godot/pull/5746).
