### ISSUE TITLE
VisualShader Materials using Alpha doesn't cast shadows

### ISSUE THREAD

**Issue by SirManfred** [godotengine/godot#73757]
### Godot version

v4.0.beta.custom_build [df61f3475]

### System information

Windows 10 Pro, RTX 3060

### Issue description

When using alpha in a VisualShader Material, the mesh with the material doesn't cast shadows.
The alpha material is also not visibile through a glass shader (using Scene texture)
![image02](https://user-images.githubusercontent.com/7838390/220624231-c219b4c0-e112-4df0-b076-74075ecad106.jpg)
Turning on the Depth Prepass Alpha Flag breaks the alpha by making the would-be transparent parts solid black.
This also makes the alpha material visible through the glass shader but as solid black.
![image02_depth_prepass_alpha](https://user-images.githubusercontent.com/7838390/220624286-3761e1b6-0bf1-402e-84f2-13b1ba979e9b.jpg)

I've tried multiple different flag combinations and settings but nothing seems to fix this.

I believe this is related to the previous bug-report I made.

### Steps to reproduce

Make a basic alpha visual shader material.
Make a basic alpha texture. (In my particular example the alpha texture is in the Alpha-channel of a diffuse texture.)
Make a glass shader.
Use them in a scene with a direct light.

### Minimal reproduction project

Reproduction steps are trivial.

**Comment by Calinou** [comment]
[This is expected](https://docs.godotengine.org/en/latest/tutorials/3d/3d_rendering_limitations.html#transparency-sorting), as transparent materials don't write to the depth buffer and cannot cast shadows.

Use alpha scissor or alpha hash transparency if you want the material to be able to cast shadows.

**Comment by clayjohn** [comment]
Yes, this is expected behaviour

The docs for BaseMaterial explain the different transparency modes in more detail https://docs.godotengine.org/en/latest/classes/class_basematerial3d.html#enum-basematerial3d-transparen

It sounds like you are looking for ``TRANSPARENCY_ALPHA_DEPTH_PRE_PASS`` which writes the opaque parts of the transparent material to depth so you can still get shadows and make parts of the object transparent.
