### ISSUE TITLE
FogVolume problems 

### ISSUE THREAD

**Issue by pietru2004** [godotengine/godot#73759]
### Godot version

4.0 beta rc2

### System information

Windows 10 Forward+

### Issue description

When using XRCamera
![20230222010310_1_vr](https://user-images.githubusercontent.com/51274570/220487278-2e1b53ab-820c-40a9-b521-814c8af4292d.jpg)
each eye has diffrent fog level.
https://github.com/GodotVR/godot-xr-tools/issues/381

### Steps to reproduce

On godot 4.0 beta rc2
Launch https://github.com/GodotVR/godot-xr-tools
Place 2 cubes to make small corridor
In corridor add FogVolume node and setup it
Launch project and look at FogVolume.
Each eye should see FogVolume diffrently.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/72331.

**Comment by pietru2004** [comment]
Well I just want to say that I did look isn't it duplicate but didn't see any.
