### ISSUE TITLE
All Godot 4.0 MONO release candidate snapshots crash on creating/loading a project

### ISSUE THREAD

**Issue by ScaredPenguinXXL** [godotengine/godot#73769]
### Godot version

4.0.rc3.mono.official [7e79aead9]

### System information

Ubuntu 22.04.2 LTS 64-bit, Intel® Celeron(R) N4120 CPU @ 1.10GHz × 4

### Issue description

The editor crashes when creating or loading a project using the **mono** release. Projects can be opened and loaded using a standard non mono build.

### Steps to reproduce

Create or load a project using a mono build of the engine.

### Minimal reproduction project

N/A

**Comment by raulsntos** [comment]
Would you be able to open Godot from a terminal with the `--verbose` flag? It may contain more useful information to help us figure out what went wrong.

Also, make sure you have the [.NET 6 SDK](https://dotnet.microsoft.com/en-us/download/dotnet/6.0) installed in a standard location. Can you execute `dotnet --info` in a terminal? What does it output?
