### ISSUE TITLE
Godot 4 rc3: TabBar child node set anchor not working in the editor.

### ISSUE THREAD

**Issue by dqdthanhthanh** [godotengine/godot#73785]
### Godot version

v4.0.rc3.official (7e79aea)

### System information

Mac Air M1 2020

### Issue description

TabBar childs anchor not working in editor.
<img width="438" alt="Ảnh màn hình 2023-02-23 lúc 04 28 01" src="https://user-images.githubusercontent.com/57259604/220763983-ccfe8b3a-10fe-4ebd-a0f8-d90007298774.png">

### Steps to reproduce

Create a TabContainer node with some Tabbar node inside it. Then create some UI node inside Tabbar node. Set any anchor to child node, nothing happen. The child still in Vector2.ZERO.
Note: only child on first Tabbar node works.

### Minimal reproduction project

[Uploading GodotProject.zip…]()

**Comment by YuriSizov** [comment]
TabContainer already contains a TabBar. What are you trying to do?

**Comment by dqdthanhthanh** [comment]
> TabContainer already contains a TabBar. What are you trying to do?

i mean when i create content inside tabbar, you can't set anchor to it. For example when I create a button, i can't set it center or full rect to it. Everything is still normal when on godot 3.5.

https://user-images.githubusercontent.com/57259604/221079765-866723bb-fe98-4953-9854-32c1e5819045.mp4

**Comment by YuriSizov** [comment]
My question is why are you adding extra tabbars to the tabcontainer, when tabcontainer already has a tabbar, and all you need to do is to add control nodes to it. So what are you trying to achieve by adding extra tabbar nodes?

**Comment by dqdthanhthanh** [comment]
For multiple tabs, of course. Even so, still have a bit of a problem with setting anchor to it. Especially in ui interface design.

**Comment by YuriSizov** [comment]
@dqdthanhthanh You don't need to add `TabBar` to `TabContainer`. Tabs are created from child control nodes, like `PanelContainer`, or `MarginContainer`, or one of the box containers. `TabContainer` already has a tabbar, it's built-in. Same is true for 3.x, where I assume you use the `Tabs` nodes as children of `TabContainer`. This is incorrect and not needed. We specifically renamed the `Tabs` node to `TabBar to indicate that it's a representation of the tabbar itself, not a special "tab" node (there is no such things).

**Comment by dqdthanhthanh** [comment]
Thanks. But I mean set anchor for node sometimes doesn't work. For example button node (video from 15 seconds)

https://user-images.githubusercontent.com/57259604/221209069-6f74a688-54c0-44c3-b56b-d0eea673f45c.mp4

**Comment by YuriSizov** [comment]
Plain Control nodes don't have any size, and don't grow in size to fit their children. So your second and third tabs have no side. Anchoring works correctly, as far as I can see, because controls have no size and are displayed from top-left. You want to use containers there not plain controls and anchors.

**Comment by dqdthanhthanh** [comment]
That's what I mean, in the first node the size is equal to the screen ratio and easyly set anchor. The remaining nodes are size = (0,0) and cannot be edit. So I don't know if it's a bug or not. Or am I doing it wrong way?
![Capture](https://user-images.githubusercontent.com/57259604/221216908-21fce849-0ba1-4ff5-8c76-d09a3fcb1802.JPG)
[](url)

**Comment by YuriSizov** [comment]
Yes, you aren't using containers where you should. And you also need to set min size, not just size, as containers will override the size (and position) as that is their function.

**Comment by cenullum** [comment]
same issue and explains better: https://github.com/godotengine/godot/issues/74653
