### ISSUE TITLE
Close file without saving changes

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#7378]
Found on Godot 2.1.1, 64 bits, Windows 10

![save_changes](https://cloud.githubusercontent.com/assets/1311555/21505326/864efd12-cc66-11e6-91e7-2cb514e6e43e.png)

Minor usability issue:
If i click cancel, the file doesn't close. If I click Ok, the file is saved and closed.
I would like to have "Yes", "No" and "Cancel" options, where "No" closes without saving the file.

**Comment by akien-mga** [comment]
Should likely be "Save", "Discard", "Cancel".

**Comment by akien-mga** [comment]
Fixed by a1d07fd.

**Comment by akien-mga** [comment]
Fixed by a1d07fd.
