### ISSUE TITLE
Empty titles and descriptions in project browser

### ISSUE THREAD

**Issue by mashumafi** [godotengine/godot#73780]
### Godot version

4.0 master

### System information

MacOS

### Issue description

After bisecting, it looks like after https://github.com/godotengine/godot/commit/ceee405cec171506dde7bc62033dc52ac3797599 the project explorer shows no text.

![image](https://user-images.githubusercontent.com/1059099/220748560-3b8280c5-b65b-43b6-bf76-cc8de3ffb2cf.png)

### Steps to reproduce

Run the master branch project browser

### Minimal reproduction project

None

**Comment by mashumafi** [comment]
Looks like other areas affected: https://github.com/godotengine/godot/pull/73736#issuecomment-1440206948

**Comment by YuriSizov** [comment]
Yes, it's the same issue. cc @bruvzg @RandomShaper for you to track something.
