### ISSUE TITLE
ColorPicker moves to the right and down when I change tabs and then back

### ISSUE THREAD

**Issue by ShatReal** [godotengine/godot#73791]
### Godot version

4 release candidate 3

### System information

win 11

### Issue description

When I make a colorpicker as root node and then change tab and then change back, it's moved down and to the right.

### Steps to reproduce

1. Make scene with colorpicker as root node
2. make another scene
3. switch back to first scene
4. switch to second scene
5. repeat 3-4

### Minimal reproduction project

N/A

**Comment by ShatReal** [comment]
This is still an issue on rc4 and rc5. Also, here is a video demonstrating the problem.


https://user-images.githubusercontent.com/69117768/221259603-073028ba-b1d4-4539-bc3c-344c944158ed.mp4

**Comment by ShatReal** [comment]
Also on r2. And on 3.5.1???

**Comment by TheSecondReal0** [comment]
This has been a bug for a very long time, I reported it a while ago here: #62937

**Comment by ShatReal** [comment]
Whoops
