### ISSUE TITLE
.mod playback broken in EventPlayer

### ISSUE THREAD

**Issue by spookdogg** [godotengine/godot#7379]
**Operating system or device - Godot version:**
Windows 7 - 2.1.1

**Issue description** (what happened, and what was expected):
Playing .mod files with EventPlayer causes the audio to be extremely distorted

**Steps to reproduce:**

**(WARNING: Low volume is recommended)**

Create an EventPlayer node
Load .mod file into EventPlayer via Stream property
Tick Autoplay
Test scene

**Comment by sboukortt** [comment]
For me, on Linux with 2.3.1, they don’t play back at all.

**Comment by Noshyaar** [comment]
Closing as EventPlayer is no more in 3.0
