### ISSUE TITLE
from 3.3 (or 3.5) to 4.0

### ISSUE THREAD

**Issue by rodell2022** [godotengine/godot#73790]
### Godot version

3.3 stable and 3.5.1 stable 

### System information

windows (of any kind)

### Issue description

how about [A] allowing anyone using 4.0 to pick at the start (or switch later) the option of using GLES3 instead of Vulkan  
[B] allowing them the option of picking 3.3 or 3.5.1 or 4.0  
[C] when starting project/project settings display windows swhitch Vsnc off and turn on Allow Hipi
  [windows of any kind: if you use Vsnc it draws a white screen with nothing else, so we have to go and switch it manualy to
  see any thing.  be fair to us and in the windows version auto set it..

[D] how about a website or [tutorial] like this
in 3.3 or 3.5.1                                                                                4.0
  you would use 
var velocity = Vector2(0,0)
var gravity = 35
var jumpforce = 1100

func _physics_process(delta):
if Input.is_action_pressed("right"):
velcocity.x = 35
if Input.is_action_pressed("left"):
velocity.x = -35
if Input.is_action_pressed("jump"):
velocity.y = jumpforce

that is just character movement
  it would be very helpful to do that for everything we do in 3.3 or 3.5.1 
  

### Steps to reproduce

take time to think not everyone has brand new video cards.. (the old ones can not do Vulkan of any kind with out crashing  in windows  [i do not know about mac because i do not have a mac computer] 
  most of use we spent months + learning 3.3 or 3.5.1 it is a major pain in the a.. to move over to 4.

### Minimal reproduction project

Not sure about this section

**Comment by Calinou** [comment]
Godot 4.0 already features a GLES3 renderer, which you can choose in the project creation dialog by choosing the **Compatibility** rendering method.

Allow Hidpi is also enabled by default in 4.0 already, but this can't be done in 3.x without breaking compatibility with existing projects (unless using the approach described in https://github.com/godotengine/godot-proposals/issues/4834 to only affect newly created projects in 3.6).

**Comment by clayjohn** [comment]
We will continue to support 3.x at least for awhile and still have a 3.6 release planned. The only reason to move to 4.0 is if you want to take advantage of the new features. There is nothing wrong with remaining with 3.x. 

That being said, 4.0 is shipping with an OpenGL compatibility backend so people on devices without Vulkan support can still use 4.0.

**Comment by Zireael07** [comment]
@Calinou Telling people that Godot 4 features GLES 3 renderer when it misses a fundamental functionality such as 3D shadows is a bit... iffy.
