### ISSUE TITLE
[Android Editor] crashing after creating a new AudioStreamMicrophone

### ISSUE THREAD

**Issue by ArkellArt** [godotengine/godot#73801]
### Godot version

v3.6.beta.custom_build [42083f3a6]

### System information

Android 11, MediaTek Helio P35 (32bit), PowerVR Rogue GE8320, also tested on: Android 10, Snapdragon 636, Adreno 506,

### Issue description

When trying to use the microphone input in an AudioStreamPlayer node on the godot android editor, unexpectedly crashes after a few seconds regardless of whether it is a new project or not. 
If the initial scene has an AudioStreamPlayer node configured with an AudioStreamMicrophone it will continuously close, not allowing to start.

### Steps to reproduce

1: Create a new project or use a existent one.
2: Press "Project" and "Project Settings"
3: Go to "Audio" and activate "Enable Audio Input"
4: After restarting, create an AudioStreamPlayer Node
5: On Stream, add a new AudioStreamMicrophone

Wait a few seconds until it crashes

### Minimal reproduction project

Use a New Project

**Comment by m4gr3d** [comment]
This could be an issue due to the lack of microphone permission in the Android editor, I'll take a look.

**Comment by ArkellArt** [comment]
> This could be an issue due to the lack of microphone permission in the Android editor, I'll take a look.

It still happens in the most recent version of Godot 3.6 (beta 2).
I don't know how the audio drivers work as if they work at all, however, if they work, adding the microphone permission in addition to the storage permission may probably fix the problem.
