### ISSUE TITLE
GDscript tokenizer : inconsistent rules for underscore usage in numbers

### ISSUE THREAD

**Issue by AdrienQuillet** [godotengine/godot#73804]
### Godot version

4.0

### System information

All OS/Hardware

### Issue description

Not sure if it's a bug / inconsistency or a willingness 😄

When writing numbers in GDScript, we can use `_` character to make number more readable for a human. Rules for this character differ depending on where it is used : before or in decimal part, making its usage inconsistent. 
- When use before decimal part, only an underscore can not follow another undersocre
- In decimal part, multiple underscores can be write without any complaint of tokenizer

### Steps to reproduce

Here is test functions to illustrate

```gdscript
func test_number_allowed_without_error() -> void:
    var a:int = 1_2_3_4_5_6
    var b:int = 123_456
    var c:int = 1.2_3_4_5_6
    var d:int = 1.2_____3_____4____5_____6
    var e:int = 1._2_3_4_5
    var f:int = 1.________23456

func test_number_not_allowed() -> void:
    var a:int = 1__2
    var b:int = 1__2.1__2
    var c:int = _1.23456
```

With a screen to show editor syntax errors

![image](https://user-images.githubusercontent.com/121614863/220851058-38439a3f-3ba8-40fa-9556-a0faf045c943.png)

### Minimal reproduction project

N/A

**Comment by bitsawer** [comment]
At least this one:

`var c:int = _1.23456`

is not really a bug `_1` is an identifier as it starts with an underscore `_`. Technically that snippet tries to look up variable named `_1` and tries to access its property `23456 `which naturally doesn't work.

**Comment by AdrienQuillet** [comment]
Exact, my bad 👍
