### ISSUE TITLE
2D optimizations issue on Adreno ("SnapDragon") GPUs 

### ISSUE THREAD

**Issue by nx7r** [godotengine/godot#73805]
### Godot version

4.0 rc3

### System information

SD 860, SD 665, SD 662, GL/Mobile rendering device

### Issue description

When any kind of 2D light is added to the scene, the frame rate drops to 9fps

Note : My device [xiaomi POCO X3 Pro](https://www.gsmarena.com/xiaomi_poco_x3_pro-10802.php)

### Steps to reproduce

1. add PointLight2D to the scene
2. export the project to Android device wich have a SnapDragon CPU
3. than all magic will happen (fps drops)

==> Running this demo on that devices will make the same issue:
[https://github.com/godotengine/godot-demo-projects/tree/master/2d/lights_and_shadows](url)

### Minimal reproduction project

[https://github.com/godotengine/godot-demo-projects/tree/master/2d/lights_and_shadows](url)

**Comment by clayjohn** [comment]
Have you tested both the mobile renderer and the gl_compatibility renderer? Note: you have to change the ``rendering_method.mobile`` setting in order to change the renderer on mobile. Changing just ``rendering_method`` isn't enough

**Comment by nx7r** [comment]
Yes, I have played with all the settings but the problem remains.

**Comment by nx7r** [comment]
@clayjohn Yes, I  have tested both mobile and  gl_compatibility renderer.

**Comment by nx7r** [comment]
@clayjohn Yes, I have tested both mobile and gl_compatibility renderer.

**Comment by nx7r** [comment]
@clayjohn Yes, I have tested both mobile and gl_compatibility renderer.

**Comment by clayjohn** [comment]
And you are getting exactly 9 FPS on both backends?

**Comment by nx7r** [comment]
@clayjohn not exactly: fps_range[9, 18]

**Comment by Calinou** [comment]
Can you reproduce this with a lower rendering resolution? Set the stretch mode to `viewport`, then export the project to Android again.

**Comment by clayjohn** [comment]
Tested on an Adreno 640 device and had a consistent 11-12 FPS, with https://github.com/godotengine/godot/pull/100302 its now locked at 60 FPS
