### ISSUE TITLE
WebSocketMultiplayerPeer server crashes if it's configured with a TLS certificate.

### ISSUE THREAD

**Issue by Vsono** [godotengine/godot#73810]
### Godot version

4.0.dev

### System information

Windows 10

### Issue description

If a WebSocketMultiplayerPeer server is configured with a TLS certificate, the program crashes whenever a client tries to connect.
I don't get any error messages (which is driving me crazy)

I tried with a self-signed (in Godot) certificate and a properly signed Let's Encrypt certificate, but same results.

### Steps to reproduce

1. Configure a WebSocketMultiplayerPeer server with a TLS certificate
2. Try to connect to the server

### Minimal reproduction project

[test_client.zip](https://github.com/godotengine/godot/files/10812125/test_client.zip)
[test_server.zip](https://github.com/godotengine/godot/files/10812126/test_server.zip)

**Comment by Vsono** [comment]
https://github.com/godotengine/godot/blob/19c9fd6926b958016d562e3b2e93b0e9480300f5/modules/websocket/websocket_multiplayer_peer.cpp#L336-L350

Is line 345 causing the problem?

**Comment by akien-mga** [comment]
CC @Faless 

> 4.0.dev

Please be explicit about the commit hash, "4.0.dev" spans 3 years of development.

**Comment by Vsono** [comment]
> Please be explicit about the commit hash, "4.0.dev" spans 3 years of development.

4.0-rc3 and the latest commit https://github.com/godotengine/godot/tree/19c9fd6926b958016d562e3b2e93b0e9480300f5

**Comment by akien-mga** [comment]
Fixed by #73811.
