### ISSUE TITLE
You cannot load a vehicle wheel externally from a different scene

### ISSUE THREAD

**Issue by bkeys** [godotengine/godot#7381]
**Operating system or device - Godot version:**
Godot 2.1.1, Fedora 25

**Issue description** (what happened, and what was expected):
I am trying to make cars customizable and have the chassis/wheels be swappable, so I tried to load tires into a scene and get it to work however it appears like you cannot load vehicle wheels from a different scene and have the physics still apply

**Steps to reproduce:**
You could manually make a scene that has a vehicle wheel, and a graphical mesh if you want something visible; load it into a separate scene containing a vehicle and attach it as a child. You could also import my project into Godot and see the issue for yourself.

**Link to minimal example project** (optional but very welcome):
https://notabug.org/bkeys/DMUX

**Comment by bojidar-bg** [comment]
Probably related/duplicate of #2314. (but, read first for yourself before closing).

**Comment by bkeys** [comment]
It kind of is a duplicate, but at the same time that issue does not mention that there is also the same issue in regard to vehicle wheels so perhaps this is all things that are in the physical world. I will comment on that issue and close this one
