### ISSUE TITLE
Game crashes without error when initial value of @export is set to get_parent().

### ISSUE THREAD

**Issue by ya-paint** [godotengine/godot#73822]
### Godot version

4.0.RC3

### System information

Windows10

### Issue description

If the initial value of @export is set to get_parent() the game will crash without error.

res://class/custom_class.gd
```
extends Node

class_name CustomClass

```

res://error_script.gd (Assigned to a child node of a custom node in the main scene.)
```
extends Node

@export var custom_node : CustomClass = get_parent()
```

I know Godot can't use get_node() with @export. 
I suspect Godot is not implementing an error when using get_parent() with @export.

### Steps to reproduce

An error occurs when I write the script below.
```
@export var custom_node : CustomClass = get_parent()
```
You can reproduce it as is in the sample project.

### Minimal reproduction project

[error_sample.zip](https://github.com/godotengine/godot/files/10815535/error_sample.zip)

**Comment by anvilfolk** [comment]
Actually, only RC3 has this issue. RC1, RC2, RC4, RC5 and `master` all work, so it's likely due to a fixed regression in RC3 :)
