### ISSUE TITLE
Is this behaviour of System.Console.WriteLine expected?

### ISSUE THREAD

**Issue by nightblade9** [godotengine/godot#73833]
### Godot version

4.0 RC2 official binaries

### System information

Windows 10 and Manjaro (Arch) Linux

### Issue description

When you run Godot with `--quiet 2>/dev/null` (or the equivalent on Windows), nothing is supposed to be printed out. But, calls to `System.Console.WriteLine(...)` still print out.

Is this expected? Can I rely on this behaviour?

I'm in the process of making a game for blind players, and I need a "clean" console - something that doesn't have any text from Godot (e.g. the intro "Vulkan running ..." text), warnings, or errors printed out. I need full, 100% control over the console window output (and I'm using it to accept player input via text).

### Steps to reproduce

Create a new Godot C# project with a scene that has this script:

```
public override void _Ready()
{
    System.Console.WriteLine("Hello, World!");
    GD.PushError("ERROR!");
    GD.PushWarning("Warnings?");
    Godot.GD.Print("HI!!!!");
}
```

- Export it to Windows or Linux
- Run the exported versions with the additional command-line parameters: Windows (`--quiet 2>out.txt`) or Linux (`--quiet 2>/dev/null`)
- Observe: `Hello, World!` prints on the console, without any other warnings or text (e.g. Godot 4 running with Vulkan)

### Minimal reproduction project

[poc2.zip](https://github.com/godotengine/godot/files/10817788/poc2.zip)

**Comment by raulsntos** [comment]
Yes, this is expected behavior.

- `System.Console.WriteLine` writes to _stdout_.
- `System.Console.Error.WriteLine` writes to _stderr_.

You are using `2>` which silences **only** _stderr_. To silence _stdout_ use `1>`.

**Comment by nightblade9** [comment]
Great, thanks. So to re-iterate, I can expect this behaviour to continue in the foreseeable future, correct?

**Comment by Calinou** [comment]
> So to re-iterate, I can expect this behaviour to continue in the foreseeable future, correct?

Yes, although we can't guarantee this.

**Comment by nightblade9** [comment]
> Yes, although we can't guarantee this. See also #63575.

I read through that and don't see the relevance, other than the fact that I should specify `--no-header` and `--quiet` both.

Can you clarify? Are you saying "We can't guarantee [-q will remove the header]" or "We can't guarantee [-q will prevent System.Console.WriteLine from writing to the console]", or something else?

**Comment by Calinou** [comment]
> Can you clarify? Are you saying "We can't guarantee [-q will remove the header]" or "We can't guarantee [-q will prevent System.Console.WriteLine from writing to the console]", or something else?

`-q` is designed to silence stdout but not stderr. You can also disable stderr using a project setting:

https://github.com/godotengine/godot/blob/e930c8d3838280e40baabc4426bd8236f7ac50a3/doc/classes/ProjectSettings.xml#L284-L291

**Comment by nightblade9** [comment]
Right. So if my goal is to have total control over the console output, I should:

- Disable stderr and stdout via the `application/run/disable_*` settings
- Use `--no-header` when it comes out
- Print to the console via `System.Console.WriteLine`

And this behaviour is expected to be consistent going forward. Is that correct?

**Comment by Calinou** [comment]
> And this behaviour is expected to be consistent going forward. Is that correct?

Yes, hopefully. Note that disabling stdout will already disable the header, so you don't need `--no-header` in this case.

**Comment by nightblade9** [comment]
Thank you very much for the feedback.

One caveat: disabling `stdout` via the project properties disables it in the editor, but not in the exported project; meaning, you can't easily debug in-editor and expect to see that in the output.

For now, I'm using a wrapper method that calls both `System.Console.WriteLine` and `Godot.Print`; the former appears in exported versions, the latter in-editor.
