### ISSUE TITLE
ConfigFile - end of file bug causes infinite loop

### ISSUE THREAD

**Issue by Listwon** [godotengine/godot#7383]
**Operating system or device - Godot version:**
Windows 10 Pro 64-bit, Godot 2.1-2.1.1

**Issue description** (what happened, and what was expected):
Loading multiple *.cfg files sometimes causes "Not responding" (game hangs up on splashscreen, possible infinite loop). There must be something wrong with ConfigFile and Windows eof implementation (I can't reproduce that on Linux), because it can be fixed by adding empty line at the end of all loaded *.cfg files.
https://github.com/godotengine/godot/blob/c05ff0577fd9cc39a6968e65743f7d7da711bfe2/core/io/config_file.cpp#L156

**Steps to reproduce:**
1. Prepare some valid *.cfg files without empty lines at the end. 
2. Load them all at once as in example http://docs.godotengine.org/en/stable/classes/class_configfile.html

**Comment by bojidar-bg** [comment]
Does it happen by any chance with regular `File` objects as well?

**Comment by Listwon** [comment]
@bojidar-bg I can't reproduce it with File although I load multiple *.csv files in my projects and tried to "break" them by removing the empty line.

**Comment by hpvb** [comment]
I've tried to reproduce this issue on master but I can't. Would you be able to share the config files that are causing this problem and the gdscript file to load them?

**Comment by reduz** [comment]
the parsing code on master was rewritten entirely, so for now I will consider this closed. Please open if anyone can reproduce
