### ISSUE TITLE
[Godot 4 RC4] Iterating over an array backwards doesn't work anymore

### ISSUE THREAD

**Issue by el-falso** [godotengine/godot#73837]
### Godot version

v4.0.rc4.official [e0de3573f]

### System information

Windows 11, Forward+

### Issue description

For my actual game I iterate over an PackedVector2Array backwards, but this happens:

> Invalid type in GDScript utility function '<unknown function>'. Cannot convert argument 3 from PackedVector2Array to float.

Because of this I took the code example of the range function for iterating backwards from the docs page, but now it gives me this error:

> Invalid type in GDScript utility function '<unknown function>'. Cannot convert argument 3 from Nil to float.

![Godot_v4 0-rc4_win64_k40kH6Sgmk](https://user-images.githubusercontent.com/5958083/221021782-fa8c6b60-b259-4573-b92b-202f4973f4bc.png)

I think it has something to do with the recent changes to the range function.

### Steps to reproduce

Simply copy the code from the range() documentation page and tada...

```
var array = [3, 6, 9]
for i in range(array.size(), 0, -1):
    print(array[i - 1])
```

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
What's the last version you tried where it worked fine?

**Comment by el-falso** [comment]
In RC3 everything was working fine, both my code and the mentioned code sample from the range() documentation page.

**Comment by akien-mga** [comment]
Likely a regression from https://github.com/godotengine/godot/pull/73796, CC @vonagam @vnen.

**Comment by mbrealm** [comment]
Can confirm this regression on Linux too, from RC3 to RC4.

Same error message as in screenshot above.

When I initially tried to fix by casting the arguments to `int`, I got an error message about there not being a int constructor. I think this was manifesting on trying to make the -1 step argument `int(-1)`. Not sure if this constructor error may point to some other lurking bug. I will retry on the RC5.

**Comment by MikeSchulze** [comment]
This bug is critical!
It crashes Godot when using `@tool` in your script.

Load the project and try to open the scene, .. instand crashes the application
[RangeIssue.zip](https://github.com/godotengine/godot/files/10822432/RangeIssue.zip)

```
SCRIPT ERROR: Invalid type in GDScript utility function '<unknown function>'. Cannot convert argument 2 from PackedStringArray to float.
          at: _ready (res://RangeCrash.gd:9)
```



Without `@tool` it shows an runtime error
`Invalid type in GDScript utility function '<unknown function>'. Cannot convert argument 2 from PackedStringArray to float.`

**Comment by Gnumaru** [comment]
Please note that this bug can be circumvented in more than one way. You can either store the output of range in a variable OR you can use the return value of an intermediate function that just return the first parameter without doing anything.

![image](https://user-images.githubusercontent.com/5783414/221165827-0b94a018-1649-4684-82e5-ebb04b1ebba0.png)

**Comment by akien-mga** [comment]
To be clear, we know why this bug happens, and there's already a PR to fix. It's just pending review, and a fix will be included in the next build.

**Comment by MikeSchulze** [comment]
Thanks!
