### ISSUE TITLE
expose EditorAutoloadSettings to gdscript

### ISSUE THREAD

**Issue by Salvakiya** [godotengine/godot#7384]
**Autoload for plugins**

**feature description** :
have the ability for plugins to setup their own autoload scripts.

if I install and activate plugin "test" for my project... test should also setup its own autoload script.

to do this we need to expose EditorAutoloadSettings to gdscript

**Comment by Noshyaar** [comment]
Closing as fixed by #16709. Please let us know if this is mistaken.
