### ISSUE TITLE
Invalid call. Nonexistent function 'new' in base 'Nil'. if you use @export_group with same class name

### ISSUE THREAD

**Issue by Ughuuu** [godotengine/godot#73843]
### Godot version

4.0 RC 3

### System information

Macbook m1

### Issue description

If I normally use:
```
Skeleton2D.new()
```

if works.

If I use:
```
@export_group("Skeleton2D")
...
Skeleton2D.new()
```

I get error: `Invalid call. Nonexistent function 'new' in base 'Nil'.`

### Steps to reproduce

- Run a script where you have `@export_group` with same name as a node class name that you use `.new()` on.

```
extends Node2D
class_name Test

@export_group("Skeleton2D")

# Called when the node enters the scene tree for the first time.
func _ready():
	var skeleton = Skeleton2D.new()


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	pass
```

### Minimal reproduction project

[BugNew.zip](https://github.com/godotengine/godot/files/10818936/BugNew.zip)

**Comment by anvilfolk** [comment]
I believe that the script is checking for its own properties, and export group is effectively exporting a property named `Skeleton2D`. This will shadow the global `Skeleton2D`. I'm not certain that I'd consider this a bug necessarily, but perhaps at least a warning when `@export_group` shadows a global name?

**Comment by YuriSizov** [comment]
Reopened because https://github.com/godotengine/godot/pull/73870 has been reverted.

**Comment by PoolloverNathan** [comment]
Bumping this, since [someone came to Discord for help](https://discord.com/channels/212250894228652034/908062856459743262/1087186462862221383) due to this.

**Comment by Shadowblitz16** [comment]
> Bumping this, since [someone came to Discord for help](https://discord.com/channels/212250894228652034/908062856459743262/1087186462862221383) due to this.
Yep it was me.
