### ISSUE TITLE
HTML5 On Chrome On Android Mobile Devices - Device Turns Off Screen, But Music Still Plays? - Dead Battery...

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#73858]
### Godot version

v4.0.rc4.official [e0de3573f]

### System information

HTML5/Android Mobile Devices/Chrome

### Issue description

HTML5 On Chrome On Android Mobile Devices - Device Turns Off Screen, But Music Still Plays? - Dead Battery...

### Steps to reproduce

1. Visit:  https://betamaxheroes.org/  on desktop/laptop computer.
2. Turn on Android smartphone or tablet and open "camera" app.
3. Scan with mobile device's rear camera the QR Code on above website.
4. Allow URL to open on mobile device's default Internet browser(we have Chrome for Android).
5. Website will open on mobile device.
6. Tap on the screenshot of the game to run HTML5 version on your mobile device.
7. Choose "touch" input(bottom selection).
8. With no user input, the device will shut off screen, but music is still playing?
9. DEAD battery if left alone for half a day or night(perhaps user fell asleep?)

### Minimal reproduction project

N.A.

**Comment by clayjohn** [comment]
Could you please upload an MRP and provide more information about the situation that causes the issue?

For example, what kind of elements are in the problematic scene?

What renderer are you using? 

What is the hardware of the device you tested on?

It sounds like the game is running, but with a black screen, so it would be useful to provide more information about the game so we can figure out why the screen is black. 

As it is there isn't enough information for a contributor to even begin investigating what is causing this issue for you
