### ISSUE TITLE
Projects permanently removed off project manager if drive not mounted

### ISSUE THREAD

**Issue by balloonpopper** [godotengine/godot#7386]
Godot 2.1.1 - Windows 10
I have my list of projects in the project list including one on a network drive (T).
If T drive isn't mounted when Godot is started, the project entries are permanently removed from the project list. Mounting the drive then restarting Godot doesn't make them reappear - they have to be reimported.
I would expect them to still be listed and fail to load if clicked. 
I know you can scan for them again, but I consider this a bug.

**Comment by akien-mga** [comment]
Duplicate of #3866.
