### ISSUE TITLE
Godot Android Editor's pan and scale half-works

### ISSUE THREAD

**Issue by Solutionful** [godotengine/godot#73867]
### Godot version

Godot 4.0 RC 4

### System information

Xiaomi Pad 5, Adreno 640

### Issue description

Good afternoon,

I have this problem with godot where selecting nodes using a touchscreen is basically impossible, because for some reason it starts to pan instead of selecting.

And using the two-fingers gesture to pan produces a weird effect, here's a video for a more visual example 

https://user-images.githubusercontent.com/34092413/221162971-a7fa2205-5405-47d8-a434-5d5bf101b2f2.mp4

I tried to toggle the pan-and-scale gesture from the Editor's settings, but no effect is seen

### Steps to reproduce

1- Install Android Godot Editor 4 RC 4
2- Try to select stuff with a touchscreen 

### Minimal reproduction project

N/A

**Comment by m4gr3d** [comment]
Fixed by https://github.com/godotengine/godot/pull/75718
