### ISSUE TITLE
TypedArray with a custom Resource fails to add element

### ISSUE THREAD

**Issue by MunWolf** [godotengine/godot#73864]
### Godot version

4.0 rc3

### System information

Windows 10

### Issue description

I have a resource as follows
```
extends Resource

class_name PieceStructure

@export var blocks : Array[Vector2i] = []
```
and in a separate script I have
```
@export var pieces : Array[PieceStructure] = []
```
It shows up correctly in the inspector but whenever I try to either add an existing resource from the file system or hit New PieceStructure in the array element I get the following error
```
  Attempted to set an object into a TypedArray, that does not inherit from 'GDScript'.
  core/variant/array.cpp:413 - Condition "!_p->typed.validate(value, "set")" is true.
```

### Steps to reproduce

Trivial, make one resource script and a node script.
add a class_name to the resource script so we can reference its type
export a typed array of the resource script type
try populating it in the inspector

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
Please provide a reproduction project, this might seem like trivial steps but the exact way you set things up have a big impact on this feature.

**Comment by MunWolf** [comment]
I have been unable to reproduce this in my original project or a test one...
which is annoying as this happened at the start of a project and I really did not have anything outside of what I posted above.

Closing this for now until I am able to reproduce it again

**Comment by akien-mga** [comment]
Yes, then it's likely a known issue. After create a new `class_name`, you need to restart the editor before it's fully usable everywhere. Otherwise some cached values still miss it.
