### ISSUE TITLE
No way to access ResourceUid class in C#

### ISSUE THREAD

**Issue by AhNesh** [godotengine/godot#73879]
### Godot version

4.0.rc4.mono

### System information

Windows 10

### Issue description

In C#, I can't find anywhere to get the instance of the ResourceUid singleton. I believe this class is supposed to be static, but it currently isn't.

### Steps to reproduce

`ResourceUid.IdToText(text);` <- Cannot access non-static method 'IdToText' in static contex.
`var tmp = new ResourceUid(); `<- Cannot access internal constructor 'ResourceUid()' here.
`var tmp = GD.ResourceUid;` <- No such property/method as far as I can tell, on GD and elsewhere.

### Minimal reproduction project

N/A

**Comment by raulsntos** [comment]
This class is indeed registered as a singleton so it should be generated as static, but it currently doesn't because it tries to find it in `Engine` with the C# name (`ResourceUid`) instead of the C++ name (`ResourceUID`). A regression from https://github.com/godotengine/godot/pull/69547.
