### ISSUE TITLE
ButtonArray aligmnent issues

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#7387]
Seen on Godot 2.1.1

ButtonArray text alignment is always set to left and there is no option in the editor to change it.
Align modes have been exposed but have no effect.
Side note: the aligment is not initialized in the C++ constructor so it's most of the time set to BEGIN, by guess.

**Comment by volzhs** [comment]
I worry about changing default value.

**Comment by Zylann** [comment]
I took a look at Godot 2.1 and there is an `align` property set to `Begin` by default, indeed.
However, this property actually doesn't control alignment of text in the buttons, but the whole widget, somehow. Text is always centered correctly inside buttons.

Also I realize `align` is not missing, I was assuming that because I missed the part where it's listed manually in `_get_property_list`. But there is a clear difference between 2.1 and 2.1.1:

In 2.1, it looks normal and Align has a visible effect on the position of the whole widget:
![buttonarray_21](https://cloud.githubusercontent.com/assets/1311555/21553002/f37fc182-ce05-11e6-8808-1f9d73f8b40b.png)

In 2.1.1, text is tied to the left and `align` doesn't seem to have any effect.
![butonarray_211_bug](https://cloud.githubusercontent.com/assets/1311555/21552993/ccbb168c-ce05-11e6-9678-bb9b1c7ce721.png)

**Comment by akien-mga** [comment]
Works fine in 2.1.4:
![image](https://user-images.githubusercontent.com/4701338/32862502-93315a34-ca58-11e7-9103-7edcebe109f8.png)
