### ISSUE TITLE
Godot 4 RC3 and RC4 Several builds and attempts to install when trying to remote debug in Android in Linux system

### ISSUE THREAD

**Issue by robherre** [godotengine/godot#73886]
### Godot version

Godot 4 RC3 and RC4

### System information

Pop OS

### Issue description

When selecting "Remote Debug" to Android device, in my case, to PICO 4 VR glasses, Godot builds and tries to install a lot of times. Finally the game installs and runs in the device. If you stop the several attemps with the "Esc" key in Godot window it runs as well.

In my system until Godot 4 RC2, included, and including all the betas or in any Godot 4 version in Windows, the same projects work fine, build, install and run in VR glasses at first attempt.

### Steps to reproduce

Select "Remote debug" with any project in POP!_OS 22.04 LTS linux system.

Here a video showing the issue:
https://drive.google.com/file/d/1v3bTlYi3eg4VF18Ssc5wD-1e9cqqPbo7

I attach a image with the final message showed if you let it do all the attemps (the game works in the device after this message window).
![Godot4Issue](https://user-images.githubusercontent.com/12828203/221271420-32612f5d-4bf6-4096-9351-6b0975c2aac9.png)

### Minimal reproduction project

N/A

**Comment by bruvzg** [comment]
Same issue as https://github.com/godotengine/godot/issues/73842, should be fixed by https://github.com/godotengine/godot/pull/73885.
