### ISSUE TITLE
Editor layouts don't work

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#73880]
### Godot version

v4.0.rc4.official [e0de3573f]

### System information

w10 64 with 2 monitors.

### Issue description

The layouts are not loaded.

![Captura3](https://user-images.githubusercontent.com/19652075/221232062-7fff3b04-1d64-4069-b26e-20aa99374675.PNG)

### Steps to reproduce

Just set up your docks and place them on the 2nd monitor.
Save your layout.
Close godot.
Open godot and load the layout.
Nothing happens, the docks are not positioned in the place where they were saved.

### Minimal reproduction project

...

**Comment by Torguen** [comment]
Works fine in v4.4.dev1.official [28a72fa43], I don't know in which version it was fixed

**Comment by Torguen** [comment]
This issue should be reopened.

Layout loading works now but there is still a problem.
Now the layout loading does not work correctly.

1 - Disable the "single window" mode.
2 - Create and save a layout where the script editor is attached to the main editor.
3 - Detach the script editor into a separate window.
4 - Now load the layout saved in step 2 where the script editor is attached to the main editor.

The layout loading will not attach the script editor that you detached from the main editor in step number 3.

**Comment by AThousandShips** [comment]
Please open a new issue with the relevant description
