### ISSUE TITLE
Image expand mode ignored when loaded before adding into tree

### ISSUE THREAD

**Issue by Ryukuzo** [godotengine/godot#73898]
### Godot version

4.0-beta17

### System information

Windows 11

### Issue description

When you instantiate a scene that contains TextureRects with a defined expand mode, and you load the texture before adding the scene in the tree, it basically ignores the expand mode and set it to default.

### Steps to reproduce

- Create a new scene (A)
- Add a TextureRect
- Set its Expand Mode to "Fit Width"
- Assign a script to the scene that loads any image into the TextureRect
- In another scene (B), instantiate A and make sure to load the image
- Add A to B
- Notice the incorrect sizing of image

(Refreshing by hiding and reshowing the texture seems to reload it with correct expand mode) 

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
The steps are confusing. Can you attach a MRP?

**Comment by Ryukuzo** [comment]
I can't seem to reproduce the bug in a general way. It seems to be coming from a very very very specific case and I can't find the combinations to reproduce it yet. I am closing the issue for now until I understand what seems to be happening
