### ISSUE TITLE
Web Editor for rc5 yields 404 on `(Try this for example)` link.

### ISSUE THREAD

**Issue by changeling** [godotengine/godot#73895]
### Godot version

RC5 

### System information

N/A

### Issue description

Clicking on (Try this for example) link in the web editor (RC5) yields a 404. The file https://editor.godotengine.org/releases/4.0.rc5/demo.zip sense to be missing.

### Steps to reproduce

Click (Try ...) link in web editor.

### Minimal reproduction project

Follow link at https://editor.godotengine.org/releases/4.0.rc5/demo.zip

**Comment by akien-mga** [comment]
Indeed, there was no suitable demo ported to 4.0 I could use for builds until now. Should figure it out before stable.

**Comment by changeling** [comment]
@akien-mga I figured. 😃  Just making sure it was on the list.

**Comment by akien-mga** [comment]
Thanks, this was indeed fixed a while ago.
