### ISSUE TITLE
ParticleProcessMaterial, scale unaffects draw pass mesh when using billboard

### ISSUE THREAD

**Issue by warriormaster12** [godotengine/godot#73891]
### Godot version

Godot 4 Rc 5

### System information

Nobara 37 Nvidia Gtx 1060 6gb 525 driver Forward +

### Issue description

Seems to be a regression. Setting scale inside "ParticleProcessMaterial" should change the scale of the mesh but at the moment it seems like mesh's scale is always set to 1.

### Steps to reproduce

1. create a GpuParticle3D node
2. add any mesh to draw pass
3. enable billboarding in mesh's material
4. create ParticleProcessMaterial
5. change scale value

### Minimal reproduction project

-

**Comment by clayjohn** [comment]
Did you also enable "keep_scale" under the billboard properties in the StandardMaterial3D?

**Comment by warriormaster12** [comment]
I tried with and without and issue persisted.

**Comment by Calinou** [comment]
The billboard mode must also be set to Particle Billboard if I'm not mistaken.

**Comment by warriormaster12** [comment]
After testing different versions it seems that 4.0-rc3 is the first version to have this issue. 4.0-rc2 works as should.

- 4.0-Rc3
![image](https://user-images.githubusercontent.com/33091666/221353147-a8ae209e-6070-44ee-932c-cee37e7c50e1.png)
- 4.0-Rc2
![image](https://user-images.githubusercontent.com/33091666/221353188-f3fcd1cf-3488-44f1-aa0b-80a78d47b01f.png)

**Comment by warriormaster12** [comment]
https://github.com/godotengine/godot/pull/65353 could be related to this pull request that got merged in 4.0-Rc3

**Comment by warriormaster12** [comment]
I'm going to retract the statement about trying with keep scaling on and off. Apparently, I didn't try carefully enough so I thought that in both modes it was broken.
