### ISSUE TITLE
"Show children" from the node tree bug

### ISSUE THREAD

**Issue by macramole** [godotengine/godot#739]
I've just compiled the latest version. I'm slowly discovering the new features, they are great.

I want to report a problem using the new "Show children" feature (instead of "open in editor") in the nodes tree. I had an AnimationPlayer inside the node I opened with one animation. I've made a few operations: duplicated the animation several times and edit them. 

When I ran the game the animation hadn't changed. Later I chose "open in editor" and all my operations were missing.

That's it.

Cheers

**Comment by akien-mga** [comment]
Editing instanced sub-scenes has actually been implemented for 2.0, so closing.
