### ISSUE TITLE
Scenes with a tool script become corrupted when it accesses a variable from a parent script

### ISSUE THREAD

**Issue by bakana808** [godotengine/godot#73905]
### Godot version

4.0.rc5 (6296b4600)

### System information

Windows 10

### Issue description

One of the scenes in my project with a tool script started saving a few `= null` lines in its `.tscn` file, causing it to become corrupt and unable to reopen. The game immediately closes when trying to play the scene in this state. These "null variables" can be seen in the inspector:

![image](https://user-images.githubusercontent.com/4042962/221333149-71b904b6-3d77-40ff-8518-0f4eaea4cb78.png)

I've managed to narrow down the cause and found that this happens when the tool script accesses a variable in its parent script. Simply having only the name of the variable on a line is enough to cause a `= null` line in the `.tscn` file. See MRP.

Workaround for now to avoid this bug is to remove the `@tool` annotation. For scenes that have already been corrupted, you can open the `.tscn` file and manually remove the `= null` lines to open it again.

I've only occurred this bug as of 4.0.rc5. I haven't seen it in versions 4.0.rc4 and older.

Thanks

### Steps to reproduce

On a new project:
1. Create the following "parent" script:
```gdscript
class_name Parent extends Node2D
var a = 0
```
2. Create the following "child" script:
```gdscript
@tool class_name Child extends Parent
func fn(): a
```
3. Create a new Node2D scene, and attach the child script
4. Reload the scene (Scene -> Reload Saved Scene)

At this point, a "null variable" should appear in the inspector.

### Minimal reproduction project

This MRP is a simple project that replicates the above steps, but with 4 variables in the parent script instead of 1. Four "null variables" should appear in the inspector.

[bug_scene_corruption.zip](https://github.com/godotengine/godot/files/10830143/bug_scene_corruption.zip)

**Comment by eh-jogos** [comment]
Just found this error as well, but had no idea what was causing it or how to report it! For me the game still runs, but it becomes extremely laggy and choppy, and values that were exported and are valid in the inspector become null when the game is running.

I'm also still able to open the scene after saving it and closing, but it starts do duplicate some nodes that are affected by this, while others lose their script.

**Comment by TheSecondReal0** [comment]
I'm getting the same error, although I'm getting corrupted .tres files when using custom resources

**Comment by Chaosus** [comment]
Regression from 6f2a8434c675b3df2aceca4e5200aaf799eeb2bd, cc @vnen

**Comment by felbecker** [comment]
Reopening the corrupted project with RC3 does NOT fix the issue and potentially makes it worse. The editor now shows `@tool` nodes multiple times in tree view. Selecting one of these duplicates somehow selects all. I am not really sure how to report this properly either. 

I think for now this issue should be communited clearly visible on the RC5 page. I couldn't fix my corrupted project by manually curating `.tscn` files.

**Comment by bakana808** [comment]
In my project I originally ran across the node duplication issue first in a scene that contained a bunch of instanced scenes using these bugged tool scripts. All the duplicated nodes in the tree view have the same name so clicking one of them highlights all of them. This might just be some kind of tree view UI bug as trying to delete one of the duplicates deletes only the one I clicked on - regardless of how many nodes looked highlighted.

In my case I found that these duplicates all had their positions reset to the (0, 0) position, so I was able to box select all of them in the editor view and was able to delete all of them at once.

**Comment by fractalcounty** [comment]
I accidentally opened one of my projects with RC5 earlier today, and it completely corrupted most scenes. Opening it back up in RC4 seemingly made it even worse, and using Git to revert relevant changes didn't seem to help either. Is there an easy workaround here?

**Comment by akien-mga** [comment]
Open the corrupted files and remove the `= null` lines. But if using git, a git checkout should work fine to undo any unwanted changes.
