### ISSUE TITLE
Loading screen too long since Beta 17

### ISSUE THREAD

**Issue by JeanMakesGames** [godotengine/godot#73910]
### Godot version

Godot 4 RC 5

### System information

Windows 11, i5, surface pro 8, 8go RAM, Iris X

### Issue description

I had the loading white screen issue before that has been fixed since the beta 10, but since the beta 17 the loading screen is still extremely long (around 15 to 20 seconds) on surface pro 8 and other laptop I have tried it on with no gpu.

On my gaming pc (with i5 and 3060RTX) it works like a charm, though.

Here's a video to show the issue:

https://user-images.githubusercontent.com/88930512/221343265-e3084a0d-dfbd-41c4-b8a7-8e6f2e0a6dde.mp4

### Steps to reproduce

Just open Godot on a surface pro, or other laptop with no gpu on it.

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
How does loading your full project compare to opening a simple project or a new project? 

From the video it looks like the project manager starts up very fast, so it would be very helpful to identify what elements are making the editor load so slowly. It could be loading resources, or loading scripts etc.

**Comment by JeanMakesGames** [comment]
Hello Clayjohn,
I've recorded a video where I'm creating a new project without any texture nor script and loading the scenes, it has the same issue.

https://user-images.githubusercontent.com/88930512/221344783-59f5c64d-29da-4673-9566-abc731708f73.mp4

**Comment by JeanMakesGames** [comment]
Just to show you: in Godot Beta 16 i was not having that problem:

https://user-images.githubusercontent.com/88930512/221345397-071e7949-9f5e-4f29-bb46-753073ba24d9.mp4

it's only since beta 17 that it has started. At that time I didn't report this as I thought it was a potential temporary regression or something like that, but Godot RC 5 is there and it still has that problem.

**Comment by JeanMakesGames** [comment]
Just tested RC6 and the regression is still there unfortunately.

https://user-images.githubusercontent.com/88930512/221548187-2993f5d7-32ba-426b-bde8-7619c1caa19a.mp4

**Comment by JeanMakesGames** [comment]
Update about Godot 4: the waiting time is gone now! I don't know where the problem was and what has been done but thanks! :)

https://user-images.githubusercontent.com/88930512/222346471-e75510f1-5f3e-4a98-8b08-e34feaea9580.mp4
