### ISSUE TITLE
Vulkan: Game freezes if window vsync mode is set to/from mailbox during runtime

### ISSUE THREAD

**Issue by BluesM18A1** [godotengine/godot#73922]
### Godot version

4.0 RC3 (update: tested on 4.0.2 stable, still persists)

### System information

EndeavourOS Linux, AMD Radeon 5700XT, Vulkan

### Issue description

This may be considered a duplicate of  #70837 or #65391 since they occur under similar circumstances, so feel free to close this if it's deemed too similar, but at any rate here is my experience:
Mailbox vsync appears to work just fine if set with the project settings and left alone.
However if you have vsync options available in-game, I find that all of them are able to be changed at runtime without a hitch, except if your project settings change from something else to mailbox, or if your project settings are set to mailbox and you change to something else. 

The issue does not seem to occur when using the OpenGL (compatibility) renderer.

### Steps to reproduce

-New scene (any type seems to work)
-Attach script to root node, GDscript or C# works (I am using GDscript for this example, C# script is available in the minimal reproduction project)

if you put the line `DisplayServer.window_set_vsync_mode(DisplayServer.VSYNC_ENABLED)`
in the _ready function, the game freezes at the splash screen.

If you do something like the following to get it to happen during _process...
```
var changed = false;

func _process(delta):
	if (!changed):
		DisplayServer.window_set_vsync_mode(DisplayServer.VSYNC_ENABLED)
		changed = true
	pass
```

Then you have a rapidly flickering and garbled screen like the following screenshot, and the following error message
![Screenshot_20230225_050232](https://user-images.githubusercontent.com/36201999/221358384-00e8b350-061a-4e03-ac9a-d1d5481b9a64.png)

```
E 0:00:00:0332   main.gd:7 @ _process(): Condition "swapchainImageCount != sp_image_count" is true. Returning: ERR_BUG
  <C++ Source>   drivers/vulkan/vulkan_context.cpp:1975 @ _update_swap_chain()
  <Stack Trace>  main.gd:7 @ _process()
```

### Minimal reproduction project

[BugTester.zip](https://github.com/godotengine/godot/files/10831213/BugTester.zip)

**Comment by Calinou** [comment]
> The issue does not seem to occur when using the OpenGL (compatibility) renderer.

The OpenGL renderer doesn't support any V-Sync mode other than Enabled yet. I suppose Mailbox/Adaptive can't be implemented with it either, but disabling V-Sync should be implemented in a future 4.x release.

**Comment by BluesM18A1** [comment]
> I can't reproduce this on 4.0.rc [adbabfb](https://github.com/godotengine/godot/commit/adbabfbaa9e7560be279b6824ca725c8cad995bf) (Linux, GeForce RTX 4090 with NVIDIA 525.89.02), but I also get this warning anyway:
> 
> ![image](https://user-images.githubusercontent.com/180032/221369664-ad13b7a5-8bac-410c-97d7-dd79d5c7ca99.png)
> 
> I'm surprised the NVIDIA driver doesn't support mailbox V-Sync on Linux. I'm fairly sure it did at some point…
> 
> > The issue does not seem to occur when using the OpenGL (compatibility) renderer.
> 
> The OpenGL driver probably won't be able to support Adaptive and Mailbox modes (as these are not exposed in a standard fashion with that API), but it should support Enabled and Disabled already from my testing.

I took some time to test swapping vsync modes on another computer I had running Windows 10 and an Nvidia GTX 765M, now that you brought nvidia cards to mind.
Swapping to and from mailbox seems to work without a hitch, but for some reason cannot simply disable vsync. Looks like anything is possible with different driver and hardware configurations.

**Comment by LyonSyonII** [comment]
Happens to me as well, also with an AMD GPU (6700 XT).

Changing to OpenGL (compatibility) fixes the problem.

**Comment by BluesM18A1** [comment]
UPDATE:
> ![image](https://user-images.githubusercontent.com/180032/221369664-ad13b7a5-8bac-410c-97d7-dd79d5c7ca99.png)

Out of curiosity I tried using Wayland instead of X11 to see if that affects the issue since wayland has gotten big updates recently.

Instead of having garbage artifacts on screen like my screenshot, I got this exact warning message you received earlier.
Looks like it could be either driver issues, poor handling on the window manager's end, or a mixture of both.

**Comment by BluesM18A1** [comment]
> @BluesM18A1
> 
> > Looks like it could be either driver issues, poor handling on the window manager's end, or a mixture of both.
> 
> Wayland currently only supports vsync for... many reasons. IMMEDIATE support is coming though: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/18268
> 
> This is intended behaviour and (perhaps surprisingly :P) not NVIDIA's fault.

Ok, so it's most likely an X11 jank issue, besides Wayland still having some ways to go in development.
I faintly remember hearing about a Valve dev who was working on Gamescope arguing with someone on the Xwayland repo over tearing protocol issues too, could be related.

**Comment by BluesM18A1** [comment]
> Mailbox vsync appears to work just fine if set with the project settings and left alone.
Upon closer inspection, this no longer seems to be the case. You either get the freeze+garbled screen or a crash shortly after launching the game.
