### ISSUE TITLE
Signal name in Chinese can't be connected to in Connections dialog

### ISSUE THREAD

**Issue by zuiaiyangyang3** [godotengine/godot#73924]
### Godot version

4.0.RC5

### System information

win10

### Issue description

![QQ截图20230225224058](https://user-images.githubusercontent.com/61361272/221362928-a9a56b79-bbb0-4045-a9aa-9f5869ee128c.png)
![QQ图片20230225224050](https://user-images.githubusercontent.com/61361272/221362930-24318d8f-1008-451d-8c5e-8e30cdd2caa2.png)

### Steps to reproduce

BUG that cannot be in Chinese,,My signal is in Chinese.

When connecting the signal, it cannot be confirmed. It must be in English.

The code can be connected, but it's a little troublesome.

### Minimal reproduction project

When connecting the signal, it cannot be confirmed. It must be in English.

The code can be connected, but it's a little troublesome.

**Comment by zuiaiyangyang3** [comment]
![image](https://user-images.githubusercontent.com/61361272/221363200-cd067ea7-e452-4118-a248-c3a4d62c50c8.png)

**Comment by AThousandShips** [comment]
This is because the check in the dialog has not been updated to support non-ascii, I will take a look at a fix for this

**Comment by AThousandShips** [comment]
Should be solved by #75814
