### ISSUE TITLE
Referencing SCREEN_TEXTURE breaks depth

### ISSUE THREAD

**Issue by mishapsi** [godotengine/godot#73934]
### Godot version

v4.0.rc4.official [e0de3573f]

### System information

Windows 10, Vulkan, Nvidia gtx 750 

### Issue description

I'm quite new to writing shaders, so I don't know if there is a way around this, but just referencing SCREEN_TEXTURE in 4.0 will break the scene depth, you don't have to perform any operation on it.  So I'm wondering what's happening behind the scenes when the engine is explicitly told to grab SCREEN_TEXTURE

Correctly intersecting:

![screen_texture_commented_out](https://user-images.githubusercontent.com/3258353/221369205-d4c94199-b52f-4740-91be-cc1cfb411d68.PNG)

With SCREEN_TEXTURE uncommented:

![screen_texture_uncommented](https://user-images.githubusercontent.com/3258353/221369208-5bc2b2d1-0f08-437e-bdd3-a18e7c819a59.PNG)

### Steps to reproduce

Scene Setup:
Two MeshInstances intersecting

Add this shader to both objects
```GLSL
shader_type spatial;

uniform sampler2D screen_texture : hint_screen_texture, filter_linear_mipmap;

uniform vec3 color : source_color;

void fragment() {
	screen_texture;
	ALBEDO = color;
}
```

### Minimal reproduction project

Just the scene and shader:
[screen_texture_test.zip](https://github.com/godotengine/godot/files/10831762/screen_texture_test.zip)

**Comment by clayjohn** [comment]
When you use the screen texture in a shader the object becomes a transparent object. By default, transparent objects do not write to depth. And they are sorted back-to-front based on the objects position (not based on pixel depth).

You need to set the transparency mode to "alpha prepass" so that depth is written still and proper per-pixel depth testing can be done.

**Comment by mishapsi** [comment]
Ah thank you @clayjohn that helped a bunched
