### ISSUE TITLE
FileSystem has wrong thumbnails for scenes

### ISSUE THREAD

**Issue by ShatReal** [godotengine/godot#73930]
### Godot version

4 rc 5

### System information

win 11

### Issue description

The scenes in my file explorer in Godot have the wrong thumbnails.

![image](https://user-images.githubusercontent.com/69117768/221367429-0ad02474-6533-49c2-9fd2-387a83315c9c.png)

They all have the same thumbnail even though they're different rooms and have a different image for the background.

### Steps to reproduce

I dunno, just make a bunch of scenes?

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
Did this issue repeat?
I think it might be some corrupted preview cache. Re-saving the scenes should fix it.

**Comment by Deozaan** [comment]
Related to #33808?

**Comment by Calinou** [comment]
- Duplicate of https://github.com/godotengine/godot/issues/57321.
