### ISSUE TITLE
ResourceSaver file corruption

### ISSUE THREAD

**Issue by 01010100010100100100100101000111** [godotengine/godot#73938]
### Godot version

4.0 RC5

### System information

Windows 11

### Issue description

When the resource is saved, and the project is then re-loaded, the .res file is reported as corrupted. The issue is not present in Godot 4 RC4. 

There are some other errors when loading the project but they can be ignored (I have a different branch with them fixed and still exhibits the same behaviour) but this is the smallest project I have to show the behaviour 

### Steps to reproduce

Open the project, go to the Inventory Plugin and click save;

<img width="701" alt="image" src="https://user-images.githubusercontent.com/45572181/221370381-f0735ddb-4a47-4d1d-9149-150d1add36f7.png">

Close the project and re-open it, all inventory data is lost;

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/45572181/221370458-cde3bd3a-297e-4b21-bbd3-5cf776a92787.png">
 

### Minimal reproduction project

[Godot4InventoryEditor.zip](https://github.com/godotengine/godot/files/10831815/Godot4InventoryEditor.zip)

**Comment by KoBeWi** [comment]
Might be same as #73905

**Comment by 01010100010100100100100101000111** [comment]
Just been messing with this a bit more, it seems to be specific to the recipe dictionary - saving inventorys and items is fine in both RC4 and 5, I can't seem to narrow it down any further, just adding one recipe entry causes the error

Will update if I find anything else.

**Comment by akien-mga** [comment]
Seems fixed in 1bd0b296e195a622c362a12d8e3dca51e8648578, was likely the same bug as #73905 indeed.
