### ISSUE TITLE
Right-Click Rename Doesn't Work in Scene Editor

### ISSUE THREAD

**Issue by Toyking10** [godotengine/godot#73940]
### Godot version

4.0.rc3.official

### System information

macOS Ventura 13.0.1

### **Issue**

The issue occurs when trying to rename anything in the "scene" tab on the lefthand side of the screen **by right clicking and clicking rename.** Even the main Node2D did not work. It does, however, work if I rename by double clicking the name or by pressing enter (macOS shortcut for rename). If I try to rename something in the FileSystem with right click rename, it works and brings up the  dialog box.

### **Reproducing**
1. Create a new project using the Mobile renderer setting
2. On the left-hand side, click on the 2d option
3. Right click the Node2D and click rename. Nothing should happen.

### Minimal reproduction project

[BugTest.zip](https://github.com/godotengine/godot/files/10831934/BugTest.zip)

**Comment by KoBeWi** [comment]
Fixed by #73885
