### ISSUE TITLE
Type Safety does not show math operations of Vector2is using a variable as type safe

### ISSUE THREAD

**Issue by andre1048576** [godotengine/godot#73951]
### Godot version

Godot 4 RC 5

### System information

Windows 11

### Issue description

Vector2i variables created from equations involving variables of type Vector2i are not shown as type safe.
![image](https://user-images.githubusercontent.com/55166043/221377889-51c23d72-5302-4c6d-81bc-adec25f47fb2.png)
The Godot error checker does identify a variable created this way as a Vector2i, however.
![image](https://user-images.githubusercontent.com/55166043/221377935-dd62be07-f561-4fc3-becb-c72d50419fae.png)

### Steps to reproduce

- Create a new script

- add this code to the script
```
var success := Vector2i(3,5) + Vector2i(5,5)
var failure : Vector2i = success + Vector2i(3,6)
```
- check the type safety color with the line number
![image](https://user-images.githubusercontent.com/55166043/221377986-3fe223ee-a290-41c5-bfbb-f8fc091aebbe.png)
in this example, line 46 is shown as type safe and line 47 is not, although line 47 is a Vector2i

### Minimal reproduction project

N/A

**Comment by monigodote** [comment]
If not related the same problem here, but it seems to happens on any arithmetic operation involving variables:
![type_safe_1](https://user-images.githubusercontent.com/126359484/221382658-eb392397-e93a-4caf-adef-13c04c798fe6.png)

Even if the line is not marked as typed-safe, `z` is effectively treated as an `int`, so it seems it's just a graphical thing:
![type_safe_2](https://user-images.githubusercontent.com/126359484/221382730-cf3ae590-e2a3-4bae-80f5-beaf0e19940c.png)

It happens with variables only, constant values work as expected:
![type_safe_3](https://user-images.githubusercontent.com/126359484/221382768-f1e4ae52-c544-431a-b154-eaf7f76575a5.png)
