### ISSUE TITLE
Remote Inspector chugs while running.

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#7395]
**Operating system or device - Godot version:**
Godot 2.1.1 official
Windows 10 x64

**Issue description** (what happened, and what was expected):
The Inspector chugs while open. all other tabs don't exhibit the same effect.
**Steps to reproduce:**
Run a project while having the remote inspector tab selected.

**Link to minimal example project** (optional but very welcome):
Kind of jarring to look at.

**Comment by bojidar-bg** [comment]
I'm not sure I have seen this, can you give us a screenshot?

**Comment by akien-mga** [comment]
I don't think I've seen that, though I'm not sure what you mean exactly by "chugging". Can you still reproduce it on 2.1.4 or 3.0 RC1?

**Comment by vonflyhighace2** [comment]
No this problem does not appear in 3.0. have not tried 2.1.4 so it might have been fixed with the updated remote debugger.

**Comment by akien-mga** [comment]
Thanks for checking! Closing then.
