### ISSUE TITLE
Exporting a game on a chromebook

### ISSUE THREAD

**Issue by MicahMuffinTop** [godotengine/godot#73952]
### Godot version

3.4.1

### System information

Chrome OS

### Issue description

I don't know how to publish my game on my chromebook but I also don't know how to do the export template thing on chromebook.

### Steps to reproduce

Make a game on a chromebook then export it

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
This is for bugs, please do not use it for instructions or tutorials

**Comment by Calinou** [comment]
Please don't ask support questions here, as this issue tracker is meant to be used for bug reports only. Use one of the other [community channels](https://godotengine.org/community) instead.

PS: You likely want to export for Android, as most Chromebooks can run Android applications if I'm not mistaken. You could also export for Linux, but this will only work if the target Chromebook is running Linux (which is not the case by default).

**Comment by MicahMuffinTop** [comment]
Thank you for letting me know 

I just joined Git Hub a couple days ago so I am still new to this website.
