### ISSUE TITLE
Debug error in Exclusive Fullscreen causes game becoming unresponsive, can't alt tab until process is killed/suspended

### ISSUE THREAD

**Issue by Lippanon** [godotengine/godot#73979]
### Godot version

v4.0.rc5.official [6296b4600]

### System information

Windows 10, Vulkan

### Issue description

When running a project/game from the editor in Exclusive Fullscreen mode, if an error is thrown, the editor won't be brought to the front/top to show where the error is, like normal. Instead, the project/game process will freeze and become unresponsive and one has to wait for the 'not responding' window to close it, or kill the process. 
![image](https://user-images.githubusercontent.com/115422160/221411852-046c6a13-b469-4b26-8c25-a4ea4a0803e2.png)

During this time alt-tab'ing doesn't work for me to go back to the editor (which works fine), I have to Ctrl+alt+del to bring Task Manager with priority (Ctrl+Shift+Esc doesn't work even with Task Manager having 'Always on top' enabled).
This is very annoying when debugging a game in Exclusive Fullscreen mode.

### Steps to reproduce

Enable Exclusive Fullscreen (through code or Project Settings) and run into an error.
Run the MRP, it has an error setup on purpose, and has Exclusive Fullscreen enabled.

MRP code:
```gdscript
extends Control

@onready var throw_error = $doesnt_exist

func _ready() -> void:
	print(throw_error.name)
```

### Minimal reproduction project

[EF bug.zip](https://github.com/godotengine/godot/files/10833748/EF.bug.zip)

**Comment by Calinou** [comment]
This should likely be fixed by making the script error handler cause the window to have fullscreen disabled.

**Comment by 3ter** [comment]
This also happens when setting a breakpoint.

The workaround of course is to set the mode in the project settings to something else than `Exclusive Fullscreen`.

**Comment by Chaosus** [comment]
A linked proposal (probably): 
- https://github.com/godotengine/godot-proposals/issues/6183

**Comment by Chaosus** [comment]
Should be fixed by https://github.com/godotengine/godot/pull/94452
