### ISSUE TITLE
Input.is_mouse_button_pressed Misreports

### ISSUE THREAD

**Issue by Gastronok** [godotengine/godot#7397]
**Operating system or device - Godot version:** Godot_v2.1.1-stable_win64.exe

**Issue description** (what happened, and what was expected): I was trying to detect if the left mouse button was not down, and sometimes it reports that it is not down even when the bit mask claims otherwise.

**Steps to reproduce:** In any project, add the following code to a processing node:
```
func _process(delta):
	if Input.is_mouse_button_pressed(BUTTON_LEFT) == false:
		if Input.get_mouse_button_mask() & BUTTON_LEFT != 0:
			printt(OS.get_ticks_msec(), Input.is_mouse_button_pressed(BUTTON_LEFT), Input.get_mouse_button_mask())
```
Click around a few times -- eventually you'll see printouts claiming that `Input.get_mouse_button_pressed(BUTTON_LEFT) == False` while simultaneously `Input.get_mouse_button_mask() == 1`.

This seems to happen consistently after double-clicks.

**Link to minimal example project** (optional but very welcome):
[Example.zip](https://github.com/godotengine/godot/files/679421/Example.zip)

**Comment by bojidar-bg** [comment]
Some initial debugging: `Input.get_mouse_button_mask` gets the mask directly from the OS singleton, as evidenced by line [475](https://github.com/godotengine/godot/blob/master/main/input_default.cpp#L475)
`Input.is_mouse_button_pressed`, on the other hand, gets the mask from some internal field (line [83](https://github.com/godotengine/godot/blob/master/main/input_default.cpp#L83)), which is updated by input events only, on line [322](https://github.com/godotengine/godot/blob/master/main/input_default.cpp#L322).

I'm not really sure which one is more correct actually..

**Comment by Hinsbart** [comment]
I think what you're observing here are just the mouse button release events.
The moment you let go of the left mouse button, an `InputEventMouseButton` will be sent down the Tree with the properties `pressed = false` and `button_mask = 1`.

So I don't think it's a bug actually.

**Comment by Gastronok** [comment]
Try double-clicking and holding it -- it will frequently continuously print that `Input.is_mouse_button_pressed(BUTTON_LEFT)` is `False` while you have the left mouse button down. For as long as you choose to hold it.

I don't think people will expect code to imply that the left mouse button isn't down while they're actively holding it down. If it's not a bug, it's at least a violation of the principle of least surprise.

**Comment by akien-mga** [comment]
> Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

As there was no update since the previous post, we close this issue.

If it is still relevant in the way it was described and discussed above, please comment to ask for it to be reevaluated. If it is only partly relevant, or if the original issue has changed, it would be better to open a new issue (potentially referring to this one) focused on the current state.
