### ISSUE TITLE
CharFXTransform missing "character" property for RichTextEffects in v4

### ISSUE THREAD

**Issue by naturally-intelligent** [godotengine/godot#73985]
### Godot version

4.0.rc5

### System information

Ubuntu 20.04 LTS (not relevant)

### Issue description

In 4.0 class CharFXTransform:
https://docs.godotengine.org/en/latest/classes/class_charfxtransform.html

We're missing the property "character" that was in v3:
https://docs.godotengine.org/en/stable/classes/class_charfxtransform.html#class-charfxtransform-property-character

Text effects such as Matrix will not work without this data...
https://docs.godotengine.org/en/stable/tutorials/ui/bbcode_in_richtextlabel.html#custom-bbcode-tags-and-text-effects

Or is there is another way to access it? If so it doesn't seem to be documented.

### Steps to reproduce

Not applicable

### Minimal reproduction project

Documentation is sufficient

**Comment by mrcdk** [comment]
It looks like it changed to [`glyph_index`](https://docs.godotengine.org/en/latest/classes/class_charfxtransform.html#class-charfxtransform-property-glyph-index)

**Comment by naturally-intelligent** [comment]
> It looks like it changed to [`glyph_index`](https://docs.godotengine.org/en/latest/classes/class_charfxtransform.html#class-charfxtransform-property-glyph-index)

You're right, thanks. I'll close this issue

**Comment by bruvzg** [comment]
It's changed to `font` and `glyph_index`.  Glyph index is font specific and not necessarily correspond to the single character (e.g., multiple characters combined int the ligature will have single CharFXTransform and index of the ligature glyph).

Check `latest` version of documentation for the updated Matrix example - https://docs.godotengine.org/en/latest/tutorials/ui/bbcode_in_richtextlabel.html

**Comment by naturally-intelligent** [comment]
The new Matrix bbcode doesn't work for me. The end result text is different than original.

Possibly a bug:

`char_fx.glyph_index = get_text_server().font_get_glyph_index(char_fx.font, 1, char_fx.glyph_index, 0)`

Shouldn't this "do nothing"? I get scrambled text here due to different characters being returned. Tried a number of fonts...

**Comment by bruvzg** [comment]
> `char_fx.glyph_index = get_text_server().font_get_glyph_index(char_fx.font, 1, char_fx.glyph_index, 0)`

This should not work, `font_get_glyph_index` takes character code and returns glyph index (these are different things).

**Comment by naturally-intelligent** [comment]
@bruvzg 

Wouldn't that mean that `var value = char_fx.glyph_index` is a mistake in the matrix bbcode? Shouldn't it be getting a character instead of the glyph index? I'm not sure how to get the character from the glyph index...

**Comment by naturally-intelligent** [comment]
If I change the last in matrix to `char_fx.glyph_index = value` instead of calling `font_get_glyph_index` then it works

**Comment by bruvzg** [comment]
> Wouldn't that mean that var value = char_fx.glyph_index is a mistake

This is a mistake, I think code supposed to use time and character range to generate matrix effect, ignoring original glyph index.

> I'm not sure how to get the character from the glyph index

In general, it's not possible to get it in character. Glyph index is content dependent and not always corresponds to the exact character.

**Comment by naturally-intelligent** [comment]
Seems like there should be a `font_get_glyph_index` equivalent function, such as 'font_get_char(glyph_index)'?
