### ISSUE TITLE
Make sound bar look nicer and more intuitive

### ISSUE THREAD

**Issue by bojidar-bg** [godotengine/godot#7398]
**Operating system or device - Godot version:**
All OS-es that can run the editor -- all Godot versions

**Issue description** (what happened, and what was expected):
Currently, we are getting lots of duplicate questions on QA about the red-yellow-green bar in the top-left corner of the editor (e.g. https://godotengine.org/qa/11180/what-this-bar-is-supposed-to-be as a recent one).

Speaking about it with @Einlander on IRC, we decided that it would be better to make it with two bars (for stereo), and to add a sound or headphones icon, just to make it more obvious (@djrm :wink:). E.g.:

![image](https://cloud.githubusercontent.com/assets/5276727/21577047/0bafb046-cf55-11e6-8e0b-5ea1dd0af223.png)

~~**Steps to reproduce:**~~
~~**Link to minimal example project** (optional but very welcome):~~

**Comment by akien-mga** [comment]
A speaker icon would be clearer IMO.

But honestly, did anyone ever use this sound bar? I think everybody thinks it's a kind of RAM usage bar or CPU load bar... Shouldn't we just remove it and/or replace it by something more useful?

**Comment by neikeq** [comment]
Wait... that's a sound bar!?

**Comment by eon-s** [comment]
If possible, I think it would be better if could be made visible when reproducing sounds only, on the debugger part.

**Comment by Dillybob92** [comment]
I remember when  I first saw that thing on the top right I thought it was a FPS meter of some sort

**Comment by djrm** [comment]
@bojidar-bg there is a headphones icon in the icons folder, i made it a while back.

**Comment by djrm** [comment]
i think this can be closed since the sound bar is now gone.
