### ISSUE TITLE
Sprite 3D wrong Flip when stretch mode set to viewport

### ISSUE THREAD

**Issue by ippan** [godotengine/godot#7399]
**Operating system or device - Godot version:**
Custom Build - Commit 86e428eea0b9ef5c1732af3a5c29b5c365fbf6e8

**Issue description** (what happened, and what was expected):
if display - stretch mode set to viewport
Sprite 3D -> Set Billboard Y
it will have a Flip V when play

![sprite flip](https://cloud.githubusercontent.com/assets/2070604/21578167/61fd59a6-cfb1-11e6-87c3-14847f12264e.png)

**Steps to reproduce:**
set stretch to viewport
create a sprite 3d and check Billboard Y

**Link to minimal example project** (optional but very welcome):
[sprite_flip.zip](https://github.com/godotengine/godot/files/679700/sprite_flip.zip)

**Comment by ippan** [comment]
try in Godot 3
Sprite 3D do not have Set Billboard Y property any more.
set Billboard Mode in Material work fine~

I think this issue has fixed~

thanks^^

**Comment by Noshyaar** [comment]
Closing as fixed.
