### ISSUE TITLE
3 to 4 converter alters strings "Room" into "Node3D"

### ISSUE THREAD

**Issue by nezvers** [godotengine/godot#73996]
### Godot version

4 rc5

### System information

Windows 10, all renderers, Nvidia GTX1060

### Issue description

I  did a conversion from RC2 to RC5 via the terminal `--convert-3to4` command.
Then going through changes and things to fix, I saw that Strings in my resources and code, that contain the word 'Room' (With capital -R) get changed into 'Node3D'.
![image](https://user-images.githubusercontent.com/26794315/221426384-e21af9cb-4337-42de-bdbc-5c53b77916ad.png)

### Steps to reproduce

1. Have an older Godot version project.
2. Have exported variable values with String type and contain text with the word "Room"
3. Have String values in code containing the word "Room"

### Minimal reproduction project

"N/A"

**Comment by Zireael07** [comment]
Guessing that's another manifestation of "converter unable to distinguish code and other stuff"

IIRC Godot3 had a special Room node that was discontinued, hence the Room->Node3D rename
