### ISSUE TITLE
Exported node types with a custom type defined by a preloaded const script path can't be selected in inspector.

### ISSUE THREAD

**Issue by SaracenOne** [godotengine/godot#73993]
### Godot version

SHA-1: 1bd0b296e195a622c362a12d8e3dca51e8648578

### System information

Windows 10, Vulkan, Intel® Core™ i7-8700K, Nvidia GTX 1080 (471.11)

### Issue description

Scripts now allow you to export node variables with explicit types, including those defined by scripts. However, while using a script type defined by a class_name will allow expected valid node to be selectable in the inspector, if the type is instead defined by a const, for example:

```
const type_b_const = preload("res://type_b.gd")
@export var type_b: type_b_const = null
```

No nodes with this script attached will be selectable in the inspector.

### Steps to reproduce

Create a node and attach a script to it (we call this script in the example 'type_b.gd')
Create another node, attach another script to it, and export a variable like this:
```
const type_b_const = preload("res://type_b.gd")
@export var type_b: type_b_const = null
```
Attempt to assign the type_b variable the node with the type_b script attached a note that it is not selectable.

### Minimal reproduction project

[TypeSelection.zip](https://github.com/godotengine/godot/files/10834394/TypeSelection.zip)

**Comment by SaracenOne** [comment]
@YuriSizov I can understand wanting to kick this back to 4.1, but I disagree with the notion that this isn't a bug, although I don't know if that comes down to semantics (is divergence from expected operation technically a bug?).

**Comment by YuriSizov** [comment]
The distinction can be hard to make, but in this case it's something that was never implemented, not something that malfunctions. So IMO it's an enhancement of the feature. It doesn't really matter, this is still nowhere near critical to 4.0, and labels don't change that.

**Comment by YuriSizov** [comment]
@SaracenOne Please, don't change the milestone. This is not a blocking issue for 4.0.
