### ISSUE TITLE
3d: certain gizmo's not showing when rendering in compatiblity mode

### ISSUE THREAD

**Issue by Ulugbeg** [godotengine/godot#74005]
### Godot version

v4.0.rc5.official [6296b4600]

### System information

Arch linux, Radeon 680M, latest drivers

### Issue description

With the `Compatiblity` renderer selected, I don't see the handles/controls on, for example, `Path3d` s or `CollisionShape3D` 's. When switching the Renderer to `Mobile` or `Forward+`, I do see them. 

![image](https://user-images.githubusercontent.com/7486114/221438407-27568cd4-999d-44f1-9f22-da9aa56127fa.png)

![image](https://user-images.githubusercontent.com/7486114/221438348-41e4ec78-86cb-400a-b4d1-2c735a27390a.png)

My apologies if this is a known issue, I couldn't find it if it was.

### Steps to reproduce

1. Create a 3D scene with Compatiblity renderer selected
2. Add a Path3D.
3. Add some nodes. Whilst doing so, notice that though the lines appear, no controls/handles at the end of those lines appear.
4. Switch the renderer to `Mobile` or `Forward+`. 
5. Observe the handles are there.

### Minimal reproduction project

[HandlesMissing.zip](https://github.com/godotengine/godot/files/10834773/HandlesMissing.zip)

**Comment by Calinou** [comment]
This is likely due to the same cause as https://github.com/godotengine/godot/issues/73826.

**Comment by clayjohn** [comment]
Yep, tested locally, will be fixed by https://github.com/godotengine/godot/pull/73966
