### ISSUE TITLE
GDScript type changes

### ISSUE THREAD

**Issue by theromis** [godotengine/godot#74013]
### Godot version

4.0.rc5

### System information

Windows 11 and MacOS Ventura (probably all others as well)

### Issue description

Please help me to correct Nakama's client code (works fine in 4.0.rc2)
```
func _safe_ret(p_obj, p_type : GDScript):
	if p_obj is p_type:
		return p_obj # Correct type
```
Gives error `Couldn't find type "p_type" in the current scope.` 

### Steps to reproduce

Put this snippet to any GDScript
```
func _safe_ret(p_obj, p_type : GDScript):
	if p_obj is p_type:
		return p_obj # Correct type
```

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/10835347/Test.zip)

**Comment by YuriSizov** [comment]
You need to use `is_instance_of`. See https://github.com/godotengine/godot/pull/73489.

**Comment by theromis** [comment]
@YuriSizov thank you for quick reply you saved a lot of my time, now it works:
```
func _safe_ret(p_obj, p_type : GDScript):
	if is_instance_of(p_obj, p_type):
		return p_obj # Correct type
```
