### ISSUE TITLE
Valve Index "Knuckles" Grip Force missing from OpenXR interaction profile

### ISSUE THREAD

**Issue by luzader** [godotengine/godot#74023]
### Godot version

4.0 rc 5

### System information

Windows 10, Vulkan API 1.3.205, Forward+, GeForce RTX 3080, Valve Index, Steam VR

### Issue description

The Valve Index "Knuckles" controllers have both capacitive/electrostatic grip sensing and a grip force sensor. 

The current "Squeeze" is accessed at "/user/hand/{side}/input/squeeze/value" but this is only the capacitive proximity reading and will max out at 1.0 if touching lightly. The force with which the grip is squeezed appears[1] to be available at "/user/hand/{side}/input/squeeze/force".

There should be a "Squeeze force" so that this is accessible through a float, just as it is with the trackpad at "Trackpad force".

[1] Someone accessing the grip force using OpenMWVR: https://www.reddit.com/r/OpenMWVR/comments/tdvg40/valve_index_controller_bindings/

### Steps to reproduce

- Attempt to use the Squeeze action with Valve Index controllers.
- Note that the Squeeze action maxes out at 1.0 even though you are only barely touching the grip, this is because it is proximity and not force.

### Minimal reproduction project

N/A

**Comment by luzader** [comment]
This is an MRP/demo code which I used to test the PR I'm about to create. (Remember to put on your headset or no inputs work, maybe other people remember this, but I keep forgetting.)

The grip force/squeeze force appears to be unique to the Valve Index controllers, if the Unity documentation is any indication: https://docs.unity3d.com/Packages/com.unity.xr.openxr@1.0/manual/features/valveindexcontrollerprofile.html

[Valve Index Grip Test.zip](https://github.com/godotengine/godot/files/10949257/Valve.Index.Grip.Test.zip)

**Comment by YuriSizov** [comment]
Fixed by https://github.com/godotengine/godot/pull/74787.
