### ISSUE TITLE
Skeleton3D incorrectly handling last bone of armature

### ISSUE THREAD

**Issue by lobziq** [godotengine/godot#74036]
### Godot version

Godot_v4.0-rc5_win64

### System information

Windows 10, vulkan, RX 570

### Issue description

I have this armature in blender
![image](https://user-images.githubusercontent.com/4528497/221528180-6e0037fc-f747-4cb2-aa75-9d91f7c4e20d.png)

When importing this from blender (additionally i used glb - same) this results in godot not showing last bone in preview, and also not modifying the positions of it correctly having selected it from inspector.
![image](https://user-images.githubusercontent.com/4528497/221530493-d1962a99-f121-429f-8fb1-223efe6f3867.png)

### Steps to reproduce

Open attached project, compare .blend file from it with the .tscn generated.

### Minimal reproduction project

[anim_exp.zip](https://github.com/godotengine/godot/files/10838304/anim_exp.zip)

**Comment by lyuma** [comment]
Godot's armature display is a little confusing at first, but what it renders as bones are actually the connections between bones.

That said, each bone also shows a coordinate axis, and you can see at the tip of the last displayed bone, there is indeed a coordinate axis which shows the direction of the final bone.

Also, if you click the little bone mouse pointer button next to the Skeleton3D menu at the top of the 3D view area, you should be able to select bones and see the gizmo for each bone.

Hope this helps.

is there anything else specific you are running into other than the rendering of the Skeleton not showing leaf bones?

**Comment by lobziq** [comment]
Well, so, yeah, my original problem was the IK. So, if i create an SkeletonIK3D and give it a first bone to the last bone chain, i expect the last bone going to face target location. Instead, the last bone just replicates the transform of the target.

https://user-images.githubusercontent.com/4528497/221571657-30eefe32-ef78-4182-aec3-0814ab9cdfc1.mp4

I started to dig and found that the last bone missing from preview and thought this must be connected?

Attaching updated project with mesh to visualize.
[anim_exp_with_mesh.zip](https://github.com/godotengine/godot/files/10839936/anim_exp_with_mesh.zip)

**Comment by dszhblx** [comment]
@lyuma Is SkeletonIK3D ready in Gotdot 4.0 RC6?

**Comment by lyuma** [comment]
@dszhblx SkeletonIK didn't make the cutoff for release candidate, sorry. Only critical bugfixes were allowed and the changes were too extensive.

We'll try and get in a better implementation as soon as possible, hopefully 4.1 as well as 4.0.x.

**Comment by lobziq** [comment]
@lyuma couple of questions

Do this problem is only because of SkeletonIK3D incorrect behavior? If so, do i need to update the title to reflect this conclusion?
Is there any point of reporting any other skeletonIK3D related problems, or it is reasonable to wait until the "release" of this feature? I have one more bug lookalike thing currently.

**Comment by dszhblx** [comment]
@lobziq As I know，SkeletonIK3D is broken in Gotdot 4.0，and it will be fixed in 4.0.x or 4.1，but it will be replaced with a brand 
 new powerful IK system in 4.x.

**Comment by DillonSteyl** [comment]
I've been encountering a number of issues with SkeletonIK3D and how bones are rotated, etc. not certain if I should raise these as seperate issues - it doesn't seem like there's a comprehensive understanding of what exactly is wrong.

**Comment by lobziq** [comment]
I am sorry, guys, but how is this normal? Went into godot again to make something, got this problem again.
My point, as end user - how is this "intented"? 
I have a bone in blender.
I import model into godot - its gone. 
They are normal in blender, I use them to animate model, BUT, godot got this "architectural decision" - which is confusing and differs from any other engine/3d modelling tool and constantly gives trouble to anyone who is using it. Just deal with it by adding another useless bone on top of it. Yep, sure.

@Calinou how is considered normal? Instead of [fixing / at least accepting the problem] you just okay with the broken state of things.

**Comment by Calinou** [comment]
> @Calinou how is considered normal? Instead of [fixing / at least accepting the problem] you just okay with the broken state of things.

Changing this behavior is [proposal](https://github.com/godotengine/godot-proposals) territory, as many users may be surprised if they suddenly start seeing bones they didn't see previously in their projects.
