### ISSUE TITLE
Unable to operate Window node

### ISSUE THREAD

**Issue by zuiaiyangyang3** [godotengine/godot#74045]
### Godot version

4.0 RC6

### System information

win10 Enterprise edition

### Issue description

![4 0 6A](https://user-images.githubusercontent.com/61361272/221604523-bb4659ea-5982-444a-9a67-d987acfb5e9d.gif)

### Steps to reproduce

null

### Minimal reproduction project

null

**Comment by akien-mga** [comment]
Your videos don't work, and without any other description of the issue, there's nothing we can do.

**Comment by zuiaiyangyang3** [comment]
> 您的视频无法正常工作，如果没有任何其他问题描述，我们将无能为力。

I don't know why mp4 can't be played, so I changed it to zip.

**Comment by FlankeR-46** [comment]
The bottom line is that you cannot select, move and resize the Window node, as well as the nodes that are placed in the Window. Such actions are available only through the Inspector or through the code. It seems to me that I have already seen such an issue somewhere before...

**Comment by ShatReal** [comment]
see #20619

**Comment by YuriSizov** [comment]
Yes, this is a duplicate.
