### ISSUE TITLE
Color picker eyedropper creates a black rectangle on the editor viewport

### ISSUE THREAD

**Issue by MrEliptik** [godotengine/godot#74048]
### Godot version

4.0.rc6

### System information

Windows 10, Forward+, GTX 1070 driver 528.49

### Issue description

As you can see on the screenshot, a black square appears with the message "Color Picking active" at the top.
![color_picker_eyedropper_bug](https://user-images.githubusercontent.com/24484962/221575790-407918f7-1bca-49cc-938d-ffe85082a857.png)
The screenshot has been taken on my ultrawide monitor but it does the same on every monitor I have. Also, if I open up the eyedropper again, the black square takes the whole screen instead of a smaller part. 

From there, pressing escape or clicking anywhere ON the rectangle closes the color picker and removes the black square and the selected color is black. If I click on the editor outside of the black rectangle, the color picker is closed but it doesn't select any color.

I've tested this issue on Windows with RC3, 4 5 and 6 and also with the three renderer available: Forward+, Compatibility and Mobile and the results are the same.

Someone else tried on Linux and had the same problem on the three renderer avaialble: Forward+, Compatibility and Mobile.
Linux config in case it's important:
Ubuntu 22.10 - KDE (X11)
3060 RTX mobile, driver: 525.78.01 

I've seen [this issue](https://github.com/godotengine/godot/issues/70020) that seems somewhat related but they're not decribing the black square that I see.

### Steps to reproduce

In an empty Godot 4 project, try to use the color picker eydropper tool to get a color on the screen

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
CC @bruvzg @KoBeWi

**Comment by bruvzg** [comment]
I can reproduce it on macOS as well (but black rect is covering the top quarter of the window).

I have never looked at the color picker code, but seems like color picker is trying to cover the parent window with a popup and draw copies of the other windows on it, which is a really strange way to do it and will never work (it at least should have a separate window for each screen).

**Comment by KoBeWi** [comment]
I think #72764 last touched this functionality.
I can't reproduce this issue, for me it works without problems. Tested on Windows 10 on master.

**Comment by bruvzg** [comment]
> I can't reproduce this issue, for me it works without problems. Tested on Windows 10 on master.

Try in on the second display or with non-maximized window. It only works if main window is at (0,0) position and on the display which is at (0,0).

**Comment by KoBeWi** [comment]
Ah right 🤔
Although for me only the background is black, the Godot window is intact and picking is still working.
It's weird that everything becomes black, but at least it's functional, idk.

I think the problem is that the picking window does not fit the parent.

**Comment by ababen1** [comment]
I get quick flashes of black on my screen. I tried to capture it on video but the recording program just blacked out until i stopped the color picking

**Comment by KoBeWi** [comment]
What program did you use? I think OBS should be able to handle it.

**Comment by ababen1** [comment]
I used obs yes

**Comment by ababen1** [comment]
I managed to record it using the age old method of recording your screen with a phone camera 

https://user-images.githubusercontent.com/80917990/221607771-2205809a-d12c-461b-bad2-fb70bc9b95a7.mp4

**Comment by couscousyeah** [comment]
I'm the Linux user MrEliptik mentioned, and i tried it without external monitor connected : no black screen anymore, it works as intended.

**Comment by MrEliptik** [comment]
I confirm that disconnecting all my other monitor to keep only one fixes the problem. I see a small rectangle with color being picked isntead of the big black rectangle

![image](https://user-images.githubusercontent.com/24484962/221617037-9d822c43-ddc8-4086-9816-cb46d84aaea9.png)

**Comment by YuriSizov** [comment]
So this seems pretty bad. But I'm also kind of surprised it's only reported now for how bad it is. Let's aim to fix it soon and include in a 4.0.x release.

**Comment by Qubus0** [comment]
It's not only windows (as the tags would suggest). The behaviour is bad in a slightly different way on Mac, so I'm not quite sure that it qualifies as the same bug. Anyway - v4.0.stable. Color picking shifts the whole window area down


also related issue
- #73935



https://user-images.githubusercontent.com/51323316/222938906-43dce778-c7c4-406a-854b-a90f5c086e5c.mov

**Comment by dame-ng** [comment]
I'd like to add that it's not very user friendly that you can't pick colors outside Godot's windows. Everything else turns black even on a single-monitor system, and it doesn't look very good.

**Comment by Qubus0** [comment]
@dame-ng color picking the whole monitor is a whole different beast that requires screen recording to be allowed afaik. Applications can not view outside their windows by design. You will notice The same behaviour in many other applications as well. As much as I would like it too, I think It would be best in a feature request

**Comment by dame-ng** [comment]
@Qubus0 I'm not sure about macOS, but I've done it on Windows without any problems.

![demo](https://user-images.githubusercontent.com/91969109/222939975-6477b5ab-44dd-446e-b180-18616a2f959f.png)

I also use apps that allow to do it, and likely on macOS too (Clip Studio Paint, for example).

**Comment by KoBeWi** [comment]
AFAIK there are some system-specific methods to allow that. GIMP supports it and it works very well, even taking the screen color calibration into account.

**Comment by CatastrophicDino** [comment]
i just used powertoys and copied it from there.

**Comment by joshchristiane** [comment]
Problem is still active and happening as of Godot 4.0.2

**Comment by cobrapitz** [comment]
Can confirm for 4.0.2 stable
Win10 | AMD Ryzen 7 3700X | RTX 3060 Ti and 6600XT | Forward+

![image](https://github.com/godotengine/godot/assets/12397702/a9a425b4-a244-4d40-91be-4cd0b9011557)

**Comment by philoufc** [comment]
4.0.2 stable, under Debian 11, with dual monitors with the primary display set as the one on the right.

it's as if godot is momentarily calculating the 0,0 position from both screens, which is on 2nd monitor and is outside of the engine, which would explain why it turns all black? otherwise, if i have godot on that (left-most) screen, it works properly, as shown below:


[Screencast 2023-05-17 18:04:19.webm](https://github.com/godotengine/godot/assets/117863579/3342a7f1-3eec-474e-8315-279aed19b307)

**Comment by KMouratidis** [comment]
Experienced this on 4.0.3 and can confirm it's also not an issue for me if I use a different monitor. This also looks similar to my other issue: https://github.com/godotengine/godot/issues/76551
