### ISSUE TITLE
Select resource drop down menu scroll bar doesn't work

### ISSUE THREAD

**Issue by xxSeys1** [godotengine/godot#74055]
### Godot version

4 rc6

### System information

Windows 11, Vulkan, ryzen 9 5900X, rx 6700xt

### Issue description

If you export an array and then add a resource to the array, the scrollbar for the create resource drop down doesn't work.

A workaround would be to scroll with the mouse wheel, but it's still an issue and the list can get quite long, which can make mouse wheel scrolling tedious. 

### Steps to reproduce

1. Export an array (for example `@export var test: Array = []`)
2. Create a new element
3. Right click in the `<empty>` field
4. Try to use the scroll bar (it won't work)

### Minimal reproduction project

See "Steps to reproduce"

**Comment by M-O-Z-G** [comment]
Got the same problem with SystemFont > Font Names > Add Element drop-down menu. Scrolling also doesn't work there with mouse wheel. Only keyboard works, but every second selection scrolls the list to the top visually.
