### ISSUE TITLE
GDExtension: ImageTexture3D::create() doesn't fill in member variables width, height, depth, etc. 

### ISSUE THREAD

**Issue by minoaut** [godotengine/godot#74062]
### Godot version

v4.0.rc.custom_build [84a80721c]

### System information

Ubuntu 23.04 (Lunar Lobster)

### Issue description

ImageTexture3D::create() seems to create a valid texture but forgets to fill in its member variables width, height, depth, format, mipmaps. 

get_width(), get_height(), get_depth() always return their default value 1, etc.

get_data() however returns valid images. 

### Steps to reproduce

run the sample project:
- cd image_texture_3d_fail/test
- scons
- godot4 --path demo
  this should almost immediately hit the first failing assert:
```
godot4: src/example.cpp:43: static void Example::test_image_texture_3d(): Assertion `texture->get_format() == format' failed.
Aborted (core dumped)
```

key part:
```
void Example::test_image_texture_3d() 
{
    size_t w{ 32 };
    size_t h{ 32 };
    size_t d{ 32 };
    auto format = godot::Image::FORMAT_RGBA8;

    godot::TypedArray<godot::Image> images;
    for (size_t i = 0; i < d; i++) {
        auto image = godot::Image::create(w, h, false, format);
        assert(image.is_valid()); // <- ok

        images.push_back(image);
    }

    auto texture = memnew(godot::ImageTexture3D);
    auto err = texture->create(format, w, h, d, false, images);
    assert(err == godot::Error::OK); // <- ok and no warnings printed either

    auto rid = texture->get_rid();
    assert(rid.is_valid()); // <- ok

    assert(texture->get_format() == format); // <- fails
    assert(texture->get_width() != 1); // <- fails
    assert(texture->get_height() != 1); // <- fails
    assert(texture->get_depth() != 1); // <- fails
}
```

### Minimal reproduction project

[image_texture_3d_fail.zip](https://github.com/godotengine/godot/files/10841921/image_texture_3d_fail.zip)

**Comment by clayjohn** [comment]
Is this issue only reproducible when using a GDExtension?
