### ISSUE TITLE
[RC 6] Hover in node inspector have strange behavior

### ISSUE THREAD

**Issue by Cronos87** [godotengine/godot#74075]
### Godot version

4.0.rc6

### System information

macOS 12.3.1, macOS 12.6.5

### Issue description

When hovering the node inspector, the state can stay as hovered even if the mouse left it; it results in showing the hover background.

https://user-images.githubusercontent.com/1923206/221655801-20b850a0-2c07-4c53-b8ef-f1a5a9c4e3ea.mp4

### Steps to reproduce

Hover some items in the node inspector.

### Minimal reproduction project

Any project can reproduce it.

**Comment by YuriSizov** [comment]
Pretty sure it's a duplicate as I've seen it before, but I can't find it.

**Comment by Cronos87** [comment]
I tried to find if a similar issue had been opened, but I didn't find it.

**Comment by saierXP** [comment]
Duplicate of #73327

**Comment by YuriSizov** [comment]
Indeed, thank you! Let's join discussions then in the one that was opened earlier.

**Comment by Cronos87** [comment]
Well done @saierXP to find the older one. Continue the discussion there indeed ☺️
