### ISSUE TITLE
the "drag and drop a material on a mesh instance" feature behaves improperly in the case where the dragged material was the one set already on the hovered mesh instance

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#74077]
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

4.0 rc6

### System information

linux

### Issue description

the preview mechanism of this feature doesn't take into account the case where the previewed material was the one there already.
As a consequence for some reason instead of setting it back when stopping the preview (that is, when you stop hovering the mesh instance), the material override is cleared.

[out3.webm](https://user-images.githubusercontent.com/71937306/221664992-6f353102-ee47-445c-ad33-c63bdb73eab0.webm)

### Steps to reproduce

1. create a material and set it to a meshinstance's `material_override`. You can do so by dragging the material from the filesystem tab onto the mesh instance in the 3d viewport.
2. from the filesystem tab, drag this material again on the mesh instance, but this time don't release and move the mouse out of the mesh
3. the MeshInstance's `material_override` has now been cleared.

### Minimal reproduction project

[dragdropmaterial.zip](https://github.com/godotengine/godot/files/10843411/dragdropmaterial.zip)

**Comment by Calinou** [comment]
cc @SaracenOne

**Comment by stilestr** [comment]
Can confirm this still happens on 4.2 dev 5. 
This is a seriously annoying problem and really hinders the usability of the editor for 3D games, as even if you want to just change the texture by dragging it right to the material override, well, you better not accidentally hover over another surface with that material otherwise you'll clear it all.

**Comment by Calinou** [comment]
cc @SaracenOne

**Comment by stilestr** [comment]
Just did another test because I am extremely passionate about this issue as it is really bothering me :) 

This doesn't seem to be a regression, it appears to have always had this behavior ever since the initial implementation in 4.0

**Comment by robotaro** [comment]
I have the same issue on 4.2.1 (windows)

**Comment by DiegoSynth** [comment]
After experiencing the same problem, I've also noticed that dragging & dropping a material into a MeshInstance3d will visually change it, but if checking on the Mesh -> Surface X, the original material remains.
So it seems to be setting it, but somewhere else.

Beside this, if selecting multiple meshes, it's not possible to assign the same material anyhow. Not very convenient when you have about 50 meshes sharing the same material. I understand the issue lays on which Surface within the Mesh it should modify, so it's probably something that cannot be easily done by dragging & dropping, but any other solution would be welcome.

**Comment by DiegoSynth** [comment]
Thanks @damil42 , yes I'm not asking for a feature, I just came by to mention the error you all pointed out, and "now that I was here" I also commented about the other issue.
I'm already writing a small program to do what I need in an automated way.
