### ISSUE TITLE
Two Scenes mutually targeting eachother within a transitional scene will crash on startup

### ISSUE THREAD

**Issue by BlindLoke** [godotengine/godot#74079]
### Godot version

v4.0.rc6.official [0cd1418313]

### System information

Windows 10 Professional, 10.0.19044, CPU Intel Core i7-3770,  GPU Nvidia GTX 1650

### Issue description

I have created a Door Scene. It carries an Exported PackedScene that is the target for a _change_scene_to_packed_().
When the Door is placed in two Scenes, and they target mutually with this Door Scene, the game crashes (but not the editor). The Editor previously crashed as well in RC5, but now on RC6 only the game itself crashes. This also happens if there is a chain of different Scenes that can loop back: Example [Scene A > Scene B] [Scene B > Scene C] [Scene C > Scene A]

This is the code of the Door, seemingly the cause of all the issues:
```extends Area2D

@export var TargetScene : PackedScene
@export var door_interact = "kb_z"
func _ready():
	pass

func _input(event):
	if event.is_action_pressed(door_interact) :
		if !TargetScene :
			print("No Valid Scene")
			return
		if get_overlapping_bodies().size() >= 1:
			next_level()

func next_level() :
	var EPR = get_tree().change_scene_to_packed(TargetScene)
	if EPR != OK :
		print("Something broke in the Door Scene")
```

I have attached a godot.log file, and one I could copy from executing it from cmd. All the text starting from "Leaked instance:" is not written to the log, and I do not know if this is relevant or not but I have included it.

### Steps to reproduce

Place a Door Scene, and a Player Scene in two different "Map Scenes".
Place each different "Map Scenes" as the target for the Door Scene inside said Maps.
Run one of the Scenes, and the program should crash.

### Minimal reproduction project

[Bug Report.zip](https://github.com/godotengine/godot/files/10843891/Bug.Report.zip)

**Comment by KoBeWi** [comment]
See #72921
Cyclic references between scenes are not supported.
