### ISSUE TITLE
Passing type as a function argument causes error.

### ISSUE THREAD

**Issue by addmix** [godotengine/godot#74076]
### Godot version

4.0 RC6

### System information

Windows 10

### Issue description

Godot throws an error "Could not find type in the current scope" when passing a type as an argument to a function.
![image](https://user-images.githubusercontent.com/38119387/221664039-f2e8c224-c308-45ca-8ac2-9545aa829a0b.png)
This is a regression introduced in RC3

### Steps to reproduce

test this function:
(I know this is a redundant function)
```
static func is_type(obj, type) -> bool:
	return obj is type
```
Observe error "Could not find type "type" in the current scope.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
You cannot do "is" check with a variable, only with a compiletime type, see #73489

**Comment by addmix** [comment]
> You cannot do "is" check with a variable, only with a compiletime type, see #73489

The functionality was present in RC2, thus the bug report.

**Comment by AThousandShips** [comment]
Using `is` like this is not valid GDScript now so not a bug?

**Comment by YuriSizov** [comment]
Indeed, this was changed for better type checking workflow, and you need to use `is_instance_of` now.

**Comment by addmix** [comment]
> Indeed, this was changed for better type checking workflow, and you need to use `is_instance_of` now for your use case.

Thank you for the information Yuri.
