### ISSUE TITLE
Mobile: Clear color values supplied (2) differ from the amount required for framebuffer color attachments (1)

### ISSUE THREAD

**Issue by Sekuta82** [godotengine/godot#74082]
### Godot version

v4.0.rc6.official [0cd148313]

### System information

Windows 10, GTX 1060 w driver 31.0.15.1694

### Issue description

I have stripped down my mobile project to the bare minimum to replicate the issue in a simple project.

I'm getting this error when anti_aliasing/quality/msaa_2d is > 0
and no material in the scene uses refraction.

![image](https://user-images.githubusercontent.com/47293702/221683765-3e46ff23-c248-470b-974b-df3dc98e4438.png)

### Steps to reproduce
- Start with a mobile project
- Create a scene with a camera and mesh node
- set anti_aliasing/quality/msaa_2d to > 0

To fix it:
Turn msaa_2d  off
or enable refraction on one of the materials

### Minimal reproduction project

[mobile_vulkan_clearing.zip](https://github.com/godotengine/godot/files/10844280/mobile_vulkan_clearing.zip)

**Comment by clayjohn** [comment]
@BastiaanOlij You'll be interested in this one.

**Comment by BastiaanOlij** [comment]
I'll look into this asap, should be pretty straight forward to fix, probably something that was only properly implemented on clustered.
