### ISSUE TITLE
Vertical scrolling instead of zooming with the mouse wheel

### ISSUE THREAD

**Issue by TX256** [godotengine/godot#7409]
**Operating system or device - Godot version:**
Windows 10, Godot 2.2

**Issue description** (what happened, and what was expected):

There does not seem to be an option to change the mouse wheel to do vertical scrolling instead of zooming...?

I'd actually suggest to change the default to vertical scrolling - most graphics software do this for a good reason - and then zoom with CTRL + mouse wheel. And add a setting to switch this.

EDIT: I'm of course talking about the 2D editor.

**Comment by bojidar-bg** [comment]
I disagree, unless it is an editor setting; personally I like to zoom with mouse wheel and pan with mouse middle button.

**Comment by TX256** [comment]
I can live with a setting. :)

But, I have to disagree about the zooming with plain mouse wheel in 2D space. A long, long time ago, I too used it for zooming and while in its own way intuitive, in my opinion (and experience) it's more practical to do it with CTRL down.

I believe the major reasons why zooming by default is often not used, is because it's so easy to accidentally change the zoom level, and because there is often enough horizontal space - but vertical space can be at sparse, and it works just like 90% of the apps you use (web browsers, text editors, et cetera).

Panning is one good example of the first one; I use middle mouse button panning in multiple graphics software all the time, but in Godot I avoid it all the time and just use space because it is so very easy to accidentally change the zoom level **_when you initiate a pan_**. 

Then again, I am used to quite loose mouse wheel - and people work differently & have different preferences... :)

**Comment by SuperUserNameMan** [comment]
note that it is possible to scroll with the mouse wheel if you put the cursor near the vertical scroll bar

**Comment by KoBeWi** [comment]
This was added in 3.0
