### ISSUE TITLE
RotatedFileLogger crashes if fails to create log

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#74090]
### Godot version

4.0.rc + libgodot

### System information

Windows 10

### Issue description

RotatedFileLogger calls FileAccess::open and then immediately calls `detach_from_objectdb` on it without checking for nullptr.
![image](https://user-images.githubusercontent.com/39946030/221711971-aa7547b4-2e75-492c-92ab-5b7b1cfa65be.png)

This particular instance occurred in developing libgodot which does not configure a writeable home directory correctly.

However, given that rotating logfiles are enabled by default on templates on PC, and end users may have varied configurations and home directory permissions (especially given that the Roaming folder is currently used on Windows for logfiles), this case could conceivably happen in the wild so it may be worth handling this case or presenting an error message to the user.

It's probably pretty rare, and godot assumes the home directory is writeable, otherwise shader_cache won't work, but it would be good not to crash.

### Steps to reproduce

1. Set Godot to enable file logging on pc (default).
2. Ensure its home directory's logs folder is not writable
3. Run the app (we used a debug template)

### Minimal reproduction project

We believe it happens even in a default project, since file logging is true by default on pc.

**Comment by akien-mga** [comment]
Can you still reproduce this in 4.0.3 and 4.1-beta3 or later?

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
