### ISSUE TITLE
[C#] Cannot cast `Area3D` to a script that extends `Node3D`

### ISSUE THREAD

**Issue by pooroligarch** [godotengine/godot#74100]
### Godot version

v4.0.rc6.mono.official [0cd148313]

### System information

EndeavourOS

### Issue description

So far the only way to create a script that can be attached to both areas and bodies is extending `Node3D`, as `CollisionObject3D` doesn't have a constructor. When I do this the script itself works as expected (in the MRP, prints its name) but casting an `Area3D` from/to it (this includes `area is Foo` in AreaEntered callbacks) throws a `System.InvalidCastException`. Doing the same on a body works as expected.

### Steps to reproduce

* Get a reference to an `Area3D`
* Cast it to a script that extends `Node3D` or check with the `is` operator
* Throws exception

### Minimal reproduction project

[MonoCollision.zip](https://github.com/godotengine/godot/files/10847170/MonoCollision.zip)

**Comment by raulsntos** [comment]
> So far the only way to create a script that can be attached to both areas and bodies is extending `Node3D`

This is not supported. Please, use the right base class for the Node type that the script will be attached to.

> casting an `Area3D` from/to it (this includes `area is Foo` in AreaEntered callbacks) throws a `System.InvalidCastException`

The exception that you are getting is correct and expected behavior. Your script inherits from `Node3D` so it can't be converted to `Area3D`, this is how OOP works.

```mermaid
graph TD;
      Node-->Node3D-->CollisionObject3D-->Area3D;
      Node3D-->Box;
```

As you can see in the diagram there's no way to go from the `Box` type to the `Area3D` type.

**Comment by raulsntos** [comment]
> So the right way is convert `Box` to an interface and implement it on `Area3D` and all types of bodies?

Yes, an interface could work for this use case.

> Also this works just fine on bodies so if it's not supported it should throw a clear error.

The `BodyEntered` signal takes a `Node3D` parameter so it should work for any type that inherits from `Node3D`. Since `Box` inherits from `Node3D`, it makes sense that it works in this case.

**Comment by pooroligarch** [comment]
Thanks, your solution fixed everything!

**Comment by winniehell** [comment]
> > So far the only way to create a script that can be attached to both areas and bodies is extending `Node3D`
> 
> This is not supported. Please, use the right base class for the Node type that the script will be attached to.

@raulsntos I have a follow-up question regarding this behavior. in the example provided here, `GetClass()` would still result in `Area3D` and `IsClass("Area3D") == True`. is that also intended?

here is a code example along with a workaround: https://framagit.org/regenbogenmarmelade/godot-playground/-/blob/class-inconsistency/godot4/Main.cs

it prints the following:

```
GetClass() = Node2D
IsClass(GetClass()) = True
GetType() = Main
GetGodotBaseType() = Godot.Node
```
