### ISSUE TITLE
GridMap renders 3D meshes as solid black with "Compatibility" renderer

### ISSUE THREAD

**Issue by kdiduk** [godotengine/godot#74111]
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

v4.0.rc6.official

### System information

Linux kernel 5.15. Driver: Mesa 22.3.1. Godot renderer: compatibility

### Issue description

When using **Compatibility** renderer in Godot 4.0, _GridMap_ doesn't render 3D meshesh correctly: they are rendered as completely black. And what is interesting is that they are rendered correctly while editing before a 3D mesh is actually placed.

![grodmap_compatibility](https://user-images.githubusercontent.com/12220677/221861968-a5e27d68-583f-4fff-9785-fc2a756bfb03.png)

#### See the video below:

https://user-images.githubusercontent.com/12220677/221860974-aabde208-1999-4799-aa46-caa0bed86a1f.mp4

#### The renderers "Forward+" and "Mobile" don't have this issue.

![gridmap_mobile_renderer](https://user-images.githubusercontent.com/12220677/221861501-4ea61280-8e25-41fd-8201-4a46696f152e.png)

### Steps to reproduce

Create new project with "Compatibility" renderer.
Create a simple 3D scene (with lights, etc.) and put GridMap node on it.
Create new MeshLibrary with some 3D meshesh.
Start editing GridMap. Notice when placing 3D meshesh on it, they are rendered correctly until they are placed. One they are placed, they are rendered as completely black.

### Minimal reproduction project

[racing.tar.gz](https://github.com/godotengine/godot/files/10850429/racing.tar.gz)

**Comment by Calinou** [comment]
> And what is interesting is that they are rendered correctly while editing before a 3D mesh is actually placed.

The preview is a single mesh, while the final GridMap is a MultiMesh.

**Comment by Leandro-170** [comment]
I've been facing this issue recently in a project of my own. At first, I thought it was my own GPU issues (I have a very old GPU, and have to rely on the Compatibility render to use Godot 4) but just now, I've found that meshes that have materials with the `vertex_color_use_as_albedo` property on render all black, and that disabling it seems to make them render properly.

In here, ground tiles were exported from Blender to a GLTF scene, then loaded as a scene in Godot, then exported to a `MeshLibrary` without any changes.
![image](https://github.com/godotengine/godot/assets/73649765/0eec4436-94b7-430c-8d13-9301cdaa7a26)

In here, i reopened the scene, picked the grass plane mesh and made both itself and it's material unique, then unset `vertex_color_use_as_albedo`.
![image](https://github.com/godotengine/godot/assets/73649765/559d5210-2d55-438f-8517-7cdb9de3e4bf)

I'm not sure if said property should behave like this - on my side, setting the property to true on a standalone `MeshInstance`'s material does not show any visible effect.
![image](https://github.com/godotengine/godot/assets/73649765/116ae5f6-1293-4ada-a570-2b3058b7148e)

**Comment by Wolfe2x7** [comment]
I confirm this bug affects any `MultiMeshInstance3D`, if and only if vertex colors are used in a shader. 4.1.1 Stable.

**Comment by Hazarth** [comment]
Yep, I encountered the same issue. Switching to Forward+ or Mobile is a simple workaround

**Comment by BrixStudios** [comment]
i have the same problem but with the mobile renderer

**Comment by Calinou** [comment]
> i have the same problem but with the mobile renderer

Please open a new issue with a minimal reproduction project attached.
