### ISSUE TITLE
Vulkan: Editor drawing is delayed by one frame

### ISSUE THREAD

**Issue by cattuna** [godotengine/godot#74126]
### Godot version

4.0 RC6

### System information

Apple M2 Max, 96 GB Mem

### Issue description

Potentially related to https://github.com/godotengine/godot/issues/71795, but that issue seems to be on Windows.

As this question in the Discord channel as well so linking it [here](https://discord.com/channels/212250894228652034/1080240357108895887/1080240357108895887).

The editor feels laggy and sometimes unresponsive. i.e. clicking on things, hovering over UI elements.

The weirdest thing is when I try to screen record it (Mac’s built-in screen record tool), the problem disappears. I had to use my phone to capture this.

The video shows general unresponsiveness when hovering over the node creation buttons, but the issues exists almost elsewhere in the editor as well.

https://user-images.githubusercontent.com/42384776/221988785-8b77b5d2-58ec-49f8-9fcc-47c04b4dfc67.mov

Things I have tried so far:

* quitting and restarting the editor
* removing and starting a new project
* change to a different display (in the video I'm using an external display), including switching to my built-in display.

Enabling continuous update in editor settings seen to have improve the issue a little but the problem is still largely there.

### Steps to reproduce

N/A

### Minimal reproduction project

Any new project.

**Comment by Calinou** [comment]
Can you reproduce this after switching the rendering method to Compatibility in the top-right corner?

**Comment by bli00** [comment]
@Calinou no, the problem is gone after switching Compatibility. I was on Mobile rendering.

**Comment by Calinou** [comment]
When using the Mobile renderer, can you reproduce this after changing the V-Sync mode to Disabled in the Project Settings, then restarting the editor? (This project setting also affects the editor.)

**Comment by bli00** [comment]
@Calinou Yes it's still there.

BTW, I see you changed the title to say "delayed by one frame". I'm not entire sure what I'm talking about, but it doesn't feel like it's just delayed by one frame. Sometimes when I click somewhere it feels like the editor froze for a split second because it seems like my input (click) didn't register.

**Comment by Calinou** [comment]
This issue reminds me of https://github.com/godotengine/godot/issues/23069, which was an issue scoped to Intel IGPs on Windows.

**Comment by bli00** [comment]
Here, I added another video, hopefully it helps.

It's hard to show this, but at 0:04 in the video, I actually clicked on the "3D" tab, but it didn't register right away, instead, moving my mouse triggered the "previous" click.

The sequence of actions were:

```text
* -> click on "Script" -> move mouse to "3D" -> click -> *nothing happens* -> move mouse -> tab switched over to "3D"
```

https://user-images.githubusercontent.com/42384776/222019450-002df094-cc19-40de-93d6-e39dae151c75.mov

**Comment by Calinou** [comment]
Moving the mouse eventually triggered a redraw, as you moved the mouse cursor away from the 3D button (which causes its hover state to be disabled).

You can see when the editor redraws by enabling **Interface > Editor > Show Update Spinner** in the Editor Settings. I recommend keeping it enabled when troubleshooting editor issues in general :slightly_smiling_face:

**Comment by bli00** [comment]
It's prob worth noting that this happens in the script editor as well, but unlike stated above, doing some additional action don't trigger the "previous" action. It just freezes for a split second "self-resolves".

**Comment by bli00** [comment]
And again, I double confirmed this, because it seemed extra weird to me -- when screen recording using Mac's built-in screen recorder (cmd + shift + 5), this problem complete disappears.

**Comment by lostminds** [comment]
I'm not seeing this on my intel-based iMac so maybe it's something related to the new Apple Silicone processors or the graphics cards in them? 

If you click the three little dots menu in the top left corner of a 3d-viewport there's a toggle to "Show frame time" that will show you the editor viewport update fps. Perhaps that could offer some information to see if the editor is actually updating slowly all around, or if it's something related only to the UI redrawing or reacting to events.

Some speculation: If the reported fps is displayed as high but visual updating is slow one thing to investigate could be if there's something in the window server compositing of window buffers that is going wrong. It could be that Godot is drawing into the window back buffer at the correct frequency, but for some reason it is not composited to the screen by the system window server. This could also explain why the issue would go away when recording the screen, as maybe that could cause some more aggressive flushing of the window server back buffers.

**Comment by Calinou** [comment]
Can you reproduce this if you enable **Single Window Mode** in the Editor Settings then restart the editor?

**Comment by bli00** [comment]
Hmmmm so I unplugged my external displays and the problem disappeared. This happened independent of the Single Window Mode @Calinou

**Comment by Calinou** [comment]
I wonder if this is caused by USB-C display support being limited to 60 Hz, but since your MBP's display is 120 Hz, this causes V-Sync to screw up.
