### ISSUE TITLE
SkeletonModification2DTwoBoneIK numbers in meters?

### ISSUE THREAD

**Issue by ShatReal** [godotengine/godot#74129]
### Godot version

4.0 rc 6

### System information

win 11

### Issue description

The suffix for target params is "m" which I think is meters, but that doesn't make any sense for 2D.

### Steps to reproduce

just make a skeletonmodification2dtwoboneik

### Minimal reproduction project

n/a

**Comment by Calinou** [comment]
It's most likely a typo and meant to be `px`. Feel free to open a pull request for this :slightly_smiling_face:
