### ISSUE TITLE
Changing Resource values gives an error and do not affect anything while on play mode

### ISSUE THREAD

**Issue by TheHyper-Dev** [godotengine/godot#74136]
### Godot version

4.0 rc6

### System information

windows 10, ryzen 5 5600x rx 590, m2 ssd

### Issue description

This error appears when I try to change a value on a Resource, it seems like the Resource value has been changed but it doesn't in the play mode untill I restart the play mode.
![image](https://user-images.githubusercontent.com/32967925/222021533-20c46514-408e-40c3-819f-94bc8ff62ff0.png)

### Steps to reproduce

.

### Minimal reproduction project

.

**Comment by Calinou** [comment]
@TheHyper-Dev Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
