### ISSUE TITLE
Rearranging bones in the skeleton2d causes polygon2d to disappear

### ISSUE THREAD

**Issue by ShatReal** [godotengine/godot#74132]
### Godot version

4 rc6

### System information

win 11

### Issue description

I made neck a check of torso instead of cervix and all the sprites for the neck and its children (head, etc) disappeared. I dunno how to get them back.

### Steps to reproduce

Make a polygon
make a skeleton with bones
assign the skeleton to the polygon and paint the weights
move the bones

### Minimal reproduction project

n/a

edit: okay i got them back by repainting the weights but now the uv thingy is off

![image](https://user-images.githubusercontent.com/69117768/222009696-857f3ef6-1510-414d-8fbf-146bbdbbee12.png)

**Comment by jasonmccollum** [comment]
I've ran into the same issue in 4.0 on Windows 10. While animating the bones, the texture of one of my Polygon2D nodes disappeared. The editor showed the bones were still painted correctly, but the when I hit "Sync Bones to Polygon" the weights disappeared. Painting again brought the texture back.

**Comment by dippinpahwa** [comment]
similar issue, I am using v4.0.1 on windows 11. The texture disappears on polygon2D while painting weights on the bones.

**Comment by dippinpahwa** [comment]
i found a simple fix, overwrite rest pose for skeleton2D node from the navigator menu.

**Comment by rretureau** [comment]
Bump. Tested from RC6 to Beta 4.1. Issue is still there. Repainting weight doesn't work and is not a solution (when you have a big UV). 

It happens in the editor and when you run the project. 

![bug](https://github.com/godotengine/godot/assets/4721624/d9d507cb-3026-458b-b230-4f19c7875577)

**Steps to reproduce**
- Add Polygon2D with UV and sync it to a bone from a Skeleton2D.
- Rotate the bone or scale the view

**Comment by Xorblax** [comment]
I had what I believe to be the same problem. It's because the pivot for the polygon2D is far away, so when the polygon rotates around its bone, it occludes as if its rotating around its pivot, which would put it off screen. The solution was changing the rotation pivot for each polygon and putting them at or close to origin.
An option to reset pivot to origin or object center without affecting the global position of the object would be very useful here.

**Comment by Xorblax** [comment]
Although now I am dealing with a new problem where some of the polygons, not all, will disappear if the rig travels too far from origin. Good ol godot

**Comment by hsandt** [comment]
Great, I studied on my side and found the same conclusion.

@ShatReal (or a moderator) now that we've reproduced things more accurately, could you edit the title to something like "When polygon points are far from root, rotating them via Skeleton2D bones with painted weights causes them to disappear above certain angles" ?

**Comment by PixelWeaver** [comment]
> i found a simple fix, overwrite rest pose for skeleton2D node from the navigator menu.

Same problem!
& Thank you so much this worked for me, even though this is so damn hackish.

**Comment by JamesKaret** [comment]
I found another way to fix this issue.
I'm pretty sure you'd moved Polygon2D nodes to certain location.
DO NOT USE TRANSFORM.
Reset transform and use offset of Polygon2D, instead.
