### ISSUE TITLE
`Find/Replace in Files` cannot search inside built-in scripts

### ISSUE THREAD

**Issue by stmSi** [godotengine/godot#74145]
### Godot version

4.0 rc5, 3.x

### System information

Manjaro Linux, KDE, Nvidia 2060

### Issue description

Both `Find in Files` (Ctrl+Shift+F) and  `Replace in Files` (Ctrl+Shift+R) cannot search in built-in script inside `tscn` files.
Searching Only performs in `gd`  and `gdshader` files.

### Steps to reproduce

1. create node2d with attach built-in script
2. open script tab
3. `Find in Files` (Ctrl+Shift+F)
4. type "Node2D" and press enter
5. see that No Results

### Minimal reproduction project

[reproducable.zip](https://github.com/godotengine/godot/files/10857551/reproducable.zip)

**Comment by stmSi** [comment]
Although searching results can be done with `tscn` extension is added in  `editor/script/search_in_file_extensions` project settings, clicking the found line doesn't take me to the built-in script file. 

It took me to the scene file that built-in script belongs to. 

To implement/fix this, we might need special use case specifically for `tscn` built-in script.

**Comment by GustJc** [comment]
I think there has been a **regression**. 
Find in Files does NOT search builtin scripts anymore.
Tested on: v4.7.dev4.mono.official [755fa449c]

I almost went crazy trying to find where a ghost "ok" print was in my project just now.
I have to stop using builtin scripts for quick testing. They are kinda dangerous to use if the search function doesn't search them.

---

Here's a MRP just in case: [ghost_print_search.zip](https://github.com/user-attachments/files/26848191/ghost_print_search.zip)
**Steps:** 
- Ctrl+Shift+F (Find in Files) and search for "Ghost print"

**Result:** Nothing found
**Expected:** Found the text in the builtin script
