### ISSUE TITLE
Exported Nodes are Nil in `@tool` mode

### ISSUE THREAD

**Issue by hunterloftis** [godotengine/godot#74141]
### Godot version

4.0-rc6

### System information

Fedora 37, Mesa Intel ADL GT2

### Issue description

Code that works as expected at runtime fails with Nil references to (assigned) exported vars in the editor:

![tool_global_position_error](https://user-images.githubusercontent.com/364501/222031460-ffb1ecbd-5175-4a42-8470-25285ba5f821.png)

### Steps to reproduce

Try to access the `global_position` of a `Node3D` that's assigned to an exported var.

See that it works at runtime.

See that it errors in the editor with:

> Invalid get index 'global_position' (on base: 'Nil').

### Minimal reproduction project

[tool_test.zip](https://github.com/godotengine/godot/files/10856640/tool_test.zip)

**Comment by theraot** [comment]
Related: [74050](https://github.com/godotengine/godot/issues/74050)

**Comment by ajreckof** [comment]
> Related: [74050](https://github.com/godotengine/godot/issues/74050)

they are in fact one and the same the problem is that the inspector never set the value, this means both the setter is never called and the property stays to null.
