### ISSUE TITLE
PopupMenu's clear method doesn't remove signals

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#7414]
**Operating system or device - Godot version:** 2.1 latest

**Issue description** (what happened, and what was expected):

```
PopupMenu.clear()
PopupMenu.add_item("Hello", 0)
PopupMenu.connect("item_pressed", self, "IGNContextMenu")
```

And if ran again, we get a signal already connected error. Just curious if this is intended or not. The `.clear` definition says `Clear the popup menu, in effect removing all items` If all items are removed, their signals should be also

**Comment by bojidar-bg** [comment]
@Dillybob92 You are connecting the whole `PopupMenu`, not individual items.

Closing as wontfix, this is intended as you don't clear the signal connections in any way.

**Comment by Dillybob92** [comment]
Oh wow, that was fast :) kept thinking individual items are signald but its the id that is passed

**Comment by Sslaxx** [comment]
Perhaps add a note/reminder about this in the docs?

**Comment by bojidar-bg** [comment]
@Sslaxx No, I don't think it is useful, it would just complicate things for advanced devs :laughing:
