### ISSUE TITLE
Missing info.plist keys prevent submitting macOS build for App Store review

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot#74154]
### Godot version

4.0rc6

### System information

macOS 13.2

### Issue description

While trying to get a Godot macOS export onto the macOS Apple App Store (as described here: https://github.com/godotengine/godot/issues/73876 which led to improvements for this process here in this PR: https://github.com/godotengine/godot/pull/74027) I've now managed to get a build to be properly signed and packaged to be accepted for upload by the Transporter app and listed in App Store Connect as ready for review. However, when you try to submit it for review (for Test Flight external testing) a new error is shown:

`This build is using a beta version of Xcode and can’t be submitted. Make sure you’re using the latest version of Xcode or the latest seed release found on the releases tab in News and Updates`

In other words, you can't submit the app for review since the system thinks it's been built with a beta version of XCode, preventing distribution via the App Store. It seems this is due to some missing keys in the info.plist of the exported app bundle Godot produces as guessed by @bruvzg  https://github.com/godotengine/godot/issues/73876#issuecomment-1448040562.

Adding the following keys copied from another macOS app I've built with XCode to the game info.plist before signing and packaging seems to resolve the issue:

```
<key>DTCompiler</key>
<string>com.apple.compilers.llvm.clang.1_0</string>
<key>DTPlatformBuild</key>
<string>14C18</string>
<key>DTPlatformName</key>
<string>macosx</string>
<key>DTPlatformVersion</key>
<string>13.1</string>
<key>DTSDKBuild</key>
<string>22C55</string>
<key>DTSDKName</key>
<string>macosx13.1</string>
<key>DTXcode</key>
<string>1420</string>
<key>DTXcodeBuild</key>
<string>14C18</string>
```

So at least some of these need to be added in exports for them to be eligible for mac app store distribution. It is however unlikely all of these keys are required for the build to be accepted. It's also unclear what content will be acceptable for these keys. I'll open this issue now to keep track of it and see if anyone else knows more about this. And I'll update with further comments if I figure out more about what keys are actually needed.

### Steps to reproduce

- Export, sign, package and upload a macOS build to the App Store using the steps described here: https://github.com/godotengine/godot/issues/73876
- In the App Store connect Test Flight interface, add external testers to the build and click the button to submit for review.
- Observer error about beta version of Xcode blocking submit.

### Minimal reproduction project

This is a general macOS export issue

**Comment by lostminds** [comment]
I've narrowed it down a little further, and it seems only these five are needed:

```
<key>DTPlatformBuild</key>
<string>14C18</string>
<key>DTSDKBuild</key>
<string>22C55</string>
<key>DTSDKName</key>
<string>macosx13.1</string>
<key>DTXcode</key>
<string>1420</string>
<key>DTXcodeBuild</key>
<string>14C18</string>
```

Basically it seems to be the SDK version and build and the XCode version and build (twice). The XCode version I haven't tried removing since that's what it complained about in the error,and removing the SDK keys I get the same error.

**Comment by lostminds** [comment]
I finally managed to get an "official" reply from an Apple tech specialist about this and basically they just said that what XCode automatically exports is what's expected (without any further details on what/why) and if you're not using XCode to generate app bundles, just try to do things the same way XCode does. So I guess [you were right](https://github.com/godotengine/godot/pull/74027#discussion_r1121853709) in your reasoning @bruvzg

**Comment by agingo** [comment]
We made the suggested changes but we still get the same error when deploying to external users.

**Comment by lostminds** [comment]
> We made the suggested changes but we still get the same error when deploying to external users.

This was a specific issue with some keys missing that were required for apple app store review, that have now been added. It was not related to direct distribution to external macOS users. Or are you still getting the error above trying to submit your macOS build to apple app store review in Godot 4.x?

**Comment by agingo** [comment]
@lostminds we're still getting the error when we deploy the catalyst app to external users.
