### ISSUE TITLE
Converting project from 3.x to 4.x using OpenGL 3 doesn’t seem to work

### ISSUE THREAD

**Issue by Brrog** [godotengine/godot#74159]
### Godot version

4.0rc6

### System information

Windows 10

### Issue description

When I tried to convert my project to godot 4 it said I couldn’t because the pc doesn’t support vulkan. So then I opened it using the command it says to use and the project crashed with a “memory” error. I may be doing something wrong but there doesn’t seem to be any information about how to convert a project but use OpenGL

### Steps to reproduce

When using the command the error gives. I noticed that it was trying to open my project in vulkan or forward+ even after running the command. I suppose it is hard to get this issue if you don’t have a pc that doesn’t support vulkan. 

### Minimal reproduction project

I cannot provide a example project at the moment sorry.

**Comment by Calinou** [comment]
The project converter does not specify the output renderer, which means it defaults to `forward_plus` (Vulkan). There's currently no way to make a project use OpenGL without opening it first.

In the meantime, edit `project.godot` to add the following at the end of the file while the editor is closed:

```toml
[rendering]

renderer/rendering_method="gl_compatibility"
```
