### ISSUE TITLE
Shader Variable POSITION Bug

### ISSUE THREAD

**Issue by carlosmarti** [godotengine/godot#7416]
Windows 10 Godot Version 2.1

When calling the variable POSITION in a fragment shader it turns the whole scene white. Don't know if this happens to 3d objects but it happens with 2d objects.

Create a 2d sprite attach a shader and in the Fragment tab call the POSITION variable.
[shader.txt](https://github.com/godotengine/godot/files/681614/shader.txt)

**Comment by bojidar-bg** [comment]
Can you share console output related to this bug, as it would probably be relevant?

**Comment by carlosmarti** [comment]
This is what it says.

> ERROR: ShaderGLES2::get_current_version: CanvasShaderGLES2: Program LINK FAILED:
Fragment info
-------------
0(223) : error C5052: gl_Position is not accessible in this profile

   At: drivers\gles2\shader_gles2.cpp:544
ERROR: ShaderGLES2::get_current_version: Method/Function Failed, returning: 0
   At: drivers\gles2\shader_gles2.cpp:551
ERROR: ShaderGLES2::bind: Condition ' !version ' is true. returned: false

**Comment by bojidar-bg** [comment]
Ah, I actually remember hitting that one a while ago...

**Comment by volzhs** [comment]
I guess this is fixed by #7969, isn't it?

**Comment by akien-mga** [comment]
Indeed, thanks for checking.
