### ISSUE TITLE
Editor disappears in Taskbar

### ISSUE THREAD

**Issue by HatAndTie** [godotengine/godot#74169]
### Godot version

4.x

### System information

Ubuntu 20.04, Mesa Intel® Iris(R) Plus Graphics 655 (CFL GT3), OpenGl 4.6, Vulkan

### Issue description

When running a Project from the Editor and then closing it, the Taskbar-Tab for the Editor will disappear. This also happens sometimes when first opening the Project and when saving. Since running the project automatically saves it, this might be the core issue.

Reloading the Project usually fixes it.

### Steps to reproduce

1. Create an Project using either __Mobile__ or __Compatibility__ as rendering method.
2. Open the Project and run it through the Editor
![Run Project](https://user-images.githubusercontent.com/126703589/222224047-3e025b38-8c89-4b16-8670-b9fa80c918a1.png)
3. Stop the project either by closing the Window or with the Button in the Editor
![Stop Project](https://user-images.githubusercontent.com/126703589/222224272-ae4e9cc8-7b69-45fd-a4ed-66a4b7dc6d02.png)
4. The Editor is no longer visible in the Taskbar
![Icon disappears](https://user-images.githubusercontent.com/126703589/222224332-51420059-7d56-4ab5-a66c-cf94aecccaeb.png)

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Can you reproduce this after enabling **Single Window Mode** in the Editor Settings then restarting the editor?

**Comment by HatAndTie** [comment]
@Calinou enabling *Single Window Mode* fixed the Issue.

I can't reproduce it in Godot 3.5.2, or other Godot 3 Versions.
