### ISSUE TITLE
False to normal exiting from Godot4 Stable

### ISSUE THREAD

**Issue by azmrv** [godotengine/godot#74165]
### Godot version

4 Stable

### System information

Windows 10

### Issue description

ERROR: Script does not inherit from Node: res://core/common_scripts/brain.gd.
   at: (editor/editor_autoload_settings.cpp:423)
ERROR: Condition "!info->node" is true. Continuing.
   at: update_autoload (editor/editor_autoload_settings.cpp:551)
ERROR: Script does not inherit from Node: res://core/common_scripts/utility.gd.
   at: (editor/editor_autoload_settings.cpp:423)
ERROR: Condition "!info->node" is true. Continuing.
   at: update_autoload (editor/editor_autoload_settings.cpp:551)
Running: D:/GODOT/GODOT 4/Godot_v4.0-stable_win64.exe/Godot_v4.0-stable_win64.exe --path D:/Projects/GAMEDEV/Godot%20DEV/NF4M_2D_Gdt --remote-debug tcp://127.0.0.1:6007 --editor-pid 16984 --position 384,256 res://core/scenes/main.tscn
Godot Engine v4.0.stable.official.92bee43ad - https://godotengine.org
Vulkan API 1.3.224 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1050 Ti

ERROR: Attempt to open script 'res://core/scripts/ship.gd' resulted in error 'File not found'.
   at: (modules/gdscript/gdscript.cpp:1043)
ERROR: Attempt to open script 'res://core/scripts/background.gd' resulted in error 'File not found'.
   at: (modules/gdscript/gdscript.cpp:1043)
ERROR: Attempt to open script 'res://core/scripts/cell.gd' resulted in error 'File not found'.
   at: (modules/gdscript/gdscript.cpp:1043)
ERROR: Attempt to open script 'res://core/scripts/gui2.gd' resulted in error 'File not found'.
   at: (modules/gdscript/gdscript.cpp:1043)
ERROR: Attempt to open script 'res://core/scripts/gui_gameover.gd' resulted in error 'File not found'.
   at: (modules/gdscript/gdscript.cpp:1043)
ERROR: Can't open file from path 'res://fonts/PT Sans_Bold.ttf'.
   at: (core/io/file_access.cpp:698)
ERROR: BUG: Unreferenced static string to 0: _update_scrollbars
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: thread_end
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: _physics_process_internal
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: _update_script_names
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: GuiToggleOnDisabledMirrored
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: raise
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: ShaderCompilation
   at: unref (core/string/string_name.cpp:129)
ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools11BucketLargeE
   at: (./core/templates/paged_allocator.h:140)
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
   at: _EDITOR_GET (editor/editor_settings.cpp:1101)
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
   at: _EDITOR_GET (editor/editor_settings.cpp:1101)
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
   at: _EDITOR_GET (editor/editor_settings.cpp:1101)
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
   at: _EDITOR_GET (editor/editor_settings.cpp:1101)
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
   at: _EDITOR_GET (editor/editor_settings.cpp:1101)
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
   at: _EDITOR_GET (editor/editor_settings.cpp:1101)
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
 

### Steps to reproduce

ERROR: Script does not inherit from Node: res://core/common_scripts/brain.gd.
   at: (editor/editor_autoload_settings.cpp:423)
ERROR: Condition "!info->node" is true. Continuing.
   at: update_autoload (editor/editor_autoload_settings.cpp:551)
ERROR: Script does not inherit from Node: res://core/common_scripts/utility.gd.
   at: (editor/editor_autoload_settings.cpp:423)
ERROR: Condition "!info->node" is true. Continuing.
   at: update_autoload (editor/editor_autoload_settings.cpp:551)
Running: D:/GODOT/GODOT 4/Godot_v4.0-stable_win64.exe/Godot_v4.0-stable_win64.exe --path D:/Projects/GAMEDEV/Godot%20DEV/NF4M_2D_Gdt --remote-debug tcp://127.0.0.1:6007 --editor-pid 16984 --position 384,256 res://core/scenes/main.tscn
Godot Engine v4.0.stable.official.92bee43ad - https://godotengine.org
Vulkan API 1.3.224 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1050 Ti

ERROR: Attempt to open script 'res://core/scripts/ship.gd' resulted in error 'File not found'.
   at: (modules/gdscript/gdscript.cpp:1043)
ERROR: Attempt to open script 'res://core/scripts/background.gd' resulted in error 'File not found'.
   at: (modules/gdscript/gdscript.cpp:1043)
ERROR: Attempt to open script 'res://core/scripts/cell.gd' resulted in error 'File not found'.
   at: (modules/gdscript/gdscript.cpp:1043)
ERROR: Attempt to open script 'res://core/scripts/gui2.gd' resulted in error 'File not found'.
   at: (modules/gdscript/gdscript.cpp:1043)
ERROR: Attempt to open script 'res://core/scripts/gui_gameover.gd' resulted in error 'File not found'.
   at: (modules/gdscript/gdscript.cpp:1043)
ERROR: Can't open file from path 'res://fonts/PT Sans_Bold.ttf'.
   at: (core/io/file_access.cpp:698)
ERROR: BUG: Unreferenced static string to 0: _update_scrollbars
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: thread_end
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: _physics_process_internal
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: _update_script_names
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: GuiToggleOnDisabledMirrored
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: raise
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: ShaderCompilation
   at: unref (core/string/string_name.cpp:129)
ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools11BucketLargeE
   at: (./core/templates/paged_allocator.h:140)
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
   at: _EDITOR_GET (editor/editor_settings.cpp:1101)
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
   at: _EDITOR_GET (editor/editor_settings.cpp:1101)
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
   at: _EDITOR_GET (editor/editor_settings.cpp:1101)
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
   at: _EDITOR_GET (editor/editor_settings.cpp:1101)
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
   at: _EDITOR_GET (editor/editor_settings.cpp:1101)
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
   at: _EDITOR_GET (editor/editor_settings.cpp:1101)
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
 

### Minimal reproduction project

ERROR: Script does not inherit from Node: res://core/common_scripts/brain.gd.
   at: (editor/editor_autoload_settings.cpp:423)
ERROR: Condition "!info->node" is true. Continuing.
   at: update_autoload (editor/editor_autoload_settings.cpp:551)
ERROR: Script does not inherit from Node: res://core/common_scripts/utility.gd.
   at: (editor/editor_autoload_settings.cpp:423)
ERROR: Condition "!info->node" is true. Continuing.
   at: update_autoload (editor/editor_autoload_settings.cpp:551)
Running: D:/GODOT/GODOT 4/Godot_v4.0-stable_win64.exe/Godot_v4.0-stable_win64.exe --path D:/Projects/GAMEDEV/Godot%20DEV/NF4M_2D_Gdt --remote-debug tcp://127.0.0.1:6007 --editor-pid 16984 --position 384,256 res://core/scenes/main.tscn
Godot Engine v4.0.stable.official.92bee43ad - https://godotengine.org
Vulkan API 1.3.224 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1050 Ti

ERROR: Attempt to open script 'res://core/scripts/ship.gd' resulted in error 'File not found'.
   at: (modules/gdscript/gdscript.cpp:1043)
ERROR: Attempt to open script 'res://core/scripts/background.gd' resulted in error 'File not found'.
   at: (modules/gdscript/gdscript.cpp:1043)
ERROR: Attempt to open script 'res://core/scripts/cell.gd' resulted in error 'File not found'.
   at: (modules/gdscript/gdscript.cpp:1043)
ERROR: Attempt to open script 'res://core/scripts/gui2.gd' resulted in error 'File not found'.
   at: (modules/gdscript/gdscript.cpp:1043)
ERROR: Attempt to open script 'res://core/scripts/gui_gameover.gd' resulted in error 'File not found'.
   at: (modules/gdscript/gdscript.cpp:1043)
ERROR: Can't open file from path 'res://fonts/PT Sans_Bold.ttf'.
   at: (core/io/file_access.cpp:698)
ERROR: BUG: Unreferenced static string to 0: _update_scrollbars
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: thread_end
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: _physics_process_internal
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: _update_script_names
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: GuiToggleOnDisabledMirrored
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: raise
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: ShaderCompilation
   at: unref (core/string/string_name.cpp:129)
ERROR: Pages in use exist at exit in PagedAllocator: N7Variant5Pools11BucketLargeE
   at: (./core/templates/paged_allocator.h:140)
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
   at: _EDITOR_GET (editor/editor_settings.cpp:1101)
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
   at: _EDITOR_GET (editor/editor_settings.cpp:1101)
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
   at: _EDITOR_GET (editor/editor_settings.cpp:1101)
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
   at: _EDITOR_GET (editor/editor_settings.cpp:1101)
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
   at: _EDITOR_GET (editor/editor_settings.cpp:1101)
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
   at: _EDITOR_GET (editor/editor_settings.cpp:1101)
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()

**Comment by clayjohn** [comment]
This is not an acceptable bug report. Please fill out each section of the template properly. 

We have a [useful guide](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#reporting-bugs) if you do not know how to make a bug report
