### ISSUE TITLE
Release Notes link yields 404 on 4.0-stable Release md.

### ISSUE THREAD

**Issue by changeling** [godotengine/godot#74160]
### Godot version

4.0

### System information

4.0-stable

### Issue description

The [Release Notes](https://godotengine.org/article/godot-4-0-sets-sail/) link at https://github.com/godotengine/godot/releases/tag/4.0-stable yields 404.

(Adding this as a housekeeping reminder on the off-chance it’s an oversight.)

### Steps to reproduce

Click on [Release Notes](https://godotengine.org/article/godot-4-0-sets-sail/) .

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
That's expected, the blog post will be published in a couple of hours.

**Comment by akien-mga** [comment]
It's up :)
https://godotengine.org/article/godot-4-0-sets-sail/
