### ISSUE TITLE
3 to 4 converter adds seemingly spurious ") #"

### ISSUE THREAD

**Issue by miv391** [godotengine/godot#74171]
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Windows 10

### Issue description

This Godot 3 line

```gdscript
assert(r.hash() == {"a":1, "b":2}.hash())
```

was converted to this:

```gdscript
assert(r.hash() == {"a":1) #,"b":2}.hash())
```

For some reason `) #` is added after `1`.

### Steps to reproduce

Just converting Godot 3 project containing the line to Godot 4.

### Minimal reproduction project

N/A

**Comment by Chubercik** [comment]
it would seem this part of the converter's code is responsible for this:

https://github.com/godotengine/godot/blob/3695fe5a573678c6491a6a33f19f9329d3256a48/editor/project_converter_3_to_4.cpp#L2022

the whole block looks like this:

```cpp
//  assert(speed < 20, str(randi()%10))  ->  assert(speed < 20) #,str(randi()%10))    GDScript - GDScript bug constant message
if (line.contains("assert(")) {
    int start = line.find("assert(");
    int end = get_end_parenthesis(line.substr(start)) + 1;
    if (end > -1) {
        Vector<String> parts = parse_arguments(line.substr(start, end));
        if (parts.size() == 2) {
            line = line.substr(0, start) + "assert(" + parts[0] + ") " + line.substr(end + start) + "#," + parts[1] + ")";
        }
    }
}
```

**Comment by olivierLefebvre96** [comment]
@Chubercik Yes, I think adding two cases handling '{' and '}', like below, to the switch of this function would solve the problem:
https://github.com/godotengine/godot/blob/3695fe5a573678c6491a6a33f19f9329d3256a48/editor/project_converter_3_to_4.cpp#L1207
```
case '{': {
  parts_counter++;
  if (parts_counter == 1 && !is_inside_string) {
    start_part = current_index;
  }
  break;
  };
case '}': {
  parts_counter--;
  if (parts_counter == 0 && !is_inside_string) {
    parts.append(line.substr(start_part + 1, current_index - start_part - 1));
    start_part = current_index;
  }
  break;
};
```

I'm very new to contributing on Github and Godot (reading Godot's contribution docs right now) but I wouldn't mind someone else doing the PR if these changes work.
