### ISSUE TITLE
Large Texture3D gets Corrupted

### ISSUE THREAD

**Issue by 1derless** [godotengine/godot#74173]
### Godot version

4.0

### System information

Windows 10

### Issue description

Image data seems to get corrupted for `Texture3D`s above a certain size.

Large `Texture3D`s seem to work just fine in Godot 3.

### Steps to reproduce

I created a large 3D texture and rendered part of it with a simple shader. It should repeat 4 times in the z-axis but if it's  larger than about 256x256x256, it repeats much more than that, and some of the texture seems to be cut off in the z-axis.

I have also found on multiple-channel textures, sometimes data from one channel seems to leak into data from other channels, eg data from the alpha channel showing up as color.

### Minimal reproduction project

[Texture3dBugDemo.zip](https://github.com/godotengine/godot/files/10864257/Texture3dBugDemo.zip)

**Comment by DanGrizzly** [comment]
I am also having this issue, described on discord: https://discord.com/channels/212250894228652034/1082287525156098119

**Comment by clayjohn** [comment]
Taking a look at your MRP, it looks like the texture is appearing with 2x the intended frequency with FORMAT_L8. The frequency increases if the size of the color format increases (i.e. FORMAT_RGBA8 has a much higher frequency)
