### ISSUE TITLE
Crash after a few seconds, exported exe, only without debug.

### ISSUE THREAD

**Issue by filipex2000** [godotengine/godot#74179]
### Godot version

4.0 (RCs too)

### System information

Windows 10, Vulkan, Radeon RX 580, Intel(R) Xeon(R) CPU E3-1220, 32 GB memory v3 @ 3.10GHz, 

### Issue description

Whenever I export an exe of my game without debug enabled, the game freezes and crashes after a few seconds of no unexpected behaviour. The crash is completely unrelated to anything I've been doing. After launching the game from CMD I recieve only one error. Shortly after it closes.

ERROR: FATAL: Index p_index = -1 is out of bounds (size() = 0).
   at: get (./core/templates/cowdata.h:155)

ERROR: FATAL: Index p_index = -1 is out of bounds (size() = 0).
'ERROR:' is not recognized as an internal or external command,
operable program or batch file.

F:\Godot 4\EXPORT>   at: get (./core/templates/cowdata.h:155)

### Steps to reproduce

Export the game project without debug enabled, wait a few seconds, see if something happens?

### Minimal reproduction project

N/A

**Comment by RedMser** [comment]
You need to include a project zip that can be used to reproduce the bug, otherwise it is impossible to fix.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
