### ISSUE TITLE
Animation window: creating new animation beyond bottom of scrollview doesn't auto-scroll to bottom

### ISSUE THREAD

**Issue by hsandt** [godotengine/godot#74185]
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Linux Ubuntu 20.04 with Unity desktop

### Issue description

In the Animation window of the AnimationPlayer, when you create a new animation after many have been created, and scrollbar is not at the bottom, the new animation ends up in the hidden area at the bottom.

Usually in apps, this would auto-scroll the scroll view to the bottom, but currently it only focuses the new animation, so you still have to scroll down to the bottom manually (a trick is to press keyboard Up arrow to focus the element above, scrolling you down then press Down arrow to select the new animation). This is the trick I use in the GIF below:

![Godot 4 0 - new animation doesnt auto-scroll to bottom](https://user-images.githubusercontent.com/1067772/222255821-50160bb8-86b7-47e2-bee7-885d24b3c5f2.gif)

### Steps to reproduce

1. Create new Animation resource with many animations (enough to cover the whole height of the scroll view)
2. Add yet another animation
3. Bonus: press Up and Down arrow key as a trick. Or just scroll down with the mouse.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
This should be easy to do by enabling autoscroll on the ItemList (I don't know if this exists), or by scrolling to the bottom when creating a new animation.
