### ISSUE TITLE
HSlider themed with a texture problem (not appear)

### ISSUE THREAD

**Issue by alberto-mco** [godotengine/godot#74183]
### Godot version

Godot 4 since beta 17

### System information

Windows 11 x64

### Issue description

I notice that HSlider with a themed texture it's not working since Godot 4 Beta 17, it was working up to beta 16.

![hslider](https://user-images.githubusercontent.com/70795945/222252046-9809d1c0-50cd-41ca-abf3-528654a7d2c0.png)

### Steps to reproduce

1. Add a slider
2. Setup a new theme
3. Modify de grabber and slider with a StyledTextureBox

### Minimal reproduction project

1. Add a slider
2. Setup a new theme
3. Modify de grabber and slider with a StyledTextureBox

**Comment by YuriSizov** [comment]
There were no relevant changes between beta 16 and beta 17, but there were changes in beta 16, so you should see the same issue in that version. StyleBoxTexture has been changed and you need to adjust yours to use content margins properly, just like any other type of StyleBox. See https://github.com/godotengine/godot/pull/72124.

**Comment by alberto-mco** [comment]
I adjusted the content margin in the StyleBoxTexture and now it works. In previous versions this wasn't needed. Thanks for the info!
