### ISSUE TITLE
hint_normal_roughness_texture canvas shader compilation failing

### ISSUE THREAD

**Issue by bruce965** [godotengine/godot#74189]
### Godot version

v4.0.stable.mono.official [92bee43ad], v4.1.dev.custom_build [1c1524a65]

### System information

Windows 10, Vulkan API 1.3.217 - Forward+

### Issue description

`hint_normal_roughness_texture` references a uniform that does not exist.

### Steps to reproduce

Create a `ColorRect` node and add a new shader material with this code:
```shader
shader_type canvas_item;

uniform sampler2D test : hint_normal_roughness_texture, repeat_disable, filter_nearest;

void fragment() {
	float x = textureLod(test, SCREEN_UV, 0).x;
	COLOR = vec4(1., 0., 0., 1.);
}
```

Built shader code is:
```shader
{
    float m_x=texture(sampler2D(normal_roughness_buffer, material_samplers[0]), screen_uv).x;
    color=vec4(1.0,0.0,0.0,1.0);
}
```

`normal_roughness_buffer` is referenced, but does not exist.

> E 0:00:01:0578   _compile_variant: Failed parse:
> ERROR: 0:516: 'normal_roughness_buffer' : undeclared identifier 
> ERROR: 0:516: '' : compilation terminated 
> ERROR: 2 compilation errors.  No code generated.
> 
> 
> 
>   <C++ Source>   servers/rendering/renderer_rd/shader_rd.cpp:283 @ _compile_variant()

### Minimal reproduction project

[NormalBufferNotAccessible.zip](https://github.com/godotengine/godot/files/10865539/NormalBufferNotAccessible.zip)

**Comment by clayjohn** [comment]
Looks like we need to add an error when users attempt to use the hint_normal_roughness texture outside of a spatial shader. 

For clarity, hint_depth_texture and hint_normal_roughness_texture are only supported in spatial shaders

**Comment by bruce965** [comment]
I see. Apologies, I did not know 😅

I should be able to do it and open a pull-request
