### ISSUE TITLE
Godot 4.0 on Android sometimes creates InputEventScreenTouch with index = -1

### ISSUE THREAD

**Issue by pipejakob** [godotengine/godot#74199]
### Godot version

v4.0.stable.official.92bee43ad

### System information

Android 13.0

### Issue description

In Godot 3.5.1, every `InputEventScreenTouch` with `is_pressed() == true` would eventually be followed by an `InputEventScreenTouch` with `is_pressed() == false` for the same `index` value when the finger was lifted (in my experience).

In Godot 4.0, occasionally it will emit `InputEventScreenTouch` events with `is_pressed() == false` and `index == -1` to signal that all fingers have been lifted and should be reset (instead of using the same `index` values as before), but this new behavior isn't documented [in the class](https://docs.godotengine.org/en/stable/classes/class_inputeventscreentouch.html#class-inputeventscreentouch-property-index). I wasn't sure if this was an implementation bug or a documentation bug.

The Android input event that triggers this case is `AMOTION_EVENT_ACTION_CANCEL`, and you can see that the handling of this event has been changed from 3.5.1 ([implementation here](https://github.com/godotengine/godot/blob/9091309ab7d93a74217acaf4943d23e05a112f05/platform/android/android_input_handler.cpp#L171)) to 4.0 ([implementation here](https://github.com/godotengine/godot/blob/1f6a5426e2a473e978ab24e6fdd38b84b82f2018/platform/android/android_input_handler.cpp#L151)). In 3.5.1, the original index was always preserved, but in 4.0, you can see that every `index` gets overridden to `-1` during `AMOTION_EVENT_ACTION_CANCEL`.

### Steps to reproduce

I've attached two projects that are identical, except that one runs in Godot 3.5.1 and the other has been upgraded to Godot 4.0.

For each project:
1. Open the project in the corresponding version of Godot.
2. Export the project for Android.
3. Install and run the APK on an Android device.
4. Touch the screen with many different combinations of fingers. Add fingers randomly, remove them randomly, add a few at once, remove a few at once. The label on the screen shows how many fingers are currently being tracked. Every time you have removed all fingers, the counter should be back at 0.

In the Godot 4.0 version of the project, I can easily trigger cases where all of my fingers have been removed from the screen, but the counter still says `2` or `3` instead of `0`.

However, this can be fixed by changing the included code from:

```
var fingers = {}

func _unhandled_input(event):
        if event is InputEventScreenTouch:
                if event.is_pressed():
                        fingers[event.index] = true
                else:
                        fingers.erase(event.index)
```

to:

```
var fingers = {}

func _unhandled_input(event):
        if event is InputEventScreenTouch:
                if event.is_pressed():
                        fingers[event.index] = true
                else:
                        if event.index == -1:
                                fingers.clear()
                        else:
                                fingers.erase(event.index)
```

If this change is expected in game code, then I would expect explicit documentation about the behavior in the `InputEventScreenTouch` class.

### Minimal reproduction project

[multitouch_3.5.1.zip](https://github.com/godotengine/godot/files/10866472/multitouch_3.5.1.zip)
[multitouch_4.0.zip](https://github.com/godotengine/godot/files/10866474/multitouch_4.0.zip)

**Comment by pipejakob** [comment]
Thank you for clarifying. It sounds like this issue should track updating the documentation so that users can understand this new expected behavior.

I can take a crack at this myself.

**Comment by m4gr3d** [comment]
> Thank you for clarifying. It sounds like this issue should track updating the documentation so that users can understand this new expected behavior.
> 
> I can take a crack at this myself.

Sounds good. I'll close this issue but feel free to comment if you have any follow-up questions.

**Comment by Federico-Ciuffardi** [comment]
Whenever I press the screen with three or more fingers, next to the correct touch press events, touch release events with index `-1` are triggered (even if I don't lift my fingers). 

Is this a Godot issue? Or is it because of the underlying Android events?

Example output (from [this project](https://github.com/godotengine/godot/files/11306712/project.tar.gz))):
```
InputEventScreenTouch: index=0, pressed=true, position=((1506, 504)), double_tap=false
InputEventScreenTouch: index=1, pressed=true, position=((1279, 544)), double_tap=false
InputEventScreenTouch: index=2, pressed=true, position=((1039, 524)), double_tap=false
InputEventScreenTouch: index=-1, pressed=false, position=((1506, 504)), double_tap=false
InputEventScreenTouch: index=-1, pressed=false, position=((1279, 544)), double_tap=false
InputEventScreenTouch: index=-1, pressed=false, position=((1039, 524)), double_tap=false
```
