### ISSUE TITLE
Localization POT generation does not regognize text on instanced nodes.

### ISSUE THREAD

**Issue by Okxa** [godotengine/godot#74194]
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Arch Linux

### Issue description

Localization POT generation does not regognize text on instanced nodes.

### Steps to reproduce

1. Create a 2D main scene
2. Create a scene with a button as the single node
3. Add the button scene as a instance to the main scene and edit the button instances text
4. Add a button node (not the instance) to the main scene and edit the buttons text
5. Go to Project Settings -> Localization -> POT generation, Add the main scene and generate POT file
6. observe the POT file and see there is no localization ID for the instanced buttons text

### Minimal reproduction project

[localization_instances.zip](https://github.com/godotengine/godot/files/10865767/localization_instances.zip)

**Comment by Okxa** [comment]
Issue might be that instanced button has no type when queried with `SceneState.get_node_type()`

The parser checks with the type if the node is translatable

https://github.com/godotengine/godot/blob/1c1524a651e6d670d0d591b050d8c4bbb721d6e9/editor/plugins/packed_scene_translation_parser_plugin.cpp#L54-L58

Tested if instances behave differently with the checks used in the parser (only in editor though):

```gdscript
func _ready():
    var state = ResourceLoader.load("res://main.tscn").get_state()
    var nodecount = state.get_node_count()
    for i in range(0, nodecount):
        var nodetype = state.get_node_type(i)
        print(state.get_node_name(i), ", type: ", nodetype, ", child of Control: ", ClassDB.is_parent_class(nodetype, "Control"), ", child of Window: ", ClassDB.is_parent_class(nodetype, "Window"))
        var propcount = state.get_node_property_count(i)
        for j in range(0, propcount):
            print(state.get_node_property_name(i, j), " ", state.get_node_property_value(i, j))
```

outputs:
```
...
Button, type: Button, child of Control: true, child of Window: false
offset_right 8
offset_bottom 8
text NORMAL_BTN
btn_instance, type: , child of Control: false, child of Window: false
offset_top 45
offset_bottom 188
text INSTANCED_BTN
```

**Comment by brunolucena** [comment]
I'm also facing this issue. Any updates on this?
