### ISSUE TITLE
editor freezes when duplicating a few CSG nodes in a particular case

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#74191]
### Godot version

4.0 stable

### System information

linux

### Issue description

Trying to duplicate the selection of nodes in the mrp freezes the editor with no particular console output.
Looking at the task manager, godot is stuck using 100% of a core and doesn't look to eat more and more ram.

### Steps to reproduce

see mrp.
Select all of the root node's children and either hit Ctrl+D or use the menu item for duplicating a node selection.

### Minimal reproduction project

[duplicate_nodes_freeze.zip](https://github.com/godotengine/godot/files/10865664/duplicate_nodes_freeze.zip)

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/73927.

**Comment by YuriSizov** [comment]
Indeed, this is the same issue as https://github.com/godotengine/godot/issues/73927 and https://github.com/godotengine/godot/issues/74343. Your MRP works very well, thanks! But I'll close this one as a duplicate so we don't have multiple reports about the same.
