### ISSUE TITLE
Scale mode needs to support all axes [prototyping essential]

### ISSUE THREAD

**Issue by JonasT** [godotengine/godot#7419]
**Operating system or device - Godot version:**
 Fedora 25 x64 - v2.1.1.stable.official

**Issue description** (what happened, and what was expected):
Scale mode needs to support all axes for fast prototyping. For level prototyping, multiple primitives types are absolutely required ( #1381 ) as well as fast texture assignment ( #7418 ) as well as being able to scale it on all axes separately. Otherwise, making up walls and floors is just too tedious. Unless this functionality is added, the editor will always remain more of a basic 3d model placement tool rather than something that can be actually used for making up basic levels quickly.

**Steps to reproduce:**
1. Press R or scale mode button
2. Observe no visible axes in the 3d view for separate dragging, and also no other obvious way to scale on just a single axis

**Link to minimal example project** (optional but very welcome):

**Comment by n-pigeon** [comment]
I agree.

**Comment by clofresh** [comment]
If I wanted to try to work on this feature, where should I look?

**Comment by Andev08** [comment]
+1 from me too

**Comment by jagt** [comment]
I suppose this is implemented in #11478 ?

**Comment by bojidar-bg** [comment]
Yes indeed. Closing as done in #11478 :tada:

**Comment by n-pigeon** [comment]
Ah sorry missed this Issue xD
