### ISSUE TITLE
Alternative to FXAA

### ISSUE THREAD

**Issue by grabiller** [godotengine/godot#742]
Detect platform support for Depth Buffer/Texture (OES_depth_texture) in order to implement a FXAA alternative that does not blur rendered Textures.

**Comment by bojidar-bg** [comment]
I'd guess that's worth tagging for 3.0..

**Comment by Calinou** [comment]
MSAA is now implemented in Godot 3.0, but I guess you also want other alternatives such as SMAA (which works on transparent textures).

**Comment by reduz** [comment]
SMAA or TAA are no go due to new renderer design. FXAA could be
reintroduced if you reaaally want it, since it's just a few lines of code
