### ISSUE TITLE
Bitmap fonts (.fnt or BMFont) don't seem to work in Godot 4

### ISSUE THREAD

**Issue by svendixon** [godotengine/godot#74200]
### Godot version

Godot 4.0.stable.official

### System information

Windows 11, Vulkan, GTX 980 Ti (528.02)

### Issue description

I'm not sure if there are settings I need to configure in Godot 4 for bitmap fonts to display correctly or not. But they worked fine in Godot 3.x. 

This is what it looked like in 3.5
![bitmapfont_issue_godot4_1](https://user-images.githubusercontent.com/14341036/222295956-984e70b1-c20c-4449-9472-860cf3e65ad6.png)

This is what it looks like in 4.0
![bitmapfont_issue_godot4_2](https://user-images.githubusercontent.com/14341036/222295971-32de7985-03c4-42d3-976c-ee0765b37e07.png)

The black outline and drop shadow are gone and the line spacing is off.

There is an example font in the [documentation](https://docs.godotengine.org/en/stable/tutorials/ui/gui_using_fonts.html) for alternatively setting up a monospaced bitmap font using an image, however I have the bitmap font file I want to use working fine in 3.5, I don't want to use a monospaced font.

### Steps to reproduce

I have included zips of both a 3.5 and 4.0 project with a label and font assigned.

### Minimal reproduction project

[BitmapFont_v3_5.zip](https://github.com/godotengine/godot/files/10866441/BitmapFont_v3_5.zip)
[BitmmapFont_v4_0.zip](https://github.com/godotengine/godot/files/10866442/BitmmapFont_v4_0.zip)

**Comment by bruvzg** [comment]
Your font have alpha channel defined as outline, but outline size (probably pre version 2 fonts) is not set. Add `outline=32` to the end of first line of `fnt`, and set the outline size in the theme override properties to the same value (32), like this:

```
info face="bitmap_test_font" size=32 bold=0 italic=0 charset="" unicode=0 stretchH=100 smooth=1 aa=1 padding=0,0,0,0 spacing=1,1 outline=32
common lineHeight=12 base=26 scaleW=128 scaleH=64 pages=1 packed=0 alphaChnl=1 redChnl=0 greenChnl=0 blueChnl=0
page id=0 file="bitmap_test_font.png"
chars count=96
char id=33 x=95 y=18 width=4 height=8 xoffset=0 yoffset=4 xadvance=3 page=0 chnl=0 letter="!"
...
```

3.x do not read channel data or support separate outline, so it's always displaying image as is.

We probably should assume default outline size is `1` not `0` for the fonts like this.

**Comment by svendixon** [comment]
Ah ok, didn't know 3.x ignored the color channel values and the base value for line height. Good to know. Thank you.
