### ISSUE TITLE
"NO DC" In every window created by Godot

### ISSUE THREAD

**Issue by Totobal5** [godotengine/godot#74201]
### Godot version

4.0 stable

### System information

Window 10, OpenGL API 3.3.0 NVIDIA 528.49, NVIDIA GeForce GTX 1660 SUPER

### Issue description

In every window created by the engine it appear a "NO DC" message
![ZC5kLhyoOV](https://user-images.githubusercontent.com/90012149/222300913-936397a8-abc5-4bd0-ab9f-5019b5d9c029.png)
![Godot_v4 0-stable_win64_mKuaM5y7nB](https://user-images.githubusercontent.com/90012149/222300930-7e99122f-27aa-4b38-b8a4-c48f8ac4c351.png)

### Steps to reproduce

1) Open Godot Engine

### Minimal reproduction project

- No proyect was open

**Comment by gotnospirit** [comment]
try
https://docs.godotengine.org/en/stable/about/troubleshooting.html#some-text-such-as-no-dc-appears-in-the-top-left-corner-of-the-project-manager-and-editor-window

**Comment by Totobal5** [comment]
Thanks for the help!!
