### ISSUE TITLE
Physics network delay

### ISSUE THREAD

**Issue by theromis** [godotengine/godot#74207]
### Godot version

4.0.stable

### System information

Macos (probably any)

### Issue description

Sorry for creating bug, because I don't know other way to keep in touch with godot developers.

Probably typical physics multiplayer problem network delay on physics calculation

![Screenshot 2023-03-01 at 7 58 24 PM](https://user-images.githubusercontent.com/3720229/222327636-06cc7b0a-b078-42ea-b297-a3daef1bdf01.png)
below is ServerSyncronizer setup (rest of it - default, replication interval 0 on all syncronizers)
![Screenshot 2023-03-01 at 8 04 02 PM](https://user-images.githubusercontent.com/3720229/222328294-1e3e598f-66d9-4ee4-bc26-86464238b186.png)

```gdscript
signal jump(force:Vector3)
...
@rpc("call_local")
func server_jump(force: Vector3):
	jump.emit(force)

func _input(event):
	if event is InputEventMouseButton:
		if event.button_index == MOUSE_BUTTON_LEFT:
			if event.pressed:
				mouse_down_position = event.position
				mouse_is_down = true
				can_jump = false
				if straightUp:
					server_jump.rpc(Vector3(0, jumpForce, 0))
			elif mouse_is_down:
				var mouse_delta = event.position - mouse_down_position
				set_can_jump(mouse_delta)
				mouse_is_down = false
				if not straightUp:
					rotate_arrow(event.position)
					if can_jump:
						var force = mouse_delta
						if force.length() > force_max:
							force = force.limit_length(force_max)
						if jumpInverse:
							server_jump.rpc(Vector3(-force.x, force.y, 0) * jumpStreingth)
						else:
							server_jump.rpc(Vector3(force.x, -force.y, 0) * jumpStreingth)
```
and player gets this signal
```gdscript
func _on_player_input_jump(force: Vector3):
	linear_velocity = force
```
https://youtu.be/BQJk97DUCr4

on the video strawberry - server, watermelon - client
it take about 0.5 second to trigger jump from client (server side and single player is perfect)
also with physics FPS set to 60 but client is jerky with physics FPS increased to 120 becomes smooth.

My question is there a way to inter/extrapolate to have movement smoother and of course is it possible to reduce jump delay?
Understand this almost impossible but any Ideas will be great.

PS: Thank you for 4.0 release

### Steps to reproduce

Probably any rigid body physics with godot multiplayer syncronizer.

### Minimal reproduction project

Project is too huge to send here :(

**Comment by theromis** [comment]
changing
```
					server_jump.rpc(Vector3(0, jumpForce, 0))
```
to
```
					server_jump.rpc_id(1, Vector3(0, jumpForce, 0))
```
doesn't helped and `@rpc("call_local", "unreliable")` too.
Is this delay on all network gameplays?

**Comment by Calinou** [comment]
Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

> also with physics FPS set to 60 but client is jerky with physics FPS increased to 120 becomes smooth.

Are you using a 120 Hz display? Godot currently physics interpolation out of the box, so this is expected.

**Comment by theromis** [comment]
@Calinou replicated scene_replication level spawning logic with disabled nakama client, everything works like a blast. I think it because previously I've spawned level manually over rpc. Now I have about a week fun to reorganize everything.

Thank you again.

Godot engine THE BEST

**Comment by Calinou** [comment]
Closing, as this isn't an engine issue.
