### ISSUE TITLE
Global Shader Parameters not exposed to C#

### ISSUE THREAD

**Issue by cuckydev** [godotengine/godot#74208]
### Godot version

4.0.stable

### System information

Windows 10

### Issue description

RenderingServer's global shader parameters are not exposed in C#, resulting in an error about the methods not being defined.
This results in the following error:
`'RenderingServer' does not contain a definition for 'global_shader_parameter_set'`

### Steps to reproduce

Attempt to use the RenderingServer global shader parameters the same as in GDScript. There's no definitions for any of the methods.

### Minimal reproduction project

[GlobalShaderParameters.zip](https://github.com/godotengine/godot/files/10867754/GlobalShaderParameters.zip)
Provided are both a .cs and .gd script for setting the global shader parameter

**Comment by constantitus** [comment]
It's GlobalShaderParameterSet, C# uses PascalCase as opposed to GDscript's camel_case.

**Comment by cuckydev** [comment]
Thank you, I appear to have overlooked this. My sincerest apologies.
