### ISSUE TITLE
UV modes should have a "world position mode" with a single scale factor for automatic cubic projection based on world coordinates

### ISSUE THREAD

**Issue by etc0de** [godotengine/godot#7420]
**Operating system or device - Godot version:**
 Fedora 25 x64 - v2.1.1.stable.official

**Issue description** (what happened, and what was expected):
UV modes should have a "world position mode" with a single scale factor for automatic cubic projection based on world coordinates. This is required for good brush editing, which combined with easy texture assignment ( #7418 ), easy scaling on all axes ( #7419 ) and more primitives ( #1381 ) could be an absolute game changer for being able to slap brushes of different sizes into the level quickly, then assign automatic "World UV mapping" with a basic scale factor to avoid manual UV adjustments. This is also how most oldschool BSP editors work (Quake 3, ...) which is by the way an absolutely amazing and super quick way of throwing together basic level geometry. I know this is going out of style for big budget productions where people just model everything with infinite detail in a 3d modeler, but for indie games or just quick prototyping this will always be a relevant approach to save on time.

**Steps to reproduce:**
1. Assign a material to a TestCube
2. Search FixedMaterial options for "Uv xForm"
3. Observe that there is no simple switch to simply use world coordinates to do an automatic cube mapping at a given scale factor

**Link to minimal example project** (optional but very welcome):

**Comment by Calinou** [comment]
This is supported since Godot 3.0 with the triplanar mapping option (**World Triplanar** must be enabled in the SpatialMaterial).
