### ISSUE TITLE
Dock position widget never disappears after changing position of a dock

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#74215]
### Godot version

4.0 stable

### System information

win 11

### Issue description

So if I click the three dots next to the docker and I choose another position, the docker moves away, but the popup stays where it is. Maybe I'm just dumb, but I thought that if I clicked on the popup again, it would move the new docker that's in the position where the old one used to be. But it doesn't work like that, it still moves the old one.

### Steps to reproduce

Click the three dots and move a docker.

### Minimal reproduction project

N/A

**Comment by YuriSizov** [comment]
Yeah, it's a very old issue, very much present in every version of Godot 3, and pretty annoying.
