### ISSUE TITLE
Compiler complains "no symbol definition" if code "getString(R.string.var_name)" in Android module (Java singleton)

### ISSUE THREAD

**Issue by KenHuang0917** [godotengine/godot#7421]
**Operating system or device - Godot version:**
macOS Sierra 10.12.1, Godot 2.1 stable

**Issue description** (what happened, and what was expected):
Hi, I am not sure if it is a bug or just my misunderstanding. I write a Java module and it works fine except that it can't accept something like "getString(R.string.var_name)", where var_name is the variable put in source file: "res/values/strings.xml" as a normal Android project usually does. Can I use "getString(R.string.var_name)" in Java module (Singleton)? If yes, where should i put the var_name string in and how to add this .xml file for compiling?

**Steps to reproduce:**
Use "getString(R.string.var_name)" in Java module (Singleton) and put var_name string in "res/values/strings.xml", the compiler complains "no symbol definition of var_name"

**Comment by RandomShaper** [comment]
Merging #7625 should do the trick.

Anyway, for your convenience and for the registers, I'm posting a [zip file](https://drive.google.com/open?id=0B-WnZEtQk02PbmlTanZteXE0TTg) which contains both a test module and a test project. Don't forget to set the custom export package.

It's also worth mentioning that the `R` class for the resource ids is always `com.godot.game.R`. One last thing, don't forget to add `env.android_add_res_dir("module-dir-relative-res-dir")` to your module's _build.py_.
