### ISSUE TITLE
Project Manager doesn't convert colors and icons to the light theme

### ISSUE THREAD

**Issue by ShatReal** [godotengine/godot#74214]
### Godot version

4.0 stable

### System information

win 11

### Issue description

![image](https://user-images.githubusercontent.com/69117768/222351990-34470553-f694-4a42-8ef4-74c4d461299a.png)

You can hardly make out the files. And the buttons on the top left are invisible!

### Steps to reproduce

I know this is very hard, but set your editor to light theme.

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
I expect it's fixed after a restart? Might just be a theme reload issue.

**Comment by ShatReal** [comment]
Restarting the editor doesn't fix it.
