### ISSUE TITLE
Holding Ctr+S will continually keep saving the project after letting go.

### ISSUE THREAD

**Issue by NumRoll** [godotengine/godot#74229]
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Operating System: openSUSE Leap 15.3 KDE Plasma Version: 5.18.6 KDE Frameworks Version: 5.76.0 Qt Version: 5.12.7 Kernel Version: 5.3.18-150300.59.101-default OS Type: 64-bit Processors: 4 × Intel® Core™ i5-2400 CPU @ 3.10GHz Memory: 7,7 GiB, Godot: OpenGL API 3.3.0 NVIDIA 390.157 - Compatibility - Using Device: NVIDIA Corporation - GeForce GT 1030

### Issue description

If you hold ctrl+S for more than a second, godot will continue to save even if you let go.
It should just save once.

### Steps to reproduce

1.Open a godot project
2.Save a scene by holding down ctr+S for more then a second.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Editor keyboard shortcuts are configured to accept echo (key repeat) events by default, but we should disable this for a select few shortcuts.

**Comment by akien-mga** [comment]
Why close?

**Comment by akien-mga** [comment]
Seems like this was fixed, I can reproduce it in 4.0-stable but not in 4.0.3-stable and 4.1-stable.
