### ISSUE TITLE
Crash！Ctrl + z to undo or   backspace when create a new folder in godot  4.0 stable editor

### ISSUE THREAD

**Issue by Kurt-Morrison** [godotengine/godot#74234]
### Godot version

4.0 stable

### System information

ubuntu16.04

### Issue description

ctrl + z to undo or   backspace when create a new folder in godot 4.0 stable editor，crash！

### Steps to reproduce

ctrl + z to undo or   backspace when create a new folder in godot 4.0 stable editor

### Minimal reproduction project

Any scene

**Comment by akien-mga** [comment]
Duplicate of https://github.com/godotengine/godot/issues/74197
