### ISSUE TITLE
Better conveying that the scene has to have a root node

### ISSUE THREAD

**Issue by bojidar-bg** [godotengine/godot#7424]
As started on discussions in #7417.

Currently, it is __probably__ a bit unintuitive that scenes need to have a root node to be saved (or to be called scenes at all..). Some proposals for making it more intuitive (from the above-mentioned issue) are:
> @bojidar-bg
> Wouldn't it be better if we show a big add node button instead of the 2D/3D viewport?
Or maybe, when you click new scene, we might let you directly choose a root node, so you have nothing empty to save anyway?

> @akien-mga 
>We could refactor the option to create new scenes to be a bit like the creation of new text documents in modern word processors, showing various icons + text for the available options:
>- Create new scene with root node <Node>, with an easy to use list where you can pick any node from the typical node tree.
>  * Maybe also with 3 preconfigured choices to create a 2D (`Node2D` root), 3D (`Spatial` root) or GUI (`Control` root) scene
>- Create new scene inheriting a base scene
>- Create new scene from template (i.e. copy and rename an existing scene - potentially from outside the project folder - and open it)
>
>Not sure how useful that would be, but if done in a way that is good-looking, it could at least feel more polished and give new users something more tangible than a blank scene.

**Comment by Zylann** [comment]
The main root nodes I use are Node (for levels), Node2D and Spatial. A dialog asking which node to create first would be ok, eventually with small a "most used" list at the top?

**Comment by bojidar-bg** [comment]
@Zylann Yeah, some useful base nodes (maybe with useful subnodes as well) should probably be shown..
I guess the following list summarizes the nodes I use the most for root nodes:
* Node
  * CanvasLayer (though I usually put the canvaslayer in the scene instancing the gui, not in the gui scene)
  * ParallaxBackground
* Spatial
  * RigidBody | KinematicBody | StaticBody
  * Position3D | Mesh (?)
* Node2D
  * RigidBody2D | KinematicBody2D | StaticBody2D
  * Position2D | Sprite (?)
* Control
  * *Container | CenterContainer | ..
  * ReferenceFrame | Panel

**Comment by eon-s** [comment]
I mostly use Node2D/Spatial for the first prototype scene, then could be any of the big four (Node/Spatial/Node2D/Control) for big/complex scenes.

The problem with Node2D and Control is these could be easily moved and new people can make a mess and not understand what happens, but if can be added and locked on the tree, will be nice.

---------

Not sure if this is for another (or the other) issue but what if the first empty scene of a new project comes with a small tree, like a "welcome" scene?

**Comment by Einlander** [comment]
as long as we get an option to skip the selection or have an editor/project option to skip it all together. sometimes I really do need a rigidbody as the root node.

**Comment by Zylann** [comment]
@Einlander then you can choose it in the dialog? You should not be limited to "most used nodes", these could be listed first but you can choose whatever node you want.

**Comment by jacobspeicher** [comment]
What about when you make a new scene, the "add a node" pop-up just appears, and you can choose any node you want.

**Comment by nunodonato** [comment]
According to steam, I have more than 600 hours of usage in Godot (not counting my own builds). Number of times I tried to save an empty scene: 2

The first one was because I didn't know it couldn't be done. The 2nd was just a mistake (instinctive impulse to save something new?).

I felt like dropping my 2 euro cents here, I think this is mostly irrelevant and, although nice, I agree with @akien-mga in the sense that the added complexity is not worth it. 

but carry on :)

**Comment by KoBeWi** [comment]
> Create new scene with root node , with an easy to use list where you can pick any node from the typical node tree.
> Maybe also with 3 preconfigured choices to create a 2D (Node2D root), 3D (Spatial root) or GUI (Control root) scene

This is already in 3.1. Although creating an inherited scene sounds useful too.

**Comment by amisner2k** [comment]
Should this issue be closed? Seems like the current stable version 3.1 pretty much addresses this issue.

![image](https://user-images.githubusercontent.com/55228705/65537913-0f646880-debb-11e9-8efa-8c5471bb4229.png)

**Comment by akien-mga** [comment]
Agreed, I think we can consider this solved.
