### ISSUE TITLE
Pausing the execution of the game does not stop the music from playing.

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#74254]
### Godot version

v3.5.2.rc2.official [1a2bf3eb4]

### System information

w10 64

### Issue description

Put a track to play (audiostreamplayer) and run the project, then pause the playback of the project, the audio will continue playing.
The sound engine is supposed to stop as well.

Pause from here
![Captura](https://user-images.githubusercontent.com/19652075/222549471-cddcc8a5-dd7b-42e7-87aa-736b65a36259.PNG)

### Steps to reproduce

Run the project in which a song plays.
Pause the running project.
Notice that the music continues to play.

### Minimal reproduction project

...

**Comment by Calinou** [comment]
@Torguen Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.
