### ISSUE TITLE
ProceduralSkyMaterial doesn't update visually and stays completely white once a Cover Texture is added and removed

### ISSUE THREAD

**Issue by jcommander** [godotengine/godot#74259]
### Godot version

4.0.stable

### System information

Windows 10, Forward+

### Issue description

While checking out the ProceduralSkyMaterial and assigning a Texture to see the Effect, I noticed that after removing it, the Sky stayed completely blank/white instead of going to its set colors, changing the Sky's Colors or any other properties doesn't seem to reset the Sky to its Colors.
At this point you either have to reopen the scene in the editor or create a new ProceduralSkyMaterial for it to update properly.

### Steps to reproduce

1. Create a ProceduralSkyMaterial as the Sky Material for the current WorldEnvironment
2. Assign a Cover Texture
3. Remove the Cover Texture

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
It looks like there are two problems here:
1. The generated shader code includes the sky cover even after the texture is removed. When the texture is removed the shader should revert back to the shader version not using the sky cover
2. The hint_texture_default_black is providing a white texture for some reason.

**Comment by kamalesh0406** [comment]
Hi @clayjohn @Calinou, I am looking to make my first contribution to the engine. Can you assign this issue to me? Thank you!

**Comment by Zireael07** [comment]
@kamalesh0406 Godot does not practice assigning issues. Just make a PR.

**Comment by ibotha** [comment]
I have played around with this issue and it seems to be because the image is not set to nil if no image was provided, instead it sets it to "RID()". I have locally tested setting the sky_cover property on the material to "Variant()", that is to say "Nil", and the bug seems to be fixed. My PR is here https://github.com/godotengine/godot/pull/75469
