### ISSUE TITLE
Unlit (unshaded) material property is ignored in glTF files

### ISSUE THREAD

**Issue by prominentdetail** [godotengine/godot#74268]
### Godot version

4.0

### System information

windows 10

### Issue description

Gltf files that have KHR_materials_unlit (unshaded mode), won't be set to Unshaded in Godot.

### Steps to reproduce

The example project contains a gltf model that is suppose to be unlit/unshaded. However, Godot imports it incorrectly with its Shading mode set to per-pixel instead.

### Minimal reproduction project

[gltfUnshadedBug.zip](https://github.com/godotengine/godot/files/10877513/gltfUnshadedBug.zip)

**Comment by Calinou** [comment]
There is no instance of `materials_unlit` anywhere in the codebase, so this glTF extension needs to be implemented.

**Comment by prominentdetail** [comment]
Can we get this working for line meshes as well? At the moment they always import as shaded.
