### ISSUE TITLE
Export doesnt use selected renderer

### ISSUE THREAD

**Issue by 7projected** [godotengine/godot#74263]
### Godot version

4.0

### System information

Windows 10

### Issue description

I have Godot 4.0 running opengl3, whenever I export the project, it defaults back to vulkan. If this is a feature, then its a bad one.

### Steps to reproduce

Run Godot in opengl3
Export the project.
Attempt to run.
Its vulkan

### Minimal reproduction project

This works in any project

**Comment by Calinou** [comment]
Can you post the contents of your project's `project.godot` file here? The rendering method project setting has a `.mobile` override, and the renderer selection dropdown will not affect this override currently.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/73712.
