### ISSUE TITLE
OpenGL: Shader uses incorrect default repeat/filter

### ISSUE THREAD

**Issue by billymyers** [godotengine/godot#74273]
### Godot version

4.0.stable

### System information

Windows 11, GLES3, AMD RX 580 (4 GB), AMD Adrenalin 23.2.2

### Issue description

I have two palette swap shaders ([this one](https://github.com/KoBeWi/Godot-Palette-Swap-Shader) and another simpler one I found by googling "godot palette swap shader"). They behave correctly in 3.5.1.stable and 4.0.stable when using the Vulkan renderers, but do not work correctly at all in the GLES renderer on 4.0. The first shader doesn't change, and the second shader sets the entire sprite to be a color which is blended between the two colors I have in my palette texture.

![Shaders rendering correctly](https://user-images.githubusercontent.com/8889889/222653256-c16c7689-5148-45ba-9e6d-d990b00536a7.png)
*Shaders rendering correctly when using Mobile renderer*

![image](https://user-images.githubusercontent.com/8889889/222653506-b102809e-fc67-44d9-b1f8-16ecb4eacc98.png)
*Shaders rendering incorrectly when using Compatibility renderer*

### Steps to reproduce

1. Download reproduction project
2. Toggle between compatibility and either Mobile or Forward+ renderer
3. Witness shaders behaving incorrectly

### Minimal reproduction project

[broken shaders.zip](https://github.com/godotengine/godot/files/10879123/broken.shaders.zip)

**Comment by billymyers** [comment]
Something that I noticed - when I open up the reproduction project, it lets me know that glow is not supported when using Compatiblity mode. This shows up only in the reproduction project and not in my own project for some reason.

**Comment by dzil123** [comment]
Both shaders are fixed if you change the palette uniform to
```glsl
uniform sampler2D palette : filter_nearest, repeat_disable;
```

**Comment by AThousandShips** [comment]
Yes there's still an inconsistency between the filtering modes in compatibility mode I think, forget if it's been changed

**Comment by billymyers** [comment]
> Both shaders are fixed if you change the palette uniform to
> 
> ```glsl
> uniform sampler2D palette : filter_nearest, repeat_disable;
> ```

Doing this fixes the issue that I had, thank you!

> Yes there's still an inconsistency between the filtering modes in compatibility mode I think, forget if it's been changed

That would be neat to know. I think that having some form of consistency or place where this is documented would be helpful for writing shaders.

**Comment by AThousandShips** [comment]
Oh no this is backwards, the default filtering is now the same as vulkan, so this is because of difference with how 3.x does it, previously the compatibility renderer used the old defaults

**Comment by AThousandShips** [comment]
My bad the issue is not there any longer, the default filtering is linear with mipmaps and repeat enableld.
