### ISSUE TITLE
Chinese characters with DynamicFonts rendered Super slow on Android.

### ISSUE THREAD

**Issue by Geequlim** [godotengine/godot#7428]
**Operating system or device - Godot version:**
OS: Android 4.4.4 and Android 6.0.1
Godot: 2.2 and 2.1.1

**Issue description** (what happened, and what was expected):

Label with chinese characters are too slow to render on android.
Rendering 8 characters may need more than 1 minutes with some large ttf fonts.

This problem doesn't appears on PC(Windows and Linux are tested).
It only appears with dynamic fonts on Android.

**Steps to reproduce:**

Download the bug demo below and export to android then you will see it.

**Link to minimal example project** (optional but very welcome):

https://github.com/Geequlim/depot/raw/master/images/godot/bug_dynamic_font.zip

**Comment by volzhs** [comment]
I guess it takes 1 minute for showing Chinese label for the first time.
It wont' take that long when changing to another scene which contains Chinese label.
I think it's because DynamicFont should read and cache for the first time for ttf.
I will happen with PC but it was so fast to notice the delay.

**Comment by Geequlim** [comment]
The time are taken by dynamic texture creation.

I result of my test:
* Set text of `Label1` with some Chinese characters: **slow**
* Set text of `Label2` with some characters in `Label1` :  **fast**
* Set text of `Label1` with some characters never appeared: **slow**

So I can sure the time is cost by texture creation.

**Comment by volzhs** [comment]
@Geequlim Nice test :)

**Comment by Geequlim** [comment]
It seems caused by freetype related stuff as the stb-truetype implementation works well.

**Comment by reduz** [comment]
How big is the font being used?

**Comment by Geequlim** [comment]
@reduz 1MB ~ 19MB.
Some small ttf font like the one in the bug demo are also too slow.

**Comment by reduz** [comment]
Ah, I mean the size you are rendering to

**Comment by Geequlim** [comment]
@reduz from 16 ~ 33

**Comment by reduz** [comment]
That is weird, can you check the code in case tits doing something strange

**Comment by rotonlin** [comment]
@Geequlim @reduz I found that the default fonts is directly loaded into memory, and it works well. But custom fonts is read form file. FT_Load_Char will call back _ft_stream_io many times when load a char.   And load a Chinese character consume more time than English character on android ......(20 times slower??)

So, after load custom font file into memory,  problem has been resolved.

**Comment by volzhs** [comment]
@rotonlin How did you load custom font into memory?

**Comment by rotonlin** [comment]
@volzhs 
in dynamic_font.cpp 
function: Error DynamicFontAtSize::_load()
custom font will run condition "if (font->font_path!=String())".   
I had optimized the load logic , load the whole custom ttf file into Vector<uint8_t> and store it into font object if needed. 
then replace FT_OPEN_STREAM with FT_OPEN_MEMORY, and FT_Stream buffer.  
Such as logic of condition "else if (font->font_mem)".

**Comment by bojidar-bg** [comment]
I think this should be made into an option on the DynamicFont resource.

**Comment by volzhs** [comment]
@bojidar-bg 
in editor on PC, current state is fast enough I think.
So, I would like to make an option for this at Project Settings, so that exported game can cache font data.

**Comment by volzhs** [comment]
I think this can be closed now.
