### ISSUE TITLE
Starting a Godot process from command line doesn't stop you from typing commands

### ISSUE THREAD

**Issue by lesleyrs** [godotengine/godot#74285]
### Godot version

4.0 stable

### System information

Windows 10, Powershell or cmd

### Issue description

I'm not sure what the behavior is on other OS or Godot 3, but in Godot 4 + Windows 10 after running Godot from command line it lets you keep typing commands. Even though before you type it visually looks like you can't as you have to type ctrl-C to show your current directory.

The problem with this is that you can't use ctrl-C to end the current process that you just started, on top of that you can type gd --headless endlessly and spawn many processes which you can't directly end inside the terminal. You have to either close the terminal or kill the processes in task manager.

### Steps to reproduce

1. Run Godot from command line
2. You now don't need to exit the process before being able to use other commands

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Are you running the command line version?

**Comment by AThousandShips** [comment]
Cannot replicate on Windows 11 under power shell

**Comment by lesleyrs** [comment]
> Are you running the command line version?

What command line version? I just have the windows binary in my path

**Comment by akien-mga** [comment]
This is not a bug.

I'm assuming you run Godot from the command without arguments to start a project directly (`-e --path ...`), so it opens the Project Manager. When you open a project to edit in the Project Manager, it spawns a new process, and the Project Manager itself closes. Since the Project Manager process is killed, Windows Terminal no longer has a handle on it and it hands back control to the user.

As mentioned by @AThousandShips the `_console.exe` versions works this around so it should work as you want it.

**Comment by lesleyrs** [comment]
Ok small problem with that still, if I rename that it stops working. But I want to rename it to be able to easily run it like "gd". The problem does not happen with the other version.

**Comment by AThousandShips** [comment]
The console version calls the main version, can't be avoided

**Comment by lesleyrs** [comment]
> The console version calls the main version, can't be avoided

Alright I added an alias and now it works how I want it to, thanks.

**Comment by lesleyrs** [comment]
> I'm assuming you run Godot from the command without arguments to start a project directly (`-e --path ...`), so it opens the Project Manager. When you open a project to edit in the Project Manager, it spawns a new process, and the Project Manager itself closes. Since the Project Manager process is killed, Windows Terminal no longer has a handle on it and it hands back control to the user. It's the same behavior on Linux and macOS.

My problem here is solved, but just wondering if there is any intention to allow running the godot editor or projects directly without accessing the project manager?

I was running it without commands yes, but inside of a project which means it will launch the game. I didn't actually realise it was launching the project manager at all.
