### ISSUE TITLE
Fullscreen window with [Resizable] == false starts without focus.

### ISSUE THREAD

**Issue by FarbrorMartin** [godotengine/godot#74286]
### Godot version

4.0-stable

### System information

Windows 10, Forward+, Intel HD 620

### Issue description

If you set Window mode = Fullscreen and Resizable = False, the game window starts without focus, meaning that it won't receive keyboard input events.
This happens both in the editor and in a windows binary export.

If Resizable == True the window starts with focus as expected. Also if Window mode is anything other than Fullscreen or Exclusive fullscreen.

I'm not sure what Resizable does when in Fullscreen but this issue had me confused, trying to find other causes for the events not working.
I believe it did not work this way in 3.x.

### Steps to reproduce

Set window mode to Fullscreen or Exclusive fullscreen
Set Resizable to False

Start the game.
It will not detect keyboard input until receiving focus.

### Minimal reproduction project

[MRP_keyboard_focus.zip](https://github.com/godotengine/godot/files/10880977/MRP_keyboard_focus.zip)

**Comment by akien-mga** [comment]
CC @bruvzg

**Comment by strellydev** [comment]
Can confirm this is still happening.
