### ISSUE TITLE
enum after export from 3.5-stable in the column without commas in 4.0-stable gives an error.

### ISSUE THREAD

**Issue by PQINT** [godotengine/godot#74295]
### Godot version

4.0-stable

### System information

Windows 10

### Issue description

on 3.5
it was possible to write those listed in columns without commas

> enum {#stat_machine
> idle
> walk
> }

in 4.0 this syntax produces an error

### Steps to reproduce

try code from the example.

### Minimal reproduction project

> enum {#stat_machine
> idle
> walk
> }

**Comment by AThousandShips** [comment]
Enums require commas in 4.0 it looks like, GDScript has changed a lot between 3.x and 4.0 so not guaranteed to be the same

**Comment by akien-mga** [comment]
This was likely an intentional change indeed. Enum declaration is like dictionary (and they're dictionaries internally).
The fact that it worked without comma in 3.x wasn't necessarily a conscious design decision, it just happened like this, but it's inconsistent with the syntax rules of GDScript everywhere else.

**Comment by vnen** [comment]
AFAICT this is an oversight. It just happens to work like this in 3.x but it was never really intended to. I could not find any references in commits, comments, or documentation that supports this use.

It was always intended to use commas as separators and in 4.0 they are indeed required and will keep being so.

Note that you can also use trailing commas which helps avoiding one extra line change in version control when adding a new item in the enum:
```gdscript
enum {
	idle,
	walk,
}
```
