### ISSUE TITLE
Godot 4 crash when creating GPUParticle node with "Compatibility" project on Macbook M1

### ISSUE THREAD

**Issue by MaxWeiChen** [godotengine/godot#74291]
### Godot version

4.0.stable.mono

### System information

Macbook M1, 2021

### Issue description

Godot 4 crash when creating GPUParticle node with "Compatibility" project on Macbook M1. 
It only "Compatibility" will crash, "Forward+" or "mobile" project will not crash.

### Steps to reproduce

1. Create a new project and select "Compatibility".
2. Create new node "GPUParticles2D" or "GPUParticles3D".
3. Godot will crash.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
@MaxWeiChen Did you find a solution to this problem? If so, please document it here by commenting :slightly_smiling_face:

**Comment by MaxWeiChen** [comment]
No, Sorry for that, I don't find solution, I just find other issue that same like it and it explain better then this one, so I closed this one, hope let dev can focus to follow that.
https://github.com/godotengine/godot/issues/72469
