### ISSUE TITLE
C# script naming is too relaxed and it can generate invalid class names

### ISSUE THREAD

**Issue by MihaMarkic** [godotengine/godot#74307]
### Godot version

v4.0.stable.mono.official [92bee43ad]

### System information

Windows 10

### Issue description

C# script names are too relaxed because class names generated are not valid when used non alphanumeric chars.

### Steps to reproduce

Try creating a C# script named `tuk-a.cs`. Godot editor will consider it valid and create class named `tuk-a_w`. Which is an invalid C# name because it contains - char. One can also use , char and perhaps others invalid.

### Minimal reproduction project

[ScriptNamesProblem.zip](https://github.com/godotengine/godot/files/10883318/ScriptNamesProblem.zip)

Sample project with a C# script named Invalid,Name-Text.cs

**Comment by AThousandShips** [comment]
Is this bug about creating a file named that manually or using CreateScript

**Comment by raulsntos** [comment]
I'm guessing this is about C# templates, the `make_template` method which replaces `_CLASS_` in templates with the name of the class doesn't sanitize the class name other than replacing spaces with underscores.

https://github.com/godotengine/godot/blob/61d2c855114c824f5ca27ded0a1fa71cc7b21134/modules/mono/csharp_script.cpp#L343-L356

Maybe we could use `String::validate_identifier`, not sure if it would have undesired side-effects.

**Comment by MihaMarkic** [comment]
@raulsntos 
> "since C# class names must match the name of the file where they are declared"
That's not mandatory, it's just a general recommendation.

Said that I'd prefer to limit file name to avoid anything non alphanumeric (including spaces) + not starting with digit.

**Comment by raulsntos** [comment]
> That's not mandatory, it's just a general recommendation.

It **is** mandatory; otherwise, Godot won't be able to find your class:

https://github.com/godotengine/godot/blob/61d2c855114c824f5ca27ded0a1fa71cc7b21134/modules/mono/editor/Godot.NET.Sdk/Godot.SourceGenerators/ScriptPathAttributeGenerator.cs#L49-L50

Maybe we haven't been clear enough about this in the documentation though.

---

> Said that I'd prefer to limit file name to avoid anything non alphanumeric (including spaces) + not starting with digit.

Limiting the filename in the _Create Script_ dialog to valid C# identifiers when creating a C# script seems like an acceptable solution to me.

**Comment by MihaMarkic** [comment]
> Limiting the filename in the _Create Script_ dialog to valid C# identifiers when creating a C# script seems like an acceptable solution to me.

Seems like a most elegant solution to me, too.
