### ISSUE TITLE
Drag Gestures in 2D Editor Removed in 4.0

### ISSUE THREAD

**Issue by TheThonos** [godotengine/godot#74309]
### Godot version

4.0.stable

### System information

HP Chromebook, Chrome 108.0.5359.111

### Issue description

In Godot 3, you could hold right click and drag in the 2D editor to move around. This was a feature that I really liked, as it made it easier to work with the 2D editor, but when I switched to Godot 4.0, I found that I was unable to pan around by right clicking and dragging.

### Steps to reproduce

Open any Godot 4.0 project, go to the 2D editor, and try to right click and drag, and it will not work. Do the same on Godot 3, and it will work.

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
See this proposal: https://github.com/godotengine/godot-proposals/issues/3881
