### ISSUE TITLE
Regression using classes inside variables from RC2 to Stable

### ISSUE THREAD

**Issue by Zennyth** [godotengine/godot#74314]
### Godot version

4.0 Stable

### System information

Windows 11

### Issue description

I'm using an utility function called "find_nodes_descendant_is_class(node, class_to_find: GDScript, class_to_stop = null)" that find all nodes that are of specific class from a node.  Here's the code: 
```gdscript
static func find_nodes_descendant_is_class(node, class_to_find: GDScript, class_to_stop = null) -> Array:
    var descendantsInGroup := []
    for child in node.get_children():
        if child is class_to_find:
            descendantsInGroup.append(child)
        
        if class_to_stop != null and child is class_to_stop:
            continue
        
        descendantsInGroup += find_nodes_descendant_is_class(child, class_to_find, class_to_stop)
    
    return descendantsInGroup
```

It worked well in RC2, however since the upper versions this error pops out:
![image](https://user-images.githubusercontent.com/51298462/222793894-107dd09f-40b6-42d5-aaf8-c5e2ff99de37.png)

### Steps to reproduce

Open the project folder and the file named "test.gd" and you'll see the error in the editor.

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/10885046/test.zip)

**Comment by bitsawer** [comment]
Possibly not a bug, see https://github.com/godotengine/godot/pull/73489

In short, instead of using `is` see if `is_instance_of()` works: https://docs.godotengine.org/en/latest/classes/class_@gdscript.html#class-gdscript-method-is-instance-of

**Comment by YuriSizov** [comment]
Indeed, this is not a bug, the new method should be used.
