### ISSUE TITLE
Name given to animations when saving them.

### ISSUE THREAD

**Issue by PullTheStrings** [godotengine/godot#7433]
**Operating system or device - Godot version:**
Windows 8.1 - 2.1.1 Stable

**Issue description** (what happened, and what was expected):
When saving an animation to a file Godot defaults to calling it 'new_animation.tres'.
This happens even if I have already named the animation say 'Jump High' in the animation window.
Having Godot default to saving an animation with the name given to it in the animation window would be nice.

**Comment by Hinsbart** [comment]
Closing this as it was implemented by #7515.
