### ISSUE TITLE
VehicleWheel do not collide with trimesh 

### ISSUE THREAD

**Issue by Desagiato** [godotengine/godot#74345]
### Godot version

3.5.1

### System information

Ubuntu 22.04

### Issue description

VehicleWheel do not collide with trimesh 
![Schermata del 2023-03-04 08-37-11](https://user-images.githubusercontent.com/114653399/222883875-bd4fd01a-9613-45b4-a4d6-09495d9c3b92.png)
![Schermata del 2023-03-04 08-38-53](https://user-images.githubusercontent.com/114653399/222883841-a482f84c-2955-4a9c-a741-7857157be7f7.png)
![Schermata del 2023-03-04 08-38-43](https://user-images.githubusercontent.com/114653399/222883853-7c052217-6081-452a-afa5-2bdee2c87e58.png)

### Steps to reproduce

You could use the project that i have zipped 

### Minimal reproduction project

[Uploading Nuovo Progetto di Gioco.zip…]()

**Comment by Zireael07** [comment]
Project didn't upload. Also, IIRC this is expected and documented?

**Comment by Desagiato** [comment]
I need the mesh to be seen from the inside, or both sides, the trimesh is only used on the staticbody, the others meshes are convex. Any way to make them collide?

**Comment by Desagiato** [comment]
I have inverted normal inside the engine, i have import them correctly

**Comment by Desagiato** [comment]
I solved it by increasing the stiffness of the suspension, even if it still seems like a problem to me

**Comment by Desagiato** [comment]
I've thinked that i have solved that but was not true, someone can help me?

**Comment by Calinou** [comment]
@Desagiato Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.

PS: Since no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
