### ISSUE TITLE
Project Settings General properties position based on engine.cfg

### ISSUE THREAD

**Issue by Keetz** [godotengine/godot#7435]
When a property in project settings is edited for the first time and therefor added to the engine.cfg it will be at the bottom of the property list next time project settings are loaded.

From IRC
> **Akien:** They're listed in the order the engine parses them, and engine.cfg is parsed after the ones that come directly from editor_node.cpp

Steps to reproduce:
- Go to Project Settings -> General Tab
- Choose any property in any section that haven't been edited before, and edit it
- Reload your project and the property is now at the bottom of the list

I think it would be less confusing if the properties had fixed positions, at least the standard properties.

**Comment by bojidar-bg** [comment]
Is this still valid in master (project settings got some revamp...)

**Comment by TwoOfDiamonds** [comment]
Just tested it on master build with main_scene and main_loop_type property and it's not happening anymore

**Comment by akien-mga** [comment]
Nice. Setting milestone to 2.1 then in case someone has a fix to propose for the 2.1 branch.

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.
