### ISSUE TITLE
`get_window()` behaves differently to `get_tree().get_root()`

### ISSUE THREAD

**Issue by simast** [godotengine/godot#74350]
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Windows 11

### Issue description

The docs suggest that `get_window()` is equivalent to `get_tree().get_root()` for the main window. However, I have hit a weird issue where I cannot change to fullscreen mode when I use `get_window()` - see steps to reproduce below.

### Steps to reproduce

I am triggering this from `PopupMenu` (UI):

```gd
get_window().mode = Window.MODE_EXCLUSIVE_FULLSCREEN # Does not work
get_tree().get_root().mode = Window.MODE_EXCLUSIVE_FULLSCREEN # Works
```

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
It says "if the node is in the main window", since you do this from a `PopupMenu` the menu is the window

**Comment by simast** [comment]
Oh I see, did not know the `PopupMenu` registers as separate window, will close this.
