### ISSUE TITLE
Linkbutton doesn't get underlined

### ISSUE THREAD

**Issue by grabthefish** [godotengine/godot#74368]
### Godot version

v4.0.stable.mono.official.92bee43ad

### System information

Windows 11, Vulkan API 1.3.224 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3060 Laptop GPU

### Issue description

LinkButton does not get underlined when when the Underline property is 'Always' or 'On Hover'

https://user-images.githubusercontent.com/12375347/222917320-ae46d590-02e7-4aa9-9e7b-54988ea940e1.mp4

### Steps to reproduce

Put a LinkButton inside an Control and set the Underline property

### Minimal reproduction project

[LinkButtonUnderline.zip](https://github.com/godotengine/godot/files/10889142/LinkButtonUnderline.zip)

**Comment by akien-mga** [comment]
This should be fixed by #74293.
