### ISSUE TITLE
"Turret Madness" won't play 

### ISSUE THREAD

**Issue by deadpahn** [godotengine/godot#74364]
### Godot version

4.0 steam

### System information

Linux mint, gtx1660ti

### Issue description

Says it's missing a file for the bullet. Play screen didn't load. 

### Steps to reproduce

![image](https://user-images.githubusercontent.com/1032331/222915089-7749dbbc-ec1c-44dc-901a-029f176d5b1c.png)

![image](https://user-images.githubusercontent.com/1032331/222915042-8ddb8ea8-03b3-4c19-b923-b8d472709f3e.png)

### Minimal reproduction project

![image](https://user-images.githubusercontent.com/1032331/222915089-7749dbbc-ec1c-44dc-901a-029f176d5b1c.png)

![image](https://user-images.githubusercontent.com/1032331/222915042-8ddb8ea8-03b3-4c19-b923-b8d472709f3e.png)

**Comment by adamscott** [comment]
This doesn't seem to be Godot 4, it's Godot 3.

And this isn't an official Godot demo. Please report the issue to the [asset's repository](https://github.com/cat-person/godot_turret_madness).

I'd close this issue.
