### ISSUE TITLE
Option to disable Tabs in TabContainer

### ISSUE THREAD

**Issue by AshSamir** [godotengine/godot#7436]
_This is an enhancement request to TabContainer._

It would be nice to be able to disable Tabs in a TabContainer like (or at all):

`self.set_tab_disabled(tab_idx)`

or a singal that get fired if you click on the Tab, and only the Tab but not the "area" beneath it.

In case you want to show the Player this tabs exists but you havent yet met the requierements to open it:

- you need to reach lvl 15 to choose super skills
- you need to be a guild member to access the guild options
- you cant open this tab until you finished the tutorial

To name 3 examples. I dont want to remove the tab because i want the player to know its there.
The Tab could be greyed out or something like that and clicking on it would do nothing.

**Comment by RayKoopa** [comment]
What should happen to the currently displayed tab in the TabContainer if that tab gets disabled?

**Comment by AshSamir** [comment]
> If the current tab gets disabled, I stay on it. It's up to the user to change to another one (if this would've been the last enabled tab I would have nowhere to jump to anywhere).
this sounds fine

> I noticed the right / left navigation buttons don't work which appear when not all tabs fit into the tab header bar of TabContainer. They just do nothing and seem disabled all the time. They work for Tabs however.
i had the same issue with 2.1. i i do not forget i will test it again and make an issue out of it (if not already)

**Comment by RayKoopa** [comment]
> i had the same issue with 2.1. i i do not forget i will test it again and make an issue out of it (if not already)

That would be nice so I can commit the fix to that in another pull request.

**Comment by AshSamir** [comment]
ok i tested it with 2.1.1 on windows:
right / left navigation buttons don't work.

i have 4 tabs, only 3 get displayed while the 3rd tab sticks out and is partly under the buttons.
i can only open the 3rd tab if i click on the area left of the buttons. the area beneath and right of them dont work. 

here an image:
[https://s27.postimg.org/g11yrijdv/Unbenannt.png](https://s27.postimg.org/g11yrijdv/Unbenannt.png)

i gues it only checks for the area of the container. maybe this could be the reason the buttons wont work, because they are also outside.

shall i open an new issue for this problem?

**Comment by RayKoopa** [comment]
Yes, please make a separate issue.

**Comment by AshSamir** [comment]
ok i made a new issue for that:
[https://github.com/godotengine/godot/issues/7546](https://github.com/godotengine/godot/issues/7546)

sorry that i closed this issue, i used the wrong button :/
