### ISSUE TITLE
Animation Tree 2d Bug

### ISSUE THREAD

**Issue by lostopkk** [godotengine/godot#74365]
### Godot version

4.0 stable

### System information

Windows 10

### Issue description

hello, I was programming an animation tree for my character and everything was working fine, but I noticed an error and I don't know why it's happening. in all options my character walks normally more if I press the keys down and to the right side at the same time it spins, making the idle animation, and the animation is to stay down and to the right side, so that's it It only happens with this specific position and I don't know why.

https://user-images.githubusercontent.com/50776714/222916257-68cc713d-58f8-4f44-a09a-e60f5f8951b4.mp4

![Godot_v4 0-stable_win64_P4kmqkSb6d](https://user-images.githubusercontent.com/50776714/222916258-dda4ba04-31ad-461e-8fa2-cba5bdebc1f4.png)
![Godot_v4 0-stable_win64_t4LNhMIH6b](https://user-images.githubusercontent.com/50776714/222916259-8b718892-bea1-4f9f-9a52-200dd1d5c61f.png)
![Godot_v4 0-stable_win64_7P7vxozgC5](https://user-images.githubusercontent.com/50776714/222916260-45e9f6ee-6aa9-4a15-82bd-75fbe37a7d4a.png)
![Godot_v4 0-stable_win64_fyAYvf9TcQ](https://user-images.githubusercontent.com/50776714/222916261-e7cbb238-a906-448c-902f-c950f5131a63.png)

### Steps to reproduce

1. Set the animation
2. Set the Programming
3. Set the Animation Tree
4. Problem Happens

### Minimal reproduction project

[jogodabruxinha.zip](https://github.com/godotengine/godot/files/10889644/jogodabruxinha.zip)

**Comment by kleonc** [comment]
> ### Minimal reproduction project
> 
> [project.zip](https://github.com/godotengine/godot/files/10889602/project.zip)

This project is not usable for testing, you've removed the scene dependencies like images etc. Please reupload the project properly (make sure you can unzip and run it yourself).

**Comment by lostopkk** [comment]
> > ### Minimal reproduction project
> > 
> > [project.zip](https://github.com/godotengine/godot/files/10889602/project.zip)
> 
> This project is not usable for testing, you've removed the scene dependencies like images etc. Please reupload the project properly (make sure you can unzip and run it yourself).

i updated the file with the entire project

**Comment by kleonc** [comment]
One of the `AnimationNodeAnimation`s has non-existing animation assigned to it:
![Godot_v4 0-stable_win64_SHfb5vWGyi](https://user-images.githubusercontent.com/9283098/222928442-8b0c2350-f177-432a-b2e7-5e887b993d46.png)

it's referencing non-existing `idle_right_down` animation. No idea how you got it to such state. After changing it to proper animation:
![7cR6GAbqfH](https://user-images.githubusercontent.com/9283098/222928497-dc37031c-debc-45b2-8211-7a88ed89b09f.png)
I could have not reproduce the reported issue. Assuming no bug, hence closing.

For the future: before opening an issue (in case you're not sure you're facing an in-engine bug) please use [other community channels](https://godotengine.org/community/) (Discord, Reddit, etc.) to ensure you're dealing with an actual bug (and not a simple user error).  This is a bugtracker, not a support desk.

**Comment by lostopkk** [comment]
Thanks man!
