### ISSUE TITLE
Doc link points to 3.5 instead of 4.0

### ISSUE THREAD

**Issue by deadpahn** [godotengine/godot#74366]
### Godot version

4.0 steam

### System information

linux mint gtx 1660ti

### Issue description

Build hex is alright I think? 
`#define VERSION_HEX 0x10000 * VERSION_MAJOR + 0x100 * VERSION_MINOR + VERSION_PATCH`

Might be that the steam version was pushed out before updating the version from 3.5 to 4.0? Not sure, anyway since lot's of noobies (myself included) are jumping on the GODOT train, I thought I'd point it out to you.

### Steps to reproduce

HELP>"Online Documentation"

core/version.h line 55 controls the version

VERSION_DOCS_URL seems to be what needs to be updated but that only happens at build I think.

### Minimal reproduction project

HELP>"Online Documentation"

core/version.h line 55 controls the version

VERSION_DOCS_URL seems to be what needs to be updated but that only happens at build I think.

**Comment by akien-mga** [comment]
I can't reproduce it.

Did you see the Steam announcement?
https://store.steampowered.com/news/app/404790/view/3646264794414966903?l=english

4.0 is not in the default branch on Steam, you're probably still using 3.5.1 now, unless you selected the `stable-4.0` beta branch explicitly.
