### ISSUE TITLE
Theme editor : font_size property cannot be removed

### ISSUE THREAD

**Issue by Fifut** [godotengine/godot#74377]
### Godot version

4.0 stable

### System information

Windows 11

### Issue description

On the theme editor, font_size proprety of any items cannot be remove after they are added 

### Steps to reproduce

Create a new project.
Add a new theme
Edit any items
Add font_size proprety
font_size proprety cannot be delete anymore

### Minimal reproduction project

[Font_size bug.zip](https://github.com/godotengine/godot/files/10889359/Font_size.bug.zip)

In this project, font_size proprety cannot be remove.

**Comment by YuriSizov** [comment]
Can you demonstrate what it is that you are trying to do?

**Comment by Fifut** [comment]
![2023-03-04 20_36_08-Paramètres](https://user-images.githubusercontent.com/68921685/222925459-5e8e7394-5d9c-457f-95fc-53b932bbbcf4.png)

Click on remove item do nothing
