### ISSUE TITLE
Background energy multiplier affects fog rendering

### ISSUE THREAD

**Issue by atirut-w** [godotengine/godot#74370]
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Windows 11, Forward+, AMD Radeon RX 6700 XT

### Issue description

When fogs are rendered over the background, they get affected by the background energy multiplier, which is incorrect. If the multiplier is at 0, fogs will be rendered completely black unless they render over a mesh.

![image](https://user-images.githubusercontent.com/25323231/222918213-1b1109c1-8a9e-4a97-a9d8-12aa1cb4d40d.png)
![image](https://user-images.githubusercontent.com/25323231/222918226-4a443cfb-008e-4477-b1ca-8d963859f8af.png)

### Steps to reproduce

1. Set up a scene with a cube, a spotlight, and any kind of fog enabled
2. Change the background energy multiplier

### Minimal reproduction project

[Fog Problem.zip](https://github.com/godotengine/godot/files/10889174/Fog.Problem.zip)

**Comment by RandomCatDude** [comment]
This affects all fog, not just volumetric.
