### ISSUE TITLE
SDFGI sometimes creates static shadows that don't move even after deleting object

### ISSUE THREAD

**Issue by seppoday** [godotengine/godot#74385]
### Godot version

4.0 stable

### System information

Windows 10

### Issue description

Sometimes using SDFGI creates shadows that don't update and stay there even when we delete object. Creating other environment sometimes helps.

**Project with issue:**

![Godot_v4 0-stable_win64_tN7VbAmyxa](https://user-images.githubusercontent.com/62170071/222926122-3fbc0b34-2b51-4476-9a09-86918bf3b3c0.gif)

**Project without issue:**

![Godot_v4 0-stable_win64_OWGXzG6Oto](https://user-images.githubusercontent.com/62170071/222926146-76d714a4-68d0-4123-88dd-d63a2889486e.gif)

In both cases SDFGI is on default.

Disclaimer. Broken project was created on my computer. Not broken project was created on computer of one of discord members. I thought that maybe there is problem with GPU or smth. I run RX 580 that supports Vulkan.

### Steps to reproduce

Hard to tell....

### Minimal reproduction project

[3D_test.zip](https://github.com/godotengine/godot/files/10889557/3D_test.zip)

**Comment by tlobig** [comment]
you can set the GI mode to dynamic and this static shadow goes away - however with no light active there is no shadow
![grafik](https://user-images.githubusercontent.com/10432347/222930329-66f7ae4a-d73a-49d7-ad7b-d6326adcfce2.png)

**Comment by seppoday** [comment]
I dont think thats the problem here. In both projects every mesh is global illumination mode is set to static
Here is example from "working fine" project.
![image](https://user-images.githubusercontent.com/62170071/222947455-ae4167c0-610b-4f42-a525-888da16bc741.png)

**Comment by tlobig** [comment]
But it is the problem. What you see is an artifact of ambient occlusion. I think the system is working as designed.
The artifact exists in your example, too. But you get actual dynamic shadows and the AO artifact from the static GI setting is less visible.

**Comment by seppoday** [comment]
So why when I make 2 exact same projects with exact same nodes, parameters, settings, everything. I get 2 different results? For me it looks like SDFGI works unpredictable.

**Comment by clayjohn** [comment]
tlobig is correct. When an objects GI mode is set to static the engine is free to assume the object won't move. That's what static means. SDFGI does not recalculate lighting when a static object is moved. Objects need to be set to dynamic if you want them to be able to move
