### ISSUE TITLE
Viewport input lag on Linux Wayland (5fps or so behind)

### ISSUE THREAD

**Issue by sourcelocation** [godotengine/godot#74380]
### Godot version

4.0.stable

### System information

Arch Linux KDE Plasma, AMD RX 6650 XT, Vulkan, Wayland

### Issue description

There's a noticeable input lag in Viewport refreshing. For example, when looking around or moving objects you can tell that it's 3-5 frames behind. Even at >60fps. Attached a video showing the issue - you can see how the pivot is behind the cursor by a few frames. 

https://user-images.githubusercontent.com/52459150/222923838-00754652-5be7-4d7c-8865-1ed64466dc7d.mov

### Steps to reproduce

1. Open Viewport on Linux (Wayland specific?)
2. Try moving objects, you should feel the significant delay

### Minimal reproduction project

Happens in every project

**Comment by vvvvvvitor** [comment]
Same happens here on Gnome with Wayland.

**Comment by sourcelocation** [comment]
Tried Xorg, and the delay becomes 1-2 frames behind

**Comment by CODESOLE** [comment]
Same here. At first launch no input lag, after some time input lag shows up. Here is my issue:

[Screencast from 2023-03-05 18-41-34.webm](https://user-images.githubusercontent.com/22984206/222970743-be3daf43-9e01-41e3-9f32-04f814979850.webm)

Steam version of Godot.
GNOME Wayland Session
Archlinux
Nvidia GeForce GTX 920M GPU

**Comment by Calinou** [comment]
> Btw, it just like there is a screen update issue as well. In the last part of the video after I clicked, i have to shake mouse to update the screen. If I click and not move mouse, it' s never update the UI changes. Yesterday i had black tooltips. When i hover some elements, its tooltips shows as black box but today they work correctly, interesting.

See https://github.com/godotengine/godot/issues/74168.
