### ISSUE TITLE
Image.create() makes an invalid / null Image

### ISSUE THREAD

**Issue by kevancress** [godotengine/godot#74384]
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Windows 10 Home. Version 10.0.19044 Build 19044

### Issue description

Creating an image in with Image.create() no longer creates a valid image.

### Steps to reproduce

1. Create a User Interface scene
2. Add a TextureRect with minimum size set to 512 x 512
3. Add the following script to the Texture Rect

```
extends TextureRect

var img : Image
var img_texture : ImageTexture

func _ready():
	img = Image.new()
	img.create(512,512,false,Image.FORMAT_RGBAF)
	img.fill(Color(1.0,0.0,0.0,1.0))
	
	img_texture = ImageTexture.new()
	img_texture.create_from_image(img)
	self.texture = img_texture
	pass # Replace with function body.

func _process(delta):
	var height = img.get_height()
	var width = img.get_width()
	var format = img.get_format()
	var data = img.get_data()	
	breakpoint
	pass
```

4. Run the scene.

In Godot 3.5.1 this would create a red image texture. In Godot 4.0 stable it raises an 'Invalid image' error when creating the image texture. The get_height(), get_width(), and get_format() methods all return 0, get_data() returns an empty PackedByteArray.

### Minimal reproduction project

[Img_test_project.zip](https://github.com/godotengine/godot/files/10889550/Img_test_project.zip)

**Comment by Mickeon** [comment]
`Image.create()` is now a static method that returns a new Image. You need to call it from the class itself, not an instance of Image.

```
var img = Image.create(512, 512, false, Image.FORMAT_RGBAF)
img.fill(Color.RED)
```

**Comment by YuriSizov** [comment]
^ This applies to ImageTexture's method as well.

**Comment by kevancress** [comment]
Ahh okay! Thanks!

**Comment by toger5** [comment]
I have the same issue with bigger images (300x300 works. 500x500 does not work, returns null)

**Comment by Zireael07** [comment]
@toger5 Are you sure it doesn't work or is it just a debugger display issue? The debugger is known to display large structs as null

**Comment by toger5** [comment]
That is good to know. I might still have other issues (porting a project from 3 to 4). But for now I dont see anything rendered...

**Comment by toger5** [comment]
It indeed works and i was facing a debugger issue. Thanks for not letting me give up.
