### ISSUE TITLE
Editor Shortcuts reset after restarting Godot

### ISSUE THREAD

**Issue by prominentdetail** [godotengine/godot#74389]
### Godot version

4.0

### System information

windows 10

### Issue description

If you change only the modifier keys such as alt,shift,ctrl of a shortcut, it won't save these changes when godot is restarted. They will be reset to the previous settings.
It only saves if you change the actual key(not the modifiers).

### Steps to reproduce

Got to the Editor settings and change the modifier keys for a shortcut.. then restart godot and check it again. They will be reset to previous settings.

### Minimal reproduction project

any

**Comment by akien-mga** [comment]
CC @EricEzaM @bruvzg
