### ISSUE TITLE
Some small UI Improvements for Mac OS

### ISSUE THREAD

**Issue by nvanfleet** [godotengine/godot#74383]
### Godot version

4.0 Stable

### System information

Mac OS 13.1

### Issue description

1. If you have multiple Godot projects open none of them are identified in any useful way in the Dock. It'd be nice for their tooltip to be something like "Godot - Project X."

<img width="205" alt="Screenshot 2023-03-04 at 11 43 48 AM" src="https://user-images.githubusercontent.com/1486399/222925771-e2c91cd7-127b-438a-baa9-b815db08c92f.png">

2. Another improvement that makes it easier to switch between windows it to have a "Window" menu that could have all the open projects listed which you can easily select between. Here is an example of how it's done in Safari, most of the options are specific to Safari but you can see at the bottom I have two windows open (one for this issue I'm creating and the other for a random google search).

<img width="341" alt="Screenshot 2023-03-04 at 11 48 18 AM" src="https://user-images.githubusercontent.com/1486399/222925903-73c585bd-756f-4eb2-8d89-853f91b9d677.png">

### Steps to reproduce

Run Godot 4 in Mac

### Minimal reproduction project

Anything

**Comment by AThousandShips** [comment]
Please go [here](https://github.com/godotengine/godot-proposals/issues) for proposals, this is for reporting bugs

**Comment by nvanfleet** [comment]
Okay sorry about that
