### ISSUE TITLE
Typed Arrays don't seem to work correctly with MultiplayerSynchronizer

### ISSUE THREAD

**Issue by MrBlockers** [godotengine/godot#74391]
### Godot version

4.0 stable

### System information

Windows 10, NVidia RTX 3080, Vulkan

### Issue description

While working on a project where I wanted to sync an Array of Vector2i for setting up a tilemap, I discovered typed arrays don't seem to play nice with MultiplayerSynchronizer, neither Spawn or Sync mode. In particular, I am testing when a scene with a child synchronizer (syncing the exported array) is replicated by a MultiplayerSpawner. The workaround I found there was to use an Array instead of Array[Vector2i].

Another issue in this same reproduction project is that the automatically generated names for instanced scenes can cause path errors and prevent the scene from replicating to clients. I think this is related to https://github.com/godotengine/godot/issues/68508, maybe a configuration issue but I am running into this in my other project as well. If its not a config issue & different enough I can create a separate issue to capture it.

### Steps to reproduce

1. Run 2 instances of the project
2. Click Host on one
3. Click Connect on the other
4. Click "Spawn Test Label" on host, which will instantiate a simple label scene 

Note that it fails to correctly create the scene on clients when the 'array' property of spawn_label.gd is a typed array, but works fine when typed as a standard Array

Bonus issue:
5. Comment control.gd:43
6. Try steps 1-4 above and see error generated in console related to get_node

### Minimal reproduction project

[SyncTypedArray.zip](https://github.com/godotengine/godot/files/10889685/SyncTypedArray.zip)

**Comment by PaulMag** [comment]
I have the same problem. I have an Array that refused to synchronize with MultiplayerSynchronizer, and I _know_ I had it working earlier. Thought I was going insane. After reading your issue I tried changing its type from Array[int] to Array. And then it worked perfectly.

At some point I added static typing to all my variables to make my code less error prone, and that apparently broke the synchronizer. Ironic. :)

**Comment by dalexeev** [comment]
* Please test if #78219 fixes this.

**Comment by MrBlockers** [comment]
Finally got a chance to check this out, this does appear to be fixed by #78219!

**Comment by machisuji** [comment]
@akien-mga I'm on 4.2.2.stable and still have this very behaviour. I have a node with a MultiplayerSynchronizer and a bunch of arrays.

If I use typed arrays they do not get synchronized. If I remove the type, they do.
In the following example I removed the type from the `player_name` array which then made the synchronization work.

![image](https://github.com/godotengine/godot/assets/158871/b702a31f-6ea6-4216-8469-102216549d3c)
