### ISSUE TITLE
!create_func is true error on osx

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#7441]
Haven't tested this on other platforms yet but now that we have a working mac os x build this error comes up when starting godot:

ERROR: create: Condition ' !create_func ' is true. returned: 0
   At: core/os/mutex.cpp:39.

Need to investigate the cause further and resolve, maybe related to visual_server_wrap_mt being removed for the time being?

Also I'm getting this error in the logs when closing godot:
ERROR: free_static: Condition ' !MemoryPoolStatic::get_singleton() ' is true.
   At: core/os/memory.cpp:58.

**Comment by reduz** [comment]
it's possible memory is being with malloc/memnew used before Mutex class was initialized in the platform, feel free to check what it might be.

**Comment by poke1024** [comment]
This no longer seems to happen.
