### ISSUE TITLE
gridmap spamming thousands of errors

### ISSUE THREAD

**Issue by yankscally** [godotengine/godot#74429]
### Godot version

4 stable

### System information

Windows 10

### Issue description

getting this error hundreds of times if I just paint anywhere for 1 second with Gridmap
`modules/navigation/godot_navigation_server.cpp:760 - Condition ""Attempted to free a NavigationServer RID that did not exist (or was already freed)."" is true.`

![image](https://user-images.githubusercontent.com/27631913/222960713-91dc3d96-73bf-443b-984f-51ae551a0b00.png)

### Steps to reproduce

It happened (I think) after I cleared a baked navigation mesh, but not sure.

### Minimal reproduction project

n/a

**Comment by akien-mga** [comment]
Aside from fixing what causes this error, the way the error is emitted should be fixed:
```
ERR_FAIL_COND("Attempted to free a NavigationServer RID that did not exist (or was already freed).");
```
`ERR_FAIL_COND` requires a condition. This should just be `ERR_PRINT`.

**Comment by smix8** [comment]
This needs an MRP cause this error is not reproducible for me with GridMap.
I can edit cells with baked navigation mesh all day without a single error like this.
