### ISSUE TITLE
Transform properties does not replicate on Children made of Packed Scene 

### ISSUE THREAD

**Issue by THEN3LLI** [godotengine/godot#74430]
### Godot version

4.0 official

### System information

Win 11

### Issue description

Hi everyone.
I don't know if it's intended, but when I try to Transfom, either modifying position or using Translate(),
everything moves but the ActorBase (and childrens) are not. 

![Screenshot 2023-03-05 132955](https://user-images.githubusercontent.com/29429638/222960654-dd26f80d-d2da-4d2f-af96-9f67d718b588.png)

**To clarify what moves:**
_Warrior, Sprite2D, AudioStreamPlayer_
**What does not moves:**
_Actor_Base, Sprite2D_

Edit 1:
Find out that if the Child scene is a Scene that has Transform properties, it works. Simple "**Node**" does not give permission to move childrens. But if I use "**Node2D**", that has Transform properties, it works.
Looks like there was an Issue on 2018:
[https://github.com/godotengine/godot/issues/17384](url)
### Steps to reproduce

Create a scene named Main, make it moves. Even Translate(Vector2(300,300)) is enough.
Create another scene named Child, add a Sprite2D so you can visually see what's going on. Save.
Add to Main as instanced scene the Child scene.
Running the code will result in the Main scene moving, and the Child scene standing still.

### Minimal reproduction project

[New Game Project.zip](https://github.com/godotengine/godot/files/10891900/New.Game.Project.zip)

**Comment by AThousandShips** [comment]
Please attach a MRP to make this easier to investigate

**Comment by AThousandShips** [comment]
Yeah I don't think transform is carried through `Node`, you need to have a chain of `Node2D`, this is expected.

**Comment by THEN3LLI** [comment]
> Yeah I don't think transform is carried through `Node`, you need to have a chain of `Node2D`, this is expected.

So, if I got it clearly, transform properties is not carried trought Children of Children, but only on direct Children of the Main Node, and only when that Child is actually a movable node.
That's why Sprite node doesn't copy the root transform.

**Comment by AThousandShips** [comment]
If a `Node2D` is the child of a `Node` it won't get transform from the parent of the parent, and so on, it will only modify the transform of the parent
