### ISSUE TITLE
DirectionalLight3D shadows are broken with Orthogonal Camera3D

### ISSUE THREAD

**Issue by fossegutten** [godotengine/godot#74431]
### Godot version

4.0 final

### System information

Windows 11

### Issue description

![image](https://user-images.githubusercontent.com/15088582/222960884-f1331300-0b40-4a8f-a532-e2aeb88ce199.png)

### Steps to reproduce

Create a DirectionalLight3D node and enable shadows. Create a Camera3D with Orthogonal projection.

### Minimal reproduction project

Not really needed, this is so simple to recreate

**Comment by myaaaaaaaaa** [comment]
This is caused by near/far plane calculations:

![far](https://user-images.githubusercontent.com/103326468/224074180-9eb50042-496b-4401-aee6-48f956912566.gif)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/58332.
