### ISSUE TITLE
Android: `InputEventMouseMotion` not emitted after double click.

### ISSUE THREAD

**Issue by HolonProduction** [godotengine/godot#74436]
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Android 13, Mobile Renderer

### Issue description

When starting to move your finger after a touch that was a double click `InputEventMouseMotion` is not emitted.

### Steps to reproduce

- run the MRP with remote debug
- touch on the display of your phone and start moving your finger
- the console should print `"moving"`
- now touch two times and start moving your finger
- the console should print `"moving"` but it doesn't

### Minimal reproduction project

[mouse_motion_android.zip](https://github.com/godotengine/godot/files/10891907/mouse_motion_android.zip)

**Comment by akien-mga** [comment]
CC @m4gr3d

**Comment by AlexandrKrivosheev** [comment]
Might be same as https://github.com/godotengine/godot/issues/74358

**Comment by m4gr3d** [comment]
Duplicate of https://github.com/godotengine/godot/issues/76587
