### ISSUE TITLE
My game is not rendering properly on some computers.

### ISSUE THREAD

**Issue by Eneskp3441** [godotengine/godot#74440]
### Godot version

4.0 stable

### System information

Windows 11, Vulkan, rx570, amd ryzen 5 2600

### Issue description

I'm exporting my game in Godot and sending it to my friends. It works fine for me, but one of my friends who has an RX570 graphics card is not able to render the 3D part of the game properly.

![image](https://user-images.githubusercontent.com/100702845/222970108-d7644015-76d7-47b2-9970-cc39c464af02.png)

**On my friend's computer:**

https://user-images.githubusercontent.com/100702845/223165588-143bffb1-04d3-4815-887f-405ecc6492fe.mp4

**on my computer:**

https://user-images.githubusercontent.com/100702845/223165168-0f4e2676-3da2-45cd-9609-b7e43d3f3d6b.mp4

There is the same issue in all 3D scenes.
For steam multiplayer, I use the editor that uses steam templates.

I didn't come across any error code on the computer where the problem occurred.

### Steps to reproduce

I don't think the problem is caused by my project. Same issue with any 3D export
I cannot provide you with a code example as there is an issue rendering anything in 3D.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Please provide more detailed information about the system of the computer where the issue happens, the system information on your computer isn't helpful if the error does not happen there.

**Comment by Eneskp3441** [comment]
> Oh yes, I'm sorry, I've updated it now, you can take a look.

**Comment by clayjohn** [comment]
There isn't enough information here for us to help you. While the image does look janky, we don't know what it is supposed to look like, so visually we can't tell what is broken. 

At minimum we need a description of what a working project is like and what exactly is broken. We also need to know what errors are being reported on the broken system. Finally we need an MRP so that interested contributors can try to reproduce and fix the bug. 

Without the above, no one is going to help you

**Comment by Eneskp3441** [comment]
> There isn't enough information here for us to help you. While the image does look janky, we don't know what it is supposed to look like, so visually we can't tell what is broken.
> 
> At minimum we need a description of what a working project is like and what exactly is broken. We also need to know what errors are being reported on the broken system. Finally we need an MRP so that interested contributors can try to reproduce and fix the bug.
> 
> Without the above, no one is going to help you

I added as much information as I could. Is it sufficient?

**Comment by dame-ng** [comment]
@Eneskp3441 Make sure your friend has their graphics card drivers updated.

**Comment by Eneskp3441** [comment]
> 

My friend checked and confirmed that the graphics card drivers are up to date

**Comment by Eneskp3441** [comment]
> @Eneskp3441 Make sure your friend has their graphics card drivers updated.

My friend checked and confirmed that the graphics card drivers are up to date

**Comment by Calinou** [comment]
What Environment features do you have enabled in the project? The artifacts look like something caused by SSAO or SSIL. Try disabling it then exporting the project again.

**Comment by Eneskp3441** [comment]
> What Environment features do you have enabled in the project? The artifacts look like something caused by SSAO or SSIL. Try disabling it then exporting the project again.

I have turned off both options, but there is no difference, the result is the same.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/61415.

You can work around this by disabing MSAA and using TAA or FXAA instead.
