### ISSUE TITLE
C# API for SurfaceTool `set_smooth_group` has incorrect type `uint`: should be `int`

### ISSUE THREAD

**Issue by 31** [godotengine/godot#74452]
### Godot version

v4.0.stable.mono.official [92bee43ad]

### System information

Windows 10 x64

### Issue description

https://docs.godotengine.org/en/stable/classes/class_surfacetool.html#class-surfacetool-method-set-smooth-group says to use `-1` to tell SurfaceTool to generate flat normals. The C# API uses the wrong type, so you can't pass `-1`.

Workaround: use `s.SetSmoothGroup(uint.MaxValue)`, which has the same raw binary representation as `(int)-1`.

### Steps to reproduce

1. Write `new SurfaceTool().SetSmoothGroup(-1);`
2. Build
3. See `...: Argument 1: cannot convert from 'int' to 'uint'`

### Minimal reproduction project

N/A

**Comment by raulsntos** [comment]
The C# is generated from ClassDB which defines  this method as follows:

https://github.com/godotengine/godot/blob/5dccc940e73d39a1ac4f3d64ccc92373e6609add/scene/resources/surface_tool.h#L192

As you can see, the method uses `uint` in Core, so the C# API is correct. Changing it now would break compatibility.

I think your workaround is good, alternatively you can also cast:

```csharp
uint group = unchecked((uint)-1);
SetSmoothGroup(group);
```

**Comment by 31** [comment]
Strange... how does https://docs.godotengine.org/en/stable/classes/class_surfacetool.html#class-surfacetool-method-set-smooth-group show `int` then? I thought those were based on the ClassDB.

(I suppose this also implies GDScript will automatically do an unchecked conversion. Which AFAIK is fine, just not something I'd realized yet.)

**Comment by AThousandShips** [comment]
GDScript doesn't have an `uint`

**Comment by raulsntos** [comment]
GDScript doesn't support unsigned types, so they use `int` for everything.

The documentation is generated from ClassDB but it probably only checks the `Variant.Type` which would be `Variant::INT` in this case. C# also checks the type metadata (which contains if the type is 32-bit or 64-bit and if it's signed or unsigned).

**Comment by 31** [comment]
Ah... the danger of using a GDScript API reference and docs based on that reference rather than the ClassDB itself being documented. 😄

Thanks for the clarifications, and for keeping compatibility so I don't have to worry about this switching mid-4.0.

**Comment by clayjohn** [comment]
We should document the fact that it is actually checking UINT_MAX internally, as that knowledge will be needed when calling it from any language that supports units and has strong typing

**Comment by AlexKostas** [comment]
Ok for anyone who might be reading this I am starting work on this issue. Just a note to avoid duplicating work :)

**Comment by RedworkDE** [comment]
@taehong99 The class ref for this is in `docs/classes/SurfaceTool.xml`. Just find the related bits for this issue and insert appropriate notes and maybe correct any C# code examples that probably don't exist. See the docs on how to build the docs to preview your changes.
