### ISSUE TITLE
Signal receiver method picker; built-in scripts don't update until scene is reopened

### ISSUE THREAD

**Issue by Jimmio92** [godotengine/godot#74453]
### Godot version

4.0

### System information

Win 10

### Issue description

When you press Pick, it only shows newly written script methods for scripts that are saved separately. Scripts that are built-in to the scene don't get updated in the picker until the scene is closed and reopened in editor.

### Steps to reproduce

Add a method to a built-in script then attempt to connect a signal to it in editor. Fail.

Add a method to a saved script then attempt to connect a signal to it in editor. Success!

### Minimal reproduction project

Load the project
Uncomment both the Saved and Built-In version of `func button()` (Ctrl+K shortcut)
Attempt to connect the Button to both and notice only in Saved does the signal receiver method picker see changes.

[min_built_in_pick.zip](https://github.com/godotengine/godot/files/10893008/min_built_in_pick.zip)

**Comment by KoBeWi** [comment]
Probably needs similar fix to #57807
