### ISSUE TITLE
[Godot 4.0 Android Editor] crashing after creating a new AudioStreamMicrophone

### ISSUE THREAD

**Issue by ArkellArt** [godotengine/godot#74455]
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Android 11, MediaTek Helio P35 (32bit), PowerVR Rogue GE8320, also tested on: Android 10, Snapdragon 636, Adreno 506,

### Issue description

Same issue of Godot 3

When trying to use the microphone input in an AudioStreamPlayer node on the godot android editor, unexpectedly crashes after a few seconds regardless of whether it is a new project or not. 
If the initial scene has an AudioStreamPlayer node configured with an AudioStreamMicrophone it will continuously close, not allowing to start.

### Steps to reproduce

1: Create a new project or use a existent one. 
2: Press "Project" and "Project Settings"
3: Check the "Advanced Settings" option on the top right corner
4: Go to "Audio" and in "Driver" activate "Enable Input"
5: After restarting, create an AudioStreamPlayer Node
6: On Stream, add a new AudioStreamMicrophone
7: Activate "Playing"

Wait a few seconds until it crashes

### Minimal reproduction project

Use a new project

**Comment by m4gr3d** [comment]
Fixed by https://github.com/godotengine/godot/pull/77686
