### ISSUE TITLE
Depth texture in CanvasItem shaders breaks code generation (Forward+)

### ISSUE THREAD

**Issue by cuckydev** [godotengine/godot#74464]
### Godot version

4.0.stable

### System information

Windows 10, NVIDIA RTX 2060 (Driver 30.0.14.7284), Vulkan 1.2.175 Forward+

### Issue description

Trying to use depth textures in a canvas item as is documented (using `hint_depth_texture`) causes the shader compiler to throw various errors.

Editor reports:
`servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp:2077 - Condition "!canvas_singleton->shader.canvas_shader.version_is_valid(version)" is true.`

Debugger reports many issues related to code compilation. Unfortunately, hovering over one of the errors causes Godot to accumulate many gigabytes of memory and crash the system.

### Steps to reproduce

Place a CanvasLayer and a ColorRect with a shader, as is typical for post-processing.
Define a depth texture in the shader using `hint_depth_texture` to trigger the issue.

### Minimal reproduction project

[DepthIssue.zip](https://github.com/godotengine/godot/files/10894111/DepthIssue.zip)

**Comment by clayjohn** [comment]
The depth texture is not available in canvas item shaders, it is only available in spatial shaders. 

We have added an in-editor warning that is more instructive in master. https://github.com/godotengine/godot/pull/74320 it will be available in 4.0.1 and 4.1
