### ISSUE TITLE
Show files in the FileSystem Tree View  

### ISSUE THREAD

**Issue by jesperkondrup** [godotengine/godot#7446]
We are several developers at my company who have been working with both Unity, Cocos Creator and Godot. In Unity and Cocos Creator it's possible to view files in the hierarchy view but in the Godot engine this is not possible. In our opinion it makes it a lot easier to to work in a game editor when you can see all your files in the tree view. 

We are currently working on our third game in the Godot engine and we are still not comfortable using the FileSystem view in Godot. This indicates to us that the current way of showing the tree view might not be optimal, at least not for all developers.

**Idea for improvement: Make a toggle button for displaying files in the FileSystem view**    

This issue shows a mockup:
#4570

**Comment by RayKoopa** [comment]
Yeah, I recommended something similar here (together with a lot of other improvements): https://github.com/godotengine/godot/issues/4570

**Comment by jesperkondrup** [comment]
Yeah I saw it. I also referenced #4570 in my post :)

**Comment by RayKoopa** [comment]
Oh, right... I should buy some glasses :D

**Comment by reduz** [comment]
@jesperkondrup I don't think you can view files in the hierarchy view in Unity, the way Godot works is very similar to it (except vertical by default).

**Comment by reduz** [comment]
Nevermind, you mean the single column mode.

**Comment by Noshyaar** [comment]
Still reproducible/relevant in 3.1 master 48890b1 : no option for that yet

**Comment by jesperkondrup** [comment]
Still very much relevant in godot 3.1 - the current file system view could definitely use some work.

**Comment by Hammster** [comment]
I agree i just switched from Unity to Godot. For learning purposes I am rewriting one of my projects and going through my assets is really a chore in Godot.

**Comment by jesperkondrup** [comment]
Created a new and more precise issue here #20444
