### ISSUE TITLE
Remove a folder in the FileSystem by pressing the Delete button

### ISSUE THREAD

**Issue by jesperkondrup** [godotengine/godot#7447]
I have often selected a folder in the FileSystem view and pressed the delete button, resulting in a node that was selected in the Scene view was deleted instead. 

**Solution**
When selecting a folder in the FileSystem, the Filesystem window should "take focus" and it should be possible to press the delete button to remove a folder. A warning message would be highly appreciated here. Like "Are you sure you want to remove this folder, you cannot undo this action."

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by jesperkondrup** [comment]
This is no longer relevant in 3.1
