### ISSUE TITLE
TextEdit: method set_line ( int line, String new_text ) not update changes in TextEdit text

### ISSUE THREAD

**Issue by davidtjesse** [godotengine/godot#74483]
### Godot version

4.0.stable

### System information

Ubuntu 22.10, 64 bits

### Issue description

The title already explains everything.
I can work around the problem by clicking in the TextEdit  or calling the  call_deferred("grab_focus") method.

### Steps to reproduce

Add a TextEdit to the scene and make any changes to any line using set_line.

### Minimal reproduction project

A new Godot project with an TextEdit.

**Comment by AThousandShips** [comment]
The method does not queue a redraw, probably by design, you need to call `queue_redraw()`

**Comment by davidtjesse** [comment]
That's right. I forgot about the changes in GDScript and I tried to use update() and it was strange because it didn't accept it. Sorry.
