### ISSUE TITLE
Remove Warning message when creating a new track in Animation window

### ISSUE THREAD

**Issue by jesperkondrup** [godotengine/godot#7448]
In my opinion there's no reason why you would give a warning message every time you want to create a new track in your animation. As a graphics guy doing a lot of animations this warning message becomes really annoying. It's like asking in Photoshop "if you really want to create a new layer." 

If you accidentally hit the wrong key button when setting a keyframe, then you can easily remove the track from the animation, so it's hard to see the need for the warning message.

**Comment by RayKoopa** [comment]
Just to be sure: You mean messages like "Create NEW track for property 'funny_balls' and insert key?"?

**Comment by jesperkondrup** [comment]
@RayKoopa - Thanks! We didn't know about this option, it works perfectly :)

**Comment by akien-mga** [comment]
The question is, does this setting make sense or should it just default to no warning?

**Comment by jesperkondrup** [comment]
In my opinion there shouldn't be a warning. As I stated earlier It's almost like asking in Photoshop "if you really want to create a new layer." And that would drive any artist insane in minutes.

**Comment by bojidar-bg** [comment]
I agree that no warnings should be produced for this one (and I don't think we should keep the settings)

**Comment by reduz** [comment]
I don't think the warning is wrong or counterproductive (it's only shown
once) and i found it often avoids mistakes for first time users. I think it
would probably be best to add a button like "disable this warning" you can
click once you know what goes on.

**Comment by RayKoopa** [comment]
I will make my own editor. Without warnings but hookers and blackjack
😆

**Comment by jesperkondrup** [comment]
@reduz - That's not a bad idea :)
