### ISSUE TITLE
GODOT 4 The debugger does not open and does not transfer to the script in which the error occurred as before.

### ISSUE THREAD

**Issue by PQINT** [godotengine/godot#74480]
### Godot version

4.0-stable

### System information

Windows 10

### Issue description

The debugger, after importing a project from 3.5 to 4.0, when stopped in case of an error, will not go to the place of the problem in the code in the desired script and will not show the place where the error occurs, instead you need to guess in which script what happened and reject it exactly it should be active in script editor window, and only in this case, when clicking on an error, the editor will lead to the desired line that needs to be corrected, but in large projects there are a huge number of scripts, and to search, you need to sort through each one until you find the one in which the error occurred after import. 

### Steps to reproduce

Import a project with a lot of scripts in 4.0 and try to fix the bugs.

### Minimal reproduction project

Unfortunately, I can't provide you with a small project, you need a large project in which you need to fix a lot of errors related to the change in syntax between 3.5 and 4.0 just to understand the essence of the problem.

**Comment by naturally-intelligent** [comment]
That's usually from a broken dependency: a base class is broken, or a preload is broken.

Unfortunately upgrading from 3 to 4 can be a lot of work

**Comment by Calinou** [comment]
Closing per @naturally-intelligent's comment. This needs proper [GDScript stack traces](https://github.com/godotengine/godot-proposals/issues/963) to be implemented to be resolved.
