### ISSUE TITLE
Highlight Assets in the FileSystem when they are selected in the inspector

### ISSUE THREAD

**Issue by jesperkondrup** [godotengine/godot#7449]
When selecting an asset (this could be an image file) in the inspector it should navigate to the file in the FileSystem view and give it a quick highlight. This is a functionality I really like in unity and I think it provides a great way of navigating your project and finding files easy and fast. 

Example image:
![godotassetselection](https://cloud.githubusercontent.com/assets/24936603/21719700/68dbbca0-d41f-11e6-9592-397210c484d1.jpg)

**Comment by RayKoopa** [comment]
I guess this should be an option too. I wouldn't like my file system to navigate around. Maybe something like a button to keep it in sync with edited properties in the inspector.

**Comment by bojidar-bg** [comment]
No, not navigate, just highlight (maybe highlight the subfolder instead of navigating the the file inside it)

**Comment by RayKoopa** [comment]
Okay, I'd like that more. Maybe plus a context menu option to navigate to the resource?

**Comment by bojidar-bg** [comment]
@RayKoopa not sure about the usefulness of that one, but, why not?

**Comment by jesperkondrup** [comment]
After looking into this again, I can see that the reason it works in Unity is because they have separated the image loader into two parts. You can click the image to navigate to the location in the File system or you can press the "Select" button beneath it to bring up the load menu. 

**Suggestion:**
What we will actually suggest instead, would be to make another item in the Context menu. It could be named "Show in FileSystem". So when you click this item, it will navigate to the location of the asset in the FileSystem and highlight it.

Example from Unity:
![godotunityhighlightasset](https://cloud.githubusercontent.com/assets/24936603/21923022/0efc3d92-d972-11e6-846f-5508cc3fc30d.jpg)

**Comment by RayKoopa** [comment]
So basically only the context menu suggestion I commented before? I think I can do that (for a first) =3

**Comment by jesperkondrup** [comment]
@RayKoopa - Hehe exactly. When I read your comment I was not sure what was meant by the context menu but you are 100 % correct. :)

**Comment by RayKoopa** [comment]
@bojidar-bg Should I edit the "issue" to reflect the context menu enhancement only?

**Comment by bojidar-bg** [comment]
Well, I have no problems with editing it, though it is useless if it is possible to implement the feature in < 2 hours ;)

**Comment by RayKoopa** [comment]
You know I might need more :'3

**Comment by reduz** [comment]
Show in filesystem item makes a lot of sense
