### ISSUE TITLE
[Godot 4 stable] Multiplayer not connect but no errors

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#74500]
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Debian 11

### Issue description

I have a client-server  project
My test case is
- server start
- client start and keep it open
- restart server

The connection is successful when I connect to the server for the first time
Then, when I restart the server, In client is trigged the signal `peer_disconnected` from `multiplayer` and `peer_disconnected` from `ENetMultiplayerPeer`

To reconnect it I follow these steps:
- disconnect `ENetMultiplayerPeer` signals
- disconnect `multiplayer` signals
- call `connection_castle_server` again

My `connection_castle_server` is:
```

func connection_castle_server() -> void:
    Log.Print( "{0}:{1}".format([Global.server_ip ,str(Network.CASTLE_SERVER_PORT_NUMBER) ]))
    if Global.network == null:
        Global.network = ENetMultiplayerPeer.new()
    connection_network_signals()
    connection_network_api_signals()
    multiplayer.multiplayer_peer.close()
    var create_client_result =  Global.network.create_client(Global.server_ip, Network.CASTLE_SERVER_PORT_NUMBER)
    match create_client_result:
        OK:
            Log.Print("Connected to the castle server")
        ERR_ALREADY_IN_USE:
            Log.Print("Error connecting to the server: Already in use")
        ERR_CANT_CREATE:
            Log.Print("Error connecting to the server: Cant create")
    multiplayer.multiplayer_peer = Global.network
```

From console I log each steps and I have no errors- It start from `peer_disconnected` of `multiplayer` :

```
1678121040.075450 D: res://auto_load/castle_server.gd (125) [_on_peer_disconnected] CastleServer disconnected 1
1678121040.075630 W: res://auto_load/castle_server.gd (120) [_on_multiplayer_api_peer_disconnected] multiplayer api CastleServer disconnected 1
1678121040.075709 I: res://auto_load/castle_server.gd (137) [reconnect_to_castle_server] 
1678121040.075771 I: res://auto_load/castle_server.gd (149) [disconnect_network_signals] 
1678121040.075849 I: res://auto_load/castle_server.gd (157) [disconnect_network_api_signals] 
1678121040.075936 I: res://auto_load/castle_server.gd (41) [connection_castle_server] 127.0.0.1:1908
1678121040.076003 I: res://auto_load/castle_server.gd (59) [connection_network_signals] 
1678121040.076081 I: res://auto_load/castle_server.gd (66) [connection_network_signals] Connection result 0
1678121040.076157 I: res://auto_load/castle_server.gd (73) [connection_network_signals] Connection result 0
1678121040.076226 I: res://auto_load/castle_server.gd (77) [connection_network_api_signals] 
1678121040.076305 I: res://auto_load/castle_server.gd (84) [connection_network_api_signals] Connection result 0
1678121040.076383 I: res://auto_load/castle_server.gd (91) [connection_network_api_signals] Connection result 0
1678121040.076461 I: res://auto_load/castle_server.gd (98) [connection_network_api_signals] Connection result 0
1678121040.076539 I: res://auto_load/castle_server.gd (105) [connection_network_api_signals] Connection result 0
1678121040.076681 I: res://auto_load/castle_server.gd (50) [connection_castle_server] Connected to the castle server
1678121040.076768 I: res://auto_load/castle_server.gd (145) [test_reconnection]
```

The last one `test_connection` is a rpc whit I found out there is no connection.
So the return `OK` is not  ok I guess :) Unless I missed something in the way it have to be done I think is a bug.

Thanks

### Steps to reproduce

See before

### Minimal reproduction project

NA. It will take some time, if its necessary, to make a MRP - are in effect two projects :)
Tell me if I have to do it.

**Comment by Calinou** [comment]
@git2013vb Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.

PS: Since no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
