### ISSUE TITLE
Pasting text doesn't work on Godot Mobile Version

### ISSUE THREAD

**Issue by muhtadshah** [godotengine/godot#74504]
### Godot version

4.0 (latest mobile version)

### System information

Android 13

### Issue description

This bug is a little frustrating. Whenever I've to paste a script in Godot (Mobile Version)... It doesn't get pasted. Instead, it pastes half of the text and doesn't paste what I exactly copied. I want it to work properly. Whenever I paste something in a script, it should get pasted. Here's a video for the bug:

https://user-images.githubusercontent.com/80309124/223189445-0073228b-e31b-4cdd-9d0d-3e468f0d0570.mp4

In this video. I'm first showing what exactly is the code in the Notes App. Then I go to Godot and paste the same text but it doesn't paste the exact text.

### Steps to reproduce

I was unable to figure out what really is going on with it (as it's a Mobile Version)...

### Minimal reproduction project

As I told you before :( I've no clue how to solve it.

**Comment by m4gr3d** [comment]
Duplicate of https://github.com/godotengine/godot/issues/70751

The root cause is the same for both issues.
