### ISSUE TITLE
Android Export

### ISSUE THREAD

**Issue by Desagiato** [godotengine/godot#74507]
### Godot version

3.5.1

### System information

Ubuntu 22.04

### Issue description

I'm trying to export the project to android, but when i try to install it doesn't work, i already signed the apk and checked if it was signed correctly with apksigner verify, what could be the error? during the export it tells me that everything is correct

### Steps to reproduce

simple empty project

### Minimal reproduction project

simply empty project

**Comment by Desagiato** [comment]
Task :preBuild UP-TO-DATE
> Task :preDebugBuild UP-TO-DATE
> Task :mergeDebugNativeDebugMetadata NO-SOURCE
> Task :compileDebugAidl NO-SOURCE
> Task :compileDebugRenderscript NO-SOURCE
> Task :generateDebugBuildConfig UP-TO-DATE
> Task :checkDebugAarMetadata UP-TO-DATE
> Task :generateDebugResValues UP-TO-DATE
> Task :generateDebugResources UP-TO-DATE
> Task :mergeDebugResources UP-TO-DATE
> Task :createDebugCompatibleScreenManifests UP-TO-DATE
> Task :extractDeepLinksDebug UP-TO-DATE
> Task :processDebugMainManifest UP-TO-DATE
> Task :processDebugManifest UP-TO-DATE
> Task :processDebugManifestForPackage UP-TO-DATE
> Task :processDebugResources UP-TO-DATE
> Task :compileDebugKotlin UP-TO-DATE
> Task :javaPreCompileDebug UP-TO-DATE
> Task :compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: /home/desa/Android/Sdk/platforms/android-32/core-for-system-modules.jar.
         > jlink executable /usr/lib/jvm/java-11-openjdk-amd64/bin/jlink does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 719ms
13 actionable tasks: 1 executed, 12 up-to-date

**Comment by akien-mga** [comment]
This GitHub repository is for bug reports, with clear reproduction steps. What you're asking for is user support, as there must be a setup issue on your end, as it works for most users.

Please use other community platforms for support on this: godotengine.org/community/

A hint though while we're here:
```
> jlink executable /usr/lib/jvm/java-11-openjdk-amd64/bin/jlink does not exist.
```

You need to install the Ubuntu package which provides this file.
