### ISSUE TITLE
set_custom_mouse_cursor(null) makes the cursor disappear.

### ISSUE THREAD

**Issue by maplefee** [godotengine/godot#74508]
### Godot version

Godot Engine v4.0.stable.official.92bee43ad

### System information

Windows 10

### Issue description

The documentation states that passing ```null``` into the image parameter of ```set_custom_mouse_cursor``` will change it back to the system cursor, however I find that it removes the cursor's image entirely, rather than setting it to the system's cursor.

### Steps to reproduce

```var isimage = false
var theimage = load("res://final.png")

func _on_my_button_pressed():
    if isimage == false:
        Input.set_custom_mouse_cursor(theimage, Input.CURSOR_ARROW, Vector2(16,16))
        isimage = true
        
    else:
        Input.set_custom_mouse_cursor(null)
        isimage = false```

When the button is pressed, the cursor is meant to change to the new cursor. When it has been pressed a second time, it changes back to the default cursor. However, upon pressing it a second time, it simply disappears. The cursor becomes visible again when the cursor exits and re-enters the window.

### Minimal reproduction project

[null mouse.zip](https://github.com/godotengine/godot/files/10901969/null.mouse.zip)

**Comment by Sauermann** [comment]
I am unable to replicate this on Linux X11 Xfce.

**Comment by AThousandShips** [comment]
I believe I have the error will test soon

**Comment by AThousandShips** [comment]
PR up #74511

**Comment by AThousandShips** [comment]
Until this is fixed a workaround should be to call the function twice (haven't tested but it should fix it based on the code)

**Comment by maplefee** [comment]
Calling the function twice works. I'll close the issue once the pull request has been approved, thank you.
