### ISSUE TITLE
Items menu does not appear when a MenuButton is selected in the 2D editor

### ISSUE THREAD

**Issue by blackears** [godotengine/godot#74502]
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Windows 10, Compatability

### Issue description

Clicking on a MenuButton when in the 2D editor should add an Items menu to the top of the editor window.  It does in Godot 3.5.1, but this seems to be missing from Godot 4.

### Steps to reproduce

Create a new scene and set it's root as a Component.
Add a MenuButton as a child.
Click on the MenuButton.

An Items button should appear to the right of the spatial editor menu to allow you to add items to your menu, but nothing appears there.

### Minimal reproduction project

N/A

**Comment by nongvantinh** [comment]
What does "set it's root as a Component" mean?

Can you provide a minimal production project?

**Comment by blackears** [comment]
I meant to say User Interface.

Here's a project that demonstrates this:
[itemMenuNotShowng.zip](https://github.com/godotengine/godot/files/10910247/itemMenuNotShowng.zip)

**Comment by akien-mga** [comment]
It was removed because the functionality is now directly in the Inspector:

![image](https://user-images.githubusercontent.com/4701338/224338858-868f44a3-4ad9-4632-af6e-c99626cfa604.png)
