### ISSUE TITLE
error when lunch godot

### ISSUE THREAD

**Issue by kamranrad1993** [godotengine/godot#7451]
os : manjoro - godot 2.2 beta

i compile it from source with this code "scons platform=x11"
when i want to lunch editor give this error:  

"
ERROR: initialize: Could not obtain an OpenGL 3.3 context!
   At: platform/x11/context_gl_x11.cpp:160.
ERROR: initialize: Error initializing GLAD
   At: drivers/gles3/rasterizer_gles3.cpp:136.
Segmentation fault (core dumped)

"

**Comment by Jerome67000** [comment]
It's seems your graphic card don't support OpenGl 3.3.

Try `glxinfo | grep 'version'` in a shell and check the OpenGL version.

**Comment by reduz** [comment]
It seems godot is not tasty :(

**Comment by plucian** [comment]
are you using the 2.2 branch ? seems more like gles3 branch to me. I compiled the 2.2 branch and had no error.

**Comment by karroffel** [comment]
this is definitely the master/gles3 branch, `drivers/gles3/rasterizer_gles3.cpp` doesn't exist in 2.2.

Looks like your GPU isn't GLES 3 compatible. Maybe try updating your GPU drivers, but this isn't Godot's fault so I'm closing this.
