### ISSUE TITLE
First Character of Label Text Gets Drawn in the Middle of the Screen

### ISSUE THREAD

**Issue by mice-k** [godotengine/godot#74529]
### Godot version

Godot Engine v4.0.stable.official.92bee43ad

### System information

Windows 10 Vulkan API 1.2.154 - Forward Mobile - Using Vulkan Device #0: Intel - Intel(R) Iris(R) Plus Graphics 655

### Issue description

This issue happens on an Intel i5-8279U mini-pc. It does not occur on my Ryzen 5 5500U laptop.
Both the Mobile and Forward+ renderers give the same bugged result. The compatibility renderer does not have this issue.

Here is the minimal project and issue in one picture:
![one](https://user-images.githubusercontent.com/60864882/223293699-bcd94ac3-8410-4126-80e3-550a7f4cf494.png)
It seems that the "A" is drawn at the top left corner based on the location of the root node before the camera view is taken into account, then the rest of the text is drawn at the correct location.

### Steps to reproduce

(Pictured above)
There are no scripts involved. All I did was add the "ACB..." text to the Label and change the font color to red for better visibility, as well as the Godot icon to the Sprite2D. All other parameters are at default values.
The issue does not occur without both the Sprite2D and the Camera2D present ~~in the Player node.~~
edit: the Player node is not needed. Sprite2D and Camera2D can just be children of Main.

### Minimal reproduction project

[LabelTest.zip](https://github.com/godotengine/godot/files/10910537/LabelTest.zip)

**Comment by arkology** [comment]
@mice-k I'm almost sure this is related to:
https://github.com/godotengine/godot/issues/71027
https://github.com/godotengine/godot/issues/59802
https://github.com/godotengine/godot/issues/58314
Please test MRPs from mentioned issues.

**Comment by anitoni** [comment]
Had the same issue, after updating the 'Intel® 6th-10th Gen Processor Graphics' driver the issue was resolved.
