### ISSUE TITLE
Grid Map 3D controls overrides camera movement.

### ISSUE THREAD

**Issue by nakano15** [godotengine/godot#74520]
### Godot version

4.0 Stable

### System information

Windows 10 x64, AMD Athlon(tm) II X4 640 Processor   3.01 GHz

### Issue description

When having Grid Map 3D selected with a tile selected, you can't move the camera any way possible, until you change the current selected object in the hierarchy.

### Steps to reproduce

1. Have the Grid Map 3D be selected in the hierarchy.
2. Select a tile.
3. Try moving or rotating the camera.
4. Get frustrated.
5. OTL

### Minimal reproduction project

[Super Frustration Grid Map 3D.zip](https://github.com/godotengine/godot/files/10903630/Super.Frustration.Grid.Map.3D.zip)

**Comment by Hiiamwilliam** [comment]
I didn't test Godot 4 so I don't know if things changed, but in Godot 3 the keys to move/pan the camera (by default w,a,s,d when Right clicking) are handled by the GridMap to rotate and delete cells. Similar issues of conflicting hotkeys were reported in the past.

In Godot 3 you can press Esc to de-select the current cell, see if that still works. Alternatively, I don't know if it's still there, but in Godot 3 there is the following option Editor Settings > Editors > 3D > Navigation > Emulate 3 Button Mouse. This allows to rotate/pan the camera even with a cell selected.

**Comment by nakano15** [comment]
Yeah, deselecting the current cell fixes the issue, but also shows how inconvenient it is to handle grid maps.
Movement of the camera is kind of crucial when messing with it, even more if one's creating a large map.

**Comment by akien-mga** [comment]
Fixed by #96922.
