### ISSUE TITLE
Godot 2.1.1 needs libpng12 to run

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#7452]
**Operating system or device - Godot version:**
Ubuntu 16.10, fresh install - Godot 2.1.1 Stable

**Issue description** 
When trying to run Godot, throws error on console:
`error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory`

Was expected to run fine with libpng16 installed.

Everything works after installing a libpng12 from not official sources.

**Steps to reproduce:**
Try to run Godot without libpng12 installed (not available in Ubuntu 16.10 repositories).

Godot 2.1.0 Stable runs fine without libpng12.

**Comment by akien-mga** [comment]
When did you download the binaries? I fixed that a few days after the 2.1.1 release and made new binaries.
https://github.com/GodotBuilder/godot-builds/commit/1ccb9e097eab88796ff287fb0b44b2819174809b

Could you try to redownload the editor/templates and check if it's better? http://download.tuxfamily.org/godotengine/2.1.1/

**Comment by eon-s** [comment]
@akien-mga ok, this is weird, I always download the stable from official site, the version I got says modified 11-16-2016 but that is before release...

Checked yours and downloaded again from the site, both have posterior timestamps (11-20 the site one) and both work fine.

Maybe I just got these just before the fix but never noticed with the messy system...

**Comment by akien-mga** [comment]
Well you were just pretty fast to download the release when I first announced it on Nov 16-17, but then I did some hotfixes on the 19th and 20th.

It should be fixed for everyone with Godot 2.1.2 :)
