### ISSUE TITLE
Orbiting with the middle-mouse key not working in the master branch since yesterday 

### ISSUE THREAD

**Issue by tagcup** [godotengine/godot#7453]
**Operating system or device - Godot version:**

Linux, latest git.

**Issue description** (what happened, and what was expected):

Orbiting with the middle-mouse key not working in the master branch since yesterday. I have removed ~/.godot directory, started a new project, made sure the Navigation Scheme is set to Godot.

**Steps to reproduce:**

Open any 3D scene (even an empty project) and try to orbit using middle mouse button.
Instead, it pans.

**Link to minimal example project** (optional but very welcome):

**Comment by karroffel** [comment]
Dodgetgo from the Discord confirms this bug on Windows too.

**Comment by BastiaanOlij** [comment]
Yeah and I just noticed it on Mac, also with emulating 3 button mouse, I can't orbit, pan nor zoom.

**Comment by karroffel** [comment]
For me it defaults to pan only

**Comment by tagcup** [comment]
Fixed in master now
