### ISSUE TITLE
Several build options produce non-working editors

### ISSUE THREAD

**Issue by stefano-elysium** [godotengine/godot#74546]
### Godot version

5dccc940e73d39a1ac4f3d64ccc92373e6609add

### System information

Xubuntu

### Issue description

Command: `scons platform=linux`

Compiling the editor with `module_svg_enabled = "no"`, causes a crash on startup.

Compiling the editor with `module_text_server_adv_enabled = "no"` breaks the texts and it looks like this:
![image](https://user-images.githubusercontent.com/85214725/223424127-6145e715-5ce1-427b-beb6-f78c05d99824.png)
(Message in console: `WARNING: Some locales are not properly supported by selected Text Server and are disabled. `)

Compiling the editor with the module_text_server_adv_enabled, but with option `module_freetype_enabled = "no"` causes compilation failure, messages `[ 46%] In file included from modules/text_server_adv/thorvg_svg_in_ot.cpp:58:
modules/text_server_adv/thorvg_svg_in_ot.h:55:10: fatal error: freetype/freetype.h: No such file or directory
   55 | #include <freetype/freetype.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[ 67%] In file included from modules/text_server_adv/text_server_adv.cpp:76:
modules/text_server_adv/thorvg_svg_in_ot.h:55: fatal error: freetype/freetype.h: No such file or directory
   55 | #include <freetype/freetype.h>
      | 
compilation terminated.
`

### Steps to reproduce

As above.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
The SVG without freetype is a bug though, the module check isn't checking for freetype even though it is required for that to work, will look at a fix

**Comment by AThousandShips** [comment]
See #74556

**Comment by YuriSizov** [comment]
The cases reported here are addressed by https://github.com/godotengine/godot/pull/74551 and https://github.com/godotengine/godot/pull/74556. Note that disabling those modules will never produce a completely working editor, because it is not building without those modules in mind. The best we can guarantee is that it doesn't crashes.

**Comment by stefano-elysium** [comment]
@YuriSizov if it will never produce a working editor, why not prevent editor builds, like if advanced UI is disabled?

**Comment by YuriSizov** [comment]
That's a good idea!
