### ISSUE TITLE
Keep getting `Condition "plugins_list.has(p_plugin)" is true.` when selecting Tilemap Node and TileSet resource is open in the inspector

### ISSUE THREAD

**Issue by eh-jogos** [godotengine/godot#74543]
### Godot version

4.0 stable

### System information

Manjaro Linux using i3, Foward+

### Issue description

Whenever the tileset property of any tilemap node is like open in the editor like this:
![image](https://user-images.githubusercontent.com/13070158/223416376-be0d7bca-1af8-43ad-9f19-a22de0a5a3c6.png)

If I select any other node and then select the TileMap node again it will print this error:
![image](https://user-images.githubusercontent.com/13070158/223416512-abbf4d45-e6c8-4c5f-894a-9b5810bf0cc2.png)
` editor/editor_node.cpp:8152 - Condition "plugins_list.has(p_plugin)" is true.`

This seems to be actually true to any plugin or `EditorInspectorPlugin` that edits node. In my project I have a InspectorPlugin that adds some buttons in `_parse_begin` for a specific kind of node, and that node also has an exported custom resource, and whenever I select any of that Node and their resource is open for edit in the Inspector I get the same error.

### Steps to reproduce

- Create a TileMap node on any scene
- Create a new TileSet resource on the TileMap node
- click on the TileSet resource to edit it in place in the TileMap node
- Select any other node
- Select the TileMap node again.

### Minimal reproduction project

[plugin_error_resource_edit.zip](https://github.com/godotengine/godot/files/10909135/plugin_error_resource_edit.zip)

- Open main scene
- Select the TileMap node
- Click the tileset resource in the inspector
- Select the root node
- Select TileMap node again

**Comment by RichardR01** [comment]
Same error with top level Control node.
It started happening after I created an AnimationPlayer, and animated some child control's scale property. Still continue to get the error even after I removed the AnimationPlayer and reloaded the project. There is a long delay before the Control node is selected or loaded in.

**Comment by anisc** [comment]
I'm using 4.0.2, I'm getting the same issue by just adding a tile set. 
  editor/editor_node.cpp:8243 - Condition "plugins_list.has(p_plugin)" is true.
  editor/editor_node.cpp:8243 - Condition "plugins_list.has(p_plugin)" is true.
The whole project is one scene 
>Node2D
   >TileMap
