### ISSUE TITLE
error building export templates for android

### ISSUE THREAD

**Issue by GrandFunkR** [godotengine/godot#7454]
**Operating system or device - Godot version:**
linux - godot 3.0-alpha

**Issue description** (what happened, and what was expected):
are there one error building export templates for android:

In file included from platform/android/os_android.cpp:30:
./drivers/gles2/rasterizer_gles2.h:54:10: fatal error: 'drivers/gles2/shaders/material.glsl.h' file not found
#include "drivers/gles2/shaders/material.glsl.h"
         ^

**Steps to reproduce:**
scons -j 2 platform=android target=release_debug

**Comment by BastiaanOlij** [comment]
Android hasn't been updated for the new renders yet.

**Comment by GrandFunkR** [comment]
It is there a due date to implement Android support in 3.0?

**Comment by akien-mga** [comment]
@reduz is working on it currently.

**Comment by GrandFunkR** [comment]
works now
