### ISSUE TITLE
CharacterBody3D's real velocity is inaccurate when colliding

### ISSUE THREAD

**Issue by prominentdetail** [godotengine/godot#74553]
### Godot version

4.0

### System information

windows 10

### Issue description

The real velocity of a CharacterBody3D becomes inaccurate in cases where it is colliding against a surface, in this case a wall.
![realvelocitybug](https://user-images.githubusercontent.com/10412778/223458144-707cd957-3974-4135-acf5-5c23a36fd0ca.gif)

### Steps to reproduce

Run the example project and push against the wall at an angle.

### Minimal reproduction project

[realVelocityBug.zip](https://github.com/godotengine/godot/files/10910647/realVelocityBug.zip)

**Comment by solitaryurt** [comment]
Looks related to: https://github.com/godotengine/godot/issues/66249
