### ISSUE TITLE
Resizing side panels lead to forever freeze

### ISSUE THREAD

**Issue by cassandrus** [godotengine/godot#74554]
### Godot version

4.0.stable

### System information

Windows 10, all GPU info is in attached file

### Issue description

When I try to resize side panels (filesystem, inspector), Godot goes to forever freeze. This is VERY disappointing, as I often do this unconsciously while editing project. 

It happens in any project. To my surprise, I didn't found similar reports in recent issues on github... so, as it's impossible to miss this very basic functionality, perhaps it only happens on my hardware config.

I added screenshot from the attempt to check it in rc5, but in a stable build situation is absolutely the same. I added debug key to show an error in console. 

Here is dxdiag report of my system, maybe it will be helpful:
[DxDiag.txt](https://github.com/godotengine/godot/files/10910652/DxDiag.txt)

Editing and running projects works fine.

![image](https://user-images.githubusercontent.com/97176349/223457176-35dda3b7-66ee-4e8d-9f24-b876cbc9e013.png)

### Steps to reproduce

I'm not sure it's easy to reproduce on other hardware. It happens right after trying to resize side panel.

### Minimal reproduction project

N/A, it's not dependent to project, happens everywhere

**Comment by clayjohn** [comment]
Indeed, this is likely a hardware/driver combo. I have added this to a tracker for similar issues. As you can see, you are not the only user affected by this bug, but it presents itself in different ways to different people. 

I suggest checking for a driver update as it has resolved the issue for some users.

**Comment by Darkiii** [comment]
![image](https://user-images.githubusercontent.com/10893550/225602433-8c08443d-d436-4a0f-85f0-2e63b5fa881c.png)
same problem on my computer,  Windows 11 os.

**Comment by vix597** [comment]
![image](https://github.com/godotengine/godot/assets/1337331/8004ffbb-b4f2-4b31-92a2-63dc29e763a4)

Same problem on my system. Godot 4.0.2.stable

* PC: Windows 10 22H2 Build 19045.2846
* Godot:

    ```
    Godot Engine v4.0.2.stable.official.7a0977ce2 - https://godotengine.org
    OpenGL API 3.3.0 - Build 31.0.101.3959 - Compatibility - Using Device: Intel - Intel(R) Iris(R) Xe Graphics
    ````

**Comment by vix597** [comment]
I can confirm that a driver update resolved the issue for me. Updated to this:

![image](https://github.com/godotengine/godot/assets/1337331/6f5ce6cb-252c-4af5-8efe-6f1e56daf306)

**Comment by Calinou** [comment]
@cassandrus @Darkiii Can you try updating your graphics driver as mentioned above? Grab the driver directly from Intel (not your OEM, not Windows Update).

**Comment by cassandrus** [comment]
> @cassandrus @Darkiii Can you try updating your graphics driver as mentioned above? Grab the driver directly from Intel (not your OEM, not Windows Update).

I've updated driver to aforementioned mentioned and it solves the issue. 👍

**Comment by Calinou** [comment]
Alright, closing then.
