### ISSUE TITLE
mobile buttons bug

### ISSUE THREAD

**Issue by JLGGX1000** [godotengine/godot#74550]
### Godot version

4.0

### System information

android 6 j2 prime

### Issue description

Thanks for solving the mobile black screen bug, but there's just one more bug that I can't press the buttons and some buttons stay off the screen and I can't press anything when I edit the project

### Steps to reproduce

Thanks for solving the mobile black screen bug, but there's just one more bug that I can't press the buttons and some buttons stay off the screen and I can't press anything when I edit the project

### Minimal reproduction project

Thanks for solving the mobile black screen bug, but there's just one more bug that I can't press the buttons and some buttons stay off the screen and I can't press anything when I edit the project

**Comment by akien-mga** [comment]
You're not following the template in any way, we can't do anything.
