### ISSUE TITLE
ScriptEditor - Right Click Menu broken

### ISSUE THREAD

**Issue by bebae** [godotengine/godot#7455]
**Operating system or device - Godot version:**
Linux - current master

**Issue description** (what happened, and what was expected):
The options when opening the right click menu in the script editor don't do what they say:
`Select All` deletes the line of the cursor or the current selection
`Paste` undos
`Undo` does nothing?
etc...

**Steps to reproduce:**
Open a script, right-click inside the text editor and choose `Select All`, this should delete a line.

**Comment by bojidar-bg** [comment]
Seem like a one-off error to me.

**Comment by bojidar-bg** [comment]
Can confirm actually, on the 2.2 branch.

**Comment by bojidar-bg** [comment]
Bug comes from [`tools/editor/plugins/script_text_editor.cpp:1229`](https://github.com/godotengine/godot/blob/86e428eea0b9ef5c1732af3a5c29b5c365fbf6e8/tools/editor/plugins/script_text_editor.cpp#L1229), await PR ;)

**Comment by plucian** [comment]
copy / paste not working either when using the right click menu.

**Comment by bojidar-bg** [comment]
@plucian Shouldn't be an issue when/if #7458 is merged. If you really want, you can test the PR for yourself :smiley:

**Comment by plucian** [comment]
this has been merged into the master not into the 2.2 branch. Could you fix that branch too please ?
