### ISSUE TITLE
Broken get_viewport().size=Vector2(x,y)

### ISSUE THREAD

**Issue by DimitriyPS** [godotengine/godot#74572]
### Godot version

Godot 4.0 stabile

### System information

Linux (all)

### Issue description

In Godot 3 I used get_viewport().size=Vector2(x,y) to change the render resolution. This is a great optimization option that you can hot-select in the game settings.

When I call get_viewport().size=Vector2(x,y) in the Godot 3 script, the viewport assumes the resolution of Vector2(x,y) and it doesn't spontaneously change.

When I do this in Godot 4, it fires for a moment and then the viewport takes the window's resolution.

### Steps to reproduce

1. Look at the code of the attached project
2. Run the project
3. Switch the selector in the project or resize the window with the mouse
3.1 Look at the viewport resolution displayed in the project

### Minimal reproduction project

[DEMO.zip](https://github.com/godotengine/godot/files/10914004/DEMO.zip)

**Comment by clayjohn** [comment]
I think the intended behaviour is for the window to control the root viewport size now. Have you tried using ``get_window().size``? Or some combination of ``get_window().content_scale_mode`` and ``get_window().content_scale_factor``?

**Comment by DimitriyPS** [comment]
I'm trying to do exactly as it's done in the demo. I am trying to switch the viewport resolution.

I use only full screen mode in the game, and the viewport resolution switch in the game settings acts as an optimization parameter. You can reduce its resolution and win extra fpc.

**Comment by clayjohn** [comment]
I don't think that it works the same way anymore. I think you have to use the window content scaling factor now. The way that Viewports interact with the window has changed a lot in Godot 4.0. So not everything can be done exactly the same. 

Can you try using the window API?

**Comment by DimitriyPS** [comment]
I have now looked https://docs.godotengine.org/en/stable/classes/class_window.html

Yes, I tried get_window().content_scale_mode/get_window().content_scale_factor through the project settings. It doesn't change the core of the problem.

> I don't think that it works the same way anymore. I think you have to use the window content scaling factor now. The way that Viewports interact with the window has changed a lot in Godot 4.0. So not everything can be done exactly the same.

I'm porting a project... and it was a whole well-established system, including adaptive theme, selective 2D content... it allowed me to significantly balance between optimization and the ideal picture, potentially on screens from HD to 8K... (although I only tested up to 4K)...

If it's no longer possible... then it's either an optimization drawdown... or the loss of a perfect picture...

Is that really not possible anymore?

**Comment by clayjohn** [comment]
I'm not suggesting that you change the project settings. You can change ``content_scale_mode`` and ``content_scale_factor`` through scripting. That's why I wrote ``get_window()`` first. Please try it from GDScript as well. 

> Is that really not possible anymore?

I'm sure something equivalent is possible, but I don't know if the exact trick that you used is still possible

**Comment by DimitriyPS** [comment]
```
func _ready():
	get_window().content_scale_mode=get_window().CONTENT_SCALE_MODE_DISABLED
	get_window().content_scale_factor=get_window().CONTENT_SCALE_ASPECT_IGNORE
	
	$OptionButton.add_item("1280*720")
	$OptionButton.add_item("1920*1080")
	$OptionButton.select(0)
	pass
```
I added them to the above demo and tried them in different combinations. But this does not change the essence of the problem. I can't set and fix the viewport resolution.

**Comment by clayjohn** [comment]
``content_scale_factor`` takes a floating point number. I.e. 0.5 would be 50% resolution. If your initial viewport size is 1920x1080 and you want it to be 1280x720, then you would use 0.66. ``CONTENT_SCALE_ASPECT_IGNORE`` is ``0`` which is the same as telling the window to use no scaling

**Comment by DimitriyPS** [comment]
Exactly ... I generally used the value of the wrong parameter 🤦

It turns out now for a similar result, you need to change get_window () .content_scale_factor (have not yet tested the game). However, this only applies to the interface. While the viewport is still full screen:

![Снимок экрана от 2023-03-08 01-31-37](https://user-images.githubusercontent.com/11189223/223570077-808a12e9-7596-4f22-bcf6-91d94023cad4.png)


Does this mean that there will be no optimization in 3D scenes?

**Comment by clayjohn** [comment]
I think I am misunderstanding what you actually want to achieve. So let me explain a few key concepts.

1. Window size and Viewport size are linked, so when you change one the other changes as well
2. You can render the entire game at a lower scale than the window size by setting ``window.content_scale_mode`` to ``CONTENT_SCALE_MODE_VIEWPORT`` and by adjusting the ``window.content_scale_factor`` (what I recommended above)
3. If you are making a 3D game, you can scale the 3D viewport and leave the 2D viewport at its current size using ``get_viewport().scaling_3d_scale``

Using options 2 or 3 you can render at a lower resolution to save performance.

**Comment by DimitriyPS** [comment]
> I think I am misunderstanding what you actually want to achieve. So let me explain a few key concepts.

I'm just solving 2 problems at once... In Godot 3 everything was simpler and clearer... and in fact it worked... in Godot 4 everything is not very obvious and confusing...

I see... so I now need get_viewport().scaling_3d_scale...

@clayjohn I'm still porting interface scenes, a global script and other things ... I won't get to the 3D scene soon to try and test it ... so I'll clarify right here, can the scaling_3d_scale parameter be changed at runtime game?

**Comment by clayjohn** [comment]
> @clayjohn I'm still porting interface scenes, a global script and other things ... I won't get to the 3D scene soon to try and test it ... so I'll clarify right here, can the scaling_3d_scale parameter be changed at runtime game?

Yes it can. Remember, that it won't affect the size of your 2D elements though. Those will still render at full resolution. That way you can keep your GUI looking nice and crisp but still lower the resolution of your 3D scene to save performance

**Comment by DimitriyPS** [comment]
@clayjohn thank you very much! You helped me a lot!
