### ISSUE TITLE
Animations stop working after rectreating/reinstancing character.

### ISSUE THREAD

**Issue by pietru2004** [godotengine/godot#74574]
### Godot version

4.0 stable

### System information

Windows 10 Forward+

### Issue description

![obraz](https://user-images.githubusercontent.com/51274570/223560639-5792e39a-1062-4e32-946b-94f855f975da.png)

After removing node called Character and recreating it animation player does not animate character.
I have system that changes character/npc look, but it references to Skeleton that is the same on all models and only thing that is different is mesh name that is not used in animation.
Also it happened cause it is not working to apply external animations file into imported gltf model.

### Steps to reproduce

Create Animation Player that will do animation
Get 2 models with rig or 2 models to create under the same name - gltf
place one of models under the same node as animation player
on game start remove that model and randomly pick one of models and add it under the node that animation player is under

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
@pietru2004 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.

PS: Since no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.

**Comment by pietru2004** [comment]
I just say - sorry I would give minimal reproduction project, but too much happening with school atm. sorry.
