### ISSUE TITLE
Animation bezier curve editor's track list can't be scrolled

### ISSUE THREAD

**Issue by GNSS-Stylist** [godotengine/godot#74577]
### Godot version

v4.1.dev.custom_build [013a45706], also 4.0

### System information

Windows 10

### Issue description

There is no scrollbar that could be used to scroll though track list in animation editor when using it in the bezier curve editor mode. Using the scroll wheel of a mouse doesn't scroll the track list area either, but tracks themselves instead.

Video:

https://user-images.githubusercontent.com/50438441/223568028-091a9687-701a-4332-94bb-702080d9df84.mp4

When editing a lot of tracks this makes selecting tracks to be edited, shown, hid, locked etc. cumbersome and finally impossible when the screen area is no longer enough to show all tracks at once (even when stretched to max height).

### Steps to reproduce

Add a lot of bezier tracks into an animation. Once there are enough tracks it will become impossible to select them from the list as the list can't be scrolled.

### Minimal reproduction project

[AnimBezierEditorNoScrollbar.zip](https://github.com/godotengine/godot/files/10914566/AnimBezierEditorNoScrollbar.zip)

**Comment by GNSS-Stylist** [comment]
Wrote a comment to the linked PR (https://github.com/godotengine/godot/pull/83776), but copying (and updating a bit) it here, since probably it was a bit hidden there:

@SaracenOne Unfortunately this fix doesn't seem to work on my setup. Scroll wheel of the mouse or two-finger scroll-gesture on the touchpad don't do anything unless zoom modifiers (CTRL / ALT) are pressed.

As a workaround it is possible to use the middle mouse button to drag-scroll.

First I though this was broken again later (first tested with post-RC1-version), but this new issue seemed to appear right after this commit (switched/checked out versions right before this and this).

Could this be related to OS/HW-setup? My system (From Godot's Help->Copy System Info): Godot v4.3.dev (a311a4b16) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.4617) - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 Threads)

This is a Lenovo laptop with touchpad and an external mouse (Logitech M705). Everything else seems to work with this setup, including scrolling in other parts of the Godot's UI.

Don't know how this should be handled so writing this comment here... I'm not able to reopen this issue.

Likely related issue: https://github.com/godotengine/godot/issues/85826

**Comment by sourcelocation** [comment]
Same issue, bumping

**Comment by AThousandShips** [comment]
Please open a new issue if you're experiencing issues, this has been closed and new details are needed
