### ISSUE TITLE
High or Increasing Memory Usage

### ISSUE THREAD

**Issue by INdIEDeV016** [godotengine/godot#74581]
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Windows 11, Forward+, NVIDIA GeForce RTX 3060 Laptop GPU (v531.18 from GeForce Experience)

### Issue description

The memory usage keeps increasing slowly and the Update Spinner is spinning continuously even if it is set to "Update When Changed". It is also using my GPU a lot even if there is no complex scene. If I tab out of Godot and let it run in background, then the memory increase slows down to a trickle, but it still seems to be increasing.

<img width="617" alt="image" src="https://user-images.githubusercontent.com/80198819/223585767-3147c933-c291-4477-9ae2-5881413ac0f5.png">

### Steps to reproduce

Use the Godot Editor from version 4.0

### Minimal reproduction project

NA

**Comment by clayjohn** [comment]
Can you please upload an MRP? Without one we cannot help you. We need the MRP to narrow down where the issue is coming from so that we can investigate

**Comment by glitchcosmonaut** [comment]
Also experiencing this issue on Mac.

**Comment by INdIEDeV016** [comment]
The issue was an addon I was using which I didn't think about. Thank you for your attention.
