### ISSUE TITLE
gles 3.0 web build (compatibility) crashing on Mac (?)

### ISSUE THREAD

**Issue by MrEgggga** [godotengine/godot#74586]
### Godot version

4.0.stable.official

### System information

MacOS 12.3.1, Apple M1, unknown driver version, GLES3

### Issue description

Any web build with UI elements from GLES 3.0 will crash the web browser on Mac (checked with Firefox, Chrome, and Safari; it crashes most of the way through the progress bar on Firefox and Chrome and gets stuck on a loading icon in Safari (but doesn't become unresponsive)). This may just be a problem with my computer only as I haven't seen anything about it online. This was a problem in version 3 too but now that the only rendering backend supported for web builds is GLES3 I can't build anything at all that runs on Mac.

### Steps to reproduce

1. Create a new project in Godot 4 with the "Compatibility" renderer. (This should also work in Godot 3 with the GLES 3.0 rendering backend.)
2. Create a scene with root type Control and add a button wherever (2D nodes may do the same thing but I haven't checked), and set it as the main scene.
3. In the Export menu, create a preset for Web and leave it on the default options.
4. Serve the build somewhere, with the correct headers to allow Godot 4 projects to run (I used Netlify).
5. On MacOS, run the project in Chrome, Firefox or Safari.
6. On Chrome or Firefox the webpage should become unresponsive and potentially entirely crash the browser; on Safari the page just gets stuck on a loading screen. (unless this isn't an actual bug and my computer is being strange)

### Minimal reproduction project

[web bug.zip](https://github.com/godotengine/godot/files/10916918/web.bug.zip)
(includes web build)

**Comment by clayjohn** [comment]
I have a feeling this is the same as https://github.com/godotengine/godot/issues/70691. Could you try the workarounds discussed there and see if they help?

**Comment by MrEgggga** [comment]
That does seem like the same bug as I had before, and in fact the project does load after 2ish minutes. I guess I just wasn't searching for the right things in the issue tracker.
