### ISSUE TITLE
Works fine while Debug but crashes when run after export

### ISSUE THREAD

**Issue by airs1991** [godotengine/godot#74596]
### Godot version

v4.0.stable.mono.official [92bee43ad]

### System information

MacOS 10.15.7(19H2026)

### Issue description

The debug in the engine can run, but it crashes after exporting.
Console information:

```
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.stable.mono.official (92bee43adba8d2401ef40e2480e53087bcb1eaf1)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] sigsegv_handler(int, __siginfo*, void*)
[2] 2   libsystem_platform.dylib            0x00007fff6f0f55fd _sigtramp + 29
[3] 3   ???                                 0x0000000000000000 0x0 + 0
[4] JSON::get_data() const
[5] Object* ClassDB::creator<mono_bind::GodotSharp>()
[6] 6   ???                                 0x00000001192d6328 0x0 + 4717372200
[7] 7   ???                                 0x00000001192d5074 0x0 + 4717367412
[8] 8   ???                                 0x00000001192d4a9c 0x0 + 4717365916
[9] 9   ???                                 0x0000000117bf8ed4 0x0 + 4693397204
[10] RendererCompositorRD::_create_current()
[11] 11  Mayor                               0x0000000103787473 Mayor + 4641907
[12] RendererCompositorRD::_create_current()
[13] 13  libdyld.dylib                       0x00007fff6eefccc9 start + 1
-- END OF BACKTRACE --
================================================================
```

The error reported by the Mac system exceeds the word limit, and is attached in the text file below.

### Steps to reproduce

Supplementary modification:
I found the offending code, after disabling the game became available after exporting.
But they simply modify the button image, like this:
`DataBtn[i].Icon = Face.GetFace(npc);`
I'm not sure if this has something to do with me passing the texture in a variable, or putting the method of rendering the button image in a for/foreach loop, but I didn't find this problem when I created a new minimal project.
Trying to find the cause.

**Comment by airs1991** [comment]
After debugging the code line by line, I finally found out that the problem is not the serialization - there is a method in my game project to serialize and display to the UI, and there is a problem when drawing the UI.
They simply draw the button's icon and text. But after disabling drawing, the game works, and I see the following error code in the console:

```
ERROR: 1 RID allocations of type 'N5GLES312RenderTargetE' were leaked at exit.
ERROR: 13 RID allocations of type 'N5GLES37TextureE' were leaked at exit.
ERROR: 16 RID allocations of type 'N18RendererCanvasCull4ItemE' were leaked at exit.
ERROR: Condition "!pb_ptr" is true.
   at: free_polygon (drivers/gles3/rasterizer_canvas_gles3.cpp:2437)
ERROR: Condition "!pb_ptr" is true.
   at: free_polygon (drivers/gles3/rasterizer_canvas_gles3.cpp:2437)
ERROR: 1 RID allocations of type 'N18RendererCanvasCull6CanvasE' were leaked at exit.
ERROR: 1 RID allocations of type 'N16RendererViewport8ViewportE' were leaked at exit.
ERROR: 28 RID allocations of type 'PN18TextServerAdvanced22ShapedTextDataAdvancedE' were leaked at exit.
ERROR: 1 RID allocations of type 'PN18TextServerAdvanced12FontAdvancedE' were leaked at exit.
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: cleanup (core/object/object.cpp:1982)
ERROR: Resources still in use at exit (run with --verbose for details).
   at: clear (core/io/resource.cpp:489)
```

**Comment by willschroeder** [comment]
I received the same stacktrace as your first one, as I was reading in a json file in the root of the project. It works in development, but crashed after compiled. I was not checking for file existence beforehand. Once I copied my json file to the same as the compiled app, it worked. 

Not the friendliest stack output.

**Comment by Calinou** [comment]
@airs1991 @willschroeder Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by airs1991** [comment]
After several struggles, I finally found the problem.
I use DirAccess class to scan all files under a certain folder and import. This works fine when running debug, but after exporting, DirAccess doesn't scan relative paths correctly. I was assigning the button image to a variable that didn't exist and that was causing the problem.
