### ISSUE TITLE
Editor command line --export-pack option does not produce pck or zip.

### ISSUE THREAD

**Issue by TyounanMOTI** [godotengine/godot#74606]
### Godot version

4.0.stable

### System information

Windows 11

### Issue description

When trying to export .pck by running Godot with command line option `--export-pack`, nothing has been produced.
I've tested for following export platform, but others may suffer from this issue.
- Web
- Windows

Only following logs are printed on cosole:
```
Godot Engine v4.0.stable.official.92bee43ad - https://godotengine.org
OpenGL API 3.3.0 NVIDIA 531.18 - Compatibility - Using Device: NVIDIA Corporation - NVIDIA GeForce RTX 3080
```

### Steps to reproduce

1. Unzip minimal reproduction project.
2. Run `godot ./ --export-pack PackPreset main.pck`
3. There is no `main.pck` at project root (reproduced).

### Minimal reproduction project

[export_pack_cmdline.zip](https://github.com/godotengine/godot/files/10921044/export_pack_cmdline.zip)

**Comment by akien-mga** [comment]
> Run `godot ./ --export-pack PackPreset main.pck`

The syntax is incorrect, if you want to pass a custom path you need to use `--path path/to/folder`.

If you're already in the folder, the syntax is simply:
```
godot --export-pack PackPreset main.pck
```
Which I confirmed is working.

**Comment by TyounanMOTI** [comment]
Oh, thank you for telling me the correct syntax. It worked as expected!
I'm looking forward that PRs because the current console output with incorrect syntax wasn't helpful as there are no error message.
Thank you and closing this issue.
