### ISSUE TITLE
Constant project.godot and re-importing when using MacOS and Windows

### ISSUE THREAD

**Issue by cridenour** [godotengine/godot#74609]
### Godot version

4.0.stable

### System information

Windows 10, MacOS

### Issue description

Some combination of ~~#72301~~#72031 and #73829 and the differing platform default settings + not including default values in project.godot has created a frustrating problem. 

When a developer on the project opens it in Windows, it deletes `rendering/textures/vram_compression/import_s3tc_bptc=true` from project.godot. When that happens, the MacOS version then re-imports everything as only ASTC and updates all the `.import` files. And then it deletes `rendering/textures/vram_compression/import_etc2_astc=true` from project.godot. Then the windows machine re-imports everything, and forever and ever they fight over import files, unless we're diligent about not letting that particular change in `project.godot`. 

This has made cross-platform development very obnoxious and with high quality textures, the constant re-imports can take a very long time. 

### Steps to reproduce

1. Add a VRAM Compressed Texture to a project. 
2. Attempt to make both platforms happy by enabling both VRAM compression formats.
3. Re-open on both Windows and MacOS.

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
https://github.com/godotengine/godot/pull/73829 only changes exports. It won't change your .import files or your project file. 

Can you elaborate how https://github.com/godotengine/godot/issues/72301 is connected to this issue?

I have a feeling the issue comes from how we handle default settings. We don't save settings if they are the same as default. My guess is we have different defaults for macOS and Windows leading to the engine silently deleting the texture import settings in your project.godot file

**Comment by WindyDarian** [comment]
For custom builds i have mentioned a local work around in https://github.com/godotengine/godot/issues/74967 , basically changing defaults to false regardless of platform, and enable both in project settings. That still means importing both formats for both platforms, which is not great, so it should stay as a local workaround...

Ideally, platforms should still only import texture compression formats they need, but all of these specific data should probably be in `.godot` folder, not `*.import` files that are version controlled

**Comment by cridenour** [comment]
@WindyDarian thanks for the workaround! Makes life so much easier.

**Comment by aaronfranke** [comment]
Fixed by #78147 which was a follow-up to #77105.

**Comment by Jhappy77** [comment]
I am encountering this issue again on 4.5.beta. 
Mac adds etc2_astc to all my texture .import files like this:
```
"imported_formats": ["s3tc_bptc", "etc2_astc"],
```

if I commit the changes, and then open it on Windows, Windows reverts all that. Causing constant diffs when moving between OSes


EDIT: I think I fixed it by enabling both in Project Settings, deleting .godot/imports, and reopening project.

**Comment by paskausks** [comment]
Maybe it's some sort of regression (also possible, that we have done something which we didn't before), but we are also encountering this issue on 4.5 stable.

Previously, on 4.3, we were just using a platform override a la `textures/vram_compression/import_etc2_astc.macos=true
` and that didn't cause any issues with the `*.import` files. But also very possible that we've done something that we didn't before that caused this issue for us. Gonna keep an eye out.
