### ISSUE TITLE
Compilation errors when tools=no

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#7460]
Compiling the master branch with tools=no gives compilation errors such as:
scene/3d/baked_light_instance.cpp:1698:18: error: no member named 'get_edited_scene_root' in 'SceneTree'

There are also a number of errors that popup around rid.h and compiler directives.

Note that I've fixed them in PR #7457 as I ran into them while fixing compilation errors for iOS.

**Comment by karroffel** [comment]
@BastiaanOlij that PR got merged, so it's fixed now and this issue can be closed?

**Comment by akien-mga** [comment]
Yep.
