### ISSUE TITLE
`DirectionalLight3D` ignores `VisualInstance3D` layers

### ISSUE THREAD

**Issue by ettiSurreal** [godotengine/godot#74617]
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Windows 11, Broken on all backends

### Issue description

I am trying to make a game where you see the world through two cameras at once, both of which see different objects and use different lighting.
I've been using the layers on `VisualInstance3D` in order to determine which camera sees which objects and lights (Layer 1 is shared, Layer 2 is camera A only and layer 3 is camera B only).

However I quickly discovered that `DirectionalLight3D` ignores the layers on `VisualInstance3D`, which makes it impossible to use it in the way I want to. Cull mask only lets me determine which objects the light affects, and not which camera sees it.
This doesn't happen with any other light type, and is not documented so i assume it is a bug and not a limitation.

### Steps to reproduce

1. Make a simple scene.
2. Add a `DirectionalLight3D`.
3. Disable `Layer 1` on `VisualInstance3D` in the inspector, the light will still affect the scene.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Duplicate of #74545

**Comment by ettiSurreal** [comment]
> Duplicate of #74545
