### ISSUE TITLE
Invalid reporting of shadowed variable as functions

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#74611]
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Windows 10, MacOS

### Issue description

I am in the process of fixing my plugin to rid it of warnings, but the warnings are partly just nonsensical or wrong.

So why i get a warning for a shadowed variable shadowing an already-declared function?
A variable is just a variable and not a function and vise versa.

a simple example:
```gdscript
var _value :int

func _init(value :int):
	_value = value

func value() -> int:
	return _value
```

The constructor uses a variable called "value" and initializes the member variable "_value". 
Why it should not allowed to use `value` as name for the argument?
How can this argument name shadow a function, that makes no sense.

Same problem for static functions, a static function is a prioritized way to decouple code from the class to minimize side effects.
From [documentation](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#static-functions): **it has no access to the instance member variables**
```
var _value :int

func value() -> int:
	return _value


static func foo():
	var value = 10
```
The variable `value` inside the static function should never affect the stuff from the class itself.

All these problems sound like a script parser problem where there is no way to distinguish between an argument and a function.
This kind of warnings confuse the developer and force him to use circumstantial names for arguments.

### Steps to reproduce

try with this lines

```gdscript
var _value :int

func _init(value :int):
	_value = value

func value() -> int:
	return _value
```
`Row 3 (SHADOWED_VARIABLE):The local function parameter "value" is shadowing an already-declared function at line 6.`

and

```gdscript
var _value :int

func value() -> int:
	return _value


static func foo():
	var value = 10
```
`Row 8 (SHADOWED_VARIABLE):The local variable "value" is shadowing an already-declared function at line 3.`

### Minimal reproduction project

N/A

**Comment by MikeSchulze** [comment]
it may be that functions and variables now share the same identifier space, but why is the syntax break here passed on to the developers?
This is absolutely inconvenient that you now have to provide the variables with a pseudo hotfix ala suffix just because the compiler does not get it done to distinguish a variable from a function.
;(

**Comment by dalexeev** [comment]
This is not a bug, but a matter of the naming you are using.

```gdscript
# Private member.
var _something: int

func _init(something: int) -> void: # Parameter / local variable.
    _something = something

# Public getter.
func get_something() -> int:
    return _something

# Public setter.
func get_something(value: int) -> void:
    _something = value
```

```gdscript
# Public member (property).
var something: int:
    get:
        return _something
    set(value):
        _something = value

# Private member (actual).
var _something: int

func _init(p_something: int) -> void: # Parameter / local variable.
    _something = p_something
```

**Comment by KoBeWi** [comment]
This is intended behavior. If you don't like it, open a [proposal](https://github.com/godotengine/godot-proposals).
