### ISSUE TITLE
Release build of project crashes when the shader cache isn't manually deleted beforehand

### ISSUE THREAD

**Issue by Zepher79** [godotengine/godot#74616]
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Windows 10, AMD Ryzen 7 2700X, NVIDIA GeForce GTX 1050 Ti, Vulkan

### Issue description

An incredibly specific crash that only happens on a release build of a project. Neither the crash nor any errors are reported when taking the same actions while running the project from the editor nor when exporting the project using a DEBUG build.

When running the project the first time, before the shader_cache folder has been populated in the AppData path, the crash does not seem to occur. Upon closing and running the executable again and taking the steps to reproduce, the crash will occur on my own and another computer, both running AMD processors but different GPUs. Deleting the shader_cache contents and running again will prevent a crash from occurring.

Turning on verbose logging sees both logs truncated at the line mentioning 'SdfgiIntegrateShaderRD', though on my machine it appears to cut the line halfway through printing its memory address (I assume?) while the second machine logs the entire address but nothing beyond. An example of a crashed log file and a normally exited log file are attached.

[godot (Crashed log).log](https://github.com/godotengine/godot/files/10924164/godot.Crashed.log.log)

[godot (Normal exit log).log](https://github.com/godotengine/godot/files/10924179/godot.Normal.exit.log.log)

For the moment this issue seems to be able to be worked around by setting rendering/shader_compiler/shader_cache/enabled to false in the advanced Project Settings.

### Steps to reproduce

Because of the very specific nature of this crash the Minimal Reproduction Project may not be enough to recreate the crash. I can provide further files necessary, but figured a packaged executable version would be frowned upon.

Export the project to a Windows 10 build without DEBUG enabled. Run the project once to create the AppData files and populate the shader_cache folder therein.

Shut down the program normally.

The mostly reliable way to reproduce the crash from there for me is to replace the generated save_file_4.tres in the app_userdata folder with the save_file_4.tres provided in the ZIP file instead.

Finally, launch the application again, optionally with verbose logging enabled, click the "Display all Tasks" checkbox in the upper right corner, and then uncheck the "Example List" checkbox in the upper left. The program ought to hang for a moment and then crash.

### Minimal reproduction project

[Taskeeper Project.zip](https://github.com/godotengine/godot/files/10924362/Taskeeper.Project.zip)

**Comment by akien-mga** [comment]
Can you still reproduce this in 4.0.3 and 4.1-beta3 or later?

**Comment by clayjohn** [comment]
Closing due to lack of response. We can re-open if OP or someone else confirms that this is still an issue
