### ISSUE TITLE
Editor screen is a dark screen

### ISSUE THREAD

**Issue by dragon3025** [godotengine/godot#74613]
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Windows 10, Intel(R) UHD Graphics 360, Graphics Driver Version: 23.30.16.4973

### Issue description

The project selection screen works fine, but when enter a project for editing, the entire window is dark.

### Steps to reproduce

Create a new project or select a project for editing.

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
What renderer are you selecting when you create the project? It sounds like your system may not support Vulkan, in which case you would need to select the "gl_compatibility" renderer

**Comment by dragon3025** [comment]
Okay, I had it to "Foward+". Setting it to "Compatibility" fixed it.

If in the future, I accidentally switched it to "Foward+" someday, how do I switch it back without being able to access the compatibility menu in the editor?

**Comment by clayjohn** [comment]
> If in the future, I accidentally switched it to "Foward+" someday, how do I switch it back without being able to access the compatibility menu in the editor?

You can add the following to your project.godot file:

```
[rendering]

renderer/rendering_method="gl_compatibility"
```
