### ISSUE TITLE
SubViewport is black when CanvasGroup (with child with texture) as child and SubViewportContainer 40x40px or less

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#74622]
### Godot version

4.0

### System information

win 11

### Issue description

I made a character with a skeleton2d and added it as a child of a subviewport. The viewport became black. When I remove all the skeleton2d and polygons, the viewport becomes the correct color.

### Steps to reproduce

Make skeleton2d, add as child of viewport

### Minimal reproduction project

https://github.com/ShatReal/Pixel-Character-Creator/tree/ad3054d8272c7f755bfc84ef06d13ec32e8077ef

**Comment by ShatReal** [comment]
Nevermind, it appears that the issue is because of Polygon2D? I still don't know why though.

**Comment by ShatReal** [comment]
It goes away when i set the size of the subviewportcontainer to be bigger than 40x40. I really don't know what's going on here.
