### ISSUE TITLE
Crashes when baking Lightmap on unsaved Scene with only LightmapGi Node

### ISSUE THREAD

**Issue by TerraDev64** [godotengine/godot#74625]
### Godot version

4.0 Stable

### System information

Windows 11, Nvidia RTX 3070ti, Ryzen 2600. Driver Version: 531.18, Vulkan

### Issue description

Baking a Lightmap on a Scene that isn't Saved and only has the LightmapGi node itself inside crashes the editor.

I'm not sure how to provide Error Logs, because I don't know where to find them.
(There aren't any log files in ```C:\Users\USERNAME\AppData\Roaming\Godot\app_userdata\projectTest```, I'm not sure if the crash logs are saved there though.)

### Steps to reproduce

1: Open a new Scene that is using the LightmapGi as the Base Node (don't save the Scene!)
2: Press the "Bake Lightmaps" button
3: Editor crashes.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
When trying to bake lightmaps in a scene that wasn't saved yet, I get this dialog:

![image](https://user-images.githubusercontent.com/180032/224167075-a8672634-841b-4b64-9ead-8691c4ddd886.png)

**Comment by TerraDev64** [comment]
This is a bit out of topic, but how do I find those Crash Logs?
Would be good to know, for next time, when I open a new Issue. @Calinou
