### ISSUE TITLE
Some problem on FileDialog

### ISSUE THREAD

**Issue by littlexfish** [godotengine/godot#74635]
### Godot version

4.0 stable

### System information

Windows 10, Vulkan, NVIDIA GeForce GTX 1080 (31.0.15.3118)

### Issue description

There have some problems when use filter on FileDialog.
The path I get if using filter, it will contain useless string after the path, also, in dialog, I switch the filter to NOT "All Files" will not show any file on the file list. 
About the useless string, I found that the string always is the string of file extension without the first character. For example, if there has a path we should get is "C:/Users/User/Desktop/test.txt", if I use the filter, I will get the path like "C:/Users/User/Desktop/test.txtxt"

### Steps to reproduce

Add a FileDialog with some filters.
Open the dialog, choose the filter to one of the filters and input file name to save file like the other program.
Get the path to save/open.

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/10928394/Test.zip)

**Comment by Calinou** [comment]
Can you reproduce this on 3.5.2?

**Comment by nongvantinh** [comment]
The MRP project is not working. I changed the filter from `txt` to `*.txt` and it works like a charm.
![before](https://user-images.githubusercontent.com/53887662/224463383-e550b460-cb48-4361-970a-a00c9c13b8e9.png)
![after](https://user-images.githubusercontent.com/53887662/224463385-316d05b4-93db-4fcb-aada-daf73aba7b39.png)

**Comment by littlexfish** [comment]
Thanks, it works, all problems on the FileDialog I found are solved. Just a little star.
