### ISSUE TITLE
It is not possible to compile for web

### ISSUE THREAD

**Issue by GrandFunkR** [godotengine/godot#7464]
**Operating system or device - Godot version:**
linux - godot 3.0-alpha

**Issue description** (what happened, and what was expected):
according to docs seems to be possible to compile for web:
http://docs.godotengine.org/en/stable/reference/compiling_for_web.html

but

$ scons platform=javascript tools=no target=release
scons: Reading SConscript files ...
No valid target platform selected.
The following were detected:
        android
        server
        haiku
        x11
        windows

**Steps to reproduce:**
clone head git
scons platform=javascript tools=no target=release

**Link to minimal example project** (optional but very welcome):

**Comment by karroffel** [comment]
2.1 / 2.2 was able to compile for web, this is the unstable 3.0-alpha now. The new renderer hasn't been made compatible with web export yet.

**Comment by eska014** [comment]
Building 3.0 should work now, but doesn't run yet.
Anyway, if you get ` No valid target platform selected` for `platform=javascript`, you probably didn't set the `EMSCRIPTEN_ROOT` environment variable. Please read the instructions: http://docs.godotengine.org/en/latest/reference/compiling_for_web.html

**Comment by akien-mga** [comment]
With #8191 it seems to build and run, so closing.

**Comment by berserk82** [comment]
EMSCRIPTEN_ROOT variable could not be set to what it's explained in the docs, because that folder doesn't exist anymore.
If the emscripten version needed is different than latest, please tell me which version do I need (I'm using Windows), otherwise, point me to the right folder to put into the environment variable to.

Thanks in advance.

**Comment by berserk82** [comment]
P.S.: Nevermind, I've been able to manage it. Just set EMSCRIPTEN_ROOT to the root directory in which you installed Emscripten.
