### ISSUE TITLE
Android export gradle version issue

### ISSUE THREAD

**Issue by the-token-studios** [godotengine/godot#74646]
### Godot version

3.5.2 stable

### System information

Windows 11

### Issue description

I recently tried to migrate one of the projects from 3.5.1 to 3.5.2. I encountered the following error while exporting to android.

![image](https://user-images.githubusercontent.com/32641353/223968812-90db1b68-5553-48ca-a5e4-cbb0d39b6571.png)

This happened because of the issue https://github.com/godotengine/godot/pull/68497. 

In this, Gradle version is moved up to 7.4 and AGP to 7.2.1. It is nice that some of the earlier warnings went away, but this happened.

Now when I changed the gradle version to 7.4.2 taking a note from the issue https://github.com/godotengine/godot/pull/62615

The error went away. 

It seems there is some incompatibility between AGP 7.2.1 and Gradle 7.4. I suggest moving the Gradle version to 7.4.2, in the next release.

### Steps to reproduce

export project for android using custom build (23-32)

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
Indeed while I had upgraded to Gradle 7.4.2 in #62615, the PR #68497 which was merged eventually only moved us to Gradle 7.4. Was there a specific reason for this or was it an oversight @m4gr3d? I don't remember the details on Gradle + AGP version incompatibilities.

**Comment by m4gr3d** [comment]
> Indeed while I had upgraded to Gradle 7.4.2 in #62615, the PR #68497 which was merged eventually only moved us to Gradle 7.4. Was there a specific reason for this or was it an oversight @m4gr3d? I don't remember the details on Gradle + AGP version incompatibilities.

I think it was an oversight; we should be able to bump it to 7.4.2
