### ISSUE TITLE
FTBFS with GCC 13

### ISSUE THREAD

**Issue by marxin** [godotengine/godot#74647]
### Godot version

4.0

### System information

Linux

### Issue description

Please cherry-pick https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/commit/29d492b60c84ca784ea0943efc7d2e6e0f3bdaac in order to support the upcoming GCC 13 compiler.

### Steps to reproduce

Build with gcc 13.

### Minimal reproduction project

...

**Comment by marxin** [comment]
The build failure is:
```
[  263s] In file included from thirdparty/vulkan/vk_mem_alloc.cpp:7:
[  263s] thirdparty/vulkan/vk_mem_alloc.h: In function 'void VmaUint32ToStr(char*, size_t, uint32_t)':
[  263s] thirdparty/vulkan/vk_mem_alloc.h:2821:9: error: 'snprintf' was not declared in this scope
[  263s]  2821 |         snprintf(outStr, strLen, "%u", static_cast<unsigned int>(num));
[  263s]       |         ^~~~~~~~
[  263s] thirdparty/vulkan/vk_mem_alloc.h:2655:1: note: 'snprintf' is defined in header '<cstdio>'; did you forget to '#include <cstdio>'?
[  263s]  2654 |     #include <mutex>
[  263s]   +++ |+#include <cstdio>
[  263s]  2655 | #else
```

**Comment by marxin** [comment]
With the patch applied, I can confirm godot `4.0` builds with GCC 13. Good job guys!

**Comment by akien-mga** [comment]
Awesome, thanks for the headsup! I'll backport the fix.
