### ISSUE TITLE
Crash On Project Loading on Fedora 35

### ISSUE THREAD

**Issue by floatyHorizonOfficial** [godotengine/godot#74657]
### Godot version

4.0

### System information

Linux Fedora 35

### Issue description

I can load into the project manager but that's as far as i can go. Whenever i want to load into a project, even if it was created in 4.0, the engine crashes.

### Steps to reproduce

Just load a project

### Minimal reproduction project

The default template is enough.

**Comment by floatyHorizonOfficial** [comment]
adding `scons dev_build=yes` gave me this:
Godot Engine v4.0.stable.official.92bee43ad - https://godotengine.org
OpenGL API 3.3.0 NVIDIA 390.154 - Compatibility - Using Device: NVIDIA Corporation - GeForce GT 610
 
Editing project: /home/[REAL NAME]/[REAL NAME] Godot/Games/Spooky
Godot Engine v4.0.stable.official.92bee43ad - https://godotengine.org
Vulkan API 1.2.195 - Forward+ - Using Vulkan Device #0: Unknown - llvmpipe (LLVM 13.0.0, 128 bits)
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:70)

**Comment by akien-mga** [comment]
> `Godot Engine v4.0.stable.official.92bee43ad - [godotengine.org](https://godotengine.org/)`

This means you're still running the official 4.0-stable build, not the one you compiled with `scons dev_build=yes`.

**Comment by maujin111** [comment]
I tried to open it on Fedora 37 and had the same issue. Here is the console log when open a project

```
OpenGL API 3.3 (Core Profile) Mesa 22.3.2 - Compatibility - Using Device: nouveau - NVA8
 
WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:70)
/usr/include/c++/12/bits/stl_deque.h:1385: std::deque<_Tp, _Alloc>::const_reference std::deque<_Tp, _Alloc>::operator[](size_type) const [with _Tp = nv50_ir::ValueRef; _Alloc = std::allocator<nv50_ir::ValueRef>; const_reference = const nv50_ir::ValueRef&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
```

**Comment by akien-mga** [comment]
@maujin111 You seem to be using the open source Nouveau driver for Nvidia. I'm afraid it's still not usable in production nowadays. I'm surprised it can't even handle OpenGL 3.3 Core Profile properly, but Nvidia really isn't helping the open source community.

**Comment by floatyHorizonOfficial** [comment]
Pardon for the late response. I did missread when i should've used `scons dev_build=yes`. So i did a run with `inxi -CSG` and got this:
`
Godot Engine v4.0.stable.official.92bee43ad - https://godotengine.org
OpenGL API 3.3.0 NVIDIA 390.154 - Compatibility - Using Device: NVIDIA Corporation - GeForce GT 610

Editing project: /home/[NAME]/[NAME] Godot/Spooky
Godot Engine v4.0.stable.official.92bee43ad - https://godotengine.org
Vulkan API 1.2.195 - Forward+ - Using Vulkan Device #0: Unknown - llvmpipe (LLVM 13.0.0, 128 bits)
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:70)`

**Comment by floatyHorizonOfficial** [comment]
Has this been forgotten?

**Comment by floatyHorizonOfficial** [comment]
Alright, thanks
