### ISSUE TITLE
Editor preview of the contents of a TabContainer is incorrect for every tab except the first one

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#74653]
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Linux

### Issue description

Creating a tabbed interface for options, the Y position for elements inside the Audio tab (second tab) appear to be incorrect in comparison to the Graphics tab (first tab).

Compare:
![01-Graphics_tab_in_editor](https://user-images.githubusercontent.com/324679/224012848-6848fe8f-7757-4ed8-a166-ca2e3b13b99a.png)
![02-Audio_tab_in_editor](https://user-images.githubusercontent.com/324679/224012875-2b1c11a9-2212-4e12-9db8-b891cd68d7a3.png)

That said, at runtime these appear to be in the correct positions.

Compare:
![03-Graphics_tab_runtime](https://user-images.githubusercontent.com/324679/224012995-7aef63f2-9e40-4470-a4ab-f75a82b9148f.png)
![04-Audio_tab_runtime](https://user-images.githubusercontent.com/324679/224013014-ce79e2a4-946f-4caa-a4a1-91d7545aa211.png)

### Steps to reproduce

A minimum scene tree:
```
Control
    TabContainer
        Control
            Label
        Control
            Label
```

Where the labels have the same position according to Layout/Transform.

[74653_demonstrator.zip](https://github.com/godotengine/godot/files/10931078/74653_demonstrator.zip) should be a minimal reproduction.

**Comment by YuriSizov** [comment]
Yeah, and I'm pretty sure this was reported already, but I can't find it. So we can keep this one for now.

**Comment by KoBeWi** [comment]
The minimal project is empty.

**Comment by kitbdev** [comment]
Here is an MRP:

[TabContainer_74653.zip](https://github.com/godotengine/godot/files/14073474/TabContainer_74653.zip)

Steps:
1. Open control.tscn.
2. Use the toggle visibility button in the Scene dock to show the ColorRect or the TextureRect.
3. The ColorRect doesn't show at all, and the TextureRect appears at the wrong position and scale.
4. Use the TabContainer's current tab property in the Inspector to see what they should look like.
5. After that, they will be correct when changing visibility, so close and reopen the scene to reproduce again.
