### ISSUE TITLE
Mismatch between AABB and mesh when mesh and skeleton don't have the same transform

### ISSUE THREAD

**Issue by SlugFiller** [godotengine/godot#74656]
### Godot version

Master (9b9bb418cb1137e69b5131ec9fa7b41c0396db28)

### System information

Irrelevant

### Issue description

Somewhat of a sequel to #71953. Sorry in advance for doing this report half-energy. I'm not sure if it counts as a bug, or is simply "You're not supposed to do that", i.e. undefined behavior.

Basically, if a mesh and a skeleton have mismatching transforms, in rendering, the mesh seems to attach to the skeleton based on the global position. For instance, if a skeleton's bone has rotation, and the mesh is moved in the direction that the bone's rest pose points at, the skeleton-transformed mesh would move in the direction that the bone's current pose points at. Basically, as if each of the mesh's vertices was moved.

Meanwhile, the AABB calculation seems to assume that the mesh and skeleton have the same transformation. That is, it attaches to the skeleton based on the positions of the vertices within the mesh, and not based on the global positions.

I've confirmed this in 2D, but it's likely present in 3D as well, since they use common code. At least for AABB.

### Steps to reproduce

1. Have a mesh (MeshInstance2D, MeshInstance3D, Polygon2D) with a skeleton (Skeleton2D, Skeleton3D) attached.
2. Move the skeleton to a non-rest pose
3. Move the the mesh's origin to being away from the skeleton.
4. Do some action that relies on AABB. e.g occlusion culling, canvas group, etc.

### Minimal reproduction project

Left as an exercise to the reader. I'm not even sure if this is unintended behavior, since skeleton and mesh with different transforms doesn't sound like something a user is normally supposed to do.

For the 2D case, it's possible to just take the project from #71953 and use the move tool to move the polygon.

**Comment by SlugFiller** [comment]
Too lazy to MRP, have an image:
![image](https://user-images.githubusercontent.com/5435495/224202261-e5fb2901-7a70-4c26-8429-00b5ee40b350.png)

The `Polygon2D` inside `CanvasGroup2` is translated 800px along the x axis. The associated bone gives a rotation of 45 degrees. These numbers are arbitrary, obviously. The skeleton is at 0,0. The drawing interprets it as the polygon first being moved, then rotated by the bone. The AABB calculation interprets it as being first rotated by the bone, then moved.

Incidentally, when moving the polygon, the rendering originally matches the AABB. Only when resizing the window, it suddenly "remembers" that it is wrong, and draws it in a way that doesn't match the AABB.

Here's an example of it looking correct:
![image](https://user-images.githubusercontent.com/5435495/224202517-bad2342f-05d4-4fa6-947c-b4fdc1378971.png)
Resizing the window causes it to jump to incorrect position shown above.

This is why I'm not sure whether the bug is in the AABB, or the skeleton shader.

> or if you are just misusing the skeleton

It's fairly likely I'm misusing the skeleton.

**Comment by Zoomulator** [comment]
I seem to have the same problem. Tested with 4.0.1-rc2 that includes the recent https://github.com/godotengine/godot/issues/71953 fix, but it didn't fix it for me.

My Polygon2D nodes are in fact translated differently to the Skeleton2D, but it hardly seems like I'm abusing the skeleton system. If that's the case, there's no indication that I should be doing things differently. The animation works as intended, except for the unexpected AABB culling.

I tried setting the Polygon2D:Offset property to the transform's offset and resetting the transform to be the same as the skeleton, but that offset isn't reflected in the Polygon2D UV editor so there's no (sane) way of adjusting the points and UVs in my case.

It seems rather limiting if this is the intended behavior, if you (like me) try to put multiple components of a character into sprite sheet. The MRP below only shows a pair of legs, but let's imagine there are overlapping parts in an armor set that aren't just a single continuous shape. I would need to provide a separate texture for each overlap if I can't use the transform or the texture offset.

I've reduced my project to the following MRP. Rotate a bone or start the animation, then pan the view, zoom in and out and the polygons will disappear at some rotations.
[Polygon2DBug.zip](https://github.com/godotengine/godot/files/11009594/Polygon2DBug.zip)

**Comment by Zoomulator** [comment]
I've created a brute force workaround if anyone needs it. Add the following script to any Polygon2D nodes affected by this bug.
`@tool
extends Polygon2D

func _process(_delta):
	var use_custom_rect = true;
	var rect = get_viewport_rect();
	RenderingServer.canvas_item_set_custom_rect(get_canvas_item(), use_custom_rect, rect)
`
