### ISSUE TITLE
Conversion Tool: Collision Layer Names Stripped

### ISSUE THREAD

**Issue by keithrdavis** [godotengine/godot#74662]
### Godot version

4.0

### System information

MacOS 13.2.1/M2

### Issue description

Collision layer names are stripped after running v4.0 conversion tool on a v3.5.1 project.

### Steps to reproduce

Run a v3.5.1 project with collision layer names through the v4.0 conversion tool.

### Minimal reproduction project

N/A

**Comment by keithrdavis** [comment]
MRP attached...
[ConversionToolBugs.zip](https://github.com/godotengine/godot/files/10933351/ConversionToolBugs.zip)

**Comment by AThousandShips** [comment]
This is not reproducible in the most recent version so has been fixed.

**Comment by AThousandShips** [comment]
Though I'm not sure why it would have been a problem as the property should be the same in 3.x and 4.0

**Comment by keithrdavis** [comment]
Thank you...

**Comment by akien-mga** [comment]
No worry! Thanks for reporting all these issues.
