### ISSUE TITLE
Conversion Tool: Custom KeyBindings Stripped 

### ISSUE THREAD

**Issue by keithrdavis** [godotengine/godot#74661]
### Godot version

4.0

### System information

MacOS 13.2.1/M2

### Issue description

Any custom key bindings are stripped after running the conversion tool on a v3.5.1 project imported with v4.0.

### Steps to reproduce

Run a v3.5.1 project with custom key bindings through the v4.0 conversions tool.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Do you mean the keyboard codes? For example arrow keys?

**Comment by keithrdavis** [comment]
Yes, keyboard codes. I had set some keys like "A" and they are not "bound".

**Comment by AThousandShips** [comment]
Then it should be fixed by #74237, if you mean the action map.

**Comment by keithrdavis** [comment]
Thank you!

**Comment by AThousandShips** [comment]
If you are able to compile the engine please confirm that this fixes it, otherwise you should attach a MRP to make this easier to test, this goes for most of your issues relating to the conversion.

**Comment by keithrdavis** [comment]
MRP attached...
[ConversionToolBugs.zip](https://github.com/godotengine/godot/files/10933300/ConversionToolBugs.zip)

**Comment by keithrdavis** [comment]
Cool...

**Comment by akien-mga** [comment]
Fixed by #74237.
