### ISSUE TITLE
Conversion Tool: Font Settings Not Honored

### ISSUE THREAD

**Issue by keithrdavis** [godotengine/godot#74664]
### Godot version

4.0

### System information

MacOS 13.2.1/M2

### Issue description

After running a v3.5.1 project with labels using custom font outlines and colors through the v4.0 conversion tool, only the font and size are honored.

### Steps to reproduce

Run a v3.5.1 project with a label using custom (Theme Override) font colors and outline sizes through the v4.0 conversion tool.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Duplicate of #66052
