### ISSUE TITLE
Autocomplete no longer infers type from `is` operator

### ISSUE THREAD

**Issue by Haydoggo** [godotengine/godot#74687]
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Windows 10

### Issue description

Using the `is` operator does not allow autocomplete to infer the type of a variable. See steps to reproduce for an example.
This functionality was last working in rc2 and broken in rc3. I suspect this was caused by #73489, but have not confirmed.

### Steps to reproduce

``` gdscript
extends Node

func _input(event: InputEvent) -> void:
	if event is InputEventKey:
		event.keycode
```
Members of `InputEventKey` such as `keycode` are no longer shown in autocomplete list.

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
CC @vonagam @vnen
