### ISSUE TITLE
Shader array uniforms dont always update in editor correctly

### ISSUE THREAD

**Issue by vvdashdash** [godotengine/godot#74680]
### Godot version

4.0 stable

### System information

Forward+ renderer, rx470

### Issue description

Creating a uniform array in shader and then changing its value in inspector will lock the variable type for some reason

### Steps to reproduce

1. Create a shader with something like uniform vec3[10] whatever;
2. Add something to the array
3. Change the array to something else, maybe vec4
4. Uniform will still show as vec3 in editor

seems to happen with all datatypes though, ive currently got it stuck on int array somehow even though it is clearly a vec4
reloading shader/scene/engine or even changing the variable name doesnt fix it, annoying

### Minimal reproduction project

trivial recreation

**Comment by vvdashdash** [comment]
I just looked into the scene file text and I think the issue stems from the lack of a PackedVector4Array type. PackedVector3 exists and works fine for vec3 if I set it to that

**Comment by akien-mga** [comment]
Reopening as #76438 was reverted.
