### ISSUE TITLE
scons 4.5.1 reports TypeError in platform/linuxbsd/detect.py line 310

### ISSUE THREAD

**Issue by cunyx** [godotengine/godot#74683]
### Godot version

godot-4.0-stable

### System information

openSUSE Tumbleweed

### Issue description

Since update of scons from 4.4.0 to 4.5.1 building fails with

scons: Reading SConscript files ...

TypeError: sequence index must be integer, not 'slice':
  File "/home/abuild/rpmbuild/BUILD/godot-4.0-stable/SConstruct", line 539:
     detect.configure(env)
  File "/home/abuild/rpmbuild/BUILD/godot-4.0-stable/./platform/linuxbsd/detect.py", line 310:
     env.ParseConfig("pkg-config libpulse --cflags --libs")
  File "/usr/lib/python3.10/site-packages/SCons/Environment.py", line 1773:
     return function(self, self.backtick(command), unique)
  File "/usr/lib/python3.10/site-packages/SCons/Environment.py", line 1767:
     return env.MergeFlags(cmd, unique)
  File "/usr/lib/python3.10/site-packages/SCons/Environment.py", line 1095:
     for v in orig[::-1]:

### Steps to reproduce

build log at

https://build.opensuse.org/package/show/openSUSE:Factory/godot

may help.

command was

scons -j8 progress=no verbose=yes udev=yes use_lto=1 use_static_cpp=no 'CCFLAGS=-O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g' system_certs_path=/var/lib/ca-certificates/ca-bundle.pem use_sowrap=no builtin_certs=no builtin_libogg=no builtin_libtheora=no builtin_libvorbis=no builtin_libwebp=no builtin_pcre2=no builtin_miniupnpc=no builtin_wslay=no builtin_freetype=no builtin_glslang=no builtin_graphite=no builtin_harfbuzz=no builtin_libpng=no builtin_mbedtls=no builtin_zlib=no builtin_zstd=no platform=linuxbsd target=editor

### Minimal reproduction project

failure during godot build

**Comment by akien-mga** [comment]
Yes, this is a SCons regression: https://github.com/SCons/scons/issues/4321

We can keep this issue open for documentation until 4.5.2 is released with a fix.

**Comment by cunyx** [comment]
That was quick!
I'll try the fix.
Thank you!

**Comment by cunyx** [comment]
With SCons 4.5.2 and godot 4.0.2 it builds again without patching detect.py.

Thanks!

**Comment by akien-mga** [comment]
Indeed this was fixed in SCons 4.5.2.
