### ISSUE TITLE
Memory leak when running a barebones project from editor

### ISSUE THREAD

**Issue by atrefonas** [godotengine/godot#74698]
### Godot version

v4.1.dev (c1128e911ccd6f1e8)

### System information

macOS Monterey, version 12.4

### Issue description

Hello,

When I create a very simple barebones project with only a Node3D, and run it via the editor, I noticed the memory usage trends up over time even though nothing is happening in the game. I guess this is a memory leak? If not what is the explanation? Thanks

edit: Could it be because Godot doesn't clean up memory right away and the garbage collection happens at a later time?

![image](https://user-images.githubusercontent.com/72869083/224217228-d905c9d6-f15b-4634-9071-0ae26403b686.png)

### Steps to reproduce

Create a new project and add a Node3D. Observe the memory usage slowly go up over time.

### Minimal reproduction project

[memtesting.zip](https://github.com/godotengine/godot/files/10938057/memtesting.zip)

**Comment by ShlomiRex** [comment]
I'm running it on my macbook M1, and its 1GB with no change over time.
What macbook are you using?

**Comment by gilcel** [comment]
I had exactly the same memory problem with Godot 4.0stable on a "Mac Mini Intel 2018" with macOS Ventura 13.2.1, 16GB RAM.

For me it happened when importing an old 3.5.1 project (which was empty).
Opening the old empty project and then leaving the window open takes about >85% CPU time....and then the memory leak grows and grows everything 2-3 seconds, the app becomes unresponsive and had to cancel quit Godot 4.0stable.

Creating a new project or importing an old project with some scripts etc. seems to work for now...no mem leaks.

**Comment by ShlomiRex** [comment]
> 

Unfortunatly I don't have this hardware and I can't replicate it :(

**Comment by atrefonas** [comment]
I have a MacBook Pro (14-inch, 2021)

I think most likely after talking to others it's not a leak, but the way
the OS manages memory. Freed data probably isn't wiped out immediately but
during pages or such. I am not an expert here. Curious what others have to
say though. If it's determined to not be a real issue then feel free to
close the ticket.

**Comment by atrefonas** [comment]
> I'm running it on my macbook M1, and its 1GB with no change over time. What macbook are you using? Also, why you have 2 processes with godot editor? It should be 1 <img alt="image" width="966" src="https://user-images.githubusercontent.com/17744127/224259946-5b836c8e-76f0-45de-853d-588a30f34324.png"> Can you post before and after images that show that the editor increases memory usage? Also, what are you doing in the editor itself? If you are doing nothing, the memory usage is the same.

Did you start the game? The editor process does not increase over time, but the game process does. When you start the game there are 2 processes called godot.

**Comment by atrefonas** [comment]
Here are 3 screenshots in sequence:

11:30 AM

<img width="929" alt="Screen Shot 2023-03-10 at 11 29 58 AM" src="https://user-images.githubusercontent.com/72869083/224371097-1a085953-a116-4bf0-ac44-13315143ae3f.png">

11:31 AM
<img width="895" alt="Screen Shot 2023-03-10 at 11 31 25 AM" src="https://user-images.githubusercontent.com/72869083/224371138-d73b2ae5-f216-466e-8532-2a5aa9b5864d.png">

11:32 AM
<img width="850" alt="Screen Shot 2023-03-10 at 11 32 50 AM" src="https://user-images.githubusercontent.com/72869083/224371163-430a2699-ba6c-4b14-a8d9-f30685335706.png">

**Comment by ShlomiRex** [comment]
Testing on macbook air m1, running the game of the project that you uploaded this issue (memtesting.zip)

Before:
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/17744127/224512585-5ff7faa2-ed9b-4820-84ce-fad3fac4e8b4.png">

After 5 minutes:
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/17744127/224512770-500c3bf4-9a1e-4b49-814c-645ce34931e4.png">


Commit im on: c1128e911ccd6f1e8c35646df804d894652a58f1

Maybe try to run profiler in godot to see if it indeed uses more CPU/memory. Not sure, can't replicate. Or check activity monitor statistics on this process

**Comment by atrefonas** [comment]
I did some other testing and it seems like a non-issue. When I free a lot of objects (in a more complicated setup than the example) the memory goes back down. I'm going to close this issue.
