### ISSUE TITLE
[G4 Stable] Physical Lighting Units make viewport too bright

### ISSUE THREAD

**Issue by Rinocrosser** [godotengine/godot#74692]
### Godot version

4.0 Stable

### System information

Windows 11, Ryzen 6800U

### Issue description

For realistic lighting, I needed to light up the scene properly and switched to Physical Lighting Units. It works well with the camera (as you may see in the inspector tab), but the viewport got too bright (even an unlit version).

![image](https://user-images.githubusercontent.com/19660324/224173672-1c835888-cc0c-4fc5-aa38-62dd1b395eef.png)

- I've tried Procedural Sky, Physical Sky, and HDRi — the same result. There are no settings to produce a realistic amount of light and see anything in the viewport.
- The default light value of the directional light is 100000 lux is also insane, lowered it significantly

### Steps to reproduce

Add the environment node, directional light, and some objects, then the camera, and enable physical light units in the settings.

### Minimal reproduction project

[G4_Stable.zip](https://github.com/godotengine/godot/files/10936641/G4_Stable.zip)

**Comment by Rinocrosser** [comment]
This also looks greater than 100 nits in the material settings:

![image](https://user-images.githubusercontent.com/19660324/224177006-a60da063-922b-4d21-bb29-c08de642e813.png)

**Comment by clayjohn** [comment]
Tested the MRP locally, you have a CameraAttributes with appropriate exposure set on the camera, but you don't have one set on the worldenvironment. If you want it to apply to all cameras in the scene, it needs to be applied to the worldenvironment. 

take a look at https://docs.godotengine.org/en/latest/tutorials/3d/physical_light_and_camera_units.html and https://docs.godotengine.org/en/latest/classes/class_cameraattributes.html for more information. Both docs are pretty clear about the need for a CameraAttributes resource to manage exposure.
