### ISSUE TITLE
Editor window stopped updating after baking voxel GI

### ISSUE THREAD

**Issue by LightShade12** [godotengine/godot#74700]
### Godot version

4.0 stable

### System information

Win 10, x64, Nvidia GTX 1650, Driver version 527.41 ,Vulkan

### Issue description

https://user-images.githubusercontent.com/102753608/224232883-1ab79c84-c2de-4d80-8597-aeeb1592de8d.mp4
I'm using forward+ renderer
After hitting bake voxelGI, the window pauses refreshing, but the editor is updating fine. After saving this paused project, it cannot be reopened. The editor is stuck in loading screen when trying to reopen the project, and eventually gives "window is not responding" error.

### Steps to reproduce

-Set up scene is provided(no advanced project rendering settings are modified)
-Hit bake voxel
The baking is probably done but screen doesn't update, the mouse cursor changes show that the editor is updating but the window doesn't display it.

### Minimal reproduction project

[testgi.zip](https://github.com/godotengine/godot/files/10938911/testgi.zip)

**Comment by LightShade12** [comment]
> What happens if you leave it alone for a few minutes?Baking shouldn't take very long, but sometimes the engine appears frozen even though it is hard at work. It would also be good to check the task manager while it appears frozen to see if it is actively working

Hi. I don't think the engine is frozen, as you can see in the video, the cursor and window can be resized ,while the engine editor window doesn't display the update. Moreover in my test I set the voxel subdiv to 64 and the scene is a small Cornell box. Regardless,I will be posting a screenshot of the task manager after hitting bake soon.

**Comment by LightShade12** [comment]
![image](https://user-images.githubusercontent.com/102753608/224302201-33104fe4-bcc7-48ce-9ce8-a16ef0290ec7.png)
![image](https://user-images.githubusercontent.com/102753608/224302408-408a4a5c-4d29-45f6-98ca-8941373d0ce5.png)

**Comment by clayjohn** [comment]
Could you run the engine from the command line and try again? There may be helpful error messages printed to the command line

**Comment by LightShade12** [comment]
![image](https://user-images.githubusercontent.com/102753608/224491019-bafc9a8b-b90c-4ac5-a0f0-14f35d30e53f.png)
This is what i get when i open a scene with baked gi (stuck in loading)

**Comment by LightShade12** [comment]
![image](https://user-images.githubusercontent.com/102753608/224493123-43c5fb78-f5fa-47a6-8541-38a1c4c76a99.png)
![image](https://user-images.githubusercontent.com/102753608/224493175-b7183410-89d3-40b7-987a-9deaca326417.png)
![image](https://user-images.githubusercontent.com/102753608/224493212-e0e056a9-e389-40a0-b3b8-f6a56044c058.png)
all these prints quickly upon closing so i recorded and went frame by frame. sry for bad quality

**Comment by Calinou** [comment]
Consolidating in https://github.com/godotengine/godot/issues/71929.
