### ISSUE TITLE
Panorama texture displays incorrectly in Procedural and Physical sky materials

### ISSUE THREAD

**Issue by aliasPercival** [godotengine/godot#74709]
### Godot version

4.0.stable

### System information

Windows 10, Compatibility, Intel HD Graphics 4400

### Issue description

I am using a Spacescape cubemap converted to panorama with [the tool recommended in the documentation](https://danilw.github.io/GLSL-howto/cubemap_to_panorama_js/cubemap_to_panorama.html) as a texture for different sky materials. It works as intended with PanoramaSkyMaterial:
![panoramasky](https://user-images.githubusercontent.com/49611994/224272250-fb62a049-9672-47c6-876b-848278ae2597.JPG)
The description of sky_cover property of ProceduralSkyMaterial states it should be a texture 'similar to PanoramaSkyMaterial'. First, it is impossible to use an actual PanoramaSkyMaterial resource as it is not a texture, the wording is ambiguous. Second, the texture that is compatible with the PanoramaSky is displayed incorrectly. It is stretched at the top of y axis and has a noticeable seam between the positive y axis and negative z axis:
![proceduralsky](https://user-images.githubusercontent.com/49611994/224272274-220eac68-5b4b-4368-9525-c7a82da48fc5.JPG)
The same happens with the night_sky texture of PhysicalSkyMaterial:
![physicalsky](https://user-images.githubusercontent.com/49611994/224272264-f0edf185-3a45-48f3-ae1c-d254f5875042.JPG)

### Steps to reproduce

Open panorama.tscn, procedural.tscn and physical.tscn for respective examples

### Minimal reproduction project

[sky_issue.zip](https://github.com/godotengine/godot/files/10940684/sky_issue.zip)

**Comment by clayjohn** [comment]
Looks like ProceduralSkyMaterial and PhysicalSkyMaterial use filtering with mipmaps by default while PanoramaSkyMaterial uses filtering without mipmaps. I'll make a PR right away

**Comment by aliasPercival** [comment]
As of now, disabling ```mipmaps/generate``` for the texture in the Import tab resolves this
