### ISSUE TITLE
MenuBar property exports as wrong type

### ISSUE THREAD

**Issue by 20milliliter** [godotengine/godot#74705]
### Godot version

4.0.stable

### System information

Windows 10

### Issue description

The MenuBar node's `start_index` property exports as a boolean in the editor, when [it is actually an integer](https://docs.godotengine.org/en/4.0/classes/class_menubar.html).

### Steps to reproduce

1. Create a MenuBar control node.

### Minimal reproduction project

N/A

**Comment by YuriSizov** [comment]
Yep, it's a typo here:

https://github.com/godotengine/godot/blob/c1128e911ccd6f1e8c35646df804d894652a58f1/scene/gui/menu_bar.cpp#L669
