### ISSUE TITLE
Sprite3D Alpha Cut glitch when set to Opaque Pre-Pass

### ISSUE THREAD

**Issue by PapaCheese** [godotengine/godot#74719]
### Godot version

4.0 stable

### System information

windows 10, vulkan forward+, GeForce GTX 1080, Intel i7-7700

### Issue description

Been trying to imitate Cult Of The Lamb's style, when i move around the level sometimes the character's sprite lowers in quality, seems like it changes its alpha cut after it passed the floor's sprite half way.
All my Sprite3Ds are set to Alpha Cut: Opaque Pre-Pass because it looks best.
It works fine with Alpha Cut set to 'Discard' or 'Alpha Hash' on either the character or the floor but the cut is too harsh on those.

https://user-images.githubusercontent.com/55656526/224334065-127ee835-b2e1-4d27-ba46-a4e9f69407d0.mp4

https://user-images.githubusercontent.com/55656526/224334071-553a958a-b972-4195-9edb-186718069cb9.mp4

### Steps to reproduce

Create 2 Sprite3Ds and set both to Alpha Cut: Opaque Pre-Pass.
Set one's Axis to Y-Axis and make it bigger so it's a floor.
Set the camera to look at the standing sprite and have the floor behind it.
Move the sprite around. 

### Minimal reproduction project

[Opaque Prepass minimal proj.zip](https://github.com/godotengine/godot/files/10942714/Opaque.Prepass.minimal.proj.zip)

**Comment by clayjohn** [comment]
This looks like an alpha sorting issue. Is the point where things break when the Sprite3D passes the origin of the floor?

Remember, for rendering transparent objects they are sorted back to front based on their position. So you can end up with sorting issues when you have larger objects close to small objects. You can use the [``sorting_offset``](https://docs.godotengine.org/en/latest/classes/class_visualinstance3d.html#class-visualinstance3d-property-sorting-offset) to adjust the sort position and ensure things sort how you want them

**Comment by PapaCheese** [comment]
yep that fixed it, thanks a lot :)

**Comment by PapaCheese** [comment]
@[clayjohn](https://github.com/clayjohn) thanks for the help :),
But I still get some visual glitches.
The robot's jaw is jittering between the front and the back of the head sprite.
movement sort of activates the glitch.
the heads sorting offset is set to 51 and the jaw is set to 52
and the jaw's z position is set to 0.016 so its a little in front

you can also see the glitch happening on the bunny's belt.

https://user-images.githubusercontent.com/55656526/232887708-f73a97c6-dc62-4832-9fcb-26f7e03db5d2.mp4


the camera is set quite far back in the scene with a low FOV (12 degrees),
bringing it closer resolves the issue,
but I am aiming for an almost orthogonal perspective and there is no option to increase the camera's sensor size,
so i set it to be far from the player.
this also caused some shadows issues but its resolvable.

But I do wonder if there are better practices for this kind of style? 


here's the settings for the jaw and head sprites:

![Screenshot 2023-04-18 222038](https://user-images.githubusercontent.com/55656526/232883814-5ba5b5be-f23a-460e-907b-6e7cf90941cc.png)
![Screenshot 2023-04-18 222319](https://user-images.githubusercontent.com/55656526/232883863-5508c438-da7d-4da1-b860-77f1ba017d6d.png)
