### ISSUE TITLE
Viewport.set_input_as_handled() doens't block Input autoload checks

### ISSUE THREAD

**Issue by eh-jogos** [godotengine/godot#74716]
### Godot version

4.0 stable

### System information

Manjaro Linux using i3, Foward+

### Issue description

If I have any input checks on physics process using Input autoload, I can use Viewport.set_input_as_handled() all I want and they'll never be blocked.

For example, in this MRP scene:
![image](https://user-images.githubusercontent.com/13070158/224316430-8faf13e7-733b-4707-8546-2dd180ab6b62.png)

this is the output of the MRP when pressing anything while the InputBlocker is disabled:
![image](https://user-images.githubusercontent.com/13070158/224316359-89afd8f1-aab4-4220-bb15-71c3908b2727.png)

Node2D reports that `_uhandled_input` was reached and prints the event, and `_physics_process` also reports that anything was pressed using `Input.is_anything_pressed()` to check for it.

This is the output after InputBlocker is enabled:
![image](https://user-images.githubusercontent.com/13070158/224316844-24e6a081-e41c-4104-9bee-33dc3f10d72e.png)

Input blocker correctly reports blocking the input, Node2D correctly doesn't report anything on  `_unhandled_input` as nothing reached there, but `_physics_process` keeps seeing the input. 

Is this expected? For me at least, I was expecting `Input` to not recognize any input as well.

### Steps to reproduce

Call `get_viewport().set_input_as_handled()` somewhere while you're also doing check using `Input` autoload either on `_physics_process` or `_process`

### Minimal reproduction project

[viewport_set_input_as_handled.zip](https://github.com/godotengine/godot/files/10942073/viewport_set_input_as_handled.zip)

Just play the scene, experiment with pressing any keyboard key while toggling Showing or Hiding the InputBlocker

**Comment by AThousandShips** [comment]
`is_anything_pressed` is not related to the `set_input_as_handled`, that only affects the transmission of the event, not info if the event is pressed or not

**Comment by eh-jogos** [comment]
Yes, but this also happens with Input.get_vector(), which was how I originally found this behavior in my project

**Comment by eh-jogos** [comment]
No, what I mean is, what I expected was for get_vector to return `Vector2.ZERO` as all the actions that it checks should have been handled in the InputBlocker when `get_viewport().set_input_as_handled()` gets called, and by the time Node2D asks `Input` for the vector of those actions. 

But it will return the same vector as the actions pressed, "ignoring" `get_viewport().set_input_as_handled()`. Is this the intended behavior? Is there a way to check if the actions Input autoload is reporting have been handled already or not?

**Comment by AThousandShips** [comment]
Oh, then I understand.

The `set_input_as_handled` only controls if input events should be forwarded to the next control or to `_unhandled_input`, the `Input` singleton is not affected by it, as far as I know, and this is by design.

The `_input` and `_unhandled_input` functions are separate, the `Input` singleton handles more "low level" input things unrelated to the GUI and similar.

**Comment by eh-jogos** [comment]
In my project I was able to work it out by moving the `Input.get_vector()` to `_unhandled_input` and saving it's return value to a member variable that is used by  `_physics_process`.

I guess if I needed to keep it in _physics_process my InputBlocker would have to emit some Event signal to tell the player to `set_physics_process(false)`

Since this is intended behavior maybe add a note about it in `Input` autoload documentation? Since it only says that it is a singleton that deals with inputs, I thought `set_input_as_handled` would apply to it.

**Comment by AThousandShips** [comment]
That makes sense, and sure that might be a thing to indicate, but the `Viewport` documentation says:
> Stops the input from propagating further down the [SceneTree](https://docs.godotengine.org/en/stable/classes/class_scenetree.html#class-scenetree).

Are you wanting to block a specific input event, or just input in general? If you want to just stop *any* input you can use a number of methods:
* Pausing
* A global variable indicating input is inactive
* A variable in the player etc. to do the same

But your solution seems to be good for your purposes, but perhaps one of my suggestions can make it simpler while achieving the same result.

I hope you've been helped with your issue, very nice talking to you

**Comment by eh-jogos** [comment]
> That makes sense, and sure that might be a thing to indicate, but the `Viewport` documentation says:
> 
> > Stops the input from propagating further down the [SceneTree](https://docs.godotengine.org/en/stable/classes/class_scenetree.html#class-scenetree).

I guess I didn't understand that `Input` autoload was not related to input propagation in any way before you explained it in this thread, but reading it again now and understanding this, it makes sense.

> Are you wanting to block a specific input event, or just input in general? 

I wanted to block any events but without pausing in this case. This would be for blocking all input on the player or any clickable UI for an ingame cutscene, so I don't really want to pause, just take control away from the player.

I like your suggestions as well! I prefer not to use global variables, so a variable in the player would work really well! 
Thanks a lot for all the explanations and It's also been nice talking to you!
