### ISSUE TITLE
Servers may rarely return an invalid RID 

### ISSUE THREAD

**Issue by lilizoey** [godotengine/godot#74728]
### Godot version

4.0.stable

### System information

Linux 5.10.167-1-MANJARO

### Issue description

After roughly 2-billion calls to `rid_allocate_id()`, if you then make a call to a server that creates and returns a new RID, and no other calls have been made to that function. The server will then return an invalid RID.

Attempting to free this RID will make godot crash without errors, unlike what normally happens when you try to free an invalid RID.

This happens because the function that generates the RID only uses the lower 31 bits of the generated id from `rid_allocate_id`. In combination with an index into the array of elements of that `RID_Owner`. So if you generate `2^31` total ids, it will overflow (without any actual integer overflow happening, as the id is 64 bits long) and become 0. then if the array is empty, the index is 0 as well, so it will generate an rid = 0.

### Steps to reproduce

Call `rid_allocate_id()` until the returned value is `0x7FFFFFFF`. Then make a call (such as `PhysicsServer3D.area_create()`) which will print an error in the console and return an invalid RID.

### Minimal reproduction project

Let the project run, eventually (takes a couple of minutes on my machine) the error will show up and a print message indicating that an invalid RID has been returned.
[repro.zip](https://github.com/godotengine/godot/files/10943606/repro.zip)

**Comment by AThousandShips** [comment]
This should probably have a check when generating, but what are the real world conditions when this would happen?

**Comment by sayaks** [comment]
> This should probably have a check when generating, but what are the real world conditions when this would happen?

i could imagine some long running server that regularly generates one object from a server and frees it soon after could eventually hit this after a while.

**Comment by AThousandShips** [comment]
If you do it once a second it takes 68 years

**Comment by AThousandShips** [comment]
But for completeness the engine should probably crash when generating an ID that is out of the range

**Comment by Bromeon** [comment]
> If you do it once a second it takes 68 years, and I don't think even once a second is a reasonable rate for generating RIDs, think it would be a bad usage of it in that case

If you do it 1000 times a second, it's "only" 25 days. I know it's very hard to imagine why one would run Godot for 25 days _and_ create so many resources, but who knows what Godot will be used for besides just games. With enough users and time, it may eventually happen.

As a real-world example, we had an issue in https://github.com/SFML/SFML/issues/1765, where a clock would overflow after 10-11 days and cause negative readings. We would never have counted with such a scenario, and I'm sure it was not fun to debug for the user.

**Comment by AThousandShips** [comment]
But what kind of resource *can* be created every millisecond? We have to consider that these are resource IDs, tied to things that contain and mange data?

**Comment by sayaks** [comment]
> But what kind of resource _can_ be created every millisecond? We have to consider that these are resource IDs, tied to things that contain and mange data?

it only takes 4 milliseconds to call `PhysicsServer3D.area_create()` 10 000 times, and store the rid in an array.

**Comment by akien-mga** [comment]
In this case I don't think it's too important to know what are valid use cases for this, it's just something that should be fixed.

**Comment by AThousandShips** [comment]
Will open a PR momentarily, going for crashing when reaching the invalid validator because I don't think reusing validators is safe, but if someone can confirm it's safe to do so I can make it roll over instead, but I think the safer way is to go with a crash

**Comment by AThousandShips** [comment]
The crash you're experiencing is caused by a combination of errors:
* Invalid RID being generated
* Invalid RID being treated as owned even if it is not, causing freeing of an object that isn't valid

My PR should fix both
