### ISSUE TITLE
NixOS - Godot fat X11 binary will only display empty window with no rendered content.

### ISSUE THREAD

**Issue by sunnystormy** [godotengine/godot#7472]
**Operating system or device - Godot version:**
NixOS 16.09 - Godot 2.1.1

**Issue description** (what happened, and what was expected):
Created a NixOS package around a generated Godot X11 fat binary (non-fat binaries won't even run), but I only get an empty window.

**Steps to reproduce:**
Make an X11 fat binary and then create a NixOS package around it (in my case, I just exported the "shader materials" demo). Linked ticket with in-depth description below.

**Link to minimal example project** (optional but very welcome):
https://github.com/NixOS/nixpkgs/issues/21743

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
I'm not familiar with NixOS, but I don't see any details about how the binary is being built. The script in https://github.com/NixOS/nixpkgs/issues/21743 references a `shadermats.tar` tarball, but I don't know what it is, what it contains and how it was built, so can't tell much.

I guess it's a binary compiled on another X11 OS, and NixOS's environment does not supply what this binary expects in terms of OpenGL/X11 libraries/versions. It works in Steam as it's basically a Unity 12.04 sandbox. If it's a binary compiled on NixOS itself, but that won't run on the same machine, I'd be interested in details about how it was compiled and what's the command line output.

**Comment by akien-mga** [comment]
Closing as we don't have enough info to provide support.
