### ISSUE TITLE
Very long scripts tend to slow writing down

### ISSUE THREAD

**Issue by Daniel-da-Silva** [godotengine/godot#74733]
### Godot version

3.5.2 and previous versions

### System information

MX Linux, SSD, i5-6500

### Issue description

Hey,

I tend to work on large scripts. When a script gets very long, 10k+ lines scrolling can be laggy (if you use the scrollbar and drag it) and writing new stuff can take considerable amount of time, the inputs are taken but until it shows on screen it can take a second (just write something very fast, especially at the end of the script). It does not happen always but in more than 50% of tries.

I could use an external editor but I would really like to avoid using one.

Edit: Sorry for Closing and Reopening that was not my intention. I wanted to add: I just tested it on Godot 4.0 - the problem is not there, not when using the Forward nor the Compatibility renderer if that helps.

### Steps to reproduce

Work with a large script

### Minimal reproduction project

[Minimal_Project.zip](https://github.com/godotengine/godot/files/10944253/Minimal_Project.zip)

I don't know how to not include the .godot folder but couldn't find one with ls -a. This is a project with 40k lines to test it properly.

Just write something very fast, especially at the end of the script.

**Comment by lawnjelly** [comment]
This is a debug profile but it should give some indication:

![script_editor_profile](https://user-images.githubusercontent.com/21999379/224486218-0eb5c0a7-b491-4712-9384-c1c863ea642f.png)

Looks like a large amount of time searching in `color_region_cache` which is a `Map`.

**Comment by lawnjelly** [comment]
OK with the bug fix above, the syntax highlighting seems no longer a problem, now the editor is fast in the MRP except for parsing, which causes a pause. Here is the new revised profile with the bug fix:

![script_editor_profile3](https://user-images.githubusercontent.com/21999379/224497746-bea2c41d-ece0-4012-bc76-c2bcefab3327.png)

I can immediately see the parsing is using an index operator with a linked list, which is a massive no-no.. :scream:

**Comment by lawnjelly** [comment]
Ok with #74782 we are getting there. Also in the parser there's a fair amount of string compares, which should probably be using hash tables.

Ideally it would be nice to just not parse the entire script, but that might be more hassle than the benefits. Also the parsing would typically be done on a separate thread, I'm not sure why it's stalling the main thread. :thinking:

**Comment by vnen** [comment]
> Ideally it would be nice to just not parse the entire script, but that might be more hassle than the benefits.

This would probably be difficult to implement. Just figuring out what region to parse could lead to issues.

> Also the parsing would typically be done on a separate thread, I'm not sure why it's stalling the main thread.

The current system does not lend itself well for this. It needs the parser info to provide things like error messages and code completion.

I actually have some ideas for this, like caching the parse tree, which would help moving it to a thread as it could have a clear sync point. It would also be possible to cancel the current parsing if another needs to start. This could also help with selective parsing but I'm still not sure if it would be worth it.

Though I don't know when this will be done and I doubt it would be possible to backport to 3.x, at least not with simple cherry-picking.

**Comment by lawnjelly** [comment]
> The current system does not lend itself well for this. It needs the parser info to provide things like error messages and code completion.

Yeah it could be a barrel of worms for a corner case, and with these fixes it should be significantly better for large files anyway.

**Comment by lawnjelly** [comment]
I've just tested with the 3 PRs merged in 3.x, and it's _LOADS_ faster. It's now fine for editing with such a large file, so I think this issue can be closed.

We should be able to cherry pick the PRs to the next 3.5 as well, I suspect.

**Comment by Daniel-da-Silva** [comment]
@lawnjelly Thank you very much for your work and effort!
