### ISSUE TITLE
Use External on <Unnamed Material > slot in GLB/GLTF Advanced Import Settings does not work correctly

### ISSUE THREAD

**Issue by jss2a98aj** [godotengine/godot#74742]
### Godot version

4.0

### System information

Windows 7

### Issue description

When enabling Use External on an <Unnamed Material> material slot in GLB/GLTF Advanced Import Settings and saving, the material will not appear to apply. The material does remain listed in Advanced Import Settings after though. Closing and re-opening the editor does not change this, not does it make the material appear to apply.

It may be related to #69741 as I am using a very similar mesh to then. At the very least it is not an editor crash this time. I was not able to find any other issues, open or closed, that appeared to be related. Possibly of note, enabling Save to File on the mesh and changing the material in the saved mesh does seem to work as expected.

I recorded a small clip showing Use External and changing the material on a saved mesh:
https://user-images.githubusercontent.com/11281893/224410807-e69abac3-2a40-481d-a4d5-ff0e63707639.mp4

### Steps to reproduce

Open the minimal reproduction project.

Open Advanced Import Settings for the included GLB file.

Enable Use External under materials.

Select the included material.

Re-import.

Open the scene (the GLB is placed in it)

The GLB should be using the default material, not the external one as expected.

### Minimal reproduction project

[Gltf Material Import.zip](https://github.com/godotengine/godot/files/10945274/Gltf.Material.Import.zip)

**Comment by clayjohn** [comment]
I think this may be the same as https://github.com/godotengine/godot/issues/64853. Can you confirm?

**Comment by jss2a98aj** [comment]
> I think this may be the same as #64853. Can you confirm?

It appears so. "Scene Import" being in the title is accurate, but was not the terminology I am used to.
