### ISSUE TITLE
Max/min functions throw incorrect error when comparing Vectors

### ISSUE THREAD

**Issue by WeaverSong** [godotengine/godot#74748]
### Godot version

4.0

### System information

Debian

### Issue description

When using 2 vectors (Vector2 or Vector3) in a max or min function, the editor will throw an error saying that the second argument should be a float. Turn the second argument into a float and it will throw an error saying that it should be a vector again.

I would expect it to compare them by their size, or to just throw an error saying they don't accept vectors.

### Steps to reproduce

```
#Invalid argument for "max()" function: argument 2 should be "float" but is "Vector3".
max(Vector3(1, 0, 0), Vector3(1, 0, 0))

Invalid argument for "max()" function: argument 2 should be "Vector3" but is "float".
max(Vector3(1, 0, 0), 1.0)
```

### Minimal reproduction project

N/A

**Comment by Rindbee** [comment]
`max` only supports `int`/`float` type operations.

Error messages should start checking the type from the first argument. Otherwise it might give the wrong feeling that it supports other types.

**Comment by AThousandShips** [comment]
Making a fix for this, will push soon
