### ISSUE TITLE
Roughly Perpendicular Collisions with Concave Polygon are not detected and stick

### ISSUE THREAD

**Issue by cuppajoeman** [godotengine/godot#74756]
### Godot version

4.0.stable

### System information

Windows 10

### Issue description

When you launch (apply_impulse) a RigidBody3D (sphere_shape) in a line which is roughly perpendicular to a wall (StaticBody), it collides with the wall, `on_body_entered` is never called and the RigidBody3D sticks to the wall.

I noticed this after updating to godot 4 stable, I don't think the issue exited in the RCs or betas.

Video showing it: https://streamable.com/lr0ydn

### Steps to reproduce

Launch the minimal reproduction project, then aim at a wall in so that a raycast coming out of the center of your screen would be roughly perpendicular to the wall or floor, upon firing, the projectile simply just sticks onto the wall and `on_body_entered` is never called.

### Minimal reproduction project

[projectile-collision.zip](https://github.com/godotengine/godot/files/10947822/projectile-collision.zip)

**Comment by rburing** [comment]
This is likely due to my change to CCD in https://github.com/godotengine/godot/pull/72917, sorry about that. I'll investigate.

**Comment by cuppajoeman** [comment]
Just FYI, I found this bug when I launched my fps game in godot 4 stable for the first, time. I noticed it because in general rockets were sticking to the ground and walls. Pretty much  I think this would affect anyone who has an fps using a projectile
which is a `RigidBody3D` and a map which has a Concave Polygon.

**Comment by cuppajoeman** [comment]
I'm not too familiar with the timeline or how regressions work, I'm guessing this fix wouldn't be available until the next version of godot 4 (4.1) releases?

**Comment by Calinou** [comment]
> I'm not too familiar with the timeline or how regressions work, I'm guessing this fix wouldn't be available until the next version of godot 4 (4.1) releases?

The fix can be cherry-picked to a future 4.0.x release.
