### ISSUE TITLE
The editor crashes at project creation when ran from the QtCreator IDE

### ISSUE THREAD

**Issue by ze2j** [godotengine/godot#74768]
### Godot version

v4.0.stable.custom_build [92bee43ad]

### System information

Xubuntu 22.04.2 LTS x86_64, NVIDIA GeForce GTX 1070, Driver Version: 525.85.05, Forward+

### Issue description

I made a custom build of Godot 4.0 [92bee43ad]:
 - `scons platform=linuxbsd target=editor dev_build=yes -j 9`

When I try to run the editor from QtCreator (my IDE),  the editor crashes somewhere when I try to create a new project (some files are created on disk) whatever :
 - the renderer used (Compatibility or Forward+) or,
 - the version control metadata used (Git or None) or,
 - the binary used (the custom build I just made, or the binary downloaded from  [the Godot Engine website](https://godotengine.org/download/linux/))

There is no crash when :
 - I run the custom build with the debugger from QtCreator or,
 - I simply double clic on the binary from my file explorer,

With Godot 3.x I have no issue to launch the editor from QtCreator.

I am not sure how I can narrow down further the issue because it works with the debugger and no error message is produced. Any idea ?

### Steps to reproduce

Launch the editor from QtCreator and try to create a new project.

The working directory is the location of the editor binary.

### Minimal reproduction project

N/A

**Comment by lawnjelly** [comment]
No idea, but I use QT Creator 4.14.2 every day on 3.x (and sometimes 4.x) no problems, Linux Mint 20.1.
Do you know where it crashes?
Does it crash any other time (loading a project from the project manager for instance?) or only after the new project dialog?

**Comment by ze2j** [comment]
@lawnjelly  I do not know exactly where it crashes because there is no crash when I use the debugger. 
I reproduce the crash with QtCreator 4.14.2 (I use QtCreator 9.0.2).
I can reload a successfully created project whatever the way I use to run the editor.
The editor also crashes with an Asset Library Project just after I click Install & Edit in the dialog box to choose the project path on my disk.

AFAIK the crash occurs in the child process created to launch the editor with the path of the newly created project. I added a lot of `print_line`, defined `DEBUG_INIT` and found out the crash is in `Main::setup` after _Main: Parse CMDLine_ is printed. I will continue to investigate this when I will have some time.

**Comment by ze2j** [comment]
The crash always occurs in the `DisplayServerX11` constructor, but its exact location appears to be random.

**Comment by ze2j** [comment]
I do not reproduce this crash with 4.0.3-stable
