### ISSUE TITLE
FixedSpatialMaterial only has Albedo and Specular properties

### ISSUE THREAD

**Issue by tagcup** [godotengine/godot#7476]
**Operating system or device - Godot version:**

Linux, git master

**Issue description** (what happened, and what was expected):

FixedSpatialMaterial only shows Albedo and Specular paramater; the other textures (AO, emission, rim, clearcoat, normal, ...) are all gone in the latest git version.

**Steps to reproduce:**

Create a FixedSpatialMaterial and check the properties editor.

**Link to minimal example project** (optional but very welcome):

**Comment by tagcup** [comment]
Maybe there was supposed to be an option "emission/enabled"? https://github.com/godotengine/godot/blob/master/scene/resources/material.cpp#L741

**Comment by MrMaidx** [comment]
I can confirm this. Not sure with which commit it started, but from unofficial builds of master branch:
January 4, 2017 at 03:38 -> parameters still there
January 5, 2017 at 04:20 -> parameters are gone
