### ISSUE TITLE
EditorFileDialog has missing icons

### ISSUE THREAD

**Issue by SirQuartz** [godotengine/godot#74762]
### Godot version

4.0.stable.mono

### System information

Windows 11, Vulkan, NVIDIA GTX 3080

### Issue description

EditorFileDialog is missing icons.

<img width="641" alt="EditorFileDialog" src="https://user-images.githubusercontent.com/62965063/224478854-af5a104d-64ca-4419-aa54-9d9446d5ac00.png">

### Steps to reproduce

Show the EditorFileDialog

### Minimal reproduction project

N/A

**Comment by YuriSizov** [comment]
That's the first time anyone reports that, so I don't think it's as simple as "Show the EditorFileDialog". Can you give me more specific steps and more details about the project that you're making? Is it a native editor window, is it a plugin? In which context does this dialog appear, saving what exactly? Do you have a custom editor theme, a custom project theme?

**Comment by SirQuartz** [comment]
I was creating a plugin, I did nothing to alter the appearance of EditorFileDialog. All I did was create a new instance of it, then called show() on it. This is what it looks like. It should be noted, that the normal `FileDialog` does correctly load icons, but for some reason `EditorFileDialog` does not.

I have no custom themes whatsoever anywhere in this project period, everything is at the default, this is simply as it appears in-engine. So when I say "Show the EditorFileDialog" I literally mean just show it. It's not caused by me altering any theme settings.

```gdscript
func _enter_tree():
	var file_dialog = EditorFileDialog.new()
	file_dialog.mode = Window.MODE_WINDOWED
	file_dialog.display_mode = EditorFileDialog.DISPLAY_THUMBNAILS
	file_dialog.size = Vector2(400, 500)
	file_dialog.transient = false
	add_child(file_dialog)

	file_dialog.show()
```

**Comment by YuriSizov** [comment]
You are adding a child to the editor plugin node directly. `EditorPlugin` is not a `Control` node or a `Window` node. It doesn't propagate the theme, and I'm not entirely sure where in the editor node tree it is added. So when you add a control node to it, it has no access to the editor theme, so it cannot fetch the icons.

What you should do instead is use `get_editor_interface().get_base_control()`. Same is true for 3.x and 4.0.

**Comment by SirQuartz** [comment]
Alright, so I assume this is intended behavior then? If so, it should probably be documented somewhere in the `EditorFileDialog` class.

**Comment by YuriSizov** [comment]
This is unrelated to the `EditorFileDialog` class. It applies to any control that you add to the editor UI. It needs to be added to the UI root, or to other control nodes in the editor. I'm pretty sure all of the official tutorials do that part correctly, but we can add a note in the `EditorPlugin`'s description, perhaps.
