### ISSUE TITLE
Critical GPU error linked to changing resolution scale in game

### ISSUE THREAD

**Issue by Rytelier** [godotengine/godot#74776]
### Godot version

4.0 

### System information

Windows 10, Vulkan
NVIDIA GeForce RTX 2060
Driver version 528.24

### Issue description

I implemented resolution scale (FSR) slider into my game, with testing it out, GPU encountered a critical error - screen gone black and GPU fans got loud, I only could force shutdown of my computer.

### Steps to reproduce

- Download the reproduction project
- Run the scene
- Move the slider around
- Change window size/maximize it?

### Minimal reproduction project

[Resolution GPU critical error.zip](https://github.com/godotengine/godot/files/10948917/Resolution.GPU.critical.error.zip)

**Comment by Calinou** [comment]
What screen resolution and window size are you using while testing this?

Can you reproduce this issue several times?

**Comment by Rytelier** [comment]
After more testing, it appears my graphics card is damaged, same situation appears in different situations as well.
