### ISSUE TITLE
Game Window spawns top-right

### ISSUE THREAD

**Issue by htory327** [godotengine/godot#7477]
**Operating system or device - Godot version:**
MacOSX El Capitan 10.11.5
Godot Engine 2.1.1

**Issue description** (what happened, and what was expected):

When I play a scene (or project) the game window spawns top-right and it's really annoying I want it to start at the center.

Weird thing is it worked (and still works) on previous version (2.0.x?)

**Steps to reproduce:**

Editor Settings > Game Window Placement > ...
Rect: Centered
Rect Custom Position: 0, 0

**Screenshot**
![ss](http://hnng.moe/f/MJi)

**Comment by bojidar-bg** [comment]
Looks related to retina to me...

**Comment by akien-mga** [comment]
Do you have a secondary monitor?

**Comment by rraallvv** [comment]
@htory327, @akien-mga

I think the problem could be fixed with the PRs above.

Cheers!

**Comment by htory327** [comment]
I don't even use this program anymore, thanks for the help though
