### ISSUE TITLE
Trim Trailing Whitespace removes indentation on blank lines

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#74775]
### Godot version

v4.1.dev.custom_build [b31d00a91]

### System information

Windows 10, Vulkan, i9900KF, RTX 2070S

### Issue description

When the editor setting "Trim Trailing White Space on Save" is removed in all places. This results in intentionally left blank lines within a function body to be stripped of their indentation.

Expected behavior is to only remove trailing white space on the end of a line containing text. And to conform to user desired indentation.

```
func get_neighbors() -> Array[Cell]:
	var a: Array[Cell] = []
	-
	for pos in NEIGHBOR_POSITIONS:
		if GridGame.grid.has_cell(pos):
			a.append(GridGame.grid.get_cell(pos))
	-
	return a
-
```

Correct example above, where - indicates the indentation depth of the line.

```
func get_neighbors() -> Array[Cell]:
	var a: Array[Cell] = []
-
	for pos in NEIGHBOR_POSITIONS:
		if GridGame.grid.has_cell(pos):
			a.append(GridGame.grid.get_cell(pos))
-
	return a
-
```

Incorrect example above.

### Steps to reproduce

Enable "Trim Trailing White Space on Save", edit a script, ctrl + s.

### Minimal reproduction project

-

**Comment by AThousandShips** [comment]
See https://github.com/godotengine/godot-proposals/issues/6300

**Comment by TheDuriel** [comment]
Seems redundant due to proposal.
