### ISSUE TITLE
Terrain peering bits ignore neighboring terrain id

### ISSUE THREAD

**Issue by bs-mwoerner** [godotengine/godot#74780]
### Godot version

4.0.stable.mono

### System information

Windows 10

### Issue description

The terrain peering bits do not work as I would expect them to. I have created a simple tileset with a "Match Corners and Sides" terrain set and three terrains: Outside (red), Wall (dark blue), Floor (light blue).
![TileSet](https://user-images.githubusercontent.com/35597337/224496651-15abfc56-da90-4d54-a115-ff365316fa4d.png)
Left are the actual tiles, right with overlaid terrain bits.

I then created the following tile map and would like to fill in the empty spot using terrain painting in Connect mode.
![TileMap](https://user-images.githubusercontent.com/35597337/224496656-31072c39-ae25-4ec2-ab16-3f6b7a8afdf4.png)

When painting "Outside" terrain into the empty tile, this is the result I would expect:
![TileMapExpected](https://user-images.githubusercontent.com/35597337/224496661-f7341d59-2b90-4e32-8129-4e6be8551254.png)
The second tile in the tile set is the only tile that matches both the selected terrain ("Outside") and all eight peering bits ("Outside" on the top row/left/right, "Wall" on the bottom row), so I would expect that to be picked.

The actual result I get is this:
![TileMapActual](https://user-images.githubusercontent.com/35597337/224496670-5cafad81-1d26-47df-8a1c-0ca6327d53f3.png)
The algorithm picks the first tile in the tileset, which has the requested terrain "Outside" but whose peering bits do not match the neighborhood. Additionally, it changes the left neighbor of the painted tile to the same, mismatching tile.

### Steps to reproduce

Create a tile map and tile set as described above or see the minimal reproduction project.

Note that filling the empty tile with "Wall" terrain produces the intended result of placing the second "Outside" tile, presumably because the "Wall" terrain does not include the first tile as a candidate, because it has no "Wall" terrain in any of its bits.

### Minimal reproduction project

[TerrainBug.zip](https://github.com/godotengine/godot/files/10948969/TerrainBug.zip)

**Comment by dandeliondino** [comment]
Is this not the expected behavior? The algorithm should be matching the corners and sides, not the terrain (center) bit. The terrain bit is there to let the user limit the options from which the algorithm can choose the tile to place.

Here is an example of corner and side matching in what should be a similar underlying algorithm to Godot's: http://cr31.co.uk/stagecast/wang/blob.html

**Comment by bs-mwoerner** [comment]
Thanks for taking the time to reply! Yes, as I understand it, the algorithm chooses between all tiles that include the selected terrain in any of their bits (not necessarily the center bit), possibly preferring tiles with the selected terrain in the center bit.

In my example, though, the tile that is placed has the selected terrain in the center bit, but doesn't match any terrain in the bottom row of the peering bits (bottom left corner, bottom side, bottom right corner), whereas there would have been a different tile that would have matched in all 9 bits.

This is the neighborhood for the paint operation:
![Neighborhood](https://user-images.githubusercontent.com/35597337/224538134-2025cdc3-b1eb-496c-9ccd-9daf4e8ce5ca.png)

And these are the candidate tiles for painting "Outside" terrain (all tiles that contain "Outside" in any of their bits):
![Candidates](https://user-images.githubusercontent.com/35597337/224538246-40ef9c8a-a61b-46f1-a96c-f5f9d53a8519.png)

Of these, only the second tile matches the neighborhood of the painted location. The tile the algorithm selects, however, asks for "Outside" terrain in all its neighbors.

The [documentation ](https://docs.godotengine.org/en/stable/tutorials/2d/using_tilesets.html) says:

_For example, if a tile has all its bits set to 0 or greater, it will only appear if all 8 neighboring tiles are using a tile with the same terrain ID._

This could be interpreted as:
- The tile requires the neighbor to have the terrain indicated in the terrain peering bit; or
- The tile requires the neighbor to have the same terrain as the current tile (i.e. the actual value of the bit does not matter, only if it's 0 or greater).

However, neither of these interpretations should allow placing the first tile set tile in this example. 🤔

**Comment by dandeliondino** [comment]
I agree that documentation is confusing and not specific enough. I'm not sure it's even correct  about only appearing if it's a perfect match.

In your case, though, I feel like I'm still missing what the problem is? The tiles with the blue center bits have red top side and top corner bits. So, if you're matching top side -> bottom side ( and similar with corners), isn't it appropriate that they'd match a tile with red bottom side and corner bits? If you paint the top side/corners of your blue tile blue instead, you should get the second piece you want in the empty spot.

**Comment by bs-mwoerner** [comment]
Ahhh, you're absolutely right! I completely misunderstood the system! I though the peering bits looked at the _terrain_ of the neighboring tile:
![MatchingTerrains](https://user-images.githubusercontent.com/35597337/224542711-f8335fa5-b089-47df-9e1e-f417fc77ba5a.png)

Instead, what they do is look at the neighboring _peering bit_:
![MatchingBits](https://user-images.githubusercontent.com/35597337/224542866-60dae85d-10f1-4318-8841-1150c37a99ae.png)

And that's certainly what you meant by "matching corners and sides", sorry I was a bit slow there. Thanks a lot for the clarification!

**Comment by dandeliondino** [comment]
Just want to circle back. I did a variety of tests and I’m now fairly confident that I was wrong. The matching algorithm matches both the peering bits AND the terrain ID. 

Sometimes it does not look to be matching terrain id, but that seems to only happen when there is not a tile that matches both terrain id and peering bits. In that case, results can vary based on order of terrains within the terrain set, and the tile chosen can change on editor restart.
