### ISSUE TITLE
Changing camera projection matrix handling in Godot 3

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#7478]
Not sure if this is the right place for this discussion but in preparing some of the OpenVR changes and looking back at the stereo camera work I did a few weeks ago I had a look at the new code related to camera handling in Godot 3.

Interestingly enough this is getting much closer to giving the flexibility needed to do stereoscopic rendering. The thing that makes life more complex is that the camera properties set in Godot (fov, near and far plane) are copied into the renderer. In Godot 2 these properties were (re)used in various places but I can see that most of that code has been replaced by evaluating the projection matrix (camera_matrix). 

What I suggest changing in visual_server_scene is to change the camera structure and replace size, fov, near and far plane by the camera matrix. The existing camera_set_perspective and camera_set_orthogonal are changed to calculate the matrix from the given parameters and we add a new function:
camera_set_projection(RID p_camera, camera_matrix& p_matrix)
that simply sets the camera type to Camera::PERSPECTIVE and copies the supplied matrix.

The function render_camera can be simplified as we simply use the matrix that was already set.

The end result is that we can use more complex projection matrices without having to duplicate a lot of logic inside of visual_server_scene. Instead our camera object can calculate, or simply supply, the correct projection matrix to the render logic. When I did my initial work on stereoscopic cameras I did add all the duplicate logic into the visual server which is something I wasn't particularly happy with

For stereoscopic calculations for generic platforms the left and right eye matrices will be different and have additional settings such as IOD (distance between the eyes) and convergence (distance from viewer where left and right eyes overlap).

Both Vive and Rift will supply the matrices through their API as the IOD is controlled on the headset itself and the convergence is non-negotiable.

**Comment by BastiaanOlij** [comment]
Bugger bugger bugger... just answered my own question...

Aspect ratio....

The camera does not know the aspect ratio of the viewport it is rendering to hence for normal purposes you can't have it calculate the projection matrix..

Unlike VR headsets where the aspect ratio is a given....

**Comment by BastiaanOlij** [comment]
Hah! IVRSystem::GetProjectionRaw allows me to enhance the camera system in Godot in a way that works with the existing approach... Ignore this topic all together....

**Comment by bojidar-bg** [comment]
@BastiaanOlij Funny, that's probably the first/second issue that a person opens, comments on by himself, then closes on his own :laughing:

**Comment by BastiaanOlij** [comment]
@bojidar-bg nothing like actually trying to implement something to find out what you missed :)
