### ISSUE TITLE
Some variables aren't updated when iterating through the last child of a node

### ISSUE THREAD

**Issue by Espian05** [godotengine/godot#74793]
### Godot version

4.0

### System information

Windows 10

### Issue description

I'm working on an Ai project at the minute. When each agent has finished running, it sends relevant data to the root node, then the root node loops through all the agents, updates relevant information, and tells them to start again.

However, when looping through all agents, for whatever reason, every agent except for the last one is reset. After trying to debug, I found that start() was being run for all of the agents, but the "alive" variable wasn't being set to true for the very last one. It's position was reset, it's fitness, everything except for the critical "alive" bool.

I'll attach a simple project that recreates the issue, sorry if this isn't a great report or I've just missed something stupid, it's my first after all.

### Steps to reproduce

Run the project, you should see that the first cycle ends, but not the second one. All but the last child report in as finished.

If you look at the data in the "child" nodes after the first cycle ends, notice that for all but the last child, the "running" bool was set to true and they all counted up to 60 before stopping and setting "running" to false again.

What confuses me most is that the last child's "counter" variable is set to zero, but apparently "running" wasn't set to true? So the start() function is definitely executed for all of them.

Idk. 

### Minimal reproduction project

[ChildrenLoopBugExample.zip](https://github.com/godotengine/godot/files/10949378/ChildrenLoopBugExample.zip)

**Comment by kleonc** [comment]
No bug in here, just a flawed logic. @Espian05 you're setting `running = false` after `get_parent().childFinished()` which can lead to calling `start()` and thus setting `running = true`. Meaning for the last child you end up overwriting the just set `running = true` with `running = false`. Changing:
```gdscript
	if counter == max:
		get_parent().childFinished()
		running = false
```
to:
```gdscript
	if counter == max:
		running = false
		get_parent().childFinished()
```
makes it work like you'd expect it to.

Nonetheless, if you're not sure you're facing an actual in-engine bug please firstly use [other community channels](https://godotengine.org/community/) (Discord, Reddit, etc.) to ask for help, before opening an issue in here. This is a bugtracker, not a helpdesk. :slightly_smiling_face:

**Comment by Espian05** [comment]
Ah, thanks @kleonc. Now you've pointed it out it's obvious...

And I was going to just make a forum post first, but it says it's down for maintenance. I'll be sure to go to other channels in future.
