### ISSUE TITLE
Web exports don't work whatsoever (Godot 4)

### ISSUE THREAD

**Issue by CMDR-Piboy314** [godotengine/godot#74799]
### Godot version

4.0.stable.arch_linux

### System information

Arch Linux, GLES3, AMD ATI Radeon HD 6520G

### Issue description

Hello! Web projects just... don't run and have these errors.

[gotm.io](https://gotm.io)
![image](https://user-images.githubusercontent.com/92357316/224516664-4ba07971-74c2-4b9b-a787-9fbc0b01482a.png)

[itch.io](https://itch.io)
![image](https://user-images.githubusercontent.com/92357316/224516669-c9dcc9fc-044f-4c90-ad3e-1a5a2dbc6849.png)

Using Brave web browser, but they don't run on Chrome either.

### Steps to reproduce

The MRP is just a 2D scene with a single label saying "test" and with the export for web set up with defaults.

### Minimal reproduction project

[MRP.zip](https://github.com/godotengine/godot/files/10949714/MRP.zip)

**Comment by CMDR-Piboy314** [comment]
Issue occurs while using the standalone executable from the godot website as well.

**Comment by MatiasVME** [comment]
Idk if that help, but in itch.io you activate de last of thats options:

![image](https://user-images.githubusercontent.com/342117/224517733-26498626-73fa-4eec-9a72-9634368c0e1f.png)

**Comment by CMDR-Piboy314** [comment]
Already enabled :/

**Comment by MatiasVME** [comment]
it's work for me =S

![image](https://user-images.githubusercontent.com/342117/224518481-0920863d-aee0-491c-9fd7-f5a715e469ff.png)

maybe you need name the mrp.html to index.html for itch.io

**Comment by CMDR-Piboy314** [comment]
I did that as well :thinking:

**Comment by QbieShay** [comment]
Have you tried a different browser? There's known issue of Godot multithreading not being supported by all browsers

**Comment by CMDR-Piboy314** [comment]
Yeah, as I said in the original post I tried it on Chrome as well as Brave, I've even tried it on another device :(

**Comment by AThousandShips** [comment]
Brave uses the same engine, have you tried Firefox?

**Comment by CMDR-Piboy314** [comment]
Alrighty, so I installed Firefox which hadn't ever been installed on this machine before, meaning there wouldn't be any leftover tweaks and skipped all customization options.

I went to itch.io, logged in, created a fresh game draft and set the kind of project to HTML. I went to Godot and opened the MRP project, exported for _debug_ and zipped it. Next, I uploaded the zip file to itch.io and marked it as a web version. Finally, I turned SharedArrayBuffer support on and hit save & view.

Sadly, I still recieved the same errors.
```
still waiting on dependencies:
dependency: wasm-instantiate
(end of list)
```

Would anyone mind attempting to reproduce this issue?

**Comment by Calinou** [comment]
> Would anyone mind attempting to reproduce this issue?

Can you link to the project exported to gotm and itch.io? I don't have time to individually upload the MRP to each platform.

**Comment by CMDR-Piboy314** [comment]
Sure, [link](https://cmdr-piboy314.itch.io/test)

**Comment by CMDR-Piboy314** [comment]
Hmm... Interestingly, this build on itch.io works just fine on my other computer.

**Comment by Calinou** [comment]
> Hmm... Interestingly, this build on itch.io works just fine on my other computer. Perhaps it is hardware or OS dependent?

This is likely, as the Radeon HD6520G is a very old GPU that most likely doesn't support WebGL 2.0 well (which is required for Godot 4.x's HTML5 export to work).

**Comment by CMDR-Piboy314** [comment]
Alright, I'll close this issue now then as there is no work to be done!
