### ISSUE TITLE
OS.execute() return of Σ character get error.

### ISSUE THREAD

**Issue by erik90mx** [godotengine/godot#74792]
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Windows 10

### Issue description

I got the following error: 
"Traceback (most recent call last):\r\n  File \"C:\\Users\\USER\\Documents\\issue\\scripts_py\\issue.py\", line 3, in <module>\r\n    print(\"\\u03a3\")\r\n  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\\lib\\encodings\\cp1252.py\", line 19, in encode\r\n    return codecs.charmap_encode(input,self.errors,encoding_table)[0]\r\nUnicodeEncodeError: \'charmap\' codec can\'t encode character \'\\u03a3\' in position 0: character maps to <undefined>\r\n"

PD: I noticed that I can write Σ directly on Godot UI labels and inside the python script. 

### Steps to reproduce

In order to test the issue, I got an external python script with the following command:
//# -*- coding: utf-8 -*-
**if __name__ == "__main__":
 print("Σ")**   <=== This one gives error in Godot end.

And in Godot v4 I got the following command:
var output = []
var _response = OS.execute("python3", [ProjectSettings.globalize_path("res://scripts_py/issue.py")], output, true)

If I put the following:
print("Σ".encode("utf-8"))

it doesn't give an error, but print back to Godot the following output: "b\'\\xce\\xa3\'\r\n" , that I can't convert back to its original symbol , or at least i don't know the build in method to do it (it should be an automated generic code, and don't hardcode just Σ for this case)

Also, I used the following commands to get the different associated encodings:

// Get the default encoding of python
enc1 = sys.getdefaultencoding()
print(enc1) # utf-8

// Get the encoding of the device associated with file descriptor 0 (standard input)
enc2 = os.device_encoding(0)
print(enc2) # None

// Get the preferred encoding according to the locale settings
enc3 = locale.getpreferredencoding()
print(enc3) # UTF-8

And get the following output:
utf-8
cp850
cp1252

PD: If I test a shell with the same print from CMD directly, It print it ok and doesn't give any error:
![imagen](https://user-images.githubusercontent.com/3485891/224512683-f3aa2709-a259-484f-8e18-af185beae652.png)

### Minimal reproduction project

N/A

**Comment by MarioLiebisch** [comment]
> it doesnt give an error, but print back to Godot the following output: "b'\xce\xa3'\r\n"

Since you're basically converting it to the UTF-8 representation (and then once again convert that by printing it), you're essentially encoding it twice. So this result is expected.

The crash itself is not, I guess.

**Comment by Calinou** [comment]
> The crash itself is not, I guess.

Is there a Godot crash anywhere in the issue? I don't see any.

**Comment by MarioLiebisch** [comment]
> I don't see any.
Ah, my bad. Disregard that addition, I misread that it's crashing (instead of just printing the encoding error).
