### ISSUE TITLE
Web export broken in Firefox

### ISSUE THREAD

**Issue by ChronoDK** [godotengine/godot#74791]
### Godot version

4.0

### System information

Web

### Issue description

Web export seems to be completely broken in Firefox, where sprites and fonts are invisible. Works great in Chrome and Edge though.

Also, does not even load in iOS Safari, but that could be a SharedArrayBuffer issue? Can't see the console in that "great" browser...

### Steps to reproduce

Create simple project with sprites and labels. Export to Web.

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
Could you provide a bit more information? An MRP and an update with what errors were printed to console would be very helpful. Right now there is nothing we can do with this bug report.

**Comment by ChronoDK** [comment]
Yikes, started Firefox again to test the MRP I just created and everything is working cause Firefox had updated... Sorry, move along nothing to see here :-D
