### ISSUE TITLE
"Files are newer on disk" warnings after shift to Daylight Savings Time

### ISSUE THREAD

**Issue by guitarmike** [godotengine/godot#74816]
### Godot version

4.0

### System information

Windows 10

### Issue description

Last night we shifted to Daylight Savings Time in the US.  I left Godot running overnight.  When I awoke, there was a dialog on screen listing many of the files in the project and saying that the files were newer on disk.  This hasn't happened before so I assume it is the result of clocks moving forward overnight.

### Steps to reproduce

N/A - see above.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
It seems this is a windows "feature", the `_wstat` method does *not* respect the epoch and does something weird with DST, will look into alternatives in Windows but think this is just a "feature" that windows has to deal with

**Comment by AThousandShips** [comment]
It seems this is a windows "feature", the _wstat method does not respect the epoch and does something weird with DST, will look into alternatives in Windows but think this is just a "feature" that windows has to deal with

**Comment by ievr** [comment]
Could we get this reviewed for the next DST changeover in November? We had a gamejam and this can cause data loss if there are unsaved files at 3AM.

**Comment by AThousandShips** [comment]
There's a PR open and if you're able to test it please do to help get it merged :)
