### ISSUE TITLE
Vector2.floorf method doesn't exist

### ISSUE THREAD

**Issue by touilleMan** [godotengine/godot#7481]
[classes.xml](https://github.com/godotengine/godot/blob/master/doc/base/classes.xml) report a `Vector2.floorf`, however this method doesn't exists in [`Vector2` implementation](https://github.com/godotengine/godot/blob/master/core/math/math_2d.cpp#L160)

So I think this should be remove from `classes.xml`

**Comment by neikeq** [comment]
I remember talking about this on irc. It's declared [here](https://github.com/godotengine/godot/blob/master/core/variant_call.cpp#L426-L428) and registered [here](https://github.com/godotengine/godot/blob/master/core/variant_call.cpp#L1461). However, it seems to be exactly the same as `floor`, so I don't see this method's point.

**Comment by touilleMan** [comment]
Thanks for pointing me out ;-)

I guess this is legacy stuff, maybe Godot 3 is the right time to get rid of it...
