### ISSUE TITLE
Put filename instead of image for script on inspector

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#7483]
I don't know how will be with visual script but for GDScript makes no sense to have a miniature of the code when one only need to know the script file name.

Currently, I have to put the cursor over it and wait a bit for the tooltip to be able to read the file name of the script.

So, I would prefer to have the file name (not full path, just the name) instead of that image on script section (for text based scripts, at least).

**Comment by Zylann** [comment]
I would prefer the name of the script rather than its path (or make it so the name is prioritized, because horizontal space is relatively small in the inspector).

**Comment by RayKoopa** [comment]
Since this is marked "discussion": I totally agree. Those zoomed-out textual previews never helped me. At least show the first lines in a readable size if you really wanna go for a thumbnail.

**Comment by ClikCode** [comment]
Alternatively. make a procedural image for each script?

**Comment by Zylann** [comment]
I'm ok for zoomed-out icons in the file explorer because we see the file name anyways (that's the best you can do IMHO, apart from not showing anything) but in the inspector it's especially inconvenient due to the fact we don't see that name.

**Comment by chanon** [comment]
Yes, I agree that showing the images of the scripts isn't useful. However #7133 needs to be fixed also or it will still require a mouseover for tooltip in most cases to see the filename.

**Comment by eon-s** [comment]
Implemented on https://github.com/godotengine/godot/pull/8358 and https://github.com/godotengine/godot/pull/8359
