### ISSUE TITLE
@export var failed loading resource

### ISSUE THREAD

**Issue by ameredude** [godotengine/godot#74849]
### Godot version

4.0.stable

### System information

Windows 11

### Issue description

So I was trying to assign an 'export var: PackedScene' to two separate Scenes which refers to each other, for example:
- Scene_A with 'export var link_scene: PackedScene' -> assigned to Scene_B through the editor(Inspector Dock)
- Scene_B with 'export var link_scene: PackedScene' -> assigned to Scene_A through the editor(Inspector Dock)

which fails and throws error: failed loading resource

So I tried the intended part with some hard code equivalent, which work flawlessly:
- in Scene_A: var link_scene: PackedScene = load(Scene_B)
- in Scene_B: var link_scene: PackedScene = load(Scene_A)

I also tried to editor assign the 'export var: PackedScene' to only one of the two Scenes (only assigned value to Scene_A or Scene_B). Which also doesn't throw any error.

So apparently I found out that export variables can't handle two Scenes pointing at each other as its hard code equivalent should

### Steps to reproduce

* create two separate Scenes and attach script, I named it Scene_A and Scene_B
* in both of the script add:
```
@export var link_scene: PackedScene
```
* in Inspector Dock:
  * in Scene_A --> link_scene assign Scene_B
  * in Scene_B --> link_scene assign Scene_A

this is the minimal reproduction work to reproduce the issue, however it does not throw any errors that I am seeing. it only stops the debugging process on its own and not throwing any error

### Minimal reproduction project

[MRP.zip](https://github.com/godotengine/godot/files/10952592/MRP.zip)
This is a minimal reproduction project to reproduce the issue. In it Scene_A and Scene_B are supposed to link to each other using 'export var'.
However if Godot tries to open it, it may broke those 'export var' dependencies. You may have to reconfigure them back. See steps to reproduce.
Scene_C and Scene_D are just hard coded equivalent two scenes link to each other and how I intended this to work with 'export var'.

[test.zip](https://github.com/godotengine/godot/files/10952642/test.zip)
This one is to let it throw some error for us to see, I have to make a mini version of the project I am trying to build. It is some sort of cycling through the item tree.
In it there is 'error_item_tree.tscn' which represent 'export var' version. While 'working_item_tree.tscn' represent the hard coded version of what I am trying to build.
As above, when Godot tries to open it, those 'export var' dependencies may broke. You may have to reconfigure them back. See video below

https://user-images.githubusercontent.com/124942760/224588375-083ad2a2-5592-4c1c-8ebf-3ce67cb56174.mp4

item_a Components variable (export var) should have item_b and item_c
item_b Components variable should have item_a
item_c Components variable should have item_a
run scene error_item_tree.tscn

run scene working_item_tree.tscn if you want to see how I intended it to work with hard coded equivalent, in it:
item_m points to item_n and item_o
item_n points to item_m
item_o points to item_m

https://user-images.githubusercontent.com/124942760/224589163-76b3b77c-062f-4f66-a5f3-a5f3c7c929d9.mp4

**Comment by KoBeWi** [comment]
See https://github.com/godotengine/godot/issues/72921
Cyclic references between scenes are not supported.
