### ISSUE TITLE
Camera2D Process Mode is "When Paused" by default, was this intentional?

### ISSUE THREAD

**Issue by dragon3025** [godotengine/godot#74845]
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Windows 10

### Issue description

After migrating to Godot 4, I was surprised that the camera wasn't moving, then I discovered that Camera2D Process Mode is "When Paused" by default, was this intentional? It seems strange to pause the camera when the game is unpaused and to unpause it when the game is paused.

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by gotnospirit** [comment]
At the moment, the project converter doesn't convert `pause_mode` values while converting the property/setter/getter
https://github.com/godotengine/godot/blob/master/editor/renames_map_3_to_4.cpp#L1106

So the converted project might interpret the 3.x value as a `PROCESS_MODE_WHEN_PAUSED`
https://github.com/godotengine/godot/blob/master/scene/main/node.h#L49-L55
https://github.com/godotengine/godot/blob/3.x/scene/main/node.h#L55-L60
