### ISSUE TITLE
TextureFrame modulate won't work if aspect ratio is keep aspect or keep aspect centered

### ISSUE THREAD

**Issue by vinod8990** [godotengine/godot#7484]
**Operating system or device - Godot version:**
Linux Mint 18.1 - based on Ubuntu 16.04
Godot version 2.1.1

**Issue description** (what happened, and what was expected):
Changing the modulate color on inspector not affecting the TextureFrame if it's stretch mode is Keep Aspect or Keep Aspect Centered

**Steps to reproduce:**
Add a TextureFrame node, change its modulate color. Change the stretch mode to every option and see the modulate color not working for Keep Aspect and Keep Aspect Centered modes.

**Comment by bojidar-bg** [comment]
Two points
1. The bug is only present in 2.1.1, as 3.0 has removed the modulate from TextureFrame, and readded it into CanvasItem.
2. The bug comes from the lack of `,modulate` here: https://github.com/godotengine/godot/blob/d5e2b59c84d8cc60dd042c1567cd1d74a654dc6e/scene/gui/texture_frame.cpp#L83

**Comment by volzhs** [comment]
fixed by a7ec7dc.
2.1.3-rc1 got this fix.
