### ISSUE TITLE
OpenXR/OpenGL(ES) rendering has washed out colors on some android devices

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#74857]
### Godot version

4.0.stable

### System information

Android

### Issue description

Using OpenXR with the OpenGL (`gl_compatibility`) renderer often results in washed out colors. There are differences between different devices and XR runtimes but this is mainly due to us attempting to work around this problem.

These issues also existed in Godot 3 and were worked around, they have returned in Godot 4 as most of this information was lost as it was poorly documented. I'll attempt to sketch the full issue here for prosperity.

Godot has always handled linear to sRGB internally as much as possible as the 2D rendering pipeline is fully sRGB oriented and doesn't require any conversions (one of the reasons Godot has a leg up on the competition), and 3D rendering in Godot 3 was performed in linear color space with a conversion to sRGB in the tone-mapping stage. I believe for Godot 4 we've decided to do all 3D rendering in OpenGL in sRGB color space.

OpenGL(ES) has build in functionality to perform linear to sRGB conversion (and back)
As Godot handles all conversions for it's own buffers normal variants of `GL_RGBA8` buffers are used ensuring no hardware conversions are applied.

This proved to be an issue for OpenXR as we are now sending our rendering result to a 3rd party system. The OpenXR specification clearly states that:
- `GL_RGBA8` and similar image formats are assumed to contain linear color data
- `GL_SRGB_ALPHA8` and similar image formats are assumed to contain sRGB color data.

The footnote here is that some XR runtimes ignore the above and always assume data is in sRGB color space when 8bit color data is used, this is important because it explains why our current workaround sometimes works.

This is why our OpenXR implementation overrides Godots default logic and uses `GL_SRGB_ALPHA8` as the color format for our render target. This ensures OpenXR handles the images correctly.

But on Android devices it broke.

In OpenGL the problem they had when adding sRGB image format support was that many solutions out there already output sRGB color data from the fragment shader. From the documentation on the Khronos website:

> When the output buffer is linear RGB, the answer is assumed to be linear. But if we are writing to an sRGB image, it is entirely reasonable for a shader to want to write linear values which will be automatically converted to sRGB for storage. However, at other times, it is entirely reasonable for a shader to want to write sRGB values directly, and therefore want to store the written provided without any conversion. 

A decision was thus made to make this a setting that by default is off. This setting is called `GL_FRAMEBUFFER_SRGB`.

When off, whatever the fragment shader outputs is written into the buffer
When on, the output of the fragment shader is assumed linear, and if a sRGB image format is used, OpenGL will convert the color to sRGB before writing it into the buffer.

Even though Godot is an OpenGLES renderer, we're still using OpenGL on desktop machines and without ever enabling `GL_FRAMEBUFFER_SRGB` we're good.

In OpenGLES however we have no such setting. OpenGLES always assumes fragment shader output is linear. No problem when the `GL_RGBA8` image format is used as OpenGLES assumes that is a linear buffer, but when a `GL_SRGB_ALPHA8` is used, it will apply the conversion. However as we've already converted the data to sRGB, this doubles up, and we get washed out colors.

The workaround that was implemented a few months ago was to change the logic around choosing the image format. In OpenXR, the XR runtime supplies us with a list of formats it supports. On most desktop system this only returns `GL_SRGB_ALPHA8` while on most Android devices it uses both `GL_RGBA8` and `GL_SRGB_ALPHA8`. So we changed the order around and use `GL_RGBA8` on Android if available. As I mentioned up above, certain runtimes ignore the rule and will treat a `GL_RGBA8` buffer as containing sRGB data. However as we found out, Quest is not one of them, and we're running into trouble with other devices also handling this wrong.

We need to undo this work around and return the logic to what it was and always use `GL_SRGB_ALPHA8` when available.

As 2D rendering to XR viewports isn't supported, we can detect in the rendering pipeline if an sRGB image format is used and if we're either using GLES or if  `GL_FRAMEBUFFER_SRGB` is enabled, we have to ensure our fragment shaders are outputting linear color space even if this means doing an sRGB to linear conversion, only for the hardware to convert it back.

For more understanding of linear v.s. sRGB color space as implemented in OpenGL/OpenGLES, please see:
https://learnopengl.com/Advanced-Lighting/Gamma-Correction
https://www.khronos.org/opengl/wiki/Framebuffer

Note, this issue is not relevant for Vulkan due to Vulkan implementing this much better and giving us the needed control.

### Steps to reproduce

Undo the workaround and thus change this code back the way it was:
```
void OpenXROpenGLExtension::get_usable_swapchain_formats(Vector<int64_t> &p_usable_swap_chains) {
	p_usable_swap_chains.push_back(GL_SRGB8_ALPHA8);
	p_usable_swap_chains.push_back(GL_RGBA8);
}
```

Run any XR project on a Quest or other mobile device

### Minimal reproduction project

The demo project for XR Tools can be used for this:
https://github.com/GodotVR/godot-xr-tools

**Comment by BastiaanOlij** [comment]
@clayjohn @dsnopek @Malcolmnixon @rsjtdrjgfuzkfg @m4gr3d 

Have a read through this issue and see if you understand this and agree with my findings.
I ran out of time today as I did a deep dive back into this and had all the memories from 2-3 years ago resurface when I solved all this in Godot 3 (well kinda solved because there are still some display issues in Godot 3).

I'm 99% sure of  the fact that `GL_FRAMEBUFFER_SRGB` is only available on OpenGL and that OpenGLES always forces this logic on us.

I'll start doing more experimenting with this tomorrow and see if I can come up with an approach that will work, where we're correctly outputting linear color data when we have to, or if there isn't some other way in OpenGLES to tell it that we're outputting sRGB color data and tell it to keep its filthy hands off of it.

I've got a few other things on my plate to finish first so can't promise to have this done and dusted right away, but I think we've got all the pieces of the puzzle.

**Comment by dsnopek** [comment]
> Undo the workaround and thus change this code back the way it was:
>
> ```
> void OpenXROpenGLExtension::get_usable_swapchain_formats(Vector<int64_t> &p_usable_swap_chains) {
> 	p_usable_swap_chains.push_back(GL_SRGB8_ALPHA8);
> 	p_usable_swap_chains.push_back(GL_RGBA8);
> }

We originally had the swapchain formats listed in this order, and then swapped them (or really, removed the SRGB one, realized that was a mistake, and then added it back :-)) because it caused problems the Pico 4 - see issue #71224

I suspect we'll need to do something more complicated to get this doing the right thing on all platforms

**Comment by clayjohn** [comment]
For 3D-only viewports this will be fine as we do the linear->sRGB conversion at the end of the fragment shader anyway. We can just pass a flag to skip the linear->sRGB step and let the driver handle it. But for 2D this seems like more of a pain as we would have to do the reverse (pass a flag to do sRGB->linear conversion and then rely on the driver to go back to sRGB).

**Comment by BastiaanOlij** [comment]
> I suspect we'll need to do something more complicated to get this doing the right thing on all platforms

@dsnopek indeed, the swapping them back and forth was a workaround. It works on OpenGLES devices that still treat `GL_RGBA8` as containing sRGB data against the OpenXR specifications, as no hardware conversion is done.

But it makes everything over bright on systems that do do the proper thing.

On desktop it's less of a problem as you need to turn the hardware conversion on so as long as `GL_SRGB8_ALPHA8` is used things go well and seeing for instance SteamVR only reports `GL_SRGB8_ALPHA8` as an option we ignore `GL_RGBA8`.
But on systems that do support `GL_RGBA8` and we end up choosing `GL_RGBA8` everything will be too dark.

@clayjohn that's actually good enough, we don't render 2D content to the HMD output because it wouldn't be stereo correct anyway, and for 2D UIs we're rendering to normal Godot viewports where we fully control what we are doing. So I think that will be a good workaround. The trick will be to detect when we should do this.

**Comment by BastiaanOlij** [comment]
@clayjohn this is hilarious, looks like we weren't the only ones who aren't happy with this automatic logic. Someone eventually added an extension to make ` GL_FRAMEBUFFER_SRGB` work in OpenGL ES, but no idea how widespread it is...

https://registry.khronos.org/OpenGL/extensions/EXT/EXT_sRGB_write_control.txt
