### ISSUE TITLE
I can't give the storage permission on Android 11

### ISSUE THREAD

**Issue by Lufims** [godotengine/godot#74853]
### Godot version

3.3.stable, 4.0.dev

### System information

Android 11

### Issue description

When I try to create a new project, I says that I have to give access to the storage, but when I try to do that, it says "no permissions required", and I can't even try to give te permission because the button is deactivated.

### Steps to reproduce

Use Godot (3 or 4 (I tried both)) on Android 11, and try to create a new project.

### Minimal reproduction project

A

**Comment by lawnjelly** [comment]
@m4gr3d might have some ideas what is going on.

**Comment by m4gr3d** [comment]
@Lufims the first time you start the app, there should be a screen promoting you for storage permissions. 

If you exited it out of that screen, try to kill the app and restart it. Worst case scenario you may need to uninstall/reinstall the app.

**Comment by Lufims** [comment]
> @Lufims the first time you start the app, there should be a screen promoting you for storage permissions.
> 
> If you exited it out of that screen, try to kill the app and restart it. Worst case scenario you may need to uninstall/reinstall the app.

I tried to use that screen, but it's the same, and I tried to reinstall the app, but, it's the same too, I think my phone doesn't let me grant the permission because it can't detect that it have to have the storage permission. Idk.

**Comment by m4gr3d** [comment]
@Lufims Can you provide a recording of the issue on your device. That'll help us identify the root cause.

**Comment by Lufims** [comment]
> @Lufims Can you provide a recording of the issue on your device. That'll help us identify the root cause.

Sorry for the delay, ı changed my phone and ı forgot to reply (but the phone it's the same model), here's the recording.

https://user-images.githubusercontent.com/73536178/227812577-edf964a7-4979-41a3-b10a-05bacfee3ea6.mp4

**Comment by m4gr3d** [comment]
@Lufims Looks like your device is missing the `All files access` permission screen which is required for access.
![Screenshot_20230326_182328](https://user-images.githubusercontent.com/914968/227819639-3e2483cb-8ce8-4768-ad00-9873d1052519.png)


You should still be able to use the editor but with limited storage capabilities; you should still be able to create new projects but only in the `Documents` or `Downloads` directories.

Can you provide the device make and model, as well as the version of Android it's running; this will enable us to provide the same guidance to other users with the same device as yours.

**Comment by Lufims** [comment]
> @Lufims Looks like your device is missing the `All files access` permission screen which is required for access. ![Screenshot_20230326_182328](https://user-images.githubusercontent.com/914968/227819639-3e2483cb-8ce8-4768-ad00-9873d1052519.png)
> 
> You should still be able to use the editor but with limited storage capabilities; you should still be able to create new projects but only in the `Documents` or `Downloads` directories.
> 
> Can you provide the device make and model, as well as the version of Android it's running; this will enable us to provide the same guidance to other users with the same device as yours.

I see... I'm using a Samsung Galaxy A03 Core, with Android 11 GO.

**Comment by m4gr3d** [comment]
It looks like this version of Android lacks certain capabilities: https://developer.android.com/guide/topics/androidgo#differences-from-android

@Lufims Are you able to create new projects in the `Documents` or `Downloads` directories? If so, feel free to close this issue.

Do note that without that permission, only the app that creates the project can access it; e.g: if you fully uninstall and reinstall the app, you won't be able to access the created projects because the device will consider the reinstalled app as a new different app.
This limitation doesn't apply to updates so I recommend using the versions from the Play store ([4.x](https://play.google.com/store/apps/details?id=org.godotengine.editor.v4), [3.x](https://play.google.com/store/apps/details?id=org.godotengine.editor.v3)), since new updates will auto-install on your device.

**Comment by Lufims** [comment]
> It looks like this version of Android lacks certain capabilities: https://developer.android.com/guide/topics/androidgo#differences-from-android
> 
> @Lufims Are you able to create new projects in the `Documents` or `Downloads` directories? If so, feel free to close this issue.
> 
> Do note that without that permission, only the app that creates the project can access it; e.g: if you fully uninstall and reinstall the app, you won't be able to access the created projects because the device will consider the reinstalled app as a new different app. This limitation doesn't apply to updates so I recommend using the versions from the Play store ([4.x](https://play.google.com/store/apps/details?id=org.godotengine.editor.v4), [3.x](https://play.google.com/store/apps/details?id=org.godotengine.editor.v3)), since new updates will auto-install on your device.

I'm able to create a project on a subfolder inside these directories, so i will close this issue then.

**Comment by Zireael07** [comment]
@m4gr3d I think that Android GO limitation should be documented in our Android docs - I hear that more and more low-ish end devices are using GO, tbh I was looking forward to buying one of those GO devices myself...
