### ISSUE TITLE
Export on mobile version

### ISSUE THREAD

**Issue by Raffa064** [godotengine/godot#74856]
### Godot version

any version after playstore

### System information

Android 10, 64bits

### Issue description

[ en ]
Before putting it on the playstore, the export functions worked!
 Now you removed it, and it shouldn't have happened!
 Look at this video, in it I show how to export when I had the option:

[ pt-Br ]
Antes de colocar na playstore as funções de export funcionavam!
Agora vocês removeram, e isso não devia ter acontecido!
Olha esse video, nele eu mostro como que fazia para exportar quando tinha a opção:

https://youtu.be/qwz-KZzAxoM

### Steps to reproduce

no needed for this issue, I think

### Minimal reproduction project

no needed for this issue, I think

**Comment by clayjohn** [comment]
CC @m4gr3d

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/godot/issues/73130.
