### ISSUE TITLE
Skeleton3D::get_bone_global_pose(bone_idx: int) return value is misleading.

### ISSUE THREAD

**Issue by sigrudds1** [godotengine/godot#74851]
Note - This post name and content has been changed from information provide in a comment.

### Godot version

4.0.stable

### System information

Windows10, Vulkan, NVIDIA GeForce RTX 2060

### Issue description

What doesn't work:
The word global in most cases mean, for the Godot Engine, global to the project not a specific space, the description does say otherwise but it still does not take away the general meaning that is presented in most other uses of the word , so it is easy to skip over the true meaning.

How do I expect it to work:
Return the global transform of the bone pose, to the world.

Proposed fix:
Rename it to get_bone_skeleton_pose() or get_bone_skeletal_pose which is more local to the skeletal space, as suggested and agreed upon in [#19551](https://github.com/godotengine/godot/issues/19551) and added to [#16863](https://github.com/godotengine/godot/issues/16863) but are both closed and last edited on Oct 21, 2021, so I assumed dropped.

Additionally:
I can see getting the global pose relative to the world as a use when trying to get the looking_at to another object from the bones perspective, this can be achieved in GDScript but I think adding it to the source would be more performant.

**Comment by sigrudds1** [comment]
OK, I limited my search to around 2020, definitely an old issue and in my frustration I missed the description seeing a lot of the descriptions are 

> There is currently no description for this method. Please help us by contributing one!

my fault for assuming, but since [#19551](https://github.com/godotengine/godot/issues/19551) and [#16863](https://github.com/godotengine/godot/issues/16863) are closed will it get overlooked?
Or has it been decided to forget the changes?

**Comment by fire** [comment]
I don't think we're able to change the names of apis, because of Godot Engine 4.0 compatibility and this is an often used function for game code but documentation pull requests are welcome.

**Comment by sigrudds1** [comment]
> I don't think we're able to change the names of apis, because of Godot Engine 4.0 compatibility and this is an often used function for game code but documentation pull requests are welcome.

I find this to be unlikely, considering that in the latest, API names are changed and deprecated.

**Comment by AThousandShips** [comment]
Between 3.x and 4.0 yes, but won't happen within 4.x

**Comment by sigrudds1** [comment]
> Between 3.x and 4.0 yes, but unlikely to happen within 4.x

That kind of pigeon holes you into limiting the development of an admittedly incomplete engine version doesn't it? Especially considering it was suggested and agreed upon in 3.x before 4.x was started? I find it wishful thinking and will be utterly amazed that names will remain unchanged for the entire life cycle of 4.x, but I get that is to be determined, when 5.x comes along.
None the less the addition function of get_bone_skeleton_pose(),  get_bone_skeletal_pose or even get_bone_global_transform, would still be applicable and help with confusion and performance.

**Comment by AThousandShips** [comment]
Also to be clear no actual decision seems to have been made to actually change the name and no action was taken, not that this would automatically make this change ignore compatibility concerns, several other proposed changes didn't happen

**Comment by AThousandShips** [comment]
My suggestion would be:
* Document this more
* Add a properly named function and make the old function point to it
* Deprecate the old function at an appropriate time (probably a minor release)
* Remove the old function when appropriate

**Comment by fire** [comment]
Please write a proposal https://github.com/godotengine/godot-proposals/ 

There's an evaluation guide here https://github.com/godotengine/godot-proposals/#how-core-developers-evaluate-proposals

**Comment by Calinou** [comment]
Closing, as feature proposals should be discussed on the [Godot proposals](https://github.com/godotengine/godot-proposals) repository. This repository is now used for bug reports only.

Make sure to follow the proposal template when opening a new proposal – don't just copy and paste the text you wrote in this issue.
