### ISSUE TITLE
"Manage Theme Items" in theme editor always delete all items when I only try to delete one of them

### ISSUE THREAD

**Issue by meowyih** [godotengine/godot#74854]
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Window 10

### Issue description

To delete the control items (Label, Button... etc.) in Theme resource is using "Manage Theme Item" dialog. But when there are two or more items in the list, if I click the delete button (trashcan icon), it always delete every thing in the list, not the one I want to delete.
![screenshot (20)](https://user-images.githubusercontent.com/32887778/224607098-e9454ddc-e203-43ec-88f1-cd27be9fadbf.png)

### Steps to reproduce

1. Create an empty project and add one Label control in it.
2. Create a Theme resource in Label's theme properties.
3. Click "Theme" to open the theme editor.
4. Click "+" button in the theme editor to add two or more control items, such as Label and Button.
5. Click "Manage Item" button in the theme editor to open the "Manage Theme Item" dialog.
6. In "Manage Theme Item" dialog, try to delete one item we just created.
7. All the items are deleted instead of one.

### Minimal reproduction project

[ThemeDeleteItemBug.zip](https://github.com/godotengine/godot/files/10953507/ThemeDeleteItemBug.zip)

**Comment by AThousandShips** [comment]
Same as #71313?

**Comment by YuriSizov** [comment]
Yes, it seems to be the same as https://github.com/godotengine/godot/issues/71313.

**Comment by meowyih** [comment]
One of the UI principle is something like "don't create two buttons to do the same thing". If such design is on purpose, we really need to combine all the buttons into one.

**Comment by YuriSizov** [comment]
I'm not sure what you mean, and deleting all the items by clicking on one is not done on purpose.
