### ISSUE TITLE
TileMap Unable to Clear Scene Tiles

### ISSUE THREAD

**Issue by IAmTraffic** [godotengine/godot#74867]
### Godot version

4.0 stable

### System information

Windows 10

### Issue description

Running .clear() on a TileMap with Scene tiles leaves the tiles in place, as though nothing happened.

This appears to be the same issue as raised in [#69596](https://github.com/godotengine/godot/issues/69596), [#72456](https://github.com/godotengine/godot/pull/72456), and [67330](https://github.com/godotengine/godot/pull/67330). None of the previous issues seem to have presented a fix for this issue besides running some dummy operations on the TileMap, which have not had any effect for me.

Manually running queue_free() on each tile scene doesn't work, presumably since they are being cached. And running a dummy operation on the TileMap doesn't have any impact to speak of.

Not sure how to proceed, or if it's just impossible to remove Scene tiles once they're created.

### Steps to reproduce

The minimal reproduction project has a TileMap with several simple scene tiles. The attached script attempts to .clear() the TileMap when the user presses Enter, demonstrating my issue.

### Minimal reproduction project

[TileMapMinimumRecreationProject.zip](https://github.com/godotengine/godot/files/10959111/TileMapMinimumRecreationProject.zip)

**Comment by KoBeWi** [comment]
> Manually running queue_free() on each tile scene doesn't work, presumably since they are being cached.

idk it works when I add
```GDScript
for node in get_children():
	node.queue_free()
```
in your MRP, both before and after the `clear()`.

**Comment by jamesfoxbr** [comment]
I have this same problem
