### ISSUE TITLE
REDUNDANT_AWAIT error incorrectly reported on `await callable.call()`

### ISSUE THREAD

**Issue by SirLich** [godotengine/godot#74879]
### Godot version

4.0.stable

### System information

Windows 10

### Issue description

The issue seems to be related to #61373.

My specific use-case is using await to stall until a callable.call is finished. When I use 'await' here it *does await*, so I think the warning is incorrect.

Actual code is like this:

```swift
	for connection in connections:
		var callable : Callable = connection["callable"]
		
		print(callable.get_object())
		await callable.call()
```

![image](https://user-images.githubusercontent.com/18729296/224826901-17907c63-5e6a-4b31-846e-af8d57ccab48.png)

### Steps to reproduce

1. Create a script, which uses `await callable.call()` on a callable. For example, based on the connections in a signal.
2. Run project
3. View warning

### Minimal reproduction project

N/A

**Comment by dalexeev** [comment]
I'm not sure if we can do something here. In the case of non-constant values, it is not always possible to determine whether `await` is needed or not. Now, if we do not know that, then we produce a warning. This may seem overkill and inconsistent with other warnings, but to me this happens very rarely and therefore a false negative result seems a worse option. In case of false positives, you can use `@warning_ignore`.

**Comment by vnen** [comment]
> Now, if we do not know that, then we produce a warning.

That's not the case actually. The warning is only shown if the function being called is known at compile time, then it can check if it's a coroutine or not. There may be no warning when it should but the alternative is worse IMO since users who do not add static typing would see those warnings pretty much every time they use `await`.

What we could do is add an exception for the `call` methods since we know they will call other functions which the compiler does not know about.

**Comment by MikeSchulze** [comment]
i run also into this issue, from my perspective a key word to signature a function would be very helpful to identify is an await need or not.
`async func foo():`

This should also be reflect in the method descriptor by a flag

**Comment by dalexeev** [comment]
This will not help if the function is not known at compile time. As far as I know, a function is already considered a coroutine if at least one `await` is present in its body, so `async` is not needed.

**Comment by MikeSchulze** [comment]
Why not? a callable has all information to check.
```
StringName get_method() const
Object get_object() const
```
Do get the method info from the object and check the async flag

**Comment by dalexeev** [comment]
> Why not? a callable has all information to check.

Only if we know the value of the callable **at compile time** (warnings are compile-time).

```gdscript
# Possible:
await const_callable.call()

# Impossible:
var t = const_callable
await t.call()
```

The `async` flag is not needed for this. Perhaps it could improve readability (like in JavaScript), but it's too late for that. In addition, there are no async methods in the core, adding a flag to the core just for GDScript would be wrong.

**Comment by SirLich** [comment]
I would submit that the false positive is more harmful than you think!

When I first saw this warning, I actually got a bit anxious that I was relying on some "Undefined Behavior" and my ability to await a `callable.call()` might be removed in the future.

I even tested multiple times to ensure that awaiting `callable.call()` was even *doing anything* since the warning implied it was redundant, and had no effect. 

I would *also submit* that awaiting a callable is a pretty common task. It's really the only way to create an event queue/scheduler that allows timed animations and stuff to play in the right order. 

> That's not the case actually. The warning is only shown if the function being called is known at compile time, then it can check if it's a coroutine or not. 

Are you saying I'm actually being "punished" (I mean this lightly) by type-hinting my Callable, and if I left it without a type hint I could avoid this warning?

**Comment by vnen** [comment]
> > That's not the case actually. The warning is only shown if the function being called is known at compile time, then it can check if it's a coroutine or not.
> 
> Are you saying I'm actually being "punished" (I mean this lightly) by type-hinting my Callable, and if I left it without a type hint I could avoid this warning?

The thing is that Callable is a black box, GDScript does not knows what it contains. When it sees the `Callable.call()` function, it checks the available data to decide whether it needs `await` or not and since it's a built-in function, generally it does not would return something that you would `await` on.

That's naturally not the case, you can still `await` on `Callable.call()`. The warning is just being a bit optimistic and being shown on cases where it's not redundant.

In a second thought, instead of adding exception for `call()`, it should be done for any function that returns `Variant`. Because even if they cannot return a `GDScriptFunctionState` (the result of a coroutine), they could still return a `Signal` which is a valid target for `await` as well.

**Comment by dalexeev** [comment]
> In a second thought, instead of adding exception for `call()`, it should be done for any function that returns `Variant`. Because even if they cannot return a `GDScriptFunctionState` (the result of a coroutine), they could still return a `Signal` which is a valid target for `await` as well.

In this case, there will be no warning for untyped functions. This is fine?

```gdscript
func not_coroutine(): # -> Variant
    pass

func not_coroutine_void() -> void:
    pass

func test():
    await not_coroutine() # No warning.
    await not_coroutine_void() # Warning.
```

**Comment by vnen** [comment]
> In this case, there will be no warning for untyped functions. This is fine?

I think it's fine. As I said, there's no way to know if they will return a signal (at least not with the current level of analysis in GDScript). I prefer to not have the warning unless it's certain that it is correct.

**Comment by dalexeev** [comment]
Ok, done. I'm not sure if function returning signal is a common use case, but it makes sense if we want to get rid of false positive warnings.
