### ISSUE TITLE
'VisualShader' cannot be created from 'ShaderMaterial' inspector

### ISSUE THREAD

**Issue by SirLich** [godotengine/godot#74880]
### Godot version

4.0.stable

### System information

Windows 10

### Issue description

`ShaderMaterials` (and likely other types) do not allow creating a new 'VisualShader' from the drop-down:

![image](https://user-images.githubusercontent.com/18729296/224828210-4d61f26f-ff6b-48ce-af82-db5de84589ac.png)

It's possible to drag+drop (or quick-load/load) a Visual Shader into this field so I know it's compatible.

### Steps to reproduce

1. Right click in explorer to create a new `ShaderMaterial`
2. Click the empty 'Shader' field
3. View that 'Visual Shader' is not an option

If desired:
1. Create a visual shader resource
2. Drag+drop into the field, to confirm it works

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
To create a visual shader you select "new shader" then in the shader creation menu you can select "Visual shader"

**Comment by SirLich** [comment]
Sorry, you're 100% right. This is what the panel looks like, for anyone who's curios:

![image](https://user-images.githubusercontent.com/18729296/224840158-9ad15758-b14d-4a6e-88ce-76601813e0c1.png)
