### ISSUE TITLE
Filesystem window - option to disable expanding all folders

### ISSUE THREAD

**Issue by Gibbz** [godotengine/godot#7488]
**Operating system or device - Godot version:**
ubuntu 16.04
2.1

**Issue description** (what happened, and what was expected):
The file system folders under res:// should not be fully expanded. I have lots of folders in folders, and by default the folders are all in an expanded view. It makes the first thing to do after loading the editor is to always close them.
The only folder that should be expanded by default is res://. None of its subfolders should be expanded.

**Steps to reproduce:**
make folders in folders in folders
load editor
pull out hair :)

**Comment by akien-mga** [comment]
I agree. It was mentioned previously in #796 but it's best to have it in a separate issue :)
