### ISSUE TITLE
Few 3D viewport selection bugs and usability problems

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#749]
Sorry that I stacked all of them here. I can separate each one to it's own report if there is need for it.

Bug 1:
I can't select instanced scenes in 3D view-port by clicking their meshes. (*Edit:* now in #2852)

Bug 2:
When zoomed out it's impossible to select  some smaller objects. I'm not talking about 5px objects of course, they are reasonably big on screen to be selectable by user.

Problem 1:
Current way of indicating which objects are selected is not very useful, the bounding box corners are not very noticeable (actually not visible in light scenes) and it's often hard to see if I selected mesh or lamp even.
Would suggest some sort of coloured outline around mesh objects and maybe sprite display change for lamps and stuff.
Additional benefit from outline is when working with stacked, intersecting meshes. User can then see borders of the object he manipulates and it's easier for him to see what he is doing.

Problem 2:
Awesome feature of Select Mode (Q) is that it can do bounding box selection, helps with selecting multiple or small objects, but it doesn't work if there are other objects behind object we want to select.
It then selects that "behind object" and because current nature of this tool automatically transforms it to the movement of the mouse, so there is no way to use bounding box selection in most scenes.

I would suggest to separate selection from multi transform tool and make it more like ON/OFF mode for transform gizmos. It would also help if user wants, for example, only translate objects that he selects, or only select object without seeing any transform widgets on the screen that can stand in the way sometimes.
I can elaborate that idea (visual help what I have in mind?) if that's not enough.

Problem 3:
In 2D there is an option to Lock objects from selection, something like that would be useful for 3D as well.

**Comment by akien-mga** [comment]
It would be nice to split this issue in several smaller bug reports, as it's indeed hard to work with such a monolithic format. Bug 1 at least is fixed already, for the rest a quick search through existing issues would also be sensible, as some might have been reported in the meantime.

**Comment by n-pigeon** [comment]
@akien-mga 
Done. Closing.

**Comment by akien-mga** [comment]
Awesome, thanks a lot :)

**Comment by GeorgeDubuque** [comment]
it would be nice if you mentioned the filed bug reports in this thread before closing the issue
