### ISSUE TITLE
In GdScript4, using Array.slice() with a step size greater than 1 omits the last expected value

### ISSUE THREAD

**Issue by ACG8** [godotengine/godot#74905]
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Windows 10

### Issue description

I would like to slice an array of 12 values to get the values at index 2, 6, and 10 with Array.slice() using a step size of 4. However, this seems to be impossible in gdscript4. No matter what I try, it won't include the last expected value (10).

It is worth mentioning that it was possible to get the value at index 10 in Godot version 3.5 (when the end of slice was inclusive rather than exclusive)

### Steps to reproduce

Create a node with the following script and run it:

```
extends Node


func _ready():
	var array = range(12)
	print("expectation: should be able to use array.slice to get [2,6,10] from range(12)")
	print("array = " + str(array))
	print("array.slice(2,11,4) = " + str(array.slice(2,11,4)))
	print("array.slice(2,12,4) = " + str(array.slice(2,12,4)))
	print("array.slice(2,INF,4) = " + str(array.slice(2,INF,4)))
	get_tree().quit()
```

You will (incorrectly) get the output:
```
expectation: should be able to use array.slice to get [2,6,10] from range(12)
array = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
array.slice(2,11,4) = [2, 6]
array.slice(2,12,4) = [2, 6]
array.slice(2,INF,4) = []
```

However, in Godot 3.5 you would have (correctly) got:

```

expectation: should be able to use array.slice to get [2,6,10] from range(12)
array = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
array.slice(2,11,4) = [2, 6, 10]
array.slice(2,12,4) = [2, 6, 10]
array.slice(2,INF,4) = []

```

### Minimal reproduction project

[array_slice_bug.zip](https://github.com/godotengine/godot/files/10968580/array_slice_bug.zip)

**Comment by AThousandShips** [comment]
This is due to rounding problems, will investigate a solution

**Comment by AThousandShips** [comment]
Also use -1 not INF for unbounded slice

**Comment by ACG8** [comment]
> Also use -1 not INF for unbounded slice

Thanks!

**Comment by AThousandShips** [comment]
My bad -1 does *exclusively* the full size, you will have to input the full size if you want the full array, somewhat messy unfortunately
