### ISSUE TITLE
`godot --version` outputs extra cruft to stdout on MacOS

### ISSUE THREAD

**Issue by ttencate** [godotengine/godot#74906]
### Godot version

master (79454bfd3b21)

### System information

MacOS

### Issue description

On MacOS, `godot --version` outputs more than just the version number to stdout. This is a problem for tools that parse the Godot version number.

The responsible code is here:
https://github.com/godotengine/godot/blob/79454bfd3b218f5d2b2bb1da2013a3f359615d63/platform/macos/godot_main_macos.mm#L54-L69

I think this debug output should just go to stderr instead, i.e. `fprintf(stderr, ...)` instead of `printf(...)`.

### Steps to reproduce

```
$ godot --version
arguments
0: /Users/runner/work/_temp/godot_bin/godot.macos.editor.dev.x86_64
1: --version
Current path: /Users/runner/work/gdext/gdext/godot-core
4.1.dev.custom_build.79454bfd3
```

(I don't have a Mac, this output is synthesized.)

### Minimal reproduction project

N/A

**Comment by bruvzg** [comment]
Seems like a really old debug printfs that were not cleaned up. Also, there are quite a few other printf which probably should be replaced with `print_verbose` or removed (mostly in iOS code).
