### ISSUE TITLE
Incorrect Setting Values Shown in Remote Scene Tree [Editor Settings]

### ISSUE THREAD

**Issue by BetaTester704** [godotengine/godot#74919]
### Godot version

Godot Engine v4.0.stable.official.92bee43ad

### System information

Windows 11, Vulkan API 1.3.237 - Forward+ - Using Vulkan Device #0: AMD - AMD Radeon RX 6800M

### Issue description

While messing with Editor Settings i noticed that changing `debugger/remote_scene_tree_refresh_interval` and `debugger/remote_inspect_refresh_interval` to 0 they became -0.
*(PropertyPath for Convenience)*
Located under the Network Dropdown

Upon hovering over the values both seem to be a type of float that only rounds for the TextBox and not the EditorHint.

Examples Below:
![image](https://user-images.githubusercontent.com/44848633/225107392-f4b7648e-a193-4ee2-ac29-53a37e9aff12.png)
![image](https://user-images.githubusercontent.com/44848633/225107515-ac8038c8-2dac-45f2-9e4e-72e15458c4e8.png)
![image](https://user-images.githubusercontent.com/44848633/225107553-441d9570-f872-4440-aceb-5558d164479f.png)
![image](https://user-images.githubusercontent.com/44848633/225107606-e2b889ff-b651-4388-9bc5-761cc2d0a7b2.png)

### Steps to reproduce

Open Editor Settings.
Navigate to Debugger.
Hover or change value.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Looks like the setting isn't configured properly, will take a look

**Comment by Calinou** [comment]
> Looks like the setting isn't configured properly, will take a look

Did you find anything? I think we just need to add a property hint to prevent zero or negative values from being chosen.

**Comment by AThousandShips** [comment]
Yes indeed, my bad got lost when investigating some other bugs
