### ISSUE TITLE
(C#) Instantiating non-tool-script in editor crashes editor

### ISSUE THREAD

**Issue by markdibarry** [godotengine/godot#74913]
### Godot version

4.1.dev (550a779851)

### System information

Windows 10

### Issue description

When using a tool script to instantiate a `PackedScene` that does not use a tool script the editor crashes.
This is not an issue in GDScript.

EDIT: After some more digging and discussion, it seems this is present in 4.0 as well, but not sure about 3.x. The major underlying issue is that the editor always interprets the wrong type of any scene unless it's a tool script. For example, if you were to set a breakpoint on the editor for the `ChildEnteredTree` signal, and drop a scene with a script inheriting from a Godot object, you'll see the runtime incorrectly identifies it as the highest concrete built-in Godot type, rather than its actual type. If you flag it as a tool script, it will identify it correctly.

It seems while this oversight causes a crash when instantiated manually, even when instantiated automatically by the editor by dragging and dropping, it still gets the wrong type. This means when using C#, Godot requires all objects tool scripts interact with to also be tool scripts, which is definitely a huge problem.

### Steps to reproduce

Without MRP:
Create a tool script.
Add logic to instantiate a `PackedScene` that does not use a tool script via the editor.
In the editor, trigger logic.

With MRP:
Open the `Spawner` scene.
Drop either a `GreenCharacter` or `RedCharacter` to the packed scene export.
Click `Update Character`.

### Minimal reproduction project

[InstantiateBug.zip](https://github.com/godotengine/godot/files/10970205/InstantiateBug.zip)

**Comment by RedworkDE** [comment]
The crash is once again a case of https://github.com/godotengine/godot/pull/77377

As you are directly trying to use `Character` object in editor code, that script has to be marked as `[Tool]`.

**Comment by markdibarry** [comment]
@RedworkDE I was aware that a custom node will not run its lifecycle methods if it's not a tool script, but I was surprised to find out that the editor can't even determine if the type exists or not when referenced from a tool script. Either way, I just tested the MRP and it looks like it's no longer crashing, which was the main subject of this issue, so I'm closing it.
