### ISSUE TITLE
FastNoiseLite needs a very tiny frequency value to be used for VFX

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#74924]
### Godot version

4.0 stable

### System information

Fedora, RX 590

### Issue description

**EDIT see Calinou's comment for a proper implementation**

When using noise for dissolving my shaders, I have to put very tiny numbers and it's very hard to tweak it as-is. 
Because i think that changing how frequency would work, i propose to add a frequency multiplier value that makes scaling the noise easier
![Screenshot from 2023-03-14 22-36-10](https://user-images.githubusercontent.com/7917475/225143740-320fe240-38a2-4c6e-a5ee-7dcc2e5e251c.png)
![Screenshot from 2023-03-14 22-36-06](https://user-images.githubusercontent.com/7917475/225143746-0b08d982-3984-47c3-8eb2-49937c9d5422.png)
![Screenshot from 2023-03-14 22-36-36](https://user-images.githubusercontent.com/7917475/225143827-8fde908b-f85d-4035-ad48-43a7acf65742.png)

### Steps to reproduce

Use fast noise as an albedo texture on a quad. observe detail density.

### Minimal reproduction project

see above.

**Comment by Calinou** [comment]
I'm not fond of having two properties that ultimately affect a single value. I'd rather increase the precision of the frequency property hint so you can use values as small as `0.0001` instead.

**Comment by brno32** [comment]
I'd love to jump on this if I could have a little bit of guidance

**Comment by QbieShay** [comment]
Hello @brno32 ! Awesome that you want to take a look.

The line that needs changing is this one

https://github.com/godotengine/godot/blob/1d14c054a12dacdc193b589e4afb0ef319ee2aae/modules/noise/fastnoise_lite.cpp#L419

Where the step needs to change from .001 to .0001

**Comment by Calinou** [comment]
> I think the step size defaults to the value in "interface/inspector/default_float_step" (which happens to be .001). Do you mean to not use the default float step size and instead use .0001?

Yes :slightly_smiling_face:

**Comment by QbieShay** [comment]
Closed via https://github.com/godotengine/godot/pull/76683
