### ISSUE TITLE
[3.x] Post processing is broken in GLES2

### ISSUE THREAD

**Issue by Ansraer** [godotengine/godot#74932]
### Godot version

3.x

### System information

Win 10, gles2, 32gb ram, 5800x, rx6900xt, latest gpu driver

### Issue description

When you try to use a post-processing effect such as glow in the gles2 renderer you only get white output and glsl errors in the console. A quick check shows that the problem is the following cherry pick. Reverting it for the gles2 tonemap shader file fixes the problem.

https://github.com/godotengine/godot/commit/f1bafe8131db1233d5d0d5c46a8b98b11d8841bf

### Steps to reproduce

Create a GLES2 project, add an environment and enable glow.

### Minimal reproduction project

See above

**Comment by lawnjelly** [comment]
Paging @clayjohn . In the meantime reverting might be wise.

**Comment by clayjohn** [comment]
Looks like we wrongly renamed Texture2DLod to TextureLod. This is a very easy fix

**Comment by Khejanin** [comment]
I'm trying my hand at this if nobody minds

**Comment by Khejanin** [comment]
Should I submit a PR to the master or 3.x branch?

**Comment by clayjohn** [comment]
@Khejanin To the 3.x branch!

**Comment by lawnjelly** [comment]
Fixed by #74953 .
