### ISSUE TITLE
Importing assets problem

### ISSUE THREAD

**Issue by PancheteG3D** [godotengine/godot#74934]
### Godot version

Godot v4.0 stable win64

### System information

Windows 10

### Issue description

Hello!
I created a report on 5th March, with title "Transient parent has another exclusive child"
The report is exactly this one: https://github.com/godotengine/godot/issues/74450
Well.... I've been investigating more about the issue. The main problem is that when I open Godot, about 15-20 seconds later a FBX2glTF pops up (I have never wanted to import anything, but that window appears always for any reason).
This is exactly the window appearing:
![FBX2glTF](https://user-images.githubusercontent.com/66872192/225261510-b8675e09-539d-4997-a983-2c6842f73a08.png)

If I select Cancel, a little window appears, and then another bigger window appears aswell.
And those windows (with no text) remain loading there for ever, and nothing can be done in Godot, although the rest of the softwares work as always.
If I wanted to save a project, a "transient parent has another exclusive child" error appeared on the console. That's why I called the issue like that.
Well... That was what I reported firstly.
But now I've deleted every "godot" file in the computer, so maybe an older version was creating that issue.
And now... I see that the FBX2glTF appears again (with no reason) and on the little window now I've been able to read something....
![Godot_ufojbixl_1K_Specular](https://user-images.githubusercontent.com/66872192/225260669-c6afea6f-cdee-4708-bceb-94edfc451088.png)
The bigger window appeared again after the smaller one, and those windows remained there eternally. 
But at least I had something new for further investigation.
So, I looked for the file "ufojbixl_1K_Specular.jpg" and this is what I've found:
![ufojbixl_1K_Specular](https://user-images.githubusercontent.com/66872192/225262006-d51c5bf2-7259-4189-a179-96f7210ddd84.png)
The same thing happened in another test I did. In Godot, 15 seconds after opening, a FBX2glTF window appeared, and when canceling, the "(Re)importing assets" appeared, this time trying to importing a file called "slnnfac_Popup_3840_sp.jpg"
All these images come from a software called Quixel Mixer.
In summary.... for any reason, Godot insists on importing files from Quixel Mixer even if I haven't wanted to do that. 
Why? I don't know. Do you know? I guess the solution is not difficult now: Uninstall QuixelMixer.
Surely that will make Godot to work as it should. But the root of the problem is still there: Why does it want to import images from third softwares which don't have anything to do with Godot?
I have to say that on the console, it also has some errors trying to read files from other softwares. Here the console log:
![CannotOpenFile_Godot](https://user-images.githubusercontent.com/66872192/225267154-7a84b001-8372-462f-b16d-dfb4284b58e7.png)
There are some issues with Unigine or CryEngine, but the big problem is the "Cannot open file ... cross_stitching.glsl" or "Cannot open file ... radial_blur.glsl".... Those were files from Albatross3D. I had to remove that software in order to get out of those errors.
But that's the main issue: Why do Godot try to open third parties files at the start, with no reason? 
Please, save me from this nightmare! I want to test the new Godot 4.0! Thanks.

### Steps to reproduce

Since there are third softwares implied, I don't know how it would be reproducible for people who want to find a solution for this issue.

### Minimal reproduction project

N/A

**Comment by Zireael07** [comment]
The FBX issue is already reported and a fix will be in 4.0.1.

As for the rest - I think you made a project in your documents folder, not in a subfolder, therefore Godot is trying to import EVERYTHING in Documents folder

**Comment by PancheteG3D** [comment]
Thanks a lot @Zireael07 You're a lifesaver! :)
You're totally right. The project was located in the Documents folder. As feedback, I would propose (for dummies like me) some kind of "Hey... you're going to create a project in the Documents/Desktop folder... are you really sure?" Or a second option would be a console info saying "importing assets from C:\Users\username\documents", so if Godot freezes, at least you can see that problem goes from importing a huge amount of assets from Documents. But without help, it was a little hard to discover where the error comes from.
Thanks again! :)

**Comment by Zireael07** [comment]
IIRC it was suggested that Documents be totally disallowed as a project folder, but I can't find the issue #

**Comment by PancheteG3D** [comment]
@Zireael07 I support that proposal about disallowing Documents as a project folder (or if you select Documents, it may create a default folder inside Documents, kind of "New_Godot_Project_01" or something like that).
