### ISSUE TITLE
AnimationTrackKeyEdit 's Args Type can't change back to string type from other type except stringname.

### ISSUE THREAD

**Issue by kaluluosi** [godotengine/godot#74942]
### Godot version

4.0.dev

### System information

win11，core i7 13700,  GTX4090

### Issue description

Just look at this gif.

![screenshots](https://user-images.githubusercontent.com/1620585/225354749-6ea17059-95b2-45e0-9765-8505e92726eb.gif)

It seems that it was block by Static Type Checking.

![image](https://user-images.githubusercontent.com/1620585/225362874-507ff0ec-c6d8-4a25-9a16-89db1885ad02.png)

If it's right.

Why it doesn't just disable other option except for String and StringName?

### Steps to reproduce

1. first select string type
2. input a text
3. change type
4. change back to string  -- it don't work
5. change to stringname -- it works
6. change back to string -- it works

### Minimal reproduction project

I think it don't need reproduction project.

**Comment by AThousandShips** [comment]
Might have a solution to this will investigate

**Comment by TokageItLab** [comment]
This is due to the KeyEdit inspector being recreated every time a key is updated. I fixed a similar problem previously occurring with Time in https://github.com/godotengine/godot/pull/69797, so a similar solution may be needed.

**Comment by AThousandShips** [comment]
In this case it's due to an incorrect validity check in the editor, it tries to construct a `String` from types that aren't supported by `Variant::construct`
