### ISSUE TITLE
LightmapGI does not take into account the alpha channel of texture

### ISSUE THREAD

**Issue by ONION-777** [godotengine/godot#74947]
### Godot version

4.0.1 RC1

### System information

Windows 10

### Issue description

![image](https://user-images.githubusercontent.com/101945951/225404540-a38d7425-b812-46a2-bd3d-d74f9940e2b7.png)
Without baked light
![image](https://user-images.githubusercontent.com/101945951/225404567-7d8fc95c-b757-4591-b6d8-280d783a5c1a.png)
Baked Light

### Steps to reproduce

Create a new MeshInstance3D, add a texture with an alpha channel to it, in the material settings, set the alpha scissors . Create LightmapGI and bake the light

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
@ONION-777 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by ONION-777** [comment]
> @ONION-777 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

[Baking light.zip](https://github.com/godotengine/godot/files/10985192/Baking.light.zip)

**Comment by Calinou** [comment]
- Closing in favor of https://github.com/godotengine/godot/issues/77590, which contains both Godot 3 and 4 MRPs for easier comparison.
