### ISSUE TITLE
Cannot use 'backspace' key and key combinations are not working after alt-tabbing

### ISSUE THREAD

**Issue by sjharb** [godotengine/godot#74957]
### Godot version

4.0.1.rc1

### System information

Windows 11

### Issue description

The backspace key is not functioning in the 'Create New Node' pop-up in Godot 4.0.1.rc1.
Noted also that the Ctrl+A is not functioning for adding new child nodes in the scene tree.

No errors were shown in the logs or console.

Edit: After restarting Godot Editor, the backspace key was working.  So there must be more steps to reproduce this issue.
The Ctrl+A was also working after restarting Godot Editor.

### Steps to reproduce

Edit: After restarting Godot Editor, the backspace key was working.  So there must be more steps to reproduce this issue.
The Ctrl+A was also working after restarting Godot Editor.

Right click in the scene tree to add a new node.  Ctrl+A does not seem to be working either, another bug report.
Click on "Add Child Node"
Expected: "Create New Node" pop-up is shown.
In my test the text was re-populated with 'sprite'.
Press 'backspace' on the keyboard to delete the text.
Expected: The text is edited showing 'sprit'.
Actual: The text will not 'backspace' remove from the end.

Workaround:
Click the 'x' at the right on the textbox to delete the text.
Now you can type text in the textbox, but still cannot use 'backspace' key.

### Minimal reproduction project

Edit: After restarting Godot Editor, the backspace key was working.  So there must be more steps to reproduce this issue.
The Ctrl+A was also working after restarting Godot Editor.

**Comment by KoBeWi** [comment]
Can't reproduce. The dialog will use the previously used node name, but the text is selected. Pressing Backspace clears it.
You sure you had the text field active?

**Comment by sjharb** [comment]
> Can't reproduce. The dialog will use the previously used node name, but the text is selected. Pressing Backspace clears it. You sure you had the text field active?

Agreed, I was unable to re-produce also.  I must have gotten into a weird state some how.  I will update if I can figure out how to reproduce it.  The issue was not present upon restarting Godot Engine Editor.

**Comment by sjharb** [comment]
Had the same issue again, here is a video of me trying to use Backspace, and some other keyboard combinations like Ctrl+A, Ctrl+C Ctrl+V, Ctrl+S (not shown, but didn't let me save with the keyboard shortcut either). 

I think maybe it is related to loosing focus to another application (Chrome etc.), I was copying and pasting from an external web browser when I noticed it again.  Also opened the 3D advanced import settings.

https://user-images.githubusercontent.com/57383586/225711607-55846fd1-dc6f-46f7-8a88-66609fe5e35c.mp4

**Comment by Zireael07** [comment]
> I think maybe it is related to loosing focus to another application (Chrome etc.

Likely so. (BTW what is that you're using to show the pressed keys?)

**Comment by sjharb** [comment]
Thanks for the quick response!
Just Windows 11 On Screen Keyboard.  Worked pretty well to show my issue.
https://support.microsoft.com/en-au/windows/use-the-on-screen-keyboard-osk-to-type-ecbb5e08-5b4e-d8c8-f794-81dbf896267a
I could not find anything else that would by easier and actually register the keypresses accurately.

**Comment by sjharb** [comment]
Maybe this is fixed by:
https://github.com/godotengine/godot/pull/74535
and related to:
https://github.com/godotengine/godot/issues/74181

**Comment by YuriSizov** [comment]
One of the reports linking to this issue mentions that this is new to 4.0.1, and not present in 4.0. I don't immediately see [among the commits of 4.0.1](https://github.com/godotengine/godot/compare/284a1b6a6ec6acb5cefc9506b9a54efe196f9ee5...6970257cffc6790f4d7e847e87e5cab9e252874e) which one could be responsible. Would be great if someone who can reproduce this issue reliably bisects the commits between the two builds (linked above).

If you can't compile the engine yourself, you can also help by testing build artifacts from one of the cherry-pick PRs: [1](https://github.com/godotengine/godot/pull/74866), [2](https://github.com/godotengine/godot/pull/74884), or [3](https://github.com/godotengine/godot/pull/74907). You can read [here](https://docs.godotengine.org/en/stable/contributing/workflow/testing_pull_requests.html#downloading-a-compiled-build) how to use build artifacts for testing.

**Comment by SilicDev** [comment]
Could this be the same issue as this 3.x bug? https://github.com/godotengine/godot/issues/28511
Particularly the losing focus part reminds me of it.

**Comment by dandeliondino** [comment]
I experienced this multiple times the first day I used 4.0.1-rc1 on Windows 11. I only noticed it with backspace and only when typing inside line edits in editor dialog windows. The script editor was fine. Restarting Godot would fix it temporarily. If it returns, I'll try to see if I can reproduce what led to it.

**Comment by AThousandShips** [comment]
Does this go away if you press the Win key?

**Comment by dandeliondino** [comment]
> 

Finally happened again and, yes, Win key fixed it.
Can't seem to reproduce it again.

**Comment by AThousandShips** [comment]
Then this is connected with #75138

**Comment by leleleSDX** [comment]
Is it possible that is this caused by the "amount of time" the godot editor windows is left unfocused? Trying to reproduce it never seems to work. But when you're deep into a godot session you suddenly notice the keyboard shortcuts/backspace isn't working.

**Comment by AThousandShips** [comment]
Reproduce on what version?
