### ISSUE TITLE
Some dialogs are too big

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#74951]
### Godot version

4.0

### System information

Windows 10 x64

### Issue description

Some dialogs are too big. Examples:

Version confirmation in Project Manager
![image](https://user-images.githubusercontent.com/2223172/225405993-2a3be157-5151-4490-ac50-53621760fb02.png)

Quit confirmation for unsaved scenes
![image](https://user-images.githubusercontent.com/2223172/225417206-0739c679-5e04-4d20-a341-fd221cd86c4a.png)

The empty space should be trimmed. I tried using `reset_size()`; it doesn't work when called before popup and calling it after popup results in... this thing
![image](https://user-images.githubusercontent.com/2223172/225417875-7b29147b-4145-48d8-a9e0-b24ba0711f8b.png)

We might need a method that resets vertical size and call it for every popup that's too big. Not sure why resetting size *before* popup does not work though. This might be the root of this issue 🤔

### Steps to reproduce

1. Make project in some Godot version
2. Open it in a different version (4.0+)
3. Observe the warning dialog

### Minimal reproduction project

N/A

**Comment by YuriSizov** [comment]
The root of this issue is that we forced them to be this way to work around label recalculation issues 🙃 Which has since been fixed, I believe, so the changes can be reverted.
