### ISSUE TITLE
Godot 4 crashes from time to time

### ISSUE THREAD

**Issue by yudi-azvd** [godotengine/godot#74968]
### Godot version

v4.0.1.rc1.official (d23922ffebe48f29126c003411495737d07e5a9f)

### System information

Ubuntu 18.04.06 LTS

### Issue description

The crash usually happens when I have another window focused (browser) for sometime and then Godot crashes.

The backtrace:

```
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.1.rc1.official (d23922ffebe48f29126c003411495737d07e5a9f)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x3ef10) [0x7f61122a5f10] (??:0)
[2] /usr/local/bin/godot() [0x361d8d9] (??:0)
[3] /usr/local/bin/godot() [0x1108da4] (??:0)
[4] /usr/local/bin/godot() [0x361d88f] (??:0)
[5] /usr/local/bin/godot() [0x2e3add7] (??:0)
[6] /usr/local/bin/godot() [0x2c7899a] (??:0)
[7] /usr/local/bin/godot() [0x45714f4] (??:0)
[8] /usr/local/bin/godot() [0x2ac7606] (??:0)
[9] /usr/local/bin/godot() [0x4b8cde5] (??:0)
[10] /usr/local/bin/godot() [0x45e3117] (??:0)
[11] /usr/local/bin/godot() [0x2bd8b28] (??:0)
[12] /usr/local/bin/godot() [0xec1b76] (??:0)
[13] /usr/local/bin/godot() [0xe04023] (??:0)
[14] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f6112288c87] (??:0)
[15] /usr/local/bin/godot() [0xe2409e] (??:0)
-- END OF BACKTRACE --
================================================================
```

Maybe there is something related to `libc` in my machine. Running `ldd --version` gives me the following:

```
ldd (Ubuntu GLIBC 2.27-3ubuntu1.6) 2.27
```
Some notes:
- Right now I'm using `v4-rc1` but this was happening with `v4` stable as well
- My laptop is not that powerful, that's why I use Ubuntu 18
- I got these logs running the engine from the terminal

### Steps to reproduce

Honestly don't know. Maybe you can try running any small project.

### Minimal reproduction project

I don't think it's required.

**Comment by Calinou** [comment]
> Maybe there is something related to libc in my machine. Running ldd --version gives me the following:

This is unlikely – the crash backtrace often points to libc at first, but this doesn't mean this is a bug in the libc.

Can you try using a [debug build](https://github.com/Calinou/godot-debug-builds/releases) until it crashes to get a proper backtrace?

**Comment by yudi-azvd** [comment]
Now that posted this issue, I can't reproduce the crash anymore haha well... I'll try anyway

The download is taking way too long. I'll try it as soon as it finishes

**Comment by yudi-azvd** [comment]
I've built Godot 4 rc 1 from source. I'll be using it in the following days. Any crashes i'll report them here.

**Comment by Calinou** [comment]
> I tried downloading [godot-4.0-debug-template-linux-gcc9.3.zip](https://github.com/Calinou/godot-debug-builds/releases/download/v4.0/godot-4.0-debug-template-linux-gcc9.3.zip) and [godot-4.0-editor-debug-linux-gcc9.3.zip](https://github.com/Calinou/godot-debug-builds/releases/download/v4.0/godot-4.0-editor-debug-linux-gcc9.3.zip) but they are shared librearies?

File managers will sometimes report executables as shared libraries, but you can ignore this and run them as executables from the terminal.

**Comment by yudi-azvd** [comment]
Running from the terminal resulted in a error:

```
./Downloads/godot-4.0-editor-debug-linux-gcc9.3/bin/linux/godot.linuxbsd.editor.x86_64: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./Downloads/godot-4.0-editor-debug-linux-gcc9.3/bin/linux/godot.linuxbsd.editor.x86_64)
./Downloads/godot-4.0-editor-debug-linux-gcc9.3/bin/linux/godot.linuxbsd.editor.x86_64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./Downloads/godot-4.0-editor-debug-linux-gcc9.3/bin/linux/godot.linuxbsd.editor.x86_64)
```

I ran with 

```
./Downloads/godot-4.0-editor-debug-linux-gcc9.3/bin/linux/godot.linuxbsd.editor.x86_64
```

**Comment by yudi-azvd** [comment]
@Calinou 

This time it didn't take too long. I was editing a `.gd` script in vscode, hit Ctrl + S and then the crash happend.

[godot_backtrace.txt](https://github.com/godotengine/godot/files/10996380/godot_backtrace.txt)

I think the important content is in the middle of file. The `ERROR: Index p_gutter = -1 is out of bounds (gutters.size() = 4)` messages are some errors I get every time I save a script file in vscode.

Note: "Use External Editor" option is _not_ ticked. Should Godot crash still?

**Comment by yudi-azvd** [comment]
Another thing: I think the dev build keeps creating some extra empty files like the following:

```
WeaponManager.tscn-AtWnlA
PlayerAnimatedSprite.tscn-2R0Ba4
Player.tscn-7ThPDN
project.godot-YRZ0f8
```

Is this normal? How do you keep them out git tracking?

**Comment by YuriSizov** [comment]
That last bit is a regression from https://github.com/godotengine/godot/pull/73156.

**Comment by yudi-azvd** [comment]
@YuriSizov I think you are correct. First I've built the `master` branch by mistake. I noticed it then built the `4.0` and it's the one I'm using now. Since then these extra files did not appeared.

**Comment by yudi-azvd** [comment]
I've been using the dev build of the `4.0` branch and the crashes (as reported in this [link](https://github.com/godotengine/godot/files/10996380/godot_backtrace.txt)) have not occurred. 

@Calinou I think it's OK if this issue is closed.

**Comment by Calinou** [comment]
Alright, closing then.
