### ISSUE TITLE
Exported arrays of type Array[Node] cannot have nodes assigned to them in editor.

### ISSUE THREAD

**Issue by Puppyguarb** [godotengine/godot#74975]
### Godot version

4.0.stable

### System information

Windows 10, NVIDIA GeForce GTX 1650 SUPER, Vulkan

### Issue description

Exporting an array with a type of Array[Node], where node can be any class that inherits from node, will result in an array that cannot have anything assigned to it from editor.

Interestingly, the Array appears to be typed Array[Object], rather than Array[Node]. Maybe related to #74712?
![image](https://user-images.githubusercontent.com/88409694/225546368-feed551a-ce03-4661-9537-6f5cfd6aa554.png)

### Steps to reproduce

1. Create a script and attach it to a node.
2. Export an array with type Array[Node]. Here is a simple way of how you could do that in code:
`@export var export_array : Array[Node] = []`
3. (optional) Add a new node into the currently open scene to add onto the array. 
4. Add an entry to the array with the drop-down on the right.
5. Try and assign a node to the exported array.

### Minimal reproduction project

Included below is a project with a main node, a node with the export script, an object node (which can be ignored if you prefer.), and an export script. I have added an extra line to the export script which should demonstrate how the export annotation usually behaves without an array.

[ExportArrayIssueProject.zip](https://github.com/godotengine/godot/files/10987898/ExportArrayIssueProject.zip)

**Comment by YuriSizov** [comment]
Yes, indeed. Thanks!
