### ISSUE TITLE
Nonexistent function get_mouse_position in base 'Window'

### ISSUE THREAD

**Issue by RonYanDaik** [godotengine/godot#74979]
### Godot version

4.0 stable

### System information

Windows 10, GeForce RTX 3080

### Issue description

Calling to get_viewport().get_mouse_positison() in process() of Node (or anywhere else) returns this Error:

`Nonexistent function get_mouse_positison in base 'Window'`

### Steps to reproduce

Cant tell how to reproduce. Yesterday everything was working fine.  Today I'm getting this issue. This happens anywhere.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
You have a spelling mistake, it is `get_mouse_position()`, make sure to check your spelling

**Comment by AThousandShips** [comment]
No problems, it happens to everyone
