### ISSUE TITLE
NOTIFICATION_UNPARENTED happens right before actual unparenting

### ISSUE THREAD

**Issue by lightspeedlucas** [godotengine/godot#7497]
Hello! In Node's remove_child implementation we see that NOTIFICATION_UNPARENTED is 'raised' before the child is actually unparented:

```
p_child->notification(NOTIFICATION_UNPARENTED);
data.children.remove(idx);
...
p_child->data.parent=NULL;
```

Is this by design? If so, what is the reasoning? I was trying to use it so that when a child is removed it signals its ex-parent to refresh some calculations that involve going through its siblings asking for some data. But the removed child is still part of the children list, making such refresh meaningless.

I'm using a workaround right now, but I thought I'd ask since I found it a bit weird.

**Comment by reduz** [comment]
the reasoning is that you still have the parent node or scene available to
deconfigure whathever you need. If you need to be notified afterwards, you
can always do call_deferred("somefunc") from the UNPARENTED notification

**Comment by lightspeedlucas** [comment]
Makes sense! Thanks.
