### ISSUE TITLE
Visual script node "definition"

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#7498]
The GraphEditor nodes in Visual Script editor are called "nodes" like the rest of Godot Nodes.

I think these nodes should get another name before implementing Visual Scripting on a stable release to prevent lot of confusion when making references to nodes (in docs, tutorials, et cetera).

I've realized this when I was trying to make a reference to a VS node...

**Comment by bojidar-bg** [comment]
Well, let's call them VSN-s then?

Actually, how can we even call them? Scriptlets? Tiles? Those-thing-you-connect-in-VS? Connectors? Computators? Guess I'm not too good at picking names...

**Comment by eon-s** [comment]
@bojidar-bg Scriptlet sounds nice, I have thought on "Component" but I think that is already taken by Other Engine (TM)

**Comment by Zylann** [comment]
Since it's breakage-day, renaming Node and Node2D to Entity and Entity2D would fix it :]

States? Ah no would be confused with FSMs. Block?
Having no namespaces and all classes for everything in the same scope doesn't helps, unless prefixing is used^^"

**Comment by hubbyist** [comment]
"lump" may be used for VS nodes as well IMO since they can be any of combination of nodes and grouping them into bigger lumps is mostly desired.

**Comment by hubbyist** [comment]
'hunk' may be used for VSnodes as in well IMO since grouping them into bigger hunks is mostly desired.

**Comment by bojidar-bg** [comment]
@Zylann There is already Node2D, so better if we don't :laughing: 

I think Block/Element/Tile are the best so far.

**Comment by akien-mga** [comment]
I think VSNode is fine, the objects you can move around in a GraphEdit node are already named GraphNode IINM.

**Comment by eon-s** [comment]
@bojidar-bg in the end is a code block in the form of graph node, so `Block` sounds good too and comparable to GDScript code blocks.

**Comment by Zylann** [comment]
@eon-s it might be, but what does "Block" tells you as a name on its own along all other class names in the engine?

**Comment by eon-s** [comment]
@Zylann block says nothing (to me, at least), and won't be confusing with the scene nodes (which are many by default, more if extended and even more with custom Visual Stu... Script nodes).

Variables, conditions, functions all will soon be "Nodes" too.

"CallInstance Node" or "Lerp Node" may put your head on the Node class tree looking for those, and Sprite for some could be sprite for others, both could be Nodes. 

-----------------------

"sprite block" will be clear, a sprite instance/variable, not a Node.

"If block" sounds like a code block and the concept is the same for graph and text scripting (not the same for "if node").

-----------------------

I could be wrong too and this ambiguity might be better...


ps: and what aobut VSCode::Blocks?

**Comment by reduz** [comment]
I think it's fine as it is, may not be perfect, but nothing that comes to
mind is better.
