### ISSUE TITLE
Crash on renaming an audio bus

### ISSUE THREAD

**Issue by Lord-Vlad** [godotengine/godot#74981]
### Godot version

v4.0.stable.flathub (92bee43ad)

### System information

Fedora 37 KDE, Compatibility, NVIDIA

### Issue description

Crash on naming an  audio bus.

### Steps to reproduce

1. Got to the audio tab.
2. Add a new audio bus.
3. Change the name and hit enter.
4. Godot freezes for a second and then crashes.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Duplicate of #74374, fixed in #74560

**Comment by YuriSizov** [comment]
Yes indeed, thanks.
