### ISSUE TITLE
Godot 4.0 Control Node transforms are locked. Limited usage.

### ISSUE THREAD

**Issue by shafnaz** [godotengine/godot#74989]
### Godot version

4.0

### System information

Windows 10

### Issue description

In Godot 3.x i can tween animate the scale of a button node or a  label node to give it a bounce effect. If the label is in a container, the transform parameters become locked, In code, it's also locked.

![image](https://user-images.githubusercontent.com/37254287/225685849-59f72986-528f-4f62-870e-6e9a5f007a66.png)

### Steps to reproduce

Add label nodes or any control nodes to a container such as a VBoxContainer

### Minimal reproduction project

No need.

**Comment by Zireael07** [comment]
Containers determine position of children. If you want to tween your controls, don't put them into a container. The previous way was a bug

**Comment by shafnaz** [comment]
Actually, it still works in code....
