### ISSUE TITLE
Godot 4 fails to call _init() and _ready() functions in extended classes.

### ISSUE THREAD

**Issue by importerfive** [godotengine/godot#74992]
### Godot version

4.0.stable

### System information

Windows 10

### Issue description

In Godot 4 Stable, when a node with a script extends to another script "Extended," `_init()` and `_ready()` are not called in Extended.
This is a mismatch with what happens in Godot 3.5.1 Stable, where the script you are extending to also has its `_init()` and `_ready()` functions called.

### Steps to reproduce

Make two scripts; the _Extended_ script and the _Extender_ script. Have Extender extend to Extended.

Make Extended print "Initialized" in `_init()` and "Ready" in `_ready()`.

Make a Scene Node with script Extender attached and run the project. "Initialized" and "Ready" fail to print from Extended.

The screenshots below debug print in both scripts and have named classes for demonstrative purposes.

Godot 4.0 Result:
![GD4 0_extension_test](https://user-images.githubusercontent.com/128074531/225701532-f4182905-07d1-4434-b5b9-b074f13f8321.PNG)

Godot 3.5.1 Result:
![GD3 5 1_extension_test](https://user-images.githubusercontent.com/128074531/225701708-579f7b57-a4d4-4e8d-9c63-78709078c755.PNG)

Code 4.0:

```
class_name Extended
extends Node


func _init() -> void:
	print_debug("Extended Inited.")


func _ready() -> void:
	print_debug("Extended Ready.")



class_name Extender
extends Extended


func _init() -> void:
	print_debug("Extender Inited.")


func _ready() -> void:
	print_debug("Extender Ready.")
```

Code 3.5.1:
(Identical)
```
class_name Extended
extends Node


func _init() -> void:
	print_debug("Extended Inited.")


func _ready() -> void:
	print_debug("Extended Ready.")



class_name Extender
extends Extended


func _init() -> void:
	print_debug("Extender Inited.")


func _ready() -> void:
	print_debug("Extender Ready.")
```

### Minimal reproduction project

Reproduction steps are trivial.
[extending_test_projects.zip](https://github.com/godotengine/godot/files/10993906/extending_test_projects.zip)

**Comment by importerfive** [comment]
> You might have to call the super functions explicitly and they won't be called automatically
> 
> See: #594 and #40670

Ah, It's intentional. Thanks for your reply, I'll use super().

**Comment by AThousandShips** [comment]
No problems!

**Comment by SamMakesCode** [comment]
The way to call the `_ready()` function in the parent script is by using `super()` in case anyone needs that and Google led them here.

**Comment by elbroandrew** [comment]
I do not have a parent script and the `_ready()` function is not called anyway in `RoomGenerator` class.
The code:
```gdscript
room.gd

extends Area2D

static var count: int = -1
var id: int

func _increment_id():
	count += 1
	return count

func _init() -> void:
	id = _increment_id()

func _ready() -> void:
	pass

```
```gdscript
RoomGenerator.gd

extends Node

var Room = preload("res://Scenes/Room.tscn") 

var rooms = []


func _init() -> void:
	for x in range(2):
		rooms.append(Room.instantiate())

func _ready() -> void:
	pass # this ready function cannot be called
```

```gdscript
main.gd

extends Node2D

var RoomGenerator = preload("res://Scripts/ProcGen/RoomGenerator.gd")
var generator = RoomGenerator.new()


func _ready():
	var rooms = generator.rooms
	for room in rooms:
		add_child(room)

```
