### ISSUE TITLE
PopupMenu.always_on_top error on gui_embed_subwindows = false

### ISSUE THREAD

**Issue by Juna-Idler** [godotengine/godot#75001]
### Godot version

4.0.1.rc1

### System information

Windows10

### Issue description

```
	get_viewport().gui_embed_subwindows = false
	$PopupMenu.always_on_top = true
```
and
```
	$PopupMenu.popup(Rect2(pos,Vector2.ZERO))
```
E 0:00:01:0997   test.gd:18 @ _on_button_pressed(): Windows with the 'on top' can't become transient.
E 0:00:03:0264   window_set_transient: Condition "wd_window.transient_parent == p_parent" is true.

If it's just this, there's actually no problem, but when I add a submenu, there's a real problem.

if `PopupSubMenu.always_on_top = false`
Hide under "always ontop window"

else `PopupSubMenu.always_on_top = true`
The popup menu itself disappears before the submenu is displayed

### Steps to reproduce

When you press the center button, a pop-up menu will appear on the upper left across the border of the window, so please mouse over it

### Minimal reproduction project

[embed_popup_menu.zip](https://github.com/godotengine/godot/files/10995754/embed_popup_menu.zip)

**Comment by AThousandShips** [comment]
Popups are always transient so they can't be set to always on top, and from the documentation it sounds like transient means on top of the parent window

**Comment by Juna-Idler** [comment]
In fact, when displaying a popup menu in an always_on_top parent window, if the popup menu is not set to always_on_top, it will be hidden behind the parent window and will not work.
In the case of a single popup menu, it works as expected (although I get an error message).
There is no problem if the child window of the always_on_top window is displayed in front without any flags.(but it isn't)

**Comment by Juna-Idler** [comment]
Close this and open a new issue with just the functional defect.
