### ISSUE TITLE
Option to change export dynamically via script

### ISSUE THREAD

**Issue by Gibbz** [godotengine/godot#7500]
**Operating system or device - Godot version:**
2.1
ubuntu 16.04

**Issue description** (what happened, and what was expected):
Example I have the following script. But it doesn't work. 
I want a way to be able to change "myArray" in my script and have it update for the user (the export chatacter_name) choices are updated from the myArray on init, but also for the script to be able to update this during execution.

tool
var myArray = ["1st yo", "2nd hey"]
export(String, myArray) var character_name

func _init():
		myArray.append("3rd option")

**Comment by bojidar-bg** [comment]
Note that this is doable with overriding `_get_property_list` in your GDScript.

**Comment by supagu** [comment]
Here is an example:

`func _get_property_list():
	var property_info = {
	    "name": "category/property_name",
	    "type": TYPE_INT,
	    "hint": PROPERTY_HINT_ENUM,
	    "hint_string": "one,two,three"
	}
	return [property_info]`

**Comment by Noshyaar** [comment]
Closing as solution exists. Please let us know if this is a mistake.
