### ISSUE TITLE
`SubViewport` + `ViewportTexture` doesn't work when created programmatically

### ISSUE THREAD

**Issue by bluenote10** [godotengine/godot#75008]
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Ubuntu 22.04, GeForce GTX 980

### Issue description

Creating a `SubViewport` + `ViewportTexture` programmatically doesn't seem to work. The content of the viewport is simply not visible, and there are debugger errors:

![image](https://user-images.githubusercontent.com/3620703/225763924-b0198a29-5d4b-4ed5-9382-2cd0cd10ab12.png)

The message `Viewport Texture must be set to use it` on first glance suggests that this is another manifestation of #66247, but in this case it is not a false error: The issue in #66247 seems to go away when setting the update mode to "always". That's not the case with the issue I'm facing. Also, creating exactly the same scene tree statically in the editor works, which indicates that the issue has rather something to do with creating the `SubViewport` + `ViewportTexture` programmatically.

### Steps to reproduce

Simply use a single `Node` as the scene root with this script attached:

```gdscript
extends Node


func _ready():
    # Create the viewport, add something to it, and add it to the scene tree:
    # Note that setting UPDATE_ALWAYS doesn't help.
    var viewport = SubViewport.new()
    viewport.render_target_update_mode = SubViewport.UPDATE_ALWAYS
    add_something_to_viewport(viewport)
    add_child(viewport)
    
    # Now that the viewport has a path, we can create a texture and connect it:
    var viewport_texture = ViewportTexture.new()
    viewport_texture.viewport_path = viewport.get_path()

    # Finally create a sprite that uses the viewport texture:
    var sprite = Sprite2D.new()
    sprite.centered = false
    sprite.texture = viewport_texture # <== this line causes debugger errors
    add_child(sprite)


func add_something_to_viewport(viewport: SubViewport):
    var label = Label.new()
    label.text = "Hello world"
    viewport.add_child(label)
```

The example builds this scene tree dynamically:

![image](https://user-images.githubusercontent.com/3620703/225763352-67a723fd-bf78-4b70-bbac-f523f08bf21e.png)

For comparison I have created another minimal project, where I'm creating exactly the same scene tree statically in the editor:

![image](https://user-images.githubusercontent.com/3620703/225763489-556676d7-c357-4848-ac69-f8a54569e6b8.png)

In this case the `SubViewport` + `ViewportTexture` works, i.e., the contents of viewport are visible.

### Minimal reproduction project

Full minimal reproduction:
- [ProgrammaticViewport.zip](https://github.com/godotengine/godot/files/10996260/ProgrammaticViewport.zip)
- [Code on GitHub](https://github.com/bluenote10/GodotDebugProjects/tree/master/Godot4/ProgrammaticViewport)

**Comment by Rindbee** [comment]
In this case, it is recommended to obtain `ViewportTexture` directly from `Viewport`.
```GDScript
#var viewport_texture = ViewportTexture.new()
var viewport_texture = viewport.get_texture()
```

**Comment by smix8** [comment]
When you create ViewportTextures in script you creating an unlinked / empty texture as rendertarget.
Setting the path on the ViewportTexture does nothing expect setting the path variable on the ViewportTexture.

You need to use the `texture_proxy_create()` and `texture_proxy_update()` functions of the RenderingServer to link rendertargets together. If you use Viewport.get_texture() this is done for you in the background. The returned ViewportTexture is just a wrapper for a texture that was proxy linked in the background.

**Comment by bluenote10** [comment]
@Rindbee @smix8 Thanks for the clarification! Indeed, using `Viewport.get_texture()` works just fine. I took the opportunity to simply [document this external on StackOverflow](https://stackoverflow.com/q/75770515/1804173), which is maybe already sufficient in terms of documenting the behavior?
