### ISSUE TITLE
Rigidbody collision against CSG Primitive doesn't always trigger on_body_entered signal

### ISSUE THREAD

**Issue by Griiimon** [godotengine/godot#75018]
### Godot version

3.5 and 4

### System information

Windows 10

### Issue description

I had this issue in Godot 3.5 ( default physics engine ) that my ball ( Rigidbody, sphere collider ) wouldn't reliably report a contact (body_entered signal) with the CSGTorus Basketball hoop rim. I thought this was down to the torus.

Now I just went on a bug hunt with somebody on the Discord server and we figured out that he didn't get reliable contact reports in a completely different project ( Godot 4 ) between a Rigidbody with a capsule collider and a CSGBox.

In both cases neither our Rigidbodies, their collision shapes or the CSG Primitives were scaled via the transform. We observed the collisions happening, the Rigidbodies bouncing off when there was no signal. Most of the time the signal triggered correctly, though. Obviously, signals and reported contacts were setup correctly since we received signals.

Since CSG primitives are only supposed to be used in prototyping anyway i assume the priority to fix this wouldn't be very high. But it should be mentioned in the docs at least.

### Steps to reproduce

run the scene, hold down left mouse button and shoot to the ground with this angle 

test in both StaticBody3D and CSGBox

![image](https://user-images.githubusercontent.com/25064539/225846028-9b412173-c1d4-43ae-8d28-f7ccfa972b7e.png)

first person view

![image](https://user-images.githubusercontent.com/25064539/225846242-d35160d2-8621-4381-825f-b3defefb8278.png)

### Minimal reproduction project

The reproduction project is for Godot 4!

[csg-collider.zip](https://github.com/godotengine/godot/files/10999042/csg-collider.zip)

**Comment by venilark** [comment]
![image](https://user-images.githubusercontent.com/98270528/225866043-ddb1f358-8642-4557-a38a-d2732d730815.png)
here with spheres and boxes

**Comment by Calinou** [comment]
I can confirm this on 4.0.stable (Linux).

- Doubling Physics Ticks Per Second (from 60 to 120) resolves the issue.
- Doubling the CSGBox's thickness doesn't resolve the issue.

**Comment by substract** [comment]
Hello, I noticed there is also a problem with RigidBody3Ds colliding with CharacterBody3Ds that might be related!
This happens when a somewhat faster (but note extremely so) RigidBody3D hits a CharacterBody3Ds which is also moving in the same direction, but slower. The RigidBody3D hits and will then be in a "floaty" state, there is also no body_entered signal triggered.
Is that a known issiue? I couldn't find any reports on it.

**Comment by venilark** [comment]
> Hello, I noticed there is also a problem with RigidBody3Ds colliding with CharacterBody3Ds that might be related! This happens when a somewhat faster (but note extremely so) RigidBody3D hits a CharacterBody3Ds which is also moving in the same direction, but slower. The RigidBody3D hits and will then be in a "floaty" state, there is also no body_entered signal triggered. Is that a known issiue? I couldn't find any reports on it.

can confirm this, it happened to me, rigidbodies are completely unreliable right now

**Comment by rburing** [comment]
Sorry, I introduced this CCD bug in 4.0-stable and it remained in 4.0.1.

It's fixed by https://github.com/godotengine/godot/pull/74861 which is in 4.0.2-rc1.

**Comment by substract** [comment]
> Sorry, I introduced this CCD bug in 4.0-stable and it remained in 4.0.1.
> 
> It's fixed by #74861 which is in 4.0.2-rc1.

I just tested it in Godot 4.0.2 and the problem I described is still there, sadly :(

**Comment by venilark** [comment]
> > Sorry, I introduced this CCD bug in 4.0-stable and it remained in 4.0.1.
> > It's fixed by #74861 which is in 4.0.2-rc1.
> 
> I just tested it in Godot 4.0.2 and the problem I described is still there, sadly :(

could you please upload a test project so they can see it in action?

**Comment by substract** [comment]
OK, will do!

**Comment by venilark** [comment]
> Sorry, I introduced this CCD bug in 4.0-stable and it remained in 4.0.1.
> 
> It's fixed by #74861 which is in 4.0.2-rc1.

I still have this problem in 4.0.2
