### ISSUE TITLE
4.0 http.connect() error

### ISSUE THREAD

**Issue by flobotics** [godotengine/godot#75010]
### Godot version

4.0-stable

### System information

win 11

### Issue description

When i use code from https://docs.godotengine.org/de/stable/tutorials/networking/http_request_class.html 

```
var http = HTTPRequest.new()
	http.connect("request_completed", self, "on_request_completed")
```

and run it, it returns:

Invalid argument for connect() function: argument 2 should be Callable but is "res://mytest.gd"

### Steps to reproduce

run it

### Minimal reproduction project

https://docs.godotengine.org/de/stable/tutorials/networking/http_request_class.html

**Comment by KoBeWi** [comment]
Looks like outdated documentation page (not class reference). You should open issue in https://github.com/godotengine/godot-docs instead.
The code should be `http.request_completed.connect(on_request_completed)`
