### ISSUE TITLE
`SubViewport`s dont process object picking when under `Panel` with mouse mode set to stop

### ISSUE THREAD

**Issue by bend-n** [godotengine/godot#75015]
### Godot version

92bee43ad 4.0.stable

### System information

ArchLinux x11

### Issue description

If a panel is above a viewport in the tree, the viewport does not process object picking.
```gdscript
Panel # needs mouse mode to be set to ignore, if it isnt set to ignore, object picking doesnt occur.
└── SubViewportContainer
    └── ViewportContainer
        └── StaticBody3D
```

I believe this is non standard behaviour, as `Panel` -> `Button` works just fine.

### Steps to reproduce

- Run `view.tscn` in mrp
- Verify that it prints `input` when you mouse over the cube
- Run `main.tscn`
- See that it no longer prints `input` when you mouse over the cube

### Minimal reproduction project

[bug.zip](https://github.com/godotengine/godot/files/10998751/bug.zip)

**Comment by Sauermann** [comment]
It looks like while the mouse is over the `SubViewportContainer`, Godot believes that the mouse is over the `Panel`.
I need to test, if this problem is solved by #67791.
