### ISSUE TITLE
Custom class in Autoload script do not have autocompletion

### ISSUE THREAD

**Issue by nilan256** [godotengine/godot#75021]
### Godot version

v4.0.1.rc1.official [d23922ffe]

### System information

MacOS 13.2, Mac mini(Inter chip)

### Issue description

Please review the issues in the video.

https://user-images.githubusercontent.com/24468033/225860661-c85ca14b-49d6-45cf-8c93-006fb862deac.mov

Here is my autoload setting.

![autoload-setting](https://user-images.githubusercontent.com/24468033/225861248-784da504-1f58-444f-88fb-5b20156ea30a.png)

As shown in video, custom class in autoload script has no autocompletion hints.
But declare the autoload type as a variable seems correctly, like the "g" variable in video.

Just a guess, it seems be able to infer the type, just broken in autocompletion.
If type the following code:
```
Globals.dog.age = "a string"
```
Even "age" is no static references, you can't "Command + click" to jump to declaration.
But the editor will alert an error "String to Int".

I have tried the Internal class Sprite2D is ok, all works fine.

### Steps to reproduce

1. Create a gdscript , and set to "Autoload". 
2. Add a variable of custom type (Node or Object)
3. Open another gdscript file
4. Type some code to access members of your custom type. 

### Minimal reproduction project

[autoload-no-autocompletion.zip](https://github.com/godotengine/godot/files/10999826/autoload-no-autocompletion.zip)

**Comment by AThousandShips** [comment]
Is this the same as #74888

**Comment by nilan256** [comment]
> Is this the same as #74888?

oh, yes, I missed this similar issue.
The only difference is I'm use a variable of autoload, but not a returned of function.
I tried:
```
var dog = Globals.dog as Animal
dog.jump() # autocompletion correctly
```

Should I close the issue? I'm first report an issue on github.

**Comment by AThousandShips** [comment]
If it covers your issue then yes, otherwise keep it open, or if you're unsure

**Comment by nilan256** [comment]
> If it covers your issue then yes, otherwise keep it open, or if you're unsure

I think that after the problem is fixed should also solve my problem.
Thank you.

**Comment by AThousandShips** [comment]
No problem!
