### ISSUE TITLE
Master build died

### ISSUE THREAD

**Issue by erikbgithub** [godotengine/godot#75029]
### Godot version

Godot Engine v4.1.dev.custom_build.1e0f7a12f

### System information

Ubuntu 22.10 on Thinkpad T580

### Issue description

Godot died. I will update the headline once it's more clear what happened.

I built Godot from master as usual, and while working through [this tutorial]() I ran into some bugs in my code. While trying to debug them, Godot hanged up completely and this is the debug messages I got on the shell:

```
Running: /home/erik/coding/godot/bin/godot.linuxbsd.editor.x86_64 --path /home/erik/games/hackerspace --remote-debug tcp://127.0.0.1:6007 --editor-pid 3278 --position 385,138 res://scenes/mainmenu.tscn
Godot Engine v4.1.dev.custom_build.1e0f7a12f - https://godotengine.org
Vulkan API 1.3.224 - Forward Mobile - Using Vulkan Device #0: Intel - Intel(R) UHD Graphics 620 (KBL GT2)
 
start pausing
pause func start
pause func end
door at (1, 10)
player at(15, 3)
key at (9, 11)
ERROR: Attempted to free invalid ID: 0
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8394)
ERROR: Attempted to free invalid ID: 0
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8394)
ERROR: Attempted to free invalid ID: 0
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8394)
ERROR: Attempted to free invalid ID: 0
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8394)
ERROR: Attempted to free invalid ID: 0
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8394)
ERROR: Condition "!shader" is true.
   at: shader_free (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2453)
ERROR: Condition "!material" is true.
   at: material_free (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2686)
ERROR: Cannot save file 'res://scenes/pause_menu.tscn'.
   at: save (scene/resources/resource_format_text.cpp:1964)
ERROR: Cannot save shader 'res://scenes/pause_blur.gdshader'.
   at: save (scene/resources/shader.cpp:279)
X connection to :0 broken (explicit kill or server shutdown).
ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
ERROR: BUG: Unreferenced static string to 0: thread_end
   at: unref (core/string/string_name.cpp:129)
   at: _update_swap_chain (drivers/vulkan/vulkan_context.cpp:1970)
ERROR: Condition "err != OK" is true. Returning: ERR_CANT_CREATE
   at: _window_create (drivers/vulkan/vulkan_context.cpp:1698)
ERROR: BUG: Unreferenced static string to 0: _compression
   at: unref (core/string/string_name.cpp:129)
```

### Steps to reproduce

1. Build Godot at 1e0f7a12f
2. Check out this commit: https://github.com/Play2Learn-Org/hackerspace/tree/94f71594ba5dcf480e1106d49df8d0ae303e3f9d
3. Import into Godot.
4. Start the game. Then stop the game.

As I'm not fully sure how I created the hang-up, I'm not sure if that's enough.

### Minimal reproduction project

For now just this:

https://github.com/Play2Learn-Org/hackerspace/tree/94f71594ba5dcf480e1106d49df8d0ae303e3f9d

**Comment by erikbgithub** [comment]
FYI: Currently, the computer I experienced this on doesn't exist anymore. I have the opportunity to sometimes use other people's computer. Therefore, for now I decided to mostly use release builds on Windows 11. I will probably research next how well I could use a hosted web instance of Godot if that is possible.

Question is, how can I continue to help with issues like this one here?

**Comment by Calinou** [comment]
Closing, as it lacks clear reproduction steps and a minimal project.
