### ISSUE TITLE
Global shader uniform vec4 does not accept Vector4 when setting

### ISSUE THREAD

**Issue by Grix** [godotengine/godot#75033]
### Godot version

4.0 (.NET)

### System information

Windows 11

### Issue description

I have a global uniform vec4 in my shader. I was trying to set this value from code, using:

`RenderingServer.GlobalShaderParameterSet("vector4test", new Vector4(1f, 0.0f, 0.0f, 1.0f))`

This did not work, it seems the uniform was still at some default or invalid value. This is confirmed by running this afterwards:

`RenderingServer.GlobalShaderParameterGet("vector4test").As<Vector4>()`

Which also returns a zero'ed Vector4, not the vector I passed in.

After some time of head-scratching, I tried passing the value as a Plane instead of a Vector4. Then, it worked.

The [documentation](https://docs.godotengine.org/en/stable/tutorials/shaders/shader_reference/shading_language.html) says that Vector4 type can be used to set vec4 shader types in GDscript (no mention of C# but I assume it should be the same). However this implementation seems to be broken.

### Steps to reproduce

Run attached project. Observe that nothing is visible. Change the line in the MeshInstance3D.cs script and observe that the plane with the shader suddenly appears when running it again.

### Minimal reproduction project

[Vector4Test.zip](https://github.com/godotengine/godot/files/11003334/Vector4Test.zip)

**Comment by bitsawer** [comment]
Should be fixed by https://github.com/godotengine/godot/pull/74937

**Comment by QbieShay** [comment]
wrongly reopened this one, please open a new one if the issue persists
