### ISSUE TITLE
Use `@export`+`getset`+`get_node()` in the inheritance scens. `get_ node()` will use the wrong path

### ISSUE THREAD

**Issue by zedrun00** [godotengine/godot#75036]
### Godot version

v4.0.1.rc2.official [6970257cf]

### System information

win10 21H2,Vulkan API 1.2.0

### Issue description

![p1](https://user-images.githubusercontent.com/104408400/225973809-6d49e8ef-55e2-46ff-880e-b2d00a4eaa57.PNG)

![p_2](https://user-images.githubusercontent.com/104408400/225973835-ede665be-ac3c-41e1-824e-f22bf9599255.PNG)

### Steps to reproduce

I don't know if this is a issues. If I don't use **@export**, godot will work properly

### Minimal reproduction project

[test_get_node.zip](https://github.com/godotengine/godot/files/11004011/test_get_node.zip)

**Comment by adamscott** [comment]
This isn't an issue.

This is normal, as the node is not yet ready. The class will be initialized and code will be run even if it's not possible yet to access children node.

I suggest you to read about [the @onready annotation](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#onready-annotation). Then, in the setter function, you'll have to add a if condition to test if your variable is set before using it.

**Comment by zedrun00** [comment]
> thanks , Using `@export` annotation will run the code . I wish I had known earlier.

**Comment by KoBeWi** [comment]
Closing per above comments.
See also https://github.com/godotengine/godot-proposals/issues/325
