### ISSUE TITLE
Did we lose a menu item?

### ISSUE THREAD

**Issue by erikbgithub** [godotengine/godot#75057]
### Godot version

Godot Engine v4.1.dev.custom_build.a7d0e18a3

### System information

Ubuntu 22.10 on Thinkpad T580

### Issue description

Yesterday in `Godot Engine v4.1.dev.custom_build.1e0f7a12f` I still had a menu item `Rect` on the right side, where you could choose a minimum size for the panel:

![](https://i.imgur.com/dEeTuND.png)

Today we don't have that anymore:

![](https://i.imgur.com/b69wGNV.png)

Is there another location or did that get lost with some recent internal changes, eg. https://github.com/godotengine/godot-proposals/issues/5903

### Steps to reproduce

see above

### Minimal reproduction project

any project with a `PanelContainer` should do.

**Comment by YuriSizov** [comment]
Control layout options in the inspector has been significantly reworked in Godot 4.0. They are functionally the same, but laid out differently to improve clarity. Everything is now under the "Layout" section, with more groups inside of it. See https://github.com/godotengine/godot/pull/55157.

But that happened in Godot 4.0, this has been a thing for over a year, and present in all betas and RCs. I'm not sure where your first screenshot is taken from, but it's not from 4.1 or 4.0. The editor theme also doesn't line up.

**Comment by erikbgithub** [comment]
[This is a commit I did yesterday](https://github.com/Play2Learn-Org/hackerspace/blob/94f71594ba5dcf480e1106d49df8d0ae303e3f9d/scenes/pause_menu.tscn#L166) with the version `Godot Engine v4.1.dev.custom_build.1e0f7a12f` which was the head of `master` branch yesterday or at most the evening before.

I didn't touch the files manually, only through the Godot UI. So the option has to be there in version `Godot Engine v4.1.dev.custom_build.1e0f7a12f`. I can rebuild it if I have to, but I'd say the `tscn` file linked through my project's commit above is showing that enough.

So, I tell you. Something happened that was unexpected. I don't know what exactly. But I'm pretty sure it's unexpected for you, too.

I can confirm that under today's build `Godot Engine v4.1.dev.custom_build.a7d0e18a3` I can find a `Layout` element, just as you describe. But it doesn't have a `Minimum Size` configuration inside, either. So, where would you expect that to be?

PS: Currently I just work less flexibly. I set the standard size parameters, and it works. So my project isn't struggling as much. But I think it might be worth finding out why the UI changed so heavily and probably in unexpected ways, so we can predict what support requests and bug reports will come in soon. Maybe there can be a small documentation change and note to the developers that can stop 500+ new urgent requests incoming.

**Comment by capnm** [comment]
> So, where would you expect that to be?

?
![grafik](https://user-images.githubusercontent.com/4047289/226115460-ba05a862-c097-49a4-9302-3aee258e815a.png)

**Comment by YuriSizov** [comment]
@erikbgithub The property is called "Custom minimum size", as depicted above. It used to be called "rect_min_size" (with "rect_" being stripped from the displayed name in Godot 3 because it was a prefix of the whole group of properties). The rename happened before Godot 4.0 stable was released, many months ago. And the change in the inspector happened in February 2022, also many months before Godot 4.0 stable was released.

The commit that you've linked was indeed made with a version of Godot 4 with these changes in place. But it couldn't have been done with the UI demonstrated on your first screenshot. If was to guess, you've mixed up some of your builds of the engine.

**Comment by erikbgithub** [comment]
Hm, when I look following your screenshot I also see it this way. Strange. Must’ve mixed things up.

maybe was just a deja vu.

**Comment by Calinou** [comment]
Closing per the above comments.
