### ISSUE TITLE
Unindicated code error.

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#75056]
### Godot version

v3.5.2.stable.official [170ba337a]

### System information

w10 64

### Issue description

I don't have any function with the name "_set_estado_impacto" however the compiler doesn't give me any error.

The function with the name "_set_estado_impacto" is in the script I'm inheriting from.
The compiler should report an error.
The correct way to call the function should be "._set_estado_impacto" using the "." to indicate that the function is in the script it is inheriting from.

https://user-images.githubusercontent.com/19652075/226097766-6f55112c-cd98-4a8c-b95a-083e4300532a.mp4

If the compiler does not report an error then:

What function is being called when using "_set_estado_impacto"?
If the inherited function is being called, then what's the point of using the "."?.

### Steps to reproduce

...

### Minimal reproduction project

...

**Comment by AThousandShips** [comment]
You can call a function in a super class without any problem can't you? It's only relevant to use the `.` syntax when you're overriding it I think

**Comment by Torguen** [comment]
> You can call a function in a super class without any problem can't you? It's only relevant to use the `.` syntax when you're overriding it I think

Yes, it makes sense, maybe this should be closed.

**Comment by AThousandShips** [comment]
Unless calling the function doesn't actually work then this isn't a bug no, see [here](https://docs.godotengine.org/en/3.5/tutorials/scripting/gdscript/gdscript_basics.html#inheritance) for an explanation of the usage

**Comment by Torguen** [comment]
I think this should be clarified, use the "." it is the same as not using it.
In both cases the function of the super class is called.

**Comment by AThousandShips** [comment]
I mean yes, in both cases the parent class is called, but nowhere is it stated that you can only call functions in the current class? You already call functions that are from inherited classes in your example video, `get_slide_collision`.

**Comment by AThousandShips** [comment]
> This is especially useful because functions in extending classes replace functions with the same name in their parent classes. If you still want to call them, you can prefix them with `.` (like the `super` keyword in other languages)

**Comment by adamscott** [comment]
Would close this issue as this is not an error or a bug. The dot notation can sometimes refer to the same function, if a class doesn't implement a parent's function, but sometimes don't.

**Comment by Calinou** [comment]
Closing per the above comments. Note that in 4.0, `super.some_function()` syntax is used instead, which is less confusing.
