### ISSUE TITLE
Sorting is broken in compatibility pipeline

### ISSUE THREAD

**Issue by Wiggan** [godotengine/godot#75063]
### Godot version

4.0.1rc1

### System information

Windows10, AMD Ryzen 9 5900X, NVIDIA GeForce RTX 3060 Ti, driver version 30.0.15.1179, compatibility.

### Issue description

Particle systems with transparent planes don't work in compatibility render pipeline. See comparison with mobile render pipeline, everything else identical:
![mobile](https://user-images.githubusercontent.com/6214882/226105754-9435cbcd-6d0c-4c16-a79e-13edfebf9321.png)
![compatibility](https://user-images.githubusercontent.com/6214882/226105755-95cc6c71-72e4-4c09-8aa6-3f4a89279201.png)

It could possibly be related to the add blend mode that is broken. Not sure.

### Steps to reproduce

Configure a CPUParticles3D system and with transparent particle and watch the sorting.

### Minimal reproduction project

[godot_repex.zip](https://github.com/godotengine/godot/files/11008506/godot_repex.zip)

**Comment by Calinou** [comment]
> It could possibly be related to the add blend mode that is broken. Not sure.

Try switching the blend mode to Mix and check if sorting works. Also set the shading mode to **Unshaded** to ensure shading isn't interfering with transparency sorting.

**Comment by clayjohn** [comment]
Weirdly enough, the issue only occurs when running the scene or when viewing through the camera preview. It doesn't occur when using the editor camera

_Using camera preview_
![Screenshot from 2023-04-11 18-52-55](https://user-images.githubusercontent.com/16521339/231327043-1550793d-cac6-40c4-aec7-5d16adb72707.png)

_Using editor camera_
![Screenshot from 2023-04-11 18-52-51](https://user-images.githubusercontent.com/16521339/231327046-e4d77d03-08d7-4ac5-bdb3-26eae85ba010.png)
