### ISSUE TITLE
Add a context menu when right-clicking a file in the shader editor

### ISSUE THREAD

**Issue by viktor-ferenczi** [godotengine/godot#75061]
### Godot version

4.0 stable, 4.1 master

### System information

Win 11, Vulcan

### Issue description

I cannot find any Close or Close All menu items and right clicking on the shader's name in the open shaders list does not do anything, no context menu appears. 

Pressing the "Script Editor / Close" shortcut (Ctrl-W) does not do anything on shader editors either. There is no separate shortcut for shader editors. 

Right now one must restart Godot to close all shader windows before deleting or renaming them.

Related: #72595

### Steps to reproduce

1. Open any `.gdshader` or `.gdshaderinc`
2. Try to close the shader editor

### Minimal reproduction project

Any project with shader code.

**Comment by bitsawer** [comment]
You can select "File -> Close File" to close the currently open shader file and press the "Shader Editor" button to toggle the whole editor visibility (but I think you know this one). I agree that the shader editor should receive some usability improvements, including keyboard shortcuts and maybe mouse left-click context menu for the shader listing etc. Also slightly usability related: https://github.com/godotengine/godot-proposals/issues/6355

![editor](https://user-images.githubusercontent.com/22456603/226104343-0c15d4cd-63f5-4ca4-bc4c-e924d4f5c3b1.png)

**Comment by KoBeWi** [comment]
You can also close using middle click.

**Comment by viktor-ferenczi** [comment]
Thank you. I was blind. Most likely because the File menu is separate from the rest of menus over the editor, which is logical, but unusual.
