### ISSUE TITLE
Text/LineEdit's relationship with custom_minimum_size is poorly documented

### ISSUE THREAD

**Issue by 20milliliter** [godotengine/godot#75075]
### Godot version

4.0.stable

### System information

Windows 10

### Issue description

Text/LineEdits do not respect their custom_minimum_size settings when being set to small values.

### Steps to reproduce

1. Place a TextEdit or LineEdit
2. Verify its custom minimum size settings to be (0, 0)
3. Attempt to set its size to 0
4. The action is denied.

### Minimal reproduction project

N/A

**Comment by Rindbee** [comment]
This case is still respect `custom_minimum_size`, as the actual `size` is not smaller than `custom_minimum_size`.

The reason why `custom_minimum_size` cannot be reached is because of theme overrides.

**Comment by 20milliliter** [comment]
There are no theme overrides enabled.
If you mean there's one that needs to be enabled, which? `minimum_character_width` doesn't work and no others seem like they would make a difference.

**Comment by KoBeWi** [comment]
The description for `custom_minimum_size` says

> If it's set to (0, 0), the node sizes automatically to fit its content, be it a texture or child nodes.

Every Control has also `get_minimum_size()` function, which determines content-based minimum size. Label's minimum size is determined by its text and affected by autowrapping and clipping. If the text is empty, the minimum size depends on the used font.

I think the docs could clarify that a bit more, especially in `custom_minimum_size` description.

**Comment by 20milliliter** [comment]
Well then what's the intended procedure if you do need a LineEdit with zero size, such as one which is intended to be animated and collapsible? A parent with `clip_contents`?

**Comment by KoBeWi** [comment]
> A parent with clip_contents?

Yes.
Although you don't really need to shrink it to (0, 0). Just animate to minimum size and make invisible.

**Comment by 20milliliter** [comment]
> Just animate to minimum size and make invisible.

I also tried that but it looked bad imo.

> Yes.

Well, alright. That feels really hacky but whatever.

**Comment by Rindbee** [comment]
`LineEdit` is affected by `theme_override_constants/minimum_character_width` and `theme_override_styles/normal`. `TextEdit` is mainly affected by `theme_override_styles/normal`.

Use `0` to override the theme constant provided by the **default** theme, and use a new StyleBox to override the StyleBox constant provided by the **default** theme. Generally, the width of the control can reach the minimum width (`0`).
