### ISSUE TITLE
GridContainer children won't report the actual Rect2 "position" and "end" when a Margin is set 

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#75086]
### Godot version

3.5.2, 4.0 stable

### System information

Win10, Nvidea 765M

### Issue description

As the title says, the Rect2 of the GridContainer children do not take the Margin offsets (Godot 3.5.2) or Position (Godot 4.0) into account.

I am currently trying to code a box select (by using [Rect2.intersects()](https://docs.godotengine.org/en/3.5/classes/class_rect2.html#class-rect2-method-intersects)) over a inventory items children of a GridContainer, and this issue makes this seemingly very simple task, suddenly really complicated. Just troubleshouting this and finding the source of the issue why I am not getting the right result wasted my whole day.

The Rect2 description even says: 

> It is typically used for fast overlap tests.

Are these Rect2 position and end values supposed to be local, not global values? If so why? Local values make overlap test a lot more complicated. Global values therefore would make much more sense. And why would the documentation say nothing about them being local rather than global values?

Maybe related: https://github.com/godotengine/godot/issues/39447

### Steps to reproduce

- Add a GridContainer (Layout: Full Rect, set Margin/Position to something like `left` 30, `top` 40)
- Add ColorRect as child of the GridContainer (set `rect_min_size` to 100, 100)
- Add a script with this code:

```
func _input(event):
	if event.is_action_pressed("ui_accept"):
		for i in $GridContainer.get_children():
			print(i.name,"  ", i.get_rect().position, i.get_rect().end)
```

- Observe the Rect2 printing a wrong position and end Vector when hitting Space.

### Minimal reproduction project

[grid_elements_rect_bug.zip](https://github.com/godotengine/godot/files/11009762/grid_elements_rect_bug.zip)

**Comment by KoBeWi** [comment]
Well

> Returns the position and size of the control in the coordinate system of the containing node.

For global coordinates use `get_global_rect()` instead.
