### ISSUE TITLE
The engine creates a random folder with a capital first letter when running the game in the editor

### ISSUE THREAD

**Issue by xxSeys1** [godotengine/godot#75082]
### Godot version

rc 4.0.1 

### System information

Windows 11, Vulkan, Ryzen 9 5900X, rx 6700xt

### Issue description

When I run a specific project in the editor, the engine picks a random folder in the project and creates a new one with the same name but with a capital first letter. If I delete the folder created from the engine, the original folder (the one with the small first letter, the original one) is also deleted.

Note that there is no actual folder created on my hard disk, it's only the engine who shows the aforementioned folder. 

Also the game windows closes itself (crashes?) instantly after running the project.

The whole issue is probably very specific but I though I'd report it anyways, cause in the end it borked my project.

### Steps to reproduce

I don't know how to reproduce this error

### Minimal reproduction project

see "Steps to reproduce"

**Comment by Calinou** [comment]
Windows has a case-insensitive filesystem by default, so this shouldn't be physically possible.

**Comment by xxSeys1** [comment]
> Windows has a case-insensitive filesystem by default, so this shouldn't be physically possible. Did you [enable case sensitivity on the project folder](https://docs.godotengine.org/en/latest/tutorials/best_practices/project_organization.html#case-sensitivity)?

I have checked if there actually is a folder created on my disk (that explorer shows), and there is none. Seems like this is an issue with how Godot displays files/folders.

**Comment by OboShape** [comment]
funnily enough im seeing the same just now .
on version - 
![image](https://github.com/godotengine/godot/assets/15170625/bff62a54-2927-457d-8621-3dd23d53429b)

seems to be creating a folder in editor, but not in OS filesystem. cant delete either thats there in editor, as either will remove the folder in OS.
![image](https://github.com/godotengine/godot/assets/15170625/1bc82385-8de6-4918-bc42-54d60505ec07)

if i go and try and open in 4.1.3 directly, folder still persists.

what i had to do to get around it, was to close editor.  delete the .godot folder.  then open in 4.1.3 and the error clears.

**Comment by OboShape** [comment]
I tseems like the cause (from one of our students cases) is possibly renaming the scripts folder mid way in a project and some scenes still referencing the old folder (prior to the rename) causes the folder in the editor to be created.

Another option to workaround was to detach all scripts, close all the scenes and open and Save As.  All scripts to the current folder, then reattach to scenes, save and test.

Just adding an additional observation from another suggestion from a different students workaround.

**Comment by akien-mga** [comment]
Is this (and other issues you closed) fixed? If not, we'd prefer issues to stay open until they are solved.
