### ISSUE TITLE
Ambient light not affecting gridmap in compatibility renderer

### ISSUE THREAD

**Issue by Wiggan** [godotengine/godot#75085]
### Godot version

4.0.1rc1

### System information

Windows10, AMD Ryzen 9 5900X, NVIDIA GeForce RTX 3060 Ti, driver version 30.0.15.1179, compatibility.

### Issue description

Ambient lighting set in the environment does not affect gridmaps when using the compatibility render pipeline.

### Steps to reproduce

Just add a gridmap and turn up ambient light. See how everything else gets bright but not the gridmap.

### Minimal reproduction project

[godot_repex.zip](https://github.com/godotengine/godot/files/11009650/godot_repex.zip)

**Comment by clayjohn** [comment]
This looks like it may be a duplicate of https://github.com/godotengine/godot/issues/74111
