### ISSUE TITLE
Sprite3D Modulate won't respect raw color values over 1

### ISSUE THREAD

**Issue by GregX999** [godotengine/godot#75083]
### Godot version

4.0

### System information

Windows 11

### Issue description

When adjusting the RAW color values in the Modulate property of a Sprite3D, values over 1.0 are ignored.

### Steps to reproduce

Add a Sprite3D to a 3d scene and try to adjust its Modulate property to have RAW values over 1.0. To drive home the effect, add a World Environment with a Glow effect, and another 3d object (such as a sphere), and adjust its Albedo to have RAW color values over 1.0.

![Screenshot 2023-03-18 151229](https://user-images.githubusercontent.com/677791/226140536-54fc9616-fb0f-499f-8240-0a4d4518aeeb.png)
![Screenshot 2023-03-18 151317](https://user-images.githubusercontent.com/677791/226140537-fe8def48-7a46-45f8-96d0-138e0db2a248.png)

### Minimal reproduction project

[CircleTest.zip](https://github.com/godotengine/godot/files/11009634/CircleTest.zip)

**Comment by Calinou** [comment]
This is due to an intentional change made in Godot 4.0 for performance reasons. Vertex color is now saved and rendered as RGBA8, instead of RGBAH. This means it has lower precision and can't be overbright anymore.
