### ISSUE TITLE
Project/Editor settings dialog saved position in single window mode does not work well with resizing the editor

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot#75084]
### Godot version

4.0

### System information

Linux

### Issue description

I'm using a tiling window manager (`dwm`) and running the editor in single window mode.
When `godot` is maximized, the project and editor settings dialogs are properly centered in Godot's window.
When `godot` is tiled to a half or quarter of the screen, these dialogs do not use space effectively

![1679174374](https://user-images.githubusercontent.com/2496231/226140732-6d8ba690-21fb-403f-93d6-f7690213fb7c.png)
![1679174383](https://user-images.githubusercontent.com/2496231/226140733-f51b5cc6-1ce2-40d2-8d67-5f4db5fa6f7e.png)
![1679174388](https://user-images.githubusercontent.com/2496231/226140734-05c70f92-e47c-4dfe-ae39-3cd691f8e4ac.png)

Other dialogs, like `Export`, seem better:

![1679174506](https://user-images.githubusercontent.com/2496231/226140760-7fe65e49-a0cd-412b-8d73-c74034deea37.png)

### Steps to reproduce

1. Open the project settings dialog
2. Tile `godot` to half or a quarter of the display.

### Minimal reproduction project

Can repro with an empty project.

**Comment by rcorre** [comment]
Ah, it looks like this has to do with the "remembered" position last time you opened it. So if you have `godot` open maximized and move the dialog at all, it remembers an absolute position in Godot's window. If you open project settings again with the Godot window smaller, it spawns in a position that doesn't make sense (unless it is so far off it is totally outside the window, in which case you get `ERROR: Window 0 spawned at invalid position: (2170, 609).`, and it returns to the center.

**Comment by Rindbee** [comment]
It feels like `interface/editor/single_window_mode` is enabled.

**Comment by AThousandShips** [comment]
Looks indeed like the saved position feature breaks with single window mode, perhaps it should not be used then and always pop up centered

**Comment by rcorre** [comment]
> It feels like interface/editor/single_window_mode is enabled.

￼Sorry, I forgot to mention that. Yes, I'm using `single_window_mode`

**Comment by AwesomeAxolotl** [comment]
Is there the possibility to always open these dialogs in the center of the screen instead of remembering their position? I have problems with a sometimes-multimonitor setup, the positions always break (shows on wrong screen, shows over the edge of the screen) unless I use single-monitor-mode.
