### ISSUE TITLE
ParticlesMaterial in Particles2D can't have different parameters

### ISSUE THREAD

**Issue by Omiod** [godotengine/godot#75100]
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Windows 10, Geforce GTX 1660, NForward+

### Issue description

I've made a simple class that instantiates a scene with a GPUParticle2D inside, to make a simple firework.
The idea is to have multiple fireworks, updating the process_material.color before adding to the scene to have each one with a different color.

The issue is that the material color seems shared between the three instances, having the last one to prevail.

I also apply a different scale to the GPUParticle2D, and in this case it works correctly. The material seem to be the problem.

### Steps to reproduce

This is the function to add a new firework:

```
func add(container:Node, type:String, pos:Vector2, scale:float, color:Color):
	var new_one = load("res://" + type + ".tscn").instantiate()
	new_one.get_node("fx").scale = Vector2(scale, scale)
	new_one.get_node("fx").process_material.color = color
	new_one.position = pos
	container.add_child(new_one)
```

Then adding multiple fireworks with different color:
```
	Sparks.add(self, "fx3", Vector2(200,400), 1, Color.RED)
	Sparks.add(self, "fx3", Vector2(500,400), 2, Color.GREEN)
	Sparks.add(self, "fx3", Vector2(800,400), 3, Color.BLUE)`
```

Will show all three fireworks with the same color of the latest added (blue in this case)

### Minimal reproduction project

Here is the Godot 4.0 test project:
[ParticlesTest.zip](https://github.com/godotengine/godot/files/11011109/ParticlesTest.zip)

Thank you.

**Comment by KoBeWi** [comment]
Resources are shared by default. Enable `local_to_scene` in your particles material to make it unique for each scene instance.
