### ISSUE TITLE
Can the node retain the file naming?

### ISSUE THREAD

**Issue by zuiaiyangyang3** [godotengine/godot#75101]
### Godot version

4.0,3.5

### System information

win10

### Issue description

![1111](https://user-images.githubusercontent.com/61361272/226178674-6ac789fc-3e23-4868-affc-8bf6920cb5f7.gif)
Drag the picture to the node
Can a_2_icon be retained?
Not A2icon.

### Steps to reproduce
![1111](https://user-images.githubusercontent.com/61361272/226178795-9669f96f-c7cf-4496-ae83-e6c7820d4964.gif)

11

### Minimal reproduction project

11

**Comment by AThousandShips** [comment]
This is based on the setting `editor/naming/node_name_casing`, it is by default "Pascal Case" which converts underscores like this, can you try changing this setting to "snake_case", but also this is for bug reporting and not help, please go to the [community channels](https://godotengine.org/community) for that.
