### ISSUE TITLE
Texture loaded from http not displaying on StandardMaterial3D

### ISSUE THREAD

**Issue by Phytoplankton** [godotengine/godot#75104]
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Windows 10

### Issue description

Using a HttpRequest node to load a png image from a web server.
Creating a ImageTexture from the loaded data.
Applying the texture to a StandardMaterial3D.

The texture does not show up on the mesh in godot 4.
It is working in godot 3 (using SpatialMaterial)

```
extends Node3D

func _ready():
	$http_req.request("https://godotengine.org/assets/favicon.png")

func _on_http_req_request_completed(result, response_code, headers, body):
	var image = Image.new()
	var error = image.load_png_from_buffer(body)
	if error != OK:
		prints("Couldn't load the image.")
		return
	var texture = ImageTexture.new()
	texture.create_from_image(image)
	
	var mat: StandardMaterial3D = $mesh.material_override
	mat.albedo_color = Color(1,1,1,1)
	mat.albedo_texture = texture
```

### Steps to reproduce

Attached a reproduction project. Just run it. Expect to display a texture on the 3d mesh (not a solid color)

### Minimal reproduction project

[project.zip](https://github.com/godotengine/godot/files/11011363/project.zip)

**Comment by Calinou** [comment]
You need to use `var texture = ImageTexture.create_from_image(image)` now, as `create_from_image()` is a static function in 4.0.
