### ISSUE TITLE
Moving a C# script outside the editor, running the scene, raise no error or message

### ISSUE THREAD

**Issue by EduardoLemos567** [godotengine/godot#75112]
### Godot version

4.0.1 RC1

### System information

Windows 10, GTX 1660 TI

### Issue description

Moving a C# cs file outside the Godot editor doesn't generate any debug message when running the game.

The game simply open and close, without any message on output or debbuger.

Tested with GDScript and it generate error message: 
"load_source_code: Attempt to open script 'res://new_script.gd' resulted in error 'File not found'."

Expected the same behaviour for C# scripts.

PS: You are only notified if you reopen the scene, receiving the fix dependencies dialog.
PS2: I'm not complaining the fact if you change files outside the editor, it loses track of resources.
Its expected. I'm complaining the fact you are left with no messages to quickly identify your mistake.

### Steps to reproduce

- Create new project
- Add new CS script to any node in the tree
- Open your OS's file explorer (Show in File Manager) and move the script to another path
- Try to run the scene F6

### Minimal reproduction project

[Test 4.0.zip](https://github.com/godotengine/godot/files/11011899/Test.4.0.zip)

**Comment by RedworkDE** [comment]
- Possibly related to the inverse issue of script contents disappearing when they shouldn't https://github.com/godotengine/godot/issues/50163

**Comment by raulsntos** [comment]
I'm unable to reproduce in v4.1.stable.mono.official [970459615].

I get these errors in the Output tab:

```
Cannot open file 'res://scene.cs'.
Failed to read file: 'res://scene.cs'.
Cannot load C# script file 'res://scene.cs'.
Failed loading resource: res://scene.cs. Make sure resources have been imported by opening the project in the editor at least once.
editor/plugins/script_editor_plugin.cpp:2580 - Condition "!rel_scr.is_valid()" is true. Continuing.
```

I get these errors in the Debugger tab:

```
E 0:00:00:0445   read_all_file_utf8: Cannot open file 'res://scene.cs'.
E 0:00:00:0445   load_source_code: Failed to read file: 'res://scene.cs'.
E 0:00:00:0445   load: Cannot load C# script file 'res://scene.cs'.
E 0:00:00:0445   _load: Failed loading resource: res://scene.cs. Make sure resources have been imported by opening the project in the editor at least once.
E 0:00:00:0445   _parse_ext_resource: res://scene.tscn:6 - Parse Error: [ext_resource] referenced non-existent resource at: res://scene.cs
```

It also doesn't close the game.

Are you still able to reproduce this issue in Godot 4.1 or any later release?

**Comment by EduardoLemos567** [comment]
Not reproducible anymore, now i get the same error messages you got with Godot 4.1.1.
I consider it fixed.
Thank you
