### ISSUE TITLE
Particle z-order changes during lifetime for Particles2D

### ISSUE THREAD

**Issue by DjPale** [godotengine/godot#7511]
**Windows 10 - Godot version: v2.1.1.stable.official**

**Issue description**:
When emitting particles, the z-order changes during lifetime creating an unintended effect where 2D particles sudden jump in front of eachother

**Steps to reproduce:**
* Create an empty scene with a root node and Particles2D node

* Custom Texture (NB! make large to see that it actually changes the draw order)
* Config (other than default):
  * Amount=3
  * Lifetime=3
  * Explosiveness=0

* Params (other than default):
  * Direction=180
  * Spread=45
  * Linear Velocity=100
  * Gravity Direction=180
  * Gravity Strength=10
  * Damping=180

**Link to GIF animation**:
[Dropbox shared animation](https://dl.dropboxusercontent.com/u/541553/Misc/godot-particle-bug.gif)

**Comment by kubecz3k** [comment]
@DjPale This issue is probably fixed, can you recheck in 3.0?

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by vnen** [comment]
> Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Since there's no new information, closing this issue as it is stale. If anyone can confirm the issue in a recent Godot version, feel free to comment so we can reopen, or open a new issue with new information.

**Comment by Cr0wned** [comment]
the issue is still here in Godot 3.4.3

**Comment by Calinou** [comment]
> the issue is still here in Godot 3.4.3

This cannot be fully resolved due to the nature of [transparency sorting](https://docs.godotengine.org/en/latest/tutorials/3d/3d_rendering_limitations.html#transparency-sorting). However, you can adjust the draw order in the ParticlesMaterial (for GPU-based Particles) or in the CPUParticles properties.
