### ISSUE TITLE
CanvasItem's Pivot Point Won't Change

### ISSUE THREAD

**Issue by toliaferrode** [godotengine/godot#7512]
**Operating system or device - Godot version:**
Ubuntu MATE, Godot 2.1.1

**Issue description** (what happened, and what was expected):
In trying to change a CanvasItem's pivot point, clicking it in the editor and then pressing and holding V, it doesn't work. Instead it moves the CanvasItem to the location of the mouse pointer. The inspector records the offset change, though. But as I said, in the editor the CanvasItem just moves to the mouse cursor, instead of the pivot point actually moving.

**Steps to reproduce:**
Try to change a CanvasItem's pivot point.

**Link to minimal example project** (optional but very welcome):

**Comment by lemilonkh** [comment]
I'm having the same problem in a self compiled version of the 2.2 branch of this repo. Does anybody know a workaround?

**Comment by reduz** [comment]
you can't change the pivot point of a CanvasItem, this is only for certain
nodes such as Sprite, AnimatedSprite, tc.

**Comment by toliaferrode** [comment]
Oh, thanks Juan. Good to know. I'll close it.
