### ISSUE TITLE
"Paste Value" does not refresh the displayed values of array/dict elements in inspector

### ISSUE THREAD

**Issue by ajreckof** [godotengine/godot#75124]
### Godot version

4.1.dev (4d5f10fc3a)

### System information

MacOS 13.1 M1 Pro

### Issue description

This is similar to #61188, but only happening on elements of array and dictionaries.

Elements of array/Dictionaries are not properly refreshed when using Paste value on them. The values do change internally but the inspector doesn't show the updated value until it is refreshed manually.
This might be related to the fact that the option to copy property path returns an empty string, but i'm not sure as i don't know how updating the property was implemented.

### Steps to reproduce

1. export an array
2. Add two element to the array
3. Change the value of one of the array's element.
4. copy the value of the one you modified.
5. Paste the value on the second element. (here nothing visually changed)
6. click in the tree anywhere except on the node with the exported array then click again on the node (here you will see it has updated and the value was pasted and just not shown)

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
I can confirm this on 4.0.3.stable and 4.1.dev 33957aee6 (Linux).

**Comment by akien-mga** [comment]
Reopening as #76711 was reverted.
