### ISSUE TITLE
Sprite's modulate alpha when instantiating custom scene as child is not repsected when having Input processing logic

### ISSUE THREAD

**Issue by mgskai** [godotengine/godot#75132]
### Godot version

3.5.2-stable, 4.0-stable

### System information

macOS 13.2.1

### Issue description

When adding an instantiated scene with alpha in self_modulate configured for the sprite to another scene as a child during a input processing logic, the alpha in self_modualte is not respeced

### Steps to reproduce

See the attached reproduction project (3.5.2 stable). Run the project and click in the game screen, the added sprite does not have the configured self_modulate alpha applied. The issue also exists in 4.0-stable.

### Minimal reproduction project

[TestSprite1.zip](https://github.com/godotengine/godot/files/11014135/TestSprite1.zip)

**Comment by KoBeWi** [comment]
The sprite has correct alpha.
Or rather sprites.
You overlap 4 of them.
![image](https://user-images.githubusercontent.com/2223172/226317567-719998c7-b16a-4209-a018-7760c23ffc4d.png)
