### ISSUE TITLE
Keyboard language switch breaks script editor

### ISSUE THREAD

**Issue by ievr** [godotengine/godot#75138]
### Godot version

4.0.1-RC2

### System information

Windows 10, with multiple keyboard layouts

### Issue description

Arrow keys, backspace, enter stop working if I switch language.

I have English, Estonian, Russian layouts. If I switch those in editor using WIN+Space shortcut only the letter keys work. CTRL, ALT, arrows and enter stop working.

### Steps to reproduce

Steps:
1. Open the editor script window
2. Type aa and erase them with backspace
3. Hit Win+Space
4. Type aa and erase them with backspace
Backspace fails to work until I restart the editor.

Notes: 
- There is a similar issue [mentioned for Ubuntu](https://github.com/godotengine/godot/issues/49771)
- I did not experience this in Godot 4.0.0

### Minimal reproduction project

N/A

**Comment by ievr** [comment]
Update and workaround: I can get it to work again when I press the WIN key again. So basically: language changer seems to break the non-alphanumeric characters.

**Comment by AThousandShips** [comment]
That's probably to be expected, some commands that trigger special behavior in the OS grab focus and mean the key never gets released, often happens when you ALT-Tab out of an application

**Comment by ievr** [comment]
This is not absolutely expected. No other program, including Godot 4.0.0 does this.

**Comment by AThousandShips** [comment]
It seems indeed to be different from the ALT situation, will try and dig some

**Comment by AThousandShips** [comment]
Could be from #74474, cc @bruvzg

**Comment by dszhblx** [comment]
This bug has a great impact on Chinese users, and Korean and Japanese users should be the same.
