### ISSUE TITLE
Godot stops working after saving a scene a couple of times

### ISSUE THREAD

**Issue by furtidev** [godotengine/godot#75145]
### Godot version

4.0.stable

### System information

Fedora Workstation 37, Intel HD 610, Mesa 22.3.7, Vulkan, 4GB RAM

### Issue description

https://user-images.githubusercontent.com/44488750/226386091-58244d61-d8e6-4aba-bb2a-f579eab0f458.mp4

Saving a scene a couple of times freezes Godot, this also happened a few times randomly (for example, I was creating a new project and switched window, when I returned Godot was frozen), though saving is the only way I was able to reproduce it everytime. 

I tried running Godot via terminal to see if it prints any errors, nothing was there.

### Steps to reproduce

- Create a new Godot project.
- Create a new scene.
- Try saving it a few times.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Duplicate of #74548?

**Comment by furtidev** [comment]
well it happens to me outside of just saving as well, so wasn't sure.

**Comment by Calinou** [comment]
- Duplicate of https://github.com/godotengine/godot/issues/74548 and/or https://github.com/godotengine/godot/issues/74850 (same cause).
