### ISSUE TITLE
Editor crashes when using the save scene or save all scenes option on MacOS (M1)

### ISSUE THREAD

**Issue by jonn-reenthused** [godotengine/godot#75156]
### Godot version

4.0.1

### System information

MacOS M1 / Vulkan

### Issue description

When pressing the Save Scene or Save All Scenes options in the editor a small black rectangle appears in the middle and a few seconds later the editor quits.  No log appears to be produced.

Note: It does NOT crash when it autosaves the scenes after running.

It doesn't matter what the contents of the scene is, I've tried empty scenes and scenes with content with no difference. I've also tried multiple projects including newly created ones.

### Steps to reproduce

- Open or create a project
- Add a scene
- Make some change to the scene that requires saving
- Use the Scene -> Save Scene or Scene -> Save All Scenes option
- Editor crashes

### Minimal reproduction project

N/A

**Comment by finecco** [comment]
I had the exact same issue today on an M1 laptop. 

For me i think it was fixed by just running the scene thus autosave.

When it was happening, godot crashed everytime ctrl+s is pressed. Now I can ctrl+s and its fine.

**Comment by YuriSizov** [comment]
Was this happening in 4.0? In one of the RCs and betas for 4.0?

**Comment by jonn-reenthused** [comment]
Autosave doesn't fix the issue for me, although it does save so I have a workaround.  I didn't know if a video of the issue would be useful (it's just showing a window disappearing) but I made one anyway:

https://diode.zone/w/9LGzxYd58qsXczXZGDHcJh

**Comment by finecco** [comment]
> Was this happening in 4.0? In one of the RCs and betas for 4.0?

Hi, I didn't encounter this issue in 4.0 betas or RCs. And only once in 4.0.1

**Comment by YuriSizov** [comment]
@jonn-reenthused Can you run the editor from the terminal and see what the output is?

**Comment by YuriSizov** [comment]
@jonn-reenthused You need to launch directly into the project, using the `-e` and `--path` arguments. See [this](https://docs.godotengine.org/en/stable/tutorials/editor/command_line_tutorial.html).

**Comment by jonn-reenthused** [comment]
I've added a link to the output, but as a TLDR; it's mostly lots of :

`ERROR: Task 'save' already exists.
   at: add_task (editor/progress_dialog.cpp:177)`

ending with:

`zsh: segmentation fault  /Applications/godot.app/Contents/MacOS/Godot -e --path  `

[https://johnnyblanchard.com/files/godot-save-crash.txt](url)

**Comment by jonn-reenthused** [comment]
I've only experienced it in 4.0.1 - not in 4.0

**Comment by ckrokosh** [comment]
Me too. Running Monterey on an intel iMac. Didn't happen in 4.0 only since upgrading o 4.0.1

**Comment by karl20038** [comment]
I've been having the issue randomly when using 4.0.1

**Comment by YNotCodeStudios** [comment]
Godot 4.01 stable crashes for me too when saving a scene, on iMac Intel i5 running Ventura 13.3

**Comment by kleonc** [comment]
> Godot 4.01 stable crashes for me too when saving a scene, on iMac Intel i5 running Ventura 13.3

@YNotCodeStudios This issue was reported for 4.0.1 so this is expected, in 4.0.1 the bug is present. It is fixed for the next release (by #75254). The fix is included in [4.0.2-rc1 which is already out](https://godotengine.org/article/release-candidate-godot-4-0-2-rc-1/).
