### ISSUE TITLE
Duplicatate or copy/pasted nodes resize together though have different parents

### ISSUE THREAD

**Issue by HPCR-SD** [godotengine/godot#75165]
### Godot version

4.0.1

### System information

Windows 10

### Issue description

My apologies if this has been reported it's late and I have 2 bugs to report and I'm exhausted, so please forgive me if I've missed this somewhere in the list of reported bugs already.

Issue: In my case and I believe I've run into this with some control nodes in another project, but when I duplicate my collision shapes in the project I will share that I ran into this again, another shape collision shape with no connection other then being the child of a sibling resizes as well. This happens when I copy and paste or duplicate. 

For example wall right and wall top are linked by duplicating the parent static body i have and wall left and wall bottom are linked by copy and paste. if you adjust the size of the collision shape on any they will affect the one the are somehow linked to.

### Steps to reproduce

Copy and paste or duplicate a resizable node like collisonshape2d

### Minimal reproduction project

[project.zip](https://github.com/godotengine/godot/files/11024256/project.zip)

**Comment by Calinou** [comment]
This is expected, as CollisionShape resource is shared between nodes. You need to use **Make Unique** in the CollisionShape's resource dropdown so that you can edit it independently from other nodes using the same CollisionShape.

**Comment by HPCR-SD** [comment]
There is no make unique in Resource....

**Comment by HPCR-SD** [comment]
Sorry I didn't mean to send that I realized where it was

**Comment by WellHiIGuess** [comment]
Where is the Make Unique in Resource?

**Comment by WellHiIGuess** [comment]
Nvm I found it where you select the shape
