### ISSUE TITLE
Unsigned int suffix not highlighted in shader editor

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#75161]
### Godot version

4.0.1

### System information

Windows 10 x64

### Issue description

![image](https://user-images.githubusercontent.com/2223172/226490990-14aa7610-55df-4f9f-9973-f743884e1db5.png)

### Steps to reproduce

1. Create shader
2. Add `uint`, e.g. `4u`

### Minimal reproduction project

N/A

**Comment by jsjtxietian** [comment]
`GDShaderSyntaxHighlighter` uses `CodeHighlighter` which doesn't recognize this syntax.
