### ISSUE TITLE
Resource scripts in addons folder not appearing in resource creation menu

### ISSUE THREAD

**Issue by SlashScreen** [godotengine/godot#75163]
### Godot version

v4.0.stable.mono.official [92bee43ad]

### System information

Windows 10

### Issue description

When creating a custom resource (GDScript class inheriting `Resource`), scripts located underneath `addons` will not show up in the asset creation menu.

### Steps to reproduce

When opening the project, attempt to create a `NormalResource` and see that it works. This script is located at `res://normal_resource.gd`. 
Then, attempt to create an `AddonsResource`. See that, despite the code being nearly identical, it will not show up in the menu. This script is located under `addons/foo/addons_resource.gd`, to simulate being part of a package from the asset library.

### Minimal reproduction project

[resourcetest.zip](https://github.com/godotengine/godot/files/11024091/resourcetest.zip)

**Comment by SlashScreen** [comment]
I need to register my folder as a plugin for it to work. Whoops.

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot/issues/30048 and https://github.com/godotengine/godot/issues/27470.
