### ISSUE TITLE
Shader code gets different rounded values for color in editor and runtime (float rounding error)

### ISSUE THREAD

**Issue by FarbrorMartin** [godotengine/godot#75183]
### Godot version

4.0-stable

### System information

Windows 10, Forward+, Intel HD 620

### Issue description

The following simple color replacement shader replaces one color with another. In the editor this works for all colors, but in debug runtime it will not match color which are affected by float rounding.
![image](https://user-images.githubusercontent.com/36861435/226594746-f9678c83-53ea-4526-81af-2adcf2ac5e68.png)

Color(204, 204, 204) works both in editor and runtime. 204/255 = 0.8

Color(205, 205, 205) works in editor, but not in runtime.  205/255 = 0.80392156862....

The shader reads the rounded values from the color, which does not match in float math.
After loading the project the editor shader code also uses the rounded values, which makes the shader break in the editor as well.
Simply opening and closing the color picker of the shader refreshes the rounded values with the correct fractional float making the shade work again.

### Steps to reproduce

Load supplied MRP.
The lower sprite is grey because the color shader has not matched the color.
Open and close the color picker for the shader in the sprite material.
The color shader gets the real color values and the sprite turns red.
Run the project
The lower sprite is grey, because in runtime the color values are rounded.

### Minimal reproduction project

[ShaderMRP.zip](https://github.com/godotengine/godot/files/11027777/ShaderMRP.zip)

**Comment by Zireael07** [comment]
This is documented somewhere in the shaders section. Use epsilon, never compare floats with ==

**Comment by Chaosus** [comment]
Yeah, do not use comparison operator on floats, use `abs(b - a) < 0.00001` if you need it.

**Comment by FarbrorMartin** [comment]
Well, I'm not comparing floats, but Vectors (Vec4).
I didn't realize the internal code actually compared floats when comparing vectors.

Changing the code to use an approx comparison makes it work as expected:
![image](https://user-images.githubusercontent.com/36861435/226610509-9f9d38e0-26fe-4b04-ad94-16bb9e4179ee.png)




> Yeah, do not use comparison operator on floats, use `abs(b - a) < 0.00001` (or `abs(b - a) < vec4(0.00001)` if you use `vec4`) if you need it.

**Comment by Zireael07** [comment]
> I didn't realize the internal code actually compared floats when comparing vectors.

That's also documented in the shader documentation. Heck, even GLSL/HLSL use floats, and googling "glsl vector" will tell you as much!

**Comment by FarbrorMartin** [comment]
Fair enough, RTFM I guess. What threw me was the different behaviour in
editor vs runtime.

Working fine now though, thanks for the quick help!

**Comment by Daniel-The-Fox** [comment]
For anyone else that stumbles on this via Google search when trying to compare colors:
Here's the link to the part of the Godot documentation that was referred to further up in one of the comments.
https://docs.godotengine.org/en/stable/tutorials/shaders/shader_reference/shading_language.html#flow-control

It would be great to have a built-in function to compare colors some time... :)

**Comment by Calinou** [comment]
> For anyone else that stumbles upon this issue thread via Google search when trying to compare colors: Here's the link to the part of the Godot documentation that was referred to further up in one of the comments. [docs.godotengine.org/en/stable/tutorials/shaders/shader_reference/shading_language.html#flow-control](https://docs.godotengine.org/en/stable/tutorials/shaders/shader_reference/shading_language.html#flow-control)
> 
> It would be great to have a built-in function to compare colors some time... :)

There's an open proposal for this: https://github.com/godotengine/godot-proposals/issues/6870

**Comment by Daniel-The-Fox** [comment]
> > For anyone else that stumbles upon this issue thread via Google search when trying to compare colors: Here's the link to the part of the Godot documentation that was referred to further up in one of the comments. [docs.godotengine.org/en/stable/tutorials/shaders/shader_reference/shading_language.html#flow-control](https://docs.godotengine.org/en/stable/tutorials/shaders/shader_reference/shading_language.html#flow-control)
> > It would be great to have a built-in function to compare colors some time... :)
> 
> There's an open proposal for this: [godotengine/godot-proposals#6870](https://github.com/godotengine/godot-proposals/issues/6870)

Thanks for the hint. I found this change proposal in the meantime as well.
If it doesn't get added, maybe they could add your example code to the docs at least? :)
