### ISSUE TITLE
Norton flagging several DLL's as a threat

### ISSUE THREAD

**Issue by T-Massey** [godotengine/godot#75195]
### Godot version

v4.0.1 stable mono 64bit

### System information

Windows 11

### Issue description

Downloaded and unzipped, Norton right away flagged the GodotSharp/SharpEditor/Tools/Plugins dll's as a threat and removed them. They all listed as Threat name WS.Reputation.1. I searched for this and from what I can tell it's most likely because it's a new release and Norton's being over protective. So there may not be anything that can be done, but I've not had this on any of the other releases so I wanted to let you all know. 

### Steps to reproduce

Download, Unzip.

### Minimal reproduction project

N/A

**Comment by Zireael07** [comment]
Norton LOVES flagging anything that's new as a threat because it has low reputation (that's exactly what WS.Reputation.1 means)

Reporting it as false positive won't help since that's exactly how the reputation "threat" is supposed to work. :/

**Comment by Calinou** [comment]
Closing, as there is nothing we can do on our end.
