### ISSUE TITLE
Shader uniform parameter vec4 without source_color hint does not follow explicit default value, and source_color default differs between vec3 and vec4

### ISSUE THREAD

**Issue by hsandt** [godotengine/godot#75191]
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Linux Ubuntu 22.04 with Unity desktop

### Issue description

In a shader using uniform parameters of type vec3 and vec4, the way defaults work is inconsistent.

* vec3 param => OK, default is (0, 0, 0) and explicit default is honored
* vec3 param : source_color => OK, default is black and explicit default is honored
* vec4 param => not OK, default is (0, 0, 0, 0) but explicit default is ignored and keeps using (0, 0, 0, 0)
* vec4 param : source_color => OK, default is white and explicit default is honored

So there are two issues:
* vec4 param without source_color hint ignores explicit default
* vec3 and vec4 react differently when source_color is used but there is no explicit default, to pick a default

Here is a sum-up screenshot of the default values for each case:

EDIT: I realized some vec3 labels are incorrect: since there is no alpha, Clear should be Black and Alpha Gray should just be Gray. This also means that it's normal that the source_color preview looks different on vec4 for those two.

![image](https://user-images.githubusercontent.com/1067772/226680399-e1d43ee8-9e35-457a-a3da-6e91fcfba3c1.png)

### Steps to reproduce

1. Open the sample project attached, open the demo scene
2. Click on Sprite2D
3. In the inspector, unfold Material info and check the shader values (there should be no Revert button visible, so they are the default values). You should see the same inconsistent values as in the screenshot above
4. When an explicit default value is set, you can also modify the value and click on the Revert button to make sure that we refreshed to the last default values

### Minimal reproduction project

[v4.0 - Shader vec3 vec4 default inconsistencies.zip](https://github.com/godotengine/godot/files/11031311/v4.0.-.Shader.vec3.vec4.default.inconsistencies.zip)

**Comment by clayjohn** [comment]
Looks like vec4 is wrong whenever it differs from vec3. I would call this an issue with vec4 not assigning the correct default value in many cases
