### ISSUE TITLE
Audio track key `end_offset` does not work when it exists outside the animation length

### ISSUE THREAD

**Issue by KnightNine** [godotengine/godot#75197]
### Godot version

4.0

### System information

Windows 10

### Issue description

The `Audio Playback Track` in an `Animation` can only stop the sound at its `End Offset` on the first loop, then it fails to do so for every loop after the first:

The sound begins overlapping with itself as seen in the top right:
![sound looping](https://user-images.githubusercontent.com/34152090/226741982-3883b08b-cd4f-4413-9e5b-0be747e69951.gif)

### Steps to reproduce

- create an `AudioStreamPlayer3D` and an `AnimationPlayer` in your scene.
- create an animation and select the looping button.
- add an `Audio Playback Track` to it that is connected to the `AudioStreamPlayer3D`
- drag a sound into the track, then shorten the sound by dragging its right edge to the left (thus increasing its `End Offset` )
- shorten the animation length to the length of the shortened audio file.
- play the animation.

### Minimal reproduction project

N/A

**Comment by KnightNine** [comment]
Is there a workaround for this without clipping the audio file to the length of the animation? I tried setting the `playing` property of the `AudioStreamPlayer3D` to false and then true to see if I could reset the player but that just stops the audio entirely.

**Comment by TokageItLab** [comment]
The audio track is basically the key that fires playback and is not trimmed by the animation length. This is the intended behavior.

The bug I can tell here is that the EndOffset outside of the animation length is ignored. This is odd, I'll send a PR to fix it later.

**Comment by YuriSizov** [comment]
@TokageItLab A reminder that you wanted to fix this :)

**Comment by KnightNine** [comment]
@TokageItLab 
The issue still seems to persist on my end.
Did you test that that this was fixed?

**Comment by TokageItLab** [comment]
See above comment

**Comment by KnightNine** [comment]
@TokageItLab 

If the sound not stopping at the end of the animation is the intended behavior How do I prevent my looping animation audio from overlapping with itself then?
Am I forced to create an audio file that is the exact length of the looping animation?


And the audio would be cut by the animation length for looping animations in 3.X so why the design change?

**Comment by TokageItLab** [comment]
Now the end offset is available if the fix is done correctly, so it might be sufficient you just setting the end offset for all looping animation.

For example, there is an animation contain jumping and the last frame landing with sound fx, if you loop and force trim that sound, the landing sound is not played correctly, so trimming shouldn’t be there at least as default.

However, AudioPlaybackTrack generally allows you only 1 sound per 1 track, so I guess your issue is "previous sound is not stopped when next key is played after looping" not "AudioPlaybackTrack is not trimmed by animation length".

**Comment by KnightNine** [comment]
@TokageItLab 

Basically it's practically impossible to set the end offset to the very end of the animation length

The `end_offset` value is based on the percentage of the audio length so I can't just enter the length of the animation into it.
I also can't snap the end offset to anything by dragging it in the timeline either.

I guess I'll post "previous sound is not stopped when next key is played after looping" because the AudioStreamPlayer3D shouldn't be able to play multiple sounds at the same time.

**Comment by TokageItLab** [comment]
> Basically it's practically impossible to set the end offset to the very end of the animation length

For about that, you can use inspector.

**Comment by KnightNine** [comment]
@TokageItLab 
> For about that, you can use inspector.

I actually have to subtract the animation length from the sound length to get the value 
I was wrong about:

> The `end_offset` value is based on the percentage of the audio length

But even then it's finnicky and needs adjustment or else it allows audio gaps on the loop.

**Comment by TokageItLab** [comment]
The only improvement that could be made for this would be the addition of a snap. If the snap is not effective currently, so you can send another issue.
