### ISSUE TITLE
Pop_front() and Pop_back do not return anything

### ISSUE THREAD

**Issue by Norrolith** [godotengine/godot#7520]
This feels weird enough I thought I would bring it up.
pop_front() and pop_back() just modify the array they are called from.
They do not return anything, which seems counterproductive.
they are already oneliners at present, array.remove(0) and array.remove(array.size()) respectively.
When I think their intended use was

pop_front ():
var temp = array[0]
array.remove(0)
return(temp)

and

pop_back():
var temp = array[array.size]
array.resize(array.size-1)
return(temp)

Correct me if this is the correct behaviour, but this feels weird.

**Comment by akien-mga** [comment]
Please complete what was asked in the issue template:

> Operating system or device - Godot version:

**Comment by Norrolith** [comment]
apologies.
Linux x64
Version 2.0.2.stable.official
The docs shows the present behaviour.

**Comment by akien-mga** [comment]
Thanks. This has been fixed already in the master branch for the upcoming version 3.0 :)

(Incidentally, duplicate of #3763)
