### ISSUE TITLE
`PhysicsDirectSpaceState` `collide_shape` returns the wrong type

### ISSUE THREAD

**Issue by voidedWarranties** [godotengine/godot#75207]
### Godot version

4.0.1-stable

### System information

Fedora 36

### Issue description

See the following snippets:

https://github.com/godotengine/godot/blob/ce90d77a1857e9cee4b7571258d6e917bf4ba268/servers/physics_server_3d.cpp#L432-L448

https://github.com/godotengine/godot/blob/ce90d77a1857e9cee4b7571258d6e917bf4ba268/servers/physics_server_2d.cpp#L412-L428

Both of these methods are documented/declared to return a `TypedArray` of `PackedVector2Array`/`PackedVector3Array`, but both of them actually return a flat `Array` of `Vector2`/`Vector3`.

See also #73182.

### Steps to reproduce

1. Create a physics body.
2. Call `collide_shape`.
3. Observe that the method does not return values as documented.

### Minimal reproduction project

[MRP.zip](https://github.com/godotengine/godot/files/11036942/MRP.zip)

**Comment by YuriSizov** [comment]
Yeah, it should be either a typed array of vectors, or a packed vector array. This amalgamation is wrong. Interesting that the original report identified the same, but the fix was not correct.

**Comment by smix8** [comment]
It is the only place where this wrong type is used for 3D but 2D has far more places in the engine e.g. Geometry2D where the same wrong was added.

**Comment by rburing** [comment]
My bad for not spotting it before in my review. @smix8 which places are you referring to exactly?

**Comment by smix8** [comment]
@rburing Oh dont mind me, on second look I was just globalsearching the wrong place. I think you caught everything with your pr.
