### ISSUE TITLE
GPUParticles2D Ignore Parent's "Disabled" Process Mode When Running Game

### ISSUE THREAD

**Issue by floere** [godotengine/godot#75218]
### Godot version

v4.0.1.stable.official [cacf49999]

### System information

macOS Ventura 13.0.1 (22A400)

### Issue description

I expected GPUParticles2D to not run when in a process mode = disabled subtree when set to process mode = inherit. But the GPUParticles2D process material still emits particles (while running, editor is fine).

https://user-images.githubusercontent.com/3022/226890480-3146676a-77b1-4a2f-828a-c0ec5bd3bffd.mp4

### Steps to reproduce

1. Add parent node, set to process mode disabled.
2. Add GPUParticles2D as a child, keep process mode inherit.
3. In the editor, the particles are stopped (or jittering back and forth)
4. When running the "game", particles are emitted and move normally.

### Minimal reproduction project

[BugDisabledGPUParticles2D.zip](https://github.com/godotengine/godot/files/11039431/BugDisabledGPUParticles2D.zip)

**Comment by AThousandShips** [comment]
Strangely it works if you set the mode *while* running, but not if it is set at start

**Comment by AThousandShips** [comment]
I think this should work, it's what I thought as a solution when seeing this

**Comment by newobj** [comment]
Thanks! I wasn't sure what was "the norm" was in Godot re: when to copy vs. encapsulate. I notice the codebase is not overly-encapsulated so I wasn't sure. (btw; wow, the codebase is SO clean + elegant!!) So would your prefer duplication or helper function as I've done?

I'll read the guidelines and do my best to make a good patch. Thanks again for the prompt response!

**Comment by AThousandShips** [comment]
I don't think copy in this case increase the risk of making mistakes, and the usage is local within `_notification` so might be best to copy to not add a new function just for this local case, but I don't think there's any direct opposition to either approach

**Comment by AThousandShips** [comment]
And swapping approach is a trivial change so won't block the success of the PR assuming the basic approach is correct, so use your own judgement
