### ISSUE TITLE
The identifier "VideoStreamWebm" isn't declared in the current scope

### ISSUE THREAD

**Issue by strash** [godotengine/godot#75214]
### Godot version

3.5.2 stable

### System information

MacOS 13.2.1, Apple M1

### Issue description

After exporting to iOS `VideoStreamWebm` appears to be undefined but works just fine in a local build or even in Android build.

### Steps to reproduce

1. add scene and script
2. add `func _ready() -> void: var webm: = VideoStreamWebm.new()`
3. run and see it works
4. export for iOS
5. run iOS build and see it doesn't works

### Minimal reproduction project

-

**Comment by strash** [comment]
If there is a quick fix I would like to know about it. I can't use generic `VideoStream` class because I need to do a `set_file` at runtime. And I can't use `VideoStreamTheora`.

**Comment by AThousandShips** [comment]
Webm is not supported on ios

**Comment by AThousandShips** [comment]
What causes you to be unable to use Theora? Are there no conversions available between the formats?

**Comment by AThousandShips** [comment]
WebM had seems to have some bugs and this support limitation, for those reasons it was dropped in 4.0, probably best to use theora instead as it's more supported and stable

**Comment by akien-mga** [comment]
Closed by #75217.
