### ISSUE TITLE
Make time_scale behave similarly to pause

### ISSUE THREAD

**Issue by ArcFutahito** [godotengine/godot#7521]
time_scale is really useful for slo-mo in games, but making it global limits use cases severely. What I propose is to handle changing scale similar to pause, where user can select some nodes/branches to be excluded from slo mo goodness.

**Comment by Norrolith** [comment]
Seconded.

**Comment by ferhand** [comment]
Yes, yes and three times yes. I second this motion too. An ease way to put some objects in slow motion even if they are influenced by the physics motor. 
Any way if there's a way to achieve that I can't find it...

**Comment by bojidar-bg** [comment]
Duplicate of #6885?

**Comment by bojidar-bg** [comment]
Closing as duplicate, given that nobody responded...
