### ISSUE TITLE
OpenXR default action map not created on macOS

### ISSUE THREAD

**Issue by robagar** [godotengine/godot#75211]
### Godot version

4.0.1

### System information

macOS Ventura 13.2.1

### Issue description

The default action map file `res://openxr_action_map.tres` does not get created automatically by the editor running in macOS.

Creating the file manually also does not work, presumably because the OpenXR module is not loaded at all.

Discord comment reminder as requested by Max213 :)
https://discord.com/channels/212250894228652034/418572953912082432/1087738562956509274

### Steps to reproduce

1. Create new project
2. Enable OpenXR in project settings
3. Save & reload

The default action map file `res://openxr_action_map.tres` should now exist, but doesn't.

### Minimal reproduction project

[Archive.zip](https://github.com/godotengine/godot/files/11037740/Archive.zip)

**Comment by eelcor** [comment]
I have the same problem. Double clicking the res://openxr_action_map.tres throws a bunch of errors stating that a number of classes cannot be found, "Cannot get class 'OpenXRIPBinding'." and "Cannot get class 'OpenXRInteractionProfile'." and "Cannot get class 'OpenXRAction'.". The Action map cannot be added using the "add resource" option, it is not listed. I thought of switching to Sonoma.

I wanted to directy map actions of the controllers to my game, but unfortunately this doesn't work. Hope it can be fixed!

**Comment by BastiaanOlij** [comment]
This was resolved some time ago when we added support for OpenXR to the MacOS build.
See: https://github.com/godotengine/godot/pull/79614

**Comment by KOOT87** [comment]
This issue seems to be back in Godot 4.3 Beta 3 (and possibly in earlier beta versions - didn't check). 
After creating a new project, enabling OpenXR in project settings and restarting the editor, the openxr_action_map.tres is not generated.
Checked Godot 4.2.1 as well, and there it does generate the action map.
I'm running an Intel based Mac on MacOS Sanoma if it helps.

**Comment by akien-mga** [comment]
@KOOT87 This sounds like https://github.com/godotengine/godot/issues/90696 maybe?

**Comment by KOOT87** [comment]
@akien-mga I don't think it's the same issue, but I did some more testing and it does work in 4.3 Beta 2. Also tested on Windows and got the same result there. On 4.3 Beta 2 the action map is created after enabling OpenXR and restarting the editor, while on Beta 3 it does not create the action map. Seems like a regression between Beta 2 and 3

**Comment by eelcor** [comment]
With the older issue, Godot crashed and it really didn't work even when
copying an action map to the game directory. Now, when I copy an older
openxr_action_map.tres to the game folder, I can add actions. Can anyone
confirm this?

Kind regards,
Eelco

Op vr 12 jul 2024 om 21:18 schreef Maarten ***@***.***>:
