### ISSUE TITLE
Tween : tween_callback expect only 1 argument, should be able to take 3

### ISSUE THREAD

**Issue by YouveBeen** [godotengine/godot#75227]
### Godot version

4.0.1

### System information

Windows 10

### Issue description

I need to use tween_callback from scenetreetween, according to the [doc](https://docs.godotengine.org/cs/stable/classes/class_scenetreetween.html#class-scenetreetween-method-tween-callback) it takes 3 arguments,
however it wants to take only one argument. So i cannot pass my parameters to the callback.
https://github.com/godotengine/godot/blob/master/scene/animation/tween.cpp

### Steps to reproduce

new project:
_tween = get_tree().create_tween()
_tween.tween_callback()

### Minimal reproduction project

Not needed

**Comment by AThousandShips** [comment]
The docs you are using are out of date, this is the correct method:
[tween_callback](https://docs.godotengine.org/en/stable/classes/class_tween.html#class-tween-method-tween-callback)

**Comment by YouveBeen** [comment]
> My bad that class is not even the right class, you're looking at `Tween` not `SceneTreeTween` it no longer exists

I'll be able to manage now that i have the right doc :D Thank you

**Comment by AThousandShips** [comment]
No problem! This does seem to be a serious issue with the documentation though will see if there's an issue over in https://github.com/godotengine/godot-docs/issues
