### ISSUE TITLE
EditorSettings's `Show Hidden Files` affects user FileDialog nodes as well

### ISSUE THREAD

**Issue by rsubtil** [godotengine/godot#75220]
### Godot version

3.5.2.stable, 4.0.1.stable

### System information

Arch Linux

### Issue description

When the `Show Hidden Files` property is enabled in the Editor Settings:
![image](https://user-images.githubusercontent.com/6501975/226908540-8e70e520-3dcd-46e4-beaf-103ac176c1de.png)
Any `FileDialog` nodes from the project will inherit this setting, and their `Show Hidden Files` property is set to true everytime the scene is re-opened:

https://user-images.githubusercontent.com/6501975/226909135-a8fafdf7-ca36-40aa-b69a-a7baf2d7ae4f.mp4

This occurs on 3.5.2 as well.

### Steps to reproduce

- Enable `Show Hidden Files` property in the Editor Settings:
    - Reload Godot for the bug to occur
- Create a FileDialog node, and set it's `Show Hidden Files` property to false
- Save and close the scene, and reopen it
- The `Show Hidden Files` property is reset to true.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
This is by design but I'm not sure why

**Comment by AThousandShips** [comment]
It can be set in scenes, though not entirely sure why that would be useful as it's something you can change from the dialog itself, but the current behavior clashes with the scene saving so needs some change

I would assume that the setting in EditorNode is legacy, and should be removed

**Comment by KoBeWi** [comment]
> It can be set in scenes

Yes, but it's overwritten with the static variable, which can't be modified from the editor. It could be a project setting maybe.
