### ISSUE TITLE
[scons] Cannot compile the engine for Visual Studio

### ISSUE THREAD

**Issue by ShlomiRex** [godotengine/godot#75221]
### Godot version

0291fcd7b66bcb315a49c44de8031e5596de4216

### System information

Windows 10

### Issue description

I can't compile godot on windows 10 for visual studio solution project.

### Steps to reproduce

1. Clone godot
2. Run: `scons platform=windows vsproj=yes`
3. I get the following error output:
```
C:\Users\Shlomi\Desktop\Projects\godot_vs>scons platform=windows vsproj=yes
scons: Reading SConscript files ...
Auto-detected 12 CPU cores available for build parallelism. Using 11 cores by default. You can override it with the -j argument.
Found MSVC version 14.3, arch x86_64
Building for platform "windows", architecture "x86_64", target "editor".
TypeError: can only concatenate deque (not "list") to deque:
  File "C:\Users\Shlomi\Desktop\Projects\godot_vs\SConstruct", line 927:
    methods.generate_vs_project(env, GetOption("num_jobs"), env["vsproj_name"])
  File "C:\Users\Shlomi\Desktop\Projects\godot_vs\methods.py", line 859:
    module_configs = ModuleConfigs()
  File "C:\Users\Shlomi\Desktop\Projects\godot_vs\methods.py", line 763:
    self.add_mode()  # default
  File "C:\Users\Shlomi\Desktop\Projects\godot_vs\methods.py", line 786:
    self.arg_dict["cppdefines"] += ModuleConfigs.for_every_variant(env["CPPDEFINES"] + defines)
```

### Minimal reproduction project

None

**Comment by RedworkDE** [comment]
Scons 4.5.0 issue, try to update to the latest patch or if that doesn't help, pinning scons to 4.4.0.

**Comment by ShlomiRex** [comment]
> Scons 4.5.0 issue, try to update to the latest patch or if that doesn't help, pinning scons to 4.4.0.

Upgraded to 4.5.2, same issue

**Comment by ShlomiRex** [comment]
Downgrading to 4.4.0 works:
`pip3 install --force-reinstall -v "scons==4.4.0"`
Closing

**Comment by Calinou** [comment]
- Duplicate of https://github.com/godotengine/godot/issues/74725.
