### ISSUE TITLE
Old Shader applied at random while deleted

### ISSUE THREAD

**Issue by tribly** [godotengine/godot#75231]
### Godot version

v4.0.stable.arch_linux

### System information

Arch Linux, Nvidia GTX 1080 Ti 525.89.02-11, Vulkan

### Issue description

I had a pixelize shader for my playersprite to play around. I've deleted the shader and removed the texture from the playersprite, but for whatever reason it gets applied after some time again. The only solution is to restart Godot.

While the game is running with the faulty shader pausing it and looking at the 'Remote' section doesn't reveal any applied shaders.

**Comment by AThousandShips** [comment]
Please provide an MRP to help with investigating this

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide an MRP or further details this can be reopened
