### ISSUE TITLE
Area3D created in Physicsserver3D dont work

### ISSUE THREAD

**Issue by michurebmann** [godotengine/godot#75239]
### Godot version

4.0 stable

### System information

Windows 10 64bit RTX-3060

### Issue description

I create a Area3D via Physicsserver3D, including callback.
On input press, a second area was created the same way in same position, but the callbacks was not trigered.
I created a Area3D with nodes and move it over a "server-area", but wether the "server area" nor the "node area" callbacks was trigered

### Steps to reproduce

create a new project scene in 3d, paste below code on a script on the root node,

press ui_right to move the "node area" towards where the "server area" should be : no trigger

press ui_down to create a second area on same position where the first is: no trigger

**edit: added the .gd script for reproduce the problem**

### Minimal reproduction project

```gdscript
extends Node3D

var area_node

var area_rid
var collider

var area_rid2

func _ready():
	
	collider = PhysicsServer3D.box_shape_create()
	
	area_node = Area3D.new()
	var colsh = CollisionShape3D.new()
	colsh.shape = BoxShape3D.new()
	area_node.add_child(colsh)
	area_node.transform.origin.x = -2
	add_child(area_node)
	area_node.area_entered.connect(area_enter)
	
	area_rid = PhysicsServer3D.area_create()
	
	
	PhysicsServer3D.shape_set_data(collider, Vector3.ONE)
	
	PhysicsServer3D.area_set_space(area_rid, get_world_3d().space)
	PhysicsServer3D.area_add_shape(area_rid, collider, transform)
	PhysicsServer3D.area_set_collision_mask(area_rid, 1)
	PhysicsServer3D.area_set_collision_layer(area_rid, 1)
	PhysicsServer3D.area_set_monitorable(area_rid, true)
	PhysicsServer3D.area_set_monitor_callback(area_rid, area_enter2)
	
func _process(delta):
	if Input.is_action_just_pressed("ui_right"):
		area_node.translate(Vector3(0.5,0,0))
		
	if Input.is_action_just_pressed("ui_down"):
		
		area_rid2 = PhysicsServer3D.area_create()
		
		PhysicsServer3D.area_set_space(area_rid2, get_world_3d().space)
		PhysicsServer3D.area_add_shape(area_rid2, collider, transform)
		PhysicsServer3D.area_set_collision_mask(area_rid2, 1)
		PhysicsServer3D.area_set_collision_layer(area_rid2, 1)
		PhysicsServer3D.area_set_monitorable(area_rid2, true)
		PhysicsServer3D.area_set_monitor_callback(area_rid2, area_enter2)

func  area_enter(area:Area3D):
	print("entered")
	
func  area_enter2(a, b, c, d, e):
	print("entered")
```

[RID_Test_.zip](https://github.com/godotengine/godot/files/11044788/RID_Test_.zip)

**Comment by Calinou** [comment]
PS: Code blocks should use triple backticks like this (with an optional language name for syntax highlighting):

\`\`\`gdscript
code here
\`\`\`

I edited your post accordingly, but remember to do this in the future :slightly_smiling_face:

**Comment by michurebmann** [comment]
Thanks a lot Calinou!

**Comment by AThousandShips** [comment]
The signal `area_entered` is triggered from the `area_set_area_monitor_callback` callback, the `area_set_monitor_callback` is for bodies

**Comment by AThousandShips** [comment]
So beyond the above, the `area_entered` signal won't be fired because it only fires when a *real* `Area3D` enters, as you can see because the signal has an `Area3D` parameter with it

And if you use the correct monitor function it all works correctly

**Comment by AThousandShips** [comment]
No problem! The new documentation should help indicate that the two different callbacks are for different uses
