### ISSUE TITLE
Gradient.reverse() appears broken.

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#75234]
### Godot version

4.0.1

### System information

Ubuntu 22.04.1 LTS

### Issue description

Reversing a gradient causes its first color to dominate. Reversing it back to how it was fixes it.

Here's a TextureRect with a GradientTexture1D that calls `texture.gradient.reverse()` periodically:

https://user-images.githubusercontent.com/85438892/226996337-d2e38c80-06fc-4ab8-bfcc-dd561575122d.mp4

### Steps to reproduce

Pretty much explained above. Also see the MRP.

### Minimal reproduction project

[BrokenGradientReverse.zip](https://github.com/godotengine/godot/files/11043313/BrokenGradientReverse.zip)

**Comment by AThousandShips** [comment]
Looks like it doesn't update sorting correctly, will see if I can fix

**Comment by MewPurPur** [comment]
I see! This was a major strain on my Gradient Editor PR, I had to do

```Vector<Gradient::Point> pts = gradient->get_points();
pts.sort();
gradient->set_points(pts);```
