### ISSUE TITLE
Godot 4 "Trim" audio import setting does nothing

### ISSUE THREAD

**Issue by markopolojorgensen** [godotengine/godot#75236]
### Godot version

4.0.1 official release

### System information

Windows 10, Forward+, AMD Radeon R9 290X

### Issue description

When importing small wav files, the "Trim" setting in the import dock has no effect. I noticed it for the first time on a ported 3.5 project (where Trim did work).

Expected behavior: trimmed audio files lose the silence at the beginning and end of the stream, so when you play them the actual sound part of the file plays immediately.

Not sure if this is only an issue with wav files, I haven't tried other audio formats.
Not sure if it's related to file length, I've only tried short samples.

### Steps to reproduce

1. Create a wav file with some silence at the beginning and then a sound.
2. Import into a godot 4 project, turn on Trim in import settings for that file.
3. Play audio stream in Inspector or assign it to an AudioStreamPlayer and play in-game.

### Minimal reproduction project

[no_trim_issue_project.zip](https://github.com/godotengine/godot/files/11043682/no_trim_issue_project.zip)

**Comment by AThousandShips** [comment]
Looks like it's due to an incorrect enum, will investigate

**Comment by AThousandShips** [comment]
Regression from #59170

**Comment by AThousandShips** [comment]
This bug is also present on 3.5

**Comment by markopolojorgensen** [comment]
I didn't actually test 3.5, so if you say it's also present there, I believe you. I guess I had imports from an older version that didn't get reimported in 3.5 and so seemed to behave correctly?
