### ISSUE TITLE
UI: Leaving Godot on in the background sometimes corrupts the UI text

### ISSUE THREAD

**Issue by Terpacey** [godotengine/godot#75248]
### Godot version

v4.0-mono stable

### System information

Windows 11, Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz , GeForce RTX 2060, Nvidia driver version 451.67

### Issue description

If left idle for long periods of time(5 days in this case) the UI text gets corrupted for lack of a better word, fixes itself upon reloading 

### Steps to reproduce

Open a Godot project and tab out for a while(occurred with Windows in this case)

If left and then reopened after a while, text looks like this
![image-22](https://user-images.githubusercontent.com/69513762/227087542-b00aa76f-e557-49f4-83d6-8ede18d48240.png)

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Your graphics drivers are very old. Try updating to 531.29 or newer.
