### ISSUE TITLE
randfn() requires at least 2 arguments

### ISSUE THREAD

**Issue by ttexpie** [godotengine/godot#75240]
### Godot version

4.0.1.stable

### System information

Windows 10 64 bit, RTX 2080 SUPER, mobile

### Issue description

Not a big issue, but ```randfn()``` doesn't assume a regular normal distribution (mean = 0, variance = 1) for empty parameters. Appears as error in editor and won't run either.
![image](https://user-images.githubusercontent.com/49420152/227036665-bc4522bb-03ab-4471-a0f3-977374cf96eb.png)
Documentation says that it does take default values, but doesn't work for me.
![image](https://user-images.githubusercontent.com/49420152/227036929-71519a83-bc83-4058-aac3-5282646c402e.png)

### Steps to reproduce

```var rand_num: float = randfn()```

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Documentation you're reading is outdated, not sure why though
[randfn](https://docs.godotengine.org/en/4.0/classes/class_@globalscope.html#class-globalscope-method-randfn)

**Comment by ttexpie** [comment]
![image](https://user-images.githubusercontent.com/49420152/227039737-56f8761b-edfb-4ba9-88cb-a04ca34e64bc.png)
![image](https://user-images.githubusercontent.com/49420152/227039793-a05fc28f-7302-4b2a-bda7-15d693254bd3.png)
Apparently global ```randfn()``` needs both parameters, but ```RandomNumberGenerator.randfn()``` doesn't. Sorry guess I pulled up the wrong function. Still weird one takes default and the other doesn't.
