### ISSUE TITLE
"Input" class fails to initialize when @export_category("Input") exists, but not @export_category("input")

### ISSUE THREAD

**Issue by Nisandra64** [godotengine/godot#75253]
### Godot version

4.0.1 [cacf499999]

### System information

Windows 10

### Issue description

When an `@export_category` exists with the title `Input`, calling a method of `Input` fails with: 
`Nonexistent function '[...]' in base 'Nil'.`

The issue is not present when the `@export_category` is lowercase (*id est* `input` versus `Input`)

### Steps to reproduce

Getting the error:
1. Create a new GDScript file with an `@export_category` with the title `Input` (`@export_category("Input")`)
2. Add a line anywhere in the function that accesses an `Input` method (`var new = Input.[...]()`)
3. Run the scene, receive the error.

Confirming the category name is the issue:
1. Change the `@export_category`'s title to `input`.
2. Run the scene. No error.

### Minimal reproduction project

N/A

**Comment by Nisandra64** [comment]
[Export Error Showcase.zip](https://github.com/godotengine/godot/files/11050224/Export.Error.Showcase.zip)

I didn't think it significant when I created the issue, so I didn't include an example project, but I made one after. The issue is still reproducible. I also forgot to mention that I recently set up VS Code as an external editor, but I haven't had any other issues thus far.

**Comment by AThousandShips** [comment]
Duplicate of #73843

**Comment by Nisandra64** [comment]
> 

Ahh, thank you. I didn't do a very thorough search, but I at least glanced. Thank you. <3
