### ISSUE TITLE
Control.force_drag cannot be used through the touch screen

### ISSUE THREAD

**Issue by tjw123hh** [godotengine/godot#75259]
### Godot version

4.0.1.stable

### System information

Android 7.1.1, GLES3

### Issue description

When using `Control.force_drag` on a touch screen device, dragging stops immediately

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
@tjw123hh Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by tjw123hh** [comment]
I may have mixed things up, it seems that there is a conflict between the built-in drag and the `force_drag`.
