### ISSUE TITLE
godot 4.0.1  videostreamplayer does not play http ogv urls

### ISSUE THREAD

**Issue by flobotics** [godotengine/godot#75265]
### Godot version

4.0.1

### System information

ubuntu 20.0.4

### Issue description

i simply create a 2d node and as child a videostreamplayer, then set http://localhost:8080/stream.ogv to "File" and run it.   The ogv stream comes from :  

`cvlc v4l2:///dev/video0 --no-audio --sout '#transcode{vcodec=theo,vb=800}:standard{access=http,mux=ogg,dst=:8080/stream.ogv}'`

![Screenshot from 2023-03-23 17-14-04](https://user-images.githubusercontent.com/11964445/227267536-51e01b0e-afef-49e6-ab6d-eaf77c3d794e.png)

It returns: cannot open file ?

### Steps to reproduce

run it

### Minimal reproduction project

none

**Comment by AThousandShips** [comment]
The file access system doesn't support network files like this as far as I know, you have to use HTTP or other similar things, the file paths here are strictly filesystem ones, not network

**Comment by flobotics** [comment]
ok, thanks

**Comment by AThousandShips** [comment]
No problem!
