### ISSUE TITLE
Godot 4.0 Item List Bug

### ISSUE THREAD

**Issue by ParasiteSt** [godotengine/godot#75267]
### Godot version

4.0

### System information

Windows 11, Vulkan

### Issue description

I am trying to use the ItemList Node for an inventory, but need the ability to scroll horizontally not only vertically. I thought I found what was needed, which is setting Columns to 0 which states that "all items will be put in the same row" but it does not work.

If 0 is specified for Max Columns there should be a horizontal scrollbar and not start a new row.
![image](https://user-images.githubusercontent.com/100494538/227319194-cd54a5a5-81e4-4b43-8564-e86afc8c1082.png)

### Steps to reproduce

1. Create a new Panel node
2. Create a child node ItemList
3. set the Max Columns to 0
4. create items until it should be off the ItemList's boundaries
5. See that it creates a new row, though it says it wont.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
`ItemList` doesn't have a horizontal scroll bar

**Comment by ParasiteSt** [comment]
Oh, is it possible to have that added if there are unlimited columns?

**Comment by ParasiteSt** [comment]
Ok, should I close this and propose an addition of a horizontal scroll bar to the ItemList node?
