### ISSUE TITLE
GPUParticles2D not emitted in web export

### ISSUE THREAD

**Issue by Sammy-T** [godotengine/godot#75270]
### Godot version

4.0.1.stable

### System information

Windows 10, NVIDIA GeForce GTX 960M (31.0.15.3141), GLES3

### Issue description

GPUParticles2D are not displayed when exporting for web. CPUParticles2D appear to work as expected but the GPUParticles2D displays nothing upon playing the exported project in a browser. 

I've tested in Chrome and Firefox using both Forward+ and Compatibility renderers which all produce the same result for me. Additionally, I've tested a similar project exported using Godot 3.5.2 GLES3 and found that both particles are displayed and emitting correctly in that version.

### Steps to reproduce

1. Create a new project using either Forward+ or Compatibility renderer
2. Create a main scene with Node2D as the root node
3. Set up a CPUParticles2D node and a GPUParticles2D node as child nodes
4. Export for web with default settings
5. Deploy a dev server to play/debug the exported web project

### Minimal reproduction project

[Web Particle Test.zip](https://github.com/godotengine/godot/files/11055295/Web.Particle.Test.zip)

**Comment by Calinou** [comment]
> I've tested in Chrome and Firefox using both Forward+ and Compatibility renderers which all produce the same result for me.

Only the Compatibility rendering method can be used in HTML5.

**Comment by Sammy-T** [comment]
> Trying to use another rendering method will always use Compatibility once you export to HTML5 (check the Project Settings).

I figured they were the same output but I didn't know there was a setting there. Thanks for the heads up.

And I hope you don't mind I saved the log to a file. It would've been a crazy long comment otherwise.
[localhost-1679612291758.log](https://github.com/godotengine/godot/files/11057081/localhost-1679612291758.log)

**Comment by cody82** [comment]
I can reproduce this. GPU particles do not work in web export because of some shader issue:
![image](https://user-images.githubusercontent.com/363688/229598258-d8f2ac2d-dfbf-4823-9e2b-b0516a10fc04.png)

**Comment by cody82** [comment]
How can I change this file in the build? I modified it, recompiled and I get the same error in an exported game.

**Comment by cody82** [comment]
Never mind, I got it. Here is the fix:
https://github.com/godotengine/godot/compare/master...cody82:godot:fix-html-particle-shader

**Comment by Calinou** [comment]
@cody82 Please open a [pull request](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html) against the `master` branch with your changes :)

Remember to modify your changes to follow the [code style guidelines](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html) too.
