### ISSUE TITLE
MenuButton control not yet fully integrated with the editor

### ISSUE THREAD

**Issue by InfiniteProductions** [godotengine/godot#75282]
### Godot version

v4.0.1.stable.official [cacf49999]

### System information

N/A

### Issue description

We can add MenuButton to a scene and fill it with item but still, it's impossible to connect relevant signals for option selection and make it usable as any other control using only the editor.
Signals and option selection management must be done by code like in 2d/3d physics_tests demos.

### Steps to reproduce

-Add aMenuButton control to a scene,
-fill it with some item,
-unable to do more with editor alone, control is unusable without dedicated code to handle option selection

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
I think this is best managed by a proposal to work out how to integrate it, as it is not a simple thing

**Comment by Calinou** [comment]
Closing, as feature proposals should be discussed on the [Godot proposals](https://github.com/godotengine/godot-proposals) repository. This repository is now used for bug reports only.

Make sure to follow the proposal template when opening a new proposal – don't just copy and paste the text you wrote in this issue.

**Comment by AThousandShips** [comment]
You can also achieve most of this functionality by simply adding a `PopupMenu` and controlling it from a button, slightly tricky to get the exact behavior of `MenuButton` but you can get access to all the functionality of the menu like connections, the only feature that's a bit tricky to get working like this is the `switch_on_hover`

This should probably be listed as the possible workaround in any proposal
