### ISSUE TITLE
Maximised window returning to default settings during running.

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#75285]
### Godot version

v4.0.1.stable.official [cacf49999]

### System information

Linux

### Issue description

I have a project whose display window is 1152x648. It has a main menu, with an options sub-menu. 
![tree_inspector](https://user-images.githubusercontent.com/324679/227503567-fb9700ea-b21d-4ec9-b2b5-dfdf3922a8f1.png) is what the scene tree and relevant options for the root node of the options menu look like.

During running, from the main menu, if the program is maximised pressing "Options" will revert it to the default window size. It does not do this if running in full screen.

https://www.dropbox.com/s/qub9pymkeejsmt1/75285_demonstrator.webm?dl=0 is a video showing what I mean.

### Steps to reproduce

The options menu has a `Control` node as its root, with its size set to 1152x648 (display window settings) and anchors preset to "full rect".

### Minimal reproduction project
[75285_demonstrator.zip](https://github.com/godotengine/godot/files/11061323/75285_demonstrator.zip)

**Comment by Calinou** [comment]
Your options menu's script calls `DisplayServer.window_set_mode()` whenever it's opened. Setting the mode to `WINDOW_MODE_WINDOWED` restores (i.e. un-maximizes) the window, which is unexpected.

**Comment by bruvzg** [comment]
> Setting the mode to DisplayServer.WINDOW_MODE_WINDOWED restores (i.e. un-maximizes) the window, which is unexpected.

Why it's unexpected? Maximized is dedicated mode `DisplayServer::WINDOW_MODE_MAXIMIZED`, so un-maximizing a maximized window is exactly what setting mode to `DisplayServer.WINDOW_MODE_WINDOWED` should do.

**Comment by Calinou** [comment]
> Why it's unexpected? Maximized is dedicated mode DisplayServer::WINDOW_MODE_MAXIMIZED, so un-maximizing a maximized window is exactly what setting mode to DisplayServer.WINDOW_MODE_WINDOWED should do.

I forgot `WINDOW_MODE_MAXIMIZED` was a dedicated window mode in 4.x, apologies.

**Comment by Sslaxx** [comment]
> > Why it's unexpected? Maximized is dedicated mode DisplayServer::WINDOW_MODE_MAXIMIZED, so un-maximizing a maximized window is exactly what setting mode to DisplayServer.WINDOW_MODE_WINDOWED should do.
> 
> I forgot `WINDOW_MODE_MAXIMIZED` was a dedicated window mode in 4.x, apologies.
> 
> In this case, this isn't a bug. You need to modify your options script to preserve the maximized mode if the window is currently maximized.

No probs. Thanks for that! Wasn't sure if this was my mistake or something else.

**Comment by Sslaxx** [comment]
Ran into something else. Probably still my end though. The code now accounts for window size. It checks to see if the window size is changed while running and saves that setting. Clicking on "Options" when the app is non-fullscreen, for some reason, still returns the size of the window to the default.
