### ISSUE TITLE
Log function working wrong

### ISSUE THREAD

**Issue by Arfushs** [godotengine/godot#75299]
### Godot version

4.1

### System information

Windows 10

### Issue description

![image](https://user-images.githubusercontent.com/36006828/227624624-ba37becb-cc5a-4274-a6ba-917fe87a1ba8.png)
I printed log(9) but it result seems like 2.192

### Steps to reproduce

var digitCount : int = int(log(9))
print(digitCount) 

### Minimal reproduction project

I don't have a .godot file for this

**Comment by AThousandShips** [comment]
Yes, it's in base e, the documentation says this

**Comment by KoBeWi** [comment]
> it's in base e, the documentation says this

tbh, while the description does say it's not base 10, it only says "natural logarithm" and not everyone knows it's base e.

**Comment by AThousandShips** [comment]
True, my bad, though not sure what the documentation should say if it doesn't assume that knowledge
