### ISSUE TITLE
Save script as new file opens and rebinds unsaved script embedded in scene

### ISSUE THREAD

**Issue by hsandt** [godotengine/godot#75293]
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Linux Ubuntu 22.04 with Unity desktop

### Issue description

When saving an existing script with File > Save as..., the new script is created indeed, but the code editor will open a temporary copy of the original script instead of the new script resource.

In addition, after saving the scene, all instances of the original scripts have been replaced with the temporary copy, now saved as embedded script inside the scene.

![Godot 4 0 - Save as saved temporary script then embed in scene on next save scene (ezgif com-resize)](https://user-images.githubusercontent.com/1067772/227567230-19b320ff-c8d2-4fb7-91b2-d9b70ea9bea3.gif)

It should open the new script resource instead, and probably not rebind script usage at all, since user probably wanted to create an unrelated copy of the script (we could have an option to force rebind of existing instances but even then, it should rebind to the new duplicated script, not some temporary copy embedded in the scene).

In other words, Save as... should act like selecting the script resource in File System, Duplicating it, renaming it, then opening the renamed copy.

### Steps to reproduce

1. Open demo scene and observe Node2D with original_script.gd attached (in the GIF, we attach it live)
2. Open original_script.gd and select File > Save as... and enter new_script.gd
3. Observe the resulting file is not "new_script.gd" but "[unsaved](*)"
4. In VCS or file system, observe that new_script.gd was properly created, just not used
5. Save the scene
6. Observe that the temporary unsaved file has now been saved, embedded in the scene as "demo.tscn:..."

### Minimal reproduction project

[v4.0 - Save script as opens and rebinds unsaved script embedded in scene.zip](https://github.com/godotengine/godot/files/11063652/v4.0.-.Save.script.as.opens.and.rebinds.unsaved.script.embedded.in.scene.zip)

**Comment by hsandt** [comment]
No, indeed, it seems to have been fixed between 4.0 and 4.0.1!

**Comment by hsandt** [comment]
Oops, an issue remains though: the second part where it replaces all instances of the script.

Not sure if it's a bug or by design, it certainly surprised me though. Plus, it only replaces scripts in open scenes, so depending on which scenes are open at the moment, you may only update part of your project.

I'll open a bug as I don't expect Save as... to modify existing references to the script.

**Comment by AThousandShips** [comment]
The reason it changes it in open scenes is likely because it probably changes the path of the script resource, which means when the scene saves it takes that path
