### ISSUE TITLE
Child movement bug

### ISSUE THREAD

**Issue by Perndoe** [godotengine/godot#75305]
### Godot version

4.0 and 4.1 mono stable

### System information

Edition	Windows 11 Pro Version	22H2 Installed on	‎11/‎12/‎2022 OS build	22621.1413 Experience	Windows Feature Experience Pack 1000.22639.1000.0

### Issue description

Move first child (with script) move child with no script

### Steps to reproduce

Put normal node (with sprite) as a child of a world node2d scene and put a player scene with movement script as child of the world scene too then when play the game and move it move both and the normal node got slippery movement while no script is attached to it

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/11067932/Test.zip)

**Comment by timothyqiu** [comment]
Child 2D nodes's position property is relative to their parent node. So if the parent node moves, the child nodes should move too.

**Comment by Perndoe** [comment]
> Child 2D nodes's position property is relative to their parent node. So if the parent node moves, the child nodes should move too.

Why is it slippery and move in opposite direction

**Comment by Perndoe** [comment]
sorry i reedited the bug

**Comment by Calinou** [comment]
This is unlikely to be a bug.

Please don't ask support questions here, as this issue tracker is meant to be used for bug reports only. Use one of the other [community channels](https://godotengine.org/community) instead.

> and how to even stop the child from moving

You can call `set_as_top_level(true)` on the child node to make it ignore the parents' transforms.
