### ISSUE TITLE
Texture Bug/Feature?

### ISSUE THREAD

**Issue by walidsantos** [godotengine/godot#75312]
### Godot version

4.0.1.stable and 4.0

### System information

Windows 10,  Intel(R)HD Graphics Family, 20.19.15.5171,  GLES3

### Issue description

The texture looks normal in editor but when
Running the project the texture is weird.

I tried experimenting in Settings but i can't find the solution. :(

![image](https://user-images.githubusercontent.com/53328867/227708333-8b8822af-e071-4219-abc8-76470b5b8b7c.png)

### Steps to reproduce

"The texture looks normal in editor but when
Running the project the texture is weird.

rotating the texture  has pixel rotation too 
![image](https://user-images.githubusercontent.com/53328867/227708565-5eb27b34-e38c-4d53-bdbd-62b96c881eba.png)

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
> To speed up our work, please upload a minimal project that isolates and reproduces the issue. This is always the best way for us to fix it. We recommend attaching a ZIP file with the minimal project directly to the bug report, by drag and dropping the file in the GitHub edition field. This ensures the file can remain available for a long period of time. Only use third-party file hosts if your ZIP file isn't accepted by GitHub because it's too large.
>
> We recommend always attaching a minimal reproduction project, even if the issue may seem simple to reproduce manually.

It's impossible to tell what's going on just from your description, we need settings, how you're using the texture, etc

**Comment by Calinou** [comment]
This looks like uneven pixel scaling. See https://github.com/godotengine/godot-proposals/issues/1666.

**Comment by walidsantos** [comment]
@Calinou it appears the solution for this problem is just setting the stretch mode to canvas_item instead of viewport
