### ISSUE TITLE
GDScript makes unexpected priority in evaluatgin boolean logic expression

### ISSUE THREAD

**Issue by albinaask** [godotengine/godot#75335]
### Godot version

4.0.1

### System information

Windows 11 x86-64 architecture

### Issue description

evaluating the following statement:

```
var _button:Button
#works
func do_something():
	if (_button != null) && _button.button_pressed:
#doesn't work
func do_something_else():
	if _button != null && _button.button_pressed:
```
Yields a compile time error in the "do_something_else" method, while not in the "do_somethig" method. You would expect the compiler to first evaluate the two expressions, i.e `_button!=null` and `_button.button_pressed` then after that weigh them together with the `&&` no matter the parentheses. This code ran fine in godot 3.5

### Steps to reproduce

1. Open Godot
2. Create a script of type GDscript
3. Paste code from above
4. Observe weird compile-time-error.

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
The compile time error is due to missing indented block after `if`. If you swap the methods, your error will be "inside" `do_something()`.

**Comment by albinaask** [comment]
Ah, the pass statements didn't transfer over, but now restarting godot I can't reproduce the bug either, so oh well.
