### ISSUE TITLE
Issue with how the engine sets unique instance ids

### ISSUE THREAD

**Issue by Evanator05** [godotengine/godot#75347]
### Godot version

4.0.1

### System information

Windows 11

### Issue description

Node ids do not stay consistent when changing or reloading scenes in godot 4

this is a problem for me because I use unique ids to save certain objects state in my game world so fixing this would be really appreciated 

### Steps to reproduce

Place a node in the world
Attack a script to it and print its unique id
then reload the scene
print its id again
``` gdscript
extends Node

func _ready():
	print(get_instance_id())
	await get_tree().create_timer(1).timeout
	get_tree().reload_current_scene()
```
You will notice that every time you launch the game the first time the id is the same but each time after its different. This is also a problem when you start on once scene but then change to a different scene afterwards so the problem isnt just with reloading the current scene

### Minimal reproduction project

steps to recreate are pretty simple

**Comment by AThousandShips** [comment]
Instance IDs are not unique between runs, they couldn't be

**Comment by AThousandShips** [comment]
But there's no guarantee given that these IDs be identical, and wouldn't be feasible to make them so

**Comment by Evanator05** [comment]
> But there's no guarantee given that these IDs be identical, and wouldn't be feasible to make them so

thank you, are you aware of any way to uniquely identify individual nodes in godot 4 then?
or do I need to make a system myself

**Comment by AThousandShips** [comment]
You can give them unique names, or use their paths, both are unique

**Comment by Evanator05** [comment]
> You can give them unique names, or use their paths in the scene, both are unique

I dont know how I didnt think of using their path, thank you

**Comment by AThousandShips** [comment]
No problem!
