### ISSUE TITLE
Document which texture types can be used in a Sprite3D

### ISSUE THREAD

**Issue by phunnyguy** [godotengine/godot#75342]
### Godot version

4.0

### System information

PopOS, Forward+, Nvidia 960M(525.85.05), Forward+(Vulkan)

### Issue description

Using a Canvas Texture on a Sprite3D results in a white image when it should just display the sprite.

![whitesprite](https://user-images.githubusercontent.com/90366172/227751160-65e69cf4-cddd-4b76-99f9-2d127f8899cc.png)

### Steps to reproduce

Create Canvas Texture using a sprite sheet. Use that Canvas Texture with a Sprite3D

### Minimal reproduction project

[test-project.zip](https://github.com/godotengine/godot/files/11070591/test-project.zip)

**Comment by Calinou** [comment]
CanvasTexture is only meant for 2D usage, not 3D.

The engine should print an error when attempting to use incompatible texture types in materials.

**Comment by phunnyguy** [comment]
Attempting to use StandardMaterial3D with a Sprite3D node isn't possible either because the engine does not allow it. Giving me this error. 
![unable to use material3d on sprite3d](https://user-images.githubusercontent.com/90366172/227752555-5a67d54f-54ed-4f9d-b4ca-01ce34316590.png)

**Comment by Calinou** [comment]
> Attempting to use StandardMaterial3D with a Sprite3D node isn't possible either because the engine does not allow it. Giving me this error.

StandardMaterial3D can only be used in MeshInstance3D's material properties, or Material Override/Overlay on a node that inherits from GeometryInstance3D (this includes Sprite3D, but its size must be set by also defining a texture in the texture property).
