### ISSUE TITLE
Area2D has inconsistent interactions with StaticBody2D when the Area2D is moving or still

### ISSUE THREAD

**Issue by wallyfoo** [godotengine/godot#75358]
### Godot version

4.0.1 stable

### System information

MacOS 13.0, Forward+, M1 Metal

### Issue description

Area2D has an inconsistent interaction with StaticBody2Ds. When Area2D holds still, it can't see the moving StaticBody2D.

For my project, I'm scaling StaticBody2D for interactions between CharacterBody2D and Area2D. I discovered an inconsistency when these scaled StaticBody2Ds entered into the Area2D's collision bodies. The Area2D didn't send the body_entered(body) signal unless the Area2D was in motion. A simple rotation on the Area2D will do the trick. Here's a short video of my test case:

https://user-images.githubusercontent.com/6932210/227780426-52fe7c25-435f-4c9b-8076-b335733b500a.mov

My expectation is that an Area2D would detect the StaticBody2D whether or not the Area2D is in motion.

tl;dr:  StaticBody2D plays a game of "Red Light, Green Light" with Area2D. 

### Steps to reproduce

Play the sample scene called "scene" in the attached project.

For my simple example, I created an Area2D scene that turns red when a body enters it, and reverts back to white when the body exits. I scale a StaticBody2D using an AnimationPlayer node. Instancing the Area2D scene three times, one instance stays still, one rotates constantly, and another moves into the StaticBody2D then holds still and lets the StaticBody2d move out of its collision body on its own.

The Area2D that doesn't move ignores the StaticBody2D and never sends the appropriate signals.

The Area2D that moves into the StaticBody2D then holds still sends the appropriate signals. I was wondering if moving into the StaticBody2D would send the body_entered(body) signal, and if holding still wouldn't send the body_exited(body) signal, but that works as expected.

The rotating Area2D also successfully sends the body_entered(body) and body_exited(body).

### Minimal reproduction project

[Areas and Static Bodies.zip](https://github.com/godotengine/godot/files/11071737/Areas.and.Static.Bodies.zip)

**Comment by Calinou** [comment]
> it can't see the moving StaticBody2D.

You should use AnimatableBody2D if you're moving a static body at run-time somehow.

**Comment by AttackButton** [comment]
> I don't claim to understand the design decisions behind adding a separate node inheriting StaticBody2d that seems to be "the same, only you can animate it", but I'll suggest a more prominent mention in the documentation to the powers that be.
> 
> Looking back over the docs for StaticBody2D, I now recognize that there's an "Inherited By AnimatableBody2D" up underneath the "Inherits" tree that gets kind of lost in the visual clutter.
This exists to respect the design of the staticbody, which is supposed to be a body that doesn't move at all.
