### ISSUE TITLE
Unary minus does not work in gdshaders

### ISSUE THREAD

**Issue by JohanAR** [godotengine/godot#75351]
### Godot version

v4.1.dev.custom_build [6ef2f358c]

### System information

Fedora 37 KDE, RTX 3080

### Issue description

Godot's shader compiler removes spaces and parentheses from expression, causing unary minus (and probably the less common unary plus) to merge with adjacent operator tokens.

Addtionally, the only error logged in the editor is:
> servers/rendering/renderer_rd/forward_clustered/scene_shader_forward_clustered.cpp:171 - Condition "!shader_singleton->shader.version_is_valid(version)" is true.

If running the editor from a console, it prints the compiled shader, the error message from the glsl compiler, and then it prints the compiled shader again.

### Steps to reproduce

```
void fragment() {
	float a = 0.5;
	float b = 1.0 - -a;
	float c = 1.0 - -0.5;
	float d = 1.0 - (-0.5);
	float e = 1.0 - -(0.5);
}
```

```
2145 |  {
2146 |          float m_a=0.5;
2147 |          float m_b=(1.0--m_a);
2148 |          float m_c=(1.0--0.5);
2149 |          float m_d=(1.0--0.5);
2150 |          float m_e=(1.0--0.5);
2151 |  }
```

### Minimal reproduction project

Trivial. Just copy one of the expressions into a new shader.

**Comment by Calinou** [comment]
cc @Chaosus
