### ISSUE TITLE
RPC referencing level objects with different instances ID's on different machines

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#7535]
**Operating system or device - Godot version:**

windows 10 and ubuntu, godot version 2.2

**Issue description** (what happened, and what was expected):

I'm trying to get multiplayer working using the high level networking in 2.2.

I am passing an object to an RPC function. On the client that calls the RPC function, the RPC function gets called and has a valid pointer to the objects. On the other client, I get null pointers.

I have debugged the instance_id for these objects and noticed they are different on the two clients. I assume this instance id is meant to be the same on both clients in order for a correct reference to be obtained. These objects I am referencing are just objects in the level.

I've printed out the instances id's of all game objects to debug this and notice that there is an issue as soon as my level has loaded.

if you diff these two files:
[log.txt](https://github.com/godotengine/godot/files/706509/log.txt)
[log_nix.txt](https://github.com/godotengine/godot/files/706510/log_nix.txt)

on file is the client (log_nix.txt) the other is the server log (log.txt)

you will see the id's go out of sync at:

Linux: World - ID: 950
Windows: World - ID: 952

I suspect this is the problem.

If a client does not connect, my windows machine ID is around 948, so when the client connects this is when the id's are going out of sync. I suspect the server makes some game objects that are discarded at this point.
Even if this is the case, a typical game might make different objects throwing instance id's out of sync even before the client connects.

There looks like there needs to be a special synchronization of instance id's.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by bojidar-bg** [comment]
I think instance ids shouldn't be used to synchronize data between the client and the server, as they are just incremented every time a new object is created, and therefore differ between the two.

**Comment by reduz** [comment]
Use the path in the scene for this, not the instance ID

**Comment by Gibbz** [comment]
okay, that seems needlessly inefficient. I assume that means we are now sending strings over the network instead of binary numbers?

Perhaps some technique to use an id (this might be a special network id instead of the instance id) should be considered for performance reasons... sending less data over the network.

Also, if this is the case, this should happen automatically when i call rpc("blah", myObject)
I would expect this to happen automatically behind the scene, instead I need to do:
rpc("blah", myObject.get_path())

but for now I will go with your advice.

**Comment by reduz** [comment]
Just call the rpc directly on the object you need to modify, then

**Comment by reduz** [comment]
that said, Godot converts paths to network IDs internally already, but I
think not for function arguments, this could probably be added at some point

**Comment by supagu** [comment]
okay thanks guys, changing to use get_path works.

**Comment by supagu** [comment]
Doing more work with multiplayer, there are still a few issues:

1. if i let the engine name instances it uses the instance id in the name, so cannot be resolved over the network - this then forces me to have to name my objects

2. this is unrelated to this bug but it seems rpc is not always getting through to the clients - particularly seems troublesome if i have an rpc call straight after another rpc call, and variable syncing also doesn't seem to work for me.

**Comment by reduz** [comment]
Yes, naming your nodes the same on both ends for doing RPC is crucual for
getting multiplayer to work. This is a feature, not a bug. You are expected
to name them the same.

RPC should work always, unless you use the rpc_unreliable() call

**Comment by supagu** [comment]
ok, ta
