### ISSUE TITLE
[4.1dev ] Godot.Collections.Array.AddRange() index out of bounds

### ISSUE THREAD

**Issue by Redwarx008** [godotengine/godot#75356]
### Godot version

[4.1dev ] mono

### System information

win10, vulkan, AMD Radeon, Nvidia gtx 1660ti

### Issue description

For example
```C#
		int[] test = new int[12];
		Array.Fill(test, 1);
		Godot.Collections.Array<int> ints = new Godot.Collections.Array<int>();
		ints.AddRange(test);
```
ERROR: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')

   at Godot.Collections.Array`1.set_Item(Int32 index, T value) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Array.cs:line 1360

   at Godot.Collections.Array`1.AddRange(IEnumerable`1 collection) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Array.cs:line 1588

I found the corresponding code and found the problem. Line 1588 may be wrong, it should be changed to this[Count +i].
![图片](https://user-images.githubusercontent.com/50837890/227776895-cec0fee4-d964-434e-b434-130788985d7a.png)

### Steps to reproduce

-

### Minimal reproduction project

-

**Comment by raulsntos** [comment]
Looks like you have already figured out the fix, feel free to open a pull request :slightly_smiling_face:.

**Comment by Redwarx008** [comment]
I don't know why, the problem is still there after modification.
I tried calling Resize before calling AddRange in 4.0.1, no error was reported, maybe more testing is needed.
```C#
		int[] test = new int[12];
		Array.Fill(test, 1);
		Godot.Collections.Array<int> ints = new Godot.Collections.Array<int>();
		ints.Resize(ints.Count + test.Length);
		ints.AddRange(test);
```

**Comment by Redwarx008** [comment]
Interestingly, when I launch from 4.0.1 with 4.1.0's nuget, it behaves the same as in 4.0.1. Starting with 4.1.0, even calling Resize before AddRange has no effect.

**Comment by raulsntos** [comment]
You are right. Resizing changes the value of the `Count` property, so the calculation of the index is still incorrect, it needs to use the old `Count` value (before `Resize`).

Something like this should work:

```diff
diff --git a/modules/mono/glue/GodotSharp/GodotSharp/Core/Array.cs b/modules/mono/glue/GodotSharp/GodotSharp/Core/Array.cs
index 000e3ed849..12487a1309 100644
--- a/modules/mono/glue/GodotSharp/GodotSharp/Core/Array.cs
+++ b/modules/mono/glue/GodotSharp/GodotSharp/Core/Array.cs
@@ -554,14 +554,15 @@ namespace Godot.Collections
             // instead of growing it as we add items.
             if (collection.TryGetNonEnumeratedCount(out int count))
             {
+                int i = Count;
                 Resize(Count + count);
 
                 using var enumerator = collection.GetEnumerator();
 
-                for (int i = 0; i < count; i++)
+                for (; i < count; i++)
                 {
                     enumerator.MoveNext();
-                    this[Count + i] = Variant.From(enumerator.Current);
+                    this[i] = Variant.From(enumerator.Current);
                 }
 
                 return;
@@ -1578,14 +1579,15 @@ namespace Godot.Collections
             // instead of growing it as we add items.
             if (collection.TryGetNonEnumeratedCount(out int count))
             {
+                int i = Count;
                 Resize(Count + count);
 
                 using var enumerator = collection.GetEnumerator();
 
-                for (int i = 0; i < count; i++)
+                for (; i < count; i++)
                 {
                     enumerator.MoveNext();
-                    this[Count + i] = enumerator.Current;
+                    this[i] = enumerator.Current;
                 }
 
                 return;

```

**Comment by RedworkDE** [comment]
> Something like this should work:

This only adds `count - Count` items, Either the old or the new size has to be saved in a variable and then used to add like in the original code or as the upper bound of the loop like in that patch.

**Comment by Redwarx008** [comment]
> > Something like this should work:
> 
> This only adds `count - Count` items, Either the old or the new size has to be saved in a variable and then used to add like in the original code or as the upper bound of the loop like in that patch.

Thank you, the PR has been updated
