### ISSUE TITLE
Missing Audio Settings in Project Settings for Godot 4.0.1

### ISSUE THREAD

**Issue by juancarlosmaggi** [godotengine/godot#75360]
### Godot version

4.0.1

### System information

Windows 11

### Issue description

The latest version of Godot (4.0.1) seems to have an issue with its Audio Settings in the Project Settings. The only available option for Audio is the Default Bus Layout, and it is missing important settings such as "Enable Audio Input". As a result, users who need to enable microphone input for their projects have to manually add the following lines to their project file:

[audio]
driver/enable_input=true
enable_audio_input=true

### Steps to reproduce

1. Open Godot 4.0.1.
2. Create a new project or open an existing one.
3. Go to the Project Settings.
4. Click on the "Audio" section.
5. Observe that the only available option is the "Default Bus Layout".
6. Notice that there are no options to enable or configure audio input.

### Minimal reproduction project

[test2.zip](https://github.com/godotengine/godot/files/11071912/test2.zip)

**Comment by AThousandShips** [comment]
They are right there, under `audio/driver/enable_input`, you need to turn on advanced settings though

**Comment by juancarlosmaggi** [comment]
> They are right there, under `audio/driver/enable_input`, you need to turn on advanced settings though

You are right, did not notice the advance settings brought them out.

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot-proposals/issues/6530.
