### ISSUE TITLE
SDFGI doesn't work on Geforce GTX 680

### ISSUE THREAD

**Issue by ErwinBr** [godotengine/godot#75362]
### Godot version

v4.0.stable.official [92bee43ad]

### System information

MacOS 10.15.2

Video:
NVIDIA GeForce GTX 680
VRAM (Total):	2 GB
Metal: Supported, feature set macOS GPUFamily1 v4

### Issue description

Vulkan API 1.2.231 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 680

does not render when SDFGI is enabled. The picture changes colour like a kaleidoscope, until all is white. See attached screenshot.

![SDFGI_GTX680](https://user-images.githubusercontent.com/46350573/227784866-f6f70efb-2a65-48ef-a9c8-90809bd822ac.png)

### Steps to reproduce

Enable SDFGI.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
@ErwinBr Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.
