### ISSUE TITLE
Camera3D orthogonal size inspector slider does not have useful limits

### ISSUE THREAD

**Issue by Deozaan** [godotengine/godot#75377]
### Godot version

v4.0.1.stable.official [cacf49999]

### System information

Windows 10

### Issue description

Using the grabber to adjust an orthogonal Camera3D's `size` value is not very useful. The slider's minimum and maximum values are so extreme that dragging the grabber a single pixel in any direction changes the value by a very large amount.

By contrast, clicking and dragging directly in the value field itself gives more useful deltas.

[Camera3D Orthogonal Size Slider.webm](https://user-images.githubusercontent.com/227734/227844703-5b4ba28f-612a-438e-9cda-65b8773c5a71.webm)

### Steps to reproduce

Shown and described above.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/36446.
