### ISSUE TITLE
AnimationTree: Frame has mixed information when using both continuous and discrete animation tracks while auto transitioning in AnimationNodeStateMachine

### ISSUE THREAD

**Issue by Akatuoro** [godotengine/godot#75373]
### Godot version

v4.0.stable.official.92bee43ad and v4.0.1.stable.official.cacf49999

### System information

Windows 10

### Issue description

In an AnimationNodeStateMachine, when transitioning between animation states (with 'At End', 'Auto'), there is a single frame glitch showing a mix of the old and the new animation (old `region_rect` and new `frame` for a `Sprite2D`). The `region_rect` track has 'Update Mode' 'Continuous' while the `frame` track has 'Update Mode' 'Discrete'.

When changing the animation directly on the AnimationPlayer (via timer), it correctly shows the new animation.

https://user-images.githubusercontent.com/4891926/227811062-ad639403-b3d2-4fdb-9942-99793763e326.mp4

When logging the changing `region_rect` and `frame` values in `_process`, the frame is also visible:
```
# using AnimationNodeStateMachine
region x: 64, frame: 0, anim:   blue12, pos: 0.008333
region x: 64, frame: 1, anim:   blue12, pos: 0.400000
region x: 64, frame: 0, anim:  black12, pos: 0.000000   # this is unexpected
region x:  0, frame: 0, anim:  black12, pos: 0.008333
region x:  0, frame: 1, anim:  black12, pos: 0.400000
region x:  0, frame: 0, anim:   blue12, pos: 0.000000   # here as well
region x: 64, frame: 0, anim:   blue12, pos: 0.008333
region x: 64, frame: 1, anim:   blue12, pos: 0.400000
region x: 64, frame: 0, anim:  black12, pos: 0.000000   # etc.
region x:  0, frame: 0, anim:  black12, pos: 0.008333
```

```
# using AnimationPlayer.play()
region x:  0, frame: 1, anim:  black12, pos: 0.400000
region x: 64, frame: 0, anim:   blue12, pos: 0.008333
region x: 64, frame: 1, anim:   blue12, pos: 0.400000
region x:  0, frame: 0, anim:  black12, pos: 0.008333
region x:  0, frame: 1, anim:  black12, pos: 0.400000
region x: 64, frame: 0, anim:   blue12, pos: 0.008333
region x: 64, frame: 1, anim:   blue12, pos: 0.400000
region x:  0, frame: 0, anim:  black12, pos: 0.008333
```

Switching the 'Update Mode' to 'Discrete' for the `region_rect` animation track fixes the glitched frame. But that inhibits other functionality, so my expectation would be that the animation state transition also behaves coherently with 'Update Mode' set to 'Continuous'.

### Steps to reproduce

Create 2 animations in an AnimationPlayer, each with a track for `region_rect` and `frame` on a Sprite2D:

<img width="1503" alt="anim1" src="https://user-images.githubusercontent.com/4891926/227810424-0a404ef2-ad93-4495-8d31-45d914903742.png">

<img width="1501" alt="anim2" src="https://user-images.githubusercontent.com/4891926/227810406-9bac1c92-e322-4312-bc3d-b5be7f8e8b6a.PNG">

Then create an AnimationTree with an AnimationNodeStateMachine that automatically transitions between these animations with switch mode 'At End':
<img width="602" alt="animtree" src="https://user-images.githubusercontent.com/4891926/227810410-22d03131-bcb3-489e-b75e-5ab77271c84e.PNG">

### Minimal reproduction project

[reproduce-animation-bug.zip](https://github.com/godotengine/godot/files/11073293/reproduce-animation-bug.zip)

**Comment by TokageItLab** [comment]
Closed by https://github.com/godotengine/godot/pull/86629 (or previous)
