### ISSUE TITLE
Margin Containers consume mouse input even when filter set to PASS

### ISSUE THREAD

**Issue by CosmoD3v** [godotengine/godot#75372]
### Godot version

4.0.stable

### System information

Windows 10

### Issue description

While working on a project, I was having issues using the mouse_entered signal. 
One of my nodes was consuming the mouse event, after some digging I found the culprit; MarginContainer.

I decided to create a new test scene to re-create the bug and to my surprise, **the bug still occured**.
MarginContainer nodes will **always** consume mouse input events when set to **mouse filter PASS** if a margin container exists in the scene tree lower than the node that you are attempting to receive them in.

I waved my mouse over the area of the nodes and the console didn't log anything from my script.
Once I changed the MarginContainer's mouse filter to ignore, it finally got it to print the event in my other node.

Temporarily, you can opt to have that container always ignore mouse events so that they can be caught elsewhere.
But for now, you'll just have to deal with margin containers always consuming these events if set to Pass.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/97708882/227810928-e8866987-16e6-46b9-99fe-062f2ac6acbe.png)
![image](https://user-images.githubusercontent.com/97708882/227811413-93d6b97c-e171-41ce-9978-195f8b7d3ccd.png)
![image](https://user-images.githubusercontent.com/97708882/227810974-69a53ba4-e0a3-4b02-bfbb-5384d3fdbdf0.png)
![image](https://user-images.githubusercontent.com/97708882/227811123-dbf5a4f6-ecdb-4f2a-91ba-edfdd87f6016.png)

### Minimal reproduction project

[Reproduction Project.zip](https://github.com/godotengine/godot/files/11073331/Reproduction.Project.zip)

**Comment by KoBeWi** [comment]
From PASS description:
> If this control does not handle the event, the parent control (if any) will be considered, and so on until there is no more parent control to potentially handle it.

The event is passed to parent nodes not siblings. You need to use IGNORE.

See also https://github.com/godotengine/godot-proposals/issues/3613 and the other linked issues in there.
