### ISSUE TITLE
Typed arrays won't accept node references with $

### ISSUE THREAD

**Issue by xxSeys1** [godotengine/godot#75393]
### Godot version

4.0.1

### System information

Windows 11, Vulkan, ryzen 9 5900X, rx 6700xt

### Issue description

When creating a typed array
(take `var wheels: Array[VehicleWheel3D]` as an example)

and then trying to add a node to the array by referencing it with `$`
(for example `var wheels: Array[VehicleWheel3D] = [$BackLeftWheel]`)

it will return the following error:
_Cannot have an element of type "Node" in an array of type "Array[VehicleWheel3D]"_

I have a theory that this is due to `$MyNode` being the same as `get_node("MyNode")` for the parser and `get_node()` has a return type of `Node`, so the parser thinks that you are trying to append a `Node` to the array (Haven't checked that in the source code, it's just a theory). 

![image](https://user-images.githubusercontent.com/111653551/227974121-e0be38bc-8c99-47f1-adf6-775083805cff.png)

This can be worked around by casting the node as the intended type
(`var wheels: Array[VehicleWheel3D] = [$BackLeftWheel as VehicleWheel3D]`)

### Steps to reproduce

See "Issue description" and "Minimal reproduction project"

### Minimal reproduction project

[Typed Array issue rep project.zip](https://github.com/godotengine/godot/files/11080146/Typed.Array.issue.rep.project.zip)

**Comment by TokisanGames** [comment]
Does it work with a UniqueName and %?

**Comment by xxSeys1** [comment]
> Does it work with a UniqueName and %?

No, same error message as before.

**Comment by dalexeev** [comment]
> I have a theory that this is due to `$MyNode` being the same as `get_node("MyNode")` for the parser and `get_node()` has a return type of `Node`, so the parser thinks that you are trying to append a `Node` to the array

Yes it is. You can use the `as` keyword to work around this:

```gdscript
var wheels: Array[VehicleWheel3D] = [$BackLeftWheel as VehicleWheel3D]
```

I'm not sure if this is a bug or not. Perhaps this should be a warning, not an error.

CC @vonagam
