### ISSUE TITLE
C# Script: Duplicate signal receiver method creation 

### ISSUE THREAD

**Issue by MisoMosiSpy** [godotengine/godot#75391]
### Godot version

v4.0.1.stable.mono.official [cacf49999]

### System information

Windows 11, Forward+

### Issue description

A duplicate method is created when selecting an existing method as a signal receiver. Since the required method already present it should not be added again.

If this works as expected it can be a workaround for issue https://github.com/godotengine/godot/issues/18721.

### Steps to reproduce

1. Add Node as a root node
2. Attach new C# script to this node
3. Add new method in the script which can work as a signal receiver (e.g. OnTimerTimeoutHandler())
4. Add a new child node (e.g. Timer)
5. Select the Timer.timeout() signal from the "Node" tab of inspector and connect
6. In the "Connect Signal toa  Method" Dialog, click "Pick"
7. Select the existing function (e.g. OnTimerTimeoutHandler) from the list and clik "OK"
8. Observe that the another method with name OnTimerTimeoutHandler() is added at the end of the script.
![CS_DuplicateSignalhandler](https://user-images.githubusercontent.com/52410428/227950101-2b04c623-b61f-480e-85fb-49d74bc457d9.gif)

### Minimal reproduction project

Please refer to "Steps to reproduce" if still needed I can provide the zip file.

**Comment by kleonc** [comment]
#75524 is a duplicate, but by now it has more details about the issue. Hence closing this one in favor of #75524.
