### ISSUE TITLE
Export with custom serializers/deserializers

### ISSUE THREAD

**Issue by raymoo** [godotengine/godot#7539]
This is a feature suggestion.

There should be a way to give custom (de)serialization code for the export of a variable. E.g. something like
```
export(ser_foo, deser_foo) foo = SomeClass()

func ser_foo(foo_thing):
    return doSomething(foo_thing) # Something that returns a string

func deser_foo(str):
    return doSomethingElse(str) # Something that returns a valid value for foo
```

It might be useful to parameterize also on the export type, but just exporting custom exports as strings would cover the majority of uses, I would guess.

I can think of a couple potential uses:
 - If exported to a human-readable format, could allow easier modification from the editor.
 - It would allow the saving of ordinarily non-exportable values when packing scenes, for example when unloading an area in an open-world game.

**Comment by bojidar-bg** [comment]
Isn't this all setters and getters are about ( [the `setget` GDScript keyword](http://docs.godotengine.org/en/stable/reference/gdscript.html#setters-getters) )

**Comment by raymoo** [comment]
@bojidar-bg Looks like that works, sorry.
