### ISSUE TITLE
macOS dotnet project crashes on run

### ISSUE THREAD

**Issue by dunyakilavuz** [godotengine/godot#75390]
### Godot version

v4.0.1.stable.mono.official [cacf49999]

### System information

macOS Ventura 13.2.1, dotnet 7.0.202

### Issue description

I can't run a project on macOS, which i am able to on the Windows 11. When I hit run project, I can not see the game window opening. And macOS gives this error afterwards. Engine does not show any errors however.

[crash_log.txt](https://github.com/godotengine/godot/files/11078911/crash_log.txt)

I have tested another dotnet project which runs fine on both macOS and Windows. Yet when I close it, it also makes macOS throw this cras log.

[crash_log.txt](https://github.com/godotengine/godot/files/11078954/crash_log.txt)

I'm not quite sure on how to approach the error, any help would be appreciated.

### Steps to reproduce

The error does not happen in all projects. Sadly i'm not sure on how to reproduce this on other projects.

### Minimal reproduction project

The project im trying to run is quite large. I'm trying to make a version which works by bisecting parts of it until it works.

**Comment by Calinou** [comment]
@dunyakilavuz Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

Without a minimal reproduction project, we can't do anything about this.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
