### ISSUE TITLE
Weird transparency issue when importing blend file

### ISSUE THREAD

**Issue by sygi** [godotengine/godot#75405]
### Godot version

4.0-stable

### System information

Ubuntu 22.04

### Issue description

I'm trying to import a blend file. When I double click it, the import options (right) show the model correctly. However, when I pull the model to a 3D scene, there are artifacts (left).

![Screenshot from 2023-03-27 20-22-14](https://user-images.githubusercontent.com/495380/228045480-bd0f20de-c508-4e3a-b5a9-9c18ad651443.png)

The issue exists in both Forward and Compatibility modes.

### Steps to reproduce

Import this file: [Cowboy_Female.blend.zip](https://github.com/godotengine/godot/files/11082286/Cowboy_Female.blend.zip)

### Minimal reproduction project

Trivial.

**Comment by Calinou** [comment]
This looks like a LOD generation issue. Can you reproduce it after disabling **Generate LODs** in the Import dock?

**Comment by sygi** [comment]
Thanks a lot for suggestions! Disabling LOD generation indeed helps. I'm closing this one as a duplicate of the ones @Calinou mentioned; it may be worth considering disabling LOD by default if fixing this is going to not be immediate.
