### ISSUE TITLE
C# Explicit Removal Of signal Handler Causes Error

### ISSUE THREAD

**Issue by silenuz** [godotengine/godot#75424]
### Godot version

v4.0.stable.mono.official [92bee43ad]

### System information

Linux, Windows

### Issue description

The documentation states:

> To provide more type-safety, Godot signals are also all available through [events](https://learn.microsoft.com/en-us/dotnet/csharp/events-overview). You can handle these events, as any other event, with the += and -= operators.

I had forgot that Godot automatically removes signal connections and out of habit disconnected all my event handlers in _ExitTree() including two signals from the EditorFileDialog.  However removing the event handlers for the signals results in the following errors:

```
ERROR: Disconnecting nonexistent signal 'dir_selected', callable: Delegate::Invoke.
   at: _disconnect (core/object/object.cpp:1331)
ERROR: Disconnecting nonexistent signal 'file_selected', callable: Delegate::Invoke.
   at: _disconnect (core/object/object.cpp:1331)
```

### Steps to reproduce

Create a scene, add a file dialog:
```

                fileDialog = new EditorFileDialog();
		fileDialog.Theme = editor.GetBaseControl().Theme;
		fileDialog.DirSelected += (path) => OnFolderSelected(path);
		fileDialog.FileSelected += path => OnFileSelected(path);
		fileDialog.InitialPosition = Window.WindowInitialPosition.CenterMainWindowScreen;
```

In _ExitTree() add the following:

```
                fileDialog.DirSelected -= OnFolderSelected;
		fileDialog.FileSelected -= OnFileSelected;
		fileDialog.Free();
```

When the file dialog is freed it raises the error.

### Minimal reproduction project

Can provide if really necessary the snippets above should reproduce the problem easily enough.  But I imagine this happens with all signals, so should be easily verified.

**Comment by AThousandShips** [comment]
Does this happen if you queue free?

**Comment by AThousandShips** [comment]
Also yes please do provide a project, while it might be easy it might not, and it helps people to investigate to not have to fiddle with setting everything up

**Comment by silenuz** [comment]
I recreated it with a simple Area2D, and have attached the project.  
[MinimalSignal.zip](https://github.com/godotengine/godot/files/11089735/MinimalSignal.zip)

Note when I run it in the Godot editor the error is never reported.  But it happens with my editor tool in the editor and with the attached project debug as player when I run it in an IDE.

![Screenshot_2023-03-28_09-15-02](https://user-images.githubusercontent.com/13521146/228248491-bc2a40f0-c184-4a1f-b205-c328169539ff.png)

To see the error when working in the Godot editor I have to start it in a terminal:

![Screenshot_2023-03-28_09-17-50](https://user-images.githubusercontent.com/13521146/228249576-87eb7836-6986-426f-824b-0244a62b0c31.png)

**Comment by RedworkDE** [comment]
You remove a callable that you never added, tho admittedly the error message is somewhat strange.

```cs
fileDialog.DirSelected += OnFolderSelected;
fileDialog.DirSelected -= OnFolderSelected;
```

works while

```cs
fileDialog.DirSelected += path => OnFolderSelected(path);
fileDialog.DirSelected -= OnFolderSelected;
```

doesn't because you add a lambda and then remove a method group.

(Also automatic removal of connections added with `+=` currently doesn't work)

**Comment by silenuz** [comment]
So it's just coincidence that when I add any signal handlers and remove them that I get this message?

It clearly states that the signal handler has already been removed.

If I comment the two removal lines the error goes away.

Try it with the attached project.  Error if run as is.  Remove the code in _ExitTree() and the error goes away.

**Comment by RedworkDE** [comment]
1. No
2. Error message is misleading, see my PR to improve it
3. Yes, I know
4. I did and the same thing happens there: `area.AreaExited += OnAreaExited;` and `area.AreaExited += area2D => OnAreaExited(area2D);` do mostly the same thing they have subtle difference that mean that you can disconnect signals connected by the first but not the latter.
5. Yes, that is what the docs say and how things are supposed to work, but that is not how things actually work currently see #73730 

(Question was edited while writing this so not 100% accurate anymore)

**Comment by silenuz** [comment]
Sorry about that I fixed things, and now no error.  I don't know how I missed the lambda in both, been fighting with the editor interface trying to create a plugin, and guess I'm starting to need a break, as I keep mixing code bases I keep making mistakes and not seeing them.

Sorry for wasting your time.
