### ISSUE TITLE
Popups close when hitting the Esc key, regardless of the input map

### ISSUE THREAD

**Issue by jbahamon** [godotengine/godot#75431]
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Windows 10

### Issue description

Currently, popups can be closed by using the Esc key. But this completely ignores the game's input map. IIRC popups used to have this closing behavior tied to the `ui_cancel` action, which I think made more sense. I'm guessing it's because of [this line](https://github.com/godotengine/godot/blob/1222d35cdd832b3d4dfd96722d746d312e69a9bb/scene/gui/popup.cpp#L39), as the Esc key is hardcoded there.

### Steps to reproduce

Create a Popup and open it. Even if the input map never references the Esc key, the popup can be closed by pressing the Esc key.

### Minimal reproduction project

N/A

**Comment by rypor** [comment]
Hi! I'm a first time contributor, may I be assigned to this issue?

**Comment by YuriSizov** [comment]
Does it need a discussion? Seems reasonable to have this respect the ui_cancel action.

**Comment by AThousandShips** [comment]
Oh sorry yes should be simple, wasn't sure if linking that was the preferred solution but it is reasonable
