### ISSUE TITLE
Changes in Inspector does not reflect properly for Scenes Collection inside TileMap

### ISSUE THREAD

**Issue by Efra-EMX** [godotengine/godot#75445]
### Godot version

v4.0.1.stable.official [cacf49999]

### System information

Windows 10

### Issue description

With Scenes Collection feature in TileMap, you can conveniently paint Scenes into the environment. Although these Scenes are not visible in the Scene dock, you can still select them via dragging in the viewport. Issues arise when you try to tamper with the Inspector of these Scenes (for example: modulate value, @export var in script, etc)
![image](https://user-images.githubusercontent.com/114894326/228426682-a6561613-2141-4c31-87a0-9910942ca21c.png)

In the minimal reproduction project, I've placed 4 identical playable characters by using Scenes Collection in TileMap

### 1. All changes in the inspector for these Scenes are not saved
In the editor, I try to set different colors for these character. However, these changes does not carry over when the project is run
![image](https://user-images.githubusercontent.com/114894326/228427934-ee769cf4-d597-42b9-8853-4ec5591821ed.png)
![image](https://user-images.githubusercontent.com/114894326/228428532-d106e0f6-8429-4c32-8854-3f965c8eb032.png)

In the editor, if I leave the current scene and reopen it again, all changes in the inspector will be reset and I occasionally get errors like this:
` editor/editor_data.cpp:1059 - Condition "!p_node->is_inside_tree()" is true.`

### 2. While the project is running, only 1 instance of the Scenes properly reflects the changes in the Inspector
While the project is running, if I select all 4 of these characters and turn them all into a different color in the editor, only 1 character will get their color changed in the game window
![image](https://user-images.githubusercontent.com/114894326/228430416-7288c7ed-74c7-45f8-b243-3e39942a250e.png)
![image](https://user-images.githubusercontent.com/114894326/228431070-7c7bc2a0-f495-4b12-9883-e5914ed187bb.png)
![image](https://user-images.githubusercontent.com/114894326/228431090-ca0ba89f-8cbf-428a-8d39-b6a121b3fa54.png)

### Steps to reproduce

1. Set up any scene you want to use in a tilemap and save it as .tscn
2. Create a new TileMap and a new TileSet
3. In the new TileSet, add a Scenes Collection and insert your Scene.tscn
4. Paint the Scene into the TileMap
5. Deselect the TileMap (press ESC)
6. In the viewport, click and drag to select any Scene inside the TileMap
7. Change any value in the Inspector of the selected Scene (preferably something visible)
8. Run the project. Your changes will not carry over in the game window (Bug 1)
9. Without stopping the project, go back to editor and select all identical Scenes in the TileMap
10. Change any values in the inspector for all selected scenes (preferably something visible)
11. Return to the game window. Only one object (or none) will properly reflect the changes you made (Bug 2)

### Minimal reproduction project

[TilemapSceneBug.zip](https://github.com/godotengine/godot/files/11096936/TilemapSceneBug.zip)

**Comment by KoBeWi** [comment]
I think this is the same issue as #69873
Scenes instantiated by TileMap are internal nodes and should not be selectable.
