### ISSUE TITLE
Picker tool does not appear in tileset paint mode when first selected

### ISSUE THREAD

**Issue by Proggle** [godotengine/godot#75448]
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Windows 10

### Issue description

The picker tool in the tileset 'paint' panel doesn't consistently appear.  The first time you open the 'paint' panel the picker does not exist.  Selecting a different property to paint (even if one is already selected) will cause the picker to appear.

### Steps to reproduce

click on the 'paint' tab of tileset.  The picker will not show up.

https://user-images.githubusercontent.com/89282845/228454981-1c7045f0-9ba3-4a71-8a25-aa5dc2abd59e.mp4

### Minimal reproduction project

any project will do this.

**Comment by KoBeWi** [comment]
Seems already fixed on master.

https://user-images.githubusercontent.com/2223172/228541627-26c0e410-216b-4d27-8215-4c8b608a837b.mp4

**Comment by AThousandShips** [comment]
This seems to have been a recurring bug #58407 and #71008, and has been fixed and then reappearing

**Comment by s9menine** [comment]
it's back in v4.0.2-stable again @KoBeWi 

https://user-images.githubusercontent.com/40716090/235468464-dd71a3bb-a839-4258-8e16-bb696939cb45.mp4
