### ISSUE TITLE
Shader Sampler2D Uniforms are always listed last in the Inspector

### ISSUE THREAD

**Issue by fracteed** [godotengine/godot#75454]
### Godot version

4.0 stable

### System information

Windows 10 960m

### Issue description

When creating sampler2d uniforms in a shader, they get listed at the bottom of the uniform group in the inspector. It is often useful to have them listed with related uniforms, so they should ideally follow the same order as listed in the shader code. For instance, albedo texture followed by the albedo color.

This example shows the standard 3d material converted to a shader with some small edits for readability. Note that the 3 sampler 2d uniforms are displayed at the bottom in the inspector and not in the shader order. However, they do display in the relative order that they appear in the shader code.

![sampler2d_order](https://user-images.githubusercontent.com/7741669/228479831-7ea0d9d5-d136-44a9-99f0-f9ce0c2fab52.jpg)

@Chaosus thanks for your fix on the alphabetical uniform group ordering! I thought it would be a good time to add this issue as the final obstacle to getting the perfect uniform ordering. Pretty sure this same issue also happened in 3.x and is a long standing problem.

### Steps to reproduce

- create a standard 3d material
- convert this material to a shader
- note that all of the uniform sample2d are listed at the bottom in the outliner

### Minimal reproduction project

[sampler2d_order.zip](https://github.com/godotengine/godot/files/11098493/sampler2d_order.zip)

**Comment by Chaosus** [comment]
I think this is intended, because sampler2D uniforms are indexed, 100000 after the common uniforms. And here I just copy-pasted the old code to make it works as before:

https://github.com/godotengine/godot/blob/23394bebed07e172f77601baedbd78fd4f423694/servers/rendering/renderer_rd/storage_rd/material_storage.cpp#L963-L976

cc @clayjohn -  what's the purpose of that comfortability, it was by your opinion?

**Comment by clayjohn** [comment]
@Chaosus I didn't add this code, nor have I worked on it much. 

If I had to guess I would say that reduz added it to allow for quickly parsing whether a given uniform is a texture or not. It is used in the ``is_parameter_texture()`` function:https://github.com/godotengine/godot/blob/6d7413be7447fa69ee6a10d410adb1060d003a2b/servers/rendering/renderer_rd/storage_rd/material_storage.cpp#L1025-L1026

We would have to ask @reduz what his rationale was when he wrote the code
