### ISSUE TITLE
MultiMeshInstance / Gridmap not working properly on some Android devices (Exynos CPU, Samsung S22 Series) 

### ISSUE THREAD

**Issue by hortopan** [godotengine/godot#75450]
### Godot version

3.5.2

### System information

Android 13, GLES2, SM-S901B

### Issue description

MultiMeshInstance and implicitly Gridmap (which I think uses multimeshinstance behind the scenes) do not work properly on some Android devices.

More specifically regardless of how many items are being placed only 1-2 end up being rendered / shown.

This seems to happen on all Samsung S22 series with Exynos soc:

"SM-S901B", "SM-S901B/DS", "SM-S908B", "SM-S908B/DS", "SM-S906B", "SM-S906B/DS"

<img width="880" alt="error" src="https://user-images.githubusercontent.com/917773/228462950-8aba2501-94c8-44a2-ba8e-3b82cae74e3d.png">

### Steps to reproduce

- Create GLES2 3D scene
- Add a Gridmap or multi mesh items with some items
- Try on any Samsung S22 series phone (plus, ultra, etc) with the Exynos soc.

### Minimal reproduction project

[testGodot.zip](https://github.com/godotengine/godot/files/11097822/testGodot.zip)

**Comment by hortopan** [comment]
Please note that CPUParticles are also broken as reported here on issue [#63261](https://github.com/godotengine/godot/issues/63261). So there seems to be multiple issues at hand here.

**Comment by lawnjelly** [comment]
Might also be a shader failing to compile due to use of unsupported `gl_FragDepth`.

**Comment by hortopan** [comment]
> Might also be a shader failing to compile due to use of unsupported `gl_FragDepth`.

It can be reproduced by using just a basic spatial material with an albedo color set.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/63261, as this is due to the same cause.
