### ISSUE TITLE
Can't connect to asset library on Windows 7 in 2.1 branch

### ISSUE THREAD

**Issue by eska014** [godotengine/godot#7545]
**Operating system or device - Godot version:**
Windows 7 x64

**Issue description** (what happened, and what was expected):
Trying to access the asset library fails, a blank panel is opened with an error message at the bottom:

> Can't connect to host: https://godotengine.org/asset-library/api

Same happens for 'Templates' in the project manager.

**Steps to reproduce:**
1. Open a project in Godot's editor
2. Open the asset library
3. Error message `Can't connect to host: https://godotengine.org/asset-library/api` appears at the bottom

ping @Faless maybe related to your cherry picks?

**Comment by Faless** [comment]
> ping @Faless maybe related to your cherry picks?

Definitely, I'll have a look at it today.

@eska014 can you try running godot from the command line and post the messages in the windows command prompt when you get the "can't connect message"?

**Comment by Faless** [comment]
I'm able to reproduce this, I'll start digging
