### ISSUE TITLE
Navigationbuttons on Tab Container wont Work

### ISSUE THREAD

**Issue by AshSamir** [godotengine/godot#7546]
**Operating system or device - Godot version:**
Windows - Godot 2.1.1 Stable 64

**Issue description** (what happened, and what was expected):

Tab Container right / left navigation buttons don't work.

**Steps to reproduce:**

i have 4 tabs, only 3 get displayed while the 3rd tab sticks out and is partly under the buttons.
i can only open the 3rd tab if i click on the area left of the buttons. the area beneath and right of them dont work.

here an image:
https://s27.postimg.org/g11yrijdv/Unbenannt.png

i gues it only checks for the area of the container. maybe this could be the reason the buttons wont work, because they are also outside.

**Comment by RayKoopa** [comment]
On top of that:
- The navigation buttons should not be outside the control bounds.
- 1 tab too much is drawn, which doesn't fit into the available width of the control anymore.
I look into this now
