### ISSUE TITLE
Error while building the solution.

### ISSUE THREAD

**Issue by kunal2604** [godotengine/godot#75474]
### Godot version

4.0, master

### System information

Windows 10 64 bit, 12GB RAM, NVIDIA GTX 1660Ti

### Issue description

I am using "pip" version 22.3 (from Python 3.11) 
and "scons" version  v4.4.0
 
I cloned this repository 2 days ago. Whenever I try to build the solution in Visual Studio 2022,  I get the following error:

"Error: Couldn't load project data at path "." Is the .pck file missing?
If you've renamed the executable, the associated .pck file should also be renamed to match the executable's name (without the extension)."

### Steps to reproduce

I just try to build the solution in Visual Studio (Local  Windows Debugger).

### Minimal reproduction project

N/A

**Comment by kunal2604** [comment]
I tried searching for solution for 2 days, but couldn't find any. Please help, I am new to Godot and I want to explore and debug features since I am very interested in game engines.

**Comment by AThousandShips** [comment]
This sounds like you're running the export template from the debugger, what target are you running?

**Comment by AThousandShips** [comment]
The template ones will indeed cause this if you try to run them instead of building them

**Comment by kunal2604** [comment]
@AThousandShips  Thanks, it worked with "editor".

Can you share any of your contact like telegram or email etc. I would like to connect just for few tips for a beginner.

**Comment by AThousandShips** [comment]
I don't give out my contact details nor do I offer any individual assistance, I don't do this for a living and I seek out issues and problems here that I'm able to help with or interested in
