### ISSUE TITLE
Editor dialogs now appear centered on the whole desktop instead of screen

### ISSUE THREAD

**Issue by RedworkDE** [godotengine/godot#75473]
### Godot version

v4.1.dev136.mono.custom_build [23394bebe]

### System information

Windows

### Issue description

Dialogs in the editor and project manager now appear centered on the whole desktop instead of centered on the current screen.
This is especially annoying with 2 screens where the new position usually in between the screens instead of at an area where one would focus on. Also it is probably possible to have setups where these dialogs now appear completely off-screen.

Expected:

https://user-images.githubusercontent.com/10944644/228656668-dd6ae1bf-a7dd-43a0-b667-3fa73eac5028.mp4

Actual:

https://user-images.githubusercontent.com/10944644/228654489-cb6619bf-9fa7-4e20-818a-f5890996a6c9.mp4

&nbsp;

- Regression from https://github.com/godotengine/godot/pull/75141, reverting it fixes the issue; cc: @rcorre

### Steps to reproduce

Open any dialog in project manager or editor, not sure if this change also extends to projects.

**Comment by YuriSizov** [comment]
I think I see the issue. We only check for `is_clamped_to_embedder`, but we don't check if we are actually embedded. That block in the `popup` method needs to also check for `get_embedder()` to be valid.
