### ISSUE TITLE
Controller events detected as InputEventKey when Steam is open (due to Steam Input event injection)

### ISSUE THREAD

**Issue by A-Totally-Normal-Name** [godotengine/godot#75480]
### Godot version

4.0, 4.0.1

### System information

Windows 10

### Issue description

If Steam is open on your computer, input from a controller can be incorrectly detected as an InputEventKey. Closing Steam corrects this error.

Controller inputs should never be detected as an InputEventKey: According to the current documentation an InputEventKey is [only for keyboard events.](https://docs.godotengine.org/en/4.0/classes/class_inputeventkey.html)

**Video demonstration:** https://youtu.be/9krmPx9vYoc
**Controller used:** Dualshock 4

### Steps to reproduce

1. Run minimal reproduction project (or a script with the following code):
```
func _input(event : InputEvent) -> void:
	if event is InputEventKey:
		print ("Keyboard Event Detected")
```
2. Test if "Keyboard Event Detected" prints on Controller input with Steam open vs. with Steam closed. 

### Minimal reproduction project

[InputEventKey Controller Test.zip](https://github.com/godotengine/godot/files/11106151/InputEventKey.Controller.Test.zip)

**Comment by Calinou** [comment]
This is most likely Steam Input injection doing its thing. Is there any way we could forcibly disable it for Godot by default?

**Comment by Calinou** [comment]
Quoting @Gramps from https://github.com/godotengine/godot/issues/75551#issuecomment-1494924000:

> The settings you're looking for are in the main Steam settings under Controller > General Controller Settings. If you turn off Configuration Support, you should start getting your inputs back.
