### ISSUE TITLE
Experiencing a bug in which the sprite stretches on some computers (in my case my friend's and my parent's PCs)

### ISSUE THREAD

**Issue by qwe3121** [godotengine/godot#75505]
### Godot version

4.0 stable

### System information

Windows 10 (both),  Vega 8 on first PC, RX 5700 XT on second (30.0.13025.1000 driver), Vulkan

### Issue description

buggy version (my friend's PC)
![image](https://user-images.githubusercontent.com/95754732/228944788-b1172ef8-cb9d-4ad3-9522-3544c20a1fff.png)
normal version (my PC, which is 1050 ti n Vulcan)
![image](https://user-images.githubusercontent.com/95754732/228944962-987444e8-84bf-42fc-a6f7-c0f67ca61e29.png)

### Steps to reproduce

Just run the project and check if its buggy. On my PC its not.

### Minimal reproduction project

[sprite_bug.zip](https://github.com/godotengine/godot/files/11115427/sprite_bug.zip)

**Comment by Calinou** [comment]
Your image is 20000×1500. This is bound to cause problems, as one of the dimensions is greater than 16384 pixels. Most GPUs don't support textures larger than 16384 pixels on either side correctly.
