### ISSUE TITLE
Project with "." (period) at the end of its name doesn't run from the editor on Windows (and logs/shader cache can't be written)

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#75516]
### Godot version

v4.0.1.stable.official [cacf49999]

### System information

Windows 11

### Issue description

Hi,

Running Godot 4.0.1 official on Windows 11 Pro 64Bit.
Projects with "."(periods) in their names do not run from Windows IDE?

Perhaps add a warning when naming projects so users don't use "." periods?

Jesse

### Steps to reproduce

Create "Hello World!' application and put a "." period in its name.
Then try to run app from within IDE on Windows 11.

### Minimal reproduction project

N.A.

**Comment by saierXP** [comment]
If the project name contains `.` at the end, can't run the project. Console prints error with `-v` arg.
```
ERROR: Could not create directory: user://logs
   at: (core/io/dir_access.cpp:180)
```

If the project is named **`Hello World!?.`**, you can run the project, but it prints an another error.

```
ERROR: Can't create shader cache folder, no shader caching will happen: user://
   at: RendererCompositorRD (servers/rendering/renderer_rd/renderer_compositor_rd.cpp:266)
```
OS:Windows10

**Comment by aidenninetynine** [comment]
This is caused by a limitation in Windows. Folders can't have a period in the name.

**Comment by Calinou** [comment]
> This is caused by a limitation in Windows. Folders can't have a period in the name.

This is not the case as of Windows 11 23H2:

https://github.com/godotengine/godot/assets/180032/4081a69a-6ba6-4f21-b6de-3f045c83d3f1

Windows 10 doesn't allow creating files/folders starting with `.` in Explorer, but it works from a command prompt.

**Comment by aidenninetynine** [comment]
Oh. Well, thanks for the correction. The issue does state that it happens when putting a period at the end.
