### ISSUE TITLE
Mesh with custom shader not render Godot 2.1.2-rc

### ISSUE THREAD

**Issue by marcosbitetti** [godotengine/godot#7551]
Some times (60% of times) when I run game from Godot 2.1.2-rc the mesh dissapear. It uses a custo shader.

![captura de tela de 2017-01-16 08-34-01](https://cloud.githubusercontent.com/assets/85936/21984553/922a980e-dbdd-11e6-91d4-fa191d032b3f.png)

OS: Linux Ubuntu Studio 16.04 - GeForce 560

Sometimes I note that pass VAR from vertex to fragment make shader fails, I don't know if it have relation.

**Comment by bojidar-bg** [comment]
@marcosbitetti Can you give us your shader, by any chance?

Also, that's probably fixed with the new renderer, but would be nice if someone ports to shader to the new syntax and tests.

**Comment by akien-mga** [comment]
If I understood correctly it's a regression, right? (i.e. it worked fine in 2.1.1-stable ?)

**Comment by akien-mga** [comment]
If it's a regression, it might be related to recent commits by @RandomShaper: 8589a1b, c44757c.

**Comment by RandomShaper** [comment]
Yes, please, post your shader code (vertex, fragment and lighting, if used) or at least a meaningful excerpt with declared uniforms.

**Comment by marcosbitetti** [comment]
Some considerations:
- Any light active, in this case I use a directional light (sun), provoque the issue! When I disable that light the object is rendered fine.
- I use a tresource to describe the material, but a shader file to define shader (file extensions help me)
- in light shader any atribuition to LIGHT variable provoke the issue

But the problem is not constant. because it, I suppose that is a problem when the script is loaded.

**Comment by RandomShaper** [comment]
That gives me some clues, but I'm still a bit out of light. :)

If you don't want to show your code, would you make a little test project with a similar setup reproducing issue?

Does that happen with the stable 2.1 version?

**Comment by marcosbitetti** [comment]
[scene.zip](https://github.com/godotengine/godot/files/711811/scene.zip)

**Comment by RandomShaper** [comment]
Thanks. I'll check it in a few hours.

**Comment by RandomShaper** [comment]
I'm sorry but I've not been able to reproduce your issue neither with stable 2.1 not with the current 2.1 branch.

I've tried both on Windows and Android.

**Comment by akien-mga** [comment]
I gave the test scene a try on Linux (Mageia 6 x64, latest kernel, mesa and all, with both Intel IGP [OpenGL 3.3] and Nvidia GPU [OpenGL 4.5]), and could not reproduce the bug either (at least by playing the scene).

**Comment by marcosbitetti** [comment]
I not totally certain, a lot of factors, as the project is inside a symlink... a lot o symlinks, can contribute to it. Or my file system is corrupt and the fdisk solve it on reboot... but the issue remains strange!
This not appears to occur in RC2.

**Comment by marcosbitetti** [comment]
The error stops on last release, and I not can reproduce it. I will close this issue, but I think that is a fail on file system (so much factors to experiment).
