### ISSUE TITLE
OS::get_free_static_memory not exposed to gdscript

### ISSUE THREAD

**Issue by SeleDreams** [godotengine/godot#75521]
### Godot version

4.1-dev

### System information

Windows 11 64-bit

### Issue description

Although the method exists in OS and can be implemented by platforms, this os function isn't accessible from gdscript while get_static_memory_usage and get_static_memory_peak_usage are.

### Steps to reproduce

create a gdscript script
try to access OS::get_free_static_memory()

### Minimal reproduction project

N/A

**Comment by SeleDreams** [comment]
I did implement it for the 3ds platform I'm working on but the fact it's
not exposed to gdscript makes the implementation unusable

**Comment by YuriSizov** [comment]
Sure, but the point is that it's not a usable method at the moment, so we can't expose it by default.

**Comment by AThousandShips** [comment]
If it's not functional but still gets exposed people will rightly complain, and how easily it can be implemented depends on the different platforms

**Comment by bruvzg** [comment]
The usefulness of this method is questionable, modern OSs have virtual memory and dynamic memory compression. So if it's implemented it probably should be multiple methods to get immediately allocatable memory size (w/o disk access and compression), generic global memory stats (physical mem. size, virtual mem. size), and app specific stats (system mem. usage, and which part of it is compressed / dumped to disk).
