### ISSUE TITLE
will godot 3 require OpenGl 3.3?

### ISSUE THREAD

**Issue by novemberist** [godotengine/godot#7552]
Trying to run the latest godot build from git, I get the following error message, followed by a segfault:

`WARNING: not found: display/window/allow_hidpi
ERROR: initialize: Could not obtain an OpenGL 3.3 context!
   At: platform/x11/context_gl_x11.cpp:160.
ERROR: initialize: Error initializing GLAD
   At: drivers/gles3/rasterizer_gles3.cpp:136.
[1]    16661 segmentation fault (core dumped)  godot
`
I run godot on an old laptop with an intel gpu that does only supports gl version 2.1. Can I assume that with the latest changes to the renderer, older hardware will not be supported anymore and godot will require at least OpenGl 3.3 or is this just a bug, that will be fixed in the future?

**Comment by neikeq** [comment]
The gles2.1 renderer will probably return for 3.1, from what I read weeks ago. But don't take my word for it.

**Comment by novemberist** [comment]
Too bad. Hopefully there will be a Godot 2.2 release or something similar, that will include all new features (visual and c# scripting) but with the old renderer, for people with older hardware that only want to use godot for 2d games anyway.

**Comment by eon-s** [comment]
@novemberist I'm sure I have read somewhere about GLES2 support on 3.1 but the only thing I could find here was [https://github.com/godotengine/godot/issues/6785#issuecomment-252892812](https://github.com/godotengine/godot/issues/6785#issuecomment-252892812)
But I don't know if that support will be for the editor or for exports only.

Regarding c#, I doubt it will get people who want to maintain it (2.x will only have like a year of life after 3 if plans for GLES2 support continue); 2.2 already has an usable visual scripting (and networking), even demos on demo project.

**Comment by akien-mga** [comment]
The current master branch, and the new GLES3 renderer for Godot 3.0 both require OpenGL 3.3 on desktop, and OpenGL ES 3.0 on mobile.

There is a plan to readd a GLES2 renderer at some time; it's not clear yet whether it will happen for Godot 3.0 or Godot 3.1.

> But I don't know if that support will be for the editor or for exports only.

It would be for both, as they use the exact same technology (export templates are the full Godot Engine, just without the editor), so it wouldn't really make sense to do it only for one of them.

The 2.1.x branch will be supported until that new GLES2 renderer is part of a stable release, to ensure that uses with limited hardware are not left behind.

The 2.2 branch is just provided for legacy and the few users who started using it for high level multiplayer. It does not contain C# support, and its VisualScript implementation is for testing only, as the compatibility will break in 3.0. There won't be a 2.2-stable release, and the 2.1.x branch will not have C# or Visual Scripting.

**Comment by DriNeo** [comment]
It will be useful to allow two Godot versions on the same machine, Godot 2.1 for mobile projects and 3.0 for PC projects. On Windows there always one editor settings folder.

**Comment by akien-mga** [comment]
> It will be useful to allow two Godot versions on the same machine, Godot 2.1 for mobile projects and 3.0 for PC projects. On Windows there always one editor settings folder.

That's supported already, Godot 3 writes its settings in a different file.

**Comment by akien-mga** [comment]
Closing as it's not an issue.
