### ISSUE TITLE
Glb import error

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#75525]
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Windows 10, 64bit

### Issue description

First, please run the reproduction project.
When I run the test scene, It report error like follow and app exited. 
![image](https://user-images.githubusercontent.com/35988767/229076194-f737bcb6-6c9b-4aa0-9bd5-3dbd36bc8d03.png)
And I don't know where was error.

### Steps to reproduce

1. Open the reproduction project.
2. Open scene 'user:\\xd\XActors\Weapon\Gun\Rifle\XRifle.tscn'
3. Assign the scene's Meshinstance's mesh with 'user:\\xd\XActors\Weapon\Gun\Rifle\XRifle01.res'
4. Run the scene
Opps, the scene exited.
![GIF](https://user-images.githubusercontent.com/35988767/229077075-4b18b9e0-933e-47f6-b6a8-0af966574884.gif)

### Minimal reproduction project

[GlbTest.zip](https://github.com/godotengine/godot/files/11120181/GlbTest.zip)

NOTE: The project that I provided was picked up from my owner project. Sorry I can't provide a minimal reproduction project because I don't know which step cause this issue. I was test like this:
Create a project, import the glb file, create meshinstance and assign mesh, but there was not error!

**Comment by CsloudX** [comment]
ADDTION: I was test again, found if save mesh file with `*.tres` instead `*.res`, where was no error.

**Comment by CsloudX** [comment]
Hello, I'm try debug and found maybe error occured in `ResourceLoaderBinary::open`.
![image](https://user-images.githubusercontent.com/35988767/232418980-2c0e06d2-9c28-4aa9-beab-1c5a49492fc1.png)
When open *Rifle.glb*, it's `external_resources` was *Rifle.glb* and *Refile02.res*.
IMO, It's should *Rifle01.res* and *Rifle02.res*.
Sorry I'm not familiar with godot's source and C++, but I wish this issue can resolve because it break my project.

**Comment by CsloudX** [comment]
![image](https://user-images.githubusercontent.com/35988767/232722555-61d14669-dc0f-4a14-8c9f-035c3d3a0f13.png)
And in `uid_cache.bin`, I found where not have `Rifle01.res`.

**Comment by CsloudX** [comment]
![image](https://user-images.githubusercontent.com/35988767/232722555-61d14669-dc0f-4a14-8c9f-035c3d3a0f13.png)
And in `uid_cache.bin`, I found where not have `Rifle01.res`.

**Comment by CsloudX** [comment]
![1](https://user-images.githubusercontent.com/35988767/233292610-e0d70ff4-4b00-4b25-a4c6-8387b8210bf9.PNG)
![222](https://user-images.githubusercontent.com/35988767/233292634-a41bb32a-35e9-4eb9-83c8-f742db540177.PNG)
Hi, I'm try debug again, and found `res://xd/XActors/Weapon/Gun/Rifle/Rifle.glb` and `res://xd/XActors/Weapon/Gun/Rifle/Rifle01.res` was return same `uid` in `EditorFileSystem::_scan_new_dir`.
I wish it can some help for resolve this issue.

**Comment by CsloudX** [comment]
Oh, I open `Rifle.glb.import` and delete line `uid="uid://<data>"`, then reopen project, everything woks well. (It will generate a another valid uid)
![image](https://user-images.githubusercontent.com/35988767/233304839-7d8c96ef-d19d-4dd5-bf08-a5ba4f495fd4.png)

**Comment by CsloudX** [comment]
Oh, I open `Rifle.glb.import` and delete line `uid="uid://<data>"`, then reopen project, everything woks well. (It will generate a another valid uid)
![image](https://user-images.githubusercontent.com/35988767/233304839-7d8c96ef-d19d-4dd5-bf08-a5ba4f495fd4.png)

**Comment by FilipLundby** [comment]
v4.1.stable.mono

I'm facing the same issue. It seem that every time the mesh is reimported, the MeshInstance3D loses it's reference to the *.res-file. So when the game is started errors are thrown:

```
E 0:00:00:0837   parse_variant: Can't load dependency: res://Vehicle1.glb.
  <C++ Error>    Method/function failed. Returning: error
  <C++ Source>   core/io/resource_format_binary.cpp:458 @ parse_variant()

E 0:00:00:0844   parse_variant: Error when trying to parse Variant.
  <C++ Error>    Condition "err" is true. Returning: ERR_FILE_CORRUPT
  <C++ Source>   core/io/resource_format_binary.cpp:502 @ parse_variant()

E 0:00:00:0851   parse_variant: Error when trying to parse Variant.
  <C++ Error>    Condition "err" is true. Returning: ERR_FILE_CORRUPT
  <C++ Source>   core/io/resource_format_binary.cpp:489 @ parse_variant()

E 0:00:00:0867   _load: Failed loading resource: res://.godot/imported/Vehicle1.glb-4d75147c5cfdb72f198826b41870917e.scn. Make sure resources have been imported by opening the project in the editor at least once.
  <C++ Error>    Condition "found" is true. Returning: Ref<Resource>()
  <C++ Source>   core/io/resource_loader.cpp:273 @ _load()

E 0:00:00:0879   _load: Failed loading resource: res://Vehicle1.glb. Make sure resources have been imported by opening the project in the editor at least once.
  <C++ Error>    Condition "found" is true. Returning: Ref<Resource>()
  <C++ Source>   core/io/resource_loader.cpp:273 @ _load()

E 0:00:00:0890   _parse_ext_resource: res://Main.tscn:8 - Parse Error: [ext_resource] referenced non-existent resource at: res://Vehicle1.glb
  <C++ Source>   scene/resources/resource_format_text.cpp:162 @ _parse_ext_resource()
```

**Minimal example**
[glb-mesh-import.zip](https://github.com/godotengine/godot/files/12052152/glb-mesh-import.zip)
