### ISSUE TITLE
Array[SubViewport] element value cannot be assigned

### ISSUE THREAD

**Issue by jzq740176597** [godotengine/godot#75520]
### Godot version

4.0.1.stable

### System information

window10,forward+

### Issue description

`@export var subviewports: Array[SubViewport] = []`

Array[SubViewport] 'element value **cannot be assigned** in inspector

### Steps to reproduce

1. create a foo gdscript
with line `@export var subviewports: Array[SubViewport] = []`
2. try add & drag SubViewport Node in scene to assign it

### Minimal reproduction project

*

**Comment by Zireael07** [comment]
*sigh*

Duplicate of *pinned* issue #62916

**Comment by YuriSizov** [comment]
Indeed, thanks.
