### ISSUE TITLE
C# Editor crash when opening a scene with a custom resource export

### ISSUE THREAD

**Issue by markdibarry** [godotengine/godot#75543]
### Godot version

4.0.dev (c29866dbc05694594b9be68b8d451816c7a0889d)

### System information

Windows 10

### Issue description

When saving a scene that has a custom resource as an export property, if you close and reopen the scene it will load correctly. If you close the project and reopen it, and try to open the scene the editor will crash, along with any subsequent attempts. The project runs correctly outside of the editor, though.

Of course, C# Resource Exports aren't supported as global classes in context menus currently, but using them at all shouldn't crash the editor.

### Steps to reproduce

Using the MRP:
1. Create a `Node2D` scene called `Foo.tscn`.
2. Attach `Foo.cs`.
3. Build and save the scene.
4. Close and reopen the scene (no issues)
5. Close the project, and reopen it.
6. Reopen the scene and the editor will crash.

### Minimal reproduction project

[ResourceCrashBug.zip](https://github.com/godotengine/godot/files/11127867/ResourceCrashBug.zip)

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/pull/72619.

**Comment by markdibarry** [comment]
So I was able to attach to the process as it crashes and got a little more information.

Someone more familiar please correct me where needed: There's no validation for a `Resource` in the editor, even if you specify the derived type in the script. As a matter of fact, it seems that if you specify the type in you script at all, the editor:
1. Can't figure out how to find its way home, trying to cast to the correct type from the serialized data
2. Crashes the editor
3. On subsequent attempts to load the project, it tries to load the same scene that crashed trying to load, effectively corrupting your project unless you discard your changes to the scene.

Because of this, you can only export a base `Resource` type, and not a custom type. The editor will somehow find the derived type, but you'll need to cast to the correct type any time you need it, which is definitely not ideal.

**Comment by RedworkDE** [comment]
The crash was another case of https://github.com/godotengine/godot/pull/77377

On 543750a1b3f5696f9ba8e91cb49dc7db05d2ae62 this now works without issues as long as `Bar` is marked as `[Tool]` and `[GlobalClass]`.

**Comment by markdibarry** [comment]
@RedworkDE I was more concerned that the project would still be corrupted if not marked as `[Tool]` or `[GlobalClass]` (wouldn't be fun for users unfamiliar with the new feature to discover), but I just tested the MRP and that doesn't seem to be the case any longer.

Closing as completed.
