### ISSUE TITLE
[4.01] TabContainer Self Modulate has no effect

### ISSUE THREAD

**Issue by ZodmanPerth** [godotengine/godot#75546]
### Godot version

v4.0.1.stable.official [cacf49999]

### System information

Windows 11 Home 22H2 22621.1413

### Issue description

In `Godot 3` when you applied a `Self Modulate` colour to the `TabContainer` it would affect the colour of the tabs but not the content.
In `Godot 4` when you applied a `Self Modulate` colour to the `TabContainer` it does nothing.
I am expecting the behaviour from `Godot 3`.

### Steps to reproduce

1. Add a `TabContainer` to a scene
1. Set the `Self Modulate` colour to another colour

Observe the colour of the `TabContainer` in the editor does not change colour.

### Minimal reproduction project

Not provided (repro steps are trivial)

**Comment by YuriSizov** [comment]
It worked like that before because TabContainer used to render its own tabbar, while contents of the tabs were separate controls, thus unaffected by "self modulate". In Godot 4 TabContainer uses a dedicated control for the tabbar, called TabBar (previously known as Tabs in Godot 3), so for the same reason it cannot be affected by "self modulate". There is no way around it other than using a script that looks up the TabBar node inside of TabContainer and applies to it a modulation.

**Comment by ZodmanPerth** [comment]
If that's the case, shouldn't the "self modulate" property by hidden in the inspector to avoid confusion?

**Comment by kleonc** [comment]
> If that's the case, shouldn't the "self modulate" property by hidden in the inspector to avoid confusion?

Hiding it in the inspector wouldn't avoid the confusion, it would just shift it. Users would instead get confused why there's no `self_modulate` if `TabContainer` derives from `CanvasItem`. Also you could still access it from the code etc.

---

I do agree it's confusing and needs to be somehow improved though. Not a bug as Yuri explained but can be better documented I think. Adding a note about potentially unaffected internal nodes in the description of `CanvasItem.self_modulate` should do the thing? :thinking:

**Comment by YuriSizov** [comment]
> Adding a note about potentially unaffected internal nodes in the description of CanvasItem.self_modulate should do the thing? 🤔

Sure, why not. There are multiple controls affected by this behavior, so it is probably worth a mention in a general description.

**Comment by ZodmanPerth** [comment]
I want to ensure we are talking about the same things.  In the picture I an talking about modifying the colour of the tab visuals of the TabContainer ("Lookup" and "Info" indicated with the arrow in the picture), not the TabBar child nodes:

![image](https://user-images.githubusercontent.com/546368/229319814-d12bc642-e11b-4366-87f9-1fbfa442834c.png)
<b>Godot 4 result</b>

In Godot 3 I could set the Self Modulate on the TabContainer to affect colour of these tab visuals.  For example, I could add a blue tint using Self Modulate, which would modulate the colour of the tab visuals of the TabContainer without affecting the colour of the Tabs child nodes:

![image](https://user-images.githubusercontent.com/546368/229319943-2a03d418-a3a8-4220-8af9-bbda610364cc.png)
<b>Self Modulate on the TabContainer</b>

This created the following result:

![image](https://user-images.githubusercontent.com/546368/229319932-9aabdae1-7799-4d3b-88ad-34e8afb37e25.png)
<b>Godot 3 result</b>

To achieve the same effect in Godot 4 I will likely have to theme the TabContainer because Self Modulate does nothing and Modulate affects the child nodes.  Theming isn't a sustainable way to colour the tab visuals of the TabContainer; what if I have many tabs with different colours?  I would need to create a theme for each one.

**Comment by YuriSizov** [comment]
> I want to ensure we are talking about the same things. In the picture I an talking about modifying the colour of the tab visuals of the TabContainer ("Lookup" and "Info" indicated with the arrow in the picture), not the TabBar child nodes

That is a TabBar child node. TabContainer, just like many other complex UI nodes in Godot, creates one implicitly. In Godot 3 this wasn't the case, but in Godot 4 it is. If you inspect the tree of a running scene, you will find the TabBar node we're talking about.

> Theming isn't a sustainable way to colour the tab visuals of the TabContainer; what if I have many tabs with different colours? I would need to create a theme for each one.

You can use [theme type variations](https://docs.godotengine.org/en/stable/tutorials/ui/gui_theme_type_variations.html) and manage everything from the same theme. You will have to duplicate the styleboxes, though.

**Comment by ZodmanPerth** [comment]
I see the implicit TabBar at runtime now, thanks.  I guess if I want to animate the Self Modulate of the tabs using I'll have to grab the implicit TabBar at runtime.

As a side note I find the TabBar control is confusing as it contains children as well, and those children don't show in the remote inspector.  The relationship between TabContainer and TabBar feels clumsy as a result.

Anyway I think I'm unblocked.  Thanks for your help.
