### ISSUE TITLE
SCREEN_PIXEL_SIZE not found

### ISSUE THREAD

**Issue by miunshine** [godotengine/godot#75541]
### Godot version

v4.0.1.stable.custom_build (sha256-0PDKZ92PJo9N5oP56/Z8bzhVhfO7IHdtQ5rMj5Difto=)

### System information

Nixos (nixos-unstable, nixpkgs-unstable) , NVIDIA GeForce RTX 2060

### Issue description

System info:
![bug4](https://user-images.githubusercontent.com/25178897/229243001-6804a536-6dc9-4464-a1b5-05ef76a05b79.png)

Trying to write a shader with SCREEN_PIXEL_SIZE and getting an error: 
![bug1](https://user-images.githubusercontent.com/25178897/229243191-c4404315-88fa-49ee-b279-d020f0387af8.png)

Was it changed in v4? 

Docs say it should be available:
![bugbug](https://user-images.githubusercontent.com/25178897/229244389-f48916f3-ab2c-4f4d-a7d0-ce9a0f5a255e.png)

https://docs.godotengine.org/en/stable/tutorials/shaders/shader_reference/canvas_item_shader.html

### Steps to reproduce

Add a shader material to a mesh instance and write a fragment shader using SCREEN_PIXEL_SIZE

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
You are looking at the wrong doc:
https://docs.godotengine.org/en/stable/tutorials/shaders/shader_reference/spatial_shader.html#fragment-built-ins
Your shader is `spatial` not `canvas_item`.

**Comment by Chaosus** [comment]
Yes, just change the `shader_type spatial` to `shader_type canvas_item` to make it work.
