### ISSUE TITLE
4.0.2 RC1 - Enabling Avoidance in NavigationAgent2D (3D) causes Godot to crash

### ISSUE THREAD

**Issue by MrDixioner** [godotengine/godot#75558]
### Godot version

4.0.2 RC1

### System information

Windows 10, nVidia GT1030, Compatibility mode in Godot

### Issue description

Enabling the **Avoidance Enabled** setting causes Godot to crash and close. This error is repeated both in the 2D scene and in 3D. There are no errors in the console. 

### Steps to reproduce

- Create a new scene
- Create a **CharacterBody2D/3D** node
- Create a child node **NavigationAgent2D/3D**
- In the settings of this node, in the **Avoidance** section, enable the **Avoidance Enabled** option.

### Minimal reproduction project

The project is not required.

**Comment by akien-mga** [comment]
CC @smix8

**Comment by AThousandShips** [comment]
Can confirm on current `master`

**Comment by AThousandShips** [comment]
Looks like a regression from #74893
