### ISSUE TITLE
Project manager segfaults when creating a new project

### ISSUE THREAD

**Issue by karroffel** [godotengine/godot#7555]
**Operating system or device - Godot version:**
Arch Linux 64 Bit, current master

**Issue description** (what happened, and what was expected):
I can't create a new project in the project manager. `touch`ing a new `engine.cfg` and importing that works fine.
```
ERROR: operator[]: Condition ' p_index<0 || p_index>=size() ' is true. returned: aux
   At: core/vector.h:145.
Segmentation fault (core dumped)
```

**Steps to reproduce:**
Try to create a new project in the project manager.

**Link to minimal example project** (optional but very welcome):
what project? :^)

**Comment by volzhs** [comment]
I can reproduce it. :)
