### ISSUE TITLE
Image texture looks washed out when used in sky shader

### ISSUE THREAD

**Issue by sebastianrueckerai** [godotengine/godot#75556]
### Godot version

4.0.1 stable

### System information

Windows 10, NVIDIA 2080, Vulkan

### Issue description

I have a png I want to use as a sky texture in a shader. 
If I use it in Panorama sky, it looks fine. 

If I use it  in a sky shader it looks washed out (see pics).

Code for the shader:

```glsl
shader_type sky;

uniform sampler2D img;

void sky() {
    vec2 uv = SKY_COORDS;
    vec4 img_tex = texture(img, SKY_COORDS);
    COLOR = img_tex.rgb;    
}
```

![inShader](https://user-images.githubusercontent.com/83586913/229276226-3506479e-bf0d-468f-977c-1a91f7252f52.png)
![Panorama](https://user-images.githubusercontent.com/83586913/229276229-f1fd7c1d-9f56-47b7-b887-18e010b58ad0.png)

### Steps to reproduce

clone and run this project:

https://github.com/sebastianrueckerai/GodotSkyBug

You can switch the sky material in the world environment between `SkyImagePanorama.tres` and `SkyImageShader.tres` and you will see that they look different.

### Minimal reproduction project

https://github.com/sebastianrueckerai/GodotSkyBug

**Comment by Calinou** [comment]
PS: Code blocks should use triple backticks like this (with an optional language name for syntax highlighting):

\`\`\`glsl
code here
\`\`\`

I edited your post accordingly, but remember to do this in the future :slightly_smiling_face:

**Comment by sebastianrueckerai** [comment]
Thanks, awesome! :)

I thought this might be the case but I only tried all the type hints beginning with "hint". Are the hints for shader variables documented somewhere?

**Comment by Calinou** [comment]
> I thought this might be the case but I only tried all the type hints beginning with "hint". Are the hints for shader variables documented somewhere?

Yes: https://docs.godotengine.org/en/latest/tutorials/shaders/shader_reference/shading_language.html#uniforms
