### ISSUE TITLE
Failure to load .NET runtime on MacOS on first install

### ISSUE THREAD

**Issue by punkscience** [godotengine/godot#75561]
### Godot version

v4.0.1.stable.mono.official [cacf49999]

### System information

MacOS Big Sur, MacBook Pro Retina 15"

### Issue description

On first install and launch, the C# version of Godot shows an error saying .NET cannot be found and directing the user to install the .NET runtime from somewhere. 

Expected Behaviour: Any dependency of Godot should be installed by or with Godot without asking the user to back-pedal and meet prerequisites depending on other projects. 

<img width="706" alt="image" src="https://user-images.githubusercontent.com/204191/229290408-e0635cf4-ea5e-4c5d-b4b9-3f015c8dd3a4.png">

### Steps to reproduce

- Install the C# build of Godot on a vanilla Macbook Pro that doesn't previously have any .NET products.
- Launch

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
From the documentation:

> However, Godot does not bundle the tools required to build and compile games, such as MSBuild and the C# compiler. These are included in the .NET SDK, and need to be installed separately.
> 
> In summary, you must have installed the .NET SDK and the .NET-enabled version of Godot.

**Comment by AThousandShips** [comment]
The need to download it is also clear on the download page of Godot:
> Additional requirements for the .NET version:
> * .NET SDK

**Comment by Calinou** [comment]
Closing, as feature proposals should be discussed on the [Godot proposals](https://github.com/godotengine/godot-proposals) repository. This repository is now used for bug reports only.

Make sure to follow the proposal template when opening a new proposal – don't just copy and paste the text you wrote in this issue.
