### ISSUE TITLE
Build system: cleaning Visual Studio solution does not erase .pdb, .ilk, .lib files

### ISSUE THREAD

**Issue by anvilfolk** [godotengine/godot#75570]
### Godot version

master

### System information

Windows 11, VS2022

### Issue description

I use the following command to generate a Visual Studio 2022 solution.

`scons vsproj=true dev_mode=true dev_build=true target=editor tests=true`

All my compilation is done through VS2022. I semi-regularly clean out the solution and rebuild from scratch:

![image](https://user-images.githubusercontent.com/1133892/229303992-af428c74-e83e-4c08-9749-39a99a8e13a4.png)

This process removes all the `.obj` files, but unfortunately does not remove the `.pdb.`, `.ilk`, and `.lib` files. Particularly, this causes `.pdb` files to bloat. I've had them as large as 2.5gb.

![image](https://user-images.githubusercontent.com/1133892/229303976-03cc33f1-8f31-4d21-8436-6371cf924a79.png)

By comparison, this is the same folder after manually deleting the files above and recompiling from scratch:

![image](https://user-images.githubusercontent.com/1133892/229304085-c5c98195-2fd9-4f1c-b138-9af526aa1700.png)

Arguably the files generated by having debug symbols should be cleaned out as well when cleaning/rebuilding solution. I'm sure this is platform and build-toolchain dependent, but each toolchain/platform combo can be addressed in separate PRs.

### Steps to reproduce

See above.

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
Fixed by #85197.
