### ISSUE TITLE
_get_configuration_warning not working

### ISSUE THREAD

**Issue by MacdonaldRobinson** [godotengine/godot#75573]
### Godot version

4.0.1

### System information

Windows 10, Compatibility

### Issue description

_get_configuration_warning() does not work

![image](https://user-images.githubusercontent.com/18366446/229307946-9ab1de45-446a-4eed-825c-1e836f7d1dbb.png)

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
It's `_get_configuration_warnings()`.

**Comment by Calinou** [comment]
For reference, Godot 3.x uses `_get_configuration_warning()` (returns String) while 4.x uses `_get_configuration_warnings()` (returns an array of Strings).

**Comment by MacdonaldRobinson** [comment]
I just tried the _get_configuration_warnings() and still no luck

![image](https://user-images.githubusercontent.com/18366446/229324203-77e403db-ab07-416d-952b-ef318ffe92d7.png)

**Comment by AThousandShips** [comment]
What happens if you call `update_configuration_warnings` in `_ready`

**Comment by AThousandShips** [comment]
You need to reload the scene for it to take effect, and use `update_configuration_warnings` when ever they are supposed to change (if a property changes)

**Comment by KoBeWi** [comment]
The documentation already says that.

I added an example, see the PR above.

**Comment by MacdonaldRobinson** [comment]
Hi @KoBeWi Thank so much for your help.

I managed to get it to work, looks like if you have inheritance setup and you add the @tool and the _get_configuration_warnings() at the top most level,  you need to add @tool to all the child classes as well or it wont work, it might not propagate all the way up the tree

Also having to close the scene and reopen it doesn't seem like a very good user experience, would be nice to get instant feedback, but that's a nice to have.

Thanks again!

**Comment by Zireael07** [comment]
>  @tool to all the child classes as well or it wont work

Yes, tool isn't inherited, by design IIRC
