### ISSUE TITLE
Godot 4.0 don't support debug on VSCODE

### ISSUE THREAD

**Issue by newjbl** [godotengine/godot#75588]
### Godot version

4.0 stable

### System information

windows 10

### Issue description

i install godot-tools on vscode, and configure follow the guidance to debug gdscripts by vscode. 
it is can work on godot 3, but when work with godot 4.0, i can setup the godot by vscode, but it will not stoped at the breakpoint.

### Steps to reproduce

Godot side
1. Open the Editor Settings
2. Select Text Editor > External
3. Make sure the Use External Editor box is checked
4. Fill Exec Path with the path to your VS Code executable
5. Fill Exec Flags with {project} --goto {file}:{line}:{col}

VS Code side
1. Open the command palette:
2. >Debug: Open launch.json
3. Select the Debug Godot configuration.

4. Press F5 to launch.

### Minimal reproduction project

any project with gdscripts can be reproducted.

**Comment by DillonSteyl** [comment]
This would be an issue with `godot-tools` extension, not godot itself. Seems like this issue has already been raised on their repo:
https://github.com/godotengine/godot-vscode-plugin/issues/460

**Comment by KoBeWi** [comment]
Closing per above comment.

**Comment by newjbl** [comment]
> This would be an issue with `godot-tools` extension, not godot itself. Seems like this issue has already been raised on their repo: [godotengine/godot-vscode-plugin#460](https://github.com/godotengine/godot-vscode-plugin/issues/460)

i don't think so. because by adding "debugServer": 6006, this issue can be solved, and i have reply before i report this issue. so i don't sure it is buf of godot 4.0, or bug of godot-tools

![image](https://user-images.githubusercontent.com/30258466/230701084-e355ae91-d88a-44cc-898a-178c59bd5d46.png)

**Comment by newjbl** [comment]
> 
i don't think so. because by adding "debugServer": 6006, this issue can be solved, and i have reply before i report this issue. so i don't sure it is buf of godot 4.0, or bug of godot-tools

![image](https://user-images.githubusercontent.com/30258466/230701160-b10cd706-4187-4e2b-976e-403e8ff283c0.png)

so, please help double check if it is bug of Godot 4.0.  thanks a lot.

**Comment by Calinou** [comment]
Please continue the discussion in https://github.com/godotengine/godot-vscode-plugin/issues/389.
