### ISSUE TITLE
Changing keyboard layout breaks the gdscript editor

### ISSUE THREAD

**Issue by PurplFish** [godotengine/godot#75580]
### Godot version

v4.0.1.stable.official [cacf49999]

### System information

Windows 10

### Issue description

When switching keyboard language in windows using windows + spacebar, you won't be able to move left or right in the gdscript editor nor do backspaces or move in any direction.

### Steps to reproduce

Launch any godot project
Go in the text editor
switch keyboard langyage using windows + spacebar
try moving using arrow key or backspace it won't work

### Minimal reproduction project

[keyboard_issue.zip](https://github.com/godotengine/godot/files/11130814/keyboard_issue.zip)

**Comment by omarzoghayyer** [comment]
I'm unable to repro using the provided project. Can you kindly share a video of the issue?

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/49771.

**Comment by Kianakiferi** [comment]
Me too, but it's more serious, many function keys are invalid 😥😥 like: 
- Ctrl+C, Ctrl+V to copy and paste, 
- F2 to rename
- ...

**Comment by Zireael07** [comment]
@Calinou literally linked an rc above that should have this bug fixed.

**Comment by Kianakiferi** [comment]
> @Calinou literally linked an rc above that should have this bug fixed.

Thank you for your reply. I just noticed that 4.0.2 was released 3 hours ago, and I have downloaded and used it without further problems.
Thanks for your hard work and contribution!😊

**Comment by Zireael07** [comment]
O_o didn't know 4.0.2 itself was already out
