### ISSUE TITLE
TileSet UI error preventing Paint Properties: Physics, Navigation and Custom Data from being selected

### ISSUE THREAD

**Issue by SeremTitus** [godotengine/godot#75592]
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Intel - Intel(R) HD Graphics 4000 

### Issue description

While in the TileSet Panel then Paint gizmo, you can not successfully select  Paint Properties: Physics, Navigation and Custom Data

https://user-images.githubusercontent.com/58259212/229351648-57525223-ec85-47c2-847e-0a364f22a166.mp4

### Steps to reproduce

1.  Create a new scene with root node type : Node2D
2. Add child node type : TileMap
3.  set TileMap node properly tile_set to New TileSet
4.  Go to the TileSet Panel add a tileset artwork
5. On the new artwork click on paint gizmo 
6.  Then Paint Properties select  Physics or Navigation or Custom Data

### Minimal reproduction project

[tileset-Godotv4.0.stable.official.zip](https://github.com/godotengine/godot/files/11132093/tileset-Godotv4.0.stable.official.zip)

**Comment by SeremTitus** [comment]
Render setting is: Compatibility

**Comment by KoBeWi** [comment]
You need to create physics/navigation/custom data layers in the inspector first.

**Comment by SeremTitus** [comment]
@KoBeWi , you are right hopefully the UI/UX might be improved more to make it intuitive
