### ISSUE TITLE
native Type ERROR

### ISSUE THREAD

**Issue by walidsantos** [godotengine/godot#75639]
### Godot version

4.0.1.stable

### System information

Windows 10,  Intel(R)HD Graphics Family, 20.19.15.5171,  GLES3

### Issue description

Script inherits from native type 'Button', so it can't be assigned to an object of type: 'TextureButton'

### Steps to reproduce

![image](https://user-images.githubusercontent.com/53328867/229701701-930cee7f-49ed-4a84-8da8-a8ee4df316c7.png)

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
This is how the script system works, it's not a bug, the script has to inherit from TextureButton

**Comment by AThousandShips** [comment]
Please in the future check with the other [community channels](https://godotengine.org/community) before opening an issue here, this is for bugs in the engine and not a help forum, and you would most likely have been informed of this error there!
