### ISSUE TITLE
[GodotPhysics] RigidBody3D Objects Overlapping

### ISSUE THREAD

**Issue by Malcolmnixon** [godotengine/godot#75634]
### Godot version

4.0.2 RC.2

### System information

Windows 11, Vulkan Mobile, NVidia RTX 3070 TI

### Issue description

RigidBody3D Objects overlap when sitting on top of each other.
![image](https://user-images.githubusercontent.com/1863707/229661553-b88af6a4-a5a9-49e4-a47c-f9550a844e98.png)

This has actually been around since Godot 3 using built-in physics:
![image](https://user-images.githubusercontent.com/1863707/229661469-78ee0f19-27eb-4b8a-821c-b15dc200a354.png)
![image](https://user-images.githubusercontent.com/1863707/229661476-0692a629-3bad-4419-8e18-bfdcca4fbc1f.png)

### Steps to reproduce

Create pretty much any RigidBody3D objects stacked on top of each other - or on top of some StaticBody3D objects, and the RigidBody3D objects will overlap each other and into the static bodies.

A demo project is attached with a special material on the RigidBody3D meshes which shows which parts of them have overlapped into the StaticBody3D meshes of the scene.
![image](https://user-images.githubusercontent.com/1863707/229661941-5bf47bac-1bb1-4437-aec5-34d5939e5ca6.png)

### Minimal reproduction project

[RigidBodyOverlap.zip](https://github.com/godotengine/godot/files/11143760/RigidBodyOverlap.zip)

**Comment by rburing** [comment]
Based on the textures I thought the cubes were bigger, but I see they are `0.1 x 0.1 x 0.1`, and the checkerboard pattern texture on a face has `32 x 32` squares, and the penetration seems to be about `3` squares, so that's about `(3/32) * 0.1 = 0.009375` units of penetration. The project setting `physics/3d/solver/contact_max_allowed_penetration` defaults to `0.01`, so the penetration is within expectations.

**Comment by Malcolmnixon** [comment]
I confirmed the workaround of manually setting the penetration distance to 0.001 in the project results in reasonably good behavior (https://www.youtube.com/watch?v=hyyyuAl5SMI). No jitters occurred in my basic tests - although jitters have been observed even with the default 0.01 value, so I assume this would have the same or possibly higher occurrence.

**Comment by Calinou** [comment]
Adding `documentation` label, as we should have a physics troubleshooting page in the documentaion covering common issues such as tunnelling, overlapping rigid shapes, etc.
