### ISSUE TITLE
unable to set anim_player propert of AnimationTree node during runtime

### ISSUE THREAD

**Issue by TomerconDevelopers** [godotengine/godot#75649]
### Godot version

4.0.2 rc1

### System information

system: windows 10, ryzen 6 3600, rx 590, 16gb RAM, android device: OPPO A57, CPH2387, android version 12

### Issue description

I want to set animation player property of animation tree node during runtime.
The code is:
![image](https://user-images.githubusercontent.com/62302722/229839666-c6aa0b57-fb2b-4acf-8ee5-7c4b7e51b06b.png)

producing this error:
![image](https://user-images.githubusercontent.com/62302722/229839842-5901629d-4f33-4bda-9fda-275e4e6d2371.png)

### Steps to reproduce

none

### Minimal reproduction project

none

**Comment by and-rad** [comment]
`anim_player` is of type `NodePath`, `maleAnim` is of type `AnimationPlayer`, so `Node`, not `NodePath`. Have you tried passing in `maleAnim`'s path instead?

**Comment by TokageItLab** [comment]
Right on with the above comment.
