### ISSUE TITLE
Accessing scene unique nodes in a static function from a different node causes error instead of returning null

### ISSUE THREAD

**Issue by bend-n** [godotengine/godot#75645]
### Godot version

ef025711a

### System information

ArchLinux x11

### Issue description

Accessing a scene unique node like this:
```gdscript
class_name Class extends Node
static func get_label() -> Label:
	return %label
```
and then accessing that class later:
```gdscript
func _ready() -> void:
	Main.get_label().text = "hello world"
```
causes a strange error when in the editor, and a normal error when run directly.
![image](https://user-images.githubusercontent.com/70787919/229785642-6aad4e31-6bd9-4eb5-bee4-7445b48a99bb.png)
```c++
ERROR: Node not found: "%label" (relative to "/root/main").
   at: get_node (scene/main/node.cpp:1364)
```
Instead of returning null.
As opposed to when using `get_node`:
```

SCRIPT ERROR: Cannot call method 'get_node' on a null value.
          at: get_label (res://main.gd:5)
SCRIPT ERROR: Invalid set index 'text' (on base: 'Nil') with value of type 'String'.
          at: _ready (res://control.gd:4)
```

### Steps to reproduce

Run mrp or follow outlined steps

### Minimal reproduction project

[bug.zip](https://github.com/godotengine/godot/files/11148287/bug.zip)

**Comment by KoBeWi** [comment]
The error should be something like this:
![image](https://user-images.githubusercontent.com/2223172/229799520-f3896f19-9202-48dc-9be8-e36f9e0058e6.png)
Seems like `%` and `$` are not handled properly in static methods.
