### ISSUE TITLE
Mouse cursor disappears if frame duration is changed while animation is playing in AnimatedSprite2D

### ISSUE THREAD

**Issue by natalmi7** [godotengine/godot#75652]
### Godot version

4.0.2 (Stable)

### System information

Windows 10

### Issue description

If you try to manually change the frame duration of a frame while the animation is playing in an AnimatedSprite2D node, the mouse will become unusable. Noticed it only happens if you try to highlight the value without first clicking inside the frame duration field. Maybe it has something to do with the multiplication operator being there before you click in it?

### Steps to reproduce

1. Open the attached project.
2. Open the planet.tscn scene and click on the planet node.

![image](https://user-images.githubusercontent.com/69772645/229880141-daf1c7be-2bf5-494f-9a3b-f316251eff8d.png)

3. Click play on the animation frames

![image](https://user-images.githubusercontent.com/69772645/229873729-174a26ce-496c-4f64-abcb-6d35dc6ef56a.png)

4. Change the frame duration to 1.1 using the up arrow.

![image](https://user-images.githubusercontent.com/69772645/229874173-e46d876b-562e-407a-983d-0595c906d873.png)

5. Using your mouse, highlight the value in frame duration (as if you were to manually change and enter a new value).

![image](https://user-images.githubusercontent.com/69772645/229875183-cf504e0e-c7eb-4b38-9d04-24ba73d240cd.png)

This should make your mouse cursor disappear and essentially make your mouse unusable until you restart the app.

### Minimal reproduction project

[project.zip](https://github.com/godotengine/godot/files/11151183/project.zip)

**Comment by dalexeev** [comment]
Can't reproduce this on Linux (KDE). The SpriteFrames plugin does not change the mouse cursor, perhaps the reason is in `SpinBox` or `LineEdit`.

**Comment by natalmi7** [comment]
Closing it. After being able to reproduce so many times, I can't reproduce it anymore; don't know what changed. Apologize for wasting your time @dalexeev .
