### ISSUE TITLE
Segfault at thirdparty/astcenc/astcenc_color_quantize.cpp

### ISSUE THREAD

**Issue by erikbgithub** [godotengine/godot#75650]
### Godot version

ada406f2f5

### System information

Fedora 38 (Workstation Edition Prerelease)

### Issue description

```
 ...
[Initial build] Compiling thirdparty/astcenc/astcenc_block_sizes.cpp ...
[Initial build] Compiling modules/vorbis/register_types.cpp ...
[Initial build] Compiling modules/vorbis/resource_importer_ogg_vorbis.cpp ...
[Initial build] Compiling modules/vorbis/audio_stream_ogg_vorbis.cpp ...
[Initial build] Compiling thirdparty/astcenc/astcenc_color_quantize.cpp ...
cc1plus: internal compiler error: Segmentation fault
Please submit a full bug report, with preprocessed source.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
The bug is not reproducible, so it is likely a hardware or OS problem.
scons: *** [main/main.linuxbsd.editor.x86_64.o] Error 1
scons: building terminated because of errors.
[Time elapsed: 00:00:42.609]
```

### Steps to reproduce

 1. Relatively fresh Fedora beta install
 2. update
 3. `sudo dnf groupinstall c-development`
 4. git clone this repo
 5. `scons platform=linuxbsd`

### Minimal reproduction project

.

**Comment by Calinou** [comment]
This link works for me: https://bugzilla.redhat.com/

This is an internal compiler error, so you should report it there instead. We don't maintain C/C++ compilers :slightly_smiling_face:
