### ISSUE TITLE
C# Report 

### ISSUE THREAD

**Issue by walidsantos** [godotengine/godot#75667]
### Godot version

4.0.2

### System information

Windows 10,  Intel(R)HD Graphics Family, 20.19.15.5171,  GLES3

### Issue description

I Can't access godot class 

### Steps to reproduce

I get this error in output

Received response for /v2/getcodeactions but could not find request

### Minimal reproduction project

N/A

**Comment by walidsantos** [comment]
Solved the issue by following this steps
https://www.reddit.com/r/godot/comments/g72hoi/print_to_the_output_in_c/

**Comment by walidsantos** [comment]
Solved it!

**Comment by AThousandShips** [comment]
In the future please consult the other [community channels](https://godotengine.org/community) before opening an issue here if you haven't got a very clear issue, it's likely someone can help you there and this is for bugs in the engine and needs more clear details
