### ISSUE TITLE
Type Error was thrown when using vsproj=yes tag with VS 2022 Preview

### ISSUE THREAD

**Issue by CodingDogzxg** [godotengine/godot#75671]
### Godot version

master branch

### System information

Windows 11 i5-8400 GTX1060 6G

### Issue description

![屏幕截图 2023-04-05 112301](https://user-images.githubusercontent.com/49633098/229975024-c8387b53-d369-4118-b8bd-328fc7330382.png)
It worked fine without the "vsproj=yes" tag

### Steps to reproduce

>>scons p=windows vsproj=yes
>>scons: Reading SConscript files ...
Auto-detected 6 CPU cores available for build parallelism. Using 5 cores by default. You can override it with the -j argument.
Using MinGW, arch x86_64
Building for platform "windows", architecture "x86_64", target "editor".
TypeError: 'NoneType' object is not iterable:
  File "F:\Github Repos\Godot\SConstruct", line 927:
    methods.generate_vs_project(env, GetOption("num_jobs"), env["vsproj_name"])
  File "methods.py", line 736:
    batch_file = find_visual_c_batch_file(env)
  File "methods.py", line 684:
    (host_platform, target_platform, _) = get_host_target(env, version)
  File "D:\Python3.9\lib\site-packages\SCons\Tool\MSCommon\vc.py", line 460:
    vernum = float(get_msvc_version_numeric(msvc_version))
  File "D:\Python3.9\lib\site-packages\SCons\Tool\MSCommon\vc.py", line 426:
    return ''.join([x for x in msvc_version if x in string_digits + '.'])

### Minimal reproduction project

N/A

**Comment by CodingDogzxg** [comment]
It seems like the Visual Studio 2022 Preview is incompatible with Scons. This problem will be solved if we reinstall Visual Studio 2022(not preview version) and rerun the command. And what's more, the latest version of Scons may have this issue: https://github.com/godotengine/godot/issues/74725 we'd better install Scons 4.4.0.

**Comment by CodingDogzxg** [comment]
After building once successfully, I found another reason that may cause this problem. If this error shows again, check if you have modified this directory (the second line, download cache):
![image](https://user-images.githubusercontent.com/49633098/230085722-b6aeac9b-a070-418c-99f6-5ad0de3f135c.png)
Make sure you do not modify its containing or change the folder's name in any case.

**Comment by Klaim** [comment]
I hit the same issue even in non-preview version.
I initially hit that issue with msvc-preview, then uninstalled msvc-preview, checked that the whole directory was removed from the system. Then I deleted all build artefact and cache I could find (maybe not all, not sure) and re-launched the command -> still failing.
I proceed to build the project without `vsproj=yes` and it does work as expected with and without msvc-preview installed.
Now I have no msvc-preview and still hit that issue (after building successfully the whole thing)

Exact log I get:
```
$ scons platform=windows deb_build=yes vsproj=yes
scons: Reading SConscript files ...
Auto-detected 24 CPU cores available for build parallelism. Using 23 cores by default. You can override it with the -j argument.
Configuring for Windows: target=debug, bits=default
Found MSVC version 14.3, arch amd64, bits=64
Note: Building a debug binary (which will run slowly). Use `target=release_debug` to build an optimized release binary.
TypeError: can only concatenate deque (not "list") to deque:
  File "E:\tools\godot\sources\godot\SConstruct", line 741:
    methods.generate_vs_project(env, GetOption("num_jobs"))
  File "E:\tools\godot\sources\godot\methods.py", line 875:
    module_configs = ModuleConfigs()
  File "E:\tools\godot\sources\godot\methods.py", line 790:
    self.add_mode()  # default
  File "E:\tools\godot\sources\godot\methods.py", line 813:
    self.arg_dict["cppdefines"] += ModuleConfigs.for_every_variant(env["CPPDEFINES"] + defines)
```

I didnt change any path locations (neither cache or install) of the visual studio installed.

Note that I'm trying to build branch `3.x`, not sure if it changes something.

Any other idea?

**Comment by CodingDogzxg** [comment]
> 

What is the version of your Scons? Is it the latest? I might have seen an alike issue on GitHub, it seems like something to do with the version of Scons, 4.4.0 is recommended.

**Comment by CodingDogzxg** [comment]
> I hit the same issue even in non-preview version. I initially hit that issue with msvc-preview, then uninstalled msvc-preview, checked that the whole directory was removed from the system. Then I deleted all build artefact and cache I could find (maybe not all, not sure) and re-launched the command -> still failing. I proceed to build the project without `vsproj=yes` and it does work as expected with and without msvc-preview installed. Now I have no msvc-preview and still hit that issue (after building successfully the whole thing)
> 
> Exact log I get:
> 
> ```
> $ scons platform=windows dev_build=yes vsproj=yes
> scons: Reading SConscript files ...
> Auto-detected 24 CPU cores available for build parallelism. Using 23 cores by default. You can override it with the -j argument.
> Configuring for Windows: target=debug, bits=default
> Found MSVC version 14.3, arch amd64, bits=64
> Note: Building a debug binary (which will run slowly). Use `target=release_debug` to build an optimized release binary.
> TypeError: can only concatenate deque (not "list") to deque:
>   File "E:\tools\godot\sources\godot\SConstruct", line 741:
>     methods.generate_vs_project(env, GetOption("num_jobs"))
>   File "E:\tools\godot\sources\godot\methods.py", line 875:
>     module_configs = ModuleConfigs()
>   File "E:\tools\godot\sources\godot\methods.py", line 790:
>     self.add_mode()  # default
>   File "E:\tools\godot\sources\godot\methods.py", line 813:
>     self.arg_dict["cppdefines"] += ModuleConfigs.for_every_variant(env["CPPDEFINES"] + defines)
> ```
> 
> I didnt change any path locations (neither cache or install) of the visual studio installed.
> 
> Note that I'm trying to build branch `3.x`, not sure if it changes something.
> 
> Any other idea?

`pip install Scons==4.4.0` might help.

**Comment by Klaim** [comment]
Thanks, switching to `Scons==4.4.0` seems to work, it builds now. Indeed I had the latest scons installed which was 4.5.something. 👍🏽

**Comment by wangafei** [comment]
scons platform=windows dev_build=yes vsproj=yes
error -ologo

**Comment by ConorDamery** [comment]
I can confirm scons 4.4.0 fixed it for me
