### ISSUE TITLE
Headless export doesn't generate `.godot/global_script_class_cache.cfg` properly when global script classes are used

### ISSUE THREAD

**Issue by umarcor** [godotengine/godot#75684]
### Godot version

4.x

### System information

Fedora 37, ubuntu:latest

### Issue description

When a repo with a Godot 4.x project is cloned and `godot --headless --export-release <NAME> <PATH>` is executed, it will fail to find GDScript classes (those not attached to any Scene or Resource but used as global resources).

Locally, it can be worked around by executing the Godot Editor once without using the `--headless` option, to let it create the `.godot` subdir. Therefore, the headless export depends on files in `.godot` which it cannot create by itself.

Precisely, if `.godot/global_script_class_cache.cfg` is added to SCM, the headless run with an otherwise empty `.godot` will succeed.

However, with Godot 4.x, a `.gitignore` file is added by default, which does ignore `.godot/`. In order to add `global_script_class_cache.cfg`, the `.gitignore` needs to be modified:

```gitignore
/.godot/**/*.*
!/.godot/global_script_class_cache.cfg
```

See https://github.com/itsas-taldea/moon/commit/d12a5ccd41f1ecc2308721cc12d83d603c1df4d2

I don't know what the solution would be:

- Should Godot regenerate the config file transparently without errors?
- Does that info need to be saved in the project file (which is checked in SCM) instead of in subdir `.godot`?

### Steps to reproduce

```sh
git clone https://github.com/itsas-taldea/moon
cd moon
git checkout -b test-bug bada535a
cd godot
# This will produce errors such as: 'SCRIPT ERROR: Parse Error: Identifier "Utils" not declared in the current scope.'
godot --headless --export-release Linux ./moon.linux

rm -rf .godot
# Open the project in Godot "normally", then close it.
# Now, it will not produce SCRIPT ERRORs:
godot --headless --export-release Linux ./moon.linux

# Let's copy the problematic config file for later use
cp .godot/global_script_class_cache.cfg ../

rm -rf .godot
# It will produce errors again
godot --headless --export-release Linux ./moon.linux

rm -rf .godot
mkdir .godot
mv ../global_script_class_cache.cfg .godot/
# It will succeed now
godot --headless --export-release Linux ./moon.linux
```

### Minimal reproduction project

See subdir in https://github.com/itsas-taldea/moon. Note that branch `main` includes `.godot/global_script_class_cache.cfg`. That needs to be removed in order to reproduce this issue.

See https://github.com/itsas-taldea/moon/actions/runs/4614444782/jobs/8157419040 and https://github.com/itsas-taldea/moon/actions/runs/4614591084/jobs/8157704125.

**Comment by akien-mga** [comment]
```
# This will produce errors such as: 'SCRIPT ERROR: Parse Error: Identifier "Utils" not declared in the current scope.'
godot --headless --export-release Linux ./moon.linux
```

This should work fine even without `.godot` folder.
Yes, it does print errors, but the generated export should work fine. Can you confirm?

Preventing the error spam is a worthy goal but it's just UX improvement, the functionality should be good already.

**Comment by akien-mga** [comment]
```
See subdir in [itsas-taldea/moon](https://github.com/itsas-taldea/moon). Note that branch main includes .godot/global_script_class_cache.cfg. That needs to be removed in order to reproduce this issue.
```

Tested with 4.0.2-stable and unlike what I wrote above (which is my experience on some other test projects), this one does export a broken PCK on the first run if `.godot` is missing.

Can be checked with:
```
mkdir build
cd godot
rm -rf .godot
Godot_v4.0.2-stable_linux.x86_64 --headless --export-pack Linux ../build/moon.zip
```

Then unzip the data package, and indeed `.godot/global_script_class_cache.cfg` exists but is empty.

**Comment by umarcor** [comment]
@akien-mga I can confirm that the exported result is broken. Since the scripts are not found, the functions within are not executed and the UI is broken due to missing images (the UI is mostly based on VBoxes, HBoxes and Grids with TextureRect and TextureButton). Actually, that's how I found out there was a problem. I read the logs post-mortem.

**Comment by bend-n** [comment]
I found this when trying to workaround #69511, this is [my workaround](https://github.com/bend-n/tracer/blob/main/init_classes.py).

**Comment by luispadron** [comment]
Running into the same issue, running Godot twice is an odd solution though.
Is this expected? I'm seeing messages to ignore these errors, but they're not producing valid exports. 

To reproduce:

- `rm -rf .godot` 
- `<path/to/godot/binary> --headless --export-release "Config"`
