### ISSUE TITLE
Greek translation missing from Weblate

### ISSUE THREAD

**Issue by gtsiam** [godotengine/godot#7568]
I just recently found out about godot, and I would like to contribute in it's translation, in a language that I know (that would be greek). Unfortunately, it is not available as a language in Weblate. If you decide to add it, I would be more than happy to help.

**Comment by akien-mga** [comment]
I think you can add it yourself, no? If not I can add it.

**Comment by gtsiam** [comment]
I dont seem to be able to add it. Besides, [this](https://github.com/godotengine/godot/blob/master/tools/translations/README.md#adding-new-languages) hints that I cant...

**Comment by akien-mga** [comment]
Hehe, and I wrote that :D I'll add it right away.

**Comment by gtsiam** [comment]
ok, thanks.

**Comment by akien-mga** [comment]
Done: https://hosted.weblate.org/projects/godot-engine/godot/el/ :)
