### ISSUE TITLE
Physical keys are not correct in web exports

### ISSUE THREAD

**Issue by DomDumont** [godotengine/godot#75681]
### Godot version

4.0.2

### System information

Windows 10, web

### Issue description

Hi,
It seems physcial keys are not correct when I export to web format.
For example, I use this input map to move a character, on my windows build and with my french keyboard, everything is ok  BUT when i export to web, only the qwerty mapping works. This is not the expected behaviour, my french azerty keyboard should work 
as it does on the windows build.

![image](https://user-images.githubusercontent.com/7558109/230026310-4fb83bda-c35c-4fa6-a5c4-3f630c02419c.png)

### Steps to reproduce

enter a physical key in the input map (let's say W).  with an non-qwerty keyboard, the web export should be able to use the key with the same position on the keyboard ( z in french for example )

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
@DomDumont Which web browsers did you test this with?

**Comment by DomDumont** [comment]
@Calinou Chrome on Windows, also Chromium on linux
