### ISSUE TITLE
Couln't Connect to GDscript language in VS CODE

### ISSUE THREAD

**Issue by walidsantos** [godotengine/godot#75683]
### Godot version

4.0.2

### System information

Windows 10,  Intel(R)HD Graphics Family, 20.19.15.5171,  GLES3

### Issue description

![image](https://user-images.githubusercontent.com/53328867/230042672-36aa2cc9-e8a6-4964-87e3-6035452954bd.png)

### Steps to reproduce

1. i downloaded GD-TOOLS
2. go to project settings
3. go down to godot
4. Added  my executable godot path in Editor_PATH
5. Added my tscn file path(universal) in Scene file config

sadly the error still occurs

![image](https://user-images.githubusercontent.com/53328867/230043268-bd4581f4-64d5-4f6d-974b-72b1224a7d5a.png)

![image](https://user-images.githubusercontent.com/53328867/230043330-a57ae925-ef9f-42c7-a7ae-82d42d632854.png)

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
The

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-vscode-plugin/issues/473, as this is an issue with the plugin.
