### ISSUE TITLE
Rigidbody collision against CharacterBody3D doesn't always trigger on_body_entered signal

### ISSUE THREAD

**Issue by substract** [godotengine/godot#75696]
### Godot version

Godot 4.0.2

### System information

Windows 10, NVIDIA GeForce 1060 GTX 3GB, Vulkan

### Issue description

Rigidbody collision against CharacterBody3D doesn't always trigger on_body_entered signal.
This happens when both objects are moving in the same direction

### Steps to reproduce

Play the test scene.
Press the right arrow key to move the character away from the rigid body. On contact no signal is emitted.

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/11160540/test.zip)

**Comment by rburing** [comment]
This is an issue with continuous collision detection (CCD), because it doesn't happen when `continuous_cd` is turned off on the RigidBody3D.
