### ISSUE TITLE
Local Array gets changed when altering the Global Array

### ISSUE THREAD

**Issue by Daniel-da-Silva** [godotengine/godot#75693]
### Godot version

4.0.2, 3.5.2

### System information

MX Linux, i5-6500

### Issue description

Hey,

It is easier to understand the problem if you see the code (at least for me).
First script is the Globals.gd singleton, the rest is the local script.

```
extends Node

var test_array : Array = [1, 1, 1]

------------------------------
extends Node2D

var local_array : Array = [7, 8, 1]

func _process(_delta):

	Globals.test_array = local_array

	if Input.is_action_just_pressed("ui_home"):
		Globals.test_array[0] -= 1
		print(Globals.test_array)
		print(local_array)
```

I would expect that the result of the prints would be:
[6, 8, 1]
[7, 8, 1]

Strangely enough, they are both
[6, 8, 1]
[6, 8, 1]

When I repeat the Input I get
[5, 8, 1]
[5, 8, 1]
etc.

And my expectation would be to get always:
[6, 8, 1]
[7, 8, 1]

The problem exists in Godot 3.5.2 and Godot 4.0.2

### Steps to reproduce

Singleton Globals.gd
Local Script attached to scene
Hit the "home" key, on my keyboard Pos1

### Minimal reproduction project

```

extends Node

var test_array : Array = [1, 1, 1]


extends Node2D

var local_array : Array = [7, 8, 1]

func _process(_delta):

	Globals.test_array = local_array

	if Input.is_action_just_pressed("ui_home"):
		Globals.test_array[0] -= 1
		print(Globals.test_array)
		print(local_array)
```

**Comment by Mickeon** [comment]
Your expectations are incorrect. By assigning `local_array` to `Globals.test_array`, both arrays are one in the same. The properties point to the same array in memory. To prevent this, you could use a copy of that array, from `Array.duplicate()`.

![image](https://user-images.githubusercontent.com/66727710/230134790-1fcfd4b4-f6bc-4f48-bde5-7a4817b51b7a.png)

**Comment by Daniel-da-Silva** [comment]
Oh, okay, I didn't know that. Thanks! Is this typical for programming languages or a GDScript quirk/design choice?

**Comment by joao-pedro-braz** [comment]
Passing by reference is actually the standard

**Comment by Daniel-da-Silva** [comment]
Thanks, that's good to know. Then I will refrain from opening a feature proposal.
