### ISSUE TITLE
Lock the script edit button if a compiled script is added to a node

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#7569]
**Operating system or device - Godot version:**
Tested only on 2.1.1 stable Linux

**Issue description** (what happened, and what was expected):
Is possible to add a gdc script file to a node/scene but it lets you edit the binary script (just shows an empty file.

The editor should not let you open a binary file, maybe lock the script button/menu options.

**Steps to reproduce:**
- Compile a script
- Add it to a scene or node
- Try to edit the compiled script

ps: posted a blank issue for some reason o_O

**Comment by bojidar-bg** [comment]
Note that this affects the upcomming DLScript as well (since it switches to the editor as if there is something to edit...)

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by eon-s** [comment]
It was affecting the pre-stable versions (including gdnative scripts) but now I cannot add a gdc file to a node anymore, this may still affects gdnative but I have not tested again.

**Comment by eon-s** [comment]
I guess this issue is no longer valid since looks like compiled scripts cannot be added to a project.
