### ISSUE TITLE
GDExtension property mismatches

### ISSUE THREAD

**Issue by migueldeicaza** [godotengine/godot#75695]
### Godot version

master: 0291fcd7b66bcb315a49c44de8031e5596de4216

### System information

MacOS

### Issue description

While generating Swift bindings, there are a number of places where Godot declares property getters or setters that do not match the methods define.

The following is a list of those cases:

* AnimationNodeTransition.input_count: property declared get_input_count, but it does not exist with that name
* ArrayOccluder3D.vertices: property declared get_vertices, but it does not exist with that name
* ArrayOccluder3D.indices: property declared get_indices, but it does not exist with that name
* AudioStreamPlayer.playing property declared _set_playing but it does not exist with that name
* AudioStreamPlayer2D.playing property declared _set_playing but it does not exist with that name
* AudioStreamPlayer3D.playing property declared _set_playing but it does not exist with that name
* Control.anchor_left property declared _set_anchor but it does not exist with that name
* Control.anchor_top property declared _set_anchor but it does not exist with that name
* Control.anchor_right property declared _set_anchor but it does not exist with that name
* Control.anchor_bottom property declared _set_anchor but it does not exist with that name
* Control.size property declared _set_size but it does not exist with that name
* Control.position property declared _set_position but it does not exist with that name
* Control.global_position property declared _set_global_position but it does not exist with that name
* CurveTexture.width: property declared get_width, but it does not exist with that name
* CurveXYZTexture.width: property declared get_width, but it does not exist with that name
* DirectionalLight2D.height: property declared get_height, but it does not exist with that name
* DirectionalLight3D.directional_shadow_split_1: property declared get_param, but it does not exist with that name
* DirectionalLight3D.directional_shadow_split_2: property declared get_param, but it does not exist with that name
* DirectionalLight3D.directional_shadow_split_3: property declared get_param, but it does not exist with that name
* DirectionalLight3D.directional_shadow_fade_start: property declared get_param, but it does not exist with that name
* DirectionalLight3D.directional_shadow_max_distance: property declared get_param, but it does not exist with that name
* DirectionalLight3D.directional_shadow_pancake_size: property declared get_param, but it does not exist with that name
* FontFile.font_name: property declared get_font_name, but it does not exist with that name
* FontFile.style_name: property declared get_font_style_name, but it does not exist with that name
* FontFile.font_style: property declared get_font_style, but it does not exist with that name
* FontFile.font_weight: property declared get_font_weight, but it does not exist with that name
* FontFile.font_stretch: property declared get_font_stretch, but it does not exist with that name
* FontFile.fallbacks: property declared get_fallbacks, but it does not exist with that name
* FontVariation.fallbacks: property declared get_fallbacks, but it does not exist with that name
* FontVariation.opentype_features: property declared get_opentype_features, but it does not exist with that name
* FontVariation.spacing_glyph: property declared get_spacing, but it does not exist with that name
* FontVariation.spacing_space: property declared get_spacing, but it does not exist with that name
* FontVariation.spacing_top: property declared get_spacing, but it does not exist with that name
* FontVariation.spacing_bottom: property declared get_spacing, but it does not exist with that name
* GradientTexture1D.width: property declared get_width, but it does not exist with that name
* GradientTexture2D.width: property declared get_width, but it does not exist with that name
* GradientTexture2D.height: property declared get_height, but it does not exist with that name
* InputEventAction.pressed: property declared is_pressed, but it does not exist with that name
* InputEventJoypadButton.pressed: property declared is_pressed, but it does not exist with that name
* InputEventKey.pressed: property declared is_pressed, but it does not exist with that name
* InputEventKey.echo: property declared is_echo, but it does not exist with that name
* InputEventMouseButton.pressed: property declared is_pressed, but it does not exist with that name
* InputEventScreenTouch.pressed: property declared is_pressed, but it does not exist with that name
* Node2D.transform: property declared get_transform, but it does not exist with that name
* Node2D.global_transform: property declared get_global_transform, but it does not exist with that name
* NoiseTexture2D.width: property declared get_width, but it does not exist with that name
* NoiseTexture2D.height: property declared get_height, but it does not exist with that name
* OmniLight3D.omni_range: property declared get_param, but it does not exist with that name
* OmniLight3D.omni_attenuation: property declared get_param, but it does not exist with that name
* OptionButton.selected property declared _select_int but it does not exist with that name
* PlaceholderMesh.aabb: property declared get_aabb, but it does not exist with that name
* PlaceholderTexture2D.size: property declared get_size, but it does not exist with that name
* PlaceholderTextureLayered.layers: property declared get_layers, but it does not exist with that name
* PointLight2D.height: property declared get_height, but it does not exist with that name
* SpotLight3D.spot_range: property declared get_param, but it does not exist with that name
* SpotLight3D.spot_attenuation: property declared get_param, but it does not exist with that name
* SpotLight3D.spot_angle: property declared get_param, but it does not exist with that name
* SpotLight3D.spot_angle_attenuation: property declared get_param, but it does not exist with that name
* SystemFont.font_weight: property declared get_font_weight, but it does not exist with that name
* SystemFont.font_stretch: property declared get_font_stretch, but it does not exist with that name
* SystemFont.fallbacks: property declared get_fallbacks, but it does not exist with that name
* VisibleOnScreenNotifier3D.aabb: property declared get_aabb, but it does not exist with that name

### Steps to reproduce

This seems to be just human error when the properties are either declared with a different name, or the missing methods are not surfaced.

### Minimal reproduction project

No need for a project, the list above contains the deltas

**Comment by AThousandShips** [comment]
Is the issue here that these functions are missing in the extension bindings because they are present in the code

**Comment by migueldeicaza** [comment]
They look like human error, often the getter and setter are there, but with different names than those referenced on the property

**Comment by AThousandShips** [comment]
What do you mean with different names? That they aren't "get_x" and "set_x"? That's not a guarantee, it's not broken

**Comment by migueldeicaza** [comment]
Take this example from the list above:

AnimationNodeTransition.input_count: property declared get_input_count, but it does not exist with that name

The Godot source declares the setter:

```
ClassDB::bind_method(D_METHOD("set_input_count", "input_count"), &AnimationNodeTransition::set_input_count);
```

And the references a non-declared getter:
```
ADD_PROPERTY(PropertyInfo(Variant::INT, "input_count", PROPERTY_HINT_NONE, "", PROPERTY_USAGE_EDITOR | PROPERTY_USAGE_ARRAY | PROPERTY_USAGE_UPDATE_ALL_IF_MODIFIED, "Inputs,input_"), "set_input_count", "get_input_count");
```

But you are correct that some seem to be a problem with my script that caught this on virtual methods - like in scene/2d/audio_stream_player_2d.cpp which declares a

**Comment by AThousandShips** [comment]
It doesn't seem that there's any bug here?

**Comment by migueldeicaza** [comment]
I'll close the bug for now, and if I find an issue will reopen with additional information.

thank you for your help @AThousandShips
