### ISSUE TITLE
textureLod(TEXTURE, UV, blur_amount) in Godot 4.0.2 not working compared to Godot3.X

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#75690]
### Godot version

4.0.2 stable

### System information

Win 10, NVidea 765M, Vulkan,

### Issue description

In Godot 3 this will work and result in a blurred texture: 

```
shader_type canvas_item;

uniform float blur_amount : hint_range(0.0, 10.0) = 2.0;

void fragment() {
	COLOR =  textureLod(TEXTURE, UV, blur_amount);
}
```

In Godot 4.0.2 this will do nothing. Also no errors or warnings will show up.
Note: This is issue about using `textureLod()` with `TEXTURE`, not `SCREEN_TEXTURE`!

Maybe related to https://github.com/godotengine/godot/issues/61969. I have also found a number of other existing issues regarding `textureLod()` however all of them seem to be about `textureLod(SCREEN_TEXTURE, SCREEN_UV, amount)`, which _does work fine_ for me (at least in the Vulkan renderer).

### Steps to reproduce

Copy/Paste above shader into shader material.

### Minimal reproduction project

Godot 4.0.2 reproduction project:
[texture_lod_issue.zip](https://github.com/godotengine/godot/files/11160242/texture_lod_issue.zip)

**Comment by Calinou** [comment]
Does the texture have mipmaps generated (check the Import dock)? If there are no mipmaps, you can't sample a lower mipmap.

**Comment by golddotasksquestions** [comment]
@Calinou :
Does the texture have mipmaps generated (check the Import dock)? 

I tried selecting the texture file in the FileSystem, then going to the Import dock and enabling the "Mipmaps Generate ON" checkmark, then hit the Reimport button, but it **made no difference**.

**Comment by clayjohn** [comment]
I took a look at the MRP. There are two issues:
1. "Generate Mipmaps" in the import settings was set to "false" so no mipmaps were generated, and
2. "Texture Filter" was set to "inherit" in the Sprite's Texture settings, so linear filtering was used. 

Enabling mipmaps and changing the filter to linear with mipmaps makes the MRP behave as expected.

**Comment by golddotasksquestions** [comment]
@clayjohn 

Thank you very much, that was it indeed! I did check the Import Mipmap as I said before, but I was not aware about having to change the the Filtering setting as well.

**Comment by ArcticWolves** [comment]
> Я взглянул на MRP. Есть две проблемы:
> 
> 1. Параметр "Generate Mipmaps" в настройках импорта был установлен в значение "false", поэтому MIP-карты не создавались, и
> 2. В настройках текстур Sprite был установлен режим "Texture Filter" на "inherit", поэтому была использована линейная фильтрация.
> 
> Включение MIP-карт и изменение фильтра на линейный с MIP-картами приводит к тому, что MRP ведет себя должным образом.


Thank you @clayjohn - I used ColorRect before, but changed it to TextureRect
