### ISSUE TITLE
[Compatibility ]Sprite3D flickers when stacked on another, and camera position/angle changes.

### ISSUE THREAD

**Issue by nakano15** [godotengine/godot#75698]
### Godot version

4.0

### System information

Windows 10, 8GB RAM, AMD Athlon(tm) II X4 640 Processor   3.01 GHz, AMD Radeon R7 200 Series

### Issue description

While using gl_compatibility rendering, 
If you place two Sprite3D on the same position of each other, and then move the camera around, the sprites will begin to flicker.
The flickering gets worser if any of the stacked sprites also change position.

### Steps to reproduce

1. Place two Sprite3D objects.
2. Change one of the Sprite3D to either have a different size or position, while it's still on top of the other Sprite3D.
3. Place a camera and make it face the sprite.
4. Make the camera move or rotate.
5. Debug to see the issue happening.
6. If you want to worsen the issue, make one of the sprites move.

### Minimal reproduction project

[Sprite Issue.zip](https://github.com/godotengine/godot/files/11160791/Sprite.Issue.zip)

**Comment by Zireael07** [comment]
Most likely ordinary Z fighting

**Comment by nakano15** [comment]
Yeah, seems like it. The camera doesn't seems to know which sprite to draw first because they have same Z position.
Not even changing Render Priority stops this issue from happening.

**Comment by Calinou** [comment]
This is a known 3D rendering limitation. Using alpha scissor transparency or playing with the node's **Sorting Offset** (not the same as ***Render Priority** can help. See https://docs.godotengine.org/en/latest/tutorials/3d/3d_rendering_limitations.html#transparency-sorting.
