### ISSUE TITLE
Base Meshinstance3D: control of visual shader inside of a gdscript => invalid get index material

### ISSUE THREAD

**Issue by hvprint** [godotengine/godot#75702]
### Godot version

Godot_v4.0.1

### System information

Win11

### Issue description

![image](https://user-images.githubusercontent.com/129978634/230138153-d3b37b61-fe0c-4639-a0be-cb973bd9893b.png)
![image](https://user-images.githubusercontent.com/129978634/230150719-961de133-87ee-44b9-8545-01dd6f11ab5f.png)

I want to fade in and out a shader on a MeschInstance3D. The Shader works fine and show the custom variable "Fade" in the  "Shader Parameters" section. But I am not able to address it in gesript.

### Steps to reproduce

1. Make a MeshInstance3D Node
2. Add a mesh ressorce
3. Add a visual shader Material 
4. In the visual shader add a Float Parameter vith a var like "Fade." and connect it to Alpha
5. Make a godot script connected to the MeshInstance3D try to get the mateiral like in the code below.
Than you will get the Error Message "invalid get index material"

### Minimal reproduction project

```gdscript
extends MeshInstance3D

@onready
var mat:Material = $".".material
var dir = 0.1
var fade = 0.0
var ticks = 0


# Called when the node enters the scene tree for the first time.
func _ready():
	pass
	

# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	pass
	ticks += 1
	if mat and ticks % 100 == 0:
		fade += dir
		if fade > 1.0:
			dir = -dir
			fade = 1.0
		elif fade < 0.0:
			dir = -dir
			fade = 0.0
		mat.set_shader_parameter("Fade", fade)
		$".".material.set_shader_parameter("Fade", fade)
		print(fade)
```

**Comment by clayjohn** [comment]
Can you please upload an MRP so contributors can try to reproduce and fix this issue?

Without an MRP, nothing is going to happen

**Comment by hvprint** [comment]
I found a solution myself. I think the problem is to find anything in the documentation of Godot 4.
A lot of things have changed.

To load the shader from the  MeshInstance3D I found:

"var shader_material = $".".get_active_material(0)"

and to change the var I done it with

"shader_material.set_shader_parameter("Fade", fade)"

That all works fine for me.

Thanks for your support.
