### ISSUE TITLE
The new default UI theme has blurry edges

### ISSUE THREAD

**Issue by davthedev** [godotengine/godot#75707]
### Godot version

4.0-stable x86_64

### System information

Ubuntu 22.04, Intel Iris Plus Graphics G7, Xorg

### Issue description

The default UI theme has blurred edges around focus boxes. Perhaps other lines of rectangles used in the UI have a slight blur.

![Capture d’écran du 2023-04-05 20-05-40](https://user-images.githubusercontent.com/26961646/230171327-6b5b3873-b6bc-4bde-82d5-2cc35aa40ed9.png)

It is a good thing to antialias the corners; I would expect the straight edges of the rectangle to be pixel-perfect for a polished look.

![blurry](https://user-images.githubusercontent.com/26961646/230171282-7c81e109-b808-4d36-acf8-0bac2b857d6e.png)

The blurry edges on the sides make the default theme look a bit unfinished. Even if a bit outdated, the previous default UI theme in Godot 3.5 had a more polished look with crisp edges.

It is noticeable especially on full HD, non Retina / high-dpi screens where the grid of pixels is still visible.

### Steps to reproduce

Create new project and a Control scene.

Add a few Button and LineEdit controls. Run the scene.

See that the outline around the focused control has a blurry edge.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
This is because antialiasing is enabled on the default theme's styleboxes to make them smoother, especially if they are rotated: https://github.com/godotengine/godot/blob/fba9416fe0046c32b19d47523eab95e9e6036093/scene/resources/default_theme/default_theme.cpp#L59

**Comment by davthedev** [comment]
I had a look at the StyleBoxFlat code, and it seems that there are two things happening with the antialiasing code:
- The addition of additional triangles to smooth the edge
- Something with the UVs I do not really understand, that makes the whole thing blurry
Seems the latter was added lately. Both share the same antialiasing factor. Perhaps if we keep the former only? I am experimenting with that part of code on my side for another improvement.

Sure, the OpenGL antialiasing is unreliable and literature about line drawing using triangles recommend the extra polygons to fade the border to transparent, even for simple lines.
I also thought about applying a pixel shader, but is it doable to only part of the drawing instructions?

**Comment by Calinou** [comment]
> Also, if we want some drawing code that draws perfect edges even if the viewport is zoomed, it should be aware of the actual rendered resolution and adjust accordingly. For instance, the thickness of edge adjustment using triangles should be relativelly smaller if the resolution is higher or the view is zoomed in.

This would require updating the polygon buffer every time the viewport size or camera zoom changes, but there's no way to ensure this can be done quickly. For StyleBoxFlat specifically, we could recreate them when the viewport size changes, but there's no way for a *resource* to listen to a viewport signal to my knowledge.

**Comment by davthedev** [comment]
I fixed those blurry edges and the rendering is much better
https://github.com/godotengine/godot/pull/76132
