### ISSUE TITLE
Unable to close godot after getting a scene dependency error 

### ISSUE THREAD

**Issue by ALiwoto** [godotengine/godot#75717]
### Godot version

4.0.2.stable.official.7a0977ce2

### System information

Windows11, Forward+, Vulkan

### Issue description

I've modified some files inside of my project, then closed Godot Editor.
And then opened it again through command line: `> godot .\project.godot` but saw this message appearing on the editor:

![image](https://user-images.githubusercontent.com/70187458/230209034-3377a204-cd79-48a4-99fa-2d9d4616bbb6.png)

So I tried to close the Editor through terminal (yes, `ctrl+c`), but then this happened:

![image](https://user-images.githubusercontent.com/70187458/230208949-0d8065aa-dce4-40bd-b4d6-b51587537bf7.png)

And didn't stop either, kept repeating itself (the Editor GUI got closed; but the process didn't).
> I know using `ctrl+c` for closing the editor is not really a _standard way_, but I thought this behavior is kinda _unexpected_, so thought better to report it.

### Steps to reproduce

1. Just download a normal project from [assets library](https://godotengine.org/asset-library/asset).
2. Modify path of one of its resources (in a way that loading the main scene fails). (do this step while the editor is closed).
3. Now open up Godot in command line `godot .\project.godot`; wait for the dialog box (shown in my screenshot previously) to appear.
4. Try to close the Editor using `ctrl+c` inside of command line.
5. Observe massive amount of errors spam (but the GUI is already closed).

> After that I usually just kill the powershell session.

### Minimal reproduction project

_N/A_

**Comment by KoBeWi** [comment]
Can you attach an example project affected by this issue?
(I tried a random project from AssetLib as suggested and the problem does not appear)
