### ISSUE TITLE
Error when changing project folder name

### ISSUE THREAD

**Issue by federicort** [godotengine/godot#75715]
### Godot version

4.0.2 stable

### System information

Fedora 37 Linux, Wayland

### Issue description

Godot crashes after project's folder name has been changed 

### Steps to reproduce

With godot closed I changed my projects folder name, then I opened godot and tried to import the project from the folder with the updated name, godot crashes and when it manages to open the Filesystem only shows Res:// but no files inside.
I'm using the version straight from the website 
Godot_v4.0.2stable_linux.x86_64

### Minimal reproduction project

Since it's simple problem it should not be needed for the reproduction of the problem.
If you need it please let me know and I'll add it.

**Comment by ZachAR3** [comment]
+1, just encountered this. Extremely annoying.

**Comment by KoBeWi** [comment]
Can't reproduce in 4.1 dev2.
Can you test in that version?

**Comment by AThousandShips** [comment]
Closing as resolved, if someone can reproduce this on a supported version please respond
