### ISSUE TITLE
Area2D mouse_entered/mouse_exited doesn't update properly with Camera2D movement

### ISSUE THREAD

**Issue by paul-deva** [godotengine/godot#75711]
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Windows 10, Linux

### Issue description

When the `mouse_entered` and `mouse_exited` signals are used with an `Area2D` node, the signals are not emitted if the `Camera2D` moves the viewport such that the mouse enters or leaves the area.

![area](https://user-images.githubusercontent.com/118939014/230185696-4154ce92-b6da-4c28-a5f8-b088900d7ac8.gif)

### Steps to reproduce

Open the attached minimal project...

1) Put the mouse cursor inside the circular area
2) Move the camera with WASD or arrow keys such that the mouse cursor enters and leaves the area (don't move the mouse in this step)
3) Watch as the label doesn't update properly

### Minimal reproduction project

[Area2D bug.zip](https://github.com/godotengine/godot/files/11162322/Area2D.bug.zip)

**Comment by Sauermann** [comment]
A few weeks ago, @RandomShaper and I have discussed this issue and came to the conclusion, that this should be considered a bug and be solved.

**Comment by paul-deva** [comment]
> A few weeks ago, @RandomShaper and I have discussed this issue and came to the conclusion, that this should be considered a bug and be solved.

I haven't found a similar issue when searching the git so I decided to open up this one. It might be good to check if other types of nodes have the same bug, like `Control` nodes and `Area3D`.

**Comment by Sauermann** [comment]
The discussion happened on RockenChat, so it is good to have this Issue open as a reminder. And both other nodetypes, that you mentioned, show the same behavior.

**Comment by Dritic** [comment]
Would love to see a fix for this implemented! I've also noticed that it's an issue if you want to use mouse_entered/mouse_exited signals on control nodes that have their positions updated (for example an AnimationPlayer that makes UI appear/disappear on toggle).

**Comment by Dritic** [comment]
Would love to see a fix for this implemented! I've also noticed that it's an issue if you want to use mouse_entered/mouse_exited signals on control nodes that have their positions updated (_for example: making UI appear/disappear using an AnimationPlayer_).

**Comment by Sauermann** [comment]
@Dritic The issue about Control nodes is more complex and will have to wait until `Viewport::update_mouse_cursor_state` no longer creates InputEvents.
