### ISSUE TITLE
TileSet Theme Menu Hard to See

### ISSUE THREAD

**Issue by toliaferrode** [godotengine/godot#7571]
**Operating system or device - Godot version:**
Ubuntu, Godot 2.1.1

**Issue description** (what happened, and what was expected):
When editing a tileset the "Theme" menu isn't obvious. I'm coming back to Godot from a break and I wasn't sure where it was supposed to show up, but then I saw it. Because it doesn't move the panels out of the way it's not obvious at first where it is. For a new user it could be frustrating.

Maybe also making it more obvious that the Theme menu is for editing a tileset. Like perhaps renaming it from just "Theme" to "Tileset" theme.

**Steps to reproduce:**
Edit a Tileset

**Link to minimal example project** (optional but very welcome):

--------------

*NOTE: Incompatibilities are broken features in the current master branch / 3.0-alpha
are expected, so no need to report them for now. Thanks!*

**Comment by Zylann** [comment]
I didn't know there was such a thing. Good to know^^
Tilesets aren't usually edited this way (it's done with scenes now), but the location of this button ans its name look messy.

**Comment by eon-s** [comment]
Where is that menu?

**Comment by Zylann** [comment]
At the bottom of the main viewport when you edit a TileSet resource:
![image](https://cloud.githubusercontent.com/assets/1311555/22066371/9e24bc2c-dd84-11e6-8f8e-14f500315ad6.png)
It lets you add or remove tiles from the list.

**Comment by eon-s** [comment]
@Zylann :no_mouth:

Oooh, after selecting the tileset resource, I guess that is to create a new tileset in the tilemap. and allows create and merge, looks handy but makes no sense to be hidden in plain sight there.

Maybe making it part of the lower panel or top tilemap buttons, since tileset won't have much use outside the tilemap (the editor one at least).

**Comment by Noshyaar** [comment]
This is how it looks in 3.0
![image](https://user-images.githubusercontent.com/26753932/38567663-fe4fb7b8-3d10-11e8-83b2-c76360b4cc35.png)

**Comment by Zylann** [comment]
How do we add and removes tiles now? (excluding the scene converter)

**Comment by Noshyaar** [comment]
![image](https://user-images.githubusercontent.com/26753932/38571417-a47606a2-3d1a-11e8-9582-b42b0850e600.png)

**Comment by MarianoGnu** [comment]
I fixed this bug while working on autotiles, completely forgot about 2.1 branch

**Comment by KoBeWi** [comment]
Closing, as this was 2.1-specific and I doubt it will be fixed there now.
