### ISSUE TITLE
Vulkan: LightmapGI Crashes when uv2 is high

### ISSUE THREAD

**Issue by CachorroVoador** [godotengine/godot#75726]
### Godot version

4.0.stable

### System information

Windows 10, Gt 710, Driver: 474.14, Vulkan

### Issue description

Goodnight! How are you?

 When I try to bake, but with the uv2 of the objects set to below 100, it does without any problem, however when they are above 100, godot hangs and stops responding and appears in the console saying that it has lost the vulkan Driver as if the video card has been reset

Here's a video demonstrating it and I'm sorry for the awful fps in the video. I had to download obs because the recorder I used used the video card to record, but even it stops recording when it gives an error

https://user-images.githubusercontent.com/87171245/230230191-c0eddb42-bea1-43ec-9e38-c2eb3dc31858.mp4

### Steps to reproduce

1- Place some objects in the scene that contain uv2
2- Expand them until the uv2 is above 100
3- Bake the LightmapGI

### Minimal reproduction project

[lightmap_crash.zip](https://github.com/godotengine/godot/files/11163870/lightmap_crash.zip)

**Comment by Calinou** [comment]
You're most likely running out of video memory, as a GT 710 only has 1 GB of VRAM.

According to `nvidia-smi`, baking lightmaps requires 1.5 GB of VRAM in this scene (my VRAM usage goes from 2.6 GB to 4.1 GB when I click **Bake Lightmaps**). For reference, baking lightmaps in the MRP takes 34 seconds on my RTX 4090 (this includes denoising time, which is performed on the CPU).

PS: You need to switch to the Forward+ rendering method to see the baked lightmaps due to https://github.com/godotengine/godot/issues/55867.

**Comment by CachorroVoador** [comment]
Oh yes, I understand! Thanks

The video card model I bought has 2gb of vram in total
Which

> PS: You need to switch to the Forward+ rendering method to see the baked lightmaps due to https://github.com/godotengine/godot/issues/55867.

About this. Is it only possible to have all lightmapgi features in forward? This becomes somewhat limiting for mobile, which already has almost nothing

**Comment by lawnjelly** [comment]
If it is to do with the UV2s, maybe Godot should be normalizing the lightmap UVs (this would alter the source mesh data though).

**Comment by CachorroVoador** [comment]
> LightmapGI intends to be fully supported when using the Mobile rendering method, but it has several bugs right now.
And about gl_compatibility? Is be possible to use LightmapGl with gl?

Do you intend to also put a processor-only version for the lightmap? As it was before in godot 3. I think it would be interesting for those who have the same problem as me. Sorry for bad english, i'm using google translate

**Comment by Calinou** [comment]
> And about gl_compatibility? Is be possible to use LightmapGl with gl?

There's no way to bake lightmaps while using the Compatibility rendering method, but it should be possible to *render* lightmaps that were already baked in the future. This isn't currently implemented yet though.

> Do you intend to also put a processor-only version for the lightmap? As it was before in godot 3. I think it would be interesting for those who have the same problem as me. Sorry for bad english, i'm using google translate

See https://github.com/godotengine/godot-proposals/issues/3921.

**Comment by CachorroVoador** [comment]
I understood. Thank you for your attention! I will close this issue as I consider it resolved
Have a good day!

**Comment by Calinou** [comment]
Reopening, as the video memory usage caveat should still be documented.
