### ISSUE TITLE
Attempted to free invalid ID when using shape keys

### ISSUE THREAD

**Issue by Dragoncraft89** [godotengine/godot#75724]
### Godot version

4.0.1 + current master (49a1962)

### System information

Ubuntu 22.04; Vulkan renderer

### Issue description

When freeing a MeshInstance3D with shape keys, the following error occurs:

```
E 0:00:01:0331   _free_internal: Attempted to free invalid ID: 3951369912333
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:8394 @ _free_internal()
```

### Steps to reproduce

Just run the attached project. The error message should appear automatically

### Minimal reproduction project

[shapekeybug.zip](https://github.com/godotengine/godot/files/11163584/shapekeybug.zip)

**Comment by smix8** [comment]
Have the same bug but only when the ArrayMesh also has a Surface Material.

Without a material the error does not show up.

**Comment by bitsawer** [comment]
Should be fixed by https://github.com/godotengine/godot/pull/78433, can't repro the test project issue anymore after the PR.
