### ISSUE TITLE
RigidBody3D in Convex Shape will sometimes pass through each other.

### ISSUE THREAD

**Issue by Abadunala** [godotengine/godot#75734]
### Godot version

4.0.2

### System information

Windows10, Vulkan, amd6700xt

### Issue description

![az](https://user-images.githubusercontent.com/75767374/230274252-6d97df39-440e-435e-b0fd-3d115853386b.gif)

### Steps to reproduce

Run the project below.
Keep in mind that I'm using a custom Convex Shape, not Box Shape.

### Minimal reproduction project

[bugs2.zip](https://github.com/godotengine/godot/files/11166484/bugs2.zip)

**Comment by rburing** [comment]
This bug was introduced in 4.0-beta4, so probably by https://github.com/godotengine/godot/pull/64382 cc @peastman

**Comment by rburing** [comment]
On second look that PR just reveals a pre-existing bug. PR incoming.
