### ISSUE TITLE
Visual Shader not declaring a parameter when the nodes are only connected to a VaryingSetter

### ISSUE THREAD

**Issue by VantaGhost** [godotengine/godot#75735]
### Godot version

v4.0.2.stable.mono.official [7a0977ce2]

### System information

Windows 10

### Issue description

When using the Visual Shader editor, if the output of a set of nodes only connects to a VaryingSetter, any Parameter nodes will fail to declare themselves in the generated code. This causes an error in the shader when the missing parameter is accessed, breaking the whole shader.

This happens in both the Vertex and Fragment functions (that I've tested) and with different types of parameters.

### Steps to reproduce

![GodotVSBug](https://user-images.githubusercontent.com/47618902/230274231-9cef179a-133e-4e10-856a-1693c9da8c34.png)
 
**To Reproduce:**

1. Create a new visual shader
2. In one of the shader functions (for example Vertex) create a new varying with the "manage varyings" button
3. Add a varying setter node and set it to the new varying
4. Add a parameter node of an appropriate type and connect to the varying setter
5. Click on the "show generated shader code" button, you should see the unknown identifier error

### Minimal reproduction project

N/A

**Comment by VantaGhost** [comment]
For anyone else having this issue, you can work around this by manually declaring the uniform parameter in a global expression node. Unfortunately this will cause another error for redefining the parameter if for some reason the parameter is being declared properly by the node.

**Comment by jsjtxietian** [comment]
Looks like the shader code generated for parameter nodes are wrong when connected to varying, but when connected to something like output, it's fine.

Also when add a bool varying shader compiler failed bacause of `flat` cannot declare a bool variable.
