### ISSUE TITLE
Exported arrays of Marker3Ds broken in editor

### ISSUE THREAD

**Issue by ZachAR3** [godotengine/godot#75755]
### Godot version

4.0.2.stable.mono

### System information

Endeavour OS Zen Kernel 6.2.7 Ryzen 5900x Nvidia RTX 2080TI 11GB (proprietary drivers)

### Issue description

When exporting an array of marker3ds after I add a new entry and click on the select Marker3D option I select my Marker3D from the scene which shows up as white (available) and nothing happens. Dragging and dropping the Marker3D onto the selection option also appears to do nothing.

### Steps to reproduce

Export an array of marker 3D's in a script
```
@export var marker_3d_array: Array[Marker3D]
```
attempt to select a marker 3d in the context options through the editor and nothing will select. Double clicking it makes the context menu disappear as expected but the option remains empty and behaves so in scripts.

### Minimal reproduction project

N/A

**Comment by capnm** [comment]
Take a look at the second box. It may be about the same issue.
![grafik](https://user-images.githubusercontent.com/4047289/230416816-153c6055-e19d-4de7-bf04-24655ff2d629.png)

**Comment by ZachAR3** [comment]
> Take a look at the second box. It might be about the same issue. ![grafik](https://user-images.githubusercontent.com/4047289/230416816-153c6055-e19d-4de7-bf04-24655ff2d629.png)

Appears to be similar, but for me I can still add and select nodes perfectly fine with every other type I have tried. It only appears to be tied to Marker3D.

**Comment by ZachAR3** [comment]
> Take a look at the second box. It might be about the same issue. ![grafik](https://user-images.githubusercontent.com/4047289/230416816-153c6055-e19d-4de7-bf04-24655ff2d629.png)

After further reviewing that issue this seems to be part of that issue, as it is still open and seems to affect large components of exported arrays. I will close this issue for the time being and hope that this is resolved when #62916 is fixed.
