### ISSUE TITLE
Plugins causing crashes when emitting signals with arguments in some devices

### ISSUE THREAD

**Issue by SirTodd** [godotengine/godot#75754]
### Godot version

4.0.2stable

### System information

Samsung SM-J701MT, GLES3

### Issue description

I've had 2 users reporting that my game is crashing on startup just after a few frames. Both users had similar devices: LG K10 and LG K12. Later on I discovered that my old phone (Samsung SM-J701MT) also had the same exact issue. Disabling plugins solved the issue entirely, but you could also run the app with plugins as long as you don't do any calls to the plugins.
I have over 100 users testing on higher end phones playing with the same plugins active and without any issues.

The only error I get is:
`Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x91df4018 in tid 14201 (GLThread 10481), pid 13924 (ploadsimulator2)`

After further investigation I've noticed that the crashes happen exactly at the moment a plugin emit a signal with an argument, if you remove the signals with arguments from the plugins it will no longer crash.

Note that I am using 4 different plugins, and all of them have the same exact issue. Changing the plugin library version does nothing (I've tried 4.0.2, 4.0 and 3.5 libraries).

### Steps to reproduce

Export any project with a plugin and emit a signal with an argument using the plugin.
High end devices won't be affected, but older devices will crash.

### Minimal reproduction project

Add the plugin to your export and run
`Engine.get_singleton("TestingPlugin").start()`
It will emit one signal without arguments and another with arguments. It will also log whenever that happens.
[TestingPlugin.zip](https://github.com/godotengine/godot/files/11172155/TestingPlugin.zip)

**Comment by SirTodd** [comment]
Update: Emitting the signal won't instantly crash if you are loading the game, but it will instantly crash as soon as the game loops begin. It will also instantly crash when emitting the signal while the game is loaded and looping. 
Looks like the crash happens a few frames after emitting the signal.

**Comment by Ajrarn777** [comment]
I encountered the same issue today.

It was with the Google Billing Plugin.

Callback signals without parameters were working fine.
But signal with 1 or more parameters make the app crash.

And something even more fun, after I reboot my phone, the issue disapear, for now... ???

**Comment by SirTodd** [comment]
Finally someone else noticed.
I've had to adapt all my plugins, removing the arguments from signals and storing data inside the plugin itself.

**Comment by Ajrarn777** [comment]
I think this is a very serious issue, but also unpredictable.

Since the time I have rebooted my phone, everything works perfectly..
It will be hard to find.

**Comment by Ajrarn777** [comment]
The more I think about it, the more it looks like an old **C++ uninitialized memory issue**. 

When Godot creates the List of function Parameters, there should be one variable not initialized.
If you are lucky, it will be zero,
If you are not lucky, it will be any value and the app may crashes.

When I reboot my phone, it reorganizes the memory, and I was lucky again. Until next time.

**Comment by shendo** [comment]
I have also been investigating what I believe to be the same issue.

In my case the reported crashes all appear to be devices running 32bit Android (Arm7 ABI) despite modern 64bit CPUs.  I believe manufacturers do this on 'budget' models that are memory constrained.  I haven't seen issue on Arm8 ABI, though this may just be coincidental.

I have been able to reproduce crash on Arm8 device (Samsung S8) by only exporting with arm7 libs, which should force to use 32bit.

@Ajrarn777 
It looks like the JNI calls back into libgodot, converting params from java types and dynamically allocating on the stack at:
https://github.com/godotengine/godot/blob/master/platform/android/plugin/godot_plugin_jni.cpp#L118

**Comment by Ajrarn777** [comment]
I think I have a hints, but it is only a wild guess at this time .

File : **\godot\platform\android\plugin\godot_plugin_jni.cpp**
```
JNIEXPORT void JNICALL Java_org_godotengine_godot_plugin_GodotPlugin_nativeEmitSignal(JNIEnv *env, jclass clazz, jstring j_plugin_name, jstring j_signal_name, jobjectArray j_signal_params) {
...
	Variant *variant_params = (Variant *)alloca(sizeof(Variant) * count);
	const Variant **args = (const Variant **)alloca(sizeof(Variant *) * count);

	for (int i = 0; i < count; i++) {
		jobject j_param = env->GetObjectArrayElement(j_signal_params, i);
		variant_params[i] = _jobject_to_variant(env, j_param);
		args[i] = &variant_params[i];
		env->DeleteLocalRef(j_param);
	}
```

Here, it uses **alloca( )**, which is **very awkward**, because it is use with C++ classes ( Variant ).
In this case, the constructor of the class Variant will not be called, which will left the class in a undefined state.
After that it use the **operator=** on a un-initialized class, and the result can be just anything.

Unless I miss something (and it is always possible), it looks like it can be our issue 😄

**Comment by shendo** [comment]
Yeah, in my debugging it was consistently crashing on the *variant_params* assignment, on arm7.

Looking through more of the engine code, it appears the macro [memnew_placement](https://github.com/godotengine/godot/blob/master/core/os/memory.h#L97) is used with stack allocated objects.

This seems to work for me:
```
 JNIEXPORT void JNICALL Java_org_godotengine_godot_plugin_GodotPlugin_nativeEmitSignal(JNIEnv *env, jclass clazz, jstring j_plugin_name, jstring j_signal_name, jobjectArray j_signal_params) {
...
        Variant *variant_params = (Variant *)alloca(sizeof(Variant) * count);
        const Variant **args = (const Variant **)alloca(sizeof(Variant *) * count);
 
        for (int i = 0; i < count; i++) {
                jobject j_param = env->GetObjectArrayElement(j_signal_params, i);
-               variant_params[i] = _jobject_to_variant(env, j_param);
+               memnew_placement(&variant_params[i], Variant(_jobject_to_variant(env, j_param)));
                args[i] = &variant_params[i];
                env->DeleteLocalRef(j_param);
        }
 ```
...but I am not confident enough to propose as a fix yet.

Interestingly,  it is already used in another func [callobject](https://github.com/godotengine/godot/blob/master/platform/android/java_godot_lib_jni.cpp#L463) with alloca/Variant in the JNI interface but not in *calldeferred* just below it.  So a few inconsistencies.

**Comment by shendo** [comment]
I'm feeling happier with my understanding of these changes now and making *nativeEmitSignal*, *callobject* and *calldeferred* consistent in their logic.

Will finish up a PR tonight, unless anyone had further comments, or has an android device with valgrind/msan configured that we can do some more verifiable tests first?

**Comment by Ajrarn777** [comment]
I have have an quick objection ;) 

Why not use a simple std::vector for this instead ?
Allocating on stack is certainly quicker, but by how much ?

Emitting a signal is a complex call, allocating the array of parameters is only a very small part of it.
If it save 0.1% by allocating on the stack instead of the heap, I will be suprised.

Like Donald Knuth said : Premature Optimization Is the Root of All Evil

Anyhow, your solution will probably fix the current problem.
But, even then, the class destructor will never be called.

The good news is, we are very near a solution 😄 

And you are right, this code is inconsistent in different places.
