### ISSUE TITLE
Minimum int value causes error when represented as code. 

### ISSUE THREAD

**Issue by ShawnMcCool** [godotengine/godot#75763]
### Godot version

4.0.1.stable.custom_build (NIX OS PKG)

### System information

Nix OS Linux

### Issue description

The minimum int value -9223372036854775808 when represented as code appears to be represented under the hood as something like ['-', 9223372036854775808] and 9223372036854775808 is higher than int's upper bounds. So, we get the error, "ERROR: Cannot represent 9223372036854775808 as a 64-bit signed integer, since the value is too large.".

### Steps to reproduce

Paste the text "-9223372036854775808" in the editor, look at the output window, wait 2 seconds to let it parse.

### Minimal reproduction project

-9223372036854775808

**Comment by Calinou** [comment]
> Paste the text "-9223372036854775808" in the editor, look at the output window, wait 2 seconds to let it parse.

*Where* do you paste this text in the editor?

**Comment by ShawnMcCool** [comment]
![image](https://user-images.githubusercontent.com/560749/230589957-e890f1bf-4401-41f9-816c-c034edcfe071.png)
[min_int_reproduction.tar.gz](https://github.com/godotengine/godot/files/11178020/min_int_reproduction.tar.gz)

**Comment by AThousandShips** [comment]
The fault is here:
https://github.com/godotengine/godot/blob/08c1b55862240e298a751ab4189e9a003f313be7/core/string/ustring.cpp#L2262

Will see about a fix should be trivial

**Comment by AThousandShips** [comment]
It's due to a broken implementation in:
https://github.com/godotengine/godot/blob/08c1b55862240e298a751ab4189e9a003f313be7/core/string/ustring.cpp#L2262

**Comment by ShawnMcCool** [comment]
yall straight up heroes in here.

**Comment by AThousandShips** [comment]
It appears yes that internally this is treated as unary minus and a literal, which does not work, this turns up in C++ as well at times and not sure how to work it out for this specific case, will take a dive later today
