### ISSUE TITLE
Error when assigning unnamed GDScript with exported variables 

### ISSUE THREAD

**Issue by anvilfolk** [godotengine/godot#75764]
### Godot version

master

### System information

W11

### Issue description

This issue only happens in `master`, it does not occur in 4.0.2 so it is a recent regression.

When assigning a script without a `class_name` and with at least one `@export` variable to a node in the scene tree (and every time you save the script after), you will get an error: `Class name cannot be empty`.

The error appears to originate from the first line of `Ref<Texture2D> EditorNode::get_class_icon(const String &p_class, const String &p_fallback)`:

`ERR_FAIL_COND_V_MSG(p_class.is_empty(), nullptr, "Class name cannot be empty.");`

### Steps to reproduce

Create a script with
```GDScript
extends Node

@export var x : int
```

Then assign it to a node in your scene. The error will occur. Remove the `@export` and it will no longer occur. Add it again, and it will, every time you save the file.

### Minimal reproduction project

N/A

**Comment by YuriSizov** [comment]
I guess it's a regression from https://github.com/godotengine/godot/pull/75472.

**Comment by anvilfolk** [comment]
> I guess it's a regression from #75472.

That sounds right, from the stack trace I was looking at it seemed to specifically be related to `_extension` being `null`, so hopefully a simple check ought to fix it?

**Comment by anvilfolk** [comment]
So the error is in line 2779:

https://github.com/godotengine/godot/blob/master/editor/editor_inspector.cpp#L2761-L2782

`script_name` is empty because `script_name = EditorNode::get_editor_data().script_class_get_name(scr->get_path());` returns empty since the path doesn't lead to a name. I guess here we want to default to something like `GDScript` or something?

I don't know enough about this part to be helpful :)

**Comment by anvilfolk** [comment]
I'm working on a fix for one :)

**Comment by capnm** [comment]
Here you get the same error even if you **assign a value**:
```
extends Node
@export var y := 1 :
	set(v):
		pass
```
Deselect / select the _Node_ with the attached script: 

ERROR: Class name cannot be empty.
   at: get_class_icon ([editor/editor_node.cpp:4471](https://github.com/godotengine/godot/blob/master/editor/editor_node.cpp#L4473))
...
