### ISSUE TITLE
Should _get_line_syntax_highlighting(line) in SyntaxHighlighter be a const function while get_text_edit() is not?

### ISSUE THREAD

**Issue by 3deathtoll** [godotengine/godot#75773]
### Godot version

4.0

### System information

Linux Mint

### Issue description

`_get_line_syntax_highlighting(line)` is declared as a const function. But when using GDExtension, it needs to call `get_text_edit()` which is not a const function. 
Link with: https://github.com/godotengine/godot-cpp/issues/1084

### Steps to reproduce

Try to use `get_text_edit()` from `_get_line_syntax_highlighting(line)` in a GDExtension.

### Minimal reproduction project

Not needed.

**Comment by YuriSizov** [comment]
`SyntaxHighlighter::get_text_edit()` can also be made const, it doesn't have any side-effects. We don't have a good consistency when it comes to using const, so feel free to correct such oversights with a PR :)
