### ISSUE TITLE
Issue : @export and all keyword about @export always has returned null value.

### ISSUE THREAD

**Issue by Irsil** [godotengine/godot#75775]
### Godot version

4.x stable

### System information

Windows 11

### Issue description

The code is this.
And I autoloaded this script in project settings.
```

extends Node2D

@export var dialogue_key : String
@export_file("*.json") var text_file

var dialogue_text = []
var area_active = false
var text_key

func _ready():
	dialogue_text = _load_scene_text()

func _load_scene_text():
	var file = FileAccess.open(text_file,FileAccess.READ)
	print_debug(file)
	var content = JSON.new()
	content.parse(file.get_as_text())
	return content.get_data()
	
func _input(event: InputEvent) -> void:
	if area_active and event.is_action_pressed("action"):
		SignalBus.emit_signal("display_dialogue_ayla", dialogue_key)

func _on_area_entered(area: Area2D) -> void:
	area_active = true

func _on_area_exited(area: Area2D) -> void:
	area_active = false
```
	

In this code, I input dialogue_key and text_file, but it does not work because dialogue_key and text_file is always null.

### Steps to reproduce

I was making dialogue systems which was based in this tutorial.
https://youtu.be/Ur9j3c5_of0

I realized that if I add some dialogue_keys, it is called several times because it has autoloaded scene.
So I was making dialogue system again, which for each node has script file and dialogue key.
And suddenly, it didn't work.
At first, I thought it was my fault, and I changed some logics, variables value, etc....but it still did not work.
I even thought it was just FileAccess.open function was invalid, but now I know it works well, because the error script was this : 
Invalid type in static function 'open' in type 'FileAccess'. Cannot convert argument 1 from Nil to String.

I used print_debug() function, and all variables which I used @export keyword had null value.
It is @export keyword's bug, I think.

### Minimal reproduction project

[project.zip](https://github.com/godotengine/godot/files/11217078/project.zip)

**Comment by dalexeev** [comment]
See:

* #74188
* #75555

For now, use a type hint and/or an explicit initial value.

Also note that before `_ready` (more precisely, before `NOTIFICATION_SCENE_INSTANTIATED`) exported variables have initial values from the script, and not the ones you set in the Inspector.

**Comment by KoBeWi** [comment]
Your MRP does not contain any scripts.

**Comment by Irsil** [comment]
Just a moment please, I'll edit about it.

**Comment by Irsil** [comment]
I don't know how to open this downloaded-project...so I put in zip folder my whole project. It's my first time to write issues and programming godot... I'm so sorry. If you have any problem, please tell me about that.

**Comment by KoBeWi** [comment]
Well, full project is not very helpful in this case 🙃
You could've just zipped the affected `.gd` files, or better, make new ones that contain only the bugged code. Or provide a snippet  that doesn't reference your classes, so it can be copy-pasted anywhere (the code you pasted in the OP uses e.g. SignalBus, which is a custom class).

**Comment by Irsil** [comment]
Oh, I had erased that json folder....So it doesn't exist. I edited the zip folder, and in zip, there will be some script file and scene which you said.

**Comment by KoBeWi** [comment]
The project still does not work. The only scene can't be opened due to missing dependencies and the script which should display the issue isn't attached anywhere.

The project should be runnable and, perfectly, it should show the error once you run it.

**Comment by Irsil** [comment]
Oh....I'm so sorry about that...My project was perfectly changed after showing this issue because I had to develop my project.
I don't know what I have to do. Still my project has this issue so I can't use export keyword. Would you mind if I send whole project with your e-mail??

**Comment by dalexeev** [comment]
To create an MRP in cases like this, you can try the following approach: create a copy of your project and iteratively remove parts of it that are not likely to be related to the problem. If after the next step the problem disappeared, go back and try to remove something else. If the problem persists, continue to iteratively remove parts and test for the problem until the MRP is small enough to be analyzed by someone unfamiliar with your project.

**Comment by adamscott** [comment]
@Irsil I cannot run your project, unfortunately. There's a file missing and the engine returns a parse error.
Can you make sure this is a minimal reproduction project? There's a lot of assets for a script issue in your project.

**Comment by Irsil** [comment]
I saw when the assets are missing, some alert window is creating. Uhm...actually, I don't know why this problem happens. I'm beginner so I just saw tutorial and followed it. I don't know what problem is happened, just knowing can't use export keyword in this project because all export keyword started returning initial value. So I couldn't find what script is exactly the reason, although I had debugged and printed console with print_debug method. I can't understand what is minimal reproduction of project. I checked the project.godot in zip folder many times and it worked when I extracted the zip. When I just opened the project.godot in zip folder, there was alert that can't find the Game.tscn. Is the problem you suffer the same thing?

**Comment by KoBeWi** [comment]
> I checked the project.godot in zip folder many times and it worked when I extracted the zip.

What do you mean it worked and where did you extract it? It should be extracted into a new directory and pressing F5 should start without errors. The project loads in the editor, but does not run.

**Comment by Irsil** [comment]
Its error was happened in autoloaded script, because I fixed the script file path. I'm so sorry about that. I checked it and changed the zip folder. It'll work now.

**Comment by Irsil** [comment]
When you run the project, it seems like that there is no problem because I took out the export keyword and just coded in initialized variable and autoloaded script. But if you add the script code including export variables in any gd.file and using print_debug function, it has always return null value. I recommend that adding export variable in 'tool_ui_script.gd' and using exported variable in test value.

**Comment by adamscott** [comment]
> When you run the project, it seems like that there is no problem because I took out the export keyword and just coded in initialized variable and autoloaded script. But if you add the script code including export variables in any gd.file and using print_debug function, it'll always return null value.

The idea is to join a MRP that has the problem. If more work is needed to reproduce your issue, it defeats the purpose of a MRP. The maintainers and contributors must be able to reproduce your issue easily.

Please make sure that the issue is found in your example project.

**Comment by Irsil** [comment]
But...it didn't work when I wrote '@export var variable_name' several days ago. And I had not even found not-typed-variable-error several days ago. I could write '@export var variable_name' that time..Now when I have to write '@export var variable_name:Type'. And editor now enforces me to write this typed variable to make error if I don't follow that grammar. I couldn't even write @export keyword by several days because of this problem...and now I can use the keyword when I type the exported variable. Did it have bug-fixed?? What should I do now? Should I close this issue?? I am sorry to tell this thing, I really don't know about this...

P.S/I'm so sorry, I didn't know about MRP...I knew yesterday that it means minimal reproduction project, and that there are several criteria to register the MRP. I'm sorry I didn't know about this. But I have not back my project up by version, so I can't register that time's project....I'm so sorry. It's all my fault.

**Comment by dalexeev** [comment]
> Now when I have to write '@export var variable_name:Type'. And editor now enforces me to write this typed variable to make error if I don't follow that grammar.

You can specify an initializer value instead of/together with the type. If you don't specify either, the Inspector can't figure out what type of field to show, so we don't allow it at the GDScript level.

```gdscript
@export var a: String = ""
@export var b: String
@export var c = ""
#@export var d # This is disallowed.
```

**Comment by Irsil** [comment]
OK. I'll use that grammar from now on. Thanks for your advice. It seems like bug has disappeared by changing grammar of gdscript. I think it's better to close the issue. Thank you so much for your kindness in participating in this issue!!
