### ISSUE TITLE
Shared texture path setting missing in Project Settings.

### ISSUE THREAD

**Issue by EzraT** [godotengine/godot#7579]
**Operating system or device - Godot version:**
Godot v2.1.1.stable.official
Ubuntu Gnome 16.04 - x86_64
NVIDIA GeForce GTX570 - Driver version: 367.57

**Issue description** (what happened, and what was expected):
The "Import 3D scene" window lists an option to import textures to a shared path in the project tree, but there is no option present in the Project Settings window to specify this path anywhere.

See [this Q&A post](https://godotengine.org/qa/11553/how-the-shared-texture-import-option-the-import-scene-window) for further info.
And [this bit of documentation](http://docs.godotengine.org/en/stable/tutorials/3d/importing_3d_scenes.html#source-target-paths) that describes this feature.

**Steps to reproduce:**
Open the "Import 3D scene" window, set the "Target Texture Folder" to the "Shared" option, and then notice that there is no way to specify this path in the Project Settings. (Either that or I'm overlooking something, would really appreciate it if someone could explain how this works.)

**Comment by bojidar-bg** [comment]
GitHub did something strange, and somehow didn't close this issue.... (reopen if I'm wrong)
