### ISSUE TITLE
Normal Buffer not working as expected if the current scene has no environment

### ISSUE THREAD

**Issue by uberfig** [godotengine/godot#75794]
### Godot version

4.0.2 stable

### System information

issue tested on win10 with ryzen 7 and rx 6600, win11 with ryzen 7 and gtx 3050

### Issue description

When creating a screen reading post processing shader, the normal buffer functions correctly in the editor, but does not seem to be functioning as expected in debug, producing only a solid colour when run. I am unsure if this behaviour is intended, but if so, I feel it should be properly documented.

Running correctly in editor:
![image](https://user-images.githubusercontent.com/71034402/230672620-fc5e4baf-c12e-4755-b7a2-206087459307.png)

Solid colour in debug:
![image](https://user-images.githubusercontent.com/71034402/230672489-d9c29755-c2d3-4e72-9ea0-355148e916fe.png)

### Steps to reproduce

*this shader should be attached to a MeshInstance3D quadmesh*
minimal shader to reproduce:

```glsl
shader_type spatial;
render_mode unshaded, cull_disabled;

uniform sampler2D NORMAL_TEXTURE : hint_normal_roughness_texture, filter_linear_mipmap;

void vertex(){
	VERTEX *= 2.0;
	POSITION = vec4(VERTEX, 1.0);
}

void fragment(){
	ALBEDO = texture(NORMAL_TEXTURE, SCREEN_UV).rgb;
}
```

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
What happens if you remove mipmaps from the filter?

**Comment by AshuraDX** [comment]
Same issue exists on Version 4.0., using Forward+ Renderer

**Comment by AshuraDX** [comment]
> What happens if you remove mipmaps from the filter?

My tests were run using filter_nearest initially, same issue.

**Comment by AshuraDX** [comment]
So I just discovered something strange!

If I disable the preview Environment in the editor, then resize the Preview Viewport vertically - I get the same solid color screen as I get when running the scene:

![grafik](https://user-images.githubusercontent.com/9929644/230677387-b78cf707-88f6-45aa-be53-7b7efe073ef0.png)

adding a basic WorldEnvironment Node to the scene fixes this again:
![grafik](https://user-images.githubusercontent.com/9929644/230677490-0137f17e-d42b-4c9b-8bce-807d3da0722c.png)

including when running the project!
![grafik](https://user-images.githubusercontent.com/9929644/230677533-ce5617d9-485a-4f8b-9620-0cba3637efda.png)

**Comment by uberfig** [comment]
Can confirm, adding the world environment fixed the problem on my end as well!

**Comment by uberfig** [comment]
Closing issue as a solution has been found

**Comment by AThousandShips** [comment]
This is still a bug and needs to be investigated, I don't think the normal texture not working is a normal thing to expect without an environment, this should probably be reopened

**Comment by Lexpartizan** [comment]
May I ask how to make the normals from this texture be in world space? Because my colors change when I move the camera.

**Comment by cufbom** [comment]
I found this issue very frustrating to debug, if it's a limitation of the renderer that the screen space normals aren't available without a world environment it would be good if it was mentioned in the shader docs.
