### ISSUE TITLE
Can't disconnect a connection after making an instance local

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#75801]
### Godot version

4.0.2

### System information

Windows 10 x64

### Issue description

Regression from #69661
The PR added a transient flag that makes instantiated connections uneditable. However when you make the instance local, the flag leaks to the local scene, making the connection impossible to remove other than by manually editing the tscn file.

### Steps to reproduce

1. Make scene A
2. Connect some signal from the root node
3. Make scene B
4. Instantiate A inside B
5. Right click A and use "Make Local"
6. You can no longer disconnect

### Minimal reproduction project

[BuggersDisconnectioners.zip](https://github.com/godotengine/godot/files/11181849/BuggersDisconnectioners.zip)

**Comment by haruyou27** [comment]
![image](https://user-images.githubusercontent.com/68549456/230725750-b3f0960f-9d26-4ad1-8ca8-cbc0d9bcd24c.png)
You can still disconnect the signal using the _Disconnect_ button at the bottom, even if you don't _Make Local_.
