### ISSUE TITLE
Add known issues to 2.1 docs

### ISSUE THREAD

**Issue by RandomShaper** [godotengine/godot#7580]
Thera are some bugs/inconsistencies in how angle functions works (`atan2`, `angle_to_point`, etc.) that won't be fixed until 3.0 for compatibility.

The thing is that I find sometimes digging among issues to recall which ones were affected.

What I am proposing is adding a _Known Issues_ section to the 2.1 docs with a summary about this so it gets documented and easily checkable.

**Comment by karroffel** [comment]
Isn't this more appropriate in the [godot-docs](https://github.com/godotengine/godot-docs) repo?

**Comment by bojidar-bg** [comment]
Migrated.
