### ISSUE TITLE
PhysicsDirectBodyState3D.get_local_contact_position sometimes returns incorrect position, scene order dependent

### ISSUE THREAD

**Issue by ilmagico** [godotengine/godot#75803]
### Godot version

4.0.1.stable.mono.official.cacf49999, 4.0.2.stable.mono.official.7a0977ce2

### System information

Manjaro Linux

### Issue description

When querying the local position of a collision of a `RigidBody3D`, the reported collision is supposed to be in "local" coordinates, that is, relative to the `RigidBody3D`'s origin (or at least, that's how I interpret it, the documentation doesn't say anything more than "local").

Instead, it seems this depends on the order of the two colliding objects in the scene: if the "other" colliding object comes after the `RigidBody3D`, then the reported position is local, else if the `RigidBody3D` comes after in the scene, the reported position is ... well, it's not local to the rigid body. My suspicion is that it's local to the other object, but I didn't dig further.

The minimal repro project has a ground plane and a rigid body, and it prints the collision position every iteration.

Minimal repro project screenshot when rigid body comes after ground plane (as attached):
![Godot_BugRepro_Screenshot_20230407_183145](https://user-images.githubusercontent.com/7019416/230698010-f01be61d-3c3d-49bb-a1e1-fbcfe2623a1c.png)

Notice the reported position is `(-2, 0.039999, -2)`, while if it was local to the rigid body it should be `(0, -1, 0)`.

Minimal repro project screenshot when rigid body comes first (just moving the rigid body before the ground plane):
![Godot_BugRepro_RigidBody3d_before_GroundPlane_Screenshot_20230407_183145](https://user-images.githubusercontent.com/7019416/230697956-d9314d49-f466-44c0-89c7-04258089915e.png)

### Steps to reproduce

1. Create a `CSGBox3D` or other collision enabled node
2. Create a `RigidBody3D`, place it right after the previous one in the scene
3. Create a script for the `RigidBody3D`
4. In the script, implement `_integrate_forces` and try using `state.get_contact_local_position`, e.g.:
    ```
    func _integrate_forces(state):
        for k in range(state.get_contact_count()):
            var collisionPos = state.get_contact_local_position(k)
            print("\t Collision " + str(k) + ": " + str(collisionPos))
   ```

### Minimal reproduction project

[BugReproRigidBodyCollision.zip](https://github.com/godotengine/godot/files/11182298/BugReproRigidBodyCollision.zip)

**Comment by rburing** [comment]
Should be fixed by https://github.com/godotengine/godot/pull/58880 which is due for a rebase hopefully this weekend.

**Comment by ilmagico** [comment]
Awesome, thanks @rburing!
