### ISSUE TITLE
Quick filter files: possibly broken or just needs documentation

### ISSUE THREAD

**Issue by tetious** [godotengine/godot#7582]
**Operating system or device - Godot version:**
MacOS El Capitan, tested with Godot 2.1 stable and current 2.1 branch git.

**Issue description:**
I'm not sure if I'm just misunderstanding what this menu item is supposed to do, but I was looking for a way to quickly open a file, and found the option "quick filter files..." in the scene menu. Selecting it seems to do nothing. At least nothing obvious. :) 

I'm not sure if it is broken or I just don't know what it is supposed to do. I wasn't able to find any mention of it in the docs or via Google.

**Comment by bojidar-bg** [comment]
Would be nice if we can confirm for 2.2/master.

**Comment by tetious** [comment]
It looks like it was commented out. I'm not sure why. It looks like it was commented out in its initial checkin. My guess is that it was a mistake.

Anyway, it seems to work fine in limited testing so I made a PR. :)
