### ISSUE TITLE
REDUNDANT_AWAIT warning not reported

### ISSUE THREAD

**Issue by ajreckof** [godotengine/godot#75824]
### Godot version

4.1.dev(c151d3231f)

### System information

MacOS 13.4 M1 Pro

### Issue description

This a regression from #74949. The warning is not trigerred even when it should be. it wasn't detected before as the test did not raise an error until more recently, but the warning was indeed already not present since then. 
<img width="712" alt="Capture d’écran 2023-04-08 à 14 35 52" src="https://user-images.githubusercontent.com/66184050/230723775-503faf9c-4bf2-4a79-997f-94604262d880.png">

Edit : 
The test seems to pass consistently I don't know why it didn't pass before but the warning is still not raisede where it should. 
The difference between this and the test case is the presence of the return type hint. Without it, it won't raise the warning.

### Steps to reproduce

copy paste this code it should raise a warning just as stated in the test case but it isn't
```
func test():
	print(await not_coroutine())


func not_coroutine():
	return "awaited"
```

### Minimal reproduction project

N/A

**Comment by dalexeev** [comment]
It is correct. Without the return type hint, there is no warning, as the function may return a signal. See https://github.com/godotengine/godot/issues/74879#issuecomment-1471382046
