### ISSUE TITLE
Some `NOTIFICATION_*` constants collide by sharing the same integer value

### ISSUE THREAD

**Issue by Bromeon** [godotengine/godot#75839]
### Godot version

4.0.2-stable

### System information

N/A

### Issue description

Godot uses `NOTIFICATION_*` constants across different classes to identify different types of lifecycle callbacks. Since they are defined in different classes, they are not enums, but resolve to `int` in GDScript. At the moment, some of these constants share the same value, although they mean different things.

Examples I've found (not necessarily exhaustive):
```js
30:   CanvasItem.NOTIFICATION_DRAW               Node.NOTIFICATION_NODE_RECACHE_REQUESTED      Window.NOTIFICATION_VISIBILITY_CHANGED
32:   CanvasItem.NOTIFICATION_ENTER_CANVAS       Window.NOTIFICATION_THEME_CHANGED
41:   Control.NOTIFICATION_MOUSE_ENTER           Node3D.NOTIFICATION_ENTER_WORLD
42:   Control.NOTIFICATION_MOUSE_EXIT            Node3D.NOTIFICATION_EXIT_WORLD
43:   Control.NOTIFICATION_FOCUS_ENTER           Node3D.NOTIFICATION_VISIBILITY_CHANGED
44:   Control.NOTIFICATION_FOCUS_EXIT            Node3D.NOTIFICATION_LOCAL_TRANSFORM_CHANGED
50:   Container.NOTIFICATION_PRE_SORT_CHILDREN   Skeleton3D.NOTIFICATION_UPDATE_SKELETON
```

It can be argued that this may not be an issue as long as those collisions happen in different inheritance branches (i.e. never directly between a base and derived class).

However, the first example above even violates that: both `CanvasItem` and `Window` inherit from `Node`, so there are simultaneously two different notification constants of the same value in scope.
```js
30:   
  CanvasItem.NOTIFICATION_DRAW
  Node.NOTIFICATION_NODE_RECACHE_REQUESTED 
  Window.NOTIFICATION_VISIBILITY_CHANGED
```

This can be problematic in the virtual function `Object::_notification(int what)`, which can be overridden by the user. There is no way to distinguish such notifications at the moment.

---

The open question is whether only this specific bug should be fixed, or collisions should be avoided in general. Given a 32-bit-integer, it's probably reasonable to never have overlapping values; yet backwards-compatibility (mostly with GDExtension) might be a factor in the decision.

### Steps to reproduce

See above.

### Minimal reproduction project

N/A

**Comment by Bromeon** [comment]
`NOTIFICATION_NODE_RECACHE_REQUESTED` was removed, fixing the worst conflict.

The other duplications are less problematic, as they appear in disjoint inheritance branches. Is the decision to keep them as-is?

**Comment by akien-mga** [comment]
I think so. For 5.0 we should look into a system that avoids such overlaps, but for now it would be worth it IMO to break compat in those key notifications if there's no actual problem with reusing the same number in separate inheritance chains.
