### ISSUE TITLE
Multiplication of integer and float gives wrong result

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#75832]
### Godot version

4.1 61630d4

### System information

Windows 10 x64

### Issue description

```GDScript
var a := 1
a *= 1.0
prints("Result:", a)
```
Produces
```
Result: 4607182418800017408
```

Does not happen in 4.0 branch.

### Steps to reproduce

1. Run the code above
2. Observe the result

### Minimal reproduction project

N/A

**Comment by logzero** [comment]
4607182418800017408 is 1.0 reinterpreted as int

**Comment by AThousandShips** [comment]
Note that this *only* affects the `*=` operator, not `a = a * 1.0`

**Comment by AThousandShips** [comment]
This calls for adding some tests along with a fix for this

**Comment by AThousandShips** [comment]
As that PR seems to just have been a performance improvement I'd suggest just reverting it and adding some tests and attempting to reimplement it later
