### ISSUE TITLE
2D Sprites get quite blurry and leave trails when moving

### ISSUE THREAD

**Issue by hakro** [godotengine/godot#75842]
### Godot version

4.0.2

### System information

PopOs 22.04, Any renderer, NVIDIA Corporation GP107GLM, Driver Version: 525.89.02

### Issue description

Moving a sprite around the screen is quite blurry. Kinda like motion blur, but unwanted. This happens in all 3 renderers.
It feels like the screen does not get cleared fast enough after each frame, leaving a trail that persists for a few frames.

Here is a video where it's a bit noticeable, but it's actually quite worse than that.

https://user-images.githubusercontent.com/3624853/230750128-18d3131c-c4b6-4fa0-84ff-3d04c37f0d6b.mp4

This happens with a very simple project, that uses the CharacterBody2D script template, with all default settings.
Toggling vsync in project settings does not help.

### Steps to reproduce

Just add a static body, and a characterbody2D with the built-in script template for platformers, and then move around.

### Minimal reproduction project

[Godot4Test.zip](https://github.com/godotengine/godot/files/11184632/Godot4Test.zip)

**Comment by smix8** [comment]
Looks like just the unhealthy-for-quality mix of using stretch mode + low res texture + down scaled texture + physics tick rate for visual updates + physics jitter "fix".

With all those removed / reset / fixed the image quality and movement is perfectly crisp and fluid.

**Comment by rainlizard** [comment]
It might be a result of your monitor, moving something around a dark background can leave a trail, smearing/ghosting on VA panels. Try the UFO test: https://www.testufo.com/

Video about the subject : https://www.youtube.com/watch?v=jdP4pw3Vaus

**Comment by Calinou** [comment]
This is monitor ghosting, which is a hardware issue that Godot can't resolve.

**Comment by partykapartyka** [comment]
> > This is monitor ghosting, which is a hardware issue that Godot can't resolve.
> 
> if this is an monitor issue how he managed to save video.

Exactly. I'm having the same issue working on Macbook M1 Godot 4.2.2

**Comment by rainlizard** [comment]
> > This is monitor ghosting, which is a hardware issue that Godot can't resolve.
> 
> if this is an monitor issue how he managed to save video.

Like I said, if you pause the video then you can't see the trail. This is proof that the video has not recorded a trail. If the trail was real then it would be recorded in the video.

So what you're seeing in the video is just the monitor ghosting yet again - you'll see the monitor ghosting regardless of whether it's a video or not.

Don't worry so much about it, after you add graphics to your game then it becomes less and less noticeable.
