### ISSUE TITLE
ResourceLoader.load_threaded_request throws Parse Error when loading multiple resources

### ISSUE THREAD

**Issue by MWippich** [godotengine/godot#75841]
### Godot version

4.0.2

### System information

Windows 10, AMD Ryzen 7 3700X 

### Issue description

When using `ResourceLoader.load_threaded_request(path)` to load mulitple resources simultaneously, some resources are not properly loaded and the error `load: res://resources/test - Copy (11).tres:3 - Parse Error: [ext_resource] referenced nonexistent resource at: <path> <C++ Source>  scene/resources/resource_format_text.cpp:490 @ load()` is thrown. (when the referenced resource at the path is obviously present). 

In godot 4.0.1-stable this error doesn't occur. 

Seems related to previous issue [[#71726](https://github.com/godotengine/godot/issues/71726)]

### Steps to reproduce

start loading a bunch of resources using `ResourceLoader.load_threaded_request(resource_path)`.

In the minimal reproduction project, simply run the main scene.

### Minimal reproduction project

[ResourceLoaderMRP.zip](https://github.com/godotengine/godot/files/11184539/ResourceLoaderMRP.zip)

**Comment by MrBBBaiXue** [comment]
Same issue here.
![A{O)F46U)8KT$JS(TQ_5MG5](https://user-images.githubusercontent.com/17956756/231656983-f545fb28-5f09-4bc4-b4a4-a0dcb1877bac.jpg)
When a scene containing multiple resources, this issue reproduces stablely.

[MRP]
Clone https://github.com/bakneko/godot-template and run in godot-4.0.2.
Check core/class/loader.gd

**Comment by venilark** [comment]
Same here.

**Comment by akien-mga** [comment]
Probably fixed by #74405.
