### ISSUE TITLE
Unexpected panning effect in 2D editor.

### ISSUE THREAD

**Issue by LGFGCODER** [godotengine/godot#75859]
### Godot version

4.0.2.stable (Android)

### System information

Android 8.0.0

### Issue description

It is a problem that arises when you want to move, rotate or scale a 2D node in Godot Android editor.  Attempting to use any of these three modes with your touch screen in the 2D editor will cause the view to scroll and prevent you from modifying the node.  Even if you use `pan mode`, the view will scroll more than normal.

### Steps to reproduce

- Create a new project.

- Add a Node2D or Sprite2D to 2D editor.

- Try using `move mode` to move your node to a new position in your 2D scene.

(Use an Android device with a touch screen for the best chance of finding the problem)

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
Sounds like something fixed by #75113
