### ISSUE TITLE
Ability to group node icons in Scene dock to drop-down menu.

### ISSUE THREAD

**Issue by MrMaidx** [godotengine/godot#7586]
I like to have layout in which I have two docks next to each other on the right side of the window.
But this layout means these docks need to be thin. And when Scene dock is too thin and nodes in it have too many icons their names are not visible.

![scene](https://cloud.githubusercontent.com/assets/8977194/22150975/43eb8aee-df1c-11e6-8c82-72eeb8d57b6d.png) 

So my feature request is a mode in which these icons would be in some kind of drop-down menu. It doesn't have to be default behavior, but it might be a nice feature switchable in the engine settings.

**Comment by eon-s** [comment]
Maybe a global toggle to hide icons on the tree?
Usually one does not care if node is in group, is a scene, is locked or is visible.

**Comment by MrMaidx** [comment]
I care about those properties. But they just occupy a lot of space. :)

**Comment by hubbyist** [comment]
What about making them stack over each other by covering half of the one before it

     +--+--+--+----+
     |  |  |  |    |
     +--+--+--+----+

When one is hovered it will be brought to foreground. Thus can be clicked safely.

**Comment by MrMaidx** [comment]
Sounds also cool. Or maybe for start just make those icons closer to each other.
Also... when you hover the row with a node a popup with "Instance:" and "Type:" is brought up. I think that value "Name:" could also be there.
I think that these changes wouldn't be much work, but they would help my work flow tremendously.

**Comment by eon-s** [comment]
@MrMaidx I mean something like this, maybe with a dropdown menu with multiple selection instead, to check the icons you want to see

![hideicons](https://cloud.githubusercontent.com/assets/10215987/22203696/0adead16-e14d-11e6-9f3c-77fdff026386.png)

**Comment by MrMaidx** [comment]
This issue was solved partially by #8238. Just moving icons closer together is probably enough.

**Comment by volzhs** [comment]
@akien-mga it would be good 2.1.3-rc2 has #8238.
I didn't notice this issue.

**Comment by volzhs** [comment]
@akien-mga @MrMaidx how about closing this issue until somebody suggests better idea or open another issue for it?
