### ISSUE TITLE
Strange cursor icon behavior when panning in the 2D view

### ISSUE THREAD

**Issue by TheSpydog** [godotengine/godot#75871]
### Godot version

4.0.2

### System information

Windows 10

### Issue description

I noticed there are two strange cursor interactions when panning in the 2D view via holding the spacebar and click+dragging. (I suspect they're directly related, which is why I only opened one issue.)

1. If you hold the spacebar in the 2D view, your mouse cursor does not change to the "panning" icon until you move your mouse. I expected the cursor icon would change as soon as the spacebar press was detected.
2. If you hold the spacebar, click and drag in the 2D view, and then release the mouse button, the cursor icon remains as the "panning" icon whenever it is hovering over the 2D view. It only returns to normal once you click somewhere in the 2D view. I expected the cursor to return to normal as soon as the spacebar was released.

These issues are fairly minor but they confused me as a new user trying to understand how panning works in the editor.

### Steps to reproduce

See above.

### Minimal reproduction project

N/A

**Comment by MewPurPur** [comment]
My mouse cursor also doesn't wrap around when I do the spacebar + drag thing.

**Comment by ivandortulov** [comment]
I just tested this and the issue appears to be exactly what @TheSpydog has described.

**Comment by jbcolli2** [comment]
I'd like to take a crack at this one, if no one else is working on it.
