### ISSUE TITLE
CanvasItem shader light function does nothing when not covered by a Light2D

### ISSUE THREAD

**Issue by conradhappeliv** [godotengine/godot#75872]
### Godot version

v4.1.dev.custom_build [c1128e911]

### System information

Windows 11, Nvidia 3070, any renderer

### Issue description

I would expect CanvasItem shader `light` functions to always have an effect, but they only seem to have any effect on pixels that are covered by a Light2D. AFAICT, this leaves us with limited options for "bypassing" default lighting behavior unless we overlay a Light2D over every texture that would need a light shader (which I'm pretty sure would have performance downsides)

### Steps to reproduce

1. Create a CanvasItem (e.g. ColorRect)
2. Add a canvas_item ShaderMaterial to it
3. Add a light function to the shader

Example shader (should make the item fully-lit always):
```
shader_type canvas_item;

void light() {
    LIGHT = vec4(1.0);
}
```

5. Observe: the light shader has no effect.
6. Now add a Light2D that covers the CanvasItem.
7. Observe: the light shader now works as intended (only on pixels covered by the Light2D).

![image](https://user-images.githubusercontent.com/4420888/230796535-29d2bdc8-da90-4036-a5a3-72a8000fa643.png)

### Minimal reproduction project

[lightshaderwithnolights.zip](https://github.com/godotengine/godot/files/11186306/lightshaderwithnolights.zip)

**Comment by AThousandShips** [comment]
I'm assuming this is specifically done *because* it would otherwise have performance issues if light code was run everywhere

**Comment by conradhappeliv** [comment]
Fragment shaders were actually my first intuition, but my problem was that I'm using a CanvasModulate (most commonly set to fully black) to darken the scene, and that would get applied _after_ the fragment shader runs (which I didn't want for specific pixels). Thus, the next logical step in my mind was to use a light shader to "override" the darkness.

For some reason, I had been under the assumption that colors set in fragment shaders were limited in range from 0-1, but in the process of writing this comment, I realized that was probably not true and that I could "bypass" the darkness by outputting a very large color value. I think that should work for me.

Thanks for taking a look and for the guidance!

**Comment by clayjohn** [comment]
> For some reason, I had been under the assumption that colors set in fragment shaders were limited in range from 0-1, but in the process of writing this comment, I realized that was probably not true and that I could "bypass" the darkness by outputting a very large color value. I think that should work for me.

On that note, the output of the CanvasItem shader _is_ limited to the 0-1 range (but that is after applying the fragment shader and all iterations of the light shader).

Good luck with your project!

**Comment by rpahut** [comment]
> outputting a very large color value
This might not work the same on different hardware or software.

Instead, I've seen [this solution](https://godotshaders.com/shader/modulate-before-light/) , to modulate conditionally in fragment shader instead of using CanvasModulate. Depending on how illuminated nodes are used, they could also be placed in a separate canvas.
