### ISSUE TITLE
Unable to change scale in viewport to fill game window

### ISSUE THREAD

**Issue by Dente222** [godotengine/godot#75876]
### Godot version

4.0.2

### System information

Win10, Radeon RX 6650 XT, Vulkan

### Issue description

So I tried to redo some basics for the new game like changing in-game resolution but have come across the fact that there is no way for Godot to expand its resolution to match one of the viewports if my resolution is lower than the one set in Project Settings.

Instead of that, on full screen, I have a game window of 800x600 while the max resolution can be set to 1920x1080.
Problem is that for some odd reason, if my resolution is lower than Max in full-screen mode, the game window will be displayed with the set resolution in the top left corner while the rest of the space is black...

I tried to find a way to fix this by changing project settings and tweaking the viewport and canvas node, but no results... 
Here is an example with a full screen set to 800x600 resolution: https://imgur.com/A9BJWz9

### Steps to reproduce

1. Make 2D controll node and add something just to make it visible
2. Change Viewport resolution in project settings to any (For example 1920x1080)
3. Load game with that resolution on fullscreen 
4. Now change the resolution in game with `get_viewport().set_size(Vector2(res_width, res_height))`

### Minimal reproduction project

[Resolution Bug.zip](https://github.com/godotengine/godot/files/11187150/Resolution.Bug.zip)

Here is example.
I have set it already to be full screen at 1920x1080 so all it has to be done is:

1. Run project in godot
2. Click options button "Its set to 1.5sec delay so be patient"
3. Pick any resolution from drop down menu
4. Press apply button at the bottom of the screen

That will be it, feel free to play around with it.
Everything is in Options.gd and Settings_Panel.gd

**Comment by Calinou** [comment]
See the [Multiple Resolutions demo](https://github.com/godotengine/godot-demo-projects/tree/master/gui/multiple_resolutions) for advice on setting up a project that supports multiple resolutions.

**Comment by Dente222** [comment]
> See the [Multiple Resolutions demo](https://github.com/godotengine/godot-demo-projects/tree/master/gui/multiple_resolutions) for advice on setting up a project that supports multiple resolutions. I've tested that demo with the Compatibility rendering method and can confirm it works there.

I checked your example and re-adapted your method into my game and its working fine with canvas and viewport
All I needed apparently was this ``get_viewport().content_scale_size = base_window_size`` and the items from OptionsButton
besides that, its good to know that now we don't have to code items into it and instead we can use build in index :D

Also good to know that it has to use different method instead of the old one soo thats a good thing

**Comment by Dente222** [comment]
Sorry to reopen that but I have actually find a problem in my code that was causing that and it was this
``get_window().set_size(Vector2(base_window_size))`` Apparently, somehow setting size for window in general also sets it in full screen mode causing my game to limit it to the area of defined resolution.

I don't really know if that is an actuall bug or intended design but at leas I know what was the actual cause
