### ISSUE TITLE
Reporting node configuration warnings not working

### ISSUE THREAD

**Issue by Vennnot** [godotengine/godot#75883]
### Godot version

4.0.2

### System information

Windows 10 GLES3

### Issue description

I followed the documentation here: https://docs.godotengine.org/en/stable/tutorials/plugins/running_code_in_the_editor.html

under the "Reporting node configuration warnings" section but the code does not seem to work. I fixed the .size() for .length() in my code but I cannot get warning to show up in the editor (this is a separate issue linked below). 

Linked here: https://github.com/godotengine/godot-docs/issues/7143

### Steps to reproduce

1. Create a new project.
2. Create an empty node and script
3. set @tool and extends Node at the top
4. Copy paste the contents of https://docs.godotengine.org/en/stable/tutorials/plugins/running_code_in_the_editor.html under the warning section below the above code
5. Reload and observe warnings not work

### Minimal reproduction project

[node.zip](https://github.com/godotengine/godot/files/11188970/node.zip)

**Comment by YuriSizov** [comment]
This example is outdated, the method has been renamed to `_get_configuration_warnings`. See https://docs.godotengine.org/en/stable/classes/class_node.html#class-node-method-get-configuration-warnings

**Comment by Vennnot** [comment]
Thank you so much Yuri! I really appreciate it.
