### ISSUE TITLE
Raycast to Area not adhering to Layer/Mask

### ISSUE THREAD

**Issue by thebluefish** [godotengine/godot#7589]
**Operating system or device - Godot version:**
2.1.1 STABLE
3.0-alpha

**Issue description:**
Raycast nodes have a Layer Mask property to filter which CollisionObjects are picked up by the cast. The Layer/Mask works properly for PhysicsBody objects such as KinematicBody, but not for Area. Regardless of which Layer/Mask is specified for Area or RayCast, the RayCast will detect a collision with the Area.

**Steps to reproduce:**
- Create node `Area`
 - Create child `CollisionShape` - Set to any desired shape
- Create node `RayCast`
 - Set Layer Mask to exclude Layer(s) used by Area
- Observe that `RayCast` node's `is_colliding()` returns `True`

**Link to minimal example project:**

This ZIP contains 2.1.1-Compatible and 3.0-alpha-Compatible scenes.

[test_proj.zip](https://github.com/godotengine/godot/files/719905/test_proj.zip)

**Comment by thimenesup** [comment]
Not only with raycast but with every Area.
Area and Area will always detect for collisions even when they are in different layers.

**Comment by bojidar-bg** [comment]
Probably an artefact of my porting of the 2D system in  #4273....

**Comment by thimenesup** [comment]
The 2D doesn't work either, behaves exactly as the 3D Area.

**Comment by bojidar-bg** [comment]
@thimenesup Ah thanks for confirming, then it's not my fault :laughing:

**Comment by eon-s** [comment]
There is a mess with Area2D detection, because it detects masks instead of layers.

I think that, at least Area2D, has mixed up layers and masks, the names `collision_layer` and `layer_mask` maybe caused some confusion somewhere.

**Comment by lonesurvivor** [comment]
I can't actually reproduce this. RayCast2D works fine for me on areas. `is_colliding()` reports when, and only when the mask in RayCast2D and the layer in Area2D have the same bit set.
The only weird thing I could find with Raycast2D is that it still reports collision when the monitorable on the Area2D is disabled. But that may be intended. So maybe it depends on the operating system? Arch Linux 64 here.

I can confirm the problem with the two areas though. Additionally the monitoring one also reports when monitoring is disabled at all (it is sufficient to have monitorable enabled on the other one).

**Comment by RandomShaper** [comment]
The code path for 3D was wrong; for 2D it's OK.

Are you still able to reproduce the issue in 2D?

**Comment by eon-s** [comment]
@RandomShaper on 2D seems to work fine, unless RayCast2D should only detect monitorable areas.

**Comment by kubecz3k** [comment]
I came across this issue in 1b2e09355e890ae32fe172aad19dcda137ed636f But from what I can tell it behaves differently. As far as I can tell RayCast node should collide with objects that are on certain collision mask. It's instead taking the layer into account.

**Comment by akien-mga** [comment]
CC @RandomShaper, as I think he partly fixed this in #9832 (but not fully as per the above comment).

**Comment by kubecz3k** [comment]
@akien-mga @RandomShaper Let me double check if what I said is correct.

**Comment by kubecz3k** [comment]
Yes, the RayCast node is colliding with objects that are on the same collision layer as RayCast node. 
Collision should be detected only when object is on proper `collision mask`, this way it would be consistent with how the rest of collision bodies are working.
Test project: [RaycastCollisionMaskTest.zip](https://github.com/godotengine/godot/files/1401645/RaycastCollisionMaskTest.zip) (run RaycastCollisionMaskTest.tscn)
tested in 3971bd41bb274c7f999801d74863746cd4546128

**Comment by RandomShaper** [comment]
I'll check it and fix accordingly.

**Comment by RandomShaper** [comment]
I think the problem is at 6c44fff5088d445d60ccd7109c8b5163a0764a7c.

Replacing `layer_mask` with `collision_layer` was right for bodies/areas, because that meant _which layers the object belongs to_.

But for `RayCast`s, `layer_mask` meant _layers we want to check against_. So in this case, the rename should have been to `collision_mask`. Otherwise, you think you are setting the `RayCast` to _belong_ to certain layers, when the semantics haven't really changed, meaning that it's still not considered as _belonging_ to layers but to _be checked against_ them.

I think the right approach would be to rename correctly `RayCast`'s `collision_layer` to `collision_mask` to keep the semantics of it not belonging but rather checking against (and doing the appropiate naming adjustements to the `Space::intersect_*` methods, like renaming their `p_collision_layer` argument to `p_collision_mask`).

CC @Noshyaar

**Comment by kubecz3k** [comment]
I'm fine with the rename. But still, we want to check against objects which are occupying given collision mask bit. So I think that renaming layers to mask in RayCast is not enough

**Comment by RandomShaper** [comment]
If I'm not mistaken, that would be a feature proposal (easily doable). 

Unless I'm not aware the philosophy of the RayCast changed from 2.x to 3.x.

Maybe @reduz can clear up this for me.

**Comment by kubecz3k** [comment]
@RandomShaper oh, I'm sorry I think I'm actually wrong here, and you are right! (since if raycast will have collision mask property it should collide with objects which are occupying corresponding collision layer (not mask)) My bad!

**Comment by Noshyaar** [comment]
@RandomShaper I was confused about naming on RayCast. I agree that it should be renamed. It would be less confusing.

**Comment by RandomShaper** [comment]
Yes, the naming was confusing. I had a hard time even writing my comment, double and triple checking every instance of the concepts involved. A lot or mind juggling between the old and new names.

Your work made them more understandable for the future. I'll fix the naming for the RayCasts and everything will be fine for 3.0!
