### ISSUE TITLE
Color pick Hex code field too small

### ISSUE THREAD

**Issue by GregX999** [godotengine/godot#75897]
### Godot version

4.0.2

### System information

Windows 11

### Issue description

The field for entering a hex value in the color picker is only large enough to show three characters.

![colorpicker](https://user-images.githubusercontent.com/677791/230940556-41c23276-acfd-400a-9f92-8755f3a4791c.png)

### Steps to reproduce

Open the color picker and enter a 6-character hex code.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
This doesn't occur with the default editor theme and font:

![image](https://user-images.githubusercontent.com/180032/230941513-1d98926f-65e6-4db7-
a3a2-2c5ad509726e.png)

However, only 6 characters with wide glyphs (such as `0` or `8`) can be displayed with the default font. We should extend the field's width to display 8 characters.

**Comment by GregX999** [comment]
I would think the field should expand to fit 6 (or whatever number is decided) characters even when using different fonts.
Maybe the title should be "Color picked Hex code field too small _with custom font_".

(Being able to enter a color name like "red" would be very nice as well.)
