### ISSUE TITLE
NODE_POSITION_VIEW shader built-ins does not work correctly

### ISSUE THREAD

**Issue by MrAndriy804** [godotengine/godot#75896]
### Godot version

v4.0.2.stable.official

### System information

Windows 10

### Issue description

Shader built-in NODE_POSITION_VIEW should show the coordinates of the node in the local space of the camera, but if the node has some rotation, it does not work correctly.
In the following video, you can see that when a node is rotated, its position relative to the camera does not change, but the NODE_POSITION_VIEW value (which is passed to ALBEDO) reacts to the rotation, and this is a bug.

https://user-images.githubusercontent.com/130088064/230925447-66b6b5a2-b248-4f42-a81b-d2aad12987b0.mp4

This bug occurs both when using Forward+ and when using mobile rendering.

### Steps to reproduce

1) Create MeshInstance3D and set some mesh
2) Add shader material
3) Create a new shader
4) Set value from NODE_POSITION_VIEW as ALBEDO
5) Rotate the MeshInstance3D node
6) You can see how mesh changes in color, but it shouldn't because its position relative to the camera doesn't change

### Minimal reproduction project

[NodePositionViewBug.zip](https://github.com/godotengine/godot/files/11191396/NodePositionViewBug.zip)

**Comment by clayjohn** [comment]
CC @paddy-exe

**Comment by paddy-exe** [comment]
@MrAndriy804 Thanks for raising this issue👍🏻 I will get on it

**Comment by paddy-exe** [comment]
@MrAndriy804 Could you please test https://github.com/godotengine/godot/pull/76109 and tell me if that solves the issue for you. Somehow I can't test it even with the changes but using the direct GDShader variant works so it should be resolved with this PR

**Comment by MrAndriy804** [comment]
It works for me! Thanks!

https://user-images.githubusercontent.com/130088064/232324552-deccd6cd-aed7-4b3f-9f2f-3804c956bb40.mp4
