### ISSUE TITLE
Could not do mathematical operations in integer property fields

### ISSUE THREAD

**Issue by LunaSquee** [godotengine/godot#7590]
Arch Linux, built from latest commit on master (72a0255)

Only seems to input the first integer before any operation
![screenshot_17-01-20-22 35 10](https://cloud.githubusercontent.com/assets/6363179/22164752/305c2a84-df61-11e6-814d-5db219239031.png)

At least on 2.1.1 that worked.

**Comment by bojidar-bg** [comment]
Note that this is a Vector2 property, not an integer property.

**Comment by LunaSquee** [comment]
This does not seem to be an issue in 3.0
