### ISSUE TITLE
executable_path in project_metadata.cfg on mac points to temporary location

### ISSUE THREAD

**Issue by van800** [godotengine/godot#75906]
### Godot version

4.0

### System information

MACOSX Ventura 13.2.1 (22D68)

### Issue description

project_metadata.cfg usually looks like the following:

```
[editor_metadata]

executable_path="/private/var/folders/2w/21lwwjnj7xjbzgn4vq54svl00000gn/T/AppTranslocation/F60239EE-2302-412A-994D-60E0B02CDB79/d/Godot_mono.app/Contents/MacOS/Godot"
```

and the non-temporary real path to the editor is `/Users/user/Downloads/Godot_mono.app`

### Steps to reproduce

no specific steps to reproduce

### Minimal reproduction project

https://github.com/van800/godot-demo-projects/tree/4.0

**Comment by van800** [comment]
Rider plugin for Godot uses this `executable_path` to provide run-configurations.

**Comment by KoBeWi** [comment]
Isn't APP some sort of archive that needs to get unpacked first? Part of the temp path is AppTranslocation.

**Comment by Calinou** [comment]
macOS' path randomization is automatically enabled for apps running from the Downloads folder. Move the app to `/Applications` before running it, or use `xattr -d com.apple.quarantine /path/to/The_Application.app`

**Comment by akien-mga** [comment]
CC @bruvzg

**Comment by bruvzg** [comment]
There's nothing we can do, Gatekeeper path randomization is a security feature that's always active for downloaded/quarantined apps, move it to the `Applications` and executable path will be correct.

In general, macOS apps are not expected to access anything outside the app bundle using relative path.
