### ISSUE TITLE
Unable to generate VS solution file with scons

### ISSUE THREAD

**Issue by ggsjyoon** [godotengine/godot#75914]
### Godot version

master

### System information

Windows 10, VS2022

### Issue description

Unable to generate VS2022 solution file with scons.

### Steps to reproduce

Followed [the official guide](https://docs.godotengine.org/en/stable/contributing/development/configuring_an_ide/visual_studio.html#doc-configuring-an-ide-vs) 

```
C:\open_source\godot>scons p=windows vsproj=yes dev_build=yes
scons: Reading SConscript files ...
Auto-detected 24 CPU cores available for build parallelism. Using 23 cores by default. You can override it with the -j argument.
Found MSVC version 14.3, arch x86_64
Building for platform "windows", architecture "x86_64", target "editor".
NOTE: Developer build, with debug optimization level and debug symbols (unless overridden).
TypeError: can only concatenate deque (not "list") to deque:
  File "C:\open_source\godot\SConstruct", line 927:
    methods.generate_vs_project(env, GetOption("num_jobs"), env["vsproj_name"])
  File "C:\open_source\godot\methods.py", line 859:
    module_configs = ModuleConfigs()
  File "C:\open_source\godot\methods.py", line 763:
    self.add_mode()  # default
  File "C:\open_source\godot\methods.py", line 786:
    self.arg_dict["cppdefines"] += ModuleConfigs.for_every_variant(env["CPPDEFINES"] + defines)
```

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
- Duplicate of https://github.com/godotengine/godot/issues/74725/

**Comment by ggsjyoon** [comment]
The fix worked. Thanks!

**Comment by geekrelief** [comment]
Either the usage of SCons 4.4 needs to be specified in the documentation, i.e. here: https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_for_windows.html#setting-up-scons or `methods.py` needs patching. I got it to work by casting `defines` to a `deque`.

**Comment by YuriSizov** [comment]
@geekrelief Are you saying that the fix from https://github.com/godotengine/godot/pull/75309 is not working for you?
