### ISSUE TITLE
Editor Zoom strange behavior

### ISSUE THREAD

**Issue by amedlock** [godotengine/godot#7591]
**Operating system or device - Godot version:**
Windows 7 64-bit Professional, AMD 64, 24 GB Ram

**Issue description:**
Several times now as I am editing a scene I cannot zoom in on objects.  I scroll the mouse wheel and when it stops zooming the object is still 1-2 inches square in the center of my monitor.  I also tried using the ALT + drag Middle Mouse button and that still doesn't work.  

What is weird is if I open 2-window layout the second window works fine.  Of course I cannot force window 1 to the view position of window 2.

Did I get the editor in some weird mode I need to exit from? 
I cannot find any docs on this.  

I have built Godot successfully locally so I am more than willing to help out if there is indeed a bug.

Thanks

**Comment by bojidar-bg** [comment]
Would be nice if someone can try to confirm this (on 2.1/HEAD and master)

**Comment by amedlock** [comment]
[shooter.zip](https://github.com/godotengine/godot/files/852097/shooter.zip)

Attached is a project which has the issue.  Just load data/test.tscn  and begin scrolling into the room.

About halfway across the room the zoom will slow and then stop.  You can scroll up all you want and the editor camera won't move.

**Comment by bojidar-bg** [comment]
@amedlock I think you are confusing zooming/panning with FPS-style walking...

Try Shift-MMB drag, to move the camera origin around.

Also, you should have mentioned it is about 3D zoom, I thought it is 2D :smiley:

Finally, can you confirm if it is a duplicate of #1084?

**Comment by amedlock** [comment]
Its kindof strange system for an editor but I see how it works now.  There is no indicator anywhere(that I can see) that my zoom level is high, so panning moves in cm when its like that.  If Blender has this feature I have never ran into it.

If we added the FPS style fly mode, add my vote for copying some of Unreal Ed's behaviors.  I like the Shift panning which locks the camera on the selected object while panning.

I haven't hacked on the code before, but I will peek at the editor control code to see if I can contribute.

Thanks for your help.
