### ISSUE TITLE
GLES3 Renderer fails on linux devices when testing browser exports.

### ISSUE THREAD

**Issue by MossFrog** [godotengine/godot#75913]
### Godot version

3.5.2 and 3.5.1 Both Don't Work

### System information

Fedora / X11 Desktop Renderer / Chromium Latest / AMD GPU

### Issue description

GLES3 Exports fail to render meshes on web exports running on linux machines, tested on mobile android devices and this issue is not present. Tested Godot versions 3.5.1 and 3.5.2 both seem to fail. Tested multiple projects with and without textures the issue persists and no meshes are rendered. I think the GLES3 Shader fails to compile when running in a web environment since the rendering is fine when done locally through the play/play scene buttons. Tested multiple browsers including chromium and opera.
![Screenshot from 2023-04-11 01-41-03](https://user-images.githubusercontent.com/15126587/231012562-4d94207d-5a63-4b29-b630-e310261d13ba.png)

![Screenshot from 2023-04-11 01-40-43](https://user-images.githubusercontent.com/15126587/231012519-f080511f-0fbc-4d8b-aad5-390719b8153b.png)

### Steps to reproduce

Create an empty project, add in any basic mesh instance and a camera to view it, export for HTML5 and test the game export in any browser on a linux machine (I'm running fedora but I assume they all have similar rendering pipelines) Other WEBGL 2.0 features work fine on the machine for the browser.

### Minimal reproduction project

Any basic project will suffice.

This issue might be related -> https://github.com/godotengine/godot/issues/73799 
This too if it uses a similar pipeline -> https://github.com/godotengine/godot/issues/75054

**Comment by MossFrog** [comment]
[Capture1.webm](https://user-images.githubusercontent.com/15126587/231013284-b5e517b1-e5c0-4245-8441-727f0e2f137c.webm)

Above the project is running through the editor just fine.

Below is the corresponding web export.

![Screenshot from 2023-04-11 01-47-38](https://user-images.githubusercontent.com/15126587/231013406-f7957196-8106-4bd0-a45a-75bc5d7f5de5.png)

**Comment by Calinou** [comment]
Which graphics card model and driver version are you using?

**Comment by MossFrog** [comment]
Radeon RX6700 10GB 
I have attached an image of the current drivers running on the machine.
![image](https://user-images.githubusercontent.com/15126587/231032057-7020a201-a471-43e5-b211-74b269f08511.png)

**Comment by lawnjelly** [comment]
The defines at the top of the shader look to be bogus:
```
#define MAX_LIGHT_DATA_STRUCTS -10066329
etc
```

**Comment by sammypanda** [comment]
+1 

I have the same issue on my development machine, Radeon 6600XT (I'm currently on Desktop NixOS)

Found the exact same export works fine when hosted/ran on ChromeOS (Intel Celeron N3350, Integrated Graphics)

**Comment by Calinou** [comment]
> Godot 4.0.2

Please test this on 4.1.1, as 4.0.2 is no longer supported.

**Comment by bitsawer** [comment]
This might have been fixed in Godot 4.x OpenGL Compatibility renderer by https://github.com/godotengine/godot/pull/80909. The fix could be possibly ported to Godot 3.x as well.

**Comment by lawnjelly** [comment]
Yes this looks like the same bug as #80909. :+1:

**Comment by akien-mga** [comment]
Should be fixed by #83031.
