### ISSUE TITLE
Input.IsKeyPressed Not Working with multiple keys active

### ISSUE THREAD

**Issue by ElliottjPierce** [godotengine/godot#75919]
### Godot version

4.0.2 .Net

### System information

Mac OS

### Issue description

When capturing key input as a vector2, only 2 keys contribute to the result at a time. Pressing a third key does not get factored in. It is as if there is a limit to the inputs that are reported. 

I am using physics process, but I expect the same in process as well. 

The bug is present in C# and GD Script and in is_key_pressed, is_physical_key_pressed, and is_key_label_pressed

Surely I am missing something, but I can't figure out what it is.

Also, this is my first time reporting a bug with Godot, so let me know if I'm doing anything wrong. :)

### Steps to reproduce

As a demonstration of the bug in GD script, create a main scene and add a script to the root node with something to the effect of:

```
func _physics_process(delta):
	var t = Vector2.ZERO;
	if (Input.is_key_pressed(KEY_W)): t.y += 1
	if (Input.is_key_pressed(KEY_S)): t.y -= 1
	if (Input.is_key_pressed(KEY_D)): t.x += 1
	if (Input.is_key_pressed(KEY_A)): t.x -= 1
	print(t)
```
Run the project. When pressing any two keys, it works as expected. Pressing a third, somehow seems to not register.

### Minimal reproduction project

[InputKeyBug.zip](https://github.com/godotengine/godot/files/11196156/InputKeyBug.zip)

**Comment by Zireael07** [comment]
99% certain this is a hardware issue known as keyboard ghosting (since it affects both GDScript and C# and several ways of getting the pressed key)

Not something Godot can fix

**Comment by AThousandShips** [comment]
See [here](https://www.microsoft.com/applied-sciences/projects/anti-ghosting-demo)

**Comment by ElliottjPierce** [comment]
You're right. It is keyboard ghosting. Thanks for the help!
