### ISSUE TITLE
Simple improvement to build.gradle.template

### ISSUE THREAD

**Issue by RameshRavone** [godotengine/godot#7592]
**Operating system or device - Godot version:**
Android: Godot 2.2

**Issue description:**

Integrating Firebase and so, need applicationId to be pressed in build.gradle
but changing 
        defaultConfig {
                minSdkVersion 15
                targetSdkVersion 23
                $$GRADLE_DEFAULT_CONFIG$$
        }
 to
        defaultConfig {
                applicationId "com.godot.game"
                minSdkVersion 15
                targetSdkVersion 23
                $$GRADLE_DEFAULT_CONFIG$$
        }
inside platform/android/build.gradle.template seems to fix.

**Steps to reproduce:**
current build from 2.2-legacy for android

**Comment by bojidar-bg** [comment]
Problem is that we can change package/appId at export...

**Comment by RameshRavone** [comment]
Ya, I kinda looked into it.
