### ISSUE TITLE
Unexpected behaviour when using inferred type of an array

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot#75925]
### Godot version

4.0.2

### System information

Windows 10, GTX 980 Ti, Vulkan Forward+

### Issue description

When inferring type on an array of floats, the array doesn't act the same as an array typed to Array[float].

Running this code:

```gdscript
var my_typed_array_1 := [5.2, 1.9, 25.1] 
var my_typed_array_2: Array[float] = [5.2, 1.9, 25.1] 

func _ready() -> void:
    print("type of array 1")
    print(typeof(my_typed_array_1))
    print("type of array 2")
    print(typeof(my_typed_array_2))
```

returns:
```
type of array 1
28
type of array 2
28
```

But trying to use the arrays in a function that expects a typed array like this:
```gdscript
static func sum_array(array : Array[float]) -> float:
    var sum := 0.0
    for element in array:
        sum += element
    return sum
```

Causes the inferred type array to throw this error:
```
Invalid type in function 'sum_array' in base 'Node2D ()'. The array of argument 1 (Array) does not have the same element type as the expected typed array argument.
```

Note: This used to work in an earlier beta of Godot 4.0.

### Steps to reproduce

Create a node with this script attached and run it

```gdscript
extends Node2D

var my_typed_array_1 := [5.2, 1.9, 25.1] 
var my_typed_array_2: Array[float] = [5.2, 1.9, 25.1] 

static func sum_array(array : Array[float]) -> float:
    var sum := 0.0
    for element in array:
        sum += element
    return sum

func _ready() -> void:
    print("type of array 1")
    print(typeof(my_typed_array_1))
    print("type of array 2")
    print(typeof(my_typed_array_2))
    sum_array(my_typed_array_1) # this causes an error
    sum_array(my_typed_array_2) # this works fine
```

### Minimal reproduction project

NA

**Comment by AThousandShips** [comment]
They are both arrays, but only one is typed, `28` is for array in general

**Comment by AThousandShips** [comment]
Run:
```gdscript
print(my_typed_array_1.is_typed())
```

**Comment by Arnklit** [comment]
Ah lovely. didn't know about those functions. But shouldn't the first instance be able to infer type and be typed? It used to be able to.

Alternatively if it isn't supposed to be able to infer type that way, shouldn't it give a warning when using ":=" ?

**Comment by AThousandShips** [comment]
That wouldn't be safe, as you don't explicitly say it should be a typed array, it correctly infers that it is an (untyped) array, the intended and useful behavior

**Comment by Arnklit** [comment]
Thanks for t he info @AThousandShips . Closing.
