### ISSUE TITLE
Unable to initialize Vulkan video driver but clean install video drivers and worked before

### ISSUE THREAD

**Issue by krunkske** [godotengine/godot#75947]
### Godot version

4.0.2

### System information

Windows 11, Vulcan, AMD ryzen 7, GTX 1650 latest available drivers (clean)

### Issue description

![Schermafbeelding 2023-04-11 175339](https://user-images.githubusercontent.com/123201489/231226153-c19c4f97-991c-42f5-9625-add27e3f52a1.png)
I have recently reinstalled Windows and i wanted to start working on some Godot projects again but every time when I open a project this happens. only happens for Vulcan/Forward+.

### Steps to reproduce

i have no idea how.....

### Minimal reproduction project

any project so i don't know if i need to supply one, ask me if needed

**Comment by clayjohn** [comment]
Have you tried updating your GPU drivers? If you reinstalled Windows it is likely that you are back on your stock NVidia drivers and you need an update.

**Comment by clayjohn** [comment]
Can you run Godot from the command line and double check that it is actually running on your dedicated GPU? Godot prints the name of the GPU it is using at startup time.

**Comment by krunkske** [comment]
> Can you run Godot from the command line and double check that it is actually running on your dedicated GPU? Godot prints the name of the GPU it is using at startup time.

U mean the console exe it comes with

**Comment by Calinou** [comment]
- This is likely related to https://github.com/godotengine/godot/issues/57708.

Try setting the `DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1` environment variable to `1`.

**Comment by krunkske** [comment]
> * This is likely related to [Vulkan: Can't start Godot with AMD integrated + NVIDIA dedicated GPU switchable graphics (Failed dispatch call `vkEnumeratePhysicalDevices`) #57708](https://github.com/godotengine/godot/issues/57708).
> 
> Try setting the `DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1` environment variable to `1`. #73450 will do this automatically, at the cost of removing the ability to use an AMD IGP in systems where there's a dedicated NVIDIA graphics card on Windows.

that doesn't seem like an ideal situation. It isn't really recommended like you said on that post.il try it for now. Can you provide steps with how to do this?

**Comment by krunkske** [comment]
> > Can you provide steps with how to do this?
> 
> See https://www.howtogeek.com/787217/how-to-edit-environment-variables-on-windows-10-or-11/
> 
> Note that the variable you need to set is called `DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1`, not `DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS`. Its value must be `1` (without quotes or spaces). After setting the environment variable, reboot your system to make sure changes apply.

Wait does this disable the igpu comepletly or only for Godot

**Comment by krunkske** [comment]
> > Wait does this disable the igpu comepletly or only for Godot
> 
> This prevents Vulkan applications from using integrated graphics, but this does not affect OpenGL or Direct3D applications. This means apps and most other games on the system won't be affected.
> 
> In any case, you can revert this change by removing the environment variable then rebooting.

Okay Il try it when I have time

**Comment by krunkske** [comment]
I'm gonna leave this open for future people who encounter this problem.
