### ISSUE TITLE
Z-Ordering Issue in 3D materials with Alpha

### ISSUE THREAD

**Issue by henriquelalves** [godotengine/godot#7594]
**Operating system or device - Godot version:**
LinuxMint - Godot 2.1.1

**Issue description:**
There is a z-ordering error when you have two 3D materials with Alpha ("Use Alpha" option on) intersecting each other. This happens with Sprite3D's and meshes.

**Steps to reproduce:**
Any 2 intersecting 3D sprites with Alpha should make this Issue happen, with any combination of depth-draw option.

**Link to minimal example project:**
Here is the video of the Issue happening: https://youtu.be/zQgYQPi7PZ0
The project used: [z-ordering-issue.zip](https://github.com/godotengine/godot/files/721008/z-ordering-issue.zip)

**Comment by bojidar-bg** [comment]
Is this valid in master/3.0 too?

**Comment by henriquelalves** [comment]
I couldn't make transparent materials work on 3.0; probably I'm doing something wrong, but the "Transparent" flag has no effect on the materials for me.

**Comment by henriquelalves** [comment]
Not sure if this is helpful, but my theory is that just one triangle out of the quad mesh bugs the z-ordering - at least this is what it looks like out of my tests.

**Comment by reduz** [comment]
this is not a bug, this is as best as it can be done, unfortunately

**Comment by henriquelalves** [comment]
Oh damn, I wasn't aware of it. Does this particular z-ordering problem has a name (I'm curious on what is it)? Will this change on v3.0?

**Comment by reduz** [comment]
no, this is a limitation of all 3D engines, or more like, how GPUs do
rastering. It can't be worked around, so you have to be creative :)

**Comment by henriquelalves** [comment]
Haha, sounds fair. Guess I'll close this Issue then, at the very least other people may find this problem and try something else.

**Comment by henriquelalves** [comment]
I guess as a reference to others, this may provide some useful insight (it's on Unity Q&A, but the answer works for Godot as well): http://answers.unity3d.com/questions/609021/how-to-fix-transparent-rendering-problem.html
