### ISSUE TITLE
Godot crashes when starting any project.

### ISSUE THREAD

**Issue by em-s-h** [godotengine/godot#75952]
### Godot version

Godot Engine v4.0.2.stable.mono.official

### System information

Ubuntu 22.04.2 LTS, Intel(R) Core(TM) i5-2310 CPU @ 2.90GHz x86_64

### Issue description

When I try to open any project in the Godot project manager or with the command line the program crashes and closes.

Command line output:
```bash
$ godot project.godot

Godot Engine v4.0.2.stable.mono.official.7a0977ce2 - https://godotengine.org
Vulkan API 1.3.224 - Forward+ - Using Vulkan Device #0: Unknown - llvmpipe (LLVM 15.0.6, 256 bits)
 
WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:70)

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.2.stable.mono.official (7a0977ce2c558fe6219f0a14f8bd4d05aea8f019)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /usr/lib/dotnet/shared/Microsoft.NETCore.App/6.0.13/libcoreclr.so(+0x4b5e94) [0x7f8f0e2b5e94] (??:0)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f8f7fe42520] (??:0)
[3] llvm::CmpInst::Create(llvm::Instruction::OtherOps, llvm::CmpInst::Predicate, llvm::Value*, llvm::Value*, llvm::Twine const&, llvm::BasicBlock*) (??:0)
-- END OF BACKTRACE --
================================================================
Abortado
```

### Steps to reproduce

Opening any project crashes Godot (even with a newly generated project).

### Minimal reproduction project

N/A

### Notes

This started to happen suddenly without me doing anything, I also tried to downgrade to Godot V4.01 (which was running fine on this computer) but the problem persisted.

**Comment by RedworkDE** [comment]
Does this crash also happen with the non-mono version?

If no, try uninstalling all .NET sdks and runtimes and reinstalling the net 6 or 7 sdk as per microsofts instructions into the default location.

If yes, try opening a project that uses the compatibility renderer.

**Comment by em-s-h** [comment]
> Duplicate of #58927. This is not C#-related – your IGP lacks Vulkan support, but Godot doesn't automatically fall back to OpenGL in the editor yet.
> 
> Switch your project to use the Compatibility rendering method as per [#74159 (comment)](https://github.com/godotengine/godot/issues/74159#issuecomment-1450427287).

It worked! Thank you!
