### ISSUE TITLE
CollisionPolygon2D doesn't snap properly to grid

### ISSUE THREAD

**Issue by lonesurvivor** [godotengine/godot#7595]
**Operating system or device - Godot version:**
Arch Linux 64 - 2.2 branch

**Issue description:**
When moving a CollisionPolygon2D around with snap enabled, it never snaps to the grid. It will always create a small offset as soon as it is move by the mouse. This doesn't happen with any other node.

**Steps to reproduce:**
Create new scene. Create root node. Create PhysicsBody. Create CollisionPolygon2D as a child of it. Make sure everything is set to position (0,0). Enable snap or pixel snap mode. Draw a polygon with one point at the origin of the scene. Select the polygon node with the mosue and try to move it by one grid step. It will immediately get off by something and will then move by the set step size. 

EDIT:
It seems that this is caused by the snap point of the polygon being always the top left corner of the outer box around the polygon, which is automatically adjusted when the polygon is drawn (and scales with its size). This is bad, it should instead snap to the origin of the polygon node.

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

---

@groud what's the status on this? :)

**Comment by groud** [comment]
No clue, it's a 2.2 issue that might be fixed on master.

**Comment by ttencate** [comment]
@ghost Just tried to repro in 3.0.6, seems to work fine nowadays.

**Comment by akien-mga** [comment]
Thanks, closing as fixed in 3.0 then.
