### ISSUE TITLE
Vulkan Mobile: Clip Children shows a copy of all nodes in the scene

### ISSUE THREAD

**Issue by Insane-Owl** [godotengine/godot#75956]
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

4.0.2.stable

### System information

Windows 11, AMD RX 6700 XT (23.4.1), Mobile renderer

### Issue description

sprites with clip_children - 'Clip Only' enabled, have a shrunk-down mirror of the scene behind them. 

This only happens in the Mobile renderer

![Godot_4_cYreMgGK0z](https://user-images.githubusercontent.com/78328941/231319679-c7cd11c6-5dcc-4703-b24d-011ada8b02f0.png)
![Godot_4_rOcYBV4uRd](https://user-images.githubusercontent.com/78328941/231319655-90093e3d-f0c6-4bcb-b4e4-73485551f576.png)

### Steps to reproduce

1. Create a background, e.g. a sprite
2. Add a sprite with clip_children enabled
3. Add another sprite as a child of the one with clip_children enabled, and scale it down or turn down its transparency
4. The background sprite will appear behind it (may require moving it)

### Minimal reproduction project

[Clip Children Bug.zip](https://github.com/godotengine/godot/files/11206016/Clip.Children.Bug.zip)

**Comment by clayjohn** [comment]
For some reason the entire background is copied into a rect the size of the Parent.

The issue is likely comes from here: https://github.com/godotengine/godot/blob/ab7cb2a95d060a6533e6ff5111c11f71972ab43f/servers/rendering/renderer_rd/storage_rd/texture_storage.cpp#L3290-L3294

**Comment by AndyAstrand** [comment]
I can also report this is happening for me in the editor, and in the emulator, and on Android using gl_compatibility mode.
https://youtu.be/usgMUOv_7EI

**Comment by Insane-Owl** [comment]
Can confirm problem still exists in Godot 4.1.stable

**Comment by endritdev1** [comment]
Still happening :/

**Comment by denq04** [comment]
Still happening
System: Godot v4.1.3.stable.mono - Windows 10.0.22621 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3699) - 13th Gen Intel(R) Core(TM) i5-13600KF (20 Threads)

**Comment by vyshliy** [comment]
Confirmed in 4.2 rc2

**Comment by denq04** [comment]
Confirmed in v4.2.stable.mono.official [46dc27791]

**Comment by htmiel** [comment]
Any news on this? I'm trying to use a Polygon2D as a mask with Clip Children, and I have the same behavior on the Mobile renderer. (Godot 4.2.1 / Win10)
