### ISSUE TITLE
Godot performance issues on MacOS

### ISSUE THREAD

**Issue by mazingtech** [godotengine/godot#75964]
### Godot version

4.0.2

### System information

MacOS 13.0.1, UHD630 & M1 macbook air

### Issue description

I'm now meanly working on a mac mini 2018, only has UHD630 & 16G RAM in it, I used to play WOW classic with this one. I also have a M1 macbook air has 16G RAM.

I followed a tutorial on YouTube, the different is I'm coding with C#.

The FPS is only 7 when I fire 24 bullets

M1 macbook air is better, the FPS is about 43-45

Is the performance really bad on MacOS or I did anything wrong?

The tutorial I followed is:

https://youtu.be/NPmpEMQqOnA

PS: I've installed vulkansdk-macos-1.3.239.0.

### Steps to reproduce

Try my project

### Minimal reproduction project

[Battle.zip](https://github.com/godotengine/godot/files/11206545/Battle.zip)

**Comment by clayjohn** [comment]
I'm not sure this is the right place to have this kind of discussion. This bug report doesn't really leave any contributor with actionable items, so its unclear when/if it could be "fixed". It would probably best for you to reach out to other MacOS users on discord or one of the other [community channels](https://docs.godotengine.org/en/latest/community/channels.html)

**Comment by mazingtech** [comment]
> I'm not sure this is the right place to have this kind of discussion. This bug report doesn't really leave any contributor with actionable items, so its unclear when/if it could be "fixed". It would probably best for you to reach out to other MacOS users on discord or one of the other [community channels]

Thanks for the heads up. Yes, I'm not reporting a precise bug, but this is not a discussion, the performance of Godot on MacOS is a total mess, keep crushing randomly, 3-5 times per day. If this situation goes on, I feel like they should not clam Godot supports MacOS at all. RE8 runs very smoothly on M1 chip, Metal 3 turns out pretty good, that means opportunities.

MacOS is not as popular as Windows, but in dev community is another story.

I really like Godot, but let's image this, nerds see Godot at the GDC, sit down with their MacBook pro at Starbucks, download it, try it, then "what the hell is this?" and delete it. How sad is that?

Only hope Godot would get better and better.

**Comment by clayjohn** [comment]
Okay. Well, let us know if you run into a specific, actionable problem. For example, if you could identify what parts of the engine were slow (was scripting slow, was it physics, was it rendering, was it interacting with OS-specific APIs). That sort of information allows contributors to investigate and optimize the engine in the areas that are contributing to the perceived slowness.

In the meantime we do our best to improve performance where we can. But very few MacOS developers contribute to the project, so it lags behind the other OSes.

**Comment by mazingtech** [comment]
It's the shader cause the performance problem, remove it, I'm back to 60 fps.

The following shader comes from https://godotshaders.com and gives us a parallax background.

shader_type canvas_item;
render_mode unshaded;

uniform int iterations = 20;
uniform float formuparam = 1.00;

uniform int volsteps = 20;
uniform float stepsize = 0.1;

uniform float zoom = 0.800;
uniform float tile = 0.5;
uniform float speed = 0.1;

uniform float brightness = 0.002;
uniform float darkmatter = 0.100;
uniform float distfading = 0.650;
uniform float saturation = 0.750;

float SCurve (float value) {

    if (value < 0.5)
    {
        return value * value * value * value * value * 16.0; 
    }
    
    value -= 1.0;
    
    return value * value * value * value * value * 16.0 + 1.0;
}

void fragment()
{
	vec2 iResolution = 1.0 / SCREEN_PIXEL_SIZE;
	//get coords and direction
	vec2 uv=FRAGCOORD.xy/iResolution.xy;
	uv.y*=iResolution.y/iResolution.x;
	vec3 dir=vec3(uv*zoom,1.);
	float time=TIME*speed;

	vec3 from=vec3(1.0,0.5,0.5);
	from-=vec3(0.0,time,0.0);
	
	//volumetric rendering
	float s=0.1,fade=1.;
	vec3 v=vec3(0.);
	for (int r=0; r<volsteps; r++) {
		lowp vec3 p=from+s*dir*0.5;
		p = abs(vec3(tile)-mod(p,vec3(tile*2.))); // tiling fold
		lowp float pa,a=pa=0.;
		for (int i=0; i<iterations; i++) { 
			p=abs(p)/dot(p,p)-formuparam; // the magic formula
			a+=abs(length(p)-pa); // absolute sum of average change
			pa=length(p);
		}
		lowp float dm=max(0.,darkmatter-a*a*.001); //dark matter
		a = pow(a, 2.3); // add contrast
		if (r>6) fade*=1.-dm; // dark matter, don't render near
		v+=fade;
		v+=vec3(s,s*s,s*s*s*s)*a*brightness*fade; // coloring based on distance
		fade*=distfading; // distance fading
		s+=stepsize;
	}
    
	v=mix(vec3(length(v)),v,saturation); //color adjust
    
    vec4 C = vec4(v*.01,1.);
    
     	C.r = pow(C.r, 0.35); 
 	 	C.g = pow(C.g, 0.36); 
 	 	C.b = pow(C.b, 0.38); 
 	
    vec4 L = C;   	
    
    COLOR.r = mix(L.r, SCurve(C.r), 0.7); 
    COLOR.g = mix(L.g, SCurve(C.g), 1.0); 
    COLOR.b = mix(L.b, SCurve(C.b), 0.7);     	
	
}

**Comment by clayjohn** [comment]
Makes sense.
