### ISSUE TITLE
LightOccluder2D transparency.

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#7597]
I'm developing a 2D game in which LightOccluder2D node is a great help but some of my objects should be semi-transparent. I think it would be nice if there was a parameter in LightOccluder2D which would affect how "bright" shadow behind it will be. Right now all shadows are the same color based on the settings in Light2D.

I'm not sure if this feature is possible to make with GLES 3.0, but I hope it is.

**Comment by KoBeWi** [comment]
The OP is a ghost, so I'm just leaving a note that we are moving proposals to [proposals repository](https://github.com/godotengine/godot-proposals). If someone is interested in this feature, make an issue over there.
