### ISSUE TITLE
Shader colors do not work with Panels with a custom StyleBoxFlat

### ISSUE THREAD

**Issue by CactiChameleon9** [godotengine/godot#75996]
### Godot version

v3.5.2.stable.official [170ba337a]

### System information

Arch Linux, GLES2 and GLES3, Ryzen Intergrated GPU (Ryzen 5 4500U) 

### Issue description

Panels with a custom StyleBoxFlat seem to not respond properly to shaders that read + edit color data from the panel. See the screenshot below:

![Screenshot](https://user-images.githubusercontent.com/51231053/231514106-769f6ae9-918c-4908-b9c0-66cd4c2d5c15.png)  
On the left an ImageRect node. On the right a Panel with my theme enabled. Both have the following shader applied: [godotshaders.com/shader/circle-pixel](https://godotshaders.com/shader/circle-pixel)

### Steps to reproduce

1. New Scene
2. User Interface (Control)
3. Add a Panel to the scene
3a. Add a new Style->Panel "Theme Override" with a "StyleBoxFlat"
3b. Add a new ShaderMaterial with a new Shader file
3c. Paste the above shader (or any other shader that manipulates color) into the shader file
5. Add a ImageRect to the scene
4a. Add the godot sprite to the image
4b. Add a new ShaderMaterial with a new Shader file
4c. Paste the above shader (or any other shader that manipulates color) into the shader file

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/11213607/Test.zip)

**Comment by CactiChameleon9** [comment]
When converting the above test project to Godot 4 (v4.0.1.stable.arch_linux), the issue still occurs, with the addition that the same issue ALSO occurs on the default Panel (no custom StyleBoxFlat).

**Comment by Calinou** [comment]
> When converting the above test project to Godot 4 (v4.0.1.stable.arch_linux), the issue still occurs, with the addition that the same issue ALSO occurs on the default Panel (no custom StyleBoxFlat).

The default project theme in 4.0 uses StyleBoxFlats instead of StyleBoxTextures.

**Comment by kleonc** [comment]
It works as expected, [the mentioned shader](https://godotshaders.com/shader/circle-pixel/) totally ignores the input [`COLOR` (it's `inout` within the fragment shader](https://docs.godotengine.org/en/3.5/tutorials/shaders/shader_reference/canvas_item_shader.html#fragment-built-ins)), hence the StyleBoxFlat's color (applied to the vertices) ends up being not taken into account. I don't see a bug in here.

Something like this would work as expected:
```glsl
void fragment() {
	vec4 input_color = COLOR;

	// Somehow incorporate `input_color` into calculations for the `final_color`;
	...

	COLOR = final_color;
}
```

E.g. within the MRP instead of overwriting the `COLOR`:
```glsl
COLOR = c * step(0.0, (0.5* c.a) - dist);
```
multiplying it by the calculated one:
```glsl
COLOR *= c * step(0.0, (0.5* c.a) - dist);
```
would do the thing.

**Comment by CactiChameleon9** [comment]
I am really not that big of a shaders person, but how come it works with normal images if it does not do anything with the input color? @kleonc

**Comment by CactiChameleon9** [comment]
What I guess I am trying to get across is why are StyleBoxFlats any different from textures in they way shaders are applied to them? Aren't shaders just editing pixels and UV directly? Seems counter-intuitive for difference behaviour for certain objects.

Really sorry if I am being massively naive here

**Comment by Calinou** [comment]
> What I guess I am trying to get across is why are StyleBoxFlats any different from textures in they way shaders are applied to them? Aren't shaders just editing pixels and UV directly? Seems counter-intuitive for there to be a difference behaviour for certain types of nodes.

StyleBoxFlat doesn't generate a texture; it generates a polygon that is drawn. This allows scaling to any size without losing quality.

**Comment by kleonc** [comment]
> I am really not that big of a shaders person, but how come it works with normal images if it does not do anything with the input color? @kleonc

@CactiChameleon9 The shader you're using "works" with "normal images" because, well, it does sample the texture and uses such color for the final result. And because "normal images" usually have default vertex color (solid white; `vec4(1.0)`) so the fact it's ignored has no visible effect (as not multiplying by ones gives the same result as multiplying). The issue occurs when you're dealing with non-default vertex color, e.g. like in case of StyleBoxFlat, ColorRect, Line2D.

**Comment by CactiChameleon9** [comment]
> > What I guess I am trying to get across is why are StyleBoxFlats any different from textures in they way shaders are applied to them? Aren't shaders just editing pixels and UV directly? Seems counter-intuitive for there to be a difference behaviour for certain types of nodes.
> 
> StyleBoxFlat doesn't generate a texture; it generates a polygon that is drawn. This allows scaling to any size without losing quality.

@Calinou So "texture" in this context means a bitmap? Understood, thanks for that! I guess that makes sense that this does not work the same - however an svg is also not a bitmap (which does seem to behave "normally"). Polygons are different to svgs then.


> > I am really not that big of a shaders person, but how come it works with normal images if it does not do anything with the input color? @kleonc
> 
> @CactiChameleon9 The shader you're using "works" with "normal images" because, well, it does sample the texture and uses such color for the final result. And because "normal images" usually have default vertex color (solid white; `vec4(1.0)`) so the fact it's ignored has no visible effect (as not multiplying by ones gives the same result as multiplying). The issue occurs when you're dealing with non-default vertex color, e.g. like in case of StyleBoxFlat, ColorRect, Line2D.

@kleonc That makes sense now, thanks for correcting me! Sorry for all the curfuffle I have caused here, but at least I have learnt something.


I will close this issue now, sorry again for the false bug report :sweat_smile:

**Comment by Calinou** [comment]
> however an svg is also not a bitmap (but does however seem to behave "normally"). Polygons are different to svgs then.

Godot rasterizes SVGs on import, so all the rendering engine sees is a bitmap.

**Comment by CactiChameleon9** [comment]
> Godot rasterizes SVGs on import, so all the rendering engine sees is a bitmap.

Just wondering.... hypothetically, would it be possible to rasterize UI such as StyleBoxFlat, ColorRect and Line2D? I assume there would be downsides to this, but if is worth a feature request I can make on in the relevant suggestion repo

**Comment by Calinou** [comment]
> Just wondering.... hypothetically, would it be possible to rasterize UI such as StyleBoxFlat, ColorRect and Line2D? I assume there would be downsides to this, but if it is worth a feature request I can make one in the relevant suggestion repo

Yes, by rendering them to a viewport and saving this viewport to a Texture2D. The downside is that you can't scale those without losing quality after doing this.
