### ISSUE TITLE
OpenXr Action Map not shown in project on M1 Mac

### ISSUE THREAD

**Issue by nox123** [godotengine/godot#76007]
i enable openxr but action map not shown on the bottom in godot 4.0
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/6450648/222290551-b3d36626-56e9-4e60-bcf1-a4be8e7f6f10.png">
 M1 macOs

**Comment by mdarveau** [comment]
Is there a workaround for this issue? I'm following the [XR tutorial](https://docs.godotengine.org/en/stable/tutorials/xr/xr_action_map.html) and I'm stuck on this step. Thanks!

**Comment by BastiaanOlij** [comment]
This was resolved some time ago when we added support for OpenXR to the MacOS build.
See: https://github.com/godotengine/godot/pull/79614
