### ISSUE TITLE
[C#] Image.CompressMode lacks Astc

### ISSUE THREAD

**Issue by ChloePrime** [godotengine/godot#76013]
### Godot version

Godot_v4.0.2-stable_mono_win64

### System information

Windows 11 22H2

### Issue description

enum CompressMode in C# glue lacks the Astc option
![image](https://user-images.githubusercontent.com/43518523/231683044-5d96c429-036e-4d26-9e73-ac2439ea74ed.png)

### Steps to reproduce

1. Download godot mono version.
2. use some IDE to see the C# glue source code, search `CompressMode` and jump to that class.
3. see the lackage of Astc option.

### Minimal reproduction project

N/A

### Workaround
use `Image.CompressMode.Bptc + 1` instead of the non-existing `Image.CompressMode.Astc`

**Comment by AThousandShips** [comment]
That's because the constant isn't bound in ClassDB for some reason, so it's not exposed to GDScript either, will see about a fix, is easy and assuming it's just an oversight
