### ISSUE TITLE
Unbinding an argument on signal callback incorrectly throws argument count error

### ISSUE THREAD

**Issue by krazyjakee** [godotengine/godot#76028]
### Godot version

4.0.2-stable

### System information

Windows 11

### Issue description

When connecting a signal to a method and unbinding arguments from that method, an error is incorrectly thrown showing a miscount of arguments expected.

Example connect code:
`$Emitter.connect("action", action.unbind(1))`

Error thrown:

```
E 0:00:01:0133   Emitter.gd:6 @ _ready(): Error calling from signal 'action' to callable: 'Node(Receiver.gd)::action': Method expected 0 arguments, but called with 0.
  <C++ Source>   core/object/object.cpp:1058 @ emit_signalp()
  <Stack Trace>  Emitter.gd:6 @ _ready()
```

### Steps to reproduce

- Download the minimal reproduction project
- Run the project. The error will be shown immediately.

### Minimal reproduction project

[godot-signal-bug.zip](https://github.com/godotengine/godot/files/11222597/godot-signal-bug.zip)

**Comment by krazyjakee** [comment]
Suggested tags:

- bug
- topic:core

**Comment by Rindbee** [comment]
In fact, the `unbind()` function reduces the number of arguments passed to the original callable, and does not affect the number of arguments used to call the original callable.

**Comment by krazyjakee** [comment]
@Rindbee So if the error states: `Method expected 0 arguments, but called with 0.` - Is it the error that is wrong, or the logic?

**Comment by Rindbee** [comment]
> @Rindbee So if the error states: `Method expected 0 arguments, but called with 0.` - Is it the error that is wrong, or the logic, or both?

The error message is problematic.

It's kind of like an adapter. The arguments emitted by the signal and the arguments required by the original `callable` are deterministic and do not necessarily match. `bind()`/`unbind()` to make them match.

**Comment by krazyjakee** [comment]
For my use case, I am creating a Node to bind any signal to any method and wish to unbind any arguments from the signal and method. This is demonstrated in the attached reproduction project. If there isn't at least some workaround, then that feels like a limitation.

**Comment by Rindbee** [comment]
> If there isn't at least some workaround, then that feels like a limitation.

@krazyjakee  In your MRP, you probably need `bind()` instead of `unbind()`.

```GDScript
class_name Receiver extends Node

func _enter_tree():
  var default_value = 0
  %Emitter.connect("action", action.bind(default_value))
  
func action(index: int = 0):
  print("action!")
```

**Comment by AThousandShips** [comment]
Closed by #76158 documenting the use of `unbind`

**Comment by AThousandShips** [comment]
For the functionality it is documented more clearly, which will probably be added to 4.0.3, see #76158 for details.

**Comment by kleonc** [comment]
The error message is clearly incorrect, don't see any other bug in here.

@krazyjakee `%Emitter.connect("action", action.unbind(1))` from your MRP doesn't make much sense to me. You can do what Rindbee suggested in https://github.com/godotengine/godot/issues/76028#issuecomment-1514776409, or you can connect the method straight away, as it has a default argument on its own:
```gdscript
class_name Receiver extends Node

func _enter_tree():
	%Emitter.connect("action", action)

func action(index: int = 0):
	prints("action!", index)
```

**Comment by krazyjakee** [comment]
Awesome thank you!
