### ISSUE TITLE
No public method is available for parsing Godot-style `.glsl` dynamically in extensions

### ISSUE THREAD

**Issue by saki7** [godotengine/godot#76022]
### Godot version

master (ef025711a694071a1407b5035a6fe3e67c2a5b07)

### System information

Windows 10, Vulkan

### Case 1: Using Godot Editor to import `.glsl`
When I import `.glsl` file into editor filesystem tree, the code is magically split according to shader stages, and the resulting chunks are saved into the familiar `.res` format. This leads to a problem that when you edit your `.glsl` file after the initial import, the content will NOT be updated unless you touch (or "click") the shader file inside the tree.

(Note that passing `CACHE_MODE_IGNORE` to `ResourceLoader::load(...)` won't work, since the import was already done by `ResourceImporterShaderFile` thus the `.res` file remains same, regardless of the change in original `.glsl` file.)

### Case 2: Compile `.glsl` on-the-fly
As an alternative to Editor imports, one might generate a compute shader's source code dynamically, and then compile it on-the-fly. This sort of approach is quite convenient when the algorithm can be optimized (or can be switched to another one) depending on runtime conditions.

In order to compile `.glsl` at runtime, I tried `RenderingDevice::shader_compile_spirv_from_source(...)`, however it will not recognize some Godot-specific tokens, for instance, **`#[compute]`**, thus leads to compile error.

Those Godot-specific tokens (and also some preprocessors like `#include`) are detected inside  `RDShaderFile::parse_versions_from_text(...)`:

https://github.com/godotengine/godot/blob/ccaebcd5e04aba9c7e3c9d819e4d10a40dd9679c/servers/rendering/rendering_device_binds.cpp#L60-L70

However, it turns out that this method is not exposed in `RDShaderFile::_bind_methods`, and it is only used internally in `ResourceImporterShaderFile::import(...)`, so there exists no public method to parse Godot-style `.glsl` files on GDExtension.

(I'm using godot-cpp btw)

### Steps to reproduce

Write a simple compute shader
```glsl
#[compute]
#version 450
void main() {}
```

Pass it to `RenderingDevice::shader_compile_spirv_from_source` (on the extension side, not the core function)

Results in compile error because shader compiler won't understand Godot-specific tokens such as `#[compute]`.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Closing, as feature proposals should be discussed on the [Godot proposals](https://github.com/godotengine/godot-proposals) repository. This repository is now used for bug reports only.

Make sure to follow the proposal template when opening a new proposal – don't just copy and paste the text you wrote in this issue.
