### ISSUE TITLE
Enable Audio Input option not showing in Project Settings > Audio

### ISSUE THREAD

**Issue by programmerNacho** [godotengine/godot#76032]
### Godot version

4.0.2

### System information

Windows 11

### Issue description

I am using Godot 4.0.2 for recording audio with my microphone and then saving the audio to a .wav file.

I did the experiment in Godot 3.5.2, and everything is working, but after porting it to the latest version, it does not show the Enable Audio Input option inside Project Settings > Audio.

I tried creating a new Godot 4.0.2 project to see if it was a bug related to my project, but unfortunately it is not.
I also tried checking Project Settings for any possible new field related to this, but I could not find anything.

Godot 3.5.2 Project Settings:

![image](https://user-images.githubusercontent.com/56942092/231819641-55737836-19e1-4c74-8471-f0ab6231bdaf.png)

Godot 4.0.2 Project Settings:

![image](https://user-images.githubusercontent.com/56942092/231820842-67e7edf2-acab-4022-a7bb-231038b9c762.png)

Godot 4.0.2 Warning Enable Audio Input:

![image](https://user-images.githubusercontent.com/56942092/231824317-a6e90beb-25a9-4af8-8907-15c38df2e25c.png)

### Steps to reproduce

Check for the Enable Audio Input option:

1. Create a new Godot 4.0.2 project.
2. Open the Project Settings window.
3. Go to the Audio section.
4. Check that there is not an "Enable Audio Input" option.

Try to record microphone:

1. Press Play.
2. Press R to start recording.
3. Press R again to start recording.
4. Close application.
5. Check microphone_recording.wav in res://

### Minimal reproduction project

[godot-enable-audio-input-bug.zip](https://github.com/godotengine/godot/files/11224362/godot-enable-audio-input-bug.zip)

**Comment by AThousandShips** [comment]
It requires advanced settings

Related: #6530

**Comment by programmerNacho** [comment]
> It requires advanced settings
> 
> Related: [godotengine/godot-proposals#6530](https://github.com/godotengine/godot-proposals/issues/6530)

Exactly as you said, after enabling it it shows the new Driver menu under Audio. 

Completely my bad, do not know how did I miss this. Thanks for the quick answer!

![image](https://user-images.githubusercontent.com/56942092/231826963-0495b35b-9df1-496b-ac0b-e84570d078a2.png)

**Comment by AThousandShips** [comment]
No problem!
