### ISSUE TITLE
AnimationTree resets Skeleton3D when playing empty animation

### ISSUE THREAD

**Issue by Coxcopi** [godotengine/godot#76036]
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Windows 10, Forward+ (Vulkan)

### Issue description

In an AnimationTree (State Machine), when a Skeleton3D is posed/deformed through an animation, and the animation player travels to an empty animation (or an animation that does not contain keyframes for the bones of the Skeleton), the whole Skeleton3D is reset to its base pose.

The same does however not happen when only using an AnimationPlayer.

Expected Result (using an AnimationPlayer):

https://user-images.githubusercontent.com/85553012/231842318-82970aef-2cf0-4385-a375-2832f2f33967.mp4

Playing the empty animation after the other one simply keeps the deformation of the Skeleton.

Actual Result (AnimationTree):

https://user-images.githubusercontent.com/85553012/231842597-d78f0475-3569-4d6b-b09a-a9ab3717380e.mp4

Playing the empty animation resets the Skeleton.

### Steps to reproduce

- Play an animation in the AnimationPlayer state machine that changes the pose of the Skeleton
- Play an empty animation (one that does not have keyframes for the Skeletons bones) in the AnimationPlayer state machine
-> the Skeleton3D resets.

## 

- Play both animations in the AnimationPlayer
-> no reset.

### Minimal reproduction project

[animation_tree_bug.zip](https://github.com/godotengine/godot/files/11225098/animation_tree_bug.zip)

**Comment by Coxcopi** [comment]
This might actually be related to, or even caused by #76538, since every time I encountered the bug, the empty animation was inside another AnimationLibrary. I'm gonna do do some further testing to see if that's where the issue is coming from.

**Comment by TokageItLab** [comment]
This is the intended behavior. https://docs.godotengine.org/en/stable/tutorials/animation/animation_tree.html#for-better-blending
