### ISSUE TITLE
Duplicating folder on FileSystem dock does nothing

### ISSUE THREAD

**Issue by deanrih** [godotengine/godot#76046]
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Operating System: Manjaro Linux, KDE Plasma Version: 5.27.4, KDE Frameworks Version: 5.104.0, Qt Version: 5.15.8, Kernel Version: 6.2.10-1-MANJARO (64-bit), Graphics Platform: X11, Processors: 4 × Intel® Core™ i3-8100 CPU @ 3.60GHz, Memory: 31.2 GiB of RAM, Graphics Processor: NVIDIA GeForce RTX 2060/PCIe/SSE2

### Issue description

Duplicating a folder in the FileSystem dock seems to do nothing, both from using a keyboard shortcut or right-click-context menu

### Steps to reproduce

1. Focus on the FileSystem dock
2. Select any folder or create one if there are none
3. `CTRL+D` or `Right-Click->Duplicate...` the selected folder
4. Choose the new name for the folder
5. Press `Enter` or click the `Duplicate` button

### Minimal reproduction project

N/A

**Comment by Zireael07** [comment]
Did you check in the filesystem explorer itself (e..g Dolphin) that the folder is created? IIRC Godot's filesystem dock has an issue where it sometimes doesn't redraw

**Comment by deanrih** [comment]
I don't know since what version, but it seems it has been fixed, which I actually not sure if it's because a bug fix or my system setup, but it seems to me it's no longer a problem, so I'll close this issue for now, and hopefully for good.
