### ISSUE TITLE
Array += Array is broken

### ISSUE THREAD

**Issue by vmedea** [godotengine/godot#76041]
### Godot version

4.1.dev (4dcf2c5431ea6894c268c384df0d81e7fd96c341)

### System information

Debian Linux, rendering N/A

### Issue description

I noticed the following strange behavior on master as of 4dcf2c5431ea6894c268c384df0d81e7fd96c341:
```
func _ready():
        var list: Array = []
        list = [1,2,3,4]
        list += [1,2]
        print(list) # should print: [1,2,3,4,1,2] prints: [1,2]
        list += []
        print(list) # should print: [1,2,3,4,1,2] prints: []

        var list2: Array = [1,2,3]
        list += list2
        print(list) # should print: [1,2,...2,3] prints: [1,2,3]
```
It appears that `+=` overwrites the current data instead of appending.

FWIW, just writing `var list = []` doesn't trigger the problem. So it's likely something with type `Array`. `Array.append_array` doesn't suffer from the problem.

~~The problem is similar to #72948, however this involves not a typed array only the type Array, and I haven't seen an error. The data just disappears silently. But it might still be fixed by #73540. Haven't tested yet.~~

### Steps to reproduce

See issue description.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Related to #75832, and should be fixed by #75885 after I rewrite it
