### ISSUE TITLE
Copy and paste nodes between projects/engine instances

### ISSUE THREAD

**Issue by marcosbitetti** [godotengine/godot#7605]
I installed last 2.1.2-stable and some projects no more run (crash without any debug)!
I start to remount the project tree in a clear project, but it is very slow.
Is possible to make nodes work on clipboard?

**Comment by Zylann** [comment]
Sounds like you have two issues:
- There is a crash that has to be fixed
- Godot should be able to recognize data copied in the clipboard from another instance of itself

**Comment by bojidar-bg** [comment]
We might copy nodes and resources in a semi-`.tscn` data format, and then detect it on paste (to allow for pasting to a chat and then the other party copying it, etc. etc.)

**Comment by vitalfadeev** [comment]
Cool.
I want copy nodes between projects too.
Easy way.

**Comment by Tybobobo** [comment]
I would love to have this feature.

**Comment by Zylann** [comment]
Note: don't forget it must be undoable ;)

**Comment by KoBeWi** [comment]
The PR that implemented it was rejected, because copying nodes outside current project is a "corner-case" and apparently can be done with a plugin. Also it makes node copy-paste feature much more complicated to do correctly.

So should this issue be closed as "WONTFIX"?

**Comment by akien-mga** [comment]
Yes, I think the feature asked here is not worth implementing.

Implementing copy/paste of node branches in a given instance is definitely a good thing, but across instances is a very rare use case. For this use case, it's simpler to save the node branch as a scene and then copy the scene file IMO.

**Comment by hawkerm** [comment]
Current proposal tracking this is here: https://github.com/godotengine/godot-proposals/discussions/10397

It's certainly not common, but if I've done something in one project, like a menu or a little HUD pop-up or something, it can be useful to be able to copy that over to another project without having to make it a whole new scene or a template or something. Especially, if trying to pillage something quickly for a game jam or what not.
