### ISSUE TITLE
No auto completion on Input.set_mouse_mode

### ISSUE THREAD

**Issue by hakro** [godotengine/godot#76057]
### Godot version

4.0.2

### System information

PopOs 22.04, any renderer

### Issue description

Typing `Input.set_mous....` on a script is expected to suggest `Input.set_mouse_mode` as a method.
But it doesn't.
Same with `Input.get_mouse...`

However, the property `Input.mouse_mode` autocompletes juste fine.

Here : 

https://user-images.githubusercontent.com/3624853/232038681-82670dd6-8afd-4a37-b054-7d528eef7bce.mp4

### Steps to reproduce

- Open any GDScript file
- Start writing `Input.set_mou...`
- It does not suggest the setter 

### Minimal reproduction project

Any empty project with just a script will be enough.

**Comment by KoBeWi** [comment]
Setters and getters are not autocompleted; you are supposed to use the property when it's available.
There was a setting for that, but it was removed in #56268 (it was from Godot 2 era, when there were no properties)

**Comment by KoBeWi** [comment]
The setters/getters are already called when you write or read the property, so using them directly is redundant.
Think of `Input.mouse_mode = MODE` as a syntactic sugar for `Input.set_mouse_mode(MODE)`.
