### ISSUE TITLE
Program freezes when inputing any number and :

### ISSUE THREAD

**Issue by Lectric1** [godotengine/godot#76061]
### Godot version

4.0

### System information

Linux Mint

### Issue description

I could be wrong that this is a bug, and I want to acknowledge that upfront, it could simply be my bad code. I create a program to condense references, and the search function of text_edit seems to freeze the program when I input what it is I am searching for. It is a really small project, and reproduces exactly the issue and as far as I can tell it doesn't do anything else.

### Steps to reproduce

download and load included project files
run the included project files, 
input some numbers and a ':' 
watch game freeze. (not Godot)

### Minimal reproduction project

[Verse Condensing V 0.1.zip](https://github.com/godotengine/godot/files/11233698/Verse.Condensing.V.0.1.zip)

**Comment by KoBeWi** [comment]
Looks like a bug in your logic. You have `while column >= 0:`, make sure this loop ever ends.
