### ISSUE TITLE
Constant frame flickering after window is maximized/minimized

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#7606]
Godot 2.1.1, Windows 10, 64 bits
nVidia 940M

When maximize or minimize the game window with a double-click or drag to top, 90% of the time the game starts to violently jitter, as if double-buffering was not working correctly. With a moving camera the effect becomes almost epileptic.
The only way to get rid of it is to resize the window multiple times until it eventually goes away next time it is maximized. It happens with any Godot game and is noticeable when anything moves on screen.

It's been a long time around, I mentionned the problem in another issue https://github.com/godotengine/godot/issues/2043#issuecomment-254009898 but I felt it was a different matter than the one discussed in the beginning, so I made a new issue.

Here is a video showing the jittering, here happening on minimize:
http://zylannprods.fr/lab/godot/videos/stuttering_motion_example.mp4

I am surprised it wasn't mentionned before, maybe I'm the only guy who makes a resizeable game :p

**Comment by bojidar-bg** [comment]
(Added "needs testing" since I don't know if it happens on 2.2-legacy and 3.0-alpha)

**Comment by Zylann** [comment]
Avast finally let me run 2.1.2, and the issue is still present.

**Comment by Zylann** [comment]
I didn't see this bug recently (but I also didn't work in Godot 2 recently). I don't think I ever saw this in Godot 3.

**Comment by akien-mga** [comment]
Closing as fixed then.
