### ISSUE TITLE
ParallaxBackground Node Ignores Order of other Node2D

### ISSUE THREAD

**Issue by SavoVuksan** [godotengine/godot#76063]
### Godot version

v4.0.1.rc1.mono.official [d23922ffe]

### System information

Windows 10, RTX 2070 Super

### Issue description

The ParallaxBackground Node seems to ignore the Z-Index value of other Node2D. It just accounts for other parallax background nodes. It seems a bit weird since I would expect the Layer value of the Parallax background to use the same ordering as every other sprite or node 2d. 

In the uploaded video you see that the ordering of the nodes is off.

https://user-images.githubusercontent.com/12395493/232076323-a538c44d-f2be-4f13-b9c5-7fc34b989c96.mp4

### Steps to reproduce

Open the Project and start up the ParallaxBackgroundBug scene.

### Minimal reproduction project

[ParallaxBackgroundBug.zip](https://github.com/godotengine/godot/files/11234031/ParallaxBackgroundBug.zip)

**Comment by KoBeWi** [comment]
ParallaxBackground inherits from CanvasLayer. It's not a Node2D.

**Comment by KoBeWi** [comment]
Closing. Nodes under CanvasLayer are sorted independently from nodes under other layers. Same applies to ParallaxBackground.
