### ISSUE TITLE
Dart Language Binding

### ISSUE THREAD

**Issue by JacobGood1** [godotengine/godot#7607]
Check out this video: https://www.youtube.com/watch?v=iPlPk43RbpA

I think Dart would make a great language for binding to Godot in addition to C#.  Hot Reloading of anything and everything could be a killer feature of Godot.  Thoughts?

**Comment by volzhs** [comment]
I think, Godot already has same feature, named as "Sync Scene/Script Changes"

**Comment by bojidar-bg** [comment]
I'd say, we would glady have this as 2.2 (now 3.0) was poised to be the "languages release" anyway. So, whoever overenergetic, adventurous person wants to try doing it is welcome to integrate it as a module.

**Comment by reduz** [comment]
let's make Google pay for it :P

**Comment by rosshadden** [comment]
While I've been a huge advocate for adding more languages, I want to be clear that none of them should actually be a part of the core engine/editor. In fact, I believe doing so would be an enormous mistake, as it implies that Godot should be responsible for them. Additional languages should be able to exist as separate repositories, as community efforts. 

Again, I am VERY much in favor of supporting more scripting languages. I have been one of the most vocal about it (see #7598 and https://github.com/godotengine/godot/issues/937#issuecomment-269876297 and IRC). But all effort that should be taking place inside the Godot code should be towards supporting arbitrary languages, and the community should take it from there in their own repositories. Many engines that do not do this are heavily encumbered by the decision, as they now have to support everything and test everything with every release. It completely kills the progress of what matters most, the engine.

**Comment by JacobGood1** [comment]
Good response, I guess you can close this down now. I am glad I asked about this, it makes me like Godot even more =)

**Comment by bojidar-bg** [comment]
Yeah, closing. If you ever get done'/almost-done with it, you might tell us, and we might mention it in the docs, or have a few official binaries bundled with it (depends). :smiley:

**Comment by billy1380** [comment]
Is anyone interested in pursuing this?

**Comment by mahdisml** [comment]
> Is anyone interested in pursuing this?

Yeah !!

**Comment by mahdisml** [comment]
i started working on it :
https://github.com/mahdisml/DartGodot
