### ISSUE TITLE
"Close documentation" does not appear in the context menu.

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#76083]
### Godot version

v3.6.beta1.official [632a544c6]

### System information

w10 64

### Issue description

The "Close Documentation" option only appears in the "File" menu.

Does not appear in context menu:

![Captura2](https://user-images.githubusercontent.com/19652075/232201683-b214d464-ed62-46be-86e6-aeff38474527.PNG)

It appears in the "File" menu:

![Captura4](https://user-images.githubusercontent.com/19652075/232201698-1317c20c-df4c-49c4-a6a3-750a010cba43.PNG)

### Steps to reproduce

...

### Minimal reproduction project

...

**Comment by Calinou** [comment]
- Duplicate of https://github.com/godotengine/godot-proposals/issues/311.
