### ISSUE TITLE
Does not build with VC++ due to missing _USE_MATH_DEFINES

### ISSUE THREAD

**Issue by RayKoopa** [godotengine/godot#7608]
`eq.cpp`, `reverb.cpp` and `audio_effect_distortion.cpp` all use the constants `M_SQRT2` or `M_PI`.

Those constants are not included with `maths.h` in VC++ while `_USE_MATH_DEFINES` is not defined, making it impossible to build **master** for me (VS2015) at the moment.

I would've fixed the build but don't know where and how exactly.

**Comment by bojidar-bg** [comment]
Probably slightly related to #7572 @BastiaanOlij

**Comment by RayKoopa** [comment]
@bojidar-bg That fixes issues with `_finite` being defined in`float.h` (against the documentation), but these are new :3

**Comment by bojidar-bg** [comment]
@RayKoopa That's the "slightly" part :wink:

**Comment by akien-mga** [comment]
I think those effects should use `Math_PI` and `Math_SQRT12` from `core/math/math_funcs.h`

**Comment by RayKoopa** [comment]
Let me check that
