### ISSUE TITLE
There is no compiled script option in android export

### ISSUE THREAD

**Issue by himaghnam** [godotengine/godot#76080]
### Godot version

4.0

### System information

win10,android 13

### Issue description

Previously there was compiled script option during android export which was good enough to not edit any script of my game for better boost but now it's not there. Using encryption with android is quite difficult as not only it bloats the download size compared to .aab but and crashes the game (encryption works fine with windows export and I think android expansion gives the crash problem ).

### Steps to reproduce

export using expansion and encryption

### Minimal reproduction project

n/a

**Comment by AThousandShips** [comment]
There's no compiled script in 4.x, it's been removed for some time

**Comment by KoBeWi** [comment]
The "compiled scripts" did not improve performance, only loading time.
The option was removed for all platforms, see #59241
