### ISSUE TITLE
Issues with warning icon on CollisionShape2D nodes

### ISSUE THREAD

**Issue by balloonpopper** [godotengine/godot#7609]
Issue when adding a shape to a CollisionShape2D node :
 When adding a CollisionShape2D to a RigidBody2D, the CollisionShape node gets a warning exclaimation mark next to it. Clicking the warning icon pops up a "Node Configuration Warning : A shape must be provided for CollisionShape2D to function. Please create a shape resource for it!" window.
If you now select the collision node and define a shape for it (eg. "New RectangleShape2d") the warning icon does not disappear like it should. Clicking it now does nothing.

Issue when removing a shape from a CollisionShape2D node :
I can get the icon to disappear, either by reloading the scene, or by dragging the node onto another parent, then dragging it back on the RigidBody2D node. If I now "clear" the shape, the warning icon does not reappear like it should. I can get it to reappear by reparenting the CollisionShape node, but the warning icon should appear as soon as the error condition is met (ie. when the node no longer has an associated shape).

Version 2.1.1

**Comment by bojidar-bg** [comment]
Seems like the issue is with the scenetree dock not updating, since moving nodes around would update/hide the warning icon.
