### ISSUE TITLE
Texture duplicated in Vram (Compatibility renderer)

### ISSUE THREAD

**Issue by haruyou27** [godotengine/godot#76110]
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

OpenGL API 4.2 (Core Profile) Mesa 22.2.5 - Compatibility - Using Device: Intel - Mesa Intel(R) HD Graphics 2500 (IVB GT1)

### Issue description

Note the abnormal high RAM usage, I checked the _Video RAM_ tab and found this.
![Screenshot_20230416_075952](https://user-images.githubusercontent.com/68549456/232260619-f1890ae9-42bf-4f22-ac7b-2b1d2e14e153.png)
_Video mem_ in _Monitor tab_ is 0 so I check the RAM usage in htop and it seems correct.

However, when switch to foward+/moblie render, the issue disappear.
![Screenshot_20230416_075913](https://user-images.githubusercontent.com/68549456/232260736-a099c90c-e6a1-491f-9275-b673863e8f39.png)
This time, _Video RAM_ tab is 0.
Vulkan API 1.3.224 - Forward+ - Using Vulkan Device #0: Intel - Intel(R) HD Graphics 2500 (IVB GT1).

### Steps to reproduce

1. Display a Texture2D in a Sprite2D.
2. Switch to Compatibility render.

### Minimal reproduction project

[Compatibility renderer Vram bug.zip](https://github.com/godotengine/godot/files/11241010/Compatibility.renderer.Vram.bug.zip)

**Comment by clayjohn** [comment]
This looks like it may be the same bug that is fixed by https://github.com/godotengine/godot/pull/75782

**Comment by clayjohn** [comment]
I'll actually leave this open until #75782 is merged in case someone else runs into the same issue.
