### ISSUE TITLE
changes size of any shape of duplicated CollisonShape2D changes all duplicated CollisonShape2D shape

### ISSUE THREAD

**Issue by kr-abhi55** [godotengine/godot#76111]
### Godot version

v3.5.2.stable.official [170ba337a]

### System information

debian 11 ,intel hd graphics,gles2

### Issue description

![bug](https://user-images.githubusercontent.com/118665057/232262487-dead9a41-0938-4f46-8e9a-ff16bdbc5699.gif)

changes shape of duplicated CollisonShape2D changes all duplicated CollisonShape2D shape.  
suppose you have created a CollisonShape2D node and have let shape is Rectangle2D.
if we duplicate CollisonShape2D node and changes size of   rectangle2d shape  of  
duplicated CollisonShape2D then all the other size of duplicated  CollisonShape2D shape change .
it must not changes other Shape

### Steps to reproduce

- create new project with Node2d 
- Add Area2d then inside Area2d add CollisionShape2d then set shape of CollisionShape2d lets say Rectangle2d
- node tree look like Node2D->Area2d->CollisionShape2d
- duplicate Area2d node with all its children
- if we change size of Rectangle2d shape of any duplicated CollisionShape2d then its changes to other which is wrong

### Minimal reproduction project

[bug.zip](https://github.com/godotengine/godot/files/11241063/bug.zip)

**Comment by smix8** [comment]
CollisionShapes use Shape2D which are resources. Resources are by default shared across instances that use them.

You need to duplicate the Shape2D of the CollisionShape or enabled Shape2D Resource tab "local_to_scene=true" so the shape auto-duplicates when instanced.

**Comment by kr-abhi55** [comment]
"local_to_scene=true"   not working

**Comment by smix8** [comment]
Click on the RectangleShape2D in the inspector and use "Make Unique",
local_to_scene only works when instancing new scenes.

**Comment by kr-abhi55** [comment]
thanks
