### ISSUE TITLE
Bitmap fonts render incorrectly if glyph dimensions are not even numbers

### ISSUE THREAD

**Issue by FibrielSolaer** [godotengine/godot#76117]
### Godot version

4.0.2.stable.mono.official [7a0977ce2]

### System information

Windows 10 Pro, HP EliteBook 840 G3, Intel HD Graphics 520

### Issue description

Bitmap fonts (pixel fonts) render incorrectly if their glyph dimensions are not an even number.

Godot allows an image to be imported as Font Data (Monospace Image Font). A single image is automatically chopped into glyphs when told how many columns and rows there are. There is no problem so long as the resulting glyphs have even dimensions (e.g. 6x10). However, the font becomes malformed if the resulting glyphs have odd dimensions (e.g. 5x9).

![image](https://user-images.githubusercontent.com/19721089/232278282-ae939a58-2eef-490b-a753-fbe8efc11744.png)

My hypothesis is that Godot's attempt to center a glyph halves its dimensions but does not truncate the result to an integer. This places the glyph halfway between two pixels, requiring an anti-aliasing or nearest-neighbor solution. This may be acceptable for vector fonts, but bitmap fonts should truncate the resolved position to an integer to avoid this distortion.

### Steps to reproduce

1. Create a bitmap image whose glyphs are odd-numbered in dimensions (e.g. 5x9).
2. Import this image as Font Data (Monospace Image Font).
3. With GDScript, load this font and attempt to draw_string() with it.
4. The font will be distorted.

### Minimal reproduction project

[Bitmap Font Render Error.zip](https://github.com/godotengine/godot/files/11241458/Bitmap.Font.Render.Error.zip)

**Comment by FibrielSolaer** [comment]
I can't seem to edit the body of an issue so I want to clarify what I think the problem is:

I think Godot positions a glyph by subtracting half of its width and/or height to center it. However, it does not truncate the result to an integer, so if the original width and/or height were an odd number this would place the glyph halfway between two pixels.

**Comment by Calinou** [comment]
cc @bruvzg
