### ISSUE TITLE
Popups in non embedded windows show up on main window

### ISSUE THREAD

**Issue by 0x0ACB** [godotengine/godot#76118]
### Godot version

4.0.2

### System information

Windows 10

### Issue description

I am currently trying to selectively not embed some Windows (like Make Floating in the Editor) however the only way I have currently found to do this is to disable `gui_embed_subwindows` before creating the window and then reenable it afterward. The issue now is that when you have eg a `MenuButton` the popup will open in the main window and you are not able to interact with it.

### Steps to reproduce

```
get_viewport().gui_embed_subwindows = false
# create window
get_viewport().gui_embed_subwindows = true
```
Try to open a popup in the new window

### Minimal reproduction project

[FloatingWindow.zip](https://github.com/godotengine/godot/files/11241488/FloatingWindow.zip)

**Comment by KoBeWi** [comment]
This is currently not supported, see #62387
> Make Floating in the Editor

This option does not use embedding. The dock is reparented to a new window.

**Comment by Calinou** [comment]
- Closing in favor of https://github.com/godotengine/godot-proposals/issues/4741.
