### ISSUE TITLE
AnimationPlayer doesn't emit "animation_finished" when asked to play animation with a custom_blend

### ISSUE THREAD

**Issue by limbonaut** [godotengine/godot#76127]
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

4.1(a7276f1ce0), 4.0.1-stable

### System information

manjaro gnome linux distro

### Issue description

`AnimationPlayer` doesn't emit `animation_finished`, when asked to play animation with a `custom_blend` property set to 0.1.  
Works as expected on the first attempt, and freezes on the second try. 

Check out simple reproduction project or steps to reproduce.

### Steps to reproduce

```
for i in range(1,10):
  anim.play("test", 0.1, 1.0, false)
  await  anim.animation_finished
  print("Finished animation #", i)
```

### Minimal reproduction project

[anim-bug-reproduction.zip](https://github.com/godotengine/godot/files/11242110/anim-bug-reproduction.zip)

**Comment by FrankLeeC** [comment]
same thing happens to me on 4.0.3.stable.

**Comment by PabloAgustinBustos** [comment]
Same, I'm on 4.1.1.stable

**Comment by limbonaut** [comment]
Checked reproduction project with the 4.2-dev, and it seems to be fixed now :tada:.

**Comment by YuriSizov** [comment]
Great! Closing per the comment above.

**Comment by tnutzmann** [comment]
Dosen't seam to work in 4.2 (v4.2.stable.official [46dc27791]) on MacOS 14.1.1 
codesnippet:
```GDScript
func player_attack_animation():
	match currentDirection:
			Directions.UP:
				$AnimatedSprite2D.play("slash_up")
			Directions.DOWN:
				$AnimatedSprite2D.play("slash_down")
			Directions.LEFT:
				$AnimatedSprite2D.play("slash_left")
			Directions.RIGHT:
				$AnimatedSprite2D.play("slash_right")
	await $AnimatedSprite2D.animation_finished
```

**Comment by AThousandShips** [comment]
This is not about `AnimatedSprite2D`, see the title
