### ISSUE TITLE
I want File.get_mtime(filename)

### ISSUE THREAD

**Issue by vitalfadeev** [godotengine/godot#7613]
**Operating system or device - Godot version:**
Linux

**Issue description:**

I need get a modify time of file. Like unix stat.st_mtime

**Feature request**
Need get a modify time of file.
Found `File::get_modify_time()` in Godot sources. It good. But need same in gdScript.

Want gd-function:

    /**
    * get_mtime(filename)
    * @filename: String  Full path to file
    * @return: int  File modification time. In seconds since 01.01.1970. 
    */
    Int File.get_mtime(String filename)

Usage:

    var mtime = File.get_mtime(filename)

It would be nice...

**Comment by reduz** [comment]
Ah, this should be doable in 3.0 given variant's 64 bitness

**Comment by bojidar-bg** [comment]
`File.get_mtime` is terrible for a name, consider `File.get_modified_time` instead. (just saying)

**Comment by notwarp** [comment]
ciao

**Comment by notwarp** [comment]
ciao achille
