### ISSUE TITLE
SkeletonShaderGLES3 vertex shader compilation error in `GET_BONE_MATRIX` expanded define [Intel HD 4000 on Windows]

### ISSUE THREAD

**Issue by Miottolas** [godotengine/godot#76142]
### Godot version

4.0.0stable, 4.0.1stable, 4.0.2stable

### System information

Windows 11, GLES3, Intel HD 4000

### Issue description

I am getting a series of errors trying to load 3D meshes (GLB/GLTF), i tried with and without animations and the errors still showing.

Running on the the Compatibility mode (Due to Intel HD 4000 not supported for Vulkan).

**On loading the project, the errors are:** 

![error001](https://user-images.githubusercontent.com/130928072/232335185-dfb59d05-9c2e-4445-97fe-03df51ecd30c.png)

**Loading the mesh, the errors are:** 

![error002](https://user-images.githubusercontent.com/130928072/232335234-4789ab47-ae57-4f02-b2db-93b716b8f6a0.png)

### Steps to reproduce

1. Run Windows 11

2. Open Godot 4.0.2

3. Apply any GLB/GLTF 3D Mesh to project folder

4. Attempt to Apply the mesh into the Scene or New Inherited Scene, and the errors will appear

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Can you please show the full error, it looks like there's more error code above indicating where the fault is in the shader code (hard to localise as the skeleton shader doesn't have that many lines so would be helpful if you showered the full error)

**Comment by Miottolas** [comment]
> 

![error003](https://user-images.githubusercontent.com/130928072/233048268-903e867e-e3cc-405f-8130-aa9ca125ef8f.png)

sorry for the late reply, here is all the errors that show.

**Comment by clayjohn** [comment]
@Miottolas Can you please copy the full error printout and paste it here? I can see in your screenshot that you have disabled part of the error print. Its important that we get the full error as it prints the entire shader and points us to the line where the error is coming from.

**Comment by clayjohn** [comment]
> Sure thing, my bad.
> 
> I will upload an txt file, hope that's help out,
> 
> File: [GD4Error.txt](https://github.com/godotengine/godot/files/11275618/GD4Error.txt)

Thank you. That is perfect

**Comment by fatduckling** [comment]
This issue still exists in Godot 4.1, thanks

**Comment by akien-mga** [comment]
The code it's failing on looks like this:
```
#ifdef USE_SKELETON
317: 
318: #define TEX(m) texelFetch(skeleton_texture, ivec2(m % 256u, m / 256u), 0)
319: #define GET_BONE_MATRIX(a, b, c, w) mat4(TEX(a), TEX(b), TEX(c), vec4(0.0, 0.0, 0.0, 1.0)) * w
320: 
321: 	uvec4 bones = in_bone_attrib * uvec4(3);
322: 	uvec4 bones_a = bones + uvec4(1);
323: 	uvec4 bones_b = bones + uvec4(2);
324: 
325: 	highp mat4 m;
326: 	m = GET_BONE_MATRIX(bones.x, bones_a.x, bones_b.x, in_weight_attrib.x);    // Error here
327: 	m += GET_BONE_MATRIX(bones.y, bones_a.y, bones_b.y, in_weight_attrib.y);
328: 	m += GET_BONE_MATRIX(bones.z, bones_a.z, bones_b.z, in_weight_attrib.z);
329: 	m += GET_BONE_MATRIX(bones.w, bones_a.w, bones_b.w, in_weight_attrib.w);
```

I don't see any obvious syntax error, so I expect the problem might be one of:
- Not supporting `texelFetch`
- Not supporting `%` or `u`
- Not supporting expanding nested macros

**Comment by fatduckling** [comment]
Hi @akien-mga 
Thanks for looking into this!
Here are my logs:
[Godot4.1_Error.txt](https://github.com/godotengine/godot/files/11969212/Godot4.1_Error.txt)

![driver](https://github.com/godotengine/godot/assets/3345706/ad22e59b-9d13-47bb-9e56-fd27664ce973)

Please let me know if you need anything. Happy to work with you on this to find root cause. Thanks

**Comment by SamuelEds** [comment]
Any solution? 
I'm also having this same problem in Godot 4.1.2 _(in fact, in any version of 4.x)_.
In Godot 3.x it works normally, but I want to be able to work in 4.x
**My specifications:**
- Intel® HD Graphics 4000 (Version 10.18.10.5161)
- Intel® Core™ i3-3217U CPU @ 1.80GHz

Thank you for your attention.

**Comment by clayjohn** [comment]
@SamuelEds Did you try upgrading to the drivers linked by Akien above?

Alternatively in Godot 4.2, you will be able to use the ANGLE backend, which will most likely resolve this issue as well

**Comment by SamuelEds** [comment]
@clayjohn thanks for answer!! The driver's version 10.18.10.5161 is the last, **but descontinued**. 
I try the Godot 4.2 dev 6 with ANGLE like you metioned and worked great!!
This is the first time I've heard about this ANGLE, but anyway, thank you very much!!

![image](https://github.com/godotengine/godot/assets/52551197/345d3694-a780-4655-bac4-749568152b75)

**Comment by YuriSizov** [comment]
Based on the discussion above I conclude that support for older Intel iGPUs is no longer provided by Intel themselves (no driver updates), and on the engine side we can only offer a workaround via ANGLE, which we now do. So this issue can be closed.

Please feel free to comment if you think this needs to be reopened for one reason or another.
