### ISSUE TITLE
Export templates for Android not working

### ISSUE THREAD

**Issue by seichter** [godotengine/godot#7614]
**Operating system or device - Godot version:**
OS X 10.11.6 - Godot 2.1.2 - Export Templates 2.1.2

**Issue description:**

Moving to 2.1.2 broke the Android ARMv7 export template. App is stuck on Godot splashscreen and keeps flickering. And attaching the debugger shows ...
`W/GodotView( 9646): creating OpenGL ES 2.0 context :`

crash reports like this:
```
W/ActivityManager(  743):   Force finishing activity 1 org.godotengine.bubblepresent/org.godotengine.godot.Godot
E/JavaBinder(  743): !!! FAILED BINDER TRANSACTION !!!
W/ActivityManager(  743): Exception thrown during pause
W/ActivityManager(  743): android.os.TransactionTooLargeException
W/ActivityManager(  743): 	at android.os.BinderProxy.transactNative(Native Method)
W/ActivityManager(  743): 	at android.os.BinderProxy.transact(Binder.java:496)
W/ActivityManager(  743): 	at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:932)
W/ActivityManager(  743): 	at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:1335)
W/ActivityManager(  743): 	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:4528)
W/ActivityManager(  743): 	at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:4229)
W/ActivityManager(  743): 	at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:4744)
W/ActivityManager(  743): 	at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:16957)
W/ActivityManager(  743): 	at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:16830)
W/ActivityManager(  743): 	at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:17602)
W/ActivityManager(  743): 	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:17106)
W/ActivityManager(  743): 	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
E/lowmemorykiller(  162): Error writing /proc/9646/oom_score_adj; errno=22
```

**Steps to reproduce:**
Minimal 2D example - export to Android ARMv7 (cannot test with Intel - no device)

**Link to minimal example project:**
:
Can use a example project from the Example package.

**Comment by RandomShaper** [comment]
Which version of Android are you testing with?

**Comment by RandomShaper** [comment]
I haven't been able to reproduce it (Android 6.1). Maybe it's a transient problem.

Please take no offense (this questions can bother some people), have you tried rebooting your device?

**Comment by seichter** [comment]
This seems a device specific bug. I've just tested the same APK with a nexus 9 on Android 6.0.1 and it works. The crashing one is a Samsung Galaxy Tab A6 on Android 5.1.1. And yes, I've rebooted it. I will update the report with more information later, when I have both devices side by side.

**Comment by RandomShaper** [comment]
Are you using any module like ads, game services, etc.?

**Comment by seichter** [comment]
For whatever reason, I also can't reproduce the error anymore. No, I didn't have ads and the like enabled. However, I had another app in testing, which might caused this. Apologies for the noise. I will have a look more when the next round of testing is due. Closing for now.

**Comment by RandomShaper** [comment]
No problem, Hartmut. It's normal to get alarmed when you think you've hit a
show-stopper bug.
