### ISSUE TITLE
Godot icon become wired in white theme

### ISSUE THREAD

**Issue by qza2468** [godotengine/godot#76156]
### Godot version

4.02

### System information

Ubuntu22.04

### Issue description

just a small problem, in the white theme, the icon become like this in the about page. 
i don't know if it's intend to be.
![image](https://user-images.githubusercontent.com/70065298/232375938-78cd833c-5980-4db8-9a8d-4f8425e13f99.png)

### Steps to reproduce

switch to white theme, open the `godot`, click the `about` at the right bottom corner.

### Minimal reproduction project

...

**Comment by 0Volcanon** [comment]
I think this got fixed in #75653. Should be there in the next release.
