### ISSUE TITLE
No warning when pressing "Remove Animation"

### ISSUE THREAD

**Issue by Keetz** [godotengine/godot#7616]
Godot 2.1.1 stable

When pressing the little trashcan "Remove Animation" in the Animation dock, it deletes selected animation without warning. It is too easy to accidentally remove an animation with hours put into it.

I know it is possible to save the animation as a file, but I think it would be great to have a "Are you sure?" warning, as deleting an animation by accident can be quiet a loss.

**Comment by RayKoopa** [comment]
I'd rather prefer an undo step for this. "Are you sure?" questions are annoying.

**Comment by Keetz** [comment]
@RayKoopa i am actually not sure about the undo.
I agree that "Are you sure?" questions are annoying, to some extend. For instance if there was a warning when deleting a track it would be annoying because it is something you do often. But deleting a whole animation i wouldn't say happen that often, and a whole animation can be quiet comprehensive.
Just my thoughts.

**Comment by RayKoopa** [comment]
As long as things can clearly and correctly be made undo, I doubt the usefulness of such messages. Blender for example does it that way. Maybe we should put in a visible Undo button to godot to improve the user about knowing such a feature.

**Comment by tamkcr** [comment]
right now it is possible for one to, inadvertently, deletes an animation through a sleepy click (strange things happens in late nights...), better safe than sorry in my opinion.  plus like Keetz said deleting an animation is not a frequent task so I don't think this will become too annoying.

**Comment by RayKoopa** [comment]
Okay, I guess I can implement this quickly asap.

**Comment by Keetz** [comment]
@RayKoopa i don't think there should be a warning when deleting a track, as it, unlike an animation, is a frequent action and not that big a loss of work. As long as it is possible to undo the track it should be fine.

But talking about tracks i'd like to refer to #7448 :D
That is an example of a really annoying warning as you press the key to create a track many times during the time of creating an animation, and every time you have to press 'confirm' too.

**Comment by RayKoopa** [comment]
What is even worse that we can detach and effectively nuke built-in scripts on nodes without getting a warning either.

Lot to do with warnings in general...

**Comment by akien-mga** [comment]
Fixed by #7648.

**Comment by hubbyist** [comment]
> detach and effectively nuke built-in scripts on nodes without getting a warning either.

Is this fixed as well? Or need an other issue?
