### ISSUE TITLE
Animation state machine Xfade time produces T pose appearing

### ISSUE THREAD

**Issue by ilievmark** [godotengine/godot#76162]
### Godot version

4.0.2 mono

### System information

Mac OS Ventura 13.2.1

### Issue description

If you setup cycled animation in state machine, with multiple states and internal state machine and put some transitions Xfade time to more than 0, T pose will start to appear for one frame

https://user-images.githubusercontent.com/32593471/232451449-3a62227d-66d8-4f91-a251-a98bcf8e9f16.mp4

For this example I setup internal state machine for idle animations state machine with 4 animations. Ive set Xfade time 0.2
for transitions from idle to jump and jump landing to idle. This is just example, but Im facing this issue using multiple internal state machines. In attached example, use conditions to swith states

### Steps to reproduce

Setup project from this report: https://github.com/godotengine/godot/issues/76159
Create internal state machine with some states
Create states to interact with the internal state machine
Between states and internal state machine create transitions and put Xfade time to value more that 0
T pose may appear in some cases

### Minimal reproduction project

[example.zip](https://github.com/godotengine/godot/files/11248861/example.zip)

**Comment by Calinou** [comment]
cc @TokageItLab

**Comment by TokageItLab** [comment]
I remember I have fixed the 1-frame glitch in #75759.

**Comment by ilievmark** [comment]
@TokageItLab 
It there any assumptions in which version it may be merged? 4.0.3?

**Comment by TokageItLab** [comment]
Maybe 4.1 since it has some breaking compatibilities.
