### ISSUE TITLE
Vulkan Forward+: Visual glitch appears in the radiance map at sizes higher or lower than the default

### ISSUE THREAD

**Issue by Lexpartizan** [godotengine/godot#76166]
### Godot version

4.02 stable

### System information

windows 11, GTX 1050, forward+

### Issue description

When I change the size of the radial size strange artifacts occur. If at a size of 256 the picture is expected, then at a smaller size for some reason the cubic nature of the picture becomes visible, and at a larger size incomprehensible darkened areas appear.
radial size = 32: Strange Cubic structure;
![image](https://user-images.githubusercontent.com/48552343/232478540-d422b997-7c07-44cb-a595-6d5cd0e0bbd7.png)
radial size = 64: Strange Cubic structure;
![image](https://user-images.githubusercontent.com/48552343/232478736-36a28b27-f36c-4a9b-98bf-d312e301f078.png)
radial size = 128: Strange Cubic structure;
![image](https://user-images.githubusercontent.com/48552343/232478960-f8395f39-35c5-45bb-9ebc-08f61689dce5.png)
radial size = 256: Awesome picture;
![image](https://user-images.githubusercontent.com/48552343/232479118-2ca4cacc-15f7-4765-9312-7ab045fa8152.png)
radial size = 512: Strange light windows;
![image](https://user-images.githubusercontent.com/48552343/232479244-14525caa-84ad-4e23-bf6e-91c41e4bbc64.png)
radial size = 1024: Strange light windows;
![image](https://user-images.githubusercontent.com/48552343/232479576-8a62aaf4-78bc-4c48-8aaf-5a1c58805f51.png)

### Steps to reproduce

Just change radial size in sky settings;

### Minimal reproduction project

[sky.zip](https://github.com/godotengine/godot/files/11249929/sky.zip)

**Comment by Calinou** [comment]
It looks like something isn't being resized relative to the default radiance map size (256), so the square appears too large or too small depending on the chosen radiance map size.

That said, the sky shader renders incorrectly for me in the MRP (4.0.2, GeForce RTX 4090 with NVIDIA 530.41.03):

![image](https://user-images.githubusercontent.com/180032/232537955-416c46ae-c9b6-4ea9-b03b-
e491101f9665.png)

**Comment by clayjohn** [comment]
Looks like the issue is only present when the update mode is set to "Automatic". When selecting a specific mode the issue goes away. So this issue likely comes from the situation where the "Automatic" update mode selects "Realtime" internally. When using the "Realtime" update mode the radiance size has to be 256 when we check that, we should also check if the update mode is set to "Automatic" and realtime is being used internally.

**Comment by Lexpartizan** [comment]
> 
I have been informed of this problem with the sky shader on new video cards.
The essence of the problem is that the noise function does not work correctly on them. Moreover, I tried different noise functions, including texture, but I got artifacts and incomprehensible circles.

This is what noise looks like on my nvidia 1050.
![image](https://user-images.githubusercontent.com/48552343/233777519-4f47e171-d59f-4730-9761-8739901c7232.png)

This is what noise looks like on Nvidia video cards of the new series.
![image](https://user-images.githubusercontent.com/48552343/233777428-43f077be-695f-43d7-8d79-901fdfd3bf79.png)
However, since I don't have a modern graphics card, I can't figure out what the reason is. It is possible that fract or floor are not working correctly. I have heard about the incorrect operation of noise with sine on new nvidia graphics cards, but in this case there is no sine.

This is a separate big story.

**Comment by Lexpartizan** [comment]
> Я могу подтвердить это при использовании метода визуализации Forward +. Этого не происходит при использовании метода рендеринга для мобильных устройств. Шейдер неба не загружается при использовании метода рендеринга совместимости.
> 
> Похоже, что размер чего-то не изменяется относительно размера карты сияния по умолчанию (256), поэтому квадрат кажется слишком большим или слишком маленьким в зависимости от выбранного размера карты сияния.
> 
> Тем не менее, шейдер sky некорректно отображается для меня в MRP (4.0.2, GeForce RTX 4090 с NVIDIA 530.41.03):[1](#user-content-fn-1-381c4bfcbbb781fea8d46825c1d787d1)
> 
> ![изображение](https://user-images.githubusercontent.com/180032/232537955-416c46ae-c9b6-4ea9-b03b-e491101f9665.png)
> 
> Можете ли вы воспроизвести это при использовании физического материала по умолчанию?
> 
> ## Примечания
> 1. Интересно, что при использовании Forward Mobile артефакты используют билинейную фильтрацию в отличие от фильтрации по ближайшему соседу. Это делает их более размытыми. [↩](#user-content-fnref-1-381c4bfcbbb781fea8d46825c1d787d1)

I have been informed of this problem with the sky shader on new video cards.
The essence of the problem is that the noise function does not work correctly on them. Moreover, I tried different noise functions, including texture, but I got artifacts and incomprehensible circles.

This is what noise looks like on my nvidia 1050.
![image](https://user-images.githubusercontent.com/48552343/233777519-4f47e171-d59f-4730-9761-8739901c7232.png)

This is what noise looks like on Nvidia video cards of the new series.
![image](https://user-images.githubusercontent.com/48552343/233777428-43f077be-695f-43d7-8d79-901fdfd3bf79.png)
However, since I don't have a modern graphics card, I can't figure out what the reason is. It is possible that fract or floor are not working correctly. I have heard about the incorrect operation of noise with sine on new nvidia graphics cards, but in this case there is no sine.

This is a separate big story.

**Comment by Lexpartizan** [comment]
> I can confirm this when using the Forward+ rendering method. This does not occur when using the Mobile rendering method. The sky shader fails to load when using the Compatibility rendering method.
> 
> It looks like something isn't being resized relative to the default radiance map size (256), so the square appears too large or too small depending on the chosen radiance map size.
> 
> That said, the sky shader renders incorrectly for me in the MRP (4.0.2, GeForce RTX 4090 with NVIDIA 530.41.03):[1](#user-content-fn-1-381c4bfcbbb781fea8d46825c1d787d1)
> 
> ![image](https://user-images.githubusercontent.com/180032/232537955-416c46ae-c9b6-4ea9-b03b-e491101f9665.png)
> 
> Can you reproduce this when using the default PhysicalSkyMaterial?
> 
> ## Footnotes
> 1. Interestingly, when using Forward Mobile, the artifacts use bilinear filtering as opposed to nearest-neighbor filtering. This makes them appear blurrier. [↩](#user-content-fnref-1-381c4bfcbbb781fea8d46825c1d787d1)

I have been informed of this problem with the my sky shader on new video cards.
The essence of the problem is that the noise function does not work correctly on them. Moreover, I tried different noise functions, including texture, but I got artifacts and incomprehensible circles.

This is what noise looks like on my nvidia 1050.
![image](https://user-images.githubusercontent.com/48552343/233777519-4f47e171-d59f-4730-9761-8739901c7232.png)

This is what noise looks like on Nvidia video cards of the new series.
![image](https://user-images.githubusercontent.com/48552343/233777428-43f077be-695f-43d7-8d79-901fdfd3bf79.png)
However, since I don't have a modern graphics card, I can't figure out what the reason is. It is possible that fract or floor are not working correctly. I have heard about the incorrect operation of noise with sine on new nvidia graphics cards, but in this case there is no sine.

This is a separate big story.
But I don't have a modern graphics card to deal with it. I got screenshots with the result of Schumann's work on the new video card after working a little with a person who wanted my sky shader for himself. He took these screenshots and that's how we found out that the noise is the problem. But it was too difficult to work further.

minimal shader is:

lowp float hash(lowp vec3 p) {p  = fract( p*0.3183099+0.1 )*17.0;return fract( p.x*p.y*p.z*(p.x+p.y+p.z) );}
lowp float noise3(lowp vec3 pos)
{
    lowp vec3 i = floor(pos); lowp vec3 f = fract(pos); f = f*f*(3.0-2.0*f);
	return mix(mix(mix( hash(i+vec3(0,0,0)), hash(i+vec3(1,0,0)),f.x),
					mix( hash(i+vec3(0,1,0)), hash(i+vec3(1,1,0)),f.x),f.y),
					mix(mix( hash(i+vec3(0,0,1)), hash(i+vec3(1,0,1)),f.x),
					mix( hash(i+vec3(0,1,1)), hash(i+vec3(1,1,1)),f.x),f.y),f.z);
}

void sky() { COLOR  = vec3(noise(rd*100.0));}

**Comment by Calinou** [comment]
This is due to how NVIDIA Turing and later GPUs handle `lowp`. As far as I know, unlike what's typically done on desktop where `lowp` and `mediump` are ignored, they convert it to use FP16, which can speed up certain operations but will break many shaders.

You can fix this particular shader by replacing all instances of `lowp` with an empty string.
