### ISSUE TITLE
The screen gets blurry and indistinct when I use a custom shader.

### ISSUE THREAD

**Issue by SneaK1ng** [godotengine/godot#76160]
### Godot version

v4.1.dev.custom_build.a7276f1ce

### System information

Win10, AMD 2600, GeForce GTX 1060, Vulkan API 1.3.205

### Issue description

I can’t confirm if this is a problem with Godot.

I set the color of a MultiMesh’s instance in C++ and pass it to a shader to use.
In C++:
```
Color rendering_data = Color(0, 1, 0);
if (use_colors)
{
	set_instance_color(instance_id, rendering_data);
}
```
In shader:
```
uniform vec3 palette[18];
void fragment(){
	int index = int(COLOR.g);
	ALBEDO.rgb = palette[index].rgb;
}

```
Editor settings:
![image](https://user-images.githubusercontent.com/6891132/232417981-44b92b98-e801-4804-a01f-3d722848ed38.png)

Then I got the weird screen effect below:
![image](https://user-images.githubusercontent.com/6891132/232418603-b41acbfa-d4b4-4dae-9d24-66f3af10a0ed.png)

~~And the problem will be gone if I do the same thing in GDScript. It seems to only happen when I use C++ in my use case!~~

Does someone have any ideas about this problem?

### Steps to reproduce

1. Click add button.
2. Press 'W' or 'S' to move.

### Minimal reproduction project

[test_set_instance_color.zip](https://github.com/godotengine/godot/files/11248632/test_set_instance_color.zip)

**Comment by AThousandShips** [comment]
Please provide a reproduction project to make this easier to troubleshoot, your information is somewhat lacking, how do you set the palette?

**Comment by SneaK1ng** [comment]
> Please provide a reproduction project to make this easier to troubleshoot, your information is somewhat lacking, how do you set the palette?
> 
> At minimum we need more of the code you're using and details, also you accidentally added the image to the code section instead of separately so no one can see your settings

I don't think it related to https://github.com/godotengine/godot/issues/76157#issuecomment-1510822139
I have edited the color array manually.

```
[gd_resource type="ShaderMaterial" load_steps=2 format=3 uid="uid://vx2or5oin038"]

[ext_resource type="Shader" path="res://world/shader/terrain/terrain.gdshader" id="1_c44v1"]

[resource]
render_priority = 0
shader = ExtResource("1_c44v1")
shader_parameter/palette = PackedColorArray(1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1)
```

Sorry for no reproduction project! I will try to make a reproduction project.

**Comment by AThousandShips** [comment]
Are you sure you're following the steps in the [documentation](https://docs.godotengine.org/en/stable/classes/class_multimesh.html#class-multimesh-method-set-instance-color)? Looks like the colour is undefined to me and causing random noise

**Comment by SneaK1ng** [comment]
> Are you sure you're following the steps in the [documentation](https://docs.godotengine.org/en/stable/classes/class_multimesh.html#class-multimesh-method-set-instance-color)? Looks like the colour is undefined to me and causing random noise

It will be fine with the screen if I change the shader code to below. So this means the steps of set_instance_color() in C++ have no problem.
```
void fragment(){
	ALBEDO.rgb = COLOR.rgb;
}
```
![image](https://user-images.githubusercontent.com/6891132/232427592-12f0cd55-1ae0-4bb8-83dc-97c59c008604.png)

**Comment by AThousandShips** [comment]
Also can you show what `get_shader_uniform_list` returns on the shader?

**Comment by AThousandShips** [comment]
The correct type for the parameter is indeed `PackedVector3Array` as it is a `vec3`

**Comment by AThousandShips** [comment]
Wait, your palette is size 18?

What happens if you do:
```
uniform vec3 palette[3];
```

Also in the second case did you use `vec4`?

**Comment by SneaK1ng** [comment]
> Wait, your palette is size 18?
> 
> What happens if you do:
> 
> ```
> uniform vec3 palette[3];
> ```
> 
> Also in the second case did you use `vec4`?

I made a reproduction project \o/
You can test it now.
[test_set_instance_color.zip](https://github.com/godotengine/godot/files/11248624/test_set_instance_color.zip)

**Comment by AThousandShips** [comment]
You've got a ton of `!v.is_finite()` errors seems like all your transformations are broken

**Comment by SneaK1ng** [comment]
> You've got a ton of `!v.is_finite()` errors seems like all your transformations are broken

May be related to https://github.com/godotengine/godot/issues/74095

**Comment by AThousandShips** [comment]
It works fine for me, renders just green squares:
![image](https://user-images.githubusercontent.com/96648715/232449894-a5e45fe9-6fa1-457b-88e2-75a84ec53c5e.png)

**Comment by SneaK1ng** [comment]
> It works fine for me, renders just green squares: ![image](https://user-images.githubusercontent.com/96648715/232449894-a5e45fe9-6fa1-457b-88e2-75a84ec53c5e.png)

but...I have no idea..
![image](https://user-images.githubusercontent.com/6891132/232450206-5b08143b-484a-4859-9b06-03d57b304eaf.png)

**Comment by AThousandShips** [comment]
Sounds like it then yeah, try updating your drivers

**Comment by bitsawer** [comment]
I get the same visual error, NVIDIA GTX 970, but I think it's because vertex color `COLOR` is not actually initialized anywhere in the mesh? Thus `COLOR.g` reads random garbage which might be 0 if you are lucky (or unlucky).

**Comment by AThousandShips** [comment]
That's a strange hardware specific issue then! No problem on AMD Radeon RX 6750 XT

**Comment by SneaK1ng** [comment]
I have updated my graphic driver. But this problem still happens.
GeForce GTX 1060 5G 516.94→531.61

**Comment by AThousandShips** [comment]
Can you test it with a custom mesh with vertex colors assigned using `SurfaceTool` just to pin down if this is caused by the colors being unassigned?

**Comment by SneaK1ng** [comment]
> Can you test it with a custom mesh with vertex colors assigned using `SurfaceTool` or just manually configured just to pin down if this is caused by the colors being unassigned?

Nothing changed
```
func add_fish():
	var multimesh = $MultiMeshInstance3D.multimesh;
	var color = Color(0, 1, 0)

	var st = SurfaceTool.new()
	st.begin(Mesh.PRIMITIVE_TRIANGLES)
	st.set_color(color)
	st.commit(multimesh)

	for i in range(multimesh.get_instance_count()):
		var pos = Transform3D()
		pos = pos.translated(Vector3(i, 0, 0))
		multimesh.set_instance_transform(i, pos)
		multimesh.set_instance_color(i, color)
```
![image](https://user-images.githubusercontent.com/6891132/232462595-8dd05173-090e-4327-a5dc-2dbbecd6c263.png)

**Comment by AThousandShips** [comment]
That code doesn't look right, it doesn't create any triangles nor does it update the mesh, it doesn't work on `Multimesh` at all

**Comment by bitsawer** [comment]
Might also need to fix the transform values, there's infinites and NAN's which might probaby cause some issues.

Also double check https://docs.godotengine.org/en/latest/classes/class_multimesh.html#class-multimesh-method-set-instance-color. Is material `vertex_color_use_as_albedo` enabled?

![infs](https://user-images.githubusercontent.com/22456603/232463293-e70d0ac8-a6c9-4f90-8f18-4d5726ee43a1.png)

**Comment by AThousandShips** [comment]
Try adding this, it's kinda hacky but should help locate the problem:
```
var old_mesh = multimesh.get_mesh()
var new_mesh := ArrayMesh.new()
var old_arrays = old_mesh.surface_get_arrays(0)
old_arrays[Mesh.ARRAY_COLOR] = PackedColorArray([ Color(1, 1, 1), Color(1, 1, 1), Color(1, 1, 1), Color(1, 1, 1)])
new_mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, old_arrays)
new_mesh.surface_set_material(0, old_mesh.surface_get_material(0))
multimesh.mesh = new_mesh
```

**Comment by AThousandShips** [comment]
Then we've eliminated the possible issue of vertex colors being unset as the cause!

What happens if you just do:
```
ALBEDO.rgb = palette[0].rgb;
```

**Comment by SneaK1ng** [comment]
> Then we've eliminated the possible issue of vertex colors being unset as the cause!
> 
> What happens if you just do:
> 
> ```
> ALBEDO.rgb = palette[0].rgb;
> ```
![image](https://user-images.githubusercontent.com/6891132/232473782-e22af5ac-f4c3-4f41-92c0-f65a039fdff6.png)

**Comment by AThousandShips** [comment]
So it is not related to the palette but just `COLOR`

**Comment by SneaK1ng** [comment]
> So it is not related to the palette but just `COLOR`

One thing I noticed is that it works fine if I don't set the rotation of the camera!
![image](https://user-images.githubusercontent.com/6891132/232474688-2320c26c-cc24-4452-b87d-9a5c58dbb923.png)

**Comment by AThousandShips** [comment]
That is very odd

**Comment by SneaK1ng** [comment]
compatibility mode, btw.
![image](https://user-images.githubusercontent.com/6891132/232680213-536b5435-3fa7-4970-80df-aac4e3dea386.png)

**Comment by bitsawer** [comment]
I was going through some other multimesh issues and decided to re-check this one. This seems to be a driver issue with interpolation.

By default, using COLOR in fragment shader interpolates the value across vertices. Seems like NVIDIA does some optimizations and shortcuts which means that interpolation between 1.0 and 1.0 can actually sometimes be something else than 1.0, in this case probably something like 0.999999 etc. Also explains why this doesn't happen on some systems. You can test with this:

```glsl
void fragment() {
    if (COLOR.g == 1.0) {
        ALBEDO = vec3(1, 0, 0);
    }
    else if (COLOR.g < 1.0) {
        ALBEDO = vec3(0, 1, 0);
    }
    else {
        ALBEDO = vec3(0, 0, 1);
    }
}
```

On some NVIDIA (and maybe some other) devices, this can output a several different fragment colors even if you set 1.0 for all instance colors. You can work around this by using a `flat` varying to avoid interpolation, like this:

```glsl
varying flat vec4 color;

void vertex() {
    color = COLOR;
}

void fragment() {
    if (color.g == 1.0) {
        ALBEDO = vec3(1, 0, 0);
    }
    else if (color.g < 1.0) {
        ALBEDO = vec3(0, 1, 0);
    }
    else {
        ALBEDO = vec3(0, 0, 1);
    }
}
```

Kind of a nasty gotcha, but not much we can do about it.  I'm not sure if OpenGL or Vulkan specs have anything to say about this either, I assume this kind of optimization is allowed. And even if it is not, you'll have to work around it anyway unless you want to drop support for NVIDIA cards.

**Comment by Zireael07** [comment]
We really need a docs page on those driver gotchas (I remember a noise shader issue that turned out to be a driver gotcha too)
