### ISSUE TITLE
Separate coroutine calls from function calls

### ISSUE THREAD

**Issue by raymoo** [godotengine/godot#7617]
Currently you can't factor out any code with a yield() into a separate function, because yields only yield up to the next function call. For example:
```
func retrieve_burrito():
    initiate_burrito_search()
    return yield(self, "burrito_acquisition")
```
will not work.

I propose a function of some kind `make_coroutine` which calling as `make_coroutine(obj, "method", args...)` creates a new coroutine state as if the method had yielded at the very beginning.

To make the next part easier to state, call any resume from a coroutine state created by this method a "coroutine call".

Whenever a function yields, instead of immediately returning from the function it yielded in, it will cause the innermost coroutine call containing the yield to return. If it is not contained within any coroutine call, it will cause the current function to return like yield currently behaves.

**Comment by raymoo** [comment]
I'm pretty sure it's still reproducible, since hasn't been much change to the coroutines API.

**Comment by bojidar-bg** [comment]
@raymoo Isn't this fixed by #8573?
Now you can do this:
```gdscript
func retrieve_burrito():
    yield(initiate_burrito_search(), "completed")
    return yield(self, "burrito_acquisition")
```

**Comment by raymoo** [comment]
@bojidar-bg I want it to also work in the case that I am not waiting on a signal and want to provide values to yield myself.

**Comment by bojidar-bg** [comment]
@raymoo Well, that's #1385 then, no?

**Comment by raymoo** [comment]
@bojidar-bg I'm not sure if I understand Python `yield from` enough to say that I could do what I want with it, but I don't see how I could use it to implement something in _process or somewhere where I call a coroutine that yields the request, and then I wait a few frames and resume the coroutine with the request response.

I know though that if I can implement Lua coroutines in terms of `yield from` then that would be enough to do what I want. Is that possible?

**Comment by bojidar-bg** [comment]
@raymoo You should already be able to resume a coroutine started in _process after a few frames or after some signal is hit even in the current version. Examples:
```gdscript
func my_coroutine():
    print(1)
    yield() # Wait for .resume()
    print(2)
    yield(get_tree().create_timer(5.0), "completed") # Wait for signal
    print(3)

var coroutine = null
func _on_btn_pressed():
    if coroutine == null:
        coroutine = my_coroutine() # Start new
    else:
        coroutine.resume() # Resume current
```
Will result in (with proper inputs and timing):
```
# Button click
Print: 1
# Button click
Print: 2
# 5 seconds later (clicks might result in errors)
Print: 3
```

**Comment by raymoo** [comment]
@bojidar-bg Yes but can the yield be inside another function? Like this:

```
func get_burrito_ingredients(veggies):
  var ingredient_list = ["tortilla", "beans"]
  if veggies:
    ingredient_list += ["pico de gallo", "guac"]
  return yield(["give me burrito ingredients", ingredients])

func prepare_burrito():
  var ingredients = get_burrito_ingredients(true) # Not what I want - returns a coroutine, not burrito ingredients
  return cook_burrito(ingredients)

# How I imagine coroutines might be used
var burrito_coroutine = run_coroutine(prepare_burrito)
while burrito_coroutine.not_done(): # I don't remember how you actually check this
  while !burrito_queue.empty():
    pass
  burrito_coroutine.resume(burrito_queue.get_burrito_ingredients())
```

**Comment by MInner** [comment]
I will duplicate a conclusion from discussing with @raymoo here: I believe what he/she meant was that in gdscript (according to my understanding of gdscript at least) there is apparently no way to communicate the temporary result of execution to the caller without signals (at least I get `Expected ',' after first argument of 'yield'` error when trying to do that) - that seems to be fairly different from the semantics of `yield` in other languages where you can do an equivalent of (adapting an example from docs) 

```
func my_func():
   print("Hello")
   var v = yield("cruel")
   print(v)  # world
   return "cheers!"

func _ready():
    var y = my_func()
    # Function state saved in 'y'.
    var cruel, y = y.resume()  # run until first yield and return the thing in yield(thing)
    var cheers, y = y.resume("world")     # 'y' resumed and is now an invalid state.
    print(cheers)
```
- in most languages resume mutates the state, but considering that in gdscript it does not, one has to return new state together with the result.

An equivalent program in current gdscript would probably look like (it does not work, so I am doing something wrong).

```

signal partial_result(string)

func my_func():
   print("Hello")
   emit_signal('partial_result', 'cruel')
   var v = yield()
   print(v)  # world
   return "cheers!"

func _ready():
    var handle = my_func()
    var cruel = yield(handle, 'partial_result')
    print(cruel)
    var cheers = handle.resume("world")
    print(cheers)
```

**Comment by raymoo** [comment]
@MInner Actually I never realized that you can't pass values back to the caller, which I assumed was possible since you could pass values to the coroutine. That would also be an important issue to me, but that is not what this issue is about. You could work around it by setting a value in an array or something to pass information back.

The issue is about where control goes when calling yield. In Lua, you might have code like this:
```
local function addToVal(x)
  local v = coroutine.yield()
  return v + x
end

local function wait_and_print()
  local v_plus_5 = addToVal(5)
  print(v_plus_5)
end

-- Create the coroutine
local co = coroutine.create(wait_and_print)

-- Begin running the coroutine
coroutine.resume(co) -- The coroutine starts running and pauses at the yield in addToVal
coroutine.resume(co, 10) -- The coroutine resumes execution, with the yield in addToVal returning 10.
-- At this point, the coroutine has finished and "15" should have printed.
```
This does not work in Godot, because yielding in a coroutine always causes the enclosing function to return, rather than the user being able to control where the coroutine yields to. See this (not working) translation to GDScript:
```
func addToVal(x):
  var v = yield()
  return v + x

func wait_and_print():
  # The following call breaks, because instead of the yield in addToVal bubbling up,
  # the addToVal here immediately returns a function state.
  var v_plus_5 = addToVal(5)

  # Not sure what happens, because I don't know if GDScriptFunctionState is printable
  print(v_plus_5)

# Create and start running the coroutine
var co = wait_and_print() # This will either crash or print the function state, not sure

co = co.resume(10) # Doesn't work because co is not a GDScriptFunctionState
```
I don't see how this could be worked around. If you look at the page at https://www.lua.org/pil/9.1.html, you can see yield in Lua causes the innermost enclosing call to `coroutine.resume` to return, not the enclosing function call. That's the behavior I want for coroutines. I don't need coroutine resumption to mutate instead of return a value, though that might make more sense if you can't call resume on a `GDScriptFunctionState` more than once. I want yields to bubble up to the point I chose.

**Comment by raymoo** [comment]
Also I'm guessing your code doesn't work because you yielded on the partial result signal after it was already emitted.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
