### ISSUE TITLE
Can't use full .net SDK in godot4?

### ISSUE THREAD

**Issue by alwaysmy** [godotengine/godot#76178]
### Godot version

4.0.2

### System information

Windows10

### Issue description

In godot4, when I try to code 
```c#
using System.IO.Ports;
...
SerialPort port;//from Ports
```
But those codes are not working because ``System.IO`` don't contain ``Ports``  while godot3 is OK. (I have installed .net sdk 6 from microsoft‘s website)

As I know ,godot 4 embed the .NET runtime , so it is different from godot3, so, is there any way to use a external .net sdk in godot4? 
or that is just because I didn't find the right way?

### Steps to reproduce

1、creat a project in godot4 
2、use a script to do something :
```c#
using Godot;
using System;
using System.IO.Ports;
// using System.IO.Ports;

public partial class main_ui : Control
{
	// Called when the node enters the scene tree for the first time.
	public override void _Ready()
	{
		GD.Print("Hello, world!");
		SerialPort port;//don't working
		// foreach (string s in SerialPort.GetPortNames())
		// {
		// 	GD.Print("  hello: {0}", s);
		// }
	}

	// Called every frame. 'delta' is the elapsed time since the previous frame.
	public override void _Process(double delta)
	{
	}

}
```
3、then run it and will fail.

### Minimal reproduction project

[Gd4csharp2.zip](https://github.com/godotengine/godot/files/11253970/Gd4csharp2.zip)

**Comment by Logical-sh** [comment]
In dotnet core System.IO.Ports is not part of the framework, its an optional nuget package. Did you try installing the package in the godot 4 project?
https://www.nuget.org/packages/System.IO.Ports/6.0.0

**Comment by alwaysmy** [comment]
Installing the package works.   Thanks you so much , I'm not  familiar with .net so  I didn't think it would be such a simple approach.

**Comment by Logical-sh** [comment]
No problem! Dotnet core moved to a more modular approach as an option instead of a fat framework, it can be useful when you want to make more trimmed experiences that you don't have to ship things that aren't needed!
