### ISSUE TITLE
Inability to delete imported files in Web Editor

### ISSUE THREAD

**Issue by cheesebellies** [godotengine/godot#76187]
### Godot version

4.0.1.stable.official

### System information

Google Chrome browser, on ChromeOS

### Issue description

Upon trying to delete any asset imported into a project in the web editor, an error occurs: `Cannot delete`.

### Steps to reproduce

Start a new project at `https://editor.godotengine.org/releases/latest/`, and import any file (a png in my case), then attempt to delete it.

### Minimal reproduction project

The project was unable to `export project source`.

**Comment by Calinou** [comment]
> Google Chrome browser, on ChromeOS

Can you reproduce this on Windows/macOS/Linux?

**Comment by cheesebellies** [comment]
I don't have a Windows/macOS/Linux machine, so I can't try. I would Assume that it's not, or this bug would have been reported before.

**Comment by Calinou** [comment]
- Duplicate of https://github.com/godotengine/godot/issues/70975.
