### ISSUE TITLE
Running platformer demo project gives an error in the console

### ISSUE THREAD

**Issue by Reinards** [godotengine/godot#7619]
**Operating system or device - Godot version:**
Ubuntu 16.04 LTS
Godot v2.1.1

**Issue description:**

I downloaded the example projects from github. I imported "Platformer" under 2d/platformer/
If I run it straight from the project manager, it opens up, but the character is not moving.
If I click edit and then run, it gives an error in the console. The debugger says - Invalid call. Nonexistent function 'move_and_slide' in base 'KinematicBody2D (player.gd)'.

**Steps to reproduce:**
1.Download the example projects.
2.Import the "Platformer" project
3.Click edit
4.Run the stage.tscn scene

**Link to minimal example project:**
:

**Comment by vnen** [comment]
The `master` branch of the demos repository is not compatible with 2,1.x. You have to download the `2.1` branch.

**Comment by Reinards** [comment]
Okay, thank you!

**Comment by bojidar-bg** [comment]
Closing as invalid, though it can be reopened.
If there is a bug in the demo itself (i.e. other demos still work), please reopen at [`godotengine/godot-demo-projects`](https://github.com/godotengine/godot-demo-projects).
Otherwise, if Godot itself is doing something quirky, we can reopen this one.
