### ISSUE TITLE
CJK characters repeated when autowrapped

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#76198]
### Godot version

4.0.2.stable, master(d6dde81)

### System information

Arch Linux

### Issue description

When using Arbitrary or Word (Smart) auto wrap mode and the label's width is smaller than one character, CJK characters are repeated unexpectedly when autowrapped.

In the following screenshot, the three labels are all narrower than a character:

* にほんご
* 简体中文
* 한국어

| Expected | Actual |
| --- | --- |
| ![ksnip_20230418-152604](https://user-images.githubusercontent.com/372476/232703096-5b9819ec-0a48-4f54-9ba9-754f7a8b6229.png) | ![ksnip_20230418-152547](https://user-images.githubusercontent.com/372476/232703148-57c07818-aa99-4638-aa6b-5a55d3b0cd1c.png) |

All characters expect the last one is repeated.

### Steps to reproduce

Use the MRP.

### Minimal reproduction project

[test-4.zip](https://github.com/godotengine/godot/files/11259001/test-4.zip)

**Comment by Rindbee** [comment]
```GDScript
extends Control

func _ready():
	var text_server := TextServerManager.get_primary_interface()
	var font:= get_theme_default_font()
	var font_rids := font.get_rids()
	var shaped_id = text_server.create_shaped_text(TextServer.DIRECTION_AUTO,TextServer.ORIENTATION_HORIZONTAL)
	
	text_server.shaped_text_add_string(shaped_id, "简体中文", font_rids, 16)
	
	var glyph_count = text_server.shaped_text_get_glyph_count(shaped_id) # 4
	var line_breaks := text_server.shaped_text_get_line_breaks(shaped_id,150,0)
	var new_glyph_count = text_server.shaped_text_get_glyph_count(shaped_id) # 7
	
	print(glyph_count == new_glyph_count) # false
	pass
```

`shaped_text_get_line_breaks()` will change the result of `shaped_text_get_glyph_count()`.
