### ISSUE TITLE
Camera Zoom affects Menu Popup position and size

### ISSUE THREAD

**Issue by WhalesState** [godotengine/godot#76194]
### Godot version

4.0.2.stable

### System information

Ubuntu

### Issue description

when zooming in and then pressing on any menu button the popup position and size changes depends on the current Camera 2d zoom value, if Zoom is equal (1, 1) it works normaly but when zoomed in the popup keeps moving down and its width changes

### Steps to reproduce

open the project attached, it's a 2d node and has camera and canvas layer as children, press on menu button or color wheel picker shape button and see the popup appears far away from the button and its size and position gets affected by 2d camera zoom, change the camera zoom by pressing on zoom in or zoom out buttons and try again the menu only appears normaly if the zoom is (1, 1)

### Minimal reproduction project

[test_project.zip](https://github.com/godotengine/godot/files/11257709/test_project.zip)

**Comment by KoBeWi** [comment]
Sounds related to #38494

**Comment by WhalesState** [comment]
it sounds related to all popups too, the popup size and position are multiplied by camera zoom.

**Comment by WhalesState** [comment]
have tried to search the source code why the Camera2D zoom affects the popups with no luck, if anyone can guide me i will appreciate it.

**Comment by Sauermann** [comment]
> if anyone can guide me i will appreciate it

The `Camera2D` works by changing the CanvasTransform of the Viewport. Currently this CanvasTransform is not taken into account for positioning the popup. For code-details, have a look at the linked PR.
