### ISSUE TITLE
Renaming a name present in a NodePath to an invalid name will wrongly update the NodePath

### ISSUE THREAD

**Issue by ajreckof** [godotengine/godot#76192]
### Godot version

4.1.dev (4d5f10fc3a)

### System information

MacOS 13.3 M1 Pro

### Issue description

If you have a NodePath pointing to a node and you rename a node on this path to a value that is already used by one of his siblings, the NodePath will be updated with the value you set while the node will be updated with another unused value created by adding a number after the value you set.

### Steps to reproduce

1. create a root and two children
2. On the root export a NodePath and set it to one of the children
3. Rename the referenced child to the name of the other child
4. now the NodePath points to the other child

### Minimal reproduction project

N/A

**Comment by nongvantinh** [comment]
The latest version of the master branch was tested using v4.1.dev.custom_build [578ca94ef] and the issue could not be replicated.

The computer's operating system is Microsoft Windows 10 Pro, version 10.0.19045 Build 19045. The system is manufactured by Acer and is a 64-bit PC with an Intel Core i5-8265U CPU @ 1.60GHz, 4 cores, and 8 logical processors. The BIOS version is Insyde Corp. V1.04, 1/15/2019, and the system is in UEFI mode. The computer has 4.00 GB of RAM, with 3.86 GB of total physical memory and 309 MB of available physical memory. The device does not have kernel DMA protection or virtualization-based security, and elevation is required to view device encryption support. The computer's time zone is SE Asia Standard Time. Hyper-V - VM Monitor Mode Extensions, Second Level Address Translation Extensions, Virtualization Enabled in Firmware, and Data Execution Protection are all enabled.

**Comment by ajreckof** [comment]
I can still reproduce on latest master 1becfea37c

https://user-images.githubusercontent.com/66184050/235124770-de0ccd75-f508-484f-a706-1dc7415d5a9c.mp4

**Comment by ajreckof** [comment]
That is exactly what I described in my first report. The only difference between the video and what I set as steps to reproduce is that I renamed not the pointed node but one that was a parent of the pointed node so that the NodePath would point to a non existent node and it will show an error.
I was going to make a fix at the start of next week but if you feel confident in making a fix, I'll gladly review it. Feel free to ping me when you have done the PR.

**Comment by KoBeWi** [comment]
I can't reproduce it on master.

https://github.com/godotengine/godot/assets/2223172/4a5ced57-c114-4143-b5e1-5ac29d9f3bae

Am I missing something?

**Comment by ajreckof** [comment]
Did you make sure to use `NodePath` and not `Node`?
 I can still reproduce on latest master personally

https://github.com/godotengine/godot/assets/66184050/b12c8e94-383e-4079-85e4-eec631ddd23b

**Comment by KoBeWi** [comment]
Ah right, I used Node.
