### ISSUE TITLE
Richtextlabel meta links shouldn't open when swiping to scroll

### ISSUE THREAD

**Issue by Procyon3** [godotengine/godot#7620]
**Version and use case**

I'm using Godot 2.1.1 to make an Android app. The app displays a long text with a lot of meta links.

**Description**

Scrolling a Richtextlabel on Android is done with swiping, but if the initial position that you put your finger to swipe is a meta link then the meta link will be opened.

If a large percentage of the Richtextlabel area is meta links, then it's uncomfortable to scroll.

I think a meta link should only be activated on release of the press or click.

Additionally, on Android to access the home button in a fullscreen program you have to swipe from the top of the screen downward. This swiping motion also causes the Richtextlabel to scroll if your finger goes over it. I don't think that that should happen.

**Comment by bojidar-bg** [comment]
Distantly related to #7612

**Comment by reduz** [comment]
links probably should be detected on mouse-up and have a highlight, and action cancelled on scroll.
RichTextLabel code is here:
https://github.com/godotengine/godot/blob/master/scene/gui/rich_text_label.cpp
