### ISSUE TITLE
WindowDialogs shown with popup() do not emit mouse_exited correctly

### ISSUE THREAD

**Issue by RayKoopa** [godotengine/godot#7622]
**Operating system or device - Godot version:**
Godot 3.0 built from master

**Issue description:**
The `mouse_exited` signal is erroneously not emitted in the following case:
- A WindowDialog has been shown with `popup()` (`exclusive` doesn't matter) and the mouse pointer has entered this one.
- The pointer leaves the area of the dialog, but still hovers over another control.

The signal for the `WindowDialog` gets emitted as soon as the pointer moves to an empty area with no control under it - not only "too late" but also when it actually left a totally different control rather than the `WindowDialog`.

This sounds similar to https://github.com/godotengine/godot/issues/2710, but it only happens with `WindowDialog` nodes.

**Steps to reproduce:**
Testing it with my resizable dialogs it becomes even more visible: The cursor doesn't change back, even though it should change it `CURSOR_ARROW` on exiting the window.
![example](https://cloud.githubusercontent.com/assets/9631152/22223959/2be3492a-e1bd-11e6-80bc-28b225300d21.gif)

**Link to minimal example project:**
Click on "Show WindowDialog" and watch the output.
[buggy_mouse_exit.zip](https://github.com/godotengine/godot/files/725015/buggy_mouse_exit.zip)

**Comment by bojidar-bg** [comment]
Note that this is probably related to the fact that WindowDialogs are "toplevel" controls.
