### ISSUE TITLE
`Array[DerivedType]` can't be assigned to a variable of type `Array[BaseType]`

### ISSUE THREAD

**Issue by cptchuckles** [godotengine/godot#76228]
### Godot version

4.0.2.stable.mono.official.7a0977ce2

### System information

`Linux x1e2 6.2.6-artix1-1 #1 SMP PREEMPT_DYNAMIC Wed, 15 Mar 2023 20:10:40 +0000 x86_64 GNU/Linux`

### Issue description

A typed array cannot be assigned to a derived-typed array, even though the elements of the derived-typed array would fully qualify to be in the base-typed array.  I think this operation should be allowed.

```gdscript
var nodes: Array[Node]
var node2ds: Array[Node2D]

# later
nodes = node2ds  # SCRIPT ERROR: Parse Error: Value of type "Array[Node2D]" cannot be assigned to a variable of type "Array[Node]".
```
The obvious work around would be to use `nodes.assign(node2ds)`... But this isn't possible when the typed array needs to be assigned as a method parameter:
```gdscript
func takes_nodes(arr: Array[Node]) -> void:
    print(arr.size())


# later
takes_nodes(node2ds) # SCRIPT ERROR: Parse Error: Invalid argument for "takes_nodes()" function: argument 1 should be "Array[Node]" but is "Array[Node2D]".
```

### Steps to reproduce

1) Save this somewhere as `typed-arrays.gd`:
```gdscript
extends SceneTree


class BaseClass:
    extends RefCounted

class DerivedClass:
    extends BaseClass


func take_things(arr: Array[BaseClass]) -> int:
    return arr.size()


func _init() -> void:
    var things: Array[BaseClass] = []
    things.push_back(DerivedClass.new())
    print(things.size())  # works fine

    var derived_things: Array[DerivedClass]
    derived_things.push_back(DerivedClass.new())
    derived_things.push_back(DerivedClass.new())
    derived_things.push_back(DerivedClass.new())
    # print(take_things(derived_things))  # SCRIPT ERROR: Parse Error: Invalid argument for "take_things()" function: argument 1 should be "Array[BaseClass]" but is "Array[DerivedClass]".
    # things = derived_things # SCRIPT ERROR: Parse Error: Value of type "Array[DerivedClass]" cannot be assigned to a variable of type "Array[BaseClass]".

    quit.call_deferred()


# vim:et:ts=4:sts=4:sw=4
```
2) Invoke it with the `--script` option to see that it runs without the offending lines:
```
${GODOT_4_EXECUTABLE} --headless --script typed-arrays.gd
```
3) Uncomment line(s) 24 and/or 25 and run it again.
4) Observe type errors that are hard to work around.

### Minimal reproduction project

n/a

**Comment by and-rad** [comment]
Is this even possible in other somewhat statically typed languages? This type of functionality is usually implemented using generics. GDScript's version of that would be to just leave out the type and change the function signature to `take_things(arr: Array) -> int`.

**Comment by NotDaze** [comment]
Would love to see this fixed/changed, it is making it much more difficult for me to work with typed arrays.

If you have a function parameter that expects a BaseClass, you can pass a DerivedClass. If you have a function parameter that expects an Array[BaseClass] you _can't_ pass an Array[DerivedClass]. That feels very inconsistent to me.

Also, the editor doesn't care, an error only occurs when you run the script.

**Comment by AThousandShips** [comment]
But `Array[Derived]` *isn't* derived from `Array[Base]`, this is not the same, it's not inconsistent

The casting of the derived type into base is different from an array of derived to base

**Comment by cptchuckles** [comment]
Admittedly, I'm starting to see why this limitation exists.  Seeing the C++ equivalent of this problem drives it home for me, because my instinct would have been to use `std::copy` to fill `x` with `y` elements instead of simple assignment, which would be equivalent to using `nodes.assign(node2ds)` in my GDScript example.

**Comment by fkeyzuwu** [comment]
Reading through all this and trying to find a solution.. I just wish there was a way to do in place replacement of the array, since right now i couldn't find a way to make something like this a one liner:
```
var sprite_array: Array[Sprite2D]
sprite_array.assign(get_children())
```
Maybe have a utility function to do this behind the scenes inside the engine code, that we can easily use in scripting?
