### ISSUE TITLE
Objects that use a shader with render_mode wireframe will cause memory to increase continuously!!

### ISSUE THREAD

**Issue by prominentdetail** [godotengine/godot#76237]
### Godot version

4.0.2

### System information

Windows 10

### Issue description

I have a meshinstance3d with a shader attached, and this is inside a subviewport. ( I instanced a bunch to make the memory rise faster, for testing purposes ).
The shader uses render_mode wireframe.
Whenever the object is onscreen, the memory will increase continuously! If the object goes offscreen, it will stop.
If I remove render_mode wireframe from the shader, the memory won't increase.
If I set debug_mode to wireframe on the subviewport, the memory won't increase.

Edit: I originally thought a subviewport was required, but it isn't. It happens even when there are no subviewports being used!

### Steps to reproduce

Open the attached project, and run the test.tscn
Watch as your memory continues to go up.
It stops if you either remove render_mode wireframe from the shader, or if you set the subviewport debug_mode to wireframe.
It also stops if the object isn't onscreen.

### Minimal reproduction project

[subViewportWireframeBug.zip](https://github.com/godotengine/godot/files/11267138/subViewportWireframeBug.zip)

**Comment by Calinou** [comment]
I can confirm this on 4.0.2 (Linux, GeForce RTX 4090 with NVIDIA 530.41.03).

The higher the FPS, the more RAM leaks. With `--disable-vsync`, I can reach 380 FPS which leaks about 500 MB of memory per second.

**Comment by prominentdetail** [comment]
Just discovered that this bug doesn't require being in a subviewport. It happens even if you don't use a subviewport! I'll edit the title.

**Comment by myaaaaaaaaa** [comment]
This is caused by a pipeline caching bug. In line 81 of `PipelineCacheRD::get_render_pipeline()`, it attempts to load a pre-existing pipeline from the cache based on supplied parameters like `p_wireframe`:

https://github.com/godotengine/godot/blob/1d14c054a12dacdc193b589e4afb0ef319ee2aae/servers/rendering/renderer_rd/pipeline_cache_rd.h#L72-L90

If a pre-existing pipeline is not found, it calls `PipelineCacheRD::_generate_version()` to generate a new one:

https://github.com/godotengine/godot/blob/1d14c054a12dacdc193b589e4afb0ef319ee2aae/servers/rendering/renderer_rd/pipeline_cache_rd.cpp#L35-L71

However, `p_wireframe` is overridden in line 39 of this function, so the newly cached pipeline will never match the original `p_wireframe` given to `get_render_pipeline()`, and a new one ends up being generated every time it is called (every frame?).

**Comment by clayjohn** [comment]
> However, p_wireframe is overridden in line 39 of this function, so the newly cached pipeline will never match the original p_wireframe given to get_render_pipeline(), and a new one ends up being generated every time it is called (every frame?).

Maybe even multiple times per frame if the same pipeline is used. 

The ``rasterization_state.wireframe`` is set by the shader, while ``p_wireframe`` comes from ``get_debug_draw_mode() == RS::VIEWPORT_DEBUG_DRAW_WIREFRAME`` and is passed to the pipeline when grabbing the pipeline state.

I guess the solution is to check ``rasterization_state.wireframe`` as well as ``p_wireframe`` to see if the version exists. As if wireframe is set in the shader wireframe is always enabled (even if ``p_wireframe``) is false

https://github.com/godotengine/godot/blob/578ca94ef6351cb6c31b1addf8b3c36577376bd4/servers/rendering/renderer_rd/pipeline_cache_rd.h#L81

**Comment by Calinou** [comment]
I wonder if this issue is what causes wireframe drawing to be very slow in Direct3D 12, as I indicated in one of my comments in https://github.com/godotengine/godot/pull/70315.

**Comment by myaaaaaaaaa** [comment]
> I guess the solution is to check `rasterization_state.wireframe` as well as `p_wireframe` to see if the version exists. 

See the below pseudocode for an alternative suggestion.

```diff
diff --git a/servers/rendering/renderer_rd/pipeline_cache_rd.cpp b/servers/rendering/renderer_rd/pipeline_cache_rd.cpp
index 17051d1954..229d0d242a 100644
--- a/servers/rendering/renderer_rd/pipeline_cache_rd.cpp
+++ b/servers/rendering/renderer_rd/pipeline_cache_rd.cpp
@@ -32,16 +32,14 @@
 
 #include "core/os/memory.h"
 
 RID PipelineCacheRD::_generate_version(RD::VertexFormatID p_vertex_format_id, RD::FramebufferFormatID p_framebuffer_format_id, bool p_wireframe, uint32_t p_render_pass, uint32_t p_bool_specializations) {
 	RD::PipelineMultisampleState multisample_state_version = multisample_state;
 	multisample_state_version.sample_count = RD::get_singleton()->framebuffer_format_get_texture_samples(p_framebuffer_format_id, p_render_pass);
 
-	bool wireframe = p_wireframe || rasterization_state.wireframe;
-
 	RD::PipelineRasterizationState raster_state_version = rasterization_state;
 	raster_state_version.wireframe = wireframe;
 
 	Vector<RD::PipelineSpecializationConstant> specialization_constants = base_specialization_constants;
 
 	uint32_t bool_index = 0;
 	uint32_t bool_specializations = p_bool_specializations;
diff --git a/servers/rendering/renderer_rd/pipeline_cache_rd.h b/servers/rendering/renderer_rd/pipeline_cache_rd.h
index 0b12dab416..58c1278312 100644
--- a/servers/rendering/renderer_rd/pipeline_cache_rd.h
+++ b/servers/rendering/renderer_rd/pipeline_cache_rd.h
@@ -72,14 +72,16 @@ public:
 	_FORCE_INLINE_ RID get_render_pipeline(RD::VertexFormatID p_vertex_format_id, RD::FramebufferFormatID p_framebuffer_format_id, bool p_wireframe = false, uint32_t p_render_pass = 0, uint32_t p_bool_specializations = 0) {
 #ifdef DEBUG_ENABLED
 		ERR_FAIL_COND_V_MSG(shader.is_null(), RID(),
 				"Attempted to use an unused shader variant (shader is null),");
 #endif
 
 		spin_lock.lock();
+		p_wireframe |= rasterization_state.wireframe;
+
 		RID result;
 		for (uint32_t i = 0; i < version_count; i++) {
 			if (versions[i].vertex_id == p_vertex_format_id && versions[i].framebuffer_id == p_framebuffer_format_id && versions[i].wireframe == p_wireframe && versions[i].render_pass == p_render_pass && versions[i].bool_specializations == p_bool_specializations) {
 				result = versions[i].pipeline;
 				spin_lock.unlock();
 				return result;
 			}
```

**Comment by clayjohn** [comment]
That solution also looks good!

**Comment by prominentdetail** [comment]
Is that all that is needed changed, or is there more to it?
I might want to test this out, since there hasn't been any updates.

**Comment by clayjohn** [comment]
@prominentdetail The solution proposed by myaaaaaaaa is all you need.

**Comment by prominentdetail** [comment]
Okay.. hopefully I did everything correctly. I tested it on my end, and it seems to work. Memory has stopped increasing.
