### ISSUE TITLE
Sprite frame textbox arrows and slider dont work

### ISSUE THREAD

**Issue by balloonpopper** [godotengine/godot#7624]
**Operating system or device - Godot version:**
Godot 2.1.1 - Windows 10

**Issue description:**
The up/down arrows next to "Frame" on a sprite node don't work. The slider that appears when you select its textbox doesn't work either.

**Steps to reproduce:**
Create a scene containing only a 2d sprite node
![image](https://cloud.githubusercontent.com/assets/5151242/22241804/227d5962-e275-11e6-9f5d-42b934f10e03.png)

Load in any spritespritesheet on the Sprite Node for its texture (I used a png file)
Set "Hframes" and/or "Vframes" to some value (eg. 2 Hframes, 2 Vframes)
![image](https://cloud.githubusercontent.com/assets/5151242/22241821/30cd7592-e275-11e6-9ebd-3a01f77d942b.png)

Error 1) In the "frame" textbox type a number and hit enter. The sprite on screen will change, but the textbox still says that you're on frame "0"
![image](https://cloud.githubusercontent.com/assets/5151242/22241835/3af91a1c-e275-11e6-8aae-b0692b6817e8.png)

Error 2) If you click the up and down arrows as part of the sprite textbox, they don't change the sprite frame
![image](https://cloud.githubusercontent.com/assets/5151242/22241898/6aaa2328-e275-11e6-8ece-33d3c337813f.png)

Error 3) If you click the frame textbox, it pops up a slider for changing the frame, but the slider is missing the handle to grab to change frames.
![image](https://cloud.githubusercontent.com/assets/5151242/22241944/95f7b25c-e275-11e6-9e15-b752a6e32932.png)

**Comment by bojidar-bg** [comment]
I think I haven't seen this in 2.2/master, can someone confirm for 2.1.2 though?

**Comment by balloonpopper** [comment]
Just downloaded 2.1.2 - all three bugs confirmed as present in 2.1.2

**Comment by reduz** [comment]
Will get rid of that slider for 3.0

**Comment by balloonpopper** [comment]
Will we still be able to choose the frame though? Currently the text field doesn't change from "0" when you type a different number in.

**Comment by bojidar-bg** [comment]
Ah, actually, I remember this not working in earlier versions...

**Comment by Faless** [comment]
> Will we still be able to choose the frame though?

@balloonpopper yes, the text field does not update correctly, but the property is updated and you should see the selected frame in the 2D view (assuming of course `frame < hframes*vframes`).

If you reload the scene in the editor (eg. by switching tabs) you will see the updated value in the inspector and surprisingly enough, both the slider and the arrow will work up to the `hframe*vframe` values at reload.

So a temporary solution until bug is fixed, is to:
1. Set `hframe` and `vframe`
2. Reload scene
3. Now you can use slider, arrows, and manual input.
4. If you change either `hframe` or `vframe` go back to 2

@bojidar-bg I can confirm the bug also affects master and 2.2.

**Comment by balloonpopper** [comment]
@Faless - Thanks for the information on the workaround - that'll be helpful! The frame question though was in relation to reduz saying the slider will be removed for v3. I was looking to confirm whether only the slider will be removed for v3, or whether the ability to type the frame number in in the interface would be removed as well. Hopefully it's just the slider.

**Comment by Faless** [comment]
I'm pretty sure he meant the slider when editing int/floats in general. The property to set the frame number will be there.

BTW, I noticed it's enough to just reload the inspector pane (i.e. selecting another node and back) instead of reloading the whole scene

**Comment by bojidar-bg** [comment]
Ah, again the cool effect with the Inspector not reloading.... :laughing:
