### ISSUE TITLE
Cannot use empty group name in when overriding property list

### ISSUE THREAD

**Issue by JackNewley** [godotengine/godot#76242]
### Godot version

4.0.2

### System information

Win 10

### Issue description

When overriding _get_property_list(), adding an empty group name property produces an error code, rather then breaking out subsequent properties from grouping.

From the EditorInspector Docs
"An empty group name effectively ends the current group."

![image](https://user-images.githubusercontent.com/9077011/232949824-282737d1-4f15-42a5-b9a2-5dfa22661b60.png)

Error produced :   modules/gdscript/gdscript.cpp:1692 - Condition "pinfo.name.is_empty()" is true. Continuing.

### Steps to reproduce

From the reproduction project
1. Inspect new_resource.tres
2. Observe error in console
3. Change the name of the group property to be non empty, and see it works otherwise

### Minimal reproduction project

[BreakoutGroupPropertyList.zip](https://github.com/godotengine/godot/files/11267910/BreakoutGroupPropertyList.zip)

**Comment by timothyqiu** [comment]
Also happens on 3.x.

GDScript requires the provided property name to be non-empty. This is unnecessary I believe. We can at least allow empty property names when the usage contains `PROPERTY_USAGE_GROUP` or `PROPERTY_USAGE_SUBGROUP`.

https://github.com/godotengine/godot/blob/1b4b8934e080ec5300c78547527517f4a5b733e9/modules/gdscript/gdscript.cpp#L1691-L1692
