### ISSUE TITLE
Vulkan: Volumetric fog glitches out in builds that use `optimize=none`, but not other optimization levels

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#76243]
### Godot version

4.0.2.stable (compiled from source)

### System information

Fedora 37, GeForce RTX 4090 (NVIDIA 530.41.03)

### Issue description

Volumetric fog glitches out with NaN/INF values depending on the compiler optimization level:

Glow disabled | Glow enabled
-|-
![Screenshot_20230419_040319 webp](https://user-images.githubusercontent.com/180032/232953404-80ba1871-c000-495d-bc26-ebf9b1bd57a8.png) | ![Screenshot_20230419_040324 webp](https://user-images.githubusercontent.com/180032/232953409-f187b812-d047-489b-b92e-73465b9edb5e.png)

This occurs regardless of whether SDFGI or VoxelGI or any other effects (glow, SSR, SSAO, SSIL) is used.

- `optimize=speed`, `optimize=speed_trace`, `optimize=debug` and `optimize=size` work as expected.
- `optimize=none` causes the glitch.

I'm using GCC 12.2.1 from the Fedora 37 repositories.

**Edit:** I've tried reproducing this again with `optimize=none` and can't reproduce this anymore, even if I clean all SCons files and rebuild. However, when I could reproduce the issue, I could always reproduce it with a binary using `optimize=none` and never with a binary using `optimize=speed`.

### Steps to reproduce

- Use a self-compiled build on Linux with `optimize=none` (GCC, not tested with Clang).
- Open the Reflection project linked below in the editor and move the 3D camera around. Fog will eventually glitch out.

### Minimal reproduction project

I haven't managed to reproduce this issue in a minimal project so far, only in https://github.com/Calinou/godot-reflection.

**Comment by akien-mga** [comment]
For the record, I've had it glitch making the whole screen black on 4.0.2.official builds on both Linux and Windows. Might not be the same bug, but at least mine wouldn't be compiler/optimization related. I should be able to provided a (non minimal) reproduction project soon.
