### ISSUE TITLE
Parallax Layers work very strangely with different camera zooms

### ISSUE THREAD

**Issue by swordcube** [godotengine/godot#76247]
### Godot version

4.0.2.stable

### System information

Arch Linux, Vulkan, Intel Haswell-ULT (Integrated Graphics using CPU: Intel i5-4310U)

### Issue description

# Unexpected Behavior
Any parallax layer that has a scroll scale/factor of anything that isn't 1.0 will start to shift everything in it to the bottom right when a Camera2D is active and the zoom is changed to anything below/above 1.0.

The problem worsens the lower/higher the scroll scale is.

# Expected Behavior
Any parallax layer that has a scroll scale/factor of anything that isn't 1.0 will correctly display everything in it to be centered like the sprite shown as 1.0 scroll factor in the video below.

https://user-images.githubusercontent.com/49110074/232971841-09c63b0b-6ce9-400f-862f-3d7b8b9e90d1.mp4

### Steps to reproduce

Put some ParallaxLayers in a ParallaxBackground and put any kind of sprite in those layers, and change the scroll scale of each layer to be lower than the other

### Minimal reproduction project

Here's a project that showcases the issue in the clearest way i can think of:

[parallax layer plus cam zoom issue.zip](https://github.com/godotengine/godot/files/11268857/parallax.layer.plus.cam.zoom.issue.zip)

**Comment by swordcube** [comment]
I figured out that this is apparently intentional (https://github.com/godotengine/godot/pull/58567), but how could i work around this?

**Comment by swordcube** [comment]
> Have you seen the explanation in #75858?

I have but i'm having trouble understanding what exactly they mean
![image](https://user-images.githubusercontent.com/49110074/233191241-a76f779f-d66a-4f92-aa3d-548e4e0e866d.png)

**Comment by swordcube** [comment]
I was thinking of somehow adjusting the offsets of the parallax layers to the camera zoom

But i don't know how i would since i usually don't have my cameras in the same node as the parallax background

**Comment by Zireael07** [comment]
@swordcube adjust them from a common parent or use groups.

As for KoBeWi's explanation, they explained it very clearly imho

**Comment by swordcube** [comment]
> @swordcube adjust them from a common parent or use groups.
> 
> As for KoBeWi's explanation, they explained it very clearly imho

I have trouble understanding certain things sometimes
Thanks though, i'm gonna close this issue now
