### ISSUE TITLE
multiple \n only work when you put a space between them

### ISSUE THREAD

**Issue by Daniel-da-Silva** [godotengine/godot#76255]
### Godot version

4.0.2

### System information

MX Linux, i5-6500

### Issue description

Hey,

when I'm setting the text of a richtextlabel and use \n\n, it only displays one line skip and not multiple. It works if you put a space between the \n\n. I think it's a bug because just writing \n\n without a space worked in 3.5.2.

### Steps to reproduce

Scene
Add RichTextLabel

```gdscript
extends RichTextLabel

func _ready():
	$RichTextLabel.text = "Potato\n\nPotato"

```

Run

### Minimal reproduction project

Easier to make a project yourself

**Comment by angel-721** [comment]
Interesting. I'll take a look at it when I can! I'm assuming it's located here. 
https://github.com/godotengine/godot/blob/master/scene/gui/rich_text_label.cpp  
I'm going to take a look at this and see if I can fix this soon!  Do you know if this occurs in other text nodes or just the richtextlabel?

**Comment by bruvzg** [comment]
Not reproducible with 4.0.2 and current master.

**Comment by Daniel-da-Silva** [comment]
@angel-721 I only tested it with richtextlabel (I only use label and richtextlabel normally)

So, I thought this would be reproducible but I just tried it and it isn't - at least not with a _new node_, with the old one it works.
Now I suspect this is an issue from porting the project from Godot 3.5.2 to 4.0.2 since it only affects the old nodes which I had already open in Godot 3.5.2. It's the Help_Text2 node which is affected, you can change it in the player.gd code (it's duplicated once so you need to change it in both places). Sorry, I should have tested this more thoroughly.

Here is the project!

[The_Blood_Mage_4_0.zip](https://github.com/godotengine/godot/files/11278280/The_Blood_Mage_4_0.zip)

**Comment by qza2468** [comment]
I can't produce it also, in Godot4.02 Android

**Comment by Daniel-da-Silva** [comment]
Hey, since this is not easily reproducible and seems to only affect projects ported from Godot 3.5.2 and is so minor (couldn't think of any issue less important than this), I would just close this.
