### ISSUE TITLE
Vulkan: SSAO breaks visuals on AMD Radeon RX 570

### ISSUE THREAD

**Issue by Daniel-da-Silva** [godotengine/godot#76258]
### Godot version

4.0.2

### System information

Win 10, AMD RX 570 23.4.1 Driver, Vulkan

### Issue description

Hey,

I played around with Godot 4.0.2 and SSAO unfortunately breaks the visuals completely. I think SSIL and SDFGI are also broken.

[Here is the YouTube video if you happen to not have an RX 570](https://youtu.be/aXAF0_aDU1M)

It works on my MX Linux Intel HD machine and on a Windows Nvidia GTX 960 machine, so I suspect it's an AMD exclusive issue.

### Steps to reproduce

Start the game, press a few times space until you get to the game world.

### Minimal reproduction project

[The_Blood_Mage_4_0.zip](https://github.com/godotengine/godot/files/11273444/The_Blood_Mage_4_0.zip)

**Comment by RandomCatDude** [comment]
I have an RX 570 and am not experiencing the problem, and happen to be on Linux.
This seems to me like a problem with official Windows drivers specifically, then.

**Comment by Daniel-da-Silva** [comment]
I updated to the recently released 23.4.2 driver and the problem still persists.

**Comment by Daniel-da-Silva** [comment]
Unfortunately, the problem still persists with the new 23.5.2 driver

**Comment by Calinou** [comment]
Could you test [4.3.dev2](https://godotengine.org/article/dev-snapshot-godot-4-3-dev-2/) under the same conditions to see if the issue is resolved there? Judging by [this comment](https://github.com/godotengine/godot/issues/85549#issuecomment-1888699705), that version might resolve the issue.

**Comment by Daniel-da-Silva** [comment]
Yes, it is fixed! 
What is a bit strange: My graphics card or some part of my pc seems to make like a noise now when the game is running which it didn't do before in previous versions but it's not so bad just weird.

**Comment by Calinou** [comment]
> My graphics card or some part of my pc seems to make like a noise now when the game is running which it didn't do before in previous versions

This is likely coil whine when running at high FPS. Do you have V-Sync disabled in the project (or forced to be disabled in the graphics driver control panel)? Check your FPS in the running project by enabling **Print FPS** in the Project Settings.

**Comment by Daniel-da-Silva** [comment]
You are right! I took an old version of the project and ported that and forgot that VSync wasn't enabled there yet. Thanks!
