### ISSUE TITLE
inspector Resource list unscrollable

### ISSUE THREAD

**Issue by djrain** [godotengine/godot#76275]
### Godot version

3.6 beta 1

### System information

macOS Monterey

### Issue description

The dropdown to make a new Resource for an exported variable has become unusable in 3.6 beta 1  - the menu opens but is unscrollable, so I can't access anything past what fits on screen. It works fine in 3.5.1.

To be clear, I'm referring to the list that appears when you click this:
<img width="278" alt="Screen Shot 2023-04-19 at 7 40 58 PM" src="https://user-images.githubusercontent.com/33777501/233244238-738e854c-78db-449e-bfd8-e7de12b8dcd4.png">

### Steps to reproduce

in any script, add an export Resource variable like so:
`export (Resource) var some_resource`

then in the inspector, click the button to create a new resource there, and try to scroll the list

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
Sounds similar to #76042

**Comment by KoBeWi** [comment]
Closing in favor of #76289
