### ISSUE TITLE
Extending a script that use `@tool` do not make the script a tool

### ISSUE THREAD

**Issue by thiagola92** [godotengine/godot#76283]
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Fedora 38

### Issue description

When script A have `@tool` and another script extends from A, the new script doesn't seems to trigger configuration warnings.

```gdscript
# first.gd
@tool
class_name First
extends Node2D


func _get_configuration_warnings() -> PackedStringArray:
	return ["Look at me"]

# -----------
# second.gd
extends First
```

### Situation
![image](https://user-images.githubusercontent.com/9352894/233315387-522d3fd9-5dd2-485c-8996-c22af68820a9.png)

### Expectation
![image](https://user-images.githubusercontent.com/9352894/233315632-cc6cd4b0-3596-4211-a147-ade221317773.png)

### Video
https://www.youtube.com/watch?v=fkyLZHmJTW8

### Steps to reproduce

- Create a script
- Add `@tool`
- Add `class_name First`
- Add a configuration warning
  - `func _get_configuration_warnings(): return ["Look at me"]`
- Create another another script
- Make it extend form previous script
  - `extends First`
- Check that configuration warning doesn't appears

### Minimal reproduction project

N/A

**Comment by YuriSizov** [comment]
Thanks for your report. There is already an open discussion about this issue: https://github.com/godotengine/godot-proposals/issues/754. So I'm going to close this in favor of the existing proposal.
