### ISSUE TITLE
Perfect music loop clips in Godot 4.

### ISSUE THREAD

**Issue by strellydev** [godotengine/godot#76307]
### Godot version

4.0.2

### System information

Windows 10

### Issue description

I have a song that loops to an offset. This looping works perfectly in Godot 3 and Audacity, but Godot 4 introduces an ugly audio clip.
I will post a video so you can see what I mean.

Sorry if this is a duplicate, I tried looking for audio loop issues but didn't find anything that could be similar to mine. Except maybe issue #26931 but that one seems to go back to Godot 3, so I don't know if it applies.

I'm not sure what could be going on, maybe there's a small delay when looping? Or maybe the loop position is not being set correctly?

https://user-images.githubusercontent.com/113683950/233506996-b28cc420-a0d6-43bc-9d9a-559a4fe20718.mp4

### Steps to reproduce

N/A

### Minimal reproduction project

No WAV files because they are too big.

[LoopIssueGodot3.zip](https://github.com/godotengine/godot/files/11294979/LoopIssueGodot3.zip)
[LoopIssueGodot4.zip](https://github.com/godotengine/godot/files/11294981/LoopIssueGodot4.zip)

**Comment by Calinou** [comment]
@strellydev Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by strellydev** [comment]
Doesn't matter if it's ogg, mp3 or wav, the three of them make the clip sound, although I must say the mp3 clip is way less noticeable.

In Godot 3, only wav introduces the audio clip, and again, way less noticeable.

I searched again for similar issues using "pop" instead of "clip" and this one came about: #64775 
But there it says the mp3 version of the song doesn't pop, so I'll still upload my sample project in case it's useful on detecting a similar issue with mp3 files.

You'll find the projects in the main issue post.

**Comment by Calinou** [comment]
> Edit 3: Okay this is very weird in Godot 3. Like I said, in Godot 3, wav introduces de "pop" sound, but it's kinda random, I sat there repeating the loop and some times it doesn't introduce it and others it does. So yeah, no clue what's going on with that.

See https://github.com/godotengine/godot/issues/22016.

**Comment by strellydev** [comment]
I will take a look at that, thanks, I'll close this issue too, seeing that it's covered by 64775.

Thanks for you support!
