### ISSUE TITLE
Continuous collision detection algorithm

### ISSUE THREAD

**Issue by wzj18133771025** [godotengine/godot#76313]
### Godot version

4.0

### System information

Windows 10

### Issue description

I want to konw the CCD algorithm of Godot Engine. The doc mentioned that : Continuous collision detection enabled using raycasting and using shapecasting. But I can not find any information about these to CCD methods. Can anyone give me some help? Paper or algorithm.

### Steps to reproduce

1

### Minimal reproduction project

1

**Comment by YuriSizov** [comment]
Hey there! Thanks for your interest, but this is not a proper place for such inquiries. This is a bug tracker platform. If you want to discuss Godot internals, I invite you to join the [Godot Contributors Chat](https://chat.godotengine.org). You will also find knowledgeable people on our [community platforms](https://godotengine.org/community/).
