### ISSUE TITLE
Breakpoints don't work on built-in scripts that are attached to autoloaded scenes.

### ISSUE THREAD

**Issue by cosmoddd** [godotengine/godot#76319]
### Godot version

4.0.2 stable

### System information

Windows 11

### Issue description

When attempting to debug a tutorial scene that had a lot of built in scripts, I was noticing the breakpoints weren't working.  On further inspection I was able to reproduce this consistently, even on a blank project.

Two things to note:

The breakpoint works on an autolaoded scene if it's in a resource script (saved as a .gd file).
The breakpoint works on a built-in script if it's directly attached to the primary scene, or is played on its own.

### Steps to reproduce

Create a primary scene.
Create a secondary scene.
Add the secondary scene to the Auto-load window so that it auto-loads.
Create a node with a built-in script in the secondary scene.
Create a breakpoint on a line in the built-in script.
Run the primary scene. 
Observe that the breakpoint is not triggered.

### Minimal reproduction project

[Bug Testing _ Breakpoints.zip](https://github.com/godotengine/godot/files/11297351/Bug.Testing._.Breakpoints.zip)

**Comment by KoBeWi** [comment]
Fixed in 4.3
