### ISSUE TITLE
AudioStreamPlayer.get_stream_playback() returns null

### ISSUE THREAD

**Issue by blackears** [godotengine/godot#76324]
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Windows 10, Forward+

### Issue description

Trying to get this project to run in Godot 4.  I imported it and ran the conversion process to upgrade to Godot 4.  

https://github.com/godotengine/godot-demo-projects/tree/3.5-9e68af3/audio/generator

When I try to run it, I get the error `Attempt to call function 'get_frames_available' in base 'null instance' on a null instance.`

### Steps to reproduce

Run the attached project.  When `$Player.get_stream_playback()` is called, it will return null which causes the rest of the demo to fail.

### Minimal reproduction project

[generator.zip](https://github.com/godotengine/godot/files/11298580/generator.zip)

**Comment by KoBeWi** [comment]
You need to play the AudioStreamPlayer before getting the playback.

**Comment by blackears** [comment]
That worked.

**Comment by KoBeWi** [comment]
Reopening, because we should have it documented. I don't see it mentioned anywhere.

**Comment by blackears** [comment]
I'm also noticing AudioStreamPlayback's methods aren't documented.

**Comment by blackears** [comment]
Would yo know why I'm able to access methods on AudioStreamPlayback like `get_frames_available()` and `push_frame()`, but methods like `seek()` and `get_playback_position()`?  None of these are listen in the documentaiton or the auto complete, but the first two can none the less be called.  

I'm looking at audio_stream_generator.h in the source code to get an idea of what methods ought to be there.

**Comment by KoBeWi** [comment]
Methods beginning with `_` are virtual. They are supposed to be overriden (to create custom playbacks), not called.

**Comment by Toemsel** [comment]
How does this work now? I want to play several sound effects. However, `self.get_stream_playback()` is always null, even if it has been set via the inspector. Playing a sound before also doesn't help as @blackears answered.

**Comment by GustasJanusauskas** [comment]
> How does this work now? I want to play several sound effects. However, `self.get_stream_playback()` is always null, even if it has been set via the inspector to `Polyphonic`. Playing a sound before also doesn't help as @blackears answered.

Setting the stream via inspector, then calling
        Play();
        playback = (AudioStreamPlaybackPolyphonic)GetStreamPlayback();
in _Ready() works for me

**Comment by Rainault** [comment]
I hit the same issue where `get_stream_playback()` returned null, even when calling `play()` on the `AudioStreamPlayer`. The problem was that `play()` doesn't do anything if the player hasn't been added to the tree. (I'm creating my Player in code.) You need to call `play()` after adding the player to the tree, or you can set the `autoplay` property to true before adding it to the tree.

```
var player = AudioStreamPlayer.new()
add_child(player)
player.play()
```

or

```
var player = AudioStreamPlayer.new()
player.autoplay = true
add_child(player)
```
