### ISSUE TITLE
Cannot load any resources except the main.pck when launching the game from windows search bar

### ISSUE THREAD

**Issue by rambda** [godotengine/godot#76326]
\# update minimal projects. I found that not only exposed resources, but also resource packs cannot be loaded

### Godot version

3.5.2.stable

### System information

Windows 10

### Issue description

It is known that we can use `ProjectSettings.load_resource_pack()` to load resoueces in .pck/.zip packs. 
Also, if we place imported resources directly in exported game directory, the game can also load them.
However, If you start the game.exe from windows search bar, these resources can NOT be load. 

> context:
> Some players have reported to me that if my game is launched from the windows search bar, the game crashes.
> As far as I know, windows can only search for .exe files written to the registry. I use windows too, but I can't find any godot exe file from my search bar.
> Still, not sure why, many players are able to open my game from windows search bar.

### Minimal reproduction project

Open WindowsSearchBarBug.exe normally, you will see `icon.png`, `icon2.zip`, `icon2.png` loaded successfully.
Open it from windows search bar, all the above will NOT be loaded.
[WindowsSearchBarBugExported.zip](https://github.com/godotengine/godot/files/11300425/WindowsSearchBarBugExported.zip)

The source:
[WindowsSearchBarBug.zip](https://github.com/godotengine/godot/files/11300426/WindowsSearchBarBug.zip)

### Steps to reproduce

1. export the project, using "export selected resources", select all resources, but leave icon.png and icon2.png for testing.
2. export icon.png to a single .zip/.pck pack.
3. put `icon.png-487276ed1e3a0c39cad0279d744ee560.stex`, `icon.png-487276ed1e3a0c39cad0279d744ee560.md5`, `icon.png.import` in exported game folder.
4. open the exported game. Apparently it works, `icon.png`, `icon2.zip`, `icon2.png` are loaded successfully.
5. open the game from windows search bar. None of the above are loaded.

**Comment by rambda** [comment]
Guess it's something about working dir?

**Comment by Calinou** [comment]
This is not a bug, as paths are relative by default unless they are made absolute.

Instead of using:

```gdscript
ProjectSettings.load_resource_pack("icon2.zip")
```

Use:

```
ProjectSettings.load_resource_pack(OS.get_executable_dir().path_join("icon2.zip"))
```

(In 3.x, use `plus_file()` instead of `path_join()`.)
