### ISSUE TITLE
Changing type of a node that has a script attached to it does not update the icon in the editor

### ISSUE THREAD

**Issue by bones527** [godotengine/godot#76339]
### Godot version

4.1dev1

### System information

Windows 11, Forward+, Intel Iris Xe

### Issue description

After attaching a script to any node, changing the type of the node does not update the icon of the node in the editor. But if no script is attached then editor updates the type change accordingly. 

### Steps to reproduce

1. Open a project
2. Select any node that has an attached script
3. Change type of the node

### Minimal reproduction project

[IconTest.zip](https://github.com/godotengine/godot/files/11301046/IconTest.zip)

**Comment by jmb462** [comment]
When a script is attached to a node, the node icon in the tree depends on the type of you are extending in the script.
(If you change this extends, the icon is updated  when you click in the tree)
If you don't change the ``extends`` at the beginning of the script, the icon stay unchanged.

**Comment by bones527** [comment]
So, this is expected then. Thank you for clarifying. I'm closing the issue then.
