### ISSUE TITLE
Unable to launch Godot 4.0/4.0.2 on Windows 10 (Nahimic 2+ Versione 2.5.35 issue)

### ISSUE THREAD

**Issue by Vytek** [godotengine/godot#76341]
### Godot version

Godot_v4.0.2-stable_win64.exe

### System information

		Operating System
			Windows 10 Home 64-bit
		CPU
			Intel Core i7 6700HQ @ 2.60GHz	54 °C
			Skylake 14nm Technology
		RAM
			16,0GB Dual-Channel DDR4 @ 1200MHz (17-17-17-39)
		Motherboard
			Micro-Star International Co. Ltd. MS-16JB (U3E1)
		Graphics
			Generic PnP Monitor (1920x1080@60Hz)
			Intel HD Graphics 530 (MSI)
			2047MB NVIDIA GeForce GTX 1060 (MSI)	49 °C
			SLI Disabled
		Storage
			238GB KINGSTON RBU-SNS8152S3256GG5 (SATA-2 (SSD))	49 °C
			931GB Hitachi HGST HTS721010A9E630 (SATA )	44 °C
		Optical Drives
			HL-DT-ST DVDRAM GUD0N
		Audio
			Realtek High Definition Audio
Operating System
	Windows 10 Home 64-bit
	Computer type: Notebook
	Installation Date: 15/04/2021 09:42:4
		Windows Security Center
			User Account Control (UAC)	Enabled
			Notify level	2 - Default
			Firewall	Enabled
		Windows Update
			AutoUpdate	Not configured
		Windows Defender
			Windows Defender	Enabled
		Antivirus
			Antivirus	Enabled
			Display Name	Windows Defender
			Virus Signature Database	Up to date
		.NET Frameworks installed
			v4.8 Full
			v4.8 Client
			v3.5 SP1
			v3.0 SP2
			v2.0 SP2
		Internet Explorer
			Version	11.789.19041.0
		PowerShell
			Version	5.1.19041.1
		Java
				Java Runtime Environment
					Path	C:\Program Files (x86)\Java\jre1.8.0_361\bin\java.exe
					Version	8.0
					Update	361
					Build	09

### Issue description

I click on the file: Godot_v4.0.2-stable_win64.exe from Explorer. The cursor turns into a wheel for about 5-6 seconds. Absolutely nothing is launched. I get the same result by repeatedly clicking on the executable.

### Steps to reproduce

I click on the file: Godot_v4.0.2-stable_win64.exe from Explorer. The cursor turns into a wheel for about 5-6 seconds. Absolutely nothing is launched. I get the same result by repeatedly clicking on the executable.

### Minimal reproduction project

No project to upload.

**Comment by Vytek** [comment]
Tell me how I can help you. Does the editor write a log of some sort?

**Comment by Zireael07** [comment]
Try launching from terminal with --verbose parameter

**Comment by Vytek** [comment]
![image](https://user-images.githubusercontent.com/2614303/233783722-3a348139-97b2-425d-8794-e30100341af0.png)

Nothing happens, but if I see the TaskManager the Godot is running, but nothing is displayed. Very strange...

**Comment by Vytek** [comment]
The process is in idle mode:

![image](https://user-images.githubusercontent.com/2614303/233784482-8bc2dd7e-f4d3-4683-ae63-e5f32ae6c545.png)

**Comment by Vytek** [comment]
I think it is very similar to: https://godotengine.org/qa/148344/godot-4-does-not-open-while-the-3-5-version-opens

**Comment by Vytek** [comment]
![image](https://user-images.githubusercontent.com/2614303/233785207-cf1af3b2-191d-40ac-8ba3-6c1792e6bf65.png)

**Comment by Vytek** [comment]
![image](https://user-images.githubusercontent.com/2614303/233785276-0b5cef26-660e-477a-8c06-53746ce203c9.png)

**Comment by Vytek** [comment]
All dependencies seem to be on, I can't understand :-(

**Comment by Vytek** [comment]
OPENGL Version, etc...

![image](https://user-images.githubusercontent.com/2614303/233785565-bb06f315-3cea-4d4a-9a89-f11f9550f342.png)

**Comment by Vytek** [comment]
Same problems using  --render opengl3

![image](https://user-images.githubusercontent.com/2614303/233797229-d1f74c42-3068-4ae3-88fd-e24d67533798.png)

**Comment by clayjohn** [comment]
Do you have an antivirus enabled? It could be stopping the Godot process from running. Some people find they need to whitelist Godot in order to get it to run

**Comment by Vytek** [comment]
> Do you have an antivirus enabled? It could be stopping the Godot process from running. Some people find they need to whitelist Godot in order to get it to run

I have only Windows Defender. 

Check on virustotal the file is OK: 

https://www.virustotal.com/gui/file/965161cabcfade9b84e36e38e4763f86bcd92a5de00f959f5918c77ff6346c3d

![screencapture-virustotal-gui-file-965161cabcfade9b84e36e38e4763f86bcd92a5de00f959f5918c77ff6346c3d-2023-04-22-21_19_18](https://user-images.githubusercontent.com/2614303/233802631-557e4bbf-17c2-42d2-a923-720c7f751f41.png)

**Comment by Vytek** [comment]
OK, I start using strace from https://cmder.app/ Version: Latest Version: v1.3.21

C:\Users\enric\Downloads\Godot_v4.0.2-stable_win64.exe

This is the result log:

λ strace Godot_v4.0.2-stable_win64.exe
--- Process 12380 created
--- Process 12380 loaded C:\Windows\System32\ntdll.dll at 00007ffecfc70000
--- Process 12380 loaded C:\Windows\System32\kernel32.dll at 00007ffecdd70000
--- Process 12380 loaded C:\Windows\System32\KernelBase.dll at 00007ffecd380000
--- Process 12380 loaded C:\Windows\System32\apphelp.dll at 00007ffecac00000
--- Process 12380 loaded C:\Windows\System32\advapi32.dll at 00007ffecf9c0000
--- Process 12380 loaded C:\Windows\System32\msvcrt.dll at 00007ffecdcd0000
--- Process 12380 thread 8416 created
--- Process 12380 loaded C:\Windows\System32\sechost.dll at 00007ffecf2f0000
--- Process 12380 loaded C:\Windows\System32\rpcrt4.dll at 00007ffecf160000
--- Process 12380 thread 15900 created
--- Process 12380 thread 6952 created
--- Process 12380 loaded C:\Windows\System32\bcrypt.dll at 00007ffecdbe0000
--- Process 12380 loaded C:\Windows\System32\avrt.dll at 00007ffec75e0000
--- Process 12380 loaded C:\Windows\System32\gdi32.dll at 00007ffecebb0000
--- Process 12380 loaded C:\Windows\System32\dinput8.dll at 00007ffeac500000
--- Process 12380 loaded C:\Windows\System32\dwmapi.dll at 00007ffecb070000
--- Process 12380 loaded C:\Windows\System32\win32u.dll at 00007ffecd660000
--- Process 12380 loaded C:\Windows\System32\user32.dll at 00007ffecfa90000
--- Process 12380 loaded C:\Windows\System32\user32.dll at 000001b35f8f0000
--- Process 12380 loaded C:\Windows\System32\DWrite.dll at 00007ffea7ff0000
--- Process 12380 unloaded DLL at 000001b35f8f0000
--- Process 12380 loaded C:\Windows\System32\gdi32full.dll at 00007ffecd7c0000
--- Process 12380 loaded C:\Windows\System32\msvcp_win.dll at 00007ffecd720000
--- Process 12380 loaded C:\Windows\System32\combase.dll at 00007ffece850000
--- Process 12380 loaded C:\Windows\System32\ucrtbase.dll at 00007ffecd8d0000
--- Process 12380 loaded C:\Windows\System32\ucrtbase.dll at 000001b35f8f0000
--- Process 12380 unloaded DLL at 000001b35f8f0000
--- Process 12380 loaded C:\Windows\System32\imm32.dll at 00007ffecf810000
--- Process 12380 loaded C:\Windows\System32\ole32.dll at 00007ffece710000
--- Process 12380 loaded C:\Windows\System32\IPHLPAPI.DLL at 00007ffecc7e0000
--- Process 12380 loaded C:\Windows\System32\oleaut32.dll at 00007ffecf840000
--- Process 12380 loaded C:\Windows\System32\shell32.dll at 00007ffecdf60000
--- Process 12380 loaded C:\Windows\System32\opengl32.dll at 00007ffe88cc0000
--- Process 12380 loaded C:\Windows\System32\shlwapi.dll at 00007ffece6b0000
--- Process 12380 loaded C:\Windows\System32\ws2_32.dll at 00007ffecf0f0000
--- Process 12380 loaded C:\Windows\System32\glu32.dll at 00007ffe8d0e0000
--- Process 12380 loaded C:\Windows\System32\winmm.dll at 00007ffec1c10000
--- Process 12380 loaded C:\Windows\System32\wsock32.dll at 00007ffebe310000
--- Process 12380 thread 17316 created
--- Process 12380 loaded C:\Windows\System32\bcryptprimitives.dll at 00007ffecd690000
--- Process 12380 loaded C:\Windows\System32\InputHost.dll at 00007ffec3260000
--- Process 12380 loaded C:\Windows\System32\SHCore.dll at 00007ffecf910000
--- Process 12380 loaded C:\Windows\System32\CoreMessaging.dll at 00007ffeca9d0000
--- Process 12380 loaded C:\Windows\System32\propsys.dll at 00007ffec85f0000
--- Process 12380 loaded C:\Windows\System32\WinTypes.dll at 00007ffec9fa0000
--- Process 12380 loaded C:\Windows\System32\CoreUIComponents.dll at 00007ffeca670000
--- Process 12380 loaded C:\Windows\System32\kernel.appcore.dll at 00007ffecbbd0000
--- Process 12380 loaded C:\Windows\System32\kernel.appcore.dll at 000001b35f740000
--- Process 12380 unloaded DLL at 000001b35f740000
--- Process 12380 loaded C:\Windows\System32\ntmarta.dll at 00007ffecc510000
--- Process 12380 thread 13892 created
--- Process 12380 loaded C:\Windows\System32\uxtheme.dll at 00007ffecacb0000
--- Process 12380 loaded C:\Program Files\Nahimic\Nahimic2\UserInterface\x64\Nahimic2DevProps.dll at 00007ffe806c0000
--- Process 12380 loaded C:\Program Files\Nahimic\Nahimic2\UserInterface\x64\Nahimic2OSD.dll at 00007ffe87ab0000
--- Process 12380 loaded C:\Windows\System32\clbcatq.dll at 00007ffecefc0000
--- Process 12380 loaded C:\Windows\System32\MMDevAPI.dll at 00007ffec7490000
--- Process 12380 loaded C:\Windows\System32\devobj.dll at 00007ffecd130000
--- Process 12380 loaded C:\Windows\System32\cfgmgr32.dll at 000001b361aa0000
--- Process 12380 unloaded DLL at 000001b361aa0000
--- Process 12380 loaded C:\Windows\System32\cfgmgr32.dll at 000001b361aa0000
--- Process 12380 unloaded DLL at 000001b361aa0000
--- Process 12380 loaded C:\Windows\System32\cfgmgr32.dll at 000001b361aa0000
--- Process 12380 unloaded DLL at 000001b361aa0000
--- Process 12380 loaded C:\Windows\System32\cfgmgr32.dll at 000001b361aa0000
--- Process 12380 loaded C:\Windows\System32\AudioSes.dll at 00007ffec6e00000
--- Process 12380 loaded C:\Windows\System32\powrprof.dll at 00007ffecc950000
--- Process 12380 loaded C:\Windows\System32\umpdc.dll at 00007ffecc7c0000
--- Process 12380 thread 4780 created
--- Process 12380 thread 8968 created
--- Process 12380 thread 15900 exited with status 0x0
--- Process 12380 thread 8416 exited with status 0x0
--- Process 12380 thread 6952 exited with status 0x0

**Comment by Calinou** [comment]
The issue is with Nahimic. You need to disable it.

**Comment by Vytek** [comment]
YES! I confirmed. Disabling Nahimic now all works fine.

![image](https://user-images.githubusercontent.com/2614303/233806160-077bb9f2-f701-4dc7-a652-be0937800475.png)

**Comment by Vytek** [comment]
> The issue is with Nahimic. You need to disable it: #28785, #13208
> 
> Are you on a multi-monitor setup?

No, only one monitor, but Nahimic 2+ is active (Version 2.5.35)

Incredible.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/13208, as this is due to the same cause.

**Comment by Zireael07** [comment]
Wow, how did you figure out the guy even has Nahimic in the first place?

Also: is this documented somewhere?

**Comment by Vytek** [comment]
> Wow, how did you figure out the guy even has Nahimic in the first place?
> 
> Also: is this documented somewhere?

Look at: https://github.com/godotengine/godot/issues/76341#issuecomment-1518746053 ;-)

--- Process 12380 loaded C:\Program Files\Nahimic\Nahimic2\UserInterface\x64\Nahimic2DevProps.dll at 00007ffe806c0000
--- Process 12380 loaded C:\Program Files\Nahimic\Nahimic2\UserInterface\x64\Nahimic2OSD.dll at 00007ffe87ab0000
