### ISSUE TITLE
class_name doesn't appear in auto complete suggestions

### ISSUE THREAD

**Issue by furroy** [godotengine/godot#76344]
### Godot version

3.6

### System information

Windows 11

### Issue description

When typing "cla" in the script editor, I would assume it would recommend class_name, just as typing "va" suggests var and "ex" suggests "export"

### Steps to reproduce

Type "cla" in script editor

### Minimal reproduction project

None needed to reproduce

![class_name](https://user-images.githubusercontent.com/24339/233787774-c237b18b-03cb-4501-a6a6-54d50523a620.png)

**Comment by akien-mga** [comment]
Fixed by #76346.
