### ISSUE TITLE
In Editor CharacterBody3D Floor Layers and Wall Layers use 2D Physics layer name settings

### ISSUE THREAD

**Issue by Torets** [godotengine/godot#76347]
### Godot version

4.0.1.stable

### System information

Windows 10, Steam

### Issue description

If you create **CharacterBody3D** and try to setup **Floor Layers** and **Wall Layers** of **Moving Platform** section, then names for editing them (three vertical dots to the right of layer setting grid) are taken from _Layer Names / 2D Physics_ settings of project.
Likewise clicking on "Edit Layer Names" in same popup window leads to _Layer Names / 2D Physics_ setting.

Layer and Mask fields of Collision section behave normally and are tied to _Layer Names / 2D Physics_.

I assume it does not influence behavior of CharacterBody3D object, but creates confusion, if operating with named layers.

### Steps to reproduce

1) Create new project 
2) Open _Project / Project Settings..._, in General Tab,  _Layer Names / 3D Physics_ section set first layer name ( in my example: 3d_layer1)
2) In same way set a different name for _Layer Names / 2D Physics_ section (in my example 2d_layer1)
3) Close Project Settings
4) Add  **CharacterBody3D** node
5) In _Inspector_ tab of created node  go to _CharacterBody3d / Moving Platform / Floor Layers_ and click 3 vertical dots to the right. Names will be displayed from _Layer Names / 2D Physics_
6) Choosing _Edit Layer Names_ will also open same section

Expected behavior: this fields should take names from _Layer Names / 3D Physics_ and _Edit Layer Names_ should open _Layer Names / 3D Physics_ section of project settings

### Minimal reproduction project

N/A

**Comment by smix8** [comment]
Can not reproduce this issue, the layer naming works just fine for me same as the edito names menu or layers menu.

Please add an MRP project.

**Comment by Torets** [comment]
Attached project as well as screenshots of behavior in question

![image](https://user-images.githubusercontent.com/1074485/233797048-e13405d2-01fd-4b77-b9d7-335e812c1659.png)
![image](https://user-images.githubusercontent.com/1074485/233797065-237b8a61-87a3-42cb-bbd5-091b5e0f56dc.png)
![image](https://user-images.githubusercontent.com/1074485/233797083-b3971294-522b-4a5b-94bb-a528b7545d49.png)
[Test.zip](https://github.com/godotengine/godot/files/11301866/Test.zip)

**Comment by Torets** [comment]
UPDATE
I have tried to check other versions. The issue  reproduces on versions 4.0 and 4.0.1 (which is the last for steam for now) and seem to be fixed in 4.0.2. So I guess the issue can be closed with "fixed in 4.0.2" in case some other steam uses stumble on it

**Comment by smix8** [comment]
PR that fixed it https://github.com/godotengine/godot/pull/75544

**Comment by rburing** [comment]
Fixed by https://github.com/godotengine/godot/pull/75544.
