### ISSUE TITLE
ButtonArray: Text in buttons is not being translated

### ISSUE THREAD

**Issue by Keyaku** [godotengine/godot#7636]
**Operating system or device - Godot version:**
Any OS - Godot 2.2-legacy

**Issue description:**
As is usual in any Control-based node (or so I thought), any text inside it would be translated at runtime.

This is the case with Labels, RichTextLabels, Buttons, but not with ButtonArrays.

Here's what I mean (Buttons above and ButtonArray below):
![Buttons](http://i.imgur.com/sAguUyT.png)

**EDIT**:
By looking at the files, I believe the only change necessary is to edit [button_array.cpp::434](https://github.com/godotengine/godot/blob/2.2-legacy/scene/gui/button_array.cpp#L434):

Swap this:
`buttons[p_button].text=p_text;`

With this:
`buttons[p_button].text=XL_MESSAGE(p_text);`

Or, in case we're updating `master`, we just add this line after [button_array.cpp::434](url):
`buttons[p_button].xl_text=XL_MESSAGE(p_text);`

**Comment by RayKoopa** [comment]
Junior job @akien-mga ? :D

**Comment by Keyaku** [comment]
Successfully merged, and the code looks good, so I'll just assume that this issue is fixed.
