### ISSUE TITLE
Android export fails when Android export setting ``keystore/debug`` begins with ``res://``

### ISSUE THREAD

**Issue by sosasees** [godotengine/godot#76365]
### Godot version

~4.0.2.stable~ 4.0.3.stable

### System information

• PC: Linux • Phone: Android 11

### Issue description

when i set the Android export setting ``keystore/debug`` to a path with ``res://``, i expect the Debug Keytore to be found in the Godot project.
instead, i get an error window when trying to export the Godot project APK (see text art in _Steps to reproduce_ #​9).

### Steps to reproduce

1. add a new Android export preset
2. fix all errors at the bottom of the export window
3. open terminal
4. ``cd`` to the Godot project folder
5. generate the debug keystore with the command from the [Exporting for Android](https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_android.html#create-a-debug-keystore) guide:
   ```
   keytool -keyalg RSA -genkeypair -alias androiddebugkey -keypass android -keystore android_debug.keystore -storepass android -dname "CN=Android Debug,O=Android,C=US" -validity 9999 -deststoretype pkcs12
   ```
   (modified to change the filename ``debug.keystore`` to ``android_debug.keystore``
6. set ``res://android_debug.keystore`` as the path for ``keystore/debug`` in the Android export preset
7. set ``keystore/debug_user`` and ``keystore/debug_password`` too:
looking at the command from step 5, i guess they are ``androiddebugkey`` and ``android`` respectively.
8. Export the project with debug
9. see this error window:
   ```
   ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────┐
   │ O ⎺                                         Project Export                                        _ □ X │
   ├─────────────────────────────────────────────────────────────────────────────────────────────────────────┤
   │ Project export for platform: 🤖 Android - ❌ Failed.                                                    |
   │   🟡 [Code Signing]: 'apksigner' returned with error #2                                                 |
   |   🟡 [Code Signing]: output:                                                                            |
   |      Failed to load signer "signer #1"                                                                  |
   |      java.io.FileNotFoundException: res:/android_debug.keystore (Datei oder Verzeichnis nicht gefunden) |
   |         at java.base/java.io.FileInputStream.open0(Native Method)                                       |
   |         at java.base/java.io.FileInputStream.open(FileInputStream.java:219)                             |
   |         at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)                           |
   |         at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)                           |
   |         at com.android.apksigner.SignerParams.loadKeyStoreFromFile(SignerParams.java:352)               |
   |         at com.android.apksigner.SignerParams.loadPrivateKeyAndCertsFromKeyStore(SignerParams.java:239) |
   |         at com.android.apksigner.SignerParams.loadPrivateKeyAndCerts(SignerParams.java:181)             |
   |         at com.android.apksigner.ApkSignerTool.getSignerConfig(ApkSignerTool.java:395)                  |
   |         at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:316)                             |
   |         at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:88)                              |
   ├─────────────────────────────────────────────────────────────────────────────────────────────────────────┤
   |                                                 > OK <                                                  |
   └─────────────────────────────────────────────────────────────────────────────────────────────────────────┘
   ```

### Minimal reproduction project

[android_export_error.zip](https://github.com/godotengine/godot/files/11303497/android_export_error.zip)
(8.0 KiByte download, 14.7 KiByte unzipped)

**Comment by Sosasees** [comment]
## ¿why would i want to put a Debug Keystore in the project folder?

this just makes sense for a free and open-source Godot project:

if the Debug Keystore is in the project folder, it's much easier for everyone — especially first-time contributors — to try their changes on a real phone.

**Comment by Calinou** [comment]
> ¿why would i want to put a Debug Keystore in the project folder?

A debug keystore can be generated by a single command, I don't see much point in committing it to version control. In fact, it should probably be the Godot editor's job to automatically create this debug keystore and reference it in the Editor Settings when you try to export a project (if no debug keystore is currently configured).

**Comment by Sosasees** [comment]
> Does it work if you make the path be just android_debug.keystore without a res:// prefix? This is how you specify a relative path in an export preset.

¡yes!, this does work.
now the issue is that i could not find this behavior documented.

fixed project:
[android_export_error_fixed.zip](https://github.com/godotengine/godot/files/11709468/android_export_error_fixed.zip)
(17.9 MiByte download, 18.1 MiByte unzipped)

> ¿why would i want to put a Debug Keystore in the project folder?

after fixing it, i found that i could use the same debug keystore as the release keystore (i educated guess that this works on more open platforms like Itch or GitHub, but not on the Google Play Store).

now i found the real purpose of putting a keystore in the Godot project: publishing the release keystore

**Comment by Calinou** [comment]
I guess we could detect uses of `res://` in export preset paths and strip them, which effectively makes it work as a relative path with no prefix.

**Comment by Sosasees** [comment]
> Don't make a release keystore public, or anyone will be able to sign the app and pretend it's official. This is particularly bad for Google Play as there's no way to revoke the keystore.

i already suspected that releasing the Play Store release keystore is a very bad idea.
my use is publishing a guest release keystore while keeping my release keystore secret.

**Comment by Calinou** [comment]
> so contributors have a way to export and then playtest the app with debug features disabled.

You can use a debug keystore for that purpose. The user will have to accept a warning prompt when installing the app either way, if the app is distributed outside the Play Store.

**Comment by Sosasees** [comment]
> A debug keystore can be generated by a single command, so I don't see much point in committing it to version control. In fact, it should probably be the Godot editor's job to automatically create this debug keystore and reference it in the Editor Settings when you try to export a project (if no debug keystore is currently configured).

this sounds like a good issue for [Godot proposals](https://github.com/godotengine/godot-proposals/issues?q=is%3Aissue+is%3Aopen+debug+keystore)

**Comment by m4gr3d** [comment]
Fixed by https://github.com/godotengine/godot/pull/90603
