### ISSUE TITLE
Navigation2D.get_simple_path() marked as deprecated but does not execute on 3.5.2

### ISSUE THREAD

**Issue by Vivraan** [godotengine/godot#76368]
### Godot version

3.5.2

### System information

Windows 11

### Issue description

In version 3.5.2 in my case, `Navigation2D.get_simple_path()` is not working as expected -- it doesn't generate a valid array.

As a corollary, can a guide be created for migrating legacy `Navigation[23]D` code to code which uses Navigation Servers?

### Steps to reproduce

2. Run the linked project. 
3. Check if the debugger stops at `guard.gd:36`.

### Minimal reproduction project

Download/clone my gamedev.tv Heist Meisters project copy from [here](https://gitlab.com/Vivraan/HelloHeistMeisters).

The relevant code is present in [res://scenes/characters/guard.gd](https://gitlab.com/Vivraan/HelloHeistMeisters/-/blob/master/scenes/characters/guard.gd).

## Edit

The example code works perfectly in 3.4.5.

**Comment by Vivraan** [comment]
One more related question would be about managing multiple tileset layers which were previously under the `Navigation2D` node -- how should those be used?

**Comment by smix8** [comment]
The `navigation_layers` for the navigation mesh are part of the NavigationPolygonInstance.

The 5th parameter of Navigation2DServer.map_get_path() is to filter the navigation layers in the path search.

Mind you that 2D navigation polygons are not stack able. They can not overlap or stack on top of each other in the same place on the same navigation map.

**Comment by Vivraan** [comment]
So is the recourse going to be to make a complex polygon which avoids obstacles? Or is there a way to mark obstacles? The earlier Node based approach abstracted away a lot of these considerations effectively.

**Comment by smix8** [comment]
I don't think I can follow what you mean.

The old node did nothing special expect creating a new navigation map for all its child nodes. You can still do that by using Navigation2DServer.map_create() and then place all your regions or agents on that new map.

If you delete the Navigation2D node all the regions and agents will just join the default navigation map of the World2D.

**Comment by smix8** [comment]
I think this discussion can be closed. Feel free to comment if there is something still unresolved.
