### ISSUE TITLE
Selectable text in dialog windows

### ISSUE THREAD

**Issue by allysonsouza** [godotengine/godot#7637]
**Operating system or device - Godot version:**
Windows 10, 2.1.2-stable

**Issue description:**
I don't know if it's in progress for 3.0 or is a Windows issue, but would be great if was possible to select text on dialog windows, it's a small detail that would improve usability and help search for thrown errors.

**Comment by bojidar-bg** [comment]
I think this should be an option for labels and other similar nodes that draw text, and it might be cool to repurpose this issue for that :smile:

**Comment by Calinou** [comment]
All error dialogs should now display a "Copy Text" button. I'll close this issue as this fulfills the base use case (looking up errors online) :slightly_smiling_face: 

If some error dialogs still lack this button, please open a bug report pinpointing the dialogs in question.
