### ISSUE TITLE
set_instance_shader_parameter() can't work

### ISSUE THREAD

**Issue by SneaK1ng** [godotengine/godot#76370]
### Godot version

v4.1.dev.custom_build.24cb43a87

### System information

Win10, AMD 2600, GeForce GTX 1060, Vulkan API 1.3.236

### Issue description

set_instance_shader_parameter() and RenderingServer.instance_geometry_set_shader_parameter() can't work.

GDScript:
```
extends MeshInstance3D

func _ready():
	set_instance_shader_parameter("custom_index", 1)
	# RenderingServer.instance_geometry_set_shader_parameter(get_instance(), "custom_index", 1)

# func _physics_process(_delta):
# 	set_instance_shader_parameter("custom_index", 2)
# 	RenderingServer.instance_geometry_set_shader_parameter(get_instance(), "custom_index", 2)
```

Shader:
```
shader_type spatial;

uniform int custom_index = 0;
varying vec3 color;

void vertex(){
	if(custom_index == 0){
		color = vec3(1, 0, 0);
	}else if(custom_index == 1){
		color = vec3(0, 1, 0);
	}else{
		color = vec3(0, 0, 1);
	}
}

void fragment() {
	ALBEDO = color;
}
```

Image:
should be green.
![image](https://user-images.githubusercontent.com/6891132/233841240-56763290-1991-45fe-a999-e59d705aec49.png)

### Steps to reproduce

run the reproduction project.

### Minimal reproduction project

[test_instance_geometry_set_shader_parameter.zip](https://github.com/godotengine/godot/files/11303802/test_instance_geometry_set_shader_parameter.zip)

**Comment by SneaK1ng** [comment]
Is there any other way to pass custom data to the shader for each instance?

**Comment by Chaosus** [comment]
@SneaK1ng You can duplicate the material itself, then every uniform inside of it will be taken into account independently.

**Comment by Chaosus** [comment]
> set_instance_shader_parameter() and RenderingServer.instance_geometry_set_shader_parameter() can't work.

To make it work you should use declare it with `instance` keyword in the shader eg:

```
instance uniform int custom_index = 0;
```

**Comment by SneaK1ng** [comment]
> To make it work you should declare it with keyword in the shader eg:`instance`
It works! Thanks a lot!
