### ISSUE TITLE
Deactivated the button handles the event "Mouse enter"

### ISSUE THREAD

**Issue by DimitriyPS** [godotengine/godot#7638]
OS All /  Godot 2.1.2

I used the event "Mouse enter" to voice the cursor is on the button. Some buttons in the interfaces deactivate - but still processed. This is not what was expected. I think it's not right for controls of the interface.

Example attached:
[knopka.zip](https://github.com/godotengine/godot/files/728913/knopka.zip)

**Comment by RayKoopa** [comment]
I don't agree with this.

Whenever asking me the question of what a disabled control should still be capable of, I ask myself what can still happen to that control.
- Can a disabled button get pressed? No, it can't. Never emit a pressed event.
- Can a disabled button still be hovered by a cursor? Yes of course. Otherwise the mouse cursor movement would need to be blocked along its borders.

That means if you do anything special in mouse enter, you should ask yourself it it's really the place to do it there, and if yes, check if the button is disabled manually.

**Comment by DimitriyPS** [comment]
The event "Mouse enter" event is inside the button class, not the mouse event. Button is not a sprite, the button is not an element of the game scene... the button is the control interface. I don't see a possible situation when you'll need to use an event "Mouse enter" if button is deactivated.

> That means if you do anything special in mouse enter, you should ask yourself it it's really the place to do it there, and if yes, check if the button is disabled manually.

Ok. I have a scene in which interface 23 button, it means I have to create the in script 23 the same event handlers "Mouse enter" (with the same logic)? It's insanity! If you go by this principle, then the event "Mouse enter" should return the object in parameter.

**Comment by bojidar-bg** [comment]
`mouse_enter` signal is part of the __`Control`__ class, not the `Button` class - http://docs.godotengine.org/en/latest/classes/class_control.html?highlight=mouse_enter#signals

Having it work differently for different control nodes would be pretty confusing to me at least.

(IMO, this is a wontfix, leaving open if someone wants to argument why/how it should be done)

**Comment by DimitriyPS** [comment]
> mouse_enter signal is part of the Control class, not the Button class 
Well, I do not dispute, I have not studied the topology classes Godot.

> (IMO, this is a wontfix
wontfix - I could not translate this word, and did not understand the proposal.

> Having it work differently for different control nodes would be pretty confusing to me at least.
I'm not an expert in the development of programming languages. But I know exactly what to create for the 23 buttons, 23 processing functions with the same code - it's a very bad decision from the point of view of interface development.

As I have suggested above, maybe the event "Mouse enter" will return a pointer to the object which called it?

Perhaps I did not properly solve the problem of voice hovering over the button. If you tell me how to properly terms GDScrip I'd appreciate it.

**Comment by bojidar-bg** [comment]
@DmitriySalnikov The so-called "pointer to the object" is achievable by providing "binds" to `connect`:
```gdscript
#...
  myNiceButton.connect("mouse_enter", self, "mouse_enter", [myNiceButton])
#...
func mouse_enter(button):
  #do stuff with button

**Comment by bojidar-bg** [comment]
(misclick xD)

**Comment by DimitriyPS** [comment]
This is an acceptable solution. It's not the most obvious solution is not the most convenient decision, but it is acceptable. It would be much easier if all this could be done visually in the editor.

I'll leave this appeal as a  initiative. Of course, if there are no serious technical difficulties. If this is not acceptable, it is possible to close it.
