### ISSUE TITLE
Font.get_multiline_string_size() does not count the line_spacing defined in Theme Label

### ISSUE THREAD

**Issue by meowyih** [godotengine/godot#76392]
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Window 10

### Issue description

Font.get_multiline_string_size() returns the size of the text with multiple lines. But when I use this function to estimate the Label size with certain text, it usually returns smaller size. After some investigation, I realized Font.get_multiline_string_size() does not count the "line_spacing" size defined in Theme. It is the addition space between each line. I suggest to add "line_spacing" parameter in the Font.get_multiline_string_size() for user to get the correct text drawing size.

### Steps to reproduce

1. Add a label with a long text and some size like (100, 300). And also change the wrapping setting for multiple lines displaying. 
2. Add a ColorRect that help to see the text drawing region
3. Assign a Theme to label and add a Label section in theme
4. Change the font size in Label's theme, also change "line_spacing" to maybe 5 or larger
5. Add the code beloew to see the different between the return size value and actual text on screen.

```gdscript
func _ready():
	var font : Font = $Label.get_theme_font("font")
	var text_size = font.get_multiline_string_size( 
		$Label.text, 
		HORIZONTAL_ALIGNMENT_LEFT, 
		$Label.size.x,
		$Label.get_theme_font_size("font_size"), 
		-1,
		TextServer.BREAK_WORD_BOUND,
		TextServer.JUSTIFICATION_WORD_BOUND,
		TextServer.DIRECTION_LTR,
		TextServer.ORIENTATION_HORIZONTAL)
	
	$ColorRect.size = text_size
```

### Minimal reproduction project

[FontGetMultipleStringLineBug.zip](https://github.com/godotengine/godot/files/11307276/FontGetMultipleStringLineBug.zip)

**Comment by bruvzg** [comment]
`Font.get_multiline_string_size` is not part of the `Label` (and not use by it), it's intended to draw text independently of any controls, so there's absolutely zero reason for `Font` functions to take `Label` theme into account.

**Comment by AThousandShips** [comment]
Not a bug, would suggest opening a [proposal](https://github.com/godotengine/godot-proposals) as this behaviour isn't implied nor should be expected

Remember to fill in all the boxes in the proposal, they are not optional, otherwise open a discussion if you're unable to

**Comment by meowyih** [comment]
> Not a bug, would suggest opening a [proposal](https://github.com/godotengine/godot-proposals) as this behaviour isn't implied nor should be expected, this issue tracker is for bugs
> 
> Remember to fill in all the boxes in the proposal, they are not optional, otherwise open a discussion if you're unable to

Got it. I will close this issue.
