### ISSUE TITLE
Documentation of `hint_string` format for PROPERTY_HINT_TYPE_STRING seems wrong

### ISSUE THREAD

**Issue by lilizoey** [godotengine/godot#76407]
### Godot version

4.0.2.stable

### System information

Linux 5.10.167-2-MANJARO

### Issue description

In the docs for PROPERTY_HINT_TYPE_STRING under [PropertyHint](https://docs.godotengine.org/en/stable/classes/class_%40globalscope.html#enum-globalscope-propertyhint) it provides these example for what the hint_string should look like:

```gdscript
hint_string = "%s:" % [TYPE_INT] # Array of integers.
hint_string = "%s:%s:" % [TYPE_ARRAY, TYPE_REAL] # Two-dimensional array of floats.
hint_string = "%s/%s:Resource" % [TYPE_OBJECT, TYPE_OBJECT] # Array of resources.
hint_string = "%s:%s/%s:Resource" % [TYPE_ARRAY, TYPE_OBJECT, TYPE_OBJECT] # Two-dimensional array of resources.
```

From what i can tell though, the value that comes after the `/` shouldn't be a type, but a propertyhint. i.e the second and third ones should be:
```gdscript
hint_string = "%s/%s:Resource" % [TYPE_OBJECT, PROPERTY_HINT_RESOURCE_TYPE] # Array of resources.
hint_string = "%s:%s/%s:Resource" % [TYPE_ARRAY, TYPE_OBJECT, PROPERTY_HINT_RESOURCE_TYPE] # Two-dimensional array of resources.
```

In addition the docs seem to imply that this `PropertyHint` is only used for specifying the type contained in the array, but it can do other things too. For instance it can be used to specify that the elements of the array are each strings that should be exported like multistrings.

I'm not entirely sure about everything that it can do, but it seems that it's under-documented as is.

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by dalexeev** [comment]
* See also comments in #72951.
