### ISSUE TITLE
C# Selecting an error makes a "Save Resource As" menu appears when running the project

### ISSUE THREAD

**Issue by XenokNyx** [godotengine/godot#76415]
### Godot version

4.0.2

### System information

Windows 10

### Issue description

If an error in the Debugger/Errors menu caused by a C# script is selected every time the project is executed a "Save Resource As" menu appears.
![Erro1](https://user-images.githubusercontent.com/6534007/234107005-1455895e-50d3-452a-b153-dae219f98211.PNG)
![Erro2](https://user-images.githubusercontent.com/6534007/234107008-315b7fed-d0ef-4573-ad76-9f0992f83a51.PNG)

The only way to stop it for appearing is restarting Godot.

### Steps to reproduce

1. Execute a C# script with an error
2. Select the error in the Debugger/Errors menu
3. Click "run project"
4. A "Save Resource As" menu appears.

### Minimal reproduction project

Example code with error:

```csharp
using Godot;
using System;

public partial class ErrorTest : Node 
{
    public override void _Ready() 
    {
        Node nullNode = null;

        nullNode.ToString();
    }
}


```

**Comment by Calinou** [comment]
Does this occur with errors that are caused by a GDScript file?

**Comment by XenokNyx** [comment]
C# Only, at least with the test I have done the error in GDScript appear in "Debugger/Stack Trace" while the error in C# appears in "Debugger/Errors" thats where the problem take place.

**Comment by raulsntos** [comment]
I'm unable to reproduce this issue, could you upload a minimal reproduction project? Also, a few questions to try and better understand the issue:

- Does this happen on every C# project?
- Do you have a custom editor configured in Editor Settings (either in **Editor Settings > Dotnet > Editor** or in **Editor Settings > Text Editor > External**)?
- Do you have any open scripts in Godot's code editor? Manually switch to the _Script_ view by using the button in the top middle of the Godot editor (right next to 2D, 3D and AssetLib) and look at the left sidebar that shows the list of open scripts.

Clicking on the errors in the _Debugger_'s _Error_ panel should open the script in your configured editor. When running the project, Godot saves every open resource (like scenes and scripts). So it's possible that clicking on an error opened an invalid script or the script was deleted afterwards, and then running the project will ask you to save it.

**Comment by XenokNyx** [comment]
It does happen in every C# project I have, here is the project I used for the test it's just an empty project with the script that produce the error.
[TESTS.zip](https://github.com/godotengine/godot/files/11950863/TESTS.zip)

There is nothing else open, only the main scene and the only modified setting is the external editor as Visual Studio Code.

Here is a video recreating the error.
https://github.com/godotengine/godot/assets/6534007/913055ba-6825-44b2-b8e7-19e62f890808

> Clicking on the errors in the Debugger's Error panel should open the script in your configured editor. When running the project, Godot saves every open resource (like scenes and scripts). So it's possible that clicking on an error opened an invalid script or the script was deleted afterwards, and then running the project will ask you to save it.

I have Visual Studio Code configured as an external editor, expanding the error details and clicking one of those lines does open the editor without any error only clicking on the red text produces the error.
