### ISSUE TITLE
Saving a scene adds an underscore between numbers and lowercases it.

### ISSUE THREAD

**Issue by Daniel-da-Silva** [godotengine/godot#76427]
### Godot version

4.0.2

### System information

MX Linux

### Issue description

When you save a scene and the top node was named Dungeon1, you get dungeon_1.tscn as default name. Caused issues when I tried to access the name of the current scene and typed in the scene name and not the name of the top node.

This differs from 3.5.2, there the default save name would be Dungeon1.tscn

### Steps to reproduce

Open a new scene, 3d, 2d doesn't matter. Call it Dungeon1, save it, default should be dungeon_1.tscn.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
This is the expected behaviour, you need to change the setting `editor/naming/scene_name_casing` under editor settings if you want a different behaviour

Please use the other [community channels](https://godotengine.org/community) for help questions, this is for bug reporting

**Comment by Daniel-da-Silva** [comment]
Oh, I thought this was a bug, since the behaviour was different in Godot 3.5.2. Thanks!
