### ISSUE TITLE
Condition is true wrongly?

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#76426]
### Godot version

v3.6.beta1.official [632a544c6]

### System information

w10 64

### Issue description

The length of the vector is not greater than 0.1, but Godot indicates that it is.

Why does Godot print "hola" if the length of the vector is not greater than 0.1?

![Captura2](https://user-images.githubusercontent.com/19652075/234219314-5957b6ec-f50a-4b68-bd81-0301d5e748a5.PNG)

### Steps to reproduce

Play the project

### Minimal reproduction project

[testCuerposKinematic.zip](https://github.com/godotengine/godot/files/11320345/testCuerposKinematic.zip)

**Comment by akien-mga** [comment]
This is because of floating point precision errors. You cant assume that `0.1 == 0.1` in computations, especially not as the result of multiple operations like `length()` does.

See https://0.30000000000000004.com/

For this case, you should add an epsilon, or invert your logic.
