### ISSUE TITLE
`SubViewport`s inside `SubViewportContainer`s don't receive events after using `push_input` with pressed `InputEventMouseButton`

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#76439]
### Godot version

v4.1.dev.custom_build [a7276f1ce]

### System information

Linux, Gnome on Arch

### Issue description

When using `push_input` on a viewport inside a SubViewportContainer, any input after the first mouse down doesn't get through.

Similar but not the same as #74868

### Steps to reproduce

```gdscript
var event = InputEventMouseButton.new()
event.pressed = true
sub_viewport.push_input(event)
sub_viewport.push_input(event) # This one doesn't go through.
```

### Minimal reproduction project

[SimulateInputDemo.zip](https://github.com/godotengine/godot/files/11322799/SimulateInputDemo.zip)

**Comment by Jummit** [comment]
This patch fixes the issue:

```patch
diff --git a/scene/main/viewport.cpp b/scene/main/viewport.cpp
index f3c2f4b0cc..84f6c4a837 100644
--- a/scene/main/viewport.cpp
+++ b/scene/main/viewport.cpp
@@ -2832,6 +2832,19 @@ void Viewport::push_input(const Ref<InputEvent> &p_event, bool p_local_coords) {
 	}
 
 	local_input_handled = false;
+	if (!handle_input_locally) {
+		Viewport *vp = this;
+		while (true) {
+			if (Object::cast_to<Window>(vp)) {
+				break;
+			}
+			if (!vp->get_parent()) {
+				break;
+			}
+			vp = vp->get_parent()->get_viewport();
+		}
+		vp->local_input_handled = false;
+	}
 
 	Ref<InputEvent> ev;
 	if (!p_local_coords) {
```

It seems like subviewports which do not handle their input locally need to set the parent viewport's `input_handled` to false.

**Comment by Chaosus** [comment]
> I'll open a PR if a maintainer thinks this is the best solution.

Do not hesitate to do it, even if you're not sure. There are multiple maintainers in rendering team and even if someone is not agreed - the PR itself can be reviewed and accepted in the appropriate PR meeting.

**Comment by Calinou** [comment]
I can confirm this on v4.1.beta.custom_build [33957aee6] (Linux).

Output from the MRP:

```
InputEventMouseButton: button_index=0, mods=none, pressed=false, canceled=false, position=((0, 0)), button_mask=0, double_click=false
InputEventMouseButton: button_index=0, mods=none, pressed=true, canceled=false, position=((0, 0)), button_mask=0, double_click=false
```

**Comment by Sauermann** [comment]
A workaround, until this gets fixed is to explicitly set `handle_input_locally` every time `push_input` is used:
``` gdscript
sub_viewport.handle_input_locally = true
sub_viewport.push_input(event)
sub_viewport.handle_input_locally = false
```
