### ISSUE TITLE
I can assign a boolean to an stricly typed int and vice versa

### ISSUE THREAD

**Issue by Daniel-da-Silva** [godotengine/godot#76433]
### Godot version

4.0.2

### System information

MX Linux

### Issue description

The code below doesn't trigger an error/warning

It throws an error at strings. Also it throws a warning at floats in the first case, and no warning or error in the second case

### Steps to reproduce

```
extends Node2D

var potato : int = 0

func _ready():
	potato = true
```

and

```
extends Node2D

var potato : bool = false

func _ready():
	potato = 2 #or 1.5
```

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
Duplicate of #40249
