### ISSUE TITLE
I can't assign elements to an array of godot objects on the Editor 

### ISSUE THREAD

**Issue by germanbv** [godotengine/godot#76440]
### Godot version

4.0.2

### System information

Windows 10, NVidiaRTX 2070

### Issue description

I'm working with C# here.. Whenever I export an array of Godot objects such as Label or TextureRect, even if I see the array on the editor and I'm allowed to assign objects of type to the array.. after selecting them, nothing happens.

### Steps to reproduce

Export an Array of godot objects by using:

[Export] 
Godot.Collections.Array<Label> Test 
or
[Export] 
Label[] Test

Create a Label node on the Editor.

Test will be exposed on the editor allowing you to create an array of type Label and also allowing you to select elements of type
Label from the scene, the problem is that after selecting the elements, nothing happens, the system just ignores your selection.

![image](https://user-images.githubusercontent.com/72418115/234298502-c3e50392-c226-4e67-af67-68069d88fb72.png)
![image](https://user-images.githubusercontent.com/72418115/234298621-35071869-43e4-497a-a802-e9e2c157568d.png)

//After selecting any of the above-allowed objects, the system just ignores your selection and the element will remain null within the array.

### Minimal reproduction project

N/A

**Comment by capnm** [comment]
Read the issue at the top of the Github page https://github.com/godotengine/godot/issues/62916

**Comment by KoBeWi** [comment]
Closing as duplicate.
