### ISSUE TITLE
Fix Silhoutte breaks some meshes in A-Pose

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#76448]
### Godot version

4.0.2-stable

### System information

Windows 10

### Issue description

I have a model in A-Pose. I was expecting to be able to import this model to Godot using its humanoid retargeter, by adapting it to T-Pose with the Fix Silhouette option. As noted in the documentation, this option "should be enabled for A-pose models.".

However, the resulting mesh looks wrong. In contrast, the resulting skeleton/armature looks correct.
![silhouette_fix_bug](https://user-images.githubusercontent.com/39946030/234375705-4912af99-0e60-4172-afa1-90e6e7f5ad80.png)
If the mesh deformed with this armature, it should not have been broken in this way, so it must be caused by a bug.

Here is the real world example which inspired this testcase. However, it is a paid asset and cannot be redistributed.
BoneMap but without Fix Silhouette. The bone rotations are not suitable for animation retargeting because the original model was in A-pose.
![image](https://user-images.githubusercontent.com/39946030/234375933-567672aa-2806-4056-8f78-c6f96fafbf3f.png)
BoneMap with Fix Silhouette. The animations now line up correctly, but the model's mesh or bind poses now appear to be corrupt.
![image](https://user-images.githubusercontent.com/39946030/234375955-889cb4cb-07ac-46b6-8455-b553b1f55440.png)

### Steps to reproduce

1. Open the attached project
2. Allow the models to import.
3. In main_scene, compare the models in front (no Fix Silhouette) to the model behind (Fix Silhouette). They should look the same, except one will be in A-Pose and the other in T-Pose.

### Minimal reproduction project

[SilhouetteFix.zip](https://github.com/godotengine/godot/files/11325908/SilhouetteFix.zip)
Here is the blender model pre-export [fix_silhouette.blend.zip](https://github.com/godotengine/godot/files/11325932/fix_silhouette.blend.zip)

**Comment by lyuma** [comment]
As an experiment, I rotated the bones so that they are all facing Y-forward. However, the issue still happens, so it should rule this out as the cause.
![image](https://user-images.githubusercontent.com/39946030/234395395-06fc0d99-a3a8-4cf2-a65f-6c0d531d9822.png)
![image](https://user-images.githubusercontent.com/39946030/234395415-13b00837-ae4b-410f-b163-e6d3158e3872.png)

Here are the blend and glb files with bones facing forward in Y
[fix_silhouette_rotated.blend.zip](https://github.com/godotengine/godot/files/11326522/fix_silhouette_rotated.zip)
[apose_silhouette_fix2.glb.zip](https://github.com/godotengine/godot/files/11326527/apose_silhouette_fix2.zip)

**Comment by TokageItLab** [comment]
It seems that for some reason `Use Named Skin` cannot be enabled and the skin/bone bindings are broken. It may be necessary to fix this so that bone idx is prioritized when `Use Named Skin` is disabled.

**Comment by lyuma** [comment]
Fixed some weight painting issues so each front/back triangle is attached to exactly one bone. It is now easy to tell that RightUpperLeg, RightShoulder, RightUpperArm, RightLowerArm, Neck and Head are really far off. LeftShoulder also looks a little bit offset.

glb plus .import: [apose_silhouette_fix2.glb.zip](https://github.com/godotengine/godot/files/11341191/apose_silhouette_fix2.glb.zip)
blend file: [fix_silhouette_rotated.blend.zip](https://github.com/godotengine/godot/files/11341286/fix_silhouette_rotated.zip)
![image](https://user-images.githubusercontent.com/39946030/234803416-ac47226f-aa6d-42d0-887b-155e4998da83.png)
