### ISSUE TITLE
Slow viewport recording

### ISSUE THREAD

**Issue by PeterMarques** [godotengine/godot#76465]
### Godot version

3.5

### System information

Win

### Issue description

I Will make a Second POST or a edit with findings and more detailed data. Tests and micro bench. 

But the thing is. Its Impossible to have a good framerate recording high resolution viewports using get_data

The thing is that inside the vídeo memory It can even do a realtime nested retrofeedback that do some cool abstract fractal efects so It can be performant but as said Its ALL inside the vram...

What os needed is someway to direcly extract the viewport data to a meaninful representation... But the thing is that the get_data().... Is already that, right?

So, How to possibly have the most perfectly performant highres viewport capturer?

I think on using shaders but maybe only doing a c extension one can get the ultmost performance.

Because what i need and what is needed is ultmost performance.

I know film mode of Godot4, maybe that implemantation can shed some light, but even that IS not performant in real time...

I guess Its simple a matter of raw power? There is no other way if we are talking about software capture... But maybe if we do some compression direclty on the GPU before sending to ram?

I personaly can compromisse pixel perfect image, but i need resolution and framerate.

Well thats the rambling. Soon i Will POST the bechmarks. But feel free to start talking about what is possible.

Thanks.

### Steps to reproduce

Record a viewport and ser the FPS get down as resolution get up

### Minimal reproduction project

Later

**Comment by Calinou** [comment]
This is expected. `get_data()` requires synchronization between the CPU and GPU, which is slow by design. You'd need to implement hardware readbacks by modifying Godot's core to be able to read viewport data quickly on the CPU, but this imposes a 2-3 frame delay.

**Comment by Calinou** [comment]
> I will se if there is any info on that proposal in the duplicate, but, why it is no planned, and i want and need, if delivered, of course it can be merged, right?

We don't have immediate plans to work on implementing hardware readbacks, but any contributor is free to do that :slightly_smiling_face:
