### ISSUE TITLE
Skeleton3D: setting animate_physical_bones in the Inspector does not work

### ISSUE THREAD

**Issue by jkulawik** [godotengine/godot#76502]
### Godot version

4.0.2

### System information

Pop_OS

### Issue description

After using "create physical skeleton" and playing an animation during runtime, the physical bones won't animate despite `animate_physical_bones` being set to true in the inspector.

Setting it to true through code in `_ready` makes the bones animate correctly.

### Steps to reproduce

- Import a rigged 3D model with an animation
- In the 3D viewport, use Skeleton -> create physical skeleton
- Optional: adjust the physical bones so that they're more visible
- Enable visible collision shapes in the debug tab
- place the model in a scene with a camera and see the bones remaining in the default pose while the mesh is animated
- Enable the option through code and see that it works correctly

```
func _ready():
	skeleton.animate_physical_bones = true
```

### Minimal reproduction project

See https://github.com/godotengine/godot/issues/75894 for an MRP that can be used to test this

**Comment by Mineorbit** [comment]
Thanks for splitting this bug of into a seperate issue :D

**Comment by KRC2000** [comment]
This is the nastiest bug I ever encountered. Even in the editor physical bones get animated, but not in the game. Spent whole day figuring this out, so happy it is actually a bug and not me going insane!
