### ISSUE TITLE
GPU usage increases considerably only enabling 2D particles turbulence

### ISSUE THREAD

**Issue by canepazzo77** [godotengine/godot#76501]
### Godot version

4.x

### System information

Windows 10, RTX 3070

### Issue description

Using 2D particles when enabling turbulence GPU usage increases dramatically.

Without Turbulence:
![ParticlesNoTurbulence](https://user-images.githubusercontent.com/58271518/234839571-1b957633-1eaa-458e-8a0b-6ad3534386f8.png)

With Turbulence:
![ParticlesWithTurbulence](https://user-images.githubusercontent.com/58271518/234839606-e3f3c417-76d8-4475-a9c7-2f09f6c5c805.png)

### Steps to reproduce

Add GPUParticles2D, add particle process material and enable turbulence

### Minimal reproduction project

see steps

**Comment by and-rad** [comment]
By how much is it increasing, exactly? This looks like less than a millisecond, which isn't great but sounds about right to me.

**Comment by canepazzo77** [comment]
> By how much is it increasing, exactly? This looks like less than a millisecond, which isn't great but sounds about right to me.

Every Particles node increase it about 0.4ms

**Comment by Zireael07** [comment]
IIRC turbulence uses noise, and IIRC 3d noise at that, which isn't free - 0.4ms sounds just about in the right ballpark

**Comment by canepazzo77** [comment]
ah, ok, I thouht an increase of 0,4ms for each node was much

**Comment by and-rad** [comment]
So, should this be closed? We can always argue whether 0.4ms is a "considerable" increase for adding a bunch of noise lookups in a shader, but I'm inclined to file this under "works as expected". Texture lookups aren't cheap.

**Comment by canepazzo77** [comment]
Yes

**Comment by Calinou** [comment]
I remember seeing this being reported elsewhere, but I can't find it right now.

This may be improved by https://github.com/godotengine/godot/pull/64606, although its main focus is making it more flexible.

**Comment by canepazzo77** [comment]
> 0.4 mspf on a RTX 3070 isn't a huge increase

But on mobile is that high? Because I wanted to use them in a mobile game

> This may be improved by #64606, although its main focus is making it more flexible. Feel free to [test that PR locally](https://docs.godotengine.org/en/latest/community/contributing/testing_pull_requests.html) 🙂

I will try it

**Comment by and-rad** [comment]
On mobile *everything* is high. Turbulence might not even work on mobile platforms at all, at least not in the Compatibility renderer. Have you ever exported and tested your project on a mobile device yet?

**Comment by canepazzo77** [comment]
Nevermind, I tried, it make the game crash

**Comment by QbieShay** [comment]
Both the generation of the 3D noise and the calculation of the gradient (curl formula?) of the noise are known to be expensive operations.
There's alternatives such as baking the noise on a 2D texture and using this texture for the particle motion.

If you can tell a bit more about the effects you want to achieve, we can think about solutions together.

I think overall this is a documentation issue. Perhaps the engine can warn when enabling turbulence that it's an expensive feature.

**Comment by canepazzo77** [comment]
I want to make a fire effect, like this

https://user-images.githubusercontent.com/58271518/235345716-914d81ef-6a87-4ab1-94e7-b0fe694534fb.mp4

**Comment by Calinou** [comment]
> I want to make a fire effect, like this
> 
>  2023-04-30.11-22-25.mp4

Turbulence sounds like a bad fit here. Using linear/angular velocity/acceleration and perhaps some damping should get you a convincing effect already.

**Comment by canepazzo77** [comment]
> I think overall this is a documentation issue. Perhaps the engine can warn when enabling turbulence that it's an expensive feature.

I checked several times and there does not seem to be, I think there should be also written in the documentation that does not work on mobile (at least it doesn’t work on phones where i tried it)

**Comment by canepazzo77** [comment]
> perhaps some damping should get you a convincing effect already.

thanks, damping made it look very similar, it was the setting I was missing

**Comment by QbieShay** [comment]
Slowdown's been documented, OP seem to have achieved the effect they were looking for. Good work everyone!

**Comment by RPicster** [comment]
One thing about this Issue brought up a thought.
I would love to see if the original 4.0 version of the turbulence calculation (the old one using only a "panning" noise instead of 4D noise) would have a compareable impact on performance.

Is there some way of testing this?
@QbieShay @clayjohn

**Comment by clayjohn** [comment]
> One thing about this Issue brought up a thought. I would love to see if the original 4.0 version of the turbulence calculation (the old one using only a "panning" noise instead of 4D noise) would have a compareable impact on performance.
> 
> Is there some way of testing this? @QbieShay @clayjohn
> 
> I reopened the issue - if that is something we should put in another issue or discuss somewhere else - feel free to close it ;)

You could copy the shader from an older project and then you could compare them side-by-side (i.e. by creating a ParticlesProcessMaterial  and converting to a shader material)

**Comment by QbieShay** [comment]
@RPicster we did perf test at the times when K made the new turbulence and there wasn't any perf impact that we could see

**Comment by RPicster** [comment]
Perfect, I remembered it. Just though I'd bring it up again in case it was related.

Then I'll close it again. 😁
