### ISSUE TITLE
Problems rendering multiline items in Tree.

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#76507]
### Godot version

4.1.dev

### System information

Ubuntu 22.04.1 LTS

### Issue description

![image](https://user-images.githubusercontent.com/85438892/234891938-c03c1172-9a55-493f-aa20-47d83cc449ef.png)

When I click one of the items it becomes normal, but the little line on the left doesn't match the icon:

![image](https://user-images.githubusercontent.com/85438892/234892457-57af338a-16fe-4d82-8a41-c19ff8225e84.png)

### Steps to reproduce

Go to the Node tab in the editor.

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
Probably a regression from #61714 ? CC @dalexeev

**Comment by MewPurPur** [comment]
Funny thing to call it a regression when the functionality didn't exist before... but yep.

**Comment by capnm** [comment]
> Funny to call it a regression since the functionality didn't exist before... but yep.

By regression he likely meant it looked good and now it looks terrible ...
