### ISSUE TITLE
[3.6beta1] Performance.MEMORY_MESSAGE_BUFFER_MAX returns current size, not max size

### ISSUE THREAD

**Issue by oeleo1** [godotengine/godot#76518]
### Godot version

3.6beta1

### System information

All

### Issue description

The `Performance.get_monitor(Performance.MEMORY_MESSAGE_BUFFER_MAX)` returns the current queue size instead of the max size. @lawnjelly 

### Steps to reproduce

Profile any project using deferred calls and compare the queue size curve on 3.6beta1 against previous versions.

### Minimal reproduction project

See steps to reproduce

**Comment by lawnjelly** [comment]
Ah I was unsure of what to return here at the time (the function internally is just called `MessageQueue::get_max_buffer_usage()`), I kind of loosely translated from reduz PR. Looking at the docs, the max buffer used so far seems to make sense I'll change this.

Although with a growable / shrinkable message queue, the current size might actually be more useful info, maybe for another PR though.

**Comment by oeleo1** [comment]
Yes, the current size is nice to have to see the savings but the peak value is always of critical interest when memory is involved.

**Comment by akien-mga** [comment]
Fixed by #76533.
