### ISSUE TITLE
Godot not support your video card

### ISSUE THREAD

**Issue by ryugold777** [godotengine/godot#76524]
### Godot version

4.0.dev

### System information

Intel HD Graphics 4000

### Issue description

When I open my project on arch linux show the message:

Your video card driver seem not to support required vulkan version .
if possible consider updating your video card driver or using the opengl3 driver
you can enable the opengl3 driver by -command-

but 2-3 days ago when I was with ubuntu I was able to run with forwward+. I compile from the source in Ubuntu and arch linux.

miss any packages?

### Steps to reproduce

When open Project

### Minimal reproduction project

[Demo.zip](https://github.com/godotengine/godot/files/11349075/Demo.zip)

**Comment by and-rad** [comment]
> miss any packages?

Probably. Did you make sure that you have the same drivers installed on both systems? Are you dual-booting or are these two different machines?

**Comment by akien-mga** [comment]
Make sure to install Vulkan drivers: https://wiki.archlinux.org/title/Vulkan

Closing as it's not a Godot bug, but a system configuration issue.

**Comment by Calinou** [comment]
> Make sure to install Vulkan drivers: [wiki.archlinux.org/title/Vulkan](https://wiki.archlinux.org/title/Vulkan)

Intel HD Graphics 4000 (Ivy Bridge) lack Vulkan support. Only the Compatibility rendering method can be used on it, as it only requires OpenGL 3.3.

**Comment by morfeo777** [comment]
> Solved! I removed amd and NVidia. Now Works! Thanks!

how you solved it? removing old drivers?

**Comment by ryugold777** [comment]
> > Solved! I removed amd and NVidia. Now Works! Thanks!
> 
> how you solved it? removing old drivers?

I removed the nVidia drives and AMD drives that was installed.

**Comment by raffomania** [comment]
In case other Arch users find this: I had only the `amdvlk` installed, additionally installing `vulkan-radeon` fixed it for me.
