### ISSUE TITLE
Textures in rgb8 format become rgba8 in rendering

### ISSUE THREAD

**Issue by Redwarx008** [godotengine/godot#76529]
### Godot version

4.02

### System information

Win10 Vulkan/GLES3 Intel(R) UHD Graphics 750

### Issue description

Textures in rgb8 format become rgba8 in rendering.
After debugging, I found that the format of texture is still rgb8, but the format of texture->rd_texture has changed to rgba8. I don’t know if it is intentional.

### Steps to reproduce

Create a texture in rgb8 format, and then use renderdoc to grab a frame to view.

### Minimal reproduction project

-

**Comment by Calinou** [comment]
Can you test the latest `master` branch? This was likely resolved by https://github.com/godotengine/godot/pull/76516 for lossless-compressed textures.
