### ISSUE TITLE
BitMap.opaque_to_polygons() fails on 1+2 pixel width/height

### ISSUE THREAD

**Issue by markusneg** [godotengine/godot#76531]
### Godot version

4.0.2.stable

### System information

Linux Mint 20.3

### Issue description

In _march_square() ([line 357](https://github.com/godotengine/godot/blob/master/scene/resources/bit_map.cpp#L357)) the assertion:

`ERR_FAIL_COND_V((int)count > width * height, Vector<Vector<Vector2>>());`

is not met when one of the bitmaps extents is 1 and opaque_to_polygons() is executed. I tested this with an 1x18 and 18x1 bitmap.

Mentioning @AThousandShips who recently did great work improving the _march_square() part.

### Steps to reproduce

Create an 1xn or nx1 BitMap and run opaque_to_polygons().

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Will take a look

**Comment by AThousandShips** [comment]
Believe this should be a previous error in ignoring that the polygons include an extra coordinate, the upper limit of the size, will test the correctness of a minor change and see, should be straight forward

**Comment by AThousandShips** [comment]
There, confirmed the bug and also confirmed it being resolved by this, please test it further if you are able to verify

**Comment by AThousandShips** [comment]
Also can you check if this bug is present in 3.x as well, will look into it there as well in that case

**Comment by AThousandShips** [comment]
> recently did great work improving the _march_square() part.

Also thank you very much!

**Comment by AThousandShips** [comment]
Then I will add a 3.x version of the fix as well
