### ISSUE TITLE
Errors in popup_menu.cpp

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#7655]
I'm using Windows 8.1, and Godot Stable v2.1.1.

Every time I open a project and navigate to a new scene, the console spits this out, and I'm wondering if it's cause for concern.

![godot_2017-01-27_14-48-55](https://cloud.githubusercontent.com/assets/13004169/22371477/fd3540d4-e49f-11e6-8462-dfc3a4fd3c37.png)

**Comment by bojidar-bg** [comment]
Does it happen in 2.1.2 too?

**Comment by avencherus** [comment]
@bojidar-bg Oh my, I've clearly had my head in the sand this week, didn't see the 2.1.2 release.  Tried it again, and seems not to happen in 2.1.2.  The problem from what I could tell happened only in projects where the main scene wasn't set.

Thanks for the response.

**Comment by avencherus** [comment]
Seems I spoke too soon, it reappeared once I enabled a plug-in that I made that adds a single custom node with no code in it.

![godot_v2 1 2-stable_win64_2017-01-27_16-08-40](https://cloud.githubusercontent.com/assets/13004169/22373566/fff4a444-e4aa-11e6-80fc-329c5b77fe6e.png)

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by avencherus** [comment]
@Noshyaar As far as I can tell it is no longer occurring.

**Comment by Noshyaar** [comment]
I'll close this as fixed then. Thanks. :)
