### ISSUE TITLE
Debugger showing incorrect RAM usage

### ISSUE THREAD

**Issue by vuk-noctiluca** [godotengine/godot#76558]
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Windows 10 IoT Enterprise LTSC

### Issue description

The "Video RAM" part of the Debugger lists the same resource hundreds of times and counts that resource's memory impact hundreds of times. It also prints the error message:

ERROR: Malformed ResourceUsage message from script debugger, message too long. Expected size: 1, actual size: 333
   at: (servers/debugger/servers_debugger.cpp:69)
(For the "actual size" bit, I've gotten numbers between 300 and 500; this will probably vary based on your device and the resource you're loading)

Even with a simple scene that contains only a TextureRect with the default icon, as seen in the attached images.

![scene setup](https://user-images.githubusercontent.com/62143274/235249480-5b562c92-67e3-4d31-a1ee-476a3ef48d6b.JPG)
![usage by resource](https://user-images.githubusercontent.com/62143274/235249484-069f5264-39c8-46ed-b7cb-82f217c2c78f.JPG)
![error message](https://user-images.githubusercontent.com/62143274/235249487-78c58791-ed52-440e-ae14-c6097bba794a.JPG)

### Steps to reproduce

- Make a project with a scene that renders a texture.
- Run that scene and go to the Video RAM tab of the Debugger.
- At this point, the error message appears in the console.

### Minimal reproduction project

[RAMtesting.zip](https://github.com/godotengine/godot/files/11357177/RAMtesting.zip)

**Comment by clayjohn** [comment]
This has been fixed already by https://github.com/godotengine/godot/pull/75782 

The fix will be in 4.1 and 4.0.3 :)
