### ISSUE TITLE
Losing precision when passing data to shaders?

### ISSUE THREAD

**Issue by SneaK1ng** [godotengine/godot#76554]
### Godot version

4.1.dev.custom_build.578ca94ef

### System information

Win10, GTX1060 5G, Vulkan1.3.236 

### Issue description

I passed some index data to the shader through `Color`, but somehow it lost precision when it came into the shader.

And `Color `looks like it doesn't allow data above 1.0... Is it intentionally designed like this?

**GDScript:**
```
extends MeshInstance3D

var tmpMesh = Mesh.new()
var vertices = PackedVector3Array()
var color = Color(1.0, 0, 0)

func _ready():
	var st = SurfaceTool.new()

	st.begin(Mesh.PRIMITIVE_TRIANGLES)
	# TRIANGLE 1
	st.set_color(Color(0.1, 0, 0, 1))
	st.add_vertex(Vector3(-1, -1, 0))

	st.set_color(Color(0.1, 0, 0, 1))
	st.add_vertex(Vector3(-1, 1, 0))

	st.set_color(Color(0.1, 0, 0, 1))
	st.add_vertex(Vector3(1, 1, 0))
	# TRIANGLE 2
	st.set_color(Color(0.11, 0, 0, 1))
	st.add_vertex(Vector3(-1, -1, 0))

	st.set_color(Color(0.11, 0, 0, 1))
	st.add_vertex(Vector3(1, 1, 0))

	st.set_color(Color(0.11, 0, 0, 1))
	st.add_vertex(Vector3(1, -1, 0))

	st.set_material(load("res://shader.tres"))

	mesh = st.commit()
```
**Palette in editor:**
![image](https://user-images.githubusercontent.com/6891132/235220914-2e875abc-ae7d-44e0-8339-50b1e91df6d6.png)

**Shader:**
```
shader_type spatial;

uniform vec3 palette[3];
varying vec3 color;

void vertex(){
	int index = int(COLOR.r * 10.0);
	color = palette[index];
}

void fragment() {
	ALBEDO = color;
}
```

**Image:** Should be all green! but...
![image](https://user-images.githubusercontent.com/6891132/235220317-83a18f12-14ef-479f-ba5b-b1afe82ab1c5.png)

### Steps to reproduce

run the reproduction project.

### Minimal reproduction project

[TEST_ARRAY_INDEX.zip](https://github.com/godotengine/godot/files/11356307/TEST_ARRAY_INDEX.zip)

**Comment by SneaK1ng** [comment]
May be related to https://github.com/godotengine/godot/issues/76160?

**Comment by Calinou** [comment]
> And Color looks like it doesn't allow data above 1.0... Is it intentionally designed like this?

In Godot 4.x, vertex color data is limited to 8-bit integer for performance reasons (as it decreases memory bandwidth with complex meshes).

**Comment by SneaK1ng** [comment]
> In Godot 4.x, vertex color data is limited to 8-bit integer for performance reasons (as it decreases memory bandwidth with complex meshes). See #75083.

Thanks for your response.

> Are you sure that `int()` truncation isn't rounding the number down when you expect it to be rounded up?

I think `* 10.0` will be executed before executing `int().`

`int(0.1 * 10.0) → int(1.0) → 1` expected

`int(0.1 * 10.0) → int(1.0) → 0` now

Or is this not the current order?

but the `0.11` is calculated correctly.

`int(0.11 * 10.0) → int(1.1) → 1` now

**Comment by AThousandShips** [comment]
Note that 0.1 is not a value that can be represented in binary, so there's very possibly rounding errors especially with 8 bit limits

**Comment by SneaK1ng** [comment]
> Note that 0.1 is not a value that can be represented in binary, so there's very possibly rounding errors especially with 8 bit limits
> 
> If using 8 bit integer colours we get: (25.5,0,0,255) which is just (25,0,0,1), transformed to floating point we get (25/255,0,0,1) which becomes 250/255 when multiplying by 10, which is where I assume the issue comes from
> 
> For 0.11 you instead get 28 and 280/255

This makes sense. Got it!

How do I pass int data precisely to each vertex()?
Is it possible to do this with CUSTOM0?

**Comment by AThousandShips** [comment]
You can probably use some method to encode a whole 32 bit value as a colour, but I'm not sure how color space transforms affect this

**Comment by SneaK1ng** [comment]
> You can probably use some method to encode a whole 32 bit value as a colour, or 16 or 24 bits if you like, but I'm not sure how color space transforms affect this, assuming you're not using colour that is

Thanks for your advice; I'll give it a try.

**Comment by AThousandShips** [comment]
Try out the `packUnorm4x8` and `packUnorm2x8` functions in the shader as well, just to see, the GDScript side should be done with bit shifts, will investigate in a bit and see if I have any suggestions

**Comment by AThousandShips** [comment]
For the GDScript side try using `to_argb32` and see how it lines up with the pack 4x8 function

**Comment by SneaK1ng** [comment]
> For the GDScript side try using `to_argb32` and see how it lines up with the pack 4x8 function

Tnanks again!

And how do you think about https://github.com/godotengine/godot/issues/76160 ?

Is it caused by the same reason?

**Comment by AThousandShips** [comment]
Hard to tell tbh, but could be
