### ISSUE TITLE
Using queue_free has errors when removing something with a Shape keys

### ISSUE THREAD

**Issue by yatoimtop** [godotengine/godot#76559]
### Godot version

4.0.2 Stable

### System information

Windows 10, Vulkan, RTX 2060

### Issue description

Whenever I Queue_free() any mesh with a shape key I get a few errors like this:
```
E 0:00:25:0342   _free_internal: Attempted to free invalid ID: 13314398617604
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:8394 @ _free_internal()
```
Additionally, when I'm switching scenes and need to queue_free the previous scene I get a bunch of these errors as well.

Here's a video demonstration of this recorded on a testing level:
https://www.youtube.com/watch?v=PACxpzaQROA

This is just a simple test scene that calls queue_free when the player walks over that blue bar.

### Steps to reproduce

Call queue_free() on an object with shape keys.

### Minimal reproduction project

[queueFreeTest.zip](https://github.com/godotengine/godot/files/11357553/queueFreeTest.zip)

**Comment by Calinou** [comment]
Thanks for the report. Consolidating as part of https://github.com/godotengine/godot/issues/75724.
