### ISSUE TITLE
Referencing a built-in matrix within the light() function of a spatial shader throws an error; falls back

### ISSUE THREAD

**Issue by ardlak** [godotengine/godot#76556]
### Godot version

4.0.2.stable.official

### System information

Windows 10, NVIDIA GeForce RTX 2080 SUPER, Driver 516.94, Vulkan backend

### Issue description

When referencing a built-in matrix (MODEL_MATRIX, VIEW_MATRIX...) within the light() function of a spatial shader, these errors are thrown per renderer:

Forward+:
```
-   servers/rendering/renderer_rd/forward_clustered/scene_shader_forward_clustered.cpp:171 - Condition "!shader_singleton->shader.version_is_valid(version)" is true.
```
Mobile:
```
-   servers/rendering/renderer_rd/forward_mobile/scene_shader_forward_mobile.cpp:182 - Condition "!shader_singleton->shader.version_is_valid(version)" is true.
```
Compatibility (MODEL_MATRIX is referenced):
```
-  drivers/gles3/shader_gles3.cpp:242 - SceneShaderGLES3: Fragment shader compilation failed:
-   0(521) : error C1503: undefined variable "model_matrix"
-   drivers/gles3/shader_gles3.cpp:342 - Method/function failed.
```

The shader displays a fallback instead of what's written. This can be avoided by defining a variable that is identical to the matrix and referencing that instead:

```
shader_type spatial;

varying mat4 mdlMtx;

void vertex() {
	mdlMtx = MODEL_MATRIX;
}

void light() {
	mdlMtx; // works
//	MODEL_MATRIX; // doesn't work
}
```

### Steps to reproduce

In a spatial shader, reference any built-in matrix within the light function:

```
shader_type spatial;

void light() {
	DIFFUSE_LIGHT += ATTENUATION; // lighting that should be displayed
	MODEL_MATRIX; // breaks the shader, displays a fallback
}
```

### Minimal reproduction project

[issue_light_matrices.zip](https://github.com/godotengine/godot/files/11356572/issue_light_matrices.zip)

**Comment by clayjohn** [comment]
Looks like the rest of the matrices need to be renamed in the light function. This comes from the uniform for the matrices using a different name from what the shader compiler maps onto.

For example, here is what is done in the GLES3 renderer's fragment function:
https://github.com/godotengine/godot/blob/9f12e7b52d944281a39b7d3a33de6700c76cc23a/drivers/gles3/shaders/scene.glsl#L934-L945

The shader compiler turns ``MODEL_MATRIX`` into ``model_matrix``, but the uniform is called ``world_transform`` so it needs to be remapped.

**Comment by mohsenph69** [comment]
I Think get some related Issue

When I use this to calculate light direction in world space;
`vec3 light_dir = mat3(INV_VIEW_MATRIX) * LIGHT;`

In editor it will give me no error but I will give me a huge error in console

```
   at: _compile_variant (servers/rendering/renderer_rd/shader_rd.cpp:286)
### ERROR: Condition "!shader_singleton->shader.version_is_valid(version)" is true.
   at: set_code (servers/rendering/renderer_rd/forward_clustered/scene_shader_forward_clustered.cpp:171)
### ERROR: Condition "!shader" is true. Returning: RID()
   at: uniform_set_create (drivers/vulkan/rendering_device_vulkan.cpp:5361)
### ERROR: Condition "!us" is true.
   at: uniform_set_set_invalidation_callback (drivers/vulkan/rendering_device_vulkan.cpp:5835)
```
