### ISSUE TITLE
create_timer() doesn't pause

### ISSUE THREAD

**Issue by mateusak** [godotengine/godot#7656]
**Disclaimer: I tried finding anything about this on the issues, but I failed. It's weird because I think someone would have made an issue already. So maybe i'm stupid.**

**Operating system or device - Godot version:**
Godot 2.2

**Issue description:**
`get_tree().create_timer(seconds)` still runs while the game is paused. I expected it to pause just like anything else.

**Comment by tamkcr** [comment]
I think adding a pause considering flag in the function (or another function) as a feature proposal would be better since some people could be utilizing the current behavior

**Comment by mateusak** [comment]
@tamkcr That's a good idea. Something like that:

get_tree().create_timer(seconds, ignore_pause = false)
