### ISSUE TITLE
GDExtension API: Modulo operator’s enum is misnamed `OP_MODULE`

### ISSUE THREAD

**Issue by ParadoxV5** [godotengine/godot#76588]
### Godot version

as early as 3.1 – 4.0.2

### System information

GDExtension (also applies to GDNative)

### Issue description

Moved and elaborated from godotengine/godot-headers#105

The modulo operator’s enum in GDExtension/GDNative is named `OP_MODULE` rather than `OP_MODULO`.

C header: https://github.com/godotengine/godot/blob/9f12e7b52d944281a39b7d3a33de6700c76cc23a/core/extension/gdextension_interface.h#L119
API JSON: https://github.com/ParadoxV5/godot-headers/blob/732ed57b5f19583a7af4272e58ce509d5ff58586/extension_api.json#L3985

* If this is not intended, a change for the next minor patch is much appreciated.
* If this is intentional (e.g., header naming limitation), please document the reason either near the header line or on Godot docs and link.
* If this is not intended but was left as is simply for backward compatibility, then it’s unfortunate that the Godot 4.0 overhaul overlooked it, but it deserves consideration for the hypothetical future version 5.0. (I searched the tracker with the keyword ‘modulo’ already and there wasn’t a previous issue for project tracking.)

### Steps to reproduce

* C header: check the `core/extension/gdextension_interface.h` file at around line 119
* API JSON: [generate the file](https://github.com/godotengine/godot-headers#updating-headers) and look at around line 3985

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
> If this is not intended but was left as is simply for backward compatibility, then it’s unfortunate that the Godot 4.0 overhaul overlooked it, but it deserves consideration for the hypothetical future version 5.0. (I searched the tracker with the keyword ‘modulo’ already and there wasn’t a previous issue for project tracking.)

- See https://github.com/godotengine/godot/pull/76446.

**Comment by ParadoxV5** [comment]
> it’s unfortunate that the Godot 4.0 overhaul overlooked it

Just came across #16863. `OP_MODULE` ➡ `OP_MODULO` is not on final list.

**Comment by akien-mga** [comment]
The GDExtension API reflects what's in the core Variant API:

https://github.com/godotengine/godot/blob/116f783db73f4bf7e9e96ae54dd3d0a20337cc8a/core/variant/variant.h#L522

Changing this would break compatibility, which we don't want to do before Godot 5 unless it's absolutely needed to fix critical issues. This slight misnomer doesn't seem critical to fix now.

**Comment by ParadoxV5** [comment]
> Changing this would break compatibility, which we don't want to do before Godot 5 unless it's absolutely needed to fix critical issues. This slight misnomer doesn't seem critical to fix now.

> If this is not intended but was left as is simply for backward compatibility, then it’s unfortunate that the Godot 4.0 overhaul overlooked it, but it deserves consideration for the hypothetical future version 5.0. (I searched the tracker with the keyword ‘modulo’ already and there wasn’t a previous issue for project tracking.)
