### ISSUE TITLE
Continously Vulkan crashes

### ISSUE THREAD

**Issue by heavyathan** [godotengine/godot#76590]
### Godot version

v4.1.dev1.official.db1302637

### System information

Windows 10, Vulkan, GPU AMD Radeon R7 M260

### Issue description

Godot 4.1.dev1 version randomly get stuck, Console shows that Vulkan driver gets lost, and only option is force-close of the program.
It happens in different situations and with no clear patron: changing a texture, importing a resource, rotating an scene, navigating in project folders, asigning materials...
Tried in Forward and Mobile renderer. Same issue. 
I took a couple of screenshots. Always same error:

![Captura de pantalla 2023-04-29 201325](https://user-images.githubusercontent.com/100681249/235323270-74089117-f5a0-4e07-86ee-24d3270aa9aa.png)
![Captura4](https://user-images.githubusercontent.com/100681249/235323271-47a3ec11-608b-42a0-8867-58be6582e2b1.JPG)

Of course, drivers are updated:
![Driver](https://user-images.githubusercontent.com/100681249/235323362-40f4aef8-95b5-4926-86b2-5e59131fa156.png)

I don't know a way to get any kind of trace or more information

### Steps to reproduce

Not able to. It's random. 

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Thanks for the report! Consolidating this in https://github.com/godotengine/godot/issues/71929.
