### ISSUE TITLE
Engine froze after testing project, files missing after reopening

### ISSUE THREAD

**Issue by SalTeyJek004** [godotengine/godot#76595]
### Godot version

v4.0.2.stable.official.7a0977ce2

### System information

Windows 10

### Issue description

uh, i closed my project window after testing, and the engine window was frozen.
it didnt unfreeze so i force closed it, but it froze before showing the project list every time i tried to open it again, even after i reinstalled it.
after i restarted my computer it didnt freeze, and after opening my project again i found most of my files missing.
i only had 12 project files, and 10 were missing.

### Steps to reproduce

i have no clue how to reproduce

### Minimal reproduction project

N/A it got deleted :(

**Comment by Calinou** [comment]
We need definitive reproduction steps to be able to do anything.

**Comment by radlotus** [comment]
What do you mean by `closed my project window after testing`? What were you doing before the window froze?

**Comment by SalTeyJek004** [comment]
i ran my project to test it. the fact that it ran means that the editor froze after saving my project. so it cant be an issue with saving, i think.

**Comment by SalTeyJek004** [comment]
> We need definitive reproduction steps to be able to do anything.

because my project files went missing, i have no way to exactly reproduce the steps.
also, i was running my project to test it before to this incident, and it went normaly. i really have no clue what happend, but considering it didnt fix after i reinstalled it might be an issue with my computer. i'll try and find out what i did if it happens again.

**Comment by Zireael07** [comment]
if things were deleted from hard drive reinstalling is unlikely to fix, also IIRC uninstaller doesn't clear project list/cache/etc.

(Also: did you just look at the project list, or did you check the actual folder/files in file explorer? )

**Comment by radlotus** [comment]
You might be able to recover the project files. 
You can use `DM Disk Editor and Data Recovery Software`. 
The free version can recover up to 4000 files.

**Comment by Calinou** [comment]
@SalTeyJek004 Did you look into using file recovery tools as mentioned above?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.
