### ISSUE TITLE
get_global_mouse_position() gives incorrect coordinates in an editor plugin

### ISSUE THREAD

**Issue by Crystalwarrior** [godotengine/godot#76599]
### Godot version

4.0.2

### System information

Windows 10, Compatibility, NVIDIA GeForce GTX 1050

### Issue description

Right-click creates a PopupMenu at the get_global_mouse_position, like so:
`_item_popup.position = get_global_mouse_position()`

However, the position is wrong, and it only gets more wrong when the editor window size changes.

Video footage of the issue:

https://user-images.githubusercontent.com/3470436/235327246-6fb43711-5a7e-45e9-a22c-713860ecb583.mp4

### Steps to reproduce

* Make an editor script that sets a control or a popupmenu position to the global mouse position

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
`get_global_mouse_position()` returns mouse position in Window's coordinates, while Popup uses screen coordinates. Use `DisplayServer.mouse_get_position()` instead.

**Comment by Crystalwarrior** [comment]
> `get_global_mouse_position()` returns mouse position in Window's coordinates, while Popup uses screen coordinates. Use `DisplayServer.mouse_get_position()` instead.

Oh, thank you so much! This should be documented somewhere for sure though.
