### ISSUE TITLE
Godot is not friendly with tiling window managers

### ISSUE THREAD

**Issue by shackra** [godotengine/godot#766]
I'm user of [SpectrWM](https://github.com/conformal/spectrwm/wiki), a *small dynamic tiling window manager for Xorg*.

There are two issues:

1. all the Godot windows (the project list, the editor and the game preview) have exactly the same *class* and *instance* according to `xprop | grep -E "^(WM_CLASS|_NET_WM_NAME|WM_NAME)"`, this makes me unable to change the tiling behavior according to each different window, i.e.: making the game preview window float over the rest of windows. And,
2. The elements of any windows do not accommodate to the window size upon startup, look:
![godot-mal](https://cloud.githubusercontent.com/assets/1055216/4554973/25b8ed3e-4eb7-11e4-9dc6-f0d7797a90dc.png)
I have to float the window and then stack it again in order to get the elements of Godot's UI accommodate to the size of the window when stacked:
Floating: 
![godot-float](https://cloud.githubusercontent.com/assets/1055216/4555006/7dd46908-4eb7-11e4-8737-c49163679592.png)
re-stacked: 
![godot-bien](https://cloud.githubusercontent.com/assets/1055216/4555011/8ac2c38a-4eb7-11e4-9343-cfc97776640d.png)
After this, Godot is able to fit the GUI properly.

Hope this bug report makes sense. Having this fix before Godot hits version 1.0 is a good idea, so I better report this now.

**Comment by greescom** [comment]
I have exactly the same problem in the DWM tiling window manager.

The Godot windows are unresponsive until floated and re-stacked. The class & name fields are different in the 1.0 stable release but I still cannot auto float the preview game window for some reason.

Had a few crashes where the entire workspace became unresponsive due to window issues.

This bug makes it very uncomfortable to use Godot.

**Comment by shackra** [comment]
Me neither, I have set `quirk[Godot:Godot] = FLOAT` in the SpectrWM configuration file and nonetheless the
window do not float. I have to do the same as you, float and re-stack, to get the UI properly drawn at the
window dimensions.

The class and names should be different in Godot, the project list should have its own, so the editor and the
same for the game preview.

greescom writes:

> I have exactly the same problem in the DWM tiling window manager.
>
> The Godot windows are unresponsive until floated and re-stacked. The class & name fields are different in the 1.0 stable release but I still cannot auto float the preview game window for some reason.
>
> Had a few crashes where the entire workspace became unresponsive due to window issues.
>
> This bug makes it very uncomfortable to use Godot.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/okamstudio/godot/issues/766#issuecomment-70944794

-- 
Pax et bonum.
Jorge Araya Navarro.
ES: Diseñador Publicitario, Programador Python y colaborador en Parabola GNU/Linux-libre
EN: Ads Designer, Python programmer and contributor Parabola GNU/Linux-libre
EO: Anonco grafikisto, Pitino programalingvo programisto kai kontribuanto en Parabola GNU/Linux-libre
https://es.gravatar.com/shackra

**Comment by shackra** [comment]
> or annoy Juan and Ariel to fix what is not working for you.

Psss, @reduz and @punto- !

**Comment by blendi-93** [comment]
i have similair issues using bspwm + Godot 1.1beta1.

and godot has no instance or class set one initial window draw.
