### ISSUE TITLE
C# Input object creation explosion

### ISSUE THREAD

**Issue by duarteroso** [godotengine/godot#76607]
### Godot version

4.0.2

### System information

Win10

### Issue description

This was only tested in the .NET version.

It seems that the C# backend is creating an insane amount of objects when handling input events.
Moving the joy sticks for a few seconds makes the objects count (and the associated memory) go higher than it probably needs to.
It also spikes using keyboard or mouse input events, but it is more noticable with gamepads.

### Steps to reproduce

1. Create a node and attached to it a C# script.
2. That script needs to override the `_Input` methods
3. Using an input controller (gamepad preferably, keyboard or mouse also acceptable)
4. Notice in the `Debugger` panel, under `Monitor` tab that the `Objects` count will spike quickly
5. Notice as well that the `Memory` increases significantly as well

### Minimal reproduction project

The project contains a scene; the scene contains a `Node3D` and a C# script attached to it.
The script overrides the `_Input` methods.

[InputObjects.zip](https://github.com/godotengine/godot/files/11360871/InputObjects.zip)

**Comment by duarteroso** [comment]
![objects_monitor](https://user-images.githubusercontent.com/11413364/235343672-a8eeb6ee-38c7-4e69-bfe4-13f62ffa06da.PNG)

**Comment by Zireael07** [comment]
IIRC it was already reported and is due to how input is implemented, and GC

**Comment by RedworkDE** [comment]
Duplicate of:
- https://github.com/godotengine/godot/issues/75269
- https://github.com/godotengine/godot/issues/72776

**Comment by duarteroso** [comment]
It is not clear from the linked issues if 
- this is something Godot can improve on
- is it a known limitation of the .NET environment?
- can these input events be reused instead of creating an new object?

**Comment by RedworkDE** [comment]
- Is there any actual issue caused by this behavior, beyond that number goes up and then it goes down again?
- This is the expected behavior of any garbage collected system when creating and then no longer referencing a whole bunch of objects
- No, because the handler could keep a reference to the input event after _Input returns.
  Also creating the managed wrappers is really cheap, so caching them make no sense and the expensive underlying native objects have to be created anyways.

**Comment by duarteroso** [comment]
No issue as far as I can see. Only a consern of maximum efficiency/performance .
