### ISSUE TITLE
Support multiple uv + color channels

### ISSUE THREAD

**Issue by Gibbz** [godotengine/godot#7661]
**Operating system or device - Godot version:**
ubuntu 16.04
godot 2.2

**Issue description:** **Steps to reproduce:**
Adding multiple uv and multiple color channels in blender from the data tab.
Export using provided exporter.
Import the mesh in godot....
1. There is no shader access to these channels.
2. The data is not even exported from blender.

**Comment by reduz** [comment]
there is support for up to 2 UV chanels, more is unsupported

**Comment by Gibbz** [comment]
what about color channels?

**Comment by reduz** [comment]
there is already support for a single color channel, too

**Comment by Gibbz** [comment]
no i mean multiple color channels. For working with more advanced shaders such as terrain blending I need a few uv channels and a few color channels

**Comment by reduz** [comment]
godot array layout is fixed, and there are no plans to change this, so
that's as much as you get

**Comment by Gibbz** [comment]
is there at least anyway to get vertex alpha through the pipeline?

**Comment by reduz** [comment]
yeah, vertex color is RGBA, you get it in the vertex program as COLOR.a (or
SRC_COLOR.a, I don't remember).

**Comment by Gibbz** [comment]
ok i dont think blender has anyway to export alpha vertex channels with the collada exporter.
I have changed the way i do my terrain to use a heightmap with textures for color and layers now instead of a mesh.
