### ISSUE TITLE
TileMap Rendering issue on Android

### ISSUE THREAD

**Issue by florisgravendeel** [godotengine/godot#76612]
### Godot version

RC 1 4.0.3 and 4.0.2 stable

### System information

OnePlus A6 (Android-version 11)

### Issue description

Hi,

I'm currently working on a TileMap and testing it on iOS and Android. It seems there is a rendering issue when exporting to my Android device.

**OnePlus A6**

https://user-images.githubusercontent.com/1598486/235357552-02cf4b56-8673-4521-9543-b9c81608e292.mp4

**iPhone 14 Pro Max** (works fine)

https://user-images.githubusercontent.com/1598486/235357599-ea4b83e0-5151-4f1b-a5da-e1d8addc1d95.MP4

### Steps to reproduce

1. Create a TileSet and TileMap
2. Export to Android (default settings)

### Minimal reproduction project

[TileMap rendering.zip](https://github.com/godotengine/godot/files/11361493/TileMap.rendering.zip)

**Comment by groud** [comment]
Is it still reproducible on latest version ? This is likely a rendering bug unrelated to the TileMap system itself. It might have been fixed.

**Comment by florisgravendeel** [comment]
Still occuring on Godot 4.0.3
If it's a unrelated rendering bug, do you know how to fix it?

**Comment by florisgravendeel** [comment]
The issue is solved on Godot 4.1 beta 3 if you disable texture padding in the TileSet properties. Also this issue may be a duplicate. See https://github.com/godotengine/godot/issues/71020#issuecomment-1483887883
