### ISSUE TITLE
Editor resets position to primary display after project finishes loading on macOS

### ISSUE THREAD

**Issue by ztc0611** [godotengine/godot#76628]
### Godot version

4.0, 4.1.dev

### System information

macOS Monterey, macOS Ventura

### Issue description

When the editor is opening a project, if you drag the window onto another screen before it is finished, the editor will return to the "default" monitor upon loading being complete. This might first appear to be an instance of #26877, but from my experience it is not.

### Steps to reproduce

Open any project on macOS, and drag it onto a second display while it is in the process of opening. This is easier to notice on larger projects that take longer to load.

### Minimal reproduction project

Happens on any project.

**Comment by YuriSizov** [comment]
cc @bruvzg Maybe you could take a look?

**Comment by ztc0611** [comment]
This still occurs on 4.1.3, I've not tried 4.2. I managed to work around the problem by just changing the default monitor Godot opens on. Not a perfect solution but that mostly works in the meantime.
