### ISSUE TITLE
HTML refuses to load with Engine is not defined 404 error

### ISSUE THREAD

**Issue by ca3gamedev** [godotengine/godot#76622]
### Godot version

3.5.2-stable

### System information

Manjaro XCFE, Intel core i3 11 generation.

### Issue description

When I test my html5 game on neocities, an error message appears.
Project runs fine on localhost.

caught ReferenceError: Engine is not defined
at (index):143:16
to load resource: the server responded with a status of 404 ()

This is the line of code that the error is coming from the console.

const GODOT_CONFIG = {"args":[],"canvasResizePolicy":2,"executable":"My html game","experimentalVK":false,"fileSizes":{"My html game.pck":5257072,"My html game.wasm":13793958},"focusCanvas":true,"gdnativeLibs":[]};
		var engine = new Engine(GODOT_CONFIG);

Using the GLES 2 renderer.

### Steps to reproduce

Opening site on chromium causes the error under the GLES 2 renderer.
On Firefox there's a forbidden page.

Using the GLES 3 renderer it causes a forbidden page on chromium.

### Minimal reproduction project

N/A

Project is just a test picture with a sound on screen.

**Comment by Calinou** [comment]
Closing per the above comment.
