### ISSUE TITLE
Editor builds compiled from source on macOS cause an excessive amount of permission popups

### ISSUE THREAD

**Issue by ztc0611** [godotengine/godot#76629]
### Godot version

4.0, 4.1.dev

### System information

macOS Monterey, macOS Ventura. Apple M1.

### Issue description

Versions of the engine built from source ask for permissions an excessive number of times, and never remember this information. Every time Godot is relaunched or the project is ran again, the events shown in the video happen. This includes of the engine has not been re-compiled between launches.

https://user-images.githubusercontent.com/28269330/235374582-375c137a-c68c-439e-9818-51b1c2579743.mov

This project does not run any scripts that pull data from disk, such as a save file or config files.

https://user-images.githubusercontent.com/28269330/235374593-1c8cb87e-18de-4f14-8462-8302b4250b64.mov

### Steps to reproduce

Build engine from source on macOS and then attempt to work with any project.

### Minimal reproduction project

Works on any.

**Comment by ajreckof** [comment]
Would you mind sharing the exact workflow you are using as I'm working on a M1 with MacOS Ventura and never stumbled on this issue. I see on the background that you are using VCS have you tried compiling and launching from terminal? it might be linked to VCS. it might also be linked to your security settings but I don't see anything out of the box.

**Comment by ztc0611** [comment]
I compile directly from terminal using a script I wrote. I'll give a more specific rundown when I get home.

**Comment by ztc0611** [comment]
Sorry, I forgot to follow up about this. I use this script to compile the engine when I'm messing with it. I run it manually via terminal, I only use VSCode to look at and edit the code, no build stuff set up.

```
cd /Users/ztc0611/Documents/GitHub/godot
rm -rf bin/
scons -j7 platform=osx arch=x86_64 --jobs=$(sysctl -n hw.logicalcpu)
scons -j7 platform=osx arch=arm64 --jobs=$(sysctl -n hw.logicalcpu)
lipo -create bin/godot.macos.editor.x86_64 bin/godot.macos.editor.arm64 -output bin/godot.macos.tools.universal
cp -r misc/dist/macos_tools.app ./Godot.app
mkdir -p Godot.app/Contents/MacOS
cp bin/godot.macos.tools.universal Godot.app/Contents/MacOS/Godot
chmod +x Godot.app/Contents/MacOS/Godot
mv Godot.app /Users/ztc0611/Documents/
cd /Users/ztc0611/Documents/
rm -rf "Godot Build Stuff/Godot 4.0 Custom.app"
mv Godot.app "Godot Build Stuff/Godot 4.0 Custom.app"

**Comment by ajreckof** [comment]
Would you mind testing if you can reproduce this without making an application and just running the script from terminal something like
```
cd /Users/ztc0611/Documents/GitHub/godot
scons -j7 platform=osx arch=arm64 --jobs=$(sysctl -n hw.logicalcpu)
.bin/godot.macos.editor.arm64 
```

**Comment by ztc0611** [comment]
It does not appear to have permission weirdness when this is done. 😁

**Comment by ajreckof** [comment]
Ok so this is linked to bundling into an app so this explain why I never had this one. I'll try to replicate your exact setup to see where it does come from

**Comment by ajreckof** [comment]
So this happens in a consistant way when bundling it into a `.app`. The core problem is that the parameter is not remembered at all which mean every time it tries to access some protected folder it asks again about permissions. Those permissions are in fact properly remembered by the System as they appear in Editor Settings but the application isn't able to detect it.

**Comment by akien-mga** [comment]
CC @bruvzg

**Comment by bruvzg** [comment]
Make sure to always codesign updated app bundle. I have never seen this with Godot myself, but sometimes this can happen with the local build of any app.

**Comment by ajreckof** [comment]
Tested this was effectively what was causing this. This should be stated in https://docs.godotengine.org/en/latest/contributing/development/compiling/compiling_for_macos.html . I'll make a PR on the godot docs

**Comment by ztc0611** [comment]
So the only thing I need to change is adding .opt in that line modified in the docs PR? Or am I missing something else?

**Comment by ajreckof** [comment]
No the opt was removed because it was used before it is just an update of an old name it does not have anything real to do with this issue what is important is the codesign line in the doc PR
`codesign -fs - Godot.app`
