### ISSUE TITLE
Using a variable in range crashes Godot

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#7662]
Using a variable in range crashes Godot.
```
for s in range(0,["1","2"].size()):
   print(s)
```

```
var a = ["1","2"].size()
for s in range(0,a):
   print(s)
```

```
var a = ["1","2"]
for s in range(0,a.size()):
   print(s)
```

```
var a = ["1","2"].size()
for s in range(a):
   print(s)
```

Error
tools.64 ERROR: operator[]: Condition ' p_index<0 || p_index>=size() ' is true. returned: aux
   At: core/vector.h:133.

**Operating system or device - Godot version:**
x11
3.0 Master

**Comment by lonesurvivor** [comment]
Can confirm, that happens to me too.
