### ISSUE TITLE
.blend Meshes/Colors aren't importing correctly

### ISSUE THREAD

**Issue by toafloast** [godotengine/godot#76626]
### Godot version

4.0.stable

### System information

Windows 11 (x64), Intel(R) Core(TM) i5-9400 CPU, Vulkan,  NVIDIA GeForce GTX 1660 Ti driver version 528.24

### Issue description

enabling Mesh colors in a .blend import does not properly set the vertex colors.
![image](https://user-images.githubusercontent.com/104696964/235373548-f344a4e4-cc15-4e98-aed9-a9d8dc8d56e9.png)
![image](https://user-images.githubusercontent.com/104696964/235373669-a6a68e86-6bc8-4199-bdb6-5ba2498c635f.png)
(the Right one is a .gltf)

### Steps to reproduce

1. Import a .blend with some vertex colors on it. 
2. Open the .blend to change import settings, and enable **Meshes/Colors** and re-import
3. The colors are messed up.

For the minimal reproduction project, open **colorful-unset.blend**, enable Meshes/Colors, and re-import.

### Minimal reproduction project

[vertexcolor-minreproduce.zip](https://github.com/godotengine/godot/files/11362213/vertexcolor-minreproduce.zip)

**Comment by fire** [comment]
I'm a bit slow right now. Would like help on validating, and fixing gltf import.

**Comment by scurest** [comment]
You are probably using Blender 3.4, which shipped with a vertex color export bug (https://github.com/KhronosGroup/glTF-Blender-IO/issues/1815). Get Blender 3.5 and make sure Godot is using that.

**Comment by toafloast** [comment]
I have now updated Blender to 3.5- while gltf files seem to be importing importing properly now (inconsistent in 3.4), enabling Meshes/Colors when importing a .blend file still produces the bug. I've restarted the editor after setting the blender installation path to 3.5. 
![image](https://user-images.githubusercontent.com/104696964/235786703-8639426f-521d-4889-96b0-dc34ce8398d8.png)

**Comment by clayjohn** [comment]
@toafloast What value is your ``filesystem/import/blender/blender3_path`` editor setting set to? Perhaps you are still using Blender 3.4 to import .blend files

**Comment by toafloast** [comment]
I've already set the Blender import path to 3.5, the issue is occurring when using .blend files directly.

**Comment by toafloast** [comment]
After upgrading to 4.0.3.stable, I've imported a .blend, and enabled Meshes/Colors. It appears to be working now, so I'll close the issue.
![image](https://github.com/godotengine/godot/assets/104696964/f7610f12-4eb5-42ed-a186-4a7f6530b8ac)
