### ISSUE TITLE
Audio only plays on one viewport

### ISSUE THREAD

**Issue by cody82** [godotengine/godot#76634]
### Godot version

4.0.3-rc1, 4.1-dev1

### System information

Windows 11

### Issue description

In Godot 3 audio used to be played on each viewport, e.g. in a 2D splitscreen scenario, you could hear the sounds from each viewport.
In Godot 4 audio seems to be only played for one viewport. I dont think this is intended?

### Steps to reproduce

1. Create two viewports and cameras, displaying the same 2D scene.
2. Set audio_listener_enable_2d of the cameras to true
3. Add AudioStreamplayer2D to the scene
4. Move the AudioStreamplayer2D and cameras around
5. Notice: You will only hear the audio for one viewport

### Minimal reproduction project

note available

**Comment by Calinou** [comment]
cc @KoBeWi

**Comment by KoBeWi** [comment]
Can't reproduce.

**Comment by Calinou** [comment]
@cody82 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by cody82** [comment]
@Calinou I created an example project:
[splitscreen-audio.zip](https://github.com/godotengine/godot/files/11388622/splitscreen-audio.zip)
There are 4 Viewports with Cameras and one world scene with contains a sprite and an audio player with plays a ~1s beep. The camera of the first viewport moves away from the audio player very fast so it can not hear the whole beep. But the other cameras should hear the full beep! You can also just set the camera position of Viewport1 to (1000,0) and you will hear nothing at all. But all cameras are centered on the audio player. So regardless where Camera1 is positioned, the others should hear the full beep.

So maybe my scene setup is wrong, but it used to work in Godot3.
