### ISSUE TITLE
AnimationTree's AnimationNodeStateMachine resets other transforms before playing an animation that does not affect those transforms

### ISSUE THREAD

**Issue by dashdotdashdot** [godotengine/godot#76638]
### Godot version

4.0.2

### System information

macOS Ventura 13.3.1

### Issue description

When an AnimationTree's AnimationNodeStateMachine transitions to an animation that changes some of a given node's transform fields, all of that node's children's other transforms are reset to their initial positions even though earlier animations separately changed them. Likewise, when it transitions to an animation that changes parameters of a given node's children, that node (the parent) has its transforms reset to their initial state. (Setting a transition's `reset` property to `false` by un-checking its box causes its destination to be skipped entirely.)

Consider the attached minimal reproduction project, which has a central Node3D (shaped like an arrow) under the control of an AnimationPlayer that translates and rotates it animation `travel_up`. The animated Node3D in turn has a Node3D child (the arrow's head) that extends and retracts with animation `retract_child`.

The AnimationPlayer is under the control of an AnimationTree with an AnimationNodeStateMachine root, which defines a loop of auto-advanced animations that switch At End, such that we expect it to:

1. Retract the arrow's head (retract_child played forwards)
2. Translate and rotate the whole arrow upwards and from 0° to 90° around the Y-axis (travel_up played forwards)
3. Extend the arrow's head (retract_child played backwards)
4. Retract the arrow's head (retract_child played forwards)
5. Translate and rotate the whole arrow downwards and from 90° to 0° around the Y-axis (travel_up played backwards)
6. Extend the arrow's head (retract_child played backwards)
7. Repeat _ad infinitum_

Instead, we see the animations proceed like this:

1. Arrow's head retracts per retract_child animation.
2. Arrow's head jumps to extended position, then arrow translates and rotates upwards per travel_up animation.
3. Arrow jumps to lower, un-rotated position and arrow's head jumps to retracted position, then arrow's head extends per retract_child animation played backwards.
4. Arrow's head retracts per retract_child animation.
5. Arrow jumps to higher, rotated position and arrow's head jumps to extended position, then arrow translates and rotates downwards per travel_up animation played backwards.
6. Arrow's head jumps to retracted position, then extends per retract_child animation played backwards.
7. Repeat.

An obvious workaround for this simplified MRP "arrow elevator" would be to merge the retract-travel-extend into one animation and then create separate travel-down and travel-up versions, but what I'm trying to do here is to make something that would extend to larger and more complex machine animations. For example, I might like to extend this AnimationNodeStateMachine to cover travel between 3+ "floors", where travel()ing to a given floor's arrival animation would cause it to retract from its current floor, then travel and extend on the given floor. I kept the MRP to two "floors" to illustrate the issue in isolation; I hope I've explained it well enough to understand.

It is possible that I have badly misunderstood how AnimationPlayer, AnimationTree, and AnimationNodeStateMachine are supposed to work together, but it seems to me that simply playing an animation should not cause other properties not touched by that animation to reset to their initial positions. I'd be delighted to know if what I'm trying to do here would be better served by some other part of AnimationTree.

### Steps to reproduce

1. Open the MRP and load `scene.tscn`.
2. Select the AnimationTree under `Scene/AnimatedObjectWithTree/AnimatedTree`.
3. Toggle the AnimationTree's `active` property to `true`.
4. Observe the behaviour outlined in the issue description: Instead of smoothly retracting, travelling, extending, and then repeating back and forth, `AnimatedObjectWithTree` instead jumps about, discarding the changes made by previous animations.
5. Optional: In the AnimationTree, set some transitions' `reset` properties to `false` by un-checking their boxes. Observe that this causes those transitions' destination animations to be skipped.

### Minimal reproduction project

[AnimationTreeMrp.zip](https://github.com/godotengine/godot/files/11363401/AnimationTreeMrp.zip)

**Comment by dashdotdashdot** [comment]
I've performed some further troubleshooting to rule out the AnimationPlayer itself and to illustrate what the expected result looks like:

1. Removed the AnimationTree from the MRP.
2. Added a simple script to the scene root that does the same thing the AnimationTree's AnimationNodeStateMachine was supposed to do:

```csharp
using Godot;

namespace AnimationTreeMrp;

public partial class Scene : Node3D
{
    [Export] private AnimationPlayer _player;

    public override async void _Ready()
    {
        while (true)
        {
            // Retract lift platform, travel to upper position, and extend platform.
            _player.Play("retract_child");
            await ToSignal(_player, AnimationPlayer.SignalName.AnimationFinished);
            _player.Play("travel_up");
            await ToSignal(_player, AnimationPlayer.SignalName.AnimationFinished);
            _player.PlayBackwards("retract_child");
            await ToSignal(_player, AnimationPlayer.SignalName.AnimationFinished);

            // Retract lift platform, travel back to lower position, and extend platform.
            _player.Play("retract_child");
            await ToSignal(_player, AnimationPlayer.SignalName.AnimationFinished);
            _player.PlayBackwards("travel_up");
            await ToSignal(_player, AnimationPlayer.SignalName.AnimationFinished);
            _player.PlayBackwards("retract_child");
            await ToSignal(_player, AnimationPlayer.SignalName.AnimationFinished);
        }
    }
}
```

3. Run the scene:

https://user-images.githubusercontent.com/132242862/235433779-0a4e5fae-25eb-405d-b388-791caa0c334a.mp4

As you can see, it produces the expected behaviour.

By contrast, here is what happens when the AnimationPlayer is driven by its original AnimationTree with root AnimationNodeStateMachine:

https://user-images.githubusercontent.com/132242862/235434081-9cb84ec0-446b-4ced-aa16-3938e166f90a.mp4

As you can see, it appears to be set up to do the same thing as the little script above:

<img width="1381" alt="76638 MRP AnimationTree State Machine" src="https://user-images.githubusercontent.com/132242862/235434556-d7c688fc-eb40-4c2c-8d20-98704bbce348.png">

I hope I'm just missing something in how I've set up the AnimationNodeStateMachine; I'd much rather use it than have to kludge together a whole animation state machine of my own!

**Comment by Calinou** [comment]
cc @fire @TokageItLab

**Comment by TokageItLab** [comment]
Sometimes the same issue is raised several times, but this is due to a missing Reset animation or Rest, which is already in the document. https://docs.godotengine.org/en/latest/tutorials/animation/animation_tree.html#for-better-blending

**Comment by dashdotdashdot** [comment]
> Sometimes the same issue is raised several times, but this is due to a missing Reset animation or Rest, or each track must be added to all animations, which is already in the document. https://docs.godotengine.org/en/latest/tutorials/animation/animation_tree.html#for-better-blending

Since the section in question concerns animation blending and illustrates it with an AnimationNodeBlendSpace2D, it was not obvious that AnimationNodeStateMachine was subject to the same behaviour. Perhaps it would be good to also make it clear that the AnimationNodeStateMachine is also considered to be "blending" animations, at least within that section's meaning of the word.
