### ISSUE TITLE
Web export: unable to run a simple web project from localhost using serve.py

### ISSUE THREAD

**Issue by diegopau** [godotengine/godot#76631]
### Godot version

4.0.2.stable

### System information

Windows 10, GLES3

### Issue description

Total noob with exporting to run in the web, but I think I am following all the correct steps.
I created a small 3D game, super basic. I exported it with the options I show in the image below, but I tried with other combinations too.

![image](https://user-images.githubusercontent.com/315149/235376967-f60cebaf-348c-429a-aeeb-b71daaeae68b.png)

I use the [serve.py](https://raw.githubusercontent.com/godotengine/godot/master/platform/web/serve.py) script to run the project .
I did had to replace the line:
shell_open(f"http://127.0.0.1:{port}")
for the line
shell_open(f"http://localhost:{port}")
or else it wouldn't even attempt to run anything. With that change it seems to be able to serve the files but it gets stuck with a loader spinner. Using the web browser inspector I get many errors that you can see in the screenshot below.

![image](https://user-images.githubusercontent.com/315149/235376890-5d92844b-8b06-4456-ae7e-3e8bef4ce254.png)

### Steps to reproduce

In a Windows 10 environment, grab the attached zip file, open the project, export it for Web and try to run it from the local machine using the serve.py

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/11362447/test.zip)

**Comment by Calinou** [comment]
It looks like the web server isn't sending the correct MIME types for JavaScript, and browsers don't like that (I didn't know MIME types were even enforced by browsers).

**Comment by diegopau** [comment]
I tried again today. I even added (with the help of ChatGPT) this piece of code to ensure the MIME type was set for JavaScript files:
```
def guess_type(self, path):
    # Add MIME type for JavaScript files.
    if path.endswith(".js"):
        mime_type = "application/javascript"
    else:
        mime_type = super().guess_type(path)
    print(f"Requested file: {path}, MIME type: {mime_type}")
    return mime_type
```
it still wasn't working but ChatGPT suggested to clear all the application cache. It worked after that.
Then I started again with the original serve.py file (just replacing 127.0.01 by localhost) and now it works and I even tried to clear the application cache again and restarting my PC just to make sure all is working with the original serve.py file.

So it seems it was some sort of issue on my end with my web browser cache and I am closing the issue but feel free to open it again if you need more details or tests from me.
Regarding the need of replacing 
shell_open(f"http://127.0.0.1:{port}")
for the line
shell_open(f"http://localhost:{port}")
I think that is just something particular of my Windows setup? else I would recommend to replace it in the official serve.py file, but it might really not be affecting anybody else.

**Comment by gpergrossi** [comment]
I have the same issue now and I am getting frustrated. What kind of cache clearing is necessary?

No matter what I do it just serves them as plain text and fails!
