### ISSUE TITLE
PathFollow2D gets set to 0  when unit_offset is set to 1

### ISSUE THREAD

**Issue by lonesurvivor** [godotengine/godot#7665]
**Operating system or device - Godot version:**
Arch Linux 64 - 2.1.2

**Issue description:**
~~When animating the unit_offset of a PathFollow2D, the follower always jumps back to position 0 when reaching a key with position 1. The value is shown correctly, however. It doesn't seem to happen with other properties that have a range from 0 to 1 (like opacity) so it seems to be a PathFollow2D issue.~~
It actually  always happens when the unit_offset is set to 1, by animation or not.

**Steps to reproduce:**
Make a PAth2D. Make a PathFollow2D as a child. Draw path. 
Make an animation player. Make a key for unit_offset of PathFollow2D. Set it to 0. Make another one, set it to 1. Start the animation and look at the follower.

**Comment by eon-s** [comment]
Setting the offset on the curve's baked length returns to the start too. 
And up to 0.99999 unit works fine, then starts rotating before looping.

**Comment by jtaart** [comment]
Still does this in Godot_v3.0-beta2_win64.exe

**Comment by earlroxas13** [comment]
Also reproduced in Godot 3.1 Alpha 4
I animate using Tween, tweening the PathFollow3D unit_offset from 0 to 1.
Tho it is a PathFollow 3D, should I make a new issue?

**Comment by timoschwarzer** [comment]
The easiest workaround is just setting `loop` to false.
