### ISSUE TITLE
Custom node appears in the node list with the wrong type when it is instanced

### ISSUE THREAD

**Issue by panreyes** [godotengine/godot#76663]
### Godot version

4.0.2

### System information

Windows 10

### Issue description

I created a custom node (a class named CustomNode that extends Sprite2D) and, when I instance a scene containing it, it will appear as a Sprite2D instead of CustomNode in the node list.

### Steps to reproduce

1. Create a class extending Sprite2D.
2. Create a scene with a custom node with this class.
3. Create another scene and add the previous scene into it

The custom node's tooltipo will say the node type is the inherited class (Sprite2D) instead of CustomNode.

### Minimal reproduction project

[TestCustomNodeIssue.zip](https://github.com/godotengine/godot/files/11368445/TestCustomNodeIssue.zip)

**Comment by panreyes** [comment]
@kleonc Yes. Using get_class() also reports the type as Sprite2D instead of CustomNode, when having a custom node or when instancing a scene with the custom node. I am not sure if I am missing something though.

**Comment by kleonc** [comment]
> Using get_class() also reports the type as Sprite2D instead of CustomNode, when having a custom node or when instancing a scene with the custom node. I am not sure if I am missing something though.

This is intended / expected, not a bug. See #21789 or [`Object.get_class`'s docs](https://docs.godotengine.org/en/4.0/classes/class_object.html#class-object-method-get-class).

**Comment by kleonc** [comment]
> I noticed a related bug: If CustomNode has exported properties, they won't be shown on the Inspector tab.

Can't reproduce:

```gdscript
class_name CustomNode
extends Sprite2D

@export var base_prop: float
```
```gdscript
extends CustomNode

@export var prop1: String
@export var prop2: Vector2
```

![Godot_v4 0 2-stable_win64_3gWCH8FB6L](https://user-images.githubusercontent.com/9283098/236224206-d7d3b644-894f-40aa-8e90-b4d29acf9381.png)
![HhhWqA3ODi](https://user-images.githubusercontent.com/9283098/236224217-cc2b12f8-8e5a-4514-be7e-66e938946278.png)
![c6yLawWMrd](https://user-images.githubusercontent.com/9283098/236224225-e2cc8751-27af-4249-89ac-2747e8e75735.png)
