### ISSUE TITLE
Custom Anchors Preset is not saved

### ISSUE THREAD

**Issue by Ark2000** [godotengine/godot#76668]
### Godot version

4.0.2.stable.mono

### System information

Windows 11, Forward+

### Issue description

Custom Anchors Preset will not be saved.

![image](https://user-images.githubusercontent.com/21126555/235602989-9edc2e99-51b6-402c-a368-ecd7d77a0f33.png)

### Steps to reproduce

1. Create an control node scene
2. Change `Anchors Preset` to `Custom`
3. Save and reopen
4. The `Anchors Preset` is not `Custom` but other values.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Does this work if you have an actual parent so the layout works and isn't disabled?

**Comment by AThousandShips** [comment]
This seems to be because it recalculates it based on what you've set up, picking a preset if it matches it

**Comment by AThousandShips** [comment]
It will work if you set non-standard values

**Comment by KoBeWi** [comment]
Yep, the preset itself has no effect, only the anchor values (which are tied to preset, but custom allows you to specify them manually).
