### ISSUE TITLE
Batch Rename lets you rename to invalid name without error or warnings

### ISSUE THREAD

**Issue by ajreckof** [godotengine/godot#76679]
### Godot version

4.1.dev (1becfea37c)

### System information

MacOS 13.3 M1 Pro

### Issue description

When you use batch rename you can ask him to rename to invalid node names. it won't raise any warning nor error it will just rename to a valid node names without informing you of the change. For comparison with simple renames this is shown as warning
<img width="452" alt="Capture d’écran 2023-05-02 à 21 49 47" src="https://user-images.githubusercontent.com/66184050/235771076-a2f09307-6c8d-4687-8d31-58234e8e2bf1.png">

### Steps to reproduce

1. create a root Node and two Node children
2. select the two children
3. Batch rename the `e` to `%`
4. See that childrens have been renamed to `Nod_` and `Nod_2` without warning 

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
We have a pretty standard way to validate and inform about errors. Create New Scene dialog for example:
![image](https://user-images.githubusercontent.com/2223172/235779087-7db4a899-dd41-40c7-8cb3-b295a42eec5e.png)
Something like this could be implemented for the batch rename dialog.
