### ISSUE TITLE
Sun Energy is int instead of float .

### ISSUE THREAD

**Issue by HotHead007** [godotengine/godot#76677]
### Godot version

4.0.3

### System information

windows 10 amdA6 integrated graphics

### Issue description

The sun energy value displayed in the Preview Sun window is shown as an integer instead of a float value. This makes it difficult to adjust the sun energy efficiency precisely.
Currently, when i attempt to adjust the sun energy i are only able to do so in whole numbers. This is not ideal, as we often need to make more precise adjustments to get the desired lighting effect.
![ScreenCapture20230428_233022_881](https://user-images.githubusercontent.com/132071423/235744769-70e85c4c-f476-46ce-8f10-6de960fb1e29.png)
I would like to look into it if you also thinks its minor bug and can be a good first contribution.

### Steps to reproduce

go to the panel in the image.

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
Go ahead! This seems like a good first issue, so if you want to investigate and open a PR, please do!

**Comment by clayjohn** [comment]
Fixed by https://github.com/godotengine/godot/pull/76722
