### ISSUE TITLE
Save Branch as Scene on edited scene causes a crash

### ISSUE THREAD

**Issue by thefryscorer** [godotengine/godot#7667]
Operating system or device - Godot version: Linux - v2.1.1.stable.official (also tested with most recent Github version)

Creating a new unsaved scene, adding a Node (tested with Node2D) and attempting to save the scene using "Save Branch as Scene" results in an editor crash with error:

ERROR: set_owner: Condition ' !owner_valid ' is true.
   At: scene/main/node.cpp:1115.

(scene/main/node.cpp:1855 in Github build)

I'm not sure what the desired behaviour for this case would be, or if the user should see an error message informing them of the correct way to save the scene, as currently it is not very beginner friendly. As shown by this Reddit thread where somebody was running into this issue: https://www.reddit.com/r/godot/comments/5qq0j8/help_godot_crashes_when_saving_new_scene/

**Comment by volzhs** [comment]
saving root node by "Save Branch as Scene"?

**Comment by thefryscorer** [comment]
Yeah. I'm not sure if that should be an error condition or not, but it shouldn't crash at least. I hadn't run into it myself, but I don't think it's unreasonable for a beginner to think that might be how to save the scene.

**Comment by volzhs** [comment]
right. I will check it.
