### ISSUE TITLE
SubViewport scaling does not work

### ISSUE THREAD

**Issue by Kapusta-dev** [godotengine/godot#76687]
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Windows 10

### Issue description

SubViewport does not scale according to project scaling settings, window size, and size parameters like it did in Godot 3.5.

### Steps to reproduce

To reproduce, open the 'viewport\3d_scaling' official example project in each version.

In 4.0 -> Nothing happens when hitting spacebar to change the scale factor. The image remains the same.
In 3.5 -> Image resolution appropriately changes and scales when hitting spacebar.

### Minimal reproduction project

This is exact  'viewport\3d_scaling' official example project with no changes made.
[3d_scaling.zip](https://github.com/godotengine/godot/files/11378760/3d_scaling.zip)

**Comment by Calinou** [comment]
This is an issue with the demo being outdated: https://github.com/godotengine/godot-demo-projects/pull/891
