### ISSUE TITLE
Rotation of nodes being instanced

### ISSUE THREAD

**Issue by Tabascus** [godotengine/godot#76682]
### Godot version

4.0.2

### System information

macOS 13.3.1, Radeon Pro 5500M, Vulkan

### Issue description

(I'm new here please be nice)

I'm in the middle of a course over on GameDev.TV in particular a lesson where I need to shoot a rocket from the ship. The asset is positioned correctly in the folder as is the Transform settings for the scene and asset in the scene, however when shooting the rocket it points downwards instead. 

<img width="752" alt="Screenshot 2023-05-03 at 6 05 30 am" src="https://user-images.githubusercontent.com/113387955/235783455-db835371-2249-44ad-9644-5eeb92c83ec9.png">

The node is set to 0 degrees rotation as shown here: 
<img width="272" alt="Screenshot 2023-05-03 at 6 24 19 am" src="https://user-images.githubusercontent.com/113387955/235783837-7de9ad34-9dde-4151-9e4f-28c017c6e08b.png">

I have found the fix for this which was to add in `rotation_degrees = 270` to the rocket.gd at the bottom. So I'm not sure if it's a bug or not, but definitely not what the instructor experienced in the video. 

### Steps to reproduce

For player.gd I was advised to add the following: 

`func shoot(): 
	var rocket_scene = load("res://Scenes/rocket.tscn")
	var rocket_instance = rocket_scene.instantiate()
	add_child(rocket_instance)
	`

And the code I have for the rocket.gd:

`extends` Area2D

@export var speed = 300

func _physics_process(delta):
	global_position.x += speed * delta
`

### Minimal reproduction project

[GameDev.TV Alien Attack.zip](https://github.com/godotengine/godot/files/11377712/GameDev.TV.Alien.Attack.zip)

**Comment by Calinou** [comment]
If your rockets are children of the ship, they will move and rotate along with the ship. Instance the rockets in the parent node of the ship instead (`get_parent().add_child()`) to avoid this, or call `set_as_top_level(true)` on the rockets just before instancing them.

**Comment by Tabascus** [comment]
Thank you, I’ll try that out! :)

**Comment by AThousandShips** [comment]
See [here](https://docs.godotengine.org/en/stable/tutorials/scripting/instancing_with_signals.html)

**Comment by Tabascus** [comment]
Thank you kindly! And again apologies for posting this as a bug report. On 3 May 2023, at 7:45 am, A Thousand Ships ***@***.***> wrote:﻿
See here
