### ISSUE TITLE
Create Plugin dialog's validation should be changed for consistency

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#76681]
### Godot version

4.0

### System information

Windows 10 x64

### Issue description

We have an established way to inform about invalid input fields: using red/green/yellow labels at the bottom:
![](https://user-images.githubusercontent.com/2223172/235779087-7db4a899-dd41-40c7-8cb3-b295a42eec5e.png)
It's used in Create New Scene dialog, Add Metadata dialog, New Folder dialog, Create Script dialog and probably others.

Meantime the New Plugin dialog (accessible in Project Settings -> Plugins) looks like this:
![image](https://user-images.githubusercontent.com/2223172/235783588-ef5e560c-8620-4017-9b50-86f8477fe40e.png)
Instead of info labels, it uses info icons that show message on hover. This dialog was created before we had an established way of validating input, so it needs updating.

### Steps to reproduce

1. Project
2. Project Settings
3. Plugins
4. Create New Plugin
5. 👀

### Minimal reproduction project

N/A

**Comment by brno32** [comment]
I'd be happy to take a look at this one

**Comment by eugene87222** [comment]
Hi @brno32, would you mind letting me fix this issue😄?

**Comment by brno32** [comment]
I do not mind! Your code looks similar to mine :)

Do we use the assignee feature here? I had already started working on it, so an official assignee might have saved the duplicated effort.

**Comment by eugene87222** [comment]
Thanks! I think assignee is not required here.
