### ISSUE TITLE
Renaming node with Batch Rename with invalid character will lead to bad `NodePath` update

### ISSUE THREAD

**Issue by ajreckof** [godotengine/godot#76680]
### Godot version

4.1.dev (1becfea37c)

### System information

MacOS 13.3 M1 Pro

### Issue description

When renaming with Batch Rename using invalid character `NodePath` will be updated with the invalid new name.

### Steps to reproduce

1.  open MRP
2. batch rename all nodes except the root from `e` to `%`
3. look at the `NodePath` on the root

### Minimal reproduction project

[test1.zip](https://github.com/godotengine/godot/files/11377324/test1.zip)

**Comment by nongvantinh** [comment]
I have made an update to #76575 to address this bug. Please test it out.
