### ISSUE TITLE
[4.0.2][bug] In-editor drop-down box and right-click menu stuttering

### ISSUE THREAD

**Issue by quijoo** [godotengine/godot#76694]
### Godot version

4.0.2

### System information

Windows11, Forward+, R5 5600x, RTX2060 (GeForce Game Ready 531.79)

### Issue description

“The editor starts normally, but after about 5 minutes, there is a 1-3 second lag when calling up the **dropdown box** and the **right-click menu**. ”

https://user-images.githubusercontent.com/41560937/235884888-ca8721f9-f985-4ed0-ab94-79bd0f1395e9.mp4

### Steps to reproduce

No minimal reproduction project is needed, this situation will occur with any empty project.

### Minimal reproduction project

[text_bug.zip](https://github.com/godotengine/godot/files/11381324/text_bug.zip)

**Comment by Calinou** [comment]
Do you have third-party programs such as shell extensions? This may cause window spawning to be severely delayed. (In Godot 4, dropdowns are separate windows so that they can extend outside the editor window.)

As a workaround, enable **Single Window Mode** in the Editor Settings.

**Comment by quijoo** [comment]
Thank you very much for your prompt, but this issue is no longer present in the latest version.

**Comment by akien-mga** [comment]
Closing then.

**Comment by AThousandShips** [comment]
To clarify, by "latest version" do you mean 4.0.3 or 4.1.beta?

**Comment by quijoo** [comment]
4.1 beta

**Comment by AThousandShips** [comment]
Have you checked in 4.0.3? Because bugs can remain on 4.0.3 while being solved in 4.1 beta

**Comment by quijoo** [comment]
I only check on v4.1.

**Comment by AThousandShips** [comment]
Then maybe this should be reopened until we can verify it's not occurring on 4.0.3

**Comment by quijoo** [comment]
I will test on v4.03 latter.

**Comment by AThousandShips** [comment]
Thank you!

**Comment by quijoo** [comment]
After testing, neither 4.02 nor 4.03 reproduces the issue at that time. In addition, both the graphics driver and the win11 version of the PC have changed during this period.
