### ISSUE TITLE
Local to Scene SubResource Ids change after saving

### ISSUE THREAD

**Issue by ChristopherWalde** [godotengine/godot#76693]
### Godot version

4.0.2 & 4.0.3 RC1

### System information

Windows 10, Vulkan API 1.3.224, NVIDIA RTX A2000 Laptop GPU

### Issue description

When saving a scene containing another recently saved instatiated scene with one or more resources being local to scene, Godot changes the affected Resource ID. This only happens if the Node containing the resource being local to scene is the root.
This Occurance is espacially problematic when working in a team with any source control solution.

### Steps to reproduce

- Create a new scene containing a MeshInstance3D node and make it the scene root.
- Assign a mesh and set the property resource_local_to_scene to true
- Create a second scene and instantiate the scene containing the MeshInstance3D node
- Without needing to change either scenes, save the MeshInstance3D scene (or any other instantiated child scene) first, then the scene where the MeshInstance3D scene is initiated

### Minimal reproduction project

[IdChange.zip](https://github.com/godotengine/godot/files/11380909/IdChange.zip)
In this example saving either child scene before the main scene will cause the error, but only the IDs of the Node labeled "ChanginIDs" will change.

**Comment by AThousandShips** [comment]
To clarify this happens every time the scene is saved? Not just the first time?

**Comment by AThousandShips** [comment]
Also what "resource Id" are you talking about here, the id tag in the .tscn file?

**Comment by ChristopherWalde** [comment]
> To clarify this happens every time the scene is saved? Not just the first time?

Exactly, you can reproduce the id change infinite times with the same scenes.

> Also what "resource Id" are you talking about here, the id tag in the .tscn file?

Speaking about the example above, the id of the BoxMesh changes in the level.tscn where the MeshInstance3D is instantiated.
In this case line 5 and 12 "gc1du":

![carbon](https://user-images.githubusercontent.com/91892423/235901700-b8214fe7-4016-498d-a51c-69f1ef8796c6.png)

**Comment by AThousandShips** [comment]
Indeed

To note: this *only* happens if you have a mesh assigned to the scene *and* to the instancing scene, that seems like a likely cause of this, I'm not quite sure how useful it is to have a mesh in the original scene and then override it

**Comment by AThousandShips** [comment]
Indeed, it only happens when the mesh in question is in the root of the other scene, so must be something related to that

**Comment by AThousandShips** [comment]
It is probably because it fetches the local ID from the other scene, and then finds it does not exist in the current scene and therefore has to regenerate it

**Comment by AThousandShips** [comment]
It appears to be happening here, but will investigate a bit further:
https://github.com/godotengine/godot/blob/2a0aef5f0912b60f85c9e150cc0bfbeab7de6e40/scene/resources/packed_scene.cpp#L305-L339

**Comment by ChristopherWalde** [comment]
First of all, thank you for looking into the problem.

What you are saying is very good to know, but isnt't the usecase of the property local_to_scene exactly this scenario? For instance I could have a scene where a Mesh follows a Path, like traintracks for example. If I want to create a level consisting of multiple tracks with different Curve resources, that do have a standard size, I would assign a default curve resource and set it to local to scene. Therefore I can change each track without manipulating every other track.

This at least sounds like the right way to aproach this, but I could very well be mistaken and the best practice is to assign the resource after instantiating a scene.

**Comment by AThousandShips** [comment]
My bad I was confused in my first comment and that's why I deleted it, this particular behavior should not be breaking and will see if there's some bug here that can be resolved

**Comment by ChristopherWalde** [comment]
No worries, thanks for looking into it.

**Comment by rakkarage** [comment]
in recent custom 4.1 builds it is regening every id on every save even if just one simple file

	[gd_scene load_steps=2 format=3 uid="uid://bj3w1run711x7"]

	[ext_resource type="Texture2D" uid="uid://c082xolc76p8n" path="res://icon.svg" id="1_ftki2"]

	[node name="Node2D" type="Node2D"]

	[node name="Sprite2D" type="Sprite2D" parent="."]
	position = Vector2(351, 294)
	texture = ExtResource("1_ftki2")

can use a script like this save all files and regen all ids in project

	@tool
	extends EditorScript

	func listFiles(path: String, extensions: Array = []) -> Array:
		var list := []
		for dir in DirAccess.get_directories_at(path):
			if not dir.begins_with("."):
				list.append_array(listFiles(path + dir + "/", extensions))
		for file in DirAccess.get_files_at(path):
			var ext = file.split(".")[-1]
			if not file.begins_with(".") and ext != "import":
				if not extensions.is_empty() and ext not in extensions:
					continue
				list.append(path + file)
		return list

	func _run() -> void:
		for file in listFiles("res://", ["tscn", "tres"]):
			ResourceSaver.save(load(file))

in 4.0.2 this script does not regen every id in the project each time it is run but in latest 4.1 it does?

thanks

**Comment by AThousandShips** [comment]
Note that while this is also an issue this is a separate problem and should probably be tracked separately as it likely has a separate fix

**Comment by Rindbee** [comment]
For SubResource, the resource of `local_to_scene` uses a copy when the scene is instantiated, and the copy generated a new id during pack. That's why the id keeps changing.
