### ISSUE TITLE
Consistent crash when clicking "Show Desktop" button

### ISSUE THREAD

**Issue by TheHyper-Dev** [godotengine/godot#76709]
### Godot version

4.0.3

### System information

windows 10, ryzen 5 5600x rx 590, m2 ssd

### Issue description

The title, it crashes even if godot isn't the focused window at the time

### Steps to reproduce

.

### Minimal reproduction project

![image_2023-05-03_230214059](https://user-images.githubusercontent.com/32967925/236035075-b86e1101-30af-4a92-81ff-bfa602ddc532.png)
Click on this

**Comment by Calinou** [comment]
>  Click on this

Does it crash when you press <kbd>Windows + D</kbd> (which is the keyboard shortcut for Show Desktop)?

**Comment by Lazy-Rabbit-2001** [comment]
> > Click on this
> 
> Does it crash when you press Windows + D (which is the keyboard shortcut for Show Desktop)?
> 
> Can you reproduce this on an empty project? Also, try enabling **Single Window Mode** in the Editor Settings, then restart the editor.

I opened it, but it kept crashing

**Comment by Calinou** [comment]
> I opened it, but it kept crashing

What did you open? I don't understand what you mean given the quote.

**Comment by d-bucur** [comment]
Confirming that this happens to me as well.

Godot version: 4.0.3
System information: Windows 11, GPU: Intel Iris Xe (Integrated i7 11th Gen)

Anytime I press Win+D (default to show desktop) and the Godot window gets minimized it will crash (even if it was not the window with active focus at the time). Will not crash if it was already minimized when the shortcut was pressed. This is reproducible with an empty project and happens with both **Single Window Mode** on and off.

**Comment by HerrSersch** [comment]
It's still happening in 4.2.2, but I can no longer reproduce it in 4.3-beta1 with the tests I've done so far.

I'm on Windows 10, Nvidia RTX 2060 Super, latest drivers. Intel i5 3550.

I couldn't crash an empty project like @d-bucur managed to do, but I've attached an MRP that crashes consistently every time for me:

[show_desktop_crash_mrp.zip](https://github.com/user-attachments/files/15836007/show_desktop_crash_mrp.zip)

I've noticed the following patterns:

- The renderer has to be set to Forward+ or Mobile. It doesn't happen with Compatibility
- The problematic scene that causes the crash has to be open, but not necessarily as the active scene. It can be in another tab
- you need to have at least the following three nodes: AnimationPlayer, AnimationTree and any Node3D derived node **except** for Node3D itself
- the Node3D derived node needs to have at least one animation with at least one keyframed property in the AnimationPlayer. The property has to be one of the transform (position, rotation, scale) properties
- The AnimationTree has to be linked to the AnimationPlayer
- The AnimationTree has to use a TreeRoot. Doesn't matter which one, but the property can't be empty

As soon as any of these conditions aren't met, my MRP stops crashing when I press Windows+D or use the Show Desktop button in the lower right. I wish I could narrow it down some more, but this is as far as I could get.

I think it's interesting that the renderer setting affects this problem and the entire setup above works as soon as the renderer is set to Compatibility. This makes me think that the problem it not really related to any of the nodes but rather to the renderer.

**Comment by akien-mga** [comment]
Closing as fixed in 4.3.
