### ISSUE TITLE
Godot always throws Poco::NotFoundException

### ISSUE THREAD

**Issue by anvilfolk** [godotengine/godot#76707]
### Godot version

4.0 master

### System information

Windows 11, VS2022, NVidia 3060m

### Issue description

This has happened for weeks/months. When running godot in debug mode (haven't tested other modes) through VS2022, the following errors show up:
```
Exception thrown at 0x00007FF928CEFDEC in godot.windows.editor.dev.x86_64.exe: Microsoft C++ exception: Poco::NotFoundException at memory location 0x00000065589E9930.
Exception thrown at 0x00007FF928CEFDEC in godot.windows.editor.dev.x86_64.exe: Microsoft C++ exception: Poco::NotFoundException at memory location 0x00000065589E9970.
```

I get 5 of these at different times during loadup, e.g.

![image](https://user-images.githubusercontent.com/1133892/236010058-1e167ef9-a124-46ba-8b16-c976ca954fb8.png)

![image](https://user-images.githubusercontent.com/1133892/236012420-28e71cfa-b2fc-4bda-a278-66dc2f64396d.png)

![image](https://user-images.githubusercontent.com/1133892/236012460-4b8ddec6-492a-4062-a307-496c2832cd11.png)

It appears a lot of these messages show up near `MessageBus.dll` messages related to GPU drivers?

A search turned up this information: https://forums.developer.nvidia.com/t/poco-notfoundexception-thrown-in-driver-version-531-18/245285

So perhaps it is not related to Godot at all, but is instead Visual Studio + NVidia driver specific?

### Steps to reproduce

Run Godot in with `dev_build` and `dev_mode` through VS2022 in debug mode. I am not certain whether this happens in other run configurations.

### Minimal reproduction project

N/A

**Comment by anvilfolk** [comment]
Added a few more images with more detail: It appears a lot of these messages show up near `MessageBus.dll` messages related to gpu drivers?

**Comment by AThousandShips** [comment]
Looks like there's something broken in the drivers, Godot doesn't use the Poco library, not sure if VS uses it though

**Comment by AThousandShips** [comment]
Could be related: https://forums.developer.nvidia.com/t/poco-notfoundexception-thrown-in-driver-version-531-18/245285

**Comment by anvilfolk** [comment]
Thank you for looking into it, I just left a post in that thread. Maybe that'll push them to look into it a bit more. I think it's safe to say it's not Godot-related then, so I believe the best option is to close this issue?

**Comment by AThousandShips** [comment]
I would say so, as it doesn't really touch the codebase directly
