### ISSUE TITLE
Godot's class reference is not sorted naturally (i.e. a8 appears after a16)

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#76718]
### Godot version

4.0.2

### System information

Ubuntu 22.04.1 LTS

### Issue description

I was reading the class reference of FileAccess and noticed some jank. `get_8()` was positioned after `get_16()`, `get_32()`, and `get_64()`. This shouldn't be the case, as I would expect natural sorting to be used for the strings (`naturalnocasecmp_to`).

### Steps to reproduce

Look at the class reference of FileAccess.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
They are sorted the way strings are compared, i.e. by unicode order, this is the default way to compare strings and what should be assumed

**Comment by AThousandShips** [comment]
Would require changing compare methods of `MethodInfo` to use this

**Comment by AThousandShips** [comment]
Will take a stab at doing this for documentation only to start with (which doesn't break compat)

**Comment by AThousandShips** [comment]
It will make relatively major changes in the documentation to implement this as it swaps some orders

It now sorts `_` *after* any letters or digits, which might be good or bad, for example currently, in `Time`:
`get_date_*` before `get_datetime_*`
Now they come later

**Comment by AThousandShips** [comment]
And yes I've confirmed that there is a bug in `naturalnocasecmp_to` will investigate that first

**Comment by AThousandShips** [comment]
It also affects `nocasecmp_to`:
`test_ac` and `test_a_c` yield `1` and `-1` respectively for `casecmp_to` and `nocasecmp_to`

*But* `TEST_AC` and `TEST_A_C` both give `-1`

Will open a separate report

**Comment by AThousandShips** [comment]
Not sure if there are any bugs necessarily but there are some complications in the comparisons regarding underscore and some other special characters that occur *between* the lower and upper case characters, which causes this issue

**Comment by AThousandShips** [comment]
As a comparison on GitHub "hash_map" comes before "hashfuncs"

**Comment by AThousandShips** [comment]
My suggestion would be to maybe add a check for the range of letters that cause a problem, but I'm unsure, it only affects a small range of letters, namely any of `[]\\^_\``, for every other character the comparison between a letter and some symbol is unchanged

This would make the functions *not* behave as if you took the uppercase of the string, which might be expected, but people might also expect it to treat it as if they were the lowercase form

**Comment by AThousandShips** [comment]
PR is up
