### ISSUE TITLE
Exported PackedScene in C# script is not visible in the inspector

### ISSUE THREAD

**Issue by Woolton** [godotengine/godot#76710]
### Godot version

v4.0.2.stable.mono.official [7a0977ce2]

### System information

Windows 11

### Issue description

Exported PackedScene variables do not appear in the editor. I've attempted restarting the whole editor, closing my code editor, closing and reopening all scenes, but `PackedScene`s do not appear in the editor.
 ```public partial class Gun : Node2D
{

		[Export]
		public PackedScene _Bullet;
```

https://i.imgur.com/gLiIADL.png

### Steps to reproduce

-Export a packedscene variable
-packedscene variable does not appear

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
I can't reproduce this in GDScript in 4.1.dev d6dde819b (Linux), both with and without a leading underscore.

```gdscript
@export var bullet: PackedScene
@export var _underscore_bullet: PackedScene

**Comment by MisoMosiSpy** [comment]
Can't reproduce on v4.1.dev.mono.custom_build [8c729f0f3] on windows. 

```
	[Export]
   	public PackedScene FirstBullet;
	
	[Export]	
	public PackedScene SecondBullet;
	
	[Export]	
	public PackedScene _ThiredBullet;
	
	[Export]	
	public PackedScene fourth_bullet;
	
	[Export]	
	public PackedScene _fifth_bullet;
```

![image](https://user-images.githubusercontent.com/52410428/236146082-37dafa78-060f-4fc5-9b12-eec09d55ea93.png)

@Woolton, Hope you did "Build Solution" after updating the source files, that is needed for C# scripts.

**Comment by Woolton** [comment]
> Can't reproduce on v4.1.dev.mono.custom_build [[8c729f0]

This appears to be a more recent build of Godot 4, would you recommend using this over the stable version? I can only consistently get Export variables to work by closing the editor after building.
