### ISSUE TITLE
GDScript autocomplete suggests nonexistent `DisplayServerMacOS` type

### ISSUE THREAD

**Issue by admoore0** [godotengine/godot#76717]
### Godot version

4.0.2.stable

### System information

macOS 12.6.3

### Issue description

`DisplayServerMacOS` seems to be a suggested type, but when I command-click for documentation, it brings up a blank page. I also can't find a reference to this on the online stable docs. Was this a removed type that got overlooked?

I asked some collaborators on Windows if they see this as well, and it seem like this option isn't suggested for them.

<img width="230" alt="image" src="https://user-images.githubusercontent.com/22134557/236076348-72490a2e-a1aa-4e5e-9a19-4c089e98dc6e.png">

### Steps to reproduce

1. Open up a GDScript file on a macOS build of the IDE
2. Start typing "Display"

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
DisplayServerMacOS is an internal class which matches your current OS, and is therefore compiled in the final binary.
