### ISSUE TITLE
Wrong behaviour of Volumetric fog

### ISSUE THREAD

**Issue by alekseym88** [godotengine/godot#76721]
### Godot version

4.0.2.stable, but also tested on 4.0.3, 4.1.dev 1 and on head 4.1 [8c729f0]

### System information

MacOS Monterey 12.0.1, Intel Iris Graphics 550 1536 MB

### Issue description

Whole scene is covered by Volumetric Fog, instead be rendered only inside a FogVolume node

<img width="1426" alt="Screenshot 2023-05-04 at 10 40 46" src="https://user-images.githubusercontent.com/4573901/236099311-f59a44d4-5466-42a7-8eb8-0eb1788d8c6d.png">

### Steps to reproduce

Just add to scene nodes FogVolume and WorldEnvironment

### Minimal reproduction project

[volume fog bug.zip](https://github.com/godotengine/godot/files/11392515/volume.fog.bug.zip)

**Comment by clayjohn** [comment]
Could you provide a bit more information about what you expect to happen and what is happening? From your description it is unclear what the buggy behaviour is.

**Comment by alekseym88** [comment]
@clayjohn I expect when you add FogVolume node, the global volumetric fog should be disappeared and only remain inside FogVolume? or it should still remain as well? Bc now on scene it has global volumetric fog and local volumetric fog inside FogVolume.

As here below, if you will increase the distance to scene, all objects will be faded by fog:

<img width="872" alt="Screenshot 2023-05-04 at 10 57 36" src="https://user-images.githubusercontent.com/4573901/236103237-3ac8a35f-a4f1-47b4-a5d5-7b4a75304320.png">

<img width="879" alt="Screenshot 2023-05-04 at 10 57 43" src="https://user-images.githubusercontent.com/4573901/236103299-ec592acd-8cb6-4f10-979a-f643d5a9e896.png">

**Comment by clayjohn** [comment]
In the MRP you have the global fog density set to 0.05. So you should expect there to be some fog globally as well as local fog where you have the FogVolume. If you only want fog to appear in the FogVolume you can set the global density to 0.0.

The docs are very helpful and also explain how global fog works: https://docs.godotengine.org/en/latest/tutorials/3d/volumetric_fog.html#volumetric-fog-properties

**Comment by alekseym88** [comment]
Oh, Thanks for it.  My bad, I didn't check it carefully 🙈

**Comment by clayjohn** [comment]
No problem! Good luck on your project!

**Comment by alekseym88** [comment]
@clayjohn one more question :) 

For spot and omni light, if shadow cast is enable, it will not interact correct with volume fog, is it a bug? or i'm doing something wrong?


<img width="1148" alt="Screenshot 2023-05-04 at 11 59 26" src="https://user-images.githubusercontent.com/4573901/236110432-d46aae7a-142e-40e0-8854-dea6343f1c0c.png">
<img width="1148" alt="Screenshot 2023-05-04 at 11 59 35" src="https://user-images.githubusercontent.com/4573901/236110443-fde34e68-49d5-4087-9ce1-409d68e0b336.png">

**Comment by clayjohn** [comment]
If there is nothing occluding the light then it should look the same before and after shadows are turned on.

**Comment by Calinou** [comment]
Volumetric fog + SpotLights with shadows enabled was broken before release, but it should be fixed now as per https://github.com/godotengine/godot/pull/73919. That said, it's possible that the issue came back in some fashion or that MoltenVK has specific bugs (due to the volumetric fog implementation being slightly different).

**Comment by alekseym88** [comment]
@clayjohn on screenshots, scene is same, just difference is: shadow on / off for spot light --  without shadow on, fog shading is correct, but with shadow it's stop working?

**Comment by alekseym88** [comment]
@Calinou just checked on last [8c729f0](https://github.com/godotengine/godot/commit/8c729f0f34a92b92a1a8204e1d56b6ad05cfd27b) commit version, still has this problem, so for this case what need to do?

**Comment by Calinou** [comment]
> @Calinou just checked on last [8c729f0](https://github.com/godotengine/godot/commit/8c729f0f34a92b92a1a8204e1d56b6ad05cfd27b) commit version, still has this problem, so for this case what need to do?

Please upload a minimal reproduction project with your SpotLight setup.

**Comment by alekseym88** [comment]
@Calinou Ok, I will do it! One more thing about fog:

I was trying to search but didn't find that people mention it before, for volumetric fog has some distance for display? as it become only partly rendered at some distance: 

<img width="1427" alt="Screenshot 2023-05-04 at 14 24 42" src="https://user-images.githubusercontent.com/4573901/236126496-19e10e19-6c08-4df7-8a43-3c35169da926.png">

**Comment by Calinou** [comment]
> I was trying to search but didn't find that people mention it before, for volumetric fog has some distance for display? as it become only partly rendered at some distance:

Yes, as described in the [Volumetric fog and fog volumes](https://docs.godotengine.org/en/stable/tutorials/3d/volumetric_fog.html) documentation.

**Comment by alekseym88** [comment]
Thanks :)
