### ISSUE TITLE
Xbox bluetooth controller detected as 2 devices, triggering 2 events instead of 1

### ISSUE THREAD

**Issue by lentsius-bark** [godotengine/godot#76724]
### Godot version

3.5.2 stable, 3.6 beta 1

### System information

Windows 11, all amd system, GLES3

### Issue description

Printed output says that the controller is in fact two controllers:
```
XInput Gamepad
Bluetooth LE XINPUT compatible input device
```
controllers of other makes only report as a single device (tested with nintendo pro controller, dual sense, steam deck)

Tested controllers:
- xbox elite controller
- xbox one s
- ~~haven't tested with xbox series controller, will report back when i have~~ Xbox series *(pink)* works fine

Effect:
- on a fresh new project it seems that the issue is only that the gamepad is reported as two
- in a project we are working on in godot 3.5.2, the double sent events propagate into the game (skips a button when going up for instance)

I am aware of https://github.com/godotengine/godot/issues/41684 and https://github.com/godotengine/godot/pull/71784 which mentions that a fix had been cherry picked, in my testing however the issue remains.

### Steps to reproduce

- create a simple ui scene with a couple of buttons
- add a script that prints the device name using: `print(Input.get_joy_name(event.device))` when event is InputEventJoypadButton in the _input function
- run the game and press a button on a bluetooth connected xbox gamepad

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
CC @PrecisionRender

**Comment by PrecisionRender** [comment]
I guess what's likely happening is that these controllers have a different GUID than the Series controller.

**Comment by PrecisionRender** [comment]
Please test this issue with the Xbox Series controller. If that also registers as 2 devices, the issue will likely be unrelated to the GUIDs.

**Comment by lmurray** [comment]
Godot's `JoypadWindows::is_xinput_device()` is historically derived from SDL's `SDL_IsXInputDevice()`. Looking at SDL I see that they chose a different approach for excluding Xbox One and later controllers instead of relying on a block list that needs to be constantly updated: https://github.com/libsdl-org/SDL/pull/4920

**Comment by PrecisionRender** [comment]
@lmurray That solution appears much more elegant.

**Comment by lentsius-bark** [comment]
@PrecisionRender just tested with a series controller and yes, it works as expected, not sending double events indeed!
If the solution above checks for all of the xbox controllers that'd be a massive win, however if need be i can test / provide GUIDs of the other xbox controllers.

**Comment by lorenzokerbrat** [comment]
This issue is still present with Godot 4.4 stable.
