### ISSUE TITLE
Editor menu mouse clicks don't register unless Single Window Mode is enabled (DisplayServer regression)

### ISSUE THREAD

**Issue by someThrowAway1900** [godotengine/godot#76726]
### Godot version

4.0.3 rc1

### System information

Windows10

### Issue description

UPDATE - windowsKey + arrowKey does not seem to be the cause. Issue is happening regardless.

Editor menu mouse clicks do not always work. ~~It seems to only happen if I snap the godot application with windowsKey + arrowKey (keyboard keys capture in lower left of video). Seems rather weird if this is the case, but I can repeat the issue consistently.~~

Note:
- this was happening randomly in 4 beta, final, etc but I could never get it to occur consistently
- this bug does not happen in 3.5.2 stable

Please see video for steps.

https://user-images.githubusercontent.com/132544925/236126715-60843be2-7a65-411f-9952-c5139aeabba8.mp4

### Steps to reproduce

- create a new project
- follow steps in attached video

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Can you reproduce this after enabling **Single Window Mode** then restarting the editor?

**Comment by someThrowAway1900** [comment]
Turning on Single Window Mode seems to work. When I turned it back off, the issue happened again.

hmm. I played around with it a bit more, and it's happening now even when I don't snap the application with windowsKey+arrowKey. I will update the issue as that's doesn't seem to be the issue.

**Comment by KoBeWi** [comment]
Sounds related to #61758

**Comment by someThrowAway1900** [comment]
Closing issue and will update https://github.com/godotengine/godot/issues/61758 as related
