### ISSUE TITLE
Clicking on an object in editor selects the thing behind it.

### ISSUE THREAD

**Issue by emplhoward** [godotengine/godot#76738]
### Godot version

Godot 4.0 RC6 Mono Win64

### System information

Windows 10

### Issue description

When I click on something in the editor, it selects the thing behind it instead. This doesn't always happen.

### Steps to reproduce

This occurs intermittently and cannot be produced consistently.

### Minimal reproduction project
This occurs randomly. I click on New Script but it keeps choosing the Output Window behind it.
![ClickingSelectTheThingBehind](https://user-images.githubusercontent.com/47064706/236347903-dbba2c63-74bc-476d-a518-ba7eeec9d9d1.jpg)

**Comment by KoBeWi** [comment]
Duplicate of #61758
