### ISSUE TITLE
Can't export game, because of too big window

### ISSUE THREAD

**Issue by artur321233** [godotengine/godot#76731]
### Godot version

v4.0.2 stable.official

### System information

Android 13, Samsung M13

### Issue description

When I click on "Export", window appears, but it's too big, and I Zcan't click "Export as..." button.

### Steps to reproduce

.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
- Duplicate of https://github.com/godotengine/godot/issues/73130.
