### ISSUE TITLE
Cannot build in headless mode if device never openned the project before

### ISSUE THREAD

**Issue by AdrKacz** [godotengine/godot#76746]
### Godot version

4.0.2

### System information

MacOS

### Issue description

Hello,

I have same issue as mentioned in https://github.com/godotengine/godot/issues/73782 despite using the command `Godot_v4.0-rc3_linux.x86_64 --headless --export-debug "Linux/X11" build/linux/godot-template-4.x86_64`.

Trying to setup CICD so the device running the command never saw the project before.
I got a bunch of 
```
Make sure resources have been imported by opening the project in the editor at least once.
```

How would you do to have CI/CD to build your project if that is not the way to go? (the project builds fine on my computer)

### Steps to reproduce

Here are the exact command I am running:
```
# Set up env
GODOT_VERSION=4.0.2
GODOT_EXEC_URL=https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_macos.universal.zip
GODOT_TEMPLATES_URL=https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION
GODOT_TEMPLATES_DIR="/Users/builder/Library/Application Support/Godot/templates"
GODOT_EXEC=Godot.app/Contents/MacOS/Godot
EXPORT_TYPE="iOS Production"
ARTIFACT=app.zip

# Download Godot 4
curl -LO ${GODOT_EXEC_URL} && unzip Godot_v${GODOT_VERSION}-stable_macos.universal.zip

# Download templates
curl -LO ${GODOT_TEMPLATES_URL} && unzip Godot_v${GODOT_VERSION}-stable_export_templates.tpz
mkdir -p "${GODOT_TEMPLATES_DIR}" && mv templates "${GODOT_TEMPLATES_DIR}/${GODOT_VERSION}.stable"

# Build
mkdir build/
${GODOT_EXEC} --path mobile-game/ --headless export-release "${EXPORT_TYPE}" build/${ARTIFACT}
```

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
You need to use the workaround described in https://github.com/godotengine/godot-proposals/issues/1362.

**Comment by AdrKacz** [comment]
I am aware of this workaround. As you said it is a workaround and should not be the "way to go".

How could we make sure this will be fix in further release?

I'd be happy to help but have no experience on Godot codebase.

**Comment by Calinou** [comment]
> How could we make sure this will be fix in further release?

As discussed in the proposal I linked, this is a difficult feature to implement given how Godot's import system works.
