### ISSUE TITLE
Traditional Chinese is not supported (Remaps)

### ISSUE THREAD

**Issue by Skyfrit** [godotengine/godot#7674]
**Operating system or device - Godot version:**
GODOT 2.1.2

**Issue description:**
I set test to zh_TW, but it doesn't works

![capture1](https://cloud.githubusercontent.com/assets/20874456/22406835/37d74740-e695-11e6-91c8-92a035f719f4.JPG)
![capture2](https://cloud.githubusercontent.com/assets/20874456/22406836/390f9d74-e695-11e6-9740-dc37459209a7.JPG)

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
Cherry-picked for 3.0.7.
