### ISSUE TITLE
Cannot unzip Godot 4 download

### ISSUE THREAD

**Issue by AdrKacz** [godotengine/godot#76744]
### Godot version

4.0.2

### System information

MacOS

### Issue description

The objective is to download Godot 4 via Command Line for CI/CD. Below are the steps to reproduce the bug.

```
curl -o ./godot.zip https://github.com/godotengine/godot/releases/download/4.0.2-stable/Godot_v4.0.2-stable_macos.universal.zip # the download succeeded and I can see ./godot.zip with cd
unzip ./godot.zip

Archive:  ./godot.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of ./godot.zip or
        ./godot.zip.zip, and cannot find ./godot.zip.ZIP, period.
```

As you can see, I cannot `unzip`. The command `jar xvf godot.zip` returns `java.util.zip.ZipException: zip file is empty`.

### Steps to reproduce

Run:
```
curl -o ./godot.zip https://github.com/godotengine/godot/releases/download/4.0.2-stable/Godot_v4.0.2-stable_macos.universal.zip
unzip ./godot.zip
```

### Minimal reproduction project

Not needed.

**Comment by Zireael07** [comment]
Are you sure the file is not broken? I tried your curl and the resulting file is 0 B

**Comment by AdrKacz** [comment]
Good catch, looks like I don't know how to use `curl`..
The following works fine (with `-LO`):
```
curl -LO https://github.com/godotengine/godot/releases/download/4.0.2-stable/Godot_v4.0.2-stable_macos.universal.zip
unzip Godot_v4.0.2-stable_macos.universal.zip
```

**Comment by Calinou** [comment]
You must use `-L` to follow redirects.

Please don't ask support questions here, as this issue tracker is meant to be used for bug reports only. Use one of the other [community channels](https://godotengine.org/community) instead.
