### ISSUE TITLE
RichTextLabel returns invalid line and paragraph index for first respective characters

### ISSUE THREAD

**Issue by Nidjo123** [godotengine/godot#76758]
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Windows 10, not platform specific

### Issue description

Methods `get_character_line` and `get_character_paragraph` return wrong indices for characters that are first in the respective line/paragraph. See the attached screenshot.

![image](https://user-images.githubusercontent.com/892180/236546781-692603be-eb09-419e-822e-d4152a66d9b6.png)

### Steps to reproduce

Run attached project.

The script goes through all characters in `RichTextLabel` and prints the respective character, line index, and paragraph index. None of them should be -1 since we are iterating through valid indices.

### Minimal reproduction project

[RichTextLabel.zip](https://github.com/godotengine/godot/files/11409399/RichTextLabel.zip)

**Comment by Calinou** [comment]
I can confirm this on 4.1.dev 33957aee6 (Linux).

Output:

```
'T' is on line -1, paragraph -1
'h' is on line 0, paragraph 0
'i' is on line 0, paragraph 0
's' is on line 0, paragraph 0
' ' is on line 0, paragraph 0
'i' is on line 0, paragraph 0
's' is on line 0, paragraph 0
' ' is on line 0, paragraph 0
't' is on line -1, paragraph 0
'h' is on line 1, paragraph 0
'e' is on line 1, paragraph 0
' ' is on line 1, paragraph 0
'f' is on line 1, paragraph 0
'i' is on line 1, paragraph 0
'r' is on line 1, paragraph 0
's' is on line 1, paragraph 0
't' is on line 1, paragraph 0
' ' is on line 1, paragraph 0
'p' is on line -1, paragraph 0
'a' is on line 2, paragraph 0
'r' is on line 2, paragraph 0
'a' is on line 2, paragraph 0
'g' is on line 2, paragraph 0
'r' is on line 2, paragraph 0
'a' is on line 2, paragraph 0
'p' is on line 2, paragraph 0
'h' is on line 2, paragraph 0
'
' is on line 2, paragraph 0
'S' is on line -1, paragraph 0
'e' is on line 3, paragraph 1
'c' is on line 3, paragraph 1
'o' is on line 3, paragraph 1
'n' is on line 3, paragraph 1
'd' is on line 3, paragraph 1
'
' is on line 3, paragraph 1
'T' is on line -1, paragraph 1
'h' is on line 4, paragraph 2
'i' is on line 4, paragraph 2
'r' is on line 4, paragraph 2
'd' is on line 4, paragraph 2
```
