### ISSUE TITLE
HTML5 mouse doesn't lock

### ISSUE THREAD

**Issue by Silvea12** [godotengine/godot#7675]
**Operating system or device - Godot version:** Arch Linux x86_64, but using web, godot 2.1.2

**Issue description:**

Mouse look is meant to work, and it doesn't when using web.
Mouse cursor capture is not locked in WebGL, making it impossible to capture the cursor.
Additionally. y 0 is either at the top or above the top of the screen, making it impossible to look up (currently)

**Steps to reproduce:**
Set up a kinematic controller, add a collider
Attach a camera to the kinematic body as a child, leave default name
Add a floor with collision (I used static body)
Use https://hastebin.com/ividaqayuf.cs as the script for the kinematicbody
Export for web

**Link to minimal example project:**
:
Live demo: https://silvea12.keybase.pub/mousebug/horse.html

**Comment by bojidar-bg** [comment]
(retitled since it's not WebGL that locks the mouse)

**Comment by Silvea12** [comment]
Note, the glitchy mouse movement I have found was due to me not using relative_x and relative_y. This has been fixed, but mouse lock is still not working. I won't update the example project and code for historical reasons.
