### ISSUE TITLE
Turning on animated physics bone on Skeleton3D is very performance intensive.

### ISSUE THREAD

**Issue by HotHead007** [godotengine/godot#76769]
### Godot version

4.0.3

### System information

Windows 10

### Issue description

In skeleton 3d nade if we turn on animat physics bones option the editor starts to lagg a lot ( like fps drops 10 to 15 frames i think) but the editor says fps is 150 or higher.
Even with simple ragdoll if i can't use 2 or 3  ragdoll, if i do editor crashes.

There is definately a problem in godot 4.0 godot 3 runs fine.

### Steps to reproduce

Create a ragdoll.

### Minimal reproduction project

[Amimated physics bone.zip](https://github.com/godotengine/godot/files/11413897/Amimated.physics.bone.zip)

**Comment by smix8** [comment]
Please add an MRP with your skeleton / ragdoll.

I am creating a ragdoll right now and have none of those performance issues you describe.

Do you have errors from your skeleton? Cause error log / print can do that.

**Comment by HotHead007** [comment]
it seems to be the case on my duel core amd a6 processor. if you still didn't face the same issue you can duplicate it few time.
it crashed when i did it 3 times.

**Comment by HotHead007** [comment]
https://user-images.githubusercontent.com/132071423/236657468-294074d7-48a9-4b91-9789-6aa812507f62.mp4

**Comment by HotHead007** [comment]
https://user-images.githubusercontent.com/132071423/236658619-ba7b01f0-fbdc-4604-bea9-7d9e58e6e45d.mp4

**Comment by smix8** [comment]
Since so far no one could reproduce this issue you could pick or build one of the recent Godot builds with debug symbols and start Godot in a console to see what actually triggers your crash and print that crash log here.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
