### ISSUE TITLE
Lingering tooltips when Godot editor window is in background

### ISSUE THREAD

**Issue by trollusk** [godotengine/godot#76766]
### Godot version

4.0.2

### System information

Windows 11

### Issue description

Toooltips in the Godot editor persist when another application window is on top of the Godot window and the mouse leaves the Godot window. This obscures part of the top window. See video.

![Untitled video](https://user-images.githubusercontent.com/220468/236569274-17c8a663-becb-49aa-90cc-7c89d292e2b8.gif)

### Steps to reproduce

- Load any project in editor.
- Open another application window in front of the Godot editor (so that the editor loses focus but is still visible). 
- Move mouse over a list of items (eg methods or scene tree) in the Godot editor window. Tooltips will protrude over the front window and will not disappear when the mouse leaves the Godot window.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Thanks for the report! Consolidating as part of https://github.com/godotengine/godot/issues/48634.
