### ISSUE TITLE
Screen-reading (postprocessing) shaders makes Volumetric Fog visible through walls

### ISSUE THREAD

**Issue by Donitzo** [godotengine/godot#76780]
### Godot version

4.0.1

### System information

Windows 11

### Issue description

When using a screen-reading shader in conjunction with environmental volumetric fog, there is a very clear difference in the way scene looks without and with the shader. The fog light emission is visible through walls.

![screen-reading-bug](https://user-images.githubusercontent.com/58847200/236618164-f4ed4e24-1333-4a44-a2fb-dbb412bc3cdf.png)

I would assume some sort of information is lost when the scene is re-rendered through a screen-reading shader. I have tried writing the original depth in the shader as well but with the exact same result.

I understand that it is possible this isn't a bug but may actually just be a technical limitation of some kind.

### Steps to reproduce

Use volumetric fog together with a passthrough screen-reading shader. Add a light behind a wall.

### Minimal reproduction project

[FogTest.zip](https://github.com/godotengine/godot/files/11412077/FogTest.zip)

**Comment by Calinou** [comment]
Using `SCREEN_TEXTURE` makes the material transparent, which makes it not draw to the depth buffer. As a result, [transparency sorting issues](https://docs.godotengine.org/en/latest/tutorials/3d/3d_rendering_limitations.html#transparency-sorting) are expected to occur.
