### ISSUE TITLE
Cross compiling for Windows on Ubuntu throws error "Error: Couldn't load project data at path ".". Is the .pck file missing?" when trying to run

### ISSUE THREAD

**Issue by nbstrong** [godotengine/godot#76783]
### Godot version

master - 64eeb04d2c

### System information

Windows 11 with WSL Ubuntu

### Issue description

Compiled for Windows from Ubuntu with
`scons platform=windows precision=double use_lto=yes target=template_release`

Compilation was successful. When trying to run 
`godot.windows.template_release.double.x86_64.exe`

The error:
```
Error: Couldn't load project data at path ".". Is the .pck file missing?
If you've renamed the executable, the associated .pck file should also be renamed to match the executable's name (without the extension).
```

### Steps to reproduce

`scons platform=windows precision=double use_lto=yes target=template_release`

Run:
`godot.windows.template_release.double.x86_64.exe`

### Minimal reproduction project

This was done on a fresh clone from Master.

**Comment by nbstrong** [comment]
I am likely getting confused here.

Is target=template_release supposed to build your game and not the editor? So I am not passing it a .pck project file to build?

My intention was to build the editor in release mode.

**Comment by bruvzg** [comment]
> Is target=template_release supposed to build your game and not the editor?

It is for building the game executable, to build the release version of editor use `target=editor production=yes`.

**Comment by nbstrong** [comment]
Ok. Thank you.

I'd like to note that the documents don't make the separation between building the game and building the engine very clear.

Most of the documentation for the build system is under "Engine development".

I haven't built a game yet though so maybe this will become clearer once I do.
