### ISSUE TITLE
Custom import scripts not working in C#

### ISSUE THREAD

**Issue by RotuleCraque** [godotengine/godot#76781]
### Godot version

v4.0.3.rc1.mono.official [2d74ee0e5]

### System information

Windows 10

### Issue description

Adding a custom script to the import options of a scene and reimporting the scene has no effect.
Changes made to the scene in EditorScenePostImport._PostImport(Node scene) do not seem to be applied.

### Steps to reproduce

1. Create a new C# Godot project
2. Create a new C# script named NodeRenamer.cs and paste the following based on the sample code from the [EditorScenePostImport documentation page](https://docs.godotengine.org/en/stable/classes/class_editorscenepostimport.html)

```
using Godot;

// This sample changes all node names.
// Called right after the scene is imported and gets the root node.
[Tool]
public partial class NodeRenamer : EditorScenePostImport
{
    public override GodotObject _PostImport(Node scene)
    {

        // Change all node names to "modified_[oldnodename]"
        Iterate(scene);
        return scene; // Remember to return the imported scene
    }

    public void Iterate(Node node)
    {
        if (node != null)
        {
            node.Name = $"modified_{node.Name}";

            GD.Print($"The node's new name is: {node.Name}");

            foreach (Node child in node.GetChildren())
            {
                Iterate(child);
            }
        }
    }
}
```
3. Build the solution
4. Create a simple scene with a few objects in your favourite digital content creation software and import it in Godot as .glb or .gltf
5. Set the scene's Import Script to NodeRenamer.cs, then reimport the scene
6. Notice the names of the objects in the scene have not been modified, though GD.Print() was called

### Minimal reproduction project

N/A

**Comment by Kirbyrawr** [comment]
Hi, did you press build in the project? 
The other day a plugin of mine didn't work till i pressed build so it may be similar.

If it doesn't work then no idea, apologies.

**Comment by RotuleCraque** [comment]
Hi @Kirbyrawr, thank you for your help!
I had built the solution but had omitted to mention it, I've edited the steps to reproduce accordingly, thanks for pointing it out!

**Comment by RotuleCraque** [comment]
After further testing it appears that the custom import scripts are working fine. I was expecting the modifications to be visible in the imported scene while they are actually visible in inherited scenes.
