### ISSUE TITLE
Invalid call. Nonexistent function 'listen' in base 'PacketPeerUDP'.

### ISSUE THREAD

**Issue by JonnyTech** [godotengine/godot#76782]
### Godot version

4.0.2

### System information

Debain

### Issue description

Unable to use `PacketPeerUDP.listen`

### Steps to reproduce

Create a new `PacketPeerUDP` and use the listen property

### Minimal reproduction project

```
extends Node

var udp_ip = "127.0.0.1"
var udp_port = 44444
var udp = PacketPeerUDP.new()

func _ready():
	if (udp.listen(udp_port) != OK):
		print("Error listening to port: ", str(udp_port))
	else:
		print("Listening to port: " , str(udp_port))
```

**Comment by kleonc** [comment]
[`PacketPeerUDP`'s `listen()` is now `bound()`](https://docs.godotengine.org/en/4.0/tutorials/migrating/upgrading_to_godot_4.html#manually-renaming-methods-properties-signals-and-constants). Also you can always check the class reference: [PacketPeerUDP](https://docs.godotengine.org/en/4.0/classes/class_packetpeerudp.html).

Already documented, hence closing.

**Comment by kleonc** [comment]
> [`PacketPeerUDP`'s `listen()` is now `bound()`](https://docs.godotengine.org/en/4.0/tutorials/migrating/upgrading_to_godot_4.html#manually-renaming-methods-properties-signals-and-constants).

Actually that's incorrect, should be "`PacketPeerUDP`'s `listen()` is now **`bind()`**". Gonna open a PR fixing that.

**Comment by JonnyTech** [comment]
Thank you, it works as described.
