### ISSUE TITLE
Word wrap makes label unreadable when put in VBoxContainer

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#7679]
Tested on Godot 2.1.1 and 2.1.2, Windows 10 64 bits

What I did:
Create a VBoxContainer, and add a few labels in it, all of them with some text. Enable word wrapping (auto-wrap) on one of them.

What happened:
The label shrunk to a height of 1, making the text unreadable. It can be resized but it overlaps on the following labels.

What was expected:
Be able to see the text, and have the label increase in height if word wrap makes it create visual line breaks so it push next items down (related to https://godotengine.org/qa/11957/how-can-set-label-change-size-according-the-length-of-the-text)

Screenshot:
![godot_label_wordwrap_vbox](https://cloud.githubusercontent.com/assets/1311555/22410407/ff0b4a62-e697-11e6-8525-d5d86118ada8.png)

**Comment by bojidar-bg** [comment]
Related to the closed #4379. As mentioned by @reduz [there](https://github.com/godotengine/godot/pull/4379#issuecomment-227018145):
>more complex container system use a function widthForHeight(), but this is
too much for Godot, so the best is to simply set a minimum size manually
with label.set_custom_minimum_size()
or use ratios for expand

**Comment by volzhs** [comment]
I wish we could support this.

**Comment by bojidar-bg** [comment]
Well, I wish so too :smiley: 

Only thing is that we have to decide how and if it's worth it.

**Comment by nerzhul** [comment]
I have exactly same problem and it's anoying. I have a vboxcontainer, if i add a richttextlabel => 1px height. Solved using set_custom_minimum_size

**Comment by Zylann** [comment]
I found this about Unity3D GUI today, FYI: https://docs.unity3d.com/Manual/HOWTO-UIFitContentSize.html

**Comment by jamie-pate** [comment]
Still getting this behavior in 3.0.6? :(
Not solved by set_custom_minimum_size

**Comment by annemarietannengrund** [comment]
there are issues with labels and labelcontent all over the place when working with long strings (i.e. translations).
as i tried working with UI i ran into these issues and trying to fix it or finding out how to handle it i stumpled over different approaches or components that might be required to achieve the desired behavior.

so for everyone crossing this post while as lost as me, i tried setting up some (minimal) examples on how to achieve a layout with more text than can be forseen.

[Example repository](https://github.com/annemarietannengrund/theGodotExperience/tree/main/Examples/Example1)
