### ISSUE TITLE
GDExtension doc page broken.

### ISSUE THREAD

**Issue by bend-n** [godotengine/godot#76796]
### Godot version

53191928e597d15a709b53abe1870b9f3607af1c  caused regression

### System information

ArchLinux x11

### Issue description

Opening docs (<kbd>f1</kbd>) and searching for desired GDExtension class will yield nothing, clicking on GDScript doc page with a typed fucntion that takes a GDExtension class (
```gdscript
func test(obj: VeryInterestingClass):
	pass
```
) Will take you to a empty doc page.

https://user-images.githubusercontent.com/70787919/236650001-dd9cd8ed-2f01-468c-b4ba-73513676abf3.mp4

<sup>[gdext tracker](https://github.com/godot-rust/gdext/issues/258)</sup>

### Steps to reproduce

I havent figured out how to use godot-cpp in 4.x, so the mrp is in rust.
To use:
- `cargo build -r` (compiling `godot-core` will take a while, but its normal)
- `godot4 -e`
- Open docs
- Search for `StructThatDoesntShowUp`
- Open docs for `Test`
- Click on the function type in `test()`

### Minimal reproduction project

[bug.zip](https://github.com/godotengine/godot/files/11413552/bug.zip)

**Comment by bend-n** [comment]
Does it not get the `regression` label?

**Comment by AThousandShips** [comment]
GDExtension is strictly 4.x is it not?

**Comment by bend-n** [comment]
Its a regression that started with https://github.com/godotengine/godot/commit/53191928e597d15a709b53abe1870b9f3607af1c.

**Comment by AThousandShips** [comment]
I don't really see how that PR could have done anything to this documentation though, so very strange what actually caused it

**Comment by bend-n** [comment]
Its probably some kind of thread misuse in the docgen?

**Comment by AThousandShips** [comment]
I mean how it can affect *only* this part of documentation and not the general documentation, not sure

**Comment by AThousandShips** [comment]
Does the issue persist if you change this line to false?
https://github.com/godotengine/godot/blob/64eeb04d2cb2e269d9710c38bdbf366ab3656e76/editor/editor_help.cpp#L2295

**Comment by bend-n** [comment]
I bisected it so im pretty sure that the issue will persist, will try later though.

**Comment by AThousandShips** [comment]
I'm not able to set up for gdextension at the moment on my platform, and haven't worked with gdextension previously

**Comment by dsnopek** [comment]
Possibly the same issue as https://github.com/godotengine/godot/issues/82817

**Comment by dkaste** [comment]
v4.3.dev.custom_build [fe01776f0] 

The docs load properly upon starting the editor, but the classes completely disappear from search once the GDExtension is reloaded. The docs pages stay open in the script editor, but are not updated. GDScript autocompletion for the relevant classes also stops working once the extension is reloaded.

Is this feature working properly for anyone? Is there any workaround?

**Comment by dsnopek** [comment]
I'm able to reproduce this issue still (although, I think we may have fixed and re-introduced it at least one since this issue has been created).

I just posted PR https://github.com/godotengine/godot/pull/91126 which fixes this in my testing.
