### ISSUE TITLE
OpenGL: Godot Editor renders blank interface at launch when using eGPU on macOS

### ISSUE THREAD

**Issue by bitinn** [godotengine/godot#76802]
### Godot version

4.0.2 stable

### System information

macOS Monterey (12.6.2), Apple Blackmagic eGPU (Radeon Pro 580)

### Issue description

Attempting to launch Godot Editor app directly with "Prefer External GPU" will cause it to render blank background at launch.

<img width="1152" alt="Screen Shot 2023-05-07 at 14 57 28" src="https://user-images.githubusercontent.com/1484279/236663066-ffb4fbe0-8923-4772-b14f-59d6d63e3a51.png">

I have waited for more than 10 minutes and it doesn't seem to do anything.

Launching Godot by clicking project file, however, doesn't seem to suffer from the same problem, here is me testing the Lumberyard Bistro scene ported to Godot.

<img width="1380" alt="Screen Shot 2023-05-07 at 15 04 58" src="https://user-images.githubusercontent.com/1484279/236663277-330db030-3de6-431b-be76-2433e5d9adc5.png">

### Steps to reproduce

- Set "Prefer External GPU" option in Godot app's Info menu.
- Test opening Godot app directly vs opening Godot via project file.

Note in the first case, Godot doesn't hang, nor does it output any relevant errors to macOS Console;
In the second case Godot launch correctly, outputs some Metal compilation error but doesn't prevent normal usage.

Also note that Blackmagic is an Apple certified eGPU device with native macOS support, so no third-party driver were installed.

https://support.apple.com/en-us/HT208897

### Minimal reproduction project

Not required.

**Comment by Calinou** [comment]
> Launching Godot by clicking project file, however, doesn't seem to suffer from the same problem, here is me testing the Lumberyard Bistro scene ported to Godot.

This means the Compatibility rendering method is broken on external GPUs, but Vulkan (MoltenVK-based) rendering methods are fine (Forward+/Forward Mobile).

The project manager always uses Compatibility as it starts up faster compared to Vulkan. You can force the use of Vulkan in the project manager by starting it with the `--rendering-driver vulkan` [command line argument](https://docs.godotengine.org/en/stable/tutorials/editor/command_line_tutorial.html).

**Comment by Calinou** [comment]
@bitinn Can you still reproduce this on [4.3.rc2](https://godotengine.org/article/release-candidate-godot-4-3-rc-2/)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.
