### ISSUE TITLE
`res://` location is inconsistent when running an exported project from another folder

### ISSUE THREAD

**Issue by JonnyTech** [godotengine/godot#76817]
### Godot version

4.0.2

### System information

Debian

### Issue description

My project has a settings file: `settings.json`.
It lives in the exported project folder.
It is accessed as follows:
`var txt_settings = FileAccess.open("res://settings.json", FileAccess.READ)`

This works well when:
 - accessed from the Godot editor
 - exported project is started from a file manager
 - exported project is started from a bash prompt/script in the same folder

But if I start the exported project from a bash prompt/script in another folder then the settings file is not found.
```
#!/bin/bash
/home/user/Desktop/myproject
```
```
$ cd /home/user
$ ls Desktop
myproject    settings.json
$ /home/user/Desktop/myproject
```

Adding this code to the script:
`settingsfile = ProjectSettings.globalize_path("res://settings.json");`

Start the exported project from bash in the same folder - shows the correct path.
Start the exported project from bash in another folder - shows blank string.

Is this a bug? I would like to start my project from a script but currently cannot.

### Steps to reproduce

Steps detailed above

### Minimal reproduction project

See code above

**Comment by Calinou** [comment]
In an exported project, `res://` only finds files within the PCK, not in the same folder as the exported binary. Use `OS.get_executable_path.path_join("settings.json")` to read a file in the same folder as the exported binary.

**Comment by JonnyTech** [comment]
Thank you @Calinou for you quick and detailed response.

> Did you enable PCK embedding when exporting the project?

Bingo! Sorry for omitting that part. Yes, your explanation makes sense.

> `Use OS.get_executable_path.path_join("settings.json")` to read a file in the same folder as the exported binary.

Thanks, that works!

But in the editor, this returns the path of the installed `godot` executable (in my case `/usr/local/bin/godot`). I guess that I need to fiddle a bit and find a way to make that run when both editing and once exported.

> you can work around this by adding this at the top of your script, so that it cds to the folder containing the script:

Another gem - great, I shall try that soon.

I have a busy day but shall try to get a minimal project to you later - sorry for not doing it sooner.

**Comment by oxygen** [comment]
On Godot 4.3.dev5 OS.GetExecutablePath().GetBaseDir() is empty or null on exported project

```C#
GD.Print($"OS.GetUserDataDir() {OS.GetUserDataDir()}");
GD.Print($"OS.GetExecutablePath().GetBaseDir() {OS.GetExecutablePath().GetBaseDir()}");
```

Output:
```
OS.GetUserDataDir() /data/data/com.projectname/files
OS.GetExecutablePath().GetBaseDir() 
```

How do I get the res:// base path?
