### ISSUE TITLE
Shorten AnimationPlayer signal names

### ISSUE THREAD

**Issue by razcore-art** [godotengine/godot#7682]
I'm opening this because the v3 API changes issue is close... or I don't know which one is currently open.

The `AnimationPlayer` node has these signals:

- `animation_changed(String old_name, String new_name)`
- `animation_started(String name)`
- `finished()`

When auto generating functions for these signals through the GUI we'd end up with names like `_on_AnimationPlayer_animation_started` etc. Kind of an overkill. I propose these be changed in v3 to:

- `changed(String old_name, String new_name)`
- `started(String name)`
- `finished(String name)` <- also include info on which animation finished playing
- `finished_all()` <- as per @bebae's comment in #7444. I didn't know that `finished` is emitted after ALL animations are finished playing. So basically the old `finished` would become `finished_all` or something like that and the new `finished(String name)` will behave as `started(String name)`

**Comment by volzhs** [comment]
hm. I'm not 100% sure.
but, we can have several `AnimationPlayer` nodes, and can connect with auto generated functions.
```
- Node
    - Sprite
    - AnimationPlayerForSomething
    - AnimationPlayerForAnotherThing
```
if we want to make a connection to auto generated functions in Node (root),
shouldn't we make that long function name?

**Comment by williamd1k0** [comment]
Hm, I think I should close my issue #7444 because this issue is more "detailed"...

**Comment by razvanc-r** [comment]
@volzhs I'm not sure what you're saying. In your case the GUI would create `_on_AnimationPlayerForSomething_changed()` & `_on_AnimationPlayerForAnotherThing_changed()` for example for the `change()` signal.

**Comment by volzhs** [comment]
@razvanc-r in that case, I agreed with your suggestion.
I thought you suggest changing very short function name without considering AnimationPlayer node names.
I guess I misunderstood.

**Comment by reduz** [comment]
I am fine with the way it works, I thin it's clearer and should be the default. That said, if you want to add some option to use shorter names because you are more comfortable with that, go ahead

**Comment by reduz** [comment]
in the meantime, kicking to 3.1

**Comment by akien-mga** [comment]
I also tend to prefer the explicit `animation_changed` and `animation_finished` names. Especially for `changed`, not specifying that we're talking about the animation can be confusing (there's more than the animations that can change in `AnimationPlayer`, it could be other properties).

I definitely don't agree with making this optional as @reduz suggested, so closing. If there's really a lot of community interest in making such changes, it should be tracked in #16863 for 4.0.
