### ISSUE TITLE
.tscn scenes become .tscn.remap files in exported projects

### ISSUE THREAD

**Issue by reflexguru** [godotengine/godot#76823]
### Godot version

4.0.2

### System information

Windows 11, Intel Core I5 12400F, Forward+, AMD RX 6700XT

### Issue description

When listing a directory from GDScript, .tscn scenes are .tscn.remap files in exported projects, which never happened in Godot 3.x, hence this is a behavior inconsistency between runtime and exported project and causes issues. Happens in 4.0.3-rc1 as well.

### Steps to reproduce

1. Create a bunch of scenes somewhere in your project.
2. Use an official snippet from Godot Documentation to read that directory and somehow show that on screen.
3. See the difference between runtime and exported project.

![image](https://user-images.githubusercontent.com/31435600/236733537-7792672c-eb90-43d8-aa66-8ef6dd386103.png)

### Minimal reproduction project

[reprod-project.zip](https://github.com/godotengine/godot/files/11417637/reprod-project.zip)

**Comment by Calinou** [comment]
This is intentional behavior in 4.x, as per this comment: https://github.com/godotengine/godot/issues/66014#issuecomment-1440261929

Please continue the discussion as per https://github.com/godotengine/godot/issues/25672.
