### ISSUE TITLE
HTTPRequest fails HEAD mode requests in Chrome 113

### ISSUE THREAD

**Issue by Isaaaca** [godotengine/godot#76825]
### Godot version

v3.5.2.stable.official [170ba337a]

### System information

Chrome Version 113.0.5672.64 (Official Build) (64-bit), Microsoft Edge Version 113.0.1774.35 (Official build) (64-bit)

### Issue description

After Chromium 113, http requests with the HEAD method returns a response with an null body. This results in a TypeError in html5 exports, which causes HTTPRequest nodes to return a RESULT_CONNECTION_ERROR  with a response code of 0. So far this affects all Chromium browsers, Firefox and Safari have not been affected (based on my limited testing). I suspect the problem to affect the HTTPClient node as well, but I have not tested that yet.

**TypeError and Variables returned from 'request_completed' signal**
![image](https://user-images.githubusercontent.com/35775019/236754539-ec9c10ff-6da6-4c21-af80-00782856aaca.png)

**Response object with body being `null` in Chrome 113**
![image](https://user-images.githubusercontent.com/35775019/236754424-78dfeefb-6370-4d74-9a4f-8eb8c287af4f.png)
**Response object in Firefox and older Chromium Browsers**
![image](https://user-images.githubusercontent.com/35775019/236756551-fd0d813e-f4eb-479b-86ce-33d7fd2a5ffe.png)

I believe the js error is caused by this bit of code in the .js export:
![image](https://user-images.githubusercontent.com/35775019/236755696-625e95d9-bded-478b-83c9-03df638ce441.png)

But re-writing that bit so that obj.reader is `null`, `undefined` or `new ReadableStream().getReader()` only suppresses the error and does not solve the problem.

### Steps to reproduce

1. Create a HTTPRequest node
2. Make a (valid) request with the HEAD method.
3. Export the project to HTML5
4. Run the project in any Chromium browser based on Chromium 113

### Minimal reproduction project

[HTTPRequestMRP.zip](https://github.com/godotengine/godot/files/11418745/HTTPRequestMRP.zip)

**Comment by Calinou** [comment]
Can you reproduce this in Chromium 112 or older?

**Comment by jmwielandt** [comment]
@Calinou maybe you wanna see this issue https://github.com/microsoft/typed-rest-client/issues/355

**Comment by Isaaaca** [comment]
> Can you reproduce this in Chromium 112 or older?

No, it only occurs in Chromium 113.0.5672.64. Our project started having problems since last week's (2 May) update to the version.
https://chromereleases.googleblog.com/2023/05/stable-channel-update-for-desktop.html

Good news is, it seems this has been _just_ been reverted.
https://chromereleases.googleblog.com/2023/05/stable-channel-update-for-desktop_8.html
![image](https://user-images.githubusercontent.com/35775019/236979935-c82dc8ae-8511-4a36-b78b-f22c7a42b220.png)
from: https://chromium.googlesource.com/chromium/src/+log/113.0.5672.63..113.0.5672.92?pretty=fuller&n=10000

However, it might still be worth fixing since having a response with a null body does comply to standard.
![image](https://user-images.githubusercontent.com/35775019/236980364-edc4f5f7-e26d-4aa3-8b47-4f4e698ae55c.png)
https://fetch.spec.whatwg.org/#responses

**Comment by lodicolo** [comment]
Because of the aforementioned revert this isn't happening in Chromium (127.0.6533.72), but does currently happen on Firefox (131.0.3) for `HEAD` requests (and presumably for any empty responses for other HTTP methods).

I traced it down to [library_godot_fetch.js#L62](https://github.com/godotengine/godot/blob/master/platform/web/js/libs/library_godot_fetch.js#L62) and I opened PR #98431 as a possible minimally invasive solution.
