### ISSUE TITLE
GridContainer V-Separation still shows for nodes that are hidden

### ISSUE THREAD

**Issue by CactiChameleon9** [godotengine/godot#76827]
### Godot version

v3.5.2.stable.official [170ba337a]

### System information

Linux, Ryzen 5 4500U, Integrated graphics, GLES2, GLES3

### Issue description

The Vertical Separation for a Grid Container is still shown per node even if that node is hidden - meaning space is taken up when it shouldn't be.

See a screenshot below of an (extreme) example:  
![image](https://user-images.githubusercontent.com/51231053/236775547-5c81b053-0f91-4ab1-bb59-cbaf8c813290.png)

### Steps to reproduce

1. New Scene
2. Control (UI) root node
3. Add a GridContainer
4. Make the GridContainer fill the control (Layout -> Full Rect)
5. Add a ColorRect as a child of the GridContainer
6. Set the ColorRect to expand Horizontally and Vertically in Size Flags
7. Duplicate the ColorRect (CTRL+D) a few times
8. Make the last one hidden and duplicate it more times

You should now see vertical space being taken up by hidden nodes

### Minimal reproduction project

[GridContainer BugReport.zip](https://github.com/godotengine/godot/files/11419444/GridContainer.BugReport.zip)

**Comment by akien-mga** [comment]
Fixed by #76833.
