### ISSUE TITLE
Godot 4 SSR jittering

### ISSUE THREAD

**Issue by Intervel** [godotengine/godot#76837]
### Godot version

Godot_v4.0.2-stable_win64

### System information

Windows 11,  Rtx 3090

### Issue description

SETTINGS :

SSR max steps : 512
fade in : 0.150
fade out :  2.00

SDFGI is on.

its jittering, ugly pixelated. kinda blur? idk how to described it.

watch : https://www.veed.io/view/dd69c255-084e-4d51-822a-cc08ad77df5d?sharingWidget=true&panel=

watch 2 : https://www.veed.io/view/1d3d80e8-2ac6-49b7-9ffe-55cd4a663612/a84a4b44-1be8-4142-aa01-011655511e86?sharingWidget=true&panel=

### Steps to reproduce

cant share the file. copyright texture

### Minimal reproduction project

cant share the file. copyright texture

**Comment by adamscott** [comment]
Can you reproduce the issue with another non-copyright texture? We can't really assess the issue without a minimal reproduction project.

And you can upload videos to github by dragging the file to the issue text box.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.

PS: Since no minimal reproduction project was included in the original bug report, please upload one as well to ease troubleshooting.
