### ISSUE TITLE
SDFGI doesn't work on mac

### ISSUE THREAD

**Issue by oliver20033549** [godotengine/godot#76835]
### Godot version

4.0.stable

### System information

MacOS Cantalina, Version 10.15.7, Vulkan, Intel Iris Pro 1536 MB

### Issue description

I have been using Godot 4 stable for a while but I can't happen to use the SDFGI whenever I turn it on nothing changed I wonder why?

### Steps to reproduce

no answer

### Minimal reproduction project

no answer

**Comment by Calinou** [comment]
- Duplicate of https://github.com/godotengine/godot/issues/63149.
