### ISSUE TITLE
[3DS] Failed to git clone and scons

### ISSUE THREAD

**Issue by CereEnder** [godotengine/godot#7684]
Can't git clone. I've got the message: 

cereender@HAL-LU:~/Descargas$ git clone https://github.com/Cruel/godot
Clonar en «godot»...
remote: Counting objects: 59993, done.
error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

I tried downloading in zip, but when I extracted it only shows those platforms: 

cereender@HAL-LU:~/Descargas/godot-3ds$ scons
scons: Reading SConscript files ...
sh: 1: i586-mingw32msvc-gcc: not found
sh: 1: i686-w64-mingw32-gcc: not found
sh: 1: pkg-config: not found
pkg-config not found.. x11 disabled.
No valid target platform selected.
The following were detected:
	windows
	server
	haiku

Please run scons again with argument: platform=<string>
scons: done reading SConscript files.
scons: Building targets ...
scons: `.' is up to date.
scons: done building targets.

current platform: lubuntu 16.04 (Linux)

**Comment by punto-** [comment]
the message from scons is not necessarily all the platforms you can build
(I bet you don't have the haiku SDK), you need to find out what env
variable you have to set for 3DS to be properly detected, it should be on
the platform README, or look into platform/3ds/detect.py

**Comment by akien-mga** [comment]
> the message from scons is not necessarily all the platforms you can build (I bet you don't have the haiku SDK)

Actually it is, as far as our `detect.py` files are concerned. It's just haiku's file doesn't check that the required compiler is in the PATH before saying that `can_build` is true :)

Here though, the issue is that you're on Linux X11, so it's selected as the default target platform if you don't specify `scons platform=<something else>`, and:
```
sh: 1: pkg-config: not found
pkg-config not found.. x11 disabled.
```

So install pkg-config.

Regarding the git clone issue, it must be a temporary GitHub problem.

**Comment by CereEnder** [comment]
Thanks both for answer me so quickly. I have installed pkg-config but now i have a lot of broken packages :hankey: 
the detect.py says I must have installed devkitPRO/ARM/CTRULIB. Done, but still not detecting 3ds

**Comment by punto-** [comment]
detect.py is probably checking some environment variables to detect those
SDKs, see if you have them setup correctly

**Comment by CereEnder** [comment]
ok, I am reading detect.py and I think I need all the dependencies. I'll checking now and let you know. THank you
