### ISSUE TITLE
Project-level template script with type casting gets applied without it

### ISSUE THREAD

**Issue by axeldeau** [godotengine/godot#76840]
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

MacOS 13.3.1(a)

### Issue description

I was following this [documentation](https://docs.godotengine.org/en/stable/tutorials/scripting/creating_script_templates.html) and created project-level template script with type casting that would then be applied without it, so this template:
```GDScript
func _process(delta: float) -> void:
	pass
```

gets rendered like:
```GDScript
func _process(delta):
	pass
```

### Steps to reproduce

- Create a project-level script template with GDScript 2.0 and typing syntax
- Use the the created script in the dropdown list of the "Attach Node Script" pop-up
- Observe that the typing informations are gone

### Minimal reproduction project

[bug.zip](https://github.com/godotengine/godot/files/11421147/bug.zip)

**Comment by Calinou** [comment]
Try enabling **Text Editor > Completion > Add Type Hints** in the Editor Settings.
