### ISSUE TITLE
Changing Editor Shortcuts is added to Scene History

### ISSUE THREAD

**Issue by me2beats** [godotengine/godot#76851]
### Godot version

4

### System information

Windows

### Issue description

![image](https://user-images.githubusercontent.com/16458555/236888224-90ed36b6-b033-4046-bada-eda49c59a156.png)

### Steps to reproduce

- add a scene
- change something in Editor-Shortcuts

### Minimal reproduction project

-

**Comment by Calinou** [comment]
I believe this occurs with all editor setting changes, but I agree these shouldn't be stored in undo/redo. Project setting changes should be stored in undo/redo though.

**Comment by me2beats** [comment]
only with Shortcuts

**Comment by KoBeWi** [comment]
Seems like duplicate of #73755?

**Comment by allenwp** [comment]
PR #100061 includes a fix for this bug: it makes changing editor shortcuts appear in global history instead of scene history.
