### ISSUE TITLE
Multiple warnings when loading scene with SkeletonModification2D

### ISSUE THREAD

**Issue by tobeks** [godotengine/godot#76850]
### Godot version

cf8ad12b56df4ae7bba4c73070dd035693a880e4

### System information

Windows 10

### Issue description

Hello team, I am working with SkeletonModification2D and I have noticed several warnings during loading scenes with this modification. Example warnings:

```

  scene\resources\skeleton_modification_2d_lookat.cpp:255 - Cannot verify the bone index for this modification...
  scene\resources\skeleton_modification_2d_lookat.cpp:199 - Cannot update Bone2D cache: modification is not properly setup!
  scene\resources\skeleton_modification_2d_lookat.cpp:264 - Cannot update target cache: modification is not properly setup!
  scene\2d\skeleton_2d.cpp:451 - No Bone2D children of node Bone2D. Cannot calculate bone length or angle reliably.
  Using transform rotation for bone angle
  core\math\transform_2d.cpp:51 - Condition "det == 0" is true.
  core\math\transform_2d.cpp:51 - Condition "det == 0" is true.
  scene\resources\skeleton_modification_2d_lookat.cpp:115 - Target cache is out of date. Attempting to update...
  scene\resources\skeleton_modification_2d_lookat.cpp:122 - Bone2D node cache is out of date. Attempting to update...
```

I have spent some time debugging this problem and I have found out that mechanism for silencing these warnings (is_setup) is enabled while "modifications/0" is loaded and the warning is raised when "bone_index" is loaded which is loaded before the "modifications/0".

![obraz](https://user-images.githubusercontent.com/13313981/236886900-6e1cad38-d32f-441d-a222-d9ff42467c49.png)

### Steps to reproduce

1. Create Scene2D,
2. Add Skeleton2D
3. Add two connected Bone2D
4. Add another Node2D to scene
5. To Skeleton add  SkeletonModification2DLookAt
6. Configure bone2d_node and target_node to the added Node2D.
7. Save and reload project:

Warnings on console:
```
  scene\resources\skeleton_modification_2d_lookat.cpp:255 - Cannot verify the bone index for this modification...
  scene\resources\skeleton_modification_2d_lookat.cpp:199 - Cannot update Bone2D cache: modification is not properly setup!
  scene\resources\skeleton_modification_2d_lookat.cpp:264 - Cannot update target cache: modification is not properly setup!
  scene\2d\skeleton_2d.cpp:451 - No Bone2D children of node Bone2D. Cannot calculate bone length or angle reliably.
  Using transform rotation for bone angle
  core\math\transform_2d.cpp:51 - Condition "det == 0" is true.
  core\math\transform_2d.cpp:51 - Condition "det == 0" is true.
  scene\resources\skeleton_modification_2d_lookat.cpp:115 - Target cache is out of date. Attempting to update...
  scene\resources\skeleton_modification_2d_lookat.cpp:122 - Bone2D node cache is out of date. Attempting to update...
```

### Minimal reproduction project

To reproduce please load project from the attachment:

[look_At.zip](https://github.com/godotengine/godot/files/11423493/look_At.zip)

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/76712.
