### ISSUE TITLE
tga image support

### ISSUE THREAD

**Issue by Gibbz** [godotengine/godot#7686]
**Operating system or device - Godot version:**
ubuntu 16.04
godot 2.2

**Issue description:**
Would love to see tga support - makes working with alpha layers easier

**Comment by SuperUserNameMan** [comment]
what advantages does TGA have over PNG ?

**Comment by ElfEars** [comment]
Is TGA even an open format?
The Wikipedia page says avid tehnology owns it currently... no info on the usage license...

**Comment by Calinou** [comment]
It's definitely possible to implement TGA in open source software, but I don't know about the potential patent issues. Also, I can't see why one would use TGA, especially since PNGs can be used uncompressed as well.

**Comment by Gibbz** [comment]
more of a convenience thing really. If your moving from one project that 
you have used tga's on. If its not something easy to put in we can just 
make a script to batch convert.

**Comment by reduz** [comment]
We need to add this format, the main reason going for it is that,
inPphotoshop, artists have an easier time editing or modifying the alpha
channel due to how it stores it, in comparison to PNG.

**Comment by Gibbz** [comment]
actually, png's strip out the color values from beneath the alpha cannel. Where tga does not do this. 
I'm currently battling through making a shader that would otherwise work fine with tga, with png's it doesnt work...

Are there any other formats that support full rgba channels currently in godot I can use instead?

**Comment by Zylann** [comment]
Png can support alpha layers preservation, I've seen an option for that in Gimp, and a plugin exists for Photoshop. It's just not available by default (and probably not well known). I'm on a phone right now so can't link easily but last time I did the search I found it was possible.

**Comment by SuperUserNameMan** [comment]
Yeah, Gimp's png exporter has a _"Save color values from transparent pixels"_ option.

**Comment by reduz** [comment]
Yeah, not saying PNG does not support this, It's simply an issue of how
Photoshop handles the TGA format vs how it handles PNG

**Comment by Gibbz** [comment]
possibly as a hack in the meantime I wonder if using 99percent transparency
instead of full transparency would suffice?

ive looked around but found no way to get png to preserve color channels
where there is full alpha.

**Comment by Zylann** [comment]
I found back the Photoshop plugin I was referring to: http://www.fnordware.com/superpng/
It adds more options, including the one that lets you save PNGs with transparent pixels preserving colors.
Its for CS3 though, I don't know if there are alternatives for newer versions.

**Comment by reduz** [comment]
this seems pretty simple:
https://github.com/benvh/EasyTGA/tree/master/src

**Comment by Gibbz** [comment]
yeah im using krita. but i can ask them to add support. is it built into
the standard for format? and is it supported by godot?

**Comment by Gibbz** [comment]
any chance of getting tga support in 2.2 github branch? :+1: 
Thanks guys!

**Comment by Zylann** [comment]
Color preservation in transparency channels is supported in the PNG format, it's just an uncommon option and some image editors don't have it. TGA has this by design but it is heavier due to a simpler compression (RLE) (and on Windows you can't have a preview of it unless you open it in Paint.NET or Photoshop :p)

**Comment by tagcup** [comment]
Or SaracenOne's? https://github.com/SaracenOne/tga

**Comment by vnen** [comment]
Solved by 871ceeb0fe219072ae708d4d4397e8ae66873386
