### ISSUE TITLE
Starting the profiler freezes godot

### ISSUE THREAD

**Issue by razcore-art** [godotengine/godot#7688]
Linux alienware 4.8.0-34-generic #36-Ubuntu SMP Wed Dec 21 17:24:18 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Godot v2.1.2.stable.official

**Issue description:**
Pressing on Start Profiling make Godot use 100% processor and freezes the editor.

**Steps to reproduce:**
Open minimum project (included for convenience), Run -> press Start Profiling -> try interacting with editor. Editor is unusable.

**Link to minimal example project:**
[godot-dbg.zip](https://github.com/godotengine/godot/files/741848/godot-dbg.zip)

**Comment by volzhs** [comment]
Linux volzhs-desktop 4.4.0-59-generic 80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Godot v2.1.2.stable.official

I can't reproduce it.
But I have a lag to switch window while running project.
In this case, I solved it by `use_vsync` OFF at Project Settings > Display

**Comment by volzhs** [comment]
I can reproduce it on Ubuntu 16.04.1.

**Comment by ktksgit** [comment]
Minimal project with Godot_v2.1.2-stable_x11.64 works fine on:
Ubuntu 14.04 64Bit and Intel i7-6700, 16GB, HD Graphics 530
Profiling works, Editor not freezing.
Hardware dependent?

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by DualMatrix** [comment]
Tested in current master, no freeze.

**Comment by akien-mga** [comment]
Thanks for testing.
