### ISSUE TITLE
AudioServer.get_bus_effect_instance(0,0) returns null 

### ISSUE THREAD

**Issue by DarkiStar** [godotengine/godot#76882]
### Godot version

v3.5.2.stable.official [170ba337a]

### System information

Windows 10

### Issue description

var spectrum = AudioServer.get_bus_effect_instance(0,0)

always returns null

Tried on two different computers. 
I added an AudioStreamPlayer unter a root Node2D and imported an mp3 file. The mp3 plays without problems. But the get_bus_effect_instance() does not work.

### Steps to reproduce

func _ready():
var spectrum = AudioServer.get_bus_effect_instance(0,0)

### Minimal reproduction project

func _ready():
var spectrum = AudioServer.get_bus_effect_instance(0,0)

**Comment by AThousandShips** [comment]
Please provide an MRP so we can test this properly including all the project settings

**Comment by DarkiStar** [comment]
My mistake. Forgot to select the Analzyer in the Audio tab.

**Comment by MJacred** [comment]
@DarkiStar: You have the edit rights to close this issue:

If you scroll to the bottom of this page (just below this comment), you should see this
![image](https://github.com/godotengine/godot/assets/6639237/4c6b5d6d-8f74-4a9d-b7e3-85bd0cef13fd)

Click it and this issue will be closed : )
