### ISSUE TITLE
BoneMap retarget causes incorrect non-skinned mesh rotation.

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#76891]
### Godot version

4.1.dev 6980b2bf1

### System information

Windows 10

### Issue description

rest fixer does not handle rotation of child bones/meshes of rotated human bones during the retargeting process.

It also prints out this error for every non-skinned mesh:
```
ERROR: Condition "!skin.is_valid()" is true. Continuing.
   at: PostImportPluginSkeletonRestFixer::internal_process (editor\import\post_import_plugin_skeleton_rest_fixer.cpp:117)
```
![comparison of FBX, rotated bonemap, original, differently rotated bonemap](https://github.com/godotengine/godot/assets/39946030/511a8437-064b-42ba-ad57-e138d161f404)
From left to right: 1. FBX2glTF conversion; 2. BoneMap applied with different rest rotation. 3. original model with no BoneMap; 4. BoneMap applied with the original rest rotation.

Expected output is the third model in the screenshot at origin. The effect on the child meshes seems to be the same regardless of the original rest pose. It seems scale is somehow also reset to 1,1,1. you can see the leftmost model was an FBX conversion with 100x scale. This causes the child meshes to become 1% as large as they should be (basically invisible)

### Steps to reproduce

1. open the scene.
2. errata: I lost the .import for `_rotated_fbx2gltf.gltf` when zipping the project. To reproduce this model, double click to the advanced importer. Assign a BoneMap. Then open the bonemap and assign a SkeletonProfileHumanoid.
3. Observe the import setting of each gltf file. Normally, there are rings around the neck, arms and tail. After BoneMap is applied, the meshes are positioned and rotated incorrectly.

### Minimal reproduction project

[BoneMap_non_skinned.zip](https://github.com/godotengine/godot/files/11437148/BoneMap_non_skinned.zip)
(Model is permissively licensed and available from https://booth.pm/ja/items/2019040 "2A-7-4 / XXXX Coolk")

**Comment by Calinou** [comment]
cc @TokageItLab
