### ISSUE TITLE
Godot 4 SSS did nothing

### ISSUE THREAD

**Issue by Intervel** [godotengine/godot#76901]
### Godot version

Godot_v4.0.2-stable_win64

### System information

Windows 11,  Rtx 3090

### Issue description

how does SSS even works?

what type of texture to input? black/white mask? 

need guidance. cant find any tututorial.

watch : https://www.veed.io/view/6b608415-a0c7-452e-ade7-ab84ee79ce72?sharingWidget=true&panel=share

### Steps to reproduce

none

### Minimal reproduction project

none

**Comment by AThousandShips** [comment]
Please use the other community channels for this, this is not a help forum, if you discover a bug in your search come back and update this

**Comment by AThousandShips** [comment]
Please use other community channels for help and guide, this is for bugs

If the documentation is missing or there are bugs that does need to be fixed however

**Comment by AThousandShips** [comment]
The video doesn't work btw

Does SSS mean subsurface scatter?

**Comment by Intervel** [comment]
yup! its working here, just click it

**Comment by AThousandShips** [comment]
No, it does not work, please don't declare to me that it does when you do not know that it does 🙃 

![Screenshot](https://github.com/godotengine/godot/assets/96648715/13fd8493-eb97-4f80-a843-a14dc665ad21)

**Comment by Intervel** [comment]
https://github.com/godotengine/godot/assets/86478025/ef5c848c-6292-4f17-bb40-78a2f7c4dd0d

**Comment by AThousandShips** [comment]
The documentation is somewhat lacking but the texture should provide the intensity of the scattering, in the red channel, according to the [documentation](https://docs.godotengine.org/en/stable/classes/class_basematerial3d.html#class-basematerial3d-property-subsurf-scatter-texture)

**Comment by AThousandShips** [comment]
It even says "keep editing" so you need to publish it after you sign up

**Comment by AThousandShips** [comment]
It works now

But you only look at it from below, are you expecting SSS to let light through the surface?

**Comment by Intervel** [comment]
isnt that how it works?

**Comment by AThousandShips** [comment]
I'm not sure but I think it has to do with how light goes into the surface before being reflected back, like with human skin

**Comment by AThousandShips** [comment]
I don't know how correctly it's set up on your case either sorry

**Comment by AThousandShips** [comment]
It does seem like it is supported but I still don't know if your setup is correct as you've not provided an MRP

**Comment by AThousandShips** [comment]
There are some issues with banding on SSS, check #75861

**Comment by adamscott** [comment]
> how does SSS even works?
> what type of texture to input? black/white mask?
> need guidance. cant find any tututorial.

Closing, as this isn't an issue. @AThousandShips's recommendation is valid, there are [community channels](https://godotengine.org/community) for these kind of "issues".
