### ISSUE TITLE
WorldBoundaryShape2D doesn't work when moving a little farther than 11000px away

### ISSUE THREAD

**Issue by hsandt** [godotengine/godot#76917]
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Linux Ubuntu 22.04 with Unity desktop

### Issue description

I'm using WorldBoundaryShape2D to delimit my level area and noticed that at some point, the character can leave the delimited area. I identified the collider to stop working around 11000px away from the center of the WorldBoundaryShape2D, in the tangent direction.

The distance is not as crazy as it seems, esp. when working on a runner-style game where the player character moves in the world (and not the reverse, i.e. obstacles are not coming at the player as some shmups do).

If there are technical reasons for the limitation, then this should be documented so users know they must regularly repeat adding the WorldBoundaryShape2D.

### Steps to reproduce

1. In the MWE attached, I setup a WorldBoundaryShape2D at the origin and several sprites marking milestones of 1000px away from the origin each. The player character is placed near the 11000 milestone to make it easier to test. Also, it is affected by gravity.
2. Run the demo and move right a little beyond the 11000 milestone with the right key.
Expected: character keeps moving on the ground delimited by WorldBoundaryShape2D
Actual: character falls into the ground shortly after the 11000 milestone

![Godot 4 0 2 - WorldBoundaryShape2D stops after 11000px](https://github.com/godotengine/godot/assets/1067772/362ca66d-ebac-46f5-9619-2f1eb675f3fe)

### Minimal reproduction project

[Godot 4.0.2 - WorldBoundaryShape2D doesn't work when very far.zip](https://github.com/godotengine/godot/files/11443680/Godot.4.0.2.-.WorldBoundaryShape2D.doesn.t.work.when.very.far.zip)

**Comment by Calinou** [comment]
Can you reproduce this in 3D?

**Comment by rburing** [comment]
Indeed, here is the AABB of the shape:

https://github.com/godotengine/godot/blob/c80a2b4fe99dcd0bba6fc24ed2748b1474b24448/servers/physics_2d/godot_shape_2d.cpp#L126

😅

**Comment by Calinou** [comment]
Are there any negative consequences to increasing this to much higher values? Would it make the collision less precise around the plane (i.e. "snapping" to coordinates)?

**Comment by awardell** [comment]
It seems odd for WorldBoundaryShape2D to _have_ an AABB, considering it is supposedly "infinite". I suppose it has to in order to be a shape, but ideally there would be some way to make the physics server disregard that and just **always test**. There will almost never be more than 4 WorldBoundaryShape2D at max, and even for angled ones the collision test is trivial.

As is currently, the WorldBoundaryShape2D is somewhat useless for its intended purpose.

**Comment by am4sten** [comment]
Yeah I stumbled upon the same issue in a side scrolling project, it seems that the workaround would be spawning collision shapes every 11k px-ish but not sure how it's sustainable or how the physics server is gonna handle all of that after a while

**Comment by Rip50** [comment]
Hit the same issue when working on my game. Is there any plans to make it **actually** infinite?
