### ISSUE TITLE
When using the color picker, the screen keeps flashing.

### ISSUE THREAD

**Issue by Abab-bk** [godotengine/godot#76912]
### Godot version

4.0.2 Stable

### System information

Windows11, Inter i3-8200, RX580 2048SP, GLES2.

### Issue description

When selecting the dropper button when picking a color, the screen keeps flashing.

### Steps to reproduce

Open up the color picker, click the dropper icon.

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
Duplicate of #74048
