### ISSUE TITLE
Godot crashes when trying to deselect input map name.

### ISSUE THREAD

**Issue by Robotathand** [godotengine/godot#76915]
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

CPU  	Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz  	Base speed:	2.71 GHz 	Sockets:	1 	Cores:	2 	Logical processors:	4 	Virtualisation:	Enabled 	L1 cache:	128 KB 	L2 cache:	512 KB 	L3 cache:	3.0 MB  	Utilisation	7% 	Speed	2.60 GHz 	Up time	3:16:29:24 	Processes	240 	Threads	2298 	Handles	94552

Windows 10

### Issue description

When deselecting an input name it crashed.

https://github.com/godotengine/godot/assets/97321601/eb6dea1c-60ba-46f2-8049-9d038b748694

### Steps to reproduce

https://github.com/godotengine/godot/assets/97321601/2aa981a5-7edb-421d-895e-50e2be7f18dc

### Minimal reproduction project

[New Compressed (zipped) Folder.zip](https://github.com/godotengine/godot/files/11443324/New.Compressed.zipped.Folder.zip)

**Comment by KoBeWi** [comment]
Closing. Comment if you can still reproduce.
