### ISSUE TITLE
Editor ignoring the project setting "initial_position" when launching the game

### ISSUE THREAD

**Issue by felaugmar** [godotengine/godot#76920]
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Windows 10

### Issue description

When `display/window/size/initial_position_type` is equal to `Absolute`, the initial window position is taken from `display/window/size/initial_position`.

But when the editor launches the game, it injects the custom position by command line aguments based in **EditorSettings/Window Placement**, ignoring the project's "initial_position" setting.

The **EditorSettings/Window Placement**'s options are useful, but I feel missing an option to fallback to the **ProjectSettings**' window placement options, instead of overriding it.

### Steps to reproduce

1. Set the project setting `display/window/size/initial_position_type` to `Absolute`;
2. Set the project setting `display/window/size/initial_position` to `x: 50 | y: 50`;
3. Run the game by the editor, notice it starts based from what is configured in **EditorSettings/Window Placement**;
4. If you export the game and run it, the desired behavior is used, starting at `x: 50 | y: 50`.

### Minimal reproduction project

N/A

**Comment by felaugmar** [comment]
Could the solution be an Editor option to not use the **EditorSettings/Window Placement** options and instead let the **ProjectSettings** options be used?

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/71288.

**Comment by Zireael07** [comment]
That issue is closed tho?

**Comment by Calinou** [comment]
> That issue is closed tho?

It is, but that doesn't mean it's not relevant 🙂
