### ISSUE TITLE
get_window_id () function not exposed.

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#76934]
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Windows 11, AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx     2.10 GHz

### Issue description

  The get_window_id () function in the Window class is not exposed and yet nearly every function in DisplayServer pertaining to window management requires a window ID as an argument, however, there's no way to retrieve this information from a window?!?!?

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by gotnospirit** [comment]
What about [DisplayServer::get_window_list](https://docs.godotengine.org/en/stable/classes/class_displayserver.html#class-displayserver-method-get-window-list ) or [DisplayServer::get_window_at_screen_position](https://docs.godotengine.org/en/stable/classes/class_displayserver.html#class-displayserver-method-get-window-at-screen-position) ?

**Comment by Zentropic** [comment]
get_window_list () just returns a bunch of IDs with no way of actually matching them up with a window except via get_window_at_screen_position (), however, that function should not be the default way of getting a window ID, I agree the function should exist for an alternate way.
