### ISSUE TITLE
draw_arc position/coordinate in Instant child doubled

### ISSUE THREAD

**Issue by J-Siu** [godotengine/godot#76944]
### Godot version

v4.0.2.stable.official.7a0977ce2

### System information

MacOS 13.3.1, Apple M2

### Issue description

Referring to https://github.com/J-Siu/circle_and_label.git

Scenes `main`, `circles_draw` and `circles_child` all positioned circles at the same coordinates.

All their labels overlaps, which is correct.

However, only `main` and `circles_draw` circles overlapped. `circles_child` circles, but not label, coordinates are doubled on screen.

### Steps to reproduce

1. git clone https://github.com/J-Siu/circle_and_label.git
2. open in Godot
3. run `main` scene to see all overlapping
4. run `circles_child` to see even `Label` child of `circle` and `draw_arc` are off.

### Minimal reproduction project

https://github.com/J-Siu/circle_and_label

**Comment by Zireael07** [comment]
draw() draws in local coords, not global - this is imho user error

**Comment by J-Siu** [comment]
> draw() draws in local coords, not global - this is imho user error

Scale is not change, so coords should be the same.

**Comment by J-Siu** [comment]
Oh... should use (0,0) inside circle ... Thank you!!
