### ISSUE TITLE
[GDScript] Loading non-existing gdscript returns valid instance.

### ISSUE THREAD

**Issue by zaevi** [godotengine/godot#76941]
### Godot version

4.1.dev

### System information

Win11

### Issue description

I load a non-existing GDScript, but it still returns a valid instance instead of null.
```gdscript
@tool
extends EditorScript

func _run():
	var s = ResourceLoader.load("non_exists.gd", "", ResourceLoader.CACHE_MODE_IGNORE)
	print(s)
	assert(s == null)

```

```
  Attempt to open script 'res://non_exists.gd' resulted in error 'File not found'.
<GDScript#-9223369015982753437>
  res://new_script.gd:7 - Assertion failed.

```

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by zaevi** [comment]
https://github.com/godotengine/godot/blob/fbb1a929a374b3d95c198dd40c896c928d8f6162/modules/gdscript/gdscript.cpp#L2592-L2610
Seems if not exist it will instantiate.  cc @vnen

**Comment by Rindbee** [comment]
Currently, there doesn't seem to be a distinction between errors in parsing and errors in `load_source_code()`. When `load_source_code()` fails, `GDScriptCache::get_shallow_script()` should return `Ref<GDScript>()` without caching.

**Comment by KoBeWi** [comment]
This leads to a bug where opening a scene with missing script dependencies will open them as empty scripts.
