### ISSUE TITLE
Connecting a signal to a method fails to generate template reciever in an external editor

### ISSUE THREAD

**Issue by Juris-S** [godotengine/godot#76943]
### Godot version

4.0.2.stable.official (7a0977ce2)

### System information

Windows 10 Pro, 10.0.19045

### Issue description

When connecting a signal to a method, [the receiver method should be automatically appended to the associated script](https://docs.godotengine.org/en/stable/getting_started/first_3d_game/05.spawning_mobs.html#:~:text=This%20will%20take%20you%20back%20to%20the%20script%2C%20with%20a%20new%20empty%20_on_mob_timer_timeout()%20function.); albeit empty.

When using an external editor (VsCode)
![image](https://github.com/godotengine/godot/assets/31705360/f8eb9bc5-a6cb-48cb-9e2a-6722b0808d05)

The empty template isn't added to the script, and it remains unchanged:
![Godot_v4 0 2-stable_win64_7tDuJf1kg2](https://github.com/godotengine/godot/assets/31705360/87d6bf88-ac3c-4fcd-a3af-4e41d5335d17)

### Steps to reproduce

**Pre-requisite**
Set up an external editor such as VsCode, or Notepad.

2. Create a component that has signals which can be added to a script
3. Select a signal and open the "Connect a Signal to a Method" modal window
4. Select a node with a script that can host the receiver method
5. Press "Connect."
6. Observe no empty receiver method is added to the script

### Minimal reproduction project

N/A

**Comment by Rindbee** [comment]
Is the LSP connected?

**Comment by Rindbee** [comment]
Use [godot-tools](https://marketplace.visualstudio.com/items?itemName=geequlim.godot-tools) in vscode, and configure `network/language_server/remote_port` in godot's editor settings.

![0](https://github.com/godotengine/godot/assets/30386067/642d45f0-48c0-4563-a076-acf53f511421)
