### ISSUE TITLE
Ctrl-Home / Ctrl-End does not deselect text selection in editor

### ISSUE THREAD

**Issue by chanon** [godotengine/godot#7694]
**Operating system or device - Godot version:**
Windows 10, Godot 2.1.2 branch custom build

**Issue description:**

When you select text in any text editor (ex. Notepad / Sublime Text) and hit Ctrl-End the cursor will go to the last position in the text file and any text that was selected will be deselected. Godot's editor however does not deselect the selected text.

**Steps to reproduce:**
- Select text in Godot GDScript editor.
- Hit Ctrl-End or Ctrl-Home
- Notice that the text is still selected

**Comment by Hinsbart** [comment]
Fixed via #7712, so closing this..
