### ISSUE TITLE
The brackets code prompt is not as good as it used to be.

### ISSUE THREAD

**Issue by 451507056** [godotengine/godot#76958]
### Godot version

4.0.2.stable

### System information

windows10，gtx1050ti

### Issue description

The brackets code prompt is not as good as it used to be.

### Steps to reproduce

![3 5 1](https://github.com/godotengine/godot/assets/6943500/10d66f2c-51a7-4a0e-a25a-00ad20ebc42e)
![4 0 2](https://github.com/godotengine/godot/assets/6943500/5c9023dc-8767-42ae-a6f3-91027f7061ff)
Code hints are still available in 3.5.1, but not after 4.0.

### Minimal reproduction project

none

**Comment by 451507056** [comment]
I'm sorry, I don't know if I rewrote the question, because I just sent one and it's not in my record again.

**Comment by Zireael07** [comment]
duplicate of 76955 is what @AThousandShips means

**Comment by 451507056** [comment]
Ah, I see that. I'm sorry I opened the question again.
