### ISSUE TITLE
Random stop when starting any project

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#76965]
### Godot version

4.0.3rc1

### System information

Fedora linux f37 (GNOME DE),
Video: AMD Radeon,
CPU: AMD Athlon,
Mem: 6Gb x 128Gb

### Issue description

When I try to edit any project to save changes or change parameters, godot freezes in the process and does not respond to events. I trace this bug with `sudo strace -p pid_godot -o trace.log` and pasted on https://pastebin.com/V5dGbUiN

### Steps to reproduce

I opened the Projects menu and selected any project. I edited the code, added keys, created objects.

### Minimal reproduction project

N/A

**Comment by Zireael07** [comment]
There's no 4.0.5, I assume you mean 4.0.3rc1

**Comment by azr13ll0** [comment]
changed

**Comment by KoBeWi** [comment]
> I trace this error https://pastebin.com/V5dGbUiN

This does not point to any file.

**Comment by AThousandShips** [comment]
Closing as OP is ghost and file is invalid
