### ISSUE TITLE
Godot 2.1.2: Project Settings Crash

### ISSUE THREAD

**Issue by toliaferrode** [godotengine/godot#7696]
**Operating system or device - Godot version:**
Ubuntu, Godot 2.1.2

**Issue description:**

Trying to check around in the Project Settings window usually freezes and crashes Godot. Some times it's the first check, some times the second or maybe even third.

**Steps to reproduce:**
Check around in Project Settings.

**Link to minimal example project:**
:

**Comment by cbscribe** [comment]
Happening here too.

**Operating system or device - Godot version:**
OS X 10.11.6, Godot 2.1.2

**Steps to reproduce:**
Create new project, add one node and save scene.  Then click on project settings and check  any of the following boxes under "Display" for an instant crash:
* fullscreen
* allow_hidpi

Happens every time I open the project.  In addition, this has happened under other projects, and with other project settings options.  I went ahead and made a repository for the simple 1 node project below.

**Link to minimal example project:**
https://github.com/cbscribe/godot_crash

**Comment by bojidar-bg** [comment]
Can confirm for `fullscreen` with `debug_release` builds both with `using_clang=no` and `using_clang=yes` on Godot 2.1.2 and Godot 2.1/HEAD.
Can't confirm with `target=debug` + `using_clang=no`, or with 3.0/HEAD.

**Comment by akien-mga** [comment]
Fixed by #8240.
