### ISSUE TITLE
ImageTexture class reference has a pointless section

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#76971]
### Godot version

4.0.2

### System information

Ubuntu 22.04.1 LTS

### Issue description

![image](https://github.com/godotengine/godot/assets/85438892/47baf956-c28c-4f8f-aed5-c515528d4ed6)

Normally, the "Property descriptions" section would be skipped in this case, but because there's an overridden property (which doesn't need a description) this section shows up without needing to.

### Steps to reproduce

Open ImageTexture's class reference.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
This should be the relevant section:
https://github.com/godotengine/godot/blob/fd4a06c51555904104b18494d0224f450d74fe2a/editor/editor_help.cpp#L918-L930
