### ISSUE TITLE
Tree: Adding TreeItems does not impact Tree's minimum size, leading to trouble with containers

### ISSUE THREAD

**Issue by whogben** [godotengine/godot#76972]
### Godot version

4.0.2.stable

### System information

Windows 11

### Issue description

Tree's minimum size remains 0,0 despite adding items to the tree.

Expectation:  Adding items to a tree will increase it's minimum size > 0 pixels.

Result:  Adding items to a tree does not impact on its minimum size, and a tree inside a container such as a VBoxContainer cannot be fit to it's content, and must either be forced to size 0,0 by the container, or take up all available space with SIZE_EXPAND_FILL

### Steps to reproduce

Create a new scene descending Control, and paste the script from minimal reproduction project into a built in script on the root control.

Things I've tried to try and get the tree to have a minimum size > 0:
* turning off clip_contents, and turning off column clipping
* setting custom_minimum_width on tree item columns
* adding a texture button to a tree item
* calling update_minimum_size on the tree after adding the items

### Minimal reproduction project

```
extends Control

func _ready():
	
	var tree = Tree.new()
	var root = tree.create_item()
	tree.hide_root = true
	var child1 = tree.create_item(root)
	var child2 = tree.create_item(root)
	var subchild1 = tree.create_item(child1)
	subchild1.set_text(0, "Subchild1")
	
	add_child(tree)
	print('size ' + str(tree.size))
```
	
(The tree creation code is copied from the documentation here https://docs.godotengine.org/en/stable/classes/class_tree.html )

**Comment by YuriSizov** [comment]
Tree is a scrollable control. It has to have a minimum size to be displayed properly. If you think there is a use case for disabling the scroll and making it change its size with content, then please [open a proposal](https://github.com/godotengine/godot-proposals) and describe your use case.
