### ISSUE TITLE
Picker tool disappears in the Paint tab of TileSet

### ISSUE THREAD

**Issue by dhyces** [godotengine/godot#76984]
### Godot version

4.0.2 Stable

### System information

Windows 10 21H2, AMD Ryzen 7 4800H with Radeon Graphics 2.90 GHz, 

### Issue description

The "Picker" tool in TileSet -> Tiles -> Paint disappears under certain conditions, such as switching to Select and selecting a tile. It reappears when using ctrl-z

### Steps to reproduce

1. Import a tile sheet
2. Create a physics layer for the TileMap
3. Select the tile sheet in TileSet
4. Select the "Paint" tab and choose the physics layer
5. Paint on a tile
6. Select the "Select" tab and click on a different tile
7. Select the "Paint" tab again

### Minimal reproduction project

[BugReport.zip](https://github.com/godotengine/godot/files/11458435/BugReport.zip)

**Comment by KoBeWi** [comment]
Seems the same as #71008 and #75448
Already fixed in 4.1

**Comment by KoBeWi** [comment]
I'll close this as resolved.
The fix could be cherry-picked to 4.0, but it's not known which PR exactly fixed this. Someone'd have to bisect the issue.
