### ISSUE TITLE
Setting y sort to true stops modulate from affecting children

### ISSUE THREAD

**Issue by Crystalwarrior** [godotengine/godot#76992]
### Godot version

4.0.2

### System information

Windows 10, Compatibility/Forward+, NVIDIA GeForce GTX 1050

### Issue description

If Y-Sort is enabled on a Node2d, Modulate stops working on its children.

### Steps to reproduce

1. Create a Node2D
2. Set modulate to some color, like red
3. Add a child to that node. It will be colored red like its parent
4. Enable Y-Sort. The child is no longer red.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Duplicate of #63994?
