### ISSUE TITLE
GDExtension: passing Image to ImageTexture with ImageTexture::update is too slow

### ISSUE THREAD

**Issue by DetermLZ** [godotengine/godot#76994]
### Godot version

4.0.2-stable

### System information

Win 11, Intel i7-12700, RTX 3060Ti

### Issue description

Hello.

I am currently working on image rendering with GPU with C++ GDExtension. An important step in the project is **passing Image data to ImageTexture** before uploading to the shader. 

But I found this conversion takes too much time in each frame with low efficiency. For a 1920x1080 image, it takes about **32 to 38 milliseconds to update the ImageTexture**. While in Godot 3.5, the same process takes **less than 1 millisecond**.

![image](https://github.com/godotengine/godot/assets/111273475/33cc7ccb-4739-4896-98fd-cbdd9281d453)

Any help will be appreciated.

### Steps to reproduce

1. clone [godot-cpp repository](https://github.com/godotengine/godot-cpp.git)
2. checkout version 4.0.2-stable
3. go to folder godot-cpp\test\src and replace 'example.cpp' and 'example.h' with the following files
[example.zip](https://github.com/godotengine/godot/files/11461428/example.zip)
4. run 'scons' to build the GDExteion dll file and run the demo project

### Minimal reproduction project

PLease follow the above descriptions to reproduce the project.

**Comment by bitsawer** [comment]
Also, some image formats have to be converted internally before they are used, depending on renderer. Try using `FORMAT_RGBAF` instead of `FORMAT_RGBF` and just ignore the alpha channel. This might avoid having to convert the data every time you update the texture.

**Comment by DetermLZ** [comment]
> Also, some image formats have to be converted internally before they are used, depending on renderer. Try using `FORMAT_RGBAF` instead of `FORMAT_RGBF` and just ignore the alpha channel. This might avoid having to convert the data every time you update the texture.

Thanks so much! This is actually what I need. 
After changing the format to `FORMAT_RGBAF`, the conversion time surprisingly decreased to 2 or 3 milliseconds.

But still, I think this is a bug for GDExtension, since this can still occur in some situations.

**Comment by lyuma** [comment]
Still reproducible on Godot 4.1 . RGB format is way slower than equivalent R, RG and RGBA formats.

Here is my GDScript MRP:
```gd
extends Sprite2D
var image: Image
var image_texture: ImageTexture

# Called when the node enters the scene tree for the first time.
func _ready():
	image = Image.create(4096,4096,false,Image.FORMAT_RGBA8)
	image.fill(Color.TURQUOISE)
	texture = ImageTexture.create_from_image(image)
	print(texture)
	self.texture = texture


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(_delta: float):
	var time_start: int = Time.get_ticks_usec()
	texture.update(image)
	var time_end: int = Time.get_ticks_usec()
	print(str(0.001 * (time_end - time_start)) + " ms")
```

Data for 4kx4k texture:
```
RF: 21ms
RGF: 48ms
RGBF: 650ms
RGBAF: 100ms

RH: 10ms
RGH: 20ms
RGBH: 800ms
RGBAH: 48ms

R8: 6.0ms
RG8: 12ms
RGB8: 51ms
RGBA8: 21ms
```
You can see the RGB formats consistently stand out as outliers.

perhaps caused by misalignment as the GPU will want to align them to multiples of 4 (though I'm surprised about RGBF, since the floating point type should guarantee they are word aligned)

I'm just surprised that RGB is up to 10 times slower than the equivalent RGBA

**Comment by Zylann** [comment]
Would there be a relation to the fact RGB doesnt actually exist as a format in the rendering driver?
