### ISSUE TITLE
Cells can't be changed in runtime in a Tilemap using TileSetScenesCollectionSource 

### ISSUE THREAD

**Issue by FarbrorMartin** [godotengine/godot#77003]
### Godot version

4.0-stable

### System information

Windows 10, Forward+, Intel HD 620

### Issue description

A Tilemap2D with scene tiles in a TileSetScenesCollectionSource is not affected by set_cell, erase or similar functions.
The tiles can be looped through with get_used_tiles, but can't be updated from script.

### Steps to reproduce

Create a tile scene and a tilemap. Add a tileset and add a TileSetScenesCollectionSource. Add the scene to the tileset.
Draw tiles.
Add a script to the tilemap.
In the process function do a `clear()`
Expected result: the tiles disappear when you run the game
Actual result: the tiles are not affected.

If you try the same thing with a regular TileSet, everything works as expected.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Related #74867
