### ISSUE TITLE
NoiseTexture2D changed size seamless shows seam?

### ISSUE THREAD

**Issue by rakkarage** [godotengine/godot#77008]
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Windows 11, Core i5-12400F, RX 6600

### Issue description

the noise looks good @ 512x512 but as you lower the size the seam becomes more and more pronounced?
![NOISE](https://github.com/godotengine/godot/assets/962340/67158871-b97b-4714-b04a-37e34202639d)
sorry if I am doing something wrong?

### Steps to reproduce

- set size to 128x128 or lower
- notice seam
- adjust skirt not fix

### Minimal reproduction project

https://github.com/rakkarage/NewNewNew

**Comment by Calinou** [comment]
This is expected. Lower blend skirts blend over a smaller surface, which makes the seam more visible. Higher values do a better job at hiding the seam, but will cause the texture to lose some contrast.

**Comment by clayjohn** [comment]
I found by trial and error that you need at least 10 pixels to have a decent blend (with the default fractal simplex noise, for other noise types more may be needed). It would be nice to investigate a better approach to seamless noise generation, but for now this limitation should be documented

**Comment by rakkarage** [comment]
Sorry if I was unclear lowering the size of the texture (not seam) causes the seam to show...
So only 512x512 noise texture is usable? What if I need smaller?

**Comment by clayjohn** [comment]
> Sorry if I was unclear lowering the size of the texture (not seam) causes the seam to show... So only 512x512 noise texture is usable? What if I need smaller?

You increase the size of the seam if you decrease the size of the texture. The code is exactly the same as in Godot 3. The seam is a percentage of texture size. So at 512 resolution, the seem is 51 pixels wide. If you decrease to 64x64, the seam is only 6 pixels wide so you need to increase the proportion of the seam to make it more smooth

**Comment by rakkarage** [comment]
![old](https://github.com/godotengine/godot/assets/962340/71d423d4-893f-46b6-98db-420e02d757b1)

![new](https://github.com/godotengine/godot/assets/962340/93a0e5d8-2b04-44a5-827c-c1ec608dcfa3)

**Comment by AThousandShips** [comment]
Does it show up in 3.x if the noise is more similar, those two cases are quite different and seams should show up more clearly in the second example

**Comment by rakkarage** [comment]
how could they be more similar? both default settings with only size and seamless changed?

**Comment by AThousandShips** [comment]
The detail on the second noise is much higher, it goes from deep black to bright white

**Comment by Calinou** [comment]
Godot 3 used OpenSimplexNoise which has a "true" seamless mode, but OpenSimplexNoise is slower and more limited.

Godot 4 uses FastNoiteLite which lacks a seamless mode, so it's emulated by blending two layers together (like GIMP's Make Seamless filter). However, FastNoiseLite is faster and more powerful.

**Comment by AThousandShips** [comment]
To be clear I'm not refuting the difference, just saying I can't really tell how much is that the noise in 4.x has much more contrast

**Comment by rakkarage** [comment]
ok thanks for the help understanding
sorry i could not understand what the blend skirt was and why it was moving from center to edge
it can look nice with small fine tuning...
maybe there is a way to set the blend skirt automatically based on size so it always looks nice?

**Comment by Calinou** [comment]
There could be an additional **Seamless Min Blend SKirt** property that defines a value in pixels, but I feel the NoiseTexture inspector is already exposing a lot of properties. It may be better to just document this in the class reference.

**Comment by clayjohn** [comment]
> ![old](https://user-images.githubusercontent.com/962340/238044837-71d423d4-893f-46b6-98db-420e02d757b1.gif)
> 
> in 3 small seamless is seamless
> 
> ![new](https://user-images.githubusercontent.com/962340/238044864-93a0e5d8-2b04-44a5-827c-c1ec608dcfa3.gif)
> 
> in 4 not

Looking through the code and I see I was totally mistaken. I thought the approach used in 4.0 was backported for some reason, but it hasn't been. So you are right, in 3.x it works without any fuss and you don't have to alter the blend skirt at all. In 4.0 it works okay, but you have to increase the blend skirt for smaller textures.

**Comment by rakkarage** [comment]
maybe this changes the "hierarchy of importance" for parameters to get_seamless_image since u have to pass two optional to get to skirt? idk i saw someone use this term and thought i recognized the situatiuon

    var image1 := _noise.get_seamless_image(_size, _size, false, false, 0.333)

or maybe the other parameters are still more important tho i have never used in my limited 2d experience
