### ISSUE TITLE
Await timer does not work in a for loop

### ISSUE THREAD

**Issue by henryernice** [godotengine/godot#77002]
### Godot version

4.0.2.stable.official [7a0977ce2]

### System information

MacOS Ventura 13.3.1, 3.4 GHz Quad-Core Intel Core i5

### Issue description

This is my first bug report so i hope its valid.

Im making a screenshake effect with a for-loop and the new await keyword but the debug window just freezes or just completely skips the code.

### Steps to reproduce

func _ready():
	for i in 10:
		print(i)
		await get_tree().create_timer(1).timeout

### Minimal reproduction project

[test project.zip](https://github.com/godotengine/godot/files/11464486/test.project.zip)

**Comment by AThousandShips** [comment]
Can you confirm this happens only if it is in a loop? Does it happen if done in some other context than `_ready`?

**Comment by felaugmar** [comment]
@henryernice 

There is a logic problem in your code:

``` gdscript
await get_tree().create_timer(1.0/i).timeout
```

The first time it get's there, `i == 0`, resulting in "infinite float" because you cannot divide by zero, so the `timeout`'s signal will never be called.

**Comment by AThousandShips** [comment]
Didn't look in the MRP so didn't see the code was different from the issue report

**Comment by henryernice** [comment]
Sorry i didnt know that was a problem. The real problem was here:

func screenshake(amount):

	randomize()
	var strenght = amount
	var cam_pos = $Head/Camera3D.position
	var xnoise = FastNoiseLite.new()
	var ynoise = FastNoiseLite.new()
	xnoise.seed = randi()
	ynoise.seed = randi()
	xnoise.frequency = 4
	xnoise.fractal_octaves = 5
	xnoise.fractal_lacunarity = 6
	ynoise.frequency = 4
	ynoise.fractal_octaves = 5
	ynoise.fractal_lacunarity = 6
	
	for i in range(int(amount)):
		$Head/Camera3D.position = cam_pos + (Vector3(xnoise.get_noise_2d(i, 0), ynoise.get_noise_2d(i, 0), 0) * amount*0.03/i)
		await get_tree().create_timer(1.0/amount).timeout


	$Head/Camera3D.position = cam_pos

Sorry if this is just a waste of your time, next time i will ask on the Godot forums first
