### ISSUE TITLE
CharacterBody3D with base script template lags on collision

### ISSUE THREAD

**Issue by brickedware** [godotengine/godot#77020]
### Godot version

4.0.2.stable (7a0977ce2)

### System information

Windows 10, Intel Core i5-9600K, Radeon Pro 580X, Vulkan

### Issue description

Everything starts lagging when the player collides with the platform for some reason after I use the base template script, even though it doesn't lag at all in other user demos I've tested. It only seems to lag when I add the script for some reason.

https://github.com/godotengine/godot/assets/106000036/36f3c484-6c3f-4176-9be9-7855475c7a35
The video, for some reason, also lags when the player _isn't_ on the platform, (something must have been up with OBS) but it does lag as the video shows when the player is on the platform

Not sure if there's a simple step to fix this but I've been having this problem since I installed version 4 recently and couldn't find any solution on line, no matter how many keywords I add.

### Steps to reproduce

Create a MeshInstance3D and assign a StaticBody and CollisionShape. Create a CharacterBody3D and assign a MeshInstance and CollisionShape. Give the CharacterBody a script, use the Basic Movement template, add camera, test scene.

### Minimal reproduction project

[scene.zip](https://github.com/godotengine/godot/files/11467677/scene.zip)

**Comment by brickedware** [comment]
I found out that the problem was the CollisionShape. Just for future reference, if this happens to anyone else, remember to choose CapsuleShape for the CollisionShape instead of making it from the mesh. This seems to cause an issue and make everything lag when colliding with other objects.

**Comment by Zireael07** [comment]
@brickedware making the shape from the mesh makes it too complex - this is a known already reported issue. Unless you really really need to make it from the mesh, using built-in shapes is in general a good rule of thumb (is this documented prominently enough in the physics docs pages though?)
