### ISSUE TITLE
Normals inverted on mirrored objects

### ISSUE THREAD

**Issue by lw64** [godotengine/godot#77032]
### Godot version

4.0.2

### System information

Arch Linux

### Issue description

I have modeled a scene in blender. One object has a mirror modifier. So the texture gets also mirrored. The problem is that the normal map is inverted on the mirrored side like this:

![grafik](https://github.com/godotengine/godot/assets/80385965/17f6176a-ce50-4a3d-b28f-715637e51006)

But it should be like this:

![grafik](https://github.com/godotengine/godot/assets/80385965/4eb35694-4e40-4700-ac62-5ff1286b79a3)

The issues appears when importing the scene as a .blend file and as well when importing from a gltf file that was exported from blender previously.
Other 

Inverting the y axis in the import settings of the normal map texture doesn't work either. Both sides get inverted and they are still different.

### Steps to reproduce

Just import such a scene and look at it in the editor view.

### Minimal reproduction project

[issue_test.zip](https://github.com/godotengine/godot/files/11469735/issue_test.zip)

**Comment by smix8** [comment]
Blender modifiers are blender specific. They do not exist in the real world outside of Blender.

Hence why they do not work in nearly all cases when exported, same with Blender shader nodes that go beyond the very PBR material basics.

All Blender modifiers need to be applied / baked to a mesh / texture before exporting. Some addons do this for you behind the scene before exporting but in most cases you need to apply all your modifiers manually.

**Comment by lw64** [comment]
I applied all modifiers on export. The mirror modifier is just what I found caused the issue. As I said the exported glb file is corretly rendered by other 3d viewers. just not godot.

**Comment by lw64** [comment]
The texture is only baked from one side of the mirrored mesh, but as the texture coordinates get also mirrored it is not a problem.

**Comment by lw64** [comment]
I am not sure if it is related, but the texture of the object also begins to flicker if looked at from a nearly 90° angle. Its especially noticable if the object has a emission map. The part that flickers has no emission though, but the flickering appears in the emission color. I my case its white:

![grafik](https://github.com/godotengine/godot/assets/80385965/de8fc1d5-049b-4a49-98ff-7d469fe08d35)

It appears also when turning the normal map of.

**Comment by lw64** [comment]
> the texture of the object also begins to flicker if looked at from a nearly 90° angle

I think this is because of specular antialiasing. After turning on TAA it descreased significantly.
