### ISSUE TITLE
Changes' names don't appear in History dock when using a language other than English

### ISSUE THREAD

**Issue by BSSM7** [godotengine/godot#77043]
### Godot version

4.1 dev2, 4.0.3

### System information

Windows 10, ryzen 5900x, radeon 6950xt (driver: 23.2.2)

### Issue description

Hello there,

I'm working on Godot editor to translate it to Arabic, but I noticed 3 or 4 bugs in History block in the editor:

- Godot history doesnt show full name for changes record.
- Sometime Godot history records a change but with "blank name".
- In 4.1 dev2: When I "**hover**" over a change name in History it (the word itself or the name of record) moves forward quickly until it disappears.
- in 4.0.3 rc1: When I "**click**" on a change in History it moves one step forward. so, one step for each click.
- Sometime when I click on a record in History, Godot crashs. I think this crash is related to these bugs.

Note: those bugs just happen in Arabic version of Godot, English version works fine.
I will attach a captured video to clarify.
Also, Im sorry to report more than a bug in one issue but they seem related.
 

https://github.com/godotengine/godot/assets/121864036/1530ef49-df4f-46db-918f-e65d8d7978f9

### Steps to reproduce

- open Godot editor (Arabic version).
- do any change on your project.
- go to History block to go back to some previous changes.

### Minimal reproduction project

N/A

**Comment by BSSM7** [comment]
I have just tried Godot editor in Hebrew language, and I found the same problem. therefore, this issue is related to RTL languages.

**Comment by akien-mga** [comment]
CC @bruvzg @KoBeWi
