### ISSUE TITLE
Tile Custom Data cleared when selecting "Local to Scene"

### ISSUE THREAD

**Issue by jjcard** [godotengine/godot#77045]
### Godot version

4.01

### System information

Windows 10

### Issue description

It seems a tiles Custom Data is cleared/not set when "Local to Scene" is enabled for the TileMap in the Resource section. At least the custom data isn't set by the time of the _ready function in the script attached to the TileMap.

### Steps to reproduce

create TileMap and tileset with custom data and attached script. in _ready method attempt to read custom data from a used cell. 

In Attached project run it. It will print_debug if it found custom data or not. "Local to Scene" is enabled so it will not find the custom data.

### Minimal reproduction project

[TileMapCustomDataLocalBugReproduce.zip](https://github.com/godotengine/godot/files/11470771/TileMapCustomDataLocalBugReproduce.zip)

**Comment by AThousandShips** [comment]
Can confirm, and adding that the error is that the `TileData` doesn't have a valid `TileSet` set, seems to be due to copying being incorrectly handled somewhere

**Comment by jjcard** [comment]
if someone has pointers to where to look for the copying for local resources, I might try and investigate it. Never contributed to Godot before, but willing to look into it.

**Comment by AThousandShips** [comment]
Looking at `TileSet` would be a pretty simple start no? https://github.com/godotengine/godot/blob/master/scene/resources/tile_set.cpp
