### ISSUE TITLE
Godot will not display an asset folder in `FileSystem` if there is a `project.godot` file in the folder

### ISSUE THREAD

**Issue by slo64** [godotengine/godot#77050]
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Windows 10 Home 22H2

### Issue description

Godot will not display an asset folder in `FileSystem` if there is a `project.godot` file in the folder.
Which might be a sound idea to prevent the user from messing with another project's resources, but as it is now the case of a disappearing folder is both confusing and not really searchable as a problem.
I suggest it should be displayed in a way that makes it clear that something is wrong with the folder - greyed out or in cursive, or with a special icon.
![Screenshot 2023-05-14 065128](https://github.com/godotengine/godot/assets/37928431/ce771f26-22f1-45b0-a341-e65b624d90a3)

### Steps to reproduce

1. Create a new project.
2. Create a new resource folder with any name via the FileSystem tab.
3. Open the new resource folder using the `Open in file manager` option in FileSystem.
4. Drop a copy of `project.godot` into the new resource folder.
5. The new resource folder is now gone from the FileSystem tab and no explanation or indication is provided.

### Minimal reproduction project

[Invisible Assets.zip](https://github.com/godotengine/godot/files/11471096/Invisible.Assets.zip)

**Comment by AThousandShips** [comment]
While I think a warning of some kind would be useful, I'm not sure in what case this would happen without the user knowing what they're doing to warrant adding the functionality to make you notice it is wrong

**Comment by AThousandShips** [comment]
For example it also just skips directories with a `.gdignore` in it, not showing up, which is appropriate

**Comment by AThousandShips** [comment]
And users who for one reason or another intentionally put a project under another project would probably be annoyed by the folder taking up space in the interface

**Comment by slo64** [comment]
1. "No one would do this and not notice" - is simply not a way for a progammer to think. If the product _is_ being used - someone would do this and probably more than once.
2. Nothing is done to communicate to the user that this would or should happen. Because the FileSystem panel is explicitly called FileSystem. It displays the contents of the file system.
3. Therefore if a FileSystem panel does not properly display the contents of the file system it is a bug.
4. Users who intentionally put a project under another project - they probably want to compile a bunch of smaller projects into a larger project. For this purpose the folders must be visible and not hidden. Unless they were hidden intentionally. 
5. The functionality for hiding folders is already explicitly provided by .gdignore.
6. It is far easier to google "how to hide a folder" than "where did it go". So making it a default behavior might not be the best idea.
7. Overall this behavior breaks the principle of least astonishment for UI design. And should be corrected.

**Comment by AThousandShips** [comment]
> It is easy to do accidentally.

I disagree, when would a user copy an entire project into another and not realize it?

> Therefore if a FileSystem panel does not properly display the contents of the file system it is a bug.

No, then the same behavior with `.gdignore` would be a bug, it also does not show `.godot`

> they probably want to compile a bunch of smaller projects into a larger project

This is not supported, and should not be supported, this would mean messy situations with imported resources, it is simply not supported to have projects within projects

> Unless they were hidden intentionally.

If you for some reason put a project inside another that would be the assumption

**Comment by AThousandShips** [comment]
The only change I think is reasonable is to add a note about it in the documentation, [here](https://docs.godotengine.org/en/stable/tutorials/best_practices/project_organization.html#ignoring-specific-folders)

**Comment by slo64** [comment]
> I disagree, when would a user copy an entire project into another and not realize it?
Almost always.

Most of the users who copy a project into another project would want to use it there in some way.
Most of them do not yet realize that doing so will make their files disappear from view.
And if the copying was done months ago - this would completely baffle them when it happens.

> No, then the same behavior with .gdignore would be a bug, it also does not show .godot

No it would not, just as hidden files existing is not a bug. What was explicitly hidden may stay hidden unless stated otherwise.
What wasn't explicitly hidden - should not be hidden. Worked that way since DOS and Unix.

> This is not supported, and should not be supported, this would mean messy situations with imported resources, it is simply not supported to have projects within projects, why should a folder that isn't part of the project be visible?

First, this should be supported, because this is how humans work. Combining parts to make a bigger whole is a very natural and intuitive thing to do.
Second, the very act of copying something into the project communicates the intention to make it part of the project. And so it should be visible. Maybe not usable, but at least visible.
And third, now we have messy situations with disappearing folders instead. Not a great trade off.
If nesting projects is not allowed at all, this warrants for a full blown error message. Or at least a warning.

> If you for some reason put a project inside another that would be the assumption

So I present you with the user A. Who is a highschooler, new to programming and Godot.
And who is copying his or her fist project "bouncing_ball" into a new larger project called "ball_pit" to use it as a resource.
Which should be quite a likely occurence.

I fail to imagine the user B, who is copying a project into another project with the intention of never using it ever.
And if there is one, I fail to see how it would be more likely to happen than the situation with user A.
The assumption has no ground.

**Comment by AThousandShips** [comment]
> First, this should be supported

Simply: No, it shouldn't

It doesn't make sense, projects are self-contained, have their individual resource, settings, and cache data that is for one project on its own

It also won't work because of the system for importing resources, they are given unique identifiers and storage data, if project A contains project B then how do you handle the importing of resources in B while still accessing them in A

> this warrants for a full blown error message. Or at least a warning.

Sure, we could add a warning!

**Comment by AThousandShips** [comment]
> into another project with the intention of never using it ever

Putting a project inside another as a weird way to organise a hierarchy of projects, for example having a separate launcher, server, etc., makes more sense to me than copying a complete project into another intending to use it

**Comment by slo64** [comment]
> copying a complete project into another intending to use it

It is not unheard of. This is how git submodules work.

> Sure, we could add a warning

A warning would have been quite enough. Thank you.

**Comment by paul-mcnamee** [comment]
> > into another project with the intention of never using it ever
> 
> Putting a project inside another as a maybe weird way to organise a hierarchy of projects, for example having a separate launcher, server, etc., makes more sense to me than copying a complete project into another intending to use it

What about for sharing libraries of common scripts between projects? What is the current standard to do that? I came here because I could not find out how to do that easily. Git submodules seem to be an option but apparently you can't import the whole project because the folder is hidden if it contains a project.godot file.
