### ISSUE TITLE
CharacterBody3D randomly teleports around when moving near the scene origin

### ISSUE THREAD

**Issue by jacobcoughenour** [godotengine/godot#77051]
### Godot version

4.1.dev (70f69f6c7 to ffd32a244)

### System information

Windows 11, Intel Core i9-12900K, Forward+, NVIDIA GeForce RTX 2080 SUPER driver v31.0.15.2849

### Issue description

When I move the CharacterBody3D with move_and_slide() close to 0,0,0 it sometimes teleports the character. It appears to be teleporting the character to ~25.574m from the origin along the X or Z axis (ex: (0, y, ~25.574) or (~25.574, y ,0)).

https://github.com/godotengine/godot/assets/5546400/df24a0fa-b8e5-4945-bf16-9e40fa622470

(Note: the white cube in the center does not have a collider)

I narrowed it down to PR #76379 introducing this bug since the commit right before it does not exhibit this behavior.

### Steps to reproduce

See player.gd in the reproduction project. The gist is I get the input and add it to the velocity with some gravity then call move_and_slide().

The controls are WASD and click the window to cursor lock and rotate left/right.

### Minimal reproduction project

[repro.zip](https://github.com/godotengine/godot/files/11471103/repro.zip)

**Comment by rburing** [comment]
With Visible Collision Shapes enabled (in the Debug menu) we see that this happens on a seam of a trimesh shape.

The linked PR did change some thresholds (which could be changed back while still keeping the spirit of the PR), but I did not expect this effect. It may be that the changed threshold uncovered some other collision solver bug; this should be investigated further.

**Comment by jcostello** [comment]
I was experimenting this issue. Good catch
