### ISSUE TITLE
4.1, Overlapping signals text in node panel

### ISSUE THREAD

**Issue by duianto** [godotengine/godot#77070]
### Godot version

v4.1.dev2.official [668cf3c66]

### System information

Windows 10 22H2, Compatibility, Geforce GTX 550 Ti

### Issue description

This might be the same/similar issue as:
4.1, Overlapping multiline error/warning messages in Debugger (Tree node bug) #77067

Issue observed in:
- v4.1.dev2.official [668cf3c66]

When the connected signal text in the node panel, is wider than the node panel's width, then the connected signal text overlaps the text below.

![Godot_v4 1-dev2_win64_mJvkNQlIqP_cropped](https://github.com/godotengine/godot/assets/13420573/cdc4ecad-5cc6-4b54-944e-65295e3e26a8)

Left-clicking in the node panel fixes it.

![Godot_v4 1-dev2_win64_rM3yKpWu6G_cropped](https://github.com/godotengine/godot/assets/13420573/7fea7167-c8c8-4d33-82f1-6ac4b65ea7da)

It's not a problem in:
- v4.0.2.stable.official [7a0977ce2]

![Godot_v4 0 2-stable_win64_wSeZpCxNr4_cropped](https://github.com/godotengine/godot/assets/13420573/84995f36-9bbc-4a7e-b902-1ebf3cbbfabb)

### Steps to reproduce

- open the attached project: [issue, overlapping signals text in node panel.zip](https://github.com/godotengine/godot/files/11472290/issue.overlapping.signals.text.in.node.panel.zip)

- in the Scene panel, select the node: ColorRect
- Open the Node panel tab (right of the Inspector)

### Observed

The text of the connected signal under mouse_entered(), overlap the text mouse_exited()

![Godot_v4 1-dev2_win64_mJvkNQlIqP_cropped](https://github.com/godotengine/godot/assets/13420573/cdc4ecad-5cc6-4b54-944e-65295e3e26a8)

### Expected

The connected signal text shouldn't overlap.

The text becomes "unoverlapped" when either:
- the node panel is left clicked
- or the mouse pointer is held over the panel until a mouse over tooltip appears

![Godot_v4 1-dev2_win64_rM3yKpWu6G_cropped](https://github.com/godotengine/godot/assets/13420573/7fea7167-c8c8-4d33-82f1-6ac4b65ea7da)

### Notes

The overlapping text issue can be reproduced by, deselecting and selecting the ColorRect node.
For example, by clicking outside the ColorRect it in the viewport, or by clicking on the root Control node.
And then selecting the ColorRect node again.

Now the connected signal text overlaps the mouse_exited() text again.

### Minimal reproduction project

[issue, overlapping signals text in node panel.zip](https://github.com/godotengine/godot/files/11472290/issue.overlapping.signals.text.in.node.panel.zip)

**Comment by AThousandShips** [comment]
As both affect the `Tree` there's no need to add a separate bug report for this case

**Comment by duianto** [comment]
I suspected that they might be related, but I opened a new issue just in case.
