### ISSUE TITLE
Setting Joint3D node_a and node_b properties programmatically has no effect, PhysicsBodies aren't connected

### ISSUE THREAD

**Issue by Dancovich** [godotengine/godot#77075]
### Godot version

v4.0.2.stable.official [7a0977ce2], v4.0.3.rc2.official [2ac4e3bb3]

### System information

Windows 11 22H2, Intel Core i5-10300H, nVidia GTX1650

### Issue description

If you use any type of Joint3D to connect two physic bodies 3D but let the `node_a` and `node_b` properties empty on the property inspector and instead set these properties in a script on the `_ready` method, it has no effect whatsoever. Only way of making them work is setting them on the property inspector.

### Steps to reproduce

- Create a new project
- Set the environment and camera so you can see the results
- Add two PhysicsBody3D instances, for example a CharacterBody3D and a RigidBody3D
- Add a Joint3D, like a PinJoint3D or HingeJoint3D
- Leave the Node A and Node B properties of this joint empty
- Create a script on the root of your scene
- On the _ready method, add this code:

```
func _ready():
	$BuggedJoint.node_a = bugged_character_path
	$BuggedJoint.node_b = bugger_rigid_body_path
```
- (Optional) set the _physics_process method to move one of the physics bodies somehow, so the joint can be tested
- Run the project

### What I expected

The two physics bodies should be attached according to the set rules

### What happens

The two bodies aren't connected at all, as if the joint wasn't there

### Minimal reproduction project

This  project has two sets of joints and physics bodies, one set completely through the property inspector and the other set via script. Running this project shows they don't behave the same.

https://github.com/Dancovich/godot_joint_bug

**Comment by KhalilBenGaied** [comment]
So the issue might be due to when the joint's nodes are being assigned. The joint might be trying to connect the nodes before they are ready, therefore failing to connect them properly.
Can you verify my attempt to edit the reproduction code you provided i guess it fixes the problem
[godot_joint_bug-main.zip](https://github.com/godotengine/godot/files/11472984/godot_joint_bug-main.zip)
i just made a change on the " node_3d.gd " with comments

**Comment by Dancovich** [comment]
@KhalilBenGaied I'm sorry but I think I'm misunderstanding something. The file node_3d.gd inside your zip file is identical to mine. Am I supposed to be seeing something different?

Anyway, I thought about the issue being trying to set these properties during _ready and moved them to _physics_process. No luck, the joint is still not keeping the bodies attached.

**Comment by KhalilBenGaied** [comment]
yes appearntly the older version got uploaded in zip, here's the updated one, please check and verify it thank you for your time.


[godot_joint_bug-main.zip](https://github.com/godotengine/godot/files/11473168/godot_joint_bug-main.zip)

**Comment by Dancovich** [comment]
@KhalilBenGaied I believe I've tracked down what the issue is.

At first, I tried using the following techniques for setting the properties `node_a` and `node_b` of a Joint3D:

- Setting it directly with `joint_node.node_a = NodePath("PathToPhysicsBody3DNode")`
- Using the ^ shortcut with `joint_node.node_a = ^"PathToPhysicsBody3DNode"`
- Creating an exported variable and setting it on the editor with `@export_node_path("PhysicsBody3D") var path_to_node: NodePath`, then assigning it on the joint with `joint_node.node_a = path_to_node`

All of these were done on `_ready` and none worked.

Then I tried the following experiment. I simply assigned the path this way on `_ready`:

```gdscript
func _ready():
    joint_node.node_a = $PhysicsBody.get_path()
```

and it worked!

To try to understand what was different, after the assignment I printed the value of `joint_node.node_a` and was surprised to find different results.

```gdscript
@export_node_path("PhysicsBody3D") var path_to_node: NodePath
func _ready():
    # joint_node.node_a = path_to_node
    joint_node.node_a = $PhysicsBody.get_path()

    print("This nodepath points to %s" % joint_node.node_a)
    # This prints "PhysicsBody" if I use the first way of assigning,
    # but it prints "/root/SceneNode/PhysicsBody" if I assign it the second way
```

If node_a is set in any of the ways I first tried, it will result in a relative NodePath (`is_absolute()` returns false) and the assignment won't work.

If instead node_a is set $PhysicsBody.get_path(), it will result in an absolute NodePath (`is_absolute()` is true) and the assignment will work.

So, apparently, `node_a` and `node_p` properties of a Joint3D need to be absolute NodePaths.

The issue is there is no way to make a relative NodePath into an absolute one as there are no `get_absolute()` or `resolve_absolute()` methods on NodePath. The only way of getting an absolute path is to get the actual reference to the Node and calling get_path(), which to my knowledge always returns an absolute path.

Not only this is not documented anywhere in Joint3D or it's children, it also goes against user expectation of NodePath being a pre-processed path to a node. I don't know of any other place in the engine where a NodePath needs to be absolute to work.

So for now I believe I've found a workaround, but the bug still persists. Either documentation on Joint3D needs to be updated to reflect that it expects an absolute NodePath (and consequently add a `get_absolute()` method to NodePath) or Joint3D node_a and node_b properties need to accept relative paths.

**Comment by AThousandShips** [comment]
So, you are making a very simple mistake here:
The correct path is `../BuggedCharacter`

The path is relative to the *joint* not to the node that is setting it

The bodies are *siblings* of the joint, not children

Not a bug

**Comment by Dancovich** [comment]
> This would never be possible, as it can't know what it is relative _to_

Why not? The engine is clearly capable of resolving a relative path when you pass it to get_node. Even accepting an argument as the point of reference would suffice:

`var absolute_path = relative_path.resolve_absolute(reference_node)`

**Comment by Dancovich** [comment]
> Node paths are relative always, this is documented

No they are not.

[From the documentation](https://docs.godotengine.org/en/stable/classes/class_nodepath.html):

> A pre-parsed relative **or absolute** path in a scene tree, for use with [Node.get_node](https://docs.godotengine.org/en/stable/classes/class_node.html#class-node-method-get-node) and similar functions.

```gdscript
# A leading slash means it is absolute from the SceneTree.
^"/root" # Equivalent to get_tree().get_root().
^"/root/Main" # If your main scene's root node were named "Main".
^"/root/MyAutoload" # If you have an autoloaded node or scene.
```

So no, it's not documented that paths are always relative. If you create the `NodePath` manually you can make it absolute and it's not documented anywhere (that I know of) if `NodePaths` created from exported variables set in the inspector are relative or absolute. I only discovered that when I called `is_absolute()` on the NodePath from my exported variable and it returned `false` (or if I decided to hover my mouse cursor over the property as you said).

I believe you're overestimating how intuitive this experience really is. Here's how I encountered this issue to begin with:

- Created a scene and added a joint as one of the children of this scene
- Created a script on this scene
- Added two exported variables of type `NodePath` to this script with `@export_node_path("PhysicsBody3D") var node_1: NodePath` and `@export_node_path("PhysicsBody3D") var node_2: NodePath`
- Wrote code in the _ready() method of this script to assign these variables to the joint node_a and node_b properties. (`$Joint3d.node_a = node1` and `$Joint3d.node_b = node2`)
- Added this scene to my main scene. This main scene has two PhysicBody3D instances and my custom scene.
- Dragged the two PhysicBody3D instances from the main scene to the exported properties of my custom scene in the inspector

In my head, since I dragged the nodes to the exported variable, the resulting NodePath would successfully resolve to a valid node. Not only it didn't work, no error message was shown. So I was on my own figuring out what the issue was.

This wasn't intuitive for me. Maybe I'm being dense here, but the steps I followed seemed reasonable and not only I didn't get the result I wanted, I also got no error message.

How is that intuitive?
