### ISSUE TITLE
Godot Game Doesn't Quit on Android

### ISSUE THREAD

**Issue by toliaferrode** [godotengine/godot#7707]
**Operating system or device - Godot version:**
Android - Godot 2.1.2

**Issue description:**

A call to get_tree().quit() takes the game off the screen, but when I hit my own applications button the game is still listed, and can be called back by tapping it.

**Steps to reproduce:**
Call get_tree().quit() on Android.

**Link to minimal example project:**
:

**Comment by volzhs** [comment]
what is "my own applications button"?

**Comment by toliaferrode** [comment]
Sorry, it's my device's own button. It's a capacitive touch button. When
you press it, it shows all applications open.

**Comment by akien-mga** [comment]
Isn't it normal on Android? I never saw an application which had a in-app way to *really* close it, it always needs to be done via the list of open Android applications (which sucks super hard, but that's a Google design decision AFAIK).

**Comment by toliaferrode** [comment]
Oh, I didn't know that. I'm a relatively recent mobile user. I notice that
my other games don't quit. But I could have sworn an app I made in another
platform closed. I'm not sure anymore.

**Comment by toliaferrode** [comment]
Thanks!
