### ISSUE TITLE
SVG rendering issue with specific files (upstream ThorVG bug)

### ISSUE THREAD

**Issue by JonnyTech** [godotengine/godot#77094]
_Originally posted by @JonnyTech in https://github.com/godotengine/godot/issues/77044#issuecomment-1546750746_

> Also, please note that there is an issue with Godot's .svg import - the stars in the included flags images of eu.svg and us.svg are not rendered correctly.

Rendered with Godot:

![godot](https://github.com/godotengine/godot/assets/3584732/db744227-ab0f-4dac-9af4-b081d007e8dd)

Exported image:

![image](https://github.com/godotengine/godot/assets/3584732/c1e82a8e-db55-4a8d-a416-0ac4070361ff)

Images from https://github.com/lipis/flag-icons

**Comment by JonnyTech** [comment]
Thanks for checking, @clemens-tolboom - it is not clear if the linked issue is related so I shall open a separate ticket there

**Comment by clemens-tolboom** [comment]
@JonnyTech as your https://github.com/thorvg/thorvg/issues/1451 lead to 2 PR (https://github.com/thorvg/thorvg/pull/1452 and https://github.com/thorvg/thorvg/pull/1453 are applied) fixing the EU maybe we should leave this open?

**Comment by akien-mga** [comment]
Yes we can leave this open until upstream fixes are made and backported.

**Comment by JonnyTech** [comment]
Indeed, although it is fixed upstream, I shall wait for it to bubble down to Godot (hopefully v4.0.3) before confirming and closing.

**Comment by capnm** [comment]
Fixed in 4.2.dev

![image](https://github.com/godotengine/godot/assets/4047289/168c02c6-c6f8-46da-b023-2d0807660b49)
