### ISSUE TITLE
Vertex color (0, 0, 0) issue when placing gridmap items with assigned texture

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#77097]
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Mac

### Issue description

Attempting to place an imported GLTF file as part of a gridmap does not work

### Steps to reproduce

1. [test-gridmap.zip](https://github.com/godotengine/godot/files/11477712/test-gridmap.zip)
2. Try to place both types of tiles

`MeshInstance3D` works, `"cube"` does not work.

### Minimal reproduction project

Please see above

**Comment by smix8** [comment]
Because you imported your "cube" material with both vertex colors as well as alpha scissor transparency enabled.

The mesh has no vertex colors. The MultiMesh that renders your GridMap meshes therefor has to fall back on the default rendering vertex color which is black. Black makes the alpha scissor transparency cull everything.

**Comment by tavurth** [comment]
Aha I see, so it's more a question of missing vertex colors?

This is certainly something confusing and which should either be documented, or missing vertex colors should be set to `Color.WHITE` by default?

**Comment by tavurth** [comment]
So using this test cube exported from [the same program](https://www.blockbench.net), everything works fine.

[Test.zip](https://github.com/godotengine/godot/files/11480547/Test.zip)

Seems the program does not assign a vertex color when exporting with textures?

Still strange that Godot displays it well in the editor but does not actually place anything visible when clicking.

**Comment by tavurth** [comment]
<img width="1552" alt="Screenshot 2023-05-16 at 01 09 06" src="https://github.com/godotengine/godot/assets/100964/f0ff2839-df69-4a84-85bf-663047c39f06">

What's really weird is that my meshes display just fine as actual meshes in Godot ^

It's the `MultiMeshInstance` causing the vertex colour issue I guess.

**Comment by tavurth** [comment]
@smix8 this appears to be a multimesh instance, thank you for the long dev delay 😞 

https://github.com/godotengine/godot/issues/77107

**Comment by Calinou** [comment]
This sounds like a bug, as vertex colors should definitely not be transparent black by default. They should be opaque white like they are when rendering regular meshes.
