### ISSUE TITLE
Editor freezes when trying to load absent documentation

### ISSUE THREAD

**Issue by Angular-Angel** [godotengine/godot#77109]
### Godot version

4.0 master

### System information

```
           `-/osyhddddhyso/-`              angle@Sager 
        .+yddddddddddddddddddy+.           ----------- 
      :yddddddddddddddddddddddddy:         OS: Xubuntu 22.10 x86_64 
    -yddddddddddddddddddddhdddddddy-       Kernel: 5.19.0-1021-lowlatency 
   odddddddddddyshdddddddh`dddd+ydddo      Uptime: 56 mins 
 `yddddddhshdd-   ydddddd+`ddh.:dddddy`    Packages: 5478 (dpkg), 11 (brew), 38 (flatpak), 40 (snap) 
 sddddddy   /d.   :dddddd-:dy`-ddddddds    Shell: bash 5.2.2 
:ddddddds    /+   .dddddd`yy`:ddddddddd:   Resolution: 1920x1080 
sdddddddd`    .    .-:/+ssdyodddddddddds   DE: Xfce 4.16 
ddddddddy                  `:ohddddddddd   WM: Xfwm4 
dddddddd.                      +dddddddd   WM Theme: Default 
sddddddy                        ydddddds   Theme: Greybird [GTK2/3] 
:dddddd+                      .oddddddd:   Icons: elementary-xfce-darker [GTK2/3] 
 sdddddo                   ./ydddddddds    Terminal: xfce4-terminal 
 `yddddd.              `:ohddddddddddy`    Terminal Font: Monospace 12 
   oddddh/`      `.:+shdddddddddddddo      CPU: Intel i5-6500 (4) @ 3.600GHz 
    -ydddddhyssyhdddddddddddddddddy-       GPU: NVIDIA GeForce GTX 1050 Ti 
      :yddddddddddddddddddddddddy:         Memory: 3945MiB / 24000MiB 
```

### Issue description

When trying to compile a custom module, if I add a class without a documentation file, it freezes the editor when I try and open that classes documentation. It's able to load the 'No documentation, you can help us by adding some!' page, but freezes afterwards.

### Steps to reproduce

1. Clone https://gitlab.com/AngularAngel/voxel-tools and add it to the godot source as a module, rename it's folder to 'voxel'
2. Compile the Godot source and run it.
3. Try and open the documentation for the 'VoxelTexturePalette' class.
4. Observe your soon to be frozen editor.

### Minimal reproduction project

https://gitlab.com/AngularAngel/voxel-tools, though you also need the Godot source.

**Comment by YuriSizov** [comment]
Can you still reproduce this in 4.1? Also, could you specify which version did you test it with? If it's a custom build, which commit has been used?

**Comment by YuriSizov** [comment]
There were some fixes around documentation, so this might be fixed by now. If you can still reproduce it, please let me know and I can reopen this issue.
