### ISSUE TITLE
Script class needs to have a virtual new() method

### ISSUE THREAD

**Issue by blackears** [godotengine/godot#77108]
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Windows 10, GLES 3,

### Issue description

Right now the Script class has no method for creating new instances of the script it points to.  Both of the nodes that currently inherit from it - GDScript and CSharpScript - do and I would presume any other derived nodes you add in the future would too.  While Godot's duck typing does allow me to just call .new() on the Script node, it would be nice to have this formally added to the Script class so there is no ambiguity about how to create new instances from a script without having to know precisely which type of script you are instancing.

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Closing, as feature proposals should be discussed on the [Godot proposals](https://github.com/godotengine/godot-proposals) repository. This repository is now used for bug reports only.

Make sure to follow the proposal template when opening a new proposal – don't just copy and paste the text you wrote in this issue.
