### ISSUE TITLE
Script editor undo sometimes merges unrelated actions

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#77101]
### Godot version

4.1 5c653c2

### System information

Windows 10 x64

### Issue description

Example:

https://github.com/godotengine/godot/assets/2223172/4313d61c-d388-4962-b2b5-6c1b6765c9f6

I started writing something, but made a mistake, so wanted to undo it. The undo registered this change and another change in a different line as the same action. So I either have to manually remove the wrong text (the one below) or write the correct text (the one above) again :unamused: 

It happens quite frequently. I move the caret to another line and write something, but then it suddenly gets merged with what I wrote previously. Annoying stuff.

### Steps to reproduce

1. Write some code
2. Write some more code
3. Undo
(I don't know what exactly triggers cases like above; *at least* it doesn't happen all the time)

### Minimal reproduction project

N/A

**Comment by ajreckof** [comment]
Normally it is only about time between two inputs. So maybe you are super fast at changing lines? 
I'm not sure if it has been done or not but maybe we could enable customisation of the max time between two inputs.

Another idea would be to force stop merge on certain action, for example changing line. I'm not sure undoredo permits that for the moment so we would need to add the evolution to it first. But I think this would be the best solution (if this is really about Kobewi being way too fast at typing)

**Comment by KoBeWi** [comment]
> So maybe you are super fast at changing lines? [...] (if this is really about Kobewi being way too fast at typing)

Suffering from success 🥲

There's another case of this bug, which is 10000% more annoying:

https://github.com/godotengine/godot/assets/2223172/1b97cef5-edde-4d62-9d66-8702bd25f2fd

When I redo the text, the editor instead of staying at the change teleports me to the last caret position. It's extremely confusing and gives a false impression that you made some change in unrelated line. In the video above, my change is adding `-=`, but for whatever reason the scroll goes completely bonkers when I redo this change.

**Comment by gokiburikin** [comment]
> I'm not sure undoredo permits that

Something about the way the code editor works already does this and the grouping time for the same action is way too lenient for me. I waste a ton of time fighting with this feature and would love to see customizable times. The delay between control + backspaces being grouped in the video below is egregiously long. At the very least changing line should break the grouping, not necessarily be its own action.

https://github.com/godotengine/godot/assets/3820082/f17dbd75-71b3-40a2-b6f9-ba0fbb51b803

**Comment by wareya** [comment]
Here's my take on this:
1) Moving the cursor should always cause a split into a new undo operation.
2) If the last action was split by moving the cursor, redoing that action should not put the cursor where the cursor movement put the cursor. Cursor movements should only be included in undo/redo actions if they're tied together with some other operation.
3) Saving should always cause a split into a new undo operation.
4) Switching between adding text and deleting text should always cause a split into a new undo operation.

**Comment by TheSofox** [comment]
I managed to find the setting for how long it needs to stay idle before they make the next actions part of a new undo operation. It's in Project Settings->GUI -> Timers -> Text Edit Idle Detect (sec) (gui/timers/text_edit_idle_detect_sec). You'll need to enable "Advanced Settings" to see them. By default it's 3 seconds.

Aside from that, I agree with what's been said. Moving the cursor, either by mouse or keyboard, should make the next action part of a new undo operation.

**Comment by TheSofox** [comment]
Created a pull request to solve this issue. Now if you add text on three different lines in quick succession, you'll need three undo commands to clear them.

The only exception is if you hold down backspace and delete multiple lines in one go. I was going to see about dividing that up into multiple operations, but then wasn't sure if that was necessary. In any event, every time you click to move the caret or move the caret via arrow keys, it'll split the undo operation.

**Comment by KoBeWi** [comment]
I see this issue again in 4.3 rc3

https://github.com/user-attachments/assets/145488c6-ea5c-4f63-bb95-4ce4a0816b69

It's not as common though and might be related to selection.

**Comment by TheSofox** [comment]
I need more detailed repo steps. I appreciate the video but it's hard to work out what's going on since I don't know what keys are being pressed. In the 2nd video I'm not certain which issue you're pointing to.

**Comment by KoBeWi** [comment]
I actually haven't encountered it recently. Maybe it's fixed again.
In any case, I press Ctrl+Z when text is deleted and Ctrl+Y when text is restored.

**Comment by TheSofox** [comment]
Alright, well glad to hear it's low key at the very least. Let us know if it happens again.
