### ISSUE TITLE
MultiMeshInstance3D not displaying in compatibility mode

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#77107]
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Mac

### Issue description

Perhaps I'm doing something completely wrong, and yet I copied from the docs 🤔 

Did something change from 3.x in the case of multimesh?

### Steps to reproduce

[multimesh.zip](https://github.com/godotengine/godot/files/11481052/multimesh.zip)

### Minimal reproduction project

Please see above

**Comment by Calinou** [comment]
On 4.1.dev 64eeb04d2 (Linux, GeForce RTX 4090 with NVIDIA 530.41.03), I can definitely see instances appearing when I change the instance count, but it flickers in all directions when I change that value. Nothing appears when using the Forward+ or Mobile rendering methods, regardless of the instance count.

PS: The cross in the middle *is* one of your MultiMeshInstance's instances.

**Comment by tavurth** [comment]
> PS: The white cross in the middle you highlighted on the screenshot _is_ one of your MultiMeshInstance's instances.

Strange, I set it up to be a `CubeMesh` is there a reason it's rendering as a cross?

**Comment by tavurth** [comment]
Updated example:

[TestGridmap.zip](https://github.com/godotengine/godot/files/11483647/TestGridmap.zip)

It appears this is because I'm exporting a GLTF model somehow strangely.

When a model is exported from blender it seems to work, but not from BlockBench.

OBJ is working in the above example

**Comment by smix8** [comment]
On Windows with a RTX3090Ti and driver 531.68 the compatibility renderer ist just entirely broken with that new test project.

Nothing is rendering and everytime I try to start the scene for a test run Godot just locks up and freezes to death without any error.

**Comment by bitsawer** [comment]
Remove this line and the test projects works:

`multimesh = MultiMesh.new()`

You are overwriting the existing multimesh and all it's editor settings here (including mesh resource), so naturally it's not going to render anything in play mode. In the editor you need to set the buffer data properly to see anything. This should be usually done by a tool script as writing the matrix values by hand is difficult. Also see https://github.com/godotengine/godot/issues/75485. You should also set instance count to 0 in the editor as you update and regenerate that in code.

I'm closing this issue, but it still might be worth creating a new issue for the gridmap problem if you are still having troubles with it and can't find an existing issue. There are still some issue related to Compatibility multimesh rendering, but they should have their separate issue reports. 

![box](https://github.com/godotengine/godot/assets/22456603/e0a859bd-eaee-45a6-90b9-5b58f050b834)
