### ISSUE TITLE
"sky_coords" node in VisualShaders not matching mapping used by PanoramaSkyMaterial

### ISSUE THREAD

**Issue by epicRedHot** [godotengine/godot#77116]
### Godot version

4.0.2.stable

### System information

Windows 11, 12th Gen Intel Core i5-12400F, Vulcan, NVIDIA GeForce RTX 3060 Ti

### Issue description

When using the sky_coords VisualShader node for a sky shader, there is distortion at the poles that isn't present when using the same texture for a PanoramaSkyMaterial.
First image is using sky_coords, second image is a PanoramaSkyMaterial.

![image](https://github.com/godotengine/godot/assets/76829489/45fe3d9c-9573-4fb7-910e-ddfdc3fb937b)
![image](https://github.com/godotengine/godot/assets/76829489/f1c9534e-8630-4676-800a-430bed3bad35)

(tagging @paddy-exe as requested)

### Steps to reproduce

The included project provides an example in the scene named "stretched", which has a WorldEnvironment using the "sky_coordsDistortion" VisualShader for its sky.

### Minimal reproduction project

[reproduction.zip](https://github.com/godotengine/godot/files/11482327/reproduction.zip)

**Comment by Calinou** [comment]
A sky texture is stretched on the poles, since that's how the sphere's UV mapping is designed. This does not occur when using a shader to render the sky.

**Comment by paddy-exe** [comment]
For context: we were in contact on the VFX Discord Server by QbieShay and I noticed that there's no `source_panorama` handle for visual shader nodes. Seems like it's currently only supported on written shaders.

**Comment by Calinou** [comment]
> For context: we were in contact on the VFX Discord Server by QbieShay and I noticed that there's no `source_panorama` handle for visual shader nodes. Seems like it's currently only supported on written shaders.

`source_panorama` is just a uniform name, not something with special treatment: https://github.com/Calinou/godot/blob/81cfa0d2bbe9c21a43770b69353b6ea3a48f16e0/scene/resources/sky_material.cpp#L439-L449

**Comment by paddy-exe** [comment]
@Calinou My Bad. That was the wrong term for it. But it's still not supported in Visual Shader Nodes as far as I tested it.

**Comment by epicRedHot** [comment]
The texture used was rendered with Blender's Panoramic Equirectangular camera, so it was already stretched at the top and bottom of the image.
![image](https://github.com/godotengine/godot/assets/76829489/2747dd09-726d-4497-820a-ba4e96a290d0)
![starsPanorama](https://github.com/godotengine/godot/assets/76829489/b45f7357-d4db-4d99-add7-4141d3be263d)

When using a "regular" texture, it stretches under both situations.
(first image is PanoramaSkyMaterial, second image is the earlier shader setup with the texture swapped out)
![image](https://github.com/godotengine/godot/assets/76829489/fd1c7861-20b8-4c84-820a-dd87de91c41e)
![image](https://github.com/godotengine/godot/assets/76829489/7498ddfe-951e-40c4-a6af-c3b317c3c6e2)

**Comment by paddy-exe** [comment]
@epicRedHot I think this issue can be closed then, right? Thanks for the clarification Clay!
