### ISSUE TITLE
Code Lens References and Unused Members not Displayed for C# Classes Inherited from GodotObject

### ISSUE THREAD

**Issue by iseos** [godotengine/godot#77128]
### Godot version

4.0.2

### System information

Windows 10

### Issue description

I have noticed that there are issues with the proper display of references in Code Lens and the incorrect detection of unused variables and methods for C# classes inherited from GodotObject. This inconsistency significantly affects the convenience and efficiency of C# development in Godot.

The behavior of Code Lens is misleading as it cannot accurately determine whether a method or variable is being used or not. This is because variables always show a minimum of 4 references, while classes and methods show 1.

![1](https://github.com/godotengine/godot/assets/16374845/17b1873a-b3e6-4e17-9a1c-fa20b243cdde)

This behavior in all IDEs I checked, Rider, Visual Studio, Visual Studio Code.

I understand that this issue stems from the code generation and usage of partial classes.

I would like to inquire whether there are any plans to address this issue and improve the accuracy of displaying references and detecting unused members. Alternatively, if there are any recommended workarounds or alternative approaches to mitigate these challenges in C# development within Godot.

Thank you for your efforts, and I appreciate your response!

### Steps to reproduce

Create a Godot Net project.
Create a class inherited from GodotObject, Node...
Add variables or methods.

### Minimal reproduction project

N/A

**Comment by raulsntos** [comment]
This sounds more like the issue is on the IDE side. I think they should be able to figure out if the file that references the member is generated or not and then choose how to display that in their UI. However, they may not want to change the current behavior since the idea behind source generators is that the generated code is no different from your manually written code.

**Comment by iseos** [comment]
Apparently you are right, [godot-support](https://github.com/JetBrains/godot-support/issues/92) plugin Rider has already been notified of this trouble.

**Comment by RedworkDE** [comment]
- See also https://github.com/dotnet/roslyn/issues/52498

**Comment by LordBrkica** [comment]
> It seems to have been fixed in Rider, as well as in VSCode. _It's not clear how they fixed it, I haven't followed it for a long time._
I still experience the same problems using VSCode and Godot 4.1.1 Mono. 
Am I the only one or do I need to do something in VScode to fix this ?

**Comment by hak33m16** [comment]
Still an issue when using Godot 4.2.2 mono paired with:
dotnet 8.0.302
C# v2.34.12 (vscode addon)
C# dev kit v1.8.14 (vscode addon)
vscode 1.91.0

@iseos Could you explain what lead you to say this is fixed in VS code?
