### ISSUE TITLE
Janky inverse kinematics on legs

### ISSUE THREAD

**Issue by magbulogtong81** [godotengine/godot#77138]
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Manjaro Linux, Intel Core i3-3220, Intel(R) HD Graphics 2500 Rendering Method=Mobile

### Issue description

when applying inverse kinamatics on the legs, the legs looked like it got twisted around, however it works well on the arms
here's the screenshot of it:
![1](https://github.com/godotengine/godot/assets/46246619/0e0887fa-2cf1-4243-8935-55291ce2d249)

and this is the one I expect it work: (captured with godot 3)
![2](https://github.com/godotengine/godot/assets/46246619/b505b68c-a93a-4f96-a5a2-ae2dcf420d0e)

here's a [sample project](https://w5ybg-my.sharepoint.com/:u:/g/personal/jil_w5ybg_onmicrosoft_com/EbA_2dp8ZZdEqmeqR02ca_UBmSgZgjeNzKW1JHnzfCZ2vg?e=cnsuNZ) with the mentioned issue

### Steps to reproduce

- import a humanoid mesh to godot
- create new 3d scene
- instantiate the humanoid mesh
- enable editable children
- add a skeletonIK child node under Skeleton3D
- set  the root bone to upper leg and tip bone to foot
- add a marker3D as target for skeletonIk
- play IK

### Minimal reproduction project

https://w5ybg-my.sharepoint.com/:u:/g/personal/jil_w5ybg_onmicrosoft_com/EaztHHOuCJBGpz8p4dbs3u0BFiVS3smgcBiPypLfAKWwkw?e=V0gaXV

**Comment by fracteed** [comment]
Unfortunately, the Skeletonik3D is very broken in 4.0 and is unusable. I get crashes just adding it into a scene. You will find various other open issues on this such as https://github.com/godotengine/godot/issues/74753

It has been a frustrating wait for this to be fixed and I personally believe that all 3dik should have been removed for the 4.0 release. The 3.5 stack based ik was removed for 4.0 ,but for some reason the skeltonik3d was kept, which leads to the impression that it works....but it does not!

**Comment by fire** [comment]
@lyuma What are your thoughts? You were interested. I am ok with removing SkeletonIK3D.

**Comment by magbulogtong81** [comment]
> Unfortunately, the Skeletonik3D is very broken in 4.0 and is unusable.
> 
>  for some reason the skeltonik3d was kept, which leads to the impression that it works....but it does not!

yeah  exactly. when you see a product that say it's 'stable' it generally means it just works. it would make much more sense if it's not included at all and just put on the documentation that it's still work in progress

**Comment by Project-Siege** [comment]
just add a marker3d as the target and rotate it
