### ISSUE TITLE
Particle Spread value field max value is 1

### ISSUE THREAD

**Issue by Gibbz** [godotengine/godot#7714]
**Operating system or device - Godot version:**
godot 2.2
ubuntu 16.04

**Issue description:**
http://docs.godotengine.org/en/stable/tutorials/2d/particle_systems_2d.html
spread angle is limited to a value of 0 - 1. The website it should be in degrees, as an angle. However a value of 1 is only about 10 degrees... So I cant get the desired result.

**Steps to reproduce:**
new particle, adjust the value :)

**Comment by bojidar-bg** [comment]
From what I've tested, it is in percent, so, a value of 1 means emit in all directions. (and 0.5 would be in half directions), but I might be wrong.

**Comment by Gibbz** [comment]
Yeah it could be, i noticed the base velocity seems to cancel it out... 
I might try the linear velocity instead with no base velocity... that 
could me my issue...

**Comment by Gibbz** [comment]
ha yeah, sorry that was the issue! what a brain fart! sorry :)
