### ISSUE TITLE
Severe memory leak when adding new tilemap patterns

### ISSUE THREAD

**Issue by x3nn3xy** [godotengine/godot#77176]
### Godot version

4.0.2 stable

### System information

Windows 10, 32GB RAM 3777MHz, 5900x, 6900xt

### Issue description

When adding a new pattern to a Tilemap, the editor sometimes freezes and starts increasing its memory usage drastically.
If the editor is not closed via the task-manager, the editors memory consumption increases from ~500MD to well over 28GB within a span of ~180 - 240 seconds.

### Steps to reproduce

Open a new scene, add a tilemap, select tileset and leave everything else on default.
After that, add a new tile in the TileSet Menu.
My workflow for adding new pattern, if they come already predefined in the tileset is the following:
Add every desired pattern into the current scene from the tileset, cut the out one after another (ctrl + x) and paste them into the pattern section under TileMap.

The error consistently appeared after ~20 - 25 pattern are created for a freshly added tileset.
When opening the editor after it errored out, I was able to add between 5-15 more pattern, bevore the editor froze again.

Potentially helpfull:
The error occured while using the following pixelart set:
https://szadiart.itch.io/pixel-fantasy-castle-prison

### Minimal reproduction project

N/A, but can provide if neccessary.

**Comment by Voidless22** [comment]
Just ran into this same issue, version "v4.0.3.stable.mono.official [5222a99f5]" -- Only had around 6 patterns in my tilemap and was editing terrain layers when the engine locked up. I checked task manager and I was consuming 18gb out of 24gb in ram before it crashed out completely.

**Comment by groud** [comment]
Hmm, I cannot reproduce it on my side. Could you check if it still happen on the latest version ?

**Comment by x3nn3xy** [comment]
Wasn't able to replicate it in the latest version either.
I will open a new ticket, if it occurs again.
