### ISSUE TITLE
double invocation of gdscript functions that have previously been invoked by a signal

### ISSUE THREAD

**Issue by jezv** [godotengine/godot#77173]
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Windows 11

### Issue description

normal invokation of gdscript functions from another script is being called twice if that function is also connected to a signal which has previously fired.

### Steps to reproduce

open either of the the minimal repros
press play
hit the 'Enter' key a few times whilst observing the output
=> observe the number increments once for every hit
now click the 'increment print' button with your left mouse button a few times
=> observe the number increments once per click
not hit the 'Enter' key again a few times
=> THE ISSUE: observe the number increments twice per hit, because increment_print is called twice now

### Minimal reproduction project

[bug1.zip](https://github.com/godotengine/godot/files/11501834/bug1.zip)
This variant involves creating a scene with a node 'Node' and a button.  The button pressed() signal is connected to a function on its sibling node 'Node', also the scene root node has a script which listens for the enter key input and calls that same function on 'Node'.  After the signal has been fired, the bug of double invocation of the function when hitting Enter begins.

[bug1-variant2.zip](https://github.com/godotengine/godot/files/11502103/bug1-variant2.zip)
This is a similar set up with the same effect but slightly different.  The button pressed() signal is instead connected to a separate function in the scene root's script, which in turn invokes the function on 'Node'.  After following the repro steps above, if you then put a breakpoint in the signal-receiving function on the scene root node, you can see that the breakpoint is hit when hitting 'Enter', even though that code path should only be encountered when clicking the button.

**Comment by dinoplane** [comment]
I think you may be clicking the button with the enter button. And so the function is called twice.

**Comment by jezv** [comment]
Yes that's exactly what's happening!

**Comment by jezv** [comment]
closing as PEBCAK
