### ISSUE TITLE
When an array contains more than 1 000 000 elements the size `EditorSpinSlider` stays to 1 000 000

### ISSUE THREAD

**Issue by ajreckof** [godotengine/godot#77190]
### Godot version

4.1.dev (a8453cb333)

### System information

MacOS 13.3 M1 Pro

### Issue description

When editing an array in the `EditorInspector` if it contains more than 1 000 000 elements the size `EditorSpinSlider` will stay to 1 000 000. 

This should be a good first issue.

### Steps to reproduce

1. export an array
2. enter 1 000 000 as size
3. add some elements with the Add Element button
4. look at the `EditorSpinSlider` it will still say 1 000 000

### Minimal reproduction project

N/A

**Comment by JBrowne017** [comment]
I might possibly take a peek at this.

**Comment by AThousandShips** [comment]
Limit is set here:
https://github.com/godotengine/godot/blob/b40b35fb39f0d0768d7ec2976135adffdce1b96d/editor/editor_properties_array_dict.cpp#L314

Not sure if it is arbitrary however

**Comment by JBrowne017** [comment]
I see no reason it shouldn't just be the DBL_MAX value, rather some some arbitrary 1,000,000. It also gets rid of the magic number.

**Comment by yosoyfreeman** [comment]
Godot team usually eludes magic numbers. You may be right, but it may also be there, for example, because the team consider that number a safe value for whatever reason. I'm curious and probably someone will answer this.

**Comment by kleonc** [comment]
> Limit is set here:
> 
> https://github.com/godotengine/godot/blob/b40b35fb39f0d0768d7ec2976135adffdce1b96d/editor/editor_properties_array_dict.cpp#L314
> 
> Not sure if it is arbitrary however, meaning I'm not sure the solution is to just increase the maximum

It was set like that in https://github.com/godotengine/godot/commit/eded06166860b3c052310cc8db28cc080655b510. I'd assume it was set arbitrarily as "should be large enough", without any special reasoning.
