### ISSUE TITLE
Blender exporter (parenting mesh to bone)

### ISSUE THREAD

**Issue by EngjellRraklli** [godotengine/godot#772]
Parenting a mesh to a single bone of an armature in blender is not supported when exported in Godot,which means that the mesh doesen't move if the bone moves.

![rigging_eyes](https://cloud.githubusercontent.com/assets/7304933/4593376/8452318c-5085-11e4-8d37-133281997cb2.jpg)

**Comment by akien-mga** [comment]
Moved to https://github.com/godotengine/collada-exporter/issues/12.
