### ISSUE TITLE
HTML5 export, problem exporting games with videoclips

### ISSUE THREAD

**Issue by gcomi1977** [godotengine/godot#7720]
**Operating system or device - Godot version:**
Ubuntu 16.04 Godot 2.1.2 stable (steam version)

**Issue description:**

when I export e project to html5 videoclips doesn't work

**Steps to reproduce:**
simply try to export in html5 a project like this one:
https://github.com/gcomi1977/videoblackjack
(PS: of course, if you launch the project within the godot ide, you will see the videoclip work)

**Link to minimal example project:**
:
https://github.com/gcomi1977/videoblackjack

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by eska014** [comment]
#17495 ended up being used to track this issue for 2.1, so I'll repurpose this one for 3.x. Need to test if this already works as-is.
