### ISSUE TITLE
Issue with threaded loading of TileMaps

### ISSUE THREAD

**Issue by MystMagus** [godotengine/godot#77218]
### Godot version

Latest master b40b35fb39f0d0768d7ec2976135adffdce1b96d, not in official release

### System information

Ubuntu 20.04.6 LTS, Intel i7-8700K, NVIDIA GeForce GTX 1060 6GB

### Issue description

When loading a scene with a TileMap using ResourceLoader the tile graphics don't show up (the physics shapes and such are, if there are any). Seems to have been introduced in 5a4613f5512b84a758d7cb4850f6e35db2bcceba

### Steps to reproduce

Load and add a scene with a TileMap using ResourceLoader.

### Minimal reproduction project

[TileLoadTest.zip](https://github.com/godotengine/godot/files/11511332/TileLoadTest.zip)

The image is loaded to show that other stuff does load, the tiles have physics bodies to show that it's just the graphics that are missing.

**Comment by Calinou** [comment]
cc @RandomShaper

**Comment by RandomShaper** [comment]
I was expecting some bug in this area to arise. I'll look into it.
