### ISSUE TITLE
When creating ViewporTexture, a Window can be selected, but not afterwards

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#77219]
### Godot version

4.1 dev2

### System information

Windows 10 x64

### Issue description

Title.

https://github.com/godotengine/godot/assets/2223172/1be0f361-d691-446d-89f0-ff2158c6f4ab

Window-based nodes are a valid target, so I think they should be available when re-selecting the node.

### Steps to reproduce

1. Create a scene with a SubViewport, Window and a Sprite2D
2. Add ViewportTexture to the sprite
3. Both SubViewport and Window are a valid target
4. After confirming the target, click the texture and re-assign it
5. Only SubViewport can be selected

### Minimal reproduction project

N/A

**Comment by felaugmar** [comment]
The issue is also present in the current release: v4.0.2.stable.official [7a0977ce2].
