### ISSUE TITLE
Skeletal animations are not working

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#77222]
### Godot version

master (5bb7d585a5e151f3fa387de7dd97d7aebc5abfd5)

### System information

Windows - RTX 4070

### Issue description

Animations are either not loaded correctly or not processed properly.

In the logs it's remarked that the skeleton data is missing:
![image](https://github.com/godotengine/godot/assets/1945449/7828fecb-125e-45aa-b4b6-fcd1a590132e)

I'm testing with GDQuests mannequin :
![image](https://github.com/godotengine/godot/assets/1945449/6e2bd72d-8404-4367-bffc-6d28a86dc8e8)

Often the model doesn't render at all until you select the skeleton node.

### Steps to reproduce

Obtain the mannequin model from GDQuests github repo here:
https://github.com/GDQuest/godot-3d-mannequin/tree/master/godot/assets/3d/mannequiny

Add it to a 3D scene in Godot.

Try and play the animations

### Minimal reproduction project

See above

**Comment by BastiaanOlij** [comment]
Bisect came up with this commit being the problem: https://github.com/godotengine/godot/pull/74405/commits/5a4613f5512b84a758d7cb4850f6e35db2bcceba

**Comment by BastiaanOlij** [comment]
Bisect came up with this commit for the first time the `skeleton->size == 0` error: https://github.com/godotengine/godot/commit/98c655ec8db17e50afa58284b1dcad754034db4b

**Comment by akien-mga** [comment]
CC @reduz @RandomShaper @godotengine/animation
