### ISSUE TITLE
Built-in and custom shaders don't work on Android

### ISSUE THREAD

**Issue by eye776** [godotengine/godot#7724]
**Operating system or device - Godot version:**
ZTE Blade A512, Android 6.0 - 2.1.2 stable
Editor was run on Windows 10 Pro 64 bit

**Issue description:**

Created two nodes, one with Lambert shading another one with Toon shading a camera node and a directional light node.
On Windows everything looks as expected: Two nodes with different shading.
On Android both nodes look the same (Lambert Shading).
Additionally, in any custom shaders the following outputs are ignored NORMALMAP, NORMALMAP_DEPTH. The LIGHT output seems to ignore LIGHT_DIFFUSE.

**Steps to reproduce:**
Create a Spatial root node .
Create a DirectionalLight node. Translate it to 0,0,8 (translation doesn't matter).
Create a Camera node. Translate it to 0,0,5 (translation doesn't matter, except to see the node).
Create a MeshInstance or TestCube. Create a new FixedMaterial and set Shader to Toon.
Run the project on Android and notice the missing effect.

**Link to minimal example project:**
:
https://drive.google.com/open?id=0B5tiIcef5MMVQnJBeXNsNEM4aXc

**Comment by volzhs** [comment]
not sure, but... did you try to enable `use_fragment_lighting` and `fp16_framebuffer` at Scene > Project Settings > Rasterizer.android?

**Comment by eye776** [comment]
The `fp16_framebuffer` option wasn't needed (but it works), enabling `use_fragment_lighting` in Rasterizer.android makes the shaders work (both built-in and custom).
Looks like the issue was on my end all along. I'm really sorry for the trouble.

**Comment by LeonardMeagher2** [comment]
@eye776 should probably close the issue.

**Comment by volzhs** [comment]
I closed this if there is any other objection.

**Comment by MNchino** [comment]
Does use_fragment_lighting in Rasterizer.android still exist (as of 3.0.6)?  I cannot find it in the Project settings.

**Comment by letsgamedev** [comment]
Found my solution for this:
Rendering->Quality->Shading.
I just deactivated everything forced for mobile. That worked.

**Comment by AugustusCollins** [comment]
> Found my solution for this: Rendering->Quality->Shading. I just deactivated everything forced for mobile. That worked.

Tried it,
Mine is not still working

**Comment by AugustusCollins** [comment]
Normalizing the vectors in my shader worked and it gave me a much cooler effect.

**Comment by Calinou** [comment]
> Normalizing the vectors in my shader worked and it gave me a much cooler effect.

If not normalizing vectors led to broken shaders, it's likely because your vectors had very large components, causing floating-point precision issues.

Remember that for performance reasons, on Android, shaders use low precision (16-bit) by default. 16-bit floats will lose their precision much more quickly compared to 32-bit floats, with values as low as 30 showing significant precision errors.
