### ISSUE TITLE
Error when resizing PackedByteArray bigger than int32 limit

### ISSUE THREAD

**Issue by Gamemap** [godotengine/godot#77256]
### Godot version

4.0.3

### System information

Windows 11 64-Bit

### Issue description

The PackedByteArray can't be bigger than 2147483647. Following [this](https://github.com/godotengine/godot/issues/46842#issuecomment-842216412) issue it should be fixed in Godot 4.0 RC 1, but running the code below in Godot 4.0.3 results in this error.

```
E 0:00:00:0834   Node.gd:9 @ _ready(): Condition "p_size < 0" is true. Returning: ERR_INVALID_PARAMETER
  <C++-Quelle>   ./core/templates/cowdata.h:262 @ resize()
  <Stacktrace>   Node.gd:9 @ _ready()

```

### Steps to reproduce

Run this code:
```
	var INT32_MAX = 2147483647 # 2^31 - 1
	var byte_arr = PackedByteArray()
	byte_arr.resize(INT32_MAX) # OK
	byte_arr.resize(INT32_MAX + 1) # error
```

### Minimal reproduction project

[PackedByteArrayError.zip](https://github.com/godotengine/godot/files/11520507/PackedByteArrayError.zip)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/62585, https://github.com/godotengine/godot/issues/45296 and https://github.com/godotengine/godot/issues/54679.

[Making CowData use 64-bit unsigned integers is welcome](https://github.com/godotengine/godot/issues/54679#issuecomment-963081535), but it's a significant undertaking as it requires replacing the type in all places where relevant.
