### ISSUE TITLE
Export with embebed PCK fails with: [PCK Embedding]: Executable file header corrupted.

### ISSUE THREAD

**Issue by Michalkap28** [godotengine/godot#77254]
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Ubuntu 22.04

### Issue description

I tried exporting my game and I can't run it without or with embeded PCK.
When I try exporting with embeded PCK this error shows up: [PCK Embedding]: Executable file header corrupted.

### Steps to reproduce

idk

### Minimal reproduction project

[SKY_MULTI.zip](https://github.com/godotengine/godot/files/11519275/SKY_MULTI.zip)

**Comment by Michalkap28** [comment]
It doesn't work on windows version either

**Comment by Michalkap28** [comment]
And exporting to windows also fails

**Comment by Michalkap28** [comment]
I tried re-installing godot and export templates, but it didn't help

**Comment by Michalkap28** [comment]
Exporting on 4.0.2 works just fine

**Comment by Michalkap28** [comment]
It does not work on 4.0.2 either

**Comment by Michalkap28** [comment]
I think, that something is broken in my project

**Comment by Michalkap28** [comment]
But i can't find it

**Comment by akien-mga** [comment]
Please use the edit button to add new information to your previous posts. It's much easier to follow a discussion where findings are reported clearly in one or two posts as opposed to following your raw thought process over 7 consecutive posts.

**Comment by akien-mga** [comment]
So far this seems to have affected only two users, and on very different versions of Godot.

Since @cullumi mentions it works in 4.2.1 and doesn't work in 4.2.2, I suspect that the problem both of you experienced is a corrupted export template download.

@cullumi Could you try to reinstall the export templates for 4.2.2 and check if that solves it?

For the record, here are the sha/md5 sums of the `windows_release_x86_64.exe` export template I have here for 4.2.2.stable, which exports your MRP fine with embedded PCK.

```
$ sha512sum ~/.local/share/godot/export_templates/4.2.2.stable/windows_release_x86_64.exe 
bed517fe8c160483df69fa0748330e8c5c0d3124f5468147aee19ca62d5dda5483cb287e42fb7c638c3f78eea521b99c31660a7a25726b69432493b9da4c068c  /home/akien/.local/share/godot/export_templates/4.2.2.stable/windows_release_x86_64.exe
$ sha256sum ~/.local/share/godot/export_templates/4.2.2.stable/windows_release_x86_64.exe 
0abfdc1fcae18e128a2dc6a1f5f8f5b717060929e62548e3d5efcd4124311388  /home/akien/.local/share/godot/export_templates/4.2.2.stable/windows_release_x86_64.exe
$ md5sum ~/.local/share/godot/export_templates/4.2.2.stable/windows_release_x86_64.exe 
7a90bbaeb1ce492144772d86bf513f7d  /home/akien/.local/share/godot/export_templates/4.2.2.stable/windows_release_x86_64.exe
```

**Comment by cullumi** [comment]
Oh yep you're absolutely right-- I reinstalled the 4.2.2 export template and it seems to work fine now. Thanks for taking a look @akien-mga ! 😄

**Comment by akien-mga** [comment]
Great! I'll close this as the second report was a corrupted download, and the first report isn't really actionable, but is likely a similar situation.
