### ISSUE TITLE
Armature Skeleton - crash

### ISSUE THREAD

**Issue by dynaweave** [godotengine/godot#77267]
### Godot version

4.0.3

### System information

Windows 11 Pro

### Issue description

Godot crashes on selection of skeleton node

### Steps to reproduce

I imported a character from blender with animations. The rig was generated using autorig pro. It was imported as a .glb. 
I created a scene from it, but when clicking the skeleton node, the app crashed and closed without warning.

### Minimal reproduction project

Files too large to upoad here.

**Comment by KoBeWi** [comment]
Well not much can be done without the affected model. You could upload it to some file hosting service.
