### ISSUE TITLE
[v4.0.3.stable.mono] C# ERROR: FATAL: Condition "!match" is true.

### ISSUE THREAD

**Issue by enxas** [godotengine/godot#77269]
### Godot version

v4.0.3.stable.mono.official.5222a99f5

### System information

Windows 10 22H2

### Issue description

Related issue #70449
Edit: Didn't realized that this fix haven't been merged yet  #75188
Game randomly crashes when playing. This is what is printed to the console. 

```
ERROR: FATAL: Condition "!match" is true.
   at: ~CSharpInstance (modules/mono/csharp_script.cpp:2021)
Fatal error. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Godot.NativeInterop.NativeFuncs.godotsharp_internal_refcounted_disposed(IntPtr, IntPtr, Godot.NativeInterop.godot_bool)
   at Godot.GodotObject.Dispose(Boolean)
   at Godot.GodotObject.Finalize()
```

### Steps to reproduce

Not sure, it happens randomly

### Minimal reproduction project

1. Launch the game
2. Right mouse click on an enemy to shoot a bullet
3. Do nothing else for 30 seconds and the game crashes

[MRP.zip](https://github.com/godotengine/godot/files/11521696/arpg_project.zip)

**Comment by AThousandShips** [comment]
#75188 has not been merged how do you mean it didn't fix it?

**Comment by enxas** [comment]
Oh, I didn't notice that this fix haven't been merged yet
