### ISSUE TITLE
Setting lights Shadow Mode to Cube turns off shadows

### ISSUE THREAD

**Issue by razcore-rad** [godotengine/godot#77270]
### Godot version

v4.0.3.stable.official [5222a99f5]
Vulkan API 1.3.224 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 2060

### System information

Ubuntu 23.04, Vulkan, NVIDIA GeForce RTX™ 2060 / NVIDIA GeForce RTX™ 2060, NVIDIA Driver Version: 525.105.17, NVML Version: 12.525.105.17

### Issue description

There must be some hardware issue here, but on my setup using `ShadowMode.SHADOW_CUBE` turns off shadows.

### Steps to reproduce

1. Open `godot-4-dbg` project.
2. Make `scene.glb` into a new inherited scene.
3. Make sure to toggle off the sunlight preview.
4. Select `Light`.
5. Turn on shadow.
6. Make sure `Shadow Mode` is set to `Cube`.
7. Notice that shadow is missing.
8. Switch `Shadow Mode` to `Dual Paraboloid`.
9. Notice that shadow is showing.

https://github.com/godotengine/godot/assets/1177508/1981172d-931c-4a64-b152-94f95f5bdc04

### Minimal reproduction project

[godot-4-dbg.zip](https://github.com/godotengine/godot/files/11521712/godot-4-dbg.zip)

**Comment by Calinou** [comment]
The light has an extremely long range (4096). The shadow is not only very blurry, but it's culled entirely due to the shadow bias being relative to the light's range.

**Comment by razcore-rad** [comment]
I see, that's fine then. I checked that exporting with a custom distance from Blender produces correct results

![image](https://github.com/godotengine/godot/assets/1177508/44c6aef3-cb10-47ce-b405-4951b1ad775f)

Only thing left for lights in my opinion is to also transfer the shadow on/off state:

![image](https://github.com/godotengine/godot/assets/1177508/7eaa6fbc-0137-43b4-9af7-9b1837163193)

![image](https://github.com/godotengine/godot/assets/1177508/23acb8ff-e8c9-4ff6-b1b4-253b577a2622)

We still need to turn enable shadow manually. But I don't know if this is a Blender-gLTF-export issue or a Godot-import issue. I'll search for related issues to this and open a separate report for that case.

So all good, thanks.
![image](https://github.com/godotengine/godot/assets/1177508/9ee28d5d-6b65-443f-8af5-a5f8e2e08a8d)
