### ISSUE TITLE
Excessive capturing of touch events in web export causes zoom lock

### ISSUE THREAD

**Issue by eska014** [godotengine/godot#7729]
Web export consumes most input events.
For touch events, this is problematic on mobile devices: If a player zooms in on the page before the game starts, they can no longer use pinch gestures on the canvas to zoom back out after game has started. If the canvas is maximized, this makes it entirely impossible to zoom out.

**Comment by eska014** [comment]
As far as I know, there's no way to tell if a browser's touch event is pinch gesture, so we can't just make exceptions for them.
I also don't think it's possible to delay the decision (capture or not?) until the event has gone through the main loop to see if it's set as handled or not.

Maybe the only solution is to use a function in `OS` to set whether the browser's input events are captured or not.

As a side note, we currently use GLUT for pointer events, which handles touch events as mouse events. So first we need to implement actual touch event handling.

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by eska014** [comment]
Fixed by #21336
