### ISSUE TITLE
Text Incorrectly Wrapping in Tree Items

### ISSUE THREAD

**Issue by joao-pedro-braz** [godotengine/godot#77296]
### Godot version

v4.1.dev.custom_build [809a98216]

### System information

Linux X11, Vulkan, Forward+, RX6600XT

### Issue description

Recently noticed a regression in which the text of Tree Items incorrectly wrap to the next line instead of collapsing/eliding  upon an overflow.

### Steps to reproduce

This can be easily reproduced by just opening the Editor and using a long enough name for either a Node or a File (Both the SceneTree and the FileSystemTree are affected), like below:

SceneTree:
![image](https://github.com/godotengine/godot/assets/37230465/8ab8c611-478c-45b9-8e00-9e94ea77b621)

FileSystemTree:
![image](https://github.com/godotengine/godot/assets/37230465/d55f5b05-f12b-49d4-9888-5fa454f90a8e)

### Minimal reproduction project

N/A

**Comment by dalexeev** [comment]
Duplicate of #77067.

**Comment by joao-pedro-braz** [comment]
@dalexeev Closing due to being a duplicate.
