### ISSUE TITLE
Refusal to open a scene with a syntax error in the embedded script

### ISSUE THREAD

**Issue by Miskler** [godotengine/godot#77311]
### Godot version

4.0.3.stable

### System information

Win 10, i5-11400H, 16GB RAM, RTX3050M

### Issue description

![image](https://github.com/godotengine/godot/assets/69055489/edb7f792-1148-45ed-bb71-0be3fbd246df)
The scene does not load due to the fact that there is a syntax error in the embedded script. Of course, I can't fix the script because it is built-in (except through an external editor). This behavior is abnormal, the scene should still load even if there is an error in its script.
Breaking the scene code example:
```
var dirSAV = DirAccess.new()
var path = \"user://SaveGame/Worlds/\" + str(name_save)
if !dirSAV.dir_exists(path):
	dirSAV.make_dir_recursive(path)
```

### Steps to reproduce

Create a project in 3 godot create a scene there with a built-in script, for example, create a folder, then transfer the project to 4 godot and try to open the scene.

### Minimal reproduction project

Link to my repository - https://github.com/Miskler/kHUTER
Branch `godot4`

**Comment by AThousandShips** [comment]
It isn't a syntax error it's a formatting error in the file, seems to be a failure to escape quotes correctly when converting projects

**Comment by Miskler** [comment]
@AThousandShips so the transition module from the 3rd generation to the 4th generation cannot process the built-in scripts correctly?

**Comment by Miskler** [comment]
For large projects this is a very big problem as fixing these errors takes a very long time

**Comment by Miskler** [comment]
![image](https://github.com/godotengine/godot/assets/69055489/311f1a19-3f53-4922-b6cf-b74c5b6f40e8)
I want to draw attention to the fact that this error is not found everywhere

**Comment by AThousandShips** [comment]
It is in your example?

**Comment by Miskler** [comment]
yes

**Comment by AThousandShips** [comment]
Where is it not? Note that the other "\\\"" are from the original 3.x code

**Comment by AThousandShips** [comment]
Working on a fix for this
