### ISSUE TITLE
NavigationServer3d::map_get_closest_point() always returns Vector3(0,0,0)

### ISSUE THREAD

**Issue by lucasrafael98** [godotengine/godot#77315]
### Godot version

4.0.2

### System information

Fedora Linux 37 (AMD Ryzen 7, RTX 3060)

### Issue description

When calling map_get_closest_point() to get the closest navigable location to any given point, the return is always (0, 0, 0). Here's the sample code on the reproduction project:

```gdscript
extends CharacterBody3D

@onready var map_rid: RID = get_node("/root/Node3D/NavigationRegion3D").get_region_rid()

func _physics_process(delta):
	print(NavigationServer3D.map_get_closest_point(map_rid, Vector3(0,0.25,0))) 
```

### Steps to reproduce

- Create a NavigationRegion3d and a script that tries to call map_get_closest_point() and print it
- Run the game with the script attached to some object
- This should start printing (0, 0, 0)

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/11525061/test.zip)

**Comment by smix8** [comment]
You are querying the navigation map with a navigation region RID, not a map RID.

You get the default 3d navigation map RID with `get_world_3d().navigation_map`.

**Comment by lucasrafael98** [comment]
My bad. Works perfectly now, thanks!
