### ISSUE TITLE
NavigationRegion3D Bake NavMesh gives undesirable results

### ISSUE THREAD

**Issue by NickSw1ft** [godotengine/godot#77332]
### Godot version

4.0.3.stable

### System information

Windows 10

### Issue description

NavigationRegion3D Bake NavMesh creates starge shaped polygon when with both default values and after trying to tweak something. Tried with both CSG and Meshes. Also tried by using CSGCombiner. Nothing works properly.
![image](https://github.com/godotengine/godot/assets/66752733/e4812bd1-4a49-4754-8b57-c16b294ac963)
![image](https://github.com/godotengine/godot/assets/66752733/fbf4f87a-14e3-474a-8ab9-0bd83cdbe58e)

### Steps to reproduce

- Create a 3D Scene
- Add NavigationRegion3D node
- Add two CSGBox (or MeshInstance3D with Box Meshes) nodes as children of NavigationRegion3D. One for floor and one as an obsticle. Make floor bigger and line obsticle so that it is on top of the floor.
- Bake NavMesh

### Minimal reproduction project

[mrp.zip](https://github.com/godotengine/godot/files/11528516/mrp.zip)

**Comment by AThousandShips** [comment]
What is the issue here? The mesh looks fine to me, what are you expecting/wanting?

**Comment by NickSw1ft** [comment]
> What is the issue here? The mesh looks fine to me, what are you expecting/wanting? Is it that the mesh doesn't fit perfectly around the obstacle?

Yes. In tutorials it fits almost perfectly with mush more complex scenes e.g. this: [https://www.youtube.com/watch?v=-juhGgA076E&t=267s](url)

**Comment by AThousandShips** [comment]
First, you need to format your links correctly, you're linking to just "URL"

Second, have you changed that setting?

**Comment by NickSw1ft** [comment]
Yes, it produces expected results when cell size is set to 0.01, which is the smallest possible value. But only when set to this minimum.

**Comment by NickSw1ft** [comment]
As this obsticle is on integer coordinates and is interger sized with no rotation, I would expect that with 0.25 cell size navmesh would look something like this:
![image](https://github.com/godotengine/godot/assets/66752733/af176823-5d10-463d-aa75-f93d766413dc)
I found a workaround by setting cell size to minimum possible value, but afraid that it may cause futere problems with pathfinding, performance and baking navmeshes for larger scenes

**Comment by AThousandShips** [comment]
I suspect that making the navmesh that exact isn't useful nor would I expect it to be "neat", there is a very slight deviation from the radius I'd say but it's very slight, only a small area would be inaccessible where it technically should be included

**Comment by NickSw1ft** [comment]
I guess no, it doesn't. Just expected it to be looking nicer. Should be closed then, thank you for your time

**Comment by AThousandShips** [comment]
I mean there might be things to investigate here, if it does affect the usability of the navmesh

**Comment by smix8** [comment]
This is somehow expect as a result of the rasterization and the edge contour post-processing of the navigation mesh baking process.

Large planes with an obstacle in the middle create the worst case scenario for the default properties of the NavigationMesh.

If you lower the `edge_max_length` property value on the NavigationMesh you can see more clearly the grid cells affected by your source geometry. You will see that there are grid cells on the edges affected around you box that ideally shouldn't but this is sometimes not really avoidable due to precision errors with floats. This is basically the layout that the edge contour step in the navigation mesh baking process gets to work with which creates this "randomly" formed looking edges around your box.

**Comment by NickSw1ft** [comment]
I think you are right, but adding more objects and/or moving obsticle from center of the plane doesnt resolve theese isues. So the only way to get a clean looking navmesh is by cranking down the cell size
![image](https://github.com/godotengine/godot/assets/66752733/eb6ee1bc-a53d-4074-8def-b37ca3ed16e9)

**Comment by smix8** [comment]
This is primarily a precision problem. By lowering the cell size your are increasing the precision due to creating more voxel cells for the rasterization.

The reason why such a lower value is not the default value on the NavigationMesh is because more voxel cells cost more performance to process and it is entirely level layout and scale depending if the default values are not sufficient.

**Comment by NickSw1ft** [comment]
Is it one time cost while baking navmesh or it will also cast when calculating paths in runtime?

**Comment by NickSw1ft** [comment]
Thank you for your answer! So I can just crank it down and bake once everything is set

**Comment by smix8** [comment]
You will need to adjust the NavigationServer navigation map cell size as well.

You can change the default navigation map cell size in the ProjectSettings in the "Navigation" tab visible with advanced settings enabled. Or you can use the NavigationServer API to change a navigation map cell size at runtime with `NavigationServer3D.map_set_cell_size(get_world_3d().navigation_map, new_cell_size_float)`

The navigation map merges navigation meshes by also placing the vertices into a grid. The default cell size is 0.25 same as the NavigationMesh so if you went for a lower cell size on the NavigationMesh you also need to match it with the navigation map.

If the NavigationMesh cell size and the navigation map cell size are different sometimes the two vertices of an edge will land into the same grid cell (your error msg) which will make the navigation map fail the navigation mesh merge.

**Comment by smix8** [comment]
Closing as there have been new error msg added with the 4.1 release for this mismatch cases of navigation mesh cell sizes and navigation map cell sizes that tell users what they need to do to fix this error.
