### ISSUE TITLE
HTML export fails to load when hosting on a server

### ISSUE THREAD

**Issue by MysterE-vW** [godotengine/godot#77336]
### Godot version

3.5.2

### System information

GLES2

### Issue description

After exporting a (3D with GLES2) project to HTML5, it runs really well locally(both via the run-in-browser-button and a python server). When trying to host it on a server however, it loads the game (the progressbar fills al the way) and then it just shows a spinner forever no matter the project's size. After inspection in Edge and Chrome, the console shows:

>  Uncaught (in promise) CompileError: WebAssembly.instantiateStreaming(): extra bits in varint @+3146210 

If it helps, in Firefox it instead says:

> Uncaught (in promise) CompileError: wasm validation error: at offset 3146211: expected number of function body bytes

I haven't been able to find any useful information about the error and its possible causes, let alone how to fix it. Is it a bug, or something I did or didn't do? 

### Steps to reproduce

In case reproducing can actually result in the same situation:
- make a new project targeting GLES2 with a few simple 3D objects
- Not sure if it's neccessary, but I ticked Import ETC (doesn't seem to contribute to the problem)
- export to HTML5 
- run it on a server that isn't local

### Minimal reproduction project

N/A

**Comment by Zireael07** [comment]
Attach a MRP. If you triggered it with a "few simple 3D objects" it should only take you a couple of minutes.

Also: what is your server? I recall some people having issues due to some settings on the host server...

**Comment by MysterE-vW** [comment]
It was not my own server, but someone else's. After figuring out how to host one myself, the problem never showed up on my own server. So the good news is that it works and should work for anyone putting it on their own server, the bad news is that I haven't been able to figure out what went wrong in the first place(I also cannot access whatever is happening on the server that gave this issue). I guess this issue can be ignored if no one else has encountered it.
