### ISSUE TITLE
Physical Keycode and Key Label options appear grayed out in the input editor when editing an existing key

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#77334]
### Godot version

4.0.2.stable

### System information

Fedora 37, GeForce RTX 4090 (NVIDIA 530.41.03)

### Issue description

Physical Keycode and Key Label options appear grayed out in the input editor when editing an existing key, even though I should logically be able to change it:

![image](https://github.com/godotengine/godot/assets/180032/54d4c3a5-4da5-4448-b42a-42f0c6870cc2)

If I set the key to another key then change it back, then the **Physical Keycode** and **Key Label** options are no longer grayed out.

cc @bruvzg

### Steps to reproduce

- Open the Project Settings > Input Map tab.
- Create an action, with an associated key. Save it.
- Click the edit button next to the key, and try to change the type without touching the actual key's value.
- Change the key's value back and forth and try to change the type using the dropdown again.

### Minimal reproduction project

N/A

**Comment by bruvzg** [comment]
Input map save only one value, and it's not always possible to convert one type of keycode to another (at least for Unicode → other), but I guess for the cases conversion is possible it should be available.
