### ISSUE TITLE
Gradient editor: clicking inside handle area (and even a little outside) to select handle moves it to exact cursor position

### ISSUE THREAD

**Issue by hsandt** [godotengine/godot#77340]
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Linux Ubuntu 22.04 with Unity desktop

### Issue description

Also tested on: v3.5.2.stable.official [170ba337a]

When clicking on a gradient handle to select it (generally just to change color), the gradient handle moves to the exact click position (the handle rectangle centers around it on X). This happens even if you don't drag the mouse at all before release. You can click anywhere in a small rectangle surrounding the whole handle (including the thin segment at the top) to trigger it.

This makes it very hard to change a color without messing up handle positions, except when they are on the edges (in which case you can still snap them to the edge later).

The handles should (1) move move on simple click, and ideally I'd say they should (2) not move when accidentally moving the mouse by a few pixels too, but that part would be more complex to design (how to define a simple click: a click that is a. short enough in time, or b. that doesn't move a lot? a. would prevent users who do a quick long drag to move handles, b. would prevent users who very slowly try to move the handle by a few pixels on purpose to make it move; maybe a combination of time and distance check would work)

I would have to try the gradient editor a little once (1) is fixed and see if I still accidentally move the handle and we need (2).

For now, consider that this issue is about (1) only.

### Steps to reproduce

1. Create any node with Gradient Color, such as CPUParticles2D > Color > Color Ramp
2. Create a new gradient
3. Click on a handle at different places inside and near the handle rectangle at the bottom and also the thin segment at the top
4. Note that when you click near enough but not on exact center, the handle moves slightly to match exact click position, even if you don't release the mouse

![Godot 4 0 2 - click inside or near handle moves it](https://github.com/godotengine/godot/assets/1067772/fed775d1-4b46-4555-9b8d-17cca9567254)

### Minimal reproduction project

N/A

**Comment by hsandt** [comment]
Note that https://github.com/godotengine/godot-proposals/issues/6555 and its PR https://github.com/godotengine/godot/pull/71915 can solve part of the issue with snapping; but if user doesn't use snapping at all, I fear it won't work (unless dev also fixes this issue on the go, didn't check the code changes but if someone wants to work on a PR for my issue, they may want to have a look at their PR just in case)

**Comment by MewPurPur** [comment]
I can't reproduce it at all, even though I'm also on Ubuntu 22.04, thus my PR probably doesn't fix it. My assumption would be that whatever problem you're having, it runs deeper than just the gradient editor. For example, does this also happen in the Curve editor?

**Comment by hsandt** [comment]
4.0.2 still has the issue.

4.1: I cannot repro with perfect (non-moving) click indeed.

Slightly moving the mouse as mentioned in point (2) will indeed move the gradient to new cursor position center. However, the threshold before a significant mouse motion is detected (basically 1px on screen) is now high enough that I don't accidentally move a gradient key. We'd have to see if other users have troubles with this, but as I said in point (2), it's a more complicated issue because some users may _want_ pixel precise displacement to a nearby position.

I don't know what changed between 4.0.2 and 4.1, but since issue point (1) is fixed, I consider this closed.
