### ISSUE TITLE
Vulkan: LightmapGI has incorrect indirect light probes when using static directional light

### ISSUE THREAD

**Issue by jcostello** [godotengine/godot#77356]
### Godot version

v4.1.dev.custom_build [437041a98]

### System information

Ubuntu with Nvidia 2060

### Issue description

When baking static directional light, lightmap probes don't work as expected like with dynamic bake.  

Dynamic Bake
![Screenshot from 2023-05-22 12-43-42](https://github.com/godotengine/godot/assets/1168582/269a235e-9a3b-406d-b36c-248df1ff915c)

Static Bake
![Screenshot from 2023-05-22 12-44-52](https://github.com/godotengine/godot/assets/1168582/0e9fb7e9-e683-4d3a-946d-0db513ea4f47)

### Steps to reproduce

Use MRP

Bake directional light as dynamic 
Disable and enable sphere mesh to apply probes lighting

Bake directional light as static
Disable and enable sphere mesh to apply probes lighting

See the same result as image above

### Minimal reproduction project

[lightmap.zip](https://github.com/godotengine/godot/files/11533271/lightmap.zip)

**Comment by atirut-w** [comment]
Seems to still happen on v4.1.stable.official [970459615]. Here are screenshots with probe gizmos enabled:

Dynamic(default)
![image](https://github.com/godotengine/godot/assets/25323231/bd5019b4-aaff-4f8a-8865-f0ecae88528d)

Static
![image](https://github.com/godotengine/godot/assets/25323231/23529cde-4f60-4ffb-a65f-ac74a158924d)

This doesn't affect just directional lights either. I tested this with omni and spot lights and they are both affected:

![image](https://github.com/godotengine/godot/assets/25323231/bf87c810-6b16-4458-b40b-b63c7c7057bc)

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/49936.

**Comment by jcostello** [comment]
https://github.com/godotengine/godot/pull/82068 Fixes the issue
