### ISSUE TITLE
AnimationTree Advance Expression is ignored (State Machine Tree transition never happens)

### ISSUE THREAD

**Issue by alfredbaudisch** [godotengine/godot#77355]
### Godot version

4.0.3-stable

### System information

Windows 10

### Issue description

The value from an Advance Expression in a `AnimationNodeStateMachineTransition` in a State Machine in an AnimationTree seems to be completely ignored.

The transition is never performed, even when setting the value of the advance expression to a raw `true`.

### Steps to reproduce

- Add an AnimationPlayer and AnimationTree
- In the root node, add a script with a boolean variable like `@export var is_running := false`
- Add a StateMachine in the AnimationTree
- Assign the root node into the AnimationTree Advance Expression Base Node.
- Add 2 animations and create transtions between them in the StateMachine, and set the Advance Expression to `is_running` and the way back to `not is_running`:

![imagen](https://github.com/godotengine/godot/assets/248383/d10c86ab-93dc-4997-9880-f8ddaab2bd80)

![imagen](https://github.com/godotengine/godot/assets/248383/f2f4cb12-3d23-4d37-8008-27e8fd4dd15c)

![imagen](https://github.com/godotengine/godot/assets/248383/f57abd3c-fce9-4ccf-97b6-8453975eb81c)

### Minimal reproduction project

[AnimationTreeAdvance.zip](https://github.com/godotengine/godot/files/11533177/AnimationTreeAdvance.zip)

Press Toggle Move, it should transition to the "Move" state, but it is currently doing nothing:

![imagen](https://github.com/godotengine/godot/assets/248383/083d6f4e-6599-49d1-94a1-a22bb8d2e7e7)

**Comment by fire** [comment]
Try putting the script on the animation tree

**Comment by alfredbaudisch** [comment]
> Try putting the script on the animation tree

No effect.

Even by changing here:

![imagen](https://github.com/godotengine/godot/assets/248383/f7fd3cde-93ca-4ae2-8ffe-25ed48806ced)

And then of course attaching the script there. Still no difference.

**Comment by fire** [comment]
[AnimationTreeAdvanceModded.zip](https://github.com/godotengine/godot/files/11535698/AnimationTreeAdvanceModded.zip)

I modified the animation tree project. 

Is it supposed to be like this?


https://github.com/godotengine/godot/assets/32321/228b6ca1-3d67-43f7-b0f1-c3aab02a38bf

**Comment by alfredbaudisch** [comment]
Thanks, I checked the project, that works. I'll see if I open a PR with more clarification in the docs.

**Comment by fire** [comment]
I modified the function to change state on up and down. Separated the functions. (removed the toggle)
