### ISSUE TITLE
Korean input not properly work of TextEdit control on Android system. (+proposal)

### ISSUE THREAD

**Issue by bugcaptor** [godotengine/godot#7735]
**Operating system or device - Godot version:**
Android - Tested on godot engine 2.1 branch recent.

**Issue description:**
In Android, when you type Korean characters, only the first consonant of the combined character will be entered and will be passed to next composition without the previous combination result applied. This is the result of receiving only the keystrokes without using the Android composition result. Only the callback of GodotTextInputWrapper will be called without any key events occurring during the compositing.

The final solution I think is that the input system itself is going to get the synthesis result of the OS, but I think the changes are going to be big, so I made it to work with small modifications first.

It clears the latest character including the characters in the composition, and replaces the last two(or one) character(s) with the characters provided by android TextView.OnEditorActionListener.

Following is the change I made.
Https://github.com/bugcaptor/godot/tree/fix-android-korean-input
That is based on master branch, but it can be merged on 2.1 branch because that file is same.

I have not tested this issue on iOS.

**Steps to reproduce:**
Type Korean characters in TextEdit on Android device.

**Comment by bojidar-bg** [comment]
Please, make a PR, instead of just linking random branches in random issues -- that would help the discussion centered around the code to be seperate from the discussion about the issue itself :smiley:

**Comment by bugcaptor** [comment]
OK. It looks different from what I intended. I thought it would be easier to see the changes.

I was not sure which branch would be good. But it looks good to make PR on the 2.1 branch which is good to test build rather than on the unstable master branch. The application of the changes will be the problem after that.

Thanks for reply.

**Comment by volzhs** [comment]
closed as #7936 is merged now.
