### ISSUE TITLE
At certain angles, `GPUParticles3D` does not render, `CPUParticles3D` works normally

### ISSUE THREAD

**Issue by zedrun00** [godotengine/godot#77365]
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

win10 21H2,Vulkan API 1.2.0

### Issue description

https://github.com/godotengine/godot/assets/104408400/3a0dd566-2b5c-4c43-9c78-351705a8663b

### Steps to reproduce

look video

### Minimal reproduction project

[project](https://github.com/godotengine/godot/files/11536005/test.zip)

**Comment by JBrowne017** [comment]
> @lyuma I wonder if it's related to the culling meshes (similar to lod mesh culling)?

This would be my first thought as well. Some form of frustum culling.

**Comment by Calinou** [comment]
This is because your GPUParticles extends outside its AABB used for culling. Use the **GPUParticles3D** menu at the top of the 3D editor viewport to generate a new AABB that matches the actual particle motion.
