### ISSUE TITLE
Godot 3 (editor) Ctrl+Up/Down (move  node) : focus goes to other control before moving node  

### ISSUE THREAD

**Issue by d-j-a-y** [godotengine/godot#7736]
**Operating system or device - Godot version:**
Linux / Godot 3.0 ( 5cc63de )

**Issue description:**

Editor : Focus on scene panel , Ctrl+Up/Down is use move up/down the node.
What happen is the focus goes to other control ( [+] , [node filter edit],  ...) before actually moving the node

**Steps to reproduce:**
In scene node hierachy, select to down child node , hit Ctrl+Up 4times before selected node actually move. 

**Link to minimal example project:**
:

**Comment by Hinsbart** [comment]
Seems to be caused by 9100db7 (CC @Faless )

**Comment by Faless** [comment]
> Seems to be caused by 9100db7 (CC @Faless )

Likely so.
Apparently ignoring keyboard modifiers (CTRL/ALT/etc.) was a behavior coming from the old times as stated in #7649 .
I think the fix here is to either change how keyboard focus navigation works in `viewport.cpp` (fix it via script) or go for [option 3 here](https://github.com/godotengine/godot/issues/6826#issuecomment-275157885) (#6826) (which will fix the problem intrinsically).
@reduz ?

**Comment by Faless** [comment]
> or go for [option 3 here](https://github.com/godotengine/godot/issues/6826#issuecomment-275157885) (#6826) (which will fix the problem intrinsically).

I implemented the "mod_ignore" option for events in the action map with [this commit](https://github.com/Faless/godot/commit/568ebb1c264d78d0b6aed9f9b998cd2803b4e47b) but it's still missing the Editor UI for setting the option.

So to enable it you either have to set it via code or hack the `godot.cfg` file like I did in this demo project:

[inputtest_mod_ignore.tar.gz](https://github.com/godotengine/godot/files/904108/inputtest_mod_ignore.tar.gz)

Comments are welcome

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by williamd1k0** [comment]
Since #17633 was closed, I think this issue should be added to 3.1 milestone.
