### ISSUE TITLE
Editor crashes when replacing built C# dlls

### ISSUE THREAD

**Issue by Avantir-Chaosfire** [godotengine/godot#77370]
### Godot version

5dc093b19a26b5055ceecaf1e1076bb5b4529a5a

### System information

macOS 13.3.1

### Issue description

Note: I first encountered this issue in 4.0.3-rc (didn't use Godot 4 versions before that) and reproduced it on the commit noted above. I did not have this issue on Godot 3.

When I started using Godot 4 and converted my C# Godot 3 project, I noticed it crashed when I tried to build. A lot of testing later, and I figured out that my editor crashes, exactly when:
1. I build my project
2. My project has changes (so the new dlls are different from the old ones)
3. The editor believes (rightly or wrongly) that there are already built dlls in `.godot/mono/temp/bin/Debug`

This means building a new project does not crash (because there are no dlls to overwrite). A non-clean build afterwards does crash. However, cleaning the build manually (deleting `.godot` or any part of its substructure) only prevents the crash if the editor is closed. So, "build -> make change -> delete `.godot` -> build" crashes the editor, but "build -> make change -> delete `.godot` -> close and reopen editor -> build" does not crash the editor.

Crash image and full log attached:

<img width="1877" alt="Crash Message" src="https://github.com/godotengine/godot/assets/11003232/96961d8f-bb34-4347-9e3f-166ad8d013b4">

[Editor Crash Report.txt](https://github.com/godotengine/godot/files/11536385/Editor.Crash.Report.txt)

### Steps to reproduce

1. Create a new project
2. Create a new scene
3. Attach a C# script to the root node
4. Save
5. Build
6. Make a change to the C# script (e.g. add a comment)
7. Build
8. Editor crashes

### Minimal reproduction project

[MRP.zip](https://github.com/godotengine/godot/files/11536226/MRP.zip)

**Comment by RedworkDE** [comment]
The crash is the same as #77343 / #68662; the underlying exceptions that ultimately triggers the crash may be different tho.

**Comment by Avantir-Chaosfire** [comment]
I forgot to mention that even when the editor crashes, the dlls ARE built and updated correctly.

**Comment by Avantir-Chaosfire** [comment]
Please reopen this issue. I was able to reproduce it on commit 3e88c4cd5c22e6e687ad88b148b0ef26d69c97eb, which is AFTER the commit that closed this issue.

**Comment by RedworkDE** [comment]
I dug out a mac to check if the issue is OS specific, but I still can not reproduce any issues with the provided project and reproduction steps.

I was able to confirm that the send to debugger crash from your screen shot is indeed fixed on commit c670c4334a6901410128f8b66a0ce7d097e66e5d (and yes I did confirm that I can trigger the crash on an older commit)

Please ensure that you are indeed running a build from a commit that includes that fix (the official dev3 build should do it, didn't test it specifically tho).

If the crash truly does persist, please post the output from `dotnet --info`, the full system info from https://github.com/godotengine/godot/pull/65902 (needs a build from todays master) and a new crash log.

**Comment by Avantir-Chaosfire** [comment]
@RedworkDE Strange. I tested latest master again (95c8216923fc9353ac50f469836ae149cb196e83) and it still crashes. No changes to the editor, just a normal mono build. Still get the crash upon modifying a script and building the project again.

```
% dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.100/

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  3.1.414 [/usr/local/share/dotnet/sdk]
  3.1.415 [/usr/local/share/dotnet/sdk]
  3.1.416 [/usr/local/share/dotnet/sdk]
  5.0.402 [/usr/local/share/dotnet/sdk]
  5.0.403 [/usr/local/share/dotnet/sdk]
  5.0.404 [/usr/local/share/dotnet/sdk]
  6.0.100 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.20 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.21 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.22 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.20 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.21 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by RedworkDE** [comment]
Still need an updated crash log (as text this time please) and godots terminal output, or there isn't really anything that can be said about this issue.

**Comment by Avantir-Chaosfire** [comment]
@RedworkDE Interestingly, the crashing has become inconsistent... But it still happens frequently. Seems if the editor doesn't crash on first build, it won't on subsequent ones either.

[Updated Crash Report.txt](https://github.com/godotengine/godot/files/11638319/Updated.Crash.Report.txt)

Not pasting the crash report as plain text as it is simply too massive...

Godot terminal output (not sure if this just the project selector output, since it seems that launches a separate process...):
```
bin % ./godot.macos.editor.x86_64.mono
Godot Engine v4.1.dev.mono.custom_build - https://godotengine.org
OpenGL API 4.1 ATI-4.12.7 - Compatibility - Using Device: ATI Technologies Inc. - AMD Radeon Pro 5700 XT OpenGL Engine
 
Editing project: /Users/Eddie/Desktop/CC & Gaming/Godot/Projects/Test
bin % Godot Engine v4.1.dev.mono.custom_build - https://godotengine.org
Vulkan API 1.2.243 - Forward+ - Using Vulkan Device #0: AMD - AMD Radeon Pro 5700 XT
 
WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:72)
Unloading assembly load context...
Assembly load context unloaded successfully.
Unloading assembly load context...
Assembly load context unloaded successfully.
ERROR: Attempt to disconnect a nonexistent connection from '@ConfirmationDialog@16959:<ConfirmationDialog#1125214378391>'. Signal: 'confirmed', callable: 'Delegate::Invoke'.
   at: _disconnect (core/object/object.cpp:1353)
ERROR: Attempt to disconnect a nonexistent connection from '<VBoxContainer#1125617031597>'. Signal: 'ready', callable: 'Delegate::Invoke'.
   at: _disconnect (core/object/object.cpp:1353)
ERROR: Attempt to disconnect a nonexistent connection from '@Button@16968:<Button#1126254565832>'. Signal: 'pressed', callable: 'Delegate::Invoke'.
   at: _disconnect (core/object/object.cpp:1353)
ERROR: Attempt to disconnect a nonexistent connection from '@PopupMenu@16967:<PopupMenu#1125885467061>'. Signal: 'id_pressed', callable: 'Delegate::Invoke'.
   at: _disconnect (core/object/object.cpp:1353)
ERROR: Attempt to disconnect a nonexistent connection from '<EditorSettings#-9223372010044783464>'. Signal: 'settings_changed', callable: 'Delegate::Invoke'.
   at: _disconnect (core/object/object.cpp:1353)
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
   at: _EDITOR_GET (editor/editor_settings.cpp:1117)
```

**Comment by enxas** [comment]
Could be related to this issue #69614

**Comment by RedworkDE** [comment]
No, the errors you see at exit are #76708, and should not be related to any crash.
