### ISSUE TITLE
Path completion for "unique name" nodes fills in the full path rather than only the node name

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#77375]
### Godot version

4.0.3

### System information

linux

### Issue description

consider a scene with a node marked as unique name:
![image](https://github.com/godotengine/godot/assets/71937306/eda6cb65-4b9d-40aa-ac10-bc5c31abe902)

Trying to access it leads to this:
![image](https://github.com/godotengine/godot/assets/71937306/f2d4089a-e571-4640-a02d-199d6e31e3cd)

which is not expected I think.

### Steps to reproduce

1. create a scene with a uniquely-named node that has a bunch of parents and grandparents
2. try to access this node via a script using the `%` operator, and notice how it gives you the full path as an autocomplete candidate.

### Minimal reproduction project

[UniqueNameAutocomplete.zip](https://github.com/godotengine/godot/files/11537220/UniqueNameAutocomplete.zip)

**Comment by KoBeWi** [comment]
Related: https://github.com/godotengine/godot-proposals/issues/4593 (the proposal might be outdated, because `%` shorthand didn't exist then)

**Comment by opyate** [comment]
Especially jarring if there are multiple options, but you can see what they are:

![image](https://github.com/godotengine/godot/assets/96808/27212910-8d53-4420-b2a9-7806e8fe706a)
