### ISSUE TITLE
Transparent Spatial Materials clip with Sprite3Ds

### ISSUE THREAD

**Issue by tacnoblode** [godotengine/godot#77374]
### Godot version

3.6

### System information

Windows 10, Ryzen 5 2600, GLES 3, Nvidia GTX 1080

### Issue description

Transparent spatial materials often clip with objects like Sprite3Ds, quads, and other transparent materials, causing these affected objects to render in front of said material.
![ss](https://github.com/godotengine/godot/assets/52140730/ec6224e0-76a2-4acd-9566-186a86b488e8)
![ss4](https://github.com/godotengine/godot/assets/52140730/50d37285-1cd6-4b4c-8896-659e163e8aa6)

### Steps to reproduce

1. Create a Spatial object (such as a mesh) and apply a SpatialMaterial on the object
2. Give the SpatialMaterial the "Transparent" flag and give it some kind of texture with transparency on it.
3. Create another Spatial object (a mesh or Sprite3D) with the same properties as above

Place these objects anywhere, and if one is in front of the other, the object that is behind it will render on top in certain angles.

### Minimal reproduction project

N/A

**Comment by Zireael07** [comment]
This is a common limitation of transparency sorting.

IIRC there is a Z priority setting on your 3d spatials, play around with that value to improve things

**Comment by Calinou** [comment]
This is not a bug: https://docs.godotengine.org/en/stable/tutorials/3d/3d_rendering_limitations.html#transparency-sorting
