### ISSUE TITLE
FloorI rounds towards zero again

### ISSUE THREAD

**Issue by MagnificentRay** [godotengine/godot#77386]
### Godot version

4.0.2-stable_linux.x86_64  4.0.3-stable_linux.x86_64

### System information

Linux mint x86_64, CPU: AMD Ryzen 7 GPU: AMD ATI Radeon RX

### Issue description

I'm having the exact same issue as described in this other issue:
https://github.com/godotengine/godot/issues/66500
And I wasn't sure if I should make a new issue, or comment on the other one, So I just made a new one.

The issue is when I use the floori() function it rounds towards zero instead of its described function of rounding towards negative infinity.
I've tested it in 4.0.0 4.0.1 4.0.2 and 4.0.3 and I'm still having this issue.

Here is my interpretation of the expected output:
(spaces added after to show where "regions" should end)
[-2,-2,-2,-2, -1,-1,-1,-1, 0,0,0,0, 1,1,1,1] region
[-8,-7,-6,-5, -4,-3,-2,-1, 0,1,2,3, 4,5,6,7] chunk

Here's the output I got:
[-2, -1, -1, -1,  -1,  0,  0,  0,   0, 0, 0, 0,  1, 1, 1, 1] region
[-8, -7, -6, -5,  -4, -3, -2, -1,  0, 1, 2, 3,   4, 5, 6, 7] chunk

The positive numbers look ok, but the negative numbers are one higher than they should be and shifted over 1 in the direction of zero.

I'm not to good at reading how Github works, but It looks like it says it was fixed here in September 2022:
https://github.com/godotengine/godot/pull/66505

But unfortunately in my case it is still not fixed. 

Any help would be greatly appreciated.

### Steps to reproduce

When the code provided in minimal reproduction project is run in it will print its output

### Minimal reproduction project

	var pos_c = []
	var pos_r = []	
	
	for p in range(-8, 8):
		pos_c.append(p)
		pos_r.append(floori(p / 4))
	
	print(str(pos_r, " region"))
	print(str(pos_c, " chunk"))

**Comment by AThousandShips** [comment]
This is probably because of an error on your end, it should be `p / 4.0`

**Comment by AThousandShips** [comment]
And confirmed with running it with correct code:
`[-2, -2, -2, -2, -1, -1, -1, -1, 0, 0, 0, 0, 1, 1, 1, 1] region`
`[-8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7] chunk`

**Comment by MagnificentRay** [comment]
@AThousandShips Thank you that fixed it.
