### ISSUE TITLE
Depth of Field and Screen Space Reflections seem to use faulty masks

### ISSUE THREAD

**Issue by jmf** [godotengine/godot#7739]
**Operating system or device - Godot version:**
Linux 4.8.11, godot  5cc63dee0f719139b263ac95027ce520843a9f5f (master)
NVIDIA Corporation GK106 [GeForce GTX 645 OEM] with nouveau driver, mesa 12.0.6

**Issue description:**
DOF and SSR seem to use a faulty mask, probably random memory.
The images show this behavior. In the first one, it looks like some other view of the aircraft is taken as mask for SSR, in the second image it looks like random memory garbage is used as mask.

**Images of the issue**
![SSR1](https://a.pomf.cat/gpeupp.png)
![SSR2](https://a.pomf.cat/rqkqae.png)

**Comment by reduz** [comment]
Weird, wonder if this is hardware related

**Comment by jmf** [comment]
This feature actually worked before. I ran git bisect and tracked it down to this commit:
c2a217c3501b8006a3d2cdf2c678e33def15f275 is the first bad commit

Date:   Sun Jan 1 22:16:52 2017 -0300

    WIP particle system
    Ability to enable and change MSAA settings
    Ability to change VCT quality
    Ability to enable/disable HDR rendering

**Comment by reduz** [comment]
ahh, seems i broke it when implemented MSAA

**Comment by jmf** [comment]
This appears to be fixed now in the latest version.
