### ISSUE TITLE
Crash when adding TileMap pattern

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#77391]
### Godot version

4.1 9dc2869

### System information

Windows 10 x64

### Issue description

When you add a pattern in TileMap, the editor crashes:
```
TilesEditorPlugin::_thread() Line 127 (c:\godot_source\editor\plugins\tiles\tiles_editor_plugin.cpp:127)
TilesEditorPlugin::_thread_func(void * ud) Line 63 (c:\godot_source\editor\plugins\tiles\tiles_editor_plugin.cpp:63)
Thread::callback(unsigned __int64 p_caller_id, const Thread::Settings & p_settings, void(*)(void *) p_callback, void * p_userdata) Line 63 (c:\godot_source\core\os\thread.cpp:63)
```
The crash seems thread-related.

There is a very brief delay, if you manage to save your scene before the crash, you won't be able to open it anymore until the pattern is removed.

### Steps to reproduce

1. Add TileMap
2. Add some TileSet
3. Draw some tiles
4. Select tiles
5. Drag them to Patterns tab

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
It crashes here:
https://github.com/godotengine/godot/blob/f581f21dd61a8fb581b80d07755cdf60c95d146d/editor/plugins/tiles/tiles_editor_plugin.cpp#L127
`get_texture()` returns null, because it's thread-guarded.

**Comment by RandomShaper** [comment]
Can somebody verify #77234 fixes this?

**Comment by KoBeWi** [comment]
Yes.
