### ISSUE TITLE
random Timer appears when copy pasting PathFollow2D

### ISSUE THREAD

**Issue by djrain** [godotengine/godot#77404]
### Godot version

4.0.3 stable

### System information

macOS Monterey

### Issue description

If you copy and paste any PathFollow2D node, the new pasted node has a seemingly random timer node as a child. This happens regardless of whether the PathFollow2D is under a Path2D. It does _not_ happen if you duplicate the node instead.

https://github.com/godotengine/godot/assets/33777501/6194ea71-3742-4fe2-8733-19517db57935

### Steps to reproduce

Add a PathFollow2D node in any scene, copy it, paste it anywhere.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Some error with copying and pasting nodes with internal nodes looks like
