### ISSUE TITLE
Editor crash when minimizing with "interface/editor/save_on_focus_loss" set to true

### ISSUE THREAD

**Issue by SleepyTonia** [godotengine/godot#77408]
### Godot version

4.1 dev 2

### System information

Linux Manjaro

### Issue description

If a project has a scene stored and open, when the editor loses focus the following line will flood the terminal:  
> ERROR: Task 'save' already exists.
       at: add_task (editor/progress_dialog.cpp:177)

This only happens following this sequence of events and if the editor setting "interface/editor/save_on_focus_loss" is set to true. Manually saving doesn't cause any issues. Saving just before minimizing doesn't prevent this either.

### Steps to reproduce

Create a new project, create a scene of any type and save it. Go in the editor settings and set "Save on focus loss" to true. Then all you need to do is minimize the window.

### Minimal reproduction project

[focus_loss.zip](https://github.com/godotengine/godot/files/11548199/focus_loss.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/73765.
