### ISSUE TITLE
Can't import image with 2px height into as TextureAtlas

### ISSUE THREAD

**Issue by andy-noisyduck** [godotengine/godot#77400]
### Godot version

3.5.2

### System information

Windows 10

### Issue description

When importing a texture (via the Import tab in the Editor) to a new TextureAtlas, the operation will fail if the texture only has a height of 2px. The console will contain the message: ```scene/resources/bit_map.cpp:37 - Condition "p_size.height < 1" is true.```

3px also does not work, but the same texture scaled to 4px high will import correctly.

Unsure if this also affects 4. I'm still working in 3.x LTS.

### Steps to reproduce

1. Create a new texture with one dimension being only 2px (I used 10x2 px).
2. Include this texture in to the project.
3. Switch the import type from Texture to TextureAtlas and set an appropriate output path.
4. Hit re-import (the operation will fail).

### Minimal reproduction project

[Testing-Atlas2px.zip](https://github.com/godotengine/godot/files/11546018/Testing-Atlas2px.zip)

**Comment by felaugmar** [comment]
Confirmed at v4.0.2.stable.official [7a0977ce2] too, same issue.

**Comment by AThousandShips** [comment]
Related to #68350, will look at a 3.x fix as well

**Comment by AThousandShips** [comment]
Would someone mind testing this for 3.x by building the PR

**Comment by felaugmar** [comment]
> Would someone mind testing this for 3.x by building the PR or downloading the artifact
> 
> https://docs.godotengine.org/en/latest/contributing/workflow/testing_pull_requests.html

Tested with textures `10x2px` and `10x1px`, it's working 👍🏼

**Comment by akien-mga** [comment]
Fixed by #77428.
