### ISSUE TITLE
Enabling SDFGI for the first time causes artefacts due to corrupted textures

### ISSUE THREAD

**Issue by josefkaragoli** [godotengine/godot#77427]
### Godot version

v4.0.3.stable.official

### System information

Windows 10, Vulkan (Forward+), GTX 1060

### Issue description

When turning on SDFGI for the first time, you will see highly bright lights or sometimes random colours. Sometimes it does not happen and seems to be very random.

https://github.com/godotengine/godot/assets/76781125/029d1e8b-7bc7-43b0-883b-a88fefb19548

I used Renderdoc, and I may have found the issue, though I have very little idea how to actually use this. I found 5 textures that were corrupted and all look like this:
![image](https://github.com/godotengine/godot/assets/76781125/5251dedf-3206-47f2-8b14-7220271372bc)

they are all labelled as VoxelGI though I think this is some mistake as my scene doesn't use voxelgi. Regardless, these textures seem to be the cause of the strange artefacts, because the issue seems to go away after some frames, and the textures return to normal.

these textures are:
lightprobe_history_texture
lightprobe_average_texture
lightprobe_history_scroll_texture
lightprobe_average_scroll_texture
lightprobe_average_parent_texture

### Steps to reproduce

Enable SDFGI for the first time in a scene, and you may see how the colours start off extremely bright and random, then slowly calm down to form a normal image.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/39961.
