### ISSUE TITLE
TileMap.set_pattern causing game to silently crash

### ISSUE THREAD

**Issue by thely** [godotengine/godot#77422]
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Mac OS 12.6.5 (Apple Silicon)

### Issue description

I'm trying to implement a city builder, using `TileMapPattern`s on a `TileMap` layer to (a) hover buildings as the mouse moves and (b) place them on click.

Problem is, when I attempt to use `TileMap.set_pattern(...)`, the game silently crashes. The Godot debugger isn't aware of anything, the editor itself is unaffected, but shortly after I always get an OS-level error (i.e., a separate popup showing that the error is some kind of segfault). I can dump the full error report, but these feel like the most relevant lines:

```
Exception Type:        EXC_BAD_ACCESS (SIGABRT)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000000000000027c
Exception Codes:       0x0000000000000001, 0x000000000000027c
Exception Note:        EXC_CORPSE_NOTIFY

VM Region Info: 0x27c is not in any region.  Bytes before following region: 105553518919044
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      MALLOC_NANO (reserved)   600018000000-600020000000 [128.0M] rw-/rwx SM=NUL  ...(unallocated)

Application Specific Information:
abort() called
```

### Steps to reproduce

1. Make a Node2D. Give it a script, and change its `_input(event)` function to the code below these steps.
2. Make a `TileMap` as a child of that Node2D. Give it a `TileSet`, and make at least one pattern for that `TileSet`.
3. Run the game, and press 1. The game will seemingly close itself without errors, but the OS will report a segfault.

```gdscript
func _input(event):
	if event is InputEventMouseMotion:
		mouse_tile = $TileMap.local_to_map($TileMap.get_local_mouse_position())
	
	if event is InputEventKey:
		if int(OS.get_keycode_string(event.keycode)) == 1:
			print(mouse_tile) # this also won't print if the line below is not commented out
			$TileMap.set_pattern(0, mouse_tile, 0)
```

### Minimal reproduction project

I can do this if needed, though the setup isn't very complicated.

**Comment by AThousandShips** [comment]
Related to #77391?

**Comment by akien-mga** [comment]
> Related to #77391?

It sounds related, but that one is a thread related regression in `master` while this one affects 4.0.3, which didn't have those thread changes. So it might be a different cause.

**Comment by vmedea** [comment]
Also, that one concerns patterns in the tilemap/tileset editor. It doesn't affect `set_pattern` on TileMap, that can only be used if there already are patterns. So would seem it's a different issue.
