### ISSUE TITLE
Node2D Position is doubled

### ISSUE THREAD

**Issue by hung-pt** [godotengine/godot#77437]
### Godot version

4.0.3-stable_mono_win64

### System information

Windows 10 Pro, Intel Core i5-11400H, GeForce RTX 3050 Ti Laptop GPU

### Issue description

Position of Node2D is double when rendered.
No scaling applied.
Each block is 32x32, setting a test node to {40,40} caused it to be rendered at {80,80}.
Position value is still as expected ({40,40}) when debugging.
![image](https://github.com/godotengine/godot/assets/62385412/43f03d94-bb02-404d-b57a-2801af656d19)

### Steps to reproduce

Set the position of the node in code.
See reproduction project.

### Minimal reproduction project

[New Game Project.zip](https://github.com/godotengine/godot/files/11554870/New.Game.Project.zip)

**Comment by AThousandShips** [comment]
You are drawing the circle at `(40, 40)` *from* your position, you need to draw it at `(0, 0)`

Not a bug
