### ISSUE TITLE
Inspector Pane Does Not Resize

### ISSUE THREAD

**Issue by JohnCWakley** [godotengine/godot#77434]
### Godot version

4.0.3.stable

### System information

macOS 13.3.1 (a), M2 Pro

### Issue description

I noticed today using Godot 4.0.2.stable that when an AnimatedSprite2D is selected in the Node Tree pane, and SpriteFrames is active in the bottom pane (not sure what it is called, but I am using the default layout), I could not resize  the Inspector pane. In addition, the Node Tree pane only resizes to a limit.

I upgraded Godot this morning to 4.0.3.stable and the issue still persists.

I am aware that this may be by design due to the SpriteFrames pane needing horizontal real-estate, but I am posting this bug just in case it is not.

### Steps to reproduce

Create a Scene as per the screenshot below:
<img width="1496" alt="Screenshot 2023-05-24 at 8 06 01 AM" src="https://github.com/godotengine/godot/assets/33690133/f22344d1-5da6-4f51-99a9-3dbe5f2a58c4">

With the AnimatedSprite2D selected in the Node Tree, and SpriteFrames selected in the lower pane, resizing the Inspector pane, using the vertical pane divider, does not change the width of the Inspector pane.

### Minimal reproduction project

[MinimalBugProject.zip](https://github.com/godotengine/godot/files/11554372/MinimalBugProject.zip)

**Comment by Calinou** [comment]
This is because the SpriteFrames editor imposes a minimum width which is very wide, and therefore prevents you from resizing the inspector (due to your screen resolution being low).
