### ISSUE TITLE
Font with LCD subpixel antialiasing in compatibility mode messes up color

### ISSUE THREAD

**Issue by Calamander** [godotengine/godot#77443]
### Godot version

4.0.2.stable, 4.0.3.stable

### System information

Win10, i7-10870H, Intel UHD Graphics / GeForce RTX 3060 Laptop(31.0.15.3203)

### Issue description

In Compatibility mode Control nodes (tested Label, Button, LineEdit, RichTextLabel, probably others) with imported Font with LCD subpixel antialiasing enabled messes up non-standard font-color if there is Control with default font (or non LCD subpixel antialiased) present. It also somehow depends on node hierarchy and which nodes are currently visible.

https://github.com/godotengine/godot/assets/8860283/484f6479-7866-4f14-9071-06dccd539d80

### Steps to reproduce

1. import any font and enable LCD subpixel antialiasing for it;
2. Create at least 1 control with text with this font and at least 1 for default or non-LCDspa so that LCDspa font precedes non-LCDspa one in hierarchy;
3. Change default color for LCDspa font;
4. Move around so that you see only LCDspa node or both and observe unintended color change;
5. (optional) other LCDspa node positioned after non-LCDspa in hierarchy prevents color change when visible.

### Minimal reproduction project

[LCD_Subpixel_n_ColorRect_antialiasing_bug.zip](https://github.com/godotengine/godot/files/11556585/LCD_Subpixel_n_ColorRect_antialiasing_bug.zip)

**Comment by clayjohn** [comment]
I guess the blend state is incorrectly cached in this situation.
