### ISSUE TITLE
MSAA freezes on Android

### ISSUE THREAD

**Issue by brcontainer** [godotengine/godot#77451]
### Godot version

4.0.3

### System information

- Device: Samsung M31 (SM-M315F) with Android 13
- Vulkan version: 1.0 (apiVersion 1.11.177)
- GPU: ARM Mali-G72 MP3 (850MHz)

### Issue description

I initially configured the program to use minimal settings, without MSAA and using Mobile, if I execute `get_viewport().msaa_2d = Viewport.MSAA_2X` (2D) or `get_viewport().msaa_3d = Viewport.MSAA_2X` (3D) activation dynamically the application simply freezes (the Android OS also freezes for a few moments).

Note that if we configure the project to use MSAA (regardless of whether it is 2D or 3D), the application starts frozen when it starts on Android:

![project settings msaa](https://github.com/godotengine/godot/assets/4368952/a4b751b3-12d6-4f88-a2cb-854cfc324d79)

Minimal, Reproducible code:

``` gdscript
extends Node3D

@onready var viewport: Viewport = get_viewport()


func _on_2d_button_down():
	if viewport.msaa_2d == Viewport.MSAA_2X:
		viewport.msaa_2d = Viewport.MSAA_DISABLED
	else:
		viewport.msaa_2d = Viewport.MSAA_2X


func _on_3d_button_down():
	if viewport.msaa_3d == Viewport.MSAA_2X:
		viewport.msaa_3d = Viewport.MSAA_DISABLED
	else:
		viewport.msaa_3d = Viewport.MSAA_2X
```

### Steps to reproduce

- Create a project and enable the MSAA option (2D or 3D, both fail)
- Generate the apk
- Install the apk on an Android
- Open the app on your device

### Minimal reproduction project

- Download and rename [app.apk.zip](https://github.com/godotengine/godot/files/11558689/app.apk.zip) to app.apk for tests
- Source: [MSAA-mcve.zip](https://github.com/godotengine/godot/files/11558713/MSAA-mcve.zip)

**Comment by clayjohn** [comment]
Does the same happen when using 4x MSAA? Your device doesn't support 2X MSAA. We have fallback code in place, but it could be that our fallback code is failing

More details about your device here https://vulkan.gpuinfo.org/displayreport.php?id=15084#properties it only reports support for 4X MSAA.

**Comment by brcontainer** [comment]
@clayjohn Thanks for the quick response. I don't think a fallback is necessary, I think the best way is for the game developers themselves to provide the option for the user to select the graphic quality right at the beginning (the first time the application starts) and if any configuration fails, the user will be able to switch.

👍
