### ISSUE TITLE
Cannot export in continuous integration headless Linux environment

### ISSUE THREAD

**Issue by Aodhagn** [godotengine/godot#77466]
### Godot version

Godot_v4.0.3-stable_linux.x86_64

### System information

Amazon Linux 2

### Issue description

I am trying to set up continuous integration for my project, but when exporting the command fails with the following error: 

```
ERROR: Can't load Xlib dynamically.
  at: DisplayServerX11 (platform/linuxbsd/x11/display_server_x11.cpp:5254)
ERROR: Unable to create DisplayServer, all display drivers failed.
  at: setup2 (main/main.cpp:2018)
```
It seems this error is caused by the fact that the instance I am running on does not have graphics drivers, which is expected since it is a GUI-less instance. 

However, shouldn't I be able to export (at least for a dedicated linux server) without having a GPU/graphics drivers on the instance creating the export?  Based on the [documentation for exporting via the CLI (which isn't yet updated for v4)](https://docs.godotengine.org/en/stable/tutorials/editor/command_line_tutorial.html#exporting) this seems like it should be possible using a headless version of Godot, however I don't see any headless versions for Godot 4.0.3, or any 4.x.

Is this a consequence of not having a headless version for v4.x? Or is there some configuration that I am missing that could solve this (and maybe I can help add some clarification in the CLI export documentation)?

### Steps to reproduce

- Spin up any headless server instance (in my case the latest AmazonLinux2 running on a t2.medium EC2 instance)
- Download [Godot_v4.0.3-stable_linux.x86_64.zip](https://github.com/godotengine/godot/releases/download/4.0.3-stable/Godot_v4.0.3-stable_linux.x86_64.zip) and unzip
- Download any godot project
- Attempt to export for a dedicated linux server using `godot --export-release "Linux/X11" ./build` or similar command

### Minimal reproduction project

N/A, should be reproducible with any project being exported in a similar environment

**Comment by Deozaan** [comment]
Did you try it with the `--headless` argument?

**Comment by Aodhagn** [comment]
This is exactly the configuration I was missing! This would be really helpful to add to the [CLI docs](https://docs.godotengine.org/en/stable/tutorials/editor/command_line_tutorial.html#exporting) for us who aren't working on Godot projects directly but the surrounding pieces like CI/CD, since this seems to be a different pattern than used in 3.x. I can open a PR to update the documentation to callout this parameter

**Comment by Calinou** [comment]
For the record, Godot does not fall back to a headless DisplayServer automatically as this would be confusing on desktop platforms when the DisplayServer fails to initialize for any reason (such as graphics driver issues). This is why you need to use `--headless` explicitly.

**Comment by Aodhagn** [comment]
Thanks! This reasoning makes a lot of sense. 

And thanks for the updates on the documentation, this helps make my task much clearer
