### ISSUE TITLE
VisibleOnScreenNotifier2D not working properly in Godot 4.0.3

### ISSUE THREAD

**Issue by Neatsudge** [godotengine/godot#77460]
### Godot version

4.0.3

### System information

Windows 10

### Issue description

I tried to use VisibleOnScreenNotifier2D node on my TileMap. When the screen_exited signal was emitted, the tilemap will hide but when the node is not visible, the screen_entered signal doesn't emit, thus my TileMap doesn't show. It seems to me that signals do not work when the node is not visible. Does this work as intended? I think this design defeats the purpose of VisibleOnScreenNotifier.

![image](https://github.com/godotengine/godot/assets/61649928/4a89fef1-0406-423f-a7d0-0752c3e9274a)

### Steps to reproduce

1. Create a TileMap
2. Add VisibleOnScreenNotifier2D an
3. Connect the signal and Add the above script to the node.

### Minimal reproduction project

N/A

**Comment by YuriSizov** [comment]
Please provide a minimal reproduction project so we can rule out a configuration issue.

**Comment by KoBeWi** [comment]
Yes it's intended. The notifier takes advantage of visibility culling, which also requires the node to be visible and have modulate alpha above 0. It's mentioned in the docs.
