### ISSUE TITLE
Extension .gdns

### ISSUE THREAD

**Issue by AaronIngE** [godotengine/godot#77470]
### Godot version

4.0.2

### System information

Windows 10

### Issue description

Can not open files that his extension is .gdns when I to use "preload".

An error is generated that is: unrecognized file extension.

The lines of code for this error are in "steps to reproduce".

### Steps to reproduce

const SERCOMM = preload("res://addons/GDSerCommDock/bin/GDSerComm.gdns")
@onready var PORT = SERCOMM.new()

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
Please link the addon you're trying to use so we don't have to search for it ourselves.
Seems to be https://github.com/NangiDev/GDSerCommPlugin/

It's for Godot 3, and `.gdns` is a GDNative extension. This addon hasn't been ported yet to Godot 4 so you can't use it in this version.
