### ISSUE TITLE
Fonts with [Multichannel Signed Distance Field] checked still blurry, but in-game only

### ISSUE THREAD

**Issue by justanothergamedev12** [godotengine/godot#77489]
### Godot version

4.0.3

### System information

OSX Ventura (13.2.1), Mac M1

### Issue description

As the title states, if you import a font with "Multichannel Signed Distance Field" checked, it anti-aliases the font at runtime even though it's supposed to be crisp as shown in the editor
EDITOR:
<img width="1433" alt="1" src="https://github.com/godotengine/godot/assets/134652860/fa32d0ea-8d73-4626-bac3-e4892b674d61">
RUNTIME:
<img width="1440" alt="2" src="https://github.com/godotengine/godot/assets/134652860/bf594cb7-3168-4894-9300-430af025577b">

### Steps to reproduce

1. Create a Godot Project with a 2D starting scene
2. Edit Window settings to a low res full-screen mode (e.g. in project settings -> display -> window under the "Size" list set 'Width' and 'Height' to 320x200 & set 'mode' to Fullscreen and then under the "Stretch" list, set 'mode' to viewport, and 'Aspect' to keep)
3. Import a low-res pixel font. (I used a 8x8 dos font)
4. Add a label into the scene and write some text into it
5. Set the label's font to the low-res pixel font and set its font size to something low (e.g. 8)
6. Text is obviously blurry since its anti-aliased
7. Reimport the font under the Import tab with "Multichannel Signed Distance Field" checked, and mipmaps and hinting off.
8. Text is now crisp in the editor
9. Run game
10. Text is still blurry and anti-aliased in-game

### Minimal reproduction project

Here's a fully reproduced example of the issue
[Problem.zip](https://github.com/godotengine/godot/files/11569700/Problem.zip)

**Comment by Calinou** [comment]
This is because you're using the `viewport` stretch mode, which means fonts cannot render at a higher resolution than the base viewport size.

That said, you should not use MSDF font rendering for pixel art fonts.
