### ISSUE TITLE
Particle turbulence behaves very differently in 4.1.dev3

### ISSUE THREAD

**Issue by Novark** [godotengine/godot#77491]
### Godot version

4.1.dev3.official [a67d37f]

### System information

Windows 11 [Vulkan]

### Issue description

The work performed in #77154 drastically changed the visual characteristics of particle turbulence.  I am no longer able to get the same "turbulent" behaviour that existed before these changes - no matter which turbulence settings I change.  Please let me know if there's something I'm missing about the new implementation that would give this result.

![image](https://github.com/godotengine/godot/assets/8756569/05a338a3-140b-4353-ae11-62ec9714b3d1)

### Steps to reproduce

To reproduce this is fairly simple:

1. Create a GPUParticles2D Node
2. Emit a significant number of particles (I'm emitting 50,000)
3. Set Initial Velocity [Max] to around 250, and Direction Spread to 180.  Enable turbulence
4. Set the turbulence_influence_min property to 0.1 (default) and turbulence_influence_max to 1
5. Observe how the turbulence appears in v4.1.dev3.official with the changes in #77154 versus the previous build without these changes.  The new implementation just results in some minor particle "jitter", but not the actual turbulence that it's supposed to have.

### Minimal reproduction project

No sample project provided, as the reproduction is quite simple to replicate.

**Comment by Calinou** [comment]
cc @KdotJPG @RPicster

**Comment by KdotJPG** [comment]
I was able to get the turbulent look in both, but I had to change the scale for some reason.

I don't know why this difference is showing up, though. No changes to the [scale value curve](https://github.com/RPicster/godot/blame/91bdd4073b5633e61a0e382e5e75397410c4c76f/scene/resources/particle_process_material.cpp#L1358) were merged since 4.0, and the same is the case for [how it's effectively used](https://github.com/RPicster/godot/blame/91bdd4073b5633e61a0e382e5e75397410c4c76f/scene/resources/particle_process_material.cpp#L386).

![turbulence40](https://github.com/godotengine/godot/assets/8829856/d3e7c2ea-dd75-47b0-a27b-01dc25077f17)
![turbulence41](https://github.com/godotengine/godot/assets/8829856/9a05f6c6-8812-4d8f-aca0-27bc813ae2ae)

**Comment by Novark** [comment]
> I was able to get the turbulent look in both, but I had to change the scale for some reason.
> 
> I don't know why this difference is showing up. No changes to the [scale value curve](https://github.com/RPicster/godot/blame/91bdd4073b5633e61a0e382e5e75397410c4c76f/scene/resources/particle_process_material.cpp#L1358) were merged since 4.0, and the same is the case for [how it's effectively used](https://github.com/RPicster/godot/blame/91bdd4073b5633e61a0e382e5e75397410c4c76f/scene/resources/particle_process_material.cpp#L386).
> 
> ![turbulence40](https://user-images.githubusercontent.com/8829856/241410836-d3e7c2ea-dd75-47b0-a27b-01dc25077f17.png) ![turbulence41](https://user-images.githubusercontent.com/8829856/241410837-9a05f6c6-8812-4d8f-aca0-27bc813ae2ae.png)

That's very strange...I just tested it again with your exact settings and see the same result that I got before - no turbulence.  One thing I did notice, however, is that your default value for "Noise Speed Random" seems to be 0 (as you don't have the little "revert" button while the value is zero), whereas my default is 0.2, and if I change it to zero I get the little revert button.  Maybe a silly question, but are you sure your local build is the 4.1.dev3.official release?

![image](https://github.com/godotengine/godot/assets/8756569/c70a543c-b44d-4104-b73d-07f8858bb9c3)

**Comment by KdotJPG** [comment]
^ found the problem!

**Comment by Novark** [comment]
> ^ found the solution!

Glad to hear it!  Do you know if this change would also affect #74541?  It may be worth taking a look at while you're in the same headspace having just solved this.
