### ISSUE TITLE
HTML5 export - Uncaught TypeError: Engine.getMissingFeatures is not a function

### ISSUE THREAD

**Issue by JapanYoshi** [godotengine/godot#77516]
### Godot version

4.0.3.stable.official [5222a99f5]

### System information

Windows 10, Forward+ renderer, NVIDIA GeForce GTX 1060 with Max-Q Design

### Issue description

When I test the game on HTML5, the game gets stuck on a black screen with the following error in the console.

    Uncaught TypeError: Engine.getMissingFeatures is not a function
        <anonymous> http://localhost:8060/tmp_js_export.html:219
        <anonymous> http://localhost:8060/tmp_js_export.html:245
    tmp_js_export.html:219:25
        <匿名> http://localhost:8060/tmp_js_export.html:219
        <匿名> http://localhost:8060/tmp_js_export.html:245

I suspect that it's this line that's causing the issue:

https://github.com/godotengine/godot/blob/d984ad64d440320e40e85dbcb79b8e9240f75493/misc/dist/html/full-size.html#LL216C1-L216C46

### Steps to reproduce

1. create new game
2. test on HTML

Issue occurred whether "Progressive web app" was on or off.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Should probably be `engine.getMissingFeatures()` instead of `Engine` yes

**Comment by akien-mga** [comment]
That file was last changed 7 months ago, I'm surprised it would only be reprinted as having an error now.

**Comment by NewDefectus** [comment]
I think you need to empty your cache. The same thing happened to me, it turned out the index.js file wasn't updated in the browser so I had to empty the cache (Ctrl+Shift+I, then right click on the refresh button) to get it to work

**Comment by JapanYoshi** [comment]
I guess that explains it.
