### ISSUE TITLE
GDscript Editor wrong

### ISSUE THREAD

**Issue by waza921** [godotengine/godot#77510]
### Godot version

v4.0.3 stable

### System information

window 11,i7-11800H,RTX3060 Laptop

### Issue description

When I was writing a script using the editor in Godot4, sometimes the related words it suggested were all in double quotes, and then restored when I closed the program and opened it again.

I use the Chinese version of godot4 and often switch between Chinese and English keyboards.

I don't know if this is a bug. Please forgive me if I've wasted your time.

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Related? #75774 

Hard to tell as you give no information to where this happens

**Comment by KoBeWi** [comment]
This is a bug, and the same one as #75774
So far the exact reproduction steps are unclear.
I'll close this as duplicate.
