### ISSUE TITLE
Cannot rename items in the FileSystem dock

### ISSUE THREAD

**Issue by kuroodo** [godotengine/godot#77527]
### Godot version

v4.1.dev3.official [a67d37f7c]

### System information

Windows 10 64-bit

### Issue description

When trying to rename anything (a scene, script, folder, etc) instead of selecting the item itself, it highlights the current folder in the FileSystem tab instead.

Upon pressing enter or confirm the name change a Warning dialogue appears with the following text:

> This file extension is not recognized by the editor.
If you want to rename it anyway, use your operating system's file manager.
After renaming to an unknown extension, the file won't be shown in the editor anymore.

If no new text is entered, the warning box instead states

> Name contains invalid characters.

Upon pressing Ok, the folder name in the FileSystem tab is visually changed to match the name of the item you attempted to rename (regardless of the entered text) including the extension if any. The folder name remains the same in the file system, but visually in the editor it is the name of the item.
In the output log, there is a message
> scene/main/viewport.cpp:3005 - Condition "!is_inside_tree()" is true.

![sample](https://github.com/godotengine/godot/assets/9257713/35ee2446-507b-4cfb-a9ab-6d46ae484feb)

### Steps to reproduce

1. Create or open a project
2. Rename any item (scene, script, folder, etc) by right clicking or pressing F2 (or corresponding shortcut for rename)

### Minimal reproduction project

N/A

**Comment by kuroodo** [comment]
It didn't occur to me to test this on other things instead of just scenes when I created the issue. The original issue was specifically about being unable to rename scenes. I have edited the issue and title accordingly since the bug appears to affect everything else in the file system.

**Comment by KoBeWi** [comment]
You CAN rename scenes. The warning appears, because it tries to use the name you provided for the wrongly selected folder. Once you accept, it will rename the file you wanted to rename, not the edited folder.

The bug here is that the wrong file is being edited when renaming.

**Comment by kuroodo** [comment]
> You CAN rename scenes.
> Once you accept, it will rename the file you wanted to rename, not the edited folder.

Can you elaborate? I am unable to rename scenes at all. When I go to windows file explorer, the file has the same name. When I restart the editor, the file still has the same name.

I can only rename things if I disable split mode (which I had forgotten to mention in the issue but is mentioned in the pull request)
