### ISSUE TITLE
Adding a GPUParticles3D programmatically does not work as expected

### ISSUE THREAD

**Issue by MyStarrySpace** [godotengine/godot#77525]
### Godot version

4.1 dev 3

### System information

Windows 11 Pro, Processor	Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz   2.59 GHz Installed RAM	16.0 GB (15.8 GB usable) Device ID	B0DAAC34-BB15-4A0C-9366-F05D4280FC30 Product ID	00330-53817-11120-AAOEM System type	64-bit operating system, x64-based processor Pen and touch	Pen support

### Issue description

I have a project that involves adding a GPUParticles3D at runtime. For some reason, when I create the mesh, attach the script, and set the parameters via code, but create the GPUParticles3D node manually beforehand (no parameters were adjusted), the particle system performs as expected and spawns a mesh at each position; however, when I spawn the GPUParticles3D via code as the child of another Node3D, it doesn't do what I want (spawn a mesh at each input position). I have also tried adding an editor-generated GPUParticles3D with the code as the child of a blank Node3D and that works. I tried replacing parts of the code, such as where the material/shader/textures/mesh are set, with saved resources, and it still performs like this. 

### Steps to reproduce

1. Create a GPUParticles3D
2. Create a node3D and write code to generate a GPUParticles3D as a child of that node
3. Write code to generate meshes/shaders/textures/materials for both
4. Write a process material shader like the one in the example

The minimum reproduction project should have this done.

### Minimal reproduction project

[proj_copy.zip](https://github.com/godotengine/godot/files/11578594/proj_copy.zip)

**Comment by AThousandShips** [comment]
In your main script you are creating the particles, but never adding them to the scene, actually adding the particles to the scene makes it appear as it should

Please consult the other [community channels](https://godotengine.org/community) if you are unsure if something is a bug or you have an error in your code (like this case)

**Comment by MyStarrySpace** [comment]
Hi there! I did post on the Godot Discord and a few other places but received no response, so thank you for your reply! I did indeed forget to write "add_child(particles)" in Test2.gd; however, it seems that even with this addition, it is only rendering one of the particles. Attached is a screenshot of what I am getting after adding add_child(particles) vs. what I expect:

Result after adding add_child:
![image](https://github.com/godotengine/godot/assets/25332257/b40dce92-6457-4335-9fea-549d297dde98)

Result I want, which I am getting from the GPUParticles3D:
![image](https://github.com/godotengine/godot/assets/25332257/3ec69c2e-6845-4563-aeeb-ac37e5d2534b)

Thank you so much for your help! It is very much appreciated

**Comment by AThousandShips** [comment]
Worked for me so not sure what's wrong

**Comment by MyStarrySpace** [comment]
> Worked for me so not sure what's wrong

Odd, must be something weird on my end. I'm not sure why none of the other PlaneMeshes are displaying as they should

**Comment by clayjohn** [comment]
This is not a platform to come to for project support. This space is reserved for bug reports only. 

As AThousandShips has already pointed out the error in your code and directed you to the [community channels](https://godotengine.org/community), I will be closing this issue. 

In the future, please only create a bug report for reporting a bug in the engine, do not open a bug report to receive help with your project.
