### ISSUE TITLE
Generate POT from GDScript does not include tr("...").format({...})

### ISSUE THREAD

**Issue by stevecotton** [godotengine/godot#77529]
### Godot version

v4.1.dev.custom_build.2210111eb

### System information

Linux 6.1.0-9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08) x86_64 GNU/Linux

### Issue description

Using the editor's feature to generate a .pot from a .gd script captures only 3 of these 5 `tr` strings. It misses the ones that call `format`:
```
func something():
	print(tr("A simple string"))
	print(tr("Found target: {name}, and test it").format({name="test"}))
	print(tr("A string with {placeholder}, but without the format call"))
	var test1 = tr("An unused string, {name}")
	var test2 = tr("A formatted string, {name}").format({name="test"})
```

Using `format` in this way is expected to work, because it's documented in https://docs.godotengine.org/en/latest/tutorials/i18n/internationalizing_games.html#placeholders .

The resulting .pot contains only the strings that were not formatted:
```
# LANGUAGE translation for Temp for the following files:
# res://test_script.gd
#
# FIRST AUTHOR < EMAIL @ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: Temp\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8-bit\n"

#: test_script.gd
msgid "A simple string"
msgstr ""

#: test_script.gd
msgid "A string with {placeholder}, but without the format call"
msgstr ""

#: test_script.gd
msgid "An unused string, {name}"
msgstr ""
```

### Steps to reproduce

This can be reproduced by pasting the 5 `tr` lines into an existing .gd file, so I've not attached a .zip with the minimal project.

Detailed reproduction steps:
1. Create a new project
1. Create a new .gd file containing just that `something` function
1. Open "Project settings", "Localization", sub-tab "POT Generation"
    1. Click "Add" and add that .gd file
    1. Click "Generate POT", choose a filename and save
1. Check which strings were included in .pot file

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
cc @ZangEldor @timothyqiu @YeldhamDev
