### ISSUE TITLE
Mutex not locking

### ISSUE THREAD

**Issue by jacopofar** [godotengine/godot#77547]
### Godot version

4.0.2.stable

### System information

Linux 6.2 (Fedora, x86_64), Vulkan API 1.3.238 - Forward+ - Using Vulkan Device: AMD - AMD Radeon Graphics (RADV RENOIR)

### Issue description

I'm trying to load a JSON configuration via HTTP, and cache it since the same URL is going to be called many times.

I created an helper in the form of an Autoload node to perform the HTTP call and cache, using a `Mutex` to ensure a single call is done at a time.

However, both the Godot console and the HTTP calls on the server show that the calls are being done for the same URL again and again, and the Mutex is being locked before being unlocked. As a result the same HTTP request is done many times in parallel, before the result is cached and reaching the limit of open connections.

I attached a minimal project reproducing the issue, the logic is this:

1. The `Game` scene instantiates many identical `Event` scenes setting the same URL to each, and adds them as childs
2. The `_ready` function in the `Event` uses the `HTTPLoader` helper to fetch its own JSON
3. The `HttpLoader` node uses a mutex to ensure a single request is done at the time, logging the `lock` and `unlock` calls

The log shows many repeated "mutex locked for..." lines at the start, while I expect to see only one followed by an unlocking event.

This behavior appears both in the native Linux app and in the WASM export.

### Steps to reproduce

Run the included Godot project, the included URL points to an existing small JSON but any address will do.

This is the code for the HTTP caching (included in the project):

```gdscript
extends Node

var json_cache: Dictionary = {}

var load_mutex = Mutex.new()


func load_json(url: String):

	load_mutex.lock()
	print("mutex locked for ", url)
	
	if json_cache.has(url):
		print("unlocking mutex (cache hit)")
		load_mutex.unlock()
		return [null, json_cache[url]]
	print("cache miss, will load ", url)

	var http_request = HTTPRequest.new()
	add_child(http_request)
	var error = http_request.request(url)
	if error != OK:
		print("unlocking mutex (request error)")
		load_mutex.unlock()
		push_error("An error occurred in the HTTP request: ", error)
	# will yield _result, _response_code, _headers, body
	var http_result = (await http_request.request_completed)
	remove_child(http_request)
	if int(http_result[1] / 100) != 2:
		print("NON 200 HTTP: ", http_result[1], " ", url)
		
		print("unlocking mutex (HTTP response errror)")
		load_mutex.unlock()
		return [str("Non-200 HTTP code ", http_result[1]), null]
	var body = http_result[3]
	var json = JSON.new()
	json.parse(body.get_string_from_utf8())

	json_cache[url] = json.get_data()
	print("unlocking mutex (success)")
	load_mutex.unlock()
	return [null, json.get_data()]
```

### Minimal reproduction project

[HttpTest.zip](https://github.com/godotengine/godot/files/11581833/HttpTest.zip)

**Comment by bitsawer** [comment]
I don't think this is a bug. GDScript Mutex is recursive / re-entrant, which means the same thread can lock it multiple times without blocking. In this case as all calls to `load_json()` come from the same thread so locking the mutex does not actually block execution.

https://docs.godotengine.org/en/latest/classes/class_mutex.html

>It's of the recursive kind, so it can be locked multiple times by one thread, provided it also unlocks it as many times.

**Comment by jacopofar** [comment]
I see, but then how can there be multiple calls to `load_json` from the same thread? Is `_ready()` called asynchronously? In that case how can one implement this kind of pattern?

**Comment by bitsawer** [comment]
No, `_ready()` is not called asynchronously, but `load_json()` does not actually block in this case. This is because as mentioned mutex can be locked multiple times by the same thread. Also, this line

`var http_result = (await http_request.request_completed)`

does not really block the main thread either as `await` is used to wait on a signal. Reading some documentation about how `await` works might also help to clear some confusion about this.

**Comment by jacopofar** [comment]
I did read it (I refer to the [awaiting for signals or coroutines](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_basics.html#awaiting-for-signals-or-coroutines)) but still could not understand what's happening here.

For what I see `await` waits for a signal to arrive or a coroutine to finish and resumes the execution from that point, the caller of the function using it will also need to use `await`, because the function becomes a coroutine (that is, it is "awaitable" and in fact must be invoked with await or it gives an error), implicitly, without needing to mark it with "`async`" or similar.

So, the way it works in my head is:

1. Godot sees the new nodes in the scene and iterates over them one by one (same thread) to call `_ready()` on them. Since this `_ready` uses an await internally it is a coroutine and is awaited
2. the function `_ready` of  `Event` calls and `awaits` on `load_json`, which also is a coroutine because it uses await internally, so it will be suspended until that function returns and must be invoked with `await` (if I don't I get an error)
3. `load_json` does the same with the `http_request.request_completed` signal, it awaits for it
4. when the HTTP request is done `load_json` is resumed and processes the result of it and returns (and by returning it lets whoever was awaiting on this coroutine go on)
5. the return of `load_json` causes the `await` in `_ready` to continue from that point
6. the `_ready` function also is a coroutine now and was awaited by Godot so it goes on and awaits for the next `_ready`

this is what I assume is happening, but it's not, I am assuming at point 1 and 6 that the engine awaits for `_ready()` because it's using `await` so `_ready` becomes a coroutine and is awaited before other `_ready` functions are called, but it's just a guess.

If these calls to `_ready` are concurrent and not awaited, then I think I get what's happening but don't know how to ensure HTTP calls are not done concurrently.

**Comment by bitsawer** [comment]
>I am assuming at point 1 and 6 that the engine awaits for _ready() because it's using await so _ready becomes a coroutine and is awaited before other _ready functions are called, but it's just a guess.

That's not quite right, `_ready()` does not really "wait" for any `await` called inside it. It simple defers the execution of affected code to a later time once the signal is emitted, but the function itself returns normally as it is not awaited. Basically the project starts all HTTP requests almost immediately, then waits for them to complete. Adding a few more `print()` statements might clarify how the functions are called and finished, it can be sometimes tricky to figure out how asynchronous code works.

I don't think there are any Godot engine bugs here. After some testing the demo project behaves as I expect it to considering the code.

**Comment by jacopofar** [comment]
Yes, makes sense.
I solved simply moving this logic from `_ready()` into a `load()` function, that I call after creating the nodes.

Now the code that creates is:

```
func _ready():
	for i in range(400):
		var new_event = Event.instantiate()
		new_event.event_url = event_url
		# [...]
		add_child(new_event)
		await new_event.load()
```
and it works as intended, removing the locks.

I agree that there's no bug here, if `_ready` is a coroutine it will not be awaited and can run concurrently with other ready functions, so the logic should not rely on it being the only one running
