### ISSUE TITLE
SurfaceTool add_triangle_fan function parameters mismatched

### ISSUE THREAD

**Issue by blooblahguy** [godotengine/godot#77542]
### Godot version

4.1 RC3

### System information

Windows 11 AMD Ryzen 5950x

### Issue description

Actually should be pretty simple, as of commit: https://github.com/godotengine/godot/commit/1c93606e470f0cad5f14af104ccb89a95a89931c

SurfaceTool's add_triangle_fan() maps its parameters like so:
`add_triangle_fan(p_vertices, p_uv2s, p_colors, p_uv2s, p_normals, Variant(p_tangents));`

As you can see its using **p_uv2s** as the 2nd _and_ 4th parameters, and isn't using **p_uvs** at all which ought to be the 2nd parameter. The 2nd parameter at the moment does nothing at all.

As a result I had to change my code from:
`surface_tool.add_triangle_fan(vertices, [uvs[0], uvs[1], uvs[2], uvs[1], uvs[3], uvs[2]])`
To:
`surface_tool.add_triangle_fan(vertices, [], [], [uvs[0], uvs[1], uvs[2], uvs[1], uvs[3], uvs[2]])`

### Steps to reproduce

Use add_triangle_fan and place your UVs as the 2nd parameter, your mesh will be black. When you change your uvs to the 4th parameter, it correctly maps.

### Minimal reproduction project

Should be trivial to reproduce (and to see why it's broken in this commit)

**Comment by akien-mga** [comment]
> 4.1 RC3

Just to be clear, I expect you meant 4.1 dev 3? We haven't reached release candidate state yet.

**Comment by blooblahguy** [comment]
Sorry yes I meant dev 3

**Comment by kdiduk** [comment]
Looks like there was a typo made [here](https://github.com/godotengine/godot/commit/1c93606e470f0cad5f14af104ccb89a95a89931c#diff-79845deb532a5552c3efbe2ea6a421bc68dd2a34ac3cac691c2892c74480a1d2R378). I've made a tiny pull-request with a fix. Please, review.
