### ISSUE TITLE
AnimationPlayer: TimeSeek node value bigger than 0 is reset after first run

### ISSUE THREAD

**Issue by rndevfx** [godotengine/godot#77557]
### Godot version

4.0.3

### System information

- OS: Mac OSX M2 Pro
- Godot Version: 4.0.3

### Issue description

When adding a TimeSeek node within a blend tree in the animation player and the value is >= 0, the value is set back to -1 after the first run

### Steps to reproduce

- Create an animation player with a AnimationNodeStateMachine
- Add a new blend tree with an animation + time seek node
- Set the time seek node to value >= 0
- Set the animation player to active and run the blend tree once
- The value is set back to -1

When the blend tree is active, it's not possible to set the value to >= 0, it goes back to -1 immediately.

### Minimal reproduction project

[TimeSeekIssue.zip](https://github.com/godotengine/godot/files/11582892/TimeSeekIssue.zip)

Option 1: Open the project and run it. The box starts from the center in the first run after a small delay (rotating box) (TimeSeek 1) - then TimeSeek is reset, and the box starts from 0.

Option 2: You can open the AnimationPlayer, jump into the "Movement" blend tree, activate the AnimationPlayer and get the same result after the first run. Setting a value >= 0 is impossible.

**Comment by TokageItLab** [comment]
It is intended behavior. In 4.0, the parameter is renamed as seek_request to make it clearer that it is a request valid for only one frame, as explained in the class reference.
