### ISSUE TITLE
CharacterBody3D with capsule stucks so often in StaticBody-Trimesh that it actually unusable.

### ISSUE THREAD

**Issue by idchlife** [godotengine/godot#77555]
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

- OS: macOS Ventura 13.0
- Rendering method: Forward+

### Issue description

I beg to read this issue fully before closing it as duplicate of issues that has obvious problems within their repro projects, that this issue hasn't.

This issue is somewhat duplicate of https://github.com/godotengine/godot/issues/77485 but this time with a really simple working Trimesh, created from mesh with NOT FLIPPED normals. Mentioned issue was closed with recommendation to flip normals - and it did not help. So for this issue I recreated mesh for collisions in Blender from scratch, without flipped normals. Simple usual mesh. To demonstrate the magnitude of the problem.

Here is video of the problem (repro is also available): https://imgur.com/ED8eKjf

I'm sorry for possible duplication in advance. I suspect that there is still no opened issue with clean project that should just work (without scale problems, without flipped normals, just simple proper done repro project)

I just can't understand what to do in my situation - I had a lot of hopes for CharacterBody3D, but it actually is just unusable for level exploration.

If it's possible I would like to know about some official/semi-official workaround.

### Steps to reproduce

1. Create Trimesh from average mesh.
2. Try to walk on it with CharacterBody3D
3. Notice that it stucks so often it becomes unusable.

### Minimal reproduction project

[character-body-3d-stuck-repro.zip](https://github.com/godotengine/godot/files/11582800/character-body-3d-stuck-repro.zip)

**Comment by rburing** [comment]
Could you please compare 4.0.1 to check if this is a recent regression? (There was a regression in this area in 4.0.2, but that particular regression is supposed to be fixed in 4.0.3.)

**Comment by idchlife** [comment]
@rburing will check right away!

**Comment by idchlife** [comment]
@rburing 

here is video from 4.0.1: https://imgur.com/4zNVYou

Unfortunately same behaviour.

Just in case here is screenshot of Blender project mesh: https://imgur.com/gDMRFbP

It was solidified (some recommendations in several issues suggested this) and it has proper facing normals. Not flipped. Exported into .glb format.

**Comment by Calinou** [comment]
> closing it as duplicate of issues that has obvious problems within their repro projects, that this issue hasn't.

Can you point out these issues in particular? I haven't seen any in the MRPs.

**Comment by idchlife** [comment]
@Calinou I apologise if this issue is indeed a duplicate with the same problem.

Is there currently available workaround of some sorts? Maybe nightly build or build with some pull request or something?

**Comment by Calinou** [comment]
> Is there currently available workaround of some sorts? Maybe nightly build or build with some pull request or something?

Try some of the workarounds outlined in [Troubleshooting physics issues](https://docs.godotengine.org/en/latest/tutorials/physics/troubleshooting_physics_issues.html);

**Comment by mgiraud** [comment]
@idchlife while waiting for godot physics engine to be corrected, i suggest you give a try to godot-jolt https://github.com/godot-jolt/godot-jolt

**Comment by idchlife** [comment]
> @idchlife while waiting for godot physics engine to be corrected, i suggest you give a try to godot-jolt https://github.com/godot-jolt/godot-jolt

unfortunately it does not have softbody physics which I rely on right now. I doubt it will work with all the softbodies I have in the scene as a drop-in-replacement.

**Comment by idchlife** [comment]
Well, it turns out the problem was me all along!

Precisely this line:

```gdscript
  _velocity.y -= gravity * delta
```

Should've been like this:

```gdscript
  if !player.is_on_floor():
    _velocity.y -= gravity * delta
```

Sorry for the inconvenience guys.

P.S. Thanks to the @mihe telling me about this in his addon repository issues, I figured out about the problem originator, me :D
