### ISSUE TITLE
Strange crash ERROR: FATAL: Index p_index = 3 is out of bounds (size() = 3).    at: get (./core/templates/cowdata.h:155)

### ISSUE THREAD

**Issue by fian46** [godotengine/godot#77565]
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

- OS win 10
- OS Android 12
- Renderer Mobile

### Issue description

Game stop running and not show any error in debugger. but if running godot editor in console mode, the error shown as in this video and screenshoot

![image](https://github.com/godotengine/godot/assets/13792627/b4e6767a-effb-4552-94e5-8171a69e39c3)
![image](https://github.com/godotengine/godot/assets/13792627/ecab2596-ff98-4ac1-b6e4-ba823ad5af38)

https://github.com/godotengine/godot/assets/13792627/a51d7302-d9e7-4e38-bd71-d5eb26a4e39c

### Steps to reproduce

not sure how it's not happen in consistent

### Minimal reproduction project

N/A

**Comment by fian46** [comment]
![image](https://github.com/godotengine/godot/assets/13792627/dd94da8e-288d-4f45-ae65-e6c0bd2be16a)
maybe this is related too, sometimes this error shows in debugger like the screenshot above. i don't know when and how it happen. maybe it related to ./core/templates/* ?

**Comment by fian46** [comment]
hi guys i think we can close this. i found the culprit. the project was previously created with godot 4.0.1 stable. i use external animation to save with version 4.0.1. after i move global animation to build-in 4.0.3 through manage animation menu, the problem goes away.

**Comment by akien-mga** [comment]
We should still aim to fix this as a crash is an engine bug.

**Comment by fian46** [comment]
No i don't have the files anymore

**Comment by akien-mga** [comment]
Closing then as this would be difficult to debug. If someone else is experiencing this bug in latest Godot releases, please open a new issue with a reproduction project.

**Comment by fian46** [comment]
@akien-mga is it possible for me to have godot in debug mode so i can where get the error exactly or at least can get the stacktrace ? I can't make small reproduce project for this issue and it only happens in this project .it is still crash btw. I don't think the animation files is the issue. After deploy it to android it's crash after 1 minutes.

**Comment by fian46** [comment]
i have seen the same issue with the cowdata at line 155 that produce the same crash with different index. this possibly related issue.

**Comment by akien-mga** [comment]
You could compile Godot from source with debug symbols (`scons debug_symbols=yes`), and run that binary through a debugger, with a breakpoint in the error print function, so you can get a stacktrace for what triggered the error.

See https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_for_windows.html

**Comment by fian46** [comment]
i am not familiar with building the engine or familiar with C++. is there any debug build for the engine ?

**Comment by fian46** [comment]
ERROR: Condition "p_elem->_root" is true.
   at: SelfList<class GodotBody2D>::List::add (C:\Users\Hugo\AppData\Local\Temp\godot-debug-build-editor\core/templates)1 2147483648
ERROR: Condition "p_elem->_root" is true.
   at: SelfList<class GodotBody2D>::List::add (C:\Users\Hugo\AppData\Local\Temp\godot-debug-build-editor\core/templates)ERROR: FATAL: Index p_index = 3 is out of bounds (size() = 3).
   at: CowData<float>::get (C:\Users\Hugo\AppData\Local\Temp\godot-debug-build-editor\core/templates/cowdata.h:155)

================================================================
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.0.3.stable.custom_build (5222a99f5d38cd5346254cefed8f65315bca4fcb)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[0] <couldn't map PC to fn name>
[1] <couldn't map PC to fn name>
[2] <couldn't map PC to fn name>
[3] <couldn't map PC to fn name>
[4] <couldn't map PC to fn name>
[5] <couldn't map PC to fn name>
[6] <couldn't map PC to fn name>
[7] <couldn't map PC to fn name>
[8] <couldn't map PC to fn name>
[9] <couldn't map PC to fn name>
[10] <couldn't map PC to fn name>
[11] <couldn't map PC to fn name>
[12] <couldn't map PC to fn name>
[13] <couldn't map PC to fn name>
[14] <couldn't map PC to fn name>
[15] <couldn't map PC to fn name>
[16] <couldn't map PC to fn name>
[17] <couldn't map PC to fn name>
[18] <couldn't map PC to fn name>
[19] <couldn't map PC to fn name>
-- END OF BACKTRACE --
================================================================

**Comment by fian46** [comment]
![image](https://github.com/godotengine/godot/assets/13792627/ba89fafe-9c4a-4e0c-9e1c-9855d060aff6)
this is the result after crash with debug build in windows.
pointing at SelfList of GodotBody2D probably related to Godot 2D Physics maybe ? 
probably not animation problem as i reported before

**Comment by fian46** [comment]
I have been checking the related issue with SelfList in Godot 2D Physics #50470 but this happening is Area2D too. Yes i am using Area2D but not using any multi thread operation. Maybe this is related ? since output of crash is the same  "p_elem->_root is true" happend couple time before the game is crashing.

**Comment by fian46** [comment]
> @Calinou has debug builds of Godot 4.0.3 available here: https://github.com/Calinou/godot-debug-builds/releases/tag/v4.0.3

Disappear in 4.2 rc 1
