### ISSUE TITLE
Center View button in TileMap editor is in awkward spot

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#77562]
### Godot version

4.1 dev3

### System information

W10

### Issue description

The button is pushed to the far right. Maybe it tries to escape, idk.

![image](https://github.com/godotengine/godot/assets/2223172/becb32f6-f725-4564-952e-946ec544c376)

It used to be more to the left. Not sure when it changed.

Seems correct in 4.0.3

![image](https://github.com/godotengine/godot/assets/2223172/3e3d206a-481d-415a-acb4-40cbf4a60fc0)

### Steps to reproduce

1. Add TileMap
2. Look to the right

### Minimal reproduction project

N/A

**Comment by ProbablyWorks** [comment]
I'd like to take a look at it as my first issue if no one else is on it :)

Notes:
This line was moved from `TileAtlasView::TileAtlasView()` in #73475 :
`button_center_view->set_icon(get_theme_icon(SNAME("CenterView"), SNAME("EditorIcons")));`

It is now found in `TileAtlasView::_notification(int p_what)` in the `NOTIFICATION_THEME_CHANGED` case:
`button_center_view->set_icon(theme_cache.center_view_icon);`

For testing, I added it back where it was and it fixed the offset:
![image](https://github.com/godotengine/godot/assets/134785754/d61ded42-a136-4a59-b0f3-afec02e5a9e0)

Though the warnings added in the aforementionned issue popped up:
![image](https://github.com/godotengine/godot/assets/134785754/f0dab4b0-8d6b-436c-a49b-11c919fa5d8a)

Still figuring out why calling it specifically in its old place fixes the issue but the not the way it is called now (I can indeed see it be called multiple times when opening a project and when changing my theme) 😕 

@YuriSizov Any ideas/thoughts?

**Comment by rburing** [comment]
Probably the size should be known before setting the anchors to top right, so maybe set a custom minimum size beforehand.

**Comment by ProbablyWorks** [comment]
@rburing Thanks a bunch! 🥳 You were definitely right for the anchors setting! If I manually set the anchors after the icon is set, the button is back where it should be! For the actual fix later today, I'll look into what you said about setting a custom minimum size before setting the anchors! I think ideally I would try to get that size from the icon itself instead of eye balling it (though without triggering the warnings about accessing theme items too early).

**Comment by YuriSizov** [comment]
Resetting the anchors after the icon is set would be sufficient. You can't really give it a minsize without having an icon, so that won't be a proper solution anyway.

**Comment by ProbablyWorks** [comment]
Right! I tried to set a minimum size with what I could find but that didn't pan out😓I'll keep that in mind!
