### ISSUE TITLE
PackedScene inconsistency

### ISSUE THREAD

**Issue by albinaask** [godotengine/godot#77576]
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

- OS: Windows 10
- AMD x86_64 cpu
- Nvidia 1070ti

### Issue description

This issue is not one of my areas of expertise, so this may just be the case of me not understanding Godot good enough, and just pointing out correct behaviour. But to me this looks really weird after studying the behaviour for a few hours.

The issue is that packing scenes from GDScript using ResourceSaver and PackedScene produces results that differ from what the editor seem to produce despite passing the same flags to ResourceSaver. Running the test case 1, things work as expected even though we end up with an extra bit of data in the "res://test case 1/copy.tscn" on line 7 where 'type="Node2D"' is inserted. However when we enable editable children for the subscene (which is done in test case 2) weird stuff starts to happen.

Running the "res://test case 2/case_2_duplicator.gd"Editor script and looking at the console output, it reveals that the repacked scene does not even contain the same amount of nodes as the original, even though it should just be a copy. If we then take a look at the result file, we see that it for one has added another external resource that was not in the original and on top of that line 13 and 14 that have also appeared from nowhere. Line 13 includes a reference to the position of the sprite in the subscene. This means that even though we haven't changed the position of the sprite in the main scene, it is updated to the same value, as if we would have. This also extends to any property it seems like (though I have only checked it for "visible"). This means that if we change the position of the sprite in the subscene.tscn, the one saved by the editor will reflect those changes, where as the copied scene will override the position with the old value. 

If I recall correctly, the editor way seem to correspond with my memory of how it should work. The issue being that this is not replicatable from within GDScript, which is weird since they should be running the same code. Looking at the source code at "editor_node.cpp":1769-1775 I seem to pass the same flags into the save function (in the off chance the error would be there after all).

Test case 3 shows the odd behaviour is present in the binary format as well since the mainscene.scn and copy.scn is of different sizes file sizes, and must therefore be presumed to contain different information. In test case 4, we see that even a script becomes replicated into the copy, even though the flag for bundling resources is not set. Maybe it is somehow told to bundle resources by default even though I'm clearly not passing that flag?

Next weirdness is outlined in test case 5 and 6:

In test case 5 we make changes to the two subscene sprites from the code upon we can observe in the 'res://test case 5/copy.tres' that only the instance marked with "editable children" that is persisting after the save. This may be according to what is expected. However then it is very weird that it says "editable children" since you can edit the children of both nodes, and not "persistent children overrides" or something like that. I can't really find any reasonable documentation of what this button is supposed to do, so I can't say whether it is right or wrong.

In test case 6 the editable children is set from the script and it alters the function of the packing of the node into the PackedScene, which is not at all what the documentation says about that method. The documentation states that "Sets the editable children state of node relative to this node. This method is only intended for use with editor tooling." Which is clearly inaccurate since this is not just a visual feature of the editor, but instead changes the entire replication process. This means that you have call this method on each node that you conceivably want to change any property of if you use the scene replication system in any other way than from within the editor, which isn't at all very handy. Together with the last issue, this means that you either have no ability to change properties of subscenes or you have a metric crap ton of replicated data in your saved scene.

Imagine you have a scene with 100 instances of a subscene in it. You have set 10 different properties to a default value in you subscene. Then you edit an additional property for each instance. Saving that scene you would have 1000 data points that are exact replicas of the subscene data that you have to carry around, basically making the file 6 times bigger than it needs to be. ( 1 node index and 11 properties instead of 1 node index + 1 property per node).

### Steps to reproduce

Look at the files in the supplied project, or rerun the scripts as need be

### Minimal reproduction project

[prj.zip](https://github.com/godotengine/godot/files/11584718/prj.zip)

**Comment by AThousandShips** [comment]
> The documentation states that "Sets the editable children state of node relative to this node. This method is only intended for use with editor tooling." Which is clearly inaccurate since this is not just a visual feature of the editor, but instead changes the entire replication process.

This points in the direction that yes, this isn't supposed to be used from outside the editor, and will probably cause problems if you do

**Comment by AThousandShips** [comment]
This doesn't really read like a bug report, but more some observations on the engine, this is best served in [some other community channel](https://godotengine.org/community) I believe, at least to discuss this and see where if at all any errors are, and then make a more clear, and less rambling, bug report which points to identified bugs

**Comment by albinaask** [comment]
I see your points regarding a long and somewhat vague bug report, the reason why I wrote it this way is that I am not 100% sure of what is intended behavior and what is not. Since I've not written the systems in question I of course cannot judge exactly what is and isn't supported. However, when I read the [class documentation for PackedScene](https://docs.godotengine.org/en/stable/classes/class_packedscene.html) it states the following "Can be used to save a node to a file". It does not say anything about limitations to the editor or anything like that. And since scene saving implementation that the editor is using, is written using the very same "pack" method. That these two methods do not produce identical output files feels to me like there is a bug somewhere. But again, I may very well be wrong.

**Comment by AThousandShips** [comment]
> that I am not 100% sure of what is intended behavior and what is not

This is when you take it to the community channels

**Comment by albinaask** [comment]
You have a clear point. I'll ask around and dig into this matter a little more. I'll update this bug report according to what I find. Thank you for your input.

**Comment by fire** [comment]
What is the expected result?

**Comment by albinaask** [comment]
The expected result of the test cases would be copies containing the same information as the source file if godot supported complete scene replication outside the editor. If not I would expect a warning or error.

**Comment by AThousandShips** [comment]
What specific settings are you manually setting to ensure the behaviour is identical to that in the editor? Are you using the right edit mode when instancing? (Only supported in the editor)

**Comment by albinaask** [comment]
You are completely correct, I didn't pass the "GEN_EDIT_STATE_INSTANCE" to the scene. No mysteries left, what good reason is there that this is an editor only feature? Or is it just not presumed to be useful for outsiders?

**Comment by AThousandShips** [comment]
I think there might be several good reasons, but what I'm just pointing out is that just because something is different it isn't an inconsistency :)

**Comment by albinaask** [comment]
I'll close this bug report here then since the behaviour I've found seem to be default godot behaviour.
