### ISSUE TITLE
Non uniform scale warning on generated PhysicalBone3D

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot#77575]
### Godot version

4.0.2

### System information

Linux

### Issue description

The "Create Physical Skeleton" option for `Skeleton3D` generates some `PhysicalBone3D` object with non-uniform scale. This shows a warning in the editor, and the scale cannot be manually adjusted (though the scale appears to be uniform in the editor).
![1685280836](https://github.com/godotengine/godot/assets/2496231/8570c352-b9b4-4d1f-b2de-a65547220e54)

### Steps to reproduce

1. Open a .glb model with a Skeleton
2. Select "Create Physical Skeleton" from the Skeleton menu
3. Note there are no warnings on the generated bones
4. Save and close the scene
5. Reopen the scene
6. Note that some PhysicalBone3D nodes have a "non-uniform scale" warning
7. Check the scale on those nodes, note that it shows 1,1,1 in the editor (but with a reset icon)
8. Click the reset icon, nothing happens
9. Check the AnimationPlayer, confirm there are no tracks for scale

### Minimal reproduction project

[example.zip](https://github.com/godotengine/godot/files/11584679/example.zip)

**Comment by ThunderBear2006** [comment]
I also have encountered this error, I just discovered if you press the unlink button (The chain symbol under the reset button) and reset the scale the reset icon disappears and it fixes the issue (or does for me) however the warning symbol still remains

**Comment by jbromberg** [comment]
I'm also encountering this issue with a scale of 1,1,1 on the physical bone nodes

**Comment by Calinou** [comment]
cc @aaronfranke

**Comment by aaronfranke** [comment]
<img width="486" alt="Screenshot 2023-10-06 at 3 14 56 PM" src="https://github.com/godotengine/godot/assets/1646875/b42e5aa8-edc6-4ac4-b140-08b9b54c7b67">

The reset icon at the top-right of the scale field indicates that the scale is, in fact, not equal to 1. It's just close enough to 1 that the editor displays it as 1. For "Physical Bone UpperArmL", the difference is actually visible:

<img width="531" alt="Screenshot 2023-10-06 at 3 18 18 PM" src="https://github.com/godotengine/godot/assets/1646875/bc2917ca-d16c-42f6-81b5-fa0662aeb847">

As for a fix to this issue, perhaps the code transferring the transforms from the bones to the PhysicalBone3D nodes should orthonormalize the transform.

**Comment by pgrenon1** [comment]
I'm also getting this issue in 4.1.1. The warning does not go away after resetting the scale of the transforms.

If I understand correctly, it looks like Godot shows the actual value as a tooltip when you hover over the field like so:

![image](https://github.com/godotengine/godot/assets/35233201/30e8ae4e-21de-40e0-bf41-165ca9b1bae7)

But for the scale of these bones, the transforms' scales seem to all be set to 1.

https://github.com/godotengine/godot/assets/35233201/385923ad-9eff-456d-b2f1-1dee16ac42f7

System Info: Godot v4.1.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated Radeon (TM) RX 480 Graphics (Advanced Micro Devices, Inc.; 31.0.21018.6011) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

**Comment by aaronfranke** [comment]
@pgrenon1 The warning may also appear when the transform is sheared, or when a parent's transform is scaled/sheared.

**Comment by pgrenon1** [comment]
@aaronfranke Thanks for the answer! I don't know what this means though :P How do I unshear it?

**Comment by aaronfranke** [comment]
@pgrenon1 You should be able to get rid of any shearing by setting the rotation to any value (just force it to update). Godot doesn't have code to preserve shearing when rotating, so setting any rotation should discard the shearing (if any).

**Comment by mynameisgump** [comment]
Also having this problem when importing from blender and creating a physical skeleton:
<img width="1280" alt="Screen Shot 2023-10-24 at 9 10 59 PM" src="https://github.com/godotengine/godot/assets/47284813/7073c1df-eba5-470b-982b-a9ee96d2e6d6">
doesn't go away when hitting the reset button either

**Comment by aaronfranke** [comment]
@mynameisgump Does #82933 fix the problem for you?

**Comment by mynameisgump** [comment]
> @mynameisgump Does #82933 fix the problem for you?

Just tried out the branch and the warning is still present. Also seems that on import the scale is set to 1.001, clicking the reset button does reset it back to 1,1,1 but the error remains present. Also will add that I'm also testing on a 2020 M1 Mac:
<img width="1421" alt="Screenshot 2023-10-25 at 11 58 14 AM" src="https://github.com/godotengine/godot/assets/47284813/3cdc91f6-0100-4838-805f-255148945bf6">

**Comment by mynameisgump** [comment]
> @mynameisgump Does #82933 fix the problem for you?

Had just commented that it didn't work but realized I forgot to switch branches when testing 🙃 

After compiling and running the warning doesn't seem to appear anymore, so I think it fixed the problem:

<img width="1421" alt="Screenshot 2023-10-25 at 12 20 58 PM" src="https://github.com/godotengine/godot/assets/47284813/7a0303b9-fded-46e9-94f9-8512b0535611">
