### ISSUE TITLE
Minor annoyances around $Node/Paths in scripts

### ISSUE THREAD

**Issue by trollusk** [godotengine/godot#77586]
### Godot version

4.0.2

### System information

Windows 11

### Issue description

Double clicking on `$MyNode` in the script editor will select the whole name including the "$".

But double clicking on `%MyNode` (unique name) will select the name but will not include the "%".

Dragging a node from the scene tree into the script editor brings up the property/method hint list, even though a "." has not been typed. Pressing enter appends "new()" even though this makes no sense as there is no period so it is just appending it directly to the node name: `$MyNodenew()`

### Steps to reproduce

Type `%MyNode` in a script and double click on it.

Type `@onready var x =` in a script, drag a node from the scene tree, then press enter.

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
> Double clicking on $MyNode in the script editor will select the whole name including the "$".
But double clicking on %MyNode (unique name) will select the name but will not include the "%".

Tracked in #56402

> Type @onready var x = in a script, drag a node from the scene tree, then press enter.

You can drag node with Ctrl to add onready var.

**Comment by ApplecrispEric** [comment]
So is the intended behavior that $ should not be selected when double-clicking a node path in the editor? Has this been handled already by #46721 or does the default behavior still needed to be changed?

I would love to tackle this one but I'm not sure where to start.

**Comment by KoBeWi** [comment]
IMO either double-clicking node path should not select $ or it should select % (i.e. it should be consistent). Note that this is discussed in #56402

**Comment by ApplecrispEric** [comment]
I think I was able to fix the bug mentioned above with the autocompletion not canceling when dragging and dropping into the editor. Should that be pushed as a separate PR before tackling the text selection issue?

**Comment by KoBeWi** [comment]
Yes.
