### ISSUE TITLE
Shadows from DirectionalLight don't show any more

### ISSUE THREAD

**Issue by jmf** [godotengine/godot#7760]
**Operating system or device - Godot version:**
Linux 4.8.11, godot  (master)
NVIDIA Corporation GK106 [GeForce GTX 645 OEM] with nouveau driver, mesa 12.0.6

**Issue description:**
Shadows from DirectionalLight sources don't show up any more. OmniLight and SpotLight work as intended though. I traced the problem back to the following commit:

07bbcf91f79480441fdaa1779f7244cdad6e1ba9 is the first bad commit

Date:   Tue Feb 7 23:48:09 2017 -0300

    basic contact shadows implementation, will most likely need some polishing

**Steps to reproduce:**
Add a DirectionalLight and enable shadows. The shadows will not show up, instead all models in the scene will get slightly darker.

**Comment by jmf** [comment]
After further testing, I found that when shadows for DirectionalLight are enabled, the console is spammed with this error message:
```
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL        Type: Error     ID: 32  Severity: High  Message: GL_INVALID_OPERATION in glUniformMatrix(program not linked)
   At: drivers/gles3/rasterizer_gles3.cpp:94.
```
In addition to this, godot doesn't display meshes outside of the editor, when a DirectionalLight with shadows enabled is in the scene. When the shadows checkbox is unchecked the game runs without problems.

**Comment by Zylann** [comment]
Did you check the light's `max distance` property? It's 0 by default, which makes no shadows at all.

**Comment by volzhs** [comment]
last time I checked with master, it works with max distance 0

**Comment by volzhs** [comment]
Linux volzhs-desktop 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Godot 3.0 current master

I can see shadows from directional light with default settings.

Project settings > Renering > Shadows > directional_shadow_size = 2048
DirectioanlLight instance > Light > Shadow > Max Distance = 0

![image](https://cloud.githubusercontent.com/assets/8281454/22772177/969644d8-eede-11e6-8542-d62bc8625637.png)

**Comment by jmf** [comment]
Shadows neither work with MaxDistance = 0 nor any other value for MaxDistance. 
ShadowSize is 2084 (default).
Could you please post the exact godot version you are using? 
What "current master" is, changes every few hours and it's hard to trace back what was current.
(You can find that out by running "git log" in your godot git folder, it is the top line.)

**Comment by jmf** [comment]
This bug doesn't happen in the current master any more.
