### ISSUE TITLE
ParallaxBackground not showing in secondary viewports

### ISSUE THREAD

**Issue by proggen-com** [godotengine/godot#77605]
### Godot version

v4.1.dev3.official [a67d37f7c]

### System information

- OS: Windows 11
- Godot version: v4.1.dev3.official [a67d37f7c]
- Renderer: Vulkan
- Videocard: GTX1060

### Issue description

When adding an extra viewport for a split-screen game and two camera's the ParallaxBackground TileMap doesn't show on the second viewport (All other nodes do show). In the player code I use these lines to assign the camera to the right viewport:
![image](https://github.com/godotengine/godot/assets/91064515/8142f613-cb2c-4014-a11c-4c14c15c05b2)

```
func _ready():
	var viewport = get_node('/root/BugDemo/GridContainer/SubViewportContainer' + str(player) + '/SubViewport')
	var game = get_node('/root/BugDemo/GridContainer/SubViewportContainer1/SubViewport/Game')
	viewport.world_2d = game.get_viewport().world_2d
	$Camera2D.custom_viewport = viewport
	$Camera2D.make_current()
```
The ParallaxBackground TileMap only shows in the first viewport.	

### Steps to reproduce

The example project below demonstrates the issue.

### Minimal reproduction project

[parallaxissue.zip](https://github.com/godotengine/godot/files/11589518/parallaxissue.zip)

**Comment by AThousandShips** [comment]
Related #28222?

**Comment by proggen-com** [comment]
I did a little digging and found a possible issue, the ParallaxBackground is inherited from CanvasLayer, and it doesn't seem to pickup the right viewport. I made a little patch to make it inherit from Node2D instead and now it does show in all viewports, but the position is not correct and the set_layer(...) isn't available. I've also noticed that the canvas layer items have a different camera group name: "__cameras_c" instead of "__cameras_" but just changing that didn't seem to work.

```
diff --git a/scene/2d/parallax_background.cpp b/scene/2d/parallax_background.cpp
index 3d57aaf6aa..a99ba2ce0f 100644
--- a/scene/2d/parallax_background.cpp
+++ b/scene/2d/parallax_background.cpp
@@ -35,7 +35,7 @@
 void ParallaxBackground::_notification(int p_what) {
        switch (p_what) {
                case NOTIFICATION_ENTER_TREE: {
-                       group_name = "__cameras_" + itos(get_viewport().get_id());
+                       group_name = "__cameras_" + itos(get_viewport_rid().get_id());
                        add_to_group(group_name);
                } break;

@@ -73,7 +73,7 @@ void ParallaxBackground::_update_scroll() {

        Vector2 scroll_ofs = base_offset + offset * base_scale;

-       Size2 vps = get_viewport_size();
+       Size2 vps = get_viewport_rect().size;

        scroll_ofs = -scroll_ofs;
        if (limit_begin.x < limit_end.x) {
@@ -186,5 +186,5 @@ void ParallaxBackground::_bind_methods() {
 }

 ParallaxBackground::ParallaxBackground() {
-       set_layer(-100); //behind all by default
+       // set_layer(-100); //behind all by default
 }
diff --git a/scene/2d/parallax_background.h b/scene/2d/parallax_background.h
index 70766ae7fa..b2ed69a9db 100644
--- a/scene/2d/parallax_background.h
+++ b/scene/2d/parallax_background.h
@@ -31,11 +31,10 @@
 #ifndef PARALLAX_BACKGROUND_H
 #define PARALLAX_BACKGROUND_H

-#include "scene/main/canvas_layer.h"
-
-class ParallaxBackground : public CanvasLayer {
-       GDCLASS(ParallaxBackground, CanvasLayer);
+#include "scene/2d/node_2d.h"

+class ParallaxBackground : public Node2D {
+       GDCLASS(ParallaxBackground, Node2D);
        Point2 offset;
        real_t scale = 1.0;
        Point2 base_offset;

```

**Comment by AThousandShips** [comment]
> I made a little patch to make it inherit from Node2D instead

This is not a solution, just to be clear

**Comment by AThousandShips** [comment]
> Thank you, can you please explain why it inherits from CanvasLayer? 

Because it *is* a `CanvasLayer`, it's how it gets the functionality, what is your argument that it should be different?

> I've replaced the ParallaxBackground with a CanvasLayer in the attached demo project and it also doesn't show on other viewports.

Then this bug isn't about `ParallaxBackground` but about `CanvasLayer`, and can't be fixed by changing the former

**Comment by proggen-com** [comment]
> Because it is a CanvasLayer, it's how it gets the functionality, what is your argument that it should be different?

Which functionality? Inheriting from Node2D doesn't change any of it's functionality, it works well.

> Then this bug isn't about ParallaxBackground but about CanvasLayer, and can't be fixed by changing the former

yes

**Comment by AThousandShips** [comment]
> Which functionality? Inheriting from Node2D doesn't change any of it's functionality, it works well.

That of being a canvas layer, it's supposed to be one, the fact that it seems to work doesn't mean it does, there's a lot of details you are probably missing. And yes it *does* change the behaviour. Why are you assuming someone made such a massive mistake and couldn't figure out they could just do this?

**Comment by proggen-com** [comment]
> That of being a canvas layer, it's supposed to be one, 
Please explain why and which details I'm missing. The docs mention that a CanvasLayer's children are on that layer, so a ParallaxBackground can be a child of a CanvasLayer and have that functionality without being a CanvasLayer itself. Perhaps the name "ParallaxBackground" is a bit confusing, it can be a parallax foreground as well.
> Why are you assuming someone made such a massive mistake and couldn't figure out they could just do this?
Why do you call it a massive mistake? ParallaxBackground is having this issue, because the underlying issue is in CanvasLayer. Whether ParallaxBackground should inherit from CanvasLayer is a separate discussion.

**Comment by AThousandShips** [comment]
Listen, it is a `CanvasLayer` because it works as a layer, with specific behaviour, the canvas layer handles the relative movement, so it can't be a `Node2D` because that has transformation, making `ParallaxBackground` a `Node2D` would just not work right, that's why it isn't one. It has a lot of similarities around organizing and processing, a lot of details, if you study the code it will be more clear to you. Please, you haven't stumbled on some ridiculous error, `ParallaxBackground` is supposed to be a `CanvasLayer`, and you aren't understanding the details.

> Why do you call it a massive mistake

Because it would be a massive mistake to make it the wrong kind of node

Have a nice day

**Comment by AThousandShips** [comment]
On further consideration:
I don't think this is a bug at all, it's a limitation, the simple solution to your situation is to add a separate background to each player, just like you would if you had individual UI

**Comment by proggen-com** [comment]
Thanks for taking the time to elaborate on this. I'll be using a custom solution for parallax scrolling with multiple viewports.

**Comment by AThousandShips** [comment]
> I'll be using a custom solution for parallax scrolling with multiple viewports.

what's wrong with the established method that I linked?

**Comment by Zireael07** [comment]
> This should probably be documented, but the fact that CanvasLayer specifies you can add a custom viewport, and that if not specified it will use the default one, should be an indication that it is restricted to a singular viewport, I'm not sure documentation needs to specify this, just like Camera doesn't specify it can only be used with one viewport

For camera this is obvious, but not obvious for Canvas Layer - it should be documented imho

**Comment by AThousandShips** [comment]
But it explicitly states it uses the default viewport?

**Comment by AThousandShips** [comment]
The label should be changed though, as this isn't a bug but a limitation, it only works with a single viewport and a single camera unless the code is fundamentally changed

**Comment by AThousandShips** [comment]
PR open

**Comment by rpahut** [comment]
> On further consideration: I don't think this is a bug at all, it's a limitation, the simple solution to your situation is to add a separate background to each player, just like you would if you had individual UI

I would have to disagree. From the product standpoint, there isn't a line of reasoning that can justify ParallaxBackground being visible in one vport but disappear in another. CanvasLayer or not, as world_2d is the designed and documented way to share the world between multiple viewports, it is expected to handle all apects of that world.

The so called "established" method is in essense a hack, that relies on duplicating same nodes into multiple places on the tree and creating additional scene files that are otherwise not useful for anything. It may just do the job for a basic parallax demo with a single level, but in a real world case it would turn into a massive headache with all the extra scenes, with no way to position the background objects against the main plane, and then still it falls apart completely once camera zooming is added to the mix. As it stands, I am looking at removing the split screen, as these two features of the engine, it seems, are unusable together.

**Comment by AThousandShips** [comment]
`ParallaxBackground` has been replaced with `Parallax2D` so this isn't critical to fix specifically for `ParallaxBackground`, it's a limitation due to how `CanvasLayer` is designed to work, and one of many aspects why it was replaced with `Parallax2D`
