### ISSUE TITLE
Not all children nodes receive _ready() call

### ISSUE THREAD

**Issue by RonYanDaik** [godotengine/godot#77610]
### Godot version

4.1 dev

### System information

Win 10

### Issue description

Have a node and bunch of child nodes.
Some get _ready called, and some do not.

### Steps to reproduce

create a scene and bunch of child nodes with different sripts.

### Minimal reproduction project

n/a

**Comment by Zireael07** [comment]
nothing the team can do without a MRP (and a commit hash, 4.1. dev isn't concrete enough)

**Comment by RonYanDaik** [comment]
Might be connected:
https://github.com/godotengine/godot/issues/76890

**Comment by RonYanDaik** [comment]
Also _notification() is not being called.

**Comment by AThousandShips** [comment]
Are those nodes added to this parent only? Is it the first parent they are added to?

**Comment by KoBeWi** [comment]
This should be impossible, although maybe it's related to child node and threading refactors.

**Comment by RonYanDaik** [comment]
I've found that this is connected to set_name() inside _ready() function
I've added some test nodes. You can see that _ready stops being received after my InvantoryManager node which has _set_name_ in its _ready()_ function

![image](https://github.com/godotengine/godot/assets/3350340/6537229e-6151-4dd7-b832-5e93998e3dd8)

I think i was able to reproduce it in godot-cpp example. You might need to recompile it:
------>>>
[test.zip](https://github.com/godotengine/godot/files/11594240/test.zip)
<<<----

![image](https://github.com/godotengine/godot/assets/3350340/8b3b9bcc-f391-4941-8ec5-e144e110af16)
1. It does not happen every time. If you see every ready message in log try reruning the game again
2. You'll have to click "click me!" button to create some instantiated scenes.

Whats happening:
as you can see nodes with name "wont-recive-ready" are located after Example-new-name node (which has set_name() it its c++ __ready_ function) and do not print ready message in the log.
While nodes that are located before Example node will be receiving __ready()_

**Comment by KoBeWi** [comment]
Related to #76890
Setting name inside `_ready()` no longer works correctly. idk if it can be fixed or we just need to block it.

**Comment by Zireael07** [comment]
> Setting name inside _ready() no longer works correctly

Yikes. I do it all the time to be able to differentiate nodes just after they are added....

**Comment by KoBeWi** [comment]
Set the name before adding. The issue only affects nodes inside tree.

**Comment by Zireael07** [comment]
This issue should be fixed before the next RC, as it's likely to break a LOT of projects

**Comment by AThousandShips** [comment]
As stated here and in #76890 this isn't a trivial thing to fix and while it's clearly important AFIK there's no clear solution in sight

**Comment by akien-mga** [comment]
Probably a regression from https://github.com/godotengine/godot/pull/75627?

**Comment by AThousandShips** [comment]
This also affects `_enter_tree`, see #78650

**Comment by reduz** [comment]
The right fix is check for `data.blocked > 0` in `Node::set_name` and ask the user to use `call_deferred("set_name", ... )` instead. The fix proposed in #78654 has a severe performance implication. With deferred call, names just change and children order dirty is only updated once and only if needed (may not be). This will avoid the game freezing if there are a lot of children nodes that do this logic.

This is a very minor compat breakage vs 4.0, but I think as long as the error explains how to workaround it should be fine.

**Comment by kleonc** [comment]
@reduz As a safe/simple fix for `4.1.stable` I agree with the `data.blocked` check in `Node::set_name`. :+1:

But what do you think about adding a method (as suggested in https://github.com/godotengine/godot/pull/78654#issuecomment-1605755006) like `HashMap::replace_key(const TKey &p_old_key, const TKey &p_new_key)` which would:
- update the existing element's key (so no deallocation/allocation),
- update the [`elements`/`hashes`](https://github.com/godotengine/godot/blob/3710f069293f2fde8afe33fea898c4b36fa5e943/core/templates/hash_map.h#L76-L77) accordingly (so they would change the same as after `erase`+`insert`),
- not change the ordering of the elements ([the linked list part of the data](https://github.com/godotengine/godot/blob/3710f069293f2fde8afe33fea898c4b36fa5e943/core/templates/hash_map.h#L56-L57)) so it would be safe to use even when the HashMap is being iterated over.

Is there anything preventing adding such method / making it be not a viable solution? :thinking:

**Comment by reduz** [comment]
@kleonc Yeah I don't see why not, that could work.
