### ISSUE TITLE
get_stylebox() for a PanelContainer always returns StyleBoxTexture object

### ISSUE THREAD

**Issue by DarkiStar** [godotengine/godot#77628]
### Godot version

v3.6.beta2.official.68c507f59

### System information

- OS: Windows 10

### Issue description

To change the BG Color property of an StyleBoxFlat that was assigned to a PanelContainer I was trying to get the StyleBoxFlat object.
Instead a StyleBoxTexture object is returned always.

![image](https://github.com/godotengine/godot/assets/23613040/3f5ff249-4e21-4de3-afaa-5725c02ecdb4)

### Steps to reproduce

run the attached minimal reproduction project

### Minimal reproduction project

[bug.zip](https://github.com/godotengine/godot/files/11594058/bug.zip)

**Comment by timothyqiu** [comment]
To get the stylebox, it should be either `get('custom_styles/panel')` or `get_stylebox('panel')`. In case of invalid theme item name, `get_stylebox()` returns a default error StyleBoxTexture.
