### ISSUE TITLE
The ._sc_ feature to make godot portable/self-contained cannot be easily created via Windows Explorer

### ISSUE THREAD

**Issue by notnsane** [godotengine/godot#7762]
**Operating system or device - Godot version:** Windows 10 Pro x64 - latest Godot version as of date.

**Issue description:**

This feature (creating a file called **._sc_**)  allows godot to write the settings in the current folder which godot is executed. Windows Explorer limitations on file creation means that this error will popup:

![ulj4yd0](https://cloud.githubusercontent.com/assets/7162375/22760045/94a9f21a-ee33-11e6-8327-2bf301b26508.png)

This is bad UX. This means that the solution only works on Windows if a workaround is used (renaming the file via Command Line) which is not user-friendly at all.

While a config setting would be preferred, this issue is fixed by requiring a file that works perfectly in every OS **without workarounds** (example: "is_portable.txt") . Another option would be to provide a download with this file previously created, so the user won't have to create anything. Another, more complex option, would be to have a setting in option to clone the %APPDATA% folder and then delete the previously used folder (to contemplate all user cases)

I repeat, forcing users to work around Windows Explorer limitations (which is arguably the most used file browser for desktop computers) is bad UX.

**Steps to reproduce:**

1. Download godot and extract
2. Try and create a file called ._sc_

**Comment by karroffel** [comment]
I know it doesn't solve the problem in any way, but that's just bad design from windows.
It's nice because files starting with `.` are hidden by default on all mayor OSs, even Windows IIRC, so it's cool to have a hidden indicator for that.

It's not a real workaround since you can create a file called `._sc_` perfectly fine in Windows, it's just that the explorer is stupid and discriminates files based on extension rather than magic number or stuff like that.

So the coolest thing would be to have a way to tell windows to not be a b*tch about it since the naming itself is pretty good IMO.

An alternative name could be added so it's easier to create from Windows without breaking stuff. (and loosing the cool name)

**Comment by eon-s** [comment]
Maybe the project manager could have some general settings that allows you to alter the mode in which Godot is running, and automatically create/delete the sc file when changing it (and reloading the project manager).

**Comment by vnen** [comment]
I think the easiest solution is to provide an alternative `._sc_` file name for Windows. (I would like more if Microsoft fixed the Windows Explorer). Maybe just `_sc_` could work.

@karroffel 
> It's nice because files starting with . are hidden by default on all mayor OSs, even Windows IIRC

This might be true for all OSs, except Windows. It doesn't hide dotfiles and AFAIK there's no way to tell it to do so (though this is pretty much irrelevant to the issue).

**Comment by notnsane** [comment]
Regardless of wheter is good or bad design of Windows _Explorer_, we should prioritize ease of use. All Windows users will face this issue (if they want to have a portable installation like me) if they use Windows _Explorer_, and I'm pretty sure 100% of them will try to create the file this way since it's the most natural way to do so. It's one extra step that requieres a **mandatory** googling because it isn't explained anywhere in the godot download page.

In all honesty, I also don't see the issue on having a visible file that indicates that the software is running in self-contained or portable mode. It's just a 0 kb file and many softwares use this option if they don't have an integrated solution (like me and eon-s suggested, but that takes developer time off more important tasks).

**Comment by bojidar-bg** [comment]
We ca trivially change `._sc_` to something like `.selfcontained.meta` or whatever. The question is not if we can, it is if we want to.
**Pros:**
* Windows users can finally create it through Microsoft's own exploder.
* Still a hidden file (no change in normal explorers)

**Cons:**
* We have to somehow either change all installations, or check for both files at start. Probably a non-issue in Godot 3.0?

**Comment by akien-mga** [comment]
Best solution is what @vnen mentioned, just add support for both `._sc_` and `_sc_`.

**Comment by Zylann** [comment]
Just curious, why is this mode triggered by the existence of such a file instead of being an option in engine.cfg?

**Comment by bojidar-bg** [comment]
@Zylann That's so that the steam version doesn't read/write global editor settings, but some more localized ones.
