### ISSUE TITLE
Android Plugin can't receive Dictionary with an Array, the result is always null

### ISSUE THREAD

**Issue by gumaciel** [godotengine/godot#77637]
### Godot version

4.1 dev3

### System information

- OS: Windows 11
- Godot: 4.1 dev 3

### Issue description

While trying to create a Android Plugin, I had a problem while trying to send a Dictionary with an Array inside, like:

```gdscript
        var PLUGIN_NAME = "AndroidPluginName"
	if (Engine.has_singleton(PLUGIN_NAME)):
		_plugin = Engine.get_singleton(PLUGIN_NAME)
		var dic_test : Dictionary = {
			"arrayTest" : ["123123", "adsada"]
		}
		_plugin.send_data(dic_test)
```

the result is always `{arrayTest=null}` while trying to print the value of Dictionary received in the Android Plugin

-----
by the way, the Android Plugin receives the value of the array if is sent in another parameter

### Steps to reproduce

Create a simple Android Plugin Project with a method receiving a Dictionary and try to print the result

### Minimal reproduction project

I can't do it now, but it is necessary let me know and I will try to provide it

**Comment by Calinou** [comment]
cc @m4gr3d 

@gumaciel Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
