### ISSUE TITLE
the OS.execute () function on the Android platform

### ISSUE THREAD

**Issue by Atem1995** [godotengine/godot#77639]
### Godot version

4.0.1 stable

### System information

HUAWEI Nova 5 Pro

### Issue description

When I want to run the OS.execute () function on the Android platform, [**OS. execute ("dumpsys", ["location"], output)**], it is clear that I have already opened the positioning authority of the application. But the result is [**permission denial: can't dump location manager service from PID = 27381, uid = 10192 due to missing Android. permission.dump permission**].

_How can I execute **“adb shell dumpsys location”**?_

### Steps to reproduce
![0](https://github.com/godotengine/godot/assets/52338846/cc275de1-b275-426c-9759-cb1fd648dca8)
![1](https://github.com/godotengine/godot/assets/52338846/07df3227-c88d-4480-b0b2-88c96702c581)

略

### Minimal reproduction project

略

**Comment by Calinou** [comment]
I'm fairly sure you can't call this command on a non-rooted device, as mentioned in one of the comments of https://stackoverflow.com/questions/11201659/whats-the-android-adb-shell-dumpsys-tool-and-what-are-its-benefits:

> unfortunately it requires root or system level permission to use in java program.
