### ISSUE TITLE
Exported node arrays only work when debugging in the editor, but not with exported projects

### ISSUE THREAD

**Issue by thornySoap** [godotengine/godot#77641]
### Godot version

4.1.dev3

### System information

Tested with Linux and Android

### Issue description

Since #73256 you can now export a typed array of nodes which holds references to the nodes assigned in the inspector. However, if you export the project you just get an empty array.

### Steps to reproduce

Export a project that makes use of exported node arrays.

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/11596494/test.zip)

**Comment by nezvers** [comment]
Since 4.0 RC versions I thought that's just a bug in a process to be fixed.
Editor doesn't allow assign nodes to exported arrays `@export var back_list:Array[Node]`

**Comment by nezvers** [comment]
That doesn't really makes sense since single node reference works but array of that don't.

**Comment by AThousandShips** [comment]
Oh then my bad, then it's down to the serialisation there then

**Comment by nezvers** [comment]
In my case I can't assign Array[Node] while working in the editor.

**Comment by AThousandShips** [comment]
That's not the bug described here though, are you also on 4.1dev?

**Comment by nezvers** [comment]
Ok, I'll make a new one.

**Comment by thornySoap** [comment]
> Does this occur if you disable **Editor > Export > Convert Text Resources to Binary** in the Project Settings?

Yes, it does

**Comment by AThousandShips** [comment]
I suspect this has something to do with it, will check if it resolves it:
https://github.com/godotengine/godot/blob/2e273f0e35800f2bcc7c05db54100caa97928f69/scene/resources/packed_scene.cpp#L447-L451

**Comment by AThousandShips** [comment]
Upon testing though I cannot replicate this bug

**Comment by AThousandShips** [comment]
Got a PR up, could you verify it @thornySoap, as on your end it seemed slightly different from my end?

**Comment by thornySoap** [comment]
@AThousandShips works great, thank you!
