### ISSUE TITLE
Drag and drop in window does not work if there is a sibling window presents at specific positions

### ISSUE THREAD

**Issue by zhhrozhh** [godotengine/godot#77665]
### Godot version

4.1-dev3

### System information

Ubuntu 23.04

### Issue description

Can not drag or drop nodes inside a window if there is another opened window at some specific positions

### Steps to reproduce

In the reproduction project, no matter where the second window is, as long as the first window's position is close to (0, 0), drag/drop related methods in the second window will not be triggered.

### Minimal reproduction project
[Reproduce.zip](https://github.com/godotengine/godot/files/11601793/Reproduce.zip)

**Comment by Sauermann** [comment]
I can confirm this bug and have verified that it gets fixed by #67531.
