### ISSUE TITLE
[GDScript 2] Reference leaking inside IF scope

### ISSUE THREAD

**Issue by felaugmar** [godotengine/godot#77666]
### Godot version

v4.0.3.stable.official [5222a99f5]
Master [6101240231600c871f5c5473872532c68ea3268c] (confirmed by https://github.com/godotengine/godot/issues/77666#issuecomment-1568952502)

### System information

Window 10

### Issue description

References are not unreferenced at the end of `if` scopes.

### Steps to reproduce

Copy, paste and run the snippet below, check the results:

```gdscript
extends Node


func _ready() -> void:
  var ref := RefCounted.new()
  var ref_count : int

  # OK
  ref_count = ref.get_reference_count()
  print('Expected: 1, Result: %d' % ref_count)

  # OK
  if true:
    var temp := ref
    temp = null

  ref_count = ref.get_reference_count()
  print('Expected: 1, Result: %d' % ref_count)

  # FAIL
  if true:
    var temp := ref

  ref_count = ref.get_reference_count()
  print('Expected: 1, Result: %d' % ref_count)
```

Output example:

```
Expected: 1, Result: 1
Expected: 1, Result: 1
Expected: 1, Result: 2
```

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Do they remain outside of function scope?

**Comment by bitsawer** [comment]
Current master at 6101240231600c871f5c5473872532c68ea3268c gives this:

```
Expected: 1, Result: 1
Expected: 1, Result: 1
Expected: 1, Result: 2
```

I don't know expected this is, I'm not sure if GDScript any any official guarantees about if/else etc. scope reference lifetimes.

**Comment by felaugmar** [comment]
@dalexeev https://github.com/godotengine/godot/issues/77666#issuecomment-1572517508

Thanks, the disassembling you posted here explains why this happens.

This behavior is understandable for "Struct-like" types (int, float, string), but ends up messing an important aspect of `RefCounted`.
