### ISSUE TITLE
Scripts cannot be loaded from additional C# projects.

### ISSUE THREAD

**Issue by Carsillas** [godotengine/godot#77675]
### Godot version

v4.0.3.stable.mono.official [5222a99f5]

### System information

Windows 10 - Godot 4.0.3.stable

### Issue description

Currently in Godot 4.0.3 you cannot have an additional C# project included in the solution with scripts. It would be nice for organization to allow multiple assemblies. As Godot uses source distribution for addons it would be very beneficial to allow csproj files to be included in this, so the csproj can define nuget/other references.

Assigning a script to a Node from another assembly results in this error at runtime: 

`Cannot instance script because the associated class could not be found. Script: 'res://SecondaryCsproj/ScriptB.cs'. Make sure the script exists and contains a class definition with a name that matches the filename of the script exactly (it's case-sensitive).`

I would expect it to load normally in the same way as other scripts in the project.

This may be related to #75352 but is not the same issue, the issue described by that ticket seems specific to runtime loading of assemblies. 

### Steps to reproduce

In the attached reproduction project I have created a second C# project in the solution and excluded the contents from the main project. It may be beneficial to allow the main csproj to occupy a subfolder instead of being required in the root of the project to avoid the necessity of excluding other csproj's source.

Just open the main scene and run, note that ScriptA executes normally, ScriptB fails to load.

### Minimal reproduction project

[MultipleCsprojBugReport.zip](https://github.com/godotengine/godot/files/11607985/MultipleCsprojBugReport.zip)

**Comment by RedworkDE** [comment]
It is the same underlying cause as the linked issue, currently scripts are fundamentally only looked up in the main assembly, so the same enhancement will likely enable both use cases.

**Comment by orolyn** [comment]
I've added this to my external project, I tested that abstract node with _Process are called when inherited by the main godot project, and it worked.

```
  <ItemGroup>
    <PackageReference Include="Godot.SourceGenerators" Version="4.1.1"
					  OutputItemType="Analyzer"
					  ReferenceOutputAssembly="false" />
    <PackageReference Include="GodotSharp" Version="4.1.1" />
  </ItemGroup>
	
  <PropertyGroup>
	<GodotProjectDir>$(MSBuildProjectDirectory)</GodotProjectDir>
  </PropertyGroup>
```

Whether or not its accidental that this is possible im not sure. I figured that the same source generators that provide the event method metadata for the main project could be used on an external one. GodotProjectDir is mandatory though.

This *might* solve the issue on https://github.com/godotengine/godot/issues/75352

**Comment by haltingstate** [comment]
Does this issue still exist? Is there a work around?

Can scripts in other assemblies be manually registered with godot?

**Comment by paulloz** [comment]
Closing to consolidate in #75352.
