### ISSUE TITLE
export exe false

### ISSUE THREAD

**Issue by wzc1392969921** [godotengine/godot#77679]
### Godot version

3.5

### System information

windows11

### Issue description

it is my project.
<img width="241" alt="image" src="https://github.com/godotengine/godot/assets/58593965/7d2f5d9a-fe0a-4651-8d32-2cdca158ab7a">
in tools file ,i have a exe file want to ues.
 in code,i want to copy "res://tools/main.exe" to "user://main.exe".

in my editor, it is right.but in export exe appliaction, if not copy.
why?

### Steps to reproduce

<img width="446" alt="image" src="https://github.com/godotengine/godot/assets/58593965/fff0aa83-21c3-4164-9b8d-9e0bfc801820">

### Minimal reproduction project

<img width="446" alt="image" src="https://github.com/godotengine/godot/assets/58593965/bddb9159-3ad3-4048-b3a5-f93a94915388">

**Comment by wzc1392969921** [comment]
[新建游戏项目.zip](https://github.com/godotengine/godot/files/11608967/default.zip)
this is source code.

**Comment by Zireael07** [comment]
Exported application doesn't have access to res://
use user://

**Comment by AThousandShips** [comment]
You have just added "main.exe" to your include filters, I think you need to do "tools/main.exe" for this to work

**Comment by Calinou** [comment]
You probably need to add `*.exe` to your non-resource export filter, as exact file names aren't supported according to https://github.com/godotengine/godot/issues/17053.

**Comment by Calinou** [comment]
@wzc1392969921 Did my above suggestion resolve the issue on your end?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.
