### ISSUE TITLE
Linked vector properties break their ratio when going through zero

### ISSUE THREAD

**Issue by YuriSizov** [godotengine/godot#77687]
### Godot version

4.0+

### System information

Windows 11 22H2

### Issue description

The new feature to link components of a vector value in the inspector, so changing them individually maintains a ratio, has a flaw when it comes to zero values. Since you can't use 0 to build a sensible ratio (what's the ratio of 0 / 20 or 12 / 0 / 5?), having any component reach this value results in values not being updated in a sensible manner anymore.

In plain terms, if you set up some ratio, enable linking, and then drag one of the components in the inspector through the value of 0 multiple times, eventually every component will have the same value (sometimes they will have different signs, depending on the exact starting values). It looks like this:

https://github.com/godotengine/godot/assets/11782833/b5c9b04e-0895-465d-8976-0ba2872149c6

https://github.com/godotengine/godot/assets/11782833/35b9d12a-2994-4d53-b297-f1721036d6e0

https://github.com/godotengine/godot/assets/11782833/09de4cce-5012-4f4c-9aeb-bf48f2bf019f

https://github.com/godotengine/godot/assets/11782833/ee5940b9-c2bd-4b3b-a7d7-b86984bc4250

### Steps to reproduce

You can reproduce it with any engine property with linking available, such as position of spatial (2D, 3D) nodes. Here's a short script I used to test all Vector2/3/4 types (relies on changes from https://github.com/godotengine/godot/pull/77135):

```gdscript

@tool
extends Node3D

var my_vector2 : Vector2
var his_vector2i : Vector2i
var your_vector3 : Vector3
var her_vector3i : Vector3i
var their_vector4 : Vector4
var our_vector4i : Vector4i

func _get_property_list() -> Array:
	return [
		{
			"name": "my_vector2",
			"type": TYPE_VECTOR2,
			"hint": PROPERTY_HINT_LINK,
		},
		{
			"name": "his_vector2i",
			"type": TYPE_VECTOR2I,
			"hint": PROPERTY_HINT_LINK,
		},
		{
			"name": "your_vector3",
			"type": TYPE_VECTOR3,
			"hint": PROPERTY_HINT_LINK,
		},
		{
			"name": "her_vector3i",
			"type": TYPE_VECTOR3I,
			"hint": PROPERTY_HINT_LINK,
		},
		{
			"name": "their_vector4",
			"type": TYPE_VECTOR4,
			"hint": PROPERTY_HINT_LINK,
		},
		{
			"name": "our_vector4i",
			"type": TYPE_VECTOR4I,
			"hint": PROPERTY_HINT_LINK,
		},
	]

```

### Minimal reproduction project

See above.

**Comment by YuriSizov** [comment]
I think the best possible way to solve this would be to keep the initial/last valid ratio for a set of changes to the components, so if we reach 0, we don't break and can recover. There is still a problem with starting from the 0 value though.

Here's what @kleonc noted about that in https://github.com/godotengine/godot/pull/77135:

> Currently in `EditorPropertyVectorN::_update_ratio` if any of the sliders has zero value then all ratios will be set to `1.0`. I think this should be changed and be resolved per component.
> 
> When dragging/changing value of a non-zero component, then all components can be scaled properly according to the ratios (at the start of the change), including the zero ones (they'll remain zero). So for `(x, y, z)` changing e.g. non-zero `x` to `new_x` would result in `new_x * (1, y/x, z/x)`. Like for `(1, 0, 2)` changing `x` to `3` would result in `(3, 0, 6)`. That's correct and expected and should be made like that.
> 
> The question is what the behavior should be when dragging/changing value of a zero component. I don't think there's an obvious expected behavior, it's rather a matter of making an arbitrary choice.
> - According to the ratios what would be correct is setting other non-zero components to infinities. It might be not desired though. :thinking: E.g. for `(1, 0, -2, 0)` changing `y` to `3` would result in `(INF, 3, -INF, 3)` (could be argued it should result in`(INF, 3, -INF, 0)` instead).
> - Another possibility would be to totally ignore linking for zero values. So for `(1, 0, -2, 0)` changing `y` to `3` would result in `(1, 3, -2, 0)` (or keep only the zeros linked so result would be `(1, 3, -2, 3)`:laughing:).
> - Maybe some other possibilities...
> 
> The decision on the behavior is needed before the implementation of course. :upside_down_face:
> 
> Also it should be ensured that e.g. when dragging the value in the inspector the `_update_ratio` is called only when the drag starts/ends. Haven't checked if it's currently like that but calling it in the middle of the drag could likely cause issues when going through zero (because of the different behavior), like the one mentioned in https://github.com/godotengine/godot/pull/77135#issuecomment-1568379310.

I agree that when we start from 0 it would probably make the most sense to ignore linking/ratio all together, as I don't see what logical ratio value we can use instead, especially for floating point vectors.

cc @KoBeWi

**Comment by lostminds** [comment]
I ran into this issue when working on a graphics app (though only 2D) where I wanted to lock ratios of 2D vectors. One not so unusual special case you might want to consider here as well is locking the ratio when all components are 0, this will have the same divide by zero INF issues, but I think this should be treated as ratio 1, so that all components are equal when they are scaled up.
