### ISSUE TITLE
Can't move directories in filesystem dock

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#77689]
### Godot version

4.1 dev3

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

Trying to move a folder results in moving error and it's not moved.
Regression from #75330

A fix already exists, but I'm opening an issue so it's not lost (the PR isn't ready and not very active).

### Steps to reproduce

1. Add 2 folders in filesystem
2. Move one folder into another one

### Minimal reproduction project

N/A

**Comment by caimantilla** [comment]
This is a serious issue, it needs to be fixed ASAP.
Not being able to move folders in the filesystem dock (that is, without breaking resource references) is totally debilitating.

**Comment by KoBeWi** [comment]
As a workaround you can move all of the folder's files. It has the same effect.

**Comment by caimantilla** [comment]
> As a workaround you can move all of the folder's files. It has the same effect.

This is nearly impossible with lots of nesting, though.
