### ISSUE TITLE
`GridMap`: Attempted to merge a navigation mesh triangle edge with another already-merged edge

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#77690]
### Godot version

4.0.rc3.official.7e79aead9

### System information

Mac

### Issue description

When using `NavigationMesh` and `GridMap`, an error is shown on each start:

```error
ERROR: Attempted to merge a navigation mesh triangle edge with another already-merged edge. This happens when the current `cell_size` is different from the one used to generate the navigation mesh. This will cause navigation problems.
```

```gdscript
@tool
extends Node3D


func _ready():
	var map = ResourceLoader.load("level.tres").build()
	self.add_child(map)

	var child: GridMap = map.get_child(0)

	var lib: MeshLibrary = child.get_mesh_library()
	var items = lib.get_item_list()

	for id in items:
		print(lib.get_item_navigation_mesh_transform(id))

	var map_id: RID = child.get_navigation_map()

	print(child.get_cell_size())
	NavigationServer3D.map_force_update(map_id)
	NavigationServer3D.map_set_active(map_id, true)

	print(NavigationServer3D.map_is_active(map_id))
	print(NavigationServer3D.map_get_regions(map_id))
```

The above outputs:

```log
[X: (0.9, 0, 0), Y: (0, 1, 0), Z: (0, 0, 0.9), O: (0, 0.125, 0)]
[X: (0.9, 0, 0), Y: (0, 1, 0), Z: (0, 0, 0.9), O: (0, 0.125, 0)]
[X: (0.9, 0, 0), Y: (0, 1, 0), Z: (0, 0, 0.9), O: (0, 0.125, 0)]
[X: (0.9, 0, 0), Y: (0, 1, 0), Z: (0, 0, 0.9), O: (0, 0.125, 0)]
[X: (0.9, 0, 0), Y: (0, 1, 0), Z: (0, 0, 0.9), O: (0, 0.125, 0)]
[X: (0.9, 0, 0), Y: (0, 1, 0), Z: (0, 0, 0.9), O: (0, 0.125, 0)]
[X: (0.9, 0, 0), Y: (0, 1, 0), Z: (0, 0, 0.9), O: (0, 0.125, 0)]
[X: (0.9, 0, 0), Y: (0, 1, 0), Z: (0, 0, 0.9), O: (0, 0.125, 0)]
[X: (0.9, 0, 0), Y: (0, 1, 0), Z: (0, 0, 0.9), O: (0, 0.125, 0)]
[X: (0.9, 0, 0), Y: (0, 1, 0), Z: (0, 0, 0.9), O: (0, 0.125, 0)]
[X: (0.9, 0, 0), Y: (0, 1, 0), Z: (0, 0, 0.9), O: (0, 0.125, 0)]
[X: (0.9, 0, 0), Y: (0, 1, 0), Z: (0, 0, 0.9), O: (0, 0.125, 0)]
[X: (0.9, 0, 0), Y: (0, 1, 0), Z: (0, 0, 0.9), O: (0, 0.125, 0)]
[X: (0.9, 0, 0), Y: (0, 1, 0), Z: (0, 0, 0.9), O: (0, 0.125, 0)]
[X: (0.9, 0, 0), Y: (0, 1, 0), Z: (0, 0, 0.9), O: (0, 0.125, 0)]
[X: (0.9, 0, 0), Y: (0, 1, 0), Z: (0, 0, 0.9), O: (0, 0.125, 0)]
[X: (0.9, 0, 0), Y: (0, 1, 0), Z: (0, 0, 0.9), O: (0, 0.125, 0)]
[X: (0.9, 0, 0), Y: (0, 1, 0), Z: (0, 0, 0.9), O: (0, 0.125, 0)]
[X: (0.9, 0, 0), Y: (0, 1, 0), Z: (0, 0, 0.9), O: (0, 0.125, 0)]
[X: (0.9, 0, 0), Y: (0, 1, 0), Z: (0, 0, 0.9), O: (0, 0.125, 0)]
[X: (0.9, 0, 0), Y: (0, 1, 0), Z: (0, 0, 0.9), O: (0, 0.125, 0)]
[X: (0.9, 0, 0), Y: (0, 1, 0), Z: (0, 0, 0.9), O: (0, 0.125, 0)]
[X: (0.9, 0, 0), Y: (0, 1, 0), Z: (0, 0, 0.9), O: (0, 0.125, 0)]
[X: (0.9, 0, 0), Y: (0, 1, 0), Z: (0, 0, 0.9), O: (0, 0.125, 0)]
[X: (0.9, 0, 0), Y: (0, 1, 0), Z: (0, 0, 0.9), O: (0, 0.125, 0)]
(0.25, 0.25, 0.25)
true
[]
ERROR: Attempted to merge a navigation mesh triangle edge with another already-merged edge. This happens when the current `cell_size` is different from the one used to generate the navigation mesh. This will cause navigation problems.
   at: sync (modules/navigation/nav_map.cpp:692)
```

<img width="688" alt="Screenshot 2023-05-31 at 16 57 14" src="https://github.com/godotengine/godot/assets/100964/54f85fad-1f30-4632-ad37-71d4c6244036">

As can be seen above, the nav-meshes are not touching each other.

They are also unique, although I would prefer to use the same nav-mesh over and over.

### Steps to reproduce

1. Download the project below
2. Run the project

### Minimal reproduction project

[test-navmesh.zip](https://github.com/godotengine/godot/files/11611370/test-navmesh.zip)

**Comment by smix8** [comment]
That is not a valid navigation mesh in your screenshot. Same issue as in the linked issue.

**Comment by tavurth** [comment]
@smix8 Hmm, how does the `NavigationMesh.create_from_mesh` work then?

**Comment by smix8** [comment]
As the documentation mentions the create_from_mesh() function copies over the vertices and indices from the mesh resource.

What it does not do is validate the mesh data for a navigation mesh or bake.

**Comment by tavurth** [comment]
I also added a hand-built grid-map with navigation meshes built in this way:

<img width="407" alt="Screenshot 2023-05-31 at 17 19 47" src="https://github.com/godotengine/godot/assets/100964/19d8d6bb-7910-4bb6-94a1-d50f55705ef6">

If that's not the correct way to do this, then it's very confusing 🤔 

[test-navmesh.zip](https://github.com/godotengine/godot/files/11611806/test-navmesh.zip)

**Comment by tavurth** [comment]
> As the documentation mentions the create_from_mesh() function copies over the vertices and indices from the mesh resource.

Ok I'm still confused 🤔 

So I should only be using the top surface of the mesh to build a navmesh?

**Comment by smix8** [comment]
@tavurth 
You can export your MeshLibrary with a setup like in the documentation that you can find here https://docs.godotengine.org/en/stable/tutorials/3d/using_gridmaps.html#navigationmeshes where you already baked the navmesh on the NavigationRegion3D.
You can also create a simple bake scene with just a NavigationRegion3D and a NavigationMesh with agent radius 0 and add the content of your GridMap cell below and bake the navmesh. Now save the navmesh to a file and add it to your GridMal MeshLibrary item.

**Comment by tavurth** [comment]
> You can also create a simple bake scene with just a NavigationRegion3D and a NavigationMesh with agent radius 0 and add the content of your GridMap cell below and bake the navmesh. Now save the navmesh to a file and add it to your GridMal MeshLibrary item.

Hmm I didn't understand this exactly, as a `NavMesh` does not exist as a `Node` but rather as a `Resource`. 

I created a new plane instance and moved it to the top of my Mesh:

<img width="353" alt="Screenshot 2023-05-31 at 17 32 16" src="https://github.com/godotengine/godot/assets/100964/bf3300df-6986-4731-b5a7-3600dadea3f1">

<img width="421" alt="Screenshot 2023-05-31 at 17 34 13" src="https://github.com/godotengine/godot/assets/100964/2c015777-7dc8-4237-849b-6ab1246211ce">

Then create the navigation mesh:

<img width="334" alt="Screenshot 2023-05-31 at 17 34 20" src="https://github.com/godotengine/godot/assets/100964/98d0e2bf-bb36-4d49-be90-13876a24c0eb">

<img width="331" alt="Screenshot 2023-05-31 at 17 34 36" src="https://github.com/godotengine/godot/assets/100964/c2c4f3f8-79a1-4082-985a-163210f68481">

And move the NavigationRegion to be just below the main floor Mesh:

<img width="337" alt="Screenshot 2023-05-31 at 17 34 59" src="https://github.com/godotengine/godot/assets/100964/8b06960a-59a6-4cc6-8c37-7cf4c47e0e1b">

<img width="384" alt="Screenshot 2023-05-31 at 17 35 03" src="https://github.com/godotengine/godot/assets/100964/65e3d3de-3316-4e1c-baaf-bdaeecf3eaba">

And export as a MeshLibrary:

<img width="153" alt="Screenshot 2023-05-31 at 17 35 19" src="https://github.com/godotengine/godot/assets/100964/9a204dbb-cb49-4b49-84ca-df95d8d5437c">

Why are these purple triangles appearing? 🤔 

<img width="688" alt="Screenshot 2023-05-31 at 17 30 26" src="https://github.com/godotengine/godot/assets/100964/6ba10097-cf8b-4125-84b1-3c8c361bd25c">

Also the following code:

```gdscript
func _ready():
	for map_id in NavigationServer3D.get_maps():
		prints("MAP ID", map_id)
		print(NavigationServer3D.map_is_active(map_id))
		print(NavigationServer3D.map_get_regions(map_id))
```

Outputs nothing:

```log
MAP ID RID(597000454144)
false
[]
```

[test-navmesh.zip](https://github.com/godotengine/godot/files/11611891/test-navmesh.zip)

**Comment by tavurth** [comment]
> In general I would suggest to not use the cell baked navigation if you want agent radius cause the GridMap has the same issues as TileMap in that you can not shrink the navigation meshes on a tile / grid layout without causing seams. It is better to have a NavigationRegion3D as a parent that bakes a (secondary?) GridMap that has only those cells that should be used for navigation.

Ok so this is working at runtime now? Last time I checked it was broken from threading concerns.

If that does work, I guess I can add a `GridMap` below the `NavigationRegion3D` and bake at map export time.

**Comment by tavurth** [comment]
I will take a look at this also:

https://docs.godotengine.org/en/4.0/tutorials/navigation/navigation_using_navigationmeshes.html#navigationmesh-rebaking-at-runtime

**Comment by tavurth** [comment]
@smix8 

https://docs.godotengine.org/en/4.0/tutorials/navigation/navigation_using_navigationmeshes.html#navmesh-for-3d-gridmaps

This is exactly what I'm doing at the moment 🤔 

And yet this code from the docs generates a NavMesh with volume.

**Comment by smix8** [comment]
@tavurth 

Please edit your last post when you want to add something.

- Add a NavigationRegion3D
- Add a NavigationMesh on the NavigationRegion3D
- Set the agent_radius to 0 on the NavigationMesh
- Add a MeshInstance3D with a Plane Mesh the size of your GridMap cell box and move the plane to the box ground level.
- Hit bake and use that NavigationMesh resource on your GridMap MeshLibrary item.

The NavigationServer syncs on the physics update.
If you query the server get_maps() in a _ready() function you are querying an empty server without maps.
[Doc about NavigationServer synchronization](https://docs.godotengine.org/en/latest/tutorials/navigation/navigation_using_navigationservers.html#waiting-for-synchronization)

The code snippet for the procedual GridMap navigation was made for a GridMap using plane meshes, not box meshes on any other shaped mesh. This needs to be added to the explanation.

Threaded navigation mesh baking is currently not possible in master or Godot 4 dev3 due to the recent SceneTree threading changes. The fix has not been merged yet https://github.com/godotengine/godot/pull/77412

**Comment by tavurth** [comment]
> Please edit your last post when you want to add something while no one has responded.

Ok 👍 

> If you query the server get_maps() in a _ready() function you are querying an empty server without maps.
Aha that makes sense, changed to the following and it displays:

```gdscript
func _ready():
	await NavigationServer3D.map_changed

	for map_id in NavigationServer3D.get_maps():
		prints("MAP ID", map_id)
		print(NavigationServer3D.map_is_active(map_id))
		print(NavigationServer3D.map_get_regions(map_id))
```

```log
[RID(618475290624), RID(639950127105), RID(648540061698), RID(657129996291)]
```

<img width="688" alt="Screenshot 2023-05-31 at 18 03 56" src="https://github.com/godotengine/godot/assets/100964/10cfc2b3-4483-47d5-a872-e47cb1e9a004">

- I'm still unsure what these pink triangles are, I didn't see them in any of the docs images, is that normal?

> In general I would suggest to not use the cell baked navigation if you want agent radius cause the GridMap has the same issues as TileMap in that you can not shrink the navigation meshes on a tile / grid layout without causing seams. It is better to have a NavigationRegion3D as a parent that bakes a (secondary?) GridMap that has only those cells that should be used for navigation.

- I'm still unsure how to proceed with this suggested approach, perhaps you know of some relevant documentation?

I have compiled the sample here for others to use as a reference:

[test-navmesh.zip](https://github.com/godotengine/godot/files/11612224/test-navmesh.zip)

**Comment by smix8** [comment]
> I'm still unsure how to proceed with this suggested approach, perhaps you know of some relevant documentation?

Don't use navigation meshes inside the GridMap MeshLibrary. Instead, place a(nother?) GridMap below a NavigationRegion3D node with the single purpose of having all the cells that should have navigation mesh. This GridMap should only have cells that should have navigation meshes as the NavigationRegion3D will parse them. You can control if visual meshes or collision shapes or both are parsed with the NavigationMesh geometry property on the NavigationRegion3D. Bake a navigation mesh for the entire GridMap so the mesh can shrink to agent size without seams between your cells. This is both better for pathfinding quality and performance compared to having a single navigation mesh for every single GridMap cell.

> Perhaps NavigationMesh.create_from_mesh could automatically figure out the faces closest to the UP_VECTOR and use those for baking to avoid this volume issue?

That is what the navigation mesh baking does. The process to make sense from a random mesh is not that simple as it may look.

This create_from_mesh() function is a legacy problem that should be deprecated which I made a pr for https://github.com/godotengine/godot/pull/77702. This function gives users the illusion that they do something correct by copying visual Mesh data directly to a NavigationMesh while this is 95% of the times wrong, and those 5% are mostly plane meshes. All the documentation script examples that use this function assume plane, or at least flat surface, meshes without mentioning it explicit but that is another issue.

The function is from a time where Godot had a very simplistic concept of what a valid navigation mesh could and should be, with no navigation mesh connections and no NavigationServer to worry about. The vast majority of visual meshes have inherently invalid data for navigation mesh use. It makes little sense to support such a data copy directly with a dropdown Editor option that most new users will stumble over.

For those that know how to create valid navigation mesh data in script the functions to add vertices and polygons to a NavigationMesh exist while everyone else should use the navigation mesh baking.

**Comment by tavurth** [comment]
@smix8 Ok I'm trying it now:

## First I've tried like this:

<img width="372" alt="Screenshot 2023-06-03 at 17 16 53" src="https://github.com/godotengine/godot/assets/100964/d0af7bdc-1ca5-4e4a-b20d-51da71190a28">

<img width="501" alt="Screenshot 2023-06-03 at 17 16 58" src="https://github.com/godotengine/godot/assets/100964/c9a00ba4-3b14-40f9-a25b-33cb71fe8a1c">

When I bake the parent `NavigationRegion3D` and then delete the child `NavigationRegion3D` nodes there is no remaining mesh 🤔 


## Next I tried like this:

<img width="375" alt="Screenshot 2023-06-03 at 17 18 13" src="https://github.com/godotengine/godot/assets/100964/6446ba70-2f32-45b3-a418-b56026999ab2">

<img width="500" alt="Screenshot 2023-06-03 at 17 18 17" src="https://github.com/godotengine/godot/assets/100964/2c0c6c0a-454b-47e9-8ed8-a4bdd90a8392">

<img width="369" alt="Screenshot 2023-06-03 at 17 20 27" src="https://github.com/godotengine/godot/assets/100964/6378fc52-6a89-49d9-8e10-35516a7da804">

Then bake the parent and delete the `MeshInstance3D` nodes, ok nothing there...


## Next I tried like this:

<img width="375" alt="Screenshot 2023-06-03 at 17 19 11" src="https://github.com/godotengine/godot/assets/100964/5702cdfe-595b-41b8-858a-01df3d30215a">

<img width="504" alt="Screenshot 2023-06-03 at 17 19 17" src="https://github.com/godotengine/godot/assets/100964/9cca9b7f-8eda-4e71-addb-020f4d340f16">

<img width="369" alt="Screenshot 2023-06-03 at 17 20 27" src="https://github.com/godotengine/godot/assets/100964/6378fc52-6a89-49d9-8e10-35516a7da804">

Ok, after baking and deletion the parent still has no `NavigationMesh` data.

## Next I tried this:

<img width="363" alt="Screenshot 2023-06-03 at 17 21 15" src="https://github.com/godotengine/godot/assets/100964/bafc7d37-e288-431d-8b57-bfdb0b94c826">

<img width="362" alt="Screenshot 2023-06-03 at 17 21 24" src="https://github.com/godotengine/godot/assets/100964/834647ec-b86d-4a62-bad9-4a257f82d96b">

After pressing "Bake navmesh" on the parent and deleting the children, no results.

## Conclusion?

I've no idea how we're expected to bake a `NavMesh` as you mentioned many times previously.

Could you make a small tutorial, or perhaps some pointers?

**Comment by tavurth** [comment]
Aha I figured it out, earlier you mentioned "With agent radius 0"

<img width="347" alt="Screenshot 2023-06-03 at 17 33 30" src="https://github.com/godotengine/godot/assets/100964/4b4e871d-3ed5-4d9c-a13c-de2848bcb8ec">


<img width="593" alt="Screenshot 2023-06-03 at 17 32 49" src="https://github.com/godotengine/godot/assets/100964/ac3fb1d1-b483-44de-9606-138c06dd1f7a">


Why is this the way to bake a `NavMesh`?

Can we document this, or perhaps better, can we just allow baking with a non-zero agent radius?

**Comment by smix8** [comment]
@tavurth 
The basic tutorial steps to make a navigation scene are in the 2D & 3D Navigation Overviews of the documentation. As those are the first pages of the navigation documentation it is assumed that people encounter them first. The 3D tutorial to bake and run a basic 3D navigation scene can be found [here](https://docs.godotengine.org/en/latest/tutorials/navigation/navigation_introduction_3d.html).

**Comment by tavurth** [comment]
> The Nr.1 issue / complain of 2D users is agent clipping because 2D has no auto-margin for agent sizes. 3D users never voice similar issues thanks to the default agent size.

Yes it's something I even built a bespoke a star for before in godot 3.x. Glad to see were getting a few improvements.

So far it's fairly logical, but there are some small gotchas like nice to have some more error messages when I'm doing something stupid.

> As those are the first pages of the navigation documentation it is assumed that people encounter them first. The 3D tutorial to bake and run a basic 3D navigation scene can be found here. 

While this may be true godot docs don't seem to have a great SEO at the moment and none of my Google searches have landed on those tutorials. 

I will take a look and see if I can find them. 

I will also throw these prs into chatgpt soon and see if we can get a nice step by step for gridmap, using the images I posted above.

**Comment by smix8** [comment]
Closing the issue as the discussion has run stale for some time now and there is no bug and I think all points have been answered or can be found in the documentation by now. Also there were some improved error msg in the 4.1 release for this error. Feel free to comment if you think otherwise so we can reopen.
