### ISSUE TITLE
Editor Crash when pressing "Control + S" with .gdshaderinc open in shader editor

### ISSUE THREAD

**Issue by nan0m** [godotengine/godot#77701]
### Godot version

Godot Engine v4.1.dev3 [a67d37f7c]

### System information

Windows 10, i711800H, Forward+ Vulkan

### Issue description

If I have a .gdshaderinc open in the bottompanel shader editor and then press CTRL + S to save the current scene the editor crashes and closes. However, it seems to work if I press save via File > Save File.
This is even an issue with an empty .gdshaderinc file

### Steps to reproduce

1. Open Main Scene
2. Open .gdshaderinc
3.  Press CTRL + S

### Minimal reproduction project

[MRP.zip](https://github.com/godotengine/godot/files/11616811/MRP.zip)

**Comment by bitsawer** [comment]
This was fixed in the master by https://github.com/godotengine/godot/pull/77467, fix should be in the next release.

**Comment by Chaosus** [comment]
Closed as fixed by https://github.com/godotengine/godot/pull/77467
