### ISSUE TITLE
Forward+ crashes when opens project on NVIDIA GeForce GTX 880M

### ISSUE THREAD

**Issue by StreamVersus** [godotengine/godot#77711]
### Godot version

4.0.3

### System information

Win10(22h2), 880m(Vulkan 1.1.126), 425.31(latest) driver, Forward+

### Issue description

When starting project, or trying to run scene, window closes with no error in console

### Steps to reproduce

1. Start GODOT
2. Create project with Forward+ render type
3. Start project
4. Crash

### Minimal reproduction project

No need in these, all projects(even blank ones) crashes

**Comment by akien-mga** [comment]
Do you happen to have an AMD integrated GPU?

Could you test 4.1 beta 1 to see if this improved? https://godotengine.org/article/dev-snapshot-godot-4-1-beta-1/

**Comment by Calinou** [comment]
The [GTX 880M](https://www.techpowerup.com/gpu-specs/geforce-gtx-880m.c2534) is a Kepler GPU, which lacks Vulkan support on mobile.

**Comment by StreamVersus** [comment]
No i dont have any amd igpu
![image](https://github.com/godotengine/godot/assets/127424589/2574b2f3-959a-4475-9242-aa7e6356cd13)
Gpu does support vulkan in gpu-z

**Comment by StreamVersus** [comment]
> The [GTX 880M](https://www.techpowerup.com/gpu-specs/geforce-gtx-880m.c2534) is a Kepler GPU, which lacks Vulkan support on mobile (it's only supported on desktop on Kepler). You need to use the Compatibility rendering method instead, which uses OpenGL.

You added link to www.techpowerup.com, in that link i found this
![image](https://github.com/godotengine/godot/assets/127424589/c2f81dff-e48d-4525-8638-98c0ece418aa)

**Comment by Zireael07** [comment]
Can you actually run a Vulkan benchmark such as https://github.com/vkmark/vkmark ? I wouldn't trust Gpu-z to be an entirely accurate source, plus Vulkan support can be lower than what Godot needs?

**Comment by StreamVersus** [comment]
> Can you actually run a Vulkan benchmark such as https://github.com/vkmark/vkmark ? I wouldn't trust Gpu-z to be an entirely accurate source, plus Vulkan support can be lower than what Godot needs?

yeah, i can, but are there windows binaries, building will take forever?

**Comment by StreamVersus** [comment]
so this looks like my error, cause each benchmark just stops, without even saying something like: "your gpu doesnt support vulkan", just get error, probably driver issue

**Comment by StreamVersus** [comment]
so, after a lot of investigation i found a culprit of that.
I was using at some point program, called FPSMonitor.
It had implicit vulkan layer, which some how was able to break all of vulkan support on my pc, so there is no error in Godot
