### ISSUE TITLE
Normal buffer does not contain correct normals, doesn't match scene debug view

### ISSUE THREAD

**Issue by paperman5** [godotengine/godot#77710]
### Godot version

4.0.3.stable

### System information

Linux (Fedora 36), Intel i7-11700KF, AMD RX 6800XT

### Issue description

When using a screen-reading shader with the normal buffer, the normals sampled from the normal buffer are incorrect. However, the normals as displayed from the scene debug view are correct (3D editor view -> Display Advanced -> Normal Buffer). The image produced by the showing the normals as an image is noticeably lighter than the debug view.
Shader (added to a ShaderMaterial on a 2x size quad as shown in the docs):
```
shader_type spatial;
render_mode unshaded;

uniform sampler2D normal_texture : hint_normal_roughness_texture, repeat_disable, filter_nearest;

void vertex() {
	POSITION = vec4(VERTEX, 1.0);
}

void fragment() {
	ALBEDO = texture(normal_texture, SCREEN_UV).xyz;
}
```
Shader image result:
![shader_view](https://github.com/godotengine/godot/assets/22630098/8a7da59f-0745-41d0-ab54-c13004bef6e9)
Debug view image:
![debug_view](https://github.com/godotengine/godot/assets/22630098/96d4d7c4-fae4-42b2-9cb2-280a081f529d)

I have been able to alter the "lightness" of the shader image by changing the tonemapping settings in the WorldEnvironment, which I don't think should affect the image and is probably not intended.

Now that I think about it, this could be happening because the quad with the shader in front of the camera is being lit/affected by the WorldEnvironment or lights in the scene... Is there a way to get around this?

### Steps to reproduce

1. Set up screen-reading quad as shown in the docs ([here](https://docs.godotengine.org/en/stable/tutorials/shaders/advanced_postprocessing.html))
2. Add the shader to the quad
3. Toggle the "Normal Buffer" debug view in the 3D scene editor to see the difference

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
This is not a bug. If sampling the texture to be used as albedo, you must add `: hint_color` to the sampler2D uniform to perform sRGB conversion.

Do not use `hint_color` when using the normal buffer as normals though.
