### ISSUE TITLE
Extending a script does not update, sometimes.

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#77720]
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Windows 10 - Forward + - 2D

### Issue description

When making a class (class_name) and extending from that class, it can happen that when you add new things to said class, it does not update the functions and properties. Whenever you try to use them they will cause an error and godot will also stop the game when trying to call them, saying they don't exist. This is fixed by restarting the editor.

### Steps to reproduce

I am not 100% What causes this but what i have done is:

1. Create Script with class name "XYZ"
2. Create new Script extending from XYZ
3. Adding something new to class XYZ
4. Error

Does not happen every time but too often to be ignored.

### Minimal reproduction project

N/A

**Comment by Kosinsinus** [comment]
I wanted to add that i have tried several things to fix this issue by myself so i would not have to reload the entire engine but nothing has really worked. I tried closing and reopening, saving, changing the class name then back. Nothing has really helped. Only restarting.

**Comment by Chaosus** [comment]
I can confirm this happens often. Pretty sure it was already reported, though.

**Comment by Kosinsinus** [comment]
> I can confirm this happens often. Pretty sure it was already reported, though.

Alright thank you. I tried searching for a similar issue but didn't find anything that seemed similar so i just thought i'd open a new report. To be fair, i didn't search very hard lol

**Comment by erick22js** [comment]
The same happened to me, I did just extended the path to script instead, and worked nicely

**Comment by dalexeev** [comment]
* I can’t reproduce it in master, and also in 4.2.2 for inheritance.
* Fixed by #90601 or some earlier PR.
