### ISSUE TITLE
Code Completion for dictionaries doesn't work when the Value is an array

### ISSUE THREAD

**Issue by Drejzer** [godotengine/godot#77725]
### Godot version

4.0.2.stable

### System information

Manjaro Linux 5.15.113-1-MANJARO

### Issue description

When using a Dictionary which values' are arrays (at least empty ones) and keys are strings, code completion doesn't show u, while it does when the values are dictionaries.

This happened when I had the dictionary defined inside a function and tried accessing it in an inline lambda definition, but when testing, it also happened in

### Steps to reproduce

1) declare a dictionary with arrays as values `var dict1={"A":[],"B":[]}` or `var dict1={A=[],B=[]}` (EDIT: fixed the declaration here, happens regardless of the syntax) 
2) write `dict1.`
3) code completion doesn't show A, nor B

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Can you reproduce this in 3.5.2?

**Comment by Drejzer** [comment]
in 3.5.2.stable 
```
func test():
	var dict1={"A":1,"B":2}
	var dict2={A=1,B=2}
	var dict3={C={},D={}}
	var dict4={E=[],F=[]}
	var dict5={"C":{},"D":{}}
	var dict6={"E":[],"F":[]}
```
happens to dicts 3 - 6

**Comment by Drejzer** [comment]
Also, in 4.0.2, when the dictionary is declared outside the function, code completion wont show 
![image](https://github.com/godotengine/godot/assets/14893831/50b1d2b2-b951-4118-bbbe-3210c050d8e2)
![image](https://github.com/godotengine/godot/assets/14893831/df9e30f3-6c6a-4fba-afc9-ab5c2f21f8cd)

**Comment by HolonProduction** [comment]
> Also, in 4.0.2, when the dictionary is declared outside the function, code completion wont show

This is already tracked in #80145.

**Comment by Drejzer** [comment]
> > Also, in 4.0.2, when the dictionary is declared outside the function, code completion wont show
> 
> This is already tracked in #80145.

Considering the issue you mentioned it's from August and this one is from June... I had no way to know that at the time.

**Comment by HolonProduction** [comment]
Yeah. Wasn't meant in a bad way. Just wanted you to know.
