### ISSUE TITLE
variable is get_script() no longer works

### ISSUE THREAD

**Issue by Variable-ind** [godotengine/godot#77728]
### Godot version

4.0.3

### System information

Linux Mint 21.1 Cinnamon, Graphics: Intel Corporation HD Graphics 620, Processor: Intel© Core™ i5-7200U CPU @ 2.50GHz × 2

### Issue description

Hy, i am experiencing (which i think is the same issue as #39244)

e.g the code:
```swift
class_name GroupLayer
extends Node2D


func _ready() -> void:
	print(self is get_script())
```
In 4.0.3 gives an error `Cannot call on an expression. Use ".call()" if it's a Callable.`

While in 3.5.1 it prints out 
```swift
True
```
if error is intended then please tell me a 4.0.3 alternative of the code that will work like it did in 3.5.1

### Steps to reproduce

use ``` print(self is get_script()) ```

### Minimal reproduction project

[New Game Project.zip](https://github.com/godotengine/godot/files/11624956/New.Game.Project.zip)

**Comment by Variable-ind** [comment]
For reference the real code i plan to use is
```swift
for layer in children:
		if not layer.is_visible_in_hierarchy():
			continue
		# Checks if layer is GroupLayer, cannot define this due to cyclic reference error
		if layer is get_script():
			image.blend_rect(layer.blend_children(frame, origin), blend_rect, origin)
		else:  # do other things

```

**Comment by dalexeev** [comment]
Not a bug. Use `is_instance_of` instead of `is` if the type is not known at compile time. See #73489.

**Comment by Variable-ind** [comment]
Thanks

**Comment by dalexeev** [comment]
For reference, this has already been added to the documentation. Should we describe in more detail?

![](https://github.com/godotengine/godot/assets/47700418/40be9126-adb9-4ec0-bd8e-1306e121243a)
