### ISSUE TITLE
Spawning multiple Area2D's sometimes throws two errors.

### ISSUE THREAD

**Issue by VanDeiMin** [godotengine/godot#77732]
### Godot version

3.5.2

### System information

windows 10, intel core i7 mobile, gles2, nvidia quadro m1000m

### Issue description

When I add multiple Area2D to scene from time to time I experience massages:

    ERROR: Index p_index = 0 is out of bounds (shapes.size() = 0).
       at: set_shape_transform (servers/physics_2d/collision_object_2d_sw.cpp:70)
    ERROR: Index p_shape = 0 is out of bounds (area->get_shape_count() = 0).
       at: area_set_shape_disabled (servers/physics_2d/physics_2d_server_sw.cpp:361)

From one to eight usually three or four. They doesnt crash the game. CollisionShapes2D work as they supposed to do.

Moving  'call_deferred("add_child")' to the next frame by 'yield(get_tree(), "idle_frame")' makes the problem dissapear.

### Steps to reproduce

    func make_star()-> void:
	    stars: Array = [];
	    if (thread.is_alive() == false):
			thread = Thread.new();
			omd_idx = SWARM;
			var _st: int = thread.start(self, "instance_star", stars); 
	    return;

instancing is called only by thread and is wrapped by mutex:
   
    func instance_star( stars: Array)-> Array:

	    for i in range(0, 200):
		mutex.lock();
		var star_inst: Area2D = star.instance();
		mutex.unlock();
		stars.push_back(star_inst);
		continue;

    return stars;

then is returned to main thread:

    func _process(_delta:float)-> void: 
	    if (omd_idx != -1 and thread.is_active() == true and thread.is_alive() == false):
		swarm = thread.wait_to_finish();

		for i in range(0, swarm.size()):	 
			call_deferred("add_child", swarm[i]);
			continue;
		call_deferred("clear_swarm");
		omd_idx = -1;

	    return;

This from time to time throws error. 

Adding 'yield(get_tree(), "idle_frame")'  before calling call_deffered("add_child()" solves the issue.

    func _process(_delta:float)-> void: 
	    if (omd_idx != -1 and thread.is_active() == true and thread.is_alive() == false):
		swarm = thread.wait_to_finish();
            yield(get_tree(), "idle_frame");
		for i in range(0, swarm.size()):	 
			call_deferred("add_child", swarm[i]);
			continue;
		call_deferred("clear_swarm");
		omd_idx = -1;

	    return;

### Minimal reproduction project

"N/A"

**Comment by Calinou** [comment]
@VanDeiMin Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

(The code samples you've posted are a good start, but they don't run on their own without a scene structure.)

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
