### ISSUE TITLE
Why does it keep generating logs, and I haven't turned off the log generation button after looking for a long time. At the same time, I will generate even an empty project, I don't know if you have encountered it, but I am already very irritated about this problem, every time I run it, open ide, it will generate a damn log, and there is no option to close it.

### ISSUE THREAD

**Issue by droog126** [godotengine/godot#77738]
### Godot version

4.X

### System information

Window10

### Issue description

Why does it keep generating logs, and I haven't turned off the log generation button after looking for a long time. At the same time, I will generate even an empty project, I don't know if you have encountered it, but I am already very irritated about this problem, every time I run it, open ide, it will generate a damn log, and there is no option to close it.
![image](https://github.com/godotengine/godot/assets/59406205/d32c57c0-5ae2-4e54-8e9a-30e3e53f4d2f)
![image](https://github.com/godotengine/godot/assets/59406205/4d971767-4ac6-4796-bf85-d347a0c47b9b)

### Steps to reproduce

Why does it keep generating logs, and I haven't turned off the log generation button after looking for a long time. At the same time, I will generate even an empty project, I don't know if you have encountered it, but I am already very irritated about this problem, every time I run it, open ide, it will generate a damn log, and there is no option to close it.

### Minimal reproduction project

Why does it keep generating logs, and I haven't turned off the log generation button after looking for a long time. At the same time, I will generate even an empty project, I don't know if you have encountered it, but I am already very irritated about this problem, every time I run it, open ide, it will generate a damn log, and there is no option to close it.

**Comment by droog126** [comment]
I don't know how to reproduce, but it just happens all the time, no matter if I only switch to 3.5 without this problem, any version of 4.x has this problem. I found all the options and just can't turn off this damn log generation.

**Comment by AThousandShips** [comment]
Please don't write such an unhelpful title, and you can't just repeat the same thing over and over in the report, fill it in properly

This is not a help desk, this might be a bug, but it sounds like you are asking for advice, please ask in [the other community channels](https://godotengine.org/community) for that instead

**Comment by akien-mga** [comment]
Indeed, without following the issue template to properly describe a bug we could reproduce and fix, this isn't actionable.
