### ISSUE TITLE
Godot 4.1.dev4 gradient color picker regression

### ISSUE THREAD

**Issue by graydoubt** [godotengine/godot#77745]
### Godot version

4.1.dev4

### System information

Godot v4.1.dev4 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1070 Ti (NVIDIA; 31.0.15.3179) - Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 Threads)

### Issue description

When modifying any gradients in the property inspector, the color picker will close automatically when trying to adjust any values. It might also fail to open. Continued interaction will result in more inconsistent behavior.

This applies to editing any gradient property, for example Line2D.gradient or a GradientTexture1D or GradientTexture2D resource.

This issue does not occur in Godot 4.1.dev3.

### Steps to reproduce

Create a new scene with a Line2D node, set the gradient property to a new gradient, and try adjusting its colors.

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
Thanks for the report.

I haven't tested myself, but this sounds related to #71915, CC @MewPurPur.

**Comment by KoBeWi** [comment]
The problem comes from here:
https://github.com/godotengine/godot/blob/5b5186383ede61a9bcd30b2e20321ba93a2cbcaa/editor/plugins/gradient_editor.cpp#L102-L116
This method puts lots of properties into UndoRedo for no reason. Particularly, `set_interpolation_mode` causes the inspector to refresh.

Interestingly, blame does not point to #71915, but to some very old PRs 🤔

**Comment by KoBeWi** [comment]
Ok found it:

https://github.com/godotengine/godot/blob/5b5186383ede61a9bcd30b2e20321ba93a2cbcaa/scene/resources/gradient.cpp#L119

This line was actually added recently, in #76545
CC @JoNax97

**Comment by JoNax97** [comment]
I puta that line there so I could show/hide the new interpolation color mode depending on the value of interpolation mode. 
I'm not sure what side effects it has

**Comment by YuriSizov** [comment]
@JoNax97 The side effect of `notify_property_list_changed` is that the entire inspector is rebuild, so any open color picker popup is destroyed. Ideally, this method should not be called if the mode value doesn't change, but we can also add a check inside of the method itself to return early when the value supplied to it is the same as the stored one.

**Comment by JoNax97** [comment]
> Ideally, this method should not be called if the mode value doesn't change

Well, it's called from the setter of the property... Maybe for some reason the editor is setting all the properties of the gradient whenever a color is modified? 
I will investigate as soon as I can

**Comment by YuriSizov** [comment]
> Maybe for some reason the editor is setting all the properties of the gradient whenever a color is modified?

Yes, that's what I mean. Ideally, the caller somewhere else is doing something redundant, but it can be fixed on both sides. An internal check that returns early is a good practice in these kind of setters.

**Comment by MewPurPur** [comment]
Wha? But my PR isn't even merged
