### ISSUE TITLE
LightmapGI : Cannot reimport lightmaps' EXR files after baked lightmaps

### ISSUE THREAD

**Issue by gongpha** [godotengine/godot#77746]
### Godot version

v4.1.dev.custom_build [2e273f0e35800f2bcc7c05db54100caa97928f69]

### System information

Windows 11 x64, Vulkan (Forward+), NVIDIA GeForce GTX 1650

### Issue description

Importing EXR files from baking lightmaps will always fail. But the files aren't corrupted and can be opened in other software like Krita.

### Steps to reproduce

Do these in the MRP

1. Find `lm` node in the scene `000.tscn`, And press `Bake Lightmaps`
2. After finished baking, The lightmaps should be rendering normally and several error messages will be printed out. They say :
- Invalid/Corrupted data found when decoding pixels.
- Error loading image: res://000.exr
- Error importing 'res://000.exr'.

3. When trying to reopen `000.tscn`, The lightmaps won't render in the scene anymore.

( Optional )

4. If trying to put the lightmap data `000.lmbake` into the `lm` node. It will spam these out :
- Uniforms were never supplied for set (1) at the time of drawing, which are required by the pipeline
- Texture (binding: 7) is an array of (8) textures, so it should be provided equal number of texture IDs to satisfy it (IDs provided: 7).

Then all the meshes go black immediately.

### Minimal reproduction project

[i_5222a99f5_001.zip](https://github.com/godotengine/godot/files/11629095/i_5222a99f5_001.zip)

**Comment by bitsawer** [comment]
Can confirm. I think I noticed this same when trying to import the third-person-shooter demo data in the latest master branch. Looks like this might be a regression, some earlier version like 4.0.2 might still work: https://github.com/godotengine/godot/pull/76348#issuecomment-1520723717. So if you created data using an earlier Godot version, it might work. But deleting old, working data and re-importing or generating it might create broken data.

**Comment by bitsawer** [comment]
Reverting https://github.com/godotengine/godot/pull/77335 fixes the .exr loading and loading the baked image works again, looks like something is incompatible with the newer tinyexr.

**Comment by gongpha** [comment]
After my little investigation, I found that the problem is only reading. I tried baking in Godot with tinyexr 1.0.2 (the problematic version), Then opened it in older Godot with tinyexr 1.0.1 and it worked. But not vice-versa.

**Comment by gongpha** [comment]
Looks like this regression has been solved by a new version of tinyexr (1.0.3, and 1.0.4, released a few minutes after I wrote this comment).

Now, Only need a new PR for this patch.

**Comment by bitsawer** [comment]
I can do the PR tomorrow, I already have the patch ready while debugging https://github.com/syoyo/tinyexr/issues/194. I want to test a few more projects I remember having similar issues, just in case.
