### ISSUE TITLE
[4.1 dev 4] UI cannot interact if 2DSprite is on top of it 

### ISSUE THREAD

**Issue by dqdthanhthanh** [godotengine/godot#77758]
### Godot version

4.1 dev 4

### System information

MacOs 13.3.1

### Issue description

UI cannot interact if 2DSprite is on top of it. Ex: click button not work.
I have an effect that is click effect, when the mouse is clicked, the sprite will appear rotates and then disappears.
However it doesn't work on dev4 because the sprite effect is on top of the UI. 
Everything is fine on dev3.
How to make the sprite not affect the interaction with the UI ? I have not found any option.

### Steps to reproduce

Open Minimal reproduction project. Run control screen. Then click button.

### Minimal reproduction project

[TestProject.zip](https://github.com/godotengine/godot/files/11631126/TestProject.zip)

**Comment by AThousandShips** [comment]
Have you read [this](https://docs.godotengine.org/en/stable/tutorials/inputs/inputevent.html)?

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/77773.

**Comment by akien-mga** [comment]
I tested myself, could reproduce the regression in 4.1-dev4, and it seems fixed in `master`.

Thanks for the report!
