### ISSUE TITLE
Container sort_children oneshot connection removed

### ISSUE THREAD

**Issue by jandrewlong** [godotengine/godot#7776]
_bugsquad edit: still reproductible in 3.0.x master (https://github.com/godotengine/godot/commit/a7f6e093d84189f3da0d52cd095107be6bab5485) 3.0 sample project here: https://github.com/godotengine/godot/issues/7776#issuecomment-380193287_

------

**Operating system or device - Godot version:**

Gentoo Linux, Godot 2.1.2
~~(I've not tested other OSs, I'll check windows later this afternoon)~~
Also, Windows 10, Godot on Steam

**Issue description:**

Opening a scene in the editor with a Container with the "sort_children" signal having a oneshot connection removes the connection.

**Steps to reproduce:**

1. Create a new scene
2. Add a Container node (or node that inherits Container)
3. Add a script
4. Connect the "sort_children" signal as a oneshot to a function in the script
5. Save the scene
6. Close the scene
7. Open the scene

The connection is now gone.

**Link to minimal example project:**

[testoneshot.zip](https://github.com/godotengine/godot/files/767524/testoneshot.zip)

This example project has the container connected to the script (you can verify by checking the .tscn file), when opened in the editor, the connection disappears.

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by jandrewlong** [comment]
Tested on the current master (a7f6e09), this is still reproducible.

Minor change, when opening the scene, the connection remains, but clicking on the container causes it to be removed.

Attached is new example project (the initial report project was built in Godot 2)

[sortchild.zip](https://github.com/godotengine/godot/files/1895784/sortchild.zip)

**Comment by kubecz3k** [comment]
@jandrewlong thank you for checking this

**Comment by akien-mga** [comment]
Cherry-picked for 3.0.7.
