### ISSUE TITLE
Line Numbers in Editor move when adding new digit positions (going from 9 to 10 lines of code or 99 to 100)

### ISSUE THREAD

**Issue by strangebirds** [godotengine/godot#77786]
### Godot version

4.0.2 stable

### System information

MacOS 12.6.6 (21G646) - Mac Studio M1 Max

### Issue description

In the GDScript editor the line numbers jump when adding a new digit position: i.e. when adding another line brings the line number from a single digit to two digits or from two to three digits. 9 to 10 or 99 to 100.

I'll be honest, I didn't test 999 to 1000 or higher

This is disconcerting to the user as they are often focused on the code and the movement looks like an error appearing in the editor margin or text changing.

Expected behavior: the line numbers will not shift to accommodate more digits. The Controls for the editor window/view should be rendered with sufficient space for more digits (maybe four? 9999 lines of code seems unwieldy enough to be an upper limit)

### Steps to reproduce

1. Start writing a new blank script
2. Exceed single digit numbers for the number of lines
3. Watch the line numbers jump to the right.
4. The line number movement can also be seen when removing a line takes it to a lower number of displayed digits: deleting line 10 causes all remaining line numbers (1-9) to shift left.

optional
5. For larger line numbers create several blank lines of code and copy & paste them to hit the desired number.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Remember that the line numbers also share space with the gutters, for bookmarks and breakpoints etc., this area shouldn't become to big with a lot of empty space

**Comment by AThousandShips** [comment]
My suggestion would be to open up a [proposal](https://github.com/godotengine/godot-proposals) as this isn't a bug, and is pretty common across IDEs unless I'm completely wrong, the default behaviour should imo not be to have excessive unused space, but a setting for this could be a new feature

**Comment by strangebirds** [comment]
That's a good idea - thanks for the suggestion. I'm going to close this ticket and open a proposal.
