### ISSUE TITLE
Bookmarks don't draw

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#77783]
### Godot version

4.1 dev4

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

https://github.com/godotengine/godot/assets/2223172/fe382ae2-04bb-4efa-b666-9e94ebb56a9c

### Steps to reproduce

1​. Go to Script Editor
2​. Toggle bookmark (Go To -> Toggle Bookmark)
3[.](https://media.tenor.com/_BiwWBWhYucAAAAd/what-huh.gif) It's not visible

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
From #66763 or unrelated?

**Comment by KoBeWi** [comment]
🤦‍♂️
Bookmarks don't draw by default and that PR removed a code that enables the gutter.

**Comment by AThousandShips** [comment]
That's what I assumed, was trying to dig into if it was by default
