### ISSUE TITLE
Collision exception and node freeing error in Godot 4.0.3

### ISSUE THREAD

**Issue by 3216717062** [godotengine/godot#77793]
### Godot version

4.0.3

### System information

Win10

### Issue description

I encountered a bug in Godot 4.0.3 when I tried to add a collision exception and free a character body 2D node. The code is as follows:

```gdscript
func _ready():
    character_body_2d.add_collision_exception_with(character_body_2d_2)
    character_body_2d_2.queue_free()
# Called every frame. "delta" is the elapsed time since the previous frame.
func _process(delta):
    character_body_2d.get_collision_exceptions()
```

> The error message is:

```text
ERROR: Condition "!body" is true. Returned: ObjectID()
   at: body_get_object_instance_id (servers/physics_2d/godot_physics_server_2d.cpp:690)
```

> I think this is a bug because the documentation says that `add_collision_exception_with` should prevent collisions between two bodies, and `queue_free` should defer the deletion of a node until it is safe. However, it seems that the node is freed before the collision exception is applied, causing an error when calling `get_collision_exceptions`. Can anyone confirm this issue and provide a workaround? Thank you.

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by RedworkDE** [comment]
`queue_free` isn't magic, the mentioned safety doesn't mean that the deletion may be deferred until the node is no longer needed.
On the next frame the node will be gone and `get_collision_exceptions` can no longer return it causing the error.
