### ISSUE TITLE
C#: GD0001 - invalid partial class error of 'Godot.GodotObject'

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#77792]
### Godot version

v4.0.3.stable.mono.official [5222a99f5]

### System information

Windows 10, MacOS

### Issue description

Inherit from a Godot class ends up in compile error.

`Missing partial modifier on declaration of type 'Test.Foo' which is a subclass of 'Godot.GodotObject'`
`Missing partial modifier on declaration of type 'Bar' which is a subclass of 'Godot.GodotObject' `

The class is not partial.

### Steps to reproduce

```
using Godot;

partial class Test
{
    class Foo : GodotObject { }

}

class Bar : GodotObject { }
```

### Minimal reproduction project

N/A

**Comment by raulsntos** [comment]
This is not a bug, every C# class that inherits from a Godot class needs to be partial. So, as the error says, you have to add the `partial` modifier to your classes.

The reason why classes need to be partial in 4.x is that we use source generators. You can read more about this in the [_What's new in C# for Godot 4.0_](https://godotengine.org/article/whats-new-in-csharp-for-godot-4-0/#engine-interop-with-source-generators) article.

**Comment by MikeSchulze** [comment]
Thanks for the link, i have to read the documentation
