### ISSUE TITLE
`NavigationMesh` does not complete when running on main thread

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#77801]
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Mac

### Issue description

The following code will not print any vertices, nor polygons. 
The `NavigationMesh` resource will not be saved correctly.

Even though we specify `bake_navigation_mesh(false)` (on the main thread)

```gdscript
func _ready() -> void:
	var navreg = $NavigationRegion3D
	navreg.bake_navigation_mesh(false)
	
	print(navreg.navmesh.get_vertices())
	print(navreg.navmesh.get_polygon_count())

	var to_save = preload("res://testresource.gd").new(navreg.navmesh)
	ResourceSaver.save(
		to_save,
		"output.tres",
		ResourceSaver.SaverFlags.FLAG_BUNDLE_RESOURCES
	)
```

### Steps to reproduce

1. Download minimal repo below
2. Run the repo
3. Check the console
4. Check `output.tres`

<img width="316" alt="Screenshot 2023-06-03 at 19 05 22" src="https://github.com/godotengine/godot/assets/100964/83ea661d-1c5a-4044-b9cc-2a5434a89280">

<img width="1028" alt="Screenshot 2023-06-03 at 19 05 34" src="https://github.com/godotengine/godot/assets/100964/cb099d0c-f626-48a4-b4f4-9a57b7988df1">

### Minimal reproduction project

[test-navmesh.zip](https://github.com/godotengine/godot/files/11642578/test-navmesh.zip)

**Comment by tavurth** [comment]
Modifying the code thusly:

```gdscript
	navreg.bake_navigation_mesh(false)
	await get_tree().process_frame
```

And I see the following output as expected:

```log
[(0.5, 0.625, -1.25), (-0.25, 0.625, -1.5), (-0.5, 0.625, -1), (-0.5, 0.625, 0), (0.5, 0.625, 0.25)]
3
```

<img width="1438" alt="Screenshot 2023-06-03 at 19 08 18" src="https://github.com/godotengine/godot/assets/100964/ea4c288c-14e2-4e8c-b2a0-4bc9541bc2bc">

**Comment by smix8** [comment]
`NavigationRegion3D.bake_navigation_mesh()` makes a deferred call to always finish on the main thread no matter what.

With the new thread-guards added in Godot 4 dev3 this is now more important than ever.
