### ISSUE TITLE
About the Chinese adaptation problem

### ISSUE THREAD

**Issue by Az-qianchen** [godotengine/godot#77809]
### Godot version

4.3

### System information

Win 10 Vulkan API 1.3.236 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1660

### Issue description

Scene nodes can not be typed in Chinese when changing a noun
but , can use Chinese names by copying them

and

Use remote debug in the browser to run in Chinese garbled. The number can be displayed normally
Running a project directly in Godot does not have this problem. 
Here is a comparison picture
![tmpB9B2](https://github.com/godotengine/godot/assets/52212525/f8932cef-9076-4e5a-921a-fd8505eeb5cc)
![tmpBDBA](https://github.com/godotengine/godot/assets/52212525/f4aa9449-012e-4149-a0f0-8ca1fd037545)

### Steps to reproduce

Use remote debug in the browser to run

### Minimal reproduction project

[Minimal reproduction project.zip](https://github.com/godotengine/godot/files/11643134/Minimal.reproduction.project.zip)

**Comment by bruvzg** [comment]
Your project does not include any fonts, default project font only support Latin/Greek/Cyrillic characters. On Windows, system fonts are used as fallback, but Web export does not support loading system fonts.

**Comment by Calinou** [comment]
Closing per @bruvzg's comment. This is now documented in the [Using fonts](https://docs.godotengine.org/en/latest/tutorials/ui/gui_using_fonts.html) documentation since https://github.com/godotengine/godot-docs/pull/7481 was merged.
