### ISSUE TITLE
CharacterBody2D constantly jumps when moving

### ISSUE THREAD

**Issue by hydroper** [godotengine/godot#77816]
### Godot version

4.0.3.stable.mono

### System information

Windows 11, gl_compatibility

### Issue description

A `CharacterBody2D` in an empty scene keeps constantly jumping during its movement. I tried both `MoveAndCollide()` and `MoveAndSlide()` in high velocity (`212, 212`).

```c#
// Called every frame. 'delta' is the elapsed time since the previous frame.
public override void _Process(double delta)
{
    this.MainPlayerEntity.MoveAndCollide(new Vector2(2f, 2f));
}
```

![Constant jumps](https://i.stack.imgur.com/vvztw.gif)

Note the GIF recorder is a bit laggy here, so it's a bit inaccurate.

### Steps to reproduce

1. Create a simple project with a empty 2D scene
2. Attach a `CharacterBody2D` with some bitmap or graphics inside
3. Move the `CharacterBody2D` within `_Process` in the root 2D scene.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Please read the [documentation](https://docs.godotengine.org/en/stable/classes/class_physicsbody2d.html#class-physicsbody2d), you need to use `delta`

For support questions and help please first turn to the other [community channels](https://godotengine.org/community), this is for bug reporting, not a help desk.
