### ISSUE TITLE
The 'get_multiplayer' method cannot obtain the value obtained by the 'set_multiplayer' method

### ISSUE THREAD

**Issue by mao437303994** [godotengine/godot#77817]
### Godot version

4.1.dev

### System information

Window 10

### Issue description

If the result is what you expect, why not block it when you set the value, the value is successfully set in the Map, but when you get it, it's not what you expect, and you make mistakes.
![微信图片编辑_20230604044018](https://github.com/godotengine/godot/assets/28644312/3f525466-0d6c-4eb4-8fef-45072ebad798)

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Please provide an MRP to indicate what specific steps you are doing, or at minimum an actual description of what you are doing

The titles on the form are not optional, you have to fill them in

**Comment by mao437303994** [comment]
> Please provide an MRP to indicate what specific steps you are doing, or at minimum an actual description of what you are doing, without that not only are we unable to tell what's wrong, we also can't tell if you're doing something wrong
> 
> The titles on the form are not optional, you have to fill them in

I have set up a custom "Multiplayer API" on scenario A, and also set up a custom "Multiplayer API" on its sub scenario B. However, sub scenario B cannot obtain its own "Multiplayer API", and only obtains scenario A's "Multiplayer API".  If I am not allowed to set up a "Multiplayer API" on sub scenario B, why not prevent it.  I hope to obtain my own "Multiplayer API" for sub scenes.

**Comment by AThousandShips** [comment]
Please attach an MRP with your script and scene

> small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the .godot folder in the archive (but keep project.godot).
Required, unless the reproduction steps are trivial and don't require any project files to be followed. In this case, write "N/A" in the field.

**Comment by mao437303994** [comment]
> Please attach an MRP with your script and scene
> 
> > small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the .godot folder in the archive (but keep project.godot).
> > Required, unless the reproduction steps are trivial and don't require any project files to be followed. In this case, write "N/A" in the field.

https://github.com/mao437303994/test_godot.git

**Comment by AThousandShips** [comment]
I think I know what might be causing this, will take a look when I have time

**Comment by AThousandShips** [comment]
Got a fix working, will open a PR soon

**Comment by mao437303994** [comment]
> Got a fix working, PR is open

If the name of a node changes, the result obtained by "get_multilayer" is also incorrect because the map still stores the previous NodePath

**Comment by AThousandShips** [comment]
It does? It worked right for me, which result?

**Comment by AThousandShips** [comment]
My results, the correct and expected result:
```
NodePath: /root/Main
Before update: <SceneMultiplayer#-9223372010682317685>
Exclusive: <SceneMultiplayer#-9223372009692461929>
After update: <SceneMultiplayer#-9223372009692461929>

NodePath: /root/Main/Test
Before update: <SceneMultiplayer#-9223372009692461929>
Exclusive: <SceneMultiplayer#-9223372007947631418>
After update: <SceneMultiplayer#-9223372007947631418>
```

**Comment by AThousandShips** [comment]
> If the name of a node changes, the result obtained by "get_multilayer" is also incorrect because the map still stores the previous NodePath

Oh my bad, that's not covered here nor is it supported atm, not in the bounds of this PR, open a separate issue please

**Comment by mao437303994** [comment]
> g.

"set_name" changes the name of node Test, and getting the result should not be correct

**Comment by mao437303994** [comment]
> > If the name of a node changes, the result obtained by "get_multilayer" is also incorrect because the map still stores the previous NodePath
> 
> Oh my bad, that's not covered here nor is it supported atm, not in the bounds of this PR, open a separate issue please

My SDK of Godot is still old and has bugs that make it difficult to demonstrate

**Comment by AThousandShips** [comment]
Yes, and I understand you expect it to work this way, but it unfortunately does not, please open an issue for that specifically as it is not within the bounds of the report in this, you don't mention it, and this is about a specific thing

**Comment by AThousandShips** [comment]
Update:
This is not a bug, see #77829 for explanation, but the PR now fixes the incorrect assignments that cause this confusion
