### ISSUE TITLE
Selected word's duplicates highlight is very hard to see

### ISSUE THREAD

**Issue by blackears** [godotengine/godot#77812]
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Windows 10, Compatability

### Issue description

I think it would be a good idea to change the default settings for how the highlighting for duplicates of the selected word is handled by the editor. In the current editor, this setting is so close to the default background that it is nearly invisible. (See the second occurrence of to_plane in the attached image).

Being able to highlight a particular word and then scrolling through your code to find any duplicates is a very helpful thing to do when debugging and it's not practical to do with the current default settings.

![image](https://github.com/godotengine/godot/assets/6724608/fdf6709f-8d14-4eab-949e-062eee4436c1)

### Steps to reproduce

Create a new script file.  
Write some code where the same variable is used on more than one line.
Double click on one instance of the variable name to highlight it.
Observe the color of the highlight around other occurrences of the same name.

### Minimal reproduction project

N/A

**Comment by blackears** [comment]
https://github.com/godotengine/godot-proposals/discussions/7012#discussioncomment-6079604

**Comment by Lielay9** [comment]
The color is driven by `text_editor/theme/highlighting/word_highlighted_color`. (The currently selected text will be also be mixed with `text_editor/theme/highlighting/selection_color`)

![kuva](https://github.com/godotengine/godot/assets/40064911/2a962dfd-8043-419f-8537-b0c8bc94ab0c)

For clearer results, you can try increasing the alpha of `word_highlighted_color`( and decrease the alpha of `selection_color` to compensate the increased brightness.) These changes could also be made to the default theme.

Personally, I rely on this feature so often that I'd wish there was an option to underline and/or have borders like in `text_editor/theme/highlighting/search_result_border_color`.

Search results border:

![kuva](https://github.com/godotengine/godot/assets/40064911/62c4a40c-470f-47e4-8d94-10a0701248db)

**Comment by Calinou** [comment]
I wouldn't make word highlight color too similar to selection color, as it then becomes an accessibility issue in the other direction.

For reference, VS Code uses different colors for selection and word highlight (selection is on the left):

![image](https://github.com/godotengine/godot/assets/180032/74e7f078-1c8e-404e-88bc-c4c17c954ee9)

**Comment by Lielay9** [comment]
> I wouldn't make word highlight color too similar to selection color by increasing this opacity a lot, as it then becomes an accessibility issue in the other direction.

Ideally the selection color should be applied on top of the highlighted color (or not have selection highlighted). That way both colors could be made distinct without  hurting the readability of the other.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/7785.
