### ISSUE TITLE
4.1 SubViewport.size is always (2, 2)?

### ISSUE THREAD

**Issue by rakkarage** [godotengine/godot#77815]
### Godot version

v4.1.dev.custom_build [543750a1b]

### System information

Windows 11, Core i5-12400F, RX 6600

### Issue description

	extends SubViewport

	func _ready():
		print(size)

- in 4.0.3- this prints the resolution of the window `(1152, 648)`
- in 4.1 this prints `(2, 2)`

Thanks.

### Steps to reproduce

- new `Control` scene
  - add `SubViewportContainer` child
    - set `Anchor` to `Full Rect`
    - turn `Stretch` on
    - add `SubViewport` child
      - add `Camera2D` child
          - set `Anchor Mode` to `Fixed Top Left`
      - attach script that prints `size`

### Minimal reproduction project

https://github.com/rakkarage/TestSubViewportSize

**Comment by AThousandShips** [comment]
Is this restricted to the first frame, does it happen if you reload the scene? Could be a limitation on showing for the first time

**Comment by Sauermann** [comment]
Please try as workaround:

``` GDSCRIPT
extends SubViewport

func _ready():
	call_deferred("print_size")


func print_size():
	print(size)
```

**Comment by rakkarage** [comment]
Ya that fixes it. thanks. :)

**Comment by AThousandShips** [comment]
An investigation and possibly documenting that it might not be available immediately, this is probably due to the shaping of the container, which isn't available immediately afik

**Comment by Rindbee** [comment]
A regression from #77651.

Previously, `_size_changed()` was called during `NOTIFICATION_VISIBILITY_CHANGED`. Only necessary for the first display, more like a call is needed after entering the tree when it's shown:
https://github.com/godotengine/godot/blob/543750a1b3f5696f9ba8e91cb49dc7db05d2ae62/scene/main/canvas_item.cpp#L328
Seems unnecessary to call every time the control is shown.

`Control::_notification(NOTIFICATION_ENTER_TREE)` will be called after `CanvasItem::_notification(NOTIFICATION_ENTER_TREE)`. `_size_changed()` can be called there (if it's necessary) and the visibility is already determined.
