### ISSUE TITLE
Initial window focus state is incorrect, `has_focus()` returns `false` when it should return `true`

### ISSUE THREAD

**Issue by Zentrophy** [godotengine/godot#77824]
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Windows 11, AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx     2.10 GHz

### Issue description

  The "focus" of a window through get_window ().has_focus () reports false for a window initially even though it is obviously true.  It doesn't get corrected until something else gets the "focus" and it receives a WM_SETFOCUS again.  This is the case for the Editor window when running a plug-in aswell.

  It looks like the internal "focus" state flag is being reset after the initial WM_SETFOCUS has occurred for a window.

### Steps to reproduce

  Run the MRP and you'll see that "false" is printed in the title-bar of the window when it should be "true".

### Minimal reproduction project

[MRP_Focus.zip](https://github.com/godotengine/godot/files/11644644/MRP_Focus.zip)

**Comment by Calinou** [comment]
cc @Rindbee @winston-yallow @Sauermann

**Comment by Rindbee** [comment]
It cannot be reproduced on Linux Mint 21.1 (Cinnamon 5.6.8/i3wm) if you just press F5/F6 to run.

After running, before the window is displayed normally (during the black screen), if other programs get the focus (clicked on other applications including editor), it will first output false. This does not seem to be a bug.

**Comment by Zentrophy** [comment]
If the window has the focus and input is directed to the window and it is reporting that it doesn't have the focus, then that is a bug.

**Comment by Rindbee** [comment]
This seems to be a Windows platform specific issue, I was able to reproduce the issue on Win10.
