### ISSUE TITLE
[3.5] Assets can import fine, but will crash godot when zipped.

### ISSUE THREAD

**Issue by Michaelwhite34** [godotengine/godot#77828]
### Godot version

v3.5.3.0.rc.custom_build[338114d47]

### System information

windows 11 pro, ver 10.0.22621 Build 22621

### Issue description

[export.zip](https://github.com/godotengine/godot/files/11644875/export.zip)
The folder can be imported without problem, but will crash godot once zipped.

### Steps to reproduce

It's compiled with https://github.com/funexpected/godot-flash-module.  Just create an empty project and import the zip file, it crashes.

### Minimal reproduction project

[proj.zip](https://github.com/godotengine/godot/files/11644908/proj.zip)

**Comment by Michaelwhite34** [comment]
https://drive.google.com/file/d/1hDim51mCZuW-2JGfq6R0ok4MFeIf0N3n/view?usp=sharing This is compiled godot file.

**Comment by AThousandShips** [comment]
Can you replicate this without the module?

**Comment by Michaelwhite34** [comment]
> Can you replicate this without the module? We do not support third party modules and if the error does not occur without the module it's likely not a fault in the engine, and should be reported to the developers of the module
> 
> The module seems to use zip files, so the cause is most likely the module

Solved, the module uses a zip format that's different from 7-zip or bandizip.

**Comment by AThousandShips** [comment]
In the future, please don't make issue reports over a module here but on the module itself, we have no ability to fix a third party module
