### ISSUE TITLE
Parallax background Ignore Camera Zoom doesn't work if the ParallaxLayer's motion_offset is modified from script.

### ISSUE THREAD

**Issue by jasonkclee** [godotengine/godot#77827]
### Godot version

v4.0.3.stable.mono.official [5222a99f5]

### System information

Windows 10

### Issue description

Parallax background Ignore Camera Zoom doesn't work if the ParallaxLayer's motion_offset is modified from script.

If camera zoom is (2,2), that layer would be zoomed in, even though it shouldn't be.

I'm guessing ParallaxBackground::get_scroll_scale needs to account for ignore_camera_zoom and return 1 (like it does in _update_scroll)? This gets used by ParallaxLayer::set_motion_offset.

### Steps to reproduce

Have camera at some zoom (ex. 2), ParallaxBackground with IgnoreCameraZoom=True. Add below script to a ParallaxLayer.

func _process(delta):
	self.motion_offset.x -= 1

### Minimal reproduction project

NA

**Comment by leo1mml** [comment]
I have something similar happening in my project. Setting the ignores camera zoom doesn't prevent the layer from being misplaced.
