### ISSUE TITLE
bad highDpi support with plugins

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#7783]
**Operating system or device - Godot version:**
macOS
2.1

**Issue description:**

when using plugins highDpi has issues. the UI elements themselves are scaled correctly, but the spacing/layout is the same than in loDpi which results in overlapping.

Also icons are loDpi.

**Steps to reproduce:**
create a project
install a plugins (I used the git plugin)
set the editor to highDpi
open the git panel

<img width="991" alt="screen shot 2017-02-11 at 14 45 49" src="https://cloud.githubusercontent.com/assets/16718859/22853839/d635dfb4-f068-11e6-9389-8718b24a62e2.png">

**Comment by bojidar-bg** [comment]
This should be opened on respective issues themselves -- we shouldn't support badly-written code with hardcoded values just because it is "plugins".

**Comment by bojidar-bg** [comment]
(Actually, I'm not sure about the icons, but if the plugin creator confirms that it is hard-to-impossible to make those scale right, I can reopen it for them specifically)
