### ISSUE TITLE
"This directory already contains a Godot project" when inputting a valid path without trailing /

### ISSUE THREAD

**Issue by idbrii** [godotengine/godot#77831]
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Windows 10

### Issue description

Inputting a project path without a trailing / results in a warning:

> This directory already contains a Godot project

![image](https://github.com/godotengine/godot/assets/43559/536fd129-cb2c-4739-ab74-d379afb99034)

It's not obvious that you need to add a trailing slash to fix.

Godot detected there's a project in this folder, so could it add the trailing slash for me? or accept paths without it?

### Steps to reproduce

1. Open Godot
2. Click Import
3. Type path to existing project. When you've typed the path (but without the trailing `/`), you'll see the error.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
The error message is unclear, but isn't due to the missing slash, but an incorrect check, will make a fix

**Comment by idbrii** [comment]
Oh, I see the slash wasn't required for another project. I guess it's actually because the path ends with "zip". Thanks for figuring that out!
