### ISSUE TITLE
Tween.kill() is not instant.

### ISSUE THREAD

**Issue by darthLeviN** [godotengine/godot#77841]
### Godot version

4.0.2

### System information

Ubuntu 22

### Issue description

Tween.kill() is not instant.
It also leads to an error that says 
```
E 0:00:00:0256   Control.gd:23 @ _ready(): Can't append to a Tween that has started. Use stop() first.
  <C++ Error>    Condition "started" is true. Returning: nullptr
  <C++ Source>   scene/animation/tween.cpp:100 @ tween_property()
  <Stack Trace>  Control.gd:23 @ _ready()
```

### Steps to reproduce

kill a tween in the same frame you use it to tween stuff.

### Minimal reproduction project

[tween_problem_1.zip](https://github.com/godotengine/godot/files/11646200/tween_problem_1.zip)

**Comment by AThousandShips** [comment]
This has nothing to do with `kill` though does it? The error occurs *before* `kill` is called, and regardless if it is

**Comment by darthLeviN** [comment]
my mistake
