### ISSUE TITLE
Dragging any item over viewport and then off throws error

### ISSUE THREAD

**Issue by markdibarry** [godotengine/godot#77845]
### Godot version

4.0.dev (543750a1b3)

### System information

Windows 10

### Issue description

When dragging any item over the viewport and then off, the console shows this error:
![image](https://github.com/godotengine/godot/assets/21325943/92157452-d196-44f1-8d4b-a212cb870c3c)

### Steps to reproduce

Create a new project.
Drag the godot icon over the viewport and then off.

### Minimal reproduction project

N/A

**Comment by capnm** [comment]
Also (+ crash)  described here https://github.com/godotengine/godot/issues/77742
