### ISSUE TITLE
Image class has its edge pixel data distorted in a similiar way that "texture_repeat" changes higher level textures with no way to disable it

### ISSUE THREAD

**Issue by themotleyprogrammer** [godotengine/godot#77847]
### Godot version

4.0.3.stable

### System information

Windows 10 - v4.0.3.stable - Vulkan (Forward+)

### Issue description

When using Image.get_region(Rect2i) to return a certain region of an Image, and using that image data to construct a HeightMapShape3D collision shape, there is a glitch with the borders equivalent to setting"texture_repeat" to true on a StandardMaterial3D. However, there is no method or parameter to change on the Image class to disable this "texture repeat" artifact.

In the screenshot below, you can see that along chunk borders, the seam vertices of the collision shape are elevated far above the surrounding heightmap. This is because, in the Image data itself, there are problematic lighter colored pixels on the image border, resulting in the verts being placed higher than they should and breaking otherwise seamless chunks. This same issue occurred when I was creating the heightmap mesh vertex shader (visual shader). However, in that case, I was able to disable "texture_repeat" on the TextureParameter2D to fix the problem.

![chunk_border_seams](https://github.com/godotengine/godot/assets/83049250/9284721a-f4b1-44db-8931-7a000903152e)

I don't know why "texture_repeat" is enabled by default for pixel data in the Image class (if that is actually what's happening) but I have not found a method to disable it. I need the pure pixel data, which because the Image is taken as a region of another Image, I know for certain is seamless. I've tried resizing, cropping, etc. and found no way to get rid of those incorrect edge pixels.

### Steps to reproduce

```

var new_image = Image.get_region(Rect2i)

```

Constructing a new image from scratch or from texture will have these "bugged" edge pixels inside its Image.get_data() by default, whether it is constructed through Image.get_region() or Image.new()

### Minimal reproduction project

The project below is an example I threw together to try and visually demonstrate the issue.

Plane1 has the original Texture2D image as an albedo. (you can toggle texture_repeat to see the seam disappear)
Plane2 has an ImageTexture as albedo. You can disable texture_repeat on Plane2 as well, but that is through an option on StandardMaterial3D. There is no way to do it with the raw Image data created from get_region(), which is where the issue lies.

[ImageGetRect_BugExample.zip](https://github.com/godotengine/godot/files/11646462/ImageGetRect_BugExample.zip)

**Comment by AThousandShips** [comment]
Can you actually verify that this is from the image function and not something else? Because there's really not anything in the code that does this from what I can see

**Comment by AThousandShips** [comment]
Your MRP doesn't actually describe the issue you are describing, turning repeat off does make the effect go away, please add an MRP showing the effect you are talking about, concerning the `get_data`

**Comment by themotleyprogrammer** [comment]
> Your MRP doesn't actually describe the issue you are describing, turning repeat off does make the effect go away, please add an MRP showing the effect you are talking about, concerning the `get_data`, and so we can see that this isn't caused by some other issue or error in setting it up

 I will try and reproduce MRP with the collision shape generation code I'm currently using. In the meantime I'll share the collision shape generation function.

> How are you identifying this edge issue in the data?

I've encountered the same problem when making the heightmap vertex shader. I set the albedo texture to the same texture used to create the vertex offsets, (both used the same Image resource). Visually describing the resulting heightmap mesh; peaks were white and pits were black. Ratio is 1 pixel = 1 meter. Pixels and vertices lined up as expected. The unwanted artifacts around the edges were white, and peaked unnaturally just as the shader should have deformed them based off pixel color.

> Does this go away for you if you disable mipmaps in import?
You should be able to use `get_mipmap_offset(1)` to get the end of the raw data (I haven't tested that it gives the right offset, but it should I believe), or just use `clear_mipmaps`, or just not generate them in the first place

I import the original texture as an Image. There are no import options, however I make sure to clear_mipmaps() anyways in the code before accessing get_data()


Collision Generation Function:
```
func _generate_collision():
	
	#>  chunk_size = 128    (128x128 = Size of Chunk Heightmap Image
	#>  map_size = 1024     (1024x1024 = Size of Base Heightmap Image)
	
	
	ref_terrain_mesh.hide()
	var heightmap_img : Image = chunk_heightmap_img
	
	heightmap_img.decompress()
	heightmap_img.normal_map_to_xy()
	heightmap_img.convert(Image.FORMAT_RF)
	heightmap_img.clear_mipmaps()
	heightmap_img.resize(chunk_size+1, chunk_size+1)
	heightmap_img.clear_mipmaps()
	
	var data = heightmap_img.get_data().to_float32_array()
	for i in range(0, data.size()):
		data[i] *= heightmap_scale
		#data[i] -= heightmap_scale * 0.00001
	
	var ncs_hm := HeightMapShape3D.new()
	
	
	ncs_hm.map_depth = heightmap_img.get_height() #chunk_size+1
	ncs_hm.map_width = heightmap_img.get_width() #chunk_size+1
	ncs_hm.map_data = data
	
	ref_collision_shape.shape = ncs_hm

```

**Comment by themotleyprogrammer** [comment]
Indeed it seems I did misunderstand how the methods worked. This issue is due to a miscalculation on my end, and this issue will be closed.
