### ISSUE TITLE
CharacterBody3D does not wallslide at all angles

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot#77850]
### Godot version

4.0.3 RC2

### System information

Windows 10

### Issue description

On Godot 3.x, if wallsliding a KinemeticBody, the controller would wallslide at all angles (besides the absolute normal of the wall) but in 4.0, it seems to need a lot more of an angle in order for wallsliding to work, and even then it doesn't seem to slide the vecetor so the speed is correct:

3.x wall-sliding:

https://github.com/godotengine/godot/assets/16231628/3c3f7ad3-f316-4575-b5e9-d54073edb0cc

4.0 wall-sliding:

https://github.com/godotengine/godot/assets/16231628/b2e68455-45bd-4455-99dd-d7a053572595

### Steps to reproduce

Try wall-sliding on 3.x:
[GodotStairs-3.x.zip](https://github.com/godotengine/godot/files/11646576/GodotStairs-3.x.zip)

Try wall-sliding on 4.0:
[GodotStairs4.0.zip](https://github.com/godotengine/godot/files/11646578/GodotStairs4.0.zip)

### Minimal reproduction project

Links above.

**Comment by Zireael07** [comment]
Title is ambiguous. Does it slide at some angles or at none at all?

**Comment by elvisish** [comment]
> Title is ambiguous. Does it slide at some angles or at none at all?

It really isn't, it slides at some angles but not all, you can see clearly in the videos (and example projects).

**Comment by ackky200R** [comment]
I struggled with this too, then I found out it's actually a feature.
[Here's a link to documentation](https://docs.godotengine.org/en/stable/classes/class_characterbody3d.html#class-characterbody3d-property-wall-min-slide-angle)
Try setting wall_min_slide_angle to 0.

**Comment by elvisish** [comment]
> I struggled with this too, then I found out it's actually a feature. [Here's a link to documentation](https://docs.godotengine.org/en/stable/classes/class_characterbody3d.html#class-characterbody3d-property-wall-min-slide-angle) Try setting wall_min_slide_angle to 0.

Thanks, that's it!
