### ISSUE TITLE
`EditorSettings` doc is not present inside the editor when using doc cache

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#77878]
### Godot version

4.0.dev [0f76ff2]

### System information

Kubuntu GNU/Linux 23.04

### Issue description

In the current `master` (stable seems fine), the `EditorSettings` doc is nowhere to be found in the editor, even though it exists: https://github.com/godotengine/godot/blob/master/doc/classes/EditorSettings.xml

### Steps to reproduce

Search for "EditorSettings" in the help dialog, or try clicking in a reference to it.

### Minimal reproduction project

N/A

**Comment by YuriSizov** [comment]
Deleting `editor_data/cache/editor.doc_cache` manually solves the problem for me. No idea why it went missing in the first place. Also no idea why this cache is considered valid.

cc @RandomShaper

**Comment by RandomShaper** [comment]
I'm not being able to reproduce this nor analytically find what can be failing in the code for either the class to be missing or the cache to be considered valid.

**Comment by akien-mga** [comment]
I can reproduce the issue locally, including with 4.1.beta3.official. It seems like 
Deleting `~/.cache/godot/editor.doc_cache` solves it for the next restart, but then opening a different Godot version with that pre-existing cache will trigger the issue again.

For example, steps to reproduce:

- Delete `~/.cache/godot/editor.doc_cache`
- Open Godot 4.1.beta3.official, check that EditorSettings is in the docs - it's there
- Close it
- Open Godot 4.1.beta2.official, check that EditorSettings is in the docs - it's missing
- Close it
- Delete `~/.cache/godot/editor.doc_cache`
- Open Godot 4.1.beta2.official, check that EditorSettings is in the docs - it's there
- Close it
- Open Godot 4.1.beta3.official, check that EditorSettings is in the docs - it's missing

The same happens testing with a build from latest `master` and 4.1.beta3.official.

Given how close we are to RC 1, and that the doc caching is not a major improvement, I suggest we disable it for now until it's fixed.

**Comment by akien-mga** [comment]
#78614 alleviates this for 4.1, so bumping milestone for actually fixing the underlying issue to 4.2.
