### ISSUE TITLE
Godot 3.0 error on core/os/os.h builds on windows

### ISSUE THREAD

**Issue by rubenjavier** [godotengine/godot#7788]
**Operating system or device - Godot version:**
Windows 10 Home 64bits
Godot 3.0

**Issue description:**
Error building on godot\core\os/os.h(406)
because 'bool OS::check_feature_support(const String &)': is abstract

C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\xlocale(341): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
platform\windows\godot_win.cpp(128): error C2259: 'OS_Windows': cannot instantiate abstract class
platform\windows\godot_win.cpp(128): note: due to following members:
platform\windows\godot_win.cpp(128): note: 'bool OS::check_feature_support(const String &)': is abstract
D:\GodotEngine\Godot.3.0\godot\core\os/os.h(406): note: see declaration of 'OS::check_feature_support'
scons: *** [platform\windows\godot_win.windows.tools.64.obj] Error 2
scons: building terminated because of errors.

**Steps to reproduce:**
.-download git source of godot from 2017 feb 12, https://github.com/godotengine/godot
.-install VS 2013 or 2015
.-install python 2.7
.-install scons
.-open a developer/tool command prompt
.-run scons on de godot directory (windows appears as platform)
.-run any of the following commands:
scons p=windows vsproj=yes
scons platform=windows -j 8 tools=yes target=release_debug
"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86 && C:\Python27\Scripts\scons platform=windows -j 8 tools=yes target=release_debug
"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" amd64 && C:\Python27\Scripts\scons platform=windows -j 8 tools=yes target=release_debug

***The same steps works for Godot 2.1 brach

**Comment by mefihl** [comment]
https://github.com/godotengine/godot/pull/7763

**Comment by rubenjavier** [comment]
Thanks,
I also had to change:
servers/audio/effects/eq.cpp
from:
50 #define BAND_LOG( m_f ) ( log((m_f)) / log(2) )
to:
50 #define BAND_LOG( m_f ) ( log((m_f)) / log((float)2) )

and:
servers/audio/effects/audio_effect_pitch_shift.cpp
from:
223 	for (k = 0, le = 2; k < (long)(log(fftFrameSize)/log(2.)+.5); k++) {
to:
223 	for (k = 0, le = 2; k < (long)(log((float)fftFrameSize)/log(2.)+.5); k++) {

**Comment by akien-mga** [comment]
Fixed by #7763.
