### ISSUE TITLE
--convert-3to4 doesn't upgrade Light2D Blend Mode `mode` -> `blend_mode`

### ISSUE THREAD

**Issue by hsandt** [godotengine/godot#77887]
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Linux Ubuntu 22.04 with Unity desktop

### Issue description

Upgrading a Godot 3 project to Godot 4 (via GUI or `godot4 --convert-3to4`) does not upgrade the Light2D `mode` member to `blend_mode`.

As a result, after opening the upgraded project, all non-Add blend modes have been lost. Subtract, Mix and Mask are all reset to Add blending mode.

Note: Mask has been removed and now requires CanvasItem clipping, which is a much more complex upgrade. I suppose we can print some warnings in the console (and if possible, in some popup when upgrading via GUI) to warn user that they need more work to upgrade this feature usage to Godot 4. It should be added on conversion doc side too, but this task has already been added on https://github.com/godotengine/godot-docs/issues/5121

At least Subtract and Mix should be upgraded correctly.

### Steps to reproduce

1. Add some lights with different blending modes in the project... or just download the MRP below
2. Run `godot4 --convert-3to4` or upgrade project via GUI
3. Observe that blending modes were lost.

Hint: for a quicker check without opening Godot, use the MRP which is under Git, run `godot4 --convert-3to4` in the console and check the Git diff to see that `mode` has not been renamed `blend_mode`.

### Minimal reproduction project

[v3.5.2 - convert 3to4 Light2D Mix Blending Mode reset to Add.zip](https://github.com/godotengine/godot/files/11655217/v3.5.2.-.convert.3to4.Light2D.Mix.Blending.Mode.reset.to.Add.zip)

**Comment by YuriSizov** [comment]
The convertor doesn't have advanced heuristics to detect when `mode` is used in the context of `Light2D` in your scripts. As the term has a very wide usage and can be mistaken in other contexts, we cannot add such a rename to the convertor. As explained in the popup before you run it, it works on the best effort principle, and such a change is outside of its capabilities.

**Comment by TheSofox** [comment]
Followed this thread and followed its conclusions to make a PR to fix this issue (though it seems I had to create a `_set()` rather than `_get()` method).
