### ISSUE TITLE
SVG files in Godot 4 not showing font

### ISSUE THREAD

**Issue by sir-vladimir** [godotengine/godot#77893]
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Atlas OS Vulkan (Forward +)

### Issue description

I made an icon in Inkscape and put it in the project, the SVG has a font text but it does not appear in Godot

![image](https://github.com/godotengine/godot/assets/69652964/018730ab-2fd5-489a-8b6a-30b7372e6d0e)

![image](https://github.com/godotengine/godot/assets/69652964/1bbb2671-0514-4aef-96e9-79ff9145b0d1)

### Steps to reproduce

Make an SVG in Inkscape with text, then import it in Godot, no text showing

### Minimal reproduction project

![icon](https://github.com/godotengine/godot/assets/69652964/7fe777d8-3480-4534-843d-781376371e47)

**Comment by RedworkDE** [comment]
This is not supported by the thorvg (https://github.com/thorvg/thorvg#svg) library used to by godot. You need to bake the text into paths for it to show up in godot.

**Comment by Ogre44** [comment]
> This is not supported by the thorvg
I see thanks.

Is it going to be soported?

**Comment by AThousandShips** [comment]
That's something to take up on ThorVG

**Comment by Calinou** [comment]
For reference, the requirement to convert text to paths is pretty common when you want your SVG to render correctly across software. Even web browsers require this if you use a font that is not available on all systems. A common approach is to duplicate the text element, hide one of them and convert the visible one to a path. This way, you can still edit the original text later.

**Comment by BeayemX** [comment]
Would it be feasible to add an optional Inkscape-importer for .svg files, like it is done for .blend files?

So that users who would require more sophisticated svg features could provide a path to the Inkscape binary which then would be used to convert the .svg files to .png files

**Comment by AThousandShips** [comment]
Is one available that is open source? Or that can be configured?

**Comment by Calinou** [comment]
> Would it be feasible to add an optional Inkscape-importer for .svg files, like it is done for .blend files?

It's technically feasible as Inkscape has a CLI, but it would rasterize files on import with no way to change their scale after the project is exported.

**Comment by TheSofox** [comment]
Looking up docs ( https://inkscape.org/doc/inkscape-man.html ) it seems Inkscape has a `--export-text-to-path` option for command line so you can keep the file as an SVG but with the text converted to paths.

As a test, I renamed the attached SVG to "LogoWithText.svg" and ran the following command:

`E:\Programs\Inkscape\bin\inkscape --export-text-to-path --export-filename LogoWithText_converted.svg LogoWithText.svg `

The resulting svg (LogoWithText_converted.svg) seemed to show the text in Godot fine:

![image](https://github.com/godotengine/godot/assets/3089525/1fb0eb01-405a-446f-a3c1-3c368e00b131)

Converted file for those curious:

![LogoWithText_converted](https://github.com/godotengine/godot/assets/3089525/f0ae41b8-898e-4ccd-b06c-73c95eaed202)

**Comment by Calinou** [comment]
@TheSofox This sounds great! Does this option exist in the Inkscape GUI as a non-destructive operation as well? I don't mean using Text to Path manually, as this is destructive (it affects your working copy in Inkscape).

**Comment by capnm** [comment]
> @TheSofox This sounds great! Does this option exist in the Inkscape GUI as a non-destructive operation as well? I don't mean using Text to Path manually, as this is destructive (it affects your working copy in Inkscape).

I know only a (relatively quick) 4-click method Ctrl + A, Ctrl + Shift + C, Save a Copy and Ctrl + Z to keep your working file...
