### ISSUE TITLE
Adding `Camera2D` to the project breaks UI rendering

### ISSUE THREAD

**Issue by BiassedTomato** [godotengine/godot#77897]
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Windows 10 - Godot v4.0.3.stable (Steam) - Vulkan API 1.2.148 - Forward+ - Using Vulkan Device #0: Intel - Intel(R) UHD Graphics 620 - NVIDIA GeForce MX150

### Issue description

Adding `Camera2D` node breaks game UI by rendering some `Control` nodes in `CanvasLayer` in world space. The issue only happens whenever `Camera2D` renders `CanvasItem` nodes (e.g. `Sprite2D`, `TileMap`, etc.), moving them out of the camera bounds/hiding them makes it render normally.

![image](https://github.com/godotengine/godot/assets/43648634/ee741dc0-ff70-48e6-b2fd-586458f01cba)
![image](https://github.com/godotengine/godot/assets/43648634/0f83c6b1-85d5-428c-a9f7-3e8f9aee8d32)

### Steps to reproduce

1. Create a new project
2. Create a new `Node2D` scene
3. Add a `CanvasLayer` to the `Node2D`
4. Add a `PanelContainer` to the `CanvasLayer`
5. Add a `RichTextLabel` to the `PanelContainer` and give it any text
6. Add a `Camera2D`
7. Move the `Camera2D` (e.g. set position to `1100, 320`) 
8. Add a `Sprite2D` node and assign a texture to it
9. Move the `Sprite2D` node so that the `Camera2D` can see it (partially or fully)
10. Run Project
11. The panel is rendered in the world space, while `RichTextLabel` is rendered as expected in the screen space.
13. Move the `Sprite2D` out of the bounds or hide it to make the panel render the way you would expect

### Minimal reproduction project

[TestIssue.zip](https://github.com/godotengine/godot/files/11660128/TestIssue.zip)

**Comment by arkology** [comment]
May be related: https://github.com/godotengine/godot/issues/58314
But I'm not sure ATM.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/58314.
