### ISSUE TITLE
Issues in input map dialog

### ISSUE THREAD

**Issue by punto-** [godotengine/godot#7790]
Tested in branch 2.2-legacy

- When adding a joystick button to an action, the "device" value is set to 3
- The little buttons on the spinbox don't respond to half of the clicks (it takes more than 3 clicks to set the value down to 0)
- After adding the button, the selected action becomes the first action that contains the button added, instead of the action that was being edited. For example, add a new action "jump", on the jump action add the button "0: PS X [etc]", the selected action becomes "ui_accept" (the first of the default actions that uses button 0)

**Comment by Hinsbart** [comment]
We also noticed this (at least the "device set to 3" part of it) on the 2.1 branch, during FOSDEM when we quickly added gamepad support to some games for showcase :P

**Comment by Hinsbart** [comment]
The problem with the little arrow buttons not responding seems to apply to all spinboxes, not only in the InputMap dialog. So it might be worth putting that into a separate issue.

**Comment by punto-** [comment]
(reopen because it was like 3 issues in the same one, I guess we need some of those checklist things?)

**Comment by akien-mga** [comment]
Well @Hinsbart fixed your points 1 and 3, and created issue #7800 for point 2 that was fixed too.

**Comment by punto-** [comment]
Oh I didn't see the ones for points 1 and 3, sorry :)
