### ISSUE TITLE
GridMap lighting appears as if a sphere instead of per surface

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#77908]
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Mac (Compat mode)

### Issue description

When drawing imported meshes in a gridmap the shading is very strange.

<img width="688" alt="Screenshot 2023-06-06 at 19 07 49" src="https://github.com/godotengine/godot/assets/100964/09e15f65-c618-4c4b-89a2-8ab363357f85">

<img width="688" alt="Screenshot 2023-06-06 at 19 08 19" src="https://github.com/godotengine/godot/assets/100964/702f7dd1-2ba3-4e37-b029-e2d90421a28c">

This works correctly for godots built in `BoxMesh` however

### Steps to reproduce

1. Download minimum repo
2. Run the project

### Minimal reproduction project

[test-gridmap-lighting.zip](https://github.com/godotengine/godot/files/11664421/test-gridmap-lighting.zip)

**Comment by Calinou** [comment]
This is not an issue with the engine – this is an issue with the mesh as authored in your 3D DCC. Your box meshes both have smooth faces when they should have flat faces:

![image](https://github.com/godotengine/godot/assets/180032/8e69ea9f-108a-42af-8d3a-c0df86b3d9bd)

**Comment by tavurth** [comment]
@Calinou Thank you! 🙏 

I'd been wondering if it was a bug for a while

<img width="688" alt="Screenshot 2023-06-06 at 19 41 36" src="https://github.com/godotengine/godot/assets/100964/923e7fdc-3aca-47f9-a5b3-7dfe258bf064">

In Wings3D
<img width="245" alt="Screenshot 2023-06-06 at 19 42 19" src="https://github.com/godotengine/godot/assets/100964/caeef5da-eae7-41d9-b5c2-4b86ea3ec5dd">

<img width="572" alt="Screenshot 2023-06-06 at 19 42 31" src="https://github.com/godotengine/godot/assets/100964/e006db66-1093-48a1-8295-886fe8c185bd">
