### ISSUE TITLE
The frame field (the spinbox) in visual profiler shows big number.

### ISSUE THREAD

**Issue by MiaoBlade** [godotengine/godot#77915]
### Godot version

4.0.3.stable

### System information

win10 vulkan

### Issue description

![frame](https://github.com/godotengine/godot/assets/103508289/6f1ff1df-eaab-4cda-b31f-01790fbd4bc2)
the value is 18446744073709549568
sometimes output shows:
Cannot represent 18446744073709549568 as a 64-bit signed integer, since the value is too large.

### Steps to reproduce

i locate this bug.
in godot\editor\debugger\editor_visual_profiler.cpp line 70:
`cursor_metric_edit->set_max(frame_metrics[last_metric].frame_number);`
`cursor_metric_edit->set_min(MAX(frame_metrics[last_metric].frame_number - frame_metrics.size(), 0u));`
![watch](https://github.com/godotengine/godot/assets/103508289/256f4363-e508-4d63-a45f-e0bf804153f3)
unsigned substraction result in big number

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/62341.
