### ISSUE TITLE
iOS Label - RichLabel - Emoticons are not showing up - Godot 4.0.3

### ISSUE THREAD

**Issue by MarcusDobler** [godotengine/godot#77914]
### Godot version

4.0.3 stable

### System information

MacOS - 4.0.3 Stable

### Issue description

Labels and RichTextLabels render emoticons in my preview window on MacOS perfectly fine! But when exporting to iOS neither Labels nor RichTextLabels show up the emoticons.

### Steps to reproduce

Make a Godot 4 Project add a Control Node add a Label Node put some emoticons in the label export to iOS! Nothing shows up.

### Minimal reproduction project

Do not think a project is needed to reproduce the issue.

**Comment by arkology** [comment]
> Do not think a project is needed to reproduce the issue.
Offtopic: I think, MRP is almost always needed. Because without it mainteiner has to not only fix bug but also create MRP before fixing.

**Comment by AThousandShips** [comment]
> Required, unless the reproduction steps are trivial and don't require any project files to be followed

Indeed, this isn't entirely trivial and might well be configuration specific

However, are you using a font which supports emoticons?

**Comment by MarcusDobler** [comment]
Yes I do, because it works on the Mac in the Preview Window

**Comment by AThousandShips** [comment]
So the font itself contains them? Turn off fallback on the font and try

**Comment by Calinou** [comment]
cc @bruvzg 

Support for system fonts is listed in the documentation, but maybe iOS ships with different/more limited emoji fonts that third-party apps can use.

**Comment by MarcusDobler** [comment]
Ok, I made a project with all your advises the result in macOS:

<img width="688" alt="Bildschirm­foto 2023-06-07 um 06 37 14" src="https://github.com/godotengine/godot/assets/16276195/fef18b08-b6f6-4d27-930f-882df6bd8350">

The result on iOS:

![ios](https://github.com/godotengine/godot/assets/16276195/d2711753-6285-44a6-bac1-df5233ca0ebe)

In macOS my font with fallback turned off is showing there is something wrong. This also happens on iOS.  I wasn't aware, emoticons aren't supported on iOS so I have to turn off fall back. Sorry. I hope this feature will come in the future.

Anyway the System Font renders all emoticons perfectly fine on macOS but the do not show up on iOS.

As you wanted I put the project in a .zip file. Hope that helps.

[project.zip](https://github.com/godotengine/godot/files/11672568/project.zip)

**Comment by MarcusDobler** [comment]
Now I've downloaded: NotoColorEmoji-Regular.ttf

Made a third label using this Font just to render the emoticons, nothing shows up even on macOS:

(The not rendered letters make the word NOTO)

<img width="809" alt="Bildschirm­foto 2023-06-07 um 07 04 00" src="https://github.com/godotengine/godot/assets/16276195/37d4027a-2dc0-4068-adf9-27c3e388a13e">

The picture shows the editor and the Godot preview window.

I put the ne project file here

[project.zip](https://github.com/godotengine/godot/files/11672669/project.zip)

**Comment by MarcusDobler** [comment]
Maybe it helps! With Noto Font I get this error as often as much emoticons are in my TextLabel:

<img width="600" alt="Bildschirm­foto 2023-06-07 um 07 21 44" src="https://github.com/godotengine/godot/assets/16276195/8747dc5f-9d54-466f-ace4-36c4b76b1ea6">

if I make 1 emoticon I get the error once, if I make 4 emoticons I get it 4 times.

**Comment by bruvzg** [comment]
iOS exports have support for the system fonts, but emoji font format might be unsupported.

There are COLR emoji fonts (not supported by Godot), SVG emoji fonts (supported, but ThorVG is not capable to render some SVG, which seems to be the case with fresh versions of Noto Emoji), and bitmap (PNG) emoji fonts (supported, that's what built-in windows and macOS fonts are). Old versions of Noto Emoji were bitmap as well.

**Comment by MarcusDobler** [comment]
Do you have a link to a working font for me so I can test it! I used Noto because its mentioned in the documentation

**Comment by bruvzg** [comment]
This one should work [NotoColorEmoji.ttf](https://github.com/googlefonts/noto-emoji/blob/main/fonts/NotoColorEmoji.ttf).

**Comment by MarcusDobler** [comment]
Thank you ... I'll try it

**Comment by MarcusDobler** [comment]
Maybe I'm doing something wrong! the downloaded .ttf file I can't even install on macOS. So I think it's corrupt?

**Comment by bruvzg** [comment]
> Maybe I'm doing something wrong! the downloaded .ttf file I can't even install on macOS. So I think it's corrupt?

It works with Godot, installing emoji font as system font usually require OS specific version.

SVG version of Noto Emoji should be fixed by - https://github.com/godotengine/godot/pull/77942

**Comment by MarcusDobler** [comment]
> > Maybe I'm doing something wrong! the downloaded .ttf file I can't even install on macOS. So I think it's corrupt?
> 
> It works with Godot, installing emoji font as system font usually require OS specific version.
> 
> SVG version of Noto Emoji should be fixed by - #77942

Great this works with my font and the downloaded Noto Font as a fallback

**Comment by bruvzg** [comment]
For the reference, iOS default emoji fonts use Apple's EMJC image compression instead of usual PNG, so it's not supported.

**Comment by Calinou** [comment]
- 
This was documented by https://github.com/godotengine/godot-docs/pull/7481, closing.

**Comment by ardaokyay** [comment]
@Calinou @bruvzg Preview in MacOS works fine with emojis but exports to iOS do not render any emojis. Could you please reopen this issue or create another one?

Apologies if mentioning or reviving an old issue is not standard procedure.

Thanks!

**Comment by Calinou** [comment]
> @Calinou @bruvzg Preview in MacOS works fine with emojis but exports to iOS do not render any emojis. Could you please reopen this issue or create another one?

You need to enable ICU data export in the project settings (`internationalization/locale/include_text_server_data`), as it's required for emoji display. This data is always available in editor binaries, but not in export template binaries due to its relatively large size. This won't be needed anymore if https://github.com/godotengine/godot/pull/120232 is merged.

**Comment by ardaokyay** [comment]
> > [@Calinou](https://github.com/Calinou) [@bruvzg](https://github.com/bruvzg) Preview in MacOS works fine with emojis but exports to iOS do not render any emojis. Could you please reopen this issue or create another one?
> 
> You need to enable ICU data export in the project settings (`internationalization/locale/include_text_server_data`), as it's required for emoji display. This data is always available in editor binaries, but not in export template binaries due to its relatively large size. This won't be needed anymore if [#120232](https://github.com/godotengine/godot/pull/120232) is merged.

Thank you for your reply. I have enabled ICU data export on project settings, although unfortunately still couldn't get emojis to work on iOS. My Godot version is v4.6.2.stable.official ... should i open an issue with MRP?

**Comment by bruvzg** [comment]
iOS still uses non-standard emoji font, you should include your own emoji font for it to work.
