### ISSUE TITLE
Starting a thread in GDScript that calls function with arguments will print error message in recent Godot build

### ISSUE THREAD

**Issue by narren96c** [godotengine/godot#77928]
### Godot version

Godot 4.1-dev (ed63b9ea23)

### System information

Manjaro Gnome

### Issue description

`thread.start(test.bind(0))` prints the following error:

```
ERROR: Caller thread can't call this function in this node. Use call_deferred() or call_thread_group() instead.
   at: get_script (scene/main/node.cpp:3536)
```

### Steps to reproduce

```
func _ready() -> void:
	var thread := Thread.new()
	thread.start(test.bind(0))

func test(i: int) -> void:
	pass
```

### Minimal reproduction project

N/A

**Comment by bitsawer** [comment]
Can confirm. Looks like the `bind(0)` call creates the issue, this works without any errors:

```gdscript
var thread := Thread.new()

func _ready() -> void:
	thread.start(test)

func test() -> void:
	print("no error")
```

I guess the Callable created when using `bind()` calls `get_script()` at some point during the threaded call, which will fail with the new thread safety checks. Note that normally a thread should always be waited until finished, but it's not really relevant for this example.
