### ISSUE TITLE
Camera2D causing RigidBody2D to not move when rotating

### ISSUE THREAD

**Issue by hydroper** [godotengine/godot#77922]
### Godot version

4.0.3.stable

### System information

Windows 11, gl_compatibility

### Issue description

When I disable the camera of my car (`self._camera.enabled = false`), it moves OK. When I enable it:

```gd
self._camera.enabled = self.is_main_player
# self._camera.enabled = false
```

both in the `_ready` and `_process` methods, the car does not move. I also ran `print(self.position.x)` to observe the position logs and I can see its value changes in a very unusual way — it basically doesn't move.

NOTE: to reproduce the car movement working and disabling the camera, you must comment exactly like this:

```gd
# DO THIS

# self._camera.enabled = this.is_main_player
self._camera.enabled = false

# DON'T DO this

self._camera.enabled = this.is_main_player
self._camera.enabled = false
```

in both `_ready` and `_process`, otherwise the movement won't work. Looks redundant, but yes.

### Steps to reproduce

- Add a `Camera2D` to a `RigidBody2D`
- Set `cam.enabled = true`
- Use the directionals to move the `RigidBody2D`

### Minimal reproduction project

`git clone https://github.com/hydroper/carknockonline` or https://github.com/hydroper/carknockonline

- The car is the `AutomobileEntity` (in [`src/entities/AutomobileEntity.tscn`](https://github.com/hydroper/carknockonline/tree/master/src/entities))
- The main scene is [`src/screens/game/GameScreen.tscn`](https://github.com/hydroper/carknockonline/tree/master/src/screens/game)

Pay attention to the comment above when disabling the camera:

```gd
# this

# self._camera.enabled = self.is_main_player
self._camera.enabled = false

# NOT this

self._camera.enabled = self.is_main_player
self._camera.enabled = false
```

**Comment by AThousandShips** [comment]
Can you confirm this only occurs in C#? Otherwise you need to follow this:
> If your issue is not Mono-specific, please upload a minimal reproduction project written in GDScript or VisualScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a Mono setup available.

**Comment by hydroper** [comment]
@AThousandShips I'm a bit lazy to go ahead and write something in GDScript, but I'll see if I can try a basic thing.

**Comment by AThousandShips** [comment]
I mean these are the instructions for making a bug report, and you're just shooting yourself in the foot because few contributors will be able to help you

**Comment by hydroper** [comment]
@AThousandShips Right; I've wrote a bit on GDScript and it the `Camera2D` works as expected. I'm guessing something is wrong with the C# support?

Since I'm not finding anyway to fix it, I guess I might try to move to GDScript.

**Comment by henriquelalves** [comment]
I tested the C# project. Couldn't replicate the issue, the player wasn't moving regardless of camera enabled in the `GameScreen` scene.

I could make the player move by commenting out some of the `_Process` code (in particular the rotation tween) and setting `RawSpeed` to always return the `SpeedOf` result, so this seems code behavior, not an engine issue. Won't delve too much more in this issue because I didn't properly setup my C# environment, I was editing code in Godot itself.

**Comment by hydroper** [comment]
@henriquelalves About the camera being enabled or not, did you consider this:

```
// THIS!!!!!!!

// this._camera.Enabled = this.IsMainPlayer;
this._camera.Enabled = false;

// NOT THIS!!!!!!!

this._camera.Enabled = this.IsMainPlayer;
this._camera.Enabled = false;
```

? Because the latter somehow does not work. If you do it exactly that way in both `_Ready` and `_Process`, the movement works.

**Comment by hydroper** [comment]
I'm rewritting the exact same code it in GDScript and will return soon telling how it goes.

**Comment by henriquelalves** [comment]
I believe I tested both cases, but I'm not sure I tested this in `_Ready` AND in `_Process`, maybe just in one of them.

**Comment by AThousandShips** [comment]
The setting the camera and clearing it is probably not safe here, it does update some details and could cause weird effects, setting and clearing it is *not* the same as never setting it

**Comment by hydroper** [comment]
@henriquelalves It looks like according to what you said, the rotation is what is breaking the camera. Why?

I didn't need to change the `raw_speed` to make the camera work.

**Comment by hydroper** [comment]
I've commented the `self.rotation_degrees = ...` everywhere and did this at the end of `_process`:

```gd
# self.rotation_degrees = self._rotation_tween.current_rotation if self._rotation_tween.is_running() else TurnDirectionf.angle(self._turn_dir)
self.move_forward(delta)
# self.rotation_degrees = self._rotation_tween.current_rotation if self._rotation_tween.is_running() else TurnDirectionf.angle(self._turn_dir)
# self._rotation_tween.process(delta)
self.rotation_degrees += 1
```

And, yes, it's not my tweener the problem!

**Comment by hydroper** [comment]
I've put a constant `ROTATION_ENABLED`. Just toggle it on or off instead of doing the above comments

**Comment by hydroper** [comment]
Cleaner issue:

https://github.com/godotengine/godot/issues/77950
