### ISSUE TITLE
Opening the Godot project with a gdextension just closes Godot with no message

### ISSUE THREAD

**Issue by nvanfleet** [godotengine/godot#77921]
### Godot version

4.0.3

### System information

Mac OS Arm64

### Issue description

I have a gdextension that uses SwiftGodot. I know that there is something with some particular scenes that are causing issues with Godot. 

1. Install the extension
2. Open the Godot project
3. The Godot project auto-opens the scene in question
4. About two seconds into the project opening Godot will just quit completely
5. There is no error message displayed or crash log in Console. There isn't any information on why Godot decided to quit. 

I can get out of this state by:
1. Changing the name of my gdextension file to "Extension.gdextension_"
2. The project now opens fine
3. Open a different scene and make sure to close the "bad" scene
4. Re enable the extension

However I still have zero feedback on why that scene in question had issues.

### Steps to reproduce

Ultimately having a gdextension that causes these issues. I don't really have anything more than a whole project to show since I can't troubleshoot the root cause of why this gdextension is causing issues since Godot doesn't seem to handle it gracefully

### Minimal reproduction project

I don't have one for now

**Comment by Calinou** [comment]
@nvanfleet Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.

PS: Since no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
