### ISSUE TITLE
BoxShape3D and RectangleShape2D has incorrect size after project conversion due to change how size/extents are treated in 4.x

### ISSUE THREAD

**Issue by sketchyfun** [godotengine/godot#77931]
### Godot version

v4.1.dev.custom_build [0a0132ccf]

### System information

Windows 10

### Issue description

When converting a project from 3 to 4, any BoxShape3D resources will end up being half the size they were in Godot 3.x

This seems to be due to the fact BoxShape3D's dimensions were defined by half extents, and now Godot 4.x uses full extents.

So a BoxShape3D that had extents of 1,1,1 in Godot 3 was actually 2m x 2m x 2m, whereas now in Godot 4 those same values would be treated as 1m x 1m x 1m

### Steps to reproduce

Create a Godot 3.x project with a BoxShape3D shape as part of a collider
Convert the project to 4.x using the project converter and open it
Notice that the BoxShape3D now appears to be half the size in the editor despite the values being the same

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
BoxShape3D already handles `extents` property, so this conversion should be removed from the converter. Also might affect `LightmapGI` and `ReflectionProbe`.

**Comment by sketchyfun** [comment]
> BoxShape3D already handles `extents` property, so this conversion should be removed from the converter. Also might affect `LightmapGI` and `ReflectionProbe`.

Are you saying BoxShape3D already deals with the old `extents` property and converts it into the new `size` property? Sorry, bit confused by what you mean

**Comment by KoBeWi** [comment]
Yes
https://github.com/godotengine/godot/blob/0a0132ccf40b14d2ca8987193b3b07a5fe03a674/scene/resources/box_shape_3d.cpp#L60-L65

**Comment by sketchyfun** [comment]
Ah okay. So the issue is with BoxShape3D doing the conversion and the project converter doing it as well? I converted my project a while ago, so it may be that it wasn't handled by the converter back then, or maybe some other weirdness happened. Either way the size of all of them was half what it should be and I ended up writing some regex stuff to go through and fix all 300+ instances in my project

**Comment by ARez2** [comment]
Hmm I looked into `project_converter_3_to_4.cpp` but I can't find the place where the extents conversion happens...

**Comment by KoBeWi** [comment]
It's in another file
https://github.com/godotengine/godot/blob/300748e52c03fd1761b716fc7eea2b9fb97b86f9/editor/renames_map_3_to_4.cpp#L1101

**Comment by ARez2** [comment]
Yes I found that as well. A really weird thing just happened. So I used my local version of Godot (did `git pull` before) and converted this project:
[Conversion3.zip](https://github.com/godotengine/godot/files/11706464/Conversion3.zip) 

Its just a simple scene with a CSGBox3D. Weird thing is: In Godot 3.5 (Steam version), the size was (2, 4, 6) but after converting it to Godot 4 using my engine version (I changed nothing in the converter files), the size was (1, 4, 6)... Can anyone explain why that would happen?

**Comment by ARez2** [comment]
Sorry I forgot to test out BoxShape3D. So, updated project:
[Conversion3.zip](https://github.com/godotengine/godot/files/11706496/Conversion3.zip)

Converting this project ("Convert full project") also produces that (1, 4, 6) size on the CSG node, but leaves the newly added CollisionShape3D with a BoxShape of size (2, 4, 6) at that exact size. So does the conversion not work?

**Comment by KoBeWi** [comment]
```
[node name="CSGBox" type="CSGBox" parent="."]
height = 4.0
depth = 6.0
```
It's missing `width` (using the default of 2).

**Comment by Zireael07** [comment]
@KoBeWi 90% sure this is the case but I can't check as my CSG-using project is broken by an attempt to convert to 4.x

**Comment by Wolses** [comment]
Can confirm that adding width to the G3 project's `Main.tscn` file gives you this when you convert it:
```
[node name="CSGBox3D" type="CSGBox3D" parent="."]
width = 2.0
height = 4.0
depth = 6.0
```
And gives you a box sized (2, 4, 6). Though I never used 3.x so I'm unclear whether it would just omit dimensions if the values are the default size.

**Comment by KoBeWi** [comment]
Default values are not stored.

**Comment by Wolses** [comment]
So a fix for this would either be 1) something that adds a line `width/height/depth = 2.0` if no value is found, OR 2) something that changes width/height/depth to `size = Vector3(w,h,d)` format. I'm going to try option 2.

**Comment by BrunoArmondBraga** [comment]
Hii everyone, I am working on this issue! Just trying to understand the changes needed on LightmapGI so I can safely delete the conversion from the renames_map_3_to_4.cpp file

**Comment by elvisish** [comment]
Can this be changed to include CollisionShape2D? (Also is imported at half the size due to extents changing)

**Comment by BrunoArmondBraga** [comment]
Trying to solve the problem, I commented the line
https://github.com/godotengine/godot/blob/0ca8542329888e8dccba89d59d3b728090c29991/editor/renames_map_3_to_4.cpp#L1101C1-L1101C1
But this arrived a new issue: when trying to access your own `extents` property (on a ReflectionProbe converted script, for example), Godot 4 rises the error `Identifier 'extents' not declared in the current scope`. However, if you use `self.extents` it works fine. So, removing the `extents` rename causes this type of script error as a side effect.
Should I create a PR to solve this issue and open a new issue to deal with this side effect? Or should we try to solve everything at once?

**Comment by KoBeWi** [comment]
I think script errors are ok, because you can see that something is wrong. In case of scenes the values are silently lost.
