### ISSUE TITLE
Transform origin (translation) of Node not saved to scene file (tscn)

### ISSUE THREAD

**Issue by adamlesinski** [godotengine/godot#77940]
### Godot version

3.5.1.stable

### System information

Windows 11

### Issue description

In my main scene, I load a sub-scene `CameraController` and set its transform in the main scene Node inspector.

![image](https://github.com/godotengine/godot/assets/915136/4cc1460f-764b-4857-9ad4-1e2a5a29dfa2)

![image](https://github.com/godotengine/godot/assets/915136/e5297826-f090-4334-aa9e-06a5afa6457c)

The `translation` does not get saved to the tscn file (no `transform` property), which can be checked by reloading the project or looking at the tscn file with a text editor.

I tried setting the value directly in the tscn file, then reloading the project. Once I hit run, the tscn file is overwritten and the transform property is removed.

This happened only with this particular sub-scene, so I stripped it down to the bare-bones and it still reproduces.

### Steps to reproduce

- Load the repro project attached
- Set the `translation` of the `CameraController` node in `Main.tscn`
- Save the project
- Reload the project
- Check the `translation` of the `CameraController` node in `Main.tscn`.
- Notice that the `translation` is back to `0, 0, 0`.

Repeat the above with the `rotation` or `scale` property and notice that these do persist.

### Minimal reproduction project

[parks_repro.zip](https://github.com/godotengine/godot/files/11672413/parks_repro.zip)

**Comment by lawnjelly** [comment]
The problem is coming from the animation player:
```
ERROR: Failed setting key at time 0 in Animation '' at Node '/root/EditorNode/AnimationPlayer', Track '.:zoom'. Check if property exists or the type of key is right for the property
   at: _animation_update_transforms (scene/animation/scu/../animation_player.cpp:878)
```
Something is incorrect in the animation, and it is failing and this is mucking up the saving. Will add more info as I get it.

**Comment by adamlesinski** [comment]
Yes, `zoom` was removed as part of reducing to the bare minimum repro project.

Interesting! The `reset_on_save` checkbox explains it. I long ago removed the actual animation that affects `CameraController` translation, and completely forgot that the RESET animation still referenced `translation`.

Thanks for looking into this, and so quickly! Much appreciated :)
