### ISSUE TITLE
Multi selection does not work in gdscript flag properties size_flags_horizontal

### ISSUE THREAD

**Issue by difight** [godotengine/godot#77947]
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Windows 11

### Issue description

In the control component, it is possible to select multiple values in the container sizing horizontal property, but there is no way to select multiple values via gdscript

### Steps to reproduce

![Screenshot_1](https://github.com/godotengine/godot/assets/8627933/086aa5c8-fe16-4fb7-8df2-faa22683f8a9)

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
How do you mean it's not possible in GDScript? Does: `size_flags_horizontal = SIZE_FILL | SIZE_EXPAND` not work?

**Comment by difight** [comment]
> How do you mean it's not possible in GDScript? Does: `size_flags_horizontal = SIZE_FILL | SIZE_EXPAND` not work?

This option works, thank you, the issue can be closed

**Comment by AThousandShips** [comment]
For support questions and help please first turn to the other [community channels](https://godotengine.org/community), this is for bug reporting, not a help desk, so please try to make sure it's a bug first.

**Comment by AThousandShips** [comment]
However the wording might be considered ambiguous, please reopen so we can track improving the documentation
