### ISSUE TITLE
Clicking a selected item in the error log doesn't scroll back to it

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#77944]
### Godot version

Godot 4.1.dev4

### System information

Ubuntu 22.04.2 LTS 22.04 - Vulkan (Forward+) - integrated Intel(R) HD Graphics 4400 (HSW GT2) () - Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 Threads)

### Issue description

![image](https://github.com/godotengine/godot/assets/85438892/a61e8333-d9f0-40ec-a508-d301850d05e9)

Let's suppose I clicked this item, then scrolled around in my script, and I then wanted to check out the warning's line again. It wouldn't work without selecting another item first.

Should be an easy fix by setting `allow_reselect = true` in the underlying tree.

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by Nimausfi** [comment]
Hi Mew, can I set the allow_reselect = true in tree.h and open a PR for #77944? Thank you!
