### ISSUE TITLE
My RigidBody2D with a Camera2D won't move if I rotate it (GDScript)

### ISSUE THREAD

**Issue by hydroper** [godotengine/godot#77950]
### Godot version

4.0.3.stable

### System information

Windows 11, gl_compatibility

### Issue description

If I change the `rotation_degrees` of a `RigidBody2D` with a `Camera2D`, it won't move. If there's no `Camera2D`, the car moves successfully with a rotation.

I've set `rigid_body_2d.lock_rotation = true` since I want to control the rotation myself.

To remove the camera in the minimal project below you've to replace:

```gd
    self._camera.enabled = self.is_main_player
    # self._camera.enabled = false
```

by:

```gd
    # self._camera.enabled = self.is_main_player # yes, you've to comment this for some reason (?)
    self._camera.enabled = false
```

in both `_ready` and `_process`.

### Steps to reproduce

- Add a `Camera2D` to a `RigidBody2D` car
- Set `cam.enabled = true`
- Use the directionals to move the `RigidBody2D`
  - The car rotates depending on pressed directionals

### Minimal reproduction project

[godot_camrotationbug.zip](https://github.com/godotengine/godot/files/11677207/godot_camrotationbug.zip)

Look at `src/entities/AutomobileEntity.gd`

- Change the constant `ROTATION_ENABLED` at the top to `true` or `false`. The car will move if false.

**Comment by AThousandShips** [comment]
This really isn't a minimal project, can you please create a minimal project that shows the issue?

**Comment by hydroper** [comment]
Oh, but isn't that torque meant for other kind of top-down car games?

**Comment by AThousandShips** [comment]
If you don't want to mess with that you can just use `CharacterBody2D`, it seems you're using `RigidBody2D` in a way it's not meant to

It's for rotating objects, it isn't the torque of an engine, torque is just the rotation equivalent of force (kinda, not really, but kinda)

**Comment by hydroper** [comment]
@AThousandShips Well, I did try using `CharacterBody2D`, but I've two issues with it:

- Friction. You can't slide through ice-like walls unless you check for collisions and their angles. I was able to slide with `CharacterBody2D`, but had to implement a very limited slide collision check.
- Forces. You can't apply forces; you've to tweak the speed manually.

The game I'm trying to mimmick (SharkBite Bay), done in ActionScript 3 by some guy, uses a rigid body from a general relativity library. Also, the car doesn't move like in most common 2D top-down car games. Directionals do not increase/decrease rotation like in other games...

**Comment by AThousandShips** [comment]
Look at the documentation above to see, you're not supposed to set the rotation every frame as it breaks the simulation, you need to use other means

**Comment by hydroper** [comment]
But I've locked the rotation with ``

**Comment by AThousandShips** [comment]
No, where are you getting that?

**Comment by hydroper** [comment]
- [RigidBody2D.lock_rotation](https://docs.godotengine.org/en/stable/classes/class_rigidbody2d.html#class-rigidbody2d-property-lock-rotation)

> If `true`, the body cannot rotate. Gravity and forces only apply linear movement.

- [[How to implement the movement system from SharkBite Bay Adventure?](https://gamedev.stackexchange.com/questions/205831/how-to-implement-the-movement-system-from-sharkbite-bay-adventure)](https://gamedev.stackexchange.com/q/205831/172220)
- [[Constant rotation tween in Godot 4](https://stackoverflow.com/questions/76400925/constant-rotation-tween-in-godot-4)](https://stackoverflow.com/q/76400925/19692949)

**Comment by AThousandShips** [comment]
1) That doesn't say *you* can change it freely, the following still stands:
> Please also keep in mind that physics bodies manage their own transform which overwrites the ones you set.
2) Neither of those use `RigidBody2D`, the first uses `CharacterBody2D` and the later `Node2D`

**Comment by hydroper** [comment]
I asked these questions before using `RigidBody2D`. Well, what can I do then? `CharacterBody2D` is very inflexible, for example... if you hit a wall with a very high speed, the car gets stuck on the wall due to accumulated speed. To fix this I've to manually check if the car collided in a certain angle and reset the speed in that direction, and of course this only works for rectangles. Using `RigidBody2D` I don't need to worry about this.

**Comment by AThousandShips** [comment]
Then follow the instructions for how to rotate them, you can't set the rotation of a RigidBody like this, or use the custom integrator for rotation

This is a limitation of this type of body, as documented

**Comment by hydroper** [comment]
I'm not sure changing anything in `_integrate_forces` will resolve the camera problem. When I remove the camera, the car works. So it's clearly a bug.

**Comment by hydroper** [comment]
> Have you tried? Try making a way to rotate the car that follows the proper way of doing things and see if it resolves your problem, as you are, as far as I know, not doing things correctly, and if you are you can't expect it to work correctly

I've played with `state.angular_velocity = 1` in `_integrate_forces` and that doesn't break the camera behaviour and makes the movement work, so it may help, but I'm not entirely sure how I'd create a tweener to work with this.

I was not using Godot's built-in `Tween` because:

- It requires a duration. There's no duration in my case.
- It goes either clockwise or counterclockwise wrongly sometimes (e.g. I want to go to target angle through the fatest route: clockwise or counterclockwise).

Aside that, there is one issue with setting `state.angular_velocity`! Depending on how I move the car, the angle abruptly changes itself even without assigning `rigidbody2d.rotation_degrees` or `rigidbody2d.rotation`. Bug?

**Comment by AThousandShips** [comment]
Use a tweeler to assign the target angle, and use angular velocity to move towards it

But this isn't a help desk, while the camera thing might be a bug, and someone will look into that. But for support questions and help please first turn to the other [community channels](https://godotengine.org/community), this is for bug reporting, I've tried to help you by pointing you in the right direction, but this isn't what this is for.
