### ISSUE TITLE
Indefinitely repeating errors when editing a preloaded scene containing TextureRect and ViewportTexture

### ISSUE THREAD

**Issue by rgson** [godotengine/godot#77981]
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Debian 11 | Vulkan API 1.2.175 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1080 | nvidia-driver 470.182.03-1 from Debian 11 | Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz

### Issue description

Re-opening a scene in the editor that contains a `TextureRect` with a `ViewportTexture` and is `preload`ed in an unopened script produces the following error repeatedly and rapidly (about 200 times per second) until either the scene is closed or the script is also opened.

>ERROR: Texture (binding: 0) should provide one ID referencing a texture (IDs provided: 0).
>   at: uniform_set_create (drivers/vulkan/rendering_device_vulkan.cpp:5501)
>ERROR: Condition "!uniform_set" is true.
>   at: draw_list_bind_uniform_set (drivers/vulkan/rendering_device_vulkan.cpp:7191)
>ERROR: Uniforms were never supplied for set (3) at the time of drawing, which are required by the pipeline
>   at: draw_list_draw (drivers/vulkan/rendering_device_vulkan.cpp:7346)

### Steps to reproduce

1. Open the attached reproduction project
2. Open demo.tscn
3. Close demo.tscn
4. Open demo.tscn again

Do **not** open other.gd beforehand. Doing so will stop the problem from occurring.

### Minimal reproduction project

[reproduce_uniform_not_set.zip](https://github.com/godotengine/godot/files/11681977/reproduce_uniform_not_set.zip)

**Comment by Braveo** [comment]
This happens for me but for a sprite that has a viewport texture. Errors display this for me, on two devices; one with i5 11600 + RTX 3060 TI, and the other device with i5-1135G7 + integrated graphics. Not sure if this is the same source of the error but may be similar considering the repeating errors.

Here are the errors that display for me (repeatedly):

```
Texture (binding: 0) should provide one ID referencing a texture (IDs provided: 0).
drivers/vulkan/rendering_device_vulkan.cpp:7208 - Condition "!uniform_set" is true.
```

**Comment by HauptmannBoosted** [comment]
can confirm this also happened on my AMDryzen 9 5900X and 3060TI, (4.0.3.stable - steam version), was only temporarily though and resolved itself when reopening the project.

Am also using Sprites with ViewportTexture

**Comment by jlucasdelima** [comment]
This is happening to me as well. In my case the same problem occurs when the viewport in question have a child scene instanced
PC setup: i5 7500 and GTX 1050ti
Godot versions tested: 4.0.3.stable and master (commit 4642448 ...)

[uniform_not_set_bug.zip](https://github.com/godotengine/godot/files/11928572/uniform_not_set_bug.zip)

**Comment by jlucasdelima** [comment]
I came up with a workaround for a while this bug isn't fixed. I've coded a very simple script for the sprite/textureRect using "@tool" annotation, so we can set the viewport nodepath to the script and change the sprite texture based on this nodepath manually. Since we are using "@tool" we can visualize the result in the editor. Although, when switching tabs, an error "Node not found..." is raised. It doesn't cause any problems with the visualization, but it can be a hint as to what is causing this issue.

[uniform_not_set_workaround.zip](https://github.com/godotengine/godot/files/11940237/uniform_not_set_workaround.zip)

**Comment by rgson** [comment]
Still happens in Godot v4.1.stable.official [970459615].

> Texture (binding: 0) should provide one ID referencing a texture (IDs provided: 0).
> drivers/vulkan/rendering_device_vulkan.cpp:7208 - Condition "!uniform_set" is true.
> Uniforms were never supplied for set (3) at the time of drawing, which are required by the pipeline

System info:
> Godot v4.1.stable - Debian GNU/Linux 12 (bookworm) 12 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1080 (nvidia) - Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 Threads)
