### ISSUE TITLE
Strange selection in Godot 3.0

### ISSUE THREAD

**Issue by mefihl** [godotengine/godot#7798]
**Operating system or device - Godot version:**
Windows 10, Godot 3.0 master 

**Issue description:**
When add node2D or another node selection is very strange.

![plplplplplplplplplpl](https://cloud.githubusercontent.com/assets/5302754/22898653/5f728906-f228-11e6-809f-c3fc04a17175.png)

**Comment by hpvb** [comment]
Could you explain a bit what you are expecting and what the actual behavior is? Thank you!

**Comment by bojidar-bg** [comment]
Uhm, probably your node is rotated, that's why. We don't convert the selected rectangle to an axis-aligned rectangle, but we just rotate it.

**Comment by mefihl** [comment]
Sorry, I have not seenit is rotated.
