### ISSUE TITLE
Script search text match highlight persisting

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#77998]
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Windows 11, AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx     2.10 GHz

### Issue description

  When searching for text in a script, if you switch to another script and then close the search bar, the original script (when you switch back to it) still has the highlighted search matches.  The only way to remove them is to open the search bar and close it again which resets it.  This can be fixed with a buffer history that is maintained when performing search matches until either the search text changes or the search bar is closed, at which point, the buffer can be traversed and the recorded scripts can have set_search_text () executed on them to reset their matched highlights, the buffer history cleared and the process continues, etc.

### Steps to reproduce

Invoke the search bar in a script.
Type in text to search for.
Switch to another script.
Close the search bar.
Switch back to the original script.

### Minimal reproduction project

N/A

**Comment by kitbdev** [comment]
- fixed by https://github.com/godotengine/godot/pull/93056
