### ISSUE TITLE
close editor will not kill adb process

### ISSUE THREAD

**Issue by crasy1** [godotengine/godot#77996]
### Godot version

Godot v4.1.beta.mono (72b59325c) 

### System information

Godot v4.1.beta.mono (72b59325c) - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Laptop GPU (NVIDIA; 31.0.15.3598) - 12th Gen Intel(R) Core(TM) i7-12700H (20 Threads)

### Issue description

open a godot project,editor will open adb process for this project ,but when i close editor,adb process will not be killed.then, project directory is locked

### Steps to reproduce

1.create new project 'test'
2.open in editor
3.close editor
4.find adb.exe in task manager

### Minimal reproduction project

N/A

**Comment by crasy1** [comment]
@https://github.com/AThousandShips it's enabled

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/47804.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/47804.
