### ISSUE TITLE
4.1 `Failed to load cached shader, recompiling.` when no `--path` parameter

### ISSUE THREAD

**Issue by rakkarage** [godotengine/godot#77990]
### Godot version

v4.1.beta.custom_build [72b59325c]

### System information

Windows 11, Core i5-12400F, RX 6600

### Issue description

I was able to build usable versions of 4.1 last week...
But recently (or few days ago maybe) get this error when running it with NO `--path` param.
Godot does not open the window asking you to open a project. Just quits.

> WARNING: Failed to load cached shader, recompiling.
>      at: ShaderGLES3::_load_from_cache (drivers\gles3\shader_gles3.cpp:577)

Sorry if doing something wrong or already exists.

Get this in godot console when loaded too idk if related...

> W 0:00:00:0133   VulkanContext::_debug_messenger_callback: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
> 	Layer name GalaxyOverlayVkLayer does not conform to naming standard (Policy #LLP_LAYER_3)
> 	Objects - 1
> 		Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 2661316882464
>   <C++ Source>   drivers\vulkan\vulkan_context.cpp:264 @ VulkanContext::_debug_messenger_callback()
> 
> W 0:00:00:0144   VulkanContext::_debug_messenger_callback: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
> 	Layer name GalaxyOverlayVkLayer_VERBOSE does not conform to naming standard (Policy #LLP_LAYER_3)
> 	Objects - 1
> 		Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 2661316882464
>   <C++ Source>   drivers\vulkan\vulkan_context.cpp:264 @ VulkanContext::_debug_messenger_callback()
> 
> W 0:00:00:0155   VulkanContext::_debug_messenger_callback: GENERAL - Message Id Number: 0 | Message Id Name: Loader Message
> 	Layer name GalaxyOverlayVkLayer_DEBUG does not conform to naming standard (Policy #LLP_LAYER_3)
> 	Objects - 1
> 		Object[0] - VK_OBJECT_TYPE_INSTANCE, Handle 2661316882464
>   <C++ Source>   drivers\vulkan\vulkan_context.cpp:264 @ VulkanContext::_debug_messenger_callback()
> 

### Steps to reproduce

- build 4.1
- F5 works fine cus uses `--path`
- double click execuable in bin folder or run from terminal without `--path`

### Minimal reproduction project

n/a

**Comment by clayjohn** [comment]
@rakkarage Can you confirm that you built with a version that includes https://github.com/godotengine/godot/pull/77985? Also note, https://github.com/godotengine/godot/pull/77985 was not in beta 1. You need to build with a something from the last 8 hours or so

**Comment by rakkarage** [comment]
Sorry. Fixed. Thanks. I had updated right before I posted.

**Comment by clayjohn** [comment]
Okay, since it is fixed I will go ahead and close this issue

**Comment by felipefacundes** [comment]
I'm using Godot 4.1.3:

WARNING: Failed to load cached shader, recompiling.
     at: _load_from_cache (drivers/gles3/shader_gles3.cpp:577)
