### ISSUE TITLE
Loading X509CertificateMbedTLS failing at editor/project startup

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#77994]
### Godot version

72b59325cf7beba7e6e9170cf6023a079fd58672

### System information

Windows 11, 22H2

### Issue description

There is an error emitting at editor and project startup: 
![image](https://github.com/godotengine/godot/assets/3036176/18062a93-3243-410e-8fb3-645dea184aea)

Looks like a regression after https://github.com/godotengine/godot/pull/76836, (it's happening on Windows after instalment by default). There should be a way to fix it, either by disable that error or providing a link where that certificate can be downloaded and installed.

### Steps to reproduce

Simply run any project or editor.

### Minimal reproduction project

No need, too easy to reproduce.

**Comment by Faless** [comment]
Seems like this is a case similar to what prompted #77063 , i.e. one of the certificates retrieved from the cert store is being skipped (probably because it uses weak or unsupported crypto),
Maybe we should simply remove the error (and make it a `print_verbose`)?

**Comment by tomelsj** [comment]
Same problem in commit c0d8d91b15597209a1ca865c6ff4f84f06f7de86, can I just comment out line 163 in crypto_mbedtls.cpp?

**Comment by frankhale** [comment]
I'm still seeing this problem. I just upgraded to 4.1 RC1:

![image](https://github.com/godotengine/godot/assets/190154/1dcffff9-ecb4-4dff-9f45-555bd369f7f3)

**Comment by akien-mga** [comment]
The fix was merged after the RC 1 commit, it should be included in RC 2 / stable.
