### ISSUE TITLE
BoneMap Overwrite Axis breaks mesh bind poses in converted FBX

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#77995]
### Godot version

4.1.dev 0a0132c - also present in 4.0 but broken slightly differently

### System information

Godot v4.1.dev (0a0132ccf) - Windows 10.0.19044 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3090 () - Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 Threads)

### Issue description

Selecting a BoneMap during import should have no visual impact on the imported mesh. However, the Overwrite Axis option (selected by default, and required for effective cross-model retargeting) seems to be visually breaking these models.

The attached project has converted FBX files (90 degree rotation, 100 scale) from KenneyNL

![image](https://github.com/godotengine/godot/assets/39946030/2534e27b-99da-4de1-88b9-8dea3dd5eac9)

Diasbling Overwrite Axis makes the imported model work.

### Steps to reproduce

1. open the attached project
2. note that the two models look different
3. the model not at origin is the same gltf but imported with BoneMap default settings.

### Minimal reproduction project

[fbx_conversion_retarget_broken.zip](https://github.com/godotengine/godot/files/11685705/fbx_conversion_retarget_broken.zip)

**Comment by fire** [comment]
@TokageItLab Can you check on this?

**Comment by TokageItLab** [comment]
As I mentioned in Contributors chat, those models seem to be broken to begin with.

These models are not displaying the SkeletonGizmo correctly, and the correct visual angles are impossible to calculate because the visual angles inferred for the reatrget are calculated the same way as for the gizmo. I think some rest related value is broken.

**Comment by fire** [comment]
Maya and FBX are allowed to have missing rests.

**Comment by lyuma** [comment]
I am able to reproduce it from a blender export. here is the .blend and the exported .gltf (embedded)

[fbx2gltf_01.blend.zip](https://github.com/godotengine/godot/files/11699566/fbx2gltf_01.blend.zip)
[blender_reexport.gltf.txt](https://github.com/godotengine/godot/files/11699570/blender_reexport.gltf.txt)
