### ISSUE TITLE
Loading plugins via editor settings tab does not work

### ISSUE THREAD

**Issue by thepipecat** [godotengine/godot#78]
When access **Editor Settings**, tab **Plugins** and try to **Load** some did not work, nothing happens.

**Comment by trollworkout** [comment]
i can confirm 1.1 july osx yosemite same issue

**Comment by akien-mga** [comment]
Is this issue still valid in the current master branch?

**Comment by trollworkout** [comment]
@akien-mga  still an issue with latest beta osx el capitan

**Comment by akien-mga** [comment]
Thanks. @calumk's comment hints that the issue might not be platform-specific, but I'll test on Linux asap to confirm it.

**Comment by akien-mga** [comment]
I can confirm this issue too on Linux, the "Load" button just doesn't do anything. If plugins are installed manually by putting them in ~/.godot/plugins/<some folder>, they however work just fine.

**Comment by neikeq** [comment]
What is the _"Load.."_ button supposed to do? Should it search for a plugin.cfg in file dialog and copy that folder to the godot's plugin directory?

**Comment by akien-mga** [comment]
> What is the "Load.." button supposed to do? Should it search for a plugin.cfg in file dialog and copy that folder to the godot's plugin directory?

That's what I would expect it to do yes. Hopefully there is still some code around that is supposed to do that, but which for some reason is not triggered when clicking "Load..".

**Comment by akien-mga** [comment]
Moving to 2.1 milestone as it's not that "junior" finally and we want to release 2.0 asap. What could be done for 2.0 is to temporarily disable the non-functional load button though.

**Comment by akien-mga** [comment]
@neikeq I guess we could fully remove this code now that plugins are project-specific?

**Comment by neikeq** [comment]
I would rather wait until we confirm global editor plugins will not be supported any more (check this comment: https://github.com/godotengine/godot/issues/2537#issuecomment-220592345).

**Comment by akien-mga** [comment]
Moving to next milestone, as 2.1 won't have global plugins, only project-specific.

**Comment by bojidar-bg** [comment]
What's the status here?

**Comment by akien-mga** [comment]
Alright, let's get rid of that commented out code (7594e963) and be done with this issue. *If* we want to readd support for editor-wide plugins, the UI to handle them would likely be quite different anyway.
