### ISSUE TITLE
ERROR: get_child_count: Caller thread can't call this function in this node.

### ISSUE THREAD

**Issue by Hanshattori** [godotengine/godot#78002]
### Godot version

Godot v4.1.beta1

### System information

Ubuntu 20.04.5 LTS (Focal Fossa) - Vulkan (Forward+) 

### Issue description

Hello, 

I just tried to migrate my project from 4.0.3 stable to 4.1 beta and I have a very similar looking problem to the issue #77780, but the solution does not work for me and there is also the thread error. 

![error](https://github.com/godotengine/godot/assets/59332707/1896cd9c-7d4e-4ddd-b3ed-17e8669b5d97)

Solution in the linked issue was to add the reference to the skeleton, but this was there all the time in my case. This is for a project going back to 4.0 alphas and upon upgrading all characters are locked in place with just the animation playing. Characters and bonemap are from Mixamo. I am not using threads anywhere in the project.  I am not calling get_child_count anywhere in the project. 

### Steps to reproduce

"N/A" 

### Minimal reproduction project

"N/A" 

Complex project, unable to reproduce the issue with minimal reproduction project.

**Comment by AThousandShips** [comment]
You need to set up thread safety for your nodes in 4.1, see [here](https://docs.godotengine.org/en/latest/classes/class_node.html#class-node-property-process-thread-group)

**Comment by Hanshattori** [comment]
Everything is set at default (inherit) so as per documentation it should then be in a main thread with group order 0. 

Few more information :
-  All other scenes seem to be fine, SplashScreen, Startscreen, Loading Screen, Options, GUI, simulation control, other actors, just the characters are locked in place. 
- All functions of the locked characters seem to be fine, process delta running and AnimationPlayer OK and running animations.
- Remote scene tree seems fine.
- Not messing with threads. 
- I tried disabling the Thread Model Avoidance in Navigation Project Setting and nothing changed. The same with other thread project and editor settings.
- Project was updated with every 4.0 beta and I just skipped the 4.1 Dev versions - this error only happens in 4.1.beta

**Comment by AThousandShips** [comment]
Then it sounds like a threading bug probably in the editor, the skeleton plugin possibly

**Comment by AThousandShips** [comment]
Yes this is probably due to a threading bug in the editor, unsure what or why

**Comment by Hanshattori** [comment]
I tested with 4.1 Stable and the issue seems to be solved. 

There is a new problem with baking NavigationMesh3D at a runtime which is extremely slow to the point of stopping the simulation for a second, but I do not think it is related to this issue and I will open a new issue if unable to resolve with further research.
