### ISSUE TITLE
(C#) SetMultiplayerAuthority is an int instead of a long

### ISSUE THREAD

**Issue by CodeDoctorDE** [godotengine/godot#78011]
### Godot version

4.1.beta.1

### System information

Fedora 38

### Issue description

When using the default peer ids all are `long`.
But when using Node#SetMultiplayerAuthority it wants to have an int

### Steps to reproduce

Try to type `SetMultiplayerAuthority` in C#

### Minimal reproduction project

There is nothing to debug.
There should be something wrong with the c# class generator.

**Comment by AThousandShips** [comment]
It's an `int` parameter in the API, so that's correct, where are the peer IDs coming from that are `long`?

**Comment by CodeDoctorDE** [comment]
Oh I see.
But why has these methods an id of type long
```
- ENetMultiplayerPeer#PeerConnected
- ENetMultiplayerPeer#PeerDisconnected
- MultiplayerAPI#PeerConnected
- MultiplayerAPI#PeerDisconnected
```

**Comment by AThousandShips** [comment]
Probably because the API doesn't support different sized INT, the bindings `int` is `int64_t`

**Comment by CodeDoctorDE** [comment]
But are these peer ids not the same?

**Comment by AThousandShips** [comment]
They will probably never larger than valid `int32_t`, so it's safe afik

**Comment by CodeDoctorDE** [comment]
Then why not decide on one type of peer id?
It's a bit confusing to use different ones?
Should I cast them to ints when settings setmultiplayerAutority?

**Comment by AThousandShips** [comment]
> Probably because the API doesn't support different sized INT, the bindings int is int64_t

This

I don't know how C# works

**Comment by CodeDoctorDE** [comment]
Then the bindings should be changed?
I don't see an advantage to have multiple types for peer ids

**Comment by AThousandShips** [comment]
You're missing the point, the signal bindings are unable to handle different types of `INT`, it's always `long`

`SetMultiplayerAuthority` can't be changed without breaking compatibility, that's not desired

While I get this is a confusing thing, but this isn't really a reason to make this kind of change

It's a limitation of the bindings system

**Comment by CodeDoctorDE** [comment]
Hmm okay, should we keep this issue open?
Maybe this can be fixed/changed in the future

**Comment by AThousandShips** [comment]
I mean I don't think this is a bug, the sending of a `long` is fully valid, as long as it'll never be an invalid `int`, which it doesn't look like in the code

It being a different type is annoying sure, but it doesn't really qualify as a bug, at least not enough to justify breaking compat

**Comment by CodeDoctorDE** [comment]
Okay, maybe I will add then this "confusion" to the proposal repo

**Comment by raulsntos** [comment]
In C#, methods will use `int` or `long` as specified by ClassDB. So if the C++ method uses a 32-bit int we will use `int`, and if it uses a 64-bit int we will use a `long`.

Signals don't have this information, so we always assume it's a 64-bit int to make sure it fits. In this case, if the peer ID is always a 32-bit int it's safe to cast it to `int`.

Changing how signals are generated would indeed break compatibility. 

This issue sounds like a duplicate of https://github.com/godotengine/godot/issues/75396 which was a duplicate of https://github.com/godotengine/godot/issues/65749. So closing as a duplicate.

**Comment by CodeDoctorDE** [comment]
Oh okay sorry, i searched for multiplayer autority
