### ISSUE TITLE
Add node in AnimationTree (additive animation) not posing correctly 

### ISSUE THREAD

**Issue by Mikeysax** [godotengine/godot#78023]
### Godot version

Godot_v4.1-dev3_win64

### System information

Windows 11 Version 22H2, AMD Ryzen 7 6800H, AMD 6700M, Drivers 23.3.2

### Issue description

When applying additive animations, the arms do not pose correctly but the animation works by itself. 

It almost appears like left and right arms are switched.

This is the correct pose in blender:

<img width="305" alt="Screenshot 2023-06-07 075555" src="https://github.com/godotengine/godot/assets/15805689/50bf873c-a2c4-4db6-96cf-374f24ce3255">

This is what happens in Godot when applying the additive animation:

https://github.com/godotengine/godot/assets/15805689/0cf96525-160e-492d-98ac-660c2274e077

I debugged this and the polls are correct on the bones that are being affected in Godot:

![image](https://github.com/godotengine/godot/assets/15805689/3d49df07-07f5-404c-8c08-a4ac2230b7a4)

### Steps to reproduce

Apply the additive animation using an Add node to a humanoid skeleton

### Minimal reproduction project

[additive_animation_bug.zip](https://github.com/godotengine/godot/files/11697265/additive_animation_bug.zip)

**Comment by TokageItLab** [comment]
It seems that the additive animation is not extracted correctly. We have recently added Sub2 for this purpose in #76616, please check it.

![image](https://github.com/godotengine/godot/assets/61938263/94693b0d-af27-4551-9067-7dfa8b59e84f)

[additive_animation_bug_fixed.zip](https://github.com/godotengine/godot/files/11701747/additive_animation_bug_fixed.zip)

**Comment by TokageItLab** [comment]
In most cases, Blend + Filter is sufficient. Clear cases where it is needed are when you want to blend based on a pose other than Rest, or when you want the blend to be correct with an amount greater than 1.0.

The purpose of use of Additive Animation is described in its PR (https://github.com/godotengine/godot/pull/76616) and proposal (https://github.com/godotengine/godot-proposals/issues/2700). However, it may be possible to document it in more detail in a separate document.
