### ISSUE TITLE
`Window.request_attention()` on Windows only flashes the taskbar, which may be hidden

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#78030]
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Windows 11, AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx     2.10 GHz

### Issue description

  The request_attention () function on Windows only flashes the taskbar, but what if the taskbar is hidden ?  In display_server_windows.cpp, FLASHW_TRAY is used, when it might be more appropriate to use FLASHW_ALL which flashes both the caption and the tray.

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Please update your issue title to be more descriptive

**Comment by Zentrophy** [comment]
It's stating that the issue is with the request_attention () function that is part of the Window class and an issue on the Windows platform, so what more do you want ?

**Comment by AThousandShips** [comment]
> so what more do you want ?

No need to be agressive

The title doesn't say *what* is wrong, just what thing is having an issue, that's not helpful, it'd be like calling an issue about scripts `Script has error`

**Comment by Calinou** [comment]
What's the behavior on Linux and macOS for comparison? Also, what happens if you use `FLASHW_ALL` while the window is focused?

**Comment by Zentrophy** [comment]
I wanted to create a plugin that once it had enumerated all search text matches for instance, that the window would flash to indicate all had been enumerated, eg. like Notepad++ does.  It shouldn't matter whether the window has the keyboard focus or not because a request for attention can occur for all sorts of reasons.
