### ISSUE TITLE
use ResourceLoader.LoadThreadedRequest in C# will cause some error

### ISSUE THREAD

**Issue by gnenux** [godotengine/godot#78034]
### Godot version

4.0.3.stable

### System information

Windows11 Vulkan API 1.2.0 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1080

### Issue description

Hi, sorry fo my english. 
I use ResourceLoader.LoadThreadedRequest to load some scene inherited from a scene with C# script, will print some error like this:

```
E 0:00:02:0048   Godot.NativeInterop.NativeFuncs.generated.cs:1535 @ void Godot.NativeInterop.NativeFuncs.godotsharp_pusherror(Godot.NativeInterop.godot_string& ): Cannot load script for type 'BaseScene'. Path: 'res://BaseScene.cs'.
  <C++ 源文件>      modules/mono/glue/runtime_interop.cpp:1303 @ godotsharp_pusherror()
  <栈追踪>          Godot.NativeInterop.NativeFuncs.generated.cs:1535 @ void Godot.NativeInterop.NativeFuncs.godotsharp_pusherror(Godot.NativeInterop.godot_string& )
                 GD.cs:351 @ void Godot.GD.PushError(System.String )
                 ScriptManagerBridge.cs:489 @ void Godot.Bridge.ScriptManagerBridge.GetOrLoadOrCreateScriptForType(System.Type , Godot.NativeInterop.godot_ref* )
                 ScriptManagerBridge.cs:748 @ void Godot.Bridge.ScriptManagerBridge.UpdateScriptClassInfo(IntPtr , Godot.NativeInterop.godot_bool* , Godot.NativeInterop.godot_array* , Godot.NativeInterop.godot_dictionary* , Godot.NativeInterop.godot_dictionary* , Godot.NativeInterop.godot_ref* )
                 Godot.NativeInterop.NativeFuncs.generated.cs:154 @ void Godot.NativeInterop.NativeFuncs.godotsharp_internal_reload_registered_script(IntPtr )
                 ScriptManagerBridge.cs:506 @ void Godot.Bridge.ScriptManagerBridge.CreateScriptBridgeForType(System.Type , Godot.NativeInterop.godot_ref* )
                 ScriptManagerBridge.cs:451 @ void Godot.Bridge.ScriptManagerBridge.GetOrCreateScriptBridgeForType(System.Type , Godot.NativeInterop.godot_ref* )
                 ScriptManagerBridge.cs:436 @ void Godot.Bridge.ScriptManagerBridge.GetOrCreateScriptBridgeForPath(Godot.NativeInterop.godot_string* , Godot.NativeInterop.godot_ref* )
```

### Steps to reproduce

1. BaseScene.tscn with BaseScene.cs
2. ChildScene.tscn with ChildScene.cs, ChildScene.tscn  inherited from  BaseScene.tscn and ChildScene.cs  inherited from BaseScene.cs
3. use ResourceLoader.LoadThreadedRequest to load ChildScene.tscn

### Minimal reproduction project

[GodotTest.zip](https://github.com/godotengine/godot/files/11704125/GodotTest.zip)

**Comment by AThousandShips** [comment]
* Related #77886

**Comment by AThousandShips** [comment]
Have you built your scripts?

**Comment by gnenux** [comment]
> Have you built your scripts?

yes, I built it

**Comment by lewiji** [comment]
Can replicate here. Your demo project didn't seem to have the inherited scene/script mentioned, so I added those inherited from the BaseScene scene/script. Yes, I get the same error.

**Comment by gnenux** [comment]
> Can replicate here. Your demo project didn't seem to have the inherited scene/script mentioned, so I added those inherited from the BaseScene scene/script. Yes, I get the same error.
> 
> Edit: did note however that the scene seems to instantiate and execute the child script fine, despite the error about loading the parent script.
> 
> Setting `useSubThreads` to `false` in the threaded load parameters doesn't cause the error.
> 
> I think #74405 may fix this.
> 
> Edit: yes, Godot 4.1 beta 1 (which includes the above PR) doesn't error with useSubThreads set to true.

I test it in Godot 4.1 beta 1. Looks like there's no problem in first run, but the status by ResourceLoader.LoadThreadedGetStatus always in InProgress in rerun.

https://github.com/godotengine/godot/assets/14236891/dd91a609-7e41-482c-8db9-3c8faefa42e3
