### ISSUE TITLE
select by ctrl+d is selecting unwanted text

### ISSUE THREAD

**Issue by Variable-ind** [godotengine/godot#78036]
### Godot version

4.0.3

### System information

Linux Mint 21.1 Cinnamon, Graphics: Intel Corporation HD Graphics 620, Processor: Intel© Core™ i5-7200U CPU @ 2.50GHz × 2

### Issue description

Hy :wave:, i am having a problem... there are a lot of variables/functions in the script that share some piece of word
e.g `variable` and `another_variable` both share the part (variable) in their name. so when i want to quick select (using Ctrl + d) the `variable` then a part of another_`variable` also gets selected (even though it was not highlighted by the dim white rectangle). i don't want another_`variable` to get selected.

it would be nice if i can change the behaviour of how this selection works in settings
(i-e choose to select if next Occurrence is part of a bigger word or not)

https://github.com/godotengine/godot/assets/77773850/5a38df1e-796b-4c3e-8eb2-2a3ba2055dc1

### Steps to reproduce

Refer to the above video

### Minimal reproduction project

none

**Comment by AThousandShips** [comment]
The shortcut just selects the next occurrence, it doesn't really state that it selects only the word on its own, it's a pretty simple function unfortunately

**Comment by Variable-ind** [comment]
> The shortcut just selects the next occurrence, it doesn't really state that it selects only the word on its own, it's a pretty simple function unfortunately

So it's a feature suggestion then.. :thinking:

**Comment by Variable-ind** [comment]
> Exactly! Open one in [godot proposals](https://github.com/godotengine/godot-proposals), be sure to fill in all the questions, or open a discussion if you don't have a clear idea of the implementation

okay so i've created this discussion: https://github.com/godotengine/godot-proposals/discussions/7049
is this good (i mean i haven't missed anything right?)

**Comment by AThousandShips** [comment]
Looks great! You can go ahead and close this issue
