### ISSUE TITLE
2D Sprites rendered black with enabled Y-sorting

### ISSUE THREAD

**Issue by theMotionblur** [godotengine/godot#78035]
### Godot version

v4.1.beta1.official [828ec2c5d]

### System information

Windows 11 Home, v4.1.beta1.official [828ec2c5d], All Renderers, NVidia GeForce RTX 3060 Ti,  Drivers 535.98

### Issue description

When enabling the "Y Sort Enabled" ordering method for a Sprite2D, the sprite will be rendered entirely black.

![grafik](https://github.com/godotengine/godot/assets/29011290/6fa4da16-d9a5-4c3b-a9e4-c1bba53c2183)
![grafik](https://github.com/godotengine/godot/assets/29011290/cbf499ae-f3f7-4c07-98b2-a1a667d810c2)

### Steps to reproduce

Simply create a Sprite2D Node, assign any texture to it and activate Y-Sorting

### Minimal reproduction project

[GDB_4.1_ysort.zip](https://github.com/godotengine/godot/files/11704361/GDB_4.1_ysort.zip)

**Comment by clayjohn** [comment]
Could be a regression from https://github.com/godotengine/godot/pull/77079

**Comment by Isenther** [comment]
I was gonna open an issue as well, but saw that it had already been opened, looking forward to seeing this being fixed.

**Comment by akien-mga** [comment]
> Could be a regression from #77079

CC @kleonc
