### ISSUE TITLE
GraphNode doesn't handle expand flag

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#7804]
All

**Operating system or device - Godot version:**

Linux, current master

**Issue description:**

GraphNode doesn't take the expand flag of it's children (SIZE_EXPAND) into account.
Instead, it behaves as if horizontal expand is enabled and vertical fill is disabled for children.

**Steps to reproduce:**

Add any UI component under GraphNode and turn on expand flags.

**Link to minimal example project:**
:

**Comment by reduz** [comment]
yeah this is expected, to expand you need to have room for expanding. There
is no such room in a GraphNode.

**Comment by tagcup** [comment]
There's actually plenty of room to expand:

![screenshot_20170213_202450](https://cloud.githubusercontent.com/assets/16531565/22912340/84fe2df4-f22a-11e6-9cfd-9dbf6a9386fb.png)

Same goes for the Container node (which GraphNode inherits from) BTW, it ignore expand.

**Comment by reduz** [comment]
ah i see, will check that out eventually

**Comment by bojidar-bg** [comment]
@tagcup Container is expected to ignore expand, but subclasses of Container must handle it :smiley:

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by kubecz3k** [comment]
@tagcup do you know maybe what's the status of this issue?

**Comment by tagcup** [comment]
Nope, it's probably as-is, because there is nothing in the git history of scene/gui/graph_node.cpp indicating a fix

**Comment by tagcup** [comment]
Link https://github.com/godotengine/godot/commits/master/scene/gui/graph_node.cpp

**Comment by GlaDOSik** [comment]
I'm trying to show dynamically loaded image in the TextureRect inside the node and I too cannot make it expand vertically.

A fix would be very appreciated as I'm making a graph-based texture editor plugin and having texture previews in nodes is important.

**Comment by khoulihan** [comment]
I have just encountered this bug in 3.0.2, if its status was still unclear. My use case is having a child TextEdit resize with the node to give more room for large amounts of text.

**Comment by Zaraka** [comment]
+1 This issue is present for like 3 years. It's really annoying

**Comment by OniLink** [comment]
This issue still exists for me. Would love to see it fixed.
