### ISSUE TITLE
[PCK Embedding]: Executable file header corrupted - HELP!?

### ISSUE THREAD

**Issue by NordicSpiritEnjoyer** [godotengine/godot#78055]
### Godot version

4.0.3 stable

### System information

Windows 10 Pro

### Issue description

Okay so I'm trying to export my project to windows but I get an error that says [PCK Embedding]: Executable file header corrupted.  I'm using Godot 4.0.3 with no plugins. In my export settings PCK Embedding is turned on. Everything else is set to default. I am using no plugins. I have reinstalled godot and tried to export a fresh and empty project to no avail, same error. If I do not select PCK Embedding it produces a 58mb .pck and an .exe that is 0kb and when run simply tells me that my version of windows doesn't support it. At a total loss any help is useful.

### Steps to reproduce

Export project for windows desktop

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/11708159/test.zip)

**Comment by AThousandShips** [comment]
Can you re-download the export templates to make sure they are not corrupted/broken, what version of the export templates are you using?

**Comment by NordicSpiritEnjoyer** [comment]
I can't believe that i didnt think to just redownload the export templates. Thank you very much hope you have a good one

**Comment by AThousandShips** [comment]
No problems! You have a good one!
