### ISSUE TITLE
AnimationTree(AnimationNodeStateMachine) error reported in the editor

### ISSUE THREAD

**Issue by magian1127** [godotengine/godot#78052]
### Godot version

4.1b

### System information

win11 Vulkan API 1.3.236

### Issue description

Selecting AnimationTree will result in error message 
`This function in this node can only be accessed from either the main thread or a thread group. Use call_deferred() instead.`

### Steps to reproduce

AnimationTree -> ROOT -> AnimationNodeStateMachine ->Add Animation.
There are several animations, clicking AnimationTree will result in several errors

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/11708080/test.zip)

**Comment by magian1127** [comment]
4.1 B2
`This function in this node (/root/@EditorNode@16972/@Control@6/@Panel@7/@VBoxContainer@15/@HSplitContainer@18/@HSplitContainer@26/@HSplitContainer@34/@VBoxContainer@35/@VSplitContainer@37/@PanelContainer@6807/@VBoxContainer@6808/@AnimationTreeEditor@12377) can only be accessed from either the main thread or a thread group. Use call_deferred() instead.`

**Comment by magian1127** [comment]
Error by `animation_tree_editor_plugin.cpp` 224 row
```
Vector<String> AnimationTreeEditor::get_animation_list() {
	if (!singleton->is_visible()) { // this
		return Vector<String>();
	}
```

'is_visible()' triggered `ERR_READ_THREAD_GUARD_V(false)`

**Comment by papezjustin** [comment]
This issue still reproduces in Godot Engine v4.3.stable.official.77dcf97d8 (Win11 - Vulkan 1.3.280).
