### ISSUE TITLE
Collapse All keyboard shortcut does not work

### ISSUE THREAD

**Issue by qxface** [godotengine/godot#78051]
### Godot version

4.0.3 stable

### System information

Windows 10

### Issue description

The "Collapse All" keyboard shortcut does not collapse code. The default is set to Ctrl-M, but I have tried changing the shortcut to other keys, like F4. Other shortcuts work properly, like Ctrl-K to comment a line of code.

### Steps to reproduce

Go to Editor > Editor Settings to check that your Collapse All shortcut has a keycode assigned to it. The default is Ctrl-M.
Open a script with at least one function and make sure one or more functions are fully expanded.
Press the keyboard shortcut to activate the "Collapse All" functionality.
No code collapses.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
The setting for this is "Fold All Lines" under "Script Text Editor", "Collapse All" is for the property editor afik

**Comment by qxface** [comment]
> The setting for this is "Fold All Lines" under "Script Text Editor", "Collapse All" is for the property editor afik

Oh, wow, thanks!
Yes, "Fold All Lines" is what I was actually looking for, and the keyboard shortcut for it works properly.

Thank you!
