### ISSUE TITLE
Sprite shake when camera2d follow the character

### ISSUE THREAD

**Issue by Pnsadeghy** [godotengine/godot#78050]
### Godot version

4.0.3

### System information

Windows 11

### Issue description

I follow my character with Camera 2D and I activate position smoothing on camera.
When Camera follow the character, Character sprite shaking.
Event without smoothing, this will happen.

This is my camera code:

```gdscript
extends Camera2D

@export var following: CharacterBody2D

func _physics_process(delta):
	global_position.x = following.global_position.x
```

**Comment by AThousandShips** [comment]
Have you tried using `RemoteTransform2D`? Or attaching the camera to the character directly?

**Comment by Calinou** [comment]
This is likely not a bug, see https://github.com/godotengine/godot/issues/73347 and https://github.com/godotengine/godot-proposals/issues/6389.

**Comment by WhalesState** [comment]
please confirm if setting `snap 2d transforms to pixel` and `snap 2d vertices to pixel` enabled still produce this issue.
![image](https://github.com/godotengine/godot/assets/53877170/6109f6fb-b35f-4180-be77-a298bbbd60a6)

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide more information or an MRP this can be reopened
