### ISSUE TITLE
Some things don't work on paint properties inside a Tileset (Android)

### ISSUE THREAD

**Issue by SniperCooper101** [godotengine/godot#78068]
### Godot version

v4.1.beta1.official [828ec2c5d]

### System information

Android 10 - Motorola One (P30 play) - 8x ARM Cortex-A53 @ 2.02 GHz

### Issue description

This bug is in the current version of the playstore until the most recent beta published, I have another device with similar specs and the same thing happens.

When you add a Tilemap and then add a tileset, it's obvious that you're going to want to add hitboxes and things like that, but there's a bug that means that for some reason the other categories can't be opened on the "paint" option

### Steps to reproduce

https://github.com/godotengine/godot/assets/92269010/c6310691-87bd-458b-a22e-e203d2cf4727

![Screenshot_20230609-213754~2](https://github.com/godotengine/godot/assets/92269010/8e94b01a-273b-4e99-a50d-3cc11f6388fc)

Add a Tilemap and then add a Tileset

In the tileset add a texture and after that select the option "paint", as you can see for some reason some things actually don't work

For better understanding, attach a video and an image where the error can be clearly seen

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Have you added a physics layer to the tileset?

**Comment by AThousandShips** [comment]
For support questions and help please first turn to the other [community channels](https://godotengine.org/community), this is for bug reporting, not a help desk.

**Comment by Zireael07** [comment]
I seem to recall this UX problem being raised before but I can't find the # now

**Comment by AThousandShips** [comment]
* Duplicate of #75592

Indeed
