### ISSUE TITLE
Impossible to start text selection on unfocused SpinBox

### ISSUE THREAD

**Issue by floppyhammer** [godotengine/godot#78079]
### Godot version

v4.1.beta.custom_build [d3651ea45]

### System information

Windows 11

### Issue description

![1](https://github.com/godotengine/godot/assets/28705694/15c14c93-7ad7-425a-8fb0-bef841b75527)

It's not possible to start text selection on a SpinBox when it's unfocused.

Note: After a bit of digging in the code, I found that clicking on a SpintBox doesn't trigger `SpinBox::gui_input` no matter if it's focused or not. However, releasing mouse left button does trigger the function.

### Steps to reproduce

See the gif.

### Minimal reproduction project

It's simple to reproduce.

**Comment by Sauermann** [comment]
`SpinBox::_line_edit_focus_enter` gets called when the LineEdit of the SpinBox receives focus and during that the drag-selection gets canceled.
Bisecting lead to #64529

**Comment by floppyhammer** [comment]
I confirm SpinBox in 3.x has the same issue, probably due to the cherry-pick of https://github.com/godotengine/godot/pull/64529.

**Comment by Calinou** [comment]
cc @KoBeWi

**Comment by KoBeWi** [comment]
You can select all with double click. There is also `select_all_on_focus` property.

The "regression" was mentioned in the PRs caveats 🙃 I'll see if it can be improved.
