### ISSUE TITLE
_build ()  not being called for plugins.

### ISSUE THREAD

**Issue by Zentrophy** [godotengine/godot#78073]
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Windows 11, AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx     2.10 GHz

### Issue description

  The documentation states that the _build () virtual function through EditorPlugin is called just before a project runs, but in my experience this doesn't happen.  Looking at the source, there is a EditorPlugin::build() method, however, it doesn't seem to be called anywhere in the source.

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Please provide an MRP so we can see the full setup of your issue
