### ISSUE TITLE
Editor main-screen mode.

### ISSUE THREAD

**Issue by Zentrophy** [godotengine/godot#78071]
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Windows 11, AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx     2.10 GHz

### Issue description

  There is an EditorInterface::set_main_screen_editor () function and a "main_screen_changed" signal via EditorPlugin, but there doesn't seem to be a way to retrieve the current "main-screen" mode, and the signal only gets emitted when the mode is actually changed.  For plugins this is useful information, but the only way I've found to do this is to enumerate the Editor buttons for these "modes" and determine which one is "pressed".  Could you consider adding a function or some property through EditorSettings that exposes this information ?

  Furthermore, on this topic, there doesn't seem to be a way to specify what the initial "main-screen" mode is when the Editor starts.  I thought this would be a command-line option, but none exists.  Looking at the source I see that a "selected_main_editor_idx" section-key in the Editor configuration file is referred to for doing this, but adding the key (which doesn't exist by default) to the configuration file is just ignored.

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
For support questions and help please first turn to the other [community channels](https://godotengine.org/community), this is for bug reporting, not a help desk. If there's no way to do this currently this is feature proposal territory, so please open one instead over [here](https://github.com/godotengine/godot-proposals), be sure to follow all the instructions.

**Comment by KoBeWi** [comment]
There is a `get_editor_main_screen()` method in EditorInterface, I think you can iterate its children and determine current screen by whatever is visible.

As said above, if you want new function added, open a proposal
