### ISSUE TITLE
Editor defined shortcut access via script.

### ISSUE THREAD

**Issue by Zentrophy** [godotengine/godot#78072]
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Windows 11, AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx     2.10 GHz

### Issue description

  Is there a way of retrieving the Editor shortcut values stored in the "command palette" ?  Only functions that modify are available, none to query the contents ?  I see in the source that there is a is_shortcut () method via the EditorSettings singleton that can do this, but it isn't exposed.  For plugins that use shortcuts, access to this information ensures they can be updated when the user makes changes in this regard.

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
For support questions and help please first turn to the other [community channels](https://godotengine.org/community), this is for bug reporting, not a help desk.

**Comment by Zentrophy** [comment]
Actually is_shortcut () tests an InputEvent against a shortcut, eg. "Script Editor/Find" which is exactly what I want.  As for get_editor_interface ().get_editor_settings ().shortcuts, I can't find that anywhere.  No mention in the documentation.

**Comment by AThousandShips** [comment]
Yes, but you asked about retrieving it, and `is_shortcut` doesn't do that, I'm sorry but you asked for a specific thing and I responded to that specific thing, namely to retrieve shortcuts 

I know, but it is a property, and I asked if you could test if it works as I'm not by my computer atm

**Comment by Zentrophy** [comment]
I only wanted to retrieve the property to test against an InputEvent, eg.  in _shortcut_input () or one of the other _input () type functions.  I tried what you suggested and an error is issued because no "shortcut" property exists.  You may be getting confused with the "Shortcuts" TAB in the Editor Settings dialog in the Editor which lists the shortcuts.  I just want to test an InputEvent against an Editor shortcut in script.

**Comment by AThousandShips** [comment]
No I'm not confusing anything here, I'm talking about a property that exists in this class but not sure if it's accessible in GDScript, try also `get("shortcuts")`

Then this is probably best served by a proposal to add this functionality to the engine, go ahead and open one if you like, because missing functionality isn't a bug as such

**Comment by Zentrophy** [comment]
That returns a dictionary with some shortcuts.  Thankyou very much.  Might be a good idea to put that in the documentation.

**Comment by AThousandShips** [comment]
Agreed, but still room for improvement, so feel free to open a proposal

**Comment by AThousandShips** [comment]
This can probably be closed, and a proposal opened for the desired features

**Comment by Zentrophy** [comment]
Looking forward to an implementation that provides access to all the Editor shortcuts because get ("shortcuts") only provides 3 shortcuts for some reason and of course, none of which I need for what I am doing.  I'll just have to piggyback on another control that uses the shortcut I want until then...
