### ISSUE TITLE
Raycast3D does not work in Beta 4.1

### ISSUE THREAD

**Issue by macryc** [godotengine/godot#78077]
### Godot version

4.1 Beta 1

### System information

Win 10, RTX 2070 mobile

### Issue description

Raycast3D does not detect collisions with bodies.

### Steps to reproduce

1. Start a new 3d scene
2. create a static body 3d with a collision shape
3. create a Raycast3d and point it towards the static body so that it intersects with it
4. enable Raycast3D and make sure it's set to collide with bodies
5. In _process() say: print("is colliding) if raycast.is_colliding() else print("not colliding').
6. Run the scene and it prints 'not colliding' even though it definitely is colliding 

### Minimal reproduction project

not needed, takes 30 secs to do the steps above

**Comment by AThousandShips** [comment]
Please upload an MRP to make this easier to investigate, to see if this is a bug or an issue with configuration
> A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the .godot folder in the archive (but keep project.godot).
> Required, unless the reproduction steps are trivial and don't require any project files to be followed. In this case, write "N/A" in the field.
> Drag and drop a ZIP archive to upload it. Do not select another field until the project is done uploading.

**Comment by macryc** [comment]
[raycast41.zip](https://github.com/godotengine/godot/files/11711950/raycast41.zip)

**Comment by Sauermann** [comment]
I have tested the MRP with v4.1.beta.custom_build [9723077f4] and can't reproduce:
```
./bin/godot.linuxbsd.editor.dev.x86_64.llvm --path /tmp/raycast41
Godot Engine v4.1.beta.custom_build.9723077f4 - https://godotengine.org
Vulkan API 1.2.175 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 2070
 
is colliding
is colliding
is colliding
[...]
```

Looking at the script, it should be noted, that the collision-detection doesn't work, when it is used as an editor-extension. It would be best to update the initial description to include this detail.
``` gdscript
@tool
extends RayCast3D

func _process(delta):
	print("is colliding") if is_colliding() else print("not colliding")
```

**Comment by macryc** [comment]
Interesting. You're right, it does work in runtime. But something's clearly changed with raycasts in 4.1 that is causing issues in my 4.0 projects. Eg, when I say: if raycast.is_colliding(): raycast.get_collider().something, I get an error saying that there is no collider (ie, that it's null), which is baffling because how can there be no collider if the condition is_colliding() has just been met...

Suppose this one can be closed until I find out what the real issue is.

**Comment by AThousandShips** [comment]
There *are* valid conditions where the collider *object* is not present but collision occurs, as it depends on `get_instance_id` which is allowed to be empty, but this would need some more specific information on when it is happening

**Comment by fracteed** [comment]
> Interesting. You're right, it does work in runtime. But something's clearly changed with raycasts in 4.1 that is causing issues in my 4.0 projects. Eg, when I say: if raycast.is_colliding(): raycast.get_collider().something, I get an error saying that there is no collider (ie, that it's null), which is baffling because how can there be no collider if the condition is_colliding() has just been met...
> 
> Suppose this one can be closed until I find out what the real issue is.

@macryc I am also running into this issue in a large project with many enemies. The frustrating this is that is a very intermittent error, so is almost impossible to reproduce. I have several levels or error trapping to check for null but still get this error randomly. Something did change in 4.1 related to raycasts, as I never had it in previous versions.

Did you ever come to any solutions to work around this?
