### ISSUE TITLE
Enable "View FPS" increases CPU usage

### ISSUE THREAD

**Issue by dn-omar** [godotengine/godot#78086]
### Godot version

3.5.2.stable Linux , 3.5.2.stable web editor , 3.6.beta2 Android

### System information

Laptop Bodhi Linux (Ubuntu 20.04.2 LTS (Focal Fossa)) CPU Intel Celeron B815 ,and Nokia phone Android 11 

### Issue description

enable "View FPS" increases CPU usage, and CPU cores to the max ,

the same Issue in "godot Linux" and "godot Android" and  "godot web editor".

videos of the Issue:
Laptop Linux , [https://youtu.be/4Nehw8YLekg](https://youtu.be/4Nehw8YLekg)
Android phone , [https://youtu.be/nCRGVYnJGfc](https://youtu.be/nCRGVYnJGfc)

sorry if this is not a problem, im new in Godot , and sorry im not good in english

### Steps to reproduce

Perspective > View FPS 

### Minimal reproduction project

the Issue is in any Godot project

**Comment by Calinou** [comment]
Enabling View FPS causes the editor viewport to redraw continuously (so that the measurement can be somewhat accurate), so this is expected.
