### ISSUE TITLE
4.1 `@tool` gets wrong `get_viewport_rect().size`

### ISSUE THREAD

**Issue by rakkarage** [godotengine/godot#78089]
### Godot version

v4.1.beta.custom_build [e188d6192]

### System information

Windows 11, Core i5-12400F, RX 6600

### Issue description

	@tool
	extends Control

	const _r := PI / 2.0

	func _ready() -> void:
		get_parent().connect("resized", _onResized)
		_onResized()

	func _onResized() -> void:
		var tex := size
		var win := get_viewport_rect().size
		print("tex: ", tex, " win: ", win)
		if win.x > win.y:
			rotation = _r
			scale = Vector2(win.y / tex.x, win.x / tex.y)
		else:
			rotation = 0
			scale = Vector2(win.x / tex.x, win.y / tex.y)

in editor, not work, wrong size:
tex: (768, 1024) win: (1492, 697)
![2023-06-10](https://github.com/godotengine/godot/assets/962340/d91d84c9-6cfa-416c-aa2b-92dee8efa580)

running, works, right size:
tex: (768, 1024) win: (1152, 648)
![2023-06-10 (1)](https://github.com/godotengine/godot/assets/962340/3ef0d09b-fda3-4cbe-9409-fe11a22af519)

- I am kinda just faking the _onResize for tool mode by calling it from _ready
- I tried `func _ready() -> void: call_deferred("_readyDeferred")`
- I tried defer call to resize...
- Pretty sure it worked in 3.x

### Steps to reproduce

- print or use size from @tool

### Minimal reproduction project

https://github.com/rakkarage/TestBack

**Comment by KoBeWi** [comment]
The viewport size in the editor is the size of the editing area.

https://github.com/godotengine/godot/assets/2223172/8e714142-7ff3-421a-8dd5-7ec0f8f7ab85

It's not a bug.

> Pretty sure it worked in 3.x

It was the same.

**Comment by rakkarage** [comment]
parent is a maxxed control not a viewport
