### ISSUE TITLE
[4.0] Dragging any window (even the editor itself) is not smooth (stuttering)

### ISSUE THREAD

**Issue by Flavelius** [godotengine/godot#78094]
### Godot version

4.1.beta1.mono

### System information

Godot v4.1.beta1.mono - Ubuntu 23.04 23.04 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (nvidia; 525.105.17) - AMD Ryzen 5 2600 Six-Core Processor (12 Threads)

### Issue description

As the title says, dragging the editor window, or any of godot's popped up settings windows is stuttering, making it feel very heavy, as if it's being recreated every update instead of just moved. This is contrasted to any other OS window where dragging does not exhibit this behaviour. 
Kubuntu 23.04, happened since 4.0 and does not happen with internal windows in single window mode where 'windows' are embedded, excluding the editor window itself which still stutters.
Example recording:

https://github.com/godotengine/godot/assets/8841352/d7fe47db-8621-465c-a4e8-f602774f5b66

### Steps to reproduce

Unrelated to projects; as the description says just dragging any of those windows around is enough.

### Minimal reproduction project

unrelated to any project

**Comment by KoBeWi** [comment]
Duplicate of #39222?

**Comment by Flavelius** [comment]
The example video in that issue itself is stuttering, so i can't judge it. And even though i'm not on gnome, it's very similar to another duplicate linked in this issue: https://github.com/godotengine/godot/issues/63788
So, yes a duplicate (haven't found those when searching 'window drag stutter' before)
