### ISSUE TITLE
Segfault when adding RayCast2D Node

### ISSUE THREAD

**Issue by d-j-a-y** [godotengine/godot#7810]
**Operating system or device - Godot version:**
Debian Jessie - Godot 3.0 : 78336990f4

**Issue description:**
Segfault : Adding RayCast2D Node

**Steps to reproduce:**
* Open linked project 
* Add RayCast2D Node (has root / has child / has you wich .... , you can even before remove the wall nodes)
* Segfault

**Stacktrace**
```
0	RasterizerCanvasGLES3::_draw_gui_primitive	rasterizer_canvas_gles3.cpp	390	0x70e6b8	
1	RasterizerCanvasGLES3::_canvas_item_render_commands	rasterizer_canvas_gles3.cpp	634	0x70fdf6	
2	RasterizerCanvasGLES3::canvas_render_items	rasterizer_canvas_gles3.cpp	1011	0x70ac65	
3	VisualServerCanvas::render_canvas	visual_server_canvas.cpp	191	0x1369b31	
4	VisualServerViewport::_draw_viewport	visual_server_viewport.cpp	214	0x13fb48f	
5	VisualServerViewport::draw_viewports	visual_server_viewport.cpp	266	0x13fb69c	
6	VisualServerRaster::draw	visual_server_raster.cpp	99	0x1328a6b	
7	Main::iteration	main.cpp	1632	0x42de6e	
8	OS_X11::run	os_x11.cpp	1962	0x40ffb3	
9	main	godot_x11.cpp	41	0x4084b1	


```
**Project:**
[Segfault_Adding_RayCast2D_Node.zip](https://github.com/godotengine/godot/files/774777/Segfault_Adding_RayCast2D_Node.zip)

**Comment by bojidar-bg** [comment]
Can confirm with other shapes such as capsuleshapes.

**Comment by akien-mga** [comment]
Is this still valid in the current master branch?

**Comment by bojidar-bg** [comment]
Can't confirm crashes with near-current master... So, closing.

Some shapes are still not drawing at all, but we have other issues for that.
