### ISSUE TITLE
4.1.beta1, mouse-over slider shows offset handle highlight

### ISSUE THREAD

**Issue by duianto** [godotengine/godot#78118]
### Godot version

v4.1.beta1.official [828ec2c5d]

### System information

Godot v4.1.beta1 - Windows 10.0.19045 - Vulkan (Compatibility) - GeForce GTX 550 Ti () - Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz (4 Threads)

### Issue description

Issue observed in:
- v4.1.beta1.official [828ec2c5d]

Expected behavior in:
- v4.1.dev4.official [5c2295ff5]
- v4.0.stable.official [92bee43ad]
- v3.5.2.stable.official [170ba337a]

### Description

A sliders mouse-over handle highlight (a circle with a ring around it) appears offset (down and to the right), the first time the mouse is moved over a slider.

![offset](https://github.com/godotengine/godot/assets/13420573/e1be920f-9272-428c-b460-63d4961e32d7)

### Expected
The slider handle highlight, should appear on the sliders handle on the first mouse-over.
As it does in the Godot versions before: 4.1.beta1

![expected](https://github.com/godotengine/godot/assets/13420573/adee6efd-6f70-4785-82af-a875e9ad663c)

### Steps to reproduce

- open the attached project: [issue, mouse over slider, handle highlight, offset.zip](https://github.com/godotengine/godot/files/11714943/issue.mouse.over.slider.handle.highlight.offset.zip)
Node2D is selected, in the Scene panel, and the Transform group/section is unfolded in the Inspector panel.
- move the mouse over the Transform > Rotation, slider

### Observed

The sliders mouse-over handle highlight (a circle with a ring around it) appears offset (down and to the right) from the sliders handle.

The mouse-over handle highlight moves to the slider handle when:
- the mouse is held still over the slider until the tooltip appears
- or if the mouse is moved away from the slider and back over the slider

Now the second and subsequent slider mouse-overs keep showing the handle highlight correctly.

The issue can be reproduced by deselecting and selecting Node2D in the Scene panel.

https://github.com/godotengine/godot/assets/13420573/c817788c-6032-44e0-8693-35801f406c51

### Expected

The sliders mouse-over handle highlight should appear on the sliders handle, the first time the mouse is moved over the slider.

### Minimal reproduction project

[issue, mouse over slider, handle highlight, offset.zip](https://github.com/godotengine/godot/files/11714943/issue.mouse.over.slider.handle.highlight.offset.zip)

**Comment by Sauermann** [comment]
Bisecting leads to #77651

**Comment by RedworkDE** [comment]
Might get fixed by #78009

**Comment by Sauermann** [comment]
Have tested #78009 and can confirm, that it fixes this issue.
