### ISSUE TITLE
ScriptInstanceExtension GDExtensionObjectPtr is no longer readable on Godot Side

### ISSUE THREAD

**Issue by Gallilus** [godotengine/godot#78116]
### Godot version

v4.1.beta

### System information

Windows 10

### Issue description

```
        virtual Ref<Script> get_script() const override {
                if (native_info->get_script_func) {
                        GDExtensionObjectPtr script = native_info->get_script_func(instance);
                        return Ref<Script>(reinterpret_cast<Script *>(script));
                }
                return Ref<Script>();
```
Is not creating a functional reference.

GDExtensionObjectPtr is a part of gdextension_interface and is a void pointer to pas data pointers between GDExtesion and Godot Core.

In the images below you are able to see that the extension `reinterpret_cast `works fine.
And that the pointer is passed to core.
However at core `Ref<Script> script_test` stays a NULL value

![image](https://github.com/godotengine/godot/assets/20573784/d4a955d3-4e02-46e2-abf1-ba88cf501e8f)
![image](https://github.com/godotengine/godot/assets/20573784/42a3fbb8-3598-479a-86bc-8b9464624885)
![image](https://github.com/godotengine/godot/assets/20573784/620782c0-192c-4e14-829c-5817ae680378)

I was hoping this would be solved by solving [cpp 1119](https://github.com/godotengine/godot-cpp/issues/1119)

### Steps to reproduce

Create a custom script instance and create it using `internal::gdextension_interface_script_instance_create` and a `GDExtensionScriptInstanceInfo` that only implements `get_property_list_func` and `get_script_func`.

### Minimal reproduction project

Difficult to create a minimal project.
Mostly looking for advice on what to test to find the actual source problem

**Comment by YuriSizov** [comment]
cc @dsnopek

**Comment by Gallilus** [comment]
Continued my testing. It might be an error when creating the instance.
So ignore the above.
With any luck, I can close this by this weekend.

**Comment by Gallilus** [comment]
https://github.com/godotengine/godot/pull/63712#discussion_r1233120685
https://github.com/godotengine/godot/pull/78392

I hope it is fixed with both of above need to fix several regressions during testing before I'm sure this issue is caused by the bug
