### ISSUE TITLE
FileSystem thumbnails display 2D scene (impressive bug!)

### ISSUE THREAD

**Issue by RayKoopa** [godotengine/godot#7812]
3.0 master

**Issue description:**
Thumbnails are not displayed and instead an upside-down view on the editor 2D scene.
![test](https://cloud.githubusercontent.com/assets/9631152/22951647/3e9504e2-f30a-11e6-979b-2bbc7c3764f7.gif)

This bug exists since several weeks now on Windows 10 x64 (possibly more OSes) so I thought I share it :)

**Steps to reproduce:**
Open any project, see thumbnails getting trashed and your console filled with things like this:
```
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL        Type: Error     ID: 3010        Severity: High  Message: glBlitFramebuffer failed because the framebuffer configurations require that the source and destination formats and sample counts match (GL_INVALID_OPERATION)
   At: drivers\gles3\rasterizer_gles3.cpp:94
REIMPORTING: res://test_dir/.dontseeme.png
mesege
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL        Type: Error     ID: 3010        Severity: High  Message: glBlitFramebuffer failed because the framebuffer configurations require that the source and destination formats and sample counts match (GL_INVALID_OPERATION)
   At: drivers\gles3\rasterizer_gles3.cpp:94
REIMPORTING: res://test_dir/absolutely_hidden.png
mesege
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL        Type: Error     ID: 3010        Severity: High  Message: glBlitFramebuffer failed because the framebuffer configurations require that the source and destination formats and sample counts match (GL_INVALID_OPERATION)
   At: drivers\gles3\rasterizer_gles3.cpp:94
REIMPORTING: res://test_dir/rms.png
mesege
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL        Type: Error     ID: 3010        Severity: High  Message: glBlitFramebuffer failed because the framebuffer configurations require that the source and destination formats and sample counts match (GL_INVALID_OPERATION)
   At: drivers\gles3\rasterizer_gles3.cpp:94
```

Also, if I make the editor window smaller than the "internal minimum size" (or what that is, when it stops resizing the inner contents), everything gets worse:
![untitled 1](https://cloud.githubusercontent.com/assets/9631152/22952201/5a16f5b6-f30c-11e6-8f09-119e95c9fec2.png)

**Comment by Hinsbart** [comment]
I've never seen this using the master branch on linux - so tagging it as a windows bug for now.

**Comment by ni-code** [comment]
I can confirm this on Ubuntu Linux 16.10.
GPU nvidia GeForce GTS 450, using proprietary driver 367.57

**Comment by punto-** [comment]
"impressive bug" should be a new tag, this looks cool :p

**Comment by bojidar-bg** [comment]
@punto- I think "feature" is a good tag for it already :stuck_out_tongue:

**Comment by RayKoopa** [comment]
I heard someone wanted to implement a live preview for the currently edited scene like this 🤣

**Comment by Zylann** [comment]
I wondered why all resource icons were black everywhere. Now I know :p

**Comment by manokara** [comment]
Can confirm. Arch Linux, latest master. But here it displays the 3D scene instead of the 2D one 😆

**Comment by algorev** [comment]
Can confirm on MacOS X El Capitan 10.11.6.

**Comment by Ahmed0425** [comment]
Lol  😂 .. Seems like many forms of only one bug ... do you encounter a crash on making a new shader?
that shader tab should not be visible
Also I think this bug was mentioned 3 other times in the tracker above #8665 #8489 #8314 .. all those testers encounter that shader crash bug
Am I wrong?

**Comment by bojidar-bg** [comment]
@Ahmed0425 Yeap, you are wrong. It is not the same bug, it is different bugs
 We sometimes mark duplicates based on the fact that a commit fixing issue X would automatically fix issue Y, for some reason. If any of the above three issues are fixed, there is no guarantee that this one would get fixed as well.
And also, the symptoms are different, so it is likely that it is not the same bug 😃.

**Comment by manokara** [comment]
As of 2e3145d, the device selection icon is doing the same thing. So whatever this issue is, it isn't only tied to the filesystem node.
![screenshot_20170524-155113](https://cloud.githubusercontent.com/assets/3709789/26420636/8971d512-4099-11e7-81a8-cb3970a1d67e.png)

Can anyone confirm this?

**Comment by akien-mga** [comment]
I love this issue.

**Comment by manokara** [comment]
I noticed that if you remove the device button, the filesystem icons [become a solid rectangle](http://i.imgur.com/b3aK5wy.png), either red or white. With the button, the filesystem icons and the button [look fine](http://i.imgur.com/QZSpnXY.png) (*somewhat, and only if you've resized the window*), but the scene not so much. And you have a lot of these at the console:

```
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Error	ID: 1282	Severity: High	Message: GL_INVALID_OPERATION error generated. Texture name does not refer to a texture object generated by OpenGL.
   At: drivers/gles3/rasterizer_gles3.cpp:123.
```

The viewport bug happens in both cases. So from what I see, this issue must be related to the gles3 renderer, somewhere in the texture management code. The renderer is using texture data it's not supposed to. I don't know a lot about rendering though, maybe @reduz can enlighten us on this.

**Comment by reduz** [comment]
I feel terrible to have fixed this bug, but it's sadly gone :(
