### ISSUE TITLE
`Resource::get_rid()` is not exposed as a GDExtension virtual method

### ISSUE THREAD

**Issue by DmitriySalnikov** [godotengine/godot#78127]
### Godot version

4.x

### System information

Windows 10

### Issue description

[Resource::get_rid()](https://github.com/godotengine/godot/blob/37d1dfef9d81aade27ab0c56fc6b6f12f6a08045/core/io/resource.h#LL140) is not exposed as GDExtension virtual method using `GDVIRTUAL*`.

For me, this makes it a bit difficult to create my own `Texture2D` and forces me to override the `draw_*` methods.
This issue has already been discussed here https://github.com/godotengine/godot-cpp/issues/877, but for some reason it was archived.

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
This is probably because in the bindings `get_rid` is *not* virtual, the virtual method is `_get_rid` but the extensions treats this as a hidden method I believe

**Comment by DmitriySalnikov** [comment]
> the virtual method is `_get_rid` but the extensions treats this as a hidden method I believe

This method simply does not exist, because `GDVIRTUAL*` was not used, as for example [here](https://github.com/godotengine/godot/blob/37d1dfef9d81aade27ab0c56fc6b6f12f6a08045/scene/resources/texture.h#LL60)


> It was archived because it was closed by the person who opened it, this is standard practice afik

Yeah, but I didn't understand why that person decided to close it. 🤷‍♂️

**Comment by DmitriySalnikov** [comment]
I found a message from [reduz](https://chat.godotengine.org/channel/gdextension?msg=bMEgB9imkjbY87FmN) that it is impossible to use GDVIRTUAL here.

> I also added Resource::get_rid() function as core, this should be added manually to Resource too because the binder does not allow me to use GDVIRTUAL for it due to include dependency

I also looked at the implementation of `Resource::get_rid` and there is a check for the existence of the `_get_rid` method in the scripts and some kind of `get_rid` call to GDExtension. But in GDExtension I found only a [pointer](https://github.com/godotengine/godot-cpp/blob/bfc9e0bd93aa75ce2efcf8be4c085f8aa08d9f1c/gdextension/gdextension_interface.h#L286) with a similar name, which is not assigned any value anywhere.

https://github.com/godotengine/godot/blob/37d1dfef9d81aade27ab0c56fc6b6f12f6a08045/core/io/resource.cpp#L306-L323

But if I manually add the `get_rid/_get_rid` method and even bind it, then nothing works anyway and I still need to manually override the methods for drawing textures.

**Comment by raulsntos** [comment]
- Fixed by https://github.com/godotengine/godot/pull/84944
