### ISSUE TITLE
Game crashes on exit if closed while awaiting a signal and there are unfreed objects

### ISSUE THREAD

**Issue by doctor-g** [godotengine/godot#78136]
### Godot version

4.0.3

### System information

Ubuntu 22.04.2 LTS

### Issue description

If awaiting a signal, and there are unfreed objects in memory, and the user closes the game, then the executable crashes with this error:
```
ERROR: Condition "_first != nullptr" is true.
   at: ~List (./core/templates/self_list.h:106)
```
In a build (rather than running from the editor), this is followed by this error:
```
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: cleanup (core/object/object.cpp:1982)
ERROR: Resources still in use at exit (run with --verbose for details).
   at: clear (core/io/resource.cpp:489)
```

This happens whether the object in question is an `Object` subclass that has not been freed or a `RefCounted`. 

What I expect to happen is that the application should close without throwing these errors. I expect any such memory to be automatically freed on application exit, or at least for the application to close gracefully, without throwing an error. The application's giving an error code produces a bad user experience that I cannot avoid if using signals and non-Node scripts.

I have seen the same behavior on Windows 10, although I am writing this report from Linux.

Note that these errors show up in the terminal that launched Godot (the engine or the built game), not within Godot's "Output" window.

### Steps to reproduce

Please see the attached minimal reproduction project. Run `main.tscn` and close the running application: it will produce an error. Run the application again and click the button, whose `pressed` signal is being awaited in the script. Now close the application, and no error will be produced.

The error is easiest to see if godot itself was started from the command-line: this error is reported in the terminal that launched Godot, not within Godot's built-in terminal.

Whether the allocated object is an unfreed `Object` or a `RefCounted` does not seem to matter. The example project uses `item.gd` as a minimal `RefCounted`. Once can change it to an `Object` and stick an `_item.free()` at the end of the `_ready()` function, and the same behavior will occur.

To make your own reproduction:
- Make a custom `Object` or `RefCounted` script
- In the main scene, e.g. in `_ready`, create an instance, then await a signal
- Run the application and close it before that signal is received.

Here is a sample. Given a script like this:
```
class_name Item
extends RefCounted
```
Then the following scene will generate the problem if closed before clicking a button in it:
```
extends Control

func _ready():
	var _item := Item.new()
	await $Button.pressed
```

### Minimal reproduction project

[repro_await.zip](https://github.com/godotengine/godot/files/11722690/repro_await.zip)

**Comment by bitsawer** [comment]
Can reproduce this on latest master at 66423d440e53109627717edbada77856c514bb6f

I guess you are running a debug build with DEV_ASSERT() enabled? Looks like during `GDScriptLanguage` destructor, `GDScriptLanguage::script_list` is not empty and still holds the Item.gd script which triggers `DEV_ASSERT(_first == nullptr);` because of that.

Stack trace:

```
SelfList<GDScript>::List::~List() (e:\Repositories\godot\core\templates\self_list.h:114)
GDScriptLanguage::~GDScriptLanguage() (e:\Repositories\godot\modules\gdscript\gdscript.cpp:2550)
void memdelete<GDScriptLanguage>(GDScriptLanguage*) (e:\Repositories\godot\core\os\memory.h:109)
uninitialize_gdscript_module(ModuleInitializationLevel) (e:\Repositories\godot\modules\gdscript\register_types.cpp:150)
uninitialize_modules(ModuleInitializationLevel) (e:\Repositories\godot\modules\register_module_types.gen.cpp:240)
Main::cleanup(bool) (e:\Repositories\godot\main\main.cpp:3577)
widechar_main(int, wchar_t**) (e:\Repositories\godot\platform\windows\godot_windows.cpp:182)
_main() (e:\Repositories\godot\platform\windows\godot_windows.cpp:204)
main (e:\Repositories\godot\platform\windows\godot_windows.cpp:223)
__tmainCRTStartup (@__tmainCRTStartup:108)
WinMainCRTStartup (@.l_startw:6)
BaseThreadInitThunk (@BaseThreadInitThunk:9)
RtlUserThreadStart (@RtlUserThreadStart:12)
```

**Comment by bitsawer** [comment]
>whether I run it in editor, with a debug build, or with a release build. I am not sure how I would enable DEV_ASSERT if I wanted to.

In some Godot debug build configurations there is more error checking enabled, for example DEV_ASSERT()'s. Doesn't really affect this report, I was just interested what kind of Godot build you use (release, debug, stock download, Linux package manager provided, custom build etc).

**Comment by doctor-g** [comment]
Gotcha. I'm just using the stock downloads of 4.0.3 from https://godotengine.org/ on both Linux and Windows.

**Comment by AThousandShips** [comment]
Issue still causes a crash on 4.1 due to the check, but since this was reported for 4.0.x I removed the tag for this issue specifically
