### ISSUE TITLE
Windows target Microsoft Visual Studio 2013 cannot compile master branch

### ISSUE THREAD

**Issue by cjmxp** [godotengine/godot#7813]
Windows target Microsoft Visual Studio 2013 cannot compile master branch

**Comment by akien-mga** [comment]
With an error log, it would be more useful :)

**Comment by rubenjavier** [comment]
check if this helps:
(the posts I added at the end with modifications for VS2013 but my changes wasnt added to the merge in time)
[Fixed compilation issues with Visual Studio #7763](https://github.com/godotengine/godot/issues/7763)

what I did::
servers/audio/effects/eq.cpp
from:
50 #define BAND_LOG( m_f ) ( log((m_f)) / log(2) )
to:
50 #define BAND_LOG( m_f ) ( log((m_f)) / log((float)2) )

and:
servers/audio/effects/audio_effect_pitch_shift.cpp
from:
223 for (k = 0, le = 2; k < (long)(log(fftFrameSize)/log(2.)+.5); k++) {
to:
223 for (k = 0, le = 2; k < (long)(log((float)fftFrameSize)/log(2.)+.5); k++) {

**Comment by akien-mga** [comment]
@rubenjavier You mean https://github.com/godotengine/godot/pull/7746/commits/16b3973c75b6d72ff944bc205b8637554cf9a06d ? :)

**Comment by rubenjavier** [comment]
@akien-mga yeap thats the one :)
sorry, didn't see that one when I cloned about 3 days ago
Thanks

**Comment by cjmxp** [comment]
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\xlocale(337) : wa
rning C4530: 使用了 C++ 异常处理程序，但未启用展开语义。请指定 /EHsc
c:\mywork\godot\drivers\gles3\shaders/copy.glsl.h(91) : error C4430: 缺少类型说
明符 - 假定为 int。注意:  C++ 不支持默认 int
c:\mywork\godot\drivers\gles3\shaders/copy.glsl.h(91) : error C2143: 语法错误 :
缺少“,”(在“&”的前面)
c:\mywork\godot\drivers\gles3\shaders/copy.glsl.h(91) : error C2535: “void Copy
ShaderGLES3::set_uniform(CopyShaderGLES3::Uniforms,int32_t)”: 已经定义或声明成
员函数
        c:\mywork\godot\drivers\gles3\shaders/copy.glsl.h(48) : 参见“CopyShader
GLES3::set_uniform”的声明
c:\mywork\godot\drivers\gles3\shaders/copy.glsl.h(93) : error C4430: 缺少类型说
明符 - 假定为 int。注意:  C++ 不支持默认 int
c:\mywork\godot\drivers\gles3\shaders/copy.glsl.h(93) : error C2143: 语法错误 :
缺少“;”(在“&”的前面)
c:\mywork\godot\drivers\gles3\shaders/copy.glsl.h(93) : error C2082: 形参“Matri
x32”的重定义
c:\mywork\godot\drivers\gles3\shaders/copy.glsl.h(93) : error C2065: “tr”: 未
声明的标识符
c:\mywork\godot\drivers\gles3\shaders/copy.glsl.h(93) : error C2065: “p_transfo
rm”: 未声明的标识符

**Comment by akien-mga** [comment]
@cjmxp Delete all `*.glsl.h` files in `c:\mywork\godot\drivers\gles3\shaders\` and it might work.

**Comment by cjmxp** [comment]
Compile through,Thank you very much.
