### ISSUE TITLE
Unexpected "Parser Error : Identifier not found" when using parent class member

### ISSUE THREAD

**Issue by 3lis4** [godotengine/godot#78146]
### Godot version

4.0.2

### System information

Linux Mint 21

### Issue description

On the minimal reproduction project, with a 3 level hierarchy and 2 autoloads, when running the game we get a parse error in daughter.gd where we use a parent member.

**Additional remarks :** 
- We have a circular dependency involving one of the autoloads : Autoload2 references Daughter which references Mother which references GrandMother which references Autoload2
- Autoload1 references Mother which references GrandMother which references Autoload2
- We don't have any error if we switch the 2 autoloads order in Project Settings
- We get the same error if _member is put in GrandMother class instead of Mother class
- We still get the issue if we disable Autoload1 in Project Settings

**A quick look in Godot source code :**
- GDScriptCache::full_gdscript_cache contains invalid scripts (ie script->is_valid() is false)
- I think the engine tries to compile GrandMother, then Daughter (but it fails), then Mother

(This issue might be related to https://github.com/godotengine/godot/issues/75388.)

### Steps to reproduce

To get the parse error :
- Open the minimal reproduction project
- Run the game
You'll get `Parser Error: Identifier not found: _member`.

### Minimal reproduction project

[ParseError_Project.zip](https://github.com/godotengine/godot/files/11725756/ParseError_Project.zip)

**Comment by anvilfolk** [comment]
I managed to create an MRP that does not include autoloads, just for the record! Just open the project and run the scene.

[MRP.zip](https://github.com/godotengine/godot/files/11992322/MRP.zip)
