### ISSUE TITLE
Can't reset root node type to Node3D in advanced import settings

### ISSUE THREAD

**Issue by mbrlabs** [godotengine/godot#78140]
### Godot version

4.0.3 and latest 4.1 (2d6b880987bc600cda586b281fcbe26791e92e09)

### System information

Manjaro Linux

### Issue description

When you change the root type of an imported scene (in my case it's a glb file) you can't change it back to a Node3D. Changing it to any other 3D node works though.

### Steps to reproduce

1. Import a glb file
2. Double click it to open the advanced import settings and change the root type to StaticBody3D or any other type that inherits from Node3D. Click reimport.
3. Now try to change it from StaticBody3D to Node3D. This will fail silently.

### Minimal reproduction project

[RootTypeBug.zip](https://github.com/godotengine/godot/files/11725039/RootTypeBug.zip)

**Comment by AThousandShips** [comment]
Might have found the cause of this, will try investigate when I have the time, it checks for the root type and doesn't do anything if it is `Node3D`, I think that check needs to be different

**Comment by mbrlabs** [comment]
Yeah, i guess you found this:
https://github.com/godotengine/godot/blob/7b1387ff218cd86be77dd7e774542e54251e7ea6/editor/import/resource_importer_scene.cpp#L2430-L2439

Not sure why Node3D is excluded here. I removed the check but it didn't seem to do anything. Didn't dig too deep into this though, so feel free to investigate further :)

**Comment by kdiduk** [comment]
I've found something interesting.

https://github.com/godotengine/godot/blob/c3b0a92c3cd9a219c1b1776b48c147f1d0602f07/editor/import/scene_import_settings.cpp#L927-L930

When any node, apart from `Node3D` is selected in the dialog, the dictionary `defaults` contains an entry with the key `nodes/root_type` and the string value with the name of selected node type.  

However, for some reason, when we select `Node3D`, the dictionary `defaults` doesn't have an entry with the key `nodes/root_type` for some reason.

**Comment by capnm** [comment]
The workaround is to use the " non-advanced" importer, the error seems to be somewhere in the flawed logic of the new one ...

**Comment by kdiduk** [comment]
I've found the problem :relieved:  Although it was tricky to find it, the fix for it is just one line. It works fine, however I'm still a bit worried about the if-condition here:
https://github.com/godotengine/godot/blob/7b1387ff218cd86be77dd7e774542e54251e7ea6/editor/import/resource_importer_scene.cpp#L2430-L2439
It works without touching that part, however I doubt why that if-condition is there and whether we should remove it.

Please, review my PR :pray:

**Comment by mikest** [comment]
I have run into this issue while Reimporting gltf models after changing the root node type from Node3D to RigidBody3D. I can no longer change back to Node3D. The changes don't stick on re-import.

This would be on 4.1.2
