### ISSUE TITLE
Exported typed array in instanced child scene gets empty elements added and crashes editor

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot#78150]
### Godot version

4.1.beta1

### System information

macOS 13.3.1

### Issue description

If you have a scene (ChildScene) with a node that has an exported typed array, for example
`@export var export_array:Array[Node]`
use the inspector to add a number of child nodes as the elements of this array and then instance this scene in another scene (ParentScene) the editor becomes prone to crashing, seemingly every time it tries to load or save ParentScene. This reliably crashes the editor, and also when opening the project after the crash, the export_array array now has added empty elements, same as the number of elements it originally had. 

### Steps to reproduce

Set up a child scene with a node with a typed export array, and set up a few child nodes to set as the items in the array in the inspector.
![Screenshot 2023-06-12 at 19 09 42](https://github.com/godotengine/godot/assets/17763524/64fc2dbc-f5ac-47ec-8ccd-73fe81894fe9)

Instanciate the childScene in another scene parentScene
![Screenshot 2023-06-12 at 19 13 02](https://github.com/godotengine/godot/assets/17763524/bfaad659-59e7-437e-a7d5-f94f4bb77b0f)

Now, go back to the childScene and save it again (with or without modification) open the parent scene and the editor will crash. When opening the editor again after the crash you can see that the array in both the instance in parentScene and the original in childScene has added empty elements (but not in the same places!). 

If you change the child scene, removing the empty rows and try to go to the parentScene you'll crash again. Open the project and the empty elements will be back. If you don't remove them and crash again, additional empty elements will have been added.

https://github.com/godotengine/godot/assets/17763524/373ef395-178a-4206-9a73-fec55e2b5a68

You can also get a warning this is happening if when you save a scene you get a bunch of errors:
`scene/main/node.cpp:1988 - Condition "!common_parent" is true. Returning: NodePath()`
Since having typed export arrays with empty items apparently causes this error (maybe this is also a bug?) so you can see that something has gone wrong and empty items have been added to your exported array.

### Minimal reproduction project

[ExportArrayTest.zip](https://www.lostminds.com/godot/ExportArrayTest.zip)

**Comment by AThousandShips** [comment]
* Related/duplicate: #77641

**Comment by AThousandShips** [comment]
Can you check if #77735 fixes this? It seems to be related to the bug I came across there

**Comment by AThousandShips** [comment]
You can download the artifacts from the build, see [here](https://docs.godotengine.org/en/stable/contributing/workflow/testing_pull_requests.html), I'm unable to test it myself right now, but otherwise I can test it when I have the time

**Comment by ajreckof** [comment]
Tried with #77735 and I have no crash did get a clean of the array at first with the same error that was given by the author but no crash and reseting the array does not reproduce the error. Tried multiple times everytime I reopen the project from MRP from the zip it will do the same but setting the array afterwards does not reproduce anything so I think the PR fix this issue.

**Comment by akien-mga** [comment]
> But while trying out downloading the #77735 artifact for the macOS editor to test this as well I think I found an issue with that (or maybe I'm not doing it correctly?) but it seems the automatically generated [artifact for the macOS editor](https://github.com/godotengine/godot/suites/13325843354/artifacts/728226743) is packaged as a linux application godot.macos.editor.x86_64 and not as the appropriate macOS .app bundle?

That's expected, making an .app bundle requires some more steps which we don't bother with for CI, as the artifacts aren't meant for general usage but for testing by developers (and I think the binary still works when run from the command line). It's not a Linux application, it's just the raw macOS binary that would end up in the .app bundle.

We could tweak the CI build scripts to go the extra length and do the .app bundling, but it still wouldn't be signed and notarized which might make it counterproductive? To be tested, I don't have a Mac handy to see what's worst.

**Comment by ajreckof** [comment]
It doesn't change much the major difference is that you don't need to open a terminal to open it but in this case since it will be quarantined in both case you will need to open the terminal to unquarantine it. There might be a difference if with .app we get to make it executable by default as right now it is not executable so you also need to make the artifact you download executable but that's just one more line to run in the terminal

**Comment by lostminds** [comment]
> That's expected, making an .app bundle requires some more steps which we don't bother with for CI, as the artifacts aren't meant for general usage but for testing by developers (and I think the binary still works when run from the command line). It's not a Linux application, it's just the raw macOS binary that would end up in the .app bundle.

I see, thanks for the explanation. From my point of view I think it would be better to package it as an .app. Most of all to make it recognizable as something you can run on mac. Apparently this may not the case with a .x86_64 file, something I've never seen on macOS despite doing development for 20+ years on the platform. Dealing with un-notarized or unsigned app bundles is however something I've done before, and I'd guess that's something more people are familiar with. If packaging the macOS binary in an .app bundle also makes it executable by default as well that would also be an improvement and further lower the threshold so more people in the community could use this feature and help test builds for pull requests.
