### ISSUE TITLE
VoxelGI rotates relative to the camera in XR

### ISSUE THREAD

**Issue by bigtoe27** [godotengine/godot#78166]
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Windows 11 - Quest 2 - Godot v4.0.3.stable - Vulkan (Forward+) - AMD Radeon RX 6600 XT Adrenalin Edition

### Issue description

When I move my head in VR, the VoxelGI rotates strangely depending on my headset's rotation. It's not as if it's parented to the camera, but rather somehow linked. I assume that when I look straight up, it's aligned as it should be.

https://github.com/godotengine/godot/assets/134245218/4d7b445a-de05-456d-8b7d-34cc801941dd

### Steps to reproduce

Go to scenes/range.tscn and start in VR. I've lowered the VoxelGI's bias to 0 to make the effect more apparent.

### Minimal reproduction project

[godotvr.zip](https://github.com/godotengine/godot/files/11730372/godotvr.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/73403.
