### ISSUE TITLE
TileSet "Paint" button for painting properties stops working and becomes greyed for an unknown reason

### ISSUE THREAD

**Issue by stilestr** [godotengine/godot#78162]
### Godot version

4.1.beta1

### System information

Godot v4.1.beta1 - Windows 10.0.22621 - Vulkan (Forward+) - dedicated AMD Radeon RX 5700 XT (Advanced Micro Devices, Inc.; 31.0.14057.2005) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

I have no idea what caused this, so not sure how this could be tracked down. But, figured it is worth noting since I couldn't find an issue opened already.

I have a rather simple project with a few nodes and Tilemap. After a long time of working on this project today, I went back to paint a new physics layer using the Tileset > Paint feature. However it was greyed out, and no amount of switching tabs, moving windows, or flicking through the inspector or scene tabs did anything.

![Screenshot 2023-06-12 192030](https://github.com/godotengine/godot/assets/4535064/cc6c3336-aeda-490c-b53f-64023da2f802)

This picture shows the paint button not working.

I did nothing but close Godot and reopen it, and it began working again.

![Screenshot 2023-06-12 192112](https://github.com/godotengine/godot/assets/4535064/51144157-e93a-4530-a09d-09468ec7ffba)

Is this intended, and did I somehow activate something that disabled the ability to Paint, or is this a bug?

### Steps to reproduce

No detailed steps, unfortunately. It just randomly became greyed out after not opening the TileSet or TileMap windows for a long time and would not become active until restarting Godot.

### Minimal reproduction project

N/A because I couldn't tell you what caused this

**Comment by Zireael07** [comment]
IMHO this read-only mode could be communicated better (e.g. the button text changing to Read only in addition to being disabled)

**Comment by stilestr** [comment]
> I am not sure this is a bug. Basically, this happens when the TileSet resource is in `read_only` mode. This might be because the resource is opened in two scenes or something like that.

Yup, this is it. Creating an inherited scene of the tilemap causes this to happen every time. I agree with @Zireael07 that maybe a simple change to the hover text to say "TileSet is in read-only mode. Make the resource unique to edit TileSet properties" would be super helpful, since I know I spent a good half hour trying to figure out what was going on. 

It may also be an issue of how I was structuring the game, but essentially it is a tile-based puzzle game, and additional levels are inherited scenes of the first level, which has all of the core logic for the game board.

**Comment by TheSofox** [comment]
Made a PR to fix this problem. I used @stilestr suggested text as the tooltip to display when the button is disabled. When enabled it should have the regular tooltip.
