### ISSUE TITLE
CollisionShape2D does not follow parent node

### ISSUE THREAD

**Issue by ImFlavo** [godotengine/godot#7817]
**Operating system or device - Godot version:**
Windows 10, SHA: 9cdd364fc0edee407a65fbef674dcc3bcea378a9

**Issue description:**
CollisionShape2D would not follow any nodes it was a child of

**Steps to reproduce:**
Create Area2D
Create a child of Area2D as CollisionShape2D
Have Area2D move, collisionshape will not follow

**Comment by RebelliousX** [comment]
Just wondering if this is related to #7799 ?

**Comment by ImFlavo** [comment]
Absolutely.

**Comment by rubenjavier** [comment]
Yeap, its the same bug, I just didn't know at the time what was causing it

This makes the 2D framework almost unusable in its current state for most types of 2D games

**Comment by bojidar-bg** [comment]
Well, if it is the same bug, I'll close it as duplicate (now you know why it was untagged :wink: )

**Comment by rubenjavier** [comment]
but [#7799](https://github.com/godotengine/godot/issues/7799) is still tagged as "need testing", I think it should be tagged "confirmed", as it has been replicated by many, so it can be assigned to someone

Thanks
