### ISSUE TITLE
Feature request: Like the new $, but for find_node

### ISSUE THREAD

**Issue by jackmakesthings** [godotengine/godot#7818]
Just reading the devblog and I love the new $ shorthand for get_node in v3! I tend to use find_node more because it's not affected if I revise the node tree later; could we also get an alias for that? 

If `$Button` is `get_node('Button')`, maybe `$$Button` = `find_node('Button')`? Doesn't have to be $$ - that was just my first thought.

**Comment by hpvb** [comment]
This sounds like a good idea to me. Are you ok with me implementing this @reduz?

**Comment by akien-mga** [comment]
Personally I'm not fond of the idea. `find_node` should not be used that often, personally I think I've never used it as I much prefer to try to organize my scenes in a way that prevents having to find a random node by its name, and instead have predictable paths to children. Also `$$Button` is not particularly explicit, when using a function like `find_node`, it's best to stay explicit IMO.

**Comment by hpvb** [comment]
OK, if it is believed that this will lead to bad coding practices perhaps it's better to not do it.

**Comment by neikeq** [comment]
`find_node` is way slower than `get_node`. Don't use it when you can do the same with the later.

**Comment by akien-mga** [comment]
Closing then. Sorry @jackmakesthings but as mentioned above, `find_node` is slow and should be only used sparsely - I would advise you to try to organize your scenes in a way that makes it possible to use `get_node` whenever possible, and `find_node` only when you can't do without it.
