### ISSUE TITLE
Home/end keys are unusable in the In-built

### ISSUE THREAD

**Issue by svprdga** [godotengine/godot#78189]
### Godot version

4.0.3.stable.official

### System information

macOS: Vulkan API 1.2.231 - Forward Mobile - Using Vulkan Device #0: Apple - Apple M2 Pro

### Issue description

The built-in editor is completely ignoring the home and end keys.

### Steps to reproduce

Create a new Godot project, create a script, go to the editor and try jumping to the start or end using the home/end keys. These keys are unusable on Mac.

### Minimal reproduction project

This issue can easily be reproduced in all projects created with Godot.

**Comment by AThousandShips** [comment]
This is not supported no, this should best be handled as a proposal though as it's not a bug

Please search for one [here](https://github.com/godotengine/godot-proposals) and open one if one isn't available, and follow all the instructions.

**Comment by AThousandShips** [comment]
Closing as this is proposal territory, not a bug

**Comment by AThousandShips** [comment]
My bad didn't realize it was the built in editor

**Comment by AThousandShips** [comment]
My bad had a bit of a confusion there, this doesn't seem to be supported no, I don't know where these specific macros are used and they don't seem to be referenced in the editor anywhere

**Comment by svprdga** [comment]
@AThousandShips forget about the custom mappings, I have changed the issue. The built-in editor is completely ignoring the home/end keys.

In Linux these keys are working as expected, in fact, I expect all regular keys in my keyboard to work in the the built-in editor.

**Comment by AThousandShips** [comment]
Can indeed not confirm on Windows, does this happen any time or at specific times such as during auto-complete?

**Comment by AThousandShips** [comment]
Looks like it is mapped differently on mac, seemingly to:
* `CTRL-A`
* `CMD/CTRL-LEFT`

It seems it doesn't use `ui_home` but `ui_text_caret_line_start` for this navigation

**Comment by svprdga** [comment]
Mmh yes, it had not occurred to me to try to correct it from the editor shortcuts, I have managed to make it respond as I want through this configuration:


<img width="851" alt="Captura de pantalla 2023-06-13 a las 17 34 48" src="https://github.com/godotengine/godot/assets/43069276/561c8bfa-c4af-4256-923a-124144cc85fc">


Anyway, I found it weird that a specific configuration would be necessary for something that should work by default...

**Comment by AThousandShips** [comment]
These settings are set up specifically for mac, to follow the usual setup AFIK, does home/end do anything else, there's no automatic collision detection between actions in the editor AFIK

**Comment by svprdga** [comment]
> Pretty much none of the Mac apps use Home/End. ⌘+Left/Right and Ctrl+A/E are standard shortcuts on macOS from moving to beginning/end of the line. But it does not seem to be used for anything, so probably can be added as an alternative.

I understand, thanks for the clarification.

I am going to close this issue then since in my case I have customized keymaps on Mac to imitate the style of Windows/Linux. If "traditional" Mac users use the keys that you mention, I understand that a change would not be necessary, but in my particular case, modify the shortcuts to customize them to my workflow.
