### ISSUE TITLE
Curve/path tools (in 3D) not working with floating script editor.

### ISSUE THREAD

**Issue by bt0rne** [godotengine/godot#78193]
### Godot version

v4.1.beta1.official [828ec2c5d]

### System information

Godot v4.1.beta1 - Debian GNU/Linux 12 (bookworm) 12 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (nvidia) - Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz (4 Threads)

### Issue description

I'm working on a project with a lot of curves, and i decided to test the new feature to make the script editor float. This doesn't affect much that i have seen for now, exept that using the path/curve tools does not work while the script editor is floating, for some reason. 

The curve points seems to disappear when re-selecting the Path3D node after making the script editor float. The points appear again and everything works great when exiting the floating script editor and then reselecting the Path3D node again. I suppose the tools not working are an extension of the problem with the points disappearing.

I could not reproduce the issue with 2D nodes.

**Simple Path3D node setup:**
![image](https://github.com/godotengine/godot/assets/123738491/82e003ea-e3a1-4dca-b2e4-060b00af7b41)
![image](https://github.com/godotengine/godot/assets/123738491/769d283c-3d06-4196-87bb-8427b4c3b58e)

**Before and after:**
![image](https://github.com/godotengine/godot/assets/123738491/f1edf1d8-f6da-4939-b9ea-3f23504bd982)
![image](https://github.com/godotengine/godot/assets/123738491/f306ff2d-9ac4-49fc-8bbb-2269cdbab44d)

### Steps to reproduce

Make points disappear:
- Add Path3D node.
- Add 1 or more points.
- In the "Script" tab, press "Make Floating".
- Reselect the Path3D node.

Make points appear again:
- Exit the floating script window.
- Reselct the Path3D node.

### Minimal reproduction project

N/A

**Comment by OhiraKyou** [comment]
Just ran into this. I always have the script editor open in a floating window. Perhaps there's still an assumption somewhere in the code that the 3D tab will not be in use while other tabs, like Script, are in use (not taking into account the possibility of floating).

As described in the reproduction steps, you have to reselect the path node to see points appear or disappear after opening or closing the script window.

Relevant information:

- Godot Engine version: `v4.1.1.stable.official [bd6af8e0e]`
- Renderer: `Compatibility`
- OS: `Fedora Linux 38 (Workstation Edition)`
- Desktop environment: `GNOME 44.5`
- Windowing System: `X11`

**Comment by Okxa** [comment]
Happens also with custom gizmos added by EditorNode3DGizmoPlugin:

https://github.com/godotengine/godot/assets/25027118/e03c3443-4c86-45cb-8ea7-8130fae15df3

**Comment by Okxa** [comment]
Just tested this, it is fixed in `v4.1.3.stable` for all handles, or atleast for those that I tested: curves and my custom gizmo handles
![image](https://github.com/godotengine/godot/assets/25027118/2f562b95-4434-4d66-b9e3-5c4196d8f58a)

**Comment by Cammymoop** [comment]
Confirmed, fixed by #80647
