### ISSUE TITLE
NavigationAgent3D computes safe velocity every frame, even when agent is immobile

### ISSUE THREAD

**Issue by BenNicholls** [godotengine/godot#78197]
### Godot version

Godot v4.1.beta1

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 960 (NVIDIA; 31.0.15.3161) - Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 Threads)

### Issue description

When avoidance is enabled, my actors are emitting the velocity_computed signal once per frame even when immobile. Naturally the safe velocity being returned is (0,0,0). As far as I can tell from the documentation, this signal is only supposed to be emitted in response to the navigation agent's velocity being set. 

If I'm reading the docs wrong let me know. I tried Godot 4.0 stable with the same setup and it does not exhibit this behaviour, so I think it's a bug, but maybe I'm all mixed up.

### Steps to reproduce

1. Create a simple navmesh (my repro project just uses a 10x10 planemesh)
2. Create an actor object and attach a NavigationAgent3D node as a child
3. Enable avoidance on the navigation agent node
4. Attach a script to the actor node and connect the "velocity_computed" signal to a function with a print statement.
5. Run and behold!

![image](https://github.com/godotengine/godot/assets/208573/502f7fd8-bd13-4279-8aac-9a72e253f288)

### Minimal reproduction project

[velocity_test.zip](https://github.com/godotengine/godot/files/11737814/velocity_test.zip)

**Comment by BenNicholls** [comment]
I thought that might be the case, makes sense. It might be a good idea to update the docs because they definitely make it seem like the avoidance calculation is initiated by the user and not done automatically per frame (see [here](https://docs.godotengine.org/en/latest/tutorials/navigation/navigation_using_navigationagents.html#navigationagent-avoidance), it says "In order to trigger the avoidance velocity calculation, the current velocity of the agent's parent node must be set with set_velocity() on the NavigationAgent node in _physics_process().")

If this is the intended behaviour then I suppose this issue can be closed, although I now have a host of other problems to investigate. It's possible I have things set up wrong so I won't go into them here. If I can pin down why I can't get it working I'll make another issue. And if I can't get avoidance working I'll just go back to 4.0.3, which appears to not have this behaviour and just works.

**Comment by smix8** [comment]
You can use the `set_velocity_forced()` function every physics frame to replicate a majority of the old avoidance behavior.
If you also want the more buggy parts you need to enable the 3d avoidance mode (cause that is what 4.0.3 is using) and zero the returned y-axis velocity.

**Comment by BenNicholls** [comment]
I tried both of your suggestions while puzzling my way through this debacle and neither seemed to give results. set_velocity_forced() didn't seem to work at all. And you're right, the 4.0.3 avoidance is not exactly a panacea, it has plenty of its own problems. I sure I'm just doing something wrong. I'll wait for new tutorials to go up and just disable avoidance for the time being. Lots of other stuff to work on in the meantime!

Thanks for the help, I'll give it another go later on. :)
