### ISSUE TITLE
Appending to RichTextLabel.text restores any cleared text

### ISSUE THREAD

**Issue by Poobslag** [godotengine/godot#78196]
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Windows 10 - Godot 4.0.3

### Issue description

Calling `RichTextLabel.clear()` and then appending to its `text` field restores all of the cleared text.

This seems related to #54951, but this issue has nothing to do with `bbcode_text` field -- it occurs simply by writing text and calling the `clear` function.

This bug can be trivially worked around by calling `RichTextLabel.text = ""` in addition to `RichTextLabel.clear()`. However this is nonsensical and contradicts the documentation, which explicitly states that the clear() function "Clears the tag stack and sets text to an empty string"

### Steps to reproduce

1. Click the "Add Text" button. A line of text is added to the RichTextLabel.
2. Click the "Clear" button. The RichTextLabel is cleared.
3. Click the "Add Text" button. The cleared lines are restored, and additional text is added beneath them.

### Minimal reproduction project

[RichTextLabel-clear.zip](https://github.com/godotengine/godot/files/11737734/RichTextLabel-clear.zip)

**Comment by bruvzg** [comment]
> Clears the tag stack and sets text to an empty string

Documentation is wrong, `clear` is cleaning tag stack, but do not affect `text`. It's intended to be used in conjunction with `push_*`/`pop` methods, not with `text`.

> This bug can be trivially worked around by calling RichTextLabel.text = "" in addition to RichTextLabel.clear(). 

Setting `text` will call `clear` automatically, there's no need to call both.
