### ISSUE TITLE
Import options don't refresh after reimport

### ISSUE THREAD

**Issue by adamscoble** [godotengine/godot#78209]
### Godot version

4.1.beta.official

### System information

Windows 10

### Issue description

`EditorImportPlugin` options that change visibility based on the value of other options don't update after reimporting the asset.

### Steps to reproduce

1. Create an EditorImportPlugin that implements `_get_import_options` and `_get_option_visibility`. 
2. In `_get_option_visibility`, return `true` or `false` depending on the value of a separate option. 
3. Changing that variable should show or hide the other on reimport, but doesn't.

### Minimal reproduction project

-

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/49641.
