### ISSUE TITLE
Plugin description tooltip has no limits

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#78202]
### Godot version

4.1 beta1

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

![image](https://github.com/godotengine/godot/assets/2223172/3030410f-3bde-4d48-a2bc-959cc4b10518)
This is a plugin description that spans 2 screens and goes beyond the right screen border.
I just wanted to test if there is any limit to plugin description size. There is none. You can potentially put a text that will cover your whole screen (don't try it 🙃).

Not sure how we should solve that. We could autowrap the label, but to gracefully display extremely long texts they either need to be scrolled (in a tooltip??) or truncated.

### Steps to reproduce

1. Open Project Settings
2. Go to Plugins -> Create New Plugin
3. Write a book in the Description field

### Minimal reproduction project

https://www.lipsum.com/

**Comment by Calinou** [comment]
I suggest using String's wrap function to wrap lines in the tooltip to 80 characters or so (using a per-word basis).
