### ISSUE TITLE
Issue with emitting signals from handlers of C# events

### ISSUE THREAD

**Issue by brane-games** [godotengine/godot#78214]
### Godot version

4.1.beta1.mono

### System information

Godot v4.1.beta1.mono - Windows 10.0.22621 - Vulkan (Forward+) - integrated Intel(R) UHD Graphics 620 () - Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 Threads)

### Issue description

Emitting signals from handlers of C# events does not work in Godot 4.1

My code in 4.0 was:
In _Ready()
```
_timeManager = new ChessMatchTimeManager();
_timeManager.PlayerSecondElapsed += HandlePlayerSecondElapsed;
```

```
	private void HandlePlayerSecondElapsed(int secondsRemaining)
	{
		EmitSignal("PlayerTimeElapsed", _boardState.Board.Turn.ToString(), secondsRemaining);
		_energyManager.HandleSecondElapsed();
	}
```

This produces an error:
```
_E 0:02:38:0692   Godot.NativeInterop.NativeFuncs.generated.cs:353 @ Godot.NativeInterop.godot_variant Godot.NativeInterop.NativeFuncs.godotsharp_method_bind_call(IntPtr , IntPtr , Godot.NativeInterop.godot_variant** , Int32 , Godot.NativeInterop.godot_variant_call_error& ): Caller thread can't call this function in this node. Use call_deferred() or call_thread_group() instead.
  <C++ Error>    Condition "!is_accessible_from_caller_thread()" is true. Returning: (ERR_INVALID_PARAMETER)
  <C++ Source>   scene/main/node.cpp:3566 @ emit_signalp()
  <Stack Trace>  Godot.NativeInterop.NativeFuncs.generated.cs:353 @ Godot.NativeInterop.godot_variant Godot.NativeInterop.NativeFuncs.godotsharp_method_bind_call(IntPtr , IntPtr , Godot.NativeInterop.godot_variant** , Int32 , Godot.NativeInterop.godot_variant_call_error& )
                 NativeCalls.cs:6058 @ Int32 Godot.NativeCalls.godot_icall_2_676(IntPtr , IntPtr , Godot.NativeInterop.godot_string_name , Godot.Variant[] )
                 GodotObject.cs:563 @ Godot.Error Godot.GodotObject.EmitSignal(Godot.StringName , Godot.Variant[] )
                 ChessMatchSimulation.cs:224 @ void ChessMatchSimulation.HandlePlayerSecondElapsed(Int32 )
                 ChessMatchTimeManager.cs:144 @ void ChessSimulation.src.match.ChessMatchTimeManager+<>c__DisplayClass36_0+<<Start>b__0>d.MoveNext()
                 :0 @ void System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext , System.Threading.ContextCallback , System.Object )
                 :0 @ void System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(System.Threading.Thread )
                 :0 @ void System.Threading.PeriodicTimer+State.Signal(Boolean , System.Threading.CancellationToken )
                 :0 @ void System.Threading.PeriodicTimer+<>c.<.ctor>b__2_0(System.Object )
                 :0 @ void System.Threading.TimerQueueTimer.Fire(Boolean )
                 :0 @ void System.Threading.TimerQueue.FireNextTimers()
                 :0 @ Boolean System.Threading.ThreadPoolWorkQueue.Dispatch()
                 :0 @ void System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()_
```

Where line 224 is EmitSignal one in HandlePlayerSecondElapsed method. 

I understand that there's a good chance this is the expected behaviour and just part of multi-threading improvements you are making but I want to make sure. If so, what is the preferred solution?

### Steps to reproduce

1. Create a C# class that emits dotnet events
2. Handle those events in Godot Node
3. Try to call EmitSignal in the handler logic

### Minimal reproduction project

N/A

**Comment by raulsntos** [comment]
The `EmitSignal` method has a thread guard which means it has to be called from the main thread:

https://github.com/godotengine/godot/blob/0aad5eb1cff831fce1263bf59144a63ecde32421/scene/main/node.cpp#L3574

As suggested by **RedworkDE**, using Godot's built-in timers should work. But if you want to keep using C# timers, you should be able to use `CallDeferred` like the error suggests. You can use `GodotObject.CallDeferred` or a `Callable`, here's an example using a `Callable`:

```csharp
private void HandlePlayerSecondElapsed(int secondsRemaining)
{
	Callable.From(() =>
	{
		EmitSignal("PlayerTimeElapsed", _boardState.Board.Turn.ToString(), secondsRemaining);
		_energyManager.HandleSecondElapsed();
	}).CallDeferred();
}
```

**Comment by brane-games** [comment]
I think I'll try the CallDeferred approach, as I want to leave the logic in the other class free of Godot dependency. 

Thank you very much for the explanation and an example!

**Comment by LordBrkica** [comment]
I just spent a day debugging this:

            DamageLabel.Text = $"{damage}";  // THIS WORKS 

            var damageLabelTimer = new System.Timers.Timer(2000);
            damageLabelTimer.Elapsed += (sender, args) => 
            {                

                    DamageLabel.Text = $" " ; // THIS RESULTS IN SILENT ERROR IN EDITOR:   <C++ Error>    Condition "!is_accessible_from_caller_thread()" is true.
            };

Can someone please add some additional documentation that C# events MAY cause issues and how to fix them. I used your fix and it worked:

            var damageLabelTimer = new System.Timers.Timer(2000);
            damageLabelTimer.Elapsed += (sender, args) => 
            {         
                Callable.From(() =>       
                    DamageLabel.Text = $" " ; // THIS WORKS 
                }).CallDeferred();
            };

The error is quite sneaky, I mostly searched for bugs regarding Label control but it is not directly related to Label control at all.
