### ISSUE TITLE
Nine patch rect doesn't update when texture atlas region is updated

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#78210]
### Godot version

v4.1.beta1.mono.official [828ec2c5d]

### System information

Kubuntu 22.04 Compatability

### Issue description

As funky as it sounds I tried using a atlas texture as the texture for a nice patch and discovered that the nine patch is not updated in the scene when the atlas texture region is changed 

### Steps to reproduce

- Add a altas texture to the nice patch node
- Mess with the atlas texture's region property (not the nice slices region property)
- See it doesn't update in the scene

### Minimal reproduction project

I will upload one if needed as it stand it seems like a very simple thing to reproduce

**Comment by Calinou** [comment]
@Shadowblitz16 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by AThousandShips** [comment]
This is because of a lack of signal connection for texture there, will look into a fix later today hopefully

**Comment by Shadowblitz16** [comment]
[NinePatchBug.zip](https://github.com/godotengine/godot/files/11750153/NinePatchBug.zip)
