### ISSUE TITLE
Cannot set filter/repeat mode for uniform arrays of Sampler2Ds

### ISSUE THREAD

**Issue by Haydoggo** [godotengine/godot#78213]
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Godot v4.0.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1080 (NVIDIA; 31.0.15.1694) - Intel(R) Core(TM) i5-10600KF CPU @ 4.10GHz (12 Threads)

### Issue description

There is no way to set the filter or repeat mode of a sampler2D array, trying to do so using shader hints `filter_nearest`/`filter_linear` or `repeat_enable`/`repeat_disable` results in an error:
`error(3): This hint is not supported for uniform arrays.`

Note: not a duplicate of #62472, which applies to `sampler2DArray`s, but not arrays of `sampler2D`s

### Steps to reproduce

```
shader_type spatial;

uniform sampler2D[8] textures : source_color, filter_nearest;
```

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
After removing this code, the hint works as expected:
https://github.com/godotengine/godot/blob/d28f9afdc63714cffa0df2fb5e749bf1bc6666ac/servers/rendering/shader_language.cpp#L8614-L8619
Looks like artificial limitation. Which exactly hints are not supported?

**Comment by Haydoggo** [comment]
Hmm interesting. From some testing with that code removed, here's what I've found works on uniform arrays of sampler2D:

|Hint||
|-|-|
|`source_color`|✔|
|`repeat[_enable, _disable]`|✔|
|`filter[_nearest, _linear][_mipmap][_anisotropic]`|✔|
|`hint_anisotropy`|❔ Not sure how to check, but doesn't cause any issues|
|`hint_roughness[_r, _g, _b, _a, _normal, _gray]`|❔ Not sure how to check, but doesn't cause any issues|
|`hint_normal`|❔ Not sure how to check, but doesn't cause any issues|
|`hint_default_white`|❔ maybe? this is default behaviour anyway|
|`hint_default_black`|❌ shows default white|
|`hint_default_white`|❌ shows default white|
|`hint_screen_texture`|❌ Hangs the editor|
|`hint_depth_texture`|❌ Hangs the editor|
|`hint_normal_roughness_texture`|❌ Hangs the editor|

tested by visually comparing the effects of each hint on the single texture vs the texture array with this shader
```
shader_type spatial;

uniform sampler2D single_texture: source_color;
uniform sampler2D[2] textures: source_color;

void fragment() {
	if (UV.x >= UV.y){
		ALBEDO = texture(single_texture, UV*2.0).rgb;
		ALPHA = texture(single_texture, UV*2.0).a;
	} else {
		int index = int((UV.x + UV.y)<1.0);
		ALBEDO = texture(textures[index], UV*2.0).rgb;
		ALPHA = texture(textures[index], UV*2.0).a;
	}
}
```
