### ISSUE TITLE
Support 1024 width resolution in scrip view, possibly others (1024x768)

### ISSUE THREAD

**Issue by qubodup** [godotengine/godot#7822]
Windows 7, Godot 2.1

I use Godot during game design workshops. Only a 1024x768 projector is available unfortunately.

It would be beneficial to situations in which low definition display hardware is available only to be able to still use Godot properly.

Most views seem to work fine at this resolution but opening a .gd file seems to lock the text view to a certain width, that blocks out the right side bar.

Please allow resizing the text widget, to support 1024 width.

I don´t know how to reproduce, but it appears that other views at times get locked into a minimal width in the center area, blocking out the right side bar. Please check if you can, wherther there are views/situations, in which the main viewport would not allow resizing to a size that would allow showing the right sidebar on a 1024 screen.

Thanks!
![1024width screenshot](https://cloud.githubusercontent.com/assets/18312/23018510/74425f42-f43e-11e6-870e-e3a30995e633.PNG)

**Comment by akien-mga** [comment]
I can confirm the issue, it would be nice to have min sizes defined as related to both the DPI and the screen resolution, so that we can have here e.g. the text editor configured to have a min size of 30%.

**Comment by kubecz3k** [comment]
I'm revisiting old issues and I believe this one is solved with some new options of 3.0, here is a screenshot which I made on this resolution in the script view after hidding script panel (`ctrl + \` and tree view ![full](https://user-images.githubusercontent.com/6129594/38573315-fde0c8fa-3cf5-11e8-8dab-5cbbfda58fff.png) )
![3zkz9wt](https://user-images.githubusercontent.com/6129594/38573335-11019e1e-3cf6-11e8-804d-262ff1db3cb8.png)
Please let us know if you think those improvements are not enough
