### ISSUE TITLE
Button's shorcut ignore button_group "allow_unpress" attribute

### ISSUE THREAD

**Issue by Wildos** [godotengine/godot#78224]
### Godot version

4.1.beta.custom_build.824c139f6

### System information

EndeavourOs - Linux kernel 6.3.7-arch1-1

### Issue description

Pressing a button through an associated shortcut allow to ignore the button group attribute "allow_unpress".
Button can then be unpressed

The button properly stay pressed when you click on it, the issue seem to only come from "clicking it" with the shortcut

### Steps to reproduce

- Create multiple buttons linked with the same button group
- Associate a shortcut to each button
- Use the shortcut to "press" the already selected button

### Minimal reproduction project

[button_group_shortcut.zip](https://github.com/godotengine/godot/files/11745281/button_group_shortcut.zip)

**Comment by Wildos** [comment]
The issue is caused by an if statement that filter and prevent the _unpress_group() call
File: scene/gui/base_button.cpp
Line: 369
```c++
			if (status.pressed) {
				_unpress_group();
				if (button_group.is_valid()) {
					button_group->emit_signal(SNAME("pressed"), this);
				}
			}
```
removing the if statement resolve the issue

Does anyone know why this condition was added?

**Comment by Sauermann** [comment]
> Does anyone know why this condition was added?

Looks like a simple oversight. I agree that this is the way to fix the bug, because the if statement is also not there in the `on_action_event` function.
