### ISSUE TITLE
Missing script that has exported `Array[Node]` make godot crash when opening the scene

### ISSUE THREAD

**Issue by ajreckof** [godotengine/godot#78238]
### Godot version

4.1.dev (4d5f10fc3a)

### System information

macOS 13.3.0 - Vulkan (Forward+) - integrated Apple M1 Pro - Apple M1 Pro (8 Threads)

### Issue description

When a script was attached to a node in a saved scene and this script is exporting a member typed with `Array[Node]` . Reopening the scene when the script is missing because it was deleted or moved will cause a crash

### Steps to reproduce

1. Create a scene with two nodes
2. attach a script to the root with just one exported member typed as `Array[Node]` 
3. Add both nodes to the exported member
4. Save the scene
5. close the scene 
6. Delete the script 
7. Try to open the scene again godot will crash 

### Minimal reproduction project

with the MRP you can start reproduction steps at the sixth step.
[Test.zip](https://github.com/godotengine/godot/files/11749000/Test.zip)

**Comment by adamscott** [comment]
CC @vonagam @dalexeev

**Comment by vonagam** [comment]
My guess (without looking) will be that this is connected to the complex issue of representation of an array of nodes in the editor. I think this issue - #62916 - references the most relevant pieces (other issues/past PRs). If that is the case then `topic:editor` tag is important and currently is missing.
