### ISSUE TITLE
Autoload scripts compile error are not reported (except confusing "Script does not inherit from Node")

### ISSUE THREAD

**Issue by idbrii** [godotengine/godot#78230]
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Win 10

### Issue description

When Autoload scripts have compile errors, the error is not printed to Output. Instead, they fail when Running with an error completely unrelated to what's wrong:

```
USER ERROR: Script does not inherit from Node: res://thetrouble.gd.
   at: start (main/main.cpp:2776)
```

There's no other information. I assume this message is because their failure to compile means they don't get associated as a Node child (related to #75388?)? But I don't understand why they don't have any errors reported. I think it only occurs if they were added to Autoload before they got compiled/used?

I am using an external editor (gvim) and godot's LSP support. That correctly shows the error, but only when I'm editing the broken file which makes it unclear what's wrong. (When I first encountered this problem, I looked at the files, saw they were extending Node2D and didn't understand the problem. It's possible the lsp was failing to show any errors, but it shows errors now.)

### Steps to reproduce

1. New project, add scene
2. Add script "thetrouble.gd"
3. Add thetrouble.gd as an Autoload
4. Add invalid code to thetrouble.gd (two variables named `seq`) 
  * **Expected**: compile error reported
  * **Actual**: No output
5. Run project
  * **Expected**: compile error reported
  * **Actual**: Script does not inherit from Node: res://thetrouble.gd.
6. Add valid code to thetrouble.gd (assign a value to `seq`) 
  * **Expected**: compile error reported
  * **Actual**: No output

Note: If you mix up steps 2 and 3, the issue will not occur.

Workaround: Edit Autoloads and disable and re-enable thetrouble's autoload state and error messages appear. New errors even appear after this point.

### Minimal reproduction project

[repro.zip](https://github.com/godotengine/godot/files/11747339/repro.zip)

**Comment by capnm** [comment]
On the current git tip you get:
([./editor/editor_autoload_settings.cpp:423](https://github.com/godotengine/godot/blob/c0d8d91b15597209a1ca865c6ff4f84f06f7de86/editor/editor_autoload_settings.cpp#LL423)) _create_autoload: 
	Script does not inherit from Node: res://thetrouble.gd.

**Comment by anvilfolk** [comment]
Step 4 is resulting in an error for me from within Godot:

![image](https://github.com/godotengine/godot/assets/1133892/06044134-6192-41df-96cd-4cd4b274e041)

I am getting the issue in Step 5 though:

![image](https://github.com/godotengine/godot/assets/1133892/d94ecbc8-7dbf-4c42-9885-8c99f0b3979f)

I'm not sure I understand what's wrong with 6 though. Valid code shouldn't result in a compile error!

Autoloads do seem to be loaded through the `ResourceLoader::load()` pathway, and apparently that's not resulting in errors being reported. Not sure why that would be though!

**Comment by Rindbee** [comment]
The following error message appears on the first run and does not reappear after that:
```
SCRIPT ERROR: Parse Error: Constant "seq" has the same name as a previously declared variable.
          at: GDScript::reload (res://thetrouble.gd:4)
```
It may have been cached.

**Comment by idbrii** [comment]
@anvilfolk :

**Comment by idbrii** [comment]
> I'm not sure I understand what's wrong with 6 though. Valid code shouldn't result in a compile error!

@anvilfolk There's still invalid code in the file, so I'd expect that modifying the file would recompile and re-emit the errors.

**Comment by OmarShehata** [comment]
FYI this issue affects any attached script, when using an external an editor, not just autoload. For example, if you attach a script with a mix of tabs/spaces, you'll get a meaningful error the first time you edit it:

```
  res://script.gd:5 - Parse Error: Used tab character for indentation instead of space as used before in the file.
```

But running the scene, you will only get the following runtime error which makes it difficult to figure out what went wrong

```
E 0:00:00:0754   start: Script does not inherit from Node: res://script.gd.
  <C++ Error>    Condition "!valid_type" is true. Continuing.
  <C++ Source>   main/main.cpp:3039 @ start()
```

**Comment by anvilfolk** [comment]
@OmarShehata can you check whether the issue in your last message is fixed in `master` now, and if not, please open a new issue with it since it's slightly different than the original one? :)
